Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 1
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43788, 12, 6)
Dimensiones de Y: (43788, 1)

In [16]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30651, 12, 6)
Las dimensiones de testX son:  (8801, 12, 6)
Las dimensiones de valX son:  (4336, 12, 6)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30651, 1)
Las dimensiones de testY son:  (8801, 1)
Las dimensiones de valY son:  (4336, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 15s - 61ms/step - ia: 0.3667 - loss: 1.6778 - mae: 0.9137 - rmse: 1.2839 - smape: 1.2401 - val_ia: 0.2625 - val_loss: 1.0516 - val_mae: 0.6821 - val_rmse: 0.8585 - val_smape: 1.1436

Epoch 2/128

240/240 - 4s - 18ms/step - ia: 0.2769 - loss: 1.1841 - mae: 0.7857 - rmse: 1.0817 - smape: 1.4268 - val_ia: 0.2438 - val_loss: 0.9651 - val_mae: 0.7147 - val_rmse: 0.8589 - val_smape: 1.6103

Epoch 3/128

240/240 - 4s - 17ms/step - ia: 0.2388 - loss: 1.1183 - mae: 0.7832 - rmse: 1.0510 - smape: 1.5025 - val_ia: 0.2491 - val_loss: 0.9631 - val_mae: 0.7286 - val_rmse: 0.8684 - val_smape: 1.8382

Epoch 4/128

240/240 - 4s - 16ms/step - ia: 0.2229 - loss: 1.0826 - mae: 0.7743 - rmse: 1.0346 - smape: 1.5284 - val_ia: 0.2505 - val_loss: 0.9596 - val_mae: 0.7274 - val_rmse: 0.8670 - val_smape: 1.8442

Epoch 5/128

240/240 - 4s - 18ms/step - ia: 0.2115 - loss: 1.0542 - mae: 0.7648 - rmse: 1.0203 - smape: 1.5458 - val_ia: 0.2534 - val_loss: 0.9537 - val_mae: 0.7267 - val_rmse: 0.8655 - val_smape: 1.8889

Epoch 6/128

240/240 - 4s - 17ms/step - ia: 0.1998 - loss: 1.0382 - mae: 0.7578 - rmse: 1.0129 - smape: 1.5627 - val_ia: 0.2581 - val_loss: 0.9419 - val_mae: 0.7229 - val_rmse: 0.8606 - val_smape: 1.8759

Epoch 7/128

240/240 - 5s - 22ms/step - ia: 0.1976 - loss: 1.0080 - mae: 0.7463 - rmse: 0.9982 - smape: 1.5668 - val_ia: 0.2666 - val_loss: 0.9162 - val_mae: 0.7096 - val_rmse: 0.8463 - val_smape: 1.7821

Epoch 8/128

240/240 - 4s - 17ms/step - ia: 0.2129 - loss: 0.9753 - mae: 0.7295 - rmse: 0.9806 - smape: 1.5366 - val_ia: 0.2822 - val_loss: 0.8726 - val_mae: 0.6845 - val_rmse: 0.8202 - val_smape: 1.6156

Epoch 9/128

240/240 - 4s - 17ms/step - ia: 0.2505 - loss: 0.9207 - mae: 0.7028 - rmse: 0.9530 - smape: 1.4742 - val_ia: 0.3086 - val_loss: 0.8110 - val_mae: 0.6502 - val_rmse: 0.7841 - val_smape: 1.4218

Epoch 10/128

240/240 - 5s - 22ms/step - ia: 0.3123 - loss: 0.8500 - mae: 0.6680 - rmse: 0.9157 - smape: 1.3710 - val_ia: 0.3509 - val_loss: 0.7309 - val_mae: 0.6045 - val_rmse: 0.7359 - val_smape: 1.2208

Epoch 11/128

240/240 - 5s - 21ms/step - ia: 0.3928 - loss: 0.7739 - mae: 0.6266 - rmse: 0.8717 - smape: 1.2403 - val_ia: 0.4111 - val_loss: 0.6398 - val_mae: 0.5484 - val_rmse: 0.6780 - val_smape: 1.0329

Epoch 12/128

240/240 - 4s - 17ms/step - ia: 0.4691 - loss: 0.7045 - mae: 0.5889 - rmse: 0.8317 - smape: 1.1193 - val_ia: 0.4724 - val_loss: 0.5527 - val_mae: 0.4985 - val_rmse: 0.6256 - val_smape: 0.9022

Epoch 13/128

240/240 - 4s - 17ms/step - ia: 0.5318 - loss: 0.6370 - mae: 0.5552 - rmse: 0.7904 - smape: 1.0272 - val_ia: 0.5170 - val_loss: 0.4817 - val_mae: 0.4561 - val_rmse: 0.5801 - val_smape: 0.8159

Epoch 14/128

240/240 - 4s - 17ms/step - ia: 0.5667 - loss: 0.5925 - mae: 0.5352 - rmse: 0.7628 - smape: 0.9779 - val_ia: 0.5557 - val_loss: 0.4279 - val_mae: 0.4260 - val_rmse: 0.5466 - val_smape: 0.7640

Epoch 15/128

240/240 - 4s - 17ms/step - ia: 0.5927 - loss: 0.5530 - mae: 0.5171 - rmse: 0.7379 - smape: 0.9438 - val_ia: 0.5758 - val_loss: 0.3896 - val_mae: 0.4058 - val_rmse: 0.5224 - val_smape: 0.7336

Epoch 16/128

240/240 - 5s - 22ms/step - ia: 0.6060 - loss: 0.5283 - mae: 0.5071 - rmse: 0.7202 - smape: 0.9296 - val_ia: 0.5941 - val_loss: 0.3613 - val_mae: 0.3884 - val_rmse: 0.5030 - val_smape: 0.7088

Epoch 17/128

240/240 - 5s - 21ms/step - ia: 0.6222 - loss: 0.5017 - mae: 0.4929 - rmse: 0.7020 - smape: 0.9068 - val_ia: 0.6030 - val_loss: 0.3386 - val_mae: 0.3776 - val_rmse: 0.4891 - val_smape: 0.6991

Epoch 18/128

240/240 - 5s - 22ms/step - ia: 0.6315 - loss: 0.4807 - mae: 0.4844 - rmse: 0.6867 - smape: 0.8935 - val_ia: 0.6131 - val_loss: 0.3198 - val_mae: 0.3665 - val_rmse: 0.4759 - val_smape: 0.6865

Epoch 19/128

240/240 - 4s - 18ms/step - ia: 0.6386 - loss: 0.4678 - mae: 0.4760 - rmse: 0.6774 - smape: 0.8863 - val_ia: 0.6209 - val_loss: 0.3027 - val_mae: 0.3574 - val_rmse: 0.4646 - val_smape: 0.6771

Epoch 20/128

240/240 - 4s - 17ms/step - ia: 0.6471 - loss: 0.4504 - mae: 0.4688 - rmse: 0.6631 - smape: 0.8730 - val_ia: 0.6249 - val_loss: 0.2902 - val_mae: 0.3504 - val_rmse: 0.4559 - val_smape: 0.6722

Epoch 21/128

240/240 - 4s - 18ms/step - ia: 0.6504 - loss: 0.4418 - mae: 0.4632 - rmse: 0.6580 - smape: 0.8726 - val_ia: 0.6342 - val_loss: 0.2772 - val_mae: 0.3426 - val_rmse: 0.4468 - val_smape: 0.6614

Epoch 22/128

240/240 - 4s - 18ms/step - ia: 0.6596 - loss: 0.4225 - mae: 0.4528 - rmse: 0.6437 - smape: 0.8547 - val_ia: 0.6429 - val_loss: 0.2634 - val_mae: 0.3340 - val_rmse: 0.4368 - val_smape: 0.6500

Epoch 23/128

240/240 - 4s - 19ms/step - ia: 0.6608 - loss: 0.4183 - mae: 0.4524 - rmse: 0.6401 - smape: 0.8570 - val_ia: 0.6470 - val_loss: 0.2543 - val_mae: 0.3288 - val_rmse: 0.4303 - val_smape: 0.6446

Epoch 24/128

240/240 - 5s - 21ms/step - ia: 0.6673 - loss: 0.4091 - mae: 0.4445 - rmse: 0.6325 - smape: 0.8493 - val_ia: 0.6538 - val_loss: 0.2452 - val_mae: 0.3228 - val_rmse: 0.4234 - val_smape: 0.6362

Epoch 25/128

240/240 - 5s - 21ms/step - ia: 0.6742 - loss: 0.3922 - mae: 0.4363 - rmse: 0.6194 - smape: 0.8387 - val_ia: 0.6627 - val_loss: 0.2350 - val_mae: 0.3158 - val_rmse: 0.4155 - val_smape: 0.6243

Epoch 26/128

240/240 - 4s - 17ms/step - ia: 0.6753 - loss: 0.3966 - mae: 0.4348 - rmse: 0.6221 - smape: 0.8335 - val_ia: 0.6653 - val_loss: 0.2308 - val_mae: 0.3121 - val_rmse: 0.4116 - val_smape: 0.6194

Epoch 27/128

240/240 - 4s - 17ms/step - ia: 0.6792 - loss: 0.3860 - mae: 0.4299 - rmse: 0.6146 - smape: 0.8270 - val_ia: 0.6758 - val_loss: 0.2209 - val_mae: 0.3044 - val_rmse: 0.4034 - val_smape: 0.6057

Epoch 28/128

240/240 - 5s - 21ms/step - ia: 0.6823 - loss: 0.3809 - mae: 0.4268 - rmse: 0.6105 - smape: 0.8229 - val_ia: 0.6816 - val_loss: 0.2151 - val_mae: 0.2999 - val_rmse: 0.3986 - val_smape: 0.5970

Epoch 29/128

240/240 - 5s - 23ms/step - ia: 0.6851 - loss: 0.3729 - mae: 0.4240 - rmse: 0.6033 - smape: 0.8194 - val_ia: 0.6814 - val_loss: 0.2112 - val_mae: 0.2991 - val_rmse: 0.3968 - val_smape: 0.5984

Epoch 30/128

240/240 - 4s - 17ms/step - ia: 0.6904 - loss: 0.3636 - mae: 0.4169 - rmse: 0.5964 - smape: 0.8055 - val_ia: 0.6924 - val_loss: 0.2028 - val_mae: 0.2905 - val_rmse: 0.3883 - val_smape: 0.5837

Epoch 31/128

240/240 - 4s - 18ms/step - ia: 0.6937 - loss: 0.3576 - mae: 0.4131 - rmse: 0.5913 - smape: 0.8041 - val_ia: 0.6895 - val_loss: 0.2011 - val_mae: 0.2918 - val_rmse: 0.3885 - val_smape: 0.5876

Epoch 32/128

240/240 - 4s - 17ms/step - ia: 0.6951 - loss: 0.3541 - mae: 0.4118 - rmse: 0.5890 - smape: 0.8024 - val_ia: 0.6948 - val_loss: 0.1957 - val_mae: 0.2875 - val_rmse: 0.3838 - val_smape: 0.5810

Epoch 33/128

240/240 - 4s - 17ms/step - ia: 0.6950 - loss: 0.3565 - mae: 0.4101 - rmse: 0.5894 - smape: 0.8021 - val_ia: 0.6997 - val_loss: 0.1917 - val_mae: 0.2839 - val_rmse: 0.3800 - val_smape: 0.5761

Epoch 34/128

240/240 - 5s - 21ms/step - ia: 0.7003 - loss: 0.3459 - mae: 0.4049 - rmse: 0.5818 - smape: 0.7954 - val_ia: 0.7033 - val_loss: 0.1878 - val_mae: 0.2807 - val_rmse: 0.3764 - val_smape: 0.5722

Epoch 35/128

240/240 - 4s - 17ms/step - ia: 0.7028 - loss: 0.3409 - mae: 0.4031 - rmse: 0.5771 - smape: 0.7883 - val_ia: 0.7000 - val_loss: 0.1864 - val_mae: 0.2818 - val_rmse: 0.3762 - val_smape: 0.5760

Epoch 36/128

240/240 - 4s - 18ms/step - ia: 0.7022 - loss: 0.3469 - mae: 0.4021 - rmse: 0.5815 - smape: 0.7864 - val_ia: 0.7069 - val_loss: 0.1818 - val_mae: 0.2774 - val_rmse: 0.3719 - val_smape: 0.5696

Epoch 37/128

240/240 - 4s - 18ms/step - ia: 0.7055 - loss: 0.3341 - mae: 0.3991 - rmse: 0.5716 - smape: 0.7839 - val_ia: 0.7069 - val_loss: 0.1789 - val_mae: 0.2767 - val_rmse: 0.3705 - val_smape: 0.5694

Epoch 38/128

240/240 - 5s - 22ms/step - ia: 0.7048 - loss: 0.3348 - mae: 0.3995 - rmse: 0.5718 - smape: 0.7882 - val_ia: 0.7089 - val_loss: 0.1764 - val_mae: 0.2747 - val_rmse: 0.3680 - val_smape: 0.5680

Epoch 39/128

240/240 - 4s - 17ms/step - ia: 0.7072 - loss: 0.3335 - mae: 0.3956 - rmse: 0.5705 - smape: 0.7791 - val_ia: 0.7101 - val_loss: 0.1734 - val_mae: 0.2733 - val_rmse: 0.3660 - val_smape: 0.5676

Epoch 40/128

240/240 - 4s - 18ms/step - ia: 0.7101 - loss: 0.3244 - mae: 0.3923 - rmse: 0.5627 - smape: 0.7759 - val_ia: 0.7147 - val_loss: 0.1685 - val_mae: 0.2694 - val_rmse: 0.3615 - val_smape: 0.5633

Epoch 41/128

240/240 - 4s - 18ms/step - ia: 0.7091 - loss: 0.3259 - mae: 0.3930 - rmse: 0.5634 - smape: 0.7793 - val_ia: 0.7147 - val_loss: 0.1671 - val_mae: 0.2689 - val_rmse: 0.3606 - val_smape: 0.5631

Epoch 42/128

240/240 - 5s - 21ms/step - ia: 0.7115 - loss: 0.3240 - mae: 0.3902 - rmse: 0.5623 - smape: 0.7730 - val_ia: 0.7154 - val_loss: 0.1644 - val_mae: 0.2681 - val_rmse: 0.3593 - val_smape: 0.5646

Epoch 43/128

240/240 - 4s - 18ms/step - ia: 0.7143 - loss: 0.3198 - mae: 0.3879 - rmse: 0.5587 - smape: 0.7676 - val_ia: 0.7177 - val_loss: 0.1622 - val_mae: 0.2660 - val_rmse: 0.3567 - val_smape: 0.5607

Epoch 44/128

240/240 - 5s - 21ms/step - ia: 0.7140 - loss: 0.3197 - mae: 0.3875 - rmse: 0.5595 - smape: 0.7686 - val_ia: 0.7153 - val_loss: 0.1613 - val_mae: 0.2670 - val_rmse: 0.3571 - val_smape: 0.5643

Epoch 45/128

240/240 - 4s - 18ms/step - ia: 0.7182 - loss: 0.3133 - mae: 0.3832 - rmse: 0.5538 - smape: 0.7643 - val_ia: 0.7194 - val_loss: 0.1591 - val_mae: 0.2636 - val_rmse: 0.3536 - val_smape: 0.5561

Epoch 46/128

240/240 - 5s - 21ms/step - ia: 0.7176 - loss: 0.3130 - mae: 0.3829 - rmse: 0.5531 - smape: 0.7625 - val_ia: 0.7167 - val_loss: 0.1593 - val_mae: 0.2663 - val_rmse: 0.3562 - val_smape: 0.5671

Epoch 47/128

240/240 - 5s - 22ms/step - ia: 0.7188 - loss: 0.3118 - mae: 0.3814 - rmse: 0.5523 - smape: 0.7600 - val_ia: 0.7212 - val_loss: 0.1559 - val_mae: 0.2619 - val_rmse: 0.3514 - val_smape: 0.5565

Epoch 48/128

240/240 - 5s - 21ms/step - ia: 0.7220 - loss: 0.3045 - mae: 0.3780 - rmse: 0.5458 - smape: 0.7557 - val_ia: 0.7173 - val_loss: 0.1562 - val_mae: 0.2645 - val_rmse: 0.3533 - val_smape: 0.5631

Epoch 49/128

240/240 - 4s - 18ms/step - ia: 0.7198 - loss: 0.3067 - mae: 0.3804 - rmse: 0.5470 - smape: 0.7577 - val_ia: 0.7161 - val_loss: 0.1552 - val_mae: 0.2651 - val_rmse: 0.3533 - val_smape: 0.5668

Epoch 50/128

240/240 - 4s - 17ms/step - ia: 0.7223 - loss: 0.3046 - mae: 0.3776 - rmse: 0.5442 - smape: 0.7522 - val_ia: 0.7220 - val_loss: 0.1523 - val_mae: 0.2606 - val_rmse: 0.3491 - val_smape: 0.5561

Epoch 51/128

240/240 - 6s - 23ms/step - ia: 0.7247 - loss: 0.2982 - mae: 0.3741 - rmse: 0.5390 - smape: 0.7481 - val_ia: 0.7202 - val_loss: 0.1516 - val_mae: 0.2623 - val_rmse: 0.3503 - val_smape: 0.5649

Epoch 52/128

240/240 - 5s - 21ms/step - ia: 0.7238 - loss: 0.3049 - mae: 0.3751 - rmse: 0.5454 - smape: 0.7471 - val_ia: 0.7223 - val_loss: 0.1490 - val_mae: 0.2596 - val_rmse: 0.3470 - val_smape: 0.5585

Epoch 53/128

240/240 - 4s - 18ms/step - ia: 0.7247 - loss: 0.2965 - mae: 0.3742 - rmse: 0.5391 - smape: 0.7514 - val_ia: 0.7214 - val_loss: 0.1497 - val_mae: 0.2606 - val_rmse: 0.3482 - val_smape: 0.5599

Epoch 54/128

240/240 - 5s - 22ms/step - ia: 0.7259 - loss: 0.2995 - mae: 0.3727 - rmse: 0.5406 - smape: 0.7465 - val_ia: 0.7247 - val_loss: 0.1470 - val_mae: 0.2581 - val_rmse: 0.3454 - val_smape: 0.5575

Epoch 55/128

240/240 - 4s - 17ms/step - ia: 0.7258 - loss: 0.2957 - mae: 0.3731 - rmse: 0.5377 - smape: 0.7470 - val_ia: 0.7253 - val_loss: 0.1462 - val_mae: 0.2569 - val_rmse: 0.3439 - val_smape: 0.5524

Epoch 56/128

240/240 - 4s - 17ms/step - ia: 0.7256 - loss: 0.2997 - mae: 0.3730 - rmse: 0.5393 - smape: 0.7435 - val_ia: 0.7214 - val_loss: 0.1467 - val_mae: 0.2596 - val_rmse: 0.3462 - val_smape: 0.5608

Epoch 57/128

240/240 - 4s - 15ms/step - ia: 0.7264 - loss: 0.2938 - mae: 0.3717 - rmse: 0.5353 - smape: 0.7440 - val_ia: 0.7178 - val_loss: 0.1487 - val_mae: 0.2630 - val_rmse: 0.3497 - val_smape: 0.5694

Epoch 58/128

240/240 - 5s - 21ms/step - ia: 0.7284 - loss: 0.2990 - mae: 0.3694 - rmse: 0.5389 - smape: 0.7391 - val_ia: 0.7260 - val_loss: 0.1443 - val_mae: 0.2560 - val_rmse: 0.3425 - val_smape: 0.5511

Epoch 59/128

240/240 - 3s - 13ms/step - ia: 0.7282 - loss: 0.2895 - mae: 0.3694 - rmse: 0.5316 - smape: 0.7427 - val_ia: 0.7272 - val_loss: 0.1420 - val_mae: 0.2545 - val_rmse: 0.3406 - val_smape: 0.5509

Epoch 60/128

240/240 - 7s - 28ms/step - ia: 0.7298 - loss: 0.2903 - mae: 0.3676 - rmse: 0.5329 - smape: 0.7409 - val_ia: 0.7258 - val_loss: 0.1415 - val_mae: 0.2549 - val_rmse: 0.3406 - val_smape: 0.5516

Epoch 61/128

240/240 - 5s - 23ms/step - ia: 0.7322 - loss: 0.2859 - mae: 0.3646 - rmse: 0.5280 - smape: 0.7361 - val_ia: 0.7249 - val_loss: 0.1420 - val_mae: 0.2564 - val_rmse: 0.3419 - val_smape: 0.5552

Epoch 62/128

240/240 - 5s - 21ms/step - ia: 0.7303 - loss: 0.2909 - mae: 0.3670 - rmse: 0.5326 - smape: 0.7379 - val_ia: 0.7264 - val_loss: 0.1404 - val_mae: 0.2550 - val_rmse: 0.3403 - val_smape: 0.5546

Epoch 63/128

240/240 - 5s - 20ms/step - ia: 0.7330 - loss: 0.2811 - mae: 0.3644 - rmse: 0.5240 - smape: 0.7353 - val_ia: 0.7313 - val_loss: 0.1359 - val_mae: 0.2498 - val_rmse: 0.3347 - val_smape: 0.5443

Epoch 64/128

240/240 - 5s - 21ms/step - ia: 0.7359 - loss: 0.2803 - mae: 0.3608 - rmse: 0.5221 - smape: 0.7275 - val_ia: 0.7301 - val_loss: 0.1378 - val_mae: 0.2520 - val_rmse: 0.3372 - val_smape: 0.5495

Epoch 65/128

240/240 - 5s - 21ms/step - ia: 0.7352 - loss: 0.2831 - mae: 0.3614 - rmse: 0.5251 - smape: 0.7281 - val_ia: 0.7277 - val_loss: 0.1374 - val_mae: 0.2531 - val_rmse: 0.3377 - val_smape: 0.5529

Epoch 66/128

240/240 - 5s - 22ms/step - ia: 0.7340 - loss: 0.2815 - mae: 0.3625 - rmse: 0.5243 - smape: 0.7325 - val_ia: 0.7284 - val_loss: 0.1369 - val_mae: 0.2525 - val_rmse: 0.3371 - val_smape: 0.5512

Epoch 67/128

240/240 - 5s - 20ms/step - ia: 0.7353 - loss: 0.2767 - mae: 0.3609 - rmse: 0.5206 - smape: 0.7321 - val_ia: 0.7280 - val_loss: 0.1361 - val_mae: 0.2527 - val_rmse: 0.3367 - val_smape: 0.5516

Epoch 68/128

240/240 - 5s - 21ms/step - ia: 0.7365 - loss: 0.2781 - mae: 0.3595 - rmse: 0.5207 - smape: 0.7250 - val_ia: 0.7293 - val_loss: 0.1359 - val_mae: 0.2517 - val_rmse: 0.3356 - val_smape: 0.5476

Epoch 69/128

240/240 - 4s - 17ms/step - ia: 0.7382 - loss: 0.2751 - mae: 0.3573 - rmse: 0.5182 - smape: 0.7219 - val_ia: 0.7323 - val_loss: 0.1314 - val_mae: 0.2477 - val_rmse: 0.3310 - val_smape: 0.5445

Epoch 70/128

240/240 - 4s - 18ms/step - ia: 0.7366 - loss: 0.2733 - mae: 0.3587 - rmse: 0.5165 - smape: 0.7311 - val_ia: 0.7333 - val_loss: 0.1344 - val_mae: 0.2488 - val_rmse: 0.3329 - val_smape: 0.5404

Epoch 71/128

240/240 - 5s - 21ms/step - ia: 0.7385 - loss: 0.2720 - mae: 0.3568 - rmse: 0.5154 - smape: 0.7228 - val_ia: 0.7247 - val_loss: 0.1343 - val_mae: 0.2535 - val_rmse: 0.3360 - val_smape: 0.5558

Epoch 72/128

240/240 - 5s - 21ms/step - ia: 0.7395 - loss: 0.2750 - mae: 0.3557 - rmse: 0.5172 - smape: 0.7218 - val_ia: 0.7315 - val_loss: 0.1320 - val_mae: 0.2493 - val_rmse: 0.3324 - val_smape: 0.5491

Epoch 73/128

240/240 - 5s - 21ms/step - ia: 0.7381 - loss: 0.2770 - mae: 0.3578 - rmse: 0.5203 - smape: 0.7239 - val_ia: 0.7225 - val_loss: 0.1350 - val_mae: 0.2554 - val_rmse: 0.3377 - val_smape: 0.5606

Epoch 74/128

240/240 - 5s - 21ms/step - ia: 0.7379 - loss: 0.2774 - mae: 0.3575 - rmse: 0.5195 - smape: 0.7233 - val_ia: 0.7235 - val_loss: 0.1374 - val_mae: 0.2562 - val_rmse: 0.3390 - val_smape: 0.5549

Epoch 75/128

240/240 - 5s - 20ms/step - ia: 0.7388 - loss: 0.2762 - mae: 0.3566 - rmse: 0.5190 - smape: 0.7199 - val_ia: 0.7295 - val_loss: 0.1320 - val_mae: 0.2503 - val_rmse: 0.3327 - val_smape: 0.5484

Epoch 76/128

240/240 - 5s - 20ms/step - ia: 0.7388 - loss: 0.2709 - mae: 0.3570 - rmse: 0.5145 - smape: 0.7234 - val_ia: 0.7297 - val_loss: 0.1296 - val_mae: 0.2490 - val_rmse: 0.3306 - val_smape: 0.5493

Epoch 77/128

240/240 - 5s - 22ms/step - ia: 0.7385 - loss: 0.2740 - mae: 0.3559 - rmse: 0.5173 - smape: 0.7248 - val_ia: 0.7286 - val_loss: 0.1317 - val_mae: 0.2509 - val_rmse: 0.3328 - val_smape: 0.5493

Epoch 78/128

240/240 - 5s - 21ms/step - ia: 0.7391 - loss: 0.2755 - mae: 0.3560 - rmse: 0.5175 - smape: 0.7202 - val_ia: 0.7293 - val_loss: 0.1283 - val_mae: 0.2493 - val_rmse: 0.3302 - val_smape: 0.5529

Epoch 79/128

240/240 - 5s - 21ms/step - ia: 0.7395 - loss: 0.2719 - mae: 0.3560 - rmse: 0.5144 - smape: 0.7249 - val_ia: 0.7282 - val_loss: 0.1309 - val_mae: 0.2511 - val_rmse: 0.3325 - val_smape: 0.5511

Epoch 80/128

240/240 - 4s - 16ms/step - ia: 0.7415 - loss: 0.2720 - mae: 0.3535 - rmse: 0.5142 - smape: 0.7138 - val_ia: 0.7305 - val_loss: 0.1284 - val_mae: 0.2485 - val_rmse: 0.3295 - val_smape: 0.5486

Epoch 81/128

240/240 - 3s - 13ms/step - ia: 0.7404 - loss: 0.2704 - mae: 0.3543 - rmse: 0.5132 - smape: 0.7218 - val_ia: 0.7280 - val_loss: 0.1267 - val_mae: 0.2488 - val_rmse: 0.3290 - val_smape: 0.5542

Epoch 82/128

240/240 - 3s - 12ms/step - ia: 0.7411 - loss: 0.2691 - mae: 0.3529 - rmse: 0.5119 - smape: 0.7205 - val_ia: 0.7238 - val_loss: 0.1314 - val_mae: 0.2543 - val_rmse: 0.3350 - val_smape: 0.5624

Epoch 83/128

240/240 - 3s - 12ms/step - ia: 0.7406 - loss: 0.2724 - mae: 0.3543 - rmse: 0.5151 - smape: 0.7173 - val_ia: 0.7331 - val_loss: 0.1239 - val_mae: 0.2446 - val_rmse: 0.3250 - val_smape: 0.5465

Epoch 84/128

240/240 - 3s - 12ms/step - ia: 0.7429 - loss: 0.2685 - mae: 0.3506 - rmse: 0.5106 - smape: 0.7149 - val_ia: 0.7267 - val_loss: 0.1264 - val_mae: 0.2496 - val_rmse: 0.3294 - val_smape: 0.5570

Epoch 85/128

240/240 - 3s - 12ms/step - ia: 0.7420 - loss: 0.2701 - mae: 0.3522 - rmse: 0.5131 - smape: 0.7163 - val_ia: 0.7243 - val_loss: 0.1286 - val_mae: 0.2519 - val_rmse: 0.3315 - val_smape: 0.5566

Epoch 86/128

240/240 - 3s - 12ms/step - ia: 0.7437 - loss: 0.2668 - mae: 0.3499 - rmse: 0.5095 - smape: 0.7109 - val_ia: 0.7255 - val_loss: 0.1272 - val_mae: 0.2510 - val_rmse: 0.3303 - val_smape: 0.5586

Epoch 87/128

240/240 - 3s - 13ms/step - ia: 0.7432 - loss: 0.2696 - mae: 0.3506 - rmse: 0.5122 - smape: 0.7143 - val_ia: 0.7281 - val_loss: 0.1254 - val_mae: 0.2488 - val_rmse: 0.3281 - val_smape: 0.5563

Epoch 88/128

240/240 - 3s - 13ms/step - ia: 0.7454 - loss: 0.2683 - mae: 0.3484 - rmse: 0.5108 - smape: 0.7072 - val_ia: 0.7229 - val_loss: 0.1284 - val_mae: 0.2532 - val_rmse: 0.3324 - val_smape: 0.5638

Epoch 89/128

240/240 - 3s - 12ms/step - ia: 0.7449 - loss: 0.2649 - mae: 0.3486 - rmse: 0.5086 - smape: 0.7109 - val_ia: 0.7266 - val_loss: 0.1262 - val_mae: 0.2497 - val_rmse: 0.3289 - val_smape: 0.5567

Epoch 90/128

240/240 - 3s - 12ms/step - ia: 0.7450 - loss: 0.2617 - mae: 0.3478 - rmse: 0.5052 - smape: 0.7161 - val_ia: 0.7360 - val_loss: 0.1220 - val_mae: 0.2425 - val_rmse: 0.3225 - val_smape: 0.5429

Epoch 91/128

240/240 - 4s - 16ms/step - ia: 0.7438 - loss: 0.2688 - mae: 0.3501 - rmse: 0.5114 - smape: 0.7104 - val_ia: 0.7290 - val_loss: 0.1243 - val_mae: 0.2474 - val_rmse: 0.3263 - val_smape: 0.5517

Epoch 92/128

240/240 - 5s - 20ms/step - ia: 0.7439 - loss: 0.2656 - mae: 0.3495 - rmse: 0.5085 - smape: 0.7153 - val_ia: 0.7306 - val_loss: 0.1232 - val_mae: 0.2462 - val_rmse: 0.3247 - val_smape: 0.5498

Epoch 93/128

240/240 - 5s - 22ms/step - ia: 0.7459 - loss: 0.2673 - mae: 0.3470 - rmse: 0.5098 - smape: 0.7064 - val_ia: 0.7303 - val_loss: 0.1219 - val_mae: 0.2454 - val_rmse: 0.3237 - val_smape: 0.5502

Epoch 94/128

240/240 - 5s - 20ms/step - ia: 0.7474 - loss: 0.2603 - mae: 0.3454 - rmse: 0.5035 - smape: 0.7068 - val_ia: 0.7272 - val_loss: 0.1224 - val_mae: 0.2478 - val_rmse: 0.3256 - val_smape: 0.5582

Epoch 95/128

240/240 - 5s - 21ms/step - ia: 0.7467 - loss: 0.2615 - mae: 0.3455 - rmse: 0.5053 - smape: 0.7056 - val_ia: 0.7285 - val_loss: 0.1217 - val_mae: 0.2468 - val_rmse: 0.3247 - val_smape: 0.5558

Epoch 96/128

240/240 - 5s - 21ms/step - ia: 0.7461 - loss: 0.2613 - mae: 0.3471 - rmse: 0.5044 - smape: 0.7098 - val_ia: 0.7283 - val_loss: 0.1225 - val_mae: 0.2473 - val_rmse: 0.3253 - val_smape: 0.5542

Epoch 97/128

240/240 - 5s - 21ms/step - ia: 0.7462 - loss: 0.2620 - mae: 0.3472 - rmse: 0.5053 - smape: 0.7068 - val_ia: 0.7267 - val_loss: 0.1243 - val_mae: 0.2491 - val_rmse: 0.3272 - val_smape: 0.5544

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 45s - 24ms/step - ia: 0.8544 - loss: 0.1037 - mae: 0.1925 - rmse: 0.2817 - smape: 0.4592 - val_ia: 0.6359 - val_loss: 0.0935 - val_mae: 0.1792 - val_rmse: 0.2375 - val_smape: 0.3846

Epoch 2/128

1916/1916 - 48s - 25ms/step - ia: 0.8890 - loss: 0.0669 - mae: 0.1512 - rmse: 0.2288 - smape: 0.3771 - val_ia: 0.6664 - val_loss: 0.0577 - val_mae: 0.1413 - val_rmse: 0.1927 - val_smape: 0.3683

Epoch 3/128

1916/1916 - 37s - 20ms/step - ia: 0.8920 - loss: 0.0661 - mae: 0.1480 - rmse: 0.2267 - smape: 0.3681 - val_ia: 0.6839 - val_loss: 0.0535 - val_mae: 0.1321 - val_rmse: 0.1835 - val_smape: 0.3543

Epoch 4/128

1916/1916 - 52s - 27ms/step - ia: 0.8925 - loss: 0.0643 - mae: 0.1467 - rmse: 0.2242 - smape: 0.3665 - val_ia: 0.6792 - val_loss: 0.0555 - val_mae: 0.1360 - val_rmse: 0.1873 - val_smape: 0.3554

Epoch 5/128

1916/1916 - 63s - 33ms/step - ia: 0.8937 - loss: 0.0639 - mae: 0.1451 - rmse: 0.2224 - smape: 0.3658 - val_ia: 0.6598 - val_loss: 0.0566 - val_mae: 0.1412 - val_rmse: 0.1926 - val_smape: 0.3709

Epoch 6/128

1916/1916 - 46s - 24ms/step - ia: 0.8948 - loss: 0.0623 - mae: 0.1436 - rmse: 0.2212 - smape: 0.3627 - val_ia: 0.6396 - val_loss: 0.0593 - val_mae: 0.1501 - val_rmse: 0.1992 - val_smape: 0.3803

Epoch 7/128

1916/1916 - 50s - 26ms/step - ia: 0.8940 - loss: 0.0619 - mae: 0.1443 - rmse: 0.2200 - smape: 0.3641 - val_ia: 0.6956 - val_loss: 0.0528 - val_mae: 0.1308 - val_rmse: 0.1829 - val_smape: 0.3511

Epoch 8/128

1916/1916 - 78s - 41ms/step - ia: 0.8962 - loss: 0.0611 - mae: 0.1420 - rmse: 0.2178 - smape: 0.3601 - val_ia: 0.7017 - val_loss: 0.0520 - val_mae: 0.1277 - val_rmse: 0.1805 - val_smape: 0.3475

Epoch 9/128

1916/1916 - 37s - 19ms/step - ia: 0.8958 - loss: 0.0606 - mae: 0.1423 - rmse: 0.2173 - smape: 0.3623 - val_ia: 0.6845 - val_loss: 0.0522 - val_mae: 0.1310 - val_rmse: 0.1837 - val_smape: 0.3527

Epoch 10/128

1916/1916 - 55s - 29ms/step - ia: 0.8960 - loss: 0.0600 - mae: 0.1410 - rmse: 0.2167 - smape: 0.3588 - val_ia: 0.6812 - val_loss: 0.0557 - val_mae: 0.1337 - val_rmse: 0.1878 - val_smape: 0.3614

Epoch 11/128

1916/1916 - 83s - 43ms/step - ia: 0.8962 - loss: 0.0593 - mae: 0.1411 - rmse: 0.2160 - smape: 0.3590 - val_ia: 0.6822 - val_loss: 0.0579 - val_mae: 0.1408 - val_rmse: 0.1912 - val_smape: 0.3652

Epoch 12/128

1916/1916 - 36s - 19ms/step - ia: 0.8977 - loss: 0.0588 - mae: 0.1399 - rmse: 0.2147 - smape: 0.3574 - val_ia: 0.7079 - val_loss: 0.0515 - val_mae: 0.1269 - val_rmse: 0.1795 - val_smape: 0.3425

Epoch 13/128

1916/1916 - 58s - 30ms/step - ia: 0.8974 - loss: 0.0586 - mae: 0.1402 - rmse: 0.2147 - smape: 0.3575 - val_ia: 0.6990 - val_loss: 0.0525 - val_mae: 0.1287 - val_rmse: 0.1823 - val_smape: 0.3465

Epoch 14/128

1916/1916 - 80s - 42ms/step - ia: 0.8981 - loss: 0.0585 - mae: 0.1393 - rmse: 0.2134 - smape: 0.3573 - val_ia: 0.7001 - val_loss: 0.0518 - val_mae: 0.1273 - val_rmse: 0.1804 - val_smape: 0.3436

Epoch 15/128

1916/1916 - 39s - 20ms/step - ia: 0.8982 - loss: 0.0570 - mae: 0.1385 - rmse: 0.2122 - smape: 0.3564 - val_ia: 0.6820 - val_loss: 0.0516 - val_mae: 0.1310 - val_rmse: 0.1823 - val_smape: 0.3516

Epoch 16/128

1916/1916 - 53s - 27ms/step - ia: 0.8986 - loss: 0.0567 - mae: 0.1379 - rmse: 0.2111 - smape: 0.3558 - val_ia: 0.6905 - val_loss: 0.0522 - val_mae: 0.1303 - val_rmse: 0.1826 - val_smape: 0.3520

Epoch 17/128

1916/1916 - 80s - 42ms/step - ia: 0.8991 - loss: 0.0564 - mae: 0.1376 - rmse: 0.2108 - smape: 0.3554 - val_ia: 0.6879 - val_loss: 0.0544 - val_mae: 0.1333 - val_rmse: 0.1881 - val_smape: 0.3643

Epoch 18/128

1916/1916 - 51s - 26ms/step - ia: 0.8981 - loss: 0.0563 - mae: 0.1385 - rmse: 0.2111 - smape: 0.3544 - val_ia: 0.6896 - val_loss: 0.0532 - val_mae: 0.1315 - val_rmse: 0.1843 - val_smape: 0.3544

Epoch 19/128

1916/1916 - 50s - 26ms/step - ia: 0.8997 - loss: 0.0562 - mae: 0.1372 - rmse: 0.2105 - smape: 0.3547 - val_ia: 0.6977 - val_loss: 0.0523 - val_mae: 0.1287 - val_rmse: 0.1810 - val_smape: 0.3495

Epoch 20/128

1916/1916 - 82s - 43ms/step - ia: 0.9000 - loss: 0.0557 - mae: 0.1370 - rmse: 0.2099 - smape: 0.3527 - val_ia: 0.7021 - val_loss: 0.0517 - val_mae: 0.1289 - val_rmse: 0.1808 - val_smape: 0.3476

Epoch 21/128

1916/1916 - 50s - 26ms/step - ia: 0.8994 - loss: 0.0552 - mae: 0.1368 - rmse: 0.2092 - smape: 0.3540 - val_ia: 0.6888 - val_loss: 0.0552 - val_mae: 0.1367 - val_rmse: 0.1902 - val_smape: 0.3497

Epoch 22/128

1916/1916 - 83s - 43ms/step - ia: 0.9008 - loss: 0.0544 - mae: 0.1362 - rmse: 0.2079 - smape: 0.3533 - val_ia: 0.6843 - val_loss: 0.0538 - val_mae: 0.1336 - val_rmse: 0.1866 - val_smape: 0.3628

Epoch 23/128

1916/1916 - 51s - 26ms/step - ia: 0.9006 - loss: 0.0546 - mae: 0.1364 - rmse: 0.2079 - smape: 0.3531 - val_ia: 0.7004 - val_loss: 0.0522 - val_mae: 0.1291 - val_rmse: 0.1815 - val_smape: 0.3482

Epoch 24/128

1916/1916 - 51s - 27ms/step - ia: 0.9006 - loss: 0.0539 - mae: 0.1356 - rmse: 0.2076 - smape: 0.3524 - val_ia: 0.6914 - val_loss: 0.0529 - val_mae: 0.1310 - val_rmse: 0.1832 - val_smape: 0.3501

Epoch 25/128

1916/1916 - 50s - 26ms/step - ia: 0.9000 - loss: 0.0536 - mae: 0.1360 - rmse: 0.2068 - smape: 0.3526 - val_ia: 0.6943 - val_loss: 0.0538 - val_mae: 0.1333 - val_rmse: 0.1853 - val_smape: 0.3502

Epoch 26/128

1916/1916 - 73s - 38ms/step - ia: 0.9009 - loss: 0.0541 - mae: 0.1356 - rmse: 0.2072 - smape: 0.3513 - val_ia: 0.6947 - val_loss: 0.0538 - val_mae: 0.1300 - val_rmse: 0.1828 - val_smape: 0.3511

Epoch 27/128

1916/1916 - 38s - 20ms/step - ia: 0.9007 - loss: 0.0534 - mae: 0.1351 - rmse: 0.2057 - smape: 0.3518 - val_ia: 0.6987 - val_loss: 0.0531 - val_mae: 0.1299 - val_rmse: 0.1818 - val_smape: 0.3478

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:58 2s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step

 17%|█▋        | 2/12 [35:25<3:10:49, 1144.96s/trial, best loss: 0.036452573825096646]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 46s - 12ms/step - ia: 0.1830 - loss: 1.3163 - mae: 0.9095 - rmse: 1.1010 - smape: 1.7906 - val_ia: 0.1745 - val_loss: 1.1807 - val_mae: 0.8536 - val_rmse: 0.8908 - val_smape: 1.8214

Epoch 2/128

3832/3832 - 44s - 11ms/step - ia: 0.1851 - loss: 1.2251 - mae: 0.8727 - rmse: 1.0578 - smape: 1.8106 - val_ia: 0.1781 - val_loss: 1.1181 - val_mae: 0.8260 - val_rmse: 0.8634 - val_smape: 1.8389

Epoch 3/128

3832/3832 - 34s - 9ms/step - ia: 0.1925 - loss: 1.1547 - mae: 0.8422 - rmse: 1.0228 - smape: 1.8190 - val_ia: 0.1804 - val_loss: 1.0665 - val_mae: 0.8026 - val_rmse: 0.8400 - val_smape: 1.8489

Epoch 4/128

3832/3832 - 51s - 13ms/step - ia: 0.1927 - loss: 1.1013 - mae: 0.8179 - rmse: 0.9955 - smape: 1.8291 - val_ia: 0.1828 - val_loss: 1.0229 - val_mae: 0.7823 - val_rmse: 0.8199 - val_smape: 1.8539

Epoch 5/128

3832/3832 - 76s - 20ms/step - ia: 0.2018 - loss: 1.0527 - mae: 0.7959 - rmse: 0.9708 - smape: 1.8290 - val_ia: 0.1847 - val_loss: 0.9859 - val_mae: 0.7649 - val_rmse: 0.8024 - val_smape: 1.8545

Epoch 6/128

3832/3832 - 38s - 10ms/step - ia: 0.2088 - loss: 1.0135 - mae: 0.7771 - rmse: 0.9523 - smape: 1.8267 - val_ia: 0.1861 - val_loss: 0.9535 - val_mae: 0.7499 - val_rmse: 0.7873 - val_smape: 1.8516

Epoch 7/128

3832/3832 - 38s - 10ms/step - ia: 0.2196 - loss: 0.9815 - mae: 0.7618 - rmse: 0.9349 - smape: 1.8190 - val_ia: 0.1875 - val_loss: 0.9253 - val_mae: 0.7371 - val_rmse: 0.7743 - val_smape: 1.8417

Epoch 8/128

3832/3832 - 38s - 10ms/step - ia: 0.2238 - loss: 0.9526 - mae: 0.7492 - rmse: 0.9202 - smape: 1.8044 - val_ia: 0.1885 - val_loss: 0.9009 - val_mae: 0.7266 - val_rmse: 0.7636 - val_smape: 1.8222

Epoch 9/128

3832/3832 - 32s - 8ms/step - ia: 0.2357 - loss: 0.9273 - mae: 0.7388 - rmse: 0.9060 - smape: 1.7804 - val_ia: 0.1892 - val_loss: 0.8795 - val_mae: 0.7181 - val_rmse: 0.7550 - val_smape: 1.7932

Epoch 10/128

3832/3832 - 33s - 9ms/step - ia: 0.2446 - loss: 0.9067 - mae: 0.7303 - rmse: 0.8964 - smape: 1.7542 - val_ia: 0.1900 - val_loss: 0.8594 - val_mae: 0.7105 - val_rmse: 0.7473 - val_smape: 1.7608

Epoch 11/128

3832/3832 - 35s - 9ms/step - ia: 0.2530 - loss: 0.8878 - mae: 0.7231 - rmse: 0.8861 - smape: 1.7273 - val_ia: 0.1910 - val_loss: 0.8392 - val_mae: 0.7029 - val_rmse: 0.7397 - val_smape: 1.7261

Epoch 12/128

3832/3832 - 31s - 8ms/step - ia: 0.2619 - loss: 0.8637 - mae: 0.7136 - rmse: 0.8738 - smape: 1.6921 - val_ia: 0.1919 - val_loss: 0.8179 - val_mae: 0.6951 - val_rmse: 0.7318 - val_smape: 1.6912

Epoch 13/128

3832/3832 - 47s - 12ms/step - ia: 0.2714 - loss: 0.8439 - mae: 0.7061 - rmse: 0.8647 - smape: 1.6605 - val_ia: 0.1930 - val_loss: 0.7962 - val_mae: 0.6870 - val_rmse: 0.7236 - val_smape: 1.6570

Epoch 14/128

3832/3832 - 37s - 10ms/step - ia: 0.2850 - loss: 0.8207 - mae: 0.6964 - rmse: 0.8526 - smape: 1.6251 - val_ia: 0.1943 - val_loss: 0.7734 - val_mae: 0.6785 - val_rmse: 0.7150 - val_smape: 1.6227

Epoch 15/128

3832/3832 - 31s - 8ms/step - ia: 0.2972 - loss: 0.7946 - mae: 0.6870 - rmse: 0.8399 - smape: 1.5915 - val_ia: 0.1958 - val_loss: 0.7495 - val_mae: 0.6693 - val_rmse: 0.7057 - val_smape: 1.5879

Epoch 16/128

3832/3832 - 36s - 9ms/step - ia: 0.3106 - loss: 0.7720 - mae: 0.6777 - rmse: 0.8268 - smape: 1.5601 - val_ia: 0.1974 - val_loss: 0.7244 - val_mae: 0.6593 - val_rmse: 0.6956 - val_smape: 1.5526

Epoch 17/128

3832/3832 - 37s - 10ms/step - ia: 0.3241 - loss: 0.7481 - mae: 0.6670 - rmse: 0.8147 - smape: 1.5246 - val_ia: 0.1991 - val_loss: 0.6985 - val_mae: 0.6487 - val_rmse: 0.6850 - val_smape: 1.5167

Epoch 18/128

3832/3832 - 42s - 11ms/step - ia: 0.3390 - loss: 0.7210 - mae: 0.6562 - rmse: 0.8003 - smape: 1.4891 - val_ia: 0.2009 - val_loss: 0.6712 - val_mae: 0.6372 - val_rmse: 0.6734 - val_smape: 1.4801

Epoch 19/128

3832/3832 - 37s - 10ms/step - ia: 0.3536 - loss: 0.6950 - mae: 0.6439 - rmse: 0.7849 - smape: 1.4516 - val_ia: 0.2030 - val_loss: 0.6432 - val_mae: 0.6250 - val_rmse: 0.6611 - val_smape: 1.4418

Epoch 20/128

3832/3832 - 32s - 8ms/step - ia: 0.3718 - loss: 0.6619 - mae: 0.6299 - rmse: 0.7675 - smape: 1.4132 - val_ia: 0.2054 - val_loss: 0.6146 - val_mae: 0.6119 - val_rmse: 0.6481 - val_smape: 1.4022

Epoch 21/128

3832/3832 - 36s - 9ms/step - ia: 0.3872 - loss: 0.6391 - mae: 0.6180 - rmse: 0.7528 - smape: 1.3758 - val_ia: 0.2085 - val_loss: 0.5848 - val_mae: 0.5978 - val_rmse: 0.6340 - val_smape: 1.3609

Epoch 22/128

3832/3832 - 30s - 8ms/step - ia: 0.4033 - loss: 0.6168 - mae: 0.6056 - rmse: 0.7386 - smape: 1.3407 - val_ia: 0.2117 - val_loss: 0.5552 - val_mae: 0.5829 - val_rmse: 0.6193 - val_smape: 1.3189

Epoch 23/128

3832/3832 - 36s - 9ms/step - ia: 0.4216 - loss: 0.5885 - mae: 0.5903 - rmse: 0.7222 - smape: 1.2977 - val_ia: 0.2152 - val_loss: 0.5255 - val_mae: 0.5674 - val_rmse: 0.6040 - val_smape: 1.2756

Epoch 24/128

3832/3832 - 38s - 10ms/step - ia: 0.4385 - loss: 0.5553 - mae: 0.5749 - rmse: 0.7018 - smape: 1.2617 - val_ia: 0.2188 - val_loss: 0.4959 - val_mae: 0.5511 - val_rmse: 0.5879 - val_smape: 1.2306

Epoch 25/128

3832/3832 - 39s - 10ms/step - ia: 0.4597 - loss: 0.5308 - mae: 0.5585 - rmse: 0.6835 - smape: 1.2168 - val_ia: 0.2223 - val_loss: 0.4662 - val_mae: 0.5344 - val_rmse: 0.5713 - val_smape: 1.1854

Epoch 26/128

3832/3832 - 35s - 9ms/step - ia: 0.4795 - loss: 0.4966 - mae: 0.5409 - rmse: 0.6627 - smape: 1.1733 - val_ia: 0.2259 - val_loss: 0.4371 - val_mae: 0.5169 - val_rmse: 0.5541 - val_smape: 1.1393

Epoch 27/128

3832/3832 - 32s - 8ms/step - ia: 0.4983 - loss: 0.4732 - mae: 0.5258 - rmse: 0.6450 - smape: 1.1352 - val_ia: 0.2294 - val_loss: 0.4094 - val_mae: 0.4992 - val_rmse: 0.5369 - val_smape: 1.0930

Epoch 28/128

3832/3832 - 37s - 10ms/step - ia: 0.5147 - loss: 0.4519 - mae: 0.5104 - rmse: 0.6290 - smape: 1.0983 - val_ia: 0.2330 - val_loss: 0.3833 - val_mae: 0.4819 - val_rmse: 0.5200 - val_smape: 1.0480

Epoch 29/128

3832/3832 - 38s - 10ms/step - ia: 0.5344 - loss: 0.4240 - mae: 0.4929 - rmse: 0.6095 - smape: 1.0562 - val_ia: 0.2370 - val_loss: 0.3589 - val_mae: 0.4647 - val_rmse: 0.5034 - val_smape: 1.0040

Epoch 30/128

3832/3832 - 38s - 10ms/step - ia: 0.5514 - loss: 0.4074 - mae: 0.4801 - rmse: 0.5957 - smape: 1.0250 - val_ia: 0.2415 - val_loss: 0.3361 - val_mae: 0.4481 - val_rmse: 0.4873 - val_smape: 0.9633

Epoch 31/128

3832/3832 - 38s - 10ms/step - ia: 0.5661 - loss: 0.3893 - mae: 0.4659 - rmse: 0.5815 - smape: 0.9888 - val_ia: 0.2459 - val_loss: 0.3158 - val_mae: 0.4323 - val_rmse: 0.4721 - val_smape: 0.9252

Epoch 32/128

3832/3832 - 37s - 10ms/step - ia: 0.5792 - loss: 0.3749 - mae: 0.4547 - rmse: 0.5702 - smape: 0.9646 - val_ia: 0.2499 - val_loss: 0.2974 - val_mae: 0.4175 - val_rmse: 0.4579 - val_smape: 0.8907

Epoch 33/128

3832/3832 - 37s - 10ms/step - ia: 0.5955 - loss: 0.3690 - mae: 0.4434 - rmse: 0.5602 - smape: 0.9345 - val_ia: 0.2533 - val_loss: 0.2819 - val_mae: 0.4042 - val_rmse: 0.4450 - val_smape: 0.8598

Epoch 34/128

3832/3832 - 38s - 10ms/step - ia: 0.6086 - loss: 0.3513 - mae: 0.4322 - rmse: 0.5477 - smape: 0.9075 - val_ia: 0.2561 - val_loss: 0.2679 - val_mae: 0.3918 - val_rmse: 0.4330 - val_smape: 0.8321

Epoch 35/128

3832/3832 - 39s - 10ms/step - ia: 0.6172 - loss: 0.3441 - mae: 0.4247 - rmse: 0.5410 - smape: 0.8890 - val_ia: 0.2587 - val_loss: 0.2566 - val_mae: 0.3810 - val_rmse: 0.4226 - val_smape: 0.8067

Epoch 36/128

3832/3832 - 38s - 10ms/step - ia: 0.6287 - loss: 0.3278 - mae: 0.4143 - rmse: 0.5292 - smape: 0.8686 - val_ia: 0.2614 - val_loss: 0.2466 - val_mae: 0.3711 - val_rmse: 0.4131 - val_smape: 0.7848

Epoch 37/128

3832/3832 - 40s - 11ms/step - ia: 0.6365 - loss: 0.3245 - mae: 0.4090 - rmse: 0.5251 - smape: 0.8536 - val_ia: 0.2646 - val_loss: 0.2380 - val_mae: 0.3625 - val_rmse: 0.4048 - val_smape: 0.7658

Epoch 38/128

3832/3832 - 38s - 10ms/step - ia: 0.6424 - loss: 0.3182 - mae: 0.4027 - rmse: 0.5188 - smape: 0.8379 - val_ia: 0.2677 - val_loss: 0.2309 - val_mae: 0.3550 - val_rmse: 0.3976 - val_smape: 0.7494

Epoch 39/128

3832/3832 - 33s - 9ms/step - ia: 0.6492 - loss: 0.3207 - mae: 0.4002 - rmse: 0.5178 - smape: 0.8277 - val_ia: 0.2707 - val_loss: 0.2251 - val_mae: 0.3489 - val_rmse: 0.3917 - val_smape: 0.7360

Epoch 40/128

3832/3832 - 32s - 8ms/step - ia: 0.6555 - loss: 0.3139 - mae: 0.3945 - rmse: 0.5119 - smape: 0.8174 - val_ia: 0.2737 - val_loss: 0.2198 - val_mae: 0.3433 - val_rmse: 0.3863 - val_smape: 0.7242

Epoch 41/128

3832/3832 - 36s - 9ms/step - ia: 0.6609 - loss: 0.3120 - mae: 0.3912 - rmse: 0.5092 - smape: 0.8076 - val_ia: 0.2765 - val_loss: 0.2151 - val_mae: 0.3383 - val_rmse: 0.3816 - val_smape: 0.7137

Epoch 42/128

3832/3832 - 30s - 8ms/step - ia: 0.6616 - loss: 0.3172 - mae: 0.3913 - rmse: 0.5124 - smape: 0.8008 - val_ia: 0.2790 - val_loss: 0.2112 - val_mae: 0.3341 - val_rmse: 0.3775 - val_smape: 0.7047

Epoch 43/128

3832/3832 - 35s - 9ms/step - ia: 0.6682 - loss: 0.3067 - mae: 0.3855 - rmse: 0.5045 - smape: 0.7912 - val_ia: 0.2814 - val_loss: 0.2077 - val_mae: 0.3303 - val_rmse: 0.3738 - val_smape: 0.6963

Epoch 44/128

3832/3832 - 37s - 10ms/step - ia: 0.6690 - loss: 0.3072 - mae: 0.3848 - rmse: 0.5041 - smape: 0.7924 - val_ia: 0.2834 - val_loss: 0.2050 - val_mae: 0.3272 - val_rmse: 0.3707 - val_smape: 0.6891

Epoch 45/128

3832/3832 - 34s - 9ms/step - ia: 0.6754 - loss: 0.2937 - mae: 0.3775 - rmse: 0.4947 - smape: 0.7802 - val_ia: 0.2855 - val_loss: 0.2019 - val_mae: 0.3239 - val_rmse: 0.3675 - val_smape: 0.6825

Epoch 46/128

3832/3832 - 44s - 12ms/step - ia: 0.6759 - loss: 0.3014 - mae: 0.3779 - rmse: 0.4979 - smape: 0.7732 - val_ia: 0.2875 - val_loss: 0.1991 - val_mae: 0.3210 - val_rmse: 0.3647 - val_smape: 0.6764

Epoch 47/128

3832/3832 - 42s - 11ms/step - ia: 0.6795 - loss: 0.2954 - mae: 0.3754 - rmse: 0.4932 - smape: 0.7726 - val_ia: 0.2892 - val_loss: 0.1971 - val_mae: 0.3186 - val_rmse: 0.3623 - val_smape: 0.6712

Epoch 48/128

3832/3832 - 38s - 10ms/step - ia: 0.6830 - loss: 0.2873 - mae: 0.3708 - rmse: 0.4873 - smape: 0.7615 - val_ia: 0.2909 - val_loss: 0.1947 - val_mae: 0.3161 - val_rmse: 0.3598 - val_smape: 0.6661

Epoch 49/128

3832/3832 - 36s - 9ms/step - ia: 0.6813 - loss: 0.2938 - mae: 0.3737 - rmse: 0.4926 - smape: 0.7670 - val_ia: 0.2925 - val_loss: 0.1923 - val_mae: 0.3139 - val_rmse: 0.3575 - val_smape: 0.6616

Epoch 50/128

3832/3832 - 30s - 8ms/step - ia: 0.6854 - loss: 0.2844 - mae: 0.3686 - rmse: 0.4865 - smape: 0.7570 - val_ia: 0.2940 - val_loss: 0.1904 - val_mae: 0.3118 - val_rmse: 0.3554 - val_smape: 0.6569

Epoch 51/128

3832/3832 - 38s - 10ms/step - ia: 0.6902 - loss: 0.2796 - mae: 0.3641 - rmse: 0.4807 - smape: 0.7491 - val_ia: 0.2954 - val_loss: 0.1884 - val_mae: 0.3097 - val_rmse: 0.3533 - val_smape: 0.6524

Epoch 52/128

3832/3832 - 35s - 9ms/step - ia: 0.6908 - loss: 0.2789 - mae: 0.3646 - rmse: 0.4804 - smape: 0.7521 - val_ia: 0.2967 - val_loss: 0.1866 - val_mae: 0.3078 - val_rmse: 0.3514 - val_smape: 0.6486

Epoch 53/128

3832/3832 - 35s - 9ms/step - ia: 0.6907 - loss: 0.2823 - mae: 0.3634 - rmse: 0.4818 - smape: 0.7456 - val_ia: 0.2978 - val_loss: 0.1851 - val_mae: 0.3062 - val_rmse: 0.3497 - val_smape: 0.6451

Epoch 54/128

3832/3832 - 39s - 10ms/step - ia: 0.6938 - loss: 0.2779 - mae: 0.3611 - rmse: 0.4781 - smape: 0.7441 - val_ia: 0.2990 - val_loss: 0.1834 - val_mae: 0.3044 - val_rmse: 0.3479 - val_smape: 0.6412

Epoch 55/128

3832/3832 - 37s - 10ms/step - ia: 0.6968 - loss: 0.2738 - mae: 0.3580 - rmse: 0.4734 - smape: 0.7346 - val_ia: 0.3004 - val_loss: 0.1817 - val_mae: 0.3026 - val_rmse: 0.3460 - val_smape: 0.6375

Epoch 56/128

3832/3832 - 41s - 11ms/step - ia: 0.6972 - loss: 0.2677 - mae: 0.3570 - rmse: 0.4727 - smape: 0.7359 - val_ia: 0.3018 - val_loss: 0.1801 - val_mae: 0.3008 - val_rmse: 0.3443 - val_smape: 0.6342

Epoch 57/128

3832/3832 - 37s - 10ms/step - ia: 0.6977 - loss: 0.2749 - mae: 0.3564 - rmse: 0.4741 - smape: 0.7332 - val_ia: 0.3032 - val_loss: 0.1785 - val_mae: 0.2991 - val_rmse: 0.3425 - val_smape: 0.6309

Epoch 58/128

3832/3832 - 38s - 10ms/step - ia: 0.7013 - loss: 0.2716 - mae: 0.3539 - rmse: 0.4716 - smape: 0.7279 - val_ia: 0.3045 - val_loss: 0.1770 - val_mae: 0.2975 - val_rmse: 0.3409 - val_smape: 0.6277

Epoch 59/128

3832/3832 - 41s - 11ms/step - ia: 0.7019 - loss: 0.2691 - mae: 0.3519 - rmse: 0.4689 - smape: 0.7250 - val_ia: 0.3058 - val_loss: 0.1754 - val_mae: 0.2959 - val_rmse: 0.3393 - val_smape: 0.6245

Epoch 60/128

3832/3832 - 31s - 8ms/step - ia: 0.7029 - loss: 0.2679 - mae: 0.3513 - rmse: 0.4674 - smape: 0.7225 - val_ia: 0.3070 - val_loss: 0.1740 - val_mae: 0.2945 - val_rmse: 0.3377 - val_smape: 0.6216

Epoch 61/128

3832/3832 - 34s - 9ms/step - ia: 0.7094 - loss: 0.2640 - mae: 0.3489 - rmse: 0.4644 - smape: 0.7197 - val_ia: 0.3080 - val_loss: 0.1726 - val_mae: 0.2931 - val_rmse: 0.3364 - val_smape: 0.6189

Epoch 62/128

3832/3832 - 34s - 9ms/step - ia: 0.7077 - loss: 0.2657 - mae: 0.3482 - rmse: 0.4644 - smape: 0.7188 - val_ia: 0.3092 - val_loss: 0.1712 - val_mae: 0.2917 - val_rmse: 0.3349 - val_smape: 0.6160

Epoch 63/128

3832/3832 - 32s - 8ms/step - ia: 0.7080 - loss: 0.2598 - mae: 0.3447 - rmse: 0.4591 - smape: 0.7135 - val_ia: 0.3103 - val_loss: 0.1698 - val_mae: 0.2902 - val_rmse: 0.3333 - val_smape: 0.6129

Epoch 64/128

3832/3832 - 37s - 10ms/step - ia: 0.7094 - loss: 0.2631 - mae: 0.3457 - rmse: 0.4630 - smape: 0.7119 - val_ia: 0.3113 - val_loss: 0.1688 - val_mae: 0.2891 - val_rmse: 0.3322 - val_smape: 0.6106

Epoch 65/128

3832/3832 - 41s - 11ms/step - ia: 0.7113 - loss: 0.2585 - mae: 0.3430 - rmse: 0.4587 - smape: 0.7085 - val_ia: 0.3123 - val_loss: 0.1679 - val_mae: 0.2878 - val_rmse: 0.3309 - val_smape: 0.6077

Epoch 66/128

3832/3832 - 34s - 9ms/step - ia: 0.7142 - loss: 0.2555 - mae: 0.3409 - rmse: 0.4559 - smape: 0.7037 - val_ia: 0.3134 - val_loss: 0.1663 - val_mae: 0.2864 - val_rmse: 0.3294 - val_smape: 0.6052

Epoch 67/128

3832/3832 - 36s - 9ms/step - ia: 0.7150 - loss: 0.2558 - mae: 0.3394 - rmse: 0.4547 - smape: 0.7021 - val_ia: 0.3144 - val_loss: 0.1654 - val_mae: 0.2852 - val_rmse: 0.3282 - val_smape: 0.6027

Epoch 68/128

3832/3832 - 37s - 10ms/step - ia: 0.7163 - loss: 0.2536 - mae: 0.3392 - rmse: 0.4535 - smape: 0.7017 - val_ia: 0.3156 - val_loss: 0.1639 - val_mae: 0.2839 - val_rmse: 0.3268 - val_smape: 0.6002

Epoch 69/128

3832/3832 - 37s - 10ms/step - ia: 0.7144 - loss: 0.2549 - mae: 0.3395 - rmse: 0.4551 - smape: 0.7040 - val_ia: 0.3164 - val_loss: 0.1633 - val_mae: 0.2831 - val_rmse: 0.3260 - val_smape: 0.5982

Epoch 70/128

3832/3832 - 38s - 10ms/step - ia: 0.7174 - loss: 0.2520 - mae: 0.3368 - rmse: 0.4521 - smape: 0.6973 - val_ia: 0.3174 - val_loss: 0.1620 - val_mae: 0.2818 - val_rmse: 0.3246 - val_smape: 0.5958

Epoch 71/128

3832/3832 - 36s - 9ms/step - ia: 0.7184 - loss: 0.2552 - mae: 0.3363 - rmse: 0.4536 - smape: 0.6953 - val_ia: 0.3185 - val_loss: 0.1609 - val_mae: 0.2806 - val_rmse: 0.3234 - val_smape: 0.5934

Epoch 72/128

3832/3832 - 31s - 8ms/step - ia: 0.7203 - loss: 0.2495 - mae: 0.3335 - rmse: 0.4480 - smape: 0.6910 - val_ia: 0.3195 - val_loss: 0.1601 - val_mae: 0.2796 - val_rmse: 0.3223 - val_smape: 0.5912

Epoch 73/128

3832/3832 - 38s - 10ms/step - ia: 0.7201 - loss: 0.2572 - mae: 0.3358 - rmse: 0.4527 - smape: 0.6949 - val_ia: 0.3204 - val_loss: 0.1590 - val_mae: 0.2786 - val_rmse: 0.3213 - val_smape: 0.5893

Epoch 74/128

3832/3832 - 38s - 10ms/step - ia: 0.7230 - loss: 0.2496 - mae: 0.3325 - rmse: 0.4471 - smape: 0.6909 - val_ia: 0.3215 - val_loss: 0.1582 - val_mae: 0.2775 - val_rmse: 0.3202 - val_smape: 0.5871

Epoch 75/128

3832/3832 - 41s - 11ms/step - ia: 0.7237 - loss: 0.2436 - mae: 0.3302 - rmse: 0.4460 - smape: 0.6859 - val_ia: 0.3226 - val_loss: 0.1570 - val_mae: 0.2763 - val_rmse: 0.3190 - val_smape: 0.5850

Epoch 76/128

3832/3832 - 37s - 10ms/step - ia: 0.7259 - loss: 0.2399 - mae: 0.3276 - rmse: 0.4406 - smape: 0.6821 - val_ia: 0.3236 - val_loss: 0.1561 - val_mae: 0.2753 - val_rmse: 0.3179 - val_smape: 0.5830

Epoch 77/128

3832/3832 - 36s - 9ms/step - ia: 0.7289 - loss: 0.2415 - mae: 0.3261 - rmse: 0.4408 - smape: 0.6772 - val_ia: 0.3246 - val_loss: 0.1551 - val_mae: 0.2742 - val_rmse: 0.3168 - val_smape: 0.5809

Epoch 78/128

3832/3832 - 38s - 10ms/step - ia: 0.7256 - loss: 0.2376 - mae: 0.3272 - rmse: 0.4394 - smape: 0.6811 - val_ia: 0.3256 - val_loss: 0.1542 - val_mae: 0.2732 - val_rmse: 0.3158 - val_smape: 0.5789

Epoch 79/128

3832/3832 - 44s - 12ms/step - ia: 0.7291 - loss: 0.2361 - mae: 0.3247 - rmse: 0.4365 - smape: 0.6778 - val_ia: 0.3266 - val_loss: 0.1533 - val_mae: 0.2723 - val_rmse: 0.3148 - val_smape: 0.5768

Epoch 80/128

3832/3832 - 39s - 10ms/step - ia: 0.7292 - loss: 0.2425 - mae: 0.3267 - rmse: 0.4403 - smape: 0.6769 - val_ia: 0.3276 - val_loss: 0.1526 - val_mae: 0.2713 - val_rmse: 0.3138 - val_smape: 0.5748

Epoch 81/128

3832/3832 - 31s - 8ms/step - ia: 0.7288 - loss: 0.2442 - mae: 0.3259 - rmse: 0.4406 - smape: 0.6762 - val_ia: 0.3285 - val_loss: 0.1514 - val_mae: 0.2703 - val_rmse: 0.3128 - val_smape: 0.5728

Epoch 82/128

3832/3832 - 36s - 9ms/step - ia: 0.7320 - loss: 0.2358 - mae: 0.3225 - rmse: 0.4360 - smape: 0.6709 - val_ia: 0.3294 - val_loss: 0.1509 - val_mae: 0.2696 - val_rmse: 0.3120 - val_smape: 0.5711

Epoch 83/128

3832/3832 - 34s - 9ms/step - ia: 0.7315 - loss: 0.2327 - mae: 0.3219 - rmse: 0.4338 - smape: 0.6722 - val_ia: 0.3304 - val_loss: 0.1501 - val_mae: 0.2686 - val_rmse: 0.3110 - val_smape: 0.5692

Epoch 84/128

3832/3832 - 34s - 9ms/step - ia: 0.7301 - loss: 0.2373 - mae: 0.3223 - rmse: 0.4360 - smape: 0.6689 - val_ia: 0.3315 - val_loss: 0.1492 - val_mae: 0.2675 - val_rmse: 0.3099 - val_smape: 0.5673

Epoch 85/128

3832/3832 - 37s - 10ms/step - ia: 0.7357 - loss: 0.2303 - mae: 0.3189 - rmse: 0.4302 - smape: 0.6672 - val_ia: 0.3323 - val_loss: 0.1485 - val_mae: 0.2668 - val_rmse: 0.3092 - val_smape: 0.5658

Epoch 86/128

3832/3832 - 41s - 11ms/step - ia: 0.7335 - loss: 0.2291 - mae: 0.3179 - rmse: 0.4307 - smape: 0.6631 - val_ia: 0.3334 - val_loss: 0.1473 - val_mae: 0.2657 - val_rmse: 0.3080 - val_smape: 0.5639

Epoch 87/128

3832/3832 - 37s - 10ms/step - ia: 0.7337 - loss: 0.2327 - mae: 0.3191 - rmse: 0.4322 - smape: 0.6672 - val_ia: 0.3341 - val_loss: 0.1467 - val_mae: 0.2650 - val_rmse: 0.3073 - val_smape: 0.5624

Epoch 88/128

3832/3832 - 41s - 11ms/step - ia: 0.7372 - loss: 0.2282 - mae: 0.3163 - rmse: 0.4268 - smape: 0.6614 - val_ia: 0.3352 - val_loss: 0.1456 - val_mae: 0.2638 - val_rmse: 0.3061 - val_smape: 0.5602

Epoch 89/128

3832/3832 - 37s - 10ms/step - ia: 0.7376 - loss: 0.2305 - mae: 0.3167 - rmse: 0.4288 - smape: 0.6584 - val_ia: 0.3359 - val_loss: 0.1450 - val_mae: 0.2631 - val_rmse: 0.3054 - val_smape: 0.5586

Epoch 90/128

3832/3832 - 40s - 10ms/step - ia: 0.7369 - loss: 0.2297 - mae: 0.3159 - rmse: 0.4285 - smape: 0.6594 - val_ia: 0.3367 - val_loss: 0.1443 - val_mae: 0.2624 - val_rmse: 0.3046 - val_smape: 0.5570

Epoch 91/128

3832/3832 - 42s - 11ms/step - ia: 0.7366 - loss: 0.2319 - mae: 0.3157 - rmse: 0.4296 - smape: 0.6592 - val_ia: 0.3378 - val_loss: 0.1432 - val_mae: 0.2613 - val_rmse: 0.3035 - val_smape: 0.5551

Epoch 92/128

3832/3832 - 37s - 10ms/step - ia: 0.7382 - loss: 0.2302 - mae: 0.3157 - rmse: 0.4286 - smape: 0.6577 - val_ia: 0.3387 - val_loss: 0.1426 - val_mae: 0.2606 - val_rmse: 0.3028 - val_smape: 0.5535

Epoch 93/128

3832/3832 - 37s - 10ms/step - ia: 0.7389 - loss: 0.2296 - mae: 0.3142 - rmse: 0.4279 - smape: 0.6584 - val_ia: 0.3394 - val_loss: 0.1422 - val_mae: 0.2601 - val_rmse: 0.3022 - val_smape: 0.5522

Epoch 94/128

3832/3832 - 37s - 10ms/step - ia: 0.7405 - loss: 0.2199 - mae: 0.3103 - rmse: 0.4208 - smape: 0.6530 - val_ia: 0.3405 - val_loss: 0.1412 - val_mae: 0.2589 - val_rmse: 0.3011 - val_smape: 0.5501

Epoch 95/128

3832/3832 - 41s - 11ms/step - ia: 0.7389 - loss: 0.2272 - mae: 0.3141 - rmse: 0.4259 - smape: 0.6584 - val_ia: 0.3414 - val_loss: 0.1405 - val_mae: 0.2581 - val_rmse: 0.3003 - val_smape: 0.5485

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 23s - 24ms/step - ia: 0.5041 - loss: 0.5719 - mae: 0.5438 - rmse: 0.7315 - smape: 1.1088 - val_ia: 0.4254 - val_loss: 0.2826 - val_mae: 0.3690 - val_rmse: 0.4528 - val_smape: 0.7878

Epoch 2/128

958/958 - 11s - 11ms/step - ia: 0.6912 - loss: 0.3400 - mae: 0.4045 - rmse: 0.5655 - smape: 0.8103 - val_ia: 0.4910 - val_loss: 0.2337 - val_mae: 0.3190 - val_rmse: 0.4090 - val_smape: 0.6981

Epoch 3/128

958/958 - 11s - 11ms/step - ia: 0.7136 - loss: 0.3110 - mae: 0.3827 - rmse: 0.5408 - smape: 0.7713 - val_ia: 0.5190 - val_loss: 0.2133 - val_mae: 0.3016 - val_rmse: 0.3918 - val_smape: 0.6686

Epoch 4/128

958/958 - 11s - 11ms/step - ia: 0.7283 - loss: 0.2859 - mae: 0.3652 - rmse: 0.5182 - smape: 0.7420 - val_ia: 0.5283 - val_loss: 0.2002 - val_mae: 0.2928 - val_rmse: 0.3803 - val_smape: 0.6550

Epoch 5/128

958/958 - 14s - 15ms/step - ia: 0.7365 - loss: 0.2703 - mae: 0.3548 - rmse: 0.5021 - smape: 0.7313 - val_ia: 0.5413 - val_loss: 0.1889 - val_mae: 0.2840 - val_rmse: 0.3703 - val_smape: 0.6413

Epoch 6/128

958/958 - 15s - 16ms/step - ia: 0.7448 - loss: 0.2562 - mae: 0.3437 - rmse: 0.4892 - smape: 0.7084 - val_ia: 0.5541 - val_loss: 0.1785 - val_mae: 0.2753 - val_rmse: 0.3608 - val_smape: 0.6277

Epoch 7/128

958/958 - 15s - 16ms/step - ia: 0.7507 - loss: 0.2446 - mae: 0.3355 - rmse: 0.4773 - smape: 0.6943 - val_ia: 0.5673 - val_loss: 0.1682 - val_mae: 0.2661 - val_rmse: 0.3509 - val_smape: 0.6119

Epoch 8/128

958/958 - 12s - 13ms/step - ia: 0.7575 - loss: 0.2340 - mae: 0.3278 - rmse: 0.4667 - smape: 0.6848 - val_ia: 0.5783 - val_loss: 0.1598 - val_mae: 0.2588 - val_rmse: 0.3428 - val_smape: 0.6002

Epoch 9/128

958/958 - 11s - 11ms/step - ia: 0.7646 - loss: 0.2233 - mae: 0.3194 - rmse: 0.4553 - smape: 0.6722 - val_ia: 0.5885 - val_loss: 0.1523 - val_mae: 0.2519 - val_rmse: 0.3354 - val_smape: 0.5889

Epoch 10/128

958/958 - 11s - 11ms/step - ia: 0.7686 - loss: 0.2142 - mae: 0.3129 - rmse: 0.4464 - smape: 0.6630 - val_ia: 0.5978 - val_loss: 0.1456 - val_mae: 0.2459 - val_rmse: 0.3285 - val_smape: 0.5788

Epoch 11/128

958/958 - 13s - 14ms/step - ia: 0.7735 - loss: 0.2093 - mae: 0.3083 - rmse: 0.4418 - smape: 0.6522 - val_ia: 0.6055 - val_loss: 0.1390 - val_mae: 0.2398 - val_rmse: 0.3213 - val_smape: 0.5679

Epoch 12/128

958/958 - 15s - 16ms/step - ia: 0.7770 - loss: 0.2032 - mae: 0.3034 - rmse: 0.4341 - smape: 0.6439 - val_ia: 0.6096 - val_loss: 0.1351 - val_mae: 0.2369 - val_rmse: 0.3171 - val_smape: 0.5626

Epoch 13/128

958/958 - 15s - 16ms/step - ia: 0.7816 - loss: 0.1939 - mae: 0.2968 - rmse: 0.4249 - smape: 0.6314 - val_ia: 0.6171 - val_loss: 0.1296 - val_mae: 0.2317 - val_rmse: 0.3114 - val_smape: 0.5540

Epoch 14/128

958/958 - 17s - 18ms/step - ia: 0.7845 - loss: 0.1895 - mae: 0.2942 - rmse: 0.4197 - smape: 0.6312 - val_ia: 0.6265 - val_loss: 0.1256 - val_mae: 0.2269 - val_rmse: 0.3073 - val_smape: 0.5465

Epoch 15/128

958/958 - 11s - 11ms/step - ia: 0.7884 - loss: 0.1859 - mae: 0.2901 - rmse: 0.4136 - smape: 0.6196 - val_ia: 0.6290 - val_loss: 0.1223 - val_mae: 0.2242 - val_rmse: 0.3030 - val_smape: 0.5404

Epoch 16/128

958/958 - 12s - 12ms/step - ia: 0.7897 - loss: 0.1837 - mae: 0.2877 - rmse: 0.4123 - smape: 0.6159 - val_ia: 0.6325 - val_loss: 0.1195 - val_mae: 0.2218 - val_rmse: 0.2998 - val_smape: 0.5364

Epoch 17/128

958/958 - 13s - 14ms/step - ia: 0.7930 - loss: 0.1772 - mae: 0.2831 - rmse: 0.4050 - smape: 0.6087 - val_ia: 0.6443 - val_loss: 0.1148 - val_mae: 0.2151 - val_rmse: 0.2943 - val_smape: 0.5263

Epoch 18/128

958/958 - 15s - 16ms/step - ia: 0.7966 - loss: 0.1730 - mae: 0.2789 - rmse: 0.4001 - smape: 0.6053 - val_ia: 0.6457 - val_loss: 0.1127 - val_mae: 0.2137 - val_rmse: 0.2915 - val_smape: 0.5228

Epoch 19/128

958/958 - 20s - 21ms/step - ia: 0.7979 - loss: 0.1695 - mae: 0.2774 - rmse: 0.3968 - smape: 0.5992 - val_ia: 0.6489 - val_loss: 0.1099 - val_mae: 0.2110 - val_rmse: 0.2886 - val_smape: 0.5194

Epoch 20/128

958/958 - 15s - 16ms/step - ia: 0.8003 - loss: 0.1699 - mae: 0.2751 - rmse: 0.3955 - smape: 0.5932 - val_ia: 0.6503 - val_loss: 0.1080 - val_mae: 0.2093 - val_rmse: 0.2858 - val_smape: 0.5150

Epoch 21/128

958/958 - 15s - 16ms/step - ia: 0.8011 - loss: 0.1653 - mae: 0.2732 - rmse: 0.3911 - smape: 0.5947 - val_ia: 0.6517 - val_loss: 0.1069 - val_mae: 0.2087 - val_rmse: 0.2845 - val_smape: 0.5133

Epoch 22/128

958/958 - 20s - 21ms/step - ia: 0.8037 - loss: 0.1640 - mae: 0.2704 - rmse: 0.3882 - smape: 0.5895 - val_ia: 0.6609 - val_loss: 0.1038 - val_mae: 0.2039 - val_rmse: 0.2803 - val_smape: 0.5058

Epoch 23/128

958/958 - 11s - 11ms/step - ia: 0.8059 - loss: 0.1600 - mae: 0.2678 - rmse: 0.3839 - smape: 0.5821 - val_ia: 0.6586 - val_loss: 0.1027 - val_mae: 0.2039 - val_rmse: 0.2790 - val_smape: 0.5052

Epoch 24/128

958/958 - 10s - 11ms/step - ia: 0.8073 - loss: 0.1591 - mae: 0.2650 - rmse: 0.3820 - smape: 0.5768 - val_ia: 0.6664 - val_loss: 0.0999 - val_mae: 0.1995 - val_rmse: 0.2753 - val_smape: 0.4987

Epoch 25/128

958/958 - 11s - 11ms/step - ia: 0.8081 - loss: 0.1547 - mae: 0.2643 - rmse: 0.3774 - smape: 0.5753 - val_ia: 0.6654 - val_loss: 0.0991 - val_mae: 0.1995 - val_rmse: 0.2740 - val_smape: 0.4975

Epoch 26/128

958/958 - 14s - 14ms/step - ia: 0.8101 - loss: 0.1528 - mae: 0.2614 - rmse: 0.3748 - smape: 0.5708 - val_ia: 0.6761 - val_loss: 0.0961 - val_mae: 0.1942 - val_rmse: 0.2702 - val_smape: 0.4905

Epoch 27/128

958/958 - 22s - 23ms/step - ia: 0.8128 - loss: 0.1498 - mae: 0.2597 - rmse: 0.3719 - smape: 0.5695 - val_ia: 0.6697 - val_loss: 0.0954 - val_mae: 0.1957 - val_rmse: 0.2694 - val_smape: 0.4915

Epoch 28/128

958/958 - 21s - 21ms/step - ia: 0.8123 - loss: 0.1498 - mae: 0.2582 - rmse: 0.3714 - smape: 0.5664 - val_ia: 0.6748 - val_loss: 0.0941 - val_mae: 0.1934 - val_rmse: 0.2675 - val_smape: 0.4883

Epoch 29/128

958/958 - 15s - 16ms/step - ia: 0.8132 - loss: 0.1494 - mae: 0.2572 - rmse: 0.3697 - smape: 0.5638 - val_ia: 0.6749 - val_loss: 0.0932 - val_mae: 0.1928 - val_rmse: 0.2662 - val_smape: 0.4865

Epoch 30/128

958/958 - 15s - 16ms/step - ia: 0.8152 - loss: 0.1468 - mae: 0.2548 - rmse: 0.3676 - smape: 0.5595 - val_ia: 0.6789 - val_loss: 0.0915 - val_mae: 0.1904 - val_rmse: 0.2638 - val_smape: 0.4826

Epoch 31/128

958/958 - 15s - 16ms/step - ia: 0.8158 - loss: 0.1474 - mae: 0.2544 - rmse: 0.3675 - smape: 0.5593 - val_ia: 0.6787 - val_loss: 0.0905 - val_mae: 0.1898 - val_rmse: 0.2624 - val_smape: 0.4807

Epoch 32/128

958/958 - 15s - 15ms/step - ia: 0.8171 - loss: 0.1432 - mae: 0.2526 - rmse: 0.3621 - smape: 0.5556 - val_ia: 0.6854 - val_loss: 0.0890 - val_mae: 0.1866 - val_rmse: 0.2602 - val_smape: 0.4770

Epoch 33/128

958/958 - 15s - 15ms/step - ia: 0.8180 - loss: 0.1422 - mae: 0.2511 - rmse: 0.3618 - smape: 0.5546 - val_ia: 0.6859 - val_loss: 0.0879 - val_mae: 0.1857 - val_rmse: 0.2584 - val_smape: 0.4741

Epoch 34/128

958/958 - 15s - 16ms/step - ia: 0.8194 - loss: 0.1407 - mae: 0.2492 - rmse: 0.3592 - smape: 0.5505 - val_ia: 0.6866 - val_loss: 0.0868 - val_mae: 0.1849 - val_rmse: 0.2571 - val_smape: 0.4723

Epoch 35/128

958/958 - 15s - 16ms/step - ia: 0.8211 - loss: 0.1382 - mae: 0.2475 - rmse: 0.3550 - smape: 0.5492 - val_ia: 0.6881 - val_loss: 0.0862 - val_mae: 0.1841 - val_rmse: 0.2562 - val_smape: 0.4711

Epoch 36/128

958/958 - 15s - 16ms/step - ia: 0.8203 - loss: 0.1425 - mae: 0.2485 - rmse: 0.3596 - smape: 0.5456 - val_ia: 0.6887 - val_loss: 0.0853 - val_mae: 0.1833 - val_rmse: 0.2549 - val_smape: 0.4692

Epoch 37/128

958/958 - 15s - 16ms/step - ia: 0.8223 - loss: 0.1369 - mae: 0.2462 - rmse: 0.3542 - smape: 0.5444 - val_ia: 0.6899 - val_loss: 0.0845 - val_mae: 0.1823 - val_rmse: 0.2536 - val_smape: 0.4674

Epoch 38/128

958/958 - 15s - 16ms/step - ia: 0.8238 - loss: 0.1345 - mae: 0.2438 - rmse: 0.3519 - smape: 0.5416 - val_ia: 0.6948 - val_loss: 0.0828 - val_mae: 0.1794 - val_rmse: 0.2512 - val_smape: 0.4632

Epoch 39/128

958/958 - 15s - 16ms/step - ia: 0.8239 - loss: 0.1362 - mae: 0.2439 - rmse: 0.3521 - smape: 0.5377 - val_ia: 0.6954 - val_loss: 0.0820 - val_mae: 0.1788 - val_rmse: 0.2499 - val_smape: 0.4612

Epoch 40/128

958/958 - 15s - 16ms/step - ia: 0.8237 - loss: 0.1374 - mae: 0.2441 - rmse: 0.3532 - smape: 0.5430 - val_ia: 0.6956 - val_loss: 0.0817 - val_mae: 0.1787 - val_rmse: 0.2495 - val_smape: 0.4604

Epoch 41/128

958/958 - 15s - 16ms/step - ia: 0.8259 - loss: 0.1341 - mae: 0.2410 - rmse: 0.3490 - smape: 0.5345 - val_ia: 0.6973 - val_loss: 0.0805 - val_mae: 0.1774 - val_rmse: 0.2477 - val_smape: 0.4580

Epoch 42/128

958/958 - 20s - 21ms/step - ia: 0.8268 - loss: 0.1296 - mae: 0.2397 - rmse: 0.3450 - smape: 0.5340 - val_ia: 0.7007 - val_loss: 0.0798 - val_mae: 0.1760 - val_rmse: 0.2466 - val_smape: 0.4556

Epoch 43/128

958/958 - 15s - 16ms/step - ia: 0.8278 - loss: 0.1309 - mae: 0.2386 - rmse: 0.3457 - smape: 0.5302 - val_ia: 0.7039 - val_loss: 0.0792 - val_mae: 0.1745 - val_rmse: 0.2450 - val_smape: 0.4526

Epoch 44/128

958/958 - 21s - 22ms/step - ia: 0.8288 - loss: 0.1283 - mae: 0.2371 - rmse: 0.3415 - smape: 0.5273 - val_ia: 0.7028 - val_loss: 0.0789 - val_mae: 0.1749 - val_rmse: 0.2449 - val_smape: 0.4525

Epoch 45/128

958/958 - 15s - 16ms/step - ia: 0.8297 - loss: 0.1294 - mae: 0.2366 - rmse: 0.3434 - smape: 0.5264 - val_ia: 0.7038 - val_loss: 0.0782 - val_mae: 0.1740 - val_rmse: 0.2436 - val_smape: 0.4503

Epoch 46/128

958/958 - 15s - 16ms/step - ia: 0.8308 - loss: 0.1266 - mae: 0.2352 - rmse: 0.3403 - smape: 0.5234 - val_ia: 0.7108 - val_loss: 0.0765 - val_mae: 0.1702 - val_rmse: 0.2410 - val_smape: 0.4456

Epoch 47/128

958/958 - 15s - 16ms/step - ia: 0.8305 - loss: 0.1258 - mae: 0.2352 - rmse: 0.3397 - smape: 0.5243 - val_ia: 0.7068 - val_loss: 0.0763 - val_mae: 0.1712 - val_rmse: 0.2410 - val_smape: 0.4456

Epoch 48/128

958/958 - 15s - 16ms/step - ia: 0.8324 - loss: 0.1268 - mae: 0.2335 - rmse: 0.3390 - smape: 0.5204 - val_ia: 0.7049 - val_loss: 0.0763 - val_mae: 0.1720 - val_rmse: 0.2406 - val_smape: 0.4451

Epoch 49/128

958/958 - 15s - 15ms/step - ia: 0.8317 - loss: 0.1241 - mae: 0.2336 - rmse: 0.3370 - smape: 0.5198 - val_ia: 0.7123 - val_loss: 0.0750 - val_mae: 0.1686 - val_rmse: 0.2384 - val_smape: 0.4407

Epoch 50/128

958/958 - 11s - 12ms/step - ia: 0.8324 - loss: 0.1253 - mae: 0.2327 - rmse: 0.3366 - smape: 0.5182 - val_ia: 0.7111 - val_loss: 0.0746 - val_mae: 0.1687 - val_rmse: 0.2377 - val_smape: 0.4397

Epoch 51/128

958/958 - 11s - 11ms/step - ia: 0.8342 - loss: 0.1204 - mae: 0.2300 - rmse: 0.3314 - smape: 0.5146 - val_ia: 0.7125 - val_loss: 0.0742 - val_mae: 0.1680 - val_rmse: 0.2371 - val_smape: 0.4376

Epoch 52/128

958/958 - 11s - 11ms/step - ia: 0.8337 - loss: 0.1219 - mae: 0.2312 - rmse: 0.3340 - smape: 0.5167 - val_ia: 0.7126 - val_loss: 0.0737 - val_mae: 0.1676 - val_rmse: 0.2363 - val_smape: 0.4366

Epoch 53/128

958/958 - 14s - 14ms/step - ia: 0.8359 - loss: 0.1205 - mae: 0.2278 - rmse: 0.3301 - smape: 0.5112 - val_ia: 0.7179 - val_loss: 0.0726 - val_mae: 0.1651 - val_rmse: 0.2346 - val_smape: 0.4332

Epoch 54/128

958/958 - 15s - 16ms/step - ia: 0.8361 - loss: 0.1198 - mae: 0.2280 - rmse: 0.3302 - smape: 0.5108 - val_ia: 0.7200 - val_loss: 0.0719 - val_mae: 0.1638 - val_rmse: 0.2335 - val_smape: 0.4311

Epoch 55/128

958/958 - 15s - 16ms/step - ia: 0.8366 - loss: 0.1181 - mae: 0.2269 - rmse: 0.3290 - smape: 0.5097 - val_ia: 0.7213 - val_loss: 0.0715 - val_mae: 0.1633 - val_rmse: 0.2324 - val_smape: 0.4295

Epoch 56/128

958/958 - 16s - 16ms/step - ia: 0.8372 - loss: 0.1174 - mae: 0.2264 - rmse: 0.3280 - smape: 0.5096 - val_ia: 0.7211 - val_loss: 0.0709 - val_mae: 0.1630 - val_rmse: 0.2316 - val_smape: 0.4282

Epoch 57/128

958/958 - 15s - 16ms/step - ia: 0.8368 - loss: 0.1179 - mae: 0.2274 - rmse: 0.3286 - smape: 0.5095 - val_ia: 0.7210 - val_loss: 0.0708 - val_mae: 0.1631 - val_rmse: 0.2313 - val_smape: 0.4273

Epoch 58/128

958/958 - 15s - 16ms/step - ia: 0.8383 - loss: 0.1175 - mae: 0.2250 - rmse: 0.3272 - smape: 0.5026 - val_ia: 0.7145 - val_loss: 0.0717 - val_mae: 0.1660 - val_rmse: 0.2326 - val_smape: 0.4296

Epoch 59/128

958/958 - 14s - 15ms/step - ia: 0.8376 - loss: 0.1173 - mae: 0.2254 - rmse: 0.3271 - smape: 0.5048 - val_ia: 0.7244 - val_loss: 0.0697 - val_mae: 0.1610 - val_rmse: 0.2295 - val_smape: 0.4236

Epoch 60/128

958/958 - 11s - 11ms/step - ia: 0.8406 - loss: 0.1150 - mae: 0.2228 - rmse: 0.3230 - smape: 0.4997 - val_ia: 0.7243 - val_loss: 0.0696 - val_mae: 0.1611 - val_rmse: 0.2292 - val_smape: 0.4232

Epoch 61/128

958/958 - 11s - 11ms/step - ia: 0.8401 - loss: 0.1155 - mae: 0.2227 - rmse: 0.3237 - smape: 0.4988 - val_ia: 0.7257 - val_loss: 0.0692 - val_mae: 0.1604 - val_rmse: 0.2282 - val_smape: 0.4215

Epoch 62/128

958/958 - 12s - 13ms/step - ia: 0.8396 - loss: 0.1172 - mae: 0.2235 - rmse: 0.3259 - smape: 0.5001 - val_ia: 0.7252 - val_loss: 0.0689 - val_mae: 0.1602 - val_rmse: 0.2281 - val_smape: 0.4209

Epoch 63/128

958/958 - 15s - 16ms/step - ia: 0.8405 - loss: 0.1143 - mae: 0.2219 - rmse: 0.3230 - smape: 0.4949 - val_ia: 0.7279 - val_loss: 0.0683 - val_mae: 0.1588 - val_rmse: 0.2271 - val_smape: 0.4189

Epoch 64/128

958/958 - 15s - 16ms/step - ia: 0.8425 - loss: 0.1132 - mae: 0.2199 - rmse: 0.3200 - smape: 0.4938 - val_ia: 0.7262 - val_loss: 0.0684 - val_mae: 0.1596 - val_rmse: 0.2270 - val_smape: 0.4191

Epoch 65/128

958/958 - 15s - 15ms/step - ia: 0.8414 - loss: 0.1158 - mae: 0.2217 - rmse: 0.3233 - smape: 0.4931 - val_ia: 0.7235 - val_loss: 0.0688 - val_mae: 0.1610 - val_rmse: 0.2277 - val_smape: 0.4207

Epoch 66/128

958/958 - 15s - 16ms/step - ia: 0.8419 - loss: 0.1125 - mae: 0.2200 - rmse: 0.3201 - smape: 0.4933 - val_ia: 0.7276 - val_loss: 0.0679 - val_mae: 0.1588 - val_rmse: 0.2261 - val_smape: 0.4173

Epoch 67/128

958/958 - 15s - 15ms/step - ia: 0.8429 - loss: 0.1131 - mae: 0.2190 - rmse: 0.3204 - smape: 0.4922 - val_ia: 0.7291 - val_loss: 0.0676 - val_mae: 0.1580 - val_rmse: 0.2254 - val_smape: 0.4159

Epoch 68/128

958/958 - 15s - 16ms/step - ia: 0.8427 - loss: 0.1111 - mae: 0.2190 - rmse: 0.3175 - smape: 0.4911 - val_ia: 0.7298 - val_loss: 0.0673 - val_mae: 0.1576 - val_rmse: 0.2248 - val_smape: 0.4149

Epoch 69/128

958/958 - 15s - 15ms/step - ia: 0.8440 - loss: 0.1096 - mae: 0.2179 - rmse: 0.3155 - smape: 0.4909 - val_ia: 0.7323 - val_loss: 0.0666 - val_mae: 0.1561 - val_rmse: 0.2237 - val_smape: 0.4129

Epoch 70/128

958/958 - 21s - 22ms/step - ia: 0.8442 - loss: 0.1110 - mae: 0.2177 - rmse: 0.3173 - smape: 0.4909 - val_ia: 0.7320 - val_loss: 0.0664 - val_mae: 0.1561 - val_rmse: 0.2233 - val_smape: 0.4119

Epoch 71/128

958/958 - 15s - 15ms/step - ia: 0.8447 - loss: 0.1075 - mae: 0.2165 - rmse: 0.3136 - smape: 0.4883 - val_ia: 0.7327 - val_loss: 0.0660 - val_mae: 0.1556 - val_rmse: 0.2225 - val_smape: 0.4107

Epoch 72/128

958/958 - 21s - 22ms/step - ia: 0.8446 - loss: 0.1099 - mae: 0.2165 - rmse: 0.3143 - smape: 0.4889 - val_ia: 0.7361 - val_loss: 0.0655 - val_mae: 0.1541 - val_rmse: 0.2218 - val_smape: 0.4087

Epoch 73/128

958/958 - 20s - 21ms/step - ia: 0.8466 - loss: 0.1061 - mae: 0.2141 - rmse: 0.3110 - smape: 0.4866 - val_ia: 0.7344 - val_loss: 0.0654 - val_mae: 0.1547 - val_rmse: 0.2214 - val_smape: 0.4082

Epoch 74/128

958/958 - 15s - 15ms/step - ia: 0.8461 - loss: 0.1082 - mae: 0.2149 - rmse: 0.3129 - smape: 0.4834 - val_ia: 0.7325 - val_loss: 0.0654 - val_mae: 0.1554 - val_rmse: 0.2215 - val_smape: 0.4088

Epoch 75/128

958/958 - 15s - 16ms/step - ia: 0.8464 - loss: 0.1082 - mae: 0.2147 - rmse: 0.3136 - smape: 0.4829 - val_ia: 0.7351 - val_loss: 0.0652 - val_mae: 0.1543 - val_rmse: 0.2210 - val_smape: 0.4073

Epoch 76/128

958/958 - 20s - 21ms/step - ia: 0.8462 - loss: 0.1073 - mae: 0.2142 - rmse: 0.3122 - smape: 0.4838 - val_ia: 0.7319 - val_loss: 0.0653 - val_mae: 0.1553 - val_rmse: 0.2214 - val_smape: 0.4080

Epoch 77/128

958/958 - 11s - 11ms/step - ia: 0.8477 - loss: 0.1067 - mae: 0.2129 - rmse: 0.3104 - smape: 0.4819 - val_ia: 0.7345 - val_loss: 0.0648 - val_mae: 0.1541 - val_rmse: 0.2204 - val_smape: 0.4062

Epoch 78/128

958/958 - 11s - 11ms/step - ia: 0.8457 - loss: 0.1085 - mae: 0.2149 - rmse: 0.3134 - smape: 0.4855 - val_ia: 0.7420 - val_loss: 0.0643 - val_mae: 0.1515 - val_rmse: 0.2191 - val_smape: 0.4027

Epoch 79/128

958/958 - 11s - 11ms/step - ia: 0.8491 - loss: 0.1048 - mae: 0.2108 - rmse: 0.3084 - smape: 0.4774 - val_ia: 0.7396 - val_loss: 0.0642 - val_mae: 0.1522 - val_rmse: 0.2189 - val_smape: 0.4029

Epoch 80/128

958/958 - 14s - 15ms/step - ia: 0.8480 - loss: 0.1050 - mae: 0.2119 - rmse: 0.3078 - smape: 0.4809 - val_ia: 0.7394 - val_loss: 0.0641 - val_mae: 0.1522 - val_rmse: 0.2185 - val_smape: 0.4022

Epoch 81/128

958/958 - 15s - 16ms/step - ia: 0.8484 - loss: 0.1046 - mae: 0.2115 - rmse: 0.3084 - smape: 0.4779 - val_ia: 0.7397 - val_loss: 0.0640 - val_mae: 0.1521 - val_rmse: 0.2183 - val_smape: 0.4017

Epoch 82/128

958/958 - 20s - 21ms/step - ia: 0.8500 - loss: 0.1037 - mae: 0.2103 - rmse: 0.3069 - smape: 0.4761 - val_ia: 0.7399 - val_loss: 0.0637 - val_mae: 0.1516 - val_rmse: 0.2180 - val_smape: 0.4008

Epoch 83/128

958/958 - 11s - 11ms/step - ia: 0.8486 - loss: 0.1049 - mae: 0.2116 - rmse: 0.3085 - smape: 0.4781 - val_ia: 0.7412 - val_loss: 0.0634 - val_mae: 0.1510 - val_rmse: 0.2173 - val_smape: 0.3996

Epoch 84/128

958/958 - 20s - 21ms/step - ia: 0.8493 - loss: 0.1048 - mae: 0.2104 - rmse: 0.3077 - smape: 0.4747 - val_ia: 0.7444 - val_loss: 0.0629 - val_mae: 0.1495 - val_rmse: 0.2164 - val_smape: 0.3974

Epoch 85/128

958/958 - 13s - 14ms/step - ia: 0.8509 - loss: 0.1025 - mae: 0.2086 - rmse: 0.3043 - smape: 0.4736 - val_ia: 0.7431 - val_loss: 0.0630 - val_mae: 0.1500 - val_rmse: 0.2165 - val_smape: 0.3976

Epoch 86/128

958/958 - 21s - 22ms/step - ia: 0.8508 - loss: 0.1041 - mae: 0.2094 - rmse: 0.3058 - smape: 0.4757 - val_ia: 0.7418 - val_loss: 0.0630 - val_mae: 0.1505 - val_rmse: 0.2165 - val_smape: 0.3977

Epoch 87/128

958/958 - 14s - 15ms/step - ia: 0.8501 - loss: 0.1038 - mae: 0.2100 - rmse: 0.3062 - smape: 0.4756 - val_ia: 0.7464 - val_loss: 0.0626 - val_mae: 0.1488 - val_rmse: 0.2155 - val_smape: 0.3957

Epoch 88/128

958/958 - 15s - 15ms/step - ia: 0.8515 - loss: 0.1032 - mae: 0.2082 - rmse: 0.3050 - smape: 0.4681 - val_ia: 0.7449 - val_loss: 0.0624 - val_mae: 0.1491 - val_rmse: 0.2150 - val_smape: 0.3954

Epoch 89/128

958/958 - 21s - 22ms/step - ia: 0.8511 - loss: 0.1043 - mae: 0.2080 - rmse: 0.3061 - smape: 0.4682 - val_ia: 0.7437 - val_loss: 0.0623 - val_mae: 0.1494 - val_rmse: 0.2150 - val_smape: 0.3956

Epoch 90/128

958/958 - 15s - 16ms/step - ia: 0.8513 - loss: 0.1022 - mae: 0.2075 - rmse: 0.3031 - smape: 0.4703 - val_ia: 0.7474 - val_loss: 0.0619 - val_mae: 0.1478 - val_rmse: 0.2142 - val_smape: 0.3937

Epoch 91/128

958/958 - 26s - 28ms/step - ia: 0.8512 - loss: 0.1047 - mae: 0.2084 - rmse: 0.3057 - smape: 0.4698 - val_ia: 0.7477 - val_loss: 0.0617 - val_mae: 0.1476 - val_rmse: 0.2140 - val_smape: 0.3934

Epoch 92/128

958/958 - 30s - 32ms/step - ia: 0.8527 - loss: 0.1000 - mae: 0.2061 - rmse: 0.3011 - smape: 0.4660 - val_ia: 0.7482 - val_loss: 0.0616 - val_mae: 0.1474 - val_rmse: 0.2135 - val_smape: 0.3926

Epoch 93/128

958/958 - 10s - 11ms/step - ia: 0.8519 - loss: 0.1008 - mae: 0.2065 - rmse: 0.3018 - smape: 0.4665 - val_ia: 0.7489 - val_loss: 0.0614 - val_mae: 0.1469 - val_rmse: 0.2132 - val_smape: 0.3919

Epoch 94/128

958/958 - 11s - 12ms/step - ia: 0.8528 - loss: 0.1022 - mae: 0.2066 - rmse: 0.3036 - smape: 0.4680 - val_ia: 0.7452 - val_loss: 0.0617 - val_mae: 0.1484 - val_rmse: 0.2137 - val_smape: 0.3932

Epoch 95/128

958/958 - 23s - 24ms/step - ia: 0.8537 - loss: 0.0976 - mae: 0.2038 - rmse: 0.2979 - smape: 0.4637 - val_ia: 0.7491 - val_loss: 0.0611 - val_mae: 0.1466 - val_rmse: 0.2127 - val_smape: 0.3908

Epoch 96/128

958/958 - 14s - 14ms/step - ia: 0.8538 - loss: 0.0994 - mae: 0.2043 - rmse: 0.3002 - smape: 0.4624 - val_ia: 0.7491 - val_loss: 0.0610 - val_mae: 0.1467 - val_rmse: 0.2123 - val_smape: 0.3901

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 12s - 24ms/step - ia: 0.1746 - loss: 1.0785 - mae: 0.7718 - rmse: 1.0267 - smape: 1.6235 - val_ia: 0.2490 - val_loss: 1.0805 - val_mae: 0.7849 - val_rmse: 0.9002 - val_smape: 1.7016

Epoch 2/128

479/479 - 5s - 10ms/step - ia: 0.1830 - loss: 1.0570 - mae: 0.7629 - rmse: 1.0162 - smape: 1.6084 - val_ia: 0.2534 - val_loss: 1.0586 - val_mae: 0.7764 - val_rmse: 0.8909 - val_smape: 1.6830

Epoch 3/128

479/479 - 5s - 10ms/step - ia: 0.1956 - loss: 1.0346 - mae: 0.7537 - rmse: 1.0049 - smape: 1.5896 - val_ia: 0.2580 - val_loss: 1.0368 - val_mae: 0.7678 - val_rmse: 0.8815 - val_smape: 1.6639

Epoch 4/128

479/479 - 4s - 9ms/step - ia: 0.2040 - loss: 1.0128 - mae: 0.7456 - rmse: 0.9938 - smape: 1.5746 - val_ia: 0.2626 - val_loss: 1.0151 - val_mae: 0.7593 - val_rmse: 0.8721 - val_smape: 1.6447

Epoch 5/128

479/479 - 4s - 9ms/step - ia: 0.2128 - loss: 0.9911 - mae: 0.7367 - rmse: 0.9838 - smape: 1.5567 - val_ia: 0.2674 - val_loss: 0.9935 - val_mae: 0.7506 - val_rmse: 0.8625 - val_smape: 1.6257

Epoch 6/128

479/479 - 4s - 9ms/step - ia: 0.2270 - loss: 0.9716 - mae: 0.7277 - rmse: 0.9734 - smape: 1.5370 - val_ia: 0.2723 - val_loss: 0.9719 - val_mae: 0.7418 - val_rmse: 0.8529 - val_smape: 1.6064

Epoch 7/128

479/479 - 4s - 9ms/step - ia: 0.2350 - loss: 0.9481 - mae: 0.7197 - rmse: 0.9614 - smape: 1.5269 - val_ia: 0.2774 - val_loss: 0.9502 - val_mae: 0.7329 - val_rmse: 0.8432 - val_smape: 1.5874

Epoch 8/128

479/479 - 4s - 9ms/step - ia: 0.2490 - loss: 0.9268 - mae: 0.7095 - rmse: 0.9494 - smape: 1.4998 - val_ia: 0.2828 - val_loss: 0.9285 - val_mae: 0.7238 - val_rmse: 0.8333 - val_smape: 1.5677

Epoch 9/128

479/479 - 4s - 9ms/step - ia: 0.2597 - loss: 0.9061 - mae: 0.7003 - rmse: 0.9389 - smape: 1.4829 - val_ia: 0.2884 - val_loss: 0.9065 - val_mae: 0.7145 - val_rmse: 0.8232 - val_smape: 1.5481

Epoch 10/128

479/479 - 4s - 9ms/step - ia: 0.2722 - loss: 0.8885 - mae: 0.6930 - rmse: 0.9303 - smape: 1.4647 - val_ia: 0.2941 - val_loss: 0.8844 - val_mae: 0.7050 - val_rmse: 0.8128 - val_smape: 1.5281

Epoch 11/128

479/479 - 4s - 9ms/step - ia: 0.2853 - loss: 0.8639 - mae: 0.6823 - rmse: 0.9169 - smape: 1.4436 - val_ia: 0.3002 - val_loss: 0.8621 - val_mae: 0.6953 - val_rmse: 0.8023 - val_smape: 1.5074

Epoch 12/128

479/479 - 4s - 9ms/step - ia: 0.3009 - loss: 0.8460 - mae: 0.6737 - rmse: 0.9070 - smape: 1.4221 - val_ia: 0.3063 - val_loss: 0.8397 - val_mae: 0.6853 - val_rmse: 0.7915 - val_smape: 1.4869

Epoch 13/128

479/479 - 4s - 9ms/step - ia: 0.3117 - loss: 0.8225 - mae: 0.6642 - rmse: 0.8951 - smape: 1.3997 - val_ia: 0.3127 - val_loss: 0.8173 - val_mae: 0.6752 - val_rmse: 0.7806 - val_smape: 1.4659

Epoch 14/128

479/479 - 5s - 10ms/step - ia: 0.3281 - loss: 0.8018 - mae: 0.6536 - rmse: 0.8829 - smape: 1.3735 - val_ia: 0.3192 - val_loss: 0.7947 - val_mae: 0.6648 - val_rmse: 0.7694 - val_smape: 1.4449

Epoch 15/128

479/479 - 5s - 10ms/step - ia: 0.3399 - loss: 0.7856 - mae: 0.6457 - rmse: 0.8738 - smape: 1.3567 - val_ia: 0.3259 - val_loss: 0.7722 - val_mae: 0.6542 - val_rmse: 0.7580 - val_smape: 1.4234

Epoch 16/128

479/479 - 5s - 11ms/step - ia: 0.3562 - loss: 0.7584 - mae: 0.6341 - rmse: 0.8581 - smape: 1.3289 - val_ia: 0.3329 - val_loss: 0.7496 - val_mae: 0.6433 - val_rmse: 0.7465 - val_smape: 1.4016

Epoch 17/128

479/479 - 5s - 11ms/step - ia: 0.3708 - loss: 0.7392 - mae: 0.6236 - rmse: 0.8483 - smape: 1.3058 - val_ia: 0.3402 - val_loss: 0.7271 - val_mae: 0.6323 - val_rmse: 0.7348 - val_smape: 1.3792

Epoch 18/128

479/479 - 4s - 9ms/step - ia: 0.3858 - loss: 0.7207 - mae: 0.6145 - rmse: 0.8364 - smape: 1.2851 - val_ia: 0.3477 - val_loss: 0.7043 - val_mae: 0.6210 - val_rmse: 0.7228 - val_smape: 1.3562

Epoch 19/128

479/479 - 4s - 9ms/step - ia: 0.4011 - loss: 0.6948 - mae: 0.6027 - rmse: 0.8225 - smape: 1.2600 - val_ia: 0.3555 - val_loss: 0.6818 - val_mae: 0.6095 - val_rmse: 0.7107 - val_smape: 1.3325

Epoch 20/128

479/479 - 5s - 10ms/step - ia: 0.4156 - loss: 0.6794 - mae: 0.5934 - rmse: 0.8124 - smape: 1.2371 - val_ia: 0.3635 - val_loss: 0.6592 - val_mae: 0.5979 - val_rmse: 0.6984 - val_smape: 1.3079

Epoch 21/128

479/479 - 4s - 9ms/step - ia: 0.4341 - loss: 0.6543 - mae: 0.5802 - rmse: 0.7966 - smape: 1.2073 - val_ia: 0.3716 - val_loss: 0.6369 - val_mae: 0.5861 - val_rmse: 0.6860 - val_smape: 1.2826

Epoch 22/128

479/479 - 5s - 11ms/step - ia: 0.4480 - loss: 0.6355 - mae: 0.5710 - rmse: 0.7848 - smape: 1.1893 - val_ia: 0.3799 - val_loss: 0.6148 - val_mae: 0.5741 - val_rmse: 0.6736 - val_smape: 1.2565

Epoch 23/128

479/479 - 4s - 9ms/step - ia: 0.4620 - loss: 0.6206 - mae: 0.5617 - rmse: 0.7757 - smape: 1.1649 - val_ia: 0.3883 - val_loss: 0.5927 - val_mae: 0.5620 - val_rmse: 0.6609 - val_smape: 1.2292

Epoch 24/128

479/479 - 5s - 11ms/step - ia: 0.4754 - loss: 0.5986 - mae: 0.5511 - rmse: 0.7623 - smape: 1.1453 - val_ia: 0.3971 - val_loss: 0.5708 - val_mae: 0.5498 - val_rmse: 0.6482 - val_smape: 1.2003

Epoch 25/128

479/479 - 5s - 10ms/step - ia: 0.4930 - loss: 0.5821 - mae: 0.5395 - rmse: 0.7506 - smape: 1.1159 - val_ia: 0.4063 - val_loss: 0.5494 - val_mae: 0.5375 - val_rmse: 0.6356 - val_smape: 1.1715

Epoch 26/128

479/479 - 4s - 9ms/step - ia: 0.5089 - loss: 0.5591 - mae: 0.5281 - rmse: 0.7359 - smape: 1.0922 - val_ia: 0.4158 - val_loss: 0.5281 - val_mae: 0.5251 - val_rmse: 0.6228 - val_smape: 1.1421

Epoch 27/128

479/479 - 5s - 11ms/step - ia: 0.5229 - loss: 0.5409 - mae: 0.5188 - rmse: 0.7237 - smape: 1.0727 - val_ia: 0.4257 - val_loss: 0.5076 - val_mae: 0.5128 - val_rmse: 0.6102 - val_smape: 1.1130

Epoch 28/128

479/479 - 4s - 9ms/step - ia: 0.5374 - loss: 0.5233 - mae: 0.5083 - rmse: 0.7121 - smape: 1.0484 - val_ia: 0.4356 - val_loss: 0.4874 - val_mae: 0.5006 - val_rmse: 0.5976 - val_smape: 1.0835

Epoch 29/128

479/479 - 4s - 9ms/step - ia: 0.5528 - loss: 0.5057 - mae: 0.4972 - rmse: 0.6992 - smape: 1.0235 - val_ia: 0.4458 - val_loss: 0.4678 - val_mae: 0.4884 - val_rmse: 0.5852 - val_smape: 1.0547

Epoch 30/128

479/479 - 5s - 11ms/step - ia: 0.5650 - loss: 0.4903 - mae: 0.4875 - rmse: 0.6869 - smape: 1.0037 - val_ia: 0.4560 - val_loss: 0.4488 - val_mae: 0.4762 - val_rmse: 0.5729 - val_smape: 1.0259

Epoch 31/128

479/479 - 5s - 11ms/step - ia: 0.5784 - loss: 0.4752 - mae: 0.4787 - rmse: 0.6769 - smape: 0.9827 - val_ia: 0.4657 - val_loss: 0.4305 - val_mae: 0.4645 - val_rmse: 0.5610 - val_smape: 0.9977

Epoch 32/128

479/479 - 5s - 11ms/step - ia: 0.5909 - loss: 0.4591 - mae: 0.4700 - rmse: 0.6656 - smape: 0.9648 - val_ia: 0.4754 - val_loss: 0.4130 - val_mae: 0.4529 - val_rmse: 0.5492 - val_smape: 0.9693

Epoch 33/128

479/479 - 4s - 9ms/step - ia: 0.6066 - loss: 0.4412 - mae: 0.4580 - rmse: 0.6512 - smape: 0.9410 - val_ia: 0.4851 - val_loss: 0.3963 - val_mae: 0.4415 - val_rmse: 0.5376 - val_smape: 0.9427

Epoch 34/128

479/479 - 4s - 9ms/step - ia: 0.6154 - loss: 0.4329 - mae: 0.4517 - rmse: 0.6455 - smape: 0.9243 - val_ia: 0.4947 - val_loss: 0.3804 - val_mae: 0.4305 - val_rmse: 0.5266 - val_smape: 0.9176

Epoch 35/128

479/479 - 5s - 11ms/step - ia: 0.6281 - loss: 0.4148 - mae: 0.4424 - rmse: 0.6312 - smape: 0.9065 - val_ia: 0.5042 - val_loss: 0.3656 - val_mae: 0.4199 - val_rmse: 0.5160 - val_smape: 0.8934

Epoch 36/128

479/479 - 5s - 11ms/step - ia: 0.6396 - loss: 0.4027 - mae: 0.4335 - rmse: 0.6213 - smape: 0.8874 - val_ia: 0.5135 - val_loss: 0.3514 - val_mae: 0.4096 - val_rmse: 0.5058 - val_smape: 0.8697

Epoch 37/128

479/479 - 3s - 7ms/step - ia: 0.6468 - loss: 0.3947 - mae: 0.4282 - rmse: 0.6161 - smape: 0.8722 - val_ia: 0.5228 - val_loss: 0.3381 - val_mae: 0.3997 - val_rmse: 0.4961 - val_smape: 0.8465

Epoch 38/128

479/479 - 3s - 6ms/step - ia: 0.6574 - loss: 0.3803 - mae: 0.4202 - rmse: 0.6041 - smape: 0.8584 - val_ia: 0.5319 - val_loss: 0.3260 - val_mae: 0.3903 - val_rmse: 0.4870 - val_smape: 0.8247

Epoch 39/128

479/479 - 3s - 6ms/step - ia: 0.6681 - loss: 0.3679 - mae: 0.4120 - rmse: 0.5936 - smape: 0.8408 - val_ia: 0.5409 - val_loss: 0.3148 - val_mae: 0.3815 - val_rmse: 0.4785 - val_smape: 0.8042

Epoch 40/128

479/479 - 3s - 6ms/step - ia: 0.6771 - loss: 0.3588 - mae: 0.4055 - rmse: 0.5862 - smape: 0.8253 - val_ia: 0.5500 - val_loss: 0.3044 - val_mae: 0.3730 - val_rmse: 0.4704 - val_smape: 0.7847

Epoch 41/128

479/479 - 3s - 7ms/step - ia: 0.6841 - loss: 0.3507 - mae: 0.4003 - rmse: 0.5798 - smape: 0.8134 - val_ia: 0.5588 - val_loss: 0.2949 - val_mae: 0.3651 - val_rmse: 0.4630 - val_smape: 0.7674

Epoch 42/128

479/479 - 5s - 11ms/step - ia: 0.6918 - loss: 0.3417 - mae: 0.3934 - rmse: 0.5726 - smape: 0.7986 - val_ia: 0.5675 - val_loss: 0.2862 - val_mae: 0.3577 - val_rmse: 0.4561 - val_smape: 0.7516

Epoch 43/128

479/479 - 5s - 11ms/step - ia: 0.6987 - loss: 0.3354 - mae: 0.3886 - rmse: 0.5675 - smape: 0.7859 - val_ia: 0.5757 - val_loss: 0.2784 - val_mae: 0.3510 - val_rmse: 0.4500 - val_smape: 0.7375

Epoch 44/128

479/479 - 3s - 6ms/step - ia: 0.7030 - loss: 0.3283 - mae: 0.3854 - rmse: 0.5608 - smape: 0.7795 - val_ia: 0.5839 - val_loss: 0.2712 - val_mae: 0.3445 - val_rmse: 0.4441 - val_smape: 0.7240

Epoch 45/128

479/479 - 5s - 11ms/step - ia: 0.7097 - loss: 0.3215 - mae: 0.3801 - rmse: 0.5558 - smape: 0.7692 - val_ia: 0.5914 - val_loss: 0.2649 - val_mae: 0.3388 - val_rmse: 0.4390 - val_smape: 0.7120

Epoch 46/128

479/479 - 3s - 7ms/step - ia: 0.7128 - loss: 0.3205 - mae: 0.3785 - rmse: 0.5533 - smape: 0.7629 - val_ia: 0.5987 - val_loss: 0.2590 - val_mae: 0.3334 - val_rmse: 0.4342 - val_smape: 0.7006

Epoch 47/128

479/479 - 6s - 13ms/step - ia: 0.7180 - loss: 0.3117 - mae: 0.3736 - rmse: 0.5461 - smape: 0.7534 - val_ia: 0.6053 - val_loss: 0.2537 - val_mae: 0.3285 - val_rmse: 0.4298 - val_smape: 0.6908

Epoch 48/128

479/479 - 5s - 11ms/step - ia: 0.7232 - loss: 0.3083 - mae: 0.3702 - rmse: 0.5434 - smape: 0.7458 - val_ia: 0.6117 - val_loss: 0.2488 - val_mae: 0.3239 - val_rmse: 0.4256 - val_smape: 0.6815

Epoch 49/128

479/479 - 4s - 9ms/step - ia: 0.7262 - loss: 0.3028 - mae: 0.3670 - rmse: 0.5384 - smape: 0.7397 - val_ia: 0.6174 - val_loss: 0.2444 - val_mae: 0.3199 - val_rmse: 0.4220 - val_smape: 0.6735

Epoch 50/128

479/479 - 4s - 9ms/step - ia: 0.7299 - loss: 0.2970 - mae: 0.3637 - rmse: 0.5339 - smape: 0.7312 - val_ia: 0.6226 - val_loss: 0.2404 - val_mae: 0.3161 - val_rmse: 0.4186 - val_smape: 0.6666

Epoch 51/128

479/479 - 5s - 11ms/step - ia: 0.7337 - loss: 0.2935 - mae: 0.3601 - rmse: 0.5297 - smape: 0.7265 - val_ia: 0.6272 - val_loss: 0.2366 - val_mae: 0.3126 - val_rmse: 0.4154 - val_smape: 0.6602

Epoch 52/128

479/479 - 4s - 9ms/step - ia: 0.7361 - loss: 0.2896 - mae: 0.3592 - rmse: 0.5255 - smape: 0.7240 - val_ia: 0.6318 - val_loss: 0.2330 - val_mae: 0.3092 - val_rmse: 0.4123 - val_smape: 0.6537

Epoch 53/128

479/479 - 4s - 9ms/step - ia: 0.7384 - loss: 0.2880 - mae: 0.3566 - rmse: 0.5241 - smape: 0.7171 - val_ia: 0.6358 - val_loss: 0.2296 - val_mae: 0.3059 - val_rmse: 0.4093 - val_smape: 0.6476

Epoch 54/128

479/479 - 4s - 9ms/step - ia: 0.7399 - loss: 0.2851 - mae: 0.3553 - rmse: 0.5222 - smape: 0.7148 - val_ia: 0.6396 - val_loss: 0.2264 - val_mae: 0.3028 - val_rmse: 0.4064 - val_smape: 0.6422

Epoch 55/128

479/479 - 5s - 9ms/step - ia: 0.7424 - loss: 0.2828 - mae: 0.3528 - rmse: 0.5199 - smape: 0.7081 - val_ia: 0.6429 - val_loss: 0.2235 - val_mae: 0.3001 - val_rmse: 0.4039 - val_smape: 0.6373

Epoch 56/128

479/479 - 4s - 8ms/step - ia: 0.7456 - loss: 0.2768 - mae: 0.3488 - rmse: 0.5155 - smape: 0.7062 - val_ia: 0.6461 - val_loss: 0.2207 - val_mae: 0.2976 - val_rmse: 0.4015 - val_smape: 0.6329

Epoch 57/128

479/479 - 3s - 6ms/step - ia: 0.7470 - loss: 0.2763 - mae: 0.3484 - rmse: 0.5138 - smape: 0.7024 - val_ia: 0.6492 - val_loss: 0.2180 - val_mae: 0.2951 - val_rmse: 0.3990 - val_smape: 0.6287

Epoch 58/128

479/479 - 3s - 6ms/step - ia: 0.7487 - loss: 0.2747 - mae: 0.3465 - rmse: 0.5110 - smape: 0.6997 - val_ia: 0.6519 - val_loss: 0.2154 - val_mae: 0.2926 - val_rmse: 0.3967 - val_smape: 0.6247

Epoch 59/128

479/479 - 3s - 7ms/step - ia: 0.7511 - loss: 0.2692 - mae: 0.3436 - rmse: 0.5073 - smape: 0.6923 - val_ia: 0.6544 - val_loss: 0.2130 - val_mae: 0.2904 - val_rmse: 0.3944 - val_smape: 0.6209

Epoch 60/128

479/479 - 5s - 11ms/step - ia: 0.7508 - loss: 0.2702 - mae: 0.3446 - rmse: 0.5084 - smape: 0.6959 - val_ia: 0.6568 - val_loss: 0.2107 - val_mae: 0.2884 - val_rmse: 0.3924 - val_smape: 0.6173

Epoch 61/128

479/479 - 5s - 11ms/step - ia: 0.7554 - loss: 0.2654 - mae: 0.3390 - rmse: 0.5037 - smape: 0.6858 - val_ia: 0.6591 - val_loss: 0.2084 - val_mae: 0.2864 - val_rmse: 0.3904 - val_smape: 0.6140

Epoch 62/128

479/479 - 3s - 7ms/step - ia: 0.7536 - loss: 0.2653 - mae: 0.3412 - rmse: 0.5033 - smape: 0.6894 - val_ia: 0.6612 - val_loss: 0.2062 - val_mae: 0.2845 - val_rmse: 0.3884 - val_smape: 0.6109

Epoch 63/128

479/479 - 3s - 7ms/step - ia: 0.7562 - loss: 0.2635 - mae: 0.3387 - rmse: 0.5020 - smape: 0.6825 - val_ia: 0.6632 - val_loss: 0.2041 - val_mae: 0.2826 - val_rmse: 0.3864 - val_smape: 0.6077

Epoch 64/128

479/479 - 3s - 7ms/step - ia: 0.7572 - loss: 0.2591 - mae: 0.3370 - rmse: 0.4978 - smape: 0.6821 - val_ia: 0.6650 - val_loss: 0.2020 - val_mae: 0.2809 - val_rmse: 0.3846 - val_smape: 0.6049

Epoch 65/128

479/479 - 4s - 7ms/step - ia: 0.7585 - loss: 0.2587 - mae: 0.3360 - rmse: 0.4969 - smape: 0.6788 - val_ia: 0.6667 - val_loss: 0.2001 - val_mae: 0.2793 - val_rmse: 0.3828 - val_smape: 0.6025

Epoch 66/128

479/479 - 3s - 7ms/step - ia: 0.7608 - loss: 0.2552 - mae: 0.3329 - rmse: 0.4947 - smape: 0.6754 - val_ia: 0.6683 - val_loss: 0.1981 - val_mae: 0.2776 - val_rmse: 0.3809 - val_smape: 0.6000

Epoch 67/128

479/479 - 4s - 7ms/step - ia: 0.7602 - loss: 0.2563 - mae: 0.3332 - rmse: 0.4936 - smape: 0.6736 - val_ia: 0.6700 - val_loss: 0.1963 - val_mae: 0.2760 - val_rmse: 0.3792 - val_smape: 0.5975

Epoch 68/128

479/479 - 6s - 12ms/step - ia: 0.7614 - loss: 0.2541 - mae: 0.3320 - rmse: 0.4917 - smape: 0.6757 - val_ia: 0.6716 - val_loss: 0.1945 - val_mae: 0.2746 - val_rmse: 0.3776 - val_smape: 0.5952

Epoch 69/128

479/479 - 5s - 10ms/step - ia: 0.7623 - loss: 0.2544 - mae: 0.3315 - rmse: 0.4927 - smape: 0.6729 - val_ia: 0.6732 - val_loss: 0.1928 - val_mae: 0.2731 - val_rmse: 0.3760 - val_smape: 0.5930

Epoch 70/128

479/479 - 6s - 13ms/step - ia: 0.7626 - loss: 0.2522 - mae: 0.3310 - rmse: 0.4906 - smape: 0.6734 - val_ia: 0.6746 - val_loss: 0.1911 - val_mae: 0.2717 - val_rmse: 0.3744 - val_smape: 0.5909

Epoch 71/128

479/479 - 5s - 9ms/step - ia: 0.7640 - loss: 0.2499 - mae: 0.3292 - rmse: 0.4890 - smape: 0.6692 - val_ia: 0.6760 - val_loss: 0.1894 - val_mae: 0.2703 - val_rmse: 0.3727 - val_smape: 0.5888

Epoch 72/128

479/479 - 5s - 10ms/step - ia: 0.7655 - loss: 0.2450 - mae: 0.3264 - rmse: 0.4838 - smape: 0.6670 - val_ia: 0.6775 - val_loss: 0.1878 - val_mae: 0.2689 - val_rmse: 0.3713 - val_smape: 0.5868

Epoch 73/128

479/479 - 4s - 9ms/step - ia: 0.7671 - loss: 0.2457 - mae: 0.3254 - rmse: 0.4834 - smape: 0.6634 - val_ia: 0.6790 - val_loss: 0.1862 - val_mae: 0.2676 - val_rmse: 0.3697 - val_smape: 0.5846

Epoch 74/128

479/479 - 5s - 11ms/step - ia: 0.7660 - loss: 0.2471 - mae: 0.3263 - rmse: 0.4861 - smape: 0.6658 - val_ia: 0.6804 - val_loss: 0.1846 - val_mae: 0.2662 - val_rmse: 0.3682 - val_smape: 0.5825

Epoch 75/128

479/479 - 4s - 9ms/step - ia: 0.7667 - loss: 0.2427 - mae: 0.3250 - rmse: 0.4813 - smape: 0.6639 - val_ia: 0.6819 - val_loss: 0.1831 - val_mae: 0.2650 - val_rmse: 0.3668 - val_smape: 0.5806

Epoch 76/128

479/479 - 4s - 9ms/step - ia: 0.7693 - loss: 0.2413 - mae: 0.3230 - rmse: 0.4795 - smape: 0.6619 - val_ia: 0.6832 - val_loss: 0.1816 - val_mae: 0.2638 - val_rmse: 0.3653 - val_smape: 0.5787

Epoch 77/128

479/479 - 4s - 9ms/step - ia: 0.7709 - loss: 0.2394 - mae: 0.3209 - rmse: 0.4772 - smape: 0.6565 - val_ia: 0.6843 - val_loss: 0.1801 - val_mae: 0.2625 - val_rmse: 0.3638 - val_smape: 0.5770

Epoch 78/128

479/479 - 4s - 9ms/step - ia: 0.7689 - loss: 0.2404 - mae: 0.3232 - rmse: 0.4782 - smape: 0.6589 - val_ia: 0.6854 - val_loss: 0.1787 - val_mae: 0.2613 - val_rmse: 0.3624 - val_smape: 0.5753

Epoch 79/128

479/479 - 4s - 9ms/step - ia: 0.7721 - loss: 0.2346 - mae: 0.3187 - rmse: 0.4726 - smape: 0.6553 - val_ia: 0.6866 - val_loss: 0.1773 - val_mae: 0.2601 - val_rmse: 0.3611 - val_smape: 0.5737

Epoch 80/128

479/479 - 4s - 9ms/step - ia: 0.7721 - loss: 0.2341 - mae: 0.3188 - rmse: 0.4714 - smape: 0.6552 - val_ia: 0.6878 - val_loss: 0.1759 - val_mae: 0.2590 - val_rmse: 0.3597 - val_smape: 0.5721

Epoch 81/128

479/479 - 4s - 9ms/step - ia: 0.7734 - loss: 0.2313 - mae: 0.3173 - rmse: 0.4704 - smape: 0.6510 - val_ia: 0.6891 - val_loss: 0.1745 - val_mae: 0.2579 - val_rmse: 0.3584 - val_smape: 0.5704

Epoch 82/128

479/479 - 4s - 9ms/step - ia: 0.7736 - loss: 0.2329 - mae: 0.3168 - rmse: 0.4696 - smape: 0.6508 - val_ia: 0.6902 - val_loss: 0.1732 - val_mae: 0.2568 - val_rmse: 0.3571 - val_smape: 0.5688

Epoch 83/128

479/479 - 5s - 10ms/step - ia: 0.7747 - loss: 0.2302 - mae: 0.3150 - rmse: 0.4681 - smape: 0.6482 - val_ia: 0.6913 - val_loss: 0.1719 - val_mae: 0.2557 - val_rmse: 0.3559 - val_smape: 0.5673

Epoch 84/128

479/479 - 4s - 9ms/step - ia: 0.7764 - loss: 0.2290 - mae: 0.3133 - rmse: 0.4665 - smape: 0.6470 - val_ia: 0.6925 - val_loss: 0.1706 - val_mae: 0.2546 - val_rmse: 0.3546 - val_smape: 0.5657

Epoch 85/128

479/479 - 4s - 9ms/step - ia: 0.7756 - loss: 0.2265 - mae: 0.3140 - rmse: 0.4641 - smape: 0.6476 - val_ia: 0.6936 - val_loss: 0.1693 - val_mae: 0.2536 - val_rmse: 0.3533 - val_smape: 0.5642

Epoch 86/128

479/479 - 4s - 9ms/step - ia: 0.7773 - loss: 0.2269 - mae: 0.3130 - rmse: 0.4635 - smape: 0.6450 - val_ia: 0.6947 - val_loss: 0.1681 - val_mae: 0.2526 - val_rmse: 0.3521 - val_smape: 0.5628

Epoch 87/128

479/479 - 4s - 8ms/step - ia: 0.7776 - loss: 0.2253 - mae: 0.3112 - rmse: 0.4633 - smape: 0.6410 - val_ia: 0.6959 - val_loss: 0.1669 - val_mae: 0.2515 - val_rmse: 0.3509 - val_smape: 0.5612

Epoch 88/128

479/479 - 3s - 7ms/step - ia: 0.7772 - loss: 0.2257 - mae: 0.3118 - rmse: 0.4637 - smape: 0.6441 - val_ia: 0.6971 - val_loss: 0.1656 - val_mae: 0.2505 - val_rmse: 0.3497 - val_smape: 0.5595

Epoch 89/128

479/479 - 3s - 7ms/step - ia: 0.7783 - loss: 0.2216 - mae: 0.3110 - rmse: 0.4590 - smape: 0.6432 - val_ia: 0.6981 - val_loss: 0.1644 - val_mae: 0.2495 - val_rmse: 0.3485 - val_smape: 0.5580

Epoch 90/128

479/479 - 3s - 7ms/step - ia: 0.7798 - loss: 0.2224 - mae: 0.3091 - rmse: 0.4610 - smape: 0.6405 - val_ia: 0.6993 - val_loss: 0.1633 - val_mae: 0.2485 - val_rmse: 0.3474 - val_smape: 0.5566

Epoch 91/128

479/479 - 3s - 7ms/step - ia: 0.7800 - loss: 0.2206 - mae: 0.3083 - rmse: 0.4577 - smape: 0.6377 - val_ia: 0.7004 - val_loss: 0.1622 - val_mae: 0.2476 - val_rmse: 0.3463 - val_smape: 0.5552

Epoch 92/128

479/479 - 3s - 7ms/step - ia: 0.7786 - loss: 0.2217 - mae: 0.3097 - rmse: 0.4591 - smape: 0.6419 - val_ia: 0.7015 - val_loss: 0.1611 - val_mae: 0.2466 - val_rmse: 0.3452 - val_smape: 0.5538

Epoch 93/128

479/479 - 3s - 7ms/step - ia: 0.7813 - loss: 0.2198 - mae: 0.3073 - rmse: 0.4580 - smape: 0.6377 - val_ia: 0.7024 - val_loss: 0.1600 - val_mae: 0.2457 - val_rmse: 0.3441 - val_smape: 0.5526

Epoch 94/128

479/479 - 3s - 7ms/step - ia: 0.7820 - loss: 0.2201 - mae: 0.3068 - rmse: 0.4572 - smape: 0.6368 - val_ia: 0.7034 - val_loss: 0.1589 - val_mae: 0.2448 - val_rmse: 0.3430 - val_smape: 0.5514

Epoch 95/128

479/479 - 3s - 7ms/step - ia: 0.7827 - loss: 0.2155 - mae: 0.3047 - rmse: 0.4531 - smape: 0.6332 - val_ia: 0.7044 - val_loss: 0.1578 - val_mae: 0.2439 - val_rmse: 0.3420 - val_smape: 0.5502

Epoch 96/128

479/479 - 3s - 7ms/step - ia: 0.7842 - loss: 0.2135 - mae: 0.3035 - rmse: 0.4510 - smape: 0.6293 - val_ia: 0.7052 - val_loss: 0.1568 - val_mae: 0.2430 - val_rmse: 0.3408 - val_smape: 0.5491

Epoch 97/128

479/479 - 5s - 10ms/step - ia: 0.7834 - loss: 0.2146 - mae: 0.3040 - rmse: 0.4517 - smape: 0.6314 - val_ia: 0.7060 - val_loss: 0.1557 - val_mae: 0.2421 - val_rmse: 0.3397 - val_smape: 0.5481

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 13s - 54ms/step - ia: 0.2493 - loss: 1.7787 - mae: 1.1200 - rmse: 1.3310 - smape: 1.5531 - val_ia: 0.2434 - val_loss: 1.4012 - val_mae: 1.0337 - val_rmse: 1.1528 - val_smape: 1.5882

Epoch 2/128

240/240 - 4s - 18ms/step - ia: 0.2476 - loss: 1.5893 - mae: 1.0383 - rmse: 1.2576 - smape: 1.5452 - val_ia: 0.2503 - val_loss: 1.2423 - val_mae: 0.9515 - val_rmse: 1.0732 - val_smape: 1.5990

Epoch 3/128

240/240 - 4s - 18ms/step - ia: 0.2462 - loss: 1.4690 - mae: 0.9813 - rmse: 1.2089 - smape: 1.5364 - val_ia: 0.2508 - val_loss: 1.1340 - val_mae: 0.8872 - val_rmse: 1.0112 - val_smape: 1.6206

Epoch 4/128

240/240 - 4s - 18ms/step - ia: 0.2461 - loss: 1.4012 - mae: 0.9456 - rmse: 1.1801 - smape: 1.5298 - val_ia: 0.2511 - val_loss: 1.0629 - val_mae: 0.8375 - val_rmse: 0.9645 - val_smape: 1.6519

Epoch 5/128

240/240 - 5s - 21ms/step - ia: 0.2518 - loss: 1.3533 - mae: 0.9129 - rmse: 1.1596 - smape: 1.5086 - val_ia: 0.2556 - val_loss: 1.0202 - val_mae: 0.8025 - val_rmse: 0.9320 - val_smape: 1.6927

Epoch 6/128

240/240 - 4s - 18ms/step - ia: 0.2581 - loss: 1.3076 - mae: 0.8897 - rmse: 1.1394 - smape: 1.4960 - val_ia: 0.2561 - val_loss: 0.9942 - val_mae: 0.7771 - val_rmse: 0.9091 - val_smape: 1.7422

Epoch 7/128

240/240 - 4s - 18ms/step - ia: 0.2624 - loss: 1.2916 - mae: 0.8758 - rmse: 1.1321 - smape: 1.4841 - val_ia: 0.2544 - val_loss: 0.9796 - val_mae: 0.7606 - val_rmse: 0.8945 - val_smape: 1.7920

Epoch 8/128

240/240 - 4s - 18ms/step - ia: 0.2687 - loss: 1.2760 - mae: 0.8638 - rmse: 1.1245 - smape: 1.4721 - val_ia: 0.2535 - val_loss: 0.9712 - val_mae: 0.7501 - val_rmse: 0.8853 - val_smape: 1.8365

Epoch 9/128

240/240 - 5s - 22ms/step - ia: 0.2693 - loss: 1.2728 - mae: 0.8602 - rmse: 1.1233 - smape: 1.4695 - val_ia: 0.2532 - val_loss: 0.9654 - val_mae: 0.7426 - val_rmse: 0.8788 - val_smape: 1.8777

Epoch 10/128

240/240 - 4s - 18ms/step - ia: 0.2698 - loss: 1.2656 - mae: 0.8556 - rmse: 1.1183 - smape: 1.4688 - val_ia: 0.2536 - val_loss: 0.9614 - val_mae: 0.7381 - val_rmse: 0.8749 - val_smape: 1.9027

Epoch 11/128

240/240 - 5s - 23ms/step - ia: 0.2724 - loss: 1.2550 - mae: 0.8505 - rmse: 1.1146 - smape: 1.4619 - val_ia: 0.2540 - val_loss: 0.9581 - val_mae: 0.7349 - val_rmse: 0.8720 - val_smape: 1.9181

Epoch 12/128

240/240 - 5s - 21ms/step - ia: 0.2756 - loss: 1.2433 - mae: 0.8432 - rmse: 1.1094 - smape: 1.4558 - val_ia: 0.2546 - val_loss: 0.9550 - val_mae: 0.7322 - val_rmse: 0.8695 - val_smape: 1.9247

Epoch 13/128

240/240 - 5s - 23ms/step - ia: 0.2769 - loss: 1.2360 - mae: 0.8390 - rmse: 1.1066 - smape: 1.4521 - val_ia: 0.2551 - val_loss: 0.9520 - val_mae: 0.7297 - val_rmse: 0.8672 - val_smape: 1.9234

Epoch 14/128

240/240 - 4s - 18ms/step - ia: 0.2747 - loss: 1.2298 - mae: 0.8374 - rmse: 1.1029 - smape: 1.4547 - val_ia: 0.2559 - val_loss: 0.9494 - val_mae: 0.7288 - val_rmse: 0.8661 - val_smape: 1.9173

Epoch 15/128

240/240 - 4s - 17ms/step - ia: 0.2776 - loss: 1.2148 - mae: 0.8312 - rmse: 1.0970 - smape: 1.4490 - val_ia: 0.2567 - val_loss: 0.9469 - val_mae: 0.7278 - val_rmse: 0.8649 - val_smape: 1.9110

Epoch 16/128

240/240 - 5s - 22ms/step - ia: 0.2722 - loss: 1.2169 - mae: 0.8306 - rmse: 1.0973 - smape: 1.4553 - val_ia: 0.2575 - val_loss: 0.9443 - val_mae: 0.7269 - val_rmse: 0.8638 - val_smape: 1.9047

Epoch 17/128

240/240 - 4s - 19ms/step - ia: 0.2711 - loss: 1.2153 - mae: 0.8336 - rmse: 1.0973 - smape: 1.4625 - val_ia: 0.2582 - val_loss: 0.9413 - val_mae: 0.7249 - val_rmse: 0.8618 - val_smape: 1.8976

Epoch 18/128

240/240 - 4s - 18ms/step - ia: 0.2731 - loss: 1.1976 - mae: 0.8259 - rmse: 1.0892 - smape: 1.4562 - val_ia: 0.2588 - val_loss: 0.9381 - val_mae: 0.7223 - val_rmse: 0.8594 - val_smape: 1.8841

Epoch 19/128

240/240 - 5s - 21ms/step - ia: 0.2757 - loss: 1.1936 - mae: 0.8216 - rmse: 1.0873 - smape: 1.4516 - val_ia: 0.2598 - val_loss: 0.9356 - val_mae: 0.7221 - val_rmse: 0.8588 - val_smape: 1.8832

Epoch 20/128

240/240 - 4s - 17ms/step - ia: 0.2763 - loss: 1.1789 - mae: 0.8188 - rmse: 1.0799 - smape: 1.4538 - val_ia: 0.2607 - val_loss: 0.9327 - val_mae: 0.7206 - val_rmse: 0.8572 - val_smape: 1.8747

Epoch 21/128

240/240 - 5s - 22ms/step - ia: 0.2753 - loss: 1.1758 - mae: 0.8158 - rmse: 1.0787 - smape: 1.4542 - val_ia: 0.2616 - val_loss: 0.9300 - val_mae: 0.7200 - val_rmse: 0.8563 - val_smape: 1.8709

Epoch 22/128

240/240 - 5s - 22ms/step - ia: 0.2770 - loss: 1.1583 - mae: 0.8098 - rmse: 1.0706 - smape: 1.4515 - val_ia: 0.2625 - val_loss: 0.9271 - val_mae: 0.7188 - val_rmse: 0.8550 - val_smape: 1.8642

Epoch 23/128

240/240 - 4s - 18ms/step - ia: 0.2732 - loss: 1.1591 - mae: 0.8111 - rmse: 1.0713 - smape: 1.4580 - val_ia: 0.2634 - val_loss: 0.9241 - val_mae: 0.7174 - val_rmse: 0.8535 - val_smape: 1.8570

Epoch 24/128

240/240 - 5s - 21ms/step - ia: 0.2748 - loss: 1.1531 - mae: 0.8078 - rmse: 1.0689 - smape: 1.4539 - val_ia: 0.2641 - val_loss: 0.9207 - val_mae: 0.7148 - val_rmse: 0.8510 - val_smape: 1.8426

Epoch 25/128

240/240 - 4s - 18ms/step - ia: 0.2730 - loss: 1.1424 - mae: 0.8051 - rmse: 1.0643 - smape: 1.4589 - val_ia: 0.2653 - val_loss: 0.9181 - val_mae: 0.7150 - val_rmse: 0.8507 - val_smape: 1.8433

Epoch 26/128

240/240 - 5s - 22ms/step - ia: 0.2764 - loss: 1.1263 - mae: 0.7987 - rmse: 1.0551 - smape: 1.4528 - val_ia: 0.2661 - val_loss: 0.9147 - val_mae: 0.7126 - val_rmse: 0.8483 - val_smape: 1.8309

Epoch 27/128

240/240 - 5s - 22ms/step - ia: 0.2761 - loss: 1.1245 - mae: 0.7964 - rmse: 1.0555 - smape: 1.4525 - val_ia: 0.2671 - val_loss: 0.9116 - val_mae: 0.7111 - val_rmse: 0.8467 - val_smape: 1.8228

Epoch 28/128

240/240 - 4s - 18ms/step - ia: 0.2775 - loss: 1.1130 - mae: 0.7904 - rmse: 1.0498 - smape: 1.4492 - val_ia: 0.2682 - val_loss: 0.9087 - val_mae: 0.7106 - val_rmse: 0.8459 - val_smape: 1.8199

Epoch 29/128

240/240 - 4s - 18ms/step - ia: 0.2778 - loss: 1.1042 - mae: 0.7878 - rmse: 1.0451 - smape: 1.4500 - val_ia: 0.2691 - val_loss: 0.9051 - val_mae: 0.7081 - val_rmse: 0.8434 - val_smape: 1.8066

Epoch 30/128

240/240 - 4s - 18ms/step - ia: 0.2750 - loss: 1.1068 - mae: 0.7885 - rmse: 1.0465 - smape: 1.4499 - val_ia: 0.2703 - val_loss: 0.9019 - val_mae: 0.7072 - val_rmse: 0.8422 - val_smape: 1.8019

Epoch 31/128

240/240 - 4s - 17ms/step - ia: 0.2790 - loss: 1.0903 - mae: 0.7824 - rmse: 1.0388 - smape: 1.4493 - val_ia: 0.2713 - val_loss: 0.8985 - val_mae: 0.7055 - val_rmse: 0.8404 - val_smape: 1.7934

Epoch 32/128

240/240 - 5s - 22ms/step - ia: 0.2802 - loss: 1.0863 - mae: 0.7803 - rmse: 1.0367 - smape: 1.4441 - val_ia: 0.2725 - val_loss: 0.8953 - val_mae: 0.7046 - val_rmse: 0.8392 - val_smape: 1.7882

Epoch 33/128

240/240 - 5s - 22ms/step - ia: 0.2780 - loss: 1.0819 - mae: 0.7800 - rmse: 1.0346 - smape: 1.4498 - val_ia: 0.2736 - val_loss: 0.8917 - val_mae: 0.7026 - val_rmse: 0.8371 - val_smape: 1.7782

Epoch 34/128

240/240 - 5s - 22ms/step - ia: 0.2821 - loss: 1.0698 - mae: 0.7715 - rmse: 1.0294 - smape: 1.4419 - val_ia: 0.2749 - val_loss: 0.8885 - val_mae: 0.7020 - val_rmse: 0.8361 - val_smape: 1.7745

Epoch 35/128

240/240 - 6s - 26ms/step - ia: 0.2805 - loss: 1.0600 - mae: 0.7709 - rmse: 1.0233 - smape: 1.4445 - val_ia: 0.2761 - val_loss: 0.8848 - val_mae: 0.7003 - val_rmse: 0.8342 - val_smape: 1.7659

Epoch 36/128

240/240 - 9s - 38ms/step - ia: 0.2822 - loss: 1.0557 - mae: 0.7672 - rmse: 1.0215 - smape: 1.4441 - val_ia: 0.2774 - val_loss: 0.8811 - val_mae: 0.6989 - val_rmse: 0.8325 - val_smape: 1.7583

Epoch 37/128

240/240 - 5s - 21ms/step - ia: 0.2829 - loss: 1.0433 - mae: 0.7634 - rmse: 1.0155 - smape: 1.4456 - val_ia: 0.2787 - val_loss: 0.8773 - val_mae: 0.6969 - val_rmse: 0.8304 - val_smape: 1.7485

Epoch 38/128

240/240 - 5s - 19ms/step - ia: 0.2845 - loss: 1.0336 - mae: 0.7596 - rmse: 1.0109 - smape: 1.4404 - val_ia: 0.2801 - val_loss: 0.8735 - val_mae: 0.6956 - val_rmse: 0.8289 - val_smape: 1.7423

Epoch 39/128

240/240 - 5s - 19ms/step - ia: 0.2831 - loss: 1.0265 - mae: 0.7579 - rmse: 1.0071 - smape: 1.4471 - val_ia: 0.2814 - val_loss: 0.8694 - val_mae: 0.6934 - val_rmse: 0.8265 - val_smape: 1.7314

Epoch 40/128

240/240 - 4s - 18ms/step - ia: 0.2855 - loss: 1.0228 - mae: 0.7558 - rmse: 1.0052 - smape: 1.4388 - val_ia: 0.2829 - val_loss: 0.8654 - val_mae: 0.6920 - val_rmse: 0.8248 - val_smape: 1.7242

Epoch 41/128

240/240 - 4s - 17ms/step - ia: 0.2898 - loss: 1.0168 - mae: 0.7511 - rmse: 1.0025 - smape: 1.4318 - val_ia: 0.2845 - val_loss: 0.8615 - val_mae: 0.6908 - val_rmse: 0.8233 - val_smape: 1.7179

Epoch 42/128

240/240 - 4s - 17ms/step - ia: 0.2895 - loss: 1.0091 - mae: 0.7491 - rmse: 0.9984 - smape: 1.4354 - val_ia: 0.2861 - val_loss: 0.8573 - val_mae: 0.6892 - val_rmse: 0.8213 - val_smape: 1.7097

Epoch 43/128

240/240 - 4s - 16ms/step - ia: 0.2877 - loss: 0.9984 - mae: 0.7474 - rmse: 0.9942 - smape: 1.4377 - val_ia: 0.2875 - val_loss: 0.8526 - val_mae: 0.6863 - val_rmse: 0.8184 - val_smape: 1.6972

Epoch 44/128

240/240 - 4s - 15ms/step - ia: 0.2913 - loss: 0.9950 - mae: 0.7442 - rmse: 0.9921 - smape: 1.4337 - val_ia: 0.2893 - val_loss: 0.8483 - val_mae: 0.6851 - val_rmse: 0.8168 - val_smape: 1.6907

Epoch 45/128

240/240 - 4s - 15ms/step - ia: 0.2936 - loss: 0.9906 - mae: 0.7418 - rmse: 0.9889 - smape: 1.4265 - val_ia: 0.2910 - val_loss: 0.8436 - val_mae: 0.6825 - val_rmse: 0.8141 - val_smape: 1.6795

Epoch 46/128

240/240 - 4s - 15ms/step - ia: 0.2884 - loss: 0.9903 - mae: 0.7447 - rmse: 0.9891 - smape: 1.4362 - val_ia: 0.2926 - val_loss: 0.8386 - val_mae: 0.6792 - val_rmse: 0.8108 - val_smape: 1.6651

Epoch 47/128

240/240 - 3s - 14ms/step - ia: 0.2991 - loss: 0.9732 - mae: 0.7351 - rmse: 0.9818 - smape: 1.4189 - val_ia: 0.2945 - val_loss: 0.8340 - val_mae: 0.6780 - val_rmse: 0.8091 - val_smape: 1.6594

Epoch 48/128

240/240 - 4s - 18ms/step - ia: 0.2981 - loss: 0.9716 - mae: 0.7333 - rmse: 0.9795 - smape: 1.4227 - val_ia: 0.2965 - val_loss: 0.8290 - val_mae: 0.6763 - val_rmse: 0.8070 - val_smape: 1.6512

Epoch 49/128

240/240 - 5s - 20ms/step - ia: 0.2959 - loss: 0.9687 - mae: 0.7336 - rmse: 0.9793 - smape: 1.4277 - val_ia: 0.2985 - val_loss: 0.8238 - val_mae: 0.6737 - val_rmse: 0.8042 - val_smape: 1.6400

Epoch 50/128

240/240 - 5s - 21ms/step - ia: 0.3033 - loss: 0.9499 - mae: 0.7271 - rmse: 0.9692 - smape: 1.4181 - val_ia: 0.3007 - val_loss: 0.8184 - val_mae: 0.6715 - val_rmse: 0.8016 - val_smape: 1.6299

Epoch 51/128

240/240 - 5s - 19ms/step - ia: 0.3032 - loss: 0.9480 - mae: 0.7242 - rmse: 0.9688 - smape: 1.4127 - val_ia: 0.3028 - val_loss: 0.8128 - val_mae: 0.6685 - val_rmse: 0.7984 - val_smape: 1.6173

Epoch 52/128

240/240 - 4s - 17ms/step - ia: 0.3076 - loss: 0.9419 - mae: 0.7220 - rmse: 0.9646 - smape: 1.4087 - val_ia: 0.3052 - val_loss: 0.8075 - val_mae: 0.6675 - val_rmse: 0.7968 - val_smape: 1.6118

Epoch 53/128

240/240 - 4s - 18ms/step - ia: 0.3094 - loss: 0.9360 - mae: 0.7184 - rmse: 0.9623 - smape: 1.4041 - val_ia: 0.3076 - val_loss: 0.8015 - val_mae: 0.6641 - val_rmse: 0.7933 - val_smape: 1.5984

Epoch 54/128

240/240 - 6s - 24ms/step - ia: 0.3139 - loss: 0.9251 - mae: 0.7150 - rmse: 0.9558 - smape: 1.3984 - val_ia: 0.3101 - val_loss: 0.7956 - val_mae: 0.6619 - val_rmse: 0.7906 - val_smape: 1.5887

Epoch 55/128

240/240 - 5s - 19ms/step - ia: 0.3177 - loss: 0.9197 - mae: 0.7119 - rmse: 0.9522 - smape: 1.3949 - val_ia: 0.3127 - val_loss: 0.7894 - val_mae: 0.6590 - val_rmse: 0.7874 - val_smape: 1.5769

Epoch 56/128

240/240 - 5s - 19ms/step - ia: 0.3221 - loss: 0.9049 - mae: 0.7062 - rmse: 0.9459 - smape: 1.3882 - val_ia: 0.3155 - val_loss: 0.7828 - val_mae: 0.6554 - val_rmse: 0.7836 - val_smape: 1.5630

Epoch 57/128

240/240 - 4s - 19ms/step - ia: 0.3249 - loss: 0.8974 - mae: 0.7031 - rmse: 0.9419 - smape: 1.3821 - val_ia: 0.3184 - val_loss: 0.7762 - val_mae: 0.6531 - val_rmse: 0.7808 - val_smape: 1.5535

Epoch 58/128

240/240 - 5s - 23ms/step - ia: 0.3301 - loss: 0.8878 - mae: 0.6982 - rmse: 0.9372 - smape: 1.3773 - val_ia: 0.3214 - val_loss: 0.7693 - val_mae: 0.6497 - val_rmse: 0.7771 - val_smape: 1.5405

Epoch 59/128

240/240 - 5s - 19ms/step - ia: 0.3311 - loss: 0.8845 - mae: 0.6972 - rmse: 0.9353 - smape: 1.3735 - val_ia: 0.3248 - val_loss: 0.7618 - val_mae: 0.6453 - val_rmse: 0.7726 - val_smape: 1.5241

Epoch 60/128

240/240 - 5s - 21ms/step - ia: 0.3383 - loss: 0.8716 - mae: 0.6918 - rmse: 0.9279 - smape: 1.3664 - val_ia: 0.3281 - val_loss: 0.7546 - val_mae: 0.6426 - val_rmse: 0.7693 - val_smape: 1.5136

Epoch 61/128

240/240 - 5s - 19ms/step - ia: 0.3409 - loss: 0.8652 - mae: 0.6888 - rmse: 0.9249 - smape: 1.3608 - val_ia: 0.3314 - val_loss: 0.7474 - val_mae: 0.6403 - val_rmse: 0.7663 - val_smape: 1.5048

Epoch 62/128

240/240 - 4s - 15ms/step - ia: 0.3453 - loss: 0.8636 - mae: 0.6875 - rmse: 0.9232 - smape: 1.3556 - val_ia: 0.3351 - val_loss: 0.7395 - val_mae: 0.6365 - val_rmse: 0.7621 - val_smape: 1.4911

Epoch 63/128

240/240 - 3s - 13ms/step - ia: 0.3504 - loss: 0.8472 - mae: 0.6810 - rmse: 0.9144 - smape: 1.3476 - val_ia: 0.3388 - val_loss: 0.7316 - val_mae: 0.6334 - val_rmse: 0.7584 - val_smape: 1.4799

Epoch 64/128

240/240 - 3s - 13ms/step - ia: 0.3550 - loss: 0.8421 - mae: 0.6784 - rmse: 0.9110 - smape: 1.3433 - val_ia: 0.3429 - val_loss: 0.7233 - val_mae: 0.6294 - val_rmse: 0.7540 - val_smape: 1.4658

Epoch 65/128

240/240 - 3s - 13ms/step - ia: 0.3600 - loss: 0.8303 - mae: 0.6734 - rmse: 0.9059 - smape: 1.3378 - val_ia: 0.3472 - val_loss: 0.7148 - val_mae: 0.6256 - val_rmse: 0.7498 - val_smape: 1.4527

Epoch 66/128

240/240 - 3s - 13ms/step - ia: 0.3696 - loss: 0.8104 - mae: 0.6661 - rmse: 0.8936 - smape: 1.3226 - val_ia: 0.3523 - val_loss: 0.7054 - val_mae: 0.6196 - val_rmse: 0.7437 - val_smape: 1.4326

Epoch 67/128

240/240 - 3s - 14ms/step - ia: 0.3745 - loss: 0.8062 - mae: 0.6619 - rmse: 0.8928 - smape: 1.3149 - val_ia: 0.3566 - val_loss: 0.6967 - val_mae: 0.6169 - val_rmse: 0.7401 - val_smape: 1.4231

Epoch 68/128

240/240 - 4s - 16ms/step - ia: 0.3793 - loss: 0.8003 - mae: 0.6601 - rmse: 0.8890 - smape: 1.3086 - val_ia: 0.3617 - val_loss: 0.6873 - val_mae: 0.6120 - val_rmse: 0.7348 - val_smape: 1.4070

Epoch 69/128

240/240 - 6s - 24ms/step - ia: 0.3861 - loss: 0.7910 - mae: 0.6552 - rmse: 0.8838 - smape: 1.3005 - val_ia: 0.3669 - val_loss: 0.6776 - val_mae: 0.6073 - val_rmse: 0.7297 - val_smape: 1.3921

Epoch 70/128

240/240 - 5s - 19ms/step - ia: 0.3918 - loss: 0.7827 - mae: 0.6514 - rmse: 0.8796 - smape: 1.2928 - val_ia: 0.3725 - val_loss: 0.6675 - val_mae: 0.6018 - val_rmse: 0.7238 - val_smape: 1.3746

Epoch 71/128

240/240 - 5s - 19ms/step - ia: 0.4001 - loss: 0.7711 - mae: 0.6451 - rmse: 0.8731 - smape: 1.2761 - val_ia: 0.3782 - val_loss: 0.6570 - val_mae: 0.5966 - val_rmse: 0.7181 - val_smape: 1.3586

Epoch 72/128

240/240 - 4s - 18ms/step - ia: 0.4043 - loss: 0.7593 - mae: 0.6417 - rmse: 0.8652 - smape: 1.2736 - val_ia: 0.3843 - val_loss: 0.6463 - val_mae: 0.5907 - val_rmse: 0.7119 - val_smape: 1.3409

Epoch 73/128

240/240 - 6s - 23ms/step - ia: 0.4106 - loss: 0.7507 - mae: 0.6370 - rmse: 0.8625 - smape: 1.2662 - val_ia: 0.3903 - val_loss: 0.6355 - val_mae: 0.5855 - val_rmse: 0.7061 - val_smape: 1.3252

Epoch 74/128

240/240 - 5s - 22ms/step - ia: 0.4200 - loss: 0.7371 - mae: 0.6314 - rmse: 0.8530 - smape: 1.2530 - val_ia: 0.3966 - val_loss: 0.6243 - val_mae: 0.5797 - val_rmse: 0.6998 - val_smape: 1.3083

Epoch 75/128

240/240 - 5s - 19ms/step - ia: 0.4282 - loss: 0.7257 - mae: 0.6258 - rmse: 0.8464 - smape: 1.2409 - val_ia: 0.4032 - val_loss: 0.6129 - val_mae: 0.5738 - val_rmse: 0.6934 - val_smape: 1.2909

Epoch 76/128

240/240 - 5s - 19ms/step - ia: 0.4342 - loss: 0.7160 - mae: 0.6216 - rmse: 0.8404 - smape: 1.2279 - val_ia: 0.4102 - val_loss: 0.6011 - val_mae: 0.5674 - val_rmse: 0.6865 - val_smape: 1.2727

Epoch 77/128

240/240 - 5s - 19ms/step - ia: 0.4424 - loss: 0.7043 - mae: 0.6151 - rmse: 0.8344 - smape: 1.2229 - val_ia: 0.4167 - val_loss: 0.5893 - val_mae: 0.5620 - val_rmse: 0.6803 - val_smape: 1.2574

Epoch 78/128

240/240 - 5s - 21ms/step - ia: 0.4505 - loss: 0.6897 - mae: 0.6098 - rmse: 0.8246 - smape: 1.2082 - val_ia: 0.4237 - val_loss: 0.5771 - val_mae: 0.5559 - val_rmse: 0.6736 - val_smape: 1.2407

Epoch 79/128

240/240 - 5s - 21ms/step - ia: 0.4574 - loss: 0.6804 - mae: 0.6051 - rmse: 0.8196 - smape: 1.2035 - val_ia: 0.4317 - val_loss: 0.5644 - val_mae: 0.5481 - val_rmse: 0.6655 - val_smape: 1.2189

Epoch 80/128

240/240 - 5s - 19ms/step - ia: 0.4642 - loss: 0.6742 - mae: 0.6011 - rmse: 0.8163 - smape: 1.1921 - val_ia: 0.4382 - val_loss: 0.5521 - val_mae: 0.5428 - val_rmse: 0.6592 - val_smape: 1.2050

Epoch 81/128

240/240 - 4s - 18ms/step - ia: 0.4723 - loss: 0.6603 - mae: 0.5946 - rmse: 0.8075 - smape: 1.1799 - val_ia: 0.4468 - val_loss: 0.5388 - val_mae: 0.5340 - val_rmse: 0.6503 - val_smape: 1.1811

Epoch 82/128

240/240 - 5s - 22ms/step - ia: 0.4848 - loss: 0.6404 - mae: 0.5862 - rmse: 0.7955 - smape: 1.1632 - val_ia: 0.4543 - val_loss: 0.5258 - val_mae: 0.5270 - val_rmse: 0.6427 - val_smape: 1.1629

Epoch 83/128

240/240 - 5s - 20ms/step - ia: 0.4913 - loss: 0.6329 - mae: 0.5824 - rmse: 0.7911 - smape: 1.1514 - val_ia: 0.4619 - val_loss: 0.5125 - val_mae: 0.5199 - val_rmse: 0.6349 - val_smape: 1.1447

Epoch 84/128

240/240 - 5s - 21ms/step - ia: 0.5002 - loss: 0.6177 - mae: 0.5754 - rmse: 0.7800 - smape: 1.1419 - val_ia: 0.4701 - val_loss: 0.4992 - val_mae: 0.5120 - val_rmse: 0.6265 - val_smape: 1.1244

Epoch 85/128

240/240 - 4s - 18ms/step - ia: 0.5084 - loss: 0.6062 - mae: 0.5693 - rmse: 0.7733 - smape: 1.1269 - val_ia: 0.4782 - val_loss: 0.4858 - val_mae: 0.5042 - val_rmse: 0.6181 - val_smape: 1.1048

Epoch 86/128

240/240 - 3s - 14ms/step - ia: 0.5189 - loss: 0.5911 - mae: 0.5613 - rmse: 0.7636 - smape: 1.1142 - val_ia: 0.4853 - val_loss: 0.4727 - val_mae: 0.4978 - val_rmse: 0.6106 - val_smape: 1.0899

Epoch 87/128

240/240 - 3s - 14ms/step - ia: 0.5254 - loss: 0.5818 - mae: 0.5580 - rmse: 0.7573 - smape: 1.1042 - val_ia: 0.4941 - val_loss: 0.4592 - val_mae: 0.4890 - val_rmse: 0.6015 - val_smape: 1.0677

Epoch 88/128

240/240 - 3s - 13ms/step - ia: 0.5322 - loss: 0.5738 - mae: 0.5547 - rmse: 0.7526 - smape: 1.0958 - val_ia: 0.5022 - val_loss: 0.4461 - val_mae: 0.4810 - val_rmse: 0.5930 - val_smape: 1.0485

Epoch 89/128

240/240 - 3s - 14ms/step - ia: 0.5389 - loss: 0.5627 - mae: 0.5493 - rmse: 0.7453 - smape: 1.0862 - val_ia: 0.5109 - val_loss: 0.4328 - val_mae: 0.4724 - val_rmse: 0.5840 - val_smape: 1.0278

Epoch 90/128

240/240 - 3s - 14ms/step - ia: 0.5485 - loss: 0.5511 - mae: 0.5428 - rmse: 0.7371 - smape: 1.0727 - val_ia: 0.5189 - val_loss: 0.4199 - val_mae: 0.4646 - val_rmse: 0.5756 - val_smape: 1.0096

Epoch 91/128

240/240 - 3s - 14ms/step - ia: 0.5587 - loss: 0.5364 - mae: 0.5343 - rmse: 0.7275 - smape: 1.0580 - val_ia: 0.5270 - val_loss: 0.4072 - val_mae: 0.4569 - val_rmse: 0.5672 - val_smape: 0.9919

Epoch 92/128

240/240 - 5s - 19ms/step - ia: 0.5636 - loss: 0.5283 - mae: 0.5325 - rmse: 0.7212 - smape: 1.0513 - val_ia: 0.5358 - val_loss: 0.3945 - val_mae: 0.4483 - val_rmse: 0.5583 - val_smape: 0.9719

Epoch 93/128

240/240 - 5s - 19ms/step - ia: 0.5708 - loss: 0.5193 - mae: 0.5267 - rmse: 0.7155 - smape: 1.0383 - val_ia: 0.5445 - val_loss: 0.3820 - val_mae: 0.4398 - val_rmse: 0.5494 - val_smape: 0.9526

Epoch 94/128

240/240 - 5s - 21ms/step - ia: 0.5785 - loss: 0.5075 - mae: 0.5208 - rmse: 0.7073 - smape: 1.0274 - val_ia: 0.5518 - val_loss: 0.3701 - val_mae: 0.4330 - val_rmse: 0.5418 - val_smape: 0.9384

Epoch 95/128

240/240 - 5s - 19ms/step - ia: 0.5847 - loss: 0.4973 - mae: 0.5157 - rmse: 0.6998 - smape: 1.0181 - val_ia: 0.5601 - val_loss: 0.3583 - val_mae: 0.4252 - val_rmse: 0.5336 - val_smape: 0.9211

Epoch 96/128

240/240 - 4s - 18ms/step - ia: 0.5917 - loss: 0.4915 - mae: 0.5132 - rmse: 0.6961 - smape: 1.0099 - val_ia: 0.5685 - val_loss: 0.3472 - val_mae: 0.4169 - val_rmse: 0.5252 - val_smape: 0.9017

Epoch 97/128

240/240 - 5s - 19ms/step - ia: 0.5964 - loss: 0.4797 - mae: 0.5090 - rmse: 0.6881 - smape: 1.0058 - val_ia: 0.5757 - val_loss: 0.3364 - val_mae: 0.4101 - val_rmse: 0.5178 - val_smape: 0.8880

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 4s - 19ms/step - ia: 0.8553 - loss: 0.1097 - mae: 0.2071 - rmse: 0.3136 - smape: 0.4666 - val_ia: 0.8618 - val_loss: 0.0598 - val_mae: 0.1432 - val_rmse: 0.2238 - val_smape: 0.3746

Epoch 2/128

240/240 - 2s - 7ms/step - ia: 0.8782 - loss: 0.0822 - mae: 0.1768 - rmse: 0.2800 - smape: 0.4104 - val_ia: 0.8530 - val_loss: 0.0581 - val_mae: 0.1471 - val_rmse: 0.2211 - val_smape: 0.3806

Epoch 3/128

240/240 - 2s - 7ms/step - ia: 0.8787 - loss: 0.0812 - mae: 0.1763 - rmse: 0.2789 - smape: 0.4088 - val_ia: 0.8364 - val_loss: 0.0635 - val_mae: 0.1611 - val_rmse: 0.2314 - val_smape: 0.3906

Epoch 4/128

240/240 - 2s - 7ms/step - ia: 0.8783 - loss: 0.0802 - mae: 0.1764 - rmse: 0.2765 - smape: 0.4100 - val_ia: 0.8720 - val_loss: 0.0548 - val_mae: 0.1311 - val_rmse: 0.2134 - val_smape: 0.3517

Epoch 5/128

240/240 - 2s - 7ms/step - ia: 0.8789 - loss: 0.0803 - mae: 0.1759 - rmse: 0.2763 - smape: 0.4102 - val_ia: 0.8592 - val_loss: 0.0572 - val_mae: 0.1424 - val_rmse: 0.2183 - val_smape: 0.3631

Epoch 6/128

240/240 - 2s - 7ms/step - ia: 0.8766 - loss: 0.0830 - mae: 0.1795 - rmse: 0.2823 - smape: 0.4128 - val_ia: 0.8381 - val_loss: 0.0653 - val_mae: 0.1602 - val_rmse: 0.2346 - val_smape: 0.4011

Epoch 7/128

240/240 - 2s - 7ms/step - ia: 0.8773 - loss: 0.0824 - mae: 0.1783 - rmse: 0.2802 - smape: 0.4090 - val_ia: 0.8526 - val_loss: 0.0635 - val_mae: 0.1519 - val_rmse: 0.2294 - val_smape: 0.3785

Epoch 8/128

240/240 - 2s - 7ms/step - ia: 0.8782 - loss: 0.0808 - mae: 0.1770 - rmse: 0.2770 - smape: 0.4112 - val_ia: 0.8665 - val_loss: 0.0598 - val_mae: 0.1401 - val_rmse: 0.2229 - val_smape: 0.3671

Epoch 9/128

240/240 - 2s - 7ms/step - ia: 0.8799 - loss: 0.0788 - mae: 0.1750 - rmse: 0.2747 - smape: 0.4080 - val_ia: 0.8539 - val_loss: 0.0567 - val_mae: 0.1467 - val_rmse: 0.2201 - val_smape: 0.3827

Epoch 10/128

240/240 - 2s - 10ms/step - ia: 0.8792 - loss: 0.0816 - mae: 0.1759 - rmse: 0.2792 - smape: 0.4074 - val_ia: 0.8449 - val_loss: 0.0616 - val_mae: 0.1532 - val_rmse: 0.2287 - val_smape: 0.3884

Epoch 11/128

240/240 - 2s - 10ms/step - ia: 0.8791 - loss: 0.0804 - mae: 0.1758 - rmse: 0.2771 - smape: 0.4060 - val_ia: 0.8725 - val_loss: 0.0543 - val_mae: 0.1317 - val_rmse: 0.2132 - val_smape: 0.3548

Epoch 12/128

240/240 - 3s - 11ms/step - ia: 0.8784 - loss: 0.0805 - mae: 0.1772 - rmse: 0.2770 - smape: 0.4106 - val_ia: 0.8688 - val_loss: 0.0549 - val_mae: 0.1341 - val_rmse: 0.2143 - val_smape: 0.3580

Epoch 13/128

240/240 - 2s - 10ms/step - ia: 0.8797 - loss: 0.0801 - mae: 0.1751 - rmse: 0.2762 - smape: 0.4073 - val_ia: 0.8670 - val_loss: 0.0563 - val_mae: 0.1366 - val_rmse: 0.2165 - val_smape: 0.3594

Epoch 14/128

240/240 - 2s - 9ms/step - ia: 0.8804 - loss: 0.0791 - mae: 0.1742 - rmse: 0.2748 - smape: 0.4009 - val_ia: 0.8697 - val_loss: 0.0554 - val_mae: 0.1336 - val_rmse: 0.2153 - val_smape: 0.3556

Epoch 15/128

240/240 - 3s - 11ms/step - ia: 0.8772 - loss: 0.0818 - mae: 0.1788 - rmse: 0.2788 - smape: 0.4147 - val_ia: 0.8750 - val_loss: 0.0542 - val_mae: 0.1300 - val_rmse: 0.2129 - val_smape: 0.3484

Epoch 16/128

240/240 - 2s - 10ms/step - ia: 0.8786 - loss: 0.0815 - mae: 0.1765 - rmse: 0.2785 - smape: 0.4046 - val_ia: 0.8312 - val_loss: 0.0657 - val_mae: 0.1652 - val_rmse: 0.2348 - val_smape: 0.3954

Epoch 17/128

240/240 - 2s - 10ms/step - ia: 0.8757 - loss: 0.0833 - mae: 0.1808 - rmse: 0.2816 - smape: 0.4183 - val_ia: 0.8632 - val_loss: 0.0582 - val_mae: 0.1413 - val_rmse: 0.2196 - val_smape: 0.3699

Epoch 18/128

240/240 - 3s - 12ms/step - ia: 0.8769 - loss: 0.0821 - mae: 0.1788 - rmse: 0.2805 - smape: 0.4116 - val_ia: 0.8478 - val_loss: 0.0580 - val_mae: 0.1503 - val_rmse: 0.2223 - val_smape: 0.3801

Epoch 19/128

240/240 - 2s - 9ms/step - ia: 0.8805 - loss: 0.0785 - mae: 0.1741 - rmse: 0.2732 - smape: 0.4043 - val_ia: 0.8523 - val_loss: 0.0588 - val_mae: 0.1489 - val_rmse: 0.2238 - val_smape: 0.3870

Epoch 20/128

240/240 - 2s - 10ms/step - ia: 0.8772 - loss: 0.0824 - mae: 0.1787 - rmse: 0.2810 - smape: 0.4137 - val_ia: 0.8444 - val_loss: 0.0597 - val_mae: 0.1530 - val_rmse: 0.2260 - val_smape: 0.3856

Epoch 21/128

240/240 - 3s - 11ms/step - ia: 0.8793 - loss: 0.0795 - mae: 0.1756 - rmse: 0.2757 - smape: 0.4101 - val_ia: 0.8619 - val_loss: 0.0599 - val_mae: 0.1455 - val_rmse: 0.2256 - val_smape: 0.3692

Epoch 22/128

240/240 - 2s - 10ms/step - ia: 0.1428 - loss: 1608105590784.0000 - mae: 334620.7188 - rmse: 618808.9375 - smape: 1.7196 - val_ia: 4.9325e-07 - val_loss: 11150084276224.0000 - val_mae: 1534051.6250 - val_rmse: 2703394.0000 - val_smape: 2.0000

Epoch 23/128

240/240 - 2s - 10ms/step - ia: 5.2886e-05 - loss: 1102083260416.0000 - mae: 327928.5938 - rmse: 589643.6250 - smape: 1.9979 - val_ia: 5.4055e-04 - val_loss: 16264530.0000 - val_mae: 2010.0815 - val_rmse: 3497.6201 - val_smape: 1.9880

Epoch 24/128

240/240 - 2s - 10ms/step - ia: 0.0287 - loss: 916222.3125 - mae: 266.4963 - rmse: 485.7636 - smape: 1.8381 - val_ia: 0.1570 - val_loss: 29.4621 - val_mae: 2.9296 - val_rmse: 4.6288 - val_smape: 1.5526

Epoch 25/128

240/240 - 2s - 9ms/step - ia: 0.2216 - loss: 3.5958 - mae: 1.1319 - rmse: 1.5679 - smape: 1.5520 - val_ia: 0.2562 - val_loss: 1.1204 - val_mae: 0.8567 - val_rmse: 1.0022 - val_smape: 1.5944

Epoch 26/128

240/240 - 3s - 12ms/step - ia: 0.2253 - loss: 1.2038 - mae: 0.8686 - rmse: 1.0924 - smape: 1.5533 - val_ia: 0.2551 - val_loss: 1.1629 - val_mae: 0.8668 - val_rmse: 1.0254 - val_smape: 1.5968

Epoch 27/128

240/240 - 2s - 10ms/step - ia: 0.2304 - loss: 1.2452 - mae: 0.8824 - rmse: 1.1108 - smape: 1.5501 - val_ia: 0.2486 - val_loss: 1.2240 - val_mae: 0.8953 - val_rmse: 1.0548 - val_smape: 1.5938

Epoch 28/128

240/240 - 2s - 10ms/step - ia: 0.2275 - loss: 1.3425 - mae: 0.9113 - rmse: 1.1535 - smape: 1.5538 - val_ia: 0.2449 - val_loss: 1.2969 - val_mae: 0.9095 - val_rmse: 1.0903 - val_smape: 1.5653

Epoch 29/128

240/240 - 2s - 9ms/step - ia: 0.2301 - loss: 1.3912 - mae: 0.9196 - rmse: 1.1739 - smape: 1.5458 - val_ia: 0.2327 - val_loss: 2.2347 - val_mae: 1.1165 - val_rmse: 1.4295 - val_smape: 1.5452

Epoch 30/128

240/240 - 3s - 11ms/step - ia: 0.2077 - loss: 5.5223 - mae: 1.5152 - rmse: 2.2691 - smape: 1.5445 - val_ia: 0.2154 - val_loss: 2.7366 - val_mae: 1.2084 - val_rmse: 1.5721 - val_smape: 1.5819

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:07 498ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 58%|█████▊    | 7/12 [2:47:30<1:18:54, 946.98s/trial, best loss: 0.036452573825096646]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 61s - 16ms/step - ia: 0.8252 - loss: 0.1125 - mae: 0.2165 - rmse: 0.2921 - smape: 0.4786 - val_ia: 0.5299 - val_loss: 0.0581 - val_mae: 0.1446 - val_rmse: 0.1858 - val_smape: 0.3780

Epoch 2/128

3832/3832 - 76s - 20ms/step - ia: 0.8434 - loss: 0.0951 - mae: 0.1956 - rmse: 0.2651 - smape: 0.4405 - val_ia: 0.5544 - val_loss: 0.0601 - val_mae: 0.1387 - val_rmse: 0.1815 - val_smape: 0.3614

Epoch 3/128

3832/3832 - 52s - 13ms/step - ia: 0.8456 - loss: 0.0915 - mae: 0.1911 - rmse: 0.2607 - smape: 0.4353 - val_ia: 0.4746 - val_loss: 0.0781 - val_mae: 0.1827 - val_rmse: 0.2194 - val_smape: 0.4363

Epoch 4/128

3832/3832 - 76s - 20ms/step - ia: 0.8500 - loss: 0.0886 - mae: 0.1868 - rmse: 0.2555 - smape: 0.4305 - val_ia: 0.5306 - val_loss: 0.0589 - val_mae: 0.1438 - val_rmse: 0.1840 - val_smape: 0.3711

Epoch 5/128

3832/3832 - 44s - 11ms/step - ia: 0.8509 - loss: 0.0871 - mae: 0.1854 - rmse: 0.2542 - smape: 0.4280 - val_ia: 0.5471 - val_loss: 0.0538 - val_mae: 0.1360 - val_rmse: 0.1761 - val_smape: 0.3683

Epoch 6/128

3832/3832 - 82s - 21ms/step - ia: 0.8527 - loss: 0.0848 - mae: 0.1836 - rmse: 0.2518 - smape: 0.4268 - val_ia: 0.4986 - val_loss: 0.0607 - val_mae: 0.1564 - val_rmse: 0.1937 - val_smape: 0.4083

Epoch 7/128

3832/3832 - 46s - 12ms/step - ia: 0.8549 - loss: 0.0825 - mae: 0.1797 - rmse: 0.2473 - smape: 0.4190 - val_ia: 0.5664 - val_loss: 0.0572 - val_mae: 0.1337 - val_rmse: 0.1764 - val_smape: 0.3510

Epoch 8/128

3832/3832 - 43s - 11ms/step - ia: 0.8544 - loss: 0.0835 - mae: 0.1813 - rmse: 0.2492 - smape: 0.4246 - val_ia: 0.4971 - val_loss: 0.0647 - val_mae: 0.1611 - val_rmse: 0.2032 - val_smape: 0.4161

Epoch 9/128

3832/3832 - 45s - 12ms/step - ia: 0.8562 - loss: 0.0812 - mae: 0.1789 - rmse: 0.2457 - smape: 0.4221 - val_ia: 0.5502 - val_loss: 0.0574 - val_mae: 0.1373 - val_rmse: 0.1774 - val_smape: 0.3633

Epoch 10/128

3832/3832 - 45s - 12ms/step - ia: 0.8565 - loss: 0.0810 - mae: 0.1791 - rmse: 0.2460 - smape: 0.4249 - val_ia: 0.5071 - val_loss: 0.0633 - val_mae: 0.1576 - val_rmse: 0.1982 - val_smape: 0.4285

Epoch 11/128

3832/3832 - 43s - 11ms/step - ia: 0.8561 - loss: 0.0805 - mae: 0.1791 - rmse: 0.2448 - smape: 0.4254 - val_ia: 0.5460 - val_loss: 0.0615 - val_mae: 0.1401 - val_rmse: 0.1824 - val_smape: 0.3594

Epoch 12/128

3832/3832 - 46s - 12ms/step - ia: 0.8565 - loss: 0.0799 - mae: 0.1788 - rmse: 0.2449 - smape: 0.4214 - val_ia: 0.5394 - val_loss: 0.0727 - val_mae: 0.1552 - val_rmse: 0.1960 - val_smape: 0.3948

Epoch 13/128

3832/3832 - 53s - 14ms/step - ia: 0.8584 - loss: 0.0775 - mae: 0.1764 - rmse: 0.2415 - smape: 0.4194 - val_ia: 0.5350 - val_loss: 0.0621 - val_mae: 0.1432 - val_rmse: 0.1826 - val_smape: 0.3685

Epoch 14/128

3832/3832 - 70s - 18ms/step - ia: 0.8578 - loss: 0.0797 - mae: 0.1765 - rmse: 0.2428 - smape: 0.4184 - val_ia: 0.5423 - val_loss: 0.0600 - val_mae: 0.1413 - val_rmse: 0.1815 - val_smape: 0.3647

Epoch 15/128

3832/3832 - 44s - 11ms/step - ia: 0.8583 - loss: 0.0799 - mae: 0.1769 - rmse: 0.2443 - smape: 0.4167 - val_ia: 0.5275 - val_loss: 0.0667 - val_mae: 0.1463 - val_rmse: 0.1862 - val_smape: 0.3727

Epoch 16/128

3832/3832 - 46s - 12ms/step - ia: 0.8594 - loss: 0.0777 - mae: 0.1763 - rmse: 0.2423 - smape: 0.4180 - val_ia: 0.5262 - val_loss: 0.0599 - val_mae: 0.1448 - val_rmse: 0.1830 - val_smape: 0.3648

Epoch 17/128

3832/3832 - 81s - 21ms/step - ia: 0.8579 - loss: 0.0787 - mae: 0.1765 - rmse: 0.2428 - smape: 0.4190 - val_ia: 0.5167 - val_loss: 0.0718 - val_mae: 0.1588 - val_rmse: 0.1965 - val_smape: 0.3814

Epoch 18/128

3832/3832 - 44s - 11ms/step - ia: 0.8601 - loss: 0.0766 - mae: 0.1746 - rmse: 0.2399 - smape: 0.4174 - val_ia: 0.5556 - val_loss: 0.0555 - val_mae: 0.1354 - val_rmse: 0.1764 - val_smape: 0.3651

Epoch 19/128

3832/3832 - 82s - 21ms/step - ia: 0.8588 - loss: 0.0777 - mae: 0.1754 - rmse: 0.2421 - smape: 0.4160 - val_ia: 0.5374 - val_loss: 0.0574 - val_mae: 0.1404 - val_rmse: 0.1807 - val_smape: 0.3657

Epoch 20/128

3832/3832 - 45s - 12ms/step - ia: 0.8594 - loss: 0.0784 - mae: 0.1761 - rmse: 0.2420 - smape: 0.4190 - val_ia: 0.5366 - val_loss: 0.0594 - val_mae: 0.1431 - val_rmse: 0.1834 - val_smape: 0.3783

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:14 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 67%|██████▋   | 8/12 [3:06:16<1:06:56, 1004.19s/trial, best loss: 0.036452573825096646]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 6s - 26ms/step - ia: 0.4848 - loss: 0.7740 - mae: 0.6020 - rmse: 0.8257 - smape: 1.1593 - val_ia: 0.7267 - val_loss: 0.1475 - val_mae: 0.2651 - val_rmse: 0.3549 - val_smape: 0.6166

Epoch 2/128

240/240 - 1s - 4ms/step - ia: 0.7555 - loss: 0.2379 - mae: 0.3360 - rmse: 0.4817 - smape: 0.7151 - val_ia: 0.7901 - val_loss: 0.1007 - val_mae: 0.2067 - val_rmse: 0.2932 - val_smape: 0.5020

Epoch 3/128

240/240 - 1s - 4ms/step - ia: 0.7900 - loss: 0.1892 - mae: 0.2928 - rmse: 0.4303 - smape: 0.6306 - val_ia: 0.8143 - val_loss: 0.0847 - val_mae: 0.1845 - val_rmse: 0.2694 - val_smape: 0.4610

Epoch 4/128

240/240 - 1s - 4ms/step - ia: 0.8088 - loss: 0.1627 - mae: 0.2685 - rmse: 0.3982 - smape: 0.5826 - val_ia: 0.8174 - val_loss: 0.0775 - val_mae: 0.1772 - val_rmse: 0.2578 - val_smape: 0.4401

Epoch 5/128

240/240 - 1s - 6ms/step - ia: 0.8206 - loss: 0.1495 - mae: 0.2525 - rmse: 0.3809 - smape: 0.5490 - val_ia: 0.8276 - val_loss: 0.0714 - val_mae: 0.1673 - val_rmse: 0.2476 - val_smape: 0.4245

Epoch 6/128

240/240 - 3s - 11ms/step - ia: 0.8289 - loss: 0.1389 - mae: 0.2415 - rmse: 0.3662 - smape: 0.5272 - val_ia: 0.8379 - val_loss: 0.0670 - val_mae: 0.1597 - val_rmse: 0.2388 - val_smape: 0.4050

Epoch 7/128

240/240 - 1s - 6ms/step - ia: 0.8365 - loss: 0.1296 - mae: 0.2320 - rmse: 0.3532 - smape: 0.5051 - val_ia: 0.8421 - val_loss: 0.0635 - val_mae: 0.1542 - val_rmse: 0.2337 - val_smape: 0.4021

Epoch 8/128

240/240 - 1s - 6ms/step - ia: 0.8413 - loss: 0.1228 - mae: 0.2256 - rmse: 0.3445 - smape: 0.4872 - val_ia: 0.8437 - val_loss: 0.0644 - val_mae: 0.1548 - val_rmse: 0.2327 - val_smape: 0.3918

Epoch 9/128

240/240 - 1s - 6ms/step - ia: 0.8438 - loss: 0.1227 - mae: 0.2218 - rmse: 0.3444 - smape: 0.4799 - val_ia: 0.8436 - val_loss: 0.0652 - val_mae: 0.1562 - val_rmse: 0.2333 - val_smape: 0.3909

Epoch 10/128

240/240 - 1s - 6ms/step - ia: 0.8465 - loss: 0.1165 - mae: 0.2183 - rmse: 0.3363 - smape: 0.4711 - val_ia: 0.8565 - val_loss: 0.0594 - val_mae: 0.1440 - val_rmse: 0.2230 - val_smape: 0.3737

Epoch 11/128

240/240 - 3s - 11ms/step - ia: 0.8477 - loss: 0.1190 - mae: 0.2171 - rmse: 0.3383 - smape: 0.4648 - val_ia: 0.8502 - val_loss: 0.0610 - val_mae: 0.1498 - val_rmse: 0.2266 - val_smape: 0.3843

Epoch 12/128

240/240 - 3s - 11ms/step - ia: 0.8492 - loss: 0.1167 - mae: 0.2158 - rmse: 0.3355 - smape: 0.4616 - val_ia: 0.8581 - val_loss: 0.0589 - val_mae: 0.1430 - val_rmse: 0.2213 - val_smape: 0.3698

Epoch 13/128

240/240 - 1s - 5ms/step - ia: 0.8495 - loss: 0.1162 - mae: 0.2148 - rmse: 0.3348 - smape: 0.4584 - val_ia: 0.8499 - val_loss: 0.0616 - val_mae: 0.1499 - val_rmse: 0.2263 - val_smape: 0.3779

Epoch 14/128

240/240 - 2s - 6ms/step - ia: 0.8515 - loss: 0.1098 - mae: 0.2120 - rmse: 0.3257 - smape: 0.4573 - val_ia: 0.8545 - val_loss: 0.0594 - val_mae: 0.1450 - val_rmse: 0.2225 - val_smape: 0.3717

Epoch 15/128

240/240 - 2s - 7ms/step - ia: 0.8518 - loss: 0.1130 - mae: 0.2118 - rmse: 0.3298 - smape: 0.4553 - val_ia: 0.8629 - val_loss: 0.0565 - val_mae: 0.1385 - val_rmse: 0.2171 - val_smape: 0.3658

Epoch 16/128

240/240 - 1s - 6ms/step - ia: 0.8519 - loss: 0.1124 - mae: 0.2117 - rmse: 0.3288 - smape: 0.4522 - val_ia: 0.8598 - val_loss: 0.0579 - val_mae: 0.1409 - val_rmse: 0.2195 - val_smape: 0.3661

Epoch 17/128

240/240 - 1s - 6ms/step - ia: 0.8522 - loss: 0.1107 - mae: 0.2109 - rmse: 0.3278 - smape: 0.4492 - val_ia: 0.8644 - val_loss: 0.0565 - val_mae: 0.1374 - val_rmse: 0.2165 - val_smape: 0.3604

Epoch 18/128

240/240 - 1s - 6ms/step - ia: 0.8519 - loss: 0.1127 - mae: 0.2116 - rmse: 0.3292 - smape: 0.4513 - val_ia: 0.8608 - val_loss: 0.0581 - val_mae: 0.1414 - val_rmse: 0.2195 - val_smape: 0.3667

Epoch 19/128

240/240 - 2s - 10ms/step - ia: 0.8534 - loss: 0.1110 - mae: 0.2098 - rmse: 0.3278 - smape: 0.4490 - val_ia: 0.8563 - val_loss: 0.0596 - val_mae: 0.1458 - val_rmse: 0.2219 - val_smape: 0.3704

Epoch 20/128

240/240 - 2s - 6ms/step - ia: 0.8519 - loss: 0.1126 - mae: 0.2114 - rmse: 0.3302 - smape: 0.4524 - val_ia: 0.8599 - val_loss: 0.0573 - val_mae: 0.1400 - val_rmse: 0.2190 - val_smape: 0.3665

Epoch 21/128

240/240 - 1s - 6ms/step - ia: 0.8525 - loss: 0.1111 - mae: 0.2110 - rmse: 0.3274 - smape: 0.4494 - val_ia: 0.8592 - val_loss: 0.0579 - val_mae: 0.1420 - val_rmse: 0.2191 - val_smape: 0.3652

Epoch 22/128

240/240 - 3s - 11ms/step - ia: 0.8519 - loss: 0.1127 - mae: 0.2113 - rmse: 0.3301 - smape: 0.4484 - val_ia: 0.8577 - val_loss: 0.0588 - val_mae: 0.1436 - val_rmse: 0.2207 - val_smape: 0.3665

Epoch 23/128

240/240 - 3s - 11ms/step - ia: 0.8544 - loss: 0.1073 - mae: 0.2081 - rmse: 0.3224 - smape: 0.4474 - val_ia: 0.8551 - val_loss: 0.0600 - val_mae: 0.1459 - val_rmse: 0.2227 - val_smape: 0.3692

Epoch 24/128

240/240 - 1s - 6ms/step - ia: 0.8523 - loss: 0.1132 - mae: 0.2109 - rmse: 0.3315 - smape: 0.4472 - val_ia: 0.8527 - val_loss: 0.0604 - val_mae: 0.1484 - val_rmse: 0.2237 - val_smape: 0.3737

Epoch 25/128

240/240 - 1s - 6ms/step - ia: 0.8540 - loss: 0.1097 - mae: 0.2090 - rmse: 0.3261 - smape: 0.4462 - val_ia: 0.8578 - val_loss: 0.0587 - val_mae: 0.1434 - val_rmse: 0.2206 - val_smape: 0.3664

Epoch 26/128

240/240 - 3s - 11ms/step - ia: 0.8530 - loss: 0.1117 - mae: 0.2102 - rmse: 0.3286 - smape: 0.4472 - val_ia: 0.8565 - val_loss: 0.0583 - val_mae: 0.1442 - val_rmse: 0.2203 - val_smape: 0.3668

Epoch 27/128

240/240 - 1s - 6ms/step - ia: 0.8537 - loss: 0.1103 - mae: 0.2092 - rmse: 0.3263 - smape: 0.4472 - val_ia: 0.8616 - val_loss: 0.0566 - val_mae: 0.1391 - val_rmse: 0.2172 - val_smape: 0.3614

Epoch 28/128

240/240 - 1s - 6ms/step - ia: 0.8532 - loss: 0.1100 - mae: 0.2100 - rmse: 0.3261 - smape: 0.4470 - val_ia: 0.8596 - val_loss: 0.0575 - val_mae: 0.1411 - val_rmse: 0.2190 - val_smape: 0.3650

Epoch 29/128

240/240 - 1s - 6ms/step - ia: 0.8531 - loss: 0.1136 - mae: 0.2105 - rmse: 0.3303 - smape: 0.4452 - val_ia: 0.8572 - val_loss: 0.0574 - val_mae: 0.1430 - val_rmse: 0.2189 - val_smape: 0.3652

Epoch 30/128

240/240 - 1s - 6ms/step - ia: 0.8526 - loss: 0.1106 - mae: 0.2104 - rmse: 0.3264 - smape: 0.4466 - val_ia: 0.8571 - val_loss: 0.0584 - val_mae: 0.1444 - val_rmse: 0.2204 - val_smape: 0.3668

Epoch 31/128

240/240 - 1s - 6ms/step - ia: 0.8543 - loss: 0.1066 - mae: 0.2082 - rmse: 0.3216 - smape: 0.4444 - val_ia: 0.8568 - val_loss: 0.0592 - val_mae: 0.1450 - val_rmse: 0.2214 - val_smape: 0.3678

Epoch 32/128

240/240 - 1s - 6ms/step - ia: 0.8549 - loss: 0.1059 - mae: 0.2072 - rmse: 0.3201 - smape: 0.4456 - val_ia: 0.8619 - val_loss: 0.0566 - val_mae: 0.1399 - val_rmse: 0.2174 - val_smape: 0.3631

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 43s 321ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 75%|███████▌  | 9/12 [3:07:16<35:26, 708.78s/trial, best loss: 0.036452573825096646]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 42s - 22ms/step - ia: 0.4631 - loss: 0.7617 - mae: 0.6332 - rmse: 0.8214 - smape: 1.1812 - val_ia: 0.3988 - val_loss: 0.2005 - val_mae: 0.3095 - val_rmse: 0.3713 - val_smape: 0.6991

Epoch 2/128

1916/1916 - 26s - 14ms/step - ia: 0.7195 - loss: 0.2699 - mae: 0.3713 - rmse: 0.4944 - smape: 0.7606 - val_ia: 0.4725 - val_loss: 0.1404 - val_mae: 0.2426 - val_rmse: 0.3029 - val_smape: 0.5625

Epoch 3/128

1916/1916 - 26s - 14ms/step - ia: 0.7614 - loss: 0.2026 - mae: 0.3155 - rmse: 0.4257 - smape: 0.6753 - val_ia: 0.5105 - val_loss: 0.1130 - val_mae: 0.2178 - val_rmse: 0.2764 - val_smape: 0.5207

Epoch 4/128

1916/1916 - 27s - 14ms/step - ia: 0.7806 - loss: 0.1739 - mae: 0.2890 - rmse: 0.3920 - smape: 0.6345 - val_ia: 0.5201 - val_loss: 0.1049 - val_mae: 0.2099 - val_rmse: 0.2658 - val_smape: 0.5094

Epoch 5/128

1916/1916 - 42s - 22ms/step - ia: 0.7946 - loss: 0.1559 - mae: 0.2706 - rmse: 0.3702 - smape: 0.6006 - val_ia: 0.5467 - val_loss: 0.0937 - val_mae: 0.1952 - val_rmse: 0.2509 - val_smape: 0.4847

Epoch 6/128

1916/1916 - 29s - 15ms/step - ia: 0.8074 - loss: 0.1423 - mae: 0.2561 - rmse: 0.3523 - smape: 0.5769 - val_ia: 0.5509 - val_loss: 0.0894 - val_mae: 0.1927 - val_rmse: 0.2460 - val_smape: 0.4730

Epoch 7/128

1916/1916 - 30s - 16ms/step - ia: 0.8159 - loss: 0.1342 - mae: 0.2459 - rmse: 0.3418 - smape: 0.5564 - val_ia: 0.5669 - val_loss: 0.0862 - val_mae: 0.1868 - val_rmse: 0.2399 - val_smape: 0.4659

Epoch 8/128

1916/1916 - 39s - 20ms/step - ia: 0.8216 - loss: 0.1271 - mae: 0.2381 - rmse: 0.3309 - smape: 0.5394 - val_ia: 0.5839 - val_loss: 0.0758 - val_mae: 0.1736 - val_rmse: 0.2267 - val_smape: 0.4409

Epoch 9/128

1916/1916 - 23s - 12ms/step - ia: 0.8287 - loss: 0.1191 - mae: 0.2306 - rmse: 0.3212 - smape: 0.5253 - val_ia: 0.5856 - val_loss: 0.0761 - val_mae: 0.1748 - val_rmse: 0.2264 - val_smape: 0.4363

Epoch 10/128

1916/1916 - 28s - 15ms/step - ia: 0.8328 - loss: 0.1149 - mae: 0.2245 - rmse: 0.3138 - smape: 0.5140 - val_ia: 0.5947 - val_loss: 0.0696 - val_mae: 0.1669 - val_rmse: 0.2192 - val_smape: 0.4252

Epoch 11/128

1916/1916 - 25s - 13ms/step - ia: 0.8378 - loss: 0.1100 - mae: 0.2183 - rmse: 0.3061 - smape: 0.5013 - val_ia: 0.6098 - val_loss: 0.0667 - val_mae: 0.1600 - val_rmse: 0.2122 - val_smape: 0.4121

Epoch 12/128

1916/1916 - 41s - 22ms/step - ia: 0.8399 - loss: 0.1082 - mae: 0.2153 - rmse: 0.3035 - smape: 0.4940 - val_ia: 0.6145 - val_loss: 0.0658 - val_mae: 0.1581 - val_rmse: 0.2100 - val_smape: 0.4082

Epoch 13/128

1916/1916 - 25s - 13ms/step - ia: 0.8424 - loss: 0.1052 - mae: 0.2120 - rmse: 0.2984 - smape: 0.4915 - val_ia: 0.6371 - val_loss: 0.0647 - val_mae: 0.1525 - val_rmse: 0.2054 - val_smape: 0.3970

Epoch 14/128

1916/1916 - 41s - 21ms/step - ia: 0.8464 - loss: 0.1012 - mae: 0.2076 - rmse: 0.2931 - smape: 0.4813 - val_ia: 0.6172 - val_loss: 0.0638 - val_mae: 0.1567 - val_rmse: 0.2076 - val_smape: 0.3983

Epoch 15/128

1916/1916 - 25s - 13ms/step - ia: 0.8481 - loss: 0.0982 - mae: 0.2044 - rmse: 0.2884 - smape: 0.4738 - val_ia: 0.6423 - val_loss: 0.0613 - val_mae: 0.1478 - val_rmse: 0.2004 - val_smape: 0.3916

Epoch 16/128

1916/1916 - 25s - 13ms/step - ia: 0.8498 - loss: 0.0979 - mae: 0.2026 - rmse: 0.2865 - smape: 0.4727 - val_ia: 0.6496 - val_loss: 0.0593 - val_mae: 0.1434 - val_rmse: 0.1969 - val_smape: 0.3782

Epoch 17/128

1916/1916 - 41s - 22ms/step - ia: 0.8519 - loss: 0.0947 - mae: 0.2002 - rmse: 0.2822 - smape: 0.4695 - val_ia: 0.6448 - val_loss: 0.0586 - val_mae: 0.1442 - val_rmse: 0.1974 - val_smape: 0.3782

Epoch 18/128

1916/1916 - 26s - 13ms/step - ia: 0.8545 - loss: 0.0918 - mae: 0.1966 - rmse: 0.2783 - smape: 0.4606 - val_ia: 0.6441 - val_loss: 0.0601 - val_mae: 0.1464 - val_rmse: 0.1979 - val_smape: 0.3798

Epoch 19/128

1916/1916 - 41s - 21ms/step - ia: 0.8562 - loss: 0.0912 - mae: 0.1943 - rmse: 0.2765 - smape: 0.4563 - val_ia: 0.6487 - val_loss: 0.0573 - val_mae: 0.1420 - val_rmse: 0.1946 - val_smape: 0.3736

Epoch 20/128

1916/1916 - 25s - 13ms/step - ia: 0.8565 - loss: 0.0911 - mae: 0.1934 - rmse: 0.2746 - smape: 0.4519 - val_ia: 0.6535 - val_loss: 0.0573 - val_mae: 0.1408 - val_rmse: 0.1935 - val_smape: 0.3711

Epoch 21/128

1916/1916 - 25s - 13ms/step - ia: 0.8578 - loss: 0.0906 - mae: 0.1922 - rmse: 0.2748 - smape: 0.4517 - val_ia: 0.6426 - val_loss: 0.0576 - val_mae: 0.1447 - val_rmse: 0.1955 - val_smape: 0.3774

Epoch 22/128

1916/1916 - 42s - 22ms/step - ia: 0.8584 - loss: 0.0898 - mae: 0.1919 - rmse: 0.2736 - smape: 0.4545 - val_ia: 0.6473 - val_loss: 0.0587 - val_mae: 0.1448 - val_rmse: 0.1958 - val_smape: 0.3736

Epoch 23/128

1916/1916 - 26s - 14ms/step - ia: 0.8593 - loss: 0.0887 - mae: 0.1902 - rmse: 0.2718 - smape: 0.4468 - val_ia: 0.6432 - val_loss: 0.0587 - val_mae: 0.1459 - val_rmse: 0.1966 - val_smape: 0.3748

Epoch 24/128

1916/1916 - 26s - 13ms/step - ia: 0.8612 - loss: 0.0871 - mae: 0.1877 - rmse: 0.2683 - smape: 0.4437 - val_ia: 0.6353 - val_loss: 0.0566 - val_mae: 0.1457 - val_rmse: 0.1964 - val_smape: 0.3767

Epoch 25/128

1916/1916 - 25s - 13ms/step - ia: 0.8613 - loss: 0.0865 - mae: 0.1870 - rmse: 0.2680 - smape: 0.4417 - val_ia: 0.6629 - val_loss: 0.0562 - val_mae: 0.1380 - val_rmse: 0.1908 - val_smape: 0.3625

Epoch 26/128

1916/1916 - 42s - 22ms/step - ia: 0.8635 - loss: 0.0851 - mae: 0.1849 - rmse: 0.2655 - smape: 0.4405 - val_ia: 0.6532 - val_loss: 0.0567 - val_mae: 0.1411 - val_rmse: 0.1929 - val_smape: 0.3671

Epoch 27/128

1916/1916 - 26s - 14ms/step - ia: 0.8627 - loss: 0.0862 - mae: 0.1858 - rmse: 0.2670 - smape: 0.4385 - val_ia: 0.6420 - val_loss: 0.0570 - val_mae: 0.1445 - val_rmse: 0.1955 - val_smape: 0.3733

Epoch 28/128

1916/1916 - 25s - 13ms/step - ia: 0.8648 - loss: 0.0838 - mae: 0.1833 - rmse: 0.2626 - smape: 0.4348 - val_ia: 0.6649 - val_loss: 0.0546 - val_mae: 0.1362 - val_rmse: 0.1882 - val_smape: 0.3631

Epoch 29/128

1916/1916 - 22s - 11ms/step - ia: 0.8642 - loss: 0.0833 - mae: 0.1830 - rmse: 0.2627 - smape: 0.4353 - val_ia: 0.6630 - val_loss: 0.0547 - val_mae: 0.1369 - val_rmse: 0.1886 - val_smape: 0.3626

Epoch 30/128

1916/1916 - 22s - 11ms/step - ia: 0.8643 - loss: 0.0847 - mae: 0.1838 - rmse: 0.2643 - smape: 0.4340 - val_ia: 0.6554 - val_loss: 0.0548 - val_mae: 0.1392 - val_rmse: 0.1903 - val_smape: 0.3655

Epoch 31/128

1916/1916 - 22s - 11ms/step - ia: 0.8649 - loss: 0.0843 - mae: 0.1834 - rmse: 0.2640 - smape: 0.4331 - val_ia: 0.6510 - val_loss: 0.0554 - val_mae: 0.1411 - val_rmse: 0.1922 - val_smape: 0.3681

Epoch 32/128

1916/1916 - 44s - 23ms/step - ia: 0.8654 - loss: 0.0842 - mae: 0.1823 - rmse: 0.2628 - smape: 0.4293 - val_ia: 0.6507 - val_loss: 0.0549 - val_mae: 0.1402 - val_rmse: 0.1915 - val_smape: 0.3670

Epoch 33/128

1916/1916 - 22s - 12ms/step - ia: 0.8667 - loss: 0.0826 - mae: 0.1802 - rmse: 0.2605 - smape: 0.4261 - val_ia: 0.6724 - val_loss: 0.0539 - val_mae: 0.1331 - val_rmse: 0.1864 - val_smape: 0.3552

Epoch 34/128

1916/1916 - 22s - 12ms/step - ia: 0.8671 - loss: 0.0836 - mae: 0.1806 - rmse: 0.2606 - smape: 0.4273 - val_ia: 0.6527 - val_loss: 0.0556 - val_mae: 0.1405 - val_rmse: 0.1920 - val_smape: 0.3673

Epoch 35/128

1916/1916 - 24s - 13ms/step - ia: 0.8678 - loss: 0.0813 - mae: 0.1794 - rmse: 0.2587 - smape: 0.4250 - val_ia: 0.6690 - val_loss: 0.0540 - val_mae: 0.1346 - val_rmse: 0.1866 - val_smape: 0.3578

Epoch 36/128

1916/1916 - 24s - 13ms/step - ia: 0.8680 - loss: 0.0819 - mae: 0.1794 - rmse: 0.2585 - smape: 0.4256 - val_ia: 0.6753 - val_loss: 0.0533 - val_mae: 0.1326 - val_rmse: 0.1849 - val_smape: 0.3551

Epoch 37/128

1916/1916 - 22s - 12ms/step - ia: 0.8674 - loss: 0.0812 - mae: 0.1796 - rmse: 0.2587 - smape: 0.4266 - val_ia: 0.6615 - val_loss: 0.0551 - val_mae: 0.1381 - val_rmse: 0.1890 - val_smape: 0.3615

Epoch 38/128

1916/1916 - 41s - 21ms/step - ia: 0.8681 - loss: 0.0818 - mae: 0.1786 - rmse: 0.2580 - smape: 0.4247 - val_ia: 0.6394 - val_loss: 0.0559 - val_mae: 0.1450 - val_rmse: 0.1960 - val_smape: 0.3802

Epoch 39/128

1916/1916 - 22s - 11ms/step - ia: 0.8690 - loss: 0.0793 - mae: 0.1773 - rmse: 0.2549 - smape: 0.4224 - val_ia: 0.6673 - val_loss: 0.0535 - val_mae: 0.1344 - val_rmse: 0.1864 - val_smape: 0.3574

Epoch 40/128

1916/1916 - 20s - 11ms/step - ia: 0.8689 - loss: 0.0804 - mae: 0.1777 - rmse: 0.2564 - smape: 0.4239 - val_ia: 0.6628 - val_loss: 0.0540 - val_mae: 0.1362 - val_rmse: 0.1881 - val_smape: 0.3588

Epoch 41/128

1916/1916 - 24s - 12ms/step - ia: 0.8700 - loss: 0.0813 - mae: 0.1774 - rmse: 0.2566 - smape: 0.4195 - val_ia: 0.6758 - val_loss: 0.0529 - val_mae: 0.1318 - val_rmse: 0.1845 - val_smape: 0.3545

Epoch 42/128

1916/1916 - 21s - 11ms/step - ia: 0.8689 - loss: 0.0811 - mae: 0.1785 - rmse: 0.2576 - smape: 0.4247 - val_ia: 0.6829 - val_loss: 0.0542 - val_mae: 0.1326 - val_rmse: 0.1847 - val_smape: 0.3530

Epoch 43/128

1916/1916 - 24s - 12ms/step - ia: 0.8700 - loss: 0.0795 - mae: 0.1761 - rmse: 0.2553 - smape: 0.4196 - val_ia: 0.6517 - val_loss: 0.0544 - val_mae: 0.1403 - val_rmse: 0.1906 - val_smape: 0.3653

Epoch 44/128

1916/1916 - 24s - 12ms/step - ia: 0.8712 - loss: 0.0790 - mae: 0.1755 - rmse: 0.2539 - smape: 0.4186 - val_ia: 0.6728 - val_loss: 0.0551 - val_mae: 0.1357 - val_rmse: 0.1871 - val_smape: 0.3544

Epoch 45/128

1916/1916 - 40s - 21ms/step - ia: 0.8713 - loss: 0.0788 - mae: 0.1754 - rmse: 0.2539 - smape: 0.4175 - val_ia: 0.6810 - val_loss: 0.0528 - val_mae: 0.1305 - val_rmse: 0.1835 - val_smape: 0.3505

Epoch 46/128

1916/1916 - 22s - 12ms/step - ia: 0.8701 - loss: 0.0787 - mae: 0.1762 - rmse: 0.2540 - smape: 0.4207 - val_ia: 0.6648 - val_loss: 0.0532 - val_mae: 0.1351 - val_rmse: 0.1870 - val_smape: 0.3603

Epoch 47/128

1916/1916 - 26s - 13ms/step - ia: 0.8712 - loss: 0.0790 - mae: 0.1750 - rmse: 0.2544 - smape: 0.4166 - val_ia: 0.6668 - val_loss: 0.0553 - val_mae: 0.1376 - val_rmse: 0.1880 - val_smape: 0.3590

Epoch 48/128

1916/1916 - 22s - 12ms/step - ia: 0.8700 - loss: 0.0788 - mae: 0.1756 - rmse: 0.2538 - smape: 0.4184 - val_ia: 0.6875 - val_loss: 0.0544 - val_mae: 0.1325 - val_rmse: 0.1848 - val_smape: 0.3545

Epoch 49/128

1916/1916 - 24s - 13ms/step - ia: 0.8719 - loss: 0.0777 - mae: 0.1741 - rmse: 0.2510 - smape: 0.4163 - val_ia: 0.6586 - val_loss: 0.0539 - val_mae: 0.1381 - val_rmse: 0.1888 - val_smape: 0.3633

Epoch 50/128

1916/1916 - 22s - 12ms/step - ia: 0.8709 - loss: 0.0785 - mae: 0.1751 - rmse: 0.2534 - smape: 0.4155 - val_ia: 0.6738 - val_loss: 0.0531 - val_mae: 0.1331 - val_rmse: 0.1847 - val_smape: 0.3551

Epoch 51/128

1916/1916 - 22s - 11ms/step - ia: 0.8722 - loss: 0.0775 - mae: 0.1740 - rmse: 0.2514 - smape: 0.4150 - val_ia: 0.6703 - val_loss: 0.0533 - val_mae: 0.1342 - val_rmse: 0.1861 - val_smape: 0.3574

Epoch 52/128

1916/1916 - 20s - 11ms/step - ia: 0.8712 - loss: 0.0786 - mae: 0.1743 - rmse: 0.2526 - smape: 0.4162 - val_ia: 0.6787 - val_loss: 0.0527 - val_mae: 0.1313 - val_rmse: 0.1840 - val_smape: 0.3533

Epoch 53/128

1916/1916 - 22s - 11ms/step - ia: 0.8718 - loss: 0.0789 - mae: 0.1739 - rmse: 0.2531 - smape: 0.4142 - val_ia: 0.6709 - val_loss: 0.0528 - val_mae: 0.1328 - val_rmse: 0.1852 - val_smape: 0.3547

Epoch 54/128

1916/1916 - 41s - 21ms/step - ia: 0.8711 - loss: 0.0796 - mae: 0.1747 - rmse: 0.2539 - smape: 0.4153 - val_ia: 0.6849 - val_loss: 0.0528 - val_mae: 0.1303 - val_rmse: 0.1828 - val_smape: 0.3494

Epoch 55/128

1916/1916 - 22s - 11ms/step - ia: 0.8719 - loss: 0.0774 - mae: 0.1733 - rmse: 0.2513 - smape: 0.4146 - val_ia: 0.6604 - val_loss: 0.0538 - val_mae: 0.1375 - val_rmse: 0.1882 - val_smape: 0.3616

Epoch 56/128

1916/1916 - 23s - 12ms/step - ia: 0.8730 - loss: 0.0771 - mae: 0.1731 - rmse: 0.2505 - smape: 0.4141 - val_ia: 0.6644 - val_loss: 0.0533 - val_mae: 0.1350 - val_rmse: 0.1873 - val_smape: 0.3587

Epoch 57/128

1916/1916 - 23s - 12ms/step - ia: 0.8716 - loss: 0.0772 - mae: 0.1734 - rmse: 0.2513 - smape: 0.4133 - val_ia: 0.6729 - val_loss: 0.0531 - val_mae: 0.1333 - val_rmse: 0.1845 - val_smape: 0.3536

Epoch 58/128

1916/1916 - 42s - 22ms/step - ia: 0.8734 - loss: 0.0761 - mae: 0.1719 - rmse: 0.2492 - smape: 0.4123 - val_ia: 0.6748 - val_loss: 0.0530 - val_mae: 0.1329 - val_rmse: 0.1847 - val_smape: 0.3545

Epoch 59/128

1916/1916 - 22s - 12ms/step - ia: 0.8726 - loss: 0.0757 - mae: 0.1720 - rmse: 0.2493 - smape: 0.4099 - val_ia: 0.6616 - val_loss: 0.0532 - val_mae: 0.1360 - val_rmse: 0.1871 - val_smape: 0.3588

Epoch 60/128

1916/1916 - 23s - 12ms/step - ia: 0.8727 - loss: 0.0768 - mae: 0.1731 - rmse: 0.2511 - smape: 0.4141 - val_ia: 0.6704 - val_loss: 0.0565 - val_mae: 0.1380 - val_rmse: 0.1890 - val_smape: 0.3572

Epoch 61/128

1916/1916 - 25s - 13ms/step - ia: 0.8732 - loss: 0.0771 - mae: 0.1720 - rmse: 0.2502 - smape: 0.4117 - val_ia: 0.6820 - val_loss: 0.0529 - val_mae: 0.1310 - val_rmse: 0.1831 - val_smape: 0.3490

Epoch 62/128

1916/1916 - 21s - 11ms/step - ia: 0.8737 - loss: 0.0763 - mae: 0.1712 - rmse: 0.2491 - smape: 0.4085 - val_ia: 0.6760 - val_loss: 0.0527 - val_mae: 0.1323 - val_rmse: 0.1840 - val_smape: 0.3529

Epoch 63/128

1916/1916 - 22s - 12ms/step - ia: 0.8736 - loss: 0.0765 - mae: 0.1716 - rmse: 0.2499 - smape: 0.4107 - val_ia: 0.6860 - val_loss: 0.0521 - val_mae: 0.1294 - val_rmse: 0.1820 - val_smape: 0.3488

Epoch 64/128

1916/1916 - 30s - 16ms/step - ia: 0.8741 - loss: 0.0759 - mae: 0.1714 - rmse: 0.2490 - smape: 0.4094 - val_ia: 0.6942 - val_loss: 0.0521 - val_mae: 0.1273 - val_rmse: 0.1810 - val_smape: 0.3453

Epoch 65/128

1916/1916 - 34s - 18ms/step - ia: 0.8738 - loss: 0.0760 - mae: 0.1712 - rmse: 0.2491 - smape: 0.4102 - val_ia: 0.6712 - val_loss: 0.0532 - val_mae: 0.1341 - val_rmse: 0.1855 - val_smape: 0.3544

Epoch 66/128

1916/1916 - 27s - 14ms/step - ia: 0.8744 - loss: 0.0756 - mae: 0.1703 - rmse: 0.2475 - smape: 0.4085 - val_ia: 0.6788 - val_loss: 0.0535 - val_mae: 0.1327 - val_rmse: 0.1845 - val_smape: 0.3517

Epoch 67/128

1916/1916 - 41s - 21ms/step - ia: 0.8735 - loss: 0.0760 - mae: 0.1717 - rmse: 0.2498 - smape: 0.4103 - val_ia: 0.6805 - val_loss: 0.0530 - val_mae: 0.1319 - val_rmse: 0.1842 - val_smape: 0.3519

Epoch 68/128

1916/1916 - 26s - 14ms/step - ia: 0.8733 - loss: 0.0769 - mae: 0.1719 - rmse: 0.2507 - smape: 0.4123 - val_ia: 0.6532 - val_loss: 0.0540 - val_mae: 0.1398 - val_rmse: 0.1904 - val_smape: 0.3660

Epoch 69/128

1916/1916 - 29s - 15ms/step - ia: 0.8742 - loss: 0.0756 - mae: 0.1714 - rmse: 0.2487 - smape: 0.4097 - val_ia: 0.6718 - val_loss: 0.0539 - val_mae: 0.1337 - val_rmse: 0.1870 - val_smape: 0.3556

Epoch 70/128

1916/1916 - 24s - 13ms/step - ia: 0.8740 - loss: 0.0772 - mae: 0.1712 - rmse: 0.2504 - smape: 0.4070 - val_ia: 0.6885 - val_loss: 0.0531 - val_mae: 0.1307 - val_rmse: 0.1830 - val_smape: 0.3486

Epoch 71/128

1916/1916 - 30s - 16ms/step - ia: 0.8754 - loss: 0.0757 - mae: 0.1702 - rmse: 0.2476 - smape: 0.4069 - val_ia: 0.6799 - val_loss: 0.0540 - val_mae: 0.1333 - val_rmse: 0.1842 - val_smape: 0.3529

Epoch 72/128

1916/1916 - 27s - 14ms/step - ia: 0.8743 - loss: 0.0750 - mae: 0.1709 - rmse: 0.2488 - smape: 0.4107 - val_ia: 0.6917 - val_loss: 0.0522 - val_mae: 0.1285 - val_rmse: 0.1811 - val_smape: 0.3472

Epoch 73/128

1916/1916 - 24s - 12ms/step - ia: 0.8748 - loss: 0.0752 - mae: 0.1703 - rmse: 0.2476 - smape: 0.4076 - val_ia: 0.6729 - val_loss: 0.0530 - val_mae: 0.1335 - val_rmse: 0.1857 - val_smape: 0.3571

Epoch 74/128

1916/1916 - 27s - 14ms/step - ia: 0.8750 - loss: 0.0753 - mae: 0.1705 - rmse: 0.2476 - smape: 0.4093 - val_ia: 0.6879 - val_loss: 0.0535 - val_mae: 0.1309 - val_rmse: 0.1832 - val_smape: 0.3480

Epoch 75/128

1916/1916 - 39s - 21ms/step - ia: 0.8753 - loss: 0.0740 - mae: 0.1688 - rmse: 0.2458 - smape: 0.4057 - val_ia: 0.6684 - val_loss: 0.0531 - val_mae: 0.1349 - val_rmse: 0.1861 - val_smape: 0.3579

Epoch 76/128

1916/1916 - 24s - 13ms/step - ia: 0.8745 - loss: 0.0764 - mae: 0.1706 - rmse: 0.2488 - smape: 0.4069 - val_ia: 0.6805 - val_loss: 0.0538 - val_mae: 0.1325 - val_rmse: 0.1842 - val_smape: 0.3507

Epoch 77/128

1916/1916 - 24s - 12ms/step - ia: 0.8755 - loss: 0.0748 - mae: 0.1697 - rmse: 0.2474 - smape: 0.4061 - val_ia: 0.6713 - val_loss: 0.0526 - val_mae: 0.1334 - val_rmse: 0.1854 - val_smape: 0.3579

Epoch 78/128

1916/1916 - 27s - 14ms/step - ia: 0.8752 - loss: 0.0745 - mae: 0.1695 - rmse: 0.2470 - smape: 0.4054 - val_ia: 0.7029 - val_loss: 0.0524 - val_mae: 0.1271 - val_rmse: 0.1815 - val_smape: 0.3427

Epoch 78: early stopping

Restoring model weights from the end of the best epoch: 63.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:35 2s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 83%|████████▎ | 10/12 [3:43:42<38:50, 1165.01s/trial, best loss: 0.036452573825096646]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 42s - 11ms/step - ia: 0.3221 - loss: 0.9890 - mae: 0.7088 - rmse: 0.9118 - smape: 1.4982 - val_ia: 0.2012 - val_loss: 0.8420 - val_mae: 0.6674 - val_rmse: 0.7038 - val_smape: 1.5239

Epoch 2/128

3832/3832 - 33s - 9ms/step - ia: 0.3325 - loss: 0.9530 - mae: 0.6980 - rmse: 0.8968 - smape: 1.4849 - val_ia: 0.2027 - val_loss: 0.8261 - val_mae: 0.6602 - val_rmse: 0.6965 - val_smape: 1.5026

Epoch 3/128

3832/3832 - 31s - 8ms/step - ia: 0.3366 - loss: 0.9385 - mae: 0.6936 - rmse: 0.8898 - smape: 1.4737 - val_ia: 0.2042 - val_loss: 0.8111 - val_mae: 0.6535 - val_rmse: 0.6896 - val_smape: 1.4828

Epoch 4/128

3832/3832 - 35s - 9ms/step - ia: 0.3422 - loss: 0.9269 - mae: 0.6860 - rmse: 0.8835 - smape: 1.4645 - val_ia: 0.2056 - val_loss: 0.7962 - val_mae: 0.6467 - val_rmse: 0.6827 - val_smape: 1.4625

Epoch 5/128

3832/3832 - 34s - 9ms/step - ia: 0.3522 - loss: 0.9021 - mae: 0.6768 - rmse: 0.8714 - smape: 1.4455 - val_ia: 0.2071 - val_loss: 0.7813 - val_mae: 0.6398 - val_rmse: 0.6757 - val_smape: 1.4410

Epoch 6/128

3832/3832 - 35s - 9ms/step - ia: 0.3563 - loss: 0.8866 - mae: 0.6705 - rmse: 0.8651 - smape: 1.4404 - val_ia: 0.2086 - val_loss: 0.7671 - val_mae: 0.6331 - val_rmse: 0.6690 - val_smape: 1.4197

Epoch 7/128

3832/3832 - 34s - 9ms/step - ia: 0.3611 - loss: 0.8746 - mae: 0.6685 - rmse: 0.8611 - smape: 1.4340 - val_ia: 0.2101 - val_loss: 0.7534 - val_mae: 0.6267 - val_rmse: 0.6625 - val_smape: 1.3997

Epoch 8/128

3832/3832 - 31s - 8ms/step - ia: 0.3679 - loss: 0.8783 - mae: 0.6610 - rmse: 0.8579 - smape: 1.4145 - val_ia: 0.2116 - val_loss: 0.7398 - val_mae: 0.6202 - val_rmse: 0.6560 - val_smape: 1.3793

Epoch 9/128

3832/3832 - 34s - 9ms/step - ia: 0.3773 - loss: 0.8536 - mae: 0.6520 - rmse: 0.8445 - smape: 1.3994 - val_ia: 0.2131 - val_loss: 0.7271 - val_mae: 0.6142 - val_rmse: 0.6499 - val_smape: 1.3595

Epoch 10/128

3832/3832 - 34s - 9ms/step - ia: 0.3797 - loss: 0.8446 - mae: 0.6497 - rmse: 0.8407 - smape: 1.3985 - val_ia: 0.2147 - val_loss: 0.7143 - val_mae: 0.6081 - val_rmse: 0.6439 - val_smape: 1.3399

Epoch 11/128

3832/3832 - 30s - 8ms/step - ia: 0.3838 - loss: 0.8226 - mae: 0.6436 - rmse: 0.8319 - smape: 1.3871 - val_ia: 0.2162 - val_loss: 0.7019 - val_mae: 0.6022 - val_rmse: 0.6379 - val_smape: 1.3205

Epoch 12/128

3832/3832 - 29s - 8ms/step - ia: 0.3912 - loss: 0.8212 - mae: 0.6376 - rmse: 0.8299 - smape: 1.3736 - val_ia: 0.2177 - val_loss: 0.6900 - val_mae: 0.5965 - val_rmse: 0.6322 - val_smape: 1.3021

Epoch 13/128

3832/3832 - 26s - 7ms/step - ia: 0.4010 - loss: 0.8018 - mae: 0.6317 - rmse: 0.8191 - smape: 1.3604 - val_ia: 0.2191 - val_loss: 0.6784 - val_mae: 0.5912 - val_rmse: 0.6269 - val_smape: 1.2855

Epoch 14/128

3832/3832 - 27s - 7ms/step - ia: 0.4075 - loss: 0.7894 - mae: 0.6239 - rmse: 0.8122 - smape: 1.3456 - val_ia: 0.2205 - val_loss: 0.6668 - val_mae: 0.5858 - val_rmse: 0.6215 - val_smape: 1.2689

Epoch 15/128

3832/3832 - 28s - 7ms/step - ia: 0.4113 - loss: 0.7883 - mae: 0.6237 - rmse: 0.8109 - smape: 1.3440 - val_ia: 0.2218 - val_loss: 0.6559 - val_mae: 0.5808 - val_rmse: 0.6164 - val_smape: 1.2537

Epoch 16/128

3832/3832 - 27s - 7ms/step - ia: 0.4118 - loss: 0.7911 - mae: 0.6224 - rmse: 0.8102 - smape: 1.3411 - val_ia: 0.2231 - val_loss: 0.6454 - val_mae: 0.5758 - val_rmse: 0.6114 - val_smape: 1.2386

Epoch 17/128

3832/3832 - 27s - 7ms/step - ia: 0.4177 - loss: 0.7777 - mae: 0.6167 - rmse: 0.8052 - smape: 1.3315 - val_ia: 0.2243 - val_loss: 0.6352 - val_mae: 0.5710 - val_rmse: 0.6066 - val_smape: 1.2244

Epoch 18/128

3832/3832 - 41s - 11ms/step - ia: 0.4217 - loss: 0.7614 - mae: 0.6132 - rmse: 0.8000 - smape: 1.3208 - val_ia: 0.2254 - val_loss: 0.6255 - val_mae: 0.5665 - val_rmse: 0.6021 - val_smape: 1.2113

Epoch 19/128

3832/3832 - 27s - 7ms/step - ia: 0.4258 - loss: 0.7469 - mae: 0.6084 - rmse: 0.7904 - smape: 1.3200 - val_ia: 0.2265 - val_loss: 0.6158 - val_mae: 0.5621 - val_rmse: 0.5977 - val_smape: 1.1983

Epoch 20/128

3832/3832 - 28s - 7ms/step - ia: 0.4334 - loss: 0.7386 - mae: 0.6026 - rmse: 0.7852 - smape: 1.3054 - val_ia: 0.2276 - val_loss: 0.6060 - val_mae: 0.5576 - val_rmse: 0.5931 - val_smape: 1.1853

Epoch 21/128

3832/3832 - 27s - 7ms/step - ia: 0.4376 - loss: 0.7290 - mae: 0.6003 - rmse: 0.7809 - smape: 1.2986 - val_ia: 0.2286 - val_loss: 0.5970 - val_mae: 0.5536 - val_rmse: 0.5891 - val_smape: 1.1741

Epoch 22/128

3832/3832 - 42s - 11ms/step - ia: 0.4402 - loss: 0.7317 - mae: 0.5993 - rmse: 0.7815 - smape: 1.2935 - val_ia: 0.2295 - val_loss: 0.5881 - val_mae: 0.5495 - val_rmse: 0.5850 - val_smape: 1.1626

Epoch 23/128

3832/3832 - 29s - 7ms/step - ia: 0.4435 - loss: 0.7254 - mae: 0.5959 - rmse: 0.7790 - smape: 1.2908 - val_ia: 0.2304 - val_loss: 0.5796 - val_mae: 0.5457 - val_rmse: 0.5812 - val_smape: 1.1522

Epoch 24/128

3832/3832 - 26s - 7ms/step - ia: 0.4471 - loss: 0.7198 - mae: 0.5915 - rmse: 0.7738 - smape: 1.2783 - val_ia: 0.2313 - val_loss: 0.5716 - val_mae: 0.5420 - val_rmse: 0.5775 - val_smape: 1.1419

Epoch 25/128

3832/3832 - 20s - 5ms/step - ia: 0.4525 - loss: 0.7108 - mae: 0.5866 - rmse: 0.7681 - smape: 1.2695 - val_ia: 0.2321 - val_loss: 0.5635 - val_mae: 0.5383 - val_rmse: 0.5738 - val_smape: 1.1319

Epoch 26/128

3832/3832 - 26s - 7ms/step - ia: 0.4525 - loss: 0.7038 - mae: 0.5866 - rmse: 0.7654 - smape: 1.2719 - val_ia: 0.2329 - val_loss: 0.5554 - val_mae: 0.5347 - val_rmse: 0.5702 - val_smape: 1.1226

Epoch 27/128

3832/3832 - 42s - 11ms/step - ia: 0.4513 - loss: 0.7083 - mae: 0.5868 - rmse: 0.7675 - smape: 1.2712 - val_ia: 0.2336 - val_loss: 0.5480 - val_mae: 0.5314 - val_rmse: 0.5669 - val_smape: 1.1140

Epoch 28/128

3832/3832 - 27s - 7ms/step - ia: 0.4608 - loss: 0.6905 - mae: 0.5793 - rmse: 0.7561 - smape: 1.2561 - val_ia: 0.2343 - val_loss: 0.5402 - val_mae: 0.5280 - val_rmse: 0.5634 - val_smape: 1.1052

Epoch 29/128

3832/3832 - 22s - 6ms/step - ia: 0.4640 - loss: 0.6876 - mae: 0.5770 - rmse: 0.7546 - smape: 1.2491 - val_ia: 0.2350 - val_loss: 0.5330 - val_mae: 0.5247 - val_rmse: 0.5601 - val_smape: 1.0968

Epoch 30/128

3832/3832 - 23s - 6ms/step - ia: 0.4655 - loss: 0.6830 - mae: 0.5754 - rmse: 0.7528 - smape: 1.2499 - val_ia: 0.2357 - val_loss: 0.5261 - val_mae: 0.5215 - val_rmse: 0.5569 - val_smape: 1.0881

Epoch 31/128

3832/3832 - 28s - 7ms/step - ia: 0.4678 - loss: 0.6754 - mae: 0.5721 - rmse: 0.7478 - smape: 1.2462 - val_ia: 0.2365 - val_loss: 0.5191 - val_mae: 0.5181 - val_rmse: 0.5535 - val_smape: 1.0791

Epoch 32/128

3832/3832 - 24s - 6ms/step - ia: 0.4678 - loss: 0.6761 - mae: 0.5735 - rmse: 0.7513 - smape: 1.2430 - val_ia: 0.2372 - val_loss: 0.5124 - val_mae: 0.5150 - val_rmse: 0.5504 - val_smape: 1.0709

Epoch 33/128

3832/3832 - 21s - 6ms/step - ia: 0.4713 - loss: 0.6800 - mae: 0.5711 - rmse: 0.7490 - smape: 1.2351 - val_ia: 0.2378 - val_loss: 0.5062 - val_mae: 0.5120 - val_rmse: 0.5474 - val_smape: 1.0630

Epoch 34/128

3832/3832 - 27s - 7ms/step - ia: 0.4746 - loss: 0.6685 - mae: 0.5682 - rmse: 0.7449 - smape: 1.2291 - val_ia: 0.2385 - val_loss: 0.5000 - val_mae: 0.5089 - val_rmse: 0.5443 - val_smape: 1.0550

Epoch 35/128

3832/3832 - 43s - 11ms/step - ia: 0.4791 - loss: 0.6595 - mae: 0.5639 - rmse: 0.7386 - smape: 1.2174 - val_ia: 0.2391 - val_loss: 0.4938 - val_mae: 0.5060 - val_rmse: 0.5414 - val_smape: 1.0476

Epoch 36/128

3832/3832 - 29s - 8ms/step - ia: 0.4799 - loss: 0.6644 - mae: 0.5646 - rmse: 0.7415 - smape: 1.2185 - val_ia: 0.2397 - val_loss: 0.4880 - val_mae: 0.5031 - val_rmse: 0.5385 - val_smape: 1.0401

Epoch 37/128

3832/3832 - 22s - 6ms/step - ia: 0.4853 - loss: 0.6530 - mae: 0.5592 - rmse: 0.7330 - smape: 1.2125 - val_ia: 0.2404 - val_loss: 0.4821 - val_mae: 0.5001 - val_rmse: 0.5355 - val_smape: 1.0320

Epoch 38/128

3832/3832 - 47s - 12ms/step - ia: 0.4858 - loss: 0.6473 - mae: 0.5586 - rmse: 0.7322 - smape: 1.2074 - val_ia: 0.2411 - val_loss: 0.4766 - val_mae: 0.4972 - val_rmse: 0.5326 - val_smape: 1.0243

Epoch 39/128

3832/3832 - 22s - 6ms/step - ia: 0.4870 - loss: 0.6459 - mae: 0.5578 - rmse: 0.7304 - smape: 1.2034 - val_ia: 0.2416 - val_loss: 0.4713 - val_mae: 0.4944 - val_rmse: 0.5298 - val_smape: 1.0171

Epoch 40/128

3832/3832 - 22s - 6ms/step - ia: 0.4919 - loss: 0.6446 - mae: 0.5537 - rmse: 0.7288 - smape: 1.1938 - val_ia: 0.2421 - val_loss: 0.4664 - val_mae: 0.4920 - val_rmse: 0.5274 - val_smape: 1.0109

Epoch 41/128

3832/3832 - 48s - 13ms/step - ia: 0.4933 - loss: 0.6357 - mae: 0.5518 - rmse: 0.7246 - smape: 1.1885 - val_ia: 0.2428 - val_loss: 0.4610 - val_mae: 0.4890 - val_rmse: 0.5244 - val_smape: 1.0030

Epoch 42/128

3832/3832 - 24s - 6ms/step - ia: 0.4961 - loss: 0.6331 - mae: 0.5501 - rmse: 0.7219 - smape: 1.1852 - val_ia: 0.2432 - val_loss: 0.4561 - val_mae: 0.4867 - val_rmse: 0.5221 - val_smape: 0.9973

Epoch 43/128

3832/3832 - 27s - 7ms/step - ia: 0.4959 - loss: 0.6336 - mae: 0.5486 - rmse: 0.7227 - smape: 1.1772 - val_ia: 0.2437 - val_loss: 0.4514 - val_mae: 0.4843 - val_rmse: 0.5197 - val_smape: 0.9915

Epoch 44/128

3832/3832 - 30s - 8ms/step - ia: 0.4960 - loss: 0.6342 - mae: 0.5507 - rmse: 0.7241 - smape: 1.1807 - val_ia: 0.2441 - val_loss: 0.4467 - val_mae: 0.4819 - val_rmse: 0.5173 - val_smape: 0.9851

Epoch 45/128

3832/3832 - 25s - 6ms/step - ia: 0.5020 - loss: 0.6178 - mae: 0.5440 - rmse: 0.7157 - smape: 1.1712 - val_ia: 0.2445 - val_loss: 0.4425 - val_mae: 0.4797 - val_rmse: 0.5151 - val_smape: 0.9798

Epoch 46/128

3832/3832 - 29s - 8ms/step - ia: 0.4991 - loss: 0.6217 - mae: 0.5453 - rmse: 0.7174 - smape: 1.1740 - val_ia: 0.2450 - val_loss: 0.4380 - val_mae: 0.4773 - val_rmse: 0.5127 - val_smape: 0.9737

Epoch 47/128

3832/3832 - 42s - 11ms/step - ia: 0.5022 - loss: 0.6224 - mae: 0.5447 - rmse: 0.7173 - smape: 1.1656 - val_ia: 0.2454 - val_loss: 0.4341 - val_mae: 0.4752 - val_rmse: 0.5106 - val_smape: 0.9682

Epoch 48/128

3832/3832 - 38s - 10ms/step - ia: 0.5044 - loss: 0.6141 - mae: 0.5418 - rmse: 0.7130 - smape: 1.1659 - val_ia: 0.2459 - val_loss: 0.4300 - val_mae: 0.4727 - val_rmse: 0.5081 - val_smape: 0.9616

Epoch 49/128

3832/3832 - 28s - 7ms/step - ia: 0.5048 - loss: 0.6230 - mae: 0.5425 - rmse: 0.7150 - smape: 1.1557 - val_ia: 0.2462 - val_loss: 0.4261 - val_mae: 0.4708 - val_rmse: 0.5063 - val_smape: 0.9571

Epoch 50/128

3832/3832 - 27s - 7ms/step - ia: 0.5051 - loss: 0.6223 - mae: 0.5417 - rmse: 0.7146 - smape: 1.1549 - val_ia: 0.2467 - val_loss: 0.4223 - val_mae: 0.4686 - val_rmse: 0.5041 - val_smape: 0.9512

Epoch 51/128

3832/3832 - 27s - 7ms/step - ia: 0.5097 - loss: 0.6153 - mae: 0.5384 - rmse: 0.7110 - smape: 1.1473 - val_ia: 0.2470 - val_loss: 0.4188 - val_mae: 0.4666 - val_rmse: 0.5020 - val_smape: 0.9459

Epoch 52/128

3832/3832 - 42s - 11ms/step - ia: 0.5154 - loss: 0.6029 - mae: 0.5330 - rmse: 0.7027 - smape: 1.1398 - val_ia: 0.2474 - val_loss: 0.4153 - val_mae: 0.4645 - val_rmse: 0.5000 - val_smape: 0.9406

Epoch 53/128

3832/3832 - 28s - 7ms/step - ia: 0.5179 - loss: 0.5987 - mae: 0.5314 - rmse: 0.7008 - smape: 1.1375 - val_ia: 0.2478 - val_loss: 0.4116 - val_mae: 0.4625 - val_rmse: 0.4980 - val_smape: 0.9353

Epoch 54/128

3832/3832 - 28s - 7ms/step - ia: 0.5193 - loss: 0.6021 - mae: 0.5315 - rmse: 0.7018 - smape: 1.1296 - val_ia: 0.2482 - val_loss: 0.4085 - val_mae: 0.4605 - val_rmse: 0.4960 - val_smape: 0.9299

Epoch 55/128

3832/3832 - 24s - 6ms/step - ia: 0.5197 - loss: 0.5997 - mae: 0.5302 - rmse: 0.7002 - smape: 1.1280 - val_ia: 0.2486 - val_loss: 0.4055 - val_mae: 0.4586 - val_rmse: 0.4942 - val_smape: 0.9249

Epoch 56/128

3832/3832 - 21s - 5ms/step - ia: 0.5195 - loss: 0.5998 - mae: 0.5288 - rmse: 0.7002 - smape: 1.1208 - val_ia: 0.2489 - val_loss: 0.4027 - val_mae: 0.4570 - val_rmse: 0.4926 - val_smape: 0.9208

Epoch 57/128

3832/3832 - 26s - 7ms/step - ia: 0.5201 - loss: 0.5964 - mae: 0.5300 - rmse: 0.6989 - smape: 1.1264 - val_ia: 0.2492 - val_loss: 0.3997 - val_mae: 0.4553 - val_rmse: 0.4909 - val_smape: 0.9165

Epoch 58/128

3832/3832 - 27s - 7ms/step - ia: 0.5211 - loss: 0.5894 - mae: 0.5271 - rmse: 0.6969 - smape: 1.1166 - val_ia: 0.2496 - val_loss: 0.3967 - val_mae: 0.4535 - val_rmse: 0.4891 - val_smape: 0.9119

Epoch 59/128

3832/3832 - 42s - 11ms/step - ia: 0.5241 - loss: 0.5806 - mae: 0.5263 - rmse: 0.6931 - smape: 1.1146 - val_ia: 0.2498 - val_loss: 0.3940 - val_mae: 0.4520 - val_rmse: 0.4876 - val_smape: 0.9080

Epoch 60/128

3832/3832 - 27s - 7ms/step - ia: 0.5276 - loss: 0.5859 - mae: 0.5226 - rmse: 0.6916 - smape: 1.1067 - val_ia: 0.2502 - val_loss: 0.3909 - val_mae: 0.4502 - val_rmse: 0.4858 - val_smape: 0.9038

Epoch 61/128

3832/3832 - 27s - 7ms/step - ia: 0.5281 - loss: 0.5836 - mae: 0.5239 - rmse: 0.6921 - smape: 1.1031 - val_ia: 0.2504 - val_loss: 0.3886 - val_mae: 0.4488 - val_rmse: 0.4845 - val_smape: 0.9004

Epoch 62/128

3832/3832 - 28s - 7ms/step - ia: 0.5305 - loss: 0.5854 - mae: 0.5214 - rmse: 0.6904 - smape: 1.0976 - val_ia: 0.2506 - val_loss: 0.3863 - val_mae: 0.4475 - val_rmse: 0.4832 - val_smape: 0.8974

Epoch 63/128

3832/3832 - 27s - 7ms/step - ia: 0.5304 - loss: 0.5774 - mae: 0.5197 - rmse: 0.6869 - smape: 1.0942 - val_ia: 0.2510 - val_loss: 0.3835 - val_mae: 0.4458 - val_rmse: 0.4815 - val_smape: 0.8935

Epoch 64/128

3832/3832 - 41s - 11ms/step - ia: 0.5363 - loss: 0.5765 - mae: 0.5159 - rmse: 0.6840 - smape: 1.0837 - val_ia: 0.2512 - val_loss: 0.3816 - val_mae: 0.4447 - val_rmse: 0.4804 - val_smape: 0.8908

Epoch 65/128

3832/3832 - 42s - 11ms/step - ia: 0.5367 - loss: 0.5627 - mae: 0.5138 - rmse: 0.6787 - smape: 1.0835 - val_ia: 0.2517 - val_loss: 0.3788 - val_mae: 0.4426 - val_rmse: 0.4784 - val_smape: 0.8858

Epoch 66/128

3832/3832 - 30s - 8ms/step - ia: 0.5361 - loss: 0.5721 - mae: 0.5151 - rmse: 0.6827 - smape: 1.0819 - val_ia: 0.2519 - val_loss: 0.3764 - val_mae: 0.4413 - val_rmse: 0.4771 - val_smape: 0.8830

Epoch 67/128

3832/3832 - 38s - 10ms/step - ia: 0.5408 - loss: 0.5679 - mae: 0.5129 - rmse: 0.6806 - smape: 1.0747 - val_ia: 0.2521 - val_loss: 0.3744 - val_mae: 0.4401 - val_rmse: 0.4759 - val_smape: 0.8804

Epoch 68/128

3832/3832 - 27s - 7ms/step - ia: 0.5352 - loss: 0.5769 - mae: 0.5167 - rmse: 0.6869 - smape: 1.0793 - val_ia: 0.2523 - val_loss: 0.3727 - val_mae: 0.4390 - val_rmse: 0.4749 - val_smape: 0.8782

Epoch 69/128

3832/3832 - 27s - 7ms/step - ia: 0.5434 - loss: 0.5614 - mae: 0.5101 - rmse: 0.6751 - smape: 1.0687 - val_ia: 0.2525 - val_loss: 0.3708 - val_mae: 0.4379 - val_rmse: 0.4738 - val_smape: 0.8758

Epoch 70/128

3832/3832 - 27s - 7ms/step - ia: 0.5439 - loss: 0.5604 - mae: 0.5093 - rmse: 0.6743 - smape: 1.0658 - val_ia: 0.2528 - val_loss: 0.3685 - val_mae: 0.4365 - val_rmse: 0.4723 - val_smape: 0.8727

Epoch 71/128

3832/3832 - 41s - 11ms/step - ia: 0.5398 - loss: 0.5772 - mae: 0.5135 - rmse: 0.6835 - smape: 1.0675 - val_ia: 0.2528 - val_loss: 0.3673 - val_mae: 0.4360 - val_rmse: 0.4719 - val_smape: 0.8720

Epoch 72/128

3832/3832 - 28s - 7ms/step - ia: 0.5504 - loss: 0.5452 - mae: 0.5038 - rmse: 0.6671 - smape: 1.0563 - val_ia: 0.2531 - val_loss: 0.3653 - val_mae: 0.4348 - val_rmse: 0.4707 - val_smape: 0.8697

Epoch 73/128

3832/3832 - 30s - 8ms/step - ia: 0.5457 - loss: 0.5582 - mae: 0.5071 - rmse: 0.6744 - smape: 1.0594 - val_ia: 0.2532 - val_loss: 0.3633 - val_mae: 0.4338 - val_rmse: 0.4697 - val_smape: 0.8679

Epoch 74/128

3832/3832 - 28s - 7ms/step - ia: 0.5486 - loss: 0.5497 - mae: 0.5060 - rmse: 0.6703 - smape: 1.0565 - val_ia: 0.2534 - val_loss: 0.3616 - val_mae: 0.4328 - val_rmse: 0.4686 - val_smape: 0.8658

Epoch 75/128

3832/3832 - 34s - 9ms/step - ia: 0.5506 - loss: 0.5440 - mae: 0.5039 - rmse: 0.6666 - smape: 1.0525 - val_ia: 0.2535 - val_loss: 0.3599 - val_mae: 0.4321 - val_rmse: 0.4679 - val_smape: 0.8650

Epoch 76/128

3832/3832 - 47s - 12ms/step - ia: 0.5506 - loss: 0.5567 - mae: 0.5055 - rmse: 0.6711 - smape: 1.0513 - val_ia: 0.2537 - val_loss: 0.3581 - val_mae: 0.4310 - val_rmse: 0.4669 - val_smape: 0.8630

Epoch 77/128

3832/3832 - 28s - 7ms/step - ia: 0.5479 - loss: 0.5601 - mae: 0.5063 - rmse: 0.6738 - smape: 1.0496 - val_ia: 0.2539 - val_loss: 0.3567 - val_mae: 0.4300 - val_rmse: 0.4659 - val_smape: 0.8610

Epoch 78/128

3832/3832 - 29s - 8ms/step - ia: 0.5540 - loss: 0.5415 - mae: 0.4991 - rmse: 0.6616 - smape: 1.0414 - val_ia: 0.2543 - val_loss: 0.3549 - val_mae: 0.4285 - val_rmse: 0.4644 - val_smape: 0.8576

Epoch 79/128

3832/3832 - 26s - 7ms/step - ia: 0.5507 - loss: 0.5420 - mae: 0.5020 - rmse: 0.6662 - smape: 1.0431 - val_ia: 0.2546 - val_loss: 0.3531 - val_mae: 0.4274 - val_rmse: 0.4634 - val_smape: 0.8558

Epoch 80/128

3832/3832 - 26s - 7ms/step - ia: 0.5557 - loss: 0.5380 - mae: 0.4977 - rmse: 0.6605 - smape: 1.0354 - val_ia: 0.2547 - val_loss: 0.3517 - val_mae: 0.4266 - val_rmse: 0.4626 - val_smape: 0.8545

Epoch 81/128

3832/3832 - 25s - 7ms/step - ia: 0.5542 - loss: 0.5477 - mae: 0.5013 - rmse: 0.6674 - smape: 1.0368 - val_ia: 0.2548 - val_loss: 0.3506 - val_mae: 0.4261 - val_rmse: 0.4620 - val_smape: 0.8537

Epoch 82/128

3832/3832 - 29s - 7ms/step - ia: 0.5562 - loss: 0.5366 - mae: 0.4982 - rmse: 0.6613 - smape: 1.0302 - val_ia: 0.2550 - val_loss: 0.3492 - val_mae: 0.4253 - val_rmse: 0.4613 - val_smape: 0.8525

Epoch 83/128

3832/3832 - 42s - 11ms/step - ia: 0.5538 - loss: 0.5478 - mae: 0.5011 - rmse: 0.6659 - smape: 1.0338 - val_ia: 0.2553 - val_loss: 0.3476 - val_mae: 0.4240 - val_rmse: 0.4600 - val_smape: 0.8496

Epoch 84/128

3832/3832 - 30s - 8ms/step - ia: 0.5566 - loss: 0.5351 - mae: 0.4989 - rmse: 0.6601 - smape: 1.0320 - val_ia: 0.2556 - val_loss: 0.3461 - val_mae: 0.4229 - val_rmse: 0.4589 - val_smape: 0.8473

Epoch 85/128

3832/3832 - 41s - 11ms/step - ia: 0.5592 - loss: 0.5334 - mae: 0.4980 - rmse: 0.6597 - smape: 1.0278 - val_ia: 0.2556 - val_loss: 0.3452 - val_mae: 0.4225 - val_rmse: 0.4584 - val_smape: 0.8468

Epoch 86/128

3832/3832 - 30s - 8ms/step - ia: 0.5586 - loss: 0.5303 - mae: 0.4963 - rmse: 0.6580 - smape: 1.0283 - val_ia: 0.2559 - val_loss: 0.3433 - val_mae: 0.4214 - val_rmse: 0.4574 - val_smape: 0.8448

Epoch 87/128

3832/3832 - 31s - 8ms/step - ia: 0.5595 - loss: 0.5381 - mae: 0.4972 - rmse: 0.6606 - smape: 1.0246 - val_ia: 0.2560 - val_loss: 0.3424 - val_mae: 0.4210 - val_rmse: 0.4570 - val_smape: 0.8447

Epoch 88/128

3832/3832 - 27s - 7ms/step - ia: 0.5582 - loss: 0.5354 - mae: 0.4979 - rmse: 0.6600 - smape: 1.0260 - val_ia: 0.2561 - val_loss: 0.3416 - val_mae: 0.4206 - val_rmse: 0.4566 - val_smape: 0.8440

Epoch 89/128

3832/3832 - 25s - 7ms/step - ia: 0.5625 - loss: 0.5306 - mae: 0.4938 - rmse: 0.6569 - smape: 1.0144 - val_ia: 0.2563 - val_loss: 0.3401 - val_mae: 0.4196 - val_rmse: 0.4556 - val_smape: 0.8424

Epoch 90/128

3832/3832 - 29s - 8ms/step - ia: 0.5613 - loss: 0.5338 - mae: 0.4951 - rmse: 0.6590 - smape: 1.0188 - val_ia: 0.2565 - val_loss: 0.3390 - val_mae: 0.4188 - val_rmse: 0.4548 - val_smape: 0.8408

Epoch 91/128

3832/3832 - 29s - 8ms/step - ia: 0.5658 - loss: 0.5246 - mae: 0.4900 - rmse: 0.6509 - smape: 1.0101 - val_ia: 0.2567 - val_loss: 0.3377 - val_mae: 0.4181 - val_rmse: 0.4541 - val_smape: 0.8397

Epoch 92/128

3832/3832 - 23s - 6ms/step - ia: 0.5672 - loss: 0.5243 - mae: 0.4915 - rmse: 0.6528 - smape: 1.0100 - val_ia: 0.2568 - val_loss: 0.3366 - val_mae: 0.4175 - val_rmse: 0.4536 - val_smape: 0.8389

Epoch 93/128

3832/3832 - 27s - 7ms/step - ia: 0.5652 - loss: 0.5300 - mae: 0.4922 - rmse: 0.6554 - smape: 1.0092 - val_ia: 0.2572 - val_loss: 0.3348 - val_mae: 0.4162 - val_rmse: 0.4523 - val_smape: 0.8363

Epoch 94/128

3832/3832 - 25s - 6ms/step - ia: 0.5657 - loss: 0.5161 - mae: 0.4907 - rmse: 0.6492 - smape: 1.0102 - val_ia: 0.2573 - val_loss: 0.3337 - val_mae: 0.4158 - val_rmse: 0.4518 - val_smape: 0.8360

Epoch 95/128

3832/3832 - 24s - 6ms/step - ia: 0.5673 - loss: 0.5287 - mae: 0.4919 - rmse: 0.6544 - smape: 1.0058 - val_ia: 0.2572 - val_loss: 0.3334 - val_mae: 0.4159 - val_rmse: 0.4520 - val_smape: 0.8368

Epoch 96/128

3832/3832 - 47s - 12ms/step - ia: 0.5655 - loss: 0.5290 - mae: 0.4919 - rmse: 0.6536 - smape: 1.0093 - val_ia: 0.2573 - val_loss: 0.3327 - val_mae: 0.4156 - val_rmse: 0.4516 - val_smape: 0.8368

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 7s - 31ms/step - ia: 0.4495 - loss: 0.7126 - mae: 0.6185 - rmse: 0.8279 - smape: 1.2121 - val_ia: 0.5912 - val_loss: 0.3045 - val_mae: 0.4018 - val_rmse: 0.4997 - val_smape: 0.8877

Epoch 2/128

240/240 - 3s - 13ms/step - ia: 0.7165 - loss: 0.2833 - mae: 0.3904 - rmse: 0.5265 - smape: 0.8033 - val_ia: 0.7619 - val_loss: 0.1365 - val_mae: 0.2449 - val_rmse: 0.3367 - val_smape: 0.5639

Epoch 3/128

240/240 - 3s - 13ms/step - ia: 0.7784 - loss: 0.1938 - mae: 0.3178 - rmse: 0.4361 - smape: 0.6843 - val_ia: 0.7974 - val_loss: 0.1050 - val_mae: 0.2047 - val_rmse: 0.2957 - val_smape: 0.4978

Epoch 4/128

240/240 - 3s - 13ms/step - ia: 0.7997 - loss: 0.1647 - mae: 0.2874 - rmse: 0.4017 - smape: 0.6381 - val_ia: 0.8110 - val_loss: 0.0940 - val_mae: 0.1904 - val_rmse: 0.2796 - val_smape: 0.4704

Epoch 5/128

240/240 - 5s - 21ms/step - ia: 0.8148 - loss: 0.1448 - mae: 0.2659 - rmse: 0.3766 - smape: 0.6022 - val_ia: 0.8200 - val_loss: 0.0841 - val_mae: 0.1787 - val_rmse: 0.2652 - val_smape: 0.4491

Epoch 6/128

240/240 - 5s - 20ms/step - ia: 0.8256 - loss: 0.1315 - mae: 0.2505 - rmse: 0.3579 - smape: 0.5737 - val_ia: 0.8269 - val_loss: 0.0796 - val_mae: 0.1722 - val_rmse: 0.2576 - val_smape: 0.4370

Epoch 7/128

240/240 - 5s - 19ms/step - ia: 0.8334 - loss: 0.1222 - mae: 0.2395 - rmse: 0.3451 - smape: 0.5585 - val_ia: 0.8243 - val_loss: 0.0753 - val_mae: 0.1706 - val_rmse: 0.2525 - val_smape: 0.4318

Epoch 8/128

240/240 - 5s - 22ms/step - ia: 0.8410 - loss: 0.1135 - mae: 0.2290 - rmse: 0.3323 - smape: 0.5360 - val_ia: 0.8341 - val_loss: 0.0708 - val_mae: 0.1624 - val_rmse: 0.2443 - val_smape: 0.4163

Epoch 9/128

240/240 - 5s - 19ms/step - ia: 0.8470 - loss: 0.1076 - mae: 0.2206 - rmse: 0.3228 - smape: 0.5182 - val_ia: 0.8381 - val_loss: 0.0682 - val_mae: 0.1583 - val_rmse: 0.2399 - val_smape: 0.4098

Epoch 10/128

240/240 - 5s - 19ms/step - ia: 0.8532 - loss: 0.1010 - mae: 0.2121 - rmse: 0.3129 - smape: 0.5045 - val_ia: 0.8448 - val_loss: 0.0655 - val_mae: 0.1528 - val_rmse: 0.2350 - val_smape: 0.3986

Epoch 11/128

240/240 - 4s - 18ms/step - ia: 0.8571 - loss: 0.0970 - mae: 0.2062 - rmse: 0.3057 - smape: 0.4917 - val_ia: 0.8477 - val_loss: 0.0638 - val_mae: 0.1504 - val_rmse: 0.2314 - val_smape: 0.3947

Epoch 12/128

240/240 - 5s - 19ms/step - ia: 0.8606 - loss: 0.0936 - mae: 0.2010 - rmse: 0.3002 - smape: 0.4837 - val_ia: 0.8535 - val_loss: 0.0624 - val_mae: 0.1466 - val_rmse: 0.2284 - val_smape: 0.3881

Epoch 13/128

240/240 - 5s - 19ms/step - ia: 0.8643 - loss: 0.0902 - mae: 0.1966 - rmse: 0.2944 - smape: 0.4760 - val_ia: 0.8551 - val_loss: 0.0613 - val_mae: 0.1453 - val_rmse: 0.2263 - val_smape: 0.3843

Epoch 14/128

240/240 - 5s - 19ms/step - ia: 0.8685 - loss: 0.0862 - mae: 0.1901 - rmse: 0.2875 - smape: 0.4634 - val_ia: 0.8582 - val_loss: 0.0597 - val_mae: 0.1418 - val_rmse: 0.2234 - val_smape: 0.3767

Epoch 15/128

240/240 - 5s - 19ms/step - ia: 0.8706 - loss: 0.0855 - mae: 0.1874 - rmse: 0.2857 - smape: 0.4559 - val_ia: 0.8604 - val_loss: 0.0588 - val_mae: 0.1399 - val_rmse: 0.2218 - val_smape: 0.3719

Epoch 16/128

240/240 - 4s - 19ms/step - ia: 0.8740 - loss: 0.0823 - mae: 0.1829 - rmse: 0.2804 - smape: 0.4439 - val_ia: 0.8569 - val_loss: 0.0586 - val_mae: 0.1418 - val_rmse: 0.2223 - val_smape: 0.3750

Epoch 17/128

240/240 - 5s - 20ms/step - ia: 0.8762 - loss: 0.0802 - mae: 0.1798 - rmse: 0.2764 - smape: 0.4398 - val_ia: 0.8669 - val_loss: 0.0575 - val_mae: 0.1353 - val_rmse: 0.2185 - val_smape: 0.3651

Epoch 18/128

240/240 - 4s - 18ms/step - ia: 0.8780 - loss: 0.0788 - mae: 0.1771 - rmse: 0.2740 - smape: 0.4320 - val_ia: 0.8571 - val_loss: 0.0580 - val_mae: 0.1416 - val_rmse: 0.2207 - val_smape: 0.3721

Epoch 19/128

240/240 - 4s - 17ms/step - ia: 0.8796 - loss: 0.0776 - mae: 0.1746 - rmse: 0.2723 - smape: 0.4293 - val_ia: 0.8672 - val_loss: 0.0570 - val_mae: 0.1343 - val_rmse: 0.2179 - val_smape: 0.3612

Epoch 20/128

240/240 - 5s - 19ms/step - ia: 0.8813 - loss: 0.0777 - mae: 0.1730 - rmse: 0.2715 - smape: 0.4237 - val_ia: 0.8675 - val_loss: 0.0568 - val_mae: 0.1348 - val_rmse: 0.2170 - val_smape: 0.3613

Epoch 21/128

240/240 - 4s - 15ms/step - ia: 0.8818 - loss: 0.0765 - mae: 0.1720 - rmse: 0.2698 - smape: 0.4235 - val_ia: 0.8677 - val_loss: 0.0568 - val_mae: 0.1350 - val_rmse: 0.2166 - val_smape: 0.3614

Epoch 22/128

240/240 - 5s - 21ms/step - ia: 0.8831 - loss: 0.0749 - mae: 0.1701 - rmse: 0.2673 - smape: 0.4175 - val_ia: 0.8688 - val_loss: 0.0563 - val_mae: 0.1337 - val_rmse: 0.2158 - val_smape: 0.3585

Epoch 23/128

240/240 - 5s - 20ms/step - ia: 0.8848 - loss: 0.0737 - mae: 0.1678 - rmse: 0.2644 - smape: 0.4113 - val_ia: 0.8696 - val_loss: 0.0559 - val_mae: 0.1325 - val_rmse: 0.2149 - val_smape: 0.3576

Epoch 24/128

240/240 - 4s - 17ms/step - ia: 0.8861 - loss: 0.0733 - mae: 0.1658 - rmse: 0.2643 - smape: 0.4088 - val_ia: 0.8646 - val_loss: 0.0565 - val_mae: 0.1362 - val_rmse: 0.2167 - val_smape: 0.3624

Epoch 25/128

240/240 - 4s - 16ms/step - ia: 0.8862 - loss: 0.0731 - mae: 0.1657 - rmse: 0.2637 - smape: 0.4092 - val_ia: 0.8690 - val_loss: 0.0559 - val_mae: 0.1331 - val_rmse: 0.2149 - val_smape: 0.3572

Epoch 26/128

240/240 - 4s - 17ms/step - ia: 0.8866 - loss: 0.0726 - mae: 0.1650 - rmse: 0.2622 - smape: 0.4080 - val_ia: 0.8670 - val_loss: 0.0560 - val_mae: 0.1346 - val_rmse: 0.2149 - val_smape: 0.3590

Epoch 27/128

240/240 - 4s - 17ms/step - ia: 0.8883 - loss: 0.0719 - mae: 0.1626 - rmse: 0.2611 - smape: 0.4025 - val_ia: 0.8678 - val_loss: 0.0568 - val_mae: 0.1347 - val_rmse: 0.2162 - val_smape: 0.3591

Epoch 28/128

240/240 - 4s - 17ms/step - ia: 0.8881 - loss: 0.0714 - mae: 0.1628 - rmse: 0.2600 - smape: 0.4024 - val_ia: 0.8703 - val_loss: 0.0553 - val_mae: 0.1318 - val_rmse: 0.2138 - val_smape: 0.3549

Epoch 29/128

240/240 - 5s - 21ms/step - ia: 0.8892 - loss: 0.0713 - mae: 0.1615 - rmse: 0.2597 - smape: 0.3985 - val_ia: 0.8681 - val_loss: 0.0555 - val_mae: 0.1336 - val_rmse: 0.2140 - val_smape: 0.3574

Epoch 30/128

240/240 - 5s - 21ms/step - ia: 0.8893 - loss: 0.0709 - mae: 0.1610 - rmse: 0.2585 - smape: 0.3950 - val_ia: 0.8730 - val_loss: 0.0557 - val_mae: 0.1310 - val_rmse: 0.2136 - val_smape: 0.3519

Epoch 31/128

240/240 - 4s - 17ms/step - ia: 0.8902 - loss: 0.0702 - mae: 0.1601 - rmse: 0.2579 - smape: 0.3958 - val_ia: 0.8675 - val_loss: 0.0553 - val_mae: 0.1334 - val_rmse: 0.2139 - val_smape: 0.3565

Epoch 32/128

240/240 - 4s - 16ms/step - ia: 0.8899 - loss: 0.0702 - mae: 0.1603 - rmse: 0.2578 - smape: 0.3959 - val_ia: 0.8733 - val_loss: 0.0551 - val_mae: 0.1300 - val_rmse: 0.2125 - val_smape: 0.3515

Epoch 33/128

240/240 - 5s - 22ms/step - ia: 0.8902 - loss: 0.0707 - mae: 0.1601 - rmse: 0.2585 - smape: 0.3945 - val_ia: 0.8681 - val_loss: 0.0551 - val_mae: 0.1331 - val_rmse: 0.2136 - val_smape: 0.3556

Epoch 34/128

240/240 - 4s - 16ms/step - ia: 0.8897 - loss: 0.0715 - mae: 0.1606 - rmse: 0.2596 - smape: 0.3946 - val_ia: 0.8762 - val_loss: 0.0545 - val_mae: 0.1277 - val_rmse: 0.2116 - val_smape: 0.3476

Epoch 35/128

240/240 - 4s - 17ms/step - ia: 0.8911 - loss: 0.0695 - mae: 0.1586 - rmse: 0.2568 - smape: 0.3914 - val_ia: 0.8738 - val_loss: 0.0549 - val_mae: 0.1297 - val_rmse: 0.2120 - val_smape: 0.3498

Epoch 36/128

240/240 - 4s - 17ms/step - ia: 0.8915 - loss: 0.0693 - mae: 0.1583 - rmse: 0.2555 - smape: 0.3907 - val_ia: 0.8748 - val_loss: 0.0546 - val_mae: 0.1281 - val_rmse: 0.2124 - val_smape: 0.3481

Epoch 37/128

240/240 - 4s - 17ms/step - ia: 0.8917 - loss: 0.0694 - mae: 0.1581 - rmse: 0.2561 - smape: 0.3903 - val_ia: 0.8689 - val_loss: 0.0545 - val_mae: 0.1319 - val_rmse: 0.2122 - val_smape: 0.3538

Epoch 38/128

240/240 - 5s - 21ms/step - ia: 0.8913 - loss: 0.0694 - mae: 0.1582 - rmse: 0.2566 - smape: 0.3904 - val_ia: 0.8678 - val_loss: 0.0552 - val_mae: 0.1338 - val_rmse: 0.2137 - val_smape: 0.3562

Epoch 39/128

240/240 - 4s - 17ms/step - ia: 0.8919 - loss: 0.0687 - mae: 0.1575 - rmse: 0.2551 - smape: 0.3880 - val_ia: 0.8620 - val_loss: 0.0559 - val_mae: 0.1379 - val_rmse: 0.2165 - val_smape: 0.3681

Epoch 40/128

240/240 - 5s - 21ms/step - ia: 0.8921 - loss: 0.0690 - mae: 0.1573 - rmse: 0.2551 - smape: 0.3885 - val_ia: 0.8621 - val_loss: 0.0559 - val_mae: 0.1373 - val_rmse: 0.2162 - val_smape: 0.3652

Epoch 41/128

240/240 - 5s - 21ms/step - ia: 0.8932 - loss: 0.0679 - mae: 0.1556 - rmse: 0.2535 - smape: 0.3861 - val_ia: 0.8758 - val_loss: 0.0540 - val_mae: 0.1278 - val_rmse: 0.2109 - val_smape: 0.3460

Epoch 42/128

240/240 - 5s - 22ms/step - ia: 0.8924 - loss: 0.0683 - mae: 0.1565 - rmse: 0.2548 - smape: 0.3867 - val_ia: 0.8669 - val_loss: 0.0549 - val_mae: 0.1334 - val_rmse: 0.2142 - val_smape: 0.3604

Epoch 43/128

240/240 - 4s - 17ms/step - ia: 0.8930 - loss: 0.0681 - mae: 0.1562 - rmse: 0.2543 - smape: 0.3876 - val_ia: 0.8750 - val_loss: 0.0538 - val_mae: 0.1278 - val_rmse: 0.2104 - val_smape: 0.3471

Epoch 44/128

240/240 - 4s - 16ms/step - ia: 0.8938 - loss: 0.0685 - mae: 0.1553 - rmse: 0.2546 - smape: 0.3842 - val_ia: 0.8707 - val_loss: 0.0548 - val_mae: 0.1318 - val_rmse: 0.2124 - val_smape: 0.3517

Epoch 45/128

240/240 - 5s - 21ms/step - ia: 0.8939 - loss: 0.0673 - mae: 0.1547 - rmse: 0.2531 - smape: 0.3838 - val_ia: 0.8757 - val_loss: 0.0543 - val_mae: 0.1287 - val_rmse: 0.2109 - val_smape: 0.3461

Epoch 46/128

240/240 - 4s - 18ms/step - ia: 0.8932 - loss: 0.0680 - mae: 0.1559 - rmse: 0.2537 - smape: 0.3863 - val_ia: 0.8735 - val_loss: 0.0537 - val_mae: 0.1291 - val_rmse: 0.2103 - val_smape: 0.3481

Epoch 47/128

240/240 - 4s - 18ms/step - ia: 0.8937 - loss: 0.0671 - mae: 0.1550 - rmse: 0.2515 - smape: 0.3842 - val_ia: 0.8720 - val_loss: 0.0546 - val_mae: 0.1314 - val_rmse: 0.2118 - val_smape: 0.3500

Epoch 48/128

240/240 - 4s - 17ms/step - ia: 0.8933 - loss: 0.0680 - mae: 0.1556 - rmse: 0.2538 - smape: 0.3830 - val_ia: 0.8707 - val_loss: 0.0544 - val_mae: 0.1314 - val_rmse: 0.2116 - val_smape: 0.3510

Epoch 49/128

240/240 - 4s - 16ms/step - ia: 0.8942 - loss: 0.0669 - mae: 0.1543 - rmse: 0.2523 - smape: 0.3822 - val_ia: 0.8744 - val_loss: 0.0540 - val_mae: 0.1287 - val_rmse: 0.2106 - val_smape: 0.3472

Epoch 50/128

240/240 - 4s - 18ms/step - ia: 0.8937 - loss: 0.0680 - mae: 0.1554 - rmse: 0.2526 - smape: 0.3850 - val_ia: 0.8737 - val_loss: 0.0538 - val_mae: 0.1289 - val_rmse: 0.2103 - val_smape: 0.3476

Epoch 51/128

240/240 - 5s - 20ms/step - ia: 0.8951 - loss: 0.0668 - mae: 0.1530 - rmse: 0.2512 - smape: 0.3791 - val_ia: 0.8731 - val_loss: 0.0547 - val_mae: 0.1308 - val_rmse: 0.2117 - val_smape: 0.3488

Epoch 52/128

240/240 - 4s - 17ms/step - ia: 0.8944 - loss: 0.0672 - mae: 0.1543 - rmse: 0.2522 - smape: 0.3812 - val_ia: 0.8768 - val_loss: 0.0533 - val_mae: 0.1268 - val_rmse: 0.2094 - val_smape: 0.3439

Epoch 53/128

240/240 - 4s - 17ms/step - ia: 0.8950 - loss: 0.0669 - mae: 0.1534 - rmse: 0.2513 - smape: 0.3814 - val_ia: 0.8743 - val_loss: 0.0534 - val_mae: 0.1281 - val_rmse: 0.2101 - val_smape: 0.3475

Epoch 54/128

240/240 - 5s - 20ms/step - ia: 0.8944 - loss: 0.0672 - mae: 0.1542 - rmse: 0.2531 - smape: 0.3820 - val_ia: 0.8732 - val_loss: 0.0536 - val_mae: 0.1292 - val_rmse: 0.2100 - val_smape: 0.3475

Epoch 55/128

240/240 - 4s - 16ms/step - ia: 0.8944 - loss: 0.0667 - mae: 0.1540 - rmse: 0.2515 - smape: 0.3829 - val_ia: 0.8758 - val_loss: 0.0533 - val_mae: 0.1275 - val_rmse: 0.2099 - val_smape: 0.3461

Epoch 56/128

240/240 - 4s - 16ms/step - ia: 0.8950 - loss: 0.0668 - mae: 0.1532 - rmse: 0.2512 - smape: 0.3798 - val_ia: 0.8704 - val_loss: 0.0538 - val_mae: 0.1313 - val_rmse: 0.2112 - val_smape: 0.3518

Epoch 57/128

240/240 - 4s - 16ms/step - ia: 0.8948 - loss: 0.0673 - mae: 0.1536 - rmse: 0.2520 - smape: 0.3802 - val_ia: 0.8678 - val_loss: 0.0540 - val_mae: 0.1325 - val_rmse: 0.2123 - val_smape: 0.3555

Epoch 58/128

240/240 - 4s - 16ms/step - ia: 0.8943 - loss: 0.0671 - mae: 0.1543 - rmse: 0.2527 - smape: 0.3838 - val_ia: 0.8733 - val_loss: 0.0538 - val_mae: 0.1295 - val_rmse: 0.2108 - val_smape: 0.3483

Epoch 59/128

240/240 - 5s - 22ms/step - ia: 0.8952 - loss: 0.0661 - mae: 0.1534 - rmse: 0.2499 - smape: 0.3815 - val_ia: 0.8730 - val_loss: 0.0538 - val_mae: 0.1299 - val_rmse: 0.2104 - val_smape: 0.3478

Epoch 60/128

240/240 - 5s - 21ms/step - ia: 0.8951 - loss: 0.0663 - mae: 0.1531 - rmse: 0.2506 - smape: 0.3817 - val_ia: 0.8701 - val_loss: 0.0544 - val_mae: 0.1325 - val_rmse: 0.2118 - val_smape: 0.3515

Epoch 61/128

240/240 - 5s - 22ms/step - ia: 0.8952 - loss: 0.0664 - mae: 0.1532 - rmse: 0.2508 - smape: 0.3806 - val_ia: 0.8740 - val_loss: 0.0536 - val_mae: 0.1292 - val_rmse: 0.2101 - val_smape: 0.3475

Epoch 62/128

240/240 - 4s - 16ms/step - ia: 0.8949 - loss: 0.0665 - mae: 0.1533 - rmse: 0.2510 - smape: 0.3811 - val_ia: 0.8776 - val_loss: 0.0530 - val_mae: 0.1265 - val_rmse: 0.2089 - val_smape: 0.3429

Epoch 63/128

240/240 - 5s - 22ms/step - ia: 0.8953 - loss: 0.0658 - mae: 0.1527 - rmse: 0.2508 - smape: 0.3794 - val_ia: 0.8676 - val_loss: 0.0540 - val_mae: 0.1333 - val_rmse: 0.2125 - val_smape: 0.3576

Epoch 64/128

240/240 - 4s - 17ms/step - ia: 0.8957 - loss: 0.0655 - mae: 0.1526 - rmse: 0.2491 - smape: 0.3795 - val_ia: 0.8732 - val_loss: 0.0541 - val_mae: 0.1302 - val_rmse: 0.2107 - val_smape: 0.3483

Epoch 65/128

240/240 - 4s - 16ms/step - ia: 0.8956 - loss: 0.0656 - mae: 0.1525 - rmse: 0.2493 - smape: 0.3795 - val_ia: 0.8705 - val_loss: 0.0535 - val_mae: 0.1313 - val_rmse: 0.2105 - val_smape: 0.3514

Epoch 66/128

240/240 - 4s - 17ms/step - ia: 0.8956 - loss: 0.0657 - mae: 0.1524 - rmse: 0.2493 - smape: 0.3809 - val_ia: 0.8741 - val_loss: 0.0538 - val_mae: 0.1297 - val_rmse: 0.2102 - val_smape: 0.3470

Epoch 67/128

240/240 - 4s - 17ms/step - ia: 0.8953 - loss: 0.0658 - mae: 0.1527 - rmse: 0.2497 - smape: 0.3803 - val_ia: 0.8765 - val_loss: 0.0530 - val_mae: 0.1274 - val_rmse: 0.2093 - val_smape: 0.3454

Epoch 68/128

240/240 - 5s - 21ms/step - ia: 0.8963 - loss: 0.0653 - mae: 0.1514 - rmse: 0.2477 - smape: 0.3777 - val_ia: 0.8762 - val_loss: 0.0528 - val_mae: 0.1273 - val_rmse: 0.2086 - val_smape: 0.3443

Epoch 69/128

240/240 - 4s - 16ms/step - ia: 0.8962 - loss: 0.0652 - mae: 0.1516 - rmse: 0.2479 - smape: 0.3775 - val_ia: 0.8752 - val_loss: 0.0526 - val_mae: 0.1276 - val_rmse: 0.2085 - val_smape: 0.3459

Epoch 70/128

240/240 - 4s - 16ms/step - ia: 0.8953 - loss: 0.0655 - mae: 0.1527 - rmse: 0.2494 - smape: 0.3796 - val_ia: 0.8740 - val_loss: 0.0530 - val_mae: 0.1287 - val_rmse: 0.2091 - val_smape: 0.3465

Epoch 71/128

240/240 - 5s - 21ms/step - ia: 0.8960 - loss: 0.0656 - mae: 0.1519 - rmse: 0.2493 - smape: 0.3782 - val_ia: 0.8731 - val_loss: 0.0528 - val_mae: 0.1291 - val_rmse: 0.2091 - val_smape: 0.3481

Epoch 72/128

240/240 - 4s - 17ms/step - ia: 0.8960 - loss: 0.0656 - mae: 0.1518 - rmse: 0.2494 - smape: 0.3776 - val_ia: 0.8775 - val_loss: 0.0527 - val_mae: 0.1266 - val_rmse: 0.2085 - val_smape: 0.3433

Epoch 73/128

240/240 - 5s - 21ms/step - ia: 0.8960 - loss: 0.0655 - mae: 0.1518 - rmse: 0.2494 - smape: 0.3777 - val_ia: 0.8745 - val_loss: 0.0528 - val_mae: 0.1281 - val_rmse: 0.2086 - val_smape: 0.3461

Epoch 74/128

240/240 - 4s - 16ms/step - ia: 0.8961 - loss: 0.0655 - mae: 0.1518 - rmse: 0.2493 - smape: 0.3769 - val_ia: 0.8724 - val_loss: 0.0532 - val_mae: 0.1304 - val_rmse: 0.2098 - val_smape: 0.3496

Epoch 75/128

240/240 - 4s - 16ms/step - ia: 0.8963 - loss: 0.0652 - mae: 0.1514 - rmse: 0.2486 - smape: 0.3755 - val_ia: 0.8670 - val_loss: 0.0532 - val_mae: 0.1333 - val_rmse: 0.2108 - val_smape: 0.3554

Epoch 76/128

240/240 - 4s - 16ms/step - ia: 0.8966 - loss: 0.0642 - mae: 0.1509 - rmse: 0.2469 - smape: 0.3777 - val_ia: 0.8728 - val_loss: 0.0539 - val_mae: 0.1309 - val_rmse: 0.2105 - val_smape: 0.3485

Epoch 77/128

240/240 - 4s - 16ms/step - ia: 0.8964 - loss: 0.0645 - mae: 0.1510 - rmse: 0.2478 - smape: 0.3762 - val_ia: 0.8709 - val_loss: 0.0534 - val_mae: 0.1311 - val_rmse: 0.2103 - val_smape: 0.3506

Epoch 78/128

240/240 - 4s - 17ms/step - ia: 0.8965 - loss: 0.0651 - mae: 0.1511 - rmse: 0.2479 - smape: 0.3753 - val_ia: 0.8735 - val_loss: 0.0537 - val_mae: 0.1301 - val_rmse: 0.2104 - val_smape: 0.3476

Epoch 79/128

240/240 - 5s - 20ms/step - ia: 0.8969 - loss: 0.0648 - mae: 0.1506 - rmse: 0.2475 - smape: 0.3766 - val_ia: 0.8760 - val_loss: 0.0523 - val_mae: 0.1273 - val_rmse: 0.2078 - val_smape: 0.3454

Epoch 80/128

240/240 - 4s - 16ms/step - ia: 0.8967 - loss: 0.0646 - mae: 0.1510 - rmse: 0.2473 - smape: 0.3766 - val_ia: 0.8707 - val_loss: 0.0527 - val_mae: 0.1305 - val_rmse: 0.2094 - val_smape: 0.3510

Epoch 81/128

240/240 - 4s - 17ms/step - ia: 0.8969 - loss: 0.0640 - mae: 0.1506 - rmse: 0.2459 - smape: 0.3754 - val_ia: 0.8762 - val_loss: 0.0524 - val_mae: 0.1274 - val_rmse: 0.2081 - val_smape: 0.3453

Epoch 82/128

240/240 - 4s - 18ms/step - ia: 0.8973 - loss: 0.0640 - mae: 0.1502 - rmse: 0.2459 - smape: 0.3756 - val_ia: 0.8730 - val_loss: 0.0524 - val_mae: 0.1289 - val_rmse: 0.2086 - val_smape: 0.3485

Epoch 83/128

240/240 - 4s - 16ms/step - ia: 0.8964 - loss: 0.0652 - mae: 0.1514 - rmse: 0.2484 - smape: 0.3758 - val_ia: 0.8738 - val_loss: 0.0531 - val_mae: 0.1294 - val_rmse: 0.2093 - val_smape: 0.3468

Epoch 84/128

240/240 - 4s - 15ms/step - ia: 0.8969 - loss: 0.0645 - mae: 0.1507 - rmse: 0.2470 - smape: 0.3765 - val_ia: 0.8753 - val_loss: 0.0524 - val_mae: 0.1278 - val_rmse: 0.2088 - val_smape: 0.3485

Epoch 85/128

240/240 - 3s - 14ms/step - ia: 0.8970 - loss: 0.0641 - mae: 0.1506 - rmse: 0.2471 - smape: 0.3742 - val_ia: 0.8773 - val_loss: 0.0526 - val_mae: 0.1272 - val_rmse: 0.2083 - val_smape: 0.3440

Epoch 86/128

240/240 - 6s - 24ms/step - ia: 0.8969 - loss: 0.0645 - mae: 0.1504 - rmse: 0.2474 - smape: 0.3765 - val_ia: 0.8754 - val_loss: 0.0527 - val_mae: 0.1284 - val_rmse: 0.2086 - val_smape: 0.3456

Epoch 87/128

240/240 - 4s - 16ms/step - ia: 0.8969 - loss: 0.0639 - mae: 0.1506 - rmse: 0.2464 - smape: 0.3767 - val_ia: 0.8747 - val_loss: 0.0529 - val_mae: 0.1288 - val_rmse: 0.2089 - val_smape: 0.3461

Epoch 88/128

240/240 - 5s - 22ms/step - ia: 0.8970 - loss: 0.0635 - mae: 0.1503 - rmse: 0.2463 - smape: 0.3752 - val_ia: 0.8771 - val_loss: 0.0525 - val_mae: 0.1271 - val_rmse: 0.2088 - val_smape: 0.3458

Epoch 89/128

240/240 - 4s - 16ms/step - ia: 0.8971 - loss: 0.0643 - mae: 0.1501 - rmse: 0.2470 - smape: 0.3750 - val_ia: 0.8594 - val_loss: 0.0546 - val_mae: 0.1395 - val_rmse: 0.2149 - val_smape: 0.3691

Epoch 90/128

240/240 - 5s - 21ms/step - ia: 0.8971 - loss: 0.0646 - mae: 0.1504 - rmse: 0.2469 - smape: 0.3754 - val_ia: 0.8779 - val_loss: 0.0522 - val_mae: 0.1264 - val_rmse: 0.2079 - val_smape: 0.3433

Epoch 91/128

240/240 - 4s - 17ms/step - ia: 0.8967 - loss: 0.0651 - mae: 0.1509 - rmse: 0.2482 - smape: 0.3758 - val_ia: 0.8770 - val_loss: 0.0520 - val_mae: 0.1264 - val_rmse: 0.2075 - val_smape: 0.3435

Epoch 92/128

240/240 - 4s - 16ms/step - ia: 0.8977 - loss: 0.0641 - mae: 0.1495 - rmse: 0.2462 - smape: 0.3719 - val_ia: 0.8769 - val_loss: 0.0525 - val_mae: 0.1271 - val_rmse: 0.2091 - val_smape: 0.3463

Epoch 93/128

240/240 - 4s - 16ms/step - ia: 0.8977 - loss: 0.0637 - mae: 0.1496 - rmse: 0.2459 - smape: 0.3735 - val_ia: 0.8756 - val_loss: 0.0525 - val_mae: 0.1281 - val_rmse: 0.2081 - val_smape: 0.3459

Epoch 94/128

240/240 - 4s - 17ms/step - ia: 0.8977 - loss: 0.0637 - mae: 0.1498 - rmse: 0.2461 - smape: 0.3746 - val_ia: 0.8773 - val_loss: 0.0521 - val_mae: 0.1266 - val_rmse: 0.2076 - val_smape: 0.3434

Epoch 95/128

240/240 - 4s - 16ms/step - ia: 0.8971 - loss: 0.0642 - mae: 0.1502 - rmse: 0.2465 - smape: 0.3736 - val_ia: 0.8718 - val_loss: 0.0525 - val_mae: 0.1299 - val_rmse: 0.2093 - val_smape: 0.3509

Epoch 96/128

240/240 - 4s - 16ms/step - ia: 0.8979 - loss: 0.0635 - mae: 0.1494 - rmse: 0.2448 - smape: 0.3747 - val_ia: 0.8729 - val_loss: 0.0524 - val_mae: 0.1296 - val_rmse: 0.2085 - val_smape: 0.3494

Epoch 97/128

240/240 - 4s - 17ms/step - ia: 0.8975 - loss: 0.0635 - mae: 0.1498 - rmse: 0.2445 - smape: 0.3759 - val_ia: 0.8681 - val_loss: 0.0548 - val_mae: 0.1349 - val_rmse: 0.2123 - val_smape: 0.3549

Epoch 98/128


In [23]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}