Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [4]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [5]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [6]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [7]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [8]:
datosNormalizados.shape

(52416, 5)

In [9]:
datosNormalizados.head(13)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823

Espacio de búsqueda

In [10]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [11]:
futuros = 1
pasados  = 12

In [12]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [13]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [14]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [15]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 12, 5)
Las dimensiones de testX son:  (10533, 12, 5)
Las dimensiones de valX son:  (5189, 12, 5)

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [17]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [18]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [19]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [20]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 16s - 57ms/step - ia: 0.3144 - loss: 2.2542 - mae: 1.2336 - rmse: 1.4856 - smape: 1.4094 - val_ia: 0.2939 - val_loss: 1.2548 - val_mae: 0.9354 - val_rmse: 1.0983 - val_smape: 1.4434

Epoch 2/128

287/287 - 9s - 31ms/step - ia: 0.2528 - loss: 1.2654 - mae: 0.9270 - rmse: 1.1229 - smape: 1.5021 - val_ia: 0.2124 - val_loss: 0.8966 - val_mae: 0.7884 - val_rmse: 0.9384 - val_smape: 1.7010

Epoch 3/128

287/287 - 5s - 18ms/step - ia: 0.2284 - loss: 1.1448 - mae: 0.8848 - rmse: 1.0687 - smape: 1.5332 - val_ia: 0.2177 - val_loss: 0.8551 - val_mae: 0.7695 - val_rmse: 0.9182 - val_smape: 1.9006

Epoch 4/128

287/287 - 5s - 17ms/step - ia: 0.2210 - loss: 1.0774 - mae: 0.8591 - rmse: 1.0363 - smape: 1.5438 - val_ia: 0.2319 - val_loss: 0.8236 - val_mae: 0.7545 - val_rmse: 0.9012 - val_smape: 1.8427

Epoch 5/128

287/287 - 5s - 18ms/step - ia: 0.2285 - loss: 1.0048 - mae: 0.8290 - rmse: 1.0008 - smape: 1.5293 - val_ia: 0.2712 - val_loss: 0.7595 - val_mae: 0.7230 - val_rmse: 0.8649 - val_smape: 1.6208

Epoch 6/128

287/287 - 5s - 18ms/step - ia: 0.2892 - loss: 0.8857 - mae: 0.7762 - rmse: 0.9398 - smape: 1.4349 - val_ia: 0.3696 - val_loss: 0.6453 - val_mae: 0.6645 - val_rmse: 0.7949 - val_smape: 1.3049

Epoch 7/128

287/287 - 5s - 17ms/step - ia: 0.4005 - loss: 0.7325 - mae: 0.7023 - rmse: 0.8538 - smape: 1.2629 - val_ia: 0.4790 - val_loss: 0.5189 - val_mae: 0.5959 - val_rmse: 0.7108 - val_smape: 1.0702

Epoch 8/128

287/287 - 5s - 17ms/step - ia: 0.5024 - loss: 0.6106 - mae: 0.6398 - rmse: 0.7797 - smape: 1.1065 - val_ia: 0.5585 - val_loss: 0.4398 - val_mae: 0.5468 - val_rmse: 0.6526 - val_smape: 0.9374

Epoch 9/128

287/287 - 6s - 19ms/step - ia: 0.5700 - loss: 0.5311 - mae: 0.5938 - rmse: 0.7276 - smape: 0.9998 - val_ia: 0.6059 - val_loss: 0.4060 - val_mae: 0.5202 - val_rmse: 0.6254 - val_smape: 0.8731

Epoch 10/128

287/287 - 5s - 17ms/step - ia: 0.6060 - loss: 0.4837 - mae: 0.5636 - rmse: 0.6943 - smape: 0.9450 - val_ia: 0.6344 - val_loss: 0.3812 - val_mae: 0.4970 - val_rmse: 0.6052 - val_smape: 0.8366

Epoch 11/128

287/287 - 5s - 18ms/step - ia: 0.6318 - loss: 0.4451 - mae: 0.5352 - rmse: 0.6659 - smape: 0.9013 - val_ia: 0.6454 - val_loss: 0.3707 - val_mae: 0.4893 - val_rmse: 0.5954 - val_smape: 0.8270

Epoch 12/128

287/287 - 5s - 17ms/step - ia: 0.6523 - loss: 0.4112 - mae: 0.5113 - rmse: 0.6398 - smape: 0.8726 - val_ia: 0.6550 - val_loss: 0.3503 - val_mae: 0.4772 - val_rmse: 0.5783 - val_smape: 0.8187

Epoch 13/128

287/287 - 5s - 16ms/step - ia: 0.6734 - loss: 0.3736 - mae: 0.4849 - rmse: 0.6099 - smape: 0.8412 - val_ia: 0.6640 - val_loss: 0.3214 - val_mae: 0.4615 - val_rmse: 0.5537 - val_smape: 0.8158

Epoch 14/128

287/287 - 5s - 16ms/step - ia: 0.6903 - loss: 0.3443 - mae: 0.4632 - rmse: 0.5856 - smape: 0.8226 - val_ia: 0.6684 - val_loss: 0.2980 - val_mae: 0.4518 - val_rmse: 0.5322 - val_smape: 0.8235

Epoch 15/128

287/287 - 5s - 18ms/step - ia: 0.7068 - loss: 0.3165 - mae: 0.4418 - rmse: 0.5612 - smape: 0.7995 - val_ia: 0.6716 - val_loss: 0.2775 - val_mae: 0.4408 - val_rmse: 0.5127 - val_smape: 0.8347

Epoch 16/128

287/287 - 5s - 18ms/step - ia: 0.7175 - loss: 0.2999 - mae: 0.4276 - rmse: 0.5462 - smape: 0.7828 - val_ia: 0.6856 - val_loss: 0.2505 - val_mae: 0.4189 - val_rmse: 0.4864 - val_smape: 0.8229

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 0.7268 - loss: 0.2838 - mae: 0.4153 - rmse: 0.5315 - smape: 0.7743 - val_ia: 0.6961 - val_loss: 0.2316 - val_mae: 0.4024 - val_rmse: 0.4677 - val_smape: 0.8122

Epoch 18/128

287/287 - 5s - 18ms/step - ia: 0.7347 - loss: 0.2707 - mae: 0.4043 - rmse: 0.5190 - smape: 0.7619 - val_ia: 0.6996 - val_loss: 0.2248 - val_mae: 0.3975 - val_rmse: 0.4599 - val_smape: 0.8156

Epoch 19/128

287/287 - 5s - 17ms/step - ia: 0.7388 - loss: 0.2649 - mae: 0.3980 - rmse: 0.5135 - smape: 0.7563 - val_ia: 0.7116 - val_loss: 0.2072 - val_mae: 0.3761 - val_rmse: 0.4413 - val_smape: 0.7954

Epoch 20/128

287/287 - 5s - 17ms/step - ia: 0.7455 - loss: 0.2521 - mae: 0.3886 - rmse: 0.5008 - smape: 0.7433 - val_ia: 0.7217 - val_loss: 0.1950 - val_mae: 0.3641 - val_rmse: 0.4280 - val_smape: 0.7800

Epoch 21/128

287/287 - 5s - 18ms/step - ia: 0.7471 - loss: 0.2510 - mae: 0.3862 - rmse: 0.4998 - smape: 0.7447 - val_ia: 0.7272 - val_loss: 0.1877 - val_mae: 0.3549 - val_rmse: 0.4198 - val_smape: 0.7711

Epoch 22/128

287/287 - 5s - 18ms/step - ia: 0.7521 - loss: 0.2415 - mae: 0.3789 - rmse: 0.4902 - smape: 0.7364 - val_ia: 0.7321 - val_loss: 0.1824 - val_mae: 0.3488 - val_rmse: 0.4135 - val_smape: 0.7657

Epoch 23/128

287/287 - 5s - 17ms/step - ia: 0.7566 - loss: 0.2333 - mae: 0.3723 - rmse: 0.4815 - smape: 0.7296 - val_ia: 0.7409 - val_loss: 0.1727 - val_mae: 0.3352 - val_rmse: 0.4018 - val_smape: 0.7471

Epoch 24/128

287/287 - 5s - 17ms/step - ia: 0.7600 - loss: 0.2270 - mae: 0.3673 - rmse: 0.4751 - smape: 0.7210 - val_ia: 0.7444 - val_loss: 0.1695 - val_mae: 0.3314 - val_rmse: 0.3976 - val_smape: 0.7441

Epoch 25/128

287/287 - 5s - 17ms/step - ia: 0.7609 - loss: 0.2266 - mae: 0.3664 - rmse: 0.4746 - smape: 0.7208 - val_ia: 0.7528 - val_loss: 0.1607 - val_mae: 0.3209 - val_rmse: 0.3871 - val_smape: 0.7277

Epoch 26/128

287/287 - 5s - 18ms/step - ia: 0.7631 - loss: 0.2219 - mae: 0.3627 - rmse: 0.4696 - smape: 0.7178 - val_ia: 0.7525 - val_loss: 0.1619 - val_mae: 0.3212 - val_rmse: 0.3878 - val_smape: 0.7301

Epoch 27/128

287/287 - 5s - 17ms/step - ia: 0.7651 - loss: 0.2198 - mae: 0.3594 - rmse: 0.4673 - smape: 0.7110 - val_ia: 0.7550 - val_loss: 0.1598 - val_mae: 0.3197 - val_rmse: 0.3850 - val_smape: 0.7301

Epoch 28/128

287/287 - 5s - 16ms/step - ia: 0.7681 - loss: 0.2147 - mae: 0.3557 - rmse: 0.4622 - smape: 0.7053 - val_ia: 0.7627 - val_loss: 0.1517 - val_mae: 0.3071 - val_rmse: 0.3751 - val_smape: 0.7061

Epoch 29/128

287/287 - 5s - 16ms/step - ia: 0.7698 - loss: 0.2122 - mae: 0.3529 - rmse: 0.4593 - smape: 0.7019 - val_ia: 0.7585 - val_loss: 0.1571 - val_mae: 0.3155 - val_rmse: 0.3814 - val_smape: 0.7225

Epoch 30/128

287/287 - 6s - 19ms/step - ia: 0.7702 - loss: 0.2109 - mae: 0.3525 - rmse: 0.4579 - smape: 0.7010 - val_ia: 0.7628 - val_loss: 0.1529 - val_mae: 0.3103 - val_rmse: 0.3756 - val_smape: 0.7130

Epoch 31/128

287/287 - 5s - 18ms/step - ia: 0.7724 - loss: 0.2075 - mae: 0.3494 - rmse: 0.4541 - smape: 0.6983 - val_ia: 0.7677 - val_loss: 0.1480 - val_mae: 0.3041 - val_rmse: 0.3697 - val_smape: 0.7002

Epoch 32/128

287/287 - 5s - 16ms/step - ia: 0.7724 - loss: 0.2080 - mae: 0.3488 - rmse: 0.4547 - smape: 0.6952 - val_ia: 0.7651 - val_loss: 0.1523 - val_mae: 0.3070 - val_rmse: 0.3746 - val_smape: 0.7064

Epoch 33/128

287/287 - 5s - 18ms/step - ia: 0.7748 - loss: 0.2031 - mae: 0.3456 - rmse: 0.4492 - smape: 0.6922 - val_ia: 0.7672 - val_loss: 0.1507 - val_mae: 0.3043 - val_rmse: 0.3726 - val_smape: 0.7013

Epoch 34/128

287/287 - 5s - 19ms/step - ia: 0.7763 - loss: 0.2022 - mae: 0.3436 - rmse: 0.4483 - smape: 0.6883 - val_ia: 0.7723 - val_loss: 0.1451 - val_mae: 0.2984 - val_rmse: 0.3659 - val_smape: 0.6843

Epoch 35/128

287/287 - 5s - 17ms/step - ia: 0.7794 - loss: 0.1973 - mae: 0.3394 - rmse: 0.4430 - smape: 0.6801 - val_ia: 0.7695 - val_loss: 0.1493 - val_mae: 0.3029 - val_rmse: 0.3712 - val_smape: 0.6915

Epoch 36/128

287/287 - 5s - 16ms/step - ia: 0.7791 - loss: 0.1973 - mae: 0.3396 - rmse: 0.4428 - smape: 0.6817 - val_ia: 0.7671 - val_loss: 0.1528 - val_mae: 0.3039 - val_rmse: 0.3748 - val_smape: 0.6931

Epoch 37/128

287/287 - 5s - 17ms/step - ia: 0.7819 - loss: 0.1940 - mae: 0.3357 - rmse: 0.4391 - smape: 0.6725 - val_ia: 0.7633 - val_loss: 0.1586 - val_mae: 0.3109 - val_rmse: 0.3814 - val_smape: 0.7080

Epoch 38/128

287/287 - 5s - 17ms/step - ia: 0.7808 - loss: 0.1953 - mae: 0.3375 - rmse: 0.4406 - smape: 0.6737 - val_ia: 0.7697 - val_loss: 0.1523 - val_mae: 0.3042 - val_rmse: 0.3735 - val_smape: 0.6910

Epoch 39/128

287/287 - 5s - 18ms/step - ia: 0.7841 - loss: 0.1896 - mae: 0.3327 - rmse: 0.4339 - smape: 0.6669 - val_ia: 0.7643 - val_loss: 0.1587 - val_mae: 0.3084 - val_rmse: 0.3809 - val_smape: 0.6986

Epoch 40/128

287/287 - 5s - 17ms/step - ia: 0.7846 - loss: 0.1894 - mae: 0.3315 - rmse: 0.4337 - smape: 0.6660 - val_ia: 0.7675 - val_loss: 0.1566 - val_mae: 0.3053 - val_rmse: 0.3786 - val_smape: 0.6875

Epoch 41/128

287/287 - 5s - 17ms/step - ia: 0.7858 - loss: 0.1890 - mae: 0.3300 - rmse: 0.4333 - smape: 0.6578 - val_ia: 0.7644 - val_loss: 0.1617 - val_mae: 0.3079 - val_rmse: 0.3837 - val_smape: 0.6917

Epoch 42/128

287/287 - 5s - 17ms/step - ia: 0.7863 - loss: 0.1879 - mae: 0.3292 - rmse: 0.4319 - smape: 0.6569 - val_ia: 0.7679 - val_loss: 0.1573 - val_mae: 0.3032 - val_rmse: 0.3790 - val_smape: 0.6770

Epoch 43/128

287/287 - 5s - 19ms/step - ia: 0.7868 - loss: 0.1878 - mae: 0.3287 - rmse: 0.4320 - smape: 0.6534 - val_ia: 0.7638 - val_loss: 0.1632 - val_mae: 0.3092 - val_rmse: 0.3856 - val_smape: 0.6877

Epoch 44/128

287/287 - 5s - 18ms/step - ia: 0.7868 - loss: 0.1868 - mae: 0.3285 - rmse: 0.4309 - smape: 0.6530 - val_ia: 0.7629 - val_loss: 0.1661 - val_mae: 0.3099 - val_rmse: 0.3885 - val_smape: 0.6861

Epoch 45/128

287/287 - 5s - 18ms/step - ia: 0.7883 - loss: 0.1855 - mae: 0.3267 - rmse: 0.4292 - smape: 0.6500 - val_ia: 0.7667 - val_loss: 0.1603 - val_mae: 0.3030 - val_rmse: 0.3816 - val_smape: 0.6706

Epoch 46/128

287/287 - 5s - 18ms/step - ia: 0.7884 - loss: 0.1846 - mae: 0.3263 - rmse: 0.4283 - smape: 0.6484 - val_ia: 0.7666 - val_loss: 0.1618 - val_mae: 0.3048 - val_rmse: 0.3833 - val_smape: 0.6742

Epoch 47/128

287/287 - 5s - 17ms/step - ia: 0.7923 - loss: 0.1794 - mae: 0.3211 - rmse: 0.4222 - smape: 0.6378 - val_ia: 0.7697 - val_loss: 0.1554 - val_mae: 0.2974 - val_rmse: 0.3759 - val_smape: 0.6562

Epoch 48/128

287/287 - 5s - 18ms/step - ia: 0.7909 - loss: 0.1816 - mae: 0.3225 - rmse: 0.4249 - smape: 0.6407 - val_ia: 0.7691 - val_loss: 0.1596 - val_mae: 0.3009 - val_rmse: 0.3808 - val_smape: 0.6626

Epoch 49/128

287/287 - 5s - 17ms/step - ia: 0.7919 - loss: 0.1817 - mae: 0.3220 - rmse: 0.4249 - smape: 0.6384 - val_ia: 0.7711 - val_loss: 0.1557 - val_mae: 0.2951 - val_rmse: 0.3756 - val_smape: 0.6490

Epoch 49: early stopping

Restoring model weights from the end of the best epoch: 34.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:15 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

  8%|▊         | 1/12 [04:25<48:35, 265.09s/trial, best loss: 0.30908995341808326]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 63s - 27ms/step - ia: 0.9544 - loss: 0.0147 - mae: 0.0699 - rmse: 0.0929 - smape: 0.1998 - val_ia: 0.7910 - val_loss: 0.0044 - val_mae: 0.0516 - val_rmse: 0.0624 - val_smape: 0.1447

Epoch 2/128

2293/2293 - 50s - 22ms/step - ia: 0.9731 - loss: 0.0038 - mae: 0.0419 - rmse: 0.0559 - smape: 0.1408 - val_ia: 0.8090 - val_loss: 0.0033 - val_mae: 0.0434 - val_rmse: 0.0540 - val_smape: 0.1367

Epoch 3/128

2293/2293 - 83s - 36ms/step - ia: 0.9740 - loss: 0.0036 - mae: 0.0406 - rmse: 0.0544 - smape: 0.1381 - val_ia: 0.8186 - val_loss: 0.0033 - val_mae: 0.0422 - val_rmse: 0.0522 - val_smape: 0.1319

Epoch 4/128

2293/2293 - 51s - 22ms/step - ia: 0.9744 - loss: 0.0035 - mae: 0.0399 - rmse: 0.0536 - smape: 0.1358 - val_ia: 0.8245 - val_loss: 0.0033 - val_mae: 0.0423 - val_rmse: 0.0525 - val_smape: 0.1409

Epoch 5/128

2293/2293 - 79s - 34ms/step - ia: 0.9750 - loss: 0.0034 - mae: 0.0391 - rmse: 0.0525 - smape: 0.1329 - val_ia: 0.7805 - val_loss: 0.0050 - val_mae: 0.0545 - val_rmse: 0.0647 - val_smape: 0.1295

Epoch 6/128

2293/2293 - 91s - 40ms/step - ia: 0.9753 - loss: 0.0034 - mae: 0.0386 - rmse: 0.0522 - smape: 0.1326 - val_ia: 0.8383 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0481 - val_smape: 0.1277

Epoch 7/128

2293/2293 - 84s - 37ms/step - ia: 0.9757 - loss: 0.0033 - mae: 0.0379 - rmse: 0.0513 - smape: 0.1319 - val_ia: 0.8411 - val_loss: 0.0026 - val_mae: 0.0361 - val_rmse: 0.0462 - val_smape: 0.1167

Epoch 8/128

2293/2293 - 45s - 20ms/step - ia: 0.9759 - loss: 0.0032 - mae: 0.0377 - rmse: 0.0509 - smape: 0.1308 - val_ia: 0.8404 - val_loss: 0.0027 - val_mae: 0.0377 - val_rmse: 0.0480 - val_smape: 0.1106

Epoch 9/128

2293/2293 - 96s - 42ms/step - ia: 0.9763 - loss: 0.0032 - mae: 0.0371 - rmse: 0.0504 - smape: 0.1301 - val_ia: 0.8448 - val_loss: 0.0025 - val_mae: 0.0360 - val_rmse: 0.0461 - val_smape: 0.1136

Epoch 10/128

2293/2293 - 46s - 20ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0367 - rmse: 0.0498 - smape: 0.1296 - val_ia: 0.8143 - val_loss: 0.0033 - val_mae: 0.0431 - val_rmse: 0.0532 - val_smape: 0.1184

Epoch 11/128

2293/2293 - 52s - 23ms/step - ia: 0.9768 - loss: 0.0030 - mae: 0.0362 - rmse: 0.0490 - smape: 0.1282 - val_ia: 0.8590 - val_loss: 0.0024 - val_mae: 0.0340 - val_rmse: 0.0442 - val_smape: 0.1102

Epoch 12/128

2293/2293 - 86s - 38ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0361 - rmse: 0.0488 - smape: 0.1273 - val_ia: 0.8516 - val_loss: 0.0024 - val_mae: 0.0348 - val_rmse: 0.0446 - val_smape: 0.1111

Epoch 13/128

2293/2293 - 42s - 18ms/step - ia: 0.9772 - loss: 0.0029 - mae: 0.0355 - rmse: 0.0482 - smape: 0.1265 - val_ia: 0.8468 - val_loss: 0.0026 - val_mae: 0.0361 - val_rmse: 0.0461 - val_smape: 0.1164

Epoch 14/128

2293/2293 - 58s - 25ms/step - ia: 0.9773 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0478 - smape: 0.1256 - val_ia: 0.8459 - val_loss: 0.0025 - val_mae: 0.0354 - val_rmse: 0.0454 - val_smape: 0.1154

Epoch 15/128

2293/2293 - 81s - 35ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0475 - smape: 0.1264 - val_ia: 0.8272 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0506 - val_smape: 0.1230

Epoch 16/128

2293/2293 - 42s - 18ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0475 - smape: 0.1256 - val_ia: 0.8526 - val_loss: 0.0024 - val_mae: 0.0338 - val_rmse: 0.0438 - val_smape: 0.1104

Epoch 17/128

2293/2293 - 59s - 26ms/step - ia: 0.9779 - loss: 0.0028 - mae: 0.0345 - rmse: 0.0468 - smape: 0.1236 - val_ia: 0.8367 - val_loss: 0.0027 - val_mae: 0.0385 - val_rmse: 0.0482 - val_smape: 0.1188

Epoch 18/128

2293/2293 - 79s - 35ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0467 - smape: 0.1249 - val_ia: 0.8563 - val_loss: 0.0022 - val_mae: 0.0327 - val_rmse: 0.0426 - val_smape: 0.1083

Epoch 19/128

2293/2293 - 79s - 35ms/step - ia: 0.9780 - loss: 0.0027 - mae: 0.0341 - rmse: 0.0463 - smape: 0.1235 - val_ia: 0.8582 - val_loss: 0.0023 - val_mae: 0.0334 - val_rmse: 0.0433 - val_smape: 0.1082

Epoch 20/128

2293/2293 - 59s - 26ms/step - ia: 0.9781 - loss: 0.0027 - mae: 0.0341 - rmse: 0.0462 - smape: 0.1240 - val_ia: 0.8454 - val_loss: 0.0029 - val_mae: 0.0376 - val_rmse: 0.0481 - val_smape: 0.1226

Epoch 21/128

2293/2293 - 53s - 23ms/step - ia: 0.9783 - loss: 0.0027 - mae: 0.0339 - rmse: 0.0459 - smape: 0.1234 - val_ia: 0.8556 - val_loss: 0.0025 - val_mae: 0.0344 - val_rmse: 0.0447 - val_smape: 0.1117

Epoch 22/128

2293/2293 - 46s - 20ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0337 - rmse: 0.0458 - smape: 0.1231 - val_ia: 0.8527 - val_loss: 0.0024 - val_mae: 0.0346 - val_rmse: 0.0447 - val_smape: 0.1128

Epoch 23/128

2293/2293 - 58s - 25ms/step - ia: 0.9785 - loss: 0.0026 - mae: 0.0335 - rmse: 0.0455 - smape: 0.1221 - val_ia: 0.8217 - val_loss: 0.0035 - val_mae: 0.0432 - val_rmse: 0.0539 - val_smape: 0.1241

Epoch 24/128

2293/2293 - 43s - 19ms/step - ia: 0.9785 - loss: 0.0027 - mae: 0.0335 - rmse: 0.0455 - smape: 0.1222 - val_ia: 0.8526 - val_loss: 0.0026 - val_mae: 0.0358 - val_rmse: 0.0458 - val_smape: 0.1157

Epoch 25/128

2293/2293 - 55s - 24ms/step - ia: 0.9787 - loss: 0.0026 - mae: 0.0331 - rmse: 0.0450 - smape: 0.1217 - val_ia: 0.8597 - val_loss: 0.0025 - val_mae: 0.0343 - val_rmse: 0.0444 - val_smape: 0.1120

Epoch 26/128

2293/2293 - 58s - 25ms/step - ia: 0.9789 - loss: 0.0026 - mae: 0.0329 - rmse: 0.0447 - smape: 0.1209 - val_ia: 0.8422 - val_loss: 0.0031 - val_mae: 0.0396 - val_rmse: 0.0500 - val_smape: 0.1264

Epoch 27/128

2293/2293 - 58s - 25ms/step - ia: 0.9787 - loss: 0.0026 - mae: 0.0331 - rmse: 0.0448 - smape: 0.1208 - val_ia: 0.8499 - val_loss: 0.0025 - val_mae: 0.0351 - val_rmse: 0.0453 - val_smape: 0.1148

Epoch 28/128

2293/2293 - 51s - 22ms/step - ia: 0.9791 - loss: 0.0025 - mae: 0.0326 - rmse: 0.0444 - smape: 0.1201 - val_ia: 0.8442 - val_loss: 0.0033 - val_mae: 0.0394 - val_rmse: 0.0504 - val_smape: 0.1306

Epoch 29/128

2293/2293 - 47s - 20ms/step - ia: 0.9791 - loss: 0.0025 - mae: 0.0325 - rmse: 0.0443 - smape: 0.1200 - val_ia: 0.8461 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0475 - val_smape: 0.1197

Epoch 30/128

2293/2293 - 81s - 35ms/step - ia: 0.9792 - loss: 0.0025 - mae: 0.0324 - rmse: 0.0440 - smape: 0.1197 - val_ia: 0.8479 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0471 - val_smape: 0.1157

Epoch 31/128

2293/2293 - 86s - 37ms/step - ia: 0.9791 - loss: 0.0025 - mae: 0.0323 - rmse: 0.0440 - smape: 0.1199 - val_ia: 0.8397 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0482 - val_smape: 0.1155

Epoch 32/128

2293/2293 - 80s - 35ms/step - ia: 0.9791 - loss: 0.0025 - mae: 0.0325 - rmse: 0.0442 - smape: 0.1197 - val_ia: 0.8534 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0446 - val_smape: 0.1131

Epoch 33/128

2293/2293 - 39s - 17ms/step - ia: 0.9794 - loss: 0.0025 - mae: 0.0320 - rmse: 0.0435 - smape: 0.1192 - val_ia: 0.8272 - val_loss: 0.0032 - val_mae: 0.0410 - val_rmse: 0.0514 - val_smape: 0.1268

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:02 1s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 17%|█▋        | 2/12 [39:11<3:42:42, 1336.26s/trial, best loss: 0.0019047236032898704]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 62s - 13ms/step - ia: 0.2564 - loss: 0.8916 - mae: 0.7787 - rmse: 0.9235 - smape: 1.6883 - val_ia: 0.1510 - val_loss: 0.7139 - val_mae: 0.6996 - val_rmse: 0.7166 - val_smape: 1.6715

Epoch 2/128

4586/4586 - 45s - 10ms/step - ia: 0.2980 - loss: 0.8226 - mae: 0.7429 - rmse: 0.8854 - smape: 1.5748 - val_ia: 0.1594 - val_loss: 0.6324 - val_mae: 0.6521 - val_rmse: 0.6689 - val_smape: 1.5272

Epoch 3/128

4586/4586 - 45s - 10ms/step - ia: 0.3539 - loss: 0.7531 - mae: 0.7026 - rmse: 0.8442 - smape: 1.4758 - val_ia: 0.1705 - val_loss: 0.5561 - val_mae: 0.6007 - val_rmse: 0.6171 - val_smape: 1.3900

Epoch 4/128

4586/4586 - 80s - 17ms/step - ia: 0.4127 - loss: 0.6871 - mae: 0.6593 - rmse: 0.8033 - smape: 1.3872 - val_ia: 0.1838 - val_loss: 0.4916 - val_mae: 0.5497 - val_rmse: 0.5659 - val_smape: 1.2807

Epoch 5/128

4586/4586 - 81s - 18ms/step - ia: 0.4676 - loss: 0.6345 - mae: 0.6202 - rmse: 0.7669 - smape: 1.3179 - val_ia: 0.2005 - val_loss: 0.4442 - val_mae: 0.5046 - val_rmse: 0.5211 - val_smape: 1.2022

Epoch 6/128

4586/4586 - 44s - 10ms/step - ia: 0.5120 - loss: 0.5968 - mae: 0.5877 - rmse: 0.7409 - smape: 1.2589 - val_ia: 0.2105 - val_loss: 0.4139 - val_mae: 0.4720 - val_rmse: 0.4888 - val_smape: 1.1448

Epoch 7/128

4586/4586 - 81s - 18ms/step - ia: 0.5381 - loss: 0.5709 - mae: 0.5657 - rmse: 0.7234 - smape: 1.2124 - val_ia: 0.2150 - val_loss: 0.3973 - val_mae: 0.4550 - val_rmse: 0.4720 - val_smape: 1.1016

Epoch 8/128

4586/4586 - 42s - 9ms/step - ia: 0.5520 - loss: 0.5537 - mae: 0.5526 - rmse: 0.7114 - smape: 1.1754 - val_ia: 0.2188 - val_loss: 0.3866 - val_mae: 0.4455 - val_rmse: 0.4626 - val_smape: 1.0642

Epoch 9/128

4586/4586 - 43s - 9ms/step - ia: 0.5621 - loss: 0.5383 - mae: 0.5419 - rmse: 0.6994 - smape: 1.1434 - val_ia: 0.2219 - val_loss: 0.3795 - val_mae: 0.4407 - val_rmse: 0.4580 - val_smape: 1.0357

Epoch 10/128

4586/4586 - 81s - 18ms/step - ia: 0.5706 - loss: 0.5252 - mae: 0.5328 - rmse: 0.6907 - smape: 1.1104 - val_ia: 0.2232 - val_loss: 0.3737 - val_mae: 0.4376 - val_rmse: 0.4551 - val_smape: 1.0135

Epoch 11/128

4586/4586 - 83s - 18ms/step - ia: 0.5777 - loss: 0.5113 - mae: 0.5239 - rmse: 0.6822 - smape: 1.0783 - val_ia: 0.2252 - val_loss: 0.3680 - val_mae: 0.4345 - val_rmse: 0.4520 - val_smape: 0.9914

Epoch 12/128

4586/4586 - 43s - 9ms/step - ia: 0.5833 - loss: 0.4998 - mae: 0.5168 - rmse: 0.6729 - smape: 1.0514 - val_ia: 0.2265 - val_loss: 0.3629 - val_mae: 0.4322 - val_rmse: 0.4496 - val_smape: 0.9710

Epoch 13/128

4586/4586 - 44s - 9ms/step - ia: 0.5918 - loss: 0.4856 - mae: 0.5080 - rmse: 0.6628 - smape: 1.0216 - val_ia: 0.2267 - val_loss: 0.3584 - val_mae: 0.4306 - val_rmse: 0.4480 - val_smape: 0.9519

Epoch 14/128

4586/4586 - 82s - 18ms/step - ia: 0.5958 - loss: 0.4744 - mae: 0.5010 - rmse: 0.6549 - smape: 0.9938 - val_ia: 0.2286 - val_loss: 0.3526 - val_mae: 0.4275 - val_rmse: 0.4448 - val_smape: 0.9319

Epoch 15/128

4586/4586 - 44s - 10ms/step - ia: 0.6021 - loss: 0.4627 - mae: 0.4941 - rmse: 0.6466 - smape: 0.9675 - val_ia: 0.2299 - val_loss: 0.3484 - val_mae: 0.4261 - val_rmse: 0.4432 - val_smape: 0.9143

Epoch 16/128

4586/4586 - 45s - 10ms/step - ia: 0.6088 - loss: 0.4494 - mae: 0.4864 - rmse: 0.6366 - smape: 0.9420 - val_ia: 0.2315 - val_loss: 0.3431 - val_mae: 0.4236 - val_rmse: 0.4406 - val_smape: 0.8959

Epoch 17/128

4586/4586 - 43s - 9ms/step - ia: 0.6140 - loss: 0.4384 - mae: 0.4803 - rmse: 0.6288 - smape: 0.9190 - val_ia: 0.2322 - val_loss: 0.3373 - val_mae: 0.4206 - val_rmse: 0.4376 - val_smape: 0.8775

Epoch 18/128

4586/4586 - 44s - 10ms/step - ia: 0.6205 - loss: 0.4243 - mae: 0.4718 - rmse: 0.6187 - smape: 0.8937 - val_ia: 0.2307 - val_loss: 0.3324 - val_mae: 0.4188 - val_rmse: 0.4355 - val_smape: 0.8613

Epoch 19/128

4586/4586 - 44s - 10ms/step - ia: 0.6281 - loss: 0.4099 - mae: 0.4636 - rmse: 0.6084 - smape: 0.8702 - val_ia: 0.2283 - val_loss: 0.3267 - val_mae: 0.4165 - val_rmse: 0.4329 - val_smape: 0.8455

Epoch 20/128

4586/4586 - 46s - 10ms/step - ia: 0.6358 - loss: 0.3968 - mae: 0.4563 - rmse: 0.5982 - smape: 0.8492 - val_ia: 0.2264 - val_loss: 0.3198 - val_mae: 0.4132 - val_rmse: 0.4294 - val_smape: 0.8299

Epoch 21/128

4586/4586 - 44s - 10ms/step - ia: 0.6421 - loss: 0.3840 - mae: 0.4493 - rmse: 0.5883 - smape: 0.8303 - val_ia: 0.2268 - val_loss: 0.3134 - val_mae: 0.4101 - val_rmse: 0.4261 - val_smape: 0.8158

Epoch 22/128

4586/4586 - 44s - 10ms/step - ia: 0.6507 - loss: 0.3695 - mae: 0.4408 - rmse: 0.5772 - smape: 0.8069 - val_ia: 0.2280 - val_loss: 0.3070 - val_mae: 0.4069 - val_rmse: 0.4229 - val_smape: 0.8029

Epoch 23/128

4586/4586 - 44s - 10ms/step - ia: 0.6575 - loss: 0.3542 - mae: 0.4332 - rmse: 0.5653 - smape: 0.7908 - val_ia: 0.2307 - val_loss: 0.2985 - val_mae: 0.4019 - val_rmse: 0.4178 - val_smape: 0.7892

Epoch 24/128

4586/4586 - 81s - 18ms/step - ia: 0.6656 - loss: 0.3402 - mae: 0.4246 - rmse: 0.5536 - smape: 0.7731 - val_ia: 0.2333 - val_loss: 0.2898 - val_mae: 0.3967 - val_rmse: 0.4126 - val_smape: 0.7762

Epoch 25/128

4586/4586 - 80s - 17ms/step - ia: 0.6726 - loss: 0.3253 - mae: 0.4170 - rmse: 0.5412 - smape: 0.7563 - val_ia: 0.2368 - val_loss: 0.2800 - val_mae: 0.3905 - val_rmse: 0.4064 - val_smape: 0.7635

Epoch 26/128

4586/4586 - 82s - 18ms/step - ia: 0.6821 - loss: 0.3098 - mae: 0.4080 - rmse: 0.5288 - smape: 0.7413 - val_ia: 0.2396 - val_loss: 0.2709 - val_mae: 0.3852 - val_rmse: 0.4011 - val_smape: 0.7526

Epoch 27/128

4586/4586 - 42s - 9ms/step - ia: 0.6931 - loss: 0.2937 - mae: 0.3978 - rmse: 0.5147 - smape: 0.7213 - val_ia: 0.2429 - val_loss: 0.2607 - val_mae: 0.3790 - val_rmse: 0.3948 - val_smape: 0.7417

Epoch 28/128

4586/4586 - 45s - 10ms/step - ia: 0.7001 - loss: 0.2790 - mae: 0.3901 - rmse: 0.5021 - smape: 0.7095 - val_ia: 0.2463 - val_loss: 0.2482 - val_mae: 0.3708 - val_rmse: 0.3866 - val_smape: 0.7299

Epoch 29/128

4586/4586 - 44s - 10ms/step - ia: 0.7107 - loss: 0.2648 - mae: 0.3810 - rmse: 0.4896 - smape: 0.6931 - val_ia: 0.2502 - val_loss: 0.2364 - val_mae: 0.3630 - val_rmse: 0.3788 - val_smape: 0.7193

Epoch 30/128

4586/4586 - 81s - 18ms/step - ia: 0.7177 - loss: 0.2523 - mae: 0.3733 - rmse: 0.4783 - smape: 0.6846 - val_ia: 0.2547 - val_loss: 0.2237 - val_mae: 0.3543 - val_rmse: 0.3701 - val_smape: 0.7086

Epoch 31/128

4586/4586 - 81s - 18ms/step - ia: 0.7262 - loss: 0.2396 - mae: 0.3655 - rmse: 0.4655 - smape: 0.6734 - val_ia: 0.2569 - val_loss: 0.2115 - val_mae: 0.3457 - val_rmse: 0.3614 - val_smape: 0.6986

Epoch 32/128

4586/4586 - 43s - 9ms/step - ia: 0.7350 - loss: 0.2270 - mae: 0.3570 - rmse: 0.4531 - smape: 0.6613 - val_ia: 0.2621 - val_loss: 0.1993 - val_mae: 0.3367 - val_rmse: 0.3524 - val_smape: 0.6884

Epoch 33/128

4586/4586 - 43s - 9ms/step - ia: 0.7423 - loss: 0.2157 - mae: 0.3498 - rmse: 0.4415 - smape: 0.6510 - val_ia: 0.2668 - val_loss: 0.1866 - val_mae: 0.3268 - val_rmse: 0.3423 - val_smape: 0.6777

Epoch 34/128

4586/4586 - 44s - 10ms/step - ia: 0.7524 - loss: 0.2035 - mae: 0.3402 - rmse: 0.4300 - smape: 0.6393 - val_ia: 0.2717 - val_loss: 0.1752 - val_mae: 0.3175 - val_rmse: 0.3329 - val_smape: 0.6681

Epoch 35/128

4586/4586 - 44s - 10ms/step - ia: 0.7576 - loss: 0.1965 - mae: 0.3344 - rmse: 0.4214 - smape: 0.6322 - val_ia: 0.2765 - val_loss: 0.1640 - val_mae: 0.3076 - val_rmse: 0.3228 - val_smape: 0.6578

Epoch 36/128

4586/4586 - 43s - 9ms/step - ia: 0.7619 - loss: 0.1902 - mae: 0.3285 - rmse: 0.4139 - smape: 0.6258 - val_ia: 0.2807 - val_loss: 0.1542 - val_mae: 0.2985 - val_rmse: 0.3136 - val_smape: 0.6482

Epoch 37/128

4586/4586 - 82s - 18ms/step - ia: 0.7674 - loss: 0.1837 - mae: 0.3238 - rmse: 0.4070 - smape: 0.6190 - val_ia: 0.2855 - val_loss: 0.1459 - val_mae: 0.2904 - val_rmse: 0.3053 - val_smape: 0.6392

Epoch 38/128

4586/4586 - 83s - 18ms/step - ia: 0.7729 - loss: 0.1780 - mae: 0.3188 - rmse: 0.4003 - smape: 0.6121 - val_ia: 0.2903 - val_loss: 0.1384 - val_mae: 0.2824 - val_rmse: 0.2972 - val_smape: 0.6297

Epoch 39/128

4586/4586 - 43s - 9ms/step - ia: 0.7756 - loss: 0.1759 - mae: 0.3143 - rmse: 0.3968 - smape: 0.6083 - val_ia: 0.2946 - val_loss: 0.1323 - val_mae: 0.2758 - val_rmse: 0.2905 - val_smape: 0.6215

Epoch 40/128

4586/4586 - 82s - 18ms/step - ia: 0.7798 - loss: 0.1704 - mae: 0.3106 - rmse: 0.3911 - smape: 0.6028 - val_ia: 0.2991 - val_loss: 0.1279 - val_mae: 0.2709 - val_rmse: 0.2854 - val_smape: 0.6152

Epoch 41/128

4586/4586 - 43s - 9ms/step - ia: 0.7835 - loss: 0.1670 - mae: 0.3069 - rmse: 0.3873 - smape: 0.5984 - val_ia: 0.3039 - val_loss: 0.1228 - val_mae: 0.2648 - val_rmse: 0.2792 - val_smape: 0.6075

Epoch 42/128

4586/4586 - 44s - 10ms/step - ia: 0.7833 - loss: 0.1658 - mae: 0.3048 - rmse: 0.3850 - smape: 0.5922 - val_ia: 0.3087 - val_loss: 0.1188 - val_mae: 0.2599 - val_rmse: 0.2742 - val_smape: 0.6008

Epoch 43/128

4586/4586 - 45s - 10ms/step - ia: 0.7892 - loss: 0.1613 - mae: 0.3003 - rmse: 0.3796 - smape: 0.5890 - val_ia: 0.3128 - val_loss: 0.1159 - val_mae: 0.2563 - val_rmse: 0.2706 - val_smape: 0.5956

Epoch 44/128

4586/4586 - 81s - 18ms/step - ia: 0.7894 - loss: 0.1611 - mae: 0.2994 - rmse: 0.3788 - smape: 0.5873 - val_ia: 0.3169 - val_loss: 0.1137 - val_mae: 0.2534 - val_rmse: 0.2676 - val_smape: 0.5911

Epoch 45/128

4586/4586 - 43s - 9ms/step - ia: 0.7926 - loss: 0.1554 - mae: 0.2931 - rmse: 0.3712 - smape: 0.5786 - val_ia: 0.3205 - val_loss: 0.1111 - val_mae: 0.2501 - val_rmse: 0.2642 - val_smape: 0.5863

Epoch 46/128

4586/4586 - 44s - 10ms/step - ia: 0.7942 - loss: 0.1550 - mae: 0.2915 - rmse: 0.3703 - smape: 0.5766 - val_ia: 0.3239 - val_loss: 0.1094 - val_mae: 0.2478 - val_rmse: 0.2617 - val_smape: 0.5826

Epoch 47/128

4586/4586 - 44s - 10ms/step - ia: 0.7943 - loss: 0.1551 - mae: 0.2905 - rmse: 0.3695 - smape: 0.5728 - val_ia: 0.3273 - val_loss: 0.1077 - val_mae: 0.2455 - val_rmse: 0.2594 - val_smape: 0.5790

Epoch 48/128

4586/4586 - 78s - 17ms/step - ia: 0.7985 - loss: 0.1487 - mae: 0.2861 - rmse: 0.3629 - smape: 0.5679 - val_ia: 0.3312 - val_loss: 0.1060 - val_mae: 0.2432 - val_rmse: 0.2569 - val_smape: 0.5751

Epoch 49/128

4586/4586 - 42s - 9ms/step - ia: 0.7992 - loss: 0.1496 - mae: 0.2854 - rmse: 0.3635 - smape: 0.5684 - val_ia: 0.3348 - val_loss: 0.1044 - val_mae: 0.2410 - val_rmse: 0.2546 - val_smape: 0.5713

Epoch 50/128

4586/4586 - 82s - 18ms/step - ia: 0.7994 - loss: 0.1457 - mae: 0.2834 - rmse: 0.3596 - smape: 0.5652 - val_ia: 0.3385 - val_loss: 0.1022 - val_mae: 0.2379 - val_rmse: 0.2516 - val_smape: 0.5663

Epoch 51/128

4586/4586 - 83s - 18ms/step - ia: 0.8017 - loss: 0.1449 - mae: 0.2801 - rmse: 0.3567 - smape: 0.5593 - val_ia: 0.3419 - val_loss: 0.1007 - val_mae: 0.2360 - val_rmse: 0.2496 - val_smape: 0.5629

Epoch 52/128

4586/4586 - 43s - 9ms/step - ia: 0.8030 - loss: 0.1457 - mae: 0.2802 - rmse: 0.3574 - smape: 0.5599 - val_ia: 0.3460 - val_loss: 0.1000 - val_mae: 0.2349 - val_rmse: 0.2484 - val_smape: 0.5603

Epoch 53/128

4586/4586 - 44s - 10ms/step - ia: 0.8047 - loss: 0.1433 - mae: 0.2776 - rmse: 0.3547 - smape: 0.5553 - val_ia: 0.3493 - val_loss: 0.0983 - val_mae: 0.2324 - val_rmse: 0.2459 - val_smape: 0.5560

Epoch 54/128

4586/4586 - 43s - 9ms/step - ia: 0.8068 - loss: 0.1396 - mae: 0.2755 - rmse: 0.3500 - smape: 0.5547 - val_ia: 0.3516 - val_loss: 0.0971 - val_mae: 0.2308 - val_rmse: 0.2443 - val_smape: 0.5531

Epoch 55/128

4586/4586 - 44s - 10ms/step - ia: 0.8071 - loss: 0.1411 - mae: 0.2752 - rmse: 0.3515 - smape: 0.5519 - val_ia: 0.3541 - val_loss: 0.0960 - val_mae: 0.2291 - val_rmse: 0.2426 - val_smape: 0.5499

Epoch 56/128

4586/4586 - 42s - 9ms/step - ia: 0.8112 - loss: 0.1352 - mae: 0.2702 - rmse: 0.3443 - smape: 0.5442 - val_ia: 0.3569 - val_loss: 0.0958 - val_mae: 0.2288 - val_rmse: 0.2422 - val_smape: 0.5482

Epoch 57/128

4586/4586 - 43s - 9ms/step - ia: 0.8098 - loss: 0.1357 - mae: 0.2708 - rmse: 0.3455 - smape: 0.5470 - val_ia: 0.3595 - val_loss: 0.0937 - val_mae: 0.2258 - val_rmse: 0.2392 - val_smape: 0.5431

Epoch 58/128

4586/4586 - 44s - 10ms/step - ia: 0.8108 - loss: 0.1346 - mae: 0.2689 - rmse: 0.3430 - smape: 0.5432 - val_ia: 0.3614 - val_loss: 0.0929 - val_mae: 0.2248 - val_rmse: 0.2381 - val_smape: 0.5409

Epoch 59/128

4586/4586 - 44s - 10ms/step - ia: 0.8122 - loss: 0.1335 - mae: 0.2667 - rmse: 0.3416 - smape: 0.5383 - val_ia: 0.3633 - val_loss: 0.0915 - val_mae: 0.2227 - val_rmse: 0.2360 - val_smape: 0.5376

Epoch 60/128

4586/4586 - 43s - 9ms/step - ia: 0.8161 - loss: 0.1292 - mae: 0.2630 - rmse: 0.3359 - smape: 0.5332 - val_ia: 0.3650 - val_loss: 0.0912 - val_mae: 0.2225 - val_rmse: 0.2358 - val_smape: 0.5364

Epoch 61/128

4586/4586 - 44s - 10ms/step - ia: 0.8160 - loss: 0.1294 - mae: 0.2625 - rmse: 0.3361 - smape: 0.5315 - val_ia: 0.3669 - val_loss: 0.0902 - val_mae: 0.2210 - val_rmse: 0.2343 - val_smape: 0.5332

Epoch 62/128

4586/4586 - 81s - 18ms/step - ia: 0.8156 - loss: 0.1308 - mae: 0.2625 - rmse: 0.3367 - smape: 0.5301 - val_ia: 0.3681 - val_loss: 0.0897 - val_mae: 0.2203 - val_rmse: 0.2335 - val_smape: 0.5312

Epoch 63/128

4586/4586 - 82s - 18ms/step - ia: 0.8176 - loss: 0.1287 - mae: 0.2594 - rmse: 0.3332 - smape: 0.5273 - val_ia: 0.3690 - val_loss: 0.0893 - val_mae: 0.2199 - val_rmse: 0.2331 - val_smape: 0.5297

Epoch 64/128

4586/4586 - 47s - 10ms/step - ia: 0.8183 - loss: 0.1275 - mae: 0.2592 - rmse: 0.3330 - smape: 0.5271 - val_ia: 0.3702 - val_loss: 0.0886 - val_mae: 0.2189 - val_rmse: 0.2321 - val_smape: 0.5274

Epoch 65/128

4586/4586 - 44s - 10ms/step - ia: 0.8209 - loss: 0.1238 - mae: 0.2549 - rmse: 0.3279 - smape: 0.5215 - val_ia: 0.3710 - val_loss: 0.0882 - val_mae: 0.2184 - val_rmse: 0.2316 - val_smape: 0.5261

Epoch 66/128

4586/4586 - 80s - 17ms/step - ia: 0.8212 - loss: 0.1232 - mae: 0.2551 - rmse: 0.3275 - smape: 0.5218 - val_ia: 0.3723 - val_loss: 0.0873 - val_mae: 0.2173 - val_rmse: 0.2304 - val_smape: 0.5237

Epoch 67/128

4586/4586 - 83s - 18ms/step - ia: 0.8212 - loss: 0.1248 - mae: 0.2552 - rmse: 0.3289 - smape: 0.5241 - val_ia: 0.3730 - val_loss: 0.0867 - val_mae: 0.2165 - val_rmse: 0.2296 - val_smape: 0.5217

Epoch 68/128

4586/4586 - 42s - 9ms/step - ia: 0.8222 - loss: 0.1227 - mae: 0.2534 - rmse: 0.3261 - smape: 0.5214 - val_ia: 0.3740 - val_loss: 0.0860 - val_mae: 0.2155 - val_rmse: 0.2286 - val_smape: 0.5192

Epoch 69/128

4586/4586 - 83s - 18ms/step - ia: 0.8231 - loss: 0.1216 - mae: 0.2518 - rmse: 0.3244 - smape: 0.5184 - val_ia: 0.3747 - val_loss: 0.0854 - val_mae: 0.2148 - val_rmse: 0.2279 - val_smape: 0.5177

Epoch 70/128

4586/4586 - 43s - 9ms/step - ia: 0.8243 - loss: 0.1194 - mae: 0.2505 - rmse: 0.3218 - smape: 0.5155 - val_ia: 0.3755 - val_loss: 0.0848 - val_mae: 0.2141 - val_rmse: 0.2272 - val_smape: 0.5160

Epoch 71/128

4586/4586 - 44s - 10ms/step - ia: 0.8253 - loss: 0.1194 - mae: 0.2488 - rmse: 0.3210 - smape: 0.5110 - val_ia: 0.3765 - val_loss: 0.0841 - val_mae: 0.2132 - val_rmse: 0.2263 - val_smape: 0.5141

Epoch 72/128

4586/4586 - 44s - 10ms/step - ia: 0.8253 - loss: 0.1189 - mae: 0.2489 - rmse: 0.3203 - smape: 0.5114 - val_ia: 0.3763 - val_loss: 0.0843 - val_mae: 0.2137 - val_rmse: 0.2268 - val_smape: 0.5137

Epoch 73/128

4586/4586 - 43s - 9ms/step - ia: 0.8269 - loss: 0.1187 - mae: 0.2471 - rmse: 0.3194 - smape: 0.5093 - val_ia: 0.3772 - val_loss: 0.0836 - val_mae: 0.2128 - val_rmse: 0.2258 - val_smape: 0.5121

Epoch 74/128

4586/4586 - 44s - 10ms/step - ia: 0.8274 - loss: 0.1188 - mae: 0.2458 - rmse: 0.3183 - smape: 0.5064 - val_ia: 0.3785 - val_loss: 0.0824 - val_mae: 0.2110 - val_rmse: 0.2241 - val_smape: 0.5099

Epoch 75/128

4586/4586 - 81s - 18ms/step - ia: 0.8277 - loss: 0.1162 - mae: 0.2448 - rmse: 0.3163 - smape: 0.5070 - val_ia: 0.3788 - val_loss: 0.0821 - val_mae: 0.2108 - val_rmse: 0.2238 - val_smape: 0.5092

Epoch 76/128

4586/4586 - 43s - 9ms/step - ia: 0.8281 - loss: 0.1169 - mae: 0.2448 - rmse: 0.3160 - smape: 0.5064 - val_ia: 0.3770 - val_loss: 0.0834 - val_mae: 0.2130 - val_rmse: 0.2260 - val_smape: 0.5111

Epoch 77/128

4586/4586 - 82s - 18ms/step - ia: 0.8292 - loss: 0.1162 - mae: 0.2426 - rmse: 0.3150 - smape: 0.5023 - val_ia: 0.3785 - val_loss: 0.0822 - val_mae: 0.2113 - val_rmse: 0.2242 - val_smape: 0.5087

Epoch 78/128

4586/4586 - 44s - 10ms/step - ia: 0.8305 - loss: 0.1127 - mae: 0.2404 - rmse: 0.3107 - smape: 0.5005 - val_ia: 0.3789 - val_loss: 0.0816 - val_mae: 0.2106 - val_rmse: 0.2236 - val_smape: 0.5076

Epoch 79/128

4586/4586 - 43s - 9ms/step - ia: 0.8350 - loss: 0.1092 - mae: 0.2362 - rmse: 0.3059 - smape: 0.4918 - val_ia: 0.3778 - val_loss: 0.0822 - val_mae: 0.2117 - val_rmse: 0.2246 - val_smape: 0.5081

Epoch 80/128

4586/4586 - 43s - 9ms/step - ia: 0.8325 - loss: 0.1122 - mae: 0.2388 - rmse: 0.3092 - smape: 0.4966 - val_ia: 0.3787 - val_loss: 0.0815 - val_mae: 0.2109 - val_rmse: 0.2238 - val_smape: 0.5068

Epoch 81/128

4586/4586 - 82s - 18ms/step - ia: 0.8337 - loss: 0.1093 - mae: 0.2369 - rmse: 0.3067 - smape: 0.4955 - val_ia: 0.3801 - val_loss: 0.0804 - val_mae: 0.2093 - val_rmse: 0.2222 - val_smape: 0.5046

Epoch 82/128

4586/4586 - 88s - 19ms/step - ia: 0.8341 - loss: 0.1106 - mae: 0.2369 - rmse: 0.3075 - smape: 0.4938 - val_ia: 0.3796 - val_loss: 0.0806 - val_mae: 0.2100 - val_rmse: 0.2228 - val_smape: 0.5049

Epoch 83/128

4586/4586 - 79s - 17ms/step - ia: 0.8352 - loss: 0.1089 - mae: 0.2355 - rmse: 0.3053 - smape: 0.4912 - val_ia: 0.3798 - val_loss: 0.0803 - val_mae: 0.2095 - val_rmse: 0.2224 - val_smape: 0.5041

Epoch 84/128

4586/4586 - 82s - 18ms/step - ia: 0.8360 - loss: 0.1076 - mae: 0.2340 - rmse: 0.3034 - smape: 0.4901 - val_ia: 0.3798 - val_loss: 0.0800 - val_mae: 0.2094 - val_rmse: 0.2222 - val_smape: 0.5040

Epoch 85/128

4586/4586 - 46s - 10ms/step - ia: 0.8374 - loss: 0.1060 - mae: 0.2316 - rmse: 0.3008 - smape: 0.4895 - val_ia: 0.3801 - val_loss: 0.0796 - val_mae: 0.2089 - val_rmse: 0.2216 - val_smape: 0.5029

Epoch 86/128

4586/4586 - 79s - 17ms/step - ia: 0.8371 - loss: 0.1071 - mae: 0.2323 - rmse: 0.3018 - smape: 0.4872 - val_ia: 0.3811 - val_loss: 0.0788 - val_mae: 0.2077 - val_rmse: 0.2205 - val_smape: 0.5008

Epoch 87/128

4586/4586 - 48s - 11ms/step - ia: 0.8368 - loss: 0.1078 - mae: 0.2329 - rmse: 0.3026 - smape: 0.4878 - val_ia: 0.3807 - val_loss: 0.0790 - val_mae: 0.2083 - val_rmse: 0.2210 - val_smape: 0.5013

Epoch 88/128

4586/4586 - 48s - 11ms/step - ia: 0.8375 - loss: 0.1058 - mae: 0.2305 - rmse: 0.3002 - smape: 0.4856 - val_ia: 0.3810 - val_loss: 0.0784 - val_mae: 0.2075 - val_rmse: 0.2202 - val_smape: 0.4999

Epoch 89/128

4586/4586 - 48s - 11ms/step - ia: 0.8373 - loss: 0.1067 - mae: 0.2320 - rmse: 0.3015 - smape: 0.4855 - val_ia: 0.3807 - val_loss: 0.0783 - val_mae: 0.2075 - val_rmse: 0.2202 - val_smape: 0.4993

Epoch 90/128

4586/4586 - 49s - 11ms/step - ia: 0.8385 - loss: 0.1046 - mae: 0.2293 - rmse: 0.2983 - smape: 0.4833 - val_ia: 0.3805 - val_loss: 0.0782 - val_mae: 0.2078 - val_rmse: 0.2205 - val_smape: 0.4992

Epoch 91/128

4586/4586 - 46s - 10ms/step - ia: 0.8400 - loss: 0.1046 - mae: 0.2285 - rmse: 0.2977 - smape: 0.4827 - val_ia: 0.3807 - val_loss: 0.0779 - val_mae: 0.2073 - val_rmse: 0.2200 - val_smape: 0.4980

Epoch 92/128

4586/4586 - 48s - 10ms/step - ia: 0.8412 - loss: 0.1018 - mae: 0.2267 - rmse: 0.2943 - smape: 0.4798 - val_ia: 0.3810 - val_loss: 0.0774 - val_mae: 0.2067 - val_rmse: 0.2193 - val_smape: 0.4970

Epoch 93/128

4586/4586 - 48s - 11ms/step - ia: 0.8427 - loss: 0.1015 - mae: 0.2248 - rmse: 0.2932 - smape: 0.4732 - val_ia: 0.3806 - val_loss: 0.0776 - val_mae: 0.2071 - val_rmse: 0.2197 - val_smape: 0.4974

Epoch 94/128

4586/4586 - 83s - 18ms/step - ia: 0.8423 - loss: 0.1009 - mae: 0.2243 - rmse: 0.2926 - smape: 0.4735 - val_ia: 0.3798 - val_loss: 0.0778 - val_mae: 0.2078 - val_rmse: 0.2204 - val_smape: 0.4977

Epoch 95/128

4586/4586 - 50s - 11ms/step - ia: 0.8417 - loss: 0.1021 - mae: 0.2256 - rmse: 0.2940 - smape: 0.4783 - val_ia: 0.3818 - val_loss: 0.0763 - val_mae: 0.2055 - val_rmse: 0.2181 - val_smape: 0.4946

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 43s - 37ms/step - ia: 0.5421 - loss: 0.4740 - mae: 0.5389 - rmse: 0.6602 - smape: 1.0868 - val_ia: 0.4804 - val_loss: 0.1996 - val_mae: 0.3458 - val_rmse: 0.4061 - val_smape: 0.7630

Epoch 2/128

1147/1147 - 21s - 19ms/step - ia: 0.7732 - loss: 0.1944 - mae: 0.3442 - rmse: 0.4364 - smape: 0.7013 - val_ia: 0.5212 - val_loss: 0.1625 - val_mae: 0.3104 - val_rmse: 0.3656 - val_smape: 0.6765

Epoch 3/128

1147/1147 - 21s - 18ms/step - ia: 0.8065 - loss: 0.1484 - mae: 0.2985 - rmse: 0.3808 - smape: 0.6188 - val_ia: 0.5484 - val_loss: 0.1450 - val_mae: 0.2982 - val_rmse: 0.3445 - val_smape: 0.6527

Epoch 4/128

1147/1147 - 41s - 36ms/step - ia: 0.8266 - loss: 0.1230 - mae: 0.2694 - rmse: 0.3470 - smape: 0.5632 - val_ia: 0.5642 - val_loss: 0.1213 - val_mae: 0.2805 - val_rmse: 0.3208 - val_smape: 0.6266

Epoch 5/128

1147/1147 - 21s - 18ms/step - ia: 0.8410 - loss: 0.1056 - mae: 0.2488 - rmse: 0.3211 - smape: 0.5248 - val_ia: 0.5852 - val_loss: 0.0960 - val_mae: 0.2539 - val_rmse: 0.2905 - val_smape: 0.5901

Epoch 6/128

1147/1147 - 21s - 18ms/step - ia: 0.8522 - loss: 0.0926 - mae: 0.2325 - rmse: 0.3006 - smape: 0.4958 - val_ia: 0.6165 - val_loss: 0.0744 - val_mae: 0.2230 - val_rmse: 0.2578 - val_smape: 0.5435

Epoch 7/128

1147/1147 - 21s - 19ms/step - ia: 0.8612 - loss: 0.0832 - mae: 0.2186 - rmse: 0.2846 - smape: 0.4694 - val_ia: 0.6440 - val_loss: 0.0601 - val_mae: 0.1990 - val_rmse: 0.2326 - val_smape: 0.5046

Epoch 8/128

1147/1147 - 41s - 36ms/step - ia: 0.8667 - loss: 0.0776 - mae: 0.2104 - rmse: 0.2752 - smape: 0.4512 - val_ia: 0.6661 - val_loss: 0.0491 - val_mae: 0.1789 - val_rmse: 0.2116 - val_smape: 0.4691

Epoch 9/128

1147/1147 - 21s - 18ms/step - ia: 0.8732 - loss: 0.0715 - mae: 0.2012 - rmse: 0.2637 - smape: 0.4345 - val_ia: 0.6835 - val_loss: 0.0430 - val_mae: 0.1654 - val_rmse: 0.1979 - val_smape: 0.4447

Epoch 10/128

1147/1147 - 42s - 36ms/step - ia: 0.8760 - loss: 0.0682 - mae: 0.1965 - rmse: 0.2578 - smape: 0.4246 - val_ia: 0.6972 - val_loss: 0.0384 - val_mae: 0.1551 - val_rmse: 0.1869 - val_smape: 0.4238

Epoch 11/128

1147/1147 - 21s - 18ms/step - ia: 0.8790 - loss: 0.0658 - mae: 0.1918 - rmse: 0.2530 - smape: 0.4130 - val_ia: 0.7189 - val_loss: 0.0338 - val_mae: 0.1425 - val_rmse: 0.1747 - val_smape: 0.4015

Epoch 12/128

1147/1147 - 21s - 19ms/step - ia: 0.8825 - loss: 0.0629 - mae: 0.1865 - rmse: 0.2470 - smape: 0.4041 - val_ia: 0.7182 - val_loss: 0.0331 - val_mae: 0.1416 - val_rmse: 0.1730 - val_smape: 0.4002

Epoch 13/128

1147/1147 - 22s - 19ms/step - ia: 0.8853 - loss: 0.0596 - mae: 0.1822 - rmse: 0.2404 - smape: 0.3963 - val_ia: 0.7342 - val_loss: 0.0301 - val_mae: 0.1330 - val_rmse: 0.1644 - val_smape: 0.3837

Epoch 14/128

1147/1147 - 23s - 20ms/step - ia: 0.8872 - loss: 0.0581 - mae: 0.1796 - rmse: 0.2374 - smape: 0.3901 - val_ia: 0.7416 - val_loss: 0.0283 - val_mae: 0.1281 - val_rmse: 0.1593 - val_smape: 0.3719

Epoch 15/128

1147/1147 - 38s - 33ms/step - ia: 0.8878 - loss: 0.0568 - mae: 0.1781 - rmse: 0.2348 - smape: 0.3889 - val_ia: 0.7453 - val_loss: 0.0274 - val_mae: 0.1257 - val_rmse: 0.1565 - val_smape: 0.3638

Epoch 16/128

1147/1147 - 20s - 17ms/step - ia: 0.8907 - loss: 0.0549 - mae: 0.1739 - rmse: 0.2307 - smape: 0.3811 - val_ia: 0.7498 - val_loss: 0.0264 - val_mae: 0.1229 - val_rmse: 0.1534 - val_smape: 0.3580

Epoch 17/128

1147/1147 - 18s - 16ms/step - ia: 0.8920 - loss: 0.0534 - mae: 0.1718 - rmse: 0.2279 - smape: 0.3765 - val_ia: 0.7519 - val_loss: 0.0254 - val_mae: 0.1209 - val_rmse: 0.1510 - val_smape: 0.3536

Epoch 18/128

1147/1147 - 15s - 13ms/step - ia: 0.8930 - loss: 0.0521 - mae: 0.1700 - rmse: 0.2250 - smape: 0.3718 - val_ia: 0.7548 - val_loss: 0.0250 - val_mae: 0.1194 - val_rmse: 0.1490 - val_smape: 0.3461

Epoch 19/128

1147/1147 - 18s - 16ms/step - ia: 0.8944 - loss: 0.0512 - mae: 0.1680 - rmse: 0.2229 - smape: 0.3697 - val_ia: 0.7588 - val_loss: 0.0241 - val_mae: 0.1173 - val_rmse: 0.1466 - val_smape: 0.3453

Epoch 20/128

1147/1147 - 19s - 17ms/step - ia: 0.8951 - loss: 0.0504 - mae: 0.1669 - rmse: 0.2212 - smape: 0.3655 - val_ia: 0.7619 - val_loss: 0.0235 - val_mae: 0.1152 - val_rmse: 0.1444 - val_smape: 0.3358

Epoch 21/128

1147/1147 - 14s - 12ms/step - ia: 0.8969 - loss: 0.0491 - mae: 0.1642 - rmse: 0.2183 - smape: 0.3612 - val_ia: 0.7633 - val_loss: 0.0232 - val_mae: 0.1146 - val_rmse: 0.1437 - val_smape: 0.3369

Epoch 22/128

1147/1147 - 12s - 11ms/step - ia: 0.8983 - loss: 0.0477 - mae: 0.1620 - rmse: 0.2151 - smape: 0.3579 - val_ia: 0.7759 - val_loss: 0.0212 - val_mae: 0.1076 - val_rmse: 0.1369 - val_smape: 0.3187

Epoch 23/128

1147/1147 - 13s - 11ms/step - ia: 0.8989 - loss: 0.0471 - mae: 0.1609 - rmse: 0.2139 - smape: 0.3549 - val_ia: 0.7757 - val_loss: 0.0210 - val_mae: 0.1075 - val_rmse: 0.1365 - val_smape: 0.3181

Epoch 24/128

1147/1147 - 18s - 16ms/step - ia: 0.8992 - loss: 0.0469 - mae: 0.1604 - rmse: 0.2134 - smape: 0.3528 - val_ia: 0.7809 - val_loss: 0.0201 - val_mae: 0.1046 - val_rmse: 0.1333 - val_smape: 0.3123

Epoch 25/128

1147/1147 - 20s - 18ms/step - ia: 0.9005 - loss: 0.0460 - mae: 0.1584 - rmse: 0.2112 - smape: 0.3500 - val_ia: 0.7809 - val_loss: 0.0201 - val_mae: 0.1049 - val_rmse: 0.1333 - val_smape: 0.3126

Epoch 26/128

1147/1147 - 21s - 18ms/step - ia: 0.9012 - loss: 0.0451 - mae: 0.1574 - rmse: 0.2093 - smape: 0.3480 - val_ia: 0.7800 - val_loss: 0.0202 - val_mae: 0.1053 - val_rmse: 0.1335 - val_smape: 0.3130

Epoch 27/128

1147/1147 - 23s - 20ms/step - ia: 0.9023 - loss: 0.0443 - mae: 0.1558 - rmse: 0.2072 - smape: 0.3459 - val_ia: 0.7786 - val_loss: 0.0200 - val_mae: 0.1050 - val_rmse: 0.1328 - val_smape: 0.3091

Epoch 28/128

1147/1147 - 15s - 13ms/step - ia: 0.9033 - loss: 0.0434 - mae: 0.1540 - rmse: 0.2051 - smape: 0.3445 - val_ia: 0.7833 - val_loss: 0.0192 - val_mae: 0.1027 - val_rmse: 0.1303 - val_smape: 0.3049

Epoch 29/128

1147/1147 - 13s - 11ms/step - ia: 0.9039 - loss: 0.0428 - mae: 0.1531 - rmse: 0.2040 - smape: 0.3390 - val_ia: 0.7840 - val_loss: 0.0192 - val_mae: 0.1027 - val_rmse: 0.1301 - val_smape: 0.3054

Epoch 30/128

1147/1147 - 13s - 11ms/step - ia: 0.9049 - loss: 0.0427 - mae: 0.1518 - rmse: 0.2031 - smape: 0.3365 - val_ia: 0.7878 - val_loss: 0.0185 - val_mae: 0.1006 - val_rmse: 0.1279 - val_smape: 0.3016

Epoch 31/128

1147/1147 - 18s - 16ms/step - ia: 0.9051 - loss: 0.0422 - mae: 0.1516 - rmse: 0.2021 - smape: 0.3373 - val_ia: 0.7860 - val_loss: 0.0186 - val_mae: 0.1008 - val_rmse: 0.1279 - val_smape: 0.2980

Epoch 32/128

1147/1147 - 18s - 16ms/step - ia: 0.9057 - loss: 0.0415 - mae: 0.1505 - rmse: 0.2007 - smape: 0.3344 - val_ia: 0.7943 - val_loss: 0.0174 - val_mae: 0.0969 - val_rmse: 0.1239 - val_smape: 0.2908

Epoch 33/128

1147/1147 - 18s - 16ms/step - ia: 0.9064 - loss: 0.0413 - mae: 0.1495 - rmse: 0.1998 - smape: 0.3321 - val_ia: 0.7946 - val_loss: 0.0172 - val_mae: 0.0963 - val_rmse: 0.1232 - val_smape: 0.2867

Epoch 34/128

1147/1147 - 18s - 16ms/step - ia: 0.9074 - loss: 0.0402 - mae: 0.1475 - rmse: 0.1970 - smape: 0.3293 - val_ia: 0.7913 - val_loss: 0.0177 - val_mae: 0.0979 - val_rmse: 0.1245 - val_smape: 0.2886

Epoch 35/128

1147/1147 - 19s - 17ms/step - ia: 0.9075 - loss: 0.0401 - mae: 0.1477 - rmse: 0.1971 - smape: 0.3275 - val_ia: 0.7980 - val_loss: 0.0167 - val_mae: 0.0947 - val_rmse: 0.1212 - val_smape: 0.2832

Epoch 36/128

1147/1147 - 13s - 11ms/step - ia: 0.9084 - loss: 0.0396 - mae: 0.1465 - rmse: 0.1959 - smape: 0.3260 - val_ia: 0.7977 - val_loss: 0.0166 - val_mae: 0.0951 - val_rmse: 0.1212 - val_smape: 0.2876

Epoch 37/128

1147/1147 - 12s - 11ms/step - ia: 0.9092 - loss: 0.0388 - mae: 0.1450 - rmse: 0.1937 - smape: 0.3224 - val_ia: 0.7971 - val_loss: 0.0165 - val_mae: 0.0945 - val_rmse: 0.1206 - val_smape: 0.2809

Epoch 38/128

1147/1147 - 13s - 11ms/step - ia: 0.9097 - loss: 0.0385 - mae: 0.1444 - rmse: 0.1928 - smape: 0.3216 - val_ia: 0.7929 - val_loss: 0.0169 - val_mae: 0.0965 - val_rmse: 0.1223 - val_smape: 0.2866

Epoch 39/128

1147/1147 - 18s - 16ms/step - ia: 0.9102 - loss: 0.0379 - mae: 0.1434 - rmse: 0.1915 - smape: 0.3217 - val_ia: 0.7941 - val_loss: 0.0167 - val_mae: 0.0958 - val_rmse: 0.1215 - val_smape: 0.2826

Epoch 40/128

1147/1147 - 21s - 18ms/step - ia: 0.9105 - loss: 0.0376 - mae: 0.1429 - rmse: 0.1909 - smape: 0.3179 - val_ia: 0.8016 - val_loss: 0.0157 - val_mae: 0.0920 - val_rmse: 0.1177 - val_smape: 0.2734

Epoch 41/128

1147/1147 - 18s - 16ms/step - ia: 0.9104 - loss: 0.0378 - mae: 0.1432 - rmse: 0.1913 - smape: 0.3194 - val_ia: 0.7975 - val_loss: 0.0161 - val_mae: 0.0938 - val_rmse: 0.1191 - val_smape: 0.2771

Epoch 42/128

1147/1147 - 18s - 16ms/step - ia: 0.9117 - loss: 0.0367 - mae: 0.1408 - rmse: 0.1884 - smape: 0.3158 - val_ia: 0.8110 - val_loss: 0.0144 - val_mae: 0.0875 - val_rmse: 0.1128 - val_smape: 0.2666

Epoch 43/128

1147/1147 - 18s - 16ms/step - ia: 0.9123 - loss: 0.0362 - mae: 0.1400 - rmse: 0.1873 - smape: 0.3136 - val_ia: 0.8031 - val_loss: 0.0152 - val_mae: 0.0908 - val_rmse: 0.1159 - val_smape: 0.2698

Epoch 44/128

1147/1147 - 18s - 16ms/step - ia: 0.9127 - loss: 0.0360 - mae: 0.1397 - rmse: 0.1869 - smape: 0.3123 - val_ia: 0.8053 - val_loss: 0.0149 - val_mae: 0.0899 - val_rmse: 0.1147 - val_smape: 0.2686

Epoch 45/128

1147/1147 - 18s - 16ms/step - ia: 0.9137 - loss: 0.0351 - mae: 0.1383 - rmse: 0.1846 - smape: 0.3099 - val_ia: 0.8083 - val_loss: 0.0145 - val_mae: 0.0885 - val_rmse: 0.1131 - val_smape: 0.2691

Epoch 46/128

1147/1147 - 21s - 18ms/step - ia: 0.9134 - loss: 0.0355 - mae: 0.1387 - rmse: 0.1854 - smape: 0.3113 - val_ia: 0.8101 - val_loss: 0.0142 - val_mae: 0.0873 - val_rmse: 0.1119 - val_smape: 0.2607

Epoch 47/128

1147/1147 - 18s - 16ms/step - ia: 0.9140 - loss: 0.0349 - mae: 0.1376 - rmse: 0.1835 - smape: 0.3084 - val_ia: 0.8118 - val_loss: 0.0139 - val_mae: 0.0862 - val_rmse: 0.1107 - val_smape: 0.2581

Epoch 48/128

1147/1147 - 18s - 16ms/step - ia: 0.9145 - loss: 0.0346 - mae: 0.1369 - rmse: 0.1829 - smape: 0.3084 - val_ia: 0.8084 - val_loss: 0.0142 - val_mae: 0.0872 - val_rmse: 0.1116 - val_smape: 0.2556

Epoch 49/128

1147/1147 - 19s - 17ms/step - ia: 0.9152 - loss: 0.0342 - mae: 0.1358 - rmse: 0.1820 - smape: 0.3029 - val_ia: 0.8114 - val_loss: 0.0139 - val_mae: 0.0862 - val_rmse: 0.1106 - val_smape: 0.2556

Epoch 50/128

1147/1147 - 19s - 17ms/step - ia: 0.9154 - loss: 0.0341 - mae: 0.1356 - rmse: 0.1815 - smape: 0.3026 - val_ia: 0.8133 - val_loss: 0.0135 - val_mae: 0.0850 - val_rmse: 0.1090 - val_smape: 0.2516

Epoch 51/128

1147/1147 - 18s - 16ms/step - ia: 0.9157 - loss: 0.0336 - mae: 0.1349 - rmse: 0.1804 - smape: 0.3026 - val_ia: 0.8145 - val_loss: 0.0133 - val_mae: 0.0841 - val_rmse: 0.1080 - val_smape: 0.2485

Epoch 52/128

1147/1147 - 18s - 16ms/step - ia: 0.9160 - loss: 0.0334 - mae: 0.1345 - rmse: 0.1797 - smape: 0.3023 - val_ia: 0.8160 - val_loss: 0.0131 - val_mae: 0.0838 - val_rmse: 0.1076 - val_smape: 0.2507

Epoch 53/128

1147/1147 - 22s - 19ms/step - ia: 0.9166 - loss: 0.0333 - mae: 0.1338 - rmse: 0.1793 - smape: 0.2993 - val_ia: 0.8215 - val_loss: 0.0124 - val_mae: 0.0808 - val_rmse: 0.1044 - val_smape: 0.2415

Epoch 54/128

1147/1147 - 18s - 16ms/step - ia: 0.9161 - loss: 0.0332 - mae: 0.1344 - rmse: 0.1794 - smape: 0.3003 - val_ia: 0.8168 - val_loss: 0.0128 - val_mae: 0.0828 - val_rmse: 0.1061 - val_smape: 0.2453

Epoch 55/128

1147/1147 - 17s - 15ms/step - ia: 0.9168 - loss: 0.0331 - mae: 0.1332 - rmse: 0.1788 - smape: 0.2984 - val_ia: 0.8252 - val_loss: 0.0118 - val_mae: 0.0791 - val_rmse: 0.1024 - val_smape: 0.2407

Epoch 56/128

1147/1147 - 25s - 22ms/step - ia: 0.9172 - loss: 0.0326 - mae: 0.1328 - rmse: 0.1775 - smape: 0.2973 - val_ia: 0.8226 - val_loss: 0.0121 - val_mae: 0.0801 - val_rmse: 0.1032 - val_smape: 0.2416

Epoch 57/128

1147/1147 - 22s - 19ms/step - ia: 0.9175 - loss: 0.0321 - mae: 0.1321 - rmse: 0.1763 - smape: 0.2958 - val_ia: 0.8238 - val_loss: 0.0118 - val_mae: 0.0794 - val_rmse: 0.1022 - val_smape: 0.2403

Epoch 58/128

1147/1147 - 33s - 29ms/step - ia: 0.9181 - loss: 0.0320 - mae: 0.1314 - rmse: 0.1760 - smape: 0.2955 - val_ia: 0.8248 - val_loss: 0.0117 - val_mae: 0.0784 - val_rmse: 0.1013 - val_smape: 0.2297

Epoch 59/128

1147/1147 - 24s - 21ms/step - ia: 0.9187 - loss: 0.0316 - mae: 0.1304 - rmse: 0.1747 - smape: 0.2934 - val_ia: 0.8217 - val_loss: 0.0119 - val_mae: 0.0802 - val_rmse: 0.1026 - val_smape: 0.2399

Epoch 60/128

1147/1147 - 18s - 15ms/step - ia: 0.9188 - loss: 0.0316 - mae: 0.1302 - rmse: 0.1749 - smape: 0.2911 - val_ia: 0.8186 - val_loss: 0.0122 - val_mae: 0.0815 - val_rmse: 0.1037 - val_smape: 0.2415

Epoch 61/128

1147/1147 - 21s - 18ms/step - ia: 0.9191 - loss: 0.0314 - mae: 0.1298 - rmse: 0.1740 - smape: 0.2914 - val_ia: 0.8230 - val_loss: 0.0117 - val_mae: 0.0797 - val_rmse: 0.1019 - val_smape: 0.2398

Epoch 62/128

1147/1147 - 18s - 16ms/step - ia: 0.9197 - loss: 0.0306 - mae: 0.1287 - rmse: 0.1722 - smape: 0.2899 - val_ia: 0.8314 - val_loss: 0.0107 - val_mae: 0.0753 - val_rmse: 0.0973 - val_smape: 0.2256

Epoch 63/128

1147/1147 - 18s - 16ms/step - ia: 0.9194 - loss: 0.0310 - mae: 0.1292 - rmse: 0.1733 - smape: 0.2873 - val_ia: 0.8256 - val_loss: 0.0113 - val_mae: 0.0781 - val_rmse: 0.0999 - val_smape: 0.2343

Epoch 64/128

1147/1147 - 18s - 16ms/step - ia: 0.9197 - loss: 0.0307 - mae: 0.1288 - rmse: 0.1720 - smape: 0.2915 - val_ia: 0.8316 - val_loss: 0.0106 - val_mae: 0.0757 - val_rmse: 0.0972 - val_smape: 0.2296

Epoch 65/128

1147/1147 - 16s - 14ms/step - ia: 0.9206 - loss: 0.0300 - mae: 0.1273 - rmse: 0.1701 - smape: 0.2859 - val_ia: 0.8281 - val_loss: 0.0109 - val_mae: 0.0768 - val_rmse: 0.0984 - val_smape: 0.2309

Epoch 66/128

1147/1147 - 12s - 11ms/step - ia: 0.9208 - loss: 0.0300 - mae: 0.1268 - rmse: 0.1699 - smape: 0.2858 - val_ia: 0.8304 - val_loss: 0.0106 - val_mae: 0.0758 - val_rmse: 0.0971 - val_smape: 0.2296

Epoch 67/128

1147/1147 - 12s - 11ms/step - ia: 0.9209 - loss: 0.0299 - mae: 0.1268 - rmse: 0.1700 - smape: 0.2847 - val_ia: 0.8313 - val_loss: 0.0105 - val_mae: 0.0755 - val_rmse: 0.0967 - val_smape: 0.2300

Epoch 68/128

1147/1147 - 16s - 14ms/step - ia: 0.9218 - loss: 0.0295 - mae: 0.1257 - rmse: 0.1688 - smape: 0.2840 - val_ia: 0.8320 - val_loss: 0.0104 - val_mae: 0.0747 - val_rmse: 0.0958 - val_smape: 0.2241

Epoch 69/128

1147/1147 - 18s - 16ms/step - ia: 0.9217 - loss: 0.0295 - mae: 0.1256 - rmse: 0.1687 - smape: 0.2827 - val_ia: 0.8345 - val_loss: 0.0101 - val_mae: 0.0733 - val_rmse: 0.0945 - val_smape: 0.2163

Epoch 70/128

1147/1147 - 18s - 16ms/step - ia: 0.9224 - loss: 0.0289 - mae: 0.1248 - rmse: 0.1671 - smape: 0.2833 - val_ia: 0.8268 - val_loss: 0.0108 - val_mae: 0.0764 - val_rmse: 0.0974 - val_smape: 0.2223

Epoch 71/128

1147/1147 - 20s - 18ms/step - ia: 0.9222 - loss: 0.0288 - mae: 0.1248 - rmse: 0.1668 - smape: 0.2817 - val_ia: 0.8425 - val_loss: 0.0093 - val_mae: 0.0701 - val_rmse: 0.0907 - val_smape: 0.2135

Epoch 72/128

1147/1147 - 18s - 16ms/step - ia: 0.9222 - loss: 0.0290 - mae: 0.1249 - rmse: 0.1673 - smape: 0.2829 - val_ia: 0.8316 - val_loss: 0.0104 - val_mae: 0.0746 - val_rmse: 0.0955 - val_smape: 0.2160

Epoch 73/128

1147/1147 - 14s - 12ms/step - ia: 0.9227 - loss: 0.0287 - mae: 0.1238 - rmse: 0.1666 - smape: 0.2800 - val_ia: 0.8369 - val_loss: 0.0097 - val_mae: 0.0723 - val_rmse: 0.0926 - val_smape: 0.2189

Epoch 74/128

1147/1147 - 13s - 11ms/step - ia: 0.9231 - loss: 0.0284 - mae: 0.1234 - rmse: 0.1655 - smape: 0.2796 - val_ia: 0.8314 - val_loss: 0.0101 - val_mae: 0.0743 - val_rmse: 0.0946 - val_smape: 0.2220

Epoch 75/128

1147/1147 - 22s - 19ms/step - ia: 0.9234 - loss: 0.0280 - mae: 0.1229 - rmse: 0.1643 - smape: 0.2777 - val_ia: 0.8403 - val_loss: 0.0093 - val_mae: 0.0702 - val_rmse: 0.0905 - val_smape: 0.2057

Epoch 76/128

1147/1147 - 18s - 15ms/step - ia: 0.9236 - loss: 0.0280 - mae: 0.1225 - rmse: 0.1642 - smape: 0.2776 - val_ia: 0.8344 - val_loss: 0.0098 - val_mae: 0.0732 - val_rmse: 0.0931 - val_smape: 0.2218

Epoch 77/128

1147/1147 - 18s - 15ms/step - ia: 0.9242 - loss: 0.0279 - mae: 0.1219 - rmse: 0.1641 - smape: 0.2754 - val_ia: 0.8371 - val_loss: 0.0095 - val_mae: 0.0720 - val_rmse: 0.0918 - val_smape: 0.2183

Epoch 78/128

1147/1147 - 21s - 18ms/step - ia: 0.9235 - loss: 0.0280 - mae: 0.1227 - rmse: 0.1646 - smape: 0.2763 - val_ia: 0.8443 - val_loss: 0.0089 - val_mae: 0.0686 - val_rmse: 0.0884 - val_smape: 0.2060

Epoch 79/128

1147/1147 - 18s - 16ms/step - ia: 0.9243 - loss: 0.0275 - mae: 0.1218 - rmse: 0.1631 - smape: 0.2751 - val_ia: 0.8345 - val_loss: 0.0097 - val_mae: 0.0725 - val_rmse: 0.0924 - val_smape: 0.2114

Epoch 80/128

1147/1147 - 16s - 14ms/step - ia: 0.9248 - loss: 0.0274 - mae: 0.1210 - rmse: 0.1624 - smape: 0.2719 - val_ia: 0.8395 - val_loss: 0.0092 - val_mae: 0.0707 - val_rmse: 0.0903 - val_smape: 0.2120

Epoch 81/128

1147/1147 - 20s - 18ms/step - ia: 0.9244 - loss: 0.0275 - mae: 0.1215 - rmse: 0.1632 - smape: 0.2733 - val_ia: 0.8465 - val_loss: 0.0086 - val_mae: 0.0676 - val_rmse: 0.0870 - val_smape: 0.2044

Epoch 82/128

1147/1147 - 17s - 14ms/step - ia: 0.9245 - loss: 0.0272 - mae: 0.1211 - rmse: 0.1621 - smape: 0.2726 - val_ia: 0.8379 - val_loss: 0.0094 - val_mae: 0.0710 - val_rmse: 0.0907 - val_smape: 0.2038

Epoch 83/128

1147/1147 - 17s - 15ms/step - ia: 0.9252 - loss: 0.0268 - mae: 0.1201 - rmse: 0.1610 - smape: 0.2715 - val_ia: 0.8437 - val_loss: 0.0087 - val_mae: 0.0682 - val_rmse: 0.0875 - val_smape: 0.2020

Epoch 84/128

1147/1147 - 15s - 13ms/step - ia: 0.9252 - loss: 0.0272 - mae: 0.1203 - rmse: 0.1619 - smape: 0.2691 - val_ia: 0.8413 - val_loss: 0.0089 - val_mae: 0.0693 - val_rmse: 0.0885 - val_smape: 0.2069

Epoch 85/128

1147/1147 - 20s - 17ms/step - ia: 0.9255 - loss: 0.0268 - mae: 0.1199 - rmse: 0.1609 - smape: 0.2714 - val_ia: 0.8452 - val_loss: 0.0085 - val_mae: 0.0678 - val_rmse: 0.0868 - val_smape: 0.2060

Epoch 86/128

1147/1147 - 19s - 17ms/step - ia: 0.9254 - loss: 0.0268 - mae: 0.1198 - rmse: 0.1607 - smape: 0.2701 - val_ia: 0.8445 - val_loss: 0.0086 - val_mae: 0.0680 - val_rmse: 0.0871 - val_smape: 0.2027

Epoch 87/128

1147/1147 - 20s - 17ms/step - ia: 0.9257 - loss: 0.0266 - mae: 0.1194 - rmse: 0.1602 - smape: 0.2681 - val_ia: 0.8499 - val_loss: 0.0081 - val_mae: 0.0656 - val_rmse: 0.0847 - val_smape: 0.1945

Epoch 88/128

1147/1147 - 20s - 18ms/step - ia: 0.9257 - loss: 0.0266 - mae: 0.1194 - rmse: 0.1600 - smape: 0.2685 - val_ia: 0.8458 - val_loss: 0.0084 - val_mae: 0.0671 - val_rmse: 0.0860 - val_smape: 0.1981

Epoch 89/128

1147/1147 - 21s - 18ms/step - ia: 0.9264 - loss: 0.0262 - mae: 0.1181 - rmse: 0.1591 - smape: 0.2669 - val_ia: 0.8437 - val_loss: 0.0086 - val_mae: 0.0682 - val_rmse: 0.0870 - val_smape: 0.2034

Epoch 90/128

1147/1147 - 15s - 13ms/step - ia: 0.9263 - loss: 0.0262 - mae: 0.1184 - rmse: 0.1591 - smape: 0.2667 - val_ia: 0.8509 - val_loss: 0.0080 - val_mae: 0.0649 - val_rmse: 0.0838 - val_smape: 0.1902

Epoch 91/128

1147/1147 - 17s - 14ms/step - ia: 0.9270 - loss: 0.0258 - mae: 0.1175 - rmse: 0.1577 - smape: 0.2648 - val_ia: 0.8543 - val_loss: 0.0077 - val_mae: 0.0637 - val_rmse: 0.0823 - val_smape: 0.1911

Epoch 92/128

1147/1147 - 22s - 19ms/step - ia: 0.9272 - loss: 0.0256 - mae: 0.1170 - rmse: 0.1571 - smape: 0.2658 - val_ia: 0.8490 - val_loss: 0.0081 - val_mae: 0.0658 - val_rmse: 0.0843 - val_smape: 0.1983

Epoch 93/128

1147/1147 - 22s - 20ms/step - ia: 0.9269 - loss: 0.0260 - mae: 0.1176 - rmse: 0.1581 - smape: 0.2657 - val_ia: 0.8550 - val_loss: 0.0076 - val_mae: 0.0632 - val_rmse: 0.0818 - val_smape: 0.1873

Epoch 94/128

1147/1147 - 22s - 20ms/step - ia: 0.9271 - loss: 0.0255 - mae: 0.1172 - rmse: 0.1570 - smape: 0.2655 - val_ia: 0.8495 - val_loss: 0.0080 - val_mae: 0.0655 - val_rmse: 0.0840 - val_smape: 0.1934

Epoch 95/128

1147/1147 - 19s - 17ms/step - ia: 0.9271 - loss: 0.0257 - mae: 0.1171 - rmse: 0.1574 - smape: 0.2650 - val_ia: 0.8450 - val_loss: 0.0084 - val_mae: 0.0673 - val_rmse: 0.0858 - val_smape: 0.1948

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

574/574 - 16s - 28ms/step - ia: 0.0817 - loss: 1.4133 - mae: 0.9886 - rmse: 1.1855 - smape: 1.7926 - val_ia: 0.2284 - val_loss: 1.1147 - val_mae: 0.8866 - val_rmse: 1.0237 - val_smape: 1.7247

Epoch 2/128

574/574 - 5s - 9ms/step - ia: 0.1067 - loss: 1.2751 - mae: 0.9377 - rmse: 1.1263 - smape: 1.7530 - val_ia: 0.2453 - val_loss: 1.0060 - val_mae: 0.8401 - val_rmse: 0.9719 - val_smape: 1.6748

Epoch 3/128

574/574 - 11s - 19ms/step - ia: 0.1387 - loss: 1.1560 - mae: 0.8908 - rmse: 1.0722 - smape: 1.6969 - val_ia: 0.2646 - val_loss: 0.9060 - val_mae: 0.7950 - val_rmse: 0.9217 - val_smape: 1.6052

Epoch 4/128

574/574 - 6s - 10ms/step - ia: 0.1841 - loss: 1.0461 - mae: 0.8451 - rmse: 1.0195 - smape: 1.6287 - val_ia: 0.2869 - val_loss: 0.8137 - val_mae: 0.7512 - val_rmse: 0.8728 - val_smape: 1.5329

Epoch 5/128

574/574 - 11s - 18ms/step - ia: 0.2295 - loss: 0.9458 - mae: 0.8020 - rmse: 0.9697 - smape: 1.5533 - val_ia: 0.3127 - val_loss: 0.7281 - val_mae: 0.7082 - val_rmse: 0.8249 - val_smape: 1.4612

Epoch 6/128

574/574 - 10s - 18ms/step - ia: 0.2824 - loss: 0.8484 - mae: 0.7567 - rmse: 0.9182 - smape: 1.4642 - val_ia: 0.3407 - val_loss: 0.6490 - val_mae: 0.6662 - val_rmse: 0.7779 - val_smape: 1.3852

Epoch 7/128

574/574 - 4s - 8ms/step - ia: 0.3351 - loss: 0.7659 - mae: 0.7162 - rmse: 0.8729 - smape: 1.3808 - val_ia: 0.3701 - val_loss: 0.5757 - val_mae: 0.6249 - val_rmse: 0.7318 - val_smape: 1.3091

Epoch 8/128

574/574 - 4s - 8ms/step - ia: 0.3867 - loss: 0.6896 - mae: 0.6768 - rmse: 0.8276 - smape: 1.2999 - val_ia: 0.4000 - val_loss: 0.5081 - val_mae: 0.5844 - val_rmse: 0.6865 - val_smape: 1.2221

Epoch 9/128

574/574 - 4s - 6ms/step - ia: 0.4384 - loss: 0.6151 - mae: 0.6370 - rmse: 0.7816 - smape: 1.2179 - val_ia: 0.4310 - val_loss: 0.4460 - val_mae: 0.5447 - val_rmse: 0.6422 - val_smape: 1.1254

Epoch 10/128

574/574 - 4s - 6ms/step - ia: 0.4867 - loss: 0.5529 - mae: 0.6005 - rmse: 0.7411 - smape: 1.1382 - val_ia: 0.4631 - val_loss: 0.3895 - val_mae: 0.5060 - val_rmse: 0.5990 - val_smape: 1.0287

Epoch 11/128

574/574 - 4s - 6ms/step - ia: 0.5339 - loss: 0.4927 - mae: 0.5638 - rmse: 0.6993 - smape: 1.0678 - val_ia: 0.4963 - val_loss: 0.3384 - val_mae: 0.4686 - val_rmse: 0.5573 - val_smape: 0.9385

Epoch 12/128

574/574 - 4s - 8ms/step - ia: 0.5750 - loss: 0.4418 - mae: 0.5295 - rmse: 0.6621 - smape: 0.9994 - val_ia: 0.5306 - val_loss: 0.2927 - val_mae: 0.4326 - val_rmse: 0.5172 - val_smape: 0.8568

Epoch 13/128

574/574 - 7s - 11ms/step - ia: 0.6082 - loss: 0.4018 - mae: 0.5022 - rmse: 0.6312 - smape: 0.9500 - val_ia: 0.5660 - val_loss: 0.2523 - val_mae: 0.3985 - val_rmse: 0.4792 - val_smape: 0.7858

Epoch 14/128

574/574 - 6s - 10ms/step - ia: 0.6437 - loss: 0.3572 - mae: 0.4706 - rmse: 0.5951 - smape: 0.8926 - val_ia: 0.6002 - val_loss: 0.2176 - val_mae: 0.3670 - val_rmse: 0.4442 - val_smape: 0.7299

Epoch 15/128

574/574 - 6s - 11ms/step - ia: 0.6726 - loss: 0.3231 - mae: 0.4447 - rmse: 0.5660 - smape: 0.8486 - val_ia: 0.6321 - val_loss: 0.1882 - val_mae: 0.3384 - val_rmse: 0.4126 - val_smape: 0.6831

Epoch 16/128

574/574 - 10s - 17ms/step - ia: 0.6967 - loss: 0.2958 - mae: 0.4228 - rmse: 0.5411 - smape: 0.8079 - val_ia: 0.6609 - val_loss: 0.1638 - val_mae: 0.3133 - val_rmse: 0.3848 - val_smape: 0.6465

Epoch 17/128

574/574 - 6s - 10ms/step - ia: 0.7184 - loss: 0.2688 - mae: 0.4024 - rmse: 0.5154 - smape: 0.7741 - val_ia: 0.6848 - val_loss: 0.1446 - val_mae: 0.2927 - val_rmse: 0.3618 - val_smape: 0.6202

Epoch 18/128

574/574 - 10s - 17ms/step - ia: 0.7350 - loss: 0.2488 - mae: 0.3864 - rmse: 0.4962 - smape: 0.7476 - val_ia: 0.7034 - val_loss: 0.1299 - val_mae: 0.2771 - val_rmse: 0.3436 - val_smape: 0.6032

Epoch 19/128

574/574 - 11s - 18ms/step - ia: 0.7500 - loss: 0.2322 - mae: 0.3725 - rmse: 0.4790 - smape: 0.7214 - val_ia: 0.7171 - val_loss: 0.1192 - val_mae: 0.2663 - val_rmse: 0.3301 - val_smape: 0.5928

Epoch 20/128

574/574 - 6s - 10ms/step - ia: 0.7609 - loss: 0.2190 - mae: 0.3622 - rmse: 0.4659 - smape: 0.7027 - val_ia: 0.7263 - val_loss: 0.1122 - val_mae: 0.2597 - val_rmse: 0.3212 - val_smape: 0.5885

Epoch 21/128

574/574 - 6s - 10ms/step - ia: 0.7699 - loss: 0.2089 - mae: 0.3526 - rmse: 0.4544 - smape: 0.6862 - val_ia: 0.7322 - val_loss: 0.1078 - val_mae: 0.2564 - val_rmse: 0.3156 - val_smape: 0.5878

Epoch 22/128

574/574 - 6s - 10ms/step - ia: 0.7790 - loss: 0.1966 - mae: 0.3432 - rmse: 0.4409 - smape: 0.6695 - val_ia: 0.7356 - val_loss: 0.1055 - val_mae: 0.2556 - val_rmse: 0.3127 - val_smape: 0.5900

Epoch 23/128

574/574 - 6s - 10ms/step - ia: 0.7842 - loss: 0.1904 - mae: 0.3376 - rmse: 0.4339 - smape: 0.6573 - val_ia: 0.7374 - val_loss: 0.1046 - val_mae: 0.2561 - val_rmse: 0.3117 - val_smape: 0.5937

Epoch 24/128

574/574 - 6s - 10ms/step - ia: 0.7885 - loss: 0.1861 - mae: 0.3337 - rmse: 0.4290 - smape: 0.6480 - val_ia: 0.7385 - val_loss: 0.1046 - val_mae: 0.2572 - val_rmse: 0.3117 - val_smape: 0.5973

Epoch 25/128

574/574 - 6s - 10ms/step - ia: 0.7921 - loss: 0.1821 - mae: 0.3299 - rmse: 0.4245 - smape: 0.6417 - val_ia: 0.7389 - val_loss: 0.1050 - val_mae: 0.2587 - val_rmse: 0.3122 - val_smape: 0.6010

Epoch 26/128

574/574 - 5s - 9ms/step - ia: 0.7948 - loss: 0.1764 - mae: 0.3260 - rmse: 0.4177 - smape: 0.6343 - val_ia: 0.7392 - val_loss: 0.1056 - val_mae: 0.2600 - val_rmse: 0.3128 - val_smape: 0.6044

Epoch 27/128

574/574 - 6s - 10ms/step - ia: 0.7983 - loss: 0.1733 - mae: 0.3219 - rmse: 0.4142 - smape: 0.6261 - val_ia: 0.7394 - val_loss: 0.1062 - val_mae: 0.2611 - val_rmse: 0.3133 - val_smape: 0.6071

Epoch 28/128

574/574 - 6s - 10ms/step - ia: 0.8025 - loss: 0.1663 - mae: 0.3159 - rmse: 0.4057 - smape: 0.6168 - val_ia: 0.7396 - val_loss: 0.1066 - val_mae: 0.2619 - val_rmse: 0.3134 - val_smape: 0.6092

Epoch 29/128

574/574 - 6s - 10ms/step - ia: 0.8060 - loss: 0.1617 - mae: 0.3107 - rmse: 0.3998 - smape: 0.6091 - val_ia: 0.7399 - val_loss: 0.1067 - val_mae: 0.2622 - val_rmse: 0.3132 - val_smape: 0.6106

Epoch 30/128

574/574 - 5s - 9ms/step - ia: 0.8068 - loss: 0.1601 - mae: 0.3097 - rmse: 0.3978 - smape: 0.6089 - val_ia: 0.7406 - val_loss: 0.1067 - val_mae: 0.2623 - val_rmse: 0.3127 - val_smape: 0.6115

Epoch 31/128

574/574 - 6s - 10ms/step - ia: 0.8099 - loss: 0.1556 - mae: 0.3048 - rmse: 0.3923 - smape: 0.6025 - val_ia: 0.7414 - val_loss: 0.1065 - val_mae: 0.2621 - val_rmse: 0.3119 - val_smape: 0.6118

Epoch 32/128

574/574 - 6s - 10ms/step - ia: 0.8114 - loss: 0.1529 - mae: 0.3029 - rmse: 0.3888 - smape: 0.5995 - val_ia: 0.7421 - val_loss: 0.1060 - val_mae: 0.2615 - val_rmse: 0.3107 - val_smape: 0.6113

Epoch 33/128

574/574 - 9s - 17ms/step - ia: 0.8136 - loss: 0.1499 - mae: 0.2996 - rmse: 0.3853 - smape: 0.5923 - val_ia: 0.7428 - val_loss: 0.1056 - val_mae: 0.2611 - val_rmse: 0.3097 - val_smape: 0.6111

Epoch 34/128

574/574 - 4s - 6ms/step - ia: 0.8155 - loss: 0.1469 - mae: 0.2961 - rmse: 0.3809 - smape: 0.5883 - val_ia: 0.7439 - val_loss: 0.1049 - val_mae: 0.2602 - val_rmse: 0.3083 - val_smape: 0.6102

Epoch 35/128

574/574 - 4s - 6ms/step - ia: 0.8192 - loss: 0.1427 - mae: 0.2915 - rmse: 0.3757 - smape: 0.5814 - val_ia: 0.7445 - val_loss: 0.1045 - val_mae: 0.2595 - val_rmse: 0.3070 - val_smape: 0.6096

Epoch 36/128

574/574 - 4s - 6ms/step - ia: 0.8195 - loss: 0.1419 - mae: 0.2905 - rmse: 0.3744 - smape: 0.5766 - val_ia: 0.7455 - val_loss: 0.1037 - val_mae: 0.2585 - val_rmse: 0.3055 - val_smape: 0.6083

Epoch 37/128

574/574 - 4s - 6ms/step - ia: 0.8199 - loss: 0.1406 - mae: 0.2894 - rmse: 0.3732 - smape: 0.5783 - val_ia: 0.7462 - val_loss: 0.1034 - val_mae: 0.2579 - val_rmse: 0.3044 - val_smape: 0.6076

Epoch 38/128

574/574 - 4s - 6ms/step - ia: 0.8232 - loss: 0.1368 - mae: 0.2847 - rmse: 0.3677 - smape: 0.5696 - val_ia: 0.7472 - val_loss: 0.1026 - val_mae: 0.2569 - val_rmse: 0.3029 - val_smape: 0.6063

Epoch 39/128

574/574 - 6s - 10ms/step - ia: 0.8246 - loss: 0.1338 - mae: 0.2827 - rmse: 0.3634 - smape: 0.5662 - val_ia: 0.7482 - val_loss: 0.1018 - val_mae: 0.2557 - val_rmse: 0.3013 - val_smape: 0.6047

Epoch 40/128

574/574 - 6s - 10ms/step - ia: 0.8249 - loss: 0.1335 - mae: 0.2821 - rmse: 0.3630 - smape: 0.5654 - val_ia: 0.7495 - val_loss: 0.1008 - val_mae: 0.2544 - val_rmse: 0.2996 - val_smape: 0.6027

Epoch 41/128

574/574 - 10s - 17ms/step - ia: 0.8271 - loss: 0.1304 - mae: 0.2785 - rmse: 0.3589 - smape: 0.5636 - val_ia: 0.7508 - val_loss: 0.0999 - val_mae: 0.2530 - val_rmse: 0.2978 - val_smape: 0.6007

Epoch 42/128

574/574 - 11s - 18ms/step - ia: 0.8293 - loss: 0.1269 - mae: 0.2743 - rmse: 0.3540 - smape: 0.5577 - val_ia: 0.7517 - val_loss: 0.0992 - val_mae: 0.2520 - val_rmse: 0.2964 - val_smape: 0.5992

Epoch 43/128

574/574 - 6s - 10ms/step - ia: 0.8301 - loss: 0.1262 - mae: 0.2733 - rmse: 0.3533 - smape: 0.5520 - val_ia: 0.7530 - val_loss: 0.0982 - val_mae: 0.2507 - val_rmse: 0.2947 - val_smape: 0.5972

Epoch 44/128

574/574 - 5s - 10ms/step - ia: 0.8311 - loss: 0.1245 - mae: 0.2723 - rmse: 0.3509 - smape: 0.5484 - val_ia: 0.7543 - val_loss: 0.0973 - val_mae: 0.2495 - val_rmse: 0.2931 - val_smape: 0.5953

Epoch 45/128

574/574 - 11s - 19ms/step - ia: 0.8335 - loss: 0.1212 - mae: 0.2684 - rmse: 0.3461 - smape: 0.5481 - val_ia: 0.7551 - val_loss: 0.0966 - val_mae: 0.2484 - val_rmse: 0.2916 - val_smape: 0.5936

Epoch 46/128

574/574 - 6s - 10ms/step - ia: 0.8339 - loss: 0.1207 - mae: 0.2677 - rmse: 0.3454 - smape: 0.5454 - val_ia: 0.7564 - val_loss: 0.0955 - val_mae: 0.2470 - val_rmse: 0.2898 - val_smape: 0.5914

Epoch 47/128

574/574 - 10s - 18ms/step - ia: 0.8363 - loss: 0.1176 - mae: 0.2639 - rmse: 0.3411 - smape: 0.5391 - val_ia: 0.7575 - val_loss: 0.0947 - val_mae: 0.2458 - val_rmse: 0.2882 - val_smape: 0.5894

Epoch 48/128

574/574 - 6s - 10ms/step - ia: 0.8371 - loss: 0.1160 - mae: 0.2620 - rmse: 0.3386 - smape: 0.5348 - val_ia: 0.7590 - val_loss: 0.0935 - val_mae: 0.2443 - val_rmse: 0.2864 - val_smape: 0.5870

Epoch 49/128

574/574 - 6s - 10ms/step - ia: 0.8383 - loss: 0.1145 - mae: 0.2603 - rmse: 0.3362 - smape: 0.5308 - val_ia: 0.7603 - val_loss: 0.0926 - val_mae: 0.2430 - val_rmse: 0.2847 - val_smape: 0.5849

Epoch 50/128

574/574 - 6s - 10ms/step - ia: 0.8398 - loss: 0.1133 - mae: 0.2580 - rmse: 0.3342 - smape: 0.5273 - val_ia: 0.7613 - val_loss: 0.0917 - val_mae: 0.2417 - val_rmse: 0.2832 - val_smape: 0.5829

Epoch 51/128

574/574 - 11s - 18ms/step - ia: 0.8403 - loss: 0.1118 - mae: 0.2571 - rmse: 0.3324 - smape: 0.5306 - val_ia: 0.7624 - val_loss: 0.0908 - val_mae: 0.2405 - val_rmse: 0.2816 - val_smape: 0.5808

Epoch 52/128

574/574 - 6s - 10ms/step - ia: 0.8427 - loss: 0.1090 - mae: 0.2540 - rmse: 0.3281 - smape: 0.5252 - val_ia: 0.7634 - val_loss: 0.0898 - val_mae: 0.2391 - val_rmse: 0.2799 - val_smape: 0.5787

Epoch 53/128

574/574 - 10s - 18ms/step - ia: 0.8431 - loss: 0.1087 - mae: 0.2529 - rmse: 0.3274 - smape: 0.5210 - val_ia: 0.7649 - val_loss: 0.0887 - val_mae: 0.2376 - val_rmse: 0.2781 - val_smape: 0.5764

Epoch 54/128

574/574 - 6s - 10ms/step - ia: 0.8454 - loss: 0.1054 - mae: 0.2495 - rmse: 0.3223 - smape: 0.5171 - val_ia: 0.7658 - val_loss: 0.0878 - val_mae: 0.2364 - val_rmse: 0.2766 - val_smape: 0.5745

Epoch 55/128

574/574 - 6s - 10ms/step - ia: 0.8459 - loss: 0.1035 - mae: 0.2478 - rmse: 0.3201 - smape: 0.5159 - val_ia: 0.7672 - val_loss: 0.0867 - val_mae: 0.2349 - val_rmse: 0.2747 - val_smape: 0.5721

Epoch 56/128

574/574 - 6s - 10ms/step - ia: 0.8470 - loss: 0.1033 - mae: 0.2464 - rmse: 0.3194 - smape: 0.5100 - val_ia: 0.7687 - val_loss: 0.0856 - val_mae: 0.2333 - val_rmse: 0.2729 - val_smape: 0.5697

Epoch 57/128

574/574 - 10s - 18ms/step - ia: 0.8474 - loss: 0.1029 - mae: 0.2460 - rmse: 0.3186 - smape: 0.5107 - val_ia: 0.7700 - val_loss: 0.0845 - val_mae: 0.2318 - val_rmse: 0.2710 - val_smape: 0.5671

Epoch 58/128

574/574 - 6s - 10ms/step - ia: 0.8486 - loss: 0.1011 - mae: 0.2439 - rmse: 0.3159 - smape: 0.5087 - val_ia: 0.7715 - val_loss: 0.0832 - val_mae: 0.2300 - val_rmse: 0.2690 - val_smape: 0.5645

Epoch 59/128

574/574 - 6s - 10ms/step - ia: 0.8490 - loss: 0.1005 - mae: 0.2432 - rmse: 0.3148 - smape: 0.5045 - val_ia: 0.7724 - val_loss: 0.0824 - val_mae: 0.2288 - val_rmse: 0.2676 - val_smape: 0.5627

Epoch 60/128

574/574 - 5s - 8ms/step - ia: 0.8504 - loss: 0.0984 - mae: 0.2409 - rmse: 0.3117 - smape: 0.5038 - val_ia: 0.7741 - val_loss: 0.0811 - val_mae: 0.2271 - val_rmse: 0.2655 - val_smape: 0.5602

Epoch 61/128

574/574 - 4s - 6ms/step - ia: 0.8517 - loss: 0.0970 - mae: 0.2387 - rmse: 0.3095 - smape: 0.4971 - val_ia: 0.7753 - val_loss: 0.0802 - val_mae: 0.2258 - val_rmse: 0.2640 - val_smape: 0.5583

Epoch 62/128

574/574 - 5s - 9ms/step - ia: 0.8543 - loss: 0.0937 - mae: 0.2350 - rmse: 0.3041 - smape: 0.4923 - val_ia: 0.7767 - val_loss: 0.0791 - val_mae: 0.2243 - val_rmse: 0.2622 - val_smape: 0.5560

Epoch 63/128

574/574 - 4s - 6ms/step - ia: 0.8542 - loss: 0.0941 - mae: 0.2353 - rmse: 0.3049 - smape: 0.4903 - val_ia: 0.7779 - val_loss: 0.0780 - val_mae: 0.2228 - val_rmse: 0.2604 - val_smape: 0.5536

Epoch 64/128

574/574 - 4s - 6ms/step - ia: 0.8544 - loss: 0.0931 - mae: 0.2345 - rmse: 0.3036 - smape: 0.4917 - val_ia: 0.7793 - val_loss: 0.0770 - val_mae: 0.2213 - val_rmse: 0.2586 - val_smape: 0.5512

Epoch 65/128

574/574 - 6s - 10ms/step - ia: 0.8552 - loss: 0.0927 - mae: 0.2333 - rmse: 0.3028 - smape: 0.4887 - val_ia: 0.7807 - val_loss: 0.0758 - val_mae: 0.2196 - val_rmse: 0.2567 - val_smape: 0.5483

Epoch 66/128

574/574 - 6s - 10ms/step - ia: 0.8566 - loss: 0.0909 - mae: 0.2310 - rmse: 0.2995 - smape: 0.4859 - val_ia: 0.7826 - val_loss: 0.0746 - val_mae: 0.2178 - val_rmse: 0.2546 - val_smape: 0.5454

Epoch 67/128

574/574 - 10s - 18ms/step - ia: 0.8572 - loss: 0.0900 - mae: 0.2305 - rmse: 0.2983 - smape: 0.4863 - val_ia: 0.7838 - val_loss: 0.0734 - val_mae: 0.2161 - val_rmse: 0.2527 - val_smape: 0.5425

Epoch 68/128

574/574 - 6s - 10ms/step - ia: 0.8580 - loss: 0.0902 - mae: 0.2293 - rmse: 0.2983 - smape: 0.4830 - val_ia: 0.7852 - val_loss: 0.0724 - val_mae: 0.2146 - val_rmse: 0.2510 - val_smape: 0.5402

Epoch 69/128

574/574 - 6s - 10ms/step - ia: 0.8588 - loss: 0.0882 - mae: 0.2275 - rmse: 0.2952 - smape: 0.4804 - val_ia: 0.7862 - val_loss: 0.0716 - val_mae: 0.2135 - val_rmse: 0.2496 - val_smape: 0.5381

Epoch 70/128

574/574 - 10s - 18ms/step - ia: 0.8597 - loss: 0.0875 - mae: 0.2261 - rmse: 0.2938 - smape: 0.4753 - val_ia: 0.7872 - val_loss: 0.0706 - val_mae: 0.2120 - val_rmse: 0.2479 - val_smape: 0.5355

Epoch 71/128

574/574 - 7s - 12ms/step - ia: 0.8608 - loss: 0.0862 - mae: 0.2243 - rmse: 0.2917 - smape: 0.4744 - val_ia: 0.7891 - val_loss: 0.0692 - val_mae: 0.2099 - val_rmse: 0.2456 - val_smape: 0.5320

Epoch 72/128

574/574 - 11s - 19ms/step - ia: 0.8605 - loss: 0.0859 - mae: 0.2248 - rmse: 0.2912 - smape: 0.4771 - val_ia: 0.7907 - val_loss: 0.0680 - val_mae: 0.2082 - val_rmse: 0.2436 - val_smape: 0.5290

Epoch 73/128

574/574 - 6s - 11ms/step - ia: 0.8616 - loss: 0.0853 - mae: 0.2231 - rmse: 0.2900 - smape: 0.4697 - val_ia: 0.7923 - val_loss: 0.0670 - val_mae: 0.2067 - val_rmse: 0.2419 - val_smape: 0.5264

Epoch 74/128

574/574 - 10s - 18ms/step - ia: 0.8619 - loss: 0.0843 - mae: 0.2223 - rmse: 0.2885 - smape: 0.4695 - val_ia: 0.7934 - val_loss: 0.0662 - val_mae: 0.2054 - val_rmse: 0.2404 - val_smape: 0.5241

Epoch 75/128

574/574 - 10s - 18ms/step - ia: 0.8636 - loss: 0.0825 - mae: 0.2200 - rmse: 0.2854 - smape: 0.4643 - val_ia: 0.7946 - val_loss: 0.0653 - val_mae: 0.2041 - val_rmse: 0.2388 - val_smape: 0.5216

Epoch 76/128

574/574 - 5s - 9ms/step - ia: 0.8626 - loss: 0.0841 - mae: 0.2216 - rmse: 0.2880 - smape: 0.4675 - val_ia: 0.7955 - val_loss: 0.0645 - val_mae: 0.2029 - val_rmse: 0.2374 - val_smape: 0.5195

Epoch 77/128

574/574 - 6s - 10ms/step - ia: 0.8655 - loss: 0.0805 - mae: 0.2170 - rmse: 0.2820 - smape: 0.4604 - val_ia: 0.7973 - val_loss: 0.0630 - val_mae: 0.2007 - val_rmse: 0.2349 - val_smape: 0.5154

Epoch 78/128

574/574 - 6s - 10ms/step - ia: 0.8665 - loss: 0.0793 - mae: 0.2153 - rmse: 0.2800 - smape: 0.4579 - val_ia: 0.7986 - val_loss: 0.0621 - val_mae: 0.1993 - val_rmse: 0.2333 - val_smape: 0.5129

Epoch 79/128

574/574 - 6s - 10ms/step - ia: 0.8664 - loss: 0.0798 - mae: 0.2158 - rmse: 0.2804 - smape: 0.4571 - val_ia: 0.8003 - val_loss: 0.0610 - val_mae: 0.1975 - val_rmse: 0.2313 - val_smape: 0.5097

Epoch 80/128

574/574 - 6s - 10ms/step - ia: 0.8672 - loss: 0.0792 - mae: 0.2145 - rmse: 0.2796 - smape: 0.4569 - val_ia: 0.8015 - val_loss: 0.0601 - val_mae: 0.1959 - val_rmse: 0.2295 - val_smape: 0.5067

Epoch 81/128

574/574 - 6s - 10ms/step - ia: 0.8673 - loss: 0.0788 - mae: 0.2138 - rmse: 0.2789 - smape: 0.4576 - val_ia: 0.8033 - val_loss: 0.0590 - val_mae: 0.1942 - val_rmse: 0.2276 - val_smape: 0.5038

Epoch 82/128

574/574 - 6s - 10ms/step - ia: 0.8672 - loss: 0.0789 - mae: 0.2145 - rmse: 0.2790 - smape: 0.4544 - val_ia: 0.8045 - val_loss: 0.0582 - val_mae: 0.1930 - val_rmse: 0.2262 - val_smape: 0.5016

Epoch 83/128

574/574 - 10s - 18ms/step - ia: 0.8684 - loss: 0.0769 - mae: 0.2121 - rmse: 0.2758 - smape: 0.4526 - val_ia: 0.8056 - val_loss: 0.0573 - val_mae: 0.1915 - val_rmse: 0.2245 - val_smape: 0.4987

Epoch 84/128

574/574 - 10s - 18ms/step - ia: 0.8693 - loss: 0.0759 - mae: 0.2109 - rmse: 0.2735 - smape: 0.4510 - val_ia: 0.8068 - val_loss: 0.0564 - val_mae: 0.1902 - val_rmse: 0.2228 - val_smape: 0.4959

Epoch 85/128

574/574 - 6s - 10ms/step - ia: 0.8708 - loss: 0.0748 - mae: 0.2086 - rmse: 0.2718 - smape: 0.4468 - val_ia: 0.8085 - val_loss: 0.0554 - val_mae: 0.1884 - val_rmse: 0.2209 - val_smape: 0.4926

Epoch 86/128

574/574 - 10s - 17ms/step - ia: 0.8714 - loss: 0.0739 - mae: 0.2076 - rmse: 0.2700 - smape: 0.4457 - val_ia: 0.8099 - val_loss: 0.0543 - val_mae: 0.1867 - val_rmse: 0.2190 - val_smape: 0.4892

Epoch 87/128

574/574 - 11s - 19ms/step - ia: 0.8720 - loss: 0.0732 - mae: 0.2063 - rmse: 0.2686 - smape: 0.4409 - val_ia: 0.8113 - val_loss: 0.0534 - val_mae: 0.1852 - val_rmse: 0.2172 - val_smape: 0.4862

Epoch 88/128

574/574 - 10s - 17ms/step - ia: 0.8726 - loss: 0.0728 - mae: 0.2056 - rmse: 0.2681 - smape: 0.4403 - val_ia: 0.8127 - val_loss: 0.0526 - val_mae: 0.1837 - val_rmse: 0.2156 - val_smape: 0.4833

Epoch 89/128

574/574 - 6s - 10ms/step - ia: 0.8730 - loss: 0.0725 - mae: 0.2051 - rmse: 0.2671 - smape: 0.4384 - val_ia: 0.8143 - val_loss: 0.0516 - val_mae: 0.1819 - val_rmse: 0.2136 - val_smape: 0.4799

Epoch 90/128

574/574 - 10s - 18ms/step - ia: 0.8735 - loss: 0.0713 - mae: 0.2039 - rmse: 0.2656 - smape: 0.4377 - val_ia: 0.8152 - val_loss: 0.0510 - val_mae: 0.1809 - val_rmse: 0.2124 - val_smape: 0.4778

Epoch 91/128

574/574 - 8s - 14ms/step - ia: 0.8735 - loss: 0.0720 - mae: 0.2043 - rmse: 0.2664 - smape: 0.4390 - val_ia: 0.8167 - val_loss: 0.0501 - val_mae: 0.1794 - val_rmse: 0.2107 - val_smape: 0.4748

Epoch 92/128

574/574 - 4s - 6ms/step - ia: 0.8744 - loss: 0.0703 - mae: 0.2028 - rmse: 0.2635 - smape: 0.4338 - val_ia: 0.8184 - val_loss: 0.0492 - val_mae: 0.1777 - val_rmse: 0.2088 - val_smape: 0.4717

Epoch 93/128

574/574 - 4s - 6ms/step - ia: 0.8746 - loss: 0.0708 - mae: 0.2026 - rmse: 0.2645 - smape: 0.4334 - val_ia: 0.8196 - val_loss: 0.0484 - val_mae: 0.1764 - val_rmse: 0.2073 - val_smape: 0.4689

Epoch 94/128

574/574 - 4s - 6ms/step - ia: 0.8762 - loss: 0.0690 - mae: 0.1998 - rmse: 0.2611 - smape: 0.4291 - val_ia: 0.8210 - val_loss: 0.0475 - val_mae: 0.1746 - val_rmse: 0.2054 - val_smape: 0.4652

Epoch 95/128

574/574 - 4s - 7ms/step - ia: 0.8760 - loss: 0.0693 - mae: 0.1999 - rmse: 0.2616 - smape: 0.4295 - val_ia: 0.8223 - val_loss: 0.0467 - val_mae: 0.1732 - val_rmse: 0.2039 - val_smape: 0.4626

Epoch 96/128

574/574 - 7s - 12ms/step - ia: 0.8771 - loss: 0.0686 - mae: 0.1988 - rmse: 0.2600 - smape: 0.4287 - val_ia: 0.8231 - val_loss: 0.0461 - val_mae: 0.1723 - val_rmse: 0.2027 - val_smape: 0.4604

Epoch 97/128

574/574 - 6s - 10ms/step - ia: 0.8768 - loss: 0.0687 - mae: 0.1989 - rmse: 0.2601 - smape: 0.4256 - val_ia: 0.8247 - val_loss: 0.0452 - val_mae: 0.1706 - val_rmse: 0.2009 - val_smape: 0.4571

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 24s - 83ms/step - ia: 0.3144 - loss: 1.9898 - mae: 1.1578 - rmse: 1.4083 - smape: 1.4121 - val_ia: 0.3193 - val_loss: 1.6095 - val_mae: 1.0783 - val_rmse: 1.2418 - val_smape: 1.4454

Epoch 2/128

287/287 - 9s - 31ms/step - ia: 0.3045 - loss: 1.7093 - mae: 1.0714 - rmse: 1.3051 - smape: 1.4256 - val_ia: 0.3076 - val_loss: 1.3303 - val_mae: 0.9673 - val_rmse: 1.1299 - val_smape: 1.4379

Epoch 3/128

287/287 - 6s - 20ms/step - ia: 0.2901 - loss: 1.5407 - mae: 1.0160 - rmse: 1.2393 - smape: 1.4467 - val_ia: 0.2822 - val_loss: 1.1369 - val_mae: 0.8877 - val_rmse: 1.0472 - val_smape: 1.4538

Epoch 4/128

287/287 - 6s - 20ms/step - ia: 0.2842 - loss: 1.4084 - mae: 0.9726 - rmse: 1.1851 - smape: 1.4559 - val_ia: 0.2517 - val_loss: 1.0092 - val_mae: 0.8349 - val_rmse: 0.9898 - val_smape: 1.4980

Epoch 5/128

287/287 - 6s - 20ms/step - ia: 0.2750 - loss: 1.3495 - mae: 0.9543 - rmse: 1.1602 - smape: 1.4694 - val_ia: 0.2305 - val_loss: 0.9265 - val_mae: 0.8005 - val_rmse: 0.9513 - val_smape: 1.5694

Epoch 6/128

287/287 - 6s - 20ms/step - ia: 0.2772 - loss: 1.2943 - mae: 0.9328 - rmse: 1.1359 - smape: 1.4656 - val_ia: 0.2243 - val_loss: 0.8777 - val_mae: 0.7798 - val_rmse: 0.9279 - val_smape: 1.6529

Epoch 7/128

287/287 - 4s - 15ms/step - ia: 0.2784 - loss: 1.2650 - mae: 0.9221 - rmse: 1.1229 - smape: 1.4655 - val_ia: 0.2246 - val_loss: 0.8484 - val_mae: 0.7668 - val_rmse: 0.9134 - val_smape: 1.7344

Epoch 8/128

287/287 - 4s - 14ms/step - ia: 0.2795 - loss: 1.2405 - mae: 0.9139 - rmse: 1.1122 - smape: 1.4641 - val_ia: 0.2290 - val_loss: 0.8295 - val_mae: 0.7580 - val_rmse: 0.9039 - val_smape: 1.8017

Epoch 9/128

287/287 - 4s - 13ms/step - ia: 0.2808 - loss: 1.2305 - mae: 0.9102 - rmse: 1.1075 - smape: 1.4618 - val_ia: 0.2338 - val_loss: 0.8161 - val_mae: 0.7517 - val_rmse: 0.8969 - val_smape: 1.8336

Epoch 10/128

287/287 - 5s - 18ms/step - ia: 0.2836 - loss: 1.2123 - mae: 0.9020 - rmse: 1.0994 - smape: 1.4586 - val_ia: 0.2388 - val_loss: 0.8053 - val_mae: 0.7464 - val_rmse: 0.8911 - val_smape: 1.8376

Epoch 11/128

287/287 - 11s - 38ms/step - ia: 0.2832 - loss: 1.2126 - mae: 0.9006 - rmse: 1.0995 - smape: 1.4576 - val_ia: 0.2436 - val_loss: 0.7954 - val_mae: 0.7416 - val_rmse: 0.8858 - val_smape: 1.8243

Epoch 12/128

287/287 - 10s - 34ms/step - ia: 0.2889 - loss: 1.1791 - mae: 0.8909 - rmse: 1.0845 - smape: 1.4521 - val_ia: 0.2480 - val_loss: 0.7871 - val_mae: 0.7376 - val_rmse: 0.8812 - val_smape: 1.8065

Epoch 13/128

287/287 - 11s - 38ms/step - ia: 0.2880 - loss: 1.1756 - mae: 0.8879 - rmse: 1.0827 - smape: 1.4509 - val_ia: 0.2528 - val_loss: 0.7779 - val_mae: 0.7332 - val_rmse: 0.8761 - val_smape: 1.7863

Epoch 14/128

287/287 - 6s - 20ms/step - ia: 0.2897 - loss: 1.1557 - mae: 0.8824 - rmse: 1.0734 - smape: 1.4533 - val_ia: 0.2572 - val_loss: 0.7695 - val_mae: 0.7291 - val_rmse: 0.8713 - val_smape: 1.7672

Epoch 15/128

287/287 - 6s - 20ms/step - ia: 0.2968 - loss: 1.1322 - mae: 0.8710 - rmse: 1.0622 - smape: 1.4400 - val_ia: 0.2620 - val_loss: 0.7606 - val_mae: 0.7248 - val_rmse: 0.8662 - val_smape: 1.7472

Epoch 16/128

287/287 - 5s - 16ms/step - ia: 0.2942 - loss: 1.1186 - mae: 0.8692 - rmse: 1.0561 - smape: 1.4472 - val_ia: 0.2676 - val_loss: 0.7503 - val_mae: 0.7196 - val_rmse: 0.8604 - val_smape: 1.7240

Epoch 17/128

287/287 - 4s - 14ms/step - ia: 0.3011 - loss: 1.0967 - mae: 0.8594 - rmse: 1.0457 - smape: 1.4364 - val_ia: 0.2728 - val_loss: 0.7407 - val_mae: 0.7150 - val_rmse: 0.8549 - val_smape: 1.7035

Epoch 18/128

287/287 - 5s - 19ms/step - ia: 0.3036 - loss: 1.0770 - mae: 0.8530 - rmse: 1.0361 - smape: 1.4333 - val_ia: 0.2784 - val_loss: 0.7306 - val_mae: 0.7099 - val_rmse: 0.8490 - val_smape: 1.6816

Epoch 19/128

287/287 - 4s - 15ms/step - ia: 0.3094 - loss: 1.0579 - mae: 0.8440 - rmse: 1.0269 - smape: 1.4250 - val_ia: 0.2848 - val_loss: 0.7191 - val_mae: 0.7041 - val_rmse: 0.8423 - val_smape: 1.6569

Epoch 20/128

287/287 - 6s - 20ms/step - ia: 0.3158 - loss: 1.0435 - mae: 0.8370 - rmse: 1.0201 - smape: 1.4168 - val_ia: 0.2916 - val_loss: 0.7072 - val_mae: 0.6981 - val_rmse: 0.8353 - val_smape: 1.6313

Epoch 21/128

287/287 - 6s - 20ms/step - ia: 0.3175 - loss: 1.0217 - mae: 0.8289 - rmse: 1.0092 - smape: 1.4107 - val_ia: 0.2984 - val_loss: 0.6955 - val_mae: 0.6921 - val_rmse: 0.8283 - val_smape: 1.6074

Epoch 22/128

287/287 - 10s - 36ms/step - ia: 0.3214 - loss: 1.0087 - mae: 0.8253 - rmse: 1.0028 - smape: 1.4090 - val_ia: 0.3058 - val_loss: 0.6830 - val_mae: 0.6857 - val_rmse: 0.8209 - val_smape: 1.5821

Epoch 23/128

287/287 - 5s - 19ms/step - ia: 0.3309 - loss: 0.9788 - mae: 0.8120 - rmse: 0.9880 - smape: 1.3971 - val_ia: 0.3135 - val_loss: 0.6701 - val_mae: 0.6790 - val_rmse: 0.8131 - val_smape: 1.5568

Epoch 24/128

287/287 - 11s - 37ms/step - ia: 0.3389 - loss: 0.9538 - mae: 0.8007 - rmse: 0.9751 - smape: 1.3819 - val_ia: 0.3212 - val_loss: 0.6575 - val_mae: 0.6725 - val_rmse: 0.8053 - val_smape: 1.5328

Epoch 25/128

287/287 - 6s - 20ms/step - ia: 0.3444 - loss: 0.9366 - mae: 0.7937 - rmse: 0.9664 - smape: 1.3740 - val_ia: 0.3300 - val_loss: 0.6433 - val_mae: 0.6650 - val_rmse: 0.7965 - val_smape: 1.5055

Epoch 26/128

287/287 - 6s - 20ms/step - ia: 0.3497 - loss: 0.9175 - mae: 0.7860 - rmse: 0.9564 - smape: 1.3694 - val_ia: 0.3397 - val_loss: 0.6280 - val_mae: 0.6567 - val_rmse: 0.7870 - val_smape: 1.4761

Epoch 27/128

287/287 - 6s - 19ms/step - ia: 0.3622 - loss: 0.8912 - mae: 0.7730 - rmse: 0.9423 - smape: 1.3518 - val_ia: 0.3493 - val_loss: 0.6130 - val_mae: 0.6486 - val_rmse: 0.7775 - val_smape: 1.4482

Epoch 28/128

287/287 - 6s - 20ms/step - ia: 0.3710 - loss: 0.8730 - mae: 0.7641 - rmse: 0.9329 - smape: 1.3386 - val_ia: 0.3601 - val_loss: 0.5965 - val_mae: 0.6394 - val_rmse: 0.7669 - val_smape: 1.4177

Epoch 29/128

287/287 - 6s - 20ms/step - ia: 0.3792 - loss: 0.8511 - mae: 0.7551 - rmse: 0.9210 - smape: 1.3263 - val_ia: 0.3708 - val_loss: 0.5806 - val_mae: 0.6306 - val_rmse: 0.7565 - val_smape: 1.3890

Epoch 30/128

287/287 - 6s - 20ms/step - ia: 0.3919 - loss: 0.8190 - mae: 0.7421 - rmse: 0.9036 - smape: 1.3115 - val_ia: 0.3828 - val_loss: 0.5629 - val_mae: 0.6205 - val_rmse: 0.7449 - val_smape: 1.3573

Epoch 31/128

287/287 - 6s - 20ms/step - ia: 0.4003 - loss: 0.8009 - mae: 0.7324 - rmse: 0.8937 - smape: 1.3004 - val_ia: 0.3959 - val_loss: 0.5442 - val_mae: 0.6094 - val_rmse: 0.7324 - val_smape: 1.3244

Epoch 32/128

287/287 - 10s - 36ms/step - ia: 0.4145 - loss: 0.7756 - mae: 0.7207 - rmse: 0.8792 - smape: 1.2767 - val_ia: 0.4084 - val_loss: 0.5269 - val_mae: 0.5995 - val_rmse: 0.7206 - val_smape: 1.2940

Epoch 33/128

287/287 - 11s - 39ms/step - ia: 0.4294 - loss: 0.7444 - mae: 0.7048 - rmse: 0.8615 - smape: 1.2553 - val_ia: 0.4224 - val_loss: 0.5078 - val_mae: 0.5880 - val_rmse: 0.7073 - val_smape: 1.2613

Epoch 34/128

287/287 - 10s - 33ms/step - ia: 0.4426 - loss: 0.7204 - mae: 0.6929 - rmse: 0.8473 - smape: 1.2375 - val_ia: 0.4365 - val_loss: 0.4893 - val_mae: 0.5769 - val_rmse: 0.6942 - val_smape: 1.2284

Epoch 35/128

287/287 - 6s - 21ms/step - ia: 0.4515 - loss: 0.7024 - mae: 0.6839 - rmse: 0.8367 - smape: 1.2254 - val_ia: 0.4520 - val_loss: 0.4691 - val_mae: 0.5642 - val_rmse: 0.6797 - val_smape: 1.1953

Epoch 36/128

287/287 - 6s - 20ms/step - ia: 0.4688 - loss: 0.6747 - mae: 0.6691 - rmse: 0.8200 - smape: 1.1974 - val_ia: 0.4679 - val_loss: 0.4489 - val_mae: 0.5512 - val_rmse: 0.6648 - val_smape: 1.1622

Epoch 37/128

287/287 - 6s - 21ms/step - ia: 0.4871 - loss: 0.6445 - mae: 0.6526 - rmse: 0.8016 - smape: 1.1721 - val_ia: 0.4844 - val_loss: 0.4285 - val_mae: 0.5377 - val_rmse: 0.6494 - val_smape: 1.1297

Epoch 38/128

287/287 - 6s - 20ms/step - ia: 0.5019 - loss: 0.6210 - mae: 0.6395 - rmse: 0.7868 - smape: 1.1532 - val_ia: 0.5008 - val_loss: 0.4089 - val_mae: 0.5247 - val_rmse: 0.6342 - val_smape: 1.0970

Epoch 39/128

287/287 - 6s - 20ms/step - ia: 0.5126 - loss: 0.6050 - mae: 0.6315 - rmse: 0.7767 - smape: 1.1390 - val_ia: 0.5175 - val_loss: 0.3895 - val_mae: 0.5113 - val_rmse: 0.6189 - val_smape: 1.0650

Epoch 40/128

287/287 - 6s - 20ms/step - ia: 0.5326 - loss: 0.5702 - mae: 0.6118 - rmse: 0.7537 - smape: 1.1080 - val_ia: 0.5349 - val_loss: 0.3700 - val_mae: 0.4975 - val_rmse: 0.6031 - val_smape: 1.0341

Epoch 41/128

287/287 - 6s - 20ms/step - ia: 0.5454 - loss: 0.5514 - mae: 0.6008 - rmse: 0.7413 - smape: 1.0882 - val_ia: 0.5521 - val_loss: 0.3514 - val_mae: 0.4842 - val_rmse: 0.5876 - val_smape: 1.0031

Epoch 42/128

287/287 - 10s - 35ms/step - ia: 0.5579 - loss: 0.5334 - mae: 0.5913 - rmse: 0.7291 - smape: 1.0707 - val_ia: 0.5707 - val_loss: 0.3325 - val_mae: 0.4695 - val_rmse: 0.5715 - val_smape: 0.9752

Epoch 43/128

287/287 - 11s - 38ms/step - ia: 0.5705 - loss: 0.5147 - mae: 0.5810 - rmse: 0.7161 - smape: 1.0535 - val_ia: 0.5876 - val_loss: 0.3152 - val_mae: 0.4564 - val_rmse: 0.5564 - val_smape: 0.9462

Epoch 44/128

287/287 - 6s - 20ms/step - ia: 0.5896 - loss: 0.4862 - mae: 0.5624 - rmse: 0.6961 - smape: 1.0240 - val_ia: 0.6052 - val_loss: 0.2983 - val_mae: 0.4425 - val_rmse: 0.5412 - val_smape: 0.9201

Epoch 45/128

287/287 - 10s - 34ms/step - ia: 0.5989 - loss: 0.4746 - mae: 0.5559 - rmse: 0.6879 - smape: 1.0116 - val_ia: 0.6219 - val_loss: 0.2829 - val_mae: 0.4296 - val_rmse: 0.5269 - val_smape: 0.8953

Epoch 46/128

287/287 - 11s - 38ms/step - ia: 0.6125 - loss: 0.4546 - mae: 0.5432 - rmse: 0.6730 - smape: 0.9905 - val_ia: 0.6378 - val_loss: 0.2686 - val_mae: 0.4172 - val_rmse: 0.5133 - val_smape: 0.8724

Epoch 47/128

287/287 - 6s - 20ms/step - ia: 0.6210 - loss: 0.4417 - mae: 0.5366 - rmse: 0.6633 - smape: 0.9769 - val_ia: 0.6523 - val_loss: 0.2556 - val_mae: 0.4059 - val_rmse: 0.5006 - val_smape: 0.8501

Epoch 48/128

287/287 - 6s - 20ms/step - ia: 0.6342 - loss: 0.4268 - mae: 0.5257 - rmse: 0.6521 - smape: 0.9579 - val_ia: 0.6660 - val_loss: 0.2440 - val_mae: 0.3949 - val_rmse: 0.4891 - val_smape: 0.8325

Epoch 49/128

287/287 - 4s - 15ms/step - ia: 0.6445 - loss: 0.4109 - mae: 0.5160 - rmse: 0.6398 - smape: 0.9394 - val_ia: 0.6778 - val_loss: 0.2338 - val_mae: 0.3857 - val_rmse: 0.4787 - val_smape: 0.8141

Epoch 50/128

287/287 - 4s - 14ms/step - ia: 0.6534 - loss: 0.3978 - mae: 0.5077 - rmse: 0.6295 - smape: 0.9280 - val_ia: 0.6885 - val_loss: 0.2248 - val_mae: 0.3772 - val_rmse: 0.4695 - val_smape: 0.7991

Epoch 51/128

287/287 - 4s - 14ms/step - ia: 0.6604 - loss: 0.3896 - mae: 0.5019 - rmse: 0.6232 - smape: 0.9174 - val_ia: 0.6988 - val_loss: 0.2171 - val_mae: 0.3687 - val_rmse: 0.4613 - val_smape: 0.7883

Epoch 52/128

287/287 - 6s - 20ms/step - ia: 0.6701 - loss: 0.3754 - mae: 0.4917 - rmse: 0.6115 - smape: 0.9000 - val_ia: 0.7065 - val_loss: 0.2106 - val_mae: 0.3626 - val_rmse: 0.4543 - val_smape: 0.7766

Epoch 53/128

287/287 - 6s - 21ms/step - ia: 0.6772 - loss: 0.3657 - mae: 0.4851 - rmse: 0.6036 - smape: 0.8864 - val_ia: 0.7130 - val_loss: 0.2050 - val_mae: 0.3575 - val_rmse: 0.4484 - val_smape: 0.7660

Epoch 54/128

287/287 - 10s - 35ms/step - ia: 0.6835 - loss: 0.3577 - mae: 0.4787 - rmse: 0.5970 - smape: 0.8752 - val_ia: 0.7194 - val_loss: 0.2003 - val_mae: 0.3524 - val_rmse: 0.4432 - val_smape: 0.7602

Epoch 55/128

287/287 - 6s - 20ms/step - ia: 0.6888 - loss: 0.3502 - mae: 0.4738 - rmse: 0.5907 - smape: 0.8680 - val_ia: 0.7240 - val_loss: 0.1964 - val_mae: 0.3489 - val_rmse: 0.4389 - val_smape: 0.7523

Epoch 56/128

287/287 - 10s - 36ms/step - ia: 0.6924 - loss: 0.3448 - mae: 0.4712 - rmse: 0.5859 - smape: 0.8626 - val_ia: 0.7280 - val_loss: 0.1932 - val_mae: 0.3459 - val_rmse: 0.4353 - val_smape: 0.7475

Epoch 57/128

287/287 - 10s - 36ms/step - ia: 0.6985 - loss: 0.3339 - mae: 0.4631 - rmse: 0.5768 - smape: 0.8516 - val_ia: 0.7313 - val_loss: 0.1905 - val_mae: 0.3435 - val_rmse: 0.4323 - val_smape: 0.7443

Epoch 58/128

287/287 - 5s - 19ms/step - ia: 0.7014 - loss: 0.3304 - mae: 0.4592 - rmse: 0.5737 - smape: 0.8465 - val_ia: 0.7342 - val_loss: 0.1877 - val_mae: 0.3414 - val_rmse: 0.4292 - val_smape: 0.7357

Epoch 59/128

287/287 - 6s - 21ms/step - ia: 0.7031 - loss: 0.3282 - mae: 0.4586 - rmse: 0.5718 - smape: 0.8440 - val_ia: 0.7366 - val_loss: 0.1856 - val_mae: 0.3397 - val_rmse: 0.4268 - val_smape: 0.7323

Epoch 60/128

287/287 - 10s - 36ms/step - ia: 0.7082 - loss: 0.3194 - mae: 0.4520 - rmse: 0.5640 - smape: 0.8330 - val_ia: 0.7388 - val_loss: 0.1837 - val_mae: 0.3382 - val_rmse: 0.4247 - val_smape: 0.7295

Epoch 61/128

287/287 - 10s - 35ms/step - ia: 0.7094 - loss: 0.3154 - mae: 0.4513 - rmse: 0.5606 - smape: 0.8333 - val_ia: 0.7409 - val_loss: 0.1819 - val_mae: 0.3367 - val_rmse: 0.4226 - val_smape: 0.7266

Epoch 62/128

287/287 - 6s - 20ms/step - ia: 0.7147 - loss: 0.3072 - mae: 0.4439 - rmse: 0.5531 - smape: 0.8234 - val_ia: 0.7427 - val_loss: 0.1803 - val_mae: 0.3355 - val_rmse: 0.4208 - val_smape: 0.7247

Epoch 63/128

287/287 - 11s - 37ms/step - ia: 0.7164 - loss: 0.3035 - mae: 0.4413 - rmse: 0.5500 - smape: 0.8197 - val_ia: 0.7445 - val_loss: 0.1786 - val_mae: 0.3342 - val_rmse: 0.4189 - val_smape: 0.7214

Epoch 64/128

287/287 - 6s - 20ms/step - ia: 0.7212 - loss: 0.2985 - mae: 0.4361 - rmse: 0.5454 - smape: 0.8095 - val_ia: 0.7458 - val_loss: 0.1774 - val_mae: 0.3332 - val_rmse: 0.4175 - val_smape: 0.7184

Epoch 65/128

287/287 - 5s - 17ms/step - ia: 0.7215 - loss: 0.2952 - mae: 0.4349 - rmse: 0.5421 - smape: 0.8112 - val_ia: 0.7470 - val_loss: 0.1763 - val_mae: 0.3324 - val_rmse: 0.4162 - val_smape: 0.7175

Epoch 66/128

287/287 - 5s - 18ms/step - ia: 0.7247 - loss: 0.2878 - mae: 0.4304 - rmse: 0.5354 - smape: 0.8058 - val_ia: 0.7485 - val_loss: 0.1749 - val_mae: 0.3313 - val_rmse: 0.4146 - val_smape: 0.7134

Epoch 67/128

287/287 - 5s - 16ms/step - ia: 0.7293 - loss: 0.2792 - mae: 0.4232 - rmse: 0.5274 - smape: 0.7946 - val_ia: 0.7499 - val_loss: 0.1736 - val_mae: 0.3303 - val_rmse: 0.4131 - val_smape: 0.7112

Epoch 68/128

287/287 - 5s - 18ms/step - ia: 0.7293 - loss: 0.2812 - mae: 0.4241 - rmse: 0.5291 - smape: 0.7954 - val_ia: 0.7510 - val_loss: 0.1725 - val_mae: 0.3296 - val_rmse: 0.4118 - val_smape: 0.7104

Epoch 69/128

287/287 - 5s - 18ms/step - ia: 0.7329 - loss: 0.2739 - mae: 0.4186 - rmse: 0.5224 - smape: 0.7911 - val_ia: 0.7524 - val_loss: 0.1713 - val_mae: 0.3285 - val_rmse: 0.4103 - val_smape: 0.7068

Epoch 70/128

287/287 - 5s - 18ms/step - ia: 0.7349 - loss: 0.2708 - mae: 0.4166 - rmse: 0.5194 - smape: 0.7830 - val_ia: 0.7535 - val_loss: 0.1703 - val_mae: 0.3277 - val_rmse: 0.4091 - val_smape: 0.7055

Epoch 71/128

287/287 - 5s - 19ms/step - ia: 0.7375 - loss: 0.2650 - mae: 0.4122 - rmse: 0.5137 - smape: 0.7823 - val_ia: 0.7545 - val_loss: 0.1693 - val_mae: 0.3270 - val_rmse: 0.4079 - val_smape: 0.7041

Epoch 72/128

287/287 - 10s - 36ms/step - ia: 0.7396 - loss: 0.2633 - mae: 0.4092 - rmse: 0.5121 - smape: 0.7762 - val_ia: 0.7555 - val_loss: 0.1684 - val_mae: 0.3261 - val_rmse: 0.4068 - val_smape: 0.7014

Epoch 73/128

287/287 - 10s - 35ms/step - ia: 0.7440 - loss: 0.2559 - mae: 0.4029 - rmse: 0.5049 - smape: 0.7653 - val_ia: 0.7565 - val_loss: 0.1675 - val_mae: 0.3254 - val_rmse: 0.4057 - val_smape: 0.6998

Epoch 74/128

287/287 - 5s - 18ms/step - ia: 0.7428 - loss: 0.2568 - mae: 0.4038 - rmse: 0.5057 - smape: 0.7669 - val_ia: 0.7575 - val_loss: 0.1665 - val_mae: 0.3247 - val_rmse: 0.4046 - val_smape: 0.6987

Epoch 75/128

287/287 - 5s - 18ms/step - ia: 0.7458 - loss: 0.2519 - mae: 0.4002 - rmse: 0.5008 - smape: 0.7618 - val_ia: 0.7583 - val_loss: 0.1657 - val_mae: 0.3241 - val_rmse: 0.4035 - val_smape: 0.6977

Epoch 76/128

287/287 - 5s - 18ms/step - ia: 0.7483 - loss: 0.2453 - mae: 0.3960 - rmse: 0.4943 - smape: 0.7592 - val_ia: 0.7595 - val_loss: 0.1648 - val_mae: 0.3233 - val_rmse: 0.4023 - val_smape: 0.6950

Epoch 77/128

287/287 - 5s - 18ms/step - ia: 0.7503 - loss: 0.2443 - mae: 0.3937 - rmse: 0.4932 - smape: 0.7529 - val_ia: 0.7602 - val_loss: 0.1639 - val_mae: 0.3227 - val_rmse: 0.4013 - val_smape: 0.6942

Epoch 78/128

287/287 - 5s - 17ms/step - ia: 0.7544 - loss: 0.2370 - mae: 0.3879 - rmse: 0.4859 - smape: 0.7439 - val_ia: 0.7610 - val_loss: 0.1630 - val_mae: 0.3221 - val_rmse: 0.4003 - val_smape: 0.6935

Epoch 79/128

287/287 - 5s - 19ms/step - ia: 0.7544 - loss: 0.2375 - mae: 0.3880 - rmse: 0.4863 - smape: 0.7442 - val_ia: 0.7618 - val_loss: 0.1622 - val_mae: 0.3215 - val_rmse: 0.3992 - val_smape: 0.6921

Epoch 80/128

287/287 - 5s - 18ms/step - ia: 0.7562 - loss: 0.2334 - mae: 0.3850 - rmse: 0.4822 - smape: 0.7429 - val_ia: 0.7627 - val_loss: 0.1615 - val_mae: 0.3208 - val_rmse: 0.3983 - val_smape: 0.6898

Epoch 81/128

287/287 - 5s - 18ms/step - ia: 0.7580 - loss: 0.2299 - mae: 0.3830 - rmse: 0.4784 - smape: 0.7417 - val_ia: 0.7634 - val_loss: 0.1607 - val_mae: 0.3203 - val_rmse: 0.3973 - val_smape: 0.6889

Epoch 82/128

287/287 - 5s - 19ms/step - ia: 0.7606 - loss: 0.2271 - mae: 0.3794 - rmse: 0.4755 - smape: 0.7341 - val_ia: 0.7640 - val_loss: 0.1601 - val_mae: 0.3197 - val_rmse: 0.3965 - val_smape: 0.6870

Epoch 83/128

287/287 - 5s - 18ms/step - ia: 0.7619 - loss: 0.2230 - mae: 0.3766 - rmse: 0.4713 - smape: 0.7296 - val_ia: 0.7648 - val_loss: 0.1595 - val_mae: 0.3191 - val_rmse: 0.3956 - val_smape: 0.6852

Epoch 84/128

287/287 - 10s - 36ms/step - ia: 0.7634 - loss: 0.2204 - mae: 0.3743 - rmse: 0.4686 - smape: 0.7302 - val_ia: 0.7654 - val_loss: 0.1586 - val_mae: 0.3186 - val_rmse: 0.3945 - val_smape: 0.6852

Epoch 85/128

287/287 - 5s - 18ms/step - ia: 0.7657 - loss: 0.2179 - mae: 0.3707 - rmse: 0.4657 - smape: 0.7216 - val_ia: 0.7663 - val_loss: 0.1578 - val_mae: 0.3180 - val_rmse: 0.3935 - val_smape: 0.6835

Epoch 86/128

287/287 - 5s - 18ms/step - ia: 0.7660 - loss: 0.2181 - mae: 0.3709 - rmse: 0.4661 - smape: 0.7184 - val_ia: 0.7672 - val_loss: 0.1576 - val_mae: 0.3174 - val_rmse: 0.3928 - val_smape: 0.6800

Epoch 87/128

287/287 - 5s - 18ms/step - ia: 0.7687 - loss: 0.2124 - mae: 0.3671 - rmse: 0.4600 - smape: 0.7144 - val_ia: 0.7677 - val_loss: 0.1567 - val_mae: 0.3170 - val_rmse: 0.3919 - val_smape: 0.6800

Epoch 88/128

287/287 - 5s - 18ms/step - ia: 0.7696 - loss: 0.2104 - mae: 0.3646 - rmse: 0.4577 - smape: 0.7112 - val_ia: 0.7685 - val_loss: 0.1561 - val_mae: 0.3165 - val_rmse: 0.3910 - val_smape: 0.6786

Epoch 89/128

287/287 - 5s - 18ms/step - ia: 0.7702 - loss: 0.2101 - mae: 0.3646 - rmse: 0.4573 - smape: 0.7142 - val_ia: 0.7691 - val_loss: 0.1557 - val_mae: 0.3160 - val_rmse: 0.3902 - val_smape: 0.6769

Epoch 90/128

287/287 - 5s - 17ms/step - ia: 0.7729 - loss: 0.2063 - mae: 0.3608 - rmse: 0.4532 - smape: 0.7045 - val_ia: 0.7696 - val_loss: 0.1548 - val_mae: 0.3156 - val_rmse: 0.3893 - val_smape: 0.6769

Epoch 91/128

287/287 - 5s - 18ms/step - ia: 0.7747 - loss: 0.2051 - mae: 0.3583 - rmse: 0.4520 - smape: 0.7018 - val_ia: 0.7700 - val_loss: 0.1545 - val_mae: 0.3151 - val_rmse: 0.3887 - val_smape: 0.6757

Epoch 92/128

287/287 - 5s - 18ms/step - ia: 0.7749 - loss: 0.2037 - mae: 0.3582 - rmse: 0.4504 - smape: 0.6997 - val_ia: 0.7705 - val_loss: 0.1541 - val_mae: 0.3147 - val_rmse: 0.3881 - val_smape: 0.6747

Epoch 93/128

287/287 - 5s - 18ms/step - ia: 0.7776 - loss: 0.1993 - mae: 0.3532 - rmse: 0.4457 - smape: 0.6942 - val_ia: 0.7711 - val_loss: 0.1537 - val_mae: 0.3143 - val_rmse: 0.3873 - val_smape: 0.6733

Epoch 94/128

287/287 - 5s - 18ms/step - ia: 0.7793 - loss: 0.1957 - mae: 0.3512 - rmse: 0.4415 - smape: 0.6890 - val_ia: 0.7714 - val_loss: 0.1526 - val_mae: 0.3139 - val_rmse: 0.3864 - val_smape: 0.6744

Epoch 95/128

287/287 - 5s - 18ms/step - ia: 0.7796 - loss: 0.1959 - mae: 0.3506 - rmse: 0.4416 - smape: 0.6896 - val_ia: 0.7719 - val_loss: 0.1524 - val_mae: 0.3135 - val_rmse: 0.3858 - val_smape: 0.6725

Epoch 96/128

287/287 - 5s - 18ms/step - ia: 0.7809 - loss: 0.1940 - mae: 0.3484 - rmse: 0.4397 - smape: 0.6843 - val_ia: 0.7725 - val_loss: 0.1518 - val_mae: 0.3131 - val_rmse: 0.3850 - val_smape: 0.6720

Epoch 97/128

287/287 - 5s - 17ms/step - ia: 0.7832 - loss: 0.1898 - mae: 0.3451 - rmse: 0.4348 - smape: 0.6800 - val_ia: 0.7731 - val_loss: 0.1516 - val_mae: 0.3127 - val_rmse: 0.3844 - val_smape: 0.6704


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 7s - 24ms/step - ia: 0.9271 - loss: 0.0294 - mae: 0.1183 - rmse: 0.1592 - smape: 0.2668 - val_ia: 0.9627 - val_loss: 0.0050 - val_mae: 0.0507 - val_rmse: 0.0701 - val_smape: 0.1432

Epoch 2/128

287/287 - 3s - 9ms/step - ia: 0.9417 - loss: 0.0178 - mae: 0.0957 - rmse: 0.1324 - smape: 0.2129 - val_ia: 0.9654 - val_loss: 0.0040 - val_mae: 0.0466 - val_rmse: 0.0620 - val_smape: 0.1489

Epoch 3/128

287/287 - 3s - 9ms/step - ia: 0.9417 - loss: 0.0178 - mae: 0.0956 - rmse: 0.1324 - smape: 0.2098 - val_ia: 0.9740 - val_loss: 0.0028 - val_mae: 0.0353 - val_rmse: 0.0523 - val_smape: 0.1113

Epoch 4/128

287/287 - 3s - 9ms/step - ia: 0.9440 - loss: 0.0167 - mae: 0.0918 - rmse: 0.1283 - smape: 0.2000 - val_ia: 0.9714 - val_loss: 0.0031 - val_mae: 0.0387 - val_rmse: 0.0548 - val_smape: 0.1215

Epoch 5/128

287/287 - 3s - 9ms/step - ia: 0.9434 - loss: 0.0171 - mae: 0.0928 - rmse: 0.1296 - smape: 0.1984 - val_ia: 0.9662 - val_loss: 0.0038 - val_mae: 0.0467 - val_rmse: 0.0615 - val_smape: 0.1302

Epoch 6/128

287/287 - 3s - 9ms/step - ia: 0.9429 - loss: 0.0174 - mae: 0.0937 - rmse: 0.1310 - smape: 0.2022 - val_ia: 0.9606 - val_loss: 0.0051 - val_mae: 0.0529 - val_rmse: 0.0705 - val_smape: 0.1381

Epoch 7/128

287/287 - 3s - 9ms/step - ia: 0.9455 - loss: 0.0159 - mae: 0.0895 - rmse: 0.1252 - smape: 0.1936 - val_ia: 0.9675 - val_loss: 0.0037 - val_mae: 0.0440 - val_rmse: 0.0601 - val_smape: 0.1278

Epoch 8/128

287/287 - 3s - 9ms/step - ia: 0.9435 - loss: 0.0171 - mae: 0.0927 - rmse: 0.1299 - smape: 0.1980 - val_ia: 0.9470 - val_loss: 0.0082 - val_mae: 0.0707 - val_rmse: 0.0880 - val_smape: 0.1693

Epoch 9/128

287/287 - 3s - 9ms/step - ia: 0.2058 - loss: 59463168000.0000 - mae: 74928.3281 - rmse: 159244.4219 - smape: 1.5809 - val_ia: 1.0756e-05 - val_loss: 47847317504.0000 - val_mae: 80130.3750 - val_rmse: 205355.3438 - val_smape: 1.9991

Epoch 10/128

287/287 - 3s - 10ms/step - ia: 9.8135e-05 - loss: 13215159296.0000 - mae: 40550.1875 - rmse: 77218.2656 - smape: 1.9978 - val_ia: 9.9727e-04 - val_loss: 2389526.7500 - val_mae: 924.0593 - val_rmse: 1492.7137 - val_smape: 1.9875

Epoch 11/128

287/287 - 3s - 9ms/step - ia: 0.0020 - loss: 1247259.8750 - mae: 538.2113 - rmse: 1006.3485 - smape: 1.9704 - val_ia: 0.0029 - val_loss: 245749.3125 - val_mae: 228.4977 - val_rmse: 470.9568 - val_smape: 1.9356

Epoch 12/128

287/287 - 3s - 9ms/step - ia: 0.0059 - loss: 139830.5156 - mae: 166.0281 - rmse: 347.6533 - smape: 1.9274 - val_ia: 0.0100 - val_loss: 34461.1836 - val_mae: 85.2538 - val_rmse: 175.1966 - val_smape: 1.8558

Epoch 13/128

287/287 - 3s - 9ms/step - ia: 0.0164 - loss: 18041.6934 - mae: 57.9276 - rmse: 124.1670 - smape: 1.8532 - val_ia: 0.0282 - val_loss: 4260.5630 - val_mae: 29.3339 - val_rmse: 61.7317 - val_smape: 1.7308

Epoch 14/128

287/287 - 3s - 9ms/step - ia: 0.0491 - loss: 1950.2433 - mae: 18.2988 - rmse: 40.0278 - smape: 1.7290 - val_ia: 0.0797 - val_loss: 346.3904 - val_mae: 8.1661 - val_rmse: 17.4848 - val_smape: 1.5508

Epoch 15/128

287/287 - 5s - 18ms/step - ia: 0.1533 - loss: 153.3358 - mae: 4.9842 - rmse: 10.8702 - smape: 1.5187 - val_ia: 0.2028 - val_loss: 23.4620 - val_mae: 2.3612 - val_rmse: 4.6005 - val_smape: 1.4065

Epoch 16/128

287/287 - 3s - 9ms/step - ia: 0.3447 - loss: 9.6690 - mae: 1.4422 - rmse: 2.7524 - smape: 1.3056 - val_ia: 0.3554 - val_loss: 1.8488 - val_mae: 0.9388 - val_rmse: 1.3252 - val_smape: 1.3426

Epoch 17/128

287/287 - 3s - 9ms/step - ia: 0.4569 - loss: 1.0417 - mae: 0.7409 - rmse: 1.0002 - smape: 1.2408 - val_ia: 0.3958 - val_loss: 0.6800 - val_mae: 0.6627 - val_rmse: 0.8156 - val_smape: 1.3480

Epoch 18/128

287/287 - 3s - 9ms/step - ia: 0.4683 - loss: 0.6909 - mae: 0.6667 - rmse: 0.8297 - smape: 1.2531 - val_ia: 0.4168 - val_loss: 0.6422 - val_mae: 0.6493 - val_rmse: 0.7931 - val_smape: 1.2975

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 47s 296ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/128

 58%|█████▊    | 7/12 [3:50:20<1:49:34, 1314.92s/trial, best loss: 0.0019047236032898704]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4586/4586 - 59s - 13ms/step - ia: 0.9163 - loss: 0.0288 - mae: 0.1221 - rmse: 0.1560 - smape: 0.2701 - val_ia: 0.6713 - val_loss: 0.0040 - val_mae: 0.0445 - val_rmse: 0.0539 - val_smape: 0.1257

Epoch 2/128

4586/4586 - 50s - 11ms/step - ia: 0.9327 - loss: 0.0187 - mae: 0.0994 - rmse: 0.1279 - smape: 0.2258 - val_ia: 0.6297 - val_loss: 0.0048 - val_mae: 0.0522 - val_rmse: 0.0614 - val_smape: 0.1722

Epoch 3/128

4586/4586 - 44s - 10ms/step - ia: 0.9350 - loss: 0.0173 - mae: 0.0959 - rmse: 0.1232 - smape: 0.2224 - val_ia: 0.5776 - val_loss: 0.0073 - val_mae: 0.0688 - val_rmse: 0.0781 - val_smape: 0.2127

Epoch 4/128

4586/4586 - 50s - 11ms/step - ia: 0.9371 - loss: 0.0165 - mae: 0.0929 - rmse: 0.1203 - smape: 0.2143 - val_ia: 0.6363 - val_loss: 0.0055 - val_mae: 0.0545 - val_rmse: 0.0634 - val_smape: 0.1449

Epoch 5/128

4586/4586 - 49s - 11ms/step - ia: 0.9379 - loss: 0.0162 - mae: 0.0920 - rmse: 0.1189 - smape: 0.2120 - val_ia: 0.5748 - val_loss: 0.0103 - val_mae: 0.0755 - val_rmse: 0.0839 - val_smape: 0.1736

Epoch 6/128

4586/4586 - 46s - 10ms/step - ia: 0.9384 - loss: 0.0158 - mae: 0.0908 - rmse: 0.1172 - smape: 0.2096 - val_ia: 0.6516 - val_loss: 0.0057 - val_mae: 0.0532 - val_rmse: 0.0620 - val_smape: 0.1369

Epoch 7/128

4586/4586 - 51s - 11ms/step - ia: 0.9389 - loss: 0.0154 - mae: 0.0898 - rmse: 0.1159 - smape: 0.2090 - val_ia: 0.5888 - val_loss: 0.0070 - val_mae: 0.0662 - val_rmse: 0.0744 - val_smape: 0.2243

Epoch 8/128

4586/4586 - 75s - 16ms/step - ia: 0.9396 - loss: 0.0153 - mae: 0.0894 - rmse: 0.1155 - smape: 0.2066 - val_ia: 0.6211 - val_loss: 0.0059 - val_mae: 0.0570 - val_rmse: 0.0654 - val_smape: 0.1459

Epoch 9/128

4586/4586 - 49s - 11ms/step - ia: 0.9400 - loss: 0.0153 - mae: 0.0891 - rmse: 0.1154 - smape: 0.2068 - val_ia: 0.6768 - val_loss: 0.0039 - val_mae: 0.0440 - val_rmse: 0.0532 - val_smape: 0.1217

Epoch 10/128

4586/4586 - 83s - 18ms/step - ia: 0.9392 - loss: 0.0154 - mae: 0.0895 - rmse: 0.1158 - smape: 0.2054 - val_ia: 0.6015 - val_loss: 0.0076 - val_mae: 0.0648 - val_rmse: 0.0731 - val_smape: 0.1428

Epoch 11/128

4586/4586 - 77s - 17ms/step - ia: 0.9405 - loss: 0.0150 - mae: 0.0884 - rmse: 0.1144 - smape: 0.2037 - val_ia: 0.6156 - val_loss: 0.0066 - val_mae: 0.0603 - val_rmse: 0.0689 - val_smape: 0.1585

Epoch 12/128

4586/4586 - 54s - 12ms/step - ia: 0.9399 - loss: 0.0152 - mae: 0.0889 - rmse: 0.1150 - smape: 0.2062 - val_ia: 0.6160 - val_loss: 0.0058 - val_mae: 0.0583 - val_rmse: 0.0667 - val_smape: 0.1487

Epoch 13/128

4586/4586 - 75s - 16ms/step - ia: 0.9402 - loss: 0.0151 - mae: 0.0885 - rmse: 0.1150 - smape: 0.2027 - val_ia: 0.6604 - val_loss: 0.0041 - val_mae: 0.0462 - val_rmse: 0.0552 - val_smape: 0.1403

Epoch 14/128

4586/4586 - 84s - 18ms/step - ia: 0.9411 - loss: 0.0147 - mae: 0.0875 - rmse: 0.1133 - smape: 0.2020 - val_ia: 0.6726 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0535 - val_smape: 0.1336

Epoch 15/128

4586/4586 - 89s - 19ms/step - ia: 0.9408 - loss: 0.0149 - mae: 0.0879 - rmse: 0.1140 - smape: 0.2002 - val_ia: 0.6001 - val_loss: 0.0060 - val_mae: 0.0610 - val_rmse: 0.0697 - val_smape: 0.1455

Epoch 16/128

4586/4586 - 80s - 17ms/step - ia: 0.9404 - loss: 0.0148 - mae: 0.0879 - rmse: 0.1136 - smape: 0.2019 - val_ia: 0.5974 - val_loss: 0.0067 - val_mae: 0.0624 - val_rmse: 0.0707 - val_smape: 0.1453

Epoch 17/128

4586/4586 - 49s - 11ms/step - ia: 0.9414 - loss: 0.0145 - mae: 0.0868 - rmse: 0.1124 - smape: 0.2009 - val_ia: 0.6088 - val_loss: 0.0059 - val_mae: 0.0587 - val_rmse: 0.0670 - val_smape: 0.1617

Epoch 18/128

4586/4586 - 50s - 11ms/step - ia: 0.9408 - loss: 0.0149 - mae: 0.0876 - rmse: 0.1135 - smape: 0.2000 - val_ia: 0.6171 - val_loss: 0.0047 - val_mae: 0.0539 - val_rmse: 0.0624 - val_smape: 0.1496

Epoch 19/128

4586/4586 - 45s - 10ms/step - ia: 0.9408 - loss: 0.0148 - mae: 0.0876 - rmse: 0.1136 - smape: 0.2019 - val_ia: 0.6763 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0526 - val_smape: 0.1320

Epoch 20/128

4586/4586 - 51s - 11ms/step - ia: 0.9412 - loss: 0.0147 - mae: 0.0872 - rmse: 0.1131 - smape: 0.2004 - val_ia: 0.6934 - val_loss: 0.0031 - val_mae: 0.0393 - val_rmse: 0.0481 - val_smape: 0.1230

Epoch 21/128

4586/4586 - 50s - 11ms/step - ia: 0.9421 - loss: 0.0141 - mae: 0.0859 - rmse: 0.1112 - smape: 0.1994 - val_ia: 0.6750 - val_loss: 0.0035 - val_mae: 0.0422 - val_rmse: 0.0513 - val_smape: 0.1272

Epoch 22/128

4586/4586 - 81s - 18ms/step - ia: 0.9409 - loss: 0.0146 - mae: 0.0871 - rmse: 0.1130 - smape: 0.2005 - val_ia: 0.6629 - val_loss: 0.0042 - val_mae: 0.0468 - val_rmse: 0.0556 - val_smape: 0.1278

Epoch 23/128

4586/4586 - 46s - 10ms/step - ia: 0.9408 - loss: 0.0147 - mae: 0.0875 - rmse: 0.1130 - smape: 0.2006 - val_ia: 0.6515 - val_loss: 0.0041 - val_mae: 0.0492 - val_rmse: 0.0578 - val_smape: 0.1472

Epoch 24/128

4586/4586 - 49s - 11ms/step - ia: 0.9410 - loss: 0.0149 - mae: 0.0875 - rmse: 0.1137 - smape: 0.2018 - val_ia: 0.6069 - val_loss: 0.0073 - val_mae: 0.0636 - val_rmse: 0.0719 - val_smape: 0.1535

Epoch 25/128

4586/4586 - 50s - 11ms/step - ia: 0.9415 - loss: 0.0146 - mae: 0.0871 - rmse: 0.1130 - smape: 0.2011 - val_ia: 0.5929 - val_loss: 0.0062 - val_mae: 0.0628 - val_rmse: 0.0713 - val_smape: 0.2099

Epoch 26/128

4586/4586 - 45s - 10ms/step - ia: 0.9415 - loss: 0.0144 - mae: 0.0865 - rmse: 0.1123 - smape: 0.2001 - val_ia: 0.6478 - val_loss: 0.0048 - val_mae: 0.0508 - val_rmse: 0.0596 - val_smape: 0.1475

Epoch 27/128

4586/4586 - 46s - 10ms/step - ia: 0.9409 - loss: 0.0148 - mae: 0.0872 - rmse: 0.1135 - smape: 0.1994 - val_ia: 0.6092 - val_loss: 0.0058 - val_mae: 0.0589 - val_rmse: 0.0675 - val_smape: 0.1622

Epoch 28/128

4586/4586 - 48s - 10ms/step - ia: 0.9411 - loss: 0.0146 - mae: 0.0867 - rmse: 0.1125 - smape: 0.1997 - val_ia: 0.6471 - val_loss: 0.0046 - val_mae: 0.0506 - val_rmse: 0.0592 - val_smape: 0.1485

Epoch 29/128

4586/4586 - 49s - 11ms/step - ia: 0.9410 - loss: 0.0147 - mae: 0.0872 - rmse: 0.1133 - smape: 0.2004 - val_ia: 0.6817 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0512 - val_smape: 0.1348

Epoch 30/128

4586/4586 - 50s - 11ms/step - ia: 0.9415 - loss: 0.0145 - mae: 0.0867 - rmse: 0.1125 - smape: 0.2007 - val_ia: 0.6262 - val_loss: 0.0056 - val_mae: 0.0560 - val_rmse: 0.0646 - val_smape: 0.1591

Epoch 31/128

4586/4586 - 45s - 10ms/step - ia: 0.9411 - loss: 0.0147 - mae: 0.0873 - rmse: 0.1131 - smape: 0.2015 - val_ia: 0.6508 - val_loss: 0.0041 - val_mae: 0.0493 - val_rmse: 0.0579 - val_smape: 0.1365

Epoch 32/128

4586/4586 - 53s - 12ms/step - ia: 0.9405 - loss: 0.0148 - mae: 0.0878 - rmse: 0.1138 - smape: 0.2062 - val_ia: 0.6122 - val_loss: 0.0053 - val_mae: 0.0587 - val_rmse: 0.0672 - val_smape: 0.1819

Epoch 33/128

4586/4586 - 46s - 10ms/step - ia: 0.9420 - loss: 0.0142 - mae: 0.0857 - rmse: 0.1111 - smape: 0.1998 - val_ia: 0.6546 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0575 - val_smape: 0.1327

Epoch 34/128

4586/4586 - 85s - 19ms/step - ia: 0.9414 - loss: 0.0146 - mae: 0.0869 - rmse: 0.1127 - smape: 0.2015 - val_ia: 0.6121 - val_loss: 0.0061 - val_mae: 0.0589 - val_rmse: 0.0675 - val_smape: 0.1444

Epoch 35/128

4586/4586 - 52s - 11ms/step - ia: 0.9416 - loss: 0.0145 - mae: 0.0867 - rmse: 0.1124 - smape: 0.2006 - val_ia: 0.6787 - val_loss: 0.0033 - val_mae: 0.0421 - val_rmse: 0.0508 - val_smape: 0.1285

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:29 925ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

Epoch 1/128

 67%|██████▋   | 8/12 [4:23:46<1:42:20, 1535.19s/trial, best loss: 0.0019047236032898704]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 6s - 19ms/step - ia: 0.8002 - loss: 0.1701 - mae: 0.2979 - rmse: 0.3897 - smape: 0.5945 - val_ia: 0.8534 - val_loss: 0.0621 - val_mae: 0.2019 - val_rmse: 0.2340 - val_smape: 0.5027

Epoch 2/128

287/287 - 1s - 5ms/step - ia: 0.8694 - loss: 0.0792 - mae: 0.2092 - rmse: 0.2802 - smape: 0.4352 - val_ia: 0.9216 - val_loss: 0.0186 - val_mae: 0.1049 - val_rmse: 0.1337 - val_smape: 0.3091

Epoch 3/128

287/287 - 3s - 9ms/step - ia: 0.8800 - loss: 0.0697 - mae: 0.1922 - rmse: 0.2628 - smape: 0.3941 - val_ia: 0.9383 - val_loss: 0.0124 - val_mae: 0.0825 - val_rmse: 0.1099 - val_smape: 0.2412

Epoch 4/128

287/287 - 3s - 9ms/step - ia: 0.8860 - loss: 0.0657 - mae: 0.1830 - rmse: 0.2550 - smape: 0.3669 - val_ia: 0.9404 - val_loss: 0.0112 - val_mae: 0.0798 - val_rmse: 0.1040 - val_smape: 0.2405

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.8908 - loss: 0.0613 - mae: 0.1754 - rmse: 0.2462 - smape: 0.3465 - val_ia: 0.9520 - val_loss: 0.0079 - val_mae: 0.0648 - val_rmse: 0.0878 - val_smape: 0.2040

Epoch 6/128

287/287 - 2s - 5ms/step - ia: 0.8931 - loss: 0.0591 - mae: 0.1715 - rmse: 0.2421 - smape: 0.3326 - val_ia: 0.9543 - val_loss: 0.0074 - val_mae: 0.0613 - val_rmse: 0.0845 - val_smape: 0.1811

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.8941 - loss: 0.0590 - mae: 0.1700 - rmse: 0.2419 - smape: 0.3219 - val_ia: 0.9530 - val_loss: 0.0074 - val_mae: 0.0629 - val_rmse: 0.0847 - val_smape: 0.1825

Epoch 8/128

287/287 - 2s - 5ms/step - ia: 0.8954 - loss: 0.0586 - mae: 0.1680 - rmse: 0.2408 - smape: 0.3149 - val_ia: 0.9593 - val_loss: 0.0059 - val_mae: 0.0549 - val_rmse: 0.0758 - val_smape: 0.1664

Epoch 9/128

287/287 - 2s - 5ms/step - ia: 0.8977 - loss: 0.0569 - mae: 0.1645 - rmse: 0.2374 - smape: 0.3050 - val_ia: 0.9515 - val_loss: 0.0077 - val_mae: 0.0647 - val_rmse: 0.0869 - val_smape: 0.1664

Epoch 10/128

287/287 - 2s - 6ms/step - ia: 0.8976 - loss: 0.0564 - mae: 0.1646 - rmse: 0.2362 - smape: 0.3046 - val_ia: 0.9607 - val_loss: 0.0055 - val_mae: 0.0529 - val_rmse: 0.0731 - val_smape: 0.1582

Epoch 11/128

287/287 - 2s - 5ms/step - ia: 0.8980 - loss: 0.0568 - mae: 0.1639 - rmse: 0.2369 - smape: 0.3002 - val_ia: 0.9549 - val_loss: 0.0066 - val_mae: 0.0603 - val_rmse: 0.0799 - val_smape: 0.1746

Epoch 12/128

287/287 - 1s - 5ms/step - ia: 0.8986 - loss: 0.0560 - mae: 0.1630 - rmse: 0.2355 - smape: 0.2983 - val_ia: 0.9558 - val_loss: 0.0066 - val_mae: 0.0591 - val_rmse: 0.0803 - val_smape: 0.1482

Epoch 13/128

287/287 - 2s - 5ms/step - ia: 0.8985 - loss: 0.0565 - mae: 0.1630 - rmse: 0.2365 - smape: 0.2942 - val_ia: 0.9574 - val_loss: 0.0062 - val_mae: 0.0569 - val_rmse: 0.0777 - val_smape: 0.1429

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.8995 - loss: 0.0554 - mae: 0.1617 - rmse: 0.2343 - smape: 0.2929 - val_ia: 0.9543 - val_loss: 0.0068 - val_mae: 0.0612 - val_rmse: 0.0812 - val_smape: 0.1564

Epoch 15/128

287/287 - 2s - 5ms/step - ia: 0.8997 - loss: 0.0559 - mae: 0.1614 - rmse: 0.2351 - smape: 0.2904 - val_ia: 0.9565 - val_loss: 0.0061 - val_mae: 0.0583 - val_rmse: 0.0761 - val_smape: 0.1658

Epoch 16/128

287/287 - 2s - 5ms/step - ia: 0.8989 - loss: 0.0563 - mae: 0.1623 - rmse: 0.2358 - smape: 0.2926 - val_ia: 0.9590 - val_loss: 0.0056 - val_mae: 0.0551 - val_rmse: 0.0734 - val_smape: 0.1496

Epoch 17/128

287/287 - 2s - 5ms/step - ia: 0.8998 - loss: 0.0558 - mae: 0.1613 - rmse: 0.2347 - smape: 0.2896 - val_ia: 0.9534 - val_loss: 0.0068 - val_mae: 0.0624 - val_rmse: 0.0814 - val_smape: 0.1573

Epoch 18/128

287/287 - 3s - 9ms/step - ia: 0.8994 - loss: 0.0560 - mae: 0.1618 - rmse: 0.2352 - smape: 0.2885 - val_ia: 0.9599 - val_loss: 0.0054 - val_mae: 0.0538 - val_rmse: 0.0723 - val_smape: 0.1405

Epoch 19/128

287/287 - 2s - 5ms/step - ia: 0.8996 - loss: 0.0559 - mae: 0.1615 - rmse: 0.2352 - smape: 0.2875 - val_ia: 0.9521 - val_loss: 0.0071 - val_mae: 0.0639 - val_rmse: 0.0827 - val_smape: 0.1486

Epoch 20/128

287/287 - 2s - 5ms/step - ia: 0.9006 - loss: 0.0546 - mae: 0.1600 - rmse: 0.2324 - smape: 0.2865 - val_ia: 0.9690 - val_loss: 0.0036 - val_mae: 0.0422 - val_rmse: 0.0587 - val_smape: 0.1371

Epoch 21/128

287/287 - 3s - 9ms/step - ia: 0.9003 - loss: 0.0559 - mae: 0.1604 - rmse: 0.2351 - smape: 0.2833 - val_ia: 0.9541 - val_loss: 0.0066 - val_mae: 0.0614 - val_rmse: 0.0803 - val_smape: 0.1495

Epoch 22/128

287/287 - 1s - 5ms/step - ia: 0.9011 - loss: 0.0550 - mae: 0.1592 - rmse: 0.2331 - smape: 0.2818 - val_ia: 0.9542 - val_loss: 0.0065 - val_mae: 0.0613 - val_rmse: 0.0788 - val_smape: 0.1507

Epoch 23/128

287/287 - 2s - 5ms/step - ia: 0.9013 - loss: 0.0543 - mae: 0.1588 - rmse: 0.2317 - smape: 0.2818 - val_ia: 0.9467 - val_loss: 0.0082 - val_mae: 0.0706 - val_rmse: 0.0897 - val_smape: 0.1514

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.9004 - loss: 0.0553 - mae: 0.1600 - rmse: 0.2338 - smape: 0.2832 - val_ia: 0.9526 - val_loss: 0.0068 - val_mae: 0.0633 - val_rmse: 0.0811 - val_smape: 0.1459

Epoch 25/128

287/287 - 3s - 9ms/step - ia: 0.9008 - loss: 0.0550 - mae: 0.1597 - rmse: 0.2334 - smape: 0.2826 - val_ia: 0.9545 - val_loss: 0.0064 - val_mae: 0.0609 - val_rmse: 0.0788 - val_smape: 0.1441

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.9008 - loss: 0.0549 - mae: 0.1595 - rmse: 0.2333 - smape: 0.2824 - val_ia: 0.9562 - val_loss: 0.0059 - val_mae: 0.0587 - val_rmse: 0.0755 - val_smape: 0.1421

Epoch 27/128

287/287 - 2s - 6ms/step - ia: 0.9014 - loss: 0.0543 - mae: 0.1586 - rmse: 0.2318 - smape: 0.2808 - val_ia: 0.9597 - val_loss: 0.0052 - val_mae: 0.0542 - val_rmse: 0.0712 - val_smape: 0.1369

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.9017 - loss: 0.0539 - mae: 0.1582 - rmse: 0.2310 - smape: 0.2810 - val_ia: 0.9551 - val_loss: 0.0062 - val_mae: 0.0602 - val_rmse: 0.0777 - val_smape: 0.1449

Epoch 29/128

287/287 - 2s - 5ms/step - ia: 0.9013 - loss: 0.0546 - mae: 0.1588 - rmse: 0.2321 - smape: 0.2803 - val_ia: 0.9561 - val_loss: 0.0060 - val_mae: 0.0589 - val_rmse: 0.0761 - val_smape: 0.1465

Epoch 30/128

287/287 - 1s - 5ms/step - ia: 0.9013 - loss: 0.0545 - mae: 0.1587 - rmse: 0.2319 - smape: 0.2801 - val_ia: 0.9482 - val_loss: 0.0077 - val_mae: 0.0690 - val_rmse: 0.0868 - val_smape: 0.1511

Epoch 31/128

287/287 - 2s - 5ms/step - ia: 0.9014 - loss: 0.0543 - mae: 0.1586 - rmse: 0.2318 - smape: 0.2789 - val_ia: 0.9543 - val_loss: 0.0062 - val_mae: 0.0613 - val_rmse: 0.0771 - val_smape: 0.1570

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.9011 - loss: 0.0545 - mae: 0.1590 - rmse: 0.2324 - smape: 0.2800 - val_ia: 0.9633 - val_loss: 0.0045 - val_mae: 0.0494 - val_rmse: 0.0658 - val_smape: 0.1274

Epoch 33/128

287/287 - 2s - 6ms/step - ia: 0.9016 - loss: 0.0546 - mae: 0.1586 - rmse: 0.2322 - smape: 0.2787 - val_ia: 0.9586 - val_loss: 0.0054 - val_mae: 0.0555 - val_rmse: 0.0726 - val_smape: 0.1336

Epoch 34/128

287/287 - 2s - 9ms/step - ia: 0.9004 - loss: 0.0559 - mae: 0.1600 - rmse: 0.2349 - smape: 0.2795 - val_ia: 0.9661 - val_loss: 0.0040 - val_mae: 0.0459 - val_rmse: 0.0626 - val_smape: 0.1256

Epoch 35/128

287/287 - 3s - 9ms/step - ia: 0.9016 - loss: 0.0541 - mae: 0.1583 - rmse: 0.2313 - smape: 0.2788 - val_ia: 0.9622 - val_loss: 0.0047 - val_mae: 0.0509 - val_rmse: 0.0675 - val_smape: 0.1304

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 44s 274ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 75%|███████▌  | 9/12 [4:24:52<53:47, 1075.86s/trial, best loss: 0.0019047236032898704]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 30s - 13ms/step - ia: 0.6312 - loss: 0.4675 - mae: 0.5163 - rmse: 0.6319 - smape: 0.9205 - val_ia: 0.4056 - val_loss: 0.1455 - val_mae: 0.3029 - val_rmse: 0.3284 - val_smape: 0.6451

Epoch 2/128

2293/2293 - 26s - 11ms/step - ia: 0.8152 - loss: 0.1317 - mae: 0.2848 - rmse: 0.3555 - smape: 0.5929 - val_ia: 0.4537 - val_loss: 0.1035 - val_mae: 0.2569 - val_rmse: 0.2760 - val_smape: 0.5891

Epoch 3/128

2293/2293 - 27s - 12ms/step - ia: 0.8551 - loss: 0.0830 - mae: 0.2238 - rmse: 0.2818 - smape: 0.4984 - val_ia: 0.5268 - val_loss: 0.0600 - val_mae: 0.1948 - val_rmse: 0.2112 - val_smape: 0.4989

Epoch 4/128

2293/2293 - 24s - 10ms/step - ia: 0.8813 - loss: 0.0572 - mae: 0.1837 - rmse: 0.2335 - smape: 0.4221 - val_ia: 0.5731 - val_loss: 0.0432 - val_mae: 0.1643 - val_rmse: 0.1810 - val_smape: 0.4410

Epoch 5/128

2293/2293 - 27s - 12ms/step - ia: 0.8937 - loss: 0.0463 - mae: 0.1649 - rmse: 0.2099 - smape: 0.3827 - val_ia: 0.6481 - val_loss: 0.0245 - val_mae: 0.1173 - val_rmse: 0.1345 - val_smape: 0.3065

Epoch 6/128

2293/2293 - 28s - 12ms/step - ia: 0.9021 - loss: 0.0402 - mae: 0.1526 - rmse: 0.1955 - smape: 0.3594 - val_ia: 0.6792 - val_loss: 0.0186 - val_mae: 0.0995 - val_rmse: 0.1171 - val_smape: 0.2705

Epoch 7/128

2293/2293 - 28s - 12ms/step - ia: 0.9074 - loss: 0.0361 - mae: 0.1440 - rmse: 0.1848 - smape: 0.3428 - val_ia: 0.6787 - val_loss: 0.0175 - val_mae: 0.0977 - val_rmse: 0.1154 - val_smape: 0.2686

Epoch 8/128

2293/2293 - 27s - 12ms/step - ia: 0.9111 - loss: 0.0335 - mae: 0.1385 - rmse: 0.1781 - smape: 0.3290 - val_ia: 0.6760 - val_loss: 0.0171 - val_mae: 0.0970 - val_rmse: 0.1143 - val_smape: 0.2563

Epoch 9/128

2293/2293 - 41s - 18ms/step - ia: 0.9139 - loss: 0.0316 - mae: 0.1339 - rmse: 0.1729 - smape: 0.3192 - val_ia: 0.6861 - val_loss: 0.0158 - val_mae: 0.0922 - val_rmse: 0.1097 - val_smape: 0.2282

Epoch 10/128

2293/2293 - 27s - 12ms/step - ia: 0.9168 - loss: 0.0296 - mae: 0.1299 - rmse: 0.1672 - smape: 0.3124 - val_ia: 0.7286 - val_loss: 0.0117 - val_mae: 0.0761 - val_rmse: 0.0930 - val_smape: 0.1945

Epoch 11/128

2293/2293 - 27s - 12ms/step - ia: 0.9188 - loss: 0.0283 - mae: 0.1265 - rmse: 0.1635 - smape: 0.3061 - val_ia: 0.7148 - val_loss: 0.0124 - val_mae: 0.0804 - val_rmse: 0.0970 - val_smape: 0.2052

Epoch 12/128

2293/2293 - 41s - 18ms/step - ia: 0.9206 - loss: 0.0270 - mae: 0.1241 - rmse: 0.1596 - smape: 0.3014 - val_ia: 0.6943 - val_loss: 0.0136 - val_mae: 0.0865 - val_rmse: 0.1026 - val_smape: 0.2130

Epoch 13/128

2293/2293 - 41s - 18ms/step - ia: 0.9226 - loss: 0.0258 - mae: 0.1209 - rmse: 0.1559 - smape: 0.2955 - val_ia: 0.7322 - val_loss: 0.0104 - val_mae: 0.0727 - val_rmse: 0.0889 - val_smape: 0.1853

Epoch 14/128

2293/2293 - 37s - 16ms/step - ia: 0.9236 - loss: 0.0252 - mae: 0.1194 - rmse: 0.1540 - smape: 0.2908 - val_ia: 0.7356 - val_loss: 0.0099 - val_mae: 0.0713 - val_rmse: 0.0868 - val_smape: 0.1866

Epoch 15/128

2293/2293 - 27s - 12ms/step - ia: 0.9241 - loss: 0.0249 - mae: 0.1183 - rmse: 0.1530 - smape: 0.2871 - val_ia: 0.7203 - val_loss: 0.0109 - val_mae: 0.0768 - val_rmse: 0.0923 - val_smape: 0.2003

Epoch 16/128

2293/2293 - 26s - 12ms/step - ia: 0.9250 - loss: 0.0245 - mae: 0.1170 - rmse: 0.1520 - smape: 0.2850 - val_ia: 0.7585 - val_loss: 0.0081 - val_mae: 0.0639 - val_rmse: 0.0788 - val_smape: 0.1818

Epoch 17/128

2293/2293 - 41s - 18ms/step - ia: 0.9265 - loss: 0.0238 - mae: 0.1151 - rmse: 0.1495 - smape: 0.2813 - val_ia: 0.7137 - val_loss: 0.0110 - val_mae: 0.0784 - val_rmse: 0.0936 - val_smape: 0.2019

Epoch 18/128

2293/2293 - 27s - 12ms/step - ia: 0.9275 - loss: 0.0231 - mae: 0.1135 - rmse: 0.1472 - smape: 0.2772 - val_ia: 0.7278 - val_loss: 0.0098 - val_mae: 0.0727 - val_rmse: 0.0878 - val_smape: 0.1890

Epoch 19/128

2293/2293 - 27s - 12ms/step - ia: 0.9279 - loss: 0.0229 - mae: 0.1127 - rmse: 0.1466 - smape: 0.2747 - val_ia: 0.7375 - val_loss: 0.0091 - val_mae: 0.0691 - val_rmse: 0.0839 - val_smape: 0.1799

Epoch 20/128

2293/2293 - 27s - 12ms/step - ia: 0.9289 - loss: 0.0223 - mae: 0.1114 - rmse: 0.1445 - smape: 0.2705 - val_ia: 0.7406 - val_loss: 0.0088 - val_mae: 0.0685 - val_rmse: 0.0831 - val_smape: 0.1824

Epoch 21/128

2293/2293 - 41s - 18ms/step - ia: 0.9287 - loss: 0.0224 - mae: 0.1115 - rmse: 0.1449 - smape: 0.2718 - val_ia: 0.7381 - val_loss: 0.0087 - val_mae: 0.0682 - val_rmse: 0.0828 - val_smape: 0.1807

Epoch 22/128

2293/2293 - 27s - 12ms/step - ia: 0.9295 - loss: 0.0220 - mae: 0.1102 - rmse: 0.1437 - smape: 0.2661 - val_ia: 0.7487 - val_loss: 0.0082 - val_mae: 0.0664 - val_rmse: 0.0804 - val_smape: 0.1798

Epoch 23/128

2293/2293 - 27s - 12ms/step - ia: 0.9299 - loss: 0.0216 - mae: 0.1098 - rmse: 0.1425 - smape: 0.2671 - val_ia: 0.7276 - val_loss: 0.0095 - val_mae: 0.0728 - val_rmse: 0.0871 - val_smape: 0.1906

Epoch 24/128

2293/2293 - 28s - 12ms/step - ia: 0.9306 - loss: 0.0213 - mae: 0.1085 - rmse: 0.1413 - smape: 0.2647 - val_ia: 0.7313 - val_loss: 0.0091 - val_mae: 0.0708 - val_rmse: 0.0849 - val_smape: 0.1905

Epoch 25/128

2293/2293 - 27s - 12ms/step - ia: 0.9312 - loss: 0.0208 - mae: 0.1076 - rmse: 0.1398 - smape: 0.2610 - val_ia: 0.7438 - val_loss: 0.0081 - val_mae: 0.0665 - val_rmse: 0.0803 - val_smape: 0.1776

Epoch 26/128

2293/2293 - 27s - 12ms/step - ia: 0.9312 - loss: 0.0208 - mae: 0.1073 - rmse: 0.1400 - smape: 0.2610 - val_ia: 0.7453 - val_loss: 0.0081 - val_mae: 0.0666 - val_rmse: 0.0805 - val_smape: 0.1756

Epoch 27/128

2293/2293 - 41s - 18ms/step - ia: 0.9313 - loss: 0.0211 - mae: 0.1074 - rmse: 0.1404 - smape: 0.2612 - val_ia: 0.7166 - val_loss: 0.0099 - val_mae: 0.0753 - val_rmse: 0.0890 - val_smape: 0.1987

Epoch 28/128

2293/2293 - 27s - 12ms/step - ia: 0.9322 - loss: 0.0204 - mae: 0.1061 - rmse: 0.1383 - smape: 0.2576 - val_ia: 0.7264 - val_loss: 0.0090 - val_mae: 0.0722 - val_rmse: 0.0859 - val_smape: 0.1851

Epoch 29/128

2293/2293 - 26s - 11ms/step - ia: 0.9321 - loss: 0.0205 - mae: 0.1063 - rmse: 0.1387 - smape: 0.2588 - val_ia: 0.7423 - val_loss: 0.0081 - val_mae: 0.0666 - val_rmse: 0.0801 - val_smape: 0.1791

Epoch 30/128

2293/2293 - 27s - 12ms/step - ia: 0.9326 - loss: 0.0204 - mae: 0.1055 - rmse: 0.1379 - smape: 0.2564 - val_ia: 0.7353 - val_loss: 0.0086 - val_mae: 0.0693 - val_rmse: 0.0827 - val_smape: 0.1918

Epoch 31/128

2293/2293 - 24s - 10ms/step - ia: 0.9333 - loss: 0.0200 - mae: 0.1044 - rmse: 0.1367 - smape: 0.2522 - val_ia: 0.7445 - val_loss: 0.0080 - val_mae: 0.0669 - val_rmse: 0.0800 - val_smape: 0.1831

Epoch 32/128

2293/2293 - 27s - 12ms/step - ia: 0.9325 - loss: 0.0203 - mae: 0.1055 - rmse: 0.1378 - smape: 0.2527 - val_ia: 0.7468 - val_loss: 0.0078 - val_mae: 0.0658 - val_rmse: 0.0790 - val_smape: 0.1771

Epoch 33/128

2293/2293 - 36s - 16ms/step - ia: 0.9337 - loss: 0.0197 - mae: 0.1039 - rmse: 0.1356 - smape: 0.2542 - val_ia: 0.7622 - val_loss: 0.0064 - val_mae: 0.0592 - val_rmse: 0.0724 - val_smape: 0.1694

Epoch 34/128

2293/2293 - 27s - 12ms/step - ia: 0.9338 - loss: 0.0197 - mae: 0.1035 - rmse: 0.1358 - smape: 0.2503 - val_ia: 0.7639 - val_loss: 0.0067 - val_mae: 0.0608 - val_rmse: 0.0737 - val_smape: 0.1754

Epoch 35/128

2293/2293 - 23s - 10ms/step - ia: 0.9342 - loss: 0.0194 - mae: 0.1031 - rmse: 0.1345 - smape: 0.2507 - val_ia: 0.7517 - val_loss: 0.0073 - val_mae: 0.0638 - val_rmse: 0.0771 - val_smape: 0.1781

Epoch 36/128

2293/2293 - 27s - 12ms/step - ia: 0.9348 - loss: 0.0192 - mae: 0.1021 - rmse: 0.1337 - smape: 0.2479 - val_ia: 0.7312 - val_loss: 0.0088 - val_mae: 0.0705 - val_rmse: 0.0834 - val_smape: 0.1814

Epoch 37/128

2293/2293 - 26s - 11ms/step - ia: 0.9343 - loss: 0.0194 - mae: 0.1028 - rmse: 0.1344 - smape: 0.2492 - val_ia: 0.7754 - val_loss: 0.0057 - val_mae: 0.0555 - val_rmse: 0.0681 - val_smape: 0.1616

Epoch 38/128

2293/2293 - 25s - 11ms/step - ia: 0.9343 - loss: 0.0193 - mae: 0.1027 - rmse: 0.1345 - smape: 0.2498 - val_ia: 0.7557 - val_loss: 0.0070 - val_mae: 0.0622 - val_rmse: 0.0748 - val_smape: 0.1725

Epoch 39/128

2293/2293 - 27s - 12ms/step - ia: 0.9352 - loss: 0.0190 - mae: 0.1016 - rmse: 0.1330 - smape: 0.2469 - val_ia: 0.7424 - val_loss: 0.0080 - val_mae: 0.0674 - val_rmse: 0.0802 - val_smape: 0.1865

Epoch 40/128

2293/2293 - 41s - 18ms/step - ia: 0.9351 - loss: 0.0190 - mae: 0.1017 - rmse: 0.1330 - smape: 0.2462 - val_ia: 0.7692 - val_loss: 0.0063 - val_mae: 0.0586 - val_rmse: 0.0715 - val_smape: 0.1632

Epoch 41/128

2293/2293 - 36s - 16ms/step - ia: 0.9356 - loss: 0.0188 - mae: 0.1010 - rmse: 0.1325 - smape: 0.2430 - val_ia: 0.7683 - val_loss: 0.0062 - val_mae: 0.0581 - val_rmse: 0.0705 - val_smape: 0.1630

Epoch 42/128

2293/2293 - 27s - 12ms/step - ia: 0.9359 - loss: 0.0186 - mae: 0.1006 - rmse: 0.1316 - smape: 0.2445 - val_ia: 0.7556 - val_loss: 0.0070 - val_mae: 0.0622 - val_rmse: 0.0745 - val_smape: 0.1740

Epoch 43/128

2293/2293 - 32s - 14ms/step - ia: 0.9357 - loss: 0.0189 - mae: 0.1008 - rmse: 0.1327 - smape: 0.2437 - val_ia: 0.7587 - val_loss: 0.0067 - val_mae: 0.0611 - val_rmse: 0.0736 - val_smape: 0.1738

Epoch 44/128

2293/2293 - 27s - 12ms/step - ia: 0.9358 - loss: 0.0185 - mae: 0.1004 - rmse: 0.1315 - smape: 0.2421 - val_ia: 0.7230 - val_loss: 0.0094 - val_mae: 0.0741 - val_rmse: 0.0868 - val_smape: 0.1917

Epoch 45/128

2293/2293 - 27s - 12ms/step - ia: 0.9367 - loss: 0.0183 - mae: 0.0992 - rmse: 0.1305 - smape: 0.2393 - val_ia: 0.7538 - val_loss: 0.0071 - val_mae: 0.0637 - val_rmse: 0.0762 - val_smape: 0.1677

Epoch 46/128

2293/2293 - 27s - 12ms/step - ia: 0.9360 - loss: 0.0186 - mae: 0.0999 - rmse: 0.1316 - smape: 0.2393 - val_ia: 0.7328 - val_loss: 0.0082 - val_mae: 0.0700 - val_rmse: 0.0827 - val_smape: 0.1794

Epoch 47/128

2293/2293 - 25s - 11ms/step - ia: 0.9363 - loss: 0.0183 - mae: 0.0996 - rmse: 0.1304 - smape: 0.2413 - val_ia: 0.7633 - val_loss: 0.0065 - val_mae: 0.0599 - val_rmse: 0.0723 - val_smape: 0.1767

Epoch 48/128

2293/2293 - 26s - 11ms/step - ia: 0.9365 - loss: 0.0182 - mae: 0.0994 - rmse: 0.1304 - smape: 0.2408 - val_ia: 0.7501 - val_loss: 0.0073 - val_mae: 0.0655 - val_rmse: 0.0778 - val_smape: 0.1733

Epoch 49/128

2293/2293 - 27s - 12ms/step - ia: 0.9364 - loss: 0.0185 - mae: 0.0999 - rmse: 0.1313 - smape: 0.2393 - val_ia: 0.7430 - val_loss: 0.0078 - val_mae: 0.0673 - val_rmse: 0.0797 - val_smape: 0.1767

Epoch 50/128

2293/2293 - 40s - 17ms/step - ia: 0.9364 - loss: 0.0184 - mae: 0.0996 - rmse: 0.1309 - smape: 0.2376 - val_ia: 0.7682 - val_loss: 0.0063 - val_mae: 0.0591 - val_rmse: 0.0714 - val_smape: 0.1663

Epoch 51/128

2293/2293 - 48s - 21ms/step - ia: 0.9374 - loss: 0.0179 - mae: 0.0982 - rmse: 0.1293 - smape: 0.2363 - val_ia: 0.7719 - val_loss: 0.0060 - val_mae: 0.0572 - val_rmse: 0.0694 - val_smape: 0.1609

Epoch 52/128

2293/2293 - 33s - 14ms/step - ia: 0.9379 - loss: 0.0177 - mae: 0.0975 - rmse: 0.1283 - smape: 0.2372 - val_ia: 0.7721 - val_loss: 0.0060 - val_mae: 0.0576 - val_rmse: 0.0697 - val_smape: 0.1629

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:22 1s/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 16s 101ms/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 83%|████████▎ | 10/12 [4:50:59<40:54, 1227.40s/trial, best loss: 0.0019047236032898704]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 56s - 12ms/step - ia: 0.3097 - loss: 0.8850 - mae: 0.7620 - rmse: 0.9176 - smape: 1.5007 - val_ia: 0.1448 - val_loss: 0.7894 - val_mae: 0.7431 - val_rmse: 0.7597 - val_smape: 1.7577

Epoch 2/128

4586/4586 - 36s - 8ms/step - ia: 0.3342 - loss: 0.8310 - mae: 0.7358 - rmse: 0.8898 - smape: 1.4587 - val_ia: 0.1472 - val_loss: 0.7455 - val_mae: 0.7232 - val_rmse: 0.7394 - val_smape: 1.7026

Epoch 3/128

4586/4586 - 39s - 8ms/step - ia: 0.3581 - loss: 0.7839 - mae: 0.7127 - rmse: 0.8621 - smape: 1.4223 - val_ia: 0.1498 - val_loss: 0.7031 - val_mae: 0.7033 - val_rmse: 0.7191 - val_smape: 1.6365

Epoch 4/128

4586/4586 - 38s - 8ms/step - ia: 0.3796 - loss: 0.7413 - mae: 0.6904 - rmse: 0.8385 - smape: 1.3836 - val_ia: 0.1526 - val_loss: 0.6618 - val_mae: 0.6830 - val_rmse: 0.6985 - val_smape: 1.5684

Epoch 5/128

4586/4586 - 36s - 8ms/step - ia: 0.4046 - loss: 0.7064 - mae: 0.6687 - rmse: 0.8170 - smape: 1.3450 - val_ia: 0.1552 - val_loss: 0.6224 - val_mae: 0.6630 - val_rmse: 0.6781 - val_smape: 1.5026

Epoch 6/128

4586/4586 - 37s - 8ms/step - ia: 0.4316 - loss: 0.6651 - mae: 0.6445 - rmse: 0.7913 - smape: 1.3067 - val_ia: 0.1581 - val_loss: 0.5842 - val_mae: 0.6427 - val_rmse: 0.6575 - val_smape: 1.4390

Epoch 7/128

4586/4586 - 38s - 8ms/step - ia: 0.4536 - loss: 0.6357 - mae: 0.6249 - rmse: 0.7732 - smape: 1.2673 - val_ia: 0.1609 - val_loss: 0.5478 - val_mae: 0.6225 - val_rmse: 0.6370 - val_smape: 1.3786

Epoch 8/128

4586/4586 - 39s - 8ms/step - ia: 0.4757 - loss: 0.6056 - mae: 0.6058 - rmse: 0.7538 - smape: 1.2310 - val_ia: 0.1638 - val_loss: 0.5131 - val_mae: 0.6025 - val_rmse: 0.6166 - val_smape: 1.3210

Epoch 9/128

4586/4586 - 38s - 8ms/step - ia: 0.4989 - loss: 0.5752 - mae: 0.5881 - rmse: 0.7340 - smape: 1.2015 - val_ia: 0.1667 - val_loss: 0.4822 - val_mae: 0.5839 - val_rmse: 0.5977 - val_smape: 1.2689

Epoch 10/128

4586/4586 - 41s - 9ms/step - ia: 0.5156 - loss: 0.5561 - mae: 0.5746 - rmse: 0.7207 - smape: 1.1691 - val_ia: 0.1693 - val_loss: 0.4546 - val_mae: 0.5667 - val_rmse: 0.5802 - val_smape: 1.2219

Epoch 11/128

4586/4586 - 37s - 8ms/step - ia: 0.5265 - loss: 0.5438 - mae: 0.5672 - rmse: 0.7119 - smape: 1.1533 - val_ia: 0.1718 - val_loss: 0.4315 - val_mae: 0.5518 - val_rmse: 0.5650 - val_smape: 1.1820

Epoch 12/128

4586/4586 - 37s - 8ms/step - ia: 0.5397 - loss: 0.5271 - mae: 0.5568 - rmse: 0.7002 - smape: 1.1315 - val_ia: 0.1741 - val_loss: 0.4124 - val_mae: 0.5391 - val_rmse: 0.5522 - val_smape: 1.1482

Epoch 13/128

4586/4586 - 24s - 5ms/step - ia: 0.5447 - loss: 0.5190 - mae: 0.5535 - rmse: 0.6945 - smape: 1.1203 - val_ia: 0.1763 - val_loss: 0.3962 - val_mae: 0.5280 - val_rmse: 0.5409 - val_smape: 1.1181

Epoch 14/128

4586/4586 - 25s - 5ms/step - ia: 0.5539 - loss: 0.5039 - mae: 0.5459 - rmse: 0.6857 - smape: 1.1047 - val_ia: 0.1784 - val_loss: 0.3820 - val_mae: 0.5180 - val_rmse: 0.5308 - val_smape: 1.0924

Epoch 15/128

4586/4586 - 24s - 5ms/step - ia: 0.5653 - loss: 0.4940 - mae: 0.5380 - rmse: 0.6777 - smape: 1.0834 - val_ia: 0.1802 - val_loss: 0.3717 - val_mae: 0.5105 - val_rmse: 0.5233 - val_smape: 1.0730

Epoch 16/128

4586/4586 - 24s - 5ms/step - ia: 0.5695 - loss: 0.4825 - mae: 0.5341 - rmse: 0.6698 - smape: 1.0759 - val_ia: 0.1821 - val_loss: 0.3617 - val_mae: 0.5030 - val_rmse: 0.5157 - val_smape: 1.0546

Epoch 17/128

4586/4586 - 24s - 5ms/step - ia: 0.5766 - loss: 0.4751 - mae: 0.5286 - rmse: 0.6651 - smape: 1.0629 - val_ia: 0.1839 - val_loss: 0.3531 - val_mae: 0.4964 - val_rmse: 0.5091 - val_smape: 1.0387

Epoch 18/128

4586/4586 - 41s - 9ms/step - ia: 0.5791 - loss: 0.4711 - mae: 0.5256 - rmse: 0.6611 - smape: 1.0555 - val_ia: 0.1860 - val_loss: 0.3446 - val_mae: 0.4897 - val_rmse: 0.5024 - val_smape: 1.0233

Epoch 19/128

4586/4586 - 41s - 9ms/step - ia: 0.5842 - loss: 0.4676 - mae: 0.5233 - rmse: 0.6588 - smape: 1.0468 - val_ia: 0.1876 - val_loss: 0.3390 - val_mae: 0.4852 - val_rmse: 0.4980 - val_smape: 1.0123

Epoch 20/128

4586/4586 - 24s - 5ms/step - ia: 0.5861 - loss: 0.4627 - mae: 0.5207 - rmse: 0.6552 - smape: 1.0384 - val_ia: 0.1891 - val_loss: 0.3337 - val_mae: 0.4808 - val_rmse: 0.4935 - val_smape: 1.0022

Epoch 21/128

4586/4586 - 24s - 5ms/step - ia: 0.5894 - loss: 0.4563 - mae: 0.5167 - rmse: 0.6506 - smape: 1.0302 - val_ia: 0.1906 - val_loss: 0.3284 - val_mae: 0.4763 - val_rmse: 0.4891 - val_smape: 0.9926

Epoch 22/128

4586/4586 - 24s - 5ms/step - ia: 0.5932 - loss: 0.4518 - mae: 0.5151 - rmse: 0.6480 - smape: 1.0237 - val_ia: 0.1919 - val_loss: 0.3242 - val_mae: 0.4727 - val_rmse: 0.4855 - val_smape: 0.9846

Epoch 23/128

4586/4586 - 24s - 5ms/step - ia: 0.5958 - loss: 0.4453 - mae: 0.5118 - rmse: 0.6435 - smape: 1.0159 - val_ia: 0.1932 - val_loss: 0.3202 - val_mae: 0.4692 - val_rmse: 0.4819 - val_smape: 0.9769

Epoch 24/128

4586/4586 - 24s - 5ms/step - ia: 0.6003 - loss: 0.4394 - mae: 0.5070 - rmse: 0.6387 - smape: 1.0064 - val_ia: 0.1943 - val_loss: 0.3172 - val_mae: 0.4666 - val_rmse: 0.4794 - val_smape: 0.9710

Epoch 25/128

4586/4586 - 24s - 5ms/step - ia: 0.5969 - loss: 0.4417 - mae: 0.5099 - rmse: 0.6407 - smape: 1.0137 - val_ia: 0.1954 - val_loss: 0.3139 - val_mae: 0.4636 - val_rmse: 0.4763 - val_smape: 0.9645

Epoch 26/128

4586/4586 - 24s - 5ms/step - ia: 0.6064 - loss: 0.4278 - mae: 0.5014 - rmse: 0.6295 - smape: 0.9975 - val_ia: 0.1966 - val_loss: 0.3106 - val_mae: 0.4607 - val_rmse: 0.4735 - val_smape: 0.9583

Epoch 27/128

4586/4586 - 24s - 5ms/step - ia: 0.6072 - loss: 0.4283 - mae: 0.5010 - rmse: 0.6306 - smape: 0.9905 - val_ia: 0.1977 - val_loss: 0.3076 - val_mae: 0.4580 - val_rmse: 0.4708 - val_smape: 0.9522

Epoch 28/128

4586/4586 - 42s - 9ms/step - ia: 0.6096 - loss: 0.4271 - mae: 0.4999 - rmse: 0.6280 - smape: 0.9819 - val_ia: 0.1984 - val_loss: 0.3058 - val_mae: 0.4563 - val_rmse: 0.4691 - val_smape: 0.9484

Epoch 29/128

4586/4586 - 40s - 9ms/step - ia: 0.6135 - loss: 0.4172 - mae: 0.4936 - rmse: 0.6221 - smape: 0.9774 - val_ia: 0.1992 - val_loss: 0.3040 - val_mae: 0.4547 - val_rmse: 0.4675 - val_smape: 0.9445

Epoch 30/128

4586/4586 - 24s - 5ms/step - ia: 0.6106 - loss: 0.4199 - mae: 0.4970 - rmse: 0.6238 - smape: 0.9792 - val_ia: 0.2001 - val_loss: 0.3013 - val_mae: 0.4523 - val_rmse: 0.4651 - val_smape: 0.9391

Epoch 31/128

4586/4586 - 24s - 5ms/step - ia: 0.6163 - loss: 0.4156 - mae: 0.4928 - rmse: 0.6202 - smape: 0.9674 - val_ia: 0.2010 - val_loss: 0.2991 - val_mae: 0.4502 - val_rmse: 0.4630 - val_smape: 0.9348

Epoch 32/128

4586/4586 - 24s - 5ms/step - ia: 0.6188 - loss: 0.4076 - mae: 0.4886 - rmse: 0.6153 - smape: 0.9645 - val_ia: 0.2018 - val_loss: 0.2971 - val_mae: 0.4485 - val_rmse: 0.4613 - val_smape: 0.9307

Epoch 33/128

4586/4586 - 24s - 5ms/step - ia: 0.6198 - loss: 0.4053 - mae: 0.4871 - rmse: 0.6124 - smape: 0.9580 - val_ia: 0.2024 - val_loss: 0.2955 - val_mae: 0.4471 - val_rmse: 0.4599 - val_smape: 0.9273

Epoch 34/128

4586/4586 - 24s - 5ms/step - ia: 0.6239 - loss: 0.4007 - mae: 0.4844 - rmse: 0.6095 - smape: 0.9518 - val_ia: 0.2029 - val_loss: 0.2943 - val_mae: 0.4459 - val_rmse: 0.4588 - val_smape: 0.9245

Epoch 35/128

4586/4586 - 24s - 5ms/step - ia: 0.6257 - loss: 0.3968 - mae: 0.4817 - rmse: 0.6062 - smape: 0.9471 - val_ia: 0.2036 - val_loss: 0.2923 - val_mae: 0.4442 - val_rmse: 0.4571 - val_smape: 0.9204

Epoch 36/128

4586/4586 - 24s - 5ms/step - ia: 0.6270 - loss: 0.3964 - mae: 0.4809 - rmse: 0.6055 - smape: 0.9419 - val_ia: 0.2046 - val_loss: 0.2898 - val_mae: 0.4420 - val_rmse: 0.4549 - val_smape: 0.9153

Epoch 37/128

4586/4586 - 41s - 9ms/step - ia: 0.6259 - loss: 0.3974 - mae: 0.4808 - rmse: 0.6059 - smape: 0.9397 - val_ia: 0.2051 - val_loss: 0.2885 - val_mae: 0.4408 - val_rmse: 0.4537 - val_smape: 0.9122

Epoch 38/128

4586/4586 - 25s - 6ms/step - ia: 0.6349 - loss: 0.3828 - mae: 0.4716 - rmse: 0.5947 - smape: 0.9246 - val_ia: 0.2056 - val_loss: 0.2870 - val_mae: 0.4395 - val_rmse: 0.4524 - val_smape: 0.9086

Epoch 39/128

4586/4586 - 25s - 5ms/step - ia: 0.6324 - loss: 0.3872 - mae: 0.4741 - rmse: 0.5984 - smape: 0.9249 - val_ia: 0.2062 - val_loss: 0.2851 - val_mae: 0.4378 - val_rmse: 0.4507 - val_smape: 0.9047

Epoch 40/128

4586/4586 - 24s - 5ms/step - ia: 0.6378 - loss: 0.3811 - mae: 0.4705 - rmse: 0.5928 - smape: 0.9199 - val_ia: 0.2066 - val_loss: 0.2842 - val_mae: 0.4369 - val_rmse: 0.4498 - val_smape: 0.9023

Epoch 41/128

4586/4586 - 24s - 5ms/step - ia: 0.6362 - loss: 0.3816 - mae: 0.4703 - rmse: 0.5938 - smape: 0.9185 - val_ia: 0.2071 - val_loss: 0.2824 - val_mae: 0.4354 - val_rmse: 0.4483 - val_smape: 0.8984

Epoch 42/128

4586/4586 - 24s - 5ms/step - ia: 0.6406 - loss: 0.3772 - mae: 0.4678 - rmse: 0.5896 - smape: 0.9142 - val_ia: 0.2073 - val_loss: 0.2817 - val_mae: 0.4349 - val_rmse: 0.4478 - val_smape: 0.8962

Epoch 43/128

4586/4586 - 24s - 5ms/step - ia: 0.6398 - loss: 0.3753 - mae: 0.4668 - rmse: 0.5881 - smape: 0.9103 - val_ia: 0.2079 - val_loss: 0.2800 - val_mae: 0.4334 - val_rmse: 0.4463 - val_smape: 0.8924

Epoch 44/128

4586/4586 - 24s - 5ms/step - ia: 0.6418 - loss: 0.3734 - mae: 0.4642 - rmse: 0.5868 - smape: 0.9059 - val_ia: 0.2086 - val_loss: 0.2780 - val_mae: 0.4316 - val_rmse: 0.4445 - val_smape: 0.8881

Epoch 45/128

4586/4586 - 24s - 5ms/step - ia: 0.6447 - loss: 0.3690 - mae: 0.4625 - rmse: 0.5833 - smape: 0.9025 - val_ia: 0.2089 - val_loss: 0.2772 - val_mae: 0.4309 - val_rmse: 0.4438 - val_smape: 0.8857

Epoch 46/128

4586/4586 - 41s - 9ms/step - ia: 0.6456 - loss: 0.3660 - mae: 0.4603 - rmse: 0.5812 - smape: 0.8984 - val_ia: 0.2095 - val_loss: 0.2754 - val_mae: 0.4292 - val_rmse: 0.4421 - val_smape: 0.8817

Epoch 47/128

4586/4586 - 24s - 5ms/step - ia: 0.6510 - loss: 0.3593 - mae: 0.4554 - rmse: 0.5751 - smape: 0.8910 - val_ia: 0.2101 - val_loss: 0.2739 - val_mae: 0.4279 - val_rmse: 0.4409 - val_smape: 0.8781

Epoch 48/128

4586/4586 - 25s - 5ms/step - ia: 0.6473 - loss: 0.3659 - mae: 0.4590 - rmse: 0.5808 - smape: 0.8915 - val_ia: 0.2105 - val_loss: 0.2727 - val_mae: 0.4269 - val_rmse: 0.4398 - val_smape: 0.8751

Epoch 49/128

4586/4586 - 25s - 5ms/step - ia: 0.6487 - loss: 0.3651 - mae: 0.4584 - rmse: 0.5802 - smape: 0.8876 - val_ia: 0.2107 - val_loss: 0.2723 - val_mae: 0.4265 - val_rmse: 0.4394 - val_smape: 0.8731

Epoch 50/128

4586/4586 - 25s - 5ms/step - ia: 0.6534 - loss: 0.3569 - mae: 0.4543 - rmse: 0.5736 - smape: 0.8817 - val_ia: 0.2111 - val_loss: 0.2715 - val_mae: 0.4258 - val_rmse: 0.4387 - val_smape: 0.8706

Epoch 51/128

4586/4586 - 25s - 5ms/step - ia: 0.6517 - loss: 0.3588 - mae: 0.4537 - rmse: 0.5741 - smape: 0.8832 - val_ia: 0.2116 - val_loss: 0.2704 - val_mae: 0.4248 - val_rmse: 0.4378 - val_smape: 0.8676

Epoch 52/128

4586/4586 - 24s - 5ms/step - ia: 0.6534 - loss: 0.3566 - mae: 0.4528 - rmse: 0.5721 - smape: 0.8787 - val_ia: 0.2119 - val_loss: 0.2699 - val_mae: 0.4243 - val_rmse: 0.4372 - val_smape: 0.8656

Epoch 53/128

4586/4586 - 24s - 5ms/step - ia: 0.6567 - loss: 0.3526 - mae: 0.4495 - rmse: 0.5700 - smape: 0.8753 - val_ia: 0.2122 - val_loss: 0.2692 - val_mae: 0.4236 - val_rmse: 0.4366 - val_smape: 0.8632

Epoch 54/128

4586/4586 - 41s - 9ms/step - ia: 0.6577 - loss: 0.3500 - mae: 0.4477 - rmse: 0.5667 - smape: 0.8665 - val_ia: 0.2128 - val_loss: 0.2679 - val_mae: 0.4225 - val_rmse: 0.4355 - val_smape: 0.8599

Epoch 55/128

4586/4586 - 24s - 5ms/step - ia: 0.6590 - loss: 0.3497 - mae: 0.4485 - rmse: 0.5669 - smape: 0.8708 - val_ia: 0.2131 - val_loss: 0.2674 - val_mae: 0.4219 - val_rmse: 0.4349 - val_smape: 0.8578

Epoch 56/128

4586/4586 - 43s - 9ms/step - ia: 0.6598 - loss: 0.3482 - mae: 0.4468 - rmse: 0.5654 - smape: 0.8674 - val_ia: 0.2132 - val_loss: 0.2671 - val_mae: 0.4217 - val_rmse: 0.4347 - val_smape: 0.8565

Epoch 57/128

4586/4586 - 25s - 5ms/step - ia: 0.6621 - loss: 0.3455 - mae: 0.4448 - rmse: 0.5633 - smape: 0.8660 - val_ia: 0.2136 - val_loss: 0.2663 - val_mae: 0.4209 - val_rmse: 0.4339 - val_smape: 0.8540

Epoch 58/128

4586/4586 - 25s - 5ms/step - ia: 0.6635 - loss: 0.3408 - mae: 0.4420 - rmse: 0.5599 - smape: 0.8593 - val_ia: 0.2139 - val_loss: 0.2657 - val_mae: 0.4203 - val_rmse: 0.4333 - val_smape: 0.8521

Epoch 59/128

4586/4586 - 24s - 5ms/step - ia: 0.6649 - loss: 0.3419 - mae: 0.4413 - rmse: 0.5603 - smape: 0.8559 - val_ia: 0.2145 - val_loss: 0.2646 - val_mae: 0.4192 - val_rmse: 0.4322 - val_smape: 0.8491

Epoch 60/128

4586/4586 - 24s - 5ms/step - ia: 0.6623 - loss: 0.3435 - mae: 0.4442 - rmse: 0.5617 - smape: 0.8590 - val_ia: 0.2151 - val_loss: 0.2638 - val_mae: 0.4184 - val_rmse: 0.4314 - val_smape: 0.8466

Epoch 61/128

4586/4586 - 41s - 9ms/step - ia: 0.6667 - loss: 0.3382 - mae: 0.4392 - rmse: 0.5576 - smape: 0.8522 - val_ia: 0.2157 - val_loss: 0.2630 - val_mae: 0.4176 - val_rmse: 0.4307 - val_smape: 0.8442

Epoch 62/128

4586/4586 - 24s - 5ms/step - ia: 0.6693 - loss: 0.3349 - mae: 0.4367 - rmse: 0.5538 - smape: 0.8464 - val_ia: 0.2161 - val_loss: 0.2625 - val_mae: 0.4170 - val_rmse: 0.4301 - val_smape: 0.8423

Epoch 63/128

4586/4586 - 24s - 5ms/step - ia: 0.6671 - loss: 0.3350 - mae: 0.4378 - rmse: 0.5550 - smape: 0.8515 - val_ia: 0.2167 - val_loss: 0.2612 - val_mae: 0.4157 - val_rmse: 0.4288 - val_smape: 0.8389

Epoch 64/128

4586/4586 - 24s - 5ms/step - ia: 0.6663 - loss: 0.3386 - mae: 0.4398 - rmse: 0.5579 - smape: 0.8507 - val_ia: 0.2168 - val_loss: 0.2615 - val_mae: 0.4159 - val_rmse: 0.4290 - val_smape: 0.8381

Epoch 65/128

4586/4586 - 24s - 5ms/step - ia: 0.6685 - loss: 0.3361 - mae: 0.4375 - rmse: 0.5557 - smape: 0.8435 - val_ia: 0.2171 - val_loss: 0.2606 - val_mae: 0.4152 - val_rmse: 0.4283 - val_smape: 0.8355

Epoch 66/128

4586/4586 - 24s - 5ms/step - ia: 0.6703 - loss: 0.3337 - mae: 0.4350 - rmse: 0.5526 - smape: 0.8428 - val_ia: 0.2173 - val_loss: 0.2601 - val_mae: 0.4146 - val_rmse: 0.4277 - val_smape: 0.8335

Epoch 67/128

4586/4586 - 26s - 6ms/step - ia: 0.6714 - loss: 0.3312 - mae: 0.4340 - rmse: 0.5507 - smape: 0.8429 - val_ia: 0.2176 - val_loss: 0.2593 - val_mae: 0.4137 - val_rmse: 0.4268 - val_smape: 0.8311

Epoch 68/128

4586/4586 - 25s - 5ms/step - ia: 0.6724 - loss: 0.3305 - mae: 0.4343 - rmse: 0.5506 - smape: 0.8365 - val_ia: 0.2174 - val_loss: 0.2598 - val_mae: 0.4141 - val_rmse: 0.4272 - val_smape: 0.8307

Epoch 69/128

4586/4586 - 24s - 5ms/step - ia: 0.6735 - loss: 0.3285 - mae: 0.4322 - rmse: 0.5487 - smape: 0.8360 - val_ia: 0.2175 - val_loss: 0.2597 - val_mae: 0.4140 - val_rmse: 0.4271 - val_smape: 0.8294

Epoch 70/128

4586/4586 - 24s - 5ms/step - ia: 0.6758 - loss: 0.3229 - mae: 0.4286 - rmse: 0.5444 - smape: 0.8318 - val_ia: 0.2177 - val_loss: 0.2594 - val_mae: 0.4137 - val_rmse: 0.4267 - val_smape: 0.8277

Epoch 71/128

4586/4586 - 24s - 5ms/step - ia: 0.6764 - loss: 0.3230 - mae: 0.4284 - rmse: 0.5436 - smape: 0.8284 - val_ia: 0.2184 - val_loss: 0.2580 - val_mae: 0.4122 - val_rmse: 0.4253 - val_smape: 0.8244

Epoch 72/128

4586/4586 - 41s - 9ms/step - ia: 0.6769 - loss: 0.3235 - mae: 0.4284 - rmse: 0.5443 - smape: 0.8270 - val_ia: 0.2186 - val_loss: 0.2576 - val_mae: 0.4118 - val_rmse: 0.4249 - val_smape: 0.8226

Epoch 73/128

4586/4586 - 24s - 5ms/step - ia: 0.6771 - loss: 0.3265 - mae: 0.4297 - rmse: 0.5469 - smape: 0.8297 - val_ia: 0.2186 - val_loss: 0.2579 - val_mae: 0.4120 - val_rmse: 0.4251 - val_smape: 0.8221

Epoch 74/128

4586/4586 - 41s - 9ms/step - ia: 0.6810 - loss: 0.3165 - mae: 0.4241 - rmse: 0.5383 - smape: 0.8211 - val_ia: 0.2191 - val_loss: 0.2568 - val_mae: 0.4110 - val_rmse: 0.4241 - val_smape: 0.8193

Epoch 75/128

4586/4586 - 24s - 5ms/step - ia: 0.6786 - loss: 0.3195 - mae: 0.4269 - rmse: 0.5398 - smape: 0.8300 - val_ia: 0.2191 - val_loss: 0.2569 - val_mae: 0.4110 - val_rmse: 0.4241 - val_smape: 0.8184

Epoch 76/128

4586/4586 - 24s - 5ms/step - ia: 0.6808 - loss: 0.3175 - mae: 0.4238 - rmse: 0.5390 - smape: 0.8174 - val_ia: 0.2193 - val_loss: 0.2566 - val_mae: 0.4106 - val_rmse: 0.4237 - val_smape: 0.8171

Epoch 77/128

4586/4586 - 25s - 5ms/step - ia: 0.6777 - loss: 0.3216 - mae: 0.4269 - rmse: 0.5428 - smape: 0.8242 - val_ia: 0.2198 - val_loss: 0.2556 - val_mae: 0.4097 - val_rmse: 0.4228 - val_smape: 0.8147

Epoch 78/128

4586/4586 - 40s - 9ms/step - ia: 0.6790 - loss: 0.3212 - mae: 0.4266 - rmse: 0.5417 - smape: 0.8203 - val_ia: 0.2200 - val_loss: 0.2552 - val_mae: 0.4093 - val_rmse: 0.4224 - val_smape: 0.8132

Epoch 79/128

4586/4586 - 24s - 5ms/step - ia: 0.6809 - loss: 0.3169 - mae: 0.4235 - rmse: 0.5390 - smape: 0.8160 - val_ia: 0.2201 - val_loss: 0.2549 - val_mae: 0.4090 - val_rmse: 0.4221 - val_smape: 0.8120

Epoch 80/128

4586/4586 - 41s - 9ms/step - ia: 0.6802 - loss: 0.3190 - mae: 0.4240 - rmse: 0.5396 - smape: 0.8194 - val_ia: 0.2201 - val_loss: 0.2550 - val_mae: 0.4092 - val_rmse: 0.4223 - val_smape: 0.8116

Epoch 81/128

4586/4586 - 24s - 5ms/step - ia: 0.6805 - loss: 0.3205 - mae: 0.4249 - rmse: 0.5413 - smape: 0.8184 - val_ia: 0.2202 - val_loss: 0.2549 - val_mae: 0.4090 - val_rmse: 0.4221 - val_smape: 0.8107

Epoch 82/128

4586/4586 - 24s - 5ms/step - ia: 0.6838 - loss: 0.3165 - mae: 0.4218 - rmse: 0.5377 - smape: 0.8132 - val_ia: 0.2204 - val_loss: 0.2546 - val_mae: 0.4088 - val_rmse: 0.4219 - val_smape: 0.8094

Epoch 83/128

4586/4586 - 24s - 5ms/step - ia: 0.6851 - loss: 0.3111 - mae: 0.4187 - rmse: 0.5334 - smape: 0.8108 - val_ia: 0.2204 - val_loss: 0.2546 - val_mae: 0.4088 - val_rmse: 0.4219 - val_smape: 0.8086

Epoch 84/128

4586/4586 - 24s - 5ms/step - ia: 0.6875 - loss: 0.3086 - mae: 0.4168 - rmse: 0.5315 - smape: 0.8052 - val_ia: 0.2207 - val_loss: 0.2540 - val_mae: 0.4082 - val_rmse: 0.4213 - val_smape: 0.8071

Epoch 85/128

4586/4586 - 24s - 5ms/step - ia: 0.6859 - loss: 0.3087 - mae: 0.4172 - rmse: 0.5314 - smape: 0.8058 - val_ia: 0.2212 - val_loss: 0.2528 - val_mae: 0.4071 - val_rmse: 0.4202 - val_smape: 0.8044

Epoch 86/128

4586/4586 - 24s - 5ms/step - ia: 0.6856 - loss: 0.3111 - mae: 0.4189 - rmse: 0.5332 - smape: 0.8077 - val_ia: 0.2215 - val_loss: 0.2522 - val_mae: 0.4066 - val_rmse: 0.4197 - val_smape: 0.8028

Epoch 87/128

4586/4586 - 25s - 5ms/step - ia: 0.6863 - loss: 0.3096 - mae: 0.4178 - rmse: 0.5316 - smape: 0.8041 - val_ia: 0.2216 - val_loss: 0.2518 - val_mae: 0.4062 - val_rmse: 0.4193 - val_smape: 0.8016

Epoch 88/128

4586/4586 - 24s - 5ms/step - ia: 0.6871 - loss: 0.3082 - mae: 0.4160 - rmse: 0.5303 - smape: 0.8059 - val_ia: 0.2220 - val_loss: 0.2510 - val_mae: 0.4055 - val_rmse: 0.4186 - val_smape: 0.7997

Epoch 89/128

4586/4586 - 24s - 5ms/step - ia: 0.6875 - loss: 0.3093 - mae: 0.4168 - rmse: 0.5319 - smape: 0.8052 - val_ia: 0.2223 - val_loss: 0.2504 - val_mae: 0.4049 - val_rmse: 0.4180 - val_smape: 0.7982

Epoch 90/128

4586/4586 - 24s - 5ms/step - ia: 0.6891 - loss: 0.3067 - mae: 0.4152 - rmse: 0.5290 - smape: 0.7971 - val_ia: 0.2224 - val_loss: 0.2502 - val_mae: 0.4047 - val_rmse: 0.4178 - val_smape: 0.7974

Epoch 91/128

4586/4586 - 24s - 5ms/step - ia: 0.6871 - loss: 0.3097 - mae: 0.4171 - rmse: 0.5320 - smape: 0.8038 - val_ia: 0.2225 - val_loss: 0.2501 - val_mae: 0.4047 - val_rmse: 0.4177 - val_smape: 0.7966

Epoch 92/128

4586/4586 - 24s - 5ms/step - ia: 0.6878 - loss: 0.3076 - mae: 0.4138 - rmse: 0.5291 - smape: 0.7930 - val_ia: 0.2230 - val_loss: 0.2488 - val_mae: 0.4034 - val_rmse: 0.4165 - val_smape: 0.7941

Epoch 93/128

4586/4586 - 24s - 5ms/step - ia: 0.6893 - loss: 0.3056 - mae: 0.4137 - rmse: 0.5282 - smape: 0.7920 - val_ia: 0.2232 - val_loss: 0.2484 - val_mae: 0.4030 - val_rmse: 0.4161 - val_smape: 0.7930

Epoch 94/128

4586/4586 - 24s - 5ms/step - ia: 0.6875 - loss: 0.3073 - mae: 0.4164 - rmse: 0.5298 - smape: 0.7971 - val_ia: 0.2232 - val_loss: 0.2484 - val_mae: 0.4031 - val_rmse: 0.4162 - val_smape: 0.7926

Epoch 95/128

4586/4586 - 24s - 5ms/step - ia: 0.6882 - loss: 0.3041 - mae: 0.4142 - rmse: 0.5271 - smape: 0.7992 - val_ia: 0.2233 - val_loss: 0.2482 - val_mae: 0.4029 - val_rmse: 0.4160 - val_smape: 0.7917

Epoch 96/128

4586/4586 - 24s - 5ms/step - ia: 0.6897 - loss: 0.3039 - mae: 0.4128 - rmse: 0.5261 - smape: 0.7928 - val_ia: 0.2240 - val_loss: 0.2464 - val_mae: 0.4013 - val_rmse: 0.4144 - val_smape: 0.7885

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 8s - 27ms/step - ia: 0.6161 - loss: 0.4954 - mae: 0.5357 - rmse: 0.6602 - smape: 0.9657 - val_ia: 0.7755 - val_loss: 0.1455 - val_mae: 0.3013 - val_rmse: 0.3781 - val_smape: 0.6704

Epoch 2/128

287/287 - 4s - 13ms/step - ia: 0.7923 - loss: 0.1798 - mae: 0.3357 - rmse: 0.4225 - smape: 0.6772 - val_ia: 0.7993 - val_loss: 0.1181 - val_mae: 0.2769 - val_rmse: 0.3384 - val_smape: 0.6287

Epoch 3/128

287/287 - 4s - 13ms/step - ia: 0.8260 - loss: 0.1292 - mae: 0.2833 - rmse: 0.3582 - smape: 0.6091 - val_ia: 0.8198 - val_loss: 0.0953 - val_mae: 0.2508 - val_rmse: 0.2982 - val_smape: 0.5946

Epoch 4/128

287/287 - 5s - 18ms/step - ia: 0.8524 - loss: 0.0943 - mae: 0.2412 - rmse: 0.3059 - smape: 0.5422 - val_ia: 0.8421 - val_loss: 0.0764 - val_mae: 0.2205 - val_rmse: 0.2583 - val_smape: 0.5459

Epoch 5/128

287/287 - 4s - 13ms/step - ia: 0.8716 - loss: 0.0721 - mae: 0.2104 - rmse: 0.2676 - smape: 0.4888 - val_ia: 0.8612 - val_loss: 0.0606 - val_mae: 0.1922 - val_rmse: 0.2234 - val_smape: 0.4911

Epoch 6/128

287/287 - 4s - 13ms/step - ia: 0.8866 - loss: 0.0562 - mae: 0.1859 - rmse: 0.2365 - smape: 0.4433 - val_ia: 0.8892 - val_loss: 0.0365 - val_mae: 0.1503 - val_rmse: 0.1774 - val_smape: 0.4114

Epoch 7/128

287/287 - 4s - 13ms/step - ia: 0.8961 - loss: 0.0478 - mae: 0.1709 - rmse: 0.2180 - smape: 0.4090 - val_ia: 0.8964 - val_loss: 0.0314 - val_mae: 0.1397 - val_rmse: 0.1641 - val_smape: 0.3897

Epoch 8/128

287/287 - 5s - 18ms/step - ia: 0.9047 - loss: 0.0402 - mae: 0.1567 - rmse: 0.1997 - smape: 0.3845 - val_ia: 0.9151 - val_loss: 0.0211 - val_mae: 0.1139 - val_rmse: 0.1381 - val_smape: 0.3275

Epoch 9/128

287/287 - 4s - 13ms/step - ia: 0.9108 - loss: 0.0357 - mae: 0.1465 - rmse: 0.1882 - smape: 0.3649 - val_ia: 0.9300 - val_loss: 0.0150 - val_mae: 0.0944 - val_rmse: 0.1201 - val_smape: 0.2701

Epoch 10/128

287/287 - 4s - 13ms/step - ia: 0.9150 - loss: 0.0325 - mae: 0.1396 - rmse: 0.1797 - smape: 0.3519 - val_ia: 0.9216 - val_loss: 0.0177 - val_mae: 0.1052 - val_rmse: 0.1277 - val_smape: 0.3069

Epoch 11/128

287/287 - 4s - 13ms/step - ia: 0.9194 - loss: 0.0294 - mae: 0.1324 - rmse: 0.1708 - smape: 0.3350 - val_ia: 0.9333 - val_loss: 0.0136 - val_mae: 0.0896 - val_rmse: 0.1137 - val_smape: 0.2591

Epoch 12/128

287/287 - 4s - 13ms/step - ia: 0.9229 - loss: 0.0271 - mae: 0.1267 - rmse: 0.1639 - smape: 0.3223 - val_ia: 0.9344 - val_loss: 0.0135 - val_mae: 0.0876 - val_rmse: 0.1126 - val_smape: 0.2453

Epoch 13/128

287/287 - 4s - 13ms/step - ia: 0.9264 - loss: 0.0249 - mae: 0.1209 - rmse: 0.1571 - smape: 0.3102 - val_ia: 0.9400 - val_loss: 0.0118 - val_mae: 0.0804 - val_rmse: 0.1062 - val_smape: 0.2227

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.9291 - loss: 0.0231 - mae: 0.1164 - rmse: 0.1514 - smape: 0.3032 - val_ia: 0.9436 - val_loss: 0.0106 - val_mae: 0.0757 - val_rmse: 0.1012 - val_smape: 0.2107

Epoch 15/128

287/287 - 4s - 13ms/step - ia: 0.9315 - loss: 0.0217 - mae: 0.1125 - rmse: 0.1467 - smape: 0.2931 - val_ia: 0.9440 - val_loss: 0.0104 - val_mae: 0.0751 - val_rmse: 0.0993 - val_smape: 0.2132

Epoch 16/128

287/287 - 4s - 13ms/step - ia: 0.9338 - loss: 0.0204 - mae: 0.1087 - rmse: 0.1420 - smape: 0.2824 - val_ia: 0.9437 - val_loss: 0.0104 - val_mae: 0.0753 - val_rmse: 0.0989 - val_smape: 0.2141

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 0.9363 - loss: 0.0191 - mae: 0.1045 - rmse: 0.1375 - smape: 0.2750 - val_ia: 0.9504 - val_loss: 0.0086 - val_mae: 0.0666 - val_rmse: 0.0910 - val_smape: 0.1878

Epoch 18/128

287/287 - 4s - 13ms/step - ia: 0.9384 - loss: 0.0180 - mae: 0.1012 - rmse: 0.1333 - smape: 0.2683 - val_ia: 0.9466 - val_loss: 0.0094 - val_mae: 0.0714 - val_rmse: 0.0940 - val_smape: 0.2079

Epoch 19/128

287/287 - 4s - 13ms/step - ia: 0.9398 - loss: 0.0172 - mae: 0.0988 - rmse: 0.1301 - smape: 0.2581 - val_ia: 0.9506 - val_loss: 0.0083 - val_mae: 0.0661 - val_rmse: 0.0889 - val_smape: 0.1918

Epoch 20/128

287/287 - 4s - 13ms/step - ia: 0.9415 - loss: 0.0164 - mae: 0.0960 - rmse: 0.1273 - smape: 0.2529 - val_ia: 0.9464 - val_loss: 0.0092 - val_mae: 0.0716 - val_rmse: 0.0927 - val_smape: 0.2120

Epoch 21/128

287/287 - 4s - 13ms/step - ia: 0.9429 - loss: 0.0157 - mae: 0.0938 - rmse: 0.1241 - smape: 0.2496 - val_ia: 0.9537 - val_loss: 0.0075 - val_mae: 0.0620 - val_rmse: 0.0846 - val_smape: 0.1748

Epoch 22/128

287/287 - 4s - 13ms/step - ia: 0.9441 - loss: 0.0150 - mae: 0.0919 - rmse: 0.1217 - smape: 0.2440 - val_ia: 0.9537 - val_loss: 0.0074 - val_mae: 0.0619 - val_rmse: 0.0838 - val_smape: 0.1772

Epoch 23/128

287/287 - 5s - 18ms/step - ia: 0.9453 - loss: 0.0144 - mae: 0.0898 - rmse: 0.1191 - smape: 0.2386 - val_ia: 0.9568 - val_loss: 0.0065 - val_mae: 0.0580 - val_rmse: 0.0793 - val_smape: 0.1726

Epoch 24/128

287/287 - 4s - 13ms/step - ia: 0.9461 - loss: 0.0141 - mae: 0.0886 - rmse: 0.1179 - smape: 0.2368 - val_ia: 0.9554 - val_loss: 0.0068 - val_mae: 0.0597 - val_rmse: 0.0804 - val_smape: 0.1753

Epoch 25/128

287/287 - 4s - 13ms/step - ia: 0.9466 - loss: 0.0138 - mae: 0.0878 - rmse: 0.1165 - smape: 0.2349 - val_ia: 0.9561 - val_loss: 0.0065 - val_mae: 0.0588 - val_rmse: 0.0789 - val_smape: 0.1736

Epoch 26/128

287/287 - 5s - 18ms/step - ia: 0.9475 - loss: 0.0134 - mae: 0.0861 - rmse: 0.1150 - smape: 0.2276 - val_ia: 0.9558 - val_loss: 0.0067 - val_mae: 0.0591 - val_rmse: 0.0796 - val_smape: 0.1681

Epoch 27/128

287/287 - 5s - 18ms/step - ia: 0.9481 - loss: 0.0131 - mae: 0.0853 - rmse: 0.1137 - smape: 0.2288 - val_ia: 0.9574 - val_loss: 0.0063 - val_mae: 0.0571 - val_rmse: 0.0780 - val_smape: 0.1555

Epoch 28/128

287/287 - 4s - 13ms/step - ia: 0.9490 - loss: 0.0126 - mae: 0.0838 - rmse: 0.1115 - smape: 0.2249 - val_ia: 0.9574 - val_loss: 0.0063 - val_mae: 0.0570 - val_rmse: 0.0770 - val_smape: 0.1614

Epoch 29/128

287/287 - 5s - 18ms/step - ia: 0.9496 - loss: 0.0124 - mae: 0.0829 - rmse: 0.1103 - smape: 0.2245 - val_ia: 0.9607 - val_loss: 0.0055 - val_mae: 0.0528 - val_rmse: 0.0728 - val_smape: 0.1513

Epoch 30/128

287/287 - 4s - 13ms/step - ia: 0.9497 - loss: 0.0124 - mae: 0.0826 - rmse: 0.1104 - smape: 0.2236 - val_ia: 0.9610 - val_loss: 0.0055 - val_mae: 0.0525 - val_rmse: 0.0727 - val_smape: 0.1478

Epoch 31/128

287/287 - 4s - 13ms/step - ia: 0.9506 - loss: 0.0119 - mae: 0.0812 - rmse: 0.1083 - smape: 0.2185 - val_ia: 0.9559 - val_loss: 0.0065 - val_mae: 0.0589 - val_rmse: 0.0778 - val_smape: 0.1639

Epoch 32/128

287/287 - 4s - 13ms/step - ia: 0.9507 - loss: 0.0119 - mae: 0.0810 - rmse: 0.1083 - smape: 0.2167 - val_ia: 0.9616 - val_loss: 0.0052 - val_mae: 0.0516 - val_rmse: 0.0709 - val_smape: 0.1463

Epoch 33/128

287/287 - 4s - 13ms/step - ia: 0.9516 - loss: 0.0115 - mae: 0.0795 - rmse: 0.1065 - smape: 0.2142 - val_ia: 0.9614 - val_loss: 0.0053 - val_mae: 0.0519 - val_rmse: 0.0707 - val_smape: 0.1475

Epoch 34/128

287/287 - 5s - 18ms/step - ia: 0.9519 - loss: 0.0114 - mae: 0.0791 - rmse: 0.1058 - smape: 0.2116 - val_ia: 0.9588 - val_loss: 0.0058 - val_mae: 0.0551 - val_rmse: 0.0737 - val_smape: 0.1511

Epoch 35/128

287/287 - 4s - 13ms/step - ia: 0.9523 - loss: 0.0113 - mae: 0.0784 - rmse: 0.1051 - smape: 0.2108 - val_ia: 0.9590 - val_loss: 0.0057 - val_mae: 0.0551 - val_rmse: 0.0727 - val_smape: 0.1555

Epoch 36/128

287/287 - 4s - 13ms/step - ia: 0.9523 - loss: 0.0112 - mae: 0.0784 - rmse: 0.1050 - smape: 0.2111 - val_ia: 0.9594 - val_loss: 0.0056 - val_mae: 0.0544 - val_rmse: 0.0721 - val_smape: 0.1522

Epoch 37/128

287/287 - 4s - 13ms/step - ia: 0.9532 - loss: 0.0109 - mae: 0.0770 - rmse: 0.1033 - smape: 0.2074 - val_ia: 0.9623 - val_loss: 0.0050 - val_mae: 0.0506 - val_rmse: 0.0691 - val_smape: 0.1396

Epoch 38/128

287/287 - 4s - 13ms/step - ia: 0.9535 - loss: 0.0107 - mae: 0.0765 - rmse: 0.1023 - smape: 0.2083 - val_ia: 0.9598 - val_loss: 0.0054 - val_mae: 0.0539 - val_rmse: 0.0708 - val_smape: 0.1518

Epoch 39/128

287/287 - 4s - 13ms/step - ia: 0.9539 - loss: 0.0106 - mae: 0.0757 - rmse: 0.1019 - smape: 0.2066 - val_ia: 0.9593 - val_loss: 0.0056 - val_mae: 0.0544 - val_rmse: 0.0719 - val_smape: 0.1494

Epoch 40/128

287/287 - 4s - 13ms/step - ia: 0.9540 - loss: 0.0105 - mae: 0.0756 - rmse: 0.1014 - smape: 0.2051 - val_ia: 0.9655 - val_loss: 0.0043 - val_mae: 0.0468 - val_rmse: 0.0643 - val_smape: 0.1355

Epoch 41/128

287/287 - 4s - 13ms/step - ia: 0.9544 - loss: 0.0104 - mae: 0.0750 - rmse: 0.1012 - smape: 0.2023 - val_ia: 0.9599 - val_loss: 0.0053 - val_mae: 0.0538 - val_rmse: 0.0700 - val_smape: 0.1534

Epoch 42/128

287/287 - 4s - 13ms/step - ia: 0.9546 - loss: 0.0103 - mae: 0.0747 - rmse: 0.1003 - smape: 0.2035 - val_ia: 0.9663 - val_loss: 0.0041 - val_mae: 0.0457 - val_rmse: 0.0631 - val_smape: 0.1349

Epoch 43/128

287/287 - 4s - 13ms/step - ia: 0.9552 - loss: 0.0101 - mae: 0.0737 - rmse: 0.0992 - smape: 0.2015 - val_ia: 0.9648 - val_loss: 0.0043 - val_mae: 0.0475 - val_rmse: 0.0647 - val_smape: 0.1367

Epoch 44/128

287/287 - 4s - 13ms/step - ia: 0.9550 - loss: 0.0102 - mae: 0.0740 - rmse: 0.0999 - smape: 0.2014 - val_ia: 0.9604 - val_loss: 0.0052 - val_mae: 0.0530 - val_rmse: 0.0692 - val_smape: 0.1469

Epoch 45/128

287/287 - 4s - 13ms/step - ia: 0.9551 - loss: 0.0101 - mae: 0.0739 - rmse: 0.0996 - smape: 0.2015 - val_ia: 0.9641 - val_loss: 0.0045 - val_mae: 0.0482 - val_rmse: 0.0651 - val_smape: 0.1354

Epoch 46/128

287/287 - 4s - 13ms/step - ia: 0.9556 - loss: 0.0099 - mae: 0.0730 - rmse: 0.0982 - smape: 0.1993 - val_ia: 0.9656 - val_loss: 0.0041 - val_mae: 0.0465 - val_rmse: 0.0628 - val_smape: 0.1348

Epoch 47/128

287/287 - 4s - 13ms/step - ia: 0.9556 - loss: 0.0099 - mae: 0.0730 - rmse: 0.0986 - smape: 0.1964 - val_ia: 0.9659 - val_loss: 0.0041 - val_mae: 0.0461 - val_rmse: 0.0623 - val_smape: 0.1351

Epoch 48/128

287/287 - 4s - 13ms/step - ia: 0.9558 - loss: 0.0098 - mae: 0.0728 - rmse: 0.0980 - smape: 0.1987 - val_ia: 0.9674 - val_loss: 0.0038 - val_mae: 0.0443 - val_rmse: 0.0607 - val_smape: 0.1328

Epoch 49/128

287/287 - 4s - 13ms/step - ia: 0.9558 - loss: 0.0098 - mae: 0.0727 - rmse: 0.0977 - smape: 0.1969 - val_ia: 0.9679 - val_loss: 0.0037 - val_mae: 0.0434 - val_rmse: 0.0595 - val_smape: 0.1316

Epoch 50/128

287/287 - 4s - 13ms/step - ia: 0.9561 - loss: 0.0097 - mae: 0.0721 - rmse: 0.0974 - smape: 0.1971 - val_ia: 0.9652 - val_loss: 0.0042 - val_mae: 0.0467 - val_rmse: 0.0624 - val_smape: 0.1373

Epoch 51/128

287/287 - 5s - 18ms/step - ia: 0.9564 - loss: 0.0096 - mae: 0.0717 - rmse: 0.0969 - smape: 0.1962 - val_ia: 0.9664 - val_loss: 0.0040 - val_mae: 0.0455 - val_rmse: 0.0616 - val_smape: 0.1322

Epoch 52/128

287/287 - 4s - 13ms/step - ia: 0.9566 - loss: 0.0094 - mae: 0.0715 - rmse: 0.0962 - smape: 0.1953 - val_ia: 0.9650 - val_loss: 0.0042 - val_mae: 0.0471 - val_rmse: 0.0631 - val_smape: 0.1351

Epoch 53/128

287/287 - 4s - 13ms/step - ia: 0.9567 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0964 - smape: 0.1943 - val_ia: 0.9667 - val_loss: 0.0039 - val_mae: 0.0449 - val_rmse: 0.0607 - val_smape: 0.1310

Epoch 54/128

287/287 - 4s - 13ms/step - ia: 0.9563 - loss: 0.0096 - mae: 0.0717 - rmse: 0.0969 - smape: 0.1951 - val_ia: 0.9661 - val_loss: 0.0040 - val_mae: 0.0457 - val_rmse: 0.0615 - val_smape: 0.1341

Epoch 55/128

287/287 - 4s - 13ms/step - ia: 0.9571 - loss: 0.0093 - mae: 0.0706 - rmse: 0.0955 - smape: 0.1920 - val_ia: 0.9647 - val_loss: 0.0042 - val_mae: 0.0478 - val_rmse: 0.0637 - val_smape: 0.1392

Epoch 56/128

287/287 - 5s - 18ms/step - ia: 0.9566 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0966 - smape: 0.1929 - val_ia: 0.9655 - val_loss: 0.0041 - val_mae: 0.0463 - val_rmse: 0.0615 - val_smape: 0.1357

Epoch 57/128

287/287 - 4s - 13ms/step - ia: 0.9571 - loss: 0.0093 - mae: 0.0707 - rmse: 0.0954 - smape: 0.1931 - val_ia: 0.9670 - val_loss: 0.0038 - val_mae: 0.0444 - val_rmse: 0.0596 - val_smape: 0.1343

Epoch 58/128

287/287 - 4s - 13ms/step - ia: 0.9573 - loss: 0.0093 - mae: 0.0703 - rmse: 0.0952 - smape: 0.1917 - val_ia: 0.9632 - val_loss: 0.0044 - val_mae: 0.0493 - val_rmse: 0.0637 - val_smape: 0.1508

Epoch 59/128

287/287 - 4s - 13ms/step - ia: 0.9574 - loss: 0.0093 - mae: 0.0701 - rmse: 0.0951 - smape: 0.1907 - val_ia: 0.9671 - val_loss: 0.0037 - val_mae: 0.0444 - val_rmse: 0.0597 - val_smape: 0.1326

Epoch 60/128

287/287 - 5s - 18ms/step - ia: 0.9575 - loss: 0.0092 - mae: 0.0701 - rmse: 0.0948 - smape: 0.1909 - val_ia: 0.9608 - val_loss: 0.0049 - val_mae: 0.0523 - val_rmse: 0.0666 - val_smape: 0.1534

Epoch 61/128

287/287 - 4s - 13ms/step - ia: 0.9572 - loss: 0.0093 - mae: 0.0704 - rmse: 0.0953 - smape: 0.1911 - val_ia: 0.9622 - val_loss: 0.0046 - val_mae: 0.0505 - val_rmse: 0.0649 - val_smape: 0.1494

Epoch 62/128

287/287 - 4s - 13ms/step - ia: 0.9575 - loss: 0.0092 - mae: 0.0699 - rmse: 0.0950 - smape: 0.1909 - val_ia: 0.9654 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0612 - val_smape: 0.1372

Epoch 63/128

287/287 - 4s - 13ms/step - ia: 0.9575 - loss: 0.0091 - mae: 0.0698 - rmse: 0.0945 - smape: 0.1893 - val_ia: 0.9657 - val_loss: 0.0040 - val_mae: 0.0461 - val_rmse: 0.0610 - val_smape: 0.1361

Epoch 64/128

287/287 - 4s - 13ms/step - ia: 0.9575 - loss: 0.0091 - mae: 0.0699 - rmse: 0.0944 - smape: 0.1909 - val_ia: 0.9682 - val_loss: 0.0035 - val_mae: 0.0432 - val_rmse: 0.0584 - val_smape: 0.1332

Epoch 65/128

287/287 - 4s - 13ms/step - ia: 0.9576 - loss: 0.0091 - mae: 0.0697 - rmse: 0.0944 - smape: 0.1883 - val_ia: 0.9666 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0600 - val_smape: 0.1327

Epoch 66/128

287/287 - 4s - 13ms/step - ia: 0.9579 - loss: 0.0090 - mae: 0.0691 - rmse: 0.0938 - smape: 0.1879 - val_ia: 0.9664 - val_loss: 0.0038 - val_mae: 0.0453 - val_rmse: 0.0603 - val_smape: 0.1339

Epoch 67/128

287/287 - 4s - 13ms/step - ia: 0.9575 - loss: 0.0091 - mae: 0.0698 - rmse: 0.0942 - smape: 0.1889 - val_ia: 0.9638 - val_loss: 0.0043 - val_mae: 0.0484 - val_rmse: 0.0629 - val_smape: 0.1418

Epoch 68/128

287/287 - 5s - 18ms/step - ia: 0.9579 - loss: 0.0090 - mae: 0.0694 - rmse: 0.0940 - smape: 0.1873 - val_ia: 0.9643 - val_loss: 0.0042 - val_mae: 0.0477 - val_rmse: 0.0623 - val_smape: 0.1393

Epoch 69/128

287/287 - 5s - 18ms/step - ia: 0.9579 - loss: 0.0090 - mae: 0.0692 - rmse: 0.0937 - smape: 0.1880 - val_ia: 0.9671 - val_loss: 0.0037 - val_mae: 0.0442 - val_rmse: 0.0588 - val_smape: 0.1355

Epoch 70/128

287/287 - 4s - 13ms/step - ia: 0.9582 - loss: 0.0089 - mae: 0.0687 - rmse: 0.0933 - smape: 0.1871 - val_ia: 0.9666 - val_loss: 0.0037 - val_mae: 0.0449 - val_rmse: 0.0597 - val_smape: 0.1347

Epoch 71/128

287/287 - 4s - 13ms/step - ia: 0.9583 - loss: 0.0088 - mae: 0.0687 - rmse: 0.0929 - smape: 0.1870 - val_ia: 0.9665 - val_loss: 0.0038 - val_mae: 0.0451 - val_rmse: 0.0598 - val_smape: 0.1338

Epoch 72/128

287/287 - 4s - 13ms/step - ia: 0.9578 - loss: 0.0091 - mae: 0.0694 - rmse: 0.0942 - smape: 0.1862 - val_ia: 0.9673 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0589 - val_smape: 0.1340

Epoch 73/128

287/287 - 4s - 13ms/step - ia: 0.9584 - loss: 0.0088 - mae: 0.0685 - rmse: 0.0929 - smape: 0.1866 - val_ia: 0.9662 - val_loss: 0.0038 - val_mae: 0.0456 - val_rmse: 0.0605 - val_smape: 0.1355

Epoch 74/128

287/287 - 4s - 13ms/step - ia: 0.9582 - loss: 0.0089 - mae: 0.0688 - rmse: 0.0932 - smape: 0.1881 - val_ia: 0.9692 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0564 - val_smape: 0.1306

Epoch 75/128

287/287 - 4s - 13ms/step - ia: 0.9586 - loss: 0.0087 - mae: 0.0681 - rmse: 0.0923 - smape: 0.1850 - val_ia: 0.9687 - val_loss: 0.0034 - val_mae: 0.0423 - val_rmse: 0.0569 - val_smape: 0.1318

Epoch 76/128

287/287 - 5s - 18ms/step - ia: 0.9588 - loss: 0.0087 - mae: 0.0678 - rmse: 0.0920 - smape: 0.1851 - val_ia: 0.9640 - val_loss: 0.0042 - val_mae: 0.0481 - val_rmse: 0.0627 - val_smape: 0.1393

Epoch 77/128

287/287 - 4s - 13ms/step - ia: 0.9587 - loss: 0.0087 - mae: 0.0679 - rmse: 0.0923 - smape: 0.1861 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0438 - val_rmse: 0.0584 - val_smape: 0.1339

Epoch 78/128

287/287 - 4s - 13ms/step - ia: 0.9587 - loss: 0.0087 - mae: 0.0678 - rmse: 0.0924 - smape: 0.1845 - val_ia: 0.9665 - val_loss: 0.0037 - val_mae: 0.0449 - val_rmse: 0.0590 - val_smape: 0.1398

Epoch 79/128

287/287 - 4s - 13ms/step - ia: 0.9583 - loss: 0.0089 - mae: 0.0685 - rmse: 0.0931 - smape: 0.1840 - val_ia: 0.9647 - val_loss: 0.0040 - val_mae: 0.0471 - val_rmse: 0.0609 - val_smape: 0.1485

Epoch 80/128

287/287 - 4s - 13ms/step - ia: 0.9588 - loss: 0.0087 - mae: 0.0679 - rmse: 0.0922 - smape: 0.1836 - val_ia: 0.9651 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0604 - val_smape: 0.1413

Epoch 81/128

287/287 - 4s - 13ms/step - ia: 0.9586 - loss: 0.0087 - mae: 0.0680 - rmse: 0.0924 - smape: 0.1864 - val_ia: 0.9683 - val_loss: 0.0034 - val_mae: 0.0426 - val_rmse: 0.0569 - val_smape: 0.1319

Epoch 82/128

287/287 - 4s - 13ms/step - ia: 0.9586 - loss: 0.0087 - mae: 0.0680 - rmse: 0.0922 - smape: 0.1850 - val_ia: 0.9669 - val_loss: 0.0037 - val_mae: 0.0444 - val_rmse: 0.0586 - val_smape: 0.1346

Epoch 83/128

287/287 - 4s - 13ms/step - ia: 0.9587 - loss: 0.0088 - mae: 0.0679 - rmse: 0.0926 - smape: 0.1831 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0436 - val_rmse: 0.0581 - val_smape: 0.1325

Epoch 84/128

287/287 - 4s - 13ms/step - ia: 0.9589 - loss: 0.0086 - mae: 0.0677 - rmse: 0.0918 - smape: 0.1858 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0575 - val_smape: 0.1350

Epoch 85/128

287/287 - 4s - 13ms/step - ia: 0.9595 - loss: 0.0084 - mae: 0.0668 - rmse: 0.0906 - smape: 0.1835 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0434 - val_rmse: 0.0576 - val_smape: 0.1331

Epoch 86/128

287/287 - 4s - 13ms/step - ia: 0.9591 - loss: 0.0085 - mae: 0.0672 - rmse: 0.0912 - smape: 0.1829 - val_ia: 0.9685 - val_loss: 0.0034 - val_mae: 0.0423 - val_rmse: 0.0567 - val_smape: 0.1335

Epoch 87/128

287/287 - 4s - 13ms/step - ia: 0.9591 - loss: 0.0086 - mae: 0.0674 - rmse: 0.0914 - smape: 0.1832 - val_ia: 0.9681 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0575 - val_smape: 0.1325

Epoch 88/128

287/287 - 4s - 13ms/step - ia: 0.9593 - loss: 0.0085 - mae: 0.0669 - rmse: 0.0911 - smape: 0.1812 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0417 - val_rmse: 0.0563 - val_smape: 0.1296

Epoch 89/128

287/287 - 4s - 13ms/step - ia: 0.9590 - loss: 0.0086 - mae: 0.0673 - rmse: 0.0917 - smape: 0.1837 - val_ia: 0.9685 - val_loss: 0.0034 - val_mae: 0.0425 - val_rmse: 0.0570 - val_smape: 0.1309

Epoch 90/128

287/287 - 4s - 13ms/step - ia: 0.9588 - loss: 0.0087 - mae: 0.0677 - rmse: 0.0919 - smape: 0.1839 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0580 - val_smape: 0.1341

Epoch 91/128

287/287 - 4s - 13ms/step - ia: 0.9594 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0910 - smape: 0.1807 - val_ia: 0.9670 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0583 - val_smape: 0.1349

Epoch 92/128

287/287 - 5s - 18ms/step - ia: 0.9594 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0909 - smape: 0.1799 - val_ia: 0.9684 - val_loss: 0.0034 - val_mae: 0.0424 - val_rmse: 0.0567 - val_smape: 0.1311

Epoch 93/128

287/287 - 5s - 18ms/step - ia: 0.9593 - loss: 0.0085 - mae: 0.0669 - rmse: 0.0912 - smape: 0.1807 - val_ia: 0.9702 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0555 - val_smape: 0.1293

Epoch 94/128

287/287 - 4s - 13ms/step - ia: 0.9591 - loss: 0.0085 - mae: 0.0672 - rmse: 0.0913 - smape: 0.1818 - val_ia: 0.9647 - val_loss: 0.0040 - val_mae: 0.0470 - val_rmse: 0.0605 - val_smape: 0.1431

Epoch 95/128

287/287 - 4s - 13ms/step - ia: 0.9594 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0912 - smape: 0.1813 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0434 - val_rmse: 0.0574 - val_smape: 0.1324

Epoch 96/128

287/287 - 5s - 18ms/step - ia: 0.9597 - loss: 0.0083 - mae: 0.0663 - rmse: 0.0900 - smape: 0.1803 - val_ia: 0.9694 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0553 - val_smape: 0.1309

Epoch 97/128

287/287 - 4s - 13ms/step - ia: 0.9593 - loss: 0.0086 - mae: 0.0670 - rmse: 0.0915 - smape: 0.1815 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0583 - val_smape: 0.1306

Epoch 98/128


In [21]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}