Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [4]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [5]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [6]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [7]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [8]:
datosNormalizados.shape

(52416, 5)

In [9]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [10]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [11]:
futuros = 1
pasados  = 12

In [12]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [13]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [14]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [15]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 12, 5)
Las dimensiones de testX son:  (10533, 12, 5)
Las dimensiones de valX son:  (5189, 12, 5)

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [17]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [18]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [19]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [20]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 17s - 61ms/step - ia: 0.1997 - loss: 1.0927 - mae: 0.8645 - rmse: 1.0438 - smape: 1.5746 - val_ia: 0.2207 - val_loss: 0.8478 - val_mae: 0.7655 - val_rmse: 0.9150 - val_smape: 1.8570

Epoch 2/128

287/287 - 4s - 14ms/step - ia: 0.1697 - loss: 1.0112 - mae: 0.8337 - rmse: 1.0042 - smape: 1.6164 - val_ia: 0.2492 - val_loss: 0.7913 - val_mae: 0.7381 - val_rmse: 0.8833 - val_smape: 1.7562

Epoch 3/128

287/287 - 5s - 18ms/step - ia: 0.2833 - loss: 0.8356 - mae: 0.7489 - rmse: 0.9113 - smape: 1.4313 - val_ia: 0.4716 - val_loss: 0.4918 - val_mae: 0.5711 - val_rmse: 0.6943 - val_smape: 1.0538

Epoch 4/128

287/287 - 5s - 18ms/step - ia: 0.5623 - loss: 0.5214 - mae: 0.5787 - rmse: 0.7195 - smape: 1.0024 - val_ia: 0.6724 - val_loss: 0.3068 - val_mae: 0.4375 - val_rmse: 0.5477 - val_smape: 0.7537

Epoch 5/128

287/287 - 5s - 18ms/step - ia: 0.6589 - loss: 0.4026 - mae: 0.5042 - rmse: 0.6331 - smape: 0.8501 - val_ia: 0.7172 - val_loss: 0.2410 - val_mae: 0.3871 - val_rmse: 0.4868 - val_smape: 0.6966

Epoch 6/128

287/287 - 5s - 18ms/step - ia: 0.6880 - loss: 0.3557 - mae: 0.4716 - rmse: 0.5951 - smape: 0.8022 - val_ia: 0.7338 - val_loss: 0.2145 - val_mae: 0.3702 - val_rmse: 0.4588 - val_smape: 0.6782

Epoch 7/128

287/287 - 5s - 16ms/step - ia: 0.7042 - loss: 0.3281 - mae: 0.4515 - rmse: 0.5716 - smape: 0.7733 - val_ia: 0.7508 - val_loss: 0.1850 - val_mae: 0.3474 - val_rmse: 0.4274 - val_smape: 0.6495

Epoch 8/128

287/287 - 4s - 15ms/step - ia: 0.7145 - loss: 0.3107 - mae: 0.4391 - rmse: 0.5561 - smape: 0.7558 - val_ia: 0.7599 - val_loss: 0.1688 - val_mae: 0.3327 - val_rmse: 0.4084 - val_smape: 0.6339

Epoch 9/128

287/287 - 4s - 14ms/step - ia: 0.7249 - loss: 0.2919 - mae: 0.4251 - rmse: 0.5389 - smape: 0.7376 - val_ia: 0.7686 - val_loss: 0.1538 - val_mae: 0.3188 - val_rmse: 0.3902 - val_smape: 0.6160

Epoch 10/128

287/287 - 6s - 20ms/step - ia: 0.7292 - loss: 0.2831 - mae: 0.4185 - rmse: 0.5310 - smape: 0.7321 - val_ia: 0.7728 - val_loss: 0.1472 - val_mae: 0.3140 - val_rmse: 0.3818 - val_smape: 0.6092

Epoch 11/128

287/287 - 4s - 15ms/step - ia: 0.7361 - loss: 0.2717 - mae: 0.4091 - rmse: 0.5199 - smape: 0.7187 - val_ia: 0.7732 - val_loss: 0.1455 - val_mae: 0.3141 - val_rmse: 0.3795 - val_smape: 0.6102

Epoch 12/128

287/287 - 4s - 13ms/step - ia: 0.7425 - loss: 0.2614 - mae: 0.4003 - rmse: 0.5101 - smape: 0.7060 - val_ia: 0.7834 - val_loss: 0.1312 - val_mae: 0.2978 - val_rmse: 0.3605 - val_smape: 0.5895

Epoch 13/128

287/287 - 4s - 14ms/step - ia: 0.7478 - loss: 0.2541 - mae: 0.3928 - rmse: 0.5028 - smape: 0.6957 - val_ia: 0.7853 - val_loss: 0.1281 - val_mae: 0.2956 - val_rmse: 0.3561 - val_smape: 0.5881

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.7510 - loss: 0.2477 - mae: 0.3879 - rmse: 0.4967 - smape: 0.6934 - val_ia: 0.7955 - val_loss: 0.1159 - val_mae: 0.2801 - val_rmse: 0.3388 - val_smape: 0.5645

Epoch 15/128

287/287 - 5s - 18ms/step - ia: 0.7545 - loss: 0.2421 - mae: 0.3830 - rmse: 0.4908 - smape: 0.6840 - val_ia: 0.7987 - val_loss: 0.1112 - val_mae: 0.2743 - val_rmse: 0.3315 - val_smape: 0.5599

Epoch 16/128

287/287 - 4s - 14ms/step - ia: 0.7562 - loss: 0.2389 - mae: 0.3799 - rmse: 0.4876 - smape: 0.6843 - val_ia: 0.8009 - val_loss: 0.1081 - val_mae: 0.2707 - val_rmse: 0.3264 - val_smape: 0.5565

Epoch 17/128

287/287 - 5s - 19ms/step - ia: 0.7596 - loss: 0.2329 - mae: 0.3749 - rmse: 0.4813 - smape: 0.6802 - val_ia: 0.8165 - val_loss: 0.0933 - val_mae: 0.2477 - val_rmse: 0.3035 - val_smape: 0.5197

Epoch 18/128

287/287 - 4s - 14ms/step - ia: 0.7655 - loss: 0.2240 - mae: 0.3658 - rmse: 0.4719 - smape: 0.6669 - val_ia: 0.8173 - val_loss: 0.0920 - val_mae: 0.2462 - val_rmse: 0.3009 - val_smape: 0.5224

Epoch 19/128

287/287 - 5s - 17ms/step - ia: 0.7677 - loss: 0.2204 - mae: 0.3632 - rmse: 0.4681 - smape: 0.6623 - val_ia: 0.8199 - val_loss: 0.0887 - val_mae: 0.2393 - val_rmse: 0.2946 - val_smape: 0.5126

Epoch 20/128

287/287 - 5s - 19ms/step - ia: 0.7687 - loss: 0.2185 - mae: 0.3607 - rmse: 0.4663 - smape: 0.6625 - val_ia: 0.8274 - val_loss: 0.0830 - val_mae: 0.2299 - val_rmse: 0.2851 - val_smape: 0.5010

Epoch 21/128

287/287 - 5s - 18ms/step - ia: 0.7714 - loss: 0.2130 - mae: 0.3564 - rmse: 0.4604 - smape: 0.6616 - val_ia: 0.8282 - val_loss: 0.0820 - val_mae: 0.2285 - val_rmse: 0.2831 - val_smape: 0.5045

Epoch 22/128

287/287 - 4s - 14ms/step - ia: 0.7733 - loss: 0.2096 - mae: 0.3533 - rmse: 0.4564 - smape: 0.6562 - val_ia: 0.8312 - val_loss: 0.0797 - val_mae: 0.2248 - val_rmse: 0.2789 - val_smape: 0.4988

Epoch 23/128

287/287 - 5s - 18ms/step - ia: 0.7767 - loss: 0.2062 - mae: 0.3479 - rmse: 0.4528 - smape: 0.6508 - val_ia: 0.8341 - val_loss: 0.0774 - val_mae: 0.2200 - val_rmse: 0.2744 - val_smape: 0.4939

Epoch 24/128

287/287 - 4s - 14ms/step - ia: 0.7796 - loss: 0.1997 - mae: 0.3438 - rmse: 0.4455 - smape: 0.6479 - val_ia: 0.8345 - val_loss: 0.0766 - val_mae: 0.2197 - val_rmse: 0.2729 - val_smape: 0.5000

Epoch 25/128

287/287 - 4s - 13ms/step - ia: 0.7808 - loss: 0.1986 - mae: 0.3420 - rmse: 0.4442 - smape: 0.6435 - val_ia: 0.8309 - val_loss: 0.0788 - val_mae: 0.2230 - val_rmse: 0.2763 - val_smape: 0.5100

Epoch 26/128

287/287 - 5s - 19ms/step - ia: 0.7803 - loss: 0.2001 - mae: 0.3412 - rmse: 0.4460 - smape: 0.6436 - val_ia: 0.8394 - val_loss: 0.0730 - val_mae: 0.2119 - val_rmse: 0.2662 - val_smape: 0.4874

Epoch 27/128

287/287 - 5s - 18ms/step - ia: 0.7815 - loss: 0.1973 - mae: 0.3400 - rmse: 0.4429 - smape: 0.6433 - val_ia: 0.8415 - val_loss: 0.0711 - val_mae: 0.2104 - val_rmse: 0.2628 - val_smape: 0.4902

Epoch 28/128

287/287 - 4s - 14ms/step - ia: 0.7837 - loss: 0.1951 - mae: 0.3366 - rmse: 0.4404 - smape: 0.6391 - val_ia: 0.8380 - val_loss: 0.0734 - val_mae: 0.2149 - val_rmse: 0.2666 - val_smape: 0.5017

Epoch 29/128

287/287 - 5s - 18ms/step - ia: 0.7863 - loss: 0.1896 - mae: 0.3326 - rmse: 0.4341 - smape: 0.6352 - val_ia: 0.8383 - val_loss: 0.0728 - val_mae: 0.2127 - val_rmse: 0.2652 - val_smape: 0.4929

Epoch 30/128

287/287 - 4s - 14ms/step - ia: 0.7860 - loss: 0.1909 - mae: 0.3328 - rmse: 0.4358 - smape: 0.6349 - val_ia: 0.8380 - val_loss: 0.0726 - val_mae: 0.2136 - val_rmse: 0.2648 - val_smape: 0.5019

Epoch 31/128

287/287 - 5s - 17ms/step - ia: 0.7884 - loss: 0.1876 - mae: 0.3292 - rmse: 0.4317 - smape: 0.6305 - val_ia: 0.8394 - val_loss: 0.0715 - val_mae: 0.2113 - val_rmse: 0.2622 - val_smape: 0.4917

Epoch 32/128

287/287 - 5s - 18ms/step - ia: 0.7879 - loss: 0.1887 - mae: 0.3300 - rmse: 0.4329 - smape: 0.6309 - val_ia: 0.8474 - val_loss: 0.0657 - val_mae: 0.2009 - val_rmse: 0.2518 - val_smape: 0.4695

Epoch 33/128

287/287 - 4s - 14ms/step - ia: 0.7887 - loss: 0.1869 - mae: 0.3290 - rmse: 0.4310 - smape: 0.6291 - val_ia: 0.8455 - val_loss: 0.0668 - val_mae: 0.2025 - val_rmse: 0.2537 - val_smape: 0.4688

Epoch 34/128

287/287 - 4s - 14ms/step - ia: 0.7907 - loss: 0.1836 - mae: 0.3255 - rmse: 0.4271 - smape: 0.6300 - val_ia: 0.8482 - val_loss: 0.0647 - val_mae: 0.1988 - val_rmse: 0.2497 - val_smape: 0.4606

Epoch 35/128

287/287 - 5s - 18ms/step - ia: 0.7905 - loss: 0.1841 - mae: 0.3258 - rmse: 0.4278 - smape: 0.6279 - val_ia: 0.8469 - val_loss: 0.0651 - val_mae: 0.1995 - val_rmse: 0.2504 - val_smape: 0.4627

Epoch 36/128

287/287 - 4s - 14ms/step - ia: 0.7919 - loss: 0.1827 - mae: 0.3238 - rmse: 0.4261 - smape: 0.6239 - val_ia: 0.8478 - val_loss: 0.0645 - val_mae: 0.1993 - val_rmse: 0.2490 - val_smape: 0.4639

Epoch 37/128

287/287 - 5s - 16ms/step - ia: 0.7929 - loss: 0.1805 - mae: 0.3220 - rmse: 0.4235 - smape: 0.6186 - val_ia: 0.8507 - val_loss: 0.0625 - val_mae: 0.1953 - val_rmse: 0.2452 - val_smape: 0.4579

Epoch 38/128

287/287 - 4s - 13ms/step - ia: 0.7932 - loss: 0.1806 - mae: 0.3214 - rmse: 0.4236 - smape: 0.6218 - val_ia: 0.8515 - val_loss: 0.0616 - val_mae: 0.1941 - val_rmse: 0.2435 - val_smape: 0.4552

Epoch 39/128

287/287 - 4s - 14ms/step - ia: 0.7964 - loss: 0.1765 - mae: 0.3172 - rmse: 0.4187 - smape: 0.6125 - val_ia: 0.8562 - val_loss: 0.0585 - val_mae: 0.1872 - val_rmse: 0.2374 - val_smape: 0.4310

Epoch 40/128

287/287 - 5s - 18ms/step - ia: 0.7961 - loss: 0.1763 - mae: 0.3171 - rmse: 0.4185 - smape: 0.6145 - val_ia: 0.8521 - val_loss: 0.0610 - val_mae: 0.1933 - val_rmse: 0.2416 - val_smape: 0.4563

Epoch 41/128

287/287 - 5s - 18ms/step - ia: 0.7964 - loss: 0.1761 - mae: 0.3167 - rmse: 0.4182 - smape: 0.6124 - val_ia: 0.8552 - val_loss: 0.0589 - val_mae: 0.1877 - val_rmse: 0.2380 - val_smape: 0.4356

Epoch 42/128

287/287 - 4s - 14ms/step - ia: 0.7960 - loss: 0.1764 - mae: 0.3173 - rmse: 0.4183 - smape: 0.6186 - val_ia: 0.8566 - val_loss: 0.0577 - val_mae: 0.1864 - val_rmse: 0.2351 - val_smape: 0.4313

Epoch 43/128

287/287 - 4s - 14ms/step - ia: 0.7976 - loss: 0.1734 - mae: 0.3148 - rmse: 0.4152 - smape: 0.6131 - val_ia: 0.8534 - val_loss: 0.0598 - val_mae: 0.1899 - val_rmse: 0.2392 - val_smape: 0.4425

Epoch 44/128

287/287 - 5s - 18ms/step - ia: 0.7986 - loss: 0.1732 - mae: 0.3135 - rmse: 0.4149 - smape: 0.6075 - val_ia: 0.8622 - val_loss: 0.0541 - val_mae: 0.1799 - val_rmse: 0.2278 - val_smape: 0.4216

Epoch 45/128

287/287 - 5s - 17ms/step - ia: 0.7986 - loss: 0.1726 - mae: 0.3133 - rmse: 0.4143 - smape: 0.6077 - val_ia: 0.8588 - val_loss: 0.0561 - val_mae: 0.1842 - val_rmse: 0.2317 - val_smape: 0.4384

Epoch 46/128

287/287 - 4s - 14ms/step - ia: 0.8015 - loss: 0.1685 - mae: 0.3096 - rmse: 0.4089 - smape: 0.6034 - val_ia: 0.8544 - val_loss: 0.0590 - val_mae: 0.1884 - val_rmse: 0.2374 - val_smape: 0.4423

Epoch 47/128

287/287 - 4s - 14ms/step - ia: 0.8008 - loss: 0.1694 - mae: 0.3102 - rmse: 0.4102 - smape: 0.6032 - val_ia: 0.8605 - val_loss: 0.0550 - val_mae: 0.1816 - val_rmse: 0.2292 - val_smape: 0.4312

Epoch 48/128

287/287 - 4s - 14ms/step - ia: 0.8009 - loss: 0.1701 - mae: 0.3097 - rmse: 0.4110 - smape: 0.6083 - val_ia: 0.8632 - val_loss: 0.0532 - val_mae: 0.1784 - val_rmse: 0.2251 - val_smape: 0.4229

Epoch 49/128

287/287 - 4s - 14ms/step - ia: 0.8012 - loss: 0.1691 - mae: 0.3097 - rmse: 0.4098 - smape: 0.6058 - val_ia: 0.8588 - val_loss: 0.0562 - val_mae: 0.1829 - val_rmse: 0.2313 - val_smape: 0.4316

Epoch 50/128

287/287 - 4s - 14ms/step - ia: 0.8020 - loss: 0.1672 - mae: 0.3082 - rmse: 0.4077 - smape: 0.6015 - val_ia: 0.8603 - val_loss: 0.0551 - val_mae: 0.1810 - val_rmse: 0.2291 - val_smape: 0.4287

Epoch 51/128

287/287 - 5s - 19ms/step - ia: 0.8013 - loss: 0.1678 - mae: 0.3092 - rmse: 0.4085 - smape: 0.6057 - val_ia: 0.8571 - val_loss: 0.0572 - val_mae: 0.1849 - val_rmse: 0.2331 - val_smape: 0.4393

Epoch 52/128

287/287 - 5s - 17ms/step - ia: 0.8045 - loss: 0.1639 - mae: 0.3045 - rmse: 0.4033 - smape: 0.5982 - val_ia: 0.8616 - val_loss: 0.0540 - val_mae: 0.1794 - val_rmse: 0.2266 - val_smape: 0.4269

Epoch 53/128

287/287 - 4s - 14ms/step - ia: 0.8029 - loss: 0.1664 - mae: 0.3072 - rmse: 0.4065 - smape: 0.6014 - val_ia: 0.8611 - val_loss: 0.0546 - val_mae: 0.1794 - val_rmse: 0.2277 - val_smape: 0.4240

Epoch 54/128

287/287 - 4s - 14ms/step - ia: 0.8048 - loss: 0.1649 - mae: 0.3038 - rmse: 0.4045 - smape: 0.5989 - val_ia: 0.8570 - val_loss: 0.0569 - val_mae: 0.1848 - val_rmse: 0.2319 - val_smape: 0.4407

Epoch 55/128

287/287 - 4s - 14ms/step - ia: 0.8026 - loss: 0.1668 - mae: 0.3071 - rmse: 0.4069 - smape: 0.6000 - val_ia: 0.8573 - val_loss: 0.0567 - val_mae: 0.1838 - val_rmse: 0.2314 - val_smape: 0.4333

Epoch 56/128

287/287 - 5s - 18ms/step - ia: 0.8051 - loss: 0.1633 - mae: 0.3032 - rmse: 0.4026 - smape: 0.5971 - val_ia: 0.8670 - val_loss: 0.0511 - val_mae: 0.1723 - val_rmse: 0.2205 - val_smape: 0.4116

Epoch 57/128

287/287 - 4s - 14ms/step - ia: 0.8056 - loss: 0.1628 - mae: 0.3029 - rmse: 0.4020 - smape: 0.5954 - val_ia: 0.8676 - val_loss: 0.0510 - val_mae: 0.1708 - val_rmse: 0.2204 - val_smape: 0.4011

Epoch 58/128

287/287 - 4s - 14ms/step - ia: 0.8065 - loss: 0.1607 - mae: 0.3011 - rmse: 0.3996 - smape: 0.5903 - val_ia: 0.8649 - val_loss: 0.0520 - val_mae: 0.1748 - val_rmse: 0.2219 - val_smape: 0.4166

Epoch 59/128

287/287 - 4s - 14ms/step - ia: 0.8079 - loss: 0.1596 - mae: 0.2994 - rmse: 0.3982 - smape: 0.5881 - val_ia: 0.8668 - val_loss: 0.0513 - val_mae: 0.1718 - val_rmse: 0.2211 - val_smape: 0.4074

Epoch 60/128

287/287 - 4s - 14ms/step - ia: 0.8084 - loss: 0.1586 - mae: 0.2987 - rmse: 0.3967 - smape: 0.5895 - val_ia: 0.8652 - val_loss: 0.0522 - val_mae: 0.1738 - val_rmse: 0.2224 - val_smape: 0.4148

Epoch 61/128

287/287 - 5s - 19ms/step - ia: 0.8079 - loss: 0.1594 - mae: 0.2990 - rmse: 0.3979 - smape: 0.5870 - val_ia: 0.8665 - val_loss: 0.0513 - val_mae: 0.1721 - val_rmse: 0.2203 - val_smape: 0.4088

Epoch 62/128

287/287 - 4s - 14ms/step - ia: 0.8079 - loss: 0.1595 - mae: 0.2991 - rmse: 0.3977 - smape: 0.5910 - val_ia: 0.8616 - val_loss: 0.0543 - val_mae: 0.1779 - val_rmse: 0.2261 - val_smape: 0.4226

Epoch 63/128

287/287 - 5s - 18ms/step - ia: 0.8093 - loss: 0.1571 - mae: 0.2972 - rmse: 0.3950 - smape: 0.5879 - val_ia: 0.8690 - val_loss: 0.0498 - val_mae: 0.1688 - val_rmse: 0.2174 - val_smape: 0.3979

Epoch 64/128

287/287 - 6s - 21ms/step - ia: 0.8090 - loss: 0.1573 - mae: 0.2975 - rmse: 0.3952 - smape: 0.5873 - val_ia: 0.8619 - val_loss: 0.0540 - val_mae: 0.1778 - val_rmse: 0.2252 - val_smape: 0.4218

Epoch 65/128

287/287 - 5s - 16ms/step - ia: 0.8101 - loss: 0.1558 - mae: 0.2961 - rmse: 0.3933 - smape: 0.5858 - val_ia: 0.8647 - val_loss: 0.0523 - val_mae: 0.1740 - val_rmse: 0.2217 - val_smape: 0.4084

Epoch 66/128

287/287 - 4s - 13ms/step - ia: 0.8105 - loss: 0.1562 - mae: 0.2952 - rmse: 0.3937 - smape: 0.5822 - val_ia: 0.8667 - val_loss: 0.0512 - val_mae: 0.1711 - val_rmse: 0.2202 - val_smape: 0.4026

Epoch 67/128

287/287 - 5s - 16ms/step - ia: 0.8100 - loss: 0.1573 - mae: 0.2957 - rmse: 0.3949 - smape: 0.5841 - val_ia: 0.8729 - val_loss: 0.0470 - val_mae: 0.1647 - val_rmse: 0.2106 - val_smape: 0.3916

Epoch 68/128

287/287 - 3s - 11ms/step - ia: 0.8107 - loss: 0.1554 - mae: 0.2956 - rmse: 0.3926 - smape: 0.5844 - val_ia: 0.8686 - val_loss: 0.0498 - val_mae: 0.1693 - val_rmse: 0.2167 - val_smape: 0.4004

Epoch 69/128

287/287 - 3s - 12ms/step - ia: 0.8112 - loss: 0.1549 - mae: 0.2944 - rmse: 0.3920 - smape: 0.5796 - val_ia: 0.8667 - val_loss: 0.0511 - val_mae: 0.1718 - val_rmse: 0.2186 - val_smape: 0.4083

Epoch 70/128

287/287 - 4s - 15ms/step - ia: 0.8111 - loss: 0.1559 - mae: 0.2941 - rmse: 0.3936 - smape: 0.5788 - val_ia: 0.8692 - val_loss: 0.0495 - val_mae: 0.1684 - val_rmse: 0.2158 - val_smape: 0.3993

Epoch 71/128

287/287 - 5s - 17ms/step - ia: 0.8112 - loss: 0.1541 - mae: 0.2944 - rmse: 0.3912 - smape: 0.5824 - val_ia: 0.8682 - val_loss: 0.0502 - val_mae: 0.1689 - val_rmse: 0.2174 - val_smape: 0.3939

Epoch 72/128

287/287 - 4s - 14ms/step - ia: 0.8141 - loss: 0.1506 - mae: 0.2903 - rmse: 0.3866 - smape: 0.5746 - val_ia: 0.8679 - val_loss: 0.0501 - val_mae: 0.1699 - val_rmse: 0.2169 - val_smape: 0.4018

Epoch 73/128

287/287 - 5s - 18ms/step - ia: 0.8127 - loss: 0.1529 - mae: 0.2921 - rmse: 0.3894 - smape: 0.5785 - val_ia: 0.8714 - val_loss: 0.0478 - val_mae: 0.1654 - val_rmse: 0.2128 - val_smape: 0.3902

Epoch 74/128

287/287 - 5s - 18ms/step - ia: 0.8132 - loss: 0.1532 - mae: 0.2915 - rmse: 0.3898 - smape: 0.5751 - val_ia: 0.8696 - val_loss: 0.0489 - val_mae: 0.1671 - val_rmse: 0.2151 - val_smape: 0.3903

Epoch 75/128

287/287 - 5s - 17ms/step - ia: 0.8137 - loss: 0.1523 - mae: 0.2907 - rmse: 0.3888 - smape: 0.5744 - val_ia: 0.8653 - val_loss: 0.0516 - val_mae: 0.1720 - val_rmse: 0.2202 - val_smape: 0.4014

Epoch 76/128

287/287 - 5s - 19ms/step - ia: 0.8135 - loss: 0.1509 - mae: 0.2907 - rmse: 0.3870 - smape: 0.5763 - val_ia: 0.8680 - val_loss: 0.0502 - val_mae: 0.1692 - val_rmse: 0.2168 - val_smape: 0.3951

Epoch 77/128

287/287 - 4s - 14ms/step - ia: 0.8146 - loss: 0.1513 - mae: 0.2893 - rmse: 0.3876 - smape: 0.5703 - val_ia: 0.8727 - val_loss: 0.0472 - val_mae: 0.1638 - val_rmse: 0.2103 - val_smape: 0.3849

Epoch 78/128

287/287 - 4s - 14ms/step - ia: 0.8142 - loss: 0.1515 - mae: 0.2896 - rmse: 0.3878 - smape: 0.5736 - val_ia: 0.8653 - val_loss: 0.0517 - val_mae: 0.1721 - val_rmse: 0.2201 - val_smape: 0.3996

Epoch 79/128

287/287 - 4s - 14ms/step - ia: 0.8142 - loss: 0.1516 - mae: 0.2899 - rmse: 0.3878 - smape: 0.5709 - val_ia: 0.8700 - val_loss: 0.0488 - val_mae: 0.1668 - val_rmse: 0.2138 - val_smape: 0.3902

Epoch 80/128

287/287 - 4s - 14ms/step - ia: 0.8150 - loss: 0.1508 - mae: 0.2887 - rmse: 0.3868 - smape: 0.5705 - val_ia: 0.8728 - val_loss: 0.0469 - val_mae: 0.1637 - val_rmse: 0.2098 - val_smape: 0.3852

Epoch 81/128

287/287 - 5s - 18ms/step - ia: 0.8147 - loss: 0.1506 - mae: 0.2888 - rmse: 0.3866 - smape: 0.5709 - val_ia: 0.8664 - val_loss: 0.0509 - val_mae: 0.1708 - val_rmse: 0.2183 - val_smape: 0.3982

Epoch 82/128

287/287 - 5s - 18ms/step - ia: 0.8160 - loss: 0.1486 - mae: 0.2870 - rmse: 0.3839 - smape: 0.5705 - val_ia: 0.8692 - val_loss: 0.0493 - val_mae: 0.1676 - val_rmse: 0.2146 - val_smape: 0.3903

Epoch 83/128

287/287 - 4s - 14ms/step - ia: 0.8158 - loss: 0.1499 - mae: 0.2872 - rmse: 0.3857 - smape: 0.5654 - val_ia: 0.8733 - val_loss: 0.0465 - val_mae: 0.1628 - val_rmse: 0.2088 - val_smape: 0.3810

Epoch 84/128

287/287 - 5s - 18ms/step - ia: 0.8148 - loss: 0.1503 - mae: 0.2887 - rmse: 0.3863 - smape: 0.5746 - val_ia: 0.8733 - val_loss: 0.0466 - val_mae: 0.1629 - val_rmse: 0.2092 - val_smape: 0.3817

Epoch 85/128

287/287 - 5s - 19ms/step - ia: 0.8167 - loss: 0.1484 - mae: 0.2863 - rmse: 0.3837 - smape: 0.5666 - val_ia: 0.8724 - val_loss: 0.0470 - val_mae: 0.1639 - val_rmse: 0.2098 - val_smape: 0.3815

Epoch 86/128

287/287 - 4s - 14ms/step - ia: 0.8179 - loss: 0.1462 - mae: 0.2843 - rmse: 0.3808 - smape: 0.5616 - val_ia: 0.8711 - val_loss: 0.0478 - val_mae: 0.1652 - val_rmse: 0.2114 - val_smape: 0.3842

Epoch 87/128

287/287 - 4s - 14ms/step - ia: 0.8168 - loss: 0.1477 - mae: 0.2861 - rmse: 0.3831 - smape: 0.5656 - val_ia: 0.8711 - val_loss: 0.0481 - val_mae: 0.1653 - val_rmse: 0.2116 - val_smape: 0.3842

Epoch 88/128

287/287 - 4s - 14ms/step - ia: 0.8162 - loss: 0.1496 - mae: 0.2868 - rmse: 0.3851 - smape: 0.5668 - val_ia: 0.8718 - val_loss: 0.0471 - val_mae: 0.1639 - val_rmse: 0.2106 - val_smape: 0.3785

Epoch 89/128

287/287 - 4s - 14ms/step - ia: 0.8178 - loss: 0.1472 - mae: 0.2846 - rmse: 0.3819 - smape: 0.5634 - val_ia: 0.8743 - val_loss: 0.0457 - val_mae: 0.1613 - val_rmse: 0.2073 - val_smape: 0.3738

Epoch 90/128

287/287 - 5s - 18ms/step - ia: 0.8180 - loss: 0.1472 - mae: 0.2844 - rmse: 0.3822 - smape: 0.5611 - val_ia: 0.8713 - val_loss: 0.0475 - val_mae: 0.1647 - val_rmse: 0.2112 - val_smape: 0.3800

Epoch 91/128

287/287 - 4s - 14ms/step - ia: 0.8162 - loss: 0.1489 - mae: 0.2865 - rmse: 0.3846 - smape: 0.5656 - val_ia: 0.8724 - val_loss: 0.0471 - val_mae: 0.1637 - val_rmse: 0.2100 - val_smape: 0.3783

Epoch 92/128

287/287 - 5s - 18ms/step - ia: 0.8168 - loss: 0.1494 - mae: 0.2858 - rmse: 0.3853 - smape: 0.5631 - val_ia: 0.8754 - val_loss: 0.0450 - val_mae: 0.1601 - val_rmse: 0.2054 - val_smape: 0.3703

Epoch 93/128

287/287 - 5s - 18ms/step - ia: 0.8184 - loss: 0.1468 - mae: 0.2833 - rmse: 0.3817 - smape: 0.5599 - val_ia: 0.8731 - val_loss: 0.0465 - val_mae: 0.1629 - val_rmse: 0.2085 - val_smape: 0.3771

Epoch 94/128

287/287 - 5s - 17ms/step - ia: 0.8192 - loss: 0.1450 - mae: 0.2825 - rmse: 0.3795 - smape: 0.5597 - val_ia: 0.8756 - val_loss: 0.0451 - val_mae: 0.1598 - val_rmse: 0.2053 - val_smape: 0.3684

Epoch 95/128

287/287 - 5s - 17ms/step - ia: 0.8198 - loss: 0.1453 - mae: 0.2816 - rmse: 0.3798 - smape: 0.5551 - val_ia: 0.8704 - val_loss: 0.0484 - val_mae: 0.1654 - val_rmse: 0.2124 - val_smape: 0.3768

Epoch 96/128

287/287 - 4s - 14ms/step - ia: 0.8196 - loss: 0.1455 - mae: 0.2818 - rmse: 0.3799 - smape: 0.5530 - val_ia: 0.8767 - val_loss: 0.0442 - val_mae: 0.1588 - val_rmse: 0.2034 - val_smape: 0.3679

Epoch 97/128

287/287 - 6s - 20ms/step - ia: 0.8179 - loss: 0.1471 - mae: 0.2838 - rmse: 0.3822 - smape: 0.5616 - val_ia: 0.8730 - val_loss: 0.0466 - val_mae: 0.1628 - val_rmse: 0.2084 - val_smape: 0.3749

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 55s - 24ms/step - ia: 0.9173 - loss: 0.0406 - mae: 0.1259 - rmse: 0.1657 - smape: 0.3194 - val_ia: 0.7730 - val_loss: 0.0060 - val_mae: 0.0566 - val_rmse: 0.0691 - val_smape: 0.1497

Epoch 2/128

2293/2293 - 48s - 21ms/step - ia: 0.9698 - loss: 0.0046 - mae: 0.0470 - rmse: 0.0621 - smape: 0.1557 - val_ia: 0.8188 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0527 - val_smape: 0.1371

Epoch 3/128

2293/2293 - 48s - 21ms/step - ia: 0.9730 - loss: 0.0039 - mae: 0.0423 - rmse: 0.0563 - smape: 0.1422 - val_ia: 0.8392 - val_loss: 0.0027 - val_mae: 0.0373 - val_rmse: 0.0478 - val_smape: 0.1269

Epoch 4/128

2293/2293 - 47s - 20ms/step - ia: 0.9741 - loss: 0.0037 - mae: 0.0405 - rmse: 0.0546 - smape: 0.1379 - val_ia: 0.7908 - val_loss: 0.0045 - val_mae: 0.0510 - val_rmse: 0.0614 - val_smape: 0.1288

Epoch 5/128

2293/2293 - 48s - 21ms/step - ia: 0.9749 - loss: 0.0035 - mae: 0.0392 - rmse: 0.0531 - smape: 0.1351 - val_ia: 0.8556 - val_loss: 0.0025 - val_mae: 0.0341 - val_rmse: 0.0447 - val_smape: 0.1133

Epoch 6/128

2293/2293 - 47s - 20ms/step - ia: 0.9752 - loss: 0.0034 - mae: 0.0388 - rmse: 0.0523 - smape: 0.1327 - val_ia: 0.8420 - val_loss: 0.0026 - val_mae: 0.0369 - val_rmse: 0.0472 - val_smape: 0.1166

Epoch 7/128

2293/2293 - 47s - 21ms/step - ia: 0.9755 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0518 - smape: 0.1318 - val_ia: 0.8149 - val_loss: 0.0036 - val_mae: 0.0452 - val_rmse: 0.0550 - val_smape: 0.1459

Epoch 8/128

2293/2293 - 48s - 21ms/step - ia: 0.9760 - loss: 0.0032 - mae: 0.0374 - rmse: 0.0507 - smape: 0.1295 - val_ia: 0.8213 - val_loss: 0.0031 - val_mae: 0.0415 - val_rmse: 0.0514 - val_smape: 0.1466

Epoch 9/128

2293/2293 - 47s - 20ms/step - ia: 0.9764 - loss: 0.0031 - mae: 0.0369 - rmse: 0.0501 - smape: 0.1291 - val_ia: 0.8138 - val_loss: 0.0034 - val_mae: 0.0437 - val_rmse: 0.0540 - val_smape: 0.1197

Epoch 10/128

2293/2293 - 81s - 36ms/step - ia: 0.9764 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0498 - smape: 0.1288 - val_ia: 0.8581 - val_loss: 0.0023 - val_mae: 0.0329 - val_rmse: 0.0430 - val_smape: 0.1096

Epoch 11/128

2293/2293 - 54s - 23ms/step - ia: 0.9766 - loss: 0.0031 - mae: 0.0364 - rmse: 0.0494 - smape: 0.1284 - val_ia: 0.8383 - val_loss: 0.0029 - val_mae: 0.0396 - val_rmse: 0.0493 - val_smape: 0.1292

Epoch 12/128

2293/2293 - 54s - 23ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0362 - rmse: 0.0490 - smape: 0.1278 - val_ia: 0.8305 - val_loss: 0.0032 - val_mae: 0.0410 - val_rmse: 0.0517 - val_smape: 0.1369

Epoch 13/128

2293/2293 - 53s - 23ms/step - ia: 0.9771 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0487 - smape: 0.1265 - val_ia: 0.8380 - val_loss: 0.0027 - val_mae: 0.0376 - val_rmse: 0.0478 - val_smape: 0.1166

Epoch 14/128

2293/2293 - 53s - 23ms/step - ia: 0.9774 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0479 - smape: 0.1262 - val_ia: 0.8104 - val_loss: 0.0035 - val_mae: 0.0444 - val_rmse: 0.0541 - val_smape: 0.1384

Epoch 15/128

2293/2293 - 52s - 23ms/step - ia: 0.9773 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0480 - smape: 0.1256 - val_ia: 0.8166 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0546 - val_smape: 0.1238

Epoch 16/128

2293/2293 - 53s - 23ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0352 - rmse: 0.0478 - smape: 0.1245 - val_ia: 0.8435 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0471 - val_smape: 0.1224

Epoch 17/128

2293/2293 - 53s - 23ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0476 - smape: 0.1249 - val_ia: 0.8391 - val_loss: 0.0031 - val_mae: 0.0391 - val_rmse: 0.0500 - val_smape: 0.1273

Epoch 18/128

2293/2293 - 54s - 23ms/step - ia: 0.9777 - loss: 0.0028 - mae: 0.0347 - rmse: 0.0469 - smape: 0.1247 - val_ia: 0.8244 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0499 - val_smape: 0.1269

Epoch 19/128

2293/2293 - 53s - 23ms/step - ia: 0.9779 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0468 - smape: 0.1236 - val_ia: 0.8389 - val_loss: 0.0028 - val_mae: 0.0369 - val_rmse: 0.0473 - val_smape: 0.1161

Epoch 20/128

2293/2293 - 52s - 22ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0466 - smape: 0.1230 - val_ia: 0.8265 - val_loss: 0.0032 - val_mae: 0.0419 - val_rmse: 0.0522 - val_smape: 0.1195

Epoch 21/128

2293/2293 - 52s - 23ms/step - ia: 0.9781 - loss: 0.0027 - mae: 0.0341 - rmse: 0.0464 - smape: 0.1226 - val_ia: 0.8148 - val_loss: 0.0033 - val_mae: 0.0424 - val_rmse: 0.0530 - val_smape: 0.1415

Epoch 22/128

2293/2293 - 51s - 22ms/step - ia: 0.9783 - loss: 0.0027 - mae: 0.0338 - rmse: 0.0459 - smape: 0.1221 - val_ia: 0.8476 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0454 - val_smape: 0.1159

Epoch 23/128

2293/2293 - 53s - 23ms/step - ia: 0.9782 - loss: 0.0027 - mae: 0.0339 - rmse: 0.0460 - smape: 0.1225 - val_ia: 0.8136 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0532 - val_smape: 0.1230

Epoch 24/128

2293/2293 - 53s - 23ms/step - ia: 0.9786 - loss: 0.0027 - mae: 0.0335 - rmse: 0.0454 - smape: 0.1221 - val_ia: 0.8037 - val_loss: 0.0034 - val_mae: 0.0443 - val_rmse: 0.0544 - val_smape: 0.1250

Epoch 25/128

2293/2293 - 81s - 35ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0336 - rmse: 0.0456 - smape: 0.1220 - val_ia: 0.8468 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0469 - val_smape: 0.1200

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:44 1s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step

 17%|█▋        | 2/12 [32:13<2:52:10, 1033.09s/trial, best loss: 0.0019945538727369925]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 57s - 13ms/step - ia: 0.2395 - loss: 0.9113 - mae: 0.7912 - rmse: 0.9359 - smape: 1.6962 - val_ia: 0.1462 - val_loss: 0.7667 - val_mae: 0.7317 - val_rmse: 0.7494 - val_smape: 1.5930

Epoch 2/128

4586/4586 - 39s - 8ms/step - ia: 0.2731 - loss: 0.8425 - mae: 0.7608 - rmse: 0.8991 - smape: 1.5980 - val_ia: 0.1525 - val_loss: 0.7127 - val_mae: 0.7042 - val_rmse: 0.7218 - val_smape: 1.4894

Epoch 3/128

4586/4586 - 37s - 8ms/step - ia: 0.3283 - loss: 0.7560 - mae: 0.7172 - rmse: 0.8504 - smape: 1.4733 - val_ia: 0.1604 - val_loss: 0.6400 - val_mae: 0.6624 - val_rmse: 0.6799 - val_smape: 1.3678

Epoch 4/128

4586/4586 - 38s - 8ms/step - ia: 0.3997 - loss: 0.6548 - mae: 0.6629 - rmse: 0.7898 - smape: 1.3461 - val_ia: 0.1695 - val_loss: 0.5696 - val_mae: 0.6174 - val_rmse: 0.6349 - val_smape: 1.2648

Epoch 5/128

4586/4586 - 41s - 9ms/step - ia: 0.4632 - loss: 0.5812 - mae: 0.6191 - rmse: 0.7419 - smape: 1.2510 - val_ia: 0.1703 - val_loss: 0.5325 - val_mae: 0.5953 - val_rmse: 0.6129 - val_smape: 1.2172

Epoch 6/128

4586/4586 - 40s - 9ms/step - ia: 0.5063 - loss: 0.5266 - mae: 0.5863 - rmse: 0.7049 - smape: 1.1835 - val_ia: 0.1707 - val_loss: 0.5063 - val_mae: 0.5792 - val_rmse: 0.5966 - val_smape: 1.1848

Epoch 7/128

4586/4586 - 38s - 8ms/step - ia: 0.5355 - loss: 0.4898 - mae: 0.5635 - rmse: 0.6801 - smape: 1.1339 - val_ia: 0.1715 - val_loss: 0.4854 - val_mae: 0.5658 - val_rmse: 0.5831 - val_smape: 1.1574

Epoch 8/128

4586/4586 - 40s - 9ms/step - ia: 0.5567 - loss: 0.4636 - mae: 0.5463 - rmse: 0.6612 - smape: 1.0960 - val_ia: 0.1729 - val_loss: 0.4673 - val_mae: 0.5537 - val_rmse: 0.5710 - val_smape: 1.1324

Epoch 9/128

4586/4586 - 36s - 8ms/step - ia: 0.5724 - loss: 0.4481 - mae: 0.5356 - rmse: 0.6490 - smape: 1.0664 - val_ia: 0.1743 - val_loss: 0.4527 - val_mae: 0.5435 - val_rmse: 0.5609 - val_smape: 1.1113

Epoch 10/128

4586/4586 - 42s - 9ms/step - ia: 0.5825 - loss: 0.4303 - mae: 0.5246 - rmse: 0.6364 - smape: 1.0442 - val_ia: 0.1772 - val_loss: 0.4383 - val_mae: 0.5324 - val_rmse: 0.5500 - val_smape: 1.0890

Epoch 11/128

4586/4586 - 37s - 8ms/step - ia: 0.5962 - loss: 0.4181 - mae: 0.5140 - rmse: 0.6259 - smape: 1.0186 - val_ia: 0.1805 - val_loss: 0.4256 - val_mae: 0.5211 - val_rmse: 0.5389 - val_smape: 1.0673

Epoch 12/128

4586/4586 - 38s - 8ms/step - ia: 0.6077 - loss: 0.3995 - mae: 0.5021 - rmse: 0.6121 - smape: 0.9927 - val_ia: 0.1865 - val_loss: 0.4140 - val_mae: 0.5101 - val_rmse: 0.5282 - val_smape: 1.0466

Epoch 13/128

4586/4586 - 38s - 8ms/step - ia: 0.6153 - loss: 0.3888 - mae: 0.4947 - rmse: 0.6034 - smape: 0.9742 - val_ia: 0.1909 - val_loss: 0.4044 - val_mae: 0.5012 - val_rmse: 0.5195 - val_smape: 1.0295

Epoch 14/128

4586/4586 - 45s - 10ms/step - ia: 0.6270 - loss: 0.3734 - mae: 0.4835 - rmse: 0.5914 - smape: 0.9490 - val_ia: 0.1919 - val_loss: 0.3965 - val_mae: 0.4962 - val_rmse: 0.5147 - val_smape: 1.0178

Epoch 15/128

4586/4586 - 38s - 8ms/step - ia: 0.6366 - loss: 0.3633 - mae: 0.4762 - rmse: 0.5830 - smape: 0.9325 - val_ia: 0.1851 - val_loss: 0.3911 - val_mae: 0.4956 - val_rmse: 0.5140 - val_smape: 1.0116

Epoch 16/128

4586/4586 - 38s - 8ms/step - ia: 0.6430 - loss: 0.3540 - mae: 0.4687 - rmse: 0.5752 - smape: 0.9144 - val_ia: 0.1814 - val_loss: 0.3866 - val_mae: 0.4963 - val_rmse: 0.5144 - val_smape: 1.0079

Epoch 17/128

4586/4586 - 37s - 8ms/step - ia: 0.6503 - loss: 0.3435 - mae: 0.4608 - rmse: 0.5660 - smape: 0.8984 - val_ia: 0.1801 - val_loss: 0.3831 - val_mae: 0.4972 - val_rmse: 0.5153 - val_smape: 1.0049

Epoch 18/128

4586/4586 - 35s - 8ms/step - ia: 0.6569 - loss: 0.3351 - mae: 0.4544 - rmse: 0.5590 - smape: 0.8870 - val_ia: 0.1794 - val_loss: 0.3809 - val_mae: 0.4989 - val_rmse: 0.5171 - val_smape: 1.0023

Epoch 19/128

4586/4586 - 41s - 9ms/step - ia: 0.6636 - loss: 0.3234 - mae: 0.4474 - rmse: 0.5502 - smape: 0.8704 - val_ia: 0.1794 - val_loss: 0.3776 - val_mae: 0.4988 - val_rmse: 0.5170 - val_smape: 0.9988

Epoch 20/128

4586/4586 - 38s - 8ms/step - ia: 0.6683 - loss: 0.3176 - mae: 0.4425 - rmse: 0.5441 - smape: 0.8584 - val_ia: 0.1799 - val_loss: 0.3741 - val_mae: 0.4977 - val_rmse: 0.5159 - val_smape: 0.9954

Epoch 21/128

4586/4586 - 38s - 8ms/step - ia: 0.6720 - loss: 0.3111 - mae: 0.4374 - rmse: 0.5393 - smape: 0.8500 - val_ia: 0.1804 - val_loss: 0.3698 - val_mae: 0.4956 - val_rmse: 0.5139 - val_smape: 0.9911

Epoch 22/128

4586/4586 - 39s - 9ms/step - ia: 0.6787 - loss: 0.3033 - mae: 0.4320 - rmse: 0.5320 - smape: 0.8398 - val_ia: 0.1811 - val_loss: 0.3654 - val_mae: 0.4931 - val_rmse: 0.5114 - val_smape: 0.9871

Epoch 23/128

4586/4586 - 38s - 8ms/step - ia: 0.6820 - loss: 0.2994 - mae: 0.4288 - rmse: 0.5279 - smape: 0.8297 - val_ia: 0.1823 - val_loss: 0.3610 - val_mae: 0.4903 - val_rmse: 0.5087 - val_smape: 0.9823

Epoch 24/128

4586/4586 - 41s - 9ms/step - ia: 0.6861 - loss: 0.2894 - mae: 0.4222 - rmse: 0.5199 - smape: 0.8191 - val_ia: 0.1840 - val_loss: 0.3551 - val_mae: 0.4861 - val_rmse: 0.5046 - val_smape: 0.9767

Epoch 25/128

4586/4586 - 40s - 9ms/step - ia: 0.6917 - loss: 0.2859 - mae: 0.4192 - rmse: 0.5162 - smape: 0.8110 - val_ia: 0.1858 - val_loss: 0.3486 - val_mae: 0.4810 - val_rmse: 0.4995 - val_smape: 0.9705

Epoch 26/128

4586/4586 - 38s - 8ms/step - ia: 0.6939 - loss: 0.2807 - mae: 0.4154 - rmse: 0.5118 - smape: 0.8049 - val_ia: 0.1873 - val_loss: 0.3425 - val_mae: 0.4762 - val_rmse: 0.4948 - val_smape: 0.9638

Epoch 27/128

4586/4586 - 38s - 8ms/step - ia: 0.6981 - loss: 0.2753 - mae: 0.4101 - rmse: 0.5054 - smape: 0.7935 - val_ia: 0.1894 - val_loss: 0.3355 - val_mae: 0.4705 - val_rmse: 0.4892 - val_smape: 0.9565

Epoch 28/128

4586/4586 - 37s - 8ms/step - ia: 0.7007 - loss: 0.2712 - mae: 0.4078 - rmse: 0.5023 - smape: 0.7905 - val_ia: 0.1916 - val_loss: 0.3289 - val_mae: 0.4652 - val_rmse: 0.4839 - val_smape: 0.9486

Epoch 29/128

4586/4586 - 36s - 8ms/step - ia: 0.7045 - loss: 0.2658 - mae: 0.4031 - rmse: 0.4975 - smape: 0.7836 - val_ia: 0.1939 - val_loss: 0.3218 - val_mae: 0.4594 - val_rmse: 0.4782 - val_smape: 0.9401

Epoch 30/128

4586/4586 - 45s - 10ms/step - ia: 0.7072 - loss: 0.2627 - mae: 0.4010 - rmse: 0.4942 - smape: 0.7779 - val_ia: 0.1959 - val_loss: 0.3156 - val_mae: 0.4542 - val_rmse: 0.4731 - val_smape: 0.9323

Epoch 31/128

4586/4586 - 39s - 9ms/step - ia: 0.7117 - loss: 0.2570 - mae: 0.3959 - rmse: 0.4887 - smape: 0.7685 - val_ia: 0.1984 - val_loss: 0.3080 - val_mae: 0.4477 - val_rmse: 0.4665 - val_smape: 0.9237

Epoch 32/128

4586/4586 - 39s - 8ms/step - ia: 0.7139 - loss: 0.2523 - mae: 0.3918 - rmse: 0.4839 - smape: 0.7618 - val_ia: 0.2006 - val_loss: 0.3015 - val_mae: 0.4423 - val_rmse: 0.4611 - val_smape: 0.9157

Epoch 33/128

4586/4586 - 38s - 8ms/step - ia: 0.7177 - loss: 0.2444 - mae: 0.3861 - rmse: 0.4766 - smape: 0.7567 - val_ia: 0.2027 - val_loss: 0.2947 - val_mae: 0.4366 - val_rmse: 0.4555 - val_smape: 0.9071

Epoch 34/128

4586/4586 - 38s - 8ms/step - ia: 0.7203 - loss: 0.2428 - mae: 0.3833 - rmse: 0.4743 - smape: 0.7506 - val_ia: 0.2047 - val_loss: 0.2878 - val_mae: 0.4305 - val_rmse: 0.4493 - val_smape: 0.8984

Epoch 35/128

4586/4586 - 38s - 8ms/step - ia: 0.7244 - loss: 0.2383 - mae: 0.3795 - rmse: 0.4700 - smape: 0.7452 - val_ia: 0.2069 - val_loss: 0.2798 - val_mae: 0.4232 - val_rmse: 0.4420 - val_smape: 0.8883

Epoch 36/128

4586/4586 - 37s - 8ms/step - ia: 0.7266 - loss: 0.2348 - mae: 0.3769 - rmse: 0.4668 - smape: 0.7409 - val_ia: 0.2090 - val_loss: 0.2727 - val_mae: 0.4169 - val_rmse: 0.4356 - val_smape: 0.8791

Epoch 37/128

4586/4586 - 36s - 8ms/step - ia: 0.7280 - loss: 0.2321 - mae: 0.3740 - rmse: 0.4632 - smape: 0.7359 - val_ia: 0.2109 - val_loss: 0.2665 - val_mae: 0.4113 - val_rmse: 0.4300 - val_smape: 0.8711

Epoch 38/128

4586/4586 - 40s - 9ms/step - ia: 0.7328 - loss: 0.2259 - mae: 0.3690 - rmse: 0.4572 - smape: 0.7295 - val_ia: 0.2132 - val_loss: 0.2597 - val_mae: 0.4051 - val_rmse: 0.4238 - val_smape: 0.8619

Epoch 39/128

4586/4586 - 39s - 8ms/step - ia: 0.7344 - loss: 0.2242 - mae: 0.3669 - rmse: 0.4549 - smape: 0.7263 - val_ia: 0.2157 - val_loss: 0.2530 - val_mae: 0.3987 - val_rmse: 0.4174 - val_smape: 0.8528

Epoch 40/128

4586/4586 - 37s - 8ms/step - ia: 0.7391 - loss: 0.2170 - mae: 0.3612 - rmse: 0.4482 - smape: 0.7177 - val_ia: 0.2184 - val_loss: 0.2466 - val_mae: 0.3925 - val_rmse: 0.4111 - val_smape: 0.8437

Epoch 41/128

4586/4586 - 40s - 9ms/step - ia: 0.7410 - loss: 0.2150 - mae: 0.3589 - rmse: 0.4456 - smape: 0.7138 - val_ia: 0.2206 - val_loss: 0.2406 - val_mae: 0.3867 - val_rmse: 0.4053 - val_smape: 0.8351

Epoch 42/128

4586/4586 - 38s - 8ms/step - ia: 0.7432 - loss: 0.2105 - mae: 0.3552 - rmse: 0.4410 - smape: 0.7078 - val_ia: 0.2228 - val_loss: 0.2347 - val_mae: 0.3811 - val_rmse: 0.3996 - val_smape: 0.8259

Epoch 43/128

4586/4586 - 38s - 8ms/step - ia: 0.7456 - loss: 0.2084 - mae: 0.3522 - rmse: 0.4387 - smape: 0.7052 - val_ia: 0.2253 - val_loss: 0.2285 - val_mae: 0.3750 - val_rmse: 0.3935 - val_smape: 0.8158

Epoch 44/128

4586/4586 - 37s - 8ms/step - ia: 0.7500 - loss: 0.2022 - mae: 0.3470 - rmse: 0.4319 - smape: 0.6971 - val_ia: 0.2278 - val_loss: 0.2226 - val_mae: 0.3689 - val_rmse: 0.3873 - val_smape: 0.8062

Epoch 45/128

4586/4586 - 45s - 10ms/step - ia: 0.7508 - loss: 0.2003 - mae: 0.3451 - rmse: 0.4296 - smape: 0.6945 - val_ia: 0.2301 - val_loss: 0.2168 - val_mae: 0.3631 - val_rmse: 0.3815 - val_smape: 0.7964

Epoch 46/128

4586/4586 - 45s - 10ms/step - ia: 0.7552 - loss: 0.1952 - mae: 0.3406 - rmse: 0.4235 - smape: 0.6890 - val_ia: 0.2319 - val_loss: 0.2117 - val_mae: 0.3580 - val_rmse: 0.3763 - val_smape: 0.7875

Epoch 47/128

4586/4586 - 46s - 10ms/step - ia: 0.7556 - loss: 0.1944 - mae: 0.3388 - rmse: 0.4221 - smape: 0.6850 - val_ia: 0.2338 - val_loss: 0.2064 - val_mae: 0.3525 - val_rmse: 0.3708 - val_smape: 0.7778

Epoch 48/128

4586/4586 - 46s - 10ms/step - ia: 0.7596 - loss: 0.1903 - mae: 0.3354 - rmse: 0.4179 - smape: 0.6779 - val_ia: 0.2358 - val_loss: 0.2011 - val_mae: 0.3470 - val_rmse: 0.3653 - val_smape: 0.7676

Epoch 49/128

4586/4586 - 48s - 10ms/step - ia: 0.7606 - loss: 0.1857 - mae: 0.3306 - rmse: 0.4120 - smape: 0.6705 - val_ia: 0.2379 - val_loss: 0.1963 - val_mae: 0.3421 - val_rmse: 0.3603 - val_smape: 0.7582

Epoch 50/128

4586/4586 - 46s - 10ms/step - ia: 0.7648 - loss: 0.1819 - mae: 0.3276 - rmse: 0.4083 - smape: 0.6685 - val_ia: 0.2399 - val_loss: 0.1917 - val_mae: 0.3373 - val_rmse: 0.3555 - val_smape: 0.7487

Epoch 51/128

4586/4586 - 47s - 10ms/step - ia: 0.7673 - loss: 0.1781 - mae: 0.3244 - rmse: 0.4036 - smape: 0.6627 - val_ia: 0.2420 - val_loss: 0.1873 - val_mae: 0.3327 - val_rmse: 0.3509 - val_smape: 0.7395

Epoch 52/128

4586/4586 - 46s - 10ms/step - ia: 0.7673 - loss: 0.1768 - mae: 0.3229 - rmse: 0.4021 - smape: 0.6614 - val_ia: 0.2446 - val_loss: 0.1827 - val_mae: 0.3276 - val_rmse: 0.3458 - val_smape: 0.7294

Epoch 53/128

4586/4586 - 45s - 10ms/step - ia: 0.7697 - loss: 0.1761 - mae: 0.3210 - rmse: 0.4004 - smape: 0.6560 - val_ia: 0.2467 - val_loss: 0.1786 - val_mae: 0.3233 - val_rmse: 0.3415 - val_smape: 0.7207

Epoch 54/128

4586/4586 - 47s - 10ms/step - ia: 0.7709 - loss: 0.1738 - mae: 0.3189 - rmse: 0.3981 - smape: 0.6493 - val_ia: 0.2489 - val_loss: 0.1753 - val_mae: 0.3197 - val_rmse: 0.3378 - val_smape: 0.7133

Epoch 55/128

4586/4586 - 46s - 10ms/step - ia: 0.7737 - loss: 0.1700 - mae: 0.3152 - rmse: 0.3940 - smape: 0.6453 - val_ia: 0.2511 - val_loss: 0.1718 - val_mae: 0.3157 - val_rmse: 0.3339 - val_smape: 0.7055

Epoch 56/128

4586/4586 - 44s - 10ms/step - ia: 0.7743 - loss: 0.1699 - mae: 0.3142 - rmse: 0.3929 - smape: 0.6440 - val_ia: 0.2529 - val_loss: 0.1687 - val_mae: 0.3123 - val_rmse: 0.3305 - val_smape: 0.6983

Epoch 57/128

4586/4586 - 42s - 9ms/step - ia: 0.7752 - loss: 0.1691 - mae: 0.3135 - rmse: 0.3928 - smape: 0.6396 - val_ia: 0.2550 - val_loss: 0.1657 - val_mae: 0.3089 - val_rmse: 0.3271 - val_smape: 0.6914

Epoch 58/128

4586/4586 - 41s - 9ms/step - ia: 0.7780 - loss: 0.1654 - mae: 0.3105 - rmse: 0.3877 - smape: 0.6368 - val_ia: 0.2573 - val_loss: 0.1627 - val_mae: 0.3055 - val_rmse: 0.3237 - val_smape: 0.6847

Epoch 59/128

4586/4586 - 37s - 8ms/step - ia: 0.7799 - loss: 0.1618 - mae: 0.3072 - rmse: 0.3839 - smape: 0.6323 - val_ia: 0.2592 - val_loss: 0.1602 - val_mae: 0.3027 - val_rmse: 0.3208 - val_smape: 0.6787

Epoch 60/128

4586/4586 - 38s - 8ms/step - ia: 0.7823 - loss: 0.1607 - mae: 0.3059 - rmse: 0.3823 - smape: 0.6270 - val_ia: 0.2615 - val_loss: 0.1573 - val_mae: 0.2993 - val_rmse: 0.3174 - val_smape: 0.6722

Epoch 61/128

4586/4586 - 37s - 8ms/step - ia: 0.7824 - loss: 0.1600 - mae: 0.3050 - rmse: 0.3813 - smape: 0.6269 - val_ia: 0.2628 - val_loss: 0.1549 - val_mae: 0.2967 - val_rmse: 0.3148 - val_smape: 0.6668

Epoch 62/128

4586/4586 - 36s - 8ms/step - ia: 0.7850 - loss: 0.1575 - mae: 0.3020 - rmse: 0.3780 - smape: 0.6250 - val_ia: 0.2640 - val_loss: 0.1524 - val_mae: 0.2941 - val_rmse: 0.3122 - val_smape: 0.6612

Epoch 63/128

4586/4586 - 40s - 9ms/step - ia: 0.7852 - loss: 0.1580 - mae: 0.3019 - rmse: 0.3785 - smape: 0.6194 - val_ia: 0.2656 - val_loss: 0.1503 - val_mae: 0.2915 - val_rmse: 0.3096 - val_smape: 0.6559

Epoch 64/128

4586/4586 - 37s - 8ms/step - ia: 0.7866 - loss: 0.1548 - mae: 0.2987 - rmse: 0.3740 - smape: 0.6138 - val_ia: 0.2676 - val_loss: 0.1485 - val_mae: 0.2891 - val_rmse: 0.3072 - val_smape: 0.6508

Epoch 65/128

4586/4586 - 35s - 8ms/step - ia: 0.7885 - loss: 0.1515 - mae: 0.2963 - rmse: 0.3706 - smape: 0.6125 - val_ia: 0.2690 - val_loss: 0.1460 - val_mae: 0.2865 - val_rmse: 0.3045 - val_smape: 0.6455

Epoch 66/128

4586/4586 - 35s - 8ms/step - ia: 0.7886 - loss: 0.1524 - mae: 0.2968 - rmse: 0.3711 - smape: 0.6117 - val_ia: 0.2710 - val_loss: 0.1443 - val_mae: 0.2843 - val_rmse: 0.3024 - val_smape: 0.6413

Epoch 67/128

4586/4586 - 36s - 8ms/step - ia: 0.7897 - loss: 0.1513 - mae: 0.2950 - rmse: 0.3698 - smape: 0.6091 - val_ia: 0.2723 - val_loss: 0.1425 - val_mae: 0.2823 - val_rmse: 0.3004 - val_smape: 0.6371

Epoch 68/128

4586/4586 - 38s - 8ms/step - ia: 0.7907 - loss: 0.1511 - mae: 0.2940 - rmse: 0.3695 - smape: 0.6040 - val_ia: 0.2734 - val_loss: 0.1412 - val_mae: 0.2808 - val_rmse: 0.2988 - val_smape: 0.6335

Epoch 69/128

4586/4586 - 36s - 8ms/step - ia: 0.7920 - loss: 0.1496 - mae: 0.2935 - rmse: 0.3682 - smape: 0.6039 - val_ia: 0.2749 - val_loss: 0.1391 - val_mae: 0.2783 - val_rmse: 0.2963 - val_smape: 0.6286

Epoch 70/128

4586/4586 - 41s - 9ms/step - ia: 0.7941 - loss: 0.1451 - mae: 0.2895 - rmse: 0.3625 - smape: 0.5992 - val_ia: 0.2763 - val_loss: 0.1374 - val_mae: 0.2764 - val_rmse: 0.2943 - val_smape: 0.6247

Epoch 71/128

4586/4586 - 35s - 8ms/step - ia: 0.7939 - loss: 0.1468 - mae: 0.2898 - rmse: 0.3642 - smape: 0.5977 - val_ia: 0.2778 - val_loss: 0.1360 - val_mae: 0.2746 - val_rmse: 0.2926 - val_smape: 0.6210

Epoch 72/128

4586/4586 - 37s - 8ms/step - ia: 0.7952 - loss: 0.1449 - mae: 0.2883 - rmse: 0.3621 - smape: 0.5954 - val_ia: 0.2794 - val_loss: 0.1346 - val_mae: 0.2730 - val_rmse: 0.2910 - val_smape: 0.6175

Epoch 73/128

4586/4586 - 36s - 8ms/step - ia: 0.7960 - loss: 0.1451 - mae: 0.2879 - rmse: 0.3622 - smape: 0.5932 - val_ia: 0.2807 - val_loss: 0.1331 - val_mae: 0.2714 - val_rmse: 0.2893 - val_smape: 0.6142

Epoch 74/128

4586/4586 - 36s - 8ms/step - ia: 0.7959 - loss: 0.1440 - mae: 0.2871 - rmse: 0.3605 - smape: 0.5910 - val_ia: 0.2821 - val_loss: 0.1320 - val_mae: 0.2700 - val_rmse: 0.2879 - val_smape: 0.6111

Epoch 75/128

4586/4586 - 37s - 8ms/step - ia: 0.7962 - loss: 0.1432 - mae: 0.2856 - rmse: 0.3594 - smape: 0.5879 - val_ia: 0.2829 - val_loss: 0.1308 - val_mae: 0.2688 - val_rmse: 0.2868 - val_smape: 0.6088

Epoch 76/128

4586/4586 - 47s - 10ms/step - ia: 0.7988 - loss: 0.1404 - mae: 0.2843 - rmse: 0.3567 - smape: 0.5878 - val_ia: 0.2844 - val_loss: 0.1294 - val_mae: 0.2670 - val_rmse: 0.2849 - val_smape: 0.6051

Epoch 77/128

4586/4586 - 37s - 8ms/step - ia: 0.7984 - loss: 0.1412 - mae: 0.2839 - rmse: 0.3566 - smape: 0.5847 - val_ia: 0.2855 - val_loss: 0.1281 - val_mae: 0.2655 - val_rmse: 0.2834 - val_smape: 0.6021

Epoch 78/128

4586/4586 - 39s - 9ms/step - ia: 0.8013 - loss: 0.1376 - mae: 0.2805 - rmse: 0.3523 - smape: 0.5817 - val_ia: 0.2867 - val_loss: 0.1269 - val_mae: 0.2641 - val_rmse: 0.2819 - val_smape: 0.5993

Epoch 79/128

4586/4586 - 38s - 8ms/step - ia: 0.8016 - loss: 0.1377 - mae: 0.2803 - rmse: 0.3526 - smape: 0.5810 - val_ia: 0.2882 - val_loss: 0.1256 - val_mae: 0.2623 - val_rmse: 0.2802 - val_smape: 0.5961

Epoch 80/128

4586/4586 - 40s - 9ms/step - ia: 0.8023 - loss: 0.1377 - mae: 0.2792 - rmse: 0.3515 - smape: 0.5766 - val_ia: 0.2886 - val_loss: 0.1247 - val_mae: 0.2615 - val_rmse: 0.2793 - val_smape: 0.5944

Epoch 81/128

4586/4586 - 37s - 8ms/step - ia: 0.8020 - loss: 0.1360 - mae: 0.2791 - rmse: 0.3497 - smape: 0.5774 - val_ia: 0.2895 - val_loss: 0.1235 - val_mae: 0.2601 - val_rmse: 0.2779 - val_smape: 0.5917

Epoch 82/128

4586/4586 - 37s - 8ms/step - ia: 0.8031 - loss: 0.1361 - mae: 0.2784 - rmse: 0.3498 - smape: 0.5769 - val_ia: 0.2907 - val_loss: 0.1224 - val_mae: 0.2587 - val_rmse: 0.2764 - val_smape: 0.5887

Epoch 83/128

4586/4586 - 35s - 8ms/step - ia: 0.8050 - loss: 0.1347 - mae: 0.2769 - rmse: 0.3485 - smape: 0.5710 - val_ia: 0.2914 - val_loss: 0.1214 - val_mae: 0.2577 - val_rmse: 0.2754 - val_smape: 0.5869

Epoch 84/128

4586/4586 - 37s - 8ms/step - ia: 0.8045 - loss: 0.1342 - mae: 0.2754 - rmse: 0.3477 - smape: 0.5702 - val_ia: 0.2918 - val_loss: 0.1204 - val_mae: 0.2568 - val_rmse: 0.2745 - val_smape: 0.5853

Epoch 85/128

4586/4586 - 37s - 8ms/step - ia: 0.8058 - loss: 0.1322 - mae: 0.2739 - rmse: 0.3450 - smape: 0.5680 - val_ia: 0.2929 - val_loss: 0.1194 - val_mae: 0.2556 - val_rmse: 0.2732 - val_smape: 0.5830

Epoch 86/128

4586/4586 - 36s - 8ms/step - ia: 0.8062 - loss: 0.1319 - mae: 0.2744 - rmse: 0.3451 - smape: 0.5690 - val_ia: 0.2938 - val_loss: 0.1181 - val_mae: 0.2541 - val_rmse: 0.2717 - val_smape: 0.5804

Epoch 87/128

4586/4586 - 36s - 8ms/step - ia: 0.8069 - loss: 0.1312 - mae: 0.2735 - rmse: 0.3439 - smape: 0.5670 - val_ia: 0.2948 - val_loss: 0.1176 - val_mae: 0.2534 - val_rmse: 0.2709 - val_smape: 0.5788

Epoch 88/128

4586/4586 - 36s - 8ms/step - ia: 0.8073 - loss: 0.1307 - mae: 0.2729 - rmse: 0.3437 - smape: 0.5658 - val_ia: 0.2956 - val_loss: 0.1163 - val_mae: 0.2520 - val_rmse: 0.2695 - val_smape: 0.5765

Epoch 89/128

4586/4586 - 42s - 9ms/step - ia: 0.8096 - loss: 0.1282 - mae: 0.2703 - rmse: 0.3395 - smape: 0.5638 - val_ia: 0.2971 - val_loss: 0.1154 - val_mae: 0.2507 - val_rmse: 0.2681 - val_smape: 0.5738

Epoch 90/128

4586/4586 - 37s - 8ms/step - ia: 0.8095 - loss: 0.1276 - mae: 0.2690 - rmse: 0.3388 - smape: 0.5603 - val_ia: 0.2977 - val_loss: 0.1148 - val_mae: 0.2500 - val_rmse: 0.2674 - val_smape: 0.5724

Epoch 91/128

4586/4586 - 38s - 8ms/step - ia: 0.8104 - loss: 0.1273 - mae: 0.2688 - rmse: 0.3384 - smape: 0.5591 - val_ia: 0.2991 - val_loss: 0.1138 - val_mae: 0.2486 - val_rmse: 0.2660 - val_smape: 0.5697

Epoch 92/128

4586/4586 - 37s - 8ms/step - ia: 0.8096 - loss: 0.1287 - mae: 0.2697 - rmse: 0.3401 - smape: 0.5617 - val_ia: 0.2987 - val_loss: 0.1129 - val_mae: 0.2482 - val_rmse: 0.2655 - val_smape: 0.5690

Epoch 93/128

4586/4586 - 41s - 9ms/step - ia: 0.8104 - loss: 0.1274 - mae: 0.2684 - rmse: 0.3385 - smape: 0.5587 - val_ia: 0.2991 - val_loss: 0.1122 - val_mae: 0.2476 - val_rmse: 0.2648 - val_smape: 0.5676

Epoch 94/128

4586/4586 - 35s - 8ms/step - ia: 0.8109 - loss: 0.1263 - mae: 0.2677 - rmse: 0.3376 - smape: 0.5585 - val_ia: 0.3003 - val_loss: 0.1116 - val_mae: 0.2468 - val_rmse: 0.2639 - val_smape: 0.5660

Epoch 95/128

4586/4586 - 36s - 8ms/step - ia: 0.8119 - loss: 0.1261 - mae: 0.2671 - rmse: 0.3370 - smape: 0.5555 - val_ia: 0.3003 - val_loss: 0.1107 - val_mae: 0.2462 - val_rmse: 0.2633 - val_smape: 0.5647

Epoch 96/128

4586/4586 - 43s - 9ms/step - ia: 0.8143 - loss: 0.1230 - mae: 0.2640 - rmse: 0.3324 - smape: 0.5498 - val_ia: 0.3025 - val_loss: 0.1102 - val_mae: 0.2448 - val_rmse: 0.2619 - val_smape: 0.5619

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 32s - 28ms/step - ia: 0.5327 - loss: 0.4692 - mae: 0.5400 - rmse: 0.6639 - smape: 1.0862 - val_ia: 0.4174 - val_loss: 0.2667 - val_mae: 0.4066 - val_rmse: 0.4733 - val_smape: 0.8060

Epoch 2/128

1147/1147 - 13s - 11ms/step - ia: 0.7486 - loss: 0.2346 - mae: 0.3752 - rmse: 0.4794 - smape: 0.7403 - val_ia: 0.4251 - val_loss: 0.2893 - val_mae: 0.4274 - val_rmse: 0.4935 - val_smape: 0.8025

Epoch 3/128

1147/1147 - 15s - 13ms/step - ia: 0.7658 - loss: 0.2111 - mae: 0.3550 - rmse: 0.4549 - smape: 0.7033 - val_ia: 0.4295 - val_loss: 0.2812 - val_mae: 0.4286 - val_rmse: 0.4907 - val_smape: 0.8003

Epoch 4/128

1147/1147 - 17s - 15ms/step - ia: 0.7771 - loss: 0.1940 - mae: 0.3393 - rmse: 0.4359 - smape: 0.6787 - val_ia: 0.4436 - val_loss: 0.2538 - val_mae: 0.4102 - val_rmse: 0.4690 - val_smape: 0.7827

Epoch 5/128

1147/1147 - 12s - 10ms/step - ia: 0.7906 - loss: 0.1740 - mae: 0.3209 - rmse: 0.4124 - smape: 0.6526 - val_ia: 0.4600 - val_loss: 0.2228 - val_mae: 0.3867 - val_rmse: 0.4429 - val_smape: 0.7620

Epoch 6/128

1147/1147 - 27s - 24ms/step - ia: 0.8036 - loss: 0.1543 - mae: 0.3021 - rmse: 0.3880 - smape: 0.6228 - val_ia: 0.4918 - val_loss: 0.1836 - val_mae: 0.3491 - val_rmse: 0.4028 - val_smape: 0.7235

Epoch 7/128

1147/1147 - 19s - 17ms/step - ia: 0.8175 - loss: 0.1347 - mae: 0.2820 - rmse: 0.3625 - smape: 0.5911 - val_ia: 0.5261 - val_loss: 0.1475 - val_mae: 0.3108 - val_rmse: 0.3617 - val_smape: 0.6809

Epoch 8/128

1147/1147 - 22s - 20ms/step - ia: 0.8318 - loss: 0.1171 - mae: 0.2623 - rmse: 0.3380 - smape: 0.5608 - val_ia: 0.5616 - val_loss: 0.1161 - val_mae: 0.2712 - val_rmse: 0.3215 - val_smape: 0.6371

Epoch 9/128

1147/1147 - 19s - 16ms/step - ia: 0.8403 - loss: 0.1067 - mae: 0.2493 - rmse: 0.3224 - smape: 0.5378 - val_ia: 0.5886 - val_loss: 0.0968 - val_mae: 0.2433 - val_rmse: 0.2936 - val_smape: 0.6000

Epoch 10/128

1147/1147 - 17s - 15ms/step - ia: 0.8475 - loss: 0.0979 - mae: 0.2385 - rmse: 0.3088 - smape: 0.5219 - val_ia: 0.6062 - val_loss: 0.0845 - val_mae: 0.2263 - val_rmse: 0.2745 - val_smape: 0.5765

Epoch 11/128

1147/1147 - 12s - 10ms/step - ia: 0.8539 - loss: 0.0905 - mae: 0.2292 - rmse: 0.2965 - smape: 0.5076 - val_ia: 0.6218 - val_loss: 0.0749 - val_mae: 0.2121 - val_rmse: 0.2581 - val_smape: 0.5524

Epoch 12/128

1147/1147 - 17s - 15ms/step - ia: 0.8588 - loss: 0.0855 - mae: 0.2216 - rmse: 0.2884 - smape: 0.4907 - val_ia: 0.6327 - val_loss: 0.0690 - val_mae: 0.2029 - val_rmse: 0.2476 - val_smape: 0.5346

Epoch 13/128

1147/1147 - 18s - 16ms/step - ia: 0.8635 - loss: 0.0811 - mae: 0.2147 - rmse: 0.2808 - smape: 0.4797 - val_ia: 0.6422 - val_loss: 0.0640 - val_mae: 0.1956 - val_rmse: 0.2381 - val_smape: 0.5191

Epoch 14/128

1147/1147 - 19s - 16ms/step - ia: 0.8671 - loss: 0.0773 - mae: 0.2095 - rmse: 0.2742 - smape: 0.4689 - val_ia: 0.6461 - val_loss: 0.0614 - val_mae: 0.1933 - val_rmse: 0.2339 - val_smape: 0.5153

Epoch 15/128

1147/1147 - 21s - 18ms/step - ia: 0.8698 - loss: 0.0739 - mae: 0.2052 - rmse: 0.2681 - smape: 0.4624 - val_ia: 0.6574 - val_loss: 0.0564 - val_mae: 0.1832 - val_rmse: 0.2232 - val_smape: 0.4901

Epoch 16/128

1147/1147 - 13s - 12ms/step - ia: 0.8725 - loss: 0.0720 - mae: 0.2007 - rmse: 0.2644 - smape: 0.4512 - val_ia: 0.6611 - val_loss: 0.0551 - val_mae: 0.1812 - val_rmse: 0.2204 - val_smape: 0.4830

Epoch 17/128

1147/1147 - 27s - 24ms/step - ia: 0.8749 - loss: 0.0690 - mae: 0.1971 - rmse: 0.2590 - smape: 0.4447 - val_ia: 0.6693 - val_loss: 0.0517 - val_mae: 0.1748 - val_rmse: 0.2133 - val_smape: 0.4667

Epoch 18/128

1147/1147 - 18s - 16ms/step - ia: 0.8775 - loss: 0.0671 - mae: 0.1934 - rmse: 0.2552 - smape: 0.4387 - val_ia: 0.6727 - val_loss: 0.0497 - val_mae: 0.1725 - val_rmse: 0.2098 - val_smape: 0.4656

Epoch 19/128

1147/1147 - 18s - 16ms/step - ia: 0.8790 - loss: 0.0660 - mae: 0.1912 - rmse: 0.2533 - smape: 0.4336 - val_ia: 0.6771 - val_loss: 0.0487 - val_mae: 0.1694 - val_rmse: 0.2069 - val_smape: 0.4520

Epoch 20/128

1147/1147 - 19s - 17ms/step - ia: 0.8807 - loss: 0.0646 - mae: 0.1891 - rmse: 0.2505 - smape: 0.4276 - val_ia: 0.6870 - val_loss: 0.0449 - val_mae: 0.1616 - val_rmse: 0.1985 - val_smape: 0.4332

Epoch 21/128

1147/1147 - 20s - 18ms/step - ia: 0.8805 - loss: 0.0644 - mae: 0.1887 - rmse: 0.2499 - smape: 0.4235 - val_ia: 0.6855 - val_loss: 0.0460 - val_mae: 0.1636 - val_rmse: 0.2006 - val_smape: 0.4350

Epoch 22/128

1147/1147 - 20s - 17ms/step - ia: 0.8834 - loss: 0.0617 - mae: 0.1849 - rmse: 0.2445 - smape: 0.4183 - val_ia: 0.6866 - val_loss: 0.0454 - val_mae: 0.1629 - val_rmse: 0.1996 - val_smape: 0.4344

Epoch 23/128

1147/1147 - 18s - 16ms/step - ia: 0.8844 - loss: 0.0608 - mae: 0.1831 - rmse: 0.2425 - smape: 0.4138 - val_ia: 0.6916 - val_loss: 0.0440 - val_mae: 0.1597 - val_rmse: 0.1962 - val_smape: 0.4239

Epoch 24/128

1147/1147 - 18s - 16ms/step - ia: 0.8863 - loss: 0.0588 - mae: 0.1798 - rmse: 0.2388 - smape: 0.4095 - val_ia: 0.7007 - val_loss: 0.0406 - val_mae: 0.1522 - val_rmse: 0.1884 - val_smape: 0.4027

Epoch 25/128

1147/1147 - 28s - 24ms/step - ia: 0.8868 - loss: 0.0583 - mae: 0.1789 - rmse: 0.2378 - smape: 0.4036 - val_ia: 0.7009 - val_loss: 0.0408 - val_mae: 0.1529 - val_rmse: 0.1889 - val_smape: 0.4061

Epoch 26/128

1147/1147 - 20s - 17ms/step - ia: 0.8881 - loss: 0.0575 - mae: 0.1773 - rmse: 0.2359 - smape: 0.4021 - val_ia: 0.7022 - val_loss: 0.0403 - val_mae: 0.1519 - val_rmse: 0.1878 - val_smape: 0.4024

Epoch 27/128

1147/1147 - 13s - 11ms/step - ia: 0.8896 - loss: 0.0559 - mae: 0.1748 - rmse: 0.2327 - smape: 0.3951 - val_ia: 0.7020 - val_loss: 0.0407 - val_mae: 0.1528 - val_rmse: 0.1886 - val_smape: 0.4041

Epoch 28/128

1147/1147 - 14s - 13ms/step - ia: 0.8902 - loss: 0.0555 - mae: 0.1742 - rmse: 0.2320 - smape: 0.3955 - val_ia: 0.7104 - val_loss: 0.0378 - val_mae: 0.1462 - val_rmse: 0.1820 - val_smape: 0.3864

Epoch 29/128

1147/1147 - 24s - 21ms/step - ia: 0.8912 - loss: 0.0544 - mae: 0.1725 - rmse: 0.2297 - smape: 0.3920 - val_ia: 0.7093 - val_loss: 0.0386 - val_mae: 0.1478 - val_rmse: 0.1836 - val_smape: 0.3895

Epoch 30/128

1147/1147 - 18s - 16ms/step - ia: 0.8926 - loss: 0.0534 - mae: 0.1709 - rmse: 0.2276 - smape: 0.3884 - val_ia: 0.7126 - val_loss: 0.0375 - val_mae: 0.1450 - val_rmse: 0.1809 - val_smape: 0.3796

Epoch 31/128

1147/1147 - 19s - 16ms/step - ia: 0.8929 - loss: 0.0531 - mae: 0.1703 - rmse: 0.2270 - smape: 0.3877 - val_ia: 0.7130 - val_loss: 0.0375 - val_mae: 0.1459 - val_rmse: 0.1810 - val_smape: 0.3901

Epoch 32/128

1147/1147 - 18s - 16ms/step - ia: 0.8942 - loss: 0.0517 - mae: 0.1681 - rmse: 0.2238 - smape: 0.3807 - val_ia: 0.7152 - val_loss: 0.0370 - val_mae: 0.1441 - val_rmse: 0.1796 - val_smape: 0.3790

Epoch 33/128

1147/1147 - 22s - 19ms/step - ia: 0.8946 - loss: 0.0515 - mae: 0.1676 - rmse: 0.2232 - smape: 0.3803 - val_ia: 0.7141 - val_loss: 0.0376 - val_mae: 0.1454 - val_rmse: 0.1810 - val_smape: 0.3834

Epoch 34/128

1147/1147 - 18s - 16ms/step - ia: 0.8957 - loss: 0.0506 - mae: 0.1656 - rmse: 0.2213 - smape: 0.3780 - val_ia: 0.7158 - val_loss: 0.0371 - val_mae: 0.1439 - val_rmse: 0.1797 - val_smape: 0.3751

Epoch 35/128

1147/1147 - 19s - 16ms/step - ia: 0.8970 - loss: 0.0494 - mae: 0.1640 - rmse: 0.2187 - smape: 0.3754 - val_ia: 0.7226 - val_loss: 0.0350 - val_mae: 0.1391 - val_rmse: 0.1747 - val_smape: 0.3638

Epoch 36/128

1147/1147 - 18s - 16ms/step - ia: 0.8976 - loss: 0.0487 - mae: 0.1630 - rmse: 0.2173 - smape: 0.3709 - val_ia: 0.7183 - val_loss: 0.0365 - val_mae: 0.1422 - val_rmse: 0.1780 - val_smape: 0.3667

Epoch 37/128

1147/1147 - 19s - 16ms/step - ia: 0.8980 - loss: 0.0483 - mae: 0.1621 - rmse: 0.2163 - smape: 0.3692 - val_ia: 0.7210 - val_loss: 0.0356 - val_mae: 0.1406 - val_rmse: 0.1761 - val_smape: 0.3660

Epoch 38/128

1147/1147 - 21s - 18ms/step - ia: 0.8983 - loss: 0.0478 - mae: 0.1613 - rmse: 0.2151 - smape: 0.3680 - val_ia: 0.7243 - val_loss: 0.0347 - val_mae: 0.1383 - val_rmse: 0.1738 - val_smape: 0.3602

Epoch 39/128

1147/1147 - 18s - 16ms/step - ia: 0.8997 - loss: 0.0470 - mae: 0.1599 - rmse: 0.2135 - smape: 0.3629 - val_ia: 0.7249 - val_loss: 0.0347 - val_mae: 0.1384 - val_rmse: 0.1739 - val_smape: 0.3599

Epoch 40/128

1147/1147 - 19s - 16ms/step - ia: 0.8999 - loss: 0.0469 - mae: 0.1595 - rmse: 0.2131 - smape: 0.3635 - val_ia: 0.7266 - val_loss: 0.0341 - val_mae: 0.1368 - val_rmse: 0.1722 - val_smape: 0.3537

Epoch 41/128

1147/1147 - 19s - 17ms/step - ia: 0.9008 - loss: 0.0461 - mae: 0.1579 - rmse: 0.2114 - smape: 0.3610 - val_ia: 0.7312 - val_loss: 0.0329 - val_mae: 0.1344 - val_rmse: 0.1693 - val_smape: 0.3553

Epoch 42/128

1147/1147 - 12s - 10ms/step - ia: 0.9014 - loss: 0.0454 - mae: 0.1570 - rmse: 0.2096 - smape: 0.3604 - val_ia: 0.7344 - val_loss: 0.0318 - val_mae: 0.1317 - val_rmse: 0.1665 - val_smape: 0.3438

Epoch 43/128

1147/1147 - 27s - 23ms/step - ia: 0.9010 - loss: 0.0458 - mae: 0.1575 - rmse: 0.2106 - smape: 0.3574 - val_ia: 0.7304 - val_loss: 0.0332 - val_mae: 0.1348 - val_rmse: 0.1699 - val_smape: 0.3530

Epoch 44/128

1147/1147 - 14s - 12ms/step - ia: 0.9020 - loss: 0.0451 - mae: 0.1563 - rmse: 0.2091 - smape: 0.3579 - val_ia: 0.7321 - val_loss: 0.0325 - val_mae: 0.1333 - val_rmse: 0.1683 - val_smape: 0.3447

Epoch 45/128

1147/1147 - 15s - 13ms/step - ia: 0.9034 - loss: 0.0437 - mae: 0.1540 - rmse: 0.2057 - smape: 0.3528 - val_ia: 0.7344 - val_loss: 0.0318 - val_mae: 0.1315 - val_rmse: 0.1664 - val_smape: 0.3372

Epoch 46/128

1147/1147 - 18s - 16ms/step - ia: 0.9030 - loss: 0.0442 - mae: 0.1549 - rmse: 0.2067 - smape: 0.3524 - val_ia: 0.7364 - val_loss: 0.0311 - val_mae: 0.1299 - val_rmse: 0.1648 - val_smape: 0.3335

Epoch 47/128

1147/1147 - 21s - 18ms/step - ia: 0.9041 - loss: 0.0432 - mae: 0.1530 - rmse: 0.2044 - smape: 0.3509 - val_ia: 0.7316 - val_loss: 0.0329 - val_mae: 0.1340 - val_rmse: 0.1691 - val_smape: 0.3481

Epoch 48/128

1147/1147 - 19s - 16ms/step - ia: 0.9048 - loss: 0.0424 - mae: 0.1518 - rmse: 0.2026 - smape: 0.3474 - val_ia: 0.7400 - val_loss: 0.0305 - val_mae: 0.1282 - val_rmse: 0.1628 - val_smape: 0.3341

Epoch 49/128

1147/1147 - 13s - 12ms/step - ia: 0.9057 - loss: 0.0417 - mae: 0.1503 - rmse: 0.2007 - smape: 0.3437 - val_ia: 0.7404 - val_loss: 0.0303 - val_mae: 0.1281 - val_rmse: 0.1626 - val_smape: 0.3340

Epoch 50/128

1147/1147 - 13s - 11ms/step - ia: 0.9059 - loss: 0.0419 - mae: 0.1504 - rmse: 0.2011 - smape: 0.3435 - val_ia: 0.7381 - val_loss: 0.0309 - val_mae: 0.1296 - val_rmse: 0.1641 - val_smape: 0.3371

Epoch 51/128

1147/1147 - 26s - 23ms/step - ia: 0.9063 - loss: 0.0410 - mae: 0.1495 - rmse: 0.1992 - smape: 0.3452 - val_ia: 0.7444 - val_loss: 0.0293 - val_mae: 0.1255 - val_rmse: 0.1598 - val_smape: 0.3294

Epoch 52/128

1147/1147 - 20s - 17ms/step - ia: 0.9063 - loss: 0.0411 - mae: 0.1493 - rmse: 0.1997 - smape: 0.3400 - val_ia: 0.7420 - val_loss: 0.0298 - val_mae: 0.1271 - val_rmse: 0.1612 - val_smape: 0.3328

Epoch 53/128

1147/1147 - 18s - 16ms/step - ia: 0.9073 - loss: 0.0405 - mae: 0.1479 - rmse: 0.1979 - smape: 0.3399 - val_ia: 0.7478 - val_loss: 0.0282 - val_mae: 0.1231 - val_rmse: 0.1568 - val_smape: 0.3218

Epoch 54/128

1147/1147 - 18s - 16ms/step - ia: 0.9076 - loss: 0.0404 - mae: 0.1478 - rmse: 0.1975 - smape: 0.3384 - val_ia: 0.7419 - val_loss: 0.0299 - val_mae: 0.1272 - val_rmse: 0.1612 - val_smape: 0.3324

Epoch 55/128

1147/1147 - 14s - 12ms/step - ia: 0.9081 - loss: 0.0399 - mae: 0.1470 - rmse: 0.1963 - smape: 0.3357 - val_ia: 0.7463 - val_loss: 0.0288 - val_mae: 0.1245 - val_rmse: 0.1581 - val_smape: 0.3282

Epoch 56/128

1147/1147 - 12s - 11ms/step - ia: 0.9084 - loss: 0.0397 - mae: 0.1464 - rmse: 0.1957 - smape: 0.3378 - val_ia: 0.7397 - val_loss: 0.0306 - val_mae: 0.1290 - val_rmse: 0.1629 - val_smape: 0.3386

Epoch 57/128

1147/1147 - 18s - 16ms/step - ia: 0.9090 - loss: 0.0390 - mae: 0.1455 - rmse: 0.1943 - smape: 0.3355 - val_ia: 0.7477 - val_loss: 0.0283 - val_mae: 0.1233 - val_rmse: 0.1567 - val_smape: 0.3207

Epoch 58/128

1147/1147 - 18s - 16ms/step - ia: 0.9100 - loss: 0.0383 - mae: 0.1438 - rmse: 0.1924 - smape: 0.3305 - val_ia: 0.7495 - val_loss: 0.0279 - val_mae: 0.1221 - val_rmse: 0.1554 - val_smape: 0.3178

Epoch 59/128

1147/1147 - 18s - 15ms/step - ia: 0.9104 - loss: 0.0380 - mae: 0.1437 - rmse: 0.1919 - smape: 0.3304 - val_ia: 0.7499 - val_loss: 0.0277 - val_mae: 0.1220 - val_rmse: 0.1552 - val_smape: 0.3176

Epoch 60/128

1147/1147 - 18s - 16ms/step - ia: 0.9108 - loss: 0.0372 - mae: 0.1423 - rmse: 0.1901 - smape: 0.3301 - val_ia: 0.7518 - val_loss: 0.0273 - val_mae: 0.1206 - val_rmse: 0.1537 - val_smape: 0.3137

Epoch 61/128

1147/1147 - 20s - 18ms/step - ia: 0.9110 - loss: 0.0375 - mae: 0.1425 - rmse: 0.1903 - smape: 0.3290 - val_ia: 0.7539 - val_loss: 0.0268 - val_mae: 0.1194 - val_rmse: 0.1525 - val_smape: 0.3123

Epoch 62/128

1147/1147 - 19s - 16ms/step - ia: 0.9111 - loss: 0.0370 - mae: 0.1422 - rmse: 0.1893 - smape: 0.3278 - val_ia: 0.7521 - val_loss: 0.0273 - val_mae: 0.1207 - val_rmse: 0.1537 - val_smape: 0.3148

Epoch 63/128

1147/1147 - 14s - 12ms/step - ia: 0.9113 - loss: 0.0372 - mae: 0.1418 - rmse: 0.1897 - smape: 0.3250 - val_ia: 0.7531 - val_loss: 0.0269 - val_mae: 0.1202 - val_rmse: 0.1528 - val_smape: 0.3153

Epoch 64/128

1147/1147 - 13s - 11ms/step - ia: 0.9121 - loss: 0.0365 - mae: 0.1405 - rmse: 0.1878 - smape: 0.3247 - val_ia: 0.7566 - val_loss: 0.0262 - val_mae: 0.1180 - val_rmse: 0.1505 - val_smape: 0.3113

Epoch 65/128

1147/1147 - 18s - 16ms/step - ia: 0.9130 - loss: 0.0360 - mae: 0.1393 - rmse: 0.1868 - smape: 0.3218 - val_ia: 0.7559 - val_loss: 0.0262 - val_mae: 0.1185 - val_rmse: 0.1508 - val_smape: 0.3109

Epoch 66/128

1147/1147 - 13s - 11ms/step - ia: 0.9130 - loss: 0.0359 - mae: 0.1393 - rmse: 0.1861 - smape: 0.3211 - val_ia: 0.7560 - val_loss: 0.0261 - val_mae: 0.1184 - val_rmse: 0.1506 - val_smape: 0.3099

Epoch 67/128

1147/1147 - 16s - 14ms/step - ia: 0.9134 - loss: 0.0352 - mae: 0.1385 - rmse: 0.1843 - smape: 0.3215 - val_ia: 0.7635 - val_loss: 0.0244 - val_mae: 0.1135 - val_rmse: 0.1455 - val_smape: 0.2990

Epoch 68/128

1147/1147 - 24s - 21ms/step - ia: 0.9137 - loss: 0.0351 - mae: 0.1380 - rmse: 0.1843 - smape: 0.3194 - val_ia: 0.7558 - val_loss: 0.0260 - val_mae: 0.1181 - val_rmse: 0.1501 - val_smape: 0.3038

Epoch 69/128

1147/1147 - 18s - 16ms/step - ia: 0.9133 - loss: 0.0354 - mae: 0.1385 - rmse: 0.1849 - smape: 0.3165 - val_ia: 0.7604 - val_loss: 0.0250 - val_mae: 0.1154 - val_rmse: 0.1471 - val_smape: 0.2992

Epoch 70/128

1147/1147 - 19s - 16ms/step - ia: 0.9147 - loss: 0.0346 - mae: 0.1366 - rmse: 0.1829 - smape: 0.3137 - val_ia: 0.7623 - val_loss: 0.0248 - val_mae: 0.1145 - val_rmse: 0.1463 - val_smape: 0.3015

Epoch 71/128

1147/1147 - 13s - 12ms/step - ia: 0.9147 - loss: 0.0347 - mae: 0.1367 - rmse: 0.1830 - smape: 0.3144 - val_ia: 0.7610 - val_loss: 0.0248 - val_mae: 0.1151 - val_rmse: 0.1465 - val_smape: 0.2989

Epoch 72/128

1147/1147 - 15s - 13ms/step - ia: 0.9152 - loss: 0.0341 - mae: 0.1359 - rmse: 0.1814 - smape: 0.3159 - val_ia: 0.7627 - val_loss: 0.0245 - val_mae: 0.1141 - val_rmse: 0.1454 - val_smape: 0.2994

Epoch 73/128

1147/1147 - 24s - 21ms/step - ia: 0.9150 - loss: 0.0342 - mae: 0.1362 - rmse: 0.1818 - smape: 0.3135 - val_ia: 0.7617 - val_loss: 0.0246 - val_mae: 0.1147 - val_rmse: 0.1457 - val_smape: 0.2967

Epoch 74/128

1147/1147 - 17s - 14ms/step - ia: 0.9155 - loss: 0.0336 - mae: 0.1350 - rmse: 0.1802 - smape: 0.3123 - val_ia: 0.7683 - val_loss: 0.0232 - val_mae: 0.1109 - val_rmse: 0.1417 - val_smape: 0.2937

Epoch 75/128

1147/1147 - 12s - 10ms/step - ia: 0.9162 - loss: 0.0330 - mae: 0.1342 - rmse: 0.1789 - smape: 0.3107 - val_ia: 0.7670 - val_loss: 0.0232 - val_mae: 0.1112 - val_rmse: 0.1418 - val_smape: 0.2879

Epoch 76/128

1147/1147 - 18s - 15ms/step - ia: 0.9162 - loss: 0.0331 - mae: 0.1338 - rmse: 0.1791 - smape: 0.3092 - val_ia: 0.7651 - val_loss: 0.0237 - val_mae: 0.1125 - val_rmse: 0.1431 - val_smape: 0.2937

Epoch 77/128

1147/1147 - 18s - 16ms/step - ia: 0.9161 - loss: 0.0333 - mae: 0.1342 - rmse: 0.1793 - smape: 0.3108 - val_ia: 0.7724 - val_loss: 0.0224 - val_mae: 0.1088 - val_rmse: 0.1392 - val_smape: 0.2924

Epoch 78/128

1147/1147 - 17s - 14ms/step - ia: 0.9170 - loss: 0.0327 - mae: 0.1332 - rmse: 0.1778 - smape: 0.3085 - val_ia: 0.7652 - val_loss: 0.0234 - val_mae: 0.1121 - val_rmse: 0.1424 - val_smape: 0.2893

Epoch 79/128

1147/1147 - 11s - 10ms/step - ia: 0.9167 - loss: 0.0332 - mae: 0.1336 - rmse: 0.1789 - smape: 0.3072 - val_ia: 0.7705 - val_loss: 0.0225 - val_mae: 0.1094 - val_rmse: 0.1395 - val_smape: 0.2887

Epoch 80/128

1147/1147 - 17s - 14ms/step - ia: 0.9174 - loss: 0.0324 - mae: 0.1325 - rmse: 0.1769 - smape: 0.3069 - val_ia: 0.7735 - val_loss: 0.0220 - val_mae: 0.1078 - val_rmse: 0.1378 - val_smape: 0.2854

Epoch 81/128

1147/1147 - 23s - 20ms/step - ia: 0.9177 - loss: 0.0324 - mae: 0.1322 - rmse: 0.1769 - smape: 0.3057 - val_ia: 0.7703 - val_loss: 0.0224 - val_mae: 0.1093 - val_rmse: 0.1392 - val_smape: 0.2858

Epoch 82/128

1147/1147 - 19s - 16ms/step - ia: 0.9177 - loss: 0.0321 - mae: 0.1319 - rmse: 0.1763 - smape: 0.3033 - val_ia: 0.7765 - val_loss: 0.0213 - val_mae: 0.1059 - val_rmse: 0.1355 - val_smape: 0.2804

Epoch 83/128

1147/1147 - 18s - 16ms/step - ia: 0.9186 - loss: 0.0314 - mae: 0.1304 - rmse: 0.1742 - smape: 0.3013 - val_ia: 0.7723 - val_loss: 0.0218 - val_mae: 0.1078 - val_rmse: 0.1372 - val_smape: 0.2787

Epoch 84/128

1147/1147 - 11s - 10ms/step - ia: 0.9185 - loss: 0.0318 - mae: 0.1305 - rmse: 0.1753 - smape: 0.3022 - val_ia: 0.7719 - val_loss: 0.0219 - val_mae: 0.1083 - val_rmse: 0.1375 - val_smape: 0.2840

Epoch 85/128

1147/1147 - 16s - 14ms/step - ia: 0.9187 - loss: 0.0314 - mae: 0.1303 - rmse: 0.1740 - smape: 0.3023 - val_ia: 0.7774 - val_loss: 0.0207 - val_mae: 0.1050 - val_rmse: 0.1340 - val_smape: 0.2739

Epoch 86/128

1147/1147 - 24s - 21ms/step - ia: 0.9191 - loss: 0.0312 - mae: 0.1299 - rmse: 0.1737 - smape: 0.2987 - val_ia: 0.7808 - val_loss: 0.0202 - val_mae: 0.1030 - val_rmse: 0.1321 - val_smape: 0.2694

Epoch 87/128

1147/1147 - 19s - 16ms/step - ia: 0.9188 - loss: 0.0313 - mae: 0.1301 - rmse: 0.1736 - smape: 0.3012 - val_ia: 0.7758 - val_loss: 0.0210 - val_mae: 0.1058 - val_rmse: 0.1349 - val_smape: 0.2753

Epoch 88/128

1147/1147 - 21s - 18ms/step - ia: 0.9196 - loss: 0.0306 - mae: 0.1287 - rmse: 0.1719 - smape: 0.3005 - val_ia: 0.7823 - val_loss: 0.0198 - val_mae: 0.1023 - val_rmse: 0.1311 - val_smape: 0.2693

Epoch 89/128

1147/1147 - 19s - 17ms/step - ia: 0.9193 - loss: 0.0311 - mae: 0.1294 - rmse: 0.1731 - smape: 0.2988 - val_ia: 0.7804 - val_loss: 0.0201 - val_mae: 0.1036 - val_rmse: 0.1321 - val_smape: 0.2724

Epoch 90/128

1147/1147 - 18s - 16ms/step - ia: 0.9198 - loss: 0.0306 - mae: 0.1284 - rmse: 0.1717 - smape: 0.2966 - val_ia: 0.7823 - val_loss: 0.0196 - val_mae: 0.1020 - val_rmse: 0.1303 - val_smape: 0.2652

Epoch 91/128

1147/1147 - 19s - 16ms/step - ia: 0.9200 - loss: 0.0305 - mae: 0.1281 - rmse: 0.1716 - smape: 0.2965 - val_ia: 0.7836 - val_loss: 0.0193 - val_mae: 0.1014 - val_rmse: 0.1295 - val_smape: 0.2659

Epoch 92/128

1147/1147 - 18s - 16ms/step - ia: 0.9208 - loss: 0.0297 - mae: 0.1272 - rmse: 0.1695 - smape: 0.2942 - val_ia: 0.7856 - val_loss: 0.0190 - val_mae: 0.1004 - val_rmse: 0.1284 - val_smape: 0.2634

Epoch 93/128

1147/1147 - 19s - 16ms/step - ia: 0.9205 - loss: 0.0302 - mae: 0.1276 - rmse: 0.1708 - smape: 0.2956 - val_ia: 0.7962 - val_loss: 0.0172 - val_mae: 0.0949 - val_rmse: 0.1226 - val_smape: 0.2533

Epoch 94/128

1147/1147 - 19s - 16ms/step - ia: 0.9204 - loss: 0.0302 - mae: 0.1277 - rmse: 0.1706 - smape: 0.2948 - val_ia: 0.7851 - val_loss: 0.0190 - val_mae: 0.1007 - val_rmse: 0.1284 - val_smape: 0.2672

Epoch 95/128

1147/1147 - 20s - 17ms/step - ia: 0.9212 - loss: 0.0297 - mae: 0.1264 - rmse: 0.1694 - smape: 0.2918 - val_ia: 0.7838 - val_loss: 0.0193 - val_mae: 0.1016 - val_rmse: 0.1292 - val_smape: 0.2715

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

574/574 - 13s - 23ms/step - ia: 0.4696 - loss: 0.5339 - mae: 0.6075 - rmse: 0.7288 - smape: 1.1857 - val_ia: 0.4032 - val_loss: 0.5074 - val_mae: 0.5906 - val_rmse: 0.6844 - val_smape: 1.2473

Epoch 2/128

574/574 - 6s - 10ms/step - ia: 0.5039 - loss: 0.4941 - mae: 0.5843 - rmse: 0.7007 - smape: 1.1339 - val_ia: 0.4221 - val_loss: 0.4726 - val_mae: 0.5687 - val_rmse: 0.6599 - val_smape: 1.1793

Epoch 3/128

574/574 - 10s - 17ms/step - ia: 0.5367 - loss: 0.4573 - mae: 0.5606 - rmse: 0.6740 - smape: 1.0797 - val_ia: 0.4408 - val_loss: 0.4414 - val_mae: 0.5481 - val_rmse: 0.6371 - val_smape: 1.1184

Epoch 4/128

574/574 - 4s - 7ms/step - ia: 0.5645 - loss: 0.4266 - mae: 0.5401 - rmse: 0.6519 - smape: 1.0346 - val_ia: 0.4588 - val_loss: 0.4138 - val_mae: 0.5290 - val_rmse: 0.6163 - val_smape: 1.0651

Epoch 5/128

574/574 - 4s - 7ms/step - ia: 0.5927 - loss: 0.3964 - mae: 0.5195 - rmse: 0.6276 - smape: 0.9905 - val_ia: 0.4760 - val_loss: 0.3893 - val_mae: 0.5112 - val_rmse: 0.5972 - val_smape: 1.0184

Epoch 6/128

574/574 - 4s - 7ms/step - ia: 0.6164 - loss: 0.3717 - mae: 0.5006 - rmse: 0.6077 - smape: 0.9521 - val_ia: 0.4928 - val_loss: 0.3678 - val_mae: 0.4946 - val_rmse: 0.5800 - val_smape: 0.9768

Epoch 7/128

574/574 - 4s - 8ms/step - ia: 0.6357 - loss: 0.3522 - mae: 0.4861 - rmse: 0.5917 - smape: 0.9226 - val_ia: 0.5095 - val_loss: 0.3495 - val_mae: 0.4794 - val_rmse: 0.5649 - val_smape: 0.9407

Epoch 8/128

574/574 - 4s - 8ms/step - ia: 0.6549 - loss: 0.3331 - mae: 0.4702 - rmse: 0.5753 - smape: 0.8914 - val_ia: 0.5257 - val_loss: 0.3338 - val_mae: 0.4659 - val_rmse: 0.5517 - val_smape: 0.9089

Epoch 9/128

574/574 - 4s - 8ms/step - ia: 0.6705 - loss: 0.3168 - mae: 0.4577 - rmse: 0.5609 - smape: 0.8676 - val_ia: 0.5407 - val_loss: 0.3208 - val_mae: 0.4540 - val_rmse: 0.5405 - val_smape: 0.8814

Epoch 10/128

574/574 - 4s - 7ms/step - ia: 0.6869 - loss: 0.3018 - mae: 0.4435 - rmse: 0.5473 - smape: 0.8422 - val_ia: 0.5541 - val_loss: 0.3102 - val_mae: 0.4440 - val_rmse: 0.5312 - val_smape: 0.8594

Epoch 11/128

574/574 - 5s - 8ms/step - ia: 0.6976 - loss: 0.2920 - mae: 0.4342 - rmse: 0.5385 - smape: 0.8240 - val_ia: 0.5654 - val_loss: 0.3018 - val_mae: 0.4360 - val_rmse: 0.5235 - val_smape: 0.8421

Epoch 12/128

574/574 - 4s - 7ms/step - ia: 0.7085 - loss: 0.2815 - mae: 0.4252 - rmse: 0.5289 - smape: 0.8092 - val_ia: 0.5742 - val_loss: 0.2954 - val_mae: 0.4301 - val_rmse: 0.5176 - val_smape: 0.8292

Epoch 13/128

574/574 - 5s - 8ms/step - ia: 0.7186 - loss: 0.2730 - mae: 0.4162 - rmse: 0.5201 - smape: 0.7913 - val_ia: 0.5810 - val_loss: 0.2907 - val_mae: 0.4257 - val_rmse: 0.5130 - val_smape: 0.8193

Epoch 14/128

574/574 - 4s - 8ms/step - ia: 0.7252 - loss: 0.2666 - mae: 0.4101 - rmse: 0.5143 - smape: 0.7800 - val_ia: 0.5864 - val_loss: 0.2870 - val_mae: 0.4226 - val_rmse: 0.5092 - val_smape: 0.8120

Epoch 15/128

574/574 - 5s - 9ms/step - ia: 0.7322 - loss: 0.2595 - mae: 0.4026 - rmse: 0.5072 - smape: 0.7669 - val_ia: 0.5904 - val_loss: 0.2843 - val_mae: 0.4205 - val_rmse: 0.5062 - val_smape: 0.8065

Epoch 16/128

574/574 - 4s - 8ms/step - ia: 0.7386 - loss: 0.2518 - mae: 0.3958 - rmse: 0.5000 - smape: 0.7571 - val_ia: 0.5935 - val_loss: 0.2822 - val_mae: 0.4191 - val_rmse: 0.5038 - val_smape: 0.8029

Epoch 17/128

574/574 - 4s - 8ms/step - ia: 0.7442 - loss: 0.2455 - mae: 0.3901 - rmse: 0.4933 - smape: 0.7476 - val_ia: 0.5956 - val_loss: 0.2811 - val_mae: 0.4186 - val_rmse: 0.5021 - val_smape: 0.8006

Epoch 18/128

574/574 - 4s - 7ms/step - ia: 0.7472 - loss: 0.2419 - mae: 0.3867 - rmse: 0.4896 - smape: 0.7411 - val_ia: 0.5973 - val_loss: 0.2800 - val_mae: 0.4182 - val_rmse: 0.5004 - val_smape: 0.7988

Epoch 19/128

574/574 - 4s - 7ms/step - ia: 0.7515 - loss: 0.2369 - mae: 0.3822 - rmse: 0.4846 - smape: 0.7328 - val_ia: 0.5981 - val_loss: 0.2797 - val_mae: 0.4184 - val_rmse: 0.4993 - val_smape: 0.7982

Epoch 20/128

574/574 - 4s - 7ms/step - ia: 0.7543 - loss: 0.2322 - mae: 0.3788 - rmse: 0.4797 - smape: 0.7269 - val_ia: 0.5988 - val_loss: 0.2794 - val_mae: 0.4187 - val_rmse: 0.4984 - val_smape: 0.7979

Epoch 21/128

574/574 - 5s - 9ms/step - ia: 0.7571 - loss: 0.2288 - mae: 0.3748 - rmse: 0.4763 - smape: 0.7216 - val_ia: 0.5994 - val_loss: 0.2792 - val_mae: 0.4191 - val_rmse: 0.4975 - val_smape: 0.7977

Epoch 22/128

574/574 - 4s - 8ms/step - ia: 0.7613 - loss: 0.2219 - mae: 0.3688 - rmse: 0.4690 - smape: 0.7139 - val_ia: 0.5998 - val_loss: 0.2793 - val_mae: 0.4196 - val_rmse: 0.4968 - val_smape: 0.7972

Epoch 23/128

574/574 - 5s - 9ms/step - ia: 0.7631 - loss: 0.2191 - mae: 0.3667 - rmse: 0.4660 - smape: 0.7103 - val_ia: 0.5998 - val_loss: 0.2796 - val_mae: 0.4203 - val_rmse: 0.4964 - val_smape: 0.7975

Epoch 24/128

574/574 - 4s - 8ms/step - ia: 0.7653 - loss: 0.2160 - mae: 0.3632 - rmse: 0.4632 - smape: 0.7054 - val_ia: 0.6000 - val_loss: 0.2798 - val_mae: 0.4209 - val_rmse: 0.4959 - val_smape: 0.7972

Epoch 25/128

574/574 - 4s - 7ms/step - ia: 0.7695 - loss: 0.2089 - mae: 0.3578 - rmse: 0.4548 - smape: 0.6973 - val_ia: 0.5999 - val_loss: 0.2803 - val_mae: 0.4218 - val_rmse: 0.4958 - val_smape: 0.7977

Epoch 26/128

574/574 - 5s - 9ms/step - ia: 0.7706 - loss: 0.2081 - mae: 0.3557 - rmse: 0.4540 - smape: 0.6937 - val_ia: 0.5998 - val_loss: 0.2807 - val_mae: 0.4225 - val_rmse: 0.4957 - val_smape: 0.7983

Epoch 27/128

574/574 - 5s - 8ms/step - ia: 0.7725 - loss: 0.2048 - mae: 0.3533 - rmse: 0.4502 - smape: 0.6897 - val_ia: 0.5997 - val_loss: 0.2810 - val_mae: 0.4232 - val_rmse: 0.4955 - val_smape: 0.7987

Epoch 28/128

574/574 - 5s - 9ms/step - ia: 0.7762 - loss: 0.1995 - mae: 0.3486 - rmse: 0.4447 - smape: 0.6838 - val_ia: 0.5995 - val_loss: 0.2812 - val_mae: 0.4240 - val_rmse: 0.4954 - val_smape: 0.7998

Epoch 29/128

574/574 - 4s - 8ms/step - ia: 0.7777 - loss: 0.1969 - mae: 0.3461 - rmse: 0.4418 - smape: 0.6809 - val_ia: 0.5994 - val_loss: 0.2814 - val_mae: 0.4247 - val_rmse: 0.4953 - val_smape: 0.8001

Epoch 30/128

574/574 - 4s - 8ms/step - ia: 0.7793 - loss: 0.1937 - mae: 0.3435 - rmse: 0.4378 - smape: 0.6759 - val_ia: 0.5994 - val_loss: 0.2813 - val_mae: 0.4251 - val_rmse: 0.4950 - val_smape: 0.8007

Epoch 31/128

574/574 - 5s - 9ms/step - ia: 0.7820 - loss: 0.1891 - mae: 0.3388 - rmse: 0.4332 - smape: 0.6690 - val_ia: 0.5995 - val_loss: 0.2809 - val_mae: 0.4253 - val_rmse: 0.4945 - val_smape: 0.8015

Epoch 32/128

574/574 - 5s - 9ms/step - ia: 0.7838 - loss: 0.1867 - mae: 0.3370 - rmse: 0.4301 - smape: 0.6671 - val_ia: 0.5996 - val_loss: 0.2805 - val_mae: 0.4255 - val_rmse: 0.4940 - val_smape: 0.8021

Epoch 33/128

574/574 - 5s - 9ms/step - ia: 0.7866 - loss: 0.1833 - mae: 0.3330 - rmse: 0.4259 - smape: 0.6601 - val_ia: 0.5998 - val_loss: 0.2797 - val_mae: 0.4254 - val_rmse: 0.4933 - val_smape: 0.8024

Epoch 34/128

574/574 - 5s - 9ms/step - ia: 0.7889 - loss: 0.1798 - mae: 0.3300 - rmse: 0.4220 - smape: 0.6566 - val_ia: 0.6001 - val_loss: 0.2788 - val_mae: 0.4252 - val_rmse: 0.4924 - val_smape: 0.8028

Epoch 35/128

574/574 - 4s - 7ms/step - ia: 0.7903 - loss: 0.1781 - mae: 0.3279 - rmse: 0.4198 - smape: 0.6514 - val_ia: 0.6002 - val_loss: 0.2778 - val_mae: 0.4250 - val_rmse: 0.4916 - val_smape: 0.8041

Epoch 36/128

574/574 - 5s - 9ms/step - ia: 0.7927 - loss: 0.1739 - mae: 0.3246 - rmse: 0.4151 - smape: 0.6463 - val_ia: 0.6006 - val_loss: 0.2765 - val_mae: 0.4245 - val_rmse: 0.4905 - val_smape: 0.8048

Epoch 37/128

574/574 - 5s - 8ms/step - ia: 0.7938 - loss: 0.1724 - mae: 0.3222 - rmse: 0.4133 - smape: 0.6452 - val_ia: 0.6011 - val_loss: 0.2750 - val_mae: 0.4238 - val_rmse: 0.4892 - val_smape: 0.8048

Epoch 38/128

574/574 - 4s - 7ms/step - ia: 0.7963 - loss: 0.1682 - mae: 0.3183 - rmse: 0.4080 - smape: 0.6380 - val_ia: 0.6016 - val_loss: 0.2736 - val_mae: 0.4232 - val_rmse: 0.4881 - val_smape: 0.8049

Epoch 39/128

574/574 - 4s - 7ms/step - ia: 0.7976 - loss: 0.1673 - mae: 0.3169 - rmse: 0.4071 - smape: 0.6345 - val_ia: 0.6026 - val_loss: 0.2714 - val_mae: 0.4218 - val_rmse: 0.4862 - val_smape: 0.8042

Epoch 40/128

574/574 - 4s - 7ms/step - ia: 0.7982 - loss: 0.1658 - mae: 0.3153 - rmse: 0.4050 - smape: 0.6333 - val_ia: 0.6035 - val_loss: 0.2690 - val_mae: 0.4203 - val_rmse: 0.4842 - val_smape: 0.8034

Epoch 41/128

574/574 - 4s - 7ms/step - ia: 0.8002 - loss: 0.1632 - mae: 0.3130 - rmse: 0.4019 - smape: 0.6305 - val_ia: 0.6041 - val_loss: 0.2670 - val_mae: 0.4192 - val_rmse: 0.4826 - val_smape: 0.8033

Epoch 42/128

574/574 - 4s - 8ms/step - ia: 0.8013 - loss: 0.1621 - mae: 0.3116 - rmse: 0.4006 - smape: 0.6265 - val_ia: 0.6055 - val_loss: 0.2642 - val_mae: 0.4173 - val_rmse: 0.4802 - val_smape: 0.8019

Epoch 43/128

574/574 - 4s - 7ms/step - ia: 0.8052 - loss: 0.1560 - mae: 0.3057 - rmse: 0.3927 - smape: 0.6203 - val_ia: 0.6071 - val_loss: 0.2609 - val_mae: 0.4148 - val_rmse: 0.4773 - val_smape: 0.7998

Epoch 44/128

574/574 - 4s - 7ms/step - ia: 0.8056 - loss: 0.1555 - mae: 0.3049 - rmse: 0.3919 - smape: 0.6181 - val_ia: 0.6082 - val_loss: 0.2584 - val_mae: 0.4131 - val_rmse: 0.4752 - val_smape: 0.7988

Epoch 45/128

574/574 - 4s - 7ms/step - ia: 0.8074 - loss: 0.1527 - mae: 0.3023 - rmse: 0.3886 - smape: 0.6124 - val_ia: 0.6096 - val_loss: 0.2555 - val_mae: 0.4110 - val_rmse: 0.4727 - val_smape: 0.7973

Epoch 46/128

574/574 - 5s - 8ms/step - ia: 0.8094 - loss: 0.1501 - mae: 0.2993 - rmse: 0.3850 - smape: 0.6118 - val_ia: 0.6108 - val_loss: 0.2528 - val_mae: 0.4090 - val_rmse: 0.4703 - val_smape: 0.7962

Epoch 47/128

574/574 - 4s - 7ms/step - ia: 0.8098 - loss: 0.1503 - mae: 0.2994 - rmse: 0.3854 - smape: 0.6088 - val_ia: 0.6128 - val_loss: 0.2492 - val_mae: 0.4062 - val_rmse: 0.4672 - val_smape: 0.7935

Epoch 48/128

574/574 - 4s - 8ms/step - ia: 0.8123 - loss: 0.1460 - mae: 0.2949 - rmse: 0.3803 - smape: 0.6035 - val_ia: 0.6145 - val_loss: 0.2460 - val_mae: 0.4037 - val_rmse: 0.4643 - val_smape: 0.7911

Epoch 49/128

574/574 - 4s - 8ms/step - ia: 0.8134 - loss: 0.1447 - mae: 0.2935 - rmse: 0.3782 - smape: 0.5998 - val_ia: 0.6162 - val_loss: 0.2429 - val_mae: 0.4012 - val_rmse: 0.4615 - val_smape: 0.7891

Epoch 50/128

574/574 - 5s - 9ms/step - ia: 0.8138 - loss: 0.1442 - mae: 0.2926 - rmse: 0.3775 - smape: 0.5969 - val_ia: 0.6183 - val_loss: 0.2391 - val_mae: 0.3980 - val_rmse: 0.4580 - val_smape: 0.7860

Epoch 51/128

574/574 - 5s - 8ms/step - ia: 0.8163 - loss: 0.1405 - mae: 0.2890 - rmse: 0.3729 - smape: 0.5932 - val_ia: 0.6205 - val_loss: 0.2352 - val_mae: 0.3947 - val_rmse: 0.4545 - val_smape: 0.7828

Epoch 52/128

574/574 - 5s - 9ms/step - ia: 0.8168 - loss: 0.1397 - mae: 0.2880 - rmse: 0.3716 - smape: 0.5916 - val_ia: 0.6229 - val_loss: 0.2315 - val_mae: 0.3915 - val_rmse: 0.4510 - val_smape: 0.7793

Epoch 53/128

574/574 - 4s - 7ms/step - ia: 0.8191 - loss: 0.1377 - mae: 0.2852 - rmse: 0.3687 - smape: 0.5878 - val_ia: 0.6250 - val_loss: 0.2280 - val_mae: 0.3885 - val_rmse: 0.4478 - val_smape: 0.7761

Epoch 54/128

574/574 - 4s - 8ms/step - ia: 0.8202 - loss: 0.1360 - mae: 0.2835 - rmse: 0.3668 - smape: 0.5833 - val_ia: 0.6273 - val_loss: 0.2244 - val_mae: 0.3852 - val_rmse: 0.4443 - val_smape: 0.7728

Epoch 55/128

574/574 - 4s - 7ms/step - ia: 0.8208 - loss: 0.1351 - mae: 0.2822 - rmse: 0.3655 - smape: 0.5826 - val_ia: 0.6302 - val_loss: 0.2199 - val_mae: 0.3811 - val_rmse: 0.4401 - val_smape: 0.7682

Epoch 56/128

574/574 - 4s - 8ms/step - ia: 0.8225 - loss: 0.1326 - mae: 0.2799 - rmse: 0.3622 - smape: 0.5782 - val_ia: 0.6322 - val_loss: 0.2167 - val_mae: 0.3783 - val_rmse: 0.4370 - val_smape: 0.7652

Epoch 57/128

574/574 - 4s - 7ms/step - ia: 0.8236 - loss: 0.1311 - mae: 0.2784 - rmse: 0.3600 - smape: 0.5755 - val_ia: 0.6347 - val_loss: 0.2129 - val_mae: 0.3748 - val_rmse: 0.4333 - val_smape: 0.7611

Epoch 58/128

574/574 - 4s - 7ms/step - ia: 0.8257 - loss: 0.1282 - mae: 0.2749 - rmse: 0.3558 - smape: 0.5705 - val_ia: 0.6365 - val_loss: 0.2102 - val_mae: 0.3723 - val_rmse: 0.4307 - val_smape: 0.7586

Epoch 59/128

574/574 - 4s - 7ms/step - ia: 0.8264 - loss: 0.1274 - mae: 0.2744 - rmse: 0.3548 - smape: 0.5696 - val_ia: 0.6393 - val_loss: 0.2061 - val_mae: 0.3684 - val_rmse: 0.4266 - val_smape: 0.7541

Epoch 60/128

574/574 - 4s - 7ms/step - ia: 0.8276 - loss: 0.1257 - mae: 0.2722 - rmse: 0.3526 - smape: 0.5654 - val_ia: 0.6418 - val_loss: 0.2025 - val_mae: 0.3648 - val_rmse: 0.4230 - val_smape: 0.7500

Epoch 61/128

574/574 - 4s - 8ms/step - ia: 0.8287 - loss: 0.1251 - mae: 0.2705 - rmse: 0.3516 - smape: 0.5624 - val_ia: 0.6443 - val_loss: 0.1990 - val_mae: 0.3615 - val_rmse: 0.4195 - val_smape: 0.7462

Epoch 62/128

574/574 - 4s - 7ms/step - ia: 0.8296 - loss: 0.1232 - mae: 0.2693 - rmse: 0.3491 - smape: 0.5615 - val_ia: 0.6473 - val_loss: 0.1950 - val_mae: 0.3575 - val_rmse: 0.4154 - val_smape: 0.7412

Epoch 63/128

574/574 - 5s - 9ms/step - ia: 0.8312 - loss: 0.1216 - mae: 0.2670 - rmse: 0.3467 - smape: 0.5558 - val_ia: 0.6502 - val_loss: 0.1914 - val_mae: 0.3538 - val_rmse: 0.4116 - val_smape: 0.7366

Epoch 64/128

574/574 - 4s - 7ms/step - ia: 0.8321 - loss: 0.1204 - mae: 0.2658 - rmse: 0.3447 - smape: 0.5541 - val_ia: 0.6528 - val_loss: 0.1879 - val_mae: 0.3502 - val_rmse: 0.4081 - val_smape: 0.7324

Epoch 65/128

574/574 - 5s - 9ms/step - ia: 0.8330 - loss: 0.1190 - mae: 0.2639 - rmse: 0.3427 - smape: 0.5531 - val_ia: 0.6562 - val_loss: 0.1836 - val_mae: 0.3458 - val_rmse: 0.4035 - val_smape: 0.7268

Epoch 66/128

574/574 - 5s - 8ms/step - ia: 0.8350 - loss: 0.1168 - mae: 0.2615 - rmse: 0.3395 - smape: 0.5490 - val_ia: 0.6584 - val_loss: 0.1808 - val_mae: 0.3427 - val_rmse: 0.4005 - val_smape: 0.7233

Epoch 67/128

574/574 - 4s - 8ms/step - ia: 0.8353 - loss: 0.1158 - mae: 0.2602 - rmse: 0.3384 - smape: 0.5461 - val_ia: 0.6616 - val_loss: 0.1770 - val_mae: 0.3388 - val_rmse: 0.3965 - val_smape: 0.7180

Epoch 68/128

574/574 - 5s - 9ms/step - ia: 0.8368 - loss: 0.1150 - mae: 0.2587 - rmse: 0.3367 - smape: 0.5435 - val_ia: 0.6643 - val_loss: 0.1738 - val_mae: 0.3355 - val_rmse: 0.3930 - val_smape: 0.7137

Epoch 69/128

574/574 - 4s - 8ms/step - ia: 0.8380 - loss: 0.1136 - mae: 0.2571 - rmse: 0.3350 - smape: 0.5420 - val_ia: 0.6671 - val_loss: 0.1705 - val_mae: 0.3318 - val_rmse: 0.3894 - val_smape: 0.7091

Epoch 70/128

574/574 - 4s - 7ms/step - ia: 0.8381 - loss: 0.1126 - mae: 0.2564 - rmse: 0.3334 - smape: 0.5399 - val_ia: 0.6705 - val_loss: 0.1668 - val_mae: 0.3276 - val_rmse: 0.3852 - val_smape: 0.7035

Epoch 71/128

574/574 - 3s - 6ms/step - ia: 0.8405 - loss: 0.1097 - mae: 0.2530 - rmse: 0.3293 - smape: 0.5337 - val_ia: 0.6730 - val_loss: 0.1639 - val_mae: 0.3244 - val_rmse: 0.3820 - val_smape: 0.6995

Epoch 72/128

574/574 - 3s - 6ms/step - ia: 0.8409 - loss: 0.1100 - mae: 0.2523 - rmse: 0.3294 - smape: 0.5325 - val_ia: 0.6756 - val_loss: 0.1611 - val_mae: 0.3211 - val_rmse: 0.3788 - val_smape: 0.6952

Epoch 73/128

574/574 - 5s - 9ms/step - ia: 0.8425 - loss: 0.1080 - mae: 0.2497 - rmse: 0.3268 - smape: 0.5279 - val_ia: 0.6791 - val_loss: 0.1574 - val_mae: 0.3171 - val_rmse: 0.3746 - val_smape: 0.6894

Epoch 74/128

574/574 - 3s - 6ms/step - ia: 0.8427 - loss: 0.1075 - mae: 0.2494 - rmse: 0.3260 - smape: 0.5282 - val_ia: 0.6822 - val_loss: 0.1542 - val_mae: 0.3133 - val_rmse: 0.3708 - val_smape: 0.6844

Epoch 75/128

574/574 - 3s - 6ms/step - ia: 0.8441 - loss: 0.1054 - mae: 0.2474 - rmse: 0.3227 - smape: 0.5260 - val_ia: 0.6847 - val_loss: 0.1517 - val_mae: 0.3103 - val_rmse: 0.3679 - val_smape: 0.6803

Epoch 76/128

574/574 - 4s - 7ms/step - ia: 0.8444 - loss: 0.1049 - mae: 0.2471 - rmse: 0.3222 - smape: 0.5244 - val_ia: 0.6870 - val_loss: 0.1493 - val_mae: 0.3074 - val_rmse: 0.3651 - val_smape: 0.6764

Epoch 77/128

574/574 - 4s - 7ms/step - ia: 0.8453 - loss: 0.1036 - mae: 0.2453 - rmse: 0.3198 - smape: 0.5219 - val_ia: 0.6904 - val_loss: 0.1459 - val_mae: 0.3033 - val_rmse: 0.3610 - val_smape: 0.6705

Epoch 78/128

574/574 - 5s - 9ms/step - ia: 0.8453 - loss: 0.1040 - mae: 0.2455 - rmse: 0.3208 - smape: 0.5215 - val_ia: 0.6934 - val_loss: 0.1431 - val_mae: 0.2999 - val_rmse: 0.3576 - val_smape: 0.6654

Epoch 79/128

574/574 - 5s - 8ms/step - ia: 0.8474 - loss: 0.1020 - mae: 0.2427 - rmse: 0.3173 - smape: 0.5163 - val_ia: 0.6959 - val_loss: 0.1406 - val_mae: 0.2969 - val_rmse: 0.3546 - val_smape: 0.6610

Epoch 80/128

574/574 - 4s - 7ms/step - ia: 0.8484 - loss: 0.1004 - mae: 0.2405 - rmse: 0.3145 - smape: 0.5129 - val_ia: 0.6996 - val_loss: 0.1372 - val_mae: 0.2929 - val_rmse: 0.3504 - val_smape: 0.6549

Epoch 81/128

574/574 - 4s - 8ms/step - ia: 0.8491 - loss: 0.0998 - mae: 0.2395 - rmse: 0.3140 - smape: 0.5112 - val_ia: 0.7021 - val_loss: 0.1348 - val_mae: 0.2896 - val_rmse: 0.3473 - val_smape: 0.6501

Epoch 82/128

574/574 - 4s - 8ms/step - ia: 0.8485 - loss: 0.0996 - mae: 0.2408 - rmse: 0.3136 - smape: 0.5131 - val_ia: 0.7048 - val_loss: 0.1324 - val_mae: 0.2866 - val_rmse: 0.3443 - val_smape: 0.6453

Epoch 83/128

574/574 - 5s - 9ms/step - ia: 0.8510 - loss: 0.0982 - mae: 0.2368 - rmse: 0.3113 - smape: 0.5058 - val_ia: 0.7074 - val_loss: 0.1301 - val_mae: 0.2837 - val_rmse: 0.3414 - val_smape: 0.6409

Epoch 84/128

574/574 - 4s - 7ms/step - ia: 0.8501 - loss: 0.0981 - mae: 0.2378 - rmse: 0.3110 - smape: 0.5087 - val_ia: 0.7106 - val_loss: 0.1273 - val_mae: 0.2801 - val_rmse: 0.3378 - val_smape: 0.6355

Epoch 85/128

574/574 - 4s - 7ms/step - ia: 0.8521 - loss: 0.0961 - mae: 0.2354 - rmse: 0.3080 - smape: 0.5049 - val_ia: 0.7126 - val_loss: 0.1255 - val_mae: 0.2778 - val_rmse: 0.3355 - val_smape: 0.6318

Epoch 86/128

574/574 - 5s - 8ms/step - ia: 0.8529 - loss: 0.0951 - mae: 0.2340 - rmse: 0.3065 - smape: 0.5022 - val_ia: 0.7151 - val_loss: 0.1233 - val_mae: 0.2749 - val_rmse: 0.3326 - val_smape: 0.6273

Epoch 87/128

574/574 - 5s - 9ms/step - ia: 0.8525 - loss: 0.0952 - mae: 0.2346 - rmse: 0.3064 - smape: 0.5040 - val_ia: 0.7174 - val_loss: 0.1214 - val_mae: 0.2722 - val_rmse: 0.3301 - val_smape: 0.6229

Epoch 88/128

574/574 - 4s - 8ms/step - ia: 0.8538 - loss: 0.0939 - mae: 0.2324 - rmse: 0.3044 - smape: 0.5013 - val_ia: 0.7204 - val_loss: 0.1189 - val_mae: 0.2690 - val_rmse: 0.3267 - val_smape: 0.6173

Epoch 89/128

574/574 - 4s - 7ms/step - ia: 0.8556 - loss: 0.0917 - mae: 0.2303 - rmse: 0.3007 - smape: 0.4988 - val_ia: 0.7233 - val_loss: 0.1165 - val_mae: 0.2657 - val_rmse: 0.3235 - val_smape: 0.6118

Epoch 90/128

574/574 - 4s - 7ms/step - ia: 0.8550 - loss: 0.0924 - mae: 0.2308 - rmse: 0.3022 - smape: 0.4960 - val_ia: 0.7253 - val_loss: 0.1148 - val_mae: 0.2635 - val_rmse: 0.3212 - val_smape: 0.6077

Epoch 91/128

574/574 - 5s - 9ms/step - ia: 0.8563 - loss: 0.0911 - mae: 0.2288 - rmse: 0.2997 - smape: 0.4957 - val_ia: 0.7275 - val_loss: 0.1130 - val_mae: 0.2611 - val_rmse: 0.3189 - val_smape: 0.6033

Epoch 92/128

574/574 - 5s - 9ms/step - ia: 0.8577 - loss: 0.0897 - mae: 0.2271 - rmse: 0.2973 - smape: 0.4925 - val_ia: 0.7294 - val_loss: 0.1115 - val_mae: 0.2587 - val_rmse: 0.3167 - val_smape: 0.5992

Epoch 93/128

574/574 - 4s - 8ms/step - ia: 0.8580 - loss: 0.0889 - mae: 0.2265 - rmse: 0.2960 - smape: 0.4923 - val_ia: 0.7314 - val_loss: 0.1099 - val_mae: 0.2565 - val_rmse: 0.3144 - val_smape: 0.5954

Epoch 94/128

574/574 - 4s - 7ms/step - ia: 0.8579 - loss: 0.0895 - mae: 0.2263 - rmse: 0.2973 - smape: 0.4898 - val_ia: 0.7340 - val_loss: 0.1079 - val_mae: 0.2538 - val_rmse: 0.3116 - val_smape: 0.5905

Epoch 95/128

574/574 - 5s - 9ms/step - ia: 0.8587 - loss: 0.0880 - mae: 0.2248 - rmse: 0.2947 - smape: 0.4860 - val_ia: 0.7362 - val_loss: 0.1061 - val_mae: 0.2514 - val_rmse: 0.3091 - val_smape: 0.5862

Epoch 96/128

574/574 - 4s - 7ms/step - ia: 0.8596 - loss: 0.0876 - mae: 0.2243 - rmse: 0.2939 - smape: 0.4864 - val_ia: 0.7383 - val_loss: 0.1045 - val_mae: 0.2491 - val_rmse: 0.3069 - val_smape: 0.5818

Epoch 97/128

574/574 - 4s - 8ms/step - ia: 0.8599 - loss: 0.0868 - mae: 0.2237 - rmse: 0.2925 - smape: 0.4854 - val_ia: 0.7403 - val_loss: 0.1030 - val_mae: 0.2468 - val_rmse: 0.3047 - val_smape: 0.5773

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 10s - 34ms/step - ia: 0.2397 - loss: 1.1698 - mae: 0.8922 - rmse: 1.0805 - smape: 1.5127 - val_ia: 0.2125 - val_loss: 0.8727 - val_mae: 0.7780 - val_rmse: 0.9269 - val_smape: 1.8035

Epoch 2/128

287/287 - 5s - 17ms/step - ia: 0.2383 - loss: 1.1447 - mae: 0.8826 - rmse: 1.0685 - smape: 1.5214 - val_ia: 0.2181 - val_loss: 0.8533 - val_mae: 0.7691 - val_rmse: 0.9172 - val_smape: 1.8982

Epoch 3/128

287/287 - 5s - 17ms/step - ia: 0.2393 - loss: 1.1367 - mae: 0.8791 - rmse: 1.0648 - smape: 1.5139 - val_ia: 0.2226 - val_loss: 0.8412 - val_mae: 0.7634 - val_rmse: 0.9109 - val_smape: 1.9386

Epoch 4/128

287/287 - 5s - 18ms/step - ia: 0.2387 - loss: 1.1194 - mae: 0.8738 - rmse: 1.0566 - smape: 1.5169 - val_ia: 0.2267 - val_loss: 0.8321 - val_mae: 0.7590 - val_rmse: 0.9060 - val_smape: 1.9191

Epoch 5/128

287/287 - 5s - 18ms/step - ia: 0.2405 - loss: 1.1078 - mae: 0.8684 - rmse: 1.0510 - smape: 1.5138 - val_ia: 0.2309 - val_loss: 0.8230 - val_mae: 0.7548 - val_rmse: 0.9011 - val_smape: 1.8951

Epoch 6/128

287/287 - 5s - 19ms/step - ia: 0.2461 - loss: 1.0914 - mae: 0.8607 - rmse: 1.0429 - smape: 1.5058 - val_ia: 0.2343 - val_loss: 0.8158 - val_mae: 0.7515 - val_rmse: 0.8970 - val_smape: 1.8775

Epoch 7/128

287/287 - 6s - 21ms/step - ia: 0.2450 - loss: 1.0730 - mae: 0.8563 - rmse: 1.0347 - smape: 1.5099 - val_ia: 0.2404 - val_loss: 0.8037 - val_mae: 0.7456 - val_rmse: 0.8905 - val_smape: 1.8462

Epoch 8/128

287/287 - 5s - 17ms/step - ia: 0.2504 - loss: 1.0546 - mae: 0.8479 - rmse: 1.0257 - smape: 1.5007 - val_ia: 0.2450 - val_loss: 0.7944 - val_mae: 0.7414 - val_rmse: 0.8852 - val_smape: 1.8271

Epoch 9/128

287/287 - 5s - 18ms/step - ia: 0.2546 - loss: 1.0424 - mae: 0.8420 - rmse: 1.0195 - smape: 1.4931 - val_ia: 0.2506 - val_loss: 0.7834 - val_mae: 0.7362 - val_rmse: 0.8791 - val_smape: 1.8005

Epoch 10/128

287/287 - 5s - 17ms/step - ia: 0.2610 - loss: 1.0202 - mae: 0.8333 - rmse: 1.0087 - smape: 1.4871 - val_ia: 0.2582 - val_loss: 0.7693 - val_mae: 0.7293 - val_rmse: 0.8711 - val_smape: 1.7690

Epoch 11/128

287/287 - 5s - 17ms/step - ia: 0.2696 - loss: 0.9961 - mae: 0.8232 - rmse: 0.9966 - smape: 1.4757 - val_ia: 0.2660 - val_loss: 0.7548 - val_mae: 0.7222 - val_rmse: 0.8628 - val_smape: 1.7365

Epoch 12/128

287/287 - 5s - 17ms/step - ia: 0.2739 - loss: 0.9835 - mae: 0.8179 - rmse: 0.9902 - smape: 1.4677 - val_ia: 0.2736 - val_loss: 0.7406 - val_mae: 0.7154 - val_rmse: 0.8546 - val_smape: 1.7037

Epoch 13/128

287/287 - 5s - 17ms/step - ia: 0.2825 - loss: 0.9594 - mae: 0.8090 - rmse: 0.9783 - smape: 1.4576 - val_ia: 0.2844 - val_loss: 0.7212 - val_mae: 0.7056 - val_rmse: 0.8434 - val_smape: 1.6646

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.2946 - loss: 0.9297 - mae: 0.7965 - rmse: 0.9631 - smape: 1.4403 - val_ia: 0.2949 - val_loss: 0.7027 - val_mae: 0.6964 - val_rmse: 0.8324 - val_smape: 1.6248

Epoch 15/128

287/287 - 7s - 25ms/step - ia: 0.3085 - loss: 0.9000 - mae: 0.7820 - rmse: 0.9471 - smape: 1.4210 - val_ia: 0.3077 - val_loss: 0.6808 - val_mae: 0.6853 - val_rmse: 0.8193 - val_smape: 1.5804

Epoch 16/128

287/287 - 6s - 21ms/step - ia: 0.3185 - loss: 0.8847 - mae: 0.7749 - rmse: 0.9392 - smape: 1.4066 - val_ia: 0.3220 - val_loss: 0.6572 - val_mae: 0.6730 - val_rmse: 0.8049 - val_smape: 1.5327

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 0.3391 - loss: 0.8450 - mae: 0.7567 - rmse: 0.9177 - smape: 1.3802 - val_ia: 0.3383 - val_loss: 0.6311 - val_mae: 0.6592 - val_rmse: 0.7887 - val_smape: 1.4819

Epoch 18/128

287/287 - 5s - 17ms/step - ia: 0.3568 - loss: 0.8132 - mae: 0.7423 - rmse: 0.9005 - smape: 1.3505 - val_ia: 0.3572 - val_loss: 0.6016 - val_mae: 0.6430 - val_rmse: 0.7700 - val_smape: 1.4275

Epoch 19/128

287/287 - 6s - 22ms/step - ia: 0.3752 - loss: 0.7802 - mae: 0.7260 - rmse: 0.8819 - smape: 1.3266 - val_ia: 0.3779 - val_loss: 0.5709 - val_mae: 0.6259 - val_rmse: 0.7499 - val_smape: 1.3694

Epoch 20/128

287/287 - 6s - 21ms/step - ia: 0.3987 - loss: 0.7436 - mae: 0.7063 - rmse: 0.8611 - smape: 1.2917 - val_ia: 0.4014 - val_loss: 0.5371 - val_mae: 0.6065 - val_rmse: 0.7273 - val_smape: 1.3082

Epoch 21/128

287/287 - 5s - 17ms/step - ia: 0.4246 - loss: 0.7023 - mae: 0.6863 - rmse: 0.8365 - smape: 1.2555 - val_ia: 0.4276 - val_loss: 0.5010 - val_mae: 0.5850 - val_rmse: 0.7023 - val_smape: 1.2449

Epoch 22/128

287/287 - 5s - 16ms/step - ia: 0.4519 - loss: 0.6601 - mae: 0.6642 - rmse: 0.8113 - smape: 1.2188 - val_ia: 0.4565 - val_loss: 0.4629 - val_mae: 0.5612 - val_rmse: 0.6749 - val_smape: 1.1806

Epoch 23/128

287/287 - 5s - 16ms/step - ia: 0.4818 - loss: 0.6189 - mae: 0.6412 - rmse: 0.7854 - smape: 1.1751 - val_ia: 0.4876 - val_loss: 0.4237 - val_mae: 0.5356 - val_rmse: 0.6456 - val_smape: 1.1163

Epoch 24/128

287/287 - 5s - 16ms/step - ia: 0.5130 - loss: 0.5745 - mae: 0.6169 - rmse: 0.7567 - smape: 1.1322 - val_ia: 0.5197 - val_loss: 0.3855 - val_mae: 0.5096 - val_rmse: 0.6156 - val_smape: 1.0531

Epoch 25/128

287/287 - 5s - 19ms/step - ia: 0.5435 - loss: 0.5319 - mae: 0.5915 - rmse: 0.7280 - smape: 1.0896 - val_ia: 0.5540 - val_loss: 0.3476 - val_mae: 0.4817 - val_rmse: 0.5843 - val_smape: 0.9932

Epoch 26/128

287/287 - 5s - 18ms/step - ia: 0.5702 - loss: 0.4939 - mae: 0.5694 - rmse: 0.7016 - smape: 1.0468 - val_ia: 0.5879 - val_loss: 0.3126 - val_mae: 0.4550 - val_rmse: 0.5539 - val_smape: 0.9356

Epoch 27/128

287/287 - 5s - 16ms/step - ia: 0.5979 - loss: 0.4590 - mae: 0.5466 - rmse: 0.6762 - smape: 1.0065 - val_ia: 0.6211 - val_loss: 0.2806 - val_mae: 0.4285 - val_rmse: 0.5246 - val_smape: 0.8841

Epoch 28/128

287/287 - 5s - 17ms/step - ia: 0.6236 - loss: 0.4250 - mae: 0.5245 - rmse: 0.6508 - smape: 0.9689 - val_ia: 0.6524 - val_loss: 0.2528 - val_mae: 0.4035 - val_rmse: 0.4978 - val_smape: 0.8390

Epoch 29/128

287/287 - 5s - 18ms/step - ia: 0.6441 - loss: 0.4003 - mae: 0.5081 - rmse: 0.6317 - smape: 0.9343 - val_ia: 0.6787 - val_loss: 0.2305 - val_mae: 0.3824 - val_rmse: 0.4751 - val_smape: 0.8012

Epoch 30/128

287/287 - 5s - 17ms/step - ia: 0.6613 - loss: 0.3797 - mae: 0.4950 - rmse: 0.6149 - smape: 0.9116 - val_ia: 0.6996 - val_loss: 0.2134 - val_mae: 0.3655 - val_rmse: 0.4571 - val_smape: 0.7715

Epoch 31/128

287/287 - 5s - 19ms/step - ia: 0.6760 - loss: 0.3605 - mae: 0.4824 - rmse: 0.5995 - smape: 0.8895 - val_ia: 0.7168 - val_loss: 0.2006 - val_mae: 0.3513 - val_rmse: 0.4431 - val_smape: 0.7517

Epoch 32/128

287/287 - 5s - 17ms/step - ia: 0.6851 - loss: 0.3520 - mae: 0.4743 - rmse: 0.5920 - smape: 0.8723 - val_ia: 0.7287 - val_loss: 0.1912 - val_mae: 0.3423 - val_rmse: 0.4327 - val_smape: 0.7353

Epoch 33/128

287/287 - 5s - 16ms/step - ia: 0.6963 - loss: 0.3374 - mae: 0.4644 - rmse: 0.5799 - smape: 0.8512 - val_ia: 0.7367 - val_loss: 0.1849 - val_mae: 0.3366 - val_rmse: 0.4256 - val_smape: 0.7248

Epoch 34/128

287/287 - 6s - 20ms/step - ia: 0.7011 - loss: 0.3322 - mae: 0.4608 - rmse: 0.5752 - smape: 0.8454 - val_ia: 0.7422 - val_loss: 0.1807 - val_mae: 0.3331 - val_rmse: 0.4208 - val_smape: 0.7168

Epoch 35/128

287/287 - 5s - 17ms/step - ia: 0.7079 - loss: 0.3240 - mae: 0.4553 - rmse: 0.5683 - smape: 0.8345 - val_ia: 0.7451 - val_loss: 0.1787 - val_mae: 0.3316 - val_rmse: 0.4185 - val_smape: 0.7156

Epoch 36/128

287/287 - 5s - 16ms/step - ia: 0.7130 - loss: 0.3152 - mae: 0.4486 - rmse: 0.5603 - smape: 0.8235 - val_ia: 0.7476 - val_loss: 0.1769 - val_mae: 0.3304 - val_rmse: 0.4165 - val_smape: 0.7104

Epoch 37/128

287/287 - 5s - 16ms/step - ia: 0.7181 - loss: 0.3044 - mae: 0.4415 - rmse: 0.5506 - smape: 0.8151 - val_ia: 0.7500 - val_loss: 0.1755 - val_mae: 0.3294 - val_rmse: 0.4148 - val_smape: 0.7023

Epoch 38/128

287/287 - 5s - 17ms/step - ia: 0.7216 - loss: 0.3001 - mae: 0.4379 - rmse: 0.5468 - smape: 0.8075 - val_ia: 0.7516 - val_loss: 0.1744 - val_mae: 0.3288 - val_rmse: 0.4137 - val_smape: 0.7022

Epoch 39/128

287/287 - 5s - 17ms/step - ia: 0.7245 - loss: 0.2954 - mae: 0.4334 - rmse: 0.5427 - smape: 0.8012 - val_ia: 0.7527 - val_loss: 0.1737 - val_mae: 0.3287 - val_rmse: 0.4129 - val_smape: 0.7035

Epoch 40/128

287/287 - 5s - 17ms/step - ia: 0.7272 - loss: 0.2901 - mae: 0.4304 - rmse: 0.5375 - smape: 0.7992 - val_ia: 0.7538 - val_loss: 0.1732 - val_mae: 0.3284 - val_rmse: 0.4124 - val_smape: 0.7001

Epoch 41/128

287/287 - 5s - 16ms/step - ia: 0.7290 - loss: 0.2873 - mae: 0.4282 - rmse: 0.5351 - smape: 0.7950 - val_ia: 0.7545 - val_loss: 0.1729 - val_mae: 0.3282 - val_rmse: 0.4121 - val_smape: 0.6981

Epoch 42/128

287/287 - 5s - 16ms/step - ia: 0.7326 - loss: 0.2802 - mae: 0.4225 - rmse: 0.5284 - smape: 0.7862 - val_ia: 0.7553 - val_loss: 0.1725 - val_mae: 0.3281 - val_rmse: 0.4117 - val_smape: 0.6974

Epoch 43/128

287/287 - 5s - 17ms/step - ia: 0.7352 - loss: 0.2765 - mae: 0.4188 - rmse: 0.5248 - smape: 0.7821 - val_ia: 0.7561 - val_loss: 0.1722 - val_mae: 0.3280 - val_rmse: 0.4114 - val_smape: 0.6963

Epoch 44/128

287/287 - 5s - 18ms/step - ia: 0.7394 - loss: 0.2680 - mae: 0.4131 - rmse: 0.5168 - smape: 0.7764 - val_ia: 0.7567 - val_loss: 0.1720 - val_mae: 0.3279 - val_rmse: 0.4112 - val_smape: 0.6950

Epoch 45/128

287/287 - 5s - 17ms/step - ia: 0.7406 - loss: 0.2655 - mae: 0.4105 - rmse: 0.5140 - smape: 0.7687 - val_ia: 0.7575 - val_loss: 0.1719 - val_mae: 0.3276 - val_rmse: 0.4109 - val_smape: 0.6927

Epoch 46/128

287/287 - 5s - 16ms/step - ia: 0.7427 - loss: 0.2638 - mae: 0.4079 - rmse: 0.5127 - smape: 0.7660 - val_ia: 0.7583 - val_loss: 0.1717 - val_mae: 0.3274 - val_rmse: 0.4107 - val_smape: 0.6913

Epoch 47/128

287/287 - 5s - 17ms/step - ia: 0.7448 - loss: 0.2593 - mae: 0.4049 - rmse: 0.5081 - smape: 0.7627 - val_ia: 0.7589 - val_loss: 0.1712 - val_mae: 0.3274 - val_rmse: 0.4103 - val_smape: 0.6915

Epoch 48/128

287/287 - 4s - 16ms/step - ia: 0.7479 - loss: 0.2535 - mae: 0.4000 - rmse: 0.5025 - smape: 0.7574 - val_ia: 0.7596 - val_loss: 0.1712 - val_mae: 0.3271 - val_rmse: 0.4101 - val_smape: 0.6895

Epoch 49/128

287/287 - 5s - 18ms/step - ia: 0.7492 - loss: 0.2522 - mae: 0.3994 - rmse: 0.5011 - smape: 0.7550 - val_ia: 0.7598 - val_loss: 0.1711 - val_mae: 0.3270 - val_rmse: 0.4100 - val_smape: 0.6892

Epoch 50/128

287/287 - 10s - 35ms/step - ia: 0.7503 - loss: 0.2475 - mae: 0.3963 - rmse: 0.4964 - smape: 0.7506 - val_ia: 0.7605 - val_loss: 0.1708 - val_mae: 0.3269 - val_rmse: 0.4096 - val_smape: 0.6885

Epoch 51/128

287/287 - 5s - 17ms/step - ia: 0.7515 - loss: 0.2455 - mae: 0.3940 - rmse: 0.4946 - smape: 0.7500 - val_ia: 0.7611 - val_loss: 0.1707 - val_mae: 0.3268 - val_rmse: 0.4094 - val_smape: 0.6871

Epoch 52/128

287/287 - 5s - 18ms/step - ia: 0.7556 - loss: 0.2396 - mae: 0.3889 - rmse: 0.4885 - smape: 0.7396 - val_ia: 0.7617 - val_loss: 0.1709 - val_mae: 0.3266 - val_rmse: 0.4093 - val_smape: 0.6853

Epoch 53/128

287/287 - 5s - 17ms/step - ia: 0.7558 - loss: 0.2378 - mae: 0.3879 - rmse: 0.4865 - smape: 0.7377 - val_ia: 0.7623 - val_loss: 0.1703 - val_mae: 0.3264 - val_rmse: 0.4088 - val_smape: 0.6852

Epoch 54/128

287/287 - 5s - 17ms/step - ia: 0.7596 - loss: 0.2332 - mae: 0.3826 - rmse: 0.4819 - smape: 0.7334 - val_ia: 0.7627 - val_loss: 0.1697 - val_mae: 0.3262 - val_rmse: 0.4083 - val_smape: 0.6852

Epoch 55/128

287/287 - 5s - 16ms/step - ia: 0.7583 - loss: 0.2333 - mae: 0.3842 - rmse: 0.4821 - smape: 0.7337 - val_ia: 0.7633 - val_loss: 0.1698 - val_mae: 0.3259 - val_rmse: 0.4081 - val_smape: 0.6830

Epoch 56/128

287/287 - 5s - 16ms/step - ia: 0.7613 - loss: 0.2299 - mae: 0.3804 - rmse: 0.4786 - smape: 0.7289 - val_ia: 0.7637 - val_loss: 0.1695 - val_mae: 0.3256 - val_rmse: 0.4077 - val_smape: 0.6824

Epoch 57/128

287/287 - 5s - 17ms/step - ia: 0.7620 - loss: 0.2279 - mae: 0.3786 - rmse: 0.4764 - smape: 0.7256 - val_ia: 0.7641 - val_loss: 0.1689 - val_mae: 0.3253 - val_rmse: 0.4071 - val_smape: 0.6822

Epoch 58/128

287/287 - 5s - 17ms/step - ia: 0.7641 - loss: 0.2244 - mae: 0.3755 - rmse: 0.4727 - smape: 0.7207 - val_ia: 0.7647 - val_loss: 0.1686 - val_mae: 0.3249 - val_rmse: 0.4066 - val_smape: 0.6811

Epoch 59/128

287/287 - 5s - 16ms/step - ia: 0.7649 - loss: 0.2216 - mae: 0.3740 - rmse: 0.4698 - smape: 0.7207 - val_ia: 0.7652 - val_loss: 0.1691 - val_mae: 0.3247 - val_rmse: 0.4066 - val_smape: 0.6789

Epoch 60/128

287/287 - 5s - 18ms/step - ia: 0.7684 - loss: 0.2180 - mae: 0.3687 - rmse: 0.4660 - smape: 0.7120 - val_ia: 0.7659 - val_loss: 0.1680 - val_mae: 0.3242 - val_rmse: 0.4057 - val_smape: 0.6787

Epoch 61/128

287/287 - 5s - 17ms/step - ia: 0.7680 - loss: 0.2173 - mae: 0.3693 - rmse: 0.4651 - smape: 0.7154 - val_ia: 0.7665 - val_loss: 0.1681 - val_mae: 0.3240 - val_rmse: 0.4054 - val_smape: 0.6771

Epoch 62/128

287/287 - 5s - 17ms/step - ia: 0.7706 - loss: 0.2146 - mae: 0.3657 - rmse: 0.4625 - smape: 0.7055 - val_ia: 0.7670 - val_loss: 0.1677 - val_mae: 0.3236 - val_rmse: 0.4048 - val_smape: 0.6762

Epoch 63/128

287/287 - 5s - 16ms/step - ia: 0.7718 - loss: 0.2129 - mae: 0.3638 - rmse: 0.4604 - smape: 0.7039 - val_ia: 0.7675 - val_loss: 0.1668 - val_mae: 0.3230 - val_rmse: 0.4039 - val_smape: 0.6758

Epoch 64/128

287/287 - 4s - 15ms/step - ia: 0.7741 - loss: 0.2076 - mae: 0.3600 - rmse: 0.4545 - smape: 0.7009 - val_ia: 0.7680 - val_loss: 0.1671 - val_mae: 0.3228 - val_rmse: 0.4038 - val_smape: 0.6740

Epoch 65/128

287/287 - 4s - 14ms/step - ia: 0.7734 - loss: 0.2089 - mae: 0.3613 - rmse: 0.4560 - smape: 0.7033 - val_ia: 0.7685 - val_loss: 0.1669 - val_mae: 0.3225 - val_rmse: 0.4033 - val_smape: 0.6730

Epoch 66/128

287/287 - 4s - 13ms/step - ia: 0.7743 - loss: 0.2055 - mae: 0.3598 - rmse: 0.4524 - smape: 0.7009 - val_ia: 0.7692 - val_loss: 0.1658 - val_mae: 0.3217 - val_rmse: 0.4022 - val_smape: 0.6725

Epoch 67/128

287/287 - 4s - 13ms/step - ia: 0.7769 - loss: 0.2041 - mae: 0.3565 - rmse: 0.4508 - smape: 0.6920 - val_ia: 0.7696 - val_loss: 0.1653 - val_mae: 0.3211 - val_rmse: 0.4015 - val_smape: 0.6715

Epoch 68/128

287/287 - 5s - 17ms/step - ia: 0.7786 - loss: 0.2002 - mae: 0.3535 - rmse: 0.4464 - smape: 0.6899 - val_ia: 0.7701 - val_loss: 0.1654 - val_mae: 0.3210 - val_rmse: 0.4011 - val_smape: 0.6705

Epoch 69/128

287/287 - 5s - 18ms/step - ia: 0.7804 - loss: 0.1976 - mae: 0.3506 - rmse: 0.4435 - smape: 0.6863 - val_ia: 0.7707 - val_loss: 0.1646 - val_mae: 0.3203 - val_rmse: 0.4002 - val_smape: 0.6698

Epoch 70/128

287/287 - 5s - 19ms/step - ia: 0.7791 - loss: 0.1989 - mae: 0.3527 - rmse: 0.4450 - smape: 0.6860 - val_ia: 0.7712 - val_loss: 0.1638 - val_mae: 0.3196 - val_rmse: 0.3993 - val_smape: 0.6689

Epoch 71/128

287/287 - 5s - 18ms/step - ia: 0.7812 - loss: 0.1958 - mae: 0.3491 - rmse: 0.4415 - smape: 0.6847 - val_ia: 0.7717 - val_loss: 0.1638 - val_mae: 0.3195 - val_rmse: 0.3989 - val_smape: 0.6678

Epoch 72/128

287/287 - 6s - 20ms/step - ia: 0.7833 - loss: 0.1933 - mae: 0.3458 - rmse: 0.4387 - smape: 0.6775 - val_ia: 0.7725 - val_loss: 0.1626 - val_mae: 0.3186 - val_rmse: 0.3977 - val_smape: 0.6672

Epoch 73/128

287/287 - 5s - 18ms/step - ia: 0.7833 - loss: 0.1931 - mae: 0.3461 - rmse: 0.4384 - smape: 0.6790 - val_ia: 0.7725 - val_loss: 0.1632 - val_mae: 0.3188 - val_rmse: 0.3977 - val_smape: 0.6663

Epoch 74/128

287/287 - 6s - 21ms/step - ia: 0.7853 - loss: 0.1896 - mae: 0.3435 - rmse: 0.4345 - smape: 0.6764 - val_ia: 0.7732 - val_loss: 0.1617 - val_mae: 0.3176 - val_rmse: 0.3963 - val_smape: 0.6656

Epoch 75/128

287/287 - 9s - 32ms/step - ia: 0.7890 - loss: 0.1846 - mae: 0.3374 - rmse: 0.4285 - smape: 0.6670 - val_ia: 0.7738 - val_loss: 0.1613 - val_mae: 0.3172 - val_rmse: 0.3955 - val_smape: 0.6647

Epoch 76/128

287/287 - 4s - 16ms/step - ia: 0.7874 - loss: 0.1867 - mae: 0.3399 - rmse: 0.4312 - smape: 0.6691 - val_ia: 0.7741 - val_loss: 0.1614 - val_mae: 0.3170 - val_rmse: 0.3952 - val_smape: 0.6639

Epoch 77/128

287/287 - 5s - 17ms/step - ia: 0.7875 - loss: 0.1850 - mae: 0.3398 - rmse: 0.4293 - smape: 0.6728 - val_ia: 0.7748 - val_loss: 0.1599 - val_mae: 0.3159 - val_rmse: 0.3937 - val_smape: 0.6631

Epoch 78/128

287/287 - 5s - 17ms/step - ia: 0.7904 - loss: 0.1813 - mae: 0.3347 - rmse: 0.4250 - smape: 0.6646 - val_ia: 0.7754 - val_loss: 0.1598 - val_mae: 0.3156 - val_rmse: 0.3932 - val_smape: 0.6620

Epoch 79/128

287/287 - 5s - 16ms/step - ia: 0.7912 - loss: 0.1812 - mae: 0.3349 - rmse: 0.4246 - smape: 0.6640 - val_ia: 0.7761 - val_loss: 0.1579 - val_mae: 0.3141 - val_rmse: 0.3913 - val_smape: 0.6614

Epoch 80/128

287/287 - 5s - 16ms/step - ia: 0.7899 - loss: 0.1823 - mae: 0.3360 - rmse: 0.4258 - smape: 0.6649 - val_ia: 0.7759 - val_loss: 0.1590 - val_mae: 0.3146 - val_rmse: 0.3916 - val_smape: 0.6606

Epoch 81/128

287/287 - 5s - 16ms/step - ia: 0.7910 - loss: 0.1807 - mae: 0.3340 - rmse: 0.4241 - smape: 0.6597 - val_ia: 0.7769 - val_loss: 0.1576 - val_mae: 0.3135 - val_rmse: 0.3902 - val_smape: 0.6595

Epoch 82/128

287/287 - 4s - 16ms/step - ia: 0.7933 - loss: 0.1773 - mae: 0.3306 - rmse: 0.4201 - smape: 0.6581 - val_ia: 0.7772 - val_loss: 0.1579 - val_mae: 0.3136 - val_rmse: 0.3899 - val_smape: 0.6587

Epoch 83/128

287/287 - 4s - 16ms/step - ia: 0.7943 - loss: 0.1761 - mae: 0.3293 - rmse: 0.4187 - smape: 0.6554 - val_ia: 0.7778 - val_loss: 0.1569 - val_mae: 0.3127 - val_rmse: 0.3887 - val_smape: 0.6578

Epoch 84/128

287/287 - 4s - 15ms/step - ia: 0.7954 - loss: 0.1738 - mae: 0.3276 - rmse: 0.4157 - smape: 0.6525 - val_ia: 0.7780 - val_loss: 0.1572 - val_mae: 0.3128 - val_rmse: 0.3885 - val_smape: 0.6573

Epoch 85/128

287/287 - 4s - 16ms/step - ia: 0.7951 - loss: 0.1738 - mae: 0.3281 - rmse: 0.4158 - smape: 0.6493 - val_ia: 0.7786 - val_loss: 0.1561 - val_mae: 0.3118 - val_rmse: 0.3872 - val_smape: 0.6564

Epoch 86/128

287/287 - 5s - 16ms/step - ia: 0.7984 - loss: 0.1693 - mae: 0.3234 - rmse: 0.4105 - smape: 0.6454 - val_ia: 0.7791 - val_loss: 0.1552 - val_mae: 0.3109 - val_rmse: 0.3861 - val_smape: 0.6554

Epoch 87/128

287/287 - 4s - 16ms/step - ia: 0.7965 - loss: 0.1709 - mae: 0.3255 - rmse: 0.4124 - smape: 0.6513 - val_ia: 0.7797 - val_loss: 0.1542 - val_mae: 0.3100 - val_rmse: 0.3849 - val_smape: 0.6544

Epoch 88/128

287/287 - 5s - 16ms/step - ia: 0.7969 - loss: 0.1711 - mae: 0.3250 - rmse: 0.4126 - smape: 0.6506 - val_ia: 0.7805 - val_loss: 0.1531 - val_mae: 0.3091 - val_rmse: 0.3836 - val_smape: 0.6533

Epoch 89/128

287/287 - 5s - 16ms/step - ia: 0.7996 - loss: 0.1675 - mae: 0.3209 - rmse: 0.4085 - smape: 0.6417 - val_ia: 0.7806 - val_loss: 0.1537 - val_mae: 0.3094 - val_rmse: 0.3836 - val_smape: 0.6530

Epoch 90/128

287/287 - 5s - 17ms/step - ia: 0.8001 - loss: 0.1665 - mae: 0.3207 - rmse: 0.4072 - smape: 0.6419 - val_ia: 0.7816 - val_loss: 0.1519 - val_mae: 0.3079 - val_rmse: 0.3818 - val_smape: 0.6516

Epoch 91/128

287/287 - 5s - 18ms/step - ia: 0.8002 - loss: 0.1654 - mae: 0.3197 - rmse: 0.4058 - smape: 0.6416 - val_ia: 0.7818 - val_loss: 0.1520 - val_mae: 0.3078 - val_rmse: 0.3814 - val_smape: 0.6510

Epoch 92/128

287/287 - 5s - 16ms/step - ia: 0.8016 - loss: 0.1640 - mae: 0.3182 - rmse: 0.4041 - smape: 0.6372 - val_ia: 0.7820 - val_loss: 0.1516 - val_mae: 0.3074 - val_rmse: 0.3806 - val_smape: 0.6503

Epoch 93/128

287/287 - 4s - 16ms/step - ia: 0.8015 - loss: 0.1642 - mae: 0.3183 - rmse: 0.4043 - smape: 0.6389 - val_ia: 0.7829 - val_loss: 0.1496 - val_mae: 0.3056 - val_rmse: 0.3786 - val_smape: 0.6490

Epoch 94/128

287/287 - 4s - 16ms/step - ia: 0.8039 - loss: 0.1612 - mae: 0.3144 - rmse: 0.4004 - smape: 0.6321 - val_ia: 0.7834 - val_loss: 0.1497 - val_mae: 0.3056 - val_rmse: 0.3782 - val_smape: 0.6482

Epoch 95/128

287/287 - 4s - 15ms/step - ia: 0.8039 - loss: 0.1594 - mae: 0.3137 - rmse: 0.3985 - smape: 0.6325 - val_ia: 0.7837 - val_loss: 0.1500 - val_mae: 0.3057 - val_rmse: 0.3781 - val_smape: 0.6476

Epoch 96/128

287/287 - 5s - 18ms/step - ia: 0.8042 - loss: 0.1605 - mae: 0.3139 - rmse: 0.3997 - smape: 0.6314 - val_ia: 0.7850 - val_loss: 0.1476 - val_mae: 0.3036 - val_rmse: 0.3757 - val_smape: 0.6459

Epoch 97/128

287/287 - 5s - 19ms/step - ia: 0.8042 - loss: 0.1605 - mae: 0.3146 - rmse: 0.3998 - smape: 0.6313 - val_ia: 0.7848 - val_loss: 0.1482 - val_mae: 0.3039 - val_rmse: 0.3756 - val_smape: 0.6456

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 12s - 43ms/step - ia: 0.9096 - loss: 0.0475 - mae: 0.1451 - rmse: 0.1937 - smape: 0.3246 - val_ia: 0.9350 - val_loss: 0.0120 - val_mae: 0.0872 - val_rmse: 0.1056 - val_smape: 0.2376

Epoch 2/128

287/287 - 2s - 7ms/step - ia: 0.9387 - loss: 0.0191 - mae: 0.1004 - rmse: 0.1373 - smape: 0.2309 - val_ia: 0.9652 - val_loss: 0.0046 - val_mae: 0.0483 - val_rmse: 0.0667 - val_smape: 0.1409

Epoch 3/128

287/287 - 2s - 7ms/step - ia: 0.9425 - loss: 0.0172 - mae: 0.0944 - rmse: 0.1303 - smape: 0.2125 - val_ia: 0.9660 - val_loss: 0.0040 - val_mae: 0.0460 - val_rmse: 0.0617 - val_smape: 0.1464

Epoch 4/128

287/287 - 2s - 8ms/step - ia: 0.9436 - loss: 0.0169 - mae: 0.0925 - rmse: 0.1289 - smape: 0.2043 - val_ia: 0.9699 - val_loss: 0.0033 - val_mae: 0.0408 - val_rmse: 0.0569 - val_smape: 0.1203

Epoch 5/128

287/287 - 2s - 7ms/step - ia: 0.9443 - loss: 0.0165 - mae: 0.0914 - rmse: 0.1276 - smape: 0.2000 - val_ia: 0.9681 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0586 - val_smape: 0.1206

Epoch 6/128

287/287 - 2s - 7ms/step - ia: 0.9453 - loss: 0.0160 - mae: 0.0898 - rmse: 0.1254 - smape: 0.1958 - val_ia: 0.9683 - val_loss: 0.0035 - val_mae: 0.0434 - val_rmse: 0.0588 - val_smape: 0.1320

Epoch 7/128

287/287 - 2s - 8ms/step - ia: 0.9447 - loss: 0.0165 - mae: 0.0907 - rmse: 0.1273 - smape: 0.1955 - val_ia: 0.9650 - val_loss: 0.0041 - val_mae: 0.0474 - val_rmse: 0.0628 - val_smape: 0.1353

Epoch 8/128

287/287 - 2s - 8ms/step - ia: 0.9452 - loss: 0.0163 - mae: 0.0899 - rmse: 0.1265 - smape: 0.1942 - val_ia: 0.9669 - val_loss: 0.0038 - val_mae: 0.0445 - val_rmse: 0.0604 - val_smape: 0.1214

Epoch 9/128

287/287 - 2s - 7ms/step - ia: 0.9454 - loss: 0.0162 - mae: 0.0896 - rmse: 0.1263 - smape: 0.1943 - val_ia: 0.9596 - val_loss: 0.0053 - val_mae: 0.0539 - val_rmse: 0.0696 - val_smape: 0.1425

Epoch 10/128

287/287 - 3s - 11ms/step - ia: 0.9457 - loss: 0.0159 - mae: 0.0893 - rmse: 0.1252 - smape: 0.1923 - val_ia: 0.9546 - val_loss: 0.0062 - val_mae: 0.0607 - val_rmse: 0.0771 - val_smape: 0.1447

Epoch 11/128

287/287 - 2s - 8ms/step - ia: 0.9457 - loss: 0.0159 - mae: 0.0891 - rmse: 0.1253 - smape: 0.1918 - val_ia: 0.9718 - val_loss: 0.0030 - val_mae: 0.0387 - val_rmse: 0.0539 - val_smape: 0.1207

Epoch 12/128

287/287 - 3s - 10ms/step - ia: 0.9450 - loss: 0.0162 - mae: 0.0902 - rmse: 0.1264 - smape: 0.1940 - val_ia: 0.9728 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0516 - val_smape: 0.1174

Epoch 13/128

287/287 - 2s - 9ms/step - ia: 0.9462 - loss: 0.0156 - mae: 0.0883 - rmse: 0.1240 - smape: 0.1885 - val_ia: 0.9626 - val_loss: 0.0043 - val_mae: 0.0502 - val_rmse: 0.0638 - val_smape: 0.1477

Epoch 14/128

287/287 - 2s - 8ms/step - ia: 0.9462 - loss: 0.0157 - mae: 0.0882 - rmse: 0.1246 - smape: 0.1887 - val_ia: 0.9668 - val_loss: 0.0037 - val_mae: 0.0448 - val_rmse: 0.0594 - val_smape: 0.1346

Epoch 15/128

287/287 - 2s - 8ms/step - ia: 0.9460 - loss: 0.0158 - mae: 0.0886 - rmse: 0.1246 - smape: 0.1895 - val_ia: 0.9657 - val_loss: 0.0040 - val_mae: 0.0465 - val_rmse: 0.0623 - val_smape: 0.1306

Epoch 16/128

287/287 - 2s - 8ms/step - ia: 0.9464 - loss: 0.0155 - mae: 0.0879 - rmse: 0.1234 - smape: 0.1870 - val_ia: 0.9597 - val_loss: 0.0052 - val_mae: 0.0563 - val_rmse: 0.0717 - val_smape: 0.1405

Epoch 17/128

287/287 - 2s - 8ms/step - ia: 0.9460 - loss: 0.0158 - mae: 0.0886 - rmse: 0.1245 - smape: 0.1887 - val_ia: 0.9719 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0533 - val_smape: 0.1154

Epoch 18/128

287/287 - 2s - 8ms/step - ia: 0.9460 - loss: 0.0159 - mae: 0.0886 - rmse: 0.1250 - smape: 0.1886 - val_ia: 0.9703 - val_loss: 0.0032 - val_mae: 0.0407 - val_rmse: 0.0557 - val_smape: 0.1287

Epoch 19/128

287/287 - 3s - 9ms/step - ia: 0.9461 - loss: 0.0157 - mae: 0.0883 - rmse: 0.1244 - smape: 0.1889 - val_ia: 0.9639 - val_loss: 0.0044 - val_mae: 0.0487 - val_rmse: 0.0657 - val_smape: 0.1251

Epoch 20/128

287/287 - 2s - 8ms/step - ia: 0.9460 - loss: 0.0160 - mae: 0.0886 - rmse: 0.1254 - smape: 0.1872 - val_ia: 0.9555 - val_loss: 0.0064 - val_mae: 0.0592 - val_rmse: 0.0759 - val_smape: 0.1422

Epoch 21/128

287/287 - 2s - 9ms/step - ia: 0.9460 - loss: 0.0158 - mae: 0.0886 - rmse: 0.1246 - smape: 0.1885 - val_ia: 0.9667 - val_loss: 0.0039 - val_mae: 0.0452 - val_rmse: 0.0614 - val_smape: 0.1246

Epoch 22/128

287/287 - 3s - 9ms/step - ia: 0.9466 - loss: 0.0156 - mae: 0.0876 - rmse: 0.1238 - smape: 0.1866 - val_ia: 0.9584 - val_loss: 0.0052 - val_mae: 0.0554 - val_rmse: 0.0689 - val_smape: 0.1507

Epoch 23/128

287/287 - 3s - 9ms/step - ia: 0.9472 - loss: 0.0153 - mae: 0.0867 - rmse: 0.1225 - smape: 0.1862 - val_ia: 0.9640 - val_loss: 0.0040 - val_mae: 0.0483 - val_rmse: 0.0615 - val_smape: 0.1473

Epoch 24/128

287/287 - 2s - 8ms/step - ia: 0.9462 - loss: 0.0157 - mae: 0.0882 - rmse: 0.1244 - smape: 0.1872 - val_ia: 0.9602 - val_loss: 0.0049 - val_mae: 0.0534 - val_rmse: 0.0676 - val_smape: 0.1440

Epoch 25/128

287/287 - 2s - 8ms/step - ia: 0.9466 - loss: 0.0156 - mae: 0.0876 - rmse: 0.1238 - smape: 0.1850 - val_ia: 0.9583 - val_loss: 0.0053 - val_mae: 0.0558 - val_rmse: 0.0707 - val_smape: 0.1401

Epoch 26/128

287/287 - 3s - 9ms/step - ia: 0.9464 - loss: 0.0156 - mae: 0.0879 - rmse: 0.1239 - smape: 0.1852 - val_ia: 0.9716 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0530 - val_smape: 0.1199

Epoch 27/128

287/287 - 2s - 8ms/step - ia: 0.9470 - loss: 0.0155 - mae: 0.0871 - rmse: 0.1235 - smape: 0.1857 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0442 - val_rmse: 0.0586 - val_smape: 0.1248

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 47s 293ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 58%|█████▊    | 7/12 [2:59:12<1:25:45, 1029.04s/trial, best loss: 0.0019945538727369925]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 52s - 11ms/step - ia: 0.9108 - loss: 0.0346 - mae: 0.1302 - rmse: 0.1662 - smape: 0.2871 - val_ia: 0.5530 - val_loss: 0.0100 - val_mae: 0.0768 - val_rmse: 0.0855 - val_smape: 0.1879

Epoch 2/128

4586/4586 - 41s - 9ms/step - ia: 0.9321 - loss: 0.0191 - mae: 0.1005 - rmse: 0.1297 - smape: 0.2278 - val_ia: 0.4718 - val_loss: 0.0149 - val_mae: 0.1037 - val_rmse: 0.1109 - val_smape: 0.2836

Epoch 3/128

4586/4586 - 41s - 9ms/step - ia: 0.9350 - loss: 0.0176 - mae: 0.0962 - rmse: 0.1241 - smape: 0.2202 - val_ia: 0.6672 - val_loss: 0.0037 - val_mae: 0.0445 - val_rmse: 0.0539 - val_smape: 0.1288

Epoch 4/128

4586/4586 - 80s - 17ms/step - ia: 0.9366 - loss: 0.0165 - mae: 0.0931 - rmse: 0.1201 - smape: 0.2142 - val_ia: 0.6683 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0521 - val_smape: 0.1302

Epoch 5/128

4586/4586 - 43s - 9ms/step - ia: 0.9382 - loss: 0.0160 - mae: 0.0917 - rmse: 0.1182 - smape: 0.2139 - val_ia: 0.5503 - val_loss: 0.0098 - val_mae: 0.0772 - val_rmse: 0.0852 - val_smape: 0.1835

Epoch 6/128

4586/4586 - 36s - 8ms/step - ia: 0.9379 - loss: 0.0160 - mae: 0.0915 - rmse: 0.1183 - smape: 0.2106 - val_ia: 0.6447 - val_loss: 0.0042 - val_mae: 0.0485 - val_rmse: 0.0572 - val_smape: 0.1378

Epoch 7/128

4586/4586 - 38s - 8ms/step - ia: 0.9398 - loss: 0.0150 - mae: 0.0885 - rmse: 0.1144 - smape: 0.2080 - val_ia: 0.6213 - val_loss: 0.0053 - val_mae: 0.0557 - val_rmse: 0.0642 - val_smape: 0.1527

Epoch 8/128

4586/4586 - 39s - 8ms/step - ia: 0.9408 - loss: 0.0149 - mae: 0.0876 - rmse: 0.1137 - smape: 0.2037 - val_ia: 0.6120 - val_loss: 0.0070 - val_mae: 0.0618 - val_rmse: 0.0704 - val_smape: 0.1588

Epoch 9/128

4586/4586 - 41s - 9ms/step - ia: 0.9407 - loss: 0.0149 - mae: 0.0881 - rmse: 0.1139 - smape: 0.2044 - val_ia: 0.6576 - val_loss: 0.0039 - val_mae: 0.0473 - val_rmse: 0.0561 - val_smape: 0.1447

Epoch 10/128

4586/4586 - 41s - 9ms/step - ia: 0.9411 - loss: 0.0149 - mae: 0.0876 - rmse: 0.1136 - smape: 0.2039 - val_ia: 0.6301 - val_loss: 0.0055 - val_mae: 0.0553 - val_rmse: 0.0641 - val_smape: 0.1485

Epoch 11/128

4586/4586 - 40s - 9ms/step - ia: 0.9412 - loss: 0.0146 - mae: 0.0870 - rmse: 0.1128 - smape: 0.1999 - val_ia: 0.6227 - val_loss: 0.0056 - val_mae: 0.0562 - val_rmse: 0.0643 - val_smape: 0.1438

Epoch 12/128

4586/4586 - 41s - 9ms/step - ia: 0.9418 - loss: 0.0143 - mae: 0.0865 - rmse: 0.1118 - smape: 0.2005 - val_ia: 0.6649 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0551 - val_smape: 0.1257

Epoch 13/128

4586/4586 - 36s - 8ms/step - ia: 0.9428 - loss: 0.0140 - mae: 0.0850 - rmse: 0.1103 - smape: 0.1969 - val_ia: 0.6491 - val_loss: 0.0052 - val_mae: 0.0529 - val_rmse: 0.0614 - val_smape: 0.1466

Epoch 14/128

4586/4586 - 36s - 8ms/step - ia: 0.9426 - loss: 0.0139 - mae: 0.0848 - rmse: 0.1101 - smape: 0.1975 - val_ia: 0.5814 - val_loss: 0.0061 - val_mae: 0.0632 - val_rmse: 0.0714 - val_smape: 0.1686

Epoch 15/128

4586/4586 - 46s - 10ms/step - ia: 0.9428 - loss: 0.0140 - mae: 0.0845 - rmse: 0.1100 - smape: 0.1958 - val_ia: 0.6389 - val_loss: 0.0046 - val_mae: 0.0512 - val_rmse: 0.0594 - val_smape: 0.1644

Epoch 16/128

4586/4586 - 44s - 10ms/step - ia: 0.9429 - loss: 0.0140 - mae: 0.0847 - rmse: 0.1101 - smape: 0.1966 - val_ia: 0.6356 - val_loss: 0.0044 - val_mae: 0.0513 - val_rmse: 0.0599 - val_smape: 0.1612

Epoch 17/128

4586/4586 - 44s - 10ms/step - ia: 0.9436 - loss: 0.0136 - mae: 0.0838 - rmse: 0.1084 - smape: 0.1952 - val_ia: 0.6314 - val_loss: 0.0053 - val_mae: 0.0544 - val_rmse: 0.0630 - val_smape: 0.1639

Epoch 18/128

4586/4586 - 41s - 9ms/step - ia: 0.9438 - loss: 0.0135 - mae: 0.0834 - rmse: 0.1084 - smape: 0.1921 - val_ia: 0.6767 - val_loss: 0.0036 - val_mae: 0.0433 - val_rmse: 0.0517 - val_smape: 0.1308

Epoch 19/128

4586/4586 - 41s - 9ms/step - ia: 0.9438 - loss: 0.0136 - mae: 0.0833 - rmse: 0.1085 - smape: 0.1920 - val_ia: 0.5860 - val_loss: 0.0060 - val_mae: 0.0616 - val_rmse: 0.0697 - val_smape: 0.1589

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:41 999ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 67%|██████▋   | 8/12 [3:12:56<1:04:15, 963.99s/trial, best loss: 0.0019945538727369925]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 6s - 19ms/step - ia: 0.6110 - loss: 0.6617 - mae: 0.5676 - rmse: 0.7320 - smape: 0.9913 - val_ia: 0.7836 - val_loss: 0.1428 - val_mae: 0.2939 - val_rmse: 0.3725 - val_smape: 0.6341

Epoch 2/128

287/287 - 1s - 4ms/step - ia: 0.8090 - loss: 0.1545 - mae: 0.3000 - rmse: 0.3909 - smape: 0.6079 - val_ia: 0.8387 - val_loss: 0.0708 - val_mae: 0.2153 - val_rmse: 0.2594 - val_smape: 0.5332

Epoch 3/128

287/287 - 1s - 5ms/step - ia: 0.8427 - loss: 0.1092 - mae: 0.2502 - rmse: 0.3293 - smape: 0.5203 - val_ia: 0.8667 - val_loss: 0.0485 - val_mae: 0.1761 - val_rmse: 0.2134 - val_smape: 0.4601

Epoch 4/128

287/287 - 2s - 8ms/step - ia: 0.8590 - loss: 0.0918 - mae: 0.2254 - rmse: 0.3017 - smape: 0.4670 - val_ia: 0.8787 - val_loss: 0.0421 - val_mae: 0.1581 - val_rmse: 0.1991 - val_smape: 0.3982

Epoch 5/128

287/287 - 1s - 3ms/step - ia: 0.8683 - loss: 0.0816 - mae: 0.2105 - rmse: 0.2843 - smape: 0.4361 - val_ia: 0.8920 - val_loss: 0.0343 - val_mae: 0.1416 - val_rmse: 0.1792 - val_smape: 0.3627

Epoch 6/128

287/287 - 1s - 3ms/step - ia: 0.8764 - loss: 0.0739 - mae: 0.1978 - rmse: 0.2708 - smape: 0.4070 - val_ia: 0.9005 - val_loss: 0.0301 - val_mae: 0.1298 - val_rmse: 0.1684 - val_smape: 0.3215

Epoch 7/128

287/287 - 1s - 3ms/step - ia: 0.8806 - loss: 0.0698 - mae: 0.1912 - rmse: 0.2631 - smape: 0.3875 - val_ia: 0.9149 - val_loss: 0.0228 - val_mae: 0.1121 - val_rmse: 0.1470 - val_smape: 0.2871

Epoch 8/128

287/287 - 1s - 4ms/step - ia: 0.8832 - loss: 0.0681 - mae: 0.1870 - rmse: 0.2598 - smape: 0.3776 - val_ia: 0.9189 - val_loss: 0.0207 - val_mae: 0.1067 - val_rmse: 0.1402 - val_smape: 0.2752

Epoch 9/128

287/287 - 1s - 4ms/step - ia: 0.8851 - loss: 0.0663 - mae: 0.1842 - rmse: 0.2563 - smape: 0.3695 - val_ia: 0.9129 - val_loss: 0.0225 - val_mae: 0.1134 - val_rmse: 0.1468 - val_smape: 0.2706

Epoch 10/128

287/287 - 1s - 5ms/step - ia: 0.8879 - loss: 0.0640 - mae: 0.1799 - rmse: 0.2517 - smape: 0.3553 - val_ia: 0.9242 - val_loss: 0.0177 - val_mae: 0.0996 - val_rmse: 0.1302 - val_smape: 0.2571

Epoch 11/128

287/287 - 1s - 4ms/step - ia: 0.8885 - loss: 0.0635 - mae: 0.1786 - rmse: 0.2507 - smape: 0.3494 - val_ia: 0.9265 - val_loss: 0.0166 - val_mae: 0.0966 - val_rmse: 0.1261 - val_smape: 0.2385

Epoch 12/128

287/287 - 1s - 4ms/step - ia: 0.8902 - loss: 0.0623 - mae: 0.1760 - rmse: 0.2483 - smape: 0.3434 - val_ia: 0.9349 - val_loss: 0.0136 - val_mae: 0.0862 - val_rmse: 0.1148 - val_smape: 0.2220

Epoch 13/128

287/287 - 1s - 4ms/step - ia: 0.8920 - loss: 0.0612 - mae: 0.1734 - rmse: 0.2463 - smape: 0.3343 - val_ia: 0.9343 - val_loss: 0.0133 - val_mae: 0.0866 - val_rmse: 0.1130 - val_smape: 0.2159

Epoch 14/128

287/287 - 1s - 4ms/step - ia: 0.8923 - loss: 0.0608 - mae: 0.1728 - rmse: 0.2454 - smape: 0.3309 - val_ia: 0.9221 - val_loss: 0.0175 - val_mae: 0.1016 - val_rmse: 0.1287 - val_smape: 0.2261

Epoch 15/128

287/287 - 1s - 3ms/step - ia: 0.8933 - loss: 0.0600 - mae: 0.1710 - rmse: 0.2436 - smape: 0.3277 - val_ia: 0.9377 - val_loss: 0.0122 - val_mae: 0.0826 - val_rmse: 0.1090 - val_smape: 0.2085

Epoch 16/128

287/287 - 1s - 4ms/step - ia: 0.8936 - loss: 0.0603 - mae: 0.1707 - rmse: 0.2442 - smape: 0.3237 - val_ia: 0.9402 - val_loss: 0.0111 - val_mae: 0.0792 - val_rmse: 0.1038 - val_smape: 0.1998

Epoch 17/128

287/287 - 1s - 3ms/step - ia: 0.8943 - loss: 0.0591 - mae: 0.1697 - rmse: 0.2419 - smape: 0.3199 - val_ia: 0.9335 - val_loss: 0.0129 - val_mae: 0.0877 - val_rmse: 0.1114 - val_smape: 0.2124

Epoch 18/128

287/287 - 1s - 3ms/step - ia: 0.8953 - loss: 0.0583 - mae: 0.1682 - rmse: 0.2403 - smape: 0.3162 - val_ia: 0.9303 - val_loss: 0.0139 - val_mae: 0.0917 - val_rmse: 0.1166 - val_smape: 0.2081

Epoch 19/128

287/287 - 1s - 3ms/step - ia: 0.8958 - loss: 0.0586 - mae: 0.1674 - rmse: 0.2404 - smape: 0.3128 - val_ia: 0.9505 - val_loss: 0.0081 - val_mae: 0.0662 - val_rmse: 0.0890 - val_smape: 0.1810

Epoch 20/128

287/287 - 1s - 3ms/step - ia: 0.8964 - loss: 0.0578 - mae: 0.1664 - rmse: 0.2393 - smape: 0.3082 - val_ia: 0.9459 - val_loss: 0.0091 - val_mae: 0.0719 - val_rmse: 0.0943 - val_smape: 0.1818

Epoch 21/128

287/287 - 1s - 3ms/step - ia: 0.8971 - loss: 0.0576 - mae: 0.1654 - rmse: 0.2387 - smape: 0.3065 - val_ia: 0.9416 - val_loss: 0.0100 - val_mae: 0.0774 - val_rmse: 0.0980 - val_smape: 0.1959

Epoch 22/128

287/287 - 1s - 4ms/step - ia: 0.8976 - loss: 0.0572 - mae: 0.1646 - rmse: 0.2379 - smape: 0.3026 - val_ia: 0.9444 - val_loss: 0.0096 - val_mae: 0.0740 - val_rmse: 0.0968 - val_smape: 0.1803

Epoch 23/128

287/287 - 1s - 4ms/step - ia: 0.8980 - loss: 0.0568 - mae: 0.1641 - rmse: 0.2371 - smape: 0.2981 - val_ia: 0.9444 - val_loss: 0.0093 - val_mae: 0.0738 - val_rmse: 0.0955 - val_smape: 0.1815

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.8980 - loss: 0.0571 - mae: 0.1638 - rmse: 0.2376 - smape: 0.2977 - val_ia: 0.9371 - val_loss: 0.0112 - val_mae: 0.0832 - val_rmse: 0.1047 - val_smape: 0.1887

Epoch 25/128

287/287 - 1s - 5ms/step - ia: 0.8978 - loss: 0.0568 - mae: 0.1641 - rmse: 0.2370 - smape: 0.2971 - val_ia: 0.9424 - val_loss: 0.0097 - val_mae: 0.0762 - val_rmse: 0.0966 - val_smape: 0.1760

Epoch 26/128

287/287 - 1s - 5ms/step - ia: 0.8976 - loss: 0.0577 - mae: 0.1645 - rmse: 0.2388 - smape: 0.2974 - val_ia: 0.9473 - val_loss: 0.0082 - val_mae: 0.0702 - val_rmse: 0.0892 - val_smape: 0.1813

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.8982 - loss: 0.0570 - mae: 0.1638 - rmse: 0.2374 - smape: 0.2948 - val_ia: 0.9430 - val_loss: 0.0094 - val_mae: 0.0756 - val_rmse: 0.0960 - val_smape: 0.1762

Epoch 28/128

287/287 - 1s - 4ms/step - ia: 0.8989 - loss: 0.0564 - mae: 0.1628 - rmse: 0.2363 - smape: 0.2934 - val_ia: 0.9423 - val_loss: 0.0097 - val_mae: 0.0766 - val_rmse: 0.0975 - val_smape: 0.1767

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.8991 - loss: 0.0562 - mae: 0.1622 - rmse: 0.2358 - smape: 0.2913 - val_ia: 0.9444 - val_loss: 0.0090 - val_mae: 0.0738 - val_rmse: 0.0934 - val_smape: 0.1731

Epoch 30/128

287/287 - 2s - 9ms/step - ia: 0.8984 - loss: 0.0571 - mae: 0.1634 - rmse: 0.2376 - smape: 0.2930 - val_ia: 0.9537 - val_loss: 0.0067 - val_mae: 0.0620 - val_rmse: 0.0811 - val_smape: 0.1599

Epoch 31/128

287/287 - 1s - 4ms/step - ia: 0.8996 - loss: 0.0556 - mae: 0.1615 - rmse: 0.2347 - smape: 0.2893 - val_ia: 0.9485 - val_loss: 0.0079 - val_mae: 0.0687 - val_rmse: 0.0882 - val_smape: 0.1667

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.8999 - loss: 0.0556 - mae: 0.1610 - rmse: 0.2345 - smape: 0.2890 - val_ia: 0.9447 - val_loss: 0.0088 - val_mae: 0.0735 - val_rmse: 0.0924 - val_smape: 0.1733

Epoch 33/128

287/287 - 3s - 9ms/step - ia: 0.8997 - loss: 0.0557 - mae: 0.1612 - rmse: 0.2347 - smape: 0.2890 - val_ia: 0.9516 - val_loss: 0.0071 - val_mae: 0.0647 - val_rmse: 0.0835 - val_smape: 0.1671

Epoch 34/128

287/287 - 1s - 5ms/step - ia: 0.8997 - loss: 0.0560 - mae: 0.1612 - rmse: 0.2352 - smape: 0.2881 - val_ia: 0.9471 - val_loss: 0.0081 - val_mae: 0.0704 - val_rmse: 0.0879 - val_smape: 0.1763

Epoch 35/128

287/287 - 2s - 8ms/step - ia: 0.8993 - loss: 0.0560 - mae: 0.1619 - rmse: 0.2353 - smape: 0.2874 - val_ia: 0.9549 - val_loss: 0.0065 - val_mae: 0.0604 - val_rmse: 0.0795 - val_smape: 0.1569

Epoch 36/128

287/287 - 1s - 3ms/step - ia: 0.8999 - loss: 0.0554 - mae: 0.1611 - rmse: 0.2343 - smape: 0.2859 - val_ia: 0.9312 - val_loss: 0.0127 - val_mae: 0.0905 - val_rmse: 0.1115 - val_smape: 0.1860

Epoch 37/128

287/287 - 1s - 3ms/step - ia: 0.9001 - loss: 0.0557 - mae: 0.1606 - rmse: 0.2346 - smape: 0.2863 - val_ia: 0.9465 - val_loss: 0.0082 - val_mae: 0.0712 - val_rmse: 0.0891 - val_smape: 0.1691

Epoch 38/128

287/287 - 1s - 3ms/step - ia: 0.8997 - loss: 0.0560 - mae: 0.1614 - rmse: 0.2353 - smape: 0.2867 - val_ia: 0.9473 - val_loss: 0.0082 - val_mae: 0.0703 - val_rmse: 0.0899 - val_smape: 0.1669

Epoch 39/128

287/287 - 1s - 5ms/step - ia: 0.9000 - loss: 0.0558 - mae: 0.1608 - rmse: 0.2350 - smape: 0.2845 - val_ia: 0.9506 - val_loss: 0.0072 - val_mae: 0.0659 - val_rmse: 0.0837 - val_smape: 0.1631

Epoch 40/128

287/287 - 1s - 3ms/step - ia: 0.9003 - loss: 0.0554 - mae: 0.1605 - rmse: 0.2341 - smape: 0.2849 - val_ia: 0.9507 - val_loss: 0.0074 - val_mae: 0.0660 - val_rmse: 0.0851 - val_smape: 0.1595

Epoch 41/128

287/287 - 1s - 3ms/step - ia: 0.9005 - loss: 0.0550 - mae: 0.1599 - rmse: 0.2332 - smape: 0.2843 - val_ia: 0.9537 - val_loss: 0.0066 - val_mae: 0.0619 - val_rmse: 0.0804 - val_smape: 0.1541

Epoch 42/128

287/287 - 1s - 3ms/step - ia: 0.9001 - loss: 0.0553 - mae: 0.1606 - rmse: 0.2341 - smape: 0.2849 - val_ia: 0.9551 - val_loss: 0.0062 - val_mae: 0.0601 - val_rmse: 0.0773 - val_smape: 0.1520

Epoch 43/128

287/287 - 1s - 3ms/step - ia: 0.9005 - loss: 0.0554 - mae: 0.1598 - rmse: 0.2344 - smape: 0.2834 - val_ia: 0.9571 - val_loss: 0.0059 - val_mae: 0.0576 - val_rmse: 0.0759 - val_smape: 0.1491

Epoch 44/128

287/287 - 1s - 3ms/step - ia: 0.9005 - loss: 0.0552 - mae: 0.1601 - rmse: 0.2335 - smape: 0.2855 - val_ia: 0.9533 - val_loss: 0.0067 - val_mae: 0.0626 - val_rmse: 0.0809 - val_smape: 0.1529

Epoch 45/128

287/287 - 1s - 4ms/step - ia: 0.9007 - loss: 0.0548 - mae: 0.1598 - rmse: 0.2329 - smape: 0.2838 - val_ia: 0.9488 - val_loss: 0.0078 - val_mae: 0.0683 - val_rmse: 0.0873 - val_smape: 0.1583

Epoch 46/128

287/287 - 1s - 3ms/step - ia: 0.9003 - loss: 0.0559 - mae: 0.1603 - rmse: 0.2352 - smape: 0.2822 - val_ia: 0.9522 - val_loss: 0.0068 - val_mae: 0.0636 - val_rmse: 0.0800 - val_smape: 0.1626

Epoch 47/128

287/287 - 1s - 3ms/step - ia: 0.9004 - loss: 0.0549 - mae: 0.1603 - rmse: 0.2331 - smape: 0.2812 - val_ia: 0.9492 - val_loss: 0.0075 - val_mae: 0.0677 - val_rmse: 0.0854 - val_smape: 0.1611

Epoch 48/128

287/287 - 1s - 3ms/step - ia: 0.9002 - loss: 0.0555 - mae: 0.1604 - rmse: 0.2343 - smape: 0.2822 - val_ia: 0.9505 - val_loss: 0.0073 - val_mae: 0.0662 - val_rmse: 0.0841 - val_smape: 0.1569

Epoch 49/128

287/287 - 1s - 3ms/step - ia: 0.9004 - loss: 0.0554 - mae: 0.1603 - rmse: 0.2342 - smape: 0.2820 - val_ia: 0.9524 - val_loss: 0.0070 - val_mae: 0.0638 - val_rmse: 0.0827 - val_smape: 0.1561

Epoch 50/128

287/287 - 1s - 3ms/step - ia: 0.9007 - loss: 0.0547 - mae: 0.1597 - rmse: 0.2327 - smape: 0.2821 - val_ia: 0.9508 - val_loss: 0.0072 - val_mae: 0.0658 - val_rmse: 0.0837 - val_smape: 0.1570

Epoch 51/128

287/287 - 1s - 3ms/step - ia: 0.9015 - loss: 0.0537 - mae: 0.1584 - rmse: 0.2307 - smape: 0.2801 - val_ia: 0.9433 - val_loss: 0.0090 - val_mae: 0.0754 - val_rmse: 0.0939 - val_smape: 0.1667

Epoch 52/128

287/287 - 1s - 3ms/step - ia: 0.9008 - loss: 0.0554 - mae: 0.1596 - rmse: 0.2339 - smape: 0.2813 - val_ia: 0.9576 - val_loss: 0.0057 - val_mae: 0.0569 - val_rmse: 0.0745 - val_smape: 0.1460

Epoch 53/128

287/287 - 1s - 3ms/step - ia: 0.9005 - loss: 0.0552 - mae: 0.1601 - rmse: 0.2336 - smape: 0.2807 - val_ia: 0.9489 - val_loss: 0.0075 - val_mae: 0.0681 - val_rmse: 0.0854 - val_smape: 0.1608

Epoch 54/128

287/287 - 1s - 3ms/step - ia: 0.9001 - loss: 0.0555 - mae: 0.1607 - rmse: 0.2344 - smape: 0.2834 - val_ia: 0.9503 - val_loss: 0.0073 - val_mae: 0.0664 - val_rmse: 0.0842 - val_smape: 0.1565

Epoch 55/128

287/287 - 1s - 3ms/step - ia: 0.9012 - loss: 0.0547 - mae: 0.1590 - rmse: 0.2327 - smape: 0.2789 - val_ia: 0.9456 - val_loss: 0.0085 - val_mae: 0.0726 - val_rmse: 0.0913 - val_smape: 0.1624

Epoch 56/128

287/287 - 2s - 6ms/step - ia: 0.9005 - loss: 0.0557 - mae: 0.1602 - rmse: 0.2345 - smape: 0.2813 - val_ia: 0.9461 - val_loss: 0.0084 - val_mae: 0.0718 - val_rmse: 0.0908 - val_smape: 0.1597

Epoch 57/128

287/287 - 1s - 4ms/step - ia: 0.9004 - loss: 0.0558 - mae: 0.1601 - rmse: 0.2351 - smape: 0.2819 - val_ia: 0.9600 - val_loss: 0.0052 - val_mae: 0.0538 - val_rmse: 0.0717 - val_smape: 0.1348

Epoch 58/128

287/287 - 1s - 4ms/step - ia: 0.9014 - loss: 0.0545 - mae: 0.1588 - rmse: 0.2320 - smape: 0.2791 - val_ia: 0.9472 - val_loss: 0.0080 - val_mae: 0.0705 - val_rmse: 0.0886 - val_smape: 0.1599

Epoch 59/128

287/287 - 1s - 4ms/step - ia: 0.9009 - loss: 0.0553 - mae: 0.1596 - rmse: 0.2337 - smape: 0.2807 - val_ia: 0.9590 - val_loss: 0.0052 - val_mae: 0.0550 - val_rmse: 0.0710 - val_smape: 0.1514

Epoch 60/128

287/287 - 2s - 5ms/step - ia: 0.9016 - loss: 0.0543 - mae: 0.1583 - rmse: 0.2318 - smape: 0.2797 - val_ia: 0.9503 - val_loss: 0.0074 - val_mae: 0.0665 - val_rmse: 0.0849 - val_smape: 0.1564

Epoch 61/128

287/287 - 1s - 5ms/step - ia: 0.9009 - loss: 0.0552 - mae: 0.1592 - rmse: 0.2334 - smape: 0.2813 - val_ia: 0.9522 - val_loss: 0.0071 - val_mae: 0.0640 - val_rmse: 0.0833 - val_smape: 0.1518

Epoch 62/128

287/287 - 1s - 4ms/step - ia: 0.9011 - loss: 0.0545 - mae: 0.1590 - rmse: 0.2322 - smape: 0.2801 - val_ia: 0.9532 - val_loss: 0.0067 - val_mae: 0.0627 - val_rmse: 0.0809 - val_smape: 0.1523

Epoch 63/128

287/287 - 1s - 5ms/step - ia: 0.9009 - loss: 0.0552 - mae: 0.1595 - rmse: 0.2338 - smape: 0.2809 - val_ia: 0.9477 - val_loss: 0.0080 - val_mae: 0.0698 - val_rmse: 0.0881 - val_smape: 0.1602

Epoch 64/128

287/287 - 1s - 5ms/step - ia: 0.8997 - loss: 0.0562 - mae: 0.1611 - rmse: 0.2359 - smape: 0.2808 - val_ia: 0.9448 - val_loss: 0.0086 - val_mae: 0.0735 - val_rmse: 0.0909 - val_smape: 0.1733

Epoch 65/128

287/287 - 1s - 4ms/step - ia: 0.9016 - loss: 0.0544 - mae: 0.1584 - rmse: 0.2320 - smape: 0.2783 - val_ia: 0.9495 - val_loss: 0.0076 - val_mae: 0.0675 - val_rmse: 0.0866 - val_smape: 0.1511

Epoch 66/128

287/287 - 1s - 5ms/step - ia: 0.9008 - loss: 0.0552 - mae: 0.1595 - rmse: 0.2337 - smape: 0.2793 - val_ia: 0.9597 - val_loss: 0.0052 - val_mae: 0.0542 - val_rmse: 0.0712 - val_smape: 0.1434

Epoch 67/128

287/287 - 1s - 5ms/step - ia: 0.9002 - loss: 0.0557 - mae: 0.1605 - rmse: 0.2348 - smape: 0.2806 - val_ia: 0.9562 - val_loss: 0.0060 - val_mae: 0.0588 - val_rmse: 0.0764 - val_smape: 0.1477

Epoch 68/128

287/287 - 1s - 4ms/step - ia: 0.9017 - loss: 0.0543 - mae: 0.1583 - rmse: 0.2318 - smape: 0.2787 - val_ia: 0.9523 - val_loss: 0.0069 - val_mae: 0.0640 - val_rmse: 0.0822 - val_smape: 0.1507

Epoch 69/128

287/287 - 1s - 4ms/step - ia: 0.9016 - loss: 0.0541 - mae: 0.1583 - rmse: 0.2314 - smape: 0.2774 - val_ia: 0.9436 - val_loss: 0.0091 - val_mae: 0.0749 - val_rmse: 0.0937 - val_smape: 0.1621

Epoch 70/128

287/287 - 1s - 4ms/step - ia: 0.9004 - loss: 0.0560 - mae: 0.1602 - rmse: 0.2354 - smape: 0.2801 - val_ia: 0.9598 - val_loss: 0.0051 - val_mae: 0.0540 - val_rmse: 0.0705 - val_smape: 0.1445

Epoch 71/128

287/287 - 1s - 4ms/step - ia: 0.9016 - loss: 0.0540 - mae: 0.1583 - rmse: 0.2311 - smape: 0.2785 - val_ia: 0.9469 - val_loss: 0.0083 - val_mae: 0.0709 - val_rmse: 0.0901 - val_smape: 0.1636

Epoch 72/128

287/287 - 1s - 5ms/step - ia: 0.9021 - loss: 0.0535 - mae: 0.1576 - rmse: 0.2300 - smape: 0.2782 - val_ia: 0.9438 - val_loss: 0.0089 - val_mae: 0.0749 - val_rmse: 0.0932 - val_smape: 0.1655

Epoch 73/128

287/287 - 1s - 4ms/step - ia: 0.9007 - loss: 0.0550 - mae: 0.1598 - rmse: 0.2332 - smape: 0.2795 - val_ia: 0.9483 - val_loss: 0.0077 - val_mae: 0.0692 - val_rmse: 0.0872 - val_smape: 0.1591

Epoch 74/128

287/287 - 1s - 4ms/step - ia: 0.9011 - loss: 0.0552 - mae: 0.1591 - rmse: 0.2335 - smape: 0.2794 - val_ia: 0.9544 - val_loss: 0.0063 - val_mae: 0.0610 - val_rmse: 0.0779 - val_smape: 0.1522

Epoch 75/128

287/287 - 1s - 5ms/step - ia: 0.9016 - loss: 0.0548 - mae: 0.1586 - rmse: 0.2330 - smape: 0.2794 - val_ia: 0.9546 - val_loss: 0.0062 - val_mae: 0.0608 - val_rmse: 0.0778 - val_smape: 0.1493

Epoch 76/128

287/287 - 1s - 5ms/step - ia: 0.9010 - loss: 0.0551 - mae: 0.1593 - rmse: 0.2335 - smape: 0.2786 - val_ia: 0.9483 - val_loss: 0.0078 - val_mae: 0.0691 - val_rmse: 0.0877 - val_smape: 0.1579

Epoch 77/128

287/287 - 1s - 4ms/step - ia: 0.9004 - loss: 0.0552 - mae: 0.1603 - rmse: 0.2337 - smape: 0.2792 - val_ia: 0.9423 - val_loss: 0.0094 - val_mae: 0.0767 - val_rmse: 0.0953 - val_smape: 0.1699

Epoch 78/128

287/287 - 1s - 5ms/step - ia: 0.9005 - loss: 0.0556 - mae: 0.1599 - rmse: 0.2345 - smape: 0.2788 - val_ia: 0.9535 - val_loss: 0.0065 - val_mae: 0.0624 - val_rmse: 0.0801 - val_smape: 0.1532

Epoch 79/128

287/287 - 3s - 9ms/step - ia: 0.9009 - loss: 0.0546 - mae: 0.1593 - rmse: 0.2321 - smape: 0.2796 - val_ia: 0.9516 - val_loss: 0.0069 - val_mae: 0.0648 - val_rmse: 0.0819 - val_smape: 0.1576

Epoch 80/128

287/287 - 1s - 4ms/step - ia: 0.9018 - loss: 0.0543 - mae: 0.1581 - rmse: 0.2317 - smape: 0.2770 - val_ia: 0.9516 - val_loss: 0.0069 - val_mae: 0.0648 - val_rmse: 0.0825 - val_smape: 0.1561

Epoch 81/128

287/287 - 1s - 4ms/step - ia: 0.9013 - loss: 0.0547 - mae: 0.1587 - rmse: 0.2325 - smape: 0.2793 - val_ia: 0.9479 - val_loss: 0.0080 - val_mae: 0.0695 - val_rmse: 0.0885 - val_smape: 0.1564

Epoch 82/128

287/287 - 1s - 5ms/step - ia: 0.9012 - loss: 0.0547 - mae: 0.1590 - rmse: 0.2325 - smape: 0.2775 - val_ia: 0.9511 - val_loss: 0.0071 - val_mae: 0.0654 - val_rmse: 0.0832 - val_smape: 0.1502

Epoch 83/128

287/287 - 1s - 4ms/step - ia: 0.9006 - loss: 0.0556 - mae: 0.1600 - rmse: 0.2346 - smape: 0.2787 - val_ia: 0.9504 - val_loss: 0.0073 - val_mae: 0.0664 - val_rmse: 0.0848 - val_smape: 0.1544

Epoch 84/128

287/287 - 1s - 4ms/step - ia: 0.9017 - loss: 0.0547 - mae: 0.1581 - rmse: 0.2327 - smape: 0.2763 - val_ia: 0.9433 - val_loss: 0.0091 - val_mae: 0.0754 - val_rmse: 0.0935 - val_smape: 0.1703

Epoch 85/128

287/287 - 1s - 4ms/step - ia: 0.9006 - loss: 0.0557 - mae: 0.1596 - rmse: 0.2349 - smape: 0.2793 - val_ia: 0.9561 - val_loss: 0.0059 - val_mae: 0.0587 - val_rmse: 0.0748 - val_smape: 0.1523

Epoch 85: early stopping

Restoring model weights from the end of the best epoch: 70.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 37s 230ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 75%|███████▌  | 9/12 [3:14:48<34:52, 697.64s/trial, best loss: 0.0019945538727369925]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 28s - 12ms/step - ia: 0.6800 - loss: 0.3479 - mae: 0.4437 - rmse: 0.5452 - smape: 0.8356 - val_ia: 0.4039 - val_loss: 0.1550 - val_mae: 0.3085 - val_rmse: 0.3317 - val_smape: 0.6487

Epoch 2/128

2293/2293 - 27s - 12ms/step - ia: 0.8272 - loss: 0.1166 - mae: 0.2663 - rmse: 0.3342 - smape: 0.5623 - val_ia: 0.4825 - val_loss: 0.0913 - val_mae: 0.2375 - val_rmse: 0.2562 - val_smape: 0.5565

Epoch 3/128

2293/2293 - 25s - 11ms/step - ia: 0.8667 - loss: 0.0715 - mae: 0.2064 - rmse: 0.2612 - smape: 0.4648 - val_ia: 0.5649 - val_loss: 0.0458 - val_mae: 0.1668 - val_rmse: 0.1850 - val_smape: 0.4474

Epoch 4/128

2293/2293 - 24s - 11ms/step - ia: 0.8883 - loss: 0.0506 - mae: 0.1733 - rmse: 0.2199 - smape: 0.4023 - val_ia: 0.6385 - val_loss: 0.0241 - val_mae: 0.1177 - val_rmse: 0.1356 - val_smape: 0.3404

Epoch 5/128

2293/2293 - 22s - 10ms/step - ia: 0.9002 - loss: 0.0417 - mae: 0.1552 - rmse: 0.1988 - smape: 0.3653 - val_ia: 0.6385 - val_loss: 0.0235 - val_mae: 0.1167 - val_rmse: 0.1353 - val_smape: 0.3499

Epoch 6/128

2293/2293 - 44s - 19ms/step - ia: 0.9059 - loss: 0.0372 - mae: 0.1462 - rmse: 0.1878 - smape: 0.3474 - val_ia: 0.6849 - val_loss: 0.0179 - val_mae: 0.0952 - val_rmse: 0.1141 - val_smape: 0.2650

Epoch 7/128

2293/2293 - 25s - 11ms/step - ia: 0.9105 - loss: 0.0342 - mae: 0.1398 - rmse: 0.1800 - smape: 0.3364 - val_ia: 0.7122 - val_loss: 0.0135 - val_mae: 0.0808 - val_rmse: 0.0989 - val_smape: 0.2181

Epoch 8/128

2293/2293 - 40s - 17ms/step - ia: 0.9129 - loss: 0.0323 - mae: 0.1356 - rmse: 0.1746 - smape: 0.3264 - val_ia: 0.7285 - val_loss: 0.0122 - val_mae: 0.0758 - val_rmse: 0.0938 - val_smape: 0.2125

Epoch 9/128

2293/2293 - 25s - 11ms/step - ia: 0.9144 - loss: 0.0313 - mae: 0.1334 - rmse: 0.1720 - smape: 0.3226 - val_ia: 0.7189 - val_loss: 0.0127 - val_mae: 0.0788 - val_rmse: 0.0972 - val_smape: 0.2078

Epoch 10/128

2293/2293 - 41s - 18ms/step - ia: 0.9171 - loss: 0.0295 - mae: 0.1294 - rmse: 0.1668 - smape: 0.3161 - val_ia: 0.7019 - val_loss: 0.0136 - val_mae: 0.0841 - val_rmse: 0.1017 - val_smape: 0.2448

Epoch 11/128

2293/2293 - 41s - 18ms/step - ia: 0.9179 - loss: 0.0289 - mae: 0.1279 - rmse: 0.1650 - smape: 0.3102 - val_ia: 0.6924 - val_loss: 0.0136 - val_mae: 0.0865 - val_rmse: 0.1037 - val_smape: 0.2623

Epoch 12/128

2293/2293 - 25s - 11ms/step - ia: 0.9196 - loss: 0.0278 - mae: 0.1255 - rmse: 0.1622 - smape: 0.3059 - val_ia: 0.7451 - val_loss: 0.0101 - val_mae: 0.0691 - val_rmse: 0.0868 - val_smape: 0.1934

Epoch 13/128

2293/2293 - 25s - 11ms/step - ia: 0.9199 - loss: 0.0275 - mae: 0.1248 - rmse: 0.1611 - smape: 0.3042 - val_ia: 0.7371 - val_loss: 0.0102 - val_mae: 0.0708 - val_rmse: 0.0880 - val_smape: 0.2066

Epoch 14/128

2293/2293 - 25s - 11ms/step - ia: 0.9217 - loss: 0.0266 - mae: 0.1223 - rmse: 0.1583 - smape: 0.2961 - val_ia: 0.6839 - val_loss: 0.0139 - val_mae: 0.0880 - val_rmse: 0.1046 - val_smape: 0.2444

Epoch 15/128

2293/2293 - 25s - 11ms/step - ia: 0.9224 - loss: 0.0261 - mae: 0.1215 - rmse: 0.1567 - smape: 0.2974 - val_ia: 0.7095 - val_loss: 0.0116 - val_mae: 0.0790 - val_rmse: 0.0958 - val_smape: 0.2320

Epoch 16/128

2293/2293 - 25s - 11ms/step - ia: 0.9231 - loss: 0.0255 - mae: 0.1197 - rmse: 0.1549 - smape: 0.2921 - val_ia: 0.7363 - val_loss: 0.0098 - val_mae: 0.0699 - val_rmse: 0.0866 - val_smape: 0.1953

Epoch 17/128

2293/2293 - 25s - 11ms/step - ia: 0.9238 - loss: 0.0250 - mae: 0.1190 - rmse: 0.1538 - smape: 0.2904 - val_ia: 0.7398 - val_loss: 0.0095 - val_mae: 0.0683 - val_rmse: 0.0848 - val_smape: 0.1906

Epoch 18/128

2293/2293 - 38s - 17ms/step - ia: 0.9241 - loss: 0.0251 - mae: 0.1185 - rmse: 0.1538 - smape: 0.2897 - val_ia: 0.7295 - val_loss: 0.0099 - val_mae: 0.0721 - val_rmse: 0.0881 - val_smape: 0.2073

Epoch 19/128

2293/2293 - 23s - 10ms/step - ia: 0.9252 - loss: 0.0247 - mae: 0.1174 - rmse: 0.1526 - smape: 0.2861 - val_ia: 0.7211 - val_loss: 0.0105 - val_mae: 0.0741 - val_rmse: 0.0900 - val_smape: 0.2087

Epoch 20/128

2293/2293 - 22s - 10ms/step - ia: 0.9252 - loss: 0.0243 - mae: 0.1170 - rmse: 0.1512 - smape: 0.2854 - val_ia: 0.7404 - val_loss: 0.0093 - val_mae: 0.0683 - val_rmse: 0.0843 - val_smape: 0.1926

Epoch 21/128

2293/2293 - 24s - 10ms/step - ia: 0.9260 - loss: 0.0240 - mae: 0.1159 - rmse: 0.1504 - smape: 0.2812 - val_ia: 0.7202 - val_loss: 0.0104 - val_mae: 0.0752 - val_rmse: 0.0910 - val_smape: 0.2005

Epoch 22/128

2293/2293 - 25s - 11ms/step - ia: 0.9260 - loss: 0.0239 - mae: 0.1158 - rmse: 0.1499 - smape: 0.2823 - val_ia: 0.7297 - val_loss: 0.0099 - val_mae: 0.0719 - val_rmse: 0.0875 - val_smape: 0.2001

Epoch 23/128

2293/2293 - 22s - 10ms/step - ia: 0.9274 - loss: 0.0233 - mae: 0.1137 - rmse: 0.1477 - smape: 0.2771 - val_ia: 0.7291 - val_loss: 0.0098 - val_mae: 0.0717 - val_rmse: 0.0872 - val_smape: 0.1991

Epoch 24/128

2293/2293 - 25s - 11ms/step - ia: 0.9272 - loss: 0.0233 - mae: 0.1140 - rmse: 0.1478 - smape: 0.2772 - val_ia: 0.7121 - val_loss: 0.0107 - val_mae: 0.0770 - val_rmse: 0.0921 - val_smape: 0.2219

Epoch 25/128

2293/2293 - 25s - 11ms/step - ia: 0.9277 - loss: 0.0231 - mae: 0.1129 - rmse: 0.1471 - smape: 0.2747 - val_ia: 0.7379 - val_loss: 0.0091 - val_mae: 0.0690 - val_rmse: 0.0844 - val_smape: 0.1983

Epoch 26/128

2293/2293 - 22s - 9ms/step - ia: 0.9280 - loss: 0.0228 - mae: 0.1127 - rmse: 0.1465 - smape: 0.2749 - val_ia: 0.7586 - val_loss: 0.0077 - val_mae: 0.0623 - val_rmse: 0.0773 - val_smape: 0.1863

Epoch 27/128

2293/2293 - 24s - 10ms/step - ia: 0.9283 - loss: 0.0226 - mae: 0.1122 - rmse: 0.1457 - smape: 0.2739 - val_ia: 0.7542 - val_loss: 0.0081 - val_mae: 0.0646 - val_rmse: 0.0797 - val_smape: 0.1917

Epoch 28/128

2293/2293 - 40s - 17ms/step - ia: 0.9290 - loss: 0.0221 - mae: 0.1109 - rmse: 0.1439 - smape: 0.2711 - val_ia: 0.7430 - val_loss: 0.0086 - val_mae: 0.0677 - val_rmse: 0.0824 - val_smape: 0.2091

Epoch 29/128

2293/2293 - 21s - 9ms/step - ia: 0.9289 - loss: 0.0223 - mae: 0.1111 - rmse: 0.1446 - smape: 0.2678 - val_ia: 0.7393 - val_loss: 0.0087 - val_mae: 0.0679 - val_rmse: 0.0829 - val_smape: 0.1899

Epoch 30/128

2293/2293 - 24s - 11ms/step - ia: 0.9291 - loss: 0.0220 - mae: 0.1106 - rmse: 0.1436 - smape: 0.2708 - val_ia: 0.7279 - val_loss: 0.0095 - val_mae: 0.0721 - val_rmse: 0.0869 - val_smape: 0.1968

Epoch 31/128

2293/2293 - 23s - 10ms/step - ia: 0.9298 - loss: 0.0217 - mae: 0.1100 - rmse: 0.1429 - smape: 0.2669 - val_ia: 0.7166 - val_loss: 0.0107 - val_mae: 0.0766 - val_rmse: 0.0911 - val_smape: 0.2071

Epoch 32/128

2293/2293 - 22s - 10ms/step - ia: 0.9302 - loss: 0.0217 - mae: 0.1094 - rmse: 0.1426 - smape: 0.2674 - val_ia: 0.7306 - val_loss: 0.0094 - val_mae: 0.0712 - val_rmse: 0.0858 - val_smape: 0.2022

Epoch 33/128

2293/2293 - 43s - 19ms/step - ia: 0.9305 - loss: 0.0216 - mae: 0.1090 - rmse: 0.1421 - smape: 0.2656 - val_ia: 0.7560 - val_loss: 0.0076 - val_mae: 0.0626 - val_rmse: 0.0771 - val_smape: 0.1860

Epoch 34/128

2293/2293 - 25s - 11ms/step - ia: 0.9307 - loss: 0.0214 - mae: 0.1085 - rmse: 0.1415 - smape: 0.2621 - val_ia: 0.6865 - val_loss: 0.0131 - val_mae: 0.0881 - val_rmse: 0.1022 - val_smape: 0.2189

Epoch 35/128

2293/2293 - 40s - 17ms/step - ia: 0.9307 - loss: 0.0211 - mae: 0.1082 - rmse: 0.1406 - smape: 0.2627 - val_ia: 0.7570 - val_loss: 0.0076 - val_mae: 0.0631 - val_rmse: 0.0775 - val_smape: 0.1894

Epoch 36/128

2293/2293 - 23s - 10ms/step - ia: 0.9313 - loss: 0.0210 - mae: 0.1077 - rmse: 0.1404 - smape: 0.2611 - val_ia: 0.7529 - val_loss: 0.0078 - val_mae: 0.0643 - val_rmse: 0.0786 - val_smape: 0.1896

Epoch 37/128

2293/2293 - 23s - 10ms/step - ia: 0.9315 - loss: 0.0208 - mae: 0.1073 - rmse: 0.1397 - smape: 0.2611 - val_ia: 0.7405 - val_loss: 0.0085 - val_mae: 0.0676 - val_rmse: 0.0818 - val_smape: 0.1878

Epoch 38/128

2293/2293 - 23s - 10ms/step - ia: 0.9316 - loss: 0.0207 - mae: 0.1071 - rmse: 0.1395 - smape: 0.2598 - val_ia: 0.7648 - val_loss: 0.0069 - val_mae: 0.0595 - val_rmse: 0.0737 - val_smape: 0.1759

Epoch 39/128

2293/2293 - 22s - 10ms/step - ia: 0.9320 - loss: 0.0204 - mae: 0.1062 - rmse: 0.1383 - smape: 0.2590 - val_ia: 0.7305 - val_loss: 0.0091 - val_mae: 0.0712 - val_rmse: 0.0853 - val_smape: 0.2038

Epoch 40/128

2293/2293 - 24s - 11ms/step - ia: 0.9315 - loss: 0.0207 - mae: 0.1071 - rmse: 0.1393 - smape: 0.2632 - val_ia: 0.7516 - val_loss: 0.0077 - val_mae: 0.0646 - val_rmse: 0.0785 - val_smape: 0.1925

Epoch 41/128

2293/2293 - 21s - 9ms/step - ia: 0.9318 - loss: 0.0206 - mae: 0.1069 - rmse: 0.1389 - smape: 0.2616 - val_ia: 0.7535 - val_loss: 0.0076 - val_mae: 0.0638 - val_rmse: 0.0777 - val_smape: 0.1846

Epoch 42/128

2293/2293 - 24s - 11ms/step - ia: 0.9320 - loss: 0.0207 - mae: 0.1066 - rmse: 0.1391 - smape: 0.2587 - val_ia: 0.7613 - val_loss: 0.0072 - val_mae: 0.0615 - val_rmse: 0.0757 - val_smape: 0.1800

Epoch 43/128

2293/2293 - 22s - 9ms/step - ia: 0.9326 - loss: 0.0202 - mae: 0.1056 - rmse: 0.1377 - smape: 0.2566 - val_ia: 0.7418 - val_loss: 0.0082 - val_mae: 0.0669 - val_rmse: 0.0808 - val_smape: 0.1917

Epoch 44/128

2293/2293 - 24s - 10ms/step - ia: 0.9323 - loss: 0.0202 - mae: 0.1056 - rmse: 0.1376 - smape: 0.2577 - val_ia: 0.7536 - val_loss: 0.0075 - val_mae: 0.0632 - val_rmse: 0.0771 - val_smape: 0.1809

Epoch 45/128

2293/2293 - 23s - 10ms/step - ia: 0.9327 - loss: 0.0202 - mae: 0.1053 - rmse: 0.1376 - smape: 0.2562 - val_ia: 0.7339 - val_loss: 0.0089 - val_mae: 0.0704 - val_rmse: 0.0840 - val_smape: 0.1999

Epoch 46/128

2293/2293 - 23s - 10ms/step - ia: 0.9330 - loss: 0.0201 - mae: 0.1052 - rmse: 0.1373 - smape: 0.2542 - val_ia: 0.7747 - val_loss: 0.0064 - val_mae: 0.0573 - val_rmse: 0.0711 - val_smape: 0.1751

Epoch 47/128

2293/2293 - 24s - 10ms/step - ia: 0.9330 - loss: 0.0202 - mae: 0.1050 - rmse: 0.1372 - smape: 0.2550 - val_ia: 0.7392 - val_loss: 0.0083 - val_mae: 0.0676 - val_rmse: 0.0813 - val_smape: 0.1926

Epoch 48/128

2293/2293 - 41s - 18ms/step - ia: 0.9328 - loss: 0.0200 - mae: 0.1049 - rmse: 0.1366 - smape: 0.2541 - val_ia: 0.7607 - val_loss: 0.0072 - val_mae: 0.0617 - val_rmse: 0.0756 - val_smape: 0.1846

Epoch 49/128

2293/2293 - 22s - 9ms/step - ia: 0.9335 - loss: 0.0198 - mae: 0.1040 - rmse: 0.1358 - smape: 0.2547 - val_ia: 0.7804 - val_loss: 0.0060 - val_mae: 0.0552 - val_rmse: 0.0689 - val_smape: 0.1696

Epoch 50/128

2293/2293 - 24s - 11ms/step - ia: 0.9336 - loss: 0.0198 - mae: 0.1042 - rmse: 0.1361 - smape: 0.2541 - val_ia: 0.7649 - val_loss: 0.0066 - val_mae: 0.0592 - val_rmse: 0.0726 - val_smape: 0.1773

Epoch 51/128

2293/2293 - 25s - 11ms/step - ia: 0.9338 - loss: 0.0196 - mae: 0.1037 - rmse: 0.1353 - smape: 0.2507 - val_ia: 0.7471 - val_loss: 0.0080 - val_mae: 0.0656 - val_rmse: 0.0790 - val_smape: 0.1844

Epoch 52/128

2293/2293 - 28s - 12ms/step - ia: 0.9336 - loss: 0.0198 - mae: 0.1042 - rmse: 0.1360 - smape: 0.2517 - val_ia: 0.7529 - val_loss: 0.0075 - val_mae: 0.0639 - val_rmse: 0.0776 - val_smape: 0.1786

Epoch 53/128

2293/2293 - 25s - 11ms/step - ia: 0.9342 - loss: 0.0195 - mae: 0.1027 - rmse: 0.1350 - smape: 0.2521 - val_ia: 0.7508 - val_loss: 0.0077 - val_mae: 0.0649 - val_rmse: 0.0786 - val_smape: 0.1820

Epoch 54/128

2293/2293 - 31s - 13ms/step - ia: 0.9340 - loss: 0.0196 - mae: 0.1032 - rmse: 0.1355 - smape: 0.2505 - val_ia: 0.7176 - val_loss: 0.0099 - val_mae: 0.0752 - val_rmse: 0.0882 - val_smape: 0.2075

Epoch 55/128

2293/2293 - 28s - 12ms/step - ia: 0.9340 - loss: 0.0196 - mae: 0.1034 - rmse: 0.1353 - smape: 0.2511 - val_ia: 0.7797 - val_loss: 0.0062 - val_mae: 0.0572 - val_rmse: 0.0704 - val_smape: 0.1809

Epoch 56/128

2293/2293 - 30s - 13ms/step - ia: 0.9340 - loss: 0.0195 - mae: 0.1031 - rmse: 0.1350 - smape: 0.2517 - val_ia: 0.7520 - val_loss: 0.0074 - val_mae: 0.0640 - val_rmse: 0.0775 - val_smape: 0.1896

Epoch 57/128

2293/2293 - 39s - 17ms/step - ia: 0.9346 - loss: 0.0192 - mae: 0.1023 - rmse: 0.1338 - smape: 0.2491 - val_ia: 0.7703 - val_loss: 0.0064 - val_mae: 0.0583 - val_rmse: 0.0716 - val_smape: 0.1773

Epoch 58/128

2293/2293 - 27s - 12ms/step - ia: 0.9340 - loss: 0.0195 - mae: 0.1034 - rmse: 0.1352 - smape: 0.2511 - val_ia: 0.7426 - val_loss: 0.0081 - val_mae: 0.0669 - val_rmse: 0.0803 - val_smape: 0.1845

Epoch 59/128

2293/2293 - 26s - 12ms/step - ia: 0.9344 - loss: 0.0193 - mae: 0.1026 - rmse: 0.1345 - smape: 0.2487 - val_ia: 0.7356 - val_loss: 0.0085 - val_mae: 0.0696 - val_rmse: 0.0831 - val_smape: 0.1951

Epoch 60/128

2293/2293 - 29s - 13ms/step - ia: 0.9344 - loss: 0.0191 - mae: 0.1024 - rmse: 0.1338 - smape: 0.2495 - val_ia: 0.7520 - val_loss: 0.0073 - val_mae: 0.0636 - val_rmse: 0.0769 - val_smape: 0.1783

Epoch 61/128

2293/2293 - 27s - 12ms/step - ia: 0.9347 - loss: 0.0193 - mae: 0.1021 - rmse: 0.1342 - smape: 0.2466 - val_ia: 0.7541 - val_loss: 0.0073 - val_mae: 0.0635 - val_rmse: 0.0767 - val_smape: 0.1782

Epoch 62/128

2293/2293 - 27s - 12ms/step - ia: 0.9344 - loss: 0.0194 - mae: 0.1028 - rmse: 0.1344 - smape: 0.2483 - val_ia: 0.7579 - val_loss: 0.0071 - val_mae: 0.0618 - val_rmse: 0.0747 - val_smape: 0.1791

Epoch 63/128

2293/2293 - 25s - 11ms/step - ia: 0.9350 - loss: 0.0191 - mae: 0.1016 - rmse: 0.1337 - smape: 0.2450 - val_ia: 0.7555 - val_loss: 0.0071 - val_mae: 0.0629 - val_rmse: 0.0761 - val_smape: 0.1794

Epoch 64/128

2293/2293 - 26s - 11ms/step - ia: 0.9347 - loss: 0.0193 - mae: 0.1022 - rmse: 0.1341 - smape: 0.2481 - val_ia: 0.7596 - val_loss: 0.0070 - val_mae: 0.0615 - val_rmse: 0.0748 - val_smape: 0.1755

Epoch 64: early stopping

Restoring model weights from the end of the best epoch: 49.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:09 1s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 83%|████████▎ | 10/12 [3:43:52<34:00, 1020.42s/trial, best loss: 0.0019945538727369925]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 44s - 10ms/step - ia: 0.2316 - loss: 0.9685 - mae: 0.8148 - rmse: 0.9645 - smape: 1.6991 - val_ia: 0.1426 - val_loss: 0.8622 - val_mae: 0.7716 - val_rmse: 0.7886 - val_smape: 1.7005

Epoch 2/128

4586/4586 - 32s - 7ms/step - ia: 0.2478 - loss: 0.9307 - mae: 0.7977 - rmse: 0.9451 - smape: 1.6674 - val_ia: 0.1445 - val_loss: 0.8270 - val_mae: 0.7558 - val_rmse: 0.7726 - val_smape: 1.6944

Epoch 3/128

4586/4586 - 31s - 7ms/step - ia: 0.2662 - loss: 0.8925 - mae: 0.7799 - rmse: 0.9254 - smape: 1.6329 - val_ia: 0.1464 - val_loss: 0.7894 - val_mae: 0.7387 - val_rmse: 0.7551 - val_smape: 1.6795

Epoch 4/128

4586/4586 - 41s - 9ms/step - ia: 0.2861 - loss: 0.8552 - mae: 0.7613 - rmse: 0.9051 - smape: 1.5906 - val_ia: 0.1486 - val_loss: 0.7477 - val_mae: 0.7190 - val_rmse: 0.7351 - val_smape: 1.6468

Epoch 5/128

4586/4586 - 32s - 7ms/step - ia: 0.3109 - loss: 0.8181 - mae: 0.7410 - rmse: 0.8833 - smape: 1.5456 - val_ia: 0.1510 - val_loss: 0.7026 - val_mae: 0.6969 - val_rmse: 0.7125 - val_smape: 1.5891

Epoch 6/128

4586/4586 - 31s - 7ms/step - ia: 0.3366 - loss: 0.7771 - mae: 0.7182 - rmse: 0.8604 - smape: 1.4901 - val_ia: 0.1533 - val_loss: 0.6551 - val_mae: 0.6726 - val_rmse: 0.6877 - val_smape: 1.5171

Epoch 7/128

4586/4586 - 33s - 7ms/step - ia: 0.3647 - loss: 0.7448 - mae: 0.6988 - rmse: 0.8404 - smape: 1.4413 - val_ia: 0.1575 - val_loss: 0.6101 - val_mae: 0.6483 - val_rmse: 0.6630 - val_smape: 1.4418

Epoch 8/128

4586/4586 - 39s - 9ms/step - ia: 0.3874 - loss: 0.7152 - mae: 0.6821 - rmse: 0.8238 - smape: 1.3988 - val_ia: 0.1626 - val_loss: 0.5702 - val_mae: 0.6259 - val_rmse: 0.6404 - val_smape: 1.3753

Epoch 9/128

4586/4586 - 31s - 7ms/step - ia: 0.4102 - loss: 0.6853 - mae: 0.6641 - rmse: 0.8053 - smape: 1.3572 - val_ia: 0.1673 - val_loss: 0.5362 - val_mae: 0.6059 - val_rmse: 0.6204 - val_smape: 1.3176

Epoch 10/128

4586/4586 - 31s - 7ms/step - ia: 0.4285 - loss: 0.6685 - mae: 0.6531 - rmse: 0.7942 - smape: 1.3316 - val_ia: 0.1715 - val_loss: 0.5112 - val_mae: 0.5907 - val_rmse: 0.6052 - val_smape: 1.2738

Epoch 11/128

4586/4586 - 41s - 9ms/step - ia: 0.4429 - loss: 0.6497 - mae: 0.6432 - rmse: 0.7826 - smape: 1.3015 - val_ia: 0.1752 - val_loss: 0.4904 - val_mae: 0.5777 - val_rmse: 0.5923 - val_smape: 1.2365

Epoch 12/128

4586/4586 - 33s - 7ms/step - ia: 0.4583 - loss: 0.6321 - mae: 0.6310 - rmse: 0.7716 - smape: 1.2750 - val_ia: 0.1773 - val_loss: 0.4738 - val_mae: 0.5676 - val_rmse: 0.5822 - val_smape: 1.2064

Epoch 13/128

4586/4586 - 36s - 8ms/step - ia: 0.4651 - loss: 0.6264 - mae: 0.6274 - rmse: 0.7672 - smape: 1.2636 - val_ia: 0.1771 - val_loss: 0.4615 - val_mae: 0.5604 - val_rmse: 0.5749 - val_smape: 1.1833

Epoch 14/128

4586/4586 - 20s - 4ms/step - ia: 0.4751 - loss: 0.6111 - mae: 0.6190 - rmse: 0.7589 - smape: 1.2413 - val_ia: 0.1775 - val_loss: 0.4516 - val_mae: 0.5544 - val_rmse: 0.5690 - val_smape: 1.1637

Epoch 15/128

4586/4586 - 20s - 4ms/step - ia: 0.4846 - loss: 0.5982 - mae: 0.6106 - rmse: 0.7493 - smape: 1.2258 - val_ia: 0.1783 - val_loss: 0.4416 - val_mae: 0.5483 - val_rmse: 0.5628 - val_smape: 1.1445

Epoch 16/128

4586/4586 - 19s - 4ms/step - ia: 0.4920 - loss: 0.5940 - mae: 0.6072 - rmse: 0.7464 - smape: 1.2181 - val_ia: 0.1793 - val_loss: 0.4353 - val_mae: 0.5445 - val_rmse: 0.5590 - val_smape: 1.1307

Epoch 17/128

4586/4586 - 19s - 4ms/step - ia: 0.4963 - loss: 0.5897 - mae: 0.6039 - rmse: 0.7439 - smape: 1.2091 - val_ia: 0.1803 - val_loss: 0.4291 - val_mae: 0.5405 - val_rmse: 0.5550 - val_smape: 1.1178

Epoch 18/128

4586/4586 - 20s - 4ms/step - ia: 0.5004 - loss: 0.5826 - mae: 0.6008 - rmse: 0.7393 - smape: 1.1989 - val_ia: 0.1806 - val_loss: 0.4252 - val_mae: 0.5381 - val_rmse: 0.5525 - val_smape: 1.1085

Epoch 19/128

4586/4586 - 19s - 4ms/step - ia: 0.5070 - loss: 0.5739 - mae: 0.5943 - rmse: 0.7339 - smape: 1.1873 - val_ia: 0.1811 - val_loss: 0.4207 - val_mae: 0.5352 - val_rmse: 0.5496 - val_smape: 1.0986

Epoch 20/128

4586/4586 - 20s - 4ms/step - ia: 0.5078 - loss: 0.5703 - mae: 0.5932 - rmse: 0.7318 - smape: 1.1869 - val_ia: 0.1813 - val_loss: 0.4173 - val_mae: 0.5331 - val_rmse: 0.5475 - val_smape: 1.0907

Epoch 21/128

4586/4586 - 20s - 4ms/step - ia: 0.5085 - loss: 0.5679 - mae: 0.5923 - rmse: 0.7293 - smape: 1.1837 - val_ia: 0.1819 - val_loss: 0.4117 - val_mae: 0.5294 - val_rmse: 0.5437 - val_smape: 1.0797

Epoch 22/128

4586/4586 - 19s - 4ms/step - ia: 0.5152 - loss: 0.5646 - mae: 0.5892 - rmse: 0.7272 - smape: 1.1771 - val_ia: 0.1821 - val_loss: 0.4086 - val_mae: 0.5273 - val_rmse: 0.5416 - val_smape: 1.0726

Epoch 23/128

4586/4586 - 19s - 4ms/step - ia: 0.5204 - loss: 0.5525 - mae: 0.5828 - rmse: 0.7200 - smape: 1.1648 - val_ia: 0.1825 - val_loss: 0.4050 - val_mae: 0.5250 - val_rmse: 0.5392 - val_smape: 1.0651

Epoch 24/128

4586/4586 - 19s - 4ms/step - ia: 0.5239 - loss: 0.5473 - mae: 0.5792 - rmse: 0.7151 - smape: 1.1567 - val_ia: 0.1826 - val_loss: 0.4023 - val_mae: 0.5233 - val_rmse: 0.5376 - val_smape: 1.0588

Epoch 25/128

4586/4586 - 20s - 4ms/step - ia: 0.5255 - loss: 0.5465 - mae: 0.5784 - rmse: 0.7156 - smape: 1.1524 - val_ia: 0.1829 - val_loss: 0.3993 - val_mae: 0.5213 - val_rmse: 0.5355 - val_smape: 1.0525

Epoch 26/128

4586/4586 - 19s - 4ms/step - ia: 0.5277 - loss: 0.5451 - mae: 0.5770 - rmse: 0.7139 - smape: 1.1519 - val_ia: 0.1830 - val_loss: 0.3979 - val_mae: 0.5205 - val_rmse: 0.5347 - val_smape: 1.0487

Epoch 27/128

4586/4586 - 19s - 4ms/step - ia: 0.5302 - loss: 0.5401 - mae: 0.5741 - rmse: 0.7110 - smape: 1.1440 - val_ia: 0.1834 - val_loss: 0.3947 - val_mae: 0.5183 - val_rmse: 0.5325 - val_smape: 1.0422

Epoch 28/128

4586/4586 - 19s - 4ms/step - ia: 0.5347 - loss: 0.5316 - mae: 0.5685 - rmse: 0.7045 - smape: 1.1384 - val_ia: 0.1838 - val_loss: 0.3914 - val_mae: 0.5162 - val_rmse: 0.5303 - val_smape: 1.0356

Epoch 29/128

4586/4586 - 19s - 4ms/step - ia: 0.5371 - loss: 0.5278 - mae: 0.5663 - rmse: 0.7028 - smape: 1.1315 - val_ia: 0.1843 - val_loss: 0.3876 - val_mae: 0.5137 - val_rmse: 0.5279 - val_smape: 1.0283

Epoch 30/128

4586/4586 - 19s - 4ms/step - ia: 0.5396 - loss: 0.5250 - mae: 0.5652 - rmse: 0.7005 - smape: 1.1280 - val_ia: 0.1847 - val_loss: 0.3850 - val_mae: 0.5119 - val_rmse: 0.5261 - val_smape: 1.0230

Epoch 31/128

4586/4586 - 20s - 4ms/step - ia: 0.5404 - loss: 0.5253 - mae: 0.5644 - rmse: 0.7005 - smape: 1.1241 - val_ia: 0.1852 - val_loss: 0.3825 - val_mae: 0.5103 - val_rmse: 0.5244 - val_smape: 1.0178

Epoch 32/128

4586/4586 - 20s - 4ms/step - ia: 0.5458 - loss: 0.5157 - mae: 0.5594 - rmse: 0.6936 - smape: 1.1171 - val_ia: 0.1855 - val_loss: 0.3809 - val_mae: 0.5092 - val_rmse: 0.5234 - val_smape: 1.0143

Epoch 33/128

4586/4586 - 20s - 4ms/step - ia: 0.5471 - loss: 0.5158 - mae: 0.5583 - rmse: 0.6937 - smape: 1.1134 - val_ia: 0.1860 - val_loss: 0.3787 - val_mae: 0.5078 - val_rmse: 0.5219 - val_smape: 1.0098

Epoch 34/128

4586/4586 - 20s - 4ms/step - ia: 0.5500 - loss: 0.5103 - mae: 0.5553 - rmse: 0.6904 - smape: 1.1079 - val_ia: 0.1865 - val_loss: 0.3758 - val_mae: 0.5057 - val_rmse: 0.5198 - val_smape: 1.0047

Epoch 35/128

4586/4586 - 19s - 4ms/step - ia: 0.5502 - loss: 0.5080 - mae: 0.5543 - rmse: 0.6884 - smape: 1.1054 - val_ia: 0.1871 - val_loss: 0.3733 - val_mae: 0.5040 - val_rmse: 0.5181 - val_smape: 0.9996

Epoch 36/128

4586/4586 - 20s - 4ms/step - ia: 0.5534 - loss: 0.5029 - mae: 0.5517 - rmse: 0.6855 - smape: 1.0983 - val_ia: 0.1878 - val_loss: 0.3701 - val_mae: 0.5018 - val_rmse: 0.5159 - val_smape: 0.9938

Epoch 37/128

4586/4586 - 20s - 4ms/step - ia: 0.5560 - loss: 0.4979 - mae: 0.5489 - rmse: 0.6819 - smape: 1.0966 - val_ia: 0.1882 - val_loss: 0.3680 - val_mae: 0.5003 - val_rmse: 0.5145 - val_smape: 0.9895

Epoch 38/128

4586/4586 - 20s - 4ms/step - ia: 0.5566 - loss: 0.4962 - mae: 0.5484 - rmse: 0.6808 - smape: 1.0934 - val_ia: 0.1888 - val_loss: 0.3654 - val_mae: 0.4986 - val_rmse: 0.5127 - val_smape: 0.9848

Epoch 39/128

4586/4586 - 20s - 4ms/step - ia: 0.5618 - loss: 0.4871 - mae: 0.5438 - rmse: 0.6746 - smape: 1.0823 - val_ia: 0.1892 - val_loss: 0.3629 - val_mae: 0.4968 - val_rmse: 0.5109 - val_smape: 0.9802

Epoch 40/128

4586/4586 - 22s - 5ms/step - ia: 0.5617 - loss: 0.4907 - mae: 0.5446 - rmse: 0.6765 - smape: 1.0813 - val_ia: 0.1895 - val_loss: 0.3612 - val_mae: 0.4957 - val_rmse: 0.5098 - val_smape: 0.9768

Epoch 41/128

4586/4586 - 20s - 4ms/step - ia: 0.5683 - loss: 0.4789 - mae: 0.5368 - rmse: 0.6681 - smape: 1.0699 - val_ia: 0.1899 - val_loss: 0.3589 - val_mae: 0.4941 - val_rmse: 0.5082 - val_smape: 0.9722

Epoch 42/128

4586/4586 - 20s - 4ms/step - ia: 0.5678 - loss: 0.4812 - mae: 0.5377 - rmse: 0.6695 - smape: 1.0715 - val_ia: 0.1902 - val_loss: 0.3563 - val_mae: 0.4923 - val_rmse: 0.5064 - val_smape: 0.9675

Epoch 43/128

4586/4586 - 19s - 4ms/step - ia: 0.5697 - loss: 0.4784 - mae: 0.5375 - rmse: 0.6685 - smape: 1.0664 - val_ia: 0.1906 - val_loss: 0.3543 - val_mae: 0.4909 - val_rmse: 0.5050 - val_smape: 0.9637

Epoch 44/128

4586/4586 - 20s - 4ms/step - ia: 0.5683 - loss: 0.4805 - mae: 0.5370 - rmse: 0.6690 - smape: 1.0672 - val_ia: 0.1909 - val_loss: 0.3524 - val_mae: 0.4896 - val_rmse: 0.5037 - val_smape: 0.9602

Epoch 45/128

4586/4586 - 20s - 4ms/step - ia: 0.5724 - loss: 0.4737 - mae: 0.5351 - rmse: 0.6649 - smape: 1.0594 - val_ia: 0.1912 - val_loss: 0.3507 - val_mae: 0.4883 - val_rmse: 0.5024 - val_smape: 0.9572

Epoch 46/128

4586/4586 - 20s - 4ms/step - ia: 0.5757 - loss: 0.4702 - mae: 0.5317 - rmse: 0.6616 - smape: 1.0536 - val_ia: 0.1915 - val_loss: 0.3490 - val_mae: 0.4871 - val_rmse: 0.5012 - val_smape: 0.9537

Epoch 47/128

4586/4586 - 20s - 4ms/step - ia: 0.5734 - loss: 0.4697 - mae: 0.5323 - rmse: 0.6625 - smape: 1.0574 - val_ia: 0.1919 - val_loss: 0.3461 - val_mae: 0.4850 - val_rmse: 0.4991 - val_smape: 0.9487

Epoch 48/128

4586/4586 - 25s - 5ms/step - ia: 0.5793 - loss: 0.4675 - mae: 0.5288 - rmse: 0.6603 - smape: 1.0477 - val_ia: 0.1921 - val_loss: 0.3441 - val_mae: 0.4836 - val_rmse: 0.4977 - val_smape: 0.9455

Epoch 49/128

4586/4586 - 21s - 4ms/step - ia: 0.5788 - loss: 0.4635 - mae: 0.5268 - rmse: 0.6572 - smape: 1.0429 - val_ia: 0.1923 - val_loss: 0.3421 - val_mae: 0.4822 - val_rmse: 0.4963 - val_smape: 0.9416

Epoch 50/128

4586/4586 - 20s - 4ms/step - ia: 0.5814 - loss: 0.4592 - mae: 0.5253 - rmse: 0.6537 - smape: 1.0393 - val_ia: 0.1926 - val_loss: 0.3404 - val_mae: 0.4809 - val_rmse: 0.4950 - val_smape: 0.9382

Epoch 51/128

4586/4586 - 21s - 5ms/step - ia: 0.5844 - loss: 0.4557 - mae: 0.5227 - rmse: 0.6527 - smape: 1.0367 - val_ia: 0.1930 - val_loss: 0.3376 - val_mae: 0.4789 - val_rmse: 0.4930 - val_smape: 0.9333

Epoch 52/128

4586/4586 - 21s - 5ms/step - ia: 0.5858 - loss: 0.4545 - mae: 0.5212 - rmse: 0.6499 - smape: 1.0308 - val_ia: 0.1934 - val_loss: 0.3353 - val_mae: 0.4772 - val_rmse: 0.4913 - val_smape: 0.9294

Epoch 53/128

4586/4586 - 21s - 5ms/step - ia: 0.5863 - loss: 0.4500 - mae: 0.5203 - rmse: 0.6477 - smape: 1.0320 - val_ia: 0.1937 - val_loss: 0.3331 - val_mae: 0.4756 - val_rmse: 0.4897 - val_smape: 0.9251

Epoch 54/128

4586/4586 - 21s - 4ms/step - ia: 0.5902 - loss: 0.4506 - mae: 0.5183 - rmse: 0.6480 - smape: 1.0198 - val_ia: 0.1940 - val_loss: 0.3317 - val_mae: 0.4746 - val_rmse: 0.4887 - val_smape: 0.9226

Epoch 55/128

4586/4586 - 41s - 9ms/step - ia: 0.5882 - loss: 0.4531 - mae: 0.5201 - rmse: 0.6489 - smape: 1.0254 - val_ia: 0.1942 - val_loss: 0.3307 - val_mae: 0.4738 - val_rmse: 0.4879 - val_smape: 0.9206

Epoch 56/128

4586/4586 - 20s - 4ms/step - ia: 0.5902 - loss: 0.4478 - mae: 0.5171 - rmse: 0.6453 - smape: 1.0209 - val_ia: 0.1946 - val_loss: 0.3280 - val_mae: 0.4718 - val_rmse: 0.4859 - val_smape: 0.9161

Epoch 57/128

4586/4586 - 20s - 4ms/step - ia: 0.5886 - loss: 0.4499 - mae: 0.5189 - rmse: 0.6464 - smape: 1.0206 - val_ia: 0.1948 - val_loss: 0.3267 - val_mae: 0.4708 - val_rmse: 0.4849 - val_smape: 0.9136

Epoch 58/128

4586/4586 - 21s - 5ms/step - ia: 0.5928 - loss: 0.4479 - mae: 0.5164 - rmse: 0.6458 - smape: 1.0166 - val_ia: 0.1949 - val_loss: 0.3260 - val_mae: 0.4702 - val_rmse: 0.4843 - val_smape: 0.9120

Epoch 59/128

4586/4586 - 21s - 5ms/step - ia: 0.5940 - loss: 0.4401 - mae: 0.5122 - rmse: 0.6402 - smape: 1.0106 - val_ia: 0.1954 - val_loss: 0.3232 - val_mae: 0.4681 - val_rmse: 0.4822 - val_smape: 0.9074

Epoch 60/128

4586/4586 - 21s - 5ms/step - ia: 0.5943 - loss: 0.4420 - mae: 0.5126 - rmse: 0.6403 - smape: 1.0067 - val_ia: 0.1956 - val_loss: 0.3219 - val_mae: 0.4671 - val_rmse: 0.4813 - val_smape: 0.9048

Epoch 61/128

4586/4586 - 21s - 4ms/step - ia: 0.5968 - loss: 0.4370 - mae: 0.5097 - rmse: 0.6375 - smape: 1.0044 - val_ia: 0.1959 - val_loss: 0.3196 - val_mae: 0.4653 - val_rmse: 0.4794 - val_smape: 0.9007

Epoch 62/128

4586/4586 - 21s - 4ms/step - ia: 0.5966 - loss: 0.4366 - mae: 0.5106 - rmse: 0.6371 - smape: 1.0013 - val_ia: 0.1961 - val_loss: 0.3187 - val_mae: 0.4647 - val_rmse: 0.4788 - val_smape: 0.8985

Epoch 63/128

4586/4586 - 20s - 4ms/step - ia: 0.6015 - loss: 0.4335 - mae: 0.5069 - rmse: 0.6348 - smape: 0.9967 - val_ia: 0.1964 - val_loss: 0.3173 - val_mae: 0.4636 - val_rmse: 0.4777 - val_smape: 0.8960

Epoch 64/128

4586/4586 - 21s - 5ms/step - ia: 0.6005 - loss: 0.4326 - mae: 0.5078 - rmse: 0.6339 - smape: 0.9952 - val_ia: 0.1965 - val_loss: 0.3164 - val_mae: 0.4629 - val_rmse: 0.4769 - val_smape: 0.8943

Epoch 65/128

4586/4586 - 21s - 5ms/step - ia: 0.5979 - loss: 0.4370 - mae: 0.5096 - rmse: 0.6368 - smape: 0.9988 - val_ia: 0.1969 - val_loss: 0.3147 - val_mae: 0.4616 - val_rmse: 0.4756 - val_smape: 0.8911

Epoch 66/128

4586/4586 - 20s - 4ms/step - ia: 0.6022 - loss: 0.4304 - mae: 0.5057 - rmse: 0.6320 - smape: 0.9916 - val_ia: 0.1971 - val_loss: 0.3138 - val_mae: 0.4609 - val_rmse: 0.4750 - val_smape: 0.8894

Epoch 67/128

4586/4586 - 21s - 4ms/step - ia: 0.6020 - loss: 0.4297 - mae: 0.5056 - rmse: 0.6316 - smape: 0.9913 - val_ia: 0.1973 - val_loss: 0.3121 - val_mae: 0.4596 - val_rmse: 0.4736 - val_smape: 0.8863

Epoch 68/128

4586/4586 - 20s - 4ms/step - ia: 0.6026 - loss: 0.4305 - mae: 0.5057 - rmse: 0.6328 - smape: 0.9885 - val_ia: 0.1974 - val_loss: 0.3116 - val_mae: 0.4592 - val_rmse: 0.4732 - val_smape: 0.8849

Epoch 69/128

4586/4586 - 20s - 4ms/step - ia: 0.6039 - loss: 0.4298 - mae: 0.5047 - rmse: 0.6321 - smape: 0.9875 - val_ia: 0.1977 - val_loss: 0.3101 - val_mae: 0.4580 - val_rmse: 0.4721 - val_smape: 0.8823

Epoch 70/128

4586/4586 - 20s - 4ms/step - ia: 0.6044 - loss: 0.4260 - mae: 0.5027 - rmse: 0.6295 - smape: 0.9832 - val_ia: 0.1979 - val_loss: 0.3087 - val_mae: 0.4570 - val_rmse: 0.4710 - val_smape: 0.8801

Epoch 71/128

4586/4586 - 21s - 5ms/step - ia: 0.6097 - loss: 0.4188 - mae: 0.4982 - rmse: 0.6237 - smape: 0.9756 - val_ia: 0.1983 - val_loss: 0.3068 - val_mae: 0.4554 - val_rmse: 0.4695 - val_smape: 0.8770

Epoch 72/128

4586/4586 - 21s - 5ms/step - ia: 0.6057 - loss: 0.4266 - mae: 0.5024 - rmse: 0.6292 - smape: 0.9806 - val_ia: 0.1985 - val_loss: 0.3054 - val_mae: 0.4543 - val_rmse: 0.4684 - val_smape: 0.8744

Epoch 73/128

4586/4586 - 21s - 4ms/step - ia: 0.6065 - loss: 0.4254 - mae: 0.5022 - rmse: 0.6283 - smape: 0.9787 - val_ia: 0.1987 - val_loss: 0.3042 - val_mae: 0.4534 - val_rmse: 0.4675 - val_smape: 0.8724

Epoch 74/128

4586/4586 - 21s - 4ms/step - ia: 0.6089 - loss: 0.4209 - mae: 0.5014 - rmse: 0.6254 - smape: 0.9797 - val_ia: 0.1992 - val_loss: 0.3023 - val_mae: 0.4517 - val_rmse: 0.4658 - val_smape: 0.8696

Epoch 75/128

4586/4586 - 21s - 4ms/step - ia: 0.6103 - loss: 0.4180 - mae: 0.4985 - rmse: 0.6232 - smape: 0.9720 - val_ia: 0.1993 - val_loss: 0.3015 - val_mae: 0.4511 - val_rmse: 0.4652 - val_smape: 0.8682

Epoch 76/128

4586/4586 - 21s - 4ms/step - ia: 0.6099 - loss: 0.4183 - mae: 0.4979 - rmse: 0.6227 - smape: 0.9707 - val_ia: 0.1997 - val_loss: 0.2992 - val_mae: 0.4494 - val_rmse: 0.4634 - val_smape: 0.8646

Epoch 77/128

4586/4586 - 21s - 5ms/step - ia: 0.6105 - loss: 0.4158 - mae: 0.4970 - rmse: 0.6217 - smape: 0.9691 - val_ia: 0.1998 - val_loss: 0.2982 - val_mae: 0.4486 - val_rmse: 0.4626 - val_smape: 0.8629

Epoch 78/128

4586/4586 - 21s - 5ms/step - ia: 0.6145 - loss: 0.4152 - mae: 0.4950 - rmse: 0.6200 - smape: 0.9634 - val_ia: 0.1999 - val_loss: 0.2973 - val_mae: 0.4479 - val_rmse: 0.4619 - val_smape: 0.8614

Epoch 79/128

4586/4586 - 20s - 4ms/step - ia: 0.6119 - loss: 0.4177 - mae: 0.4977 - rmse: 0.6224 - smape: 0.9648 - val_ia: 0.2002 - val_loss: 0.2954 - val_mae: 0.4464 - val_rmse: 0.4604 - val_smape: 0.8585

Epoch 80/128

4586/4586 - 21s - 4ms/step - ia: 0.6129 - loss: 0.4158 - mae: 0.4963 - rmse: 0.6211 - smape: 0.9636 - val_ia: 0.2003 - val_loss: 0.2948 - val_mae: 0.4459 - val_rmse: 0.4599 - val_smape: 0.8575

Epoch 81/128

4586/4586 - 20s - 4ms/step - ia: 0.6146 - loss: 0.4134 - mae: 0.4943 - rmse: 0.6195 - smape: 0.9592 - val_ia: 0.2007 - val_loss: 0.2930 - val_mae: 0.4444 - val_rmse: 0.4584 - val_smape: 0.8549

Epoch 82/128

4586/4586 - 20s - 4ms/step - ia: 0.6147 - loss: 0.4112 - mae: 0.4943 - rmse: 0.6178 - smape: 0.9586 - val_ia: 0.2009 - val_loss: 0.2917 - val_mae: 0.4433 - val_rmse: 0.4573 - val_smape: 0.8527

Epoch 83/128

4586/4586 - 20s - 4ms/step - ia: 0.6161 - loss: 0.4102 - mae: 0.4926 - rmse: 0.6167 - smape: 0.9583 - val_ia: 0.2016 - val_loss: 0.2890 - val_mae: 0.4410 - val_rmse: 0.4550 - val_smape: 0.8487

Epoch 84/128

4586/4586 - 21s - 5ms/step - ia: 0.6157 - loss: 0.4106 - mae: 0.4921 - rmse: 0.6164 - smape: 0.9529 - val_ia: 0.2015 - val_loss: 0.2887 - val_mae: 0.4408 - val_rmse: 0.4548 - val_smape: 0.8479

Epoch 85/128

4586/4586 - 21s - 5ms/step - ia: 0.6173 - loss: 0.4089 - mae: 0.4909 - rmse: 0.6151 - smape: 0.9540 - val_ia: 0.2018 - val_loss: 0.2874 - val_mae: 0.4398 - val_rmse: 0.4537 - val_smape: 0.8458

Epoch 86/128

4586/4586 - 21s - 5ms/step - ia: 0.6190 - loss: 0.4055 - mae: 0.4886 - rmse: 0.6126 - smape: 0.9490 - val_ia: 0.2022 - val_loss: 0.2853 - val_mae: 0.4380 - val_rmse: 0.4520 - val_smape: 0.8426

Epoch 87/128

4586/4586 - 21s - 5ms/step - ia: 0.6230 - loss: 0.4019 - mae: 0.4876 - rmse: 0.6103 - smape: 0.9445 - val_ia: 0.2022 - val_loss: 0.2850 - val_mae: 0.4378 - val_rmse: 0.4518 - val_smape: 0.8420

Epoch 88/128

4586/4586 - 21s - 4ms/step - ia: 0.6189 - loss: 0.4064 - mae: 0.4897 - rmse: 0.6136 - smape: 0.9477 - val_ia: 0.2024 - val_loss: 0.2842 - val_mae: 0.4371 - val_rmse: 0.4511 - val_smape: 0.8407

Epoch 89/128

4586/4586 - 21s - 5ms/step - ia: 0.6211 - loss: 0.4020 - mae: 0.4879 - rmse: 0.6106 - smape: 0.9484 - val_ia: 0.2027 - val_loss: 0.2823 - val_mae: 0.4356 - val_rmse: 0.4495 - val_smape: 0.8377

Epoch 90/128

4586/4586 - 21s - 5ms/step - ia: 0.6206 - loss: 0.4032 - mae: 0.4877 - rmse: 0.6109 - smape: 0.9439 - val_ia: 0.2026 - val_loss: 0.2823 - val_mae: 0.4357 - val_rmse: 0.4496 - val_smape: 0.8376

Epoch 91/128

4586/4586 - 21s - 5ms/step - ia: 0.6203 - loss: 0.4054 - mae: 0.4890 - rmse: 0.6129 - smape: 0.9425 - val_ia: 0.2027 - val_loss: 0.2816 - val_mae: 0.4351 - val_rmse: 0.4491 - val_smape: 0.8366

Epoch 92/128

4586/4586 - 20s - 4ms/step - ia: 0.6215 - loss: 0.4044 - mae: 0.4878 - rmse: 0.6123 - smape: 0.9408 - val_ia: 0.2028 - val_loss: 0.2808 - val_mae: 0.4345 - val_rmse: 0.4484 - val_smape: 0.8352

Epoch 93/128

4586/4586 - 20s - 4ms/step - ia: 0.6218 - loss: 0.4030 - mae: 0.4873 - rmse: 0.6101 - smape: 0.9393 - val_ia: 0.2033 - val_loss: 0.2791 - val_mae: 0.4330 - val_rmse: 0.4470 - val_smape: 0.8328

Epoch 94/128

4586/4586 - 21s - 4ms/step - ia: 0.6232 - loss: 0.4008 - mae: 0.4861 - rmse: 0.6093 - smape: 0.9381 - val_ia: 0.2035 - val_loss: 0.2782 - val_mae: 0.4322 - val_rmse: 0.4462 - val_smape: 0.8316

Epoch 95/128

4586/4586 - 21s - 5ms/step - ia: 0.6261 - loss: 0.3947 - mae: 0.4821 - rmse: 0.6042 - smape: 0.9303 - val_ia: 0.2037 - val_loss: 0.2771 - val_mae: 0.4313 - val_rmse: 0.4452 - val_smape: 0.8298

Epoch 96/128

4586/4586 - 21s - 4ms/step - ia: 0.6240 - loss: 0.4006 - mae: 0.4859 - rmse: 0.6088 - smape: 0.9407 - val_ia: 0.2038 - val_loss: 0.2763 - val_mae: 0.4307 - val_rmse: 0.4446 - val_smape: 0.8286

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 9s - 32ms/step - ia: 0.6582 - loss: 0.3611 - mae: 0.4566 - rmse: 0.5632 - smape: 0.8871 - val_ia: 0.7811 - val_loss: 0.1397 - val_mae: 0.3028 - val_rmse: 0.3697 - val_smape: 0.6705

Epoch 2/128

287/287 - 4s - 14ms/step - ia: 0.8283 - loss: 0.1260 - mae: 0.2777 - rmse: 0.3536 - smape: 0.6009 - val_ia: 0.8064 - val_loss: 0.1109 - val_mae: 0.2709 - val_rmse: 0.3281 - val_smape: 0.6268

Epoch 3/128

287/287 - 5s - 17ms/step - ia: 0.8558 - loss: 0.0895 - mae: 0.2342 - rmse: 0.2979 - smape: 0.5332 - val_ia: 0.8310 - val_loss: 0.0889 - val_mae: 0.2360 - val_rmse: 0.2845 - val_smape: 0.5657

Epoch 4/128

287/287 - 8s - 28ms/step - ia: 0.8764 - loss: 0.0670 - mae: 0.2014 - rmse: 0.2581 - smape: 0.4769 - val_ia: 0.8568 - val_loss: 0.0643 - val_mae: 0.1984 - val_rmse: 0.2383 - val_smape: 0.5031

Epoch 5/128

287/287 - 7s - 25ms/step - ia: 0.8923 - loss: 0.0516 - mae: 0.1763 - rmse: 0.2264 - smape: 0.4251 - val_ia: 0.8929 - val_loss: 0.0347 - val_mae: 0.1461 - val_rmse: 0.1785 - val_smape: 0.4101

Epoch 6/128

287/287 - 7s - 23ms/step - ia: 0.9041 - loss: 0.0412 - mae: 0.1572 - rmse: 0.2021 - smape: 0.3884 - val_ia: 0.9161 - val_loss: 0.0213 - val_mae: 0.1135 - val_rmse: 0.1421 - val_smape: 0.3357

Epoch 7/128

287/287 - 10s - 36ms/step - ia: 0.9121 - loss: 0.0352 - mae: 0.1446 - rmse: 0.1868 - smape: 0.3635 - val_ia: 0.9328 - val_loss: 0.0147 - val_mae: 0.0909 - val_rmse: 0.1200 - val_smape: 0.2702

Epoch 8/128

287/287 - 9s - 32ms/step - ia: 0.9175 - loss: 0.0310 - mae: 0.1358 - rmse: 0.1754 - smape: 0.3461 - val_ia: 0.9353 - val_loss: 0.0139 - val_mae: 0.0872 - val_rmse: 0.1164 - val_smape: 0.2569

Epoch 9/128

287/287 - 5s - 18ms/step - ia: 0.9211 - loss: 0.0285 - mae: 0.1296 - rmse: 0.1680 - smape: 0.3322 - val_ia: 0.9381 - val_loss: 0.0129 - val_mae: 0.0836 - val_rmse: 0.1122 - val_smape: 0.2479

Epoch 10/128

287/287 - 7s - 23ms/step - ia: 0.9245 - loss: 0.0263 - mae: 0.1241 - rmse: 0.1615 - smape: 0.3209 - val_ia: 0.9410 - val_loss: 0.0123 - val_mae: 0.0793 - val_rmse: 0.1096 - val_smape: 0.2236

Epoch 11/128

287/287 - 7s - 24ms/step - ia: 0.9275 - loss: 0.0245 - mae: 0.1192 - rmse: 0.1557 - smape: 0.3107 - val_ia: 0.9380 - val_loss: 0.0131 - val_mae: 0.0830 - val_rmse: 0.1121 - val_smape: 0.2335

Epoch 12/128

287/287 - 7s - 23ms/step - ia: 0.9300 - loss: 0.0228 - mae: 0.1150 - rmse: 0.1502 - smape: 0.3036 - val_ia: 0.9407 - val_loss: 0.0121 - val_mae: 0.0796 - val_rmse: 0.1080 - val_smape: 0.2294

Epoch 13/128

287/287 - 10s - 36ms/step - ia: 0.9317 - loss: 0.0219 - mae: 0.1123 - rmse: 0.1473 - smape: 0.2961 - val_ia: 0.9443 - val_loss: 0.0112 - val_mae: 0.0750 - val_rmse: 0.1043 - val_smape: 0.2102

Epoch 14/128

287/287 - 10s - 34ms/step - ia: 0.9334 - loss: 0.0208 - mae: 0.1094 - rmse: 0.1432 - smape: 0.2889 - val_ia: 0.9398 - val_loss: 0.0123 - val_mae: 0.0804 - val_rmse: 0.1088 - val_smape: 0.2254

Epoch 15/128

287/287 - 11s - 38ms/step - ia: 0.9353 - loss: 0.0198 - mae: 0.1062 - rmse: 0.1400 - smape: 0.2818 - val_ia: 0.9434 - val_loss: 0.0112 - val_mae: 0.0757 - val_rmse: 0.1038 - val_smape: 0.2144

Epoch 16/128

287/287 - 7s - 24ms/step - ia: 0.9364 - loss: 0.0191 - mae: 0.1043 - rmse: 0.1375 - smape: 0.2773 - val_ia: 0.9418 - val_loss: 0.0115 - val_mae: 0.0779 - val_rmse: 0.1048 - val_smape: 0.2256

Epoch 17/128

287/287 - 10s - 35ms/step - ia: 0.9381 - loss: 0.0181 - mae: 0.1015 - rmse: 0.1339 - smape: 0.2694 - val_ia: 0.9463 - val_loss: 0.0103 - val_mae: 0.0719 - val_rmse: 0.0999 - val_smape: 0.1973

Epoch 18/128

287/287 - 7s - 24ms/step - ia: 0.9398 - loss: 0.0173 - mae: 0.0989 - rmse: 0.1308 - smape: 0.2637 - val_ia: 0.9483 - val_loss: 0.0096 - val_mae: 0.0694 - val_rmse: 0.0962 - val_smape: 0.1968

Epoch 19/128

287/287 - 6s - 22ms/step - ia: 0.9409 - loss: 0.0169 - mae: 0.0971 - rmse: 0.1291 - smape: 0.2605 - val_ia: 0.9481 - val_loss: 0.0095 - val_mae: 0.0697 - val_rmse: 0.0958 - val_smape: 0.2005

Epoch 20/128

287/287 - 6s - 21ms/step - ia: 0.9418 - loss: 0.0164 - mae: 0.0956 - rmse: 0.1270 - smape: 0.2568 - val_ia: 0.9500 - val_loss: 0.0089 - val_mae: 0.0674 - val_rmse: 0.0928 - val_smape: 0.1968

Epoch 21/128

287/287 - 11s - 38ms/step - ia: 0.9428 - loss: 0.0158 - mae: 0.0940 - rmse: 0.1248 - smape: 0.2525 - val_ia: 0.9492 - val_loss: 0.0091 - val_mae: 0.0682 - val_rmse: 0.0939 - val_smape: 0.1892

Epoch 22/128

287/287 - 7s - 23ms/step - ia: 0.9437 - loss: 0.0153 - mae: 0.0923 - rmse: 0.1229 - smape: 0.2500 - val_ia: 0.9469 - val_loss: 0.0095 - val_mae: 0.0711 - val_rmse: 0.0956 - val_smape: 0.2063

Epoch 23/128

287/287 - 10s - 36ms/step - ia: 0.9446 - loss: 0.0149 - mae: 0.0911 - rmse: 0.1211 - smape: 0.2495 - val_ia: 0.9505 - val_loss: 0.0085 - val_mae: 0.0667 - val_rmse: 0.0905 - val_smape: 0.1981

Epoch 24/128

287/287 - 9s - 33ms/step - ia: 0.9452 - loss: 0.0146 - mae: 0.0900 - rmse: 0.1198 - smape: 0.2443 - val_ia: 0.9490 - val_loss: 0.0088 - val_mae: 0.0684 - val_rmse: 0.0920 - val_smape: 0.1983

Epoch 25/128

287/287 - 7s - 23ms/step - ia: 0.9463 - loss: 0.0141 - mae: 0.0882 - rmse: 0.1177 - smape: 0.2390 - val_ia: 0.9530 - val_loss: 0.0077 - val_mae: 0.0633 - val_rmse: 0.0868 - val_smape: 0.1812

Epoch 26/128

287/287 - 7s - 23ms/step - ia: 0.9468 - loss: 0.0138 - mae: 0.0874 - rmse: 0.1167 - smape: 0.2370 - val_ia: 0.9459 - val_loss: 0.0094 - val_mae: 0.0722 - val_rmse: 0.0946 - val_smape: 0.2090

Epoch 27/128

287/287 - 10s - 36ms/step - ia: 0.9473 - loss: 0.0136 - mae: 0.0865 - rmse: 0.1156 - smape: 0.2364 - val_ia: 0.9481 - val_loss: 0.0087 - val_mae: 0.0696 - val_rmse: 0.0913 - val_smape: 0.2084

Epoch 28/128

287/287 - 10s - 36ms/step - ia: 0.9486 - loss: 0.0129 - mae: 0.0844 - rmse: 0.1129 - smape: 0.2313 - val_ia: 0.9495 - val_loss: 0.0084 - val_mae: 0.0676 - val_rmse: 0.0892 - val_smape: 0.2021

Epoch 29/128

287/287 - 10s - 35ms/step - ia: 0.9490 - loss: 0.0127 - mae: 0.0838 - rmse: 0.1119 - smape: 0.2297 - val_ia: 0.9467 - val_loss: 0.0089 - val_mae: 0.0715 - val_rmse: 0.0920 - val_smape: 0.2195

Epoch 30/128

287/287 - 11s - 37ms/step - ia: 0.9492 - loss: 0.0127 - mae: 0.0834 - rmse: 0.1116 - smape: 0.2297 - val_ia: 0.9523 - val_loss: 0.0076 - val_mae: 0.0640 - val_rmse: 0.0855 - val_smape: 0.1845

Epoch 31/128

287/287 - 7s - 23ms/step - ia: 0.9495 - loss: 0.0126 - mae: 0.0829 - rmse: 0.1112 - smape: 0.2257 - val_ia: 0.9519 - val_loss: 0.0076 - val_mae: 0.0645 - val_rmse: 0.0852 - val_smape: 0.1919

Epoch 32/128

287/287 - 7s - 24ms/step - ia: 0.9505 - loss: 0.0121 - mae: 0.0815 - rmse: 0.1091 - smape: 0.2231 - val_ia: 0.9497 - val_loss: 0.0081 - val_mae: 0.0672 - val_rmse: 0.0877 - val_smape: 0.1981

Epoch 33/128

287/287 - 10s - 36ms/step - ia: 0.9505 - loss: 0.0122 - mae: 0.0815 - rmse: 0.1095 - smape: 0.2229 - val_ia: 0.9515 - val_loss: 0.0077 - val_mae: 0.0649 - val_rmse: 0.0854 - val_smape: 0.1880

Epoch 34/128

287/287 - 11s - 37ms/step - ia: 0.9511 - loss: 0.0118 - mae: 0.0803 - rmse: 0.1076 - smape: 0.2201 - val_ia: 0.9576 - val_loss: 0.0063 - val_mae: 0.0575 - val_rmse: 0.0783 - val_smape: 0.1671

Epoch 35/128

287/287 - 7s - 24ms/step - ia: 0.9516 - loss: 0.0117 - mae: 0.0797 - rmse: 0.1071 - smape: 0.2177 - val_ia: 0.9536 - val_loss: 0.0071 - val_mae: 0.0622 - val_rmse: 0.0820 - val_smape: 0.1885

Epoch 36/128

287/287 - 7s - 25ms/step - ia: 0.9517 - loss: 0.0116 - mae: 0.0793 - rmse: 0.1065 - smape: 0.2158 - val_ia: 0.9536 - val_loss: 0.0071 - val_mae: 0.0622 - val_rmse: 0.0818 - val_smape: 0.1845

Epoch 37/128

287/287 - 7s - 23ms/step - ia: 0.9522 - loss: 0.0114 - mae: 0.0786 - rmse: 0.1059 - smape: 0.2140 - val_ia: 0.9565 - val_loss: 0.0064 - val_mae: 0.0585 - val_rmse: 0.0779 - val_smape: 0.1775

Epoch 38/128

287/287 - 7s - 23ms/step - ia: 0.9525 - loss: 0.0113 - mae: 0.0781 - rmse: 0.1050 - smape: 0.2108 - val_ia: 0.9550 - val_loss: 0.0067 - val_mae: 0.0603 - val_rmse: 0.0794 - val_smape: 0.1798

Epoch 39/128

287/287 - 9s - 33ms/step - ia: 0.9529 - loss: 0.0110 - mae: 0.0774 - rmse: 0.1041 - smape: 0.2126 - val_ia: 0.9550 - val_loss: 0.0066 - val_mae: 0.0603 - val_rmse: 0.0793 - val_smape: 0.1758

Epoch 40/128

287/287 - 7s - 23ms/step - ia: 0.9529 - loss: 0.0111 - mae: 0.0774 - rmse: 0.1041 - smape: 0.2126 - val_ia: 0.9560 - val_loss: 0.0064 - val_mae: 0.0590 - val_rmse: 0.0777 - val_smape: 0.1799

Epoch 41/128

287/287 - 10s - 35ms/step - ia: 0.9533 - loss: 0.0109 - mae: 0.0768 - rmse: 0.1032 - smape: 0.2116 - val_ia: 0.9566 - val_loss: 0.0062 - val_mae: 0.0582 - val_rmse: 0.0770 - val_smape: 0.1768

Epoch 42/128

287/287 - 10s - 36ms/step - ia: 0.9536 - loss: 0.0109 - mae: 0.0764 - rmse: 0.1032 - smape: 0.2088 - val_ia: 0.9564 - val_loss: 0.0063 - val_mae: 0.0584 - val_rmse: 0.0772 - val_smape: 0.1702

Epoch 43/128

287/287 - 6s - 23ms/step - ia: 0.9538 - loss: 0.0107 - mae: 0.0760 - rmse: 0.1023 - smape: 0.2078 - val_ia: 0.9568 - val_loss: 0.0062 - val_mae: 0.0579 - val_rmse: 0.0762 - val_smape: 0.1789

Epoch 44/128

287/287 - 6s - 22ms/step - ia: 0.9543 - loss: 0.0105 - mae: 0.0752 - rmse: 0.1014 - smape: 0.2059 - val_ia: 0.9595 - val_loss: 0.0056 - val_mae: 0.0545 - val_rmse: 0.0729 - val_smape: 0.1663

Epoch 45/128

287/287 - 6s - 21ms/step - ia: 0.9545 - loss: 0.0104 - mae: 0.0749 - rmse: 0.1009 - smape: 0.2066 - val_ia: 0.9595 - val_loss: 0.0055 - val_mae: 0.0545 - val_rmse: 0.0727 - val_smape: 0.1647

Epoch 46/128

287/287 - 7s - 23ms/step - ia: 0.9547 - loss: 0.0104 - mae: 0.0744 - rmse: 0.1007 - smape: 0.2047 - val_ia: 0.9560 - val_loss: 0.0063 - val_mae: 0.0588 - val_rmse: 0.0767 - val_smape: 0.1752

Epoch 47/128

287/287 - 7s - 25ms/step - ia: 0.9546 - loss: 0.0104 - mae: 0.0747 - rmse: 0.1009 - smape: 0.2042 - val_ia: 0.9581 - val_loss: 0.0058 - val_mae: 0.0561 - val_rmse: 0.0745 - val_smape: 0.1617

Epoch 48/128

287/287 - 10s - 35ms/step - ia: 0.9552 - loss: 0.0101 - mae: 0.0736 - rmse: 0.0993 - smape: 0.2018 - val_ia: 0.9582 - val_loss: 0.0058 - val_mae: 0.0560 - val_rmse: 0.0739 - val_smape: 0.1667

Epoch 49/128

287/287 - 10s - 35ms/step - ia: 0.9549 - loss: 0.0103 - mae: 0.0743 - rmse: 0.1006 - smape: 0.2022 - val_ia: 0.9578 - val_loss: 0.0059 - val_mae: 0.0565 - val_rmse: 0.0745 - val_smape: 0.1638

Epoch 50/128

287/287 - 6s - 19ms/step - ia: 0.9553 - loss: 0.0101 - mae: 0.0736 - rmse: 0.0995 - smape: 0.2021 - val_ia: 0.9589 - val_loss: 0.0056 - val_mae: 0.0551 - val_rmse: 0.0725 - val_smape: 0.1690

Epoch 51/128

287/287 - 7s - 23ms/step - ia: 0.9553 - loss: 0.0101 - mae: 0.0735 - rmse: 0.0995 - smape: 0.2019 - val_ia: 0.9586 - val_loss: 0.0057 - val_mae: 0.0555 - val_rmse: 0.0736 - val_smape: 0.1607

Epoch 52/128

287/287 - 10s - 35ms/step - ia: 0.9558 - loss: 0.0099 - mae: 0.0727 - rmse: 0.0986 - smape: 0.1979 - val_ia: 0.9613 - val_loss: 0.0051 - val_mae: 0.0521 - val_rmse: 0.0695 - val_smape: 0.1613

Epoch 53/128

287/287 - 7s - 23ms/step - ia: 0.9554 - loss: 0.0100 - mae: 0.0732 - rmse: 0.0990 - smape: 0.2016 - val_ia: 0.9566 - val_loss: 0.0060 - val_mae: 0.0580 - val_rmse: 0.0749 - val_smape: 0.1777

Epoch 54/128

287/287 - 7s - 24ms/step - ia: 0.9559 - loss: 0.0099 - mae: 0.0725 - rmse: 0.0984 - smape: 0.1988 - val_ia: 0.9581 - val_loss: 0.0057 - val_mae: 0.0561 - val_rmse: 0.0735 - val_smape: 0.1664

Epoch 55/128

287/287 - 7s - 23ms/step - ia: 0.9561 - loss: 0.0097 - mae: 0.0722 - rmse: 0.0973 - smape: 0.1999 - val_ia: 0.9611 - val_loss: 0.0051 - val_mae: 0.0522 - val_rmse: 0.0695 - val_smape: 0.1594

Epoch 56/128

287/287 - 6s - 20ms/step - ia: 0.9562 - loss: 0.0098 - mae: 0.0720 - rmse: 0.0977 - smape: 0.1987 - val_ia: 0.9596 - val_loss: 0.0054 - val_mae: 0.0542 - val_rmse: 0.0715 - val_smape: 0.1639

Epoch 57/128

287/287 - 6s - 23ms/step - ia: 0.9565 - loss: 0.0096 - mae: 0.0715 - rmse: 0.0970 - smape: 0.1969 - val_ia: 0.9627 - val_loss: 0.0048 - val_mae: 0.0502 - val_rmse: 0.0674 - val_smape: 0.1548

Epoch 58/128

287/287 - 10s - 36ms/step - ia: 0.9563 - loss: 0.0097 - mae: 0.0719 - rmse: 0.0976 - smape: 0.1976 - val_ia: 0.9622 - val_loss: 0.0048 - val_mae: 0.0508 - val_rmse: 0.0676 - val_smape: 0.1601

Epoch 59/128

287/287 - 7s - 23ms/step - ia: 0.9566 - loss: 0.0096 - mae: 0.0714 - rmse: 0.0970 - smape: 0.1968 - val_ia: 0.9604 - val_loss: 0.0052 - val_mae: 0.0529 - val_rmse: 0.0698 - val_smape: 0.1596

Epoch 60/128

287/287 - 7s - 23ms/step - ia: 0.9565 - loss: 0.0096 - mae: 0.0715 - rmse: 0.0969 - smape: 0.1959 - val_ia: 0.9580 - val_loss: 0.0056 - val_mae: 0.0561 - val_rmse: 0.0724 - val_smape: 0.1770

Epoch 61/128

287/287 - 7s - 23ms/step - ia: 0.9564 - loss: 0.0095 - mae: 0.0716 - rmse: 0.0965 - smape: 0.1954 - val_ia: 0.9611 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0693 - val_smape: 0.1538

Epoch 62/128

287/287 - 6s - 22ms/step - ia: 0.9567 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0965 - smape: 0.1964 - val_ia: 0.9570 - val_loss: 0.0059 - val_mae: 0.0574 - val_rmse: 0.0735 - val_smape: 0.1719

Epoch 63/128

287/287 - 6s - 21ms/step - ia: 0.9569 - loss: 0.0095 - mae: 0.0709 - rmse: 0.0961 - smape: 0.1952 - val_ia: 0.9629 - val_loss: 0.0047 - val_mae: 0.0499 - val_rmse: 0.0668 - val_smape: 0.1529

Epoch 64/128

287/287 - 7s - 23ms/step - ia: 0.9569 - loss: 0.0094 - mae: 0.0708 - rmse: 0.0958 - smape: 0.1940 - val_ia: 0.9575 - val_loss: 0.0057 - val_mae: 0.0567 - val_rmse: 0.0730 - val_smape: 0.1677

Epoch 65/128

287/287 - 7s - 23ms/step - ia: 0.9571 - loss: 0.0094 - mae: 0.0705 - rmse: 0.0958 - smape: 0.1935 - val_ia: 0.9599 - val_loss: 0.0052 - val_mae: 0.0536 - val_rmse: 0.0701 - val_smape: 0.1593

Epoch 66/128

287/287 - 10s - 35ms/step - ia: 0.9575 - loss: 0.0093 - mae: 0.0701 - rmse: 0.0950 - smape: 0.1929 - val_ia: 0.9620 - val_loss: 0.0048 - val_mae: 0.0509 - val_rmse: 0.0675 - val_smape: 0.1526

Epoch 67/128

287/287 - 7s - 23ms/step - ia: 0.9573 - loss: 0.0093 - mae: 0.0702 - rmse: 0.0953 - smape: 0.1947 - val_ia: 0.9616 - val_loss: 0.0049 - val_mae: 0.0514 - val_rmse: 0.0680 - val_smape: 0.1510

Epoch 68/128

287/287 - 7s - 23ms/step - ia: 0.9573 - loss: 0.0093 - mae: 0.0703 - rmse: 0.0952 - smape: 0.1929 - val_ia: 0.9628 - val_loss: 0.0047 - val_mae: 0.0499 - val_rmse: 0.0662 - val_smape: 0.1553

Epoch 69/128

287/287 - 6s - 20ms/step - ia: 0.9579 - loss: 0.0091 - mae: 0.0693 - rmse: 0.0943 - smape: 0.1921 - val_ia: 0.9626 - val_loss: 0.0047 - val_mae: 0.0501 - val_rmse: 0.0664 - val_smape: 0.1536

Epoch 70/128

287/287 - 11s - 38ms/step - ia: 0.9577 - loss: 0.0092 - mae: 0.0698 - rmse: 0.0947 - smape: 0.1913 - val_ia: 0.9629 - val_loss: 0.0046 - val_mae: 0.0498 - val_rmse: 0.0665 - val_smape: 0.1526

Epoch 71/128

287/287 - 7s - 24ms/step - ia: 0.9577 - loss: 0.0092 - mae: 0.0696 - rmse: 0.0947 - smape: 0.1934 - val_ia: 0.9601 - val_loss: 0.0051 - val_mae: 0.0532 - val_rmse: 0.0693 - val_smape: 0.1607

Epoch 72/128

287/287 - 7s - 23ms/step - ia: 0.9577 - loss: 0.0091 - mae: 0.0696 - rmse: 0.0945 - smape: 0.1898 - val_ia: 0.9616 - val_loss: 0.0049 - val_mae: 0.0514 - val_rmse: 0.0674 - val_smape: 0.1539

Epoch 73/128

287/287 - 7s - 23ms/step - ia: 0.9578 - loss: 0.0091 - mae: 0.0694 - rmse: 0.0943 - smape: 0.1901 - val_ia: 0.9636 - val_loss: 0.0045 - val_mae: 0.0488 - val_rmse: 0.0649 - val_smape: 0.1527

Epoch 74/128

287/287 - 7s - 23ms/step - ia: 0.9579 - loss: 0.0091 - mae: 0.0693 - rmse: 0.0941 - smape: 0.1925 - val_ia: 0.9650 - val_loss: 0.0042 - val_mae: 0.0471 - val_rmse: 0.0633 - val_smape: 0.1448

Epoch 75/128

287/287 - 5s - 17ms/step - ia: 0.9581 - loss: 0.0090 - mae: 0.0690 - rmse: 0.0939 - smape: 0.1900 - val_ia: 0.9618 - val_loss: 0.0048 - val_mae: 0.0511 - val_rmse: 0.0669 - val_smape: 0.1590

Epoch 76/128

287/287 - 6s - 22ms/step - ia: 0.9579 - loss: 0.0091 - mae: 0.0692 - rmse: 0.0941 - smape: 0.1899 - val_ia: 0.9635 - val_loss: 0.0045 - val_mae: 0.0490 - val_rmse: 0.0653 - val_smape: 0.1458

Epoch 77/128

287/287 - 10s - 36ms/step - ia: 0.9580 - loss: 0.0090 - mae: 0.0691 - rmse: 0.0937 - smape: 0.1899 - val_ia: 0.9637 - val_loss: 0.0045 - val_mae: 0.0486 - val_rmse: 0.0646 - val_smape: 0.1502

Epoch 78/128

287/287 - 7s - 23ms/step - ia: 0.9582 - loss: 0.0089 - mae: 0.0687 - rmse: 0.0933 - smape: 0.1899 - val_ia: 0.9595 - val_loss: 0.0052 - val_mae: 0.0541 - val_rmse: 0.0698 - val_smape: 0.1632

Epoch 79/128

287/287 - 7s - 23ms/step - ia: 0.9584 - loss: 0.0089 - mae: 0.0686 - rmse: 0.0933 - smape: 0.1869 - val_ia: 0.9610 - val_loss: 0.0049 - val_mae: 0.0521 - val_rmse: 0.0676 - val_smape: 0.1570

Epoch 80/128

287/287 - 10s - 36ms/step - ia: 0.9581 - loss: 0.0090 - mae: 0.0689 - rmse: 0.0934 - smape: 0.1888 - val_ia: 0.9640 - val_loss: 0.0044 - val_mae: 0.0482 - val_rmse: 0.0641 - val_smape: 0.1507

Epoch 81/128

287/287 - 6s - 22ms/step - ia: 0.9581 - loss: 0.0090 - mae: 0.0688 - rmse: 0.0938 - smape: 0.1893 - val_ia: 0.9636 - val_loss: 0.0044 - val_mae: 0.0488 - val_rmse: 0.0649 - val_smape: 0.1473

Epoch 82/128

287/287 - 7s - 24ms/step - ia: 0.9582 - loss: 0.0089 - mae: 0.0688 - rmse: 0.0934 - smape: 0.1902 - val_ia: 0.9641 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0637 - val_smape: 0.1485

Epoch 83/128

287/287 - 7s - 25ms/step - ia: 0.9587 - loss: 0.0088 - mae: 0.0679 - rmse: 0.0925 - smape: 0.1871 - val_ia: 0.9612 - val_loss: 0.0049 - val_mae: 0.0517 - val_rmse: 0.0676 - val_smape: 0.1510

Epoch 84/128

287/287 - 7s - 25ms/step - ia: 0.9585 - loss: 0.0088 - mae: 0.0683 - rmse: 0.0927 - smape: 0.1872 - val_ia: 0.9656 - val_loss: 0.0041 - val_mae: 0.0462 - val_rmse: 0.0620 - val_smape: 0.1425

Epoch 85/128

287/287 - 8s - 29ms/step - ia: 0.9590 - loss: 0.0087 - mae: 0.0676 - rmse: 0.0921 - smape: 0.1853 - val_ia: 0.9613 - val_loss: 0.0049 - val_mae: 0.0516 - val_rmse: 0.0670 - val_smape: 0.1608

Epoch 86/128

287/287 - 8s - 27ms/step - ia: 0.9585 - loss: 0.0088 - mae: 0.0682 - rmse: 0.0925 - smape: 0.1875 - val_ia: 0.9646 - val_loss: 0.0042 - val_mae: 0.0475 - val_rmse: 0.0633 - val_smape: 0.1452

Epoch 87/128

287/287 - 7s - 23ms/step - ia: 0.9589 - loss: 0.0086 - mae: 0.0675 - rmse: 0.0917 - smape: 0.1878 - val_ia: 0.9650 - val_loss: 0.0041 - val_mae: 0.0468 - val_rmse: 0.0626 - val_smape: 0.1434

Epoch 88/128

287/287 - 10s - 36ms/step - ia: 0.9586 - loss: 0.0088 - mae: 0.0681 - rmse: 0.0925 - smape: 0.1863 - val_ia: 0.9635 - val_loss: 0.0044 - val_mae: 0.0488 - val_rmse: 0.0644 - val_smape: 0.1454

Epoch 89/128

287/287 - 10s - 36ms/step - ia: 0.9588 - loss: 0.0086 - mae: 0.0678 - rmse: 0.0918 - smape: 0.1886 - val_ia: 0.9644 - val_loss: 0.0042 - val_mae: 0.0477 - val_rmse: 0.0635 - val_smape: 0.1493

Epoch 90/128

287/287 - 6s - 23ms/step - ia: 0.9588 - loss: 0.0087 - mae: 0.0677 - rmse: 0.0922 - smape: 0.1866 - val_ia: 0.9659 - val_loss: 0.0040 - val_mae: 0.0458 - val_rmse: 0.0616 - val_smape: 0.1436

Epoch 91/128

287/287 - 6s - 22ms/step - ia: 0.9587 - loss: 0.0087 - mae: 0.0680 - rmse: 0.0924 - smape: 0.1855 - val_ia: 0.9635 - val_loss: 0.0044 - val_mae: 0.0489 - val_rmse: 0.0646 - val_smape: 0.1459

Epoch 92/128

287/287 - 6s - 22ms/step - ia: 0.9592 - loss: 0.0086 - mae: 0.0671 - rmse: 0.0914 - smape: 0.1860 - val_ia: 0.9612 - val_loss: 0.0049 - val_mae: 0.0517 - val_rmse: 0.0671 - val_smape: 0.1519

Epoch 93/128

287/287 - 6s - 22ms/step - ia: 0.9591 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0920 - smape: 0.1864 - val_ia: 0.9655 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0619 - val_smape: 0.1425

Epoch 94/128

287/287 - 7s - 23ms/step - ia: 0.9587 - loss: 0.0088 - mae: 0.0679 - rmse: 0.0925 - smape: 0.1864 - val_ia: 0.9660 - val_loss: 0.0039 - val_mae: 0.0457 - val_rmse: 0.0613 - val_smape: 0.1428

Epoch 95/128

287/287 - 7s - 24ms/step - ia: 0.9591 - loss: 0.0086 - mae: 0.0674 - rmse: 0.0916 - smape: 0.1857 - val_ia: 0.9654 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0621 - val_smape: 0.1434

Epoch 96/128

287/287 - 6s - 23ms/step - ia: 0.9591 - loss: 0.0086 - mae: 0.0673 - rmse: 0.0916 - smape: 0.1840 - val_ia: 0.9647 - val_loss: 0.0042 - val_mae: 0.0473 - val_rmse: 0.0626 - val_smape: 0.1492

Epoch 97/128

287/287 - 10s - 36ms/step - ia: 0.9590 - loss: 0.0087 - mae: 0.0675 - rmse: 0.0918 - smape: 0.1854 - val_ia: 0.9622 - val_loss: 0.0046 - val_mae: 0.0507 - val_rmse: 0.0665 - val_smape: 0.1451


In [21]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}