Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [4]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(43800, 6)

In [10]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 1
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43788, 12, 6)
Dimensiones de Y: (43788, 1)

In [15]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30651, 12, 6)
Las dimensiones de testX son:  (8801, 12, 6)
Las dimensiones de valX son:  (4336, 12, 6)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30651, 1)
Las dimensiones de testY son:  (8801, 1)
Las dimensiones de valY son:  (4336, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 21s - 86ms/step - ia: 0.2313 - loss: 1.1224 - mae: 0.7976 - rmse: 1.0535 - smape: 1.5265 - val_ia: 0.2484 - val_loss: 0.9671 - val_mae: 0.7350 - val_rmse: 0.8737 - val_smape: 1.9485

Epoch 2/128

240/240 - 9s - 35ms/step - ia: 0.2047 - loss: 1.0736 - mae: 0.7753 - rmse: 1.0306 - smape: 1.5562 - val_ia: 0.2495 - val_loss: 0.9652 - val_mae: 0.7355 - val_rmse: 0.8737 - val_smape: 1.9824

Epoch 3/128

240/240 - 5s - 21ms/step - ia: 0.1826 - loss: 1.0428 - mae: 0.7656 - rmse: 1.0150 - smape: 1.5924 - val_ia: 0.2525 - val_loss: 0.9509 - val_mae: 0.7233 - val_rmse: 0.8625 - val_smape: 1.8196

Epoch 4/128

240/240 - 5s - 21ms/step - ia: 0.1909 - loss: 0.9957 - mae: 0.7429 - rmse: 0.9913 - smape: 1.5741 - val_ia: 0.2813 - val_loss: 0.8757 - val_mae: 0.6916 - val_rmse: 0.8265 - val_smape: 1.6550

Epoch 5/128

240/240 - 5s - 23ms/step - ia: 0.3084 - loss: 0.8507 - mae: 0.6708 - rmse: 0.9151 - smape: 1.3748 - val_ia: 0.3992 - val_loss: 0.6396 - val_mae: 0.5640 - val_rmse: 0.6900 - val_smape: 1.0862

Epoch 6/128

240/240 - 5s - 22ms/step - ia: 0.5014 - loss: 0.6589 - mae: 0.5750 - rmse: 0.8037 - smape: 1.0812 - val_ia: 0.4999 - val_loss: 0.4532 - val_mae: 0.4642 - val_rmse: 0.5831 - val_smape: 0.8269

Epoch 7/128

240/240 - 5s - 23ms/step - ia: 0.5826 - loss: 0.5574 - mae: 0.5284 - rmse: 0.7409 - smape: 0.9656 - val_ia: 0.5441 - val_loss: 0.3770 - val_mae: 0.4199 - val_rmse: 0.5339 - val_smape: 0.7582

Epoch 8/128

240/240 - 5s - 21ms/step - ia: 0.6147 - loss: 0.4979 - mae: 0.5001 - rmse: 0.6992 - smape: 0.9220 - val_ia: 0.5721 - val_loss: 0.3304 - val_mae: 0.3919 - val_rmse: 0.5015 - val_smape: 0.7245

Epoch 9/128

240/240 - 5s - 20ms/step - ia: 0.6304 - loss: 0.4682 - mae: 0.4833 - rmse: 0.6783 - smape: 0.9019 - val_ia: 0.5907 - val_loss: 0.3008 - val_mae: 0.3737 - val_rmse: 0.4806 - val_smape: 0.7028

Epoch 10/128

240/240 - 3s - 14ms/step - ia: 0.6367 - loss: 0.4565 - mae: 0.4770 - rmse: 0.6689 - smape: 0.8905 - val_ia: 0.5934 - val_loss: 0.2860 - val_mae: 0.3645 - val_rmse: 0.4697 - val_smape: 0.6967

Epoch 11/128

240/240 - 4s - 17ms/step - ia: 0.6478 - loss: 0.4337 - mae: 0.4650 - rmse: 0.6523 - smape: 0.8745 - val_ia: 0.6117 - val_loss: 0.2699 - val_mae: 0.3509 - val_rmse: 0.4548 - val_smape: 0.6766

Epoch 12/128

240/240 - 4s - 19ms/step - ia: 0.6561 - loss: 0.4176 - mae: 0.4552 - rmse: 0.6399 - smape: 0.8591 - val_ia: 0.6241 - val_loss: 0.2551 - val_mae: 0.3413 - val_rmse: 0.4435 - val_smape: 0.6635

Epoch 13/128

240/240 - 4s - 17ms/step - ia: 0.6655 - loss: 0.4052 - mae: 0.4458 - rmse: 0.6304 - smape: 0.8439 - val_ia: 0.6287 - val_loss: 0.2483 - val_mae: 0.3352 - val_rmse: 0.4372 - val_smape: 0.6592

Epoch 14/128

240/240 - 4s - 15ms/step - ia: 0.6700 - loss: 0.3954 - mae: 0.4399 - rmse: 0.6230 - smape: 0.8382 - val_ia: 0.6407 - val_loss: 0.2386 - val_mae: 0.3272 - val_rmse: 0.4284 - val_smape: 0.6461

Epoch 15/128

240/240 - 3s - 14ms/step - ia: 0.6703 - loss: 0.3966 - mae: 0.4385 - rmse: 0.6223 - smape: 0.8363 - val_ia: 0.6533 - val_loss: 0.2311 - val_mae: 0.3189 - val_rmse: 0.4204 - val_smape: 0.6339

Epoch 16/128

240/240 - 4s - 17ms/step - ia: 0.6782 - loss: 0.3863 - mae: 0.4301 - rmse: 0.6149 - smape: 0.8203 - val_ia: 0.6599 - val_loss: 0.2237 - val_mae: 0.3124 - val_rmse: 0.4126 - val_smape: 0.6270

Epoch 17/128

240/240 - 5s - 20ms/step - ia: 0.6833 - loss: 0.3731 - mae: 0.4239 - rmse: 0.6042 - smape: 0.8129 - val_ia: 0.6791 - val_loss: 0.2149 - val_mae: 0.3020 - val_rmse: 0.4035 - val_smape: 0.6089

Epoch 18/128

240/240 - 4s - 16ms/step - ia: 0.6878 - loss: 0.3716 - mae: 0.4202 - rmse: 0.6022 - smape: 0.8083 - val_ia: 0.6728 - val_loss: 0.2129 - val_mae: 0.3027 - val_rmse: 0.4027 - val_smape: 0.6182

Epoch 19/128

240/240 - 5s - 23ms/step - ia: 0.6893 - loss: 0.3602 - mae: 0.4171 - rmse: 0.5933 - smape: 0.8064 - val_ia: 0.6822 - val_loss: 0.2080 - val_mae: 0.2975 - val_rmse: 0.3982 - val_smape: 0.6109

Epoch 20/128

240/240 - 6s - 24ms/step - ia: 0.6911 - loss: 0.3586 - mae: 0.4144 - rmse: 0.5921 - smape: 0.8065 - val_ia: 0.6882 - val_loss: 0.2019 - val_mae: 0.2915 - val_rmse: 0.3907 - val_smape: 0.6020

Epoch 21/128

240/240 - 5s - 20ms/step - ia: 0.6936 - loss: 0.3507 - mae: 0.4109 - rmse: 0.5855 - smape: 0.8033 - val_ia: 0.7008 - val_loss: 0.1947 - val_mae: 0.2838 - val_rmse: 0.3834 - val_smape: 0.5880

Epoch 22/128

240/240 - 4s - 15ms/step - ia: 0.6970 - loss: 0.3437 - mae: 0.4076 - rmse: 0.5805 - smape: 0.8002 - val_ia: 0.7002 - val_loss: 0.1933 - val_mae: 0.2836 - val_rmse: 0.3831 - val_smape: 0.5914

Epoch 23/128

240/240 - 6s - 25ms/step - ia: 0.6988 - loss: 0.3451 - mae: 0.4053 - rmse: 0.5805 - smape: 0.7986 - val_ia: 0.6982 - val_loss: 0.1904 - val_mae: 0.2824 - val_rmse: 0.3800 - val_smape: 0.5932

Epoch 24/128

240/240 - 5s - 21ms/step - ia: 0.6988 - loss: 0.3396 - mae: 0.4034 - rmse: 0.5762 - smape: 0.8012 - val_ia: 0.7128 - val_loss: 0.1837 - val_mae: 0.2748 - val_rmse: 0.3737 - val_smape: 0.5779

Epoch 25/128

240/240 - 5s - 20ms/step - ia: 0.7015 - loss: 0.3384 - mae: 0.4012 - rmse: 0.5753 - smape: 0.7935 - val_ia: 0.7125 - val_loss: 0.1821 - val_mae: 0.2736 - val_rmse: 0.3720 - val_smape: 0.5809

Epoch 26/128

240/240 - 4s - 15ms/step - ia: 0.7020 - loss: 0.3382 - mae: 0.4000 - rmse: 0.5752 - smape: 0.7947 - val_ia: 0.7154 - val_loss: 0.1802 - val_mae: 0.2715 - val_rmse: 0.3695 - val_smape: 0.5789

Epoch 27/128

240/240 - 5s - 21ms/step - ia: 0.7040 - loss: 0.3291 - mae: 0.3970 - rmse: 0.5676 - smape: 0.7939 - val_ia: 0.7196 - val_loss: 0.1787 - val_mae: 0.2699 - val_rmse: 0.3688 - val_smape: 0.5765

Epoch 28/128

240/240 - 3s - 14ms/step - ia: 0.7082 - loss: 0.3255 - mae: 0.3930 - rmse: 0.5636 - smape: 0.7870 - val_ia: 0.7225 - val_loss: 0.1753 - val_mae: 0.2671 - val_rmse: 0.3654 - val_smape: 0.5723

Epoch 29/128

240/240 - 4s - 15ms/step - ia: 0.7087 - loss: 0.3235 - mae: 0.3925 - rmse: 0.5613 - smape: 0.7872 - val_ia: 0.7224 - val_loss: 0.1732 - val_mae: 0.2667 - val_rmse: 0.3647 - val_smape: 0.5734

Epoch 30/128

240/240 - 3s - 15ms/step - ia: 0.7097 - loss: 0.3221 - mae: 0.3905 - rmse: 0.5615 - smape: 0.7839 - val_ia: 0.7294 - val_loss: 0.1687 - val_mae: 0.2619 - val_rmse: 0.3593 - val_smape: 0.5624

Epoch 31/128

240/240 - 4s - 15ms/step - ia: 0.7102 - loss: 0.3163 - mae: 0.3902 - rmse: 0.5564 - smape: 0.7871 - val_ia: 0.7279 - val_loss: 0.1682 - val_mae: 0.2617 - val_rmse: 0.3586 - val_smape: 0.5664

Epoch 32/128

240/240 - 6s - 24ms/step - ia: 0.7139 - loss: 0.3133 - mae: 0.3854 - rmse: 0.5534 - smape: 0.7784 - val_ia: 0.7292 - val_loss: 0.1661 - val_mae: 0.2600 - val_rmse: 0.3560 - val_smape: 0.5638

Epoch 33/128

240/240 - 5s - 20ms/step - ia: 0.7121 - loss: 0.3151 - mae: 0.3883 - rmse: 0.5550 - smape: 0.7854 - val_ia: 0.7295 - val_loss: 0.1645 - val_mae: 0.2595 - val_rmse: 0.3551 - val_smape: 0.5635

Epoch 34/128

240/240 - 6s - 24ms/step - ia: 0.7169 - loss: 0.3073 - mae: 0.3820 - rmse: 0.5484 - smape: 0.7761 - val_ia: 0.7308 - val_loss: 0.1649 - val_mae: 0.2601 - val_rmse: 0.3570 - val_smape: 0.5662

Epoch 35/128

240/240 - 5s - 21ms/step - ia: 0.7134 - loss: 0.3141 - mae: 0.3853 - rmse: 0.5545 - smape: 0.7799 - val_ia: 0.7410 - val_loss: 0.1585 - val_mae: 0.2522 - val_rmse: 0.3486 - val_smape: 0.5461

Epoch 36/128

240/240 - 5s - 21ms/step - ia: 0.7168 - loss: 0.3072 - mae: 0.3816 - rmse: 0.5489 - smape: 0.7761 - val_ia: 0.7380 - val_loss: 0.1579 - val_mae: 0.2526 - val_rmse: 0.3472 - val_smape: 0.5486

Epoch 37/128

240/240 - 4s - 17ms/step - ia: 0.7174 - loss: 0.3048 - mae: 0.3807 - rmse: 0.5469 - smape: 0.7734 - val_ia: 0.7392 - val_loss: 0.1579 - val_mae: 0.2527 - val_rmse: 0.3484 - val_smape: 0.5485

Epoch 38/128

240/240 - 5s - 23ms/step - ia: 0.7185 - loss: 0.3035 - mae: 0.3795 - rmse: 0.5439 - smape: 0.7719 - val_ia: 0.7403 - val_loss: 0.1556 - val_mae: 0.2512 - val_rmse: 0.3461 - val_smape: 0.5460

Epoch 39/128

240/240 - 4s - 15ms/step - ia: 0.7201 - loss: 0.3018 - mae: 0.3780 - rmse: 0.5441 - smape: 0.7694 - val_ia: 0.7451 - val_loss: 0.1531 - val_mae: 0.2478 - val_rmse: 0.3423 - val_smape: 0.5415

Epoch 40/128

240/240 - 4s - 15ms/step - ia: 0.7223 - loss: 0.2969 - mae: 0.3754 - rmse: 0.5380 - smape: 0.7645 - val_ia: 0.7476 - val_loss: 0.1500 - val_mae: 0.2450 - val_rmse: 0.3390 - val_smape: 0.5372

Epoch 41/128

240/240 - 4s - 16ms/step - ia: 0.7220 - loss: 0.2993 - mae: 0.3762 - rmse: 0.5403 - smape: 0.7666 - val_ia: 0.7437 - val_loss: 0.1510 - val_mae: 0.2472 - val_rmse: 0.3404 - val_smape: 0.5420

Epoch 42/128

240/240 - 6s - 23ms/step - ia: 0.7230 - loss: 0.2969 - mae: 0.3738 - rmse: 0.5383 - smape: 0.7621 - val_ia: 0.7440 - val_loss: 0.1505 - val_mae: 0.2469 - val_rmse: 0.3399 - val_smape: 0.5414

Epoch 43/128

240/240 - 5s - 21ms/step - ia: 0.7220 - loss: 0.2957 - mae: 0.3751 - rmse: 0.5377 - smape: 0.7691 - val_ia: 0.7476 - val_loss: 0.1474 - val_mae: 0.2440 - val_rmse: 0.3369 - val_smape: 0.5347

Epoch 44/128

240/240 - 5s - 20ms/step - ia: 0.7234 - loss: 0.2940 - mae: 0.3742 - rmse: 0.5364 - smape: 0.7634 - val_ia: 0.7473 - val_loss: 0.1471 - val_mae: 0.2439 - val_rmse: 0.3365 - val_smape: 0.5357

Epoch 45/128

240/240 - 4s - 17ms/step - ia: 0.7252 - loss: 0.2938 - mae: 0.3721 - rmse: 0.5351 - smape: 0.7599 - val_ia: 0.7535 - val_loss: 0.1451 - val_mae: 0.2406 - val_rmse: 0.3342 - val_smape: 0.5271

Epoch 46/128

240/240 - 5s - 19ms/step - ia: 0.7292 - loss: 0.2838 - mae: 0.3680 - rmse: 0.5272 - smape: 0.7543 - val_ia: 0.7495 - val_loss: 0.1449 - val_mae: 0.2416 - val_rmse: 0.3335 - val_smape: 0.5328

Epoch 47/128

240/240 - 6s - 25ms/step - ia: 0.7260 - loss: 0.2957 - mae: 0.3703 - rmse: 0.5371 - smape: 0.7574 - val_ia: 0.7523 - val_loss: 0.1441 - val_mae: 0.2401 - val_rmse: 0.3323 - val_smape: 0.5290

Epoch 48/128

240/240 - 4s - 15ms/step - ia: 0.7259 - loss: 0.2924 - mae: 0.3702 - rmse: 0.5345 - smape: 0.7584 - val_ia: 0.7569 - val_loss: 0.1397 - val_mae: 0.2359 - val_rmse: 0.3275 - val_smape: 0.5221

Epoch 49/128

240/240 - 5s - 22ms/step - ia: 0.7273 - loss: 0.2902 - mae: 0.3696 - rmse: 0.5327 - smape: 0.7557 - val_ia: 0.7567 - val_loss: 0.1406 - val_mae: 0.2366 - val_rmse: 0.3286 - val_smape: 0.5226

Epoch 50/128

240/240 - 4s - 15ms/step - ia: 0.7285 - loss: 0.2865 - mae: 0.3678 - rmse: 0.5286 - smape: 0.7550 - val_ia: 0.7578 - val_loss: 0.1393 - val_mae: 0.2353 - val_rmse: 0.3267 - val_smape: 0.5208

Epoch 51/128

240/240 - 6s - 23ms/step - ia: 0.7312 - loss: 0.2849 - mae: 0.3651 - rmse: 0.5260 - smape: 0.7455 - val_ia: 0.7615 - val_loss: 0.1372 - val_mae: 0.2325 - val_rmse: 0.3239 - val_smape: 0.5159

Epoch 52/128

240/240 - 5s - 22ms/step - ia: 0.7311 - loss: 0.2839 - mae: 0.3647 - rmse: 0.5264 - smape: 0.7479 - val_ia: 0.7610 - val_loss: 0.1372 - val_mae: 0.2328 - val_rmse: 0.3241 - val_smape: 0.5147

Epoch 53/128

240/240 - 6s - 23ms/step - ia: 0.7320 - loss: 0.2812 - mae: 0.3641 - rmse: 0.5232 - smape: 0.7474 - val_ia: 0.7592 - val_loss: 0.1368 - val_mae: 0.2330 - val_rmse: 0.3235 - val_smape: 0.5162

Epoch 54/128

240/240 - 4s - 18ms/step - ia: 0.7337 - loss: 0.2751 - mae: 0.3613 - rmse: 0.5177 - smape: 0.7425 - val_ia: 0.7645 - val_loss: 0.1345 - val_mae: 0.2299 - val_rmse: 0.3212 - val_smape: 0.5095

Epoch 55/128

240/240 - 6s - 24ms/step - ia: 0.7342 - loss: 0.2802 - mae: 0.3619 - rmse: 0.5226 - smape: 0.7407 - val_ia: 0.7647 - val_loss: 0.1351 - val_mae: 0.2300 - val_rmse: 0.3214 - val_smape: 0.5112

Epoch 56/128

240/240 - 4s - 15ms/step - ia: 0.7340 - loss: 0.2784 - mae: 0.3610 - rmse: 0.5210 - smape: 0.7386 - val_ia: 0.7630 - val_loss: 0.1347 - val_mae: 0.2304 - val_rmse: 0.3213 - val_smape: 0.5114

Epoch 57/128

240/240 - 6s - 23ms/step - ia: 0.7374 - loss: 0.2739 - mae: 0.3574 - rmse: 0.5180 - smape: 0.7333 - val_ia: 0.7670 - val_loss: 0.1315 - val_mae: 0.2267 - val_rmse: 0.3168 - val_smape: 0.5062

Epoch 58/128

240/240 - 5s - 22ms/step - ia: 0.7342 - loss: 0.2804 - mae: 0.3611 - rmse: 0.5223 - smape: 0.7403 - val_ia: 0.7662 - val_loss: 0.1328 - val_mae: 0.2281 - val_rmse: 0.3191 - val_smape: 0.5074

Epoch 59/128

240/240 - 5s - 20ms/step - ia: 0.7344 - loss: 0.2786 - mae: 0.3609 - rmse: 0.5208 - smape: 0.7376 - val_ia: 0.7657 - val_loss: 0.1307 - val_mae: 0.2266 - val_rmse: 0.3161 - val_smape: 0.5049

Epoch 60/128

240/240 - 3s - 15ms/step - ia: 0.7364 - loss: 0.2756 - mae: 0.3584 - rmse: 0.5185 - smape: 0.7360 - val_ia: 0.7698 - val_loss: 0.1293 - val_mae: 0.2240 - val_rmse: 0.3138 - val_smape: 0.4992

Epoch 61/128

240/240 - 3s - 13ms/step - ia: 0.7373 - loss: 0.2717 - mae: 0.3578 - rmse: 0.5148 - smape: 0.7331 - val_ia: 0.7672 - val_loss: 0.1305 - val_mae: 0.2262 - val_rmse: 0.3164 - val_smape: 0.5050

Epoch 62/128

240/240 - 4s - 15ms/step - ia: 0.7352 - loss: 0.2804 - mae: 0.3600 - rmse: 0.5230 - smape: 0.7334 - val_ia: 0.7737 - val_loss: 0.1274 - val_mae: 0.2215 - val_rmse: 0.3119 - val_smape: 0.4949

Epoch 63/128

240/240 - 5s - 21ms/step - ia: 0.7386 - loss: 0.2711 - mae: 0.3566 - rmse: 0.5138 - smape: 0.7291 - val_ia: 0.7740 - val_loss: 0.1275 - val_mae: 0.2218 - val_rmse: 0.3128 - val_smape: 0.4952

Epoch 64/128

240/240 - 3s - 13ms/step - ia: 0.7378 - loss: 0.2734 - mae: 0.3568 - rmse: 0.5159 - smape: 0.7344 - val_ia: 0.7752 - val_loss: 0.1257 - val_mae: 0.2200 - val_rmse: 0.3099 - val_smape: 0.4934

Epoch 65/128

240/240 - 4s - 16ms/step - ia: 0.7391 - loss: 0.2696 - mae: 0.3559 - rmse: 0.5121 - smape: 0.7282 - val_ia: 0.7751 - val_loss: 0.1259 - val_mae: 0.2198 - val_rmse: 0.3098 - val_smape: 0.4918

Epoch 66/128

240/240 - 4s - 16ms/step - ia: 0.7405 - loss: 0.2710 - mae: 0.3540 - rmse: 0.5128 - smape: 0.7262 - val_ia: 0.7732 - val_loss: 0.1257 - val_mae: 0.2204 - val_rmse: 0.3095 - val_smape: 0.4940

Epoch 67/128

240/240 - 5s - 21ms/step - ia: 0.7387 - loss: 0.2719 - mae: 0.3555 - rmse: 0.5150 - smape: 0.7245 - val_ia: 0.7784 - val_loss: 0.1235 - val_mae: 0.2174 - val_rmse: 0.3073 - val_smape: 0.4890

Epoch 68/128

240/240 - 5s - 21ms/step - ia: 0.7409 - loss: 0.2682 - mae: 0.3535 - rmse: 0.5121 - smape: 0.7234 - val_ia: 0.7804 - val_loss: 0.1226 - val_mae: 0.2161 - val_rmse: 0.3064 - val_smape: 0.4855

Epoch 69/128

240/240 - 6s - 23ms/step - ia: 0.7412 - loss: 0.2665 - mae: 0.3533 - rmse: 0.5093 - smape: 0.7266 - val_ia: 0.7771 - val_loss: 0.1239 - val_mae: 0.2180 - val_rmse: 0.3075 - val_smape: 0.4921

Epoch 70/128

240/240 - 5s - 21ms/step - ia: 0.7424 - loss: 0.2625 - mae: 0.3514 - rmse: 0.5056 - smape: 0.7223 - val_ia: 0.7816 - val_loss: 0.1223 - val_mae: 0.2148 - val_rmse: 0.3044 - val_smape: 0.4855

Epoch 71/128

240/240 - 6s - 23ms/step - ia: 0.7380 - loss: 0.2728 - mae: 0.3560 - rmse: 0.5166 - smape: 0.7267 - val_ia: 0.7828 - val_loss: 0.1202 - val_mae: 0.2136 - val_rmse: 0.3030 - val_smape: 0.4815

Epoch 72/128

240/240 - 5s - 21ms/step - ia: 0.7416 - loss: 0.2710 - mae: 0.3524 - rmse: 0.5143 - smape: 0.7186 - val_ia: 0.7820 - val_loss: 0.1202 - val_mae: 0.2135 - val_rmse: 0.3027 - val_smape: 0.4832

Epoch 73/128

240/240 - 5s - 23ms/step - ia: 0.7444 - loss: 0.2674 - mae: 0.3498 - rmse: 0.5095 - smape: 0.7175 - val_ia: 0.7799 - val_loss: 0.1212 - val_mae: 0.2148 - val_rmse: 0.3036 - val_smape: 0.4858

Epoch 74/128

240/240 - 5s - 21ms/step - ia: 0.7420 - loss: 0.2674 - mae: 0.3519 - rmse: 0.5106 - smape: 0.7208 - val_ia: 0.7793 - val_loss: 0.1212 - val_mae: 0.2149 - val_rmse: 0.3035 - val_smape: 0.4861

Epoch 75/128

240/240 - 5s - 22ms/step - ia: 0.7433 - loss: 0.2632 - mae: 0.3506 - rmse: 0.5076 - smape: 0.7181 - val_ia: 0.7826 - val_loss: 0.1187 - val_mae: 0.2122 - val_rmse: 0.3007 - val_smape: 0.4805

Epoch 76/128

240/240 - 4s - 16ms/step - ia: 0.7421 - loss: 0.2687 - mae: 0.3520 - rmse: 0.5114 - smape: 0.7169 - val_ia: 0.7823 - val_loss: 0.1188 - val_mae: 0.2127 - val_rmse: 0.3016 - val_smape: 0.4817

Epoch 77/128

240/240 - 4s - 15ms/step - ia: 0.7436 - loss: 0.2676 - mae: 0.3495 - rmse: 0.5113 - smape: 0.7172 - val_ia: 0.7834 - val_loss: 0.1179 - val_mae: 0.2116 - val_rmse: 0.3002 - val_smape: 0.4796

Epoch 78/128

240/240 - 5s - 21ms/step - ia: 0.7433 - loss: 0.2651 - mae: 0.3500 - rmse: 0.5082 - smape: 0.7190 - val_ia: 0.7842 - val_loss: 0.1181 - val_mae: 0.2108 - val_rmse: 0.2993 - val_smape: 0.4787

Epoch 79/128

240/240 - 3s - 13ms/step - ia: 0.7438 - loss: 0.2645 - mae: 0.3495 - rmse: 0.5065 - smape: 0.7145 - val_ia: 0.7844 - val_loss: 0.1180 - val_mae: 0.2106 - val_rmse: 0.2988 - val_smape: 0.4781

Epoch 80/128

240/240 - 5s - 22ms/step - ia: 0.7436 - loss: 0.2651 - mae: 0.3494 - rmse: 0.5078 - smape: 0.7168 - val_ia: 0.7865 - val_loss: 0.1162 - val_mae: 0.2089 - val_rmse: 0.2973 - val_smape: 0.4762

Epoch 81/128

240/240 - 5s - 22ms/step - ia: 0.7442 - loss: 0.2618 - mae: 0.3496 - rmse: 0.5064 - smape: 0.7178 - val_ia: 0.7858 - val_loss: 0.1165 - val_mae: 0.2095 - val_rmse: 0.2979 - val_smape: 0.4777

Epoch 82/128

240/240 - 5s - 22ms/step - ia: 0.7444 - loss: 0.2632 - mae: 0.3490 - rmse: 0.5059 - smape: 0.7130 - val_ia: 0.7881 - val_loss: 0.1149 - val_mae: 0.2076 - val_rmse: 0.2958 - val_smape: 0.4744

Epoch 83/128

240/240 - 5s - 22ms/step - ia: 0.7468 - loss: 0.2618 - mae: 0.3468 - rmse: 0.5043 - smape: 0.7112 - val_ia: 0.7898 - val_loss: 0.1147 - val_mae: 0.2066 - val_rmse: 0.2954 - val_smape: 0.4729

Epoch 84/128

240/240 - 5s - 21ms/step - ia: 0.7464 - loss: 0.2597 - mae: 0.3472 - rmse: 0.5032 - smape: 0.7097 - val_ia: 0.7861 - val_loss: 0.1155 - val_mae: 0.2088 - val_rmse: 0.2966 - val_smape: 0.4774

Epoch 85/128

240/240 - 4s - 16ms/step - ia: 0.7461 - loss: 0.2595 - mae: 0.3468 - rmse: 0.5031 - smape: 0.7088 - val_ia: 0.7881 - val_loss: 0.1138 - val_mae: 0.2069 - val_rmse: 0.2943 - val_smape: 0.4735

Epoch 86/128

240/240 - 5s - 22ms/step - ia: 0.7466 - loss: 0.2606 - mae: 0.3473 - rmse: 0.5030 - smape: 0.7124 - val_ia: 0.7852 - val_loss: 0.1138 - val_mae: 0.2084 - val_rmse: 0.2951 - val_smape: 0.4774

Epoch 87/128

240/240 - 5s - 22ms/step - ia: 0.7485 - loss: 0.2560 - mae: 0.3437 - rmse: 0.4988 - smape: 0.7104 - val_ia: 0.7898 - val_loss: 0.1133 - val_mae: 0.2059 - val_rmse: 0.2936 - val_smape: 0.4724

Epoch 88/128

240/240 - 5s - 21ms/step - ia: 0.7466 - loss: 0.2605 - mae: 0.3469 - rmse: 0.5038 - smape: 0.7131 - val_ia: 0.7870 - val_loss: 0.1142 - val_mae: 0.2077 - val_rmse: 0.2956 - val_smape: 0.4760

Epoch 89/128

240/240 - 5s - 21ms/step - ia: 0.7461 - loss: 0.2608 - mae: 0.3459 - rmse: 0.5042 - smape: 0.7076 - val_ia: 0.7875 - val_loss: 0.1128 - val_mae: 0.2068 - val_rmse: 0.2938 - val_smape: 0.4743

Epoch 90/128

240/240 - 3s - 14ms/step - ia: 0.7482 - loss: 0.2553 - mae: 0.3436 - rmse: 0.4982 - smape: 0.7093 - val_ia: 0.7868 - val_loss: 0.1138 - val_mae: 0.2076 - val_rmse: 0.2945 - val_smape: 0.4757

Epoch 91/128

240/240 - 3s - 13ms/step - ia: 0.7473 - loss: 0.2577 - mae: 0.3451 - rmse: 0.5021 - smape: 0.7101 - val_ia: 0.7912 - val_loss: 0.1122 - val_mae: 0.2046 - val_rmse: 0.2922 - val_smape: 0.4705

Epoch 92/128

240/240 - 6s - 23ms/step - ia: 0.7503 - loss: 0.2556 - mae: 0.3423 - rmse: 0.4979 - smape: 0.6998 - val_ia: 0.7880 - val_loss: 0.1132 - val_mae: 0.2066 - val_rmse: 0.2938 - val_smape: 0.4742

Epoch 93/128

240/240 - 5s - 23ms/step - ia: 0.7494 - loss: 0.2559 - mae: 0.3425 - rmse: 0.4993 - smape: 0.7084 - val_ia: 0.7931 - val_loss: 0.1114 - val_mae: 0.2032 - val_rmse: 0.2911 - val_smape: 0.4681

Epoch 94/128

240/240 - 4s - 16ms/step - ia: 0.7488 - loss: 0.2555 - mae: 0.3439 - rmse: 0.4987 - smape: 0.7069 - val_ia: 0.7927 - val_loss: 0.1115 - val_mae: 0.2035 - val_rmse: 0.2910 - val_smape: 0.4688

Epoch 95/128

240/240 - 5s - 22ms/step - ia: 0.7498 - loss: 0.2505 - mae: 0.3424 - rmse: 0.4940 - smape: 0.7046 - val_ia: 0.7912 - val_loss: 0.1120 - val_mae: 0.2048 - val_rmse: 0.2923 - val_smape: 0.4724

Epoch 96/128

240/240 - 5s - 21ms/step - ia: 0.7473 - loss: 0.2580 - mae: 0.3452 - rmse: 0.5002 - smape: 0.7081 - val_ia: 0.7877 - val_loss: 0.1127 - val_mae: 0.2068 - val_rmse: 0.2932 - val_smape: 0.4752

Epoch 97/128

240/240 - 3s - 14ms/step - ia: 0.7520 - loss: 0.2498 - mae: 0.3395 - rmse: 0.4931 - smape: 0.7024 - val_ia: 0.7912 - val_loss: 0.1097 - val_mae: 0.2036 - val_rmse: 0.2901 - val_smape: 0.4699

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 54s - 28ms/step - ia: 0.7792 - loss: 0.2039 - mae: 0.2809 - rmse: 0.3988 - smape: 0.6170 - val_ia: 0.6545 - val_loss: 0.0595 - val_mae: 0.1454 - val_rmse: 0.1990 - val_smape: 0.3828

Epoch 2/128

1916/1916 - 44s - 23ms/step - ia: 0.8856 - loss: 0.0689 - mae: 0.1558 - rmse: 0.2337 - smape: 0.3883 - val_ia: 0.6546 - val_loss: 0.0629 - val_mae: 0.1483 - val_rmse: 0.2032 - val_smape: 0.3854

Epoch 3/128

1916/1916 - 81s - 42ms/step - ia: 0.8902 - loss: 0.0670 - mae: 0.1504 - rmse: 0.2287 - smape: 0.3757 - val_ia: 0.6929 - val_loss: 0.0581 - val_mae: 0.1348 - val_rmse: 0.1891 - val_smape: 0.3513

Epoch 4/128

1916/1916 - 84s - 44ms/step - ia: 0.8926 - loss: 0.0638 - mae: 0.1459 - rmse: 0.2234 - smape: 0.3683 - val_ia: 0.6508 - val_loss: 0.0563 - val_mae: 0.1427 - val_rmse: 0.1931 - val_smape: 0.3703

Epoch 5/128

1916/1916 - 48s - 25ms/step - ia: 0.8927 - loss: 0.0633 - mae: 0.1461 - rmse: 0.2227 - smape: 0.3680 - val_ia: 0.6934 - val_loss: 0.0543 - val_mae: 0.1303 - val_rmse: 0.1834 - val_smape: 0.3510

Epoch 6/128

1916/1916 - 79s - 41ms/step - ia: 0.8934 - loss: 0.0643 - mae: 0.1456 - rmse: 0.2238 - smape: 0.3656 - val_ia: 0.6734 - val_loss: 0.0540 - val_mae: 0.1354 - val_rmse: 0.1855 - val_smape: 0.3578

Epoch 7/128

1916/1916 - 47s - 25ms/step - ia: 0.8962 - loss: 0.0612 - mae: 0.1417 - rmse: 0.2183 - smape: 0.3591 - val_ia: 0.6660 - val_loss: 0.0540 - val_mae: 0.1366 - val_rmse: 0.1883 - val_smape: 0.3656

Epoch 8/128

1916/1916 - 47s - 24ms/step - ia: 0.8945 - loss: 0.0630 - mae: 0.1440 - rmse: 0.2210 - smape: 0.3625 - val_ia: 0.6831 - val_loss: 0.0571 - val_mae: 0.1377 - val_rmse: 0.1882 - val_smape: 0.3578

Epoch 9/128

1916/1916 - 46s - 24ms/step - ia: 0.8972 - loss: 0.0601 - mae: 0.1407 - rmse: 0.2170 - smape: 0.3588 - val_ia: 0.6515 - val_loss: 0.0544 - val_mae: 0.1401 - val_rmse: 0.1893 - val_smape: 0.3659

Epoch 10/128

1916/1916 - 46s - 24ms/step - ia: 0.8961 - loss: 0.0600 - mae: 0.1414 - rmse: 0.2174 - smape: 0.3602 - val_ia: 0.7037 - val_loss: 0.0530 - val_mae: 0.1281 - val_rmse: 0.1821 - val_smape: 0.3439

Epoch 11/128

1916/1916 - 84s - 44ms/step - ia: 0.8968 - loss: 0.0602 - mae: 0.1413 - rmse: 0.2156 - smape: 0.3590 - val_ia: 0.7021 - val_loss: 0.0526 - val_mae: 0.1274 - val_rmse: 0.1813 - val_smape: 0.3422

Epoch 12/128

1916/1916 - 81s - 42ms/step - ia: 0.8970 - loss: 0.0592 - mae: 0.1403 - rmse: 0.2158 - smape: 0.3574 - val_ia: 0.7039 - val_loss: 0.0531 - val_mae: 0.1281 - val_rmse: 0.1825 - val_smape: 0.3462

Epoch 13/128

1916/1916 - 45s - 24ms/step - ia: 0.8969 - loss: 0.0592 - mae: 0.1403 - rmse: 0.2153 - smape: 0.3578 - val_ia: 0.7031 - val_loss: 0.0532 - val_mae: 0.1273 - val_rmse: 0.1809 - val_smape: 0.3424

Epoch 14/128

1916/1916 - 80s - 42ms/step - ia: 0.8975 - loss: 0.0595 - mae: 0.1401 - rmse: 0.2156 - smape: 0.3577 - val_ia: 0.6929 - val_loss: 0.0537 - val_mae: 0.1310 - val_rmse: 0.1821 - val_smape: 0.3470

Epoch 15/128

1916/1916 - 44s - 23ms/step - ia: 0.8977 - loss: 0.0586 - mae: 0.1398 - rmse: 0.2140 - smape: 0.3578 - val_ia: 0.7057 - val_loss: 0.0540 - val_mae: 0.1284 - val_rmse: 0.1823 - val_smape: 0.3419

Epoch 16/128

1916/1916 - 83s - 43ms/step - ia: 0.8983 - loss: 0.0580 - mae: 0.1391 - rmse: 0.2140 - smape: 0.3571 - val_ia: 0.7011 - val_loss: 0.0534 - val_mae: 0.1304 - val_rmse: 0.1837 - val_smape: 0.3450

Epoch 17/128

1916/1916 - 83s - 43ms/step - ia: 0.8981 - loss: 0.0578 - mae: 0.1391 - rmse: 0.2128 - smape: 0.3566 - val_ia: 0.6647 - val_loss: 0.0540 - val_mae: 0.1378 - val_rmse: 0.1887 - val_smape: 0.3669

Epoch 18/128

1916/1916 - 45s - 24ms/step - ia: 0.8988 - loss: 0.0573 - mae: 0.1386 - rmse: 0.2125 - smape: 0.3562 - val_ia: 0.6875 - val_loss: 0.0533 - val_mae: 0.1315 - val_rmse: 0.1830 - val_smape: 0.3519

Epoch 19/128

1916/1916 - 46s - 24ms/step - ia: 0.8991 - loss: 0.0569 - mae: 0.1379 - rmse: 0.2116 - smape: 0.3554 - val_ia: 0.6551 - val_loss: 0.0591 - val_mae: 0.1437 - val_rmse: 0.1941 - val_smape: 0.3693

Epoch 20/128

1916/1916 - 46s - 24ms/step - ia: 0.8990 - loss: 0.0567 - mae: 0.1378 - rmse: 0.2122 - smape: 0.3531 - val_ia: 0.6750 - val_loss: 0.0541 - val_mae: 0.1359 - val_rmse: 0.1852 - val_smape: 0.3555

Epoch 21/128

1916/1916 - 45s - 23ms/step - ia: 0.8986 - loss: 0.0565 - mae: 0.1379 - rmse: 0.2113 - smape: 0.3548 - val_ia: 0.7036 - val_loss: 0.0520 - val_mae: 0.1281 - val_rmse: 0.1804 - val_smape: 0.3456

Epoch 22/128

1916/1916 - 46s - 24ms/step - ia: 0.8996 - loss: 0.0562 - mae: 0.1376 - rmse: 0.2110 - smape: 0.3556 - val_ia: 0.6794 - val_loss: 0.0533 - val_mae: 0.1328 - val_rmse: 0.1858 - val_smape: 0.3583

Epoch 23/128

1916/1916 - 83s - 43ms/step - ia: 0.8997 - loss: 0.0562 - mae: 0.1370 - rmse: 0.2106 - smape: 0.3540 - val_ia: 0.6822 - val_loss: 0.0541 - val_mae: 0.1334 - val_rmse: 0.1854 - val_smape: 0.3581

Epoch 24/128

1916/1916 - 46s - 24ms/step - ia: 0.8999 - loss: 0.0553 - mae: 0.1368 - rmse: 0.2097 - smape: 0.3536 - val_ia: 0.6810 - val_loss: 0.0553 - val_mae: 0.1356 - val_rmse: 0.1860 - val_smape: 0.3543

Epoch 25/128

1916/1916 - 45s - 24ms/step - ia: 0.8998 - loss: 0.0552 - mae: 0.1372 - rmse: 0.2092 - smape: 0.3555 - val_ia: 0.7046 - val_loss: 0.0542 - val_mae: 0.1287 - val_rmse: 0.1820 - val_smape: 0.3435

Epoch 26/128

1916/1916 - 45s - 24ms/step - ia: 0.9010 - loss: 0.0545 - mae: 0.1356 - rmse: 0.2078 - smape: 0.3525 - val_ia: 0.6958 - val_loss: 0.0557 - val_mae: 0.1305 - val_rmse: 0.1843 - val_smape: 0.3468

Epoch 27/128

1916/1916 - 46s - 24ms/step - ia: 0.9003 - loss: 0.0549 - mae: 0.1360 - rmse: 0.2083 - smape: 0.3518 - val_ia: 0.6948 - val_loss: 0.0528 - val_mae: 0.1295 - val_rmse: 0.1814 - val_smape: 0.3459

Epoch 28/128

1916/1916 - 45s - 24ms/step - ia: 0.9012 - loss: 0.0542 - mae: 0.1353 - rmse: 0.2070 - smape: 0.3511 - val_ia: 0.6717 - val_loss: 0.0541 - val_mae: 0.1359 - val_rmse: 0.1870 - val_smape: 0.3597

Epoch 29/128

1916/1916 - 45s - 23ms/step - ia: 0.9003 - loss: 0.0537 - mae: 0.1356 - rmse: 0.2073 - smape: 0.3515 - val_ia: 0.6960 - val_loss: 0.0546 - val_mae: 0.1304 - val_rmse: 0.1837 - val_smape: 0.3470

Epoch 30/128

1916/1916 - 45s - 23ms/step - ia: 0.9016 - loss: 0.0531 - mae: 0.1349 - rmse: 0.2061 - smape: 0.3507 - val_ia: 0.6892 - val_loss: 0.0539 - val_mae: 0.1311 - val_rmse: 0.1846 - val_smape: 0.3508

Epoch 31/128

1916/1916 - 44s - 23ms/step - ia: 0.9016 - loss: 0.0526 - mae: 0.1346 - rmse: 0.2049 - smape: 0.3496 - val_ia: 0.6914 - val_loss: 0.0560 - val_mae: 0.1351 - val_rmse: 0.1878 - val_smape: 0.3521

Epoch 32/128

1916/1916 - 88s - 46ms/step - ia: 0.9011 - loss: 0.0525 - mae: 0.1349 - rmse: 0.2050 - smape: 0.3513 - val_ia: 0.6882 - val_loss: 0.0579 - val_mae: 0.1335 - val_rmse: 0.1852 - val_smape: 0.3485

Epoch 33/128

1916/1916 - 48s - 25ms/step - ia: 0.9017 - loss: 0.0515 - mae: 0.1341 - rmse: 0.2036 - smape: 0.3499 - val_ia: 0.6817 - val_loss: 0.0557 - val_mae: 0.1335 - val_rmse: 0.1855 - val_smape: 0.3539

Epoch 34/128

1916/1916 - 47s - 25ms/step - ia: 0.9021 - loss: 0.0516 - mae: 0.1338 - rmse: 0.2034 - smape: 0.3497 - val_ia: 0.6965 - val_loss: 0.0566 - val_mae: 0.1321 - val_rmse: 0.1845 - val_smape: 0.3501

Epoch 35/128

1916/1916 - 83s - 43ms/step - ia: 0.9022 - loss: 0.0514 - mae: 0.1334 - rmse: 0.2033 - smape: 0.3499 - val_ia: 0.6735 - val_loss: 0.0606 - val_mae: 0.1379 - val_rmse: 0.1901 - val_smape: 0.3578

Epoch 36/128

1916/1916 - 46s - 24ms/step - ia: 0.9026 - loss: 0.0503 - mae: 0.1330 - rmse: 0.2017 - smape: 0.3480 - val_ia: 0.6853 - val_loss: 0.0551 - val_mae: 0.1340 - val_rmse: 0.1848 - val_smape: 0.3535

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:19 1s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

 17%|█▋        | 2/12 [44:39<4:04:41, 1468.20s/trial, best loss: 0.03682275219635514]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 58s - 15ms/step - ia: 0.2175 - loss: 0.9878 - mae: 0.7433 - rmse: 0.9253 - smape: 1.8976 - val_ia: 0.1876 - val_loss: 0.9482 - val_mae: 0.7276 - val_rmse: 0.7650 - val_smape: 1.8890

Epoch 2/128

3832/3832 - 39s - 10ms/step - ia: 0.2222 - loss: 0.9788 - mae: 0.7402 - rmse: 0.9220 - smape: 1.8785 - val_ia: 0.1881 - val_loss: 0.9369 - val_mae: 0.7239 - val_rmse: 0.7613 - val_smape: 1.8663

Epoch 3/128

3832/3832 - 40s - 11ms/step - ia: 0.2281 - loss: 0.9670 - mae: 0.7359 - rmse: 0.9162 - smape: 1.8545 - val_ia: 0.1886 - val_loss: 0.9236 - val_mae: 0.7193 - val_rmse: 0.7567 - val_smape: 1.8419

Epoch 4/128

3832/3832 - 37s - 10ms/step - ia: 0.2321 - loss: 0.9532 - mae: 0.7305 - rmse: 0.9091 - smape: 1.8228 - val_ia: 0.1894 - val_loss: 0.9083 - val_mae: 0.7136 - val_rmse: 0.7510 - val_smape: 1.8100

Epoch 5/128

3832/3832 - 39s - 10ms/step - ia: 0.2411 - loss: 0.9358 - mae: 0.7227 - rmse: 0.8991 - smape: 1.7785 - val_ia: 0.1903 - val_loss: 0.8905 - val_mae: 0.7062 - val_rmse: 0.7437 - val_smape: 1.7698

Epoch 6/128

3832/3832 - 42s - 11ms/step - ia: 0.2544 - loss: 0.9149 - mae: 0.7128 - rmse: 0.8885 - smape: 1.7284 - val_ia: 0.1919 - val_loss: 0.8694 - val_mae: 0.6964 - val_rmse: 0.7340 - val_smape: 1.7211

Epoch 7/128

3832/3832 - 37s - 10ms/step - ia: 0.2742 - loss: 0.8897 - mae: 0.6984 - rmse: 0.8747 - smape: 1.6624 - val_ia: 0.1938 - val_loss: 0.8460 - val_mae: 0.6842 - val_rmse: 0.7220 - val_smape: 1.6668

Epoch 8/128

3832/3832 - 42s - 11ms/step - ia: 0.2953 - loss: 0.8673 - mae: 0.6859 - rmse: 0.8641 - smape: 1.6032 - val_ia: 0.1955 - val_loss: 0.8229 - val_mae: 0.6723 - val_rmse: 0.7105 - val_smape: 1.6162

Epoch 9/128

3832/3832 - 37s - 10ms/step - ia: 0.3122 - loss: 0.8444 - mae: 0.6758 - rmse: 0.8496 - smape: 1.5535 - val_ia: 0.1978 - val_loss: 0.8008 - val_mae: 0.6630 - val_rmse: 0.7016 - val_smape: 1.5751

Epoch 10/128

3832/3832 - 33s - 8ms/step - ia: 0.3277 - loss: 0.8228 - mae: 0.6665 - rmse: 0.8408 - smape: 1.5121 - val_ia: 0.1996 - val_loss: 0.7779 - val_mae: 0.6545 - val_rmse: 0.6935 - val_smape: 1.5382

Epoch 11/128

3832/3832 - 44s - 11ms/step - ia: 0.3416 - loss: 0.8014 - mae: 0.6584 - rmse: 0.8296 - smape: 1.4752 - val_ia: 0.2012 - val_loss: 0.7534 - val_mae: 0.6457 - val_rmse: 0.6849 - val_smape: 1.5026

Epoch 12/128

3832/3832 - 37s - 10ms/step - ia: 0.3572 - loss: 0.7784 - mae: 0.6492 - rmse: 0.8182 - smape: 1.4377 - val_ia: 0.2018 - val_loss: 0.7265 - val_mae: 0.6360 - val_rmse: 0.6755 - val_smape: 1.4680

Epoch 13/128

3832/3832 - 36s - 9ms/step - ia: 0.3734 - loss: 0.7471 - mae: 0.6393 - rmse: 0.8031 - smape: 1.4039 - val_ia: 0.2024 - val_loss: 0.6971 - val_mae: 0.6251 - val_rmse: 0.6646 - val_smape: 1.4301

Epoch 14/128

3832/3832 - 35s - 9ms/step - ia: 0.3899 - loss: 0.7255 - mae: 0.6295 - rmse: 0.7915 - smape: 1.3662 - val_ia: 0.2032 - val_loss: 0.6665 - val_mae: 0.6133 - val_rmse: 0.6530 - val_smape: 1.3923

Epoch 15/128

3832/3832 - 33s - 9ms/step - ia: 0.4076 - loss: 0.6942 - mae: 0.6166 - rmse: 0.7750 - smape: 1.3269 - val_ia: 0.2043 - val_loss: 0.6342 - val_mae: 0.5996 - val_rmse: 0.6396 - val_smape: 1.3484

Epoch 16/128

3832/3832 - 34s - 9ms/step - ia: 0.4257 - loss: 0.6670 - mae: 0.6051 - rmse: 0.7618 - smape: 1.2842 - val_ia: 0.2056 - val_loss: 0.6015 - val_mae: 0.5848 - val_rmse: 0.6252 - val_smape: 1.3000

Epoch 17/128

3832/3832 - 34s - 9ms/step - ia: 0.4450 - loss: 0.6389 - mae: 0.5907 - rmse: 0.7442 - smape: 1.2412 - val_ia: 0.2074 - val_loss: 0.5702 - val_mae: 0.5695 - val_rmse: 0.6103 - val_smape: 1.2496

Epoch 18/128

3832/3832 - 35s - 9ms/step - ia: 0.4633 - loss: 0.6129 - mae: 0.5773 - rmse: 0.7286 - smape: 1.1983 - val_ia: 0.2099 - val_loss: 0.5405 - val_mae: 0.5534 - val_rmse: 0.5948 - val_smape: 1.1953

Epoch 19/128

3832/3832 - 33s - 9ms/step - ia: 0.4821 - loss: 0.5860 - mae: 0.5625 - rmse: 0.7132 - smape: 1.1521 - val_ia: 0.2117 - val_loss: 0.5145 - val_mae: 0.5381 - val_rmse: 0.5801 - val_smape: 1.1448

Epoch 20/128

3832/3832 - 33s - 9ms/step - ia: 0.4963 - loss: 0.5724 - mae: 0.5518 - rmse: 0.7020 - smape: 1.1145 - val_ia: 0.2127 - val_loss: 0.4931 - val_mae: 0.5242 - val_rmse: 0.5670 - val_smape: 1.0988

Epoch 21/128

3832/3832 - 43s - 11ms/step - ia: 0.5150 - loss: 0.5494 - mae: 0.5382 - rmse: 0.6866 - smape: 1.0740 - val_ia: 0.2135 - val_loss: 0.4756 - val_mae: 0.5120 - val_rmse: 0.5554 - val_smape: 1.0591

Epoch 22/128

3832/3832 - 41s - 11ms/step - ia: 0.5233 - loss: 0.5418 - mae: 0.5324 - rmse: 0.6813 - smape: 1.0511 - val_ia: 0.2149 - val_loss: 0.4619 - val_mae: 0.5022 - val_rmse: 0.5460 - val_smape: 1.0284

Epoch 23/128

3832/3832 - 34s - 9ms/step - ia: 0.5332 - loss: 0.5341 - mae: 0.5251 - rmse: 0.6759 - smape: 1.0264 - val_ia: 0.2155 - val_loss: 0.4514 - val_mae: 0.4941 - val_rmse: 0.5382 - val_smape: 1.0029

Epoch 24/128

3832/3832 - 33s - 9ms/step - ia: 0.5440 - loss: 0.5271 - mae: 0.5182 - rmse: 0.6690 - smape: 1.0054 - val_ia: 0.2159 - val_loss: 0.4433 - val_mae: 0.4875 - val_rmse: 0.5320 - val_smape: 0.9830

Epoch 25/128

3832/3832 - 33s - 9ms/step - ia: 0.5487 - loss: 0.5204 - mae: 0.5126 - rmse: 0.6640 - smape: 0.9898 - val_ia: 0.2163 - val_loss: 0.4361 - val_mae: 0.4814 - val_rmse: 0.5261 - val_smape: 0.9653

Epoch 26/128

3832/3832 - 42s - 11ms/step - ia: 0.5535 - loss: 0.5118 - mae: 0.5070 - rmse: 0.6576 - smape: 0.9778 - val_ia: 0.2166 - val_loss: 0.4300 - val_mae: 0.4764 - val_rmse: 0.5212 - val_smape: 0.9516

Epoch 27/128

3832/3832 - 42s - 11ms/step - ia: 0.5591 - loss: 0.5070 - mae: 0.5031 - rmse: 0.6557 - smape: 0.9643 - val_ia: 0.2168 - val_loss: 0.4245 - val_mae: 0.4717 - val_rmse: 0.5167 - val_smape: 0.9397

Epoch 28/128

3832/3832 - 40s - 10ms/step - ia: 0.5632 - loss: 0.5057 - mae: 0.5008 - rmse: 0.6538 - smape: 0.9599 - val_ia: 0.2171 - val_loss: 0.4195 - val_mae: 0.4675 - val_rmse: 0.5126 - val_smape: 0.9292

Epoch 29/128

3832/3832 - 38s - 10ms/step - ia: 0.5705 - loss: 0.4979 - mae: 0.4958 - rmse: 0.6484 - smape: 0.9461 - val_ia: 0.2174 - val_loss: 0.4145 - val_mae: 0.4633 - val_rmse: 0.5086 - val_smape: 0.9197

Epoch 30/128

3832/3832 - 37s - 10ms/step - ia: 0.5736 - loss: 0.4944 - mae: 0.4924 - rmse: 0.6449 - smape: 0.9391 - val_ia: 0.2179 - val_loss: 0.4095 - val_mae: 0.4590 - val_rmse: 0.5044 - val_smape: 0.9096

Epoch 31/128

3832/3832 - 35s - 9ms/step - ia: 0.5784 - loss: 0.4924 - mae: 0.4892 - rmse: 0.6435 - smape: 0.9309 - val_ia: 0.2185 - val_loss: 0.4050 - val_mae: 0.4550 - val_rmse: 0.5004 - val_smape: 0.9007

Epoch 32/128

3832/3832 - 35s - 9ms/step - ia: 0.5845 - loss: 0.4811 - mae: 0.4827 - rmse: 0.6352 - smape: 0.9192 - val_ia: 0.2191 - val_loss: 0.4005 - val_mae: 0.4512 - val_rmse: 0.4967 - val_smape: 0.8928

Epoch 33/128

3832/3832 - 34s - 9ms/step - ia: 0.5876 - loss: 0.4793 - mae: 0.4799 - rmse: 0.6325 - smape: 0.9130 - val_ia: 0.2196 - val_loss: 0.3960 - val_mae: 0.4474 - val_rmse: 0.4929 - val_smape: 0.8848

Epoch 34/128

3832/3832 - 35s - 9ms/step - ia: 0.5914 - loss: 0.4761 - mae: 0.4774 - rmse: 0.6298 - smape: 0.9049 - val_ia: 0.2200 - val_loss: 0.3916 - val_mae: 0.4438 - val_rmse: 0.4893 - val_smape: 0.8779

Epoch 35/128

3832/3832 - 35s - 9ms/step - ia: 0.5946 - loss: 0.4704 - mae: 0.4730 - rmse: 0.6244 - smape: 0.8984 - val_ia: 0.2204 - val_loss: 0.3872 - val_mae: 0.4402 - val_rmse: 0.4857 - val_smape: 0.8712

Epoch 36/128

3832/3832 - 38s - 10ms/step - ia: 0.5980 - loss: 0.4656 - mae: 0.4706 - rmse: 0.6229 - smape: 0.8935 - val_ia: 0.2210 - val_loss: 0.3828 - val_mae: 0.4367 - val_rmse: 0.4822 - val_smape: 0.8645

Epoch 37/128

3832/3832 - 39s - 10ms/step - ia: 0.6002 - loss: 0.4623 - mae: 0.4679 - rmse: 0.6201 - smape: 0.8890 - val_ia: 0.2217 - val_loss: 0.3788 - val_mae: 0.4332 - val_rmse: 0.4787 - val_smape: 0.8582

Epoch 38/128

3832/3832 - 34s - 9ms/step - ia: 0.6026 - loss: 0.4587 - mae: 0.4651 - rmse: 0.6175 - smape: 0.8827 - val_ia: 0.2225 - val_loss: 0.3745 - val_mae: 0.4297 - val_rmse: 0.4753 - val_smape: 0.8517

Epoch 39/128

3832/3832 - 39s - 10ms/step - ia: 0.6083 - loss: 0.4553 - mae: 0.4601 - rmse: 0.6128 - smape: 0.8772 - val_ia: 0.2236 - val_loss: 0.3703 - val_mae: 0.4264 - val_rmse: 0.4720 - val_smape: 0.8459

Epoch 40/128

3832/3832 - 38s - 10ms/step - ia: 0.6130 - loss: 0.4486 - mae: 0.4579 - rmse: 0.6087 - smape: 0.8724 - val_ia: 0.2246 - val_loss: 0.3661 - val_mae: 0.4230 - val_rmse: 0.4686 - val_smape: 0.8398

Epoch 41/128

3832/3832 - 40s - 10ms/step - ia: 0.6152 - loss: 0.4483 - mae: 0.4556 - rmse: 0.6086 - smape: 0.8670 - val_ia: 0.2254 - val_loss: 0.3617 - val_mae: 0.4198 - val_rmse: 0.4654 - val_smape: 0.8345

Epoch 42/128

3832/3832 - 37s - 10ms/step - ia: 0.6184 - loss: 0.4443 - mae: 0.4538 - rmse: 0.6050 - smape: 0.8649 - val_ia: 0.2269 - val_loss: 0.3574 - val_mae: 0.4162 - val_rmse: 0.4619 - val_smape: 0.8284

Epoch 43/128

3832/3832 - 36s - 9ms/step - ia: 0.6175 - loss: 0.4391 - mae: 0.4510 - rmse: 0.6022 - smape: 0.8610 - val_ia: 0.2283 - val_loss: 0.3531 - val_mae: 0.4128 - val_rmse: 0.4586 - val_smape: 0.8229

Epoch 44/128

3832/3832 - 30s - 8ms/step - ia: 0.6236 - loss: 0.4317 - mae: 0.4462 - rmse: 0.5968 - smape: 0.8526 - val_ia: 0.2297 - val_loss: 0.3488 - val_mae: 0.4094 - val_rmse: 0.4553 - val_smape: 0.8174

Epoch 45/128

3832/3832 - 29s - 7ms/step - ia: 0.6266 - loss: 0.4271 - mae: 0.4428 - rmse: 0.5943 - smape: 0.8482 - val_ia: 0.2311 - val_loss: 0.3443 - val_mae: 0.4056 - val_rmse: 0.4517 - val_smape: 0.8110

Epoch 46/128

3832/3832 - 29s - 8ms/step - ia: 0.6288 - loss: 0.4277 - mae: 0.4414 - rmse: 0.5924 - smape: 0.8434 - val_ia: 0.2317 - val_loss: 0.3401 - val_mae: 0.4029 - val_rmse: 0.4488 - val_smape: 0.8071

Epoch 47/128

3832/3832 - 30s - 8ms/step - ia: 0.6325 - loss: 0.4227 - mae: 0.4385 - rmse: 0.5891 - smape: 0.8393 - val_ia: 0.2329 - val_loss: 0.3358 - val_mae: 0.3994 - val_rmse: 0.4455 - val_smape: 0.8017

Epoch 48/128

3832/3832 - 31s - 8ms/step - ia: 0.6332 - loss: 0.4210 - mae: 0.4367 - rmse: 0.5868 - smape: 0.8353 - val_ia: 0.2340 - val_loss: 0.3312 - val_mae: 0.3961 - val_rmse: 0.4422 - val_smape: 0.7964

Epoch 49/128

3832/3832 - 30s - 8ms/step - ia: 0.6350 - loss: 0.4175 - mae: 0.4336 - rmse: 0.5841 - smape: 0.8321 - val_ia: 0.2347 - val_loss: 0.3269 - val_mae: 0.3929 - val_rmse: 0.4391 - val_smape: 0.7917

Epoch 50/128

3832/3832 - 31s - 8ms/step - ia: 0.6394 - loss: 0.4160 - mae: 0.4319 - rmse: 0.5824 - smape: 0.8298 - val_ia: 0.2355 - val_loss: 0.3227 - val_mae: 0.3897 - val_rmse: 0.4359 - val_smape: 0.7872

Epoch 51/128

3832/3832 - 32s - 8ms/step - ia: 0.6407 - loss: 0.4097 - mae: 0.4284 - rmse: 0.5776 - smape: 0.8231 - val_ia: 0.2364 - val_loss: 0.3182 - val_mae: 0.3866 - val_rmse: 0.4328 - val_smape: 0.7828

Epoch 52/128

3832/3832 - 28s - 7ms/step - ia: 0.6436 - loss: 0.4042 - mae: 0.4273 - rmse: 0.5754 - smape: 0.8239 - val_ia: 0.2378 - val_loss: 0.3136 - val_mae: 0.3832 - val_rmse: 0.4295 - val_smape: 0.7776

Epoch 53/128

3832/3832 - 27s - 7ms/step - ia: 0.6494 - loss: 0.3973 - mae: 0.4215 - rmse: 0.5700 - smape: 0.8137 - val_ia: 0.2388 - val_loss: 0.3092 - val_mae: 0.3802 - val_rmse: 0.4264 - val_smape: 0.7732

Epoch 54/128

3832/3832 - 27s - 7ms/step - ia: 0.6491 - loss: 0.3959 - mae: 0.4214 - rmse: 0.5694 - smape: 0.8146 - val_ia: 0.2399 - val_loss: 0.3051 - val_mae: 0.3771 - val_rmse: 0.4233 - val_smape: 0.7685

Epoch 55/128

3832/3832 - 25s - 7ms/step - ia: 0.6515 - loss: 0.3921 - mae: 0.4184 - rmse: 0.5652 - smape: 0.8132 - val_ia: 0.2410 - val_loss: 0.3007 - val_mae: 0.3739 - val_rmse: 0.4202 - val_smape: 0.7635

Epoch 56/128

3832/3832 - 27s - 7ms/step - ia: 0.6551 - loss: 0.3812 - mae: 0.4146 - rmse: 0.5593 - smape: 0.8061 - val_ia: 0.2422 - val_loss: 0.2961 - val_mae: 0.3706 - val_rmse: 0.4170 - val_smape: 0.7585

Epoch 57/128

3832/3832 - 35s - 9ms/step - ia: 0.6556 - loss: 0.3783 - mae: 0.4133 - rmse: 0.5580 - smape: 0.8053 - val_ia: 0.2436 - val_loss: 0.2920 - val_mae: 0.3675 - val_rmse: 0.4140 - val_smape: 0.7541

Epoch 58/128

3832/3832 - 28s - 7ms/step - ia: 0.6571 - loss: 0.3786 - mae: 0.4114 - rmse: 0.5563 - smape: 0.8019 - val_ia: 0.2448 - val_loss: 0.2880 - val_mae: 0.3649 - val_rmse: 0.4113 - val_smape: 0.7504

Epoch 59/128

3832/3832 - 27s - 7ms/step - ia: 0.6617 - loss: 0.3772 - mae: 0.4095 - rmse: 0.5537 - smape: 0.7998 - val_ia: 0.2460 - val_loss: 0.2842 - val_mae: 0.3622 - val_rmse: 0.4087 - val_smape: 0.7466

Epoch 60/128

3832/3832 - 27s - 7ms/step - ia: 0.6632 - loss: 0.3712 - mae: 0.4058 - rmse: 0.5502 - smape: 0.7939 - val_ia: 0.2471 - val_loss: 0.2807 - val_mae: 0.3595 - val_rmse: 0.4061 - val_smape: 0.7422

Epoch 61/128

3832/3832 - 29s - 7ms/step - ia: 0.6651 - loss: 0.3663 - mae: 0.4040 - rmse: 0.5467 - smape: 0.7902 - val_ia: 0.2480 - val_loss: 0.2774 - val_mae: 0.3572 - val_rmse: 0.4038 - val_smape: 0.7387

Epoch 62/128

3832/3832 - 29s - 8ms/step - ia: 0.6643 - loss: 0.3688 - mae: 0.4042 - rmse: 0.5479 - smape: 0.7931 - val_ia: 0.2489 - val_loss: 0.2743 - val_mae: 0.3549 - val_rmse: 0.4016 - val_smape: 0.7351

Epoch 63/128

3832/3832 - 40s - 11ms/step - ia: 0.6675 - loss: 0.3567 - mae: 0.3993 - rmse: 0.5384 - smape: 0.7841 - val_ia: 0.2499 - val_loss: 0.2713 - val_mae: 0.3526 - val_rmse: 0.3993 - val_smape: 0.7319

Epoch 64/128

3832/3832 - 27s - 7ms/step - ia: 0.6700 - loss: 0.3604 - mae: 0.3985 - rmse: 0.5403 - smape: 0.7814 - val_ia: 0.2510 - val_loss: 0.2683 - val_mae: 0.3501 - val_rmse: 0.3970 - val_smape: 0.7280

Epoch 65/128

3832/3832 - 24s - 6ms/step - ia: 0.6679 - loss: 0.3589 - mae: 0.3996 - rmse: 0.5413 - smape: 0.7842 - val_ia: 0.2517 - val_loss: 0.2658 - val_mae: 0.3482 - val_rmse: 0.3950 - val_smape: 0.7246

Epoch 66/128

3832/3832 - 24s - 6ms/step - ia: 0.6702 - loss: 0.3558 - mae: 0.3962 - rmse: 0.5366 - smape: 0.7800 - val_ia: 0.2526 - val_loss: 0.2632 - val_mae: 0.3463 - val_rmse: 0.3932 - val_smape: 0.7218

Epoch 67/128

3832/3832 - 30s - 8ms/step - ia: 0.6727 - loss: 0.3485 - mae: 0.3932 - rmse: 0.5328 - smape: 0.7769 - val_ia: 0.2538 - val_loss: 0.2605 - val_mae: 0.3442 - val_rmse: 0.3912 - val_smape: 0.7187

Epoch 68/128

3832/3832 - 26s - 7ms/step - ia: 0.6750 - loss: 0.3461 - mae: 0.3929 - rmse: 0.5323 - smape: 0.7759 - val_ia: 0.2546 - val_loss: 0.2585 - val_mae: 0.3427 - val_rmse: 0.3896 - val_smape: 0.7162

Epoch 69/128

3832/3832 - 24s - 6ms/step - ia: 0.6741 - loss: 0.3499 - mae: 0.3933 - rmse: 0.5350 - smape: 0.7725 - val_ia: 0.2555 - val_loss: 0.2561 - val_mae: 0.3409 - val_rmse: 0.3879 - val_smape: 0.7138

Epoch 70/128

3832/3832 - 25s - 7ms/step - ia: 0.6726 - loss: 0.3474 - mae: 0.3929 - rmse: 0.5314 - smape: 0.7737 - val_ia: 0.2565 - val_loss: 0.2539 - val_mae: 0.3391 - val_rmse: 0.3861 - val_smape: 0.7107

Epoch 71/128

3832/3832 - 35s - 9ms/step - ia: 0.6791 - loss: 0.3394 - mae: 0.3874 - rmse: 0.5254 - smape: 0.7687 - val_ia: 0.2575 - val_loss: 0.2516 - val_mae: 0.3372 - val_rmse: 0.3843 - val_smape: 0.7078

Epoch 72/128

3832/3832 - 33s - 9ms/step - ia: 0.6794 - loss: 0.3427 - mae: 0.3885 - rmse: 0.5285 - smape: 0.7665 - val_ia: 0.2579 - val_loss: 0.2496 - val_mae: 0.3359 - val_rmse: 0.3829 - val_smape: 0.7061

Epoch 73/128

3832/3832 - 33s - 9ms/step - ia: 0.6765 - loss: 0.3414 - mae: 0.3877 - rmse: 0.5269 - smape: 0.7695 - val_ia: 0.2588 - val_loss: 0.2475 - val_mae: 0.3342 - val_rmse: 0.3813 - val_smape: 0.7041

Epoch 74/128

3832/3832 - 29s - 8ms/step - ia: 0.6801 - loss: 0.3398 - mae: 0.3851 - rmse: 0.5223 - smape: 0.7620 - val_ia: 0.2597 - val_loss: 0.2456 - val_mae: 0.3325 - val_rmse: 0.3796 - val_smape: 0.7015

Epoch 75/128

3832/3832 - 41s - 11ms/step - ia: 0.6829 - loss: 0.3337 - mae: 0.3833 - rmse: 0.5196 - smape: 0.7611 - val_ia: 0.2602 - val_loss: 0.2434 - val_mae: 0.3314 - val_rmse: 0.3785 - val_smape: 0.7003

Epoch 76/128

3832/3832 - 29s - 8ms/step - ia: 0.6837 - loss: 0.3317 - mae: 0.3826 - rmse: 0.5193 - smape: 0.7634 - val_ia: 0.2610 - val_loss: 0.2417 - val_mae: 0.3300 - val_rmse: 0.3770 - val_smape: 0.6984

Epoch 77/128

3832/3832 - 29s - 8ms/step - ia: 0.6831 - loss: 0.3352 - mae: 0.3825 - rmse: 0.5201 - smape: 0.7604 - val_ia: 0.2623 - val_loss: 0.2396 - val_mae: 0.3281 - val_rmse: 0.3752 - val_smape: 0.6955

Epoch 78/128

3832/3832 - 29s - 8ms/step - ia: 0.6853 - loss: 0.3323 - mae: 0.3801 - rmse: 0.5183 - smape: 0.7543 - val_ia: 0.2631 - val_loss: 0.2378 - val_mae: 0.3267 - val_rmse: 0.3738 - val_smape: 0.6934

Epoch 79/128

3832/3832 - 30s - 8ms/step - ia: 0.6866 - loss: 0.3268 - mae: 0.3799 - rmse: 0.5149 - smape: 0.7567 - val_ia: 0.2640 - val_loss: 0.2356 - val_mae: 0.3252 - val_rmse: 0.3723 - val_smape: 0.6913

Epoch 80/128

3832/3832 - 31s - 8ms/step - ia: 0.6881 - loss: 0.3241 - mae: 0.3769 - rmse: 0.5124 - smape: 0.7517 - val_ia: 0.2646 - val_loss: 0.2340 - val_mae: 0.3241 - val_rmse: 0.3712 - val_smape: 0.6897

Epoch 81/128

3832/3832 - 31s - 8ms/step - ia: 0.6857 - loss: 0.3216 - mae: 0.3773 - rmse: 0.5113 - smape: 0.7521 - val_ia: 0.2655 - val_loss: 0.2320 - val_mae: 0.3226 - val_rmse: 0.3697 - val_smape: 0.6875

Epoch 82/128

3832/3832 - 30s - 8ms/step - ia: 0.6885 - loss: 0.3230 - mae: 0.3758 - rmse: 0.5095 - smape: 0.7534 - val_ia: 0.2664 - val_loss: 0.2307 - val_mae: 0.3215 - val_rmse: 0.3685 - val_smape: 0.6860

Epoch 83/128

3832/3832 - 27s - 7ms/step - ia: 0.6912 - loss: 0.3176 - mae: 0.3738 - rmse: 0.5076 - smape: 0.7507 - val_ia: 0.2674 - val_loss: 0.2289 - val_mae: 0.3200 - val_rmse: 0.3671 - val_smape: 0.6836

Epoch 84/128

3832/3832 - 28s - 7ms/step - ia: 0.6885 - loss: 0.3227 - mae: 0.3743 - rmse: 0.5083 - smape: 0.7486 - val_ia: 0.2679 - val_loss: 0.2276 - val_mae: 0.3190 - val_rmse: 0.3660 - val_smape: 0.6819

Epoch 85/128

3832/3832 - 27s - 7ms/step - ia: 0.6902 - loss: 0.3157 - mae: 0.3726 - rmse: 0.5053 - smape: 0.7463 - val_ia: 0.2690 - val_loss: 0.2255 - val_mae: 0.3174 - val_rmse: 0.3645 - val_smape: 0.6796

Epoch 86/128

3832/3832 - 27s - 7ms/step - ia: 0.6907 - loss: 0.3171 - mae: 0.3721 - rmse: 0.5057 - smape: 0.7447 - val_ia: 0.2699 - val_loss: 0.2239 - val_mae: 0.3161 - val_rmse: 0.3632 - val_smape: 0.6778

Epoch 87/128

3832/3832 - 28s - 7ms/step - ia: 0.6918 - loss: 0.3135 - mae: 0.3713 - rmse: 0.5036 - smape: 0.7449 - val_ia: 0.2709 - val_loss: 0.2223 - val_mae: 0.3148 - val_rmse: 0.3620 - val_smape: 0.6756

Epoch 88/128

3832/3832 - 38s - 10ms/step - ia: 0.6924 - loss: 0.3146 - mae: 0.3721 - rmse: 0.5047 - smape: 0.7470 - val_ia: 0.2715 - val_loss: 0.2206 - val_mae: 0.3138 - val_rmse: 0.3609 - val_smape: 0.6742

Epoch 89/128

3832/3832 - 25s - 6ms/step - ia: 0.6954 - loss: 0.3116 - mae: 0.3685 - rmse: 0.5005 - smape: 0.7404 - val_ia: 0.2724 - val_loss: 0.2191 - val_mae: 0.3127 - val_rmse: 0.3598 - val_smape: 0.6723

Epoch 90/128

3832/3832 - 25s - 6ms/step - ia: 0.6955 - loss: 0.3089 - mae: 0.3676 - rmse: 0.5005 - smape: 0.7418 - val_ia: 0.2734 - val_loss: 0.2172 - val_mae: 0.3114 - val_rmse: 0.3585 - val_smape: 0.6703

Epoch 91/128

3832/3832 - 32s - 8ms/step - ia: 0.6965 - loss: 0.3067 - mae: 0.3660 - rmse: 0.4970 - smape: 0.7385 - val_ia: 0.2746 - val_loss: 0.2156 - val_mae: 0.3101 - val_rmse: 0.3572 - val_smape: 0.6681

Epoch 92/128

3832/3832 - 29s - 7ms/step - ia: 0.6974 - loss: 0.3040 - mae: 0.3666 - rmse: 0.4969 - smape: 0.7389 - val_ia: 0.2759 - val_loss: 0.2138 - val_mae: 0.3083 - val_rmse: 0.3555 - val_smape: 0.6651

Epoch 93/128

3832/3832 - 25s - 6ms/step - ia: 0.6986 - loss: 0.3056 - mae: 0.3653 - rmse: 0.4967 - smape: 0.7355 - val_ia: 0.2763 - val_loss: 0.2128 - val_mae: 0.3078 - val_rmse: 0.3548 - val_smape: 0.6643

Epoch 94/128

3832/3832 - 45s - 12ms/step - ia: 0.6985 - loss: 0.3071 - mae: 0.3658 - rmse: 0.4957 - smape: 0.7367 - val_ia: 0.2776 - val_loss: 0.2112 - val_mae: 0.3063 - val_rmse: 0.3534 - val_smape: 0.6620

Epoch 95/128

3832/3832 - 34s - 9ms/step - ia: 0.6970 - loss: 0.3036 - mae: 0.3650 - rmse: 0.4954 - smape: 0.7354 - val_ia: 0.2781 - val_loss: 0.2103 - val_mae: 0.3056 - val_rmse: 0.3526 - val_smape: 0.6609

Epoch 96/128

3832/3832 - 32s - 8ms/step - ia: 0.6990 - loss: 0.2990 - mae: 0.3630 - rmse: 0.4921 - smape: 0.7340 - val_ia: 0.2792 - val_loss: 0.2083 - val_mae: 0.3041 - val_rmse: 0.3512 - val_smape: 0.6587

Epoch 97/128

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 31s - 33ms/step - ia: 0.2872 - loss: 0.8010 - mae: 0.6627 - rmse: 0.8719 - smape: 1.4902 - val_ia: 0.2810 - val_loss: 0.5212 - val_mae: 0.5467 - val_rmse: 0.6310 - val_smape: 1.2051

Epoch 2/128

958/958 - 17s - 18ms/step - ia: 0.5671 - loss: 0.4986 - mae: 0.5013 - rmse: 0.6860 - smape: 1.0231 - val_ia: 0.3277 - val_loss: 0.4020 - val_mae: 0.4529 - val_rmse: 0.5465 - val_smape: 0.9613

Epoch 3/128

958/958 - 16s - 17ms/step - ia: 0.6233 - loss: 0.4516 - mae: 0.4640 - rmse: 0.6538 - smape: 0.9318 - val_ia: 0.3512 - val_loss: 0.3806 - val_mae: 0.4312 - val_rmse: 0.5274 - val_smape: 0.9117

Epoch 4/128

958/958 - 16s - 17ms/step - ia: 0.6383 - loss: 0.4396 - mae: 0.4535 - rmse: 0.6431 - smape: 0.9049 - val_ia: 0.3633 - val_loss: 0.3693 - val_mae: 0.4218 - val_rmse: 0.5181 - val_smape: 0.8907

Epoch 5/128

958/958 - 17s - 18ms/step - ia: 0.6466 - loss: 0.4269 - mae: 0.4457 - rmse: 0.6348 - smape: 0.8900 - val_ia: 0.3731 - val_loss: 0.3581 - val_mae: 0.4139 - val_rmse: 0.5102 - val_smape: 0.8741

Epoch 6/128

958/958 - 17s - 18ms/step - ia: 0.6551 - loss: 0.4163 - mae: 0.4389 - rmse: 0.6260 - smape: 0.8747 - val_ia: 0.3787 - val_loss: 0.3484 - val_mae: 0.4079 - val_rmse: 0.5032 - val_smape: 0.8628

Epoch 7/128

958/958 - 16s - 17ms/step - ia: 0.6600 - loss: 0.4071 - mae: 0.4327 - rmse: 0.6192 - smape: 0.8636 - val_ia: 0.3864 - val_loss: 0.3377 - val_mae: 0.4009 - val_rmse: 0.4956 - val_smape: 0.8504

Epoch 8/128

958/958 - 17s - 18ms/step - ia: 0.6689 - loss: 0.3935 - mae: 0.4249 - rmse: 0.6090 - smape: 0.8507 - val_ia: 0.3910 - val_loss: 0.3280 - val_mae: 0.3953 - val_rmse: 0.4889 - val_smape: 0.8410

Epoch 9/128

958/958 - 17s - 18ms/step - ia: 0.6728 - loss: 0.3831 - mae: 0.4196 - rmse: 0.5997 - smape: 0.8428 - val_ia: 0.3973 - val_loss: 0.3169 - val_mae: 0.3885 - val_rmse: 0.4811 - val_smape: 0.8288

Epoch 10/128

958/958 - 19s - 20ms/step - ia: 0.6802 - loss: 0.3702 - mae: 0.4117 - rmse: 0.5905 - smape: 0.8284 - val_ia: 0.4081 - val_loss: 0.3053 - val_mae: 0.3793 - val_rmse: 0.4724 - val_smape: 0.8117

Epoch 11/128

958/958 - 17s - 18ms/step - ia: 0.6862 - loss: 0.3601 - mae: 0.4052 - rmse: 0.5807 - smape: 0.8180 - val_ia: 0.4103 - val_loss: 0.2953 - val_mae: 0.3751 - val_rmse: 0.4659 - val_smape: 0.8058

Epoch 12/128

958/958 - 17s - 18ms/step - ia: 0.6914 - loss: 0.3449 - mae: 0.3978 - rmse: 0.5696 - smape: 0.8083 - val_ia: 0.4212 - val_loss: 0.2826 - val_mae: 0.3657 - val_rmse: 0.4560 - val_smape: 0.7881

Epoch 13/128

958/958 - 16s - 16ms/step - ia: 0.6990 - loss: 0.3355 - mae: 0.3907 - rmse: 0.5614 - smape: 0.7967 - val_ia: 0.4323 - val_loss: 0.2704 - val_mae: 0.3573 - val_rmse: 0.4473 - val_smape: 0.7736

Epoch 14/128

958/958 - 22s - 23ms/step - ia: 0.7054 - loss: 0.3224 - mae: 0.3835 - rmse: 0.5496 - smape: 0.7825 - val_ia: 0.4396 - val_loss: 0.2596 - val_mae: 0.3500 - val_rmse: 0.4391 - val_smape: 0.7611

Epoch 15/128

958/958 - 17s - 18ms/step - ia: 0.7093 - loss: 0.3154 - mae: 0.3777 - rmse: 0.5430 - smape: 0.7722 - val_ia: 0.4506 - val_loss: 0.2494 - val_mae: 0.3418 - val_rmse: 0.4308 - val_smape: 0.7468

Epoch 16/128

958/958 - 16s - 16ms/step - ia: 0.7154 - loss: 0.3037 - mae: 0.3722 - rmse: 0.5335 - smape: 0.7647 - val_ia: 0.4583 - val_loss: 0.2410 - val_mae: 0.3359 - val_rmse: 0.4244 - val_smape: 0.7376

Epoch 17/128

958/958 - 17s - 18ms/step - ia: 0.7205 - loss: 0.2959 - mae: 0.3664 - rmse: 0.5256 - smape: 0.7548 - val_ia: 0.4645 - val_loss: 0.2342 - val_mae: 0.3309 - val_rmse: 0.4188 - val_smape: 0.7286

Epoch 18/128

958/958 - 17s - 18ms/step - ia: 0.7263 - loss: 0.2866 - mae: 0.3602 - rmse: 0.5178 - smape: 0.7410 - val_ia: 0.4723 - val_loss: 0.2277 - val_mae: 0.3255 - val_rmse: 0.4132 - val_smape: 0.7190

Epoch 19/128

958/958 - 16s - 16ms/step - ia: 0.7298 - loss: 0.2818 - mae: 0.3564 - rmse: 0.5131 - smape: 0.7403 - val_ia: 0.4798 - val_loss: 0.2226 - val_mae: 0.3207 - val_rmse: 0.4088 - val_smape: 0.7102

Epoch 20/128

958/958 - 17s - 18ms/step - ia: 0.7316 - loss: 0.2799 - mae: 0.3550 - rmse: 0.5110 - smape: 0.7326 - val_ia: 0.4808 - val_loss: 0.2192 - val_mae: 0.3193 - val_rmse: 0.4061 - val_smape: 0.7079

Epoch 21/128

958/958 - 17s - 18ms/step - ia: 0.7334 - loss: 0.2770 - mae: 0.3517 - rmse: 0.5082 - smape: 0.7277 - val_ia: 0.4891 - val_loss: 0.2148 - val_mae: 0.3142 - val_rmse: 0.4019 - val_smape: 0.6995

Epoch 22/128

958/958 - 16s - 16ms/step - ia: 0.7373 - loss: 0.2681 - mae: 0.3472 - rmse: 0.5000 - smape: 0.7232 - val_ia: 0.4978 - val_loss: 0.2109 - val_mae: 0.3097 - val_rmse: 0.3981 - val_smape: 0.6908

Epoch 23/128

958/958 - 17s - 18ms/step - ia: 0.7393 - loss: 0.2703 - mae: 0.3463 - rmse: 0.5031 - smape: 0.7169 - val_ia: 0.5013 - val_loss: 0.2081 - val_mae: 0.3071 - val_rmse: 0.3955 - val_smape: 0.6864

Epoch 24/128

958/958 - 18s - 18ms/step - ia: 0.7422 - loss: 0.2625 - mae: 0.3424 - rmse: 0.4937 - smape: 0.7130 - val_ia: 0.5046 - val_loss: 0.2047 - val_mae: 0.3047 - val_rmse: 0.3925 - val_smape: 0.6824

Epoch 25/128

958/958 - 20s - 20ms/step - ia: 0.7450 - loss: 0.2571 - mae: 0.3389 - rmse: 0.4892 - smape: 0.7063 - val_ia: 0.5083 - val_loss: 0.2017 - val_mae: 0.3020 - val_rmse: 0.3898 - val_smape: 0.6782

Epoch 26/128

958/958 - 17s - 18ms/step - ia: 0.7483 - loss: 0.2570 - mae: 0.3362 - rmse: 0.4889 - smape: 0.7029 - val_ia: 0.5124 - val_loss: 0.1992 - val_mae: 0.2999 - val_rmse: 0.3873 - val_smape: 0.6743

Epoch 27/128

958/958 - 17s - 18ms/step - ia: 0.7483 - loss: 0.2535 - mae: 0.3355 - rmse: 0.4856 - smape: 0.6997 - val_ia: 0.5137 - val_loss: 0.1973 - val_mae: 0.2992 - val_rmse: 0.3865 - val_smape: 0.6730

Epoch 28/128

958/958 - 19s - 20ms/step - ia: 0.7511 - loss: 0.2470 - mae: 0.3318 - rmse: 0.4796 - smape: 0.6954 - val_ia: 0.5212 - val_loss: 0.1933 - val_mae: 0.2941 - val_rmse: 0.3819 - val_smape: 0.6639

Epoch 29/128

958/958 - 17s - 18ms/step - ia: 0.7542 - loss: 0.2444 - mae: 0.3290 - rmse: 0.4770 - smape: 0.6899 - val_ia: 0.5264 - val_loss: 0.1907 - val_mae: 0.2915 - val_rmse: 0.3795 - val_smape: 0.6586

Epoch 30/128

958/958 - 21s - 22ms/step - ia: 0.7559 - loss: 0.2422 - mae: 0.3273 - rmse: 0.4727 - smape: 0.6875 - val_ia: 0.5269 - val_loss: 0.1884 - val_mae: 0.2901 - val_rmse: 0.3775 - val_smape: 0.6568

Epoch 31/128

958/958 - 16s - 16ms/step - ia: 0.7567 - loss: 0.2393 - mae: 0.3260 - rmse: 0.4724 - smape: 0.6865 - val_ia: 0.5310 - val_loss: 0.1854 - val_mae: 0.2876 - val_rmse: 0.3748 - val_smape: 0.6534

Epoch 32/128

958/958 - 17s - 18ms/step - ia: 0.7582 - loss: 0.2381 - mae: 0.3243 - rmse: 0.4704 - smape: 0.6814 - val_ia: 0.5325 - val_loss: 0.1833 - val_mae: 0.2863 - val_rmse: 0.3727 - val_smape: 0.6511

Epoch 33/128

958/958 - 17s - 18ms/step - ia: 0.7600 - loss: 0.2358 - mae: 0.3225 - rmse: 0.4673 - smape: 0.6785 - val_ia: 0.5360 - val_loss: 0.1809 - val_mae: 0.2840 - val_rmse: 0.3704 - val_smape: 0.6472

Epoch 34/128

958/958 - 19s - 20ms/step - ia: 0.7624 - loss: 0.2309 - mae: 0.3194 - rmse: 0.4627 - smape: 0.6755 - val_ia: 0.5403 - val_loss: 0.1783 - val_mae: 0.2813 - val_rmse: 0.3681 - val_smape: 0.6431

Epoch 35/128

958/958 - 22s - 23ms/step - ia: 0.7641 - loss: 0.2278 - mae: 0.3183 - rmse: 0.4603 - smape: 0.6729 - val_ia: 0.5431 - val_loss: 0.1755 - val_mae: 0.2791 - val_rmse: 0.3656 - val_smape: 0.6395

Epoch 36/128

958/958 - 17s - 17ms/step - ia: 0.7653 - loss: 0.2245 - mae: 0.3160 - rmse: 0.4569 - smape: 0.6707 - val_ia: 0.5444 - val_loss: 0.1732 - val_mae: 0.2774 - val_rmse: 0.3633 - val_smape: 0.6367

Epoch 37/128

958/958 - 16s - 17ms/step - ia: 0.7663 - loss: 0.2232 - mae: 0.3138 - rmse: 0.4545 - smape: 0.6666 - val_ia: 0.5470 - val_loss: 0.1709 - val_mae: 0.2757 - val_rmse: 0.3611 - val_smape: 0.6340

Epoch 38/128

958/958 - 17s - 18ms/step - ia: 0.7694 - loss: 0.2195 - mae: 0.3109 - rmse: 0.4512 - smape: 0.6616 - val_ia: 0.5477 - val_loss: 0.1688 - val_mae: 0.2747 - val_rmse: 0.3592 - val_smape: 0.6323

Epoch 39/128

958/958 - 17s - 18ms/step - ia: 0.7696 - loss: 0.2174 - mae: 0.3105 - rmse: 0.4486 - smape: 0.6614 - val_ia: 0.5522 - val_loss: 0.1658 - val_mae: 0.2711 - val_rmse: 0.3561 - val_smape: 0.6269

Epoch 40/128

958/958 - 16s - 16ms/step - ia: 0.7732 - loss: 0.2136 - mae: 0.3062 - rmse: 0.4452 - smape: 0.6534 - val_ia: 0.5575 - val_loss: 0.1635 - val_mae: 0.2682 - val_rmse: 0.3540 - val_smape: 0.6228

Epoch 41/128

958/958 - 17s - 18ms/step - ia: 0.7737 - loss: 0.2090 - mae: 0.3050 - rmse: 0.4403 - smape: 0.6540 - val_ia: 0.5574 - val_loss: 0.1613 - val_mae: 0.2675 - val_rmse: 0.3515 - val_smape: 0.6203

Epoch 42/128

958/958 - 21s - 22ms/step - ia: 0.7755 - loss: 0.2106 - mae: 0.3038 - rmse: 0.4413 - smape: 0.6494 - val_ia: 0.5634 - val_loss: 0.1587 - val_mae: 0.2640 - val_rmse: 0.3489 - val_smape: 0.6153

Epoch 43/128

958/958 - 12s - 12ms/step - ia: 0.7775 - loss: 0.2089 - mae: 0.3027 - rmse: 0.4387 - smape: 0.6489 - val_ia: 0.5622 - val_loss: 0.1566 - val_mae: 0.2635 - val_rmse: 0.3469 - val_smape: 0.6144

Epoch 44/128

958/958 - 10s - 11ms/step - ia: 0.7781 - loss: 0.2034 - mae: 0.3003 - rmse: 0.4344 - smape: 0.6458 - val_ia: 0.5690 - val_loss: 0.1537 - val_mae: 0.2594 - val_rmse: 0.3435 - val_smape: 0.6084

Epoch 45/128

958/958 - 11s - 11ms/step - ia: 0.7793 - loss: 0.2023 - mae: 0.2984 - rmse: 0.4318 - smape: 0.6417 - val_ia: 0.5695 - val_loss: 0.1516 - val_mae: 0.2585 - val_rmse: 0.3417 - val_smape: 0.6065

Epoch 46/128

958/958 - 15s - 16ms/step - ia: 0.7800 - loss: 0.2016 - mae: 0.2976 - rmse: 0.4315 - smape: 0.6377 - val_ia: 0.5740 - val_loss: 0.1496 - val_mae: 0.2558 - val_rmse: 0.3396 - val_smape: 0.6025

Epoch 47/128

958/958 - 17s - 17ms/step - ia: 0.7821 - loss: 0.1978 - mae: 0.2947 - rmse: 0.4270 - smape: 0.6353 - val_ia: 0.5754 - val_loss: 0.1469 - val_mae: 0.2541 - val_rmse: 0.3368 - val_smape: 0.6003

Epoch 48/128

958/958 - 20s - 21ms/step - ia: 0.7821 - loss: 0.1944 - mae: 0.2950 - rmse: 0.4251 - smape: 0.6382 - val_ia: 0.5791 - val_loss: 0.1450 - val_mae: 0.2520 - val_rmse: 0.3349 - val_smape: 0.5970

Epoch 49/128

958/958 - 13s - 13ms/step - ia: 0.7838 - loss: 0.1951 - mae: 0.2927 - rmse: 0.4258 - smape: 0.6300 - val_ia: 0.5802 - val_loss: 0.1431 - val_mae: 0.2510 - val_rmse: 0.3323 - val_smape: 0.5948

Epoch 50/128

958/958 - 12s - 13ms/step - ia: 0.7859 - loss: 0.1913 - mae: 0.2909 - rmse: 0.4209 - smape: 0.6317 - val_ia: 0.5831 - val_loss: 0.1409 - val_mae: 0.2485 - val_rmse: 0.3306 - val_smape: 0.5917

Epoch 51/128

958/958 - 22s - 22ms/step - ia: 0.7870 - loss: 0.1891 - mae: 0.2886 - rmse: 0.4175 - smape: 0.6248 - val_ia: 0.5839 - val_loss: 0.1389 - val_mae: 0.2472 - val_rmse: 0.3279 - val_smape: 0.5890

Epoch 52/128

958/958 - 20s - 21ms/step - ia: 0.7886 - loss: 0.1862 - mae: 0.2868 - rmse: 0.4147 - smape: 0.6229 - val_ia: 0.5896 - val_loss: 0.1368 - val_mae: 0.2442 - val_rmse: 0.3258 - val_smape: 0.5846

Epoch 53/128

958/958 - 13s - 13ms/step - ia: 0.7894 - loss: 0.1834 - mae: 0.2858 - rmse: 0.4118 - smape: 0.6226 - val_ia: 0.5908 - val_loss: 0.1353 - val_mae: 0.2434 - val_rmse: 0.3239 - val_smape: 0.5826

Epoch 54/128

958/958 - 21s - 21ms/step - ia: 0.7908 - loss: 0.1841 - mae: 0.2847 - rmse: 0.4116 - smape: 0.6181 - val_ia: 0.5923 - val_loss: 0.1334 - val_mae: 0.2416 - val_rmse: 0.3222 - val_smape: 0.5805

Epoch 55/128

958/958 - 13s - 13ms/step - ia: 0.7924 - loss: 0.1797 - mae: 0.2827 - rmse: 0.4082 - smape: 0.6165 - val_ia: 0.5945 - val_loss: 0.1316 - val_mae: 0.2399 - val_rmse: 0.3199 - val_smape: 0.5779

Epoch 56/128

958/958 - 20s - 21ms/step - ia: 0.7933 - loss: 0.1792 - mae: 0.2816 - rmse: 0.4068 - smape: 0.6154 - val_ia: 0.5953 - val_loss: 0.1305 - val_mae: 0.2390 - val_rmse: 0.3189 - val_smape: 0.5765

Epoch 57/128

958/958 - 21s - 22ms/step - ia: 0.7950 - loss: 0.1773 - mae: 0.2797 - rmse: 0.4051 - smape: 0.6102 - val_ia: 0.5984 - val_loss: 0.1285 - val_mae: 0.2370 - val_rmse: 0.3160 - val_smape: 0.5732

Epoch 58/128

958/958 - 20s - 21ms/step - ia: 0.7947 - loss: 0.1760 - mae: 0.2781 - rmse: 0.4033 - smape: 0.6070 - val_ia: 0.6021 - val_loss: 0.1275 - val_mae: 0.2349 - val_rmse: 0.3151 - val_smape: 0.5705

Epoch 59/128

958/958 - 12s - 13ms/step - ia: 0.7956 - loss: 0.1755 - mae: 0.2783 - rmse: 0.4019 - smape: 0.6077 - val_ia: 0.6070 - val_loss: 0.1255 - val_mae: 0.2325 - val_rmse: 0.3124 - val_smape: 0.5665

Epoch 60/128

958/958 - 12s - 13ms/step - ia: 0.7989 - loss: 0.1691 - mae: 0.2748 - rmse: 0.3956 - smape: 0.6051 - val_ia: 0.6042 - val_loss: 0.1241 - val_mae: 0.2328 - val_rmse: 0.3112 - val_smape: 0.5672

Epoch 61/128

958/958 - 13s - 13ms/step - ia: 0.7975 - loss: 0.1721 - mae: 0.2759 - rmse: 0.3999 - smape: 0.6026 - val_ia: 0.6068 - val_loss: 0.1231 - val_mae: 0.2315 - val_rmse: 0.3097 - val_smape: 0.5647

Epoch 62/128

958/958 - 12s - 13ms/step - ia: 0.7979 - loss: 0.1718 - mae: 0.2748 - rmse: 0.3973 - smape: 0.6024 - val_ia: 0.6127 - val_loss: 0.1212 - val_mae: 0.2283 - val_rmse: 0.3070 - val_smape: 0.5594

Epoch 63/128

958/958 - 12s - 13ms/step - ia: 0.7995 - loss: 0.1693 - mae: 0.2735 - rmse: 0.3960 - smape: 0.6015 - val_ia: 0.6133 - val_loss: 0.1204 - val_mae: 0.2275 - val_rmse: 0.3058 - val_smape: 0.5579

Epoch 64/128

958/958 - 12s - 13ms/step - ia: 0.8015 - loss: 0.1679 - mae: 0.2714 - rmse: 0.3935 - smape: 0.5953 - val_ia: 0.6124 - val_loss: 0.1194 - val_mae: 0.2274 - val_rmse: 0.3049 - val_smape: 0.5573

Epoch 65/128

958/958 - 12s - 13ms/step - ia: 0.8020 - loss: 0.1657 - mae: 0.2709 - rmse: 0.3911 - smape: 0.5946 - val_ia: 0.6147 - val_loss: 0.1179 - val_mae: 0.2257 - val_rmse: 0.3028 - val_smape: 0.5542

Epoch 66/128

958/958 - 12s - 13ms/step - ia: 0.8019 - loss: 0.1659 - mae: 0.2700 - rmse: 0.3918 - smape: 0.5950 - val_ia: 0.6182 - val_loss: 0.1168 - val_mae: 0.2239 - val_rmse: 0.3014 - val_smape: 0.5515

Epoch 67/128

958/958 - 12s - 13ms/step - ia: 0.8035 - loss: 0.1642 - mae: 0.2682 - rmse: 0.3887 - smape: 0.5902 - val_ia: 0.6214 - val_loss: 0.1156 - val_mae: 0.2223 - val_rmse: 0.2999 - val_smape: 0.5488

Epoch 68/128

958/958 - 20s - 21ms/step - ia: 0.8040 - loss: 0.1620 - mae: 0.2677 - rmse: 0.3856 - smape: 0.5939 - val_ia: 0.6206 - val_loss: 0.1151 - val_mae: 0.2226 - val_rmse: 0.2993 - val_smape: 0.5484

Epoch 69/128

958/958 - 12s - 13ms/step - ia: 0.8054 - loss: 0.1619 - mae: 0.2664 - rmse: 0.3857 - smape: 0.5887 - val_ia: 0.6235 - val_loss: 0.1137 - val_mae: 0.2205 - val_rmse: 0.2977 - val_smape: 0.5455

Epoch 70/128

958/958 - 12s - 13ms/step - ia: 0.8083 - loss: 0.1561 - mae: 0.2627 - rmse: 0.3789 - smape: 0.5860 - val_ia: 0.6256 - val_loss: 0.1126 - val_mae: 0.2192 - val_rmse: 0.2962 - val_smape: 0.5429

Epoch 71/128

958/958 - 12s - 13ms/step - ia: 0.8074 - loss: 0.1598 - mae: 0.2637 - rmse: 0.3827 - smape: 0.5841 - val_ia: 0.6219 - val_loss: 0.1121 - val_mae: 0.2204 - val_rmse: 0.2954 - val_smape: 0.5428

Epoch 72/128

958/958 - 12s - 13ms/step - ia: 0.8081 - loss: 0.1579 - mae: 0.2625 - rmse: 0.3808 - smape: 0.5840 - val_ia: 0.6272 - val_loss: 0.1106 - val_mae: 0.2175 - val_rmse: 0.2934 - val_smape: 0.5391

Epoch 73/128

958/958 - 20s - 21ms/step - ia: 0.8089 - loss: 0.1561 - mae: 0.2615 - rmse: 0.3794 - smape: 0.5824 - val_ia: 0.6306 - val_loss: 0.1094 - val_mae: 0.2158 - val_rmse: 0.2918 - val_smape: 0.5359

Epoch 74/128

958/958 - 11s - 11ms/step - ia: 0.8106 - loss: 0.1535 - mae: 0.2597 - rmse: 0.3756 - smape: 0.5817 - val_ia: 0.6346 - val_loss: 0.1082 - val_mae: 0.2137 - val_rmse: 0.2901 - val_smape: 0.5329

Epoch 75/128

958/958 - 22s - 23ms/step - ia: 0.8105 - loss: 0.1534 - mae: 0.2607 - rmse: 0.3768 - smape: 0.5778 - val_ia: 0.6333 - val_loss: 0.1074 - val_mae: 0.2139 - val_rmse: 0.2893 - val_smape: 0.5319

Epoch 76/128

958/958 - 13s - 13ms/step - ia: 0.8103 - loss: 0.1541 - mae: 0.2596 - rmse: 0.3760 - smape: 0.5769 - val_ia: 0.6378 - val_loss: 0.1063 - val_mae: 0.2115 - val_rmse: 0.2876 - val_smape: 0.5282

Epoch 77/128

958/958 - 12s - 13ms/step - ia: 0.8116 - loss: 0.1511 - mae: 0.2580 - rmse: 0.3726 - smape: 0.5754 - val_ia: 0.6381 - val_loss: 0.1057 - val_mae: 0.2111 - val_rmse: 0.2867 - val_smape: 0.5278

Epoch 78/128

958/958 - 13s - 13ms/step - ia: 0.8116 - loss: 0.1535 - mae: 0.2586 - rmse: 0.3750 - smape: 0.5752 - val_ia: 0.6358 - val_loss: 0.1055 - val_mae: 0.2120 - val_rmse: 0.2868 - val_smape: 0.5282

Epoch 79/128

958/958 - 21s - 22ms/step - ia: 0.8146 - loss: 0.1471 - mae: 0.2548 - rmse: 0.3690 - smape: 0.5685 - val_ia: 0.6408 - val_loss: 0.1039 - val_mae: 0.2091 - val_rmse: 0.2844 - val_smape: 0.5238

Epoch 80/128

958/958 - 21s - 22ms/step - ia: 0.8146 - loss: 0.1479 - mae: 0.2555 - rmse: 0.3691 - smape: 0.5703 - val_ia: 0.6408 - val_loss: 0.1030 - val_mae: 0.2088 - val_rmse: 0.2832 - val_smape: 0.5222

Epoch 81/128

958/958 - 12s - 13ms/step - ia: 0.8137 - loss: 0.1479 - mae: 0.2555 - rmse: 0.3682 - smape: 0.5710 - val_ia: 0.6426 - val_loss: 0.1022 - val_mae: 0.2075 - val_rmse: 0.2820 - val_smape: 0.5204

Epoch 82/128

958/958 - 12s - 13ms/step - ia: 0.8131 - loss: 0.1477 - mae: 0.2555 - rmse: 0.3698 - smape: 0.5692 - val_ia: 0.6455 - val_loss: 0.1012 - val_mae: 0.2057 - val_rmse: 0.2809 - val_smape: 0.5180

Epoch 83/128

958/958 - 12s - 13ms/step - ia: 0.8168 - loss: 0.1458 - mae: 0.2530 - rmse: 0.3657 - smape: 0.5644 - val_ia: 0.6474 - val_loss: 0.0999 - val_mae: 0.2045 - val_rmse: 0.2788 - val_smape: 0.5153

Epoch 84/128

958/958 - 24s - 25ms/step - ia: 0.8176 - loss: 0.1449 - mae: 0.2510 - rmse: 0.3649 - smape: 0.5591 - val_ia: 0.6510 - val_loss: 0.0990 - val_mae: 0.2027 - val_rmse: 0.2776 - val_smape: 0.5130

Epoch 85/128

958/958 - 13s - 14ms/step - ia: 0.8165 - loss: 0.1461 - mae: 0.2523 - rmse: 0.3663 - smape: 0.5632 - val_ia: 0.6506 - val_loss: 0.0992 - val_mae: 0.2036 - val_rmse: 0.2775 - val_smape: 0.5124

Epoch 86/128

958/958 - 13s - 14ms/step - ia: 0.8167 - loss: 0.1434 - mae: 0.2514 - rmse: 0.3628 - smape: 0.5626 - val_ia: 0.6526 - val_loss: 0.0980 - val_mae: 0.2020 - val_rmse: 0.2757 - val_smape: 0.5094

Epoch 87/128

958/958 - 12s - 13ms/step - ia: 0.8178 - loss: 0.1413 - mae: 0.2508 - rmse: 0.3615 - smape: 0.5622 - val_ia: 0.6513 - val_loss: 0.0974 - val_mae: 0.2017 - val_rmse: 0.2752 - val_smape: 0.5093

Epoch 88/128

958/958 - 21s - 22ms/step - ia: 0.8199 - loss: 0.1402 - mae: 0.2481 - rmse: 0.3584 - smape: 0.5577 - val_ia: 0.6586 - val_loss: 0.0963 - val_mae: 0.1988 - val_rmse: 0.2736 - val_smape: 0.5055

Epoch 89/128

958/958 - 12s - 13ms/step - ia: 0.8200 - loss: 0.1416 - mae: 0.2478 - rmse: 0.3611 - smape: 0.5552 - val_ia: 0.6548 - val_loss: 0.0961 - val_mae: 0.2002 - val_rmse: 0.2732 - val_smape: 0.5056

Epoch 90/128

958/958 - 12s - 13ms/step - ia: 0.8197 - loss: 0.1410 - mae: 0.2477 - rmse: 0.3589 - smape: 0.5573 - val_ia: 0.6591 - val_loss: 0.0949 - val_mae: 0.1978 - val_rmse: 0.2712 - val_smape: 0.5018

Epoch 91/128

958/958 - 20s - 21ms/step - ia: 0.8210 - loss: 0.1388 - mae: 0.2472 - rmse: 0.3572 - smape: 0.5558 - val_ia: 0.6569 - val_loss: 0.0944 - val_mae: 0.1982 - val_rmse: 0.2708 - val_smape: 0.5024

Epoch 92/128

958/958 - 13s - 13ms/step - ia: 0.8190 - loss: 0.1408 - mae: 0.2488 - rmse: 0.3606 - smape: 0.5535 - val_ia: 0.6564 - val_loss: 0.0946 - val_mae: 0.1988 - val_rmse: 0.2712 - val_smape: 0.5031

Epoch 93/128

958/958 - 20s - 21ms/step - ia: 0.8220 - loss: 0.1365 - mae: 0.2450 - rmse: 0.3547 - smape: 0.5521 - val_ia: 0.6621 - val_loss: 0.0929 - val_mae: 0.1958 - val_rmse: 0.2685 - val_smape: 0.4981

Epoch 94/128

958/958 - 21s - 21ms/step - ia: 0.8215 - loss: 0.1376 - mae: 0.2457 - rmse: 0.3554 - smape: 0.5527 - val_ia: 0.6648 - val_loss: 0.0926 - val_mae: 0.1947 - val_rmse: 0.2682 - val_smape: 0.4970

Epoch 95/128

958/958 - 20s - 21ms/step - ia: 0.8231 - loss: 0.1387 - mae: 0.2447 - rmse: 0.3550 - smape: 0.5496 - val_ia: 0.6644 - val_loss: 0.0918 - val_mae: 0.1943 - val_rmse: 0.2668 - val_smape: 0.4956

Epoch 96/128

958/958 - 12s - 13ms/step - ia: 0.8225 - loss: 0.1354 - mae: 0.2438 - rmse: 0.3531 - smape: 0.5484 - val_ia: 0.6676 - val_loss: 0.0908 - val_mae: 0.1925 - val_rmse: 0.2656 - val_smape: 0.4935

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 10s - 21ms/step - ia: 0.1924 - loss: 0.9599 - mae: 0.7468 - rmse: 0.9688 - smape: 1.5942 - val_ia: 0.2390 - val_loss: 0.8624 - val_mae: 0.6972 - val_rmse: 0.8005 - val_smape: 1.5042

Epoch 2/128

479/479 - 4s - 8ms/step - ia: 0.2029 - loss: 0.9331 - mae: 0.7353 - rmse: 0.9559 - smape: 1.5844 - val_ia: 0.2454 - val_loss: 0.8394 - val_mae: 0.6875 - val_rmse: 0.7896 - val_smape: 1.4979

Epoch 3/128

479/479 - 4s - 8ms/step - ia: 0.2140 - loss: 0.9058 - mae: 0.7231 - rmse: 0.9401 - smape: 1.5702 - val_ia: 0.2519 - val_loss: 0.8172 - val_mae: 0.6780 - val_rmse: 0.7790 - val_smape: 1.4893

Epoch 4/128

479/479 - 5s - 11ms/step - ia: 0.2261 - loss: 0.8784 - mae: 0.7109 - rmse: 0.9267 - smape: 1.5527 - val_ia: 0.2588 - val_loss: 0.7954 - val_mae: 0.6686 - val_rmse: 0.7686 - val_smape: 1.4791

Epoch 5/128

479/479 - 5s - 11ms/step - ia: 0.2374 - loss: 0.8541 - mae: 0.6994 - rmse: 0.9136 - smape: 1.5354 - val_ia: 0.2657 - val_loss: 0.7739 - val_mae: 0.6592 - val_rmse: 0.7581 - val_smape: 1.4676

Epoch 6/128

479/479 - 4s - 8ms/step - ia: 0.2533 - loss: 0.8288 - mae: 0.6866 - rmse: 0.8989 - smape: 1.5097 - val_ia: 0.2727 - val_loss: 0.7526 - val_mae: 0.6498 - val_rmse: 0.7478 - val_smape: 1.4527

Epoch 7/128

479/479 - 4s - 8ms/step - ia: 0.2694 - loss: 0.8044 - mae: 0.6750 - rmse: 0.8866 - smape: 1.4837 - val_ia: 0.2798 - val_loss: 0.7318 - val_mae: 0.6405 - val_rmse: 0.7376 - val_smape: 1.4361

Epoch 8/128

479/479 - 4s - 8ms/step - ia: 0.2839 - loss: 0.7812 - mae: 0.6646 - rmse: 0.8735 - smape: 1.4589 - val_ia: 0.2873 - val_loss: 0.7110 - val_mae: 0.6311 - val_rmse: 0.7272 - val_smape: 1.4162

Epoch 9/128

479/479 - 4s - 8ms/step - ia: 0.3026 - loss: 0.7537 - mae: 0.6522 - rmse: 0.8579 - smape: 1.4309 - val_ia: 0.2951 - val_loss: 0.6902 - val_mae: 0.6214 - val_rmse: 0.7167 - val_smape: 1.3938

Epoch 10/128

479/479 - 4s - 8ms/step - ia: 0.3203 - loss: 0.7334 - mae: 0.6407 - rmse: 0.8456 - smape: 1.4016 - val_ia: 0.3032 - val_loss: 0.6695 - val_mae: 0.6116 - val_rmse: 0.7061 - val_smape: 1.3689

Epoch 11/128

479/479 - 4s - 8ms/step - ia: 0.3388 - loss: 0.7097 - mae: 0.6294 - rmse: 0.8321 - smape: 1.3734 - val_ia: 0.3116 - val_loss: 0.6491 - val_mae: 0.6017 - val_rmse: 0.6955 - val_smape: 1.3425

Epoch 12/128

479/479 - 4s - 8ms/step - ia: 0.3573 - loss: 0.6882 - mae: 0.6188 - rmse: 0.8183 - smape: 1.3430 - val_ia: 0.3203 - val_loss: 0.6287 - val_mae: 0.5916 - val_rmse: 0.6848 - val_smape: 1.3152

Epoch 13/128

479/479 - 6s - 12ms/step - ia: 0.3774 - loss: 0.6653 - mae: 0.6058 - rmse: 0.8041 - smape: 1.3077 - val_ia: 0.3293 - val_loss: 0.6084 - val_mae: 0.5813 - val_rmse: 0.6740 - val_smape: 1.2861

Epoch 14/128

479/479 - 3s - 7ms/step - ia: 0.3945 - loss: 0.6445 - mae: 0.5959 - rmse: 0.7920 - smape: 1.2827 - val_ia: 0.3384 - val_loss: 0.5884 - val_mae: 0.5710 - val_rmse: 0.6631 - val_smape: 1.2572

Epoch 15/128

479/479 - 4s - 8ms/step - ia: 0.4165 - loss: 0.6234 - mae: 0.5826 - rmse: 0.7782 - smape: 1.2452 - val_ia: 0.3478 - val_loss: 0.5685 - val_mae: 0.5605 - val_rmse: 0.6522 - val_smape: 1.2282

Epoch 16/128

479/479 - 5s - 11ms/step - ia: 0.4361 - loss: 0.6014 - mae: 0.5705 - rmse: 0.7638 - smape: 1.2113 - val_ia: 0.3573 - val_loss: 0.5490 - val_mae: 0.5499 - val_rmse: 0.6412 - val_smape: 1.1986

Epoch 17/128

479/479 - 4s - 8ms/step - ia: 0.4549 - loss: 0.5813 - mae: 0.5590 - rmse: 0.7512 - smape: 1.1820 - val_ia: 0.3670 - val_loss: 0.5300 - val_mae: 0.5392 - val_rmse: 0.6303 - val_smape: 1.1693

Epoch 18/128

479/479 - 4s - 8ms/step - ia: 0.4737 - loss: 0.5615 - mae: 0.5477 - rmse: 0.7376 - smape: 1.1543 - val_ia: 0.3769 - val_loss: 0.5114 - val_mae: 0.5285 - val_rmse: 0.6195 - val_smape: 1.1407

Epoch 19/128

479/479 - 6s - 12ms/step - ia: 0.4917 - loss: 0.5467 - mae: 0.5373 - rmse: 0.7285 - smape: 1.1236 - val_ia: 0.3867 - val_loss: 0.4936 - val_mae: 0.5178 - val_rmse: 0.6089 - val_smape: 1.1128

Epoch 20/128

479/479 - 4s - 7ms/step - ia: 0.5119 - loss: 0.5250 - mae: 0.5241 - rmse: 0.7135 - smape: 1.0900 - val_ia: 0.3966 - val_loss: 0.4764 - val_mae: 0.5071 - val_rmse: 0.5983 - val_smape: 1.0847

Epoch 21/128

479/479 - 4s - 7ms/step - ia: 0.5286 - loss: 0.5093 - mae: 0.5135 - rmse: 0.7013 - smape: 1.0638 - val_ia: 0.4066 - val_loss: 0.4602 - val_mae: 0.4965 - val_rmse: 0.5882 - val_smape: 1.0578

Epoch 22/128

479/479 - 4s - 7ms/step - ia: 0.5469 - loss: 0.4941 - mae: 0.5020 - rmse: 0.6916 - smape: 1.0366 - val_ia: 0.4163 - val_loss: 0.4450 - val_mae: 0.4862 - val_rmse: 0.5785 - val_smape: 1.0317

Epoch 23/128

479/479 - 5s - 11ms/step - ia: 0.5651 - loss: 0.4771 - mae: 0.4903 - rmse: 0.6792 - smape: 1.0060 - val_ia: 0.4257 - val_loss: 0.4309 - val_mae: 0.4762 - val_rmse: 0.5694 - val_smape: 1.0068

Epoch 24/128

479/479 - 4s - 8ms/step - ia: 0.5787 - loss: 0.4654 - mae: 0.4811 - rmse: 0.6712 - smape: 0.9837 - val_ia: 0.4350 - val_loss: 0.4177 - val_mae: 0.4664 - val_rmse: 0.5605 - val_smape: 0.9828

Epoch 25/128

479/479 - 4s - 7ms/step - ia: 0.5932 - loss: 0.4530 - mae: 0.4719 - rmse: 0.6619 - smape: 0.9617 - val_ia: 0.4441 - val_loss: 0.4057 - val_mae: 0.4569 - val_rmse: 0.5523 - val_smape: 0.9598

Epoch 26/128

479/479 - 4s - 7ms/step - ia: 0.6064 - loss: 0.4419 - mae: 0.4633 - rmse: 0.6534 - smape: 0.9412 - val_ia: 0.4529 - val_loss: 0.3946 - val_mae: 0.4478 - val_rmse: 0.5446 - val_smape: 0.9384

Epoch 27/128

479/479 - 4s - 8ms/step - ia: 0.6174 - loss: 0.4347 - mae: 0.4565 - rmse: 0.6472 - smape: 0.9234 - val_ia: 0.4613 - val_loss: 0.3850 - val_mae: 0.4395 - val_rmse: 0.5377 - val_smape: 0.9189

Epoch 28/128

479/479 - 4s - 7ms/step - ia: 0.6283 - loss: 0.4238 - mae: 0.4485 - rmse: 0.6394 - smape: 0.9051 - val_ia: 0.4696 - val_loss: 0.3764 - val_mae: 0.4317 - val_rmse: 0.5314 - val_smape: 0.9008

Epoch 29/128

479/479 - 4s - 8ms/step - ia: 0.6386 - loss: 0.4150 - mae: 0.4413 - rmse: 0.6324 - smape: 0.8891 - val_ia: 0.4775 - val_loss: 0.3688 - val_mae: 0.4245 - val_rmse: 0.5259 - val_smape: 0.8844

Epoch 30/128

479/479 - 4s - 8ms/step - ia: 0.6472 - loss: 0.4096 - mae: 0.4358 - rmse: 0.6284 - smape: 0.8740 - val_ia: 0.4848 - val_loss: 0.3622 - val_mae: 0.4181 - val_rmse: 0.5209 - val_smape: 0.8698

Epoch 31/128

479/479 - 4s - 8ms/step - ia: 0.6560 - loss: 0.4022 - mae: 0.4298 - rmse: 0.6232 - smape: 0.8629 - val_ia: 0.4912 - val_loss: 0.3564 - val_mae: 0.4124 - val_rmse: 0.5166 - val_smape: 0.8567

Epoch 32/128

479/479 - 4s - 8ms/step - ia: 0.6600 - loss: 0.4005 - mae: 0.4286 - rmse: 0.6211 - smape: 0.8569 - val_ia: 0.4972 - val_loss: 0.3514 - val_mae: 0.4073 - val_rmse: 0.5129 - val_smape: 0.8450

Epoch 33/128

479/479 - 5s - 11ms/step - ia: 0.6659 - loss: 0.3988 - mae: 0.4245 - rmse: 0.6200 - smape: 0.8444 - val_ia: 0.5026 - val_loss: 0.3471 - val_mae: 0.4029 - val_rmse: 0.5095 - val_smape: 0.8343

Epoch 34/128

479/479 - 4s - 8ms/step - ia: 0.6720 - loss: 0.3918 - mae: 0.4202 - rmse: 0.6141 - smape: 0.8357 - val_ia: 0.5073 - val_loss: 0.3432 - val_mae: 0.3990 - val_rmse: 0.5066 - val_smape: 0.8254

Epoch 35/128

479/479 - 4s - 8ms/step - ia: 0.6751 - loss: 0.3898 - mae: 0.4182 - rmse: 0.6132 - smape: 0.8311 - val_ia: 0.5116 - val_loss: 0.3398 - val_mae: 0.3956 - val_rmse: 0.5039 - val_smape: 0.8175

Epoch 36/128

479/479 - 4s - 8ms/step - ia: 0.6788 - loss: 0.3867 - mae: 0.4158 - rmse: 0.6095 - smape: 0.8241 - val_ia: 0.5152 - val_loss: 0.3367 - val_mae: 0.3926 - val_rmse: 0.5016 - val_smape: 0.8106

Epoch 37/128

479/479 - 4s - 8ms/step - ia: 0.6835 - loss: 0.3802 - mae: 0.4122 - rmse: 0.6058 - smape: 0.8151 - val_ia: 0.5185 - val_loss: 0.3338 - val_mae: 0.3899 - val_rmse: 0.4994 - val_smape: 0.8048

Epoch 38/128

479/479 - 4s - 8ms/step - ia: 0.6842 - loss: 0.3824 - mae: 0.4125 - rmse: 0.6067 - smape: 0.8143 - val_ia: 0.5212 - val_loss: 0.3312 - val_mae: 0.3876 - val_rmse: 0.4975 - val_smape: 0.7996

Epoch 39/128

479/479 - 4s - 8ms/step - ia: 0.6856 - loss: 0.3805 - mae: 0.4114 - rmse: 0.6059 - smape: 0.8112 - val_ia: 0.5238 - val_loss: 0.3287 - val_mae: 0.3854 - val_rmse: 0.4956 - val_smape: 0.7949

Epoch 40/128

479/479 - 4s - 8ms/step - ia: 0.6884 - loss: 0.3792 - mae: 0.4097 - rmse: 0.6040 - smape: 0.8084 - val_ia: 0.5260 - val_loss: 0.3263 - val_mae: 0.3834 - val_rmse: 0.4938 - val_smape: 0.7906

Epoch 41/128

479/479 - 4s - 8ms/step - ia: 0.6908 - loss: 0.3734 - mae: 0.4069 - rmse: 0.5997 - smape: 0.8063 - val_ia: 0.5280 - val_loss: 0.3240 - val_mae: 0.3815 - val_rmse: 0.4921 - val_smape: 0.7870

Epoch 42/128

479/479 - 4s - 8ms/step - ia: 0.6920 - loss: 0.3724 - mae: 0.4062 - rmse: 0.5986 - smape: 0.8043 - val_ia: 0.5300 - val_loss: 0.3218 - val_mae: 0.3798 - val_rmse: 0.4905 - val_smape: 0.7837

Epoch 43/128

479/479 - 5s - 11ms/step - ia: 0.6947 - loss: 0.3701 - mae: 0.4041 - rmse: 0.5962 - smape: 0.7970 - val_ia: 0.5316 - val_loss: 0.3198 - val_mae: 0.3782 - val_rmse: 0.4890 - val_smape: 0.7809

Epoch 44/128

479/479 - 5s - 11ms/step - ia: 0.6946 - loss: 0.3698 - mae: 0.4035 - rmse: 0.5967 - smape: 0.7942 - val_ia: 0.5331 - val_loss: 0.3178 - val_mae: 0.3767 - val_rmse: 0.4875 - val_smape: 0.7782

Epoch 45/128

479/479 - 4s - 8ms/step - ia: 0.6963 - loss: 0.3678 - mae: 0.4018 - rmse: 0.5950 - smape: 0.7945 - val_ia: 0.5345 - val_loss: 0.3158 - val_mae: 0.3753 - val_rmse: 0.4861 - val_smape: 0.7755

Epoch 46/128

479/479 - 4s - 8ms/step - ia: 0.6975 - loss: 0.3645 - mae: 0.4005 - rmse: 0.5925 - smape: 0.7920 - val_ia: 0.5358 - val_loss: 0.3139 - val_mae: 0.3740 - val_rmse: 0.4847 - val_smape: 0.7732

Epoch 47/128

479/479 - 5s - 11ms/step - ia: 0.6990 - loss: 0.3637 - mae: 0.3992 - rmse: 0.5927 - smape: 0.7881 - val_ia: 0.5370 - val_loss: 0.3120 - val_mae: 0.3726 - val_rmse: 0.4833 - val_smape: 0.7708

Epoch 48/128

479/479 - 4s - 8ms/step - ia: 0.6992 - loss: 0.3628 - mae: 0.3992 - rmse: 0.5909 - smape: 0.7912 - val_ia: 0.5381 - val_loss: 0.3102 - val_mae: 0.3714 - val_rmse: 0.4819 - val_smape: 0.7685

Epoch 49/128

479/479 - 4s - 8ms/step - ia: 0.7000 - loss: 0.3606 - mae: 0.3983 - rmse: 0.5886 - smape: 0.7888 - val_ia: 0.5392 - val_loss: 0.3083 - val_mae: 0.3701 - val_rmse: 0.4806 - val_smape: 0.7664

Epoch 50/128

479/479 - 4s - 8ms/step - ia: 0.7004 - loss: 0.3615 - mae: 0.3980 - rmse: 0.5897 - smape: 0.7865 - val_ia: 0.5401 - val_loss: 0.3066 - val_mae: 0.3690 - val_rmse: 0.4793 - val_smape: 0.7645

Epoch 51/128

479/479 - 5s - 10ms/step - ia: 0.7024 - loss: 0.3567 - mae: 0.3959 - rmse: 0.5862 - smape: 0.7841 - val_ia: 0.5410 - val_loss: 0.3048 - val_mae: 0.3679 - val_rmse: 0.4780 - val_smape: 0.7629

Epoch 52/128

479/479 - 4s - 8ms/step - ia: 0.7037 - loss: 0.3540 - mae: 0.3941 - rmse: 0.5844 - smape: 0.7822 - val_ia: 0.5419 - val_loss: 0.3032 - val_mae: 0.3669 - val_rmse: 0.4769 - val_smape: 0.7617

Epoch 53/128

479/479 - 5s - 10ms/step - ia: 0.7040 - loss: 0.3549 - mae: 0.3942 - rmse: 0.5841 - smape: 0.7818 - val_ia: 0.5428 - val_loss: 0.3014 - val_mae: 0.3658 - val_rmse: 0.4756 - val_smape: 0.7600

Epoch 54/128

479/479 - 4s - 8ms/step - ia: 0.7049 - loss: 0.3504 - mae: 0.3920 - rmse: 0.5798 - smape: 0.7777 - val_ia: 0.5437 - val_loss: 0.2998 - val_mae: 0.3648 - val_rmse: 0.4745 - val_smape: 0.7586

Epoch 55/128

479/479 - 4s - 8ms/step - ia: 0.7062 - loss: 0.3481 - mae: 0.3916 - rmse: 0.5796 - smape: 0.7790 - val_ia: 0.5446 - val_loss: 0.2982 - val_mae: 0.3638 - val_rmse: 0.4733 - val_smape: 0.7571

Epoch 56/128

479/479 - 4s - 8ms/step - ia: 0.7065 - loss: 0.3505 - mae: 0.3899 - rmse: 0.5816 - smape: 0.7740 - val_ia: 0.5457 - val_loss: 0.2965 - val_mae: 0.3626 - val_rmse: 0.4721 - val_smape: 0.7553

Epoch 57/128

479/479 - 4s - 7ms/step - ia: 0.7070 - loss: 0.3478 - mae: 0.3904 - rmse: 0.5778 - smape: 0.7760 - val_ia: 0.5465 - val_loss: 0.2948 - val_mae: 0.3616 - val_rmse: 0.4709 - val_smape: 0.7537

Epoch 58/128

479/479 - 4s - 8ms/step - ia: 0.7089 - loss: 0.3436 - mae: 0.3880 - rmse: 0.5742 - smape: 0.7717 - val_ia: 0.5473 - val_loss: 0.2932 - val_mae: 0.3606 - val_rmse: 0.4697 - val_smape: 0.7522

Epoch 59/128

479/479 - 5s - 11ms/step - ia: 0.7086 - loss: 0.3453 - mae: 0.3881 - rmse: 0.5768 - smape: 0.7722 - val_ia: 0.5482 - val_loss: 0.2916 - val_mae: 0.3595 - val_rmse: 0.4685 - val_smape: 0.7507

Epoch 60/128

479/479 - 5s - 10ms/step - ia: 0.7093 - loss: 0.3421 - mae: 0.3872 - rmse: 0.5739 - smape: 0.7737 - val_ia: 0.5492 - val_loss: 0.2901 - val_mae: 0.3585 - val_rmse: 0.4674 - val_smape: 0.7492

Epoch 61/128

479/479 - 4s - 8ms/step - ia: 0.7096 - loss: 0.3413 - mae: 0.3864 - rmse: 0.5730 - smape: 0.7720 - val_ia: 0.5502 - val_loss: 0.2885 - val_mae: 0.3575 - val_rmse: 0.4663 - val_smape: 0.7478

Epoch 62/128

479/479 - 4s - 8ms/step - ia: 0.7102 - loss: 0.3429 - mae: 0.3866 - rmse: 0.5745 - smape: 0.7698 - val_ia: 0.5510 - val_loss: 0.2870 - val_mae: 0.3566 - val_rmse: 0.4652 - val_smape: 0.7464

Epoch 63/128

479/479 - 4s - 8ms/step - ia: 0.7115 - loss: 0.3390 - mae: 0.3845 - rmse: 0.5715 - smape: 0.7663 - val_ia: 0.5518 - val_loss: 0.2855 - val_mae: 0.3557 - val_rmse: 0.4642 - val_smape: 0.7451

Epoch 64/128

479/479 - 6s - 13ms/step - ia: 0.7128 - loss: 0.3370 - mae: 0.3840 - rmse: 0.5691 - smape: 0.7659 - val_ia: 0.5527 - val_loss: 0.2840 - val_mae: 0.3547 - val_rmse: 0.4630 - val_smape: 0.7437

Epoch 65/128

479/479 - 4s - 9ms/step - ia: 0.7130 - loss: 0.3355 - mae: 0.3827 - rmse: 0.5679 - smape: 0.7645 - val_ia: 0.5535 - val_loss: 0.2825 - val_mae: 0.3537 - val_rmse: 0.4619 - val_smape: 0.7420

Epoch 66/128

479/479 - 4s - 9ms/step - ia: 0.7132 - loss: 0.3353 - mae: 0.3822 - rmse: 0.5674 - smape: 0.7631 - val_ia: 0.5544 - val_loss: 0.2811 - val_mae: 0.3528 - val_rmse: 0.4609 - val_smape: 0.7407

Epoch 67/128

479/479 - 5s - 10ms/step - ia: 0.7148 - loss: 0.3306 - mae: 0.3800 - rmse: 0.5632 - smape: 0.7614 - val_ia: 0.5552 - val_loss: 0.2796 - val_mae: 0.3519 - val_rmse: 0.4598 - val_smape: 0.7394

Epoch 68/128

479/479 - 4s - 8ms/step - ia: 0.7147 - loss: 0.3318 - mae: 0.3807 - rmse: 0.5647 - smape: 0.7623 - val_ia: 0.5559 - val_loss: 0.2782 - val_mae: 0.3510 - val_rmse: 0.4587 - val_smape: 0.7382

Epoch 69/128

479/479 - 4s - 7ms/step - ia: 0.7175 - loss: 0.3271 - mae: 0.3780 - rmse: 0.5602 - smape: 0.7569 - val_ia: 0.5567 - val_loss: 0.2767 - val_mae: 0.3500 - val_rmse: 0.4575 - val_smape: 0.7370

Epoch 70/128

479/479 - 4s - 8ms/step - ia: 0.7170 - loss: 0.3284 - mae: 0.3777 - rmse: 0.5620 - smape: 0.7567 - val_ia: 0.5577 - val_loss: 0.2752 - val_mae: 0.3491 - val_rmse: 0.4564 - val_smape: 0.7356

Epoch 71/128

479/479 - 6s - 12ms/step - ia: 0.7169 - loss: 0.3273 - mae: 0.3770 - rmse: 0.5604 - smape: 0.7574 - val_ia: 0.5587 - val_loss: 0.2738 - val_mae: 0.3481 - val_rmse: 0.4554 - val_smape: 0.7342

Epoch 72/128

479/479 - 4s - 8ms/step - ia: 0.7182 - loss: 0.3238 - mae: 0.3765 - rmse: 0.5588 - smape: 0.7563 - val_ia: 0.5597 - val_loss: 0.2724 - val_mae: 0.3471 - val_rmse: 0.4542 - val_smape: 0.7327

Epoch 73/128

479/479 - 4s - 8ms/step - ia: 0.7184 - loss: 0.3240 - mae: 0.3757 - rmse: 0.5580 - smape: 0.7562 - val_ia: 0.5605 - val_loss: 0.2710 - val_mae: 0.3463 - val_rmse: 0.4532 - val_smape: 0.7315

Epoch 74/128

479/479 - 4s - 8ms/step - ia: 0.7194 - loss: 0.3210 - mae: 0.3748 - rmse: 0.5562 - smape: 0.7547 - val_ia: 0.5613 - val_loss: 0.2697 - val_mae: 0.3454 - val_rmse: 0.4522 - val_smape: 0.7303

Epoch 75/128

479/479 - 4s - 7ms/step - ia: 0.7203 - loss: 0.3207 - mae: 0.3740 - rmse: 0.5544 - smape: 0.7539 - val_ia: 0.5623 - val_loss: 0.2683 - val_mae: 0.3445 - val_rmse: 0.4511 - val_smape: 0.7289

Epoch 76/128

479/479 - 4s - 8ms/step - ia: 0.7211 - loss: 0.3206 - mae: 0.3730 - rmse: 0.5541 - smape: 0.7505 - val_ia: 0.5633 - val_loss: 0.2669 - val_mae: 0.3435 - val_rmse: 0.4501 - val_smape: 0.7275

Epoch 77/128

479/479 - 4s - 8ms/step - ia: 0.7211 - loss: 0.3209 - mae: 0.3732 - rmse: 0.5546 - smape: 0.7520 - val_ia: 0.5640 - val_loss: 0.2656 - val_mae: 0.3427 - val_rmse: 0.4491 - val_smape: 0.7264

Epoch 78/128

479/479 - 4s - 8ms/step - ia: 0.7219 - loss: 0.3178 - mae: 0.3719 - rmse: 0.5527 - smape: 0.7493 - val_ia: 0.5649 - val_loss: 0.2643 - val_mae: 0.3419 - val_rmse: 0.4481 - val_smape: 0.7253

Epoch 79/128

479/479 - 3s - 7ms/step - ia: 0.7223 - loss: 0.3155 - mae: 0.3710 - rmse: 0.5519 - smape: 0.7505 - val_ia: 0.5657 - val_loss: 0.2629 - val_mae: 0.3410 - val_rmse: 0.4470 - val_smape: 0.7241

Epoch 80/128

479/479 - 4s - 8ms/step - ia: 0.7236 - loss: 0.3164 - mae: 0.3702 - rmse: 0.5516 - smape: 0.7480 - val_ia: 0.5665 - val_loss: 0.2616 - val_mae: 0.3401 - val_rmse: 0.4460 - val_smape: 0.7228

Epoch 81/128

479/479 - 4s - 7ms/step - ia: 0.7240 - loss: 0.3130 - mae: 0.3690 - rmse: 0.5484 - smape: 0.7455 - val_ia: 0.5675 - val_loss: 0.2604 - val_mae: 0.3392 - val_rmse: 0.4450 - val_smape: 0.7216

Epoch 82/128

479/479 - 4s - 8ms/step - ia: 0.7247 - loss: 0.3114 - mae: 0.3680 - rmse: 0.5472 - smape: 0.7436 - val_ia: 0.5684 - val_loss: 0.2590 - val_mae: 0.3383 - val_rmse: 0.4440 - val_smape: 0.7202

Epoch 83/128

479/479 - 4s - 7ms/step - ia: 0.7246 - loss: 0.3125 - mae: 0.3687 - rmse: 0.5479 - smape: 0.7448 - val_ia: 0.5693 - val_loss: 0.2578 - val_mae: 0.3375 - val_rmse: 0.4430 - val_smape: 0.7190

Epoch 84/128

479/479 - 4s - 8ms/step - ia: 0.7271 - loss: 0.3093 - mae: 0.3660 - rmse: 0.5445 - smape: 0.7405 - val_ia: 0.5702 - val_loss: 0.2565 - val_mae: 0.3366 - val_rmse: 0.4421 - val_smape: 0.7178

Epoch 85/128

479/479 - 4s - 8ms/step - ia: 0.7271 - loss: 0.3065 - mae: 0.3657 - rmse: 0.5421 - smape: 0.7407 - val_ia: 0.5711 - val_loss: 0.2553 - val_mae: 0.3358 - val_rmse: 0.4411 - val_smape: 0.7167

Epoch 86/128

479/479 - 4s - 8ms/step - ia: 0.7283 - loss: 0.3056 - mae: 0.3643 - rmse: 0.5424 - smape: 0.7405 - val_ia: 0.5719 - val_loss: 0.2540 - val_mae: 0.3349 - val_rmse: 0.4401 - val_smape: 0.7154

Epoch 87/128

479/479 - 5s - 11ms/step - ia: 0.7290 - loss: 0.3058 - mae: 0.3640 - rmse: 0.5415 - smape: 0.7374 - val_ia: 0.5725 - val_loss: 0.2528 - val_mae: 0.3342 - val_rmse: 0.4391 - val_smape: 0.7145

Epoch 88/128

479/479 - 4s - 8ms/step - ia: 0.7285 - loss: 0.3037 - mae: 0.3638 - rmse: 0.5405 - smape: 0.7367 - val_ia: 0.5735 - val_loss: 0.2515 - val_mae: 0.3333 - val_rmse: 0.4381 - val_smape: 0.7132

Epoch 89/128

479/479 - 3s - 7ms/step - ia: 0.7284 - loss: 0.3032 - mae: 0.3637 - rmse: 0.5394 - smape: 0.7404 - val_ia: 0.5744 - val_loss: 0.2503 - val_mae: 0.3325 - val_rmse: 0.4372 - val_smape: 0.7121

Epoch 90/128

479/479 - 3s - 6ms/step - ia: 0.7299 - loss: 0.3018 - mae: 0.3626 - rmse: 0.5385 - smape: 0.7368 - val_ia: 0.5752 - val_loss: 0.2491 - val_mae: 0.3316 - val_rmse: 0.4361 - val_smape: 0.7108

Epoch 91/128

479/479 - 3s - 7ms/step - ia: 0.7307 - loss: 0.3007 - mae: 0.3607 - rmse: 0.5364 - smape: 0.7329 - val_ia: 0.5761 - val_loss: 0.2479 - val_mae: 0.3308 - val_rmse: 0.4352 - val_smape: 0.7094

Epoch 92/128

479/479 - 5s - 11ms/step - ia: 0.7309 - loss: 0.2992 - mae: 0.3610 - rmse: 0.5359 - smape: 0.7340 - val_ia: 0.5769 - val_loss: 0.2467 - val_mae: 0.3300 - val_rmse: 0.4343 - val_smape: 0.7081

Epoch 93/128

479/479 - 4s - 7ms/step - ia: 0.7327 - loss: 0.2973 - mae: 0.3593 - rmse: 0.5336 - smape: 0.7323 - val_ia: 0.5777 - val_loss: 0.2455 - val_mae: 0.3292 - val_rmse: 0.4333 - val_smape: 0.7070

Epoch 94/128

479/479 - 4s - 8ms/step - ia: 0.7328 - loss: 0.2974 - mae: 0.3586 - rmse: 0.5334 - smape: 0.7307 - val_ia: 0.5786 - val_loss: 0.2443 - val_mae: 0.3284 - val_rmse: 0.4324 - val_smape: 0.7059

Epoch 95/128

479/479 - 4s - 8ms/step - ia: 0.7320 - loss: 0.2964 - mae: 0.3592 - rmse: 0.5328 - smape: 0.7323 - val_ia: 0.5795 - val_loss: 0.2431 - val_mae: 0.3276 - val_rmse: 0.4314 - val_smape: 0.7045

Epoch 96/128

479/479 - 4s - 8ms/step - ia: 0.7336 - loss: 0.2949 - mae: 0.3575 - rmse: 0.5325 - smape: 0.7325 - val_ia: 0.5805 - val_loss: 0.2419 - val_mae: 0.3267 - val_rmse: 0.4304 - val_smape: 0.7033

Epoch 97/128

479/479 - 4s - 7ms/step - ia: 0.7330 - loss: 0.2935 - mae: 0.3578 - rmse: 0.5307 - smape: 0.7306 - val_ia: 0.5816 - val_loss: 0.2408 - val_mae: 0.3258 - val_rmse: 0.4295 - val_smape: 0.7019

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 11s - 45ms/step - ia: 0.2279 - loss: 1.2743 - mae: 0.9104 - rmse: 1.1252 - smape: 1.5620 - val_ia: 0.2499 - val_loss: 1.0649 - val_mae: 0.8363 - val_rmse: 0.9641 - val_smape: 1.6582

Epoch 2/128

240/240 - 4s - 17ms/step - ia: 0.2258 - loss: 1.2121 - mae: 0.8636 - rmse: 1.0969 - smape: 1.5466 - val_ia: 0.2548 - val_loss: 1.0108 - val_mae: 0.7890 - val_rmse: 0.9208 - val_smape: 1.7265

Epoch 3/128

240/240 - 4s - 16ms/step - ia: 0.2299 - loss: 1.1918 - mae: 0.8394 - rmse: 1.0869 - smape: 1.5305 - val_ia: 0.2526 - val_loss: 0.9885 - val_mae: 0.7642 - val_rmse: 0.8988 - val_smape: 1.7973

Epoch 4/128

240/240 - 4s - 17ms/step - ia: 0.2421 - loss: 1.1622 - mae: 0.8188 - rmse: 1.0720 - smape: 1.5053 - val_ia: 0.2520 - val_loss: 0.9790 - val_mae: 0.7524 - val_rmse: 0.8885 - val_smape: 1.8492

Epoch 5/128

240/240 - 4s - 17ms/step - ia: 0.2397 - loss: 1.1718 - mae: 0.8190 - rmse: 1.0778 - smape: 1.5063 - val_ia: 0.2519 - val_loss: 0.9730 - val_mae: 0.7452 - val_rmse: 0.8823 - val_smape: 1.8880

Epoch 6/128

240/240 - 4s - 16ms/step - ia: 0.2456 - loss: 1.1460 - mae: 0.8072 - rmse: 1.0654 - smape: 1.4957 - val_ia: 0.2525 - val_loss: 0.9689 - val_mae: 0.7410 - val_rmse: 0.8785 - val_smape: 1.9093

Epoch 7/128

240/240 - 5s - 22ms/step - ia: 0.2418 - loss: 1.1427 - mae: 0.8081 - rmse: 1.0634 - smape: 1.5066 - val_ia: 0.2533 - val_loss: 0.9651 - val_mae: 0.7376 - val_rmse: 0.8754 - val_smape: 1.9176

Epoch 8/128

240/240 - 4s - 16ms/step - ia: 0.2450 - loss: 1.1441 - mae: 0.8038 - rmse: 1.0629 - smape: 1.4987 - val_ia: 0.2542 - val_loss: 0.9622 - val_mae: 0.7364 - val_rmse: 0.8740 - val_smape: 1.9119

Epoch 9/128

240/240 - 5s - 23ms/step - ia: 0.2441 - loss: 1.1308 - mae: 0.7988 - rmse: 1.0575 - smape: 1.4993 - val_ia: 0.2551 - val_loss: 0.9592 - val_mae: 0.7349 - val_rmse: 0.8724 - val_smape: 1.9072

Epoch 10/128

240/240 - 4s - 18ms/step - ia: 0.2426 - loss: 1.1270 - mae: 0.7980 - rmse: 1.0560 - smape: 1.5008 - val_ia: 0.2560 - val_loss: 0.9559 - val_mae: 0.7328 - val_rmse: 0.8704 - val_smape: 1.9027

Epoch 11/128

240/240 - 5s - 20ms/step - ia: 0.2478 - loss: 1.1132 - mae: 0.7919 - rmse: 1.0495 - smape: 1.4905 - val_ia: 0.2570 - val_loss: 0.9529 - val_mae: 0.7315 - val_rmse: 0.8689 - val_smape: 1.8957

Epoch 12/128

240/240 - 4s - 16ms/step - ia: 0.2429 - loss: 1.1088 - mae: 0.7916 - rmse: 1.0471 - smape: 1.5016 - val_ia: 0.2581 - val_loss: 0.9503 - val_mae: 0.7314 - val_rmse: 0.8684 - val_smape: 1.8865

Epoch 13/128

240/240 - 4s - 16ms/step - ia: 0.2449 - loss: 1.1060 - mae: 0.7893 - rmse: 1.0467 - smape: 1.4929 - val_ia: 0.2591 - val_loss: 0.9468 - val_mae: 0.7294 - val_rmse: 0.8663 - val_smape: 1.8804

Epoch 14/128

240/240 - 4s - 17ms/step - ia: 0.2445 - loss: 1.0973 - mae: 0.7861 - rmse: 1.0421 - smape: 1.4954 - val_ia: 0.2602 - val_loss: 0.9435 - val_mae: 0.7278 - val_rmse: 0.8646 - val_smape: 1.8733

Epoch 15/128

240/240 - 5s - 21ms/step - ia: 0.2440 - loss: 1.0891 - mae: 0.7838 - rmse: 1.0383 - smape: 1.4988 - val_ia: 0.2613 - val_loss: 0.9399 - val_mae: 0.7259 - val_rmse: 0.8626 - val_smape: 1.8659

Epoch 16/128

240/240 - 4s - 16ms/step - ia: 0.2452 - loss: 1.0781 - mae: 0.7783 - rmse: 1.0325 - smape: 1.4956 - val_ia: 0.2624 - val_loss: 0.9363 - val_mae: 0.7238 - val_rmse: 0.8604 - val_smape: 1.8575

Epoch 17/128

240/240 - 5s - 22ms/step - ia: 0.2472 - loss: 1.0753 - mae: 0.7771 - rmse: 1.0317 - smape: 1.4899 - val_ia: 0.2637 - val_loss: 0.9327 - val_mae: 0.7224 - val_rmse: 0.8588 - val_smape: 1.8486

Epoch 18/128

240/240 - 4s - 17ms/step - ia: 0.2461 - loss: 1.0703 - mae: 0.7757 - rmse: 1.0285 - smape: 1.4971 - val_ia: 0.2650 - val_loss: 0.9290 - val_mae: 0.7207 - val_rmse: 0.8570 - val_smape: 1.8395

Epoch 19/128

240/240 - 5s - 22ms/step - ia: 0.2500 - loss: 1.0623 - mae: 0.7698 - rmse: 1.0252 - smape: 1.4878 - val_ia: 0.2664 - val_loss: 0.9253 - val_mae: 0.7196 - val_rmse: 0.8555 - val_smape: 1.8306

Epoch 20/128

240/240 - 4s - 16ms/step - ia: 0.2506 - loss: 1.0479 - mae: 0.7662 - rmse: 1.0174 - smape: 1.4875 - val_ia: 0.2679 - val_loss: 0.9215 - val_mae: 0.7183 - val_rmse: 0.8539 - val_smape: 1.8214

Epoch 21/128

240/240 - 4s - 16ms/step - ia: 0.2502 - loss: 1.0463 - mae: 0.7653 - rmse: 1.0168 - smape: 1.4879 - val_ia: 0.2694 - val_loss: 0.9173 - val_mae: 0.7163 - val_rmse: 0.8517 - val_smape: 1.8113

Epoch 22/128

240/240 - 4s - 19ms/step - ia: 0.2507 - loss: 1.0408 - mae: 0.7629 - rmse: 1.0150 - smape: 1.4874 - val_ia: 0.2710 - val_loss: 0.9128 - val_mae: 0.7141 - val_rmse: 0.8493 - val_smape: 1.8003

Epoch 23/128

240/240 - 5s - 20ms/step - ia: 0.2526 - loss: 1.0353 - mae: 0.7611 - rmse: 1.0115 - smape: 1.4860 - val_ia: 0.2726 - val_loss: 0.9081 - val_mae: 0.7116 - val_rmse: 0.8467 - val_smape: 1.7885

Epoch 24/128

240/240 - 4s - 17ms/step - ia: 0.2584 - loss: 1.0135 - mae: 0.7541 - rmse: 1.0018 - smape: 1.4781 - val_ia: 0.2745 - val_loss: 0.9035 - val_mae: 0.7101 - val_rmse: 0.8449 - val_smape: 1.7781

Epoch 25/128

240/240 - 4s - 16ms/step - ia: 0.2574 - loss: 1.0232 - mae: 0.7541 - rmse: 1.0056 - smape: 1.4780 - val_ia: 0.2764 - val_loss: 0.8987 - val_mae: 0.7083 - val_rmse: 0.8427 - val_smape: 1.7671

Epoch 26/128

240/240 - 5s - 22ms/step - ia: 0.2600 - loss: 1.0098 - mae: 0.7516 - rmse: 0.9989 - smape: 1.4764 - val_ia: 0.2784 - val_loss: 0.8934 - val_mae: 0.7058 - val_rmse: 0.8400 - val_smape: 1.7545

Epoch 27/128

240/240 - 4s - 17ms/step - ia: 0.2650 - loss: 0.9997 - mae: 0.7455 - rmse: 0.9934 - smape: 1.4694 - val_ia: 0.2805 - val_loss: 0.8879 - val_mae: 0.7031 - val_rmse: 0.8371 - val_smape: 1.7415

Epoch 28/128

240/240 - 4s - 18ms/step - ia: 0.2681 - loss: 0.9898 - mae: 0.7397 - rmse: 0.9899 - smape: 1.4626 - val_ia: 0.2828 - val_loss: 0.8825 - val_mae: 0.7014 - val_rmse: 0.8350 - val_smape: 1.7304

Epoch 29/128

240/240 - 4s - 16ms/step - ia: 0.2690 - loss: 0.9940 - mae: 0.7420 - rmse: 0.9911 - smape: 1.4604 - val_ia: 0.2851 - val_loss: 0.8766 - val_mae: 0.6988 - val_rmse: 0.8320 - val_smape: 1.7172

Epoch 30/128

240/240 - 6s - 23ms/step - ia: 0.2723 - loss: 0.9757 - mae: 0.7365 - rmse: 0.9821 - smape: 1.4592 - val_ia: 0.2877 - val_loss: 0.8701 - val_mae: 0.6954 - val_rmse: 0.8285 - val_smape: 1.7020

Epoch 31/128

240/240 - 4s - 18ms/step - ia: 0.2749 - loss: 0.9718 - mae: 0.7335 - rmse: 0.9800 - smape: 1.4538 - val_ia: 0.2903 - val_loss: 0.8633 - val_mae: 0.6919 - val_rmse: 0.8248 - val_smape: 1.6864

Epoch 32/128

240/240 - 5s - 20ms/step - ia: 0.2785 - loss: 0.9629 - mae: 0.7297 - rmse: 0.9760 - smape: 1.4478 - val_ia: 0.2933 - val_loss: 0.8566 - val_mae: 0.6896 - val_rmse: 0.8220 - val_smape: 1.6739

Epoch 33/128

240/240 - 4s - 17ms/step - ia: 0.2864 - loss: 0.9580 - mae: 0.7245 - rmse: 0.9715 - smape: 1.4343 - val_ia: 0.2964 - val_loss: 0.8492 - val_mae: 0.6860 - val_rmse: 0.8181 - val_smape: 1.6577

Epoch 34/128

240/240 - 4s - 17ms/step - ia: 0.2879 - loss: 0.9469 - mae: 0.7219 - rmse: 0.9674 - smape: 1.4339 - val_ia: 0.2997 - val_loss: 0.8420 - val_mae: 0.6841 - val_rmse: 0.8154 - val_smape: 1.6454

Epoch 35/128

240/240 - 4s - 17ms/step - ia: 0.2953 - loss: 0.9327 - mae: 0.7153 - rmse: 0.9597 - smape: 1.4238 - val_ia: 0.3032 - val_loss: 0.8337 - val_mae: 0.6799 - val_rmse: 0.8110 - val_smape: 1.6281

Epoch 36/128

240/240 - 5s - 21ms/step - ia: 0.2996 - loss: 0.9281 - mae: 0.7137 - rmse: 0.9584 - smape: 1.4166 - val_ia: 0.3071 - val_loss: 0.8249 - val_mae: 0.6755 - val_rmse: 0.8063 - val_smape: 1.6102

Epoch 37/128

240/240 - 5s - 22ms/step - ia: 0.3039 - loss: 0.9188 - mae: 0.7092 - rmse: 0.9521 - smape: 1.4114 - val_ia: 0.3114 - val_loss: 0.8155 - val_mae: 0.6702 - val_rmse: 0.8008 - val_smape: 1.5901

Epoch 38/128

240/240 - 5s - 21ms/step - ia: 0.3103 - loss: 0.9069 - mae: 0.7054 - rmse: 0.9469 - smape: 1.4069 - val_ia: 0.3159 - val_loss: 0.8058 - val_mae: 0.6656 - val_rmse: 0.7958 - val_smape: 1.5717

Epoch 39/128

240/240 - 4s - 16ms/step - ia: 0.3185 - loss: 0.8985 - mae: 0.7003 - rmse: 0.9429 - smape: 1.3912 - val_ia: 0.3205 - val_loss: 0.7960 - val_mae: 0.6620 - val_rmse: 0.7915 - val_smape: 1.5564

Epoch 40/128

240/240 - 4s - 17ms/step - ia: 0.3275 - loss: 0.8791 - mae: 0.6919 - rmse: 0.9322 - smape: 1.3793 - val_ia: 0.3257 - val_loss: 0.7854 - val_mae: 0.6579 - val_rmse: 0.7866 - val_smape: 1.5392

Epoch 41/128

240/240 - 4s - 18ms/step - ia: 0.3340 - loss: 0.8744 - mae: 0.6882 - rmse: 0.9297 - smape: 1.3680 - val_ia: 0.3316 - val_loss: 0.7738 - val_mae: 0.6521 - val_rmse: 0.7805 - val_smape: 1.5185

Epoch 42/128

240/240 - 4s - 16ms/step - ia: 0.3411 - loss: 0.8642 - mae: 0.6841 - rmse: 0.9240 - smape: 1.3597 - val_ia: 0.3383 - val_loss: 0.7613 - val_mae: 0.6450 - val_rmse: 0.7732 - val_smape: 1.4948

Epoch 43/128

240/240 - 5s - 19ms/step - ia: 0.3469 - loss: 0.8550 - mae: 0.6811 - rmse: 0.9195 - smape: 1.3530 - val_ia: 0.3452 - val_loss: 0.7486 - val_mae: 0.6387 - val_rmse: 0.7664 - val_smape: 1.4735

Epoch 44/128

240/240 - 5s - 22ms/step - ia: 0.3606 - loss: 0.8365 - mae: 0.6720 - rmse: 0.9080 - smape: 1.3338 - val_ia: 0.3512 - val_loss: 0.7363 - val_mae: 0.6358 - val_rmse: 0.7621 - val_smape: 1.4585

Epoch 45/128

240/240 - 4s - 18ms/step - ia: 0.3734 - loss: 0.8137 - mae: 0.6604 - rmse: 0.8957 - smape: 1.3112 - val_ia: 0.3592 - val_loss: 0.7221 - val_mae: 0.6284 - val_rmse: 0.7543 - val_smape: 1.4351

Epoch 46/128

240/240 - 4s - 17ms/step - ia: 0.3840 - loss: 0.8049 - mae: 0.6558 - rmse: 0.8903 - smape: 1.2981 - val_ia: 0.3675 - val_loss: 0.7072 - val_mae: 0.6206 - val_rmse: 0.7460 - val_smape: 1.4115

Epoch 47/128

240/240 - 5s - 21ms/step - ia: 0.3896 - loss: 0.7875 - mae: 0.6510 - rmse: 0.8818 - smape: 1.2948 - val_ia: 0.3769 - val_loss: 0.6915 - val_mae: 0.6118 - val_rmse: 0.7370 - val_smape: 1.3860

Epoch 48/128

240/240 - 4s - 17ms/step - ia: 0.4002 - loss: 0.7774 - mae: 0.6458 - rmse: 0.8757 - smape: 1.2823 - val_ia: 0.3854 - val_loss: 0.6759 - val_mae: 0.6053 - val_rmse: 0.7295 - val_smape: 1.3650

Epoch 49/128

240/240 - 5s - 21ms/step - ia: 0.4148 - loss: 0.7569 - mae: 0.6363 - rmse: 0.8646 - smape: 1.2605 - val_ia: 0.3952 - val_loss: 0.6592 - val_mae: 0.5966 - val_rmse: 0.7202 - val_smape: 1.3398

Epoch 50/128

240/240 - 5s - 21ms/step - ia: 0.4227 - loss: 0.7443 - mae: 0.6313 - rmse: 0.8574 - smape: 1.2509 - val_ia: 0.4057 - val_loss: 0.6415 - val_mae: 0.5868 - val_rmse: 0.7100 - val_smape: 1.3125

Epoch 51/128

240/240 - 5s - 23ms/step - ia: 0.4347 - loss: 0.7319 - mae: 0.6245 - rmse: 0.8494 - smape: 1.2309 - val_ia: 0.4153 - val_loss: 0.6241 - val_mae: 0.5786 - val_rmse: 0.7008 - val_smape: 1.2891

Epoch 52/128

240/240 - 4s - 16ms/step - ia: 0.4507 - loss: 0.7071 - mae: 0.6137 - rmse: 0.8353 - smape: 1.2090 - val_ia: 0.4272 - val_loss: 0.6051 - val_mae: 0.5664 - val_rmse: 0.6886 - val_smape: 1.2576

Epoch 53/128

240/240 - 4s - 16ms/step - ia: 0.4619 - loss: 0.6943 - mae: 0.6062 - rmse: 0.8269 - smape: 1.1906 - val_ia: 0.4369 - val_loss: 0.5868 - val_mae: 0.5580 - val_rmse: 0.6791 - val_smape: 1.2346

Epoch 54/128

240/240 - 4s - 16ms/step - ia: 0.4706 - loss: 0.6814 - mae: 0.6012 - rmse: 0.8199 - smape: 1.1844 - val_ia: 0.4473 - val_loss: 0.5680 - val_mae: 0.5484 - val_rmse: 0.6685 - val_smape: 1.2098

Epoch 55/128

240/240 - 5s - 19ms/step - ia: 0.4793 - loss: 0.6694 - mae: 0.5965 - rmse: 0.8129 - smape: 1.1710 - val_ia: 0.4588 - val_loss: 0.5482 - val_mae: 0.5369 - val_rmse: 0.6565 - val_smape: 1.1809

Epoch 56/128

240/240 - 5s - 19ms/step - ia: 0.4954 - loss: 0.6486 - mae: 0.5850 - rmse: 0.7996 - smape: 1.1446 - val_ia: 0.4699 - val_loss: 0.5284 - val_mae: 0.5258 - val_rmse: 0.6446 - val_smape: 1.1527

Epoch 57/128

240/240 - 4s - 16ms/step - ia: 0.5063 - loss: 0.6346 - mae: 0.5789 - rmse: 0.7915 - smape: 1.1340 - val_ia: 0.4799 - val_loss: 0.5092 - val_mae: 0.5161 - val_rmse: 0.6337 - val_smape: 1.1293

Epoch 58/128

240/240 - 6s - 25ms/step - ia: 0.5164 - loss: 0.6151 - mae: 0.5717 - rmse: 0.7802 - smape: 1.1183 - val_ia: 0.4913 - val_loss: 0.4898 - val_mae: 0.5044 - val_rmse: 0.6214 - val_smape: 1.1008

Epoch 59/128

240/240 - 5s - 20ms/step - ia: 0.5268 - loss: 0.5982 - mae: 0.5659 - rmse: 0.7673 - smape: 1.1036 - val_ia: 0.5013 - val_loss: 0.4709 - val_mae: 0.4948 - val_rmse: 0.6106 - val_smape: 1.0783

Epoch 60/128

240/240 - 4s - 15ms/step - ia: 0.5379 - loss: 0.5849 - mae: 0.5591 - rmse: 0.7598 - smape: 1.0904 - val_ia: 0.5136 - val_loss: 0.4516 - val_mae: 0.4816 - val_rmse: 0.5973 - val_smape: 1.0461

Epoch 61/128

240/240 - 4s - 17ms/step - ia: 0.5499 - loss: 0.5697 - mae: 0.5502 - rmse: 0.7494 - smape: 1.0667 - val_ia: 0.5236 - val_loss: 0.4337 - val_mae: 0.4719 - val_rmse: 0.5864 - val_smape: 1.0243

Epoch 62/128

240/240 - 5s - 22ms/step - ia: 0.5587 - loss: 0.5532 - mae: 0.5438 - rmse: 0.7386 - smape: 1.0579 - val_ia: 0.5342 - val_loss: 0.4161 - val_mae: 0.4612 - val_rmse: 0.5750 - val_smape: 0.9996

Epoch 63/128

240/240 - 4s - 17ms/step - ia: 0.5691 - loss: 0.5396 - mae: 0.5375 - rmse: 0.7298 - smape: 1.0420 - val_ia: 0.5429 - val_loss: 0.3999 - val_mae: 0.4528 - val_rmse: 0.5653 - val_smape: 0.9820

Epoch 64/128

240/240 - 4s - 17ms/step - ia: 0.5788 - loss: 0.5266 - mae: 0.5307 - rmse: 0.7206 - smape: 1.0293 - val_ia: 0.5542 - val_loss: 0.3838 - val_mae: 0.4409 - val_rmse: 0.5534 - val_smape: 0.9535

Epoch 65/128

240/240 - 4s - 16ms/step - ia: 0.5846 - loss: 0.5190 - mae: 0.5270 - rmse: 0.7162 - smape: 1.0191 - val_ia: 0.5623 - val_loss: 0.3694 - val_mae: 0.4329 - val_rmse: 0.5444 - val_smape: 0.9372

Epoch 66/128

240/240 - 4s - 17ms/step - ia: 0.5929 - loss: 0.5051 - mae: 0.5213 - rmse: 0.7060 - smape: 1.0068 - val_ia: 0.5735 - val_loss: 0.3551 - val_mae: 0.4210 - val_rmse: 0.5329 - val_smape: 0.9086

Epoch 67/128

240/240 - 5s - 21ms/step - ia: 0.6026 - loss: 0.4891 - mae: 0.5135 - rmse: 0.6951 - smape: 0.9931 - val_ia: 0.5806 - val_loss: 0.3426 - val_mae: 0.4140 - val_rmse: 0.5250 - val_smape: 0.8948

Epoch 68/128

240/240 - 5s - 22ms/step - ia: 0.6070 - loss: 0.4842 - mae: 0.5115 - rmse: 0.6918 - smape: 0.9855 - val_ia: 0.5897 - val_loss: 0.3307 - val_mae: 0.4047 - val_rmse: 0.5157 - val_smape: 0.8732

Epoch 69/128

240/240 - 4s - 16ms/step - ia: 0.6158 - loss: 0.4708 - mae: 0.5031 - rmse: 0.6808 - smape: 0.9710 - val_ia: 0.5955 - val_loss: 0.3206 - val_mae: 0.3989 - val_rmse: 0.5093 - val_smape: 0.8629

Epoch 70/128

240/240 - 4s - 17ms/step - ia: 0.6195 - loss: 0.4658 - mae: 0.5018 - rmse: 0.6778 - smape: 0.9683 - val_ia: 0.6026 - val_loss: 0.3108 - val_mae: 0.3917 - val_rmse: 0.5018 - val_smape: 0.8479

Epoch 71/128

240/240 - 4s - 16ms/step - ia: 0.6242 - loss: 0.4610 - mae: 0.4985 - rmse: 0.6747 - smape: 0.9568 - val_ia: 0.6091 - val_loss: 0.3023 - val_mae: 0.3850 - val_rmse: 0.4951 - val_smape: 0.8334

Epoch 72/128

240/240 - 4s - 16ms/step - ia: 0.6304 - loss: 0.4502 - mae: 0.4919 - rmse: 0.6665 - smape: 0.9480 - val_ia: 0.6158 - val_loss: 0.2942 - val_mae: 0.3782 - val_rmse: 0.4884 - val_smape: 0.8183

Epoch 73/128

240/240 - 4s - 16ms/step - ia: 0.6335 - loss: 0.4417 - mae: 0.4897 - rmse: 0.6603 - smape: 0.9490 - val_ia: 0.6217 - val_loss: 0.2872 - val_mae: 0.3721 - val_rmse: 0.4825 - val_smape: 0.8055

Epoch 74/128

240/240 - 5s - 22ms/step - ia: 0.6389 - loss: 0.4311 - mae: 0.4840 - rmse: 0.6523 - smape: 0.9415 - val_ia: 0.6248 - val_loss: 0.2807 - val_mae: 0.3689 - val_rmse: 0.4787 - val_smape: 0.8014

Epoch 75/128

240/240 - 4s - 17ms/step - ia: 0.6404 - loss: 0.4357 - mae: 0.4845 - rmse: 0.6560 - smape: 0.9395 - val_ia: 0.6305 - val_loss: 0.2751 - val_mae: 0.3630 - val_rmse: 0.4732 - val_smape: 0.7880

Epoch 76/128

240/240 - 4s - 16ms/step - ia: 0.6468 - loss: 0.4194 - mae: 0.4774 - rmse: 0.6438 - smape: 0.9268 - val_ia: 0.6324 - val_loss: 0.2703 - val_mae: 0.3608 - val_rmse: 0.4706 - val_smape: 0.7859

Epoch 77/128

240/240 - 4s - 17ms/step - ia: 0.6494 - loss: 0.4193 - mae: 0.4754 - rmse: 0.6440 - smape: 0.9224 - val_ia: 0.6369 - val_loss: 0.2657 - val_mae: 0.3561 - val_rmse: 0.4662 - val_smape: 0.7753

Epoch 78/128

240/240 - 5s - 22ms/step - ia: 0.6533 - loss: 0.4150 - mae: 0.4713 - rmse: 0.6399 - smape: 0.9163 - val_ia: 0.6391 - val_loss: 0.2617 - val_mae: 0.3534 - val_rmse: 0.4634 - val_smape: 0.7712

Epoch 79/128

240/240 - 6s - 23ms/step - ia: 0.6555 - loss: 0.4082 - mae: 0.4677 - rmse: 0.6351 - smape: 0.9117 - val_ia: 0.6410 - val_loss: 0.2581 - val_mae: 0.3509 - val_rmse: 0.4608 - val_smape: 0.7674

Epoch 80/128

240/240 - 4s - 17ms/step - ia: 0.6597 - loss: 0.4025 - mae: 0.4643 - rmse: 0.6299 - smape: 0.9023 - val_ia: 0.6424 - val_loss: 0.2548 - val_mae: 0.3491 - val_rmse: 0.4587 - val_smape: 0.7654

Epoch 81/128

240/240 - 4s - 16ms/step - ia: 0.6601 - loss: 0.3978 - mae: 0.4636 - rmse: 0.6265 - smape: 0.9046 - val_ia: 0.6454 - val_loss: 0.2518 - val_mae: 0.3458 - val_rmse: 0.4557 - val_smape: 0.7584

Epoch 82/128

240/240 - 4s - 16ms/step - ia: 0.6632 - loss: 0.3944 - mae: 0.4588 - rmse: 0.6237 - smape: 0.8964 - val_ia: 0.6480 - val_loss: 0.2487 - val_mae: 0.3429 - val_rmse: 0.4530 - val_smape: 0.7528

Epoch 83/128

240/240 - 5s - 23ms/step - ia: 0.6651 - loss: 0.3907 - mae: 0.4570 - rmse: 0.6207 - smape: 0.8977 - val_ia: 0.6509 - val_loss: 0.2461 - val_mae: 0.3397 - val_rmse: 0.4502 - val_smape: 0.7453

Epoch 84/128

240/240 - 4s - 16ms/step - ia: 0.6679 - loss: 0.3862 - mae: 0.4536 - rmse: 0.6169 - smape: 0.8898 - val_ia: 0.6537 - val_loss: 0.2437 - val_mae: 0.3368 - val_rmse: 0.4476 - val_smape: 0.7379

Epoch 85/128

240/240 - 4s - 18ms/step - ia: 0.6707 - loss: 0.3804 - mae: 0.4506 - rmse: 0.6129 - smape: 0.8851 - val_ia: 0.6535 - val_loss: 0.2416 - val_mae: 0.3362 - val_rmse: 0.4467 - val_smape: 0.7390

Epoch 86/128

240/240 - 5s - 20ms/step - ia: 0.6684 - loss: 0.3831 - mae: 0.4513 - rmse: 0.6144 - smape: 0.8918 - val_ia: 0.6554 - val_loss: 0.2395 - val_mae: 0.3342 - val_rmse: 0.4448 - val_smape: 0.7348

Epoch 87/128

240/240 - 4s - 16ms/step - ia: 0.6729 - loss: 0.3748 - mae: 0.4473 - rmse: 0.6076 - smape: 0.8809 - val_ia: 0.6566 - val_loss: 0.2374 - val_mae: 0.3327 - val_rmse: 0.4432 - val_smape: 0.7321

Epoch 88/128

240/240 - 4s - 16ms/step - ia: 0.6742 - loss: 0.3742 - mae: 0.4458 - rmse: 0.6087 - smape: 0.8809 - val_ia: 0.6569 - val_loss: 0.2358 - val_mae: 0.3317 - val_rmse: 0.4421 - val_smape: 0.7309

Epoch 89/128

240/240 - 4s - 17ms/step - ia: 0.6762 - loss: 0.3731 - mae: 0.4434 - rmse: 0.6064 - smape: 0.8744 - val_ia: 0.6580 - val_loss: 0.2344 - val_mae: 0.3303 - val_rmse: 0.4407 - val_smape: 0.7280

Epoch 90/128

240/240 - 4s - 17ms/step - ia: 0.6791 - loss: 0.3653 - mae: 0.4396 - rmse: 0.6009 - smape: 0.8712 - val_ia: 0.6595 - val_loss: 0.2327 - val_mae: 0.3287 - val_rmse: 0.4392 - val_smape: 0.7250

Epoch 91/128

240/240 - 4s - 18ms/step - ia: 0.6802 - loss: 0.3652 - mae: 0.4381 - rmse: 0.5996 - smape: 0.8670 - val_ia: 0.6611 - val_loss: 0.2311 - val_mae: 0.3269 - val_rmse: 0.4375 - val_smape: 0.7211

Epoch 92/128

240/240 - 5s - 20ms/step - ia: 0.6821 - loss: 0.3634 - mae: 0.4356 - rmse: 0.5984 - smape: 0.8644 - val_ia: 0.6621 - val_loss: 0.2297 - val_mae: 0.3256 - val_rmse: 0.4363 - val_smape: 0.7185

Epoch 93/128

240/240 - 5s - 23ms/step - ia: 0.6840 - loss: 0.3595 - mae: 0.4331 - rmse: 0.5956 - smape: 0.8583 - val_ia: 0.6617 - val_loss: 0.2285 - val_mae: 0.3254 - val_rmse: 0.4357 - val_smape: 0.7194

Epoch 94/128

240/240 - 4s - 16ms/step - ia: 0.6846 - loss: 0.3568 - mae: 0.4320 - rmse: 0.5930 - smape: 0.8601 - val_ia: 0.6633 - val_loss: 0.2273 - val_mae: 0.3237 - val_rmse: 0.4342 - val_smape: 0.7153

Epoch 95/128

240/240 - 4s - 17ms/step - ia: 0.6857 - loss: 0.3522 - mae: 0.4300 - rmse: 0.5897 - smape: 0.8578 - val_ia: 0.6642 - val_loss: 0.2261 - val_mae: 0.3226 - val_rmse: 0.4332 - val_smape: 0.7135

Epoch 96/128

240/240 - 4s - 16ms/step - ia: 0.6855 - loss: 0.3559 - mae: 0.4310 - rmse: 0.5920 - smape: 0.8574 - val_ia: 0.6637 - val_loss: 0.2251 - val_mae: 0.3225 - val_rmse: 0.4326 - val_smape: 0.7139

Epoch 97/128

240/240 - 4s - 17ms/step - ia: 0.6864 - loss: 0.3512 - mae: 0.4286 - rmse: 0.5884 - smape: 0.8582 - val_ia: 0.6651 - val_loss: 0.2241 - val_mae: 0.3210 - val_rmse: 0.4314 - val_smape: 0.7107

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 7s - 27ms/step - ia: 0.8431 - loss: 0.1278 - mae: 0.2223 - rmse: 0.3383 - smape: 0.4976 - val_ia: 0.8575 - val_loss: 0.0604 - val_mae: 0.1454 - val_rmse: 0.2232 - val_smape: 0.3740

Epoch 2/128

240/240 - 5s - 19ms/step - ia: 0.8759 - loss: 0.0846 - mae: 0.1800 - rmse: 0.2849 - smape: 0.4139 - val_ia: 0.8521 - val_loss: 0.0648 - val_mae: 0.1504 - val_rmse: 0.2288 - val_smape: 0.3743

Epoch 3/128

240/240 - 2s - 9ms/step - ia: 0.8779 - loss: 0.0830 - mae: 0.1773 - rmse: 0.2822 - smape: 0.4110 - val_ia: 0.8731 - val_loss: 0.0593 - val_mae: 0.1341 - val_rmse: 0.2221 - val_smape: 0.3515

Epoch 4/128

240/240 - 2s - 10ms/step - ia: 0.8782 - loss: 0.0827 - mae: 0.1774 - rmse: 0.2812 - smape: 0.4114 - val_ia: 0.8630 - val_loss: 0.0569 - val_mae: 0.1380 - val_rmse: 0.2192 - val_smape: 0.3689

Epoch 5/128

240/240 - 2s - 8ms/step - ia: 0.8783 - loss: 0.0820 - mae: 0.1772 - rmse: 0.2795 - smape: 0.4087 - val_ia: 0.8675 - val_loss: 0.0571 - val_mae: 0.1361 - val_rmse: 0.2174 - val_smape: 0.3548

Epoch 6/128

240/240 - 3s - 11ms/step - ia: 0.8787 - loss: 0.0835 - mae: 0.1765 - rmse: 0.2824 - smape: 0.4071 - val_ia: 0.8567 - val_loss: 0.0618 - val_mae: 0.1463 - val_rmse: 0.2247 - val_smape: 0.3661

Epoch 7/128

240/240 - 2s - 8ms/step - ia: 0.8796 - loss: 0.0801 - mae: 0.1747 - rmse: 0.2765 - smape: 0.4037 - val_ia: 0.8432 - val_loss: 0.0704 - val_mae: 0.1599 - val_rmse: 0.2390 - val_smape: 0.3922

Epoch 8/128

240/240 - 2s - 8ms/step - ia: 0.8768 - loss: 0.0848 - mae: 0.1792 - rmse: 0.2846 - smape: 0.4112 - val_ia: 0.8637 - val_loss: 0.0582 - val_mae: 0.1394 - val_rmse: 0.2205 - val_smape: 0.3626

Epoch 9/128

240/240 - 3s - 11ms/step - ia: 0.8613 - loss: 0.1163 - mae: 0.1997 - rmse: 0.3200 - smape: 0.4441 - val_ia: 0.7350 - val_loss: 0.1232 - val_mae: 0.2491 - val_rmse: 0.3221 - val_smape: 0.5505

Epoch 10/128

240/240 - 2s - 8ms/step - ia: 0.0597 - loss: 56349163520.0000 - mae: 66699.6562 - rmse: 130335.9141 - smape: 1.8406 - val_ia: 5.8231e-06 - val_loss: 411914076160.0000 - val_mae: 355477.6250 - val_rmse: 509551.2500 - val_smape: 1.9997

Epoch 11/128

240/240 - 3s - 11ms/step - ia: 1.3612e-05 - loss: 302092877824.0000 - mae: 200111.1875 - rmse: 361584.7812 - smape: 1.9991 - val_ia: 4.4376e-05 - val_loss: 1823114368.0000 - val_mae: 23277.7402 - val_rmse: 37134.2891 - val_smape: 1.9990

Epoch 12/128

240/240 - 3s - 12ms/step - ia: 5.7029e-05 - loss: 1141892992.0000 - mae: 15224.0410 - rmse: 30734.6055 - smape: 1.9956 - val_ia: 1.0599e-04 - val_loss: 304793632.0000 - val_mae: 6894.8623 - val_rmse: 15724.0547 - val_smape: 1.9945

Epoch 13/128

240/240 - 2s - 10ms/step - ia: 9.0524e-05 - loss: 610385920.0000 - mae: 9087.2900 - rmse: 23146.0098 - smape: 1.9932 - val_ia: 1.5506e-04 - val_loss: 184865408.0000 - val_mae: 5173.2930 - val_rmse: 12353.7490 - val_smape: 1.9949

Epoch 14/128

240/240 - 2s - 9ms/step - ia: 1.1389e-04 - loss: 590968512.0000 - mae: 7117.4971 - rmse: 21084.3535 - smape: 1.9915 - val_ia: 1.4722e-04 - val_loss: 149763792.0000 - val_mae: 4655.5200 - val_rmse: 11080.5107 - val_smape: 1.9953

Epoch 15/128

240/240 - 3s - 11ms/step - ia: 1.3041e-04 - loss: 572111808.0000 - mae: 6657.2388 - rmse: 20281.8184 - smape: 1.9912 - val_ia: 3.1938e-04 - val_loss: 39259480.0000 - val_mae: 2125.3760 - val_rmse: 5479.6372 - val_smape: 1.9843

Epoch 16/128

240/240 - 2s - 8ms/step - ia: 1.9163e-04 - loss: 140127520.0000 - mae: 4134.6519 - rmse: 11190.1426 - smape: 1.9881 - val_ia: 3.8728e-04 - val_loss: 26762006.0000 - val_mae: 1848.5303 - val_rmse: 4668.3467 - val_smape: 1.9756

Epoch 17/128

240/240 - 2s - 9ms/step - ia: 2.2486e-04 - loss: 105755728.0000 - mae: 3650.7925 - rmse: 9563.0488 - smape: 1.9870 - val_ia: 3.8809e-04 - val_loss: 30275774.0000 - val_mae: 1759.4363 - val_rmse: 4600.9028 - val_smape: 1.9879

Epoch 18/128

240/240 - 3s - 11ms/step - ia: 2.8718e-04 - loss: 62271632.0000 - mae: 2872.4243 - rmse: 7349.6104 - smape: 1.9836 - val_ia: 6.1365e-04 - val_loss: 16450474.0000 - val_mae: 1280.3815 - val_rmse: 3209.2314 - val_smape: 1.9801

Epoch 19/128

240/240 - 3s - 11ms/step - ia: 4.3136e-04 - loss: 27907774.0000 - mae: 1931.0309 - rmse: 4846.0225 - smape: 1.9802 - val_ia: 7.1878e-04 - val_loss: 9912352.0000 - val_mae: 1020.0133 - val_rmse: 2658.2065 - val_smape: 1.9696

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 41s 306ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 58%|█████▊    | 7/12 [2:49:43<1:18:07, 937.59s/trial, best loss: 0.03682275219635514]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 45s - 12ms/step - ia: 0.8151 - loss: 0.1360 - mae: 0.2281 - rmse: 0.3121 - smape: 0.4984 - val_ia: 0.5582 - val_loss: 0.0580 - val_mae: 0.1364 - val_rmse: 0.1789 - val_smape: 0.3603

Epoch 2/128

3832/3832 - 35s - 9ms/step - ia: 0.8467 - loss: 0.0919 - mae: 0.1916 - rmse: 0.2630 - smape: 0.4293 - val_ia: 0.5083 - val_loss: 0.0750 - val_mae: 0.1657 - val_rmse: 0.2078 - val_smape: 0.3828

Epoch 3/128

3832/3832 - 37s - 10ms/step - ia: 0.8503 - loss: 0.0887 - mae: 0.1868 - rmse: 0.2557 - smape: 0.4252 - val_ia: 0.5355 - val_loss: 0.0579 - val_mae: 0.1424 - val_rmse: 0.1827 - val_smape: 0.3667

Epoch 4/128

3832/3832 - 34s - 9ms/step - ia: 0.8515 - loss: 0.0869 - mae: 0.1848 - rmse: 0.2532 - smape: 0.4230 - val_ia: 0.5506 - val_loss: 0.0610 - val_mae: 0.1408 - val_rmse: 0.1838 - val_smape: 0.3556

Epoch 5/128

3832/3832 - 38s - 10ms/step - ia: 0.8536 - loss: 0.0837 - mae: 0.1819 - rmse: 0.2494 - smape: 0.4188 - val_ia: 0.5286 - val_loss: 0.0668 - val_mae: 0.1544 - val_rmse: 0.1931 - val_smape: 0.3798

Epoch 6/128

3832/3832 - 34s - 9ms/step - ia: 0.8558 - loss: 0.0825 - mae: 0.1797 - rmse: 0.2469 - smape: 0.4172 - val_ia: 0.5567 - val_loss: 0.0562 - val_mae: 0.1341 - val_rmse: 0.1754 - val_smape: 0.3535

Epoch 7/128

3832/3832 - 34s - 9ms/step - ia: 0.8574 - loss: 0.0838 - mae: 0.1784 - rmse: 0.2469 - smape: 0.4135 - val_ia: 0.5418 - val_loss: 0.0624 - val_mae: 0.1437 - val_rmse: 0.1858 - val_smape: 0.3611

Epoch 8/128

3832/3832 - 40s - 11ms/step - ia: 0.8581 - loss: 0.0799 - mae: 0.1763 - rmse: 0.2429 - smape: 0.4124 - val_ia: 0.5195 - val_loss: 0.0647 - val_mae: 0.1505 - val_rmse: 0.1913 - val_smape: 0.3873

Epoch 9/128

3832/3832 - 34s - 9ms/step - ia: 0.8584 - loss: 0.0812 - mae: 0.1770 - rmse: 0.2443 - smape: 0.4131 - val_ia: 0.5446 - val_loss: 0.0580 - val_mae: 0.1425 - val_rmse: 0.1812 - val_smape: 0.3635

Epoch 10/128

3832/3832 - 35s - 9ms/step - ia: 0.8597 - loss: 0.0797 - mae: 0.1741 - rmse: 0.2405 - smape: 0.4114 - val_ia: 0.5471 - val_loss: 0.0566 - val_mae: 0.1395 - val_rmse: 0.1809 - val_smape: 0.3641

Epoch 11/128

3832/3832 - 34s - 9ms/step - ia: 0.8608 - loss: 0.0780 - mae: 0.1737 - rmse: 0.2399 - smape: 0.4122 - val_ia: 0.5357 - val_loss: 0.0577 - val_mae: 0.1441 - val_rmse: 0.1838 - val_smape: 0.3740

Epoch 12/128

3832/3832 - 32s - 8ms/step - ia: 0.8605 - loss: 0.0757 - mae: 0.1726 - rmse: 0.2373 - smape: 0.4077 - val_ia: 0.5586 - val_loss: 0.0552 - val_mae: 0.1344 - val_rmse: 0.1746 - val_smape: 0.3553

Epoch 13/128

3832/3832 - 34s - 9ms/step - ia: 0.8619 - loss: 0.0767 - mae: 0.1730 - rmse: 0.2388 - smape: 0.4099 - val_ia: 0.5444 - val_loss: 0.0613 - val_mae: 0.1443 - val_rmse: 0.1839 - val_smape: 0.3710

Epoch 14/128

3832/3832 - 41s - 11ms/step - ia: 0.8629 - loss: 0.0759 - mae: 0.1706 - rmse: 0.2358 - smape: 0.4058 - val_ia: 0.5551 - val_loss: 0.0542 - val_mae: 0.1344 - val_rmse: 0.1748 - val_smape: 0.3581

Epoch 15/128

3832/3832 - 34s - 9ms/step - ia: 0.8639 - loss: 0.0750 - mae: 0.1702 - rmse: 0.2356 - smape: 0.4022 - val_ia: 0.5534 - val_loss: 0.0540 - val_mae: 0.1340 - val_rmse: 0.1738 - val_smape: 0.3596

Epoch 16/128

3832/3832 - 34s - 9ms/step - ia: 0.8640 - loss: 0.0742 - mae: 0.1695 - rmse: 0.2345 - smape: 0.4045 - val_ia: 0.5404 - val_loss: 0.0549 - val_mae: 0.1388 - val_rmse: 0.1776 - val_smape: 0.3604

Epoch 17/128

3832/3832 - 34s - 9ms/step - ia: 0.8637 - loss: 0.0746 - mae: 0.1704 - rmse: 0.2355 - smape: 0.4047 - val_ia: 0.5617 - val_loss: 0.0546 - val_mae: 0.1336 - val_rmse: 0.1747 - val_smape: 0.3616

Epoch 18/128

3832/3832 - 42s - 11ms/step - ia: 0.8649 - loss: 0.0744 - mae: 0.1693 - rmse: 0.2334 - smape: 0.4016 - val_ia: 0.5402 - val_loss: 0.0562 - val_mae: 0.1395 - val_rmse: 0.1796 - val_smape: 0.3614

Epoch 19/128

3832/3832 - 37s - 10ms/step - ia: 0.8647 - loss: 0.0740 - mae: 0.1691 - rmse: 0.2340 - smape: 0.4036 - val_ia: 0.5146 - val_loss: 0.0587 - val_mae: 0.1520 - val_rmse: 0.1906 - val_smape: 0.3857

Epoch 20/128

3832/3832 - 33s - 9ms/step - ia: 0.8655 - loss: 0.0724 - mae: 0.1680 - rmse: 0.2322 - smape: 0.4015 - val_ia: 0.5352 - val_loss: 0.0563 - val_mae: 0.1427 - val_rmse: 0.1809 - val_smape: 0.3704

Epoch 21/128

3832/3832 - 43s - 11ms/step - ia: 0.8660 - loss: 0.0711 - mae: 0.1673 - rmse: 0.2309 - smape: 0.3994 - val_ia: 0.5435 - val_loss: 0.0558 - val_mae: 0.1375 - val_rmse: 0.1777 - val_smape: 0.3622

Epoch 22/128

3832/3832 - 35s - 9ms/step - ia: 0.8655 - loss: 0.0735 - mae: 0.1677 - rmse: 0.2321 - smape: 0.4010 - val_ia: 0.5601 - val_loss: 0.0541 - val_mae: 0.1323 - val_rmse: 0.1721 - val_smape: 0.3589

Epoch 23/128

3832/3832 - 34s - 9ms/step - ia: 0.8656 - loss: 0.0728 - mae: 0.1676 - rmse: 0.2317 - smape: 0.4015 - val_ia: 0.5389 - val_loss: 0.0565 - val_mae: 0.1402 - val_rmse: 0.1790 - val_smape: 0.3642

Epoch 24/128

3832/3832 - 34s - 9ms/step - ia: 0.8660 - loss: 0.0719 - mae: 0.1674 - rmse: 0.2311 - smape: 0.4002 - val_ia: 0.5508 - val_loss: 0.0565 - val_mae: 0.1380 - val_rmse: 0.1785 - val_smape: 0.3563

Epoch 25/128

3832/3832 - 35s - 9ms/step - ia: 0.8663 - loss: 0.0696 - mae: 0.1659 - rmse: 0.2291 - smape: 0.3966 - val_ia: 0.5549 - val_loss: 0.0572 - val_mae: 0.1370 - val_rmse: 0.1788 - val_smape: 0.3588

Epoch 26/128

3832/3832 - 41s - 11ms/step - ia: 0.8667 - loss: 0.0692 - mae: 0.1661 - rmse: 0.2290 - smape: 0.4003 - val_ia: 0.5732 - val_loss: 0.0534 - val_mae: 0.1292 - val_rmse: 0.1701 - val_smape: 0.3455

Epoch 27/128

3832/3832 - 34s - 9ms/step - ia: 0.8667 - loss: 0.0701 - mae: 0.1664 - rmse: 0.2298 - smape: 0.4028 - val_ia: 0.5718 - val_loss: 0.0532 - val_mae: 0.1305 - val_rmse: 0.1708 - val_smape: 0.3522

Epoch 28/128

3832/3832 - 35s - 9ms/step - ia: 0.8665 - loss: 0.0696 - mae: 0.1659 - rmse: 0.2293 - smape: 0.3990 - val_ia: 0.5567 - val_loss: 0.0578 - val_mae: 0.1374 - val_rmse: 0.1766 - val_smape: 0.3543

Epoch 29/128

3832/3832 - 34s - 9ms/step - ia: 0.8660 - loss: 0.0702 - mae: 0.1663 - rmse: 0.2293 - smape: 0.3995 - val_ia: 0.5073 - val_loss: 0.0607 - val_mae: 0.1550 - val_rmse: 0.1953 - val_smape: 0.4086

Epoch 30/128

3832/3832 - 40s - 11ms/step - ia: 0.8665 - loss: 0.0692 - mae: 0.1653 - rmse: 0.2293 - smape: 0.3972 - val_ia: 0.5641 - val_loss: 0.0526 - val_mae: 0.1296 - val_rmse: 0.1696 - val_smape: 0.3466

Epoch 31/128

3832/3832 - 34s - 9ms/step - ia: 0.8684 - loss: 0.0682 - mae: 0.1644 - rmse: 0.2270 - smape: 0.3965 - val_ia: 0.5468 - val_loss: 0.0589 - val_mae: 0.1406 - val_rmse: 0.1794 - val_smape: 0.3653

Epoch 32/128

3832/3832 - 33s - 9ms/step - ia: 0.8670 - loss: 0.0681 - mae: 0.1652 - rmse: 0.2273 - smape: 0.3991 - val_ia: 0.5641 - val_loss: 0.0607 - val_mae: 0.1358 - val_rmse: 0.1775 - val_smape: 0.3529

Epoch 33/128

3832/3832 - 34s - 9ms/step - ia: 0.8684 - loss: 0.0679 - mae: 0.1635 - rmse: 0.2253 - smape: 0.3946 - val_ia: 0.5659 - val_loss: 0.0550 - val_mae: 0.1315 - val_rmse: 0.1726 - val_smape: 0.3474

Epoch 34/128

3832/3832 - 33s - 9ms/step - ia: 0.8686 - loss: 0.0679 - mae: 0.1640 - rmse: 0.2263 - smape: 0.3955 - val_ia: 0.5544 - val_loss: 0.0561 - val_mae: 0.1345 - val_rmse: 0.1737 - val_smape: 0.3516

Epoch 35/128

3832/3832 - 42s - 11ms/step - ia: 0.8682 - loss: 0.0680 - mae: 0.1639 - rmse: 0.2263 - smape: 0.3963 - val_ia: 0.5566 - val_loss: 0.0636 - val_mae: 0.1439 - val_rmse: 0.1826 - val_smape: 0.3596

Epoch 36/128

3832/3832 - 33s - 9ms/step - ia: 0.8687 - loss: 0.0676 - mae: 0.1635 - rmse: 0.2249 - smape: 0.3953 - val_ia: 0.5344 - val_loss: 0.0573 - val_mae: 0.1404 - val_rmse: 0.1800 - val_smape: 0.3710

Epoch 37/128

3832/3832 - 34s - 9ms/step - ia: 0.8692 - loss: 0.0674 - mae: 0.1634 - rmse: 0.2253 - smape: 0.3941 - val_ia: 0.5295 - val_loss: 0.0582 - val_mae: 0.1462 - val_rmse: 0.1853 - val_smape: 0.3721

Epoch 38/128

3832/3832 - 41s - 11ms/step - ia: 0.8687 - loss: 0.0658 - mae: 0.1630 - rmse: 0.2243 - smape: 0.3954 - val_ia: 0.5263 - val_loss: 0.0652 - val_mae: 0.1515 - val_rmse: 0.1890 - val_smape: 0.3734

Epoch 39/128

3832/3832 - 33s - 9ms/step - ia: 0.8687 - loss: 0.0660 - mae: 0.1631 - rmse: 0.2245 - smape: 0.3946 - val_ia: 0.5309 - val_loss: 0.0573 - val_mae: 0.1425 - val_rmse: 0.1828 - val_smape: 0.3721

Epoch 40/128

3832/3832 - 35s - 9ms/step - ia: 0.8686 - loss: 0.0664 - mae: 0.1634 - rmse: 0.2253 - smape: 0.3949 - val_ia: 0.5726 - val_loss: 0.0537 - val_mae: 0.1299 - val_rmse: 0.1701 - val_smape: 0.3491

Epoch 41/128

3832/3832 - 34s - 9ms/step - ia: 0.8699 - loss: 0.0651 - mae: 0.1619 - rmse: 0.2235 - smape: 0.3930 - val_ia: 0.5582 - val_loss: 0.0548 - val_mae: 0.1333 - val_rmse: 0.1735 - val_smape: 0.3577

Epoch 42/128

3832/3832 - 34s - 9ms/step - ia: 0.8688 - loss: 0.0660 - mae: 0.1622 - rmse: 0.2240 - smape: 0.3929 - val_ia: 0.5514 - val_loss: 0.0616 - val_mae: 0.1398 - val_rmse: 0.1821 - val_smape: 0.3618

Epoch 43/128

3832/3832 - 34s - 9ms/step - ia: 0.8695 - loss: 0.0645 - mae: 0.1622 - rmse: 0.2226 - smape: 0.3951 - val_ia: 0.5577 - val_loss: 0.0605 - val_mae: 0.1370 - val_rmse: 0.1790 - val_smape: 0.3573

Epoch 44/128

3832/3832 - 34s - 9ms/step - ia: 0.8721 - loss: 0.0627 - mae: 0.1605 - rmse: 0.2196 - smape: 0.3898 - val_ia: 0.5539 - val_loss: 0.0576 - val_mae: 0.1369 - val_rmse: 0.1770 - val_smape: 0.3552

Epoch 45/128

3832/3832 - 34s - 9ms/step - ia: 0.8710 - loss: 0.0639 - mae: 0.1604 - rmse: 0.2213 - smape: 0.3917 - val_ia: 0.5487 - val_loss: 0.0556 - val_mae: 0.1364 - val_rmse: 0.1761 - val_smape: 0.3578

Epoch 45: early stopping

Restoring model weights from the end of the best epoch: 30.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:19 1s/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 67%|██████▋   | 8/12 [3:16:40<1:16:54, 1153.72s/trial, best loss: 0.03682275219635514]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 6s - 23ms/step - ia: 0.6646 - loss: 0.3954 - mae: 0.4231 - rmse: 0.6063 - smape: 0.8800 - val_ia: 0.7135 - val_loss: 0.1392 - val_mae: 0.2691 - val_rmse: 0.3508 - val_smape: 0.6307

Epoch 2/128

240/240 - 1s - 4ms/step - ia: 0.7677 - loss: 0.2181 - mae: 0.3142 - rmse: 0.4611 - smape: 0.6761 - val_ia: 0.7724 - val_loss: 0.1074 - val_mae: 0.2214 - val_rmse: 0.3044 - val_smape: 0.5289

Epoch 3/128

240/240 - 1s - 5ms/step - ia: 0.7955 - loss: 0.1790 - mae: 0.2818 - rmse: 0.4168 - smape: 0.6085 - val_ia: 0.7986 - val_loss: 0.0898 - val_mae: 0.1967 - val_rmse: 0.2784 - val_smape: 0.4831

Epoch 4/128

240/240 - 1s - 6ms/step - ia: 0.8111 - loss: 0.1600 - mae: 0.2632 - rmse: 0.3936 - smape: 0.5689 - val_ia: 0.8098 - val_loss: 0.0806 - val_mae: 0.1843 - val_rmse: 0.2633 - val_smape: 0.4556

Epoch 5/128

240/240 - 1s - 5ms/step - ia: 0.8220 - loss: 0.1448 - mae: 0.2494 - rmse: 0.3750 - smape: 0.5408 - val_ia: 0.8165 - val_loss: 0.0753 - val_mae: 0.1785 - val_rmse: 0.2539 - val_smape: 0.4382

Epoch 6/128

240/240 - 1s - 5ms/step - ia: 0.8304 - loss: 0.1357 - mae: 0.2392 - rmse: 0.3617 - smape: 0.5198 - val_ia: 0.8248 - val_loss: 0.0728 - val_mae: 0.1717 - val_rmse: 0.2489 - val_smape: 0.4259

Epoch 7/128

240/240 - 1s - 5ms/step - ia: 0.8336 - loss: 0.1310 - mae: 0.2347 - rmse: 0.3569 - smape: 0.5064 - val_ia: 0.8290 - val_loss: 0.0705 - val_mae: 0.1685 - val_rmse: 0.2437 - val_smape: 0.4131

Epoch 8/128

240/240 - 1s - 5ms/step - ia: 0.8371 - loss: 0.1310 - mae: 0.2305 - rmse: 0.3560 - smape: 0.4953 - val_ia: 0.8431 - val_loss: 0.0649 - val_mae: 0.1566 - val_rmse: 0.2340 - val_smape: 0.3973

Epoch 9/128

240/240 - 1s - 5ms/step - ia: 0.8398 - loss: 0.1250 - mae: 0.2267 - rmse: 0.3483 - smape: 0.4861 - val_ia: 0.8450 - val_loss: 0.0611 - val_mae: 0.1511 - val_rmse: 0.2285 - val_smape: 0.3900

Epoch 10/128

240/240 - 1s - 4ms/step - ia: 0.8431 - loss: 0.1201 - mae: 0.2228 - rmse: 0.3403 - smape: 0.4836 - val_ia: 0.8400 - val_loss: 0.0655 - val_mae: 0.1592 - val_rmse: 0.2336 - val_smape: 0.3936

Epoch 11/128

240/240 - 1s - 5ms/step - ia: 0.8433 - loss: 0.1234 - mae: 0.2229 - rmse: 0.3455 - smape: 0.4775 - val_ia: 0.8460 - val_loss: 0.0617 - val_mae: 0.1525 - val_rmse: 0.2279 - val_smape: 0.3853

Epoch 12/128

240/240 - 1s - 6ms/step - ia: 0.8444 - loss: 0.1206 - mae: 0.2211 - rmse: 0.3417 - smape: 0.4742 - val_ia: 0.8470 - val_loss: 0.0616 - val_mae: 0.1512 - val_rmse: 0.2277 - val_smape: 0.3827

Epoch 13/128

240/240 - 1s - 4ms/step - ia: 0.8449 - loss: 0.1214 - mae: 0.2207 - rmse: 0.3431 - smape: 0.4699 - val_ia: 0.8506 - val_loss: 0.0615 - val_mae: 0.1498 - val_rmse: 0.2262 - val_smape: 0.3785

Epoch 14/128

240/240 - 1s - 5ms/step - ia: 0.8449 - loss: 0.1209 - mae: 0.2207 - rmse: 0.3425 - smape: 0.4695 - val_ia: 0.8487 - val_loss: 0.0614 - val_mae: 0.1507 - val_rmse: 0.2262 - val_smape: 0.3795

Epoch 15/128

240/240 - 1s - 5ms/step - ia: 0.8455 - loss: 0.1224 - mae: 0.2196 - rmse: 0.3435 - smape: 0.4667 - val_ia: 0.8525 - val_loss: 0.0607 - val_mae: 0.1480 - val_rmse: 0.2247 - val_smape: 0.3748

Epoch 16/128

240/240 - 1s - 6ms/step - ia: 0.8464 - loss: 0.1208 - mae: 0.2191 - rmse: 0.3416 - smape: 0.4660 - val_ia: 0.8548 - val_loss: 0.0593 - val_mae: 0.1454 - val_rmse: 0.2223 - val_smape: 0.3732

Epoch 17/128

240/240 - 1s - 5ms/step - ia: 0.8480 - loss: 0.1142 - mae: 0.2172 - rmse: 0.3327 - smape: 0.4659 - val_ia: 0.8434 - val_loss: 0.0647 - val_mae: 0.1565 - val_rmse: 0.2310 - val_smape: 0.3840

Epoch 18/128

240/240 - 1s - 5ms/step - ia: 0.8493 - loss: 0.1151 - mae: 0.2154 - rmse: 0.3335 - smape: 0.4624 - val_ia: 0.8529 - val_loss: 0.0603 - val_mae: 0.1478 - val_rmse: 0.2236 - val_smape: 0.3757

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.8495 - loss: 0.1153 - mae: 0.2144 - rmse: 0.3336 - smape: 0.4610 - val_ia: 0.8602 - val_loss: 0.0581 - val_mae: 0.1410 - val_rmse: 0.2194 - val_smape: 0.3666

Epoch 20/128

240/240 - 1s - 6ms/step - ia: 0.8513 - loss: 0.1107 - mae: 0.2122 - rmse: 0.3282 - smape: 0.4568 - val_ia: 0.8552 - val_loss: 0.0584 - val_mae: 0.1445 - val_rmse: 0.2208 - val_smape: 0.3705

Epoch 21/128

240/240 - 1s - 4ms/step - ia: 0.8512 - loss: 0.1125 - mae: 0.2125 - rmse: 0.3300 - smape: 0.4554 - val_ia: 0.8558 - val_loss: 0.0588 - val_mae: 0.1445 - val_rmse: 0.2209 - val_smape: 0.3718

Epoch 22/128

240/240 - 1s - 5ms/step - ia: 0.8520 - loss: 0.1149 - mae: 0.2113 - rmse: 0.3332 - smape: 0.4526 - val_ia: 0.8574 - val_loss: 0.0588 - val_mae: 0.1434 - val_rmse: 0.2206 - val_smape: 0.3686

Epoch 23/128

240/240 - 1s - 6ms/step - ia: 0.8517 - loss: 0.1129 - mae: 0.2118 - rmse: 0.3300 - smape: 0.4536 - val_ia: 0.8612 - val_loss: 0.0572 - val_mae: 0.1394 - val_rmse: 0.2182 - val_smape: 0.3635

Epoch 24/128

240/240 - 2s - 9ms/step - ia: 0.8517 - loss: 0.1151 - mae: 0.2121 - rmse: 0.3329 - smape: 0.4521 - val_ia: 0.8589 - val_loss: 0.0588 - val_mae: 0.1425 - val_rmse: 0.2210 - val_smape: 0.3669

Epoch 25/128

240/240 - 1s - 4ms/step - ia: 0.8526 - loss: 0.1132 - mae: 0.2109 - rmse: 0.3302 - smape: 0.4495 - val_ia: 0.8508 - val_loss: 0.0600 - val_mae: 0.1491 - val_rmse: 0.2238 - val_smape: 0.3756

Epoch 26/128

240/240 - 1s - 4ms/step - ia: 0.8528 - loss: 0.1100 - mae: 0.2102 - rmse: 0.3264 - smape: 0.4534 - val_ia: 0.8612 - val_loss: 0.0575 - val_mae: 0.1408 - val_rmse: 0.2186 - val_smape: 0.3653

Epoch 27/128

240/240 - 2s - 6ms/step - ia: 0.8513 - loss: 0.1138 - mae: 0.2124 - rmse: 0.3316 - smape: 0.4521 - val_ia: 0.8647 - val_loss: 0.0562 - val_mae: 0.1376 - val_rmse: 0.2160 - val_smape: 0.3616

Epoch 28/128

240/240 - 1s - 5ms/step - ia: 0.8532 - loss: 0.1110 - mae: 0.2100 - rmse: 0.3272 - smape: 0.4484 - val_ia: 0.8533 - val_loss: 0.0593 - val_mae: 0.1471 - val_rmse: 0.2219 - val_smape: 0.3713

Epoch 29/128

240/240 - 1s - 5ms/step - ia: 0.8527 - loss: 0.1112 - mae: 0.2106 - rmse: 0.3278 - smape: 0.4530 - val_ia: 0.8530 - val_loss: 0.0578 - val_mae: 0.1461 - val_rmse: 0.2203 - val_smape: 0.3715

Epoch 30/128

240/240 - 1s - 5ms/step - ia: 0.8525 - loss: 0.1140 - mae: 0.2108 - rmse: 0.3312 - smape: 0.4478 - val_ia: 0.8556 - val_loss: 0.0580 - val_mae: 0.1442 - val_rmse: 0.2203 - val_smape: 0.3674

Epoch 31/128

240/240 - 1s - 6ms/step - ia: 0.8521 - loss: 0.1127 - mae: 0.2117 - rmse: 0.3298 - smape: 0.4528 - val_ia: 0.8451 - val_loss: 0.0647 - val_mae: 0.1562 - val_rmse: 0.2302 - val_smape: 0.3800

Epoch 32/128

240/240 - 2s - 10ms/step - ia: 0.8522 - loss: 0.1109 - mae: 0.2111 - rmse: 0.3275 - smape: 0.4505 - val_ia: 0.8562 - val_loss: 0.0586 - val_mae: 0.1449 - val_rmse: 0.2206 - val_smape: 0.3680

Epoch 33/128

240/240 - 1s - 6ms/step - ia: 0.8533 - loss: 0.1087 - mae: 0.2099 - rmse: 0.3243 - smape: 0.4490 - val_ia: 0.8618 - val_loss: 0.0575 - val_mae: 0.1402 - val_rmse: 0.2183 - val_smape: 0.3631

Epoch 34/128

240/240 - 1s - 5ms/step - ia: 0.8541 - loss: 0.1079 - mae: 0.2088 - rmse: 0.3224 - smape: 0.4492 - val_ia: 0.8577 - val_loss: 0.0581 - val_mae: 0.1431 - val_rmse: 0.2200 - val_smape: 0.3660

Epoch 35/128

240/240 - 1s - 5ms/step - ia: 0.8543 - loss: 0.1073 - mae: 0.2085 - rmse: 0.3227 - smape: 0.4471 - val_ia: 0.8566 - val_loss: 0.0577 - val_mae: 0.1438 - val_rmse: 0.2190 - val_smape: 0.3672

Epoch 36/128

240/240 - 1s - 5ms/step - ia: 0.8532 - loss: 0.1118 - mae: 0.2097 - rmse: 0.3281 - smape: 0.4465 - val_ia: 0.8672 - val_loss: 0.0551 - val_mae: 0.1348 - val_rmse: 0.2142 - val_smape: 0.3563

Epoch 37/128

240/240 - 1s - 5ms/step - ia: 0.8535 - loss: 0.1112 - mae: 0.2100 - rmse: 0.3277 - smape: 0.4488 - val_ia: 0.8568 - val_loss: 0.0582 - val_mae: 0.1441 - val_rmse: 0.2197 - val_smape: 0.3673

Epoch 38/128

240/240 - 1s - 5ms/step - ia: 0.8540 - loss: 0.1080 - mae: 0.2084 - rmse: 0.3234 - smape: 0.4478 - val_ia: 0.8589 - val_loss: 0.0583 - val_mae: 0.1433 - val_rmse: 0.2195 - val_smape: 0.3650

Epoch 39/128

240/240 - 1s - 5ms/step - ia: 0.8524 - loss: 0.1114 - mae: 0.2110 - rmse: 0.3284 - smape: 0.4497 - val_ia: 0.8604 - val_loss: 0.0578 - val_mae: 0.1412 - val_rmse: 0.2187 - val_smape: 0.3626

Epoch 40/128

240/240 - 1s - 4ms/step - ia: 0.8534 - loss: 0.1102 - mae: 0.2098 - rmse: 0.3263 - smape: 0.4478 - val_ia: 0.8657 - val_loss: 0.0566 - val_mae: 0.1376 - val_rmse: 0.2161 - val_smape: 0.3583

Epoch 41/128

240/240 - 1s - 6ms/step - ia: 0.8536 - loss: 0.1114 - mae: 0.2094 - rmse: 0.3275 - smape: 0.4477 - val_ia: 0.8590 - val_loss: 0.0585 - val_mae: 0.1431 - val_rmse: 0.2200 - val_smape: 0.3651

Epoch 42/128

240/240 - 1s - 4ms/step - ia: 0.8531 - loss: 0.1101 - mae: 0.2098 - rmse: 0.3267 - smape: 0.4486 - val_ia: 0.8540 - val_loss: 0.0599 - val_mae: 0.1469 - val_rmse: 0.2231 - val_smape: 0.3704

Epoch 43/128

240/240 - 1s - 6ms/step - ia: 0.8537 - loss: 0.1091 - mae: 0.2089 - rmse: 0.3239 - smape: 0.4463 - val_ia: 0.8600 - val_loss: 0.0574 - val_mae: 0.1409 - val_rmse: 0.2185 - val_smape: 0.3636

Epoch 44/128

240/240 - 1s - 5ms/step - ia: 0.8543 - loss: 0.1080 - mae: 0.2080 - rmse: 0.3227 - smape: 0.4453 - val_ia: 0.8587 - val_loss: 0.0575 - val_mae: 0.1412 - val_rmse: 0.2187 - val_smape: 0.3645

Epoch 45/128

240/240 - 1s - 5ms/step - ia: 0.8532 - loss: 0.1098 - mae: 0.2095 - rmse: 0.3256 - smape: 0.4462 - val_ia: 0.8613 - val_loss: 0.0577 - val_mae: 0.1410 - val_rmse: 0.2184 - val_smape: 0.3633

Epoch 46/128

240/240 - 1s - 6ms/step - ia: 0.8540 - loss: 0.1093 - mae: 0.2091 - rmse: 0.3257 - smape: 0.4460 - val_ia: 0.8642 - val_loss: 0.0555 - val_mae: 0.1366 - val_rmse: 0.2148 - val_smape: 0.3591

Epoch 47/128

240/240 - 1s - 5ms/step - ia: 0.8520 - loss: 0.1129 - mae: 0.2113 - rmse: 0.3308 - smape: 0.4496 - val_ia: 0.8566 - val_loss: 0.0582 - val_mae: 0.1440 - val_rmse: 0.2200 - val_smape: 0.3664

Epoch 48/128

240/240 - 1s - 5ms/step - ia: 0.8538 - loss: 0.1076 - mae: 0.2090 - rmse: 0.3230 - smape: 0.4461 - val_ia: 0.8627 - val_loss: 0.0566 - val_mae: 0.1391 - val_rmse: 0.2167 - val_smape: 0.3607

Epoch 49/128

240/240 - 1s - 5ms/step - ia: 0.8536 - loss: 0.1085 - mae: 0.2094 - rmse: 0.3239 - smape: 0.4478 - val_ia: 0.8563 - val_loss: 0.0587 - val_mae: 0.1448 - val_rmse: 0.2207 - val_smape: 0.3668

Epoch 50/128

240/240 - 1s - 6ms/step - ia: 0.8539 - loss: 0.1106 - mae: 0.2093 - rmse: 0.3261 - smape: 0.4459 - val_ia: 0.8575 - val_loss: 0.0581 - val_mae: 0.1432 - val_rmse: 0.2193 - val_smape: 0.3658

Epoch 51/128

240/240 - 1s - 6ms/step - ia: 0.8544 - loss: 0.1078 - mae: 0.2081 - rmse: 0.3227 - smape: 0.4469 - val_ia: 0.8558 - val_loss: 0.0597 - val_mae: 0.1461 - val_rmse: 0.2218 - val_smape: 0.3689

Epoch 51: early stopping

Restoring model weights from the end of the best epoch: 36.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 34s 254ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 75%|███████▌  | 9/12 [3:17:49<40:44, 814.85s/trial, best loss: 0.03682275219635514]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 29s - 15ms/step - ia: 0.5040 - loss: 0.6468 - mae: 0.5754 - rmse: 0.7501 - smape: 1.1181 - val_ia: 0.3989 - val_loss: 0.2008 - val_mae: 0.2964 - val_rmse: 0.3607 - val_smape: 0.6611

Epoch 2/128

1916/1916 - 23s - 12ms/step - ia: 0.7215 - loss: 0.2631 - mae: 0.3625 - rmse: 0.4875 - smape: 0.7569 - val_ia: 0.4260 - val_loss: 0.1583 - val_mae: 0.2813 - val_rmse: 0.3408 - val_smape: 0.6595

Epoch 3/128

1916/1916 - 23s - 12ms/step - ia: 0.7582 - loss: 0.2074 - mae: 0.3162 - rmse: 0.4304 - smape: 0.6826 - val_ia: 0.4931 - val_loss: 0.1190 - val_mae: 0.2264 - val_rmse: 0.2856 - val_smape: 0.5423

Epoch 4/128

1916/1916 - 22s - 11ms/step - ia: 0.7828 - loss: 0.1744 - mae: 0.2882 - rmse: 0.3934 - smape: 0.6382 - val_ia: 0.5342 - val_loss: 0.1032 - val_mae: 0.2039 - val_rmse: 0.2630 - val_smape: 0.4996

Epoch 5/128

1916/1916 - 22s - 12ms/step - ia: 0.7946 - loss: 0.1542 - mae: 0.2705 - rmse: 0.3695 - smape: 0.6072 - val_ia: 0.5360 - val_loss: 0.0953 - val_mae: 0.2014 - val_rmse: 0.2576 - val_smape: 0.4979

Epoch 6/128

1916/1916 - 41s - 21ms/step - ia: 0.8067 - loss: 0.1430 - mae: 0.2561 - rmse: 0.3537 - smape: 0.5794 - val_ia: 0.5710 - val_loss: 0.0865 - val_mae: 0.1838 - val_rmse: 0.2415 - val_smape: 0.4656

Epoch 7/128

1916/1916 - 22s - 11ms/step - ia: 0.8151 - loss: 0.1340 - mae: 0.2453 - rmse: 0.3404 - smape: 0.5620 - val_ia: 0.5825 - val_loss: 0.0820 - val_mae: 0.1776 - val_rmse: 0.2340 - val_smape: 0.4530

Epoch 8/128

1916/1916 - 25s - 13ms/step - ia: 0.8206 - loss: 0.1266 - mae: 0.2383 - rmse: 0.3310 - smape: 0.5472 - val_ia: 0.5937 - val_loss: 0.0783 - val_mae: 0.1728 - val_rmse: 0.2289 - val_smape: 0.4412

Epoch 9/128

1916/1916 - 21s - 11ms/step - ia: 0.8266 - loss: 0.1204 - mae: 0.2316 - rmse: 0.3225 - smape: 0.5319 - val_ia: 0.5900 - val_loss: 0.0754 - val_mae: 0.1718 - val_rmse: 0.2259 - val_smape: 0.4391

Epoch 10/128

1916/1916 - 17s - 9ms/step - ia: 0.8296 - loss: 0.1170 - mae: 0.2268 - rmse: 0.3172 - smape: 0.5248 - val_ia: 0.5848 - val_loss: 0.0732 - val_mae: 0.1727 - val_rmse: 0.2259 - val_smape: 0.4409

Epoch 11/128

1916/1916 - 19s - 10ms/step - ia: 0.8342 - loss: 0.1121 - mae: 0.2225 - rmse: 0.3109 - smape: 0.5140 - val_ia: 0.6077 - val_loss: 0.0717 - val_mae: 0.1650 - val_rmse: 0.2187 - val_smape: 0.4231

Epoch 12/128

1916/1916 - 22s - 12ms/step - ia: 0.8367 - loss: 0.1095 - mae: 0.2178 - rmse: 0.3053 - smape: 0.5030 - val_ia: 0.5830 - val_loss: 0.0718 - val_mae: 0.1735 - val_rmse: 0.2267 - val_smape: 0.4481

Epoch 13/128

1916/1916 - 20s - 11ms/step - ia: 0.8383 - loss: 0.1074 - mae: 0.2167 - rmse: 0.3036 - smape: 0.5043 - val_ia: 0.6110 - val_loss: 0.0688 - val_mae: 0.1619 - val_rmse: 0.2153 - val_smape: 0.4164

Epoch 14/128

1916/1916 - 18s - 9ms/step - ia: 0.8402 - loss: 0.1064 - mae: 0.2147 - rmse: 0.3019 - smape: 0.4980 - val_ia: 0.6348 - val_loss: 0.0657 - val_mae: 0.1529 - val_rmse: 0.2081 - val_smape: 0.4052

Epoch 15/128

1916/1916 - 18s - 10ms/step - ia: 0.8437 - loss: 0.1019 - mae: 0.2101 - rmse: 0.2951 - smape: 0.4911 - val_ia: 0.6209 - val_loss: 0.0681 - val_mae: 0.1596 - val_rmse: 0.2125 - val_smape: 0.4153

Epoch 16/128

1916/1916 - 23s - 12ms/step - ia: 0.8437 - loss: 0.1024 - mae: 0.2097 - rmse: 0.2953 - smape: 0.4904 - val_ia: 0.6227 - val_loss: 0.0654 - val_mae: 0.1566 - val_rmse: 0.2089 - val_smape: 0.4082

Epoch 17/128

1916/1916 - 22s - 11ms/step - ia: 0.8470 - loss: 0.1000 - mae: 0.2059 - rmse: 0.2909 - smape: 0.4800 - val_ia: 0.6337 - val_loss: 0.0649 - val_mae: 0.1537 - val_rmse: 0.2065 - val_smape: 0.4010

Epoch 18/128

1916/1916 - 39s - 20ms/step - ia: 0.8472 - loss: 0.0997 - mae: 0.2056 - rmse: 0.2898 - smape: 0.4808 - val_ia: 0.6292 - val_loss: 0.0665 - val_mae: 0.1564 - val_rmse: 0.2084 - val_smape: 0.4032

Epoch 19/128

1916/1916 - 22s - 11ms/step - ia: 0.8488 - loss: 0.0981 - mae: 0.2037 - rmse: 0.2876 - smape: 0.4790 - val_ia: 0.6515 - val_loss: 0.0619 - val_mae: 0.1458 - val_rmse: 0.2007 - val_smape: 0.3875

Epoch 20/128

1916/1916 - 22s - 12ms/step - ia: 0.8507 - loss: 0.0955 - mae: 0.2007 - rmse: 0.2838 - smape: 0.4731 - val_ia: 0.6481 - val_loss: 0.0608 - val_mae: 0.1452 - val_rmse: 0.1996 - val_smape: 0.3873

Epoch 21/128

1916/1916 - 22s - 11ms/step - ia: 0.8520 - loss: 0.0953 - mae: 0.2000 - rmse: 0.2827 - smape: 0.4713 - val_ia: 0.6281 - val_loss: 0.0634 - val_mae: 0.1539 - val_rmse: 0.2051 - val_smape: 0.3954

Epoch 22/128

1916/1916 - 18s - 10ms/step - ia: 0.8523 - loss: 0.0935 - mae: 0.1992 - rmse: 0.2814 - smape: 0.4686 - val_ia: 0.6384 - val_loss: 0.0602 - val_mae: 0.1475 - val_rmse: 0.2002 - val_smape: 0.3879

Epoch 23/128

1916/1916 - 24s - 13ms/step - ia: 0.8539 - loss: 0.0925 - mae: 0.1970 - rmse: 0.2786 - smape: 0.4634 - val_ia: 0.6388 - val_loss: 0.0605 - val_mae: 0.1480 - val_rmse: 0.2002 - val_smape: 0.3877

Epoch 24/128

1916/1916 - 23s - 12ms/step - ia: 0.8536 - loss: 0.0926 - mae: 0.1971 - rmse: 0.2788 - smape: 0.4670 - val_ia: 0.6473 - val_loss: 0.0592 - val_mae: 0.1446 - val_rmse: 0.1974 - val_smape: 0.3835

Epoch 25/128

1916/1916 - 22s - 12ms/step - ia: 0.8557 - loss: 0.0913 - mae: 0.1948 - rmse: 0.2773 - smape: 0.4610 - val_ia: 0.6527 - val_loss: 0.0588 - val_mae: 0.1425 - val_rmse: 0.1965 - val_smape: 0.3804

Epoch 26/128

1916/1916 - 22s - 12ms/step - ia: 0.8550 - loss: 0.0921 - mae: 0.1957 - rmse: 0.2775 - smape: 0.4650 - val_ia: 0.6432 - val_loss: 0.0612 - val_mae: 0.1479 - val_rmse: 0.2001 - val_smape: 0.3837

Epoch 27/128

1916/1916 - 41s - 21ms/step - ia: 0.8567 - loss: 0.0901 - mae: 0.1936 - rmse: 0.2745 - smape: 0.4595 - val_ia: 0.6527 - val_loss: 0.0585 - val_mae: 0.1425 - val_rmse: 0.1959 - val_smape: 0.3784

Epoch 28/128

1916/1916 - 22s - 12ms/step - ia: 0.8570 - loss: 0.0903 - mae: 0.1932 - rmse: 0.2742 - smape: 0.4592 - val_ia: 0.6641 - val_loss: 0.0575 - val_mae: 0.1390 - val_rmse: 0.1929 - val_smape: 0.3722

Epoch 29/128

1916/1916 - 22s - 11ms/step - ia: 0.8581 - loss: 0.0890 - mae: 0.1917 - rmse: 0.2721 - smape: 0.4549 - val_ia: 0.6544 - val_loss: 0.0574 - val_mae: 0.1411 - val_rmse: 0.1945 - val_smape: 0.3762

Epoch 30/128

1916/1916 - 22s - 11ms/step - ia: 0.8577 - loss: 0.0894 - mae: 0.1916 - rmse: 0.2733 - smape: 0.4540 - val_ia: 0.6522 - val_loss: 0.0577 - val_mae: 0.1417 - val_rmse: 0.1950 - val_smape: 0.3779

Epoch 31/128

1916/1916 - 43s - 22ms/step - ia: 0.8587 - loss: 0.0892 - mae: 0.1908 - rmse: 0.2727 - smape: 0.4505 - val_ia: 0.6608 - val_loss: 0.0585 - val_mae: 0.1416 - val_rmse: 0.1943 - val_smape: 0.3739

Epoch 32/128

1916/1916 - 21s - 11ms/step - ia: 0.8603 - loss: 0.0872 - mae: 0.1891 - rmse: 0.2687 - smape: 0.4500 - val_ia: 0.6698 - val_loss: 0.0567 - val_mae: 0.1365 - val_rmse: 0.1912 - val_smape: 0.3681

Epoch 33/128

1916/1916 - 22s - 11ms/step - ia: 0.8608 - loss: 0.0875 - mae: 0.1886 - rmse: 0.2691 - smape: 0.4494 - val_ia: 0.6465 - val_loss: 0.0576 - val_mae: 0.1432 - val_rmse: 0.1964 - val_smape: 0.3810

Epoch 34/128

1916/1916 - 22s - 11ms/step - ia: 0.8607 - loss: 0.0866 - mae: 0.1879 - rmse: 0.2685 - smape: 0.4469 - val_ia: 0.6596 - val_loss: 0.0566 - val_mae: 0.1391 - val_rmse: 0.1923 - val_smape: 0.3709

Epoch 35/128

1916/1916 - 41s - 21ms/step - ia: 0.8619 - loss: 0.0866 - mae: 0.1876 - rmse: 0.2682 - smape: 0.4454 - val_ia: 0.6663 - val_loss: 0.0567 - val_mae: 0.1380 - val_rmse: 0.1913 - val_smape: 0.3693

Epoch 36/128

1916/1916 - 22s - 11ms/step - ia: 0.8613 - loss: 0.0872 - mae: 0.1878 - rmse: 0.2688 - smape: 0.4465 - val_ia: 0.6634 - val_loss: 0.0568 - val_mae: 0.1388 - val_rmse: 0.1916 - val_smape: 0.3714

Epoch 37/128

1916/1916 - 22s - 12ms/step - ia: 0.8622 - loss: 0.0855 - mae: 0.1862 - rmse: 0.2660 - smape: 0.4420 - val_ia: 0.6563 - val_loss: 0.0566 - val_mae: 0.1402 - val_rmse: 0.1924 - val_smape: 0.3728

Epoch 38/128

1916/1916 - 22s - 12ms/step - ia: 0.8612 - loss: 0.0875 - mae: 0.1872 - rmse: 0.2687 - smape: 0.4448 - val_ia: 0.6571 - val_loss: 0.0569 - val_mae: 0.1397 - val_rmse: 0.1936 - val_smape: 0.3731

Epoch 39/128

1916/1916 - 22s - 11ms/step - ia: 0.8623 - loss: 0.0858 - mae: 0.1864 - rmse: 0.2661 - smape: 0.4424 - val_ia: 0.6560 - val_loss: 0.0569 - val_mae: 0.1407 - val_rmse: 0.1933 - val_smape: 0.3717

Epoch 40/128

1916/1916 - 24s - 12ms/step - ia: 0.8624 - loss: 0.0873 - mae: 0.1868 - rmse: 0.2679 - smape: 0.4425 - val_ia: 0.6471 - val_loss: 0.0572 - val_mae: 0.1435 - val_rmse: 0.1948 - val_smape: 0.3765

Epoch 41/128

1916/1916 - 22s - 12ms/step - ia: 0.8633 - loss: 0.0851 - mae: 0.1843 - rmse: 0.2648 - smape: 0.4383 - val_ia: 0.6618 - val_loss: 0.0556 - val_mae: 0.1378 - val_rmse: 0.1904 - val_smape: 0.3687

Epoch 42/128

1916/1916 - 22s - 11ms/step - ia: 0.8629 - loss: 0.0845 - mae: 0.1849 - rmse: 0.2642 - smape: 0.4417 - val_ia: 0.6705 - val_loss: 0.0555 - val_mae: 0.1358 - val_rmse: 0.1892 - val_smape: 0.3654

Epoch 43/128

1916/1916 - 22s - 12ms/step - ia: 0.8637 - loss: 0.0843 - mae: 0.1843 - rmse: 0.2642 - smape: 0.4363 - val_ia: 0.6778 - val_loss: 0.0555 - val_mae: 0.1346 - val_rmse: 0.1883 - val_smape: 0.3640

Epoch 44/128

1916/1916 - 40s - 21ms/step - ia: 0.8637 - loss: 0.0848 - mae: 0.1845 - rmse: 0.2653 - smape: 0.4388 - val_ia: 0.6539 - val_loss: 0.0559 - val_mae: 0.1403 - val_rmse: 0.1922 - val_smape: 0.3719

Epoch 45/128

1916/1916 - 41s - 21ms/step - ia: 0.8642 - loss: 0.0844 - mae: 0.1833 - rmse: 0.2635 - smape: 0.4358 - val_ia: 0.6541 - val_loss: 0.0566 - val_mae: 0.1411 - val_rmse: 0.1933 - val_smape: 0.3727

Epoch 46/128

1916/1916 - 21s - 11ms/step - ia: 0.8651 - loss: 0.0830 - mae: 0.1827 - rmse: 0.2623 - smape: 0.4354 - val_ia: 0.6618 - val_loss: 0.0561 - val_mae: 0.1385 - val_rmse: 0.1911 - val_smape: 0.3673

Epoch 47/128

1916/1916 - 22s - 12ms/step - ia: 0.8650 - loss: 0.0838 - mae: 0.1829 - rmse: 0.2622 - smape: 0.4361 - val_ia: 0.6733 - val_loss: 0.0557 - val_mae: 0.1355 - val_rmse: 0.1894 - val_smape: 0.3634

Epoch 48/128

1916/1916 - 21s - 11ms/step - ia: 0.8650 - loss: 0.0824 - mae: 0.1818 - rmse: 0.2612 - smape: 0.4348 - val_ia: 0.6414 - val_loss: 0.0576 - val_mae: 0.1455 - val_rmse: 0.1966 - val_smape: 0.3777

Epoch 49/128

1916/1916 - 25s - 13ms/step - ia: 0.8664 - loss: 0.0817 - mae: 0.1813 - rmse: 0.2601 - smape: 0.4354 - val_ia: 0.6624 - val_loss: 0.0563 - val_mae: 0.1393 - val_rmse: 0.1906 - val_smape: 0.3684

Epoch 50/128

1916/1916 - 41s - 21ms/step - ia: 0.8650 - loss: 0.0837 - mae: 0.1822 - rmse: 0.2616 - smape: 0.4339 - val_ia: 0.6699 - val_loss: 0.0549 - val_mae: 0.1355 - val_rmse: 0.1882 - val_smape: 0.3643

Epoch 51/128

1916/1916 - 39s - 20ms/step - ia: 0.8662 - loss: 0.0827 - mae: 0.1816 - rmse: 0.2608 - smape: 0.4315 - val_ia: 0.6755 - val_loss: 0.0568 - val_mae: 0.1373 - val_rmse: 0.1899 - val_smape: 0.3644

Epoch 52/128

1916/1916 - 24s - 13ms/step - ia: 0.8663 - loss: 0.0824 - mae: 0.1815 - rmse: 0.2610 - smape: 0.4338 - val_ia: 0.6629 - val_loss: 0.0551 - val_mae: 0.1370 - val_rmse: 0.1896 - val_smape: 0.3662

Epoch 53/128

1916/1916 - 28s - 15ms/step - ia: 0.8662 - loss: 0.0821 - mae: 0.1812 - rmse: 0.2596 - smape: 0.4346 - val_ia: 0.6650 - val_loss: 0.0558 - val_mae: 0.1380 - val_rmse: 0.1899 - val_smape: 0.3654

Epoch 54/128

1916/1916 - 25s - 13ms/step - ia: 0.8666 - loss: 0.0825 - mae: 0.1808 - rmse: 0.2607 - smape: 0.4298 - val_ia: 0.6691 - val_loss: 0.0549 - val_mae: 0.1354 - val_rmse: 0.1887 - val_smape: 0.3630

Epoch 55/128

1916/1916 - 41s - 22ms/step - ia: 0.8671 - loss: 0.0808 - mae: 0.1803 - rmse: 0.2586 - smape: 0.4293 - val_ia: 0.6769 - val_loss: 0.0544 - val_mae: 0.1333 - val_rmse: 0.1867 - val_smape: 0.3603

Epoch 56/128

1916/1916 - 25s - 13ms/step - ia: 0.8672 - loss: 0.0823 - mae: 0.1807 - rmse: 0.2602 - smape: 0.4305 - val_ia: 0.6827 - val_loss: 0.0545 - val_mae: 0.1321 - val_rmse: 0.1862 - val_smape: 0.3580

Epoch 57/128

1916/1916 - 23s - 12ms/step - ia: 0.8668 - loss: 0.0835 - mae: 0.1808 - rmse: 0.2610 - smape: 0.4299 - val_ia: 0.6836 - val_loss: 0.0552 - val_mae: 0.1340 - val_rmse: 0.1872 - val_smape: 0.3599

Epoch 58/128

1916/1916 - 40s - 21ms/step - ia: 0.8669 - loss: 0.0820 - mae: 0.1809 - rmse: 0.2605 - smape: 0.4292 - val_ia: 0.6827 - val_loss: 0.0542 - val_mae: 0.1323 - val_rmse: 0.1860 - val_smape: 0.3583

Epoch 59/128

1916/1916 - 25s - 13ms/step - ia: 0.8670 - loss: 0.0812 - mae: 0.1801 - rmse: 0.2589 - smape: 0.4297 - val_ia: 0.6843 - val_loss: 0.0545 - val_mae: 0.1316 - val_rmse: 0.1860 - val_smape: 0.3571

Epoch 60/128

1916/1916 - 26s - 13ms/step - ia: 0.8672 - loss: 0.0814 - mae: 0.1799 - rmse: 0.2595 - smape: 0.4276 - val_ia: 0.6778 - val_loss: 0.0543 - val_mae: 0.1332 - val_rmse: 0.1864 - val_smape: 0.3593

Epoch 61/128

1916/1916 - 25s - 13ms/step - ia: 0.8681 - loss: 0.0796 - mae: 0.1788 - rmse: 0.2567 - smape: 0.4289 - val_ia: 0.6831 - val_loss: 0.0545 - val_mae: 0.1324 - val_rmse: 0.1860 - val_smape: 0.3586

Epoch 62/128

1916/1916 - 26s - 14ms/step - ia: 0.8681 - loss: 0.0811 - mae: 0.1786 - rmse: 0.2580 - smape: 0.4258 - val_ia: 0.6868 - val_loss: 0.0541 - val_mae: 0.1312 - val_rmse: 0.1853 - val_smape: 0.3559

Epoch 63/128

1916/1916 - 25s - 13ms/step - ia: 0.8681 - loss: 0.0813 - mae: 0.1786 - rmse: 0.2584 - smape: 0.4256 - val_ia: 0.6727 - val_loss: 0.0549 - val_mae: 0.1352 - val_rmse: 0.1882 - val_smape: 0.3620

Epoch 64/128

1916/1916 - 32s - 17ms/step - ia: 0.8689 - loss: 0.0792 - mae: 0.1784 - rmse: 0.2560 - smape: 0.4279 - val_ia: 0.6712 - val_loss: 0.0549 - val_mae: 0.1346 - val_rmse: 0.1884 - val_smape: 0.3625

Epoch 65/128

1916/1916 - 26s - 13ms/step - ia: 0.8693 - loss: 0.0804 - mae: 0.1780 - rmse: 0.2570 - smape: 0.4247 - val_ia: 0.6775 - val_loss: 0.0544 - val_mae: 0.1334 - val_rmse: 0.1864 - val_smape: 0.3582

Epoch 66/128

1916/1916 - 37s - 19ms/step - ia: 0.8687 - loss: 0.0811 - mae: 0.1783 - rmse: 0.2577 - smape: 0.4233 - val_ia: 0.6718 - val_loss: 0.0561 - val_mae: 0.1366 - val_rmse: 0.1888 - val_smape: 0.3602

Epoch 67/128

1916/1916 - 23s - 12ms/step - ia: 0.8679 - loss: 0.0807 - mae: 0.1791 - rmse: 0.2581 - smape: 0.4268 - val_ia: 0.6591 - val_loss: 0.0551 - val_mae: 0.1384 - val_rmse: 0.1903 - val_smape: 0.3667

Epoch 68/128

1916/1916 - 42s - 22ms/step - ia: 0.8695 - loss: 0.0793 - mae: 0.1768 - rmse: 0.2563 - smape: 0.4225 - val_ia: 0.6827 - val_loss: 0.0542 - val_mae: 0.1323 - val_rmse: 0.1854 - val_smape: 0.3575

Epoch 69/128

1916/1916 - 24s - 12ms/step - ia: 0.8689 - loss: 0.0817 - mae: 0.1784 - rmse: 0.2583 - smape: 0.4262 - val_ia: 0.6743 - val_loss: 0.0541 - val_mae: 0.1337 - val_rmse: 0.1862 - val_smape: 0.3602

Epoch 70/128

1916/1916 - 24s - 13ms/step - ia: 0.8693 - loss: 0.0789 - mae: 0.1773 - rmse: 0.2554 - smape: 0.4252 - val_ia: 0.6785 - val_loss: 0.0545 - val_mae: 0.1328 - val_rmse: 0.1869 - val_smape: 0.3578

Epoch 71/128

1916/1916 - 25s - 13ms/step - ia: 0.8693 - loss: 0.0802 - mae: 0.1775 - rmse: 0.2564 - smape: 0.4244 - val_ia: 0.6696 - val_loss: 0.0542 - val_mae: 0.1348 - val_rmse: 0.1877 - val_smape: 0.3624

Epoch 72/128

1916/1916 - 24s - 13ms/step - ia: 0.8690 - loss: 0.0803 - mae: 0.1774 - rmse: 0.2567 - smape: 0.4227 - val_ia: 0.6473 - val_loss: 0.0555 - val_mae: 0.1423 - val_rmse: 0.1933 - val_smape: 0.3742

Epoch 73/128

1916/1916 - 25s - 13ms/step - ia: 0.8706 - loss: 0.0797 - mae: 0.1768 - rmse: 0.2551 - smape: 0.4226 - val_ia: 0.6575 - val_loss: 0.0552 - val_mae: 0.1387 - val_rmse: 0.1918 - val_smape: 0.3708

Epoch 74/128

1916/1916 - 25s - 13ms/step - ia: 0.8696 - loss: 0.0799 - mae: 0.1773 - rmse: 0.2556 - smape: 0.4225 - val_ia: 0.6710 - val_loss: 0.0540 - val_mae: 0.1347 - val_rmse: 0.1873 - val_smape: 0.3622

Epoch 75/128

1916/1916 - 24s - 12ms/step - ia: 0.8696 - loss: 0.0802 - mae: 0.1771 - rmse: 0.2558 - smape: 0.4219 - val_ia: 0.6759 - val_loss: 0.0539 - val_mae: 0.1328 - val_rmse: 0.1862 - val_smape: 0.3587

Epoch 76/128

1916/1916 - 39s - 20ms/step - ia: 0.8711 - loss: 0.0771 - mae: 0.1747 - rmse: 0.2518 - smape: 0.4194 - val_ia: 0.6638 - val_loss: 0.0559 - val_mae: 0.1389 - val_rmse: 0.1902 - val_smape: 0.3652

Epoch 77/128

1916/1916 - 44s - 23ms/step - ia: 0.8703 - loss: 0.0783 - mae: 0.1757 - rmse: 0.2536 - smape: 0.4204 - val_ia: 0.6731 - val_loss: 0.0539 - val_mae: 0.1336 - val_rmse: 0.1865 - val_smape: 0.3591

Epoch 78/128

1916/1916 - 23s - 12ms/step - ia: 0.8704 - loss: 0.0781 - mae: 0.1761 - rmse: 0.2538 - smape: 0.4225 - val_ia: 0.6837 - val_loss: 0.0537 - val_mae: 0.1311 - val_rmse: 0.1846 - val_smape: 0.3545

Epoch 79/128

1916/1916 - 24s - 13ms/step - ia: 0.8703 - loss: 0.0779 - mae: 0.1758 - rmse: 0.2528 - smape: 0.4232 - val_ia: 0.6748 - val_loss: 0.0550 - val_mae: 0.1352 - val_rmse: 0.1874 - val_smape: 0.3595

Epoch 80/128

1916/1916 - 38s - 20ms/step - ia: 0.8705 - loss: 0.0795 - mae: 0.1757 - rmse: 0.2555 - smape: 0.4213 - val_ia: 0.6800 - val_loss: 0.0543 - val_mae: 0.1331 - val_rmse: 0.1860 - val_smape: 0.3571

Epoch 81/128

1916/1916 - 23s - 12ms/step - ia: 0.8704 - loss: 0.0784 - mae: 0.1756 - rmse: 0.2537 - smape: 0.4209 - val_ia: 0.6746 - val_loss: 0.0555 - val_mae: 0.1359 - val_rmse: 0.1876 - val_smape: 0.3588

Epoch 82/128

1916/1916 - 24s - 13ms/step - ia: 0.8709 - loss: 0.0786 - mae: 0.1752 - rmse: 0.2535 - smape: 0.4186 - val_ia: 0.6594 - val_loss: 0.0554 - val_mae: 0.1396 - val_rmse: 0.1898 - val_smape: 0.3653

Epoch 83/128

1916/1916 - 24s - 13ms/step - ia: 0.8706 - loss: 0.0785 - mae: 0.1751 - rmse: 0.2534 - smape: 0.4195 - val_ia: 0.6828 - val_loss: 0.0535 - val_mae: 0.1310 - val_rmse: 0.1849 - val_smape: 0.3570

Epoch 84/128

1916/1916 - 40s - 21ms/step - ia: 0.8710 - loss: 0.0793 - mae: 0.1760 - rmse: 0.2549 - smape: 0.4212 - val_ia: 0.6750 - val_loss: 0.0535 - val_mae: 0.1331 - val_rmse: 0.1855 - val_smape: 0.3591

Epoch 85/128

1916/1916 - 24s - 13ms/step - ia: 0.8695 - loss: 0.0791 - mae: 0.1762 - rmse: 0.2551 - smape: 0.4202 - val_ia: 0.6861 - val_loss: 0.0538 - val_mae: 0.1311 - val_rmse: 0.1850 - val_smape: 0.3556

Epoch 86/128

1916/1916 - 24s - 13ms/step - ia: 0.8719 - loss: 0.0781 - mae: 0.1744 - rmse: 0.2527 - smape: 0.4167 - val_ia: 0.6650 - val_loss: 0.0546 - val_mae: 0.1365 - val_rmse: 0.1882 - val_smape: 0.3617

Epoch 87/128

1916/1916 - 23s - 12ms/step - ia: 0.8705 - loss: 0.0799 - mae: 0.1757 - rmse: 0.2549 - smape: 0.4169 - val_ia: 0.6868 - val_loss: 0.0542 - val_mae: 0.1324 - val_rmse: 0.1847 - val_smape: 0.3548

Epoch 88/128

1916/1916 - 24s - 13ms/step - ia: 0.8718 - loss: 0.0774 - mae: 0.1745 - rmse: 0.2523 - smape: 0.4174 - val_ia: 0.6653 - val_loss: 0.0539 - val_mae: 0.1356 - val_rmse: 0.1877 - val_smape: 0.3629

Epoch 89/128

1916/1916 - 40s - 21ms/step - ia: 0.8722 - loss: 0.0780 - mae: 0.1735 - rmse: 0.2516 - smape: 0.4168 - val_ia: 0.6865 - val_loss: 0.0534 - val_mae: 0.1306 - val_rmse: 0.1835 - val_smape: 0.3539

Epoch 90/128

1916/1916 - 42s - 22ms/step - ia: 0.8715 - loss: 0.0779 - mae: 0.1746 - rmse: 0.2520 - smape: 0.4187 - val_ia: 0.6831 - val_loss: 0.0543 - val_mae: 0.1329 - val_rmse: 0.1852 - val_smape: 0.3548

Epoch 91/128

1916/1916 - 25s - 13ms/step - ia: 0.8719 - loss: 0.0776 - mae: 0.1741 - rmse: 0.2528 - smape: 0.4160 - val_ia: 0.6770 - val_loss: 0.0534 - val_mae: 0.1322 - val_rmse: 0.1855 - val_smape: 0.3580

Epoch 92/128

1916/1916 - 23s - 12ms/step - ia: 0.8716 - loss: 0.0771 - mae: 0.1737 - rmse: 0.2510 - smape: 0.4165 - val_ia: 0.6761 - val_loss: 0.0539 - val_mae: 0.1334 - val_rmse: 0.1858 - val_smape: 0.3580

Epoch 93/128

1916/1916 - 39s - 20ms/step - ia: 0.8719 - loss: 0.0768 - mae: 0.1741 - rmse: 0.2512 - smape: 0.4156 - val_ia: 0.6729 - val_loss: 0.0534 - val_mae: 0.1336 - val_rmse: 0.1856 - val_smape: 0.3588

Epoch 94/128

1916/1916 - 25s - 13ms/step - ia: 0.8717 - loss: 0.0776 - mae: 0.1738 - rmse: 0.2516 - smape: 0.4145 - val_ia: 0.6695 - val_loss: 0.0535 - val_mae: 0.1343 - val_rmse: 0.1860 - val_smape: 0.3585

Epoch 95/128

1916/1916 - 41s - 21ms/step - ia: 0.8718 - loss: 0.0780 - mae: 0.1733 - rmse: 0.2515 - smape: 0.4160 - val_ia: 0.6886 - val_loss: 0.0531 - val_mae: 0.1297 - val_rmse: 0.1833 - val_smape: 0.3529

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 31s - 8ms/step - ia: 0.2355 - loss: 1.1633 - mae: 0.8428 - rmse: 1.0255 - smape: 1.6544 - val_ia: 0.1763 - val_loss: 1.0118 - val_mae: 0.7988 - val_rmse: 0.8357 - val_smape: 1.7365

Epoch 2/128

3832/3832 - 23s - 6ms/step - ia: 0.2382 - loss: 1.1262 - mae: 0.8294 - rmse: 1.0087 - smape: 1.6579 - val_ia: 0.1777 - val_loss: 0.9913 - val_mae: 0.7891 - val_rmse: 0.8260 - val_smape: 1.7435

Epoch 3/128

3832/3832 - 22s - 6ms/step - ia: 0.2395 - loss: 1.0935 - mae: 0.8183 - rmse: 0.9915 - smape: 1.6640 - val_ia: 0.1788 - val_loss: 0.9729 - val_mae: 0.7800 - val_rmse: 0.8169 - val_smape: 1.7499

Epoch 4/128

3832/3832 - 23s - 6ms/step - ia: 0.2387 - loss: 1.0741 - mae: 0.8087 - rmse: 0.9827 - smape: 1.6691 - val_ia: 0.1795 - val_loss: 0.9560 - val_mae: 0.7719 - val_rmse: 0.8089 - val_smape: 1.7556

Epoch 5/128

3832/3832 - 23s - 6ms/step - ia: 0.2441 - loss: 1.0509 - mae: 0.7982 - rmse: 0.9717 - smape: 1.6620 - val_ia: 0.1802 - val_loss: 0.9403 - val_mae: 0.7639 - val_rmse: 0.8009 - val_smape: 1.7594

Epoch 6/128

3832/3832 - 22s - 6ms/step - ia: 0.2449 - loss: 1.0300 - mae: 0.7905 - rmse: 0.9619 - smape: 1.6680 - val_ia: 0.1809 - val_loss: 0.9252 - val_mae: 0.7565 - val_rmse: 0.7936 - val_smape: 1.7618

Epoch 7/128

3832/3832 - 23s - 6ms/step - ia: 0.2476 - loss: 1.0184 - mae: 0.7841 - rmse: 0.9553 - smape: 1.6676 - val_ia: 0.1815 - val_loss: 0.9116 - val_mae: 0.7498 - val_rmse: 0.7870 - val_smape: 1.7630

Epoch 8/128

3832/3832 - 23s - 6ms/step - ia: 0.2483 - loss: 1.0020 - mae: 0.7772 - rmse: 0.9457 - smape: 1.6667 - val_ia: 0.1822 - val_loss: 0.8984 - val_mae: 0.7434 - val_rmse: 0.7807 - val_smape: 1.7630

Epoch 9/128

3832/3832 - 23s - 6ms/step - ia: 0.2502 - loss: 0.9873 - mae: 0.7698 - rmse: 0.9391 - smape: 1.6666 - val_ia: 0.1830 - val_loss: 0.8853 - val_mae: 0.7372 - val_rmse: 0.7746 - val_smape: 1.7609

Epoch 10/128

3832/3832 - 23s - 6ms/step - ia: 0.2525 - loss: 0.9819 - mae: 0.7662 - rmse: 0.9368 - smape: 1.6665 - val_ia: 0.1837 - val_loss: 0.8738 - val_mae: 0.7316 - val_rmse: 0.7689 - val_smape: 1.7580

Epoch 11/128

3832/3832 - 23s - 6ms/step - ia: 0.2549 - loss: 0.9676 - mae: 0.7606 - rmse: 0.9291 - smape: 1.6687 - val_ia: 0.1843 - val_loss: 0.8618 - val_mae: 0.7260 - val_rmse: 0.7634 - val_smape: 1.7537

Epoch 12/128

3832/3832 - 22s - 6ms/step - ia: 0.2572 - loss: 0.9581 - mae: 0.7555 - rmse: 0.9233 - smape: 1.6627 - val_ia: 0.1850 - val_loss: 0.8501 - val_mae: 0.7206 - val_rmse: 0.7580 - val_smape: 1.7478

Epoch 13/128

3832/3832 - 23s - 6ms/step - ia: 0.2589 - loss: 0.9443 - mae: 0.7513 - rmse: 0.9166 - smape: 1.6622 - val_ia: 0.1856 - val_loss: 0.8380 - val_mae: 0.7154 - val_rmse: 0.7528 - val_smape: 1.7412

Epoch 14/128

3832/3832 - 40s - 11ms/step - ia: 0.2613 - loss: 0.9398 - mae: 0.7477 - rmse: 0.9129 - smape: 1.6572 - val_ia: 0.1863 - val_loss: 0.8273 - val_mae: 0.7104 - val_rmse: 0.7479 - val_smape: 1.7341

Epoch 15/128

3832/3832 - 23s - 6ms/step - ia: 0.2668 - loss: 0.9239 - mae: 0.7421 - rmse: 0.9085 - smape: 1.6482 - val_ia: 0.1870 - val_loss: 0.8161 - val_mae: 0.7055 - val_rmse: 0.7430 - val_smape: 1.7267

Epoch 16/128

3832/3832 - 23s - 6ms/step - ia: 0.2687 - loss: 0.9194 - mae: 0.7395 - rmse: 0.9047 - smape: 1.6490 - val_ia: 0.1876 - val_loss: 0.8049 - val_mae: 0.7009 - val_rmse: 0.7384 - val_smape: 1.7196

Epoch 17/128

3832/3832 - 22s - 6ms/step - ia: 0.2738 - loss: 0.9099 - mae: 0.7344 - rmse: 0.8987 - smape: 1.6441 - val_ia: 0.1882 - val_loss: 0.7941 - val_mae: 0.6963 - val_rmse: 0.7338 - val_smape: 1.7114

Epoch 18/128

3832/3832 - 22s - 6ms/step - ia: 0.2725 - loss: 0.9016 - mae: 0.7310 - rmse: 0.8944 - smape: 1.6388 - val_ia: 0.1888 - val_loss: 0.7831 - val_mae: 0.6918 - val_rmse: 0.7293 - val_smape: 1.7034

Epoch 19/128

3832/3832 - 42s - 11ms/step - ia: 0.2746 - loss: 0.8929 - mae: 0.7286 - rmse: 0.8916 - smape: 1.6353 - val_ia: 0.1894 - val_loss: 0.7714 - val_mae: 0.6868 - val_rmse: 0.7243 - val_smape: 1.6941

Epoch 20/128

3832/3832 - 23s - 6ms/step - ia: 0.2820 - loss: 0.8851 - mae: 0.7231 - rmse: 0.8862 - smape: 1.6256 - val_ia: 0.1900 - val_loss: 0.7597 - val_mae: 0.6817 - val_rmse: 0.7192 - val_smape: 1.6838

Epoch 21/128

3832/3832 - 23s - 6ms/step - ia: 0.2876 - loss: 0.8771 - mae: 0.7195 - rmse: 0.8799 - smape: 1.6185 - val_ia: 0.1905 - val_loss: 0.7479 - val_mae: 0.6769 - val_rmse: 0.7145 - val_smape: 1.6742

Epoch 22/128

3832/3832 - 23s - 6ms/step - ia: 0.2908 - loss: 0.8639 - mae: 0.7148 - rmse: 0.8754 - smape: 1.6100 - val_ia: 0.1911 - val_loss: 0.7363 - val_mae: 0.6718 - val_rmse: 0.7095 - val_smape: 1.6618

Epoch 23/128

3832/3832 - 49s - 13ms/step - ia: 0.2942 - loss: 0.8569 - mae: 0.7100 - rmse: 0.8713 - smape: 1.5976 - val_ia: 0.1916 - val_loss: 0.7239 - val_mae: 0.6664 - val_rmse: 0.7042 - val_smape: 1.6482

Epoch 24/128

3832/3832 - 30s - 8ms/step - ia: 0.2969 - loss: 0.8482 - mae: 0.7066 - rmse: 0.8683 - smape: 1.5891 - val_ia: 0.1921 - val_loss: 0.7121 - val_mae: 0.6612 - val_rmse: 0.6990 - val_smape: 1.6346

Epoch 25/128

3832/3832 - 33s - 9ms/step - ia: 0.3038 - loss: 0.8383 - mae: 0.7025 - rmse: 0.8606 - smape: 1.5841 - val_ia: 0.1924 - val_loss: 0.7003 - val_mae: 0.6560 - val_rmse: 0.6939 - val_smape: 1.6208

Epoch 26/128

3832/3832 - 31s - 8ms/step - ia: 0.3100 - loss: 0.8272 - mae: 0.6985 - rmse: 0.8560 - smape: 1.5730 - val_ia: 0.1929 - val_loss: 0.6886 - val_mae: 0.6508 - val_rmse: 0.6888 - val_smape: 1.6059

Epoch 27/128

3832/3832 - 29s - 8ms/step - ia: 0.3133 - loss: 0.8208 - mae: 0.6941 - rmse: 0.8541 - smape: 1.5638 - val_ia: 0.1935 - val_loss: 0.6764 - val_mae: 0.6454 - val_rmse: 0.6835 - val_smape: 1.5885

Epoch 28/128

3832/3832 - 28s - 7ms/step - ia: 0.3216 - loss: 0.8013 - mae: 0.6876 - rmse: 0.8419 - smape: 1.5494 - val_ia: 0.1941 - val_loss: 0.6642 - val_mae: 0.6397 - val_rmse: 0.6779 - val_smape: 1.5693

Epoch 29/128

3832/3832 - 30s - 8ms/step - ia: 0.3230 - loss: 0.8031 - mae: 0.6865 - rmse: 0.8436 - smape: 1.5409 - val_ia: 0.1946 - val_loss: 0.6529 - val_mae: 0.6343 - val_rmse: 0.6727 - val_smape: 1.5498

Epoch 30/128

3832/3832 - 30s - 8ms/step - ia: 0.3265 - loss: 0.7985 - mae: 0.6832 - rmse: 0.8414 - smape: 1.5385 - val_ia: 0.1950 - val_loss: 0.6418 - val_mae: 0.6293 - val_rmse: 0.6677 - val_smape: 1.5311

Epoch 31/128

3832/3832 - 28s - 7ms/step - ia: 0.3328 - loss: 0.7910 - mae: 0.6788 - rmse: 0.8351 - smape: 1.5247 - val_ia: 0.1956 - val_loss: 0.6300 - val_mae: 0.6235 - val_rmse: 0.6620 - val_smape: 1.5099

Epoch 32/128

3832/3832 - 29s - 7ms/step - ia: 0.3401 - loss: 0.7807 - mae: 0.6734 - rmse: 0.8291 - smape: 1.5107 - val_ia: 0.1960 - val_loss: 0.6190 - val_mae: 0.6184 - val_rmse: 0.6570 - val_smape: 1.4906

Epoch 33/128

3832/3832 - 29s - 8ms/step - ia: 0.3464 - loss: 0.7672 - mae: 0.6687 - rmse: 0.8236 - smape: 1.4938 - val_ia: 0.1964 - val_loss: 0.6085 - val_mae: 0.6133 - val_rmse: 0.6519 - val_smape: 1.4708

Epoch 34/128

3832/3832 - 44s - 11ms/step - ia: 0.3510 - loss: 0.7600 - mae: 0.6640 - rmse: 0.8171 - smape: 1.4869 - val_ia: 0.1969 - val_loss: 0.5980 - val_mae: 0.6078 - val_rmse: 0.6466 - val_smape: 1.4491

Epoch 35/128

3832/3832 - 28s - 7ms/step - ia: 0.3567 - loss: 0.7584 - mae: 0.6612 - rmse: 0.8173 - smape: 1.4764 - val_ia: 0.1974 - val_loss: 0.5885 - val_mae: 0.6026 - val_rmse: 0.6415 - val_smape: 1.4280

Epoch 36/128

3832/3832 - 28s - 7ms/step - ia: 0.3603 - loss: 0.7432 - mae: 0.6559 - rmse: 0.8096 - smape: 1.4689 - val_ia: 0.1980 - val_loss: 0.5789 - val_mae: 0.5973 - val_rmse: 0.6363 - val_smape: 1.4074

Epoch 37/128

3832/3832 - 28s - 7ms/step - ia: 0.3655 - loss: 0.7437 - mae: 0.6549 - rmse: 0.8095 - smape: 1.4560 - val_ia: 0.1985 - val_loss: 0.5704 - val_mae: 0.5925 - val_rmse: 0.6316 - val_smape: 1.3885

Epoch 38/128

3832/3832 - 27s - 7ms/step - ia: 0.3714 - loss: 0.7340 - mae: 0.6482 - rmse: 0.8028 - smape: 1.4448 - val_ia: 0.1991 - val_loss: 0.5619 - val_mae: 0.5878 - val_rmse: 0.6270 - val_smape: 1.3700

Epoch 39/128

3832/3832 - 28s - 7ms/step - ia: 0.3739 - loss: 0.7354 - mae: 0.6465 - rmse: 0.8028 - smape: 1.4363 - val_ia: 0.1998 - val_loss: 0.5540 - val_mae: 0.5828 - val_rmse: 0.6221 - val_smape: 1.3503

Epoch 40/128

3832/3832 - 29s - 8ms/step - ia: 0.3792 - loss: 0.7272 - mae: 0.6418 - rmse: 0.7975 - smape: 1.4205 - val_ia: 0.2004 - val_loss: 0.5460 - val_mae: 0.5779 - val_rmse: 0.6174 - val_smape: 1.3309

Epoch 41/128

3832/3832 - 29s - 8ms/step - ia: 0.3822 - loss: 0.7219 - mae: 0.6391 - rmse: 0.7947 - smape: 1.4145 - val_ia: 0.2011 - val_loss: 0.5377 - val_mae: 0.5729 - val_rmse: 0.6125 - val_smape: 1.3116

Epoch 42/128

3832/3832 - 40s - 11ms/step - ia: 0.3897 - loss: 0.7101 - mae: 0.6335 - rmse: 0.7888 - smape: 1.3993 - val_ia: 0.2018 - val_loss: 0.5294 - val_mae: 0.5681 - val_rmse: 0.6079 - val_smape: 1.2938

Epoch 43/128

3832/3832 - 37s - 10ms/step - ia: 0.3954 - loss: 0.7070 - mae: 0.6288 - rmse: 0.7835 - smape: 1.3839 - val_ia: 0.2026 - val_loss: 0.5225 - val_mae: 0.5635 - val_rmse: 0.6034 - val_smape: 1.2758

Epoch 44/128

3832/3832 - 44s - 12ms/step - ia: 0.4007 - loss: 0.7030 - mae: 0.6247 - rmse: 0.7822 - smape: 1.3745 - val_ia: 0.2032 - val_loss: 0.5160 - val_mae: 0.5591 - val_rmse: 0.5991 - val_smape: 1.2587

Epoch 45/128

3832/3832 - 24s - 6ms/step - ia: 0.4041 - loss: 0.6914 - mae: 0.6228 - rmse: 0.7783 - smape: 1.3657 - val_ia: 0.2039 - val_loss: 0.5094 - val_mae: 0.5548 - val_rmse: 0.5949 - val_smape: 1.2428

Epoch 46/128

3832/3832 - 22s - 6ms/step - ia: 0.4077 - loss: 0.6909 - mae: 0.6209 - rmse: 0.7757 - smape: 1.3590 - val_ia: 0.2045 - val_loss: 0.5035 - val_mae: 0.5510 - val_rmse: 0.5911 - val_smape: 1.2283

Epoch 47/128

3832/3832 - 22s - 6ms/step - ia: 0.4097 - loss: 0.6899 - mae: 0.6195 - rmse: 0.7749 - smape: 1.3539 - val_ia: 0.2053 - val_loss: 0.4978 - val_mae: 0.5469 - val_rmse: 0.5871 - val_smape: 1.2126

Epoch 48/128

3832/3832 - 22s - 6ms/step - ia: 0.4219 - loss: 0.6697 - mae: 0.6089 - rmse: 0.7633 - smape: 1.3307 - val_ia: 0.2060 - val_loss: 0.4915 - val_mae: 0.5426 - val_rmse: 0.5829 - val_smape: 1.1968

Epoch 49/128

3832/3832 - 22s - 6ms/step - ia: 0.4227 - loss: 0.6724 - mae: 0.6086 - rmse: 0.7648 - smape: 1.3270 - val_ia: 0.2067 - val_loss: 0.4860 - val_mae: 0.5387 - val_rmse: 0.5791 - val_smape: 1.1818

Epoch 50/128

3832/3832 - 22s - 6ms/step - ia: 0.4261 - loss: 0.6725 - mae: 0.6070 - rmse: 0.7635 - smape: 1.3194 - val_ia: 0.2074 - val_loss: 0.4810 - val_mae: 0.5350 - val_rmse: 0.5755 - val_smape: 1.1682

Epoch 51/128

3832/3832 - 21s - 6ms/step - ia: 0.4283 - loss: 0.6715 - mae: 0.6046 - rmse: 0.7611 - smape: 1.3098 - val_ia: 0.2079 - val_loss: 0.4765 - val_mae: 0.5318 - val_rmse: 0.5724 - val_smape: 1.1563

Epoch 52/128

3832/3832 - 37s - 10ms/step - ia: 0.4361 - loss: 0.6547 - mae: 0.5993 - rmse: 0.7552 - smape: 1.3000 - val_ia: 0.2084 - val_loss: 0.4710 - val_mae: 0.5282 - val_rmse: 0.5689 - val_smape: 1.1437

Epoch 53/128

3832/3832 - 21s - 5ms/step - ia: 0.4410 - loss: 0.6575 - mae: 0.5965 - rmse: 0.7539 - smape: 1.2896 - val_ia: 0.2089 - val_loss: 0.4675 - val_mae: 0.5252 - val_rmse: 0.5659 - val_smape: 1.1322

Epoch 54/128

3832/3832 - 21s - 5ms/step - ia: 0.4393 - loss: 0.6629 - mae: 0.5962 - rmse: 0.7559 - smape: 1.2845 - val_ia: 0.2094 - val_loss: 0.4634 - val_mae: 0.5224 - val_rmse: 0.5632 - val_smape: 1.1223

Epoch 55/128

3832/3832 - 21s - 6ms/step - ia: 0.4431 - loss: 0.6497 - mae: 0.5933 - rmse: 0.7515 - smape: 1.2807 - val_ia: 0.2098 - val_loss: 0.4591 - val_mae: 0.5196 - val_rmse: 0.5604 - val_smape: 1.1129

Epoch 56/128

3832/3832 - 22s - 6ms/step - ia: 0.4464 - loss: 0.6439 - mae: 0.5892 - rmse: 0.7464 - smape: 1.2730 - val_ia: 0.2103 - val_loss: 0.4547 - val_mae: 0.5166 - val_rmse: 0.5575 - val_smape: 1.1031

Epoch 57/128

3832/3832 - 41s - 11ms/step - ia: 0.4543 - loss: 0.6344 - mae: 0.5842 - rmse: 0.7411 - smape: 1.2586 - val_ia: 0.2106 - val_loss: 0.4508 - val_mae: 0.5138 - val_rmse: 0.5548 - val_smape: 1.0940

Epoch 58/128

3832/3832 - 22s - 6ms/step - ia: 0.4540 - loss: 0.6344 - mae: 0.5856 - rmse: 0.7419 - smape: 1.2609 - val_ia: 0.2109 - val_loss: 0.4475 - val_mae: 0.5114 - val_rmse: 0.5524 - val_smape: 1.0859

Epoch 59/128

3832/3832 - 41s - 11ms/step - ia: 0.4587 - loss: 0.6325 - mae: 0.5828 - rmse: 0.7401 - smape: 1.2469 - val_ia: 0.2112 - val_loss: 0.4441 - val_mae: 0.5091 - val_rmse: 0.5502 - val_smape: 1.0785

Epoch 60/128

3832/3832 - 22s - 6ms/step - ia: 0.4591 - loss: 0.6380 - mae: 0.5825 - rmse: 0.7406 - smape: 1.2478 - val_ia: 0.2114 - val_loss: 0.4410 - val_mae: 0.5071 - val_rmse: 0.5481 - val_smape: 1.0719

Epoch 61/128

3832/3832 - 22s - 6ms/step - ia: 0.4627 - loss: 0.6345 - mae: 0.5794 - rmse: 0.7388 - smape: 1.2384 - val_ia: 0.2116 - val_loss: 0.4390 - val_mae: 0.5054 - val_rmse: 0.5465 - val_smape: 1.0659

Epoch 62/128

3832/3832 - 22s - 6ms/step - ia: 0.4632 - loss: 0.6375 - mae: 0.5792 - rmse: 0.7405 - smape: 1.2348 - val_ia: 0.2119 - val_loss: 0.4364 - val_mae: 0.5035 - val_rmse: 0.5446 - val_smape: 1.0603

Epoch 63/128

3832/3832 - 22s - 6ms/step - ia: 0.4630 - loss: 0.6336 - mae: 0.5804 - rmse: 0.7382 - smape: 1.2386 - val_ia: 0.2121 - val_loss: 0.4349 - val_mae: 0.5023 - val_rmse: 0.5434 - val_smape: 1.0560

Epoch 64/128

3832/3832 - 22s - 6ms/step - ia: 0.4683 - loss: 0.6257 - mae: 0.5742 - rmse: 0.7325 - smape: 1.2269 - val_ia: 0.2123 - val_loss: 0.4327 - val_mae: 0.5006 - val_rmse: 0.5418 - val_smape: 1.0509

Epoch 65/128

3832/3832 - 21s - 6ms/step - ia: 0.4701 - loss: 0.6193 - mae: 0.5728 - rmse: 0.7302 - smape: 1.2199 - val_ia: 0.2126 - val_loss: 0.4299 - val_mae: 0.4990 - val_rmse: 0.5402 - val_smape: 1.0462

Epoch 66/128

3832/3832 - 22s - 6ms/step - ia: 0.4755 - loss: 0.6216 - mae: 0.5706 - rmse: 0.7303 - smape: 1.2127 - val_ia: 0.2128 - val_loss: 0.4287 - val_mae: 0.4980 - val_rmse: 0.5392 - val_smape: 1.0429

Epoch 67/128

3832/3832 - 22s - 6ms/step - ia: 0.4718 - loss: 0.6187 - mae: 0.5712 - rmse: 0.7293 - smape: 1.2181 - val_ia: 0.2130 - val_loss: 0.4264 - val_mae: 0.4966 - val_rmse: 0.5378 - val_smape: 1.0389

Epoch 68/128

3832/3832 - 41s - 11ms/step - ia: 0.4761 - loss: 0.6286 - mae: 0.5704 - rmse: 0.7303 - smape: 1.2095 - val_ia: 0.2132 - val_loss: 0.4260 - val_mae: 0.4960 - val_rmse: 0.5371 - val_smape: 1.0364

Epoch 69/128

3832/3832 - 39s - 10ms/step - ia: 0.4771 - loss: 0.6008 - mae: 0.5653 - rmse: 0.7204 - smape: 1.2101 - val_ia: 0.2135 - val_loss: 0.4235 - val_mae: 0.4946 - val_rmse: 0.5357 - val_smape: 1.0327

Epoch 70/128

3832/3832 - 22s - 6ms/step - ia: 0.4783 - loss: 0.6147 - mae: 0.5684 - rmse: 0.7264 - smape: 1.2086 - val_ia: 0.2137 - val_loss: 0.4219 - val_mae: 0.4934 - val_rmse: 0.5346 - val_smape: 1.0295

Epoch 71/128

3832/3832 - 22s - 6ms/step - ia: 0.4798 - loss: 0.6160 - mae: 0.5659 - rmse: 0.7243 - smape: 1.2018 - val_ia: 0.2139 - val_loss: 0.4205 - val_mae: 0.4927 - val_rmse: 0.5338 - val_smape: 1.0276

Epoch 72/128

3832/3832 - 22s - 6ms/step - ia: 0.4791 - loss: 0.6185 - mae: 0.5674 - rmse: 0.7265 - smape: 1.2007 - val_ia: 0.2140 - val_loss: 0.4201 - val_mae: 0.4923 - val_rmse: 0.5334 - val_smape: 1.0262

Epoch 73/128

3832/3832 - 30s - 8ms/step - ia: 0.4761 - loss: 0.6173 - mae: 0.5685 - rmse: 0.7268 - smape: 1.2009 - val_ia: 0.2142 - val_loss: 0.4193 - val_mae: 0.4919 - val_rmse: 0.5330 - val_smape: 1.0250

Epoch 74/128

3832/3832 - 34s - 9ms/step - ia: 0.4830 - loss: 0.6018 - mae: 0.5615 - rmse: 0.7185 - smape: 1.1922 - val_ia: 0.2144 - val_loss: 0.4176 - val_mae: 0.4908 - val_rmse: 0.5319 - val_smape: 1.0224

Epoch 75/128

3832/3832 - 22s - 6ms/step - ia: 0.4828 - loss: 0.6049 - mae: 0.5641 - rmse: 0.7199 - smape: 1.1933 - val_ia: 0.2146 - val_loss: 0.4163 - val_mae: 0.4900 - val_rmse: 0.5311 - val_smape: 1.0204

Epoch 76/128

3832/3832 - 22s - 6ms/step - ia: 0.4873 - loss: 0.6060 - mae: 0.5612 - rmse: 0.7204 - smape: 1.1840 - val_ia: 0.2147 - val_loss: 0.4160 - val_mae: 0.4898 - val_rmse: 0.5308 - val_smape: 1.0193

Epoch 77/128

3832/3832 - 22s - 6ms/step - ia: 0.4856 - loss: 0.6040 - mae: 0.5602 - rmse: 0.7183 - smape: 1.1807 - val_ia: 0.2149 - val_loss: 0.4150 - val_mae: 0.4892 - val_rmse: 0.5302 - val_smape: 1.0176

Epoch 78/128

3832/3832 - 22s - 6ms/step - ia: 0.4877 - loss: 0.6020 - mae: 0.5587 - rmse: 0.7172 - smape: 1.1807 - val_ia: 0.2151 - val_loss: 0.4137 - val_mae: 0.4886 - val_rmse: 0.5297 - val_smape: 1.0164

Epoch 79/128

3832/3832 - 40s - 10ms/step - ia: 0.4886 - loss: 0.5961 - mae: 0.5579 - rmse: 0.7161 - smape: 1.1773 - val_ia: 0.2153 - val_loss: 0.4129 - val_mae: 0.4879 - val_rmse: 0.5289 - val_smape: 1.0141

Epoch 80/128

3832/3832 - 42s - 11ms/step - ia: 0.4847 - loss: 0.6042 - mae: 0.5616 - rmse: 0.7201 - smape: 1.1829 - val_ia: 0.2154 - val_loss: 0.4120 - val_mae: 0.4873 - val_rmse: 0.5284 - val_smape: 1.0125

Epoch 81/128

3832/3832 - 21s - 6ms/step - ia: 0.4913 - loss: 0.5909 - mae: 0.5551 - rmse: 0.7114 - smape: 1.1733 - val_ia: 0.2156 - val_loss: 0.4105 - val_mae: 0.4865 - val_rmse: 0.5276 - val_smape: 1.0107

Epoch 82/128

3832/3832 - 48s - 13ms/step - ia: 0.4926 - loss: 0.5964 - mae: 0.5545 - rmse: 0.7126 - smape: 1.1680 - val_ia: 0.2159 - val_loss: 0.4087 - val_mae: 0.4855 - val_rmse: 0.5266 - val_smape: 1.0084

Epoch 83/128

3832/3832 - 26s - 7ms/step - ia: 0.4956 - loss: 0.5935 - mae: 0.5539 - rmse: 0.7116 - smape: 1.1641 - val_ia: 0.2160 - val_loss: 0.4082 - val_mae: 0.4852 - val_rmse: 0.5262 - val_smape: 1.0074

Epoch 84/128

3832/3832 - 26s - 7ms/step - ia: 0.4945 - loss: 0.5868 - mae: 0.5526 - rmse: 0.7087 - smape: 1.1617 - val_ia: 0.2162 - val_loss: 0.4062 - val_mae: 0.4843 - val_rmse: 0.5253 - val_smape: 1.0056

Epoch 85/128

3832/3832 - 35s - 9ms/step - ia: 0.4932 - loss: 0.5888 - mae: 0.5531 - rmse: 0.7097 - smape: 1.1628 - val_ia: 0.2163 - val_loss: 0.4054 - val_mae: 0.4838 - val_rmse: 0.5248 - val_smape: 1.0042

Epoch 86/128

3832/3832 - 22s - 6ms/step - ia: 0.4994 - loss: 0.5779 - mae: 0.5492 - rmse: 0.7045 - smape: 1.1531 - val_ia: 0.2165 - val_loss: 0.4047 - val_mae: 0.4832 - val_rmse: 0.5243 - val_smape: 1.0027

Epoch 87/128

3832/3832 - 27s - 7ms/step - ia: 0.4970 - loss: 0.5867 - mae: 0.5518 - rmse: 0.7073 - smape: 1.1572 - val_ia: 0.2166 - val_loss: 0.4043 - val_mae: 0.4830 - val_rmse: 0.5240 - val_smape: 1.0017

Epoch 88/128

3832/3832 - 21s - 5ms/step - ia: 0.4987 - loss: 0.5851 - mae: 0.5479 - rmse: 0.7058 - smape: 1.1507 - val_ia: 0.2167 - val_loss: 0.4038 - val_mae: 0.4826 - val_rmse: 0.5237 - val_smape: 1.0006

Epoch 89/128

3832/3832 - 23s - 6ms/step - ia: 0.5035 - loss: 0.5769 - mae: 0.5440 - rmse: 0.7007 - smape: 1.1436 - val_ia: 0.2168 - val_loss: 0.4028 - val_mae: 0.4821 - val_rmse: 0.5231 - val_smape: 0.9994

Epoch 90/128

3832/3832 - 26s - 7ms/step - ia: 0.5018 - loss: 0.5757 - mae: 0.5448 - rmse: 0.7015 - smape: 1.1413 - val_ia: 0.2170 - val_loss: 0.4018 - val_mae: 0.4815 - val_rmse: 0.5225 - val_smape: 0.9979

Epoch 91/128

3832/3832 - 19s - 5ms/step - ia: 0.5019 - loss: 0.5764 - mae: 0.5460 - rmse: 0.6997 - smape: 1.1432 - val_ia: 0.2171 - val_loss: 0.4012 - val_mae: 0.4812 - val_rmse: 0.5222 - val_smape: 0.9970

Epoch 92/128

3832/3832 - 24s - 6ms/step - ia: 0.5017 - loss: 0.5785 - mae: 0.5466 - rmse: 0.7031 - smape: 1.1418 - val_ia: 0.2173 - val_loss: 0.4006 - val_mae: 0.4807 - val_rmse: 0.5217 - val_smape: 0.9958

Epoch 93/128

3832/3832 - 18s - 5ms/step - ia: 0.5025 - loss: 0.5768 - mae: 0.5449 - rmse: 0.7012 - smape: 1.1409 - val_ia: 0.2174 - val_loss: 0.3996 - val_mae: 0.4802 - val_rmse: 0.5212 - val_smape: 0.9946

Epoch 94/128

3832/3832 - 28s - 7ms/step - ia: 0.5052 - loss: 0.5664 - mae: 0.5427 - rmse: 0.6962 - smape: 1.1375 - val_ia: 0.2175 - val_loss: 0.3980 - val_mae: 0.4795 - val_rmse: 0.5205 - val_smape: 0.9931

Epoch 95/128

3832/3832 - 26s - 7ms/step - ia: 0.5051 - loss: 0.5722 - mae: 0.5425 - rmse: 0.6986 - smape: 1.1298 - val_ia: 0.2176 - val_loss: 0.3970 - val_mae: 0.4790 - val_rmse: 0.5200 - val_smape: 0.9920

Epoch 96/128

3832/3832 - 26s - 7ms/step - ia: 0.5081 - loss: 0.5663 - mae: 0.5393 - rmse: 0.6950 - smape: 1.1286 - val_ia: 0.2179 - val_loss: 0.3953 - val_mae: 0.4779 - val_rmse: 0.5190 - val_smape: 0.9896

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 35s - 147ms/step - ia: 0.4550 - loss: 0.6698 - mae: 0.5883 - rmse: 0.7984 - smape: 1.1950 - val_ia: 0.6910 - val_loss: 0.2118 - val_mae: 0.3172 - val_rmse: 0.4199 - val_smape: 0.7070

Epoch 2/128

240/240 - 7s - 28ms/step - ia: 0.7491 - loss: 0.2476 - mae: 0.3542 - rmse: 0.4927 - smape: 0.7374 - val_ia: 0.7600 - val_loss: 0.1423 - val_mae: 0.2420 - val_rmse: 0.3436 - val_smape: 0.5678

Epoch 3/128

240/240 - 10s - 40ms/step - ia: 0.7806 - loss: 0.2001 - mae: 0.3112 - rmse: 0.4429 - smape: 0.6732 - val_ia: 0.7860 - val_loss: 0.1186 - val_mae: 0.2159 - val_rmse: 0.3146 - val_smape: 0.5205

Epoch 4/128

240/240 - 11s - 44ms/step - ia: 0.8000 - loss: 0.1700 - mae: 0.2850 - rmse: 0.4081 - smape: 0.6312 - val_ia: 0.7995 - val_loss: 0.1047 - val_mae: 0.2009 - val_rmse: 0.2961 - val_smape: 0.4933

Epoch 5/128

240/240 - 6s - 26ms/step - ia: 0.8123 - loss: 0.1536 - mae: 0.2681 - rmse: 0.3871 - smape: 0.6042 - val_ia: 0.8097 - val_loss: 0.0957 - val_mae: 0.1906 - val_rmse: 0.2836 - val_smape: 0.4729

Epoch 6/128

240/240 - 6s - 24ms/step - ia: 0.8239 - loss: 0.1383 - mae: 0.2520 - rmse: 0.3666 - smape: 0.5755 - val_ia: 0.8101 - val_loss: 0.0898 - val_mae: 0.1873 - val_rmse: 0.2765 - val_smape: 0.4692

Epoch 7/128

240/240 - 5s - 19ms/step - ia: 0.8294 - loss: 0.1312 - mae: 0.2451 - rmse: 0.3572 - smape: 0.5640 - val_ia: 0.8205 - val_loss: 0.0843 - val_mae: 0.1781 - val_rmse: 0.2682 - val_smape: 0.4518

Epoch 8/128

240/240 - 4s - 17ms/step - ia: 0.8363 - loss: 0.1236 - mae: 0.2352 - rmse: 0.3463 - smape: 0.5452 - val_ia: 0.8349 - val_loss: 0.0789 - val_mae: 0.1672 - val_rmse: 0.2573 - val_smape: 0.4278

Epoch 9/128

240/240 - 4s - 17ms/step - ia: 0.8413 - loss: 0.1181 - mae: 0.2284 - rmse: 0.3375 - smape: 0.5337 - val_ia: 0.8405 - val_loss: 0.0761 - val_mae: 0.1624 - val_rmse: 0.2523 - val_smape: 0.4194

Epoch 10/128

240/240 - 8s - 32ms/step - ia: 0.8460 - loss: 0.1127 - mae: 0.2220 - rmse: 0.3302 - smape: 0.5229 - val_ia: 0.8425 - val_loss: 0.0742 - val_mae: 0.1607 - val_rmse: 0.2488 - val_smape: 0.4158

Epoch 11/128

240/240 - 6s - 25ms/step - ia: 0.8500 - loss: 0.1074 - mae: 0.2165 - rmse: 0.3224 - smape: 0.5104 - val_ia: 0.8417 - val_loss: 0.0739 - val_mae: 0.1616 - val_rmse: 0.2480 - val_smape: 0.4151

Epoch 12/128

240/240 - 6s - 24ms/step - ia: 0.8538 - loss: 0.1045 - mae: 0.2115 - rmse: 0.3177 - smape: 0.5003 - val_ia: 0.8480 - val_loss: 0.0706 - val_mae: 0.1554 - val_rmse: 0.2428 - val_smape: 0.4058

Epoch 13/128

240/240 - 9s - 40ms/step - ia: 0.8559 - loss: 0.1015 - mae: 0.2081 - rmse: 0.3129 - smape: 0.4971 - val_ia: 0.8470 - val_loss: 0.0686 - val_mae: 0.1537 - val_rmse: 0.2403 - val_smape: 0.4005

Epoch 14/128

240/240 - 7s - 28ms/step - ia: 0.8585 - loss: 0.0981 - mae: 0.2049 - rmse: 0.3076 - smape: 0.4913 - val_ia: 0.8491 - val_loss: 0.0680 - val_mae: 0.1530 - val_rmse: 0.2384 - val_smape: 0.3995

Epoch 15/128

240/240 - 10s - 40ms/step - ia: 0.8600 - loss: 0.0968 - mae: 0.2028 - rmse: 0.3044 - smape: 0.4842 - val_ia: 0.8537 - val_loss: 0.0662 - val_mae: 0.1492 - val_rmse: 0.2352 - val_smape: 0.3940

Epoch 16/128

240/240 - 10s - 42ms/step - ia: 0.8628 - loss: 0.0946 - mae: 0.1985 - rmse: 0.3015 - smape: 0.4774 - val_ia: 0.8483 - val_loss: 0.0654 - val_mae: 0.1515 - val_rmse: 0.2348 - val_smape: 0.3932

Epoch 17/128

240/240 - 11s - 45ms/step - ia: 0.8653 - loss: 0.0919 - mae: 0.1952 - rmse: 0.2967 - smape: 0.4698 - val_ia: 0.8564 - val_loss: 0.0640 - val_mae: 0.1464 - val_rmse: 0.2313 - val_smape: 0.3877

Epoch 18/128

240/240 - 6s - 24ms/step - ia: 0.8670 - loss: 0.0896 - mae: 0.1927 - rmse: 0.2939 - smape: 0.4662 - val_ia: 0.8536 - val_loss: 0.0631 - val_mae: 0.1472 - val_rmse: 0.2301 - val_smape: 0.3865

Epoch 19/128

240/240 - 10s - 41ms/step - ia: 0.8690 - loss: 0.0875 - mae: 0.1901 - rmse: 0.2889 - smape: 0.4615 - val_ia: 0.8530 - val_loss: 0.0623 - val_mae: 0.1466 - val_rmse: 0.2293 - val_smape: 0.3850

Epoch 20/128

240/240 - 6s - 23ms/step - ia: 0.8693 - loss: 0.0874 - mae: 0.1897 - rmse: 0.2889 - smape: 0.4597 - val_ia: 0.8567 - val_loss: 0.0621 - val_mae: 0.1450 - val_rmse: 0.2277 - val_smape: 0.3817

Epoch 21/128

240/240 - 11s - 44ms/step - ia: 0.8717 - loss: 0.0852 - mae: 0.1862 - rmse: 0.2856 - smape: 0.4543 - val_ia: 0.8601 - val_loss: 0.0605 - val_mae: 0.1413 - val_rmse: 0.2255 - val_smape: 0.3757

Epoch 22/128

240/240 - 6s - 25ms/step - ia: 0.8734 - loss: 0.0833 - mae: 0.1838 - rmse: 0.2816 - smape: 0.4502 - val_ia: 0.8601 - val_loss: 0.0603 - val_mae: 0.1416 - val_rmse: 0.2245 - val_smape: 0.3751

Epoch 23/128

240/240 - 6s - 23ms/step - ia: 0.8736 - loss: 0.0831 - mae: 0.1838 - rmse: 0.2821 - smape: 0.4490 - val_ia: 0.8613 - val_loss: 0.0597 - val_mae: 0.1403 - val_rmse: 0.2233 - val_smape: 0.3727

Epoch 24/128

240/240 - 5s - 22ms/step - ia: 0.8759 - loss: 0.0805 - mae: 0.1806 - rmse: 0.2774 - smape: 0.4403 - val_ia: 0.8650 - val_loss: 0.0587 - val_mae: 0.1375 - val_rmse: 0.2213 - val_smape: 0.3691

Epoch 25/128

240/240 - 11s - 45ms/step - ia: 0.8769 - loss: 0.0799 - mae: 0.1791 - rmse: 0.2756 - smape: 0.4399 - val_ia: 0.8657 - val_loss: 0.0583 - val_mae: 0.1367 - val_rmse: 0.2205 - val_smape: 0.3667

Epoch 26/128

240/240 - 6s - 26ms/step - ia: 0.8782 - loss: 0.0788 - mae: 0.1771 - rmse: 0.2740 - smape: 0.4333 - val_ia: 0.8632 - val_loss: 0.0582 - val_mae: 0.1384 - val_rmse: 0.2201 - val_smape: 0.3679

Epoch 27/128

240/240 - 9s - 38ms/step - ia: 0.8792 - loss: 0.0780 - mae: 0.1757 - rmse: 0.2733 - smape: 0.4327 - val_ia: 0.8628 - val_loss: 0.0580 - val_mae: 0.1384 - val_rmse: 0.2200 - val_smape: 0.3678

Epoch 28/128

240/240 - 6s - 24ms/step - ia: 0.8797 - loss: 0.0773 - mae: 0.1748 - rmse: 0.2722 - smape: 0.4292 - val_ia: 0.8610 - val_loss: 0.0580 - val_mae: 0.1395 - val_rmse: 0.2201 - val_smape: 0.3689

Epoch 29/128

240/240 - 6s - 24ms/step - ia: 0.8815 - loss: 0.0764 - mae: 0.1725 - rmse: 0.2693 - smape: 0.4273 - val_ia: 0.8571 - val_loss: 0.0582 - val_mae: 0.1417 - val_rmse: 0.2219 - val_smape: 0.3750

Epoch 30/128

240/240 - 10s - 43ms/step - ia: 0.8814 - loss: 0.0764 - mae: 0.1727 - rmse: 0.2700 - smape: 0.4251 - val_ia: 0.8600 - val_loss: 0.0577 - val_mae: 0.1396 - val_rmse: 0.2202 - val_smape: 0.3692

Epoch 31/128

240/240 - 11s - 44ms/step - ia: 0.8827 - loss: 0.0751 - mae: 0.1708 - rmse: 0.2678 - smape: 0.4212 - val_ia: 0.8692 - val_loss: 0.0567 - val_mae: 0.1336 - val_rmse: 0.2169 - val_smape: 0.3602

Epoch 32/128

240/240 - 10s - 42ms/step - ia: 0.8828 - loss: 0.0755 - mae: 0.1706 - rmse: 0.2688 - smape: 0.4195 - val_ia: 0.8667 - val_loss: 0.0567 - val_mae: 0.1352 - val_rmse: 0.2171 - val_smape: 0.3614

Epoch 33/128

240/240 - 10s - 41ms/step - ia: 0.8840 - loss: 0.0744 - mae: 0.1690 - rmse: 0.2660 - smape: 0.4189 - val_ia: 0.8672 - val_loss: 0.0568 - val_mae: 0.1350 - val_rmse: 0.2169 - val_smape: 0.3608

Epoch 34/128

240/240 - 11s - 46ms/step - ia: 0.8836 - loss: 0.0748 - mae: 0.1695 - rmse: 0.2671 - smape: 0.4196 - val_ia: 0.8685 - val_loss: 0.0564 - val_mae: 0.1340 - val_rmse: 0.2160 - val_smape: 0.3596

Epoch 35/128

240/240 - 10s - 42ms/step - ia: 0.8847 - loss: 0.0743 - mae: 0.1681 - rmse: 0.2657 - smape: 0.4157 - val_ia: 0.8697 - val_loss: 0.0562 - val_mae: 0.1328 - val_rmse: 0.2160 - val_smape: 0.3575

Epoch 36/128

240/240 - 4s - 18ms/step - ia: 0.8859 - loss: 0.0731 - mae: 0.1663 - rmse: 0.2629 - smape: 0.4138 - val_ia: 0.8641 - val_loss: 0.0566 - val_mae: 0.1367 - val_rmse: 0.2172 - val_smape: 0.3626

Epoch 37/128

240/240 - 5s - 20ms/step - ia: 0.8860 - loss: 0.0731 - mae: 0.1663 - rmse: 0.2643 - smape: 0.4120 - val_ia: 0.8671 - val_loss: 0.0571 - val_mae: 0.1356 - val_rmse: 0.2170 - val_smape: 0.3609

Epoch 38/128

240/240 - 4s - 16ms/step - ia: 0.8858 - loss: 0.0728 - mae: 0.1666 - rmse: 0.2629 - smape: 0.4096 - val_ia: 0.8694 - val_loss: 0.0563 - val_mae: 0.1328 - val_rmse: 0.2163 - val_smape: 0.3568

Epoch 39/128

240/240 - 4s - 15ms/step - ia: 0.8869 - loss: 0.0721 - mae: 0.1653 - rmse: 0.2621 - smape: 0.4092 - val_ia: 0.8685 - val_loss: 0.0574 - val_mae: 0.1354 - val_rmse: 0.2174 - val_smape: 0.3641

Epoch 40/128

240/240 - 4s - 18ms/step - ia: 0.8870 - loss: 0.0723 - mae: 0.1647 - rmse: 0.2626 - smape: 0.4081 - val_ia: 0.8725 - val_loss: 0.0560 - val_mae: 0.1314 - val_rmse: 0.2151 - val_smape: 0.3559

Epoch 41/128

240/240 - 6s - 25ms/step - ia: 0.8880 - loss: 0.0716 - mae: 0.1634 - rmse: 0.2612 - smape: 0.4058 - val_ia: 0.8655 - val_loss: 0.0563 - val_mae: 0.1359 - val_rmse: 0.2161 - val_smape: 0.3606

Epoch 42/128

240/240 - 5s - 20ms/step - ia: 0.8882 - loss: 0.0712 - mae: 0.1632 - rmse: 0.2594 - smape: 0.4043 - val_ia: 0.8610 - val_loss: 0.0568 - val_mae: 0.1387 - val_rmse: 0.2180 - val_smape: 0.3656

Epoch 43/128

240/240 - 5s - 19ms/step - ia: 0.8877 - loss: 0.0721 - mae: 0.1637 - rmse: 0.2621 - smape: 0.4051 - val_ia: 0.8694 - val_loss: 0.0561 - val_mae: 0.1333 - val_rmse: 0.2154 - val_smape: 0.3566

Epoch 44/128

240/240 - 5s - 19ms/step - ia: 0.8883 - loss: 0.0708 - mae: 0.1629 - rmse: 0.2596 - smape: 0.4046 - val_ia: 0.8664 - val_loss: 0.0564 - val_mae: 0.1357 - val_rmse: 0.2163 - val_smape: 0.3599

Epoch 45/128

240/240 - 5s - 21ms/step - ia: 0.8889 - loss: 0.0713 - mae: 0.1621 - rmse: 0.2600 - smape: 0.4020 - val_ia: 0.8664 - val_loss: 0.0563 - val_mae: 0.1356 - val_rmse: 0.2158 - val_smape: 0.3597

Epoch 46/128

240/240 - 4s - 17ms/step - ia: 0.8895 - loss: 0.0703 - mae: 0.1611 - rmse: 0.2582 - smape: 0.4028 - val_ia: 0.8710 - val_loss: 0.0556 - val_mae: 0.1319 - val_rmse: 0.2144 - val_smape: 0.3547

Epoch 47/128

240/240 - 7s - 30ms/step - ia: 0.8889 - loss: 0.0704 - mae: 0.1620 - rmse: 0.2587 - smape: 0.4010 - val_ia: 0.8641 - val_loss: 0.0564 - val_mae: 0.1369 - val_rmse: 0.2170 - val_smape: 0.3626

Epoch 48/128

240/240 - 10s - 43ms/step - ia: 0.8891 - loss: 0.0703 - mae: 0.1621 - rmse: 0.2587 - smape: 0.4043 - val_ia: 0.8685 - val_loss: 0.0555 - val_mae: 0.1334 - val_rmse: 0.2145 - val_smape: 0.3568

Epoch 49/128

240/240 - 9s - 39ms/step - ia: 0.8896 - loss: 0.0707 - mae: 0.1613 - rmse: 0.2584 - smape: 0.4006 - val_ia: 0.8718 - val_loss: 0.0554 - val_mae: 0.1313 - val_rmse: 0.2139 - val_smape: 0.3544

Epoch 50/128

240/240 - 5s - 20ms/step - ia: 0.8898 - loss: 0.0700 - mae: 0.1610 - rmse: 0.2575 - smape: 0.4010 - val_ia: 0.8658 - val_loss: 0.0562 - val_mae: 0.1360 - val_rmse: 0.2159 - val_smape: 0.3594

Epoch 51/128

240/240 - 4s - 19ms/step - ia: 0.8908 - loss: 0.0687 - mae: 0.1594 - rmse: 0.2565 - smape: 0.3954 - val_ia: 0.8675 - val_loss: 0.0557 - val_mae: 0.1341 - val_rmse: 0.2152 - val_smape: 0.3582

Epoch 52/128

240/240 - 5s - 22ms/step - ia: 0.8909 - loss: 0.0700 - mae: 0.1595 - rmse: 0.2580 - smape: 0.3955 - val_ia: 0.8670 - val_loss: 0.0556 - val_mae: 0.1346 - val_rmse: 0.2150 - val_smape: 0.3584

Epoch 53/128

240/240 - 5s - 19ms/step - ia: 0.8909 - loss: 0.0696 - mae: 0.1594 - rmse: 0.2565 - smape: 0.3976 - val_ia: 0.8702 - val_loss: 0.0560 - val_mae: 0.1332 - val_rmse: 0.2146 - val_smape: 0.3547

Epoch 54/128

240/240 - 4s - 19ms/step - ia: 0.8905 - loss: 0.0703 - mae: 0.1598 - rmse: 0.2582 - smape: 0.3966 - val_ia: 0.8673 - val_loss: 0.0558 - val_mae: 0.1347 - val_rmse: 0.2152 - val_smape: 0.3579

Epoch 55/128

240/240 - 5s - 22ms/step - ia: 0.8901 - loss: 0.0690 - mae: 0.1600 - rmse: 0.2566 - smape: 0.3977 - val_ia: 0.8735 - val_loss: 0.0554 - val_mae: 0.1308 - val_rmse: 0.2135 - val_smape: 0.3520

Epoch 56/128

240/240 - 5s - 22ms/step - ia: 0.8911 - loss: 0.0698 - mae: 0.1593 - rmse: 0.2567 - smape: 0.3954 - val_ia: 0.8724 - val_loss: 0.0551 - val_mae: 0.1309 - val_rmse: 0.2132 - val_smape: 0.3528

Epoch 57/128

240/240 - 4s - 17ms/step - ia: 0.8908 - loss: 0.0688 - mae: 0.1593 - rmse: 0.2560 - smape: 0.3974 - val_ia: 0.8698 - val_loss: 0.0553 - val_mae: 0.1328 - val_rmse: 0.2141 - val_smape: 0.3553

Epoch 58/128

240/240 - 4s - 16ms/step - ia: 0.8914 - loss: 0.0688 - mae: 0.1581 - rmse: 0.2557 - smape: 0.3917 - val_ia: 0.8718 - val_loss: 0.0560 - val_mae: 0.1326 - val_rmse: 0.2146 - val_smape: 0.3565

Epoch 59/128

240/240 - 3s - 14ms/step - ia: 0.8920 - loss: 0.0688 - mae: 0.1577 - rmse: 0.2548 - smape: 0.3936 - val_ia: 0.8730 - val_loss: 0.0550 - val_mae: 0.1306 - val_rmse: 0.2130 - val_smape: 0.3522

Epoch 60/128

240/240 - 4s - 15ms/step - ia: 0.8917 - loss: 0.0691 - mae: 0.1580 - rmse: 0.2561 - smape: 0.3938 - val_ia: 0.8671 - val_loss: 0.0553 - val_mae: 0.1342 - val_rmse: 0.2146 - val_smape: 0.3574

Epoch 61/128

240/240 - 6s - 25ms/step - ia: 0.8917 - loss: 0.0688 - mae: 0.1579 - rmse: 0.2547 - smape: 0.3915 - val_ia: 0.8695 - val_loss: 0.0560 - val_mae: 0.1338 - val_rmse: 0.2148 - val_smape: 0.3551

Epoch 62/128

240/240 - 5s - 19ms/step - ia: 0.8925 - loss: 0.0688 - mae: 0.1569 - rmse: 0.2563 - smape: 0.3899 - val_ia: 0.8732 - val_loss: 0.0550 - val_mae: 0.1304 - val_rmse: 0.2134 - val_smape: 0.3521

Epoch 63/128

240/240 - 5s - 21ms/step - ia: 0.8919 - loss: 0.0696 - mae: 0.1578 - rmse: 0.2567 - smape: 0.3903 - val_ia: 0.8743 - val_loss: 0.0552 - val_mae: 0.1302 - val_rmse: 0.2132 - val_smape: 0.3508

Epoch 64/128

240/240 - 5s - 21ms/step - ia: 0.8926 - loss: 0.0682 - mae: 0.1568 - rmse: 0.2539 - smape: 0.3908 - val_ia: 0.8630 - val_loss: 0.0561 - val_mae: 0.1380 - val_rmse: 0.2164 - val_smape: 0.3638

Epoch 65/128

240/240 - 5s - 19ms/step - ia: 0.8925 - loss: 0.0689 - mae: 0.1567 - rmse: 0.2561 - smape: 0.3907 - val_ia: 0.8733 - val_loss: 0.0549 - val_mae: 0.1307 - val_rmse: 0.2125 - val_smape: 0.3517

Epoch 66/128

240/240 - 4s - 17ms/step - ia: 0.8931 - loss: 0.0678 - mae: 0.1562 - rmse: 0.2539 - smape: 0.3882 - val_ia: 0.8708 - val_loss: 0.0552 - val_mae: 0.1326 - val_rmse: 0.2136 - val_smape: 0.3538

Epoch 67/128

240/240 - 6s - 26ms/step - ia: 0.8929 - loss: 0.0681 - mae: 0.1564 - rmse: 0.2539 - smape: 0.3904 - val_ia: 0.8716 - val_loss: 0.0550 - val_mae: 0.1316 - val_rmse: 0.2132 - val_smape: 0.3524

Epoch 68/128

240/240 - 6s - 27ms/step - ia: 0.8924 - loss: 0.0683 - mae: 0.1570 - rmse: 0.2547 - smape: 0.3909 - val_ia: 0.8702 - val_loss: 0.0548 - val_mae: 0.1323 - val_rmse: 0.2136 - val_smape: 0.3556

Epoch 69/128

240/240 - 9s - 37ms/step - ia: 0.8931 - loss: 0.0681 - mae: 0.1561 - rmse: 0.2537 - smape: 0.3869 - val_ia: 0.8638 - val_loss: 0.0557 - val_mae: 0.1371 - val_rmse: 0.2154 - val_smape: 0.3603

Epoch 70/128

240/240 - 5s - 19ms/step - ia: 0.8930 - loss: 0.0676 - mae: 0.1558 - rmse: 0.2537 - smape: 0.3872 - val_ia: 0.8660 - val_loss: 0.0551 - val_mae: 0.1349 - val_rmse: 0.2144 - val_smape: 0.3594

Epoch 71/128

240/240 - 5s - 23ms/step - ia: 0.8930 - loss: 0.0678 - mae: 0.1564 - rmse: 0.2539 - smape: 0.3892 - val_ia: 0.8674 - val_loss: 0.0550 - val_mae: 0.1342 - val_rmse: 0.2139 - val_smape: 0.3567

Epoch 72/128

240/240 - 5s - 22ms/step - ia: 0.8934 - loss: 0.0676 - mae: 0.1556 - rmse: 0.2536 - smape: 0.3878 - val_ia: 0.8729 - val_loss: 0.0544 - val_mae: 0.1304 - val_rmse: 0.2123 - val_smape: 0.3517

Epoch 73/128

240/240 - 4s - 19ms/step - ia: 0.8937 - loss: 0.0675 - mae: 0.1552 - rmse: 0.2530 - smape: 0.3862 - val_ia: 0.8713 - val_loss: 0.0546 - val_mae: 0.1313 - val_rmse: 0.2127 - val_smape: 0.3524

Epoch 74/128

240/240 - 5s - 22ms/step - ia: 0.8943 - loss: 0.0669 - mae: 0.1544 - rmse: 0.2521 - smape: 0.3871 - val_ia: 0.8743 - val_loss: 0.0548 - val_mae: 0.1302 - val_rmse: 0.2123 - val_smape: 0.3504

Epoch 75/128

240/240 - 4s - 19ms/step - ia: 0.8939 - loss: 0.0669 - mae: 0.1550 - rmse: 0.2518 - smape: 0.3863 - val_ia: 0.8714 - val_loss: 0.0548 - val_mae: 0.1317 - val_rmse: 0.2127 - val_smape: 0.3521

Epoch 76/128

240/240 - 5s - 19ms/step - ia: 0.8941 - loss: 0.0670 - mae: 0.1548 - rmse: 0.2509 - smape: 0.3856 - val_ia: 0.8756 - val_loss: 0.0542 - val_mae: 0.1286 - val_rmse: 0.2112 - val_smape: 0.3482

Epoch 77/128

240/240 - 5s - 21ms/step - ia: 0.8939 - loss: 0.0676 - mae: 0.1550 - rmse: 0.2534 - smape: 0.3849 - val_ia: 0.8674 - val_loss: 0.0554 - val_mae: 0.1345 - val_rmse: 0.2153 - val_smape: 0.3611

Epoch 78/128

240/240 - 5s - 21ms/step - ia: 0.8933 - loss: 0.0678 - mae: 0.1555 - rmse: 0.2537 - smape: 0.3879 - val_ia: 0.8733 - val_loss: 0.0554 - val_mae: 0.1315 - val_rmse: 0.2131 - val_smape: 0.3505

Epoch 79/128

240/240 - 5s - 20ms/step - ia: 0.8938 - loss: 0.0674 - mae: 0.1552 - rmse: 0.2528 - smape: 0.3869 - val_ia: 0.8762 - val_loss: 0.0543 - val_mae: 0.1282 - val_rmse: 0.2119 - val_smape: 0.3473

Epoch 80/128

240/240 - 5s - 22ms/step - ia: 0.8941 - loss: 0.0678 - mae: 0.1548 - rmse: 0.2537 - smape: 0.3863 - val_ia: 0.8744 - val_loss: 0.0544 - val_mae: 0.1295 - val_rmse: 0.2125 - val_smape: 0.3504

Epoch 81/128

240/240 - 5s - 20ms/step - ia: 0.8945 - loss: 0.0667 - mae: 0.1544 - rmse: 0.2507 - smape: 0.3865 - val_ia: 0.8738 - val_loss: 0.0542 - val_mae: 0.1298 - val_rmse: 0.2116 - val_smape: 0.3498

Epoch 82/128

240/240 - 5s - 20ms/step - ia: 0.8947 - loss: 0.0670 - mae: 0.1538 - rmse: 0.2524 - smape: 0.3869 - val_ia: 0.8748 - val_loss: 0.0541 - val_mae: 0.1293 - val_rmse: 0.2114 - val_smape: 0.3488

Epoch 83/128

240/240 - 5s - 20ms/step - ia: 0.8949 - loss: 0.0668 - mae: 0.1533 - rmse: 0.2510 - smape: 0.3827 - val_ia: 0.8730 - val_loss: 0.0543 - val_mae: 0.1307 - val_rmse: 0.2123 - val_smape: 0.3521

Epoch 84/128

240/240 - 5s - 21ms/step - ia: 0.8943 - loss: 0.0672 - mae: 0.1544 - rmse: 0.2526 - smape: 0.3849 - val_ia: 0.8733 - val_loss: 0.0542 - val_mae: 0.1302 - val_rmse: 0.2119 - val_smape: 0.3506

Epoch 85/128

240/240 - 3s - 14ms/step - ia: 0.8948 - loss: 0.0666 - mae: 0.1535 - rmse: 0.2508 - smape: 0.3845 - val_ia: 0.8686 - val_loss: 0.0547 - val_mae: 0.1334 - val_rmse: 0.2137 - val_smape: 0.3577

Epoch 86/128

240/240 - 3s - 14ms/step - ia: 0.8945 - loss: 0.0674 - mae: 0.1543 - rmse: 0.2528 - smape: 0.3857 - val_ia: 0.8715 - val_loss: 0.0542 - val_mae: 0.1317 - val_rmse: 0.2120 - val_smape: 0.3525

Epoch 87/128

240/240 - 4s - 17ms/step - ia: 0.8944 - loss: 0.0673 - mae: 0.1541 - rmse: 0.2525 - smape: 0.3854 - val_ia: 0.8714 - val_loss: 0.0544 - val_mae: 0.1312 - val_rmse: 0.2128 - val_smape: 0.3537

Epoch 88/128

240/240 - 5s - 19ms/step - ia: 0.8946 - loss: 0.0670 - mae: 0.1540 - rmse: 0.2511 - smape: 0.3845 - val_ia: 0.8757 - val_loss: 0.0542 - val_mae: 0.1290 - val_rmse: 0.2114 - val_smape: 0.3481

Epoch 89/128

240/240 - 4s - 18ms/step - ia: 0.8947 - loss: 0.0670 - mae: 0.1541 - rmse: 0.2517 - smape: 0.3850 - val_ia: 0.8741 - val_loss: 0.0540 - val_mae: 0.1295 - val_rmse: 0.2114 - val_smape: 0.3492

Epoch 90/128

240/240 - 4s - 19ms/step - ia: 0.8951 - loss: 0.0660 - mae: 0.1529 - rmse: 0.2507 - smape: 0.3828 - val_ia: 0.8753 - val_loss: 0.0543 - val_mae: 0.1294 - val_rmse: 0.2114 - val_smape: 0.3478

Epoch 91/128

240/240 - 4s - 19ms/step - ia: 0.8953 - loss: 0.0658 - mae: 0.1532 - rmse: 0.2496 - smape: 0.3841 - val_ia: 0.8752 - val_loss: 0.0545 - val_mae: 0.1296 - val_rmse: 0.2118 - val_smape: 0.3482

Epoch 92/128

240/240 - 5s - 22ms/step - ia: 0.8949 - loss: 0.0666 - mae: 0.1533 - rmse: 0.2510 - smape: 0.3825 - val_ia: 0.8760 - val_loss: 0.0539 - val_mae: 0.1284 - val_rmse: 0.2109 - val_smape: 0.3474

Epoch 93/128

240/240 - 5s - 21ms/step - ia: 0.8953 - loss: 0.0662 - mae: 0.1528 - rmse: 0.2508 - smape: 0.3831 - val_ia: 0.8715 - val_loss: 0.0544 - val_mae: 0.1314 - val_rmse: 0.2124 - val_smape: 0.3532

Epoch 94/128

240/240 - 5s - 23ms/step - ia: 0.8951 - loss: 0.0664 - mae: 0.1532 - rmse: 0.2508 - smape: 0.3828 - val_ia: 0.8746 - val_loss: 0.0541 - val_mae: 0.1293 - val_rmse: 0.2115 - val_smape: 0.3487

Epoch 95/128

240/240 - 5s - 22ms/step - ia: 0.8952 - loss: 0.0666 - mae: 0.1531 - rmse: 0.2512 - smape: 0.3817 - val_ia: 0.8753 - val_loss: 0.0539 - val_mae: 0.1287 - val_rmse: 0.2111 - val_smape: 0.3480

Epoch 96/128

240/240 - 5s - 19ms/step - ia: 0.8954 - loss: 0.0658 - mae: 0.1527 - rmse: 0.2503 - smape: 0.3820 - val_ia: 0.8707 - val_loss: 0.0541 - val_mae: 0.1313 - val_rmse: 0.2120 - val_smape: 0.3529

Epoch 97/128

240/240 - 5s - 20ms/step - ia: 0.8948 - loss: 0.0663 - mae: 0.1532 - rmse: 0.2512 - smape: 0.3844 - val_ia: 0.8760 - val_loss: 0.0539 - val_mae: 0.1281 - val_rmse: 0.2113 - val_smape: 0.3474


In [22]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}