Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [4]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(43800, 6)

In [10]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 1
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43788, 12, 6)
Dimensiones de Y: (43788, 1)

In [15]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [16]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (43788, 72)

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30651, 72)
Las dimensiones de testX son:  (8801, 72)
Las dimensiones de valX son:  (4336, 72)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30651, 1)
Las dimensiones de testY son:  (8801, 1)
Las dimensiones de valY son:  (4336, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 8s - 34ms/step - ia: 0.2514 - loss: 1.7808 - mae: 1.1324 - rmse: 1.3275 - smape: 1.5555 - val_ia: 0.2529 - val_loss: 1.2191 - val_mae: 0.9412 - val_rmse: 1.0625 - val_smape: 1.5971

Epoch 2/128

240/240 - 1s - 5ms/step - ia: 0.2356 - loss: 1.2554 - mae: 0.8943 - rmse: 1.1156 - smape: 1.5463 - val_ia: 0.2596 - val_loss: 0.9917 - val_mae: 0.7842 - val_rmse: 0.9141 - val_smape: 1.7066

Epoch 3/128

240/240 - 1s - 3ms/step - ia: 0.2373 - loss: 1.1468 - mae: 0.8220 - rmse: 1.0659 - smape: 1.5157 - val_ia: 0.2582 - val_loss: 0.9502 - val_mae: 0.7394 - val_rmse: 0.8740 - val_smape: 1.8387

Epoch 4/128

240/240 - 1s - 3ms/step - ia: 0.2394 - loss: 1.1118 - mae: 0.7967 - rmse: 1.0492 - smape: 1.5070 - val_ia: 0.2631 - val_loss: 0.9311 - val_mae: 0.7243 - val_rmse: 0.8596 - val_smape: 1.8547

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.2452 - loss: 1.0660 - mae: 0.7753 - rmse: 1.0278 - smape: 1.4957 - val_ia: 0.2737 - val_loss: 0.9029 - val_mae: 0.7075 - val_rmse: 0.8422 - val_smape: 1.7586

Epoch 6/128

240/240 - 1s - 6ms/step - ia: 0.2572 - loss: 1.0212 - mae: 0.7551 - rmse: 1.0050 - smape: 1.4733 - val_ia: 0.2923 - val_loss: 0.8588 - val_mae: 0.6816 - val_rmse: 0.8154 - val_smape: 1.6053

Epoch 7/128

240/240 - 1s - 2ms/step - ia: 0.2815 - loss: 0.9744 - mae: 0.7286 - rmse: 0.9814 - smape: 1.4292 - val_ia: 0.3238 - val_loss: 0.7971 - val_mae: 0.6446 - val_rmse: 0.7772 - val_smape: 1.4164

Epoch 8/128

240/240 - 1s - 3ms/step - ia: 0.3260 - loss: 0.9055 - mae: 0.6936 - rmse: 0.9455 - smape: 1.3619 - val_ia: 0.3677 - val_loss: 0.7168 - val_mae: 0.5974 - val_rmse: 0.7277 - val_smape: 1.2186

Epoch 9/128

240/240 - 1s - 4ms/step - ia: 0.3800 - loss: 0.8417 - mae: 0.6586 - rmse: 0.9112 - smape: 1.2739 - val_ia: 0.4256 - val_loss: 0.6320 - val_mae: 0.5461 - val_rmse: 0.6742 - val_smape: 1.0435

Epoch 10/128

240/240 - 2s - 7ms/step - ia: 0.4285 - loss: 0.7805 - mae: 0.6317 - rmse: 0.8774 - smape: 1.2029 - val_ia: 0.4851 - val_loss: 0.5513 - val_mae: 0.4913 - val_rmse: 0.6188 - val_smape: 0.8835

Epoch 11/128

240/240 - 2s - 7ms/step - ia: 0.4781 - loss: 0.7234 - mae: 0.6016 - rmse: 0.8431 - smape: 1.1258 - val_ia: 0.5306 - val_loss: 0.4859 - val_mae: 0.4500 - val_rmse: 0.5754 - val_smape: 0.7825

Epoch 12/128

240/240 - 1s - 3ms/step - ia: 0.5150 - loss: 0.6810 - mae: 0.5810 - rmse: 0.8191 - smape: 1.0671 - val_ia: 0.5622 - val_loss: 0.4382 - val_mae: 0.4206 - val_rmse: 0.5434 - val_smape: 0.7222

Epoch 13/128

240/240 - 2s - 7ms/step - ia: 0.5387 - loss: 0.6448 - mae: 0.5661 - rmse: 0.7963 - smape: 1.0353 - val_ia: 0.5803 - val_loss: 0.4036 - val_mae: 0.4023 - val_rmse: 0.5217 - val_smape: 0.6895

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.5553 - loss: 0.6172 - mae: 0.5546 - rmse: 0.7784 - smape: 1.0058 - val_ia: 0.5944 - val_loss: 0.3775 - val_mae: 0.3904 - val_rmse: 0.5064 - val_smape: 0.6699

Epoch 15/128

240/240 - 1s - 6ms/step - ia: 0.5721 - loss: 0.5858 - mae: 0.5394 - rmse: 0.7599 - smape: 0.9808 - val_ia: 0.5990 - val_loss: 0.3576 - val_mae: 0.3820 - val_rmse: 0.4948 - val_smape: 0.6613

Epoch 16/128

240/240 - 1s - 5ms/step - ia: 0.5836 - loss: 0.5677 - mae: 0.5312 - rmse: 0.7477 - smape: 0.9616 - val_ia: 0.6041 - val_loss: 0.3457 - val_mae: 0.3789 - val_rmse: 0.4892 - val_smape: 0.6582

Epoch 17/128

240/240 - 1s - 3ms/step - ia: 0.5927 - loss: 0.5515 - mae: 0.5216 - rmse: 0.7360 - smape: 0.9423 - val_ia: 0.5994 - val_loss: 0.3302 - val_mae: 0.3750 - val_rmse: 0.4820 - val_smape: 0.6615

Epoch 18/128

240/240 - 1s - 3ms/step - ia: 0.6003 - loss: 0.5343 - mae: 0.5143 - rmse: 0.7243 - smape: 0.9317 - val_ia: 0.6039 - val_loss: 0.3202 - val_mae: 0.3715 - val_rmse: 0.4765 - val_smape: 0.6584

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.6061 - loss: 0.5184 - mae: 0.5093 - rmse: 0.7131 - smape: 0.9237 - val_ia: 0.6017 - val_loss: 0.3123 - val_mae: 0.3703 - val_rmse: 0.4734 - val_smape: 0.6622

Epoch 20/128

240/240 - 1s - 5ms/step - ia: 0.6091 - loss: 0.5113 - mae: 0.5055 - rmse: 0.7081 - smape: 0.9175 - val_ia: 0.5971 - val_loss: 0.3052 - val_mae: 0.3686 - val_rmse: 0.4701 - val_smape: 0.6677

Epoch 21/128

240/240 - 1s - 4ms/step - ia: 0.6154 - loss: 0.5024 - mae: 0.4999 - rmse: 0.7028 - smape: 0.9053 - val_ia: 0.5967 - val_loss: 0.2993 - val_mae: 0.3672 - val_rmse: 0.4672 - val_smape: 0.6698

Epoch 22/128

240/240 - 1s - 3ms/step - ia: 0.6169 - loss: 0.4968 - mae: 0.4985 - rmse: 0.6987 - smape: 0.9047 - val_ia: 0.6000 - val_loss: 0.2950 - val_mae: 0.3657 - val_rmse: 0.4645 - val_smape: 0.6694

Epoch 23/128

240/240 - 1s - 3ms/step - ia: 0.6238 - loss: 0.4811 - mae: 0.4905 - rmse: 0.6864 - smape: 0.8949 - val_ia: 0.6012 - val_loss: 0.2896 - val_mae: 0.3638 - val_rmse: 0.4615 - val_smape: 0.6691

Epoch 24/128

240/240 - 1s - 3ms/step - ia: 0.6225 - loss: 0.4823 - mae: 0.4912 - rmse: 0.6877 - smape: 0.8920 - val_ia: 0.5945 - val_loss: 0.2845 - val_mae: 0.3637 - val_rmse: 0.4602 - val_smape: 0.6737

Epoch 25/128

240/240 - 1s - 3ms/step - ia: 0.6285 - loss: 0.4705 - mae: 0.4857 - rmse: 0.6798 - smape: 0.8818 - val_ia: 0.5996 - val_loss: 0.2807 - val_mae: 0.3608 - val_rmse: 0.4568 - val_smape: 0.6681

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.6301 - loss: 0.4658 - mae: 0.4849 - rmse: 0.6759 - smape: 0.8776 - val_ia: 0.6042 - val_loss: 0.2770 - val_mae: 0.3585 - val_rmse: 0.4538 - val_smape: 0.6674

Epoch 27/128

240/240 - 1s - 4ms/step - ia: 0.6325 - loss: 0.4621 - mae: 0.4814 - rmse: 0.6733 - smape: 0.8756 - val_ia: 0.6021 - val_loss: 0.2730 - val_mae: 0.3576 - val_rmse: 0.4520 - val_smape: 0.6708

Epoch 28/128

240/240 - 2s - 7ms/step - ia: 0.6307 - loss: 0.4646 - mae: 0.4828 - rmse: 0.6754 - smape: 0.8795 - val_ia: 0.6048 - val_loss: 0.2685 - val_mae: 0.3555 - val_rmse: 0.4492 - val_smape: 0.6679

Epoch 29/128

240/240 - 1s - 3ms/step - ia: 0.6387 - loss: 0.4537 - mae: 0.4759 - rmse: 0.6672 - smape: 0.8645 - val_ia: 0.6012 - val_loss: 0.2659 - val_mae: 0.3549 - val_rmse: 0.4480 - val_smape: 0.6711

Epoch 30/128

240/240 - 1s - 4ms/step - ia: 0.6412 - loss: 0.4456 - mae: 0.4729 - rmse: 0.6608 - smape: 0.8583 - val_ia: 0.6089 - val_loss: 0.2608 - val_mae: 0.3511 - val_rmse: 0.4437 - val_smape: 0.6646

Epoch 31/128

240/240 - 1s - 3ms/step - ia: 0.6413 - loss: 0.4472 - mae: 0.4728 - rmse: 0.6622 - smape: 0.8587 - val_ia: 0.6039 - val_loss: 0.2585 - val_mae: 0.3508 - val_rmse: 0.4426 - val_smape: 0.6688

Epoch 32/128

240/240 - 1s - 2ms/step - ia: 0.6396 - loss: 0.4482 - mae: 0.4739 - rmse: 0.6634 - smape: 0.8612 - val_ia: 0.6059 - val_loss: 0.2570 - val_mae: 0.3492 - val_rmse: 0.4414 - val_smape: 0.6664

Epoch 33/128

240/240 - 1s - 2ms/step - ia: 0.6459 - loss: 0.4359 - mae: 0.4669 - rmse: 0.6540 - smape: 0.8522 - val_ia: 0.6117 - val_loss: 0.2533 - val_mae: 0.3456 - val_rmse: 0.4376 - val_smape: 0.6608

Epoch 34/128

240/240 - 1s - 3ms/step - ia: 0.6476 - loss: 0.4327 - mae: 0.4656 - rmse: 0.6508 - smape: 0.8501 - val_ia: 0.6174 - val_loss: 0.2492 - val_mae: 0.3423 - val_rmse: 0.4335 - val_smape: 0.6562

Epoch 35/128

240/240 - 1s - 3ms/step - ia: 0.6479 - loss: 0.4305 - mae: 0.4645 - rmse: 0.6495 - smape: 0.8504 - val_ia: 0.6185 - val_loss: 0.2460 - val_mae: 0.3403 - val_rmse: 0.4313 - val_smape: 0.6544

Epoch 36/128

240/240 - 1s - 3ms/step - ia: 0.6508 - loss: 0.4312 - mae: 0.4629 - rmse: 0.6497 - smape: 0.8442 - val_ia: 0.6221 - val_loss: 0.2457 - val_mae: 0.3389 - val_rmse: 0.4299 - val_smape: 0.6535

Epoch 37/128

240/240 - 1s - 2ms/step - ia: 0.6524 - loss: 0.4273 - mae: 0.4607 - rmse: 0.6468 - smape: 0.8410 - val_ia: 0.6208 - val_loss: 0.2443 - val_mae: 0.3382 - val_rmse: 0.4289 - val_smape: 0.6550

Epoch 38/128

240/240 - 1s - 2ms/step - ia: 0.6548 - loss: 0.4215 - mae: 0.4568 - rmse: 0.6427 - smape: 0.8373 - val_ia: 0.6205 - val_loss: 0.2389 - val_mae: 0.3356 - val_rmse: 0.4252 - val_smape: 0.6539

Epoch 39/128

240/240 - 1s - 2ms/step - ia: 0.6554 - loss: 0.4206 - mae: 0.4567 - rmse: 0.6423 - smape: 0.8374 - val_ia: 0.6235 - val_loss: 0.2382 - val_mae: 0.3336 - val_rmse: 0.4236 - val_smape: 0.6531

Epoch 40/128

240/240 - 1s - 4ms/step - ia: 0.6586 - loss: 0.4115 - mae: 0.4545 - rmse: 0.6350 - smape: 0.8354 - val_ia: 0.6255 - val_loss: 0.2346 - val_mae: 0.3316 - val_rmse: 0.4209 - val_smape: 0.6517

Epoch 41/128

240/240 - 1s - 6ms/step - ia: 0.6593 - loss: 0.4106 - mae: 0.4534 - rmse: 0.6343 - smape: 0.8381 - val_ia: 0.6340 - val_loss: 0.2323 - val_mae: 0.3275 - val_rmse: 0.4170 - val_smape: 0.6438

Epoch 42/128

240/240 - 2s - 6ms/step - ia: 0.6620 - loss: 0.4065 - mae: 0.4503 - rmse: 0.6309 - smape: 0.8282 - val_ia: 0.6294 - val_loss: 0.2286 - val_mae: 0.3271 - val_rmse: 0.4156 - val_smape: 0.6475

Epoch 43/128

240/240 - 1s - 5ms/step - ia: 0.6625 - loss: 0.4032 - mae: 0.4483 - rmse: 0.6291 - smape: 0.8316 - val_ia: 0.6360 - val_loss: 0.2252 - val_mae: 0.3235 - val_rmse: 0.4120 - val_smape: 0.6389

Epoch 44/128

240/240 - 1s - 5ms/step - ia: 0.6651 - loss: 0.4033 - mae: 0.4474 - rmse: 0.6292 - smape: 0.8273 - val_ia: 0.6344 - val_loss: 0.2242 - val_mae: 0.3229 - val_rmse: 0.4111 - val_smape: 0.6420

Epoch 45/128

240/240 - 1s - 4ms/step - ia: 0.6673 - loss: 0.4065 - mae: 0.4439 - rmse: 0.6306 - smape: 0.8233 - val_ia: 0.6417 - val_loss: 0.2227 - val_mae: 0.3193 - val_rmse: 0.4078 - val_smape: 0.6363

Epoch 46/128

240/240 - 1s - 3ms/step - ia: 0.6658 - loss: 0.4021 - mae: 0.4445 - rmse: 0.6276 - smape: 0.8261 - val_ia: 0.6438 - val_loss: 0.2180 - val_mae: 0.3167 - val_rmse: 0.4044 - val_smape: 0.6343

Epoch 47/128

240/240 - 1s - 6ms/step - ia: 0.6701 - loss: 0.3946 - mae: 0.4406 - rmse: 0.6212 - smape: 0.8235 - val_ia: 0.6495 - val_loss: 0.2137 - val_mae: 0.3130 - val_rmse: 0.4003 - val_smape: 0.6273

Epoch 48/128

240/240 - 1s - 3ms/step - ia: 0.6712 - loss: 0.3877 - mae: 0.4400 - rmse: 0.6159 - smape: 0.8206 - val_ia: 0.6517 - val_loss: 0.2134 - val_mae: 0.3118 - val_rmse: 0.3993 - val_smape: 0.6274

Epoch 49/128

240/240 - 1s - 4ms/step - ia: 0.6708 - loss: 0.3962 - mae: 0.4403 - rmse: 0.6227 - smape: 0.8218 - val_ia: 0.6510 - val_loss: 0.2118 - val_mae: 0.3107 - val_rmse: 0.3978 - val_smape: 0.6292

Epoch 50/128

240/240 - 1s - 6ms/step - ia: 0.6710 - loss: 0.3894 - mae: 0.4381 - rmse: 0.6169 - smape: 0.8232 - val_ia: 0.6606 - val_loss: 0.2065 - val_mae: 0.3051 - val_rmse: 0.3921 - val_smape: 0.6160

Epoch 51/128

240/240 - 1s - 5ms/step - ia: 0.6734 - loss: 0.3858 - mae: 0.4367 - rmse: 0.6147 - smape: 0.8215 - val_ia: 0.6589 - val_loss: 0.2073 - val_mae: 0.3056 - val_rmse: 0.3925 - val_smape: 0.6209

Epoch 52/128

240/240 - 1s - 6ms/step - ia: 0.6743 - loss: 0.3801 - mae: 0.4356 - rmse: 0.6107 - smape: 0.8188 - val_ia: 0.6536 - val_loss: 0.2075 - val_mae: 0.3069 - val_rmse: 0.3936 - val_smape: 0.6284

Epoch 53/128

240/240 - 1s - 3ms/step - ia: 0.6757 - loss: 0.3828 - mae: 0.4346 - rmse: 0.6114 - smape: 0.8180 - val_ia: 0.6610 - val_loss: 0.2033 - val_mae: 0.3023 - val_rmse: 0.3888 - val_smape: 0.6180

Epoch 54/128

240/240 - 1s - 3ms/step - ia: 0.6796 - loss: 0.3728 - mae: 0.4290 - rmse: 0.6047 - smape: 0.8126 - val_ia: 0.6706 - val_loss: 0.1990 - val_mae: 0.2973 - val_rmse: 0.3837 - val_smape: 0.6076

Epoch 55/128

240/240 - 1s - 4ms/step - ia: 0.6778 - loss: 0.3817 - mae: 0.4315 - rmse: 0.6107 - smape: 0.8134 - val_ia: 0.6698 - val_loss: 0.1967 - val_mae: 0.2958 - val_rmse: 0.3818 - val_smape: 0.6061

Epoch 56/128

240/240 - 1s - 3ms/step - ia: 0.6803 - loss: 0.3738 - mae: 0.4287 - rmse: 0.6054 - smape: 0.8109 - val_ia: 0.6706 - val_loss: 0.1946 - val_mae: 0.2941 - val_rmse: 0.3801 - val_smape: 0.6045

Epoch 57/128

240/240 - 2s - 9ms/step - ia: 0.6820 - loss: 0.3707 - mae: 0.4267 - rmse: 0.6022 - smape: 0.8105 - val_ia: 0.6753 - val_loss: 0.1939 - val_mae: 0.2924 - val_rmse: 0.3784 - val_smape: 0.6029

Epoch 58/128

240/240 - 2s - 8ms/step - ia: 0.6816 - loss: 0.3744 - mae: 0.4276 - rmse: 0.6043 - smape: 0.8113 - val_ia: 0.6746 - val_loss: 0.1920 - val_mae: 0.2915 - val_rmse: 0.3770 - val_smape: 0.6036

Epoch 59/128

240/240 - 2s - 9ms/step - ia: 0.6839 - loss: 0.3719 - mae: 0.4235 - rmse: 0.6030 - smape: 0.8062 - val_ia: 0.6796 - val_loss: 0.1899 - val_mae: 0.2882 - val_rmse: 0.3741 - val_smape: 0.5950

Epoch 60/128

240/240 - 1s - 4ms/step - ia: 0.6844 - loss: 0.3690 - mae: 0.4230 - rmse: 0.6006 - smape: 0.8039 - val_ia: 0.6846 - val_loss: 0.1878 - val_mae: 0.2857 - val_rmse: 0.3714 - val_smape: 0.5919

Epoch 61/128

240/240 - 1s - 4ms/step - ia: 0.6812 - loss: 0.3769 - mae: 0.4273 - rmse: 0.6076 - smape: 0.8117 - val_ia: 0.6826 - val_loss: 0.1883 - val_mae: 0.2861 - val_rmse: 0.3716 - val_smape: 0.5968

Epoch 62/128

240/240 - 1s - 3ms/step - ia: 0.6825 - loss: 0.3692 - mae: 0.4248 - rmse: 0.6002 - smape: 0.8136 - val_ia: 0.6837 - val_loss: 0.1852 - val_mae: 0.2841 - val_rmse: 0.3693 - val_smape: 0.5923

Epoch 63/128

240/240 - 1s - 5ms/step - ia: 0.6822 - loss: 0.3713 - mae: 0.4244 - rmse: 0.6033 - smape: 0.8094 - val_ia: 0.6855 - val_loss: 0.1842 - val_mae: 0.2828 - val_rmse: 0.3680 - val_smape: 0.5899

Epoch 64/128

240/240 - 1s - 5ms/step - ia: 0.6858 - loss: 0.3665 - mae: 0.4206 - rmse: 0.5993 - smape: 0.8031 - val_ia: 0.6874 - val_loss: 0.1827 - val_mae: 0.2811 - val_rmse: 0.3664 - val_smape: 0.5873

Epoch 65/128

240/240 - 1s - 4ms/step - ia: 0.6840 - loss: 0.3718 - mae: 0.4227 - rmse: 0.6031 - smape: 0.8038 - val_ia: 0.6912 - val_loss: 0.1808 - val_mae: 0.2792 - val_rmse: 0.3642 - val_smape: 0.5852

Epoch 66/128

240/240 - 1s - 4ms/step - ia: 0.6876 - loss: 0.3624 - mae: 0.4201 - rmse: 0.5955 - smape: 0.8031 - val_ia: 0.6917 - val_loss: 0.1804 - val_mae: 0.2786 - val_rmse: 0.3634 - val_smape: 0.5859

Epoch 67/128

240/240 - 1s - 3ms/step - ia: 0.6887 - loss: 0.3633 - mae: 0.4178 - rmse: 0.5962 - smape: 0.7995 - val_ia: 0.6916 - val_loss: 0.1774 - val_mae: 0.2772 - val_rmse: 0.3614 - val_smape: 0.5852

Epoch 68/128

240/240 - 1s - 4ms/step - ia: 0.6900 - loss: 0.3583 - mae: 0.4158 - rmse: 0.5932 - smape: 0.8006 - val_ia: 0.6967 - val_loss: 0.1754 - val_mae: 0.2741 - val_rmse: 0.3585 - val_smape: 0.5785

Epoch 69/128

240/240 - 1s - 4ms/step - ia: 0.6897 - loss: 0.3622 - mae: 0.4170 - rmse: 0.5950 - smape: 0.7994 - val_ia: 0.6952 - val_loss: 0.1749 - val_mae: 0.2745 - val_rmse: 0.3586 - val_smape: 0.5809

Epoch 70/128

240/240 - 1s - 2ms/step - ia: 0.6895 - loss: 0.3596 - mae: 0.4160 - rmse: 0.5925 - smape: 0.7988 - val_ia: 0.6973 - val_loss: 0.1731 - val_mae: 0.2724 - val_rmse: 0.3566 - val_smape: 0.5779

Epoch 71/128

240/240 - 1s - 3ms/step - ia: 0.6907 - loss: 0.3576 - mae: 0.4157 - rmse: 0.5923 - smape: 0.7971 - val_ia: 0.7014 - val_loss: 0.1710 - val_mae: 0.2699 - val_rmse: 0.3540 - val_smape: 0.5719

Epoch 72/128

240/240 - 1s - 3ms/step - ia: 0.6910 - loss: 0.3567 - mae: 0.4154 - rmse: 0.5902 - smape: 0.8002 - val_ia: 0.7004 - val_loss: 0.1695 - val_mae: 0.2698 - val_rmse: 0.3534 - val_smape: 0.5740

Epoch 73/128

240/240 - 1s - 3ms/step - ia: 0.6958 - loss: 0.3469 - mae: 0.4099 - rmse: 0.5821 - smape: 0.7906 - val_ia: 0.7035 - val_loss: 0.1683 - val_mae: 0.2681 - val_rmse: 0.3517 - val_smape: 0.5711

Epoch 74/128

240/240 - 1s - 5ms/step - ia: 0.6947 - loss: 0.3524 - mae: 0.4102 - rmse: 0.5862 - smape: 0.7919 - val_ia: 0.7066 - val_loss: 0.1677 - val_mae: 0.2662 - val_rmse: 0.3501 - val_smape: 0.5662

Epoch 75/128

240/240 - 1s - 4ms/step - ia: 0.6941 - loss: 0.3503 - mae: 0.4111 - rmse: 0.5851 - smape: 0.7964 - val_ia: 0.7069 - val_loss: 0.1660 - val_mae: 0.2646 - val_rmse: 0.3483 - val_smape: 0.5647

Epoch 76/128

240/240 - 1s - 4ms/step - ia: 0.6994 - loss: 0.3433 - mae: 0.4050 - rmse: 0.5793 - smape: 0.7869 - val_ia: 0.7122 - val_loss: 0.1646 - val_mae: 0.2622 - val_rmse: 0.3459 - val_smape: 0.5603

Epoch 77/128

240/240 - 1s - 3ms/step - ia: 0.6947 - loss: 0.3555 - mae: 0.4101 - rmse: 0.5896 - smape: 0.7917 - val_ia: 0.7120 - val_loss: 0.1660 - val_mae: 0.2636 - val_rmse: 0.3473 - val_smape: 0.5636

Epoch 78/128

240/240 - 2s - 6ms/step - ia: 0.6940 - loss: 0.3549 - mae: 0.4110 - rmse: 0.5890 - smape: 0.7948 - val_ia: 0.7119 - val_loss: 0.1633 - val_mae: 0.2612 - val_rmse: 0.3449 - val_smape: 0.5593

Epoch 79/128

240/240 - 1s - 6ms/step - ia: 0.7005 - loss: 0.3415 - mae: 0.4036 - rmse: 0.5769 - smape: 0.7814 - val_ia: 0.7180 - val_loss: 0.1619 - val_mae: 0.2585 - val_rmse: 0.3422 - val_smape: 0.5527

Epoch 80/128

240/240 - 1s - 3ms/step - ia: 0.6974 - loss: 0.3485 - mae: 0.4068 - rmse: 0.5825 - smape: 0.7901 - val_ia: 0.7191 - val_loss: 0.1596 - val_mae: 0.2567 - val_rmse: 0.3402 - val_smape: 0.5515

Epoch 81/128

240/240 - 1s - 3ms/step - ia: 0.6978 - loss: 0.3464 - mae: 0.4062 - rmse: 0.5825 - smape: 0.7881 - val_ia: 0.7192 - val_loss: 0.1584 - val_mae: 0.2560 - val_rmse: 0.3393 - val_smape: 0.5516

Epoch 82/128

240/240 - 1s - 3ms/step - ia: 0.7023 - loss: 0.3365 - mae: 0.4013 - rmse: 0.5732 - smape: 0.7821 - val_ia: 0.7171 - val_loss: 0.1572 - val_mae: 0.2562 - val_rmse: 0.3390 - val_smape: 0.5555

Epoch 83/128

240/240 - 1s - 3ms/step - ia: 0.7010 - loss: 0.3439 - mae: 0.4031 - rmse: 0.5803 - smape: 0.7857 - val_ia: 0.7243 - val_loss: 0.1561 - val_mae: 0.2534 - val_rmse: 0.3366 - val_smape: 0.5453

Epoch 84/128

240/240 - 1s - 4ms/step - ia: 0.7010 - loss: 0.3371 - mae: 0.4027 - rmse: 0.5746 - smape: 0.7845 - val_ia: 0.7226 - val_loss: 0.1542 - val_mae: 0.2529 - val_rmse: 0.3355 - val_smape: 0.5481

Epoch 85/128

240/240 - 1s - 3ms/step - ia: 0.7002 - loss: 0.3420 - mae: 0.4035 - rmse: 0.5770 - smape: 0.7873 - val_ia: 0.7238 - val_loss: 0.1532 - val_mae: 0.2518 - val_rmse: 0.3345 - val_smape: 0.5430

Epoch 86/128

240/240 - 1s - 3ms/step - ia: 0.7022 - loss: 0.3377 - mae: 0.4011 - rmse: 0.5737 - smape: 0.7802 - val_ia: 0.7219 - val_loss: 0.1519 - val_mae: 0.2519 - val_rmse: 0.3341 - val_smape: 0.5489

Epoch 87/128

240/240 - 1s - 3ms/step - ia: 0.7038 - loss: 0.3351 - mae: 0.3998 - rmse: 0.5720 - smape: 0.7826 - val_ia: 0.7221 - val_loss: 0.1519 - val_mae: 0.2516 - val_rmse: 0.3339 - val_smape: 0.5464

Epoch 88/128

240/240 - 1s - 3ms/step - ia: 0.7042 - loss: 0.3365 - mae: 0.3996 - rmse: 0.5726 - smape: 0.7778 - val_ia: 0.7260 - val_loss: 0.1518 - val_mae: 0.2504 - val_rmse: 0.3328 - val_smape: 0.5442

Epoch 89/128

240/240 - 2s - 6ms/step - ia: 0.7069 - loss: 0.3285 - mae: 0.3958 - rmse: 0.5658 - smape: 0.7744 - val_ia: 0.7285 - val_loss: 0.1497 - val_mae: 0.2484 - val_rmse: 0.3305 - val_smape: 0.5413

Epoch 90/128

240/240 - 1s - 4ms/step - ia: 0.7035 - loss: 0.3351 - mae: 0.4000 - rmse: 0.5722 - smape: 0.7795 - val_ia: 0.7240 - val_loss: 0.1502 - val_mae: 0.2506 - val_rmse: 0.3323 - val_smape: 0.5468

Epoch 91/128

240/240 - 2s - 7ms/step - ia: 0.7031 - loss: 0.3363 - mae: 0.3990 - rmse: 0.5735 - smape: 0.7798 - val_ia: 0.7329 - val_loss: 0.1484 - val_mae: 0.2464 - val_rmse: 0.3286 - val_smape: 0.5343

Epoch 92/128

240/240 - 1s - 3ms/step - ia: 0.7045 - loss: 0.3384 - mae: 0.3990 - rmse: 0.5758 - smape: 0.7777 - val_ia: 0.7259 - val_loss: 0.1490 - val_mae: 0.2487 - val_rmse: 0.3306 - val_smape: 0.5408

Epoch 93/128

240/240 - 1s - 5ms/step - ia: 0.7066 - loss: 0.3292 - mae: 0.3954 - rmse: 0.5674 - smape: 0.7756 - val_ia: 0.7299 - val_loss: 0.1478 - val_mae: 0.2469 - val_rmse: 0.3288 - val_smape: 0.5381

Epoch 94/128

240/240 - 1s - 3ms/step - ia: 0.7102 - loss: 0.3270 - mae: 0.3929 - rmse: 0.5651 - smape: 0.7691 - val_ia: 0.7303 - val_loss: 0.1476 - val_mae: 0.2465 - val_rmse: 0.3284 - val_smape: 0.5366

Epoch 95/128

240/240 - 1s - 3ms/step - ia: 0.7051 - loss: 0.3317 - mae: 0.3965 - rmse: 0.5687 - smape: 0.7786 - val_ia: 0.7362 - val_loss: 0.1431 - val_mae: 0.2419 - val_rmse: 0.3237 - val_smape: 0.5274

Epoch 96/128

240/240 - 1s - 3ms/step - ia: 0.7086 - loss: 0.3313 - mae: 0.3947 - rmse: 0.5691 - smape: 0.7701 - val_ia: 0.7317 - val_loss: 0.1452 - val_mae: 0.2445 - val_rmse: 0.3261 - val_smape: 0.5342

Epoch 97/128

240/240 - 1s - 2ms/step - ia: 0.7069 - loss: 0.3291 - mae: 0.3949 - rmse: 0.5677 - smape: 0.7743 - val_ia: 0.7370 - val_loss: 0.1433 - val_mae: 0.2418 - val_rmse: 0.3234 - val_smape: 0.5280

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 10s - 5ms/step - ia: 0.8497 - loss: 0.1011 - mae: 0.2026 - rmse: 0.2834 - smape: 0.4712 - val_ia: 0.6375 - val_loss: 0.0642 - val_mae: 0.1557 - val_rmse: 0.2101 - val_smape: 0.4016

Epoch 2/128

1916/1916 - 11s - 6ms/step - ia: 0.8728 - loss: 0.0772 - mae: 0.1730 - rmse: 0.2491 - smape: 0.4215 - val_ia: 0.6520 - val_loss: 0.0632 - val_mae: 0.1528 - val_rmse: 0.2058 - val_smape: 0.3905

Epoch 3/128

1916/1916 - 7s - 4ms/step - ia: 0.8765 - loss: 0.0751 - mae: 0.1685 - rmse: 0.2449 - smape: 0.4096 - val_ia: 0.6509 - val_loss: 0.0624 - val_mae: 0.1487 - val_rmse: 0.2045 - val_smape: 0.3906

Epoch 4/128

1916/1916 - 11s - 6ms/step - ia: 0.8788 - loss: 0.0732 - mae: 0.1639 - rmse: 0.2408 - smape: 0.4018 - val_ia: 0.6034 - val_loss: 0.0748 - val_mae: 0.1754 - val_rmse: 0.2274 - val_smape: 0.4340

Epoch 5/128

1916/1916 - 7s - 3ms/step - ia: 0.8816 - loss: 0.0711 - mae: 0.1608 - rmse: 0.2372 - smape: 0.3948 - val_ia: 0.6465 - val_loss: 0.0676 - val_mae: 0.1573 - val_rmse: 0.2132 - val_smape: 0.3805

Epoch 6/128

1916/1916 - 8s - 4ms/step - ia: 0.8842 - loss: 0.0702 - mae: 0.1583 - rmse: 0.2354 - smape: 0.3902 - val_ia: 0.6390 - val_loss: 0.0643 - val_mae: 0.1536 - val_rmse: 0.2049 - val_smape: 0.3840

Epoch 7/128

1916/1916 - 7s - 4ms/step - ia: 0.8841 - loss: 0.0694 - mae: 0.1578 - rmse: 0.2331 - smape: 0.3899 - val_ia: 0.6389 - val_loss: 0.0656 - val_mae: 0.1577 - val_rmse: 0.2136 - val_smape: 0.4210

Epoch 8/128

1916/1916 - 7s - 4ms/step - ia: 0.8869 - loss: 0.0685 - mae: 0.1545 - rmse: 0.2302 - smape: 0.3845 - val_ia: 0.6540 - val_loss: 0.0630 - val_mae: 0.1493 - val_rmse: 0.2041 - val_smape: 0.3894

Epoch 9/128

1916/1916 - 10s - 5ms/step - ia: 0.8870 - loss: 0.0683 - mae: 0.1541 - rmse: 0.2308 - smape: 0.3829 - val_ia: 0.6668 - val_loss: 0.0621 - val_mae: 0.1458 - val_rmse: 0.2010 - val_smape: 0.3673

Epoch 10/128

1916/1916 - 10s - 5ms/step - ia: 0.8873 - loss: 0.0680 - mae: 0.1534 - rmse: 0.2303 - smape: 0.3805 - val_ia: 0.5095 - val_loss: 0.1265 - val_mae: 0.2490 - val_rmse: 0.2918 - val_smape: 0.5566

Epoch 11/128

1916/1916 - 6s - 3ms/step - ia: 0.8869 - loss: 0.0676 - mae: 0.1532 - rmse: 0.2299 - smape: 0.3824 - val_ia: 0.6871 - val_loss: 0.0585 - val_mae: 0.1356 - val_rmse: 0.1908 - val_smape: 0.3557

Epoch 12/128

1916/1916 - 7s - 3ms/step - ia: 0.8885 - loss: 0.0673 - mae: 0.1517 - rmse: 0.2280 - smape: 0.3799 - val_ia: 0.6733 - val_loss: 0.0592 - val_mae: 0.1413 - val_rmse: 0.1944 - val_smape: 0.3647

Epoch 13/128

1916/1916 - 6s - 3ms/step - ia: 0.8891 - loss: 0.0669 - mae: 0.1508 - rmse: 0.2277 - smape: 0.3757 - val_ia: 0.6254 - val_loss: 0.0702 - val_mae: 0.1652 - val_rmse: 0.2151 - val_smape: 0.4040

Epoch 14/128

1916/1916 - 12s - 6ms/step - ia: 0.8896 - loss: 0.0665 - mae: 0.1503 - rmse: 0.2270 - smape: 0.3753 - val_ia: 0.6632 - val_loss: 0.0674 - val_mae: 0.1524 - val_rmse: 0.2085 - val_smape: 0.3721

Epoch 15/128

1916/1916 - 7s - 4ms/step - ia: 0.8907 - loss: 0.0666 - mae: 0.1499 - rmse: 0.2254 - smape: 0.3765 - val_ia: 0.6760 - val_loss: 0.0578 - val_mae: 0.1389 - val_rmse: 0.1916 - val_smape: 0.3658

Epoch 16/128

1916/1916 - 11s - 6ms/step - ia: 0.8895 - loss: 0.0666 - mae: 0.1504 - rmse: 0.2266 - smape: 0.3752 - val_ia: 0.6584 - val_loss: 0.0605 - val_mae: 0.1454 - val_rmse: 0.1976 - val_smape: 0.3746

Epoch 17/128

1916/1916 - 10s - 5ms/step - ia: 0.8909 - loss: 0.0659 - mae: 0.1489 - rmse: 0.2244 - smape: 0.3734 - val_ia: 0.6713 - val_loss: 0.0584 - val_mae: 0.1408 - val_rmse: 0.1934 - val_smape: 0.3722

Epoch 18/128

1916/1916 - 8s - 4ms/step - ia: 0.8905 - loss: 0.0661 - mae: 0.1494 - rmse: 0.2251 - smape: 0.3742 - val_ia: 0.6462 - val_loss: 0.0631 - val_mae: 0.1528 - val_rmse: 0.2072 - val_smape: 0.3995

Epoch 19/128

1916/1916 - 10s - 5ms/step - ia: 0.8910 - loss: 0.0655 - mae: 0.1487 - rmse: 0.2249 - smape: 0.3731 - val_ia: 0.6559 - val_loss: 0.0596 - val_mae: 0.1461 - val_rmse: 0.1974 - val_smape: 0.3826

Epoch 20/128

1916/1916 - 10s - 5ms/step - ia: 0.8909 - loss: 0.0657 - mae: 0.1485 - rmse: 0.2245 - smape: 0.3706 - val_ia: 0.6630 - val_loss: 0.0630 - val_mae: 0.1486 - val_rmse: 0.2031 - val_smape: 0.3806

Epoch 21/128

1916/1916 - 11s - 6ms/step - ia: 0.8915 - loss: 0.0652 - mae: 0.1481 - rmse: 0.2240 - smape: 0.3717 - val_ia: 0.6906 - val_loss: 0.0573 - val_mae: 0.1334 - val_rmse: 0.1888 - val_smape: 0.3515

Epoch 22/128

1916/1916 - 11s - 6ms/step - ia: 0.8921 - loss: 0.0655 - mae: 0.1476 - rmse: 0.2243 - smape: 0.3703 - val_ia: 0.6649 - val_loss: 0.0591 - val_mae: 0.1428 - val_rmse: 0.1945 - val_smape: 0.3729

Epoch 23/128

1916/1916 - 7s - 4ms/step - ia: 0.8924 - loss: 0.0656 - mae: 0.1473 - rmse: 0.2240 - smape: 0.3699 - val_ia: 0.6718 - val_loss: 0.0585 - val_mae: 0.1408 - val_rmse: 0.1925 - val_smape: 0.3649

Epoch 24/128

1916/1916 - 10s - 5ms/step - ia: 0.8917 - loss: 0.0658 - mae: 0.1480 - rmse: 0.2248 - smape: 0.3708 - val_ia: 0.6787 - val_loss: 0.0580 - val_mae: 0.1385 - val_rmse: 0.1914 - val_smape: 0.3646

Epoch 25/128

1916/1916 - 7s - 4ms/step - ia: 0.8929 - loss: 0.0651 - mae: 0.1460 - rmse: 0.2224 - smape: 0.3673 - val_ia: 0.6923 - val_loss: 0.0570 - val_mae: 0.1330 - val_rmse: 0.1874 - val_smape: 0.3500

Epoch 26/128

1916/1916 - 7s - 3ms/step - ia: 0.8924 - loss: 0.0647 - mae: 0.1466 - rmse: 0.2229 - smape: 0.3683 - val_ia: 0.6105 - val_loss: 0.0725 - val_mae: 0.1723 - val_rmse: 0.2221 - val_smape: 0.4276

Epoch 27/128

1916/1916 - 7s - 4ms/step - ia: 0.8922 - loss: 0.0651 - mae: 0.1472 - rmse: 0.2230 - smape: 0.3701 - val_ia: 0.6784 - val_loss: 0.0575 - val_mae: 0.1368 - val_rmse: 0.1914 - val_smape: 0.3641

Epoch 28/128

1916/1916 - 7s - 4ms/step - ia: 0.8926 - loss: 0.0651 - mae: 0.1475 - rmse: 0.2238 - smape: 0.3689 - val_ia: 0.6903 - val_loss: 0.0573 - val_mae: 0.1335 - val_rmse: 0.1884 - val_smape: 0.3516

Epoch 29/128

1916/1916 - 7s - 4ms/step - ia: 0.8932 - loss: 0.0649 - mae: 0.1463 - rmse: 0.2230 - smape: 0.3671 - val_ia: 0.6762 - val_loss: 0.0576 - val_mae: 0.1370 - val_rmse: 0.1905 - val_smape: 0.3592

Epoch 30/128

1916/1916 - 7s - 4ms/step - ia: 0.8925 - loss: 0.0648 - mae: 0.1463 - rmse: 0.2224 - smape: 0.3673 - val_ia: 0.6712 - val_loss: 0.0579 - val_mae: 0.1393 - val_rmse: 0.1911 - val_smape: 0.3675

Epoch 31/128

1916/1916 - 8s - 4ms/step - ia: 0.8927 - loss: 0.0644 - mae: 0.1459 - rmse: 0.2219 - smape: 0.3672 - val_ia: 0.6787 - val_loss: 0.0596 - val_mae: 0.1389 - val_rmse: 0.1946 - val_smape: 0.3685

Epoch 32/128

1916/1916 - 7s - 4ms/step - ia: 0.8931 - loss: 0.0645 - mae: 0.1461 - rmse: 0.2223 - smape: 0.3671 - val_ia: 0.6817 - val_loss: 0.0581 - val_mae: 0.1371 - val_rmse: 0.1912 - val_smape: 0.3635

Epoch 33/128

1916/1916 - 11s - 6ms/step - ia: 0.8928 - loss: 0.0648 - mae: 0.1462 - rmse: 0.2223 - smape: 0.3672 - val_ia: 0.6783 - val_loss: 0.0582 - val_mae: 0.1395 - val_rmse: 0.1914 - val_smape: 0.3646

Epoch 34/128

1916/1916 - 8s - 4ms/step - ia: 0.8930 - loss: 0.0647 - mae: 0.1460 - rmse: 0.2226 - smape: 0.3674 - val_ia: 0.6808 - val_loss: 0.0569 - val_mae: 0.1356 - val_rmse: 0.1880 - val_smape: 0.3588

Epoch 35/128

1916/1916 - 7s - 4ms/step - ia: 0.8940 - loss: 0.0645 - mae: 0.1453 - rmse: 0.2217 - smape: 0.3647 - val_ia: 0.6916 - val_loss: 0.0575 - val_mae: 0.1330 - val_rmse: 0.1884 - val_smape: 0.3524

Epoch 36/128

1916/1916 - 7s - 4ms/step - ia: 0.8928 - loss: 0.0646 - mae: 0.1460 - rmse: 0.2229 - smape: 0.3668 - val_ia: 0.6969 - val_loss: 0.0568 - val_mae: 0.1309 - val_rmse: 0.1860 - val_smape: 0.3483

Epoch 37/128

1916/1916 - 7s - 4ms/step - ia: 0.8935 - loss: 0.0646 - mae: 0.1454 - rmse: 0.2220 - smape: 0.3652 - val_ia: 0.6470 - val_loss: 0.0628 - val_mae: 0.1522 - val_rmse: 0.2049 - val_smape: 0.3913

Epoch 38/128

1916/1916 - 7s - 4ms/step - ia: 0.8930 - loss: 0.0643 - mae: 0.1449 - rmse: 0.2213 - smape: 0.3653 - val_ia: 0.6917 - val_loss: 0.0568 - val_mae: 0.1332 - val_rmse: 0.1873 - val_smape: 0.3516

Epoch 39/128

1916/1916 - 7s - 4ms/step - ia: 0.8932 - loss: 0.0642 - mae: 0.1450 - rmse: 0.2210 - smape: 0.3665 - val_ia: 0.6739 - val_loss: 0.0573 - val_mae: 0.1378 - val_rmse: 0.1898 - val_smape: 0.3622

Epoch 40/128

1916/1916 - 10s - 5ms/step - ia: 0.8935 - loss: 0.0644 - mae: 0.1449 - rmse: 0.2222 - smape: 0.3645 - val_ia: 0.6903 - val_loss: 0.0565 - val_mae: 0.1326 - val_rmse: 0.1863 - val_smape: 0.3530

Epoch 41/128

1916/1916 - 7s - 4ms/step - ia: 0.8935 - loss: 0.0647 - mae: 0.1453 - rmse: 0.2227 - smape: 0.3647 - val_ia: 0.6949 - val_loss: 0.0562 - val_mae: 0.1314 - val_rmse: 0.1854 - val_smape: 0.3514

Epoch 42/128

1916/1916 - 10s - 5ms/step - ia: 0.8939 - loss: 0.0641 - mae: 0.1449 - rmse: 0.2208 - smape: 0.3650 - val_ia: 0.6850 - val_loss: 0.0570 - val_mae: 0.1356 - val_rmse: 0.1895 - val_smape: 0.3554

Epoch 43/128

1916/1916 - 10s - 5ms/step - ia: 0.8935 - loss: 0.0643 - mae: 0.1450 - rmse: 0.2220 - smape: 0.3654 - val_ia: 0.6791 - val_loss: 0.0602 - val_mae: 0.1395 - val_rmse: 0.1947 - val_smape: 0.3664

Epoch 44/128

1916/1916 - 10s - 5ms/step - ia: 0.8939 - loss: 0.0642 - mae: 0.1451 - rmse: 0.2222 - smape: 0.3656 - val_ia: 0.6952 - val_loss: 0.0567 - val_mae: 0.1316 - val_rmse: 0.1860 - val_smape: 0.3514

Epoch 45/128

1916/1916 - 11s - 6ms/step - ia: 0.8947 - loss: 0.0644 - mae: 0.1444 - rmse: 0.2217 - smape: 0.3628 - val_ia: 0.6893 - val_loss: 0.0562 - val_mae: 0.1327 - val_rmse: 0.1858 - val_smape: 0.3522

Epoch 46/128

1916/1916 - 6s - 3ms/step - ia: 0.8946 - loss: 0.0643 - mae: 0.1444 - rmse: 0.2216 - smape: 0.3645 - val_ia: 0.6751 - val_loss: 0.0585 - val_mae: 0.1387 - val_rmse: 0.1930 - val_smape: 0.3655

Epoch 47/128

1916/1916 - 10s - 5ms/step - ia: 0.8943 - loss: 0.0643 - mae: 0.1444 - rmse: 0.2216 - smape: 0.3638 - val_ia: 0.6842 - val_loss: 0.0572 - val_mae: 0.1357 - val_rmse: 0.1894 - val_smape: 0.3614

Epoch 48/128

1916/1916 - 6s - 3ms/step - ia: 0.8932 - loss: 0.0643 - mae: 0.1453 - rmse: 0.2218 - smape: 0.3657 - val_ia: 0.6866 - val_loss: 0.0568 - val_mae: 0.1346 - val_rmse: 0.1881 - val_smape: 0.3557

Epoch 49/128

1916/1916 - 11s - 6ms/step - ia: 0.8947 - loss: 0.0640 - mae: 0.1441 - rmse: 0.2205 - smape: 0.3624 - val_ia: 0.6855 - val_loss: 0.0567 - val_mae: 0.1350 - val_rmse: 0.1890 - val_smape: 0.3567

Epoch 50/128

1916/1916 - 5s - 3ms/step - ia: 0.8944 - loss: 0.0642 - mae: 0.1443 - rmse: 0.2213 - smape: 0.3631 - val_ia: 0.6731 - val_loss: 0.0596 - val_mae: 0.1417 - val_rmse: 0.1955 - val_smape: 0.3667

Epoch 51/128

1916/1916 - 6s - 3ms/step - ia: 0.8946 - loss: 0.0639 - mae: 0.1441 - rmse: 0.2197 - smape: 0.3636 - val_ia: 0.6810 - val_loss: 0.0577 - val_mae: 0.1366 - val_rmse: 0.1913 - val_smape: 0.3606

Epoch 52/128

1916/1916 - 11s - 6ms/step - ia: 0.8943 - loss: 0.0641 - mae: 0.1441 - rmse: 0.2211 - smape: 0.3625 - val_ia: 0.6835 - val_loss: 0.0571 - val_mae: 0.1350 - val_rmse: 0.1888 - val_smape: 0.3598

Epoch 53/128

1916/1916 - 6s - 3ms/step - ia: 0.8947 - loss: 0.0644 - mae: 0.1437 - rmse: 0.2211 - smape: 0.3629 - val_ia: 0.6744 - val_loss: 0.0580 - val_mae: 0.1398 - val_rmse: 0.1914 - val_smape: 0.3650

Epoch 54/128

1916/1916 - 6s - 3ms/step - ia: 0.8944 - loss: 0.0638 - mae: 0.1436 - rmse: 0.2213 - smape: 0.3628 - val_ia: 0.6793 - val_loss: 0.0620 - val_mae: 0.1418 - val_rmse: 0.1977 - val_smape: 0.3595

Epoch 55/128

1916/1916 - 5s - 3ms/step - ia: 0.8947 - loss: 0.0640 - mae: 0.1441 - rmse: 0.2205 - smape: 0.3641 - val_ia: 0.6911 - val_loss: 0.0565 - val_mae: 0.1331 - val_rmse: 0.1870 - val_smape: 0.3543

Epoch 56/128

1916/1916 - 6s - 3ms/step - ia: 0.8931 - loss: 0.0639 - mae: 0.1447 - rmse: 0.2209 - smape: 0.3639 - val_ia: 0.6829 - val_loss: 0.0570 - val_mae: 0.1357 - val_rmse: 0.1891 - val_smape: 0.3597

Epoch 56: early stopping

Restoring model weights from the end of the best epoch: 41.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 215ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 17%|█▋        | 2/12 [09:55<54:23, 326.31s/trial, best loss: 0.03826835975527505]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 16s - 4ms/step - ia: 0.3227 - loss: 1.6017 - mae: 0.8390 - rmse: 1.1512 - smape: 1.2709 - val_ia: 0.2016 - val_loss: 1.2701 - val_mae: 0.7266 - val_rmse: 0.7806 - val_smape: 1.1970

Epoch 2/128

3832/3832 - 11s - 3ms/step - ia: 0.3149 - loss: 1.4407 - mae: 0.7987 - rmse: 1.0863 - smape: 1.3073 - val_ia: 0.2026 - val_loss: 1.1819 - val_mae: 0.7103 - val_rmse: 0.7615 - val_smape: 1.2446

Epoch 3/128

3832/3832 - 19s - 5ms/step - ia: 0.3068 - loss: 1.3139 - mae: 0.7718 - rmse: 1.0411 - smape: 1.3440 - val_ia: 0.2022 - val_loss: 1.1170 - val_mae: 0.7004 - val_rmse: 0.7500 - val_smape: 1.2915

Epoch 4/128

3832/3832 - 10s - 3ms/step - ia: 0.3014 - loss: 1.2423 - mae: 0.7566 - rmse: 1.0115 - smape: 1.3816 - val_ia: 0.2014 - val_loss: 1.0658 - val_mae: 0.6943 - val_rmse: 0.7422 - val_smape: 1.3410

Epoch 5/128

3832/3832 - 25s - 7ms/step - ia: 0.2954 - loss: 1.1712 - mae: 0.7422 - rmse: 0.9863 - smape: 1.4114 - val_ia: 0.1998 - val_loss: 1.0239 - val_mae: 0.6898 - val_rmse: 0.7363 - val_smape: 1.3897

Epoch 6/128

3832/3832 - 18s - 5ms/step - ia: 0.2910 - loss: 1.1286 - mae: 0.7343 - rmse: 0.9664 - smape: 1.4395 - val_ia: 0.1979 - val_loss: 0.9906 - val_mae: 0.6866 - val_rmse: 0.7321 - val_smape: 1.4329

Epoch 7/128

3832/3832 - 11s - 3ms/step - ia: 0.2944 - loss: 1.0887 - mae: 0.7255 - rmse: 0.9529 - smape: 1.4579 - val_ia: 0.1970 - val_loss: 0.9615 - val_mae: 0.6840 - val_rmse: 0.7287 - val_smape: 1.4681

Epoch 8/128

3832/3832 - 13s - 3ms/step - ia: 0.2957 - loss: 1.0477 - mae: 0.7173 - rmse: 0.9339 - smape: 1.4770 - val_ia: 0.1962 - val_loss: 0.9371 - val_mae: 0.6814 - val_rmse: 0.7255 - val_smape: 1.4949

Epoch 9/128

3832/3832 - 21s - 6ms/step - ia: 0.2996 - loss: 1.0174 - mae: 0.7111 - rmse: 0.9247 - smape: 1.4854 - val_ia: 0.1961 - val_loss: 0.9150 - val_mae: 0.6780 - val_rmse: 0.7219 - val_smape: 1.5105

Epoch 10/128

3832/3832 - 12s - 3ms/step - ia: 0.3046 - loss: 0.9931 - mae: 0.7047 - rmse: 0.9144 - smape: 1.4913 - val_ia: 0.1964 - val_loss: 0.8952 - val_mae: 0.6746 - val_rmse: 0.7183 - val_smape: 1.5201

Epoch 11/128

3832/3832 - 12s - 3ms/step - ia: 0.3089 - loss: 0.9659 - mae: 0.6976 - rmse: 0.9008 - smape: 1.4880 - val_ia: 0.1967 - val_loss: 0.8761 - val_mae: 0.6704 - val_rmse: 0.7141 - val_smape: 1.5226

Epoch 12/128

3832/3832 - 15s - 4ms/step - ia: 0.3159 - loss: 0.9475 - mae: 0.6923 - rmse: 0.8931 - smape: 1.4818 - val_ia: 0.1968 - val_loss: 0.8584 - val_mae: 0.6659 - val_rmse: 0.7096 - val_smape: 1.5212

Epoch 13/128

3832/3832 - 19s - 5ms/step - ia: 0.3238 - loss: 0.9313 - mae: 0.6886 - rmse: 0.8866 - smape: 1.4747 - val_ia: 0.1976 - val_loss: 0.8410 - val_mae: 0.6609 - val_rmse: 0.7049 - val_smape: 1.5141

Epoch 14/128

3832/3832 - 11s - 3ms/step - ia: 0.3330 - loss: 0.9064 - mae: 0.6795 - rmse: 0.8766 - smape: 1.4576 - val_ia: 0.1984 - val_loss: 0.8242 - val_mae: 0.6558 - val_rmse: 0.7000 - val_smape: 1.5048

Epoch 15/128

3832/3832 - 10s - 3ms/step - ia: 0.3421 - loss: 0.8894 - mae: 0.6733 - rmse: 0.8672 - smape: 1.4454 - val_ia: 0.1997 - val_loss: 0.8074 - val_mae: 0.6501 - val_rmse: 0.6945 - val_smape: 1.4925

Epoch 16/128

3832/3832 - 13s - 3ms/step - ia: 0.3509 - loss: 0.8667 - mae: 0.6675 - rmse: 0.8574 - smape: 1.4325 - val_ia: 0.2005 - val_loss: 0.7905 - val_mae: 0.6443 - val_rmse: 0.6891 - val_smape: 1.4777

Epoch 17/128

3832/3832 - 16s - 4ms/step - ia: 0.3569 - loss: 0.8552 - mae: 0.6630 - rmse: 0.8528 - smape: 1.4145 - val_ia: 0.2004 - val_loss: 0.7734 - val_mae: 0.6388 - val_rmse: 0.6839 - val_smape: 1.4615

Epoch 18/128

3832/3832 - 21s - 6ms/step - ia: 0.3677 - loss: 0.8411 - mae: 0.6578 - rmse: 0.8433 - smape: 1.3961 - val_ia: 0.2008 - val_loss: 0.7563 - val_mae: 0.6330 - val_rmse: 0.6784 - val_smape: 1.4446

Epoch 19/128

3832/3832 - 28s - 7ms/step - ia: 0.3749 - loss: 0.8238 - mae: 0.6514 - rmse: 0.8359 - smape: 1.3806 - val_ia: 0.2015 - val_loss: 0.7385 - val_mae: 0.6268 - val_rmse: 0.6725 - val_smape: 1.4257

Epoch 20/128

3832/3832 - 22s - 6ms/step - ia: 0.3841 - loss: 0.8085 - mae: 0.6459 - rmse: 0.8288 - smape: 1.3659 - val_ia: 0.2021 - val_loss: 0.7203 - val_mae: 0.6202 - val_rmse: 0.6662 - val_smape: 1.4054

Epoch 21/128

3832/3832 - 18s - 5ms/step - ia: 0.3932 - loss: 0.7949 - mae: 0.6404 - rmse: 0.8212 - smape: 1.3453 - val_ia: 0.2029 - val_loss: 0.7014 - val_mae: 0.6128 - val_rmse: 0.6592 - val_smape: 1.3841

Epoch 22/128

3832/3832 - 16s - 4ms/step - ia: 0.4057 - loss: 0.7725 - mae: 0.6313 - rmse: 0.8101 - smape: 1.3256 - val_ia: 0.2037 - val_loss: 0.6826 - val_mae: 0.6052 - val_rmse: 0.6519 - val_smape: 1.3623

Epoch 23/128

3832/3832 - 17s - 5ms/step - ia: 0.4152 - loss: 0.7560 - mae: 0.6256 - rmse: 0.8010 - smape: 1.3072 - val_ia: 0.2045 - val_loss: 0.6631 - val_mae: 0.5971 - val_rmse: 0.6442 - val_smape: 1.3396

Epoch 24/128

3832/3832 - 17s - 4ms/step - ia: 0.4201 - loss: 0.7491 - mae: 0.6211 - rmse: 0.7984 - smape: 1.2953 - val_ia: 0.2053 - val_loss: 0.6448 - val_mae: 0.5891 - val_rmse: 0.6365 - val_smape: 1.3173

Epoch 25/128

3832/3832 - 14s - 4ms/step - ia: 0.4307 - loss: 0.7303 - mae: 0.6136 - rmse: 0.7880 - smape: 1.2758 - val_ia: 0.2061 - val_loss: 0.6262 - val_mae: 0.5808 - val_rmse: 0.6287 - val_smape: 1.2950

Epoch 26/128

3832/3832 - 16s - 4ms/step - ia: 0.4414 - loss: 0.7112 - mae: 0.6044 - rmse: 0.7765 - smape: 1.2536 - val_ia: 0.2072 - val_loss: 0.6078 - val_mae: 0.5720 - val_rmse: 0.6204 - val_smape: 1.2712

Epoch 27/128

3832/3832 - 21s - 6ms/step - ia: 0.4533 - loss: 0.6928 - mae: 0.5968 - rmse: 0.7663 - smape: 1.2397 - val_ia: 0.2085 - val_loss: 0.5883 - val_mae: 0.5626 - val_rmse: 0.6115 - val_smape: 1.2467

Epoch 28/128

3832/3832 - 16s - 4ms/step - ia: 0.4580 - loss: 0.6860 - mae: 0.5939 - rmse: 0.7638 - smape: 1.2253 - val_ia: 0.2098 - val_loss: 0.5702 - val_mae: 0.5534 - val_rmse: 0.6029 - val_smape: 1.2232

Epoch 29/128

3832/3832 - 22s - 6ms/step - ia: 0.4678 - loss: 0.6752 - mae: 0.5859 - rmse: 0.7556 - smape: 1.2063 - val_ia: 0.2113 - val_loss: 0.5535 - val_mae: 0.5448 - val_rmse: 0.5948 - val_smape: 1.2013

Epoch 30/128

3832/3832 - 21s - 5ms/step - ia: 0.4793 - loss: 0.6612 - mae: 0.5791 - rmse: 0.7470 - smape: 1.1888 - val_ia: 0.2129 - val_loss: 0.5366 - val_mae: 0.5359 - val_rmse: 0.5864 - val_smape: 1.1803

Epoch 31/128

3832/3832 - 16s - 4ms/step - ia: 0.4869 - loss: 0.6404 - mae: 0.5710 - rmse: 0.7375 - smape: 1.1708 - val_ia: 0.2140 - val_loss: 0.5209 - val_mae: 0.5273 - val_rmse: 0.5782 - val_smape: 1.1602

Epoch 32/128

3832/3832 - 16s - 4ms/step - ia: 0.4937 - loss: 0.6372 - mae: 0.5668 - rmse: 0.7330 - smape: 1.1561 - val_ia: 0.2149 - val_loss: 0.5071 - val_mae: 0.5197 - val_rmse: 0.5710 - val_smape: 1.1426

Epoch 33/128

3832/3832 - 16s - 4ms/step - ia: 0.5026 - loss: 0.6227 - mae: 0.5620 - rmse: 0.7280 - smape: 1.1460 - val_ia: 0.2158 - val_loss: 0.4938 - val_mae: 0.5125 - val_rmse: 0.5641 - val_smape: 1.1253

Epoch 34/128

3832/3832 - 15s - 4ms/step - ia: 0.5120 - loss: 0.6107 - mae: 0.5552 - rmse: 0.7179 - smape: 1.1336 - val_ia: 0.2167 - val_loss: 0.4817 - val_mae: 0.5055 - val_rmse: 0.5574 - val_smape: 1.1085

Epoch 35/128

3832/3832 - 22s - 6ms/step - ia: 0.5157 - loss: 0.6097 - mae: 0.5510 - rmse: 0.7169 - smape: 1.1172 - val_ia: 0.2176 - val_loss: 0.4701 - val_mae: 0.4990 - val_rmse: 0.5512 - val_smape: 1.0935

Epoch 36/128

3832/3832 - 17s - 4ms/step - ia: 0.5220 - loss: 0.5972 - mae: 0.5479 - rmse: 0.7105 - smape: 1.1132 - val_ia: 0.2188 - val_loss: 0.4598 - val_mae: 0.4928 - val_rmse: 0.5454 - val_smape: 1.0793

Epoch 37/128

3832/3832 - 16s - 4ms/step - ia: 0.5250 - loss: 0.5913 - mae: 0.5450 - rmse: 0.7066 - smape: 1.1034 - val_ia: 0.2201 - val_loss: 0.4500 - val_mae: 0.4871 - val_rmse: 0.5399 - val_smape: 1.0658

Epoch 38/128

3832/3832 - 18s - 5ms/step - ia: 0.5343 - loss: 0.5758 - mae: 0.5365 - rmse: 0.6985 - smape: 1.0893 - val_ia: 0.2214 - val_loss: 0.4408 - val_mae: 0.4813 - val_rmse: 0.5345 - val_smape: 1.0520

Epoch 39/128

3832/3832 - 15s - 4ms/step - ia: 0.5350 - loss: 0.5802 - mae: 0.5365 - rmse: 0.6998 - smape: 1.0833 - val_ia: 0.2227 - val_loss: 0.4325 - val_mae: 0.4761 - val_rmse: 0.5295 - val_smape: 1.0391

Epoch 40/128

3832/3832 - 16s - 4ms/step - ia: 0.5416 - loss: 0.5679 - mae: 0.5317 - rmse: 0.6911 - smape: 1.0741 - val_ia: 0.2238 - val_loss: 0.4247 - val_mae: 0.4712 - val_rmse: 0.5248 - val_smape: 1.0279

Epoch 41/128

3832/3832 - 19s - 5ms/step - ia: 0.5432 - loss: 0.5611 - mae: 0.5292 - rmse: 0.6896 - smape: 1.0682 - val_ia: 0.2248 - val_loss: 0.4175 - val_mae: 0.4669 - val_rmse: 0.5206 - val_smape: 1.0172

Epoch 42/128

3832/3832 - 14s - 4ms/step - ia: 0.5494 - loss: 0.5624 - mae: 0.5257 - rmse: 0.6872 - smape: 1.0559 - val_ia: 0.2260 - val_loss: 0.4112 - val_mae: 0.4627 - val_rmse: 0.5166 - val_smape: 1.0074

Epoch 43/128

3832/3832 - 12s - 3ms/step - ia: 0.5524 - loss: 0.5575 - mae: 0.5232 - rmse: 0.6821 - smape: 1.0543 - val_ia: 0.2269 - val_loss: 0.4050 - val_mae: 0.4588 - val_rmse: 0.5128 - val_smape: 0.9979

Epoch 44/128

3832/3832 - 22s - 6ms/step - ia: 0.5560 - loss: 0.5482 - mae: 0.5183 - rmse: 0.6777 - smape: 1.0433 - val_ia: 0.2278 - val_loss: 0.3988 - val_mae: 0.4550 - val_rmse: 0.5090 - val_smape: 0.9891

Epoch 45/128

3832/3832 - 14s - 4ms/step - ia: 0.5580 - loss: 0.5412 - mae: 0.5151 - rmse: 0.6745 - smape: 1.0399 - val_ia: 0.2288 - val_loss: 0.3931 - val_mae: 0.4514 - val_rmse: 0.5055 - val_smape: 0.9814

Epoch 46/128

3832/3832 - 13s - 3ms/step - ia: 0.5596 - loss: 0.5491 - mae: 0.5155 - rmse: 0.6761 - smape: 1.0324 - val_ia: 0.2297 - val_loss: 0.3878 - val_mae: 0.4481 - val_rmse: 0.5022 - val_smape: 0.9738

Epoch 47/128

3832/3832 - 14s - 4ms/step - ia: 0.5637 - loss: 0.5336 - mae: 0.5113 - rmse: 0.6701 - smape: 1.0310 - val_ia: 0.2308 - val_loss: 0.3825 - val_mae: 0.4444 - val_rmse: 0.4985 - val_smape: 0.9656

Epoch 48/128

3832/3832 - 13s - 3ms/step - ia: 0.5662 - loss: 0.5303 - mae: 0.5092 - rmse: 0.6667 - smape: 1.0248 - val_ia: 0.2319 - val_loss: 0.3771 - val_mae: 0.4408 - val_rmse: 0.4950 - val_smape: 0.9580

Epoch 49/128

3832/3832 - 20s - 5ms/step - ia: 0.5675 - loss: 0.5224 - mae: 0.5074 - rmse: 0.6635 - smape: 1.0188 - val_ia: 0.2329 - val_loss: 0.3722 - val_mae: 0.4375 - val_rmse: 0.4917 - val_smape: 0.9506

Epoch 50/128

3832/3832 - 21s - 5ms/step - ia: 0.5702 - loss: 0.5271 - mae: 0.5043 - rmse: 0.6627 - smape: 1.0128 - val_ia: 0.2339 - val_loss: 0.3676 - val_mae: 0.4345 - val_rmse: 0.4886 - val_smape: 0.9444

Epoch 51/128

3832/3832 - 12s - 3ms/step - ia: 0.5748 - loss: 0.5146 - mae: 0.4995 - rmse: 0.6553 - smape: 1.0073 - val_ia: 0.2349 - val_loss: 0.3629 - val_mae: 0.4312 - val_rmse: 0.4854 - val_smape: 0.9373

Epoch 52/128

3832/3832 - 23s - 6ms/step - ia: 0.5756 - loss: 0.5154 - mae: 0.4994 - rmse: 0.6562 - smape: 1.0062 - val_ia: 0.2358 - val_loss: 0.3587 - val_mae: 0.4286 - val_rmse: 0.4828 - val_smape: 0.9324

Epoch 53/128

3832/3832 - 14s - 4ms/step - ia: 0.5790 - loss: 0.5018 - mae: 0.4944 - rmse: 0.6487 - smape: 0.9978 - val_ia: 0.2368 - val_loss: 0.3543 - val_mae: 0.4257 - val_rmse: 0.4799 - val_smape: 0.9262

Epoch 54/128

3832/3832 - 14s - 4ms/step - ia: 0.5840 - loss: 0.4955 - mae: 0.4904 - rmse: 0.6438 - smape: 0.9903 - val_ia: 0.2377 - val_loss: 0.3499 - val_mae: 0.4229 - val_rmse: 0.4771 - val_smape: 0.9203

Epoch 55/128

3832/3832 - 14s - 4ms/step - ia: 0.5839 - loss: 0.4919 - mae: 0.4883 - rmse: 0.6423 - smape: 0.9873 - val_ia: 0.2387 - val_loss: 0.3457 - val_mae: 0.4202 - val_rmse: 0.4744 - val_smape: 0.9146

Epoch 56/128

3832/3832 - 16s - 4ms/step - ia: 0.5863 - loss: 0.4951 - mae: 0.4867 - rmse: 0.6415 - smape: 0.9805 - val_ia: 0.2398 - val_loss: 0.3412 - val_mae: 0.4173 - val_rmse: 0.4715 - val_smape: 0.9090

Epoch 57/128

3832/3832 - 14s - 4ms/step - ia: 0.5883 - loss: 0.4868 - mae: 0.4845 - rmse: 0.6386 - smape: 0.9816 - val_ia: 0.2410 - val_loss: 0.3370 - val_mae: 0.4146 - val_rmse: 0.4687 - val_smape: 0.9032

Epoch 58/128

3832/3832 - 23s - 6ms/step - ia: 0.5879 - loss: 0.4890 - mae: 0.4838 - rmse: 0.6388 - smape: 0.9779 - val_ia: 0.2421 - val_loss: 0.3333 - val_mae: 0.4120 - val_rmse: 0.4661 - val_smape: 0.8981

Epoch 59/128

3832/3832 - 15s - 4ms/step - ia: 0.5921 - loss: 0.4708 - mae: 0.4791 - rmse: 0.6297 - smape: 0.9685 - val_ia: 0.2432 - val_loss: 0.3292 - val_mae: 0.4093 - val_rmse: 0.4635 - val_smape: 0.8926

Epoch 60/128

3832/3832 - 21s - 5ms/step - ia: 0.5969 - loss: 0.4732 - mae: 0.4762 - rmse: 0.6271 - smape: 0.9635 - val_ia: 0.2444 - val_loss: 0.3256 - val_mae: 0.4068 - val_rmse: 0.4609 - val_smape: 0.8869

Epoch 61/128

3832/3832 - 19s - 5ms/step - ia: 0.5990 - loss: 0.4671 - mae: 0.4732 - rmse: 0.6239 - smape: 0.9571 - val_ia: 0.2455 - val_loss: 0.3219 - val_mae: 0.4042 - val_rmse: 0.4582 - val_smape: 0.8814

Epoch 62/128

3832/3832 - 16s - 4ms/step - ia: 0.5974 - loss: 0.4754 - mae: 0.4757 - rmse: 0.6286 - smape: 0.9588 - val_ia: 0.2466 - val_loss: 0.3186 - val_mae: 0.4019 - val_rmse: 0.4558 - val_smape: 0.8765

Epoch 63/128

3832/3832 - 10s - 3ms/step - ia: 0.6020 - loss: 0.4621 - mae: 0.4690 - rmse: 0.6194 - smape: 0.9502 - val_ia: 0.2476 - val_loss: 0.3149 - val_mae: 0.3993 - val_rmse: 0.4532 - val_smape: 0.8711

Epoch 64/128

3832/3832 - 11s - 3ms/step - ia: 0.6062 - loss: 0.4594 - mae: 0.4668 - rmse: 0.6181 - smape: 0.9448 - val_ia: 0.2487 - val_loss: 0.3115 - val_mae: 0.3969 - val_rmse: 0.4508 - val_smape: 0.8661

Epoch 65/128

3832/3832 - 8s - 2ms/step - ia: 0.6035 - loss: 0.4592 - mae: 0.4661 - rmse: 0.6157 - smape: 0.9445 - val_ia: 0.2499 - val_loss: 0.3078 - val_mae: 0.3941 - val_rmse: 0.4480 - val_smape: 0.8601

Epoch 66/128

3832/3832 - 14s - 4ms/step - ia: 0.6098 - loss: 0.4392 - mae: 0.4606 - rmse: 0.6059 - smape: 0.9365 - val_ia: 0.2510 - val_loss: 0.3045 - val_mae: 0.3919 - val_rmse: 0.4457 - val_smape: 0.8558

Epoch 67/128

3832/3832 - 14s - 4ms/step - ia: 0.6094 - loss: 0.4469 - mae: 0.4605 - rmse: 0.6091 - smape: 0.9333 - val_ia: 0.2521 - val_loss: 0.3013 - val_mae: 0.3898 - val_rmse: 0.4435 - val_smape: 0.8514

Epoch 68/128

3832/3832 - 14s - 4ms/step - ia: 0.6101 - loss: 0.4472 - mae: 0.4600 - rmse: 0.6095 - smape: 0.9283 - val_ia: 0.2532 - val_loss: 0.2977 - val_mae: 0.3875 - val_rmse: 0.4412 - val_smape: 0.8472

Epoch 69/128

3832/3832 - 21s - 5ms/step - ia: 0.6127 - loss: 0.4437 - mae: 0.4557 - rmse: 0.6049 - smape: 0.9237 - val_ia: 0.2545 - val_loss: 0.2947 - val_mae: 0.3852 - val_rmse: 0.4388 - val_smape: 0.8418

Epoch 70/128

3832/3832 - 21s - 6ms/step - ia: 0.6152 - loss: 0.4440 - mae: 0.4552 - rmse: 0.6043 - smape: 0.9211 - val_ia: 0.2554 - val_loss: 0.2915 - val_mae: 0.3832 - val_rmse: 0.4367 - val_smape: 0.8383

Epoch 71/128

3832/3832 - 21s - 5ms/step - ia: 0.6166 - loss: 0.4350 - mae: 0.4535 - rmse: 0.5993 - smape: 0.9200 - val_ia: 0.2563 - val_loss: 0.2888 - val_mae: 0.3814 - val_rmse: 0.4348 - val_smape: 0.8351

Epoch 72/128

3832/3832 - 20s - 5ms/step - ia: 0.6176 - loss: 0.4249 - mae: 0.4505 - rmse: 0.5951 - smape: 0.9196 - val_ia: 0.2576 - val_loss: 0.2853 - val_mae: 0.3787 - val_rmse: 0.4321 - val_smape: 0.8294

Epoch 73/128

3832/3832 - 12s - 3ms/step - ia: 0.6202 - loss: 0.4302 - mae: 0.4472 - rmse: 0.5937 - smape: 0.9091 - val_ia: 0.2587 - val_loss: 0.2822 - val_mae: 0.3765 - val_rmse: 0.4297 - val_smape: 0.8247

Epoch 74/128

3832/3832 - 14s - 4ms/step - ia: 0.6210 - loss: 0.4312 - mae: 0.4491 - rmse: 0.5956 - smape: 0.9090 - val_ia: 0.2597 - val_loss: 0.2794 - val_mae: 0.3745 - val_rmse: 0.4277 - val_smape: 0.8211

Epoch 75/128

3832/3832 - 12s - 3ms/step - ia: 0.6237 - loss: 0.4259 - mae: 0.4465 - rmse: 0.5914 - smape: 0.9089 - val_ia: 0.2607 - val_loss: 0.2767 - val_mae: 0.3728 - val_rmse: 0.4258 - val_smape: 0.8178

Epoch 76/128

3832/3832 - 12s - 3ms/step - ia: 0.6247 - loss: 0.4195 - mae: 0.4444 - rmse: 0.5892 - smape: 0.9038 - val_ia: 0.2616 - val_loss: 0.2740 - val_mae: 0.3709 - val_rmse: 0.4238 - val_smape: 0.8143

Epoch 77/128

3832/3832 - 14s - 4ms/step - ia: 0.6280 - loss: 0.4155 - mae: 0.4406 - rmse: 0.5850 - smape: 0.8982 - val_ia: 0.2627 - val_loss: 0.2712 - val_mae: 0.3687 - val_rmse: 0.4215 - val_smape: 0.8098

Epoch 78/128

3832/3832 - 13s - 3ms/step - ia: 0.6272 - loss: 0.4163 - mae: 0.4416 - rmse: 0.5862 - smape: 0.8977 - val_ia: 0.2637 - val_loss: 0.2686 - val_mae: 0.3667 - val_rmse: 0.4195 - val_smape: 0.8059

Epoch 79/128

3832/3832 - 19s - 5ms/step - ia: 0.6320 - loss: 0.4096 - mae: 0.4362 - rmse: 0.5807 - smape: 0.8892 - val_ia: 0.2648 - val_loss: 0.2661 - val_mae: 0.3647 - val_rmse: 0.4174 - val_smape: 0.8013

Epoch 80/128

3832/3832 - 10s - 3ms/step - ia: 0.6367 - loss: 0.3978 - mae: 0.4313 - rmse: 0.5712 - smape: 0.8856 - val_ia: 0.2660 - val_loss: 0.2632 - val_mae: 0.3625 - val_rmse: 0.4150 - val_smape: 0.7967

Epoch 81/128

3832/3832 - 10s - 3ms/step - ia: 0.6347 - loss: 0.3918 - mae: 0.4306 - rmse: 0.5712 - smape: 0.8829 - val_ia: 0.2669 - val_loss: 0.2605 - val_mae: 0.3606 - val_rmse: 0.4131 - val_smape: 0.7928

Epoch 82/128

3832/3832 - 9s - 2ms/step - ia: 0.6354 - loss: 0.3943 - mae: 0.4301 - rmse: 0.5713 - smape: 0.8807 - val_ia: 0.2678 - val_loss: 0.2575 - val_mae: 0.3585 - val_rmse: 0.4110 - val_smape: 0.7888

Epoch 83/128

3832/3832 - 15s - 4ms/step - ia: 0.6387 - loss: 0.3967 - mae: 0.4286 - rmse: 0.5691 - smape: 0.8720 - val_ia: 0.2687 - val_loss: 0.2552 - val_mae: 0.3569 - val_rmse: 0.4092 - val_smape: 0.7858

Epoch 84/128

3832/3832 - 24s - 6ms/step - ia: 0.6400 - loss: 0.3971 - mae: 0.4274 - rmse: 0.5690 - smape: 0.8718 - val_ia: 0.2697 - val_loss: 0.2530 - val_mae: 0.3551 - val_rmse: 0.4073 - val_smape: 0.7820

Epoch 85/128

3832/3832 - 13s - 3ms/step - ia: 0.6421 - loss: 0.3919 - mae: 0.4261 - rmse: 0.5670 - smape: 0.8711 - val_ia: 0.2709 - val_loss: 0.2504 - val_mae: 0.3531 - val_rmse: 0.4052 - val_smape: 0.7773

Epoch 86/128

3832/3832 - 23s - 6ms/step - ia: 0.6399 - loss: 0.3865 - mae: 0.4248 - rmse: 0.5650 - smape: 0.8717 - val_ia: 0.2720 - val_loss: 0.2479 - val_mae: 0.3511 - val_rmse: 0.4032 - val_smape: 0.7735

Epoch 87/128

3832/3832 - 14s - 4ms/step - ia: 0.6456 - loss: 0.3802 - mae: 0.4212 - rmse: 0.5589 - smape: 0.8659 - val_ia: 0.2731 - val_loss: 0.2456 - val_mae: 0.3492 - val_rmse: 0.4012 - val_smape: 0.7687

Epoch 88/128

3832/3832 - 13s - 3ms/step - ia: 0.6468 - loss: 0.3805 - mae: 0.4190 - rmse: 0.5596 - smape: 0.8596 - val_ia: 0.2741 - val_loss: 0.2437 - val_mae: 0.3475 - val_rmse: 0.3994 - val_smape: 0.7645

Epoch 89/128

3832/3832 - 14s - 4ms/step - ia: 0.6456 - loss: 0.3760 - mae: 0.4190 - rmse: 0.5574 - smape: 0.8596 - val_ia: 0.2750 - val_loss: 0.2409 - val_mae: 0.3456 - val_rmse: 0.3973 - val_smape: 0.7607

Epoch 90/128

3832/3832 - 19s - 5ms/step - ia: 0.6521 - loss: 0.3713 - mae: 0.4145 - rmse: 0.5518 - smape: 0.8500 - val_ia: 0.2757 - val_loss: 0.2390 - val_mae: 0.3443 - val_rmse: 0.3959 - val_smape: 0.7584

Epoch 91/128

3832/3832 - 12s - 3ms/step - ia: 0.6515 - loss: 0.3655 - mae: 0.4134 - rmse: 0.5486 - smape: 0.8503 - val_ia: 0.2766 - val_loss: 0.2371 - val_mae: 0.3429 - val_rmse: 0.3943 - val_smape: 0.7553

Epoch 92/128

3832/3832 - 22s - 6ms/step - ia: 0.6493 - loss: 0.3711 - mae: 0.4158 - rmse: 0.5529 - smape: 0.8533 - val_ia: 0.2776 - val_loss: 0.2347 - val_mae: 0.3409 - val_rmse: 0.3922 - val_smape: 0.7512

Epoch 93/128

3832/3832 - 19s - 5ms/step - ia: 0.6512 - loss: 0.3753 - mae: 0.4143 - rmse: 0.5521 - smape: 0.8481 - val_ia: 0.2784 - val_loss: 0.2331 - val_mae: 0.3396 - val_rmse: 0.3908 - val_smape: 0.7480

Epoch 94/128

3832/3832 - 22s - 6ms/step - ia: 0.6524 - loss: 0.3694 - mae: 0.4123 - rmse: 0.5504 - smape: 0.8443 - val_ia: 0.2794 - val_loss: 0.2309 - val_mae: 0.3378 - val_rmse: 0.3889 - val_smape: 0.7445

Epoch 95/128

3832/3832 - 16s - 4ms/step - ia: 0.6574 - loss: 0.3609 - mae: 0.4073 - rmse: 0.5446 - smape: 0.8357 - val_ia: 0.2802 - val_loss: 0.2291 - val_mae: 0.3364 - val_rmse: 0.3874 - val_smape: 0.7414

Epoch 96/128

3832/3832 - 10s - 3ms/step - ia: 0.6589 - loss: 0.3582 - mae: 0.4065 - rmse: 0.5422 - smape: 0.8355 - val_ia: 0.2809 - val_loss: 0.2273 - val_mae: 0.3353 - val_rmse: 0.3860 - val_smape: 0.7389

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 6s - 6ms/step - ia: 0.2844 - loss: 7.0985 - mae: 1.9725 - rmse: 2.6124 - smape: 1.4226 - val_ia: 0.3582 - val_loss: 0.5750 - val_mae: 0.5616 - val_rmse: 0.7080 - val_smape: 0.9578

Epoch 2/128

958/958 - 2s - 3ms/step - ia: 0.3139 - loss: 5.4071 - mae: 1.7272 - rmse: 2.2823 - smape: 1.3867 - val_ia: 0.4048 - val_loss: 0.4177 - val_mae: 0.4655 - val_rmse: 0.5925 - val_smape: 0.8844

Epoch 3/128

958/958 - 3s - 3ms/step - ia: 0.3371 - loss: 4.2710 - mae: 1.5348 - rmse: 2.0278 - smape: 1.3517 - val_ia: 0.4389 - val_loss: 0.3367 - val_mae: 0.4098 - val_rmse: 0.5233 - val_smape: 0.8275

Epoch 4/128

958/958 - 6s - 6ms/step - ia: 0.3568 - loss: 3.5963 - mae: 1.4071 - rmse: 1.8612 - smape: 1.3282 - val_ia: 0.4547 - val_loss: 0.2988 - val_mae: 0.3837 - val_rmse: 0.4854 - val_smape: 0.8039

Epoch 5/128

958/958 - 4s - 4ms/step - ia: 0.3721 - loss: 3.1314 - mae: 1.3064 - rmse: 1.7329 - smape: 1.3088 - val_ia: 0.4714 - val_loss: 0.2646 - val_mae: 0.3580 - val_rmse: 0.4518 - val_smape: 0.7649

Epoch 6/128

958/958 - 4s - 4ms/step - ia: 0.3932 - loss: 2.6741 - mae: 1.2055 - rmse: 1.6019 - smape: 1.2831 - val_ia: 0.4802 - val_loss: 0.2464 - val_mae: 0.3439 - val_rmse: 0.4321 - val_smape: 0.7448

Epoch 7/128

958/958 - 5s - 6ms/step - ia: 0.4096 - loss: 2.3486 - mae: 1.1294 - rmse: 1.5017 - smape: 1.2620 - val_ia: 0.4859 - val_loss: 0.2328 - val_mae: 0.3337 - val_rmse: 0.4172 - val_smape: 0.7256

Epoch 8/128

958/958 - 3s - 3ms/step - ia: 0.4232 - loss: 2.0663 - mae: 1.0674 - rmse: 1.4103 - smape: 1.2461 - val_ia: 0.4873 - val_loss: 0.2266 - val_mae: 0.3297 - val_rmse: 0.4093 - val_smape: 0.7144

Epoch 9/128

958/958 - 3s - 3ms/step - ia: 0.4368 - loss: 1.8861 - mae: 1.0159 - rmse: 1.3476 - smape: 1.2272 - val_ia: 0.4888 - val_loss: 0.2208 - val_mae: 0.3259 - val_rmse: 0.4030 - val_smape: 0.7081

Epoch 10/128

958/958 - 3s - 3ms/step - ia: 0.4474 - loss: 1.7033 - mae: 0.9644 - rmse: 1.2790 - smape: 1.2142 - val_ia: 0.4971 - val_loss: 0.2103 - val_mae: 0.3156 - val_rmse: 0.3925 - val_smape: 0.6905

Epoch 11/128

958/958 - 3s - 3ms/step - ia: 0.4647 - loss: 1.5299 - mae: 0.9156 - rmse: 1.2150 - smape: 1.1924 - val_ia: 0.4957 - val_loss: 0.2104 - val_mae: 0.3176 - val_rmse: 0.3920 - val_smape: 0.6932

Epoch 12/128

958/958 - 3s - 3ms/step - ia: 0.4752 - loss: 1.4051 - mae: 0.8808 - rmse: 1.1629 - smape: 1.1787 - val_ia: 0.5009 - val_loss: 0.2032 - val_mae: 0.3120 - val_rmse: 0.3853 - val_smape: 0.6823

Epoch 13/128

958/958 - 3s - 3ms/step - ia: 0.4836 - loss: 1.3267 - mae: 0.8499 - rmse: 1.1293 - smape: 1.1647 - val_ia: 0.5031 - val_loss: 0.2008 - val_mae: 0.3103 - val_rmse: 0.3827 - val_smape: 0.6788

Epoch 14/128

958/958 - 3s - 3ms/step - ia: 0.4936 - loss: 1.2420 - mae: 0.8249 - rmse: 1.0941 - smape: 1.1468 - val_ia: 0.5079 - val_loss: 0.1965 - val_mae: 0.3063 - val_rmse: 0.3782 - val_smape: 0.6692

Epoch 15/128

958/958 - 3s - 3ms/step - ia: 0.5010 - loss: 1.1890 - mae: 0.8025 - rmse: 1.0658 - smape: 1.1425 - val_ia: 0.5203 - val_loss: 0.1853 - val_mae: 0.2955 - val_rmse: 0.3678 - val_smape: 0.6506

Epoch 16/128

958/958 - 3s - 3ms/step - ia: 0.5145 - loss: 1.0840 - mae: 0.7698 - rmse: 1.0220 - smape: 1.1193 - val_ia: 0.5243 - val_loss: 0.1822 - val_mae: 0.2930 - val_rmse: 0.3647 - val_smape: 0.6454

Epoch 17/128

958/958 - 3s - 3ms/step - ia: 0.5235 - loss: 1.0251 - mae: 0.7503 - rmse: 0.9946 - smape: 1.1053 - val_ia: 0.5300 - val_loss: 0.1777 - val_mae: 0.2888 - val_rmse: 0.3602 - val_smape: 0.6358

Epoch 18/128

958/958 - 3s - 3ms/step - ia: 0.5326 - loss: 0.9741 - mae: 0.7298 - rmse: 0.9691 - smape: 1.0957 - val_ia: 0.5344 - val_loss: 0.1738 - val_mae: 0.2860 - val_rmse: 0.3564 - val_smape: 0.6291

Epoch 19/128

958/958 - 5s - 5ms/step - ia: 0.5406 - loss: 0.9219 - mae: 0.7096 - rmse: 0.9422 - smape: 1.0809 - val_ia: 0.5401 - val_loss: 0.1693 - val_mae: 0.2821 - val_rmse: 0.3522 - val_smape: 0.6238

Epoch 20/128

958/958 - 3s - 3ms/step - ia: 0.5434 - loss: 0.9030 - mae: 0.7001 - rmse: 0.9321 - smape: 1.0783 - val_ia: 0.5477 - val_loss: 0.1632 - val_mae: 0.2760 - val_rmse: 0.3460 - val_smape: 0.6139

Epoch 21/128

958/958 - 3s - 3ms/step - ia: 0.5555 - loss: 0.8487 - mae: 0.6783 - rmse: 0.9051 - smape: 1.0614 - val_ia: 0.5563 - val_loss: 0.1574 - val_mae: 0.2695 - val_rmse: 0.3394 - val_smape: 0.6012

Epoch 22/128

958/958 - 3s - 3ms/step - ia: 0.5634 - loss: 0.8014 - mae: 0.6601 - rmse: 0.8772 - smape: 1.0451 - val_ia: 0.5621 - val_loss: 0.1534 - val_mae: 0.2657 - val_rmse: 0.3352 - val_smape: 0.5945

Epoch 23/128

958/958 - 3s - 3ms/step - ia: 0.5704 - loss: 0.7670 - mae: 0.6484 - rmse: 0.8607 - smape: 1.0409 - val_ia: 0.5688 - val_loss: 0.1487 - val_mae: 0.2606 - val_rmse: 0.3296 - val_smape: 0.5845

Epoch 24/128

958/958 - 5s - 5ms/step - ia: 0.5767 - loss: 0.7387 - mae: 0.6340 - rmse: 0.8426 - smape: 1.0276 - val_ia: 0.5785 - val_loss: 0.1435 - val_mae: 0.2541 - val_rmse: 0.3231 - val_smape: 0.5729

Epoch 25/128

958/958 - 5s - 6ms/step - ia: 0.5838 - loss: 0.7093 - mae: 0.6228 - rmse: 0.8266 - smape: 1.0180 - val_ia: 0.5767 - val_loss: 0.1428 - val_mae: 0.2548 - val_rmse: 0.3228 - val_smape: 0.5738

Epoch 26/128

958/958 - 6s - 6ms/step - ia: 0.5932 - loss: 0.6708 - mae: 0.6036 - rmse: 0.8036 - smape: 1.0022 - val_ia: 0.5817 - val_loss: 0.1394 - val_mae: 0.2514 - val_rmse: 0.3191 - val_smape: 0.5672

Epoch 27/128

958/958 - 3s - 3ms/step - ia: 0.5929 - loss: 0.6615 - mae: 0.5994 - rmse: 0.7985 - smape: 1.0027 - val_ia: 0.5898 - val_loss: 0.1352 - val_mae: 0.2459 - val_rmse: 0.3136 - val_smape: 0.5577

Epoch 28/128

958/958 - 5s - 5ms/step - ia: 0.6032 - loss: 0.6312 - mae: 0.5844 - rmse: 0.7800 - smape: 0.9838 - val_ia: 0.5952 - val_loss: 0.1315 - val_mae: 0.2424 - val_rmse: 0.3099 - val_smape: 0.5532

Epoch 29/128

958/958 - 2s - 2ms/step - ia: 0.6134 - loss: 0.5849 - mae: 0.5643 - rmse: 0.7519 - smape: 0.9684 - val_ia: 0.5969 - val_loss: 0.1297 - val_mae: 0.2412 - val_rmse: 0.3079 - val_smape: 0.5508

Epoch 30/128

958/958 - 2s - 2ms/step - ia: 0.6119 - loss: 0.5814 - mae: 0.5647 - rmse: 0.7492 - smape: 0.9696 - val_ia: 0.6007 - val_loss: 0.1280 - val_mae: 0.2390 - val_rmse: 0.3055 - val_smape: 0.5458

Epoch 31/128

958/958 - 3s - 3ms/step - ia: 0.6203 - loss: 0.5593 - mae: 0.5505 - rmse: 0.7333 - smape: 0.9599 - val_ia: 0.6082 - val_loss: 0.1248 - val_mae: 0.2346 - val_rmse: 0.3012 - val_smape: 0.5380

Epoch 32/128

958/958 - 3s - 3ms/step - ia: 0.6239 - loss: 0.5487 - mae: 0.5470 - rmse: 0.7266 - smape: 0.9539 - val_ia: 0.6130 - val_loss: 0.1217 - val_mae: 0.2309 - val_rmse: 0.2977 - val_smape: 0.5332

Epoch 33/128

958/958 - 3s - 3ms/step - ia: 0.6343 - loss: 0.5179 - mae: 0.5300 - rmse: 0.7049 - smape: 0.9392 - val_ia: 0.6114 - val_loss: 0.1210 - val_mae: 0.2317 - val_rmse: 0.2977 - val_smape: 0.5339

Epoch 34/128

958/958 - 5s - 5ms/step - ia: 0.6386 - loss: 0.5046 - mae: 0.5206 - rmse: 0.6958 - smape: 0.9241 - val_ia: 0.6188 - val_loss: 0.1174 - val_mae: 0.2270 - val_rmse: 0.2930 - val_smape: 0.5256

Epoch 35/128

958/958 - 5s - 5ms/step - ia: 0.6425 - loss: 0.4909 - mae: 0.5146 - rmse: 0.6875 - smape: 0.9208 - val_ia: 0.6170 - val_loss: 0.1180 - val_mae: 0.2283 - val_rmse: 0.2937 - val_smape: 0.5264

Epoch 36/128

958/958 - 3s - 3ms/step - ia: 0.6469 - loss: 0.4737 - mae: 0.5044 - rmse: 0.6738 - smape: 0.9114 - val_ia: 0.6317 - val_loss: 0.1120 - val_mae: 0.2194 - val_rmse: 0.2856 - val_smape: 0.5126

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.6497 - loss: 0.4603 - mae: 0.5010 - rmse: 0.6656 - smape: 0.9098 - val_ia: 0.6323 - val_loss: 0.1109 - val_mae: 0.2187 - val_rmse: 0.2844 - val_smape: 0.5113

Epoch 38/128

958/958 - 3s - 3ms/step - ia: 0.6570 - loss: 0.4495 - mae: 0.4910 - rmse: 0.6569 - smape: 0.8938 - val_ia: 0.6318 - val_loss: 0.1106 - val_mae: 0.2190 - val_rmse: 0.2839 - val_smape: 0.5098

Epoch 39/128

958/958 - 3s - 3ms/step - ia: 0.6633 - loss: 0.4310 - mae: 0.4803 - rmse: 0.6422 - smape: 0.8846 - val_ia: 0.6368 - val_loss: 0.1084 - val_mae: 0.2159 - val_rmse: 0.2812 - val_smape: 0.5061

Epoch 40/128

958/958 - 3s - 3ms/step - ia: 0.6659 - loss: 0.4206 - mae: 0.4749 - rmse: 0.6339 - smape: 0.8784 - val_ia: 0.6433 - val_loss: 0.1055 - val_mae: 0.2120 - val_rmse: 0.2770 - val_smape: 0.4984

Epoch 41/128

958/958 - 3s - 3ms/step - ia: 0.6682 - loss: 0.4135 - mae: 0.4725 - rmse: 0.6312 - smape: 0.8756 - val_ia: 0.6424 - val_loss: 0.1056 - val_mae: 0.2126 - val_rmse: 0.2773 - val_smape: 0.4991

Epoch 42/128

958/958 - 3s - 3ms/step - ia: 0.6742 - loss: 0.3990 - mae: 0.4617 - rmse: 0.6177 - smape: 0.8625 - val_ia: 0.6472 - val_loss: 0.1035 - val_mae: 0.2096 - val_rmse: 0.2740 - val_smape: 0.4927

Epoch 43/128

958/958 - 5s - 5ms/step - ia: 0.6789 - loss: 0.3816 - mae: 0.4533 - rmse: 0.6049 - smape: 0.8537 - val_ia: 0.6459 - val_loss: 0.1035 - val_mae: 0.2103 - val_rmse: 0.2744 - val_smape: 0.4940

Epoch 44/128

958/958 - 3s - 3ms/step - ia: 0.6814 - loss: 0.3820 - mae: 0.4502 - rmse: 0.6051 - smape: 0.8469 - val_ia: 0.6540 - val_loss: 0.1002 - val_mae: 0.2054 - val_rmse: 0.2698 - val_smape: 0.4859

Epoch 45/128

958/958 - 5s - 5ms/step - ia: 0.6886 - loss: 0.3593 - mae: 0.4394 - rmse: 0.5870 - smape: 0.8351 - val_ia: 0.6574 - val_loss: 0.0984 - val_mae: 0.2034 - val_rmse: 0.2679 - val_smape: 0.4835

Epoch 46/128

958/958 - 5s - 5ms/step - ia: 0.6890 - loss: 0.3641 - mae: 0.4382 - rmse: 0.5885 - smape: 0.8308 - val_ia: 0.6587 - val_loss: 0.0978 - val_mae: 0.2028 - val_rmse: 0.2668 - val_smape: 0.4811

Epoch 47/128

958/958 - 2s - 3ms/step - ia: 0.6935 - loss: 0.3494 - mae: 0.4314 - rmse: 0.5789 - smape: 0.8301 - val_ia: 0.6662 - val_loss: 0.0953 - val_mae: 0.1984 - val_rmse: 0.2630 - val_smape: 0.4746

Epoch 48/128

958/958 - 2s - 3ms/step - ia: 0.6941 - loss: 0.3487 - mae: 0.4290 - rmse: 0.5774 - smape: 0.8245 - val_ia: 0.6634 - val_loss: 0.0961 - val_mae: 0.2001 - val_rmse: 0.2646 - val_smape: 0.4781

Epoch 49/128

958/958 - 3s - 3ms/step - ia: 0.7020 - loss: 0.3316 - mae: 0.4198 - rmse: 0.5622 - smape: 0.8113 - val_ia: 0.6682 - val_loss: 0.0940 - val_mae: 0.1970 - val_rmse: 0.2611 - val_smape: 0.4707

Epoch 50/128

958/958 - 3s - 3ms/step - ia: 0.7034 - loss: 0.3267 - mae: 0.4157 - rmse: 0.5598 - smape: 0.8059 - val_ia: 0.6648 - val_loss: 0.0946 - val_mae: 0.1987 - val_rmse: 0.2622 - val_smape: 0.4731

Epoch 51/128

958/958 - 3s - 3ms/step - ia: 0.7080 - loss: 0.3177 - mae: 0.4088 - rmse: 0.5507 - smape: 0.7995 - val_ia: 0.6670 - val_loss: 0.0937 - val_mae: 0.1975 - val_rmse: 0.2609 - val_smape: 0.4712

Epoch 52/128

958/958 - 2s - 2ms/step - ia: 0.7096 - loss: 0.3152 - mae: 0.4062 - rmse: 0.5480 - smape: 0.7919 - val_ia: 0.6707 - val_loss: 0.0921 - val_mae: 0.1951 - val_rmse: 0.2588 - val_smape: 0.4679

Epoch 53/128

958/958 - 3s - 3ms/step - ia: 0.7149 - loss: 0.3023 - mae: 0.3978 - rmse: 0.5365 - smape: 0.7852 - val_ia: 0.6777 - val_loss: 0.0899 - val_mae: 0.1914 - val_rmse: 0.2554 - val_smape: 0.4613

Epoch 54/128

958/958 - 3s - 3ms/step - ia: 0.7176 - loss: 0.3013 - mae: 0.3960 - rmse: 0.5350 - smape: 0.7810 - val_ia: 0.6726 - val_loss: 0.0908 - val_mae: 0.1938 - val_rmse: 0.2570 - val_smape: 0.4643

Epoch 55/128

958/958 - 2s - 3ms/step - ia: 0.7213 - loss: 0.2891 - mae: 0.3894 - rmse: 0.5253 - smape: 0.7717 - val_ia: 0.6831 - val_loss: 0.0876 - val_mae: 0.1881 - val_rmse: 0.2524 - val_smape: 0.4569

Epoch 56/128

958/958 - 3s - 3ms/step - ia: 0.7241 - loss: 0.2873 - mae: 0.3863 - rmse: 0.5236 - smape: 0.7642 - val_ia: 0.6780 - val_loss: 0.0886 - val_mae: 0.1906 - val_rmse: 0.2543 - val_smape: 0.4602

Epoch 57/128

958/958 - 5s - 5ms/step - ia: 0.7247 - loss: 0.2864 - mae: 0.3842 - rmse: 0.5220 - smape: 0.7630 - val_ia: 0.6821 - val_loss: 0.0878 - val_mae: 0.1889 - val_rmse: 0.2525 - val_smape: 0.4562

Epoch 58/128

958/958 - 3s - 3ms/step - ia: 0.7281 - loss: 0.2763 - mae: 0.3784 - rmse: 0.5128 - smape: 0.7540 - val_ia: 0.6845 - val_loss: 0.0866 - val_mae: 0.1874 - val_rmse: 0.2508 - val_smape: 0.4535

Epoch 59/128

958/958 - 3s - 3ms/step - ia: 0.7344 - loss: 0.2674 - mae: 0.3718 - rmse: 0.5044 - smape: 0.7423 - val_ia: 0.6864 - val_loss: 0.0857 - val_mae: 0.1860 - val_rmse: 0.2498 - val_smape: 0.4520

Epoch 60/128

958/958 - 2s - 3ms/step - ia: 0.7347 - loss: 0.2643 - mae: 0.3692 - rmse: 0.5015 - smape: 0.7412 - val_ia: 0.6876 - val_loss: 0.0853 - val_mae: 0.1853 - val_rmse: 0.2488 - val_smape: 0.4491

Epoch 61/128

958/958 - 2s - 2ms/step - ia: 0.7353 - loss: 0.2638 - mae: 0.3676 - rmse: 0.5004 - smape: 0.7362 - val_ia: 0.6905 - val_loss: 0.0843 - val_mae: 0.1838 - val_rmse: 0.2475 - val_smape: 0.4476

Epoch 62/128

958/958 - 3s - 3ms/step - ia: 0.7395 - loss: 0.2585 - mae: 0.3634 - rmse: 0.4950 - smape: 0.7318 - val_ia: 0.6918 - val_loss: 0.0835 - val_mae: 0.1829 - val_rmse: 0.2465 - val_smape: 0.4458

Epoch 63/128

958/958 - 3s - 3ms/step - ia: 0.7418 - loss: 0.2531 - mae: 0.3597 - rmse: 0.4894 - smape: 0.7257 - val_ia: 0.6894 - val_loss: 0.0840 - val_mae: 0.1839 - val_rmse: 0.2470 - val_smape: 0.4456

Epoch 64/128

958/958 - 3s - 3ms/step - ia: 0.7425 - loss: 0.2476 - mae: 0.3571 - rmse: 0.4847 - smape: 0.7252 - val_ia: 0.6967 - val_loss: 0.0818 - val_mae: 0.1800 - val_rmse: 0.2437 - val_smape: 0.4401

Epoch 65/128

958/958 - 3s - 3ms/step - ia: 0.7465 - loss: 0.2434 - mae: 0.3533 - rmse: 0.4809 - smape: 0.7185 - val_ia: 0.6906 - val_loss: 0.0834 - val_mae: 0.1833 - val_rmse: 0.2465 - val_smape: 0.4454

Epoch 66/128

958/958 - 3s - 3ms/step - ia: 0.7491 - loss: 0.2397 - mae: 0.3490 - rmse: 0.4761 - smape: 0.7122 - val_ia: 0.7004 - val_loss: 0.0806 - val_mae: 0.1782 - val_rmse: 0.2418 - val_smape: 0.4369

Epoch 67/128

958/958 - 3s - 3ms/step - ia: 0.7487 - loss: 0.2393 - mae: 0.3490 - rmse: 0.4758 - smape: 0.7126 - val_ia: 0.6998 - val_loss: 0.0807 - val_mae: 0.1785 - val_rmse: 0.2419 - val_smape: 0.4368

Epoch 68/128

958/958 - 3s - 3ms/step - ia: 0.7526 - loss: 0.2350 - mae: 0.3443 - rmse: 0.4709 - smape: 0.7065 - val_ia: 0.6905 - val_loss: 0.0831 - val_mae: 0.1832 - val_rmse: 0.2455 - val_smape: 0.4425

Epoch 69/128

958/958 - 5s - 5ms/step - ia: 0.7531 - loss: 0.2325 - mae: 0.3425 - rmse: 0.4684 - smape: 0.7029 - val_ia: 0.7047 - val_loss: 0.0793 - val_mae: 0.1759 - val_rmse: 0.2395 - val_smape: 0.4326

Epoch 70/128

958/958 - 5s - 5ms/step - ia: 0.7562 - loss: 0.2271 - mae: 0.3388 - rmse: 0.4639 - smape: 0.6956 - val_ia: 0.7038 - val_loss: 0.0792 - val_mae: 0.1762 - val_rmse: 0.2395 - val_smape: 0.4329

Epoch 71/128

958/958 - 5s - 6ms/step - ia: 0.7599 - loss: 0.2183 - mae: 0.3339 - rmse: 0.4554 - smape: 0.6916 - val_ia: 0.7049 - val_loss: 0.0789 - val_mae: 0.1755 - val_rmse: 0.2389 - val_smape: 0.4313

Epoch 72/128

958/958 - 5s - 5ms/step - ia: 0.7589 - loss: 0.2256 - mae: 0.3346 - rmse: 0.4597 - smape: 0.6868 - val_ia: 0.7060 - val_loss: 0.0781 - val_mae: 0.1746 - val_rmse: 0.2379 - val_smape: 0.4302

Epoch 73/128

958/958 - 2s - 2ms/step - ia: 0.7618 - loss: 0.2188 - mae: 0.3308 - rmse: 0.4539 - smape: 0.6826 - val_ia: 0.7087 - val_loss: 0.0773 - val_mae: 0.1730 - val_rmse: 0.2367 - val_smape: 0.4277

Epoch 74/128

958/958 - 2s - 2ms/step - ia: 0.7632 - loss: 0.2164 - mae: 0.3290 - rmse: 0.4509 - smape: 0.6813 - val_ia: 0.7042 - val_loss: 0.0783 - val_mae: 0.1753 - val_rmse: 0.2382 - val_smape: 0.4304

Epoch 75/128

958/958 - 2s - 2ms/step - ia: 0.7632 - loss: 0.2143 - mae: 0.3285 - rmse: 0.4496 - smape: 0.6787 - val_ia: 0.7104 - val_loss: 0.0770 - val_mae: 0.1724 - val_rmse: 0.2363 - val_smape: 0.4272

Epoch 76/128

958/958 - 3s - 3ms/step - ia: 0.7668 - loss: 0.2133 - mae: 0.3236 - rmse: 0.4463 - smape: 0.6726 - val_ia: 0.7105 - val_loss: 0.0769 - val_mae: 0.1722 - val_rmse: 0.2358 - val_smape: 0.4257

Epoch 77/128

958/958 - 3s - 3ms/step - ia: 0.7673 - loss: 0.2083 - mae: 0.3225 - rmse: 0.4430 - smape: 0.6708 - val_ia: 0.7108 - val_loss: 0.0763 - val_mae: 0.1717 - val_rmse: 0.2352 - val_smape: 0.4253

Epoch 78/128

958/958 - 5s - 5ms/step - ia: 0.7684 - loss: 0.2075 - mae: 0.3209 - rmse: 0.4414 - smape: 0.6678 - val_ia: 0.7114 - val_loss: 0.0762 - val_mae: 0.1714 - val_rmse: 0.2350 - val_smape: 0.4243

Epoch 79/128

958/958 - 2s - 3ms/step - ia: 0.7712 - loss: 0.2037 - mae: 0.3173 - rmse: 0.4374 - smape: 0.6588 - val_ia: 0.7194 - val_loss: 0.0741 - val_mae: 0.1674 - val_rmse: 0.2315 - val_smape: 0.4187

Epoch 80/128

958/958 - 3s - 3ms/step - ia: 0.7741 - loss: 0.1993 - mae: 0.3140 - rmse: 0.4326 - smape: 0.6507 - val_ia: 0.7162 - val_loss: 0.0744 - val_mae: 0.1687 - val_rmse: 0.2321 - val_smape: 0.4203

Epoch 81/128

958/958 - 5s - 5ms/step - ia: 0.7726 - loss: 0.2014 - mae: 0.3145 - rmse: 0.4347 - smape: 0.6524 - val_ia: 0.7224 - val_loss: 0.0731 - val_mae: 0.1656 - val_rmse: 0.2296 - val_smape: 0.4158

Epoch 82/128

958/958 - 3s - 3ms/step - ia: 0.7770 - loss: 0.1935 - mae: 0.3092 - rmse: 0.4268 - smape: 0.6491 - val_ia: 0.7109 - val_loss: 0.0759 - val_mae: 0.1714 - val_rmse: 0.2344 - val_smape: 0.4229

Epoch 83/128

958/958 - 3s - 3ms/step - ia: 0.7760 - loss: 0.1942 - mae: 0.3105 - rmse: 0.4285 - smape: 0.6497 - val_ia: 0.7155 - val_loss: 0.0742 - val_mae: 0.1688 - val_rmse: 0.2317 - val_smape: 0.4200

Epoch 84/128

958/958 - 5s - 5ms/step - ia: 0.7789 - loss: 0.1911 - mae: 0.3062 - rmse: 0.4232 - smape: 0.6443 - val_ia: 0.7139 - val_loss: 0.0750 - val_mae: 0.1699 - val_rmse: 0.2331 - val_smape: 0.4210

Epoch 85/128

958/958 - 2s - 2ms/step - ia: 0.7794 - loss: 0.1892 - mae: 0.3050 - rmse: 0.4215 - smape: 0.6414 - val_ia: 0.7115 - val_loss: 0.0757 - val_mae: 0.1711 - val_rmse: 0.2341 - val_smape: 0.4219

Epoch 86/128

958/958 - 3s - 3ms/step - ia: 0.7800 - loss: 0.1886 - mae: 0.3043 - rmse: 0.4218 - smape: 0.6399 - val_ia: 0.7143 - val_loss: 0.0744 - val_mae: 0.1695 - val_rmse: 0.2319 - val_smape: 0.4198

Epoch 87/128

958/958 - 3s - 3ms/step - ia: 0.7819 - loss: 0.1885 - mae: 0.3028 - rmse: 0.4191 - smape: 0.6380 - val_ia: 0.7225 - val_loss: 0.0724 - val_mae: 0.1653 - val_rmse: 0.2287 - val_smape: 0.4143

Epoch 88/128

958/958 - 2s - 3ms/step - ia: 0.7833 - loss: 0.1831 - mae: 0.3001 - rmse: 0.4139 - smape: 0.6304 - val_ia: 0.7255 - val_loss: 0.0717 - val_mae: 0.1637 - val_rmse: 0.2273 - val_smape: 0.4117

Epoch 89/128

958/958 - 3s - 3ms/step - ia: 0.7844 - loss: 0.1850 - mae: 0.2991 - rmse: 0.4146 - smape: 0.6318 - val_ia: 0.7227 - val_loss: 0.0723 - val_mae: 0.1650 - val_rmse: 0.2285 - val_smape: 0.4131

Epoch 90/128

958/958 - 5s - 5ms/step - ia: 0.7840 - loss: 0.1827 - mae: 0.2988 - rmse: 0.4135 - smape: 0.6276 - val_ia: 0.7247 - val_loss: 0.0719 - val_mae: 0.1642 - val_rmse: 0.2276 - val_smape: 0.4117

Epoch 91/128

958/958 - 3s - 3ms/step - ia: 0.7878 - loss: 0.1784 - mae: 0.2942 - rmse: 0.4081 - smape: 0.6240 - val_ia: 0.7292 - val_loss: 0.0711 - val_mae: 0.1621 - val_rmse: 0.2264 - val_smape: 0.4087

Epoch 92/128

958/958 - 5s - 6ms/step - ia: 0.7883 - loss: 0.1753 - mae: 0.2939 - rmse: 0.4066 - smape: 0.6179 - val_ia: 0.7299 - val_loss: 0.0706 - val_mae: 0.1616 - val_rmse: 0.2253 - val_smape: 0.4076

Epoch 93/128

958/958 - 5s - 5ms/step - ia: 0.7875 - loss: 0.1805 - mae: 0.2949 - rmse: 0.4106 - smape: 0.6185 - val_ia: 0.7214 - val_loss: 0.0725 - val_mae: 0.1656 - val_rmse: 0.2286 - val_smape: 0.4124

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.7909 - loss: 0.1744 - mae: 0.2901 - rmse: 0.4038 - smape: 0.6140 - val_ia: 0.7255 - val_loss: 0.0714 - val_mae: 0.1637 - val_rmse: 0.2268 - val_smape: 0.4098

Epoch 95/128

958/958 - 3s - 3ms/step - ia: 0.7914 - loss: 0.1735 - mae: 0.2895 - rmse: 0.4024 - smape: 0.6116 - val_ia: 0.7239 - val_loss: 0.0716 - val_mae: 0.1641 - val_rmse: 0.2273 - val_smape: 0.4105

Epoch 96/128

958/958 - 3s - 3ms/step - ia: 0.7921 - loss: 0.1724 - mae: 0.2883 - rmse: 0.4014 - smape: 0.6139 - val_ia: 0.7298 - val_loss: 0.0702 - val_mae: 0.1612 - val_rmse: 0.2249 - val_smape: 0.4065

Epoch 97/128

958/958 - 3s - 3ms/step - ia: 0.7923 - loss: 0.1706 - mae: 0.2873 - rmse: 0.3994 - smape: 0.6093 - val_ia: 0.7273 - val_loss: 0.0704 - val_mae: 0.1621 - val_rmse: 0.2255 - val_smape: 0.4072

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 6s - 12ms/step - ia: 0.3136 - loss: 1.6583 - mae: 0.9707 - rmse: 1.2786 - smape: 1.3972 - val_ia: 0.3024 - val_loss: 1.5389 - val_mae: 0.9347 - val_rmse: 1.1072 - val_smape: 1.4490

Epoch 2/128

479/479 - 1s - 3ms/step - ia: 0.3221 - loss: 1.5699 - mae: 0.9462 - rmse: 1.2441 - smape: 1.3866 - val_ia: 0.3107 - val_loss: 1.4221 - val_mae: 0.8956 - val_rmse: 1.0653 - val_smape: 1.4320

Epoch 3/128

479/479 - 1s - 2ms/step - ia: 0.3316 - loss: 1.4925 - mae: 0.9244 - rmse: 1.2125 - smape: 1.3766 - val_ia: 0.3192 - val_loss: 1.3167 - val_mae: 0.8592 - val_rmse: 1.0260 - val_smape: 1.4119

Epoch 4/128

479/479 - 1s - 3ms/step - ia: 0.3436 - loss: 1.4265 - mae: 0.8991 - rmse: 1.1840 - smape: 1.3577 - val_ia: 0.3279 - val_loss: 1.2236 - val_mae: 0.8261 - val_rmse: 0.9900 - val_smape: 1.3904

Epoch 5/128

479/479 - 1s - 3ms/step - ia: 0.3544 - loss: 1.3463 - mae: 0.8754 - rmse: 1.1513 - smape: 1.3488 - val_ia: 0.3365 - val_loss: 1.1421 - val_mae: 0.7961 - val_rmse: 0.9574 - val_smape: 1.3675

Epoch 6/128

479/479 - 2s - 5ms/step - ia: 0.3670 - loss: 1.2924 - mae: 0.8545 - rmse: 1.1273 - smape: 1.3291 - val_ia: 0.3453 - val_loss: 1.0676 - val_mae: 0.7679 - val_rmse: 0.9265 - val_smape: 1.3426

Epoch 7/128

479/479 - 1s - 3ms/step - ia: 0.3824 - loss: 1.2307 - mae: 0.8355 - rmse: 1.0998 - smape: 1.3075 - val_ia: 0.3539 - val_loss: 1.0010 - val_mae: 0.7419 - val_rmse: 0.8980 - val_smape: 1.3176

Epoch 8/128

479/479 - 1s - 3ms/step - ia: 0.3934 - loss: 1.1764 - mae: 0.8166 - rmse: 1.0740 - smape: 1.2956 - val_ia: 0.3626 - val_loss: 0.9403 - val_mae: 0.7175 - val_rmse: 0.8710 - val_smape: 1.2921

Epoch 9/128

479/479 - 1s - 3ms/step - ia: 0.4031 - loss: 1.1297 - mae: 0.8018 - rmse: 1.0537 - smape: 1.2827 - val_ia: 0.3716 - val_loss: 0.8859 - val_mae: 0.6948 - val_rmse: 0.8461 - val_smape: 1.2656

Epoch 10/128

479/479 - 1s - 2ms/step - ia: 0.4178 - loss: 1.0801 - mae: 0.7834 - rmse: 1.0296 - smape: 1.2615 - val_ia: 0.3805 - val_loss: 0.8358 - val_mae: 0.6735 - val_rmse: 0.8226 - val_smape: 1.2391

Epoch 11/128

479/479 - 1s - 3ms/step - ia: 0.4340 - loss: 1.0311 - mae: 0.7642 - rmse: 1.0064 - smape: 1.2392 - val_ia: 0.3892 - val_loss: 0.7905 - val_mae: 0.6537 - val_rmse: 0.8005 - val_smape: 1.2142

Epoch 12/128

479/479 - 1s - 3ms/step - ia: 0.4409 - loss: 1.0020 - mae: 0.7539 - rmse: 0.9927 - smape: 1.2289 - val_ia: 0.3980 - val_loss: 0.7491 - val_mae: 0.6351 - val_rmse: 0.7799 - val_smape: 1.1881

Epoch 13/128

479/479 - 1s - 3ms/step - ia: 0.4576 - loss: 0.9547 - mae: 0.7347 - rmse: 0.9694 - smape: 1.2041 - val_ia: 0.4067 - val_loss: 0.7127 - val_mae: 0.6185 - val_rmse: 0.7612 - val_smape: 1.1633

Epoch 14/128

479/479 - 1s - 2ms/step - ia: 0.4676 - loss: 0.9249 - mae: 0.7216 - rmse: 0.9535 - smape: 1.1884 - val_ia: 0.4152 - val_loss: 0.6778 - val_mae: 0.6021 - val_rmse: 0.7428 - val_smape: 1.1391

Epoch 15/128

479/479 - 1s - 2ms/step - ia: 0.4762 - loss: 0.8991 - mae: 0.7124 - rmse: 0.9389 - smape: 1.1778 - val_ia: 0.4235 - val_loss: 0.6462 - val_mae: 0.5869 - val_rmse: 0.7257 - val_smape: 1.1160

Epoch 16/128

479/479 - 2s - 3ms/step - ia: 0.4889 - loss: 0.8632 - mae: 0.6982 - rmse: 0.9200 - smape: 1.1612 - val_ia: 0.4316 - val_loss: 0.6175 - val_mae: 0.5727 - val_rmse: 0.7098 - val_smape: 1.0935

Epoch 17/128

479/479 - 1s - 2ms/step - ia: 0.4961 - loss: 0.8459 - mae: 0.6912 - rmse: 0.9105 - smape: 1.1504 - val_ia: 0.4397 - val_loss: 0.5912 - val_mae: 0.5594 - val_rmse: 0.6950 - val_smape: 1.0732

Epoch 18/128

479/479 - 1s - 2ms/step - ia: 0.5062 - loss: 0.8155 - mae: 0.6790 - rmse: 0.8948 - smape: 1.1345 - val_ia: 0.4478 - val_loss: 0.5673 - val_mae: 0.5470 - val_rmse: 0.6811 - val_smape: 1.0537

Epoch 19/128

479/479 - 1s - 2ms/step - ia: 0.5147 - loss: 0.8036 - mae: 0.6724 - rmse: 0.8871 - smape: 1.1219 - val_ia: 0.4557 - val_loss: 0.5458 - val_mae: 0.5355 - val_rmse: 0.6684 - val_smape: 1.0349

Epoch 20/128

479/479 - 1s - 3ms/step - ia: 0.5225 - loss: 0.7794 - mae: 0.6650 - rmse: 0.8734 - smape: 1.1110 - val_ia: 0.4634 - val_loss: 0.5257 - val_mae: 0.5246 - val_rmse: 0.6562 - val_smape: 1.0160

Epoch 21/128

479/479 - 1s - 3ms/step - ia: 0.5317 - loss: 0.7607 - mae: 0.6527 - rmse: 0.8635 - smape: 1.0938 - val_ia: 0.4707 - val_loss: 0.5071 - val_mae: 0.5142 - val_rmse: 0.6447 - val_smape: 0.9979

Epoch 22/128

479/479 - 3s - 6ms/step - ia: 0.5378 - loss: 0.7409 - mae: 0.6471 - rmse: 0.8530 - smape: 1.0860 - val_ia: 0.4777 - val_loss: 0.4901 - val_mae: 0.5047 - val_rmse: 0.6341 - val_smape: 0.9806

Epoch 23/128

479/479 - 1s - 3ms/step - ia: 0.5443 - loss: 0.7301 - mae: 0.6411 - rmse: 0.8459 - smape: 1.0795 - val_ia: 0.4843 - val_loss: 0.4748 - val_mae: 0.4959 - val_rmse: 0.6243 - val_smape: 0.9647

Epoch 24/128

479/479 - 1s - 2ms/step - ia: 0.5514 - loss: 0.7120 - mae: 0.6330 - rmse: 0.8354 - smape: 1.0670 - val_ia: 0.4906 - val_loss: 0.4609 - val_mae: 0.4879 - val_rmse: 0.6153 - val_smape: 0.9495

Epoch 25/128

479/479 - 1s - 3ms/step - ia: 0.5574 - loss: 0.6970 - mae: 0.6264 - rmse: 0.8270 - smape: 1.0563 - val_ia: 0.4966 - val_loss: 0.4481 - val_mae: 0.4804 - val_rmse: 0.6069 - val_smape: 0.9356

Epoch 26/128

479/479 - 1s - 3ms/step - ia: 0.5658 - loss: 0.6731 - mae: 0.6160 - rmse: 0.8123 - smape: 1.0453 - val_ia: 0.5021 - val_loss: 0.4362 - val_mae: 0.4733 - val_rmse: 0.5988 - val_smape: 0.9218

Epoch 27/128

479/479 - 1s - 3ms/step - ia: 0.5708 - loss: 0.6664 - mae: 0.6115 - rmse: 0.8082 - smape: 1.0334 - val_ia: 0.5075 - val_loss: 0.4250 - val_mae: 0.4665 - val_rmse: 0.5912 - val_smape: 0.9086

Epoch 28/128

479/479 - 2s - 3ms/step - ia: 0.5735 - loss: 0.6604 - mae: 0.6084 - rmse: 0.8050 - smape: 1.0295 - val_ia: 0.5125 - val_loss: 0.4144 - val_mae: 0.4601 - val_rmse: 0.5838 - val_smape: 0.8966

Epoch 29/128

479/479 - 2s - 5ms/step - ia: 0.5788 - loss: 0.6444 - mae: 0.6042 - rmse: 0.7950 - smape: 1.0204 - val_ia: 0.5172 - val_loss: 0.4049 - val_mae: 0.4543 - val_rmse: 0.5770 - val_smape: 0.8858

Epoch 30/128

479/479 - 1s - 2ms/step - ia: 0.5849 - loss: 0.6308 - mae: 0.5964 - rmse: 0.7859 - smape: 1.0099 - val_ia: 0.5216 - val_loss: 0.3960 - val_mae: 0.4488 - val_rmse: 0.5706 - val_smape: 0.8757

Epoch 31/128

479/479 - 1s - 3ms/step - ia: 0.5873 - loss: 0.6244 - mae: 0.5925 - rmse: 0.7830 - smape: 1.0043 - val_ia: 0.5260 - val_loss: 0.3877 - val_mae: 0.4437 - val_rmse: 0.5646 - val_smape: 0.8667

Epoch 32/128

479/479 - 3s - 5ms/step - ia: 0.5916 - loss: 0.6129 - mae: 0.5869 - rmse: 0.7750 - smape: 1.0016 - val_ia: 0.5301 - val_loss: 0.3800 - val_mae: 0.4388 - val_rmse: 0.5588 - val_smape: 0.8575

Epoch 33/128

479/479 - 3s - 5ms/step - ia: 0.5984 - loss: 0.5977 - mae: 0.5774 - rmse: 0.7650 - smape: 0.9870 - val_ia: 0.5339 - val_loss: 0.3729 - val_mae: 0.4343 - val_rmse: 0.5535 - val_smape: 0.8501

Epoch 34/128

479/479 - 1s - 2ms/step - ia: 0.5979 - loss: 0.5992 - mae: 0.5797 - rmse: 0.7665 - smape: 0.9928 - val_ia: 0.5377 - val_loss: 0.3657 - val_mae: 0.4296 - val_rmse: 0.5480 - val_smape: 0.8419

Epoch 35/128

479/479 - 1s - 3ms/step - ia: 0.5996 - loss: 0.5954 - mae: 0.5780 - rmse: 0.7642 - smape: 0.9877 - val_ia: 0.5413 - val_loss: 0.3587 - val_mae: 0.4250 - val_rmse: 0.5425 - val_smape: 0.8345

Epoch 36/128

479/479 - 1s - 3ms/step - ia: 0.6044 - loss: 0.5785 - mae: 0.5705 - rmse: 0.7527 - smape: 0.9799 - val_ia: 0.5449 - val_loss: 0.3521 - val_mae: 0.4207 - val_rmse: 0.5373 - val_smape: 0.8276

Epoch 37/128

479/479 - 3s - 6ms/step - ia: 0.6069 - loss: 0.5737 - mae: 0.5663 - rmse: 0.7495 - smape: 0.9778 - val_ia: 0.5483 - val_loss: 0.3460 - val_mae: 0.4167 - val_rmse: 0.5325 - val_smape: 0.8211

Epoch 38/128

479/479 - 1s - 3ms/step - ia: 0.6115 - loss: 0.5680 - mae: 0.5620 - rmse: 0.7458 - smape: 0.9657 - val_ia: 0.5515 - val_loss: 0.3401 - val_mae: 0.4126 - val_rmse: 0.5277 - val_smape: 0.8147

Epoch 39/128

479/479 - 1s - 3ms/step - ia: 0.6156 - loss: 0.5570 - mae: 0.5560 - rmse: 0.7385 - smape: 0.9622 - val_ia: 0.5547 - val_loss: 0.3346 - val_mae: 0.4088 - val_rmse: 0.5232 - val_smape: 0.8086

Epoch 40/128

479/479 - 1s - 3ms/step - ia: 0.6141 - loss: 0.5534 - mae: 0.5584 - rmse: 0.7361 - smape: 0.9640 - val_ia: 0.5580 - val_loss: 0.3295 - val_mae: 0.4052 - val_rmse: 0.5188 - val_smape: 0.8024

Epoch 41/128

479/479 - 1s - 2ms/step - ia: 0.6199 - loss: 0.5418 - mae: 0.5499 - rmse: 0.7285 - smape: 0.9528 - val_ia: 0.5612 - val_loss: 0.3241 - val_mae: 0.4013 - val_rmse: 0.5143 - val_smape: 0.7957

Epoch 42/128

479/479 - 1s - 3ms/step - ia: 0.6219 - loss: 0.5396 - mae: 0.5475 - rmse: 0.7268 - smape: 0.9495 - val_ia: 0.5643 - val_loss: 0.3191 - val_mae: 0.3977 - val_rmse: 0.5100 - val_smape: 0.7897

Epoch 43/128

479/479 - 1s - 2ms/step - ia: 0.6221 - loss: 0.5330 - mae: 0.5465 - rmse: 0.7227 - smape: 0.9491 - val_ia: 0.5675 - val_loss: 0.3143 - val_mae: 0.3940 - val_rmse: 0.5058 - val_smape: 0.7840

Epoch 44/128

479/479 - 1s - 2ms/step - ia: 0.6278 - loss: 0.5291 - mae: 0.5410 - rmse: 0.7188 - smape: 0.9365 - val_ia: 0.5705 - val_loss: 0.3093 - val_mae: 0.3903 - val_rmse: 0.5013 - val_smape: 0.7772

Epoch 45/128

479/479 - 1s - 2ms/step - ia: 0.6291 - loss: 0.5214 - mae: 0.5392 - rmse: 0.7136 - smape: 0.9377 - val_ia: 0.5736 - val_loss: 0.3048 - val_mae: 0.3868 - val_rmse: 0.4973 - val_smape: 0.7711

Epoch 46/128

479/479 - 1s - 2ms/step - ia: 0.6321 - loss: 0.5145 - mae: 0.5336 - rmse: 0.7085 - smape: 0.9329 - val_ia: 0.5765 - val_loss: 0.3005 - val_mae: 0.3835 - val_rmse: 0.4935 - val_smape: 0.7656

Epoch 47/128

479/479 - 1s - 2ms/step - ia: 0.6331 - loss: 0.5075 - mae: 0.5315 - rmse: 0.7046 - smape: 0.9293 - val_ia: 0.5795 - val_loss: 0.2964 - val_mae: 0.3802 - val_rmse: 0.4897 - val_smape: 0.7601

Epoch 48/128

479/479 - 2s - 3ms/step - ia: 0.6363 - loss: 0.5015 - mae: 0.5269 - rmse: 0.7004 - smape: 0.9274 - val_ia: 0.5824 - val_loss: 0.2923 - val_mae: 0.3770 - val_rmse: 0.4859 - val_smape: 0.7544

Epoch 49/128

479/479 - 1s - 3ms/step - ia: 0.6377 - loss: 0.4996 - mae: 0.5265 - rmse: 0.6988 - smape: 0.9258 - val_ia: 0.5853 - val_loss: 0.2885 - val_mae: 0.3738 - val_rmse: 0.4823 - val_smape: 0.7493

Epoch 50/128

479/479 - 1s - 2ms/step - ia: 0.6402 - loss: 0.4936 - mae: 0.5214 - rmse: 0.6947 - smape: 0.9180 - val_ia: 0.5882 - val_loss: 0.2847 - val_mae: 0.3707 - val_rmse: 0.4787 - val_smape: 0.7443

Epoch 51/128

479/479 - 1s - 2ms/step - ia: 0.6428 - loss: 0.4842 - mae: 0.5164 - rmse: 0.6876 - smape: 0.9138 - val_ia: 0.5911 - val_loss: 0.2809 - val_mae: 0.3676 - val_rmse: 0.4751 - val_smape: 0.7391

Epoch 52/128

479/479 - 1s - 3ms/step - ia: 0.6423 - loss: 0.4882 - mae: 0.5173 - rmse: 0.6908 - smape: 0.9120 - val_ia: 0.5940 - val_loss: 0.2773 - val_mae: 0.3645 - val_rmse: 0.4717 - val_smape: 0.7342

Epoch 53/128

479/479 - 1s - 3ms/step - ia: 0.6444 - loss: 0.4804 - mae: 0.5146 - rmse: 0.6853 - smape: 0.9110 - val_ia: 0.5968 - val_loss: 0.2738 - val_mae: 0.3616 - val_rmse: 0.4683 - val_smape: 0.7292

Epoch 54/128

479/479 - 1s - 3ms/step - ia: 0.6503 - loss: 0.4717 - mae: 0.5065 - rmse: 0.6781 - smape: 0.9006 - val_ia: 0.5996 - val_loss: 0.2703 - val_mae: 0.3587 - val_rmse: 0.4648 - val_smape: 0.7239

Epoch 55/128

479/479 - 1s - 3ms/step - ia: 0.6527 - loss: 0.4645 - mae: 0.5034 - rmse: 0.6736 - smape: 0.8944 - val_ia: 0.6023 - val_loss: 0.2669 - val_mae: 0.3558 - val_rmse: 0.4615 - val_smape: 0.7190

Epoch 56/128

479/479 - 3s - 5ms/step - ia: 0.6535 - loss: 0.4586 - mae: 0.5007 - rmse: 0.6699 - smape: 0.8927 - val_ia: 0.6049 - val_loss: 0.2637 - val_mae: 0.3531 - val_rmse: 0.4583 - val_smape: 0.7144

Epoch 57/128

479/479 - 2s - 3ms/step - ia: 0.6541 - loss: 0.4552 - mae: 0.4998 - rmse: 0.6663 - smape: 0.8939 - val_ia: 0.6076 - val_loss: 0.2606 - val_mae: 0.3504 - val_rmse: 0.4552 - val_smape: 0.7099

Epoch 58/128

479/479 - 2s - 5ms/step - ia: 0.6575 - loss: 0.4532 - mae: 0.4950 - rmse: 0.6641 - smape: 0.8818 - val_ia: 0.6102 - val_loss: 0.2576 - val_mae: 0.3478 - val_rmse: 0.4521 - val_smape: 0.7058

Epoch 59/128

479/479 - 1s - 3ms/step - ia: 0.6584 - loss: 0.4504 - mae: 0.4944 - rmse: 0.6625 - smape: 0.8869 - val_ia: 0.6129 - val_loss: 0.2545 - val_mae: 0.3451 - val_rmse: 0.4491 - val_smape: 0.7016

Epoch 60/128

479/479 - 1s - 2ms/step - ia: 0.6577 - loss: 0.4500 - mae: 0.4952 - rmse: 0.6628 - smape: 0.8854 - val_ia: 0.6154 - val_loss: 0.2516 - val_mae: 0.3425 - val_rmse: 0.4461 - val_smape: 0.6975

Epoch 61/128

479/479 - 1s - 3ms/step - ia: 0.6606 - loss: 0.4411 - mae: 0.4913 - rmse: 0.6563 - smape: 0.8828 - val_ia: 0.6181 - val_loss: 0.2489 - val_mae: 0.3399 - val_rmse: 0.4431 - val_smape: 0.6937

Epoch 62/128

479/479 - 1s - 3ms/step - ia: 0.6612 - loss: 0.4440 - mae: 0.4903 - rmse: 0.6574 - smape: 0.8833 - val_ia: 0.6205 - val_loss: 0.2461 - val_mae: 0.3374 - val_rmse: 0.4401 - val_smape: 0.6895

Epoch 63/128

479/479 - 1s - 3ms/step - ia: 0.6649 - loss: 0.4349 - mae: 0.4832 - rmse: 0.6504 - smape: 0.8723 - val_ia: 0.6231 - val_loss: 0.2434 - val_mae: 0.3350 - val_rmse: 0.4374 - val_smape: 0.6854

Epoch 64/128

479/479 - 1s - 3ms/step - ia: 0.6649 - loss: 0.4349 - mae: 0.4853 - rmse: 0.6513 - smape: 0.8754 - val_ia: 0.6254 - val_loss: 0.2407 - val_mae: 0.3325 - val_rmse: 0.4345 - val_smape: 0.6816

Epoch 65/128

479/479 - 3s - 5ms/step - ia: 0.6681 - loss: 0.4264 - mae: 0.4800 - rmse: 0.6439 - smape: 0.8692 - val_ia: 0.6277 - val_loss: 0.2381 - val_mae: 0.3301 - val_rmse: 0.4317 - val_smape: 0.6773

Epoch 66/128

479/479 - 2s - 5ms/step - ia: 0.6720 - loss: 0.4191 - mae: 0.4737 - rmse: 0.6393 - smape: 0.8604 - val_ia: 0.6301 - val_loss: 0.2357 - val_mae: 0.3279 - val_rmse: 0.4291 - val_smape: 0.6731

Epoch 67/128

479/479 - 1s - 2ms/step - ia: 0.6693 - loss: 0.4199 - mae: 0.4761 - rmse: 0.6392 - smape: 0.8637 - val_ia: 0.6325 - val_loss: 0.2333 - val_mae: 0.3256 - val_rmse: 0.4266 - val_smape: 0.6694

Epoch 68/128

479/479 - 1s - 2ms/step - ia: 0.6726 - loss: 0.4206 - mae: 0.4738 - rmse: 0.6403 - smape: 0.8567 - val_ia: 0.6348 - val_loss: 0.2310 - val_mae: 0.3233 - val_rmse: 0.4239 - val_smape: 0.6660

Epoch 69/128

479/479 - 1s - 3ms/step - ia: 0.6734 - loss: 0.4142 - mae: 0.4718 - rmse: 0.6343 - smape: 0.8601 - val_ia: 0.6369 - val_loss: 0.2287 - val_mae: 0.3213 - val_rmse: 0.4215 - val_smape: 0.6625

Epoch 70/128

479/479 - 1s - 3ms/step - ia: 0.6777 - loss: 0.4067 - mae: 0.4656 - rmse: 0.6284 - smape: 0.8505 - val_ia: 0.6390 - val_loss: 0.2264 - val_mae: 0.3191 - val_rmse: 0.4190 - val_smape: 0.6591

Epoch 71/128

479/479 - 1s - 3ms/step - ia: 0.6792 - loss: 0.4048 - mae: 0.4637 - rmse: 0.6285 - smape: 0.8451 - val_ia: 0.6412 - val_loss: 0.2243 - val_mae: 0.3170 - val_rmse: 0.4166 - val_smape: 0.6557

Epoch 72/128

479/479 - 2s - 5ms/step - ia: 0.6786 - loss: 0.4045 - mae: 0.4638 - rmse: 0.6272 - smape: 0.8484 - val_ia: 0.6434 - val_loss: 0.2222 - val_mae: 0.3151 - val_rmse: 0.4144 - val_smape: 0.6521

Epoch 73/128

479/479 - 1s - 3ms/step - ia: 0.6798 - loss: 0.4037 - mae: 0.4638 - rmse: 0.6261 - smape: 0.8444 - val_ia: 0.6454 - val_loss: 0.2202 - val_mae: 0.3130 - val_rmse: 0.4120 - val_smape: 0.6483

Epoch 74/128

479/479 - 1s - 3ms/step - ia: 0.6808 - loss: 0.3948 - mae: 0.4600 - rmse: 0.6196 - smape: 0.8468 - val_ia: 0.6475 - val_loss: 0.2182 - val_mae: 0.3111 - val_rmse: 0.4098 - val_smape: 0.6447

Epoch 75/128

479/479 - 1s - 3ms/step - ia: 0.6826 - loss: 0.3952 - mae: 0.4578 - rmse: 0.6198 - smape: 0.8411 - val_ia: 0.6494 - val_loss: 0.2162 - val_mae: 0.3092 - val_rmse: 0.4076 - val_smape: 0.6410

Epoch 76/128

479/479 - 1s - 2ms/step - ia: 0.6850 - loss: 0.3918 - mae: 0.4549 - rmse: 0.6169 - smape: 0.8337 - val_ia: 0.6515 - val_loss: 0.2144 - val_mae: 0.3074 - val_rmse: 0.4055 - val_smape: 0.6376

Epoch 77/128

479/479 - 1s - 3ms/step - ia: 0.6880 - loss: 0.3807 - mae: 0.4507 - rmse: 0.6092 - smape: 0.8321 - val_ia: 0.6534 - val_loss: 0.2125 - val_mae: 0.3055 - val_rmse: 0.4033 - val_smape: 0.6340

Epoch 78/128

479/479 - 1s - 3ms/step - ia: 0.6893 - loss: 0.3791 - mae: 0.4483 - rmse: 0.6066 - smape: 0.8273 - val_ia: 0.6549 - val_loss: 0.2107 - val_mae: 0.3039 - val_rmse: 0.4014 - val_smape: 0.6310

Epoch 79/128

479/479 - 1s - 3ms/step - ia: 0.6898 - loss: 0.3814 - mae: 0.4477 - rmse: 0.6088 - smape: 0.8226 - val_ia: 0.6569 - val_loss: 0.2090 - val_mae: 0.3022 - val_rmse: 0.3995 - val_smape: 0.6279

Epoch 80/128

479/479 - 1s - 3ms/step - ia: 0.6883 - loss: 0.3790 - mae: 0.4493 - rmse: 0.6079 - smape: 0.8312 - val_ia: 0.6587 - val_loss: 0.2073 - val_mae: 0.3005 - val_rmse: 0.3975 - val_smape: 0.6248

Epoch 81/128

479/479 - 1s - 3ms/step - ia: 0.6928 - loss: 0.3731 - mae: 0.4430 - rmse: 0.6016 - smape: 0.8227 - val_ia: 0.6604 - val_loss: 0.2057 - val_mae: 0.2988 - val_rmse: 0.3956 - val_smape: 0.6219

Epoch 82/128

479/479 - 1s - 3ms/step - ia: 0.6943 - loss: 0.3685 - mae: 0.4412 - rmse: 0.5994 - smape: 0.8158 - val_ia: 0.6622 - val_loss: 0.2041 - val_mae: 0.2972 - val_rmse: 0.3937 - val_smape: 0.6190

Epoch 83/128

479/479 - 1s - 3ms/step - ia: 0.6920 - loss: 0.3760 - mae: 0.4443 - rmse: 0.6050 - smape: 0.8229 - val_ia: 0.6640 - val_loss: 0.2025 - val_mae: 0.2956 - val_rmse: 0.3919 - val_smape: 0.6161

Epoch 84/128

479/479 - 1s - 3ms/step - ia: 0.6966 - loss: 0.3654 - mae: 0.4381 - rmse: 0.5954 - smape: 0.8147 - val_ia: 0.6656 - val_loss: 0.2010 - val_mae: 0.2942 - val_rmse: 0.3903 - val_smape: 0.6133

Epoch 85/128

479/479 - 1s - 3ms/step - ia: 0.6954 - loss: 0.3688 - mae: 0.4396 - rmse: 0.5983 - smape: 0.8137 - val_ia: 0.6671 - val_loss: 0.1995 - val_mae: 0.2927 - val_rmse: 0.3886 - val_smape: 0.6104

Epoch 86/128

479/479 - 3s - 5ms/step - ia: 0.6979 - loss: 0.3635 - mae: 0.4366 - rmse: 0.5946 - smape: 0.8121 - val_ia: 0.6688 - val_loss: 0.1980 - val_mae: 0.2911 - val_rmse: 0.3868 - val_smape: 0.6074

Epoch 87/128

479/479 - 2s - 5ms/step - ia: 0.6977 - loss: 0.3651 - mae: 0.4365 - rmse: 0.5949 - smape: 0.8130 - val_ia: 0.6706 - val_loss: 0.1966 - val_mae: 0.2895 - val_rmse: 0.3850 - val_smape: 0.6047

Epoch 88/128

479/479 - 1s - 2ms/step - ia: 0.6993 - loss: 0.3634 - mae: 0.4341 - rmse: 0.5937 - smape: 0.8055 - val_ia: 0.6721 - val_loss: 0.1952 - val_mae: 0.2880 - val_rmse: 0.3833 - val_smape: 0.6021

Epoch 89/128

479/479 - 1s - 3ms/step - ia: 0.6989 - loss: 0.3609 - mae: 0.4337 - rmse: 0.5914 - smape: 0.8107 - val_ia: 0.6737 - val_loss: 0.1938 - val_mae: 0.2865 - val_rmse: 0.3816 - val_smape: 0.5994

Epoch 90/128

479/479 - 2s - 3ms/step - ia: 0.7020 - loss: 0.3537 - mae: 0.4298 - rmse: 0.5864 - smape: 0.8038 - val_ia: 0.6750 - val_loss: 0.1925 - val_mae: 0.2852 - val_rmse: 0.3802 - val_smape: 0.5967

Epoch 91/128

479/479 - 2s - 5ms/step - ia: 0.7020 - loss: 0.3521 - mae: 0.4300 - rmse: 0.5844 - smape: 0.8034 - val_ia: 0.6764 - val_loss: 0.1912 - val_mae: 0.2838 - val_rmse: 0.3786 - val_smape: 0.5941

Epoch 92/128

479/479 - 2s - 3ms/step - ia: 0.7031 - loss: 0.3505 - mae: 0.4279 - rmse: 0.5829 - smape: 0.8000 - val_ia: 0.6778 - val_loss: 0.1899 - val_mae: 0.2825 - val_rmse: 0.3771 - val_smape: 0.5917

Epoch 93/128

479/479 - 1s - 3ms/step - ia: 0.7060 - loss: 0.3454 - mae: 0.4239 - rmse: 0.5791 - smape: 0.7983 - val_ia: 0.6792 - val_loss: 0.1887 - val_mae: 0.2813 - val_rmse: 0.3756 - val_smape: 0.5894

Epoch 94/128

479/479 - 1s - 3ms/step - ia: 0.7052 - loss: 0.3476 - mae: 0.4249 - rmse: 0.5804 - smape: 0.7985 - val_ia: 0.6808 - val_loss: 0.1875 - val_mae: 0.2800 - val_rmse: 0.3742 - val_smape: 0.5873

Epoch 95/128

479/479 - 1s - 3ms/step - ia: 0.7061 - loss: 0.3435 - mae: 0.4236 - rmse: 0.5772 - smape: 0.7944 - val_ia: 0.6821 - val_loss: 0.1863 - val_mae: 0.2788 - val_rmse: 0.3729 - val_smape: 0.5852

Epoch 96/128

479/479 - 2s - 4ms/step - ia: 0.7091 - loss: 0.3417 - mae: 0.4199 - rmse: 0.5747 - smape: 0.7889 - val_ia: 0.6831 - val_loss: 0.1852 - val_mae: 0.2776 - val_rmse: 0.3715 - val_smape: 0.5833

Epoch 97/128

479/479 - 2s - 3ms/step - ia: 0.7065 - loss: 0.3431 - mae: 0.4220 - rmse: 0.5766 - smape: 0.7939 - val_ia: 0.6847 - val_loss: 0.1840 - val_mae: 0.2763 - val_rmse: 0.3701 - val_smape: 0.5811

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 5s - 22ms/step - ia: 0.3064 - loss: 1.4799 - mae: 0.9029 - rmse: 1.2114 - smape: 1.3902 - val_ia: 0.2405 - val_loss: 0.9769 - val_mae: 0.6903 - val_rmse: 0.8463 - val_smape: 1.3210

Epoch 2/128

240/240 - 1s - 3ms/step - ia: 0.3043 - loss: 1.4249 - mae: 0.8921 - rmse: 1.1888 - smape: 1.4005 - val_ia: 0.2466 - val_loss: 0.9472 - val_mae: 0.6917 - val_rmse: 0.8407 - val_smape: 1.4130

Epoch 3/128

240/240 - 1s - 3ms/step - ia: 0.3058 - loss: 1.3907 - mae: 0.8833 - rmse: 1.1746 - smape: 1.3993 - val_ia: 0.2512 - val_loss: 0.9243 - val_mae: 0.6923 - val_rmse: 0.8366 - val_smape: 1.4951

Epoch 4/128

240/240 - 1s - 4ms/step - ia: 0.3066 - loss: 1.3616 - mae: 0.8778 - rmse: 1.1619 - smape: 1.4036 - val_ia: 0.2588 - val_loss: 0.9045 - val_mae: 0.6908 - val_rmse: 0.8317 - val_smape: 1.5534

Epoch 5/128

240/240 - 1s - 6ms/step - ia: 0.3084 - loss: 1.3362 - mae: 0.8720 - rmse: 1.1515 - smape: 1.4076 - val_ia: 0.2665 - val_loss: 0.8866 - val_mae: 0.6880 - val_rmse: 0.8264 - val_smape: 1.5936

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.3120 - loss: 1.3283 - mae: 0.8701 - rmse: 1.1467 - smape: 1.4025 - val_ia: 0.2741 - val_loss: 0.8694 - val_mae: 0.6846 - val_rmse: 0.8208 - val_smape: 1.6185

Epoch 7/128

240/240 - 2s - 7ms/step - ia: 0.3168 - loss: 1.3048 - mae: 0.8611 - rmse: 1.1373 - smape: 1.3938 - val_ia: 0.2812 - val_loss: 0.8521 - val_mae: 0.6785 - val_rmse: 0.8132 - val_smape: 1.6079

Epoch 8/128

240/240 - 1s - 5ms/step - ia: 0.3232 - loss: 1.2728 - mae: 0.8520 - rmse: 1.1231 - smape: 1.3866 - val_ia: 0.2881 - val_loss: 0.8347 - val_mae: 0.6725 - val_rmse: 0.8057 - val_smape: 1.5950

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.3307 - loss: 1.2431 - mae: 0.8412 - rmse: 1.1097 - smape: 1.3775 - val_ia: 0.2951 - val_loss: 0.8179 - val_mae: 0.6660 - val_rmse: 0.7980 - val_smape: 1.5738

Epoch 10/128

240/240 - 1s - 4ms/step - ia: 0.3321 - loss: 1.2381 - mae: 0.8397 - rmse: 1.1078 - smape: 1.3768 - val_ia: 0.3021 - val_loss: 0.8012 - val_mae: 0.6603 - val_rmse: 0.7908 - val_smape: 1.5540

Epoch 11/128

240/240 - 1s - 6ms/step - ia: 0.3426 - loss: 1.2002 - mae: 0.8257 - rmse: 1.0906 - smape: 1.3622 - val_ia: 0.3093 - val_loss: 0.7844 - val_mae: 0.6529 - val_rmse: 0.7823 - val_smape: 1.5249

Epoch 12/128

240/240 - 1s - 5ms/step - ia: 0.3456 - loss: 1.1767 - mae: 0.8172 - rmse: 1.0799 - smape: 1.3589 - val_ia: 0.3169 - val_loss: 0.7676 - val_mae: 0.6458 - val_rmse: 0.7740 - val_smape: 1.4973

Epoch 13/128

240/240 - 1s - 3ms/step - ia: 0.3515 - loss: 1.1589 - mae: 0.8141 - rmse: 1.0716 - smape: 1.3528 - val_ia: 0.3248 - val_loss: 0.7505 - val_mae: 0.6369 - val_rmse: 0.7645 - val_smape: 1.4639

Epoch 14/128

240/240 - 1s - 4ms/step - ia: 0.3557 - loss: 1.1459 - mae: 0.8077 - rmse: 1.0651 - smape: 1.3459 - val_ia: 0.3330 - val_loss: 0.7340 - val_mae: 0.6298 - val_rmse: 0.7562 - val_smape: 1.4381

Epoch 15/128

240/240 - 1s - 4ms/step - ia: 0.3655 - loss: 1.1146 - mae: 0.7951 - rmse: 1.0511 - smape: 1.3328 - val_ia: 0.3416 - val_loss: 0.7171 - val_mae: 0.6211 - val_rmse: 0.7468 - val_smape: 1.4075

Epoch 16/128

240/240 - 1s - 5ms/step - ia: 0.3740 - loss: 1.0966 - mae: 0.7860 - rmse: 1.0423 - smape: 1.3232 - val_ia: 0.3501 - val_loss: 0.7012 - val_mae: 0.6137 - val_rmse: 0.7385 - val_smape: 1.3818

Epoch 17/128

240/240 - 1s - 3ms/step - ia: 0.3777 - loss: 1.0855 - mae: 0.7827 - rmse: 1.0374 - smape: 1.3131 - val_ia: 0.3583 - val_loss: 0.6852 - val_mae: 0.6067 - val_rmse: 0.7303 - val_smape: 1.3580

Epoch 18/128

240/240 - 2s - 7ms/step - ia: 0.3834 - loss: 1.0691 - mae: 0.7769 - rmse: 1.0293 - smape: 1.3060 - val_ia: 0.3668 - val_loss: 0.6692 - val_mae: 0.5989 - val_rmse: 0.7217 - val_smape: 1.3324

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.3868 - loss: 1.0500 - mae: 0.7743 - rmse: 1.0196 - smape: 1.3062 - val_ia: 0.3757 - val_loss: 0.6538 - val_mae: 0.5911 - val_rmse: 0.7132 - val_smape: 1.3074

Epoch 20/128

240/240 - 1s - 4ms/step - ia: 0.4021 - loss: 1.0084 - mae: 0.7552 - rmse: 0.9989 - smape: 1.2810 - val_ia: 0.3847 - val_loss: 0.6386 - val_mae: 0.5833 - val_rmse: 0.7047 - val_smape: 1.2836

Epoch 21/128

240/240 - 1s - 3ms/step - ia: 0.4093 - loss: 0.9914 - mae: 0.7484 - rmse: 0.9909 - smape: 1.2734 - val_ia: 0.3932 - val_loss: 0.6241 - val_mae: 0.5763 - val_rmse: 0.6970 - val_smape: 1.2632

Epoch 22/128

240/240 - 1s - 3ms/step - ia: 0.4119 - loss: 0.9896 - mae: 0.7474 - rmse: 0.9897 - smape: 1.2699 - val_ia: 0.4027 - val_loss: 0.6087 - val_mae: 0.5668 - val_rmse: 0.6872 - val_smape: 1.2348

Epoch 23/128

240/240 - 1s - 6ms/step - ia: 0.4228 - loss: 0.9574 - mae: 0.7349 - rmse: 0.9729 - smape: 1.2576 - val_ia: 0.4115 - val_loss: 0.5942 - val_mae: 0.5590 - val_rmse: 0.6788 - val_smape: 1.2129

Epoch 24/128

240/240 - 1s - 6ms/step - ia: 0.4292 - loss: 0.9519 - mae: 0.7311 - rmse: 0.9707 - smape: 1.2427 - val_ia: 0.4195 - val_loss: 0.5806 - val_mae: 0.5524 - val_rmse: 0.6714 - val_smape: 1.1954

Epoch 25/128

240/240 - 1s - 5ms/step - ia: 0.4311 - loss: 0.9330 - mae: 0.7269 - rmse: 0.9617 - smape: 1.2451 - val_ia: 0.4290 - val_loss: 0.5663 - val_mae: 0.5432 - val_rmse: 0.6621 - val_smape: 1.1697

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.4421 - loss: 0.9095 - mae: 0.7131 - rmse: 0.9491 - smape: 1.2260 - val_ia: 0.4377 - val_loss: 0.5532 - val_mae: 0.5357 - val_rmse: 0.6543 - val_smape: 1.1500

Epoch 27/128

240/240 - 1s - 5ms/step - ia: 0.4464 - loss: 0.8963 - mae: 0.7110 - rmse: 0.9422 - smape: 1.2258 - val_ia: 0.4458 - val_loss: 0.5406 - val_mae: 0.5289 - val_rmse: 0.6470 - val_smape: 1.1329

Epoch 28/128

240/240 - 1s - 3ms/step - ia: 0.4529 - loss: 0.8958 - mae: 0.7079 - rmse: 0.9403 - smape: 1.2105 - val_ia: 0.4547 - val_loss: 0.5279 - val_mae: 0.5208 - val_rmse: 0.6388 - val_smape: 1.1119

Epoch 29/128

240/240 - 1s - 6ms/step - ia: 0.4605 - loss: 0.8700 - mae: 0.6980 - rmse: 0.9280 - smape: 1.2006 - val_ia: 0.4629 - val_loss: 0.5156 - val_mae: 0.5135 - val_rmse: 0.6313 - val_smape: 1.0937

Epoch 30/128

240/240 - 1s - 6ms/step - ia: 0.4693 - loss: 0.8550 - mae: 0.6919 - rmse: 0.9205 - smape: 1.1878 - val_ia: 0.4719 - val_loss: 0.5040 - val_mae: 0.5052 - val_rmse: 0.6233 - val_smape: 1.0723

Epoch 31/128

240/240 - 1s - 6ms/step - ia: 0.4751 - loss: 0.8458 - mae: 0.6870 - rmse: 0.9143 - smape: 1.1776 - val_ia: 0.4796 - val_loss: 0.4930 - val_mae: 0.4990 - val_rmse: 0.6168 - val_smape: 1.0577

Epoch 32/128

240/240 - 1s - 5ms/step - ia: 0.4784 - loss: 0.8335 - mae: 0.6836 - rmse: 0.9084 - smape: 1.1754 - val_ia: 0.4882 - val_loss: 0.4822 - val_mae: 0.4915 - val_rmse: 0.6095 - val_smape: 1.0390

Epoch 33/128

240/240 - 1s - 3ms/step - ia: 0.4817 - loss: 0.8209 - mae: 0.6800 - rmse: 0.9018 - smape: 1.1732 - val_ia: 0.4968 - val_loss: 0.4716 - val_mae: 0.4841 - val_rmse: 0.6023 - val_smape: 1.0206

Epoch 34/128

240/240 - 1s - 3ms/step - ia: 0.4907 - loss: 0.8080 - mae: 0.6707 - rmse: 0.8943 - smape: 1.1572 - val_ia: 0.5038 - val_loss: 0.4619 - val_mae: 0.4785 - val_rmse: 0.5965 - val_smape: 1.0084

Epoch 35/128

240/240 - 1s - 4ms/step - ia: 0.4955 - loss: 0.7980 - mae: 0.6663 - rmse: 0.8896 - smape: 1.1479 - val_ia: 0.5109 - val_loss: 0.4526 - val_mae: 0.4729 - val_rmse: 0.5908 - val_smape: 0.9961

Epoch 36/128

240/240 - 1s - 4ms/step - ia: 0.5004 - loss: 0.7847 - mae: 0.6630 - rmse: 0.8811 - smape: 1.1444 - val_ia: 0.5192 - val_loss: 0.4434 - val_mae: 0.4657 - val_rmse: 0.5841 - val_smape: 0.9788

Epoch 37/128

240/240 - 1s - 4ms/step - ia: 0.5085 - loss: 0.7662 - mae: 0.6536 - rmse: 0.8701 - smape: 1.1324 - val_ia: 0.5272 - val_loss: 0.4350 - val_mae: 0.4591 - val_rmse: 0.5779 - val_smape: 0.9634

Epoch 38/128

240/240 - 1s - 5ms/step - ia: 0.5140 - loss: 0.7605 - mae: 0.6495 - rmse: 0.8668 - smape: 1.1272 - val_ia: 0.5342 - val_loss: 0.4272 - val_mae: 0.4534 - val_rmse: 0.5725 - val_smape: 0.9507

Epoch 39/128

240/240 - 1s - 5ms/step - ia: 0.5176 - loss: 0.7516 - mae: 0.6474 - rmse: 0.8625 - smape: 1.1189 - val_ia: 0.5394 - val_loss: 0.4200 - val_mae: 0.4496 - val_rmse: 0.5685 - val_smape: 0.9434

Epoch 40/128

240/240 - 1s - 3ms/step - ia: 0.5194 - loss: 0.7389 - mae: 0.6429 - rmse: 0.8555 - smape: 1.1175 - val_ia: 0.5468 - val_loss: 0.4126 - val_mae: 0.4437 - val_rmse: 0.5631 - val_smape: 0.9299

Epoch 41/128

240/240 - 1s - 6ms/step - ia: 0.5235 - loss: 0.7386 - mae: 0.6420 - rmse: 0.8546 - smape: 1.1112 - val_ia: 0.5542 - val_loss: 0.4055 - val_mae: 0.4375 - val_rmse: 0.5576 - val_smape: 0.9155

Epoch 42/128

240/240 - 1s - 6ms/step - ia: 0.5289 - loss: 0.7256 - mae: 0.6366 - rmse: 0.8478 - smape: 1.1014 - val_ia: 0.5598 - val_loss: 0.3989 - val_mae: 0.4330 - val_rmse: 0.5532 - val_smape: 0.9060

Epoch 43/128

240/240 - 1s - 5ms/step - ia: 0.5346 - loss: 0.7094 - mae: 0.6308 - rmse: 0.8373 - smape: 1.0951 - val_ia: 0.5666 - val_loss: 0.3926 - val_mae: 0.4273 - val_rmse: 0.5480 - val_smape: 0.8928

Epoch 44/128

240/240 - 1s - 3ms/step - ia: 0.5366 - loss: 0.7118 - mae: 0.6292 - rmse: 0.8398 - smape: 1.0892 - val_ia: 0.5719 - val_loss: 0.3865 - val_mae: 0.4230 - val_rmse: 0.5437 - val_smape: 0.8838

Epoch 45/128

240/240 - 1s - 6ms/step - ia: 0.5416 - loss: 0.7009 - mae: 0.6236 - rmse: 0.8330 - smape: 1.0835 - val_ia: 0.5772 - val_loss: 0.3809 - val_mae: 0.4188 - val_rmse: 0.5397 - val_smape: 0.8749

Epoch 46/128

240/240 - 1s - 4ms/step - ia: 0.5450 - loss: 0.6882 - mae: 0.6207 - rmse: 0.8249 - smape: 1.0802 - val_ia: 0.5825 - val_loss: 0.3756 - val_mae: 0.4146 - val_rmse: 0.5358 - val_smape: 0.8659

Epoch 47/128

240/240 - 1s - 4ms/step - ia: 0.5483 - loss: 0.6815 - mae: 0.6156 - rmse: 0.8212 - smape: 1.0754 - val_ia: 0.5866 - val_loss: 0.3707 - val_mae: 0.4115 - val_rmse: 0.5327 - val_smape: 0.8599

Epoch 48/128

240/240 - 2s - 6ms/step - ia: 0.5544 - loss: 0.6715 - mae: 0.6096 - rmse: 0.8158 - smape: 1.0620 - val_ia: 0.5905 - val_loss: 0.3662 - val_mae: 0.4086 - val_rmse: 0.5298 - val_smape: 0.8541

Epoch 49/128

240/240 - 1s - 3ms/step - ia: 0.5549 - loss: 0.6661 - mae: 0.6109 - rmse: 0.8127 - smape: 1.0658 - val_ia: 0.5963 - val_loss: 0.3612 - val_mae: 0.4037 - val_rmse: 0.5253 - val_smape: 0.8430

Epoch 50/128

240/240 - 1s - 6ms/step - ia: 0.5578 - loss: 0.6614 - mae: 0.6071 - rmse: 0.8091 - smape: 1.0605 - val_ia: 0.5997 - val_loss: 0.3570 - val_mae: 0.4012 - val_rmse: 0.5228 - val_smape: 0.8385

Epoch 51/128

240/240 - 1s - 6ms/step - ia: 0.5614 - loss: 0.6552 - mae: 0.6024 - rmse: 0.8051 - smape: 1.0509 - val_ia: 0.6039 - val_loss: 0.3529 - val_mae: 0.3978 - val_rmse: 0.5196 - val_smape: 0.8311

Epoch 52/128

240/240 - 1s - 4ms/step - ia: 0.5613 - loss: 0.6616 - mae: 0.6034 - rmse: 0.8081 - smape: 1.0528 - val_ia: 0.6078 - val_loss: 0.3488 - val_mae: 0.3947 - val_rmse: 0.5166 - val_smape: 0.8248

Epoch 53/128

240/240 - 1s - 3ms/step - ia: 0.5669 - loss: 0.6461 - mae: 0.5977 - rmse: 0.7998 - smape: 1.0430 - val_ia: 0.6113 - val_loss: 0.3450 - val_mae: 0.3918 - val_rmse: 0.5138 - val_smape: 0.8189

Epoch 54/128

240/240 - 1s - 3ms/step - ia: 0.5707 - loss: 0.6361 - mae: 0.5927 - rmse: 0.7932 - smape: 1.0383 - val_ia: 0.6147 - val_loss: 0.3414 - val_mae: 0.3891 - val_rmse: 0.5112 - val_smape: 0.8136

Epoch 55/128

240/240 - 1s - 3ms/step - ia: 0.5722 - loss: 0.6322 - mae: 0.5926 - rmse: 0.7913 - smape: 1.0355 - val_ia: 0.6177 - val_loss: 0.3380 - val_mae: 0.3865 - val_rmse: 0.5086 - val_smape: 0.8085

Epoch 56/128

240/240 - 2s - 6ms/step - ia: 0.5782 - loss: 0.6217 - mae: 0.5836 - rmse: 0.7837 - smape: 1.0227 - val_ia: 0.6221 - val_loss: 0.3345 - val_mae: 0.3829 - val_rmse: 0.5053 - val_smape: 0.8001

Epoch 57/128

240/240 - 1s - 6ms/step - ia: 0.5773 - loss: 0.6212 - mae: 0.5850 - rmse: 0.7836 - smape: 1.0287 - val_ia: 0.6249 - val_loss: 0.3313 - val_mae: 0.3806 - val_rmse: 0.5031 - val_smape: 0.7957

Epoch 58/128

240/240 - 1s - 3ms/step - ia: 0.5829 - loss: 0.6102 - mae: 0.5792 - rmse: 0.7767 - smape: 1.0156 - val_ia: 0.6279 - val_loss: 0.3283 - val_mae: 0.3783 - val_rmse: 0.5008 - val_smape: 0.7909

Epoch 59/128

240/240 - 1s - 3ms/step - ia: 0.5831 - loss: 0.6126 - mae: 0.5785 - rmse: 0.7781 - smape: 1.0160 - val_ia: 0.6308 - val_loss: 0.3253 - val_mae: 0.3758 - val_rmse: 0.4984 - val_smape: 0.7859

Epoch 60/128

240/240 - 1s - 3ms/step - ia: 0.5873 - loss: 0.5992 - mae: 0.5734 - rmse: 0.7693 - smape: 1.0106 - val_ia: 0.6339 - val_loss: 0.3224 - val_mae: 0.3732 - val_rmse: 0.4959 - val_smape: 0.7805

Epoch 61/128

240/240 - 2s - 6ms/step - ia: 0.5923 - loss: 0.5889 - mae: 0.5658 - rmse: 0.7630 - smape: 1.0027 - val_ia: 0.6362 - val_loss: 0.3195 - val_mae: 0.3713 - val_rmse: 0.4940 - val_smape: 0.7772

Epoch 62/128

240/240 - 1s - 3ms/step - ia: 0.5902 - loss: 0.5939 - mae: 0.5704 - rmse: 0.7668 - smape: 1.0062 - val_ia: 0.6388 - val_loss: 0.3168 - val_mae: 0.3690 - val_rmse: 0.4917 - val_smape: 0.7725

Epoch 63/128

240/240 - 1s - 4ms/step - ia: 0.5958 - loss: 0.5827 - mae: 0.5631 - rmse: 0.7589 - smape: 0.9992 - val_ia: 0.6426 - val_loss: 0.3141 - val_mae: 0.3659 - val_rmse: 0.4888 - val_smape: 0.7649

Epoch 64/128

240/240 - 1s - 6ms/step - ia: 0.5959 - loss: 0.5827 - mae: 0.5646 - rmse: 0.7585 - smape: 0.9977 - val_ia: 0.6435 - val_loss: 0.3118 - val_mae: 0.3649 - val_rmse: 0.4876 - val_smape: 0.7642

Epoch 65/128

240/240 - 1s - 3ms/step - ia: 0.6015 - loss: 0.5676 - mae: 0.5562 - rmse: 0.7482 - smape: 0.9892 - val_ia: 0.6448 - val_loss: 0.3095 - val_mae: 0.3636 - val_rmse: 0.4861 - val_smape: 0.7624

Epoch 66/128

240/240 - 1s - 4ms/step - ia: 0.6002 - loss: 0.5686 - mae: 0.5558 - rmse: 0.7500 - smape: 0.9899 - val_ia: 0.6484 - val_loss: 0.3070 - val_mae: 0.3607 - val_rmse: 0.4834 - val_smape: 0.7550

Epoch 67/128

240/240 - 1s - 4ms/step - ia: 0.6022 - loss: 0.5653 - mae: 0.5559 - rmse: 0.7467 - smape: 0.9863 - val_ia: 0.6503 - val_loss: 0.3049 - val_mae: 0.3589 - val_rmse: 0.4817 - val_smape: 0.7515

Epoch 68/128

240/240 - 1s - 5ms/step - ia: 0.6055 - loss: 0.5543 - mae: 0.5505 - rmse: 0.7392 - smape: 0.9814 - val_ia: 0.6518 - val_loss: 0.3026 - val_mae: 0.3575 - val_rmse: 0.4801 - val_smape: 0.7492

Epoch 69/128

240/240 - 1s - 6ms/step - ia: 0.6075 - loss: 0.5573 - mae: 0.5482 - rmse: 0.7416 - smape: 0.9765 - val_ia: 0.6540 - val_loss: 0.3004 - val_mae: 0.3554 - val_rmse: 0.4780 - val_smape: 0.7450

Epoch 70/128

240/240 - 1s - 3ms/step - ia: 0.6110 - loss: 0.5495 - mae: 0.5438 - rmse: 0.7370 - smape: 0.9674 - val_ia: 0.6562 - val_loss: 0.2983 - val_mae: 0.3536 - val_rmse: 0.4762 - val_smape: 0.7412

Epoch 71/128

240/240 - 1s - 3ms/step - ia: 0.6127 - loss: 0.5445 - mae: 0.5413 - rmse: 0.7337 - smape: 0.9655 - val_ia: 0.6575 - val_loss: 0.2964 - val_mae: 0.3522 - val_rmse: 0.4747 - val_smape: 0.7389

Epoch 72/128

240/240 - 1s - 6ms/step - ia: 0.6127 - loss: 0.5434 - mae: 0.5421 - rmse: 0.7332 - smape: 0.9679 - val_ia: 0.6593 - val_loss: 0.2943 - val_mae: 0.3505 - val_rmse: 0.4729 - val_smape: 0.7356

Epoch 73/128

240/240 - 1s - 3ms/step - ia: 0.6169 - loss: 0.5321 - mae: 0.5351 - rmse: 0.7253 - smape: 0.9567 - val_ia: 0.6607 - val_loss: 0.2923 - val_mae: 0.3491 - val_rmse: 0.4714 - val_smape: 0.7330

Epoch 74/128

240/240 - 2s - 6ms/step - ia: 0.6169 - loss: 0.5355 - mae: 0.5349 - rmse: 0.7273 - smape: 0.9609 - val_ia: 0.6626 - val_loss: 0.2903 - val_mae: 0.3473 - val_rmse: 0.4695 - val_smape: 0.7292

Epoch 75/128

240/240 - 1s - 5ms/step - ia: 0.6204 - loss: 0.5260 - mae: 0.5310 - rmse: 0.7206 - smape: 0.9531 - val_ia: 0.6645 - val_loss: 0.2884 - val_mae: 0.3455 - val_rmse: 0.4676 - val_smape: 0.7254

Epoch 76/128

240/240 - 1s - 3ms/step - ia: 0.6188 - loss: 0.5260 - mae: 0.5319 - rmse: 0.7206 - smape: 0.9567 - val_ia: 0.6652 - val_loss: 0.2865 - val_mae: 0.3446 - val_rmse: 0.4664 - val_smape: 0.7243

Epoch 77/128

240/240 - 1s - 3ms/step - ia: 0.6216 - loss: 0.5220 - mae: 0.5264 - rmse: 0.7175 - smape: 0.9547 - val_ia: 0.6670 - val_loss: 0.2846 - val_mae: 0.3430 - val_rmse: 0.4648 - val_smape: 0.7211

Epoch 78/128

240/240 - 2s - 6ms/step - ia: 0.6216 - loss: 0.5194 - mae: 0.5273 - rmse: 0.7163 - smape: 0.9551 - val_ia: 0.6675 - val_loss: 0.2829 - val_mae: 0.3423 - val_rmse: 0.4638 - val_smape: 0.7208

Epoch 79/128

240/240 - 1s - 3ms/step - ia: 0.6266 - loss: 0.5098 - mae: 0.5217 - rmse: 0.7094 - smape: 0.9465 - val_ia: 0.6692 - val_loss: 0.2810 - val_mae: 0.3406 - val_rmse: 0.4621 - val_smape: 0.7169

Epoch 80/128

240/240 - 1s - 3ms/step - ia: 0.6263 - loss: 0.5122 - mae: 0.5230 - rmse: 0.7116 - smape: 0.9444 - val_ia: 0.6705 - val_loss: 0.2793 - val_mae: 0.3392 - val_rmse: 0.4605 - val_smape: 0.7142

Epoch 81/128

240/240 - 1s - 4ms/step - ia: 0.6301 - loss: 0.5043 - mae: 0.5157 - rmse: 0.7053 - smape: 0.9373 - val_ia: 0.6729 - val_loss: 0.2775 - val_mae: 0.3371 - val_rmse: 0.4585 - val_smape: 0.7097

Epoch 82/128

240/240 - 1s - 3ms/step - ia: 0.6303 - loss: 0.4973 - mae: 0.5147 - rmse: 0.7005 - smape: 0.9400 - val_ia: 0.6747 - val_loss: 0.2757 - val_mae: 0.3355 - val_rmse: 0.4567 - val_smape: 0.7064

Epoch 83/128

240/240 - 1s - 3ms/step - ia: 0.6323 - loss: 0.4967 - mae: 0.5130 - rmse: 0.6997 - smape: 0.9311 - val_ia: 0.6757 - val_loss: 0.2740 - val_mae: 0.3343 - val_rmse: 0.4554 - val_smape: 0.7045

Epoch 84/128

240/240 - 2s - 7ms/step - ia: 0.6347 - loss: 0.4944 - mae: 0.5094 - rmse: 0.6982 - smape: 0.9268 - val_ia: 0.6773 - val_loss: 0.2723 - val_mae: 0.3329 - val_rmse: 0.4539 - val_smape: 0.7017

Epoch 85/128

240/240 - 1s - 3ms/step - ia: 0.6381 - loss: 0.4822 - mae: 0.5062 - rmse: 0.6901 - smape: 0.9212 - val_ia: 0.6786 - val_loss: 0.2707 - val_mae: 0.3315 - val_rmse: 0.4525 - val_smape: 0.6992

Epoch 86/128

240/240 - 1s - 3ms/step - ia: 0.6379 - loss: 0.4855 - mae: 0.5058 - rmse: 0.6916 - smape: 0.9257 - val_ia: 0.6800 - val_loss: 0.2690 - val_mae: 0.3301 - val_rmse: 0.4509 - val_smape: 0.6965

Epoch 87/128

240/240 - 1s - 3ms/step - ia: 0.6424 - loss: 0.4747 - mae: 0.5002 - rmse: 0.6849 - smape: 0.9173 - val_ia: 0.6813 - val_loss: 0.2674 - val_mae: 0.3287 - val_rmse: 0.4494 - val_smape: 0.6937

Epoch 88/128

240/240 - 1s - 6ms/step - ia: 0.6395 - loss: 0.4768 - mae: 0.5028 - rmse: 0.6859 - smape: 0.9218 - val_ia: 0.6816 - val_loss: 0.2660 - val_mae: 0.3281 - val_rmse: 0.4485 - val_smape: 0.6933

Epoch 89/128

240/240 - 1s - 5ms/step - ia: 0.6436 - loss: 0.4705 - mae: 0.4966 - rmse: 0.6814 - smape: 0.9148 - val_ia: 0.6828 - val_loss: 0.2644 - val_mae: 0.3269 - val_rmse: 0.4471 - val_smape: 0.6910

Epoch 90/128

240/240 - 1s - 3ms/step - ia: 0.6437 - loss: 0.4715 - mae: 0.4973 - rmse: 0.6821 - smape: 0.9148 - val_ia: 0.6848 - val_loss: 0.2628 - val_mae: 0.3252 - val_rmse: 0.4454 - val_smape: 0.6872

Epoch 91/128

240/240 - 1s - 5ms/step - ia: 0.6456 - loss: 0.4641 - mae: 0.4936 - rmse: 0.6767 - smape: 0.9114 - val_ia: 0.6858 - val_loss: 0.2612 - val_mae: 0.3240 - val_rmse: 0.4441 - val_smape: 0.6852

Epoch 92/128

240/240 - 1s - 2ms/step - ia: 0.6471 - loss: 0.4596 - mae: 0.4919 - rmse: 0.6731 - smape: 0.9132 - val_ia: 0.6868 - val_loss: 0.2597 - val_mae: 0.3230 - val_rmse: 0.4429 - val_smape: 0.6835

Epoch 93/128

240/240 - 1s - 3ms/step - ia: 0.6486 - loss: 0.4624 - mae: 0.4906 - rmse: 0.6757 - smape: 0.9048 - val_ia: 0.6881 - val_loss: 0.2582 - val_mae: 0.3216 - val_rmse: 0.4414 - val_smape: 0.6806

Epoch 94/128

240/240 - 1s - 2ms/step - ia: 0.6511 - loss: 0.4548 - mae: 0.4865 - rmse: 0.6701 - smape: 0.8989 - val_ia: 0.6894 - val_loss: 0.2567 - val_mae: 0.3203 - val_rmse: 0.4400 - val_smape: 0.6778

Epoch 95/128

240/240 - 1s - 2ms/step - ia: 0.6504 - loss: 0.4562 - mae: 0.4880 - rmse: 0.6700 - smape: 0.8999 - val_ia: 0.6905 - val_loss: 0.2553 - val_mae: 0.3191 - val_rmse: 0.4386 - val_smape: 0.6751

Epoch 96/128

240/240 - 1s - 2ms/step - ia: 0.6553 - loss: 0.4476 - mae: 0.4816 - rmse: 0.6642 - smape: 0.8934 - val_ia: 0.6917 - val_loss: 0.2539 - val_mae: 0.3179 - val_rmse: 0.4373 - val_smape: 0.6725

Epoch 97/128

240/240 - 1s - 3ms/step - ia: 0.6557 - loss: 0.4450 - mae: 0.4798 - rmse: 0.6613 - smape: 0.8906 - val_ia: 0.6927 - val_loss: 0.2523 - val_mae: 0.3168 - val_rmse: 0.4360 - val_smape: 0.6707

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 4s - 18ms/step - ia: 0.7783 - loss: 0.3944 - mae: 0.3580 - rmse: 0.4931 - smape: 0.6482 - val_ia: 0.8576 - val_loss: 0.0636 - val_mae: 0.1465 - val_rmse: 0.2305 - val_smape: 0.3828

Epoch 2/128

240/240 - 1s - 4ms/step - ia: 0.8610 - loss: 0.0966 - mae: 0.2018 - rmse: 0.3044 - smape: 0.4651 - val_ia: 0.8154 - val_loss: 0.0754 - val_mae: 0.1819 - val_rmse: 0.2564 - val_smape: 0.4586

Epoch 3/128

240/240 - 1s - 6ms/step - ia: 0.8699 - loss: 0.0882 - mae: 0.1888 - rmse: 0.2904 - smape: 0.4386 - val_ia: 0.8470 - val_loss: 0.0644 - val_mae: 0.1526 - val_rmse: 0.2316 - val_smape: 0.3842

Epoch 4/128

240/240 - 1s - 3ms/step - ia: 0.8751 - loss: 0.0836 - mae: 0.1814 - rmse: 0.2822 - smape: 0.4238 - val_ia: 0.8608 - val_loss: 0.0594 - val_mae: 0.1439 - val_rmse: 0.2223 - val_smape: 0.3717

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.8725 - loss: 0.0856 - mae: 0.1856 - rmse: 0.2855 - smape: 0.4271 - val_ia: 0.8525 - val_loss: 0.0605 - val_mae: 0.1454 - val_rmse: 0.2255 - val_smape: 0.3765

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.8748 - loss: 0.0845 - mae: 0.1824 - rmse: 0.2840 - smape: 0.4224 - val_ia: 0.8598 - val_loss: 0.0592 - val_mae: 0.1419 - val_rmse: 0.2213 - val_smape: 0.3664

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.8714 - loss: 0.0874 - mae: 0.1866 - rmse: 0.2891 - smape: 0.4288 - val_ia: 0.8062 - val_loss: 0.0803 - val_mae: 0.1866 - val_rmse: 0.2598 - val_smape: 0.4339

Epoch 8/128

240/240 - 1s - 4ms/step - ia: 0.8715 - loss: 0.0875 - mae: 0.1864 - rmse: 0.2891 - smape: 0.4277 - val_ia: 0.8619 - val_loss: 0.0645 - val_mae: 0.1470 - val_rmse: 0.2319 - val_smape: 0.3730

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.8741 - loss: 0.0840 - mae: 0.1826 - rmse: 0.2836 - smape: 0.4211 - val_ia: 0.8716 - val_loss: 0.0579 - val_mae: 0.1336 - val_rmse: 0.2178 - val_smape: 0.3514

Epoch 10/128

240/240 - 1s - 2ms/step - ia: 0.8686 - loss: 0.0886 - mae: 0.1910 - rmse: 0.2906 - smape: 0.4343 - val_ia: 0.8618 - val_loss: 0.0592 - val_mae: 0.1400 - val_rmse: 0.2209 - val_smape: 0.3653

Epoch 11/128

240/240 - 1s - 3ms/step - ia: 0.8697 - loss: 0.0884 - mae: 0.1891 - rmse: 0.2906 - smape: 0.4325 - val_ia: 0.8603 - val_loss: 0.0592 - val_mae: 0.1409 - val_rmse: 0.2213 - val_smape: 0.3654

Epoch 12/128

240/240 - 1s - 5ms/step - ia: 0.8704 - loss: 0.0868 - mae: 0.1881 - rmse: 0.2881 - smape: 0.4297 - val_ia: 0.8607 - val_loss: 0.0597 - val_mae: 0.1415 - val_rmse: 0.2206 - val_smape: 0.3628

Epoch 13/128

240/240 - 1s - 3ms/step - ia: 0.8715 - loss: 0.0875 - mae: 0.1869 - rmse: 0.2882 - smape: 0.4288 - val_ia: 0.8535 - val_loss: 0.0615 - val_mae: 0.1484 - val_rmse: 0.2256 - val_smape: 0.3766

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.8697 - loss: 0.0877 - mae: 0.1887 - rmse: 0.2903 - smape: 0.4302 - val_ia: 0.8218 - val_loss: 0.0756 - val_mae: 0.1835 - val_rmse: 0.2577 - val_smape: 0.4533

Epoch 15/128

240/240 - 1s - 3ms/step - ia: 0.8638 - loss: 0.0940 - mae: 0.1979 - rmse: 0.2992 - smape: 0.4476 - val_ia: 0.8599 - val_loss: 0.0696 - val_mae: 0.1524 - val_rmse: 0.2403 - val_smape: 0.3702

Epoch 16/128

240/240 - 1s - 2ms/step - ia: 0.8593 - loss: 0.0991 - mae: 0.2033 - rmse: 0.3087 - smape: 0.4513 - val_ia: 0.8414 - val_loss: 0.0667 - val_mae: 0.1603 - val_rmse: 0.2396 - val_smape: 0.4028

Epoch 17/128

240/240 - 1s - 3ms/step - ia: 0.8671 - loss: 0.0913 - mae: 0.1927 - rmse: 0.2945 - smape: 0.4390 - val_ia: 0.8627 - val_loss: 0.0610 - val_mae: 0.1447 - val_rmse: 0.2251 - val_smape: 0.3703

Epoch 18/128

240/240 - 1s - 3ms/step - ia: 0.8653 - loss: 0.0921 - mae: 0.1957 - rmse: 0.2963 - smape: 0.4420 - val_ia: 0.8582 - val_loss: 0.0617 - val_mae: 0.1456 - val_rmse: 0.2272 - val_smape: 0.3727

Epoch 19/128

240/240 - 1s - 3ms/step - ia: 0.8658 - loss: 0.0920 - mae: 0.1952 - rmse: 0.2956 - smape: 0.4400 - val_ia: 0.8642 - val_loss: 0.0637 - val_mae: 0.1438 - val_rmse: 0.2288 - val_smape: 0.3625

Epoch 20/128

240/240 - 1s - 3ms/step - ia: 0.8644 - loss: 0.0923 - mae: 0.1961 - rmse: 0.2979 - smape: 0.4444 - val_ia: 0.8657 - val_loss: 0.0593 - val_mae: 0.1403 - val_rmse: 0.2212 - val_smape: 0.3641

Epoch 21/128

240/240 - 1s - 4ms/step - ia: 0.8674 - loss: 0.0894 - mae: 0.1926 - rmse: 0.2927 - smape: 0.4376 - val_ia: 0.7711 - val_loss: 0.0989 - val_mae: 0.2269 - val_rmse: 0.2969 - val_smape: 0.5640

Epoch 22/128

240/240 - 1s - 5ms/step - ia: 0.8580 - loss: 0.0990 - mae: 0.2055 - rmse: 0.3077 - smape: 0.4553 - val_ia: 0.8653 - val_loss: 0.0598 - val_mae: 0.1396 - val_rmse: 0.2221 - val_smape: 0.3624

Epoch 23/128

240/240 - 1s - 3ms/step - ia: 0.8637 - loss: 0.0949 - mae: 0.1976 - rmse: 0.3007 - smape: 0.4469 - val_ia: 0.8291 - val_loss: 0.0666 - val_mae: 0.1637 - val_rmse: 0.2389 - val_smape: 0.4124

Epoch 24/128

240/240 - 1s - 3ms/step - ia: 0.8594 - loss: 0.0987 - mae: 0.2034 - rmse: 0.3073 - smape: 0.4565 - val_ia: 0.8200 - val_loss: 0.0717 - val_mae: 0.1725 - val_rmse: 0.2472 - val_smape: 0.4239

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 14s 111ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 58%|█████▊    | 7/12 [54:18<24:49, 297.89s/trial, best loss: 0.03826835975527505]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 14s - 4ms/step - ia: 0.7511 - loss: 0.2151 - mae: 0.3162 - rmse: 0.4127 - smape: 0.6359 - val_ia: 0.4627 - val_loss: 0.1093 - val_mae: 0.2053 - val_rmse: 0.2489 - val_smape: 0.4806

Epoch 2/128

3832/3832 - 9s - 2ms/step - ia: 0.7857 - loss: 0.1522 - mae: 0.2668 - rmse: 0.3486 - smape: 0.5702 - val_ia: 0.4944 - val_loss: 0.0859 - val_mae: 0.1719 - val_rmse: 0.2127 - val_smape: 0.4098

Epoch 3/128

3832/3832 - 11s - 3ms/step - ia: 0.7951 - loss: 0.1414 - mae: 0.2556 - rmse: 0.3351 - smape: 0.5580 - val_ia: 0.4925 - val_loss: 0.0919 - val_mae: 0.1859 - val_rmse: 0.2302 - val_smape: 0.4375

Epoch 4/128

3832/3832 - 9s - 2ms/step - ia: 0.7946 - loss: 0.1410 - mae: 0.2556 - rmse: 0.3355 - smape: 0.5564 - val_ia: 0.4928 - val_loss: 0.0842 - val_mae: 0.1714 - val_rmse: 0.2127 - val_smape: 0.4177

Epoch 5/128

3832/3832 - 7s - 2ms/step - ia: 0.7971 - loss: 0.1368 - mae: 0.2526 - rmse: 0.3304 - smape: 0.5557 - val_ia: 0.4317 - val_loss: 0.0958 - val_mae: 0.2114 - val_rmse: 0.2493 - val_smape: 0.5094

Epoch 6/128

3832/3832 - 9s - 2ms/step - ia: 0.7970 - loss: 0.1372 - mae: 0.2522 - rmse: 0.3297 - smape: 0.5570 - val_ia: 0.5051 - val_loss: 0.0808 - val_mae: 0.1665 - val_rmse: 0.2091 - val_smape: 0.3897

Epoch 7/128

3832/3832 - 11s - 3ms/step - ia: 0.7964 - loss: 0.1373 - mae: 0.2530 - rmse: 0.3307 - smape: 0.5561 - val_ia: 0.5027 - val_loss: 0.0793 - val_mae: 0.1659 - val_rmse: 0.2083 - val_smape: 0.4125

Epoch 8/128

3832/3832 - 9s - 2ms/step - ia: 0.7968 - loss: 0.1353 - mae: 0.2520 - rmse: 0.3286 - smape: 0.5536 - val_ia: 0.4969 - val_loss: 0.0837 - val_mae: 0.1722 - val_rmse: 0.2137 - val_smape: 0.3977

Epoch 9/128

3832/3832 - 10s - 3ms/step - ia: 0.7974 - loss: 0.1355 - mae: 0.2519 - rmse: 0.3293 - smape: 0.5567 - val_ia: 0.4731 - val_loss: 0.0844 - val_mae: 0.1851 - val_rmse: 0.2249 - val_smape: 0.4529

Epoch 10/128

3832/3832 - 10s - 3ms/step - ia: 0.7984 - loss: 0.1331 - mae: 0.2505 - rmse: 0.3267 - smape: 0.5566 - val_ia: 0.4804 - val_loss: 0.0828 - val_mae: 0.1752 - val_rmse: 0.2135 - val_smape: 0.4527

Epoch 11/128

3832/3832 - 11s - 3ms/step - ia: 0.8009 - loss: 0.1321 - mae: 0.2479 - rmse: 0.3239 - smape: 0.5475 - val_ia: 0.5049 - val_loss: 0.0753 - val_mae: 0.1634 - val_rmse: 0.2051 - val_smape: 0.4021

Epoch 12/128

3832/3832 - 11s - 3ms/step - ia: 0.8001 - loss: 0.1309 - mae: 0.2484 - rmse: 0.3235 - smape: 0.5509 - val_ia: 0.5135 - val_loss: 0.0779 - val_mae: 0.1656 - val_rmse: 0.2077 - val_smape: 0.4089

Epoch 13/128

3832/3832 - 9s - 2ms/step - ia: 0.7976 - loss: 0.1320 - mae: 0.2492 - rmse: 0.3249 - smape: 0.5539 - val_ia: 0.4927 - val_loss: 0.0785 - val_mae: 0.1715 - val_rmse: 0.2114 - val_smape: 0.4095

Epoch 14/128

3832/3832 - 10s - 3ms/step - ia: 0.8019 - loss: 0.1299 - mae: 0.2460 - rmse: 0.3224 - smape: 0.5488 - val_ia: 0.5054 - val_loss: 0.0806 - val_mae: 0.1684 - val_rmse: 0.2127 - val_smape: 0.3896

Epoch 15/128

3832/3832 - 10s - 3ms/step - ia: 0.7990 - loss: 0.1329 - mae: 0.2499 - rmse: 0.3262 - smape: 0.5536 - val_ia: 0.4811 - val_loss: 0.0813 - val_mae: 0.1738 - val_rmse: 0.2145 - val_smape: 0.4207

Epoch 16/128

3832/3832 - 11s - 3ms/step - ia: 0.7995 - loss: 0.1328 - mae: 0.2495 - rmse: 0.3254 - smape: 0.5521 - val_ia: 0.4733 - val_loss: 0.0824 - val_mae: 0.1835 - val_rmse: 0.2251 - val_smape: 0.4594

Epoch 17/128

3832/3832 - 10s - 3ms/step - ia: 0.8014 - loss: 0.1307 - mae: 0.2473 - rmse: 0.3231 - smape: 0.5486 - val_ia: 0.4908 - val_loss: 0.0785 - val_mae: 0.1699 - val_rmse: 0.2106 - val_smape: 0.4173

Epoch 18/128

3832/3832 - 10s - 3ms/step - ia: 0.8008 - loss: 0.1297 - mae: 0.2471 - rmse: 0.3221 - smape: 0.5504 - val_ia: 0.5154 - val_loss: 0.0775 - val_mae: 0.1672 - val_rmse: 0.2116 - val_smape: 0.3995

Epoch 19/128

3832/3832 - 8s - 2ms/step - ia: 0.8004 - loss: 0.1327 - mae: 0.2490 - rmse: 0.3256 - smape: 0.5502 - val_ia: 0.5156 - val_loss: 0.0765 - val_mae: 0.1614 - val_rmse: 0.2015 - val_smape: 0.3738

Epoch 20/128

3832/3832 - 10s - 3ms/step - ia: 0.8014 - loss: 0.1312 - mae: 0.2485 - rmse: 0.3239 - smape: 0.5524 - val_ia: 0.4765 - val_loss: 0.0994 - val_mae: 0.1906 - val_rmse: 0.2294 - val_smape: 0.4344

Epoch 21/128

3832/3832 - 10s - 3ms/step - ia: 0.7998 - loss: 0.1308 - mae: 0.2484 - rmse: 0.3235 - smape: 0.5518 - val_ia: 0.4941 - val_loss: 0.0772 - val_mae: 0.1685 - val_rmse: 0.2093 - val_smape: 0.4341

Epoch 22/128

3832/3832 - 11s - 3ms/step - ia: 0.8015 - loss: 0.1301 - mae: 0.2462 - rmse: 0.3214 - smape: 0.5476 - val_ia: 0.4482 - val_loss: 0.0893 - val_mae: 0.1977 - val_rmse: 0.2367 - val_smape: 0.4913

Epoch 23/128

3832/3832 - 20s - 5ms/step - ia: 0.8012 - loss: 0.1305 - mae: 0.2467 - rmse: 0.3230 - smape: 0.5504 - val_ia: 0.4646 - val_loss: 0.0882 - val_mae: 0.1867 - val_rmse: 0.2267 - val_smape: 0.4629

Epoch 24/128

3832/3832 - 11s - 3ms/step - ia: 0.8024 - loss: 0.1308 - mae: 0.2477 - rmse: 0.3232 - smape: 0.5512 - val_ia: 0.5110 - val_loss: 0.0778 - val_mae: 0.1630 - val_rmse: 0.2050 - val_smape: 0.3796

Epoch 25/128

3832/3832 - 20s - 5ms/step - ia: 0.8008 - loss: 0.1310 - mae: 0.2475 - rmse: 0.3234 - smape: 0.5502 - val_ia: 0.4543 - val_loss: 0.0927 - val_mae: 0.1988 - val_rmse: 0.2404 - val_smape: 0.4894

Epoch 26/128

3832/3832 - 10s - 3ms/step - ia: 0.7997 - loss: 0.1306 - mae: 0.2492 - rmse: 0.3236 - smape: 0.5556 - val_ia: 0.4835 - val_loss: 0.0819 - val_mae: 0.1758 - val_rmse: 0.2166 - val_smape: 0.4191

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 34s 256ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 67%|██████▋   | 8/12 [59:06<19:38, 294.58s/trial, best loss: 0.03826835975527505]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 14s - 59ms/step - ia: 0.5529 - loss: 1.2374 - mae: 0.7552 - rmse: 1.0042 - smape: 1.0611 - val_ia: 0.7135 - val_loss: 0.1701 - val_mae: 0.2893 - val_rmse: 0.3896 - val_smape: 0.6562

Epoch 2/128

240/240 - 2s - 8ms/step - ia: 0.7308 - loss: 0.2978 - mae: 0.3901 - rmse: 0.5401 - smape: 0.7672 - val_ia: 0.7745 - val_loss: 0.1096 - val_mae: 0.2255 - val_rmse: 0.3096 - val_smape: 0.5394

Epoch 3/128

240/240 - 1s - 4ms/step - ia: 0.7759 - loss: 0.2113 - mae: 0.3210 - rmse: 0.4543 - smape: 0.6659 - val_ia: 0.7981 - val_loss: 0.0906 - val_mae: 0.2021 - val_rmse: 0.2809 - val_smape: 0.4914

Epoch 4/128

240/240 - 2s - 6ms/step - ia: 0.7984 - loss: 0.1730 - mae: 0.2874 - rmse: 0.4113 - smape: 0.6142 - val_ia: 0.8108 - val_loss: 0.0823 - val_mae: 0.1886 - val_rmse: 0.2665 - val_smape: 0.4604

Epoch 5/128

240/240 - 2s - 9ms/step - ia: 0.8116 - loss: 0.1571 - mae: 0.2680 - rmse: 0.3914 - smape: 0.5776 - val_ia: 0.8316 - val_loss: 0.0718 - val_mae: 0.1698 - val_rmse: 0.2482 - val_smape: 0.4288

Epoch 6/128

240/240 - 3s - 12ms/step - ia: 0.8189 - loss: 0.1485 - mae: 0.2579 - rmse: 0.3799 - smape: 0.5544 - val_ia: 0.8296 - val_loss: 0.0707 - val_mae: 0.1702 - val_rmse: 0.2459 - val_smape: 0.4259

Epoch 7/128

240/240 - 3s - 14ms/step - ia: 0.8246 - loss: 0.1398 - mae: 0.2495 - rmse: 0.3684 - smape: 0.5414 - val_ia: 0.8314 - val_loss: 0.0697 - val_mae: 0.1682 - val_rmse: 0.2453 - val_smape: 0.4282

Epoch 8/128

240/240 - 2s - 9ms/step - ia: 0.8304 - loss: 0.1353 - mae: 0.2421 - rmse: 0.3618 - smape: 0.5247 - val_ia: 0.8388 - val_loss: 0.0671 - val_mae: 0.1610 - val_rmse: 0.2378 - val_smape: 0.4034

Epoch 9/128

240/240 - 1s - 6ms/step - ia: 0.8326 - loss: 0.1309 - mae: 0.2384 - rmse: 0.3558 - smape: 0.5165 - val_ia: 0.8394 - val_loss: 0.0669 - val_mae: 0.1605 - val_rmse: 0.2378 - val_smape: 0.4030

Epoch 10/128

240/240 - 1s - 5ms/step - ia: 0.8351 - loss: 0.1281 - mae: 0.2354 - rmse: 0.3523 - smape: 0.5119 - val_ia: 0.8445 - val_loss: 0.0645 - val_mae: 0.1561 - val_rmse: 0.2329 - val_smape: 0.3934

Epoch 11/128

240/240 - 1s - 4ms/step - ia: 0.8373 - loss: 0.1261 - mae: 0.2318 - rmse: 0.3497 - smape: 0.5050 - val_ia: 0.8520 - val_loss: 0.0613 - val_mae: 0.1487 - val_rmse: 0.2265 - val_smape: 0.3832

Epoch 12/128

240/240 - 1s - 4ms/step - ia: 0.8392 - loss: 0.1239 - mae: 0.2293 - rmse: 0.3465 - smape: 0.4964 - val_ia: 0.8516 - val_loss: 0.0619 - val_mae: 0.1495 - val_rmse: 0.2278 - val_smape: 0.3835

Epoch 13/128

240/240 - 1s - 4ms/step - ia: 0.8412 - loss: 0.1223 - mae: 0.2269 - rmse: 0.3432 - smape: 0.4900 - val_ia: 0.8574 - val_loss: 0.0602 - val_mae: 0.1450 - val_rmse: 0.2241 - val_smape: 0.3763

Epoch 14/128

240/240 - 1s - 5ms/step - ia: 0.8422 - loss: 0.1212 - mae: 0.2253 - rmse: 0.3419 - smape: 0.4874 - val_ia: 0.8578 - val_loss: 0.0595 - val_mae: 0.1439 - val_rmse: 0.2224 - val_smape: 0.3732

Epoch 15/128

240/240 - 2s - 7ms/step - ia: 0.8432 - loss: 0.1192 - mae: 0.2237 - rmse: 0.3396 - smape: 0.4834 - val_ia: 0.8637 - val_loss: 0.0582 - val_mae: 0.1390 - val_rmse: 0.2196 - val_smape: 0.3673

Epoch 16/128

240/240 - 1s - 5ms/step - ia: 0.8432 - loss: 0.1213 - mae: 0.2242 - rmse: 0.3424 - smape: 0.4783 - val_ia: 0.8463 - val_loss: 0.0626 - val_mae: 0.1529 - val_rmse: 0.2288 - val_smape: 0.3869

Epoch 17/128

240/240 - 1s - 4ms/step - ia: 0.8436 - loss: 0.1197 - mae: 0.2235 - rmse: 0.3403 - smape: 0.4803 - val_ia: 0.8449 - val_loss: 0.0636 - val_mae: 0.1564 - val_rmse: 0.2303 - val_smape: 0.3902

Epoch 18/128

240/240 - 1s - 6ms/step - ia: 0.8452 - loss: 0.1177 - mae: 0.2212 - rmse: 0.3370 - smape: 0.4767 - val_ia: 0.8611 - val_loss: 0.0584 - val_mae: 0.1405 - val_rmse: 0.2201 - val_smape: 0.3695

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.8447 - loss: 0.1187 - mae: 0.2214 - rmse: 0.3379 - smape: 0.4763 - val_ia: 0.8458 - val_loss: 0.0639 - val_mae: 0.1545 - val_rmse: 0.2301 - val_smape: 0.3839

Epoch 20/128

240/240 - 1s - 3ms/step - ia: 0.8455 - loss: 0.1182 - mae: 0.2203 - rmse: 0.3370 - smape: 0.4741 - val_ia: 0.8644 - val_loss: 0.0582 - val_mae: 0.1387 - val_rmse: 0.2197 - val_smape: 0.3680

Epoch 21/128

240/240 - 2s - 8ms/step - ia: 0.8464 - loss: 0.1138 - mae: 0.2190 - rmse: 0.3324 - smape: 0.4731 - val_ia: 0.8424 - val_loss: 0.0643 - val_mae: 0.1561 - val_rmse: 0.2315 - val_smape: 0.3875

Epoch 22/128

240/240 - 1s - 4ms/step - ia: 0.8471 - loss: 0.1166 - mae: 0.2187 - rmse: 0.3351 - smape: 0.4699 - val_ia: 0.8619 - val_loss: 0.0582 - val_mae: 0.1406 - val_rmse: 0.2194 - val_smape: 0.3664

Epoch 23/128

240/240 - 1s - 4ms/step - ia: 0.8475 - loss: 0.1130 - mae: 0.2178 - rmse: 0.3313 - smape: 0.4689 - val_ia: 0.8493 - val_loss: 0.0625 - val_mae: 0.1502 - val_rmse: 0.2280 - val_smape: 0.3777

Epoch 24/128

240/240 - 1s - 5ms/step - ia: 0.8458 - loss: 0.1173 - mae: 0.2194 - rmse: 0.3370 - smape: 0.4709 - val_ia: 0.8574 - val_loss: 0.0589 - val_mae: 0.1446 - val_rmse: 0.2223 - val_smape: 0.3800

Epoch 25/128

240/240 - 1s - 4ms/step - ia: 0.8486 - loss: 0.1148 - mae: 0.2165 - rmse: 0.3333 - smape: 0.4665 - val_ia: 0.8561 - val_loss: 0.0604 - val_mae: 0.1441 - val_rmse: 0.2234 - val_smape: 0.3671

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.8470 - loss: 0.1169 - mae: 0.2178 - rmse: 0.3363 - smape: 0.4658 - val_ia: 0.8351 - val_loss: 0.0664 - val_mae: 0.1619 - val_rmse: 0.2361 - val_smape: 0.3971

Epoch 27/128

240/240 - 1s - 3ms/step - ia: 0.8472 - loss: 0.1183 - mae: 0.2182 - rmse: 0.3360 - smape: 0.4672 - val_ia: 0.8642 - val_loss: 0.0574 - val_mae: 0.1376 - val_rmse: 0.2174 - val_smape: 0.3615

Epoch 28/128

240/240 - 1s - 2ms/step - ia: 0.8483 - loss: 0.1168 - mae: 0.2167 - rmse: 0.3347 - smape: 0.4652 - val_ia: 0.8556 - val_loss: 0.0608 - val_mae: 0.1453 - val_rmse: 0.2242 - val_smape: 0.3700

Epoch 29/128

240/240 - 1s - 2ms/step - ia: 0.8491 - loss: 0.1136 - mae: 0.2148 - rmse: 0.3308 - smape: 0.4629 - val_ia: 0.8538 - val_loss: 0.0612 - val_mae: 0.1482 - val_rmse: 0.2246 - val_smape: 0.3747

Epoch 30/128

240/240 - 1s - 3ms/step - ia: 0.8489 - loss: 0.1145 - mae: 0.2161 - rmse: 0.3334 - smape: 0.4629 - val_ia: 0.8576 - val_loss: 0.0598 - val_mae: 0.1435 - val_rmse: 0.2223 - val_smape: 0.3695

Epoch 31/128

240/240 - 1s - 3ms/step - ia: 0.8487 - loss: 0.1151 - mae: 0.2160 - rmse: 0.3324 - smape: 0.4612 - val_ia: 0.8598 - val_loss: 0.0588 - val_mae: 0.1434 - val_rmse: 0.2211 - val_smape: 0.3760

Epoch 32/128

240/240 - 1s - 2ms/step - ia: 0.8489 - loss: 0.1152 - mae: 0.2158 - rmse: 0.3334 - smape: 0.4631 - val_ia: 0.8574 - val_loss: 0.0590 - val_mae: 0.1425 - val_rmse: 0.2210 - val_smape: 0.3669

Epoch 33/128

240/240 - 1s - 3ms/step - ia: 0.8492 - loss: 0.1135 - mae: 0.2151 - rmse: 0.3303 - smape: 0.4610 - val_ia: 0.8532 - val_loss: 0.0609 - val_mae: 0.1466 - val_rmse: 0.2247 - val_smape: 0.3727

Epoch 34/128

240/240 - 1s - 3ms/step - ia: 0.8493 - loss: 0.1131 - mae: 0.2151 - rmse: 0.3303 - smape: 0.4587 - val_ia: 0.8530 - val_loss: 0.0618 - val_mae: 0.1476 - val_rmse: 0.2252 - val_smape: 0.3691

Epoch 35/128

240/240 - 1s - 3ms/step - ia: 0.8489 - loss: 0.1147 - mae: 0.2155 - rmse: 0.3317 - smape: 0.4635 - val_ia: 0.8623 - val_loss: 0.0579 - val_mae: 0.1391 - val_rmse: 0.2182 - val_smape: 0.3615

Epoch 36/128

240/240 - 1s - 2ms/step - ia: 0.8498 - loss: 0.1142 - mae: 0.2143 - rmse: 0.3312 - smape: 0.4589 - val_ia: 0.8642 - val_loss: 0.0575 - val_mae: 0.1388 - val_rmse: 0.2179 - val_smape: 0.3660

Epoch 37/128

240/240 - 1s - 3ms/step - ia: 0.8493 - loss: 0.1151 - mae: 0.2151 - rmse: 0.3330 - smape: 0.4611 - val_ia: 0.8641 - val_loss: 0.0575 - val_mae: 0.1380 - val_rmse: 0.2175 - val_smape: 0.3614

Epoch 38/128

240/240 - 1s - 3ms/step - ia: 0.8504 - loss: 0.1133 - mae: 0.2135 - rmse: 0.3302 - smape: 0.4584 - val_ia: 0.8530 - val_loss: 0.0595 - val_mae: 0.1467 - val_rmse: 0.2223 - val_smape: 0.3743

Epoch 39/128

240/240 - 1s - 4ms/step - ia: 0.8489 - loss: 0.1148 - mae: 0.2152 - rmse: 0.3330 - smape: 0.4614 - val_ia: 0.8625 - val_loss: 0.0595 - val_mae: 0.1411 - val_rmse: 0.2205 - val_smape: 0.3621

Epoch 40/128

240/240 - 1s - 3ms/step - ia: 0.8500 - loss: 0.1145 - mae: 0.2144 - rmse: 0.3324 - smape: 0.4552 - val_ia: 0.8480 - val_loss: 0.0620 - val_mae: 0.1513 - val_rmse: 0.2270 - val_smape: 0.3797

Epoch 41/128

240/240 - 1s - 3ms/step - ia: 0.8500 - loss: 0.1146 - mae: 0.2139 - rmse: 0.3312 - smape: 0.4565 - val_ia: 0.8663 - val_loss: 0.0568 - val_mae: 0.1361 - val_rmse: 0.2162 - val_smape: 0.3591

Epoch 42/128

240/240 - 1s - 3ms/step - ia: 0.8508 - loss: 0.1119 - mae: 0.2128 - rmse: 0.3286 - smape: 0.4546 - val_ia: 0.8600 - val_loss: 0.0585 - val_mae: 0.1412 - val_rmse: 0.2204 - val_smape: 0.3700

Epoch 43/128

240/240 - 1s - 3ms/step - ia: 0.8506 - loss: 0.1123 - mae: 0.2133 - rmse: 0.3290 - smape: 0.4585 - val_ia: 0.8582 - val_loss: 0.0591 - val_mae: 0.1441 - val_rmse: 0.2210 - val_smape: 0.3723

Epoch 44/128

240/240 - 1s - 2ms/step - ia: 0.8487 - loss: 0.1142 - mae: 0.2156 - rmse: 0.3320 - smape: 0.4605 - val_ia: 0.8683 - val_loss: 0.0566 - val_mae: 0.1342 - val_rmse: 0.2157 - val_smape: 0.3575

Epoch 45/128

240/240 - 1s - 3ms/step - ia: 0.8516 - loss: 0.1116 - mae: 0.2123 - rmse: 0.3276 - smape: 0.4555 - val_ia: 0.8424 - val_loss: 0.0649 - val_mae: 0.1585 - val_rmse: 0.2314 - val_smape: 0.3896

Epoch 46/128

240/240 - 1s - 3ms/step - ia: 0.8514 - loss: 0.1105 - mae: 0.2124 - rmse: 0.3271 - smape: 0.4554 - val_ia: 0.8637 - val_loss: 0.0579 - val_mae: 0.1378 - val_rmse: 0.2183 - val_smape: 0.3584

Epoch 47/128

240/240 - 1s - 6ms/step - ia: 0.8510 - loss: 0.1130 - mae: 0.2126 - rmse: 0.3293 - smape: 0.4557 - val_ia: 0.8498 - val_loss: 0.0614 - val_mae: 0.1508 - val_rmse: 0.2255 - val_smape: 0.3830

Epoch 48/128

240/240 - 1s - 3ms/step - ia: 0.8515 - loss: 0.1124 - mae: 0.2117 - rmse: 0.3288 - smape: 0.4544 - val_ia: 0.8454 - val_loss: 0.0627 - val_mae: 0.1541 - val_rmse: 0.2280 - val_smape: 0.3834

Epoch 49/128

240/240 - 1s - 3ms/step - ia: 0.8505 - loss: 0.1143 - mae: 0.2135 - rmse: 0.3321 - smape: 0.4552 - val_ia: 0.8613 - val_loss: 0.0582 - val_mae: 0.1403 - val_rmse: 0.2203 - val_smape: 0.3705

Epoch 50/128

240/240 - 1s - 3ms/step - ia: 0.8506 - loss: 0.1132 - mae: 0.2130 - rmse: 0.3303 - smape: 0.4569 - val_ia: 0.8596 - val_loss: 0.0586 - val_mae: 0.1409 - val_rmse: 0.2205 - val_smape: 0.3683

Epoch 51/128

240/240 - 1s - 3ms/step - ia: 0.8521 - loss: 0.1083 - mae: 0.2108 - rmse: 0.3235 - smape: 0.4530 - val_ia: 0.8693 - val_loss: 0.0564 - val_mae: 0.1340 - val_rmse: 0.2150 - val_smape: 0.3550

Epoch 52/128

240/240 - 1s - 3ms/step - ia: 0.8505 - loss: 0.1154 - mae: 0.2134 - rmse: 0.3334 - smape: 0.4546 - val_ia: 0.8648 - val_loss: 0.0574 - val_mae: 0.1368 - val_rmse: 0.2172 - val_smape: 0.3598

Epoch 53/128

240/240 - 1s - 3ms/step - ia: 0.8522 - loss: 0.1111 - mae: 0.2117 - rmse: 0.3273 - smape: 0.4506 - val_ia: 0.8522 - val_loss: 0.0602 - val_mae: 0.1474 - val_rmse: 0.2236 - val_smape: 0.3757

Epoch 54/128

240/240 - 1s - 6ms/step - ia: 0.8493 - loss: 0.1154 - mae: 0.2150 - rmse: 0.3328 - smape: 0.4590 - val_ia: 0.8580 - val_loss: 0.0593 - val_mae: 0.1421 - val_rmse: 0.2223 - val_smape: 0.3690

Epoch 55/128

240/240 - 1s - 4ms/step - ia: 0.8515 - loss: 0.1106 - mae: 0.2124 - rmse: 0.3262 - smape: 0.4561 - val_ia: 0.8559 - val_loss: 0.0607 - val_mae: 0.1452 - val_rmse: 0.2240 - val_smape: 0.3714

Epoch 56/128

240/240 - 1s - 3ms/step - ia: 0.8509 - loss: 0.1117 - mae: 0.2130 - rmse: 0.3283 - smape: 0.4545 - val_ia: 0.8535 - val_loss: 0.0622 - val_mae: 0.1496 - val_rmse: 0.2262 - val_smape: 0.3787

Epoch 57/128

240/240 - 1s - 3ms/step - ia: 0.8508 - loss: 0.1124 - mae: 0.2129 - rmse: 0.3295 - smape: 0.4552 - val_ia: 0.8632 - val_loss: 0.0579 - val_mae: 0.1384 - val_rmse: 0.2182 - val_smape: 0.3605

Epoch 58/128

240/240 - 1s - 3ms/step - ia: 0.8521 - loss: 0.1119 - mae: 0.2119 - rmse: 0.3282 - smape: 0.4516 - val_ia: 0.8515 - val_loss: 0.0619 - val_mae: 0.1487 - val_rmse: 0.2267 - val_smape: 0.3775

Epoch 59/128

240/240 - 1s - 2ms/step - ia: 0.8512 - loss: 0.1114 - mae: 0.2124 - rmse: 0.3285 - smape: 0.4552 - val_ia: 0.8472 - val_loss: 0.0621 - val_mae: 0.1520 - val_rmse: 0.2269 - val_smape: 0.3785

Epoch 60/128

240/240 - 1s - 3ms/step - ia: 0.8506 - loss: 0.1139 - mae: 0.2134 - rmse: 0.3307 - smape: 0.4555 - val_ia: 0.8618 - val_loss: 0.0579 - val_mae: 0.1396 - val_rmse: 0.2181 - val_smape: 0.3618

Epoch 61/128

240/240 - 1s - 3ms/step - ia: 0.8506 - loss: 0.1145 - mae: 0.2131 - rmse: 0.3313 - smape: 0.4579 - val_ia: 0.8449 - val_loss: 0.0635 - val_mae: 0.1543 - val_rmse: 0.2298 - val_smape: 0.3859

Epoch 62/128

240/240 - 1s - 3ms/step - ia: 0.8517 - loss: 0.1092 - mae: 0.2117 - rmse: 0.3254 - smape: 0.4561 - val_ia: 0.8511 - val_loss: 0.0626 - val_mae: 0.1499 - val_rmse: 0.2264 - val_smape: 0.3732

Epoch 63/128

240/240 - 1s - 3ms/step - ia: 0.8512 - loss: 0.1130 - mae: 0.2122 - rmse: 0.3293 - smape: 0.4544 - val_ia: 0.8600 - val_loss: 0.0591 - val_mae: 0.1427 - val_rmse: 0.2202 - val_smape: 0.3685

Epoch 64/128

240/240 - 1s - 3ms/step - ia: 0.8504 - loss: 0.1140 - mae: 0.2137 - rmse: 0.3317 - smape: 0.4560 - val_ia: 0.8653 - val_loss: 0.0572 - val_mae: 0.1369 - val_rmse: 0.2167 - val_smape: 0.3591

Epoch 65/128

240/240 - 1s - 3ms/step - ia: 0.8530 - loss: 0.1112 - mae: 0.2103 - rmse: 0.3271 - smape: 0.4508 - val_ia: 0.8582 - val_loss: 0.0590 - val_mae: 0.1433 - val_rmse: 0.2203 - val_smape: 0.3689

Epoch 66/128

240/240 - 1s - 4ms/step - ia: 0.8523 - loss: 0.1100 - mae: 0.2112 - rmse: 0.3257 - smape: 0.4511 - val_ia: 0.8546 - val_loss: 0.0605 - val_mae: 0.1463 - val_rmse: 0.2229 - val_smape: 0.3698

Epoch 66: early stopping

Restoring model weights from the end of the best epoch: 51.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 25s 191ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 75%|███████▌  | 9/12 [1:00:29<11:25, 228.40s/trial, best loss: 0.03826835975527505]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 10s - 5ms/step - ia: 0.5398 - loss: 0.6912 - mae: 0.6159 - rmse: 0.7947 - smape: 1.0663 - val_ia: 0.4172 - val_loss: 0.2253 - val_mae: 0.3011 - val_rmse: 0.3653 - val_smape: 0.6366

Epoch 2/128

1916/1916 - 6s - 3ms/step - ia: 0.6921 - loss: 0.3320 - mae: 0.4134 - rmse: 0.5487 - smape: 0.8055 - val_ia: 0.4804 - val_loss: 0.1522 - val_mae: 0.2427 - val_rmse: 0.3038 - val_smape: 0.5541

Epoch 3/128

1916/1916 - 5s - 3ms/step - ia: 0.7465 - loss: 0.2310 - mae: 0.3347 - rmse: 0.4547 - smape: 0.7024 - val_ia: 0.4974 - val_loss: 0.1205 - val_mae: 0.2256 - val_rmse: 0.2831 - val_smape: 0.5324

Epoch 4/128

1916/1916 - 5s - 2ms/step - ia: 0.7705 - loss: 0.1895 - mae: 0.3007 - rmse: 0.4100 - smape: 0.6539 - val_ia: 0.5198 - val_loss: 0.1056 - val_mae: 0.2113 - val_rmse: 0.2671 - val_smape: 0.5128

Epoch 5/128

1916/1916 - 5s - 3ms/step - ia: 0.7891 - loss: 0.1646 - mae: 0.2787 - rmse: 0.3811 - smape: 0.6201 - val_ia: 0.5302 - val_loss: 0.0987 - val_mae: 0.2050 - val_rmse: 0.2592 - val_smape: 0.5032

Epoch 6/128

1916/1916 - 5s - 3ms/step - ia: 0.7973 - loss: 0.1527 - mae: 0.2662 - rmse: 0.3651 - smape: 0.6001 - val_ia: 0.5372 - val_loss: 0.0924 - val_mae: 0.2003 - val_rmse: 0.2529 - val_smape: 0.4903

Epoch 7/128

1916/1916 - 5s - 3ms/step - ia: 0.8075 - loss: 0.1427 - mae: 0.2542 - rmse: 0.3511 - smape: 0.5810 - val_ia: 0.5663 - val_loss: 0.0861 - val_mae: 0.1863 - val_rmse: 0.2400 - val_smape: 0.4664

Epoch 8/128

1916/1916 - 6s - 3ms/step - ia: 0.8143 - loss: 0.1336 - mae: 0.2457 - rmse: 0.3403 - smape: 0.5631 - val_ia: 0.5623 - val_loss: 0.0839 - val_mae: 0.1870 - val_rmse: 0.2392 - val_smape: 0.4664

Epoch 9/128

1916/1916 - 10s - 5ms/step - ia: 0.8203 - loss: 0.1276 - mae: 0.2388 - rmse: 0.3320 - smape: 0.5501 - val_ia: 0.5937 - val_loss: 0.0787 - val_mae: 0.1734 - val_rmse: 0.2273 - val_smape: 0.4446

Epoch 10/128

1916/1916 - 5s - 3ms/step - ia: 0.8246 - loss: 0.1242 - mae: 0.2333 - rmse: 0.3258 - smape: 0.5407 - val_ia: 0.5964 - val_loss: 0.0781 - val_mae: 0.1730 - val_rmse: 0.2260 - val_smape: 0.4390

Epoch 11/128

1916/1916 - 10s - 5ms/step - ia: 0.8304 - loss: 0.1179 - mae: 0.2272 - rmse: 0.3179 - smape: 0.5260 - val_ia: 0.6089 - val_loss: 0.0754 - val_mae: 0.1679 - val_rmse: 0.2211 - val_smape: 0.4316

Epoch 12/128

1916/1916 - 6s - 3ms/step - ia: 0.8323 - loss: 0.1148 - mae: 0.2234 - rmse: 0.3126 - smape: 0.5222 - val_ia: 0.5925 - val_loss: 0.0774 - val_mae: 0.1749 - val_rmse: 0.2268 - val_smape: 0.4387

Epoch 13/128

1916/1916 - 6s - 3ms/step - ia: 0.8354 - loss: 0.1130 - mae: 0.2208 - rmse: 0.3107 - smape: 0.5155 - val_ia: 0.5989 - val_loss: 0.0735 - val_mae: 0.1695 - val_rmse: 0.2212 - val_smape: 0.4296

Epoch 14/128

1916/1916 - 5s - 3ms/step - ia: 0.8387 - loss: 0.1101 - mae: 0.2159 - rmse: 0.3056 - smape: 0.5058 - val_ia: 0.6133 - val_loss: 0.0723 - val_mae: 0.1646 - val_rmse: 0.2168 - val_smape: 0.4206

Epoch 15/128

1916/1916 - 5s - 2ms/step - ia: 0.8409 - loss: 0.1080 - mae: 0.2138 - rmse: 0.3027 - smape: 0.4989 - val_ia: 0.6108 - val_loss: 0.0733 - val_mae: 0.1667 - val_rmse: 0.2187 - val_smape: 0.4216

Epoch 16/128

1916/1916 - 6s - 3ms/step - ia: 0.8428 - loss: 0.1070 - mae: 0.2118 - rmse: 0.3000 - smape: 0.4956 - val_ia: 0.6287 - val_loss: 0.0689 - val_mae: 0.1582 - val_rmse: 0.2106 - val_smape: 0.4082

Epoch 17/128

1916/1916 - 10s - 5ms/step - ia: 0.8456 - loss: 0.1028 - mae: 0.2078 - rmse: 0.2947 - smape: 0.4907 - val_ia: 0.6341 - val_loss: 0.0680 - val_mae: 0.1562 - val_rmse: 0.2087 - val_smape: 0.4035

Epoch 18/128

1916/1916 - 10s - 5ms/step - ia: 0.8457 - loss: 0.1028 - mae: 0.2077 - rmse: 0.2943 - smape: 0.4877 - val_ia: 0.6139 - val_loss: 0.0692 - val_mae: 0.1628 - val_rmse: 0.2139 - val_smape: 0.4132

Epoch 19/128

1916/1916 - 5s - 2ms/step - ia: 0.8475 - loss: 0.1012 - mae: 0.2049 - rmse: 0.2917 - smape: 0.4815 - val_ia: 0.6348 - val_loss: 0.0678 - val_mae: 0.1563 - val_rmse: 0.2084 - val_smape: 0.4020

Epoch 20/128

1916/1916 - 5s - 3ms/step - ia: 0.8479 - loss: 0.1016 - mae: 0.2045 - rmse: 0.2927 - smape: 0.4796 - val_ia: 0.6330 - val_loss: 0.0691 - val_mae: 0.1582 - val_rmse: 0.2099 - val_smape: 0.4025

Epoch 21/128

1916/1916 - 10s - 5ms/step - ia: 0.8500 - loss: 0.0992 - mae: 0.2025 - rmse: 0.2879 - smape: 0.4750 - val_ia: 0.6250 - val_loss: 0.0674 - val_mae: 0.1585 - val_rmse: 0.2098 - val_smape: 0.4021

Epoch 22/128

1916/1916 - 6s - 3ms/step - ia: 0.8505 - loss: 0.0974 - mae: 0.2010 - rmse: 0.2867 - smape: 0.4725 - val_ia: 0.6379 - val_loss: 0.0648 - val_mae: 0.1528 - val_rmse: 0.2044 - val_smape: 0.3932

Epoch 23/128

1916/1916 - 10s - 5ms/step - ia: 0.8516 - loss: 0.0979 - mae: 0.1998 - rmse: 0.2860 - smape: 0.4686 - val_ia: 0.6294 - val_loss: 0.0670 - val_mae: 0.1574 - val_rmse: 0.2085 - val_smape: 0.3980

Epoch 24/128

1916/1916 - 10s - 5ms/step - ia: 0.8524 - loss: 0.0972 - mae: 0.1995 - rmse: 0.2855 - smape: 0.4683 - val_ia: 0.6430 - val_loss: 0.0633 - val_mae: 0.1503 - val_rmse: 0.2021 - val_smape: 0.3888

Epoch 25/128

1916/1916 - 11s - 6ms/step - ia: 0.8540 - loss: 0.0953 - mae: 0.1973 - rmse: 0.2822 - smape: 0.4643 - val_ia: 0.6307 - val_loss: 0.0637 - val_mae: 0.1537 - val_rmse: 0.2050 - val_smape: 0.3944

Epoch 26/128

1916/1916 - 10s - 5ms/step - ia: 0.8540 - loss: 0.0965 - mae: 0.1978 - rmse: 0.2838 - smape: 0.4616 - val_ia: 0.6507 - val_loss: 0.0631 - val_mae: 0.1477 - val_rmse: 0.2000 - val_smape: 0.3818

Epoch 27/128

1916/1916 - 9s - 5ms/step - ia: 0.8554 - loss: 0.0951 - mae: 0.1960 - rmse: 0.2817 - smape: 0.4624 - val_ia: 0.6368 - val_loss: 0.0638 - val_mae: 0.1524 - val_rmse: 0.2036 - val_smape: 0.3891

Epoch 28/128

1916/1916 - 5s - 2ms/step - ia: 0.8566 - loss: 0.0942 - mae: 0.1946 - rmse: 0.2796 - smape: 0.4592 - val_ia: 0.6369 - val_loss: 0.0649 - val_mae: 0.1537 - val_rmse: 0.2047 - val_smape: 0.3880

Epoch 29/128

1916/1916 - 5s - 3ms/step - ia: 0.8576 - loss: 0.0937 - mae: 0.1933 - rmse: 0.2790 - smape: 0.4541 - val_ia: 0.6283 - val_loss: 0.0640 - val_mae: 0.1552 - val_rmse: 0.2059 - val_smape: 0.3934

Epoch 30/128

1916/1916 - 4s - 2ms/step - ia: 0.8582 - loss: 0.0916 - mae: 0.1922 - rmse: 0.2763 - smape: 0.4521 - val_ia: 0.6448 - val_loss: 0.0649 - val_mae: 0.1515 - val_rmse: 0.2030 - val_smape: 0.3835

Epoch 31/128

1916/1916 - 4s - 2ms/step - ia: 0.8562 - loss: 0.0939 - mae: 0.1943 - rmse: 0.2796 - smape: 0.4550 - val_ia: 0.6396 - val_loss: 0.0639 - val_mae: 0.1523 - val_rmse: 0.2031 - val_smape: 0.3862

Epoch 32/128

1916/1916 - 6s - 3ms/step - ia: 0.8585 - loss: 0.0921 - mae: 0.1926 - rmse: 0.2756 - smape: 0.4518 - val_ia: 0.6503 - val_loss: 0.0627 - val_mae: 0.1483 - val_rmse: 0.1997 - val_smape: 0.3795

Epoch 33/128

1916/1916 - 10s - 5ms/step - ia: 0.8574 - loss: 0.0923 - mae: 0.1924 - rmse: 0.2770 - smape: 0.4503 - val_ia: 0.6361 - val_loss: 0.0625 - val_mae: 0.1519 - val_rmse: 0.2025 - val_smape: 0.3867

Epoch 34/128

1916/1916 - 9s - 5ms/step - ia: 0.8601 - loss: 0.0891 - mae: 0.1897 - rmse: 0.2728 - smape: 0.4477 - val_ia: 0.6556 - val_loss: 0.0592 - val_mae: 0.1429 - val_rmse: 0.1949 - val_smape: 0.3747

Epoch 35/128

1916/1916 - 5s - 3ms/step - ia: 0.8592 - loss: 0.0913 - mae: 0.1910 - rmse: 0.2745 - smape: 0.4481 - val_ia: 0.6490 - val_loss: 0.0601 - val_mae: 0.1463 - val_rmse: 0.1972 - val_smape: 0.3791

Epoch 36/128

1916/1916 - 6s - 3ms/step - ia: 0.8607 - loss: 0.0904 - mae: 0.1896 - rmse: 0.2730 - smape: 0.4459 - val_ia: 0.6556 - val_loss: 0.0599 - val_mae: 0.1438 - val_rmse: 0.1955 - val_smape: 0.3747

Epoch 37/128

1916/1916 - 5s - 3ms/step - ia: 0.8602 - loss: 0.0899 - mae: 0.1901 - rmse: 0.2725 - smape: 0.4459 - val_ia: 0.6498 - val_loss: 0.0595 - val_mae: 0.1450 - val_rmse: 0.1963 - val_smape: 0.3764

Epoch 38/128

1916/1916 - 5s - 3ms/step - ia: 0.8611 - loss: 0.0895 - mae: 0.1886 - rmse: 0.2722 - smape: 0.4440 - val_ia: 0.6680 - val_loss: 0.0584 - val_mae: 0.1394 - val_rmse: 0.1918 - val_smape: 0.3681

Epoch 39/128

1916/1916 - 5s - 3ms/step - ia: 0.8617 - loss: 0.0890 - mae: 0.1882 - rmse: 0.2715 - smape: 0.4441 - val_ia: 0.6625 - val_loss: 0.0590 - val_mae: 0.1415 - val_rmse: 0.1933 - val_smape: 0.3704

Epoch 40/128

1916/1916 - 5s - 3ms/step - ia: 0.8622 - loss: 0.0881 - mae: 0.1865 - rmse: 0.2693 - smape: 0.4406 - val_ia: 0.6629 - val_loss: 0.0604 - val_mae: 0.1429 - val_rmse: 0.1948 - val_smape: 0.3692

Epoch 41/128

1916/1916 - 5s - 3ms/step - ia: 0.8620 - loss: 0.0868 - mae: 0.1868 - rmse: 0.2691 - smape: 0.4431 - val_ia: 0.6539 - val_loss: 0.0606 - val_mae: 0.1456 - val_rmse: 0.1967 - val_smape: 0.3748

Epoch 42/128

1916/1916 - 5s - 3ms/step - ia: 0.8616 - loss: 0.0884 - mae: 0.1868 - rmse: 0.2701 - smape: 0.4400 - val_ia: 0.6620 - val_loss: 0.0579 - val_mae: 0.1402 - val_rmse: 0.1921 - val_smape: 0.3699

Epoch 43/128

1916/1916 - 5s - 3ms/step - ia: 0.8627 - loss: 0.0875 - mae: 0.1862 - rmse: 0.2689 - smape: 0.4384 - val_ia: 0.6564 - val_loss: 0.0595 - val_mae: 0.1439 - val_rmse: 0.1951 - val_smape: 0.3730

Epoch 44/128

1916/1916 - 5s - 3ms/step - ia: 0.8629 - loss: 0.0879 - mae: 0.1856 - rmse: 0.2696 - smape: 0.4365 - val_ia: 0.6576 - val_loss: 0.0600 - val_mae: 0.1438 - val_rmse: 0.1952 - val_smape: 0.3714

Epoch 45/128

1916/1916 - 5s - 2ms/step - ia: 0.8628 - loss: 0.0860 - mae: 0.1851 - rmse: 0.2665 - smape: 0.4384 - val_ia: 0.6596 - val_loss: 0.0596 - val_mae: 0.1436 - val_rmse: 0.1947 - val_smape: 0.3734

Epoch 46/128

1916/1916 - 4s - 2ms/step - ia: 0.8630 - loss: 0.0845 - mae: 0.1859 - rmse: 0.2657 - smape: 0.4398 - val_ia: 0.6526 - val_loss: 0.0607 - val_mae: 0.1461 - val_rmse: 0.1970 - val_smape: 0.3748

Epoch 47/128

1916/1916 - 5s - 3ms/step - ia: 0.8633 - loss: 0.0878 - mae: 0.1864 - rmse: 0.2687 - smape: 0.4408 - val_ia: 0.6555 - val_loss: 0.0577 - val_mae: 0.1419 - val_rmse: 0.1933 - val_smape: 0.3720

Epoch 48/128

1916/1916 - 10s - 5ms/step - ia: 0.8634 - loss: 0.0867 - mae: 0.1857 - rmse: 0.2676 - smape: 0.4386 - val_ia: 0.6637 - val_loss: 0.0584 - val_mae: 0.1406 - val_rmse: 0.1925 - val_smape: 0.3672

Epoch 49/128

1916/1916 - 5s - 3ms/step - ia: 0.8638 - loss: 0.0862 - mae: 0.1851 - rmse: 0.2654 - smape: 0.4384 - val_ia: 0.6649 - val_loss: 0.0581 - val_mae: 0.1402 - val_rmse: 0.1919 - val_smape: 0.3667

Epoch 50/128

1916/1916 - 5s - 2ms/step - ia: 0.8653 - loss: 0.0840 - mae: 0.1823 - rmse: 0.2636 - smape: 0.4309 - val_ia: 0.6592 - val_loss: 0.0578 - val_mae: 0.1415 - val_rmse: 0.1926 - val_smape: 0.3714

Epoch 51/128

1916/1916 - 4s - 2ms/step - ia: 0.8641 - loss: 0.0863 - mae: 0.1847 - rmse: 0.2667 - smape: 0.4343 - val_ia: 0.6608 - val_loss: 0.0580 - val_mae: 0.1412 - val_rmse: 0.1925 - val_smape: 0.3685

Epoch 52/128

1916/1916 - 5s - 3ms/step - ia: 0.8647 - loss: 0.0859 - mae: 0.1837 - rmse: 0.2662 - smape: 0.4339 - val_ia: 0.6673 - val_loss: 0.0584 - val_mae: 0.1402 - val_rmse: 0.1917 - val_smape: 0.3656

Epoch 53/128

1916/1916 - 10s - 5ms/step - ia: 0.8655 - loss: 0.0855 - mae: 0.1832 - rmse: 0.2646 - smape: 0.4316 - val_ia: 0.6587 - val_loss: 0.0588 - val_mae: 0.1428 - val_rmse: 0.1938 - val_smape: 0.3701

Epoch 54/128

1916/1916 - 5s - 2ms/step - ia: 0.8648 - loss: 0.0869 - mae: 0.1838 - rmse: 0.2670 - smape: 0.4316 - val_ia: 0.6667 - val_loss: 0.0585 - val_mae: 0.1404 - val_rmse: 0.1920 - val_smape: 0.3659

Epoch 55/128

1916/1916 - 5s - 3ms/step - ia: 0.8654 - loss: 0.0864 - mae: 0.1828 - rmse: 0.2648 - smape: 0.4308 - val_ia: 0.6539 - val_loss: 0.0591 - val_mae: 0.1444 - val_rmse: 0.1950 - val_smape: 0.3716

Epoch 56/128

1916/1916 - 5s - 3ms/step - ia: 0.8660 - loss: 0.0839 - mae: 0.1826 - rmse: 0.2636 - smape: 0.4313 - val_ia: 0.6575 - val_loss: 0.0586 - val_mae: 0.1428 - val_rmse: 0.1940 - val_smape: 0.3715

Epoch 57/128

1916/1916 - 5s - 3ms/step - ia: 0.8667 - loss: 0.0837 - mae: 0.1819 - rmse: 0.2627 - smape: 0.4315 - val_ia: 0.6581 - val_loss: 0.0578 - val_mae: 0.1414 - val_rmse: 0.1927 - val_smape: 0.3688

Epoch 58/128

1916/1916 - 5s - 3ms/step - ia: 0.8654 - loss: 0.0834 - mae: 0.1818 - rmse: 0.2629 - smape: 0.4312 - val_ia: 0.6646 - val_loss: 0.0571 - val_mae: 0.1393 - val_rmse: 0.1908 - val_smape: 0.3665

Epoch 59/128

1916/1916 - 10s - 5ms/step - ia: 0.8662 - loss: 0.0843 - mae: 0.1814 - rmse: 0.2632 - smape: 0.4299 - val_ia: 0.6701 - val_loss: 0.0565 - val_mae: 0.1370 - val_rmse: 0.1891 - val_smape: 0.3643

Epoch 60/128

1916/1916 - 10s - 5ms/step - ia: 0.8655 - loss: 0.0839 - mae: 0.1825 - rmse: 0.2636 - smape: 0.4293 - val_ia: 0.6557 - val_loss: 0.0576 - val_mae: 0.1421 - val_rmse: 0.1931 - val_smape: 0.3706

Epoch 61/128

1916/1916 - 10s - 5ms/step - ia: 0.8668 - loss: 0.0844 - mae: 0.1818 - rmse: 0.2634 - smape: 0.4295 - val_ia: 0.6654 - val_loss: 0.0575 - val_mae: 0.1396 - val_rmse: 0.1912 - val_smape: 0.3657

Epoch 62/128

1916/1916 - 5s - 3ms/step - ia: 0.8668 - loss: 0.0843 - mae: 0.1819 - rmse: 0.2627 - smape: 0.4313 - val_ia: 0.6572 - val_loss: 0.0584 - val_mae: 0.1426 - val_rmse: 0.1937 - val_smape: 0.3704

Epoch 63/128

1916/1916 - 4s - 2ms/step - ia: 0.8662 - loss: 0.0838 - mae: 0.1815 - rmse: 0.2628 - smape: 0.4296 - val_ia: 0.6721 - val_loss: 0.0561 - val_mae: 0.1359 - val_rmse: 0.1883 - val_smape: 0.3621

Epoch 64/128

1916/1916 - 4s - 2ms/step - ia: 0.8669 - loss: 0.0832 - mae: 0.1808 - rmse: 0.2614 - smape: 0.4302 - val_ia: 0.6571 - val_loss: 0.0572 - val_mae: 0.1413 - val_rmse: 0.1924 - val_smape: 0.3706

Epoch 65/128

1916/1916 - 4s - 2ms/step - ia: 0.8658 - loss: 0.0840 - mae: 0.1823 - rmse: 0.2642 - smape: 0.4302 - val_ia: 0.6676 - val_loss: 0.0574 - val_mae: 0.1392 - val_rmse: 0.1907 - val_smape: 0.3647

Epoch 66/128

1916/1916 - 6s - 3ms/step - ia: 0.8680 - loss: 0.0834 - mae: 0.1805 - rmse: 0.2612 - smape: 0.4279 - val_ia: 0.6659 - val_loss: 0.0586 - val_mae: 0.1412 - val_rmse: 0.1924 - val_smape: 0.3681

Epoch 67/128

1916/1916 - 5s - 3ms/step - ia: 0.8671 - loss: 0.0831 - mae: 0.1796 - rmse: 0.2613 - smape: 0.4276 - val_ia: 0.6574 - val_loss: 0.0576 - val_mae: 0.1418 - val_rmse: 0.1928 - val_smape: 0.3700

Epoch 68/128

1916/1916 - 5s - 3ms/step - ia: 0.8671 - loss: 0.0832 - mae: 0.1805 - rmse: 0.2620 - smape: 0.4263 - val_ia: 0.6551 - val_loss: 0.0586 - val_mae: 0.1435 - val_rmse: 0.1942 - val_smape: 0.3711

Epoch 69/128

1916/1916 - 5s - 3ms/step - ia: 0.8681 - loss: 0.0825 - mae: 0.1795 - rmse: 0.2605 - smape: 0.4260 - val_ia: 0.6580 - val_loss: 0.0588 - val_mae: 0.1430 - val_rmse: 0.1941 - val_smape: 0.3711

Epoch 70/128

1916/1916 - 10s - 5ms/step - ia: 0.8667 - loss: 0.0839 - mae: 0.1810 - rmse: 0.2631 - smape: 0.4268 - val_ia: 0.6668 - val_loss: 0.0562 - val_mae: 0.1378 - val_rmse: 0.1894 - val_smape: 0.3649

Epoch 71/128

1916/1916 - 5s - 3ms/step - ia: 0.8672 - loss: 0.0834 - mae: 0.1799 - rmse: 0.2613 - smape: 0.4263 - val_ia: 0.6641 - val_loss: 0.0567 - val_mae: 0.1389 - val_rmse: 0.1904 - val_smape: 0.3655

Epoch 72/128

1916/1916 - 4s - 2ms/step - ia: 0.8667 - loss: 0.0842 - mae: 0.1811 - rmse: 0.2632 - smape: 0.4259 - val_ia: 0.6736 - val_loss: 0.0570 - val_mae: 0.1371 - val_rmse: 0.1890 - val_smape: 0.3621

Epoch 73/128

1916/1916 - 6s - 3ms/step - ia: 0.8683 - loss: 0.0823 - mae: 0.1794 - rmse: 0.2607 - smape: 0.4229 - val_ia: 0.6729 - val_loss: 0.0562 - val_mae: 0.1362 - val_rmse: 0.1882 - val_smape: 0.3621

Epoch 74/128

1916/1916 - 5s - 3ms/step - ia: 0.8664 - loss: 0.0833 - mae: 0.1810 - rmse: 0.2615 - smape: 0.4293 - val_ia: 0.6652 - val_loss: 0.0567 - val_mae: 0.1388 - val_rmse: 0.1902 - val_smape: 0.3663

Epoch 75/128

1916/1916 - 6s - 3ms/step - ia: 0.8688 - loss: 0.0813 - mae: 0.1781 - rmse: 0.2593 - smape: 0.4229 - val_ia: 0.6643 - val_loss: 0.0569 - val_mae: 0.1394 - val_rmse: 0.1905 - val_smape: 0.3671

Epoch 76/128

1916/1916 - 9s - 5ms/step - ia: 0.8679 - loss: 0.0836 - mae: 0.1793 - rmse: 0.2601 - smape: 0.4250 - val_ia: 0.6700 - val_loss: 0.0574 - val_mae: 0.1387 - val_rmse: 0.1901 - val_smape: 0.3651

Epoch 77/128

1916/1916 - 5s - 3ms/step - ia: 0.8675 - loss: 0.0829 - mae: 0.1805 - rmse: 0.2611 - smape: 0.4264 - val_ia: 0.6708 - val_loss: 0.0580 - val_mae: 0.1393 - val_rmse: 0.1907 - val_smape: 0.3652

Epoch 78/128

1916/1916 - 5s - 3ms/step - ia: 0.8686 - loss: 0.0814 - mae: 0.1782 - rmse: 0.2591 - smape: 0.4246 - val_ia: 0.6673 - val_loss: 0.0562 - val_mae: 0.1380 - val_rmse: 0.1893 - val_smape: 0.3656

Epoch 78: early stopping

Restoring model weights from the end of the best epoch: 63.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 44s 333ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 83%|████████▎ | 10/12 [1:08:50<10:25, 312.64s/trial, best loss: 0.03826835975527505]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 13s - 3ms/step - ia: 0.2334 - loss: 1.9477 - mae: 1.0337 - rmse: 1.3055 - smape: 1.6663 - val_ia: 0.1719 - val_loss: 1.0912 - val_mae: 0.8375 - val_rmse: 0.8843 - val_smape: 1.6368

Epoch 2/128

3832/3832 - 9s - 2ms/step - ia: 0.2365 - loss: 1.8198 - mae: 1.0082 - rmse: 1.2666 - smape: 1.6617 - val_ia: 0.1740 - val_loss: 1.0521 - val_mae: 0.8196 - val_rmse: 0.8659 - val_smape: 1.6366

Epoch 3/128

3832/3832 - 9s - 2ms/step - ia: 0.2375 - loss: 1.7562 - mae: 0.9895 - rmse: 1.2416 - smape: 1.6625 - val_ia: 0.1759 - val_loss: 1.0191 - val_mae: 0.8040 - val_rmse: 0.8499 - val_smape: 1.6366

Epoch 4/128

3832/3832 - 10s - 3ms/step - ia: 0.2403 - loss: 1.6526 - mae: 0.9648 - rmse: 1.2084 - smape: 1.6553 - val_ia: 0.1778 - val_loss: 0.9916 - val_mae: 0.7905 - val_rmse: 0.8360 - val_smape: 1.6360

Epoch 5/128

3832/3832 - 10s - 3ms/step - ia: 0.2456 - loss: 1.5902 - mae: 0.9453 - rmse: 1.1833 - smape: 1.6492 - val_ia: 0.1793 - val_loss: 0.9694 - val_mae: 0.7793 - val_rmse: 0.8245 - val_smape: 1.6359

Epoch 6/128

3832/3832 - 19s - 5ms/step - ia: 0.2479 - loss: 1.4886 - mae: 0.9231 - rmse: 1.1507 - smape: 1.6406 - val_ia: 0.1808 - val_loss: 0.9496 - val_mae: 0.7689 - val_rmse: 0.8140 - val_smape: 1.6353

Epoch 7/128

3832/3832 - 11s - 3ms/step - ia: 0.2554 - loss: 1.4360 - mae: 0.9048 - rmse: 1.1298 - smape: 1.6310 - val_ia: 0.1821 - val_loss: 0.9332 - val_mae: 0.7603 - val_rmse: 0.8052 - val_smape: 1.6354

Epoch 8/128

3832/3832 - 10s - 2ms/step - ia: 0.2568 - loss: 1.4066 - mae: 0.8942 - rmse: 1.1158 - smape: 1.6284 - val_ia: 0.1834 - val_loss: 0.9184 - val_mae: 0.7523 - val_rmse: 0.7970 - val_smape: 1.6349

Epoch 9/128

3832/3832 - 10s - 3ms/step - ia: 0.2576 - loss: 1.3592 - mae: 0.8825 - rmse: 1.0978 - smape: 1.6299 - val_ia: 0.1844 - val_loss: 0.9057 - val_mae: 0.7452 - val_rmse: 0.7898 - val_smape: 1.6334

Epoch 10/128

3832/3832 - 9s - 2ms/step - ia: 0.2620 - loss: 1.3427 - mae: 0.8732 - rmse: 1.0893 - smape: 1.6223 - val_ia: 0.1854 - val_loss: 0.8943 - val_mae: 0.7387 - val_rmse: 0.7832 - val_smape: 1.6316

Epoch 11/128

3832/3832 - 9s - 2ms/step - ia: 0.2663 - loss: 1.2814 - mae: 0.8560 - rmse: 1.0653 - smape: 1.6128 - val_ia: 0.1864 - val_loss: 0.8836 - val_mae: 0.7328 - val_rmse: 0.7772 - val_smape: 1.6290

Epoch 12/128

3832/3832 - 9s - 2ms/step - ia: 0.2675 - loss: 1.2613 - mae: 0.8485 - rmse: 1.0563 - smape: 1.6128 - val_ia: 0.1874 - val_loss: 0.8735 - val_mae: 0.7270 - val_rmse: 0.7713 - val_smape: 1.6251

Epoch 13/128

3832/3832 - 10s - 3ms/step - ia: 0.2753 - loss: 1.2176 - mae: 0.8362 - rmse: 1.0397 - smape: 1.5999 - val_ia: 0.1882 - val_loss: 0.8641 - val_mae: 0.7218 - val_rmse: 0.7659 - val_smape: 1.6210

Epoch 14/128

3832/3832 - 9s - 2ms/step - ia: 0.2716 - loss: 1.2148 - mae: 0.8318 - rmse: 1.0357 - smape: 1.6041 - val_ia: 0.1891 - val_loss: 0.8546 - val_mae: 0.7166 - val_rmse: 0.7606 - val_smape: 1.6159

Epoch 15/128

3832/3832 - 10s - 3ms/step - ia: 0.2758 - loss: 1.1976 - mae: 0.8256 - rmse: 1.0286 - smape: 1.5970 - val_ia: 0.1900 - val_loss: 0.8457 - val_mae: 0.7115 - val_rmse: 0.7555 - val_smape: 1.6103

Epoch 16/128

3832/3832 - 9s - 2ms/step - ia: 0.2814 - loss: 1.1609 - mae: 0.8134 - rmse: 1.0132 - smape: 1.5870 - val_ia: 0.1908 - val_loss: 0.8372 - val_mae: 0.7066 - val_rmse: 0.7505 - val_smape: 1.6045

Epoch 17/128

3832/3832 - 9s - 2ms/step - ia: 0.2833 - loss: 1.1286 - mae: 0.8063 - rmse: 1.0007 - smape: 1.5874 - val_ia: 0.1916 - val_loss: 0.8283 - val_mae: 0.7016 - val_rmse: 0.7454 - val_smape: 1.5991

Epoch 18/128

3832/3832 - 9s - 2ms/step - ia: 0.2883 - loss: 1.1190 - mae: 0.8000 - rmse: 0.9956 - smape: 1.5786 - val_ia: 0.1923 - val_loss: 0.8201 - val_mae: 0.6970 - val_rmse: 0.7407 - val_smape: 1.5928

Epoch 19/128

3832/3832 - 9s - 2ms/step - ia: 0.2893 - loss: 1.1087 - mae: 0.7937 - rmse: 0.9896 - smape: 1.5755 - val_ia: 0.1930 - val_loss: 0.8123 - val_mae: 0.6927 - val_rmse: 0.7363 - val_smape: 1.5863

Epoch 20/128

3832/3832 - 11s - 3ms/step - ia: 0.2937 - loss: 1.0718 - mae: 0.7831 - rmse: 0.9737 - smape: 1.5667 - val_ia: 0.1936 - val_loss: 0.8040 - val_mae: 0.6883 - val_rmse: 0.7318 - val_smape: 1.5792

Epoch 21/128

3832/3832 - 11s - 3ms/step - ia: 0.2966 - loss: 1.0639 - mae: 0.7779 - rmse: 0.9692 - smape: 1.5617 - val_ia: 0.1941 - val_loss: 0.7968 - val_mae: 0.6844 - val_rmse: 0.7278 - val_smape: 1.5724

Epoch 22/128

3832/3832 - 18s - 5ms/step - ia: 0.3035 - loss: 1.0390 - mae: 0.7699 - rmse: 0.9588 - smape: 1.5494 - val_ia: 0.1946 - val_loss: 0.7890 - val_mae: 0.6803 - val_rmse: 0.7236 - val_smape: 1.5644

Epoch 23/128

3832/3832 - 10s - 3ms/step - ia: 0.3008 - loss: 1.0378 - mae: 0.7676 - rmse: 0.9567 - smape: 1.5552 - val_ia: 0.1951 - val_loss: 0.7819 - val_mae: 0.6765 - val_rmse: 0.7197 - val_smape: 1.5572

Epoch 24/128

3832/3832 - 10s - 3ms/step - ia: 0.3083 - loss: 1.0118 - mae: 0.7595 - rmse: 0.9480 - smape: 1.5458 - val_ia: 0.1954 - val_loss: 0.7752 - val_mae: 0.6730 - val_rmse: 0.7160 - val_smape: 1.5503

Epoch 25/128

3832/3832 - 9s - 2ms/step - ia: 0.3144 - loss: 0.9996 - mae: 0.7521 - rmse: 0.9384 - smape: 1.5362 - val_ia: 0.1959 - val_loss: 0.7679 - val_mae: 0.6692 - val_rmse: 0.7122 - val_smape: 1.5419

Epoch 26/128

3832/3832 - 11s - 3ms/step - ia: 0.3142 - loss: 0.9938 - mae: 0.7494 - rmse: 0.9352 - smape: 1.5370 - val_ia: 0.1963 - val_loss: 0.7608 - val_mae: 0.6656 - val_rmse: 0.7085 - val_smape: 1.5330

Epoch 27/128

3832/3832 - 9s - 2ms/step - ia: 0.3138 - loss: 0.9890 - mae: 0.7461 - rmse: 0.9314 - smape: 1.5355 - val_ia: 0.1968 - val_loss: 0.7543 - val_mae: 0.6622 - val_rmse: 0.7050 - val_smape: 1.5245

Epoch 28/128

3832/3832 - 9s - 2ms/step - ia: 0.3179 - loss: 0.9702 - mae: 0.7422 - rmse: 0.9245 - smape: 1.5294 - val_ia: 0.1973 - val_loss: 0.7472 - val_mae: 0.6586 - val_rmse: 0.7013 - val_smape: 1.5160

Epoch 29/128

3832/3832 - 7s - 2ms/step - ia: 0.3247 - loss: 0.9548 - mae: 0.7332 - rmse: 0.9159 - smape: 1.5149 - val_ia: 0.1978 - val_loss: 0.7410 - val_mae: 0.6553 - val_rmse: 0.6979 - val_smape: 1.5081

Epoch 30/128

3832/3832 - 9s - 2ms/step - ia: 0.3299 - loss: 0.9463 - mae: 0.7278 - rmse: 0.9113 - smape: 1.5105 - val_ia: 0.1982 - val_loss: 0.7349 - val_mae: 0.6522 - val_rmse: 0.6947 - val_smape: 1.5000

Epoch 31/128

3832/3832 - 9s - 2ms/step - ia: 0.3285 - loss: 0.9385 - mae: 0.7270 - rmse: 0.9088 - smape: 1.5132 - val_ia: 0.1986 - val_loss: 0.7289 - val_mae: 0.6492 - val_rmse: 0.6917 - val_smape: 1.4920

Epoch 32/128

3832/3832 - 9s - 2ms/step - ia: 0.3305 - loss: 0.9343 - mae: 0.7235 - rmse: 0.9063 - smape: 1.5049 - val_ia: 0.1990 - val_loss: 0.7228 - val_mae: 0.6460 - val_rmse: 0.6883 - val_smape: 1.4827

Epoch 33/128

3832/3832 - 9s - 2ms/step - ia: 0.3333 - loss: 0.9251 - mae: 0.7205 - rmse: 0.9024 - smape: 1.5009 - val_ia: 0.1993 - val_loss: 0.7169 - val_mae: 0.6430 - val_rmse: 0.6853 - val_smape: 1.4747

Epoch 34/128

3832/3832 - 9s - 2ms/step - ia: 0.3356 - loss: 0.9109 - mae: 0.7155 - rmse: 0.8950 - smape: 1.4973 - val_ia: 0.1997 - val_loss: 0.7115 - val_mae: 0.6402 - val_rmse: 0.6824 - val_smape: 1.4663

Epoch 35/128

3832/3832 - 9s - 2ms/step - ia: 0.3404 - loss: 0.9093 - mae: 0.7094 - rmse: 0.8890 - smape: 1.4857 - val_ia: 0.2001 - val_loss: 0.7055 - val_mae: 0.6372 - val_rmse: 0.6793 - val_smape: 1.4573

Epoch 36/128

3832/3832 - 10s - 2ms/step - ia: 0.3406 - loss: 0.9050 - mae: 0.7104 - rmse: 0.8909 - smape: 1.4867 - val_ia: 0.2004 - val_loss: 0.7007 - val_mae: 0.6347 - val_rmse: 0.6767 - val_smape: 1.4498

Epoch 37/128

3832/3832 - 9s - 2ms/step - ia: 0.3444 - loss: 0.8849 - mae: 0.7036 - rmse: 0.8805 - smape: 1.4802 - val_ia: 0.2009 - val_loss: 0.6951 - val_mae: 0.6319 - val_rmse: 0.6738 - val_smape: 1.4413

Epoch 38/128

3832/3832 - 9s - 2ms/step - ia: 0.3490 - loss: 0.8923 - mae: 0.7021 - rmse: 0.8822 - smape: 1.4728 - val_ia: 0.2013 - val_loss: 0.6898 - val_mae: 0.6292 - val_rmse: 0.6711 - val_smape: 1.4331

Epoch 39/128

3832/3832 - 17s - 5ms/step - ia: 0.3488 - loss: 0.8781 - mae: 0.6987 - rmse: 0.8768 - smape: 1.4755 - val_ia: 0.2017 - val_loss: 0.6850 - val_mae: 0.6267 - val_rmse: 0.6685 - val_smape: 1.4256

Epoch 40/128

3832/3832 - 13s - 3ms/step - ia: 0.3568 - loss: 0.8512 - mae: 0.6904 - rmse: 0.8643 - smape: 1.4592 - val_ia: 0.2021 - val_loss: 0.6794 - val_mae: 0.6241 - val_rmse: 0.6658 - val_smape: 1.4181

Epoch 41/128

3832/3832 - 10s - 3ms/step - ia: 0.3551 - loss: 0.8617 - mae: 0.6909 - rmse: 0.8698 - smape: 1.4555 - val_ia: 0.2025 - val_loss: 0.6753 - val_mae: 0.6218 - val_rmse: 0.6635 - val_smape: 1.4108

Epoch 42/128

3832/3832 - 9s - 2ms/step - ia: 0.3574 - loss: 0.8478 - mae: 0.6864 - rmse: 0.8609 - smape: 1.4553 - val_ia: 0.2028 - val_loss: 0.6706 - val_mae: 0.6195 - val_rmse: 0.6612 - val_smape: 1.4038

Epoch 43/128

3832/3832 - 9s - 2ms/step - ia: 0.3653 - loss: 0.8377 - mae: 0.6806 - rmse: 0.8559 - smape: 1.4427 - val_ia: 0.2032 - val_loss: 0.6661 - val_mae: 0.6172 - val_rmse: 0.6588 - val_smape: 1.3970

Epoch 44/128

3832/3832 - 7s - 2ms/step - ia: 0.3670 - loss: 0.8289 - mae: 0.6779 - rmse: 0.8506 - smape: 1.4373 - val_ia: 0.2036 - val_loss: 0.6611 - val_mae: 0.6149 - val_rmse: 0.6565 - val_smape: 1.3899

Epoch 45/128

3832/3832 - 10s - 3ms/step - ia: 0.3663 - loss: 0.8250 - mae: 0.6776 - rmse: 0.8493 - smape: 1.4371 - val_ia: 0.2040 - val_loss: 0.6574 - val_mae: 0.6129 - val_rmse: 0.6544 - val_smape: 1.3837

Epoch 46/128

3832/3832 - 9s - 2ms/step - ia: 0.3759 - loss: 0.8238 - mae: 0.6708 - rmse: 0.8444 - smape: 1.4244 - val_ia: 0.2043 - val_loss: 0.6533 - val_mae: 0.6108 - val_rmse: 0.6522 - val_smape: 1.3774

Epoch 47/128

3832/3832 - 9s - 2ms/step - ia: 0.3689 - loss: 0.8286 - mae: 0.6762 - rmse: 0.8498 - smape: 1.4334 - val_ia: 0.2046 - val_loss: 0.6490 - val_mae: 0.6087 - val_rmse: 0.6501 - val_smape: 1.3711

Epoch 48/128

3832/3832 - 9s - 2ms/step - ia: 0.3768 - loss: 0.8043 - mae: 0.6673 - rmse: 0.8388 - smape: 1.4216 - val_ia: 0.2050 - val_loss: 0.6449 - val_mae: 0.6067 - val_rmse: 0.6480 - val_smape: 1.3650

Epoch 49/128

3832/3832 - 9s - 2ms/step - ia: 0.3779 - loss: 0.8125 - mae: 0.6656 - rmse: 0.8395 - smape: 1.4159 - val_ia: 0.2053 - val_loss: 0.6411 - val_mae: 0.6048 - val_rmse: 0.6461 - val_smape: 1.3591

Epoch 50/128

3832/3832 - 9s - 2ms/step - ia: 0.3777 - loss: 0.8055 - mae: 0.6641 - rmse: 0.8378 - smape: 1.4106 - val_ia: 0.2056 - val_loss: 0.6369 - val_mae: 0.6027 - val_rmse: 0.6440 - val_smape: 1.3527

Epoch 51/128

3832/3832 - 8s - 2ms/step - ia: 0.3816 - loss: 0.7969 - mae: 0.6620 - rmse: 0.8337 - smape: 1.4077 - val_ia: 0.2060 - val_loss: 0.6335 - val_mae: 0.6010 - val_rmse: 0.6422 - val_smape: 1.3471

Epoch 52/128

3832/3832 - 9s - 2ms/step - ia: 0.3825 - loss: 0.7880 - mae: 0.6595 - rmse: 0.8299 - smape: 1.4043 - val_ia: 0.2064 - val_loss: 0.6297 - val_mae: 0.5991 - val_rmse: 0.6403 - val_smape: 1.3412

Epoch 53/128

3832/3832 - 9s - 2ms/step - ia: 0.3839 - loss: 0.7826 - mae: 0.6560 - rmse: 0.8268 - smape: 1.3994 - val_ia: 0.2068 - val_loss: 0.6266 - val_mae: 0.5974 - val_rmse: 0.6386 - val_smape: 1.3357

Epoch 54/128

3832/3832 - 10s - 3ms/step - ia: 0.3901 - loss: 0.7820 - mae: 0.6536 - rmse: 0.8224 - smape: 1.3914 - val_ia: 0.2072 - val_loss: 0.6235 - val_mae: 0.5957 - val_rmse: 0.6369 - val_smape: 1.3300

Epoch 55/128

3832/3832 - 8s - 2ms/step - ia: 0.3882 - loss: 0.7744 - mae: 0.6514 - rmse: 0.8227 - smape: 1.3863 - val_ia: 0.2076 - val_loss: 0.6201 - val_mae: 0.5940 - val_rmse: 0.6352 - val_smape: 1.3247

Epoch 56/128

3832/3832 - 8s - 2ms/step - ia: 0.3934 - loss: 0.7683 - mae: 0.6487 - rmse: 0.8178 - smape: 1.3858 - val_ia: 0.2079 - val_loss: 0.6170 - val_mae: 0.5925 - val_rmse: 0.6336 - val_smape: 1.3192

Epoch 57/128

3832/3832 - 12s - 3ms/step - ia: 0.3952 - loss: 0.7604 - mae: 0.6456 - rmse: 0.8135 - smape: 1.3797 - val_ia: 0.2084 - val_loss: 0.6136 - val_mae: 0.5907 - val_rmse: 0.6318 - val_smape: 1.3134

Epoch 58/128

3832/3832 - 10s - 3ms/step - ia: 0.3958 - loss: 0.7655 - mae: 0.6447 - rmse: 0.8144 - smape: 1.3811 - val_ia: 0.2088 - val_loss: 0.6102 - val_mae: 0.5890 - val_rmse: 0.6300 - val_smape: 1.3082

Epoch 59/128

3832/3832 - 9s - 2ms/step - ia: 0.3979 - loss: 0.7608 - mae: 0.6432 - rmse: 0.8123 - smape: 1.3743 - val_ia: 0.2092 - val_loss: 0.6075 - val_mae: 0.5874 - val_rmse: 0.6284 - val_smape: 1.3029

Epoch 60/128

3832/3832 - 10s - 3ms/step - ia: 0.4021 - loss: 0.7533 - mae: 0.6392 - rmse: 0.8075 - smape: 1.3669 - val_ia: 0.2095 - val_loss: 0.6047 - val_mae: 0.5860 - val_rmse: 0.6270 - val_smape: 1.2983

Epoch 61/128

3832/3832 - 9s - 2ms/step - ia: 0.4001 - loss: 0.7553 - mae: 0.6415 - rmse: 0.8098 - smape: 1.3704 - val_ia: 0.2099 - val_loss: 0.6021 - val_mae: 0.5844 - val_rmse: 0.6254 - val_smape: 1.2933

Epoch 62/128

3832/3832 - 9s - 2ms/step - ia: 0.4078 - loss: 0.7448 - mae: 0.6350 - rmse: 0.8025 - smape: 1.3591 - val_ia: 0.2102 - val_loss: 0.5996 - val_mae: 0.5831 - val_rmse: 0.6240 - val_smape: 1.2888

Epoch 63/128

3832/3832 - 9s - 2ms/step - ia: 0.4062 - loss: 0.7357 - mae: 0.6349 - rmse: 0.8005 - smape: 1.3534 - val_ia: 0.2106 - val_loss: 0.5963 - val_mae: 0.5814 - val_rmse: 0.6223 - val_smape: 1.2835

Epoch 64/128

3832/3832 - 10s - 3ms/step - ia: 0.4060 - loss: 0.7425 - mae: 0.6341 - rmse: 0.8018 - smape: 1.3535 - val_ia: 0.2109 - val_loss: 0.5934 - val_mae: 0.5799 - val_rmse: 0.6208 - val_smape: 1.2786

Epoch 65/128

3832/3832 - 8s - 2ms/step - ia: 0.4115 - loss: 0.7297 - mae: 0.6293 - rmse: 0.7944 - smape: 1.3446 - val_ia: 0.2112 - val_loss: 0.5903 - val_mae: 0.5783 - val_rmse: 0.6192 - val_smape: 1.2737

Epoch 66/128

3832/3832 - 9s - 2ms/step - ia: 0.4098 - loss: 0.7260 - mae: 0.6280 - rmse: 0.7932 - smape: 1.3468 - val_ia: 0.2116 - val_loss: 0.5871 - val_mae: 0.5767 - val_rmse: 0.6176 - val_smape: 1.2687

Epoch 67/128

3832/3832 - 8s - 2ms/step - ia: 0.4141 - loss: 0.7150 - mae: 0.6242 - rmse: 0.7880 - smape: 1.3363 - val_ia: 0.2119 - val_loss: 0.5843 - val_mae: 0.5753 - val_rmse: 0.6161 - val_smape: 1.2644

Epoch 68/128

3832/3832 - 10s - 3ms/step - ia: 0.4165 - loss: 0.7259 - mae: 0.6241 - rmse: 0.7908 - smape: 1.3325 - val_ia: 0.2121 - val_loss: 0.5814 - val_mae: 0.5738 - val_rmse: 0.6145 - val_smape: 1.2600

Epoch 69/128

3832/3832 - 9s - 2ms/step - ia: 0.4175 - loss: 0.7200 - mae: 0.6233 - rmse: 0.7903 - smape: 1.3258 - val_ia: 0.2124 - val_loss: 0.5791 - val_mae: 0.5725 - val_rmse: 0.6132 - val_smape: 1.2560

Epoch 70/128

3832/3832 - 11s - 3ms/step - ia: 0.4170 - loss: 0.7171 - mae: 0.6237 - rmse: 0.7876 - smape: 1.3286 - val_ia: 0.2127 - val_loss: 0.5769 - val_mae: 0.5712 - val_rmse: 0.6119 - val_smape: 1.2522

Epoch 71/128

3832/3832 - 10s - 3ms/step - ia: 0.4201 - loss: 0.7139 - mae: 0.6220 - rmse: 0.7859 - smape: 1.3246 - val_ia: 0.2129 - val_loss: 0.5751 - val_mae: 0.5702 - val_rmse: 0.6109 - val_smape: 1.2490

Epoch 72/128

3832/3832 - 10s - 2ms/step - ia: 0.4229 - loss: 0.7004 - mae: 0.6171 - rmse: 0.7792 - smape: 1.3213 - val_ia: 0.2132 - val_loss: 0.5725 - val_mae: 0.5688 - val_rmse: 0.6095 - val_smape: 1.2447

Epoch 73/128

3832/3832 - 9s - 2ms/step - ia: 0.4238 - loss: 0.7057 - mae: 0.6170 - rmse: 0.7814 - smape: 1.3125 - val_ia: 0.2135 - val_loss: 0.5704 - val_mae: 0.5677 - val_rmse: 0.6083 - val_smape: 1.2413

Epoch 74/128

3832/3832 - 9s - 2ms/step - ia: 0.4283 - loss: 0.7085 - mae: 0.6146 - rmse: 0.7801 - smape: 1.3061 - val_ia: 0.2137 - val_loss: 0.5677 - val_mae: 0.5663 - val_rmse: 0.6068 - val_smape: 1.2373

Epoch 75/128

3832/3832 - 9s - 2ms/step - ia: 0.4266 - loss: 0.6994 - mae: 0.6145 - rmse: 0.7784 - smape: 1.3079 - val_ia: 0.2140 - val_loss: 0.5651 - val_mae: 0.5649 - val_rmse: 0.6054 - val_smape: 1.2335

Epoch 76/128

3832/3832 - 8s - 2ms/step - ia: 0.4281 - loss: 0.7034 - mae: 0.6142 - rmse: 0.7796 - smape: 1.3047 - val_ia: 0.2142 - val_loss: 0.5628 - val_mae: 0.5636 - val_rmse: 0.6041 - val_smape: 1.2295

Epoch 77/128

3832/3832 - 9s - 2ms/step - ia: 0.4281 - loss: 0.6930 - mae: 0.6123 - rmse: 0.7747 - smape: 1.3061 - val_ia: 0.2145 - val_loss: 0.5606 - val_mae: 0.5624 - val_rmse: 0.6028 - val_smape: 1.2257

Epoch 78/128

3832/3832 - 10s - 3ms/step - ia: 0.4311 - loss: 0.6964 - mae: 0.6112 - rmse: 0.7755 - smape: 1.3029 - val_ia: 0.2147 - val_loss: 0.5587 - val_mae: 0.5613 - val_rmse: 0.6017 - val_smape: 1.2225

Epoch 79/128

3832/3832 - 8s - 2ms/step - ia: 0.4310 - loss: 0.6948 - mae: 0.6105 - rmse: 0.7738 - smape: 1.2964 - val_ia: 0.2149 - val_loss: 0.5566 - val_mae: 0.5602 - val_rmse: 0.6005 - val_smape: 1.2193

Epoch 80/128

3832/3832 - 9s - 2ms/step - ia: 0.4324 - loss: 0.6865 - mae: 0.6080 - rmse: 0.7712 - smape: 1.2942 - val_ia: 0.2152 - val_loss: 0.5544 - val_mae: 0.5590 - val_rmse: 0.5993 - val_smape: 1.2156

Epoch 81/128

3832/3832 - 9s - 2ms/step - ia: 0.4360 - loss: 0.6856 - mae: 0.6051 - rmse: 0.7682 - smape: 1.2844 - val_ia: 0.2154 - val_loss: 0.5517 - val_mae: 0.5576 - val_rmse: 0.5979 - val_smape: 1.2117

Epoch 82/128

3832/3832 - 11s - 3ms/step - ia: 0.4374 - loss: 0.6790 - mae: 0.6038 - rmse: 0.7659 - smape: 1.2881 - val_ia: 0.2157 - val_loss: 0.5495 - val_mae: 0.5565 - val_rmse: 0.5967 - val_smape: 1.2081

Epoch 83/128

3832/3832 - 8s - 2ms/step - ia: 0.4365 - loss: 0.6831 - mae: 0.6052 - rmse: 0.7675 - smape: 1.2810 - val_ia: 0.2159 - val_loss: 0.5473 - val_mae: 0.5553 - val_rmse: 0.5955 - val_smape: 1.2047

Epoch 84/128

3832/3832 - 8s - 2ms/step - ia: 0.4358 - loss: 0.6843 - mae: 0.6046 - rmse: 0.7677 - smape: 1.2816 - val_ia: 0.2162 - val_loss: 0.5450 - val_mae: 0.5542 - val_rmse: 0.5943 - val_smape: 1.2012

Epoch 85/128

3832/3832 - 10s - 3ms/step - ia: 0.4431 - loss: 0.6674 - mae: 0.5988 - rmse: 0.7594 - smape: 1.2697 - val_ia: 0.2164 - val_loss: 0.5434 - val_mae: 0.5533 - val_rmse: 0.5934 - val_smape: 1.1985

Epoch 86/128

3832/3832 - 9s - 2ms/step - ia: 0.4471 - loss: 0.6509 - mae: 0.5927 - rmse: 0.7510 - smape: 1.2643 - val_ia: 0.2166 - val_loss: 0.5413 - val_mae: 0.5521 - val_rmse: 0.5922 - val_smape: 1.1949

Epoch 87/128

3832/3832 - 8s - 2ms/step - ia: 0.4455 - loss: 0.6678 - mae: 0.5953 - rmse: 0.7581 - smape: 1.2635 - val_ia: 0.2170 - val_loss: 0.5381 - val_mae: 0.5505 - val_rmse: 0.5906 - val_smape: 1.1904

Epoch 88/128

3832/3832 - 8s - 2ms/step - ia: 0.4459 - loss: 0.6627 - mae: 0.5954 - rmse: 0.7544 - smape: 1.2642 - val_ia: 0.2173 - val_loss: 0.5360 - val_mae: 0.5494 - val_rmse: 0.5894 - val_smape: 1.1873

Epoch 89/128

3832/3832 - 11s - 3ms/step - ia: 0.4493 - loss: 0.6689 - mae: 0.5946 - rmse: 0.7575 - smape: 1.2576 - val_ia: 0.2176 - val_loss: 0.5341 - val_mae: 0.5484 - val_rmse: 0.5884 - val_smape: 1.1844

Epoch 90/128

3832/3832 - 8s - 2ms/step - ia: 0.4489 - loss: 0.6704 - mae: 0.5929 - rmse: 0.7570 - smape: 1.2504 - val_ia: 0.2179 - val_loss: 0.5316 - val_mae: 0.5471 - val_rmse: 0.5871 - val_smape: 1.1810

Epoch 91/128

3832/3832 - 8s - 2ms/step - ia: 0.4488 - loss: 0.6636 - mae: 0.5926 - rmse: 0.7545 - smape: 1.2558 - val_ia: 0.2181 - val_loss: 0.5301 - val_mae: 0.5462 - val_rmse: 0.5861 - val_smape: 1.1778

Epoch 92/128

3832/3832 - 11s - 3ms/step - ia: 0.4506 - loss: 0.6615 - mae: 0.5909 - rmse: 0.7540 - smape: 1.2483 - val_ia: 0.2184 - val_loss: 0.5281 - val_mae: 0.5451 - val_rmse: 0.5850 - val_smape: 1.1748

Epoch 93/128

3832/3832 - 9s - 2ms/step - ia: 0.4514 - loss: 0.6582 - mae: 0.5905 - rmse: 0.7514 - smape: 1.2480 - val_ia: 0.2187 - val_loss: 0.5266 - val_mae: 0.5441 - val_rmse: 0.5840 - val_smape: 1.1718

Epoch 94/128

3832/3832 - 8s - 2ms/step - ia: 0.4538 - loss: 0.6553 - mae: 0.5888 - rmse: 0.7501 - smape: 1.2440 - val_ia: 0.2190 - val_loss: 0.5252 - val_mae: 0.5432 - val_rmse: 0.5830 - val_smape: 1.1686

Epoch 95/128

3832/3832 - 8s - 2ms/step - ia: 0.4522 - loss: 0.6586 - mae: 0.5907 - rmse: 0.7526 - smape: 1.2463 - val_ia: 0.2193 - val_loss: 0.5240 - val_mae: 0.5423 - val_rmse: 0.5822 - val_smape: 1.1658

Epoch 96/128

3832/3832 - 11s - 3ms/step - ia: 0.4523 - loss: 0.6522 - mae: 0.5864 - rmse: 0.7495 - smape: 1.2396 - val_ia: 0.2195 - val_loss: 0.5222 - val_mae: 0.5413 - val_rmse: 0.5812 - val_smape: 1.1629

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 5s - 21ms/step - ia: 0.6157 - loss: 0.4985 - mae: 0.5160 - rmse: 0.6931 - smape: 0.9676 - val_ia: 0.7230 - val_loss: 0.1942 - val_mae: 0.2862 - val_rmse: 0.3991 - val_smape: 0.6385

Epoch 2/128

240/240 - 1s - 3ms/step - ia: 0.7206 - loss: 0.3044 - mae: 0.4048 - rmse: 0.5471 - smape: 0.7972 - val_ia: 0.7739 - val_loss: 0.1360 - val_mae: 0.2335 - val_rmse: 0.3341 - val_smape: 0.5457

Epoch 3/128

240/240 - 1s - 3ms/step - ia: 0.7523 - loss: 0.2462 - mae: 0.3615 - rmse: 0.4920 - smape: 0.7337 - val_ia: 0.8005 - val_loss: 0.1136 - val_mae: 0.2076 - val_rmse: 0.3056 - val_smape: 0.4943

Epoch 4/128

240/240 - 1s - 6ms/step - ia: 0.7718 - loss: 0.2126 - mae: 0.3347 - rmse: 0.4570 - smape: 0.6947 - val_ia: 0.8148 - val_loss: 0.1012 - val_mae: 0.1932 - val_rmse: 0.2872 - val_smape: 0.4647

Epoch 5/128

240/240 - 1s - 4ms/step - ia: 0.7847 - loss: 0.1912 - mae: 0.3154 - rmse: 0.4334 - smape: 0.6694 - val_ia: 0.8235 - val_loss: 0.0941 - val_mae: 0.1836 - val_rmse: 0.2777 - val_smape: 0.4494

Epoch 6/128

240/240 - 1s - 5ms/step - ia: 0.7969 - loss: 0.1755 - mae: 0.2976 - rmse: 0.4147 - smape: 0.6385 - val_ia: 0.8297 - val_loss: 0.0897 - val_mae: 0.1772 - val_rmse: 0.2698 - val_smape: 0.4356

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.8050 - loss: 0.1627 - mae: 0.2848 - rmse: 0.3989 - smape: 0.6178 - val_ia: 0.8336 - val_loss: 0.0864 - val_mae: 0.1728 - val_rmse: 0.2642 - val_smape: 0.4257

Epoch 8/128

240/240 - 1s - 3ms/step - ia: 0.8134 - loss: 0.1530 - mae: 0.2734 - rmse: 0.3866 - smape: 0.5962 - val_ia: 0.8391 - val_loss: 0.0836 - val_mae: 0.1683 - val_rmse: 0.2595 - val_smape: 0.4150

Epoch 9/128

240/240 - 1s - 6ms/step - ia: 0.8195 - loss: 0.1447 - mae: 0.2645 - rmse: 0.3754 - smape: 0.5816 - val_ia: 0.8404 - val_loss: 0.0818 - val_mae: 0.1668 - val_rmse: 0.2574 - val_smape: 0.4159

Epoch 10/128

240/240 - 1s - 3ms/step - ia: 0.8242 - loss: 0.1384 - mae: 0.2575 - rmse: 0.3671 - smape: 0.5698 - val_ia: 0.8459 - val_loss: 0.0803 - val_mae: 0.1624 - val_rmse: 0.2524 - val_smape: 0.4003

Epoch 11/128

240/240 - 1s - 3ms/step - ia: 0.8298 - loss: 0.1320 - mae: 0.2496 - rmse: 0.3586 - smape: 0.5549 - val_ia: 0.8479 - val_loss: 0.0779 - val_mae: 0.1594 - val_rmse: 0.2491 - val_smape: 0.3956

Epoch 12/128

240/240 - 1s - 4ms/step - ia: 0.8330 - loss: 0.1292 - mae: 0.2447 - rmse: 0.3544 - smape: 0.5462 - val_ia: 0.8531 - val_loss: 0.0761 - val_mae: 0.1555 - val_rmse: 0.2457 - val_smape: 0.3885

Epoch 13/128

240/240 - 1s - 3ms/step - ia: 0.8361 - loss: 0.1274 - mae: 0.2404 - rmse: 0.3520 - smape: 0.5366 - val_ia: 0.8535 - val_loss: 0.0751 - val_mae: 0.1548 - val_rmse: 0.2437 - val_smape: 0.3872

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.8400 - loss: 0.1214 - mae: 0.2351 - rmse: 0.3429 - smape: 0.5299 - val_ia: 0.8569 - val_loss: 0.0732 - val_mae: 0.1518 - val_rmse: 0.2412 - val_smape: 0.3812

Epoch 15/128

240/240 - 1s - 3ms/step - ia: 0.8422 - loss: 0.1188 - mae: 0.2315 - rmse: 0.3390 - smape: 0.5230 - val_ia: 0.8576 - val_loss: 0.0723 - val_mae: 0.1506 - val_rmse: 0.2395 - val_smape: 0.3804

Epoch 16/128

240/240 - 2s - 7ms/step - ia: 0.8448 - loss: 0.1162 - mae: 0.2282 - rmse: 0.3360 - smape: 0.5191 - val_ia: 0.8561 - val_loss: 0.0720 - val_mae: 0.1504 - val_rmse: 0.2397 - val_smape: 0.3797

Epoch 17/128

240/240 - 1s - 4ms/step - ia: 0.8464 - loss: 0.1141 - mae: 0.2256 - rmse: 0.3324 - smape: 0.5128 - val_ia: 0.8603 - val_loss: 0.0700 - val_mae: 0.1473 - val_rmse: 0.2363 - val_smape: 0.3743

Epoch 18/128

240/240 - 1s - 2ms/step - ia: 0.8496 - loss: 0.1111 - mae: 0.2213 - rmse: 0.3275 - smape: 0.5023 - val_ia: 0.8606 - val_loss: 0.0692 - val_mae: 0.1465 - val_rmse: 0.2346 - val_smape: 0.3727

Epoch 19/128

240/240 - 1s - 3ms/step - ia: 0.8504 - loss: 0.1102 - mae: 0.2200 - rmse: 0.3264 - smape: 0.5047 - val_ia: 0.8633 - val_loss: 0.0680 - val_mae: 0.1440 - val_rmse: 0.2326 - val_smape: 0.3670

Epoch 20/128

240/240 - 1s - 5ms/step - ia: 0.8523 - loss: 0.1095 - mae: 0.2173 - rmse: 0.3245 - smape: 0.4971 - val_ia: 0.8622 - val_loss: 0.0678 - val_mae: 0.1445 - val_rmse: 0.2321 - val_smape: 0.3687

Epoch 21/128

240/240 - 1s - 5ms/step - ia: 0.8538 - loss: 0.1067 - mae: 0.2151 - rmse: 0.3200 - smape: 0.4939 - val_ia: 0.8652 - val_loss: 0.0667 - val_mae: 0.1418 - val_rmse: 0.2302 - val_smape: 0.3634

Epoch 22/128

240/240 - 1s - 4ms/step - ia: 0.8548 - loss: 0.1059 - mae: 0.2137 - rmse: 0.3194 - smape: 0.4905 - val_ia: 0.8658 - val_loss: 0.0661 - val_mae: 0.1419 - val_rmse: 0.2287 - val_smape: 0.3632

Epoch 23/128

240/240 - 1s - 2ms/step - ia: 0.8561 - loss: 0.1035 - mae: 0.2118 - rmse: 0.3144 - smape: 0.4878 - val_ia: 0.8659 - val_loss: 0.0656 - val_mae: 0.1404 - val_rmse: 0.2280 - val_smape: 0.3607

Epoch 24/128

240/240 - 1s - 3ms/step - ia: 0.8582 - loss: 0.1018 - mae: 0.2086 - rmse: 0.3127 - smape: 0.4851 - val_ia: 0.8653 - val_loss: 0.0659 - val_mae: 0.1410 - val_rmse: 0.2267 - val_smape: 0.3601

Epoch 25/128

240/240 - 1s - 2ms/step - ia: 0.8596 - loss: 0.0994 - mae: 0.2061 - rmse: 0.3083 - smape: 0.4822 - val_ia: 0.8610 - val_loss: 0.0653 - val_mae: 0.1437 - val_rmse: 0.2293 - val_smape: 0.3675

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.8613 - loss: 0.0984 - mae: 0.2038 - rmse: 0.3078 - smape: 0.4737 - val_ia: 0.8679 - val_loss: 0.0640 - val_mae: 0.1388 - val_rmse: 0.2263 - val_smape: 0.3587

Epoch 27/128

240/240 - 1s - 3ms/step - ia: 0.8613 - loss: 0.0986 - mae: 0.2044 - rmse: 0.3079 - smape: 0.4745 - val_ia: 0.8682 - val_loss: 0.0633 - val_mae: 0.1374 - val_rmse: 0.2243 - val_smape: 0.3554

Epoch 28/128

240/240 - 1s - 4ms/step - ia: 0.8627 - loss: 0.0977 - mae: 0.2017 - rmse: 0.3057 - smape: 0.4719 - val_ia: 0.8682 - val_loss: 0.0626 - val_mae: 0.1373 - val_rmse: 0.2229 - val_smape: 0.3568

Epoch 29/128

240/240 - 1s - 5ms/step - ia: 0.8652 - loss: 0.0946 - mae: 0.1984 - rmse: 0.3008 - smape: 0.4655 - val_ia: 0.8707 - val_loss: 0.0621 - val_mae: 0.1357 - val_rmse: 0.2216 - val_smape: 0.3533

Epoch 30/128

240/240 - 2s - 7ms/step - ia: 0.8647 - loss: 0.0949 - mae: 0.1990 - rmse: 0.3015 - smape: 0.4655 - val_ia: 0.8674 - val_loss: 0.0619 - val_mae: 0.1365 - val_rmse: 0.2217 - val_smape: 0.3529

Epoch 31/128

240/240 - 2s - 10ms/step - ia: 0.8658 - loss: 0.0945 - mae: 0.1973 - rmse: 0.3006 - smape: 0.4620 - val_ia: 0.8652 - val_loss: 0.0628 - val_mae: 0.1385 - val_rmse: 0.2227 - val_smape: 0.3560

Epoch 32/128

240/240 - 1s - 6ms/step - ia: 0.8667 - loss: 0.0941 - mae: 0.1960 - rmse: 0.2997 - smape: 0.4611 - val_ia: 0.8700 - val_loss: 0.0613 - val_mae: 0.1349 - val_rmse: 0.2208 - val_smape: 0.3506

Epoch 33/128

240/240 - 1s - 3ms/step - ia: 0.8684 - loss: 0.0911 - mae: 0.1934 - rmse: 0.2949 - smape: 0.4590 - val_ia: 0.8699 - val_loss: 0.0608 - val_mae: 0.1347 - val_rmse: 0.2206 - val_smape: 0.3514

Epoch 34/128

240/240 - 1s - 5ms/step - ia: 0.8683 - loss: 0.0911 - mae: 0.1934 - rmse: 0.2954 - smape: 0.4593 - val_ia: 0.8698 - val_loss: 0.0607 - val_mae: 0.1343 - val_rmse: 0.2201 - val_smape: 0.3508

Epoch 35/128

240/240 - 1s - 4ms/step - ia: 0.8698 - loss: 0.0909 - mae: 0.1909 - rmse: 0.2947 - smape: 0.4545 - val_ia: 0.8702 - val_loss: 0.0604 - val_mae: 0.1341 - val_rmse: 0.2194 - val_smape: 0.3498

Epoch 36/128

240/240 - 1s - 3ms/step - ia: 0.8700 - loss: 0.0896 - mae: 0.1910 - rmse: 0.2922 - smape: 0.4524 - val_ia: 0.8716 - val_loss: 0.0597 - val_mae: 0.1331 - val_rmse: 0.2182 - val_smape: 0.3490

Epoch 37/128

240/240 - 1s - 4ms/step - ia: 0.8704 - loss: 0.0890 - mae: 0.1900 - rmse: 0.2920 - smape: 0.4523 - val_ia: 0.8704 - val_loss: 0.0596 - val_mae: 0.1337 - val_rmse: 0.2179 - val_smape: 0.3509

Epoch 38/128

240/240 - 1s - 3ms/step - ia: 0.8719 - loss: 0.0872 - mae: 0.1878 - rmse: 0.2886 - smape: 0.4500 - val_ia: 0.8691 - val_loss: 0.0596 - val_mae: 0.1339 - val_rmse: 0.2185 - val_smape: 0.3496

Epoch 39/128

240/240 - 2s - 7ms/step - ia: 0.8720 - loss: 0.0878 - mae: 0.1876 - rmse: 0.2897 - smape: 0.4476 - val_ia: 0.8696 - val_loss: 0.0591 - val_mae: 0.1336 - val_rmse: 0.2179 - val_smape: 0.3498

Epoch 40/128

240/240 - 2s - 8ms/step - ia: 0.8729 - loss: 0.0861 - mae: 0.1869 - rmse: 0.2860 - smape: 0.4461 - val_ia: 0.8692 - val_loss: 0.0590 - val_mae: 0.1335 - val_rmse: 0.2173 - val_smape: 0.3504

Epoch 41/128

240/240 - 2s - 9ms/step - ia: 0.8735 - loss: 0.0860 - mae: 0.1853 - rmse: 0.2861 - smape: 0.4451 - val_ia: 0.8701 - val_loss: 0.0590 - val_mae: 0.1333 - val_rmse: 0.2177 - val_smape: 0.3499

Epoch 42/128

240/240 - 1s - 6ms/step - ia: 0.8738 - loss: 0.0874 - mae: 0.1851 - rmse: 0.2873 - smape: 0.4409 - val_ia: 0.8716 - val_loss: 0.0585 - val_mae: 0.1321 - val_rmse: 0.2165 - val_smape: 0.3481

Epoch 43/128

240/240 - 1s - 6ms/step - ia: 0.8745 - loss: 0.0850 - mae: 0.1836 - rmse: 0.2849 - smape: 0.4399 - val_ia: 0.8708 - val_loss: 0.0586 - val_mae: 0.1323 - val_rmse: 0.2170 - val_smape: 0.3473

Epoch 44/128

240/240 - 1s - 4ms/step - ia: 0.8748 - loss: 0.0853 - mae: 0.1837 - rmse: 0.2849 - smape: 0.4397 - val_ia: 0.8657 - val_loss: 0.0588 - val_mae: 0.1353 - val_rmse: 0.2183 - val_smape: 0.3536

Epoch 45/128

240/240 - 1s - 3ms/step - ia: 0.8753 - loss: 0.0843 - mae: 0.1828 - rmse: 0.2834 - smape: 0.4392 - val_ia: 0.8659 - val_loss: 0.0585 - val_mae: 0.1348 - val_rmse: 0.2178 - val_smape: 0.3521

Epoch 46/128

240/240 - 1s - 4ms/step - ia: 0.8756 - loss: 0.0835 - mae: 0.1822 - rmse: 0.2821 - smape: 0.4393 - val_ia: 0.8691 - val_loss: 0.0583 - val_mae: 0.1332 - val_rmse: 0.2171 - val_smape: 0.3492

Epoch 47/128

240/240 - 1s - 3ms/step - ia: 0.8762 - loss: 0.0833 - mae: 0.1813 - rmse: 0.2814 - smape: 0.4384 - val_ia: 0.8675 - val_loss: 0.0586 - val_mae: 0.1344 - val_rmse: 0.2178 - val_smape: 0.3524

Epoch 48/128

240/240 - 1s - 3ms/step - ia: 0.8759 - loss: 0.0835 - mae: 0.1817 - rmse: 0.2817 - smape: 0.4400 - val_ia: 0.8676 - val_loss: 0.0582 - val_mae: 0.1339 - val_rmse: 0.2171 - val_smape: 0.3517

Epoch 49/128

240/240 - 1s - 6ms/step - ia: 0.8779 - loss: 0.0819 - mae: 0.1790 - rmse: 0.2789 - smape: 0.4317 - val_ia: 0.8685 - val_loss: 0.0583 - val_mae: 0.1339 - val_rmse: 0.2171 - val_smape: 0.3522

Epoch 50/128

240/240 - 1s - 5ms/step - ia: 0.8759 - loss: 0.0835 - mae: 0.1811 - rmse: 0.2816 - smape: 0.4383 - val_ia: 0.8613 - val_loss: 0.0586 - val_mae: 0.1378 - val_rmse: 0.2190 - val_smape: 0.3582

Epoch 51/128

240/240 - 1s - 3ms/step - ia: 0.8777 - loss: 0.0820 - mae: 0.1787 - rmse: 0.2791 - smape: 0.4319 - val_ia: 0.8691 - val_loss: 0.0575 - val_mae: 0.1327 - val_rmse: 0.2155 - val_smape: 0.3505

Epoch 52/128

240/240 - 1s - 3ms/step - ia: 0.8782 - loss: 0.0814 - mae: 0.1784 - rmse: 0.2790 - smape: 0.4308 - val_ia: 0.8702 - val_loss: 0.0573 - val_mae: 0.1319 - val_rmse: 0.2151 - val_smape: 0.3492

Epoch 53/128

240/240 - 1s - 2ms/step - ia: 0.8780 - loss: 0.0815 - mae: 0.1782 - rmse: 0.2781 - smape: 0.4325 - val_ia: 0.8716 - val_loss: 0.0573 - val_mae: 0.1313 - val_rmse: 0.2148 - val_smape: 0.3498

Epoch 54/128

240/240 - 1s - 3ms/step - ia: 0.8784 - loss: 0.0812 - mae: 0.1778 - rmse: 0.2773 - smape: 0.4322 - val_ia: 0.8662 - val_loss: 0.0578 - val_mae: 0.1344 - val_rmse: 0.2172 - val_smape: 0.3512

Epoch 55/128

240/240 - 1s - 5ms/step - ia: 0.8796 - loss: 0.0805 - mae: 0.1764 - rmse: 0.2771 - smape: 0.4286 - val_ia: 0.8691 - val_loss: 0.0577 - val_mae: 0.1329 - val_rmse: 0.2158 - val_smape: 0.3512

Epoch 56/128

240/240 - 1s - 3ms/step - ia: 0.8793 - loss: 0.0800 - mae: 0.1766 - rmse: 0.2753 - smape: 0.4302 - val_ia: 0.8673 - val_loss: 0.0576 - val_mae: 0.1340 - val_rmse: 0.2159 - val_smape: 0.3524

Epoch 57/128

240/240 - 1s - 3ms/step - ia: 0.8791 - loss: 0.0805 - mae: 0.1766 - rmse: 0.2764 - smape: 0.4271 - val_ia: 0.8662 - val_loss: 0.0580 - val_mae: 0.1358 - val_rmse: 0.2163 - val_smape: 0.3602

Epoch 58/128

240/240 - 1s - 3ms/step - ia: 0.8796 - loss: 0.0804 - mae: 0.1760 - rmse: 0.2761 - smape: 0.4297 - val_ia: 0.8614 - val_loss: 0.0576 - val_mae: 0.1378 - val_rmse: 0.2168 - val_smape: 0.3590

Epoch 59/128

240/240 - 1s - 3ms/step - ia: 0.8795 - loss: 0.0798 - mae: 0.1761 - rmse: 0.2760 - smape: 0.4294 - val_ia: 0.8664 - val_loss: 0.0577 - val_mae: 0.1347 - val_rmse: 0.2160 - val_smape: 0.3531

Epoch 60/128

240/240 - 1s - 6ms/step - ia: 0.8801 - loss: 0.0796 - mae: 0.1751 - rmse: 0.2743 - smape: 0.4267 - val_ia: 0.8618 - val_loss: 0.0579 - val_mae: 0.1367 - val_rmse: 0.2182 - val_smape: 0.3584

Epoch 61/128

240/240 - 1s - 2ms/step - ia: 0.8803 - loss: 0.0793 - mae: 0.1749 - rmse: 0.2746 - smape: 0.4265 - val_ia: 0.8706 - val_loss: 0.0569 - val_mae: 0.1318 - val_rmse: 0.2147 - val_smape: 0.3498

Epoch 62/128

240/240 - 1s - 2ms/step - ia: 0.8812 - loss: 0.0786 - mae: 0.1736 - rmse: 0.2726 - smape: 0.4238 - val_ia: 0.8660 - val_loss: 0.0581 - val_mae: 0.1353 - val_rmse: 0.2171 - val_smape: 0.3552

Epoch 63/128

240/240 - 1s - 2ms/step - ia: 0.8807 - loss: 0.0796 - mae: 0.1740 - rmse: 0.2746 - smape: 0.4226 - val_ia: 0.8660 - val_loss: 0.0569 - val_mae: 0.1342 - val_rmse: 0.2154 - val_smape: 0.3526

Epoch 64/128

240/240 - 1s - 3ms/step - ia: 0.8814 - loss: 0.0786 - mae: 0.1733 - rmse: 0.2730 - smape: 0.4238 - val_ia: 0.8685 - val_loss: 0.0572 - val_mae: 0.1330 - val_rmse: 0.2156 - val_smape: 0.3514

Epoch 65/128

240/240 - 1s - 2ms/step - ia: 0.8823 - loss: 0.0775 - mae: 0.1723 - rmse: 0.2712 - smape: 0.4222 - val_ia: 0.8683 - val_loss: 0.0566 - val_mae: 0.1328 - val_rmse: 0.2143 - val_smape: 0.3511

Epoch 66/128

240/240 - 1s - 2ms/step - ia: 0.8821 - loss: 0.0774 - mae: 0.1721 - rmse: 0.2715 - smape: 0.4203 - val_ia: 0.8687 - val_loss: 0.0565 - val_mae: 0.1325 - val_rmse: 0.2147 - val_smape: 0.3504

Epoch 67/128

240/240 - 1s - 3ms/step - ia: 0.8821 - loss: 0.0793 - mae: 0.1722 - rmse: 0.2743 - smape: 0.4215 - val_ia: 0.8713 - val_loss: 0.0563 - val_mae: 0.1310 - val_rmse: 0.2135 - val_smape: 0.3502

Epoch 68/128

240/240 - 1s - 6ms/step - ia: 0.8826 - loss: 0.0780 - mae: 0.1718 - rmse: 0.2715 - smape: 0.4193 - val_ia: 0.8651 - val_loss: 0.0566 - val_mae: 0.1349 - val_rmse: 0.2147 - val_smape: 0.3548

Epoch 69/128

240/240 - 1s - 4ms/step - ia: 0.8830 - loss: 0.0764 - mae: 0.1709 - rmse: 0.2700 - smape: 0.4187 - val_ia: 0.8708 - val_loss: 0.0564 - val_mae: 0.1320 - val_rmse: 0.2138 - val_smape: 0.3526

Epoch 70/128

240/240 - 1s - 4ms/step - ia: 0.8823 - loss: 0.0775 - mae: 0.1720 - rmse: 0.2714 - smape: 0.4200 - val_ia: 0.8688 - val_loss: 0.0562 - val_mae: 0.1328 - val_rmse: 0.2137 - val_smape: 0.3532

Epoch 71/128

240/240 - 1s - 5ms/step - ia: 0.8839 - loss: 0.0763 - mae: 0.1699 - rmse: 0.2694 - smape: 0.4165 - val_ia: 0.8688 - val_loss: 0.0564 - val_mae: 0.1327 - val_rmse: 0.2139 - val_smape: 0.3522

Epoch 72/128

240/240 - 1s - 4ms/step - ia: 0.8833 - loss: 0.0760 - mae: 0.1704 - rmse: 0.2687 - smape: 0.4185 - val_ia: 0.8720 - val_loss: 0.0563 - val_mae: 0.1305 - val_rmse: 0.2143 - val_smape: 0.3466

Epoch 73/128

240/240 - 1s - 4ms/step - ia: 0.8841 - loss: 0.0763 - mae: 0.1694 - rmse: 0.2693 - smape: 0.4162 - val_ia: 0.8677 - val_loss: 0.0561 - val_mae: 0.1332 - val_rmse: 0.2135 - val_smape: 0.3536

Epoch 74/128

240/240 - 1s - 5ms/step - ia: 0.8844 - loss: 0.0756 - mae: 0.1686 - rmse: 0.2683 - smape: 0.4149 - val_ia: 0.8674 - val_loss: 0.0563 - val_mae: 0.1333 - val_rmse: 0.2138 - val_smape: 0.3527

Epoch 75/128

240/240 - 1s - 3ms/step - ia: 0.8840 - loss: 0.0760 - mae: 0.1693 - rmse: 0.2682 - smape: 0.4152 - val_ia: 0.8643 - val_loss: 0.0567 - val_mae: 0.1354 - val_rmse: 0.2161 - val_smape: 0.3543

Epoch 76/128

240/240 - 1s - 4ms/step - ia: 0.8839 - loss: 0.0762 - mae: 0.1693 - rmse: 0.2694 - smape: 0.4139 - val_ia: 0.8644 - val_loss: 0.0566 - val_mae: 0.1356 - val_rmse: 0.2151 - val_smape: 0.3548

Epoch 77/128

240/240 - 1s - 6ms/step - ia: 0.8853 - loss: 0.0746 - mae: 0.1678 - rmse: 0.2659 - smape: 0.4110 - val_ia: 0.8655 - val_loss: 0.0563 - val_mae: 0.1346 - val_rmse: 0.2150 - val_smape: 0.3544

Epoch 78/128

240/240 - 2s - 6ms/step - ia: 0.8853 - loss: 0.0755 - mae: 0.1679 - rmse: 0.2678 - smape: 0.4114 - val_ia: 0.8692 - val_loss: 0.0560 - val_mae: 0.1318 - val_rmse: 0.2141 - val_smape: 0.3492

Epoch 79/128

240/240 - 1s - 3ms/step - ia: 0.8849 - loss: 0.0751 - mae: 0.1679 - rmse: 0.2671 - smape: 0.4132 - val_ia: 0.8690 - val_loss: 0.0559 - val_mae: 0.1319 - val_rmse: 0.2137 - val_smape: 0.3491

Epoch 80/128

240/240 - 1s - 6ms/step - ia: 0.8849 - loss: 0.0745 - mae: 0.1682 - rmse: 0.2662 - smape: 0.4121 - val_ia: 0.8588 - val_loss: 0.0581 - val_mae: 0.1397 - val_rmse: 0.2188 - val_smape: 0.3612

Epoch 81/128

240/240 - 1s - 3ms/step - ia: 0.8857 - loss: 0.0746 - mae: 0.1673 - rmse: 0.2657 - smape: 0.4081 - val_ia: 0.8701 - val_loss: 0.0556 - val_mae: 0.1315 - val_rmse: 0.2128 - val_smape: 0.3493

Epoch 82/128

240/240 - 1s - 3ms/step - ia: 0.8859 - loss: 0.0739 - mae: 0.1664 - rmse: 0.2650 - smape: 0.4099 - val_ia: 0.8677 - val_loss: 0.0558 - val_mae: 0.1328 - val_rmse: 0.2133 - val_smape: 0.3508

Epoch 83/128

240/240 - 1s - 3ms/step - ia: 0.8859 - loss: 0.0750 - mae: 0.1670 - rmse: 0.2664 - smape: 0.4087 - val_ia: 0.8650 - val_loss: 0.0565 - val_mae: 0.1353 - val_rmse: 0.2158 - val_smape: 0.3549

Epoch 84/128

240/240 - 1s - 3ms/step - ia: 0.8859 - loss: 0.0735 - mae: 0.1666 - rmse: 0.2639 - smape: 0.4103 - val_ia: 0.8663 - val_loss: 0.0560 - val_mae: 0.1334 - val_rmse: 0.2146 - val_smape: 0.3514

Epoch 85/128

240/240 - 1s - 3ms/step - ia: 0.8869 - loss: 0.0734 - mae: 0.1654 - rmse: 0.2636 - smape: 0.4084 - val_ia: 0.8675 - val_loss: 0.0557 - val_mae: 0.1332 - val_rmse: 0.2132 - val_smape: 0.3526

Epoch 86/128

240/240 - 1s - 3ms/step - ia: 0.8866 - loss: 0.0739 - mae: 0.1657 - rmse: 0.2650 - smape: 0.4065 - val_ia: 0.8685 - val_loss: 0.0559 - val_mae: 0.1329 - val_rmse: 0.2133 - val_smape: 0.3513

Epoch 87/128

240/240 - 1s - 5ms/step - ia: 0.8867 - loss: 0.0737 - mae: 0.1652 - rmse: 0.2637 - smape: 0.4086 - val_ia: 0.8680 - val_loss: 0.0559 - val_mae: 0.1325 - val_rmse: 0.2143 - val_smape: 0.3507

Epoch 88/128

240/240 - 1s - 3ms/step - ia: 0.8874 - loss: 0.0733 - mae: 0.1647 - rmse: 0.2640 - smape: 0.4047 - val_ia: 0.8695 - val_loss: 0.0554 - val_mae: 0.1315 - val_rmse: 0.2130 - val_smape: 0.3485

Epoch 89/128

240/240 - 1s - 3ms/step - ia: 0.8870 - loss: 0.0736 - mae: 0.1652 - rmse: 0.2639 - smape: 0.4053 - val_ia: 0.8639 - val_loss: 0.0562 - val_mae: 0.1357 - val_rmse: 0.2148 - val_smape: 0.3542

Epoch 90/128

240/240 - 1s - 6ms/step - ia: 0.8878 - loss: 0.0727 - mae: 0.1639 - rmse: 0.2622 - smape: 0.4049 - val_ia: 0.8718 - val_loss: 0.0553 - val_mae: 0.1305 - val_rmse: 0.2121 - val_smape: 0.3479

Epoch 91/128

240/240 - 1s - 3ms/step - ia: 0.8883 - loss: 0.0726 - mae: 0.1634 - rmse: 0.2624 - smape: 0.4037 - val_ia: 0.8710 - val_loss: 0.0555 - val_mae: 0.1306 - val_rmse: 0.2132 - val_smape: 0.3470

Epoch 92/128

240/240 - 1s - 3ms/step - ia: 0.8878 - loss: 0.0727 - mae: 0.1640 - rmse: 0.2626 - smape: 0.4060 - val_ia: 0.8674 - val_loss: 0.0553 - val_mae: 0.1329 - val_rmse: 0.2130 - val_smape: 0.3509

Epoch 93/128

240/240 - 1s - 3ms/step - ia: 0.8873 - loss: 0.0735 - mae: 0.1646 - rmse: 0.2638 - smape: 0.4058 - val_ia: 0.8674 - val_loss: 0.0568 - val_mae: 0.1350 - val_rmse: 0.2148 - val_smape: 0.3532

Epoch 94/128

240/240 - 1s - 3ms/step - ia: 0.8877 - loss: 0.0723 - mae: 0.1641 - rmse: 0.2610 - smape: 0.4051 - val_ia: 0.8720 - val_loss: 0.0551 - val_mae: 0.1300 - val_rmse: 0.2118 - val_smape: 0.3467

Epoch 95/128

240/240 - 1s - 3ms/step - ia: 0.8879 - loss: 0.0728 - mae: 0.1641 - rmse: 0.2622 - smape: 0.4052 - val_ia: 0.8693 - val_loss: 0.0551 - val_mae: 0.1320 - val_rmse: 0.2124 - val_smape: 0.3491

Epoch 96/128

240/240 - 1s - 4ms/step - ia: 0.8883 - loss: 0.0726 - mae: 0.1632 - rmse: 0.2626 - smape: 0.4017 - val_ia: 0.8713 - val_loss: 0.0553 - val_mae: 0.1309 - val_rmse: 0.2125 - val_smape: 0.3468

Epoch 97/128

240/240 - 1s - 3ms/step - ia: 0.8892 - loss: 0.0709 - mae: 0.1622 - rmse: 0.2587 - smape: 0.4012 - val_ia: 0.8678 - val_loss: 0.0552 - val_mae: 0.1326 - val_rmse: 0.2129 - val_smape: 0.3504

Epoch 98/128


In [23]:
print(best)

{'activation': 1, 'batch': 4, 'dropout': 0.2, 'layers': 1.0, 'learning_rate': 0.0002707756079796208, 'units': 4}