Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [4]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [5]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [6]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [7]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [8]:
datosNormalizados.shape

(52416, 5)

In [9]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [10]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [11]:
futuros = 1
pasados  = 12

In [12]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [13]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [14]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [15]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (52404, 60)

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 60)
Las dimensiones de testX son:  (10533, 60)
Las dimensiones de valX son:  (5189, 60)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 8s - 28ms/step - ia: 0.2674 - loss: 1.2491 - mae: 0.9158 - rmse: 1.1148 - smape: 1.4796 - val_ia: 0.2424 - val_loss: 0.8193 - val_mae: 0.7497 - val_rmse: 0.9000 - val_smape: 1.6552

Epoch 2/128

287/287 - 1s - 3ms/step - ia: 0.2366 - loss: 1.0978 - mae: 0.8649 - rmse: 1.0462 - smape: 1.5214 - val_ia: 0.2425 - val_loss: 0.8045 - val_mae: 0.7446 - val_rmse: 0.8909 - val_smape: 1.8059

Epoch 3/128

287/287 - 1s - 4ms/step - ia: 0.2392 - loss: 1.0268 - mae: 0.8350 - rmse: 1.0117 - smape: 1.5088 - val_ia: 0.2749 - val_loss: 0.7508 - val_mae: 0.7170 - val_rmse: 0.8602 - val_smape: 1.6341

Epoch 4/128

287/287 - 2s - 6ms/step - ia: 0.2840 - loss: 0.9278 - mae: 0.7889 - rmse: 0.9619 - smape: 1.4337 - val_ia: 0.3496 - val_loss: 0.6458 - val_mae: 0.6593 - val_rmse: 0.7968 - val_smape: 1.3620

Epoch 5/128

287/287 - 2s - 6ms/step - ia: 0.3617 - loss: 0.8160 - mae: 0.7299 - rmse: 0.9014 - smape: 1.3077 - val_ia: 0.4729 - val_loss: 0.4952 - val_mae: 0.5661 - val_rmse: 0.6961 - val_smape: 1.0486

Epoch 6/128

287/287 - 1s - 3ms/step - ia: 0.4690 - loss: 0.6789 - mae: 0.6573 - rmse: 0.8219 - smape: 1.1478 - val_ia: 0.6057 - val_loss: 0.3334 - val_mae: 0.4465 - val_rmse: 0.5703 - val_smape: 0.7817

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.5498 - loss: 0.5823 - mae: 0.6028 - rmse: 0.7615 - smape: 1.0215 - val_ia: 0.6958 - val_loss: 0.2332 - val_mae: 0.3577 - val_rmse: 0.4766 - val_smape: 0.6041

Epoch 8/128

287/287 - 2s - 5ms/step - ia: 0.5879 - loss: 0.5366 - mae: 0.5784 - rmse: 0.7309 - smape: 0.9591 - val_ia: 0.7330 - val_loss: 0.1938 - val_mae: 0.3204 - val_rmse: 0.4338 - val_smape: 0.5196

Epoch 9/128

287/287 - 1s - 4ms/step - ia: 0.6101 - loss: 0.5023 - mae: 0.5599 - rmse: 0.7073 - smape: 0.9226 - val_ia: 0.7510 - val_loss: 0.1748 - val_mae: 0.2982 - val_rmse: 0.4115 - val_smape: 0.4676

Epoch 10/128

287/287 - 1s - 3ms/step - ia: 0.6234 - loss: 0.4765 - mae: 0.5463 - rmse: 0.6887 - smape: 0.8967 - val_ia: 0.7643 - val_loss: 0.1624 - val_mae: 0.2840 - val_rmse: 0.3962 - val_smape: 0.4448

Epoch 11/128

287/287 - 2s - 7ms/step - ia: 0.6325 - loss: 0.4606 - mae: 0.5370 - rmse: 0.6769 - smape: 0.8802 - val_ia: 0.7666 - val_loss: 0.1573 - val_mae: 0.2795 - val_rmse: 0.3900 - val_smape: 0.4524

Epoch 12/128

287/287 - 2s - 8ms/step - ia: 0.6441 - loss: 0.4414 - mae: 0.5232 - rmse: 0.6629 - smape: 0.8565 - val_ia: 0.7769 - val_loss: 0.1481 - val_mae: 0.2681 - val_rmse: 0.3783 - val_smape: 0.4393

Epoch 13/128

287/287 - 1s - 4ms/step - ia: 0.6500 - loss: 0.4310 - mae: 0.5168 - rmse: 0.6549 - smape: 0.8450 - val_ia: 0.7709 - val_loss: 0.1486 - val_mae: 0.2758 - val_rmse: 0.3794 - val_smape: 0.4788

Epoch 14/128

287/287 - 1s - 3ms/step - ia: 0.6569 - loss: 0.4185 - mae: 0.5090 - rmse: 0.6456 - smape: 0.8355 - val_ia: 0.7736 - val_loss: 0.1440 - val_mae: 0.2723 - val_rmse: 0.3732 - val_smape: 0.4801

Epoch 15/128

287/287 - 1s - 3ms/step - ia: 0.6598 - loss: 0.4121 - mae: 0.5055 - rmse: 0.6407 - smape: 0.8305 - val_ia: 0.7788 - val_loss: 0.1401 - val_mae: 0.2658 - val_rmse: 0.3680 - val_smape: 0.4636

Epoch 16/128

287/287 - 1s - 4ms/step - ia: 0.6633 - loss: 0.4035 - mae: 0.5006 - rmse: 0.6338 - smape: 0.8244 - val_ia: 0.7829 - val_loss: 0.1353 - val_mae: 0.2620 - val_rmse: 0.3616 - val_smape: 0.4598

Epoch 17/128

287/287 - 1s - 5ms/step - ia: 0.6670 - loss: 0.3970 - mae: 0.4966 - rmse: 0.6285 - smape: 0.8179 - val_ia: 0.7837 - val_loss: 0.1324 - val_mae: 0.2623 - val_rmse: 0.3577 - val_smape: 0.4752

Epoch 18/128

287/287 - 1s - 3ms/step - ia: 0.6744 - loss: 0.3851 - mae: 0.4880 - rmse: 0.6190 - smape: 0.8056 - val_ia: 0.7807 - val_loss: 0.1330 - val_mae: 0.2659 - val_rmse: 0.3588 - val_smape: 0.4986

Epoch 19/128

287/287 - 2s - 6ms/step - ia: 0.6765 - loss: 0.3836 - mae: 0.4846 - rmse: 0.6180 - smape: 0.8025 - val_ia: 0.7833 - val_loss: 0.1301 - val_mae: 0.2626 - val_rmse: 0.3547 - val_smape: 0.4919

Epoch 20/128

287/287 - 1s - 4ms/step - ia: 0.6812 - loss: 0.3737 - mae: 0.4788 - rmse: 0.6101 - smape: 0.7941 - val_ia: 0.7795 - val_loss: 0.1312 - val_mae: 0.2661 - val_rmse: 0.3566 - val_smape: 0.5058

Epoch 21/128

287/287 - 1s - 4ms/step - ia: 0.6848 - loss: 0.3647 - mae: 0.4733 - rmse: 0.6026 - smape: 0.7878 - val_ia: 0.7864 - val_loss: 0.1249 - val_mae: 0.2590 - val_rmse: 0.3479 - val_smape: 0.4895

Epoch 22/128

287/287 - 1s - 3ms/step - ia: 0.6875 - loss: 0.3614 - mae: 0.4706 - rmse: 0.5996 - smape: 0.7840 - val_ia: 0.7863 - val_loss: 0.1242 - val_mae: 0.2602 - val_rmse: 0.3470 - val_smape: 0.5017

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.6916 - loss: 0.3541 - mae: 0.4659 - rmse: 0.5936 - smape: 0.7789 - val_ia: 0.7853 - val_loss: 0.1231 - val_mae: 0.2617 - val_rmse: 0.3455 - val_smape: 0.5155

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.6928 - loss: 0.3531 - mae: 0.4649 - rmse: 0.5929 - smape: 0.7786 - val_ia: 0.7870 - val_loss: 0.1225 - val_mae: 0.2580 - val_rmse: 0.3446 - val_smape: 0.4952

Epoch 25/128

287/287 - 1s - 3ms/step - ia: 0.6984 - loss: 0.3433 - mae: 0.4571 - rmse: 0.5844 - smape: 0.7675 - val_ia: 0.7913 - val_loss: 0.1187 - val_mae: 0.2542 - val_rmse: 0.3391 - val_smape: 0.4856

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.7007 - loss: 0.3389 - mae: 0.4537 - rmse: 0.5809 - smape: 0.7662 - val_ia: 0.7887 - val_loss: 0.1197 - val_mae: 0.2563 - val_rmse: 0.3409 - val_smape: 0.4928

Epoch 27/128

287/287 - 1s - 4ms/step - ia: 0.6996 - loss: 0.3413 - mae: 0.4540 - rmse: 0.5828 - smape: 0.7672 - val_ia: 0.7945 - val_loss: 0.1153 - val_mae: 0.2498 - val_rmse: 0.3343 - val_smape: 0.4699

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.7050 - loss: 0.3308 - mae: 0.4479 - rmse: 0.5735 - smape: 0.7594 - val_ia: 0.7977 - val_loss: 0.1119 - val_mae: 0.2475 - val_rmse: 0.3295 - val_smape: 0.4661

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.7057 - loss: 0.3308 - mae: 0.4464 - rmse: 0.5736 - smape: 0.7596 - val_ia: 0.7970 - val_loss: 0.1128 - val_mae: 0.2466 - val_rmse: 0.3309 - val_smape: 0.4558

Epoch 30/128

287/287 - 1s - 4ms/step - ia: 0.7071 - loss: 0.3285 - mae: 0.4448 - rmse: 0.5718 - smape: 0.7578 - val_ia: 0.7992 - val_loss: 0.1108 - val_mae: 0.2454 - val_rmse: 0.3279 - val_smape: 0.4596

Epoch 31/128

287/287 - 1s - 5ms/step - ia: 0.7110 - loss: 0.3225 - mae: 0.4389 - rmse: 0.5663 - smape: 0.7500 - val_ia: 0.8054 - val_loss: 0.1063 - val_mae: 0.2389 - val_rmse: 0.3210 - val_smape: 0.4398

Epoch 32/128

287/287 - 1s - 4ms/step - ia: 0.7120 - loss: 0.3187 - mae: 0.4377 - rmse: 0.5633 - smape: 0.7518 - val_ia: 0.8071 - val_loss: 0.1049 - val_mae: 0.2372 - val_rmse: 0.3187 - val_smape: 0.4356

Epoch 33/128

287/287 - 1s - 3ms/step - ia: 0.7134 - loss: 0.3173 - mae: 0.4355 - rmse: 0.5616 - smape: 0.7479 - val_ia: 0.8053 - val_loss: 0.1052 - val_mae: 0.2382 - val_rmse: 0.3193 - val_smape: 0.4353

Epoch 34/128

287/287 - 1s - 3ms/step - ia: 0.7158 - loss: 0.3135 - mae: 0.4320 - rmse: 0.5583 - smape: 0.7442 - val_ia: 0.8108 - val_loss: 0.1014 - val_mae: 0.2321 - val_rmse: 0.3132 - val_smape: 0.4185

Epoch 35/128

287/287 - 1s - 3ms/step - ia: 0.7195 - loss: 0.3060 - mae: 0.4272 - rmse: 0.5519 - smape: 0.7425 - val_ia: 0.8129 - val_loss: 0.1000 - val_mae: 0.2303 - val_rmse: 0.3110 - val_smape: 0.4158

Epoch 36/128

287/287 - 1s - 3ms/step - ia: 0.7185 - loss: 0.3108 - mae: 0.4285 - rmse: 0.5558 - smape: 0.7412 - val_ia: 0.8120 - val_loss: 0.1005 - val_mae: 0.2316 - val_rmse: 0.3119 - val_smape: 0.4170

Epoch 37/128

287/287 - 1s - 3ms/step - ia: 0.7227 - loss: 0.3016 - mae: 0.4219 - rmse: 0.5474 - smape: 0.7329 - val_ia: 0.8191 - val_loss: 0.0945 - val_mae: 0.2236 - val_rmse: 0.3023 - val_smape: 0.3966

Epoch 38/128

287/287 - 1s - 3ms/step - ia: 0.7239 - loss: 0.2995 - mae: 0.4206 - rmse: 0.5456 - smape: 0.7334 - val_ia: 0.8204 - val_loss: 0.0935 - val_mae: 0.2225 - val_rmse: 0.3006 - val_smape: 0.3946

Epoch 39/128

287/287 - 1s - 3ms/step - ia: 0.7241 - loss: 0.2989 - mae: 0.4207 - rmse: 0.5453 - smape: 0.7330 - val_ia: 0.8204 - val_loss: 0.0940 - val_mae: 0.2218 - val_rmse: 0.3013 - val_smape: 0.3902

Epoch 40/128

287/287 - 1s - 2ms/step - ia: 0.7271 - loss: 0.2937 - mae: 0.4162 - rmse: 0.5406 - smape: 0.7297 - val_ia: 0.8219 - val_loss: 0.0920 - val_mae: 0.2220 - val_rmse: 0.2981 - val_smape: 0.3946

Epoch 41/128

287/287 - 1s - 3ms/step - ia: 0.7272 - loss: 0.2926 - mae: 0.4160 - rmse: 0.5394 - smape: 0.7298 - val_ia: 0.8251 - val_loss: 0.0895 - val_mae: 0.2173 - val_rmse: 0.2939 - val_smape: 0.3828

Epoch 42/128

287/287 - 1s - 5ms/step - ia: 0.7295 - loss: 0.2905 - mae: 0.4127 - rmse: 0.5373 - smape: 0.7251 - val_ia: 0.8255 - val_loss: 0.0893 - val_mae: 0.2176 - val_rmse: 0.2937 - val_smape: 0.3851

Epoch 43/128

287/287 - 1s - 3ms/step - ia: 0.7282 - loss: 0.2920 - mae: 0.4133 - rmse: 0.5389 - smape: 0.7261 - val_ia: 0.8253 - val_loss: 0.0888 - val_mae: 0.2187 - val_rmse: 0.2929 - val_smape: 0.3890

Epoch 44/128

287/287 - 1s - 3ms/step - ia: 0.7305 - loss: 0.2883 - mae: 0.4101 - rmse: 0.5355 - smape: 0.7211 - val_ia: 0.8302 - val_loss: 0.0847 - val_mae: 0.2136 - val_rmse: 0.2858 - val_smape: 0.3788

Epoch 45/128

287/287 - 1s - 5ms/step - ia: 0.7359 - loss: 0.2804 - mae: 0.4041 - rmse: 0.5278 - smape: 0.7137 - val_ia: 0.8288 - val_loss: 0.0858 - val_mae: 0.2145 - val_rmse: 0.2879 - val_smape: 0.3790

Epoch 46/128

287/287 - 1s - 3ms/step - ia: 0.7341 - loss: 0.2840 - mae: 0.4050 - rmse: 0.5314 - smape: 0.7144 - val_ia: 0.8322 - val_loss: 0.0827 - val_mae: 0.2106 - val_rmse: 0.2825 - val_smape: 0.3714

Epoch 47/128

287/287 - 1s - 3ms/step - ia: 0.7359 - loss: 0.2796 - mae: 0.4028 - rmse: 0.5272 - smape: 0.7161 - val_ia: 0.8363 - val_loss: 0.0810 - val_mae: 0.2067 - val_rmse: 0.2793 - val_smape: 0.3659

Epoch 48/128

287/287 - 1s - 3ms/step - ia: 0.7397 - loss: 0.2738 - mae: 0.3978 - rmse: 0.5216 - smape: 0.7068 - val_ia: 0.8331 - val_loss: 0.0819 - val_mae: 0.2098 - val_rmse: 0.2812 - val_smape: 0.3674

Epoch 49/128

287/287 - 1s - 3ms/step - ia: 0.7378 - loss: 0.2770 - mae: 0.4001 - rmse: 0.5249 - smape: 0.7121 - val_ia: 0.8330 - val_loss: 0.0805 - val_mae: 0.2107 - val_rmse: 0.2789 - val_smape: 0.3751

Epoch 50/128

287/287 - 1s - 4ms/step - ia: 0.7372 - loss: 0.2785 - mae: 0.4010 - rmse: 0.5260 - smape: 0.7160 - val_ia: 0.8357 - val_loss: 0.0804 - val_mae: 0.2070 - val_rmse: 0.2786 - val_smape: 0.3675

Epoch 51/128

287/287 - 1s - 5ms/step - ia: 0.7403 - loss: 0.2726 - mae: 0.3962 - rmse: 0.5207 - smape: 0.7124 - val_ia: 0.8358 - val_loss: 0.0798 - val_mae: 0.2067 - val_rmse: 0.2773 - val_smape: 0.3678

Epoch 52/128

287/287 - 1s - 2ms/step - ia: 0.7424 - loss: 0.2697 - mae: 0.3933 - rmse: 0.5177 - smape: 0.7050 - val_ia: 0.8401 - val_loss: 0.0760 - val_mae: 0.2034 - val_rmse: 0.2708 - val_smape: 0.3650

Epoch 53/128

287/287 - 2s - 5ms/step - ia: 0.7402 - loss: 0.2736 - mae: 0.3961 - rmse: 0.5216 - smape: 0.7123 - val_ia: 0.8394 - val_loss: 0.0765 - val_mae: 0.2033 - val_rmse: 0.2714 - val_smape: 0.3634

Epoch 54/128

287/287 - 1s - 5ms/step - ia: 0.7432 - loss: 0.2688 - mae: 0.3927 - rmse: 0.5169 - smape: 0.7029 - val_ia: 0.8403 - val_loss: 0.0755 - val_mae: 0.2024 - val_rmse: 0.2698 - val_smape: 0.3591

Epoch 55/128

287/287 - 1s - 5ms/step - ia: 0.7446 - loss: 0.2674 - mae: 0.3901 - rmse: 0.5154 - smape: 0.7027 - val_ia: 0.8417 - val_loss: 0.0752 - val_mae: 0.2009 - val_rmse: 0.2690 - val_smape: 0.3597

Epoch 56/128

287/287 - 1s - 5ms/step - ia: 0.7451 - loss: 0.2663 - mae: 0.3896 - rmse: 0.5145 - smape: 0.7020 - val_ia: 0.8403 - val_loss: 0.0749 - val_mae: 0.2033 - val_rmse: 0.2689 - val_smape: 0.3659

Epoch 57/128

287/287 - 2s - 6ms/step - ia: 0.7456 - loss: 0.2651 - mae: 0.3892 - rmse: 0.5132 - smape: 0.6993 - val_ia: 0.8384 - val_loss: 0.0762 - val_mae: 0.2045 - val_rmse: 0.2711 - val_smape: 0.3672

Epoch 58/128

287/287 - 2s - 7ms/step - ia: 0.7470 - loss: 0.2617 - mae: 0.3865 - rmse: 0.5101 - smape: 0.7007 - val_ia: 0.8426 - val_loss: 0.0730 - val_mae: 0.1998 - val_rmse: 0.2651 - val_smape: 0.3584

Epoch 59/128

287/287 - 1s - 4ms/step - ia: 0.7473 - loss: 0.2606 - mae: 0.3860 - rmse: 0.5090 - smape: 0.7018 - val_ia: 0.8434 - val_loss: 0.0722 - val_mae: 0.1989 - val_rmse: 0.2639 - val_smape: 0.3543

Epoch 60/128

287/287 - 1s - 5ms/step - ia: 0.7468 - loss: 0.2618 - mae: 0.3869 - rmse: 0.5101 - smape: 0.7041 - val_ia: 0.8454 - val_loss: 0.0711 - val_mae: 0.1966 - val_rmse: 0.2616 - val_smape: 0.3522

Epoch 61/128

287/287 - 1s - 3ms/step - ia: 0.7482 - loss: 0.2618 - mae: 0.3847 - rmse: 0.5099 - smape: 0.6988 - val_ia: 0.8454 - val_loss: 0.0709 - val_mae: 0.1981 - val_rmse: 0.2612 - val_smape: 0.3609

Epoch 62/128

287/287 - 1s - 5ms/step - ia: 0.7509 - loss: 0.2564 - mae: 0.3813 - rmse: 0.5047 - smape: 0.6903 - val_ia: 0.8455 - val_loss: 0.0705 - val_mae: 0.1969 - val_rmse: 0.2605 - val_smape: 0.3580

Epoch 63/128

287/287 - 1s - 4ms/step - ia: 0.7510 - loss: 0.2545 - mae: 0.3801 - rmse: 0.5027 - smape: 0.6942 - val_ia: 0.8511 - val_loss: 0.0667 - val_mae: 0.1916 - val_rmse: 0.2531 - val_smape: 0.3517

Epoch 64/128

287/287 - 1s - 2ms/step - ia: 0.7499 - loss: 0.2595 - mae: 0.3830 - rmse: 0.5080 - smape: 0.6946 - val_ia: 0.8469 - val_loss: 0.0690 - val_mae: 0.1954 - val_rmse: 0.2579 - val_smape: 0.3549

Epoch 65/128

287/287 - 2s - 5ms/step - ia: 0.7508 - loss: 0.2558 - mae: 0.3806 - rmse: 0.5039 - smape: 0.6956 - val_ia: 0.8490 - val_loss: 0.0675 - val_mae: 0.1937 - val_rmse: 0.2549 - val_smape: 0.3568

Epoch 66/128

287/287 - 1s - 5ms/step - ia: 0.7528 - loss: 0.2524 - mae: 0.3784 - rmse: 0.5008 - smape: 0.6903 - val_ia: 0.8447 - val_loss: 0.0697 - val_mae: 0.1980 - val_rmse: 0.2592 - val_smape: 0.3649

Epoch 67/128

287/287 - 1s - 2ms/step - ia: 0.7535 - loss: 0.2503 - mae: 0.3770 - rmse: 0.4989 - smape: 0.6928 - val_ia: 0.8462 - val_loss: 0.0687 - val_mae: 0.1956 - val_rmse: 0.2572 - val_smape: 0.3604

Epoch 68/128

287/287 - 1s - 3ms/step - ia: 0.7517 - loss: 0.2547 - mae: 0.3794 - rmse: 0.5030 - smape: 0.6955 - val_ia: 0.8465 - val_loss: 0.0682 - val_mae: 0.1959 - val_rmse: 0.2563 - val_smape: 0.3601

Epoch 69/128

287/287 - 1s - 5ms/step - ia: 0.7546 - loss: 0.2514 - mae: 0.3759 - rmse: 0.4996 - smape: 0.6860 - val_ia: 0.8474 - val_loss: 0.0683 - val_mae: 0.1948 - val_rmse: 0.2562 - val_smape: 0.3606

Epoch 70/128

287/287 - 1s - 3ms/step - ia: 0.7531 - loss: 0.2510 - mae: 0.3772 - rmse: 0.4995 - smape: 0.6951 - val_ia: 0.8493 - val_loss: 0.0667 - val_mae: 0.1926 - val_rmse: 0.2532 - val_smape: 0.3587

Epoch 71/128

287/287 - 1s - 3ms/step - ia: 0.7570 - loss: 0.2460 - mae: 0.3730 - rmse: 0.4944 - smape: 0.6850 - val_ia: 0.8511 - val_loss: 0.0652 - val_mae: 0.1903 - val_rmse: 0.2502 - val_smape: 0.3501

Epoch 72/128

287/287 - 1s - 3ms/step - ia: 0.7559 - loss: 0.2477 - mae: 0.3744 - rmse: 0.4959 - smape: 0.6861 - val_ia: 0.8464 - val_loss: 0.0673 - val_mae: 0.1958 - val_rmse: 0.2544 - val_smape: 0.3665

Epoch 73/128

287/287 - 1s - 4ms/step - ia: 0.7555 - loss: 0.2474 - mae: 0.3742 - rmse: 0.4958 - smape: 0.6857 - val_ia: 0.8529 - val_loss: 0.0639 - val_mae: 0.1891 - val_rmse: 0.2477 - val_smape: 0.3519

Epoch 74/128

287/287 - 1s - 4ms/step - ia: 0.7582 - loss: 0.2461 - mae: 0.3708 - rmse: 0.4944 - smape: 0.6828 - val_ia: 0.8521 - val_loss: 0.0644 - val_mae: 0.1901 - val_rmse: 0.2487 - val_smape: 0.3553

Epoch 75/128

287/287 - 2s - 6ms/step - ia: 0.7594 - loss: 0.2419 - mae: 0.3688 - rmse: 0.4902 - smape: 0.6798 - val_ia: 0.8530 - val_loss: 0.0626 - val_mae: 0.1892 - val_rmse: 0.2454 - val_smape: 0.3543

Epoch 76/128

287/287 - 1s - 4ms/step - ia: 0.7575 - loss: 0.2448 - mae: 0.3716 - rmse: 0.4932 - smape: 0.6881 - val_ia: 0.8567 - val_loss: 0.0618 - val_mae: 0.1844 - val_rmse: 0.2433 - val_smape: 0.3394

Epoch 77/128

287/287 - 2s - 5ms/step - ia: 0.7588 - loss: 0.2428 - mae: 0.3691 - rmse: 0.4909 - smape: 0.6828 - val_ia: 0.8585 - val_loss: 0.0607 - val_mae: 0.1825 - val_rmse: 0.2411 - val_smape: 0.3362

Epoch 78/128

287/287 - 3s - 10ms/step - ia: 0.7586 - loss: 0.2433 - mae: 0.3693 - rmse: 0.4912 - smape: 0.6838 - val_ia: 0.8606 - val_loss: 0.0595 - val_mae: 0.1801 - val_rmse: 0.2385 - val_smape: 0.3339

Epoch 79/128

287/287 - 2s - 8ms/step - ia: 0.7581 - loss: 0.2442 - mae: 0.3706 - rmse: 0.4926 - smape: 0.6840 - val_ia: 0.8575 - val_loss: 0.0618 - val_mae: 0.1839 - val_rmse: 0.2431 - val_smape: 0.3439

Epoch 80/128

287/287 - 1s - 4ms/step - ia: 0.7593 - loss: 0.2434 - mae: 0.3685 - rmse: 0.4916 - smape: 0.6827 - val_ia: 0.8627 - val_loss: 0.0584 - val_mae: 0.1784 - val_rmse: 0.2364 - val_smape: 0.3308

Epoch 81/128

287/287 - 1s - 4ms/step - ia: 0.7609 - loss: 0.2392 - mae: 0.3662 - rmse: 0.4874 - smape: 0.6801 - val_ia: 0.8635 - val_loss: 0.0578 - val_mae: 0.1767 - val_rmse: 0.2350 - val_smape: 0.3258

Epoch 82/128

287/287 - 2s - 8ms/step - ia: 0.7615 - loss: 0.2393 - mae: 0.3660 - rmse: 0.4873 - smape: 0.6762 - val_ia: 0.8607 - val_loss: 0.0590 - val_mae: 0.1813 - val_rmse: 0.2379 - val_smape: 0.3371

Epoch 83/128

287/287 - 3s - 9ms/step - ia: 0.7603 - loss: 0.2405 - mae: 0.3675 - rmse: 0.4890 - smape: 0.6774 - val_ia: 0.8640 - val_loss: 0.0578 - val_mae: 0.1769 - val_rmse: 0.2349 - val_smape: 0.3279

Epoch 84/128

287/287 - 1s - 5ms/step - ia: 0.7608 - loss: 0.2394 - mae: 0.3660 - rmse: 0.4878 - smape: 0.6815 - val_ia: 0.8648 - val_loss: 0.0567 - val_mae: 0.1762 - val_rmse: 0.2328 - val_smape: 0.3274

Epoch 85/128

287/287 - 2s - 8ms/step - ia: 0.7620 - loss: 0.2380 - mae: 0.3649 - rmse: 0.4862 - smape: 0.6794 - val_ia: 0.8653 - val_loss: 0.0562 - val_mae: 0.1742 - val_rmse: 0.2314 - val_smape: 0.3204

Epoch 86/128

287/287 - 1s - 4ms/step - ia: 0.7620 - loss: 0.2378 - mae: 0.3645 - rmse: 0.4859 - smape: 0.6780 - val_ia: 0.8658 - val_loss: 0.0563 - val_mae: 0.1738 - val_rmse: 0.2318 - val_smape: 0.3149

Epoch 87/128

287/287 - 2s - 5ms/step - ia: 0.7631 - loss: 0.2381 - mae: 0.3637 - rmse: 0.4861 - smape: 0.6755 - val_ia: 0.8664 - val_loss: 0.0559 - val_mae: 0.1726 - val_rmse: 0.2308 - val_smape: 0.3151

Epoch 88/128

287/287 - 2s - 6ms/step - ia: 0.7623 - loss: 0.2364 - mae: 0.3633 - rmse: 0.4847 - smape: 0.6757 - val_ia: 0.8655 - val_loss: 0.0552 - val_mae: 0.1743 - val_rmse: 0.2297 - val_smape: 0.3198

Epoch 89/128

287/287 - 1s - 5ms/step - ia: 0.7624 - loss: 0.2378 - mae: 0.3638 - rmse: 0.4859 - smape: 0.6791 - val_ia: 0.8682 - val_loss: 0.0546 - val_mae: 0.1715 - val_rmse: 0.2284 - val_smape: 0.3132

Epoch 90/128

287/287 - 1s - 4ms/step - ia: 0.7654 - loss: 0.2317 - mae: 0.3599 - rmse: 0.4799 - smape: 0.6686 - val_ia: 0.8680 - val_loss: 0.0541 - val_mae: 0.1713 - val_rmse: 0.2273 - val_smape: 0.3120

Epoch 91/128

287/287 - 1s - 5ms/step - ia: 0.7635 - loss: 0.2350 - mae: 0.3619 - rmse: 0.4832 - smape: 0.6756 - val_ia: 0.8718 - val_loss: 0.0525 - val_mae: 0.1669 - val_rmse: 0.2238 - val_smape: 0.3003

Epoch 92/128

287/287 - 1s - 5ms/step - ia: 0.7649 - loss: 0.2348 - mae: 0.3608 - rmse: 0.4829 - smape: 0.6724 - val_ia: 0.8724 - val_loss: 0.0528 - val_mae: 0.1663 - val_rmse: 0.2242 - val_smape: 0.3007

Epoch 93/128

287/287 - 1s - 4ms/step - ia: 0.7639 - loss: 0.2342 - mae: 0.3616 - rmse: 0.4822 - smape: 0.6742 - val_ia: 0.8718 - val_loss: 0.0527 - val_mae: 0.1667 - val_rmse: 0.2240 - val_smape: 0.3029

Epoch 94/128

287/287 - 1s - 4ms/step - ia: 0.7628 - loss: 0.2370 - mae: 0.3630 - rmse: 0.4849 - smape: 0.6745 - val_ia: 0.8763 - val_loss: 0.0510 - val_mae: 0.1621 - val_rmse: 0.2202 - val_smape: 0.2897

Epoch 95/128

287/287 - 2s - 6ms/step - ia: 0.7670 - loss: 0.2305 - mae: 0.3577 - rmse: 0.4785 - smape: 0.6692 - val_ia: 0.8733 - val_loss: 0.0525 - val_mae: 0.1656 - val_rmse: 0.2236 - val_smape: 0.2964

Epoch 96/128

287/287 - 1s - 5ms/step - ia: 0.7681 - loss: 0.2289 - mae: 0.3560 - rmse: 0.4767 - smape: 0.6674 - val_ia: 0.8744 - val_loss: 0.0516 - val_mae: 0.1653 - val_rmse: 0.2220 - val_smape: 0.2964

Epoch 97/128

287/287 - 2s - 6ms/step - ia: 0.7650 - loss: 0.2335 - mae: 0.3599 - rmse: 0.4817 - smape: 0.6706 - val_ia: 0.8736 - val_loss: 0.0517 - val_mae: 0.1664 - val_rmse: 0.2221 - val_smape: 0.3063

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 14s - 6ms/step - ia: 0.9546 - loss: 0.0155 - mae: 0.0710 - rmse: 0.0921 - smape: 0.2015 - val_ia: 0.7545 - val_loss: 0.0060 - val_mae: 0.0624 - val_rmse: 0.0737 - val_smape: 0.1916

Epoch 2/128

2293/2293 - 9s - 4ms/step - ia: 0.9641 - loss: 0.0062 - mae: 0.0560 - rmse: 0.0727 - smape: 0.1739 - val_ia: 0.7403 - val_loss: 0.0103 - val_mae: 0.0783 - val_rmse: 0.0897 - val_smape: 0.2390

Epoch 3/128

2293/2293 - 8s - 4ms/step - ia: 0.9674 - loss: 0.0052 - mae: 0.0509 - rmse: 0.0667 - smape: 0.1612 - val_ia: 0.8506 - val_loss: 0.0031 - val_mae: 0.0381 - val_rmse: 0.0496 - val_smape: 0.1188

Epoch 4/128

2293/2293 - 9s - 4ms/step - ia: 0.9686 - loss: 0.0049 - mae: 0.0488 - rmse: 0.0643 - smape: 0.1564 - val_ia: 0.7674 - val_loss: 0.0061 - val_mae: 0.0599 - val_rmse: 0.0702 - val_smape: 0.1920

Epoch 5/128

2293/2293 - 11s - 5ms/step - ia: 0.9698 - loss: 0.0046 - mae: 0.0473 - rmse: 0.0626 - smape: 0.1527 - val_ia: 0.7811 - val_loss: 0.0046 - val_mae: 0.0513 - val_rmse: 0.0625 - val_smape: 0.1566

Epoch 6/128

2293/2293 - 11s - 5ms/step - ia: 0.9704 - loss: 0.0045 - mae: 0.0462 - rmse: 0.0613 - smape: 0.1504 - val_ia: 0.7895 - val_loss: 0.0041 - val_mae: 0.0485 - val_rmse: 0.0598 - val_smape: 0.1486

Epoch 7/128

2293/2293 - 8s - 4ms/step - ia: 0.9706 - loss: 0.0044 - mae: 0.0457 - rmse: 0.0607 - smape: 0.1492 - val_ia: 0.8240 - val_loss: 0.0033 - val_mae: 0.0421 - val_rmse: 0.0533 - val_smape: 0.1397

Epoch 8/128

2293/2293 - 8s - 3ms/step - ia: 0.9718 - loss: 0.0042 - mae: 0.0441 - rmse: 0.0590 - smape: 0.1465 - val_ia: 0.7681 - val_loss: 0.0067 - val_mae: 0.0651 - val_rmse: 0.0760 - val_smape: 0.1707

Epoch 9/128

2293/2293 - 8s - 3ms/step - ia: 0.9722 - loss: 0.0041 - mae: 0.0433 - rmse: 0.0581 - smape: 0.1440 - val_ia: 0.8267 - val_loss: 0.0036 - val_mae: 0.0436 - val_rmse: 0.0545 - val_smape: 0.1395

Epoch 10/128

2293/2293 - 8s - 4ms/step - ia: 0.9720 - loss: 0.0041 - mae: 0.0436 - rmse: 0.0583 - smape: 0.1446 - val_ia: 0.8304 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0548 - val_smape: 0.1398

Epoch 11/128

2293/2293 - 8s - 4ms/step - ia: 0.9722 - loss: 0.0041 - mae: 0.0434 - rmse: 0.0580 - smape: 0.1438 - val_ia: 0.8524 - val_loss: 0.0028 - val_mae: 0.0365 - val_rmse: 0.0476 - val_smape: 0.1130

Epoch 12/128

2293/2293 - 8s - 3ms/step - ia: 0.9728 - loss: 0.0040 - mae: 0.0425 - rmse: 0.0571 - smape: 0.1425 - val_ia: 0.8307 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0514 - val_smape: 0.1269

Epoch 13/128

2293/2293 - 11s - 5ms/step - ia: 0.9731 - loss: 0.0039 - mae: 0.0421 - rmse: 0.0567 - smape: 0.1421 - val_ia: 0.8500 - val_loss: 0.0027 - val_mae: 0.0352 - val_rmse: 0.0464 - val_smape: 0.1093

Epoch 14/128

2293/2293 - 10s - 5ms/step - ia: 0.9730 - loss: 0.0039 - mae: 0.0423 - rmse: 0.0568 - smape: 0.1415 - val_ia: 0.8399 - val_loss: 0.0031 - val_mae: 0.0390 - val_rmse: 0.0505 - val_smape: 0.1197

Epoch 15/128

2293/2293 - 10s - 5ms/step - ia: 0.9730 - loss: 0.0039 - mae: 0.0422 - rmse: 0.0568 - smape: 0.1411 - val_ia: 0.8364 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0497 - val_smape: 0.1281

Epoch 16/128

2293/2293 - 10s - 4ms/step - ia: 0.9734 - loss: 0.0038 - mae: 0.0414 - rmse: 0.0558 - smape: 0.1405 - val_ia: 0.8403 - val_loss: 0.0034 - val_mae: 0.0416 - val_rmse: 0.0533 - val_smape: 0.1372

Epoch 17/128

2293/2293 - 9s - 4ms/step - ia: 0.9736 - loss: 0.0038 - mae: 0.0412 - rmse: 0.0556 - smape: 0.1404 - val_ia: 0.7893 - val_loss: 0.0043 - val_mae: 0.0503 - val_rmse: 0.0608 - val_smape: 0.1634

Epoch 18/128

2293/2293 - 10s - 4ms/step - ia: 0.9736 - loss: 0.0038 - mae: 0.0411 - rmse: 0.0556 - smape: 0.1393 - val_ia: 0.8282 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0532 - val_smape: 0.1374

Epoch 19/128

2293/2293 - 9s - 4ms/step - ia: 0.9737 - loss: 0.0037 - mae: 0.0411 - rmse: 0.0555 - smape: 0.1399 - val_ia: 0.8051 - val_loss: 0.0038 - val_mae: 0.0473 - val_rmse: 0.0580 - val_smape: 0.1533

Epoch 20/128

2293/2293 - 9s - 4ms/step - ia: 0.9737 - loss: 0.0038 - mae: 0.0411 - rmse: 0.0555 - smape: 0.1399 - val_ia: 0.8514 - val_loss: 0.0028 - val_mae: 0.0358 - val_rmse: 0.0470 - val_smape: 0.1141

Epoch 21/128

2293/2293 - 8s - 3ms/step - ia: 0.9737 - loss: 0.0038 - mae: 0.0410 - rmse: 0.0555 - smape: 0.1391 - val_ia: 0.8188 - val_loss: 0.0034 - val_mae: 0.0418 - val_rmse: 0.0530 - val_smape: 0.1206

Epoch 22/128

2293/2293 - 9s - 4ms/step - ia: 0.9738 - loss: 0.0037 - mae: 0.0408 - rmse: 0.0553 - smape: 0.1381 - val_ia: 0.8216 - val_loss: 0.0032 - val_mae: 0.0414 - val_rmse: 0.0528 - val_smape: 0.1289

Epoch 23/128

2293/2293 - 9s - 4ms/step - ia: 0.9738 - loss: 0.0037 - mae: 0.0407 - rmse: 0.0551 - smape: 0.1382 - val_ia: 0.8515 - val_loss: 0.0028 - val_mae: 0.0367 - val_rmse: 0.0480 - val_smape: 0.1168

Epoch 24/128

2293/2293 - 10s - 4ms/step - ia: 0.9740 - loss: 0.0037 - mae: 0.0405 - rmse: 0.0549 - smape: 0.1374 - val_ia: 0.8141 - val_loss: 0.0033 - val_mae: 0.0413 - val_rmse: 0.0527 - val_smape: 0.1253

Epoch 25/128

2293/2293 - 10s - 5ms/step - ia: 0.9741 - loss: 0.0036 - mae: 0.0403 - rmse: 0.0547 - smape: 0.1369 - val_ia: 0.8137 - val_loss: 0.0041 - val_mae: 0.0487 - val_rmse: 0.0592 - val_smape: 0.1518

Epoch 26/128

2293/2293 - 8s - 3ms/step - ia: 0.9740 - loss: 0.0037 - mae: 0.0407 - rmse: 0.0550 - smape: 0.1384 - val_ia: 0.8497 - val_loss: 0.0027 - val_mae: 0.0355 - val_rmse: 0.0468 - val_smape: 0.1119

Epoch 27/128

2293/2293 - 8s - 3ms/step - ia: 0.9740 - loss: 0.0037 - mae: 0.0406 - rmse: 0.0550 - smape: 0.1378 - val_ia: 0.8444 - val_loss: 0.0031 - val_mae: 0.0394 - val_rmse: 0.0506 - val_smape: 0.1265

Epoch 28/128

2293/2293 - 7s - 3ms/step - ia: 0.9741 - loss: 0.0037 - mae: 0.0403 - rmse: 0.0545 - smape: 0.1375 - val_ia: 0.8133 - val_loss: 0.0035 - val_mae: 0.0442 - val_rmse: 0.0551 - val_smape: 0.1355

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 55s 341ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 17%|█▋        | 2/12 [07:25<38:13, 229.37s/trial, best loss: 0.0018056012500971394]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 16s - 4ms/step - ia: 0.3292 - loss: 0.9903 - mae: 0.7994 - rmse: 0.9646 - smape: 1.5180 - val_ia: 0.1538 - val_loss: 0.7451 - val_mae: 0.7019 - val_rmse: 0.7200 - val_smape: 1.3274

Epoch 2/128

4586/4586 - 13s - 3ms/step - ia: 0.4133 - loss: 0.8315 - mae: 0.7145 - rmse: 0.8799 - smape: 1.4156 - val_ia: 0.1748 - val_loss: 0.6112 - val_mae: 0.6184 - val_rmse: 0.6365 - val_smape: 1.2397

Epoch 3/128

4586/4586 - 13s - 3ms/step - ia: 0.4554 - loss: 0.7407 - mae: 0.6696 - rmse: 0.8300 - smape: 1.3380 - val_ia: 0.1909 - val_loss: 0.5275 - val_mae: 0.5637 - val_rmse: 0.5820 - val_smape: 1.1808

Epoch 4/128

4586/4586 - 12s - 3ms/step - ia: 0.4806 - loss: 0.6781 - mae: 0.6393 - rmse: 0.7940 - smape: 1.2751 - val_ia: 0.1959 - val_loss: 0.4720 - val_mae: 0.5296 - val_rmse: 0.5479 - val_smape: 1.1274

Epoch 5/128

4586/4586 - 21s - 5ms/step - ia: 0.4975 - loss: 0.6369 - mae: 0.6192 - rmse: 0.7687 - smape: 1.2246 - val_ia: 0.1998 - val_loss: 0.4281 - val_mae: 0.5033 - val_rmse: 0.5215 - val_smape: 1.0813

Epoch 6/128

4586/4586 - 15s - 3ms/step - ia: 0.5163 - loss: 0.5917 - mae: 0.5951 - rmse: 0.7400 - smape: 1.1684 - val_ia: 0.2012 - val_loss: 0.3913 - val_mae: 0.4820 - val_rmse: 0.5000 - val_smape: 1.0421

Epoch 7/128

4586/4586 - 19s - 4ms/step - ia: 0.5322 - loss: 0.5622 - mae: 0.5791 - rmse: 0.7216 - smape: 1.1234 - val_ia: 0.2030 - val_loss: 0.3606 - val_mae: 0.4644 - val_rmse: 0.4824 - val_smape: 1.0060

Epoch 8/128

4586/4586 - 22s - 5ms/step - ia: 0.5494 - loss: 0.5260 - mae: 0.5593 - rmse: 0.6964 - smape: 1.0728 - val_ia: 0.2048 - val_loss: 0.3348 - val_mae: 0.4498 - val_rmse: 0.4679 - val_smape: 0.9701

Epoch 9/128

4586/4586 - 12s - 3ms/step - ia: 0.5694 - loss: 0.4980 - mae: 0.5420 - rmse: 0.6772 - smape: 1.0323 - val_ia: 0.2050 - val_loss: 0.3143 - val_mae: 0.4396 - val_rmse: 0.4577 - val_smape: 0.9375

Epoch 10/128

4586/4586 - 21s - 5ms/step - ia: 0.5853 - loss: 0.4669 - mae: 0.5239 - rmse: 0.6553 - smape: 0.9919 - val_ia: 0.2098 - val_loss: 0.2935 - val_mae: 0.4259 - val_rmse: 0.4444 - val_smape: 0.8986

Epoch 11/128

4586/4586 - 17s - 4ms/step - ia: 0.6045 - loss: 0.4428 - mae: 0.5080 - rmse: 0.6371 - smape: 0.9590 - val_ia: 0.2143 - val_loss: 0.2760 - val_mae: 0.4138 - val_rmse: 0.4326 - val_smape: 0.8644

Epoch 12/128

4586/4586 - 18s - 4ms/step - ia: 0.6197 - loss: 0.4234 - mae: 0.4933 - rmse: 0.6211 - smape: 0.9276 - val_ia: 0.2190 - val_loss: 0.2604 - val_mae: 0.4023 - val_rmse: 0.4213 - val_smape: 0.8339

Epoch 13/128

4586/4586 - 20s - 4ms/step - ia: 0.6372 - loss: 0.3972 - mae: 0.4755 - rmse: 0.6007 - smape: 0.9014 - val_ia: 0.2225 - val_loss: 0.2473 - val_mae: 0.3926 - val_rmse: 0.4116 - val_smape: 0.8089

Epoch 14/128

4586/4586 - 14s - 3ms/step - ia: 0.6514 - loss: 0.3772 - mae: 0.4599 - rmse: 0.5839 - smape: 0.8733 - val_ia: 0.2242 - val_loss: 0.2376 - val_mae: 0.3863 - val_rmse: 0.4052 - val_smape: 0.7925

Epoch 15/128

4586/4586 - 15s - 3ms/step - ia: 0.6642 - loss: 0.3600 - mae: 0.4459 - rmse: 0.5687 - smape: 0.8515 - val_ia: 0.2271 - val_loss: 0.2279 - val_mae: 0.3785 - val_rmse: 0.3974 - val_smape: 0.7776

Epoch 16/128

4586/4586 - 15s - 3ms/step - ia: 0.6762 - loss: 0.3395 - mae: 0.4328 - rmse: 0.5514 - smape: 0.8360 - val_ia: 0.2294 - val_loss: 0.2196 - val_mae: 0.3721 - val_rmse: 0.3908 - val_smape: 0.7665

Epoch 17/128

4586/4586 - 23s - 5ms/step - ia: 0.6800 - loss: 0.3394 - mae: 0.4290 - rmse: 0.5499 - smape: 0.8270 - val_ia: 0.2320 - val_loss: 0.2122 - val_mae: 0.3660 - val_rmse: 0.3845 - val_smape: 0.7569

Epoch 18/128

4586/4586 - 19s - 4ms/step - ia: 0.6871 - loss: 0.3245 - mae: 0.4182 - rmse: 0.5375 - smape: 0.8118 - val_ia: 0.2339 - val_loss: 0.2054 - val_mae: 0.3610 - val_rmse: 0.3791 - val_smape: 0.7491

Epoch 19/128

4586/4586 - 13s - 3ms/step - ia: 0.6904 - loss: 0.3220 - mae: 0.4150 - rmse: 0.5349 - smape: 0.8112 - val_ia: 0.2356 - val_loss: 0.1990 - val_mae: 0.3563 - val_rmse: 0.3740 - val_smape: 0.7429

Epoch 20/128

4586/4586 - 13s - 3ms/step - ia: 0.6993 - loss: 0.3088 - mae: 0.4047 - rmse: 0.5229 - smape: 0.7932 - val_ia: 0.2365 - val_loss: 0.1937 - val_mae: 0.3529 - val_rmse: 0.3702 - val_smape: 0.7386

Epoch 21/128

4586/4586 - 27s - 6ms/step - ia: 0.7036 - loss: 0.3036 - mae: 0.3987 - rmse: 0.5174 - smape: 0.7841 - val_ia: 0.2400 - val_loss: 0.1859 - val_mae: 0.3458 - val_rmse: 0.3627 - val_smape: 0.7296

Epoch 22/128

4586/4586 - 19s - 4ms/step - ia: 0.7091 - loss: 0.2946 - mae: 0.3907 - rmse: 0.5097 - smape: 0.7707 - val_ia: 0.2407 - val_loss: 0.1817 - val_mae: 0.3432 - val_rmse: 0.3597 - val_smape: 0.7272

Epoch 23/128

4586/4586 - 23s - 5ms/step - ia: 0.7137 - loss: 0.2895 - mae: 0.3858 - rmse: 0.5052 - smape: 0.7640 - val_ia: 0.2423 - val_loss: 0.1770 - val_mae: 0.3395 - val_rmse: 0.3556 - val_smape: 0.7236

Epoch 24/128

4586/4586 - 27s - 6ms/step - ia: 0.7182 - loss: 0.2827 - mae: 0.3799 - rmse: 0.4978 - smape: 0.7549 - val_ia: 0.2461 - val_loss: 0.1702 - val_mae: 0.3325 - val_rmse: 0.3483 - val_smape: 0.7140

Epoch 25/128

4586/4586 - 19s - 4ms/step - ia: 0.7251 - loss: 0.2709 - mae: 0.3719 - rmse: 0.4877 - smape: 0.7425 - val_ia: 0.2487 - val_loss: 0.1651 - val_mae: 0.3278 - val_rmse: 0.3433 - val_smape: 0.7082

Epoch 26/128

4586/4586 - 20s - 4ms/step - ia: 0.7243 - loss: 0.2768 - mae: 0.3733 - rmse: 0.4914 - smape: 0.7443 - val_ia: 0.2519 - val_loss: 0.1607 - val_mae: 0.3231 - val_rmse: 0.3384 - val_smape: 0.7025

Epoch 27/128

4586/4586 - 21s - 4ms/step - ia: 0.7289 - loss: 0.2665 - mae: 0.3654 - rmse: 0.4826 - smape: 0.7365 - val_ia: 0.2536 - val_loss: 0.1575 - val_mae: 0.3205 - val_rmse: 0.3355 - val_smape: 0.7000

Epoch 28/128

4586/4586 - 18s - 4ms/step - ia: 0.7320 - loss: 0.2643 - mae: 0.3618 - rmse: 0.4800 - smape: 0.7275 - val_ia: 0.2571 - val_loss: 0.1530 - val_mae: 0.3155 - val_rmse: 0.3303 - val_smape: 0.6929

Epoch 29/128

4586/4586 - 18s - 4ms/step - ia: 0.7357 - loss: 0.2595 - mae: 0.3570 - rmse: 0.4768 - smape: 0.7148 - val_ia: 0.2598 - val_loss: 0.1493 - val_mae: 0.3116 - val_rmse: 0.3262 - val_smape: 0.6877

Epoch 30/128

4586/4586 - 18s - 4ms/step - ia: 0.7418 - loss: 0.2513 - mae: 0.3503 - rmse: 0.4673 - smape: 0.7043 - val_ia: 0.2628 - val_loss: 0.1457 - val_mae: 0.3076 - val_rmse: 0.3220 - val_smape: 0.6819

Epoch 31/128

4586/4586 - 20s - 4ms/step - ia: 0.7447 - loss: 0.2497 - mae: 0.3471 - rmse: 0.4652 - smape: 0.7013 - val_ia: 0.2661 - val_loss: 0.1423 - val_mae: 0.3034 - val_rmse: 0.3177 - val_smape: 0.6754

Epoch 32/128

4586/4586 - 22s - 5ms/step - ia: 0.7466 - loss: 0.2445 - mae: 0.3438 - rmse: 0.4598 - smape: 0.6936 - val_ia: 0.2697 - val_loss: 0.1380 - val_mae: 0.2982 - val_rmse: 0.3124 - val_smape: 0.6668

Epoch 33/128

4586/4586 - 20s - 4ms/step - ia: 0.7497 - loss: 0.2444 - mae: 0.3419 - rmse: 0.4598 - smape: 0.6907 - val_ia: 0.2729 - val_loss: 0.1344 - val_mae: 0.2938 - val_rmse: 0.3079 - val_smape: 0.6591

Epoch 34/128

4586/4586 - 18s - 4ms/step - ia: 0.7503 - loss: 0.2434 - mae: 0.3404 - rmse: 0.4575 - smape: 0.6881 - val_ia: 0.2758 - val_loss: 0.1312 - val_mae: 0.2898 - val_rmse: 0.3038 - val_smape: 0.6524

Epoch 35/128

4586/4586 - 22s - 5ms/step - ia: 0.7549 - loss: 0.2341 - mae: 0.3335 - rmse: 0.4492 - smape: 0.6769 - val_ia: 0.2787 - val_loss: 0.1285 - val_mae: 0.2861 - val_rmse: 0.3001 - val_smape: 0.6456

Epoch 36/128

4586/4586 - 19s - 4ms/step - ia: 0.7576 - loss: 0.2318 - mae: 0.3308 - rmse: 0.4463 - smape: 0.6739 - val_ia: 0.2812 - val_loss: 0.1259 - val_mae: 0.2828 - val_rmse: 0.2968 - val_smape: 0.6392

Epoch 37/128

4586/4586 - 17s - 4ms/step - ia: 0.7591 - loss: 0.2312 - mae: 0.3290 - rmse: 0.4458 - smape: 0.6653 - val_ia: 0.2837 - val_loss: 0.1231 - val_mae: 0.2793 - val_rmse: 0.2933 - val_smape: 0.6320

Epoch 38/128

4586/4586 - 20s - 4ms/step - ia: 0.7626 - loss: 0.2258 - mae: 0.3249 - rmse: 0.4397 - smape: 0.6598 - val_ia: 0.2883 - val_loss: 0.1186 - val_mae: 0.2729 - val_rmse: 0.2869 - val_smape: 0.6202

Epoch 39/128

4586/4586 - 19s - 4ms/step - ia: 0.7660 - loss: 0.2196 - mae: 0.3209 - rmse: 0.4337 - smape: 0.6528 - val_ia: 0.2899 - val_loss: 0.1164 - val_mae: 0.2703 - val_rmse: 0.2843 - val_smape: 0.6143

Epoch 40/128

4586/4586 - 22s - 5ms/step - ia: 0.7648 - loss: 0.2217 - mae: 0.3216 - rmse: 0.4358 - smape: 0.6565 - val_ia: 0.2922 - val_loss: 0.1136 - val_mae: 0.2665 - val_rmse: 0.2806 - val_smape: 0.6069

Epoch 41/128

4586/4586 - 18s - 4ms/step - ia: 0.7673 - loss: 0.2157 - mae: 0.3181 - rmse: 0.4296 - smape: 0.6520 - val_ia: 0.2936 - val_loss: 0.1115 - val_mae: 0.2639 - val_rmse: 0.2779 - val_smape: 0.6012

Epoch 42/128

4586/4586 - 18s - 4ms/step - ia: 0.7652 - loss: 0.2191 - mae: 0.3202 - rmse: 0.4334 - smape: 0.6535 - val_ia: 0.2960 - val_loss: 0.1089 - val_mae: 0.2603 - val_rmse: 0.2744 - val_smape: 0.5935

Epoch 43/128

4586/4586 - 16s - 4ms/step - ia: 0.7692 - loss: 0.2137 - mae: 0.3152 - rmse: 0.4282 - smape: 0.6421 - val_ia: 0.2965 - val_loss: 0.1074 - val_mae: 0.2589 - val_rmse: 0.2730 - val_smape: 0.5893

Epoch 44/128

4586/4586 - 16s - 4ms/step - ia: 0.7722 - loss: 0.2087 - mae: 0.3116 - rmse: 0.4213 - smape: 0.6356 - val_ia: 0.2973 - val_loss: 0.1057 - val_mae: 0.2573 - val_rmse: 0.2712 - val_smape: 0.5843

Epoch 45/128

4586/4586 - 14s - 3ms/step - ia: 0.7712 - loss: 0.2105 - mae: 0.3131 - rmse: 0.4244 - smape: 0.6402 - val_ia: 0.2985 - val_loss: 0.1041 - val_mae: 0.2553 - val_rmse: 0.2692 - val_smape: 0.5791

Epoch 46/128

4586/4586 - 15s - 3ms/step - ia: 0.7743 - loss: 0.2053 - mae: 0.3091 - rmse: 0.4184 - smape: 0.6331 - val_ia: 0.3008 - val_loss: 0.1014 - val_mae: 0.2517 - val_rmse: 0.2656 - val_smape: 0.5718

Epoch 47/128

4586/4586 - 16s - 4ms/step - ia: 0.7754 - loss: 0.2033 - mae: 0.3075 - rmse: 0.4154 - smape: 0.6311 - val_ia: 0.3010 - val_loss: 0.1004 - val_mae: 0.2510 - val_rmse: 0.2649 - val_smape: 0.5685

Epoch 48/128

4586/4586 - 15s - 3ms/step - ia: 0.7764 - loss: 0.2015 - mae: 0.3062 - rmse: 0.4146 - smape: 0.6270 - val_ia: 0.3020 - val_loss: 0.0991 - val_mae: 0.2497 - val_rmse: 0.2635 - val_smape: 0.5638

Epoch 49/128

4586/4586 - 16s - 4ms/step - ia: 0.7785 - loss: 0.1972 - mae: 0.3029 - rmse: 0.4097 - smape: 0.6215 - val_ia: 0.3029 - val_loss: 0.0978 - val_mae: 0.2483 - val_rmse: 0.2622 - val_smape: 0.5590

Epoch 50/128

4586/4586 - 18s - 4ms/step - ia: 0.7815 - loss: 0.1952 - mae: 0.3010 - rmse: 0.4077 - smape: 0.6178 - val_ia: 0.3050 - val_loss: 0.0959 - val_mae: 0.2456 - val_rmse: 0.2595 - val_smape: 0.5524

Epoch 51/128

4586/4586 - 22s - 5ms/step - ia: 0.7801 - loss: 0.1954 - mae: 0.3021 - rmse: 0.4082 - smape: 0.6221 - val_ia: 0.3056 - val_loss: 0.0949 - val_mae: 0.2448 - val_rmse: 0.2586 - val_smape: 0.5488

Epoch 52/128

4586/4586 - 20s - 4ms/step - ia: 0.7807 - loss: 0.1928 - mae: 0.3008 - rmse: 0.4063 - smape: 0.6193 - val_ia: 0.3061 - val_loss: 0.0940 - val_mae: 0.2441 - val_rmse: 0.2579 - val_smape: 0.5453

Epoch 53/128

4586/4586 - 14s - 3ms/step - ia: 0.7826 - loss: 0.1931 - mae: 0.2986 - rmse: 0.4047 - smape: 0.6120 - val_ia: 0.3074 - val_loss: 0.0927 - val_mae: 0.2424 - val_rmse: 0.2562 - val_smape: 0.5399

Epoch 54/128

4586/4586 - 23s - 5ms/step - ia: 0.7855 - loss: 0.1897 - mae: 0.2952 - rmse: 0.4011 - smape: 0.6053 - val_ia: 0.3097 - val_loss: 0.0908 - val_mae: 0.2397 - val_rmse: 0.2535 - val_smape: 0.5331

Epoch 55/128

4586/4586 - 22s - 5ms/step - ia: 0.7851 - loss: 0.1891 - mae: 0.2952 - rmse: 0.4003 - smape: 0.6071 - val_ia: 0.3109 - val_loss: 0.0897 - val_mae: 0.2383 - val_rmse: 0.2522 - val_smape: 0.5288

Epoch 56/128

4586/4586 - 22s - 5ms/step - ia: 0.7873 - loss: 0.1867 - mae: 0.2934 - rmse: 0.3977 - smape: 0.6026 - val_ia: 0.3137 - val_loss: 0.0875 - val_mae: 0.2348 - val_rmse: 0.2488 - val_smape: 0.5218

Epoch 57/128

4586/4586 - 16s - 3ms/step - ia: 0.7858 - loss: 0.1877 - mae: 0.2956 - rmse: 0.3997 - smape: 0.6027 - val_ia: 0.3150 - val_loss: 0.0863 - val_mae: 0.2334 - val_rmse: 0.2474 - val_smape: 0.5176

Epoch 58/128

4586/4586 - 19s - 4ms/step - ia: 0.7870 - loss: 0.1855 - mae: 0.2937 - rmse: 0.3970 - smape: 0.6006 - val_ia: 0.3160 - val_loss: 0.0856 - val_mae: 0.2326 - val_rmse: 0.2466 - val_smape: 0.5136

Epoch 59/128

4586/4586 - 17s - 4ms/step - ia: 0.7909 - loss: 0.1789 - mae: 0.2889 - rmse: 0.3903 - smape: 0.5954 - val_ia: 0.3170 - val_loss: 0.0847 - val_mae: 0.2315 - val_rmse: 0.2456 - val_smape: 0.5105

Epoch 60/128

4586/4586 - 20s - 4ms/step - ia: 0.7908 - loss: 0.1791 - mae: 0.2890 - rmse: 0.3899 - smape: 0.5944 - val_ia: 0.3178 - val_loss: 0.0843 - val_mae: 0.2313 - val_rmse: 0.2453 - val_smape: 0.5079

Epoch 61/128

4586/4586 - 15s - 3ms/step - ia: 0.7915 - loss: 0.1779 - mae: 0.2879 - rmse: 0.3887 - smape: 0.5909 - val_ia: 0.3202 - val_loss: 0.0825 - val_mae: 0.2284 - val_rmse: 0.2426 - val_smape: 0.5024

Epoch 62/128

4586/4586 - 13s - 3ms/step - ia: 0.7925 - loss: 0.1765 - mae: 0.2867 - rmse: 0.3881 - smape: 0.5890 - val_ia: 0.3219 - val_loss: 0.0815 - val_mae: 0.2268 - val_rmse: 0.2410 - val_smape: 0.4982

Epoch 63/128

4586/4586 - 10s - 2ms/step - ia: 0.7928 - loss: 0.1764 - mae: 0.2859 - rmse: 0.3869 - smape: 0.5872 - val_ia: 0.3219 - val_loss: 0.0816 - val_mae: 0.2274 - val_rmse: 0.2415 - val_smape: 0.4971

Epoch 64/128

4586/4586 - 10s - 2ms/step - ia: 0.7949 - loss: 0.1754 - mae: 0.2851 - rmse: 0.3856 - smape: 0.5817 - val_ia: 0.3241 - val_loss: 0.0799 - val_mae: 0.2248 - val_rmse: 0.2390 - val_smape: 0.4920

Epoch 65/128

4586/4586 - 10s - 2ms/step - ia: 0.7934 - loss: 0.1751 - mae: 0.2849 - rmse: 0.3853 - smape: 0.5833 - val_ia: 0.3239 - val_loss: 0.0801 - val_mae: 0.2254 - val_rmse: 0.2396 - val_smape: 0.4912

Epoch 66/128

4586/4586 - 14s - 3ms/step - ia: 0.7972 - loss: 0.1682 - mae: 0.2814 - rmse: 0.3789 - smape: 0.5793 - val_ia: 0.3265 - val_loss: 0.0782 - val_mae: 0.2224 - val_rmse: 0.2367 - val_smape: 0.4857

Epoch 67/128

4586/4586 - 17s - 4ms/step - ia: 0.7955 - loss: 0.1716 - mae: 0.2834 - rmse: 0.3822 - smape: 0.5794 - val_ia: 0.3266 - val_loss: 0.0781 - val_mae: 0.2226 - val_rmse: 0.2368 - val_smape: 0.4847

Epoch 68/128

4586/4586 - 16s - 3ms/step - ia: 0.7984 - loss: 0.1676 - mae: 0.2792 - rmse: 0.3770 - smape: 0.5751 - val_ia: 0.3285 - val_loss: 0.0769 - val_mae: 0.2206 - val_rmse: 0.2348 - val_smape: 0.4808

Epoch 69/128

4586/4586 - 17s - 4ms/step - ia: 0.7998 - loss: 0.1667 - mae: 0.2781 - rmse: 0.3759 - smape: 0.5713 - val_ia: 0.3306 - val_loss: 0.0755 - val_mae: 0.2182 - val_rmse: 0.2325 - val_smape: 0.4762

Epoch 70/128

4586/4586 - 15s - 3ms/step - ia: 0.8015 - loss: 0.1634 - mae: 0.2763 - rmse: 0.3732 - smape: 0.5665 - val_ia: 0.3287 - val_loss: 0.0766 - val_mae: 0.2206 - val_rmse: 0.2349 - val_smape: 0.4787

Epoch 71/128

4586/4586 - 20s - 4ms/step - ia: 0.8035 - loss: 0.1614 - mae: 0.2737 - rmse: 0.3703 - smape: 0.5634 - val_ia: 0.3307 - val_loss: 0.0753 - val_mae: 0.2185 - val_rmse: 0.2329 - val_smape: 0.4743

Epoch 72/128

4586/4586 - 16s - 3ms/step - ia: 0.8007 - loss: 0.1638 - mae: 0.2766 - rmse: 0.3729 - smape: 0.5671 - val_ia: 0.3334 - val_loss: 0.0735 - val_mae: 0.2153 - val_rmse: 0.2297 - val_smape: 0.4696

Epoch 73/128

4586/4586 - 15s - 3ms/step - ia: 0.8008 - loss: 0.1640 - mae: 0.2765 - rmse: 0.3734 - smape: 0.5689 - val_ia: 0.3327 - val_loss: 0.0740 - val_mae: 0.2166 - val_rmse: 0.2309 - val_smape: 0.4697

Epoch 74/128

4586/4586 - 15s - 3ms/step - ia: 0.8032 - loss: 0.1598 - mae: 0.2731 - rmse: 0.3680 - smape: 0.5588 - val_ia: 0.3341 - val_loss: 0.0733 - val_mae: 0.2153 - val_rmse: 0.2297 - val_smape: 0.4671

Epoch 75/128

4586/4586 - 16s - 4ms/step - ia: 0.8033 - loss: 0.1588 - mae: 0.2725 - rmse: 0.3673 - smape: 0.5572 - val_ia: 0.3352 - val_loss: 0.0726 - val_mae: 0.2143 - val_rmse: 0.2287 - val_smape: 0.4645

Epoch 76/128

4586/4586 - 19s - 4ms/step - ia: 0.8055 - loss: 0.1583 - mae: 0.2714 - rmse: 0.3663 - smape: 0.5555 - val_ia: 0.3364 - val_loss: 0.0719 - val_mae: 0.2132 - val_rmse: 0.2277 - val_smape: 0.4622

Epoch 77/128

4586/4586 - 16s - 3ms/step - ia: 0.8059 - loss: 0.1574 - mae: 0.2707 - rmse: 0.3656 - smape: 0.5564 - val_ia: 0.3364 - val_loss: 0.0719 - val_mae: 0.2134 - val_rmse: 0.2278 - val_smape: 0.4619

Epoch 78/128

4586/4586 - 20s - 4ms/step - ia: 0.8057 - loss: 0.1557 - mae: 0.2701 - rmse: 0.3633 - smape: 0.5543 - val_ia: 0.3382 - val_loss: 0.0710 - val_mae: 0.2117 - val_rmse: 0.2261 - val_smape: 0.4582

Epoch 79/128

4586/4586 - 16s - 4ms/step - ia: 0.8066 - loss: 0.1559 - mae: 0.2688 - rmse: 0.3632 - smape: 0.5507 - val_ia: 0.3385 - val_loss: 0.0710 - val_mae: 0.2118 - val_rmse: 0.2263 - val_smape: 0.4577

Epoch 80/128

4586/4586 - 12s - 3ms/step - ia: 0.8075 - loss: 0.1539 - mae: 0.2682 - rmse: 0.3617 - smape: 0.5478 - val_ia: 0.3419 - val_loss: 0.0688 - val_mae: 0.2080 - val_rmse: 0.2226 - val_smape: 0.4518

Epoch 81/128

4586/4586 - 20s - 4ms/step - ia: 0.8107 - loss: 0.1506 - mae: 0.2644 - rmse: 0.3558 - smape: 0.5431 - val_ia: 0.3415 - val_loss: 0.0692 - val_mae: 0.2089 - val_rmse: 0.2234 - val_smape: 0.4521

Epoch 82/128

4586/4586 - 14s - 3ms/step - ia: 0.8112 - loss: 0.1490 - mae: 0.2636 - rmse: 0.3550 - smape: 0.5407 - val_ia: 0.3431 - val_loss: 0.0681 - val_mae: 0.2070 - val_rmse: 0.2216 - val_smape: 0.4488

Epoch 83/128

4586/4586 - 17s - 4ms/step - ia: 0.8105 - loss: 0.1506 - mae: 0.2640 - rmse: 0.3556 - smape: 0.5419 - val_ia: 0.3435 - val_loss: 0.0681 - val_mae: 0.2072 - val_rmse: 0.2217 - val_smape: 0.4482

Epoch 84/128

4586/4586 - 14s - 3ms/step - ia: 0.8125 - loss: 0.1475 - mae: 0.2622 - rmse: 0.3532 - smape: 0.5392 - val_ia: 0.3449 - val_loss: 0.0672 - val_mae: 0.2055 - val_rmse: 0.2201 - val_smape: 0.4457

Epoch 85/128

4586/4586 - 16s - 4ms/step - ia: 0.8134 - loss: 0.1463 - mae: 0.2609 - rmse: 0.3511 - smape: 0.5378 - val_ia: 0.3463 - val_loss: 0.0664 - val_mae: 0.2043 - val_rmse: 0.2189 - val_smape: 0.4435

Epoch 86/128

4586/4586 - 21s - 5ms/step - ia: 0.8125 - loss: 0.1457 - mae: 0.2615 - rmse: 0.3520 - smape: 0.5333 - val_ia: 0.3465 - val_loss: 0.0664 - val_mae: 0.2044 - val_rmse: 0.2189 - val_smape: 0.4424

Epoch 87/128

4586/4586 - 21s - 5ms/step - ia: 0.8132 - loss: 0.1468 - mae: 0.2614 - rmse: 0.3523 - smape: 0.5339 - val_ia: 0.3471 - val_loss: 0.0659 - val_mae: 0.2036 - val_rmse: 0.2181 - val_smape: 0.4411

Epoch 88/128

4586/4586 - 15s - 3ms/step - ia: 0.8136 - loss: 0.1464 - mae: 0.2610 - rmse: 0.3517 - smape: 0.5341 - val_ia: 0.3484 - val_loss: 0.0651 - val_mae: 0.2023 - val_rmse: 0.2168 - val_smape: 0.4392

Epoch 89/128

4586/4586 - 14s - 3ms/step - ia: 0.8155 - loss: 0.1427 - mae: 0.2580 - rmse: 0.3476 - smape: 0.5296 - val_ia: 0.3480 - val_loss: 0.0655 - val_mae: 0.2031 - val_rmse: 0.2176 - val_smape: 0.4396

Epoch 90/128

4586/4586 - 14s - 3ms/step - ia: 0.8184 - loss: 0.1391 - mae: 0.2550 - rmse: 0.3432 - smape: 0.5252 - val_ia: 0.3495 - val_loss: 0.0648 - val_mae: 0.2019 - val_rmse: 0.2164 - val_smape: 0.4371

Epoch 91/128

4586/4586 - 16s - 3ms/step - ia: 0.8165 - loss: 0.1425 - mae: 0.2573 - rmse: 0.3469 - smape: 0.5280 - val_ia: 0.3498 - val_loss: 0.0647 - val_mae: 0.2018 - val_rmse: 0.2162 - val_smape: 0.4363

Epoch 92/128

4586/4586 - 14s - 3ms/step - ia: 0.8159 - loss: 0.1417 - mae: 0.2562 - rmse: 0.3463 - smape: 0.5262 - val_ia: 0.3505 - val_loss: 0.0639 - val_mae: 0.2006 - val_rmse: 0.2151 - val_smape: 0.4350

Epoch 93/128

4586/4586 - 14s - 3ms/step - ia: 0.8190 - loss: 0.1404 - mae: 0.2537 - rmse: 0.3429 - smape: 0.5223 - val_ia: 0.3498 - val_loss: 0.0645 - val_mae: 0.2019 - val_rmse: 0.2163 - val_smape: 0.4358

Epoch 94/128

4586/4586 - 15s - 3ms/step - ia: 0.8210 - loss: 0.1368 - mae: 0.2520 - rmse: 0.3401 - smape: 0.5187 - val_ia: 0.3505 - val_loss: 0.0640 - val_mae: 0.2012 - val_rmse: 0.2156 - val_smape: 0.4348

Epoch 95/128

4586/4586 - 10s - 2ms/step - ia: 0.8197 - loss: 0.1374 - mae: 0.2523 - rmse: 0.3409 - smape: 0.5185 - val_ia: 0.3515 - val_loss: 0.0636 - val_mae: 0.2003 - val_rmse: 0.2147 - val_smape: 0.4333

Epoch 96/128

4586/4586 - 9s - 2ms/step - ia: 0.8189 - loss: 0.1398 - mae: 0.2540 - rmse: 0.3427 - smape: 0.5193 - val_ia: 0.3525 - val_loss: 0.0632 - val_mae: 0.1998 - val_rmse: 0.2141 - val_smape: 0.4315

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 8s - 7ms/step - ia: 0.2843 - loss: 6.7371 - mae: 1.9379 - rmse: 2.5480 - smape: 1.4422 - val_ia: 0.2603 - val_loss: 1.3006 - val_mae: 0.9657 - val_rmse: 1.0396 - val_smape: 1.2021

Epoch 2/128

1147/1147 - 3s - 3ms/step - ia: 0.3582 - loss: 4.2029 - mae: 1.5418 - rmse: 2.0195 - smape: 1.3423 - val_ia: 0.3542 - val_loss: 0.5613 - val_mae: 0.6176 - val_rmse: 0.6743 - val_smape: 1.0440

Epoch 3/128

1147/1147 - 3s - 2ms/step - ia: 0.4091 - loss: 2.9412 - mae: 1.2933 - rmse: 1.6904 - smape: 1.2722 - val_ia: 0.4576 - val_loss: 0.2464 - val_mae: 0.3977 - val_rmse: 0.4447 - val_smape: 0.8669

Epoch 4/128

1147/1147 - 6s - 5ms/step - ia: 0.4557 - loss: 2.1287 - mae: 1.1038 - rmse: 1.4404 - smape: 1.2068 - val_ia: 0.5351 - val_loss: 0.1428 - val_mae: 0.2908 - val_rmse: 0.3375 - val_smape: 0.7140

Epoch 5/128

1147/1147 - 3s - 3ms/step - ia: 0.4905 - loss: 1.6754 - mae: 0.9822 - rmse: 1.2784 - smape: 1.1576 - val_ia: 0.5827 - val_loss: 0.1017 - val_mae: 0.2446 - val_rmse: 0.2908 - val_smape: 0.6022

Epoch 6/128

1147/1147 - 3s - 3ms/step - ia: 0.5269 - loss: 1.3125 - mae: 0.8690 - rmse: 1.1308 - smape: 1.1033 - val_ia: 0.5897 - val_loss: 0.0906 - val_mae: 0.2359 - val_rmse: 0.2785 - val_smape: 0.5629

Epoch 7/128

1147/1147 - 3s - 3ms/step - ia: 0.5551 - loss: 1.0721 - mae: 0.7892 - rmse: 1.0222 - smape: 1.0651 - val_ia: 0.5932 - val_loss: 0.0865 - val_mae: 0.2352 - val_rmse: 0.2746 - val_smape: 0.5604

Epoch 8/128

1147/1147 - 5s - 4ms/step - ia: 0.5828 - loss: 0.8983 - mae: 0.7223 - rmse: 0.9361 - smape: 1.0240 - val_ia: 0.6059 - val_loss: 0.0791 - val_mae: 0.2265 - val_rmse: 0.2631 - val_smape: 0.5435

Epoch 9/128

1147/1147 - 6s - 5ms/step - ia: 0.6078 - loss: 0.7734 - mae: 0.6670 - rmse: 0.8675 - smape: 0.9842 - val_ia: 0.6161 - val_loss: 0.0727 - val_mae: 0.2176 - val_rmse: 0.2527 - val_smape: 0.5189

Epoch 10/128

1147/1147 - 4s - 3ms/step - ia: 0.6309 - loss: 0.6662 - mae: 0.6197 - rmse: 0.8061 - smape: 0.9458 - val_ia: 0.6193 - val_loss: 0.0710 - val_mae: 0.2163 - val_rmse: 0.2496 - val_smape: 0.5069

Epoch 11/128

1147/1147 - 5s - 4ms/step - ia: 0.6483 - loss: 0.5872 - mae: 0.5808 - rmse: 0.7560 - smape: 0.9117 - val_ia: 0.6319 - val_loss: 0.0651 - val_mae: 0.2076 - val_rmse: 0.2391 - val_smape: 0.4924

Epoch 12/128

1147/1147 - 3s - 3ms/step - ia: 0.6637 - loss: 0.5287 - mae: 0.5505 - rmse: 0.7177 - smape: 0.8841 - val_ia: 0.6525 - val_loss: 0.0556 - val_mae: 0.1905 - val_rmse: 0.2214 - val_smape: 0.4589

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.6815 - loss: 0.4744 - mae: 0.5207 - rmse: 0.6797 - smape: 0.8558 - val_ia: 0.6520 - val_loss: 0.0555 - val_mae: 0.1915 - val_rmse: 0.2212 - val_smape: 0.4556

Epoch 14/128

1147/1147 - 3s - 2ms/step - ia: 0.6915 - loss: 0.4382 - mae: 0.4989 - rmse: 0.6521 - smape: 0.8340 - val_ia: 0.6684 - val_loss: 0.0480 - val_mae: 0.1776 - val_rmse: 0.2065 - val_smape: 0.4346

Epoch 15/128

1147/1147 - 6s - 5ms/step - ia: 0.7065 - loss: 0.3973 - mae: 0.4749 - rmse: 0.6214 - smape: 0.8109 - val_ia: 0.6696 - val_loss: 0.0476 - val_mae: 0.1761 - val_rmse: 0.2052 - val_smape: 0.4172

Epoch 16/128

1147/1147 - 3s - 3ms/step - ia: 0.7145 - loss: 0.3698 - mae: 0.4579 - rmse: 0.5996 - smape: 0.7931 - val_ia: 0.6769 - val_loss: 0.0444 - val_mae: 0.1701 - val_rmse: 0.1986 - val_smape: 0.4067

Epoch 17/128

1147/1147 - 4s - 4ms/step - ia: 0.7266 - loss: 0.3386 - mae: 0.4377 - rmse: 0.5736 - smape: 0.7709 - val_ia: 0.6880 - val_loss: 0.0398 - val_mae: 0.1614 - val_rmse: 0.1888 - val_smape: 0.4003

Epoch 18/128

1147/1147 - 2s - 2ms/step - ia: 0.7345 - loss: 0.3203 - mae: 0.4251 - rmse: 0.5582 - smape: 0.7533 - val_ia: 0.6806 - val_loss: 0.0425 - val_mae: 0.1674 - val_rmse: 0.1945 - val_smape: 0.4060

Epoch 19/128

1147/1147 - 3s - 3ms/step - ia: 0.7409 - loss: 0.2993 - mae: 0.4118 - rmse: 0.5398 - smape: 0.7355 - val_ia: 0.7016 - val_loss: 0.0353 - val_mae: 0.1510 - val_rmse: 0.1781 - val_smape: 0.3739

Epoch 20/128

1147/1147 - 5s - 5ms/step - ia: 0.7483 - loss: 0.2845 - mae: 0.4010 - rmse: 0.5260 - smape: 0.7240 - val_ia: 0.7030 - val_loss: 0.0349 - val_mae: 0.1498 - val_rmse: 0.1766 - val_smape: 0.3642

Epoch 21/128

1147/1147 - 3s - 3ms/step - ia: 0.7564 - loss: 0.2700 - mae: 0.3870 - rmse: 0.5118 - smape: 0.7046 - val_ia: 0.7081 - val_loss: 0.0332 - val_mae: 0.1467 - val_rmse: 0.1728 - val_smape: 0.3706

Epoch 22/128

1147/1147 - 3s - 3ms/step - ia: 0.7620 - loss: 0.2538 - mae: 0.3773 - rmse: 0.4966 - smape: 0.6932 - val_ia: 0.7051 - val_loss: 0.0342 - val_mae: 0.1490 - val_rmse: 0.1747 - val_smape: 0.3665

Epoch 23/128

1147/1147 - 3s - 2ms/step - ia: 0.7682 - loss: 0.2410 - mae: 0.3677 - rmse: 0.4842 - smape: 0.6800 - val_ia: 0.7119 - val_loss: 0.0320 - val_mae: 0.1440 - val_rmse: 0.1695 - val_smape: 0.3593

Epoch 24/128

1147/1147 - 3s - 3ms/step - ia: 0.7747 - loss: 0.2286 - mae: 0.3567 - rmse: 0.4710 - smape: 0.6638 - val_ia: 0.7121 - val_loss: 0.0320 - val_mae: 0.1438 - val_rmse: 0.1692 - val_smape: 0.3523

Epoch 25/128

1147/1147 - 5s - 4ms/step - ia: 0.7788 - loss: 0.2198 - mae: 0.3493 - rmse: 0.4621 - smape: 0.6540 - val_ia: 0.7234 - val_loss: 0.0289 - val_mae: 0.1358 - val_rmse: 0.1609 - val_smape: 0.3370

Epoch 26/128

1147/1147 - 3s - 3ms/step - ia: 0.7847 - loss: 0.2097 - mae: 0.3411 - rmse: 0.4514 - smape: 0.6385 - val_ia: 0.7251 - val_loss: 0.0283 - val_mae: 0.1346 - val_rmse: 0.1593 - val_smape: 0.3348

Epoch 27/128

1147/1147 - 3s - 2ms/step - ia: 0.7889 - loss: 0.2000 - mae: 0.3330 - rmse: 0.4407 - smape: 0.6287 - val_ia: 0.7299 - val_loss: 0.0268 - val_mae: 0.1312 - val_rmse: 0.1555 - val_smape: 0.3301

Epoch 28/128

1147/1147 - 3s - 2ms/step - ia: 0.7940 - loss: 0.1916 - mae: 0.3252 - rmse: 0.4315 - smape: 0.6201 - val_ia: 0.7309 - val_loss: 0.0267 - val_mae: 0.1307 - val_rmse: 0.1549 - val_smape: 0.3276

Epoch 29/128

1147/1147 - 3s - 2ms/step - ia: 0.7952 - loss: 0.1896 - mae: 0.3232 - rmse: 0.4288 - smape: 0.6168 - val_ia: 0.7302 - val_loss: 0.0267 - val_mae: 0.1311 - val_rmse: 0.1548 - val_smape: 0.3294

Epoch 30/128

1147/1147 - 3s - 2ms/step - ia: 0.7999 - loss: 0.1822 - mae: 0.3158 - rmse: 0.4204 - smape: 0.6005 - val_ia: 0.7443 - val_loss: 0.0235 - val_mae: 0.1219 - val_rmse: 0.1457 - val_smape: 0.3115

Epoch 31/128

1147/1147 - 3s - 2ms/step - ia: 0.8044 - loss: 0.1728 - mae: 0.3090 - rmse: 0.4092 - smape: 0.5923 - val_ia: 0.7411 - val_loss: 0.0243 - val_mae: 0.1237 - val_rmse: 0.1475 - val_smape: 0.3078

Epoch 32/128

1147/1147 - 3s - 3ms/step - ia: 0.8081 - loss: 0.1666 - mae: 0.3025 - rmse: 0.4026 - smape: 0.5828 - val_ia: 0.7467 - val_loss: 0.0228 - val_mae: 0.1204 - val_rmse: 0.1435 - val_smape: 0.3109

Epoch 33/128

1147/1147 - 3s - 3ms/step - ia: 0.8109 - loss: 0.1629 - mae: 0.2979 - rmse: 0.3974 - smape: 0.5742 - val_ia: 0.7507 - val_loss: 0.0221 - val_mae: 0.1180 - val_rmse: 0.1412 - val_smape: 0.3035

Epoch 34/128

1147/1147 - 3s - 3ms/step - ia: 0.8139 - loss: 0.1572 - mae: 0.2933 - rmse: 0.3905 - smape: 0.5682 - val_ia: 0.7514 - val_loss: 0.0218 - val_mae: 0.1174 - val_rmse: 0.1402 - val_smape: 0.3016

Epoch 35/128

1147/1147 - 6s - 5ms/step - ia: 0.8182 - loss: 0.1510 - mae: 0.2869 - rmse: 0.3829 - smape: 0.5580 - val_ia: 0.7535 - val_loss: 0.0214 - val_mae: 0.1162 - val_rmse: 0.1388 - val_smape: 0.2998

Epoch 36/128

1147/1147 - 5s - 4ms/step - ia: 0.8197 - loss: 0.1474 - mae: 0.2841 - rmse: 0.3787 - smape: 0.5532 - val_ia: 0.7611 - val_loss: 0.0199 - val_mae: 0.1118 - val_rmse: 0.1341 - val_smape: 0.2913

Epoch 37/128

1147/1147 - 5s - 5ms/step - ia: 0.8226 - loss: 0.1436 - mae: 0.2798 - rmse: 0.3733 - smape: 0.5449 - val_ia: 0.7492 - val_loss: 0.0223 - val_mae: 0.1193 - val_rmse: 0.1413 - val_smape: 0.3035

Epoch 38/128

1147/1147 - 3s - 2ms/step - ia: 0.8254 - loss: 0.1386 - mae: 0.2749 - rmse: 0.3670 - smape: 0.5366 - val_ia: 0.7585 - val_loss: 0.0204 - val_mae: 0.1133 - val_rmse: 0.1355 - val_smape: 0.2929

Epoch 39/128

1147/1147 - 3s - 3ms/step - ia: 0.8291 - loss: 0.1345 - mae: 0.2698 - rmse: 0.3615 - smape: 0.5251 - val_ia: 0.7609 - val_loss: 0.0199 - val_mae: 0.1120 - val_rmse: 0.1338 - val_smape: 0.2947

Epoch 40/128

1147/1147 - 5s - 5ms/step - ia: 0.8297 - loss: 0.1325 - mae: 0.2681 - rmse: 0.3584 - smape: 0.5255 - val_ia: 0.7591 - val_loss: 0.0201 - val_mae: 0.1129 - val_rmse: 0.1345 - val_smape: 0.2930

Epoch 41/128

1147/1147 - 4s - 3ms/step - ia: 0.8332 - loss: 0.1275 - mae: 0.2629 - rmse: 0.3515 - smape: 0.5183 - val_ia: 0.7717 - val_loss: 0.0178 - val_mae: 0.1052 - val_rmse: 0.1269 - val_smape: 0.2778

Epoch 42/128

1147/1147 - 5s - 4ms/step - ia: 0.8360 - loss: 0.1224 - mae: 0.2583 - rmse: 0.3447 - smape: 0.5108 - val_ia: 0.7707 - val_loss: 0.0180 - val_mae: 0.1058 - val_rmse: 0.1273 - val_smape: 0.2799

Epoch 43/128

1147/1147 - 3s - 3ms/step - ia: 0.8376 - loss: 0.1221 - mae: 0.2564 - rmse: 0.3440 - smape: 0.5040 - val_ia: 0.7712 - val_loss: 0.0179 - val_mae: 0.1053 - val_rmse: 0.1268 - val_smape: 0.2712

Epoch 44/128

1147/1147 - 5s - 5ms/step - ia: 0.8405 - loss: 0.1166 - mae: 0.2511 - rmse: 0.3362 - smape: 0.5010 - val_ia: 0.7724 - val_loss: 0.0175 - val_mae: 0.1043 - val_rmse: 0.1255 - val_smape: 0.2707

Epoch 45/128

1147/1147 - 3s - 3ms/step - ia: 0.8417 - loss: 0.1152 - mae: 0.2499 - rmse: 0.3343 - smape: 0.4948 - val_ia: 0.7770 - val_loss: 0.0168 - val_mae: 0.1020 - val_rmse: 0.1232 - val_smape: 0.2701

Epoch 46/128

1147/1147 - 3s - 3ms/step - ia: 0.8436 - loss: 0.1115 - mae: 0.2462 - rmse: 0.3288 - smape: 0.4911 - val_ia: 0.7732 - val_loss: 0.0174 - val_mae: 0.1039 - val_rmse: 0.1250 - val_smape: 0.2707

Epoch 47/128

1147/1147 - 5s - 4ms/step - ia: 0.8456 - loss: 0.1103 - mae: 0.2440 - rmse: 0.3272 - smape: 0.4815 - val_ia: 0.7724 - val_loss: 0.0177 - val_mae: 0.1045 - val_rmse: 0.1256 - val_smape: 0.2667

Epoch 48/128

1147/1147 - 3s - 3ms/step - ia: 0.8472 - loss: 0.1070 - mae: 0.2409 - rmse: 0.3223 - smape: 0.4772 - val_ia: 0.7776 - val_loss: 0.0166 - val_mae: 0.1012 - val_rmse: 0.1221 - val_smape: 0.2631

Epoch 49/128

1147/1147 - 6s - 5ms/step - ia: 0.8502 - loss: 0.1039 - mae: 0.2364 - rmse: 0.3171 - smape: 0.4719 - val_ia: 0.7787 - val_loss: 0.0165 - val_mae: 0.1007 - val_rmse: 0.1215 - val_smape: 0.2620

Epoch 50/128

1147/1147 - 3s - 2ms/step - ia: 0.8505 - loss: 0.1028 - mae: 0.2356 - rmse: 0.3157 - smape: 0.4665 - val_ia: 0.7810 - val_loss: 0.0161 - val_mae: 0.0996 - val_rmse: 0.1202 - val_smape: 0.2639

Epoch 51/128

1147/1147 - 6s - 5ms/step - ia: 0.8522 - loss: 0.1007 - mae: 0.2332 - rmse: 0.3127 - smape: 0.4642 - val_ia: 0.7784 - val_loss: 0.0163 - val_mae: 0.1005 - val_rmse: 0.1211 - val_smape: 0.2612

Epoch 52/128

1147/1147 - 3s - 3ms/step - ia: 0.8531 - loss: 0.1003 - mae: 0.2315 - rmse: 0.3120 - smape: 0.4597 - val_ia: 0.7816 - val_loss: 0.0159 - val_mae: 0.0988 - val_rmse: 0.1193 - val_smape: 0.2578

Epoch 53/128

1147/1147 - 5s - 5ms/step - ia: 0.8558 - loss: 0.0961 - mae: 0.2275 - rmse: 0.3053 - smape: 0.4545 - val_ia: 0.7838 - val_loss: 0.0153 - val_mae: 0.0976 - val_rmse: 0.1175 - val_smape: 0.2599

Epoch 54/128

1147/1147 - 5s - 4ms/step - ia: 0.8566 - loss: 0.0961 - mae: 0.2268 - rmse: 0.3054 - smape: 0.4487 - val_ia: 0.7799 - val_loss: 0.0160 - val_mae: 0.0999 - val_rmse: 0.1198 - val_smape: 0.2608

Epoch 55/128

1147/1147 - 6s - 5ms/step - ia: 0.8579 - loss: 0.0941 - mae: 0.2240 - rmse: 0.3021 - smape: 0.4460 - val_ia: 0.7975 - val_loss: 0.0134 - val_mae: 0.0900 - val_rmse: 0.1101 - val_smape: 0.2464

Epoch 56/128

1147/1147 - 3s - 3ms/step - ia: 0.8597 - loss: 0.0910 - mae: 0.2216 - rmse: 0.2972 - smape: 0.4397 - val_ia: 0.7951 - val_loss: 0.0139 - val_mae: 0.0913 - val_rmse: 0.1115 - val_smape: 0.2424

Epoch 57/128

1147/1147 - 6s - 5ms/step - ia: 0.8603 - loss: 0.0904 - mae: 0.2202 - rmse: 0.2961 - smape: 0.4399 - val_ia: 0.7999 - val_loss: 0.0132 - val_mae: 0.0886 - val_rmse: 0.1087 - val_smape: 0.2385

Epoch 58/128

1147/1147 - 3s - 3ms/step - ia: 0.8622 - loss: 0.0887 - mae: 0.2180 - rmse: 0.2933 - smape: 0.4348 - val_ia: 0.7982 - val_loss: 0.0133 - val_mae: 0.0892 - val_rmse: 0.1091 - val_smape: 0.2407

Epoch 59/128

1147/1147 - 6s - 5ms/step - ia: 0.8633 - loss: 0.0875 - mae: 0.2164 - rmse: 0.2914 - smape: 0.4308 - val_ia: 0.7893 - val_loss: 0.0145 - val_mae: 0.0943 - val_rmse: 0.1139 - val_smape: 0.2472

Epoch 60/128

1147/1147 - 5s - 4ms/step - ia: 0.8648 - loss: 0.0855 - mae: 0.2135 - rmse: 0.2879 - smape: 0.4245 - val_ia: 0.7935 - val_loss: 0.0138 - val_mae: 0.0923 - val_rmse: 0.1116 - val_smape: 0.2504

Epoch 61/128

1147/1147 - 5s - 5ms/step - ia: 0.8655 - loss: 0.0849 - mae: 0.2126 - rmse: 0.2868 - smape: 0.4253 - val_ia: 0.7896 - val_loss: 0.0144 - val_mae: 0.0942 - val_rmse: 0.1135 - val_smape: 0.2487

Epoch 62/128

1147/1147 - 3s - 3ms/step - ia: 0.8677 - loss: 0.0823 - mae: 0.2093 - rmse: 0.2825 - smape: 0.4188 - val_ia: 0.7991 - val_loss: 0.0130 - val_mae: 0.0890 - val_rmse: 0.1081 - val_smape: 0.2445

Epoch 63/128

1147/1147 - 3s - 3ms/step - ia: 0.8682 - loss: 0.0813 - mae: 0.2082 - rmse: 0.2809 - smape: 0.4170 - val_ia: 0.8053 - val_loss: 0.0122 - val_mae: 0.0858 - val_rmse: 0.1052 - val_smape: 0.2388

Epoch 64/128

1147/1147 - 5s - 4ms/step - ia: 0.8695 - loss: 0.0796 - mae: 0.2065 - rmse: 0.2778 - smape: 0.4128 - val_ia: 0.8022 - val_loss: 0.0126 - val_mae: 0.0868 - val_rmse: 0.1061 - val_smape: 0.2330

Epoch 65/128

1147/1147 - 3s - 3ms/step - ia: 0.8703 - loss: 0.0792 - mae: 0.2051 - rmse: 0.2773 - smape: 0.4099 - val_ia: 0.8045 - val_loss: 0.0123 - val_mae: 0.0860 - val_rmse: 0.1051 - val_smape: 0.2364

Epoch 66/128

1147/1147 - 3s - 3ms/step - ia: 0.8712 - loss: 0.0783 - mae: 0.2042 - rmse: 0.2755 - smape: 0.4046 - val_ia: 0.8034 - val_loss: 0.0126 - val_mae: 0.0863 - val_rmse: 0.1058 - val_smape: 0.2284

Epoch 67/128

1147/1147 - 3s - 3ms/step - ia: 0.8715 - loss: 0.0777 - mae: 0.2034 - rmse: 0.2744 - smape: 0.4053 - val_ia: 0.8064 - val_loss: 0.0120 - val_mae: 0.0847 - val_rmse: 0.1039 - val_smape: 0.2297

Epoch 68/128

1147/1147 - 5s - 5ms/step - ia: 0.8734 - loss: 0.0758 - mae: 0.2004 - rmse: 0.2709 - smape: 0.4025 - val_ia: 0.8052 - val_loss: 0.0122 - val_mae: 0.0852 - val_rmse: 0.1044 - val_smape: 0.2275

Epoch 69/128

1147/1147 - 5s - 5ms/step - ia: 0.8730 - loss: 0.0761 - mae: 0.2004 - rmse: 0.2715 - smape: 0.3970 - val_ia: 0.8129 - val_loss: 0.0113 - val_mae: 0.0816 - val_rmse: 0.1008 - val_smape: 0.2239

Epoch 70/128

1147/1147 - 5s - 4ms/step - ia: 0.8749 - loss: 0.0739 - mae: 0.1980 - rmse: 0.2676 - smape: 0.3961 - val_ia: 0.8092 - val_loss: 0.0116 - val_mae: 0.0832 - val_rmse: 0.1021 - val_smape: 0.2241

Epoch 71/128

1147/1147 - 5s - 5ms/step - ia: 0.8756 - loss: 0.0725 - mae: 0.1970 - rmse: 0.2650 - smape: 0.3971 - val_ia: 0.8140 - val_loss: 0.0111 - val_mae: 0.0811 - val_rmse: 0.1000 - val_smape: 0.2227

Epoch 72/128

1147/1147 - 6s - 5ms/step - ia: 0.8766 - loss: 0.0719 - mae: 0.1956 - rmse: 0.2642 - smape: 0.3905 - val_ia: 0.8113 - val_loss: 0.0116 - val_mae: 0.0827 - val_rmse: 0.1018 - val_smape: 0.2220

Epoch 73/128

1147/1147 - 3s - 3ms/step - ia: 0.8774 - loss: 0.0707 - mae: 0.1938 - rmse: 0.2617 - smape: 0.3881 - val_ia: 0.8094 - val_loss: 0.0115 - val_mae: 0.0827 - val_rmse: 0.1014 - val_smape: 0.2202

Epoch 74/128

1147/1147 - 3s - 3ms/step - ia: 0.8784 - loss: 0.0705 - mae: 0.1931 - rmse: 0.2615 - smape: 0.3855 - val_ia: 0.8090 - val_loss: 0.0116 - val_mae: 0.0830 - val_rmse: 0.1016 - val_smape: 0.2198

Epoch 75/128

1147/1147 - 5s - 4ms/step - ia: 0.8788 - loss: 0.0690 - mae: 0.1917 - rmse: 0.2585 - smape: 0.3836 - val_ia: 0.8120 - val_loss: 0.0113 - val_mae: 0.0822 - val_rmse: 0.1007 - val_smape: 0.2252

Epoch 76/128

1147/1147 - 5s - 5ms/step - ia: 0.8802 - loss: 0.0682 - mae: 0.1899 - rmse: 0.2568 - smape: 0.3789 - val_ia: 0.8193 - val_loss: 0.0105 - val_mae: 0.0782 - val_rmse: 0.0970 - val_smape: 0.2154

Epoch 77/128

1147/1147 - 5s - 4ms/step - ia: 0.8802 - loss: 0.0686 - mae: 0.1900 - rmse: 0.2574 - smape: 0.3803 - val_ia: 0.8072 - val_loss: 0.0120 - val_mae: 0.0843 - val_rmse: 0.1030 - val_smape: 0.2215

Epoch 78/128

1147/1147 - 5s - 4ms/step - ia: 0.8804 - loss: 0.0678 - mae: 0.1891 - rmse: 0.2561 - smape: 0.3770 - val_ia: 0.8102 - val_loss: 0.0114 - val_mae: 0.0821 - val_rmse: 0.1006 - val_smape: 0.2164

Epoch 79/128

1147/1147 - 3s - 2ms/step - ia: 0.8817 - loss: 0.0668 - mae: 0.1876 - rmse: 0.2544 - smape: 0.3740 - val_ia: 0.8096 - val_loss: 0.0116 - val_mae: 0.0832 - val_rmse: 0.1015 - val_smape: 0.2223

Epoch 80/128

1147/1147 - 3s - 3ms/step - ia: 0.8809 - loss: 0.0673 - mae: 0.1880 - rmse: 0.2555 - smape: 0.3749 - val_ia: 0.8157 - val_loss: 0.0109 - val_mae: 0.0801 - val_rmse: 0.0985 - val_smape: 0.2165

Epoch 81/128

1147/1147 - 4s - 3ms/step - ia: 0.8822 - loss: 0.0667 - mae: 0.1870 - rmse: 0.2543 - smape: 0.3706 - val_ia: 0.8229 - val_loss: 0.0101 - val_mae: 0.0766 - val_rmse: 0.0950 - val_smape: 0.2140

Epoch 82/128

1147/1147 - 5s - 4ms/step - ia: 0.8832 - loss: 0.0659 - mae: 0.1854 - rmse: 0.2525 - smape: 0.3683 - val_ia: 0.8221 - val_loss: 0.0102 - val_mae: 0.0772 - val_rmse: 0.0957 - val_smape: 0.2137

Epoch 83/128

1147/1147 - 3s - 3ms/step - ia: 0.8837 - loss: 0.0647 - mae: 0.1841 - rmse: 0.2500 - smape: 0.3652 - val_ia: 0.8185 - val_loss: 0.0104 - val_mae: 0.0785 - val_rmse: 0.0966 - val_smape: 0.2159

Epoch 84/128

1147/1147 - 5s - 4ms/step - ia: 0.8853 - loss: 0.0633 - mae: 0.1820 - rmse: 0.2474 - smape: 0.3610 - val_ia: 0.8191 - val_loss: 0.0104 - val_mae: 0.0784 - val_rmse: 0.0965 - val_smape: 0.2163

Epoch 85/128

1147/1147 - 3s - 3ms/step - ia: 0.8851 - loss: 0.0636 - mae: 0.1820 - rmse: 0.2478 - smape: 0.3635 - val_ia: 0.8177 - val_loss: 0.0105 - val_mae: 0.0789 - val_rmse: 0.0970 - val_smape: 0.2148

Epoch 86/128

1147/1147 - 5s - 4ms/step - ia: 0.8848 - loss: 0.0631 - mae: 0.1826 - rmse: 0.2472 - smape: 0.3663 - val_ia: 0.8249 - val_loss: 0.0096 - val_mae: 0.0748 - val_rmse: 0.0928 - val_smape: 0.2096

Epoch 87/128

1147/1147 - 3s - 3ms/step - ia: 0.8863 - loss: 0.0618 - mae: 0.1803 - rmse: 0.2448 - smape: 0.3625 - val_ia: 0.8255 - val_loss: 0.0096 - val_mae: 0.0747 - val_rmse: 0.0926 - val_smape: 0.2072

Epoch 88/128

1147/1147 - 3s - 2ms/step - ia: 0.8868 - loss: 0.0619 - mae: 0.1798 - rmse: 0.2448 - smape: 0.3576 - val_ia: 0.8190 - val_loss: 0.0102 - val_mae: 0.0778 - val_rmse: 0.0955 - val_smape: 0.2115

Epoch 89/128

1147/1147 - 2s - 2ms/step - ia: 0.8871 - loss: 0.0609 - mae: 0.1789 - rmse: 0.2428 - smape: 0.3579 - val_ia: 0.8256 - val_loss: 0.0096 - val_mae: 0.0751 - val_rmse: 0.0928 - val_smape: 0.2122

Epoch 90/128

1147/1147 - 2s - 2ms/step - ia: 0.8870 - loss: 0.0613 - mae: 0.1791 - rmse: 0.2437 - smape: 0.3538 - val_ia: 0.8194 - val_loss: 0.0102 - val_mae: 0.0778 - val_rmse: 0.0955 - val_smape: 0.2116

Epoch 91/128

1147/1147 - 2s - 2ms/step - ia: 0.8882 - loss: 0.0602 - mae: 0.1774 - rmse: 0.2415 - smape: 0.3544 - val_ia: 0.8259 - val_loss: 0.0096 - val_mae: 0.0750 - val_rmse: 0.0928 - val_smape: 0.2098

Epoch 92/128

1147/1147 - 3s - 3ms/step - ia: 0.8884 - loss: 0.0603 - mae: 0.1771 - rmse: 0.2417 - smape: 0.3526 - val_ia: 0.8195 - val_loss: 0.0101 - val_mae: 0.0776 - val_rmse: 0.0952 - val_smape: 0.2126

Epoch 93/128

1147/1147 - 5s - 5ms/step - ia: 0.8895 - loss: 0.0587 - mae: 0.1757 - rmse: 0.2383 - smape: 0.3509 - val_ia: 0.8242 - val_loss: 0.0097 - val_mae: 0.0756 - val_rmse: 0.0933 - val_smape: 0.2085

Epoch 94/128

1147/1147 - 3s - 3ms/step - ia: 0.8892 - loss: 0.0594 - mae: 0.1759 - rmse: 0.2397 - smape: 0.3488 - val_ia: 0.8270 - val_loss: 0.0094 - val_mae: 0.0741 - val_rmse: 0.0917 - val_smape: 0.2086

Epoch 95/128

1147/1147 - 3s - 3ms/step - ia: 0.8902 - loss: 0.0587 - mae: 0.1743 - rmse: 0.2382 - smape: 0.3470 - val_ia: 0.8139 - val_loss: 0.0108 - val_mae: 0.0801 - val_rmse: 0.0978 - val_smape: 0.2069

Epoch 96/128

1147/1147 - 3s - 3ms/step - ia: 0.8900 - loss: 0.0584 - mae: 0.1743 - rmse: 0.2376 - smape: 0.3446 - val_ia: 0.8251 - val_loss: 0.0096 - val_mae: 0.0748 - val_rmse: 0.0924 - val_smape: 0.2045

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

574/574 - 6s - 10ms/step - ia: 0.2353 - loss: 1.8861 - mae: 1.1273 - rmse: 1.3694 - smape: 1.5446 - val_ia: 0.2667 - val_loss: 1.4855 - val_mae: 1.0012 - val_rmse: 1.1602 - val_smape: 1.5575

Epoch 2/128

574/574 - 2s - 4ms/step - ia: 0.3015 - loss: 1.5850 - mae: 1.0239 - rmse: 1.2545 - smape: 1.4490 - val_ia: 0.3100 - val_loss: 1.2462 - val_mae: 0.9048 - val_rmse: 1.0590 - val_smape: 1.4198

Epoch 3/128

574/574 - 2s - 3ms/step - ia: 0.3671 - loss: 1.3380 - mae: 0.9326 - rmse: 1.1523 - smape: 1.3603 - val_ia: 0.3544 - val_loss: 1.0738 - val_mae: 0.8282 - val_rmse: 0.9802 - val_smape: 1.2912

Epoch 4/128

574/574 - 3s - 5ms/step - ia: 0.4278 - loss: 1.1571 - mae: 0.8633 - rmse: 1.0712 - smape: 1.2735 - val_ia: 0.3924 - val_loss: 0.9579 - val_mae: 0.7729 - val_rmse: 0.9239 - val_smape: 1.1891

Epoch 5/128

574/574 - 2s - 3ms/step - ia: 0.4798 - loss: 1.0204 - mae: 0.8060 - rmse: 1.0050 - smape: 1.1989 - val_ia: 0.4234 - val_loss: 0.8816 - val_mae: 0.7355 - val_rmse: 0.8850 - val_smape: 1.1131

Epoch 6/128

574/574 - 3s - 4ms/step - ia: 0.5203 - loss: 0.9282 - mae: 0.7637 - rmse: 0.9586 - smape: 1.1349 - val_ia: 0.4453 - val_loss: 0.8327 - val_mae: 0.7121 - val_rmse: 0.8589 - val_smape: 1.0592

Epoch 7/128

574/574 - 3s - 5ms/step - ia: 0.5440 - loss: 0.8728 - mae: 0.7404 - rmse: 0.9293 - smape: 1.1016 - val_ia: 0.4604 - val_loss: 0.8002 - val_mae: 0.6982 - val_rmse: 0.8407 - val_smape: 1.0210

Epoch 8/128

574/574 - 2s - 3ms/step - ia: 0.5672 - loss: 0.8142 - mae: 0.7141 - rmse: 0.8984 - smape: 1.0641 - val_ia: 0.4724 - val_loss: 0.7757 - val_mae: 0.6882 - val_rmse: 0.8266 - val_smape: 0.9940

Epoch 9/128

574/574 - 3s - 5ms/step - ia: 0.5867 - loss: 0.7695 - mae: 0.6942 - rmse: 0.8728 - smape: 1.0296 - val_ia: 0.4827 - val_loss: 0.7538 - val_mae: 0.6786 - val_rmse: 0.8135 - val_smape: 0.9765

Epoch 10/128

574/574 - 2s - 3ms/step - ia: 0.6010 - loss: 0.7278 - mae: 0.6731 - rmse: 0.8487 - smape: 1.0072 - val_ia: 0.4926 - val_loss: 0.7313 - val_mae: 0.6681 - val_rmse: 0.7996 - val_smape: 0.9621

Epoch 11/128

574/574 - 2s - 3ms/step - ia: 0.6112 - loss: 0.7042 - mae: 0.6615 - rmse: 0.8348 - smape: 0.9910 - val_ia: 0.5022 - val_loss: 0.7067 - val_mae: 0.6562 - val_rmse: 0.7843 - val_smape: 0.9502

Epoch 12/128

574/574 - 3s - 4ms/step - ia: 0.6206 - loss: 0.6681 - mae: 0.6444 - rmse: 0.8133 - smape: 0.9792 - val_ia: 0.5119 - val_loss: 0.6821 - val_mae: 0.6437 - val_rmse: 0.7685 - val_smape: 0.9381

Epoch 13/128

574/574 - 2s - 4ms/step - ia: 0.6303 - loss: 0.6404 - mae: 0.6285 - rmse: 0.7963 - smape: 0.9609 - val_ia: 0.5214 - val_loss: 0.6573 - val_mae: 0.6307 - val_rmse: 0.7523 - val_smape: 0.9263

Epoch 14/128

574/574 - 3s - 5ms/step - ia: 0.6374 - loss: 0.6182 - mae: 0.6178 - rmse: 0.7826 - smape: 0.9511 - val_ia: 0.5308 - val_loss: 0.6308 - val_mae: 0.6164 - val_rmse: 0.7347 - val_smape: 0.9150

Epoch 15/128

574/574 - 2s - 3ms/step - ia: 0.6476 - loss: 0.5803 - mae: 0.5974 - rmse: 0.7576 - smape: 0.9335 - val_ia: 0.5399 - val_loss: 0.6062 - val_mae: 0.6030 - val_rmse: 0.7179 - val_smape: 0.9048

Epoch 16/128

574/574 - 2s - 3ms/step - ia: 0.6528 - loss: 0.5641 - mae: 0.5884 - rmse: 0.7473 - smape: 0.9248 - val_ia: 0.5490 - val_loss: 0.5813 - val_mae: 0.5892 - val_rmse: 0.7007 - val_smape: 0.8942

Epoch 17/128

574/574 - 2s - 4ms/step - ia: 0.6584 - loss: 0.5411 - mae: 0.5775 - rmse: 0.7327 - smape: 0.9156 - val_ia: 0.5583 - val_loss: 0.5565 - val_mae: 0.5750 - val_rmse: 0.6829 - val_smape: 0.8828

Epoch 18/128

574/574 - 2s - 3ms/step - ia: 0.6663 - loss: 0.5182 - mae: 0.5631 - rmse: 0.7163 - smape: 0.9026 - val_ia: 0.5675 - val_loss: 0.5316 - val_mae: 0.5606 - val_rmse: 0.6651 - val_smape: 0.8717

Epoch 19/128

574/574 - 2s - 3ms/step - ia: 0.6703 - loss: 0.5008 - mae: 0.5558 - rmse: 0.7042 - smape: 0.8979 - val_ia: 0.5762 - val_loss: 0.5079 - val_mae: 0.5468 - val_rmse: 0.6479 - val_smape: 0.8616

Epoch 20/128

574/574 - 3s - 4ms/step - ia: 0.6799 - loss: 0.4733 - mae: 0.5379 - rmse: 0.6843 - smape: 0.8792 - val_ia: 0.5850 - val_loss: 0.4863 - val_mae: 0.5337 - val_rmse: 0.6316 - val_smape: 0.8508

Epoch 21/128

574/574 - 1s - 3ms/step - ia: 0.6838 - loss: 0.4625 - mae: 0.5325 - rmse: 0.6766 - smape: 0.8723 - val_ia: 0.5931 - val_loss: 0.4643 - val_mae: 0.5206 - val_rmse: 0.6151 - val_smape: 0.8415

Epoch 22/128

574/574 - 3s - 4ms/step - ia: 0.6870 - loss: 0.4510 - mae: 0.5249 - rmse: 0.6685 - smape: 0.8646 - val_ia: 0.6017 - val_loss: 0.4437 - val_mae: 0.5077 - val_rmse: 0.5993 - val_smape: 0.8311

Epoch 23/128

574/574 - 2s - 3ms/step - ia: 0.6937 - loss: 0.4318 - mae: 0.5138 - rmse: 0.6536 - smape: 0.8518 - val_ia: 0.6098 - val_loss: 0.4224 - val_mae: 0.4945 - val_rmse: 0.5829 - val_smape: 0.8219

Epoch 24/128

574/574 - 1s - 2ms/step - ia: 0.6985 - loss: 0.4150 - mae: 0.5030 - rmse: 0.6406 - smape: 0.8434 - val_ia: 0.6177 - val_loss: 0.4032 - val_mae: 0.4822 - val_rmse: 0.5677 - val_smape: 0.8132

Epoch 25/128

574/574 - 2s - 3ms/step - ia: 0.7028 - loss: 0.4049 - mae: 0.4965 - rmse: 0.6328 - smape: 0.8338 - val_ia: 0.6255 - val_loss: 0.3833 - val_mae: 0.4693 - val_rmse: 0.5521 - val_smape: 0.8044

Epoch 26/128

574/574 - 2s - 3ms/step - ia: 0.7075 - loss: 0.3895 - mae: 0.4866 - rmse: 0.6210 - smape: 0.8265 - val_ia: 0.6332 - val_loss: 0.3652 - val_mae: 0.4572 - val_rmse: 0.5376 - val_smape: 0.7957

Epoch 27/128

574/574 - 2s - 4ms/step - ia: 0.7132 - loss: 0.3763 - mae: 0.4781 - rmse: 0.6096 - smape: 0.8166 - val_ia: 0.6409 - val_loss: 0.3465 - val_mae: 0.4446 - val_rmse: 0.5228 - val_smape: 0.7871

Epoch 28/128

574/574 - 3s - 4ms/step - ia: 0.7159 - loss: 0.3680 - mae: 0.4736 - rmse: 0.6026 - smape: 0.8148 - val_ia: 0.6484 - val_loss: 0.3292 - val_mae: 0.4325 - val_rmse: 0.5088 - val_smape: 0.7785

Epoch 29/128

574/574 - 3s - 5ms/step - ia: 0.7215 - loss: 0.3542 - mae: 0.4640 - rmse: 0.5920 - smape: 0.8008 - val_ia: 0.6556 - val_loss: 0.3121 - val_mae: 0.4206 - val_rmse: 0.4949 - val_smape: 0.7701

Epoch 30/128

574/574 - 3s - 5ms/step - ia: 0.7254 - loss: 0.3453 - mae: 0.4567 - rmse: 0.5844 - smape: 0.7900 - val_ia: 0.6624 - val_loss: 0.2959 - val_mae: 0.4091 - val_rmse: 0.4814 - val_smape: 0.7618

Epoch 31/128

574/574 - 2s - 3ms/step - ia: 0.7281 - loss: 0.3356 - mae: 0.4522 - rmse: 0.5763 - smape: 0.7895 - val_ia: 0.6694 - val_loss: 0.2801 - val_mae: 0.3976 - val_rmse: 0.4683 - val_smape: 0.7532

Epoch 32/128

574/574 - 3s - 5ms/step - ia: 0.7347 - loss: 0.3198 - mae: 0.4404 - rmse: 0.5625 - smape: 0.7754 - val_ia: 0.6756 - val_loss: 0.2661 - val_mae: 0.3872 - val_rmse: 0.4562 - val_smape: 0.7452

Epoch 33/128

574/574 - 3s - 5ms/step - ia: 0.7341 - loss: 0.3201 - mae: 0.4415 - rmse: 0.5628 - smape: 0.7723 - val_ia: 0.6821 - val_loss: 0.2521 - val_mae: 0.3766 - val_rmse: 0.4440 - val_smape: 0.7370

Epoch 34/128

574/574 - 2s - 3ms/step - ia: 0.7409 - loss: 0.3048 - mae: 0.4302 - rmse: 0.5490 - smape: 0.7609 - val_ia: 0.6885 - val_loss: 0.2382 - val_mae: 0.3659 - val_rmse: 0.4317 - val_smape: 0.7284

Epoch 35/128

574/574 - 3s - 5ms/step - ia: 0.7429 - loss: 0.2994 - mae: 0.4268 - rmse: 0.5441 - smape: 0.7589 - val_ia: 0.6949 - val_loss: 0.2253 - val_mae: 0.3557 - val_rmse: 0.4204 - val_smape: 0.7202

Epoch 36/128

574/574 - 2s - 4ms/step - ia: 0.7458 - loss: 0.2910 - mae: 0.4209 - rmse: 0.5364 - smape: 0.7531 - val_ia: 0.7010 - val_loss: 0.2129 - val_mae: 0.3458 - val_rmse: 0.4094 - val_smape: 0.7123

Epoch 37/128

574/574 - 3s - 4ms/step - ia: 0.7485 - loss: 0.2862 - mae: 0.4165 - rmse: 0.5322 - smape: 0.7473 - val_ia: 0.7068 - val_loss: 0.2014 - val_mae: 0.3364 - val_rmse: 0.3989 - val_smape: 0.7042

Epoch 38/128

574/574 - 1s - 2ms/step - ia: 0.7511 - loss: 0.2802 - mae: 0.4120 - rmse: 0.5264 - smape: 0.7389 - val_ia: 0.7127 - val_loss: 0.1899 - val_mae: 0.3268 - val_rmse: 0.3883 - val_smape: 0.6959

Epoch 39/128

574/574 - 1s - 2ms/step - ia: 0.7541 - loss: 0.2710 - mae: 0.4060 - rmse: 0.5181 - smape: 0.7327 - val_ia: 0.7185 - val_loss: 0.1799 - val_mae: 0.3180 - val_rmse: 0.3787 - val_smape: 0.6875

Epoch 40/128

574/574 - 1s - 2ms/step - ia: 0.7564 - loss: 0.2673 - mae: 0.4024 - rmse: 0.5144 - smape: 0.7288 - val_ia: 0.7238 - val_loss: 0.1694 - val_mae: 0.3090 - val_rmse: 0.3685 - val_smape: 0.6790

Epoch 41/128

574/574 - 1s - 2ms/step - ia: 0.7586 - loss: 0.2623 - mae: 0.3981 - rmse: 0.5095 - smape: 0.7219 - val_ia: 0.7294 - val_loss: 0.1606 - val_mae: 0.3009 - val_rmse: 0.3599 - val_smape: 0.6713

Epoch 42/128

574/574 - 1s - 3ms/step - ia: 0.7629 - loss: 0.2543 - mae: 0.3921 - rmse: 0.5014 - smape: 0.7173 - val_ia: 0.7347 - val_loss: 0.1517 - val_mae: 0.2926 - val_rmse: 0.3507 - val_smape: 0.6628

Epoch 43/128

574/574 - 2s - 3ms/step - ia: 0.7653 - loss: 0.2487 - mae: 0.3875 - rmse: 0.4962 - smape: 0.7081 - val_ia: 0.7400 - val_loss: 0.1431 - val_mae: 0.2845 - val_rmse: 0.3418 - val_smape: 0.6541

Epoch 44/128

574/574 - 3s - 4ms/step - ia: 0.7666 - loss: 0.2448 - mae: 0.3844 - rmse: 0.4923 - smape: 0.7049 - val_ia: 0.7450 - val_loss: 0.1349 - val_mae: 0.2766 - val_rmse: 0.3330 - val_smape: 0.6457

Epoch 45/128

574/574 - 2s - 3ms/step - ia: 0.7696 - loss: 0.2410 - mae: 0.3802 - rmse: 0.4880 - smape: 0.6975 - val_ia: 0.7498 - val_loss: 0.1275 - val_mae: 0.2694 - val_rmse: 0.3249 - val_smape: 0.6374

Epoch 46/128

574/574 - 2s - 4ms/step - ia: 0.7707 - loss: 0.2368 - mae: 0.3778 - rmse: 0.4840 - smape: 0.6986 - val_ia: 0.7550 - val_loss: 0.1207 - val_mae: 0.2623 - val_rmse: 0.3171 - val_smape: 0.6289

Epoch 47/128

574/574 - 2s - 4ms/step - ia: 0.7724 - loss: 0.2338 - mae: 0.3755 - rmse: 0.4809 - smape: 0.6951 - val_ia: 0.7595 - val_loss: 0.1142 - val_mae: 0.2556 - val_rmse: 0.3098 - val_smape: 0.6205

Epoch 48/128

574/574 - 3s - 5ms/step - ia: 0.7752 - loss: 0.2286 - mae: 0.3698 - rmse: 0.4750 - smape: 0.6863 - val_ia: 0.7636 - val_loss: 0.1085 - val_mae: 0.2496 - val_rmse: 0.3030 - val_smape: 0.6123

Epoch 49/128

574/574 - 2s - 3ms/step - ia: 0.7769 - loss: 0.2253 - mae: 0.3672 - rmse: 0.4718 - smape: 0.6818 - val_ia: 0.7679 - val_loss: 0.1035 - val_mae: 0.2441 - val_rmse: 0.2969 - val_smape: 0.6043

Epoch 50/128

574/574 - 2s - 4ms/step - ia: 0.7787 - loss: 0.2191 - mae: 0.3641 - rmse: 0.4653 - smape: 0.6814 - val_ia: 0.7720 - val_loss: 0.0985 - val_mae: 0.2385 - val_rmse: 0.2906 - val_smape: 0.5952

Epoch 51/128

574/574 - 2s - 3ms/step - ia: 0.7806 - loss: 0.2158 - mae: 0.3606 - rmse: 0.4616 - smape: 0.6740 - val_ia: 0.7753 - val_loss: 0.0944 - val_mae: 0.2339 - val_rmse: 0.2854 - val_smape: 0.5887

Epoch 52/128

574/574 - 3s - 5ms/step - ia: 0.7829 - loss: 0.2113 - mae: 0.3566 - rmse: 0.4572 - smape: 0.6692 - val_ia: 0.7793 - val_loss: 0.0897 - val_mae: 0.2284 - val_rmse: 0.2792 - val_smape: 0.5793

Epoch 53/128

574/574 - 2s - 4ms/step - ia: 0.7843 - loss: 0.2098 - mae: 0.3546 - rmse: 0.4554 - smape: 0.6678 - val_ia: 0.7829 - val_loss: 0.0856 - val_mae: 0.2236 - val_rmse: 0.2738 - val_smape: 0.5702

Epoch 54/128

574/574 - 3s - 4ms/step - ia: 0.7861 - loss: 0.2061 - mae: 0.3510 - rmse: 0.4519 - smape: 0.6646 - val_ia: 0.7875 - val_loss: 0.0817 - val_mae: 0.2185 - val_rmse: 0.2684 - val_smape: 0.5599

Epoch 55/128

574/574 - 3s - 5ms/step - ia: 0.7877 - loss: 0.2037 - mae: 0.3486 - rmse: 0.4486 - smape: 0.6584 - val_ia: 0.7903 - val_loss: 0.0789 - val_mae: 0.2150 - val_rmse: 0.2644 - val_smape: 0.5530

Epoch 56/128

574/574 - 2s - 3ms/step - ia: 0.7889 - loss: 0.1994 - mae: 0.3462 - rmse: 0.4443 - smape: 0.6534 - val_ia: 0.7935 - val_loss: 0.0758 - val_mae: 0.2110 - val_rmse: 0.2599 - val_smape: 0.5441

Epoch 57/128

574/574 - 3s - 5ms/step - ia: 0.7903 - loss: 0.1969 - mae: 0.3428 - rmse: 0.4411 - smape: 0.6520 - val_ia: 0.7971 - val_loss: 0.0728 - val_mae: 0.2069 - val_rmse: 0.2554 - val_smape: 0.5350

Epoch 58/128

574/574 - 2s - 3ms/step - ia: 0.7921 - loss: 0.1941 - mae: 0.3414 - rmse: 0.4384 - smape: 0.6480 - val_ia: 0.7994 - val_loss: 0.0703 - val_mae: 0.2038 - val_rmse: 0.2518 - val_smape: 0.5269

Epoch 59/128

574/574 - 3s - 4ms/step - ia: 0.7933 - loss: 0.1913 - mae: 0.3377 - rmse: 0.4350 - smape: 0.6448 - val_ia: 0.8028 - val_loss: 0.0679 - val_mae: 0.2002 - val_rmse: 0.2480 - val_smape: 0.5190

Epoch 60/128

574/574 - 2s - 3ms/step - ia: 0.7942 - loss: 0.1895 - mae: 0.3365 - rmse: 0.4334 - smape: 0.6419 - val_ia: 0.8057 - val_loss: 0.0657 - val_mae: 0.1970 - val_rmse: 0.2444 - val_smape: 0.5102

Epoch 61/128

574/574 - 2s - 4ms/step - ia: 0.7965 - loss: 0.1862 - mae: 0.3332 - rmse: 0.4291 - smape: 0.6352 - val_ia: 0.8084 - val_loss: 0.0634 - val_mae: 0.1935 - val_rmse: 0.2405 - val_smape: 0.4996

Epoch 62/128

574/574 - 3s - 5ms/step - ia: 0.7974 - loss: 0.1824 - mae: 0.3312 - rmse: 0.4248 - smape: 0.6376 - val_ia: 0.8106 - val_loss: 0.0617 - val_mae: 0.1910 - val_rmse: 0.2377 - val_smape: 0.4925

Epoch 63/128

574/574 - 3s - 5ms/step - ia: 0.7997 - loss: 0.1810 - mae: 0.3275 - rmse: 0.4228 - smape: 0.6296 - val_ia: 0.8133 - val_loss: 0.0599 - val_mae: 0.1883 - val_rmse: 0.2348 - val_smape: 0.4849

Epoch 64/128

574/574 - 3s - 5ms/step - ia: 0.7998 - loss: 0.1810 - mae: 0.3280 - rmse: 0.4227 - smape: 0.6296 - val_ia: 0.8157 - val_loss: 0.0584 - val_mae: 0.1856 - val_rmse: 0.2319 - val_smape: 0.4775

Epoch 65/128

574/574 - 3s - 5ms/step - ia: 0.8029 - loss: 0.1741 - mae: 0.3224 - rmse: 0.4147 - smape: 0.6222 - val_ia: 0.8174 - val_loss: 0.0570 - val_mae: 0.1835 - val_rmse: 0.2295 - val_smape: 0.4700

Epoch 66/128

574/574 - 2s - 3ms/step - ia: 0.8026 - loss: 0.1740 - mae: 0.3219 - rmse: 0.4150 - smape: 0.6247 - val_ia: 0.8198 - val_loss: 0.0556 - val_mae: 0.1811 - val_rmse: 0.2269 - val_smape: 0.4629

Epoch 67/128

574/574 - 1s - 3ms/step - ia: 0.8042 - loss: 0.1719 - mae: 0.3194 - rmse: 0.4124 - smape: 0.6195 - val_ia: 0.8223 - val_loss: 0.0541 - val_mae: 0.1784 - val_rmse: 0.2242 - val_smape: 0.4552

Epoch 68/128

574/574 - 3s - 4ms/step - ia: 0.8066 - loss: 0.1674 - mae: 0.3153 - rmse: 0.4069 - smape: 0.6120 - val_ia: 0.8239 - val_loss: 0.0531 - val_mae: 0.1767 - val_rmse: 0.2222 - val_smape: 0.4493

Epoch 69/128

574/574 - 3s - 5ms/step - ia: 0.8065 - loss: 0.1692 - mae: 0.3159 - rmse: 0.4089 - smape: 0.6114 - val_ia: 0.8256 - val_loss: 0.0518 - val_mae: 0.1744 - val_rmse: 0.2197 - val_smape: 0.4408

Epoch 70/128

574/574 - 3s - 5ms/step - ia: 0.8085 - loss: 0.1643 - mae: 0.3124 - rmse: 0.4027 - smape: 0.6054 - val_ia: 0.8269 - val_loss: 0.0511 - val_mae: 0.1732 - val_rmse: 0.2184 - val_smape: 0.4368

Epoch 71/128

574/574 - 2s - 4ms/step - ia: 0.8094 - loss: 0.1638 - mae: 0.3107 - rmse: 0.4021 - smape: 0.6070 - val_ia: 0.8291 - val_loss: 0.0500 - val_mae: 0.1711 - val_rmse: 0.2162 - val_smape: 0.4305

Epoch 72/128

574/574 - 3s - 5ms/step - ia: 0.8097 - loss: 0.1636 - mae: 0.3105 - rmse: 0.4020 - smape: 0.6021 - val_ia: 0.8305 - val_loss: 0.0490 - val_mae: 0.1692 - val_rmse: 0.2142 - val_smape: 0.4228

Epoch 73/128

574/574 - 2s - 4ms/step - ia: 0.8110 - loss: 0.1607 - mae: 0.3077 - rmse: 0.3986 - smape: 0.5995 - val_ia: 0.8322 - val_loss: 0.0482 - val_mae: 0.1676 - val_rmse: 0.2125 - val_smape: 0.4182

Epoch 74/128

574/574 - 3s - 5ms/step - ia: 0.8116 - loss: 0.1587 - mae: 0.3060 - rmse: 0.3961 - smape: 0.5957 - val_ia: 0.8343 - val_loss: 0.0472 - val_mae: 0.1656 - val_rmse: 0.2105 - val_smape: 0.4122

Epoch 75/128

574/574 - 3s - 5ms/step - ia: 0.8129 - loss: 0.1572 - mae: 0.3055 - rmse: 0.3942 - smape: 0.5991 - val_ia: 0.8351 - val_loss: 0.0467 - val_mae: 0.1646 - val_rmse: 0.2094 - val_smape: 0.4088

Epoch 76/128

574/574 - 2s - 3ms/step - ia: 0.8140 - loss: 0.1557 - mae: 0.3031 - rmse: 0.3921 - smape: 0.5922 - val_ia: 0.8365 - val_loss: 0.0460 - val_mae: 0.1633 - val_rmse: 0.2080 - val_smape: 0.4043

Epoch 77/128

574/574 - 3s - 6ms/step - ia: 0.8151 - loss: 0.1531 - mae: 0.3010 - rmse: 0.3889 - smape: 0.5928 - val_ia: 0.8379 - val_loss: 0.0453 - val_mae: 0.1618 - val_rmse: 0.2065 - val_smape: 0.3997

Epoch 78/128

574/574 - 2s - 3ms/step - ia: 0.8170 - loss: 0.1500 - mae: 0.2980 - rmse: 0.3852 - smape: 0.5870 - val_ia: 0.8389 - val_loss: 0.0447 - val_mae: 0.1605 - val_rmse: 0.2050 - val_smape: 0.3945

Epoch 79/128

574/574 - 2s - 3ms/step - ia: 0.8166 - loss: 0.1505 - mae: 0.2975 - rmse: 0.3854 - smape: 0.5853 - val_ia: 0.8407 - val_loss: 0.0439 - val_mae: 0.1590 - val_rmse: 0.2034 - val_smape: 0.3911

Epoch 80/128

574/574 - 3s - 5ms/step - ia: 0.8177 - loss: 0.1496 - mae: 0.2969 - rmse: 0.3848 - smape: 0.5826 - val_ia: 0.8414 - val_loss: 0.0435 - val_mae: 0.1580 - val_rmse: 0.2024 - val_smape: 0.3870

Epoch 81/128

574/574 - 2s - 3ms/step - ia: 0.8197 - loss: 0.1461 - mae: 0.2935 - rmse: 0.3799 - smape: 0.5818 - val_ia: 0.8422 - val_loss: 0.0430 - val_mae: 0.1571 - val_rmse: 0.2013 - val_smape: 0.3833

Epoch 82/128

574/574 - 3s - 4ms/step - ia: 0.8198 - loss: 0.1456 - mae: 0.2926 - rmse: 0.3792 - smape: 0.5771 - val_ia: 0.8438 - val_loss: 0.0424 - val_mae: 0.1558 - val_rmse: 0.1999 - val_smape: 0.3807

Epoch 83/128

574/574 - 1s - 2ms/step - ia: 0.8200 - loss: 0.1451 - mae: 0.2929 - rmse: 0.3787 - smape: 0.5750 - val_ia: 0.8441 - val_loss: 0.0421 - val_mae: 0.1552 - val_rmse: 0.1992 - val_smape: 0.3771

Epoch 84/128

574/574 - 1s - 2ms/step - ia: 0.8206 - loss: 0.1446 - mae: 0.2919 - rmse: 0.3778 - smape: 0.5736 - val_ia: 0.8449 - val_loss: 0.0417 - val_mae: 0.1540 - val_rmse: 0.1980 - val_smape: 0.3718

Epoch 85/128

574/574 - 3s - 4ms/step - ia: 0.8236 - loss: 0.1396 - mae: 0.2858 - rmse: 0.3711 - smape: 0.5657 - val_ia: 0.8467 - val_loss: 0.0409 - val_mae: 0.1525 - val_rmse: 0.1964 - val_smape: 0.3684

Epoch 86/128

574/574 - 3s - 5ms/step - ia: 0.8244 - loss: 0.1386 - mae: 0.2853 - rmse: 0.3700 - smape: 0.5655 - val_ia: 0.8470 - val_loss: 0.0407 - val_mae: 0.1520 - val_rmse: 0.1957 - val_smape: 0.3659

Epoch 87/128

574/574 - 3s - 4ms/step - ia: 0.8241 - loss: 0.1389 - mae: 0.2859 - rmse: 0.3700 - smape: 0.5648 - val_ia: 0.8482 - val_loss: 0.0402 - val_mae: 0.1508 - val_rmse: 0.1946 - val_smape: 0.3625

Epoch 88/128

574/574 - 1s - 2ms/step - ia: 0.8234 - loss: 0.1399 - mae: 0.2864 - rmse: 0.3717 - smape: 0.5649 - val_ia: 0.8490 - val_loss: 0.0398 - val_mae: 0.1499 - val_rmse: 0.1936 - val_smape: 0.3600

Epoch 89/128

574/574 - 2s - 4ms/step - ia: 0.8264 - loss: 0.1360 - mae: 0.2819 - rmse: 0.3665 - smape: 0.5589 - val_ia: 0.8499 - val_loss: 0.0394 - val_mae: 0.1490 - val_rmse: 0.1926 - val_smape: 0.3570

Epoch 90/128

574/574 - 1s - 3ms/step - ia: 0.8253 - loss: 0.1363 - mae: 0.2832 - rmse: 0.3670 - smape: 0.5602 - val_ia: 0.8509 - val_loss: 0.0389 - val_mae: 0.1480 - val_rmse: 0.1915 - val_smape: 0.3546

Epoch 91/128

574/574 - 2s - 3ms/step - ia: 0.8263 - loss: 0.1355 - mae: 0.2825 - rmse: 0.3660 - smape: 0.5587 - val_ia: 0.8512 - val_loss: 0.0387 - val_mae: 0.1475 - val_rmse: 0.1910 - val_smape: 0.3516

Epoch 92/128

574/574 - 3s - 4ms/step - ia: 0.8266 - loss: 0.1352 - mae: 0.2811 - rmse: 0.3655 - smape: 0.5590 - val_ia: 0.8522 - val_loss: 0.0384 - val_mae: 0.1469 - val_rmse: 0.1902 - val_smape: 0.3520

Epoch 93/128

574/574 - 2s - 3ms/step - ia: 0.8283 - loss: 0.1340 - mae: 0.2786 - rmse: 0.3638 - smape: 0.5517 - val_ia: 0.8533 - val_loss: 0.0379 - val_mae: 0.1459 - val_rmse: 0.1891 - val_smape: 0.3494

Epoch 94/128

574/574 - 3s - 5ms/step - ia: 0.8295 - loss: 0.1308 - mae: 0.2767 - rmse: 0.3597 - smape: 0.5503 - val_ia: 0.8536 - val_loss: 0.0376 - val_mae: 0.1451 - val_rmse: 0.1883 - val_smape: 0.3450

Epoch 95/128

574/574 - 2s - 3ms/step - ia: 0.8313 - loss: 0.1286 - mae: 0.2739 - rmse: 0.3564 - smape: 0.5439 - val_ia: 0.8544 - val_loss: 0.0373 - val_mae: 0.1443 - val_rmse: 0.1875 - val_smape: 0.3428

Epoch 96/128

574/574 - 3s - 5ms/step - ia: 0.8300 - loss: 0.1298 - mae: 0.2754 - rmse: 0.3581 - smape: 0.5480 - val_ia: 0.8556 - val_loss: 0.0368 - val_mae: 0.1433 - val_rmse: 0.1864 - val_smape: 0.3401

Epoch 97/128

574/574 - 3s - 5ms/step - ia: 0.8298 - loss: 0.1297 - mae: 0.2758 - rmse: 0.3583 - smape: 0.5488 - val_ia: 0.8561 - val_loss: 0.0366 - val_mae: 0.1427 - val_rmse: 0.1858 - val_smape: 0.3383

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 6s - 21ms/step - ia: 0.3160 - loss: 1.4464 - mae: 0.9783 - rmse: 1.2011 - smape: 1.4189 - val_ia: 0.2848 - val_loss: 0.8498 - val_mae: 0.7672 - val_rmse: 0.9075 - val_smape: 1.5047

Epoch 2/128

287/287 - 1s - 3ms/step - ia: 0.3368 - loss: 1.3399 - mae: 0.9380 - rmse: 1.1554 - smape: 1.3893 - val_ia: 0.3083 - val_loss: 0.7632 - val_mae: 0.7279 - val_rmse: 0.8613 - val_smape: 1.5209

Epoch 3/128

287/287 - 1s - 5ms/step - ia: 0.3551 - loss: 1.2630 - mae: 0.9089 - rmse: 1.1220 - smape: 1.3640 - val_ia: 0.3398 - val_loss: 0.6909 - val_mae: 0.6927 - val_rmse: 0.8203 - val_smape: 1.4580

Epoch 4/128

287/287 - 1s - 3ms/step - ia: 0.3722 - loss: 1.1933 - mae: 0.8841 - rmse: 1.0906 - smape: 1.3438 - val_ia: 0.3725 - val_loss: 0.6301 - val_mae: 0.6614 - val_rmse: 0.7840 - val_smape: 1.3815

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.3906 - loss: 1.1322 - mae: 0.8604 - rmse: 1.0619 - smape: 1.3188 - val_ia: 0.4047 - val_loss: 0.5783 - val_mae: 0.6331 - val_rmse: 0.7512 - val_smape: 1.3077

Epoch 6/128

287/287 - 2s - 5ms/step - ia: 0.4080 - loss: 1.0786 - mae: 0.8395 - rmse: 1.0366 - smape: 1.2980 - val_ia: 0.4354 - val_loss: 0.5310 - val_mae: 0.6058 - val_rmse: 0.7200 - val_smape: 1.2394

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.4333 - loss: 1.0134 - mae: 0.8107 - rmse: 1.0047 - smape: 1.2604 - val_ia: 0.4642 - val_loss: 0.4903 - val_mae: 0.5811 - val_rmse: 0.6919 - val_smape: 1.1754

Epoch 8/128

287/287 - 1s - 4ms/step - ia: 0.4487 - loss: 0.9770 - mae: 0.7961 - rmse: 0.9866 - smape: 1.2386 - val_ia: 0.4920 - val_loss: 0.4533 - val_mae: 0.5575 - val_rmse: 0.6652 - val_smape: 1.1166

Epoch 9/128

287/287 - 1s - 4ms/step - ia: 0.4721 - loss: 0.9135 - mae: 0.7702 - rmse: 0.9539 - smape: 1.2070 - val_ia: 0.5186 - val_loss: 0.4200 - val_mae: 0.5350 - val_rmse: 0.6403 - val_smape: 1.0635

Epoch 10/128

287/287 - 1s - 4ms/step - ia: 0.4847 - loss: 0.8840 - mae: 0.7573 - rmse: 0.9384 - smape: 1.1921 - val_ia: 0.5439 - val_loss: 0.3912 - val_mae: 0.5146 - val_rmse: 0.6178 - val_smape: 1.0165

Epoch 11/128

287/287 - 1s - 3ms/step - ia: 0.5008 - loss: 0.8519 - mae: 0.7394 - rmse: 0.9210 - smape: 1.1634 - val_ia: 0.5683 - val_loss: 0.3654 - val_mae: 0.4954 - val_rmse: 0.5970 - val_smape: 0.9743

Epoch 12/128

287/287 - 1s - 5ms/step - ia: 0.5178 - loss: 0.8155 - mae: 0.7237 - rmse: 0.9014 - smape: 1.1390 - val_ia: 0.5910 - val_loss: 0.3427 - val_mae: 0.4776 - val_rmse: 0.5782 - val_smape: 0.9374

Epoch 13/128

287/287 - 1s - 3ms/step - ia: 0.5300 - loss: 0.7882 - mae: 0.7114 - rmse: 0.8859 - smape: 1.1244 - val_ia: 0.6116 - val_loss: 0.3236 - val_mae: 0.4618 - val_rmse: 0.5618 - val_smape: 0.9055

Epoch 14/128

287/287 - 1s - 3ms/step - ia: 0.5442 - loss: 0.7501 - mae: 0.6943 - rmse: 0.8645 - smape: 1.1012 - val_ia: 0.6304 - val_loss: 0.3071 - val_mae: 0.4472 - val_rmse: 0.5472 - val_smape: 0.8771

Epoch 15/128

287/287 - 1s - 4ms/step - ia: 0.5588 - loss: 0.7223 - mae: 0.6813 - rmse: 0.8482 - smape: 1.0781 - val_ia: 0.6468 - val_loss: 0.2933 - val_mae: 0.4343 - val_rmse: 0.5347 - val_smape: 0.8530

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.5675 - loss: 0.7051 - mae: 0.6716 - rmse: 0.8382 - smape: 1.0650 - val_ia: 0.6620 - val_loss: 0.2809 - val_mae: 0.4221 - val_rmse: 0.5234 - val_smape: 0.8312

Epoch 17/128

287/287 - 1s - 3ms/step - ia: 0.5757 - loss: 0.6951 - mae: 0.6668 - rmse: 0.8322 - smape: 1.0518 - val_ia: 0.6736 - val_loss: 0.2720 - val_mae: 0.4133 - val_rmse: 0.5149 - val_smape: 0.8146

Epoch 18/128

287/287 - 1s - 5ms/step - ia: 0.5808 - loss: 0.6849 - mae: 0.6627 - rmse: 0.8261 - smape: 1.0439 - val_ia: 0.6829 - val_loss: 0.2655 - val_mae: 0.4069 - val_rmse: 0.5084 - val_smape: 0.8015

Epoch 19/128

287/287 - 1s - 5ms/step - ia: 0.5929 - loss: 0.6580 - mae: 0.6485 - rmse: 0.8097 - smape: 1.0246 - val_ia: 0.6909 - val_loss: 0.2598 - val_mae: 0.4012 - val_rmse: 0.5027 - val_smape: 0.7904

Epoch 20/128

287/287 - 1s - 3ms/step - ia: 0.6001 - loss: 0.6405 - mae: 0.6403 - rmse: 0.7985 - smape: 1.0106 - val_ia: 0.6975 - val_loss: 0.2552 - val_mae: 0.3967 - val_rmse: 0.4981 - val_smape: 0.7815

Epoch 21/128

287/287 - 1s - 5ms/step - ia: 0.6052 - loss: 0.6297 - mae: 0.6338 - rmse: 0.7918 - smape: 1.0022 - val_ia: 0.7033 - val_loss: 0.2508 - val_mae: 0.3927 - val_rmse: 0.4937 - val_smape: 0.7738

Epoch 22/128

287/287 - 1s - 3ms/step - ia: 0.6082 - loss: 0.6274 - mae: 0.6322 - rmse: 0.7908 - smape: 0.9998 - val_ia: 0.7078 - val_loss: 0.2475 - val_mae: 0.3899 - val_rmse: 0.4902 - val_smape: 0.7676

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.6161 - loss: 0.6050 - mae: 0.6211 - rmse: 0.7762 - smape: 0.9833 - val_ia: 0.7118 - val_loss: 0.2447 - val_mae: 0.3877 - val_rmse: 0.4872 - val_smape: 0.7626

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.6217 - loss: 0.5916 - mae: 0.6150 - rmse: 0.7677 - smape: 0.9745 - val_ia: 0.7148 - val_loss: 0.2426 - val_mae: 0.3861 - val_rmse: 0.4849 - val_smape: 0.7587

Epoch 25/128

287/287 - 1s - 5ms/step - ia: 0.6265 - loss: 0.5809 - mae: 0.6093 - rmse: 0.7609 - smape: 0.9669 - val_ia: 0.7170 - val_loss: 0.2416 - val_mae: 0.3853 - val_rmse: 0.4834 - val_smape: 0.7557

Epoch 26/128

287/287 - 1s - 3ms/step - ia: 0.6299 - loss: 0.5722 - mae: 0.6035 - rmse: 0.7551 - smape: 0.9577 - val_ia: 0.7200 - val_loss: 0.2385 - val_mae: 0.3830 - val_rmse: 0.4804 - val_smape: 0.7516

Epoch 27/128

287/287 - 1s - 4ms/step - ia: 0.6334 - loss: 0.5600 - mae: 0.5992 - rmse: 0.7469 - smape: 0.9570 - val_ia: 0.7220 - val_loss: 0.2371 - val_mae: 0.3819 - val_rmse: 0.4786 - val_smape: 0.7487

Epoch 28/128

287/287 - 1s - 4ms/step - ia: 0.6397 - loss: 0.5456 - mae: 0.5894 - rmse: 0.7372 - smape: 0.9444 - val_ia: 0.7239 - val_loss: 0.2354 - val_mae: 0.3807 - val_rmse: 0.4766 - val_smape: 0.7459

Epoch 29/128

287/287 - 1s - 4ms/step - ia: 0.6421 - loss: 0.5410 - mae: 0.5863 - rmse: 0.7341 - smape: 0.9395 - val_ia: 0.7258 - val_loss: 0.2338 - val_mae: 0.3795 - val_rmse: 0.4747 - val_smape: 0.7433

Epoch 30/128

287/287 - 1s - 4ms/step - ia: 0.6435 - loss: 0.5367 - mae: 0.5833 - rmse: 0.7312 - smape: 0.9386 - val_ia: 0.7275 - val_loss: 0.2320 - val_mae: 0.3782 - val_rmse: 0.4726 - val_smape: 0.7407

Epoch 31/128

287/287 - 1s - 3ms/step - ia: 0.6475 - loss: 0.5205 - mae: 0.5767 - rmse: 0.7200 - smape: 0.9300 - val_ia: 0.7295 - val_loss: 0.2297 - val_mae: 0.3764 - val_rmse: 0.4702 - val_smape: 0.7378

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.6540 - loss: 0.5068 - mae: 0.5680 - rmse: 0.7105 - smape: 0.9198 - val_ia: 0.7304 - val_loss: 0.2288 - val_mae: 0.3757 - val_rmse: 0.4687 - val_smape: 0.7364

Epoch 33/128

287/287 - 1s - 5ms/step - ia: 0.6557 - loss: 0.5025 - mae: 0.5651 - rmse: 0.7076 - smape: 0.9164 - val_ia: 0.7316 - val_loss: 0.2276 - val_mae: 0.3748 - val_rmse: 0.4671 - val_smape: 0.7346

Epoch 34/128

287/287 - 1s - 3ms/step - ia: 0.6588 - loss: 0.4896 - mae: 0.5583 - rmse: 0.6985 - smape: 0.9104 - val_ia: 0.7330 - val_loss: 0.2259 - val_mae: 0.3735 - val_rmse: 0.4650 - val_smape: 0.7325

Epoch 35/128

287/287 - 1s - 4ms/step - ia: 0.6614 - loss: 0.4792 - mae: 0.5531 - rmse: 0.6909 - smape: 0.9047 - val_ia: 0.7345 - val_loss: 0.2239 - val_mae: 0.3720 - val_rmse: 0.4628 - val_smape: 0.7302

Epoch 36/128

287/287 - 1s - 2ms/step - ia: 0.6648 - loss: 0.4715 - mae: 0.5476 - rmse: 0.6852 - smape: 0.8981 - val_ia: 0.7356 - val_loss: 0.2227 - val_mae: 0.3711 - val_rmse: 0.4611 - val_smape: 0.7286

Epoch 37/128

287/287 - 1s - 5ms/step - ia: 0.6685 - loss: 0.4631 - mae: 0.5414 - rmse: 0.6793 - smape: 0.8916 - val_ia: 0.7368 - val_loss: 0.2214 - val_mae: 0.3701 - val_rmse: 0.4593 - val_smape: 0.7270

Epoch 38/128

287/287 - 1s - 2ms/step - ia: 0.6697 - loss: 0.4575 - mae: 0.5394 - rmse: 0.6751 - smape: 0.8919 - val_ia: 0.7380 - val_loss: 0.2199 - val_mae: 0.3690 - val_rmse: 0.4574 - val_smape: 0.7253

Epoch 39/128

287/287 - 1s - 2ms/step - ia: 0.6721 - loss: 0.4489 - mae: 0.5341 - rmse: 0.6687 - smape: 0.8881 - val_ia: 0.7394 - val_loss: 0.2178 - val_mae: 0.3673 - val_rmse: 0.4550 - val_smape: 0.7232

Epoch 40/128

287/287 - 1s - 2ms/step - ia: 0.6777 - loss: 0.4345 - mae: 0.5252 - rmse: 0.6578 - smape: 0.8780 - val_ia: 0.7405 - val_loss: 0.2163 - val_mae: 0.3662 - val_rmse: 0.4530 - val_smape: 0.7216

Epoch 41/128

287/287 - 2s - 6ms/step - ia: 0.6774 - loss: 0.4327 - mae: 0.5243 - rmse: 0.6565 - smape: 0.8773 - val_ia: 0.7425 - val_loss: 0.2133 - val_mae: 0.3638 - val_rmse: 0.4500 - val_smape: 0.7184

Epoch 42/128

287/287 - 1s - 5ms/step - ia: 0.6830 - loss: 0.4195 - mae: 0.5175 - rmse: 0.6464 - smape: 0.8681 - val_ia: 0.7431 - val_loss: 0.2122 - val_mae: 0.3629 - val_rmse: 0.4483 - val_smape: 0.7172

Epoch 43/128

287/287 - 1s - 4ms/step - ia: 0.6864 - loss: 0.4108 - mae: 0.5104 - rmse: 0.6396 - smape: 0.8602 - val_ia: 0.7440 - val_loss: 0.2111 - val_mae: 0.3621 - val_rmse: 0.4466 - val_smape: 0.7158

Epoch 44/128

287/287 - 1s - 5ms/step - ia: 0.6870 - loss: 0.4083 - mae: 0.5093 - rmse: 0.6377 - smape: 0.8594 - val_ia: 0.7447 - val_loss: 0.2101 - val_mae: 0.3614 - val_rmse: 0.4451 - val_smape: 0.7145

Epoch 45/128

287/287 - 1s - 5ms/step - ia: 0.6911 - loss: 0.3999 - mae: 0.5036 - rmse: 0.6311 - smape: 0.8497 - val_ia: 0.7457 - val_loss: 0.2084 - val_mae: 0.3601 - val_rmse: 0.4430 - val_smape: 0.7128

Epoch 46/128

287/287 - 1s - 4ms/step - ia: 0.6945 - loss: 0.3889 - mae: 0.4960 - rmse: 0.6224 - smape: 0.8450 - val_ia: 0.7475 - val_loss: 0.2053 - val_mae: 0.3575 - val_rmse: 0.4398 - val_smape: 0.7094

Epoch 47/128

287/287 - 1s - 3ms/step - ia: 0.6959 - loss: 0.3855 - mae: 0.4934 - rmse: 0.6199 - smape: 0.8419 - val_ia: 0.7483 - val_loss: 0.2041 - val_mae: 0.3566 - val_rmse: 0.4381 - val_smape: 0.7083

Epoch 48/128

287/287 - 2s - 5ms/step - ia: 0.6969 - loss: 0.3807 - mae: 0.4908 - rmse: 0.6158 - smape: 0.8407 - val_ia: 0.7490 - val_loss: 0.2037 - val_mae: 0.3563 - val_rmse: 0.4370 - val_smape: 0.7074

Epoch 49/128

287/287 - 1s - 4ms/step - ia: 0.7003 - loss: 0.3727 - mae: 0.4857 - rmse: 0.6094 - smape: 0.8342 - val_ia: 0.7503 - val_loss: 0.2017 - val_mae: 0.3546 - val_rmse: 0.4346 - val_smape: 0.7048

Epoch 50/128

287/287 - 1s - 5ms/step - ia: 0.7038 - loss: 0.3660 - mae: 0.4809 - rmse: 0.6038 - smape: 0.8241 - val_ia: 0.7510 - val_loss: 0.2005 - val_mae: 0.3537 - val_rmse: 0.4329 - val_smape: 0.7035

Epoch 51/128

287/287 - 1s - 5ms/step - ia: 0.7077 - loss: 0.3552 - mae: 0.4737 - rmse: 0.5947 - smape: 0.8201 - val_ia: 0.7523 - val_loss: 0.1983 - val_mae: 0.3518 - val_rmse: 0.4303 - val_smape: 0.7011

Epoch 52/128

287/287 - 1s - 5ms/step - ia: 0.7112 - loss: 0.3477 - mae: 0.4684 - rmse: 0.5882 - smape: 0.8110 - val_ia: 0.7533 - val_loss: 0.1968 - val_mae: 0.3506 - val_rmse: 0.4284 - val_smape: 0.6992

Epoch 53/128

287/287 - 1s - 5ms/step - ia: 0.7111 - loss: 0.3485 - mae: 0.4689 - rmse: 0.5893 - smape: 0.8149 - val_ia: 0.7539 - val_loss: 0.1956 - val_mae: 0.3496 - val_rmse: 0.4266 - val_smape: 0.6978

Epoch 54/128

287/287 - 1s - 4ms/step - ia: 0.7131 - loss: 0.3422 - mae: 0.4640 - rmse: 0.5838 - smape: 0.8100 - val_ia: 0.7553 - val_loss: 0.1934 - val_mae: 0.3478 - val_rmse: 0.4241 - val_smape: 0.6953

Epoch 55/128

287/287 - 1s - 3ms/step - ia: 0.7182 - loss: 0.3306 - mae: 0.4569 - rmse: 0.5738 - smape: 0.8039 - val_ia: 0.7563 - val_loss: 0.1914 - val_mae: 0.3461 - val_rmse: 0.4218 - val_smape: 0.6932

Epoch 56/128

287/287 - 1s - 4ms/step - ia: 0.7198 - loss: 0.3262 - mae: 0.4531 - rmse: 0.5699 - smape: 0.7950 - val_ia: 0.7574 - val_loss: 0.1899 - val_mae: 0.3447 - val_rmse: 0.4198 - val_smape: 0.6912

Epoch 57/128

287/287 - 1s - 5ms/step - ia: 0.7218 - loss: 0.3201 - mae: 0.4490 - rmse: 0.5646 - smape: 0.7915 - val_ia: 0.7587 - val_loss: 0.1880 - val_mae: 0.3431 - val_rmse: 0.4176 - val_smape: 0.6887

Epoch 58/128

287/287 - 1s - 4ms/step - ia: 0.7229 - loss: 0.3179 - mae: 0.4479 - rmse: 0.5627 - smape: 0.7899 - val_ia: 0.7597 - val_loss: 0.1865 - val_mae: 0.3418 - val_rmse: 0.4156 - val_smape: 0.6866

Epoch 59/128

287/287 - 1s - 3ms/step - ia: 0.7250 - loss: 0.3144 - mae: 0.4443 - rmse: 0.5595 - smape: 0.7862 - val_ia: 0.7602 - val_loss: 0.1859 - val_mae: 0.3412 - val_rmse: 0.4144 - val_smape: 0.6854

Epoch 60/128

287/287 - 1s - 4ms/step - ia: 0.7279 - loss: 0.3067 - mae: 0.4391 - rmse: 0.5526 - smape: 0.7800 - val_ia: 0.7610 - val_loss: 0.1847 - val_mae: 0.3402 - val_rmse: 0.4127 - val_smape: 0.6835

Epoch 61/128

287/287 - 1s - 3ms/step - ia: 0.7313 - loss: 0.2988 - mae: 0.4339 - rmse: 0.5456 - smape: 0.7728 - val_ia: 0.7621 - val_loss: 0.1829 - val_mae: 0.3386 - val_rmse: 0.4105 - val_smape: 0.6812

Epoch 62/128

287/287 - 1s - 5ms/step - ia: 0.7337 - loss: 0.2950 - mae: 0.4307 - rmse: 0.5418 - smape: 0.7643 - val_ia: 0.7632 - val_loss: 0.1811 - val_mae: 0.3370 - val_rmse: 0.4083 - val_smape: 0.6790

Epoch 63/128

287/287 - 1s - 5ms/step - ia: 0.7355 - loss: 0.2898 - mae: 0.4266 - rmse: 0.5371 - smape: 0.7663 - val_ia: 0.7640 - val_loss: 0.1802 - val_mae: 0.3361 - val_rmse: 0.4069 - val_smape: 0.6773

Epoch 64/128

287/287 - 1s - 5ms/step - ia: 0.7359 - loss: 0.2877 - mae: 0.4257 - rmse: 0.5352 - smape: 0.7653 - val_ia: 0.7655 - val_loss: 0.1778 - val_mae: 0.3339 - val_rmse: 0.4041 - val_smape: 0.6744

Epoch 65/128

287/287 - 1s - 5ms/step - ia: 0.7368 - loss: 0.2870 - mae: 0.4244 - rmse: 0.5347 - smape: 0.7601 - val_ia: 0.7672 - val_loss: 0.1749 - val_mae: 0.3312 - val_rmse: 0.4010 - val_smape: 0.6713

Epoch 66/128

287/287 - 1s - 4ms/step - ia: 0.7424 - loss: 0.2775 - mae: 0.4163 - rmse: 0.5255 - smape: 0.7476 - val_ia: 0.7674 - val_loss: 0.1743 - val_mae: 0.3307 - val_rmse: 0.3999 - val_smape: 0.6702

Epoch 67/128

287/287 - 1s - 3ms/step - ia: 0.7428 - loss: 0.2735 - mae: 0.4147 - rmse: 0.5221 - smape: 0.7513 - val_ia: 0.7680 - val_loss: 0.1735 - val_mae: 0.3300 - val_rmse: 0.3985 - val_smape: 0.6690

Epoch 68/128

287/287 - 1s - 3ms/step - ia: 0.7465 - loss: 0.2660 - mae: 0.4085 - rmse: 0.5145 - smape: 0.7429 - val_ia: 0.7690 - val_loss: 0.1721 - val_mae: 0.3287 - val_rmse: 0.3967 - val_smape: 0.6673

Epoch 69/128

287/287 - 1s - 3ms/step - ia: 0.7473 - loss: 0.2636 - mae: 0.4060 - rmse: 0.5125 - smape: 0.7420 - val_ia: 0.7709 - val_loss: 0.1694 - val_mae: 0.3261 - val_rmse: 0.3937 - val_smape: 0.6641

Epoch 70/128

287/287 - 1s - 3ms/step - ia: 0.7504 - loss: 0.2593 - mae: 0.4030 - rmse: 0.5081 - smape: 0.7349 - val_ia: 0.7717 - val_loss: 0.1682 - val_mae: 0.3249 - val_rmse: 0.3920 - val_smape: 0.6625

Epoch 71/128

287/287 - 1s - 3ms/step - ia: 0.7520 - loss: 0.2558 - mae: 0.3994 - rmse: 0.5049 - smape: 0.7302 - val_ia: 0.7733 - val_loss: 0.1655 - val_mae: 0.3225 - val_rmse: 0.3891 - val_smape: 0.6595

Epoch 72/128

287/287 - 1s - 3ms/step - ia: 0.7538 - loss: 0.2531 - mae: 0.3975 - rmse: 0.5019 - smape: 0.7262 - val_ia: 0.7742 - val_loss: 0.1637 - val_mae: 0.3207 - val_rmse: 0.3868 - val_smape: 0.6574

Epoch 73/128

287/287 - 1s - 5ms/step - ia: 0.7558 - loss: 0.2486 - mae: 0.3940 - rmse: 0.4974 - smape: 0.7202 - val_ia: 0.7753 - val_loss: 0.1621 - val_mae: 0.3191 - val_rmse: 0.3848 - val_smape: 0.6553

Epoch 74/128

287/287 - 1s - 3ms/step - ia: 0.7571 - loss: 0.2443 - mae: 0.3910 - rmse: 0.4932 - smape: 0.7223 - val_ia: 0.7762 - val_loss: 0.1608 - val_mae: 0.3179 - val_rmse: 0.3831 - val_smape: 0.6534

Epoch 75/128

287/287 - 1s - 5ms/step - ia: 0.7577 - loss: 0.2440 - mae: 0.3906 - rmse: 0.4930 - smape: 0.7188 - val_ia: 0.7773 - val_loss: 0.1592 - val_mae: 0.3163 - val_rmse: 0.3811 - val_smape: 0.6513

Epoch 76/128

287/287 - 2s - 5ms/step - ia: 0.7620 - loss: 0.2358 - mae: 0.3833 - rmse: 0.4844 - smape: 0.7072 - val_ia: 0.7781 - val_loss: 0.1580 - val_mae: 0.3152 - val_rmse: 0.3795 - val_smape: 0.6495

Epoch 77/128

287/287 - 1s - 5ms/step - ia: 0.7627 - loss: 0.2342 - mae: 0.3822 - rmse: 0.4831 - smape: 0.7085 - val_ia: 0.7788 - val_loss: 0.1568 - val_mae: 0.3140 - val_rmse: 0.3778 - val_smape: 0.6478

Epoch 78/128

287/287 - 2s - 5ms/step - ia: 0.7657 - loss: 0.2298 - mae: 0.3774 - rmse: 0.4783 - smape: 0.6971 - val_ia: 0.7801 - val_loss: 0.1549 - val_mae: 0.3122 - val_rmse: 0.3755 - val_smape: 0.6455

Epoch 79/128

287/287 - 1s - 3ms/step - ia: 0.7667 - loss: 0.2264 - mae: 0.3760 - rmse: 0.4746 - smape: 0.7003 - val_ia: 0.7818 - val_loss: 0.1522 - val_mae: 0.3095 - val_rmse: 0.3725 - val_smape: 0.6425

Epoch 80/128

287/287 - 1s - 4ms/step - ia: 0.7688 - loss: 0.2235 - mae: 0.3727 - rmse: 0.4718 - smape: 0.6947 - val_ia: 0.7826 - val_loss: 0.1508 - val_mae: 0.3081 - val_rmse: 0.3707 - val_smape: 0.6407

Epoch 81/128

287/287 - 1s - 3ms/step - ia: 0.7700 - loss: 0.2213 - mae: 0.3711 - rmse: 0.4694 - smape: 0.6926 - val_ia: 0.7836 - val_loss: 0.1491 - val_mae: 0.3064 - val_rmse: 0.3686 - val_smape: 0.6386

Epoch 82/128

287/287 - 1s - 5ms/step - ia: 0.7734 - loss: 0.2153 - mae: 0.3653 - rmse: 0.4628 - smape: 0.6867 - val_ia: 0.7843 - val_loss: 0.1482 - val_mae: 0.3055 - val_rmse: 0.3672 - val_smape: 0.6371

Epoch 83/128

287/287 - 1s - 5ms/step - ia: 0.7728 - loss: 0.2154 - mae: 0.3666 - rmse: 0.4629 - smape: 0.6850 - val_ia: 0.7854 - val_loss: 0.1463 - val_mae: 0.3035 - val_rmse: 0.3649 - val_smape: 0.6347

Epoch 84/128

287/287 - 1s - 3ms/step - ia: 0.7752 - loss: 0.2106 - mae: 0.3621 - rmse: 0.4578 - smape: 0.6832 - val_ia: 0.7863 - val_loss: 0.1450 - val_mae: 0.3023 - val_rmse: 0.3632 - val_smape: 0.6330

Epoch 85/128

287/287 - 1s - 4ms/step - ia: 0.7753 - loss: 0.2122 - mae: 0.3623 - rmse: 0.4595 - smape: 0.6791 - val_ia: 0.7872 - val_loss: 0.1435 - val_mae: 0.3007 - val_rmse: 0.3612 - val_smape: 0.6310

Epoch 86/128

287/287 - 1s - 4ms/step - ia: 0.7798 - loss: 0.2027 - mae: 0.3547 - rmse: 0.4493 - smape: 0.6735 - val_ia: 0.7885 - val_loss: 0.1416 - val_mae: 0.2988 - val_rmse: 0.3590 - val_smape: 0.6286

Epoch 87/128

287/287 - 1s - 5ms/step - ia: 0.7798 - loss: 0.2028 - mae: 0.3548 - rmse: 0.4493 - smape: 0.6719 - val_ia: 0.7898 - val_loss: 0.1397 - val_mae: 0.2968 - val_rmse: 0.3566 - val_smape: 0.6262

Epoch 88/128

287/287 - 1s - 5ms/step - ia: 0.7816 - loss: 0.1998 - mae: 0.3526 - rmse: 0.4461 - smape: 0.6657 - val_ia: 0.7904 - val_loss: 0.1388 - val_mae: 0.2958 - val_rmse: 0.3552 - val_smape: 0.6247

Epoch 89/128

287/287 - 1s - 5ms/step - ia: 0.7838 - loss: 0.1966 - mae: 0.3487 - rmse: 0.4423 - smape: 0.6614 - val_ia: 0.7918 - val_loss: 0.1367 - val_mae: 0.2937 - val_rmse: 0.3527 - val_smape: 0.6221

Epoch 90/128

287/287 - 1s - 4ms/step - ia: 0.7845 - loss: 0.1950 - mae: 0.3472 - rmse: 0.4407 - smape: 0.6633 - val_ia: 0.7936 - val_loss: 0.1341 - val_mae: 0.2909 - val_rmse: 0.3497 - val_smape: 0.6188

Epoch 91/128

287/287 - 1s - 4ms/step - ia: 0.7861 - loss: 0.1925 - mae: 0.3449 - rmse: 0.4377 - smape: 0.6605 - val_ia: 0.7941 - val_loss: 0.1332 - val_mae: 0.2899 - val_rmse: 0.3483 - val_smape: 0.6173

Epoch 92/128

287/287 - 1s - 4ms/step - ia: 0.7874 - loss: 0.1901 - mae: 0.3432 - rmse: 0.4350 - smape: 0.6540 - val_ia: 0.7955 - val_loss: 0.1312 - val_mae: 0.2877 - val_rmse: 0.3458 - val_smape: 0.6147

Epoch 93/128

287/287 - 1s - 3ms/step - ia: 0.7879 - loss: 0.1892 - mae: 0.3421 - rmse: 0.4340 - smape: 0.6522 - val_ia: 0.7966 - val_loss: 0.1296 - val_mae: 0.2860 - val_rmse: 0.3438 - val_smape: 0.6125

Epoch 94/128

287/287 - 1s - 3ms/step - ia: 0.7906 - loss: 0.1850 - mae: 0.3381 - rmse: 0.4291 - smape: 0.6472 - val_ia: 0.7976 - val_loss: 0.1280 - val_mae: 0.2843 - val_rmse: 0.3417 - val_smape: 0.6104

Epoch 95/128

287/287 - 1s - 5ms/step - ia: 0.7900 - loss: 0.1859 - mae: 0.3391 - rmse: 0.4301 - smape: 0.6500 - val_ia: 0.7979 - val_loss: 0.1275 - val_mae: 0.2837 - val_rmse: 0.3407 - val_smape: 0.6095

Epoch 96/128

287/287 - 1s - 4ms/step - ia: 0.7921 - loss: 0.1815 - mae: 0.3351 - rmse: 0.4251 - smape: 0.6469 - val_ia: 0.8000 - val_loss: 0.1246 - val_mae: 0.2806 - val_rmse: 0.3374 - val_smape: 0.6057

Epoch 97/128

287/287 - 1s - 5ms/step - ia: 0.7945 - loss: 0.1785 - mae: 0.3317 - rmse: 0.4215 - smape: 0.6398 - val_ia: 0.8002 - val_loss: 0.1243 - val_mae: 0.2802 - val_rmse: 0.3366 - val_smape: 0.6051

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 4s - 13ms/step - ia: 0.8321 - loss: 0.3452 - mae: 0.3019 - rmse: 0.3913 - smape: 0.5207 - val_ia: 0.9334 - val_loss: 0.0144 - val_mae: 0.0907 - val_rmse: 0.1190 - val_smape: 0.2718

Epoch 2/128

287/287 - 1s - 4ms/step - ia: 0.9200 - loss: 0.0313 - mae: 0.1309 - rmse: 0.1754 - smape: 0.3068 - val_ia: 0.9343 - val_loss: 0.0121 - val_mae: 0.0878 - val_rmse: 0.1078 - val_smape: 0.2533

Epoch 3/128

287/287 - 2s - 8ms/step - ia: 0.9313 - loss: 0.0235 - mae: 0.1123 - rmse: 0.1524 - smape: 0.2645 - val_ia: 0.9419 - val_loss: 0.0100 - val_mae: 0.0774 - val_rmse: 0.0980 - val_smape: 0.2057

Epoch 4/128

287/287 - 2s - 6ms/step - ia: 0.9347 - loss: 0.0214 - mae: 0.1069 - rmse: 0.1455 - smape: 0.2494 - val_ia: 0.9510 - val_loss: 0.0077 - val_mae: 0.0656 - val_rmse: 0.0866 - val_smape: 0.1690

Epoch 5/128

287/287 - 2s - 6ms/step - ia: 0.9377 - loss: 0.0198 - mae: 0.1020 - rmse: 0.1397 - smape: 0.2358 - val_ia: 0.9595 - val_loss: 0.0054 - val_mae: 0.0549 - val_rmse: 0.0727 - val_smape: 0.1728

Epoch 6/128

287/287 - 2s - 8ms/step - ia: 0.9376 - loss: 0.0198 - mae: 0.1022 - rmse: 0.1395 - smape: 0.2317 - val_ia: 0.9505 - val_loss: 0.0076 - val_mae: 0.0666 - val_rmse: 0.0853 - val_smape: 0.2191

Epoch 7/128

287/287 - 2s - 8ms/step - ia: 0.9395 - loss: 0.0188 - mae: 0.0991 - rmse: 0.1361 - smape: 0.2265 - val_ia: 0.9651 - val_loss: 0.0046 - val_mae: 0.0476 - val_rmse: 0.0670 - val_smape: 0.1436

Epoch 8/128

287/287 - 1s - 5ms/step - ia: 0.9403 - loss: 0.0182 - mae: 0.0978 - rmse: 0.1341 - smape: 0.2205 - val_ia: 0.9458 - val_loss: 0.0082 - val_mae: 0.0722 - val_rmse: 0.0878 - val_smape: 0.2092

Epoch 9/128

287/287 - 1s - 5ms/step - ia: 0.9392 - loss: 0.0190 - mae: 0.0997 - rmse: 0.1365 - smape: 0.2220 - val_ia: 0.9591 - val_loss: 0.0052 - val_mae: 0.0559 - val_rmse: 0.0714 - val_smape: 0.1718

Epoch 10/128

287/287 - 2s - 8ms/step - ia: 0.9417 - loss: 0.0176 - mae: 0.0955 - rmse: 0.1317 - smape: 0.2135 - val_ia: 0.9672 - val_loss: 0.0040 - val_mae: 0.0445 - val_rmse: 0.0618 - val_smape: 0.1356

Epoch 11/128

287/287 - 1s - 4ms/step - ia: 0.9417 - loss: 0.0177 - mae: 0.0956 - rmse: 0.1319 - smape: 0.2135 - val_ia: 0.9470 - val_loss: 0.0076 - val_mae: 0.0712 - val_rmse: 0.0856 - val_smape: 0.2179

Epoch 12/128

287/287 - 2s - 7ms/step - ia: 0.9415 - loss: 0.0177 - mae: 0.0958 - rmse: 0.1322 - smape: 0.2130 - val_ia: 0.9619 - val_loss: 0.0048 - val_mae: 0.0526 - val_rmse: 0.0688 - val_smape: 0.1550

Epoch 13/128

287/287 - 3s - 9ms/step - ia: 0.9415 - loss: 0.0180 - mae: 0.0958 - rmse: 0.1329 - smape: 0.2121 - val_ia: 0.9607 - val_loss: 0.0053 - val_mae: 0.0528 - val_rmse: 0.0716 - val_smape: 0.1357

Epoch 14/128

287/287 - 3s - 9ms/step - ia: 0.9409 - loss: 0.0182 - mae: 0.0967 - rmse: 0.1338 - smape: 0.2136 - val_ia: 0.9657 - val_loss: 0.0042 - val_mae: 0.0471 - val_rmse: 0.0639 - val_smape: 0.1407

Epoch 15/128

287/287 - 1s - 4ms/step - ia: 0.9414 - loss: 0.0180 - mae: 0.0960 - rmse: 0.1331 - smape: 0.2102 - val_ia: 0.9711 - val_loss: 0.0034 - val_mae: 0.0397 - val_rmse: 0.0572 - val_smape: 0.1203

Epoch 16/128

287/287 - 1s - 4ms/step - ia: 0.9419 - loss: 0.0177 - mae: 0.0951 - rmse: 0.1320 - smape: 0.2083 - val_ia: 0.9646 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0646 - val_smape: 0.1400

Epoch 17/128

287/287 - 1s - 4ms/step - ia: 0.9411 - loss: 0.0183 - mae: 0.0965 - rmse: 0.1340 - smape: 0.2101 - val_ia: 0.9616 - val_loss: 0.0050 - val_mae: 0.0513 - val_rmse: 0.0697 - val_smape: 0.1423

Epoch 18/128

287/287 - 2s - 6ms/step - ia: 0.9403 - loss: 0.0188 - mae: 0.0979 - rmse: 0.1353 - smape: 0.2107 - val_ia: 0.9711 - val_loss: 0.0033 - val_mae: 0.0393 - val_rmse: 0.0565 - val_smape: 0.1233

Epoch 19/128

287/287 - 1s - 4ms/step - ia: 0.9399 - loss: 0.0190 - mae: 0.0985 - rmse: 0.1363 - smape: 0.2130 - val_ia: 0.9279 - val_loss: 0.0138 - val_mae: 0.0947 - val_rmse: 0.1159 - val_smape: 0.1970

Epoch 20/128

287/287 - 1s - 5ms/step - ia: 0.9395 - loss: 0.0194 - mae: 0.0991 - rmse: 0.1375 - smape: 0.2118 - val_ia: 0.9648 - val_loss: 0.0041 - val_mae: 0.0479 - val_rmse: 0.0634 - val_smape: 0.1452

Epoch 21/128

287/287 - 1s - 3ms/step - ia: 0.9401 - loss: 0.0190 - mae: 0.0981 - rmse: 0.1362 - smape: 0.2101 - val_ia: 0.9519 - val_loss: 0.0071 - val_mae: 0.0646 - val_rmse: 0.0835 - val_smape: 0.1555

Epoch 22/128

287/287 - 1s - 4ms/step - ia: 0.9399 - loss: 0.0190 - mae: 0.0984 - rmse: 0.1361 - smape: 0.2114 - val_ia: 0.9720 - val_loss: 0.0031 - val_mae: 0.0384 - val_rmse: 0.0549 - val_smape: 0.1216

Epoch 23/128

287/287 - 1s - 3ms/step - ia: 0.9377 - loss: 0.0206 - mae: 0.1019 - rmse: 0.1415 - smape: 0.2138 - val_ia: 0.8999 - val_loss: 0.0243 - val_mae: 0.1278 - val_rmse: 0.1548 - val_smape: 0.2321

Epoch 24/128

287/287 - 2s - 5ms/step - ia: 0.9376 - loss: 0.0207 - mae: 0.1021 - rmse: 0.1416 - smape: 0.2150 - val_ia: 0.9693 - val_loss: 0.0035 - val_mae: 0.0426 - val_rmse: 0.0582 - val_smape: 0.1187

Epoch 25/128

287/287 - 1s - 4ms/step - ia: 0.9398 - loss: 0.0194 - mae: 0.0986 - rmse: 0.1373 - smape: 0.2097 - val_ia: 0.9617 - val_loss: 0.0047 - val_mae: 0.0532 - val_rmse: 0.0682 - val_smape: 0.1474

Epoch 26/128

287/287 - 1s - 3ms/step - ia: 0.9388 - loss: 0.0197 - mae: 0.1002 - rmse: 0.1389 - smape: 0.2116 - val_ia: 0.9360 - val_loss: 0.0109 - val_mae: 0.0841 - val_rmse: 0.1036 - val_smape: 0.1796

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.9406 - loss: 0.0186 - mae: 0.0972 - rmse: 0.1349 - smape: 0.2072 - val_ia: 0.9497 - val_loss: 0.0079 - val_mae: 0.0705 - val_rmse: 0.0883 - val_smape: 0.1998

Epoch 28/128

287/287 - 1s - 3ms/step - ia: 0.9368 - loss: 0.0210 - mae: 0.1034 - rmse: 0.1430 - smape: 0.2171 - val_ia: 0.9591 - val_loss: 0.0051 - val_mae: 0.0557 - val_rmse: 0.0704 - val_smape: 0.1795

Epoch 29/128

287/287 - 1s - 4ms/step - ia: 0.9388 - loss: 0.0199 - mae: 0.1002 - rmse: 0.1392 - smape: 0.2099 - val_ia: 0.9656 - val_loss: 0.0038 - val_mae: 0.0466 - val_rmse: 0.0606 - val_smape: 0.1486

Epoch 30/128

287/287 - 1s - 5ms/step - ia: 0.9394 - loss: 0.0193 - mae: 0.0991 - rmse: 0.1373 - smape: 0.2111 - val_ia: 0.9686 - val_loss: 0.0036 - val_mae: 0.0427 - val_rmse: 0.0590 - val_smape: 0.1326

Epoch 31/128

287/287 - 1s - 3ms/step - ia: 0.9398 - loss: 0.0193 - mae: 0.0985 - rmse: 0.1371 - smape: 0.2101 - val_ia: 0.9698 - val_loss: 0.0035 - val_mae: 0.0414 - val_rmse: 0.0583 - val_smape: 0.1334

Epoch 32/128

287/287 - 2s - 5ms/step - ia: 0.9401 - loss: 0.0191 - mae: 0.0981 - rmse: 0.1364 - smape: 0.2076 - val_ia: 0.9693 - val_loss: 0.0034 - val_mae: 0.0425 - val_rmse: 0.0578 - val_smape: 0.1265

Epoch 33/128

287/287 - 1s - 3ms/step - ia: 0.9375 - loss: 0.0208 - mae: 0.1022 - rmse: 0.1421 - smape: 0.2143 - val_ia: 0.9621 - val_loss: 0.0046 - val_mae: 0.0511 - val_rmse: 0.0660 - val_smape: 0.1471

Epoch 34/128

287/287 - 1s - 3ms/step - ia: 0.9415 - loss: 0.0182 - mae: 0.0957 - rmse: 0.1336 - smape: 0.2036 - val_ia: 0.9691 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0578 - val_smape: 0.1305

Epoch 35/128

287/287 - 1s - 3ms/step - ia: 0.9349 - loss: 0.0226 - mae: 0.1063 - rmse: 0.1468 - smape: 0.2183 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0422 - val_rmse: 0.0572 - val_smape: 0.1421

Epoch 36/128

287/287 - 1s - 4ms/step - ia: 0.9407 - loss: 0.0187 - mae: 0.0972 - rmse: 0.1349 - smape: 0.2072 - val_ia: 0.9664 - val_loss: 0.0039 - val_mae: 0.0462 - val_rmse: 0.0616 - val_smape: 0.1488

Epoch 37/128

287/287 - 1s - 5ms/step - ia: 0.9419 - loss: 0.0179 - mae: 0.0952 - rmse: 0.1325 - smape: 0.2057 - val_ia: 0.9657 - val_loss: 0.0041 - val_mae: 0.0468 - val_rmse: 0.0633 - val_smape: 0.1428

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 22.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 26s 164ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 58%|█████▊    | 7/12 [59:28<28:48, 345.61s/trial, best loss: 0.0018056012500971394]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 18s - 4ms/step - ia: 0.8595 - loss: 0.0749 - mae: 0.2058 - rmse: 0.2545 - smape: 0.4355 - val_ia: 0.5049 - val_loss: 0.0153 - val_mae: 0.0950 - val_rmse: 0.1058 - val_smape: 0.2283

Epoch 2/128

4586/4586 - 13s - 3ms/step - ia: 0.8805 - loss: 0.0509 - mae: 0.1744 - rmse: 0.2157 - smape: 0.4025 - val_ia: 0.4743 - val_loss: 0.0202 - val_mae: 0.1135 - val_rmse: 0.1235 - val_smape: 0.3359

Epoch 3/128

4586/4586 - 20s - 4ms/step - ia: 0.8847 - loss: 0.0478 - mae: 0.1685 - rmse: 0.2086 - smape: 0.3962 - val_ia: 0.4775 - val_loss: 0.0182 - val_mae: 0.1086 - val_rmse: 0.1197 - val_smape: 0.3100

Epoch 4/128

4586/4586 - 12s - 3ms/step - ia: 0.8859 - loss: 0.0464 - mae: 0.1666 - rmse: 0.2061 - smape: 0.3937 - val_ia: 0.4958 - val_loss: 0.0165 - val_mae: 0.1004 - val_rmse: 0.1102 - val_smape: 0.2559

Epoch 5/128

4586/4586 - 12s - 3ms/step - ia: 0.8868 - loss: 0.0456 - mae: 0.1651 - rmse: 0.2040 - smape: 0.3934 - val_ia: 0.5328 - val_loss: 0.0118 - val_mae: 0.0836 - val_rmse: 0.0946 - val_smape: 0.2256

Epoch 6/128

4586/4586 - 11s - 2ms/step - ia: 0.8880 - loss: 0.0450 - mae: 0.1640 - rmse: 0.2029 - smape: 0.3901 - val_ia: 0.5503 - val_loss: 0.0133 - val_mae: 0.0854 - val_rmse: 0.0960 - val_smape: 0.2093

Epoch 7/128

4586/4586 - 14s - 3ms/step - ia: 0.8875 - loss: 0.0444 - mae: 0.1635 - rmse: 0.2017 - smape: 0.3906 - val_ia: 0.4628 - val_loss: 0.0197 - val_mae: 0.1151 - val_rmse: 0.1256 - val_smape: 0.3077

Epoch 8/128

4586/4586 - 19s - 4ms/step - ia: 0.8883 - loss: 0.0441 - mae: 0.1623 - rmse: 0.2006 - smape: 0.3897 - val_ia: 0.5077 - val_loss: 0.0142 - val_mae: 0.0930 - val_rmse: 0.1038 - val_smape: 0.2396

Epoch 9/128

4586/4586 - 12s - 3ms/step - ia: 0.8877 - loss: 0.0441 - mae: 0.1634 - rmse: 0.2012 - smape: 0.3933 - val_ia: 0.5020 - val_loss: 0.0157 - val_mae: 0.0965 - val_rmse: 0.1071 - val_smape: 0.2239

Epoch 10/128

4586/4586 - 20s - 4ms/step - ia: 0.8893 - loss: 0.0434 - mae: 0.1612 - rmse: 0.1991 - smape: 0.3893 - val_ia: 0.4828 - val_loss: 0.0171 - val_mae: 0.1041 - val_rmse: 0.1161 - val_smape: 0.2487

Epoch 11/128

4586/4586 - 12s - 3ms/step - ia: 0.8891 - loss: 0.0438 - mae: 0.1617 - rmse: 0.2004 - smape: 0.3907 - val_ia: 0.4436 - val_loss: 0.0218 - val_mae: 0.1197 - val_rmse: 0.1304 - val_smape: 0.3937

Epoch 12/128

4586/4586 - 12s - 3ms/step - ia: 0.8892 - loss: 0.0432 - mae: 0.1608 - rmse: 0.1991 - smape: 0.3883 - val_ia: 0.5316 - val_loss: 0.0135 - val_mae: 0.0890 - val_rmse: 0.1009 - val_smape: 0.2131

Epoch 13/128

4586/4586 - 12s - 3ms/step - ia: 0.8905 - loss: 0.0429 - mae: 0.1599 - rmse: 0.1981 - smape: 0.3869 - val_ia: 0.4662 - val_loss: 0.0199 - val_mae: 0.1122 - val_rmse: 0.1222 - val_smape: 0.2804

Epoch 14/128

4586/4586 - 20s - 4ms/step - ia: 0.8902 - loss: 0.0427 - mae: 0.1599 - rmse: 0.1977 - smape: 0.3879 - val_ia: 0.5334 - val_loss: 0.0114 - val_mae: 0.0837 - val_rmse: 0.0957 - val_smape: 0.2318

Epoch 15/128

4586/4586 - 19s - 4ms/step - ia: 0.8918 - loss: 0.0415 - mae: 0.1578 - rmse: 0.1949 - smape: 0.3856 - val_ia: 0.5187 - val_loss: 0.0139 - val_mae: 0.0910 - val_rmse: 0.1019 - val_smape: 0.2267

Epoch 16/128

4586/4586 - 11s - 2ms/step - ia: 0.8905 - loss: 0.0422 - mae: 0.1590 - rmse: 0.1967 - smape: 0.3875 - val_ia: 0.4633 - val_loss: 0.0187 - val_mae: 0.1118 - val_rmse: 0.1234 - val_smape: 0.3300

Epoch 17/128

4586/4586 - 11s - 2ms/step - ia: 0.8912 - loss: 0.0418 - mae: 0.1583 - rmse: 0.1957 - smape: 0.3849 - val_ia: 0.4668 - val_loss: 0.0199 - val_mae: 0.1134 - val_rmse: 0.1239 - val_smape: 0.3126

Epoch 18/128

4586/4586 - 22s - 5ms/step - ia: 0.8904 - loss: 0.0418 - mae: 0.1582 - rmse: 0.1956 - smape: 0.3874 - val_ia: 0.5072 - val_loss: 0.0193 - val_mae: 0.1029 - val_rmse: 0.1148 - val_smape: 0.2833

Epoch 19/128

4586/4586 - 12s - 3ms/step - ia: 0.8911 - loss: 0.0420 - mae: 0.1593 - rmse: 0.1959 - smape: 0.3894 - val_ia: 0.4952 - val_loss: 0.0175 - val_mae: 0.1000 - val_rmse: 0.1125 - val_smape: 0.2455

Epoch 20/128

4586/4586 - 12s - 3ms/step - ia: 0.8900 - loss: 0.0421 - mae: 0.1591 - rmse: 0.1964 - smape: 0.3888 - val_ia: 0.5489 - val_loss: 0.0103 - val_mae: 0.0766 - val_rmse: 0.0883 - val_smape: 0.2054

Epoch 21/128

4586/4586 - 12s - 3ms/step - ia: 0.8916 - loss: 0.0416 - mae: 0.1579 - rmse: 0.1951 - smape: 0.3857 - val_ia: 0.4002 - val_loss: 0.0269 - val_mae: 0.1418 - val_rmse: 0.1529 - val_smape: 0.3651

Epoch 22/128

4586/4586 - 19s - 4ms/step - ia: 0.8913 - loss: 0.0414 - mae: 0.1573 - rmse: 0.1947 - smape: 0.3850 - val_ia: 0.5083 - val_loss: 0.0119 - val_mae: 0.0863 - val_rmse: 0.0979 - val_smape: 0.2154

Epoch 23/128

4586/4586 - 12s - 3ms/step - ia: 0.8916 - loss: 0.0418 - mae: 0.1582 - rmse: 0.1952 - smape: 0.3834 - val_ia: 0.4161 - val_loss: 0.0269 - val_mae: 0.1378 - val_rmse: 0.1497 - val_smape: 0.4279

Epoch 24/128

4586/4586 - 19s - 4ms/step - ia: 0.8919 - loss: 0.0413 - mae: 0.1578 - rmse: 0.1944 - smape: 0.3857 - val_ia: 0.5460 - val_loss: 0.0097 - val_mae: 0.0756 - val_rmse: 0.0882 - val_smape: 0.2067

Epoch 25/128

4586/4586 - 22s - 5ms/step - ia: 0.8925 - loss: 0.0409 - mae: 0.1566 - rmse: 0.1935 - smape: 0.3867 - val_ia: 0.5111 - val_loss: 0.0152 - val_mae: 0.0931 - val_rmse: 0.1046 - val_smape: 0.2321

Epoch 26/128

4586/4586 - 11s - 2ms/step - ia: 0.8925 - loss: 0.0409 - mae: 0.1566 - rmse: 0.1933 - smape: 0.3838 - val_ia: 0.5302 - val_loss: 0.0136 - val_mae: 0.0875 - val_rmse: 0.0999 - val_smape: 0.2231

Epoch 27/128

4586/4586 - 11s - 2ms/step - ia: 0.8919 - loss: 0.0412 - mae: 0.1565 - rmse: 0.1936 - smape: 0.3834 - val_ia: 0.5755 - val_loss: 0.0081 - val_mae: 0.0656 - val_rmse: 0.0783 - val_smape: 0.1987

Epoch 28/128

4586/4586 - 11s - 2ms/step - ia: 0.8926 - loss: 0.0409 - mae: 0.1564 - rmse: 0.1933 - smape: 0.3853 - val_ia: 0.5200 - val_loss: 0.0161 - val_mae: 0.0938 - val_rmse: 0.1056 - val_smape: 0.2325

Epoch 29/128

4586/4586 - 12s - 3ms/step - ia: 0.8915 - loss: 0.0417 - mae: 0.1580 - rmse: 0.1953 - smape: 0.3875 - val_ia: 0.5134 - val_loss: 0.0129 - val_mae: 0.0885 - val_rmse: 0.1004 - val_smape: 0.2295

Epoch 30/128

4586/4586 - 22s - 5ms/step - ia: 0.8916 - loss: 0.0415 - mae: 0.1579 - rmse: 0.1949 - smape: 0.3862 - val_ia: 0.5284 - val_loss: 0.0139 - val_mae: 0.0885 - val_rmse: 0.1010 - val_smape: 0.2155

Epoch 31/128

4586/4586 - 12s - 3ms/step - ia: 0.8929 - loss: 0.0408 - mae: 0.1562 - rmse: 0.1929 - smape: 0.3821 - val_ia: 0.5659 - val_loss: 0.0100 - val_mae: 0.0729 - val_rmse: 0.0845 - val_smape: 0.1825

Epoch 32/128

4586/4586 - 11s - 2ms/step - ia: 0.8919 - loss: 0.0413 - mae: 0.1572 - rmse: 0.1943 - smape: 0.3819 - val_ia: 0.5356 - val_loss: 0.0129 - val_mae: 0.0846 - val_rmse: 0.0970 - val_smape: 0.2149

Epoch 33/128

4586/4586 - 22s - 5ms/step - ia: 0.8924 - loss: 0.0414 - mae: 0.1572 - rmse: 0.1943 - smape: 0.3830 - val_ia: 0.5319 - val_loss: 0.0116 - val_mae: 0.0813 - val_rmse: 0.0943 - val_smape: 0.2076

Epoch 34/128

4586/4586 - 10s - 2ms/step - ia: 0.8913 - loss: 0.0413 - mae: 0.1576 - rmse: 0.1945 - smape: 0.3844 - val_ia: 0.5477 - val_loss: 0.0091 - val_mae: 0.0724 - val_rmse: 0.0846 - val_smape: 0.2267

Epoch 35/128

4586/4586 - 10s - 2ms/step - ia: 0.8918 - loss: 0.0409 - mae: 0.1570 - rmse: 0.1935 - smape: 0.3860 - val_ia: 0.5261 - val_loss: 0.0120 - val_mae: 0.0848 - val_rmse: 0.0966 - val_smape: 0.2555

Epoch 36/128

4586/4586 - 12s - 3ms/step - ia: 0.8926 - loss: 0.0411 - mae: 0.1566 - rmse: 0.1935 - smape: 0.3864 - val_ia: 0.4906 - val_loss: 0.0163 - val_mae: 0.1003 - val_rmse: 0.1131 - val_smape: 0.3606

Epoch 37/128

4586/4586 - 20s - 4ms/step - ia: 0.8926 - loss: 0.0407 - mae: 0.1562 - rmse: 0.1928 - smape: 0.3815 - val_ia: 0.5579 - val_loss: 0.0102 - val_mae: 0.0733 - val_rmse: 0.0863 - val_smape: 0.2135

Epoch 38/128

4586/4586 - 11s - 2ms/step - ia: 0.8924 - loss: 0.0409 - mae: 0.1567 - rmse: 0.1935 - smape: 0.3830 - val_ia: 0.4974 - val_loss: 0.0161 - val_mae: 0.0970 - val_rmse: 0.1089 - val_smape: 0.2297

Epoch 39/128

4586/4586 - 11s - 2ms/step - ia: 0.8940 - loss: 0.0408 - mae: 0.1557 - rmse: 0.1929 - smape: 0.3836 - val_ia: 0.5037 - val_loss: 0.0145 - val_mae: 0.0947 - val_rmse: 0.1070 - val_smape: 0.2135

Epoch 40/128

4586/4586 - 10s - 2ms/step - ia: 0.8927 - loss: 0.0410 - mae: 0.1561 - rmse: 0.1933 - smape: 0.3819 - val_ia: 0.3919 - val_loss: 0.0315 - val_mae: 0.1499 - val_rmse: 0.1616 - val_smape: 0.4668

Epoch 41/128

4586/4586 - 11s - 2ms/step - ia: 0.8924 - loss: 0.0412 - mae: 0.1569 - rmse: 0.1941 - smape: 0.3843 - val_ia: 0.5369 - val_loss: 0.0120 - val_mae: 0.0808 - val_rmse: 0.0935 - val_smape: 0.1930

Epoch 42/128

4586/4586 - 11s - 2ms/step - ia: 0.8917 - loss: 0.0412 - mae: 0.1575 - rmse: 0.1944 - smape: 0.3850 - val_ia: 0.5333 - val_loss: 0.0119 - val_mae: 0.0823 - val_rmse: 0.0941 - val_smape: 0.2072

Epoch 42: early stopping

Restoring model weights from the end of the best epoch: 27.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 46s 284ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 67%|██████▋   | 8/12 [1:09:26<28:23, 425.76s/trial, best loss: 0.0018056012500971394]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 4s - 14ms/step - ia: 0.7310 - loss: 0.4545 - mae: 0.4532 - rmse: 0.6021 - smape: 0.7570 - val_ia: 0.8795 - val_loss: 0.0489 - val_mae: 0.1609 - val_rmse: 0.2186 - val_smape: 0.3990

Epoch 2/128

287/287 - 1s - 2ms/step - ia: 0.8496 - loss: 0.1081 - mae: 0.2419 - rmse: 0.3270 - smape: 0.4923 - val_ia: 0.9094 - val_loss: 0.0269 - val_mae: 0.1206 - val_rmse: 0.1623 - val_smape: 0.3140

Epoch 3/128

287/287 - 1s - 2ms/step - ia: 0.8688 - loss: 0.0836 - mae: 0.2106 - rmse: 0.2877 - smape: 0.4273 - val_ia: 0.9204 - val_loss: 0.0200 - val_mae: 0.1064 - val_rmse: 0.1396 - val_smape: 0.2857

Epoch 4/128

287/287 - 1s - 2ms/step - ia: 0.8770 - loss: 0.0754 - mae: 0.1973 - rmse: 0.2735 - smape: 0.3944 - val_ia: 0.9227 - val_loss: 0.0182 - val_mae: 0.1025 - val_rmse: 0.1328 - val_smape: 0.2635

Epoch 5/128

287/287 - 1s - 2ms/step - ia: 0.8830 - loss: 0.0692 - mae: 0.1879 - rmse: 0.2618 - smape: 0.3711 - val_ia: 0.9325 - val_loss: 0.0141 - val_mae: 0.0900 - val_rmse: 0.1170 - val_smape: 0.2433

Epoch 6/128

287/287 - 1s - 2ms/step - ia: 0.8864 - loss: 0.0654 - mae: 0.1824 - rmse: 0.2546 - smape: 0.3564 - val_ia: 0.9346 - val_loss: 0.0130 - val_mae: 0.0872 - val_rmse: 0.1119 - val_smape: 0.2308

Epoch 7/128

287/287 - 1s - 2ms/step - ia: 0.8898 - loss: 0.0628 - mae: 0.1770 - rmse: 0.2492 - smape: 0.3423 - val_ia: 0.9397 - val_loss: 0.0112 - val_mae: 0.0805 - val_rmse: 0.1039 - val_smape: 0.2182

Epoch 8/128

287/287 - 1s - 2ms/step - ia: 0.8905 - loss: 0.0622 - mae: 0.1761 - rmse: 0.2481 - smape: 0.3389 - val_ia: 0.9342 - val_loss: 0.0123 - val_mae: 0.0877 - val_rmse: 0.1082 - val_smape: 0.2499

Epoch 9/128

287/287 - 1s - 2ms/step - ia: 0.8913 - loss: 0.0613 - mae: 0.1745 - rmse: 0.2464 - smape: 0.3328 - val_ia: 0.9404 - val_loss: 0.0104 - val_mae: 0.0797 - val_rmse: 0.0996 - val_smape: 0.2330

Epoch 10/128

287/287 - 1s - 2ms/step - ia: 0.8916 - loss: 0.0615 - mae: 0.1739 - rmse: 0.2468 - smape: 0.3280 - val_ia: 0.9393 - val_loss: 0.0108 - val_mae: 0.0809 - val_rmse: 0.1018 - val_smape: 0.2145

Epoch 11/128

287/287 - 1s - 2ms/step - ia: 0.8928 - loss: 0.0607 - mae: 0.1720 - rmse: 0.2453 - smape: 0.3235 - val_ia: 0.9436 - val_loss: 0.0098 - val_mae: 0.0754 - val_rmse: 0.0973 - val_smape: 0.1875

Epoch 12/128

287/287 - 1s - 2ms/step - ia: 0.8937 - loss: 0.0597 - mae: 0.1706 - rmse: 0.2431 - smape: 0.3196 - val_ia: 0.9392 - val_loss: 0.0107 - val_mae: 0.0809 - val_rmse: 0.1016 - val_smape: 0.2044

Epoch 13/128

287/287 - 1s - 2ms/step - ia: 0.8940 - loss: 0.0594 - mae: 0.1702 - rmse: 0.2427 - smape: 0.3166 - val_ia: 0.9456 - val_loss: 0.0087 - val_mae: 0.0728 - val_rmse: 0.0918 - val_smape: 0.2031

Epoch 14/128

287/287 - 1s - 2ms/step - ia: 0.8955 - loss: 0.0582 - mae: 0.1679 - rmse: 0.2400 - smape: 0.3130 - val_ia: 0.9360 - val_loss: 0.0113 - val_mae: 0.0849 - val_rmse: 0.1036 - val_smape: 0.2237

Epoch 15/128

287/287 - 1s - 2ms/step - ia: 0.8957 - loss: 0.0579 - mae: 0.1676 - rmse: 0.2395 - smape: 0.3095 - val_ia: 0.9427 - val_loss: 0.0094 - val_mae: 0.0763 - val_rmse: 0.0953 - val_smape: 0.2049

Epoch 16/128

287/287 - 1s - 2ms/step - ia: 0.8951 - loss: 0.0589 - mae: 0.1684 - rmse: 0.2416 - smape: 0.3116 - val_ia: 0.9555 - val_loss: 0.0064 - val_mae: 0.0600 - val_rmse: 0.0789 - val_smape: 0.1644

Epoch 17/128

287/287 - 1s - 5ms/step - ia: 0.8956 - loss: 0.0590 - mae: 0.1678 - rmse: 0.2417 - smape: 0.3064 - val_ia: 0.9405 - val_loss: 0.0104 - val_mae: 0.0792 - val_rmse: 0.1004 - val_smape: 0.1870

Epoch 18/128

287/287 - 1s - 3ms/step - ia: 0.8968 - loss: 0.0573 - mae: 0.1657 - rmse: 0.2380 - smape: 0.3034 - val_ia: 0.9440 - val_loss: 0.0092 - val_mae: 0.0745 - val_rmse: 0.0943 - val_smape: 0.1818

Epoch 19/128

287/287 - 1s - 3ms/step - ia: 0.8966 - loss: 0.0574 - mae: 0.1661 - rmse: 0.2383 - smape: 0.3035 - val_ia: 0.9473 - val_loss: 0.0082 - val_mae: 0.0705 - val_rmse: 0.0891 - val_smape: 0.1803

Epoch 20/128

287/287 - 1s - 5ms/step - ia: 0.8976 - loss: 0.0570 - mae: 0.1644 - rmse: 0.2375 - smape: 0.2977 - val_ia: 0.9472 - val_loss: 0.0083 - val_mae: 0.0707 - val_rmse: 0.0896 - val_smape: 0.1803

Epoch 21/128

287/287 - 1s - 4ms/step - ia: 0.8969 - loss: 0.0577 - mae: 0.1656 - rmse: 0.2390 - smape: 0.3012 - val_ia: 0.9376 - val_loss: 0.0108 - val_mae: 0.0830 - val_rmse: 0.1019 - val_smape: 0.2057

Epoch 22/128

287/287 - 1s - 3ms/step - ia: 0.8973 - loss: 0.0573 - mae: 0.1649 - rmse: 0.2380 - smape: 0.2990 - val_ia: 0.9357 - val_loss: 0.0113 - val_mae: 0.0848 - val_rmse: 0.1050 - val_smape: 0.1877

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.8984 - loss: 0.0564 - mae: 0.1633 - rmse: 0.2364 - smape: 0.2980 - val_ia: 0.9424 - val_loss: 0.0094 - val_mae: 0.0768 - val_rmse: 0.0951 - val_smape: 0.1918

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.8972 - loss: 0.0572 - mae: 0.1651 - rmse: 0.2378 - smape: 0.2990 - val_ia: 0.9492 - val_loss: 0.0076 - val_mae: 0.0680 - val_rmse: 0.0857 - val_smape: 0.1740

Epoch 25/128

287/287 - 1s - 3ms/step - ia: 0.8985 - loss: 0.0564 - mae: 0.1632 - rmse: 0.2361 - smape: 0.2933 - val_ia: 0.9510 - val_loss: 0.0074 - val_mae: 0.0657 - val_rmse: 0.0849 - val_smape: 0.1545

Epoch 26/128

287/287 - 1s - 3ms/step - ia: 0.8979 - loss: 0.0565 - mae: 0.1640 - rmse: 0.2365 - smape: 0.2937 - val_ia: 0.9578 - val_loss: 0.0056 - val_mae: 0.0568 - val_rmse: 0.0733 - val_smape: 0.1654

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.8975 - loss: 0.0571 - mae: 0.1645 - rmse: 0.2378 - smape: 0.2940 - val_ia: 0.9603 - val_loss: 0.0052 - val_mae: 0.0534 - val_rmse: 0.0709 - val_smape: 0.1466

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.8982 - loss: 0.0564 - mae: 0.1635 - rmse: 0.2361 - smape: 0.2928 - val_ia: 0.9526 - val_loss: 0.0067 - val_mae: 0.0634 - val_rmse: 0.0801 - val_smape: 0.1749

Epoch 29/128

287/287 - 1s - 4ms/step - ia: 0.8990 - loss: 0.0561 - mae: 0.1623 - rmse: 0.2355 - smape: 0.2920 - val_ia: 0.9576 - val_loss: 0.0057 - val_mae: 0.0573 - val_rmse: 0.0747 - val_smape: 0.1876

Epoch 30/128

287/287 - 1s - 5ms/step - ia: 0.8984 - loss: 0.0564 - mae: 0.1631 - rmse: 0.2362 - smape: 0.2912 - val_ia: 0.9460 - val_loss: 0.0083 - val_mae: 0.0720 - val_rmse: 0.0893 - val_smape: 0.1854

Epoch 31/128

287/287 - 1s - 4ms/step - ia: 0.8983 - loss: 0.0566 - mae: 0.1633 - rmse: 0.2367 - smape: 0.2915 - val_ia: 0.9526 - val_loss: 0.0071 - val_mae: 0.0637 - val_rmse: 0.0831 - val_smape: 0.1582

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.8988 - loss: 0.0564 - mae: 0.1624 - rmse: 0.2363 - smape: 0.2894 - val_ia: 0.9534 - val_loss: 0.0066 - val_mae: 0.0626 - val_rmse: 0.0798 - val_smape: 0.1686

Epoch 33/128

287/287 - 1s - 4ms/step - ia: 0.8987 - loss: 0.0566 - mae: 0.1627 - rmse: 0.2367 - smape: 0.2909 - val_ia: 0.9574 - val_loss: 0.0056 - val_mae: 0.0572 - val_rmse: 0.0733 - val_smape: 0.1635

Epoch 34/128

287/287 - 1s - 5ms/step - ia: 0.8990 - loss: 0.0566 - mae: 0.1622 - rmse: 0.2366 - smape: 0.2883 - val_ia: 0.9567 - val_loss: 0.0059 - val_mae: 0.0581 - val_rmse: 0.0758 - val_smape: 0.1477

Epoch 35/128

287/287 - 1s - 3ms/step - ia: 0.8984 - loss: 0.0564 - mae: 0.1631 - rmse: 0.2362 - smape: 0.2897 - val_ia: 0.9530 - val_loss: 0.0065 - val_mae: 0.0629 - val_rmse: 0.0791 - val_smape: 0.1751

Epoch 36/128

287/287 - 1s - 5ms/step - ia: 0.8986 - loss: 0.0568 - mae: 0.1628 - rmse: 0.2372 - smape: 0.2897 - val_ia: 0.9547 - val_loss: 0.0062 - val_mae: 0.0608 - val_rmse: 0.0770 - val_smape: 0.1667

Epoch 37/128

287/287 - 1s - 3ms/step - ia: 0.8992 - loss: 0.0560 - mae: 0.1621 - rmse: 0.2354 - smape: 0.2885 - val_ia: 0.9569 - val_loss: 0.0058 - val_mae: 0.0580 - val_rmse: 0.0752 - val_smape: 0.1559

Epoch 38/128

287/287 - 1s - 3ms/step - ia: 0.8993 - loss: 0.0561 - mae: 0.1620 - rmse: 0.2356 - smape: 0.2893 - val_ia: 0.9530 - val_loss: 0.0067 - val_mae: 0.0631 - val_rmse: 0.0807 - val_smape: 0.1566

Epoch 39/128

287/287 - 1s - 5ms/step - ia: 0.8993 - loss: 0.0561 - mae: 0.1618 - rmse: 0.2357 - smape: 0.2863 - val_ia: 0.9513 - val_loss: 0.0070 - val_mae: 0.0654 - val_rmse: 0.0823 - val_smape: 0.1680

Epoch 40/128

287/287 - 1s - 3ms/step - ia: 0.8989 - loss: 0.0565 - mae: 0.1623 - rmse: 0.2363 - smape: 0.2869 - val_ia: 0.9553 - val_loss: 0.0061 - val_mae: 0.0600 - val_rmse: 0.0766 - val_smape: 0.1593

Epoch 41/128

287/287 - 1s - 5ms/step - ia: 0.8993 - loss: 0.0562 - mae: 0.1618 - rmse: 0.2357 - smape: 0.2877 - val_ia: 0.9521 - val_loss: 0.0069 - val_mae: 0.0642 - val_rmse: 0.0819 - val_smape: 0.1603

Epoch 42/128

287/287 - 1s - 2ms/step - ia: 0.8996 - loss: 0.0558 - mae: 0.1614 - rmse: 0.2348 - smape: 0.2854 - val_ia: 0.9618 - val_loss: 0.0047 - val_mae: 0.0513 - val_rmse: 0.0674 - val_smape: 0.1577

Epoch 43/128

287/287 - 1s - 2ms/step - ia: 0.9003 - loss: 0.0549 - mae: 0.1604 - rmse: 0.2331 - smape: 0.2852 - val_ia: 0.9576 - val_loss: 0.0057 - val_mae: 0.0571 - val_rmse: 0.0743 - val_smape: 0.1483

Epoch 44/128

287/287 - 1s - 2ms/step - ia: 0.9002 - loss: 0.0553 - mae: 0.1604 - rmse: 0.2339 - smape: 0.2854 - val_ia: 0.9518 - val_loss: 0.0067 - val_mae: 0.0644 - val_rmse: 0.0800 - val_smape: 0.1799

Epoch 45/128

287/287 - 1s - 3ms/step - ia: 0.8988 - loss: 0.0568 - mae: 0.1627 - rmse: 0.2370 - smape: 0.2872 - val_ia: 0.9534 - val_loss: 0.0066 - val_mae: 0.0626 - val_rmse: 0.0798 - val_smape: 0.1598

Epoch 46/128

287/287 - 1s - 3ms/step - ia: 0.8997 - loss: 0.0559 - mae: 0.1612 - rmse: 0.2352 - smape: 0.2865 - val_ia: 0.9596 - val_loss: 0.0050 - val_mae: 0.0544 - val_rmse: 0.0698 - val_smape: 0.1776

Epoch 47/128

287/287 - 1s - 5ms/step - ia: 0.8997 - loss: 0.0555 - mae: 0.1612 - rmse: 0.2342 - smape: 0.2851 - val_ia: 0.9604 - val_loss: 0.0050 - val_mae: 0.0533 - val_rmse: 0.0695 - val_smape: 0.1490

Epoch 48/128

287/287 - 1s - 5ms/step - ia: 0.9010 - loss: 0.0545 - mae: 0.1591 - rmse: 0.2321 - smape: 0.2835 - val_ia: 0.9645 - val_loss: 0.0043 - val_mae: 0.0479 - val_rmse: 0.0646 - val_smape: 0.1416

Epoch 49/128

287/287 - 1s - 5ms/step - ia: 0.9015 - loss: 0.0541 - mae: 0.1583 - rmse: 0.2314 - smape: 0.2806 - val_ia: 0.9492 - val_loss: 0.0076 - val_mae: 0.0680 - val_rmse: 0.0861 - val_smape: 0.1579

Epoch 50/128

287/287 - 1s - 4ms/step - ia: 0.9003 - loss: 0.0549 - mae: 0.1604 - rmse: 0.2330 - smape: 0.2839 - val_ia: 0.9611 - val_loss: 0.0049 - val_mae: 0.0525 - val_rmse: 0.0688 - val_smape: 0.1449

Epoch 51/128

287/287 - 1s - 5ms/step - ia: 0.9004 - loss: 0.0557 - mae: 0.1600 - rmse: 0.2349 - smape: 0.2820 - val_ia: 0.9563 - val_loss: 0.0057 - val_mae: 0.0588 - val_rmse: 0.0741 - val_smape: 0.1647

Epoch 52/128

287/287 - 1s - 5ms/step - ia: 0.8999 - loss: 0.0556 - mae: 0.1610 - rmse: 0.2346 - smape: 0.2836 - val_ia: 0.9522 - val_loss: 0.0068 - val_mae: 0.0640 - val_rmse: 0.0815 - val_smape: 0.1528

Epoch 53/128

287/287 - 1s - 5ms/step - ia: 0.8996 - loss: 0.0559 - mae: 0.1614 - rmse: 0.2350 - smape: 0.2832 - val_ia: 0.9444 - val_loss: 0.0089 - val_mae: 0.0742 - val_rmse: 0.0930 - val_smape: 0.1677

Epoch 54/128

287/287 - 1s - 3ms/step - ia: 0.9002 - loss: 0.0552 - mae: 0.1604 - rmse: 0.2339 - smape: 0.2817 - val_ia: 0.9516 - val_loss: 0.0068 - val_mae: 0.0648 - val_rmse: 0.0810 - val_smape: 0.1692

Epoch 55/128

287/287 - 1s - 3ms/step - ia: 0.8998 - loss: 0.0556 - mae: 0.1610 - rmse: 0.2348 - smape: 0.2841 - val_ia: 0.9539 - val_loss: 0.0064 - val_mae: 0.0619 - val_rmse: 0.0785 - val_smape: 0.1587

Epoch 56/128

287/287 - 1s - 3ms/step - ia: 0.9002 - loss: 0.0552 - mae: 0.1604 - rmse: 0.2337 - smape: 0.2821 - val_ia: 0.9509 - val_loss: 0.0073 - val_mae: 0.0656 - val_rmse: 0.0845 - val_smape: 0.1488

Epoch 57/128

287/287 - 1s - 5ms/step - ia: 0.9009 - loss: 0.0549 - mae: 0.1593 - rmse: 0.2331 - smape: 0.2805 - val_ia: 0.9620 - val_loss: 0.0047 - val_mae: 0.0512 - val_rmse: 0.0681 - val_smape: 0.1577

Epoch 58/128

287/287 - 2s - 6ms/step - ia: 0.8997 - loss: 0.0555 - mae: 0.1612 - rmse: 0.2342 - smape: 0.2853 - val_ia: 0.9545 - val_loss: 0.0061 - val_mae: 0.0609 - val_rmse: 0.0763 - val_smape: 0.1702

Epoch 59/128

287/287 - 1s - 3ms/step - ia: 0.9003 - loss: 0.0551 - mae: 0.1603 - rmse: 0.2335 - smape: 0.2807 - val_ia: 0.9603 - val_loss: 0.0049 - val_mae: 0.0535 - val_rmse: 0.0691 - val_smape: 0.1458

Epoch 60/128

287/287 - 1s - 4ms/step - ia: 0.8995 - loss: 0.0565 - mae: 0.1615 - rmse: 0.2365 - smape: 0.2826 - val_ia: 0.9505 - val_loss: 0.0073 - val_mae: 0.0662 - val_rmse: 0.0847 - val_smape: 0.1495

Epoch 61/128

287/287 - 1s - 5ms/step - ia: 0.9004 - loss: 0.0551 - mae: 0.1600 - rmse: 0.2336 - smape: 0.2822 - val_ia: 0.9491 - val_loss: 0.0074 - val_mae: 0.0679 - val_rmse: 0.0850 - val_smape: 0.1594

Epoch 62/128

287/287 - 1s - 4ms/step - ia: 0.9005 - loss: 0.0551 - mae: 0.1600 - rmse: 0.2334 - smape: 0.2824 - val_ia: 0.9597 - val_loss: 0.0050 - val_mae: 0.0546 - val_rmse: 0.0699 - val_smape: 0.1603

Epoch 63/128

287/287 - 1s - 5ms/step - ia: 0.9010 - loss: 0.0547 - mae: 0.1593 - rmse: 0.2326 - smape: 0.2809 - val_ia: 0.9574 - val_loss: 0.0056 - val_mae: 0.0573 - val_rmse: 0.0738 - val_smape: 0.1483

Epoch 63: early stopping

Restoring model weights from the end of the best epoch: 48.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 15s 95ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 75%|███████▌  | 9/12 [1:10:34<15:41, 313.94s/trial, best loss: 0.0018056012500971394]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 19s - 8ms/step - ia: 0.6644 - loss: 0.4454 - mae: 0.5111 - rmse: 0.6311 - smape: 0.8689 - val_ia: 0.4139 - val_loss: 0.1454 - val_mae: 0.3026 - val_rmse: 0.3236 - val_smape: 0.6452

Epoch 2/128

2293/2293 - 9s - 4ms/step - ia: 0.8105 - loss: 0.1417 - mae: 0.2939 - rmse: 0.3675 - smape: 0.5918 - val_ia: 0.5186 - val_loss: 0.0629 - val_mae: 0.1995 - val_rmse: 0.2193 - val_smape: 0.4951

Epoch 3/128

2293/2293 - 10s - 4ms/step - ia: 0.8599 - loss: 0.0790 - mae: 0.2176 - rmse: 0.2744 - smape: 0.4780 - val_ia: 0.5852 - val_loss: 0.0387 - val_mae: 0.1527 - val_rmse: 0.1716 - val_smape: 0.3991

Epoch 4/128

2293/2293 - 6s - 3ms/step - ia: 0.8814 - loss: 0.0575 - mae: 0.1846 - rmse: 0.2340 - smape: 0.4240 - val_ia: 0.5956 - val_loss: 0.0347 - val_mae: 0.1428 - val_rmse: 0.1614 - val_smape: 0.3627

Epoch 5/128

2293/2293 - 7s - 3ms/step - ia: 0.8925 - loss: 0.0478 - mae: 0.1667 - rmse: 0.2130 - smape: 0.3957 - val_ia: 0.6159 - val_loss: 0.0284 - val_mae: 0.1283 - val_rmse: 0.1470 - val_smape: 0.3356

Epoch 6/128

2293/2293 - 6s - 3ms/step - ia: 0.8996 - loss: 0.0422 - mae: 0.1561 - rmse: 0.2002 - smape: 0.3741 - val_ia: 0.5908 - val_loss: 0.0307 - val_mae: 0.1374 - val_rmse: 0.1556 - val_smape: 0.3530

Epoch 7/128

2293/2293 - 6s - 3ms/step - ia: 0.9041 - loss: 0.0386 - mae: 0.1487 - rmse: 0.1911 - smape: 0.3609 - val_ia: 0.6209 - val_loss: 0.0242 - val_mae: 0.1207 - val_rmse: 0.1386 - val_smape: 0.3334

Epoch 8/128

2293/2293 - 5s - 2ms/step - ia: 0.9063 - loss: 0.0367 - mae: 0.1452 - rmse: 0.1865 - smape: 0.3582 - val_ia: 0.6307 - val_loss: 0.0223 - val_mae: 0.1151 - val_rmse: 0.1329 - val_smape: 0.3176

Epoch 9/128

2293/2293 - 5s - 2ms/step - ia: 0.9086 - loss: 0.0347 - mae: 0.1417 - rmse: 0.1816 - smape: 0.3525 - val_ia: 0.6226 - val_loss: 0.0228 - val_mae: 0.1184 - val_rmse: 0.1354 - val_smape: 0.3224

Epoch 10/128

2293/2293 - 11s - 5ms/step - ia: 0.9104 - loss: 0.0338 - mae: 0.1391 - rmse: 0.1788 - smape: 0.3436 - val_ia: 0.6396 - val_loss: 0.0197 - val_mae: 0.1089 - val_rmse: 0.1258 - val_smape: 0.3000

Epoch 11/128

2293/2293 - 6s - 3ms/step - ia: 0.9119 - loss: 0.0328 - mae: 0.1366 - rmse: 0.1758 - smape: 0.3394 - val_ia: 0.6673 - val_loss: 0.0171 - val_mae: 0.0992 - val_rmse: 0.1163 - val_smape: 0.2880

Epoch 12/128

2293/2293 - 7s - 3ms/step - ia: 0.9126 - loss: 0.0321 - mae: 0.1358 - rmse: 0.1744 - smape: 0.3370 - val_ia: 0.6657 - val_loss: 0.0168 - val_mae: 0.0990 - val_rmse: 0.1155 - val_smape: 0.2866

Epoch 13/128

2293/2293 - 10s - 4ms/step - ia: 0.9137 - loss: 0.0315 - mae: 0.1340 - rmse: 0.1727 - smape: 0.3317 - val_ia: 0.6689 - val_loss: 0.0164 - val_mae: 0.0972 - val_rmse: 0.1140 - val_smape: 0.2735

Epoch 14/128

2293/2293 - 11s - 5ms/step - ia: 0.9151 - loss: 0.0307 - mae: 0.1324 - rmse: 0.1704 - smape: 0.3290 - val_ia: 0.6916 - val_loss: 0.0142 - val_mae: 0.0886 - val_rmse: 0.1052 - val_smape: 0.2627

Epoch 15/128

2293/2293 - 10s - 5ms/step - ia: 0.9156 - loss: 0.0303 - mae: 0.1311 - rmse: 0.1690 - smape: 0.3258 - val_ia: 0.6792 - val_loss: 0.0145 - val_mae: 0.0915 - val_rmse: 0.1075 - val_smape: 0.2638

Epoch 16/128

2293/2293 - 10s - 4ms/step - ia: 0.9169 - loss: 0.0294 - mae: 0.1295 - rmse: 0.1665 - smape: 0.3220 - val_ia: 0.6920 - val_loss: 0.0133 - val_mae: 0.0860 - val_rmse: 0.1021 - val_smape: 0.2452

Epoch 17/128

2293/2293 - 10s - 4ms/step - ia: 0.9175 - loss: 0.0288 - mae: 0.1282 - rmse: 0.1651 - smape: 0.3196 - val_ia: 0.7037 - val_loss: 0.0125 - val_mae: 0.0832 - val_rmse: 0.0992 - val_smape: 0.2444

Epoch 18/128

2293/2293 - 6s - 3ms/step - ia: 0.9179 - loss: 0.0288 - mae: 0.1276 - rmse: 0.1650 - smape: 0.3167 - val_ia: 0.6825 - val_loss: 0.0135 - val_mae: 0.0888 - val_rmse: 0.1042 - val_smape: 0.2502

Epoch 19/128

2293/2293 - 6s - 3ms/step - ia: 0.9181 - loss: 0.0284 - mae: 0.1273 - rmse: 0.1638 - smape: 0.3166 - val_ia: 0.6921 - val_loss: 0.0130 - val_mae: 0.0862 - val_rmse: 0.1016 - val_smape: 0.2451

Epoch 20/128

2293/2293 - 11s - 5ms/step - ia: 0.9187 - loss: 0.0280 - mae: 0.1264 - rmse: 0.1626 - smape: 0.3134 - val_ia: 0.7012 - val_loss: 0.0121 - val_mae: 0.0823 - val_rmse: 0.0978 - val_smape: 0.2354

Epoch 21/128

2293/2293 - 10s - 4ms/step - ia: 0.9192 - loss: 0.0278 - mae: 0.1257 - rmse: 0.1619 - smape: 0.3103 - val_ia: 0.6706 - val_loss: 0.0145 - val_mae: 0.0935 - val_rmse: 0.1085 - val_smape: 0.2496

Epoch 22/128

2293/2293 - 11s - 5ms/step - ia: 0.9195 - loss: 0.0279 - mae: 0.1260 - rmse: 0.1623 - smape: 0.3103 - val_ia: 0.7119 - val_loss: 0.0111 - val_mae: 0.0785 - val_rmse: 0.0935 - val_smape: 0.2267

Epoch 23/128

2293/2293 - 10s - 4ms/step - ia: 0.9199 - loss: 0.0274 - mae: 0.1247 - rmse: 0.1605 - smape: 0.3073 - val_ia: 0.6857 - val_loss: 0.0132 - val_mae: 0.0880 - val_rmse: 0.1027 - val_smape: 0.2349

Epoch 24/128

2293/2293 - 6s - 3ms/step - ia: 0.9205 - loss: 0.0272 - mae: 0.1240 - rmse: 0.1600 - smape: 0.3058 - val_ia: 0.7311 - val_loss: 0.0101 - val_mae: 0.0737 - val_rmse: 0.0885 - val_smape: 0.2166

Epoch 25/128

2293/2293 - 6s - 3ms/step - ia: 0.9211 - loss: 0.0265 - mae: 0.1228 - rmse: 0.1582 - smape: 0.3051 - val_ia: 0.7220 - val_loss: 0.0103 - val_mae: 0.0758 - val_rmse: 0.0905 - val_smape: 0.2233

Epoch 26/128

2293/2293 - 6s - 3ms/step - ia: 0.9222 - loss: 0.0261 - mae: 0.1213 - rmse: 0.1568 - smape: 0.2996 - val_ia: 0.7179 - val_loss: 0.0114 - val_mae: 0.0782 - val_rmse: 0.0930 - val_smape: 0.2097

Epoch 27/128

2293/2293 - 14s - 6ms/step - ia: 0.9224 - loss: 0.0258 - mae: 0.1213 - rmse: 0.1561 - smape: 0.2987 - val_ia: 0.7429 - val_loss: 0.0099 - val_mae: 0.0713 - val_rmse: 0.0861 - val_smape: 0.2057

Epoch 28/128

2293/2293 - 10s - 4ms/step - ia: 0.9231 - loss: 0.0255 - mae: 0.1199 - rmse: 0.1550 - smape: 0.2971 - val_ia: 0.7387 - val_loss: 0.0093 - val_mae: 0.0705 - val_rmse: 0.0850 - val_smape: 0.2044

Epoch 29/128

2293/2293 - 6s - 3ms/step - ia: 0.9227 - loss: 0.0257 - mae: 0.1205 - rmse: 0.1558 - smape: 0.2976 - val_ia: 0.7307 - val_loss: 0.0100 - val_mae: 0.0725 - val_rmse: 0.0871 - val_smape: 0.1962

Epoch 30/128

2293/2293 - 6s - 3ms/step - ia: 0.9232 - loss: 0.0255 - mae: 0.1198 - rmse: 0.1551 - smape: 0.2930 - val_ia: 0.7187 - val_loss: 0.0101 - val_mae: 0.0754 - val_rmse: 0.0897 - val_smape: 0.2094

Epoch 31/128

2293/2293 - 6s - 3ms/step - ia: 0.9228 - loss: 0.0257 - mae: 0.1202 - rmse: 0.1553 - smape: 0.2937 - val_ia: 0.7394 - val_loss: 0.0096 - val_mae: 0.0708 - val_rmse: 0.0852 - val_smape: 0.1932

Epoch 32/128

2293/2293 - 6s - 3ms/step - ia: 0.9239 - loss: 0.0251 - mae: 0.1186 - rmse: 0.1534 - smape: 0.2936 - val_ia: 0.7221 - val_loss: 0.0103 - val_mae: 0.0756 - val_rmse: 0.0899 - val_smape: 0.2115

Epoch 33/128

2293/2293 - 6s - 3ms/step - ia: 0.9236 - loss: 0.0250 - mae: 0.1189 - rmse: 0.1533 - smape: 0.2914 - val_ia: 0.7578 - val_loss: 0.0078 - val_mae: 0.0635 - val_rmse: 0.0778 - val_smape: 0.1885

Epoch 34/128

2293/2293 - 6s - 3ms/step - ia: 0.9240 - loss: 0.0250 - mae: 0.1185 - rmse: 0.1533 - smape: 0.2917 - val_ia: 0.7557 - val_loss: 0.0086 - val_mae: 0.0663 - val_rmse: 0.0806 - val_smape: 0.1942

Epoch 35/128

2293/2293 - 6s - 3ms/step - ia: 0.9249 - loss: 0.0244 - mae: 0.1172 - rmse: 0.1515 - smape: 0.2907 - val_ia: 0.7204 - val_loss: 0.0104 - val_mae: 0.0761 - val_rmse: 0.0899 - val_smape: 0.2002

Epoch 36/128

2293/2293 - 10s - 4ms/step - ia: 0.9247 - loss: 0.0246 - mae: 0.1174 - rmse: 0.1521 - smape: 0.2871 - val_ia: 0.7350 - val_loss: 0.0088 - val_mae: 0.0695 - val_rmse: 0.0834 - val_smape: 0.1907

Epoch 37/128

2293/2293 - 7s - 3ms/step - ia: 0.9253 - loss: 0.0242 - mae: 0.1169 - rmse: 0.1511 - smape: 0.2881 - val_ia: 0.7335 - val_loss: 0.0090 - val_mae: 0.0704 - val_rmse: 0.0842 - val_smape: 0.1949

Epoch 38/128

2293/2293 - 6s - 3ms/step - ia: 0.9256 - loss: 0.0240 - mae: 0.1164 - rmse: 0.1504 - smape: 0.2868 - val_ia: 0.7664 - val_loss: 0.0077 - val_mae: 0.0625 - val_rmse: 0.0766 - val_smape: 0.1869

Epoch 39/128

2293/2293 - 6s - 3ms/step - ia: 0.9258 - loss: 0.0241 - mae: 0.1160 - rmse: 0.1503 - smape: 0.2834 - val_ia: 0.7172 - val_loss: 0.0099 - val_mae: 0.0753 - val_rmse: 0.0888 - val_smape: 0.2001

Epoch 40/128

2293/2293 - 10s - 4ms/step - ia: 0.9257 - loss: 0.0240 - mae: 0.1159 - rmse: 0.1502 - smape: 0.2860 - val_ia: 0.7469 - val_loss: 0.0083 - val_mae: 0.0667 - val_rmse: 0.0806 - val_smape: 0.1935

Epoch 41/128

2293/2293 - 6s - 3ms/step - ia: 0.9268 - loss: 0.0235 - mae: 0.1144 - rmse: 0.1485 - smape: 0.2813 - val_ia: 0.7543 - val_loss: 0.0076 - val_mae: 0.0639 - val_rmse: 0.0774 - val_smape: 0.1903

Epoch 42/128

2293/2293 - 6s - 3ms/step - ia: 0.9263 - loss: 0.0236 - mae: 0.1150 - rmse: 0.1488 - smape: 0.2817 - val_ia: 0.7479 - val_loss: 0.0081 - val_mae: 0.0662 - val_rmse: 0.0798 - val_smape: 0.1913

Epoch 43/128

2293/2293 - 6s - 3ms/step - ia: 0.9266 - loss: 0.0237 - mae: 0.1148 - rmse: 0.1491 - smape: 0.2822 - val_ia: 0.7495 - val_loss: 0.0080 - val_mae: 0.0656 - val_rmse: 0.0792 - val_smape: 0.1903

Epoch 44/128

2293/2293 - 6s - 3ms/step - ia: 0.9273 - loss: 0.0230 - mae: 0.1137 - rmse: 0.1471 - smape: 0.2774 - val_ia: 0.7656 - val_loss: 0.0072 - val_mae: 0.0610 - val_rmse: 0.0746 - val_smape: 0.1788

Epoch 45/128

2293/2293 - 10s - 4ms/step - ia: 0.9269 - loss: 0.0234 - mae: 0.1142 - rmse: 0.1481 - smape: 0.2796 - val_ia: 0.7431 - val_loss: 0.0082 - val_mae: 0.0682 - val_rmse: 0.0812 - val_smape: 0.1984

Epoch 46/128

2293/2293 - 6s - 3ms/step - ia: 0.9273 - loss: 0.0231 - mae: 0.1135 - rmse: 0.1474 - smape: 0.2778 - val_ia: 0.7268 - val_loss: 0.0089 - val_mae: 0.0715 - val_rmse: 0.0847 - val_smape: 0.1932

Epoch 47/128

2293/2293 - 6s - 3ms/step - ia: 0.9278 - loss: 0.0230 - mae: 0.1131 - rmse: 0.1468 - smape: 0.2787 - val_ia: 0.7480 - val_loss: 0.0078 - val_mae: 0.0658 - val_rmse: 0.0790 - val_smape: 0.1882

Epoch 48/128

2293/2293 - 6s - 3ms/step - ia: 0.9279 - loss: 0.0226 - mae: 0.1125 - rmse: 0.1459 - smape: 0.2773 - val_ia: 0.7593 - val_loss: 0.0074 - val_mae: 0.0631 - val_rmse: 0.0764 - val_smape: 0.1853

Epoch 49/128

2293/2293 - 10s - 5ms/step - ia: 0.9277 - loss: 0.0228 - mae: 0.1126 - rmse: 0.1463 - smape: 0.2760 - val_ia: 0.7763 - val_loss: 0.0072 - val_mae: 0.0598 - val_rmse: 0.0734 - val_smape: 0.1732

Epoch 50/128

2293/2293 - 5s - 2ms/step - ia: 0.9276 - loss: 0.0229 - mae: 0.1133 - rmse: 0.1469 - smape: 0.2758 - val_ia: 0.7346 - val_loss: 0.0083 - val_mae: 0.0690 - val_rmse: 0.0821 - val_smape: 0.1936

Epoch 51/128

2293/2293 - 5s - 2ms/step - ia: 0.9281 - loss: 0.0228 - mae: 0.1124 - rmse: 0.1461 - smape: 0.2732 - val_ia: 0.7703 - val_loss: 0.0069 - val_mae: 0.0602 - val_rmse: 0.0735 - val_smape: 0.1801

Epoch 52/128

2293/2293 - 5s - 2ms/step - ia: 0.9279 - loss: 0.0227 - mae: 0.1127 - rmse: 0.1459 - smape: 0.2738 - val_ia: 0.7368 - val_loss: 0.0082 - val_mae: 0.0682 - val_rmse: 0.0812 - val_smape: 0.1920

Epoch 53/128

2293/2293 - 6s - 2ms/step - ia: 0.9283 - loss: 0.0224 - mae: 0.1120 - rmse: 0.1453 - smape: 0.2750 - val_ia: 0.7618 - val_loss: 0.0071 - val_mae: 0.0616 - val_rmse: 0.0749 - val_smape: 0.1804

Epoch 54/128

2293/2293 - 6s - 3ms/step - ia: 0.9282 - loss: 0.0226 - mae: 0.1124 - rmse: 0.1458 - smape: 0.2723 - val_ia: 0.7625 - val_loss: 0.0072 - val_mae: 0.0618 - val_rmse: 0.0749 - val_smape: 0.1738

Epoch 55/128

2293/2293 - 6s - 3ms/step - ia: 0.9282 - loss: 0.0224 - mae: 0.1122 - rmse: 0.1451 - smape: 0.2736 - val_ia: 0.7808 - val_loss: 0.0066 - val_mae: 0.0578 - val_rmse: 0.0709 - val_smape: 0.1765

Epoch 56/128

2293/2293 - 10s - 4ms/step - ia: 0.9286 - loss: 0.0224 - mae: 0.1114 - rmse: 0.1449 - smape: 0.2710 - val_ia: 0.7709 - val_loss: 0.0068 - val_mae: 0.0594 - val_rmse: 0.0725 - val_smape: 0.1758

Epoch 57/128

2293/2293 - 10s - 5ms/step - ia: 0.9293 - loss: 0.0220 - mae: 0.1106 - rmse: 0.1436 - smape: 0.2691 - val_ia: 0.7511 - val_loss: 0.0076 - val_mae: 0.0648 - val_rmse: 0.0776 - val_smape: 0.1813

Epoch 58/128

2293/2293 - 10s - 5ms/step - ia: 0.9283 - loss: 0.0225 - mae: 0.1123 - rmse: 0.1457 - smape: 0.2740 - val_ia: 0.7743 - val_loss: 0.0064 - val_mae: 0.0576 - val_rmse: 0.0705 - val_smape: 0.1742

Epoch 59/128

2293/2293 - 6s - 3ms/step - ia: 0.9297 - loss: 0.0218 - mae: 0.1101 - rmse: 0.1429 - smape: 0.2680 - val_ia: 0.7720 - val_loss: 0.0065 - val_mae: 0.0587 - val_rmse: 0.0716 - val_smape: 0.1816

Epoch 60/128

2293/2293 - 6s - 2ms/step - ia: 0.9295 - loss: 0.0218 - mae: 0.1104 - rmse: 0.1431 - smape: 0.2680 - val_ia: 0.7695 - val_loss: 0.0069 - val_mae: 0.0602 - val_rmse: 0.0731 - val_smape: 0.1773

Epoch 61/128

2293/2293 - 6s - 3ms/step - ia: 0.9291 - loss: 0.0222 - mae: 0.1109 - rmse: 0.1443 - smape: 0.2694 - val_ia: 0.7692 - val_loss: 0.0066 - val_mae: 0.0593 - val_rmse: 0.0723 - val_smape: 0.1791

Epoch 62/128

2293/2293 - 10s - 4ms/step - ia: 0.9294 - loss: 0.0219 - mae: 0.1104 - rmse: 0.1435 - smape: 0.2686 - val_ia: 0.7970 - val_loss: 0.0057 - val_mae: 0.0530 - val_rmse: 0.0660 - val_smape: 0.1703

Epoch 63/128

2293/2293 - 10s - 5ms/step - ia: 0.9297 - loss: 0.0217 - mae: 0.1100 - rmse: 0.1430 - smape: 0.2668 - val_ia: 0.7977 - val_loss: 0.0057 - val_mae: 0.0528 - val_rmse: 0.0660 - val_smape: 0.1644

Epoch 64/128

2293/2293 - 6s - 2ms/step - ia: 0.9294 - loss: 0.0220 - mae: 0.1103 - rmse: 0.1436 - smape: 0.2673 - val_ia: 0.7718 - val_loss: 0.0065 - val_mae: 0.0585 - val_rmse: 0.0715 - val_smape: 0.1775

Epoch 65/128

2293/2293 - 10s - 5ms/step - ia: 0.9299 - loss: 0.0216 - mae: 0.1098 - rmse: 0.1425 - smape: 0.2666 - val_ia: 0.7684 - val_loss: 0.0066 - val_mae: 0.0594 - val_rmse: 0.0722 - val_smape: 0.1794

Epoch 66/128

2293/2293 - 11s - 5ms/step - ia: 0.9304 - loss: 0.0212 - mae: 0.1090 - rmse: 0.1414 - smape: 0.2665 - val_ia: 0.7664 - val_loss: 0.0071 - val_mae: 0.0617 - val_rmse: 0.0745 - val_smape: 0.1859

Epoch 67/128

2293/2293 - 6s - 3ms/step - ia: 0.9303 - loss: 0.0215 - mae: 0.1090 - rmse: 0.1420 - smape: 0.2651 - val_ia: 0.7978 - val_loss: 0.0057 - val_mae: 0.0532 - val_rmse: 0.0660 - val_smape: 0.1749

Epoch 68/128

2293/2293 - 10s - 4ms/step - ia: 0.9301 - loss: 0.0217 - mae: 0.1094 - rmse: 0.1424 - smape: 0.2651 - val_ia: 0.7802 - val_loss: 0.0059 - val_mae: 0.0553 - val_rmse: 0.0680 - val_smape: 0.1682

Epoch 69/128

2293/2293 - 6s - 3ms/step - ia: 0.9301 - loss: 0.0216 - mae: 0.1091 - rmse: 0.1423 - smape: 0.2652 - val_ia: 0.7702 - val_loss: 0.0063 - val_mae: 0.0577 - val_rmse: 0.0704 - val_smape: 0.1716

Epoch 70/128

2293/2293 - 6s - 3ms/step - ia: 0.9302 - loss: 0.0215 - mae: 0.1093 - rmse: 0.1421 - smape: 0.2644 - val_ia: 0.7367 - val_loss: 0.0079 - val_mae: 0.0678 - val_rmse: 0.0801 - val_smape: 0.1905

Epoch 71/128

2293/2293 - 6s - 3ms/step - ia: 0.9309 - loss: 0.0214 - mae: 0.1082 - rmse: 0.1412 - smape: 0.2643 - val_ia: 0.8011 - val_loss: 0.0056 - val_mae: 0.0527 - val_rmse: 0.0654 - val_smape: 0.1715

Epoch 72/128

2293/2293 - 6s - 3ms/step - ia: 0.9312 - loss: 0.0209 - mae: 0.1076 - rmse: 0.1401 - smape: 0.2631 - val_ia: 0.7627 - val_loss: 0.0069 - val_mae: 0.0612 - val_rmse: 0.0738 - val_smape: 0.1783

Epoch 73/128

2293/2293 - 6s - 3ms/step - ia: 0.9309 - loss: 0.0210 - mae: 0.1078 - rmse: 0.1401 - smape: 0.2614 - val_ia: 0.7528 - val_loss: 0.0073 - val_mae: 0.0638 - val_rmse: 0.0762 - val_smape: 0.1797

Epoch 74/128

2293/2293 - 10s - 4ms/step - ia: 0.9307 - loss: 0.0214 - mae: 0.1084 - rmse: 0.1415 - smape: 0.2606 - val_ia: 0.7947 - val_loss: 0.0057 - val_mae: 0.0531 - val_rmse: 0.0658 - val_smape: 0.1691

Epoch 75/128

2293/2293 - 6s - 2ms/step - ia: 0.9312 - loss: 0.0210 - mae: 0.1079 - rmse: 0.1404 - smape: 0.2615 - val_ia: 0.7813 - val_loss: 0.0060 - val_mae: 0.0563 - val_rmse: 0.0688 - val_smape: 0.1759

Epoch 76/128

2293/2293 - 11s - 5ms/step - ia: 0.9309 - loss: 0.0212 - mae: 0.1082 - rmse: 0.1408 - smape: 0.2632 - val_ia: 0.7884 - val_loss: 0.0057 - val_mae: 0.0539 - val_rmse: 0.0665 - val_smape: 0.1680

Epoch 77/128

2293/2293 - 10s - 4ms/step - ia: 0.9313 - loss: 0.0210 - mae: 0.1075 - rmse: 0.1402 - smape: 0.2600 - val_ia: 0.8047 - val_loss: 0.0054 - val_mae: 0.0513 - val_rmse: 0.0641 - val_smape: 0.1629

Epoch 78/128

2293/2293 - 10s - 5ms/step - ia: 0.9309 - loss: 0.0212 - mae: 0.1082 - rmse: 0.1408 - smape: 0.2624 - val_ia: 0.7372 - val_loss: 0.0081 - val_mae: 0.0687 - val_rmse: 0.0809 - val_smape: 0.1872

Epoch 79/128

2293/2293 - 10s - 4ms/step - ia: 0.9314 - loss: 0.0209 - mae: 0.1074 - rmse: 0.1399 - smape: 0.2607 - val_ia: 0.7889 - val_loss: 0.0059 - val_mae: 0.0547 - val_rmse: 0.0673 - val_smape: 0.1688

Epoch 80/128

2293/2293 - 6s - 2ms/step - ia: 0.9315 - loss: 0.0208 - mae: 0.1073 - rmse: 0.1395 - smape: 0.2620 - val_ia: 0.7650 - val_loss: 0.0065 - val_mae: 0.0599 - val_rmse: 0.0723 - val_smape: 0.1755

Epoch 81/128

2293/2293 - 10s - 4ms/step - ia: 0.9318 - loss: 0.0206 - mae: 0.1068 - rmse: 0.1390 - smape: 0.2611 - val_ia: 0.7930 - val_loss: 0.0055 - val_mae: 0.0530 - val_rmse: 0.0655 - val_smape: 0.1677

Epoch 82/128

2293/2293 - 6s - 2ms/step - ia: 0.9316 - loss: 0.0207 - mae: 0.1070 - rmse: 0.1392 - smape: 0.2587 - val_ia: 0.7485 - val_loss: 0.0075 - val_mae: 0.0653 - val_rmse: 0.0775 - val_smape: 0.1839

Epoch 83/128

2293/2293 - 6s - 3ms/step - ia: 0.9317 - loss: 0.0206 - mae: 0.1068 - rmse: 0.1391 - smape: 0.2583 - val_ia: 0.7787 - val_loss: 0.0058 - val_mae: 0.0556 - val_rmse: 0.0679 - val_smape: 0.1692

Epoch 84/128

2293/2293 - 11s - 5ms/step - ia: 0.9321 - loss: 0.0204 - mae: 0.1065 - rmse: 0.1386 - smape: 0.2589 - val_ia: 0.7743 - val_loss: 0.0063 - val_mae: 0.0581 - val_rmse: 0.0706 - val_smape: 0.1757

Epoch 85/128

2293/2293 - 10s - 4ms/step - ia: 0.9318 - loss: 0.0207 - mae: 0.1069 - rmse: 0.1393 - smape: 0.2572 - val_ia: 0.7580 - val_loss: 0.0068 - val_mae: 0.0617 - val_rmse: 0.0739 - val_smape: 0.1828

Epoch 86/128

2293/2293 - 6s - 3ms/step - ia: 0.9312 - loss: 0.0209 - mae: 0.1075 - rmse: 0.1399 - smape: 0.2591 - val_ia: 0.8134 - val_loss: 0.0050 - val_mae: 0.0490 - val_rmse: 0.0616 - val_smape: 0.1600

Epoch 87/128

2293/2293 - 6s - 3ms/step - ia: 0.9317 - loss: 0.0208 - mae: 0.1069 - rmse: 0.1396 - smape: 0.2577 - val_ia: 0.7870 - val_loss: 0.0057 - val_mae: 0.0543 - val_rmse: 0.0667 - val_smape: 0.1658

Epoch 88/128

2293/2293 - 10s - 5ms/step - ia: 0.9322 - loss: 0.0207 - mae: 0.1064 - rmse: 0.1392 - smape: 0.2569 - val_ia: 0.7872 - val_loss: 0.0056 - val_mae: 0.0539 - val_rmse: 0.0664 - val_smape: 0.1632

Epoch 89/128

2293/2293 - 10s - 4ms/step - ia: 0.9323 - loss: 0.0206 - mae: 0.1062 - rmse: 0.1387 - smape: 0.2568 - val_ia: 0.7482 - val_loss: 0.0071 - val_mae: 0.0645 - val_rmse: 0.0766 - val_smape: 0.1951

Epoch 90/128

2293/2293 - 6s - 3ms/step - ia: 0.9325 - loss: 0.0204 - mae: 0.1058 - rmse: 0.1380 - smape: 0.2558 - val_ia: 0.7904 - val_loss: 0.0056 - val_mae: 0.0540 - val_rmse: 0.0662 - val_smape: 0.1721

Epoch 91/128

2293/2293 - 6s - 3ms/step - ia: 0.9322 - loss: 0.0205 - mae: 0.1064 - rmse: 0.1382 - smape: 0.2591 - val_ia: 0.7870 - val_loss: 0.0059 - val_mae: 0.0553 - val_rmse: 0.0678 - val_smape: 0.1695

Epoch 92/128

2293/2293 - 5s - 2ms/step - ia: 0.9325 - loss: 0.0204 - mae: 0.1057 - rmse: 0.1382 - smape: 0.2558 - val_ia: 0.7842 - val_loss: 0.0055 - val_mae: 0.0538 - val_rmse: 0.0662 - val_smape: 0.1653

Epoch 93/128

2293/2293 - 5s - 2ms/step - ia: 0.9321 - loss: 0.0205 - mae: 0.1064 - rmse: 0.1386 - smape: 0.2574 - val_ia: 0.7935 - val_loss: 0.0054 - val_mae: 0.0525 - val_rmse: 0.0649 - val_smape: 0.1648

Epoch 94/128

2293/2293 - 5s - 2ms/step - ia: 0.9316 - loss: 0.0208 - mae: 0.1069 - rmse: 0.1395 - smape: 0.2566 - val_ia: 0.7812 - val_loss: 0.0057 - val_mae: 0.0549 - val_rmse: 0.0673 - val_smape: 0.1656

Epoch 95/128

2293/2293 - 6s - 3ms/step - ia: 0.9321 - loss: 0.0203 - mae: 0.1061 - rmse: 0.1380 - smape: 0.2559 - val_ia: 0.7829 - val_loss: 0.0057 - val_mae: 0.0550 - val_rmse: 0.0671 - val_smape: 0.1685

Epoch 96/128

2293/2293 - 10s - 5ms/step - ia: 0.9321 - loss: 0.0206 - mae: 0.1064 - rmse: 0.1390 - smape: 0.2566 - val_ia: 0.7440 - val_loss: 0.0073 - val_mae: 0.0654 - val_rmse: 0.0773 - val_smape: 0.1892

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4586/4586 - 15s - 3ms/step - ia: 0.2428 - loss: 6.1339 - mae: 1.7251 - rmse: 2.3036 - smape: 1.5843 - val_ia: 0.1086 - val_loss: 2.9219 - val_mae: 1.3723 - val_rmse: 1.3936 - val_smape: 1.4881

Epoch 2/128

4586/4586 - 10s - 2ms/step - ia: 0.2575 - loss: 4.7624 - mae: 1.5512 - rmse: 2.0452 - smape: 1.5651 - val_ia: 0.1136 - val_loss: 2.4817 - val_mae: 1.2723 - val_rmse: 1.2937 - val_smape: 1.4906

Epoch 3/128

4586/4586 - 10s - 2ms/step - ia: 0.2686 - loss: 3.8076 - mae: 1.4130 - rmse: 1.8386 - smape: 1.5601 - val_ia: 0.1155 - val_loss: 2.1434 - val_mae: 1.1890 - val_rmse: 1.2100 - val_smape: 1.4956

Epoch 4/128

4586/4586 - 10s - 2ms/step - ia: 0.2803 - loss: 3.0000 - mae: 1.2774 - rmse: 1.6365 - smape: 1.5520 - val_ia: 0.1163 - val_loss: 1.8907 - val_mae: 1.1221 - val_rmse: 1.1427 - val_smape: 1.5051

Epoch 5/128

4586/4586 - 23s - 5ms/step - ia: 0.2880 - loss: 2.5092 - mae: 1.1879 - rmse: 1.5056 - smape: 1.5441 - val_ia: 0.1182 - val_loss: 1.6914 - val_mae: 1.0655 - val_rmse: 1.0860 - val_smape: 1.5173

Epoch 6/128

4586/4586 - 9s - 2ms/step - ia: 0.2922 - loss: 2.1236 - mae: 1.1100 - rmse: 1.3894 - smape: 1.5489 - val_ia: 0.1214 - val_loss: 1.5426 - val_mae: 1.0200 - val_rmse: 1.0405 - val_smape: 1.5284

Epoch 7/128

4586/4586 - 12s - 3ms/step - ia: 0.2964 - loss: 1.8698 - mae: 1.0528 - rmse: 1.3071 - smape: 1.5471 - val_ia: 0.1242 - val_loss: 1.4227 - val_mae: 0.9811 - val_rmse: 1.0015 - val_smape: 1.5378

Epoch 8/128

4586/4586 - 10s - 2ms/step - ia: 0.3034 - loss: 1.6520 - mae: 0.9979 - rmse: 1.2338 - smape: 1.5377 - val_ia: 0.1267 - val_loss: 1.3239 - val_mae: 0.9476 - val_rmse: 0.9678 - val_smape: 1.5454

Epoch 9/128

4586/4586 - 10s - 2ms/step - ia: 0.3079 - loss: 1.5099 - mae: 0.9634 - rmse: 1.1804 - smape: 1.5384 - val_ia: 0.1296 - val_loss: 1.2380 - val_mae: 0.9172 - val_rmse: 0.9372 - val_smape: 1.5517

Epoch 10/128

4586/4586 - 7s - 2ms/step - ia: 0.3151 - loss: 1.3776 - mae: 0.9271 - rmse: 1.1310 - smape: 1.5316 - val_ia: 0.1316 - val_loss: 1.1667 - val_mae: 0.8914 - val_rmse: 0.9111 - val_smape: 1.5574

Epoch 11/128

4586/4586 - 11s - 2ms/step - ia: 0.3174 - loss: 1.2924 - mae: 0.9012 - rmse: 1.0959 - smape: 1.5233 - val_ia: 0.1332 - val_loss: 1.1026 - val_mae: 0.8675 - val_rmse: 0.8870 - val_smape: 1.5596

Epoch 12/128

4586/4586 - 20s - 4ms/step - ia: 0.3255 - loss: 1.2180 - mae: 0.8776 - rmse: 1.0643 - smape: 1.5222 - val_ia: 0.1345 - val_loss: 1.0486 - val_mae: 0.8469 - val_rmse: 0.8661 - val_smape: 1.5604

Epoch 13/128

4586/4586 - 20s - 4ms/step - ia: 0.3288 - loss: 1.1645 - mae: 0.8600 - rmse: 1.0417 - smape: 1.5083 - val_ia: 0.1365 - val_loss: 0.9971 - val_mae: 0.8266 - val_rmse: 0.8455 - val_smape: 1.5575

Epoch 14/128

4586/4586 - 10s - 2ms/step - ia: 0.3336 - loss: 1.1148 - mae: 0.8446 - rmse: 1.0214 - smape: 1.4980 - val_ia: 0.1385 - val_loss: 0.9509 - val_mae: 0.8078 - val_rmse: 0.8264 - val_smape: 1.5514

Epoch 15/128

4586/4586 - 10s - 2ms/step - ia: 0.3411 - loss: 1.0725 - mae: 0.8254 - rmse: 1.0006 - smape: 1.4881 - val_ia: 0.1407 - val_loss: 0.9141 - val_mae: 0.7925 - val_rmse: 0.8109 - val_smape: 1.5458

Epoch 16/128

4586/4586 - 10s - 2ms/step - ia: 0.3450 - loss: 1.0336 - mae: 0.8155 - rmse: 0.9838 - smape: 1.4825 - val_ia: 0.1422 - val_loss: 0.8824 - val_mae: 0.7792 - val_rmse: 0.7973 - val_smape: 1.5393

Epoch 17/128

4586/4586 - 11s - 2ms/step - ia: 0.3530 - loss: 0.9911 - mae: 0.7998 - rmse: 0.9656 - smape: 1.4687 - val_ia: 0.1436 - val_loss: 0.8560 - val_mae: 0.7678 - val_rmse: 0.7856 - val_smape: 1.5333

Epoch 18/128

4586/4586 - 10s - 2ms/step - ia: 0.3533 - loss: 0.9691 - mae: 0.7930 - rmse: 0.9547 - smape: 1.4666 - val_ia: 0.1448 - val_loss: 0.8336 - val_mae: 0.7581 - val_rmse: 0.7757 - val_smape: 1.5279

Epoch 19/128

4586/4586 - 10s - 2ms/step - ia: 0.3584 - loss: 0.9482 - mae: 0.7813 - rmse: 0.9444 - smape: 1.4493 - val_ia: 0.1460 - val_loss: 0.8132 - val_mae: 0.7489 - val_rmse: 0.7663 - val_smape: 1.5211

Epoch 20/128

4586/4586 - 11s - 2ms/step - ia: 0.3590 - loss: 0.9232 - mae: 0.7749 - rmse: 0.9335 - smape: 1.4493 - val_ia: 0.1472 - val_loss: 0.7942 - val_mae: 0.7404 - val_rmse: 0.7577 - val_smape: 1.5145

Epoch 21/128

4586/4586 - 20s - 4ms/step - ia: 0.3671 - loss: 0.9059 - mae: 0.7664 - rmse: 0.9248 - smape: 1.4351 - val_ia: 0.1482 - val_loss: 0.7775 - val_mae: 0.7329 - val_rmse: 0.7500 - val_smape: 1.5088

Epoch 22/128

4586/4586 - 11s - 2ms/step - ia: 0.3658 - loss: 0.8860 - mae: 0.7605 - rmse: 0.9157 - smape: 1.4367 - val_ia: 0.1487 - val_loss: 0.7647 - val_mae: 0.7272 - val_rmse: 0.7441 - val_smape: 1.5058

Epoch 23/128

4586/4586 - 20s - 4ms/step - ia: 0.3666 - loss: 0.8806 - mae: 0.7571 - rmse: 0.9131 - smape: 1.4284 - val_ia: 0.1497 - val_loss: 0.7503 - val_mae: 0.7205 - val_rmse: 0.7373 - val_smape: 1.5000

Epoch 24/128

4586/4586 - 11s - 2ms/step - ia: 0.3687 - loss: 0.8624 - mae: 0.7510 - rmse: 0.9041 - smape: 1.4246 - val_ia: 0.1505 - val_loss: 0.7368 - val_mae: 0.7143 - val_rmse: 0.7310 - val_smape: 1.4946

Epoch 25/128

4586/4586 - 11s - 2ms/step - ia: 0.3697 - loss: 0.8631 - mae: 0.7501 - rmse: 0.9035 - smape: 1.4196 - val_ia: 0.1513 - val_loss: 0.7252 - val_mae: 0.7089 - val_rmse: 0.7255 - val_smape: 1.4900

Epoch 26/128

4586/4586 - 10s - 2ms/step - ia: 0.3723 - loss: 0.8481 - mae: 0.7446 - rmse: 0.8976 - smape: 1.4128 - val_ia: 0.1523 - val_loss: 0.7132 - val_mae: 0.7031 - val_rmse: 0.7195 - val_smape: 1.4833

Epoch 27/128

4586/4586 - 13s - 3ms/step - ia: 0.3724 - loss: 0.8393 - mae: 0.7405 - rmse: 0.8921 - smape: 1.4095 - val_ia: 0.1536 - val_loss: 0.7001 - val_mae: 0.6967 - val_rmse: 0.7131 - val_smape: 1.4750

Epoch 28/128

4586/4586 - 13s - 3ms/step - ia: 0.3774 - loss: 0.8244 - mae: 0.7350 - rmse: 0.8841 - smape: 1.4021 - val_ia: 0.1541 - val_loss: 0.6924 - val_mae: 0.6932 - val_rmse: 0.7094 - val_smape: 1.4728

Epoch 29/128

4586/4586 - 17s - 4ms/step - ia: 0.3772 - loss: 0.8172 - mae: 0.7322 - rmse: 0.8809 - smape: 1.3969 - val_ia: 0.1549 - val_loss: 0.6830 - val_mae: 0.6886 - val_rmse: 0.7047 - val_smape: 1.4673

Epoch 30/128

4586/4586 - 11s - 2ms/step - ia: 0.3832 - loss: 0.8038 - mae: 0.7248 - rmse: 0.8734 - smape: 1.3827 - val_ia: 0.1562 - val_loss: 0.6722 - val_mae: 0.6831 - val_rmse: 0.6991 - val_smape: 1.4585

Epoch 31/128

4586/4586 - 20s - 4ms/step - ia: 0.3827 - loss: 0.7976 - mae: 0.7237 - rmse: 0.8706 - smape: 1.3853 - val_ia: 0.1569 - val_loss: 0.6640 - val_mae: 0.6790 - val_rmse: 0.6949 - val_smape: 1.4532

Epoch 32/128

4586/4586 - 11s - 2ms/step - ia: 0.3866 - loss: 0.7874 - mae: 0.7183 - rmse: 0.8654 - smape: 1.3705 - val_ia: 0.1577 - val_loss: 0.6555 - val_mae: 0.6747 - val_rmse: 0.6905 - val_smape: 1.4473

Epoch 33/128

4586/4586 - 11s - 2ms/step - ia: 0.3893 - loss: 0.7801 - mae: 0.7154 - rmse: 0.8614 - smape: 1.3698 - val_ia: 0.1581 - val_loss: 0.6489 - val_mae: 0.6714 - val_rmse: 0.6871 - val_smape: 1.4436

Epoch 34/128

4586/4586 - 10s - 2ms/step - ia: 0.3899 - loss: 0.7726 - mae: 0.7123 - rmse: 0.8564 - smape: 1.3640 - val_ia: 0.1591 - val_loss: 0.6403 - val_mae: 0.6669 - val_rmse: 0.6825 - val_smape: 1.4353

Epoch 35/128

4586/4586 - 9s - 2ms/step - ia: 0.3894 - loss: 0.7718 - mae: 0.7124 - rmse: 0.8564 - smape: 1.3630 - val_ia: 0.1596 - val_loss: 0.6342 - val_mae: 0.6638 - val_rmse: 0.6793 - val_smape: 1.4307

Epoch 36/128

4586/4586 - 9s - 2ms/step - ia: 0.3934 - loss: 0.7609 - mae: 0.7069 - rmse: 0.8506 - smape: 1.3567 - val_ia: 0.1604 - val_loss: 0.6267 - val_mae: 0.6598 - val_rmse: 0.6753 - val_smape: 1.4236

Epoch 37/128

4586/4586 - 9s - 2ms/step - ia: 0.3911 - loss: 0.7658 - mae: 0.7091 - rmse: 0.8534 - smape: 1.3544 - val_ia: 0.1610 - val_loss: 0.6209 - val_mae: 0.6568 - val_rmse: 0.6722 - val_smape: 1.4191

Epoch 38/128

4586/4586 - 8s - 2ms/step - ia: 0.3977 - loss: 0.7574 - mae: 0.7038 - rmse: 0.8483 - smape: 1.3425 - val_ia: 0.1616 - val_loss: 0.6147 - val_mae: 0.6534 - val_rmse: 0.6687 - val_smape: 1.4132

Epoch 39/128

4586/4586 - 7s - 2ms/step - ia: 0.3967 - loss: 0.7493 - mae: 0.7016 - rmse: 0.8447 - smape: 1.3415 - val_ia: 0.1621 - val_loss: 0.6094 - val_mae: 0.6506 - val_rmse: 0.6658 - val_smape: 1.4085

Epoch 40/128

4586/4586 - 9s - 2ms/step - ia: 0.4003 - loss: 0.7447 - mae: 0.6982 - rmse: 0.8425 - smape: 1.3317 - val_ia: 0.1622 - val_loss: 0.6055 - val_mae: 0.6486 - val_rmse: 0.6638 - val_smape: 1.4056

Epoch 41/128

4586/4586 - 9s - 2ms/step - ia: 0.4019 - loss: 0.7391 - mae: 0.6957 - rmse: 0.8382 - smape: 1.3290 - val_ia: 0.1625 - val_loss: 0.6006 - val_mae: 0.6460 - val_rmse: 0.6611 - val_smape: 1.4016

Epoch 42/128

4586/4586 - 9s - 2ms/step - ia: 0.4024 - loss: 0.7393 - mae: 0.6959 - rmse: 0.8385 - smape: 1.3268 - val_ia: 0.1632 - val_loss: 0.5949 - val_mae: 0.6429 - val_rmse: 0.6578 - val_smape: 1.3953

Epoch 43/128

4586/4586 - 10s - 2ms/step - ia: 0.4043 - loss: 0.7357 - mae: 0.6932 - rmse: 0.8355 - smape: 1.3210 - val_ia: 0.1639 - val_loss: 0.5895 - val_mae: 0.6397 - val_rmse: 0.6546 - val_smape: 1.3891

Epoch 44/128

4586/4586 - 10s - 2ms/step - ia: 0.4072 - loss: 0.7274 - mae: 0.6900 - rmse: 0.8323 - smape: 1.3137 - val_ia: 0.1647 - val_loss: 0.5844 - val_mae: 0.6368 - val_rmse: 0.6516 - val_smape: 1.3826

Epoch 45/128

4586/4586 - 8s - 2ms/step - ia: 0.4094 - loss: 0.7196 - mae: 0.6852 - rmse: 0.8269 - smape: 1.3073 - val_ia: 0.1653 - val_loss: 0.5795 - val_mae: 0.6339 - val_rmse: 0.6487 - val_smape: 1.3765

Epoch 46/128

4586/4586 - 9s - 2ms/step - ia: 0.4100 - loss: 0.7191 - mae: 0.6865 - rmse: 0.8274 - smape: 1.3056 - val_ia: 0.1654 - val_loss: 0.5766 - val_mae: 0.6324 - val_rmse: 0.6471 - val_smape: 1.3745

Epoch 47/128

4586/4586 - 9s - 2ms/step - ia: 0.4105 - loss: 0.7143 - mae: 0.6836 - rmse: 0.8245 - smape: 1.2978 - val_ia: 0.1659 - val_loss: 0.5726 - val_mae: 0.6301 - val_rmse: 0.6448 - val_smape: 1.3700

Epoch 48/128

4586/4586 - 10s - 2ms/step - ia: 0.4141 - loss: 0.7091 - mae: 0.6805 - rmse: 0.8205 - smape: 1.2934 - val_ia: 0.1666 - val_loss: 0.5681 - val_mae: 0.6275 - val_rmse: 0.6421 - val_smape: 1.3643

Epoch 49/128

4586/4586 - 9s - 2ms/step - ia: 0.4147 - loss: 0.7146 - mae: 0.6822 - rmse: 0.8236 - smape: 1.2890 - val_ia: 0.1667 - val_loss: 0.5658 - val_mae: 0.6262 - val_rmse: 0.6407 - val_smape: 1.3625

Epoch 50/128

4586/4586 - 9s - 2ms/step - ia: 0.4137 - loss: 0.7116 - mae: 0.6811 - rmse: 0.8227 - smape: 1.2869 - val_ia: 0.1676 - val_loss: 0.5606 - val_mae: 0.6230 - val_rmse: 0.6375 - val_smape: 1.3551

Epoch 51/128

4586/4586 - 10s - 2ms/step - ia: 0.4127 - loss: 0.7057 - mae: 0.6794 - rmse: 0.8196 - smape: 1.2872 - val_ia: 0.1685 - val_loss: 0.5554 - val_mae: 0.6199 - val_rmse: 0.6343 - val_smape: 1.3477

Epoch 52/128

4586/4586 - 11s - 2ms/step - ia: 0.4174 - loss: 0.7022 - mae: 0.6767 - rmse: 0.8163 - smape: 1.2811 - val_ia: 0.1691 - val_loss: 0.5522 - val_mae: 0.6180 - val_rmse: 0.6324 - val_smape: 1.3435

Epoch 53/128

4586/4586 - 10s - 2ms/step - ia: 0.4165 - loss: 0.7012 - mae: 0.6764 - rmse: 0.8165 - smape: 1.2768 - val_ia: 0.1693 - val_loss: 0.5493 - val_mae: 0.6163 - val_rmse: 0.6306 - val_smape: 1.3400

Epoch 54/128

4586/4586 - 10s - 2ms/step - ia: 0.4213 - loss: 0.6937 - mae: 0.6733 - rmse: 0.8122 - smape: 1.2724 - val_ia: 0.1695 - val_loss: 0.5465 - val_mae: 0.6147 - val_rmse: 0.6291 - val_smape: 1.3372

Epoch 55/128

4586/4586 - 9s - 2ms/step - ia: 0.4185 - loss: 0.6926 - mae: 0.6723 - rmse: 0.8114 - smape: 1.2706 - val_ia: 0.1704 - val_loss: 0.5425 - val_mae: 0.6122 - val_rmse: 0.6265 - val_smape: 1.3310

Epoch 56/128

4586/4586 - 9s - 2ms/step - ia: 0.4258 - loss: 0.6831 - mae: 0.6661 - rmse: 0.8059 - smape: 1.2588 - val_ia: 0.1710 - val_loss: 0.5387 - val_mae: 0.6099 - val_rmse: 0.6241 - val_smape: 1.3254

Epoch 57/128

4586/4586 - 9s - 2ms/step - ia: 0.4237 - loss: 0.6884 - mae: 0.6687 - rmse: 0.8087 - smape: 1.2608 - val_ia: 0.1719 - val_loss: 0.5346 - val_mae: 0.6073 - val_rmse: 0.6215 - val_smape: 1.3191

Epoch 58/128

4586/4586 - 9s - 2ms/step - ia: 0.4253 - loss: 0.6861 - mae: 0.6689 - rmse: 0.8068 - smape: 1.2606 - val_ia: 0.1719 - val_loss: 0.5327 - val_mae: 0.6063 - val_rmse: 0.6205 - val_smape: 1.3175

Epoch 59/128

4586/4586 - 9s - 2ms/step - ia: 0.4261 - loss: 0.6817 - mae: 0.6657 - rmse: 0.8040 - smape: 1.2534 - val_ia: 0.1725 - val_loss: 0.5296 - val_mae: 0.6044 - val_rmse: 0.6185 - val_smape: 1.3128

Epoch 60/128

4586/4586 - 9s - 2ms/step - ia: 0.4281 - loss: 0.6792 - mae: 0.6636 - rmse: 0.8031 - smape: 1.2473 - val_ia: 0.1725 - val_loss: 0.5277 - val_mae: 0.6033 - val_rmse: 0.6175 - val_smape: 1.3105

Epoch 61/128

4586/4586 - 9s - 2ms/step - ia: 0.4277 - loss: 0.6742 - mae: 0.6624 - rmse: 0.7997 - smape: 1.2475 - val_ia: 0.1732 - val_loss: 0.5243 - val_mae: 0.6013 - val_rmse: 0.6154 - val_smape: 1.3052

Epoch 62/128

4586/4586 - 13s - 3ms/step - ia: 0.4331 - loss: 0.6740 - mae: 0.6610 - rmse: 0.7990 - smape: 1.2404 - val_ia: 0.1736 - val_loss: 0.5217 - val_mae: 0.5997 - val_rmse: 0.6137 - val_smape: 1.3011

Epoch 63/128

4586/4586 - 17s - 4ms/step - ia: 0.4370 - loss: 0.6656 - mae: 0.6563 - rmse: 0.7946 - smape: 1.2326 - val_ia: 0.1740 - val_loss: 0.5187 - val_mae: 0.5979 - val_rmse: 0.6119 - val_smape: 1.2970

Epoch 64/128

4586/4586 - 12s - 3ms/step - ia: 0.4364 - loss: 0.6669 - mae: 0.6557 - rmse: 0.7952 - smape: 1.2285 - val_ia: 0.1745 - val_loss: 0.5163 - val_mae: 0.5963 - val_rmse: 0.6104 - val_smape: 1.2931

Epoch 65/128

4586/4586 - 9s - 2ms/step - ia: 0.4351 - loss: 0.6637 - mae: 0.6567 - rmse: 0.7945 - smape: 1.2314 - val_ia: 0.1750 - val_loss: 0.5137 - val_mae: 0.5947 - val_rmse: 0.6087 - val_smape: 1.2885

Epoch 66/128

4586/4586 - 11s - 2ms/step - ia: 0.4383 - loss: 0.6628 - mae: 0.6547 - rmse: 0.7928 - smape: 1.2254 - val_ia: 0.1755 - val_loss: 0.5114 - val_mae: 0.5932 - val_rmse: 0.6072 - val_smape: 1.2849

Epoch 67/128

4586/4586 - 9s - 2ms/step - ia: 0.4358 - loss: 0.6635 - mae: 0.6556 - rmse: 0.7930 - smape: 1.2283 - val_ia: 0.1765 - val_loss: 0.5076 - val_mae: 0.5907 - val_rmse: 0.6047 - val_smape: 1.2783

Epoch 68/128

4586/4586 - 9s - 2ms/step - ia: 0.4381 - loss: 0.6629 - mae: 0.6541 - rmse: 0.7925 - smape: 1.2235 - val_ia: 0.1766 - val_loss: 0.5064 - val_mae: 0.5900 - val_rmse: 0.6040 - val_smape: 1.2763

Epoch 69/128

4586/4586 - 9s - 2ms/step - ia: 0.4389 - loss: 0.6582 - mae: 0.6521 - rmse: 0.7902 - smape: 1.2192 - val_ia: 0.1775 - val_loss: 0.5030 - val_mae: 0.5878 - val_rmse: 0.6017 - val_smape: 1.2702

Epoch 70/128

4586/4586 - 10s - 2ms/step - ia: 0.4419 - loss: 0.6526 - mae: 0.6490 - rmse: 0.7865 - smape: 1.2118 - val_ia: 0.1781 - val_loss: 0.5001 - val_mae: 0.5860 - val_rmse: 0.5999 - val_smape: 1.2654

Epoch 71/128

4586/4586 - 10s - 2ms/step - ia: 0.4450 - loss: 0.6499 - mae: 0.6475 - rmse: 0.7846 - smape: 1.2113 - val_ia: 0.1783 - val_loss: 0.4986 - val_mae: 0.5851 - val_rmse: 0.5990 - val_smape: 1.2631

Epoch 72/128

4586/4586 - 11s - 2ms/step - ia: 0.4442 - loss: 0.6480 - mae: 0.6473 - rmse: 0.7841 - smape: 1.2085 - val_ia: 0.1787 - val_loss: 0.4964 - val_mae: 0.5837 - val_rmse: 0.5975 - val_smape: 1.2593

Epoch 73/128

4586/4586 - 9s - 2ms/step - ia: 0.4464 - loss: 0.6464 - mae: 0.6452 - rmse: 0.7831 - smape: 1.2037 - val_ia: 0.1788 - val_loss: 0.4949 - val_mae: 0.5828 - val_rmse: 0.5967 - val_smape: 1.2574

Epoch 74/128

4586/4586 - 9s - 2ms/step - ia: 0.4445 - loss: 0.6458 - mae: 0.6461 - rmse: 0.7828 - smape: 1.2047 - val_ia: 0.1797 - val_loss: 0.4915 - val_mae: 0.5806 - val_rmse: 0.5944 - val_smape: 1.2513

Epoch 75/128

4586/4586 - 9s - 2ms/step - ia: 0.4483 - loss: 0.6469 - mae: 0.6439 - rmse: 0.7824 - smape: 1.1993 - val_ia: 0.1800 - val_loss: 0.4897 - val_mae: 0.5795 - val_rmse: 0.5933 - val_smape: 1.2485

Epoch 76/128

4586/4586 - 9s - 2ms/step - ia: 0.4522 - loss: 0.6386 - mae: 0.6410 - rmse: 0.7769 - smape: 1.1911 - val_ia: 0.1806 - val_loss: 0.4869 - val_mae: 0.5777 - val_rmse: 0.5915 - val_smape: 1.2437

Epoch 77/128

4586/4586 - 10s - 2ms/step - ia: 0.4498 - loss: 0.6381 - mae: 0.6412 - rmse: 0.7777 - smape: 1.1928 - val_ia: 0.1810 - val_loss: 0.4850 - val_mae: 0.5764 - val_rmse: 0.5902 - val_smape: 1.2401

Epoch 78/128

4586/4586 - 9s - 2ms/step - ia: 0.4517 - loss: 0.6362 - mae: 0.6400 - rmse: 0.7768 - smape: 1.1893 - val_ia: 0.1814 - val_loss: 0.4830 - val_mae: 0.5752 - val_rmse: 0.5890 - val_smape: 1.2368

Epoch 79/128

4586/4586 - 9s - 2ms/step - ia: 0.4509 - loss: 0.6375 - mae: 0.6395 - rmse: 0.7771 - smape: 1.1847 - val_ia: 0.1816 - val_loss: 0.4821 - val_mae: 0.5746 - val_rmse: 0.5885 - val_smape: 1.2352

Epoch 80/128

4586/4586 - 10s - 2ms/step - ia: 0.4521 - loss: 0.6385 - mae: 0.6403 - rmse: 0.7768 - smape: 1.1850 - val_ia: 0.1817 - val_loss: 0.4809 - val_mae: 0.5740 - val_rmse: 0.5879 - val_smape: 1.2337

Epoch 81/128

4586/4586 - 9s - 2ms/step - ia: 0.4552 - loss: 0.6321 - mae: 0.6375 - rmse: 0.7739 - smape: 1.1804 - val_ia: 0.1820 - val_loss: 0.4789 - val_mae: 0.5728 - val_rmse: 0.5866 - val_smape: 1.2303

Epoch 82/128

4586/4586 - 14s - 3ms/step - ia: 0.4573 - loss: 0.6280 - mae: 0.6345 - rmse: 0.7706 - smape: 1.1724 - val_ia: 0.1826 - val_loss: 0.4761 - val_mae: 0.5710 - val_rmse: 0.5848 - val_smape: 1.2256

Epoch 83/128

4586/4586 - 11s - 2ms/step - ia: 0.4581 - loss: 0.6288 - mae: 0.6345 - rmse: 0.7716 - smape: 1.1719 - val_ia: 0.1826 - val_loss: 0.4750 - val_mae: 0.5704 - val_rmse: 0.5843 - val_smape: 1.2243

Epoch 84/128

4586/4586 - 10s - 2ms/step - ia: 0.4575 - loss: 0.6287 - mae: 0.6341 - rmse: 0.7715 - smape: 1.1725 - val_ia: 0.1829 - val_loss: 0.4738 - val_mae: 0.5697 - val_rmse: 0.5835 - val_smape: 1.2224

Epoch 85/128

4586/4586 - 11s - 2ms/step - ia: 0.4593 - loss: 0.6281 - mae: 0.6342 - rmse: 0.7707 - smape: 1.1722 - val_ia: 0.1831 - val_loss: 0.4723 - val_mae: 0.5687 - val_rmse: 0.5826 - val_smape: 1.2195

Epoch 86/128

4586/4586 - 11s - 2ms/step - ia: 0.4603 - loss: 0.6247 - mae: 0.6319 - rmse: 0.7688 - smape: 1.1638 - val_ia: 0.1838 - val_loss: 0.4694 - val_mae: 0.5668 - val_rmse: 0.5806 - val_smape: 1.2147

Epoch 87/128

4586/4586 - 11s - 2ms/step - ia: 0.4621 - loss: 0.6201 - mae: 0.6298 - rmse: 0.7658 - smape: 1.1616 - val_ia: 0.1843 - val_loss: 0.4674 - val_mae: 0.5655 - val_rmse: 0.5794 - val_smape: 1.2115

Epoch 88/128

4586/4586 - 12s - 3ms/step - ia: 0.4595 - loss: 0.6238 - mae: 0.6319 - rmse: 0.7687 - smape: 1.1627 - val_ia: 0.1841 - val_loss: 0.4672 - val_mae: 0.5655 - val_rmse: 0.5793 - val_smape: 1.2109

Epoch 89/128

4586/4586 - 19s - 4ms/step - ia: 0.4642 - loss: 0.6163 - mae: 0.6276 - rmse: 0.7636 - smape: 1.1569 - val_ia: 0.1851 - val_loss: 0.4636 - val_mae: 0.5630 - val_rmse: 0.5768 - val_smape: 1.2040

Epoch 90/128

4586/4586 - 27s - 6ms/step - ia: 0.4655 - loss: 0.6133 - mae: 0.6265 - rmse: 0.7617 - smape: 1.1534 - val_ia: 0.1852 - val_loss: 0.4622 - val_mae: 0.5621 - val_rmse: 0.5759 - val_smape: 1.2016

Epoch 91/128

4586/4586 - 18s - 4ms/step - ia: 0.4642 - loss: 0.6157 - mae: 0.6281 - rmse: 0.7635 - smape: 1.1546 - val_ia: 0.1854 - val_loss: 0.4606 - val_mae: 0.5612 - val_rmse: 0.5750 - val_smape: 1.1991

Epoch 92/128

4586/4586 - 13s - 3ms/step - ia: 0.4640 - loss: 0.6158 - mae: 0.6275 - rmse: 0.7635 - smape: 1.1542 - val_ia: 0.1855 - val_loss: 0.4593 - val_mae: 0.5604 - val_rmse: 0.5743 - val_smape: 1.1969

Epoch 93/128

4586/4586 - 12s - 3ms/step - ia: 0.4650 - loss: 0.6136 - mae: 0.6268 - rmse: 0.7619 - smape: 1.1535 - val_ia: 0.1857 - val_loss: 0.4579 - val_mae: 0.5596 - val_rmse: 0.5734 - val_smape: 1.1943

Epoch 94/128

4586/4586 - 14s - 3ms/step - ia: 0.4677 - loss: 0.6134 - mae: 0.6256 - rmse: 0.7614 - smape: 1.1472 - val_ia: 0.1860 - val_loss: 0.4563 - val_mae: 0.5585 - val_rmse: 0.5723 - val_smape: 1.1913

Epoch 95/128

4586/4586 - 19s - 4ms/step - ia: 0.4686 - loss: 0.6090 - mae: 0.6234 - rmse: 0.7587 - smape: 1.1433 - val_ia: 0.1866 - val_loss: 0.4535 - val_mae: 0.5566 - val_rmse: 0.5704 - val_smape: 1.1862

Epoch 96/128

4586/4586 - 11s - 2ms/step - ia: 0.4712 - loss: 0.6060 - mae: 0.6220 - rmse: 0.7568 - smape: 1.1434 - val_ia: 0.1869 - val_loss: 0.4516 - val_mae: 0.5554 - val_rmse: 0.5692 - val_smape: 1.1829

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 4s - 15ms/step - ia: 0.7387 - loss: 0.2809 - mae: 0.4100 - rmse: 0.5136 - smape: 0.7567 - val_ia: 0.8299 - val_loss: 0.0906 - val_mae: 0.2389 - val_rmse: 0.2872 - val_smape: 0.5680

Epoch 2/128

287/287 - 2s - 5ms/step - ia: 0.8275 - loss: 0.1318 - mae: 0.2867 - rmse: 0.3619 - smape: 0.5885 - val_ia: 0.8894 - val_loss: 0.0372 - val_mae: 0.1503 - val_rmse: 0.1880 - val_smape: 0.4205

Epoch 3/128

287/287 - 1s - 4ms/step - ia: 0.8519 - loss: 0.0965 - mae: 0.2453 - rmse: 0.3095 - smape: 0.5331 - val_ia: 0.9025 - val_loss: 0.0289 - val_mae: 0.1321 - val_rmse: 0.1668 - val_smape: 0.3750

Epoch 4/128

287/287 - 1s - 4ms/step - ia: 0.8700 - loss: 0.0748 - mae: 0.2150 - rmse: 0.2725 - smape: 0.4857 - val_ia: 0.9127 - val_loss: 0.0235 - val_mae: 0.1177 - val_rmse: 0.1507 - val_smape: 0.3316

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.8852 - loss: 0.0581 - mae: 0.1890 - rmse: 0.2403 - smape: 0.4448 - val_ia: 0.9171 - val_loss: 0.0217 - val_mae: 0.1117 - val_rmse: 0.1449 - val_smape: 0.3125

Epoch 6/128

287/287 - 1s - 3ms/step - ia: 0.8958 - loss: 0.0480 - mae: 0.1715 - rmse: 0.2183 - smape: 0.4121 - val_ia: 0.9194 - val_loss: 0.0203 - val_mae: 0.1087 - val_rmse: 0.1401 - val_smape: 0.3040

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.9040 - loss: 0.0412 - mae: 0.1579 - rmse: 0.2022 - smape: 0.3853 - val_ia: 0.9223 - val_loss: 0.0190 - val_mae: 0.1048 - val_rmse: 0.1357 - val_smape: 0.2887

Epoch 8/128

287/287 - 1s - 4ms/step - ia: 0.9099 - loss: 0.0367 - mae: 0.1483 - rmse: 0.1907 - smape: 0.3662 - val_ia: 0.9277 - val_loss: 0.0170 - val_mae: 0.0977 - val_rmse: 0.1284 - val_smape: 0.2664

Epoch 9/128

287/287 - 1s - 4ms/step - ia: 0.9143 - loss: 0.0332 - mae: 0.1410 - rmse: 0.1815 - smape: 0.3531 - val_ia: 0.9292 - val_loss: 0.0162 - val_mae: 0.0961 - val_rmse: 0.1256 - val_smape: 0.2611

Epoch 10/128

287/287 - 1s - 4ms/step - ia: 0.9176 - loss: 0.0308 - mae: 0.1357 - rmse: 0.1748 - smape: 0.3396 - val_ia: 0.9322 - val_loss: 0.0151 - val_mae: 0.0912 - val_rmse: 0.1212 - val_smape: 0.2389

Epoch 11/128

287/287 - 1s - 5ms/step - ia: 0.9198 - loss: 0.0294 - mae: 0.1323 - rmse: 0.1708 - smape: 0.3317 - val_ia: 0.9356 - val_loss: 0.0141 - val_mae: 0.0870 - val_rmse: 0.1170 - val_smape: 0.2245

Epoch 12/128

287/287 - 1s - 5ms/step - ia: 0.9221 - loss: 0.0279 - mae: 0.1285 - rmse: 0.1661 - smape: 0.3243 - val_ia: 0.9376 - val_loss: 0.0132 - val_mae: 0.0847 - val_rmse: 0.1136 - val_smape: 0.2190

Epoch 13/128

287/287 - 1s - 4ms/step - ia: 0.9245 - loss: 0.0262 - mae: 0.1246 - rmse: 0.1609 - smape: 0.3191 - val_ia: 0.9378 - val_loss: 0.0129 - val_mae: 0.0843 - val_rmse: 0.1120 - val_smape: 0.2181

Epoch 14/128

287/287 - 2s - 5ms/step - ia: 0.9255 - loss: 0.0255 - mae: 0.1228 - rmse: 0.1590 - smape: 0.3125 - val_ia: 0.9378 - val_loss: 0.0127 - val_mae: 0.0839 - val_rmse: 0.1109 - val_smape: 0.2163

Epoch 15/128

287/287 - 1s - 4ms/step - ia: 0.9270 - loss: 0.0246 - mae: 0.1204 - rmse: 0.1560 - smape: 0.3065 - val_ia: 0.9414 - val_loss: 0.0116 - val_mae: 0.0793 - val_rmse: 0.1058 - val_smape: 0.2043

Epoch 16/128

287/287 - 2s - 5ms/step - ia: 0.9281 - loss: 0.0239 - mae: 0.1186 - rmse: 0.1538 - smape: 0.3033 - val_ia: 0.9430 - val_loss: 0.0112 - val_mae: 0.0772 - val_rmse: 0.1042 - val_smape: 0.1969

Epoch 17/128

287/287 - 1s - 5ms/step - ia: 0.9290 - loss: 0.0232 - mae: 0.1171 - rmse: 0.1516 - smape: 0.3021 - val_ia: 0.9442 - val_loss: 0.0107 - val_mae: 0.0754 - val_rmse: 0.1017 - val_smape: 0.1923

Epoch 18/128

287/287 - 2s - 9ms/step - ia: 0.9304 - loss: 0.0226 - mae: 0.1149 - rmse: 0.1496 - smape: 0.2956 - val_ia: 0.9430 - val_loss: 0.0108 - val_mae: 0.0768 - val_rmse: 0.1018 - val_smape: 0.1959

Epoch 19/128

287/287 - 1s - 4ms/step - ia: 0.9310 - loss: 0.0221 - mae: 0.1138 - rmse: 0.1479 - smape: 0.2940 - val_ia: 0.9428 - val_loss: 0.0109 - val_mae: 0.0771 - val_rmse: 0.1024 - val_smape: 0.1963

Epoch 20/128

287/287 - 1s - 4ms/step - ia: 0.9319 - loss: 0.0215 - mae: 0.1124 - rmse: 0.1459 - smape: 0.2891 - val_ia: 0.9411 - val_loss: 0.0111 - val_mae: 0.0792 - val_rmse: 0.1021 - val_smape: 0.2063

Epoch 21/128

287/287 - 1s - 3ms/step - ia: 0.9332 - loss: 0.0209 - mae: 0.1104 - rmse: 0.1437 - smape: 0.2869 - val_ia: 0.9431 - val_loss: 0.0106 - val_mae: 0.0765 - val_rmse: 0.1004 - val_smape: 0.1944

Epoch 22/128

287/287 - 1s - 4ms/step - ia: 0.9342 - loss: 0.0203 - mae: 0.1086 - rmse: 0.1417 - smape: 0.2819 - val_ia: 0.9455 - val_loss: 0.0101 - val_mae: 0.0732 - val_rmse: 0.0982 - val_smape: 0.1807

Epoch 23/128

287/287 - 2s - 6ms/step - ia: 0.9341 - loss: 0.0203 - mae: 0.1089 - rmse: 0.1415 - smape: 0.2820 - val_ia: 0.9469 - val_loss: 0.0096 - val_mae: 0.0718 - val_rmse: 0.0962 - val_smape: 0.1815

Epoch 24/128

287/287 - 2s - 8ms/step - ia: 0.9353 - loss: 0.0197 - mae: 0.1069 - rmse: 0.1397 - smape: 0.2768 - val_ia: 0.9415 - val_loss: 0.0111 - val_mae: 0.0782 - val_rmse: 0.1021 - val_smape: 0.1953

Epoch 25/128

287/287 - 2s - 6ms/step - ia: 0.9357 - loss: 0.0193 - mae: 0.1061 - rmse: 0.1383 - smape: 0.2747 - val_ia: 0.9445 - val_loss: 0.0103 - val_mae: 0.0744 - val_rmse: 0.0985 - val_smape: 0.1806

Epoch 26/128

287/287 - 1s - 5ms/step - ia: 0.9370 - loss: 0.0188 - mae: 0.1040 - rmse: 0.1361 - smape: 0.2704 - val_ia: 0.9461 - val_loss: 0.0096 - val_mae: 0.0727 - val_rmse: 0.0956 - val_smape: 0.1860

Epoch 27/128

287/287 - 1s - 4ms/step - ia: 0.9367 - loss: 0.0188 - mae: 0.1045 - rmse: 0.1362 - smape: 0.2729 - val_ia: 0.9427 - val_loss: 0.0106 - val_mae: 0.0765 - val_rmse: 0.1000 - val_smape: 0.1901

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.9370 - loss: 0.0186 - mae: 0.1040 - rmse: 0.1357 - smape: 0.2709 - val_ia: 0.9467 - val_loss: 0.0093 - val_mae: 0.0717 - val_rmse: 0.0941 - val_smape: 0.1827

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.9387 - loss: 0.0177 - mae: 0.1013 - rmse: 0.1323 - smape: 0.2644 - val_ia: 0.9449 - val_loss: 0.0100 - val_mae: 0.0741 - val_rmse: 0.0980 - val_smape: 0.1808

Epoch 30/128

287/287 - 2s - 8ms/step - ia: 0.9384 - loss: 0.0179 - mae: 0.1018 - rmse: 0.1329 - smape: 0.2672 - val_ia: 0.9454 - val_loss: 0.0100 - val_mae: 0.0732 - val_rmse: 0.0982 - val_smape: 0.1720

Epoch 31/128

287/287 - 1s - 4ms/step - ia: 0.9394 - loss: 0.0174 - mae: 0.1001 - rmse: 0.1311 - smape: 0.2622 - val_ia: 0.9449 - val_loss: 0.0100 - val_mae: 0.0736 - val_rmse: 0.0967 - val_smape: 0.1771

Epoch 32/128

287/287 - 1s - 3ms/step - ia: 0.9402 - loss: 0.0169 - mae: 0.0987 - rmse: 0.1293 - smape: 0.2600 - val_ia: 0.9453 - val_loss: 0.0100 - val_mae: 0.0733 - val_rmse: 0.0979 - val_smape: 0.1716

Epoch 33/128

287/287 - 1s - 4ms/step - ia: 0.9404 - loss: 0.0169 - mae: 0.0984 - rmse: 0.1292 - smape: 0.2590 - val_ia: 0.9472 - val_loss: 0.0092 - val_mae: 0.0708 - val_rmse: 0.0935 - val_smape: 0.1725

Epoch 34/128

287/287 - 2s - 5ms/step - ia: 0.9410 - loss: 0.0166 - mae: 0.0975 - rmse: 0.1280 - smape: 0.2564 - val_ia: 0.9458 - val_loss: 0.0096 - val_mae: 0.0725 - val_rmse: 0.0955 - val_smape: 0.1744

Epoch 35/128

287/287 - 1s - 3ms/step - ia: 0.9418 - loss: 0.0162 - mae: 0.0961 - rmse: 0.1262 - smape: 0.2537 - val_ia: 0.9447 - val_loss: 0.0099 - val_mae: 0.0738 - val_rmse: 0.0961 - val_smape: 0.1774

Epoch 36/128

287/287 - 1s - 5ms/step - ia: 0.9419 - loss: 0.0162 - mae: 0.0959 - rmse: 0.1264 - smape: 0.2544 - val_ia: 0.9482 - val_loss: 0.0090 - val_mae: 0.0695 - val_rmse: 0.0927 - val_smape: 0.1666

Epoch 37/128

287/287 - 1s - 5ms/step - ia: 0.9424 - loss: 0.0158 - mae: 0.0951 - rmse: 0.1248 - smape: 0.2544 - val_ia: 0.9458 - val_loss: 0.0095 - val_mae: 0.0724 - val_rmse: 0.0948 - val_smape: 0.1734

Epoch 38/128

287/287 - 1s - 5ms/step - ia: 0.9424 - loss: 0.0158 - mae: 0.0950 - rmse: 0.1249 - smape: 0.2525 - val_ia: 0.9457 - val_loss: 0.0096 - val_mae: 0.0727 - val_rmse: 0.0961 - val_smape: 0.1717

Epoch 39/128

287/287 - 1s - 4ms/step - ia: 0.9431 - loss: 0.0155 - mae: 0.0940 - rmse: 0.1234 - smape: 0.2483 - val_ia: 0.9462 - val_loss: 0.0094 - val_mae: 0.0719 - val_rmse: 0.0943 - val_smape: 0.1713

Epoch 40/128

287/287 - 1s - 5ms/step - ia: 0.9439 - loss: 0.0151 - mae: 0.0926 - rmse: 0.1219 - smape: 0.2476 - val_ia: 0.9478 - val_loss: 0.0088 - val_mae: 0.0697 - val_rmse: 0.0912 - val_smape: 0.1685

Epoch 41/128

287/287 - 1s - 5ms/step - ia: 0.9438 - loss: 0.0152 - mae: 0.0927 - rmse: 0.1224 - smape: 0.2463 - val_ia: 0.9459 - val_loss: 0.0095 - val_mae: 0.0722 - val_rmse: 0.0953 - val_smape: 0.1674

Epoch 42/128

287/287 - 1s - 5ms/step - ia: 0.9442 - loss: 0.0150 - mae: 0.0921 - rmse: 0.1214 - smape: 0.2456 - val_ia: 0.9456 - val_loss: 0.0096 - val_mae: 0.0725 - val_rmse: 0.0952 - val_smape: 0.1659

Epoch 43/128

287/287 - 1s - 5ms/step - ia: 0.9447 - loss: 0.0147 - mae: 0.0913 - rmse: 0.1203 - smape: 0.2450 - val_ia: 0.9508 - val_loss: 0.0079 - val_mae: 0.0660 - val_rmse: 0.0869 - val_smape: 0.1621

Epoch 44/128

287/287 - 1s - 4ms/step - ia: 0.9448 - loss: 0.0146 - mae: 0.0913 - rmse: 0.1200 - smape: 0.2445 - val_ia: 0.9480 - val_loss: 0.0086 - val_mae: 0.0694 - val_rmse: 0.0897 - val_smape: 0.1717

Epoch 45/128

287/287 - 1s - 5ms/step - ia: 0.9451 - loss: 0.0144 - mae: 0.0906 - rmse: 0.1191 - smape: 0.2428 - val_ia: 0.9504 - val_loss: 0.0080 - val_mae: 0.0663 - val_rmse: 0.0870 - val_smape: 0.1600

Epoch 46/128

287/287 - 1s - 5ms/step - ia: 0.9455 - loss: 0.0143 - mae: 0.0900 - rmse: 0.1188 - smape: 0.2399 - val_ia: 0.9501 - val_loss: 0.0081 - val_mae: 0.0668 - val_rmse: 0.0877 - val_smape: 0.1608

Epoch 47/128

287/287 - 1s - 5ms/step - ia: 0.9462 - loss: 0.0139 - mae: 0.0889 - rmse: 0.1170 - smape: 0.2373 - val_ia: 0.9508 - val_loss: 0.0081 - val_mae: 0.0660 - val_rmse: 0.0882 - val_smape: 0.1534

Epoch 48/128

287/287 - 1s - 5ms/step - ia: 0.9463 - loss: 0.0139 - mae: 0.0886 - rmse: 0.1170 - smape: 0.2386 - val_ia: 0.9511 - val_loss: 0.0079 - val_mae: 0.0656 - val_rmse: 0.0871 - val_smape: 0.1554

Epoch 49/128

287/287 - 1s - 4ms/step - ia: 0.9466 - loss: 0.0137 - mae: 0.0881 - rmse: 0.1162 - smape: 0.2367 - val_ia: 0.9540 - val_loss: 0.0070 - val_mae: 0.0617 - val_rmse: 0.0817 - val_smape: 0.1504

Epoch 50/128

287/287 - 1s - 4ms/step - ia: 0.9469 - loss: 0.0135 - mae: 0.0876 - rmse: 0.1153 - smape: 0.2365 - val_ia: 0.9519 - val_loss: 0.0076 - val_mae: 0.0646 - val_rmse: 0.0853 - val_smape: 0.1586

Epoch 51/128

287/287 - 1s - 4ms/step - ia: 0.9471 - loss: 0.0135 - mae: 0.0873 - rmse: 0.1152 - smape: 0.2335 - val_ia: 0.9522 - val_loss: 0.0076 - val_mae: 0.0642 - val_rmse: 0.0851 - val_smape: 0.1512

Epoch 52/128

287/287 - 1s - 3ms/step - ia: 0.9476 - loss: 0.0132 - mae: 0.0864 - rmse: 0.1141 - smape: 0.2322 - val_ia: 0.9547 - val_loss: 0.0068 - val_mae: 0.0608 - val_rmse: 0.0805 - val_smape: 0.1512

Epoch 53/128

287/287 - 2s - 5ms/step - ia: 0.9477 - loss: 0.0132 - mae: 0.0863 - rmse: 0.1139 - smape: 0.2315 - val_ia: 0.9538 - val_loss: 0.0071 - val_mae: 0.0621 - val_rmse: 0.0821 - val_smape: 0.1527

Epoch 54/128

287/287 - 1s - 4ms/step - ia: 0.9480 - loss: 0.0130 - mae: 0.0857 - rmse: 0.1133 - smape: 0.2319 - val_ia: 0.9533 - val_loss: 0.0071 - val_mae: 0.0624 - val_rmse: 0.0815 - val_smape: 0.1536

Epoch 55/128

287/287 - 1s - 3ms/step - ia: 0.9484 - loss: 0.0130 - mae: 0.0851 - rmse: 0.1130 - smape: 0.2293 - val_ia: 0.9561 - val_loss: 0.0064 - val_mae: 0.0589 - val_rmse: 0.0785 - val_smape: 0.1450

Epoch 56/128

287/287 - 1s - 3ms/step - ia: 0.9484 - loss: 0.0129 - mae: 0.0851 - rmse: 0.1129 - smape: 0.2297 - val_ia: 0.9522 - val_loss: 0.0073 - val_mae: 0.0638 - val_rmse: 0.0826 - val_smape: 0.1586

Epoch 57/128

287/287 - 1s - 3ms/step - ia: 0.9492 - loss: 0.0126 - mae: 0.0838 - rmse: 0.1112 - smape: 0.2279 - val_ia: 0.9572 - val_loss: 0.0061 - val_mae: 0.0574 - val_rmse: 0.0757 - val_smape: 0.1445

Epoch 58/128

287/287 - 1s - 5ms/step - ia: 0.9490 - loss: 0.0126 - mae: 0.0840 - rmse: 0.1114 - smape: 0.2271 - val_ia: 0.9556 - val_loss: 0.0067 - val_mae: 0.0596 - val_rmse: 0.0798 - val_smape: 0.1427

Epoch 59/128

287/287 - 1s - 3ms/step - ia: 0.9494 - loss: 0.0125 - mae: 0.0834 - rmse: 0.1109 - smape: 0.2265 - val_ia: 0.9542 - val_loss: 0.0068 - val_mae: 0.0612 - val_rmse: 0.0797 - val_smape: 0.1501

Epoch 60/128

287/287 - 1s - 5ms/step - ia: 0.9500 - loss: 0.0122 - mae: 0.0824 - rmse: 0.1095 - smape: 0.2236 - val_ia: 0.9562 - val_loss: 0.0064 - val_mae: 0.0588 - val_rmse: 0.0779 - val_smape: 0.1446

Epoch 61/128

287/287 - 1s - 4ms/step - ia: 0.9497 - loss: 0.0122 - mae: 0.0829 - rmse: 0.1096 - smape: 0.2250 - val_ia: 0.9561 - val_loss: 0.0063 - val_mae: 0.0588 - val_rmse: 0.0775 - val_smape: 0.1460

Epoch 62/128

287/287 - 1s - 4ms/step - ia: 0.9503 - loss: 0.0121 - mae: 0.0820 - rmse: 0.1092 - smape: 0.2236 - val_ia: 0.9595 - val_loss: 0.0057 - val_mae: 0.0546 - val_rmse: 0.0737 - val_smape: 0.1376

Epoch 63/128

287/287 - 1s - 3ms/step - ia: 0.9510 - loss: 0.0118 - mae: 0.0808 - rmse: 0.1074 - smape: 0.2192 - val_ia: 0.9572 - val_loss: 0.0060 - val_mae: 0.0573 - val_rmse: 0.0754 - val_smape: 0.1473

Epoch 64/128

287/287 - 1s - 3ms/step - ia: 0.9505 - loss: 0.0119 - mae: 0.0816 - rmse: 0.1082 - smape: 0.2206 - val_ia: 0.9605 - val_loss: 0.0052 - val_mae: 0.0531 - val_rmse: 0.0709 - val_smape: 0.1453

Epoch 65/128

287/287 - 1s - 3ms/step - ia: 0.9511 - loss: 0.0118 - mae: 0.0806 - rmse: 0.1075 - smape: 0.2184 - val_ia: 0.9578 - val_loss: 0.0058 - val_mae: 0.0565 - val_rmse: 0.0736 - val_smape: 0.1487

Epoch 66/128

287/287 - 1s - 3ms/step - ia: 0.9515 - loss: 0.0115 - mae: 0.0799 - rmse: 0.1062 - smape: 0.2177 - val_ia: 0.9586 - val_loss: 0.0055 - val_mae: 0.0555 - val_rmse: 0.0723 - val_smape: 0.1523

Epoch 67/128

287/287 - 1s - 5ms/step - ia: 0.9517 - loss: 0.0114 - mae: 0.0797 - rmse: 0.1058 - smape: 0.2185 - val_ia: 0.9548 - val_loss: 0.0064 - val_mae: 0.0605 - val_rmse: 0.0769 - val_smape: 0.1615

Epoch 68/128

287/287 - 1s - 5ms/step - ia: 0.9518 - loss: 0.0114 - mae: 0.0794 - rmse: 0.1059 - smape: 0.2174 - val_ia: 0.9562 - val_loss: 0.0061 - val_mae: 0.0586 - val_rmse: 0.0758 - val_smape: 0.1480

Epoch 69/128

287/287 - 1s - 4ms/step - ia: 0.9519 - loss: 0.0113 - mae: 0.0792 - rmse: 0.1055 - smape: 0.2159 - val_ia: 0.9632 - val_loss: 0.0047 - val_mae: 0.0495 - val_rmse: 0.0666 - val_smape: 0.1378

Epoch 70/128

287/287 - 1s - 5ms/step - ia: 0.9521 - loss: 0.0113 - mae: 0.0789 - rmse: 0.1054 - smape: 0.2159 - val_ia: 0.9603 - val_loss: 0.0052 - val_mae: 0.0534 - val_rmse: 0.0703 - val_smape: 0.1426

Epoch 71/128

287/287 - 1s - 3ms/step - ia: 0.9526 - loss: 0.0111 - mae: 0.0782 - rmse: 0.1041 - smape: 0.2147 - val_ia: 0.9596 - val_loss: 0.0054 - val_mae: 0.0543 - val_rmse: 0.0712 - val_smape: 0.1448

Epoch 72/128

287/287 - 2s - 5ms/step - ia: 0.9526 - loss: 0.0110 - mae: 0.0780 - rmse: 0.1042 - smape: 0.2132 - val_ia: 0.9628 - val_loss: 0.0047 - val_mae: 0.0500 - val_rmse: 0.0669 - val_smape: 0.1388

Epoch 73/128

287/287 - 1s - 3ms/step - ia: 0.9528 - loss: 0.0110 - mae: 0.0778 - rmse: 0.1040 - smape: 0.2132 - val_ia: 0.9637 - val_loss: 0.0045 - val_mae: 0.0489 - val_rmse: 0.0660 - val_smape: 0.1369

Epoch 74/128

287/287 - 2s - 6ms/step - ia: 0.9529 - loss: 0.0110 - mae: 0.0777 - rmse: 0.1038 - smape: 0.2117 - val_ia: 0.9632 - val_loss: 0.0046 - val_mae: 0.0494 - val_rmse: 0.0663 - val_smape: 0.1397

Epoch 75/128

287/287 - 2s - 8ms/step - ia: 0.9532 - loss: 0.0108 - mae: 0.0770 - rmse: 0.1031 - smape: 0.2096 - val_ia: 0.9640 - val_loss: 0.0046 - val_mae: 0.0485 - val_rmse: 0.0662 - val_smape: 0.1297

Epoch 76/128

287/287 - 1s - 5ms/step - ia: 0.9533 - loss: 0.0108 - mae: 0.0770 - rmse: 0.1028 - smape: 0.2106 - val_ia: 0.9648 - val_loss: 0.0045 - val_mae: 0.0475 - val_rmse: 0.0654 - val_smape: 0.1284

Epoch 77/128

287/287 - 3s - 9ms/step - ia: 0.9534 - loss: 0.0107 - mae: 0.0768 - rmse: 0.1022 - smape: 0.2106 - val_ia: 0.9642 - val_loss: 0.0045 - val_mae: 0.0482 - val_rmse: 0.0651 - val_smape: 0.1343

Epoch 78/128

287/287 - 1s - 5ms/step - ia: 0.9537 - loss: 0.0106 - mae: 0.0762 - rmse: 0.1017 - smape: 0.2081 - val_ia: 0.9663 - val_loss: 0.0041 - val_mae: 0.0455 - val_rmse: 0.0625 - val_smape: 0.1329

Epoch 79/128

287/287 - 2s - 5ms/step - ia: 0.9539 - loss: 0.0106 - mae: 0.0759 - rmse: 0.1019 - smape: 0.2072 - val_ia: 0.9648 - val_loss: 0.0044 - val_mae: 0.0475 - val_rmse: 0.0646 - val_smape: 0.1319

Epoch 80/128

287/287 - 1s - 5ms/step - ia: 0.9544 - loss: 0.0103 - mae: 0.0753 - rmse: 0.1005 - smape: 0.2073 - val_ia: 0.9662 - val_loss: 0.0041 - val_mae: 0.0456 - val_rmse: 0.0628 - val_smape: 0.1289

Epoch 81/128

287/287 - 2s - 8ms/step - ia: 0.9538 - loss: 0.0106 - mae: 0.0760 - rmse: 0.1017 - smape: 0.2088 - val_ia: 0.9661 - val_loss: 0.0041 - val_mae: 0.0456 - val_rmse: 0.0627 - val_smape: 0.1288

Epoch 82/128

287/287 - 2s - 6ms/step - ia: 0.9546 - loss: 0.0103 - mae: 0.0747 - rmse: 0.1003 - smape: 0.2044 - val_ia: 0.9660 - val_loss: 0.0042 - val_mae: 0.0458 - val_rmse: 0.0633 - val_smape: 0.1256

Epoch 83/128

287/287 - 2s - 5ms/step - ia: 0.9547 - loss: 0.0102 - mae: 0.0746 - rmse: 0.1001 - smape: 0.2045 - val_ia: 0.9625 - val_loss: 0.0048 - val_mae: 0.0505 - val_rmse: 0.0673 - val_smape: 0.1374

Epoch 84/128

287/287 - 1s - 5ms/step - ia: 0.9548 - loss: 0.0102 - mae: 0.0745 - rmse: 0.0998 - smape: 0.2036 - val_ia: 0.9666 - val_loss: 0.0040 - val_mae: 0.0450 - val_rmse: 0.0620 - val_smape: 0.1307

Epoch 85/128

287/287 - 1s - 5ms/step - ia: 0.9549 - loss: 0.0101 - mae: 0.0742 - rmse: 0.0993 - smape: 0.2029 - val_ia: 0.9678 - val_loss: 0.0039 - val_mae: 0.0434 - val_rmse: 0.0608 - val_smape: 0.1253

Epoch 86/128

287/287 - 1s - 4ms/step - ia: 0.9550 - loss: 0.0101 - mae: 0.0742 - rmse: 0.0994 - smape: 0.2048 - val_ia: 0.9652 - val_loss: 0.0042 - val_mae: 0.0469 - val_rmse: 0.0637 - val_smape: 0.1338

Epoch 87/128

287/287 - 1s - 5ms/step - ia: 0.9554 - loss: 0.0099 - mae: 0.0734 - rmse: 0.0986 - smape: 0.2025 - val_ia: 0.9638 - val_loss: 0.0045 - val_mae: 0.0485 - val_rmse: 0.0651 - val_smape: 0.1356

Epoch 88/128

287/287 - 1s - 4ms/step - ia: 0.9554 - loss: 0.0099 - mae: 0.0735 - rmse: 0.0983 - smape: 0.2044 - val_ia: 0.9669 - val_loss: 0.0040 - val_mae: 0.0447 - val_rmse: 0.0618 - val_smape: 0.1275

Epoch 89/128

287/287 - 1s - 5ms/step - ia: 0.9555 - loss: 0.0099 - mae: 0.0733 - rmse: 0.0986 - smape: 0.2005 - val_ia: 0.9643 - val_loss: 0.0043 - val_mae: 0.0479 - val_rmse: 0.0637 - val_smape: 0.1397

Epoch 90/128

287/287 - 1s - 5ms/step - ia: 0.9558 - loss: 0.0098 - mae: 0.0728 - rmse: 0.0978 - smape: 0.1996 - val_ia: 0.9656 - val_loss: 0.0041 - val_mae: 0.0462 - val_rmse: 0.0625 - val_smape: 0.1329

Epoch 91/128

287/287 - 1s - 5ms/step - ia: 0.9562 - loss: 0.0097 - mae: 0.0722 - rmse: 0.0973 - smape: 0.1988 - val_ia: 0.9684 - val_loss: 0.0037 - val_mae: 0.0427 - val_rmse: 0.0598 - val_smape: 0.1274

Epoch 92/128

287/287 - 2s - 5ms/step - ia: 0.9561 - loss: 0.0097 - mae: 0.0723 - rmse: 0.0971 - smape: 0.1997 - val_ia: 0.9668 - val_loss: 0.0039 - val_mae: 0.0447 - val_rmse: 0.0608 - val_smape: 0.1323

Epoch 93/128

287/287 - 1s - 3ms/step - ia: 0.9557 - loss: 0.0099 - mae: 0.0729 - rmse: 0.0983 - smape: 0.2017 - val_ia: 0.9694 - val_loss: 0.0036 - val_mae: 0.0415 - val_rmse: 0.0586 - val_smape: 0.1240

Epoch 94/128

287/287 - 2s - 6ms/step - ia: 0.9562 - loss: 0.0096 - mae: 0.0721 - rmse: 0.0967 - smape: 0.1990 - val_ia: 0.9688 - val_loss: 0.0036 - val_mae: 0.0422 - val_rmse: 0.0591 - val_smape: 0.1296

Epoch 95/128

287/287 - 1s - 5ms/step - ia: 0.9559 - loss: 0.0097 - mae: 0.0726 - rmse: 0.0976 - smape: 0.1985 - val_ia: 0.9665 - val_loss: 0.0041 - val_mae: 0.0453 - val_rmse: 0.0625 - val_smape: 0.1289

Epoch 96/128

287/287 - 1s - 4ms/step - ia: 0.9563 - loss: 0.0096 - mae: 0.0720 - rmse: 0.0969 - smape: 0.1967 - val_ia: 0.9687 - val_loss: 0.0037 - val_mae: 0.0422 - val_rmse: 0.0594 - val_smape: 0.1253

Epoch 97/128

287/287 - 1s - 5ms/step - ia: 0.9568 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0961 - smape: 0.1930 - val_ia: 0.9686 - val_loss: 0.0037 - val_mae: 0.0425 - val_rmse: 0.0597 - val_smape: 0.1248

Epoch 98/128


In [22]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}