Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\Desktop\\pruebas_collab\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(13)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 1
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [15]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 12, 5)
Las dimensiones de testX son:  (10533, 12, 5)
Las dimensiones de valX son:  (5189, 12, 5)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 48s - 42ms/step - ia: 0.6895 - loss: 0.3408 - mae: 0.4367 - rmse: 0.5563 - smape: 0.8184 - val_ia: 0.5292 - val_loss: 0.1281 - val_mae: 0.2987 - val_rmse: 0.3393 - val_smape: 0.6548

Epoch 2/128

1147/1147 - 26s - 22ms/step - ia: 0.7871 - loss: 0.1823 - mae: 0.3237 - rmse: 0.4217 - smape: 0.6236 - val_ia: 0.6354 - val_loss: 0.0622 - val_mae: 0.1983 - val_rmse: 0.2382 - val_smape: 0.4940

Epoch 3/128

1147/1147 - 39s - 34ms/step - ia: 0.8149 - loss: 0.1441 - mae: 0.2846 - rmse: 0.3744 - smape: 0.5538 - val_ia: 0.6946 - val_loss: 0.0448 - val_mae: 0.1571 - val_rmse: 0.1939 - val_smape: 0.3630

Epoch 4/128

1147/1147 - 35s - 30ms/step - ia: 0.8336 - loss: 0.1204 - mae: 0.2578 - rmse: 0.3421 - smape: 0.5028 - val_ia: 0.7277 - val_loss: 0.0339 - val_mae: 0.1353 - val_rmse: 0.1677 - val_smape: 0.3251

Epoch 5/128

1147/1147 - 24s - 21ms/step - ia: 0.8448 - loss: 0.1079 - mae: 0.2420 - rmse: 0.3240 - smape: 0.4684 - val_ia: 0.7515 - val_loss: 0.0260 - val_mae: 0.1183 - val_rmse: 0.1464 - val_smape: 0.2944

Epoch 6/128

1147/1147 - 26s - 23ms/step - ia: 0.8542 - loss: 0.0975 - mae: 0.2280 - rmse: 0.3076 - smape: 0.4398 - val_ia: 0.7617 - val_loss: 0.0239 - val_mae: 0.1132 - val_rmse: 0.1397 - val_smape: 0.2767

Epoch 7/128

1147/1147 - 26s - 22ms/step - ia: 0.8592 - loss: 0.0913 - mae: 0.2207 - rmse: 0.2975 - smape: 0.4248 - val_ia: 0.7833 - val_loss: 0.0188 - val_mae: 0.0998 - val_rmse: 0.1242 - val_smape: 0.2421

Epoch 8/128

1147/1147 - 25s - 22ms/step - ia: 0.8640 - loss: 0.0866 - mae: 0.2134 - rmse: 0.2897 - smape: 0.4093 - val_ia: 0.7902 - val_loss: 0.0171 - val_mae: 0.0969 - val_rmse: 0.1196 - val_smape: 0.2391

Epoch 9/128

1147/1147 - 25s - 22ms/step - ia: 0.8662 - loss: 0.0839 - mae: 0.2103 - rmse: 0.2849 - smape: 0.4038 - val_ia: 0.7669 - val_loss: 0.0209 - val_mae: 0.1108 - val_rmse: 0.1322 - val_smape: 0.2687

Epoch 10/128

1147/1147 - 21s - 18ms/step - ia: 0.8681 - loss: 0.0821 - mae: 0.2068 - rmse: 0.2820 - smape: 0.3974 - val_ia: 0.7783 - val_loss: 0.0180 - val_mae: 0.1038 - val_rmse: 0.1233 - val_smape: 0.2532

Epoch 11/128

1147/1147 - 31s - 27ms/step - ia: 0.8707 - loss: 0.0795 - mae: 0.2032 - rmse: 0.2772 - smape: 0.3915 - val_ia: 0.7976 - val_loss: 0.0158 - val_mae: 0.0936 - val_rmse: 0.1141 - val_smape: 0.2156

Epoch 12/128

1147/1147 - 29s - 25ms/step - ia: 0.8712 - loss: 0.0791 - mae: 0.2029 - rmse: 0.2763 - smape: 0.3922 - val_ia: 0.7962 - val_loss: 0.0164 - val_mae: 0.0952 - val_rmse: 0.1152 - val_smape: 0.2157

Epoch 13/128

1147/1147 - 31s - 27ms/step - ia: 0.8726 - loss: 0.0767 - mae: 0.2000 - rmse: 0.2727 - smape: 0.3870 - val_ia: 0.7925 - val_loss: 0.0180 - val_mae: 0.0988 - val_rmse: 0.1199 - val_smape: 0.2191

Epoch 14/128

1147/1147 - 27s - 23ms/step - ia: 0.8745 - loss: 0.0756 - mae: 0.1973 - rmse: 0.2701 - smape: 0.3843 - val_ia: 0.7998 - val_loss: 0.0158 - val_mae: 0.0945 - val_rmse: 0.1136 - val_smape: 0.2184

Epoch 15/128

1147/1147 - 26s - 22ms/step - ia: 0.8743 - loss: 0.0757 - mae: 0.1978 - rmse: 0.2705 - smape: 0.3821 - val_ia: 0.8000 - val_loss: 0.0163 - val_mae: 0.0945 - val_rmse: 0.1142 - val_smape: 0.2133

Epoch 16/128

1147/1147 - 24s - 21ms/step - ia: 0.8749 - loss: 0.0751 - mae: 0.1969 - rmse: 0.2693 - smape: 0.3802 - val_ia: 0.8100 - val_loss: 0.0144 - val_mae: 0.0884 - val_rmse: 0.1079 - val_smape: 0.2048

Epoch 17/128

1147/1147 - 28s - 25ms/step - ia: 0.8759 - loss: 0.0737 - mae: 0.1953 - rmse: 0.2669 - smape: 0.3784 - val_ia: 0.8169 - val_loss: 0.0131 - val_mae: 0.0844 - val_rmse: 0.1027 - val_smape: 0.1965

Epoch 18/128

1147/1147 - 27s - 24ms/step - ia: 0.8770 - loss: 0.0726 - mae: 0.1935 - rmse: 0.2648 - smape: 0.3745 - val_ia: 0.8151 - val_loss: 0.0127 - val_mae: 0.0845 - val_rmse: 0.1022 - val_smape: 0.2117

Epoch 19/128

1147/1147 - 42s - 37ms/step - ia: 0.8765 - loss: 0.0739 - mae: 0.1944 - rmse: 0.2669 - smape: 0.3743 - val_ia: 0.8093 - val_loss: 0.0145 - val_mae: 0.0895 - val_rmse: 0.1084 - val_smape: 0.2036

Epoch 20/128

1147/1147 - 27s - 24ms/step - ia: 0.8775 - loss: 0.0725 - mae: 0.1929 - rmse: 0.2646 - smape: 0.3711 - val_ia: 0.8095 - val_loss: 0.0135 - val_mae: 0.0872 - val_rmse: 0.1051 - val_smape: 0.2165

Epoch 21/128

1147/1147 - 28s - 24ms/step - ia: 0.8778 - loss: 0.0718 - mae: 0.1925 - rmse: 0.2634 - smape: 0.3703 - val_ia: 0.8004 - val_loss: 0.0162 - val_mae: 0.0939 - val_rmse: 0.1140 - val_smape: 0.1995

Epoch 22/128

1147/1147 - 26s - 23ms/step - ia: 0.8802 - loss: 0.0699 - mae: 0.1892 - rmse: 0.2596 - smape: 0.3684 - val_ia: 0.8266 - val_loss: 0.0114 - val_mae: 0.0790 - val_rmse: 0.0969 - val_smape: 0.1922

Epoch 23/128

1147/1147 - 26s - 23ms/step - ia: 0.8792 - loss: 0.0707 - mae: 0.1905 - rmse: 0.2613 - smape: 0.3679 - val_ia: 0.8156 - val_loss: 0.0131 - val_mae: 0.0855 - val_rmse: 0.1036 - val_smape: 0.2006

Epoch 24/128

1147/1147 - 25s - 22ms/step - ia: 0.8799 - loss: 0.0704 - mae: 0.1897 - rmse: 0.2607 - smape: 0.3662 - val_ia: 0.8102 - val_loss: 0.0128 - val_mae: 0.0851 - val_rmse: 0.1031 - val_smape: 0.2033

Epoch 25/128

1147/1147 - 31s - 27ms/step - ia: 0.8804 - loss: 0.0697 - mae: 0.1888 - rmse: 0.2593 - smape: 0.3646 - val_ia: 0.8183 - val_loss: 0.0126 - val_mae: 0.0822 - val_rmse: 0.1007 - val_smape: 0.1859

Epoch 26/128

1147/1147 - 21s - 19ms/step - ia: 0.8812 - loss: 0.0691 - mae: 0.1876 - rmse: 0.2583 - smape: 0.3630 - val_ia: 0.8392 - val_loss: 0.0100 - val_mae: 0.0721 - val_rmse: 0.0903 - val_smape: 0.1770

Epoch 27/128

1147/1147 - 27s - 24ms/step - ia: 0.8805 - loss: 0.0696 - mae: 0.1883 - rmse: 0.2591 - smape: 0.3632 - val_ia: 0.8376 - val_loss: 0.0111 - val_mae: 0.0753 - val_rmse: 0.0939 - val_smape: 0.1791

Epoch 28/128

1147/1147 - 20s - 17ms/step - ia: 0.8815 - loss: 0.0682 - mae: 0.1870 - rmse: 0.2570 - smape: 0.3618 - val_ia: 0.8097 - val_loss: 0.0132 - val_mae: 0.0859 - val_rmse: 0.1043 - val_smape: 0.1908

Epoch 29/128

1147/1147 - 21s - 19ms/step - ia: 0.8800 - loss: 0.0701 - mae: 0.1890 - rmse: 0.2602 - smape: 0.3662 - val_ia: 0.8046 - val_loss: 0.0143 - val_mae: 0.0905 - val_rmse: 0.1085 - val_smape: 0.2056

Epoch 30/128

1147/1147 - 39s - 34ms/step - ia: 0.8815 - loss: 0.0683 - mae: 0.1869 - rmse: 0.2570 - smape: 0.3594 - val_ia: 0.7749 - val_loss: 0.0172 - val_mae: 0.1044 - val_rmse: 0.1212 - val_smape: 0.2526

Epoch 31/128

1147/1147 - 18s - 16ms/step - ia: 0.8817 - loss: 0.0681 - mae: 0.1867 - rmse: 0.2564 - smape: 0.3598 - val_ia: 0.8424 - val_loss: 0.0093 - val_mae: 0.0700 - val_rmse: 0.0876 - val_smape: 0.1763

Epoch 32/128

1147/1147 - 19s - 17ms/step - ia: 0.8825 - loss: 0.0675 - mae: 0.1855 - rmse: 0.2551 - smape: 0.3553 - val_ia: 0.8617 - val_loss: 0.0073 - val_mae: 0.0608 - val_rmse: 0.0777 - val_smape: 0.1543

Epoch 33/128

1147/1147 - 22s - 19ms/step - ia: 0.8826 - loss: 0.0669 - mae: 0.1852 - rmse: 0.2542 - smape: 0.3585 - val_ia: 0.8479 - val_loss: 0.0090 - val_mae: 0.0687 - val_rmse: 0.0862 - val_smape: 0.1698

Epoch 34/128

1147/1147 - 19s - 16ms/step - ia: 0.8819 - loss: 0.0684 - mae: 0.1864 - rmse: 0.2566 - smape: 0.3608 - val_ia: 0.8549 - val_loss: 0.0077 - val_mae: 0.0644 - val_rmse: 0.0809 - val_smape: 0.1736

Epoch 35/128

1147/1147 - 26s - 22ms/step - ia: 0.8824 - loss: 0.0679 - mae: 0.1856 - rmse: 0.2558 - smape: 0.3559 - val_ia: 0.8502 - val_loss: 0.0085 - val_mae: 0.0674 - val_rmse: 0.0846 - val_smape: 0.1689

Epoch 36/128

1147/1147 - 22s - 19ms/step - ia: 0.8816 - loss: 0.0685 - mae: 0.1870 - rmse: 0.2571 - smape: 0.3622 - val_ia: 0.8517 - val_loss: 0.0079 - val_mae: 0.0653 - val_rmse: 0.0818 - val_smape: 0.1766

Epoch 37/128

1147/1147 - 24s - 21ms/step - ia: 0.8824 - loss: 0.0676 - mae: 0.1859 - rmse: 0.2553 - smape: 0.3566 - val_ia: 0.8302 - val_loss: 0.0102 - val_mae: 0.0767 - val_rmse: 0.0932 - val_smape: 0.2148

Epoch 38/128

1147/1147 - 27s - 24ms/step - ia: 0.8831 - loss: 0.0670 - mae: 0.1845 - rmse: 0.2539 - smape: 0.3561 - val_ia: 0.8295 - val_loss: 0.0109 - val_mae: 0.0771 - val_rmse: 0.0947 - val_smape: 0.1801

Epoch 39/128

1147/1147 - 33s - 28ms/step - ia: 0.8824 - loss: 0.0679 - mae: 0.1855 - rmse: 0.2561 - smape: 0.3532 - val_ia: 0.8503 - val_loss: 0.0086 - val_mae: 0.0665 - val_rmse: 0.0839 - val_smape: 0.1622

Epoch 40/128

1147/1147 - 40s - 35ms/step - ia: 0.8827 - loss: 0.0676 - mae: 0.1852 - rmse: 0.2552 - smape: 0.3549 - val_ia: 0.8360 - val_loss: 0.0095 - val_mae: 0.0733 - val_rmse: 0.0901 - val_smape: 0.1821

Epoch 41/128

1147/1147 - 32s - 28ms/step - ia: 0.8825 - loss: 0.0671 - mae: 0.1853 - rmse: 0.2545 - smape: 0.3558 - val_ia: 0.8465 - val_loss: 0.0085 - val_mae: 0.0681 - val_rmse: 0.0848 - val_smape: 0.1783

Epoch 42/128

1147/1147 - 26s - 23ms/step - ia: 0.8848 - loss: 0.0650 - mae: 0.1818 - rmse: 0.2507 - smape: 0.3529 - val_ia: 0.8364 - val_loss: 0.0100 - val_mae: 0.0736 - val_rmse: 0.0908 - val_smape: 0.1729

Epoch 43/128

1147/1147 - 31s - 27ms/step - ia: 0.8828 - loss: 0.0676 - mae: 0.1850 - rmse: 0.2551 - smape: 0.3560 - val_ia: 0.8359 - val_loss: 0.0097 - val_mae: 0.0743 - val_rmse: 0.0907 - val_smape: 0.2096

Epoch 44/128

1147/1147 - 28s - 25ms/step - ia: 0.8839 - loss: 0.0660 - mae: 0.1832 - rmse: 0.2522 - smape: 0.3517 - val_ia: 0.8137 - val_loss: 0.0118 - val_mae: 0.0837 - val_rmse: 0.1003 - val_smape: 0.2026

Epoch 45/128

1147/1147 - 22s - 19ms/step - ia: 0.8826 - loss: 0.0672 - mae: 0.1851 - rmse: 0.2547 - smape: 0.3568 - val_ia: 0.8393 - val_loss: 0.0093 - val_mae: 0.0722 - val_rmse: 0.0890 - val_smape: 0.1913

Epoch 46/128

1147/1147 - 22s - 19ms/step - ia: 0.8826 - loss: 0.0672 - mae: 0.1850 - rmse: 0.2548 - smape: 0.3534 - val_ia: 0.8349 - val_loss: 0.0103 - val_mae: 0.0748 - val_rmse: 0.0923 - val_smape: 0.1842

Epoch 47/128

1147/1147 - 26s - 23ms/step - ia: 0.8836 - loss: 0.0662 - mae: 0.1835 - rmse: 0.2528 - smape: 0.3527 - val_ia: 0.8244 - val_loss: 0.0108 - val_mae: 0.0789 - val_rmse: 0.0958 - val_smape: 0.2110

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:02 4s/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step

  2%|▏         | 1/50 [21:39<17:41:01, 1299.21s/trial, best loss: 0.008055927496625412]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 65s - 452ms/step - ia: 0.7989 - loss: 0.1697 - mae: 0.2557 - rmse: 0.3265 - smape: 0.5798 - val_ia: 0.9361 - val_loss: 0.0131 - val_mae: 0.0836 - val_rmse: 0.1141 - val_smape: 0.2324

Epoch 2/16

144/144 - 23s - 159ms/step - ia: 0.9649 - loss: 0.0073 - mae: 0.0580 - rmse: 0.0836 - smape: 0.1813 - val_ia: 0.9631 - val_loss: 0.0048 - val_mae: 0.0477 - val_rmse: 0.0688 - val_smape: 0.1459

Epoch 3/16

144/144 - 24s - 165ms/step - ia: 0.9703 - loss: 0.0051 - mae: 0.0490 - rmse: 0.0698 - smape: 0.1618 - val_ia: 0.9398 - val_loss: 0.0093 - val_mae: 0.0784 - val_rmse: 0.0950 - val_smape: 0.2384

Epoch 4/16

144/144 - 19s - 134ms/step - ia: 0.9740 - loss: 0.0041 - mae: 0.0429 - rmse: 0.0622 - smape: 0.1477 - val_ia: 0.9549 - val_loss: 0.0057 - val_mae: 0.0591 - val_rmse: 0.0746 - val_smape: 0.1808

Epoch 5/16

144/144 - 21s - 148ms/step - ia: 0.9756 - loss: 0.0037 - mae: 0.0403 - rmse: 0.0589 - smape: 0.1423 - val_ia: 0.9716 - val_loss: 0.0030 - val_mae: 0.0382 - val_rmse: 0.0543 - val_smape: 0.1189

Epoch 6/16

144/144 - 21s - 149ms/step - ia: 0.9772 - loss: 0.0034 - mae: 0.0378 - rmse: 0.0562 - smape: 0.1354 - val_ia: 0.9709 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0546 - val_smape: 0.1259

Epoch 7/16

144/144 - 21s - 148ms/step - ia: 0.9762 - loss: 0.0035 - mae: 0.0394 - rmse: 0.0574 - smape: 0.1391 - val_ia: 0.9727 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0519 - val_smape: 0.1161

Epoch 8/16

144/144 - 22s - 151ms/step - ia: 0.9773 - loss: 0.0033 - mae: 0.0375 - rmse: 0.0554 - smape: 0.1343 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0415 - val_rmse: 0.0566 - val_smape: 0.1343

Epoch 9/16

144/144 - 24s - 165ms/step - ia: 0.9771 - loss: 0.0033 - mae: 0.0379 - rmse: 0.0556 - smape: 0.1360 - val_ia: 0.9729 - val_loss: 0.0027 - val_mae: 0.0364 - val_rmse: 0.0515 - val_smape: 0.1155

Epoch 10/16

144/144 - 20s - 141ms/step - ia: 0.9766 - loss: 0.0034 - mae: 0.0387 - rmse: 0.0562 - smape: 0.1370 - val_ia: 0.9626 - val_loss: 0.0042 - val_mae: 0.0494 - val_rmse: 0.0637 - val_smape: 0.1557

Epoch 11/16

144/144 - 17s - 121ms/step - ia: 0.9777 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0543 - smape: 0.1315 - val_ia: 0.9653 - val_loss: 0.0039 - val_mae: 0.0476 - val_rmse: 0.0612 - val_smape: 0.1479

Epoch 12/16

144/144 - 16s - 114ms/step - ia: 0.9783 - loss: 0.0031 - mae: 0.0359 - rmse: 0.0535 - smape: 0.1304 - val_ia: 0.9643 - val_loss: 0.0039 - val_mae: 0.0479 - val_rmse: 0.0619 - val_smape: 0.1442

Epoch 13/16

144/144 - 13s - 94ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0533 - smape: 0.1294 - val_ia: 0.9726 - val_loss: 0.0027 - val_mae: 0.0374 - val_rmse: 0.0518 - val_smape: 0.1189

Epoch 14/16

144/144 - 15s - 101ms/step - ia: 0.9784 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0531 - smape: 0.1299 - val_ia: 0.9625 - val_loss: 0.0042 - val_mae: 0.0496 - val_rmse: 0.0635 - val_smape: 0.1576

Epoch 15/16

144/144 - 14s - 100ms/step - ia: 0.9774 - loss: 0.0032 - mae: 0.0372 - rmse: 0.0544 - smape: 0.1337 - val_ia: 0.9694 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0555 - val_smape: 0.1278

Epoch 16/16

144/144 - 16s - 109ms/step - ia: 0.9788 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0524 - smape: 0.1281 - val_ia: 0.9716 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0531 - val_smape: 0.1239

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:52 1s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step

  4%|▍         | 2/50 [27:38<9:56:49, 746.02s/trial, best loss: 0.002311278363512626]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

574/574 - 34s - 60ms/step - ia: 0.2567 - loss: 0.8516 - mae: 0.7547 - rmse: 0.9206 - smape: 1.5229 - val_ia: 0.3474 - val_loss: 0.8131 - val_mae: 0.7442 - val_rmse: 0.8578 - val_smape: 1.4436

Epoch 2/8

574/574 - 8s - 13ms/step - ia: 0.2661 - loss: 0.8393 - mae: 0.7488 - rmse: 0.9144 - smape: 1.5191 - val_ia: 0.3511 - val_loss: 0.8045 - val_mae: 0.7402 - val_rmse: 0.8531 - val_smape: 1.4392

Epoch 3/8

574/574 - 7s - 13ms/step - ia: 0.2706 - loss: 0.8298 - mae: 0.7438 - rmse: 0.9088 - smape: 1.5149 - val_ia: 0.3547 - val_loss: 0.7960 - val_mae: 0.7363 - val_rmse: 0.8483 - val_smape: 1.4350

Epoch 4/8

574/574 - 9s - 16ms/step - ia: 0.2801 - loss: 0.8178 - mae: 0.7377 - rmse: 0.9021 - smape: 1.5059 - val_ia: 0.3585 - val_loss: 0.7876 - val_mae: 0.7323 - val_rmse: 0.8435 - val_smape: 1.4307

Epoch 5/8

574/574 - 10s - 18ms/step - ia: 0.2880 - loss: 0.8048 - mae: 0.7316 - rmse: 0.8952 - smape: 1.4988 - val_ia: 0.3623 - val_loss: 0.7792 - val_mae: 0.7285 - val_rmse: 0.8387 - val_smape: 1.4266

Epoch 6/8

574/574 - 10s - 18ms/step - ia: 0.2951 - loss: 0.7945 - mae: 0.7263 - rmse: 0.8892 - smape: 1.4927 - val_ia: 0.3661 - val_loss: 0.7709 - val_mae: 0.7246 - val_rmse: 0.8340 - val_smape: 1.4224

Epoch 7/8

574/574 - 11s - 18ms/step - ia: 0.3062 - loss: 0.7809 - mae: 0.7197 - rmse: 0.8814 - smape: 1.4821 - val_ia: 0.3700 - val_loss: 0.7628 - val_mae: 0.7209 - val_rmse: 0.8293 - val_smape: 1.4183

Epoch 8/8

574/574 - 10s - 17ms/step - ia: 0.3135 - loss: 0.7721 - mae: 0.7145 - rmse: 0.8764 - smape: 1.4736 - val_ia: 0.3738 - val_loss: 0.7549 - val_mae: 0.7173 - val_rmse: 0.8246 - val_smape: 1.4143

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8:41 3s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step

  6%|▌         | 3/50 [29:25<5:56:08, 454.65s/trial, best loss: 0.002311278363512626]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 49s - 169ms/step - ia: 0.3759 - loss: 0.6474 - mae: 0.6599 - rmse: 0.8008 - smape: 1.3161 - val_ia: 0.5054 - val_loss: 0.3821 - val_mae: 0.5064 - val_rmse: 0.6143 - val_smape: 1.0301

Epoch 2/32

287/287 - 10s - 33ms/step - ia: 0.6298 - loss: 0.3416 - mae: 0.4723 - rmse: 0.5809 - smape: 0.9250 - val_ia: 0.7105 - val_loss: 0.1934 - val_mae: 0.3467 - val_rmse: 0.4359 - val_smape: 0.7323

Epoch 3/32

287/287 - 9s - 33ms/step - ia: 0.7522 - loss: 0.2106 - mae: 0.3643 - rmse: 0.4575 - smape: 0.7381 - val_ia: 0.7801 - val_loss: 0.1450 - val_mae: 0.2910 - val_rmse: 0.3780 - val_smape: 0.6454

Epoch 4/32

287/287 - 9s - 32ms/step - ia: 0.7880 - loss: 0.1756 - mae: 0.3293 - rmse: 0.4182 - smape: 0.6695 - val_ia: 0.7962 - val_loss: 0.1330 - val_mae: 0.2787 - val_rmse: 0.3627 - val_smape: 0.6247

Epoch 5/32

287/287 - 9s - 33ms/step - ia: 0.8020 - loss: 0.1606 - mae: 0.3125 - rmse: 0.3998 - smape: 0.6386 - val_ia: 0.8066 - val_loss: 0.1223 - val_mae: 0.2669 - val_rmse: 0.3480 - val_smape: 0.6095

Epoch 6/32

287/287 - 8s - 27ms/step - ia: 0.8115 - loss: 0.1476 - mae: 0.2990 - rmse: 0.3834 - smape: 0.6135 - val_ia: 0.8144 - val_loss: 0.1137 - val_mae: 0.2578 - val_rmse: 0.3353 - val_smape: 0.5999

Epoch 7/32

287/287 - 8s - 27ms/step - ia: 0.8194 - loss: 0.1377 - mae: 0.2878 - rmse: 0.3701 - smape: 0.5918 - val_ia: 0.8199 - val_loss: 0.1058 - val_mae: 0.2500 - val_rmse: 0.3232 - val_smape: 0.5903

Epoch 8/32

287/287 - 8s - 28ms/step - ia: 0.8257 - loss: 0.1289 - mae: 0.2777 - rmse: 0.3580 - smape: 0.5731 - val_ia: 0.8243 - val_loss: 0.1001 - val_mae: 0.2452 - val_rmse: 0.3145 - val_smape: 0.5825

Epoch 9/32

287/287 - 9s - 31ms/step - ia: 0.8328 - loss: 0.1198 - mae: 0.2675 - rmse: 0.3453 - smape: 0.5575 - val_ia: 0.8289 - val_loss: 0.0931 - val_mae: 0.2384 - val_rmse: 0.3034 - val_smape: 0.5704

Epoch 10/32

287/287 - 9s - 32ms/step - ia: 0.8376 - loss: 0.1142 - mae: 0.2603 - rmse: 0.3370 - smape: 0.5408 - val_ia: 0.8319 - val_loss: 0.0885 - val_mae: 0.2345 - val_rmse: 0.2959 - val_smape: 0.5618

Epoch 11/32

287/287 - 10s - 36ms/step - ia: 0.8434 - loss: 0.1072 - mae: 0.2519 - rmse: 0.3264 - smape: 0.5264 - val_ia: 0.8363 - val_loss: 0.0822 - val_mae: 0.2276 - val_rmse: 0.2852 - val_smape: 0.5489

Epoch 12/32

287/287 - 9s - 33ms/step - ia: 0.8478 - loss: 0.1025 - mae: 0.2449 - rmse: 0.3193 - smape: 0.5112 - val_ia: 0.8435 - val_loss: 0.0754 - val_mae: 0.2180 - val_rmse: 0.2733 - val_smape: 0.5329

Epoch 13/32

287/287 - 9s - 33ms/step - ia: 0.8520 - loss: 0.0977 - mae: 0.2386 - rmse: 0.3115 - smape: 0.5001 - val_ia: 0.8471 - val_loss: 0.0703 - val_mae: 0.2120 - val_rmse: 0.2640 - val_smape: 0.5214

Epoch 14/32

287/287 - 9s - 32ms/step - ia: 0.8571 - loss: 0.0917 - mae: 0.2308 - rmse: 0.3017 - smape: 0.4861 - val_ia: 0.8545 - val_loss: 0.0642 - val_mae: 0.2016 - val_rmse: 0.2522 - val_smape: 0.5042

Epoch 15/32

287/287 - 9s - 32ms/step - ia: 0.8601 - loss: 0.0885 - mae: 0.2262 - rmse: 0.2964 - smape: 0.4759 - val_ia: 0.8603 - val_loss: 0.0585 - val_mae: 0.1927 - val_rmse: 0.2407 - val_smape: 0.4885

Epoch 16/32

287/287 - 9s - 31ms/step - ia: 0.8640 - loss: 0.0836 - mae: 0.2198 - rmse: 0.2882 - smape: 0.4659 - val_ia: 0.8663 - val_loss: 0.0543 - val_mae: 0.1849 - val_rmse: 0.2320 - val_smape: 0.4752

Epoch 17/32

287/287 - 7s - 24ms/step - ia: 0.8673 - loss: 0.0805 - mae: 0.2149 - rmse: 0.2830 - smape: 0.4542 - val_ia: 0.8723 - val_loss: 0.0493 - val_mae: 0.1757 - val_rmse: 0.2209 - val_smape: 0.4588

Epoch 18/32

287/287 - 6s - 22ms/step - ia: 0.8698 - loss: 0.0778 - mae: 0.2112 - rmse: 0.2779 - smape: 0.4480 - val_ia: 0.8797 - val_loss: 0.0443 - val_mae: 0.1651 - val_rmse: 0.2093 - val_smape: 0.4404

Epoch 19/32

287/287 - 7s - 24ms/step - ia: 0.8725 - loss: 0.0748 - mae: 0.2069 - rmse: 0.2726 - smape: 0.4395 - val_ia: 0.8838 - val_loss: 0.0410 - val_mae: 0.1590 - val_rmse: 0.2014 - val_smape: 0.4283

Epoch 20/32

287/287 - 7s - 24ms/step - ia: 0.8747 - loss: 0.0721 - mae: 0.2033 - rmse: 0.2677 - smape: 0.4331 - val_ia: 0.8887 - val_loss: 0.0382 - val_mae: 0.1524 - val_rmse: 0.1943 - val_smape: 0.4169

Epoch 21/32

287/287 - 7s - 24ms/step - ia: 0.8774 - loss: 0.0694 - mae: 0.1991 - rmse: 0.2624 - smape: 0.4251 - val_ia: 0.8934 - val_loss: 0.0354 - val_mae: 0.1459 - val_rmse: 0.1869 - val_smape: 0.4054

Epoch 22/32

287/287 - 7s - 24ms/step - ia: 0.8794 - loss: 0.0676 - mae: 0.1957 - rmse: 0.2593 - smape: 0.4185 - val_ia: 0.8958 - val_loss: 0.0339 - val_mae: 0.1426 - val_rmse: 0.1830 - val_smape: 0.3994

Epoch 23/32

287/287 - 9s - 32ms/step - ia: 0.8813 - loss: 0.0653 - mae: 0.1928 - rmse: 0.2545 - smape: 0.4171 - val_ia: 0.9001 - val_loss: 0.0314 - val_mae: 0.1360 - val_rmse: 0.1758 - val_smape: 0.3854

Epoch 24/32

287/287 - 10s - 36ms/step - ia: 0.8824 - loss: 0.0650 - mae: 0.1911 - rmse: 0.2541 - smape: 0.4105 - val_ia: 0.9027 - val_loss: 0.0299 - val_mae: 0.1322 - val_rmse: 0.1714 - val_smape: 0.3776

Epoch 25/32

287/287 - 9s - 32ms/step - ia: 0.8839 - loss: 0.0627 - mae: 0.1884 - rmse: 0.2495 - smape: 0.4055 - val_ia: 0.9063 - val_loss: 0.0281 - val_mae: 0.1275 - val_rmse: 0.1663 - val_smape: 0.3684

Epoch 26/32

287/287 - 10s - 36ms/step - ia: 0.8850 - loss: 0.0620 - mae: 0.1868 - rmse: 0.2480 - smape: 0.4021 - val_ia: 0.9079 - val_loss: 0.0272 - val_mae: 0.1252 - val_rmse: 0.1636 - val_smape: 0.3635

Epoch 27/32

287/287 - 10s - 35ms/step - ia: 0.8871 - loss: 0.0596 - mae: 0.1835 - rmse: 0.2432 - smape: 0.3971 - val_ia: 0.9091 - val_loss: 0.0264 - val_mae: 0.1234 - val_rmse: 0.1610 - val_smape: 0.3597

Epoch 28/32

287/287 - 10s - 36ms/step - ia: 0.8877 - loss: 0.0592 - mae: 0.1827 - rmse: 0.2425 - smape: 0.3942 - val_ia: 0.9111 - val_loss: 0.0255 - val_mae: 0.1209 - val_rmse: 0.1581 - val_smape: 0.3544

Epoch 29/32

287/287 - 9s - 32ms/step - ia: 0.8889 - loss: 0.0579 - mae: 0.1806 - rmse: 0.2398 - smape: 0.3920 - val_ia: 0.9121 - val_loss: 0.0249 - val_mae: 0.1192 - val_rmse: 0.1561 - val_smape: 0.3499

Epoch 30/32

287/287 - 10s - 33ms/step - ia: 0.8904 - loss: 0.0570 - mae: 0.1782 - rmse: 0.2378 - smape: 0.3845 - val_ia: 0.9130 - val_loss: 0.0244 - val_mae: 0.1181 - val_rmse: 0.1546 - val_smape: 0.3483

Epoch 31/32

287/287 - 10s - 36ms/step - ia: 0.8906 - loss: 0.0565 - mae: 0.1779 - rmse: 0.2367 - smape: 0.3849 - val_ia: 0.9144 - val_loss: 0.0238 - val_mae: 0.1158 - val_rmse: 0.1524 - val_smape: 0.3420

Epoch 32/32

287/287 - 10s - 34ms/step - ia: 0.8918 - loss: 0.0554 - mae: 0.1757 - rmse: 0.2345 - smape: 0.3830 - val_ia: 0.9158 - val_loss: 0.0231 - val_mae: 0.1140 - val_rmse: 0.1503 - val_smape: 0.3381

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:56 3s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step

  8%|▊         | 4/50 [34:57<5:11:24, 406.18s/trial, best loss: 0.002311278363512626]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4586/4586 - 78s - 17ms/step - ia: 0.2711 - loss: 1.1942 - mae: 0.8989 - rmse: 1.0648 - smape: 1.4835 - val_ia: 0.1431 - val_loss: 0.8260 - val_mae: 0.7421 - val_rmse: 0.7591 - val_smape: 1.3566

Epoch 2/64

4586/4586 - 52s - 11ms/step - ia: 0.2621 - loss: 1.0977 - mae: 0.8644 - rmse: 1.0238 - smape: 1.5248 - val_ia: 0.1465 - val_loss: 0.7953 - val_mae: 0.7343 - val_rmse: 0.7517 - val_smape: 1.4791

Epoch 3/64

4586/4586 - 51s - 11ms/step - ia: 0.2602 - loss: 1.0428 - mae: 0.8432 - rmse: 0.9989 - smape: 1.5391 - val_ia: 0.1465 - val_loss: 0.7834 - val_mae: 0.7324 - val_rmse: 0.7498 - val_smape: 1.6042

Epoch 4/64

4586/4586 - 38s - 8ms/step - ia: 0.2666 - loss: 1.0051 - mae: 0.8287 - rmse: 0.9805 - smape: 1.5336 - val_ia: 0.1462 - val_loss: 0.7739 - val_mae: 0.7296 - val_rmse: 0.7468 - val_smape: 1.6949

Epoch 5/64

4586/4586 - 40s - 9ms/step - ia: 0.2711 - loss: 0.9821 - mae: 0.8200 - rmse: 0.9698 - smape: 1.5218 - val_ia: 0.1473 - val_loss: 0.7620 - val_mae: 0.7246 - val_rmse: 0.7417 - val_smape: 1.7278

Epoch 6/64

4586/4586 - 40s - 9ms/step - ia: 0.2799 - loss: 0.9585 - mae: 0.8089 - rmse: 0.9591 - smape: 1.5079 - val_ia: 0.1484 - val_loss: 0.7473 - val_mae: 0.7177 - val_rmse: 0.7347 - val_smape: 1.7039

Epoch 7/64

4586/4586 - 47s - 10ms/step - ia: 0.2902 - loss: 0.9322 - mae: 0.7970 - rmse: 0.9456 - smape: 1.4841 - val_ia: 0.1497 - val_loss: 0.7294 - val_mae: 0.7089 - val_rmse: 0.7258 - val_smape: 1.6634

Epoch 8/64

4586/4586 - 46s - 10ms/step - ia: 0.2977 - loss: 0.9081 - mae: 0.7865 - rmse: 0.9328 - smape: 1.4698 - val_ia: 0.1514 - val_loss: 0.7099 - val_mae: 0.6992 - val_rmse: 0.7159 - val_smape: 1.6204

Epoch 9/64

4586/4586 - 47s - 10ms/step - ia: 0.3065 - loss: 0.8808 - mae: 0.7741 - rmse: 0.9184 - smape: 1.4479 - val_ia: 0.1534 - val_loss: 0.6867 - val_mae: 0.6874 - val_rmse: 0.7039 - val_smape: 1.5717

Epoch 10/64

4586/4586 - 46s - 10ms/step - ia: 0.3201 - loss: 0.8509 - mae: 0.7601 - rmse: 0.9024 - smape: 1.4245 - val_ia: 0.1558 - val_loss: 0.6616 - val_mae: 0.6742 - val_rmse: 0.6906 - val_smape: 1.5201

Epoch 11/64

4586/4586 - 40s - 9ms/step - ia: 0.3333 - loss: 0.8196 - mae: 0.7455 - rmse: 0.8852 - smape: 1.4000 - val_ia: 0.1586 - val_loss: 0.6341 - val_mae: 0.6596 - val_rmse: 0.6757 - val_smape: 1.4649

Epoch 12/64

4586/4586 - 40s - 9ms/step - ia: 0.3477 - loss: 0.7898 - mae: 0.7305 - rmse: 0.8688 - smape: 1.3646 - val_ia: 0.1620 - val_loss: 0.6031 - val_mae: 0.6424 - val_rmse: 0.6584 - val_smape: 1.4059

Epoch 13/64

4586/4586 - 40s - 9ms/step - ia: 0.3654 - loss: 0.7532 - mae: 0.7128 - rmse: 0.8478 - smape: 1.3344 - val_ia: 0.1659 - val_loss: 0.5708 - val_mae: 0.6242 - val_rmse: 0.6400 - val_smape: 1.3440

Epoch 14/64

4586/4586 - 39s - 9ms/step - ia: 0.3870 - loss: 0.7135 - mae: 0.6917 - rmse: 0.8253 - smape: 1.2955 - val_ia: 0.1701 - val_loss: 0.5360 - val_mae: 0.6039 - val_rmse: 0.6194 - val_smape: 1.2796

Epoch 15/64

4586/4586 - 40s - 9ms/step - ia: 0.4092 - loss: 0.6706 - mae: 0.6694 - rmse: 0.7991 - smape: 1.2496 - val_ia: 0.1746 - val_loss: 0.4987 - val_mae: 0.5812 - val_rmse: 0.5965 - val_smape: 1.2124

Epoch 16/64

4586/4586 - 40s - 9ms/step - ia: 0.4359 - loss: 0.6250 - mae: 0.6448 - rmse: 0.7705 - smape: 1.2061 - val_ia: 0.1801 - val_loss: 0.4593 - val_mae: 0.5562 - val_rmse: 0.5711 - val_smape: 1.1433

Epoch 17/64

4586/4586 - 41s - 9ms/step - ia: 0.4597 - loss: 0.5850 - mae: 0.6230 - rmse: 0.7453 - smape: 1.1637 - val_ia: 0.1862 - val_loss: 0.4183 - val_mae: 0.5288 - val_rmse: 0.5434 - val_smape: 1.0732

Epoch 18/64

4586/4586 - 40s - 9ms/step - ia: 0.4913 - loss: 0.5381 - mae: 0.5938 - rmse: 0.7136 - smape: 1.1082 - val_ia: 0.1928 - val_loss: 0.3780 - val_mae: 0.5007 - val_rmse: 0.5149 - val_smape: 1.0047

Epoch 19/64

4586/4586 - 39s - 8ms/step - ia: 0.5223 - loss: 0.4924 - mae: 0.5664 - rmse: 0.6821 - smape: 1.0555 - val_ia: 0.2001 - val_loss: 0.3382 - val_mae: 0.4710 - val_rmse: 0.4849 - val_smape: 0.9382

Epoch 20/64

4586/4586 - 40s - 9ms/step - ia: 0.5509 - loss: 0.4525 - mae: 0.5405 - rmse: 0.6530 - smape: 1.0053 - val_ia: 0.2089 - val_loss: 0.3003 - val_mae: 0.4408 - val_rmse: 0.4546 - val_smape: 0.8755

Epoch 21/64

4586/4586 - 40s - 9ms/step - ia: 0.5812 - loss: 0.4131 - mae: 0.5132 - rmse: 0.6226 - smape: 0.9557 - val_ia: 0.2200 - val_loss: 0.2662 - val_mae: 0.4118 - val_rmse: 0.4258 - val_smape: 0.8185

Epoch 22/64

4586/4586 - 40s - 9ms/step - ia: 0.6064 - loss: 0.3779 - mae: 0.4895 - rmse: 0.5949 - smape: 0.9136 - val_ia: 0.2327 - val_loss: 0.2361 - val_mae: 0.3837 - val_rmse: 0.3982 - val_smape: 0.7674

Epoch 23/64

4586/4586 - 40s - 9ms/step - ia: 0.6333 - loss: 0.3461 - mae: 0.4671 - rmse: 0.5689 - smape: 0.8749 - val_ia: 0.2480 - val_loss: 0.2109 - val_mae: 0.3582 - val_rmse: 0.3732 - val_smape: 0.7236

Epoch 24/64

4586/4586 - 39s - 8ms/step - ia: 0.6537 - loss: 0.3204 - mae: 0.4478 - rmse: 0.5470 - smape: 0.8419 - val_ia: 0.2623 - val_loss: 0.1911 - val_mae: 0.3370 - val_rmse: 0.3527 - val_smape: 0.6890

Epoch 25/64

4586/4586 - 42s - 9ms/step - ia: 0.6752 - loss: 0.2979 - mae: 0.4297 - rmse: 0.5270 - smape: 0.8068 - val_ia: 0.2734 - val_loss: 0.1766 - val_mae: 0.3217 - val_rmse: 0.3379 - val_smape: 0.6644

Epoch 26/64

4586/4586 - 40s - 9ms/step - ia: 0.6859 - loss: 0.2869 - mae: 0.4214 - rmse: 0.5164 - smape: 0.7896 - val_ia: 0.2738 - val_loss: 0.1661 - val_mae: 0.3120 - val_rmse: 0.3285 - val_smape: 0.6484

Epoch 27/64

4586/4586 - 38s - 8ms/step - ia: 0.7004 - loss: 0.2685 - mae: 0.4079 - rmse: 0.5003 - smape: 0.7657 - val_ia: 0.2736 - val_loss: 0.1589 - val_mae: 0.3064 - val_rmse: 0.3230 - val_smape: 0.6384

Epoch 28/64

4586/4586 - 40s - 9ms/step - ia: 0.7089 - loss: 0.2589 - mae: 0.4000 - rmse: 0.4909 - smape: 0.7525 - val_ia: 0.2727 - val_loss: 0.1536 - val_mae: 0.3025 - val_rmse: 0.3193 - val_smape: 0.6312

Epoch 29/64

4586/4586 - 39s - 9ms/step - ia: 0.7164 - loss: 0.2509 - mae: 0.3938 - rmse: 0.4831 - smape: 0.7386 - val_ia: 0.2707 - val_loss: 0.1502 - val_mae: 0.3006 - val_rmse: 0.3174 - val_smape: 0.6273

Epoch 30/64

4586/4586 - 40s - 9ms/step - ia: 0.7215 - loss: 0.2444 - mae: 0.3886 - rmse: 0.4767 - smape: 0.7281 - val_ia: 0.2697 - val_loss: 0.1473 - val_mae: 0.2991 - val_rmse: 0.3159 - val_smape: 0.6239

Epoch 31/64

4586/4586 - 41s - 9ms/step - ia: 0.7289 - loss: 0.2346 - mae: 0.3802 - rmse: 0.4673 - smape: 0.7138 - val_ia: 0.2694 - val_loss: 0.1450 - val_mae: 0.2979 - val_rmse: 0.3147 - val_smape: 0.6213

Epoch 32/64

4586/4586 - 40s - 9ms/step - ia: 0.7302 - loss: 0.2334 - mae: 0.3806 - rmse: 0.4662 - smape: 0.7136 - val_ia: 0.2691 - val_loss: 0.1431 - val_mae: 0.2969 - val_rmse: 0.3136 - val_smape: 0.6192

Epoch 33/64

4586/4586 - 39s - 9ms/step - ia: 0.7370 - loss: 0.2265 - mae: 0.3738 - rmse: 0.4590 - smape: 0.7005 - val_ia: 0.2691 - val_loss: 0.1416 - val_mae: 0.2959 - val_rmse: 0.3126 - val_smape: 0.6174

Epoch 34/64

4586/4586 - 39s - 9ms/step - ia: 0.7382 - loss: 0.2234 - mae: 0.3715 - rmse: 0.4565 - smape: 0.6979 - val_ia: 0.2695 - val_loss: 0.1400 - val_mae: 0.2948 - val_rmse: 0.3114 - val_smape: 0.6153

Epoch 35/64

4586/4586 - 38s - 8ms/step - ia: 0.7419 - loss: 0.2191 - mae: 0.3668 - rmse: 0.4516 - smape: 0.6887 - val_ia: 0.2700 - val_loss: 0.1383 - val_mae: 0.2936 - val_rmse: 0.3102 - val_smape: 0.6133

Epoch 36/64

4586/4586 - 40s - 9ms/step - ia: 0.7458 - loss: 0.2149 - mae: 0.3633 - rmse: 0.4465 - smape: 0.6832 - val_ia: 0.2710 - val_loss: 0.1368 - val_mae: 0.2924 - val_rmse: 0.3089 - val_smape: 0.6115

Epoch 37/64

4586/4586 - 40s - 9ms/step - ia: 0.7463 - loss: 0.2137 - mae: 0.3623 - rmse: 0.4457 - smape: 0.6822 - val_ia: 0.2722 - val_loss: 0.1356 - val_mae: 0.2913 - val_rmse: 0.3077 - val_smape: 0.6097

Epoch 38/64

4586/4586 - 39s - 8ms/step - ia: 0.7499 - loss: 0.2081 - mae: 0.3571 - rmse: 0.4394 - smape: 0.6744 - val_ia: 0.2733 - val_loss: 0.1342 - val_mae: 0.2900 - val_rmse: 0.3063 - val_smape: 0.6078

Epoch 39/64

4586/4586 - 39s - 9ms/step - ia: 0.7522 - loss: 0.2047 - mae: 0.3544 - rmse: 0.4361 - smape: 0.6713 - val_ia: 0.2741 - val_loss: 0.1325 - val_mae: 0.2885 - val_rmse: 0.3046 - val_smape: 0.6058

Epoch 40/64

4586/4586 - 40s - 9ms/step - ia: 0.7525 - loss: 0.2007 - mae: 0.3509 - rmse: 0.4321 - smape: 0.6644 - val_ia: 0.2747 - val_loss: 0.1311 - val_mae: 0.2873 - val_rmse: 0.3033 - val_smape: 0.6041

Epoch 41/64

4586/4586 - 40s - 9ms/step - ia: 0.7551 - loss: 0.1996 - mae: 0.3499 - rmse: 0.4303 - smape: 0.6632 - val_ia: 0.2757 - val_loss: 0.1298 - val_mae: 0.2861 - val_rmse: 0.3020 - val_smape: 0.6027

Epoch 42/64

4586/4586 - 41s - 9ms/step - ia: 0.7577 - loss: 0.1962 - mae: 0.3454 - rmse: 0.4264 - smape: 0.6559 - val_ia: 0.2765 - val_loss: 0.1284 - val_mae: 0.2849 - val_rmse: 0.3006 - val_smape: 0.6011

Epoch 43/64

4586/4586 - 40s - 9ms/step - ia: 0.7616 - loss: 0.1914 - mae: 0.3412 - rmse: 0.4210 - smape: 0.6503 - val_ia: 0.2774 - val_loss: 0.1273 - val_mae: 0.2837 - val_rmse: 0.2994 - val_smape: 0.5996

Epoch 44/64

4586/4586 - 40s - 9ms/step - ia: 0.7647 - loss: 0.1878 - mae: 0.3381 - rmse: 0.4175 - smape: 0.6431 - val_ia: 0.2787 - val_loss: 0.1261 - val_mae: 0.2825 - val_rmse: 0.2980 - val_smape: 0.5981

Epoch 45/64

4586/4586 - 40s - 9ms/step - ia: 0.7654 - loss: 0.1852 - mae: 0.3360 - rmse: 0.4140 - smape: 0.6407 - val_ia: 0.2800 - val_loss: 0.1248 - val_mae: 0.2811 - val_rmse: 0.2965 - val_smape: 0.5966

Epoch 46/64

4586/4586 - 40s - 9ms/step - ia: 0.7677 - loss: 0.1825 - mae: 0.3334 - rmse: 0.4115 - smape: 0.6384 - val_ia: 0.2810 - val_loss: 0.1234 - val_mae: 0.2797 - val_rmse: 0.2950 - val_smape: 0.5950

Epoch 47/64

4586/4586 - 40s - 9ms/step - ia: 0.7680 - loss: 0.1821 - mae: 0.3325 - rmse: 0.4106 - smape: 0.6388 - val_ia: 0.2820 - val_loss: 0.1221 - val_mae: 0.2784 - val_rmse: 0.2936 - val_smape: 0.5934

Epoch 48/64

4586/4586 - 40s - 9ms/step - ia: 0.7690 - loss: 0.1795 - mae: 0.3301 - rmse: 0.4073 - smape: 0.6310 - val_ia: 0.2829 - val_loss: 0.1213 - val_mae: 0.2775 - val_rmse: 0.2925 - val_smape: 0.5924

Epoch 49/64

4586/4586 - 40s - 9ms/step - ia: 0.7730 - loss: 0.1740 - mae: 0.3253 - rmse: 0.4015 - smape: 0.6258 - val_ia: 0.2841 - val_loss: 0.1197 - val_mae: 0.2760 - val_rmse: 0.2909 - val_smape: 0.5905

Epoch 50/64

4586/4586 - 40s - 9ms/step - ia: 0.7715 - loss: 0.1753 - mae: 0.3261 - rmse: 0.4023 - smape: 0.6288 - val_ia: 0.2853 - val_loss: 0.1184 - val_mae: 0.2747 - val_rmse: 0.2894 - val_smape: 0.5889

Epoch 51/64

4586/4586 - 40s - 9ms/step - ia: 0.7754 - loss: 0.1707 - mae: 0.3217 - rmse: 0.3970 - smape: 0.6198 - val_ia: 0.2862 - val_loss: 0.1172 - val_mae: 0.2735 - val_rmse: 0.2881 - val_smape: 0.5874

Epoch 52/64

4586/4586 - 39s - 9ms/step - ia: 0.7756 - loss: 0.1701 - mae: 0.3212 - rmse: 0.3968 - smape: 0.6205 - val_ia: 0.2872 - val_loss: 0.1159 - val_mae: 0.2721 - val_rmse: 0.2866 - val_smape: 0.5857

Epoch 53/64

4586/4586 - 38s - 8ms/step - ia: 0.7779 - loss: 0.1681 - mae: 0.3181 - rmse: 0.3935 - smape: 0.6128 - val_ia: 0.2883 - val_loss: 0.1153 - val_mae: 0.2713 - val_rmse: 0.2857 - val_smape: 0.5846

Epoch 54/64

4586/4586 - 40s - 9ms/step - ia: 0.7794 - loss: 0.1652 - mae: 0.3162 - rmse: 0.3909 - smape: 0.6124 - val_ia: 0.2891 - val_loss: 0.1139 - val_mae: 0.2699 - val_rmse: 0.2842 - val_smape: 0.5829

Epoch 55/64

4586/4586 - 39s - 8ms/step - ia: 0.7806 - loss: 0.1643 - mae: 0.3152 - rmse: 0.3895 - smape: 0.6098 - val_ia: 0.2902 - val_loss: 0.1125 - val_mae: 0.2685 - val_rmse: 0.2826 - val_smape: 0.5813

Epoch 56/64

4586/4586 - 41s - 9ms/step - ia: 0.7826 - loss: 0.1614 - mae: 0.3121 - rmse: 0.3863 - smape: 0.6050 - val_ia: 0.2910 - val_loss: 0.1117 - val_mae: 0.2675 - val_rmse: 0.2816 - val_smape: 0.5802

Epoch 57/64

4586/4586 - 47s - 10ms/step - ia: 0.7841 - loss: 0.1598 - mae: 0.3099 - rmse: 0.3835 - smape: 0.6022 - val_ia: 0.2919 - val_loss: 0.1106 - val_mae: 0.2663 - val_rmse: 0.2802 - val_smape: 0.5787

Epoch 58/64

4586/4586 - 47s - 10ms/step - ia: 0.7833 - loss: 0.1581 - mae: 0.3090 - rmse: 0.3815 - smape: 0.6017 - val_ia: 0.2927 - val_loss: 0.1098 - val_mae: 0.2654 - val_rmse: 0.2792 - val_smape: 0.5777

Epoch 59/64

4586/4586 - 46s - 10ms/step - ia: 0.7871 - loss: 0.1548 - mae: 0.3051 - rmse: 0.3781 - smape: 0.5923 - val_ia: 0.2936 - val_loss: 0.1086 - val_mae: 0.2641 - val_rmse: 0.2778 - val_smape: 0.5763

Epoch 60/64

4586/4586 - 48s - 10ms/step - ia: 0.7875 - loss: 0.1552 - mae: 0.3044 - rmse: 0.3779 - smape: 0.5952 - val_ia: 0.2945 - val_loss: 0.1074 - val_mae: 0.2628 - val_rmse: 0.2764 - val_smape: 0.5747

Epoch 61/64

4586/4586 - 48s - 10ms/step - ia: 0.7889 - loss: 0.1533 - mae: 0.3031 - rmse: 0.3760 - smape: 0.5912 - val_ia: 0.2955 - val_loss: 0.1063 - val_mae: 0.2616 - val_rmse: 0.2750 - val_smape: 0.5731

Epoch 62/64

4586/4586 - 46s - 10ms/step - ia: 0.7890 - loss: 0.1511 - mae: 0.3018 - rmse: 0.3737 - smape: 0.5913 - val_ia: 0.2963 - val_loss: 0.1055 - val_mae: 0.2606 - val_rmse: 0.2740 - val_smape: 0.5719

Epoch 63/64

4586/4586 - 48s - 10ms/step - ia: 0.7918 - loss: 0.1479 - mae: 0.2991 - rmse: 0.3693 - smape: 0.5856 - val_ia: 0.2972 - val_loss: 0.1043 - val_mae: 0.2593 - val_rmse: 0.2725 - val_smape: 0.5703

Epoch 64/64

4586/4586 - 46s - 10ms/step - ia: 0.7933 - loss: 0.1475 - mae: 0.2972 - rmse: 0.3686 - smape: 0.5815 - val_ia: 0.2979 - val_loss: 0.1035 - val_mae: 0.2583 - val_rmse: 0.2714 - val_smape: 0.5690

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:57 2s/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

 10%|█         | 5/50 [1:19:54<15:24:03, 1232.07s/trial, best loss: 0.002311278363512626]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 41s - 36ms/step - ia: 0.4981 - loss: 0.5446 - mae: 0.5783 - rmse: 0.7182 - smape: 1.1187 - val_ia: 0.4258 - val_loss: 0.2535 - val_mae: 0.4121 - val_rmse: 0.4637 - val_smape: 0.7926

Epoch 2/128

1147/1147 - 16s - 14ms/step - ia: 0.7595 - loss: 0.2116 - mae: 0.3556 - rmse: 0.4549 - smape: 0.6993 - val_ia: 0.4925 - val_loss: 0.2111 - val_mae: 0.3605 - val_rmse: 0.4099 - val_smape: 0.7077

Epoch 3/128

1147/1147 - 16s - 14ms/step - ia: 0.7953 - loss: 0.1687 - mae: 0.3176 - rmse: 0.4065 - smape: 0.6315 - val_ia: 0.5202 - val_loss: 0.1877 - val_mae: 0.3388 - val_rmse: 0.3849 - val_smape: 0.6842

Epoch 4/128

1147/1147 - 14s - 12ms/step - ia: 0.8111 - loss: 0.1467 - mae: 0.2946 - rmse: 0.3789 - smape: 0.5929 - val_ia: 0.5481 - val_loss: 0.1588 - val_mae: 0.3126 - val_rmse: 0.3556 - val_smape: 0.6556

Epoch 5/128

1147/1147 - 16s - 14ms/step - ia: 0.8233 - loss: 0.1294 - mae: 0.2756 - rmse: 0.3555 - smape: 0.5631 - val_ia: 0.5722 - val_loss: 0.1322 - val_mae: 0.2863 - val_rmse: 0.3269 - val_smape: 0.6256

Epoch 6/128

1147/1147 - 16s - 14ms/step - ia: 0.8357 - loss: 0.1144 - mae: 0.2580 - rmse: 0.3345 - smape: 0.5361 - val_ia: 0.5884 - val_loss: 0.1098 - val_mae: 0.2642 - val_rmse: 0.3021 - val_smape: 0.6000

Epoch 7/128

1147/1147 - 16s - 14ms/step - ia: 0.8439 - loss: 0.1040 - mae: 0.2459 - rmse: 0.3185 - smape: 0.5141 - val_ia: 0.6109 - val_loss: 0.0908 - val_mae: 0.2406 - val_rmse: 0.2769 - val_smape: 0.5692

Epoch 8/128

1147/1147 - 16s - 14ms/step - ia: 0.8525 - loss: 0.0937 - mae: 0.2328 - rmse: 0.3023 - smape: 0.4930 - val_ia: 0.6255 - val_loss: 0.0752 - val_mae: 0.2210 - val_rmse: 0.2555 - val_smape: 0.5400

Epoch 9/128

1147/1147 - 15s - 13ms/step - ia: 0.8581 - loss: 0.0870 - mae: 0.2240 - rmse: 0.2914 - smape: 0.4794 - val_ia: 0.6454 - val_loss: 0.0627 - val_mae: 0.2020 - val_rmse: 0.2353 - val_smape: 0.5093

Epoch 10/128

1147/1147 - 16s - 14ms/step - ia: 0.8639 - loss: 0.0810 - mae: 0.2155 - rmse: 0.2811 - smape: 0.4608 - val_ia: 0.6616 - val_loss: 0.0544 - val_mae: 0.1875 - val_rmse: 0.2202 - val_smape: 0.4836

Epoch 11/128

1147/1147 - 15s - 13ms/step - ia: 0.8691 - loss: 0.0751 - mae: 0.2075 - rmse: 0.2704 - smape: 0.4483 - val_ia: 0.6781 - val_loss: 0.0470 - val_mae: 0.1735 - val_rmse: 0.2056 - val_smape: 0.4592

Epoch 12/128

1147/1147 - 14s - 12ms/step - ia: 0.8738 - loss: 0.0697 - mae: 0.2002 - rmse: 0.2608 - smape: 0.4376 - val_ia: 0.7006 - val_loss: 0.0394 - val_mae: 0.1566 - val_rmse: 0.1885 - val_smape: 0.4274

Epoch 13/128

1147/1147 - 23s - 20ms/step - ia: 0.8766 - loss: 0.0673 - mae: 0.1958 - rmse: 0.2560 - smape: 0.4277 - val_ia: 0.7078 - val_loss: 0.0362 - val_mae: 0.1500 - val_rmse: 0.1814 - val_smape: 0.4128

Epoch 14/128

1147/1147 - 16s - 14ms/step - ia: 0.8803 - loss: 0.0639 - mae: 0.1905 - rmse: 0.2493 - smape: 0.4170 - val_ia: 0.7174 - val_loss: 0.0322 - val_mae: 0.1408 - val_rmse: 0.1718 - val_smape: 0.3910

Epoch 15/128

1147/1147 - 16s - 14ms/step - ia: 0.8831 - loss: 0.0611 - mae: 0.1861 - rmse: 0.2438 - smape: 0.4089 - val_ia: 0.7312 - val_loss: 0.0291 - val_mae: 0.1323 - val_rmse: 0.1632 - val_smape: 0.3745

Epoch 16/128

1147/1147 - 16s - 14ms/step - ia: 0.8859 - loss: 0.0581 - mae: 0.1816 - rmse: 0.2378 - smape: 0.4009 - val_ia: 0.7415 - val_loss: 0.0270 - val_mae: 0.1266 - val_rmse: 0.1571 - val_smape: 0.3653

Epoch 17/128

1147/1147 - 14s - 12ms/step - ia: 0.8877 - loss: 0.0564 - mae: 0.1786 - rmse: 0.2344 - smape: 0.3940 - val_ia: 0.7516 - val_loss: 0.0244 - val_mae: 0.1188 - val_rmse: 0.1492 - val_smape: 0.3453

Epoch 18/128

1147/1147 - 15s - 13ms/step - ia: 0.8907 - loss: 0.0547 - mae: 0.1748 - rmse: 0.2307 - smape: 0.3890 - val_ia: 0.7564 - val_loss: 0.0233 - val_mae: 0.1156 - val_rmse: 0.1456 - val_smape: 0.3372

Epoch 19/128

1147/1147 - 17s - 15ms/step - ia: 0.8919 - loss: 0.0526 - mae: 0.1720 - rmse: 0.2262 - smape: 0.3848 - val_ia: 0.7648 - val_loss: 0.0221 - val_mae: 0.1118 - val_rmse: 0.1417 - val_smape: 0.3316

Epoch 20/128

1147/1147 - 19s - 17ms/step - ia: 0.8933 - loss: 0.0514 - mae: 0.1704 - rmse: 0.2235 - smape: 0.3810 - val_ia: 0.7672 - val_loss: 0.0212 - val_mae: 0.1096 - val_rmse: 0.1387 - val_smape: 0.3275

Epoch 21/128

1147/1147 - 17s - 15ms/step - ia: 0.8952 - loss: 0.0495 - mae: 0.1669 - rmse: 0.2192 - smape: 0.3744 - val_ia: 0.7719 - val_loss: 0.0203 - val_mae: 0.1070 - val_rmse: 0.1356 - val_smape: 0.3197

Epoch 22/128

1147/1147 - 18s - 16ms/step - ia: 0.8963 - loss: 0.0491 - mae: 0.1657 - rmse: 0.2183 - smape: 0.3697 - val_ia: 0.7753 - val_loss: 0.0196 - val_mae: 0.1044 - val_rmse: 0.1329 - val_smape: 0.3127

Epoch 23/128

1147/1147 - 20s - 17ms/step - ia: 0.8977 - loss: 0.0478 - mae: 0.1632 - rmse: 0.2153 - smape: 0.3644 - val_ia: 0.7805 - val_loss: 0.0188 - val_mae: 0.1020 - val_rmse: 0.1302 - val_smape: 0.3071

Epoch 24/128

1147/1147 - 18s - 16ms/step - ia: 0.8988 - loss: 0.0468 - mae: 0.1617 - rmse: 0.2132 - smape: 0.3626 - val_ia: 0.7848 - val_loss: 0.0181 - val_mae: 0.0994 - val_rmse: 0.1274 - val_smape: 0.2996

Epoch 25/128

1147/1147 - 17s - 15ms/step - ia: 0.9008 - loss: 0.0451 - mae: 0.1587 - rmse: 0.2094 - smape: 0.3568 - val_ia: 0.7879 - val_loss: 0.0176 - val_mae: 0.0978 - val_rmse: 0.1255 - val_smape: 0.2950

Epoch 26/128

1147/1147 - 17s - 15ms/step - ia: 0.9010 - loss: 0.0448 - mae: 0.1581 - rmse: 0.2087 - smape: 0.3564 - val_ia: 0.7915 - val_loss: 0.0171 - val_mae: 0.0958 - val_rmse: 0.1234 - val_smape: 0.2903

Epoch 27/128

1147/1147 - 18s - 16ms/step - ia: 0.9023 - loss: 0.0437 - mae: 0.1560 - rmse: 0.2059 - smape: 0.3527 - val_ia: 0.7935 - val_loss: 0.0168 - val_mae: 0.0949 - val_rmse: 0.1223 - val_smape: 0.2886

Epoch 28/128

1147/1147 - 16s - 14ms/step - ia: 0.9026 - loss: 0.0436 - mae: 0.1556 - rmse: 0.2059 - smape: 0.3504 - val_ia: 0.7914 - val_loss: 0.0168 - val_mae: 0.0953 - val_rmse: 0.1221 - val_smape: 0.2873

Epoch 29/128

1147/1147 - 15s - 13ms/step - ia: 0.9037 - loss: 0.0427 - mae: 0.1541 - rmse: 0.2034 - smape: 0.3471 - val_ia: 0.7915 - val_loss: 0.0167 - val_mae: 0.0954 - val_rmse: 0.1218 - val_smape: 0.2865

Epoch 30/128

1147/1147 - 18s - 16ms/step - ia: 0.9046 - loss: 0.0416 - mae: 0.1524 - rmse: 0.2011 - smape: 0.3444 - val_ia: 0.7937 - val_loss: 0.0162 - val_mae: 0.0937 - val_rmse: 0.1200 - val_smape: 0.2811

Epoch 31/128

1147/1147 - 16s - 14ms/step - ia: 0.9056 - loss: 0.0409 - mae: 0.1511 - rmse: 0.1994 - smape: 0.3416 - val_ia: 0.7998 - val_loss: 0.0156 - val_mae: 0.0913 - val_rmse: 0.1174 - val_smape: 0.2775

Epoch 32/128

1147/1147 - 18s - 16ms/step - ia: 0.9060 - loss: 0.0409 - mae: 0.1504 - rmse: 0.1991 - smape: 0.3383 - val_ia: 0.8028 - val_loss: 0.0152 - val_mae: 0.0897 - val_rmse: 0.1158 - val_smape: 0.2730

Epoch 33/128

1147/1147 - 17s - 15ms/step - ia: 0.9059 - loss: 0.0407 - mae: 0.1504 - rmse: 0.1986 - smape: 0.3406 - val_ia: 0.8071 - val_loss: 0.0146 - val_mae: 0.0874 - val_rmse: 0.1134 - val_smape: 0.2672

Epoch 34/128

1147/1147 - 16s - 14ms/step - ia: 0.9071 - loss: 0.0399 - mae: 0.1481 - rmse: 0.1966 - smape: 0.3342 - val_ia: 0.8023 - val_loss: 0.0152 - val_mae: 0.0899 - val_rmse: 0.1155 - val_smape: 0.2723

Epoch 35/128

1147/1147 - 18s - 15ms/step - ia: 0.9082 - loss: 0.0390 - mae: 0.1470 - rmse: 0.1946 - smape: 0.3312 - val_ia: 0.8070 - val_loss: 0.0146 - val_mae: 0.0878 - val_rmse: 0.1135 - val_smape: 0.2684

Epoch 36/128

1147/1147 - 15s - 14ms/step - ia: 0.9086 - loss: 0.0387 - mae: 0.1462 - rmse: 0.1937 - smape: 0.3321 - val_ia: 0.8063 - val_loss: 0.0146 - val_mae: 0.0879 - val_rmse: 0.1133 - val_smape: 0.2669

Epoch 37/128

1147/1147 - 17s - 15ms/step - ia: 0.9095 - loss: 0.0379 - mae: 0.1447 - rmse: 0.1918 - smape: 0.3295 - val_ia: 0.8078 - val_loss: 0.0144 - val_mae: 0.0869 - val_rmse: 0.1122 - val_smape: 0.2627

Epoch 38/128

1147/1147 - 15s - 14ms/step - ia: 0.9094 - loss: 0.0380 - mae: 0.1448 - rmse: 0.1921 - smape: 0.3270 - val_ia: 0.8115 - val_loss: 0.0139 - val_mae: 0.0850 - val_rmse: 0.1102 - val_smape: 0.2572

Epoch 39/128

1147/1147 - 18s - 16ms/step - ia: 0.9100 - loss: 0.0378 - mae: 0.1437 - rmse: 0.1914 - smape: 0.3262 - val_ia: 0.8124 - val_loss: 0.0138 - val_mae: 0.0849 - val_rmse: 0.1099 - val_smape: 0.2590

Epoch 40/128

1147/1147 - 15s - 13ms/step - ia: 0.9104 - loss: 0.0374 - mae: 0.1433 - rmse: 0.1904 - smape: 0.3249 - val_ia: 0.8091 - val_loss: 0.0142 - val_mae: 0.0865 - val_rmse: 0.1113 - val_smape: 0.2623

Epoch 41/128

1147/1147 - 14s - 12ms/step - ia: 0.9108 - loss: 0.0370 - mae: 0.1424 - rmse: 0.1894 - smape: 0.3217 - val_ia: 0.8143 - val_loss: 0.0135 - val_mae: 0.0839 - val_rmse: 0.1087 - val_smape: 0.2566

Epoch 42/128

1147/1147 - 13s - 12ms/step - ia: 0.9120 - loss: 0.0362 - mae: 0.1409 - rmse: 0.1870 - smape: 0.3197 - val_ia: 0.8105 - val_loss: 0.0139 - val_mae: 0.0854 - val_rmse: 0.1100 - val_smape: 0.2575

Epoch 43/128

1147/1147 - 16s - 14ms/step - ia: 0.9122 - loss: 0.0358 - mae: 0.1406 - rmse: 0.1864 - smape: 0.3215 - val_ia: 0.8172 - val_loss: 0.0132 - val_mae: 0.0826 - val_rmse: 0.1071 - val_smape: 0.2523

Epoch 44/128

1147/1147 - 19s - 16ms/step - ia: 0.9124 - loss: 0.0359 - mae: 0.1400 - rmse: 0.1862 - smape: 0.3167 - val_ia: 0.8183 - val_loss: 0.0129 - val_mae: 0.0815 - val_rmse: 0.1061 - val_smape: 0.2471

Epoch 45/128

1147/1147 - 15s - 13ms/step - ia: 0.9127 - loss: 0.0359 - mae: 0.1396 - rmse: 0.1865 - smape: 0.3169 - val_ia: 0.8189 - val_loss: 0.0129 - val_mae: 0.0818 - val_rmse: 0.1061 - val_smape: 0.2510

Epoch 46/128

1147/1147 - 15s - 13ms/step - ia: 0.9135 - loss: 0.0348 - mae: 0.1381 - rmse: 0.1836 - smape: 0.3149 - val_ia: 0.8164 - val_loss: 0.0131 - val_mae: 0.0829 - val_rmse: 0.1070 - val_smape: 0.2524

Epoch 47/128

1147/1147 - 14s - 12ms/step - ia: 0.9136 - loss: 0.0350 - mae: 0.1383 - rmse: 0.1841 - smape: 0.3122 - val_ia: 0.8137 - val_loss: 0.0132 - val_mae: 0.0836 - val_rmse: 0.1076 - val_smape: 0.2533

Epoch 48/128

1147/1147 - 16s - 14ms/step - ia: 0.9144 - loss: 0.0343 - mae: 0.1373 - rmse: 0.1825 - smape: 0.3126 - val_ia: 0.8202 - val_loss: 0.0126 - val_mae: 0.0809 - val_rmse: 0.1049 - val_smape: 0.2469

Epoch 49/128

1147/1147 - 17s - 15ms/step - ia: 0.9151 - loss: 0.0336 - mae: 0.1361 - rmse: 0.1802 - smape: 0.3105 - val_ia: 0.8173 - val_loss: 0.0128 - val_mae: 0.0819 - val_rmse: 0.1056 - val_smape: 0.2480

Epoch 50/128

1147/1147 - 17s - 15ms/step - ia: 0.9149 - loss: 0.0342 - mae: 0.1361 - rmse: 0.1818 - smape: 0.3105 - val_ia: 0.8230 - val_loss: 0.0123 - val_mae: 0.0795 - val_rmse: 0.1032 - val_smape: 0.2434

Epoch 51/128

1147/1147 - 15s - 13ms/step - ia: 0.9153 - loss: 0.0339 - mae: 0.1357 - rmse: 0.1809 - smape: 0.3081 - val_ia: 0.8164 - val_loss: 0.0127 - val_mae: 0.0817 - val_rmse: 0.1052 - val_smape: 0.2458

Epoch 52/128

1147/1147 - 17s - 15ms/step - ia: 0.9152 - loss: 0.0337 - mae: 0.1358 - rmse: 0.1805 - smape: 0.3084 - val_ia: 0.8218 - val_loss: 0.0123 - val_mae: 0.0797 - val_rmse: 0.1033 - val_smape: 0.2418

Epoch 53/128

1147/1147 - 16s - 14ms/step - ia: 0.9158 - loss: 0.0332 - mae: 0.1349 - rmse: 0.1794 - smape: 0.3068 - val_ia: 0.8190 - val_loss: 0.0125 - val_mae: 0.0807 - val_rmse: 0.1041 - val_smape: 0.2431

Epoch 54/128

1147/1147 - 17s - 15ms/step - ia: 0.9170 - loss: 0.0324 - mae: 0.1328 - rmse: 0.1770 - smape: 0.3041 - val_ia: 0.8235 - val_loss: 0.0120 - val_mae: 0.0790 - val_rmse: 0.1023 - val_smape: 0.2410

Epoch 55/128

1147/1147 - 15s - 14ms/step - ia: 0.9165 - loss: 0.0328 - mae: 0.1335 - rmse: 0.1783 - smape: 0.3044 - val_ia: 0.8300 - val_loss: 0.0114 - val_mae: 0.0763 - val_rmse: 0.0996 - val_smape: 0.2365

Epoch 56/128

1147/1147 - 14s - 12ms/step - ia: 0.9170 - loss: 0.0324 - mae: 0.1329 - rmse: 0.1771 - smape: 0.3043 - val_ia: 0.8235 - val_loss: 0.0119 - val_mae: 0.0788 - val_rmse: 0.1019 - val_smape: 0.2402

Epoch 57/128

1147/1147 - 17s - 15ms/step - ia: 0.9174 - loss: 0.0325 - mae: 0.1325 - rmse: 0.1773 - smape: 0.3017 - val_ia: 0.8234 - val_loss: 0.0118 - val_mae: 0.0784 - val_rmse: 0.1015 - val_smape: 0.2372

Epoch 58/128

1147/1147 - 17s - 15ms/step - ia: 0.9175 - loss: 0.0322 - mae: 0.1321 - rmse: 0.1766 - smape: 0.3001 - val_ia: 0.8297 - val_loss: 0.0113 - val_mae: 0.0762 - val_rmse: 0.0991 - val_smape: 0.2349

Epoch 59/128

1147/1147 - 15s - 13ms/step - ia: 0.9178 - loss: 0.0318 - mae: 0.1316 - rmse: 0.1754 - smape: 0.3005 - val_ia: 0.8286 - val_loss: 0.0113 - val_mae: 0.0762 - val_rmse: 0.0992 - val_smape: 0.2321

Epoch 60/128

1147/1147 - 16s - 14ms/step - ia: 0.9175 - loss: 0.0321 - mae: 0.1319 - rmse: 0.1760 - smape: 0.2993 - val_ia: 0.8342 - val_loss: 0.0108 - val_mae: 0.0738 - val_rmse: 0.0968 - val_smape: 0.2251

Epoch 61/128

1147/1147 - 17s - 15ms/step - ia: 0.9180 - loss: 0.0317 - mae: 0.1309 - rmse: 0.1751 - smape: 0.2991 - val_ia: 0.8293 - val_loss: 0.0111 - val_mae: 0.0755 - val_rmse: 0.0983 - val_smape: 0.2290

Epoch 62/128

1147/1147 - 17s - 15ms/step - ia: 0.9179 - loss: 0.0317 - mae: 0.1314 - rmse: 0.1753 - smape: 0.2997 - val_ia: 0.8352 - val_loss: 0.0107 - val_mae: 0.0735 - val_rmse: 0.0962 - val_smape: 0.2275

Epoch 63/128

1147/1147 - 17s - 15ms/step - ia: 0.9188 - loss: 0.0311 - mae: 0.1301 - rmse: 0.1735 - smape: 0.2975 - val_ia: 0.8359 - val_loss: 0.0106 - val_mae: 0.0729 - val_rmse: 0.0955 - val_smape: 0.2220

Epoch 64/128

1147/1147 - 21s - 18ms/step - ia: 0.9189 - loss: 0.0310 - mae: 0.1298 - rmse: 0.1734 - smape: 0.2926 - val_ia: 0.8354 - val_loss: 0.0106 - val_mae: 0.0734 - val_rmse: 0.0958 - val_smape: 0.2256

Epoch 65/128

1147/1147 - 17s - 15ms/step - ia: 0.9197 - loss: 0.0305 - mae: 0.1287 - rmse: 0.1716 - smape: 0.2947 - val_ia: 0.8345 - val_loss: 0.0106 - val_mae: 0.0734 - val_rmse: 0.0957 - val_smape: 0.2238

Epoch 66/128

1147/1147 - 17s - 15ms/step - ia: 0.9197 - loss: 0.0305 - mae: 0.1287 - rmse: 0.1719 - smape: 0.2924 - val_ia: 0.8289 - val_loss: 0.0109 - val_mae: 0.0750 - val_rmse: 0.0974 - val_smape: 0.2226

Epoch 67/128

1147/1147 - 17s - 15ms/step - ia: 0.9207 - loss: 0.0298 - mae: 0.1271 - rmse: 0.1699 - smape: 0.2898 - val_ia: 0.8306 - val_loss: 0.0107 - val_mae: 0.0742 - val_rmse: 0.0965 - val_smape: 0.2213

Epoch 68/128

1147/1147 - 15s - 13ms/step - ia: 0.9195 - loss: 0.0307 - mae: 0.1289 - rmse: 0.1722 - smape: 0.2932 - val_ia: 0.8351 - val_loss: 0.0104 - val_mae: 0.0728 - val_rmse: 0.0950 - val_smape: 0.2220

Epoch 69/128

1147/1147 - 14s - 12ms/step - ia: 0.9204 - loss: 0.0300 - mae: 0.1274 - rmse: 0.1704 - smape: 0.2913 - val_ia: 0.8390 - val_loss: 0.0101 - val_mae: 0.0715 - val_rmse: 0.0935 - val_smape: 0.2209

Epoch 70/128

1147/1147 - 13s - 12ms/step - ia: 0.9204 - loss: 0.0304 - mae: 0.1279 - rmse: 0.1713 - smape: 0.2906 - val_ia: 0.8351 - val_loss: 0.0104 - val_mae: 0.0727 - val_rmse: 0.0947 - val_smape: 0.2211

Epoch 71/128

1147/1147 - 16s - 14ms/step - ia: 0.9208 - loss: 0.0299 - mae: 0.1268 - rmse: 0.1700 - smape: 0.2901 - val_ia: 0.8348 - val_loss: 0.0104 - val_mae: 0.0733 - val_rmse: 0.0950 - val_smape: 0.2259

Epoch 72/128

1147/1147 - 16s - 14ms/step - ia: 0.9211 - loss: 0.0297 - mae: 0.1264 - rmse: 0.1695 - smape: 0.2877 - val_ia: 0.8395 - val_loss: 0.0100 - val_mae: 0.0711 - val_rmse: 0.0929 - val_smape: 0.2183

Epoch 73/128

1147/1147 - 14s - 12ms/step - ia: 0.9214 - loss: 0.0296 - mae: 0.1262 - rmse: 0.1690 - smape: 0.2869 - val_ia: 0.8356 - val_loss: 0.0102 - val_mae: 0.0723 - val_rmse: 0.0941 - val_smape: 0.2188

Epoch 74/128

1147/1147 - 16s - 14ms/step - ia: 0.9215 - loss: 0.0292 - mae: 0.1256 - rmse: 0.1679 - smape: 0.2858 - val_ia: 0.8346 - val_loss: 0.0102 - val_mae: 0.0728 - val_rmse: 0.0944 - val_smape: 0.2219

Epoch 75/128

1147/1147 - 17s - 15ms/step - ia: 0.9221 - loss: 0.0288 - mae: 0.1247 - rmse: 0.1669 - smape: 0.2860 - val_ia: 0.8397 - val_loss: 0.0098 - val_mae: 0.0706 - val_rmse: 0.0922 - val_smape: 0.2155

Epoch 76/128

1147/1147 - 16s - 14ms/step - ia: 0.9220 - loss: 0.0289 - mae: 0.1248 - rmse: 0.1670 - smape: 0.2866 - val_ia: 0.8428 - val_loss: 0.0095 - val_mae: 0.0692 - val_rmse: 0.0908 - val_smape: 0.2124

Epoch 77/128

1147/1147 - 14s - 13ms/step - ia: 0.9219 - loss: 0.0290 - mae: 0.1250 - rmse: 0.1673 - smape: 0.2858 - val_ia: 0.8376 - val_loss: 0.0099 - val_mae: 0.0713 - val_rmse: 0.0926 - val_smape: 0.2167

Epoch 78/128

1147/1147 - 16s - 14ms/step - ia: 0.9221 - loss: 0.0290 - mae: 0.1250 - rmse: 0.1675 - smape: 0.2846 - val_ia: 0.8416 - val_loss: 0.0096 - val_mae: 0.0696 - val_rmse: 0.0909 - val_smape: 0.2117

Epoch 79/128

1147/1147 - 16s - 14ms/step - ia: 0.9226 - loss: 0.0283 - mae: 0.1238 - rmse: 0.1654 - smape: 0.2831 - val_ia: 0.8390 - val_loss: 0.0097 - val_mae: 0.0707 - val_rmse: 0.0918 - val_smape: 0.2161

Epoch 80/128

1147/1147 - 15s - 13ms/step - ia: 0.9227 - loss: 0.0284 - mae: 0.1240 - rmse: 0.1656 - smape: 0.2838 - val_ia: 0.8410 - val_loss: 0.0095 - val_mae: 0.0697 - val_rmse: 0.0908 - val_smape: 0.2123

Epoch 81/128

1147/1147 - 20s - 18ms/step - ia: 0.9236 - loss: 0.0283 - mae: 0.1228 - rmse: 0.1651 - smape: 0.2797 - val_ia: 0.8363 - val_loss: 0.0098 - val_mae: 0.0715 - val_rmse: 0.0924 - val_smape: 0.2166

Epoch 82/128

1147/1147 - 14s - 12ms/step - ia: 0.9234 - loss: 0.0279 - mae: 0.1229 - rmse: 0.1644 - smape: 0.2819 - val_ia: 0.8345 - val_loss: 0.0099 - val_mae: 0.0721 - val_rmse: 0.0928 - val_smape: 0.2156

Epoch 83/128

1147/1147 - 14s - 12ms/step - ia: 0.9237 - loss: 0.0277 - mae: 0.1223 - rmse: 0.1637 - smape: 0.2791 - val_ia: 0.8444 - val_loss: 0.0092 - val_mae: 0.0682 - val_rmse: 0.0891 - val_smape: 0.2086

Epoch 84/128

1147/1147 - 15s - 13ms/step - ia: 0.9236 - loss: 0.0279 - mae: 0.1226 - rmse: 0.1642 - smape: 0.2806 - val_ia: 0.8428 - val_loss: 0.0093 - val_mae: 0.0690 - val_rmse: 0.0897 - val_smape: 0.2108

Epoch 85/128

1147/1147 - 14s - 12ms/step - ia: 0.9229 - loss: 0.0283 - mae: 0.1235 - rmse: 0.1654 - smape: 0.2807 - val_ia: 0.8442 - val_loss: 0.0091 - val_mae: 0.0685 - val_rmse: 0.0890 - val_smape: 0.2109

Epoch 86/128

1147/1147 - 13s - 11ms/step - ia: 0.9239 - loss: 0.0277 - mae: 0.1220 - rmse: 0.1636 - smape: 0.2764 - val_ia: 0.8438 - val_loss: 0.0091 - val_mae: 0.0683 - val_rmse: 0.0888 - val_smape: 0.2093

Epoch 87/128

1147/1147 - 12s - 11ms/step - ia: 0.9242 - loss: 0.0273 - mae: 0.1215 - rmse: 0.1625 - smape: 0.2800 - val_ia: 0.8447 - val_loss: 0.0090 - val_mae: 0.0679 - val_rmse: 0.0884 - val_smape: 0.2068

Epoch 88/128

1147/1147 - 13s - 12ms/step - ia: 0.9241 - loss: 0.0275 - mae: 0.1218 - rmse: 0.1627 - smape: 0.2788 - val_ia: 0.8462 - val_loss: 0.0088 - val_mae: 0.0669 - val_rmse: 0.0874 - val_smape: 0.2020

Epoch 89/128

1147/1147 - 14s - 12ms/step - ia: 0.9245 - loss: 0.0273 - mae: 0.1211 - rmse: 0.1623 - smape: 0.2752 - val_ia: 0.8429 - val_loss: 0.0091 - val_mae: 0.0685 - val_rmse: 0.0888 - val_smape: 0.2072

Epoch 90/128

1147/1147 - 14s - 12ms/step - ia: 0.9249 - loss: 0.0271 - mae: 0.1206 - rmse: 0.1619 - smape: 0.2746 - val_ia: 0.8460 - val_loss: 0.0088 - val_mae: 0.0671 - val_rmse: 0.0873 - val_smape: 0.2051

Epoch 91/128

1147/1147 - 14s - 12ms/step - ia: 0.9248 - loss: 0.0272 - mae: 0.1208 - rmse: 0.1620 - smape: 0.2755 - val_ia: 0.8477 - val_loss: 0.0087 - val_mae: 0.0664 - val_rmse: 0.0867 - val_smape: 0.2032

Epoch 92/128

1147/1147 - 13s - 12ms/step - ia: 0.9257 - loss: 0.0265 - mae: 0.1194 - rmse: 0.1596 - smape: 0.2739 - val_ia: 0.8440 - val_loss: 0.0089 - val_mae: 0.0677 - val_rmse: 0.0879 - val_smape: 0.2044

Epoch 93/128

1147/1147 - 10s - 9ms/step - ia: 0.9250 - loss: 0.0271 - mae: 0.1205 - rmse: 0.1616 - smape: 0.2728 - val_ia: 0.8430 - val_loss: 0.0090 - val_mae: 0.0683 - val_rmse: 0.0883 - val_smape: 0.2071

Epoch 94/128

1147/1147 - 14s - 12ms/step - ia: 0.9258 - loss: 0.0263 - mae: 0.1189 - rmse: 0.1595 - smape: 0.2700 - val_ia: 0.8459 - val_loss: 0.0087 - val_mae: 0.0671 - val_rmse: 0.0870 - val_smape: 0.2045

Epoch 95/128

1147/1147 - 14s - 12ms/step - ia: 0.9256 - loss: 0.0268 - mae: 0.1194 - rmse: 0.1608 - smape: 0.2733 - val_ia: 0.8486 - val_loss: 0.0086 - val_mae: 0.0666 - val_rmse: 0.0863 - val_smape: 0.2064

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 8s - 53ms/step - ia: 0.8826 - loss: 0.0749 - mae: 0.1845 - rmse: 0.2469 - smape: 0.3835 - val_ia: 0.9552 - val_loss: 0.0072 - val_mae: 0.0606 - val_rmse: 0.0842 - val_smape: 0.1644

Epoch 2/128

144/144 - 2s - 13ms/step - ia: 0.9208 - loss: 0.0323 - mae: 0.1294 - rmse: 0.1793 - smape: 0.2671 - val_ia: 0.9401 - val_loss: 0.0103 - val_mae: 0.0794 - val_rmse: 0.0978 - val_smape: 0.1944

Epoch 3/128

144/144 - 2s - 14ms/step - ia: 0.9240 - loss: 0.0306 - mae: 0.1242 - rmse: 0.1743 - smape: 0.2489 - val_ia: 0.9620 - val_loss: 0.0046 - val_mae: 0.0508 - val_rmse: 0.0675 - val_smape: 0.1521

Epoch 4/128

144/144 - 2s - 12ms/step - ia: 0.9247 - loss: 0.0303 - mae: 0.1230 - rmse: 0.1738 - smape: 0.2428 - val_ia: 0.9409 - val_loss: 0.0097 - val_mae: 0.0775 - val_rmse: 0.0976 - val_smape: 0.1755

Epoch 5/128

144/144 - 2s - 13ms/step - ia: 0.9256 - loss: 0.0296 - mae: 0.1217 - rmse: 0.1710 - smape: 0.2401 - val_ia: 0.9607 - val_loss: 0.0052 - val_mae: 0.0525 - val_rmse: 0.0716 - val_smape: 0.1435

Epoch 6/128

144/144 - 2s - 12ms/step - ia: 0.9272 - loss: 0.0286 - mae: 0.1191 - rmse: 0.1686 - smape: 0.2357 - val_ia: 0.9593 - val_loss: 0.0052 - val_mae: 0.0563 - val_rmse: 0.0720 - val_smape: 0.1459

Epoch 7/128

144/144 - 2s - 14ms/step - ia: 0.9270 - loss: 0.0291 - mae: 0.1193 - rmse: 0.1701 - smape: 0.2338 - val_ia: 0.9668 - val_loss: 0.0037 - val_mae: 0.0438 - val_rmse: 0.0599 - val_smape: 0.1331

Epoch 8/128

144/144 - 2s - 13ms/step - ia: 0.9279 - loss: 0.0285 - mae: 0.1179 - rmse: 0.1681 - smape: 0.2299 - val_ia: 0.9507 - val_loss: 0.0065 - val_mae: 0.0652 - val_rmse: 0.0792 - val_smape: 0.1781

Epoch 9/128

144/144 - 2s - 13ms/step - ia: 0.9282 - loss: 0.0281 - mae: 0.1174 - rmse: 0.1672 - smape: 0.2293 - val_ia: 0.9660 - val_loss: 0.0038 - val_mae: 0.0447 - val_rmse: 0.0604 - val_smape: 0.1390

Epoch 10/128

144/144 - 2s - 14ms/step - ia: 0.9291 - loss: 0.0275 - mae: 0.1159 - rmse: 0.1654 - smape: 0.2279 - val_ia: 0.9667 - val_loss: 0.0037 - val_mae: 0.0435 - val_rmse: 0.0602 - val_smape: 0.1406

Epoch 11/128

144/144 - 2s - 13ms/step - ia: 0.9300 - loss: 0.0270 - mae: 0.1144 - rmse: 0.1637 - smape: 0.2225 - val_ia: 0.9634 - val_loss: 0.0043 - val_mae: 0.0485 - val_rmse: 0.0642 - val_smape: 0.1482

Epoch 12/128

144/144 - 2s - 13ms/step - ia: 0.9304 - loss: 0.0263 - mae: 0.1139 - rmse: 0.1619 - smape: 0.2235 - val_ia: 0.9575 - val_loss: 0.0053 - val_mae: 0.0566 - val_rmse: 0.0723 - val_smape: 0.1644

Epoch 13/128

144/144 - 2s - 14ms/step - ia: 0.9300 - loss: 0.0269 - mae: 0.1145 - rmse: 0.1633 - smape: 0.2224 - val_ia: 0.9623 - val_loss: 0.0051 - val_mae: 0.0510 - val_rmse: 0.0708 - val_smape: 0.1433

Epoch 14/128

144/144 - 2s - 14ms/step - ia: 0.9289 - loss: 0.0276 - mae: 0.1163 - rmse: 0.1655 - smape: 0.2263 - val_ia: 0.9628 - val_loss: 0.0048 - val_mae: 0.0504 - val_rmse: 0.0686 - val_smape: 0.1419

Epoch 15/128

144/144 - 2s - 16ms/step - ia: 0.9303 - loss: 0.0268 - mae: 0.1140 - rmse: 0.1632 - smape: 0.2206 - val_ia: 0.9674 - val_loss: 0.0038 - val_mae: 0.0443 - val_rmse: 0.0606 - val_smape: 0.1269

Epoch 16/128

144/144 - 2s - 16ms/step - ia: 0.9305 - loss: 0.0262 - mae: 0.1137 - rmse: 0.1615 - smape: 0.2218 - val_ia: 0.9651 - val_loss: 0.0041 - val_mae: 0.0469 - val_rmse: 0.0635 - val_smape: 0.1373

Epoch 17/128

144/144 - 2s - 17ms/step - ia: 0.9303 - loss: 0.0270 - mae: 0.1141 - rmse: 0.1636 - smape: 0.2203 - val_ia: 0.9684 - val_loss: 0.0033 - val_mae: 0.0421 - val_rmse: 0.0564 - val_smape: 0.1353

Epoch 18/128

144/144 - 2s - 15ms/step - ia: 0.9309 - loss: 0.0264 - mae: 0.1132 - rmse: 0.1617 - smape: 0.2203 - val_ia: 0.9466 - val_loss: 0.0080 - val_mae: 0.0709 - val_rmse: 0.0862 - val_smape: 0.1777

Epoch 19/128

144/144 - 2s - 15ms/step - ia: 0.9309 - loss: 0.0264 - mae: 0.1130 - rmse: 0.1620 - smape: 0.2193 - val_ia: 0.9722 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0528 - val_smape: 0.1161

Epoch 20/128

144/144 - 2s - 13ms/step - ia: 0.9308 - loss: 0.0263 - mae: 0.1132 - rmse: 0.1618 - smape: 0.2181 - val_ia: 0.9637 - val_loss: 0.0042 - val_mae: 0.0481 - val_rmse: 0.0631 - val_smape: 0.1405

Epoch 21/128

144/144 - 2s - 12ms/step - ia: 0.9309 - loss: 0.0264 - mae: 0.1130 - rmse: 0.1620 - smape: 0.2170 - val_ia: 0.9672 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0589 - val_smape: 0.1401

Epoch 22/128

144/144 - 2s - 12ms/step - ia: 0.9309 - loss: 0.0262 - mae: 0.1130 - rmse: 0.1615 - smape: 0.2194 - val_ia: 0.9482 - val_loss: 0.0073 - val_mae: 0.0692 - val_rmse: 0.0826 - val_smape: 0.1786

Epoch 23/128

144/144 - 2s - 12ms/step - ia: 0.9294 - loss: 0.0275 - mae: 0.1156 - rmse: 0.1655 - smape: 0.2215 - val_ia: 0.9565 - val_loss: 0.0057 - val_mae: 0.0580 - val_rmse: 0.0732 - val_smape: 0.1504

Epoch 24/128

144/144 - 2s - 13ms/step - ia: 0.9294 - loss: 0.0274 - mae: 0.1155 - rmse: 0.1651 - smape: 0.2223 - val_ia: 0.9706 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0547 - val_smape: 0.1307

Epoch 25/128

144/144 - 2s - 14ms/step - ia: 0.9312 - loss: 0.0260 - mae: 0.1125 - rmse: 0.1608 - smape: 0.2191 - val_ia: 0.9480 - val_loss: 0.0075 - val_mae: 0.0693 - val_rmse: 0.0852 - val_smape: 0.1730

Epoch 26/128

144/144 - 2s - 17ms/step - ia: 0.9304 - loss: 0.0266 - mae: 0.1139 - rmse: 0.1625 - smape: 0.2183 - val_ia: 0.9533 - val_loss: 0.0060 - val_mae: 0.0618 - val_rmse: 0.0751 - val_smape: 0.1723

Epoch 27/128

144/144 - 3s - 17ms/step - ia: 0.9310 - loss: 0.0264 - mae: 0.1130 - rmse: 0.1616 - smape: 0.2175 - val_ia: 0.9484 - val_loss: 0.0074 - val_mae: 0.0689 - val_rmse: 0.0835 - val_smape: 0.1797

Epoch 28/128

144/144 - 2s - 16ms/step - ia: 0.9300 - loss: 0.0268 - mae: 0.1146 - rmse: 0.1633 - smape: 0.2199 - val_ia: 0.9319 - val_loss: 0.0131 - val_mae: 0.0902 - val_rmse: 0.1095 - val_smape: 0.2137

Epoch 29/128

144/144 - 2s - 16ms/step - ia: 0.9303 - loss: 0.0267 - mae: 0.1140 - rmse: 0.1628 - smape: 0.2201 - val_ia: 0.9616 - val_loss: 0.0049 - val_mae: 0.0521 - val_rmse: 0.0682 - val_smape: 0.1571

Epoch 30/128

144/144 - 2s - 15ms/step - ia: 0.9307 - loss: 0.0263 - mae: 0.1133 - rmse: 0.1617 - smape: 0.2210 - val_ia: 0.9612 - val_loss: 0.0047 - val_mae: 0.0518 - val_rmse: 0.0675 - val_smape: 0.1451

Epoch 31/128

144/144 - 2s - 17ms/step - ia: 0.9302 - loss: 0.0269 - mae: 0.1141 - rmse: 0.1637 - smape: 0.2194 - val_ia: 0.9621 - val_loss: 0.0045 - val_mae: 0.0504 - val_rmse: 0.0666 - val_smape: 0.1662

Epoch 32/128

144/144 - 2s - 17ms/step - ia: 0.9266 - loss: 0.0293 - mae: 0.1199 - rmse: 0.1705 - smape: 0.2328 - val_ia: 0.9255 - val_loss: 0.0137 - val_mae: 0.0970 - val_rmse: 0.1160 - val_smape: 0.2171

Epoch 33/128

144/144 - 2s - 17ms/step - ia: 0.9272 - loss: 0.0290 - mae: 0.1190 - rmse: 0.1697 - smape: 0.2287 - val_ia: 0.9592 - val_loss: 0.0057 - val_mae: 0.0551 - val_rmse: 0.0747 - val_smape: 0.1565

Epoch 34/128

144/144 - 2s - 17ms/step - ia: 0.9285 - loss: 0.0283 - mae: 0.1171 - rmse: 0.1677 - smape: 0.2253 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0423 - val_rmse: 0.0577 - val_smape: 0.1425

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:54 707ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 14%|█▍        | 7/50 [1:55:54<12:32:07, 1049.47s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2293/2293 - 55s - 24ms/step - ia: 0.9187 - loss: 0.0312 - mae: 0.1273 - rmse: 0.1662 - smape: 0.2812 - val_ia: 0.8094 - val_loss: 0.0042 - val_mae: 0.0476 - val_rmse: 0.0594 - val_smape: 0.1342

Epoch 2/8

2293/2293 - 37s - 16ms/step - ia: 0.9374 - loss: 0.0185 - mae: 0.0984 - rmse: 0.1310 - smape: 0.2216 - val_ia: 0.7239 - val_loss: 0.0083 - val_mae: 0.0719 - val_rmse: 0.0826 - val_smape: 0.1693

Epoch 3/8

2293/2293 - 35s - 15ms/step - ia: 0.9405 - loss: 0.0167 - mae: 0.0938 - rmse: 0.1243 - smape: 0.2156 - val_ia: 0.8130 - val_loss: 0.0043 - val_mae: 0.0497 - val_rmse: 0.0603 - val_smape: 0.1530

Epoch 4/8

2293/2293 - 39s - 17ms/step - ia: 0.9413 - loss: 0.0163 - mae: 0.0923 - rmse: 0.1227 - smape: 0.2133 - val_ia: 0.8036 - val_loss: 0.0043 - val_mae: 0.0481 - val_rmse: 0.0590 - val_smape: 0.1452

Epoch 5/8

2293/2293 - 38s - 17ms/step - ia: 0.9419 - loss: 0.0159 - mae: 0.0910 - rmse: 0.1212 - smape: 0.2095 - val_ia: 0.7777 - val_loss: 0.0054 - val_mae: 0.0559 - val_rmse: 0.0666 - val_smape: 0.1537

Epoch 6/8

2293/2293 - 36s - 16ms/step - ia: 0.9433 - loss: 0.0153 - mae: 0.0893 - rmse: 0.1185 - smape: 0.2084 - val_ia: 0.7734 - val_loss: 0.0063 - val_mae: 0.0618 - val_rmse: 0.0730 - val_smape: 0.1517

Epoch 7/8

2293/2293 - 34s - 15ms/step - ia: 0.9441 - loss: 0.0150 - mae: 0.0880 - rmse: 0.1172 - smape: 0.2040 - val_ia: 0.8297 - val_loss: 0.0034 - val_mae: 0.0414 - val_rmse: 0.0521 - val_smape: 0.1355

Epoch 8/8

2293/2293 - 36s - 16ms/step - ia: 0.9431 - loss: 0.0154 - mae: 0.0896 - rmse: 0.1191 - smape: 0.2060 - val_ia: 0.7600 - val_loss: 0.0059 - val_mae: 0.0596 - val_rmse: 0.0697 - val_smape: 0.1494

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:25 2s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step

 16%|█▌        | 8/50 [2:01:12<9:31:39, 816.66s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 9s - 63ms/step - ia: 0.7316 - loss: 0.2718 - mae: 0.3896 - rmse: 0.5041 - smape: 0.7726 - val_ia: 0.8449 - val_loss: 0.0680 - val_mae: 0.2037 - val_rmse: 0.2583 - val_smape: 0.5198

Epoch 2/128

144/144 - 1s - 7ms/step - ia: 0.8355 - loss: 0.1206 - mae: 0.2621 - rmse: 0.3458 - smape: 0.5395 - val_ia: 0.8913 - val_loss: 0.0352 - val_mae: 0.1417 - val_rmse: 0.1869 - val_smape: 0.3770

Epoch 3/128

144/144 - 1s - 7ms/step - ia: 0.8602 - loss: 0.0906 - mae: 0.2241 - rmse: 0.3006 - smape: 0.4642 - val_ia: 0.9062 - val_loss: 0.0254 - val_mae: 0.1219 - val_rmse: 0.1580 - val_smape: 0.3298

Epoch 4/128

144/144 - 1s - 7ms/step - ia: 0.8713 - loss: 0.0784 - mae: 0.2069 - rmse: 0.2795 - smape: 0.4275 - val_ia: 0.9150 - val_loss: 0.0206 - val_mae: 0.1106 - val_rmse: 0.1423 - val_smape: 0.3010

Epoch 5/128

144/144 - 1s - 6ms/step - ia: 0.8777 - loss: 0.0718 - mae: 0.1970 - rmse: 0.2671 - smape: 0.4074 - val_ia: 0.9209 - val_loss: 0.0177 - val_mae: 0.1034 - val_rmse: 0.1317 - val_smape: 0.2789

Epoch 6/128

144/144 - 1s - 7ms/step - ia: 0.8818 - loss: 0.0686 - mae: 0.1902 - rmse: 0.2613 - smape: 0.3877 - val_ia: 0.9314 - val_loss: 0.0140 - val_mae: 0.0901 - val_rmse: 0.1176 - val_smape: 0.2434

Epoch 7/128

144/144 - 1s - 7ms/step - ia: 0.8856 - loss: 0.0653 - mae: 0.1841 - rmse: 0.2550 - smape: 0.3750 - val_ia: 0.9322 - val_loss: 0.0138 - val_mae: 0.0892 - val_rmse: 0.1166 - val_smape: 0.2274

Epoch 8/128

144/144 - 1s - 8ms/step - ia: 0.8883 - loss: 0.0630 - mae: 0.1798 - rmse: 0.2506 - smape: 0.3607 - val_ia: 0.9378 - val_loss: 0.0111 - val_mae: 0.0822 - val_rmse: 0.1043 - val_smape: 0.2311

Epoch 9/128

144/144 - 1s - 7ms/step - ia: 0.8893 - loss: 0.0627 - mae: 0.1779 - rmse: 0.2501 - smape: 0.3508 - val_ia: 0.9392 - val_loss: 0.0105 - val_mae: 0.0800 - val_rmse: 0.1014 - val_smape: 0.2224

Epoch 10/128

144/144 - 1s - 7ms/step - ia: 0.8922 - loss: 0.0603 - mae: 0.1737 - rmse: 0.2449 - smape: 0.3412 - val_ia: 0.9375 - val_loss: 0.0114 - val_mae: 0.0828 - val_rmse: 0.1060 - val_smape: 0.2051

Epoch 11/128

144/144 - 1s - 9ms/step - ia: 0.8931 - loss: 0.0601 - mae: 0.1722 - rmse: 0.2445 - smape: 0.3351 - val_ia: 0.9384 - val_loss: 0.0112 - val_mae: 0.0817 - val_rmse: 0.1050 - val_smape: 0.2031

Epoch 12/128

144/144 - 1s - 8ms/step - ia: 0.8943 - loss: 0.0589 - mae: 0.1701 - rmse: 0.2419 - smape: 0.3275 - val_ia: 0.9429 - val_loss: 0.0095 - val_mae: 0.0754 - val_rmse: 0.0967 - val_smape: 0.1943

Epoch 13/128

144/144 - 1s - 8ms/step - ia: 0.8945 - loss: 0.0588 - mae: 0.1698 - rmse: 0.2419 - smape: 0.3245 - val_ia: 0.9530 - val_loss: 0.0070 - val_mae: 0.0620 - val_rmse: 0.0833 - val_smape: 0.1759

Epoch 14/128

144/144 - 1s - 7ms/step - ia: 0.8956 - loss: 0.0580 - mae: 0.1682 - rmse: 0.2402 - smape: 0.3197 - val_ia: 0.9462 - val_loss: 0.0085 - val_mae: 0.0712 - val_rmse: 0.0914 - val_smape: 0.1933

Epoch 15/128

144/144 - 1s - 7ms/step - ia: 0.8967 - loss: 0.0571 - mae: 0.1664 - rmse: 0.2381 - smape: 0.3115 - val_ia: 0.9527 - val_loss: 0.0069 - val_mae: 0.0622 - val_rmse: 0.0826 - val_smape: 0.1766

Epoch 16/128

144/144 - 1s - 7ms/step - ia: 0.8959 - loss: 0.0585 - mae: 0.1676 - rmse: 0.2411 - smape: 0.3122 - val_ia: 0.9508 - val_loss: 0.0077 - val_mae: 0.0653 - val_rmse: 0.0872 - val_smape: 0.1663

Epoch 17/128

144/144 - 1s - 7ms/step - ia: 0.8968 - loss: 0.0577 - mae: 0.1663 - rmse: 0.2393 - smape: 0.3109 - val_ia: 0.9555 - val_loss: 0.0063 - val_mae: 0.0587 - val_rmse: 0.0792 - val_smape: 0.1620

Epoch 18/128

144/144 - 1s - 7ms/step - ia: 0.8972 - loss: 0.0578 - mae: 0.1657 - rmse: 0.2395 - smape: 0.3068 - val_ia: 0.9468 - val_loss: 0.0084 - val_mae: 0.0706 - val_rmse: 0.0908 - val_smape: 0.1770

Epoch 19/128

144/144 - 1s - 7ms/step - ia: 0.8980 - loss: 0.0564 - mae: 0.1643 - rmse: 0.2370 - smape: 0.3050 - val_ia: 0.9513 - val_loss: 0.0074 - val_mae: 0.0648 - val_rmse: 0.0858 - val_smape: 0.1642

Epoch 20/128

144/144 - 1s - 8ms/step - ia: 0.8976 - loss: 0.0577 - mae: 0.1650 - rmse: 0.2393 - smape: 0.3042 - val_ia: 0.9494 - val_loss: 0.0076 - val_mae: 0.0673 - val_rmse: 0.0865 - val_smape: 0.1767

Epoch 21/128

144/144 - 1s - 7ms/step - ia: 0.8988 - loss: 0.0563 - mae: 0.1632 - rmse: 0.2364 - smape: 0.3002 - val_ia: 0.9551 - val_loss: 0.0064 - val_mae: 0.0599 - val_rmse: 0.0799 - val_smape: 0.1588

Epoch 22/128

144/144 - 1s - 9ms/step - ia: 0.8990 - loss: 0.0560 - mae: 0.1626 - rmse: 0.2361 - smape: 0.2986 - val_ia: 0.9500 - val_loss: 0.0077 - val_mae: 0.0667 - val_rmse: 0.0868 - val_smape: 0.1632

Epoch 23/128

144/144 - 1s - 6ms/step - ia: 0.8989 - loss: 0.0559 - mae: 0.1629 - rmse: 0.2355 - smape: 0.2995 - val_ia: 0.9502 - val_loss: 0.0076 - val_mae: 0.0665 - val_rmse: 0.0869 - val_smape: 0.1598

Epoch 24/128

144/144 - 1s - 7ms/step - ia: 0.8987 - loss: 0.0569 - mae: 0.1632 - rmse: 0.2378 - smape: 0.2958 - val_ia: 0.9560 - val_loss: 0.0062 - val_mae: 0.0586 - val_rmse: 0.0776 - val_smape: 0.1565

Epoch 25/128

144/144 - 1s - 7ms/step - ia: 0.8991 - loss: 0.0561 - mae: 0.1626 - rmse: 0.2362 - smape: 0.2964 - val_ia: 0.9563 - val_loss: 0.0061 - val_mae: 0.0582 - val_rmse: 0.0768 - val_smape: 0.1552

Epoch 26/128

144/144 - 1s - 7ms/step - ia: 0.8984 - loss: 0.0570 - mae: 0.1634 - rmse: 0.2383 - smape: 0.2937 - val_ia: 0.9538 - val_loss: 0.0068 - val_mae: 0.0618 - val_rmse: 0.0816 - val_smape: 0.1530

Epoch 27/128

144/144 - 1s - 8ms/step - ia: 0.8996 - loss: 0.0558 - mae: 0.1620 - rmse: 0.2353 - smape: 0.2940 - val_ia: 0.9480 - val_loss: 0.0081 - val_mae: 0.0694 - val_rmse: 0.0891 - val_smape: 0.1624

Epoch 28/128

144/144 - 1s - 6ms/step - ia: 0.8996 - loss: 0.0558 - mae: 0.1617 - rmse: 0.2356 - smape: 0.2915 - val_ia: 0.9526 - val_loss: 0.0069 - val_mae: 0.0634 - val_rmse: 0.0817 - val_smape: 0.1565

Epoch 29/128

144/144 - 1s - 7ms/step - ia: 0.9002 - loss: 0.0547 - mae: 0.1609 - rmse: 0.2333 - smape: 0.2910 - val_ia: 0.9482 - val_loss: 0.0080 - val_mae: 0.0693 - val_rmse: 0.0886 - val_smape: 0.1603

Epoch 30/128

144/144 - 1s - 8ms/step - ia: 0.8994 - loss: 0.0566 - mae: 0.1620 - rmse: 0.2372 - smape: 0.2923 - val_ia: 0.9475 - val_loss: 0.0081 - val_mae: 0.0703 - val_rmse: 0.0884 - val_smape: 0.1729

Epoch 31/128

144/144 - 1s - 8ms/step - ia: 0.8997 - loss: 0.0557 - mae: 0.1613 - rmse: 0.2355 - smape: 0.2912 - val_ia: 0.9568 - val_loss: 0.0059 - val_mae: 0.0579 - val_rmse: 0.0761 - val_smape: 0.1475

Epoch 32/128

144/144 - 1s - 7ms/step - ia: 0.9005 - loss: 0.0547 - mae: 0.1604 - rmse: 0.2331 - smape: 0.2896 - val_ia: 0.9534 - val_loss: 0.0066 - val_mae: 0.0623 - val_rmse: 0.0792 - val_smape: 0.1633

Epoch 33/128

144/144 - 1s - 6ms/step - ia: 0.9004 - loss: 0.0555 - mae: 0.1605 - rmse: 0.2350 - smape: 0.2878 - val_ia: 0.9519 - val_loss: 0.0071 - val_mae: 0.0645 - val_rmse: 0.0831 - val_smape: 0.1528

Epoch 34/128

144/144 - 1s - 7ms/step - ia: 0.8998 - loss: 0.0559 - mae: 0.1612 - rmse: 0.2361 - smape: 0.2878 - val_ia: 0.9599 - val_loss: 0.0052 - val_mae: 0.0538 - val_rmse: 0.0715 - val_smape: 0.1408

Epoch 35/128

144/144 - 1s - 8ms/step - ia: 0.9010 - loss: 0.0547 - mae: 0.1597 - rmse: 0.2330 - smape: 0.2846 - val_ia: 0.9505 - val_loss: 0.0074 - val_mae: 0.0662 - val_rmse: 0.0847 - val_smape: 0.1493

Epoch 36/128

144/144 - 1s - 7ms/step - ia: 0.9012 - loss: 0.0546 - mae: 0.1591 - rmse: 0.2329 - smape: 0.2835 - val_ia: 0.9584 - val_loss: 0.0055 - val_mae: 0.0557 - val_rmse: 0.0729 - val_smape: 0.1429

Epoch 37/128

144/144 - 1s - 9ms/step - ia: 0.9002 - loss: 0.0558 - mae: 0.1610 - rmse: 0.2350 - smape: 0.2880 - val_ia: 0.9555 - val_loss: 0.0062 - val_mae: 0.0597 - val_rmse: 0.0780 - val_smape: 0.1396

Epoch 38/128

144/144 - 1s - 7ms/step - ia: 0.9008 - loss: 0.0546 - mae: 0.1599 - rmse: 0.2330 - smape: 0.2862 - val_ia: 0.9536 - val_loss: 0.0066 - val_mae: 0.0623 - val_rmse: 0.0805 - val_smape: 0.1431

Epoch 39/128

144/144 - 1s - 7ms/step - ia: 0.9015 - loss: 0.0548 - mae: 0.1588 - rmse: 0.2337 - smape: 0.2833 - val_ia: 0.9532 - val_loss: 0.0066 - val_mae: 0.0628 - val_rmse: 0.0808 - val_smape: 0.1452

Epoch 40/128

144/144 - 1s - 7ms/step - ia: 0.8998 - loss: 0.0563 - mae: 0.1615 - rmse: 0.2367 - smape: 0.2858 - val_ia: 0.9567 - val_loss: 0.0059 - val_mae: 0.0583 - val_rmse: 0.0754 - val_smape: 0.1445

Epoch 41/128

144/144 - 1s - 6ms/step - ia: 0.9004 - loss: 0.0559 - mae: 0.1604 - rmse: 0.2357 - smape: 0.2852 - val_ia: 0.9586 - val_loss: 0.0055 - val_mae: 0.0558 - val_rmse: 0.0730 - val_smape: 0.1401

Epoch 42/128

144/144 - 1s - 7ms/step - ia: 0.9007 - loss: 0.0550 - mae: 0.1600 - rmse: 0.2339 - smape: 0.2840 - val_ia: 0.9539 - val_loss: 0.0065 - val_mae: 0.0621 - val_rmse: 0.0792 - val_smape: 0.1484

Epoch 43/128

144/144 - 1s - 9ms/step - ia: 0.9008 - loss: 0.0550 - mae: 0.1598 - rmse: 0.2343 - smape: 0.2837 - val_ia: 0.9601 - val_loss: 0.0052 - val_mae: 0.0538 - val_rmse: 0.0711 - val_smape: 0.1340

Epoch 44/128

144/144 - 1s - 7ms/step - ia: 0.9011 - loss: 0.0555 - mae: 0.1595 - rmse: 0.2344 - smape: 0.2838 - val_ia: 0.9642 - val_loss: 0.0043 - val_mae: 0.0481 - val_rmse: 0.0643 - val_smape: 0.1312

Epoch 45/128

144/144 - 1s - 8ms/step - ia: 0.9010 - loss: 0.0547 - mae: 0.1597 - rmse: 0.2333 - smape: 0.2828 - val_ia: 0.9487 - val_loss: 0.0078 - val_mae: 0.0690 - val_rmse: 0.0870 - val_smape: 0.1559

Epoch 46/128

144/144 - 1s - 10ms/step - ia: 0.9005 - loss: 0.0559 - mae: 0.1604 - rmse: 0.2358 - smape: 0.2822 - val_ia: 0.9604 - val_loss: 0.0050 - val_mae: 0.0534 - val_rmse: 0.0697 - val_smape: 0.1381

Epoch 47/128

144/144 - 1s - 9ms/step - ia: 0.9013 - loss: 0.0546 - mae: 0.1590 - rmse: 0.2329 - smape: 0.2817 - val_ia: 0.9497 - val_loss: 0.0075 - val_mae: 0.0672 - val_rmse: 0.0858 - val_smape: 0.1491

Epoch 48/128

144/144 - 1s - 8ms/step - ia: 0.9007 - loss: 0.0551 - mae: 0.1599 - rmse: 0.2341 - smape: 0.2829 - val_ia: 0.9539 - val_loss: 0.0065 - val_mae: 0.0622 - val_rmse: 0.0795 - val_smape: 0.1486

Epoch 49/128

144/144 - 1s - 8ms/step - ia: 0.9010 - loss: 0.0546 - mae: 0.1596 - rmse: 0.2329 - smape: 0.2823 - val_ia: 0.9595 - val_loss: 0.0052 - val_mae: 0.0547 - val_rmse: 0.0713 - val_smape: 0.1388

Epoch 50/128

144/144 - 1s - 8ms/step - ia: 0.9014 - loss: 0.0551 - mae: 0.1591 - rmse: 0.2337 - smape: 0.2829 - val_ia: 0.9542 - val_loss: 0.0064 - val_mae: 0.0618 - val_rmse: 0.0791 - val_smape: 0.1454

Epoch 51/128

144/144 - 1s - 8ms/step - ia: 0.9019 - loss: 0.0542 - mae: 0.1583 - rmse: 0.2320 - smape: 0.2811 - val_ia: 0.9544 - val_loss: 0.0064 - val_mae: 0.0615 - val_rmse: 0.0791 - val_smape: 0.1443

Epoch 52/128

144/144 - 1s - 7ms/step - ia: 0.9025 - loss: 0.0536 - mae: 0.1572 - rmse: 0.2306 - smape: 0.2789 - val_ia: 0.9624 - val_loss: 0.0046 - val_mae: 0.0507 - val_rmse: 0.0669 - val_smape: 0.1343

Epoch 53/128

144/144 - 1s - 7ms/step - ia: 0.9007 - loss: 0.0557 - mae: 0.1597 - rmse: 0.2356 - smape: 0.2829 - val_ia: 0.9563 - val_loss: 0.0059 - val_mae: 0.0590 - val_rmse: 0.0752 - val_smape: 0.1454

Epoch 54/128

144/144 - 1s - 7ms/step - ia: 0.9013 - loss: 0.0546 - mae: 0.1591 - rmse: 0.2331 - smape: 0.2813 - val_ia: 0.9545 - val_loss: 0.0063 - val_mae: 0.0609 - val_rmse: 0.0785 - val_smape: 0.1426

Epoch 55/128

144/144 - 1s - 7ms/step - ia: 0.9017 - loss: 0.0552 - mae: 0.1585 - rmse: 0.2343 - smape: 0.2811 - val_ia: 0.9512 - val_loss: 0.0072 - val_mae: 0.0657 - val_rmse: 0.0835 - val_smape: 0.1477

Epoch 56/128

144/144 - 1s - 6ms/step - ia: 0.9012 - loss: 0.0548 - mae: 0.1592 - rmse: 0.2332 - smape: 0.2810 - val_ia: 0.9586 - val_loss: 0.0054 - val_mae: 0.0560 - val_rmse: 0.0725 - val_smape: 0.1411

Epoch 57/128

144/144 - 1s - 6ms/step - ia: 0.9012 - loss: 0.0548 - mae: 0.1594 - rmse: 0.2335 - smape: 0.2791 - val_ia: 0.9606 - val_loss: 0.0050 - val_mae: 0.0534 - val_rmse: 0.0700 - val_smape: 0.1360

Epoch 58/128

144/144 - 1s - 7ms/step - ia: 0.9013 - loss: 0.0549 - mae: 0.1592 - rmse: 0.2337 - smape: 0.2804 - val_ia: 0.9532 - val_loss: 0.0067 - val_mae: 0.0633 - val_rmse: 0.0808 - val_smape: 0.1462

Epoch 59/128

144/144 - 1s - 7ms/step - ia: 0.9016 - loss: 0.0541 - mae: 0.1587 - rmse: 0.2317 - smape: 0.2808 - val_ia: 0.9583 - val_loss: 0.0055 - val_mae: 0.0564 - val_rmse: 0.0733 - val_smape: 0.1380

Epoch 59: early stopping

Restoring model weights from the end of the best epoch: 44.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:11 443ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 18%|█▊        | 9/50 [2:02:25<6:39:08, 584.10s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

1147/1147 - 32s - 28ms/step - ia: 0.8314 - loss: 0.1205 - mae: 0.2418 - rmse: 0.3082 - smape: 0.5208 - val_ia: 0.7571 - val_loss: 0.0264 - val_mae: 0.1170 - val_rmse: 0.1493 - val_smape: 0.3099

Epoch 2/16

1147/1147 - 20s - 17ms/step - ia: 0.9073 - loss: 0.0391 - mae: 0.1485 - rmse: 0.1945 - smape: 0.3439 - val_ia: 0.7791 - val_loss: 0.0183 - val_mae: 0.1021 - val_rmse: 0.1277 - val_smape: 0.2726

Epoch 3/16

1147/1147 - 19s - 16ms/step - ia: 0.9186 - loss: 0.0308 - mae: 0.1303 - rmse: 0.1726 - smape: 0.3037 - val_ia: 0.7488 - val_loss: 0.0215 - val_mae: 0.1177 - val_rmse: 0.1384 - val_smape: 0.2803

Epoch 4/16

1147/1147 - 19s - 16ms/step - ia: 0.9245 - loss: 0.0271 - mae: 0.1213 - rmse: 0.1616 - smape: 0.2801 - val_ia: 0.7325 - val_loss: 0.0256 - val_mae: 0.1284 - val_rmse: 0.1478 - val_smape: 0.2969

Epoch 5/16

1147/1147 - 19s - 17ms/step - ia: 0.9281 - loss: 0.0246 - mae: 0.1155 - rmse: 0.1542 - smape: 0.2664 - val_ia: 0.7158 - val_loss: 0.0281 - val_mae: 0.1388 - val_rmse: 0.1564 - val_smape: 0.3045

Epoch 6/16

1147/1147 - 20s - 18ms/step - ia: 0.9313 - loss: 0.0227 - mae: 0.1105 - rmse: 0.1478 - smape: 0.2569 - val_ia: 0.7192 - val_loss: 0.0273 - val_mae: 0.1364 - val_rmse: 0.1530 - val_smape: 0.3190

Epoch 7/16

1147/1147 - 20s - 17ms/step - ia: 0.9335 - loss: 0.0215 - mae: 0.1072 - rmse: 0.1438 - smape: 0.2489 - val_ia: 0.7332 - val_loss: 0.0226 - val_mae: 0.1275 - val_rmse: 0.1430 - val_smape: 0.2972

Epoch 8/16

1147/1147 - 20s - 18ms/step - ia: 0.9343 - loss: 0.0210 - mae: 0.1056 - rmse: 0.1421 - smape: 0.2435 - val_ia: 0.7047 - val_loss: 0.0314 - val_mae: 0.1470 - val_rmse: 0.1634 - val_smape: 0.3360

Epoch 9/16

1147/1147 - 20s - 18ms/step - ia: 0.9354 - loss: 0.0204 - mae: 0.1037 - rmse: 0.1398 - smape: 0.2390 - val_ia: 0.7340 - val_loss: 0.0226 - val_mae: 0.1265 - val_rmse: 0.1418 - val_smape: 0.2970

Epoch 10/16

1147/1147 - 20s - 18ms/step - ia: 0.9363 - loss: 0.0199 - mae: 0.1026 - rmse: 0.1382 - smape: 0.2370 - val_ia: 0.7446 - val_loss: 0.0210 - val_mae: 0.1206 - val_rmse: 0.1364 - val_smape: 0.2881

Epoch 11/16

1147/1147 - 20s - 18ms/step - ia: 0.9372 - loss: 0.0196 - mae: 0.1012 - rmse: 0.1371 - smape: 0.2318 - val_ia: 0.7303 - val_loss: 0.0244 - val_mae: 0.1296 - val_rmse: 0.1453 - val_smape: 0.3067

Epoch 12/16

1147/1147 - 20s - 18ms/step - ia: 0.9381 - loss: 0.0190 - mae: 0.0997 - rmse: 0.1350 - smape: 0.2284 - val_ia: 0.7462 - val_loss: 0.0211 - val_mae: 0.1196 - val_rmse: 0.1346 - val_smape: 0.2811

Epoch 13/16

1147/1147 - 20s - 18ms/step - ia: 0.9381 - loss: 0.0191 - mae: 0.0996 - rmse: 0.1353 - smape: 0.2271 - val_ia: 0.7734 - val_loss: 0.0159 - val_mae: 0.1029 - val_rmse: 0.1180 - val_smape: 0.2588

Epoch 14/16

1147/1147 - 20s - 17ms/step - ia: 0.9386 - loss: 0.0187 - mae: 0.0987 - rmse: 0.1338 - smape: 0.2265 - val_ia: 0.7405 - val_loss: 0.0203 - val_mae: 0.1225 - val_rmse: 0.1361 - val_smape: 0.2848

Epoch 15/16

1147/1147 - 21s - 18ms/step - ia: 0.9395 - loss: 0.0184 - mae: 0.0977 - rmse: 0.1325 - smape: 0.2245 - val_ia: 0.7726 - val_loss: 0.0157 - val_mae: 0.1029 - val_rmse: 0.1185 - val_smape: 0.2530

Epoch 16/16

1147/1147 - 20s - 18ms/step - ia: 0.9392 - loss: 0.0184 - mae: 0.0980 - rmse: 0.1329 - smape: 0.2225 - val_ia: 0.7802 - val_loss: 0.0151 - val_mae: 0.0976 - val_rmse: 0.1132 - val_smape: 0.2442

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:21 1s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 20%|██        | 10/50 [2:08:01<5:38:21, 507.53s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 28s - 96ms/step - ia: 0.3804 - loss: 2.1389 - mae: 1.0251 - rmse: 1.4554 - smape: 1.3259 - val_ia: 0.4462 - val_loss: 0.5612 - val_mae: 0.6150 - val_rmse: 0.7398 - val_smape: 1.1558

Epoch 2/8

287/287 - 4s - 14ms/step - ia: 0.3855 - loss: 2.0747 - mae: 1.0163 - rmse: 1.4339 - smape: 1.3204 - val_ia: 0.4522 - val_loss: 0.5531 - val_mae: 0.6100 - val_rmse: 0.7343 - val_smape: 1.1467

Epoch 3/8

287/287 - 4s - 13ms/step - ia: 0.3946 - loss: 2.0272 - mae: 1.0039 - rmse: 1.4165 - smape: 1.3088 - val_ia: 0.4579 - val_loss: 0.5455 - val_mae: 0.6054 - val_rmse: 0.7292 - val_smape: 1.1383

Epoch 4/8

287/287 - 3s - 12ms/step - ia: 0.3937 - loss: 2.0194 - mae: 1.0029 - rmse: 1.4132 - smape: 1.3113 - val_ia: 0.4636 - val_loss: 0.5379 - val_mae: 0.6006 - val_rmse: 0.7240 - val_smape: 1.1300

Epoch 5/8

287/287 - 3s - 11ms/step - ia: 0.3936 - loss: 1.9578 - mae: 0.9950 - rmse: 1.3923 - smape: 1.3147 - val_ia: 0.4692 - val_loss: 0.5305 - val_mae: 0.5960 - val_rmse: 0.7189 - val_smape: 1.1220

Epoch 6/8

287/287 - 3s - 11ms/step - ia: 0.3985 - loss: 1.9810 - mae: 0.9934 - rmse: 1.3997 - smape: 1.3064 - val_ia: 0.4746 - val_loss: 0.5234 - val_mae: 0.5916 - val_rmse: 0.7140 - val_smape: 1.1145

Epoch 7/8

287/287 - 3s - 11ms/step - ia: 0.3999 - loss: 1.9510 - mae: 0.9854 - rmse: 1.3889 - smape: 1.2989 - val_ia: 0.4802 - val_loss: 0.5163 - val_mae: 0.5871 - val_rmse: 0.7091 - val_smape: 1.1069

Epoch 8/8

287/287 - 3s - 11ms/step - ia: 0.4025 - loss: 1.9659 - mae: 0.9886 - rmse: 1.3940 - smape: 1.2982 - val_ia: 0.4853 - val_loss: 0.5098 - val_mae: 0.5829 - val_rmse: 0.7045 - val_smape: 1.1001

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:48 672ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 22%|██▏       | 11/50 [2:08:55<3:59:40, 368.73s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 18s - 16ms/step - ia: 0.7730 - loss: 0.2047 - mae: 0.3379 - rmse: 0.4216 - smape: 0.6908 - val_ia: 0.6340 - val_loss: 0.0735 - val_mae: 0.2195 - val_rmse: 0.2457 - val_smape: 0.5468

Epoch 2/128

1147/1147 - 11s - 10ms/step - ia: 0.8854 - loss: 0.0561 - mae: 0.1837 - rmse: 0.2327 - smape: 0.4386 - val_ia: 0.7473 - val_loss: 0.0286 - val_mae: 0.1326 - val_rmse: 0.1524 - val_smape: 0.3707

Epoch 3/128

1147/1147 - 11s - 9ms/step - ia: 0.9134 - loss: 0.0325 - mae: 0.1393 - rmse: 0.1775 - smape: 0.3523 - val_ia: 0.7791 - val_loss: 0.0180 - val_mae: 0.1041 - val_rmse: 0.1235 - val_smape: 0.2948

Epoch 4/128

1147/1147 - 11s - 10ms/step - ia: 0.9257 - loss: 0.0244 - mae: 0.1192 - rmse: 0.1537 - smape: 0.3090 - val_ia: 0.8288 - val_loss: 0.0111 - val_mae: 0.0764 - val_rmse: 0.0970 - val_smape: 0.2184

Epoch 5/128

1147/1147 - 11s - 10ms/step - ia: 0.9335 - loss: 0.0201 - mae: 0.1069 - rmse: 0.1394 - smape: 0.2766 - val_ia: 0.8030 - val_loss: 0.0130 - val_mae: 0.0884 - val_rmse: 0.1065 - val_smape: 0.2616

Epoch 6/128

1147/1147 - 11s - 9ms/step - ia: 0.9389 - loss: 0.0172 - mae: 0.0981 - rmse: 0.1285 - smape: 0.2579 - val_ia: 0.8523 - val_loss: 0.0080 - val_mae: 0.0638 - val_rmse: 0.0825 - val_smape: 0.1855

Epoch 7/128

1147/1147 - 11s - 10ms/step - ia: 0.9422 - loss: 0.0155 - mae: 0.0930 - rmse: 0.1220 - smape: 0.2446 - val_ia: 0.8277 - val_loss: 0.0095 - val_mae: 0.0752 - val_rmse: 0.0915 - val_smape: 0.2313

Epoch 8/128

1147/1147 - 11s - 9ms/step - ia: 0.9447 - loss: 0.0144 - mae: 0.0890 - rmse: 0.1173 - smape: 0.2368 - val_ia: 0.8617 - val_loss: 0.0066 - val_mae: 0.0591 - val_rmse: 0.0759 - val_smape: 0.1751

Epoch 9/128

1147/1147 - 10s - 9ms/step - ia: 0.9466 - loss: 0.0134 - mae: 0.0859 - rmse: 0.1135 - smape: 0.2288 - val_ia: 0.8551 - val_loss: 0.0068 - val_mae: 0.0618 - val_rmse: 0.0775 - val_smape: 0.1879

Epoch 10/128

1147/1147 - 10s - 9ms/step - ia: 0.9488 - loss: 0.0124 - mae: 0.0826 - rmse: 0.1089 - smape: 0.2215 - val_ia: 0.8539 - val_loss: 0.0070 - val_mae: 0.0607 - val_rmse: 0.0774 - val_smape: 0.1561

Epoch 11/128

1147/1147 - 11s - 10ms/step - ia: 0.9499 - loss: 0.0120 - mae: 0.0808 - rmse: 0.1068 - smape: 0.2170 - val_ia: 0.8683 - val_loss: 0.0056 - val_mae: 0.0552 - val_rmse: 0.0700 - val_smape: 0.1597

Epoch 12/128

1147/1147 - 10s - 9ms/step - ia: 0.9512 - loss: 0.0114 - mae: 0.0787 - rmse: 0.1041 - smape: 0.2113 - val_ia: 0.8530 - val_loss: 0.0066 - val_mae: 0.0597 - val_rmse: 0.0745 - val_smape: 0.1590

Epoch 13/128

1147/1147 - 10s - 9ms/step - ia: 0.9516 - loss: 0.0112 - mae: 0.0780 - rmse: 0.1031 - smape: 0.2092 - val_ia: 0.8631 - val_loss: 0.0058 - val_mae: 0.0570 - val_rmse: 0.0710 - val_smape: 0.1604

Epoch 14/128

1147/1147 - 12s - 11ms/step - ia: 0.9525 - loss: 0.0108 - mae: 0.0764 - rmse: 0.1013 - smape: 0.2052 - val_ia: 0.8772 - val_loss: 0.0048 - val_mae: 0.0510 - val_rmse: 0.0655 - val_smape: 0.1480

Epoch 15/128

1147/1147 - 11s - 9ms/step - ia: 0.9531 - loss: 0.0106 - mae: 0.0757 - rmse: 0.1004 - smape: 0.2043 - val_ia: 0.8786 - val_loss: 0.0047 - val_mae: 0.0503 - val_rmse: 0.0644 - val_smape: 0.1429

Epoch 16/128

1147/1147 - 11s - 10ms/step - ia: 0.9536 - loss: 0.0104 - mae: 0.0748 - rmse: 0.0992 - smape: 0.2010 - val_ia: 0.8821 - val_loss: 0.0044 - val_mae: 0.0483 - val_rmse: 0.0619 - val_smape: 0.1403

Epoch 17/128

1147/1147 - 11s - 10ms/step - ia: 0.9542 - loss: 0.0102 - mae: 0.0738 - rmse: 0.0983 - smape: 0.1986 - val_ia: 0.8877 - val_loss: 0.0041 - val_mae: 0.0466 - val_rmse: 0.0597 - val_smape: 0.1380

Epoch 18/128

1147/1147 - 13s - 11ms/step - ia: 0.9549 - loss: 0.0099 - mae: 0.0727 - rmse: 0.0967 - smape: 0.1967 - val_ia: 0.8795 - val_loss: 0.0044 - val_mae: 0.0492 - val_rmse: 0.0618 - val_smape: 0.1458

Epoch 19/128

1147/1147 - 10s - 9ms/step - ia: 0.9553 - loss: 0.0097 - mae: 0.0720 - rmse: 0.0957 - smape: 0.1946 - val_ia: 0.8747 - val_loss: 0.0047 - val_mae: 0.0510 - val_rmse: 0.0639 - val_smape: 0.1489

Epoch 20/128

1147/1147 - 10s - 9ms/step - ia: 0.9558 - loss: 0.0095 - mae: 0.0714 - rmse: 0.0949 - smape: 0.1942 - val_ia: 0.8767 - val_loss: 0.0046 - val_mae: 0.0507 - val_rmse: 0.0628 - val_smape: 0.1575

Epoch 21/128

1147/1147 - 12s - 10ms/step - ia: 0.9558 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0949 - smape: 0.1937 - val_ia: 0.8941 - val_loss: 0.0037 - val_mae: 0.0448 - val_rmse: 0.0571 - val_smape: 0.1416

Epoch 22/128

1147/1147 - 9s - 8ms/step - ia: 0.9560 - loss: 0.0095 - mae: 0.0710 - rmse: 0.0944 - smape: 0.1929 - val_ia: 0.8710 - val_loss: 0.0048 - val_mae: 0.0522 - val_rmse: 0.0641 - val_smape: 0.1572

Epoch 23/128

1147/1147 - 9s - 8ms/step - ia: 0.9559 - loss: 0.0095 - mae: 0.0712 - rmse: 0.0949 - smape: 0.1926 - val_ia: 0.8668 - val_loss: 0.0051 - val_mae: 0.0539 - val_rmse: 0.0657 - val_smape: 0.1614

Epoch 24/128

1147/1147 - 10s - 8ms/step - ia: 0.9568 - loss: 0.0091 - mae: 0.0697 - rmse: 0.0926 - smape: 0.1922 - val_ia: 0.8716 - val_loss: 0.0047 - val_mae: 0.0517 - val_rmse: 0.0638 - val_smape: 0.1476

Epoch 25/128

1147/1147 - 11s - 9ms/step - ia: 0.9568 - loss: 0.0092 - mae: 0.0697 - rmse: 0.0931 - smape: 0.1893 - val_ia: 0.8846 - val_loss: 0.0042 - val_mae: 0.0485 - val_rmse: 0.0602 - val_smape: 0.1455

Epoch 26/128

1147/1147 - 10s - 9ms/step - ia: 0.9566 - loss: 0.0092 - mae: 0.0699 - rmse: 0.0931 - smape: 0.1880 - val_ia: 0.8845 - val_loss: 0.0040 - val_mae: 0.0469 - val_rmse: 0.0590 - val_smape: 0.1420

Epoch 27/128

1147/1147 - 10s - 9ms/step - ia: 0.9574 - loss: 0.0089 - mae: 0.0687 - rmse: 0.0918 - smape: 0.1867 - val_ia: 0.8757 - val_loss: 0.0045 - val_mae: 0.0503 - val_rmse: 0.0623 - val_smape: 0.1483

Epoch 28/128

1147/1147 - 10s - 9ms/step - ia: 0.9575 - loss: 0.0089 - mae: 0.0687 - rmse: 0.0917 - smape: 0.1857 - val_ia: 0.8979 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0557 - val_smape: 0.1413

Epoch 29/128

1147/1147 - 11s - 9ms/step - ia: 0.9575 - loss: 0.0089 - mae: 0.0685 - rmse: 0.0915 - smape: 0.1868 - val_ia: 0.8806 - val_loss: 0.0042 - val_mae: 0.0488 - val_rmse: 0.0613 - val_smape: 0.1438

Epoch 30/128

1147/1147 - 9s - 8ms/step - ia: 0.9574 - loss: 0.0089 - mae: 0.0687 - rmse: 0.0917 - smape: 0.1872 - val_ia: 0.8896 - val_loss: 0.0037 - val_mae: 0.0452 - val_rmse: 0.0572 - val_smape: 0.1399

Epoch 31/128

1147/1147 - 9s - 8ms/step - ia: 0.9581 - loss: 0.0087 - mae: 0.0677 - rmse: 0.0905 - smape: 0.1838 - val_ia: 0.8938 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0565 - val_smape: 0.1389

Epoch 32/128

1147/1147 - 11s - 10ms/step - ia: 0.9579 - loss: 0.0088 - mae: 0.0681 - rmse: 0.0913 - smape: 0.1854 - val_ia: 0.8935 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0556 - val_smape: 0.1374

Epoch 33/128

1147/1147 - 10s - 8ms/step - ia: 0.9582 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0904 - smape: 0.1814 - val_ia: 0.8911 - val_loss: 0.0037 - val_mae: 0.0451 - val_rmse: 0.0569 - val_smape: 0.1422

Epoch 34/128

1147/1147 - 9s - 8ms/step - ia: 0.9582 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0904 - smape: 0.1827 - val_ia: 0.8904 - val_loss: 0.0037 - val_mae: 0.0450 - val_rmse: 0.0567 - val_smape: 0.1457

Epoch 35/128

1147/1147 - 10s - 9ms/step - ia: 0.9585 - loss: 0.0085 - mae: 0.0670 - rmse: 0.0898 - smape: 0.1812 - val_ia: 0.8837 - val_loss: 0.0039 - val_mae: 0.0473 - val_rmse: 0.0595 - val_smape: 0.1407

Epoch 36/128

1147/1147 - 9s - 8ms/step - ia: 0.9582 - loss: 0.0087 - mae: 0.0676 - rmse: 0.0903 - smape: 0.1826 - val_ia: 0.8946 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0554 - val_smape: 0.1384

Epoch 37/128

1147/1147 - 9s - 8ms/step - ia: 0.9584 - loss: 0.0086 - mae: 0.0672 - rmse: 0.0900 - smape: 0.1812 - val_ia: 0.8972 - val_loss: 0.0034 - val_mae: 0.0428 - val_rmse: 0.0545 - val_smape: 0.1386

Epoch 38/128

1147/1147 - 9s - 8ms/step - ia: 0.9587 - loss: 0.0084 - mae: 0.0665 - rmse: 0.0890 - smape: 0.1825 - val_ia: 0.8927 - val_loss: 0.0035 - val_mae: 0.0440 - val_rmse: 0.0559 - val_smape: 0.1383

Epoch 39/128

1147/1147 - 10s - 9ms/step - ia: 0.9587 - loss: 0.0085 - mae: 0.0667 - rmse: 0.0893 - smape: 0.1818 - val_ia: 0.8942 - val_loss: 0.0034 - val_mae: 0.0432 - val_rmse: 0.0550 - val_smape: 0.1374

Epoch 40/128

1147/1147 - 9s - 8ms/step - ia: 0.9591 - loss: 0.0084 - mae: 0.0660 - rmse: 0.0887 - smape: 0.1800 - val_ia: 0.8623 - val_loss: 0.0051 - val_mae: 0.0552 - val_rmse: 0.0662 - val_smape: 0.1613

Epoch 41/128

1147/1147 - 10s - 9ms/step - ia: 0.9588 - loss: 0.0085 - mae: 0.0666 - rmse: 0.0892 - smape: 0.1805 - val_ia: 0.8925 - val_loss: 0.0035 - val_mae: 0.0443 - val_rmse: 0.0562 - val_smape: 0.1396

Epoch 42/128

1147/1147 - 10s - 9ms/step - ia: 0.9590 - loss: 0.0084 - mae: 0.0662 - rmse: 0.0888 - smape: 0.1812 - val_ia: 0.8719 - val_loss: 0.0045 - val_mae: 0.0515 - val_rmse: 0.0630 - val_smape: 0.1490

Epoch 43/128

1147/1147 - 20s - 17ms/step - ia: 0.9587 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0896 - smape: 0.1807 - val_ia: 0.8932 - val_loss: 0.0036 - val_mae: 0.0444 - val_rmse: 0.0564 - val_smape: 0.1355

Epoch 44/128

1147/1147 - 10s - 9ms/step - ia: 0.9591 - loss: 0.0083 - mae: 0.0661 - rmse: 0.0886 - smape: 0.1770 - val_ia: 0.9061 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0521 - val_smape: 0.1350

Epoch 45/128

1147/1147 - 10s - 9ms/step - ia: 0.9593 - loss: 0.0083 - mae: 0.0658 - rmse: 0.0883 - smape: 0.1781 - val_ia: 0.9085 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0519 - val_smape: 0.1309

Epoch 46/128

1147/1147 - 9s - 8ms/step - ia: 0.9589 - loss: 0.0084 - mae: 0.0663 - rmse: 0.0890 - smape: 0.1796 - val_ia: 0.9047 - val_loss: 0.0031 - val_mae: 0.0403 - val_rmse: 0.0522 - val_smape: 0.1364

Epoch 47/128

1147/1147 - 10s - 8ms/step - ia: 0.9595 - loss: 0.0082 - mae: 0.0655 - rmse: 0.0877 - smape: 0.1782 - val_ia: 0.8906 - val_loss: 0.0036 - val_mae: 0.0452 - val_rmse: 0.0571 - val_smape: 0.1407

Epoch 48/128

1147/1147 - 10s - 9ms/step - ia: 0.9595 - loss: 0.0082 - mae: 0.0656 - rmse: 0.0879 - smape: 0.1773 - val_ia: 0.8953 - val_loss: 0.0035 - val_mae: 0.0442 - val_rmse: 0.0561 - val_smape: 0.1369

Epoch 49/128

1147/1147 - 10s - 9ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0653 - rmse: 0.0878 - smape: 0.1768 - val_ia: 0.9083 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0512 - val_smape: 0.1306

Epoch 50/128

1147/1147 - 10s - 9ms/step - ia: 0.9593 - loss: 0.0082 - mae: 0.0656 - rmse: 0.0881 - smape: 0.1765 - val_ia: 0.8993 - val_loss: 0.0033 - val_mae: 0.0419 - val_rmse: 0.0536 - val_smape: 0.1382

Epoch 51/128

1147/1147 - 10s - 9ms/step - ia: 0.9594 - loss: 0.0083 - mae: 0.0654 - rmse: 0.0881 - smape: 0.1748 - val_ia: 0.9060 - val_loss: 0.0031 - val_mae: 0.0410 - val_rmse: 0.0530 - val_smape: 0.1345

Epoch 52/128

1147/1147 - 9s - 8ms/step - ia: 0.9597 - loss: 0.0081 - mae: 0.0652 - rmse: 0.0874 - smape: 0.1761 - val_ia: 0.9079 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0510 - val_smape: 0.1318

Epoch 53/128

1147/1147 - 11s - 9ms/step - ia: 0.9600 - loss: 0.0081 - mae: 0.0647 - rmse: 0.0870 - smape: 0.1760 - val_ia: 0.8932 - val_loss: 0.0035 - val_mae: 0.0436 - val_rmse: 0.0551 - val_smape: 0.1411

Epoch 54/128

1147/1147 - 10s - 9ms/step - ia: 0.9595 - loss: 0.0082 - mae: 0.0653 - rmse: 0.0878 - smape: 0.1759 - val_ia: 0.8862 - val_loss: 0.0038 - val_mae: 0.0462 - val_rmse: 0.0578 - val_smape: 0.1444

Epoch 55/128

1147/1147 - 10s - 9ms/step - ia: 0.9597 - loss: 0.0081 - mae: 0.0650 - rmse: 0.0872 - smape: 0.1755 - val_ia: 0.8954 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0552 - val_smape: 0.1475

Epoch 56/128

1147/1147 - 10s - 9ms/step - ia: 0.9597 - loss: 0.0081 - mae: 0.0651 - rmse: 0.0875 - smape: 0.1758 - val_ia: 0.9013 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0533 - val_smape: 0.1329

Epoch 57/128

1147/1147 - 10s - 9ms/step - ia: 0.9598 - loss: 0.0081 - mae: 0.0649 - rmse: 0.0871 - smape: 0.1748 - val_ia: 0.9086 - val_loss: 0.0030 - val_mae: 0.0392 - val_rmse: 0.0512 - val_smape: 0.1309

Epoch 58/128

1147/1147 - 10s - 9ms/step - ia: 0.9597 - loss: 0.0082 - mae: 0.0652 - rmse: 0.0879 - smape: 0.1753 - val_ia: 0.9027 - val_loss: 0.0031 - val_mae: 0.0405 - val_rmse: 0.0524 - val_smape: 0.1328

Epoch 59/128

1147/1147 - 10s - 9ms/step - ia: 0.9600 - loss: 0.0080 - mae: 0.0647 - rmse: 0.0869 - smape: 0.1753 - val_ia: 0.8948 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0548 - val_smape: 0.1402

Epoch 60/128

1147/1147 - 10s - 9ms/step - ia: 0.9601 - loss: 0.0080 - mae: 0.0644 - rmse: 0.0869 - smape: 0.1725 - val_ia: 0.8880 - val_loss: 0.0037 - val_mae: 0.0452 - val_rmse: 0.0567 - val_smape: 0.1463

Epoch 61/128

1147/1147 - 10s - 9ms/step - ia: 0.9600 - loss: 0.0080 - mae: 0.0645 - rmse: 0.0867 - smape: 0.1735 - val_ia: 0.9001 - val_loss: 0.0032 - val_mae: 0.0416 - val_rmse: 0.0534 - val_smape: 0.1375

Epoch 62/128

1147/1147 - 11s - 9ms/step - ia: 0.9603 - loss: 0.0079 - mae: 0.0641 - rmse: 0.0861 - smape: 0.1731 - val_ia: 0.9094 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0511 - val_smape: 0.1291

Epoch 63/128

1147/1147 - 10s - 9ms/step - ia: 0.9600 - loss: 0.0080 - mae: 0.0645 - rmse: 0.0869 - smape: 0.1733 - val_ia: 0.8850 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0581 - val_smape: 0.1504

Epoch 64/128

1147/1147 - 10s - 9ms/step - ia: 0.9601 - loss: 0.0079 - mae: 0.0643 - rmse: 0.0863 - smape: 0.1738 - val_ia: 0.8987 - val_loss: 0.0033 - val_mae: 0.0424 - val_rmse: 0.0544 - val_smape: 0.1334

Epoch 65/128

1147/1147 - 11s - 9ms/step - ia: 0.9603 - loss: 0.0079 - mae: 0.0643 - rmse: 0.0863 - smape: 0.1728 - val_ia: 0.8930 - val_loss: 0.0036 - val_mae: 0.0442 - val_rmse: 0.0558 - val_smape: 0.1460

Epoch 66/128

1147/1147 - 10s - 8ms/step - ia: 0.9605 - loss: 0.0078 - mae: 0.0639 - rmse: 0.0858 - smape: 0.1727 - val_ia: 0.9085 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0510 - val_smape: 0.1317

Epoch 67/128

1147/1147 - 9s - 8ms/step - ia: 0.9604 - loss: 0.0079 - mae: 0.0639 - rmse: 0.0859 - smape: 0.1716 - val_ia: 0.8960 - val_loss: 0.0035 - val_mae: 0.0433 - val_rmse: 0.0549 - val_smape: 0.1445

Epoch 68/128

1147/1147 - 10s - 9ms/step - ia: 0.9604 - loss: 0.0079 - mae: 0.0640 - rmse: 0.0860 - smape: 0.1717 - val_ia: 0.8935 - val_loss: 0.0035 - val_mae: 0.0440 - val_rmse: 0.0558 - val_smape: 0.1396

Epoch 69/128

1147/1147 - 11s - 9ms/step - ia: 0.9605 - loss: 0.0079 - mae: 0.0638 - rmse: 0.0860 - smape: 0.1715 - val_ia: 0.9100 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0503 - val_smape: 0.1336

Epoch 70/128

1147/1147 - 10s - 9ms/step - ia: 0.9603 - loss: 0.0079 - mae: 0.0641 - rmse: 0.0862 - smape: 0.1721 - val_ia: 0.9061 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0513 - val_smape: 0.1300

Epoch 71/128

1147/1147 - 10s - 9ms/step - ia: 0.9606 - loss: 0.0078 - mae: 0.0635 - rmse: 0.0858 - smape: 0.1687 - val_ia: 0.9048 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0518 - val_smape: 0.1377

Epoch 72/128

1147/1147 - 10s - 9ms/step - ia: 0.9604 - loss: 0.0079 - mae: 0.0640 - rmse: 0.0862 - smape: 0.1721 - val_ia: 0.9057 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0509 - val_smape: 0.1324

Epoch 73/128

1147/1147 - 10s - 9ms/step - ia: 0.9605 - loss: 0.0078 - mae: 0.0638 - rmse: 0.0858 - smape: 0.1728 - val_ia: 0.8915 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0581 - val_smape: 0.1554

Epoch 74/128

1147/1147 - 11s - 10ms/step - ia: 0.9609 - loss: 0.0077 - mae: 0.0633 - rmse: 0.0850 - smape: 0.1710 - val_ia: 0.9096 - val_loss: 0.0029 - val_mae: 0.0382 - val_rmse: 0.0504 - val_smape: 0.1302

Epoch 75/128

1147/1147 - 20s - 18ms/step - ia: 0.9608 - loss: 0.0077 - mae: 0.0633 - rmse: 0.0852 - smape: 0.1697 - val_ia: 0.9097 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0504 - val_smape: 0.1287

Epoch 76/128

1147/1147 - 10s - 9ms/step - ia: 0.9608 - loss: 0.0078 - mae: 0.0634 - rmse: 0.0854 - smape: 0.1696 - val_ia: 0.9103 - val_loss: 0.0029 - val_mae: 0.0383 - val_rmse: 0.0502 - val_smape: 0.1322

Epoch 77/128

1147/1147 - 19s - 17ms/step - ia: 0.9609 - loss: 0.0077 - mae: 0.0633 - rmse: 0.0850 - smape: 0.1701 - val_ia: 0.8975 - val_loss: 0.0033 - val_mae: 0.0417 - val_rmse: 0.0535 - val_smape: 0.1375

Epoch 78/128

1147/1147 - 11s - 9ms/step - ia: 0.9609 - loss: 0.0078 - mae: 0.0633 - rmse: 0.0855 - smape: 0.1703 - val_ia: 0.8990 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0529 - val_smape: 0.1318

Epoch 79/128

1147/1147 - 11s - 9ms/step - ia: 0.9611 - loss: 0.0076 - mae: 0.0629 - rmse: 0.0847 - smape: 0.1689 - val_ia: 0.8909 - val_loss: 0.0035 - val_mae: 0.0444 - val_rmse: 0.0561 - val_smape: 0.1396

Epoch 80/128

1147/1147 - 11s - 9ms/step - ia: 0.9608 - loss: 0.0077 - mae: 0.0633 - rmse: 0.0849 - smape: 0.1706 - val_ia: 0.8984 - val_loss: 0.0032 - val_mae: 0.0416 - val_rmse: 0.0533 - val_smape: 0.1339

Epoch 81/128

1147/1147 - 11s - 9ms/step - ia: 0.9609 - loss: 0.0077 - mae: 0.0630 - rmse: 0.0852 - smape: 0.1688 - val_ia: 0.8876 - val_loss: 0.0037 - val_mae: 0.0461 - val_rmse: 0.0577 - val_smape: 0.1448

Epoch 82/128

1147/1147 - 10s - 9ms/step - ia: 0.9606 - loss: 0.0078 - mae: 0.0636 - rmse: 0.0857 - smape: 0.1698 - val_ia: 0.9091 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0510 - val_smape: 0.1317

Epoch 83/128

1147/1147 - 10s - 9ms/step - ia: 0.9608 - loss: 0.0077 - mae: 0.0634 - rmse: 0.0853 - smape: 0.1701 - val_ia: 0.8916 - val_loss: 0.0034 - val_mae: 0.0434 - val_rmse: 0.0549 - val_smape: 0.1341

Epoch 84/128

1147/1147 - 10s - 9ms/step - ia: 0.9608 - loss: 0.0078 - mae: 0.0633 - rmse: 0.0853 - smape: 0.1684 - val_ia: 0.9039 - val_loss: 0.0030 - val_mae: 0.0399 - val_rmse: 0.0519 - val_smape: 0.1271

Epoch 85/128

1147/1147 - 10s - 9ms/step - ia: 0.9612 - loss: 0.0077 - mae: 0.0627 - rmse: 0.0849 - smape: 0.1676 - val_ia: 0.9079 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0505 - val_smape: 0.1287

Epoch 86/128

1147/1147 - 9s - 8ms/step - ia: 0.9611 - loss: 0.0076 - mae: 0.0628 - rmse: 0.0845 - smape: 0.1686 - val_ia: 0.8995 - val_loss: 0.0032 - val_mae: 0.0416 - val_rmse: 0.0534 - val_smape: 0.1393

Epoch 87/128

1147/1147 - 10s - 9ms/step - ia: 0.9615 - loss: 0.0075 - mae: 0.0623 - rmse: 0.0836 - smape: 0.1687 - val_ia: 0.9038 - val_loss: 0.0030 - val_mae: 0.0395 - val_rmse: 0.0512 - val_smape: 0.1303

Epoch 88/128

1147/1147 - 10s - 9ms/step - ia: 0.9610 - loss: 0.0077 - mae: 0.0630 - rmse: 0.0851 - smape: 0.1683 - val_ia: 0.9101 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0498 - val_smape: 0.1276

Epoch 89/128

1147/1147 - 10s - 9ms/step - ia: 0.9612 - loss: 0.0076 - mae: 0.0627 - rmse: 0.0846 - smape: 0.1667 - val_ia: 0.9029 - val_loss: 0.0030 - val_mae: 0.0401 - val_rmse: 0.0521 - val_smape: 0.1277

Epoch 90/128

1147/1147 - 10s - 9ms/step - ia: 0.9615 - loss: 0.0075 - mae: 0.0622 - rmse: 0.0840 - smape: 0.1670 - val_ia: 0.9082 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0504 - val_smape: 0.1326

Epoch 91/128

1147/1147 - 12s - 10ms/step - ia: 0.9613 - loss: 0.0075 - mae: 0.0625 - rmse: 0.0842 - smape: 0.1691 - val_ia: 0.9081 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0503 - val_smape: 0.1320

Epoch 92/128

1147/1147 - 12s - 11ms/step - ia: 0.9613 - loss: 0.0076 - mae: 0.0626 - rmse: 0.0845 - smape: 0.1672 - val_ia: 0.8992 - val_loss: 0.0031 - val_mae: 0.0409 - val_rmse: 0.0525 - val_smape: 0.1333

Epoch 93/128

1147/1147 - 12s - 10ms/step - ia: 0.9614 - loss: 0.0076 - mae: 0.0624 - rmse: 0.0844 - smape: 0.1681 - val_ia: 0.8971 - val_loss: 0.0033 - val_mae: 0.0425 - val_rmse: 0.0543 - val_smape: 0.1347

Epoch 94/128

1147/1147 - 10s - 9ms/step - ia: 0.9613 - loss: 0.0076 - mae: 0.0626 - rmse: 0.0844 - smape: 0.1673 - val_ia: 0.8974 - val_loss: 0.0032 - val_mae: 0.0414 - val_rmse: 0.0529 - val_smape: 0.1292

Epoch 95/128

1147/1147 - 10s - 9ms/step - ia: 0.9615 - loss: 0.0075 - mae: 0.0621 - rmse: 0.0840 - smape: 0.1658 - val_ia: 0.9095 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0498 - val_smape: 0.1306

Epoch 96/128

1147/1147 - 11s - 9ms/step - ia: 0.9615 - loss: 0.0075 - mae: 0.0622 - rmse: 0.0837 - smape: 0.1685 - val_ia: 0.9085 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0498 - val_smape: 0.1276

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 29s - 99ms/step - ia: 0.8234 - loss: 0.1369 - mae: 0.2592 - rmse: 0.3343 - smape: 0.5524 - val_ia: 0.8916 - val_loss: 0.0352 - val_mae: 0.1410 - val_rmse: 0.1822 - val_smape: 0.3624

Epoch 2/16

287/287 - 5s - 18ms/step - ia: 0.9046 - loss: 0.0436 - mae: 0.1551 - rmse: 0.2074 - smape: 0.3515 - val_ia: 0.9354 - val_loss: 0.0148 - val_mae: 0.0855 - val_rmse: 0.1200 - val_smape: 0.2275

Epoch 3/16

287/287 - 5s - 18ms/step - ia: 0.9188 - loss: 0.0323 - mae: 0.1325 - rmse: 0.1788 - smape: 0.3035 - val_ia: 0.9495 - val_loss: 0.0097 - val_mae: 0.0669 - val_rmse: 0.0974 - val_smape: 0.1802

Epoch 4/16

287/287 - 5s - 18ms/step - ia: 0.9262 - loss: 0.0269 - mae: 0.1208 - rmse: 0.1632 - smape: 0.2794 - val_ia: 0.9514 - val_loss: 0.0087 - val_mae: 0.0644 - val_rmse: 0.0920 - val_smape: 0.1697

Epoch 5/16

287/287 - 10s - 36ms/step - ia: 0.9300 - loss: 0.0242 - mae: 0.1145 - rmse: 0.1546 - smape: 0.2680 - val_ia: 0.9548 - val_loss: 0.0073 - val_mae: 0.0608 - val_rmse: 0.0841 - val_smape: 0.1708

Epoch 6/16

287/287 - 5s - 18ms/step - ia: 0.9336 - loss: 0.0221 - mae: 0.1089 - rmse: 0.1476 - smape: 0.2533 - val_ia: 0.9555 - val_loss: 0.0069 - val_mae: 0.0593 - val_rmse: 0.0811 - val_smape: 0.1582

Epoch 7/16

287/287 - 5s - 18ms/step - ia: 0.9361 - loss: 0.0203 - mae: 0.1048 - rmse: 0.1416 - smape: 0.2449 - val_ia: 0.9608 - val_loss: 0.0054 - val_mae: 0.0532 - val_rmse: 0.0724 - val_smape: 0.1552

Epoch 8/16

287/287 - 5s - 18ms/step - ia: 0.9394 - loss: 0.0187 - mae: 0.0995 - rmse: 0.1357 - smape: 0.2350 - val_ia: 0.9588 - val_loss: 0.0059 - val_mae: 0.0552 - val_rmse: 0.0748 - val_smape: 0.1500

Epoch 9/16

287/287 - 5s - 19ms/step - ia: 0.9417 - loss: 0.0174 - mae: 0.0958 - rmse: 0.1310 - smape: 0.2263 - val_ia: 0.9571 - val_loss: 0.0059 - val_mae: 0.0576 - val_rmse: 0.0744 - val_smape: 0.1704

Epoch 10/16

287/287 - 5s - 18ms/step - ia: 0.9430 - loss: 0.0167 - mae: 0.0936 - rmse: 0.1281 - smape: 0.2195 - val_ia: 0.9662 - val_loss: 0.0042 - val_mae: 0.0458 - val_rmse: 0.0635 - val_smape: 0.1349

Epoch 11/16

287/287 - 5s - 19ms/step - ia: 0.9443 - loss: 0.0161 - mae: 0.0915 - rmse: 0.1257 - smape: 0.2151 - val_ia: 0.9613 - val_loss: 0.0052 - val_mae: 0.0520 - val_rmse: 0.0711 - val_smape: 0.1382

Epoch 12/16

287/287 - 5s - 19ms/step - ia: 0.9447 - loss: 0.0157 - mae: 0.0908 - rmse: 0.1246 - smape: 0.2126 - val_ia: 0.9663 - val_loss: 0.0041 - val_mae: 0.0453 - val_rmse: 0.0630 - val_smape: 0.1316

Epoch 13/16

287/287 - 5s - 18ms/step - ia: 0.9460 - loss: 0.0151 - mae: 0.0886 - rmse: 0.1220 - smape: 0.2082 - val_ia: 0.9684 - val_loss: 0.0037 - val_mae: 0.0432 - val_rmse: 0.0595 - val_smape: 0.1303

Epoch 14/16

287/287 - 5s - 18ms/step - ia: 0.9465 - loss: 0.0148 - mae: 0.0879 - rmse: 0.1208 - smape: 0.2061 - val_ia: 0.9674 - val_loss: 0.0039 - val_mae: 0.0438 - val_rmse: 0.0613 - val_smape: 0.1258

Epoch 15/16

287/287 - 5s - 19ms/step - ia: 0.9473 - loss: 0.0145 - mae: 0.0866 - rmse: 0.1194 - smape: 0.2039 - val_ia: 0.9664 - val_loss: 0.0039 - val_mae: 0.0455 - val_rmse: 0.0611 - val_smape: 0.1419

Epoch 16/16

287/287 - 5s - 19ms/step - ia: 0.9477 - loss: 0.0143 - mae: 0.0859 - rmse: 0.1185 - smape: 0.2005 - val_ia: 0.9720 - val_loss: 0.0031 - val_mae: 0.0379 - val_rmse: 0.0547 - val_smape: 0.1185

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:15 2s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step

 26%|██▌       | 13/50 [2:31:19<4:52:41, 474.63s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 12s - 43ms/step - ia: 0.5539 - loss: 0.5550 - mae: 0.5609 - rmse: 0.7018 - smape: 1.0610 - val_ia: 0.7632 - val_loss: 0.1701 - val_mae: 0.3194 - val_rmse: 0.4076 - val_smape: 0.7035

Epoch 2/8

287/287 - 3s - 11ms/step - ia: 0.7886 - loss: 0.1872 - mae: 0.3358 - rmse: 0.4310 - smape: 0.6717 - val_ia: 0.8007 - val_loss: 0.1244 - val_mae: 0.2762 - val_rmse: 0.3494 - val_smape: 0.6238

Epoch 3/8

287/287 - 3s - 11ms/step - ia: 0.8238 - loss: 0.1356 - mae: 0.2824 - rmse: 0.3666 - smape: 0.5814 - val_ia: 0.8260 - val_loss: 0.0970 - val_mae: 0.2431 - val_rmse: 0.3024 - val_smape: 0.5775

Epoch 4/8

287/287 - 3s - 11ms/step - ia: 0.8479 - loss: 0.1032 - mae: 0.2455 - rmse: 0.3200 - smape: 0.5140 - val_ia: 0.8445 - val_loss: 0.0770 - val_mae: 0.2168 - val_rmse: 0.2668 - val_smape: 0.5398

Epoch 5/8

287/287 - 3s - 11ms/step - ia: 0.8668 - loss: 0.0809 - mae: 0.2165 - rmse: 0.2834 - smape: 0.4645 - val_ia: 0.8652 - val_loss: 0.0553 - val_mae: 0.1852 - val_rmse: 0.2273 - val_smape: 0.4914

Epoch 6/8

287/287 - 3s - 10ms/step - ia: 0.8790 - loss: 0.0664 - mae: 0.1970 - rmse: 0.2569 - smape: 0.4347 - val_ia: 0.8890 - val_loss: 0.0377 - val_mae: 0.1513 - val_rmse: 0.1894 - val_smape: 0.4327

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.8909 - loss: 0.0547 - mae: 0.1779 - rmse: 0.2331 - smape: 0.4012 - val_ia: 0.9083 - val_loss: 0.0267 - val_mae: 0.1244 - val_rmse: 0.1604 - val_smape: 0.3760

Epoch 8/8

287/287 - 3s - 11ms/step - ia: 0.8990 - loss: 0.0475 - mae: 0.1649 - rmse: 0.2171 - smape: 0.3753 - val_ia: 0.9211 - val_loss: 0.0207 - val_mae: 0.1070 - val_rmse: 0.1417 - val_smape: 0.3330

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:44 643ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 28%|██▊       | 14/50 [2:31:55<3:25:18, 342.18s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

574/574 - 14s - 24ms/step - ia: 0.8927 - loss: 0.0597 - mae: 0.1723 - rmse: 0.2323 - smape: 0.3535 - val_ia: 0.9256 - val_loss: 0.0092 - val_mae: 0.0716 - val_rmse: 0.0924 - val_smape: 0.1692

Epoch 2/16

574/574 - 4s - 6ms/step - ia: 0.9127 - loss: 0.0398 - mae: 0.1410 - rmse: 0.1975 - smape: 0.2740 - val_ia: 0.9379 - val_loss: 0.0060 - val_mae: 0.0586 - val_rmse: 0.0750 - val_smape: 0.1636

Epoch 3/16

574/574 - 4s - 7ms/step - ia: 0.9157 - loss: 0.0375 - mae: 0.1362 - rmse: 0.1918 - smape: 0.2585 - val_ia: 0.9437 - val_loss: 0.0053 - val_mae: 0.0526 - val_rmse: 0.0694 - val_smape: 0.1361

Epoch 4/16

574/574 - 4s - 7ms/step - ia: 0.9162 - loss: 0.0373 - mae: 0.1353 - rmse: 0.1912 - smape: 0.2559 - val_ia: 0.9350 - val_loss: 0.0064 - val_mae: 0.0610 - val_rmse: 0.0774 - val_smape: 0.1517

Epoch 5/16

574/574 - 4s - 7ms/step - ia: 0.9166 - loss: 0.0374 - mae: 0.1347 - rmse: 0.1914 - smape: 0.2517 - val_ia: 0.9283 - val_loss: 0.0084 - val_mae: 0.0699 - val_rmse: 0.0882 - val_smape: 0.1513

Epoch 6/16

574/574 - 4s - 6ms/step - ia: 0.9165 - loss: 0.0377 - mae: 0.1350 - rmse: 0.1920 - smape: 0.2518 - val_ia: 0.9607 - val_loss: 0.0032 - val_mae: 0.0383 - val_rmse: 0.0546 - val_smape: 0.1143

Epoch 7/16

574/574 - 4s - 7ms/step - ia: 0.9167 - loss: 0.0373 - mae: 0.1349 - rmse: 0.1911 - smape: 0.2485 - val_ia: 0.9460 - val_loss: 0.0049 - val_mae: 0.0515 - val_rmse: 0.0679 - val_smape: 0.1296

Epoch 8/16

574/574 - 4s - 7ms/step - ia: 0.9178 - loss: 0.0367 - mae: 0.1331 - rmse: 0.1896 - smape: 0.2446 - val_ia: 0.9487 - val_loss: 0.0051 - val_mae: 0.0512 - val_rmse: 0.0684 - val_smape: 0.1298

Epoch 9/16

574/574 - 4s - 7ms/step - ia: 0.9180 - loss: 0.0364 - mae: 0.1329 - rmse: 0.1887 - smape: 0.2456 - val_ia: 0.9312 - val_loss: 0.0071 - val_mae: 0.0649 - val_rmse: 0.0816 - val_smape: 0.1519

Epoch 10/16

574/574 - 4s - 7ms/step - ia: 0.9179 - loss: 0.0362 - mae: 0.1326 - rmse: 0.1885 - smape: 0.2439 - val_ia: 0.9460 - val_loss: 0.0048 - val_mae: 0.0521 - val_rmse: 0.0670 - val_smape: 0.1516

Epoch 11/16

574/574 - 4s - 7ms/step - ia: 0.9176 - loss: 0.0367 - mae: 0.1332 - rmse: 0.1898 - smape: 0.2464 - val_ia: 0.9595 - val_loss: 0.0033 - val_mae: 0.0402 - val_rmse: 0.0551 - val_smape: 0.1240

Epoch 12/16

574/574 - 4s - 7ms/step - ia: 0.9173 - loss: 0.0369 - mae: 0.1338 - rmse: 0.1901 - smape: 0.2479 - val_ia: 0.9366 - val_loss: 0.0061 - val_mae: 0.0596 - val_rmse: 0.0751 - val_smape: 0.1515

Epoch 13/16

574/574 - 4s - 7ms/step - ia: 0.9180 - loss: 0.0359 - mae: 0.1325 - rmse: 0.1875 - smape: 0.2449 - val_ia: 0.9148 - val_loss: 0.0099 - val_mae: 0.0785 - val_rmse: 0.0955 - val_smape: 0.1729

Epoch 14/16

574/574 - 4s - 7ms/step - ia: 0.9171 - loss: 0.0370 - mae: 0.1339 - rmse: 0.1904 - smape: 0.2452 - val_ia: 0.9577 - val_loss: 0.0034 - val_mae: 0.0411 - val_rmse: 0.0561 - val_smape: 0.1232

Epoch 15/16

574/574 - 4s - 7ms/step - ia: 0.9174 - loss: 0.0368 - mae: 0.1337 - rmse: 0.1899 - smape: 0.2476 - val_ia: 0.9467 - val_loss: 0.0053 - val_mae: 0.0525 - val_rmse: 0.0699 - val_smape: 0.1334

Epoch 16/16

574/574 - 4s - 7ms/step - ia: 0.9181 - loss: 0.0364 - mae: 0.1326 - rmse: 0.1889 - smape: 0.2440 - val_ia: 0.9306 - val_loss: 0.0075 - val_mae: 0.0658 - val_rmse: 0.0838 - val_smape: 0.1446

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:49 673ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 30%|███       | 15/50 [2:33:10<2:32:31, 261.48s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4586/4586 - 58s - 13ms/step - ia: 0.8741 - loss: 0.0670 - mae: 0.1836 - rmse: 0.2387 - smape: 0.3561 - val_ia: 0.4224 - val_loss: 0.0327 - val_mae: 0.1467 - val_rmse: 0.1544 - val_smape: 0.3494

Epoch 2/256

4586/4586 - 39s - 8ms/step - ia: 0.8877 - loss: 0.0533 - mae: 0.1649 - rmse: 0.2163 - smape: 0.3187 - val_ia: 0.5402 - val_loss: 0.0112 - val_mae: 0.0811 - val_rmse: 0.0924 - val_smape: 0.2345

Epoch 3/256

4586/4586 - 36s - 8ms/step - ia: 0.5300 - loss: 1.1132 - mae: 0.6155 - rmse: 0.7797 - smape: 1.0207 - val_ia: 0.1592 - val_loss: 0.6655 - val_mae: 0.6681 - val_rmse: 0.6844 - val_smape: 1.3613

Epoch 4/256

4586/4586 - 39s - 9ms/step - ia: 0.3339 - loss: 3.2192 - mae: 0.9464 - rmse: 1.2339 - smape: 1.3932 - val_ia: 0.1574 - val_loss: 0.5867 - val_mae: 0.6305 - val_rmse: 0.6594 - val_smape: 1.1937

Epoch 5/256

4586/4586 - 42s - 9ms/step - ia: 0.4099 - loss: 5.9632 - mae: 0.8911 - rmse: 1.1792 - smape: 1.2596 - val_ia: 0.1742 - val_loss: 0.4307 - val_mae: 0.5301 - val_rmse: 0.5615 - val_smape: 1.0711

Epoch 6/256

4586/4586 - 35s - 8ms/step - ia: 0.3930 - loss: 42.5148 - mae: 2.0264 - rmse: 2.7531 - smape: 1.2631 - val_ia: 0.1748 - val_loss: 2.4180 - val_mae: 0.5771 - val_rmse: 0.6776 - val_smape: 0.9999

Epoch 7/256

4586/4586 - 39s - 9ms/step - ia: 0.4848 - loss: 0.9297 - mae: 0.6726 - rmse: 0.8376 - smape: 1.1882 - val_ia: 0.1509 - val_loss: 0.6151 - val_mae: 0.6262 - val_rmse: 0.6688 - val_smape: 1.0414

Epoch 8/256

4586/4586 - 41s - 9ms/step - ia: 0.4744 - loss: 0.8848 - mae: 0.7155 - rmse: 0.8787 - smape: 1.1961 - val_ia: 0.1566 - val_loss: 0.5856 - val_mae: 0.6333 - val_rmse: 0.6554 - val_smape: 1.1334

Epoch 9/256

4586/4586 - 39s - 9ms/step - ia: 0.5104 - loss: 0.7499 - mae: 0.6752 - rmse: 0.8249 - smape: 1.1317 - val_ia: 0.1718 - val_loss: 0.3984 - val_mae: 0.4948 - val_rmse: 0.5210 - val_smape: 0.9672

Epoch 10/256

4586/4586 - 36s - 8ms/step - ia: 0.5495 - loss: 1.6097 - mae: 0.6794 - rmse: 0.8479 - smape: 1.0609 - val_ia: 0.2009 - val_loss: 0.3146 - val_mae: 0.4444 - val_rmse: 0.4673 - val_smape: 0.9216

Epoch 11/256

4586/4586 - 39s - 8ms/step - ia: 0.6267 - loss: 0.3868 - mae: 0.4992 - rmse: 0.6039 - smape: 0.9367 - val_ia: 0.1959 - val_loss: 0.2989 - val_mae: 0.4423 - val_rmse: 0.4649 - val_smape: 0.8916

Epoch 12/256

4586/4586 - 40s - 9ms/step - ia: 0.6602 - loss: 0.3323 - mae: 0.4639 - rmse: 0.5594 - smape: 0.8790 - val_ia: 0.2174 - val_loss: 0.2126 - val_mae: 0.3781 - val_rmse: 0.4014 - val_smape: 0.7751

Epoch 13/256

4586/4586 - 40s - 9ms/step - ia: 0.7016 - loss: 0.2705 - mae: 0.4115 - rmse: 0.5014 - smape: 0.7944 - val_ia: 0.2226 - val_loss: 0.2595 - val_mae: 0.4005 - val_rmse: 0.4197 - val_smape: 0.8587

Epoch 14/256

4586/4586 - 40s - 9ms/step - ia: 0.6322 - loss: 0.8200 - mae: 0.5312 - rmse: 0.6694 - smape: 0.9210 - val_ia: 0.1915 - val_loss: 0.3261 - val_mae: 0.4721 - val_rmse: 0.4950 - val_smape: 0.9877

Epoch 15/256

4586/4586 - 39s - 9ms/step - ia: 0.6709 - loss: 0.3276 - mae: 0.4470 - rmse: 0.5477 - smape: 0.8691 - val_ia: 0.2130 - val_loss: 0.2402 - val_mae: 0.3976 - val_rmse: 0.4187 - val_smape: 0.8909

Epoch 16/256

4586/4586 - 40s - 9ms/step - ia: 0.6945 - loss: 0.5428 - mae: 0.4347 - rmse: 0.5427 - smape: 0.8193 - val_ia: 0.1522 - val_loss: 3.6667 - val_mae: 0.9726 - val_rmse: 1.1761 - val_smape: 1.0383

Epoch 17/256

4586/4586 - 40s - 9ms/step - ia: 0.3347 - loss: 136.3676 - mae: 2.0614 - rmse: 3.2824 - smape: 1.3222 - val_ia: 0.1738 - val_loss: 2.3522 - val_mae: 0.5504 - val_rmse: 0.6520 - val_smape: 0.9397

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:06 1s/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 32%|███▏      | 16/50 [2:44:36<3:40:34, 389.24s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4586/4586 - 104s - 23ms/step - ia: 0.8830 - loss: 0.0638 - mae: 0.1685 - rmse: 0.2087 - smape: 0.3823 - val_ia: 0.5491 - val_loss: 0.0114 - val_mae: 0.0806 - val_rmse: 0.0902 - val_smape: 0.1915

Epoch 2/256

4586/4586 - 68s - 15ms/step - ia: 0.9239 - loss: 0.0221 - mae: 0.1115 - rmse: 0.1404 - smape: 0.2727 - val_ia: 0.6080 - val_loss: 0.0066 - val_mae: 0.0602 - val_rmse: 0.0697 - val_smape: 0.1697

Epoch 3/256

4586/4586 - 89s - 19ms/step - ia: 0.9308 - loss: 0.0189 - mae: 0.1023 - rmse: 0.1296 - smape: 0.2503 - val_ia: 0.6289 - val_loss: 0.0054 - val_mae: 0.0546 - val_rmse: 0.0638 - val_smape: 0.1585

Epoch 4/256

4586/4586 - 73s - 16ms/step - ia: 0.9333 - loss: 0.0176 - mae: 0.0978 - rmse: 0.1247 - smape: 0.2377 - val_ia: 0.5027 - val_loss: 0.0123 - val_mae: 0.0921 - val_rmse: 0.0999 - val_smape: 0.2437

Epoch 5/256

4586/4586 - 71s - 15ms/step - ia: 0.9350 - loss: 0.0167 - mae: 0.0954 - rmse: 0.1216 - smape: 0.2316 - val_ia: 0.6103 - val_loss: 0.0058 - val_mae: 0.0590 - val_rmse: 0.0673 - val_smape: 0.1628

Epoch 6/256

4586/4586 - 72s - 16ms/step - ia: 0.9374 - loss: 0.0160 - mae: 0.0928 - rmse: 0.1186 - smape: 0.2247 - val_ia: 0.6090 - val_loss: 0.0060 - val_mae: 0.0597 - val_rmse: 0.0676 - val_smape: 0.1818

Epoch 7/256

4586/4586 - 74s - 16ms/step - ia: 0.9374 - loss: 0.0161 - mae: 0.0926 - rmse: 0.1186 - smape: 0.2227 - val_ia: 0.5736 - val_loss: 0.0077 - val_mae: 0.0677 - val_rmse: 0.0761 - val_smape: 0.1824

Epoch 8/256

4586/4586 - 71s - 15ms/step - ia: 0.9391 - loss: 0.0151 - mae: 0.0898 - rmse: 0.1153 - smape: 0.2172 - val_ia: 0.6518 - val_loss: 0.0050 - val_mae: 0.0503 - val_rmse: 0.0588 - val_smape: 0.1462

Epoch 9/256

4586/4586 - 72s - 16ms/step - ia: 0.9398 - loss: 0.0148 - mae: 0.0888 - rmse: 0.1137 - smape: 0.2138 - val_ia: 0.6348 - val_loss: 0.0047 - val_mae: 0.0514 - val_rmse: 0.0595 - val_smape: 0.1718

Epoch 10/256

4586/4586 - 73s - 16ms/step - ia: 0.9400 - loss: 0.0149 - mae: 0.0888 - rmse: 0.1139 - smape: 0.2118 - val_ia: 0.6448 - val_loss: 0.0046 - val_mae: 0.0502 - val_rmse: 0.0585 - val_smape: 0.1393

Epoch 11/256

4586/4586 - 74s - 16ms/step - ia: 0.9408 - loss: 0.0146 - mae: 0.0877 - rmse: 0.1128 - smape: 0.2108 - val_ia: 0.6274 - val_loss: 0.0054 - val_mae: 0.0549 - val_rmse: 0.0632 - val_smape: 0.1658

Epoch 12/256

4586/4586 - 72s - 16ms/step - ia: 0.9409 - loss: 0.0144 - mae: 0.0872 - rmse: 0.1122 - smape: 0.2078 - val_ia: 0.6700 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0522 - val_smape: 0.1327

Epoch 13/256

4586/4586 - 68s - 15ms/step - ia: 0.9412 - loss: 0.0145 - mae: 0.0868 - rmse: 0.1120 - smape: 0.2081 - val_ia: 0.6150 - val_loss: 0.0073 - val_mae: 0.0621 - val_rmse: 0.0702 - val_smape: 0.1436

Epoch 14/256

4586/4586 - 68s - 15ms/step - ia: 0.9419 - loss: 0.0141 - mae: 0.0863 - rmse: 0.1109 - smape: 0.2077 - val_ia: 0.6605 - val_loss: 0.0039 - val_mae: 0.0470 - val_rmse: 0.0559 - val_smape: 0.1529

Epoch 15/256

4586/4586 - 68s - 15ms/step - ia: 0.9422 - loss: 0.0139 - mae: 0.0854 - rmse: 0.1103 - smape: 0.2045 - val_ia: 0.6615 - val_loss: 0.0039 - val_mae: 0.0461 - val_rmse: 0.0547 - val_smape: 0.1411

Epoch 16/256

4586/4586 - 67s - 15ms/step - ia: 0.9425 - loss: 0.0138 - mae: 0.0851 - rmse: 0.1096 - smape: 0.2032 - val_ia: 0.5107 - val_loss: 0.0105 - val_mae: 0.0868 - val_rmse: 0.0938 - val_smape: 0.2399

Epoch 17/256

4586/4586 - 75s - 16ms/step - ia: 0.9423 - loss: 0.0140 - mae: 0.0853 - rmse: 0.1103 - smape: 0.2035 - val_ia: 0.6442 - val_loss: 0.0046 - val_mae: 0.0507 - val_rmse: 0.0591 - val_smape: 0.1457

Epoch 18/256

4586/4586 - 67s - 15ms/step - ia: 0.9421 - loss: 0.0139 - mae: 0.0854 - rmse: 0.1102 - smape: 0.2028 - val_ia: 0.6537 - val_loss: 0.0045 - val_mae: 0.0493 - val_rmse: 0.0579 - val_smape: 0.1413

Epoch 19/256

4586/4586 - 72s - 16ms/step - ia: 0.9427 - loss: 0.0137 - mae: 0.0848 - rmse: 0.1095 - smape: 0.2012 - val_ia: 0.6405 - val_loss: 0.0051 - val_mae: 0.0524 - val_rmse: 0.0614 - val_smape: 0.1743

Epoch 20/256

4586/4586 - 73s - 16ms/step - ia: 0.9432 - loss: 0.0136 - mae: 0.0842 - rmse: 0.1088 - smape: 0.2000 - val_ia: 0.6904 - val_loss: 0.0032 - val_mae: 0.0403 - val_rmse: 0.0490 - val_smape: 0.1337

Epoch 21/256

4586/4586 - 68s - 15ms/step - ia: 0.9434 - loss: 0.0135 - mae: 0.0836 - rmse: 0.1081 - smape: 0.1985 - val_ia: 0.6708 - val_loss: 0.0036 - val_mae: 0.0445 - val_rmse: 0.0530 - val_smape: 0.1407

Epoch 22/256

4586/4586 - 69s - 15ms/step - ia: 0.9434 - loss: 0.0135 - mae: 0.0838 - rmse: 0.1083 - smape: 0.1987 - val_ia: 0.6619 - val_loss: 0.0037 - val_mae: 0.0450 - val_rmse: 0.0536 - val_smape: 0.1480

Epoch 23/256

4586/4586 - 64s - 14ms/step - ia: 0.9437 - loss: 0.0134 - mae: 0.0836 - rmse: 0.1078 - smape: 0.1982 - val_ia: 0.6875 - val_loss: 0.0032 - val_mae: 0.0408 - val_rmse: 0.0491 - val_smape: 0.1282

Epoch 24/256

4586/4586 - 75s - 16ms/step - ia: 0.9438 - loss: 0.0132 - mae: 0.0832 - rmse: 0.1072 - smape: 0.1988 - val_ia: 0.6731 - val_loss: 0.0034 - val_mae: 0.0435 - val_rmse: 0.0519 - val_smape: 0.1394

Epoch 25/256

4586/4586 - 72s - 16ms/step - ia: 0.9436 - loss: 0.0134 - mae: 0.0835 - rmse: 0.1080 - smape: 0.1964 - val_ia: 0.6514 - val_loss: 0.0039 - val_mae: 0.0469 - val_rmse: 0.0551 - val_smape: 0.1485

Epoch 26/256

4586/4586 - 69s - 15ms/step - ia: 0.9439 - loss: 0.0133 - mae: 0.0831 - rmse: 0.1075 - smape: 0.1970 - val_ia: 0.5948 - val_loss: 0.0061 - val_mae: 0.0626 - val_rmse: 0.0709 - val_smape: 0.1499

Epoch 27/256

4586/4586 - 68s - 15ms/step - ia: 0.9440 - loss: 0.0131 - mae: 0.0828 - rmse: 0.1070 - smape: 0.1964 - val_ia: 0.6879 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0479 - val_smape: 0.1280

Epoch 28/256

4586/4586 - 64s - 14ms/step - ia: 0.9435 - loss: 0.0134 - mae: 0.0832 - rmse: 0.1078 - smape: 0.1967 - val_ia: 0.6515 - val_loss: 0.0041 - val_mae: 0.0476 - val_rmse: 0.0561 - val_smape: 0.1331

Epoch 29/256

4586/4586 - 72s - 16ms/step - ia: 0.9443 - loss: 0.0132 - mae: 0.0825 - rmse: 0.1069 - smape: 0.1946 - val_ia: 0.6695 - val_loss: 0.0039 - val_mae: 0.0449 - val_rmse: 0.0530 - val_smape: 0.1334

Epoch 30/256

4586/4586 - 72s - 16ms/step - ia: 0.9443 - loss: 0.0129 - mae: 0.0816 - rmse: 0.1058 - smape: 0.1925 - val_ia: 0.6848 - val_loss: 0.0035 - val_mae: 0.0422 - val_rmse: 0.0507 - val_smape: 0.1430

Epoch 31/256

4586/4586 - 68s - 15ms/step - ia: 0.9442 - loss: 0.0132 - mae: 0.0823 - rmse: 0.1069 - smape: 0.1924 - val_ia: 0.6379 - val_loss: 0.0040 - val_mae: 0.0486 - val_rmse: 0.0567 - val_smape: 0.1450

Epoch 32/256

4586/4586 - 72s - 16ms/step - ia: 0.9446 - loss: 0.0130 - mae: 0.0818 - rmse: 0.1061 - smape: 0.1924 - val_ia: 0.6944 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0479 - val_smape: 0.1189

Epoch 33/256

4586/4586 - 67s - 15ms/step - ia: 0.9444 - loss: 0.0131 - mae: 0.0824 - rmse: 0.1067 - smape: 0.1958 - val_ia: 0.6031 - val_loss: 0.0052 - val_mae: 0.0575 - val_rmse: 0.0654 - val_smape: 0.1567

Epoch 34/256

4586/4586 - 74s - 16ms/step - ia: 0.9445 - loss: 0.0130 - mae: 0.0818 - rmse: 0.1061 - smape: 0.1935 - val_ia: 0.6477 - val_loss: 0.0040 - val_mae: 0.0473 - val_rmse: 0.0554 - val_smape: 0.1501

Epoch 35/256

4586/4586 - 83s - 18ms/step - ia: 0.9445 - loss: 0.0129 - mae: 0.0816 - rmse: 0.1059 - smape: 0.1907 - val_ia: 0.6758 - val_loss: 0.0034 - val_mae: 0.0425 - val_rmse: 0.0511 - val_smape: 0.1322

Epoch 36/256

4586/4586 - 88s - 19ms/step - ia: 0.9446 - loss: 0.0131 - mae: 0.0821 - rmse: 0.1064 - smape: 0.1918 - val_ia: 0.6523 - val_loss: 0.0041 - val_mae: 0.0481 - val_rmse: 0.0563 - val_smape: 0.1673

Epoch 37/256

4586/4586 - 85s - 18ms/step - ia: 0.9455 - loss: 0.0127 - mae: 0.0809 - rmse: 0.1048 - smape: 0.1919 - val_ia: 0.6754 - val_loss: 0.0035 - val_mae: 0.0431 - val_rmse: 0.0514 - val_smape: 0.1330

Epoch 38/256

4586/4586 - 82s - 18ms/step - ia: 0.9450 - loss: 0.0129 - mae: 0.0813 - rmse: 0.1056 - smape: 0.1903 - val_ia: 0.6706 - val_loss: 0.0034 - val_mae: 0.0430 - val_rmse: 0.0515 - val_smape: 0.1324

Epoch 39/256

4586/4586 - 87s - 19ms/step - ia: 0.9455 - loss: 0.0127 - mae: 0.0806 - rmse: 0.1049 - smape: 0.1885 - val_ia: 0.6793 - val_loss: 0.0034 - val_mae: 0.0429 - val_rmse: 0.0516 - val_smape: 0.1350

Epoch 40/256

4586/4586 - 86s - 19ms/step - ia: 0.9449 - loss: 0.0129 - mae: 0.0814 - rmse: 0.1055 - smape: 0.1910 - val_ia: 0.6771 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0522 - val_smape: 0.1385

Epoch 41/256

4586/4586 - 78s - 17ms/step - ia: 0.9455 - loss: 0.0127 - mae: 0.0809 - rmse: 0.1049 - smape: 0.1890 - val_ia: 0.6802 - val_loss: 0.0034 - val_mae: 0.0430 - val_rmse: 0.0511 - val_smape: 0.1260

Epoch 42/256

4586/4586 - 87s - 19ms/step - ia: 0.9457 - loss: 0.0126 - mae: 0.0805 - rmse: 0.1043 - smape: 0.1878 - val_ia: 0.6957 - val_loss: 0.0032 - val_mae: 0.0402 - val_rmse: 0.0491 - val_smape: 0.1213

Epoch 43/256

4586/4586 - 82s - 18ms/step - ia: 0.9459 - loss: 0.0126 - mae: 0.0802 - rmse: 0.1044 - smape: 0.1891 - val_ia: 0.7119 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0442 - val_smape: 0.1182

Epoch 44/256

4586/4586 - 85s - 19ms/step - ia: 0.9463 - loss: 0.0125 - mae: 0.0799 - rmse: 0.1041 - smape: 0.1881 - val_ia: 0.6568 - val_loss: 0.0040 - val_mae: 0.0471 - val_rmse: 0.0553 - val_smape: 0.1451

Epoch 45/256

4586/4586 - 90s - 20ms/step - ia: 0.9463 - loss: 0.0125 - mae: 0.0797 - rmse: 0.1038 - smape: 0.1870 - val_ia: 0.5792 - val_loss: 0.0069 - val_mae: 0.0676 - val_rmse: 0.0754 - val_smape: 0.1888

Epoch 46/256

4586/4586 - 86s - 19ms/step - ia: 0.9460 - loss: 0.0126 - mae: 0.0804 - rmse: 0.1045 - smape: 0.1886 - val_ia: 0.6419 - val_loss: 0.0044 - val_mae: 0.0513 - val_rmse: 0.0595 - val_smape: 0.1601

Epoch 47/256

4586/4586 - 75s - 16ms/step - ia: 0.9460 - loss: 0.0125 - mae: 0.0800 - rmse: 0.1040 - smape: 0.1875 - val_ia: 0.7000 - val_loss: 0.0029 - val_mae: 0.0380 - val_rmse: 0.0463 - val_smape: 0.1156

Epoch 48/256

4586/4586 - 72s - 16ms/step - ia: 0.9459 - loss: 0.0125 - mae: 0.0802 - rmse: 0.1042 - smape: 0.1863 - val_ia: 0.6030 - val_loss: 0.0051 - val_mae: 0.0566 - val_rmse: 0.0649 - val_smape: 0.1593

Epoch 49/256

4586/4586 - 78s - 17ms/step - ia: 0.9462 - loss: 0.0123 - mae: 0.0793 - rmse: 0.1031 - smape: 0.1865 - val_ia: 0.6803 - val_loss: 0.0034 - val_mae: 0.0424 - val_rmse: 0.0510 - val_smape: 0.1308

Epoch 50/256

4586/4586 - 81s - 18ms/step - ia: 0.9462 - loss: 0.0124 - mae: 0.0796 - rmse: 0.1036 - smape: 0.1860 - val_ia: 0.6560 - val_loss: 0.0040 - val_mae: 0.0479 - val_rmse: 0.0560 - val_smape: 0.1582

Epoch 51/256

4586/4586 - 77s - 17ms/step - ia: 0.9465 - loss: 0.0125 - mae: 0.0798 - rmse: 0.1039 - smape: 0.1853 - val_ia: 0.6755 - val_loss: 0.0037 - val_mae: 0.0436 - val_rmse: 0.0521 - val_smape: 0.1285

Epoch 52/256

4586/4586 - 72s - 16ms/step - ia: 0.9459 - loss: 0.0125 - mae: 0.0801 - rmse: 0.1042 - smape: 0.1891 - val_ia: 0.6535 - val_loss: 0.0042 - val_mae: 0.0474 - val_rmse: 0.0561 - val_smape: 0.1381

Epoch 53/256

4586/4586 - 91s - 20ms/step - ia: 0.9465 - loss: 0.0122 - mae: 0.0792 - rmse: 0.1027 - smape: 0.1852 - val_ia: 0.6993 - val_loss: 0.0030 - val_mae: 0.0384 - val_rmse: 0.0469 - val_smape: 0.1197

Epoch 54/256

4586/4586 - 74s - 16ms/step - ia: 0.9464 - loss: 0.0122 - mae: 0.0791 - rmse: 0.1030 - smape: 0.1856 - val_ia: 0.6776 - val_loss: 0.0035 - val_mae: 0.0433 - val_rmse: 0.0517 - val_smape: 0.1334

Epoch 55/256

4586/4586 - 76s - 17ms/step - ia: 0.9462 - loss: 0.0125 - mae: 0.0798 - rmse: 0.1039 - smape: 0.1828 - val_ia: 0.6845 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0507 - val_smape: 0.1305

Epoch 56/256

4586/4586 - 76s - 17ms/step - ia: 0.9465 - loss: 0.0122 - mae: 0.0791 - rmse: 0.1027 - smape: 0.1837 - val_ia: 0.5949 - val_loss: 0.0060 - val_mae: 0.0608 - val_rmse: 0.0690 - val_smape: 0.1597

Epoch 57/256

4586/4586 - 79s - 17ms/step - ia: 0.9468 - loss: 0.0123 - mae: 0.0791 - rmse: 0.1033 - smape: 0.1843 - val_ia: 0.6940 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0470 - val_smape: 0.1208

Epoch 58/256

4586/4586 - 74s - 16ms/step - ia: 0.9462 - loss: 0.0124 - mae: 0.0796 - rmse: 0.1038 - smape: 0.1853 - val_ia: 0.6781 - val_loss: 0.0032 - val_mae: 0.0422 - val_rmse: 0.0508 - val_smape: 0.1364

Epoch 58: early stopping

Restoring model weights from the end of the best epoch: 43.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:53 2s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 34%|███▍      | 17/50 [3:57:49<14:36:15, 1593.21s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 21s - 74ms/step - ia: 0.0640 - loss: 2.1892 - mae: 1.2266 - rmse: 1.4777 - smape: 1.7888 - val_ia: 0.1190 - val_loss: 1.9016 - val_mae: 1.1565 - val_rmse: 1.3672 - val_smape: 1.8135

Epoch 2/16

287/287 - 4s - 15ms/step - ia: 0.0723 - loss: 2.0349 - mae: 1.1819 - rmse: 1.4243 - smape: 1.7742 - val_ia: 0.1269 - val_loss: 1.7481 - val_mae: 1.1082 - val_rmse: 1.3107 - val_smape: 1.8128

Epoch 3/16

287/287 - 4s - 15ms/step - ia: 0.0861 - loss: 1.8749 - mae: 1.1329 - rmse: 1.3673 - smape: 1.7512 - val_ia: 0.1351 - val_loss: 1.6073 - val_mae: 1.0620 - val_rmse: 1.2566 - val_smape: 1.8112

Epoch 4/16

287/287 - 4s - 15ms/step - ia: 0.0999 - loss: 1.7350 - mae: 1.0878 - rmse: 1.3157 - smape: 1.7292 - val_ia: 0.1439 - val_loss: 1.4766 - val_mae: 1.0173 - val_rmse: 1.2042 - val_smape: 1.8056

Epoch 5/16

287/287 - 4s - 13ms/step - ia: 0.1183 - loss: 1.6170 - mae: 1.0480 - rmse: 1.2699 - smape: 1.7017 - val_ia: 0.1541 - val_loss: 1.3554 - val_mae: 0.9739 - val_rmse: 1.1535 - val_smape: 1.7932

Epoch 6/16

287/287 - 4s - 13ms/step - ia: 0.1397 - loss: 1.4879 - mae: 1.0048 - rmse: 1.2183 - smape: 1.6741 - val_ia: 0.1662 - val_loss: 1.2424 - val_mae: 0.9317 - val_rmse: 1.1042 - val_smape: 1.7758

Epoch 7/16

287/287 - 3s - 11ms/step - ia: 0.1654 - loss: 1.3704 - mae: 0.9625 - rmse: 1.1690 - smape: 1.6359 - val_ia: 0.1813 - val_loss: 1.1376 - val_mae: 0.8908 - val_rmse: 1.0563 - val_smape: 1.7560

Epoch 8/16

287/287 - 4s - 13ms/step - ia: 0.1917 - loss: 1.2723 - mae: 0.9254 - rmse: 1.1263 - smape: 1.6006 - val_ia: 0.2007 - val_loss: 1.0400 - val_mae: 0.8510 - val_rmse: 1.0098 - val_smape: 1.7361

Epoch 9/16

287/287 - 4s - 13ms/step - ia: 0.2227 - loss: 1.1689 - mae: 0.8856 - rmse: 1.0794 - smape: 1.5568 - val_ia: 0.2263 - val_loss: 0.9490 - val_mae: 0.8121 - val_rmse: 0.9643 - val_smape: 1.7050

Epoch 10/16

287/287 - 5s - 16ms/step - ia: 0.2561 - loss: 1.0816 - mae: 0.8497 - rmse: 1.0382 - smape: 1.5152 - val_ia: 0.2577 - val_loss: 0.8642 - val_mae: 0.7741 - val_rmse: 0.9199 - val_smape: 1.6548

Epoch 11/16

287/287 - 5s - 16ms/step - ia: 0.2911 - loss: 0.9962 - mae: 0.8138 - rmse: 0.9965 - smape: 1.4663 - val_ia: 0.2928 - val_loss: 0.7858 - val_mae: 0.7373 - val_rmse: 0.8769 - val_smape: 1.5838

Epoch 12/16

287/287 - 4s - 15ms/step - ia: 0.3270 - loss: 0.9191 - mae: 0.7786 - rmse: 0.9572 - smape: 1.4159 - val_ia: 0.3303 - val_loss: 0.7131 - val_mae: 0.7014 - val_rmse: 0.8351 - val_smape: 1.5018

Epoch 13/16

287/287 - 5s - 16ms/step - ia: 0.3617 - loss: 0.8520 - mae: 0.7464 - rmse: 0.9216 - smape: 1.3675 - val_ia: 0.3691 - val_loss: 0.6457 - val_mae: 0.6665 - val_rmse: 0.7943 - val_smape: 1.4167

Epoch 14/16

287/287 - 4s - 15ms/step - ia: 0.3968 - loss: 0.7803 - mae: 0.7141 - rmse: 0.8817 - smape: 1.3196 - val_ia: 0.4077 - val_loss: 0.5835 - val_mae: 0.6324 - val_rmse: 0.7548 - val_smape: 1.3336

Epoch 15/16

287/287 - 4s - 14ms/step - ia: 0.4310 - loss: 0.7215 - mae: 0.6848 - rmse: 0.8479 - smape: 1.2716 - val_ia: 0.4447 - val_loss: 0.5272 - val_mae: 0.5999 - val_rmse: 0.7171 - val_smape: 1.2551

Epoch 16/16

287/287 - 5s - 16ms/step - ia: 0.4646 - loss: 0.6674 - mae: 0.6557 - rmse: 0.8152 - smape: 1.2211 - val_ia: 0.4804 - val_loss: 0.4756 - val_mae: 0.5685 - val_rmse: 0.6809 - val_smape: 1.1810

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:41 1s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 36%|███▌      | 18/50 [3:59:17<10:08:29, 1140.93s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

574/574 - 20s - 34ms/step - ia: 0.8816 - loss: 0.0752 - mae: 0.1878 - rmse: 0.2391 - smape: 0.4312 - val_ia: 0.9154 - val_loss: 0.0112 - val_mae: 0.0795 - val_rmse: 0.1018 - val_smape: 0.2230

Epoch 2/16

574/574 - 7s - 12ms/step - ia: 0.9388 - loss: 0.0176 - mae: 0.0998 - rmse: 0.1309 - smape: 0.2620 - val_ia: 0.9181 - val_loss: 0.0101 - val_mae: 0.0788 - val_rmse: 0.0957 - val_smape: 0.2371

Epoch 3/16

574/574 - 7s - 12ms/step - ia: 0.9465 - loss: 0.0138 - mae: 0.0874 - rmse: 0.1157 - smape: 0.2323 - val_ia: 0.9407 - val_loss: 0.0061 - val_mae: 0.0583 - val_rmse: 0.0746 - val_smape: 0.1901

Epoch 4/16

574/574 - 7s - 12ms/step - ia: 0.9511 - loss: 0.0116 - mae: 0.0799 - rmse: 0.1061 - smape: 0.2151 - val_ia: 0.9486 - val_loss: 0.0050 - val_mae: 0.0514 - val_rmse: 0.0685 - val_smape: 0.1466

Epoch 5/16

574/574 - 7s - 12ms/step - ia: 0.9528 - loss: 0.0108 - mae: 0.0771 - rmse: 0.1025 - smape: 0.2067 - val_ia: 0.9368 - val_loss: 0.0062 - val_mae: 0.0601 - val_rmse: 0.0762 - val_smape: 0.1510

Epoch 6/16

574/574 - 6s - 11ms/step - ia: 0.9545 - loss: 0.0103 - mae: 0.0744 - rmse: 0.0999 - smape: 0.1986 - val_ia: 0.9556 - val_loss: 0.0036 - val_mae: 0.0431 - val_rmse: 0.0581 - val_smape: 0.1365

Epoch 7/16

574/574 - 6s - 10ms/step - ia: 0.9554 - loss: 0.0099 - mae: 0.0729 - rmse: 0.0979 - smape: 0.1961 - val_ia: 0.9448 - val_loss: 0.0055 - val_mae: 0.0558 - val_rmse: 0.0719 - val_smape: 0.1427

Epoch 8/16

574/574 - 6s - 11ms/step - ia: 0.9559 - loss: 0.0097 - mae: 0.0721 - rmse: 0.0967 - smape: 0.1949 - val_ia: 0.9490 - val_loss: 0.0042 - val_mae: 0.0479 - val_rmse: 0.0617 - val_smape: 0.1422

Epoch 9/16

574/574 - 6s - 11ms/step - ia: 0.9572 - loss: 0.0092 - mae: 0.0699 - rmse: 0.0942 - smape: 0.1869 - val_ia: 0.9393 - val_loss: 0.0059 - val_mae: 0.0596 - val_rmse: 0.0750 - val_smape: 0.1535

Epoch 10/16

574/574 - 6s - 10ms/step - ia: 0.9568 - loss: 0.0094 - mae: 0.0706 - rmse: 0.0955 - smape: 0.1896 - val_ia: 0.9500 - val_loss: 0.0043 - val_mae: 0.0498 - val_rmse: 0.0639 - val_smape: 0.1407

Epoch 11/16

574/574 - 6s - 11ms/step - ia: 0.9574 - loss: 0.0092 - mae: 0.0696 - rmse: 0.0941 - smape: 0.1862 - val_ia: 0.9579 - val_loss: 0.0032 - val_mae: 0.0402 - val_rmse: 0.0544 - val_smape: 0.1299

Epoch 12/16

574/574 - 7s - 12ms/step - ia: 0.9578 - loss: 0.0091 - mae: 0.0691 - rmse: 0.0936 - smape: 0.1845 - val_ia: 0.9600 - val_loss: 0.0031 - val_mae: 0.0391 - val_rmse: 0.0531 - val_smape: 0.1293

Epoch 13/16

574/574 - 7s - 12ms/step - ia: 0.9581 - loss: 0.0089 - mae: 0.0685 - rmse: 0.0924 - smape: 0.1835 - val_ia: 0.9591 - val_loss: 0.0032 - val_mae: 0.0401 - val_rmse: 0.0540 - val_smape: 0.1330

Epoch 14/16

574/574 - 7s - 13ms/step - ia: 0.9583 - loss: 0.0089 - mae: 0.0682 - rmse: 0.0924 - smape: 0.1821 - val_ia: 0.9547 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0560 - val_smape: 0.1382

Epoch 15/16

574/574 - 7s - 13ms/step - ia: 0.9591 - loss: 0.0086 - mae: 0.0669 - rmse: 0.0909 - smape: 0.1792 - val_ia: 0.9501 - val_loss: 0.0041 - val_mae: 0.0487 - val_rmse: 0.0626 - val_smape: 0.1454

Epoch 16/16

574/574 - 7s - 12ms/step - ia: 0.9591 - loss: 0.0086 - mae: 0.0669 - rmse: 0.0910 - smape: 0.1799 - val_ia: 0.9472 - val_loss: 0.0044 - val_mae: 0.0505 - val_rmse: 0.0624 - val_smape: 0.1642

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:21 501ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 38%|███▊      | 19/50 [4:01:18<7:11:18, 834.78s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4586/4586 - 114s - 25ms/step - ia: 0.6789 - loss: 0.3238 - mae: 0.4151 - rmse: 0.5054 - smape: 0.7824 - val_ia: 0.3626 - val_loss: 0.0573 - val_mae: 0.1853 - val_rmse: 0.1986 - val_smape: 0.4669

Epoch 2/32

4586/4586 - 141s - 31ms/step - ia: 0.8322 - loss: 0.0981 - mae: 0.2389 - rmse: 0.2985 - smape: 0.5220 - val_ia: 0.4032 - val_loss: 0.0450 - val_mae: 0.1603 - val_rmse: 0.1737 - val_smape: 0.4085

Epoch 3/32

4586/4586 - 80s - 17ms/step - ia: 0.8515 - loss: 0.0794 - mae: 0.2144 - rmse: 0.2685 - smape: 0.4769 - val_ia: 0.4218 - val_loss: 0.0378 - val_mae: 0.1465 - val_rmse: 0.1590 - val_smape: 0.3705

Epoch 4/32

4586/4586 - 79s - 17ms/step - ia: 0.8604 - loss: 0.0708 - mae: 0.2007 - rmse: 0.2528 - smape: 0.4469 - val_ia: 0.4507 - val_loss: 0.0300 - val_mae: 0.1295 - val_rmse: 0.1415 - val_smape: 0.3413

Epoch 5/32

4586/4586 - 79s - 17ms/step - ia: 0.8673 - loss: 0.0651 - mae: 0.1913 - rmse: 0.2414 - smape: 0.4253 - val_ia: 0.4587 - val_loss: 0.0256 - val_mae: 0.1195 - val_rmse: 0.1315 - val_smape: 0.2873

Epoch 6/32

4586/4586 - 79s - 17ms/step - ia: 0.8753 - loss: 0.0586 - mae: 0.1808 - rmse: 0.2285 - smape: 0.4025 - val_ia: 0.4774 - val_loss: 0.0224 - val_mae: 0.1112 - val_rmse: 0.1227 - val_smape: 0.2693

Epoch 7/32

4586/4586 - 73s - 16ms/step - ia: 0.8793 - loss: 0.0553 - mae: 0.1748 - rmse: 0.2216 - smape: 0.3909 - val_ia: 0.4973 - val_loss: 0.0192 - val_mae: 0.1018 - val_rmse: 0.1131 - val_smape: 0.2439

Epoch 8/32

4586/4586 - 80s - 17ms/step - ia: 0.8823 - loss: 0.0533 - mae: 0.1710 - rmse: 0.2167 - smape: 0.3803 - val_ia: 0.4959 - val_loss: 0.0194 - val_mae: 0.1021 - val_rmse: 0.1134 - val_smape: 0.2361

Epoch 9/32

4586/4586 - 81s - 18ms/step - ia: 0.8845 - loss: 0.0511 - mae: 0.1675 - rmse: 0.2127 - smape: 0.3732 - val_ia: 0.5181 - val_loss: 0.0160 - val_mae: 0.0917 - val_rmse: 0.1027 - val_smape: 0.2188

Epoch 10/32

4586/4586 - 79s - 17ms/step - ia: 0.8878 - loss: 0.0488 - mae: 0.1628 - rmse: 0.2075 - smape: 0.3646 - val_ia: 0.5232 - val_loss: 0.0154 - val_mae: 0.0906 - val_rmse: 0.1013 - val_smape: 0.2217

Epoch 11/32

4586/4586 - 82s - 18ms/step - ia: 0.8892 - loss: 0.0477 - mae: 0.1605 - rmse: 0.2046 - smape: 0.3594 - val_ia: 0.5304 - val_loss: 0.0145 - val_mae: 0.0860 - val_rmse: 0.0967 - val_smape: 0.2040

Epoch 12/32

4586/4586 - 82s - 18ms/step - ia: 0.8891 - loss: 0.0473 - mae: 0.1598 - rmse: 0.2038 - smape: 0.3576 - val_ia: 0.5378 - val_loss: 0.0142 - val_mae: 0.0849 - val_rmse: 0.0956 - val_smape: 0.2009

Epoch 13/32

4586/4586 - 80s - 17ms/step - ia: 0.8919 - loss: 0.0454 - mae: 0.1567 - rmse: 0.2000 - smape: 0.3560 - val_ia: 0.5472 - val_loss: 0.0132 - val_mae: 0.0811 - val_rmse: 0.0915 - val_smape: 0.1877

Epoch 14/32

4586/4586 - 81s - 18ms/step - ia: 0.8927 - loss: 0.0453 - mae: 0.1555 - rmse: 0.1988 - smape: 0.3501 - val_ia: 0.5189 - val_loss: 0.0182 - val_mae: 0.0972 - val_rmse: 0.1079 - val_smape: 0.2170

Epoch 15/32

4586/4586 - 81s - 18ms/step - ia: 0.8940 - loss: 0.0450 - mae: 0.1538 - rmse: 0.1978 - smape: 0.3458 - val_ia: 0.5343 - val_loss: 0.0171 - val_mae: 0.0919 - val_rmse: 0.1026 - val_smape: 0.2008

Epoch 16/32

4586/4586 - 85s - 19ms/step - ia: 0.8946 - loss: 0.0441 - mae: 0.1532 - rmse: 0.1961 - smape: 0.3432 - val_ia: 0.5490 - val_loss: 0.0143 - val_mae: 0.0849 - val_rmse: 0.0949 - val_smape: 0.1731

Epoch 17/32

4586/4586 - 84s - 18ms/step - ia: 0.8973 - loss: 0.0427 - mae: 0.1495 - rmse: 0.1925 - smape: 0.3366 - val_ia: 0.5506 - val_loss: 0.0142 - val_mae: 0.0847 - val_rmse: 0.0946 - val_smape: 0.1735

Epoch 18/32

4586/4586 - 83s - 18ms/step - ia: 0.8982 - loss: 0.0421 - mae: 0.1486 - rmse: 0.1913 - smape: 0.3342 - val_ia: 0.5548 - val_loss: 0.0139 - val_mae: 0.0838 - val_rmse: 0.0937 - val_smape: 0.1707

Epoch 19/32

4586/4586 - 83s - 18ms/step - ia: 0.8991 - loss: 0.0414 - mae: 0.1466 - rmse: 0.1893 - smape: 0.3292 - val_ia: 0.5656 - val_loss: 0.0122 - val_mae: 0.0780 - val_rmse: 0.0877 - val_smape: 0.1642

Epoch 20/32

4586/4586 - 85s - 18ms/step - ia: 0.8997 - loss: 0.0417 - mae: 0.1467 - rmse: 0.1896 - smape: 0.3243 - val_ia: 0.5311 - val_loss: 0.0179 - val_mae: 0.0949 - val_rmse: 0.1046 - val_smape: 0.1918

Epoch 21/32

4586/4586 - 81s - 18ms/step - ia: 0.9006 - loss: 0.0408 - mae: 0.1452 - rmse: 0.1874 - smape: 0.3237 - val_ia: 0.5513 - val_loss: 0.0153 - val_mae: 0.0874 - val_rmse: 0.0971 - val_smape: 0.1759

Epoch 22/32

4586/4586 - 87s - 19ms/step - ia: 0.9029 - loss: 0.0388 - mae: 0.1417 - rmse: 0.1831 - smape: 0.3169 - val_ia: 0.5290 - val_loss: 0.0187 - val_mae: 0.0979 - val_rmse: 0.1073 - val_smape: 0.1874

Epoch 23/32

4586/4586 - 146s - 32ms/step - ia: 0.9013 - loss: 0.0405 - mae: 0.1439 - rmse: 0.1865 - smape: 0.3170 - val_ia: 0.5258 - val_loss: 0.0159 - val_mae: 0.0939 - val_rmse: 0.1032 - val_smape: 0.2070

Epoch 24/32

4586/4586 - 89s - 19ms/step - ia: 0.9026 - loss: 0.0392 - mae: 0.1422 - rmse: 0.1838 - smape: 0.3135 - val_ia: 0.5520 - val_loss: 0.0177 - val_mae: 0.0916 - val_rmse: 0.1012 - val_smape: 0.1692

Epoch 25/32

4586/4586 - 88s - 19ms/step - ia: 0.9026 - loss: 0.0398 - mae: 0.1420 - rmse: 0.1849 - smape: 0.3154 - val_ia: 0.5216 - val_loss: 0.0180 - val_mae: 0.0982 - val_rmse: 0.1075 - val_smape: 0.1950

Epoch 26/32

4586/4586 - 143s - 31ms/step - ia: 0.9029 - loss: 0.0397 - mae: 0.1416 - rmse: 0.1844 - smape: 0.3114 - val_ia: 0.5664 - val_loss: 0.0147 - val_mae: 0.0836 - val_rmse: 0.0932 - val_smape: 0.1644

Epoch 27/32

4586/4586 - 89s - 19ms/step - ia: 0.9032 - loss: 0.0392 - mae: 0.1409 - rmse: 0.1832 - smape: 0.3111 - val_ia: 0.5472 - val_loss: 0.0152 - val_mae: 0.0889 - val_rmse: 0.0979 - val_smape: 0.1901

Epoch 28/32

4586/4586 - 85s - 19ms/step - ia: 0.9050 - loss: 0.0381 - mae: 0.1383 - rmse: 0.1805 - smape: 0.3034 - val_ia: 0.5711 - val_loss: 0.0135 - val_mae: 0.0805 - val_rmse: 0.0900 - val_smape: 0.1644

Epoch 29/32

4586/4586 - 77s - 17ms/step - ia: 0.9050 - loss: 0.0385 - mae: 0.1385 - rmse: 0.1808 - smape: 0.3039 - val_ia: 0.5207 - val_loss: 0.0184 - val_mae: 0.0988 - val_rmse: 0.1076 - val_smape: 0.1915

Epoch 30/32

4586/4586 - 81s - 18ms/step - ia: 0.9053 - loss: 0.0376 - mae: 0.1381 - rmse: 0.1794 - smape: 0.3028 - val_ia: 0.5499 - val_loss: 0.0159 - val_mae: 0.0892 - val_rmse: 0.0985 - val_smape: 0.1911

Epoch 31/32

4586/4586 - 82s - 18ms/step - ia: 0.9055 - loss: 0.0381 - mae: 0.1379 - rmse: 0.1804 - smape: 0.3010 - val_ia: 0.5615 - val_loss: 0.0135 - val_mae: 0.0823 - val_rmse: 0.0916 - val_smape: 0.1691

Epoch 32/32

4586/4586 - 84s - 18ms/step - ia: 0.9068 - loss: 0.0369 - mae: 0.1361 - rmse: 0.1776 - smape: 0.2996 - val_ia: 0.5463 - val_loss: 0.0167 - val_mae: 0.0912 - val_rmse: 0.1002 - val_smape: 0.1706

Restoring model weights from the end of the best epoch: 19.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9:58 4s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 9s 36ms/step

 40%|████      | 20/50 [4:48:51<12:00:20, 1440.70s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

144/144 - 56s - 389ms/step - ia: 0.2014 - loss: 0.8169 - mae: 0.7457 - rmse: 0.8993 - smape: 1.6040 - val_ia: 0.4432 - val_loss: 0.4961 - val_mae: 0.5829 - val_rmse: 0.6949 - val_smape: 1.1723

Epoch 2/64

144/144 - 21s - 143ms/step - ia: 0.7254 - loss: 0.2393 - mae: 0.3809 - rmse: 0.4760 - smape: 0.7527 - val_ia: 0.7548 - val_loss: 0.1916 - val_mae: 0.3418 - val_rmse: 0.4335 - val_smape: 0.7012

Epoch 3/64

144/144 - 20s - 138ms/step - ia: 0.8569 - loss: 0.0955 - mae: 0.2293 - rmse: 0.3069 - smape: 0.5308 - val_ia: 0.8068 - val_loss: 0.1040 - val_mae: 0.2588 - val_rmse: 0.3193 - val_smape: 0.6059

Epoch 4/64

144/144 - 22s - 150ms/step - ia: 0.8991 - loss: 0.0540 - mae: 0.1643 - rmse: 0.2311 - smape: 0.4245 - val_ia: 0.8645 - val_loss: 0.0540 - val_mae: 0.1728 - val_rmse: 0.2320 - val_smape: 0.4232

Epoch 5/64

144/144 - 19s - 131ms/step - ia: 0.9200 - loss: 0.0346 - mae: 0.1310 - rmse: 0.1852 - smape: 0.3643 - val_ia: 0.8851 - val_loss: 0.0366 - val_mae: 0.1419 - val_rmse: 0.1919 - val_smape: 0.3469

Epoch 6/64

144/144 - 20s - 138ms/step - ia: 0.9365 - loss: 0.0223 - mae: 0.1043 - rmse: 0.1485 - smape: 0.3009 - val_ia: 0.9073 - val_loss: 0.0245 - val_mae: 0.1185 - val_rmse: 0.1553 - val_smape: 0.3064

Epoch 7/64

144/144 - 19s - 134ms/step - ia: 0.9471 - loss: 0.0159 - mae: 0.0870 - rmse: 0.1252 - smape: 0.2517 - val_ia: 0.9223 - val_loss: 0.0179 - val_mae: 0.1004 - val_rmse: 0.1328 - val_smape: 0.2686

Epoch 8/64

144/144 - 15s - 103ms/step - ia: 0.9531 - loss: 0.0128 - mae: 0.0773 - rmse: 0.1123 - smape: 0.2238 - val_ia: 0.9280 - val_loss: 0.0152 - val_mae: 0.0923 - val_rmse: 0.1226 - val_smape: 0.2462

Epoch 9/64

144/144 - 14s - 99ms/step - ia: 0.9575 - loss: 0.0108 - mae: 0.0700 - rmse: 0.1033 - smape: 0.2068 - val_ia: 0.9332 - val_loss: 0.0132 - val_mae: 0.0860 - val_rmse: 0.1143 - val_smape: 0.2344

Epoch 10/64

144/144 - 15s - 105ms/step - ia: 0.9609 - loss: 0.0093 - mae: 0.0645 - rmse: 0.0956 - smape: 0.1937 - val_ia: 0.9421 - val_loss: 0.0102 - val_mae: 0.0743 - val_rmse: 0.1007 - val_smape: 0.2087

Epoch 11/64

144/144 - 20s - 137ms/step - ia: 0.9638 - loss: 0.0081 - mae: 0.0597 - rmse: 0.0888 - smape: 0.1830 - val_ia: 0.9462 - val_loss: 0.0087 - val_mae: 0.0683 - val_rmse: 0.0931 - val_smape: 0.1924

Epoch 12/64

144/144 - 19s - 131ms/step - ia: 0.9664 - loss: 0.0071 - mae: 0.0554 - rmse: 0.0829 - smape: 0.1750 - val_ia: 0.9414 - val_loss: 0.0101 - val_mae: 0.0773 - val_rmse: 0.0997 - val_smape: 0.2248

Epoch 13/64

144/144 - 17s - 116ms/step - ia: 0.9677 - loss: 0.0064 - mae: 0.0533 - rmse: 0.0790 - smape: 0.1697 - val_ia: 0.9517 - val_loss: 0.0070 - val_mae: 0.0620 - val_rmse: 0.0835 - val_smape: 0.1809

Epoch 14/64

144/144 - 16s - 114ms/step - ia: 0.9697 - loss: 0.0058 - mae: 0.0501 - rmse: 0.0747 - smape: 0.1635 - val_ia: 0.9559 - val_loss: 0.0057 - val_mae: 0.0547 - val_rmse: 0.0758 - val_smape: 0.1598

Epoch 15/64

144/144 - 20s - 141ms/step - ia: 0.9704 - loss: 0.0054 - mae: 0.0488 - rmse: 0.0722 - smape: 0.1607 - val_ia: 0.9538 - val_loss: 0.0062 - val_mae: 0.0594 - val_rmse: 0.0785 - val_smape: 0.1699

Epoch 16/64

144/144 - 17s - 118ms/step - ia: 0.9715 - loss: 0.0051 - mae: 0.0470 - rmse: 0.0696 - smape: 0.1555 - val_ia: 0.9585 - val_loss: 0.0051 - val_mae: 0.0517 - val_rmse: 0.0712 - val_smape: 0.1532

Epoch 17/64

144/144 - 16s - 113ms/step - ia: 0.9721 - loss: 0.0048 - mae: 0.0461 - rmse: 0.0681 - smape: 0.1538 - val_ia: 0.9544 - val_loss: 0.0058 - val_mae: 0.0553 - val_rmse: 0.0763 - val_smape: 0.1640

Epoch 18/64

144/144 - 17s - 115ms/step - ia: 0.9732 - loss: 0.0045 - mae: 0.0444 - rmse: 0.0658 - smape: 0.1498 - val_ia: 0.9585 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0702 - val_smape: 0.1493

Epoch 19/64

144/144 - 16s - 111ms/step - ia: 0.9737 - loss: 0.0044 - mae: 0.0436 - rmse: 0.0645 - smape: 0.1480 - val_ia: 0.9615 - val_loss: 0.0044 - val_mae: 0.0482 - val_rmse: 0.0663 - val_smape: 0.1426

Epoch 20/64

144/144 - 24s - 167ms/step - ia: 0.9741 - loss: 0.0042 - mae: 0.0428 - rmse: 0.0634 - smape: 0.1458 - val_ia: 0.9619 - val_loss: 0.0043 - val_mae: 0.0487 - val_rmse: 0.0657 - val_smape: 0.1440

Epoch 21/64

144/144 - 17s - 120ms/step - ia: 0.9743 - loss: 0.0041 - mae: 0.0424 - rmse: 0.0628 - smape: 0.1444 - val_ia: 0.9632 - val_loss: 0.0041 - val_mae: 0.0469 - val_rmse: 0.0640 - val_smape: 0.1385

Epoch 22/64

144/144 - 20s - 137ms/step - ia: 0.9751 - loss: 0.0040 - mae: 0.0411 - rmse: 0.0613 - smape: 0.1416 - val_ia: 0.9612 - val_loss: 0.0044 - val_mae: 0.0479 - val_rmse: 0.0660 - val_smape: 0.1438

Epoch 23/64

144/144 - 17s - 119ms/step - ia: 0.9749 - loss: 0.0039 - mae: 0.0414 - rmse: 0.0613 - smape: 0.1425 - val_ia: 0.9635 - val_loss: 0.0041 - val_mae: 0.0476 - val_rmse: 0.0638 - val_smape: 0.1374

Epoch 24/64

144/144 - 19s - 134ms/step - ia: 0.9752 - loss: 0.0039 - mae: 0.0409 - rmse: 0.0607 - smape: 0.1419 - val_ia: 0.9638 - val_loss: 0.0039 - val_mae: 0.0454 - val_rmse: 0.0625 - val_smape: 0.1371

Epoch 25/64

144/144 - 20s - 138ms/step - ia: 0.9756 - loss: 0.0038 - mae: 0.0403 - rmse: 0.0598 - smape: 0.1399 - val_ia: 0.9636 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0628 - val_smape: 0.1368

Epoch 26/64

144/144 - 20s - 140ms/step - ia: 0.9757 - loss: 0.0037 - mae: 0.0401 - rmse: 0.0594 - smape: 0.1393 - val_ia: 0.9608 - val_loss: 0.0044 - val_mae: 0.0484 - val_rmse: 0.0661 - val_smape: 0.1445

Epoch 27/64

144/144 - 19s - 130ms/step - ia: 0.9761 - loss: 0.0036 - mae: 0.0395 - rmse: 0.0587 - smape: 0.1380 - val_ia: 0.9673 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0585 - val_smape: 0.1285

Epoch 28/64

144/144 - 17s - 120ms/step - ia: 0.9767 - loss: 0.0035 - mae: 0.0386 - rmse: 0.0576 - smape: 0.1360 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0594 - val_smape: 0.1328

Epoch 29/64

144/144 - 21s - 144ms/step - ia: 0.9764 - loss: 0.0036 - mae: 0.0389 - rmse: 0.0579 - smape: 0.1374 - val_ia: 0.9677 - val_loss: 0.0035 - val_mae: 0.0426 - val_rmse: 0.0584 - val_smape: 0.1287

Epoch 30/64

144/144 - 20s - 142ms/step - ia: 0.9770 - loss: 0.0035 - mae: 0.0381 - rmse: 0.0569 - smape: 0.1351 - val_ia: 0.9667 - val_loss: 0.0037 - val_mae: 0.0445 - val_rmse: 0.0599 - val_smape: 0.1340

Epoch 31/64

144/144 - 22s - 150ms/step - ia: 0.9766 - loss: 0.0035 - mae: 0.0387 - rmse: 0.0574 - smape: 0.1364 - val_ia: 0.9654 - val_loss: 0.0039 - val_mae: 0.0467 - val_rmse: 0.0618 - val_smape: 0.1431

Epoch 32/64

144/144 - 21s - 144ms/step - ia: 0.9768 - loss: 0.0034 - mae: 0.0383 - rmse: 0.0568 - smape: 0.1356 - val_ia: 0.9665 - val_loss: 0.0035 - val_mae: 0.0423 - val_rmse: 0.0586 - val_smape: 0.1296

Epoch 33/64

144/144 - 21s - 144ms/step - ia: 0.9772 - loss: 0.0034 - mae: 0.0377 - rmse: 0.0564 - smape: 0.1342 - val_ia: 0.9680 - val_loss: 0.0033 - val_mae: 0.0413 - val_rmse: 0.0573 - val_smape: 0.1263

Epoch 34/64

144/144 - 19s - 131ms/step - ia: 0.9775 - loss: 0.0033 - mae: 0.0372 - rmse: 0.0559 - smape: 0.1337 - val_ia: 0.9582 - val_loss: 0.0052 - val_mae: 0.0570 - val_rmse: 0.0711 - val_smape: 0.1723

Epoch 35/64

144/144 - 18s - 124ms/step - ia: 0.9772 - loss: 0.0033 - mae: 0.0378 - rmse: 0.0562 - smape: 0.1343 - val_ia: 0.9693 - val_loss: 0.0032 - val_mae: 0.0400 - val_rmse: 0.0558 - val_smape: 0.1238

Epoch 36/64

144/144 - 20s - 142ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0367 - rmse: 0.0554 - smape: 0.1319 - val_ia: 0.9666 - val_loss: 0.0037 - val_mae: 0.0453 - val_rmse: 0.0600 - val_smape: 0.1423

Epoch 37/64

144/144 - 20s - 139ms/step - ia: 0.9777 - loss: 0.0033 - mae: 0.0369 - rmse: 0.0552 - smape: 0.1320 - val_ia: 0.9674 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0575 - val_smape: 0.1295

Epoch 38/64

144/144 - 21s - 143ms/step - ia: 0.9776 - loss: 0.0033 - mae: 0.0371 - rmse: 0.0554 - smape: 0.1328 - val_ia: 0.9713 - val_loss: 0.0029 - val_mae: 0.0382 - val_rmse: 0.0537 - val_smape: 0.1206

Epoch 39/64

144/144 - 18s - 122ms/step - ia: 0.9781 - loss: 0.0032 - mae: 0.0361 - rmse: 0.0545 - smape: 0.1309 - val_ia: 0.9713 - val_loss: 0.0030 - val_mae: 0.0386 - val_rmse: 0.0537 - val_smape: 0.1220

Epoch 40/64

144/144 - 15s - 107ms/step - ia: 0.9779 - loss: 0.0032 - mae: 0.0365 - rmse: 0.0547 - smape: 0.1313 - val_ia: 0.9616 - val_loss: 0.0042 - val_mae: 0.0485 - val_rmse: 0.0645 - val_smape: 0.1496

Epoch 41/64

144/144 - 15s - 106ms/step - ia: 0.9772 - loss: 0.0033 - mae: 0.0377 - rmse: 0.0556 - smape: 0.1337 - val_ia: 0.9705 - val_loss: 0.0030 - val_mae: 0.0392 - val_rmse: 0.0543 - val_smape: 0.1223

Epoch 42/64

144/144 - 19s - 131ms/step - ia: 0.9782 - loss: 0.0031 - mae: 0.0361 - rmse: 0.0542 - smape: 0.1306 - val_ia: 0.9580 - val_loss: 0.0051 - val_mae: 0.0569 - val_rmse: 0.0705 - val_smape: 0.1709

Epoch 43/64

144/144 - 15s - 101ms/step - ia: 0.9779 - loss: 0.0032 - mae: 0.0366 - rmse: 0.0547 - smape: 0.1312 - val_ia: 0.9652 - val_loss: 0.0039 - val_mae: 0.0469 - val_rmse: 0.0612 - val_smape: 0.1462

Epoch 44/64

144/144 - 14s - 96ms/step - ia: 0.9782 - loss: 0.0031 - mae: 0.0361 - rmse: 0.0542 - smape: 0.1300 - val_ia: 0.9717 - val_loss: 0.0029 - val_mae: 0.0379 - val_rmse: 0.0529 - val_smape: 0.1195

Epoch 45/64

144/144 - 15s - 107ms/step - ia: 0.9785 - loss: 0.0031 - mae: 0.0355 - rmse: 0.0538 - smape: 0.1292 - val_ia: 0.9718 - val_loss: 0.0029 - val_mae: 0.0381 - val_rmse: 0.0529 - val_smape: 0.1235

Epoch 46/64

144/144 - 16s - 111ms/step - ia: 0.9781 - loss: 0.0031 - mae: 0.0360 - rmse: 0.0542 - smape: 0.1303 - val_ia: 0.9701 - val_loss: 0.0031 - val_mae: 0.0405 - val_rmse: 0.0550 - val_smape: 0.1278

Epoch 47/64

144/144 - 17s - 120ms/step - ia: 0.9783 - loss: 0.0031 - mae: 0.0359 - rmse: 0.0540 - smape: 0.1300 - val_ia: 0.9719 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0526 - val_smape: 0.1200

Epoch 48/64

144/144 - 19s - 135ms/step - ia: 0.9785 - loss: 0.0031 - mae: 0.0356 - rmse: 0.0535 - smape: 0.1291 - val_ia: 0.9720 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0524 - val_smape: 0.1187

Epoch 49/64

144/144 - 19s - 131ms/step - ia: 0.9783 - loss: 0.0031 - mae: 0.0359 - rmse: 0.0536 - smape: 0.1298 - val_ia: 0.9728 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0514 - val_smape: 0.1175

Epoch 50/64

144/144 - 16s - 113ms/step - ia: 0.9785 - loss: 0.0031 - mae: 0.0355 - rmse: 0.0538 - smape: 0.1288 - val_ia: 0.9720 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0524 - val_smape: 0.1191

Epoch 51/64

144/144 - 16s - 112ms/step - ia: 0.9779 - loss: 0.0032 - mae: 0.0365 - rmse: 0.0544 - smape: 0.1312 - val_ia: 0.9722 - val_loss: 0.0028 - val_mae: 0.0376 - val_rmse: 0.0522 - val_smape: 0.1205

Epoch 52/64

144/144 - 17s - 115ms/step - ia: 0.9787 - loss: 0.0030 - mae: 0.0353 - rmse: 0.0529 - smape: 0.1286 - val_ia: 0.9652 - val_loss: 0.0037 - val_mae: 0.0455 - val_rmse: 0.0604 - val_smape: 0.1393

Epoch 53/64

144/144 - 16s - 111ms/step - ia: 0.9787 - loss: 0.0030 - mae: 0.0352 - rmse: 0.0532 - smape: 0.1282 - val_ia: 0.9722 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0518 - val_smape: 0.1179

Epoch 54/64

144/144 - 20s - 141ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0349 - rmse: 0.0528 - smape: 0.1276 - val_ia: 0.9724 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0519 - val_smape: 0.1186

Epoch 55/64

144/144 - 21s - 149ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0350 - rmse: 0.0526 - smape: 0.1274 - val_ia: 0.9594 - val_loss: 0.0048 - val_mae: 0.0552 - val_rmse: 0.0684 - val_smape: 0.1664

Epoch 56/64

144/144 - 20s - 140ms/step - ia: 0.9784 - loss: 0.0030 - mae: 0.0357 - rmse: 0.0533 - smape: 0.1294 - val_ia: 0.9722 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0522 - val_smape: 0.1197

Epoch 57/64

144/144 - 17s - 119ms/step - ia: 0.9788 - loss: 0.0030 - mae: 0.0350 - rmse: 0.0528 - smape: 0.1268 - val_ia: 0.9720 - val_loss: 0.0029 - val_mae: 0.0380 - val_rmse: 0.0525 - val_smape: 0.1200

Epoch 58/64

144/144 - 18s - 126ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0349 - rmse: 0.0527 - smape: 0.1279 - val_ia: 0.9634 - val_loss: 0.0041 - val_mae: 0.0493 - val_rmse: 0.0630 - val_smape: 0.1529

Epoch 59/64

144/144 - 19s - 133ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0350 - rmse: 0.0527 - smape: 0.1279 - val_ia: 0.9715 - val_loss: 0.0029 - val_mae: 0.0380 - val_rmse: 0.0528 - val_smape: 0.1196

Epoch 60/64

144/144 - 20s - 136ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0348 - rmse: 0.0525 - smape: 0.1271 - val_ia: 0.9703 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0540 - val_smape: 0.1261

Epoch 61/64

144/144 - 14s - 99ms/step - ia: 0.9789 - loss: 0.0030 - mae: 0.0349 - rmse: 0.0524 - smape: 0.1270 - val_ia: 0.9705 - val_loss: 0.0031 - val_mae: 0.0400 - val_rmse: 0.0543 - val_smape: 0.1287

Epoch 62/64

144/144 - 13s - 89ms/step - ia: 0.9791 - loss: 0.0029 - mae: 0.0346 - rmse: 0.0522 - smape: 0.1270 - val_ia: 0.9717 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0525 - val_smape: 0.1196

Epoch 63/64

144/144 - 20s - 137ms/step - ia: 0.9790 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0523 - smape: 0.1271 - val_ia: 0.9726 - val_loss: 0.0028 - val_mae: 0.0370 - val_rmse: 0.0517 - val_smape: 0.1179

Epoch 64/64

144/144 - 21s - 148ms/step - ia: 0.9791 - loss: 0.0029 - mae: 0.0346 - rmse: 0.0522 - smape: 0.1270 - val_ia: 0.9723 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0522 - val_smape: 0.1232

Epoch 64: early stopping

Restoring model weights from the end of the best epoch: 49.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:18 5s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 11s 39ms/step

 42%|████▏     | 21/50 [5:09:19<11:05:24, 1376.72s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 78s - 541ms/step - ia: 0.8999 - loss: 0.0931 - mae: 0.1445 - rmse: 0.1940 - smape: 0.3256 - val_ia: 0.9707 - val_loss: 0.0031 - val_mae: 0.0396 - val_rmse: 0.0550 - val_smape: 0.1332

Epoch 2/128

144/144 - 20s - 138ms/step - ia: 0.9756 - loss: 0.0036 - mae: 0.0404 - rmse: 0.0579 - smape: 0.1382 - val_ia: 0.9731 - val_loss: 0.0026 - val_mae: 0.0361 - val_rmse: 0.0507 - val_smape: 0.1144

Epoch 3/128

144/144 - 22s - 152ms/step - ia: 0.9755 - loss: 0.0036 - mae: 0.0405 - rmse: 0.0577 - smape: 0.1388 - val_ia: 0.9672 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0580 - val_smape: 0.1443

Epoch 4/128

144/144 - 21s - 148ms/step - ia: 0.9759 - loss: 0.0034 - mae: 0.0399 - rmse: 0.0571 - smape: 0.1356 - val_ia: 0.9721 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0520 - val_smape: 0.1242

Epoch 5/128

144/144 - 20s - 140ms/step - ia: 0.9752 - loss: 0.0036 - mae: 0.0409 - rmse: 0.0579 - smape: 0.1397 - val_ia: 0.9576 - val_loss: 0.0052 - val_mae: 0.0563 - val_rmse: 0.0692 - val_smape: 0.1816

Epoch 6/128

144/144 - 22s - 152ms/step - ia: 0.9747 - loss: 0.0036 - mae: 0.0417 - rmse: 0.0588 - smape: 0.1395 - val_ia: 0.9673 - val_loss: 0.0034 - val_mae: 0.0435 - val_rmse: 0.0579 - val_smape: 0.1494

Epoch 7/128

144/144 - 22s - 151ms/step - ia: 0.9749 - loss: 0.0036 - mae: 0.0414 - rmse: 0.0582 - smape: 0.1376 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0444 - val_rmse: 0.0598 - val_smape: 0.1339

Epoch 8/128

144/144 - 18s - 124ms/step - ia: 0.9762 - loss: 0.0034 - mae: 0.0394 - rmse: 0.0564 - smape: 0.1341 - val_ia: 0.9709 - val_loss: 0.0032 - val_mae: 0.0392 - val_rmse: 0.0557 - val_smape: 0.1182

Epoch 9/128

144/144 - 21s - 145ms/step - ia: 0.9773 - loss: 0.0031 - mae: 0.0375 - rmse: 0.0541 - smape: 0.1296 - val_ia: 0.9703 - val_loss: 0.0030 - val_mae: 0.0399 - val_rmse: 0.0543 - val_smape: 0.1183

Epoch 10/128

144/144 - 19s - 129ms/step - ia: 0.9758 - loss: 0.0034 - mae: 0.0400 - rmse: 0.0564 - smape: 0.1356 - val_ia: 0.9691 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0572 - val_smape: 0.1318

Epoch 11/128

144/144 - 17s - 119ms/step - ia: 0.9781 - loss: 0.0029 - mae: 0.0362 - rmse: 0.0526 - smape: 0.1280 - val_ia: 0.9646 - val_loss: 0.0040 - val_mae: 0.0472 - val_rmse: 0.0624 - val_smape: 0.1287

Epoch 12/128

144/144 - 16s - 114ms/step - ia: 0.9774 - loss: 0.0030 - mae: 0.0372 - rmse: 0.0533 - smape: 0.1292 - val_ia: 0.9673 - val_loss: 0.0037 - val_mae: 0.0449 - val_rmse: 0.0599 - val_smape: 0.1217

Epoch 13/128

144/144 - 17s - 120ms/step - ia: 0.9770 - loss: 0.0031 - mae: 0.0380 - rmse: 0.0542 - smape: 0.1308 - val_ia: 0.9562 - val_loss: 0.0053 - val_mae: 0.0577 - val_rmse: 0.0715 - val_smape: 0.1633

Epoch 14/128

144/144 - 18s - 122ms/step - ia: 0.9756 - loss: 0.0034 - mae: 0.0402 - rmse: 0.0568 - smape: 0.1335 - val_ia: 0.9627 - val_loss: 0.0042 - val_mae: 0.0494 - val_rmse: 0.0647 - val_smape: 0.1411

Epoch 15/128

144/144 - 23s - 157ms/step - ia: 0.9770 - loss: 0.0031 - mae: 0.0380 - rmse: 0.0540 - smape: 0.1315 - val_ia: 0.9621 - val_loss: 0.0044 - val_mae: 0.0521 - val_rmse: 0.0665 - val_smape: 0.1440

Epoch 16/128

144/144 - 23s - 162ms/step - ia: 0.9784 - loss: 0.0029 - mae: 0.0357 - rmse: 0.0519 - smape: 0.1261 - val_ia: 0.9691 - val_loss: 0.0031 - val_mae: 0.0396 - val_rmse: 0.0555 - val_smape: 0.1259

Epoch 17/128

144/144 - 22s - 152ms/step - ia: 0.9755 - loss: 0.0034 - mae: 0.0405 - rmse: 0.0568 - smape: 0.1332 - val_ia: 0.9632 - val_loss: 0.0042 - val_mae: 0.0489 - val_rmse: 0.0653 - val_smape: 0.1388

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:35 5s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step

 44%|████▍     | 22/50 [5:16:09<8:27:04, 1086.60s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 78s - 544ms/step - ia: 0.7901 - loss: 0.1906 - mae: 0.2944 - rmse: 0.3789 - smape: 0.5750 - val_ia: 0.8880 - val_loss: 0.0376 - val_mae: 0.1460 - val_rmse: 0.1833 - val_smape: 0.3497

Epoch 2/128

144/144 - 10s - 70ms/step - ia: 0.9055 - loss: 0.0435 - mae: 0.1544 - rmse: 0.2075 - smape: 0.3346 - val_ia: 0.8987 - val_loss: 0.0298 - val_mae: 0.1331 - val_rmse: 0.1646 - val_smape: 0.3247

Epoch 3/128

144/144 - 11s - 75ms/step - ia: 0.9160 - loss: 0.0350 - mae: 0.1373 - rmse: 0.1862 - smape: 0.3043 - val_ia: 0.8578 - val_loss: 0.0475 - val_mae: 0.1822 - val_rmse: 0.2119 - val_smape: 0.4059

Epoch 4/128

144/144 - 11s - 77ms/step - ia: 0.9206 - loss: 0.0317 - mae: 0.1300 - rmse: 0.1772 - smape: 0.2874 - val_ia: 0.8759 - val_loss: 0.0418 - val_mae: 0.1597 - val_rmse: 0.1946 - val_smape: 0.3385

Epoch 5/128

144/144 - 11s - 76ms/step - ia: 0.9233 - loss: 0.0297 - mae: 0.1257 - rmse: 0.1720 - smape: 0.2786 - val_ia: 0.8922 - val_loss: 0.0319 - val_mae: 0.1396 - val_rmse: 0.1704 - val_smape: 0.3177

Epoch 6/128

144/144 - 20s - 141ms/step - ia: 0.9240 - loss: 0.0288 - mae: 0.1242 - rmse: 0.1693 - smape: 0.2752 - val_ia: 0.8694 - val_loss: 0.0447 - val_mae: 0.1669 - val_rmse: 0.2035 - val_smape: 0.3366

Epoch 7/128

144/144 - 10s - 67ms/step - ia: 0.9252 - loss: 0.0283 - mae: 0.1225 - rmse: 0.1676 - smape: 0.2701 - val_ia: 0.8752 - val_loss: 0.0382 - val_mae: 0.1565 - val_rmse: 0.1884 - val_smape: 0.3183

Epoch 8/128

144/144 - 11s - 79ms/step - ia: 0.9265 - loss: 0.0273 - mae: 0.1205 - rmse: 0.1645 - smape: 0.2668 - val_ia: 0.8767 - val_loss: 0.0368 - val_mae: 0.1580 - val_rmse: 0.1843 - val_smape: 0.3286

Epoch 9/128

144/144 - 11s - 76ms/step - ia: 0.9284 - loss: 0.0260 - mae: 0.1174 - rmse: 0.1606 - smape: 0.2605 - val_ia: 0.8755 - val_loss: 0.0429 - val_mae: 0.1594 - val_rmse: 0.1948 - val_smape: 0.3273

Epoch 10/128

144/144 - 11s - 77ms/step - ia: 0.9270 - loss: 0.0271 - mae: 0.1195 - rmse: 0.1639 - smape: 0.2632 - val_ia: 0.8797 - val_loss: 0.0396 - val_mae: 0.1555 - val_rmse: 0.1909 - val_smape: 0.3660

Epoch 11/128

144/144 - 11s - 76ms/step - ia: 0.9290 - loss: 0.0256 - mae: 0.1164 - rmse: 0.1595 - smape: 0.2585 - val_ia: 0.8547 - val_loss: 0.0487 - val_mae: 0.1811 - val_rmse: 0.2163 - val_smape: 0.3362

Epoch 12/128

144/144 - 11s - 74ms/step - ia: 0.9299 - loss: 0.0254 - mae: 0.1151 - rmse: 0.1587 - smape: 0.2538 - val_ia: 0.8407 - val_loss: 0.0564 - val_mae: 0.1975 - val_rmse: 0.2331 - val_smape: 0.3653

Epoch 13/128

144/144 - 10s - 66ms/step - ia: 0.9305 - loss: 0.0247 - mae: 0.1139 - rmse: 0.1568 - smape: 0.2527 - val_ia: 0.8542 - val_loss: 0.0480 - val_mae: 0.1820 - val_rmse: 0.2125 - val_smape: 0.3537

Epoch 14/128

144/144 - 11s - 78ms/step - ia: 0.9308 - loss: 0.0244 - mae: 0.1135 - rmse: 0.1557 - smape: 0.2521 - val_ia: 0.8332 - val_loss: 0.0619 - val_mae: 0.2055 - val_rmse: 0.2429 - val_smape: 0.3857

Epoch 15/128

144/144 - 21s - 143ms/step - ia: 0.9298 - loss: 0.0251 - mae: 0.1149 - rmse: 0.1579 - smape: 0.2544 - val_ia: 0.8425 - val_loss: 0.0516 - val_mae: 0.1933 - val_rmse: 0.2219 - val_smape: 0.4044

Epoch 16/128

144/144 - 11s - 76ms/step - ia: 0.9310 - loss: 0.0245 - mae: 0.1131 - rmse: 0.1559 - smape: 0.2493 - val_ia: 0.8310 - val_loss: 0.0643 - val_mae: 0.2068 - val_rmse: 0.2436 - val_smape: 0.3866

Epoch 17/128

144/144 - 10s - 71ms/step - ia: 0.9298 - loss: 0.0249 - mae: 0.1151 - rmse: 0.1576 - smape: 0.2567 - val_ia: 0.8214 - val_loss: 0.0617 - val_mae: 0.2164 - val_rmse: 0.2457 - val_smape: 0.4384

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 7:03 3s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step

 46%|████▌     | 23/50 [5:20:49<6:20:04, 844.60s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 72s - 498ms/step - ia: 0.8112 - loss: 0.1812 - mae: 0.2648 - rmse: 0.3426 - smape: 0.5327 - val_ia: 0.9254 - val_loss: 0.0164 - val_mae: 0.0999 - val_rmse: 0.1267 - val_smape: 0.2560

Epoch 2/128

144/144 - 19s - 132ms/step - ia: 0.9207 - loss: 0.0313 - mae: 0.1300 - rmse: 0.1761 - smape: 0.2889 - val_ia: 0.9348 - val_loss: 0.0122 - val_mae: 0.0860 - val_rmse: 0.1090 - val_smape: 0.2065

Epoch 3/128

144/144 - 17s - 119ms/step - ia: 0.9261 - loss: 0.0276 - mae: 0.1212 - rmse: 0.1655 - smape: 0.2703 - val_ia: 0.9067 - val_loss: 0.0236 - val_mae: 0.1213 - val_rmse: 0.1465 - val_smape: 0.2623

Epoch 4/128

144/144 - 18s - 128ms/step - ia: 0.9290 - loss: 0.0255 - mae: 0.1164 - rmse: 0.1590 - smape: 0.2600 - val_ia: 0.9291 - val_loss: 0.0150 - val_mae: 0.0913 - val_rmse: 0.1139 - val_smape: 0.2203

Epoch 5/128

144/144 - 18s - 128ms/step - ia: 0.9301 - loss: 0.0249 - mae: 0.1147 - rmse: 0.1570 - smape: 0.2550 - val_ia: 0.9228 - val_loss: 0.0187 - val_mae: 0.0990 - val_rmse: 0.1281 - val_smape: 0.2022

Epoch 6/128

144/144 - 17s - 121ms/step - ia: 0.9299 - loss: 0.0250 - mae: 0.1150 - rmse: 0.1574 - smape: 0.2589 - val_ia: 0.9401 - val_loss: 0.0116 - val_mae: 0.0778 - val_rmse: 0.1031 - val_smape: 0.1825

Epoch 7/128

144/144 - 18s - 128ms/step - ia: 0.9331 - loss: 0.0233 - mae: 0.1099 - rmse: 0.1522 - smape: 0.2426 - val_ia: 0.9288 - val_loss: 0.0155 - val_mae: 0.0924 - val_rmse: 0.1161 - val_smape: 0.2055

Epoch 8/128

144/144 - 19s - 130ms/step - ia: 0.9334 - loss: 0.0228 - mae: 0.1094 - rmse: 0.1502 - smape: 0.2452 - val_ia: 0.9436 - val_loss: 0.0099 - val_mae: 0.0741 - val_rmse: 0.0962 - val_smape: 0.1698

Epoch 9/128

144/144 - 20s - 141ms/step - ia: 0.9345 - loss: 0.0222 - mae: 0.1075 - rmse: 0.1484 - smape: 0.2411 - val_ia: 0.9473 - val_loss: 0.0095 - val_mae: 0.0689 - val_rmse: 0.0913 - val_smape: 0.1661

Epoch 10/128

144/144 - 15s - 103ms/step - ia: 0.9347 - loss: 0.0219 - mae: 0.1072 - rmse: 0.1476 - smape: 0.2402 - val_ia: 0.9209 - val_loss: 0.0199 - val_mae: 0.1020 - val_rmse: 0.1309 - val_smape: 0.2071

Epoch 11/128

144/144 - 15s - 105ms/step - ia: 0.9359 - loss: 0.0213 - mae: 0.1054 - rmse: 0.1453 - smape: 0.2360 - val_ia: 0.9405 - val_loss: 0.0109 - val_mae: 0.0783 - val_rmse: 0.0980 - val_smape: 0.1989

Epoch 12/128

144/144 - 15s - 106ms/step - ia: 0.9350 - loss: 0.0215 - mae: 0.1069 - rmse: 0.1463 - smape: 0.2399 - val_ia: 0.9322 - val_loss: 0.0129 - val_mae: 0.0908 - val_rmse: 0.1120 - val_smape: 0.2701

Epoch 13/128

144/144 - 15s - 105ms/step - ia: 0.9347 - loss: 0.0219 - mae: 0.1072 - rmse: 0.1473 - smape: 0.2415 - val_ia: 0.9475 - val_loss: 0.0089 - val_mae: 0.0677 - val_rmse: 0.0887 - val_smape: 0.1660

Epoch 14/128

144/144 - 14s - 98ms/step - ia: 0.9346 - loss: 0.0222 - mae: 0.1074 - rmse: 0.1483 - smape: 0.2406 - val_ia: 0.9233 - val_loss: 0.0171 - val_mae: 0.1004 - val_rmse: 0.1249 - val_smape: 0.2040

Epoch 15/128

144/144 - 19s - 129ms/step - ia: 0.9368 - loss: 0.0207 - mae: 0.1038 - rmse: 0.1434 - smape: 0.2325 - val_ia: 0.9196 - val_loss: 0.0186 - val_mae: 0.1052 - val_rmse: 0.1290 - val_smape: 0.2243

Epoch 16/128

144/144 - 17s - 115ms/step - ia: 0.9358 - loss: 0.0214 - mae: 0.1055 - rmse: 0.1454 - smape: 0.2379 - val_ia: 0.9275 - val_loss: 0.0166 - val_mae: 0.0944 - val_rmse: 0.1213 - val_smape: 0.1809

Epoch 17/128

144/144 - 15s - 105ms/step - ia: 0.9373 - loss: 0.0202 - mae: 0.1029 - rmse: 0.1414 - smape: 0.2324 - val_ia: 0.9482 - val_loss: 0.0078 - val_mae: 0.0666 - val_rmse: 0.0838 - val_smape: 0.1650

Epoch 18/128

144/144 - 17s - 119ms/step - ia: 0.9362 - loss: 0.0210 - mae: 0.1048 - rmse: 0.1444 - smape: 0.2354 - val_ia: 0.9203 - val_loss: 0.0207 - val_mae: 0.1047 - val_rmse: 0.1361 - val_smape: 0.1959

Epoch 19/128

144/144 - 16s - 114ms/step - ia: 0.9362 - loss: 0.0209 - mae: 0.1045 - rmse: 0.1441 - smape: 0.2363 - val_ia: 0.9220 - val_loss: 0.0150 - val_mae: 0.1008 - val_rmse: 0.1211 - val_smape: 0.2312

Epoch 20/128

144/144 - 19s - 129ms/step - ia: 0.9370 - loss: 0.0204 - mae: 0.1033 - rmse: 0.1422 - smape: 0.2345 - val_ia: 0.9126 - val_loss: 0.0203 - val_mae: 0.1151 - val_rmse: 0.1395 - val_smape: 0.2319

Epoch 21/128

144/144 - 17s - 115ms/step - ia: 0.9370 - loss: 0.0205 - mae: 0.1035 - rmse: 0.1427 - smape: 0.2320 - val_ia: 0.9272 - val_loss: 0.0150 - val_mae: 0.0951 - val_rmse: 0.1173 - val_smape: 0.1920

Epoch 22/128

144/144 - 22s - 155ms/step - ia: 0.9366 - loss: 0.0206 - mae: 0.1041 - rmse: 0.1431 - smape: 0.2334 - val_ia: 0.9139 - val_loss: 0.0203 - val_mae: 0.1128 - val_rmse: 0.1365 - val_smape: 0.2215

Epoch 23/128

144/144 - 18s - 128ms/step - ia: 0.9376 - loss: 0.0204 - mae: 0.1025 - rmse: 0.1423 - smape: 0.2294 - val_ia: 0.9068 - val_loss: 0.0238 - val_mae: 0.1223 - val_rmse: 0.1481 - val_smape: 0.2484

Epoch 24/128

144/144 - 16s - 111ms/step - ia: 0.9376 - loss: 0.0202 - mae: 0.1025 - rmse: 0.1415 - smape: 0.2317 - val_ia: 0.9463 - val_loss: 0.0092 - val_mae: 0.0714 - val_rmse: 0.0907 - val_smape: 0.1800

Epoch 25/128

144/144 - 16s - 111ms/step - ia: 0.9372 - loss: 0.0204 - mae: 0.1031 - rmse: 0.1421 - smape: 0.2338 - val_ia: 0.9158 - val_loss: 0.0191 - val_mae: 0.1101 - val_rmse: 0.1362 - val_smape: 0.2293

Epoch 26/128

144/144 - 23s - 158ms/step - ia: 0.9363 - loss: 0.0208 - mae: 0.1047 - rmse: 0.1438 - smape: 0.2357 - val_ia: 0.9232 - val_loss: 0.0160 - val_mae: 0.1020 - val_rmse: 0.1231 - val_smape: 0.2181

Epoch 27/128

144/144 - 18s - 125ms/step - ia: 0.9360 - loss: 0.0210 - mae: 0.1052 - rmse: 0.1445 - smape: 0.2357 - val_ia: 0.9253 - val_loss: 0.0160 - val_mae: 0.0985 - val_rmse: 0.1225 - val_smape: 0.1983

Epoch 28/128

144/144 - 14s - 97ms/step - ia: 0.9376 - loss: 0.0202 - mae: 0.1027 - rmse: 0.1416 - smape: 0.2317 - val_ia: 0.9145 - val_loss: 0.0188 - val_mae: 0.1124 - val_rmse: 0.1349 - val_smape: 0.2527

Epoch 29/128

144/144 - 12s - 80ms/step - ia: 0.9357 - loss: 0.0211 - mae: 0.1055 - rmse: 0.1448 - smape: 0.2392 - val_ia: 0.9047 - val_loss: 0.0215 - val_mae: 0.1239 - val_rmse: 0.1449 - val_smape: 0.2658

Epoch 30/128

144/144 - 16s - 113ms/step - ia: 0.9369 - loss: 0.0205 - mae: 0.1037 - rmse: 0.1425 - smape: 0.2335 - val_ia: 0.9024 - val_loss: 0.0246 - val_mae: 0.1271 - val_rmse: 0.1532 - val_smape: 0.2403

Epoch 31/128

144/144 - 19s - 129ms/step - ia: 0.9388 - loss: 0.0195 - mae: 0.1005 - rmse: 0.1391 - smape: 0.2260 - val_ia: 0.9320 - val_loss: 0.0114 - val_mae: 0.0897 - val_rmse: 0.1060 - val_smape: 0.1962

Epoch 32/128

144/144 - 18s - 126ms/step - ia: 0.9387 - loss: 0.0195 - mae: 0.1007 - rmse: 0.1393 - smape: 0.2277 - val_ia: 0.9292 - val_loss: 0.0142 - val_mae: 0.0913 - val_rmse: 0.1129 - val_smape: 0.1935

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8:16 3s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step

 48%|████▊     | 24/50 [5:31:03<5:35:58, 775.31s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 30s - 13ms/step - ia: 0.9650 - loss: 0.0093 - mae: 0.0543 - rmse: 0.0721 - smape: 0.1676 - val_ia: 0.8146 - val_loss: 0.0042 - val_mae: 0.0458 - val_rmse: 0.0571 - val_smape: 0.1410

Epoch 2/128

2293/2293 - 16s - 7ms/step - ia: 0.9736 - loss: 0.0037 - mae: 0.0412 - rmse: 0.0551 - smape: 0.1406 - val_ia: 0.8332 - val_loss: 0.0034 - val_mae: 0.0418 - val_rmse: 0.0529 - val_smape: 0.1378

Epoch 3/128

2293/2293 - 20s - 9ms/step - ia: 0.9744 - loss: 0.0035 - mae: 0.0400 - rmse: 0.0536 - smape: 0.1376 - val_ia: 0.8229 - val_loss: 0.0038 - val_mae: 0.0434 - val_rmse: 0.0553 - val_smape: 0.1277

Epoch 4/128

2293/2293 - 14s - 6ms/step - ia: 0.9750 - loss: 0.0034 - mae: 0.0389 - rmse: 0.0522 - smape: 0.1359 - val_ia: 0.8438 - val_loss: 0.0030 - val_mae: 0.0379 - val_rmse: 0.0489 - val_smape: 0.1171

Epoch 5/128

2293/2293 - 11s - 5ms/step - ia: 0.9756 - loss: 0.0033 - mae: 0.0380 - rmse: 0.0513 - smape: 0.1328 - val_ia: 0.8234 - val_loss: 0.0031 - val_mae: 0.0413 - val_rmse: 0.0518 - val_smape: 0.1368

Epoch 6/128

2293/2293 - 23s - 10ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0374 - rmse: 0.0505 - smape: 0.1307 - val_ia: 0.8411 - val_loss: 0.0031 - val_mae: 0.0388 - val_rmse: 0.0502 - val_smape: 0.1288

Epoch 7/128

2293/2293 - 14s - 6ms/step - ia: 0.9765 - loss: 0.0030 - mae: 0.0366 - rmse: 0.0494 - smape: 0.1292 - val_ia: 0.8560 - val_loss: 0.0025 - val_mae: 0.0344 - val_rmse: 0.0450 - val_smape: 0.1089

Epoch 8/128

2293/2293 - 14s - 6ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0496 - smape: 0.1289 - val_ia: 0.7555 - val_loss: 0.0051 - val_mae: 0.0579 - val_rmse: 0.0675 - val_smape: 0.1751

Epoch 9/128

2293/2293 - 16s - 7ms/step - ia: 0.9766 - loss: 0.0030 - mae: 0.0364 - rmse: 0.0492 - smape: 0.1295 - val_ia: 0.8396 - val_loss: 0.0031 - val_mae: 0.0395 - val_rmse: 0.0501 - val_smape: 0.1320

Epoch 10/128

2293/2293 - 14s - 6ms/step - ia: 0.9767 - loss: 0.0030 - mae: 0.0363 - rmse: 0.0492 - smape: 0.1290 - val_ia: 0.8499 - val_loss: 0.0024 - val_mae: 0.0345 - val_rmse: 0.0448 - val_smape: 0.1093

Epoch 11/128

2293/2293 - 14s - 6ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0361 - rmse: 0.0489 - smape: 0.1292 - val_ia: 0.8411 - val_loss: 0.0028 - val_mae: 0.0373 - val_rmse: 0.0479 - val_smape: 0.1195

Epoch 12/128

2293/2293 - 16s - 7ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0488 - smape: 0.1284 - val_ia: 0.8515 - val_loss: 0.0029 - val_mae: 0.0371 - val_rmse: 0.0478 - val_smape: 0.1164

Epoch 13/128

2293/2293 - 21s - 9ms/step - ia: 0.9770 - loss: 0.0029 - mae: 0.0358 - rmse: 0.0485 - smape: 0.1268 - val_ia: 0.8541 - val_loss: 0.0027 - val_mae: 0.0357 - val_rmse: 0.0464 - val_smape: 0.1130

Epoch 14/128

2293/2293 - 16s - 7ms/step - ia: 0.9770 - loss: 0.0029 - mae: 0.0358 - rmse: 0.0485 - smape: 0.1278 - val_ia: 0.8245 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0510 - val_smape: 0.1263

Epoch 15/128

2293/2293 - 15s - 7ms/step - ia: 0.9773 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0480 - smape: 0.1264 - val_ia: 0.8287 - val_loss: 0.0034 - val_mae: 0.0419 - val_rmse: 0.0532 - val_smape: 0.1421

Epoch 16/128

2293/2293 - 13s - 6ms/step - ia: 0.9774 - loss: 0.0029 - mae: 0.0352 - rmse: 0.0477 - smape: 0.1264 - val_ia: 0.8417 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0488 - val_smape: 0.1100

Epoch 17/128

2293/2293 - 16s - 7ms/step - ia: 0.9773 - loss: 0.0029 - mae: 0.0355 - rmse: 0.0478 - smape: 0.1270 - val_ia: 0.8489 - val_loss: 0.0030 - val_mae: 0.0371 - val_rmse: 0.0485 - val_smape: 0.1142

Epoch 18/128

2293/2293 - 20s - 9ms/step - ia: 0.9773 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0479 - smape: 0.1272 - val_ia: 0.8528 - val_loss: 0.0027 - val_mae: 0.0354 - val_rmse: 0.0461 - val_smape: 0.1077

Epoch 19/128

2293/2293 - 16s - 7ms/step - ia: 0.9775 - loss: 0.0028 - mae: 0.0350 - rmse: 0.0475 - smape: 0.1259 - val_ia: 0.8408 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0474 - val_smape: 0.1135

Epoch 20/128

2293/2293 - 16s - 7ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0477 - smape: 0.1267 - val_ia: 0.8326 - val_loss: 0.0032 - val_mae: 0.0403 - val_rmse: 0.0510 - val_smape: 0.1277

Epoch 21/128

2293/2293 - 16s - 7ms/step - ia: 0.9776 - loss: 0.0028 - mae: 0.0350 - rmse: 0.0475 - smape: 0.1261 - val_ia: 0.8066 - val_loss: 0.0040 - val_mae: 0.0454 - val_rmse: 0.0564 - val_smape: 0.1354

Epoch 22/128

2293/2293 - 15s - 7ms/step - ia: 0.9776 - loss: 0.0028 - mae: 0.0349 - rmse: 0.0475 - smape: 0.1261 - val_ia: 0.8096 - val_loss: 0.0041 - val_mae: 0.0454 - val_rmse: 0.0569 - val_smape: 0.1294

Epoch 23/128

2293/2293 - 13s - 6ms/step - ia: 0.9775 - loss: 0.0028 - mae: 0.0350 - rmse: 0.0474 - smape: 0.1274 - val_ia: 0.8172 - val_loss: 0.0035 - val_mae: 0.0423 - val_rmse: 0.0533 - val_smape: 0.1299

Epoch 24/128

2293/2293 - 13s - 6ms/step - ia: 0.9778 - loss: 0.0028 - mae: 0.0345 - rmse: 0.0471 - smape: 0.1249 - val_ia: 0.8287 - val_loss: 0.0038 - val_mae: 0.0425 - val_rmse: 0.0539 - val_smape: 0.1321

Epoch 25/128

2293/2293 - 13s - 6ms/step - ia: 0.9777 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0474 - smape: 0.1263 - val_ia: 0.8359 - val_loss: 0.0031 - val_mae: 0.0387 - val_rmse: 0.0496 - val_smape: 0.1228

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:29 551ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 50%|█████     | 25/50 [5:37:51<4:37:11, 665.27s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 46s - 319ms/step - ia: 0.8380 - loss: 0.1230 - mae: 0.2483 - rmse: 0.3228 - smape: 0.4915 - val_ia: 0.8666 - val_loss: 0.0432 - val_mae: 0.1699 - val_rmse: 0.2036 - val_smape: 0.3643

Epoch 2/128

144/144 - 10s - 68ms/step - ia: 0.9048 - loss: 0.0447 - mae: 0.1554 - rmse: 0.2109 - smape: 0.3254 - val_ia: 0.8375 - val_loss: 0.0533 - val_mae: 0.2016 - val_rmse: 0.2276 - val_smape: 0.4385

Epoch 3/128

144/144 - 11s - 78ms/step - ia: 0.9102 - loss: 0.0400 - mae: 0.1466 - rmse: 0.1996 - smape: 0.3108 - val_ia: 0.8894 - val_loss: 0.0258 - val_mae: 0.1403 - val_rmse: 0.1595 - val_smape: 0.3508

Epoch 4/128

144/144 - 9s - 61ms/step - ia: 0.9147 - loss: 0.0363 - mae: 0.1391 - rmse: 0.1899 - smape: 0.3011 - val_ia: 0.9191 - val_loss: 0.0171 - val_mae: 0.1064 - val_rmse: 0.1296 - val_smape: 0.2675

Epoch 5/128

144/144 - 10s - 69ms/step - ia: 0.9148 - loss: 0.0362 - mae: 0.1391 - rmse: 0.1899 - smape: 0.3005 - val_ia: 0.9141 - val_loss: 0.0238 - val_mae: 0.1116 - val_rmse: 0.1503 - val_smape: 0.2596

Epoch 6/128

144/144 - 11s - 75ms/step - ia: 0.9176 - loss: 0.0343 - mae: 0.1347 - rmse: 0.1847 - smape: 0.2878 - val_ia: 0.8911 - val_loss: 0.0277 - val_mae: 0.1414 - val_rmse: 0.1648 - val_smape: 0.3494

Epoch 7/128

144/144 - 11s - 74ms/step - ia: 0.9172 - loss: 0.0345 - mae: 0.1351 - rmse: 0.1855 - smape: 0.2919 - val_ia: 0.8995 - val_loss: 0.0253 - val_mae: 0.1301 - val_rmse: 0.1567 - val_smape: 0.2615

Epoch 8/128

144/144 - 10s - 67ms/step - ia: 0.9172 - loss: 0.0344 - mae: 0.1352 - rmse: 0.1849 - smape: 0.2900 - val_ia: 0.9143 - val_loss: 0.0187 - val_mae: 0.1110 - val_rmse: 0.1352 - val_smape: 0.2110

Epoch 9/128

144/144 - 11s - 74ms/step - ia: 0.9191 - loss: 0.0330 - mae: 0.1322 - rmse: 0.1812 - smape: 0.2814 - val_ia: 0.8871 - val_loss: 0.0309 - val_mae: 0.1414 - val_rmse: 0.1729 - val_smape: 0.2731

Epoch 10/128

144/144 - 11s - 73ms/step - ia: 0.9201 - loss: 0.0324 - mae: 0.1305 - rmse: 0.1796 - smape: 0.2792 - val_ia: 0.9326 - val_loss: 0.0126 - val_mae: 0.0889 - val_rmse: 0.1117 - val_smape: 0.2479

Epoch 11/128

144/144 - 10s - 70ms/step - ia: 0.9191 - loss: 0.0329 - mae: 0.1322 - rmse: 0.1809 - smape: 0.2860 - val_ia: 0.8921 - val_loss: 0.0270 - val_mae: 0.1393 - val_rmse: 0.1621 - val_smape: 0.2782

Epoch 12/128

144/144 - 11s - 74ms/step - ia: 0.9190 - loss: 0.0332 - mae: 0.1323 - rmse: 0.1818 - smape: 0.2861 - val_ia: 0.9066 - val_loss: 0.0210 - val_mae: 0.1241 - val_rmse: 0.1425 - val_smape: 0.3348

Epoch 13/128

144/144 - 9s - 66ms/step - ia: 0.9202 - loss: 0.0326 - mae: 0.1305 - rmse: 0.1799 - smape: 0.2781 - val_ia: 0.8546 - val_loss: 0.0441 - val_mae: 0.1793 - val_rmse: 0.2087 - val_smape: 0.3463

Epoch 14/128

144/144 - 9s - 64ms/step - ia: 0.9205 - loss: 0.0321 - mae: 0.1298 - rmse: 0.1788 - smape: 0.2768 - val_ia: 0.8817 - val_loss: 0.0337 - val_mae: 0.1509 - val_rmse: 0.1812 - val_smape: 0.2838

Epoch 15/128

144/144 - 11s - 76ms/step - ia: 0.9216 - loss: 0.0315 - mae: 0.1281 - rmse: 0.1771 - smape: 0.2748 - val_ia: 0.8613 - val_loss: 0.0447 - val_mae: 0.1731 - val_rmse: 0.2072 - val_smape: 0.3377

Epoch 16/128

144/144 - 11s - 74ms/step - ia: 0.9209 - loss: 0.0320 - mae: 0.1294 - rmse: 0.1783 - smape: 0.2748 - val_ia: 0.9185 - val_loss: 0.0205 - val_mae: 0.1070 - val_rmse: 0.1393 - val_smape: 0.2175

Epoch 17/128

144/144 - 20s - 140ms/step - ia: 0.9215 - loss: 0.0317 - mae: 0.1283 - rmse: 0.1777 - smape: 0.2698 - val_ia: 0.8426 - val_loss: 0.0530 - val_mae: 0.1947 - val_rmse: 0.2271 - val_smape: 0.3695

Epoch 18/128

144/144 - 9s - 62ms/step - ia: 0.9215 - loss: 0.0315 - mae: 0.1284 - rmse: 0.1770 - smape: 0.2746 - val_ia: 0.8616 - val_loss: 0.0411 - val_mae: 0.1736 - val_rmse: 0.2000 - val_smape: 0.3492

Epoch 19/128

144/144 - 11s - 75ms/step - ia: 0.9208 - loss: 0.0320 - mae: 0.1294 - rmse: 0.1784 - smape: 0.2754 - val_ia: 0.8751 - val_loss: 0.0396 - val_mae: 0.1570 - val_rmse: 0.1965 - val_smape: 0.2734

Epoch 20/128

144/144 - 11s - 74ms/step - ia: 0.9224 - loss: 0.0310 - mae: 0.1269 - rmse: 0.1754 - smape: 0.2710 - val_ia: 0.8829 - val_loss: 0.0339 - val_mae: 0.1482 - val_rmse: 0.1815 - val_smape: 0.3010

Epoch 21/128

144/144 - 11s - 73ms/step - ia: 0.9226 - loss: 0.0306 - mae: 0.1265 - rmse: 0.1742 - smape: 0.2705 - val_ia: 0.8764 - val_loss: 0.0444 - val_mae: 0.1532 - val_rmse: 0.2067 - val_smape: 0.2578

Epoch 22/128

144/144 - 10s - 69ms/step - ia: 0.9217 - loss: 0.0312 - mae: 0.1279 - rmse: 0.1762 - smape: 0.2755 - val_ia: 0.8720 - val_loss: 0.0406 - val_mae: 0.1595 - val_rmse: 0.1990 - val_smape: 0.2940

Epoch 23/128

144/144 - 11s - 74ms/step - ia: 0.9222 - loss: 0.0307 - mae: 0.1270 - rmse: 0.1747 - smape: 0.2720 - val_ia: 0.8653 - val_loss: 0.0422 - val_mae: 0.1682 - val_rmse: 0.2020 - val_smape: 0.3300

Epoch 24/128

144/144 - 10s - 67ms/step - ia: 0.9226 - loss: 0.0311 - mae: 0.1267 - rmse: 0.1760 - smape: 0.2674 - val_ia: 0.8778 - val_loss: 0.0365 - val_mae: 0.1534 - val_rmse: 0.1890 - val_smape: 0.2713

Epoch 25/128

144/144 - 10s - 72ms/step - ia: 0.9231 - loss: 0.0307 - mae: 0.1258 - rmse: 0.1746 - smape: 0.2650 - val_ia: 0.8778 - val_loss: 0.0386 - val_mae: 0.1524 - val_rmse: 0.1924 - val_smape: 0.2948

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 10:03 4s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step

 52%|█████▏    | 26/50 [5:43:04<3:43:45, 559.39s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 71s - 496ms/step - ia: 0.1353 - loss: 1.0026 - mae: 0.8206 - rmse: 1.0001 - smape: 1.6986 - val_ia: 0.2789 - val_loss: 0.7583 - val_mae: 0.7204 - val_rmse: 0.8634 - val_smape: 1.7042

Epoch 2/128

144/144 - 15s - 104ms/step - ia: 0.2029 - loss: 0.8766 - mae: 0.7656 - rmse: 0.9355 - smape: 1.5966 - val_ia: 0.3539 - val_loss: 0.6343 - val_mae: 0.6558 - val_rmse: 0.7887 - val_smape: 1.4672

Epoch 3/128

144/144 - 10s - 71ms/step - ia: 0.3281 - loss: 0.7157 - mae: 0.6857 - rmse: 0.8448 - smape: 1.3977 - val_ia: 0.4670 - val_loss: 0.4748 - val_mae: 0.5618 - val_rmse: 0.6808 - val_smape: 1.1815

Epoch 4/128

144/144 - 10s - 71ms/step - ia: 0.5037 - loss: 0.5142 - mae: 0.5694 - rmse: 0.7147 - smape: 1.1261 - val_ia: 0.6206 - val_loss: 0.3172 - val_mae: 0.4444 - val_rmse: 0.5559 - val_smape: 0.9027

Epoch 5/128

144/144 - 8s - 58ms/step - ia: 0.6623 - loss: 0.3370 - mae: 0.4520 - rmse: 0.5790 - smape: 0.8819 - val_ia: 0.7031 - val_loss: 0.2480 - val_mae: 0.3913 - val_rmse: 0.4946 - val_smape: 0.7710

Epoch 6/128

144/144 - 8s - 54ms/step - ia: 0.7257 - loss: 0.2718 - mae: 0.4053 - rmse: 0.5203 - smape: 0.7773 - val_ia: 0.7181 - val_loss: 0.2388 - val_mae: 0.3870 - val_rmse: 0.4850 - val_smape: 0.7461

Epoch 7/128

144/144 - 8s - 55ms/step - ia: 0.7420 - loss: 0.2545 - mae: 0.3912 - rmse: 0.5035 - smape: 0.7444 - val_ia: 0.7219 - val_loss: 0.2332 - val_mae: 0.3831 - val_rmse: 0.4783 - val_smape: 0.7384

Epoch 8/128

144/144 - 8s - 55ms/step - ia: 0.7514 - loss: 0.2396 - mae: 0.3795 - rmse: 0.4887 - smape: 0.7255 - val_ia: 0.7243 - val_loss: 0.2291 - val_mae: 0.3801 - val_rmse: 0.4723 - val_smape: 0.7327

Epoch 9/128

144/144 - 8s - 58ms/step - ia: 0.7586 - loss: 0.2296 - mae: 0.3693 - rmse: 0.4793 - smape: 0.7070 - val_ia: 0.7279 - val_loss: 0.2224 - val_mae: 0.3749 - val_rmse: 0.4644 - val_smape: 0.7266

Epoch 10/128

144/144 - 8s - 59ms/step - ia: 0.7647 - loss: 0.2200 - mae: 0.3615 - rmse: 0.4683 - smape: 0.6969 - val_ia: 0.7309 - val_loss: 0.2161 - val_mae: 0.3700 - val_rmse: 0.4564 - val_smape: 0.7204

Epoch 11/128

144/144 - 8s - 59ms/step - ia: 0.7710 - loss: 0.2099 - mae: 0.3529 - rmse: 0.4574 - smape: 0.6820 - val_ia: 0.7357 - val_loss: 0.2081 - val_mae: 0.3636 - val_rmse: 0.4470 - val_smape: 0.7120

Epoch 12/128

144/144 - 8s - 58ms/step - ia: 0.7798 - loss: 0.1964 - mae: 0.3411 - rmse: 0.4424 - smape: 0.6626 - val_ia: 0.7395 - val_loss: 0.2011 - val_mae: 0.3580 - val_rmse: 0.4382 - val_smape: 0.7045

Epoch 13/128

144/144 - 8s - 57ms/step - ia: 0.7833 - loss: 0.1923 - mae: 0.3366 - rmse: 0.4379 - smape: 0.6513 - val_ia: 0.7439 - val_loss: 0.1931 - val_mae: 0.3514 - val_rmse: 0.4288 - val_smape: 0.6983

Epoch 14/128

144/144 - 8s - 55ms/step - ia: 0.7898 - loss: 0.1834 - mae: 0.3275 - rmse: 0.4275 - smape: 0.6393 - val_ia: 0.7465 - val_loss: 0.1871 - val_mae: 0.3467 - val_rmse: 0.4210 - val_smape: 0.6945

Epoch 15/128

144/144 - 6s - 45ms/step - ia: 0.7938 - loss: 0.1771 - mae: 0.3215 - rmse: 0.4203 - smape: 0.6265 - val_ia: 0.7496 - val_loss: 0.1799 - val_mae: 0.3408 - val_rmse: 0.4122 - val_smape: 0.6905

Epoch 16/128

144/144 - 7s - 48ms/step - ia: 0.7987 - loss: 0.1706 - mae: 0.3146 - rmse: 0.4123 - smape: 0.6163 - val_ia: 0.7541 - val_loss: 0.1717 - val_mae: 0.3337 - val_rmse: 0.4023 - val_smape: 0.6844

Epoch 17/128

144/144 - 8s - 56ms/step - ia: 0.8051 - loss: 0.1611 - mae: 0.3055 - rmse: 0.4004 - smape: 0.6015 - val_ia: 0.7591 - val_loss: 0.1628 - val_mae: 0.3258 - val_rmse: 0.3917 - val_smape: 0.6769

Epoch 18/128

144/144 - 9s - 60ms/step - ia: 0.8083 - loss: 0.1581 - mae: 0.3014 - rmse: 0.3968 - smape: 0.5929 - val_ia: 0.7592 - val_loss: 0.1590 - val_mae: 0.3224 - val_rmse: 0.3863 - val_smape: 0.6752

Epoch 19/128

144/144 - 8s - 57ms/step - ia: 0.8101 - loss: 0.1542 - mae: 0.2981 - rmse: 0.3921 - smape: 0.5858 - val_ia: 0.7657 - val_loss: 0.1494 - val_mae: 0.3130 - val_rmse: 0.3750 - val_smape: 0.6650

Epoch 20/128

144/144 - 8s - 56ms/step - ia: 0.8148 - loss: 0.1479 - mae: 0.2916 - rmse: 0.3843 - smape: 0.5749 - val_ia: 0.7660 - val_loss: 0.1471 - val_mae: 0.3107 - val_rmse: 0.3714 - val_smape: 0.6631

Epoch 21/128

144/144 - 8s - 57ms/step - ia: 0.8187 - loss: 0.1425 - mae: 0.2866 - rmse: 0.3769 - smape: 0.5656 - val_ia: 0.7736 - val_loss: 0.1367 - val_mae: 0.2996 - val_rmse: 0.3590 - val_smape: 0.6501

Epoch 22/128

144/144 - 8s - 53ms/step - ia: 0.8212 - loss: 0.1403 - mae: 0.2830 - rmse: 0.3738 - smape: 0.5612 - val_ia: 0.7763 - val_loss: 0.1321 - val_mae: 0.2938 - val_rmse: 0.3528 - val_smape: 0.6437

Epoch 23/128

144/144 - 8s - 55ms/step - ia: 0.8233 - loss: 0.1366 - mae: 0.2792 - rmse: 0.3690 - smape: 0.5528 - val_ia: 0.7807 - val_loss: 0.1267 - val_mae: 0.2876 - val_rmse: 0.3455 - val_smape: 0.6363

Epoch 24/128

144/144 - 8s - 54ms/step - ia: 0.8257 - loss: 0.1340 - mae: 0.2765 - rmse: 0.3653 - smape: 0.5514 - val_ia: 0.7832 - val_loss: 0.1228 - val_mae: 0.2824 - val_rmse: 0.3402 - val_smape: 0.6302

Epoch 25/128

144/144 - 8s - 55ms/step - ia: 0.8272 - loss: 0.1316 - mae: 0.2740 - rmse: 0.3621 - smape: 0.5434 - val_ia: 0.7877 - val_loss: 0.1175 - val_mae: 0.2751 - val_rmse: 0.3329 - val_smape: 0.6204

Epoch 26/128

144/144 - 8s - 57ms/step - ia: 0.8303 - loss: 0.1273 - mae: 0.2691 - rmse: 0.3562 - smape: 0.5377 - val_ia: 0.7929 - val_loss: 0.1119 - val_mae: 0.2676 - val_rmse: 0.3253 - val_smape: 0.6091

Epoch 27/128

144/144 - 8s - 57ms/step - ia: 0.8315 - loss: 0.1258 - mae: 0.2677 - rmse: 0.3541 - smape: 0.5365 - val_ia: 0.7952 - val_loss: 0.1094 - val_mae: 0.2639 - val_rmse: 0.3217 - val_smape: 0.6031

Epoch 28/128

144/144 - 8s - 57ms/step - ia: 0.8341 - loss: 0.1229 - mae: 0.2641 - rmse: 0.3502 - smape: 0.5308 - val_ia: 0.7974 - val_loss: 0.1071 - val_mae: 0.2598 - val_rmse: 0.3186 - val_smape: 0.5958

Epoch 29/128

144/144 - 8s - 56ms/step - ia: 0.8348 - loss: 0.1207 - mae: 0.2626 - rmse: 0.3468 - smape: 0.5291 - val_ia: 0.8027 - val_loss: 0.1025 - val_mae: 0.2527 - val_rmse: 0.3120 - val_smape: 0.5827

Epoch 30/128

144/144 - 8s - 53ms/step - ia: 0.8387 - loss: 0.1160 - mae: 0.2569 - rmse: 0.3402 - smape: 0.5190 - val_ia: 0.8067 - val_loss: 0.0991 - val_mae: 0.2474 - val_rmse: 0.3070 - val_smape: 0.5726

Epoch 31/128

144/144 - 8s - 56ms/step - ia: 0.8391 - loss: 0.1156 - mae: 0.2566 - rmse: 0.3394 - smape: 0.5196 - val_ia: 0.8077 - val_loss: 0.0982 - val_mae: 0.2453 - val_rmse: 0.3056 - val_smape: 0.5666

Epoch 32/128

144/144 - 8s - 53ms/step - ia: 0.8414 - loss: 0.1133 - mae: 0.2531 - rmse: 0.3357 - smape: 0.5137 - val_ia: 0.8074 - val_loss: 0.0985 - val_mae: 0.2447 - val_rmse: 0.3059 - val_smape: 0.5629

Epoch 33/128

144/144 - 8s - 55ms/step - ia: 0.8408 - loss: 0.1139 - mae: 0.2541 - rmse: 0.3374 - smape: 0.5150 - val_ia: 0.8115 - val_loss: 0.0953 - val_mae: 0.2388 - val_rmse: 0.3017 - val_smape: 0.5485

Epoch 34/128

144/144 - 8s - 57ms/step - ia: 0.8432 - loss: 0.1100 - mae: 0.2503 - rmse: 0.3308 - smape: 0.5108 - val_ia: 0.8081 - val_loss: 0.0975 - val_mae: 0.2421 - val_rmse: 0.3048 - val_smape: 0.5513

Epoch 35/128

144/144 - 9s - 59ms/step - ia: 0.8433 - loss: 0.1098 - mae: 0.2498 - rmse: 0.3311 - smape: 0.5077 - val_ia: 0.8093 - val_loss: 0.0963 - val_mae: 0.2403 - val_rmse: 0.3030 - val_smape: 0.5469

Epoch 36/128

144/144 - 9s - 63ms/step - ia: 0.8453 - loss: 0.1080 - mae: 0.2475 - rmse: 0.3278 - smape: 0.5045 - val_ia: 0.8090 - val_loss: 0.0963 - val_mae: 0.2401 - val_rmse: 0.3029 - val_smape: 0.5436

Epoch 37/128

144/144 - 7s - 48ms/step - ia: 0.8474 - loss: 0.1045 - mae: 0.2437 - rmse: 0.3227 - smape: 0.4993 - val_ia: 0.8122 - val_loss: 0.0935 - val_mae: 0.2365 - val_rmse: 0.2985 - val_smape: 0.5379

Epoch 38/128

144/144 - 8s - 56ms/step - ia: 0.8477 - loss: 0.1042 - mae: 0.2437 - rmse: 0.3222 - smape: 0.5008 - val_ia: 0.8117 - val_loss: 0.0935 - val_mae: 0.2363 - val_rmse: 0.2989 - val_smape: 0.5336

Epoch 39/128

144/144 - 8s - 54ms/step - ia: 0.8491 - loss: 0.1031 - mae: 0.2415 - rmse: 0.3207 - smape: 0.4935 - val_ia: 0.8118 - val_loss: 0.0930 - val_mae: 0.2354 - val_rmse: 0.2982 - val_smape: 0.5276

Epoch 40/128

144/144 - 10s - 72ms/step - ia: 0.8487 - loss: 0.1031 - mae: 0.2417 - rmse: 0.3206 - smape: 0.4928 - val_ia: 0.8140 - val_loss: 0.0909 - val_mae: 0.2328 - val_rmse: 0.2951 - val_smape: 0.5225

Epoch 41/128

144/144 - 11s - 75ms/step - ia: 0.8505 - loss: 0.1000 - mae: 0.2391 - rmse: 0.3158 - smape: 0.4926 - val_ia: 0.8120 - val_loss: 0.0918 - val_mae: 0.2340 - val_rmse: 0.2969 - val_smape: 0.5176

Epoch 42/128

144/144 - 9s - 60ms/step - ia: 0.8522 - loss: 0.0990 - mae: 0.2370 - rmse: 0.3140 - smape: 0.4865 - val_ia: 0.8143 - val_loss: 0.0897 - val_mae: 0.2313 - val_rmse: 0.2936 - val_smape: 0.5133

Epoch 43/128

144/144 - 8s - 57ms/step - ia: 0.8534 - loss: 0.0973 - mae: 0.2350 - rmse: 0.3114 - smape: 0.4855 - val_ia: 0.8113 - val_loss: 0.0914 - val_mae: 0.2339 - val_rmse: 0.2962 - val_smape: 0.5135

Epoch 44/128

144/144 - 8s - 57ms/step - ia: 0.8536 - loss: 0.0974 - mae: 0.2344 - rmse: 0.3115 - smape: 0.4833 - val_ia: 0.8139 - val_loss: 0.0892 - val_mae: 0.2312 - val_rmse: 0.2927 - val_smape: 0.5093

Epoch 45/128

144/144 - 9s - 63ms/step - ia: 0.8539 - loss: 0.0968 - mae: 0.2341 - rmse: 0.3107 - smape: 0.4824 - val_ia: 0.8106 - val_loss: 0.0904 - val_mae: 0.2336 - val_rmse: 0.2951 - val_smape: 0.5084

Epoch 46/128

144/144 - 9s - 60ms/step - ia: 0.8541 - loss: 0.0959 - mae: 0.2337 - rmse: 0.3093 - smape: 0.4819 - val_ia: 0.8132 - val_loss: 0.0882 - val_mae: 0.2307 - val_rmse: 0.2915 - val_smape: 0.5035

Epoch 47/128

144/144 - 8s - 52ms/step - ia: 0.8556 - loss: 0.0949 - mae: 0.2318 - rmse: 0.3076 - smape: 0.4785 - val_ia: 0.8118 - val_loss: 0.0888 - val_mae: 0.2320 - val_rmse: 0.2925 - val_smape: 0.5036

Epoch 48/128

144/144 - 8s - 57ms/step - ia: 0.8566 - loss: 0.0934 - mae: 0.2299 - rmse: 0.3051 - smape: 0.4765 - val_ia: 0.8115 - val_loss: 0.0879 - val_mae: 0.2312 - val_rmse: 0.2914 - val_smape: 0.4981

Epoch 49/128

144/144 - 8s - 57ms/step - ia: 0.8572 - loss: 0.0929 - mae: 0.2291 - rmse: 0.3043 - smape: 0.4744 - val_ia: 0.8098 - val_loss: 0.0892 - val_mae: 0.2337 - val_rmse: 0.2932 - val_smape: 0.5039

Epoch 50/128

144/144 - 8s - 56ms/step - ia: 0.8586 - loss: 0.0908 - mae: 0.2269 - rmse: 0.3007 - smape: 0.4735 - val_ia: 0.8118 - val_loss: 0.0874 - val_mae: 0.2312 - val_rmse: 0.2904 - val_smape: 0.4982

Epoch 51/128

144/144 - 7s - 51ms/step - ia: 0.8587 - loss: 0.0912 - mae: 0.2267 - rmse: 0.3017 - smape: 0.4704 - val_ia: 0.8145 - val_loss: 0.0852 - val_mae: 0.2279 - val_rmse: 0.2869 - val_smape: 0.4909

Epoch 52/128

144/144 - 8s - 55ms/step - ia: 0.8597 - loss: 0.0901 - mae: 0.2250 - rmse: 0.2996 - smape: 0.4690 - val_ia: 0.8133 - val_loss: 0.0860 - val_mae: 0.2297 - val_rmse: 0.2882 - val_smape: 0.4940

Epoch 53/128

144/144 - 8s - 55ms/step - ia: 0.8606 - loss: 0.0894 - mae: 0.2241 - rmse: 0.2982 - smape: 0.4656 - val_ia: 0.8114 - val_loss: 0.0860 - val_mae: 0.2304 - val_rmse: 0.2887 - val_smape: 0.4911

Epoch 54/128

144/144 - 8s - 57ms/step - ia: 0.8613 - loss: 0.0874 - mae: 0.2224 - rmse: 0.2954 - smape: 0.4632 - val_ia: 0.8145 - val_loss: 0.0839 - val_mae: 0.2273 - val_rmse: 0.2852 - val_smape: 0.4854

Epoch 55/128

144/144 - 8s - 52ms/step - ia: 0.8619 - loss: 0.0879 - mae: 0.2222 - rmse: 0.2955 - smape: 0.4594 - val_ia: 0.8112 - val_loss: 0.0856 - val_mae: 0.2307 - val_rmse: 0.2881 - val_smape: 0.4893

Epoch 56/128

144/144 - 8s - 55ms/step - ia: 0.8627 - loss: 0.0863 - mae: 0.2203 - rmse: 0.2931 - smape: 0.4577 - val_ia: 0.8107 - val_loss: 0.0860 - val_mae: 0.2315 - val_rmse: 0.2886 - val_smape: 0.4894

Epoch 57/128

144/144 - 8s - 55ms/step - ia: 0.8624 - loss: 0.0865 - mae: 0.2212 - rmse: 0.2936 - smape: 0.4609 - val_ia: 0.8064 - val_loss: 0.0885 - val_mae: 0.2359 - val_rmse: 0.2928 - val_smape: 0.4960

Epoch 58/128

144/144 - 7s - 51ms/step - ia: 0.8635 - loss: 0.0858 - mae: 0.2196 - rmse: 0.2920 - smape: 0.4547 - val_ia: 0.8069 - val_loss: 0.0874 - val_mae: 0.2348 - val_rmse: 0.2912 - val_smape: 0.4915

Epoch 59/128

144/144 - 8s - 55ms/step - ia: 0.8637 - loss: 0.0857 - mae: 0.2191 - rmse: 0.2924 - smape: 0.4567 - val_ia: 0.8098 - val_loss: 0.0857 - val_mae: 0.2322 - val_rmse: 0.2882 - val_smape: 0.4871

Epoch 60/128

144/144 - 8s - 57ms/step - ia: 0.8650 - loss: 0.0836 - mae: 0.2172 - rmse: 0.2883 - smape: 0.4540 - val_ia: 0.8078 - val_loss: 0.0864 - val_mae: 0.2337 - val_rmse: 0.2894 - val_smape: 0.4870

Epoch 61/128

144/144 - 8s - 54ms/step - ia: 0.8642 - loss: 0.0842 - mae: 0.2178 - rmse: 0.2899 - smape: 0.4546 - val_ia: 0.8096 - val_loss: 0.0846 - val_mae: 0.2315 - val_rmse: 0.2867 - val_smape: 0.4832

Epoch 62/128

144/144 - 7s - 48ms/step - ia: 0.8660 - loss: 0.0825 - mae: 0.2154 - rmse: 0.2869 - smape: 0.4500 - val_ia: 0.8092 - val_loss: 0.0852 - val_mae: 0.2326 - val_rmse: 0.2874 - val_smape: 0.4857

Epoch 63/128

144/144 - 7s - 45ms/step - ia: 0.8670 - loss: 0.0814 - mae: 0.2143 - rmse: 0.2847 - smape: 0.4462 - val_ia: 0.8062 - val_loss: 0.0865 - val_mae: 0.2350 - val_rmse: 0.2897 - val_smape: 0.4860

Epoch 64/128

144/144 - 8s - 53ms/step - ia: 0.8676 - loss: 0.0812 - mae: 0.2131 - rmse: 0.2846 - smape: 0.4444 - val_ia: 0.8072 - val_loss: 0.0856 - val_mae: 0.2340 - val_rmse: 0.2881 - val_smape: 0.4845

Epoch 65/128

144/144 - 8s - 54ms/step - ia: 0.8678 - loss: 0.0810 - mae: 0.2131 - rmse: 0.2841 - smape: 0.4436 - val_ia: 0.8043 - val_loss: 0.0869 - val_mae: 0.2367 - val_rmse: 0.2905 - val_smape: 0.4870

Epoch 66/128

144/144 - 8s - 56ms/step - ia: 0.8677 - loss: 0.0809 - mae: 0.2131 - rmse: 0.2840 - smape: 0.4419 - val_ia: 0.8095 - val_loss: 0.0830 - val_mae: 0.2309 - val_rmse: 0.2842 - val_smape: 0.4771

Epoch 67/128

144/144 - 9s - 61ms/step - ia: 0.8689 - loss: 0.0792 - mae: 0.2112 - rmse: 0.2808 - smape: 0.4398 - val_ia: 0.8065 - val_loss: 0.0853 - val_mae: 0.2346 - val_rmse: 0.2876 - val_smape: 0.4828

Epoch 68/128

144/144 - 8s - 57ms/step - ia: 0.8690 - loss: 0.0797 - mae: 0.2110 - rmse: 0.2818 - smape: 0.4395 - val_ia: 0.8093 - val_loss: 0.0831 - val_mae: 0.2316 - val_rmse: 0.2840 - val_smape: 0.4780

Epoch 69/128

144/144 - 8s - 56ms/step - ia: 0.8690 - loss: 0.0792 - mae: 0.2110 - rmse: 0.2811 - smape: 0.4400 - val_ia: 0.8095 - val_loss: 0.0829 - val_mae: 0.2314 - val_rmse: 0.2837 - val_smape: 0.4762

Epoch 70/128

144/144 - 8s - 54ms/step - ia: 0.8698 - loss: 0.0781 - mae: 0.2098 - rmse: 0.2791 - smape: 0.4362 - val_ia: 0.8055 - val_loss: 0.0853 - val_mae: 0.2355 - val_rmse: 0.2876 - val_smape: 0.4815

Epoch 71/128

144/144 - 7s - 50ms/step - ia: 0.8704 - loss: 0.0780 - mae: 0.2090 - rmse: 0.2789 - smape: 0.4357 - val_ia: 0.8038 - val_loss: 0.0865 - val_mae: 0.2374 - val_rmse: 0.2895 - val_smape: 0.4827

Epoch 72/128

144/144 - 7s - 46ms/step - ia: 0.8706 - loss: 0.0780 - mae: 0.2088 - rmse: 0.2786 - smape: 0.4340 - val_ia: 0.8033 - val_loss: 0.0862 - val_mae: 0.2377 - val_rmse: 0.2893 - val_smape: 0.4819

Epoch 73/128

144/144 - 6s - 41ms/step - ia: 0.8726 - loss: 0.0753 - mae: 0.2057 - rmse: 0.2737 - smape: 0.4304 - val_ia: 0.8071 - val_loss: 0.0838 - val_mae: 0.2339 - val_rmse: 0.2851 - val_smape: 0.4760

Epoch 74/128

144/144 - 7s - 50ms/step - ia: 0.8729 - loss: 0.0755 - mae: 0.2050 - rmse: 0.2741 - smape: 0.4282 - val_ia: 0.8083 - val_loss: 0.0830 - val_mae: 0.2328 - val_rmse: 0.2838 - val_smape: 0.4732

Epoch 75/128

144/144 - 8s - 56ms/step - ia: 0.8731 - loss: 0.0751 - mae: 0.2048 - rmse: 0.2733 - smape: 0.4272 - val_ia: 0.8072 - val_loss: 0.0832 - val_mae: 0.2335 - val_rmse: 0.2843 - val_smape: 0.4709

Epoch 76/128

144/144 - 8s - 55ms/step - ia: 0.8727 - loss: 0.0758 - mae: 0.2053 - rmse: 0.2748 - smape: 0.4268 - val_ia: 0.8070 - val_loss: 0.0833 - val_mae: 0.2339 - val_rmse: 0.2843 - val_smape: 0.4709

Epoch 77/128

144/144 - 8s - 57ms/step - ia: 0.8744 - loss: 0.0736 - mae: 0.2028 - rmse: 0.2707 - smape: 0.4224 - val_ia: 0.8037 - val_loss: 0.0854 - val_mae: 0.2374 - val_rmse: 0.2877 - val_smape: 0.4756

Epoch 78/128

144/144 - 10s - 71ms/step - ia: 0.8742 - loss: 0.0737 - mae: 0.2030 - rmse: 0.2710 - smape: 0.4214 - val_ia: 0.8014 - val_loss: 0.0865 - val_mae: 0.2395 - val_rmse: 0.2896 - val_smape: 0.4765

Epoch 79/128

144/144 - 8s - 56ms/step - ia: 0.8751 - loss: 0.0730 - mae: 0.2018 - rmse: 0.2696 - smape: 0.4230 - val_ia: 0.8033 - val_loss: 0.0847 - val_mae: 0.2373 - val_rmse: 0.2868 - val_smape: 0.4712

Epoch 80/128

144/144 - 7s - 50ms/step - ia: 0.8748 - loss: 0.0735 - mae: 0.2020 - rmse: 0.2708 - smape: 0.4202 - val_ia: 0.8052 - val_loss: 0.0840 - val_mae: 0.2360 - val_rmse: 0.2853 - val_smape: 0.4699

Epoch 81/128

144/144 - 7s - 51ms/step - ia: 0.8757 - loss: 0.0722 - mae: 0.2009 - rmse: 0.2681 - smape: 0.4180 - val_ia: 0.8017 - val_loss: 0.0857 - val_mae: 0.2393 - val_rmse: 0.2885 - val_smape: 0.4723

Epoch 82/128

144/144 - 8s - 57ms/step - ia: 0.8768 - loss: 0.0714 - mae: 0.1992 - rmse: 0.2666 - smape: 0.4132 - val_ia: 0.8046 - val_loss: 0.0834 - val_mae: 0.2364 - val_rmse: 0.2846 - val_smape: 0.4669

Epoch 83/128

144/144 - 8s - 57ms/step - ia: 0.8782 - loss: 0.0696 - mae: 0.1968 - rmse: 0.2635 - smape: 0.4106 - val_ia: 0.8035 - val_loss: 0.0840 - val_mae: 0.2375 - val_rmse: 0.2855 - val_smape: 0.4679

Epoch 84/128

144/144 - 8s - 55ms/step - ia: 0.8769 - loss: 0.0711 - mae: 0.1992 - rmse: 0.2659 - smape: 0.4139 - val_ia: 0.7995 - val_loss: 0.0867 - val_mae: 0.2419 - val_rmse: 0.2901 - val_smape: 0.4759

Epoch 84: early stopping

Restoring model weights from the end of the best epoch: 69.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:01 4s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 32ms/step

 54%|█████▍    | 27/50 [5:55:44<3:57:34, 619.75s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 39s - 270ms/step - ia: 0.8715 - loss: 0.0836 - mae: 0.1854 - rmse: 0.2387 - smape: 0.4267 - val_ia: 0.9479 - val_loss: 0.0091 - val_mae: 0.0688 - val_rmse: 0.0944 - val_smape: 0.1949

Epoch 2/256

144/144 - 10s - 72ms/step - ia: 0.9447 - loss: 0.0151 - mae: 0.0913 - rmse: 0.1222 - smape: 0.2381 - val_ia: 0.9527 - val_loss: 0.0071 - val_mae: 0.0628 - val_rmse: 0.0835 - val_smape: 0.1782

Epoch 3/256

144/144 - 9s - 63ms/step - ia: 0.9506 - loss: 0.0122 - mae: 0.0814 - rmse: 0.1096 - smape: 0.2202 - val_ia: 0.9468 - val_loss: 0.0087 - val_mae: 0.0706 - val_rmse: 0.0918 - val_smape: 0.1810

Epoch 4/256

144/144 - 10s - 71ms/step - ia: 0.9549 - loss: 0.0103 - mae: 0.0745 - rmse: 0.1008 - smape: 0.2045 - val_ia: 0.9575 - val_loss: 0.0060 - val_mae: 0.0567 - val_rmse: 0.0760 - val_smape: 0.1628

Epoch 5/256

144/144 - 11s - 78ms/step - ia: 0.9571 - loss: 0.0094 - mae: 0.0709 - rmse: 0.0965 - smape: 0.1974 - val_ia: 0.9585 - val_loss: 0.0057 - val_mae: 0.0553 - val_rmse: 0.0738 - val_smape: 0.1662

Epoch 6/256

144/144 - 12s - 83ms/step - ia: 0.9590 - loss: 0.0087 - mae: 0.0676 - rmse: 0.0924 - smape: 0.1899 - val_ia: 0.9590 - val_loss: 0.0056 - val_mae: 0.0546 - val_rmse: 0.0733 - val_smape: 0.1437

Epoch 7/256

144/144 - 12s - 83ms/step - ia: 0.9606 - loss: 0.0080 - mae: 0.0651 - rmse: 0.0887 - smape: 0.1845 - val_ia: 0.9600 - val_loss: 0.0053 - val_mae: 0.0533 - val_rmse: 0.0714 - val_smape: 0.1426

Epoch 8/256

144/144 - 11s - 79ms/step - ia: 0.9619 - loss: 0.0076 - mae: 0.0630 - rmse: 0.0862 - smape: 0.1770 - val_ia: 0.9590 - val_loss: 0.0055 - val_mae: 0.0545 - val_rmse: 0.0729 - val_smape: 0.1370

Epoch 9/256

144/144 - 11s - 76ms/step - ia: 0.9627 - loss: 0.0073 - mae: 0.0616 - rmse: 0.0842 - smape: 0.1749 - val_ia: 0.9662 - val_loss: 0.0039 - val_mae: 0.0454 - val_rmse: 0.0614 - val_smape: 0.1451

Epoch 10/256

144/144 - 11s - 75ms/step - ia: 0.9634 - loss: 0.0070 - mae: 0.0604 - rmse: 0.0828 - smape: 0.1718 - val_ia: 0.9641 - val_loss: 0.0044 - val_mae: 0.0480 - val_rmse: 0.0646 - val_smape: 0.1341

Epoch 11/256

144/144 - 12s - 80ms/step - ia: 0.9645 - loss: 0.0066 - mae: 0.0587 - rmse: 0.0804 - smape: 0.1698 - val_ia: 0.9633 - val_loss: 0.0045 - val_mae: 0.0491 - val_rmse: 0.0659 - val_smape: 0.1431

Epoch 12/256

144/144 - 12s - 81ms/step - ia: 0.9648 - loss: 0.0065 - mae: 0.0581 - rmse: 0.0798 - smape: 0.1656 - val_ia: 0.9610 - val_loss: 0.0047 - val_mae: 0.0521 - val_rmse: 0.0670 - val_smape: 0.1433

Epoch 13/256

144/144 - 12s - 82ms/step - ia: 0.9649 - loss: 0.0065 - mae: 0.0580 - rmse: 0.0798 - smape: 0.1652 - val_ia: 0.9591 - val_loss: 0.0051 - val_mae: 0.0545 - val_rmse: 0.0698 - val_smape: 0.1467

Epoch 14/256

144/144 - 11s - 75ms/step - ia: 0.9660 - loss: 0.0061 - mae: 0.0561 - rmse: 0.0773 - smape: 0.1609 - val_ia: 0.9601 - val_loss: 0.0049 - val_mae: 0.0525 - val_rmse: 0.0683 - val_smape: 0.1427

Epoch 15/256

144/144 - 20s - 136ms/step - ia: 0.9661 - loss: 0.0061 - mae: 0.0560 - rmse: 0.0774 - smape: 0.1600 - val_ia: 0.9721 - val_loss: 0.0030 - val_mae: 0.0377 - val_rmse: 0.0538 - val_smape: 0.1222

Epoch 16/256

144/144 - 9s - 63ms/step - ia: 0.9663 - loss: 0.0061 - mae: 0.0557 - rmse: 0.0770 - smape: 0.1596 - val_ia: 0.9673 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0585 - val_smape: 0.1323

Epoch 17/256

144/144 - 9s - 64ms/step - ia: 0.9666 - loss: 0.0060 - mae: 0.0552 - rmse: 0.0766 - smape: 0.1574 - val_ia: 0.9677 - val_loss: 0.0034 - val_mae: 0.0433 - val_rmse: 0.0578 - val_smape: 0.1435

Epoch 18/256

144/144 - 11s - 75ms/step - ia: 0.9662 - loss: 0.0061 - mae: 0.0559 - rmse: 0.0770 - smape: 0.1587 - val_ia: 0.9719 - val_loss: 0.0029 - val_mae: 0.0377 - val_rmse: 0.0532 - val_smape: 0.1170

Epoch 19/256

144/144 - 11s - 78ms/step - ia: 0.9666 - loss: 0.0060 - mae: 0.0552 - rmse: 0.0763 - smape: 0.1561 - val_ia: 0.9679 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0579 - val_smape: 0.1414

Epoch 20/256

144/144 - 9s - 66ms/step - ia: 0.9671 - loss: 0.0059 - mae: 0.0544 - rmse: 0.0755 - smape: 0.1544 - val_ia: 0.9713 - val_loss: 0.0030 - val_mae: 0.0387 - val_rmse: 0.0536 - val_smape: 0.1296

Epoch 21/256

144/144 - 10s - 68ms/step - ia: 0.9678 - loss: 0.0056 - mae: 0.0532 - rmse: 0.0738 - smape: 0.1527 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0591 - val_smape: 0.1263

Epoch 22/256

144/144 - 12s - 82ms/step - ia: 0.9680 - loss: 0.0055 - mae: 0.0528 - rmse: 0.0734 - smape: 0.1509 - val_ia: 0.9622 - val_loss: 0.0046 - val_mae: 0.0495 - val_rmse: 0.0671 - val_smape: 0.1297

Epoch 23/256

144/144 - 11s - 75ms/step - ia: 0.9678 - loss: 0.0056 - mae: 0.0531 - rmse: 0.0738 - smape: 0.1520 - val_ia: 0.9660 - val_loss: 0.0039 - val_mae: 0.0449 - val_rmse: 0.0617 - val_smape: 0.1279

Epoch 24/256

144/144 - 11s - 78ms/step - ia: 0.9676 - loss: 0.0057 - mae: 0.0535 - rmse: 0.0741 - smape: 0.1526 - val_ia: 0.9632 - val_loss: 0.0043 - val_mae: 0.0492 - val_rmse: 0.0639 - val_smape: 0.1400

Epoch 25/256

144/144 - 12s - 82ms/step - ia: 0.9678 - loss: 0.0056 - mae: 0.0531 - rmse: 0.0738 - smape: 0.1509 - val_ia: 0.9711 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0541 - val_smape: 0.1258

Epoch 26/256

144/144 - 12s - 81ms/step - ia: 0.9683 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0724 - smape: 0.1501 - val_ia: 0.9656 - val_loss: 0.0040 - val_mae: 0.0464 - val_rmse: 0.0617 - val_smape: 0.1380

Epoch 27/256

144/144 - 12s - 80ms/step - ia: 0.9686 - loss: 0.0054 - mae: 0.0520 - rmse: 0.0721 - smape: 0.1485 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0418 - val_rmse: 0.0569 - val_smape: 0.1216

Epoch 28/256

144/144 - 20s - 136ms/step - ia: 0.9683 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0727 - smape: 0.1497 - val_ia: 0.9669 - val_loss: 0.0036 - val_mae: 0.0443 - val_rmse: 0.0587 - val_smape: 0.1332

Epoch 29/256

144/144 - 12s - 82ms/step - ia: 0.9690 - loss: 0.0052 - mae: 0.0513 - rmse: 0.0712 - smape: 0.1491 - val_ia: 0.9684 - val_loss: 0.0035 - val_mae: 0.0426 - val_rmse: 0.0584 - val_smape: 0.1214

Epoch 30/256

144/144 - 12s - 82ms/step - ia: 0.9684 - loss: 0.0054 - mae: 0.0523 - rmse: 0.0725 - smape: 0.1490 - val_ia: 0.9731 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0504 - val_smape: 0.1188

Epoch 31/256

144/144 - 12s - 81ms/step - ia: 0.9691 - loss: 0.0051 - mae: 0.0509 - rmse: 0.0706 - smape: 0.1457 - val_ia: 0.9651 - val_loss: 0.0039 - val_mae: 0.0463 - val_rmse: 0.0614 - val_smape: 0.1268

Epoch 32/256

144/144 - 10s - 67ms/step - ia: 0.9691 - loss: 0.0052 - mae: 0.0510 - rmse: 0.0712 - smape: 0.1458 - val_ia: 0.9691 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0554 - val_smape: 0.1371

Epoch 33/256

144/144 - 8s - 52ms/step - ia: 0.9689 - loss: 0.0053 - mae: 0.0515 - rmse: 0.0715 - smape: 0.1477 - val_ia: 0.9678 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0589 - val_smape: 0.1270

Epoch 34/256

144/144 - 9s - 63ms/step - ia: 0.9688 - loss: 0.0053 - mae: 0.0515 - rmse: 0.0718 - smape: 0.1467 - val_ia: 0.9698 - val_loss: 0.0032 - val_mae: 0.0408 - val_rmse: 0.0554 - val_smape: 0.1244

Epoch 35/256

144/144 - 10s - 67ms/step - ia: 0.9690 - loss: 0.0052 - mae: 0.0512 - rmse: 0.0712 - smape: 0.1467 - val_ia: 0.9645 - val_loss: 0.0041 - val_mae: 0.0477 - val_rmse: 0.0616 - val_smape: 0.1429

Epoch 36/256

144/144 - 10s - 67ms/step - ia: 0.9692 - loss: 0.0051 - mae: 0.0508 - rmse: 0.0707 - smape: 0.1460 - val_ia: 0.9710 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0534 - val_smape: 0.1226

Epoch 37/256

144/144 - 12s - 85ms/step - ia: 0.9693 - loss: 0.0051 - mae: 0.0507 - rmse: 0.0707 - smape: 0.1445 - val_ia: 0.9705 - val_loss: 0.0031 - val_mae: 0.0397 - val_rmse: 0.0543 - val_smape: 0.1181

Epoch 38/256

144/144 - 12s - 85ms/step - ia: 0.9695 - loss: 0.0051 - mae: 0.0504 - rmse: 0.0702 - smape: 0.1435 - val_ia: 0.9700 - val_loss: 0.0032 - val_mae: 0.0403 - val_rmse: 0.0546 - val_smape: 0.1208

Epoch 39/256

144/144 - 11s - 75ms/step - ia: 0.9696 - loss: 0.0051 - mae: 0.0502 - rmse: 0.0702 - smape: 0.1442 - val_ia: 0.9687 - val_loss: 0.0033 - val_mae: 0.0421 - val_rmse: 0.0569 - val_smape: 0.1246

Epoch 40/256

144/144 - 10s - 72ms/step - ia: 0.9693 - loss: 0.0051 - mae: 0.0507 - rmse: 0.0705 - smape: 0.1446 - val_ia: 0.9634 - val_loss: 0.0043 - val_mae: 0.0487 - val_rmse: 0.0652 - val_smape: 0.1300

Epoch 41/256

144/144 - 12s - 83ms/step - ia: 0.9696 - loss: 0.0051 - mae: 0.0503 - rmse: 0.0703 - smape: 0.1435 - val_ia: 0.9711 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0531 - val_smape: 0.1181

Epoch 42/256

144/144 - 12s - 86ms/step - ia: 0.9696 - loss: 0.0050 - mae: 0.0502 - rmse: 0.0700 - smape: 0.1426 - val_ia: 0.9676 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0590 - val_smape: 0.1332

Epoch 43/256

144/144 - 12s - 86ms/step - ia: 0.9696 - loss: 0.0050 - mae: 0.0501 - rmse: 0.0698 - smape: 0.1440 - val_ia: 0.9714 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0529 - val_smape: 0.1180

Epoch 44/256

144/144 - 11s - 77ms/step - ia: 0.9697 - loss: 0.0050 - mae: 0.0501 - rmse: 0.0700 - smape: 0.1433 - val_ia: 0.9611 - val_loss: 0.0048 - val_mae: 0.0513 - val_rmse: 0.0689 - val_smape: 0.1395

Epoch 45/256

144/144 - 11s - 79ms/step - ia: 0.9696 - loss: 0.0051 - mae: 0.0503 - rmse: 0.0703 - smape: 0.1441 - val_ia: 0.9679 - val_loss: 0.0036 - val_mae: 0.0434 - val_rmse: 0.0588 - val_smape: 0.1218

Epoch 45: early stopping

Restoring model weights from the end of the best epoch: 30.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 7:44 3s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step

 56%|█████▌    | 28/50 [6:04:50<3:39:07, 597.59s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

144/144 - 70s - 487ms/step - ia: 0.6653 - loss: 0.3144 - mae: 0.4078 - rmse: 0.5083 - smape: 0.8435 - val_ia: 0.8475 - val_loss: 0.0655 - val_mae: 0.2063 - val_rmse: 0.2553 - val_smape: 0.4804

Epoch 2/64

144/144 - 23s - 160ms/step - ia: 0.8822 - loss: 0.0653 - mae: 0.1921 - rmse: 0.2546 - smape: 0.4248 - val_ia: 0.9070 - val_loss: 0.0278 - val_mae: 0.1197 - val_rmse: 0.1652 - val_smape: 0.2836

Epoch 3/64

144/144 - 26s - 181ms/step - ia: 0.9019 - loss: 0.0454 - mae: 0.1606 - rmse: 0.2125 - smape: 0.3639 - val_ia: 0.9212 - val_loss: 0.0193 - val_mae: 0.1024 - val_rmse: 0.1366 - val_smape: 0.2370

Epoch 4/64

144/144 - 23s - 159ms/step - ia: 0.9113 - loss: 0.0377 - mae: 0.1455 - rmse: 0.1936 - smape: 0.3360 - val_ia: 0.9152 - val_loss: 0.0209 - val_mae: 0.1104 - val_rmse: 0.1419 - val_smape: 0.2543

Epoch 5/64

144/144 - 21s - 144ms/step - ia: 0.9176 - loss: 0.0329 - mae: 0.1354 - rmse: 0.1809 - smape: 0.3157 - val_ia: 0.9284 - val_loss: 0.0158 - val_mae: 0.0948 - val_rmse: 0.1228 - val_smape: 0.2456

Epoch 6/64

144/144 - 26s - 182ms/step - ia: 0.9230 - loss: 0.0289 - mae: 0.1266 - rmse: 0.1697 - smape: 0.3005 - val_ia: 0.9138 - val_loss: 0.0214 - val_mae: 0.1134 - val_rmse: 0.1407 - val_smape: 0.2830

Epoch 7/64

144/144 - 39s - 271ms/step - ia: 0.9255 - loss: 0.0272 - mae: 0.1226 - rmse: 0.1644 - smape: 0.2902 - val_ia: 0.9044 - val_loss: 0.0238 - val_mae: 0.1231 - val_rmse: 0.1511 - val_smape: 0.2904

Epoch 8/64

144/144 - 26s - 180ms/step - ia: 0.9283 - loss: 0.0254 - mae: 0.1180 - rmse: 0.1589 - smape: 0.2800 - val_ia: 0.9082 - val_loss: 0.0218 - val_mae: 0.1185 - val_rmse: 0.1446 - val_smape: 0.2883

Epoch 9/64

144/144 - 24s - 166ms/step - ia: 0.9301 - loss: 0.0240 - mae: 0.1150 - rmse: 0.1543 - smape: 0.2744 - val_ia: 0.9045 - val_loss: 0.0232 - val_mae: 0.1237 - val_rmse: 0.1482 - val_smape: 0.3003

Epoch 10/64

144/144 - 26s - 179ms/step - ia: 0.9315 - loss: 0.0231 - mae: 0.1125 - rmse: 0.1515 - smape: 0.2707 - val_ia: 0.9047 - val_loss: 0.0229 - val_mae: 0.1237 - val_rmse: 0.1480 - val_smape: 0.3021

Epoch 11/64

144/144 - 24s - 170ms/step - ia: 0.9336 - loss: 0.0220 - mae: 0.1092 - rmse: 0.1479 - smape: 0.2629 - val_ia: 0.9036 - val_loss: 0.0233 - val_mae: 0.1253 - val_rmse: 0.1492 - val_smape: 0.3021

Epoch 12/64

144/144 - 25s - 173ms/step - ia: 0.9354 - loss: 0.0207 - mae: 0.1063 - rmse: 0.1433 - smape: 0.2567 - val_ia: 0.9032 - val_loss: 0.0239 - val_mae: 0.1262 - val_rmse: 0.1507 - val_smape: 0.3061

Epoch 13/64

144/144 - 26s - 179ms/step - ia: 0.9370 - loss: 0.0198 - mae: 0.1036 - rmse: 0.1401 - smape: 0.2519 - val_ia: 0.9019 - val_loss: 0.0241 - val_mae: 0.1276 - val_rmse: 0.1519 - val_smape: 0.2925

Epoch 14/64

144/144 - 23s - 162ms/step - ia: 0.9370 - loss: 0.0198 - mae: 0.1036 - rmse: 0.1403 - smape: 0.2512 - val_ia: 0.8968 - val_loss: 0.0261 - val_mae: 0.1341 - val_rmse: 0.1571 - val_smape: 0.3165

Epoch 15/64

144/144 - 20s - 141ms/step - ia: 0.9385 - loss: 0.0191 - mae: 0.1014 - rmse: 0.1375 - smape: 0.2468 - val_ia: 0.8855 - val_loss: 0.0317 - val_mae: 0.1478 - val_rmse: 0.1728 - val_smape: 0.3333

Epoch 16/64

144/144 - 19s - 135ms/step - ia: 0.9396 - loss: 0.0184 - mae: 0.0994 - rmse: 0.1350 - smape: 0.2423 - val_ia: 0.8888 - val_loss: 0.0292 - val_mae: 0.1435 - val_rmse: 0.1673 - val_smape: 0.3178

Epoch 17/64

144/144 - 26s - 178ms/step - ia: 0.9400 - loss: 0.0181 - mae: 0.0989 - rmse: 0.1341 - smape: 0.2428 - val_ia: 0.8857 - val_loss: 0.0310 - val_mae: 0.1478 - val_rmse: 0.1717 - val_smape: 0.3280

Epoch 18/64

144/144 - 25s - 177ms/step - ia: 0.9405 - loss: 0.0179 - mae: 0.0979 - rmse: 0.1332 - smape: 0.2381 - val_ia: 0.8949 - val_loss: 0.0268 - val_mae: 0.1364 - val_rmse: 0.1596 - val_smape: 0.3069

Epoch 19/64

144/144 - 26s - 179ms/step - ia: 0.9414 - loss: 0.0172 - mae: 0.0965 - rmse: 0.1307 - smape: 0.2369 - val_ia: 0.8802 - val_loss: 0.0325 - val_mae: 0.1533 - val_rmse: 0.1772 - val_smape: 0.3304

Epoch 20/64

144/144 - 27s - 184ms/step - ia: 0.9421 - loss: 0.0170 - mae: 0.0953 - rmse: 0.1298 - smape: 0.2329 - val_ia: 0.8845 - val_loss: 0.0309 - val_mae: 0.1488 - val_rmse: 0.1719 - val_smape: 0.3236

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 10:37 4s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step

 58%|█████▊    | 29/50 [6:14:06<3:24:48, 585.16s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2293/2293 - 36s - 16ms/step - ia: 0.9057 - loss: 0.0430 - mae: 0.1461 - rmse: 0.1954 - smape: 0.2967 - val_ia: 0.7453 - val_loss: 0.0064 - val_mae: 0.0624 - val_rmse: 0.0745 - val_smape: 0.1731

Epoch 2/32

2293/2293 - 19s - 8ms/step - ia: 0.9185 - loss: 0.0325 - mae: 0.1276 - rmse: 0.1737 - smape: 0.2581 - val_ia: 0.8039 - val_loss: 0.0053 - val_mae: 0.0518 - val_rmse: 0.0641 - val_smape: 0.1504

Epoch 3/32

2293/2293 - 20s - 9ms/step - ia: 0.9190 - loss: 0.0327 - mae: 0.1271 - rmse: 0.1740 - smape: 0.2541 - val_ia: 0.7545 - val_loss: 0.0069 - val_mae: 0.0658 - val_rmse: 0.0770 - val_smape: 0.1679

Epoch 4/32

2293/2293 - 17s - 8ms/step - ia: 0.9207 - loss: 0.0310 - mae: 0.1242 - rmse: 0.1696 - smape: 0.2504 - val_ia: 0.8055 - val_loss: 0.0048 - val_mae: 0.0513 - val_rmse: 0.0623 - val_smape: 0.1623

Epoch 5/32

2293/2293 - 18s - 8ms/step - ia: 0.9211 - loss: 0.0310 - mae: 0.1237 - rmse: 0.1695 - smape: 0.2475 - val_ia: 0.8116 - val_loss: 0.0040 - val_mae: 0.0456 - val_rmse: 0.0567 - val_smape: 0.1336

Epoch 6/32

2293/2293 - 19s - 8ms/step - ia: 0.9218 - loss: 0.0304 - mae: 0.1227 - rmse: 0.1679 - smape: 0.2442 - val_ia: 0.7634 - val_loss: 0.0062 - val_mae: 0.0621 - val_rmse: 0.0728 - val_smape: 0.1541

Epoch 7/32

2293/2293 - 17s - 7ms/step - ia: 0.9222 - loss: 0.0306 - mae: 0.1223 - rmse: 0.1682 - smape: 0.2429 - val_ia: 0.8213 - val_loss: 0.0035 - val_mae: 0.0430 - val_rmse: 0.0543 - val_smape: 0.1383

Epoch 8/32

2293/2293 - 22s - 10ms/step - ia: 0.9227 - loss: 0.0300 - mae: 0.1215 - rmse: 0.1667 - smape: 0.2397 - val_ia: 0.7864 - val_loss: 0.0049 - val_mae: 0.0548 - val_rmse: 0.0653 - val_smape: 0.1530

Epoch 9/32

2293/2293 - 19s - 8ms/step - ia: 0.9218 - loss: 0.0306 - mae: 0.1226 - rmse: 0.1686 - smape: 0.2422 - val_ia: 0.6735 - val_loss: 0.0119 - val_mae: 0.0916 - val_rmse: 0.1014 - val_smape: 0.2099

Epoch 10/32

2293/2293 - 16s - 7ms/step - ia: 0.9227 - loss: 0.0301 - mae: 0.1214 - rmse: 0.1669 - smape: 0.2400 - val_ia: 0.7151 - val_loss: 0.0092 - val_mae: 0.0784 - val_rmse: 0.0884 - val_smape: 0.1981

Epoch 11/32

2293/2293 - 16s - 7ms/step - ia: 0.9229 - loss: 0.0296 - mae: 0.1212 - rmse: 0.1657 - smape: 0.2419 - val_ia: 0.8250 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0546 - val_smape: 0.1353

Epoch 12/32

2293/2293 - 18s - 8ms/step - ia: 0.9230 - loss: 0.0297 - mae: 0.1209 - rmse: 0.1659 - smape: 0.2422 - val_ia: 0.7208 - val_loss: 0.0072 - val_mae: 0.0691 - val_rmse: 0.0793 - val_smape: 0.1809

Epoch 13/32

2293/2293 - 18s - 8ms/step - ia: 0.9232 - loss: 0.0298 - mae: 0.1206 - rmse: 0.1660 - smape: 0.2407 - val_ia: 0.7797 - val_loss: 0.0046 - val_mae: 0.0523 - val_rmse: 0.0634 - val_smape: 0.1683

Epoch 14/32

2293/2293 - 18s - 8ms/step - ia: 0.9170 - loss: 0.0351 - mae: 0.1300 - rmse: 0.1786 - smape: 0.2584 - val_ia: 0.7518 - val_loss: 0.0075 - val_mae: 0.0677 - val_rmse: 0.0792 - val_smape: 0.1752

Epoch 15/32

2293/2293 - 18s - 8ms/step - ia: 0.9197 - loss: 0.0320 - mae: 0.1259 - rmse: 0.1722 - smape: 0.2568 - val_ia: 0.7644 - val_loss: 0.0055 - val_mae: 0.0582 - val_rmse: 0.0688 - val_smape: 0.1702

Epoch 16/32

2293/2293 - 15s - 6ms/step - ia: 0.9205 - loss: 0.0313 - mae: 0.1247 - rmse: 0.1705 - smape: 0.2539 - val_ia: 0.7010 - val_loss: 0.0112 - val_mae: 0.0830 - val_rmse: 0.0936 - val_smape: 0.1969

Epoch 17/32

2293/2293 - 13s - 6ms/step - ia: 0.9204 - loss: 0.0317 - mae: 0.1244 - rmse: 0.1702 - smape: 0.2562 - val_ia: 0.8020 - val_loss: 0.0055 - val_mae: 0.0524 - val_rmse: 0.0658 - val_smape: 0.1636

Epoch 18/32

2293/2293 - 15s - 7ms/step - ia: 0.9198 - loss: 0.0312 - mae: 0.1252 - rmse: 0.1700 - smape: 0.2616 - val_ia: 0.7934 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0645 - val_smape: 0.1604

Epoch 19/32

2293/2293 - 18s - 8ms/step - ia: 0.9140 - loss: 0.0378 - mae: 0.1343 - rmse: 0.1843 - smape: 0.2745 - val_ia: 0.6996 - val_loss: 0.0113 - val_mae: 0.0813 - val_rmse: 0.0929 - val_smape: 0.2092

Epoch 20/32

2293/2293 - 19s - 9ms/step - ia: 0.9170 - loss: 0.0338 - mae: 0.1295 - rmse: 0.1768 - smape: 0.2667 - val_ia: 0.7155 - val_loss: 0.0082 - val_mae: 0.0731 - val_rmse: 0.0833 - val_smape: 0.1786

Epoch 21/32

2293/2293 - 16s - 7ms/step - ia: 0.9209 - loss: 0.0310 - mae: 0.1242 - rmse: 0.1696 - smape: 0.2543 - val_ia: 0.7874 - val_loss: 0.0045 - val_mae: 0.0515 - val_rmse: 0.0623 - val_smape: 0.1539

Epoch 22/32

2293/2293 - 15s - 7ms/step - ia: 0.9208 - loss: 0.0313 - mae: 0.1240 - rmse: 0.1707 - smape: 0.2490 - val_ia: 0.7238 - val_loss: 0.0077 - val_mae: 0.0692 - val_rmse: 0.0791 - val_smape: 0.1972

Epoch 23/32

2293/2293 - 15s - 7ms/step - ia: 0.9211 - loss: 0.0313 - mae: 0.1238 - rmse: 0.1701 - smape: 0.2492 - val_ia: 0.7870 - val_loss: 0.0052 - val_mae: 0.0561 - val_rmse: 0.0670 - val_smape: 0.1573

Epoch 24/32

2293/2293 - 13s - 6ms/step - ia: 0.9220 - loss: 0.0304 - mae: 0.1226 - rmse: 0.1680 - smape: 0.2499 - val_ia: 0.7632 - val_loss: 0.0055 - val_mae: 0.0578 - val_rmse: 0.0678 - val_smape: 0.1920

Epoch 25/32

2293/2293 - 13s - 5ms/step - ia: 0.9211 - loss: 0.0314 - mae: 0.1238 - rmse: 0.1705 - smape: 0.2477 - val_ia: 0.7451 - val_loss: 0.0080 - val_mae: 0.0686 - val_rmse: 0.0792 - val_smape: 0.1612

Epoch 26/32

2293/2293 - 17s - 7ms/step - ia: 0.9209 - loss: 0.0423 - mae: 0.1242 - rmse: 0.1725 - smape: 0.2496 - val_ia: 0.6466 - val_loss: 0.0180 - val_mae: 0.1052 - val_rmse: 0.1198 - val_smape: 0.3050

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:44 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 60%|██████    | 30/50 [6:21:52<3:03:07, 549.37s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 65s - 449ms/step - ia: 0.0792 - loss: 0.9722 - mae: 0.8163 - rmse: 0.9852 - smape: 1.8562 - val_ia: 0.2407 - val_loss: 0.8052 - val_mae: 0.7443 - val_rmse: 0.8894 - val_smape: 1.7568

Epoch 2/128

144/144 - 4s - 29ms/step - ia: 0.1562 - loss: 0.8818 - mae: 0.7733 - rmse: 0.9385 - smape: 1.6910 - val_ia: 0.2903 - val_loss: 0.7163 - val_mae: 0.6997 - val_rmse: 0.8388 - val_smape: 1.5685

Epoch 3/128

144/144 - 5s - 32ms/step - ia: 0.2906 - loss: 0.7476 - mae: 0.7000 - rmse: 0.8630 - smape: 1.4518 - val_ia: 0.4123 - val_loss: 0.5324 - val_mae: 0.5952 - val_rmse: 0.7226 - val_smape: 1.2127

Epoch 4/128

144/144 - 5s - 34ms/step - ia: 0.5354 - loss: 0.4998 - mae: 0.5362 - rmse: 0.7032 - smape: 1.0483 - val_ia: 0.6239 - val_loss: 0.3203 - val_mae: 0.4434 - val_rmse: 0.5586 - val_smape: 0.8521

Epoch 5/128

144/144 - 4s - 29ms/step - ia: 0.7156 - loss: 0.3055 - mae: 0.3903 - rmse: 0.5501 - smape: 0.7485 - val_ia: 0.6852 - val_loss: 0.2943 - val_mae: 0.4400 - val_rmse: 0.5310 - val_smape: 0.8105

Epoch 6/128

144/144 - 4s - 30ms/step - ia: 0.7956 - loss: 0.1838 - mae: 0.3138 - rmse: 0.4267 - smape: 0.6160 - val_ia: 0.6932 - val_loss: 0.3348 - val_mae: 0.4698 - val_rmse: 0.5616 - val_smape: 0.8099

Epoch 7/128

144/144 - 5s - 33ms/step - ia: 0.8263 - loss: 0.1417 - mae: 0.2787 - rmse: 0.3761 - smape: 0.5701 - val_ia: 0.7082 - val_loss: 0.3059 - val_mae: 0.4437 - val_rmse: 0.5345 - val_smape: 0.7770

Epoch 8/128

144/144 - 4s - 31ms/step - ia: 0.8387 - loss: 0.1258 - mae: 0.2598 - rmse: 0.3540 - smape: 0.5472 - val_ia: 0.7206 - val_loss: 0.2747 - val_mae: 0.4182 - val_rmse: 0.5050 - val_smape: 0.7531

Epoch 9/128

144/144 - 4s - 31ms/step - ia: 0.8482 - loss: 0.1133 - mae: 0.2444 - rmse: 0.3355 - smape: 0.5272 - val_ia: 0.7321 - val_loss: 0.2499 - val_mae: 0.3968 - val_rmse: 0.4804 - val_smape: 0.7333

Epoch 10/128

144/144 - 5s - 32ms/step - ia: 0.8576 - loss: 0.1016 - mae: 0.2299 - rmse: 0.3177 - smape: 0.5069 - val_ia: 0.7375 - val_loss: 0.2381 - val_mae: 0.3873 - val_rmse: 0.4673 - val_smape: 0.7261

Epoch 11/128

144/144 - 4s - 29ms/step - ia: 0.8672 - loss: 0.0895 - mae: 0.2142 - rmse: 0.2983 - smape: 0.4847 - val_ia: 0.7519 - val_loss: 0.2116 - val_mae: 0.3636 - val_rmse: 0.4395 - val_smape: 0.7025

Epoch 12/128

144/144 - 5s - 33ms/step - ia: 0.8775 - loss: 0.0773 - mae: 0.1980 - rmse: 0.2776 - smape: 0.4617 - val_ia: 0.7632 - val_loss: 0.1912 - val_mae: 0.3451 - val_rmse: 0.4155 - val_smape: 0.6851

Epoch 13/128

144/144 - 4s - 29ms/step - ia: 0.8877 - loss: 0.0660 - mae: 0.1822 - rmse: 0.2559 - smape: 0.4381 - val_ia: 0.7798 - val_loss: 0.1646 - val_mae: 0.3179 - val_rmse: 0.3827 - val_smape: 0.6556

Epoch 14/128

144/144 - 4s - 30ms/step - ia: 0.8984 - loss: 0.0548 - mae: 0.1653 - rmse: 0.2332 - smape: 0.4136 - val_ia: 0.7968 - val_loss: 0.1407 - val_mae: 0.2909 - val_rmse: 0.3504 - val_smape: 0.6235

Epoch 15/128

144/144 - 4s - 29ms/step - ia: 0.9080 - loss: 0.0453 - mae: 0.1499 - rmse: 0.2122 - smape: 0.3912 - val_ia: 0.8123 - val_loss: 0.1198 - val_mae: 0.2653 - val_rmse: 0.3207 - val_smape: 0.5911

Epoch 16/128

144/144 - 5s - 33ms/step - ia: 0.9154 - loss: 0.0388 - mae: 0.1381 - rmse: 0.1960 - smape: 0.3717 - val_ia: 0.8262 - val_loss: 0.1018 - val_mae: 0.2430 - val_rmse: 0.2955 - val_smape: 0.5596

Epoch 17/128

144/144 - 5s - 32ms/step - ia: 0.9213 - loss: 0.0339 - mae: 0.1287 - rmse: 0.1832 - smape: 0.3532 - val_ia: 0.8365 - val_loss: 0.0888 - val_mae: 0.2267 - val_rmse: 0.2763 - val_smape: 0.5375

Epoch 18/128

144/144 - 4s - 28ms/step - ia: 0.9267 - loss: 0.0298 - mae: 0.1201 - rmse: 0.1714 - smape: 0.3353 - val_ia: 0.8487 - val_loss: 0.0744 - val_mae: 0.2076 - val_rmse: 0.2543 - val_smape: 0.5123

Epoch 19/128

144/144 - 4s - 30ms/step - ia: 0.9317 - loss: 0.0261 - mae: 0.1120 - rmse: 0.1605 - smape: 0.3180 - val_ia: 0.8631 - val_loss: 0.0600 - val_mae: 0.1860 - val_rmse: 0.2305 - val_smape: 0.4805

Epoch 20/128

144/144 - 5s - 32ms/step - ia: 0.9373 - loss: 0.0226 - mae: 0.1029 - rmse: 0.1494 - smape: 0.2980 - val_ia: 0.8768 - val_loss: 0.0492 - val_mae: 0.1667 - val_rmse: 0.2103 - val_smape: 0.4543

Epoch 21/128

144/144 - 5s - 33ms/step - ia: 0.9428 - loss: 0.0191 - mae: 0.0939 - rmse: 0.1375 - smape: 0.2786 - val_ia: 0.8901 - val_loss: 0.0394 - val_mae: 0.1480 - val_rmse: 0.1898 - val_smape: 0.4252

Epoch 22/128

144/144 - 5s - 31ms/step - ia: 0.9463 - loss: 0.0169 - mae: 0.0883 - rmse: 0.1291 - smape: 0.2633 - val_ia: 0.8978 - val_loss: 0.0333 - val_mae: 0.1373 - val_rmse: 0.1757 - val_smape: 0.4052

Epoch 23/128

144/144 - 5s - 31ms/step - ia: 0.9491 - loss: 0.0152 - mae: 0.0837 - rmse: 0.1223 - smape: 0.2513 - val_ia: 0.9051 - val_loss: 0.0282 - val_mae: 0.1272 - val_rmse: 0.1626 - val_smape: 0.3800

Epoch 24/128

144/144 - 5s - 32ms/step - ia: 0.9516 - loss: 0.0137 - mae: 0.0795 - rmse: 0.1167 - smape: 0.2413 - val_ia: 0.9111 - val_loss: 0.0244 - val_mae: 0.1186 - val_rmse: 0.1521 - val_smape: 0.3593

Epoch 25/128

144/144 - 4s - 29ms/step - ia: 0.9539 - loss: 0.0126 - mae: 0.0759 - rmse: 0.1112 - smape: 0.2326 - val_ia: 0.9168 - val_loss: 0.0212 - val_mae: 0.1109 - val_rmse: 0.1422 - val_smape: 0.3348

Epoch 26/128

144/144 - 6s - 39ms/step - ia: 0.9558 - loss: 0.0115 - mae: 0.0726 - rmse: 0.1064 - smape: 0.2255 - val_ia: 0.9228 - val_loss: 0.0181 - val_mae: 0.1022 - val_rmse: 0.1324 - val_smape: 0.3110

Epoch 27/128

144/144 - 5s - 33ms/step - ia: 0.9576 - loss: 0.0107 - mae: 0.0698 - rmse: 0.1025 - smape: 0.2198 - val_ia: 0.9264 - val_loss: 0.0165 - val_mae: 0.0973 - val_rmse: 0.1265 - val_smape: 0.2968

Epoch 28/128

144/144 - 5s - 32ms/step - ia: 0.9591 - loss: 0.0100 - mae: 0.0674 - rmse: 0.0990 - smape: 0.2149 - val_ia: 0.9306 - val_loss: 0.0148 - val_mae: 0.0920 - val_rmse: 0.1198 - val_smape: 0.2767

Epoch 29/128

144/144 - 5s - 36ms/step - ia: 0.9604 - loss: 0.0094 - mae: 0.0652 - rmse: 0.0957 - smape: 0.2096 - val_ia: 0.9336 - val_loss: 0.0135 - val_mae: 0.0875 - val_rmse: 0.1150 - val_smape: 0.2655

Epoch 30/128

144/144 - 4s - 30ms/step - ia: 0.9616 - loss: 0.0088 - mae: 0.0633 - rmse: 0.0929 - smape: 0.2047 - val_ia: 0.9357 - val_loss: 0.0128 - val_mae: 0.0846 - val_rmse: 0.1117 - val_smape: 0.2569

Epoch 31/128

144/144 - 5s - 34ms/step - ia: 0.9628 - loss: 0.0083 - mae: 0.0615 - rmse: 0.0898 - smape: 0.2010 - val_ia: 0.9394 - val_loss: 0.0113 - val_mae: 0.0800 - val_rmse: 0.1053 - val_smape: 0.2397

Epoch 32/128

144/144 - 5s - 32ms/step - ia: 0.9639 - loss: 0.0078 - mae: 0.0594 - rmse: 0.0874 - smape: 0.1960 - val_ia: 0.9412 - val_loss: 0.0107 - val_mae: 0.0774 - val_rmse: 0.1026 - val_smape: 0.2332

Epoch 33/128

144/144 - 5s - 32ms/step - ia: 0.9650 - loss: 0.0074 - mae: 0.0578 - rmse: 0.0848 - smape: 0.1919 - val_ia: 0.9439 - val_loss: 0.0099 - val_mae: 0.0739 - val_rmse: 0.0985 - val_smape: 0.2217

Epoch 34/128

144/144 - 5s - 32ms/step - ia: 0.9658 - loss: 0.0071 - mae: 0.0564 - rmse: 0.0829 - smape: 0.1883 - val_ia: 0.9454 - val_loss: 0.0094 - val_mae: 0.0720 - val_rmse: 0.0959 - val_smape: 0.2147

Epoch 35/128

144/144 - 5s - 36ms/step - ia: 0.9665 - loss: 0.0068 - mae: 0.0553 - rmse: 0.0813 - smape: 0.1846 - val_ia: 0.9479 - val_loss: 0.0086 - val_mae: 0.0688 - val_rmse: 0.0922 - val_smape: 0.2037

Epoch 36/128

144/144 - 4s - 31ms/step - ia: 0.9672 - loss: 0.0065 - mae: 0.0541 - rmse: 0.0794 - smape: 0.1820 - val_ia: 0.9494 - val_loss: 0.0082 - val_mae: 0.0671 - val_rmse: 0.0900 - val_smape: 0.1970

Epoch 37/128

144/144 - 5s - 33ms/step - ia: 0.9679 - loss: 0.0063 - mae: 0.0530 - rmse: 0.0779 - smape: 0.1784 - val_ia: 0.9508 - val_loss: 0.0078 - val_mae: 0.0653 - val_rmse: 0.0877 - val_smape: 0.1917

Epoch 38/128

144/144 - 5s - 32ms/step - ia: 0.9686 - loss: 0.0060 - mae: 0.0519 - rmse: 0.0764 - smape: 0.1758 - val_ia: 0.9521 - val_loss: 0.0075 - val_mae: 0.0637 - val_rmse: 0.0858 - val_smape: 0.1860

Epoch 39/128

144/144 - 5s - 32ms/step - ia: 0.9691 - loss: 0.0058 - mae: 0.0510 - rmse: 0.0750 - smape: 0.1735 - val_ia: 0.9521 - val_loss: 0.0074 - val_mae: 0.0636 - val_rmse: 0.0857 - val_smape: 0.1869

Epoch 40/128

144/144 - 4s - 30ms/step - ia: 0.9697 - loss: 0.0056 - mae: 0.0502 - rmse: 0.0738 - smape: 0.1711 - val_ia: 0.9545 - val_loss: 0.0068 - val_mae: 0.0608 - val_rmse: 0.0822 - val_smape: 0.1766

Epoch 41/128

144/144 - 5s - 32ms/step - ia: 0.9701 - loss: 0.0055 - mae: 0.0494 - rmse: 0.0727 - smape: 0.1688 - val_ia: 0.9555 - val_loss: 0.0066 - val_mae: 0.0596 - val_rmse: 0.0805 - val_smape: 0.1731

Epoch 42/128

144/144 - 5s - 32ms/step - ia: 0.9706 - loss: 0.0053 - mae: 0.0486 - rmse: 0.0715 - smape: 0.1666 - val_ia: 0.9561 - val_loss: 0.0064 - val_mae: 0.0588 - val_rmse: 0.0797 - val_smape: 0.1710

Epoch 43/128

144/144 - 4s - 29ms/step - ia: 0.9710 - loss: 0.0052 - mae: 0.0478 - rmse: 0.0710 - smape: 0.1645 - val_ia: 0.9576 - val_loss: 0.0061 - val_mae: 0.0572 - val_rmse: 0.0776 - val_smape: 0.1655

Epoch 44/128

144/144 - 4s - 31ms/step - ia: 0.9715 - loss: 0.0050 - mae: 0.0470 - rmse: 0.0696 - smape: 0.1623 - val_ia: 0.9581 - val_loss: 0.0060 - val_mae: 0.0564 - val_rmse: 0.0767 - val_smape: 0.1638

Epoch 45/128

144/144 - 6s - 40ms/step - ia: 0.9719 - loss: 0.0049 - mae: 0.0465 - rmse: 0.0686 - smape: 0.1609 - val_ia: 0.9568 - val_loss: 0.0062 - val_mae: 0.0581 - val_rmse: 0.0782 - val_smape: 0.1700

Epoch 46/128

144/144 - 5s - 37ms/step - ia: 0.9721 - loss: 0.0048 - mae: 0.0461 - rmse: 0.0679 - smape: 0.1593 - val_ia: 0.9593 - val_loss: 0.0057 - val_mae: 0.0550 - val_rmse: 0.0748 - val_smape: 0.1604

Epoch 47/128

144/144 - 4s - 28ms/step - ia: 0.9726 - loss: 0.0047 - mae: 0.0453 - rmse: 0.0669 - smape: 0.1571 - val_ia: 0.9594 - val_loss: 0.0056 - val_mae: 0.0548 - val_rmse: 0.0744 - val_smape: 0.1596

Epoch 48/128

144/144 - 5s - 36ms/step - ia: 0.9728 - loss: 0.0046 - mae: 0.0448 - rmse: 0.0663 - smape: 0.1558 - val_ia: 0.9606 - val_loss: 0.0054 - val_mae: 0.0534 - val_rmse: 0.0726 - val_smape: 0.1545

Epoch 49/128

144/144 - 5s - 33ms/step - ia: 0.9731 - loss: 0.0045 - mae: 0.0444 - rmse: 0.0656 - smape: 0.1547 - val_ia: 0.9610 - val_loss: 0.0053 - val_mae: 0.0529 - val_rmse: 0.0719 - val_smape: 0.1545

Epoch 50/128

144/144 - 4s - 31ms/step - ia: 0.9735 - loss: 0.0044 - mae: 0.0438 - rmse: 0.0648 - smape: 0.1531 - val_ia: 0.9613 - val_loss: 0.0052 - val_mae: 0.0524 - val_rmse: 0.0713 - val_smape: 0.1533

Epoch 51/128

144/144 - 5s - 31ms/step - ia: 0.9737 - loss: 0.0043 - mae: 0.0434 - rmse: 0.0642 - smape: 0.1520 - val_ia: 0.9611 - val_loss: 0.0052 - val_mae: 0.0526 - val_rmse: 0.0715 - val_smape: 0.1554

Epoch 52/128

144/144 - 4s - 31ms/step - ia: 0.9739 - loss: 0.0043 - mae: 0.0430 - rmse: 0.0637 - smape: 0.1508 - val_ia: 0.9614 - val_loss: 0.0051 - val_mae: 0.0521 - val_rmse: 0.0709 - val_smape: 0.1548

Epoch 53/128

144/144 - 5s - 38ms/step - ia: 0.9743 - loss: 0.0042 - mae: 0.0425 - rmse: 0.0631 - smape: 0.1496 - val_ia: 0.9627 - val_loss: 0.0048 - val_mae: 0.0505 - val_rmse: 0.0688 - val_smape: 0.1485

Epoch 54/128

144/144 - 4s - 31ms/step - ia: 0.9744 - loss: 0.0041 - mae: 0.0422 - rmse: 0.0627 - smape: 0.1486 - val_ia: 0.9632 - val_loss: 0.0047 - val_mae: 0.0499 - val_rmse: 0.0679 - val_smape: 0.1472

Epoch 55/128

144/144 - 5s - 36ms/step - ia: 0.9746 - loss: 0.0041 - mae: 0.0419 - rmse: 0.0620 - smape: 0.1479 - val_ia: 0.9637 - val_loss: 0.0046 - val_mae: 0.0492 - val_rmse: 0.0671 - val_smape: 0.1465

Epoch 56/128

144/144 - 4s - 28ms/step - ia: 0.9748 - loss: 0.0040 - mae: 0.0417 - rmse: 0.0618 - smape: 0.1472 - val_ia: 0.9638 - val_loss: 0.0045 - val_mae: 0.0490 - val_rmse: 0.0667 - val_smape: 0.1455

Epoch 57/128

144/144 - 4s - 29ms/step - ia: 0.9750 - loss: 0.0040 - mae: 0.0414 - rmse: 0.0614 - smape: 0.1466 - val_ia: 0.9634 - val_loss: 0.0046 - val_mae: 0.0493 - val_rmse: 0.0672 - val_smape: 0.1501

Epoch 58/128

144/144 - 4s - 28ms/step - ia: 0.9751 - loss: 0.0039 - mae: 0.0411 - rmse: 0.0611 - smape: 0.1458 - val_ia: 0.9642 - val_loss: 0.0044 - val_mae: 0.0484 - val_rmse: 0.0659 - val_smape: 0.1464

Epoch 59/128

144/144 - 4s - 28ms/step - ia: 0.9753 - loss: 0.0039 - mae: 0.0408 - rmse: 0.0604 - smape: 0.1450 - val_ia: 0.9643 - val_loss: 0.0044 - val_mae: 0.0482 - val_rmse: 0.0656 - val_smape: 0.1471

Epoch 60/128

144/144 - 4s - 30ms/step - ia: 0.9754 - loss: 0.0038 - mae: 0.0407 - rmse: 0.0604 - smape: 0.1443 - val_ia: 0.9652 - val_loss: 0.0042 - val_mae: 0.0471 - val_rmse: 0.0642 - val_smape: 0.1436

Epoch 61/128

144/144 - 5s - 32ms/step - ia: 0.9757 - loss: 0.0038 - mae: 0.0402 - rmse: 0.0600 - smape: 0.1436 - val_ia: 0.9649 - val_loss: 0.0042 - val_mae: 0.0474 - val_rmse: 0.0644 - val_smape: 0.1455

Epoch 62/128

144/144 - 4s - 29ms/step - ia: 0.9757 - loss: 0.0038 - mae: 0.0401 - rmse: 0.0596 - smape: 0.1432 - val_ia: 0.9651 - val_loss: 0.0042 - val_mae: 0.0472 - val_rmse: 0.0643 - val_smape: 0.1449

Epoch 63/128

144/144 - 5s - 32ms/step - ia: 0.9759 - loss: 0.0037 - mae: 0.0398 - rmse: 0.0593 - smape: 0.1426 - val_ia: 0.9656 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0634 - val_smape: 0.1434

Epoch 64/128

144/144 - 5s - 32ms/step - ia: 0.9761 - loss: 0.0037 - mae: 0.0396 - rmse: 0.0588 - smape: 0.1423 - val_ia: 0.9660 - val_loss: 0.0040 - val_mae: 0.0459 - val_rmse: 0.0626 - val_smape: 0.1418

Epoch 65/128

144/144 - 5s - 32ms/step - ia: 0.9761 - loss: 0.0037 - mae: 0.0396 - rmse: 0.0590 - smape: 0.1421 - val_ia: 0.9662 - val_loss: 0.0040 - val_mae: 0.0457 - val_rmse: 0.0623 - val_smape: 0.1419

Epoch 66/128

144/144 - 4s - 30ms/step - ia: 0.9763 - loss: 0.0036 - mae: 0.0392 - rmse: 0.0585 - smape: 0.1414 - val_ia: 0.9643 - val_loss: 0.0043 - val_mae: 0.0481 - val_rmse: 0.0649 - val_smape: 0.1492

Epoch 67/128

144/144 - 5s - 32ms/step - ia: 0.9764 - loss: 0.0036 - mae: 0.0391 - rmse: 0.0584 - smape: 0.1408 - val_ia: 0.9659 - val_loss: 0.0040 - val_mae: 0.0460 - val_rmse: 0.0626 - val_smape: 0.1439

Epoch 68/128

144/144 - 4s - 30ms/step - ia: 0.9765 - loss: 0.0036 - mae: 0.0389 - rmse: 0.0580 - smape: 0.1406 - val_ia: 0.9662 - val_loss: 0.0039 - val_mae: 0.0456 - val_rmse: 0.0622 - val_smape: 0.1436

Epoch 69/128

144/144 - 4s - 25ms/step - ia: 0.9766 - loss: 0.0035 - mae: 0.0387 - rmse: 0.0577 - smape: 0.1399 - val_ia: 0.9662 - val_loss: 0.0039 - val_mae: 0.0456 - val_rmse: 0.0621 - val_smape: 0.1434

Epoch 70/128

144/144 - 3s - 20ms/step - ia: 0.9767 - loss: 0.0035 - mae: 0.0385 - rmse: 0.0574 - smape: 0.1397 - val_ia: 0.9669 - val_loss: 0.0038 - val_mae: 0.0447 - val_rmse: 0.0610 - val_smape: 0.1408

Epoch 71/128

144/144 - 4s - 31ms/step - ia: 0.9768 - loss: 0.0035 - mae: 0.0383 - rmse: 0.0573 - smape: 0.1387 - val_ia: 0.9661 - val_loss: 0.0039 - val_mae: 0.0457 - val_rmse: 0.0621 - val_smape: 0.1454

Epoch 72/128

144/144 - 5s - 35ms/step - ia: 0.9768 - loss: 0.0035 - mae: 0.0382 - rmse: 0.0573 - smape: 0.1387 - val_ia: 0.9667 - val_loss: 0.0038 - val_mae: 0.0448 - val_rmse: 0.0611 - val_smape: 0.1426

Epoch 73/128

144/144 - 4s - 31ms/step - ia: 0.9769 - loss: 0.0034 - mae: 0.0381 - rmse: 0.0569 - smape: 0.1389 - val_ia: 0.9661 - val_loss: 0.0039 - val_mae: 0.0457 - val_rmse: 0.0619 - val_smape: 0.1447

Epoch 74/128

144/144 - 5s - 32ms/step - ia: 0.9770 - loss: 0.0034 - mae: 0.0380 - rmse: 0.0568 - smape: 0.1381 - val_ia: 0.9669 - val_loss: 0.0038 - val_mae: 0.0447 - val_rmse: 0.0608 - val_smape: 0.1408

Epoch 75/128

144/144 - 5s - 37ms/step - ia: 0.9771 - loss: 0.0034 - mae: 0.0378 - rmse: 0.0566 - smape: 0.1380 - val_ia: 0.9678 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0593 - val_smape: 0.1389

Epoch 76/128

144/144 - 10s - 69ms/step - ia: 0.9772 - loss: 0.0034 - mae: 0.0377 - rmse: 0.0564 - smape: 0.1374 - val_ia: 0.9677 - val_loss: 0.0036 - val_mae: 0.0436 - val_rmse: 0.0595 - val_smape: 0.1388

Epoch 77/128

144/144 - 5s - 36ms/step - ia: 0.9771 - loss: 0.0034 - mae: 0.0378 - rmse: 0.0564 - smape: 0.1375 - val_ia: 0.9675 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0596 - val_smape: 0.1412

Epoch 78/128

144/144 - 5s - 32ms/step - ia: 0.9773 - loss: 0.0034 - mae: 0.0375 - rmse: 0.0563 - smape: 0.1367 - val_ia: 0.9676 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0595 - val_smape: 0.1395

Epoch 79/128

144/144 - 4s - 31ms/step - ia: 0.9774 - loss: 0.0033 - mae: 0.0375 - rmse: 0.0561 - smape: 0.1367 - val_ia: 0.9684 - val_loss: 0.0035 - val_mae: 0.0427 - val_rmse: 0.0584 - val_smape: 0.1366

Epoch 80/128

144/144 - 4s - 28ms/step - ia: 0.9774 - loss: 0.0033 - mae: 0.0374 - rmse: 0.0559 - smape: 0.1365 - val_ia: 0.9682 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0586 - val_smape: 0.1383

Epoch 81/128

144/144 - 4s - 28ms/step - ia: 0.9774 - loss: 0.0033 - mae: 0.0373 - rmse: 0.0559 - smape: 0.1360 - val_ia: 0.9684 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0583 - val_smape: 0.1338

Epoch 82/128

144/144 - 5s - 32ms/step - ia: 0.9774 - loss: 0.0033 - mae: 0.0374 - rmse: 0.0559 - smape: 0.1364 - val_ia: 0.9677 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0592 - val_smape: 0.1405

Epoch 83/128

144/144 - 5s - 34ms/step - ia: 0.9776 - loss: 0.0033 - mae: 0.0370 - rmse: 0.0554 - smape: 0.1354 - val_ia: 0.9686 - val_loss: 0.0034 - val_mae: 0.0424 - val_rmse: 0.0580 - val_smape: 0.1365

Epoch 84/128

144/144 - 5s - 34ms/step - ia: 0.9776 - loss: 0.0033 - mae: 0.0370 - rmse: 0.0555 - smape: 0.1352 - val_ia: 0.9690 - val_loss: 0.0034 - val_mae: 0.0419 - val_rmse: 0.0574 - val_smape: 0.1341

Epoch 85/128

144/144 - 5s - 35ms/step - ia: 0.9777 - loss: 0.0033 - mae: 0.0368 - rmse: 0.0554 - smape: 0.1348 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0577 - val_smape: 0.1347

Epoch 86/128

144/144 - 5s - 33ms/step - ia: 0.9777 - loss: 0.0032 - mae: 0.0368 - rmse: 0.0553 - smape: 0.1348 - val_ia: 0.9684 - val_loss: 0.0035 - val_mae: 0.0427 - val_rmse: 0.0583 - val_smape: 0.1375

Epoch 87/128

144/144 - 5s - 32ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0367 - rmse: 0.0551 - smape: 0.1346 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0575 - val_smape: 0.1346

Epoch 88/128

144/144 - 5s - 33ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0368 - rmse: 0.0550 - smape: 0.1344 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0574 - val_smape: 0.1362

Epoch 89/128

144/144 - 5s - 33ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0367 - rmse: 0.0549 - smape: 0.1340 - val_ia: 0.9683 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0582 - val_smape: 0.1372

Epoch 90/128

144/144 - 5s - 34ms/step - ia: 0.9779 - loss: 0.0032 - mae: 0.0366 - rmse: 0.0549 - smape: 0.1341 - val_ia: 0.9696 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0564 - val_smape: 0.1319

Epoch 91/128

144/144 - 4s - 29ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0366 - rmse: 0.0550 - smape: 0.1341 - val_ia: 0.9692 - val_loss: 0.0033 - val_mae: 0.0417 - val_rmse: 0.0570 - val_smape: 0.1352

Epoch 92/128

144/144 - 4s - 26ms/step - ia: 0.9780 - loss: 0.0032 - mae: 0.0365 - rmse: 0.0547 - smape: 0.1335 - val_ia: 0.9697 - val_loss: 0.0032 - val_mae: 0.0410 - val_rmse: 0.0562 - val_smape: 0.1322

Epoch 93/128

144/144 - 3s - 22ms/step - ia: 0.9779 - loss: 0.0032 - mae: 0.0365 - rmse: 0.0547 - smape: 0.1338 - val_ia: 0.9697 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0561 - val_smape: 0.1300

Epoch 94/128

144/144 - 3s - 22ms/step - ia: 0.9780 - loss: 0.0032 - mae: 0.0363 - rmse: 0.0545 - smape: 0.1334 - val_ia: 0.9686 - val_loss: 0.0034 - val_mae: 0.0424 - val_rmse: 0.0577 - val_smape: 0.1378

Epoch 95/128

144/144 - 5s - 35ms/step - ia: 0.9781 - loss: 0.0032 - mae: 0.0363 - rmse: 0.0543 - smape: 0.1330 - val_ia: 0.9700 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0558 - val_smape: 0.1317

Epoch 96/128

144/144 - 3s - 21ms/step - ia: 0.9781 - loss: 0.0032 - mae: 0.0363 - rmse: 0.0545 - smape: 0.1329 - val_ia: 0.9692 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0570 - val_smape: 0.1348

Epoch 97/128

144/144 - 3s - 21ms/step - ia: 0.9781 - loss: 0.0032 - mae: 0.0363 - rmse: 0.0544 - smape: 0.1332 - val_ia: 0.9701 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0556 - val_smape: 0.1316

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 21s - 146ms/step - ia: 0.5674 - loss: 0.4380 - mae: 0.4979 - rmse: 0.6232 - smape: 1.0178 - val_ia: 0.7694 - val_loss: 0.1547 - val_mae: 0.3115 - val_rmse: 0.3840 - val_smape: 0.6431

Epoch 2/128

144/144 - 4s - 30ms/step - ia: 0.8359 - loss: 0.1205 - mae: 0.2623 - rmse: 0.3456 - smape: 0.5195 - val_ia: 0.8325 - val_loss: 0.0743 - val_mae: 0.2082 - val_rmse: 0.2686 - val_smape: 0.4386

Epoch 3/128

144/144 - 4s - 29ms/step - ia: 0.8611 - loss: 0.0886 - mae: 0.2236 - rmse: 0.2970 - smape: 0.4568 - val_ia: 0.8248 - val_loss: 0.0745 - val_mae: 0.2122 - val_rmse: 0.2682 - val_smape: 0.4107

Epoch 4/128

144/144 - 4s - 30ms/step - ia: 0.8738 - loss: 0.0751 - mae: 0.2041 - rmse: 0.2733 - smape: 0.4231 - val_ia: 0.8530 - val_loss: 0.0557 - val_mae: 0.1803 - val_rmse: 0.2308 - val_smape: 0.3440

Epoch 5/128

144/144 - 4s - 31ms/step - ia: 0.8807 - loss: 0.0673 - mae: 0.1931 - rmse: 0.2587 - smape: 0.4012 - val_ia: 0.8513 - val_loss: 0.0530 - val_mae: 0.1810 - val_rmse: 0.2276 - val_smape: 0.3449

Epoch 6/128

144/144 - 5s - 32ms/step - ia: 0.8860 - loss: 0.0629 - mae: 0.1848 - rmse: 0.2499 - smape: 0.3849 - val_ia: 0.8324 - val_loss: 0.0628 - val_mae: 0.2030 - val_rmse: 0.2471 - val_smape: 0.3771

Epoch 7/128

144/144 - 4s - 31ms/step - ia: 0.8912 - loss: 0.0579 - mae: 0.1765 - rmse: 0.2401 - smape: 0.3670 - val_ia: 0.8547 - val_loss: 0.0500 - val_mae: 0.1801 - val_rmse: 0.2200 - val_smape: 0.3359

Epoch 8/128

144/144 - 4s - 30ms/step - ia: 0.8941 - loss: 0.0552 - mae: 0.1718 - rmse: 0.2342 - smape: 0.3590 - val_ia: 0.8251 - val_loss: 0.0673 - val_mae: 0.2129 - val_rmse: 0.2556 - val_smape: 0.3852

Epoch 9/128

144/144 - 4s - 24ms/step - ia: 0.8966 - loss: 0.0534 - mae: 0.1679 - rmse: 0.2308 - smape: 0.3475 - val_ia: 0.8385 - val_loss: 0.0583 - val_mae: 0.1984 - val_rmse: 0.2380 - val_smape: 0.3666

Epoch 10/128

144/144 - 5s - 36ms/step - ia: 0.8992 - loss: 0.0511 - mae: 0.1637 - rmse: 0.2256 - smape: 0.3404 - val_ia: 0.8237 - val_loss: 0.0692 - val_mae: 0.2158 - val_rmse: 0.2581 - val_smape: 0.4025

Epoch 11/128

144/144 - 5s - 36ms/step - ia: 0.9007 - loss: 0.0495 - mae: 0.1612 - rmse: 0.2221 - smape: 0.3382 - val_ia: 0.8287 - val_loss: 0.0657 - val_mae: 0.2115 - val_rmse: 0.2520 - val_smape: 0.3959

Epoch 12/128

144/144 - 5s - 35ms/step - ia: 0.9019 - loss: 0.0484 - mae: 0.1594 - rmse: 0.2194 - smape: 0.3313 - val_ia: 0.8309 - val_loss: 0.0653 - val_mae: 0.2103 - val_rmse: 0.2503 - val_smape: 0.4115

Epoch 13/128

144/144 - 5s - 32ms/step - ia: 0.9029 - loss: 0.0477 - mae: 0.1578 - rmse: 0.2176 - smape: 0.3299 - val_ia: 0.8180 - val_loss: 0.0739 - val_mae: 0.2234 - val_rmse: 0.2653 - val_smape: 0.4351

Epoch 14/128

144/144 - 5s - 37ms/step - ia: 0.9044 - loss: 0.0465 - mae: 0.1555 - rmse: 0.2151 - smape: 0.3235 - val_ia: 0.8247 - val_loss: 0.0670 - val_mae: 0.2147 - val_rmse: 0.2538 - val_smape: 0.4055

Epoch 15/128

144/144 - 5s - 34ms/step - ia: 0.9062 - loss: 0.0448 - mae: 0.1529 - rmse: 0.2108 - smape: 0.3202 - val_ia: 0.8248 - val_loss: 0.0664 - val_mae: 0.2155 - val_rmse: 0.2538 - val_smape: 0.4204

Epoch 16/128

144/144 - 5s - 34ms/step - ia: 0.9061 - loss: 0.0451 - mae: 0.1528 - rmse: 0.2117 - smape: 0.3160 - val_ia: 0.8082 - val_loss: 0.0794 - val_mae: 0.2330 - val_rmse: 0.2767 - val_smape: 0.4404

Epoch 17/128

144/144 - 5s - 34ms/step - ia: 0.9068 - loss: 0.0444 - mae: 0.1517 - rmse: 0.2103 - smape: 0.3146 - val_ia: 0.8084 - val_loss: 0.0796 - val_mae: 0.2329 - val_rmse: 0.2767 - val_smape: 0.4430

Epoch 18/128

144/144 - 5s - 34ms/step - ia: 0.9065 - loss: 0.0449 - mae: 0.1523 - rmse: 0.2109 - smape: 0.3157 - val_ia: 0.8098 - val_loss: 0.0767 - val_mae: 0.2308 - val_rmse: 0.2722 - val_smape: 0.4464

Epoch 19/128

144/144 - 4s - 29ms/step - ia: 0.9075 - loss: 0.0440 - mae: 0.1504 - rmse: 0.2092 - smape: 0.3126 - val_ia: 0.8174 - val_loss: 0.0757 - val_mae: 0.2269 - val_rmse: 0.2678 - val_smape: 0.4675

Epoch 20/128

144/144 - 4s - 29ms/step - ia: 0.9093 - loss: 0.0421 - mae: 0.1475 - rmse: 0.2048 - smape: 0.3104 - val_ia: 0.8249 - val_loss: 0.0693 - val_mae: 0.2171 - val_rmse: 0.2572 - val_smape: 0.4406

Epoch 21/128

144/144 - 4s - 31ms/step - ia: 0.9098 - loss: 0.0419 - mae: 0.1468 - rmse: 0.2043 - smape: 0.3047 - val_ia: 0.8084 - val_loss: 0.0825 - val_mae: 0.2358 - val_rmse: 0.2803 - val_smape: 0.4813

Epoch 22/128

144/144 - 5s - 32ms/step - ia: 0.9092 - loss: 0.0423 - mae: 0.1478 - rmse: 0.2053 - smape: 0.3065 - val_ia: 0.7992 - val_loss: 0.0879 - val_mae: 0.2455 - val_rmse: 0.2896 - val_smape: 0.5024

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:46 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step

 64%|██████▍   | 32/50 [6:34:48<2:12:59, 443.29s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

574/574 - 94s - 165ms/step - ia: 0.8687 - loss: 0.0840 - mae: 0.2031 - rmse: 0.2671 - smape: 0.4163 - val_ia: 0.7628 - val_loss: 0.0637 - val_mae: 0.2164 - val_rmse: 0.2462 - val_smape: 0.4640

Epoch 2/128

574/574 - 38s - 66ms/step - ia: 0.9146 - loss: 0.0354 - mae: 0.1384 - rmse: 0.1866 - smape: 0.3017 - val_ia: 0.8085 - val_loss: 0.0448 - val_mae: 0.1799 - val_rmse: 0.2059 - val_smape: 0.4186

Epoch 3/128

574/574 - 33s - 58ms/step - ia: 0.9190 - loss: 0.0321 - mae: 0.1315 - rmse: 0.1776 - smape: 0.2887 - val_ia: 0.8546 - val_loss: 0.0282 - val_mae: 0.1392 - val_rmse: 0.1634 - val_smape: 0.3754

Epoch 4/128

574/574 - 37s - 64ms/step - ia: 0.9213 - loss: 0.0306 - mae: 0.1277 - rmse: 0.1731 - smape: 0.2818 - val_ia: 0.8156 - val_loss: 0.0413 - val_mae: 0.1728 - val_rmse: 0.1975 - val_smape: 0.3621

Epoch 5/128

574/574 - 37s - 64ms/step - ia: 0.9233 - loss: 0.0291 - mae: 0.1247 - rmse: 0.1689 - smape: 0.2753 - val_ia: 0.9081 - val_loss: 0.0133 - val_mae: 0.0900 - val_rmse: 0.1114 - val_smape: 0.1859

Epoch 6/128

574/574 - 38s - 66ms/step - ia: 0.9234 - loss: 0.0293 - mae: 0.1246 - rmse: 0.1694 - smape: 0.2722 - val_ia: 0.8104 - val_loss: 0.0425 - val_mae: 0.1751 - val_rmse: 0.2002 - val_smape: 0.3437

Epoch 7/128

574/574 - 37s - 65ms/step - ia: 0.9248 - loss: 0.0280 - mae: 0.1221 - rmse: 0.1659 - smape: 0.2686 - val_ia: 0.8538 - val_loss: 0.0262 - val_mae: 0.1328 - val_rmse: 0.1563 - val_smape: 0.2704

Epoch 8/128

574/574 - 40s - 69ms/step - ia: 0.9255 - loss: 0.0278 - mae: 0.1211 - rmse: 0.1649 - smape: 0.2653 - val_ia: 0.8177 - val_loss: 0.0367 - val_mae: 0.1622 - val_rmse: 0.1822 - val_smape: 0.4089

Epoch 9/128

574/574 - 35s - 62ms/step - ia: 0.9265 - loss: 0.0268 - mae: 0.1195 - rmse: 0.1621 - smape: 0.2626 - val_ia: 0.9073 - val_loss: 0.0113 - val_mae: 0.0871 - val_rmse: 0.1040 - val_smape: 0.2508

Epoch 10/128

574/574 - 31s - 54ms/step - ia: 0.9263 - loss: 0.0270 - mae: 0.1200 - rmse: 0.1627 - smape: 0.2646 - val_ia: 0.8801 - val_loss: 0.0203 - val_mae: 0.1169 - val_rmse: 0.1374 - val_smape: 0.2665

Epoch 11/128

574/574 - 37s - 65ms/step - ia: 0.9270 - loss: 0.0266 - mae: 0.1185 - rmse: 0.1613 - smape: 0.2607 - val_ia: 0.8862 - val_loss: 0.0164 - val_mae: 0.1084 - val_rmse: 0.1258 - val_smape: 0.3105

Epoch 12/128

574/574 - 39s - 67ms/step - ia: 0.9275 - loss: 0.0263 - mae: 0.1176 - rmse: 0.1605 - smape: 0.2607 - val_ia: 0.8478 - val_loss: 0.0257 - val_mae: 0.1406 - val_rmse: 0.1570 - val_smape: 0.2982

Epoch 13/128

574/574 - 40s - 69ms/step - ia: 0.9276 - loss: 0.0264 - mae: 0.1176 - rmse: 0.1608 - smape: 0.2579 - val_ia: 0.8710 - val_loss: 0.0194 - val_mae: 0.1175 - val_rmse: 0.1343 - val_smape: 0.2958

Epoch 14/128

574/574 - 35s - 61ms/step - ia: 0.9276 - loss: 0.0259 - mae: 0.1175 - rmse: 0.1593 - smape: 0.2588 - val_ia: 0.8471 - val_loss: 0.0271 - val_mae: 0.1401 - val_rmse: 0.1605 - val_smape: 0.3238

Epoch 15/128

574/574 - 34s - 59ms/step - ia: 0.9283 - loss: 0.0260 - mae: 0.1167 - rmse: 0.1594 - smape: 0.2549 - val_ia: 0.8648 - val_loss: 0.0234 - val_mae: 0.1287 - val_rmse: 0.1491 - val_smape: 0.3322

Epoch 16/128

574/574 - 37s - 64ms/step - ia: 0.9286 - loss: 0.0257 - mae: 0.1162 - rmse: 0.1586 - smape: 0.2554 - val_ia: 0.8943 - val_loss: 0.0146 - val_mae: 0.1004 - val_rmse: 0.1173 - val_smape: 0.2211

Epoch 17/128

574/574 - 37s - 64ms/step - ia: 0.9289 - loss: 0.0256 - mae: 0.1156 - rmse: 0.1583 - smape: 0.2537 - val_ia: 0.8600 - val_loss: 0.0234 - val_mae: 0.1317 - val_rmse: 0.1503 - val_smape: 0.3261

Epoch 18/128

574/574 - 37s - 64ms/step - ia: 0.9289 - loss: 0.0253 - mae: 0.1156 - rmse: 0.1574 - smape: 0.2539 - val_ia: 0.8589 - val_loss: 0.0265 - val_mae: 0.1334 - val_rmse: 0.1571 - val_smape: 0.2924

Epoch 19/128

574/574 - 33s - 58ms/step - ia: 0.9293 - loss: 0.0252 - mae: 0.1150 - rmse: 0.1570 - smape: 0.2516 - val_ia: 0.9048 - val_loss: 0.0189 - val_mae: 0.0964 - val_rmse: 0.1252 - val_smape: 0.2085

Epoch 20/128

574/574 - 36s - 63ms/step - ia: 0.9289 - loss: 0.0255 - mae: 0.1157 - rmse: 0.1581 - smape: 0.2548 - val_ia: 0.8677 - val_loss: 0.0213 - val_mae: 0.1248 - val_rmse: 0.1429 - val_smape: 0.2917

Epoch 21/128

574/574 - 36s - 62ms/step - ia: 0.9290 - loss: 0.0253 - mae: 0.1153 - rmse: 0.1574 - smape: 0.2532 - val_ia: 0.8517 - val_loss: 0.0297 - val_mae: 0.1411 - val_rmse: 0.1658 - val_smape: 0.3019

Epoch 22/128

574/574 - 36s - 63ms/step - ia: 0.9300 - loss: 0.0249 - mae: 0.1138 - rmse: 0.1561 - smape: 0.2498 - val_ia: 0.8471 - val_loss: 0.0280 - val_mae: 0.1411 - val_rmse: 0.1629 - val_smape: 0.2722

Epoch 23/128

574/574 - 38s - 66ms/step - ia: 0.9292 - loss: 0.0252 - mae: 0.1152 - rmse: 0.1571 - smape: 0.2546 - val_ia: 0.8693 - val_loss: 0.0260 - val_mae: 0.1250 - val_rmse: 0.1529 - val_smape: 0.2360

Epoch 24/128

574/574 - 35s - 60ms/step - ia: 0.9294 - loss: 0.0252 - mae: 0.1147 - rmse: 0.1570 - smape: 0.2517 - val_ia: 0.8818 - val_loss: 0.0280 - val_mae: 0.1176 - val_rmse: 0.1522 - val_smape: 0.2325

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:44 5s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step

 66%|██████▌   | 33/50 [6:50:30<2:48:02, 593.10s/trial, best loss: 0.002081705785395108]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

144/144 - 33s - 229ms/step - ia: 0.9208 - loss: 0.0439 - mae: 0.1276 - rmse: 0.1665 - smape: 0.2928 - val_ia: 0.9661 - val_loss: 0.0042 - val_mae: 0.0453 - val_rmse: 0.0644 - val_smape: 0.1330

Epoch 2/32

144/144 - 6s - 42ms/step - ia: 0.9577 - loss: 0.0092 - mae: 0.0698 - rmse: 0.0952 - smape: 0.1881 - val_ia: 0.9647 - val_loss: 0.0042 - val_mae: 0.0473 - val_rmse: 0.0640 - val_smape: 0.1344

Epoch 3/32

144/144 - 6s - 40ms/step - ia: 0.9612 - loss: 0.0079 - mae: 0.0641 - rmse: 0.0878 - smape: 0.1766 - val_ia: 0.9676 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0597 - val_smape: 0.1285

Epoch 4/32

144/144 - 11s - 73ms/step - ia: 0.9629 - loss: 0.0072 - mae: 0.0614 - rmse: 0.0839 - smape: 0.1705 - val_ia: 0.9620 - val_loss: 0.0044 - val_mae: 0.0501 - val_rmse: 0.0647 - val_smape: 0.1740

Epoch 5/32

144/144 - 6s - 42ms/step - ia: 0.9644 - loss: 0.0067 - mae: 0.0588 - rmse: 0.0807 - smape: 0.1623 - val_ia: 0.9621 - val_loss: 0.0045 - val_mae: 0.0496 - val_rmse: 0.0664 - val_smape: 0.1463

Epoch 6/32

144/144 - 6s - 40ms/step - ia: 0.9645 - loss: 0.0066 - mae: 0.0586 - rmse: 0.0806 - smape: 0.1636 - val_ia: 0.9658 - val_loss: 0.0038 - val_mae: 0.0448 - val_rmse: 0.0611 - val_smape: 0.1221

Epoch 7/32

144/144 - 5s - 36ms/step - ia: 0.9660 - loss: 0.0062 - mae: 0.0563 - rmse: 0.0779 - smape: 0.1590 - val_ia: 0.9730 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0517 - val_smape: 0.1182

Epoch 8/32

144/144 - 6s - 41ms/step - ia: 0.9660 - loss: 0.0062 - mae: 0.0562 - rmse: 0.0777 - smape: 0.1568 - val_ia: 0.9647 - val_loss: 0.0038 - val_mae: 0.0473 - val_rmse: 0.0611 - val_smape: 0.1531

Epoch 9/32

144/144 - 6s - 41ms/step - ia: 0.9660 - loss: 0.0062 - mae: 0.0563 - rmse: 0.0778 - smape: 0.1566 - val_ia: 0.9613 - val_loss: 0.0049 - val_mae: 0.0519 - val_rmse: 0.0689 - val_smape: 0.1469

Epoch 10/32

144/144 - 6s - 40ms/step - ia: 0.9648 - loss: 0.0066 - mae: 0.0581 - rmse: 0.0800 - smape: 0.1600 - val_ia: 0.9739 - val_loss: 0.0026 - val_mae: 0.0353 - val_rmse: 0.0502 - val_smape: 0.1142

Epoch 11/32

144/144 - 6s - 42ms/step - ia: 0.9660 - loss: 0.0062 - mae: 0.0561 - rmse: 0.0775 - smape: 0.1568 - val_ia: 0.9542 - val_loss: 0.0060 - val_mae: 0.0605 - val_rmse: 0.0771 - val_smape: 0.1412

Epoch 12/32

144/144 - 6s - 40ms/step - ia: 0.9670 - loss: 0.0058 - mae: 0.0545 - rmse: 0.0755 - smape: 0.1518 - val_ia: 0.9734 - val_loss: 0.0026 - val_mae: 0.0356 - val_rmse: 0.0500 - val_smape: 0.1143

Epoch 13/32

144/144 - 5s - 37ms/step - ia: 0.9661 - loss: 0.0062 - mae: 0.0560 - rmse: 0.0774 - smape: 0.1554 - val_ia: 0.9658 - val_loss: 0.0038 - val_mae: 0.0470 - val_rmse: 0.0616 - val_smape: 0.1302

Epoch 14/32

144/144 - 6s - 42ms/step - ia: 0.9668 - loss: 0.0059 - mae: 0.0549 - rmse: 0.0761 - smape: 0.1529 - val_ia: 0.9716 - val_loss: 0.0030 - val_mae: 0.0387 - val_rmse: 0.0544 - val_smape: 0.1105

Epoch 15/32

144/144 - 6s - 41ms/step - ia: 0.9670 - loss: 0.0058 - mae: 0.0545 - rmse: 0.0754 - smape: 0.1546 - val_ia: 0.9642 - val_loss: 0.0039 - val_mae: 0.0483 - val_rmse: 0.0612 - val_smape: 0.1512

Epoch 16/32

144/144 - 6s - 40ms/step - ia: 0.9672 - loss: 0.0058 - mae: 0.0542 - rmse: 0.0751 - smape: 0.1520 - val_ia: 0.9714 - val_loss: 0.0028 - val_mae: 0.0383 - val_rmse: 0.0523 - val_smape: 0.1228

Epoch 17/32

144/144 - 5s - 36ms/step - ia: 0.9667 - loss: 0.0060 - mae: 0.0551 - rmse: 0.0764 - smape: 0.1512 - val_ia: 0.9599 - val_loss: 0.0048 - val_mae: 0.0539 - val_rmse: 0.0683 - val_smape: 0.1402

Epoch 18/32

144/144 - 6s - 41ms/step - ia: 0.9673 - loss: 0.0058 - mae: 0.0541 - rmse: 0.0752 - smape: 0.1512 - val_ia: 0.9696 - val_loss: 0.0034 - val_mae: 0.0412 - val_rmse: 0.0580 - val_smape: 0.1112

Epoch 19/32

144/144 - 6s - 41ms/step - ia: 0.9667 - loss: 0.0060 - mae: 0.0551 - rmse: 0.0764 - smape: 0.1531 - val_ia: 0.9744 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0492 - val_smape: 0.1096

Epoch 20/32

144/144 - 6s - 40ms/step - ia: 0.9675 - loss: 0.0057 - mae: 0.0537 - rmse: 0.0747 - smape: 0.1493 - val_ia: 0.9730 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0509 - val_smape: 0.1122

Epoch 21/32

144/144 - 6s - 41ms/step - ia: 0.9684 - loss: 0.0055 - mae: 0.0522 - rmse: 0.0728 - smape: 0.1475 - val_ia: 0.9736 - val_loss: 0.0026 - val_mae: 0.0358 - val_rmse: 0.0504 - val_smape: 0.1129

Epoch 22/32

144/144 - 10s - 71ms/step - ia: 0.9686 - loss: 0.0054 - mae: 0.0520 - rmse: 0.0726 - smape: 0.1471 - val_ia: 0.9681 - val_loss: 0.0033 - val_mae: 0.0424 - val_rmse: 0.0565 - val_smape: 0.1275

Epoch 23/32

144/144 - 6s - 40ms/step - ia: 0.9681 - loss: 0.0056 - mae: 0.0527 - rmse: 0.0736 - smape: 0.1486 - val_ia: 0.9722 - val_loss: 0.0027 - val_mae: 0.0372 - val_rmse: 0.0509 - val_smape: 0.1170

Epoch 24/32

144/144 - 6s - 40ms/step - ia: 0.9673 - loss: 0.0058 - mae: 0.0541 - rmse: 0.0751 - smape: 0.1496 - val_ia: 0.9697 - val_loss: 0.0030 - val_mae: 0.0400 - val_rmse: 0.0540 - val_smape: 0.1245

Epoch 25/32

144/144 - 5s - 35ms/step - ia: 0.9674 - loss: 0.0057 - mae: 0.0539 - rmse: 0.0748 - smape: 0.1507 - val_ia: 0.9720 - val_loss: 0.0029 - val_mae: 0.0379 - val_rmse: 0.0535 - val_smape: 0.1110

Epoch 26/32

144/144 - 5s - 33ms/step - ia: 0.9683 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0728 - smape: 0.1482 - val_ia: 0.9706 - val_loss: 0.0029 - val_mae: 0.0396 - val_rmse: 0.0535 - val_smape: 0.1172

Epoch 27/32

144/144 - 6s - 40ms/step - ia: 0.9672 - loss: 0.0058 - mae: 0.0542 - rmse: 0.0750 - smape: 0.1520 - val_ia: 0.9696 - val_loss: 0.0031 - val_mae: 0.0406 - val_rmse: 0.0541 - val_smape: 0.1219

Epoch 28/32

144/144 - 6s - 41ms/step - ia: 0.9678 - loss: 0.0056 - mae: 0.0532 - rmse: 0.0741 - smape: 0.1491 - val_ia: 0.9726 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0513 - val_smape: 0.1148

Epoch 29/32

144/144 - 6s - 40ms/step - ia: 0.9680 - loss: 0.0056 - mae: 0.0529 - rmse: 0.0739 - smape: 0.1471 - val_ia: 0.9713 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0520 - val_smape: 0.1218

Epoch 30/32

144/144 - 6s - 39ms/step - ia: 0.9674 - loss: 0.0057 - mae: 0.0538 - rmse: 0.0747 - smape: 0.1504 - val_ia: 0.9673 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0563 - val_smape: 0.1329

Epoch 31/32

144/144 - 6s - 40ms/step - ia: 0.9680 - loss: 0.0055 - mae: 0.0528 - rmse: 0.0733 - smape: 0.1485 - val_ia: 0.9747 - val_loss: 0.0024 - val_mae: 0.0340 - val_rmse: 0.0484 - val_smape: 0.1086

Epoch 32/32

144/144 - 6s - 40ms/step - ia: 0.9680 - loss: 0.0056 - mae: 0.0529 - rmse: 0.0736 - smape: 0.1481 - val_ia: 0.9750 - val_loss: 0.0023 - val_mae: 0.0339 - val_rmse: 0.0479 - val_smape: 0.1098

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:34 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step

 68%|██████▊   | 34/50 [6:54:17<2:08:50, 483.15s/trial, best loss: 0.0019506437682772187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 43s - 37ms/step - ia: 0.8881 - loss: 0.0673 - mae: 0.1672 - rmse: 0.2166 - smape: 0.3994 - val_ia: 0.8280 - val_loss: 0.0120 - val_mae: 0.0769 - val_rmse: 0.1016 - val_smape: 0.2236

Epoch 2/32

1147/1147 - 17s - 14ms/step - ia: 0.9420 - loss: 0.0164 - mae: 0.0933 - rmse: 0.1249 - smape: 0.2422 - val_ia: 0.8638 - val_loss: 0.0073 - val_mae: 0.0603 - val_rmse: 0.0799 - val_smape: 0.1861

Epoch 3/32

1147/1147 - 18s - 16ms/step - ia: 0.9502 - loss: 0.0121 - mae: 0.0804 - rmse: 0.1072 - smape: 0.2157 - val_ia: 0.8809 - val_loss: 0.0054 - val_mae: 0.0526 - val_rmse: 0.0697 - val_smape: 0.1632

Epoch 4/32

1147/1147 - 19s - 17ms/step - ia: 0.9552 - loss: 0.0099 - mae: 0.0724 - rmse: 0.0970 - smape: 0.1969 - val_ia: 0.8928 - val_loss: 0.0043 - val_mae: 0.0469 - val_rmse: 0.0622 - val_smape: 0.1508

Epoch 5/32

1147/1147 - 20s - 18ms/step - ia: 0.9583 - loss: 0.0086 - mae: 0.0672 - rmse: 0.0900 - smape: 0.1864 - val_ia: 0.9064 - val_loss: 0.0034 - val_mae: 0.0400 - val_rmse: 0.0540 - val_smape: 0.1219

Epoch 6/32

1147/1147 - 18s - 16ms/step - ia: 0.9604 - loss: 0.0079 - mae: 0.0641 - rmse: 0.0858 - smape: 0.1775 - val_ia: 0.9012 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0554 - val_smape: 0.1337

Epoch 7/32

1147/1147 - 21s - 18ms/step - ia: 0.9617 - loss: 0.0074 - mae: 0.0618 - rmse: 0.0829 - smape: 0.1702 - val_ia: 0.9071 - val_loss: 0.0030 - val_mae: 0.0386 - val_rmse: 0.0513 - val_smape: 0.1177

Epoch 8/32

1147/1147 - 21s - 18ms/step - ia: 0.9631 - loss: 0.0069 - mae: 0.0598 - rmse: 0.0803 - smape: 0.1674 - val_ia: 0.9138 - val_loss: 0.0027 - val_mae: 0.0358 - val_rmse: 0.0487 - val_smape: 0.1139

Epoch 9/32

1147/1147 - 19s - 16ms/step - ia: 0.9638 - loss: 0.0067 - mae: 0.0584 - rmse: 0.0788 - smape: 0.1639 - val_ia: 0.9200 - val_loss: 0.0026 - val_mae: 0.0342 - val_rmse: 0.0469 - val_smape: 0.1097

Epoch 10/32

1147/1147 - 18s - 16ms/step - ia: 0.9645 - loss: 0.0065 - mae: 0.0574 - rmse: 0.0777 - smape: 0.1616 - val_ia: 0.9143 - val_loss: 0.0026 - val_mae: 0.0357 - val_rmse: 0.0480 - val_smape: 0.1127

Epoch 11/32

1147/1147 - 18s - 16ms/step - ia: 0.9651 - loss: 0.0063 - mae: 0.0565 - rmse: 0.0763 - smape: 0.1592 - val_ia: 0.9085 - val_loss: 0.0028 - val_mae: 0.0371 - val_rmse: 0.0493 - val_smape: 0.1142

Epoch 12/32

1147/1147 - 20s - 17ms/step - ia: 0.9657 - loss: 0.0061 - mae: 0.0553 - rmse: 0.0747 - smape: 0.1565 - val_ia: 0.9133 - val_loss: 0.0029 - val_mae: 0.0382 - val_rmse: 0.0500 - val_smape: 0.1203

Epoch 13/32

1147/1147 - 20s - 18ms/step - ia: 0.9662 - loss: 0.0059 - mae: 0.0547 - rmse: 0.0738 - smape: 0.1554 - val_ia: 0.9133 - val_loss: 0.0027 - val_mae: 0.0372 - val_rmse: 0.0490 - val_smape: 0.1137

Epoch 14/32

1147/1147 - 19s - 17ms/step - ia: 0.9664 - loss: 0.0059 - mae: 0.0543 - rmse: 0.0737 - smape: 0.1540 - val_ia: 0.9038 - val_loss: 0.0031 - val_mae: 0.0414 - val_rmse: 0.0530 - val_smape: 0.1133

Epoch 15/32

1147/1147 - 18s - 16ms/step - ia: 0.9666 - loss: 0.0058 - mae: 0.0540 - rmse: 0.0732 - smape: 0.1515 - val_ia: 0.9200 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0465 - val_smape: 0.1098

Epoch 16/32

1147/1147 - 18s - 16ms/step - ia: 0.9670 - loss: 0.0057 - mae: 0.0534 - rmse: 0.0723 - smape: 0.1510 - val_ia: 0.9072 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0498 - val_smape: 0.1244

Epoch 17/32

1147/1147 - 19s - 16ms/step - ia: 0.9669 - loss: 0.0057 - mae: 0.0535 - rmse: 0.0723 - smape: 0.1513 - val_ia: 0.9000 - val_loss: 0.0034 - val_mae: 0.0434 - val_rmse: 0.0551 - val_smape: 0.1484

Epoch 18/32

1147/1147 - 19s - 16ms/step - ia: 0.9668 - loss: 0.0057 - mae: 0.0536 - rmse: 0.0725 - smape: 0.1516 - val_ia: 0.9157 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0469 - val_smape: 0.1139

Epoch 19/32

1147/1147 - 18s - 15ms/step - ia: 0.9673 - loss: 0.0056 - mae: 0.0529 - rmse: 0.0717 - smape: 0.1508 - val_ia: 0.9161 - val_loss: 0.0025 - val_mae: 0.0349 - val_rmse: 0.0468 - val_smape: 0.1095

Epoch 20/32

1147/1147 - 19s - 17ms/step - ia: 0.9672 - loss: 0.0056 - mae: 0.0530 - rmse: 0.0718 - smape: 0.1502 - val_ia: 0.8999 - val_loss: 0.0033 - val_mae: 0.0423 - val_rmse: 0.0545 - val_smape: 0.1191

Epoch 21/32

1147/1147 - 18s - 15ms/step - ia: 0.9674 - loss: 0.0056 - mae: 0.0528 - rmse: 0.0717 - smape: 0.1490 - val_ia: 0.9208 - val_loss: 0.0024 - val_mae: 0.0334 - val_rmse: 0.0454 - val_smape: 0.1090

Epoch 22/32

1147/1147 - 19s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0710 - smape: 0.1498 - val_ia: 0.9058 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0496 - val_smape: 0.1126

Epoch 23/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0523 - rmse: 0.0711 - smape: 0.1490 - val_ia: 0.9188 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0471 - val_smape: 0.1141

Epoch 24/32

1147/1147 - 18s - 16ms/step - ia: 0.9675 - loss: 0.0055 - mae: 0.0525 - rmse: 0.0713 - smape: 0.1490 - val_ia: 0.9045 - val_loss: 0.0029 - val_mae: 0.0383 - val_rmse: 0.0502 - val_smape: 0.1165

Epoch 25/32

1147/1147 - 19s - 16ms/step - ia: 0.9677 - loss: 0.0054 - mae: 0.0520 - rmse: 0.0708 - smape: 0.1483 - val_ia: 0.9212 - val_loss: 0.0024 - val_mae: 0.0335 - val_rmse: 0.0457 - val_smape: 0.1080

Epoch 26/32

1147/1147 - 21s - 18ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0522 - rmse: 0.0710 - smape: 0.1484 - val_ia: 0.9166 - val_loss: 0.0025 - val_mae: 0.0345 - val_rmse: 0.0465 - val_smape: 0.1144

Epoch 27/32

1147/1147 - 16s - 14ms/step - ia: 0.9680 - loss: 0.0053 - mae: 0.0516 - rmse: 0.0701 - smape: 0.1476 - val_ia: 0.9201 - val_loss: 0.0024 - val_mae: 0.0333 - val_rmse: 0.0455 - val_smape: 0.1066

Epoch 28/32

1147/1147 - 14s - 12ms/step - ia: 0.9681 - loss: 0.0054 - mae: 0.0516 - rmse: 0.0701 - smape: 0.1465 - val_ia: 0.9183 - val_loss: 0.0024 - val_mae: 0.0336 - val_rmse: 0.0459 - val_smape: 0.1065

Epoch 29/32

1147/1147 - 15s - 13ms/step - ia: 0.9682 - loss: 0.0054 - mae: 0.0516 - rmse: 0.0701 - smape: 0.1476 - val_ia: 0.9207 - val_loss: 0.0025 - val_mae: 0.0339 - val_rmse: 0.0463 - val_smape: 0.1133

Epoch 30/32

1147/1147 - 18s - 16ms/step - ia: 0.9679 - loss: 0.0054 - mae: 0.0519 - rmse: 0.0703 - smape: 0.1482 - val_ia: 0.9168 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0470 - val_smape: 0.1110

Epoch 31/32

1147/1147 - 18s - 16ms/step - ia: 0.9683 - loss: 0.0053 - mae: 0.0512 - rmse: 0.0696 - smape: 0.1468 - val_ia: 0.9201 - val_loss: 0.0024 - val_mae: 0.0335 - val_rmse: 0.0457 - val_smape: 0.1085

Epoch 32/32

1147/1147 - 17s - 14ms/step - ia: 0.9684 - loss: 0.0053 - mae: 0.0512 - rmse: 0.0695 - smape: 0.1466 - val_ia: 0.9226 - val_loss: 0.0024 - val_mae: 0.0327 - val_rmse: 0.0450 - val_smape: 0.1078

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:15 838ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 70%|███████   | 35/50 [7:04:32<2:10:41, 522.76s/trial, best loss: 0.0016936418135275735]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 22s - 19ms/step - ia: 0.6276 - loss: 0.3647 - mae: 0.4596 - rmse: 0.5608 - smape: 0.9116 - val_ia: 0.5578 - val_loss: 0.1232 - val_mae: 0.2714 - val_rmse: 0.3211 - val_smape: 0.6159

Epoch 2/32

1147/1147 - 17s - 15ms/step - ia: 0.8476 - loss: 0.0967 - mae: 0.2390 - rmse: 0.3072 - smape: 0.5423 - val_ia: 0.5842 - val_loss: 0.1134 - val_mae: 0.2628 - val_rmse: 0.3050 - val_smape: 0.6055

Epoch 3/32

1147/1147 - 22s - 19ms/step - ia: 0.8758 - loss: 0.0673 - mae: 0.1970 - rmse: 0.2557 - smape: 0.4667 - val_ia: 0.6243 - val_loss: 0.0855 - val_mae: 0.2311 - val_rmse: 0.2666 - val_smape: 0.5618

Epoch 4/32

1147/1147 - 18s - 16ms/step - ia: 0.8977 - loss: 0.0467 - mae: 0.1630 - rmse: 0.2127 - smape: 0.4007 - val_ia: 0.6788 - val_loss: 0.0498 - val_mae: 0.1781 - val_rmse: 0.2090 - val_smape: 0.4796

Epoch 5/32

1147/1147 - 18s - 16ms/step - ia: 0.9146 - loss: 0.0335 - mae: 0.1368 - rmse: 0.1797 - smape: 0.3467 - val_ia: 0.7390 - val_loss: 0.0280 - val_mae: 0.1302 - val_rmse: 0.1592 - val_smape: 0.3864

Epoch 6/32

1147/1147 - 19s - 17ms/step - ia: 0.9243 - loss: 0.0269 - mae: 0.1217 - rmse: 0.1611 - smape: 0.3104 - val_ia: 0.7835 - val_loss: 0.0183 - val_mae: 0.1009 - val_rmse: 0.1283 - val_smape: 0.3137

Epoch 7/32

1147/1147 - 18s - 16ms/step - ia: 0.9296 - loss: 0.0232 - mae: 0.1129 - rmse: 0.1496 - smape: 0.2897 - val_ia: 0.8007 - val_loss: 0.0153 - val_mae: 0.0909 - val_rmse: 0.1167 - val_smape: 0.2847

Epoch 8/32

1147/1147 - 19s - 16ms/step - ia: 0.9330 - loss: 0.0213 - mae: 0.1078 - rmse: 0.1430 - smape: 0.2787 - val_ia: 0.8072 - val_loss: 0.0142 - val_mae: 0.0878 - val_rmse: 0.1122 - val_smape: 0.2735

Epoch 9/32

1147/1147 - 17s - 15ms/step - ia: 0.9353 - loss: 0.0200 - mae: 0.1041 - rmse: 0.1384 - smape: 0.2686 - val_ia: 0.8162 - val_loss: 0.0129 - val_mae: 0.0833 - val_rmse: 0.1069 - val_smape: 0.2596

Epoch 10/32

1147/1147 - 18s - 16ms/step - ia: 0.9373 - loss: 0.0189 - mae: 0.1008 - rmse: 0.1347 - smape: 0.2618 - val_ia: 0.8204 - val_loss: 0.0123 - val_mae: 0.0816 - val_rmse: 0.1044 - val_smape: 0.2564

Epoch 11/32

1147/1147 - 19s - 16ms/step - ia: 0.9390 - loss: 0.0181 - mae: 0.0982 - rmse: 0.1314 - smape: 0.2538 - val_ia: 0.8273 - val_loss: 0.0114 - val_mae: 0.0776 - val_rmse: 0.1003 - val_smape: 0.2401

Epoch 12/32

1147/1147 - 19s - 16ms/step - ia: 0.9404 - loss: 0.0172 - mae: 0.0959 - rmse: 0.1282 - smape: 0.2503 - val_ia: 0.8320 - val_loss: 0.0108 - val_mae: 0.0751 - val_rmse: 0.0973 - val_smape: 0.2287

Epoch 13/32

1147/1147 - 17s - 15ms/step - ia: 0.9419 - loss: 0.0163 - mae: 0.0936 - rmse: 0.1249 - smape: 0.2459 - val_ia: 0.8339 - val_loss: 0.0104 - val_mae: 0.0741 - val_rmse: 0.0958 - val_smape: 0.2274

Epoch 14/32

1147/1147 - 19s - 16ms/step - ia: 0.9428 - loss: 0.0159 - mae: 0.0921 - rmse: 0.1234 - smape: 0.2428 - val_ia: 0.8417 - val_loss: 0.0096 - val_mae: 0.0707 - val_rmse: 0.0919 - val_smape: 0.2169

Epoch 15/32

1147/1147 - 18s - 16ms/step - ia: 0.9441 - loss: 0.0152 - mae: 0.0900 - rmse: 0.1206 - smape: 0.2366 - val_ia: 0.8424 - val_loss: 0.0094 - val_mae: 0.0706 - val_rmse: 0.0913 - val_smape: 0.2198

Epoch 16/32

1147/1147 - 18s - 16ms/step - ia: 0.9446 - loss: 0.0149 - mae: 0.0891 - rmse: 0.1194 - smape: 0.2343 - val_ia: 0.8440 - val_loss: 0.0091 - val_mae: 0.0686 - val_rmse: 0.0893 - val_smape: 0.2065

Epoch 17/32

1147/1147 - 17s - 15ms/step - ia: 0.9455 - loss: 0.0145 - mae: 0.0877 - rmse: 0.1176 - smape: 0.2299 - val_ia: 0.8499 - val_loss: 0.0085 - val_mae: 0.0667 - val_rmse: 0.0869 - val_smape: 0.2058

Epoch 18/32

1147/1147 - 17s - 15ms/step - ia: 0.9465 - loss: 0.0140 - mae: 0.0862 - rmse: 0.1155 - smape: 0.2274 - val_ia: 0.8517 - val_loss: 0.0083 - val_mae: 0.0654 - val_rmse: 0.0854 - val_smape: 0.2001

Epoch 19/32

1147/1147 - 18s - 15ms/step - ia: 0.9471 - loss: 0.0135 - mae: 0.0851 - rmse: 0.1136 - smape: 0.2271 - val_ia: 0.8521 - val_loss: 0.0081 - val_mae: 0.0646 - val_rmse: 0.0843 - val_smape: 0.1973

Epoch 20/32

1147/1147 - 18s - 16ms/step - ia: 0.9478 - loss: 0.0133 - mae: 0.0842 - rmse: 0.1128 - smape: 0.2226 - val_ia: 0.8508 - val_loss: 0.0081 - val_mae: 0.0653 - val_rmse: 0.0846 - val_smape: 0.2016

Epoch 21/32

1147/1147 - 16s - 14ms/step - ia: 0.9483 - loss: 0.0130 - mae: 0.0832 - rmse: 0.1112 - smape: 0.2216 - val_ia: 0.8579 - val_loss: 0.0075 - val_mae: 0.0620 - val_rmse: 0.0813 - val_smape: 0.1876

Epoch 22/32

1147/1147 - 18s - 16ms/step - ia: 0.9490 - loss: 0.0126 - mae: 0.0820 - rmse: 0.1096 - smape: 0.2189 - val_ia: 0.8634 - val_loss: 0.0070 - val_mae: 0.0595 - val_rmse: 0.0785 - val_smape: 0.1819

Epoch 23/32

1147/1147 - 18s - 16ms/step - ia: 0.9495 - loss: 0.0125 - mae: 0.0812 - rmse: 0.1089 - smape: 0.2174 - val_ia: 0.8656 - val_loss: 0.0068 - val_mae: 0.0589 - val_rmse: 0.0776 - val_smape: 0.1838

Epoch 24/32

1147/1147 - 17s - 15ms/step - ia: 0.9502 - loss: 0.0121 - mae: 0.0802 - rmse: 0.1075 - smape: 0.2153 - val_ia: 0.8625 - val_loss: 0.0069 - val_mae: 0.0597 - val_rmse: 0.0782 - val_smape: 0.1839

Epoch 25/32

1147/1147 - 16s - 14ms/step - ia: 0.9505 - loss: 0.0119 - mae: 0.0796 - rmse: 0.1064 - smape: 0.2163 - val_ia: 0.8597 - val_loss: 0.0070 - val_mae: 0.0605 - val_rmse: 0.0787 - val_smape: 0.1851

Epoch 26/32

1147/1147 - 18s - 16ms/step - ia: 0.9512 - loss: 0.0116 - mae: 0.0787 - rmse: 0.1052 - smape: 0.2123 - val_ia: 0.8671 - val_loss: 0.0064 - val_mae: 0.0574 - val_rmse: 0.0754 - val_smape: 0.1762

Epoch 27/32

1147/1147 - 15s - 13ms/step - ia: 0.9516 - loss: 0.0114 - mae: 0.0780 - rmse: 0.1040 - smape: 0.2086 - val_ia: 0.8666 - val_loss: 0.0064 - val_mae: 0.0576 - val_rmse: 0.0754 - val_smape: 0.1784

Epoch 28/32

1147/1147 - 13s - 11ms/step - ia: 0.9521 - loss: 0.0113 - mae: 0.0773 - rmse: 0.1035 - smape: 0.2074 - val_ia: 0.8727 - val_loss: 0.0060 - val_mae: 0.0554 - val_rmse: 0.0729 - val_smape: 0.1720

Epoch 29/32

1147/1147 - 11s - 10ms/step - ia: 0.9526 - loss: 0.0110 - mae: 0.0765 - rmse: 0.1024 - smape: 0.2072 - val_ia: 0.8713 - val_loss: 0.0060 - val_mae: 0.0556 - val_rmse: 0.0730 - val_smape: 0.1729

Epoch 30/32

1147/1147 - 12s - 11ms/step - ia: 0.9530 - loss: 0.0108 - mae: 0.0758 - rmse: 0.1013 - smape: 0.2060 - val_ia: 0.8723 - val_loss: 0.0058 - val_mae: 0.0548 - val_rmse: 0.0719 - val_smape: 0.1677

Epoch 31/32

1147/1147 - 16s - 14ms/step - ia: 0.9533 - loss: 0.0107 - mae: 0.0752 - rmse: 0.1006 - smape: 0.2038 - val_ia: 0.8762 - val_loss: 0.0056 - val_mae: 0.0532 - val_rmse: 0.0702 - val_smape: 0.1649

Epoch 32/32

1147/1147 - 17s - 15ms/step - ia: 0.9537 - loss: 0.0106 - mae: 0.0746 - rmse: 0.1001 - smape: 0.2034 - val_ia: 0.8788 - val_loss: 0.0054 - val_mae: 0.0523 - val_rmse: 0.0692 - val_smape: 0.1613

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:12 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 72%|███████▏  | 36/50 [7:13:53<2:04:40, 534.36s/trial, best loss: 0.0016936418135275735]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 39s - 34ms/step - ia: 0.9078 - loss: 0.0451 - mae: 0.1438 - rmse: 0.1874 - smape: 0.3522 - val_ia: 0.8258 - val_loss: 0.0115 - val_mae: 0.0773 - val_rmse: 0.1000 - val_smape: 0.2379

Epoch 2/32

1147/1147 - 17s - 15ms/step - ia: 0.9442 - loss: 0.0151 - mae: 0.0900 - rmse: 0.1197 - smape: 0.2387 - val_ia: 0.8600 - val_loss: 0.0071 - val_mae: 0.0609 - val_rmse: 0.0791 - val_smape: 0.1897

Epoch 3/32

1147/1147 - 18s - 16ms/step - ia: 0.9515 - loss: 0.0114 - mae: 0.0781 - rmse: 0.1037 - smape: 0.2125 - val_ia: 0.8802 - val_loss: 0.0051 - val_mae: 0.0509 - val_rmse: 0.0666 - val_smape: 0.1616

Epoch 4/32

1147/1147 - 18s - 16ms/step - ia: 0.9560 - loss: 0.0095 - mae: 0.0709 - rmse: 0.0946 - smape: 0.1956 - val_ia: 0.8883 - val_loss: 0.0043 - val_mae: 0.0465 - val_rmse: 0.0608 - val_smape: 0.1428

Epoch 5/32

1147/1147 - 15s - 13ms/step - ia: 0.9585 - loss: 0.0085 - mae: 0.0669 - rmse: 0.0894 - smape: 0.1842 - val_ia: 0.8968 - val_loss: 0.0036 - val_mae: 0.0426 - val_rmse: 0.0562 - val_smape: 0.1333

Epoch 6/32

1147/1147 - 21s - 18ms/step - ia: 0.9610 - loss: 0.0077 - mae: 0.0630 - rmse: 0.0845 - smape: 0.1743 - val_ia: 0.9084 - val_loss: 0.0030 - val_mae: 0.0382 - val_rmse: 0.0513 - val_smape: 0.1214

Epoch 7/32

1147/1147 - 16s - 14ms/step - ia: 0.9625 - loss: 0.0071 - mae: 0.0605 - rmse: 0.0813 - smape: 0.1676 - val_ia: 0.9029 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0532 - val_smape: 0.1329

Epoch 8/32

1147/1147 - 18s - 16ms/step - ia: 0.9637 - loss: 0.0067 - mae: 0.0586 - rmse: 0.0789 - smape: 0.1631 - val_ia: 0.9131 - val_loss: 0.0028 - val_mae: 0.0363 - val_rmse: 0.0486 - val_smape: 0.1173

Epoch 9/32

1147/1147 - 18s - 16ms/step - ia: 0.9643 - loss: 0.0065 - mae: 0.0575 - rmse: 0.0778 - smape: 0.1608 - val_ia: 0.9163 - val_loss: 0.0026 - val_mae: 0.0356 - val_rmse: 0.0477 - val_smape: 0.1150

Epoch 10/32

1147/1147 - 17s - 15ms/step - ia: 0.9652 - loss: 0.0062 - mae: 0.0564 - rmse: 0.0761 - smape: 0.1582 - val_ia: 0.9185 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0464 - val_smape: 0.1110

Epoch 11/32

1147/1147 - 16s - 14ms/step - ia: 0.9655 - loss: 0.0061 - mae: 0.0557 - rmse: 0.0753 - smape: 0.1566 - val_ia: 0.9176 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0471 - val_smape: 0.1137

Epoch 12/32

1147/1147 - 16s - 14ms/step - ia: 0.9660 - loss: 0.0060 - mae: 0.0550 - rmse: 0.0746 - smape: 0.1553 - val_ia: 0.9095 - val_loss: 0.0028 - val_mae: 0.0376 - val_rmse: 0.0497 - val_smape: 0.1188

Epoch 13/32

1147/1147 - 17s - 15ms/step - ia: 0.9663 - loss: 0.0059 - mae: 0.0543 - rmse: 0.0734 - smape: 0.1532 - val_ia: 0.9138 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0479 - val_smape: 0.1166

Epoch 14/32

1147/1147 - 18s - 16ms/step - ia: 0.9666 - loss: 0.0058 - mae: 0.0540 - rmse: 0.0730 - smape: 0.1535 - val_ia: 0.9038 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0527 - val_smape: 0.1351

Epoch 15/32

1147/1147 - 19s - 16ms/step - ia: 0.9666 - loss: 0.0058 - mae: 0.0538 - rmse: 0.0730 - smape: 0.1522 - val_ia: 0.9020 - val_loss: 0.0030 - val_mae: 0.0392 - val_rmse: 0.0511 - val_smape: 0.1209

Epoch 16/32

1147/1147 - 18s - 15ms/step - ia: 0.9669 - loss: 0.0057 - mae: 0.0534 - rmse: 0.0724 - smape: 0.1511 - val_ia: 0.8948 - val_loss: 0.0032 - val_mae: 0.0420 - val_rmse: 0.0538 - val_smape: 0.1282

Epoch 17/32

1147/1147 - 18s - 16ms/step - ia: 0.9673 - loss: 0.0056 - mae: 0.0530 - rmse: 0.0718 - smape: 0.1507 - val_ia: 0.9125 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0484 - val_smape: 0.1121

Epoch 18/32

1147/1147 - 20s - 18ms/step - ia: 0.9671 - loss: 0.0057 - mae: 0.0532 - rmse: 0.0721 - smape: 0.1505 - val_ia: 0.9165 - val_loss: 0.0025 - val_mae: 0.0350 - val_rmse: 0.0469 - val_smape: 0.1207

Epoch 19/32

1147/1147 - 18s - 15ms/step - ia: 0.9670 - loss: 0.0056 - mae: 0.0532 - rmse: 0.0721 - smape: 0.1501 - val_ia: 0.8950 - val_loss: 0.0033 - val_mae: 0.0432 - val_rmse: 0.0550 - val_smape: 0.1214

Epoch 20/32

1147/1147 - 18s - 16ms/step - ia: 0.9670 - loss: 0.0057 - mae: 0.0532 - rmse: 0.0724 - smape: 0.1499 - val_ia: 0.9222 - val_loss: 0.0023 - val_mae: 0.0325 - val_rmse: 0.0446 - val_smape: 0.1063

Epoch 21/32

1147/1147 - 18s - 16ms/step - ia: 0.9674 - loss: 0.0055 - mae: 0.0527 - rmse: 0.0714 - smape: 0.1503 - val_ia: 0.9212 - val_loss: 0.0024 - val_mae: 0.0332 - val_rmse: 0.0455 - val_smape: 0.1101

Epoch 22/32

1147/1147 - 18s - 16ms/step - ia: 0.9675 - loss: 0.0056 - mae: 0.0525 - rmse: 0.0714 - smape: 0.1486 - val_ia: 0.9122 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0487 - val_smape: 0.1140

Epoch 23/32

1147/1147 - 21s - 19ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0521 - rmse: 0.0708 - smape: 0.1482 - val_ia: 0.9106 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0494 - val_smape: 0.1276

Epoch 24/32

1147/1147 - 15s - 13ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0523 - rmse: 0.0709 - smape: 0.1493 - val_ia: 0.9182 - val_loss: 0.0025 - val_mae: 0.0343 - val_rmse: 0.0464 - val_smape: 0.1145

Epoch 25/32

1147/1147 - 15s - 13ms/step - ia: 0.9679 - loss: 0.0054 - mae: 0.0518 - rmse: 0.0703 - smape: 0.1484 - val_ia: 0.9127 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0489 - val_smape: 0.1180

Epoch 26/32

1147/1147 - 24s - 21ms/step - ia: 0.9679 - loss: 0.0054 - mae: 0.0518 - rmse: 0.0705 - smape: 0.1472 - val_ia: 0.9146 - val_loss: 0.0027 - val_mae: 0.0364 - val_rmse: 0.0482 - val_smape: 0.1207

Epoch 27/32

1147/1147 - 15s - 13ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0522 - rmse: 0.0709 - smape: 0.1474 - val_ia: 0.9189 - val_loss: 0.0025 - val_mae: 0.0349 - val_rmse: 0.0469 - val_smape: 0.1125

Epoch 28/32

1147/1147 - 15s - 13ms/step - ia: 0.9681 - loss: 0.0053 - mae: 0.0515 - rmse: 0.0700 - smape: 0.1470 - val_ia: 0.9036 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0504 - val_smape: 0.1217

Epoch 29/32

1147/1147 - 18s - 16ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0522 - rmse: 0.0714 - smape: 0.1476 - val_ia: 0.9087 - val_loss: 0.0031 - val_mae: 0.0403 - val_rmse: 0.0519 - val_smape: 0.1242

Epoch 30/32

1147/1147 - 17s - 15ms/step - ia: 0.9678 - loss: 0.0055 - mae: 0.0520 - rmse: 0.0708 - smape: 0.1469 - val_ia: 0.9016 - val_loss: 0.0032 - val_mae: 0.0417 - val_rmse: 0.0533 - val_smape: 0.1198

Epoch 31/32

1147/1147 - 16s - 14ms/step - ia: 0.9679 - loss: 0.0054 - mae: 0.0519 - rmse: 0.0705 - smape: 0.1470 - val_ia: 0.9141 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0478 - val_smape: 0.1108

Epoch 32/32

1147/1147 - 17s - 15ms/step - ia: 0.9683 - loss: 0.0053 - mae: 0.0512 - rmse: 0.0696 - smape: 0.1459 - val_ia: 0.9078 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0499 - val_smape: 0.1210

Restoring model weights from the end of the best epoch: 20.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:47 3s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 74%|███████▍  | 37/50 [7:23:45<1:59:29, 551.50s/trial, best loss: 0.0016936418135275735]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 44s - 38ms/step - ia: 0.8931 - loss: 0.0618 - mae: 0.1597 - rmse: 0.2078 - smape: 0.3816 - val_ia: 0.8100 - val_loss: 0.0139 - val_mae: 0.0852 - val_rmse: 0.1095 - val_smape: 0.2514

Epoch 2/32

1147/1147 - 13s - 12ms/step - ia: 0.9420 - loss: 0.0164 - mae: 0.0932 - rmse: 0.1250 - smape: 0.2417 - val_ia: 0.8473 - val_loss: 0.0087 - val_mae: 0.0669 - val_rmse: 0.0871 - val_smape: 0.2012

Epoch 3/32

1147/1147 - 14s - 12ms/step - ia: 0.9494 - loss: 0.0125 - mae: 0.0816 - rmse: 0.1089 - smape: 0.2161 - val_ia: 0.8639 - val_loss: 0.0067 - val_mae: 0.0594 - val_rmse: 0.0769 - val_smape: 0.1814

Epoch 4/32

1147/1147 - 18s - 15ms/step - ia: 0.9540 - loss: 0.0104 - mae: 0.0741 - rmse: 0.0993 - smape: 0.2002 - val_ia: 0.8640 - val_loss: 0.0058 - val_mae: 0.0554 - val_rmse: 0.0712 - val_smape: 0.1548

Epoch 5/32

1147/1147 - 16s - 14ms/step - ia: 0.9574 - loss: 0.0090 - mae: 0.0686 - rmse: 0.0919 - smape: 0.1874 - val_ia: 0.8818 - val_loss: 0.0046 - val_mae: 0.0490 - val_rmse: 0.0636 - val_smape: 0.1356

Epoch 6/32

1147/1147 - 15s - 13ms/step - ia: 0.9595 - loss: 0.0081 - mae: 0.0653 - rmse: 0.0876 - smape: 0.1809 - val_ia: 0.8988 - val_loss: 0.0035 - val_mae: 0.0417 - val_rmse: 0.0554 - val_smape: 0.1227

Epoch 7/32

1147/1147 - 14s - 12ms/step - ia: 0.9616 - loss: 0.0075 - mae: 0.0619 - rmse: 0.0833 - smape: 0.1729 - val_ia: 0.8994 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0539 - val_smape: 0.1243

Epoch 8/32

1147/1147 - 13s - 11ms/step - ia: 0.9630 - loss: 0.0070 - mae: 0.0598 - rmse: 0.0806 - smape: 0.1682 - val_ia: 0.9054 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0532 - val_smape: 0.1244

Epoch 9/32

1147/1147 - 15s - 13ms/step - ia: 0.9643 - loss: 0.0066 - mae: 0.0577 - rmse: 0.0777 - smape: 0.1631 - val_ia: 0.9067 - val_loss: 0.0030 - val_mae: 0.0384 - val_rmse: 0.0509 - val_smape: 0.1186

Epoch 10/32

1147/1147 - 18s - 16ms/step - ia: 0.9645 - loss: 0.0065 - mae: 0.0573 - rmse: 0.0774 - smape: 0.1598 - val_ia: 0.9055 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0519 - val_smape: 0.1171

Epoch 11/32

1147/1147 - 15s - 13ms/step - ia: 0.9654 - loss: 0.0061 - mae: 0.0559 - rmse: 0.0753 - smape: 0.1582 - val_ia: 0.9118 - val_loss: 0.0029 - val_mae: 0.0380 - val_rmse: 0.0499 - val_smape: 0.1191

Epoch 12/32

1147/1147 - 13s - 12ms/step - ia: 0.9657 - loss: 0.0061 - mae: 0.0554 - rmse: 0.0748 - smape: 0.1567 - val_ia: 0.9107 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0496 - val_smape: 0.1212

Epoch 13/32

1147/1147 - 12s - 11ms/step - ia: 0.9664 - loss: 0.0059 - mae: 0.0545 - rmse: 0.0738 - smape: 0.1539 - val_ia: 0.9161 - val_loss: 0.0026 - val_mae: 0.0358 - val_rmse: 0.0478 - val_smape: 0.1133

Epoch 14/32

1147/1147 - 14s - 12ms/step - ia: 0.9665 - loss: 0.0058 - mae: 0.0541 - rmse: 0.0732 - smape: 0.1536 - val_ia: 0.9176 - val_loss: 0.0026 - val_mae: 0.0352 - val_rmse: 0.0474 - val_smape: 0.1110

Epoch 15/32

1147/1147 - 15s - 13ms/step - ia: 0.9667 - loss: 0.0057 - mae: 0.0537 - rmse: 0.0726 - smape: 0.1527 - val_ia: 0.9212 - val_loss: 0.0024 - val_mae: 0.0336 - val_rmse: 0.0457 - val_smape: 0.1076

Epoch 16/32

1147/1147 - 17s - 15ms/step - ia: 0.9667 - loss: 0.0058 - mae: 0.0539 - rmse: 0.0729 - smape: 0.1514 - val_ia: 0.9204 - val_loss: 0.0024 - val_mae: 0.0338 - val_rmse: 0.0459 - val_smape: 0.1095

Epoch 17/32

1147/1147 - 20s - 17ms/step - ia: 0.9670 - loss: 0.0056 - mae: 0.0533 - rmse: 0.0719 - smape: 0.1507 - val_ia: 0.9139 - val_loss: 0.0025 - val_mae: 0.0351 - val_rmse: 0.0470 - val_smape: 0.1128

Epoch 18/32

1147/1147 - 17s - 15ms/step - ia: 0.9672 - loss: 0.0056 - mae: 0.0529 - rmse: 0.0717 - smape: 0.1514 - val_ia: 0.9090 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0508 - val_smape: 0.1234

Epoch 19/32

1147/1147 - 18s - 16ms/step - ia: 0.9672 - loss: 0.0057 - mae: 0.0531 - rmse: 0.0722 - smape: 0.1505 - val_ia: 0.9061 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0505 - val_smape: 0.1262

Epoch 20/32

1147/1147 - 17s - 15ms/step - ia: 0.9674 - loss: 0.0056 - mae: 0.0527 - rmse: 0.0717 - smape: 0.1492 - val_ia: 0.9078 - val_loss: 0.0030 - val_mae: 0.0389 - val_rmse: 0.0506 - val_smape: 0.1294

Epoch 21/32

1147/1147 - 18s - 15ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0712 - smape: 0.1500 - val_ia: 0.9110 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0484 - val_smape: 0.1158

Epoch 22/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0711 - smape: 0.1487 - val_ia: 0.9172 - val_loss: 0.0026 - val_mae: 0.0354 - val_rmse: 0.0474 - val_smape: 0.1137

Epoch 23/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0710 - smape: 0.1484 - val_ia: 0.9061 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0505 - val_smape: 0.1225

Epoch 24/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0523 - rmse: 0.0711 - smape: 0.1486 - val_ia: 0.9205 - val_loss: 0.0024 - val_mae: 0.0335 - val_rmse: 0.0456 - val_smape: 0.1083

Epoch 25/32

1147/1147 - 18s - 16ms/step - ia: 0.9679 - loss: 0.0054 - mae: 0.0519 - rmse: 0.0706 - smape: 0.1478 - val_ia: 0.9137 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0487 - val_smape: 0.1218

Epoch 26/32

1147/1147 - 18s - 16ms/step - ia: 0.9677 - loss: 0.0054 - mae: 0.0521 - rmse: 0.0705 - smape: 0.1492 - val_ia: 0.9079 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0525 - val_smape: 0.1199

Epoch 27/32

1147/1147 - 17s - 15ms/step - ia: 0.9678 - loss: 0.0054 - mae: 0.0519 - rmse: 0.0705 - smape: 0.1473 - val_ia: 0.9136 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0489 - val_smape: 0.1160

Epoch 28/32

1147/1147 - 18s - 15ms/step - ia: 0.9680 - loss: 0.0054 - mae: 0.0518 - rmse: 0.0704 - smape: 0.1478 - val_ia: 0.9150 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0478 - val_smape: 0.1150

Epoch 29/32

1147/1147 - 18s - 16ms/step - ia: 0.9681 - loss: 0.0054 - mae: 0.0516 - rmse: 0.0702 - smape: 0.1466 - val_ia: 0.9159 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0477 - val_smape: 0.1144

Epoch 30/32

1147/1147 - 18s - 15ms/step - ia: 0.9681 - loss: 0.0054 - mae: 0.0516 - rmse: 0.0702 - smape: 0.1470 - val_ia: 0.9103 - val_loss: 0.0028 - val_mae: 0.0386 - val_rmse: 0.0501 - val_smape: 0.1117

Epoch 31/32

1147/1147 - 18s - 15ms/step - ia: 0.9682 - loss: 0.0054 - mae: 0.0515 - rmse: 0.0700 - smape: 0.1471 - val_ia: 0.9093 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0486 - val_smape: 0.1180

Epoch 32/32

1147/1147 - 18s - 16ms/step - ia: 0.9683 - loss: 0.0053 - mae: 0.0513 - rmse: 0.0697 - smape: 0.1454 - val_ia: 0.9194 - val_loss: 0.0025 - val_mae: 0.0341 - val_rmse: 0.0462 - val_smape: 0.1107

Restoring model weights from the end of the best epoch: 24.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:51 2s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step

 76%|███████▌  | 38/50 [7:33:03<1:50:41, 553.44s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 40s - 35ms/step - ia: 0.8672 - loss: 0.0807 - mae: 0.2014 - rmse: 0.2610 - smape: 0.4609 - val_ia: 0.7500 - val_loss: 0.0245 - val_mae: 0.1183 - val_rmse: 0.1497 - val_smape: 0.3378

Epoch 2/32

1147/1147 - 14s - 12ms/step - ia: 0.9279 - loss: 0.0246 - mae: 0.1160 - rmse: 0.1538 - smape: 0.2934 - val_ia: 0.8182 - val_loss: 0.0130 - val_mae: 0.0814 - val_rmse: 0.1063 - val_smape: 0.2471

Epoch 3/32

1147/1147 - 16s - 14ms/step - ia: 0.9380 - loss: 0.0185 - mae: 0.0997 - rmse: 0.1333 - smape: 0.2575 - val_ia: 0.8447 - val_loss: 0.0098 - val_mae: 0.0696 - val_rmse: 0.0925 - val_smape: 0.2125

Epoch 4/32

1147/1147 - 18s - 15ms/step - ia: 0.9435 - loss: 0.0155 - mae: 0.0910 - rmse: 0.1218 - smape: 0.2381 - val_ia: 0.8528 - val_loss: 0.0085 - val_mae: 0.0657 - val_rmse: 0.0867 - val_smape: 0.2037

Epoch 5/32

1147/1147 - 15s - 13ms/step - ia: 0.9473 - loss: 0.0135 - mae: 0.0849 - rmse: 0.1133 - smape: 0.2242 - val_ia: 0.8641 - val_loss: 0.0071 - val_mae: 0.0594 - val_rmse: 0.0788 - val_smape: 0.1791

Epoch 6/32

1147/1147 - 18s - 15ms/step - ia: 0.9502 - loss: 0.0121 - mae: 0.0802 - rmse: 0.1072 - smape: 0.2159 - val_ia: 0.8769 - val_loss: 0.0060 - val_mae: 0.0538 - val_rmse: 0.0724 - val_smape: 0.1652

Epoch 7/32

1147/1147 - 17s - 15ms/step - ia: 0.9525 - loss: 0.0110 - mae: 0.0765 - rmse: 0.1023 - smape: 0.2071 - val_ia: 0.8842 - val_loss: 0.0052 - val_mae: 0.0504 - val_rmse: 0.0677 - val_smape: 0.1576

Epoch 8/32

1147/1147 - 16s - 14ms/step - ia: 0.9543 - loss: 0.0103 - mae: 0.0737 - rmse: 0.0986 - smape: 0.2011 - val_ia: 0.8817 - val_loss: 0.0052 - val_mae: 0.0503 - val_rmse: 0.0668 - val_smape: 0.1443

Epoch 9/32

1147/1147 - 17s - 15ms/step - ia: 0.9556 - loss: 0.0097 - mae: 0.0717 - rmse: 0.0959 - smape: 0.1955 - val_ia: 0.8871 - val_loss: 0.0046 - val_mae: 0.0474 - val_rmse: 0.0631 - val_smape: 0.1340

Epoch 10/32

1147/1147 - 20s - 17ms/step - ia: 0.9569 - loss: 0.0093 - mae: 0.0696 - rmse: 0.0933 - smape: 0.1897 - val_ia: 0.8936 - val_loss: 0.0042 - val_mae: 0.0464 - val_rmse: 0.0612 - val_smape: 0.1445

Epoch 11/32

1147/1147 - 17s - 15ms/step - ia: 0.9583 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0905 - smape: 0.1862 - val_ia: 0.8972 - val_loss: 0.0039 - val_mae: 0.0437 - val_rmse: 0.0583 - val_smape: 0.1369

Epoch 12/32

1147/1147 - 17s - 14ms/step - ia: 0.9592 - loss: 0.0083 - mae: 0.0658 - rmse: 0.0885 - smape: 0.1825 - val_ia: 0.9063 - val_loss: 0.0034 - val_mae: 0.0402 - val_rmse: 0.0544 - val_smape: 0.1237

Epoch 13/32

1147/1147 - 17s - 15ms/step - ia: 0.9601 - loss: 0.0080 - mae: 0.0643 - rmse: 0.0864 - smape: 0.1779 - val_ia: 0.9023 - val_loss: 0.0035 - val_mae: 0.0410 - val_rmse: 0.0549 - val_smape: 0.1296

Epoch 14/32

1147/1147 - 16s - 14ms/step - ia: 0.9609 - loss: 0.0077 - mae: 0.0631 - rmse: 0.0844 - smape: 0.1777 - val_ia: 0.9008 - val_loss: 0.0035 - val_mae: 0.0414 - val_rmse: 0.0551 - val_smape: 0.1248

Epoch 15/32

1147/1147 - 17s - 15ms/step - ia: 0.9616 - loss: 0.0075 - mae: 0.0621 - rmse: 0.0833 - smape: 0.1725 - val_ia: 0.9002 - val_loss: 0.0034 - val_mae: 0.0412 - val_rmse: 0.0546 - val_smape: 0.1292

Epoch 16/32

1147/1147 - 16s - 14ms/step - ia: 0.9622 - loss: 0.0073 - mae: 0.0611 - rmse: 0.0827 - smape: 0.1709 - val_ia: 0.9092 - val_loss: 0.0030 - val_mae: 0.0379 - val_rmse: 0.0511 - val_smape: 0.1177

Epoch 17/32

1147/1147 - 16s - 14ms/step - ia: 0.9626 - loss: 0.0071 - mae: 0.0604 - rmse: 0.0813 - smape: 0.1695 - val_ia: 0.9041 - val_loss: 0.0031 - val_mae: 0.0394 - val_rmse: 0.0525 - val_smape: 0.1271

Epoch 18/32

1147/1147 - 21s - 18ms/step - ia: 0.9631 - loss: 0.0070 - mae: 0.0595 - rmse: 0.0805 - smape: 0.1657 - val_ia: 0.9107 - val_loss: 0.0029 - val_mae: 0.0373 - val_rmse: 0.0502 - val_smape: 0.1158

Epoch 19/32

1147/1147 - 15s - 13ms/step - ia: 0.9639 - loss: 0.0067 - mae: 0.0583 - rmse: 0.0787 - smape: 0.1643 - val_ia: 0.9137 - val_loss: 0.0028 - val_mae: 0.0362 - val_rmse: 0.0490 - val_smape: 0.1170

Epoch 20/32

1147/1147 - 14s - 12ms/step - ia: 0.9639 - loss: 0.0067 - mae: 0.0584 - rmse: 0.0788 - smape: 0.1643 - val_ia: 0.9153 - val_loss: 0.0027 - val_mae: 0.0356 - val_rmse: 0.0484 - val_smape: 0.1110

Epoch 21/32

1147/1147 - 15s - 13ms/step - ia: 0.9643 - loss: 0.0065 - mae: 0.0577 - rmse: 0.0778 - smape: 0.1625 - val_ia: 0.9014 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0532 - val_smape: 0.1168

Epoch 22/32

1147/1147 - 17s - 14ms/step - ia: 0.9647 - loss: 0.0064 - mae: 0.0570 - rmse: 0.0768 - smape: 0.1609 - val_ia: 0.9124 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0487 - val_smape: 0.1160

Epoch 23/32

1147/1147 - 15s - 13ms/step - ia: 0.9649 - loss: 0.0063 - mae: 0.0567 - rmse: 0.0764 - smape: 0.1600 - val_ia: 0.9125 - val_loss: 0.0028 - val_mae: 0.0371 - val_rmse: 0.0494 - val_smape: 0.1197

Epoch 24/32

1147/1147 - 15s - 13ms/step - ia: 0.9653 - loss: 0.0062 - mae: 0.0560 - rmse: 0.0757 - smape: 0.1581 - val_ia: 0.9128 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0486 - val_smape: 0.1138

Epoch 25/32

1147/1147 - 16s - 14ms/step - ia: 0.9656 - loss: 0.0061 - mae: 0.0555 - rmse: 0.0751 - smape: 0.1574 - val_ia: 0.9168 - val_loss: 0.0026 - val_mae: 0.0347 - val_rmse: 0.0470 - val_smape: 0.1107

Epoch 26/32

1147/1147 - 17s - 15ms/step - ia: 0.9658 - loss: 0.0061 - mae: 0.0554 - rmse: 0.0750 - smape: 0.1564 - val_ia: 0.9109 - val_loss: 0.0028 - val_mae: 0.0371 - val_rmse: 0.0495 - val_smape: 0.1123

Epoch 27/32

1147/1147 - 18s - 16ms/step - ia: 0.9658 - loss: 0.0060 - mae: 0.0553 - rmse: 0.0746 - smape: 0.1570 - val_ia: 0.9185 - val_loss: 0.0025 - val_mae: 0.0339 - val_rmse: 0.0461 - val_smape: 0.1075

Epoch 28/32

1147/1147 - 15s - 13ms/step - ia: 0.9663 - loss: 0.0059 - mae: 0.0546 - rmse: 0.0738 - smape: 0.1553 - val_ia: 0.9200 - val_loss: 0.0024 - val_mae: 0.0334 - val_rmse: 0.0455 - val_smape: 0.1073

Epoch 29/32

1147/1147 - 16s - 14ms/step - ia: 0.9664 - loss: 0.0059 - mae: 0.0543 - rmse: 0.0735 - smape: 0.1554 - val_ia: 0.9170 - val_loss: 0.0025 - val_mae: 0.0343 - val_rmse: 0.0463 - val_smape: 0.1129

Epoch 30/32

1147/1147 - 18s - 16ms/step - ia: 0.9665 - loss: 0.0058 - mae: 0.0541 - rmse: 0.0733 - smape: 0.1547 - val_ia: 0.9195 - val_loss: 0.0024 - val_mae: 0.0335 - val_rmse: 0.0457 - val_smape: 0.1093

Epoch 31/32

1147/1147 - 18s - 15ms/step - ia: 0.9665 - loss: 0.0059 - mae: 0.0541 - rmse: 0.0734 - smape: 0.1532 - val_ia: 0.9178 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0462 - val_smape: 0.1140

Epoch 32/32

1147/1147 - 14s - 12ms/step - ia: 0.9666 - loss: 0.0058 - mae: 0.0538 - rmse: 0.0728 - smape: 0.1533 - val_ia: 0.9188 - val_loss: 0.0024 - val_mae: 0.0339 - val_rmse: 0.0458 - val_smape: 0.1078

Restoring model weights from the end of the best epoch: 28.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:38 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 78%|███████▊  | 39/50 [7:42:19<1:41:34, 554.09s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 47s - 41ms/step - ia: 0.8521 - loss: 0.0954 - mae: 0.2158 - rmse: 0.2748 - smape: 0.5048 - val_ia: 0.7093 - val_loss: 0.0361 - val_mae: 0.1515 - val_rmse: 0.1801 - val_smape: 0.4293

Epoch 2/32

1147/1147 - 18s - 15ms/step - ia: 0.9459 - loss: 0.0152 - mae: 0.0869 - rmse: 0.1193 - smape: 0.2528 - val_ia: 0.8087 - val_loss: 0.0134 - val_mae: 0.0843 - val_rmse: 0.1077 - val_smape: 0.2466

Epoch 3/32

1147/1147 - 17s - 15ms/step - ia: 0.9571 - loss: 0.0105 - mae: 0.0691 - rmse: 0.0986 - smape: 0.2028 - val_ia: 0.8288 - val_loss: 0.0106 - val_mae: 0.0748 - val_rmse: 0.0960 - val_smape: 0.2192

Epoch 4/32

1147/1147 - 17s - 15ms/step - ia: 0.9620 - loss: 0.0084 - mae: 0.0610 - rmse: 0.0877 - smape: 0.1839 - val_ia: 0.8387 - val_loss: 0.0092 - val_mae: 0.0692 - val_rmse: 0.0891 - val_smape: 0.1916

Epoch 5/32

1147/1147 - 18s - 15ms/step - ia: 0.9661 - loss: 0.0068 - mae: 0.0545 - rmse: 0.0785 - smape: 0.1685 - val_ia: 0.8560 - val_loss: 0.0072 - val_mae: 0.0621 - val_rmse: 0.0799 - val_smape: 0.1842

Epoch 6/32

1147/1147 - 17s - 15ms/step - ia: 0.9692 - loss: 0.0056 - mae: 0.0495 - rmse: 0.0709 - smape: 0.1573 - val_ia: 0.8703 - val_loss: 0.0057 - val_mae: 0.0546 - val_rmse: 0.0709 - val_smape: 0.1583

Epoch 7/32

1147/1147 - 17s - 15ms/step - ia: 0.9720 - loss: 0.0048 - mae: 0.0452 - rmse: 0.0649 - smape: 0.1488 - val_ia: 0.8775 - val_loss: 0.0050 - val_mae: 0.0512 - val_rmse: 0.0660 - val_smape: 0.1462

Epoch 8/32

1147/1147 - 20s - 18ms/step - ia: 0.9739 - loss: 0.0042 - mae: 0.0420 - rmse: 0.0604 - smape: 0.1419 - val_ia: 0.8869 - val_loss: 0.0042 - val_mae: 0.0472 - val_rmse: 0.0612 - val_smape: 0.1412

Epoch 9/32

1147/1147 - 17s - 15ms/step - ia: 0.9753 - loss: 0.0038 - mae: 0.0398 - rmse: 0.0572 - smape: 0.1372 - val_ia: 0.9025 - val_loss: 0.0034 - val_mae: 0.0410 - val_rmse: 0.0543 - val_smape: 0.1257

Epoch 10/32

1147/1147 - 13s - 11ms/step - ia: 0.9764 - loss: 0.0035 - mae: 0.0381 - rmse: 0.0546 - smape: 0.1339 - val_ia: 0.9070 - val_loss: 0.0031 - val_mae: 0.0388 - val_rmse: 0.0515 - val_smape: 0.1214

Epoch 11/32

1147/1147 - 16s - 14ms/step - ia: 0.9771 - loss: 0.0033 - mae: 0.0368 - rmse: 0.0528 - smape: 0.1312 - val_ia: 0.9031 - val_loss: 0.0031 - val_mae: 0.0398 - val_rmse: 0.0522 - val_smape: 0.1262

Epoch 12/32

1147/1147 - 16s - 14ms/step - ia: 0.9777 - loss: 0.0032 - mae: 0.0359 - rmse: 0.0516 - smape: 0.1297 - val_ia: 0.9078 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0509 - val_smape: 0.1251

Epoch 13/32

1147/1147 - 12s - 10ms/step - ia: 0.9780 - loss: 0.0031 - mae: 0.0354 - rmse: 0.0509 - smape: 0.1286 - val_ia: 0.9095 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0492 - val_smape: 0.1181

Epoch 14/32

1147/1147 - 17s - 15ms/step - ia: 0.9782 - loss: 0.0031 - mae: 0.0351 - rmse: 0.0502 - smape: 0.1283 - val_ia: 0.9055 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0514 - val_smape: 0.1326

Epoch 15/32

1147/1147 - 15s - 13ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0351 - rmse: 0.0501 - smape: 0.1284 - val_ia: 0.9075 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0511 - val_smape: 0.1220

Epoch 16/32

1147/1147 - 13s - 11ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0349 - rmse: 0.0500 - smape: 0.1276 - val_ia: 0.9106 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0494 - val_smape: 0.1141

Epoch 17/32

1147/1147 - 17s - 15ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0348 - rmse: 0.0498 - smape: 0.1277 - val_ia: 0.9170 - val_loss: 0.0025 - val_mae: 0.0346 - val_rmse: 0.0465 - val_smape: 0.1144

Epoch 18/32

1147/1147 - 16s - 14ms/step - ia: 0.9784 - loss: 0.0030 - mae: 0.0347 - rmse: 0.0497 - smape: 0.1271 - val_ia: 0.9142 - val_loss: 0.0026 - val_mae: 0.0357 - val_rmse: 0.0476 - val_smape: 0.1198

Epoch 19/32

1147/1147 - 17s - 15ms/step - ia: 0.9785 - loss: 0.0030 - mae: 0.0346 - rmse: 0.0497 - smape: 0.1268 - val_ia: 0.9089 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0496 - val_smape: 0.1212

Epoch 20/32

1147/1147 - 14s - 12ms/step - ia: 0.9786 - loss: 0.0030 - mae: 0.0345 - rmse: 0.0495 - smape: 0.1267 - val_ia: 0.9123 - val_loss: 0.0026 - val_mae: 0.0363 - val_rmse: 0.0482 - val_smape: 0.1211

Epoch 21/32

1147/1147 - 12s - 11ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0344 - rmse: 0.0494 - smape: 0.1264 - val_ia: 0.9156 - val_loss: 0.0025 - val_mae: 0.0350 - val_rmse: 0.0469 - val_smape: 0.1148

Epoch 22/32

1147/1147 - 14s - 12ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0344 - rmse: 0.0493 - smape: 0.1263 - val_ia: 0.9128 - val_loss: 0.0026 - val_mae: 0.0364 - val_rmse: 0.0484 - val_smape: 0.1142

Epoch 23/32

1147/1147 - 16s - 14ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0344 - rmse: 0.0493 - smape: 0.1262 - val_ia: 0.9153 - val_loss: 0.0025 - val_mae: 0.0351 - val_rmse: 0.0470 - val_smape: 0.1145

Epoch 24/32

1147/1147 - 17s - 15ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0343 - rmse: 0.0493 - smape: 0.1262 - val_ia: 0.9107 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0490 - val_smape: 0.1167

Epoch 25/32

1147/1147 - 16s - 14ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0491 - smape: 0.1261 - val_ia: 0.9088 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0488 - val_smape: 0.1156

Epoch 26/32

1147/1147 - 16s - 14ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0491 - smape: 0.1259 - val_ia: 0.9069 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0496 - val_smape: 0.1213

Epoch 27/32

1147/1147 - 13s - 12ms/step - ia: 0.9788 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0491 - smape: 0.1255 - val_ia: 0.9088 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0494 - val_smape: 0.1197

Epoch 28/32

1147/1147 - 13s - 12ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0491 - smape: 0.1251 - val_ia: 0.9125 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0478 - val_smape: 0.1155

Epoch 29/32

1147/1147 - 16s - 14ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0341 - rmse: 0.0490 - smape: 0.1255 - val_ia: 0.9143 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0479 - val_smape: 0.1168

Epoch 30/32

1147/1147 - 17s - 15ms/step - ia: 0.9788 - loss: 0.0029 - mae: 0.0341 - rmse: 0.0489 - smape: 0.1254 - val_ia: 0.9099 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0488 - val_smape: 0.1213

Epoch 31/32

1147/1147 - 16s - 14ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0489 - smape: 0.1258 - val_ia: 0.9097 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0490 - val_smape: 0.1247

Epoch 32/32

1147/1147 - 16s - 14ms/step - ia: 0.9789 - loss: 0.0029 - mae: 0.0340 - rmse: 0.0487 - smape: 0.1247 - val_ia: 0.9097 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0482 - val_smape: 0.1171

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:30 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 80%|████████  | 40/50 [7:51:21<1:31:46, 550.66s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 23s - 20ms/step - ia: 0.6805 - loss: 0.3345 - mae: 0.4473 - rmse: 0.5558 - smape: 0.8208 - val_ia: 0.4890 - val_loss: 0.1479 - val_mae: 0.3064 - val_rmse: 0.3613 - val_smape: 0.6299

Epoch 2/32

1147/1147 - 8s - 7ms/step - ia: 0.8585 - loss: 0.0872 - mae: 0.2246 - rmse: 0.2890 - smape: 0.5122 - val_ia: 0.6544 - val_loss: 0.0536 - val_mae: 0.1818 - val_rmse: 0.2188 - val_smape: 0.4472

Epoch 3/32

1147/1147 - 8s - 7ms/step - ia: 0.9154 - loss: 0.0329 - mae: 0.1357 - rmse: 0.1777 - smape: 0.3560 - val_ia: 0.7275 - val_loss: 0.0308 - val_mae: 0.1394 - val_rmse: 0.1655 - val_smape: 0.3970

Epoch 4/32

1147/1147 - 8s - 7ms/step - ia: 0.9383 - loss: 0.0185 - mae: 0.0995 - rmse: 0.1326 - smape: 0.2817 - val_ia: 0.7734 - val_loss: 0.0187 - val_mae: 0.1070 - val_rmse: 0.1298 - val_smape: 0.3226

Epoch 5/32

1147/1147 - 7s - 7ms/step - ia: 0.9511 - loss: 0.0123 - mae: 0.0788 - rmse: 0.1077 - smape: 0.2318 - val_ia: 0.8153 - val_loss: 0.0117 - val_mae: 0.0822 - val_rmse: 0.1030 - val_smape: 0.2544

Epoch 6/32

1147/1147 - 7s - 6ms/step - ia: 0.9587 - loss: 0.0092 - mae: 0.0666 - rmse: 0.0924 - smape: 0.1998 - val_ia: 0.8410 - val_loss: 0.0086 - val_mae: 0.0693 - val_rmse: 0.0885 - val_smape: 0.2118

Epoch 7/32

1147/1147 - 7s - 6ms/step - ia: 0.9635 - loss: 0.0075 - mae: 0.0590 - rmse: 0.0828 - smape: 0.1793 - val_ia: 0.8554 - val_loss: 0.0072 - val_mae: 0.0623 - val_rmse: 0.0805 - val_smape: 0.1859

Epoch 8/32

1147/1147 - 7s - 6ms/step - ia: 0.9666 - loss: 0.0064 - mae: 0.0539 - rmse: 0.0763 - smape: 0.1655 - val_ia: 0.8622 - val_loss: 0.0065 - val_mae: 0.0585 - val_rmse: 0.0759 - val_smape: 0.1695

Epoch 9/32

1147/1147 - 6s - 5ms/step - ia: 0.9689 - loss: 0.0057 - mae: 0.0503 - rmse: 0.0715 - smape: 0.1563 - val_ia: 0.8704 - val_loss: 0.0057 - val_mae: 0.0546 - val_rmse: 0.0712 - val_smape: 0.1543

Epoch 10/32

1147/1147 - 8s - 7ms/step - ia: 0.9705 - loss: 0.0052 - mae: 0.0475 - rmse: 0.0678 - smape: 0.1499 - val_ia: 0.8706 - val_loss: 0.0055 - val_mae: 0.0542 - val_rmse: 0.0702 - val_smape: 0.1537

Epoch 11/32

1147/1147 - 9s - 8ms/step - ia: 0.9718 - loss: 0.0048 - mae: 0.0454 - rmse: 0.0649 - smape: 0.1454 - val_ia: 0.8752 - val_loss: 0.0051 - val_mae: 0.0520 - val_rmse: 0.0675 - val_smape: 0.1482

Epoch 12/32

1147/1147 - 10s - 9ms/step - ia: 0.9729 - loss: 0.0045 - mae: 0.0437 - rmse: 0.0626 - smape: 0.1420 - val_ia: 0.8789 - val_loss: 0.0048 - val_mae: 0.0506 - val_rmse: 0.0656 - val_smape: 0.1447

Epoch 13/32

1147/1147 - 9s - 8ms/step - ia: 0.9737 - loss: 0.0042 - mae: 0.0424 - rmse: 0.0608 - smape: 0.1399 - val_ia: 0.8833 - val_loss: 0.0045 - val_mae: 0.0485 - val_rmse: 0.0631 - val_smape: 0.1402

Epoch 14/32

1147/1147 - 9s - 8ms/step - ia: 0.9744 - loss: 0.0040 - mae: 0.0413 - rmse: 0.0592 - smape: 0.1376 - val_ia: 0.8821 - val_loss: 0.0045 - val_mae: 0.0488 - val_rmse: 0.0631 - val_smape: 0.1409

Epoch 15/32

1147/1147 - 9s - 8ms/step - ia: 0.9749 - loss: 0.0039 - mae: 0.0404 - rmse: 0.0579 - smape: 0.1359 - val_ia: 0.8897 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0605 - val_smape: 0.1373

Epoch 16/32

1147/1147 - 9s - 8ms/step - ia: 0.9754 - loss: 0.0038 - mae: 0.0396 - rmse: 0.0569 - smape: 0.1344 - val_ia: 0.8923 - val_loss: 0.0039 - val_mae: 0.0450 - val_rmse: 0.0588 - val_smape: 0.1324

Epoch 17/32

1147/1147 - 9s - 8ms/step - ia: 0.9758 - loss: 0.0037 - mae: 0.0390 - rmse: 0.0559 - smape: 0.1331 - val_ia: 0.8939 - val_loss: 0.0038 - val_mae: 0.0442 - val_rmse: 0.0579 - val_smape: 0.1310

Epoch 18/32

1147/1147 - 9s - 8ms/step - ia: 0.9762 - loss: 0.0036 - mae: 0.0383 - rmse: 0.0551 - smape: 0.1320 - val_ia: 0.8950 - val_loss: 0.0037 - val_mae: 0.0437 - val_rmse: 0.0571 - val_smape: 0.1307

Epoch 19/32

1147/1147 - 7s - 6ms/step - ia: 0.9765 - loss: 0.0035 - mae: 0.0379 - rmse: 0.0545 - smape: 0.1315 - val_ia: 0.8961 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0566 - val_smape: 0.1301

Epoch 20/32

1147/1147 - 7s - 6ms/step - ia: 0.9767 - loss: 0.0034 - mae: 0.0375 - rmse: 0.0538 - smape: 0.1306 - val_ia: 0.8950 - val_loss: 0.0036 - val_mae: 0.0434 - val_rmse: 0.0567 - val_smape: 0.1293

Epoch 21/32

1147/1147 - 7s - 6ms/step - ia: 0.9770 - loss: 0.0034 - mae: 0.0371 - rmse: 0.0534 - smape: 0.1300 - val_ia: 0.9024 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0541 - val_smape: 0.1243

Epoch 22/32

1147/1147 - 6s - 5ms/step - ia: 0.9772 - loss: 0.0033 - mae: 0.0367 - rmse: 0.0529 - smape: 0.1297 - val_ia: 0.9035 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0536 - val_smape: 0.1244

Epoch 23/32

1147/1147 - 7s - 6ms/step - ia: 0.9774 - loss: 0.0033 - mae: 0.0364 - rmse: 0.0524 - smape: 0.1291 - val_ia: 0.9036 - val_loss: 0.0032 - val_mae: 0.0404 - val_rmse: 0.0535 - val_smape: 0.1240

Epoch 24/32

1147/1147 - 6s - 6ms/step - ia: 0.9775 - loss: 0.0032 - mae: 0.0362 - rmse: 0.0521 - smape: 0.1290 - val_ia: 0.9004 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0541 - val_smape: 0.1230

Epoch 25/32

1147/1147 - 8s - 7ms/step - ia: 0.9777 - loss: 0.0032 - mae: 0.0360 - rmse: 0.0517 - smape: 0.1284 - val_ia: 0.9064 - val_loss: 0.0031 - val_mae: 0.0392 - val_rmse: 0.0522 - val_smape: 0.1213

Epoch 26/32

1147/1147 - 9s - 8ms/step - ia: 0.9778 - loss: 0.0032 - mae: 0.0358 - rmse: 0.0515 - smape: 0.1282 - val_ia: 0.9053 - val_loss: 0.0031 - val_mae: 0.0393 - val_rmse: 0.0522 - val_smape: 0.1205

Epoch 27/32

1147/1147 - 8s - 7ms/step - ia: 0.9779 - loss: 0.0031 - mae: 0.0356 - rmse: 0.0512 - smape: 0.1283 - val_ia: 0.9021 - val_loss: 0.0032 - val_mae: 0.0404 - val_rmse: 0.0531 - val_smape: 0.1217

Epoch 28/32

1147/1147 - 8s - 7ms/step - ia: 0.9779 - loss: 0.0031 - mae: 0.0355 - rmse: 0.0511 - smape: 0.1279 - val_ia: 0.9045 - val_loss: 0.0031 - val_mae: 0.0396 - val_rmse: 0.0523 - val_smape: 0.1203

Epoch 29/32

1147/1147 - 8s - 7ms/step - ia: 0.9780 - loss: 0.0031 - mae: 0.0354 - rmse: 0.0509 - smape: 0.1275 - val_ia: 0.9060 - val_loss: 0.0030 - val_mae: 0.0392 - val_rmse: 0.0519 - val_smape: 0.1194

Epoch 30/32

1147/1147 - 8s - 7ms/step - ia: 0.9781 - loss: 0.0031 - mae: 0.0353 - rmse: 0.0506 - smape: 0.1279 - val_ia: 0.9091 - val_loss: 0.0029 - val_mae: 0.0380 - val_rmse: 0.0508 - val_smape: 0.1188

Epoch 31/32

1147/1147 - 9s - 7ms/step - ia: 0.9782 - loss: 0.0031 - mae: 0.0351 - rmse: 0.0506 - smape: 0.1272 - val_ia: 0.9095 - val_loss: 0.0029 - val_mae: 0.0379 - val_rmse: 0.0506 - val_smape: 0.1188

Epoch 32/32

1147/1147 - 10s - 9ms/step - ia: 0.9782 - loss: 0.0031 - mae: 0.0350 - rmse: 0.0505 - smape: 0.1272 - val_ia: 0.9109 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0500 - val_smape: 0.1167

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:52 1s/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 82%|████████▏ | 41/50 [7:55:55<1:10:08, 467.57s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 40s - 35ms/step - ia: 0.7799 - loss: 0.1709 - mae: 0.3147 - rmse: 0.3956 - smape: 0.6684 - val_ia: 0.5762 - val_loss: 0.1224 - val_mae: 0.2747 - val_rmse: 0.3162 - val_smape: 0.6195

Epoch 2/32

1147/1147 - 14s - 12ms/step - ia: 0.8705 - loss: 0.0731 - mae: 0.2054 - rmse: 0.2663 - smape: 0.4668 - val_ia: 0.6476 - val_loss: 0.0625 - val_mae: 0.2019 - val_rmse: 0.2344 - val_smape: 0.5125

Epoch 3/32

1147/1147 - 16s - 14ms/step - ia: 0.8971 - loss: 0.0475 - mae: 0.1641 - rmse: 0.2145 - smape: 0.3871 - val_ia: 0.7312 - val_loss: 0.0301 - val_mae: 0.1356 - val_rmse: 0.1653 - val_smape: 0.3777

Epoch 4/32

1147/1147 - 18s - 16ms/step - ia: 0.9121 - loss: 0.0353 - mae: 0.1406 - rmse: 0.1851 - smape: 0.3388 - val_ia: 0.7824 - val_loss: 0.0189 - val_mae: 0.1023 - val_rmse: 0.1303 - val_smape: 0.2989

Epoch 5/32

1147/1147 - 19s - 16ms/step - ia: 0.9193 - loss: 0.0300 - mae: 0.1294 - rmse: 0.1702 - smape: 0.3127 - val_ia: 0.7917 - val_loss: 0.0167 - val_mae: 0.0961 - val_rmse: 0.1220 - val_smape: 0.2837

Epoch 6/32

1147/1147 - 16s - 14ms/step - ia: 0.9226 - loss: 0.0278 - mae: 0.1242 - rmse: 0.1642 - smape: 0.3019 - val_ia: 0.8048 - val_loss: 0.0149 - val_mae: 0.0887 - val_rmse: 0.1139 - val_smape: 0.2573

Epoch 7/32

1147/1147 - 14s - 12ms/step - ia: 0.9257 - loss: 0.0259 - mae: 0.1193 - rmse: 0.1582 - smape: 0.2899 - val_ia: 0.8091 - val_loss: 0.0139 - val_mae: 0.0860 - val_rmse: 0.1104 - val_smape: 0.2494

Epoch 8/32

1147/1147 - 16s - 14ms/step - ia: 0.9291 - loss: 0.0237 - mae: 0.1140 - rmse: 0.1511 - smape: 0.2826 - val_ia: 0.8239 - val_loss: 0.0121 - val_mae: 0.0792 - val_rmse: 0.1029 - val_smape: 0.2351

Epoch 9/32

1147/1147 - 18s - 15ms/step - ia: 0.9302 - loss: 0.0230 - mae: 0.1120 - rmse: 0.1486 - smape: 0.2747 - val_ia: 0.8251 - val_loss: 0.0117 - val_mae: 0.0776 - val_rmse: 0.1008 - val_smape: 0.2253

Epoch 10/32

1147/1147 - 16s - 14ms/step - ia: 0.9325 - loss: 0.0218 - mae: 0.1087 - rmse: 0.1448 - smape: 0.2679 - val_ia: 0.8345 - val_loss: 0.0106 - val_mae: 0.0739 - val_rmse: 0.0965 - val_smape: 0.2206

Epoch 11/32

1147/1147 - 15s - 13ms/step - ia: 0.9342 - loss: 0.0206 - mae: 0.1057 - rmse: 0.1409 - smape: 0.2628 - val_ia: 0.8361 - val_loss: 0.0102 - val_mae: 0.0725 - val_rmse: 0.0947 - val_smape: 0.2122

Epoch 12/32

1147/1147 - 16s - 14ms/step - ia: 0.9353 - loss: 0.0199 - mae: 0.1039 - rmse: 0.1383 - smape: 0.2607 - val_ia: 0.8408 - val_loss: 0.0096 - val_mae: 0.0706 - val_rmse: 0.0921 - val_smape: 0.2120

Epoch 13/32

1147/1147 - 16s - 14ms/step - ia: 0.9364 - loss: 0.0192 - mae: 0.1024 - rmse: 0.1358 - smape: 0.2549 - val_ia: 0.8441 - val_loss: 0.0091 - val_mae: 0.0681 - val_rmse: 0.0893 - val_smape: 0.2018

Epoch 14/32

1147/1147 - 15s - 13ms/step - ia: 0.9374 - loss: 0.0187 - mae: 0.1006 - rmse: 0.1341 - smape: 0.2500 - val_ia: 0.8486 - val_loss: 0.0086 - val_mae: 0.0665 - val_rmse: 0.0874 - val_smape: 0.1985

Epoch 15/32

1147/1147 - 13s - 11ms/step - ia: 0.9384 - loss: 0.0182 - mae: 0.0992 - rmse: 0.1324 - smape: 0.2497 - val_ia: 0.8604 - val_loss: 0.0077 - val_mae: 0.0622 - val_rmse: 0.0825 - val_smape: 0.1867

Epoch 16/32

1147/1147 - 12s - 11ms/step - ia: 0.9398 - loss: 0.0175 - mae: 0.0970 - rmse: 0.1293 - smape: 0.2433 - val_ia: 0.8545 - val_loss: 0.0079 - val_mae: 0.0633 - val_rmse: 0.0834 - val_smape: 0.1882

Epoch 17/32

1147/1147 - 15s - 13ms/step - ia: 0.9404 - loss: 0.0172 - mae: 0.0960 - rmse: 0.1283 - smape: 0.2419 - val_ia: 0.8592 - val_loss: 0.0075 - val_mae: 0.0623 - val_rmse: 0.0818 - val_smape: 0.1890

Epoch 18/32

1147/1147 - 16s - 14ms/step - ia: 0.9413 - loss: 0.0165 - mae: 0.0946 - rmse: 0.1258 - smape: 0.2390 - val_ia: 0.8623 - val_loss: 0.0072 - val_mae: 0.0602 - val_rmse: 0.0795 - val_smape: 0.1799

Epoch 19/32

1147/1147 - 15s - 13ms/step - ia: 0.9419 - loss: 0.0163 - mae: 0.0936 - rmse: 0.1249 - smape: 0.2347 - val_ia: 0.8630 - val_loss: 0.0070 - val_mae: 0.0596 - val_rmse: 0.0787 - val_smape: 0.1775

Epoch 20/32

1147/1147 - 16s - 14ms/step - ia: 0.9427 - loss: 0.0158 - mae: 0.0922 - rmse: 0.1229 - smape: 0.2344 - val_ia: 0.8620 - val_loss: 0.0069 - val_mae: 0.0599 - val_rmse: 0.0785 - val_smape: 0.1805

Epoch 21/32

1147/1147 - 16s - 14ms/step - ia: 0.9434 - loss: 0.0154 - mae: 0.0911 - rmse: 0.1215 - smape: 0.2302 - val_ia: 0.8659 - val_loss: 0.0066 - val_mae: 0.0576 - val_rmse: 0.0762 - val_smape: 0.1699

Epoch 22/32

1147/1147 - 16s - 14ms/step - ia: 0.9439 - loss: 0.0151 - mae: 0.0904 - rmse: 0.1203 - smape: 0.2274 - val_ia: 0.8678 - val_loss: 0.0063 - val_mae: 0.0565 - val_rmse: 0.0749 - val_smape: 0.1654

Epoch 23/32

1147/1147 - 16s - 14ms/step - ia: 0.9448 - loss: 0.0148 - mae: 0.0889 - rmse: 0.1191 - smape: 0.2251 - val_ia: 0.8614 - val_loss: 0.0067 - val_mae: 0.0590 - val_rmse: 0.0768 - val_smape: 0.1743

Epoch 24/32

1147/1147 - 21s - 18ms/step - ia: 0.9450 - loss: 0.0145 - mae: 0.0884 - rmse: 0.1179 - smape: 0.2227 - val_ia: 0.8702 - val_loss: 0.0061 - val_mae: 0.0566 - val_rmse: 0.0740 - val_smape: 0.1732

Epoch 25/32

1147/1147 - 16s - 14ms/step - ia: 0.9456 - loss: 0.0143 - mae: 0.0878 - rmse: 0.1171 - smape: 0.2242 - val_ia: 0.8722 - val_loss: 0.0058 - val_mae: 0.0548 - val_rmse: 0.0721 - val_smape: 0.1646

Epoch 26/32

1147/1147 - 15s - 13ms/step - ia: 0.9461 - loss: 0.0141 - mae: 0.0869 - rmse: 0.1159 - smape: 0.2190 - val_ia: 0.8755 - val_loss: 0.0057 - val_mae: 0.0545 - val_rmse: 0.0715 - val_smape: 0.1684

Epoch 27/32

1147/1147 - 16s - 14ms/step - ia: 0.9466 - loss: 0.0139 - mae: 0.0861 - rmse: 0.1151 - smape: 0.2190 - val_ia: 0.8795 - val_loss: 0.0054 - val_mae: 0.0521 - val_rmse: 0.0691 - val_smape: 0.1585

Epoch 28/32

1147/1147 - 16s - 14ms/step - ia: 0.9473 - loss: 0.0135 - mae: 0.0851 - rmse: 0.1136 - smape: 0.2170 - val_ia: 0.8788 - val_loss: 0.0053 - val_mae: 0.0525 - val_rmse: 0.0691 - val_smape: 0.1605

Epoch 29/32

1147/1147 - 16s - 14ms/step - ia: 0.9475 - loss: 0.0133 - mae: 0.0845 - rmse: 0.1127 - smape: 0.2158 - val_ia: 0.8781 - val_loss: 0.0053 - val_mae: 0.0524 - val_rmse: 0.0689 - val_smape: 0.1597

Epoch 30/32

1147/1147 - 16s - 14ms/step - ia: 0.9485 - loss: 0.0130 - mae: 0.0831 - rmse: 0.1114 - smape: 0.2130 - val_ia: 0.8780 - val_loss: 0.0052 - val_mae: 0.0520 - val_rmse: 0.0683 - val_smape: 0.1561

Epoch 31/32

1147/1147 - 15s - 13ms/step - ia: 0.9487 - loss: 0.0129 - mae: 0.0828 - rmse: 0.1108 - smape: 0.2118 - val_ia: 0.8872 - val_loss: 0.0047 - val_mae: 0.0487 - val_rmse: 0.0648 - val_smape: 0.1474

Epoch 32/32

1147/1147 - 14s - 12ms/step - ia: 0.9491 - loss: 0.0125 - mae: 0.0818 - rmse: 0.1092 - smape: 0.2107 - val_ia: 0.8818 - val_loss: 0.0049 - val_mae: 0.0505 - val_rmse: 0.0664 - val_smape: 0.1526

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:56 719ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 84%|████████▍ | 42/50 [8:04:48<1:04:58, 487.29s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1147/1147 - 37s - 32ms/step - ia: 0.3387 - loss: 0.7152 - mae: 0.6968 - rmse: 0.8407 - smape: 1.3489 - val_ia: 0.3080 - val_loss: 0.6022 - val_mae: 0.6384 - val_rmse: 0.7056 - val_smape: 1.3197

Epoch 2/64

1147/1147 - 20s - 17ms/step - ia: 0.4285 - loss: 0.5953 - mae: 0.6308 - rmse: 0.7671 - smape: 1.2009 - val_ia: 0.3381 - val_loss: 0.5049 - val_mae: 0.5821 - val_rmse: 0.6450 - val_smape: 1.1423

Epoch 3/64

1147/1147 - 19s - 17ms/step - ia: 0.5197 - loss: 0.4800 - mae: 0.5609 - rmse: 0.6880 - smape: 1.0510 - val_ia: 0.3679 - val_loss: 0.4185 - val_mae: 0.5275 - val_rmse: 0.5858 - val_smape: 0.9986

Epoch 4/64

1147/1147 - 19s - 17ms/step - ia: 0.6069 - loss: 0.3754 - mae: 0.4911 - rmse: 0.6079 - smape: 0.9160 - val_ia: 0.4001 - val_loss: 0.3523 - val_mae: 0.4810 - val_rmse: 0.5350 - val_smape: 0.8926

Epoch 5/64

1147/1147 - 19s - 16ms/step - ia: 0.6779 - loss: 0.2939 - mae: 0.4297 - rmse: 0.5376 - smape: 0.8119 - val_ia: 0.4291 - val_loss: 0.3137 - val_mae: 0.4490 - val_rmse: 0.5009 - val_smape: 0.8228

Epoch 6/64

1147/1147 - 19s - 17ms/step - ia: 0.7293 - loss: 0.2399 - mae: 0.3837 - rmse: 0.4852 - smape: 0.7382 - val_ia: 0.4430 - val_loss: 0.3017 - val_mae: 0.4392 - val_rmse: 0.4897 - val_smape: 0.7907

Epoch 7/64

1147/1147 - 19s - 17ms/step - ia: 0.7587 - loss: 0.2103 - mae: 0.3575 - rmse: 0.4537 - smape: 0.6948 - val_ia: 0.4406 - val_loss: 0.3028 - val_mae: 0.4434 - val_rmse: 0.4918 - val_smape: 0.7835

Epoch 8/64

1147/1147 - 21s - 18ms/step - ia: 0.7763 - loss: 0.1932 - mae: 0.3408 - rmse: 0.4349 - smape: 0.6664 - val_ia: 0.4428 - val_loss: 0.3025 - val_mae: 0.4452 - val_rmse: 0.4927 - val_smape: 0.7795

Epoch 9/64

1147/1147 - 16s - 14ms/step - ia: 0.7842 - loss: 0.1843 - mae: 0.3333 - rmse: 0.4246 - smape: 0.6528 - val_ia: 0.4463 - val_loss: 0.2984 - val_mae: 0.4432 - val_rmse: 0.4896 - val_smape: 0.7754

Epoch 10/64

1147/1147 - 17s - 15ms/step - ia: 0.7921 - loss: 0.1748 - mae: 0.3233 - rmse: 0.4131 - smape: 0.6383 - val_ia: 0.4517 - val_loss: 0.2887 - val_mae: 0.4366 - val_rmse: 0.4817 - val_smape: 0.7685

Epoch 11/64

1147/1147 - 21s - 18ms/step - ia: 0.7969 - loss: 0.1680 - mae: 0.3168 - rmse: 0.4052 - smape: 0.6273 - val_ia: 0.4581 - val_loss: 0.2766 - val_mae: 0.4279 - val_rmse: 0.4718 - val_smape: 0.7603

Epoch 12/64

1147/1147 - 23s - 20ms/step - ia: 0.8014 - loss: 0.1612 - mae: 0.3098 - rmse: 0.3969 - smape: 0.6159 - val_ia: 0.4646 - val_loss: 0.2644 - val_mae: 0.4187 - val_rmse: 0.4613 - val_smape: 0.7517

Epoch 13/64

1147/1147 - 20s - 17ms/step - ia: 0.8050 - loss: 0.1563 - mae: 0.3049 - rmse: 0.3908 - smape: 0.6084 - val_ia: 0.4712 - val_loss: 0.2520 - val_mae: 0.4092 - val_rmse: 0.4507 - val_smape: 0.7421

Epoch 14/64

1147/1147 - 22s - 19ms/step - ia: 0.8102 - loss: 0.1499 - mae: 0.2975 - rmse: 0.3827 - smape: 0.5986 - val_ia: 0.4780 - val_loss: 0.2395 - val_mae: 0.3993 - val_rmse: 0.4398 - val_smape: 0.7323

Epoch 15/64

1147/1147 - 22s - 19ms/step - ia: 0.8137 - loss: 0.1444 - mae: 0.2921 - rmse: 0.3756 - smape: 0.5895 - val_ia: 0.4850 - val_loss: 0.2272 - val_mae: 0.3892 - val_rmse: 0.4287 - val_smape: 0.7222

Epoch 16/64

1147/1147 - 42s - 36ms/step - ia: 0.8177 - loss: 0.1387 - mae: 0.2864 - rmse: 0.3678 - smape: 0.5801 - val_ia: 0.4921 - val_loss: 0.2152 - val_mae: 0.3790 - val_rmse: 0.4175 - val_smape: 0.7120

Epoch 17/64

1147/1147 - 22s - 19ms/step - ia: 0.8211 - loss: 0.1342 - mae: 0.2815 - rmse: 0.3622 - smape: 0.5705 - val_ia: 0.4988 - val_loss: 0.2040 - val_mae: 0.3695 - val_rmse: 0.4070 - val_smape: 0.7021

Epoch 18/64

1147/1147 - 21s - 19ms/step - ia: 0.8242 - loss: 0.1296 - mae: 0.2766 - rmse: 0.3557 - smape: 0.5652 - val_ia: 0.5063 - val_loss: 0.1919 - val_mae: 0.3587 - val_rmse: 0.3953 - val_smape: 0.6911

Epoch 19/64

1147/1147 - 20s - 18ms/step - ia: 0.8272 - loss: 0.1259 - mae: 0.2721 - rmse: 0.3504 - smape: 0.5566 - val_ia: 0.5130 - val_loss: 0.1821 - val_mae: 0.3496 - val_rmse: 0.3853 - val_smape: 0.6816

Epoch 20/64

1147/1147 - 21s - 19ms/step - ia: 0.8308 - loss: 0.1209 - mae: 0.2665 - rmse: 0.3435 - smape: 0.5476 - val_ia: 0.5197 - val_loss: 0.1725 - val_mae: 0.3406 - val_rmse: 0.3755 - val_smape: 0.6721

Epoch 21/64

1147/1147 - 21s - 18ms/step - ia: 0.8338 - loss: 0.1169 - mae: 0.2621 - rmse: 0.3379 - smape: 0.5403 - val_ia: 0.5274 - val_loss: 0.1614 - val_mae: 0.3299 - val_rmse: 0.3641 - val_smape: 0.6609

Epoch 22/64

1147/1147 - 22s - 19ms/step - ia: 0.8368 - loss: 0.1135 - mae: 0.2584 - rmse: 0.3326 - smape: 0.5355 - val_ia: 0.5343 - val_loss: 0.1525 - val_mae: 0.3208 - val_rmse: 0.3542 - val_smape: 0.6511

Epoch 23/64

1147/1147 - 21s - 19ms/step - ia: 0.8397 - loss: 0.1105 - mae: 0.2542 - rmse: 0.3284 - smape: 0.5263 - val_ia: 0.5422 - val_loss: 0.1426 - val_mae: 0.3104 - val_rmse: 0.3432 - val_smape: 0.6394

Epoch 24/64

1147/1147 - 21s - 18ms/step - ia: 0.8421 - loss: 0.1070 - mae: 0.2501 - rmse: 0.3232 - smape: 0.5176 - val_ia: 0.5483 - val_loss: 0.1355 - val_mae: 0.3028 - val_rmse: 0.3349 - val_smape: 0.6310

Epoch 25/64

1147/1147 - 42s - 36ms/step - ia: 0.8432 - loss: 0.1054 - mae: 0.2477 - rmse: 0.3207 - smape: 0.5135 - val_ia: 0.5563 - val_loss: 0.1268 - val_mae: 0.2929 - val_rmse: 0.3244 - val_smape: 0.6196

Epoch 26/64

1147/1147 - 17s - 15ms/step - ia: 0.8472 - loss: 0.1016 - mae: 0.2423 - rmse: 0.3146 - smape: 0.5048 - val_ia: 0.5638 - val_loss: 0.1190 - val_mae: 0.2838 - val_rmse: 0.3148 - val_smape: 0.6087

Epoch 27/64

1147/1147 - 16s - 14ms/step - ia: 0.8478 - loss: 0.0998 - mae: 0.2412 - rmse: 0.3122 - smape: 0.5034 - val_ia: 0.5709 - val_loss: 0.1119 - val_mae: 0.2754 - val_rmse: 0.3058 - val_smape: 0.5983

Epoch 28/64

1147/1147 - 18s - 16ms/step - ia: 0.8516 - loss: 0.0958 - mae: 0.2357 - rmse: 0.3056 - smape: 0.4931 - val_ia: 0.5788 - val_loss: 0.1051 - val_mae: 0.2665 - val_rmse: 0.2964 - val_smape: 0.5870

Epoch 29/64

1147/1147 - 22s - 19ms/step - ia: 0.8520 - loss: 0.0949 - mae: 0.2350 - rmse: 0.3045 - smape: 0.4913 - val_ia: 0.5859 - val_loss: 0.0990 - val_mae: 0.2587 - val_rmse: 0.2882 - val_smape: 0.5765

Epoch 30/64

1147/1147 - 20s - 17ms/step - ia: 0.8547 - loss: 0.0921 - mae: 0.2304 - rmse: 0.2994 - smape: 0.4816 - val_ia: 0.5931 - val_loss: 0.0932 - val_mae: 0.2508 - val_rmse: 0.2798 - val_smape: 0.5654

Epoch 31/64

1147/1147 - 17s - 15ms/step - ia: 0.8573 - loss: 0.0890 - mae: 0.2269 - rmse: 0.2948 - smape: 0.4761 - val_ia: 0.6005 - val_loss: 0.0877 - val_mae: 0.2432 - val_rmse: 0.2719 - val_smape: 0.5544

Epoch 32/64

1147/1147 - 20s - 17ms/step - ia: 0.8596 - loss: 0.0868 - mae: 0.2238 - rmse: 0.2908 - smape: 0.4703 - val_ia: 0.6077 - val_loss: 0.0826 - val_mae: 0.2357 - val_rmse: 0.2641 - val_smape: 0.5434

Epoch 33/64

1147/1147 - 21s - 18ms/step - ia: 0.8594 - loss: 0.0864 - mae: 0.2237 - rmse: 0.2902 - smape: 0.4670 - val_ia: 0.6161 - val_loss: 0.0773 - val_mae: 0.2274 - val_rmse: 0.2555 - val_smape: 0.5293

Epoch 34/64

1147/1147 - 19s - 17ms/step - ia: 0.8623 - loss: 0.0839 - mae: 0.2194 - rmse: 0.2857 - smape: 0.4616 - val_ia: 0.6239 - val_loss: 0.0729 - val_mae: 0.2201 - val_rmse: 0.2481 - val_smape: 0.5164

Epoch 35/64

1147/1147 - 21s - 18ms/step - ia: 0.8626 - loss: 0.0834 - mae: 0.2185 - rmse: 0.2848 - smape: 0.4609 - val_ia: 0.6317 - val_loss: 0.0684 - val_mae: 0.2126 - val_rmse: 0.2405 - val_smape: 0.5026

Epoch 36/64

1147/1147 - 19s - 17ms/step - ia: 0.8649 - loss: 0.0803 - mae: 0.2147 - rmse: 0.2795 - smape: 0.4533 - val_ia: 0.6372 - val_loss: 0.0654 - val_mae: 0.2075 - val_rmse: 0.2350 - val_smape: 0.4934

Epoch 37/64

1147/1147 - 21s - 18ms/step - ia: 0.8659 - loss: 0.0794 - mae: 0.2131 - rmse: 0.2779 - smape: 0.4498 - val_ia: 0.6441 - val_loss: 0.0616 - val_mae: 0.2012 - val_rmse: 0.2286 - val_smape: 0.4813

Epoch 38/64

1147/1147 - 21s - 18ms/step - ia: 0.8674 - loss: 0.0777 - mae: 0.2115 - rmse: 0.2751 - smape: 0.4492 - val_ia: 0.6505 - val_loss: 0.0585 - val_mae: 0.1955 - val_rmse: 0.2228 - val_smape: 0.4698

Epoch 39/64

1147/1147 - 20s - 17ms/step - ia: 0.8681 - loss: 0.0765 - mae: 0.2101 - rmse: 0.2728 - smape: 0.4458 - val_ia: 0.6574 - val_loss: 0.0553 - val_mae: 0.1894 - val_rmse: 0.2166 - val_smape: 0.4574

Epoch 40/64

1147/1147 - 21s - 18ms/step - ia: 0.8699 - loss: 0.0751 - mae: 0.2074 - rmse: 0.2701 - smape: 0.4398 - val_ia: 0.6630 - val_loss: 0.0529 - val_mae: 0.1847 - val_rmse: 0.2118 - val_smape: 0.4475

Epoch 41/64

1147/1147 - 20s - 18ms/step - ia: 0.8706 - loss: 0.0741 - mae: 0.2063 - rmse: 0.2686 - smape: 0.4373 - val_ia: 0.6691 - val_loss: 0.0503 - val_mae: 0.1796 - val_rmse: 0.2066 - val_smape: 0.4366

Epoch 42/64

1147/1147 - 20s - 18ms/step - ia: 0.8715 - loss: 0.0732 - mae: 0.2045 - rmse: 0.2669 - smape: 0.4369 - val_ia: 0.6754 - val_loss: 0.0482 - val_mae: 0.1747 - val_rmse: 0.2017 - val_smape: 0.4244

Epoch 43/64

1147/1147 - 21s - 19ms/step - ia: 0.8729 - loss: 0.0721 - mae: 0.2030 - rmse: 0.2646 - smape: 0.4330 - val_ia: 0.6815 - val_loss: 0.0460 - val_mae: 0.1699 - val_rmse: 0.1969 - val_smape: 0.4127

Epoch 44/64

1147/1147 - 22s - 19ms/step - ia: 0.8747 - loss: 0.0703 - mae: 0.2003 - rmse: 0.2614 - smape: 0.4284 - val_ia: 0.6869 - val_loss: 0.0441 - val_mae: 0.1657 - val_rmse: 0.1926 - val_smape: 0.4020

Epoch 45/64

1147/1147 - 20s - 18ms/step - ia: 0.8741 - loss: 0.0707 - mae: 0.2008 - rmse: 0.2623 - smape: 0.4290 - val_ia: 0.6920 - val_loss: 0.0427 - val_mae: 0.1621 - val_rmse: 0.1891 - val_smape: 0.3926

Epoch 46/64

1147/1147 - 22s - 19ms/step - ia: 0.8762 - loss: 0.0688 - mae: 0.1977 - rmse: 0.2583 - smape: 0.4218 - val_ia: 0.6975 - val_loss: 0.0406 - val_mae: 0.1577 - val_rmse: 0.1847 - val_smape: 0.3820

Epoch 47/64

1147/1147 - 21s - 18ms/step - ia: 0.8759 - loss: 0.0687 - mae: 0.1978 - rmse: 0.2583 - smape: 0.4230 - val_ia: 0.7015 - val_loss: 0.0394 - val_mae: 0.1547 - val_rmse: 0.1816 - val_smape: 0.3746

Epoch 48/64

1147/1147 - 41s - 36ms/step - ia: 0.8785 - loss: 0.0665 - mae: 0.1943 - rmse: 0.2543 - smape: 0.4163 - val_ia: 0.7060 - val_loss: 0.0378 - val_mae: 0.1513 - val_rmse: 0.1780 - val_smape: 0.3659

Epoch 49/64

1147/1147 - 21s - 18ms/step - ia: 0.8789 - loss: 0.0658 - mae: 0.1937 - rmse: 0.2530 - smape: 0.4157 - val_ia: 0.7102 - val_loss: 0.0369 - val_mae: 0.1486 - val_rmse: 0.1753 - val_smape: 0.3581

Epoch 50/64

1147/1147 - 21s - 19ms/step - ia: 0.8782 - loss: 0.0666 - mae: 0.1947 - rmse: 0.2542 - smape: 0.4194 - val_ia: 0.7139 - val_loss: 0.0357 - val_mae: 0.1458 - val_rmse: 0.1724 - val_smape: 0.3515

Epoch 51/64

1147/1147 - 20s - 18ms/step - ia: 0.8797 - loss: 0.0648 - mae: 0.1920 - rmse: 0.2507 - smape: 0.4144 - val_ia: 0.7197 - val_loss: 0.0346 - val_mae: 0.1422 - val_rmse: 0.1690 - val_smape: 0.3404

Epoch 52/64

1147/1147 - 20s - 18ms/step - ia: 0.8801 - loss: 0.0646 - mae: 0.1916 - rmse: 0.2502 - smape: 0.4123 - val_ia: 0.7235 - val_loss: 0.0333 - val_mae: 0.1394 - val_rmse: 0.1661 - val_smape: 0.3338

Epoch 53/64

1147/1147 - 22s - 19ms/step - ia: 0.8812 - loss: 0.0638 - mae: 0.1902 - rmse: 0.2488 - smape: 0.4100 - val_ia: 0.7276 - val_loss: 0.0323 - val_mae: 0.1367 - val_rmse: 0.1634 - val_smape: 0.3261

Epoch 54/64

1147/1147 - 21s - 19ms/step - ia: 0.8821 - loss: 0.0625 - mae: 0.1885 - rmse: 0.2464 - smape: 0.4061 - val_ia: 0.7310 - val_loss: 0.0315 - val_mae: 0.1345 - val_rmse: 0.1612 - val_smape: 0.3201

Epoch 55/64

1147/1147 - 20s - 18ms/step - ia: 0.8823 - loss: 0.0621 - mae: 0.1883 - rmse: 0.2456 - smape: 0.4065 - val_ia: 0.7331 - val_loss: 0.0308 - val_mae: 0.1329 - val_rmse: 0.1594 - val_smape: 0.3173

Epoch 56/64

1147/1147 - 20s - 18ms/step - ia: 0.8837 - loss: 0.0608 - mae: 0.1862 - rmse: 0.2430 - smape: 0.4039 - val_ia: 0.7376 - val_loss: 0.0301 - val_mae: 0.1305 - val_rmse: 0.1570 - val_smape: 0.3094

Epoch 57/64

1147/1147 - 21s - 19ms/step - ia: 0.8846 - loss: 0.0600 - mae: 0.1845 - rmse: 0.2413 - smape: 0.4003 - val_ia: 0.7405 - val_loss: 0.0293 - val_mae: 0.1286 - val_rmse: 0.1550 - val_smape: 0.3047

Epoch 58/64

1147/1147 - 19s - 16ms/step - ia: 0.8841 - loss: 0.0604 - mae: 0.1851 - rmse: 0.2423 - smape: 0.4006 - val_ia: 0.7441 - val_loss: 0.0285 - val_mae: 0.1264 - val_rmse: 0.1528 - val_smape: 0.2987

Epoch 59/64

1147/1147 - 15s - 13ms/step - ia: 0.8846 - loss: 0.0598 - mae: 0.1848 - rmse: 0.2410 - smape: 0.3995 - val_ia: 0.7461 - val_loss: 0.0279 - val_mae: 0.1250 - val_rmse: 0.1512 - val_smape: 0.2957

Epoch 60/64

1147/1147 - 18s - 15ms/step - ia: 0.8852 - loss: 0.0591 - mae: 0.1835 - rmse: 0.2393 - smape: 0.3987 - val_ia: 0.7484 - val_loss: 0.0271 - val_mae: 0.1233 - val_rmse: 0.1493 - val_smape: 0.2924

Epoch 61/64

1147/1147 - 19s - 17ms/step - ia: 0.8862 - loss: 0.0582 - mae: 0.1824 - rmse: 0.2378 - smape: 0.3989 - val_ia: 0.7510 - val_loss: 0.0268 - val_mae: 0.1220 - val_rmse: 0.1480 - val_smape: 0.2878

Epoch 62/64

1147/1147 - 20s - 17ms/step - ia: 0.8861 - loss: 0.0586 - mae: 0.1824 - rmse: 0.2386 - smape: 0.3974 - val_ia: 0.7542 - val_loss: 0.0261 - val_mae: 0.1201 - val_rmse: 0.1461 - val_smape: 0.2822

Epoch 63/64

1147/1147 - 20s - 17ms/step - ia: 0.8859 - loss: 0.0587 - mae: 0.1822 - rmse: 0.2386 - smape: 0.3953 - val_ia: 0.7556 - val_loss: 0.0257 - val_mae: 0.1192 - val_rmse: 0.1450 - val_smape: 0.2809

Epoch 64/64

1147/1147 - 21s - 18ms/step - ia: 0.8867 - loss: 0.0574 - mae: 0.1808 - rmse: 0.2361 - smape: 0.3927 - val_ia: 0.7583 - val_loss: 0.0250 - val_mae: 0.1174 - val_rmse: 0.1431 - val_smape: 0.2761

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:58 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step

 86%|████████▌ | 43/50 [8:27:42<1:27:52, 753.22s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1147/1147 - 59s - 51ms/step - ia: 0.0642 - loss: 1.3762 - mae: 0.9737 - rmse: 1.1675 - smape: 1.8879 - val_ia: 0.2287 - val_loss: 1.0854 - val_mae: 0.8675 - val_rmse: 0.9541 - val_smape: 1.8691

Epoch 2/8

1147/1147 - 14s - 12ms/step - ia: 0.0777 - loss: 1.2215 - mae: 0.9167 - rmse: 1.0997 - smape: 1.8996 - val_ia: 0.2392 - val_loss: 0.9657 - val_mae: 0.8171 - val_rmse: 0.9000 - val_smape: 1.8634

Epoch 3/8

1147/1147 - 14s - 13ms/step - ia: 0.1080 - loss: 1.0787 - mae: 0.8609 - rmse: 1.0336 - smape: 1.8940 - val_ia: 0.2512 - val_loss: 0.8554 - val_mae: 0.7677 - val_rmse: 0.8469 - val_smape: 1.7927

Epoch 4/8

1147/1147 - 15s - 13ms/step - ia: 0.1563 - loss: 0.9468 - mae: 0.8061 - rmse: 0.9681 - smape: 1.7699 - val_ia: 0.2650 - val_loss: 0.7539 - val_mae: 0.7194 - val_rmse: 0.7949 - val_smape: 1.6336

Epoch 5/8

1147/1147 - 15s - 13ms/step - ia: 0.2252 - loss: 0.8253 - mae: 0.7521 - rmse: 0.9041 - smape: 1.5840 - val_ia: 0.2826 - val_loss: 0.6608 - val_mae: 0.6720 - val_rmse: 0.7438 - val_smape: 1.4803

Epoch 6/8

1147/1147 - 14s - 12ms/step - ia: 0.3059 - loss: 0.7136 - mae: 0.6989 - rmse: 0.8401 - smape: 1.4175 - val_ia: 0.3019 - val_loss: 0.5754 - val_mae: 0.6254 - val_rmse: 0.6936 - val_smape: 1.3418

Epoch 7/8

1147/1147 - 22s - 19ms/step - ia: 0.3845 - loss: 0.6114 - mae: 0.6467 - rmse: 0.7776 - smape: 1.2750 - val_ia: 0.3229 - val_loss: 0.4976 - val_mae: 0.5796 - val_rmse: 0.6443 - val_smape: 1.2180

Epoch 8/8

1147/1147 - 15s - 13ms/step - ia: 0.4604 - loss: 0.5184 - mae: 0.5955 - rmse: 0.7161 - smape: 1.1532 - val_ia: 0.3454 - val_loss: 0.4273 - val_mae: 0.5350 - val_rmse: 0.5961 - val_smape: 1.1094

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:14 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 88%|████████▊ | 44/50 [8:30:35<57:55, 579.19s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2293/2293 - 26s - 11ms/step - ia: 0.9121 - loss: 0.0395 - mae: 0.1335 - rmse: 0.1711 - smape: 0.3258 - val_ia: 0.7798 - val_loss: 0.0064 - val_mae: 0.0560 - val_rmse: 0.0704 - val_smape: 0.1682

Epoch 2/32

2293/2293 - 21s - 9ms/step - ia: 0.9493 - loss: 0.0117 - mae: 0.0793 - rmse: 0.1037 - smape: 0.2137 - val_ia: 0.8193 - val_loss: 0.0040 - val_mae: 0.0437 - val_rmse: 0.0561 - val_smape: 0.1359

Epoch 3/32

2293/2293 - 19s - 8ms/step - ia: 0.9550 - loss: 0.0096 - mae: 0.0707 - rmse: 0.0934 - smape: 0.1871 - val_ia: 0.8356 - val_loss: 0.0032 - val_mae: 0.0395 - val_rmse: 0.0509 - val_smape: 0.1210

Epoch 4/32

2293/2293 - 17s - 7ms/step - ia: 0.9578 - loss: 0.0085 - mae: 0.0665 - rmse: 0.0880 - smape: 0.1735 - val_ia: 0.8124 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0543 - val_smape: 0.1249

Epoch 5/32

2293/2293 - 19s - 8ms/step - ia: 0.9593 - loss: 0.0080 - mae: 0.0640 - rmse: 0.0849 - smape: 0.1681 - val_ia: 0.8263 - val_loss: 0.0030 - val_mae: 0.0395 - val_rmse: 0.0501 - val_smape: 0.1310

Epoch 6/32

2293/2293 - 21s - 9ms/step - ia: 0.9597 - loss: 0.0079 - mae: 0.0635 - rmse: 0.0845 - smape: 0.1645 - val_ia: 0.8398 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0471 - val_smape: 0.1177

Epoch 7/32

2293/2293 - 17s - 7ms/step - ia: 0.9604 - loss: 0.0077 - mae: 0.0624 - rmse: 0.0831 - smape: 0.1622 - val_ia: 0.8564 - val_loss: 0.0024 - val_mae: 0.0337 - val_rmse: 0.0443 - val_smape: 0.1093

Epoch 8/32

2293/2293 - 19s - 8ms/step - ia: 0.9602 - loss: 0.0077 - mae: 0.0624 - rmse: 0.0834 - smape: 0.1599 - val_ia: 0.8315 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0491 - val_smape: 0.1266

Epoch 9/32

2293/2293 - 18s - 8ms/step - ia: 0.9608 - loss: 0.0076 - mae: 0.0617 - rmse: 0.0825 - smape: 0.1595 - val_ia: 0.8490 - val_loss: 0.0025 - val_mae: 0.0346 - val_rmse: 0.0451 - val_smape: 0.1182

Epoch 10/32

2293/2293 - 18s - 8ms/step - ia: 0.9607 - loss: 0.0076 - mae: 0.0618 - rmse: 0.0827 - smape: 0.1594 - val_ia: 0.8329 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0489 - val_smape: 0.1169

Epoch 11/32

2293/2293 - 19s - 8ms/step - ia: 0.9610 - loss: 0.0075 - mae: 0.0614 - rmse: 0.0821 - smape: 0.1586 - val_ia: 0.8505 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0453 - val_smape: 0.1124

Epoch 12/32

2293/2293 - 20s - 9ms/step - ia: 0.9609 - loss: 0.0075 - mae: 0.0613 - rmse: 0.0820 - smape: 0.1580 - val_ia: 0.8272 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0504 - val_smape: 0.1331

Epoch 13/32

2293/2293 - 18s - 8ms/step - ia: 0.9612 - loss: 0.0075 - mae: 0.0611 - rmse: 0.0818 - smape: 0.1573 - val_ia: 0.8287 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0498 - val_smape: 0.1210

Epoch 14/32

2293/2293 - 14s - 6ms/step - ia: 0.9612 - loss: 0.0075 - mae: 0.0611 - rmse: 0.0819 - smape: 0.1566 - val_ia: 0.8476 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0465 - val_smape: 0.1160

Epoch 15/32

2293/2293 - 16s - 7ms/step - ia: 0.9613 - loss: 0.0074 - mae: 0.0610 - rmse: 0.0818 - smape: 0.1560 - val_ia: 0.8511 - val_loss: 0.0025 - val_mae: 0.0353 - val_rmse: 0.0457 - val_smape: 0.1102

Epoch 16/32

2293/2293 - 19s - 9ms/step - ia: 0.9618 - loss: 0.0072 - mae: 0.0602 - rmse: 0.0806 - smape: 0.1551 - val_ia: 0.8296 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0493 - val_smape: 0.1250

Epoch 17/32

2293/2293 - 18s - 8ms/step - ia: 0.9617 - loss: 0.0072 - mae: 0.0603 - rmse: 0.0809 - smape: 0.1544 - val_ia: 0.8389 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0482 - val_smape: 0.1157

Epoch 18/32

2293/2293 - 18s - 8ms/step - ia: 0.9614 - loss: 0.0073 - mae: 0.0606 - rmse: 0.0812 - smape: 0.1553 - val_ia: 0.8396 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0473 - val_smape: 0.1216

Epoch 19/32

2293/2293 - 17s - 7ms/step - ia: 0.9618 - loss: 0.0073 - mae: 0.0600 - rmse: 0.0809 - smape: 0.1543 - val_ia: 0.8409 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0466 - val_smape: 0.1175

Epoch 20/32

2293/2293 - 15s - 7ms/step - ia: 0.9616 - loss: 0.0073 - mae: 0.0605 - rmse: 0.0812 - smape: 0.1543 - val_ia: 0.8468 - val_loss: 0.0026 - val_mae: 0.0356 - val_rmse: 0.0460 - val_smape: 0.1186

Epoch 21/32

2293/2293 - 16s - 7ms/step - ia: 0.9617 - loss: 0.0072 - mae: 0.0603 - rmse: 0.0809 - smape: 0.1549 - val_ia: 0.8277 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0500 - val_smape: 0.1203

Epoch 22/32

2293/2293 - 18s - 8ms/step - ia: 0.9618 - loss: 0.0072 - mae: 0.0601 - rmse: 0.0806 - smape: 0.1552 - val_ia: 0.8404 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0473 - val_smape: 0.1246

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:52 1s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 90%|█████████ | 45/50 [8:37:23<43:58, 527.78s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 36s - 31ms/step - ia: 0.9029 - loss: 0.0482 - mae: 0.1509 - rmse: 0.1967 - smape: 0.3669 - val_ia: 0.8354 - val_loss: 0.0112 - val_mae: 0.0740 - val_rmse: 0.0978 - val_smape: 0.2258

Epoch 2/32

1147/1147 - 18s - 16ms/step - ia: 0.9408 - loss: 0.0170 - mae: 0.0952 - rmse: 0.1275 - smape: 0.2490 - val_ia: 0.8546 - val_loss: 0.0083 - val_mae: 0.0629 - val_rmse: 0.0842 - val_smape: 0.1890

Epoch 3/32

1147/1147 - 18s - 15ms/step - ia: 0.9478 - loss: 0.0132 - mae: 0.0838 - rmse: 0.1121 - smape: 0.2234 - val_ia: 0.8711 - val_loss: 0.0063 - val_mae: 0.0546 - val_rmse: 0.0735 - val_smape: 0.1609

Epoch 4/32

1147/1147 - 19s - 16ms/step - ia: 0.9523 - loss: 0.0111 - mae: 0.0768 - rmse: 0.1025 - smape: 0.2095 - val_ia: 0.8894 - val_loss: 0.0048 - val_mae: 0.0479 - val_rmse: 0.0642 - val_smape: 0.1436

Epoch 5/32

1147/1147 - 17s - 15ms/step - ia: 0.9556 - loss: 0.0098 - mae: 0.0717 - rmse: 0.0960 - smape: 0.1976 - val_ia: 0.8916 - val_loss: 0.0043 - val_mae: 0.0449 - val_rmse: 0.0605 - val_smape: 0.1358

Epoch 6/32

1147/1147 - 18s - 16ms/step - ia: 0.9582 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0902 - smape: 0.1877 - val_ia: 0.8904 - val_loss: 0.0042 - val_mae: 0.0463 - val_rmse: 0.0607 - val_smape: 0.1479

Epoch 7/32

1147/1147 - 18s - 16ms/step - ia: 0.9598 - loss: 0.0081 - mae: 0.0651 - rmse: 0.0871 - smape: 0.1803 - val_ia: 0.9020 - val_loss: 0.0035 - val_mae: 0.0409 - val_rmse: 0.0548 - val_smape: 0.1283

Epoch 8/32

1147/1147 - 18s - 16ms/step - ia: 0.9614 - loss: 0.0075 - mae: 0.0624 - rmse: 0.0837 - smape: 0.1738 - val_ia: 0.9065 - val_loss: 0.0033 - val_mae: 0.0394 - val_rmse: 0.0526 - val_smape: 0.1277

Epoch 9/32

1147/1147 - 18s - 16ms/step - ia: 0.9625 - loss: 0.0071 - mae: 0.0606 - rmse: 0.0813 - smape: 0.1693 - val_ia: 0.8987 - val_loss: 0.0035 - val_mae: 0.0431 - val_rmse: 0.0556 - val_smape: 0.1332

Epoch 10/32

1147/1147 - 18s - 16ms/step - ia: 0.9633 - loss: 0.0069 - mae: 0.0594 - rmse: 0.0799 - smape: 0.1668 - val_ia: 0.9115 - val_loss: 0.0028 - val_mae: 0.0364 - val_rmse: 0.0490 - val_smape: 0.1187

Epoch 11/32

1147/1147 - 21s - 18ms/step - ia: 0.9641 - loss: 0.0066 - mae: 0.0580 - rmse: 0.0781 - smape: 0.1633 - val_ia: 0.9087 - val_loss: 0.0029 - val_mae: 0.0376 - val_rmse: 0.0500 - val_smape: 0.1209

Epoch 12/32

1147/1147 - 18s - 16ms/step - ia: 0.9650 - loss: 0.0063 - mae: 0.0565 - rmse: 0.0763 - smape: 0.1612 - val_ia: 0.9136 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0487 - val_smape: 0.1160

Epoch 13/32

1147/1147 - 13s - 12ms/step - ia: 0.9655 - loss: 0.0062 - mae: 0.0559 - rmse: 0.0755 - smape: 0.1590 - val_ia: 0.9085 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0495 - val_smape: 0.1230

Epoch 14/32

1147/1147 - 14s - 12ms/step - ia: 0.9657 - loss: 0.0061 - mae: 0.0555 - rmse: 0.0748 - smape: 0.1573 - val_ia: 0.9192 - val_loss: 0.0025 - val_mae: 0.0338 - val_rmse: 0.0460 - val_smape: 0.1105

Epoch 15/32

1147/1147 - 14s - 13ms/step - ia: 0.9662 - loss: 0.0059 - mae: 0.0547 - rmse: 0.0739 - smape: 0.1541 - val_ia: 0.9042 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0508 - val_smape: 0.1215

Epoch 16/32

1147/1147 - 18s - 16ms/step - ia: 0.9663 - loss: 0.0059 - mae: 0.0545 - rmse: 0.0735 - smape: 0.1546 - val_ia: 0.9171 - val_loss: 0.0025 - val_mae: 0.0349 - val_rmse: 0.0468 - val_smape: 0.1077

Epoch 17/32

1147/1147 - 17s - 15ms/step - ia: 0.9665 - loss: 0.0058 - mae: 0.0541 - rmse: 0.0732 - smape: 0.1539 - val_ia: 0.9207 - val_loss: 0.0024 - val_mae: 0.0334 - val_rmse: 0.0455 - val_smape: 0.1096

Epoch 18/32

1147/1147 - 18s - 16ms/step - ia: 0.9663 - loss: 0.0059 - mae: 0.0544 - rmse: 0.0736 - smape: 0.1539 - val_ia: 0.9197 - val_loss: 0.0024 - val_mae: 0.0335 - val_rmse: 0.0456 - val_smape: 0.1071

Epoch 19/32

1147/1147 - 19s - 16ms/step - ia: 0.9669 - loss: 0.0057 - mae: 0.0534 - rmse: 0.0723 - smape: 0.1528 - val_ia: 0.9179 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0468 - val_smape: 0.1146

Epoch 20/32

1147/1147 - 16s - 14ms/step - ia: 0.9670 - loss: 0.0057 - mae: 0.0534 - rmse: 0.0724 - smape: 0.1524 - val_ia: 0.9113 - val_loss: 0.0027 - val_mae: 0.0375 - val_rmse: 0.0491 - val_smape: 0.1166

Epoch 21/32

1147/1147 - 14s - 12ms/step - ia: 0.9672 - loss: 0.0057 - mae: 0.0531 - rmse: 0.0722 - smape: 0.1513 - val_ia: 0.9146 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0470 - val_smape: 0.1095

Epoch 22/32

1147/1147 - 14s - 12ms/step - ia: 0.9673 - loss: 0.0056 - mae: 0.0528 - rmse: 0.0717 - smape: 0.1501 - val_ia: 0.9187 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0463 - val_smape: 0.1135

Epoch 23/32

1147/1147 - 16s - 14ms/step - ia: 0.9672 - loss: 0.0056 - mae: 0.0529 - rmse: 0.0716 - smape: 0.1497 - val_ia: 0.9089 - val_loss: 0.0028 - val_mae: 0.0382 - val_rmse: 0.0497 - val_smape: 0.1160

Epoch 24/32

1147/1147 - 19s - 16ms/step - ia: 0.9674 - loss: 0.0056 - mae: 0.0527 - rmse: 0.0716 - smape: 0.1505 - val_ia: 0.9197 - val_loss: 0.0024 - val_mae: 0.0340 - val_rmse: 0.0460 - val_smape: 0.1097

Epoch 25/32

1147/1147 - 17s - 15ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0711 - smape: 0.1498 - val_ia: 0.9158 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0466 - val_smape: 0.1069

Epoch 26/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0525 - rmse: 0.0713 - smape: 0.1492 - val_ia: 0.9211 - val_loss: 0.0024 - val_mae: 0.0328 - val_rmse: 0.0451 - val_smape: 0.1086

Epoch 27/32

1147/1147 - 18s - 16ms/step - ia: 0.9676 - loss: 0.0055 - mae: 0.0524 - rmse: 0.0711 - smape: 0.1486 - val_ia: 0.9191 - val_loss: 0.0025 - val_mae: 0.0343 - val_rmse: 0.0461 - val_smape: 0.1136

Epoch 28/32

1147/1147 - 18s - 16ms/step - ia: 0.9675 - loss: 0.0056 - mae: 0.0525 - rmse: 0.0713 - smape: 0.1497 - val_ia: 0.9153 - val_loss: 0.0026 - val_mae: 0.0355 - val_rmse: 0.0476 - val_smape: 0.1144

Epoch 29/32

1147/1147 - 18s - 15ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0523 - rmse: 0.0710 - smape: 0.1493 - val_ia: 0.9186 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0466 - val_smape: 0.1108

Epoch 30/32

1147/1147 - 18s - 15ms/step - ia: 0.9680 - loss: 0.0054 - mae: 0.0517 - rmse: 0.0702 - smape: 0.1479 - val_ia: 0.9121 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0494 - val_smape: 0.1148

Epoch 31/32

1147/1147 - 21s - 18ms/step - ia: 0.9680 - loss: 0.0054 - mae: 0.0518 - rmse: 0.0702 - smape: 0.1485 - val_ia: 0.9206 - val_loss: 0.0024 - val_mae: 0.0334 - val_rmse: 0.0454 - val_smape: 0.1105

Epoch 32/32

1147/1147 - 16s - 14ms/step - ia: 0.9680 - loss: 0.0054 - mae: 0.0517 - rmse: 0.0703 - smape: 0.1470 - val_ia: 0.9226 - val_loss: 0.0023 - val_mae: 0.0324 - val_rmse: 0.0444 - val_smape: 0.1056

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:46 660ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 92%|█████████▏| 46/50 [8:46:59<36:08, 542.23s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1147/1147 - 31s - 27ms/step - ia: 0.6888 - loss: 0.3015 - mae: 0.4283 - rmse: 0.5354 - smape: 0.8554 - val_ia: 0.4738 - val_loss: 0.2205 - val_mae: 0.3692 - val_rmse: 0.4277 - val_smape: 0.7932

Epoch 2/256

1147/1147 - 18s - 16ms/step - ia: 0.7875 - loss: 0.1769 - mae: 0.3251 - rmse: 0.4162 - smape: 0.6581 - val_ia: 0.5077 - val_loss: 0.1814 - val_mae: 0.3311 - val_rmse: 0.3835 - val_smape: 0.6967

Epoch 3/256

1147/1147 - 20s - 17ms/step - ia: 0.8186 - loss: 0.1339 - mae: 0.2810 - rmse: 0.3617 - smape: 0.5788 - val_ia: 0.5442 - val_loss: 0.1463 - val_mae: 0.3019 - val_rmse: 0.3457 - val_smape: 0.6539

Epoch 4/256

1147/1147 - 18s - 16ms/step - ia: 0.8387 - loss: 0.1081 - mae: 0.2520 - rmse: 0.3251 - smape: 0.5254 - val_ia: 0.5826 - val_loss: 0.1016 - val_mae: 0.2566 - val_rmse: 0.2945 - val_smape: 0.5964

Epoch 5/256

1147/1147 - 22s - 20ms/step - ia: 0.8527 - loss: 0.0930 - mae: 0.2322 - rmse: 0.3014 - smape: 0.4859 - val_ia: 0.6226 - val_loss: 0.0702 - val_mae: 0.2144 - val_rmse: 0.2497 - val_smape: 0.5317

Epoch 6/256

1147/1147 - 18s - 16ms/step - ia: 0.8634 - loss: 0.0811 - mae: 0.2155 - rmse: 0.2813 - smape: 0.4560 - val_ia: 0.6560 - val_loss: 0.0523 - val_mae: 0.1839 - val_rmse: 0.2178 - val_smape: 0.4792

Epoch 7/256

1147/1147 - 19s - 16ms/step - ia: 0.8707 - loss: 0.0733 - mae: 0.2044 - rmse: 0.2670 - smape: 0.4331 - val_ia: 0.6779 - val_loss: 0.0439 - val_mae: 0.1669 - val_rmse: 0.2000 - val_smape: 0.4472

Epoch 8/256

1147/1147 - 20s - 17ms/step - ia: 0.8758 - loss: 0.0687 - mae: 0.1965 - rmse: 0.2586 - smape: 0.4159 - val_ia: 0.7058 - val_loss: 0.0359 - val_mae: 0.1477 - val_rmse: 0.1806 - val_smape: 0.4093

Epoch 9/256

1147/1147 - 21s - 18ms/step - ia: 0.8803 - loss: 0.0641 - mae: 0.1895 - rmse: 0.2497 - smape: 0.4027 - val_ia: 0.7137 - val_loss: 0.0331 - val_mae: 0.1415 - val_rmse: 0.1737 - val_smape: 0.3943

Epoch 10/256

1147/1147 - 19s - 17ms/step - ia: 0.8845 - loss: 0.0603 - mae: 0.1835 - rmse: 0.2420 - smape: 0.3930 - val_ia: 0.7371 - val_loss: 0.0285 - val_mae: 0.1282 - val_rmse: 0.1604 - val_smape: 0.3679

Epoch 11/256

1147/1147 - 19s - 17ms/step - ia: 0.8869 - loss: 0.0576 - mae: 0.1791 - rmse: 0.2367 - smape: 0.3836 - val_ia: 0.7414 - val_loss: 0.0267 - val_mae: 0.1241 - val_rmse: 0.1548 - val_smape: 0.3492

Epoch 12/256

1147/1147 - 18s - 15ms/step - ia: 0.8902 - loss: 0.0551 - mae: 0.1744 - rmse: 0.2312 - smape: 0.3740 - val_ia: 0.7481 - val_loss: 0.0251 - val_mae: 0.1204 - val_rmse: 0.1507 - val_smape: 0.3521

Epoch 13/256

1147/1147 - 23s - 20ms/step - ia: 0.8925 - loss: 0.0532 - mae: 0.1710 - rmse: 0.2268 - smape: 0.3681 - val_ia: 0.7563 - val_loss: 0.0238 - val_mae: 0.1163 - val_rmse: 0.1460 - val_smape: 0.3401

Epoch 14/256

1147/1147 - 20s - 18ms/step - ia: 0.8938 - loss: 0.0520 - mae: 0.1687 - rmse: 0.2246 - smape: 0.3608 - val_ia: 0.7667 - val_loss: 0.0222 - val_mae: 0.1115 - val_rmse: 0.1412 - val_smape: 0.3354

Epoch 15/256

1147/1147 - 19s - 17ms/step - ia: 0.8970 - loss: 0.0492 - mae: 0.1639 - rmse: 0.2186 - smape: 0.3532 - val_ia: 0.7638 - val_loss: 0.0222 - val_mae: 0.1124 - val_rmse: 0.1410 - val_smape: 0.3324

Epoch 16/256

1147/1147 - 20s - 18ms/step - ia: 0.8975 - loss: 0.0489 - mae: 0.1631 - rmse: 0.2179 - smape: 0.3479 - val_ia: 0.7686 - val_loss: 0.0211 - val_mae: 0.1091 - val_rmse: 0.1370 - val_smape: 0.3157

Epoch 17/256

1147/1147 - 22s - 19ms/step - ia: 0.8993 - loss: 0.0473 - mae: 0.1602 - rmse: 0.2142 - smape: 0.3461 - val_ia: 0.7703 - val_loss: 0.0206 - val_mae: 0.1084 - val_rmse: 0.1358 - val_smape: 0.3214

Epoch 18/256

1147/1147 - 20s - 18ms/step - ia: 0.9019 - loss: 0.0452 - mae: 0.1564 - rmse: 0.2091 - smape: 0.3383 - val_ia: 0.7796 - val_loss: 0.0191 - val_mae: 0.1032 - val_rmse: 0.1304 - val_smape: 0.3042

Epoch 19/256

1147/1147 - 22s - 19ms/step - ia: 0.9029 - loss: 0.0447 - mae: 0.1549 - rmse: 0.2078 - smape: 0.3342 - val_ia: 0.7730 - val_loss: 0.0201 - val_mae: 0.1075 - val_rmse: 0.1339 - val_smape: 0.3210

Epoch 20/256

1147/1147 - 17s - 15ms/step - ia: 0.9037 - loss: 0.0438 - mae: 0.1539 - rmse: 0.2061 - smape: 0.3305 - val_ia: 0.7784 - val_loss: 0.0189 - val_mae: 0.1038 - val_rmse: 0.1296 - val_smape: 0.3085

Epoch 21/256

1147/1147 - 17s - 15ms/step - ia: 0.9054 - loss: 0.0423 - mae: 0.1512 - rmse: 0.2025 - smape: 0.3275 - val_ia: 0.7821 - val_loss: 0.0183 - val_mae: 0.1019 - val_rmse: 0.1274 - val_smape: 0.2991

Epoch 22/256

1147/1147 - 17s - 15ms/step - ia: 0.9053 - loss: 0.0429 - mae: 0.1512 - rmse: 0.2038 - smape: 0.3232 - val_ia: 0.7726 - val_loss: 0.0194 - val_mae: 0.1067 - val_rmse: 0.1313 - val_smape: 0.3108

Epoch 23/256

1147/1147 - 16s - 14ms/step - ia: 0.9066 - loss: 0.0413 - mae: 0.1491 - rmse: 0.2000 - smape: 0.3210 - val_ia: 0.7854 - val_loss: 0.0173 - val_mae: 0.0995 - val_rmse: 0.1238 - val_smape: 0.2908

Epoch 24/256

1147/1147 - 17s - 15ms/step - ia: 0.9065 - loss: 0.0412 - mae: 0.1492 - rmse: 0.1998 - smape: 0.3222 - val_ia: 0.7906 - val_loss: 0.0167 - val_mae: 0.0976 - val_rmse: 0.1218 - val_smape: 0.2910

Epoch 25/256

1147/1147 - 17s - 15ms/step - ia: 0.9090 - loss: 0.0395 - mae: 0.1456 - rmse: 0.1956 - smape: 0.3144 - val_ia: 0.7987 - val_loss: 0.0156 - val_mae: 0.0940 - val_rmse: 0.1179 - val_smape: 0.2881

Epoch 26/256

1147/1147 - 16s - 14ms/step - ia: 0.9099 - loss: 0.0386 - mae: 0.1442 - rmse: 0.1933 - smape: 0.3126 - val_ia: 0.8039 - val_loss: 0.0146 - val_mae: 0.0905 - val_rmse: 0.1139 - val_smape: 0.2751

Epoch 27/256

1147/1147 - 17s - 15ms/step - ia: 0.9097 - loss: 0.0389 - mae: 0.1442 - rmse: 0.1941 - smape: 0.3105 - val_ia: 0.8027 - val_loss: 0.0145 - val_mae: 0.0909 - val_rmse: 0.1138 - val_smape: 0.2773

Epoch 28/256

1147/1147 - 16s - 14ms/step - ia: 0.9108 - loss: 0.0381 - mae: 0.1429 - rmse: 0.1921 - smape: 0.3075 - val_ia: 0.7980 - val_loss: 0.0152 - val_mae: 0.0939 - val_rmse: 0.1163 - val_smape: 0.2816

Epoch 29/256

1147/1147 - 17s - 15ms/step - ia: 0.9117 - loss: 0.0371 - mae: 0.1412 - rmse: 0.1893 - smape: 0.3067 - val_ia: 0.8047 - val_loss: 0.0141 - val_mae: 0.0898 - val_rmse: 0.1119 - val_smape: 0.2712

Epoch 30/256

1147/1147 - 14s - 12ms/step - ia: 0.9126 - loss: 0.0365 - mae: 0.1397 - rmse: 0.1876 - smape: 0.3006 - val_ia: 0.8098 - val_loss: 0.0134 - val_mae: 0.0874 - val_rmse: 0.1091 - val_smape: 0.2625

Epoch 31/256

1147/1147 - 13s - 11ms/step - ia: 0.9126 - loss: 0.0365 - mae: 0.1399 - rmse: 0.1882 - smape: 0.3038 - val_ia: 0.8082 - val_loss: 0.0134 - val_mae: 0.0879 - val_rmse: 0.1091 - val_smape: 0.2643

Epoch 32/256

1147/1147 - 16s - 14ms/step - ia: 0.9129 - loss: 0.0363 - mae: 0.1394 - rmse: 0.1874 - smape: 0.2978 - val_ia: 0.8103 - val_loss: 0.0131 - val_mae: 0.0869 - val_rmse: 0.1078 - val_smape: 0.2598

Epoch 33/256

1147/1147 - 17s - 14ms/step - ia: 0.9140 - loss: 0.0355 - mae: 0.1377 - rmse: 0.1854 - smape: 0.2968 - val_ia: 0.8169 - val_loss: 0.0122 - val_mae: 0.0839 - val_rmse: 0.1044 - val_smape: 0.2554

Epoch 34/256

1147/1147 - 17s - 15ms/step - ia: 0.9147 - loss: 0.0349 - mae: 0.1367 - rmse: 0.1835 - smape: 0.2977 - val_ia: 0.8153 - val_loss: 0.0124 - val_mae: 0.0847 - val_rmse: 0.1050 - val_smape: 0.2572

Epoch 35/256

1147/1147 - 16s - 14ms/step - ia: 0.9144 - loss: 0.0350 - mae: 0.1370 - rmse: 0.1841 - smape: 0.2941 - val_ia: 0.8144 - val_loss: 0.0124 - val_mae: 0.0848 - val_rmse: 0.1048 - val_smape: 0.2548

Epoch 36/256

1147/1147 - 17s - 15ms/step - ia: 0.9153 - loss: 0.0345 - mae: 0.1356 - rmse: 0.1825 - smape: 0.2915 - val_ia: 0.8253 - val_loss: 0.0111 - val_mae: 0.0795 - val_rmse: 0.0994 - val_smape: 0.2444

Epoch 37/256

1147/1147 - 17s - 15ms/step - ia: 0.9176 - loss: 0.0332 - mae: 0.1324 - rmse: 0.1789 - smape: 0.2870 - val_ia: 0.8239 - val_loss: 0.0112 - val_mae: 0.0801 - val_rmse: 0.0997 - val_smape: 0.2431

Epoch 38/256

1147/1147 - 17s - 15ms/step - ia: 0.9162 - loss: 0.0341 - mae: 0.1343 - rmse: 0.1814 - smape: 0.2887 - val_ia: 0.8212 - val_loss: 0.0113 - val_mae: 0.0814 - val_rmse: 0.1006 - val_smape: 0.2482

Epoch 39/256

1147/1147 - 16s - 14ms/step - ia: 0.9171 - loss: 0.0333 - mae: 0.1329 - rmse: 0.1793 - smape: 0.2852 - val_ia: 0.8267 - val_loss: 0.0108 - val_mae: 0.0786 - val_rmse: 0.0977 - val_smape: 0.2360

Epoch 40/256

1147/1147 - 17s - 15ms/step - ia: 0.9173 - loss: 0.0331 - mae: 0.1327 - rmse: 0.1788 - smape: 0.2837 - val_ia: 0.8347 - val_loss: 0.0099 - val_mae: 0.0751 - val_rmse: 0.0941 - val_smape: 0.2278

Epoch 41/256

1147/1147 - 17s - 15ms/step - ia: 0.9174 - loss: 0.0332 - mae: 0.1326 - rmse: 0.1787 - smape: 0.2841 - val_ia: 0.8341 - val_loss: 0.0100 - val_mae: 0.0755 - val_rmse: 0.0942 - val_smape: 0.2289

Epoch 42/256

1147/1147 - 17s - 14ms/step - ia: 0.9185 - loss: 0.0324 - mae: 0.1308 - rmse: 0.1770 - smape: 0.2810 - val_ia: 0.8344 - val_loss: 0.0098 - val_mae: 0.0750 - val_rmse: 0.0935 - val_smape: 0.2278

Epoch 43/256

1147/1147 - 17s - 15ms/step - ia: 0.9191 - loss: 0.0319 - mae: 0.1299 - rmse: 0.1753 - smape: 0.2789 - val_ia: 0.8380 - val_loss: 0.0096 - val_mae: 0.0733 - val_rmse: 0.0918 - val_smape: 0.2184

Epoch 44/256

1147/1147 - 17s - 15ms/step - ia: 0.9186 - loss: 0.0322 - mae: 0.1304 - rmse: 0.1763 - smape: 0.2804 - val_ia: 0.8264 - val_loss: 0.0104 - val_mae: 0.0780 - val_rmse: 0.0961 - val_smape: 0.2320

Epoch 45/256

1147/1147 - 19s - 17ms/step - ia: 0.9194 - loss: 0.0316 - mae: 0.1292 - rmse: 0.1746 - smape: 0.2766 - val_ia: 0.8377 - val_loss: 0.0094 - val_mae: 0.0743 - val_rmse: 0.0919 - val_smape: 0.2305

Epoch 46/256

1147/1147 - 17s - 15ms/step - ia: 0.9192 - loss: 0.0320 - mae: 0.1297 - rmse: 0.1758 - smape: 0.2746 - val_ia: 0.8353 - val_loss: 0.0096 - val_mae: 0.0743 - val_rmse: 0.0921 - val_smape: 0.2211

Epoch 47/256

1147/1147 - 17s - 15ms/step - ia: 0.9204 - loss: 0.0311 - mae: 0.1279 - rmse: 0.1731 - smape: 0.2748 - val_ia: 0.8421 - val_loss: 0.0089 - val_mae: 0.0708 - val_rmse: 0.0886 - val_smape: 0.2102

Epoch 48/256

1147/1147 - 17s - 15ms/step - ia: 0.9206 - loss: 0.0308 - mae: 0.1275 - rmse: 0.1724 - smape: 0.2748 - val_ia: 0.8337 - val_loss: 0.0096 - val_mae: 0.0740 - val_rmse: 0.0916 - val_smape: 0.2180

Epoch 49/256

1147/1147 - 16s - 14ms/step - ia: 0.9206 - loss: 0.0310 - mae: 0.1275 - rmse: 0.1728 - smape: 0.2718 - val_ia: 0.8274 - val_loss: 0.0100 - val_mae: 0.0767 - val_rmse: 0.0939 - val_smape: 0.2220

Epoch 50/256

1147/1147 - 22s - 19ms/step - ia: 0.9214 - loss: 0.0301 - mae: 0.1260 - rmse: 0.1703 - smape: 0.2713 - val_ia: 0.8408 - val_loss: 0.0088 - val_mae: 0.0711 - val_rmse: 0.0882 - val_smape: 0.2146

Epoch 51/256

1147/1147 - 17s - 15ms/step - ia: 0.9214 - loss: 0.0302 - mae: 0.1262 - rmse: 0.1709 - smape: 0.2707 - val_ia: 0.8505 - val_loss: 0.0082 - val_mae: 0.0674 - val_rmse: 0.0848 - val_smape: 0.2008

Epoch 52/256

1147/1147 - 16s - 14ms/step - ia: 0.9216 - loss: 0.0300 - mae: 0.1256 - rmse: 0.1702 - smape: 0.2683 - val_ia: 0.8447 - val_loss: 0.0086 - val_mae: 0.0695 - val_rmse: 0.0868 - val_smape: 0.2041

Epoch 53/256

1147/1147 - 17s - 15ms/step - ia: 0.9221 - loss: 0.0300 - mae: 0.1250 - rmse: 0.1699 - smape: 0.2677 - val_ia: 0.8436 - val_loss: 0.0086 - val_mae: 0.0709 - val_rmse: 0.0875 - val_smape: 0.2176

Epoch 54/256

1147/1147 - 17s - 15ms/step - ia: 0.9221 - loss: 0.0302 - mae: 0.1252 - rmse: 0.1703 - smape: 0.2673 - val_ia: 0.8491 - val_loss: 0.0080 - val_mae: 0.0677 - val_rmse: 0.0843 - val_smape: 0.2053

Epoch 55/256

1147/1147 - 16s - 14ms/step - ia: 0.9222 - loss: 0.0297 - mae: 0.1247 - rmse: 0.1694 - smape: 0.2677 - val_ia: 0.8438 - val_loss: 0.0085 - val_mae: 0.0691 - val_rmse: 0.0861 - val_smape: 0.1996

Epoch 56/256

1147/1147 - 17s - 15ms/step - ia: 0.9232 - loss: 0.0291 - mae: 0.1234 - rmse: 0.1676 - smape: 0.2655 - val_ia: 0.8506 - val_loss: 0.0079 - val_mae: 0.0666 - val_rmse: 0.0833 - val_smape: 0.1978

Epoch 57/256

1147/1147 - 17s - 15ms/step - ia: 0.9228 - loss: 0.0294 - mae: 0.1240 - rmse: 0.1684 - smape: 0.2657 - val_ia: 0.8553 - val_loss: 0.0075 - val_mae: 0.0649 - val_rmse: 0.0814 - val_smape: 0.1955

Epoch 58/256

1147/1147 - 17s - 15ms/step - ia: 0.9231 - loss: 0.0291 - mae: 0.1234 - rmse: 0.1676 - smape: 0.2648 - val_ia: 0.8599 - val_loss: 0.0072 - val_mae: 0.0636 - val_rmse: 0.0799 - val_smape: 0.1938

Epoch 59/256

1147/1147 - 16s - 14ms/step - ia: 0.9237 - loss: 0.0286 - mae: 0.1226 - rmse: 0.1659 - smape: 0.2636 - val_ia: 0.8607 - val_loss: 0.0071 - val_mae: 0.0626 - val_rmse: 0.0790 - val_smape: 0.1872

Epoch 60/256

1147/1147 - 17s - 15ms/step - ia: 0.9239 - loss: 0.0287 - mae: 0.1222 - rmse: 0.1662 - smape: 0.2590 - val_ia: 0.8571 - val_loss: 0.0074 - val_mae: 0.0639 - val_rmse: 0.0804 - val_smape: 0.1909

Epoch 61/256

1147/1147 - 17s - 15ms/step - ia: 0.9242 - loss: 0.0287 - mae: 0.1218 - rmse: 0.1660 - smape: 0.2606 - val_ia: 0.8511 - val_loss: 0.0077 - val_mae: 0.0665 - val_rmse: 0.0825 - val_smape: 0.2017

Epoch 62/256

1147/1147 - 15s - 13ms/step - ia: 0.9239 - loss: 0.0287 - mae: 0.1222 - rmse: 0.1663 - smape: 0.2613 - val_ia: 0.8603 - val_loss: 0.0069 - val_mae: 0.0620 - val_rmse: 0.0781 - val_smape: 0.1838

Epoch 63/256

1147/1147 - 17s - 15ms/step - ia: 0.9247 - loss: 0.0279 - mae: 0.1208 - rmse: 0.1640 - smape: 0.2589 - val_ia: 0.8622 - val_loss: 0.0069 - val_mae: 0.0616 - val_rmse: 0.0778 - val_smape: 0.1838

Epoch 64/256

1147/1147 - 16s - 14ms/step - ia: 0.9249 - loss: 0.0279 - mae: 0.1205 - rmse: 0.1641 - smape: 0.2575 - val_ia: 0.8694 - val_loss: 0.0064 - val_mae: 0.0591 - val_rmse: 0.0750 - val_smape: 0.1784

Epoch 65/256

1147/1147 - 16s - 14ms/step - ia: 0.9248 - loss: 0.0280 - mae: 0.1210 - rmse: 0.1641 - smape: 0.2606 - val_ia: 0.8661 - val_loss: 0.0066 - val_mae: 0.0600 - val_rmse: 0.0760 - val_smape: 0.1802

Epoch 66/256

1147/1147 - 16s - 14ms/step - ia: 0.9251 - loss: 0.0280 - mae: 0.1204 - rmse: 0.1639 - smape: 0.2566 - val_ia: 0.8673 - val_loss: 0.0065 - val_mae: 0.0598 - val_rmse: 0.0758 - val_smape: 0.1801

Epoch 67/256

1147/1147 - 17s - 15ms/step - ia: 0.9250 - loss: 0.0280 - mae: 0.1206 - rmse: 0.1640 - smape: 0.2578 - val_ia: 0.8709 - val_loss: 0.0063 - val_mae: 0.0575 - val_rmse: 0.0736 - val_smape: 0.1699

Epoch 68/256

1147/1147 - 16s - 14ms/step - ia: 0.9253 - loss: 0.0274 - mae: 0.1200 - rmse: 0.1625 - smape: 0.2587 - val_ia: 0.8612 - val_loss: 0.0069 - val_mae: 0.0614 - val_rmse: 0.0773 - val_smape: 0.1818

Epoch 69/256

1147/1147 - 17s - 15ms/step - ia: 0.9252 - loss: 0.0277 - mae: 0.1200 - rmse: 0.1634 - smape: 0.2575 - val_ia: 0.8599 - val_loss: 0.0070 - val_mae: 0.0620 - val_rmse: 0.0779 - val_smape: 0.1828

Epoch 70/256

1147/1147 - 18s - 16ms/step - ia: 0.9257 - loss: 0.0275 - mae: 0.1194 - rmse: 0.1625 - smape: 0.2556 - val_ia: 0.8653 - val_loss: 0.0064 - val_mae: 0.0591 - val_rmse: 0.0749 - val_smape: 0.1751

Epoch 71/256

1147/1147 - 20s - 17ms/step - ia: 0.9264 - loss: 0.0275 - mae: 0.1186 - rmse: 0.1625 - smape: 0.2520 - val_ia: 0.8596 - val_loss: 0.0069 - val_mae: 0.0616 - val_rmse: 0.0774 - val_smape: 0.1800

Epoch 72/256

1147/1147 - 21s - 18ms/step - ia: 0.9259 - loss: 0.0274 - mae: 0.1190 - rmse: 0.1623 - smape: 0.2524 - val_ia: 0.8688 - val_loss: 0.0062 - val_mae: 0.0584 - val_rmse: 0.0741 - val_smape: 0.1767

Epoch 73/256

1147/1147 - 19s - 16ms/step - ia: 0.9261 - loss: 0.0272 - mae: 0.1190 - rmse: 0.1616 - smape: 0.2535 - val_ia: 0.8673 - val_loss: 0.0064 - val_mae: 0.0584 - val_rmse: 0.0744 - val_smape: 0.1688

Epoch 74/256

1147/1147 - 21s - 18ms/step - ia: 0.9264 - loss: 0.0271 - mae: 0.1183 - rmse: 0.1614 - smape: 0.2520 - val_ia: 0.8739 - val_loss: 0.0060 - val_mae: 0.0562 - val_rmse: 0.0720 - val_smape: 0.1691

Epoch 75/256

1147/1147 - 21s - 18ms/step - ia: 0.9265 - loss: 0.0270 - mae: 0.1183 - rmse: 0.1611 - smape: 0.2509 - val_ia: 0.8654 - val_loss: 0.0065 - val_mae: 0.0591 - val_rmse: 0.0749 - val_smape: 0.1716

Epoch 76/256

1147/1147 - 15s - 13ms/step - ia: 0.9269 - loss: 0.0267 - mae: 0.1175 - rmse: 0.1604 - smape: 0.2493 - val_ia: 0.8658 - val_loss: 0.0064 - val_mae: 0.0591 - val_rmse: 0.0747 - val_smape: 0.1749

Epoch 77/256

1147/1147 - 15s - 13ms/step - ia: 0.9272 - loss: 0.0266 - mae: 0.1172 - rmse: 0.1599 - smape: 0.2486 - val_ia: 0.8633 - val_loss: 0.0064 - val_mae: 0.0595 - val_rmse: 0.0750 - val_smape: 0.1773

Epoch 78/256

1147/1147 - 23s - 20ms/step - ia: 0.9268 - loss: 0.0267 - mae: 0.1174 - rmse: 0.1603 - smape: 0.2502 - val_ia: 0.8721 - val_loss: 0.0060 - val_mae: 0.0568 - val_rmse: 0.0723 - val_smape: 0.1709

Epoch 79/256

1147/1147 - 18s - 16ms/step - ia: 0.9270 - loss: 0.0264 - mae: 0.1172 - rmse: 0.1591 - smape: 0.2499 - val_ia: 0.8714 - val_loss: 0.0061 - val_mae: 0.0575 - val_rmse: 0.0730 - val_smape: 0.1731

Epoch 80/256

1147/1147 - 16s - 14ms/step - ia: 0.9266 - loss: 0.0269 - mae: 0.1177 - rmse: 0.1608 - smape: 0.2498 - val_ia: 0.8706 - val_loss: 0.0061 - val_mae: 0.0576 - val_rmse: 0.0728 - val_smape: 0.1750

Epoch 81/256

1147/1147 - 15s - 13ms/step - ia: 0.9271 - loss: 0.0266 - mae: 0.1172 - rmse: 0.1598 - smape: 0.2482 - val_ia: 0.8755 - val_loss: 0.0058 - val_mae: 0.0551 - val_rmse: 0.0707 - val_smape: 0.1636

Epoch 82/256

1147/1147 - 15s - 13ms/step - ia: 0.9276 - loss: 0.0261 - mae: 0.1161 - rmse: 0.1583 - smape: 0.2487 - val_ia: 0.8770 - val_loss: 0.0056 - val_mae: 0.0558 - val_rmse: 0.0708 - val_smape: 0.1711

Epoch 83/256

1147/1147 - 16s - 14ms/step - ia: 0.9273 - loss: 0.0264 - mae: 0.1167 - rmse: 0.1594 - smape: 0.2485 - val_ia: 0.8690 - val_loss: 0.0061 - val_mae: 0.0571 - val_rmse: 0.0726 - val_smape: 0.1661

Epoch 84/256

1147/1147 - 15s - 13ms/step - ia: 0.9280 - loss: 0.0259 - mae: 0.1158 - rmse: 0.1578 - smape: 0.2481 - val_ia: 0.8766 - val_loss: 0.0057 - val_mae: 0.0547 - val_rmse: 0.0703 - val_smape: 0.1624

Epoch 85/256

1147/1147 - 16s - 14ms/step - ia: 0.9278 - loss: 0.0261 - mae: 0.1161 - rmse: 0.1585 - smape: 0.2481 - val_ia: 0.8744 - val_loss: 0.0058 - val_mae: 0.0560 - val_rmse: 0.0713 - val_smape: 0.1693

Epoch 86/256

1147/1147 - 15s - 13ms/step - ia: 0.9275 - loss: 0.0264 - mae: 0.1167 - rmse: 0.1594 - smape: 0.2475 - val_ia: 0.8804 - val_loss: 0.0054 - val_mae: 0.0530 - val_rmse: 0.0684 - val_smape: 0.1575

Epoch 87/256

1147/1147 - 16s - 14ms/step - ia: 0.9279 - loss: 0.0260 - mae: 0.1160 - rmse: 0.1581 - smape: 0.2472 - val_ia: 0.8825 - val_loss: 0.0054 - val_mae: 0.0526 - val_rmse: 0.0681 - val_smape: 0.1530

Epoch 88/256

1147/1147 - 15s - 13ms/step - ia: 0.9277 - loss: 0.0262 - mae: 0.1162 - rmse: 0.1587 - smape: 0.2471 - val_ia: 0.8807 - val_loss: 0.0055 - val_mae: 0.0533 - val_rmse: 0.0688 - val_smape: 0.1565

Epoch 89/256

1147/1147 - 16s - 14ms/step - ia: 0.9281 - loss: 0.0261 - mae: 0.1158 - rmse: 0.1583 - smape: 0.2454 - val_ia: 0.8820 - val_loss: 0.0054 - val_mae: 0.0526 - val_rmse: 0.0680 - val_smape: 0.1569

Epoch 90/256

1147/1147 - 16s - 14ms/step - ia: 0.9282 - loss: 0.0259 - mae: 0.1154 - rmse: 0.1579 - smape: 0.2457 - val_ia: 0.8754 - val_loss: 0.0056 - val_mae: 0.0541 - val_rmse: 0.0695 - val_smape: 0.1556

Epoch 91/256

1147/1147 - 16s - 14ms/step - ia: 0.9280 - loss: 0.0259 - mae: 0.1158 - rmse: 0.1579 - smape: 0.2454 - val_ia: 0.8749 - val_loss: 0.0059 - val_mae: 0.0554 - val_rmse: 0.0710 - val_smape: 0.1608

Epoch 92/256

1147/1147 - 16s - 14ms/step - ia: 0.9280 - loss: 0.0260 - mae: 0.1158 - rmse: 0.1581 - smape: 0.2458 - val_ia: 0.8725 - val_loss: 0.0059 - val_mae: 0.0559 - val_rmse: 0.0714 - val_smape: 0.1635

Epoch 93/256

1147/1147 - 18s - 16ms/step - ia: 0.9286 - loss: 0.0255 - mae: 0.1147 - rmse: 0.1566 - smape: 0.2431 - val_ia: 0.8808 - val_loss: 0.0053 - val_mae: 0.0536 - val_rmse: 0.0683 - val_smape: 0.1634

Epoch 94/256

1147/1147 - 17s - 14ms/step - ia: 0.9283 - loss: 0.0258 - mae: 0.1153 - rmse: 0.1575 - smape: 0.2444 - val_ia: 0.8723 - val_loss: 0.0058 - val_mae: 0.0563 - val_rmse: 0.0713 - val_smape: 0.1712

Epoch 95/256

1147/1147 - 16s - 14ms/step - ia: 0.9281 - loss: 0.0261 - mae: 0.1153 - rmse: 0.1583 - smape: 0.2447 - val_ia: 0.8693 - val_loss: 0.0061 - val_mae: 0.0570 - val_rmse: 0.0723 - val_smape: 0.1662

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

574/574 - 18s - 31ms/step - ia: 0.1809 - loss: 1.0608 - mae: 0.8523 - rmse: 1.0275 - smape: 1.5110 - val_ia: 0.2714 - val_loss: 0.9612 - val_mae: 0.8156 - val_rmse: 0.9392 - val_smape: 1.5836

Epoch 2/8

574/574 - 7s - 12ms/step - ia: 0.1577 - loss: 1.0350 - mae: 0.8421 - rmse: 1.0147 - smape: 1.5554 - val_ia: 0.2695 - val_loss: 0.9271 - val_mae: 0.8014 - val_rmse: 0.9240 - val_smape: 1.6284

Epoch 3/8

574/574 - 7s - 11ms/step - ia: 0.1400 - loss: 1.0149 - mae: 0.8342 - rmse: 1.0051 - smape: 1.6026 - val_ia: 0.2689 - val_loss: 0.8994 - val_mae: 0.7896 - val_rmse: 0.9114 - val_smape: 1.6789

Epoch 4/8

574/574 - 7s - 12ms/step - ia: 0.1268 - loss: 0.9992 - mae: 0.8281 - rmse: 0.9970 - smape: 1.6578 - val_ia: 0.2698 - val_loss: 0.8772 - val_mae: 0.7799 - val_rmse: 0.9010 - val_smape: 1.7323

Epoch 5/8

574/574 - 7s - 12ms/step - ia: 0.1170 - loss: 0.9868 - mae: 0.8232 - rmse: 0.9907 - smape: 1.7137 - val_ia: 0.2728 - val_loss: 0.8597 - val_mae: 0.7719 - val_rmse: 0.8926 - val_smape: 1.7851

Epoch 6/8

574/574 - 7s - 11ms/step - ia: 0.1115 - loss: 0.9766 - mae: 0.8192 - rmse: 0.9857 - smape: 1.7694 - val_ia: 0.2757 - val_loss: 0.8451 - val_mae: 0.7650 - val_rmse: 0.8855 - val_smape: 1.8386

Epoch 7/8

574/574 - 6s - 10ms/step - ia: 0.1151 - loss: 0.9677 - mae: 0.8158 - rmse: 0.9814 - smape: 1.8261 - val_ia: 0.2783 - val_loss: 0.8332 - val_mae: 0.7593 - val_rmse: 0.8795 - val_smape: 1.8775

Epoch 8/8

574/574 - 6s - 10ms/step - ia: 0.1153 - loss: 0.9596 - mae: 0.8125 - rmse: 0.9776 - smape: 1.8628 - val_ia: 0.2807 - val_loss: 0.8230 - val_mae: 0.7543 - val_rmse: 0.8742 - val_smape: 1.8726

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:53 699ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/32

 96%|█████████▌| 48/50 [9:39:12<30:59, 929.64s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4586/4586 - 37s - 8ms/step - ia: 0.1704 - loss: 1.3921 - mae: 0.9661 - rmse: 1.1461 - smape: 1.7506 - val_ia: 0.1515 - val_loss: 0.6635 - val_mae: 0.6749 - val_rmse: 0.6922 - val_smape: 1.4826

Epoch 2/32

4586/4586 - 28s - 6ms/step - ia: 0.5153 - loss: 0.4772 - mae: 0.5537 - rmse: 0.6637 - smape: 1.0749 - val_ia: 0.2406 - val_loss: 0.2203 - val_mae: 0.3683 - val_rmse: 0.3854 - val_smape: 0.7811

Epoch 3/32

4586/4586 - 42s - 9ms/step - ia: 0.7464 - loss: 0.1891 - mae: 0.3450 - rmse: 0.4203 - smape: 0.7026 - val_ia: 0.2566 - val_loss: 0.1484 - val_mae: 0.3080 - val_rmse: 0.3244 - val_smape: 0.6808

Epoch 4/32

4586/4586 - 27s - 6ms/step - ia: 0.7982 - loss: 0.1351 - mae: 0.2874 - rmse: 0.3545 - smape: 0.6141 - val_ia: 0.2751 - val_loss: 0.1243 - val_mae: 0.2845 - val_rmse: 0.2995 - val_smape: 0.6408

Epoch 5/32

4586/4586 - 27s - 6ms/step - ia: 0.8231 - loss: 0.1087 - mae: 0.2545 - rmse: 0.3168 - smape: 0.5571 - val_ia: 0.2954 - val_loss: 0.1025 - val_mae: 0.2579 - val_rmse: 0.2717 - val_smape: 0.6008

Epoch 6/32

4586/4586 - 27s - 6ms/step - ia: 0.8424 - loss: 0.0876 - mae: 0.2266 - rmse: 0.2835 - smape: 0.5049 - val_ia: 0.3143 - val_loss: 0.0851 - val_mae: 0.2336 - val_rmse: 0.2463 - val_smape: 0.5671

Epoch 7/32

4586/4586 - 28s - 6ms/step - ia: 0.8594 - loss: 0.0713 - mae: 0.2031 - rmse: 0.2546 - smape: 0.4630 - val_ia: 0.3364 - val_loss: 0.0713 - val_mae: 0.2122 - val_rmse: 0.2240 - val_smape: 0.5345

Epoch 8/32

4586/4586 - 27s - 6ms/step - ia: 0.8713 - loss: 0.0602 - mae: 0.1854 - rmse: 0.2338 - smape: 0.4255 - val_ia: 0.3606 - val_loss: 0.0603 - val_mae: 0.1936 - val_rmse: 0.2049 - val_smape: 0.5021

Epoch 9/32

4586/4586 - 27s - 6ms/step - ia: 0.8827 - loss: 0.0516 - mae: 0.1705 - rmse: 0.2156 - smape: 0.3952 - val_ia: 0.3837 - val_loss: 0.0512 - val_mae: 0.1777 - val_rmse: 0.1888 - val_smape: 0.4735

Epoch 10/32

4586/4586 - 29s - 6ms/step - ia: 0.8909 - loss: 0.0448 - mae: 0.1583 - rmse: 0.2009 - smape: 0.3689 - val_ia: 0.4040 - val_loss: 0.0434 - val_mae: 0.1636 - val_rmse: 0.1746 - val_smape: 0.4478

Epoch 11/32

4586/4586 - 27s - 6ms/step - ia: 0.8977 - loss: 0.0396 - mae: 0.1487 - rmse: 0.1885 - smape: 0.3522 - val_ia: 0.4222 - val_loss: 0.0358 - val_mae: 0.1492 - val_rmse: 0.1602 - val_smape: 0.4201

Epoch 12/32

4586/4586 - 28s - 6ms/step - ia: 0.9025 - loss: 0.0366 - mae: 0.1429 - rmse: 0.1811 - smape: 0.3377 - val_ia: 0.4358 - val_loss: 0.0304 - val_mae: 0.1381 - val_rmse: 0.1491 - val_smape: 0.3969

Epoch 13/32

4586/4586 - 27s - 6ms/step - ia: 0.9064 - loss: 0.0334 - mae: 0.1362 - rmse: 0.1728 - smape: 0.3246 - val_ia: 0.4493 - val_loss: 0.0257 - val_mae: 0.1272 - val_rmse: 0.1382 - val_smape: 0.3740

Epoch 14/32

4586/4586 - 27s - 6ms/step - ia: 0.9107 - loss: 0.0305 - mae: 0.1303 - rmse: 0.1651 - smape: 0.3119 - val_ia: 0.4630 - val_loss: 0.0218 - val_mae: 0.1169 - val_rmse: 0.1280 - val_smape: 0.3492

Epoch 15/32

4586/4586 - 28s - 6ms/step - ia: 0.9130 - loss: 0.0290 - mae: 0.1267 - rmse: 0.1606 - smape: 0.3048 - val_ia: 0.4760 - val_loss: 0.0189 - val_mae: 0.1083 - val_rmse: 0.1195 - val_smape: 0.3281

Epoch 16/32

4586/4586 - 27s - 6ms/step - ia: 0.9162 - loss: 0.0274 - mae: 0.1225 - rmse: 0.1560 - smape: 0.2975 - val_ia: 0.4922 - val_loss: 0.0164 - val_mae: 0.0999 - val_rmse: 0.1112 - val_smape: 0.3054

Epoch 17/32

4586/4586 - 27s - 6ms/step - ia: 0.9174 - loss: 0.0260 - mae: 0.1202 - rmse: 0.1524 - smape: 0.2928 - val_ia: 0.5035 - val_loss: 0.0148 - val_mae: 0.0945 - val_rmse: 0.1058 - val_smape: 0.2910

Epoch 18/32

4586/4586 - 27s - 6ms/step - ia: 0.9199 - loss: 0.0248 - mae: 0.1172 - rmse: 0.1488 - smape: 0.2877 - val_ia: 0.5176 - val_loss: 0.0134 - val_mae: 0.0889 - val_rmse: 0.1003 - val_smape: 0.2763

Epoch 19/32

4586/4586 - 27s - 6ms/step - ia: 0.9205 - loss: 0.0243 - mae: 0.1160 - rmse: 0.1471 - smape: 0.2856 - val_ia: 0.5267 - val_loss: 0.0126 - val_mae: 0.0856 - val_rmse: 0.0969 - val_smape: 0.2663

Epoch 20/32

4586/4586 - 26s - 6ms/step - ia: 0.9229 - loss: 0.0229 - mae: 0.1124 - rmse: 0.1429 - smape: 0.2783 - val_ia: 0.5429 - val_loss: 0.0114 - val_mae: 0.0801 - val_rmse: 0.0915 - val_smape: 0.2519

Epoch 21/32

4586/4586 - 28s - 6ms/step - ia: 0.9239 - loss: 0.0225 - mae: 0.1116 - rmse: 0.1415 - smape: 0.2786 - val_ia: 0.5471 - val_loss: 0.0109 - val_mae: 0.0786 - val_rmse: 0.0899 - val_smape: 0.2485

Epoch 22/32

4586/4586 - 28s - 6ms/step - ia: 0.9252 - loss: 0.0216 - mae: 0.1094 - rmse: 0.1386 - smape: 0.2735 - val_ia: 0.5537 - val_loss: 0.0105 - val_mae: 0.0764 - val_rmse: 0.0877 - val_smape: 0.2405

Epoch 23/32

4586/4586 - 39s - 9ms/step - ia: 0.9259 - loss: 0.0212 - mae: 0.1080 - rmse: 0.1371 - smape: 0.2708 - val_ia: 0.5615 - val_loss: 0.0099 - val_mae: 0.0737 - val_rmse: 0.0849 - val_smape: 0.2330

Epoch 24/32

4586/4586 - 27s - 6ms/step - ia: 0.9279 - loss: 0.0201 - mae: 0.1055 - rmse: 0.1337 - smape: 0.2672 - val_ia: 0.5724 - val_loss: 0.0092 - val_mae: 0.0705 - val_rmse: 0.0818 - val_smape: 0.2255

Epoch 25/32

4586/4586 - 28s - 6ms/step - ia: 0.9285 - loss: 0.0198 - mae: 0.1045 - rmse: 0.1327 - smape: 0.2651 - val_ia: 0.5744 - val_loss: 0.0090 - val_mae: 0.0698 - val_rmse: 0.0810 - val_smape: 0.2226

Epoch 26/32

4586/4586 - 28s - 6ms/step - ia: 0.9287 - loss: 0.0194 - mae: 0.1039 - rmse: 0.1316 - smape: 0.2642 - val_ia: 0.5755 - val_loss: 0.0089 - val_mae: 0.0694 - val_rmse: 0.0805 - val_smape: 0.2214

Epoch 27/32

4586/4586 - 27s - 6ms/step - ia: 0.9299 - loss: 0.0189 - mae: 0.1022 - rmse: 0.1297 - smape: 0.2602 - val_ia: 0.5829 - val_loss: 0.0085 - val_mae: 0.0672 - val_rmse: 0.0783 - val_smape: 0.2145

Epoch 28/32

4586/4586 - 28s - 6ms/step - ia: 0.9313 - loss: 0.0183 - mae: 0.1005 - rmse: 0.1277 - smape: 0.2558 - val_ia: 0.5893 - val_loss: 0.0081 - val_mae: 0.0654 - val_rmse: 0.0765 - val_smape: 0.2102

Epoch 29/32

4586/4586 - 27s - 6ms/step - ia: 0.9322 - loss: 0.0179 - mae: 0.0992 - rmse: 0.1258 - smape: 0.2554 - val_ia: 0.5906 - val_loss: 0.0080 - val_mae: 0.0649 - val_rmse: 0.0760 - val_smape: 0.2064

Epoch 30/32

4586/4586 - 28s - 6ms/step - ia: 0.9322 - loss: 0.0179 - mae: 0.0988 - rmse: 0.1256 - smape: 0.2538 - val_ia: 0.5946 - val_loss: 0.0077 - val_mae: 0.0638 - val_rmse: 0.0748 - val_smape: 0.2050

Epoch 31/32

4586/4586 - 27s - 6ms/step - ia: 0.9333 - loss: 0.0173 - mae: 0.0975 - rmse: 0.1240 - smape: 0.2529 - val_ia: 0.5960 - val_loss: 0.0077 - val_mae: 0.0634 - val_rmse: 0.0744 - val_smape: 0.2034

Epoch 32/32

4586/4586 - 27s - 6ms/step - ia: 0.9343 - loss: 0.0169 - mae: 0.0960 - rmse: 0.1221 - smape: 0.2500 - val_ia: 0.6005 - val_loss: 0.0074 - val_mae: 0.0621 - val_rmse: 0.0731 - val_smape: 0.1981

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:13 452ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/64

 98%|█████████▊| 49/50 [9:54:25<15:24, 924.59s/trial, best loss: 0.0016658599381961904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 11s - 39ms/step - ia: 0.6848 - loss: 0.2977 - mae: 0.4152 - rmse: 0.5192 - smape: 0.8309 - val_ia: 0.7746 - val_loss: 0.1665 - val_mae: 0.3227 - val_rmse: 0.3904 - val_smape: 0.6698

Epoch 2/64

287/287 - 4s - 15ms/step - ia: 0.8544 - loss: 0.0946 - mae: 0.2346 - rmse: 0.3059 - smape: 0.5202 - val_ia: 0.8061 - val_loss: 0.1220 - val_mae: 0.2754 - val_rmse: 0.3298 - val_smape: 0.6066

Epoch 3/64

287/287 - 4s - 13ms/step - ia: 0.8767 - loss: 0.0689 - mae: 0.1999 - rmse: 0.2614 - smape: 0.4581 - val_ia: 0.8377 - val_loss: 0.0816 - val_mae: 0.2265 - val_rmse: 0.2716 - val_smape: 0.5474

Epoch 4/64

287/287 - 4s - 12ms/step - ia: 0.8918 - loss: 0.0535 - mae: 0.1763 - rmse: 0.2306 - smape: 0.4150 - val_ia: 0.8689 - val_loss: 0.0512 - val_mae: 0.1808 - val_rmse: 0.2191 - val_smape: 0.4811

Epoch 5/64

287/287 - 4s - 12ms/step - ia: 0.9044 - loss: 0.0424 - mae: 0.1563 - rmse: 0.2050 - smape: 0.3768 - val_ia: 0.9006 - val_loss: 0.0295 - val_mae: 0.1351 - val_rmse: 0.1687 - val_smape: 0.3926

Epoch 6/64

287/287 - 4s - 13ms/step - ia: 0.9142 - loss: 0.0348 - mae: 0.1406 - rmse: 0.1856 - smape: 0.3458 - val_ia: 0.9228 - val_loss: 0.0193 - val_mae: 0.1050 - val_rmse: 0.1368 - val_smape: 0.3232

Epoch 7/64

287/287 - 3s - 12ms/step - ia: 0.9204 - loss: 0.0299 - mae: 0.1304 - rmse: 0.1719 - smape: 0.3252 - val_ia: 0.9354 - val_loss: 0.0144 - val_mae: 0.0880 - val_rmse: 0.1183 - val_smape: 0.2788

Epoch 8/64

287/287 - 3s - 11ms/step - ia: 0.9259 - loss: 0.0262 - mae: 0.1213 - rmse: 0.1609 - smape: 0.3059 - val_ia: 0.9405 - val_loss: 0.0125 - val_mae: 0.0804 - val_rmse: 0.1099 - val_smape: 0.2498

Epoch 9/64

287/287 - 3s - 10ms/step - ia: 0.9300 - loss: 0.0235 - mae: 0.1147 - rmse: 0.1525 - smape: 0.2912 - val_ia: 0.9465 - val_loss: 0.0107 - val_mae: 0.0721 - val_rmse: 0.1019 - val_smape: 0.2187

Epoch 10/64

287/287 - 3s - 10ms/step - ia: 0.9333 - loss: 0.0216 - mae: 0.1094 - rmse: 0.1461 - smape: 0.2800 - val_ia: 0.9499 - val_loss: 0.0096 - val_mae: 0.0678 - val_rmse: 0.0965 - val_smape: 0.2090

Epoch 11/64

287/287 - 3s - 9ms/step - ia: 0.9361 - loss: 0.0198 - mae: 0.1047 - rmse: 0.1400 - smape: 0.2729 - val_ia: 0.9508 - val_loss: 0.0091 - val_mae: 0.0667 - val_rmse: 0.0940 - val_smape: 0.2089

Epoch 12/64

287/287 - 3s - 10ms/step - ia: 0.9382 - loss: 0.0187 - mae: 0.1014 - rmse: 0.1359 - smape: 0.2634 - val_ia: 0.9518 - val_loss: 0.0088 - val_mae: 0.0651 - val_rmse: 0.0922 - val_smape: 0.1976

Epoch 13/64

287/287 - 3s - 9ms/step - ia: 0.9403 - loss: 0.0176 - mae: 0.0978 - rmse: 0.1317 - smape: 0.2556 - val_ia: 0.9533 - val_loss: 0.0082 - val_mae: 0.0632 - val_rmse: 0.0891 - val_smape: 0.1954

Epoch 14/64

287/287 - 3s - 10ms/step - ia: 0.9423 - loss: 0.0164 - mae: 0.0946 - rmse: 0.1271 - smape: 0.2496 - val_ia: 0.9545 - val_loss: 0.0078 - val_mae: 0.0616 - val_rmse: 0.0868 - val_smape: 0.1895

Epoch 15/64

287/287 - 3s - 9ms/step - ia: 0.9440 - loss: 0.0155 - mae: 0.0919 - rmse: 0.1233 - smape: 0.2450 - val_ia: 0.9557 - val_loss: 0.0074 - val_mae: 0.0599 - val_rmse: 0.0846 - val_smape: 0.1824

Epoch 16/64

287/287 - 3s - 11ms/step - ia: 0.9455 - loss: 0.0147 - mae: 0.0895 - rmse: 0.1204 - smape: 0.2383 - val_ia: 0.9555 - val_loss: 0.0073 - val_mae: 0.0601 - val_rmse: 0.0837 - val_smape: 0.1859

Epoch 17/64

287/287 - 6s - 20ms/step - ia: 0.9467 - loss: 0.0142 - mae: 0.0876 - rmse: 0.1182 - smape: 0.2349 - val_ia: 0.9577 - val_loss: 0.0067 - val_mae: 0.0573 - val_rmse: 0.0803 - val_smape: 0.1787

Epoch 18/64

287/287 - 4s - 13ms/step - ia: 0.9478 - loss: 0.0135 - mae: 0.0857 - rmse: 0.1154 - smape: 0.2296 - val_ia: 0.9585 - val_loss: 0.0064 - val_mae: 0.0562 - val_rmse: 0.0787 - val_smape: 0.1740

Epoch 19/64

287/287 - 3s - 10ms/step - ia: 0.9490 - loss: 0.0130 - mae: 0.0837 - rmse: 0.1130 - smape: 0.2264 - val_ia: 0.9593 - val_loss: 0.0062 - val_mae: 0.0552 - val_rmse: 0.0769 - val_smape: 0.1720

Epoch 20/64

287/287 - 3s - 12ms/step - ia: 0.9497 - loss: 0.0126 - mae: 0.0826 - rmse: 0.1114 - smape: 0.2238 - val_ia: 0.9616 - val_loss: 0.0056 - val_mae: 0.0521 - val_rmse: 0.0736 - val_smape: 0.1622

Epoch 21/64

287/287 - 6s - 19ms/step - ia: 0.9507 - loss: 0.0122 - mae: 0.0810 - rmse: 0.1094 - smape: 0.2185 - val_ia: 0.9617 - val_loss: 0.0055 - val_mae: 0.0519 - val_rmse: 0.0729 - val_smape: 0.1606

Epoch 22/64

287/287 - 4s - 13ms/step - ia: 0.9515 - loss: 0.0118 - mae: 0.0795 - rmse: 0.1075 - smape: 0.2167 - val_ia: 0.9619 - val_loss: 0.0054 - val_mae: 0.0518 - val_rmse: 0.0720 - val_smape: 0.1631

Epoch 23/64

287/287 - 3s - 11ms/step - ia: 0.9521 - loss: 0.0116 - mae: 0.0786 - rmse: 0.1067 - smape: 0.2133 - val_ia: 0.9629 - val_loss: 0.0052 - val_mae: 0.0503 - val_rmse: 0.0704 - val_smape: 0.1560

Epoch 24/64

287/287 - 4s - 13ms/step - ia: 0.9527 - loss: 0.0113 - mae: 0.0777 - rmse: 0.1055 - smape: 0.2100 - val_ia: 0.9645 - val_loss: 0.0048 - val_mae: 0.0481 - val_rmse: 0.0682 - val_smape: 0.1475

Epoch 25/64

287/287 - 4s - 13ms/step - ia: 0.9534 - loss: 0.0110 - mae: 0.0765 - rmse: 0.1035 - smape: 0.2061 - val_ia: 0.9640 - val_loss: 0.0048 - val_mae: 0.0488 - val_rmse: 0.0681 - val_smape: 0.1513

Epoch 26/64

287/287 - 4s - 13ms/step - ia: 0.9544 - loss: 0.0106 - mae: 0.0749 - rmse: 0.1017 - smape: 0.2034 - val_ia: 0.9649 - val_loss: 0.0046 - val_mae: 0.0477 - val_rmse: 0.0667 - val_smape: 0.1502

Epoch 27/64

287/287 - 3s - 12ms/step - ia: 0.9549 - loss: 0.0104 - mae: 0.0741 - rmse: 0.1010 - smape: 0.2017 - val_ia: 0.9646 - val_loss: 0.0046 - val_mae: 0.0478 - val_rmse: 0.0666 - val_smape: 0.1474

Epoch 28/64

287/287 - 3s - 9ms/step - ia: 0.9555 - loss: 0.0101 - mae: 0.0732 - rmse: 0.0995 - smape: 0.1976 - val_ia: 0.9651 - val_loss: 0.0045 - val_mae: 0.0472 - val_rmse: 0.0655 - val_smape: 0.1475

Epoch 29/64

287/287 - 3s - 9ms/step - ia: 0.9559 - loss: 0.0100 - mae: 0.0725 - rmse: 0.0986 - smape: 0.1958 - val_ia: 0.9673 - val_loss: 0.0041 - val_mae: 0.0445 - val_rmse: 0.0629 - val_smape: 0.1390

Epoch 30/64

287/287 - 4s - 12ms/step - ia: 0.9561 - loss: 0.0099 - mae: 0.0723 - rmse: 0.0982 - smape: 0.1949 - val_ia: 0.9668 - val_loss: 0.0042 - val_mae: 0.0449 - val_rmse: 0.0632 - val_smape: 0.1374

Epoch 31/64

287/287 - 4s - 14ms/step - ia: 0.9566 - loss: 0.0097 - mae: 0.0714 - rmse: 0.0973 - smape: 0.1928 - val_ia: 0.9658 - val_loss: 0.0043 - val_mae: 0.0463 - val_rmse: 0.0640 - val_smape: 0.1423

Epoch 32/64

287/287 - 4s - 14ms/step - ia: 0.9571 - loss: 0.0094 - mae: 0.0705 - rmse: 0.0958 - smape: 0.1907 - val_ia: 0.9677 - val_loss: 0.0040 - val_mae: 0.0438 - val_rmse: 0.0614 - val_smape: 0.1379

Epoch 33/64

287/287 - 4s - 14ms/step - ia: 0.9573 - loss: 0.0094 - mae: 0.0702 - rmse: 0.0961 - smape: 0.1886 - val_ia: 0.9681 - val_loss: 0.0039 - val_mae: 0.0432 - val_rmse: 0.0607 - val_smape: 0.1360

Epoch 34/64

287/287 - 4s - 14ms/step - ia: 0.9575 - loss: 0.0094 - mae: 0.0699 - rmse: 0.0958 - smape: 0.1884 - val_ia: 0.9683 - val_loss: 0.0038 - val_mae: 0.0429 - val_rmse: 0.0601 - val_smape: 0.1362

Epoch 35/64

287/287 - 4s - 14ms/step - ia: 0.9579 - loss: 0.0091 - mae: 0.0692 - rmse: 0.0943 - smape: 0.1857 - val_ia: 0.9685 - val_loss: 0.0038 - val_mae: 0.0427 - val_rmse: 0.0598 - val_smape: 0.1326

Epoch 36/64

287/287 - 4s - 12ms/step - ia: 0.9579 - loss: 0.0092 - mae: 0.0692 - rmse: 0.0946 - smape: 0.1852 - val_ia: 0.9708 - val_loss: 0.0034 - val_mae: 0.0397 - val_rmse: 0.0569 - val_smape: 0.1273

Epoch 37/64

287/287 - 4s - 12ms/step - ia: 0.9586 - loss: 0.0089 - mae: 0.0681 - rmse: 0.0930 - smape: 0.1821 - val_ia: 0.9698 - val_loss: 0.0035 - val_mae: 0.0410 - val_rmse: 0.0580 - val_smape: 0.1297

Epoch 38/64

287/287 - 4s - 13ms/step - ia: 0.9585 - loss: 0.0089 - mae: 0.0682 - rmse: 0.0933 - smape: 0.1836 - val_ia: 0.9701 - val_loss: 0.0034 - val_mae: 0.0405 - val_rmse: 0.0573 - val_smape: 0.1298

Epoch 39/64

287/287 - 4s - 14ms/step - ia: 0.9592 - loss: 0.0087 - mae: 0.0671 - rmse: 0.0922 - smape: 0.1792 - val_ia: 0.9698 - val_loss: 0.0035 - val_mae: 0.0409 - val_rmse: 0.0574 - val_smape: 0.1311

Epoch 40/64

287/287 - 4s - 13ms/step - ia: 0.9591 - loss: 0.0087 - mae: 0.0672 - rmse: 0.0921 - smape: 0.1795 - val_ia: 0.9719 - val_loss: 0.0032 - val_mae: 0.0383 - val_rmse: 0.0551 - val_smape: 0.1235

Epoch 41/64

287/287 - 4s - 12ms/step - ia: 0.9595 - loss: 0.0086 - mae: 0.0667 - rmse: 0.0916 - smape: 0.1786 - val_ia: 0.9700 - val_loss: 0.0034 - val_mae: 0.0406 - val_rmse: 0.0568 - val_smape: 0.1297

Epoch 42/64

287/287 - 4s - 13ms/step - ia: 0.9597 - loss: 0.0085 - mae: 0.0662 - rmse: 0.0907 - smape: 0.1783 - val_ia: 0.9705 - val_loss: 0.0033 - val_mae: 0.0399 - val_rmse: 0.0561 - val_smape: 0.1272

Epoch 43/64

287/287 - 4s - 13ms/step - ia: 0.9600 - loss: 0.0084 - mae: 0.0659 - rmse: 0.0904 - smape: 0.1769 - val_ia: 0.9715 - val_loss: 0.0032 - val_mae: 0.0387 - val_rmse: 0.0549 - val_smape: 0.1246

Epoch 44/64

287/287 - 4s - 13ms/step - ia: 0.9600 - loss: 0.0084 - mae: 0.0658 - rmse: 0.0905 - smape: 0.1760 - val_ia: 0.9700 - val_loss: 0.0033 - val_mae: 0.0405 - val_rmse: 0.0563 - val_smape: 0.1305

Epoch 45/64

287/287 - 3s - 12ms/step - ia: 0.9599 - loss: 0.0084 - mae: 0.0660 - rmse: 0.0906 - smape: 0.1745 - val_ia: 0.9718 - val_loss: 0.0031 - val_mae: 0.0383 - val_rmse: 0.0543 - val_smape: 0.1240

Epoch 46/64

287/287 - 4s - 13ms/step - ia: 0.9604 - loss: 0.0083 - mae: 0.0651 - rmse: 0.0898 - smape: 0.1727 - val_ia: 0.9714 - val_loss: 0.0031 - val_mae: 0.0387 - val_rmse: 0.0545 - val_smape: 0.1248

Epoch 47/64

287/287 - 3s - 12ms/step - ia: 0.9606 - loss: 0.0082 - mae: 0.0649 - rmse: 0.0892 - smape: 0.1740 - val_ia: 0.9710 - val_loss: 0.0032 - val_mae: 0.0393 - val_rmse: 0.0549 - val_smape: 0.1259

Epoch 48/64

287/287 - 4s - 13ms/step - ia: 0.9610 - loss: 0.0080 - mae: 0.0642 - rmse: 0.0882 - smape: 0.1715 - val_ia: 0.9726 - val_loss: 0.0030 - val_mae: 0.0372 - val_rmse: 0.0531 - val_smape: 0.1214

Epoch 49/64

287/287 - 3s - 11ms/step - ia: 0.9605 - loss: 0.0082 - mae: 0.0649 - rmse: 0.0894 - smape: 0.1723 - val_ia: 0.9728 - val_loss: 0.0029 - val_mae: 0.0369 - val_rmse: 0.0525 - val_smape: 0.1227

Epoch 50/64

287/287 - 4s - 13ms/step - ia: 0.9610 - loss: 0.0080 - mae: 0.0640 - rmse: 0.0881 - smape: 0.1715 - val_ia: 0.9726 - val_loss: 0.0029 - val_mae: 0.0371 - val_rmse: 0.0526 - val_smape: 0.1219

Epoch 51/64

287/287 - 4s - 13ms/step - ia: 0.9609 - loss: 0.0081 - mae: 0.0643 - rmse: 0.0885 - smape: 0.1707 - val_ia: 0.9729 - val_loss: 0.0029 - val_mae: 0.0368 - val_rmse: 0.0523 - val_smape: 0.1202

Epoch 52/64

287/287 - 4s - 13ms/step - ia: 0.9614 - loss: 0.0079 - mae: 0.0635 - rmse: 0.0874 - smape: 0.1687 - val_ia: 0.9726 - val_loss: 0.0029 - val_mae: 0.0371 - val_rmse: 0.0525 - val_smape: 0.1227

Epoch 53/64

287/287 - 4s - 12ms/step - ia: 0.9614 - loss: 0.0078 - mae: 0.0634 - rmse: 0.0873 - smape: 0.1678 - val_ia: 0.9718 - val_loss: 0.0030 - val_mae: 0.0381 - val_rmse: 0.0534 - val_smape: 0.1230

Epoch 54/64

287/287 - 4s - 13ms/step - ia: 0.9614 - loss: 0.0079 - mae: 0.0636 - rmse: 0.0878 - smape: 0.1690 - val_ia: 0.9730 - val_loss: 0.0028 - val_mae: 0.0367 - val_rmse: 0.0519 - val_smape: 0.1211

Epoch 55/64

287/287 - 4s - 13ms/step - ia: 0.9613 - loss: 0.0079 - mae: 0.0636 - rmse: 0.0880 - smape: 0.1687 - val_ia: 0.9734 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0512 - val_smape: 0.1198

Epoch 56/64

287/287 - 4s - 13ms/step - ia: 0.9614 - loss: 0.0079 - mae: 0.0635 - rmse: 0.0876 - smape: 0.1678 - val_ia: 0.9728 - val_loss: 0.0028 - val_mae: 0.0369 - val_rmse: 0.0520 - val_smape: 0.1200

Epoch 57/64

287/287 - 4s - 12ms/step - ia: 0.9618 - loss: 0.0077 - mae: 0.0628 - rmse: 0.0864 - smape: 0.1650 - val_ia: 0.9727 - val_loss: 0.0028 - val_mae: 0.0370 - val_rmse: 0.0520 - val_smape: 0.1214

Epoch 58/64

287/287 - 4s - 13ms/step - ia: 0.9617 - loss: 0.0078 - mae: 0.0630 - rmse: 0.0870 - smape: 0.1670 - val_ia: 0.9736 - val_loss: 0.0027 - val_mae: 0.0359 - val_rmse: 0.0510 - val_smape: 0.1192

Epoch 59/64

287/287 - 4s - 13ms/step - ia: 0.9618 - loss: 0.0077 - mae: 0.0628 - rmse: 0.0867 - smape: 0.1653 - val_ia: 0.9730 - val_loss: 0.0028 - val_mae: 0.0367 - val_rmse: 0.0517 - val_smape: 0.1219

Epoch 60/64

287/287 - 4s - 13ms/step - ia: 0.9622 - loss: 0.0075 - mae: 0.0623 - rmse: 0.0854 - smape: 0.1650 - val_ia: 0.9732 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0511 - val_smape: 0.1214

Epoch 61/64

287/287 - 4s - 13ms/step - ia: 0.9623 - loss: 0.0076 - mae: 0.0622 - rmse: 0.0860 - smape: 0.1649 - val_ia: 0.9732 - val_loss: 0.0028 - val_mae: 0.0363 - val_rmse: 0.0512 - val_smape: 0.1188

Epoch 62/64

287/287 - 4s - 13ms/step - ia: 0.9620 - loss: 0.0077 - mae: 0.0625 - rmse: 0.0865 - smape: 0.1643 - val_ia: 0.9730 - val_loss: 0.0028 - val_mae: 0.0367 - val_rmse: 0.0515 - val_smape: 0.1203

Epoch 63/64

287/287 - 3s - 12ms/step - ia: 0.9622 - loss: 0.0076 - mae: 0.0622 - rmse: 0.0859 - smape: 0.1652 - val_ia: 0.9734 - val_loss: 0.0027 - val_mae: 0.0361 - val_rmse: 0.0510 - val_smape: 0.1173

Epoch 64/64

287/287 - 4s - 14ms/step - ia: 0.9624 - loss: 0.0076 - mae: 0.0620 - rmse: 0.0858 - smape: 0.1640 - val_ia: 0.9737 - val_loss: 0.0027 - val_mae: 0.0358 - val_rmse: 0.0506 - val_smape: 0.1164

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:06 784ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

100%|██████████| 50/50 [9:58:26<00:00, 718.12s/trial, best loss: 0.0016658599381961904]
{'activation': 0, 'batch': 2, 'dropout': 0.1, 'epochs': 2, 'layers': 2.0, 'learning_rate': 0.0001582738817910678, 'units': 3}

In [22]:
print(best)

{'activation': 0, 'batch': 2, 'dropout': 0.1, 'epochs': 2, 'layers': 2.0, 'learning_rate': 0.0001582738817910678, 'units': 3}