Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 1
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43788, 12, 6)
Dimensiones de Y: (43788, 1)

In [16]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30651, 12, 6)
Las dimensiones de testX son:  (8801, 12, 6)
Las dimensiones de valX son:  (4336, 12, 6)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30651, 1)
Las dimensiones de testY son:  (8801, 1)
Las dimensiones de valY son:  (4336, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 36s - 37ms/step - ia: 0.5232 - loss: 0.5913 - mae: 0.5389 - rmse: 0.7432 - smape: 1.0938 - val_ia: 0.3560 - val_loss: 0.3671 - val_mae: 0.4190 - val_rmse: 0.5169 - val_smape: 0.8776

Epoch 2/128

958/958 - 16s - 16ms/step - ia: 0.6335 - loss: 0.4389 - mae: 0.4574 - rmse: 0.6422 - smape: 0.9077 - val_ia: 0.4006 - val_loss: 0.2832 - val_mae: 0.3781 - val_rmse: 0.4683 - val_smape: 0.8222

Epoch 3/128

958/958 - 12s - 13ms/step - ia: 0.6695 - loss: 0.3782 - mae: 0.4224 - rmse: 0.5955 - smape: 0.8432 - val_ia: 0.4333 - val_loss: 0.2456 - val_mae: 0.3491 - val_rmse: 0.4355 - val_smape: 0.7644

Epoch 4/128

958/958 - 12s - 13ms/step - ia: 0.6918 - loss: 0.3431 - mae: 0.3985 - rmse: 0.5655 - smape: 0.8035 - val_ia: 0.4746 - val_loss: 0.2108 - val_mae: 0.3175 - val_rmse: 0.4032 - val_smape: 0.7083

Epoch 5/128

958/958 - 14s - 14ms/step - ia: 0.7081 - loss: 0.3121 - mae: 0.3809 - rmse: 0.5392 - smape: 0.7736 - val_ia: 0.4979 - val_loss: 0.1922 - val_mae: 0.3018 - val_rmse: 0.3839 - val_smape: 0.6793

Epoch 6/128

958/958 - 16s - 17ms/step - ia: 0.7204 - loss: 0.2909 - mae: 0.3679 - rmse: 0.5205 - smape: 0.7528 - val_ia: 0.5302 - val_loss: 0.1689 - val_mae: 0.2774 - val_rmse: 0.3591 - val_smape: 0.6387

Epoch 7/128

958/958 - 19s - 19ms/step - ia: 0.7338 - loss: 0.2665 - mae: 0.3523 - rmse: 0.4984 - smape: 0.7236 - val_ia: 0.5434 - val_loss: 0.1559 - val_mae: 0.2692 - val_rmse: 0.3479 - val_smape: 0.6251

Epoch 8/128

958/958 - 13s - 13ms/step - ia: 0.7432 - loss: 0.2548 - mae: 0.3415 - rmse: 0.4864 - smape: 0.7011 - val_ia: 0.5663 - val_loss: 0.1449 - val_mae: 0.2544 - val_rmse: 0.3301 - val_smape: 0.5911

Epoch 9/128

958/958 - 12s - 13ms/step - ia: 0.7500 - loss: 0.2418 - mae: 0.3337 - rmse: 0.4743 - smape: 0.6866 - val_ia: 0.5813 - val_loss: 0.1275 - val_mae: 0.2407 - val_rmse: 0.3158 - val_smape: 0.5736

Epoch 10/128

958/958 - 13s - 13ms/step - ia: 0.7615 - loss: 0.2211 - mae: 0.3196 - rmse: 0.4533 - smape: 0.6646 - val_ia: 0.6167 - val_loss: 0.1133 - val_mae: 0.2207 - val_rmse: 0.2948 - val_smape: 0.5361

Epoch 11/128

958/958 - 13s - 13ms/step - ia: 0.7686 - loss: 0.2149 - mae: 0.3120 - rmse: 0.4451 - smape: 0.6461 - val_ia: 0.6050 - val_loss: 0.1145 - val_mae: 0.2289 - val_rmse: 0.2942 - val_smape: 0.5347

Epoch 12/128

958/958 - 11s - 12ms/step - ia: 0.7766 - loss: 0.2017 - mae: 0.3027 - rmse: 0.4311 - smape: 0.6294 - val_ia: 0.6311 - val_loss: 0.0975 - val_mae: 0.2085 - val_rmse: 0.2734 - val_smape: 0.5058

Epoch 13/128

958/958 - 12s - 12ms/step - ia: 0.7817 - loss: 0.1960 - mae: 0.2963 - rmse: 0.4241 - smape: 0.6178 - val_ia: 0.6298 - val_loss: 0.0985 - val_mae: 0.2102 - val_rmse: 0.2731 - val_smape: 0.5016

Epoch 14/128

958/958 - 12s - 12ms/step - ia: 0.7861 - loss: 0.1856 - mae: 0.2912 - rmse: 0.4145 - smape: 0.6093 - val_ia: 0.6500 - val_loss: 0.0899 - val_mae: 0.1972 - val_rmse: 0.2605 - val_smape: 0.4816

Epoch 15/128

958/958 - 21s - 21ms/step - ia: 0.7885 - loss: 0.1834 - mae: 0.2875 - rmse: 0.4110 - smape: 0.6014 - val_ia: 0.6554 - val_loss: 0.0872 - val_mae: 0.1943 - val_rmse: 0.2575 - val_smape: 0.4747

Epoch 16/128

958/958 - 11s - 12ms/step - ia: 0.7935 - loss: 0.1788 - mae: 0.2824 - rmse: 0.4054 - smape: 0.5908 - val_ia: 0.6761 - val_loss: 0.0781 - val_mae: 0.1802 - val_rmse: 0.2442 - val_smape: 0.4527

Epoch 17/128

958/958 - 11s - 11ms/step - ia: 0.7952 - loss: 0.1765 - mae: 0.2792 - rmse: 0.4016 - smape: 0.5836 - val_ia: 0.6733 - val_loss: 0.0821 - val_mae: 0.1847 - val_rmse: 0.2473 - val_smape: 0.4534

Epoch 18/128

958/958 - 12s - 12ms/step - ia: 0.7987 - loss: 0.1699 - mae: 0.2754 - rmse: 0.3953 - smape: 0.5778 - val_ia: 0.6861 - val_loss: 0.0738 - val_mae: 0.1740 - val_rmse: 0.2377 - val_smape: 0.4373

Epoch 19/128

958/958 - 9s - 10ms/step - ia: 0.8016 - loss: 0.1674 - mae: 0.2715 - rmse: 0.3922 - smape: 0.5698 - val_ia: 0.6865 - val_loss: 0.0766 - val_mae: 0.1772 - val_rmse: 0.2373 - val_smape: 0.4335

Epoch 20/128

958/958 - 12s - 12ms/step - ia: 0.8036 - loss: 0.1641 - mae: 0.2694 - rmse: 0.3882 - smape: 0.5680 - val_ia: 0.6977 - val_loss: 0.0726 - val_mae: 0.1693 - val_rmse: 0.2324 - val_smape: 0.4240

Epoch 21/128

958/958 - 20s - 21ms/step - ia: 0.8062 - loss: 0.1613 - mae: 0.2662 - rmse: 0.3842 - smape: 0.5572 - val_ia: 0.7060 - val_loss: 0.0730 - val_mae: 0.1670 - val_rmse: 0.2306 - val_smape: 0.4186

Epoch 22/128

958/958 - 10s - 10ms/step - ia: 0.8075 - loss: 0.1600 - mae: 0.2643 - rmse: 0.3829 - smape: 0.5563 - val_ia: 0.6816 - val_loss: 0.0799 - val_mae: 0.1826 - val_rmse: 0.2406 - val_smape: 0.4353

Epoch 23/128

958/958 - 11s - 12ms/step - ia: 0.8078 - loss: 0.1576 - mae: 0.2635 - rmse: 0.3807 - smape: 0.5530 - val_ia: 0.6952 - val_loss: 0.0709 - val_mae: 0.1699 - val_rmse: 0.2294 - val_smape: 0.4203

Epoch 24/128

958/958 - 11s - 11ms/step - ia: 0.8094 - loss: 0.1560 - mae: 0.2613 - rmse: 0.3766 - smape: 0.5531 - val_ia: 0.6904 - val_loss: 0.0784 - val_mae: 0.1783 - val_rmse: 0.2371 - val_smape: 0.4244

Epoch 25/128

958/958 - 11s - 12ms/step - ia: 0.8110 - loss: 0.1573 - mae: 0.2600 - rmse: 0.3782 - smape: 0.5457 - val_ia: 0.7114 - val_loss: 0.0675 - val_mae: 0.1614 - val_rmse: 0.2231 - val_smape: 0.4075

Epoch 26/128

958/958 - 10s - 11ms/step - ia: 0.8124 - loss: 0.1522 - mae: 0.2584 - rmse: 0.3742 - smape: 0.5439 - val_ia: 0.7182 - val_loss: 0.0657 - val_mae: 0.1577 - val_rmse: 0.2204 - val_smape: 0.3986

Epoch 27/128

958/958 - 10s - 10ms/step - ia: 0.8129 - loss: 0.1501 - mae: 0.2571 - rmse: 0.3713 - smape: 0.5408 - val_ia: 0.6960 - val_loss: 0.0733 - val_mae: 0.1735 - val_rmse: 0.2308 - val_smape: 0.4153

Epoch 28/128

958/958 - 11s - 12ms/step - ia: 0.8126 - loss: 0.1518 - mae: 0.2576 - rmse: 0.3732 - smape: 0.5414 - val_ia: 0.7289 - val_loss: 0.0635 - val_mae: 0.1540 - val_rmse: 0.2152 - val_smape: 0.3940

Epoch 29/128

958/958 - 11s - 12ms/step - ia: 0.8146 - loss: 0.1514 - mae: 0.2547 - rmse: 0.3721 - smape: 0.5373 - val_ia: 0.7073 - val_loss: 0.0686 - val_mae: 0.1653 - val_rmse: 0.2262 - val_smape: 0.4174

Epoch 30/128

958/958 - 11s - 12ms/step - ia: 0.8149 - loss: 0.1524 - mae: 0.2555 - rmse: 0.3722 - smape: 0.5373 - val_ia: 0.7207 - val_loss: 0.0646 - val_mae: 0.1565 - val_rmse: 0.2188 - val_smape: 0.3980

Epoch 31/128

958/958 - 11s - 12ms/step - ia: 0.8150 - loss: 0.1512 - mae: 0.2550 - rmse: 0.3716 - smape: 0.5363 - val_ia: 0.6988 - val_loss: 0.0792 - val_mae: 0.1775 - val_rmse: 0.2348 - val_smape: 0.4191

Epoch 32/128

958/958 - 9s - 9ms/step - ia: 0.8161 - loss: 0.1458 - mae: 0.2529 - rmse: 0.3654 - smape: 0.5375 - val_ia: 0.7093 - val_loss: 0.0712 - val_mae: 0.1674 - val_rmse: 0.2259 - val_smape: 0.4096

Epoch 33/128

958/958 - 11s - 12ms/step - ia: 0.8173 - loss: 0.1467 - mae: 0.2517 - rmse: 0.3645 - smape: 0.5322 - val_ia: 0.7287 - val_loss: 0.0623 - val_mae: 0.1527 - val_rmse: 0.2136 - val_smape: 0.3919

Epoch 34/128

958/958 - 11s - 12ms/step - ia: 0.8183 - loss: 0.1436 - mae: 0.2503 - rmse: 0.3621 - smape: 0.5307 - val_ia: 0.7249 - val_loss: 0.0628 - val_mae: 0.1546 - val_rmse: 0.2154 - val_smape: 0.3954

Epoch 35/128

958/958 - 11s - 12ms/step - ia: 0.8178 - loss: 0.1474 - mae: 0.2510 - rmse: 0.3660 - smape: 0.5329 - val_ia: 0.7271 - val_loss: 0.0647 - val_mae: 0.1565 - val_rmse: 0.2162 - val_smape: 0.3897

Epoch 36/128

958/958 - 11s - 12ms/step - ia: 0.8187 - loss: 0.1456 - mae: 0.2497 - rmse: 0.3647 - smape: 0.5230 - val_ia: 0.7357 - val_loss: 0.0623 - val_mae: 0.1522 - val_rmse: 0.2122 - val_smape: 0.3873

Epoch 37/128

958/958 - 11s - 12ms/step - ia: 0.8200 - loss: 0.1459 - mae: 0.2484 - rmse: 0.3643 - smape: 0.5262 - val_ia: 0.7176 - val_loss: 0.0676 - val_mae: 0.1621 - val_rmse: 0.2200 - val_smape: 0.3951

Epoch 38/128

958/958 - 21s - 22ms/step - ia: 0.8195 - loss: 0.1434 - mae: 0.2490 - rmse: 0.3613 - smape: 0.5290 - val_ia: 0.7284 - val_loss: 0.0678 - val_mae: 0.1577 - val_rmse: 0.2174 - val_smape: 0.3859

Epoch 39/128

958/958 - 11s - 12ms/step - ia: 0.8177 - loss: 0.1481 - mae: 0.2514 - rmse: 0.3678 - smape: 0.5294 - val_ia: 0.7393 - val_loss: 0.0619 - val_mae: 0.1494 - val_rmse: 0.2125 - val_smape: 0.3863

Epoch 40/128

958/958 - 11s - 12ms/step - ia: 0.8199 - loss: 0.1451 - mae: 0.2488 - rmse: 0.3623 - smape: 0.5252 - val_ia: 0.7233 - val_loss: 0.0691 - val_mae: 0.1616 - val_rmse: 0.2206 - val_smape: 0.3957

Epoch 41/128

958/958 - 11s - 12ms/step - ia: 0.8195 - loss: 0.1450 - mae: 0.2494 - rmse: 0.3633 - smape: 0.5267 - val_ia: 0.7370 - val_loss: 0.0619 - val_mae: 0.1505 - val_rmse: 0.2107 - val_smape: 0.3811

Epoch 42/128

958/958 - 12s - 13ms/step - ia: 0.8214 - loss: 0.1414 - mae: 0.2467 - rmse: 0.3591 - smape: 0.5212 - val_ia: 0.7262 - val_loss: 0.0613 - val_mae: 0.1536 - val_rmse: 0.2131 - val_smape: 0.3907

Epoch 43/128

958/958 - 11s - 12ms/step - ia: 0.8204 - loss: 0.1444 - mae: 0.2482 - rmse: 0.3631 - smape: 0.5233 - val_ia: 0.7448 - val_loss: 0.0624 - val_mae: 0.1480 - val_rmse: 0.2097 - val_smape: 0.3766

Epoch 44/128

958/958 - 22s - 23ms/step - ia: 0.8211 - loss: 0.1404 - mae: 0.2466 - rmse: 0.3585 - smape: 0.5216 - val_ia: 0.7253 - val_loss: 0.0635 - val_mae: 0.1563 - val_rmse: 0.2144 - val_smape: 0.3898

Epoch 45/128

958/958 - 19s - 19ms/step - ia: 0.8207 - loss: 0.1417 - mae: 0.2471 - rmse: 0.3583 - smape: 0.5215 - val_ia: 0.7507 - val_loss: 0.0610 - val_mae: 0.1452 - val_rmse: 0.2081 - val_smape: 0.3755

Epoch 46/128

958/958 - 12s - 12ms/step - ia: 0.8207 - loss: 0.1425 - mae: 0.2465 - rmse: 0.3590 - smape: 0.5220 - val_ia: 0.7575 - val_loss: 0.0615 - val_mae: 0.1436 - val_rmse: 0.2070 - val_smape: 0.3701

Epoch 47/128

958/958 - 20s - 21ms/step - ia: 0.8233 - loss: 0.1435 - mae: 0.2453 - rmse: 0.3596 - smape: 0.5149 - val_ia: 0.7493 - val_loss: 0.0637 - val_mae: 0.1482 - val_rmse: 0.2100 - val_smape: 0.3746

Epoch 48/128

958/958 - 10s - 10ms/step - ia: 0.8236 - loss: 0.1415 - mae: 0.2444 - rmse: 0.3590 - smape: 0.5178 - val_ia: 0.7192 - val_loss: 0.0662 - val_mae: 0.1595 - val_rmse: 0.2175 - val_smape: 0.3916

Epoch 49/128

958/958 - 12s - 12ms/step - ia: 0.8223 - loss: 0.1431 - mae: 0.2459 - rmse: 0.3609 - smape: 0.5208 - val_ia: 0.7208 - val_loss: 0.0659 - val_mae: 0.1604 - val_rmse: 0.2181 - val_smape: 0.3919

Epoch 50/128

958/958 - 12s - 12ms/step - ia: 0.8233 - loss: 0.1385 - mae: 0.2443 - rmse: 0.3553 - smape: 0.5147 - val_ia: 0.7208 - val_loss: 0.0665 - val_mae: 0.1598 - val_rmse: 0.2176 - val_smape: 0.3892

Epoch 51/128

958/958 - 9s - 9ms/step - ia: 0.8233 - loss: 0.1397 - mae: 0.2441 - rmse: 0.3576 - smape: 0.5149 - val_ia: 0.7325 - val_loss: 0.0628 - val_mae: 0.1518 - val_rmse: 0.2114 - val_smape: 0.3820

Epoch 52/128

958/958 - 12s - 12ms/step - ia: 0.8226 - loss: 0.1431 - mae: 0.2453 - rmse: 0.3597 - smape: 0.5194 - val_ia: 0.7364 - val_loss: 0.0649 - val_mae: 0.1525 - val_rmse: 0.2126 - val_smape: 0.3799

Epoch 53/128

958/958 - 10s - 10ms/step - ia: 0.8237 - loss: 0.1387 - mae: 0.2432 - rmse: 0.3551 - smape: 0.5171 - val_ia: 0.7252 - val_loss: 0.0674 - val_mae: 0.1588 - val_rmse: 0.2175 - val_smape: 0.3901

Epoch 54/128

958/958 - 13s - 14ms/step - ia: 0.8224 - loss: 0.1414 - mae: 0.2455 - rmse: 0.3588 - smape: 0.5173 - val_ia: 0.7055 - val_loss: 0.0685 - val_mae: 0.1675 - val_rmse: 0.2237 - val_smape: 0.4064

Epoch 55/128

958/958 - 12s - 12ms/step - ia: 0.8241 - loss: 0.1381 - mae: 0.2433 - rmse: 0.3555 - smape: 0.5163 - val_ia: 0.7316 - val_loss: 0.0670 - val_mae: 0.1581 - val_rmse: 0.2163 - val_smape: 0.3874

Epoch 56/128

958/958 - 12s - 12ms/step - ia: 0.8239 - loss: 0.1387 - mae: 0.2437 - rmse: 0.3555 - smape: 0.5145 - val_ia: 0.7156 - val_loss: 0.0728 - val_mae: 0.1661 - val_rmse: 0.2230 - val_smape: 0.3938

Epoch 57/128

958/958 - 12s - 12ms/step - ia: 0.8236 - loss: 0.1402 - mae: 0.2436 - rmse: 0.3562 - smape: 0.5156 - val_ia: 0.7302 - val_loss: 0.0656 - val_mae: 0.1563 - val_rmse: 0.2146 - val_smape: 0.3877

Epoch 58/128

958/958 - 12s - 12ms/step - ia: 0.8233 - loss: 0.1402 - mae: 0.2441 - rmse: 0.3573 - smape: 0.5183 - val_ia: 0.7343 - val_loss: 0.0629 - val_mae: 0.1526 - val_rmse: 0.2111 - val_smape: 0.3830

Epoch 59/128

958/958 - 21s - 21ms/step - ia: 0.8229 - loss: 0.1421 - mae: 0.2438 - rmse: 0.3577 - smape: 0.5173 - val_ia: 0.7499 - val_loss: 0.0615 - val_mae: 0.1461 - val_rmse: 0.2072 - val_smape: 0.3728

Epoch 60/128

958/958 - 12s - 13ms/step - ia: 0.8232 - loss: 0.1395 - mae: 0.2432 - rmse: 0.3567 - smape: 0.5161 - val_ia: 0.7479 - val_loss: 0.0642 - val_mae: 0.1478 - val_rmse: 0.2096 - val_smape: 0.3734

Epoch 60: early stopping

Restoring model weights from the end of the best epoch: 45.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:35 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

  2%|▏         | 1/50 [13:14<10:48:35, 794.19s/trial, best loss: 0.04417709273722074]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

120/120 - 38s - 314ms/step - ia: 0.5226 - loss: 0.6517 - mae: 0.5162 - rmse: 0.7597 - smape: 1.0757 - val_ia: 0.6801 - val_loss: 0.2621 - val_mae: 0.3510 - val_rmse: 0.4798 - val_smape: 0.7603

Epoch 2/16

120/120 - 35s - 292ms/step - ia: 0.7860 - loss: 0.2076 - mae: 0.2989 - rmse: 0.4479 - smape: 0.6524 - val_ia: 0.7434 - val_loss: 0.1601 - val_mae: 0.2720 - val_rmse: 0.3781 - val_smape: 0.6276

Epoch 3/16

120/120 - 23s - 188ms/step - ia: 0.8481 - loss: 0.1157 - mae: 0.2189 - rmse: 0.3356 - smape: 0.5130 - val_ia: 0.8486 - val_loss: 0.0738 - val_mae: 0.1671 - val_rmse: 0.2566 - val_smape: 0.4308

Epoch 4/16

120/120 - 20s - 170ms/step - ia: 0.8761 - loss: 0.0831 - mae: 0.1804 - rmse: 0.2835 - smape: 0.4446 - val_ia: 0.8452 - val_loss: 0.0681 - val_mae: 0.1682 - val_rmse: 0.2491 - val_smape: 0.4391

Epoch 5/16

120/120 - 20s - 170ms/step - ia: 0.8891 - loss: 0.0712 - mae: 0.1628 - rmse: 0.2625 - smape: 0.4080 - val_ia: 0.8616 - val_loss: 0.0650 - val_mae: 0.1585 - val_rmse: 0.2406 - val_smape: 0.4089

Epoch 6/16

120/120 - 16s - 135ms/step - ia: 0.8946 - loss: 0.0675 - mae: 0.1548 - rmse: 0.2551 - smape: 0.3900 - val_ia: 0.8579 - val_loss: 0.0592 - val_mae: 0.1507 - val_rmse: 0.2322 - val_smape: 0.3978

Epoch 7/16

120/120 - 16s - 129ms/step - ia: 0.8961 - loss: 0.0655 - mae: 0.1523 - rmse: 0.2526 - smape: 0.3875 - val_ia: 0.8773 - val_loss: 0.0596 - val_mae: 0.1435 - val_rmse: 0.2272 - val_smape: 0.3674

Epoch 8/16

120/120 - 19s - 161ms/step - ia: 0.8952 - loss: 0.0664 - mae: 0.1536 - rmse: 0.2526 - smape: 0.3900 - val_ia: 0.8745 - val_loss: 0.0572 - val_mae: 0.1432 - val_rmse: 0.2248 - val_smape: 0.3751

Epoch 9/16

120/120 - 19s - 161ms/step - ia: 0.8994 - loss: 0.0637 - mae: 0.1481 - rmse: 0.2481 - smape: 0.3769 - val_ia: 0.8792 - val_loss: 0.0551 - val_mae: 0.1358 - val_rmse: 0.2197 - val_smape: 0.3585

Epoch 10/16

120/120 - 21s - 171ms/step - ia: 0.8955 - loss: 0.0657 - mae: 0.1534 - rmse: 0.2521 - smape: 0.3896 - val_ia: 0.8491 - val_loss: 0.0651 - val_mae: 0.1685 - val_rmse: 0.2445 - val_smape: 0.4214

Epoch 11/16

120/120 - 19s - 154ms/step - ia: 0.8953 - loss: 0.0660 - mae: 0.1540 - rmse: 0.2529 - smape: 0.3899 - val_ia: 0.8633 - val_loss: 0.0571 - val_mae: 0.1474 - val_rmse: 0.2259 - val_smape: 0.3786

Epoch 12/16

120/120 - 19s - 158ms/step - ia: 0.8976 - loss: 0.0647 - mae: 0.1504 - rmse: 0.2494 - smape: 0.3830 - val_ia: 0.8630 - val_loss: 0.0594 - val_mae: 0.1506 - val_rmse: 0.2322 - val_smape: 0.4018

Epoch 13/16

120/120 - 19s - 158ms/step - ia: 0.9001 - loss: 0.0626 - mae: 0.1469 - rmse: 0.2458 - smape: 0.3754 - val_ia: 0.8757 - val_loss: 0.0579 - val_mae: 0.1429 - val_rmse: 0.2252 - val_smape: 0.3750

Epoch 14/16

120/120 - 19s - 157ms/step - ia: 0.9023 - loss: 0.0619 - mae: 0.1436 - rmse: 0.2451 - smape: 0.3661 - val_ia: 0.8853 - val_loss: 0.0540 - val_mae: 0.1329 - val_rmse: 0.2180 - val_smape: 0.3516

Epoch 15/16

120/120 - 16s - 132ms/step - ia: 0.9039 - loss: 0.0610 - mae: 0.1414 - rmse: 0.2428 - smape: 0.3631 - val_ia: 0.8878 - val_loss: 0.0542 - val_mae: 0.1298 - val_rmse: 0.2175 - val_smape: 0.3477

Epoch 16/16

120/120 - 15s - 121ms/step - ia: 0.9028 - loss: 0.0611 - mae: 0.1429 - rmse: 0.2430 - smape: 0.3672 - val_ia: 0.8825 - val_loss: 0.0542 - val_mae: 0.1346 - val_rmse: 0.2181 - val_smape: 0.3584

Restoring model weights from the end of the best epoch: 14.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:03 917ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step

  4%|▍         | 2/50 [18:51<7:00:14, 525.29s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 15s - 31ms/step - ia: 0.1193 - loss: 0.9999 - mae: 0.7372 - rmse: 0.9866 - smape: 1.7690 - val_ia: 0.2387 - val_loss: 0.9674 - val_mae: 0.7248 - val_rmse: 0.8364 - val_smape: 1.7920

Epoch 2/8

479/479 - 5s - 11ms/step - ia: 0.1310 - loss: 0.9980 - mae: 0.7365 - rmse: 0.9846 - smape: 1.7697 - val_ia: 0.2390 - val_loss: 0.9661 - val_mae: 0.7244 - val_rmse: 0.8359 - val_smape: 1.7938

Epoch 3/8

479/479 - 5s - 10ms/step - ia: 0.1256 - loss: 0.9963 - mae: 0.7356 - rmse: 0.9845 - smape: 1.7684 - val_ia: 0.2393 - val_loss: 0.9648 - val_mae: 0.7239 - val_rmse: 0.8354 - val_smape: 1.7949

Epoch 4/8

479/479 - 5s - 10ms/step - ia: 0.1282 - loss: 0.9944 - mae: 0.7346 - rmse: 0.9836 - smape: 1.7677 - val_ia: 0.2397 - val_loss: 0.9635 - val_mae: 0.7233 - val_rmse: 0.8349 - val_smape: 1.7957

Epoch 5/8

479/479 - 5s - 10ms/step - ia: 0.1295 - loss: 0.9925 - mae: 0.7336 - rmse: 0.9825 - smape: 1.7661 - val_ia: 0.2400 - val_loss: 0.9621 - val_mae: 0.7228 - val_rmse: 0.8343 - val_smape: 1.7961

Epoch 6/8

479/479 - 5s - 11ms/step - ia: 0.1306 - loss: 0.9909 - mae: 0.7327 - rmse: 0.9828 - smape: 1.7640 - val_ia: 0.2404 - val_loss: 0.9607 - val_mae: 0.7221 - val_rmse: 0.8337 - val_smape: 1.7960

Epoch 7/8

479/479 - 5s - 10ms/step - ia: 0.1295 - loss: 0.9888 - mae: 0.7314 - rmse: 0.9812 - smape: 1.7613 - val_ia: 0.2408 - val_loss: 0.9593 - val_mae: 0.7214 - val_rmse: 0.8330 - val_smape: 1.7952

Epoch 8/8

479/479 - 5s - 11ms/step - ia: 0.1380 - loss: 0.9871 - mae: 0.7304 - rmse: 0.9800 - smape: 1.7587 - val_ia: 0.2412 - val_loss: 0.9577 - val_mae: 0.7206 - val_rmse: 0.8323 - val_smape: 1.7938

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:43 769ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

  6%|▌         | 3/50 [19:43<4:02:19, 309.35s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

240/240 - 18s - 75ms/step - ia: 0.1095 - loss: 0.9765 - mae: 0.7388 - rmse: 0.9816 - smape: 1.7862 - val_ia: 0.2682 - val_loss: 0.9003 - val_mae: 0.7079 - val_rmse: 0.8435 - val_smape: 1.7685

Epoch 2/32

240/240 - 7s - 28ms/step - ia: 0.1884 - loss: 0.8738 - mae: 0.6947 - rmse: 0.9292 - smape: 1.6194 - val_ia: 0.2989 - val_loss: 0.7897 - val_mae: 0.6610 - val_rmse: 0.7912 - val_smape: 1.5503

Epoch 3/32

240/240 - 10s - 43ms/step - ia: 0.3070 - loss: 0.7516 - mae: 0.6387 - rmse: 0.8608 - smape: 1.4077 - val_ia: 0.3569 - val_loss: 0.6556 - val_mae: 0.5995 - val_rmse: 0.7249 - val_smape: 1.3210

Epoch 4/32

240/240 - 7s - 28ms/step - ia: 0.4411 - loss: 0.6214 - mae: 0.5718 - rmse: 0.7816 - smape: 1.1975 - val_ia: 0.4299 - val_loss: 0.5286 - val_mae: 0.5333 - val_rmse: 0.6583 - val_smape: 1.1246

Epoch 5/32

240/240 - 7s - 28ms/step - ia: 0.5499 - loss: 0.5270 - mae: 0.5136 - rmse: 0.7203 - smape: 1.0378 - val_ia: 0.4859 - val_loss: 0.4598 - val_mae: 0.4849 - val_rmse: 0.6186 - val_smape: 0.9995

Epoch 6/32

240/240 - 10s - 44ms/step - ia: 0.6041 - loss: 0.4892 - mae: 0.4837 - rmse: 0.6930 - smape: 0.9515 - val_ia: 0.5161 - val_loss: 0.4342 - val_mae: 0.4610 - val_rmse: 0.6011 - val_smape: 0.9404

Epoch 7/32

240/240 - 10s - 43ms/step - ia: 0.6271 - loss: 0.4744 - mae: 0.4696 - rmse: 0.6838 - smape: 0.9172 - val_ia: 0.5310 - val_loss: 0.4185 - val_mae: 0.4477 - val_rmse: 0.5890 - val_smape: 0.9110

Epoch 8/32

240/240 - 7s - 28ms/step - ia: 0.6366 - loss: 0.4624 - mae: 0.4621 - rmse: 0.6748 - smape: 0.9032 - val_ia: 0.5413 - val_loss: 0.4072 - val_mae: 0.4398 - val_rmse: 0.5810 - val_smape: 0.8970

Epoch 9/32

240/240 - 10s - 43ms/step - ia: 0.6433 - loss: 0.4543 - mae: 0.4563 - rmse: 0.6683 - smape: 0.8932 - val_ia: 0.5482 - val_loss: 0.3968 - val_mae: 0.4335 - val_rmse: 0.5734 - val_smape: 0.8871

Epoch 10/32

240/240 - 6s - 27ms/step - ia: 0.6485 - loss: 0.4460 - mae: 0.4514 - rmse: 0.6616 - smape: 0.8841 - val_ia: 0.5546 - val_loss: 0.3878 - val_mae: 0.4283 - val_rmse: 0.5672 - val_smape: 0.8799

Epoch 11/32

240/240 - 6s - 26ms/step - ia: 0.6526 - loss: 0.4376 - mae: 0.4469 - rmse: 0.6560 - smape: 0.8784 - val_ia: 0.5611 - val_loss: 0.3795 - val_mae: 0.4233 - val_rmse: 0.5617 - val_smape: 0.8730

Epoch 12/32

240/240 - 6s - 24ms/step - ia: 0.6570 - loss: 0.4316 - mae: 0.4428 - rmse: 0.6504 - smape: 0.8702 - val_ia: 0.5658 - val_loss: 0.3712 - val_mae: 0.4186 - val_rmse: 0.5558 - val_smape: 0.8660

Epoch 13/32

240/240 - 6s - 24ms/step - ia: 0.6602 - loss: 0.4234 - mae: 0.4381 - rmse: 0.6442 - smape: 0.8639 - val_ia: 0.5705 - val_loss: 0.3635 - val_mae: 0.4142 - val_rmse: 0.5504 - val_smape: 0.8611

Epoch 14/32

240/240 - 6s - 24ms/step - ia: 0.6641 - loss: 0.4179 - mae: 0.4353 - rmse: 0.6399 - smape: 0.8606 - val_ia: 0.5754 - val_loss: 0.3558 - val_mae: 0.4097 - val_rmse: 0.5450 - val_smape: 0.8544

Epoch 15/32

240/240 - 10s - 41ms/step - ia: 0.6685 - loss: 0.4091 - mae: 0.4300 - rmse: 0.6340 - smape: 0.8523 - val_ia: 0.5804 - val_loss: 0.3487 - val_mae: 0.4056 - val_rmse: 0.5402 - val_smape: 0.8489

Epoch 16/32

240/240 - 10s - 43ms/step - ia: 0.6713 - loss: 0.4022 - mae: 0.4272 - rmse: 0.6298 - smape: 0.8502 - val_ia: 0.5828 - val_loss: 0.3413 - val_mae: 0.4022 - val_rmse: 0.5348 - val_smape: 0.8456

Epoch 17/32

240/240 - 8s - 33ms/step - ia: 0.6753 - loss: 0.3956 - mae: 0.4227 - rmse: 0.6241 - smape: 0.8430 - val_ia: 0.5862 - val_loss: 0.3342 - val_mae: 0.3985 - val_rmse: 0.5297 - val_smape: 0.8407

Epoch 18/32

240/240 - 13s - 55ms/step - ia: 0.6775 - loss: 0.3890 - mae: 0.4201 - rmse: 0.6174 - smape: 0.8424 - val_ia: 0.5908 - val_loss: 0.3264 - val_mae: 0.3936 - val_rmse: 0.5237 - val_smape: 0.8322

Epoch 19/32

240/240 - 10s - 42ms/step - ia: 0.6816 - loss: 0.3801 - mae: 0.4148 - rmse: 0.6111 - smape: 0.8341 - val_ia: 0.5964 - val_loss: 0.3195 - val_mae: 0.3891 - val_rmse: 0.5188 - val_smape: 0.8254

Epoch 20/32

240/240 - 11s - 45ms/step - ia: 0.6837 - loss: 0.3751 - mae: 0.4124 - rmse: 0.6068 - smape: 0.8276 - val_ia: 0.6011 - val_loss: 0.3125 - val_mae: 0.3846 - val_rmse: 0.5135 - val_smape: 0.8186

Epoch 21/32

240/240 - 21s - 86ms/step - ia: 0.6898 - loss: 0.3657 - mae: 0.4062 - rmse: 0.5985 - smape: 0.8203 - val_ia: 0.6045 - val_loss: 0.3055 - val_mae: 0.3807 - val_rmse: 0.5082 - val_smape: 0.8124

Epoch 22/32

240/240 - 8s - 32ms/step - ia: 0.6920 - loss: 0.3598 - mae: 0.4033 - rmse: 0.5945 - smape: 0.8159 - val_ia: 0.6098 - val_loss: 0.2981 - val_mae: 0.3758 - val_rmse: 0.5025 - val_smape: 0.8042

Epoch 23/32

240/240 - 13s - 55ms/step - ia: 0.6965 - loss: 0.3541 - mae: 0.3987 - rmse: 0.5902 - smape: 0.8069 - val_ia: 0.6146 - val_loss: 0.2911 - val_mae: 0.3712 - val_rmse: 0.4969 - val_smape: 0.7968

Epoch 24/32

240/240 - 10s - 41ms/step - ia: 0.7004 - loss: 0.3471 - mae: 0.3948 - rmse: 0.5836 - smape: 0.8045 - val_ia: 0.6181 - val_loss: 0.2842 - val_mae: 0.3671 - val_rmse: 0.4914 - val_smape: 0.7902

Epoch 25/32

240/240 - 11s - 47ms/step - ia: 0.7044 - loss: 0.3393 - mae: 0.3904 - rmse: 0.5771 - smape: 0.7936 - val_ia: 0.6236 - val_loss: 0.2780 - val_mae: 0.3624 - val_rmse: 0.4865 - val_smape: 0.7825

Epoch 26/32

240/240 - 10s - 42ms/step - ia: 0.7075 - loss: 0.3334 - mae: 0.3867 - rmse: 0.5717 - smape: 0.7891 - val_ia: 0.6271 - val_loss: 0.2714 - val_mae: 0.3581 - val_rmse: 0.4809 - val_smape: 0.7755

Epoch 27/32

240/240 - 11s - 45ms/step - ia: 0.7103 - loss: 0.3286 - mae: 0.3835 - rmse: 0.5676 - smape: 0.7825 - val_ia: 0.6339 - val_loss: 0.2658 - val_mae: 0.3529 - val_rmse: 0.4762 - val_smape: 0.7652

Epoch 28/32

240/240 - 15s - 63ms/step - ia: 0.7151 - loss: 0.3187 - mae: 0.3783 - rmse: 0.5589 - smape: 0.7755 - val_ia: 0.6346 - val_loss: 0.2598 - val_mae: 0.3504 - val_rmse: 0.4711 - val_smape: 0.7639

Epoch 29/32

240/240 - 10s - 42ms/step - ia: 0.7183 - loss: 0.3169 - mae: 0.3749 - rmse: 0.5565 - smape: 0.7687 - val_ia: 0.6384 - val_loss: 0.2548 - val_mae: 0.3467 - val_rmse: 0.4666 - val_smape: 0.7584

Epoch 30/32

240/240 - 11s - 45ms/step - ia: 0.7200 - loss: 0.3118 - mae: 0.3725 - rmse: 0.5523 - smape: 0.7645 - val_ia: 0.6458 - val_loss: 0.2503 - val_mae: 0.3418 - val_rmse: 0.4632 - val_smape: 0.7480

Epoch 31/32

240/240 - 10s - 43ms/step - ia: 0.7256 - loss: 0.3029 - mae: 0.3674 - rmse: 0.5454 - smape: 0.7563 - val_ia: 0.6470 - val_loss: 0.2454 - val_mae: 0.3392 - val_rmse: 0.4587 - val_smape: 0.7433

Epoch 32/32

240/240 - 6s - 26ms/step - ia: 0.7277 - loss: 0.2974 - mae: 0.3645 - rmse: 0.5399 - smape: 0.7511 - val_ia: 0.6519 - val_loss: 0.2411 - val_mae: 0.3350 - val_rmse: 0.4548 - val_smape: 0.7355

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:12 533ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

Epoch 1/64

  8%|▊         | 4/50 [25:00<3:59:20, 312.19s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

3832/3832 - 32s - 8ms/step - ia: 0.2357 - loss: 1.0294 - mae: 0.7617 - rmse: 0.9481 - smape: 1.6396 - val_ia: 0.1873 - val_loss: 0.9639 - val_mae: 0.7362 - val_rmse: 0.7734 - val_smape: 1.9756

Epoch 2/64

3832/3832 - 40s - 10ms/step - ia: 0.2366 - loss: 1.0234 - mae: 0.7595 - rmse: 0.9452 - smape: 1.6406 - val_ia: 0.1877 - val_loss: 0.9603 - val_mae: 0.7336 - val_rmse: 0.7709 - val_smape: 1.9677

Epoch 3/64

3832/3832 - 38s - 10ms/step - ia: 0.2381 - loss: 1.0189 - mae: 0.7571 - rmse: 0.9440 - smape: 1.6384 - val_ia: 0.1880 - val_loss: 0.9567 - val_mae: 0.7316 - val_rmse: 0.7688 - val_smape: 1.9504

Epoch 4/64

3832/3832 - 42s - 11ms/step - ia: 0.2371 - loss: 1.0191 - mae: 0.7556 - rmse: 0.9424 - smape: 1.6325 - val_ia: 0.1883 - val_loss: 0.9531 - val_mae: 0.7295 - val_rmse: 0.7667 - val_smape: 1.9326

Epoch 5/64

3832/3832 - 25s - 6ms/step - ia: 0.2401 - loss: 1.0130 - mae: 0.7533 - rmse: 0.9389 - smape: 1.6297 - val_ia: 0.1886 - val_loss: 0.9494 - val_mae: 0.7279 - val_rmse: 0.7651 - val_smape: 1.9255

Epoch 6/64

3832/3832 - 40s - 10ms/step - ia: 0.2395 - loss: 1.0074 - mae: 0.7511 - rmse: 0.9368 - smape: 1.6287 - val_ia: 0.1890 - val_loss: 0.9452 - val_mae: 0.7258 - val_rmse: 0.7630 - val_smape: 1.9107

Epoch 7/64

3832/3832 - 51s - 13ms/step - ia: 0.2428 - loss: 1.0013 - mae: 0.7479 - rmse: 0.9325 - smape: 1.6230 - val_ia: 0.1894 - val_loss: 0.9407 - val_mae: 0.7237 - val_rmse: 0.7608 - val_smape: 1.8966

Epoch 8/64

3832/3832 - 26s - 7ms/step - ia: 0.2444 - loss: 0.9964 - mae: 0.7460 - rmse: 0.9306 - smape: 1.6204 - val_ia: 0.1897 - val_loss: 0.9359 - val_mae: 0.7216 - val_rmse: 0.7587 - val_smape: 1.8863

Epoch 9/64

3832/3832 - 27s - 7ms/step - ia: 0.2439 - loss: 0.9920 - mae: 0.7445 - rmse: 0.9291 - smape: 1.6168 - val_ia: 0.1902 - val_loss: 0.9305 - val_mae: 0.7192 - val_rmse: 0.7563 - val_smape: 1.8732

Epoch 10/64

3832/3832 - 42s - 11ms/step - ia: 0.2482 - loss: 0.9846 - mae: 0.7397 - rmse: 0.9232 - smape: 1.6071 - val_ia: 0.1907 - val_loss: 0.9244 - val_mae: 0.7165 - val_rmse: 0.7534 - val_smape: 1.8571

Epoch 11/64

3832/3832 - 45s - 12ms/step - ia: 0.2520 - loss: 0.9758 - mae: 0.7371 - rmse: 0.9196 - smape: 1.6028 - val_ia: 0.1912 - val_loss: 0.9176 - val_mae: 0.7135 - val_rmse: 0.7504 - val_smape: 1.8413

Epoch 12/64

3832/3832 - 37s - 10ms/step - ia: 0.2530 - loss: 0.9687 - mae: 0.7337 - rmse: 0.9188 - smape: 1.5944 - val_ia: 0.1918 - val_loss: 0.9100 - val_mae: 0.7101 - val_rmse: 0.7470 - val_smape: 1.8233

Epoch 13/64

3832/3832 - 30s - 8ms/step - ia: 0.2598 - loss: 0.9568 - mae: 0.7280 - rmse: 0.9099 - smape: 1.5820 - val_ia: 0.1925 - val_loss: 0.9013 - val_mae: 0.7062 - val_rmse: 0.7430 - val_smape: 1.8016

Epoch 14/64

3832/3832 - 25s - 6ms/step - ia: 0.2601 - loss: 0.9545 - mae: 0.7264 - rmse: 0.9098 - smape: 1.5758 - val_ia: 0.1933 - val_loss: 0.8918 - val_mae: 0.7020 - val_rmse: 0.7387 - val_smape: 1.7794

Epoch 15/64

3832/3832 - 24s - 6ms/step - ia: 0.2652 - loss: 0.9420 - mae: 0.7212 - rmse: 0.9033 - smape: 1.5670 - val_ia: 0.1942 - val_loss: 0.8811 - val_mae: 0.6970 - val_rmse: 0.7336 - val_smape: 1.7534

Epoch 16/64

3832/3832 - 24s - 6ms/step - ia: 0.2745 - loss: 0.9243 - mae: 0.7129 - rmse: 0.8936 - smape: 1.5463 - val_ia: 0.1952 - val_loss: 0.8691 - val_mae: 0.6913 - val_rmse: 0.7278 - val_smape: 1.7241

Epoch 17/64

3832/3832 - 24s - 6ms/step - ia: 0.2809 - loss: 0.9149 - mae: 0.7078 - rmse: 0.8889 - smape: 1.5291 - val_ia: 0.1963 - val_loss: 0.8560 - val_mae: 0.6853 - val_rmse: 0.7217 - val_smape: 1.6948

Epoch 18/64

3832/3832 - 24s - 6ms/step - ia: 0.2891 - loss: 0.8992 - mae: 0.7005 - rmse: 0.8795 - smape: 1.5106 - val_ia: 0.1976 - val_loss: 0.8414 - val_mae: 0.6785 - val_rmse: 0.7148 - val_smape: 1.6620

Epoch 19/64

3832/3832 - 41s - 11ms/step - ia: 0.2984 - loss: 0.8793 - mae: 0.6905 - rmse: 0.8686 - smape: 1.4851 - val_ia: 0.1990 - val_loss: 0.8254 - val_mae: 0.6713 - val_rmse: 0.7075 - val_smape: 1.6294

Epoch 20/64

3832/3832 - 24s - 6ms/step - ia: 0.3060 - loss: 0.8644 - mae: 0.6840 - rmse: 0.8610 - smape: 1.4672 - val_ia: 0.2007 - val_loss: 0.8078 - val_mae: 0.6629 - val_rmse: 0.6990 - val_smape: 1.5921

Epoch 21/64

3832/3832 - 38s - 10ms/step - ia: 0.3168 - loss: 0.8456 - mae: 0.6745 - rmse: 0.8504 - smape: 1.4443 - val_ia: 0.2027 - val_loss: 0.7887 - val_mae: 0.6538 - val_rmse: 0.6898 - val_smape: 1.5535

Epoch 22/64

3832/3832 - 50s - 13ms/step - ia: 0.3295 - loss: 0.8261 - mae: 0.6644 - rmse: 0.8395 - smape: 1.4141 - val_ia: 0.2050 - val_loss: 0.7680 - val_mae: 0.6437 - val_rmse: 0.6796 - val_smape: 1.5121

Epoch 23/64

3832/3832 - 31s - 8ms/step - ia: 0.3390 - loss: 0.8046 - mae: 0.6541 - rmse: 0.8301 - smape: 1.3879 - val_ia: 0.2074 - val_loss: 0.7455 - val_mae: 0.6324 - val_rmse: 0.6683 - val_smape: 1.4682

Epoch 24/64

3832/3832 - 34s - 9ms/step - ia: 0.3583 - loss: 0.7791 - mae: 0.6404 - rmse: 0.8137 - smape: 1.3535 - val_ia: 0.2099 - val_loss: 0.7216 - val_mae: 0.6206 - val_rmse: 0.6564 - val_smape: 1.4250

Epoch 25/64

3832/3832 - 30s - 8ms/step - ia: 0.3744 - loss: 0.7574 - mae: 0.6294 - rmse: 0.8018 - smape: 1.3213 - val_ia: 0.2126 - val_loss: 0.6962 - val_mae: 0.6078 - val_rmse: 0.6435 - val_smape: 1.3794

Epoch 26/64

3832/3832 - 28s - 7ms/step - ia: 0.3902 - loss: 0.7311 - mae: 0.6165 - rmse: 0.7862 - smape: 1.2863 - val_ia: 0.2156 - val_loss: 0.6691 - val_mae: 0.5929 - val_rmse: 0.6286 - val_smape: 1.3289

Epoch 27/64

3832/3832 - 25s - 7ms/step - ia: 0.4101 - loss: 0.7051 - mae: 0.6007 - rmse: 0.7706 - smape: 1.2486 - val_ia: 0.2192 - val_loss: 0.6410 - val_mae: 0.5776 - val_rmse: 0.6133 - val_smape: 1.2796

Epoch 28/64

3832/3832 - 27s - 7ms/step - ia: 0.4304 - loss: 0.6765 - mae: 0.5852 - rmse: 0.7535 - smape: 1.2099 - val_ia: 0.2232 - val_loss: 0.6117 - val_mae: 0.5613 - val_rmse: 0.5970 - val_smape: 1.2295

Epoch 29/64

3832/3832 - 27s - 7ms/step - ia: 0.4502 - loss: 0.6514 - mae: 0.5710 - rmse: 0.7364 - smape: 1.1719 - val_ia: 0.2275 - val_loss: 0.5818 - val_mae: 0.5438 - val_rmse: 0.5796 - val_smape: 1.1774

Epoch 30/64

3832/3832 - 27s - 7ms/step - ia: 0.4720 - loss: 0.6251 - mae: 0.5553 - rmse: 0.7206 - smape: 1.1367 - val_ia: 0.2322 - val_loss: 0.5514 - val_mae: 0.5253 - val_rmse: 0.5613 - val_smape: 1.1248

Epoch 31/64

3832/3832 - 27s - 7ms/step - ia: 0.4919 - loss: 0.5949 - mae: 0.5384 - rmse: 0.7031 - smape: 1.0935 - val_ia: 0.2366 - val_loss: 0.5218 - val_mae: 0.5077 - val_rmse: 0.5438 - val_smape: 1.0769

Epoch 32/64

3832/3832 - 26s - 7ms/step - ia: 0.5161 - loss: 0.5645 - mae: 0.5206 - rmse: 0.6827 - smape: 1.0556 - val_ia: 0.2417 - val_loss: 0.4925 - val_mae: 0.4894 - val_rmse: 0.5258 - val_smape: 1.0291

Epoch 33/64

3832/3832 - 26s - 7ms/step - ia: 0.5323 - loss: 0.5416 - mae: 0.5086 - rmse: 0.6681 - smape: 1.0276 - val_ia: 0.2476 - val_loss: 0.4640 - val_mae: 0.4700 - val_rmse: 0.5069 - val_smape: 0.9796

Epoch 34/64

3832/3832 - 26s - 7ms/step - ia: 0.5524 - loss: 0.5194 - mae: 0.4939 - rmse: 0.6532 - smape: 0.9907 - val_ia: 0.2529 - val_loss: 0.4378 - val_mae: 0.4523 - val_rmse: 0.4895 - val_smape: 0.9369

Epoch 35/64

3832/3832 - 26s - 7ms/step - ia: 0.5679 - loss: 0.4959 - mae: 0.4828 - rmse: 0.6376 - smape: 0.9647 - val_ia: 0.2586 - val_loss: 0.4133 - val_mae: 0.4344 - val_rmse: 0.4722 - val_smape: 0.8943

Epoch 36/64

3832/3832 - 26s - 7ms/step - ia: 0.5840 - loss: 0.4747 - mae: 0.4709 - rmse: 0.6241 - smape: 0.9365 - val_ia: 0.2644 - val_loss: 0.3913 - val_mae: 0.4196 - val_rmse: 0.4580 - val_smape: 0.8622

Epoch 37/64

3832/3832 - 26s - 7ms/step - ia: 0.5977 - loss: 0.4590 - mae: 0.4627 - rmse: 0.6139 - smape: 0.9188 - val_ia: 0.2702 - val_loss: 0.3715 - val_mae: 0.4052 - val_rmse: 0.4443 - val_smape: 0.8309

Epoch 38/64

3832/3832 - 26s - 7ms/step - ia: 0.6095 - loss: 0.4396 - mae: 0.4520 - rmse: 0.5997 - smape: 0.8929 - val_ia: 0.2765 - val_loss: 0.3535 - val_mae: 0.3906 - val_rmse: 0.4304 - val_smape: 0.7981

Epoch 39/64

3832/3832 - 41s - 11ms/step - ia: 0.6200 - loss: 0.4260 - mae: 0.4440 - rmse: 0.5900 - smape: 0.8759 - val_ia: 0.2814 - val_loss: 0.3380 - val_mae: 0.3789 - val_rmse: 0.4193 - val_smape: 0.7733

Epoch 40/64

3832/3832 - 27s - 7ms/step - ia: 0.6271 - loss: 0.4171 - mae: 0.4395 - rmse: 0.5838 - smape: 0.8624 - val_ia: 0.2860 - val_loss: 0.3246 - val_mae: 0.3686 - val_rmse: 0.4096 - val_smape: 0.7528

Epoch 41/64

3832/3832 - 26s - 7ms/step - ia: 0.6361 - loss: 0.4076 - mae: 0.4335 - rmse: 0.5761 - smape: 0.8463 - val_ia: 0.2899 - val_loss: 0.3131 - val_mae: 0.3596 - val_rmse: 0.4011 - val_smape: 0.7350

Epoch 42/64

3832/3832 - 41s - 11ms/step - ia: 0.6420 - loss: 0.3940 - mae: 0.4281 - rmse: 0.5684 - smape: 0.8376 - val_ia: 0.2924 - val_loss: 0.3032 - val_mae: 0.3530 - val_rmse: 0.3948 - val_smape: 0.7221

Epoch 43/64

3832/3832 - 26s - 7ms/step - ia: 0.6457 - loss: 0.3882 - mae: 0.4255 - rmse: 0.5629 - smape: 0.8305 - val_ia: 0.2952 - val_loss: 0.2945 - val_mae: 0.3464 - val_rmse: 0.3885 - val_smape: 0.7080

Epoch 44/64

3832/3832 - 41s - 11ms/step - ia: 0.6531 - loss: 0.3790 - mae: 0.4198 - rmse: 0.5572 - smape: 0.8167 - val_ia: 0.2972 - val_loss: 0.2870 - val_mae: 0.3411 - val_rmse: 0.3835 - val_smape: 0.6972

Epoch 45/64

3832/3832 - 26s - 7ms/step - ia: 0.6596 - loss: 0.3713 - mae: 0.4148 - rmse: 0.5499 - smape: 0.8044 - val_ia: 0.2992 - val_loss: 0.2803 - val_mae: 0.3358 - val_rmse: 0.3785 - val_smape: 0.6858

Epoch 46/64

3832/3832 - 27s - 7ms/step - ia: 0.6606 - loss: 0.3682 - mae: 0.4141 - rmse: 0.5485 - smape: 0.8059 - val_ia: 0.3006 - val_loss: 0.2745 - val_mae: 0.3318 - val_rmse: 0.3746 - val_smape: 0.6778

Epoch 47/64

3832/3832 - 27s - 7ms/step - ia: 0.6642 - loss: 0.3635 - mae: 0.4092 - rmse: 0.5435 - smape: 0.7942 - val_ia: 0.3016 - val_loss: 0.2692 - val_mae: 0.3284 - val_rmse: 0.3714 - val_smape: 0.6713

Epoch 48/64

3832/3832 - 26s - 7ms/step - ia: 0.6699 - loss: 0.3511 - mae: 0.4039 - rmse: 0.5359 - smape: 0.7873 - val_ia: 0.3025 - val_loss: 0.2644 - val_mae: 0.3254 - val_rmse: 0.3686 - val_smape: 0.6657

Epoch 49/64

3832/3832 - 41s - 11ms/step - ia: 0.6728 - loss: 0.3486 - mae: 0.4022 - rmse: 0.5329 - smape: 0.7841 - val_ia: 0.3035 - val_loss: 0.2603 - val_mae: 0.3224 - val_rmse: 0.3657 - val_smape: 0.6604

Epoch 50/64

3832/3832 - 25s - 7ms/step - ia: 0.6737 - loss: 0.3457 - mae: 0.3992 - rmse: 0.5297 - smape: 0.7796 - val_ia: 0.3041 - val_loss: 0.2563 - val_mae: 0.3201 - val_rmse: 0.3636 - val_smape: 0.6566

Epoch 51/64

3832/3832 - 25s - 7ms/step - ia: 0.6748 - loss: 0.3436 - mae: 0.4007 - rmse: 0.5299 - smape: 0.7837 - val_ia: 0.3047 - val_loss: 0.2528 - val_mae: 0.3179 - val_rmse: 0.3614 - val_smape: 0.6529

Epoch 52/64

3832/3832 - 26s - 7ms/step - ia: 0.6749 - loss: 0.3404 - mae: 0.3985 - rmse: 0.5284 - smape: 0.7759 - val_ia: 0.3049 - val_loss: 0.2494 - val_mae: 0.3164 - val_rmse: 0.3599 - val_smape: 0.6507

Epoch 53/64

3832/3832 - 24s - 6ms/step - ia: 0.6787 - loss: 0.3389 - mae: 0.3959 - rmse: 0.5248 - smape: 0.7733 - val_ia: 0.3060 - val_loss: 0.2463 - val_mae: 0.3139 - val_rmse: 0.3575 - val_smape: 0.6462

Epoch 54/64

3832/3832 - 24s - 6ms/step - ia: 0.6809 - loss: 0.3321 - mae: 0.3922 - rmse: 0.5204 - smape: 0.7682 - val_ia: 0.3067 - val_loss: 0.2434 - val_mae: 0.3121 - val_rmse: 0.3556 - val_smape: 0.6431

Epoch 55/64

3832/3832 - 46s - 12ms/step - ia: 0.6798 - loss: 0.3317 - mae: 0.3919 - rmse: 0.5204 - smape: 0.7656 - val_ia: 0.3073 - val_loss: 0.2406 - val_mae: 0.3105 - val_rmse: 0.3541 - val_smape: 0.6407

Epoch 56/64

3832/3832 - 38s - 10ms/step - ia: 0.6854 - loss: 0.3217 - mae: 0.3871 - rmse: 0.5118 - smape: 0.7622 - val_ia: 0.3068 - val_loss: 0.2381 - val_mae: 0.3100 - val_rmse: 0.3535 - val_smape: 0.6410

Epoch 57/64

3832/3832 - 25s - 7ms/step - ia: 0.6844 - loss: 0.3254 - mae: 0.3884 - rmse: 0.5150 - smape: 0.7631 - val_ia: 0.3077 - val_loss: 0.2356 - val_mae: 0.3083 - val_rmse: 0.3518 - val_smape: 0.6382

Epoch 58/64

3832/3832 - 25s - 7ms/step - ia: 0.6866 - loss: 0.3212 - mae: 0.3858 - rmse: 0.5124 - smape: 0.7575 - val_ia: 0.3088 - val_loss: 0.2331 - val_mae: 0.3065 - val_rmse: 0.3500 - val_smape: 0.6348

Epoch 59/64

3832/3832 - 25s - 7ms/step - ia: 0.6881 - loss: 0.3175 - mae: 0.3832 - rmse: 0.5087 - smape: 0.7523 - val_ia: 0.3090 - val_loss: 0.2308 - val_mae: 0.3056 - val_rmse: 0.3490 - val_smape: 0.6338

Epoch 60/64

3832/3832 - 25s - 7ms/step - ia: 0.6879 - loss: 0.3159 - mae: 0.3816 - rmse: 0.5068 - smape: 0.7517 - val_ia: 0.3093 - val_loss: 0.2286 - val_mae: 0.3045 - val_rmse: 0.3478 - val_smape: 0.6320

Epoch 61/64

3832/3832 - 26s - 7ms/step - ia: 0.6888 - loss: 0.3111 - mae: 0.3792 - rmse: 0.5029 - smape: 0.7497 - val_ia: 0.3104 - val_loss: 0.2265 - val_mae: 0.3028 - val_rmse: 0.3461 - val_smape: 0.6289

Epoch 62/64

3832/3832 - 26s - 7ms/step - ia: 0.6945 - loss: 0.3106 - mae: 0.3771 - rmse: 0.5023 - smape: 0.7429 - val_ia: 0.3106 - val_loss: 0.2244 - val_mae: 0.3019 - val_rmse: 0.3452 - val_smape: 0.6279

Epoch 63/64

3832/3832 - 27s - 7ms/step - ia: 0.6920 - loss: 0.3089 - mae: 0.3771 - rmse: 0.5013 - smape: 0.7442 - val_ia: 0.3111 - val_loss: 0.2224 - val_mae: 0.3008 - val_rmse: 0.3440 - val_smape: 0.6264

Epoch 64/64

3832/3832 - 29s - 8ms/step - ia: 0.6906 - loss: 0.3046 - mae: 0.3746 - rmse: 0.4970 - smape: 0.7429 - val_ia: 0.3120 - val_loss: 0.2204 - val_mae: 0.2993 - val_rmse: 0.3425 - val_smape: 0.6242

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:47 795ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 10%|█         | 5/50 [57:32<11:17:47, 903.72s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 16s - 17ms/step - ia: 0.2248 - loss: 0.9527 - mae: 0.7165 - rmse: 0.9520 - smape: 1.5821 - val_ia: 0.2674 - val_loss: 0.7569 - val_mae: 0.6353 - val_rmse: 0.7198 - val_smape: 1.4509

Epoch 2/128

958/958 - 9s - 9ms/step - ia: 0.4035 - loss: 0.6803 - mae: 0.5979 - rmse: 0.8020 - smape: 1.2748 - val_ia: 0.3006 - val_loss: 0.5394 - val_mae: 0.5383 - val_rmse: 0.6224 - val_smape: 1.1515

Epoch 3/128

958/958 - 9s - 9ms/step - ia: 0.5485 - loss: 0.5039 - mae: 0.5082 - rmse: 0.6915 - smape: 1.0394 - val_ia: 0.3374 - val_loss: 0.4009 - val_mae: 0.4546 - val_rmse: 0.5446 - val_smape: 0.9506

Epoch 4/128

958/958 - 11s - 11ms/step - ia: 0.6182 - loss: 0.4373 - mae: 0.4622 - rmse: 0.6429 - smape: 0.9309 - val_ia: 0.3641 - val_loss: 0.3592 - val_mae: 0.4179 - val_rmse: 0.5112 - val_smape: 0.8726

Epoch 5/128

958/958 - 11s - 12ms/step - ia: 0.6460 - loss: 0.4112 - mae: 0.4412 - rmse: 0.6212 - smape: 0.8836 - val_ia: 0.3831 - val_loss: 0.3371 - val_mae: 0.3984 - val_rmse: 0.4923 - val_smape: 0.8351

Epoch 6/128

958/958 - 10s - 10ms/step - ia: 0.6633 - loss: 0.3888 - mae: 0.4258 - rmse: 0.6055 - smape: 0.8554 - val_ia: 0.3985 - val_loss: 0.3199 - val_mae: 0.3842 - val_rmse: 0.4781 - val_smape: 0.8094

Epoch 7/128

958/958 - 10s - 10ms/step - ia: 0.6735 - loss: 0.3762 - mae: 0.4165 - rmse: 0.5946 - smape: 0.8374 - val_ia: 0.4103 - val_loss: 0.3069 - val_mae: 0.3747 - val_rmse: 0.4678 - val_smape: 0.7938

Epoch 8/128

958/958 - 10s - 10ms/step - ia: 0.6834 - loss: 0.3604 - mae: 0.4076 - rmse: 0.5818 - smape: 0.8215 - val_ia: 0.4204 - val_loss: 0.2962 - val_mae: 0.3678 - val_rmse: 0.4599 - val_smape: 0.7842

Epoch 9/128

958/958 - 9s - 9ms/step - ia: 0.6892 - loss: 0.3507 - mae: 0.4007 - rmse: 0.5733 - smape: 0.8105 - val_ia: 0.4297 - val_loss: 0.2850 - val_mae: 0.3602 - val_rmse: 0.4513 - val_smape: 0.7716

Epoch 10/128

958/958 - 9s - 9ms/step - ia: 0.6978 - loss: 0.3358 - mae: 0.3919 - rmse: 0.5616 - smape: 0.7963 - val_ia: 0.4373 - val_loss: 0.2758 - val_mae: 0.3543 - val_rmse: 0.4443 - val_smape: 0.7625

Epoch 11/128

958/958 - 11s - 11ms/step - ia: 0.7030 - loss: 0.3269 - mae: 0.3860 - rmse: 0.5531 - smape: 0.7900 - val_ia: 0.4462 - val_loss: 0.2663 - val_mae: 0.3478 - val_rmse: 0.4373 - val_smape: 0.7521

Epoch 12/128

958/958 - 9s - 9ms/step - ia: 0.7061 - loss: 0.3187 - mae: 0.3810 - rmse: 0.5459 - smape: 0.7800 - val_ia: 0.4531 - val_loss: 0.2570 - val_mae: 0.3414 - val_rmse: 0.4299 - val_smape: 0.7417

Epoch 13/128

958/958 - 10s - 11ms/step - ia: 0.7139 - loss: 0.3108 - mae: 0.3740 - rmse: 0.5374 - smape: 0.7675 - val_ia: 0.4593 - val_loss: 0.2489 - val_mae: 0.3366 - val_rmse: 0.4239 - val_smape: 0.7345

Epoch 14/128

958/958 - 9s - 9ms/step - ia: 0.7169 - loss: 0.2989 - mae: 0.3692 - rmse: 0.5283 - smape: 0.7621 - val_ia: 0.4681 - val_loss: 0.2408 - val_mae: 0.3306 - val_rmse: 0.4177 - val_smape: 0.7247

Epoch 15/128

958/958 - 9s - 9ms/step - ia: 0.7234 - loss: 0.2914 - mae: 0.3620 - rmse: 0.5219 - smape: 0.7502 - val_ia: 0.4736 - val_loss: 0.2336 - val_mae: 0.3262 - val_rmse: 0.4122 - val_smape: 0.7180

Epoch 16/128

958/958 - 11s - 11ms/step - ia: 0.7269 - loss: 0.2860 - mae: 0.3583 - rmse: 0.5168 - smape: 0.7420 - val_ia: 0.4825 - val_loss: 0.2257 - val_mae: 0.3198 - val_rmse: 0.4058 - val_smape: 0.7074

Epoch 17/128

958/958 - 10s - 10ms/step - ia: 0.7315 - loss: 0.2766 - mae: 0.3533 - rmse: 0.5086 - smape: 0.7318 - val_ia: 0.4888 - val_loss: 0.2190 - val_mae: 0.3147 - val_rmse: 0.4005 - val_smape: 0.6992

Epoch 18/128

958/958 - 9s - 9ms/step - ia: 0.7369 - loss: 0.2678 - mae: 0.3463 - rmse: 0.5002 - smape: 0.7230 - val_ia: 0.4922 - val_loss: 0.2135 - val_mae: 0.3119 - val_rmse: 0.3960 - val_smape: 0.6945

Epoch 19/128

958/958 - 8s - 9ms/step - ia: 0.7408 - loss: 0.2599 - mae: 0.3423 - rmse: 0.4928 - smape: 0.7148 - val_ia: 0.4999 - val_loss: 0.2075 - val_mae: 0.3067 - val_rmse: 0.3909 - val_smape: 0.6856

Epoch 20/128

958/958 - 9s - 9ms/step - ia: 0.7453 - loss: 0.2563 - mae: 0.3373 - rmse: 0.4893 - smape: 0.7075 - val_ia: 0.5050 - val_loss: 0.2026 - val_mae: 0.3032 - val_rmse: 0.3868 - val_smape: 0.6795

Epoch 21/128

958/958 - 10s - 10ms/step - ia: 0.7460 - loss: 0.2502 - mae: 0.3352 - rmse: 0.4831 - smape: 0.7062 - val_ia: 0.5117 - val_loss: 0.1982 - val_mae: 0.2990 - val_rmse: 0.3830 - val_smape: 0.6724

Epoch 22/128

958/958 - 7s - 7ms/step - ia: 0.7492 - loss: 0.2501 - mae: 0.3325 - rmse: 0.4819 - smape: 0.6975 - val_ia: 0.5190 - val_loss: 0.1937 - val_mae: 0.2944 - val_rmse: 0.3787 - val_smape: 0.6644

Epoch 23/128

958/958 - 7s - 8ms/step - ia: 0.7534 - loss: 0.2417 - mae: 0.3275 - rmse: 0.4752 - smape: 0.6916 - val_ia: 0.5235 - val_loss: 0.1902 - val_mae: 0.2917 - val_rmse: 0.3755 - val_smape: 0.6596

Epoch 24/128

958/958 - 9s - 9ms/step - ia: 0.7561 - loss: 0.2382 - mae: 0.3250 - rmse: 0.4706 - smape: 0.6867 - val_ia: 0.5277 - val_loss: 0.1872 - val_mae: 0.2889 - val_rmse: 0.3728 - val_smape: 0.6548

Epoch 25/128

958/958 - 8s - 9ms/step - ia: 0.7570 - loss: 0.2370 - mae: 0.3232 - rmse: 0.4685 - smape: 0.6822 - val_ia: 0.5321 - val_loss: 0.1845 - val_mae: 0.2863 - val_rmse: 0.3699 - val_smape: 0.6499

Epoch 26/128

958/958 - 8s - 9ms/step - ia: 0.7601 - loss: 0.2351 - mae: 0.3198 - rmse: 0.4673 - smape: 0.6755 - val_ia: 0.5358 - val_loss: 0.1818 - val_mae: 0.2839 - val_rmse: 0.3675 - val_smape: 0.6461

Epoch 27/128

958/958 - 7s - 7ms/step - ia: 0.7629 - loss: 0.2259 - mae: 0.3166 - rmse: 0.4582 - smape: 0.6713 - val_ia: 0.5413 - val_loss: 0.1788 - val_mae: 0.2806 - val_rmse: 0.3644 - val_smape: 0.6402

Epoch 28/128

958/958 - 7s - 7ms/step - ia: 0.7643 - loss: 0.2268 - mae: 0.3153 - rmse: 0.4586 - smape: 0.6697 - val_ia: 0.5430 - val_loss: 0.1766 - val_mae: 0.2791 - val_rmse: 0.3624 - val_smape: 0.6377

Epoch 29/128

958/958 - 8s - 9ms/step - ia: 0.7655 - loss: 0.2258 - mae: 0.3134 - rmse: 0.4565 - smape: 0.6665 - val_ia: 0.5459 - val_loss: 0.1747 - val_mae: 0.2774 - val_rmse: 0.3608 - val_smape: 0.6350

Epoch 30/128

958/958 - 9s - 9ms/step - ia: 0.7676 - loss: 0.2213 - mae: 0.3116 - rmse: 0.4532 - smape: 0.6629 - val_ia: 0.5509 - val_loss: 0.1722 - val_mae: 0.2745 - val_rmse: 0.3578 - val_smape: 0.6297

Epoch 31/128

958/958 - 9s - 9ms/step - ia: 0.7683 - loss: 0.2213 - mae: 0.3102 - rmse: 0.4516 - smape: 0.6576 - val_ia: 0.5544 - val_loss: 0.1702 - val_mae: 0.2725 - val_rmse: 0.3559 - val_smape: 0.6261

Epoch 32/128

958/958 - 10s - 10ms/step - ia: 0.7707 - loss: 0.2156 - mae: 0.3082 - rmse: 0.4469 - smape: 0.6534 - val_ia: 0.5580 - val_loss: 0.1685 - val_mae: 0.2705 - val_rmse: 0.3543 - val_smape: 0.6226

Epoch 33/128

958/958 - 8s - 9ms/step - ia: 0.7707 - loss: 0.2171 - mae: 0.3079 - rmse: 0.4475 - smape: 0.6527 - val_ia: 0.5573 - val_loss: 0.1675 - val_mae: 0.2705 - val_rmse: 0.3531 - val_smape: 0.6218

Epoch 34/128

958/958 - 8s - 9ms/step - ia: 0.7736 - loss: 0.2112 - mae: 0.3053 - rmse: 0.4429 - smape: 0.6506 - val_ia: 0.5599 - val_loss: 0.1653 - val_mae: 0.2685 - val_rmse: 0.3511 - val_smape: 0.6183

Epoch 35/128

958/958 - 8s - 8ms/step - ia: 0.7735 - loss: 0.2113 - mae: 0.3039 - rmse: 0.4427 - smape: 0.6498 - val_ia: 0.5655 - val_loss: 0.1635 - val_mae: 0.2659 - val_rmse: 0.3491 - val_smape: 0.6137

Epoch 36/128

958/958 - 8s - 9ms/step - ia: 0.7767 - loss: 0.2078 - mae: 0.3012 - rmse: 0.4381 - smape: 0.6445 - val_ia: 0.5670 - val_loss: 0.1620 - val_mae: 0.2647 - val_rmse: 0.3476 - val_smape: 0.6114

Epoch 37/128

958/958 - 9s - 9ms/step - ia: 0.7782 - loss: 0.2055 - mae: 0.2996 - rmse: 0.4361 - smape: 0.6432 - val_ia: 0.5695 - val_loss: 0.1601 - val_mae: 0.2630 - val_rmse: 0.3455 - val_smape: 0.6086

Epoch 38/128

958/958 - 9s - 9ms/step - ia: 0.7794 - loss: 0.2071 - mae: 0.2988 - rmse: 0.4365 - smape: 0.6387 - val_ia: 0.5705 - val_loss: 0.1587 - val_mae: 0.2620 - val_rmse: 0.3443 - val_smape: 0.6068

Epoch 39/128

958/958 - 9s - 9ms/step - ia: 0.7801 - loss: 0.2018 - mae: 0.2963 - rmse: 0.4311 - smape: 0.6369 - val_ia: 0.5722 - val_loss: 0.1569 - val_mae: 0.2603 - val_rmse: 0.3423 - val_smape: 0.6042

Epoch 40/128

958/958 - 9s - 9ms/step - ia: 0.7804 - loss: 0.2021 - mae: 0.2965 - rmse: 0.4318 - smape: 0.6371 - val_ia: 0.5761 - val_loss: 0.1555 - val_mae: 0.2586 - val_rmse: 0.3410 - val_smape: 0.6015

Epoch 41/128

958/958 - 9s - 9ms/step - ia: 0.7823 - loss: 0.2008 - mae: 0.2948 - rmse: 0.4296 - smape: 0.6317 - val_ia: 0.5750 - val_loss: 0.1547 - val_mae: 0.2587 - val_rmse: 0.3405 - val_smape: 0.6010

Epoch 42/128

958/958 - 10s - 11ms/step - ia: 0.7816 - loss: 0.1991 - mae: 0.2947 - rmse: 0.4293 - smape: 0.6348 - val_ia: 0.5776 - val_loss: 0.1535 - val_mae: 0.2573 - val_rmse: 0.3389 - val_smape: 0.5987

Epoch 43/128

958/958 - 9s - 9ms/step - ia: 0.7838 - loss: 0.1971 - mae: 0.2932 - rmse: 0.4265 - smape: 0.6321 - val_ia: 0.5815 - val_loss: 0.1515 - val_mae: 0.2549 - val_rmse: 0.3368 - val_smape: 0.5949

Epoch 44/128

958/958 - 11s - 11ms/step - ia: 0.7850 - loss: 0.1964 - mae: 0.2920 - rmse: 0.4256 - smape: 0.6280 - val_ia: 0.5830 - val_loss: 0.1502 - val_mae: 0.2537 - val_rmse: 0.3355 - val_smape: 0.5931

Epoch 45/128

958/958 - 8s - 9ms/step - ia: 0.7863 - loss: 0.1938 - mae: 0.2902 - rmse: 0.4232 - smape: 0.6277 - val_ia: 0.5866 - val_loss: 0.1490 - val_mae: 0.2521 - val_rmse: 0.3341 - val_smape: 0.5903

Epoch 46/128

958/958 - 8s - 9ms/step - ia: 0.7862 - loss: 0.1946 - mae: 0.2901 - rmse: 0.4234 - smape: 0.6242 - val_ia: 0.5841 - val_loss: 0.1480 - val_mae: 0.2524 - val_rmse: 0.3331 - val_smape: 0.5906

Epoch 47/128

958/958 - 9s - 9ms/step - ia: 0.7873 - loss: 0.1890 - mae: 0.2872 - rmse: 0.4178 - smape: 0.6227 - val_ia: 0.5904 - val_loss: 0.1465 - val_mae: 0.2496 - val_rmse: 0.3317 - val_smape: 0.5864

Epoch 48/128

958/958 - 9s - 9ms/step - ia: 0.7887 - loss: 0.1902 - mae: 0.2869 - rmse: 0.4184 - smape: 0.6212 - val_ia: 0.5918 - val_loss: 0.1450 - val_mae: 0.2483 - val_rmse: 0.3300 - val_smape: 0.5843

Epoch 49/128

958/958 - 9s - 9ms/step - ia: 0.7883 - loss: 0.1881 - mae: 0.2865 - rmse: 0.4170 - smape: 0.6210 - val_ia: 0.5944 - val_loss: 0.1439 - val_mae: 0.2470 - val_rmse: 0.3286 - val_smape: 0.5817

Epoch 50/128

958/958 - 8s - 9ms/step - ia: 0.7896 - loss: 0.1891 - mae: 0.2857 - rmse: 0.4181 - smape: 0.6165 - val_ia: 0.5927 - val_loss: 0.1429 - val_mae: 0.2470 - val_rmse: 0.3276 - val_smape: 0.5817

Epoch 51/128

958/958 - 8s - 9ms/step - ia: 0.7918 - loss: 0.1829 - mae: 0.2825 - rmse: 0.4100 - smape: 0.6139 - val_ia: 0.5968 - val_loss: 0.1416 - val_mae: 0.2451 - val_rmse: 0.3262 - val_smape: 0.5788

Epoch 52/128

958/958 - 9s - 9ms/step - ia: 0.7907 - loss: 0.1871 - mae: 0.2839 - rmse: 0.4154 - smape: 0.6134 - val_ia: 0.5976 - val_loss: 0.1406 - val_mae: 0.2443 - val_rmse: 0.3250 - val_smape: 0.5775

Epoch 53/128

958/958 - 10s - 11ms/step - ia: 0.7938 - loss: 0.1822 - mae: 0.2806 - rmse: 0.4096 - smape: 0.6081 - val_ia: 0.6000 - val_loss: 0.1393 - val_mae: 0.2428 - val_rmse: 0.3235 - val_smape: 0.5748

Epoch 54/128

958/958 - 9s - 9ms/step - ia: 0.7947 - loss: 0.1828 - mae: 0.2795 - rmse: 0.4102 - smape: 0.6077 - val_ia: 0.6010 - val_loss: 0.1381 - val_mae: 0.2420 - val_rmse: 0.3223 - val_smape: 0.5735

Epoch 55/128

958/958 - 8s - 9ms/step - ia: 0.7954 - loss: 0.1790 - mae: 0.2783 - rmse: 0.4068 - smape: 0.6070 - val_ia: 0.6028 - val_loss: 0.1369 - val_mae: 0.2407 - val_rmse: 0.3212 - val_smape: 0.5719

Epoch 56/128

958/958 - 11s - 12ms/step - ia: 0.7964 - loss: 0.1769 - mae: 0.2771 - rmse: 0.4033 - smape: 0.6055 - val_ia: 0.6036 - val_loss: 0.1358 - val_mae: 0.2397 - val_rmse: 0.3199 - val_smape: 0.5702

Epoch 57/128

958/958 - 8s - 9ms/step - ia: 0.7958 - loss: 0.1790 - mae: 0.2773 - rmse: 0.4058 - smape: 0.6038 - val_ia: 0.6050 - val_loss: 0.1346 - val_mae: 0.2387 - val_rmse: 0.3186 - val_smape: 0.5686

Epoch 58/128

958/958 - 9s - 9ms/step - ia: 0.7969 - loss: 0.1774 - mae: 0.2760 - rmse: 0.4025 - smape: 0.6050 - val_ia: 0.6058 - val_loss: 0.1338 - val_mae: 0.2381 - val_rmse: 0.3175 - val_smape: 0.5670

Epoch 59/128

958/958 - 12s - 12ms/step - ia: 0.7981 - loss: 0.1752 - mae: 0.2758 - rmse: 0.4024 - smape: 0.6018 - val_ia: 0.6067 - val_loss: 0.1331 - val_mae: 0.2375 - val_rmse: 0.3167 - val_smape: 0.5659

Epoch 60/128

958/958 - 19s - 20ms/step - ia: 0.7987 - loss: 0.1750 - mae: 0.2742 - rmse: 0.4006 - smape: 0.5982 - val_ia: 0.6076 - val_loss: 0.1320 - val_mae: 0.2367 - val_rmse: 0.3155 - val_smape: 0.5643

Epoch 61/128

958/958 - 10s - 11ms/step - ia: 0.7988 - loss: 0.1730 - mae: 0.2734 - rmse: 0.3984 - smape: 0.5989 - val_ia: 0.6117 - val_loss: 0.1306 - val_mae: 0.2344 - val_rmse: 0.3141 - val_smape: 0.5611

Epoch 62/128

958/958 - 9s - 10ms/step - ia: 0.8010 - loss: 0.1703 - mae: 0.2716 - rmse: 0.3961 - smape: 0.5960 - val_ia: 0.6118 - val_loss: 0.1297 - val_mae: 0.2339 - val_rmse: 0.3129 - val_smape: 0.5602

Epoch 63/128

958/958 - 9s - 10ms/step - ia: 0.8007 - loss: 0.1692 - mae: 0.2722 - rmse: 0.3947 - smape: 0.5969 - val_ia: 0.6123 - val_loss: 0.1287 - val_mae: 0.2332 - val_rmse: 0.3119 - val_smape: 0.5589

Epoch 64/128

958/958 - 11s - 11ms/step - ia: 0.8008 - loss: 0.1712 - mae: 0.2724 - rmse: 0.3960 - smape: 0.5983 - val_ia: 0.6150 - val_loss: 0.1276 - val_mae: 0.2318 - val_rmse: 0.3105 - val_smape: 0.5565

Epoch 65/128

958/958 - 9s - 10ms/step - ia: 0.8025 - loss: 0.1694 - mae: 0.2700 - rmse: 0.3940 - smape: 0.5920 - val_ia: 0.6167 - val_loss: 0.1266 - val_mae: 0.2307 - val_rmse: 0.3093 - val_smape: 0.5548

Epoch 66/128

958/958 - 10s - 11ms/step - ia: 0.8039 - loss: 0.1661 - mae: 0.2682 - rmse: 0.3907 - smape: 0.5898 - val_ia: 0.6180 - val_loss: 0.1257 - val_mae: 0.2297 - val_rmse: 0.3086 - val_smape: 0.5536

Epoch 67/128

958/958 - 9s - 10ms/step - ia: 0.8049 - loss: 0.1642 - mae: 0.2664 - rmse: 0.3891 - smape: 0.5883 - val_ia: 0.6174 - val_loss: 0.1247 - val_mae: 0.2292 - val_rmse: 0.3073 - val_smape: 0.5525

Epoch 68/128

958/958 - 10s - 11ms/step - ia: 0.8043 - loss: 0.1655 - mae: 0.2673 - rmse: 0.3899 - smape: 0.5874 - val_ia: 0.6214 - val_loss: 0.1236 - val_mae: 0.2274 - val_rmse: 0.3061 - val_smape: 0.5501

Epoch 69/128

958/958 - 11s - 11ms/step - ia: 0.8051 - loss: 0.1641 - mae: 0.2663 - rmse: 0.3875 - smape: 0.5861 - val_ia: 0.6216 - val_loss: 0.1229 - val_mae: 0.2270 - val_rmse: 0.3053 - val_smape: 0.5492

Epoch 70/128

958/958 - 9s - 9ms/step - ia: 0.8063 - loss: 0.1614 - mae: 0.2650 - rmse: 0.3865 - smape: 0.5842 - val_ia: 0.6220 - val_loss: 0.1218 - val_mae: 0.2262 - val_rmse: 0.3037 - val_smape: 0.5476

Epoch 71/128

958/958 - 9s - 10ms/step - ia: 0.8063 - loss: 0.1620 - mae: 0.2644 - rmse: 0.3864 - smape: 0.5845 - val_ia: 0.6253 - val_loss: 0.1209 - val_mae: 0.2246 - val_rmse: 0.3027 - val_smape: 0.5453

Epoch 72/128

958/958 - 10s - 10ms/step - ia: 0.8068 - loss: 0.1626 - mae: 0.2638 - rmse: 0.3859 - smape: 0.5812 - val_ia: 0.6270 - val_loss: 0.1201 - val_mae: 0.2237 - val_rmse: 0.3017 - val_smape: 0.5438

Epoch 73/128

958/958 - 9s - 10ms/step - ia: 0.8103 - loss: 0.1580 - mae: 0.2603 - rmse: 0.3808 - smape: 0.5764 - val_ia: 0.6279 - val_loss: 0.1190 - val_mae: 0.2226 - val_rmse: 0.3004 - val_smape: 0.5422

Epoch 74/128

958/958 - 9s - 10ms/step - ia: 0.8081 - loss: 0.1590 - mae: 0.2620 - rmse: 0.3823 - smape: 0.5816 - val_ia: 0.6293 - val_loss: 0.1183 - val_mae: 0.2220 - val_rmse: 0.2996 - val_smape: 0.5411

Epoch 75/128

958/958 - 10s - 10ms/step - ia: 0.8097 - loss: 0.1584 - mae: 0.2613 - rmse: 0.3813 - smape: 0.5766 - val_ia: 0.6286 - val_loss: 0.1175 - val_mae: 0.2214 - val_rmse: 0.2989 - val_smape: 0.5408

Epoch 76/128

958/958 - 8s - 8ms/step - ia: 0.8100 - loss: 0.1566 - mae: 0.2595 - rmse: 0.3789 - smape: 0.5746 - val_ia: 0.6313 - val_loss: 0.1165 - val_mae: 0.2201 - val_rmse: 0.2975 - val_smape: 0.5384

Epoch 77/128

958/958 - 6s - 7ms/step - ia: 0.8111 - loss: 0.1552 - mae: 0.2588 - rmse: 0.3775 - smape: 0.5740 - val_ia: 0.6310 - val_loss: 0.1158 - val_mae: 0.2199 - val_rmse: 0.2963 - val_smape: 0.5375

Epoch 78/128

958/958 - 9s - 9ms/step - ia: 0.8104 - loss: 0.1572 - mae: 0.2594 - rmse: 0.3782 - smape: 0.5741 - val_ia: 0.6331 - val_loss: 0.1152 - val_mae: 0.2190 - val_rmse: 0.2959 - val_smape: 0.5363

Epoch 79/128

958/958 - 10s - 11ms/step - ia: 0.8119 - loss: 0.1537 - mae: 0.2574 - rmse: 0.3751 - smape: 0.5716 - val_ia: 0.6368 - val_loss: 0.1142 - val_mae: 0.2170 - val_rmse: 0.2945 - val_smape: 0.5332

Epoch 80/128

958/958 - 7s - 7ms/step - ia: 0.8122 - loss: 0.1542 - mae: 0.2579 - rmse: 0.3753 - smape: 0.5716 - val_ia: 0.6365 - val_loss: 0.1134 - val_mae: 0.2166 - val_rmse: 0.2935 - val_smape: 0.5326

Epoch 81/128

958/958 - 7s - 8ms/step - ia: 0.8136 - loss: 0.1523 - mae: 0.2561 - rmse: 0.3735 - smape: 0.5702 - val_ia: 0.6378 - val_loss: 0.1125 - val_mae: 0.2155 - val_rmse: 0.2924 - val_smape: 0.5311

Epoch 82/128

958/958 - 12s - 12ms/step - ia: 0.8135 - loss: 0.1520 - mae: 0.2566 - rmse: 0.3739 - smape: 0.5707 - val_ia: 0.6373 - val_loss: 0.1120 - val_mae: 0.2154 - val_rmse: 0.2918 - val_smape: 0.5306

Epoch 83/128

958/958 - 10s - 11ms/step - ia: 0.8135 - loss: 0.1509 - mae: 0.2559 - rmse: 0.3721 - smape: 0.5699 - val_ia: 0.6397 - val_loss: 0.1113 - val_mae: 0.2143 - val_rmse: 0.2908 - val_smape: 0.5288

Epoch 84/128

958/958 - 9s - 9ms/step - ia: 0.8148 - loss: 0.1479 - mae: 0.2540 - rmse: 0.3690 - smape: 0.5685 - val_ia: 0.6405 - val_loss: 0.1105 - val_mae: 0.2136 - val_rmse: 0.2898 - val_smape: 0.5273

Epoch 85/128

958/958 - 9s - 9ms/step - ia: 0.8145 - loss: 0.1509 - mae: 0.2549 - rmse: 0.3720 - smape: 0.5651 - val_ia: 0.6403 - val_loss: 0.1103 - val_mae: 0.2137 - val_rmse: 0.2894 - val_smape: 0.5267

Epoch 86/128

958/958 - 9s - 10ms/step - ia: 0.8158 - loss: 0.1484 - mae: 0.2526 - rmse: 0.3685 - smape: 0.5623 - val_ia: 0.6438 - val_loss: 0.1090 - val_mae: 0.2115 - val_rmse: 0.2879 - val_smape: 0.5240

Epoch 87/128

958/958 - 9s - 10ms/step - ia: 0.8169 - loss: 0.1464 - mae: 0.2510 - rmse: 0.3655 - smape: 0.5617 - val_ia: 0.6438 - val_loss: 0.1083 - val_mae: 0.2110 - val_rmse: 0.2870 - val_smape: 0.5230

Epoch 88/128

958/958 - 10s - 11ms/step - ia: 0.8172 - loss: 0.1468 - mae: 0.2510 - rmse: 0.3656 - smape: 0.5616 - val_ia: 0.6447 - val_loss: 0.1078 - val_mae: 0.2105 - val_rmse: 0.2864 - val_smape: 0.5221

Epoch 89/128

958/958 - 9s - 10ms/step - ia: 0.8162 - loss: 0.1487 - mae: 0.2520 - rmse: 0.3683 - smape: 0.5620 - val_ia: 0.6471 - val_loss: 0.1069 - val_mae: 0.2091 - val_rmse: 0.2851 - val_smape: 0.5201

Epoch 90/128

958/958 - 8s - 9ms/step - ia: 0.8189 - loss: 0.1451 - mae: 0.2492 - rmse: 0.3644 - smape: 0.5574 - val_ia: 0.6461 - val_loss: 0.1062 - val_mae: 0.2091 - val_rmse: 0.2842 - val_smape: 0.5195

Epoch 91/128

958/958 - 11s - 12ms/step - ia: 0.8189 - loss: 0.1429 - mae: 0.2481 - rmse: 0.3619 - smape: 0.5573 - val_ia: 0.6479 - val_loss: 0.1055 - val_mae: 0.2080 - val_rmse: 0.2833 - val_smape: 0.5181

Epoch 92/128

958/958 - 9s - 9ms/step - ia: 0.8182 - loss: 0.1450 - mae: 0.2499 - rmse: 0.3640 - smape: 0.5558 - val_ia: 0.6484 - val_loss: 0.1049 - val_mae: 0.2075 - val_rmse: 0.2827 - val_smape: 0.5175

Epoch 93/128

958/958 - 8s - 9ms/step - ia: 0.8182 - loss: 0.1449 - mae: 0.2500 - rmse: 0.3642 - smape: 0.5574 - val_ia: 0.6489 - val_loss: 0.1045 - val_mae: 0.2073 - val_rmse: 0.2819 - val_smape: 0.5164

Epoch 94/128

958/958 - 9s - 10ms/step - ia: 0.8209 - loss: 0.1415 - mae: 0.2465 - rmse: 0.3602 - smape: 0.5546 - val_ia: 0.6503 - val_loss: 0.1040 - val_mae: 0.2065 - val_rmse: 0.2813 - val_smape: 0.5152

Epoch 95/128

958/958 - 10s - 11ms/step - ia: 0.8186 - loss: 0.1414 - mae: 0.2477 - rmse: 0.3604 - smape: 0.5563 - val_ia: 0.6509 - val_loss: 0.1033 - val_mae: 0.2057 - val_rmse: 0.2803 - val_smape: 0.5138

Epoch 96/128

958/958 - 9s - 10ms/step - ia: 0.8203 - loss: 0.1428 - mae: 0.2469 - rmse: 0.3603 - smape: 0.5546 - val_ia: 0.6543 - val_loss: 0.1027 - val_mae: 0.2042 - val_rmse: 0.2796 - val_smape: 0.5119

Epoch 97/128

958/958 - 10s - 11ms/step - ia: 0.8212 - loss: 0.1408 - mae: 0.2460 - rmse: 0.3589 - smape: 0.5521 - val_ia: 0.6535 - val_loss: 0.1022 - val_mae: 0.2043 - val_rmse: 0.2788 - val_smape: 0.5112

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 7s - 60ms/step - ia: 0.8173 - loss: 0.1578 - mae: 0.2539 - rmse: 0.3823 - smape: 0.5520 - val_ia: 0.8631 - val_loss: 0.0637 - val_mae: 0.1512 - val_rmse: 0.2369 - val_smape: 0.3919

Epoch 2/128

120/120 - 2s - 16ms/step - ia: 0.8609 - loss: 0.1016 - mae: 0.2017 - rmse: 0.3154 - smape: 0.4493 - val_ia: 0.8806 - val_loss: 0.0603 - val_mae: 0.1376 - val_rmse: 0.2269 - val_smape: 0.3609

Epoch 3/128

120/120 - 2s - 17ms/step - ia: 0.8666 - loss: 0.0945 - mae: 0.1939 - rmse: 0.3039 - smape: 0.4345 - val_ia: 0.8627 - val_loss: 0.0643 - val_mae: 0.1533 - val_rmse: 0.2355 - val_smape: 0.3823

Epoch 4/128

120/120 - 2s - 15ms/step - ia: 0.8683 - loss: 0.0931 - mae: 0.1913 - rmse: 0.3012 - smape: 0.4305 - val_ia: 0.8758 - val_loss: 0.0586 - val_mae: 0.1396 - val_rmse: 0.2253 - val_smape: 0.3671

Epoch 5/128

120/120 - 3s - 23ms/step - ia: 0.8680 - loss: 0.0927 - mae: 0.1915 - rmse: 0.3012 - smape: 0.4303 - val_ia: 0.8692 - val_loss: 0.0623 - val_mae: 0.1491 - val_rmse: 0.2339 - val_smape: 0.3756

Epoch 6/128

120/120 - 2s - 16ms/step - ia: 0.8695 - loss: 0.0895 - mae: 0.1901 - rmse: 0.2963 - smape: 0.4269 - val_ia: 0.8690 - val_loss: 0.0589 - val_mae: 0.1436 - val_rmse: 0.2264 - val_smape: 0.3693

Epoch 7/128

120/120 - 2s - 16ms/step - ia: 0.8706 - loss: 0.0875 - mae: 0.1880 - rmse: 0.2927 - smape: 0.4236 - val_ia: 0.8803 - val_loss: 0.0566 - val_mae: 0.1348 - val_rmse: 0.2217 - val_smape: 0.3550

Epoch 8/128

120/120 - 3s - 21ms/step - ia: 0.8699 - loss: 0.0899 - mae: 0.1887 - rmse: 0.2961 - smape: 0.4265 - val_ia: 0.8760 - val_loss: 0.0572 - val_mae: 0.1399 - val_rmse: 0.2231 - val_smape: 0.3678

Epoch 9/128

120/120 - 2s - 15ms/step - ia: 0.8703 - loss: 0.0895 - mae: 0.1883 - rmse: 0.2962 - smape: 0.4249 - val_ia: 0.8878 - val_loss: 0.0544 - val_mae: 0.1289 - val_rmse: 0.2184 - val_smape: 0.3491

Epoch 10/128

120/120 - 3s - 23ms/step - ia: 0.8714 - loss: 0.0872 - mae: 0.1871 - rmse: 0.2920 - smape: 0.4237 - val_ia: 0.8840 - val_loss: 0.0556 - val_mae: 0.1337 - val_rmse: 0.2190 - val_smape: 0.3524

Epoch 11/128

120/120 - 2s - 17ms/step - ia: 0.8703 - loss: 0.0891 - mae: 0.1882 - rmse: 0.2960 - smape: 0.4208 - val_ia: 0.8816 - val_loss: 0.0540 - val_mae: 0.1323 - val_rmse: 0.2175 - val_smape: 0.3578

Epoch 12/128

120/120 - 2s - 16ms/step - ia: 0.8717 - loss: 0.0872 - mae: 0.1868 - rmse: 0.2918 - smape: 0.4204 - val_ia: 0.8848 - val_loss: 0.0550 - val_mae: 0.1322 - val_rmse: 0.2195 - val_smape: 0.3568

Epoch 13/128

120/120 - 3s - 21ms/step - ia: 0.8731 - loss: 0.0856 - mae: 0.1845 - rmse: 0.2888 - smape: 0.4171 - val_ia: 0.8812 - val_loss: 0.0587 - val_mae: 0.1369 - val_rmse: 0.2243 - val_smape: 0.3514

Epoch 14/128

120/120 - 3s - 23ms/step - ia: 0.8724 - loss: 0.0863 - mae: 0.1855 - rmse: 0.2908 - smape: 0.4178 - val_ia: 0.8709 - val_loss: 0.0609 - val_mae: 0.1467 - val_rmse: 0.2276 - val_smape: 0.3706

Epoch 15/128

120/120 - 2s - 16ms/step - ia: 0.8678 - loss: 0.0948 - mae: 0.1920 - rmse: 0.3036 - smape: 0.4248 - val_ia: 0.8754 - val_loss: 0.0566 - val_mae: 0.1406 - val_rmse: 0.2222 - val_smape: 0.3641

Epoch 16/128

120/120 - 3s - 23ms/step - ia: 0.8697 - loss: 0.0903 - mae: 0.1894 - rmse: 0.2976 - smape: 0.4249 - val_ia: 0.8691 - val_loss: 0.0618 - val_mae: 0.1454 - val_rmse: 0.2302 - val_smape: 0.3687

Epoch 17/128

120/120 - 3s - 21ms/step - ia: 0.8715 - loss: 0.0865 - mae: 0.1867 - rmse: 0.2909 - smape: 0.4217 - val_ia: 0.8864 - val_loss: 0.0563 - val_mae: 0.1318 - val_rmse: 0.2199 - val_smape: 0.3490

Epoch 18/128

120/120 - 2s - 15ms/step - ia: 0.8715 - loss: 0.0858 - mae: 0.1868 - rmse: 0.2902 - smape: 0.4206 - val_ia: 0.8804 - val_loss: 0.0538 - val_mae: 0.1355 - val_rmse: 0.2171 - val_smape: 0.3596

Epoch 19/128

120/120 - 3s - 23ms/step - ia: 0.8729 - loss: 0.0850 - mae: 0.1849 - rmse: 0.2883 - smape: 0.4167 - val_ia: 0.8850 - val_loss: 0.0543 - val_mae: 0.1309 - val_rmse: 0.2168 - val_smape: 0.3533

Epoch 20/128

120/120 - 2s - 16ms/step - ia: 0.8735 - loss: 0.0839 - mae: 0.1842 - rmse: 0.2865 - smape: 0.4163 - val_ia: 0.8788 - val_loss: 0.0577 - val_mae: 0.1401 - val_rmse: 0.2227 - val_smape: 0.3605

Epoch 21/128

120/120 - 2s - 16ms/step - ia: 0.8716 - loss: 0.0858 - mae: 0.1868 - rmse: 0.2899 - smape: 0.4180 - val_ia: 0.8782 - val_loss: 0.0646 - val_mae: 0.1439 - val_rmse: 0.2312 - val_smape: 0.3601

Epoch 22/128

120/120 - 2s - 16ms/step - ia: 0.8729 - loss: 0.0853 - mae: 0.1850 - rmse: 0.2886 - smape: 0.4171 - val_ia: 0.8701 - val_loss: 0.0571 - val_mae: 0.1432 - val_rmse: 0.2235 - val_smape: 0.3687

Epoch 23/128

120/120 - 2s - 16ms/step - ia: 0.8739 - loss: 0.0843 - mae: 0.1833 - rmse: 0.2872 - smape: 0.4140 - val_ia: 0.8872 - val_loss: 0.0532 - val_mae: 0.1296 - val_rmse: 0.2151 - val_smape: 0.3495

Epoch 24/128

120/120 - 2s - 16ms/step - ia: 0.8752 - loss: 0.0826 - mae: 0.1817 - rmse: 0.2853 - smape: 0.4121 - val_ia: 0.8721 - val_loss: 0.0602 - val_mae: 0.1452 - val_rmse: 0.2263 - val_smape: 0.3672

Epoch 25/128

120/120 - 2s - 16ms/step - ia: 0.8744 - loss: 0.0861 - mae: 0.1828 - rmse: 0.2902 - smape: 0.4118 - val_ia: 0.8779 - val_loss: 0.0608 - val_mae: 0.1409 - val_rmse: 0.2273 - val_smape: 0.3644

Epoch 26/128

120/120 - 2s - 16ms/step - ia: 0.8738 - loss: 0.0831 - mae: 0.1839 - rmse: 0.2854 - smape: 0.4163 - val_ia: 0.8805 - val_loss: 0.0582 - val_mae: 0.1382 - val_rmse: 0.2223 - val_smape: 0.3561

Epoch 27/128

120/120 - 2s - 17ms/step - ia: 0.8761 - loss: 0.0820 - mae: 0.1806 - rmse: 0.2832 - smape: 0.4123 - val_ia: 0.8732 - val_loss: 0.0544 - val_mae: 0.1393 - val_rmse: 0.2177 - val_smape: 0.3654

Epoch 28/128

120/120 - 2s - 16ms/step - ia: 0.8746 - loss: 0.0831 - mae: 0.1825 - rmse: 0.2857 - smape: 0.4125 - val_ia: 0.8680 - val_loss: 0.0574 - val_mae: 0.1456 - val_rmse: 0.2238 - val_smape: 0.3734

Epoch 29/128

120/120 - 2s - 16ms/step - ia: 0.8753 - loss: 0.0809 - mae: 0.1814 - rmse: 0.2824 - smape: 0.4123 - val_ia: 0.8794 - val_loss: 0.0559 - val_mae: 0.1393 - val_rmse: 0.2192 - val_smape: 0.3592

Epoch 30/128

120/120 - 2s - 17ms/step - ia: 0.8750 - loss: 0.0814 - mae: 0.1822 - rmse: 0.2829 - smape: 0.4110 - val_ia: 0.8862 - val_loss: 0.0542 - val_mae: 0.1320 - val_rmse: 0.2163 - val_smape: 0.3547

Epoch 31/128

120/120 - 2s - 15ms/step - ia: 0.8752 - loss: 0.0816 - mae: 0.1814 - rmse: 0.2826 - smape: 0.4126 - val_ia: 0.8852 - val_loss: 0.0535 - val_mae: 0.1313 - val_rmse: 0.2146 - val_smape: 0.3505

Epoch 32/128

120/120 - 3s - 22ms/step - ia: 0.8748 - loss: 0.0819 - mae: 0.1823 - rmse: 0.2830 - smape: 0.4132 - val_ia: 0.8712 - val_loss: 0.0568 - val_mae: 0.1444 - val_rmse: 0.2233 - val_smape: 0.3751

Epoch 33/128

120/120 - 3s - 21ms/step - ia: 0.8753 - loss: 0.0821 - mae: 0.1816 - rmse: 0.2839 - smape: 0.4122 - val_ia: 0.8870 - val_loss: 0.0538 - val_mae: 0.1304 - val_rmse: 0.2156 - val_smape: 0.3504

Epoch 34/128

120/120 - 3s - 23ms/step - ia: 0.8753 - loss: 0.0827 - mae: 0.1816 - rmse: 0.2841 - smape: 0.4107 - val_ia: 0.8795 - val_loss: 0.0549 - val_mae: 0.1356 - val_rmse: 0.2185 - val_smape: 0.3561

Epoch 35/128

120/120 - 3s - 21ms/step - ia: 0.8748 - loss: 0.0829 - mae: 0.1822 - rmse: 0.2842 - smape: 0.4134 - val_ia: 0.8822 - val_loss: 0.0536 - val_mae: 0.1334 - val_rmse: 0.2155 - val_smape: 0.3544

Epoch 36/128

120/120 - 2s - 16ms/step - ia: 0.8753 - loss: 0.0819 - mae: 0.1812 - rmse: 0.2830 - smape: 0.4108 - val_ia: 0.8695 - val_loss: 0.0625 - val_mae: 0.1491 - val_rmse: 0.2290 - val_smape: 0.3675

Epoch 37/128

120/120 - 2s - 16ms/step - ia: 0.8630 - loss: 0.1436 - mae: 0.1979 - rmse: 0.3342 - smape: 0.4273 - val_ia: 0.7510 - val_loss: 0.3333 - val_mae: 0.3086 - val_rmse: 0.4457 - val_smape: 0.5720

Epoch 38/128

120/120 - 2s - 16ms/step - ia: 0.7723 - loss: 0.7252 - mae: 0.3210 - rmse: 0.5851 - smape: 0.6202 - val_ia: 0.7944 - val_loss: 0.1901 - val_mae: 0.2431 - val_rmse: 0.3631 - val_smape: 0.4789

Epoch 38: early stopping

Restoring model weights from the end of the best epoch: 23.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 34s 252ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

Epoch 1/8

 14%|█▍        | 7/50 [1:19:00<8:25:35, 705.47s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1916/1916 - 24s - 12ms/step - ia: 0.8269 - loss: 0.1334 - mae: 0.2285 - rmse: 0.3269 - smape: 0.5067 - val_ia: 0.6656 - val_loss: 0.0561 - val_mae: 0.1380 - val_rmse: 0.1908 - val_smape: 0.3699

Epoch 2/8

1916/1916 - 20s - 11ms/step - ia: 0.8620 - loss: 0.0914 - mae: 0.1875 - rmse: 0.2739 - smape: 0.4233 - val_ia: 0.6641 - val_loss: 0.0551 - val_mae: 0.1375 - val_rmse: 0.1889 - val_smape: 0.3587

Epoch 3/8

1916/1916 - 20s - 10ms/step - ia: 0.8642 - loss: 0.0879 - mae: 0.1843 - rmse: 0.2676 - smape: 0.4197 - val_ia: 0.6867 - val_loss: 0.0560 - val_mae: 0.1340 - val_rmse: 0.1896 - val_smape: 0.3546

Epoch 4/8

1916/1916 - 20s - 10ms/step - ia: 0.8686 - loss: 0.0842 - mae: 0.1796 - rmse: 0.2618 - smape: 0.4133 - val_ia: 0.6691 - val_loss: 0.0557 - val_mae: 0.1367 - val_rmse: 0.1902 - val_smape: 0.3603

Epoch 5/8

1916/1916 - 20s - 10ms/step - ia: 0.8680 - loss: 0.0841 - mae: 0.1801 - rmse: 0.2627 - smape: 0.4148 - val_ia: 0.6622 - val_loss: 0.0577 - val_mae: 0.1388 - val_rmse: 0.1920 - val_smape: 0.3579

Epoch 6/8

1916/1916 - 21s - 11ms/step - ia: 0.8699 - loss: 0.0826 - mae: 0.1780 - rmse: 0.2587 - smape: 0.4109 - val_ia: 0.6306 - val_loss: 0.0730 - val_mae: 0.1633 - val_rmse: 0.2196 - val_smape: 0.3822

Epoch 7/8

1916/1916 - 45s - 23ms/step - ia: 0.8714 - loss: 0.0798 - mae: 0.1752 - rmse: 0.2554 - smape: 0.4075 - val_ia: 0.6717 - val_loss: 0.0548 - val_mae: 0.1362 - val_rmse: 0.1874 - val_smape: 0.3584

Epoch 8/8

1916/1916 - 20s - 11ms/step - ia: 0.8699 - loss: 0.0814 - mae: 0.1774 - rmse: 0.2588 - smape: 0.4089 - val_ia: 0.6882 - val_loss: 0.0553 - val_mae: 0.1316 - val_rmse: 0.1873 - val_smape: 0.3505

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 54s 400ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 16%|█▌        | 8/50 [1:22:12<6:19:27, 542.08s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 3s - 24ms/step - ia: 0.5960 - loss: 0.5530 - mae: 0.5521 - rmse: 0.7230 - smape: 1.0259 - val_ia: 0.7109 - val_loss: 0.1572 - val_mae: 0.2905 - val_rmse: 0.3839 - val_smape: 0.6839

Epoch 2/128

120/120 - 1s - 5ms/step - ia: 0.7218 - loss: 0.2796 - mae: 0.3822 - rmse: 0.5254 - smape: 0.8024 - val_ia: 0.7562 - val_loss: 0.1299 - val_mae: 0.2530 - val_rmse: 0.3442 - val_smape: 0.6001

Epoch 3/128

120/120 - 1s - 4ms/step - ia: 0.7553 - loss: 0.2256 - mae: 0.3378 - rmse: 0.4727 - smape: 0.7316 - val_ia: 0.7830 - val_loss: 0.1067 - val_mae: 0.2259 - val_rmse: 0.3131 - val_smape: 0.5545

Epoch 4/128

120/120 - 1s - 6ms/step - ia: 0.7752 - loss: 0.2004 - mae: 0.3126 - rmse: 0.4447 - smape: 0.6795 - val_ia: 0.7922 - val_loss: 0.1000 - val_mae: 0.2171 - val_rmse: 0.3021 - val_smape: 0.5321

Epoch 5/128

120/120 - 1s - 5ms/step - ia: 0.7900 - loss: 0.1789 - mae: 0.2926 - rmse: 0.4204 - smape: 0.6425 - val_ia: 0.8091 - val_loss: 0.0890 - val_mae: 0.2010 - val_rmse: 0.2851 - val_smape: 0.5061

Epoch 6/128

120/120 - 1s - 5ms/step - ia: 0.7999 - loss: 0.1670 - mae: 0.2804 - rmse: 0.4064 - smape: 0.6164 - val_ia: 0.8090 - val_loss: 0.0860 - val_mae: 0.1999 - val_rmse: 0.2801 - val_smape: 0.4989

Epoch 7/128

120/120 - 1s - 4ms/step - ia: 0.8067 - loss: 0.1599 - mae: 0.2707 - rmse: 0.3963 - smape: 0.5935 - val_ia: 0.8156 - val_loss: 0.0837 - val_mae: 0.1952 - val_rmse: 0.2747 - val_smape: 0.4786

Epoch 8/128

120/120 - 1s - 7ms/step - ia: 0.8152 - loss: 0.1480 - mae: 0.2605 - rmse: 0.3827 - smape: 0.5747 - val_ia: 0.8233 - val_loss: 0.0796 - val_mae: 0.1878 - val_rmse: 0.2675 - val_smape: 0.4659

Epoch 9/128

120/120 - 2s - 13ms/step - ia: 0.8202 - loss: 0.1426 - mae: 0.2536 - rmse: 0.3745 - smape: 0.5565 - val_ia: 0.8336 - val_loss: 0.0718 - val_mae: 0.1765 - val_rmse: 0.2552 - val_smape: 0.4499

Epoch 10/128

120/120 - 1s - 10ms/step - ia: 0.8219 - loss: 0.1459 - mae: 0.2518 - rmse: 0.3791 - smape: 0.5482 - val_ia: 0.8357 - val_loss: 0.0708 - val_mae: 0.1750 - val_rmse: 0.2529 - val_smape: 0.4408

Epoch 11/128

120/120 - 1s - 12ms/step - ia: 0.8254 - loss: 0.1396 - mae: 0.2471 - rmse: 0.3709 - smape: 0.5402 - val_ia: 0.8405 - val_loss: 0.0691 - val_mae: 0.1706 - val_rmse: 0.2494 - val_smape: 0.4322

Epoch 12/128

120/120 - 1s - 7ms/step - ia: 0.8298 - loss: 0.1352 - mae: 0.2418 - rmse: 0.3652 - smape: 0.5264 - val_ia: 0.8434 - val_loss: 0.0671 - val_mae: 0.1672 - val_rmse: 0.2459 - val_smape: 0.4274

Epoch 13/128

120/120 - 1s - 8ms/step - ia: 0.8319 - loss: 0.1341 - mae: 0.2386 - rmse: 0.3636 - smape: 0.5208 - val_ia: 0.8465 - val_loss: 0.0656 - val_mae: 0.1643 - val_rmse: 0.2434 - val_smape: 0.4238

Epoch 14/128

120/120 - 1s - 9ms/step - ia: 0.8332 - loss: 0.1298 - mae: 0.2370 - rmse: 0.3576 - smape: 0.5180 - val_ia: 0.8489 - val_loss: 0.0649 - val_mae: 0.1625 - val_rmse: 0.2415 - val_smape: 0.4180

Epoch 15/128

120/120 - 1s - 9ms/step - ia: 0.8362 - loss: 0.1290 - mae: 0.2329 - rmse: 0.3566 - smape: 0.5089 - val_ia: 0.8478 - val_loss: 0.0647 - val_mae: 0.1628 - val_rmse: 0.2413 - val_smape: 0.4161

Epoch 16/128

120/120 - 1s - 7ms/step - ia: 0.8373 - loss: 0.1247 - mae: 0.2309 - rmse: 0.3504 - smape: 0.5059 - val_ia: 0.8532 - val_loss: 0.0638 - val_mae: 0.1588 - val_rmse: 0.2389 - val_smape: 0.4095

Epoch 17/128

120/120 - 1s - 6ms/step - ia: 0.8393 - loss: 0.1256 - mae: 0.2288 - rmse: 0.3513 - smape: 0.4991 - val_ia: 0.8479 - val_loss: 0.0664 - val_mae: 0.1641 - val_rmse: 0.2433 - val_smape: 0.4132

Epoch 18/128

120/120 - 1s - 6ms/step - ia: 0.8420 - loss: 0.1217 - mae: 0.2249 - rmse: 0.3454 - smape: 0.4923 - val_ia: 0.8544 - val_loss: 0.0629 - val_mae: 0.1578 - val_rmse: 0.2373 - val_smape: 0.4053

Epoch 19/128

120/120 - 1s - 6ms/step - ia: 0.8424 - loss: 0.1213 - mae: 0.2248 - rmse: 0.3453 - smape: 0.4911 - val_ia: 0.8574 - val_loss: 0.0624 - val_mae: 0.1554 - val_rmse: 0.2360 - val_smape: 0.4021

Epoch 20/128

120/120 - 1s - 6ms/step - ia: 0.8414 - loss: 0.1243 - mae: 0.2255 - rmse: 0.3501 - smape: 0.4888 - val_ia: 0.8609 - val_loss: 0.0619 - val_mae: 0.1536 - val_rmse: 0.2344 - val_smape: 0.3965

Epoch 21/128

120/120 - 1s - 7ms/step - ia: 0.8448 - loss: 0.1187 - mae: 0.2220 - rmse: 0.3418 - smape: 0.4842 - val_ia: 0.8570 - val_loss: 0.0634 - val_mae: 0.1567 - val_rmse: 0.2368 - val_smape: 0.3978

Epoch 22/128

120/120 - 1s - 11ms/step - ia: 0.8454 - loss: 0.1177 - mae: 0.2208 - rmse: 0.3399 - smape: 0.4810 - val_ia: 0.8608 - val_loss: 0.0608 - val_mae: 0.1526 - val_rmse: 0.2323 - val_smape: 0.3916

Epoch 23/128

120/120 - 1s - 6ms/step - ia: 0.8458 - loss: 0.1201 - mae: 0.2201 - rmse: 0.3426 - smape: 0.4804 - val_ia: 0.8595 - val_loss: 0.0620 - val_mae: 0.1548 - val_rmse: 0.2342 - val_smape: 0.3950

Epoch 24/128

120/120 - 1s - 6ms/step - ia: 0.8462 - loss: 0.1208 - mae: 0.2194 - rmse: 0.3441 - smape: 0.4735 - val_ia: 0.8618 - val_loss: 0.0615 - val_mae: 0.1525 - val_rmse: 0.2328 - val_smape: 0.3908

Epoch 25/128

120/120 - 1s - 6ms/step - ia: 0.8486 - loss: 0.1153 - mae: 0.2164 - rmse: 0.3360 - smape: 0.4709 - val_ia: 0.8732 - val_loss: 0.0575 - val_mae: 0.1416 - val_rmse: 0.2254 - val_smape: 0.3762

Epoch 26/128

120/120 - 1s - 11ms/step - ia: 0.8491 - loss: 0.1154 - mae: 0.2159 - rmse: 0.3365 - smape: 0.4694 - val_ia: 0.8704 - val_loss: 0.0581 - val_mae: 0.1436 - val_rmse: 0.2265 - val_smape: 0.3786

Epoch 27/128

120/120 - 1s - 11ms/step - ia: 0.8492 - loss: 0.1176 - mae: 0.2162 - rmse: 0.3405 - smape: 0.4642 - val_ia: 0.8637 - val_loss: 0.0591 - val_mae: 0.1488 - val_rmse: 0.2290 - val_smape: 0.3834

Epoch 28/128

120/120 - 1s - 10ms/step - ia: 0.8490 - loss: 0.1176 - mae: 0.2164 - rmse: 0.3403 - smape: 0.4662 - val_ia: 0.8687 - val_loss: 0.0580 - val_mae: 0.1446 - val_rmse: 0.2264 - val_smape: 0.3774

Epoch 29/128

120/120 - 1s - 5ms/step - ia: 0.8492 - loss: 0.1149 - mae: 0.2159 - rmse: 0.3363 - smape: 0.4649 - val_ia: 0.8707 - val_loss: 0.0578 - val_mae: 0.1442 - val_rmse: 0.2257 - val_smape: 0.3769

Epoch 30/128

120/120 - 1s - 5ms/step - ia: 0.8502 - loss: 0.1153 - mae: 0.2147 - rmse: 0.3359 - smape: 0.4630 - val_ia: 0.8653 - val_loss: 0.0593 - val_mae: 0.1488 - val_rmse: 0.2285 - val_smape: 0.3803

Epoch 31/128

120/120 - 1s - 6ms/step - ia: 0.8496 - loss: 0.1172 - mae: 0.2151 - rmse: 0.3388 - smape: 0.4627 - val_ia: 0.8677 - val_loss: 0.0590 - val_mae: 0.1473 - val_rmse: 0.2277 - val_smape: 0.3787

Epoch 32/128

120/120 - 1s - 6ms/step - ia: 0.8511 - loss: 0.1142 - mae: 0.2137 - rmse: 0.3345 - smape: 0.4585 - val_ia: 0.8612 - val_loss: 0.0604 - val_mae: 0.1517 - val_rmse: 0.2309 - val_smape: 0.3838

Epoch 33/128

120/120 - 1s - 11ms/step - ia: 0.8506 - loss: 0.1148 - mae: 0.2140 - rmse: 0.3352 - smape: 0.4596 - val_ia: 0.8671 - val_loss: 0.0600 - val_mae: 0.1474 - val_rmse: 0.2293 - val_smape: 0.3767

Epoch 34/128

120/120 - 1s - 6ms/step - ia: 0.8499 - loss: 0.1168 - mae: 0.2149 - rmse: 0.3382 - smape: 0.4604 - val_ia: 0.8626 - val_loss: 0.0604 - val_mae: 0.1506 - val_rmse: 0.2306 - val_smape: 0.3822

Epoch 35/128

120/120 - 1s - 6ms/step - ia: 0.8507 - loss: 0.1158 - mae: 0.2140 - rmse: 0.3366 - smape: 0.4593 - val_ia: 0.8674 - val_loss: 0.0600 - val_mae: 0.1478 - val_rmse: 0.2291 - val_smape: 0.3766

Epoch 36/128

120/120 - 1s - 6ms/step - ia: 0.8519 - loss: 0.1120 - mae: 0.2121 - rmse: 0.3317 - smape: 0.4561 - val_ia: 0.8735 - val_loss: 0.0576 - val_mae: 0.1423 - val_rmse: 0.2245 - val_smape: 0.3708

Epoch 37/128

120/120 - 1s - 6ms/step - ia: 0.8513 - loss: 0.1157 - mae: 0.2136 - rmse: 0.3366 - smape: 0.4564 - val_ia: 0.8711 - val_loss: 0.0563 - val_mae: 0.1417 - val_rmse: 0.2232 - val_smape: 0.3716

Epoch 38/128

120/120 - 1s - 12ms/step - ia: 0.8514 - loss: 0.1132 - mae: 0.2127 - rmse: 0.3327 - smape: 0.4565 - val_ia: 0.8765 - val_loss: 0.0559 - val_mae: 0.1384 - val_rmse: 0.2216 - val_smape: 0.3658

Epoch 39/128

120/120 - 1s - 8ms/step - ia: 0.8528 - loss: 0.1097 - mae: 0.2109 - rmse: 0.3278 - smape: 0.4532 - val_ia: 0.8655 - val_loss: 0.0593 - val_mae: 0.1473 - val_rmse: 0.2286 - val_smape: 0.3780

Epoch 40/128

120/120 - 1s - 6ms/step - ia: 0.8520 - loss: 0.1130 - mae: 0.2124 - rmse: 0.3333 - smape: 0.4560 - val_ia: 0.8684 - val_loss: 0.0587 - val_mae: 0.1466 - val_rmse: 0.2269 - val_smape: 0.3744

Epoch 41/128

120/120 - 1s - 5ms/step - ia: 0.8513 - loss: 0.1142 - mae: 0.2134 - rmse: 0.3352 - smape: 0.4541 - val_ia: 0.8608 - val_loss: 0.0636 - val_mae: 0.1552 - val_rmse: 0.2347 - val_smape: 0.3813

Epoch 42/128

120/120 - 1s - 6ms/step - ia: 0.8520 - loss: 0.1122 - mae: 0.2120 - rmse: 0.3315 - smape: 0.4552 - val_ia: 0.8762 - val_loss: 0.0558 - val_mae: 0.1383 - val_rmse: 0.2214 - val_smape: 0.3646

Epoch 43/128

120/120 - 1s - 6ms/step - ia: 0.8535 - loss: 0.1099 - mae: 0.2102 - rmse: 0.3287 - smape: 0.4518 - val_ia: 0.8759 - val_loss: 0.0555 - val_mae: 0.1386 - val_rmse: 0.2209 - val_smape: 0.3649

Epoch 44/128

120/120 - 1s - 6ms/step - ia: 0.8540 - loss: 0.1089 - mae: 0.2094 - rmse: 0.3270 - smape: 0.4507 - val_ia: 0.8683 - val_loss: 0.0595 - val_mae: 0.1467 - val_rmse: 0.2279 - val_smape: 0.3715

Epoch 45/128

120/120 - 1s - 6ms/step - ia: 0.8517 - loss: 0.1130 - mae: 0.2127 - rmse: 0.3335 - smape: 0.4518 - val_ia: 0.8676 - val_loss: 0.0596 - val_mae: 0.1473 - val_rmse: 0.2282 - val_smape: 0.3737

Epoch 46/128

120/120 - 1s - 11ms/step - ia: 0.8546 - loss: 0.1086 - mae: 0.2091 - rmse: 0.3270 - smape: 0.4471 - val_ia: 0.8754 - val_loss: 0.0554 - val_mae: 0.1388 - val_rmse: 0.2208 - val_smape: 0.3644

Epoch 47/128

120/120 - 1s - 11ms/step - ia: 0.8525 - loss: 0.1107 - mae: 0.2114 - rmse: 0.3299 - smape: 0.4532 - val_ia: 0.8672 - val_loss: 0.0601 - val_mae: 0.1486 - val_rmse: 0.2286 - val_smape: 0.3746

Epoch 48/128

120/120 - 1s - 12ms/step - ia: 0.8525 - loss: 0.1106 - mae: 0.2112 - rmse: 0.3299 - smape: 0.4513 - val_ia: 0.8703 - val_loss: 0.0586 - val_mae: 0.1454 - val_rmse: 0.2262 - val_smape: 0.3711

Epoch 49/128

120/120 - 1s - 11ms/step - ia: 0.8533 - loss: 0.1086 - mae: 0.2105 - rmse: 0.3269 - smape: 0.4495 - val_ia: 0.8709 - val_loss: 0.0595 - val_mae: 0.1455 - val_rmse: 0.2271 - val_smape: 0.3690

Epoch 50/128

120/120 - 1s - 11ms/step - ia: 0.8532 - loss: 0.1154 - mae: 0.2108 - rmse: 0.3357 - smape: 0.4489 - val_ia: 0.8723 - val_loss: 0.0569 - val_mae: 0.1420 - val_rmse: 0.2235 - val_smape: 0.3660

Epoch 51/128

120/120 - 1s - 6ms/step - ia: 0.8533 - loss: 0.1116 - mae: 0.2104 - rmse: 0.3309 - smape: 0.4486 - val_ia: 0.8744 - val_loss: 0.0558 - val_mae: 0.1403 - val_rmse: 0.2217 - val_smape: 0.3654

Epoch 52/128

120/120 - 1s - 11ms/step - ia: 0.8533 - loss: 0.1101 - mae: 0.2104 - rmse: 0.3291 - smape: 0.4505 - val_ia: 0.8721 - val_loss: 0.0579 - val_mae: 0.1437 - val_rmse: 0.2250 - val_smape: 0.3681

Epoch 53/128

120/120 - 1s - 7ms/step - ia: 0.8534 - loss: 0.1119 - mae: 0.2107 - rmse: 0.3308 - smape: 0.4505 - val_ia: 0.8736 - val_loss: 0.0572 - val_mae: 0.1419 - val_rmse: 0.2234 - val_smape: 0.3654

Epoch 54/128

120/120 - 1s - 11ms/step - ia: 0.8539 - loss: 0.1096 - mae: 0.2097 - rmse: 0.3282 - smape: 0.4498 - val_ia: 0.8709 - val_loss: 0.0577 - val_mae: 0.1444 - val_rmse: 0.2246 - val_smape: 0.3681

Epoch 55/128

120/120 - 1s - 6ms/step - ia: 0.8537 - loss: 0.1118 - mae: 0.2098 - rmse: 0.3310 - smape: 0.4481 - val_ia: 0.8698 - val_loss: 0.0579 - val_mae: 0.1439 - val_rmse: 0.2255 - val_smape: 0.3704

Epoch 56/128

120/120 - 1s - 11ms/step - ia: 0.8542 - loss: 0.1088 - mae: 0.2095 - rmse: 0.3272 - smape: 0.4485 - val_ia: 0.8725 - val_loss: 0.0571 - val_mae: 0.1424 - val_rmse: 0.2236 - val_smape: 0.3666

Epoch 57/128

120/120 - 1s - 6ms/step - ia: 0.8543 - loss: 0.1094 - mae: 0.2089 - rmse: 0.3273 - smape: 0.4492 - val_ia: 0.8725 - val_loss: 0.0564 - val_mae: 0.1419 - val_rmse: 0.2225 - val_smape: 0.3668

Epoch 58/128

120/120 - 1s - 11ms/step - ia: 0.8543 - loss: 0.1095 - mae: 0.2090 - rmse: 0.3273 - smape: 0.4489 - val_ia: 0.8700 - val_loss: 0.0590 - val_mae: 0.1460 - val_rmse: 0.2267 - val_smape: 0.3700

Epoch 59/128

120/120 - 1s - 11ms/step - ia: 0.8529 - loss: 0.1121 - mae: 0.2109 - rmse: 0.3316 - smape: 0.4512 - val_ia: 0.8752 - val_loss: 0.0567 - val_mae: 0.1409 - val_rmse: 0.2225 - val_smape: 0.3641

Epoch 60/128

120/120 - 1s - 6ms/step - ia: 0.8555 - loss: 0.1086 - mae: 0.2077 - rmse: 0.3262 - smape: 0.4460 - val_ia: 0.8748 - val_loss: 0.0564 - val_mae: 0.1402 - val_rmse: 0.2221 - val_smape: 0.3636

Epoch 61/128

120/120 - 1s - 6ms/step - ia: 0.8538 - loss: 0.1079 - mae: 0.2102 - rmse: 0.3255 - smape: 0.4465 - val_ia: 0.8696 - val_loss: 0.0573 - val_mae: 0.1449 - val_rmse: 0.2242 - val_smape: 0.3697

Epoch 61: early stopping

Restoring model weights from the end of the best epoch: 46.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 40s 300ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 18%|█▊        | 9/50 [1:23:12<4:27:30, 391.46s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 26s - 27ms/step - ia: 0.6801 - loss: 0.3450 - mae: 0.3899 - rmse: 0.5549 - smape: 0.8147 - val_ia: 0.5446 - val_loss: 0.1628 - val_mae: 0.2731 - val_rmse: 0.3516 - val_smape: 0.6233

Epoch 2/16

958/958 - 19s - 20ms/step - ia: 0.7865 - loss: 0.1938 - mae: 0.2910 - rmse: 0.4219 - smape: 0.6296 - val_ia: 0.6598 - val_loss: 0.1135 - val_mae: 0.2109 - val_rmse: 0.2873 - val_smape: 0.5107

Epoch 3/16

958/958 - 22s - 23ms/step - ia: 0.8073 - loss: 0.1603 - mae: 0.2652 - rmse: 0.3833 - smape: 0.5854 - val_ia: 0.6647 - val_loss: 0.1022 - val_mae: 0.2000 - val_rmse: 0.2761 - val_smape: 0.4928

Epoch 4/16

958/958 - 15s - 16ms/step - ia: 0.8217 - loss: 0.1414 - mae: 0.2472 - rmse: 0.3591 - smape: 0.5539 - val_ia: 0.6780 - val_loss: 0.0888 - val_mae: 0.1862 - val_rmse: 0.2579 - val_smape: 0.4675

Epoch 5/16

958/958 - 15s - 15ms/step - ia: 0.8316 - loss: 0.1273 - mae: 0.2344 - rmse: 0.3406 - smape: 0.5307 - val_ia: 0.7199 - val_loss: 0.0780 - val_mae: 0.1682 - val_rmse: 0.2409 - val_smape: 0.4319

Epoch 6/16

958/958 - 15s - 15ms/step - ia: 0.8391 - loss: 0.1175 - mae: 0.2252 - rmse: 0.3262 - smape: 0.5180 - val_ia: 0.7014 - val_loss: 0.0783 - val_mae: 0.1731 - val_rmse: 0.2385 - val_smape: 0.4344

Epoch 7/16

958/958 - 12s - 13ms/step - ia: 0.8438 - loss: 0.1121 - mae: 0.2184 - rmse: 0.3188 - smape: 0.5010 - val_ia: 0.7340 - val_loss: 0.0681 - val_mae: 0.1559 - val_rmse: 0.2232 - val_smape: 0.4076

Epoch 8/16

958/958 - 15s - 16ms/step - ia: 0.8482 - loss: 0.1050 - mae: 0.2125 - rmse: 0.3089 - smape: 0.4923 - val_ia: 0.7226 - val_loss: 0.0671 - val_mae: 0.1568 - val_rmse: 0.2233 - val_smape: 0.4053

Epoch 9/16

958/958 - 12s - 13ms/step - ia: 0.8536 - loss: 0.1010 - mae: 0.2053 - rmse: 0.3012 - smape: 0.4769 - val_ia: 0.7443 - val_loss: 0.0661 - val_mae: 0.1520 - val_rmse: 0.2177 - val_smape: 0.3924

Epoch 10/16

958/958 - 15s - 16ms/step - ia: 0.8572 - loss: 0.0978 - mae: 0.2010 - rmse: 0.2956 - smape: 0.4676 - val_ia: 0.7412 - val_loss: 0.0645 - val_mae: 0.1513 - val_rmse: 0.2152 - val_smape: 0.3913

Epoch 11/16

958/958 - 15s - 16ms/step - ia: 0.8584 - loss: 0.0951 - mae: 0.1987 - rmse: 0.2929 - smape: 0.4652 - val_ia: 0.7460 - val_loss: 0.0605 - val_mae: 0.1451 - val_rmse: 0.2101 - val_smape: 0.3815

Epoch 12/16

958/958 - 20s - 21ms/step - ia: 0.8614 - loss: 0.0927 - mae: 0.1946 - rmse: 0.2876 - smape: 0.4549 - val_ia: 0.7290 - val_loss: 0.0654 - val_mae: 0.1551 - val_rmse: 0.2161 - val_smape: 0.3921

Epoch 13/16

958/958 - 21s - 22ms/step - ia: 0.8622 - loss: 0.0930 - mae: 0.1938 - rmse: 0.2863 - smape: 0.4551 - val_ia: 0.7502 - val_loss: 0.0592 - val_mae: 0.1429 - val_rmse: 0.2078 - val_smape: 0.3768

Epoch 14/16

958/958 - 21s - 22ms/step - ia: 0.8649 - loss: 0.0900 - mae: 0.1908 - rmse: 0.2826 - smape: 0.4485 - val_ia: 0.7417 - val_loss: 0.0596 - val_mae: 0.1458 - val_rmse: 0.2082 - val_smape: 0.3782

Epoch 15/16

958/958 - 14s - 15ms/step - ia: 0.8663 - loss: 0.0880 - mae: 0.1886 - rmse: 0.2794 - smape: 0.4432 - val_ia: 0.7647 - val_loss: 0.0570 - val_mae: 0.1378 - val_rmse: 0.2028 - val_smape: 0.3699

Epoch 16/16

958/958 - 13s - 14ms/step - ia: 0.8674 - loss: 0.0887 - mae: 0.1869 - rmse: 0.2793 - smape: 0.4387 - val_ia: 0.7533 - val_loss: 0.0571 - val_mae: 0.1405 - val_rmse: 0.2035 - val_smape: 0.3792

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:30 667ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 20%|██        | 10/50 [1:27:45<3:56:31, 354.79s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 10s - 43ms/step - ia: 0.3200 - loss: 2.0560 - mae: 1.0309 - rmse: 1.4221 - smape: 1.4141 - val_ia: 0.3279 - val_loss: 1.3812 - val_mae: 0.9518 - val_rmse: 1.1007 - val_smape: 1.4769

Epoch 2/8

240/240 - 4s - 18ms/step - ia: 0.3244 - loss: 2.0077 - mae: 1.0186 - rmse: 1.4062 - smape: 1.4124 - val_ia: 0.3287 - val_loss: 1.3610 - val_mae: 0.9443 - val_rmse: 1.0928 - val_smape: 1.4754

Epoch 3/8

240/240 - 2s - 8ms/step - ia: 0.3214 - loss: 1.9853 - mae: 1.0169 - rmse: 1.4005 - smape: 1.4169 - val_ia: 0.3295 - val_loss: 1.3417 - val_mae: 0.9370 - val_rmse: 1.0852 - val_smape: 1.4739

Epoch 4/8

240/240 - 2s - 9ms/step - ia: 0.3267 - loss: 1.8935 - mae: 0.9970 - rmse: 1.3674 - smape: 1.4101 - val_ia: 0.3303 - val_loss: 1.3233 - val_mae: 0.9300 - val_rmse: 1.0779 - val_smape: 1.4724

Epoch 5/8

240/240 - 2s - 9ms/step - ia: 0.3256 - loss: 1.8797 - mae: 0.9920 - rmse: 1.3620 - smape: 1.4101 - val_ia: 0.3311 - val_loss: 1.3056 - val_mae: 0.9232 - val_rmse: 1.0708 - val_smape: 1.4709

Epoch 6/8

240/240 - 2s - 9ms/step - ia: 0.3264 - loss: 1.9037 - mae: 0.9910 - rmse: 1.3677 - smape: 1.4096 - val_ia: 0.3318 - val_loss: 1.2883 - val_mae: 0.9164 - val_rmse: 1.0637 - val_smape: 1.4695

Epoch 7/8

240/240 - 3s - 11ms/step - ia: 0.3279 - loss: 1.8508 - mae: 0.9858 - rmse: 1.3489 - smape: 1.4095 - val_ia: 0.3326 - val_loss: 1.2715 - val_mae: 0.9098 - val_rmse: 1.0568 - val_smape: 1.4681

Epoch 8/8

240/240 - 2s - 8ms/step - ia: 0.3257 - loss: 1.8220 - mae: 0.9754 - rmse: 1.3406 - smape: 1.4103 - val_ia: 0.3333 - val_loss: 1.2560 - val_mae: 0.9037 - val_rmse: 1.0504 - val_smape: 1.4667

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 38s 285ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/128

 22%|██▏       | 11/50 [1:28:14<2:45:48, 255.08s/trial, best loss: 0.038702921828591516]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

958/958 - 14s - 15ms/step - ia: 0.6698 - loss: 0.3503 - mae: 0.4062 - rmse: 0.5491 - smape: 0.8521 - val_ia: 0.5999 - val_loss: 0.1207 - val_mae: 0.2372 - val_rmse: 0.3072 - val_smape: 0.5812

Epoch 2/128

958/958 - 8s - 8ms/step - ia: 0.8092 - loss: 0.1487 - mae: 0.2648 - rmse: 0.3711 - smape: 0.5991 - val_ia: 0.6996 - val_loss: 0.0846 - val_mae: 0.1784 - val_rmse: 0.2489 - val_smape: 0.4513

Epoch 3/128

958/958 - 8s - 9ms/step - ia: 0.8336 - loss: 0.1187 - mae: 0.2317 - rmse: 0.3291 - smape: 0.5391 - val_ia: 0.6997 - val_loss: 0.0758 - val_mae: 0.1729 - val_rmse: 0.2384 - val_smape: 0.4347

Epoch 4/128

958/958 - 8s - 8ms/step - ia: 0.8472 - loss: 0.1046 - mae: 0.2136 - rmse: 0.3077 - smape: 0.5061 - val_ia: 0.7505 - val_loss: 0.0687 - val_mae: 0.1535 - val_rmse: 0.2210 - val_smape: 0.4027

Epoch 5/128

958/958 - 8s - 8ms/step - ia: 0.8553 - loss: 0.0968 - mae: 0.2029 - rmse: 0.2939 - smape: 0.4858 - val_ia: 0.7584 - val_loss: 0.0647 - val_mae: 0.1464 - val_rmse: 0.2150 - val_smape: 0.3879

Epoch 6/128

958/958 - 8s - 8ms/step - ia: 0.8606 - loss: 0.0906 - mae: 0.1956 - rmse: 0.2842 - smape: 0.4729 - val_ia: 0.7683 - val_loss: 0.0616 - val_mae: 0.1411 - val_rmse: 0.2087 - val_smape: 0.3787

Epoch 7/128

958/958 - 8s - 9ms/step - ia: 0.8661 - loss: 0.0863 - mae: 0.1884 - rmse: 0.2770 - smape: 0.4588 - val_ia: 0.7471 - val_loss: 0.0618 - val_mae: 0.1475 - val_rmse: 0.2104 - val_smape: 0.3824

Epoch 8/128

958/958 - 10s - 10ms/step - ia: 0.8712 - loss: 0.0822 - mae: 0.1813 - rmse: 0.2696 - smape: 0.4426 - val_ia: 0.7559 - val_loss: 0.0590 - val_mae: 0.1419 - val_rmse: 0.2051 - val_smape: 0.3738

Epoch 9/128

958/958 - 8s - 8ms/step - ia: 0.8727 - loss: 0.0804 - mae: 0.1790 - rmse: 0.2664 - smape: 0.4368 - val_ia: 0.7805 - val_loss: 0.0577 - val_mae: 0.1336 - val_rmse: 0.2012 - val_smape: 0.3615

Epoch 10/128

958/958 - 8s - 8ms/step - ia: 0.8762 - loss: 0.0783 - mae: 0.1752 - rmse: 0.2620 - smape: 0.4298 - val_ia: 0.7718 - val_loss: 0.0570 - val_mae: 0.1347 - val_rmse: 0.2004 - val_smape: 0.3614

Epoch 11/128

958/958 - 8s - 8ms/step - ia: 0.8785 - loss: 0.0762 - mae: 0.1717 - rmse: 0.2585 - smape: 0.4201 - val_ia: 0.7536 - val_loss: 0.0581 - val_mae: 0.1410 - val_rmse: 0.2055 - val_smape: 0.3734

Epoch 12/128

958/958 - 8s - 9ms/step - ia: 0.8798 - loss: 0.0753 - mae: 0.1700 - rmse: 0.2561 - smape: 0.4183 - val_ia: 0.7762 - val_loss: 0.0567 - val_mae: 0.1327 - val_rmse: 0.1998 - val_smape: 0.3569

Epoch 13/128

958/958 - 8s - 8ms/step - ia: 0.8811 - loss: 0.0741 - mae: 0.1683 - rmse: 0.2543 - smape: 0.4143 - val_ia: 0.7779 - val_loss: 0.0565 - val_mae: 0.1333 - val_rmse: 0.1986 - val_smape: 0.3586

Epoch 14/128

958/958 - 8s - 8ms/step - ia: 0.8814 - loss: 0.0737 - mae: 0.1677 - rmse: 0.2540 - smape: 0.4134 - val_ia: 0.7587 - val_loss: 0.0570 - val_mae: 0.1381 - val_rmse: 0.2025 - val_smape: 0.3661

Epoch 15/128

958/958 - 8s - 8ms/step - ia: 0.8836 - loss: 0.0717 - mae: 0.1647 - rmse: 0.2505 - smape: 0.4076 - val_ia: 0.7705 - val_loss: 0.0559 - val_mae: 0.1336 - val_rmse: 0.1983 - val_smape: 0.3586

Epoch 16/128

958/958 - 10s - 11ms/step - ia: 0.8837 - loss: 0.0718 - mae: 0.1643 - rmse: 0.2504 - smape: 0.4086 - val_ia: 0.7840 - val_loss: 0.0562 - val_mae: 0.1323 - val_rmse: 0.1970 - val_smape: 0.3566

Epoch 17/128

958/958 - 8s - 8ms/step - ia: 0.8850 - loss: 0.0718 - mae: 0.1630 - rmse: 0.2494 - smape: 0.4040 - val_ia: 0.7751 - val_loss: 0.0557 - val_mae: 0.1327 - val_rmse: 0.1975 - val_smape: 0.3560

Epoch 18/128

958/958 - 10s - 11ms/step - ia: 0.8862 - loss: 0.0708 - mae: 0.1611 - rmse: 0.2470 - smape: 0.3993 - val_ia: 0.7708 - val_loss: 0.0566 - val_mae: 0.1356 - val_rmse: 0.1988 - val_smape: 0.3582

Epoch 19/128

958/958 - 6s - 6ms/step - ia: 0.8860 - loss: 0.0703 - mae: 0.1611 - rmse: 0.2469 - smape: 0.4000 - val_ia: 0.7795 - val_loss: 0.0567 - val_mae: 0.1336 - val_rmse: 0.1978 - val_smape: 0.3549

Epoch 20/128

958/958 - 6s - 7ms/step - ia: 0.8872 - loss: 0.0696 - mae: 0.1599 - rmse: 0.2464 - smape: 0.3950 - val_ia: 0.7878 - val_loss: 0.0551 - val_mae: 0.1294 - val_rmse: 0.1952 - val_smape: 0.3510

Epoch 21/128

958/958 - 8s - 8ms/step - ia: 0.8869 - loss: 0.0701 - mae: 0.1603 - rmse: 0.2467 - smape: 0.3969 - val_ia: 0.7646 - val_loss: 0.0567 - val_mae: 0.1369 - val_rmse: 0.2012 - val_smape: 0.3641

Epoch 22/128

958/958 - 6s - 6ms/step - ia: 0.8879 - loss: 0.0697 - mae: 0.1590 - rmse: 0.2460 - smape: 0.3943 - val_ia: 0.7778 - val_loss: 0.0551 - val_mae: 0.1314 - val_rmse: 0.1964 - val_smape: 0.3528

Epoch 23/128

958/958 - 6s - 7ms/step - ia: 0.8880 - loss: 0.0692 - mae: 0.1582 - rmse: 0.2451 - smape: 0.3911 - val_ia: 0.7729 - val_loss: 0.0554 - val_mae: 0.1331 - val_rmse: 0.1981 - val_smape: 0.3573

Epoch 24/128

958/958 - 8s - 8ms/step - ia: 0.8884 - loss: 0.0694 - mae: 0.1582 - rmse: 0.2448 - smape: 0.3925 - val_ia: 0.7665 - val_loss: 0.0555 - val_mae: 0.1346 - val_rmse: 0.1992 - val_smape: 0.3600

Epoch 25/128

958/958 - 6s - 6ms/step - ia: 0.8889 - loss: 0.0683 - mae: 0.1574 - rmse: 0.2441 - smape: 0.3911 - val_ia: 0.7832 - val_loss: 0.0547 - val_mae: 0.1301 - val_rmse: 0.1948 - val_smape: 0.3504

Epoch 26/128

958/958 - 6s - 6ms/step - ia: 0.8887 - loss: 0.0690 - mae: 0.1577 - rmse: 0.2444 - smape: 0.3923 - val_ia: 0.7581 - val_loss: 0.0556 - val_mae: 0.1374 - val_rmse: 0.2005 - val_smape: 0.3648

Epoch 27/128

958/958 - 8s - 8ms/step - ia: 0.8895 - loss: 0.0683 - mae: 0.1567 - rmse: 0.2418 - smape: 0.3896 - val_ia: 0.7450 - val_loss: 0.0569 - val_mae: 0.1431 - val_rmse: 0.2052 - val_smape: 0.3773

Epoch 28/128

958/958 - 8s - 9ms/step - ia: 0.8895 - loss: 0.0684 - mae: 0.1567 - rmse: 0.2430 - smape: 0.3902 - val_ia: 0.7849 - val_loss: 0.0553 - val_mae: 0.1319 - val_rmse: 0.1963 - val_smape: 0.3542

Epoch 29/128

958/958 - 7s - 7ms/step - ia: 0.8900 - loss: 0.0677 - mae: 0.1561 - rmse: 0.2418 - smape: 0.3897 - val_ia: 0.7868 - val_loss: 0.0550 - val_mae: 0.1300 - val_rmse: 0.1951 - val_smape: 0.3509

Epoch 30/128

958/958 - 8s - 8ms/step - ia: 0.8898 - loss: 0.0683 - mae: 0.1562 - rmse: 0.2426 - smape: 0.3893 - val_ia: 0.7656 - val_loss: 0.0563 - val_mae: 0.1370 - val_rmse: 0.2006 - val_smape: 0.3636

Epoch 31/128

958/958 - 8s - 8ms/step - ia: 0.8899 - loss: 0.0683 - mae: 0.1557 - rmse: 0.2424 - smape: 0.3873 - val_ia: 0.7761 - val_loss: 0.0549 - val_mae: 0.1322 - val_rmse: 0.1971 - val_smape: 0.3547

Epoch 32/128

958/958 - 8s - 8ms/step - ia: 0.8907 - loss: 0.0676 - mae: 0.1549 - rmse: 0.2409 - smape: 0.3850 - val_ia: 0.7853 - val_loss: 0.0549 - val_mae: 0.1307 - val_rmse: 0.1950 - val_smape: 0.3509

Epoch 33/128

958/958 - 8s - 8ms/step - ia: 0.8902 - loss: 0.0676 - mae: 0.1552 - rmse: 0.2413 - smape: 0.3874 - val_ia: 0.7793 - val_loss: 0.0543 - val_mae: 0.1306 - val_rmse: 0.1951 - val_smape: 0.3517

Epoch 34/128

958/958 - 7s - 8ms/step - ia: 0.8909 - loss: 0.0667 - mae: 0.1545 - rmse: 0.2399 - smape: 0.3862 - val_ia: 0.7682 - val_loss: 0.0558 - val_mae: 0.1357 - val_rmse: 0.1996 - val_smape: 0.3626

Epoch 35/128

958/958 - 9s - 9ms/step - ia: 0.8909 - loss: 0.0675 - mae: 0.1551 - rmse: 0.2414 - smape: 0.3860 - val_ia: 0.7881 - val_loss: 0.0547 - val_mae: 0.1301 - val_rmse: 0.1954 - val_smape: 0.3491

Epoch 36/128

958/958 - 9s - 9ms/step - ia: 0.8917 - loss: 0.0669 - mae: 0.1534 - rmse: 0.2402 - smape: 0.3836 - val_ia: 0.7856 - val_loss: 0.0546 - val_mae: 0.1292 - val_rmse: 0.1960 - val_smape: 0.3515

Epoch 37/128

958/958 - 11s - 11ms/step - ia: 0.8908 - loss: 0.0670 - mae: 0.1545 - rmse: 0.2409 - smape: 0.3840 - val_ia: 0.7758 - val_loss: 0.0546 - val_mae: 0.1321 - val_rmse: 0.1956 - val_smape: 0.3541

Epoch 38/128

958/958 - 9s - 9ms/step - ia: 0.8911 - loss: 0.0668 - mae: 0.1543 - rmse: 0.2400 - smape: 0.3853 - val_ia: 0.7669 - val_loss: 0.0549 - val_mae: 0.1348 - val_rmse: 0.1981 - val_smape: 0.3589

Epoch 39/128

958/958 - 9s - 9ms/step - ia: 0.8914 - loss: 0.0674 - mae: 0.1544 - rmse: 0.2411 - smape: 0.3854 - val_ia: 0.7813 - val_loss: 0.0540 - val_mae: 0.1299 - val_rmse: 0.1945 - val_smape: 0.3500

Epoch 40/128

958/958 - 11s - 12ms/step - ia: 0.8911 - loss: 0.0665 - mae: 0.1538 - rmse: 0.2393 - smape: 0.3837 - val_ia: 0.7710 - val_loss: 0.0549 - val_mae: 0.1342 - val_rmse: 0.1971 - val_smape: 0.3574

Epoch 41/128

958/958 - 9s - 9ms/step - ia: 0.8916 - loss: 0.0669 - mae: 0.1535 - rmse: 0.2400 - smape: 0.3839 - val_ia: 0.7793 - val_loss: 0.0550 - val_mae: 0.1321 - val_rmse: 0.1960 - val_smape: 0.3523

Epoch 42/128

958/958 - 8s - 8ms/step - ia: 0.8921 - loss: 0.0663 - mae: 0.1535 - rmse: 0.2399 - smape: 0.3833 - val_ia: 0.7805 - val_loss: 0.0542 - val_mae: 0.1304 - val_rmse: 0.1954 - val_smape: 0.3516

Epoch 43/128

958/958 - 9s - 9ms/step - ia: 0.8919 - loss: 0.0667 - mae: 0.1530 - rmse: 0.2390 - smape: 0.3814 - val_ia: 0.7914 - val_loss: 0.0544 - val_mae: 0.1284 - val_rmse: 0.1950 - val_smape: 0.3466

Epoch 44/128

958/958 - 9s - 9ms/step - ia: 0.8926 - loss: 0.0657 - mae: 0.1528 - rmse: 0.2384 - smape: 0.3820 - val_ia: 0.7791 - val_loss: 0.0546 - val_mae: 0.1318 - val_rmse: 0.1951 - val_smape: 0.3522

Epoch 45/128

958/958 - 9s - 9ms/step - ia: 0.8924 - loss: 0.0667 - mae: 0.1529 - rmse: 0.2395 - smape: 0.3819 - val_ia: 0.7885 - val_loss: 0.0539 - val_mae: 0.1287 - val_rmse: 0.1934 - val_smape: 0.3470

Epoch 46/128

958/958 - 9s - 9ms/step - ia: 0.8924 - loss: 0.0655 - mae: 0.1525 - rmse: 0.2384 - smape: 0.3824 - val_ia: 0.7743 - val_loss: 0.0545 - val_mae: 0.1324 - val_rmse: 0.1969 - val_smape: 0.3559

Epoch 47/128

958/958 - 8s - 8ms/step - ia: 0.8929 - loss: 0.0657 - mae: 0.1522 - rmse: 0.2371 - smape: 0.3811 - val_ia: 0.7805 - val_loss: 0.0544 - val_mae: 0.1311 - val_rmse: 0.1953 - val_smape: 0.3521

Epoch 48/128

958/958 - 9s - 10ms/step - ia: 0.8923 - loss: 0.0659 - mae: 0.1527 - rmse: 0.2392 - smape: 0.3829 - val_ia: 0.7872 - val_loss: 0.0544 - val_mae: 0.1300 - val_rmse: 0.1942 - val_smape: 0.3488

Epoch 49/128

958/958 - 11s - 12ms/step - ia: 0.8923 - loss: 0.0663 - mae: 0.1528 - rmse: 0.2384 - smape: 0.3824 - val_ia: 0.7886 - val_loss: 0.0538 - val_mae: 0.1280 - val_rmse: 0.1937 - val_smape: 0.3467

Epoch 50/128

958/958 - 8s - 8ms/step - ia: 0.8927 - loss: 0.0653 - mae: 0.1519 - rmse: 0.2377 - smape: 0.3809 - val_ia: 0.7813 - val_loss: 0.0545 - val_mae: 0.1312 - val_rmse: 0.1952 - val_smape: 0.3505

Epoch 51/128

958/958 - 7s - 8ms/step - ia: 0.8925 - loss: 0.0660 - mae: 0.1529 - rmse: 0.2390 - smape: 0.3809 - val_ia: 0.7893 - val_loss: 0.0538 - val_mae: 0.1282 - val_rmse: 0.1932 - val_smape: 0.3467

Epoch 52/128

958/958 - 8s - 8ms/step - ia: 0.8929 - loss: 0.0656 - mae: 0.1520 - rmse: 0.2384 - smape: 0.3801 - val_ia: 0.7741 - val_loss: 0.0541 - val_mae: 0.1323 - val_rmse: 0.1961 - val_smape: 0.3553

Epoch 53/128

958/958 - 10s - 11ms/step - ia: 0.8929 - loss: 0.0657 - mae: 0.1517 - rmse: 0.2378 - smape: 0.3814 - val_ia: 0.7891 - val_loss: 0.0540 - val_mae: 0.1283 - val_rmse: 0.1949 - val_smape: 0.3491

Epoch 54/128

958/958 - 8s - 8ms/step - ia: 0.8927 - loss: 0.0653 - mae: 0.1519 - rmse: 0.2373 - smape: 0.3798 - val_ia: 0.7804 - val_loss: 0.0541 - val_mae: 0.1310 - val_rmse: 0.1951 - val_smape: 0.3526

Epoch 55/128

958/958 - 8s - 8ms/step - ia: 0.8939 - loss: 0.0646 - mae: 0.1510 - rmse: 0.2363 - smape: 0.3792 - val_ia: 0.7908 - val_loss: 0.0534 - val_mae: 0.1273 - val_rmse: 0.1930 - val_smape: 0.3451

Epoch 56/128

958/958 - 8s - 8ms/step - ia: 0.8930 - loss: 0.0656 - mae: 0.1524 - rmse: 0.2379 - smape: 0.3831 - val_ia: 0.7896 - val_loss: 0.0545 - val_mae: 0.1297 - val_rmse: 0.1942 - val_smape: 0.3474

Epoch 57/128

958/958 - 8s - 8ms/step - ia: 0.8936 - loss: 0.0653 - mae: 0.1514 - rmse: 0.2374 - smape: 0.3796 - val_ia: 0.7738 - val_loss: 0.0543 - val_mae: 0.1328 - val_rmse: 0.1960 - val_smape: 0.3548

Epoch 58/128

958/958 - 7s - 8ms/step - ia: 0.8923 - loss: 0.0657 - mae: 0.1527 - rmse: 0.2391 - smape: 0.3801 - val_ia: 0.7785 - val_loss: 0.0551 - val_mae: 0.1328 - val_rmse: 0.1957 - val_smape: 0.3513

Epoch 59/128

958/958 - 8s - 8ms/step - ia: 0.8939 - loss: 0.0640 - mae: 0.1509 - rmse: 0.2353 - smape: 0.3777 - val_ia: 0.7719 - val_loss: 0.0543 - val_mae: 0.1332 - val_rmse: 0.1965 - val_smape: 0.3569

Epoch 60/128

958/958 - 7s - 8ms/step - ia: 0.8938 - loss: 0.0644 - mae: 0.1510 - rmse: 0.2354 - smape: 0.3775 - val_ia: 0.7476 - val_loss: 0.0557 - val_mae: 0.1416 - val_rmse: 0.2033 - val_smape: 0.3755

Epoch 61/128

958/958 - 7s - 8ms/step - ia: 0.8941 - loss: 0.0647 - mae: 0.1506 - rmse: 0.2360 - smape: 0.3780 - val_ia: 0.7724 - val_loss: 0.0544 - val_mae: 0.1335 - val_rmse: 0.1964 - val_smape: 0.3566

Epoch 62/128

958/958 - 7s - 8ms/step - ia: 0.8934 - loss: 0.0649 - mae: 0.1510 - rmse: 0.2362 - smape: 0.3799 - val_ia: 0.7707 - val_loss: 0.0546 - val_mae: 0.1339 - val_rmse: 0.1962 - val_smape: 0.3541

Epoch 63/128

958/958 - 7s - 8ms/step - ia: 0.8936 - loss: 0.0644 - mae: 0.1507 - rmse: 0.2361 - smape: 0.3788 - val_ia: 0.7900 - val_loss: 0.0536 - val_mae: 0.1285 - val_rmse: 0.1932 - val_smape: 0.3470

Epoch 64/128

958/958 - 7s - 8ms/step - ia: 0.8943 - loss: 0.0637 - mae: 0.1498 - rmse: 0.2338 - smape: 0.3772 - val_ia: 0.7881 - val_loss: 0.0538 - val_mae: 0.1294 - val_rmse: 0.1931 - val_smape: 0.3471

Epoch 65/128

958/958 - 10s - 11ms/step - ia: 0.8938 - loss: 0.0643 - mae: 0.1506 - rmse: 0.2348 - smape: 0.3770 - val_ia: 0.7872 - val_loss: 0.0542 - val_mae: 0.1309 - val_rmse: 0.1944 - val_smape: 0.3518

Epoch 66/128

958/958 - 7s - 8ms/step - ia: 0.8936 - loss: 0.0644 - mae: 0.1508 - rmse: 0.2355 - smape: 0.3797 - val_ia: 0.7768 - val_loss: 0.0555 - val_mae: 0.1345 - val_rmse: 0.1964 - val_smape: 0.3537

Epoch 67/128

958/958 - 7s - 8ms/step - ia: 0.8935 - loss: 0.0650 - mae: 0.1510 - rmse: 0.2370 - smape: 0.3797 - val_ia: 0.7610 - val_loss: 0.0560 - val_mae: 0.1386 - val_rmse: 0.1994 - val_smape: 0.3605

Epoch 68/128

958/958 - 8s - 8ms/step - ia: 0.8939 - loss: 0.0641 - mae: 0.1505 - rmse: 0.2356 - smape: 0.3776 - val_ia: 0.7897 - val_loss: 0.0539 - val_mae: 0.1290 - val_rmse: 0.1937 - val_smape: 0.3495

Epoch 69/128

958/958 - 10s - 11ms/step - ia: 0.8937 - loss: 0.0644 - mae: 0.1505 - rmse: 0.2363 - smape: 0.3764 - val_ia: 0.7913 - val_loss: 0.0531 - val_mae: 0.1270 - val_rmse: 0.1925 - val_smape: 0.3447

Epoch 70/128

958/958 - 7s - 8ms/step - ia: 0.8934 - loss: 0.0639 - mae: 0.1505 - rmse: 0.2357 - smape: 0.3783 - val_ia: 0.7825 - val_loss: 0.0535 - val_mae: 0.1299 - val_rmse: 0.1945 - val_smape: 0.3513

Epoch 71/128

958/958 - 10s - 11ms/step - ia: 0.8940 - loss: 0.0638 - mae: 0.1499 - rmse: 0.2346 - smape: 0.3774 - val_ia: 0.7857 - val_loss: 0.0532 - val_mae: 0.1285 - val_rmse: 0.1934 - val_smape: 0.3480

Epoch 72/128

958/958 - 7s - 8ms/step - ia: 0.8945 - loss: 0.0641 - mae: 0.1499 - rmse: 0.2355 - smape: 0.3761 - val_ia: 0.7877 - val_loss: 0.0530 - val_mae: 0.1282 - val_rmse: 0.1926 - val_smape: 0.3469

Epoch 73/128

958/958 - 10s - 10ms/step - ia: 0.8939 - loss: 0.0643 - mae: 0.1507 - rmse: 0.2354 - smape: 0.3786 - val_ia: 0.7893 - val_loss: 0.0538 - val_mae: 0.1292 - val_rmse: 0.1935 - val_smape: 0.3471

Epoch 74/128

958/958 - 7s - 7ms/step - ia: 0.8947 - loss: 0.0629 - mae: 0.1495 - rmse: 0.2327 - smape: 0.3764 - val_ia: 0.7924 - val_loss: 0.0530 - val_mae: 0.1265 - val_rmse: 0.1924 - val_smape: 0.3435

Epoch 75/128

958/958 - 7s - 7ms/step - ia: 0.8938 - loss: 0.0638 - mae: 0.1503 - rmse: 0.2344 - smape: 0.3782 - val_ia: 0.7899 - val_loss: 0.0529 - val_mae: 0.1272 - val_rmse: 0.1927 - val_smape: 0.3461

Epoch 76/128

958/958 - 7s - 8ms/step - ia: 0.8940 - loss: 0.0641 - mae: 0.1505 - rmse: 0.2353 - smape: 0.3780 - val_ia: 0.7714 - val_loss: 0.0540 - val_mae: 0.1332 - val_rmse: 0.1960 - val_smape: 0.3558

Epoch 77/128

958/958 - 7s - 7ms/step - ia: 0.8941 - loss: 0.0640 - mae: 0.1502 - rmse: 0.2355 - smape: 0.3758 - val_ia: 0.7786 - val_loss: 0.0532 - val_mae: 0.1302 - val_rmse: 0.1939 - val_smape: 0.3503

Epoch 78/128

958/958 - 7s - 7ms/step - ia: 0.8956 - loss: 0.0629 - mae: 0.1488 - rmse: 0.2336 - smape: 0.3763 - val_ia: 0.7738 - val_loss: 0.0534 - val_mae: 0.1319 - val_rmse: 0.1951 - val_smape: 0.3543

Epoch 79/128

958/958 - 7s - 8ms/step - ia: 0.8945 - loss: 0.0628 - mae: 0.1498 - rmse: 0.2338 - smape: 0.3766 - val_ia: 0.7842 - val_loss: 0.0527 - val_mae: 0.1280 - val_rmse: 0.1923 - val_smape: 0.3464

Epoch 80/128

958/958 - 10s - 10ms/step - ia: 0.8943 - loss: 0.0639 - mae: 0.1498 - rmse: 0.2349 - smape: 0.3772 - val_ia: 0.7935 - val_loss: 0.0531 - val_mae: 0.1269 - val_rmse: 0.1927 - val_smape: 0.3440

Epoch 81/128

958/958 - 8s - 8ms/step - ia: 0.8949 - loss: 0.0636 - mae: 0.1494 - rmse: 0.2344 - smape: 0.3757 - val_ia: 0.7827 - val_loss: 0.0531 - val_mae: 0.1286 - val_rmse: 0.1936 - val_smape: 0.3481

Epoch 82/128

958/958 - 9s - 10ms/step - ia: 0.8949 - loss: 0.0634 - mae: 0.1497 - rmse: 0.2350 - smape: 0.3759 - val_ia: 0.7863 - val_loss: 0.0527 - val_mae: 0.1278 - val_rmse: 0.1924 - val_smape: 0.3461

Epoch 83/128

958/958 - 7s - 8ms/step - ia: 0.8945 - loss: 0.0635 - mae: 0.1498 - rmse: 0.2349 - smape: 0.3760 - val_ia: 0.7913 - val_loss: 0.0527 - val_mae: 0.1268 - val_rmse: 0.1920 - val_smape: 0.3444

Epoch 84/128

958/958 - 9s - 9ms/step - ia: 0.8953 - loss: 0.0627 - mae: 0.1488 - rmse: 0.2333 - smape: 0.3750 - val_ia: 0.7843 - val_loss: 0.0531 - val_mae: 0.1294 - val_rmse: 0.1936 - val_smape: 0.3509

Epoch 85/128

958/958 - 10s - 11ms/step - ia: 0.8950 - loss: 0.0634 - mae: 0.1491 - rmse: 0.2341 - smape: 0.3750 - val_ia: 0.7868 - val_loss: 0.0534 - val_mae: 0.1291 - val_rmse: 0.1927 - val_smape: 0.3467

Epoch 86/128

958/958 - 9s - 9ms/step - ia: 0.8950 - loss: 0.0626 - mae: 0.1486 - rmse: 0.2325 - smape: 0.3727 - val_ia: 0.7878 - val_loss: 0.0535 - val_mae: 0.1294 - val_rmse: 0.1929 - val_smape: 0.3472

Epoch 87/128

958/958 - 9s - 9ms/step - ia: 0.8942 - loss: 0.0637 - mae: 0.1496 - rmse: 0.2350 - smape: 0.3764 - val_ia: 0.7848 - val_loss: 0.0528 - val_mae: 0.1283 - val_rmse: 0.1928 - val_smape: 0.3469

Epoch 88/128

958/958 - 10s - 11ms/step - ia: 0.8950 - loss: 0.0630 - mae: 0.1489 - rmse: 0.2340 - smape: 0.3762 - val_ia: 0.7862 - val_loss: 0.0538 - val_mae: 0.1313 - val_rmse: 0.1948 - val_smape: 0.3504

Epoch 89/128

958/958 - 10s - 11ms/step - ia: 0.8951 - loss: 0.0627 - mae: 0.1489 - rmse: 0.2333 - smape: 0.3751 - val_ia: 0.7819 - val_loss: 0.0540 - val_mae: 0.1312 - val_rmse: 0.1936 - val_smape: 0.3485

Epoch 90/128

958/958 - 9s - 9ms/step - ia: 0.8947 - loss: 0.0627 - mae: 0.1489 - rmse: 0.2327 - smape: 0.3743 - val_ia: 0.7878 - val_loss: 0.0529 - val_mae: 0.1283 - val_rmse: 0.1918 - val_smape: 0.3462

Epoch 91/128

958/958 - 11s - 11ms/step - ia: 0.8954 - loss: 0.0623 - mae: 0.1484 - rmse: 0.2319 - smape: 0.3739 - val_ia: 0.7901 - val_loss: 0.0527 - val_mae: 0.1275 - val_rmse: 0.1915 - val_smape: 0.3456

Epoch 92/128

958/958 - 9s - 9ms/step - ia: 0.8953 - loss: 0.0630 - mae: 0.1488 - rmse: 0.2337 - smape: 0.3739 - val_ia: 0.7898 - val_loss: 0.0535 - val_mae: 0.1278 - val_rmse: 0.1945 - val_smape: 0.3475

Epoch 93/128

958/958 - 9s - 10ms/step - ia: 0.8954 - loss: 0.0627 - mae: 0.1485 - rmse: 0.2329 - smape: 0.3739 - val_ia: 0.7920 - val_loss: 0.0524 - val_mae: 0.1268 - val_rmse: 0.1914 - val_smape: 0.3459

Epoch 94/128

958/958 - 9s - 9ms/step - ia: 0.8953 - loss: 0.0626 - mae: 0.1489 - rmse: 0.2331 - smape: 0.3762 - val_ia: 0.7916 - val_loss: 0.0526 - val_mae: 0.1269 - val_rmse: 0.1918 - val_smape: 0.3436

Epoch 95/128

958/958 - 9s - 9ms/step - ia: 0.8956 - loss: 0.0628 - mae: 0.1490 - rmse: 0.2342 - smape: 0.3750 - val_ia: 0.7907 - val_loss: 0.0526 - val_mae: 0.1277 - val_rmse: 0.1917 - val_smape: 0.3453

Epoch 96/128

958/958 - 10s - 11ms/step - ia: 0.8958 - loss: 0.0626 - mae: 0.1487 - rmse: 0.2327 - smape: 0.3743 - val_ia: 0.7906 - val_loss: 0.0524 - val_mae: 0.1272 - val_rmse: 0.1911 - val_smape: 0.3455

Epoch 97/128

958/958 - 9s - 9ms/step - ia: 0.8953 - loss: 0.0625 - mae: 0.1486 - rmse: 0.2327 - smape: 0.3745 - val_ia: 0.7899 - val_loss: 0.0524 - val_mae: 0.1270 - val_rmse: 0.1914 - val_smape: 0.3444

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 24s - 100ms/step - ia: 0.6260 - loss: 0.4234 - mae: 0.4499 - rmse: 0.6343 - smape: 0.9438 - val_ia: 0.6402 - val_loss: 0.2304 - val_mae: 0.3430 - val_rmse: 0.4511 - val_smape: 0.7570

Epoch 2/16

240/240 - 4s - 16ms/step - ia: 0.7650 - loss: 0.2307 - mae: 0.3216 - rmse: 0.4740 - smape: 0.6850 - val_ia: 0.7404 - val_loss: 0.1359 - val_mae: 0.2491 - val_rmse: 0.3460 - val_smape: 0.5887

Epoch 3/16

240/240 - 3s - 12ms/step - ia: 0.8097 - loss: 0.1632 - mae: 0.2676 - rmse: 0.3985 - smape: 0.5959 - val_ia: 0.7840 - val_loss: 0.0916 - val_mae: 0.2031 - val_rmse: 0.2871 - val_smape: 0.5159

Epoch 4/16

240/240 - 3s - 14ms/step - ia: 0.8347 - loss: 0.1283 - mae: 0.2359 - rmse: 0.3526 - smape: 0.5385 - val_ia: 0.8205 - val_loss: 0.0755 - val_mae: 0.1731 - val_rmse: 0.2572 - val_smape: 0.4520

Epoch 5/16

240/240 - 4s - 15ms/step - ia: 0.8478 - loss: 0.1101 - mae: 0.2184 - rmse: 0.3257 - smape: 0.5093 - val_ia: 0.8311 - val_loss: 0.0677 - val_mae: 0.1633 - val_rmse: 0.2439 - val_smape: 0.4307

Epoch 6/16

240/240 - 5s - 22ms/step - ia: 0.8561 - loss: 0.1018 - mae: 0.2079 - rmse: 0.3138 - smape: 0.4861 - val_ia: 0.8453 - val_loss: 0.0626 - val_mae: 0.1522 - val_rmse: 0.2320 - val_smape: 0.4036

Epoch 7/16

240/240 - 3s - 14ms/step - ia: 0.8636 - loss: 0.0944 - mae: 0.1971 - rmse: 0.3016 - smape: 0.4643 - val_ia: 0.8498 - val_loss: 0.0589 - val_mae: 0.1478 - val_rmse: 0.2249 - val_smape: 0.3936

Epoch 8/16

240/240 - 4s - 15ms/step - ia: 0.8672 - loss: 0.0902 - mae: 0.1919 - rmse: 0.2945 - smape: 0.4508 - val_ia: 0.8574 - val_loss: 0.0579 - val_mae: 0.1427 - val_rmse: 0.2219 - val_smape: 0.3807

Epoch 9/16

240/240 - 3s - 15ms/step - ia: 0.8723 - loss: 0.0868 - mae: 0.1851 - rmse: 0.2883 - smape: 0.4366 - val_ia: 0.8648 - val_loss: 0.0569 - val_mae: 0.1378 - val_rmse: 0.2191 - val_smape: 0.3689

Epoch 10/16

240/240 - 5s - 23ms/step - ia: 0.8747 - loss: 0.0846 - mae: 0.1814 - rmse: 0.2850 - smape: 0.4290 - val_ia: 0.8679 - val_loss: 0.0545 - val_mae: 0.1338 - val_rmse: 0.2132 - val_smape: 0.3605

Epoch 11/16

240/240 - 4s - 15ms/step - ia: 0.8776 - loss: 0.0819 - mae: 0.1779 - rmse: 0.2805 - smape: 0.4211 - val_ia: 0.8553 - val_loss: 0.0564 - val_mae: 0.1431 - val_rmse: 0.2181 - val_smape: 0.3762

Epoch 12/16

240/240 - 3s - 11ms/step - ia: 0.8784 - loss: 0.0806 - mae: 0.1764 - rmse: 0.2779 - smape: 0.4171 - val_ia: 0.8517 - val_loss: 0.0581 - val_mae: 0.1464 - val_rmse: 0.2207 - val_smape: 0.3769

Epoch 13/16

240/240 - 4s - 15ms/step - ia: 0.8799 - loss: 0.0793 - mae: 0.1746 - rmse: 0.2755 - smape: 0.4145 - val_ia: 0.8635 - val_loss: 0.0556 - val_mae: 0.1385 - val_rmse: 0.2148 - val_smape: 0.3643

Epoch 14/16

240/240 - 3s - 14ms/step - ia: 0.8815 - loss: 0.0792 - mae: 0.1724 - rmse: 0.2741 - smape: 0.4085 - val_ia: 0.8715 - val_loss: 0.0545 - val_mae: 0.1319 - val_rmse: 0.2129 - val_smape: 0.3525

Epoch 15/16

240/240 - 5s - 22ms/step - ia: 0.8829 - loss: 0.0776 - mae: 0.1706 - rmse: 0.2721 - smape: 0.4049 - val_ia: 0.8711 - val_loss: 0.0544 - val_mae: 0.1332 - val_rmse: 0.2134 - val_smape: 0.3576

Epoch 16/16

240/240 - 3s - 13ms/step - ia: 0.8823 - loss: 0.0775 - mae: 0.1715 - rmse: 0.2725 - smape: 0.4077 - val_ia: 0.8350 - val_loss: 0.0617 - val_mae: 0.1597 - val_rmse: 0.2279 - val_smape: 0.3895

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 59s 439ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/8

 26%|██▌       | 13/50 [1:46:16<3:42:28, 360.78s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 7s - 29ms/step - ia: 0.5185 - loss: 0.5549 - mae: 0.5358 - rmse: 0.7253 - smape: 1.1132 - val_ia: 0.6106 - val_loss: 0.2660 - val_mae: 0.3659 - val_rmse: 0.4735 - val_smape: 0.7994

Epoch 2/8

240/240 - 4s - 18ms/step - ia: 0.6971 - loss: 0.3195 - mae: 0.3999 - rmse: 0.5594 - smape: 0.8323 - val_ia: 0.6708 - val_loss: 0.2160 - val_mae: 0.3191 - val_rmse: 0.4283 - val_smape: 0.7138

Epoch 3/8

240/240 - 3s - 11ms/step - ia: 0.7287 - loss: 0.2737 - mae: 0.3659 - rmse: 0.5188 - smape: 0.7669 - val_ia: 0.6999 - val_loss: 0.1883 - val_mae: 0.2938 - val_rmse: 0.4010 - val_smape: 0.6696

Epoch 4/8

240/240 - 2s - 9ms/step - ia: 0.7504 - loss: 0.2427 - mae: 0.3408 - rmse: 0.4883 - smape: 0.7212 - val_ia: 0.7186 - val_loss: 0.1677 - val_mae: 0.2751 - val_rmse: 0.3788 - val_smape: 0.6346

Epoch 5/8

240/240 - 3s - 12ms/step - ia: 0.7664 - loss: 0.2165 - mae: 0.3206 - rmse: 0.4613 - smape: 0.6864 - val_ia: 0.7328 - val_loss: 0.1514 - val_mae: 0.2605 - val_rmse: 0.3606 - val_smape: 0.6080

Epoch 6/8

240/240 - 2s - 10ms/step - ia: 0.7799 - loss: 0.1990 - mae: 0.3035 - rmse: 0.4414 - smape: 0.6563 - val_ia: 0.7502 - val_loss: 0.1368 - val_mae: 0.2449 - val_rmse: 0.3431 - val_smape: 0.5796

Epoch 7/8

240/240 - 2s - 10ms/step - ia: 0.7945 - loss: 0.1798 - mae: 0.2859 - rmse: 0.4190 - smape: 0.6263 - val_ia: 0.7631 - val_loss: 0.1265 - val_mae: 0.2329 - val_rmse: 0.3301 - val_smape: 0.5582

Epoch 8/8

240/240 - 2s - 9ms/step - ia: 0.8022 - loss: 0.1708 - mae: 0.2761 - rmse: 0.4080 - smape: 0.6071 - val_ia: 0.7707 - val_loss: 0.1188 - val_mae: 0.2251 - val_rmse: 0.3205 - val_smape: 0.5450

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 219ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/16

 28%|██▊       | 14/50 [1:46:44<2:35:59, 259.98s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

479/479 - 8s - 17ms/step - ia: 0.8140 - loss: 0.1572 - mae: 0.2554 - rmse: 0.3744 - smape: 0.5550 - val_ia: 0.8087 - val_loss: 0.0603 - val_mae: 0.1471 - val_rmse: 0.2204 - val_smape: 0.3883

Epoch 2/16

479/479 - 3s - 6ms/step - ia: 0.8569 - loss: 0.1020 - mae: 0.2033 - rmse: 0.3088 - smape: 0.4501 - val_ia: 0.8172 - val_loss: 0.0586 - val_mae: 0.1432 - val_rmse: 0.2135 - val_smape: 0.3711

Epoch 3/16

479/479 - 3s - 6ms/step - ia: 0.8629 - loss: 0.0981 - mae: 0.1960 - rmse: 0.3022 - smape: 0.4321 - val_ia: 0.8221 - val_loss: 0.0577 - val_mae: 0.1406 - val_rmse: 0.2109 - val_smape: 0.3658

Epoch 4/16

479/479 - 3s - 6ms/step - ia: 0.8632 - loss: 0.0984 - mae: 0.1960 - rmse: 0.3025 - smape: 0.4289 - val_ia: 0.8231 - val_loss: 0.0559 - val_mae: 0.1384 - val_rmse: 0.2103 - val_smape: 0.3682

Epoch 5/16

479/479 - 3s - 6ms/step - ia: 0.8626 - loss: 0.0988 - mae: 0.1962 - rmse: 0.3016 - smape: 0.4302 - val_ia: 0.8315 - val_loss: 0.0537 - val_mae: 0.1327 - val_rmse: 0.2043 - val_smape: 0.3547

Epoch 6/16

479/479 - 3s - 6ms/step - ia: 0.8629 - loss: 0.0964 - mae: 0.1960 - rmse: 0.3005 - smape: 0.4302 - val_ia: 0.8286 - val_loss: 0.0554 - val_mae: 0.1360 - val_rmse: 0.2085 - val_smape: 0.3652

Epoch 7/16

479/479 - 3s - 6ms/step - ia: 0.8647 - loss: 0.0957 - mae: 0.1936 - rmse: 0.2971 - smape: 0.4272 - val_ia: 0.8171 - val_loss: 0.0562 - val_mae: 0.1417 - val_rmse: 0.2095 - val_smape: 0.3664

Epoch 8/16

479/479 - 3s - 6ms/step - ia: 0.8637 - loss: 0.0959 - mae: 0.1946 - rmse: 0.2982 - smape: 0.4285 - val_ia: 0.8362 - val_loss: 0.0549 - val_mae: 0.1329 - val_rmse: 0.2060 - val_smape: 0.3542

Epoch 9/16

479/479 - 3s - 6ms/step - ia: 0.8635 - loss: 0.0960 - mae: 0.1949 - rmse: 0.3001 - smape: 0.4263 - val_ia: 0.8031 - val_loss: 0.0611 - val_mae: 0.1519 - val_rmse: 0.2175 - val_smape: 0.3776

Epoch 10/16

479/479 - 3s - 6ms/step - ia: 0.8651 - loss: 0.0927 - mae: 0.1925 - rmse: 0.2951 - smape: 0.4220 - val_ia: 0.8180 - val_loss: 0.0574 - val_mae: 0.1418 - val_rmse: 0.2107 - val_smape: 0.3648

Epoch 11/16

479/479 - 3s - 6ms/step - ia: 0.8658 - loss: 0.0930 - mae: 0.1923 - rmse: 0.2953 - smape: 0.4254 - val_ia: 0.8283 - val_loss: 0.0538 - val_mae: 0.1343 - val_rmse: 0.2050 - val_smape: 0.3575

Epoch 12/16

479/479 - 3s - 6ms/step - ia: 0.8641 - loss: 0.0960 - mae: 0.1941 - rmse: 0.2987 - smape: 0.4261 - val_ia: 0.8191 - val_loss: 0.0559 - val_mae: 0.1407 - val_rmse: 0.2088 - val_smape: 0.3677

Epoch 13/16

479/479 - 5s - 11ms/step - ia: 0.8658 - loss: 0.0929 - mae: 0.1917 - rmse: 0.2946 - smape: 0.4240 - val_ia: 0.8338 - val_loss: 0.0547 - val_mae: 0.1334 - val_rmse: 0.2049 - val_smape: 0.3500

Epoch 14/16

479/479 - 3s - 6ms/step - ia: 0.8644 - loss: 0.0949 - mae: 0.1937 - rmse: 0.2984 - smape: 0.4255 - val_ia: 0.8258 - val_loss: 0.0539 - val_mae: 0.1349 - val_rmse: 0.2053 - val_smape: 0.3563

Epoch 15/16

479/479 - 3s - 6ms/step - ia: 0.8651 - loss: 0.0949 - mae: 0.1928 - rmse: 0.2968 - smape: 0.4231 - val_ia: 0.8014 - val_loss: 0.0596 - val_mae: 0.1514 - val_rmse: 0.2163 - val_smape: 0.3792

Epoch 16/16

479/479 - 3s - 6ms/step - ia: 0.8639 - loss: 0.0944 - mae: 0.1948 - rmse: 0.2983 - smape: 0.4260 - val_ia: 0.8266 - val_loss: 0.0574 - val_mae: 0.1396 - val_rmse: 0.2084 - val_smape: 0.3571

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:02 461ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 30%|███       | 15/50 [1:47:38<1:55:37, 198.20s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3832/3832 - 31s - 8ms/step - ia: 0.7768 - loss: 0.1806 - mae: 0.2707 - rmse: 0.3650 - smape: 0.5699 - val_ia: 0.4788 - val_loss: 0.0756 - val_mae: 0.1763 - val_rmse: 0.2181 - val_smape: 0.4210

Epoch 2/256

3832/3832 - 23s - 6ms/step - ia: 0.8046 - loss: 0.1418 - mae: 0.2393 - rmse: 0.3248 - smape: 0.5117 - val_ia: 0.4499 - val_loss: 0.1020 - val_mae: 0.1933 - val_rmse: 0.2305 - val_smape: 0.4219

Epoch 3/256

3832/3832 - 23s - 6ms/step - ia: 0.8102 - loss: 0.1342 - mae: 0.2363 - rmse: 0.3194 - smape: 0.5120 - val_ia: 0.4602 - val_loss: 0.0801 - val_mae: 0.1779 - val_rmse: 0.2192 - val_smape: 0.4304

Epoch 4/256

3832/3832 - 25s - 6ms/step - ia: 0.8097 - loss: 0.1332 - mae: 0.2353 - rmse: 0.3177 - smape: 0.5115 - val_ia: 0.4961 - val_loss: 0.0674 - val_mae: 0.1573 - val_rmse: 0.1966 - val_smape: 0.3945

Epoch 5/256

3832/3832 - 27s - 7ms/step - ia: 0.8153 - loss: 0.1292 - mae: 0.2305 - rmse: 0.3120 - smape: 0.5026 - val_ia: 0.4905 - val_loss: 0.0763 - val_mae: 0.1693 - val_rmse: 0.2069 - val_smape: 0.4059

Epoch 6/256

3832/3832 - 39s - 10ms/step - ia: 0.3048 - loss: 18364.8438 - mae: 5.1701 - rmse: 11.5456 - smape: 1.1850 - val_ia: 0.1579 - val_loss: 43.7031 - val_mae: 1.8102 - val_rmse: 3.0003 - val_smape: 1.0989

Epoch 7/256

3832/3832 - 24s - 6ms/step - ia: 0.2732 - loss: 364.5813 - mae: 2.8935 - rmse: 6.3825 - smape: 1.1896 - val_ia: 0.1628 - val_loss: 35.3703 - val_mae: 1.4987 - val_rmse: 2.3373 - val_smape: 1.2168

Epoch 8/256

3832/3832 - 40s - 10ms/step - ia: 0.2315 - loss: 45.5572 - mae: 1.5062 - rmse: 2.7255 - smape: 1.5387 - val_ia: 0.1735 - val_loss: 6.7185 - val_mae: 0.9785 - val_rmse: 1.2546 - val_smape: 1.4512

Epoch 9/256

3832/3832 - 23s - 6ms/step - ia: 0.2594 - loss: 4.6385 - mae: 0.8909 - rmse: 1.2820 - smape: 1.5931 - val_ia: 0.1897 - val_loss: 0.9715 - val_mae: 0.7232 - val_rmse: 0.7800 - val_smape: 1.6602

Epoch 10/256

3832/3832 - 24s - 6ms/step - ia: 0.2507 - loss: 113.3488 - mae: 1.1577 - rmse: 1.8636 - smape: 1.6068 - val_ia: 0.1059 - val_loss: 169.1475 - val_mae: 3.8026 - val_rmse: 5.6879 - val_smape: 1.6167

Epoch 11/256

3832/3832 - 24s - 6ms/step - ia: 0.2220 - loss: 256.5627 - mae: 1.9254 - rmse: 3.5477 - smape: 1.5895 - val_ia: 0.1671 - val_loss: 8.8816 - val_mae: 0.9767 - val_rmse: 1.2067 - val_smape: 1.7304

Epoch 12/256

3832/3832 - 26s - 7ms/step - ia: 0.2184 - loss: 5.6111 - mae: 0.8957 - rmse: 1.2366 - smape: 1.7769 - val_ia: 0.1852 - val_loss: 1.0511 - val_mae: 0.7501 - val_rmse: 0.8063 - val_smape: 1.8741

Epoch 13/256

3832/3832 - 38s - 10ms/step - ia: 0.2219 - loss: 9.0825 - mae: 1.0554 - rmse: 1.5396 - smape: 1.6761 - val_ia: 0.1830 - val_loss: 0.9887 - val_mae: 0.7580 - val_rmse: 0.8067 - val_smape: 1.7761

Epoch 14/256

3832/3832 - 24s - 6ms/step - ia: 0.2193 - loss: 268.4360 - mae: 1.8264 - rmse: 3.1951 - smape: 1.7034 - val_ia: 0.0549 - val_loss: 3137.8577 - val_mae: 17.5492 - val_rmse: 28.2572 - val_smape: 1.6087

Epoch 15/256

3832/3832 - 25s - 6ms/step - ia: 0.1645 - loss: 1220.0325 - mae: 5.9568 - rmse: 11.4724 - smape: 1.5775 - val_ia: 0.1841 - val_loss: 1.0209 - val_mae: 0.7551 - val_rmse: 0.7964 - val_smape: 1.6760

Epoch 16/256

3832/3832 - 38s - 10ms/step - ia: 0.2082 - loss: 80.3991 - mae: 1.9867 - rmse: 3.2719 - smape: 1.7140 - val_ia: 0.1657 - val_loss: 3.1296 - val_mae: 0.9503 - val_rmse: 1.2110 - val_smape: 1.6812

Epoch 17/256

3832/3832 - 42s - 11ms/step - ia: 0.1758 - loss: 10698.7773 - mae: 6.2297 - rmse: 12.7535 - smape: 1.5970 - val_ia: 0.0920 - val_loss: 172.5920 - val_mae: 3.6194 - val_rmse: 5.9925 - val_smape: 1.5612

Epoch 18/256

3832/3832 - 23s - 6ms/step - ia: 0.1304 - loss: 86333032.0000 - mae: 113.6652 - rmse: 262.1416 - smape: 1.5202 - val_ia: 0.0734 - val_loss: 422.2146 - val_mae: 4.3520 - val_rmse: 8.1514 - val_smape: 1.3505

Epoch 19/256

3832/3832 - 41s - 11ms/step - ia: 0.1446 - loss: 870.2027 - mae: 5.9413 - rmse: 12.2758 - smape: 1.4892 - val_ia: 0.0885 - val_loss: 162.6355 - val_mae: 3.4294 - val_rmse: 6.2196 - val_smape: 1.3483

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:01 897ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 32%|███▏      | 16/50 [1:57:02<2:54:35, 308.11s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3832/3832 - 55s - 14ms/step - ia: 0.7865 - loss: 0.1567 - mae: 0.2566 - rmse: 0.3382 - smape: 0.5672 - val_ia: 0.5096 - val_loss: 0.0699 - val_mae: 0.1585 - val_rmse: 0.2020 - val_smape: 0.3877

Epoch 2/256

3832/3832 - 82s - 21ms/step - ia: 0.8380 - loss: 0.0959 - mae: 0.2002 - rmse: 0.2710 - smape: 0.4638 - val_ia: 0.5306 - val_loss: 0.0648 - val_mae: 0.1482 - val_rmse: 0.1934 - val_smape: 0.3683

Epoch 3/256

3832/3832 - 45s - 12ms/step - ia: 0.8466 - loss: 0.0905 - mae: 0.1916 - rmse: 0.2601 - smape: 0.4456 - val_ia: 0.4846 - val_loss: 0.0655 - val_mae: 0.1696 - val_rmse: 0.2059 - val_smape: 0.4089

Epoch 4/256

3832/3832 - 76s - 20ms/step - ia: 0.8494 - loss: 0.0877 - mae: 0.1880 - rmse: 0.2557 - smape: 0.4402 - val_ia: 0.5566 - val_loss: 0.0556 - val_mae: 0.1340 - val_rmse: 0.1763 - val_smape: 0.3555

Epoch 5/256

3832/3832 - 42s - 11ms/step - ia: 0.8508 - loss: 0.0863 - mae: 0.1848 - rmse: 0.2528 - smape: 0.4317 - val_ia: 0.5514 - val_loss: 0.0557 - val_mae: 0.1367 - val_rmse: 0.1755 - val_smape: 0.3574

Epoch 6/256

3832/3832 - 39s - 10ms/step - ia: 0.8526 - loss: 0.0828 - mae: 0.1827 - rmse: 0.2492 - smape: 0.4308 - val_ia: 0.5501 - val_loss: 0.0559 - val_mae: 0.1351 - val_rmse: 0.1755 - val_smape: 0.3566

Epoch 7/256

3832/3832 - 42s - 11ms/step - ia: 0.8544 - loss: 0.0837 - mae: 0.1809 - rmse: 0.2479 - smape: 0.4276 - val_ia: 0.5415 - val_loss: 0.0560 - val_mae: 0.1376 - val_rmse: 0.1779 - val_smape: 0.3573

Epoch 8/256

3832/3832 - 42s - 11ms/step - ia: 0.8552 - loss: 0.0816 - mae: 0.1797 - rmse: 0.2465 - smape: 0.4256 - val_ia: 0.5656 - val_loss: 0.0552 - val_mae: 0.1325 - val_rmse: 0.1746 - val_smape: 0.3484

Epoch 9/256

3832/3832 - 42s - 11ms/step - ia: 0.8575 - loss: 0.0798 - mae: 0.1771 - rmse: 0.2426 - smape: 0.4203 - val_ia: 0.5491 - val_loss: 0.0557 - val_mae: 0.1398 - val_rmse: 0.1801 - val_smape: 0.3704

Epoch 10/256

3832/3832 - 42s - 11ms/step - ia: 0.8592 - loss: 0.0775 - mae: 0.1757 - rmse: 0.2409 - smape: 0.4177 - val_ia: 0.5497 - val_loss: 0.0550 - val_mae: 0.1342 - val_rmse: 0.1740 - val_smape: 0.3530

Epoch 11/256

3832/3832 - 36s - 9ms/step - ia: 0.8592 - loss: 0.0776 - mae: 0.1751 - rmse: 0.2403 - smape: 0.4140 - val_ia: 0.5200 - val_loss: 0.0608 - val_mae: 0.1489 - val_rmse: 0.1888 - val_smape: 0.3842

Epoch 12/256

3832/3832 - 44s - 11ms/step - ia: 0.8597 - loss: 0.0774 - mae: 0.1750 - rmse: 0.2406 - smape: 0.4158 - val_ia: 0.5522 - val_loss: 0.0542 - val_mae: 0.1349 - val_rmse: 0.1758 - val_smape: 0.3555

Epoch 13/256

3832/3832 - 41s - 11ms/step - ia: 0.8613 - loss: 0.0762 - mae: 0.1728 - rmse: 0.2370 - smape: 0.4086 - val_ia: 0.5572 - val_loss: 0.0563 - val_mae: 0.1339 - val_rmse: 0.1755 - val_smape: 0.3597

Epoch 14/256

3832/3832 - 40s - 10ms/step - ia: 0.8609 - loss: 0.0770 - mae: 0.1737 - rmse: 0.2391 - smape: 0.4126 - val_ia: 0.5187 - val_loss: 0.0573 - val_mae: 0.1479 - val_rmse: 0.1881 - val_smape: 0.3844

Epoch 15/256

3832/3832 - 42s - 11ms/step - ia: 0.8626 - loss: 0.0764 - mae: 0.1715 - rmse: 0.2371 - smape: 0.4087 - val_ia: 0.4789 - val_loss: 0.0625 - val_mae: 0.1692 - val_rmse: 0.2072 - val_smape: 0.4402

Epoch 16/256

3832/3832 - 42s - 11ms/step - ia: 0.8637 - loss: 0.0751 - mae: 0.1708 - rmse: 0.2353 - smape: 0.4095 - val_ia: 0.5530 - val_loss: 0.0542 - val_mae: 0.1339 - val_rmse: 0.1748 - val_smape: 0.3564

Epoch 17/256

3832/3832 - 42s - 11ms/step - ia: 0.8632 - loss: 0.0749 - mae: 0.1707 - rmse: 0.2355 - smape: 0.4053 - val_ia: 0.5603 - val_loss: 0.0545 - val_mae: 0.1317 - val_rmse: 0.1724 - val_smape: 0.3492

Epoch 18/256

3832/3832 - 42s - 11ms/step - ia: 0.8634 - loss: 0.0745 - mae: 0.1713 - rmse: 0.2358 - smape: 0.4052 - val_ia: 0.5538 - val_loss: 0.0545 - val_mae: 0.1353 - val_rmse: 0.1741 - val_smape: 0.3647

Epoch 19/256

3832/3832 - 84s - 22ms/step - ia: 0.8629 - loss: 0.0736 - mae: 0.1700 - rmse: 0.2334 - smape: 0.4054 - val_ia: 0.5643 - val_loss: 0.0552 - val_mae: 0.1342 - val_rmse: 0.1757 - val_smape: 0.3484

Epoch 20/256

3832/3832 - 43s - 11ms/step - ia: 0.8629 - loss: 0.0728 - mae: 0.1693 - rmse: 0.2331 - smape: 0.4039 - val_ia: 0.5749 - val_loss: 0.0536 - val_mae: 0.1304 - val_rmse: 0.1718 - val_smape: 0.3580

Epoch 21/256

3832/3832 - 87s - 23ms/step - ia: 0.8651 - loss: 0.0727 - mae: 0.1694 - rmse: 0.2324 - smape: 0.4049 - val_ia: 0.5385 - val_loss: 0.0555 - val_mae: 0.1395 - val_rmse: 0.1788 - val_smape: 0.3710

Epoch 22/256

3832/3832 - 44s - 12ms/step - ia: 0.8633 - loss: 0.0729 - mae: 0.1689 - rmse: 0.2328 - smape: 0.4023 - val_ia: 0.5693 - val_loss: 0.0558 - val_mae: 0.1315 - val_rmse: 0.1726 - val_smape: 0.3557

Epoch 23/256

3832/3832 - 37s - 10ms/step - ia: 0.8649 - loss: 0.0718 - mae: 0.1689 - rmse: 0.2323 - smape: 0.4036 - val_ia: 0.5606 - val_loss: 0.0564 - val_mae: 0.1390 - val_rmse: 0.1789 - val_smape: 0.3576

Epoch 24/256

3832/3832 - 44s - 12ms/step - ia: 0.8653 - loss: 0.0716 - mae: 0.1684 - rmse: 0.2322 - smape: 0.4032 - val_ia: 0.5685 - val_loss: 0.0538 - val_mae: 0.1296 - val_rmse: 0.1706 - val_smape: 0.3465

Epoch 25/256

3832/3832 - 45s - 12ms/step - ia: 0.8669 - loss: 0.0694 - mae: 0.1659 - rmse: 0.2277 - smape: 0.4008 - val_ia: 0.5527 - val_loss: 0.0538 - val_mae: 0.1334 - val_rmse: 0.1733 - val_smape: 0.3528

Epoch 26/256

3832/3832 - 82s - 21ms/step - ia: 0.8648 - loss: 0.0708 - mae: 0.1679 - rmse: 0.2306 - smape: 0.4014 - val_ia: 0.5617 - val_loss: 0.0553 - val_mae: 0.1344 - val_rmse: 0.1748 - val_smape: 0.3524

Epoch 27/256

3832/3832 - 45s - 12ms/step - ia: 0.8663 - loss: 0.0704 - mae: 0.1663 - rmse: 0.2290 - smape: 0.3997 - val_ia: 0.5590 - val_loss: 0.0563 - val_mae: 0.1335 - val_rmse: 0.1760 - val_smape: 0.3484

Epoch 28/256

3832/3832 - 44s - 12ms/step - ia: 0.8657 - loss: 0.0701 - mae: 0.1664 - rmse: 0.2296 - smape: 0.4002 - val_ia: 0.5663 - val_loss: 0.0533 - val_mae: 0.1305 - val_rmse: 0.1710 - val_smape: 0.3532

Epoch 29/256

3832/3832 - 45s - 12ms/step - ia: 0.8661 - loss: 0.0692 - mae: 0.1666 - rmse: 0.2291 - smape: 0.4015 - val_ia: 0.5514 - val_loss: 0.0627 - val_mae: 0.1412 - val_rmse: 0.1822 - val_smape: 0.3591

Epoch 30/256

3832/3832 - 45s - 12ms/step - ia: 0.8676 - loss: 0.0694 - mae: 0.1651 - rmse: 0.2281 - smape: 0.3978 - val_ia: 0.5225 - val_loss: 0.0589 - val_mae: 0.1476 - val_rmse: 0.1876 - val_smape: 0.3735

Epoch 31/256

3832/3832 - 41s - 11ms/step - ia: 0.8675 - loss: 0.0699 - mae: 0.1658 - rmse: 0.2281 - smape: 0.3977 - val_ia: 0.5363 - val_loss: 0.0552 - val_mae: 0.1400 - val_rmse: 0.1783 - val_smape: 0.3684

Epoch 32/256

3832/3832 - 39s - 10ms/step - ia: 0.8671 - loss: 0.0694 - mae: 0.1648 - rmse: 0.2279 - smape: 0.3988 - val_ia: 0.5294 - val_loss: 0.0581 - val_mae: 0.1450 - val_rmse: 0.1861 - val_smape: 0.3880

Epoch 33/256

3832/3832 - 46s - 12ms/step - ia: 0.8671 - loss: 0.0676 - mae: 0.1652 - rmse: 0.2264 - smape: 0.3991 - val_ia: 0.5754 - val_loss: 0.0551 - val_mae: 0.1300 - val_rmse: 0.1716 - val_smape: 0.3451

Epoch 34/256

3832/3832 - 46s - 12ms/step - ia: 0.8689 - loss: 0.0671 - mae: 0.1628 - rmse: 0.2249 - smape: 0.3963 - val_ia: 0.5319 - val_loss: 0.0576 - val_mae: 0.1434 - val_rmse: 0.1815 - val_smape: 0.3710

Epoch 35/256

3832/3832 - 45s - 12ms/step - ia: 0.8676 - loss: 0.0680 - mae: 0.1647 - rmse: 0.2268 - smape: 0.3951 - val_ia: 0.5723 - val_loss: 0.0567 - val_mae: 0.1318 - val_rmse: 0.1731 - val_smape: 0.3490

Epoch 36/256

3832/3832 - 45s - 12ms/step - ia: 0.8679 - loss: 0.0665 - mae: 0.1639 - rmse: 0.2246 - smape: 0.3972 - val_ia: 0.5310 - val_loss: 0.0578 - val_mae: 0.1437 - val_rmse: 0.1828 - val_smape: 0.3770

Epoch 37/256

3832/3832 - 45s - 12ms/step - ia: 0.8686 - loss: 0.0688 - mae: 0.1644 - rmse: 0.2269 - smape: 0.3975 - val_ia: 0.5655 - val_loss: 0.0558 - val_mae: 0.1316 - val_rmse: 0.1721 - val_smape: 0.3485

Epoch 38/256

3832/3832 - 48s - 12ms/step - ia: 0.8703 - loss: 0.0666 - mae: 0.1624 - rmse: 0.2235 - smape: 0.3954 - val_ia: 0.5601 - val_loss: 0.0559 - val_mae: 0.1335 - val_rmse: 0.1738 - val_smape: 0.3580

Epoch 39/256

3832/3832 - 80s - 21ms/step - ia: 0.8683 - loss: 0.0669 - mae: 0.1639 - rmse: 0.2256 - smape: 0.3963 - val_ia: 0.5618 - val_loss: 0.0550 - val_mae: 0.1315 - val_rmse: 0.1724 - val_smape: 0.3498

Epoch 40/256

3832/3832 - 45s - 12ms/step - ia: 0.8693 - loss: 0.0660 - mae: 0.1629 - rmse: 0.2238 - smape: 0.3952 - val_ia: 0.5631 - val_loss: 0.0595 - val_mae: 0.1346 - val_rmse: 0.1757 - val_smape: 0.3537

Epoch 41/256

3832/3832 - 46s - 12ms/step - ia: 0.8677 - loss: 0.0671 - mae: 0.1638 - rmse: 0.2250 - smape: 0.3964 - val_ia: 0.5694 - val_loss: 0.0540 - val_mae: 0.1296 - val_rmse: 0.1707 - val_smape: 0.3502

Epoch 42/256

3832/3832 - 47s - 12ms/step - ia: 0.8694 - loss: 0.0668 - mae: 0.1628 - rmse: 0.2243 - smape: 0.3950 - val_ia: 0.5703 - val_loss: 0.0607 - val_mae: 0.1343 - val_rmse: 0.1757 - val_smape: 0.3491

Epoch 43/256

3832/3832 - 71s - 19ms/step - ia: 0.8695 - loss: 0.0662 - mae: 0.1625 - rmse: 0.2232 - smape: 0.3944 - val_ia: 0.5502 - val_loss: 0.0598 - val_mae: 0.1415 - val_rmse: 0.1826 - val_smape: 0.3680

Epoch 43: early stopping

Restoring model weights from the end of the best epoch: 28.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:46 2s/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 34%|███▍      | 17/50 [2:32:32<7:50:48, 856.01s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 32s - 133ms/step - ia: 0.1784 - loss: 1.0441 - mae: 0.7578 - rmse: 1.0149 - smape: 1.6060 - val_ia: 0.2615 - val_loss: 1.0101 - val_mae: 0.7526 - val_rmse: 0.8939 - val_smape: 1.7212

Epoch 2/16

240/240 - 3s - 14ms/step - ia: 0.1928 - loss: 1.0203 - mae: 0.7448 - rmse: 1.0032 - smape: 1.5815 - val_ia: 0.2697 - val_loss: 0.9792 - val_mae: 0.7389 - val_rmse: 0.8788 - val_smape: 1.6871

Epoch 3/16

240/240 - 5s - 22ms/step - ia: 0.2071 - loss: 0.9887 - mae: 0.7322 - rmse: 0.9881 - smape: 1.5591 - val_ia: 0.2784 - val_loss: 0.9493 - val_mae: 0.7254 - val_rmse: 0.8639 - val_smape: 1.6526

Epoch 4/16

240/240 - 3s - 13ms/step - ia: 0.2261 - loss: 0.9584 - mae: 0.7190 - rmse: 0.9716 - smape: 1.5300 - val_ia: 0.2879 - val_loss: 0.9204 - val_mae: 0.7120 - val_rmse: 0.8493 - val_smape: 1.6175

Epoch 5/16

240/240 - 5s - 22ms/step - ia: 0.2461 - loss: 0.9297 - mae: 0.7042 - rmse: 0.9576 - smape: 1.4969 - val_ia: 0.2980 - val_loss: 0.8920 - val_mae: 0.6987 - val_rmse: 0.8348 - val_smape: 1.5816

Epoch 6/16

240/240 - 6s - 24ms/step - ia: 0.2653 - loss: 0.9053 - mae: 0.6918 - rmse: 0.9447 - smape: 1.4652 - val_ia: 0.3087 - val_loss: 0.8642 - val_mae: 0.6854 - val_rmse: 0.8203 - val_smape: 1.5443

Epoch 7/16

240/240 - 4s - 15ms/step - ia: 0.2841 - loss: 0.8778 - mae: 0.6795 - rmse: 0.9300 - smape: 1.4397 - val_ia: 0.3195 - val_loss: 0.8370 - val_mae: 0.6722 - val_rmse: 0.8060 - val_smape: 1.5075

Epoch 8/16

240/240 - 3s - 12ms/step - ia: 0.3049 - loss: 0.8531 - mae: 0.6664 - rmse: 0.9161 - smape: 1.4068 - val_ia: 0.3305 - val_loss: 0.8101 - val_mae: 0.6588 - val_rmse: 0.7915 - val_smape: 1.4701

Epoch 9/16

240/240 - 3s - 13ms/step - ia: 0.3226 - loss: 0.8302 - mae: 0.6543 - rmse: 0.9041 - smape: 1.3748 - val_ia: 0.3416 - val_loss: 0.7841 - val_mae: 0.6456 - val_rmse: 0.7773 - val_smape: 1.4322

Epoch 10/16

240/240 - 3s - 12ms/step - ia: 0.3428 - loss: 0.8064 - mae: 0.6421 - rmse: 0.8921 - smape: 1.3446 - val_ia: 0.3530 - val_loss: 0.7580 - val_mae: 0.6323 - val_rmse: 0.7629 - val_smape: 1.3938

Epoch 11/16

240/240 - 3s - 12ms/step - ia: 0.3596 - loss: 0.7853 - mae: 0.6312 - rmse: 0.8793 - smape: 1.3179 - val_ia: 0.3646 - val_loss: 0.7324 - val_mae: 0.6189 - val_rmse: 0.7485 - val_smape: 1.3566

Epoch 12/16

240/240 - 3s - 13ms/step - ia: 0.3827 - loss: 0.7581 - mae: 0.6172 - rmse: 0.8638 - smape: 1.2832 - val_ia: 0.3761 - val_loss: 0.7072 - val_mae: 0.6056 - val_rmse: 0.7342 - val_smape: 1.3193

Epoch 13/16

240/240 - 5s - 21ms/step - ia: 0.3979 - loss: 0.7381 - mae: 0.6079 - rmse: 0.8519 - smape: 1.2614 - val_ia: 0.3876 - val_loss: 0.6827 - val_mae: 0.5922 - val_rmse: 0.7201 - val_smape: 1.2817

Epoch 14/16

240/240 - 5s - 22ms/step - ia: 0.4192 - loss: 0.7128 - mae: 0.5945 - rmse: 0.8380 - smape: 1.2232 - val_ia: 0.3993 - val_loss: 0.6585 - val_mae: 0.5789 - val_rmse: 0.7060 - val_smape: 1.2447

Epoch 15/16

240/240 - 5s - 22ms/step - ia: 0.4360 - loss: 0.6961 - mae: 0.5846 - rmse: 0.8270 - smape: 1.2019 - val_ia: 0.4112 - val_loss: 0.6352 - val_mae: 0.5659 - val_rmse: 0.6924 - val_smape: 1.2090

Epoch 16/16

240/240 - 5s - 22ms/step - ia: 0.4556 - loss: 0.6725 - mae: 0.5719 - rmse: 0.8133 - smape: 1.1678 - val_ia: 0.4233 - val_loss: 0.6129 - val_mae: 0.5531 - val_rmse: 0.6791 - val_smape: 1.1739

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:05 930ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 36%|███▌      | 18/50 [2:34:10<5:35:01, 628.17s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 12s - 26ms/step - ia: 0.7983 - loss: 0.1754 - mae: 0.2770 - rmse: 0.3888 - smape: 0.6141 - val_ia: 0.8190 - val_loss: 0.0657 - val_mae: 0.1486 - val_rmse: 0.2254 - val_smape: 0.3955

Epoch 2/16

479/479 - 9s - 19ms/step - ia: 0.8656 - loss: 0.0890 - mae: 0.1930 - rmse: 0.2884 - smape: 0.4676 - val_ia: 0.8209 - val_loss: 0.0585 - val_mae: 0.1397 - val_rmse: 0.2133 - val_smape: 0.3691

Epoch 3/16

479/479 - 6s - 12ms/step - ia: 0.8761 - loss: 0.0793 - mae: 0.1779 - rmse: 0.2707 - smape: 0.4346 - val_ia: 0.8181 - val_loss: 0.0576 - val_mae: 0.1411 - val_rmse: 0.2136 - val_smape: 0.3752

Epoch 4/16

479/479 - 6s - 12ms/step - ia: 0.8814 - loss: 0.0748 - mae: 0.1709 - rmse: 0.2628 - smape: 0.4213 - val_ia: 0.8280 - val_loss: 0.0565 - val_mae: 0.1365 - val_rmse: 0.2088 - val_smape: 0.3627

Epoch 5/16

479/479 - 6s - 12ms/step - ia: 0.8857 - loss: 0.0721 - mae: 0.1656 - rmse: 0.2576 - smape: 0.4094 - val_ia: 0.8331 - val_loss: 0.0555 - val_mae: 0.1329 - val_rmse: 0.2057 - val_smape: 0.3564

Epoch 6/16

479/479 - 7s - 14ms/step - ia: 0.8864 - loss: 0.0722 - mae: 0.1642 - rmse: 0.2577 - smape: 0.4038 - val_ia: 0.8073 - val_loss: 0.0575 - val_mae: 0.1454 - val_rmse: 0.2125 - val_smape: 0.3719

Epoch 7/16

479/479 - 6s - 13ms/step - ia: 0.8873 - loss: 0.0721 - mae: 0.1630 - rmse: 0.2566 - smape: 0.4015 - val_ia: 0.8408 - val_loss: 0.0554 - val_mae: 0.1304 - val_rmse: 0.2046 - val_smape: 0.3488

Epoch 8/16

479/479 - 10s - 21ms/step - ia: 0.8886 - loss: 0.0708 - mae: 0.1614 - rmse: 0.2548 - smape: 0.3964 - val_ia: 0.8092 - val_loss: 0.0574 - val_mae: 0.1445 - val_rmse: 0.2114 - val_smape: 0.3708

Epoch 9/16

479/479 - 6s - 13ms/step - ia: 0.8895 - loss: 0.0700 - mae: 0.1601 - rmse: 0.2536 - smape: 0.3921 - val_ia: 0.8295 - val_loss: 0.0553 - val_mae: 0.1339 - val_rmse: 0.2067 - val_smape: 0.3558

Epoch 10/16

479/479 - 10s - 21ms/step - ia: 0.8898 - loss: 0.0696 - mae: 0.1590 - rmse: 0.2526 - smape: 0.3912 - val_ia: 0.8422 - val_loss: 0.0549 - val_mae: 0.1297 - val_rmse: 0.2042 - val_smape: 0.3509

Epoch 11/16

479/479 - 6s - 12ms/step - ia: 0.8909 - loss: 0.0692 - mae: 0.1578 - rmse: 0.2511 - smape: 0.3897 - val_ia: 0.8438 - val_loss: 0.0547 - val_mae: 0.1290 - val_rmse: 0.2034 - val_smape: 0.3484

Epoch 12/16

479/479 - 11s - 22ms/step - ia: 0.8916 - loss: 0.0683 - mae: 0.1568 - rmse: 0.2505 - smape: 0.3862 - val_ia: 0.8101 - val_loss: 0.0603 - val_mae: 0.1483 - val_rmse: 0.2203 - val_smape: 0.3908

Epoch 13/16

479/479 - 11s - 22ms/step - ia: 0.8924 - loss: 0.0677 - mae: 0.1557 - rmse: 0.2490 - smape: 0.3850 - val_ia: 0.8315 - val_loss: 0.0570 - val_mae: 0.1370 - val_rmse: 0.2070 - val_smape: 0.3579

Epoch 14/16

479/479 - 10s - 21ms/step - ia: 0.8923 - loss: 0.0672 - mae: 0.1554 - rmse: 0.2484 - smape: 0.3835 - val_ia: 0.8329 - val_loss: 0.0544 - val_mae: 0.1328 - val_rmse: 0.2051 - val_smape: 0.3551

Epoch 15/16

479/479 - 6s - 13ms/step - ia: 0.8931 - loss: 0.0664 - mae: 0.1546 - rmse: 0.2472 - smape: 0.3828 - val_ia: 0.8381 - val_loss: 0.0555 - val_mae: 0.1334 - val_rmse: 0.2047 - val_smape: 0.3524

Epoch 16/16

479/479 - 6s - 12ms/step - ia: 0.8933 - loss: 0.0664 - mae: 0.1544 - rmse: 0.2467 - smape: 0.3820 - val_ia: 0.8419 - val_loss: 0.0548 - val_mae: 0.1314 - val_rmse: 0.2033 - val_smape: 0.3510

Restoring model weights from the end of the best epoch: 14.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:33 689ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

 38%|███▊      | 19/50 [2:36:20<4:07:18, 478.67s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3832/3832 - 70s - 18ms/step - ia: 0.5851 - loss: 0.5133 - mae: 0.4717 - rmse: 0.6214 - smape: 0.9118 - val_ia: 0.3539 - val_loss: 0.1843 - val_mae: 0.2636 - val_rmse: 0.3058 - val_smape: 0.5349

Epoch 2/32

3832/3832 - 78s - 20ms/step - ia: 0.7375 - loss: 0.2376 - mae: 0.3230 - rmse: 0.4309 - smape: 0.6561 - val_ia: 0.4049 - val_loss: 0.1211 - val_mae: 0.2115 - val_rmse: 0.2520 - val_smape: 0.4782

Epoch 3/32

3832/3832 - 80s - 21ms/step - ia: 0.7606 - loss: 0.1925 - mae: 0.2949 - rmse: 0.3900 - smape: 0.6270 - val_ia: 0.4233 - val_loss: 0.1022 - val_mae: 0.2011 - val_rmse: 0.2405 - val_smape: 0.4790

Epoch 4/32

3832/3832 - 42s - 11ms/step - ia: 0.7688 - loss: 0.1772 - mae: 0.2825 - rmse: 0.3736 - smape: 0.6094 - val_ia: 0.4580 - val_loss: 0.0867 - val_mae: 0.1733 - val_rmse: 0.2142 - val_smape: 0.4168

Epoch 5/32

3832/3832 - 43s - 11ms/step - ia: 0.7790 - loss: 0.1666 - mae: 0.2728 - rmse: 0.3620 - smape: 0.5875 - val_ia: 0.4555 - val_loss: 0.0841 - val_mae: 0.1737 - val_rmse: 0.2130 - val_smape: 0.4174

Epoch 6/32

3832/3832 - 42s - 11ms/step - ia: 0.7821 - loss: 0.1582 - mae: 0.2674 - rmse: 0.3525 - smape: 0.5785 - val_ia: 0.4708 - val_loss: 0.0787 - val_mae: 0.1670 - val_rmse: 0.2068 - val_smape: 0.4071

Epoch 7/32

3832/3832 - 41s - 11ms/step - ia: 0.7873 - loss: 0.1557 - mae: 0.2624 - rmse: 0.3483 - smape: 0.5691 - val_ia: 0.4725 - val_loss: 0.0757 - val_mae: 0.1654 - val_rmse: 0.2042 - val_smape: 0.4008

Epoch 8/32

3832/3832 - 47s - 12ms/step - ia: 0.7921 - loss: 0.1515 - mae: 0.2570 - rmse: 0.3431 - smape: 0.5569 - val_ia: 0.4787 - val_loss: 0.0728 - val_mae: 0.1637 - val_rmse: 0.2023 - val_smape: 0.3965

Epoch 9/32

3832/3832 - 46s - 12ms/step - ia: 0.7934 - loss: 0.1472 - mae: 0.2541 - rmse: 0.3382 - smape: 0.5531 - val_ia: 0.4911 - val_loss: 0.0723 - val_mae: 0.1582 - val_rmse: 0.1973 - val_smape: 0.3873

Epoch 10/32

3832/3832 - 43s - 11ms/step - ia: 0.7967 - loss: 0.1491 - mae: 0.2513 - rmse: 0.3373 - smape: 0.5470 - val_ia: 0.5018 - val_loss: 0.0686 - val_mae: 0.1543 - val_rmse: 0.1940 - val_smape: 0.3820

Epoch 11/32

3832/3832 - 41s - 11ms/step - ia: 0.7991 - loss: 0.1410 - mae: 0.2482 - rmse: 0.3306 - smape: 0.5468 - val_ia: 0.5007 - val_loss: 0.0712 - val_mae: 0.1571 - val_rmse: 0.1977 - val_smape: 0.3855

Epoch 12/32

3832/3832 - 42s - 11ms/step - ia: 0.8022 - loss: 0.1400 - mae: 0.2448 - rmse: 0.3281 - smape: 0.5391 - val_ia: 0.5050 - val_loss: 0.0669 - val_mae: 0.1529 - val_rmse: 0.1926 - val_smape: 0.3789

Epoch 13/32

3832/3832 - 41s - 11ms/step - ia: 0.8042 - loss: 0.1381 - mae: 0.2430 - rmse: 0.3271 - smape: 0.5322 - val_ia: 0.4969 - val_loss: 0.0714 - val_mae: 0.1596 - val_rmse: 0.1979 - val_smape: 0.3828

Epoch 14/32

3832/3832 - 42s - 11ms/step - ia: 0.8036 - loss: 0.1387 - mae: 0.2420 - rmse: 0.3258 - smape: 0.5294 - val_ia: 0.5148 - val_loss: 0.0657 - val_mae: 0.1484 - val_rmse: 0.1892 - val_smape: 0.3729

Epoch 15/32

3832/3832 - 38s - 10ms/step - ia: 0.8058 - loss: 0.1354 - mae: 0.2402 - rmse: 0.3226 - smape: 0.5290 - val_ia: 0.5118 - val_loss: 0.0650 - val_mae: 0.1500 - val_rmse: 0.1898 - val_smape: 0.3750

Epoch 16/32

3832/3832 - 37s - 10ms/step - ia: 0.8063 - loss: 0.1387 - mae: 0.2400 - rmse: 0.3233 - smape: 0.5268 - val_ia: 0.5146 - val_loss: 0.0652 - val_mae: 0.1488 - val_rmse: 0.1883 - val_smape: 0.3716

Epoch 17/32

3832/3832 - 42s - 11ms/step - ia: 0.8049 - loss: 0.1351 - mae: 0.2401 - rmse: 0.3222 - smape: 0.5282 - val_ia: 0.5078 - val_loss: 0.0649 - val_mae: 0.1507 - val_rmse: 0.1896 - val_smape: 0.3766

Epoch 18/32

3832/3832 - 33s - 9ms/step - ia: 0.8098 - loss: 0.1301 - mae: 0.2357 - rmse: 0.3161 - smape: 0.5210 - val_ia: 0.5209 - val_loss: 0.0632 - val_mae: 0.1457 - val_rmse: 0.1859 - val_smape: 0.3696

Epoch 19/32

3832/3832 - 38s - 10ms/step - ia: 0.8100 - loss: 0.1318 - mae: 0.2367 - rmse: 0.3166 - smape: 0.5207 - val_ia: 0.5187 - val_loss: 0.0622 - val_mae: 0.1458 - val_rmse: 0.1856 - val_smape: 0.3693

Epoch 20/32

3832/3832 - 31s - 8ms/step - ia: 0.8124 - loss: 0.1275 - mae: 0.2329 - rmse: 0.3127 - smape: 0.5145 - val_ia: 0.5157 - val_loss: 0.0627 - val_mae: 0.1475 - val_rmse: 0.1874 - val_smape: 0.3719

Epoch 21/32

3832/3832 - 38s - 10ms/step - ia: 0.8108 - loss: 0.1335 - mae: 0.2348 - rmse: 0.3174 - smape: 0.5132 - val_ia: 0.5191 - val_loss: 0.0624 - val_mae: 0.1457 - val_rmse: 0.1853 - val_smape: 0.3678

Epoch 22/32

3832/3832 - 39s - 10ms/step - ia: 0.8087 - loss: 0.1304 - mae: 0.2338 - rmse: 0.3151 - smape: 0.5155 - val_ia: 0.5232 - val_loss: 0.0619 - val_mae: 0.1440 - val_rmse: 0.1839 - val_smape: 0.3679

Epoch 23/32

3832/3832 - 40s - 10ms/step - ia: 0.8126 - loss: 0.1277 - mae: 0.2305 - rmse: 0.3114 - smape: 0.5111 - val_ia: 0.5308 - val_loss: 0.0630 - val_mae: 0.1430 - val_rmse: 0.1840 - val_smape: 0.3611

Epoch 24/32

3832/3832 - 38s - 10ms/step - ia: 0.8126 - loss: 0.1313 - mae: 0.2322 - rmse: 0.3135 - smape: 0.5102 - val_ia: 0.5112 - val_loss: 0.0641 - val_mae: 0.1503 - val_rmse: 0.1906 - val_smape: 0.3744

Epoch 25/32

3832/3832 - 33s - 9ms/step - ia: 0.8155 - loss: 0.1269 - mae: 0.2298 - rmse: 0.3090 - smape: 0.5103 - val_ia: 0.5203 - val_loss: 0.0616 - val_mae: 0.1461 - val_rmse: 0.1858 - val_smape: 0.3675

Epoch 26/32

3832/3832 - 39s - 10ms/step - ia: 0.8158 - loss: 0.1223 - mae: 0.2277 - rmse: 0.3057 - smape: 0.5072 - val_ia: 0.5140 - val_loss: 0.0618 - val_mae: 0.1487 - val_rmse: 0.1871 - val_smape: 0.3757

Epoch 27/32

3832/3832 - 40s - 10ms/step - ia: 0.8159 - loss: 0.1257 - mae: 0.2273 - rmse: 0.3066 - smape: 0.5031 - val_ia: 0.5252 - val_loss: 0.0604 - val_mae: 0.1434 - val_rmse: 0.1829 - val_smape: 0.3645

Epoch 28/32

3832/3832 - 39s - 10ms/step - ia: 0.8170 - loss: 0.1260 - mae: 0.2276 - rmse: 0.3077 - smape: 0.5068 - val_ia: 0.5234 - val_loss: 0.0609 - val_mae: 0.1441 - val_rmse: 0.1838 - val_smape: 0.3662

Epoch 29/32

3832/3832 - 40s - 10ms/step - ia: 0.8166 - loss: 0.1231 - mae: 0.2271 - rmse: 0.3063 - smape: 0.5026 - val_ia: 0.5187 - val_loss: 0.0615 - val_mae: 0.1468 - val_rmse: 0.1853 - val_smape: 0.3687

Epoch 30/32

3832/3832 - 36s - 9ms/step - ia: 0.8174 - loss: 0.1240 - mae: 0.2267 - rmse: 0.3058 - smape: 0.5048 - val_ia: 0.5161 - val_loss: 0.0608 - val_mae: 0.1476 - val_rmse: 0.1863 - val_smape: 0.3733

Epoch 31/32

3832/3832 - 35s - 9ms/step - ia: 0.8173 - loss: 0.1247 - mae: 0.2255 - rmse: 0.3048 - smape: 0.5002 - val_ia: 0.5274 - val_loss: 0.0614 - val_mae: 0.1441 - val_rmse: 0.1830 - val_smape: 0.3622

Epoch 32/32

3832/3832 - 39s - 10ms/step - ia: 0.8146 - loss: 0.1279 - mae: 0.2291 - rmse: 0.3099 - smape: 0.5044 - val_ia: 0.5200 - val_loss: 0.0600 - val_mae: 0.1450 - val_rmse: 0.1847 - val_smape: 0.3669

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:55 1s/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 40%|████      | 20/50 [2:59:17<6:14:11, 748.38s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1916/1916 - 42s - 22ms/step - ia: 0.1909 - loss: 0.9698 - mae: 0.7378 - rmse: 0.9456 - smape: 1.7914 - val_ia: 0.2302 - val_loss: 0.8315 - val_mae: 0.6867 - val_rmse: 0.7450 - val_smape: 1.6431

Epoch 2/256

1916/1916 - 25s - 13ms/step - ia: 0.6201 - loss: 0.4089 - mae: 0.4330 - rmse: 0.5943 - smape: 0.9099 - val_ia: 0.3577 - val_loss: 0.2445 - val_mae: 0.3331 - val_rmse: 0.4009 - val_smape: 0.7210

Epoch 3/256

1916/1916 - 31s - 16ms/step - ia: 0.7445 - loss: 0.2533 - mae: 0.3308 - rmse: 0.4715 - smape: 0.6999 - val_ia: 0.4082 - val_loss: 0.2046 - val_mae: 0.2967 - val_rmse: 0.3631 - val_smape: 0.6547

Epoch 4/256

1916/1916 - 42s - 22ms/step - ia: 0.7744 - loss: 0.2077 - mae: 0.2950 - rmse: 0.4243 - smape: 0.6431 - val_ia: 0.4504 - val_loss: 0.1663 - val_mae: 0.2641 - val_rmse: 0.3288 - val_smape: 0.6032

Epoch 5/256

1916/1916 - 33s - 17ms/step - ia: 0.8012 - loss: 0.1709 - mae: 0.2623 - rmse: 0.3816 - smape: 0.5888 - val_ia: 0.4763 - val_loss: 0.1380 - val_mae: 0.2446 - val_rmse: 0.3067 - val_smape: 0.5823

Epoch 6/256

1916/1916 - 33s - 17ms/step - ia: 0.8235 - loss: 0.1428 - mae: 0.2340 - rmse: 0.3454 - smape: 0.5366 - val_ia: 0.5067 - val_loss: 0.1186 - val_mae: 0.2254 - val_rmse: 0.2855 - val_smape: 0.5491

Epoch 7/256

1916/1916 - 32s - 17ms/step - ia: 0.8409 - loss: 0.1226 - mae: 0.2129 - rmse: 0.3169 - smape: 0.4982 - val_ia: 0.5662 - val_loss: 0.0994 - val_mae: 0.1934 - val_rmse: 0.2532 - val_smape: 0.4758

Epoch 8/256

1916/1916 - 32s - 17ms/step - ia: 0.8550 - loss: 0.1077 - mae: 0.1954 - rmse: 0.2940 - smape: 0.4650 - val_ia: 0.5956 - val_loss: 0.0885 - val_mae: 0.1788 - val_rmse: 0.2373 - val_smape: 0.4464

Epoch 9/256

1916/1916 - 33s - 17ms/step - ia: 0.8659 - loss: 0.0966 - mae: 0.1811 - rmse: 0.2762 - smape: 0.4367 - val_ia: 0.6139 - val_loss: 0.0805 - val_mae: 0.1685 - val_rmse: 0.2257 - val_smape: 0.4264

Epoch 10/256

1916/1916 - 40s - 21ms/step - ia: 0.8732 - loss: 0.0887 - mae: 0.1712 - rmse: 0.2644 - smape: 0.4165 - val_ia: 0.6329 - val_loss: 0.0742 - val_mae: 0.1591 - val_rmse: 0.2161 - val_smape: 0.4086

Epoch 11/256

1916/1916 - 33s - 17ms/step - ia: 0.8790 - loss: 0.0827 - mae: 0.1640 - rmse: 0.2533 - smape: 0.4034 - val_ia: 0.6442 - val_loss: 0.0704 - val_mae: 0.1542 - val_rmse: 0.2093 - val_smape: 0.3991

Epoch 12/256

1916/1916 - 30s - 15ms/step - ia: 0.8835 - loss: 0.0782 - mae: 0.1577 - rmse: 0.2452 - smape: 0.3910 - val_ia: 0.6619 - val_loss: 0.0664 - val_mae: 0.1470 - val_rmse: 0.2025 - val_smape: 0.3845

Epoch 13/256

1916/1916 - 33s - 17ms/step - ia: 0.8872 - loss: 0.0747 - mae: 0.1536 - rmse: 0.2394 - smape: 0.3825 - val_ia: 0.6738 - val_loss: 0.0643 - val_mae: 0.1440 - val_rmse: 0.1988 - val_smape: 0.3783

Epoch 14/256

1916/1916 - 32s - 17ms/step - ia: 0.8902 - loss: 0.0719 - mae: 0.1490 - rmse: 0.2345 - smape: 0.3750 - val_ia: 0.6748 - val_loss: 0.0618 - val_mae: 0.1389 - val_rmse: 0.1953 - val_smape: 0.3672

Epoch 15/256

1916/1916 - 32s - 17ms/step - ia: 0.8926 - loss: 0.0699 - mae: 0.1466 - rmse: 0.2307 - smape: 0.3700 - val_ia: 0.6808 - val_loss: 0.0602 - val_mae: 0.1366 - val_rmse: 0.1921 - val_smape: 0.3627

Epoch 16/256

1916/1916 - 32s - 17ms/step - ia: 0.8946 - loss: 0.0683 - mae: 0.1437 - rmse: 0.2261 - smape: 0.3633 - val_ia: 0.6929 - val_loss: 0.0594 - val_mae: 0.1347 - val_rmse: 0.1898 - val_smape: 0.3595

Epoch 17/256

1916/1916 - 32s - 17ms/step - ia: 0.8955 - loss: 0.0671 - mae: 0.1431 - rmse: 0.2250 - smape: 0.3612 - val_ia: 0.6947 - val_loss: 0.0584 - val_mae: 0.1332 - val_rmse: 0.1879 - val_smape: 0.3569

Epoch 18/256

1916/1916 - 33s - 17ms/step - ia: 0.8966 - loss: 0.0662 - mae: 0.1416 - rmse: 0.2235 - smape: 0.3593 - val_ia: 0.6689 - val_loss: 0.0583 - val_mae: 0.1371 - val_rmse: 0.1916 - val_smape: 0.3605

Epoch 19/256

1916/1916 - 32s - 17ms/step - ia: 0.8972 - loss: 0.0656 - mae: 0.1407 - rmse: 0.2217 - smape: 0.3583 - val_ia: 0.6963 - val_loss: 0.0572 - val_mae: 0.1309 - val_rmse: 0.1858 - val_smape: 0.3515

Epoch 20/256

1916/1916 - 26s - 14ms/step - ia: 0.8980 - loss: 0.0650 - mae: 0.1397 - rmse: 0.2209 - smape: 0.3560 - val_ia: 0.6941 - val_loss: 0.0570 - val_mae: 0.1313 - val_rmse: 0.1854 - val_smape: 0.3519

Epoch 21/256

1916/1916 - 32s - 17ms/step - ia: 0.8970 - loss: 0.0647 - mae: 0.1396 - rmse: 0.2197 - smape: 0.3559 - val_ia: 0.6963 - val_loss: 0.0566 - val_mae: 0.1300 - val_rmse: 0.1848 - val_smape: 0.3494

Epoch 22/256

1916/1916 - 41s - 21ms/step - ia: 0.8983 - loss: 0.0643 - mae: 0.1391 - rmse: 0.2199 - smape: 0.3558 - val_ia: 0.6994 - val_loss: 0.0570 - val_mae: 0.1312 - val_rmse: 0.1853 - val_smape: 0.3535

Epoch 23/256

1916/1916 - 32s - 17ms/step - ia: 0.8983 - loss: 0.0641 - mae: 0.1390 - rmse: 0.2187 - smape: 0.3553 - val_ia: 0.6955 - val_loss: 0.0562 - val_mae: 0.1291 - val_rmse: 0.1844 - val_smape: 0.3477

Epoch 24/256

1916/1916 - 32s - 17ms/step - ia: 0.8983 - loss: 0.0640 - mae: 0.1390 - rmse: 0.2183 - smape: 0.3552 - val_ia: 0.6894 - val_loss: 0.0564 - val_mae: 0.1305 - val_rmse: 0.1854 - val_smape: 0.3491

Epoch 25/256

1916/1916 - 32s - 17ms/step - ia: 0.8982 - loss: 0.0637 - mae: 0.1387 - rmse: 0.2181 - smape: 0.3545 - val_ia: 0.7020 - val_loss: 0.0563 - val_mae: 0.1292 - val_rmse: 0.1837 - val_smape: 0.3491

Epoch 26/256

1916/1916 - 32s - 17ms/step - ia: 0.8983 - loss: 0.0637 - mae: 0.1385 - rmse: 0.2188 - smape: 0.3537 - val_ia: 0.6795 - val_loss: 0.0569 - val_mae: 0.1329 - val_rmse: 0.1883 - val_smape: 0.3541

Epoch 27/256

1916/1916 - 37s - 19ms/step - ia: 0.8983 - loss: 0.0634 - mae: 0.1385 - rmse: 0.2182 - smape: 0.3550 - val_ia: 0.7040 - val_loss: 0.0561 - val_mae: 0.1275 - val_rmse: 0.1830 - val_smape: 0.3450

Epoch 28/256

1916/1916 - 29s - 15ms/step - ia: 0.8986 - loss: 0.0635 - mae: 0.1385 - rmse: 0.2178 - smape: 0.3541 - val_ia: 0.6960 - val_loss: 0.0572 - val_mae: 0.1329 - val_rmse: 0.1862 - val_smape: 0.3572

Epoch 29/256

1916/1916 - 33s - 17ms/step - ia: 0.8984 - loss: 0.0634 - mae: 0.1383 - rmse: 0.2173 - smape: 0.3541 - val_ia: 0.6974 - val_loss: 0.0561 - val_mae: 0.1294 - val_rmse: 0.1835 - val_smape: 0.3486

Epoch 30/256

1916/1916 - 40s - 21ms/step - ia: 0.8990 - loss: 0.0634 - mae: 0.1385 - rmse: 0.2181 - smape: 0.3554 - val_ia: 0.7008 - val_loss: 0.0561 - val_mae: 0.1292 - val_rmse: 0.1833 - val_smape: 0.3492

Epoch 31/256

1916/1916 - 33s - 17ms/step - ia: 0.8979 - loss: 0.0633 - mae: 0.1385 - rmse: 0.2182 - smape: 0.3551 - val_ia: 0.6967 - val_loss: 0.0558 - val_mae: 0.1285 - val_rmse: 0.1833 - val_smape: 0.3466

Epoch 32/256

1916/1916 - 28s - 14ms/step - ia: 0.8986 - loss: 0.0631 - mae: 0.1384 - rmse: 0.2180 - smape: 0.3547 - val_ia: 0.6666 - val_loss: 0.0606 - val_mae: 0.1461 - val_rmse: 0.1973 - val_smape: 0.3831

Epoch 33/256

1916/1916 - 46s - 24ms/step - ia: 0.8985 - loss: 0.0631 - mae: 0.1386 - rmse: 0.2177 - smape: 0.3547 - val_ia: 0.6907 - val_loss: 0.0561 - val_mae: 0.1295 - val_rmse: 0.1849 - val_smape: 0.3479

Epoch 34/256

1916/1916 - 33s - 17ms/step - ia: 0.8985 - loss: 0.0631 - mae: 0.1387 - rmse: 0.2177 - smape: 0.3546 - val_ia: 0.7010 - val_loss: 0.0563 - val_mae: 0.1299 - val_rmse: 0.1839 - val_smape: 0.3516

Epoch 35/256

1916/1916 - 34s - 18ms/step - ia: 0.8980 - loss: 0.0632 - mae: 0.1388 - rmse: 0.2180 - smape: 0.3561 - val_ia: 0.6904 - val_loss: 0.0579 - val_mae: 0.1358 - val_rmse: 0.1884 - val_smape: 0.3639

Epoch 36/256

1916/1916 - 38s - 20ms/step - ia: 0.8986 - loss: 0.0630 - mae: 0.1382 - rmse: 0.2175 - smape: 0.3535 - val_ia: 0.6642 - val_loss: 0.0578 - val_mae: 0.1379 - val_rmse: 0.1925 - val_smape: 0.3671

Epoch 37/256

1916/1916 - 35s - 18ms/step - ia: 0.8988 - loss: 0.0630 - mae: 0.1385 - rmse: 0.2174 - smape: 0.3553 - val_ia: 0.6832 - val_loss: 0.0561 - val_mae: 0.1314 - val_rmse: 0.1860 - val_smape: 0.3514

Epoch 38/256

1916/1916 - 35s - 18ms/step - ia: 0.8985 - loss: 0.0629 - mae: 0.1386 - rmse: 0.2176 - smape: 0.3549 - val_ia: 0.6811 - val_loss: 0.0563 - val_mae: 0.1321 - val_rmse: 0.1867 - val_smape: 0.3528

Epoch 39/256

1916/1916 - 35s - 18ms/step - ia: 0.8984 - loss: 0.0627 - mae: 0.1383 - rmse: 0.2169 - smape: 0.3537 - val_ia: 0.6476 - val_loss: 0.0589 - val_mae: 0.1438 - val_rmse: 0.1972 - val_smape: 0.3793

Epoch 40/256

1916/1916 - 34s - 18ms/step - ia: 0.8987 - loss: 0.0628 - mae: 0.1386 - rmse: 0.2169 - smape: 0.3550 - val_ia: 0.6980 - val_loss: 0.0565 - val_mae: 0.1312 - val_rmse: 0.1845 - val_smape: 0.3540

Epoch 41/256

1916/1916 - 41s - 21ms/step - ia: 0.8988 - loss: 0.0628 - mae: 0.1384 - rmse: 0.2167 - smape: 0.3544 - val_ia: 0.6958 - val_loss: 0.0555 - val_mae: 0.1283 - val_rmse: 0.1828 - val_smape: 0.3465

Epoch 42/256

1916/1916 - 33s - 17ms/step - ia: 0.8992 - loss: 0.0627 - mae: 0.1382 - rmse: 0.2165 - smape: 0.3551 - val_ia: 0.6512 - val_loss: 0.0584 - val_mae: 0.1422 - val_rmse: 0.1957 - val_smape: 0.3756

Epoch 43/256

1916/1916 - 32s - 17ms/step - ia: 0.8990 - loss: 0.0629 - mae: 0.1386 - rmse: 0.2168 - smape: 0.3557 - val_ia: 0.6958 - val_loss: 0.0555 - val_mae: 0.1284 - val_rmse: 0.1829 - val_smape: 0.3464

Epoch 44/256

1916/1916 - 35s - 18ms/step - ia: 0.8985 - loss: 0.0627 - mae: 0.1385 - rmse: 0.2174 - smape: 0.3541 - val_ia: 0.6994 - val_loss: 0.0554 - val_mae: 0.1277 - val_rmse: 0.1825 - val_smape: 0.3457

Epoch 45/256

1916/1916 - 34s - 18ms/step - ia: 0.8993 - loss: 0.0625 - mae: 0.1380 - rmse: 0.2167 - smape: 0.3541 - val_ia: 0.6783 - val_loss: 0.0568 - val_mae: 0.1332 - val_rmse: 0.1884 - val_smape: 0.3563

Epoch 46/256

1916/1916 - 32s - 17ms/step - ia: 0.8990 - loss: 0.0625 - mae: 0.1380 - rmse: 0.2168 - smape: 0.3549 - val_ia: 0.6956 - val_loss: 0.0554 - val_mae: 0.1283 - val_rmse: 0.1829 - val_smape: 0.3463

Epoch 47/256

1916/1916 - 36s - 19ms/step - ia: 0.8988 - loss: 0.0626 - mae: 0.1384 - rmse: 0.2165 - smape: 0.3553 - val_ia: 0.6836 - val_loss: 0.0559 - val_mae: 0.1311 - val_rmse: 0.1857 - val_smape: 0.3511

Epoch 48/256

1916/1916 - 33s - 17ms/step - ia: 0.8981 - loss: 0.0625 - mae: 0.1383 - rmse: 0.2166 - smape: 0.3546 - val_ia: 0.6994 - val_loss: 0.0555 - val_mae: 0.1284 - val_rmse: 0.1824 - val_smape: 0.3468

Epoch 49/256

1916/1916 - 35s - 18ms/step - ia: 0.8982 - loss: 0.0624 - mae: 0.1384 - rmse: 0.2168 - smape: 0.3551 - val_ia: 0.7021 - val_loss: 0.0554 - val_mae: 0.1278 - val_rmse: 0.1821 - val_smape: 0.3465

Epoch 50/256

1916/1916 - 34s - 18ms/step - ia: 0.8993 - loss: 0.0624 - mae: 0.1380 - rmse: 0.2162 - smape: 0.3537 - val_ia: 0.7006 - val_loss: 0.0556 - val_mae: 0.1289 - val_rmse: 0.1826 - val_smape: 0.3481

Epoch 51/256

1916/1916 - 36s - 19ms/step - ia: 0.8989 - loss: 0.0624 - mae: 0.1383 - rmse: 0.2173 - smape: 0.3537 - val_ia: 0.6506 - val_loss: 0.0592 - val_mae: 0.1432 - val_rmse: 0.1975 - val_smape: 0.3804

Epoch 52/256

1916/1916 - 33s - 17ms/step - ia: 0.8987 - loss: 0.0624 - mae: 0.1382 - rmse: 0.2164 - smape: 0.3544 - val_ia: 0.6877 - val_loss: 0.0558 - val_mae: 0.1302 - val_rmse: 0.1850 - val_smape: 0.3498

Epoch 53/256

1916/1916 - 31s - 16ms/step - ia: 0.8995 - loss: 0.0622 - mae: 0.1373 - rmse: 0.2153 - smape: 0.3527 - val_ia: 0.6577 - val_loss: 0.0576 - val_mae: 0.1397 - val_rmse: 0.1931 - val_smape: 0.3701

Epoch 54/256

1916/1916 - 34s - 18ms/step - ia: 0.8991 - loss: 0.0622 - mae: 0.1377 - rmse: 0.2166 - smape: 0.3538 - val_ia: 0.7014 - val_loss: 0.0552 - val_mae: 0.1273 - val_rmse: 0.1818 - val_smape: 0.3454

Epoch 55/256

1916/1916 - 31s - 16ms/step - ia: 0.8990 - loss: 0.0623 - mae: 0.1380 - rmse: 0.2166 - smape: 0.3549 - val_ia: 0.7031 - val_loss: 0.0554 - val_mae: 0.1278 - val_rmse: 0.1820 - val_smape: 0.3466

Epoch 56/256

1916/1916 - 34s - 18ms/step - ia: 0.8986 - loss: 0.0623 - mae: 0.1383 - rmse: 0.2158 - smape: 0.3550 - val_ia: 0.7019 - val_loss: 0.0553 - val_mae: 0.1279 - val_rmse: 0.1820 - val_smape: 0.3461

Epoch 57/256

1916/1916 - 32s - 17ms/step - ia: 0.8996 - loss: 0.0622 - mae: 0.1374 - rmse: 0.2160 - smape: 0.3527 - val_ia: 0.6935 - val_loss: 0.0553 - val_mae: 0.1286 - val_rmse: 0.1833 - val_smape: 0.3476

Epoch 58/256

1916/1916 - 33s - 17ms/step - ia: 0.8992 - loss: 0.0621 - mae: 0.1378 - rmse: 0.2157 - smape: 0.3528 - val_ia: 0.6987 - val_loss: 0.0551 - val_mae: 0.1276 - val_rmse: 0.1819 - val_smape: 0.3455

Epoch 59/256

1916/1916 - 31s - 16ms/step - ia: 0.8985 - loss: 0.0623 - mae: 0.1382 - rmse: 0.2167 - smape: 0.3543 - val_ia: 0.6863 - val_loss: 0.0579 - val_mae: 0.1372 - val_rmse: 0.1891 - val_smape: 0.3650

Epoch 60/256

1916/1916 - 35s - 18ms/step - ia: 0.8996 - loss: 0.0621 - mae: 0.1380 - rmse: 0.2158 - smape: 0.3533 - val_ia: 0.6934 - val_loss: 0.0553 - val_mae: 0.1288 - val_rmse: 0.1830 - val_smape: 0.3469

Epoch 61/256

1916/1916 - 34s - 18ms/step - ia: 0.8989 - loss: 0.0621 - mae: 0.1379 - rmse: 0.2164 - smape: 0.3527 - val_ia: 0.7001 - val_loss: 0.0558 - val_mae: 0.1299 - val_rmse: 0.1832 - val_smape: 0.3504

Epoch 62/256

1916/1916 - 37s - 19ms/step - ia: 0.8985 - loss: 0.0621 - mae: 0.1382 - rmse: 0.2166 - smape: 0.3546 - val_ia: 0.6641 - val_loss: 0.0568 - val_mae: 0.1372 - val_rmse: 0.1906 - val_smape: 0.3637

Epoch 63/256

1916/1916 - 43s - 22ms/step - ia: 0.8976 - loss: 0.0622 - mae: 0.1387 - rmse: 0.2174 - smape: 0.3564 - val_ia: 0.6702 - val_loss: 0.0570 - val_mae: 0.1357 - val_rmse: 0.1903 - val_smape: 0.3627

Epoch 64/256

1916/1916 - 33s - 17ms/step - ia: 0.8991 - loss: 0.0622 - mae: 0.1380 - rmse: 0.2169 - smape: 0.3545 - val_ia: 0.6964 - val_loss: 0.0550 - val_mae: 0.1282 - val_rmse: 0.1821 - val_smape: 0.3464

Epoch 65/256

1916/1916 - 32s - 17ms/step - ia: 0.8985 - loss: 0.0620 - mae: 0.1383 - rmse: 0.2163 - smape: 0.3557 - val_ia: 0.6948 - val_loss: 0.0551 - val_mae: 0.1286 - val_rmse: 0.1825 - val_smape: 0.3464

Epoch 66/256

1916/1916 - 34s - 18ms/step - ia: 0.8987 - loss: 0.0620 - mae: 0.1378 - rmse: 0.2166 - smape: 0.3534 - val_ia: 0.6913 - val_loss: 0.0569 - val_mae: 0.1345 - val_rmse: 0.1868 - val_smape: 0.3604

Epoch 67/256

1916/1916 - 31s - 16ms/step - ia: 0.8980 - loss: 0.0621 - mae: 0.1383 - rmse: 0.2163 - smape: 0.3546 - val_ia: 0.6986 - val_loss: 0.0551 - val_mae: 0.1282 - val_rmse: 0.1821 - val_smape: 0.3458

Epoch 68/256

1916/1916 - 35s - 18ms/step - ia: 0.8991 - loss: 0.0619 - mae: 0.1377 - rmse: 0.2155 - smape: 0.3545 - val_ia: 0.6981 - val_loss: 0.0551 - val_mae: 0.1284 - val_rmse: 0.1821 - val_smape: 0.3462

Epoch 69/256

1916/1916 - 32s - 17ms/step - ia: 0.8986 - loss: 0.0619 - mae: 0.1377 - rmse: 0.2163 - smape: 0.3531 - val_ia: 0.6808 - val_loss: 0.0560 - val_mae: 0.1321 - val_rmse: 0.1866 - val_smape: 0.3543

Epoch 70/256

1916/1916 - 34s - 18ms/step - ia: 0.8984 - loss: 0.0620 - mae: 0.1378 - rmse: 0.2156 - smape: 0.3537 - val_ia: 0.7027 - val_loss: 0.0550 - val_mae: 0.1272 - val_rmse: 0.1816 - val_smape: 0.3444

Epoch 71/256

1916/1916 - 33s - 17ms/step - ia: 0.8994 - loss: 0.0618 - mae: 0.1374 - rmse: 0.2159 - smape: 0.3528 - val_ia: 0.6981 - val_loss: 0.0558 - val_mae: 0.1305 - val_rmse: 0.1833 - val_smape: 0.3508

Epoch 72/256

1916/1916 - 32s - 17ms/step - ia: 0.8988 - loss: 0.0619 - mae: 0.1379 - rmse: 0.2158 - smape: 0.3552 - val_ia: 0.6963 - val_loss: 0.0563 - val_mae: 0.1319 - val_rmse: 0.1844 - val_smape: 0.3535

Epoch 73/256

1916/1916 - 32s - 17ms/step - ia: 0.8992 - loss: 0.0618 - mae: 0.1379 - rmse: 0.2154 - smape: 0.3533 - val_ia: 0.6991 - val_loss: 0.0555 - val_mae: 0.1295 - val_rmse: 0.1827 - val_smape: 0.3487

Epoch 74/256

1916/1916 - 33s - 17ms/step - ia: 0.8983 - loss: 0.0620 - mae: 0.1381 - rmse: 0.2159 - smape: 0.3547 - val_ia: 0.6526 - val_loss: 0.0585 - val_mae: 0.1422 - val_rmse: 0.1962 - val_smape: 0.3789

Epoch 75/256

1916/1916 - 42s - 22ms/step - ia: 0.8998 - loss: 0.0618 - mae: 0.1372 - rmse: 0.2154 - smape: 0.3516 - val_ia: 0.6977 - val_loss: 0.0557 - val_mae: 0.1306 - val_rmse: 0.1833 - val_smape: 0.3511

Epoch 76/256

1916/1916 - 35s - 18ms/step - ia: 0.8987 - loss: 0.0618 - mae: 0.1382 - rmse: 0.2164 - smape: 0.3543 - val_ia: 0.7021 - val_loss: 0.0550 - val_mae: 0.1280 - val_rmse: 0.1818 - val_smape: 0.3465

Epoch 77/256

1916/1916 - 34s - 18ms/step - ia: 0.8988 - loss: 0.0618 - mae: 0.1381 - rmse: 0.2161 - smape: 0.3542 - val_ia: 0.6979 - val_loss: 0.0551 - val_mae: 0.1277 - val_rmse: 0.1827 - val_smape: 0.3451

Epoch 78/256

1916/1916 - 34s - 18ms/step - ia: 0.8990 - loss: 0.0618 - mae: 0.1377 - rmse: 0.2158 - smape: 0.3541 - val_ia: 0.6925 - val_loss: 0.0551 - val_mae: 0.1289 - val_rmse: 0.1834 - val_smape: 0.3476

Epoch 79/256

1916/1916 - 35s - 19ms/step - ia: 0.8995 - loss: 0.0617 - mae: 0.1377 - rmse: 0.2150 - smape: 0.3546 - val_ia: 0.6893 - val_loss: 0.0551 - val_mae: 0.1296 - val_rmse: 0.1837 - val_smape: 0.3481

Epoch 80/256

1916/1916 - 32s - 17ms/step - ia: 0.8993 - loss: 0.0615 - mae: 0.1371 - rmse: 0.2157 - smape: 0.3524 - val_ia: 0.6956 - val_loss: 0.0550 - val_mae: 0.1289 - val_rmse: 0.1824 - val_smape: 0.3464

Epoch 81/256

1916/1916 - 32s - 17ms/step - ia: 0.8987 - loss: 0.0616 - mae: 0.1376 - rmse: 0.2159 - smape: 0.3534 - val_ia: 0.6726 - val_loss: 0.0565 - val_mae: 0.1348 - val_rmse: 0.1893 - val_smape: 0.3616

Epoch 82/256

1916/1916 - 33s - 17ms/step - ia: 0.8990 - loss: 0.0616 - mae: 0.1378 - rmse: 0.2158 - smape: 0.3540 - val_ia: 0.6797 - val_loss: 0.0554 - val_mae: 0.1322 - val_rmse: 0.1857 - val_smape: 0.3532

Epoch 83/256

1916/1916 - 37s - 19ms/step - ia: 0.8991 - loss: 0.0616 - mae: 0.1375 - rmse: 0.2157 - smape: 0.3538 - val_ia: 0.6978 - val_loss: 0.0555 - val_mae: 0.1300 - val_rmse: 0.1828 - val_smape: 0.3494

Epoch 84/256

1916/1916 - 35s - 18ms/step - ia: 0.8988 - loss: 0.0616 - mae: 0.1382 - rmse: 0.2155 - smape: 0.3552 - val_ia: 0.6727 - val_loss: 0.0560 - val_mae: 0.1344 - val_rmse: 0.1879 - val_smape: 0.3581

Epoch 85/256

1916/1916 - 38s - 20ms/step - ia: 0.8991 - loss: 0.0617 - mae: 0.1377 - rmse: 0.2159 - smape: 0.3541 - val_ia: 0.6370 - val_loss: 0.0593 - val_mae: 0.1480 - val_rmse: 0.2005 - val_smape: 0.3904

Epoch 85: early stopping

Restoring model weights from the end of the best epoch: 70.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:38 2s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

 42%|████▏     | 21/50 [3:47:34<11:13:25, 1393.28s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1916/1916 - 61s - 32ms/step - ia: 0.1795 - loss: 0.9988 - mae: 0.7480 - rmse: 0.9605 - smape: 1.8440 - val_ia: 0.2221 - val_loss: 0.9495 - val_mae: 0.7197 - val_rmse: 0.7817 - val_smape: 1.7657

Epoch 2/256

1916/1916 - 46s - 24ms/step - ia: 0.5149 - loss: 0.5664 - mae: 0.5162 - rmse: 0.6989 - smape: 1.1025 - val_ia: 0.3176 - val_loss: 0.3040 - val_mae: 0.3765 - val_rmse: 0.4444 - val_smape: 0.7772

Epoch 3/256

1916/1916 - 85s - 44ms/step - ia: 0.7183 - loss: 0.3015 - mae: 0.3624 - rmse: 0.5142 - smape: 0.7395 - val_ia: 0.3580 - val_loss: 0.2385 - val_mae: 0.3340 - val_rmse: 0.3996 - val_smape: 0.7273

Epoch 4/256

1916/1916 - 47s - 25ms/step - ia: 0.7511 - loss: 0.2446 - mae: 0.3235 - rmse: 0.4624 - smape: 0.6872 - val_ia: 0.4040 - val_loss: 0.1923 - val_mae: 0.2934 - val_rmse: 0.3581 - val_smape: 0.6600

Epoch 5/256

1916/1916 - 46s - 24ms/step - ia: 0.7786 - loss: 0.2005 - mae: 0.2894 - rmse: 0.4160 - smape: 0.6330 - val_ia: 0.4454 - val_loss: 0.1585 - val_mae: 0.2633 - val_rmse: 0.3269 - val_smape: 0.6102

Epoch 6/256

1916/1916 - 47s - 24ms/step - ia: 0.8032 - loss: 0.1666 - mae: 0.2600 - rmse: 0.3757 - smape: 0.5850 - val_ia: 0.4829 - val_loss: 0.1334 - val_mae: 0.2382 - val_rmse: 0.2999 - val_smape: 0.5646

Epoch 7/256

1916/1916 - 47s - 24ms/step - ia: 0.8238 - loss: 0.1403 - mae: 0.2331 - rmse: 0.3418 - smape: 0.5360 - val_ia: 0.5004 - val_loss: 0.1186 - val_mae: 0.2294 - val_rmse: 0.2891 - val_smape: 0.5569

Epoch 8/256

1916/1916 - 45s - 24ms/step - ia: 0.8418 - loss: 0.1203 - mae: 0.2111 - rmse: 0.3133 - smape: 0.4953 - val_ia: 0.5694 - val_loss: 0.0997 - val_mae: 0.1940 - val_rmse: 0.2539 - val_smape: 0.4769

Epoch 9/256

1916/1916 - 45s - 24ms/step - ia: 0.8547 - loss: 0.1056 - mae: 0.1941 - rmse: 0.2918 - smape: 0.4629 - val_ia: 0.5987 - val_loss: 0.0872 - val_mae: 0.1781 - val_rmse: 0.2361 - val_smape: 0.4466

Epoch 10/256

1916/1916 - 44s - 23ms/step - ia: 0.8651 - loss: 0.0949 - mae: 0.1814 - rmse: 0.2742 - smape: 0.4391 - val_ia: 0.6200 - val_loss: 0.0785 - val_mae: 0.1664 - val_rmse: 0.2231 - val_smape: 0.4246

Epoch 11/256

1916/1916 - 82s - 43ms/step - ia: 0.8744 - loss: 0.0864 - mae: 0.1696 - rmse: 0.2603 - smape: 0.4145 - val_ia: 0.6355 - val_loss: 0.0730 - val_mae: 0.1592 - val_rmse: 0.2143 - val_smape: 0.4114

Epoch 12/256

1916/1916 - 44s - 23ms/step - ia: 0.8803 - loss: 0.0804 - mae: 0.1621 - rmse: 0.2488 - smape: 0.4020 - val_ia: 0.6500 - val_loss: 0.0671 - val_mae: 0.1497 - val_rmse: 0.2052 - val_smape: 0.3907

Epoch 13/256

1916/1916 - 50s - 26ms/step - ia: 0.8851 - loss: 0.0756 - mae: 0.1560 - rmse: 0.2410 - smape: 0.3890 - val_ia: 0.6599 - val_loss: 0.0639 - val_mae: 0.1447 - val_rmse: 0.1997 - val_smape: 0.3791

Epoch 14/256

1916/1916 - 75s - 39ms/step - ia: 0.8889 - loss: 0.0722 - mae: 0.1508 - rmse: 0.2350 - smape: 0.3780 - val_ia: 0.6749 - val_loss: 0.0618 - val_mae: 0.1392 - val_rmse: 0.1955 - val_smape: 0.3675

Epoch 15/256

1916/1916 - 46s - 24ms/step - ia: 0.8915 - loss: 0.0699 - mae: 0.1476 - rmse: 0.2297 - smape: 0.3722 - val_ia: 0.6805 - val_loss: 0.0596 - val_mae: 0.1362 - val_rmse: 0.1911 - val_smape: 0.3613

Epoch 16/256

1916/1916 - 45s - 23ms/step - ia: 0.8934 - loss: 0.0681 - mae: 0.1454 - rmse: 0.2269 - smape: 0.3682 - val_ia: 0.6748 - val_loss: 0.0600 - val_mae: 0.1372 - val_rmse: 0.1935 - val_smape: 0.3611

Epoch 17/256

1916/1916 - 46s - 24ms/step - ia: 0.8951 - loss: 0.0669 - mae: 0.1431 - rmse: 0.2237 - smape: 0.3632 - val_ia: 0.6767 - val_loss: 0.0582 - val_mae: 0.1353 - val_rmse: 0.1903 - val_smape: 0.3581

Epoch 18/256

1916/1916 - 44s - 23ms/step - ia: 0.8948 - loss: 0.0662 - mae: 0.1428 - rmse: 0.2232 - smape: 0.3628 - val_ia: 0.6845 - val_loss: 0.0573 - val_mae: 0.1326 - val_rmse: 0.1874 - val_smape: 0.3536

Epoch 19/256

1916/1916 - 45s - 24ms/step - ia: 0.8962 - loss: 0.0656 - mae: 0.1419 - rmse: 0.2212 - smape: 0.3607 - val_ia: 0.6736 - val_loss: 0.0579 - val_mae: 0.1356 - val_rmse: 0.1905 - val_smape: 0.3584

Epoch 20/256

1916/1916 - 46s - 24ms/step - ia: 0.8965 - loss: 0.0651 - mae: 0.1410 - rmse: 0.2212 - smape: 0.3590 - val_ia: 0.6940 - val_loss: 0.0565 - val_mae: 0.1307 - val_rmse: 0.1847 - val_smape: 0.3517

Epoch 21/256

1916/1916 - 42s - 22ms/step - ia: 0.8960 - loss: 0.0649 - mae: 0.1414 - rmse: 0.2207 - smape: 0.3603 - val_ia: 0.6913 - val_loss: 0.0567 - val_mae: 0.1319 - val_rmse: 0.1851 - val_smape: 0.3545

Epoch 22/256

1916/1916 - 48s - 25ms/step - ia: 0.8973 - loss: 0.0647 - mae: 0.1408 - rmse: 0.2202 - smape: 0.3597 - val_ia: 0.6860 - val_loss: 0.0581 - val_mae: 0.1365 - val_rmse: 0.1892 - val_smape: 0.3655

Epoch 23/256

1916/1916 - 46s - 24ms/step - ia: 0.8971 - loss: 0.0643 - mae: 0.1401 - rmse: 0.2199 - smape: 0.3579 - val_ia: 0.6820 - val_loss: 0.0563 - val_mae: 0.1329 - val_rmse: 0.1857 - val_smape: 0.3532

Epoch 24/256

1916/1916 - 82s - 43ms/step - ia: 0.8966 - loss: 0.0642 - mae: 0.1405 - rmse: 0.2193 - smape: 0.3587 - val_ia: 0.6862 - val_loss: 0.0560 - val_mae: 0.1312 - val_rmse: 0.1849 - val_smape: 0.3507

Epoch 25/256

1916/1916 - 43s - 22ms/step - ia: 0.8971 - loss: 0.0640 - mae: 0.1403 - rmse: 0.2188 - smape: 0.3584 - val_ia: 0.6719 - val_loss: 0.0594 - val_mae: 0.1422 - val_rmse: 0.1945 - val_smape: 0.3770

Epoch 26/256

1916/1916 - 85s - 44ms/step - ia: 0.8973 - loss: 0.0639 - mae: 0.1401 - rmse: 0.2187 - smape: 0.3594 - val_ia: 0.6829 - val_loss: 0.0562 - val_mae: 0.1318 - val_rmse: 0.1860 - val_smape: 0.3518

Epoch 27/256

1916/1916 - 81s - 42ms/step - ia: 0.8975 - loss: 0.0639 - mae: 0.1402 - rmse: 0.2182 - smape: 0.3577 - val_ia: 0.6701 - val_loss: 0.0570 - val_mae: 0.1358 - val_rmse: 0.1896 - val_smape: 0.3594

Epoch 28/256

1916/1916 - 44s - 23ms/step - ia: 0.8972 - loss: 0.0637 - mae: 0.1400 - rmse: 0.2181 - smape: 0.3580 - val_ia: 0.6979 - val_loss: 0.0556 - val_mae: 0.1286 - val_rmse: 0.1831 - val_smape: 0.3473

Epoch 29/256

1916/1916 - 45s - 24ms/step - ia: 0.8972 - loss: 0.0637 - mae: 0.1403 - rmse: 0.2195 - smape: 0.3586 - val_ia: 0.6875 - val_loss: 0.0574 - val_mae: 0.1355 - val_rmse: 0.1880 - val_smape: 0.3638

Epoch 30/256

1916/1916 - 46s - 24ms/step - ia: 0.8974 - loss: 0.0637 - mae: 0.1399 - rmse: 0.2181 - smape: 0.3581 - val_ia: 0.6572 - val_loss: 0.0580 - val_mae: 0.1403 - val_rmse: 0.1937 - val_smape: 0.3705

Epoch 31/256

1916/1916 - 44s - 23ms/step - ia: 0.8972 - loss: 0.0638 - mae: 0.1401 - rmse: 0.2189 - smape: 0.3577 - val_ia: 0.6441 - val_loss: 0.0595 - val_mae: 0.1456 - val_rmse: 0.1988 - val_smape: 0.3829

Epoch 32/256

1916/1916 - 45s - 23ms/step - ia: 0.8962 - loss: 0.0639 - mae: 0.1409 - rmse: 0.2194 - smape: 0.3603 - val_ia: 0.6902 - val_loss: 0.0567 - val_mae: 0.1330 - val_rmse: 0.1853 - val_smape: 0.3568

Epoch 33/256

1916/1916 - 81s - 42ms/step - ia: 0.8977 - loss: 0.0633 - mae: 0.1396 - rmse: 0.2179 - smape: 0.3568 - val_ia: 0.6927 - val_loss: 0.0559 - val_mae: 0.1309 - val_rmse: 0.1837 - val_smape: 0.3523

Epoch 34/256

1916/1916 - 46s - 24ms/step - ia: 0.8971 - loss: 0.0635 - mae: 0.1401 - rmse: 0.2185 - smape: 0.3591 - val_ia: 0.6973 - val_loss: 0.0556 - val_mae: 0.1296 - val_rmse: 0.1832 - val_smape: 0.3496

Epoch 35/256

1916/1916 - 81s - 42ms/step - ia: 0.8969 - loss: 0.0635 - mae: 0.1405 - rmse: 0.2186 - smape: 0.3605 - val_ia: 0.6843 - val_loss: 0.0557 - val_mae: 0.1312 - val_rmse: 0.1851 - val_smape: 0.3508

Epoch 36/256

1916/1916 - 83s - 43ms/step - ia: 0.8975 - loss: 0.0633 - mae: 0.1395 - rmse: 0.2178 - smape: 0.3561 - val_ia: 0.6802 - val_loss: 0.0559 - val_mae: 0.1324 - val_rmse: 0.1861 - val_smape: 0.3536

Epoch 37/256

1916/1916 - 81s - 42ms/step - ia: 0.8975 - loss: 0.0634 - mae: 0.1398 - rmse: 0.2184 - smape: 0.3598 - val_ia: 0.6874 - val_loss: 0.0571 - val_mae: 0.1353 - val_rmse: 0.1877 - val_smape: 0.3630

Epoch 38/256

1916/1916 - 84s - 44ms/step - ia: 0.8970 - loss: 0.0633 - mae: 0.1398 - rmse: 0.2183 - smape: 0.3579 - val_ia: 0.6860 - val_loss: 0.0554 - val_mae: 0.1307 - val_rmse: 0.1842 - val_smape: 0.3507

Epoch 39/256

1916/1916 - 42s - 22ms/step - ia: 0.8971 - loss: 0.0632 - mae: 0.1401 - rmse: 0.2181 - smape: 0.3592 - val_ia: 0.6937 - val_loss: 0.0553 - val_mae: 0.1291 - val_rmse: 0.1831 - val_smape: 0.3479

Epoch 40/256

1916/1916 - 48s - 25ms/step - ia: 0.8972 - loss: 0.0632 - mae: 0.1395 - rmse: 0.2181 - smape: 0.3575 - val_ia: 0.6893 - val_loss: 0.0554 - val_mae: 0.1305 - val_rmse: 0.1835 - val_smape: 0.3499

Epoch 41/256

1916/1916 - 45s - 23ms/step - ia: 0.8975 - loss: 0.0631 - mae: 0.1397 - rmse: 0.2176 - smape: 0.3573 - val_ia: 0.6899 - val_loss: 0.0565 - val_mae: 0.1338 - val_rmse: 0.1862 - val_smape: 0.3598

Epoch 42/256

1916/1916 - 46s - 24ms/step - ia: 0.8975 - loss: 0.0630 - mae: 0.1391 - rmse: 0.2176 - smape: 0.3568 - val_ia: 0.6615 - val_loss: 0.0579 - val_mae: 0.1392 - val_rmse: 0.1931 - val_smape: 0.3698

Epoch 43/256

1916/1916 - 45s - 23ms/step - ia: 0.8978 - loss: 0.0631 - mae: 0.1395 - rmse: 0.2178 - smape: 0.3577 - val_ia: 0.6725 - val_loss: 0.0587 - val_mae: 0.1417 - val_rmse: 0.1933 - val_smape: 0.3761

Epoch 44/256

1916/1916 - 45s - 23ms/step - ia: 0.8984 - loss: 0.0630 - mae: 0.1395 - rmse: 0.2172 - smape: 0.3584 - val_ia: 0.6755 - val_loss: 0.0560 - val_mae: 0.1338 - val_rmse: 0.1872 - val_smape: 0.3564

Epoch 45/256

1916/1916 - 46s - 24ms/step - ia: 0.8976 - loss: 0.0629 - mae: 0.1394 - rmse: 0.2178 - smape: 0.3557 - val_ia: 0.6960 - val_loss: 0.0551 - val_mae: 0.1288 - val_rmse: 0.1822 - val_smape: 0.3477

Epoch 46/256

1916/1916 - 47s - 24ms/step - ia: 0.8980 - loss: 0.0629 - mae: 0.1394 - rmse: 0.2169 - smape: 0.3568 - val_ia: 0.6927 - val_loss: 0.0560 - val_mae: 0.1319 - val_rmse: 0.1842 - val_smape: 0.3546

Epoch 47/256

1916/1916 - 46s - 24ms/step - ia: 0.8974 - loss: 0.0628 - mae: 0.1394 - rmse: 0.2170 - smape: 0.3561 - val_ia: 0.6803 - val_loss: 0.0556 - val_mae: 0.1326 - val_rmse: 0.1853 - val_smape: 0.3532

Epoch 48/256

1916/1916 - 46s - 24ms/step - ia: 0.8979 - loss: 0.0628 - mae: 0.1397 - rmse: 0.2180 - smape: 0.3595 - val_ia: 0.6948 - val_loss: 0.0551 - val_mae: 0.1286 - val_rmse: 0.1826 - val_smape: 0.3468

Epoch 49/256

1916/1916 - 46s - 24ms/step - ia: 0.8979 - loss: 0.0628 - mae: 0.1395 - rmse: 0.2178 - smape: 0.3572 - val_ia: 0.6820 - val_loss: 0.0577 - val_mae: 0.1380 - val_rmse: 0.1897 - val_smape: 0.3676

Epoch 50/256

1916/1916 - 82s - 43ms/step - ia: 0.8980 - loss: 0.0628 - mae: 0.1392 - rmse: 0.2174 - smape: 0.3571 - val_ia: 0.6890 - val_loss: 0.0556 - val_mae: 0.1314 - val_rmse: 0.1836 - val_smape: 0.3518

Epoch 51/256

1916/1916 - 49s - 26ms/step - ia: 0.8974 - loss: 0.0626 - mae: 0.1390 - rmse: 0.2173 - smape: 0.3563 - val_ia: 0.6896 - val_loss: 0.0557 - val_mae: 0.1302 - val_rmse: 0.1846 - val_smape: 0.3506

Epoch 52/256

1916/1916 - 47s - 24ms/step - ia: 0.8972 - loss: 0.0629 - mae: 0.1397 - rmse: 0.2180 - smape: 0.3583 - val_ia: 0.6889 - val_loss: 0.0568 - val_mae: 0.1347 - val_rmse: 0.1868 - val_smape: 0.3599

Epoch 53/256

1916/1916 - 49s - 26ms/step - ia: 0.8986 - loss: 0.0626 - mae: 0.1391 - rmse: 0.2168 - smape: 0.3551 - val_ia: 0.6896 - val_loss: 0.0552 - val_mae: 0.1305 - val_rmse: 0.1834 - val_smape: 0.3496

Epoch 54/256

1916/1916 - 49s - 25ms/step - ia: 0.8978 - loss: 0.0626 - mae: 0.1392 - rmse: 0.2182 - smape: 0.3573 - val_ia: 0.6519 - val_loss: 0.0586 - val_mae: 0.1427 - val_rmse: 0.1962 - val_smape: 0.3789

Epoch 55/256

1916/1916 - 47s - 25ms/step - ia: 0.8976 - loss: 0.0626 - mae: 0.1394 - rmse: 0.2176 - smape: 0.3578 - val_ia: 0.6915 - val_loss: 0.0562 - val_mae: 0.1332 - val_rmse: 0.1856 - val_smape: 0.3569

Epoch 56/256

1916/1916 - 48s - 25ms/step - ia: 0.8981 - loss: 0.0627 - mae: 0.1390 - rmse: 0.2171 - smape: 0.3551 - val_ia: 0.6967 - val_loss: 0.0548 - val_mae: 0.1286 - val_rmse: 0.1820 - val_smape: 0.3471

Epoch 57/256

1916/1916 - 47s - 25ms/step - ia: 0.8972 - loss: 0.0627 - mae: 0.1401 - rmse: 0.2178 - smape: 0.3590 - val_ia: 0.6966 - val_loss: 0.0549 - val_mae: 0.1288 - val_rmse: 0.1821 - val_smape: 0.3474

Epoch 58/256

1916/1916 - 49s - 25ms/step - ia: 0.8975 - loss: 0.0626 - mae: 0.1397 - rmse: 0.2177 - smape: 0.3587 - val_ia: 0.6915 - val_loss: 0.0548 - val_mae: 0.1292 - val_rmse: 0.1826 - val_smape: 0.3480

Epoch 59/256

1916/1916 - 47s - 24ms/step - ia: 0.8982 - loss: 0.0625 - mae: 0.1392 - rmse: 0.2165 - smape: 0.3569 - val_ia: 0.6843 - val_loss: 0.0559 - val_mae: 0.1317 - val_rmse: 0.1861 - val_smape: 0.3543

Epoch 60/256

1916/1916 - 83s - 43ms/step - ia: 0.8975 - loss: 0.0625 - mae: 0.1392 - rmse: 0.2177 - smape: 0.3577 - val_ia: 0.6980 - val_loss: 0.0548 - val_mae: 0.1286 - val_rmse: 0.1819 - val_smape: 0.3477

Epoch 61/256

1916/1916 - 47s - 25ms/step - ia: 0.8977 - loss: 0.0625 - mae: 0.1391 - rmse: 0.2169 - smape: 0.3566 - val_ia: 0.6834 - val_loss: 0.0551 - val_mae: 0.1317 - val_rmse: 0.1842 - val_smape: 0.3514

Epoch 62/256

1916/1916 - 46s - 24ms/step - ia: 0.8978 - loss: 0.0623 - mae: 0.1392 - rmse: 0.2173 - smape: 0.3578 - val_ia: 0.6963 - val_loss: 0.0547 - val_mae: 0.1283 - val_rmse: 0.1818 - val_smape: 0.3468

Epoch 63/256

1916/1916 - 48s - 25ms/step - ia: 0.8977 - loss: 0.0623 - mae: 0.1392 - rmse: 0.2167 - smape: 0.3570 - val_ia: 0.6740 - val_loss: 0.0560 - val_mae: 0.1342 - val_rmse: 0.1878 - val_smape: 0.3585

Epoch 64/256

1916/1916 - 46s - 24ms/step - ia: 0.8976 - loss: 0.0626 - mae: 0.1399 - rmse: 0.2169 - smape: 0.3581 - val_ia: 0.6968 - val_loss: 0.0548 - val_mae: 0.1286 - val_rmse: 0.1819 - val_smape: 0.3472

Epoch 65/256

1916/1916 - 44s - 23ms/step - ia: 0.8981 - loss: 0.0626 - mae: 0.1392 - rmse: 0.2171 - smape: 0.3567 - val_ia: 0.6922 - val_loss: 0.0560 - val_mae: 0.1328 - val_rmse: 0.1850 - val_smape: 0.3566

Epoch 66/256

1916/1916 - 43s - 22ms/step - ia: 0.8978 - loss: 0.0623 - mae: 0.1388 - rmse: 0.2168 - smape: 0.3558 - val_ia: 0.6922 - val_loss: 0.0548 - val_mae: 0.1291 - val_rmse: 0.1826 - val_smape: 0.3481

Epoch 67/256

1916/1916 - 46s - 24ms/step - ia: 0.8986 - loss: 0.0622 - mae: 0.1388 - rmse: 0.2168 - smape: 0.3552 - val_ia: 0.6789 - val_loss: 0.0554 - val_mae: 0.1327 - val_rmse: 0.1857 - val_smape: 0.3545

Epoch 68/256

1916/1916 - 77s - 40ms/step - ia: 0.8981 - loss: 0.0623 - mae: 0.1393 - rmse: 0.2170 - smape: 0.3568 - val_ia: 0.6941 - val_loss: 0.0548 - val_mae: 0.1288 - val_rmse: 0.1827 - val_smape: 0.3471

Epoch 69/256

1916/1916 - 47s - 24ms/step - ia: 0.8975 - loss: 0.0624 - mae: 0.1397 - rmse: 0.2176 - smape: 0.3582 - val_ia: 0.6911 - val_loss: 0.0559 - val_mae: 0.1331 - val_rmse: 0.1852 - val_smape: 0.3574

Epoch 70/256

1916/1916 - 47s - 25ms/step - ia: 0.8981 - loss: 0.0622 - mae: 0.1391 - rmse: 0.2165 - smape: 0.3575 - val_ia: 0.6955 - val_loss: 0.0550 - val_mae: 0.1296 - val_rmse: 0.1823 - val_smape: 0.3489

Epoch 71/256

1916/1916 - 47s - 25ms/step - ia: 0.8980 - loss: 0.0622 - mae: 0.1388 - rmse: 0.2168 - smape: 0.3560 - val_ia: 0.6879 - val_loss: 0.0549 - val_mae: 0.1302 - val_rmse: 0.1836 - val_smape: 0.3494

Epoch 72/256

1916/1916 - 48s - 25ms/step - ia: 0.8976 - loss: 0.0622 - mae: 0.1389 - rmse: 0.2164 - smape: 0.3557 - val_ia: 0.6944 - val_loss: 0.0546 - val_mae: 0.1288 - val_rmse: 0.1819 - val_smape: 0.3472

Epoch 73/256

1916/1916 - 48s - 25ms/step - ia: 0.8979 - loss: 0.0621 - mae: 0.1391 - rmse: 0.2163 - smape: 0.3563 - val_ia: 0.6899 - val_loss: 0.0550 - val_mae: 0.1297 - val_rmse: 0.1835 - val_smape: 0.3501

Epoch 74/256

1916/1916 - 81s - 42ms/step - ia: 0.8979 - loss: 0.0621 - mae: 0.1389 - rmse: 0.2160 - smape: 0.3567 - val_ia: 0.6986 - val_loss: 0.0548 - val_mae: 0.1290 - val_rmse: 0.1820 - val_smape: 0.3482

Epoch 75/256

1916/1916 - 47s - 25ms/step - ia: 0.8984 - loss: 0.0620 - mae: 0.1387 - rmse: 0.2162 - smape: 0.3561 - val_ia: 0.6418 - val_loss: 0.0591 - val_mae: 0.1464 - val_rmse: 0.1992 - val_smape: 0.3881

Epoch 76/256

1916/1916 - 48s - 25ms/step - ia: 0.8985 - loss: 0.0621 - mae: 0.1388 - rmse: 0.2172 - smape: 0.3554 - val_ia: 0.6970 - val_loss: 0.0546 - val_mae: 0.1286 - val_rmse: 0.1817 - val_smape: 0.3474

Epoch 77/256

1916/1916 - 50s - 26ms/step - ia: 0.8985 - loss: 0.0621 - mae: 0.1387 - rmse: 0.2159 - smape: 0.3562 - val_ia: 0.6765 - val_loss: 0.0556 - val_mae: 0.1335 - val_rmse: 0.1867 - val_smape: 0.3574

Epoch 78/256

1916/1916 - 48s - 25ms/step - ia: 0.8978 - loss: 0.0621 - mae: 0.1388 - rmse: 0.2172 - smape: 0.3556 - val_ia: 0.6902 - val_loss: 0.0546 - val_mae: 0.1296 - val_rmse: 0.1826 - val_smape: 0.3482

Epoch 79/256

1916/1916 - 49s - 26ms/step - ia: 0.8977 - loss: 0.0621 - mae: 0.1393 - rmse: 0.2174 - smape: 0.3572 - val_ia: 0.6987 - val_loss: 0.0549 - val_mae: 0.1292 - val_rmse: 0.1824 - val_smape: 0.3489

Epoch 80/256

1916/1916 - 47s - 25ms/step - ia: 0.8977 - loss: 0.0621 - mae: 0.1392 - rmse: 0.2166 - smape: 0.3577 - val_ia: 0.6977 - val_loss: 0.0551 - val_mae: 0.1299 - val_rmse: 0.1826 - val_smape: 0.3500

Epoch 81/256

1916/1916 - 48s - 25ms/step - ia: 0.8980 - loss: 0.0620 - mae: 0.1389 - rmse: 0.2163 - smape: 0.3568 - val_ia: 0.6816 - val_loss: 0.0572 - val_mae: 0.1377 - val_rmse: 0.1891 - val_smape: 0.3657

Epoch 82/256

1916/1916 - 42s - 22ms/step - ia: 0.8978 - loss: 0.0620 - mae: 0.1390 - rmse: 0.2164 - smape: 0.3569 - val_ia: 0.6981 - val_loss: 0.0545 - val_mae: 0.1281 - val_rmse: 0.1814 - val_smape: 0.3461

Epoch 83/256

1916/1916 - 88s - 46ms/step - ia: 0.8979 - loss: 0.0620 - mae: 0.1392 - rmse: 0.2167 - smape: 0.3563 - val_ia: 0.6972 - val_loss: 0.0549 - val_mae: 0.1296 - val_rmse: 0.1822 - val_smape: 0.3491

Epoch 84/256

1916/1916 - 41s - 21ms/step - ia: 0.8983 - loss: 0.0619 - mae: 0.1386 - rmse: 0.2164 - smape: 0.3556 - val_ia: 0.6668 - val_loss: 0.0565 - val_mae: 0.1369 - val_rmse: 0.1901 - val_smape: 0.3662

Epoch 85/256

1916/1916 - 47s - 24ms/step - ia: 0.8979 - loss: 0.0620 - mae: 0.1391 - rmse: 0.2167 - smape: 0.3575 - val_ia: 0.6536 - val_loss: 0.0574 - val_mae: 0.1412 - val_rmse: 0.1939 - val_smape: 0.3750

Epoch 86/256

1916/1916 - 46s - 24ms/step - ia: 0.8982 - loss: 0.0620 - mae: 0.1392 - rmse: 0.2170 - smape: 0.3573 - val_ia: 0.6862 - val_loss: 0.0547 - val_mae: 0.1306 - val_rmse: 0.1833 - val_smape: 0.3503

Epoch 87/256

1916/1916 - 47s - 24ms/step - ia: 0.8986 - loss: 0.0619 - mae: 0.1389 - rmse: 0.2160 - smape: 0.3569 - val_ia: 0.6825 - val_loss: 0.0553 - val_mae: 0.1317 - val_rmse: 0.1853 - val_smape: 0.3545

Epoch 88/256

1916/1916 - 84s - 44ms/step - ia: 0.8978 - loss: 0.0622 - mae: 0.1395 - rmse: 0.2166 - smape: 0.3585 - val_ia: 0.6940 - val_loss: 0.0555 - val_mae: 0.1319 - val_rmse: 0.1840 - val_smape: 0.3538

Epoch 89/256

1916/1916 - 43s - 23ms/step - ia: 0.8973 - loss: 0.0620 - mae: 0.1393 - rmse: 0.2159 - smape: 0.3589 - val_ia: 0.6838 - val_loss: 0.0548 - val_mae: 0.1313 - val_rmse: 0.1837 - val_smape: 0.3505

Epoch 90/256

1916/1916 - 45s - 23ms/step - ia: 0.8986 - loss: 0.0619 - mae: 0.1386 - rmse: 0.2165 - smape: 0.3563 - val_ia: 0.6965 - val_loss: 0.0545 - val_mae: 0.1287 - val_rmse: 0.1816 - val_smape: 0.3475

Epoch 91/256

1916/1916 - 46s - 24ms/step - ia: 0.8980 - loss: 0.0619 - mae: 0.1391 - rmse: 0.2163 - smape: 0.3570 - val_ia: 0.6939 - val_loss: 0.0545 - val_mae: 0.1286 - val_rmse: 0.1819 - val_smape: 0.3468

Epoch 92/256

1916/1916 - 41s - 22ms/step - ia: 0.8980 - loss: 0.0618 - mae: 0.1392 - rmse: 0.2165 - smape: 0.3573 - val_ia: 0.6971 - val_loss: 0.0549 - val_mae: 0.1299 - val_rmse: 0.1825 - val_smape: 0.3499

Epoch 93/256

1916/1916 - 43s - 22ms/step - ia: 0.8977 - loss: 0.0619 - mae: 0.1396 - rmse: 0.2162 - smape: 0.3584 - val_ia: 0.6895 - val_loss: 0.0554 - val_mae: 0.1303 - val_rmse: 0.1847 - val_smape: 0.3520

Epoch 94/256

1916/1916 - 47s - 25ms/step - ia: 0.8977 - loss: 0.0619 - mae: 0.1392 - rmse: 0.2165 - smape: 0.3577 - val_ia: 0.6968 - val_loss: 0.0551 - val_mae: 0.1304 - val_rmse: 0.1831 - val_smape: 0.3507

Epoch 95/256

1916/1916 - 47s - 25ms/step - ia: 0.8978 - loss: 0.0618 - mae: 0.1391 - rmse: 0.2172 - smape: 0.3579 - val_ia: 0.6636 - val_loss: 0.0564 - val_mae: 0.1375 - val_rmse: 0.1905 - val_smape: 0.3667

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1916/1916 - 90s - 47ms/step - ia: 0.1755 - loss: 0.9968 - mae: 0.7484 - rmse: 0.9582 - smape: 1.8729 - val_ia: 0.2202 - val_loss: 0.9379 - val_mae: 0.7253 - val_rmse: 0.7862 - val_smape: 1.8819

Epoch 2/64

1916/1916 - 55s - 29ms/step - ia: 0.5851 - loss: 0.4794 - mae: 0.4683 - rmse: 0.6418 - smape: 0.9596 - val_ia: 0.3320 - val_loss: 0.2834 - val_mae: 0.3596 - val_rmse: 0.4270 - val_smape: 0.7452

Epoch 3/64

1916/1916 - 50s - 26ms/step - ia: 0.7342 - loss: 0.2776 - mae: 0.3449 - rmse: 0.4925 - smape: 0.7100 - val_ia: 0.3944 - val_loss: 0.2169 - val_mae: 0.3049 - val_rmse: 0.3714 - val_smape: 0.6626

Epoch 4/64

1916/1916 - 83s - 43ms/step - ia: 0.7693 - loss: 0.2179 - mae: 0.3024 - rmse: 0.4329 - smape: 0.6492 - val_ia: 0.4369 - val_loss: 0.1691 - val_mae: 0.2694 - val_rmse: 0.3338 - val_smape: 0.6132

Epoch 5/64

1916/1916 - 77s - 40ms/step - ia: 0.7977 - loss: 0.1753 - mae: 0.2671 - rmse: 0.3867 - smape: 0.5918 - val_ia: 0.4761 - val_loss: 0.1383 - val_mae: 0.2430 - val_rmse: 0.3051 - val_smape: 0.5703

Epoch 6/64

1916/1916 - 43s - 23ms/step - ia: 0.8217 - loss: 0.1441 - mae: 0.2370 - rmse: 0.3469 - smape: 0.5416 - val_ia: 0.5281 - val_loss: 0.1149 - val_mae: 0.2130 - val_rmse: 0.2745 - val_smape: 0.5101

Epoch 7/64

1916/1916 - 42s - 22ms/step - ia: 0.8423 - loss: 0.1218 - mae: 0.2120 - rmse: 0.3157 - smape: 0.4954 - val_ia: 0.5607 - val_loss: 0.0987 - val_mae: 0.1940 - val_rmse: 0.2535 - val_smape: 0.4751

Epoch 8/64

1916/1916 - 41s - 21ms/step - ia: 0.8560 - loss: 0.1058 - mae: 0.1928 - rmse: 0.2920 - smape: 0.4580 - val_ia: 0.5996 - val_loss: 0.0882 - val_mae: 0.1782 - val_rmse: 0.2359 - val_smape: 0.4468

Epoch 9/64

1916/1916 - 41s - 21ms/step - ia: 0.8668 - loss: 0.0943 - mae: 0.1798 - rmse: 0.2726 - smape: 0.4337 - val_ia: 0.6039 - val_loss: 0.0792 - val_mae: 0.1703 - val_rmse: 0.2272 - val_smape: 0.4290

Epoch 10/64

1916/1916 - 42s - 22ms/step - ia: 0.8755 - loss: 0.0857 - mae: 0.1683 - rmse: 0.2578 - smape: 0.4117 - val_ia: 0.6271 - val_loss: 0.0714 - val_mae: 0.1579 - val_rmse: 0.2133 - val_smape: 0.4026

Epoch 11/64

1916/1916 - 42s - 22ms/step - ia: 0.8824 - loss: 0.0793 - mae: 0.1596 - rmse: 0.2466 - smape: 0.3941 - val_ia: 0.6522 - val_loss: 0.0668 - val_mae: 0.1485 - val_rmse: 0.2032 - val_smape: 0.3866

Epoch 12/64

1916/1916 - 41s - 22ms/step - ia: 0.8875 - loss: 0.0750 - mae: 0.1538 - rmse: 0.2388 - smape: 0.3829 - val_ia: 0.6584 - val_loss: 0.0639 - val_mae: 0.1441 - val_rmse: 0.1997 - val_smape: 0.3751

Epoch 13/64

1916/1916 - 40s - 21ms/step - ia: 0.8895 - loss: 0.0719 - mae: 0.1498 - rmse: 0.2330 - smape: 0.3750 - val_ia: 0.6752 - val_loss: 0.0612 - val_mae: 0.1384 - val_rmse: 0.1932 - val_smape: 0.3657

Epoch 14/64

1916/1916 - 41s - 21ms/step - ia: 0.8915 - loss: 0.0697 - mae: 0.1472 - rmse: 0.2294 - smape: 0.3701 - val_ia: 0.6809 - val_loss: 0.0602 - val_mae: 0.1371 - val_rmse: 0.1912 - val_smape: 0.3627

Epoch 15/64

1916/1916 - 42s - 22ms/step - ia: 0.8929 - loss: 0.0683 - mae: 0.1454 - rmse: 0.2270 - smape: 0.3672 - val_ia: 0.6732 - val_loss: 0.0589 - val_mae: 0.1364 - val_rmse: 0.1906 - val_smape: 0.3601

Epoch 16/64

1916/1916 - 81s - 42ms/step - ia: 0.8948 - loss: 0.0672 - mae: 0.1437 - rmse: 0.2244 - smape: 0.3639 - val_ia: 0.6706 - val_loss: 0.0583 - val_mae: 0.1363 - val_rmse: 0.1904 - val_smape: 0.3588

Epoch 17/64

1916/1916 - 41s - 21ms/step - ia: 0.8953 - loss: 0.0667 - mae: 0.1431 - rmse: 0.2234 - smape: 0.3626 - val_ia: 0.6878 - val_loss: 0.0576 - val_mae: 0.1325 - val_rmse: 0.1867 - val_smape: 0.3551

Epoch 18/64

1916/1916 - 41s - 21ms/step - ia: 0.8958 - loss: 0.0661 - mae: 0.1424 - rmse: 0.2224 - smape: 0.3613 - val_ia: 0.6833 - val_loss: 0.0595 - val_mae: 0.1380 - val_rmse: 0.1904 - val_smape: 0.3701

Epoch 19/64

1916/1916 - 43s - 22ms/step - ia: 0.8958 - loss: 0.0657 - mae: 0.1422 - rmse: 0.2215 - smape: 0.3620 - val_ia: 0.6906 - val_loss: 0.0579 - val_mae: 0.1338 - val_rmse: 0.1872 - val_smape: 0.3614

Epoch 20/64

1916/1916 - 91s - 48ms/step - ia: 0.8957 - loss: 0.0654 - mae: 0.1418 - rmse: 0.2218 - smape: 0.3615 - val_ia: 0.6874 - val_loss: 0.0568 - val_mae: 0.1310 - val_rmse: 0.1859 - val_smape: 0.3505

Epoch 21/64

1916/1916 - 82s - 43ms/step - ia: 0.8966 - loss: 0.0651 - mae: 0.1415 - rmse: 0.2215 - smape: 0.3596 - val_ia: 0.6922 - val_loss: 0.0565 - val_mae: 0.1300 - val_rmse: 0.1847 - val_smape: 0.3498

Epoch 22/64

1916/1916 - 52s - 27ms/step - ia: 0.8964 - loss: 0.0650 - mae: 0.1417 - rmse: 0.2205 - smape: 0.3619 - val_ia: 0.6900 - val_loss: 0.0565 - val_mae: 0.1305 - val_rmse: 0.1848 - val_smape: 0.3502

Epoch 23/64

1916/1916 - 52s - 27ms/step - ia: 0.8970 - loss: 0.0647 - mae: 0.1412 - rmse: 0.2204 - smape: 0.3599 - val_ia: 0.6631 - val_loss: 0.0575 - val_mae: 0.1377 - val_rmse: 0.1910 - val_smape: 0.3610

Epoch 24/64

1916/1916 - 54s - 28ms/step - ia: 0.8963 - loss: 0.0647 - mae: 0.1414 - rmse: 0.2200 - smape: 0.3607 - val_ia: 0.6853 - val_loss: 0.0565 - val_mae: 0.1318 - val_rmse: 0.1853 - val_smape: 0.3524

Epoch 25/64

1916/1916 - 53s - 28ms/step - ia: 0.8957 - loss: 0.0648 - mae: 0.1420 - rmse: 0.2211 - smape: 0.3628 - val_ia: 0.6941 - val_loss: 0.0565 - val_mae: 0.1306 - val_rmse: 0.1845 - val_smape: 0.3525

Epoch 26/64

1916/1916 - 56s - 29ms/step - ia: 0.8962 - loss: 0.0645 - mae: 0.1413 - rmse: 0.2193 - smape: 0.3603 - val_ia: 0.6866 - val_loss: 0.0564 - val_mae: 0.1308 - val_rmse: 0.1856 - val_smape: 0.3495

Epoch 27/64

1916/1916 - 83s - 44ms/step - ia: 0.8971 - loss: 0.0644 - mae: 0.1406 - rmse: 0.2196 - smape: 0.3586 - val_ia: 0.6917 - val_loss: 0.0560 - val_mae: 0.1299 - val_rmse: 0.1841 - val_smape: 0.3495

Epoch 28/64

1916/1916 - 53s - 28ms/step - ia: 0.8966 - loss: 0.0643 - mae: 0.1408 - rmse: 0.2203 - smape: 0.3584 - val_ia: 0.6685 - val_loss: 0.0571 - val_mae: 0.1358 - val_rmse: 0.1897 - val_smape: 0.3581

Epoch 29/64

1916/1916 - 49s - 25ms/step - ia: 0.8964 - loss: 0.0640 - mae: 0.1406 - rmse: 0.2192 - smape: 0.3603 - val_ia: 0.6910 - val_loss: 0.0572 - val_mae: 0.1335 - val_rmse: 0.1864 - val_smape: 0.3602

Epoch 30/64

1916/1916 - 89s - 47ms/step - ia: 0.8969 - loss: 0.0641 - mae: 0.1404 - rmse: 0.2192 - smape: 0.3595 - val_ia: 0.6953 - val_loss: 0.0559 - val_mae: 0.1294 - val_rmse: 0.1834 - val_smape: 0.3497

Epoch 31/64

1916/1916 - 56s - 29ms/step - ia: 0.8969 - loss: 0.0640 - mae: 0.1404 - rmse: 0.2189 - smape: 0.3593 - val_ia: 0.6967 - val_loss: 0.0558 - val_mae: 0.1291 - val_rmse: 0.1832 - val_smape: 0.3493

Epoch 32/64

1916/1916 - 36s - 19ms/step - ia: 0.8975 - loss: 0.0639 - mae: 0.1402 - rmse: 0.2181 - smape: 0.3589 - val_ia: 0.6669 - val_loss: 0.0567 - val_mae: 0.1364 - val_rmse: 0.1888 - val_smape: 0.3584

Epoch 33/64

1916/1916 - 55s - 29ms/step - ia: 0.8968 - loss: 0.0638 - mae: 0.1402 - rmse: 0.2190 - smape: 0.3573 - val_ia: 0.6860 - val_loss: 0.0559 - val_mae: 0.1308 - val_rmse: 0.1851 - val_smape: 0.3504

Epoch 34/64

1916/1916 - 82s - 43ms/step - ia: 0.8971 - loss: 0.0638 - mae: 0.1404 - rmse: 0.2186 - smape: 0.3583 - val_ia: 0.6918 - val_loss: 0.0556 - val_mae: 0.1293 - val_rmse: 0.1834 - val_smape: 0.3484

Epoch 35/64

1916/1916 - 55s - 29ms/step - ia: 0.8975 - loss: 0.0637 - mae: 0.1400 - rmse: 0.2187 - smape: 0.3572 - val_ia: 0.6804 - val_loss: 0.0560 - val_mae: 0.1320 - val_rmse: 0.1859 - val_smape: 0.3517

Epoch 36/64

1916/1916 - 55s - 28ms/step - ia: 0.8965 - loss: 0.0637 - mae: 0.1408 - rmse: 0.2192 - smape: 0.3593 - val_ia: 0.6720 - val_loss: 0.0565 - val_mae: 0.1347 - val_rmse: 0.1883 - val_smape: 0.3565

Epoch 37/64

1916/1916 - 55s - 29ms/step - ia: 0.8966 - loss: 0.0636 - mae: 0.1404 - rmse: 0.2187 - smape: 0.3597 - val_ia: 0.6768 - val_loss: 0.0560 - val_mae: 0.1330 - val_rmse: 0.1866 - val_smape: 0.3535

Epoch 38/64

1916/1916 - 52s - 27ms/step - ia: 0.8966 - loss: 0.0635 - mae: 0.1404 - rmse: 0.2189 - smape: 0.3594 - val_ia: 0.6732 - val_loss: 0.0565 - val_mae: 0.1342 - val_rmse: 0.1881 - val_smape: 0.3560

Epoch 39/64

1916/1916 - 56s - 29ms/step - ia: 0.8977 - loss: 0.0633 - mae: 0.1398 - rmse: 0.2187 - smape: 0.3587 - val_ia: 0.6926 - val_loss: 0.0560 - val_mae: 0.1309 - val_rmse: 0.1838 - val_smape: 0.3519

Epoch 40/64

1916/1916 - 55s - 29ms/step - ia: 0.8968 - loss: 0.0635 - mae: 0.1410 - rmse: 0.2188 - smape: 0.3610 - val_ia: 0.6957 - val_loss: 0.0554 - val_mae: 0.1286 - val_rmse: 0.1828 - val_smape: 0.3477

Epoch 41/64

1916/1916 - 52s - 27ms/step - ia: 0.8969 - loss: 0.0634 - mae: 0.1404 - rmse: 0.2188 - smape: 0.3595 - val_ia: 0.6937 - val_loss: 0.0555 - val_mae: 0.1297 - val_rmse: 0.1831 - val_smape: 0.3493

Epoch 42/64

1916/1916 - 54s - 28ms/step - ia: 0.8970 - loss: 0.0634 - mae: 0.1402 - rmse: 0.2188 - smape: 0.3584 - val_ia: 0.6957 - val_loss: 0.0559 - val_mae: 0.1304 - val_rmse: 0.1836 - val_smape: 0.3516

Epoch 43/64

1916/1916 - 55s - 29ms/step - ia: 0.8971 - loss: 0.0633 - mae: 0.1401 - rmse: 0.2180 - smape: 0.3584 - val_ia: 0.6814 - val_loss: 0.0579 - val_mae: 0.1379 - val_rmse: 0.1903 - val_smape: 0.3688

Epoch 44/64

1916/1916 - 53s - 28ms/step - ia: 0.8964 - loss: 0.0633 - mae: 0.1408 - rmse: 0.2191 - smape: 0.3611 - val_ia: 0.6585 - val_loss: 0.0577 - val_mae: 0.1395 - val_rmse: 0.1931 - val_smape: 0.3693

Epoch 45/64

1916/1916 - 84s - 44ms/step - ia: 0.8979 - loss: 0.0632 - mae: 0.1397 - rmse: 0.2181 - smape: 0.3584 - val_ia: 0.6917 - val_loss: 0.0554 - val_mae: 0.1297 - val_rmse: 0.1830 - val_smape: 0.3492

Epoch 46/64

1916/1916 - 52s - 27ms/step - ia: 0.8968 - loss: 0.0631 - mae: 0.1399 - rmse: 0.2190 - smape: 0.3592 - val_ia: 0.6661 - val_loss: 0.0564 - val_mae: 0.1362 - val_rmse: 0.1889 - val_smape: 0.3591

Epoch 47/64

1916/1916 - 52s - 27ms/step - ia: 0.8971 - loss: 0.0632 - mae: 0.1400 - rmse: 0.2185 - smape: 0.3579 - val_ia: 0.6699 - val_loss: 0.0562 - val_mae: 0.1352 - val_rmse: 0.1882 - val_smape: 0.3577

Epoch 48/64

1916/1916 - 52s - 27ms/step - ia: 0.8977 - loss: 0.0630 - mae: 0.1394 - rmse: 0.2170 - smape: 0.3568 - val_ia: 0.6537 - val_loss: 0.0575 - val_mae: 0.1408 - val_rmse: 0.1934 - val_smape: 0.3705

Epoch 49/64

1916/1916 - 55s - 29ms/step - ia: 0.8974 - loss: 0.0629 - mae: 0.1399 - rmse: 0.2177 - smape: 0.3595 - val_ia: 0.6934 - val_loss: 0.0552 - val_mae: 0.1291 - val_rmse: 0.1831 - val_smape: 0.3474

Epoch 50/64

1916/1916 - 51s - 27ms/step - ia: 0.8976 - loss: 0.0630 - mae: 0.1400 - rmse: 0.2175 - smape: 0.3580 - val_ia: 0.6849 - val_loss: 0.0578 - val_mae: 0.1371 - val_rmse: 0.1890 - val_smape: 0.3661

Epoch 51/64

1916/1916 - 55s - 29ms/step - ia: 0.8973 - loss: 0.0631 - mae: 0.1400 - rmse: 0.2175 - smape: 0.3593 - val_ia: 0.6716 - val_loss: 0.0563 - val_mae: 0.1347 - val_rmse: 0.1883 - val_smape: 0.3580

Epoch 52/64

1916/1916 - 56s - 29ms/step - ia: 0.8983 - loss: 0.0628 - mae: 0.1393 - rmse: 0.2174 - smape: 0.3581 - val_ia: 0.6978 - val_loss: 0.0552 - val_mae: 0.1287 - val_rmse: 0.1823 - val_smape: 0.3476

Epoch 53/64

1916/1916 - 81s - 42ms/step - ia: 0.8979 - loss: 0.0629 - mae: 0.1396 - rmse: 0.2176 - smape: 0.3565 - val_ia: 0.6543 - val_loss: 0.0583 - val_mae: 0.1415 - val_rmse: 0.1950 - val_smape: 0.3748

Epoch 54/64

1916/1916 - 53s - 28ms/step - ia: 0.8977 - loss: 0.0627 - mae: 0.1394 - rmse: 0.2173 - smape: 0.3575 - val_ia: 0.7007 - val_loss: 0.0551 - val_mae: 0.1281 - val_rmse: 0.1820 - val_smape: 0.3474

Epoch 55/64

1916/1916 - 51s - 27ms/step - ia: 0.8974 - loss: 0.0626 - mae: 0.1393 - rmse: 0.2173 - smape: 0.3571 - val_ia: 0.6811 - val_loss: 0.0581 - val_mae: 0.1388 - val_rmse: 0.1905 - val_smape: 0.3698

Epoch 56/64

1916/1916 - 86s - 45ms/step - ia: 0.8972 - loss: 0.0628 - mae: 0.1398 - rmse: 0.2170 - smape: 0.3578 - val_ia: 0.6854 - val_loss: 0.0576 - val_mae: 0.1368 - val_rmse: 0.1886 - val_smape: 0.3664

Epoch 57/64

1916/1916 - 55s - 29ms/step - ia: 0.8978 - loss: 0.0627 - mae: 0.1391 - rmse: 0.2172 - smape: 0.3556 - val_ia: 0.6926 - val_loss: 0.0561 - val_mae: 0.1324 - val_rmse: 0.1848 - val_smape: 0.3573

Epoch 58/64

1916/1916 - 53s - 28ms/step - ia: 0.8976 - loss: 0.0627 - mae: 0.1395 - rmse: 0.2171 - smape: 0.3571 - val_ia: 0.6824 - val_loss: 0.0584 - val_mae: 0.1387 - val_rmse: 0.1901 - val_smape: 0.3696

Epoch 59/64

1916/1916 - 55s - 29ms/step - ia: 0.8977 - loss: 0.0625 - mae: 0.1396 - rmse: 0.2170 - smape: 0.3585 - val_ia: 0.6898 - val_loss: 0.0568 - val_mae: 0.1344 - val_rmse: 0.1868 - val_smape: 0.3594

Epoch 60/64

1916/1916 - 55s - 29ms/step - ia: 0.8976 - loss: 0.0626 - mae: 0.1397 - rmse: 0.2177 - smape: 0.3585 - val_ia: 0.6958 - val_loss: 0.0551 - val_mae: 0.1281 - val_rmse: 0.1827 - val_smape: 0.3459

Epoch 61/64

1916/1916 - 81s - 42ms/step - ia: 0.8979 - loss: 0.0625 - mae: 0.1392 - rmse: 0.2171 - smape: 0.3570 - val_ia: 0.6930 - val_loss: 0.0549 - val_mae: 0.1285 - val_rmse: 0.1825 - val_smape: 0.3473

Epoch 62/64

1916/1916 - 82s - 43ms/step - ia: 0.8975 - loss: 0.0626 - mae: 0.1395 - rmse: 0.2165 - smape: 0.3567 - val_ia: 0.6986 - val_loss: 0.0549 - val_mae: 0.1286 - val_rmse: 0.1819 - val_smape: 0.3482

Epoch 63/64

1916/1916 - 53s - 28ms/step - ia: 0.8974 - loss: 0.0624 - mae: 0.1395 - rmse: 0.2173 - smape: 0.3575 - val_ia: 0.6895 - val_loss: 0.0572 - val_mae: 0.1348 - val_rmse: 0.1864 - val_smape: 0.3585

Epoch 64/64

1916/1916 - 83s - 44ms/step - ia: 0.8978 - loss: 0.0624 - mae: 0.1391 - rmse: 0.2162 - smape: 0.3567 - val_ia: 0.6975 - val_loss: 0.0555 - val_mae: 0.1302 - val_rmse: 0.1835 - val_smape: 0.3511

Restoring model weights from the end of the best epoch: 61.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 6:21 3s/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step

 46%|████▌     | 23/50 [8:43:23<35:35:27, 4745.48s/trial, best loss: 0.03723732727116705]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 56s - 58ms/step - ia: 0.1829 - loss: 1.0259 - mae: 0.7595 - rmse: 0.9909 - smape: 1.6473 - val_ia: 0.2391 - val_loss: 0.9661 - val_mae: 0.7405 - val_rmse: 0.8254 - val_smape: 1.9181

Epoch 2/256

958/958 - 46s - 48ms/step - ia: 0.3348 - loss: 0.8111 - mae: 0.6522 - rmse: 0.8683 - smape: 1.3788 - val_ia: 0.3849 - val_loss: 0.3756 - val_mae: 0.4166 - val_rmse: 0.5066 - val_smape: 0.8064

Epoch 3/256

958/958 - 37s - 39ms/step - ia: 0.6828 - loss: 0.3768 - mae: 0.4199 - rmse: 0.5948 - smape: 0.8137 - val_ia: 0.4468 - val_loss: 0.2662 - val_mae: 0.3509 - val_rmse: 0.4371 - val_smape: 0.7367

Epoch 4/256

958/958 - 31s - 33ms/step - ia: 0.7195 - loss: 0.3053 - mae: 0.3782 - rmse: 0.5344 - smape: 0.7636 - val_ia: 0.5033 - val_loss: 0.2194 - val_mae: 0.3083 - val_rmse: 0.3923 - val_smape: 0.6693

Epoch 5/256

958/958 - 51s - 54ms/step - ia: 0.7399 - loss: 0.2643 - mae: 0.3522 - rmse: 0.4973 - smape: 0.7296 - val_ia: 0.5256 - val_loss: 0.1872 - val_mae: 0.2898 - val_rmse: 0.3709 - val_smape: 0.6495

Epoch 6/256

958/958 - 76s - 79ms/step - ia: 0.7581 - loss: 0.2361 - mae: 0.3320 - rmse: 0.4689 - smape: 0.6984 - val_ia: 0.5698 - val_loss: 0.1701 - val_mae: 0.2650 - val_rmse: 0.3464 - val_smape: 0.5985

Epoch 7/256

958/958 - 36s - 38ms/step - ia: 0.7695 - loss: 0.2148 - mae: 0.3156 - rmse: 0.4471 - smape: 0.6773 - val_ia: 0.5945 - val_loss: 0.1478 - val_mae: 0.2456 - val_rmse: 0.3256 - val_smape: 0.5669

Epoch 8/256

958/958 - 34s - 35ms/step - ia: 0.7801 - loss: 0.1983 - mae: 0.3028 - rmse: 0.4287 - smape: 0.6529 - val_ia: 0.6086 - val_loss: 0.1356 - val_mae: 0.2343 - val_rmse: 0.3122 - val_smape: 0.5485

Epoch 9/256

958/958 - 34s - 36ms/step - ia: 0.7871 - loss: 0.1856 - mae: 0.2938 - rmse: 0.4151 - smape: 0.6427 - val_ia: 0.6276 - val_loss: 0.1241 - val_mae: 0.2221 - val_rmse: 0.2989 - val_smape: 0.5254

Epoch 10/256

958/958 - 41s - 43ms/step - ia: 0.7942 - loss: 0.1752 - mae: 0.2846 - rmse: 0.4029 - smape: 0.6281 - val_ia: 0.6475 - val_loss: 0.1163 - val_mae: 0.2121 - val_rmse: 0.2888 - val_smape: 0.5091

Epoch 11/256

958/958 - 43s - 45ms/step - ia: 0.7996 - loss: 0.1678 - mae: 0.2779 - rmse: 0.3922 - smape: 0.6175 - val_ia: 0.6517 - val_loss: 0.1105 - val_mae: 0.2074 - val_rmse: 0.2816 - val_smape: 0.5020

Epoch 12/256

958/958 - 35s - 36ms/step - ia: 0.8047 - loss: 0.1610 - mae: 0.2716 - rmse: 0.3850 - smape: 0.6052 - val_ia: 0.6499 - val_loss: 0.1035 - val_mae: 0.2037 - val_rmse: 0.2751 - val_smape: 0.4921

Epoch 13/256

958/958 - 34s - 36ms/step - ia: 0.8092 - loss: 0.1546 - mae: 0.2652 - rmse: 0.3764 - smape: 0.5950 - val_ia: 0.6585 - val_loss: 0.0996 - val_mae: 0.1989 - val_rmse: 0.2691 - val_smape: 0.4850

Epoch 14/256

958/958 - 34s - 36ms/step - ia: 0.8115 - loss: 0.1480 - mae: 0.2612 - rmse: 0.3694 - smape: 0.5881 - val_ia: 0.6686 - val_loss: 0.0976 - val_mae: 0.1953 - val_rmse: 0.2651 - val_smape: 0.4818

Epoch 15/256

958/958 - 42s - 43ms/step - ia: 0.8160 - loss: 0.1437 - mae: 0.2553 - rmse: 0.3623 - smape: 0.5788 - val_ia: 0.6683 - val_loss: 0.0914 - val_mae: 0.1909 - val_rmse: 0.2604 - val_smape: 0.4677

Epoch 16/256

958/958 - 41s - 42ms/step - ia: 0.8211 - loss: 0.1367 - mae: 0.2487 - rmse: 0.3539 - smape: 0.5662 - val_ia: 0.6853 - val_loss: 0.0895 - val_mae: 0.1850 - val_rmse: 0.2541 - val_smape: 0.4628

Epoch 17/256

958/958 - 34s - 36ms/step - ia: 0.8227 - loss: 0.1340 - mae: 0.2465 - rmse: 0.3506 - smape: 0.5638 - val_ia: 0.6909 - val_loss: 0.0854 - val_mae: 0.1801 - val_rmse: 0.2489 - val_smape: 0.4518

Epoch 18/256

958/958 - 35s - 36ms/step - ia: 0.8255 - loss: 0.1308 - mae: 0.2433 - rmse: 0.3457 - smape: 0.5585 - val_ia: 0.6770 - val_loss: 0.0840 - val_mae: 0.1836 - val_rmse: 0.2493 - val_smape: 0.4546

Epoch 19/256

958/958 - 36s - 38ms/step - ia: 0.8295 - loss: 0.1259 - mae: 0.2380 - rmse: 0.3387 - smape: 0.5487 - val_ia: 0.6968 - val_loss: 0.0814 - val_mae: 0.1759 - val_rmse: 0.2431 - val_smape: 0.4447

Epoch 20/256

958/958 - 34s - 36ms/step - ia: 0.8306 - loss: 0.1234 - mae: 0.2359 - rmse: 0.3360 - smape: 0.5445 - val_ia: 0.7005 - val_loss: 0.0809 - val_mae: 0.1754 - val_rmse: 0.2417 - val_smape: 0.4450

Epoch 21/256

958/958 - 33s - 35ms/step - ia: 0.8340 - loss: 0.1210 - mae: 0.2322 - rmse: 0.3317 - smape: 0.5396 - val_ia: 0.6943 - val_loss: 0.0774 - val_mae: 0.1737 - val_rmse: 0.2389 - val_smape: 0.4370

Epoch 22/256

958/958 - 33s - 35ms/step - ia: 0.8359 - loss: 0.1181 - mae: 0.2292 - rmse: 0.3281 - smape: 0.5318 - val_ia: 0.6913 - val_loss: 0.0765 - val_mae: 0.1742 - val_rmse: 0.2379 - val_smape: 0.4375

Epoch 23/256

958/958 - 34s - 36ms/step - ia: 0.8379 - loss: 0.1158 - mae: 0.2260 - rmse: 0.3240 - smape: 0.5276 - val_ia: 0.7084 - val_loss: 0.0743 - val_mae: 0.1669 - val_rmse: 0.2335 - val_smape: 0.4264

Epoch 24/256

958/958 - 33s - 35ms/step - ia: 0.8400 - loss: 0.1144 - mae: 0.2238 - rmse: 0.3225 - smape: 0.5229 - val_ia: 0.7212 - val_loss: 0.0735 - val_mae: 0.1632 - val_rmse: 0.2313 - val_smape: 0.4212

Epoch 25/256

958/958 - 33s - 35ms/step - ia: 0.8417 - loss: 0.1110 - mae: 0.2216 - rmse: 0.3175 - smape: 0.5182 - val_ia: 0.7194 - val_loss: 0.0723 - val_mae: 0.1633 - val_rmse: 0.2294 - val_smape: 0.4210

Epoch 26/256

958/958 - 41s - 43ms/step - ia: 0.8441 - loss: 0.1088 - mae: 0.2179 - rmse: 0.3137 - smape: 0.5120 - val_ia: 0.7177 - val_loss: 0.0718 - val_mae: 0.1636 - val_rmse: 0.2288 - val_smape: 0.4216

Epoch 27/256

958/958 - 35s - 37ms/step - ia: 0.8451 - loss: 0.1073 - mae: 0.2170 - rmse: 0.3114 - smape: 0.5110 - val_ia: 0.7151 - val_loss: 0.0701 - val_mae: 0.1627 - val_rmse: 0.2268 - val_smape: 0.4173

Epoch 28/256

958/958 - 33s - 35ms/step - ia: 0.8460 - loss: 0.1064 - mae: 0.2157 - rmse: 0.3099 - smape: 0.5092 - val_ia: 0.7258 - val_loss: 0.0704 - val_mae: 0.1606 - val_rmse: 0.2264 - val_smape: 0.4166

Epoch 29/256

958/958 - 33s - 34ms/step - ia: 0.8484 - loss: 0.1048 - mae: 0.2127 - rmse: 0.3074 - smape: 0.5018 - val_ia: 0.7117 - val_loss: 0.0690 - val_mae: 0.1628 - val_rmse: 0.2263 - val_smape: 0.4170

Epoch 30/256

958/958 - 28s - 30ms/step - ia: 0.8476 - loss: 0.1050 - mae: 0.2131 - rmse: 0.3076 - smape: 0.5053 - val_ia: 0.7252 - val_loss: 0.0679 - val_mae: 0.1576 - val_rmse: 0.2234 - val_smape: 0.4089

Epoch 31/256

958/958 - 36s - 37ms/step - ia: 0.8501 - loss: 0.1033 - mae: 0.2100 - rmse: 0.3048 - smape: 0.4962 - val_ia: 0.7342 - val_loss: 0.0676 - val_mae: 0.1554 - val_rmse: 0.2219 - val_smape: 0.4057

Epoch 32/256

958/958 - 33s - 34ms/step - ia: 0.8509 - loss: 0.1001 - mae: 0.2080 - rmse: 0.3003 - smape: 0.4981 - val_ia: 0.7040 - val_loss: 0.0687 - val_mae: 0.1655 - val_rmse: 0.2285 - val_smape: 0.4236

Epoch 33/256

958/958 - 41s - 43ms/step - ia: 0.8522 - loss: 0.1008 - mae: 0.2080 - rmse: 0.3017 - smape: 0.4945 - val_ia: 0.7266 - val_loss: 0.0664 - val_mae: 0.1563 - val_rmse: 0.2209 - val_smape: 0.4050

Epoch 34/256

958/958 - 33s - 34ms/step - ia: 0.8539 - loss: 0.0983 - mae: 0.2049 - rmse: 0.2977 - smape: 0.4884 - val_ia: 0.7415 - val_loss: 0.0657 - val_mae: 0.1521 - val_rmse: 0.2185 - val_smape: 0.3999

Epoch 35/256

958/958 - 43s - 45ms/step - ia: 0.8548 - loss: 0.0978 - mae: 0.2039 - rmse: 0.2967 - smape: 0.4862 - val_ia: 0.7396 - val_loss: 0.0660 - val_mae: 0.1532 - val_rmse: 0.2190 - val_smape: 0.4021

Epoch 36/256

958/958 - 33s - 35ms/step - ia: 0.8560 - loss: 0.0958 - mae: 0.2025 - rmse: 0.2945 - smape: 0.4829 - val_ia: 0.7347 - val_loss: 0.0651 - val_mae: 0.1534 - val_rmse: 0.2177 - val_smape: 0.4010

Epoch 37/256

958/958 - 33s - 35ms/step - ia: 0.8552 - loss: 0.0989 - mae: 0.2033 - rmse: 0.2982 - smape: 0.4837 - val_ia: 0.7422 - val_loss: 0.0643 - val_mae: 0.1501 - val_rmse: 0.2162 - val_smape: 0.3960

Epoch 38/256

958/958 - 33s - 35ms/step - ia: 0.8578 - loss: 0.0953 - mae: 0.2000 - rmse: 0.2912 - smape: 0.4783 - val_ia: 0.7384 - val_loss: 0.0640 - val_mae: 0.1515 - val_rmse: 0.2158 - val_smape: 0.3956

Epoch 39/256

958/958 - 33s - 35ms/step - ia: 0.8582 - loss: 0.0951 - mae: 0.1994 - rmse: 0.2917 - smape: 0.4780 - val_ia: 0.7332 - val_loss: 0.0638 - val_mae: 0.1520 - val_rmse: 0.2170 - val_smape: 0.3957

Epoch 40/256

958/958 - 25s - 26ms/step - ia: 0.8595 - loss: 0.0948 - mae: 0.1988 - rmse: 0.2904 - smape: 0.4760 - val_ia: 0.7401 - val_loss: 0.0630 - val_mae: 0.1500 - val_rmse: 0.2142 - val_smape: 0.3927

Epoch 41/256

958/958 - 22s - 23ms/step - ia: 0.8594 - loss: 0.0937 - mae: 0.1978 - rmse: 0.2894 - smape: 0.4737 - val_ia: 0.7466 - val_loss: 0.0624 - val_mae: 0.1474 - val_rmse: 0.2130 - val_smape: 0.3881

Epoch 42/256

958/958 - 33s - 35ms/step - ia: 0.8600 - loss: 0.0927 - mae: 0.1968 - rmse: 0.2883 - smape: 0.4749 - val_ia: 0.7485 - val_loss: 0.0623 - val_mae: 0.1471 - val_rmse: 0.2125 - val_smape: 0.3879

Epoch 43/256

958/958 - 33s - 35ms/step - ia: 0.8599 - loss: 0.0920 - mae: 0.1961 - rmse: 0.2872 - smape: 0.4708 - val_ia: 0.7463 - val_loss: 0.0621 - val_mae: 0.1474 - val_rmse: 0.2122 - val_smape: 0.3882

Epoch 44/256

958/958 - 29s - 31ms/step - ia: 0.8608 - loss: 0.0921 - mae: 0.1960 - rmse: 0.2870 - smape: 0.4701 - val_ia: 0.7477 - val_loss: 0.0615 - val_mae: 0.1462 - val_rmse: 0.2116 - val_smape: 0.3853

Epoch 45/256

958/958 - 25s - 26ms/step - ia: 0.8618 - loss: 0.0915 - mae: 0.1946 - rmse: 0.2863 - smape: 0.4674 - val_ia: 0.7407 - val_loss: 0.0620 - val_mae: 0.1483 - val_rmse: 0.2134 - val_smape: 0.3876

Epoch 46/256

958/958 - 30s - 31ms/step - ia: 0.8621 - loss: 0.0918 - mae: 0.1949 - rmse: 0.2858 - smape: 0.4691 - val_ia: 0.7491 - val_loss: 0.0624 - val_mae: 0.1479 - val_rmse: 0.2128 - val_smape: 0.3932

Epoch 47/256

958/958 - 45s - 47ms/step - ia: 0.8635 - loss: 0.0901 - mae: 0.1928 - rmse: 0.2834 - smape: 0.4661 - val_ia: 0.7489 - val_loss: 0.0610 - val_mae: 0.1452 - val_rmse: 0.2106 - val_smape: 0.3836

Epoch 48/256

958/958 - 41s - 42ms/step - ia: 0.8636 - loss: 0.0897 - mae: 0.1920 - rmse: 0.2826 - smape: 0.4636 - val_ia: 0.7529 - val_loss: 0.0607 - val_mae: 0.1445 - val_rmse: 0.2094 - val_smape: 0.3826

Epoch 49/256

958/958 - 25s - 26ms/step - ia: 0.8653 - loss: 0.0879 - mae: 0.1897 - rmse: 0.2800 - smape: 0.4604 - val_ia: 0.7489 - val_loss: 0.0607 - val_mae: 0.1460 - val_rmse: 0.2096 - val_smape: 0.3843

Epoch 50/256

958/958 - 22s - 23ms/step - ia: 0.8642 - loss: 0.0893 - mae: 0.1909 - rmse: 0.2815 - smape: 0.4616 - val_ia: 0.7560 - val_loss: 0.0603 - val_mae: 0.1428 - val_rmse: 0.2091 - val_smape: 0.3784

Epoch 51/256

958/958 - 32s - 34ms/step - ia: 0.8650 - loss: 0.0892 - mae: 0.1903 - rmse: 0.2812 - smape: 0.4572 - val_ia: 0.7509 - val_loss: 0.0599 - val_mae: 0.1441 - val_rmse: 0.2085 - val_smape: 0.3802

Epoch 52/256

958/958 - 33s - 34ms/step - ia: 0.8661 - loss: 0.0880 - mae: 0.1891 - rmse: 0.2798 - smape: 0.4551 - val_ia: 0.7520 - val_loss: 0.0596 - val_mae: 0.1433 - val_rmse: 0.2080 - val_smape: 0.3792

Epoch 53/256

958/958 - 30s - 31ms/step - ia: 0.8657 - loss: 0.0876 - mae: 0.1891 - rmse: 0.2798 - smape: 0.4572 - val_ia: 0.7492 - val_loss: 0.0597 - val_mae: 0.1444 - val_rmse: 0.2083 - val_smape: 0.3796

Epoch 54/256

958/958 - 22s - 23ms/step - ia: 0.8668 - loss: 0.0871 - mae: 0.1878 - rmse: 0.2779 - smape: 0.4534 - val_ia: 0.7579 - val_loss: 0.0594 - val_mae: 0.1421 - val_rmse: 0.2070 - val_smape: 0.3784

Epoch 55/256

958/958 - 29s - 30ms/step - ia: 0.8667 - loss: 0.0870 - mae: 0.1880 - rmse: 0.2779 - smape: 0.4521 - val_ia: 0.7569 - val_loss: 0.0594 - val_mae: 0.1423 - val_rmse: 0.2071 - val_smape: 0.3802

Epoch 56/256

958/958 - 33s - 35ms/step - ia: 0.8678 - loss: 0.0855 - mae: 0.1864 - rmse: 0.2758 - smape: 0.4536 - val_ia: 0.7561 - val_loss: 0.0587 - val_mae: 0.1411 - val_rmse: 0.2061 - val_smape: 0.3746

Epoch 57/256

958/958 - 39s - 41ms/step - ia: 0.8678 - loss: 0.0868 - mae: 0.1861 - rmse: 0.2763 - smape: 0.4497 - val_ia: 0.7509 - val_loss: 0.0589 - val_mae: 0.1429 - val_rmse: 0.2069 - val_smape: 0.3771

Epoch 58/256

958/958 - 23s - 24ms/step - ia: 0.8680 - loss: 0.0862 - mae: 0.1863 - rmse: 0.2764 - smape: 0.4504 - val_ia: 0.7571 - val_loss: 0.0585 - val_mae: 0.1407 - val_rmse: 0.2061 - val_smape: 0.3726

Epoch 59/256

958/958 - 29s - 30ms/step - ia: 0.8694 - loss: 0.0840 - mae: 0.1843 - rmse: 0.2733 - smape: 0.4483 - val_ia: 0.7621 - val_loss: 0.0585 - val_mae: 0.1397 - val_rmse: 0.2055 - val_smape: 0.3708

Epoch 60/256

958/958 - 33s - 34ms/step - ia: 0.8688 - loss: 0.0857 - mae: 0.1849 - rmse: 0.2754 - smape: 0.4484 - val_ia: 0.7470 - val_loss: 0.0586 - val_mae: 0.1436 - val_rmse: 0.2073 - val_smape: 0.3767

Epoch 61/256

958/958 - 34s - 35ms/step - ia: 0.8690 - loss: 0.0846 - mae: 0.1842 - rmse: 0.2740 - smape: 0.4452 - val_ia: 0.7541 - val_loss: 0.0580 - val_mae: 0.1411 - val_rmse: 0.2054 - val_smape: 0.3729

Epoch 62/256

958/958 - 40s - 42ms/step - ia: 0.8706 - loss: 0.0835 - mae: 0.1831 - rmse: 0.2712 - smape: 0.4446 - val_ia: 0.7621 - val_loss: 0.0579 - val_mae: 0.1388 - val_rmse: 0.2043 - val_smape: 0.3709

Epoch 63/256

958/958 - 33s - 35ms/step - ia: 0.8703 - loss: 0.0837 - mae: 0.1828 - rmse: 0.2722 - smape: 0.4437 - val_ia: 0.7544 - val_loss: 0.0578 - val_mae: 0.1406 - val_rmse: 0.2051 - val_smape: 0.3715

Epoch 64/256

958/958 - 33s - 34ms/step - ia: 0.8707 - loss: 0.0835 - mae: 0.1828 - rmse: 0.2720 - smape: 0.4427 - val_ia: 0.7530 - val_loss: 0.0581 - val_mae: 0.1420 - val_rmse: 0.2052 - val_smape: 0.3739

Epoch 65/256

958/958 - 33s - 35ms/step - ia: 0.8717 - loss: 0.0834 - mae: 0.1814 - rmse: 0.2714 - smape: 0.4403 - val_ia: 0.7579 - val_loss: 0.0575 - val_mae: 0.1398 - val_rmse: 0.2040 - val_smape: 0.3696

Epoch 66/256

958/958 - 33s - 34ms/step - ia: 0.8718 - loss: 0.0827 - mae: 0.1811 - rmse: 0.2701 - smape: 0.4406 - val_ia: 0.7562 - val_loss: 0.0572 - val_mae: 0.1403 - val_rmse: 0.2037 - val_smape: 0.3705

Epoch 67/256

958/958 - 33s - 35ms/step - ia: 0.8715 - loss: 0.0834 - mae: 0.1819 - rmse: 0.2712 - smape: 0.4431 - val_ia: 0.7630 - val_loss: 0.0576 - val_mae: 0.1379 - val_rmse: 0.2041 - val_smape: 0.3665

Epoch 68/256

958/958 - 35s - 37ms/step - ia: 0.8724 - loss: 0.0829 - mae: 0.1804 - rmse: 0.2701 - smape: 0.4409 - val_ia: 0.7629 - val_loss: 0.0585 - val_mae: 0.1410 - val_rmse: 0.2047 - val_smape: 0.3738

Epoch 69/256

958/958 - 43s - 45ms/step - ia: 0.8725 - loss: 0.0826 - mae: 0.1800 - rmse: 0.2695 - smape: 0.4386 - val_ia: 0.7544 - val_loss: 0.0574 - val_mae: 0.1403 - val_rmse: 0.2049 - val_smape: 0.3721

Epoch 70/256

958/958 - 30s - 31ms/step - ia: 0.8723 - loss: 0.0816 - mae: 0.1803 - rmse: 0.2684 - smape: 0.4385 - val_ia: 0.7571 - val_loss: 0.0573 - val_mae: 0.1403 - val_rmse: 0.2033 - val_smape: 0.3691

Epoch 71/256

958/958 - 30s - 31ms/step - ia: 0.8733 - loss: 0.0815 - mae: 0.1795 - rmse: 0.2681 - smape: 0.4375 - val_ia: 0.7661 - val_loss: 0.0570 - val_mae: 0.1376 - val_rmse: 0.2021 - val_smape: 0.3664

Epoch 72/256

958/958 - 25s - 26ms/step - ia: 0.8744 - loss: 0.0800 - mae: 0.1779 - rmse: 0.2658 - smape: 0.4344 - val_ia: 0.7657 - val_loss: 0.0567 - val_mae: 0.1371 - val_rmse: 0.2017 - val_smape: 0.3652

Epoch 73/256

958/958 - 30s - 31ms/step - ia: 0.8737 - loss: 0.0811 - mae: 0.1786 - rmse: 0.2672 - smape: 0.4340 - val_ia: 0.7587 - val_loss: 0.0581 - val_mae: 0.1415 - val_rmse: 0.2041 - val_smape: 0.3763

Epoch 74/256

958/958 - 30s - 32ms/step - ia: 0.8735 - loss: 0.0814 - mae: 0.1790 - rmse: 0.2676 - smape: 0.4377 - val_ia: 0.7683 - val_loss: 0.0564 - val_mae: 0.1361 - val_rmse: 0.2012 - val_smape: 0.3644

Epoch 75/256

958/958 - 30s - 31ms/step - ia: 0.8739 - loss: 0.0813 - mae: 0.1785 - rmse: 0.2670 - smape: 0.4377 - val_ia: 0.7616 - val_loss: 0.0568 - val_mae: 0.1387 - val_rmse: 0.2020 - val_smape: 0.3669

Epoch 76/256

958/958 - 30s - 31ms/step - ia: 0.8745 - loss: 0.0802 - mae: 0.1772 - rmse: 0.2652 - smape: 0.4346 - val_ia: 0.7686 - val_loss: 0.0565 - val_mae: 0.1358 - val_rmse: 0.2013 - val_smape: 0.3646

Epoch 77/256

958/958 - 41s - 43ms/step - ia: 0.8754 - loss: 0.0797 - mae: 0.1765 - rmse: 0.2648 - smape: 0.4309 - val_ia: 0.7657 - val_loss: 0.0560 - val_mae: 0.1358 - val_rmse: 0.2009 - val_smape: 0.3629

Epoch 78/256

958/958 - 41s - 43ms/step - ia: 0.8748 - loss: 0.0801 - mae: 0.1770 - rmse: 0.2648 - smape: 0.4324 - val_ia: 0.7566 - val_loss: 0.0565 - val_mae: 0.1395 - val_rmse: 0.2026 - val_smape: 0.3673

Epoch 79/256

958/958 - 30s - 31ms/step - ia: 0.8758 - loss: 0.0800 - mae: 0.1758 - rmse: 0.2643 - smape: 0.4306 - val_ia: 0.7608 - val_loss: 0.0559 - val_mae: 0.1374 - val_rmse: 0.2010 - val_smape: 0.3649

Epoch 80/256

958/958 - 29s - 30ms/step - ia: 0.8764 - loss: 0.0797 - mae: 0.1754 - rmse: 0.2632 - smape: 0.4280 - val_ia: 0.7654 - val_loss: 0.0558 - val_mae: 0.1356 - val_rmse: 0.2008 - val_smape: 0.3620

Epoch 81/256

958/958 - 28s - 30ms/step - ia: 0.8753 - loss: 0.0804 - mae: 0.1764 - rmse: 0.2657 - smape: 0.4312 - val_ia: 0.7625 - val_loss: 0.0586 - val_mae: 0.1427 - val_rmse: 0.2064 - val_smape: 0.3812

Epoch 82/256

958/958 - 25s - 27ms/step - ia: 0.8757 - loss: 0.0797 - mae: 0.1760 - rmse: 0.2646 - smape: 0.4307 - val_ia: 0.7609 - val_loss: 0.0560 - val_mae: 0.1371 - val_rmse: 0.2019 - val_smape: 0.3653

Epoch 83/256

958/958 - 26s - 27ms/step - ia: 0.8759 - loss: 0.0789 - mae: 0.1754 - rmse: 0.2631 - smape: 0.4303 - val_ia: 0.7655 - val_loss: 0.0556 - val_mae: 0.1357 - val_rmse: 0.2001 - val_smape: 0.3618

Epoch 84/256

958/958 - 29s - 30ms/step - ia: 0.8758 - loss: 0.0783 - mae: 0.1750 - rmse: 0.2625 - smape: 0.4303 - val_ia: 0.7730 - val_loss: 0.0555 - val_mae: 0.1337 - val_rmse: 0.1995 - val_smape: 0.3598

Epoch 85/256

958/958 - 28s - 29ms/step - ia: 0.8769 - loss: 0.0789 - mae: 0.1747 - rmse: 0.2632 - smape: 0.4278 - val_ia: 0.7479 - val_loss: 0.0563 - val_mae: 0.1416 - val_rmse: 0.2041 - val_smape: 0.3730

Epoch 86/256

958/958 - 26s - 27ms/step - ia: 0.8769 - loss: 0.0784 - mae: 0.1746 - rmse: 0.2620 - smape: 0.4292 - val_ia: 0.7631 - val_loss: 0.0552 - val_mae: 0.1359 - val_rmse: 0.1997 - val_smape: 0.3623

Epoch 87/256

958/958 - 31s - 33ms/step - ia: 0.8776 - loss: 0.0781 - mae: 0.1739 - rmse: 0.2611 - smape: 0.4291 - val_ia: 0.7675 - val_loss: 0.0552 - val_mae: 0.1347 - val_rmse: 0.1990 - val_smape: 0.3614

Epoch 88/256

958/958 - 37s - 38ms/step - ia: 0.8773 - loss: 0.0783 - mae: 0.1736 - rmse: 0.2625 - smape: 0.4262 - val_ia: 0.7744 - val_loss: 0.0559 - val_mae: 0.1350 - val_rmse: 0.2010 - val_smape: 0.3615

Epoch 89/256

958/958 - 43s - 45ms/step - ia: 0.8773 - loss: 0.0787 - mae: 0.1739 - rmse: 0.2629 - smape: 0.4257 - val_ia: 0.7688 - val_loss: 0.0551 - val_mae: 0.1341 - val_rmse: 0.1991 - val_smape: 0.3594

Epoch 90/256

958/958 - 25s - 26ms/step - ia: 0.8769 - loss: 0.0773 - mae: 0.1737 - rmse: 0.2602 - smape: 0.4277 - val_ia: 0.7670 - val_loss: 0.0551 - val_mae: 0.1354 - val_rmse: 0.1989 - val_smape: 0.3606

Epoch 91/256

958/958 - 28s - 30ms/step - ia: 0.8777 - loss: 0.0784 - mae: 0.1732 - rmse: 0.2621 - smape: 0.4260 - val_ia: 0.7699 - val_loss: 0.0555 - val_mae: 0.1355 - val_rmse: 0.1995 - val_smape: 0.3646

Epoch 92/256

958/958 - 24s - 26ms/step - ia: 0.8780 - loss: 0.0776 - mae: 0.1730 - rmse: 0.2608 - smape: 0.4232 - val_ia: 0.7576 - val_loss: 0.0553 - val_mae: 0.1376 - val_rmse: 0.2014 - val_smape: 0.3669

Epoch 93/256

958/958 - 46s - 48ms/step - ia: 0.8783 - loss: 0.0774 - mae: 0.1726 - rmse: 0.2601 - smape: 0.4247 - val_ia: 0.7666 - val_loss: 0.0550 - val_mae: 0.1353 - val_rmse: 0.1987 - val_smape: 0.3602

Epoch 94/256

958/958 - 24s - 25ms/step - ia: 0.8786 - loss: 0.0771 - mae: 0.1722 - rmse: 0.2597 - smape: 0.4223 - val_ia: 0.7643 - val_loss: 0.0561 - val_mae: 0.1379 - val_rmse: 0.2001 - val_smape: 0.3639

Epoch 95/256

958/958 - 30s - 31ms/step - ia: 0.8778 - loss: 0.0770 - mae: 0.1728 - rmse: 0.2600 - smape: 0.4241 - val_ia: 0.7755 - val_loss: 0.0548 - val_mae: 0.1328 - val_rmse: 0.1981 - val_smape: 0.3578

Epoch 96/256

958/958 - 29s - 31ms/step - ia: 0.8792 - loss: 0.0770 - mae: 0.1711 - rmse: 0.2594 - smape: 0.4207 - val_ia: 0.7698 - val_loss: 0.0557 - val_mae: 0.1361 - val_rmse: 0.1999 - val_smape: 0.3652

Epoch 97/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 16s - 8ms/step - ia: 0.6736 - loss: 0.3414 - mae: 0.4040 - rmse: 0.5349 - smape: 0.8369 - val_ia: 0.5262 - val_loss: 0.1124 - val_mae: 0.2140 - val_rmse: 0.2736 - val_smape: 0.5235

Epoch 2/128

1916/1916 - 12s - 6ms/step - ia: 0.7989 - loss: 0.1529 - mae: 0.2685 - rmse: 0.3668 - smape: 0.6036 - val_ia: 0.5949 - val_loss: 0.0855 - val_mae: 0.1780 - val_rmse: 0.2347 - val_smape: 0.4486

Epoch 3/128

1916/1916 - 12s - 6ms/step - ia: 0.8231 - loss: 0.1231 - mae: 0.2362 - rmse: 0.3261 - smape: 0.5469 - val_ia: 0.6290 - val_loss: 0.0724 - val_mae: 0.1588 - val_rmse: 0.2155 - val_smape: 0.4120

Epoch 4/128

1916/1916 - 12s - 6ms/step - ia: 0.8385 - loss: 0.1069 - mae: 0.2163 - rmse: 0.3021 - smape: 0.5085 - val_ia: 0.6004 - val_loss: 0.0714 - val_mae: 0.1677 - val_rmse: 0.2201 - val_smape: 0.4198

Epoch 5/128

1916/1916 - 12s - 6ms/step - ia: 0.8467 - loss: 0.0987 - mae: 0.2057 - rmse: 0.2895 - smape: 0.4899 - val_ia: 0.6354 - val_loss: 0.0646 - val_mae: 0.1517 - val_rmse: 0.2054 - val_smape: 0.3920

Epoch 6/128

1916/1916 - 21s - 11ms/step - ia: 0.8529 - loss: 0.0916 - mae: 0.1971 - rmse: 0.2779 - smape: 0.4719 - val_ia: 0.6479 - val_loss: 0.0620 - val_mae: 0.1462 - val_rmse: 0.2005 - val_smape: 0.3833

Epoch 7/128

1916/1916 - 12s - 6ms/step - ia: 0.8586 - loss: 0.0880 - mae: 0.1904 - rmse: 0.2712 - smape: 0.4574 - val_ia: 0.6433 - val_loss: 0.0616 - val_mae: 0.1479 - val_rmse: 0.2000 - val_smape: 0.3834

Epoch 8/128

1916/1916 - 12s - 6ms/step - ia: 0.8613 - loss: 0.0848 - mae: 0.1870 - rmse: 0.2665 - smape: 0.4496 - val_ia: 0.6628 - val_loss: 0.0590 - val_mae: 0.1401 - val_rmse: 0.1939 - val_smape: 0.3714

Epoch 9/128

1916/1916 - 21s - 11ms/step - ia: 0.8643 - loss: 0.0831 - mae: 0.1826 - rmse: 0.2622 - smape: 0.4420 - val_ia: 0.6593 - val_loss: 0.0590 - val_mae: 0.1414 - val_rmse: 0.1944 - val_smape: 0.3712

Epoch 10/128

1916/1916 - 20s - 10ms/step - ia: 0.8668 - loss: 0.0810 - mae: 0.1798 - rmse: 0.2587 - smape: 0.4369 - val_ia: 0.6767 - val_loss: 0.0571 - val_mae: 0.1353 - val_rmse: 0.1894 - val_smape: 0.3633

Epoch 11/128

1916/1916 - 11s - 6ms/step - ia: 0.8673 - loss: 0.0796 - mae: 0.1789 - rmse: 0.2558 - smape: 0.4347 - val_ia: 0.6751 - val_loss: 0.0569 - val_mae: 0.1356 - val_rmse: 0.1893 - val_smape: 0.3650

Epoch 12/128

1916/1916 - 13s - 7ms/step - ia: 0.8694 - loss: 0.0784 - mae: 0.1762 - rmse: 0.2536 - smape: 0.4285 - val_ia: 0.6737 - val_loss: 0.0574 - val_mae: 0.1372 - val_rmse: 0.1897 - val_smape: 0.3643

Epoch 13/128

1916/1916 - 13s - 7ms/step - ia: 0.8704 - loss: 0.0783 - mae: 0.1754 - rmse: 0.2536 - smape: 0.4265 - val_ia: 0.6876 - val_loss: 0.0569 - val_mae: 0.1343 - val_rmse: 0.1880 - val_smape: 0.3608

Epoch 14/128

1916/1916 - 12s - 6ms/step - ia: 0.8724 - loss: 0.0769 - mae: 0.1736 - rmse: 0.2514 - smape: 0.4226 - val_ia: 0.6638 - val_loss: 0.0570 - val_mae: 0.1383 - val_rmse: 0.1914 - val_smape: 0.3658

Epoch 15/128

1916/1916 - 12s - 6ms/step - ia: 0.8735 - loss: 0.0765 - mae: 0.1711 - rmse: 0.2489 - smape: 0.4165 - val_ia: 0.6915 - val_loss: 0.0559 - val_mae: 0.1315 - val_rmse: 0.1860 - val_smape: 0.3574

Epoch 16/128

1916/1916 - 12s - 6ms/step - ia: 0.8744 - loss: 0.0756 - mae: 0.1708 - rmse: 0.2484 - smape: 0.4152 - val_ia: 0.6759 - val_loss: 0.0574 - val_mae: 0.1368 - val_rmse: 0.1893 - val_smape: 0.3620

Epoch 17/128

1916/1916 - 12s - 6ms/step - ia: 0.8756 - loss: 0.0752 - mae: 0.1692 - rmse: 0.2467 - smape: 0.4141 - val_ia: 0.6766 - val_loss: 0.0561 - val_mae: 0.1341 - val_rmse: 0.1882 - val_smape: 0.3594

Epoch 18/128

1916/1916 - 12s - 6ms/step - ia: 0.8756 - loss: 0.0748 - mae: 0.1688 - rmse: 0.2465 - smape: 0.4114 - val_ia: 0.6599 - val_loss: 0.0568 - val_mae: 0.1394 - val_rmse: 0.1923 - val_smape: 0.3710

Epoch 19/128

1916/1916 - 13s - 7ms/step - ia: 0.8757 - loss: 0.0743 - mae: 0.1684 - rmse: 0.2459 - smape: 0.4111 - val_ia: 0.6765 - val_loss: 0.0563 - val_mae: 0.1353 - val_rmse: 0.1879 - val_smape: 0.3591

Epoch 20/128

1916/1916 - 12s - 6ms/step - ia: 0.8773 - loss: 0.0742 - mae: 0.1671 - rmse: 0.2451 - smape: 0.4077 - val_ia: 0.6978 - val_loss: 0.0552 - val_mae: 0.1301 - val_rmse: 0.1849 - val_smape: 0.3527

Epoch 21/128

1916/1916 - 13s - 7ms/step - ia: 0.8779 - loss: 0.0730 - mae: 0.1663 - rmse: 0.2440 - smape: 0.4041 - val_ia: 0.6752 - val_loss: 0.0558 - val_mae: 0.1349 - val_rmse: 0.1877 - val_smape: 0.3595

Epoch 22/128

1916/1916 - 12s - 6ms/step - ia: 0.8765 - loss: 0.0742 - mae: 0.1669 - rmse: 0.2446 - smape: 0.4068 - val_ia: 0.6509 - val_loss: 0.0570 - val_mae: 0.1421 - val_rmse: 0.1943 - val_smape: 0.3753

Epoch 23/128

1916/1916 - 12s - 6ms/step - ia: 0.8773 - loss: 0.0742 - mae: 0.1666 - rmse: 0.2448 - smape: 0.4050 - val_ia: 0.6992 - val_loss: 0.0552 - val_mae: 0.1293 - val_rmse: 0.1848 - val_smape: 0.3521

Epoch 24/128

1916/1916 - 12s - 7ms/step - ia: 0.8776 - loss: 0.0730 - mae: 0.1657 - rmse: 0.2432 - smape: 0.4056 - val_ia: 0.6855 - val_loss: 0.0551 - val_mae: 0.1322 - val_rmse: 0.1857 - val_smape: 0.3555

Epoch 25/128

1916/1916 - 12s - 7ms/step - ia: 0.8791 - loss: 0.0731 - mae: 0.1645 - rmse: 0.2427 - smape: 0.4025 - val_ia: 0.6874 - val_loss: 0.0556 - val_mae: 0.1326 - val_rmse: 0.1857 - val_smape: 0.3544

Epoch 26/128

1916/1916 - 16s - 8ms/step - ia: 0.8792 - loss: 0.0724 - mae: 0.1642 - rmse: 0.2418 - smape: 0.4010 - val_ia: 0.6755 - val_loss: 0.0555 - val_mae: 0.1345 - val_rmse: 0.1873 - val_smape: 0.3580

Epoch 27/128

1916/1916 - 16s - 9ms/step - ia: 0.8798 - loss: 0.0720 - mae: 0.1638 - rmse: 0.2404 - smape: 0.4015 - val_ia: 0.6991 - val_loss: 0.0549 - val_mae: 0.1296 - val_rmse: 0.1839 - val_smape: 0.3516

Epoch 28/128

1916/1916 - 20s - 10ms/step - ia: 0.8798 - loss: 0.0719 - mae: 0.1634 - rmse: 0.2398 - smape: 0.3992 - val_ia: 0.6838 - val_loss: 0.0549 - val_mae: 0.1324 - val_rmse: 0.1855 - val_smape: 0.3557

Epoch 29/128

1916/1916 - 14s - 7ms/step - ia: 0.8798 - loss: 0.0724 - mae: 0.1641 - rmse: 0.2411 - smape: 0.4002 - val_ia: 0.6759 - val_loss: 0.0556 - val_mae: 0.1348 - val_rmse: 0.1878 - val_smape: 0.3607

Epoch 30/128

1916/1916 - 12s - 7ms/step - ia: 0.8806 - loss: 0.0715 - mae: 0.1626 - rmse: 0.2394 - smape: 0.3996 - val_ia: 0.6741 - val_loss: 0.0567 - val_mae: 0.1369 - val_rmse: 0.1896 - val_smape: 0.3638

Epoch 31/128

1916/1916 - 21s - 11ms/step - ia: 0.8802 - loss: 0.0714 - mae: 0.1626 - rmse: 0.2406 - smape: 0.3982 - val_ia: 0.6984 - val_loss: 0.0550 - val_mae: 0.1304 - val_rmse: 0.1841 - val_smape: 0.3514

Epoch 32/128

1916/1916 - 13s - 7ms/step - ia: 0.8817 - loss: 0.0702 - mae: 0.1613 - rmse: 0.2382 - smape: 0.3971 - val_ia: 0.6840 - val_loss: 0.0561 - val_mae: 0.1342 - val_rmse: 0.1864 - val_smape: 0.3563

Epoch 33/128

1916/1916 - 13s - 7ms/step - ia: 0.8799 - loss: 0.0726 - mae: 0.1629 - rmse: 0.2412 - smape: 0.3998 - val_ia: 0.6887 - val_loss: 0.0550 - val_mae: 0.1314 - val_rmse: 0.1854 - val_smape: 0.3547

Epoch 34/128

1916/1916 - 12s - 6ms/step - ia: 0.8807 - loss: 0.0710 - mae: 0.1619 - rmse: 0.2390 - smape: 0.3976 - val_ia: 0.6919 - val_loss: 0.0553 - val_mae: 0.1317 - val_rmse: 0.1851 - val_smape: 0.3534

Epoch 35/128

1916/1916 - 12s - 6ms/step - ia: 0.8807 - loss: 0.0713 - mae: 0.1626 - rmse: 0.2395 - smape: 0.3979 - val_ia: 0.6870 - val_loss: 0.0549 - val_mae: 0.1320 - val_rmse: 0.1853 - val_smape: 0.3549

Epoch 36/128

1916/1916 - 16s - 8ms/step - ia: 0.8810 - loss: 0.0705 - mae: 0.1609 - rmse: 0.2379 - smape: 0.3940 - val_ia: 0.6902 - val_loss: 0.0546 - val_mae: 0.1312 - val_rmse: 0.1844 - val_smape: 0.3539

Epoch 37/128

1916/1916 - 15s - 8ms/step - ia: 0.8814 - loss: 0.0715 - mae: 0.1616 - rmse: 0.2390 - smape: 0.3985 - val_ia: 0.6823 - val_loss: 0.0547 - val_mae: 0.1328 - val_rmse: 0.1854 - val_smape: 0.3568

Epoch 38/128

1916/1916 - 14s - 7ms/step - ia: 0.8809 - loss: 0.0718 - mae: 0.1621 - rmse: 0.2403 - smape: 0.3980 - val_ia: 0.6734 - val_loss: 0.0559 - val_mae: 0.1360 - val_rmse: 0.1890 - val_smape: 0.3638

Epoch 39/128

1916/1916 - 21s - 11ms/step - ia: 0.8816 - loss: 0.0702 - mae: 0.1604 - rmse: 0.2375 - smape: 0.3927 - val_ia: 0.6668 - val_loss: 0.0560 - val_mae: 0.1380 - val_rmse: 0.1899 - val_smape: 0.3649

Epoch 40/128

1916/1916 - 16s - 8ms/step - ia: 0.8818 - loss: 0.0698 - mae: 0.1607 - rmse: 0.2374 - smape: 0.3960 - val_ia: 0.6945 - val_loss: 0.0558 - val_mae: 0.1322 - val_rmse: 0.1852 - val_smape: 0.3519

Epoch 41/128

1916/1916 - 15s - 8ms/step - ia: 0.8826 - loss: 0.0706 - mae: 0.1601 - rmse: 0.2378 - smape: 0.3925 - val_ia: 0.6941 - val_loss: 0.0544 - val_mae: 0.1299 - val_rmse: 0.1838 - val_smape: 0.3528

Epoch 42/128

1916/1916 - 15s - 8ms/step - ia: 0.8813 - loss: 0.0706 - mae: 0.1604 - rmse: 0.2372 - smape: 0.3950 - val_ia: 0.6860 - val_loss: 0.0549 - val_mae: 0.1318 - val_rmse: 0.1863 - val_smape: 0.3583

Epoch 43/128

1916/1916 - 15s - 8ms/step - ia: 0.8815 - loss: 0.0706 - mae: 0.1609 - rmse: 0.2381 - smape: 0.3947 - val_ia: 0.6856 - val_loss: 0.0544 - val_mae: 0.1318 - val_rmse: 0.1848 - val_smape: 0.3552

Epoch 44/128

1916/1916 - 20s - 10ms/step - ia: 0.8818 - loss: 0.0707 - mae: 0.1604 - rmse: 0.2383 - smape: 0.3935 - val_ia: 0.6993 - val_loss: 0.0554 - val_mae: 0.1312 - val_rmse: 0.1847 - val_smape: 0.3509

Epoch 45/128

1916/1916 - 16s - 9ms/step - ia: 0.8822 - loss: 0.0699 - mae: 0.1608 - rmse: 0.2370 - smape: 0.3951 - val_ia: 0.6937 - val_loss: 0.0545 - val_mae: 0.1303 - val_rmse: 0.1844 - val_smape: 0.3540

Epoch 46/128

1916/1916 - 15s - 8ms/step - ia: 0.8822 - loss: 0.0699 - mae: 0.1606 - rmse: 0.2371 - smape: 0.3939 - val_ia: 0.6765 - val_loss: 0.0562 - val_mae: 0.1360 - val_rmse: 0.1891 - val_smape: 0.3646

Epoch 47/128

1916/1916 - 21s - 11ms/step - ia: 0.8825 - loss: 0.0698 - mae: 0.1600 - rmse: 0.2369 - smape: 0.3929 - val_ia: 0.7046 - val_loss: 0.0542 - val_mae: 0.1282 - val_rmse: 0.1826 - val_smape: 0.3481

Epoch 48/128

1916/1916 - 20s - 11ms/step - ia: 0.8821 - loss: 0.0699 - mae: 0.1599 - rmse: 0.2369 - smape: 0.3934 - val_ia: 0.6817 - val_loss: 0.0563 - val_mae: 0.1351 - val_rmse: 0.1873 - val_smape: 0.3566

Epoch 49/128

1916/1916 - 17s - 9ms/step - ia: 0.8829 - loss: 0.0705 - mae: 0.1600 - rmse: 0.2375 - smape: 0.3922 - val_ia: 0.7010 - val_loss: 0.0542 - val_mae: 0.1287 - val_rmse: 0.1827 - val_smape: 0.3504

Epoch 50/128

1916/1916 - 10s - 5ms/step - ia: 0.8825 - loss: 0.0692 - mae: 0.1594 - rmse: 0.2358 - smape: 0.3927 - val_ia: 0.6965 - val_loss: 0.0541 - val_mae: 0.1294 - val_rmse: 0.1827 - val_smape: 0.3497

Epoch 51/128

1916/1916 - 10s - 5ms/step - ia: 0.8820 - loss: 0.0697 - mae: 0.1598 - rmse: 0.2360 - smape: 0.3922 - val_ia: 0.6796 - val_loss: 0.0553 - val_mae: 0.1344 - val_rmse: 0.1867 - val_smape: 0.3573

Epoch 52/128

1916/1916 - 9s - 5ms/step - ia: 0.8827 - loss: 0.0696 - mae: 0.1594 - rmse: 0.2362 - smape: 0.3925 - val_ia: 0.6576 - val_loss: 0.0564 - val_mae: 0.1407 - val_rmse: 0.1925 - val_smape: 0.3720

Epoch 53/128

1916/1916 - 14s - 7ms/step - ia: 0.8829 - loss: 0.0696 - mae: 0.1595 - rmse: 0.2358 - smape: 0.3923 - val_ia: 0.6851 - val_loss: 0.0544 - val_mae: 0.1319 - val_rmse: 0.1846 - val_smape: 0.3541

Epoch 54/128

1916/1916 - 15s - 8ms/step - ia: 0.8825 - loss: 0.0693 - mae: 0.1596 - rmse: 0.2363 - smape: 0.3936 - val_ia: 0.7015 - val_loss: 0.0545 - val_mae: 0.1300 - val_rmse: 0.1832 - val_smape: 0.3496

Epoch 55/128

1916/1916 - 14s - 8ms/step - ia: 0.8825 - loss: 0.0703 - mae: 0.1596 - rmse: 0.2369 - smape: 0.3927 - val_ia: 0.6699 - val_loss: 0.0560 - val_mae: 0.1376 - val_rmse: 0.1887 - val_smape: 0.3606

Epoch 56/128

1916/1916 - 21s - 11ms/step - ia: 0.8833 - loss: 0.0689 - mae: 0.1590 - rmse: 0.2357 - smape: 0.3909 - val_ia: 0.7017 - val_loss: 0.0538 - val_mae: 0.1284 - val_rmse: 0.1823 - val_smape: 0.3488

Epoch 57/128

1916/1916 - 15s - 8ms/step - ia: 0.8834 - loss: 0.0700 - mae: 0.1594 - rmse: 0.2360 - smape: 0.3908 - val_ia: 0.6864 - val_loss: 0.0545 - val_mae: 0.1318 - val_rmse: 0.1846 - val_smape: 0.3529

Epoch 58/128

1916/1916 - 19s - 10ms/step - ia: 0.8837 - loss: 0.0683 - mae: 0.1578 - rmse: 0.2343 - smape: 0.3895 - val_ia: 0.6917 - val_loss: 0.0546 - val_mae: 0.1315 - val_rmse: 0.1839 - val_smape: 0.3524

Epoch 59/128

1916/1916 - 21s - 11ms/step - ia: 0.8829 - loss: 0.0684 - mae: 0.1589 - rmse: 0.2348 - smape: 0.3916 - val_ia: 0.6728 - val_loss: 0.0549 - val_mae: 0.1346 - val_rmse: 0.1878 - val_smape: 0.3611

Epoch 60/128

1916/1916 - 14s - 7ms/step - ia: 0.8839 - loss: 0.0694 - mae: 0.1583 - rmse: 0.2355 - smape: 0.3886 - val_ia: 0.7044 - val_loss: 0.0538 - val_mae: 0.1277 - val_rmse: 0.1819 - val_smape: 0.3476

Epoch 61/128

1916/1916 - 21s - 11ms/step - ia: 0.8837 - loss: 0.0684 - mae: 0.1582 - rmse: 0.2343 - smape: 0.3894 - val_ia: 0.6963 - val_loss: 0.0540 - val_mae: 0.1290 - val_rmse: 0.1828 - val_smape: 0.3501

Epoch 62/128

1916/1916 - 15s - 8ms/step - ia: 0.8840 - loss: 0.0694 - mae: 0.1582 - rmse: 0.2356 - smape: 0.3891 - val_ia: 0.7021 - val_loss: 0.0540 - val_mae: 0.1287 - val_rmse: 0.1823 - val_smape: 0.3475

Epoch 63/128

1916/1916 - 14s - 7ms/step - ia: 0.8825 - loss: 0.0694 - mae: 0.1592 - rmse: 0.2361 - smape: 0.3911 - val_ia: 0.7042 - val_loss: 0.0539 - val_mae: 0.1282 - val_rmse: 0.1823 - val_smape: 0.3479

Epoch 64/128

1916/1916 - 21s - 11ms/step - ia: 0.8838 - loss: 0.0686 - mae: 0.1580 - rmse: 0.2345 - smape: 0.3896 - val_ia: 0.6832 - val_loss: 0.0546 - val_mae: 0.1328 - val_rmse: 0.1853 - val_smape: 0.3557

Epoch 65/128

1916/1916 - 15s - 8ms/step - ia: 0.8841 - loss: 0.0680 - mae: 0.1575 - rmse: 0.2330 - smape: 0.3879 - val_ia: 0.7029 - val_loss: 0.0543 - val_mae: 0.1291 - val_rmse: 0.1835 - val_smape: 0.3492

Epoch 66/128

1916/1916 - 11s - 6ms/step - ia: 0.8837 - loss: 0.0686 - mae: 0.1584 - rmse: 0.2348 - smape: 0.3900 - val_ia: 0.6977 - val_loss: 0.0537 - val_mae: 0.1291 - val_rmse: 0.1819 - val_smape: 0.3482

Epoch 67/128

1916/1916 - 10s - 5ms/step - ia: 0.8838 - loss: 0.0687 - mae: 0.1580 - rmse: 0.2354 - smape: 0.3877 - val_ia: 0.6881 - val_loss: 0.0538 - val_mae: 0.1306 - val_rmse: 0.1836 - val_smape: 0.3528

Epoch 68/128

1916/1916 - 9s - 5ms/step - ia: 0.8839 - loss: 0.0688 - mae: 0.1576 - rmse: 0.2349 - smape: 0.3880 - val_ia: 0.6945 - val_loss: 0.0543 - val_mae: 0.1302 - val_rmse: 0.1831 - val_smape: 0.3487

Epoch 69/128

1916/1916 - 10s - 5ms/step - ia: 0.8845 - loss: 0.0691 - mae: 0.1582 - rmse: 0.2353 - smape: 0.3882 - val_ia: 0.7046 - val_loss: 0.0541 - val_mae: 0.1280 - val_rmse: 0.1827 - val_smape: 0.3480

Epoch 70/128

1916/1916 - 14s - 7ms/step - ia: 0.8837 - loss: 0.0684 - mae: 0.1581 - rmse: 0.2338 - smape: 0.3896 - val_ia: 0.7004 - val_loss: 0.0536 - val_mae: 0.1283 - val_rmse: 0.1822 - val_smape: 0.3495

Epoch 71/128

1916/1916 - 15s - 8ms/step - ia: 0.8839 - loss: 0.0683 - mae: 0.1579 - rmse: 0.2340 - smape: 0.3912 - val_ia: 0.6971 - val_loss: 0.0545 - val_mae: 0.1303 - val_rmse: 0.1831 - val_smape: 0.3501

Epoch 72/128

1916/1916 - 15s - 8ms/step - ia: 0.8843 - loss: 0.0675 - mae: 0.1571 - rmse: 0.2319 - smape: 0.3896 - val_ia: 0.7033 - val_loss: 0.0537 - val_mae: 0.1284 - val_rmse: 0.1821 - val_smape: 0.3477

Epoch 73/128

1916/1916 - 15s - 8ms/step - ia: 0.8847 - loss: 0.0679 - mae: 0.1569 - rmse: 0.2326 - smape: 0.3868 - val_ia: 0.7024 - val_loss: 0.0536 - val_mae: 0.1278 - val_rmse: 0.1820 - val_smape: 0.3478

Epoch 74/128

1916/1916 - 10s - 5ms/step - ia: 0.8846 - loss: 0.0682 - mae: 0.1580 - rmse: 0.2342 - smape: 0.3894 - val_ia: 0.6804 - val_loss: 0.0543 - val_mae: 0.1326 - val_rmse: 0.1856 - val_smape: 0.3568

Epoch 75/128

1916/1916 - 10s - 5ms/step - ia: 0.8846 - loss: 0.0677 - mae: 0.1572 - rmse: 0.2331 - smape: 0.3867 - val_ia: 0.6984 - val_loss: 0.0538 - val_mae: 0.1291 - val_rmse: 0.1824 - val_smape: 0.3491

Epoch 76/128

1916/1916 - 12s - 6ms/step - ia: 0.8835 - loss: 0.0681 - mae: 0.1576 - rmse: 0.2343 - smape: 0.3888 - val_ia: 0.7053 - val_loss: 0.0536 - val_mae: 0.1280 - val_rmse: 0.1817 - val_smape: 0.3461

Epoch 77/128

1916/1916 - 23s - 12ms/step - ia: 0.8850 - loss: 0.0675 - mae: 0.1571 - rmse: 0.2334 - smape: 0.3856 - val_ia: 0.6964 - val_loss: 0.0535 - val_mae: 0.1288 - val_rmse: 0.1822 - val_smape: 0.3498

Epoch 78/128

1916/1916 - 14s - 7ms/step - ia: 0.8849 - loss: 0.0676 - mae: 0.1568 - rmse: 0.2329 - smape: 0.3874 - val_ia: 0.6906 - val_loss: 0.0544 - val_mae: 0.1314 - val_rmse: 0.1837 - val_smape: 0.3517

Epoch 79/128

1916/1916 - 15s - 8ms/step - ia: 0.8848 - loss: 0.0671 - mae: 0.1570 - rmse: 0.2334 - smape: 0.3886 - val_ia: 0.6779 - val_loss: 0.0543 - val_mae: 0.1339 - val_rmse: 0.1863 - val_smape: 0.3593

Epoch 80/128

1916/1916 - 15s - 8ms/step - ia: 0.8844 - loss: 0.0679 - mae: 0.1572 - rmse: 0.2335 - smape: 0.3866 - val_ia: 0.6946 - val_loss: 0.0533 - val_mae: 0.1288 - val_rmse: 0.1819 - val_smape: 0.3493

Epoch 81/128

1916/1916 - 14s - 7ms/step - ia: 0.8843 - loss: 0.0681 - mae: 0.1572 - rmse: 0.2330 - smape: 0.3891 - val_ia: 0.6979 - val_loss: 0.0536 - val_mae: 0.1286 - val_rmse: 0.1821 - val_smape: 0.3481

Epoch 82/128

1916/1916 - 14s - 8ms/step - ia: 0.8842 - loss: 0.0675 - mae: 0.1569 - rmse: 0.2327 - smape: 0.3869 - val_ia: 0.6844 - val_loss: 0.0536 - val_mae: 0.1313 - val_rmse: 0.1838 - val_smape: 0.3541

Epoch 83/128

1916/1916 - 15s - 8ms/step - ia: 0.8847 - loss: 0.0672 - mae: 0.1567 - rmse: 0.2320 - smape: 0.3871 - val_ia: 0.6835 - val_loss: 0.0539 - val_mae: 0.1317 - val_rmse: 0.1849 - val_smape: 0.3542

Epoch 84/128

1916/1916 - 20s - 11ms/step - ia: 0.8850 - loss: 0.0673 - mae: 0.1564 - rmse: 0.2330 - smape: 0.3857 - val_ia: 0.6996 - val_loss: 0.0533 - val_mae: 0.1283 - val_rmse: 0.1815 - val_smape: 0.3479

Epoch 85/128

1916/1916 - 15s - 8ms/step - ia: 0.8848 - loss: 0.0672 - mae: 0.1568 - rmse: 0.2330 - smape: 0.3870 - val_ia: 0.6833 - val_loss: 0.0539 - val_mae: 0.1320 - val_rmse: 0.1843 - val_smape: 0.3529

Epoch 86/128

1916/1916 - 15s - 8ms/step - ia: 0.8847 - loss: 0.0672 - mae: 0.1565 - rmse: 0.2321 - smape: 0.3850 - val_ia: 0.7016 - val_loss: 0.0533 - val_mae: 0.1277 - val_rmse: 0.1811 - val_smape: 0.3453

Epoch 87/128

1916/1916 - 14s - 7ms/step - ia: 0.8854 - loss: 0.0666 - mae: 0.1562 - rmse: 0.2314 - smape: 0.3854 - val_ia: 0.6872 - val_loss: 0.0539 - val_mae: 0.1312 - val_rmse: 0.1843 - val_smape: 0.3537

Epoch 88/128

1916/1916 - 15s - 8ms/step - ia: 0.8851 - loss: 0.0657 - mae: 0.1556 - rmse: 0.2303 - smape: 0.3835 - val_ia: 0.7038 - val_loss: 0.0532 - val_mae: 0.1276 - val_rmse: 0.1812 - val_smape: 0.3464

Epoch 89/128

1916/1916 - 15s - 8ms/step - ia: 0.8850 - loss: 0.0671 - mae: 0.1565 - rmse: 0.2320 - smape: 0.3856 - val_ia: 0.7040 - val_loss: 0.0533 - val_mae: 0.1281 - val_rmse: 0.1811 - val_smape: 0.3463

Epoch 90/128

1916/1916 - 15s - 8ms/step - ia: 0.8851 - loss: 0.0669 - mae: 0.1568 - rmse: 0.2329 - smape: 0.3857 - val_ia: 0.6957 - val_loss: 0.0532 - val_mae: 0.1292 - val_rmse: 0.1816 - val_smape: 0.3494

Epoch 91/128

1916/1916 - 15s - 8ms/step - ia: 0.8852 - loss: 0.0670 - mae: 0.1566 - rmse: 0.2323 - smape: 0.3864 - val_ia: 0.6851 - val_loss: 0.0536 - val_mae: 0.1309 - val_rmse: 0.1840 - val_smape: 0.3525

Epoch 92/128

1916/1916 - 15s - 8ms/step - ia: 0.8850 - loss: 0.0669 - mae: 0.1570 - rmse: 0.2323 - smape: 0.3874 - val_ia: 0.6957 - val_loss: 0.0531 - val_mae: 0.1288 - val_rmse: 0.1817 - val_smape: 0.3488

Epoch 93/128

1916/1916 - 15s - 8ms/step - ia: 0.8849 - loss: 0.0666 - mae: 0.1566 - rmse: 0.2314 - smape: 0.3876 - val_ia: 0.6935 - val_loss: 0.0534 - val_mae: 0.1295 - val_rmse: 0.1822 - val_smape: 0.3491

Epoch 94/128

1916/1916 - 14s - 7ms/step - ia: 0.8855 - loss: 0.0667 - mae: 0.1567 - rmse: 0.2326 - smape: 0.3878 - val_ia: 0.7056 - val_loss: 0.0530 - val_mae: 0.1273 - val_rmse: 0.1807 - val_smape: 0.3459

Epoch 95/128

1916/1916 - 21s - 11ms/step - ia: 0.8853 - loss: 0.0666 - mae: 0.1562 - rmse: 0.2308 - smape: 0.3864 - val_ia: 0.6838 - val_loss: 0.0541 - val_mae: 0.1323 - val_rmse: 0.1850 - val_smape: 0.3545

Epoch 96/128

1916/1916 - 20s - 10ms/step - ia: 0.8857 - loss: 0.0668 - mae: 0.1562 - rmse: 0.2319 - smape: 0.3869 - val_ia: 0.6983 - val_loss: 0.0539 - val_mae: 0.1295 - val_rmse: 0.1840 - val_smape: 0.3538

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 16s - 17ms/step - ia: 0.6448 - loss: 0.3926 - mae: 0.4412 - rmse: 0.5896 - smape: 0.8980 - val_ia: 0.6097 - val_loss: 0.1274 - val_mae: 0.2354 - val_rmse: 0.3101 - val_smape: 0.5732

Epoch 2/128

958/958 - 9s - 9ms/step - ia: 0.7880 - loss: 0.1761 - mae: 0.2943 - rmse: 0.4059 - smape: 0.6455 - val_ia: 0.6744 - val_loss: 0.0959 - val_mae: 0.1943 - val_rmse: 0.2650 - val_smape: 0.4816

Epoch 3/128

958/958 - 9s - 9ms/step - ia: 0.8122 - loss: 0.1428 - mae: 0.2599 - rmse: 0.3631 - smape: 0.5885 - val_ia: 0.7160 - val_loss: 0.0816 - val_mae: 0.1720 - val_rmse: 0.2426 - val_smape: 0.4389

Epoch 4/128

958/958 - 8s - 8ms/step - ia: 0.8285 - loss: 0.1232 - mae: 0.2385 - rmse: 0.3364 - smape: 0.5522 - val_ia: 0.7201 - val_loss: 0.0747 - val_mae: 0.1652 - val_rmse: 0.2337 - val_smape: 0.4239

Epoch 5/128

958/958 - 9s - 9ms/step - ia: 0.8408 - loss: 0.1106 - mae: 0.2221 - rmse: 0.3169 - smape: 0.5194 - val_ia: 0.7352 - val_loss: 0.0695 - val_mae: 0.1563 - val_rmse: 0.2248 - val_smape: 0.4074

Epoch 6/128

958/958 - 9s - 9ms/step - ia: 0.8483 - loss: 0.1016 - mae: 0.2120 - rmse: 0.3038 - smape: 0.5036 - val_ia: 0.7379 - val_loss: 0.0682 - val_mae: 0.1559 - val_rmse: 0.2211 - val_smape: 0.4066

Epoch 7/128

958/958 - 10s - 11ms/step - ia: 0.8534 - loss: 0.0981 - mae: 0.2053 - rmse: 0.2969 - smape: 0.4872 - val_ia: 0.7555 - val_loss: 0.0640 - val_mae: 0.1463 - val_rmse: 0.2145 - val_smape: 0.3874

Epoch 8/128

958/958 - 9s - 9ms/step - ia: 0.8590 - loss: 0.0937 - mae: 0.1982 - rmse: 0.2899 - smape: 0.4727 - val_ia: 0.7619 - val_loss: 0.0624 - val_mae: 0.1437 - val_rmse: 0.2109 - val_smape: 0.3851

Epoch 9/128

958/958 - 8s - 9ms/step - ia: 0.8633 - loss: 0.0881 - mae: 0.1920 - rmse: 0.2806 - smape: 0.4638 - val_ia: 0.7363 - val_loss: 0.0643 - val_mae: 0.1531 - val_rmse: 0.2156 - val_smape: 0.3924

Epoch 10/128

958/958 - 8s - 9ms/step - ia: 0.8656 - loss: 0.0855 - mae: 0.1892 - rmse: 0.2772 - smape: 0.4575 - val_ia: 0.7611 - val_loss: 0.0597 - val_mae: 0.1407 - val_rmse: 0.2063 - val_smape: 0.3751

Epoch 11/128

958/958 - 9s - 9ms/step - ia: 0.8690 - loss: 0.0840 - mae: 0.1850 - rmse: 0.2731 - smape: 0.4464 - val_ia: 0.7593 - val_loss: 0.0605 - val_mae: 0.1431 - val_rmse: 0.2066 - val_smape: 0.3782

Epoch 12/128

958/958 - 9s - 9ms/step - ia: 0.8704 - loss: 0.0826 - mae: 0.1828 - rmse: 0.2714 - smape: 0.4406 - val_ia: 0.7765 - val_loss: 0.0585 - val_mae: 0.1364 - val_rmse: 0.2034 - val_smape: 0.3699

Epoch 13/128

958/958 - 10s - 11ms/step - ia: 0.8714 - loss: 0.0818 - mae: 0.1814 - rmse: 0.2691 - smape: 0.4390 - val_ia: 0.7650 - val_loss: 0.0577 - val_mae: 0.1375 - val_rmse: 0.2029 - val_smape: 0.3677

Epoch 14/128

958/958 - 8s - 9ms/step - ia: 0.8742 - loss: 0.0798 - mae: 0.1781 - rmse: 0.2649 - smape: 0.4326 - val_ia: 0.7565 - val_loss: 0.0588 - val_mae: 0.1420 - val_rmse: 0.2043 - val_smape: 0.3726

Epoch 15/128

958/958 - 10s - 11ms/step - ia: 0.8745 - loss: 0.0788 - mae: 0.1772 - rmse: 0.2639 - smape: 0.4310 - val_ia: 0.7559 - val_loss: 0.0581 - val_mae: 0.1406 - val_rmse: 0.2043 - val_smape: 0.3695

Epoch 16/128

958/958 - 10s - 11ms/step - ia: 0.8755 - loss: 0.0789 - mae: 0.1760 - rmse: 0.2630 - smape: 0.4285 - val_ia: 0.7629 - val_loss: 0.0579 - val_mae: 0.1387 - val_rmse: 0.2037 - val_smape: 0.3678

Epoch 17/128

958/958 - 9s - 9ms/step - ia: 0.8771 - loss: 0.0778 - mae: 0.1735 - rmse: 0.2614 - smape: 0.4209 - val_ia: 0.7504 - val_loss: 0.0579 - val_mae: 0.1423 - val_rmse: 0.2046 - val_smape: 0.3704

Epoch 18/128

958/958 - 9s - 9ms/step - ia: 0.8772 - loss: 0.0775 - mae: 0.1734 - rmse: 0.2610 - smape: 0.4218 - val_ia: 0.7653 - val_loss: 0.0568 - val_mae: 0.1361 - val_rmse: 0.2011 - val_smape: 0.3622

Epoch 19/128

958/958 - 10s - 10ms/step - ia: 0.8791 - loss: 0.0755 - mae: 0.1707 - rmse: 0.2578 - smape: 0.4169 - val_ia: 0.7671 - val_loss: 0.0566 - val_mae: 0.1359 - val_rmse: 0.2003 - val_smape: 0.3605

Epoch 20/128

958/958 - 11s - 11ms/step - ia: 0.8792 - loss: 0.0756 - mae: 0.1708 - rmse: 0.2571 - smape: 0.4155 - val_ia: 0.7820 - val_loss: 0.0562 - val_mae: 0.1323 - val_rmse: 0.1979 - val_smape: 0.3588

Epoch 21/128

958/958 - 9s - 9ms/step - ia: 0.8794 - loss: 0.0754 - mae: 0.1702 - rmse: 0.2583 - smape: 0.4155 - val_ia: 0.7504 - val_loss: 0.0573 - val_mae: 0.1414 - val_rmse: 0.2047 - val_smape: 0.3738

Epoch 22/128

958/958 - 9s - 9ms/step - ia: 0.8805 - loss: 0.0748 - mae: 0.1690 - rmse: 0.2562 - smape: 0.4106 - val_ia: 0.7702 - val_loss: 0.0560 - val_mae: 0.1345 - val_rmse: 0.1989 - val_smape: 0.3598

Epoch 23/128

958/958 - 10s - 11ms/step - ia: 0.8805 - loss: 0.0754 - mae: 0.1688 - rmse: 0.2561 - smape: 0.4117 - val_ia: 0.7764 - val_loss: 0.0558 - val_mae: 0.1328 - val_rmse: 0.1979 - val_smape: 0.3567

Epoch 24/128

958/958 - 8s - 8ms/step - ia: 0.8811 - loss: 0.0737 - mae: 0.1676 - rmse: 0.2540 - smape: 0.4093 - val_ia: 0.7807 - val_loss: 0.0555 - val_mae: 0.1314 - val_rmse: 0.1970 - val_smape: 0.3549

Epoch 25/128

958/958 - 7s - 7ms/step - ia: 0.8822 - loss: 0.0737 - mae: 0.1668 - rmse: 0.2543 - smape: 0.4052 - val_ia: 0.7800 - val_loss: 0.0562 - val_mae: 0.1328 - val_rmse: 0.1978 - val_smape: 0.3548

Epoch 26/128

958/958 - 7s - 7ms/step - ia: 0.8821 - loss: 0.0741 - mae: 0.1670 - rmse: 0.2545 - smape: 0.4079 - val_ia: 0.7685 - val_loss: 0.0568 - val_mae: 0.1364 - val_rmse: 0.1999 - val_smape: 0.3591

Epoch 27/128

958/958 - 7s - 7ms/step - ia: 0.8823 - loss: 0.0738 - mae: 0.1664 - rmse: 0.2539 - smape: 0.4073 - val_ia: 0.7845 - val_loss: 0.0560 - val_mae: 0.1319 - val_rmse: 0.1974 - val_smape: 0.3546

Epoch 28/128

958/958 - 11s - 11ms/step - ia: 0.8834 - loss: 0.0730 - mae: 0.1652 - rmse: 0.2530 - smape: 0.4015 - val_ia: 0.7616 - val_loss: 0.0559 - val_mae: 0.1370 - val_rmse: 0.2000 - val_smape: 0.3628

Epoch 29/128

958/958 - 10s - 10ms/step - ia: 0.8839 - loss: 0.0720 - mae: 0.1645 - rmse: 0.2516 - smape: 0.4017 - val_ia: 0.7769 - val_loss: 0.0555 - val_mae: 0.1321 - val_rmse: 0.1979 - val_smape: 0.3551

Epoch 30/128

958/958 - 10s - 10ms/step - ia: 0.8837 - loss: 0.0719 - mae: 0.1640 - rmse: 0.2509 - smape: 0.4030 - val_ia: 0.7857 - val_loss: 0.0555 - val_mae: 0.1308 - val_rmse: 0.1968 - val_smape: 0.3522

Epoch 31/128

958/958 - 8s - 9ms/step - ia: 0.8835 - loss: 0.0731 - mae: 0.1645 - rmse: 0.2518 - smape: 0.4020 - val_ia: 0.7809 - val_loss: 0.0553 - val_mae: 0.1317 - val_rmse: 0.1964 - val_smape: 0.3539

Epoch 32/128

958/958 - 8s - 9ms/step - ia: 0.8842 - loss: 0.0720 - mae: 0.1639 - rmse: 0.2513 - smape: 0.4009 - val_ia: 0.7819 - val_loss: 0.0556 - val_mae: 0.1322 - val_rmse: 0.1966 - val_smape: 0.3534

Epoch 33/128

958/958 - 8s - 9ms/step - ia: 0.8846 - loss: 0.0724 - mae: 0.1631 - rmse: 0.2510 - smape: 0.3994 - val_ia: 0.7777 - val_loss: 0.0575 - val_mae: 0.1359 - val_rmse: 0.1991 - val_smape: 0.3581

Epoch 34/128

958/958 - 9s - 10ms/step - ia: 0.8844 - loss: 0.0719 - mae: 0.1636 - rmse: 0.2505 - smape: 0.3998 - val_ia: 0.7783 - val_loss: 0.0546 - val_mae: 0.1309 - val_rmse: 0.1959 - val_smape: 0.3529

Epoch 35/128

958/958 - 8s - 8ms/step - ia: 0.8842 - loss: 0.0730 - mae: 0.1640 - rmse: 0.2511 - smape: 0.3991 - val_ia: 0.7601 - val_loss: 0.0557 - val_mae: 0.1375 - val_rmse: 0.1998 - val_smape: 0.3624

Epoch 36/128

958/958 - 8s - 8ms/step - ia: 0.8849 - loss: 0.0719 - mae: 0.1629 - rmse: 0.2490 - smape: 0.3995 - val_ia: 0.7753 - val_loss: 0.0548 - val_mae: 0.1324 - val_rmse: 0.1966 - val_smape: 0.3549

Epoch 37/128

958/958 - 8s - 8ms/step - ia: 0.8854 - loss: 0.0713 - mae: 0.1620 - rmse: 0.2494 - smape: 0.3967 - val_ia: 0.7802 - val_loss: 0.0546 - val_mae: 0.1307 - val_rmse: 0.1958 - val_smape: 0.3527

Epoch 38/128

958/958 - 10s - 11ms/step - ia: 0.8853 - loss: 0.0714 - mae: 0.1625 - rmse: 0.2496 - smape: 0.3968 - val_ia: 0.7850 - val_loss: 0.0553 - val_mae: 0.1312 - val_rmse: 0.1965 - val_smape: 0.3516

Epoch 39/128

958/958 - 8s - 8ms/step - ia: 0.8857 - loss: 0.0706 - mae: 0.1615 - rmse: 0.2485 - smape: 0.3975 - val_ia: 0.7480 - val_loss: 0.0563 - val_mae: 0.1418 - val_rmse: 0.2037 - val_smape: 0.3744

Epoch 40/128

958/958 - 8s - 8ms/step - ia: 0.8857 - loss: 0.0715 - mae: 0.1618 - rmse: 0.2494 - smape: 0.3952 - val_ia: 0.7701 - val_loss: 0.0554 - val_mae: 0.1349 - val_rmse: 0.1978 - val_smape: 0.3575

Epoch 41/128

958/958 - 7s - 8ms/step - ia: 0.8858 - loss: 0.0708 - mae: 0.1613 - rmse: 0.2491 - smape: 0.3954 - val_ia: 0.7797 - val_loss: 0.0555 - val_mae: 0.1329 - val_rmse: 0.1965 - val_smape: 0.3537

Epoch 42/128

958/958 - 8s - 8ms/step - ia: 0.8854 - loss: 0.0713 - mae: 0.1620 - rmse: 0.2496 - smape: 0.3956 - val_ia: 0.7880 - val_loss: 0.0546 - val_mae: 0.1294 - val_rmse: 0.1955 - val_smape: 0.3514

Epoch 43/128

958/958 - 8s - 8ms/step - ia: 0.8859 - loss: 0.0705 - mae: 0.1611 - rmse: 0.2478 - smape: 0.3967 - val_ia: 0.7561 - val_loss: 0.0557 - val_mae: 0.1389 - val_rmse: 0.2001 - val_smape: 0.3640

Epoch 44/128

958/958 - 7s - 8ms/step - ia: 0.8870 - loss: 0.0705 - mae: 0.1608 - rmse: 0.2484 - smape: 0.3955 - val_ia: 0.7858 - val_loss: 0.0544 - val_mae: 0.1299 - val_rmse: 0.1949 - val_smape: 0.3502

Epoch 45/128

958/958 - 8s - 8ms/step - ia: 0.8858 - loss: 0.0709 - mae: 0.1614 - rmse: 0.2485 - smape: 0.3960 - val_ia: 0.7870 - val_loss: 0.0544 - val_mae: 0.1294 - val_rmse: 0.1951 - val_smape: 0.3496

Epoch 46/128

958/958 - 8s - 8ms/step - ia: 0.8872 - loss: 0.0700 - mae: 0.1601 - rmse: 0.2478 - smape: 0.3932 - val_ia: 0.7664 - val_loss: 0.0549 - val_mae: 0.1353 - val_rmse: 0.1978 - val_smape: 0.3591

Epoch 47/128

958/958 - 8s - 8ms/step - ia: 0.8866 - loss: 0.0711 - mae: 0.1608 - rmse: 0.2478 - smape: 0.3945 - val_ia: 0.7846 - val_loss: 0.0544 - val_mae: 0.1299 - val_rmse: 0.1952 - val_smape: 0.3511

Epoch 48/128

958/958 - 8s - 8ms/step - ia: 0.8870 - loss: 0.0701 - mae: 0.1599 - rmse: 0.2466 - smape: 0.3922 - val_ia: 0.7719 - val_loss: 0.0548 - val_mae: 0.1336 - val_rmse: 0.1972 - val_smape: 0.3576

Epoch 49/128

958/958 - 7s - 8ms/step - ia: 0.8870 - loss: 0.0705 - mae: 0.1603 - rmse: 0.2472 - smape: 0.3935 - val_ia: 0.7701 - val_loss: 0.0550 - val_mae: 0.1347 - val_rmse: 0.1974 - val_smape: 0.3570

Epoch 50/128

958/958 - 8s - 8ms/step - ia: 0.8877 - loss: 0.0698 - mae: 0.1594 - rmse: 0.2457 - smape: 0.3907 - val_ia: 0.7892 - val_loss: 0.0544 - val_mae: 0.1290 - val_rmse: 0.1946 - val_smape: 0.3496

Epoch 51/128

958/958 - 8s - 8ms/step - ia: 0.8873 - loss: 0.0701 - mae: 0.1600 - rmse: 0.2465 - smape: 0.3920 - val_ia: 0.7794 - val_loss: 0.0549 - val_mae: 0.1321 - val_rmse: 0.1958 - val_smape: 0.3540

Epoch 52/128

958/958 - 10s - 11ms/step - ia: 0.8872 - loss: 0.0701 - mae: 0.1600 - rmse: 0.2465 - smape: 0.3924 - val_ia: 0.7816 - val_loss: 0.0549 - val_mae: 0.1314 - val_rmse: 0.1958 - val_smape: 0.3512

Epoch 53/128

958/958 - 10s - 11ms/step - ia: 0.8864 - loss: 0.0706 - mae: 0.1603 - rmse: 0.2475 - smape: 0.3938 - val_ia: 0.7706 - val_loss: 0.0548 - val_mae: 0.1336 - val_rmse: 0.1981 - val_smape: 0.3598

Epoch 54/128

958/958 - 10s - 11ms/step - ia: 0.8878 - loss: 0.0693 - mae: 0.1596 - rmse: 0.2463 - smape: 0.3921 - val_ia: 0.7648 - val_loss: 0.0548 - val_mae: 0.1353 - val_rmse: 0.1984 - val_smape: 0.3607

Epoch 55/128

958/958 - 8s - 8ms/step - ia: 0.8875 - loss: 0.0697 - mae: 0.1599 - rmse: 0.2460 - smape: 0.3934 - val_ia: 0.7866 - val_loss: 0.0550 - val_mae: 0.1308 - val_rmse: 0.1951 - val_smape: 0.3501

Epoch 56/128

958/958 - 10s - 11ms/step - ia: 0.8877 - loss: 0.0695 - mae: 0.1589 - rmse: 0.2455 - smape: 0.3931 - val_ia: 0.7731 - val_loss: 0.0553 - val_mae: 0.1339 - val_rmse: 0.1975 - val_smape: 0.3559

Epoch 57/128

958/958 - 10s - 11ms/step - ia: 0.8875 - loss: 0.0700 - mae: 0.1594 - rmse: 0.2465 - smape: 0.3906 - val_ia: 0.7752 - val_loss: 0.0548 - val_mae: 0.1331 - val_rmse: 0.1960 - val_smape: 0.3546

Epoch 58/128

958/958 - 10s - 11ms/step - ia: 0.8867 - loss: 0.0702 - mae: 0.1603 - rmse: 0.2475 - smape: 0.3935 - val_ia: 0.7693 - val_loss: 0.0546 - val_mae: 0.1343 - val_rmse: 0.1969 - val_smape: 0.3574

Epoch 59/128

958/958 - 8s - 8ms/step - ia: 0.8874 - loss: 0.0704 - mae: 0.1595 - rmse: 0.2461 - smape: 0.3905 - val_ia: 0.7652 - val_loss: 0.0547 - val_mae: 0.1353 - val_rmse: 0.1983 - val_smape: 0.3604

Epoch 59: early stopping

Restoring model weights from the end of the best epoch: 44.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:35 707ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 52%|█████▏    | 26/50 [11:20:31<21:24:49, 3212.08s/trial, best loss: 0.03705484021205277]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 18s - 9ms/step - ia: 0.4466 - loss: 0.7512 - mae: 0.6249 - rmse: 0.8192 - smape: 1.2071 - val_ia: 0.3809 - val_loss: 0.2811 - val_mae: 0.3700 - val_rmse: 0.4262 - val_smape: 0.8055

Epoch 2/128

1916/1916 - 12s - 6ms/step - ia: 0.6993 - loss: 0.2970 - mae: 0.3982 - rmse: 0.5216 - smape: 0.8037 - val_ia: 0.5001 - val_loss: 0.1374 - val_mae: 0.2374 - val_rmse: 0.2970 - val_smape: 0.5543

Epoch 3/128

1916/1916 - 13s - 7ms/step - ia: 0.7491 - loss: 0.2195 - mae: 0.3375 - rmse: 0.4473 - smape: 0.7063 - val_ia: 0.5343 - val_loss: 0.1169 - val_mae: 0.2136 - val_rmse: 0.2730 - val_smape: 0.5134

Epoch 4/128

1916/1916 - 12s - 6ms/step - ia: 0.7729 - loss: 0.1868 - mae: 0.3053 - rmse: 0.4105 - smape: 0.6584 - val_ia: 0.5585 - val_loss: 0.1029 - val_mae: 0.1979 - val_rmse: 0.2564 - val_smape: 0.4856

Epoch 5/128

1916/1916 - 12s - 6ms/step - ia: 0.7886 - loss: 0.1641 - mae: 0.2831 - rmse: 0.3819 - smape: 0.6266 - val_ia: 0.5777 - val_loss: 0.0936 - val_mae: 0.1864 - val_rmse: 0.2442 - val_smape: 0.4629

Epoch 6/128

1916/1916 - 20s - 11ms/step - ia: 0.8006 - loss: 0.1477 - mae: 0.2669 - rmse: 0.3615 - smape: 0.5997 - val_ia: 0.6003 - val_loss: 0.0873 - val_mae: 0.1774 - val_rmse: 0.2348 - val_smape: 0.4446

Epoch 7/128

1916/1916 - 13s - 7ms/step - ia: 0.8103 - loss: 0.1368 - mae: 0.2537 - rmse: 0.3462 - smape: 0.5753 - val_ia: 0.6139 - val_loss: 0.0820 - val_mae: 0.1706 - val_rmse: 0.2275 - val_smape: 0.4322

Epoch 8/128

1916/1916 - 12s - 6ms/step - ia: 0.8177 - loss: 0.1274 - mae: 0.2443 - rmse: 0.3345 - smape: 0.5601 - val_ia: 0.6096 - val_loss: 0.0779 - val_mae: 0.1677 - val_rmse: 0.2238 - val_smape: 0.4259

Epoch 9/128

1916/1916 - 12s - 6ms/step - ia: 0.8229 - loss: 0.1221 - mae: 0.2361 - rmse: 0.3255 - smape: 0.5443 - val_ia: 0.6332 - val_loss: 0.0748 - val_mae: 0.1607 - val_rmse: 0.2169 - val_smape: 0.4142

Epoch 10/128

1916/1916 - 12s - 6ms/step - ia: 0.8295 - loss: 0.1157 - mae: 0.2295 - rmse: 0.3163 - smape: 0.5336 - val_ia: 0.6271 - val_loss: 0.0718 - val_mae: 0.1589 - val_rmse: 0.2147 - val_smape: 0.4088

Epoch 11/128

1916/1916 - 12s - 6ms/step - ia: 0.8338 - loss: 0.1119 - mae: 0.2240 - rmse: 0.3102 - smape: 0.5213 - val_ia: 0.6213 - val_loss: 0.0709 - val_mae: 0.1602 - val_rmse: 0.2145 - val_smape: 0.4084

Epoch 12/128

1916/1916 - 12s - 6ms/step - ia: 0.8374 - loss: 0.1075 - mae: 0.2180 - rmse: 0.3035 - smape: 0.5128 - val_ia: 0.6438 - val_loss: 0.0682 - val_mae: 0.1522 - val_rmse: 0.2081 - val_smape: 0.3969

Epoch 13/128

1916/1916 - 20s - 11ms/step - ia: 0.8405 - loss: 0.1048 - mae: 0.2150 - rmse: 0.2997 - smape: 0.5061 - val_ia: 0.6315 - val_loss: 0.0674 - val_mae: 0.1546 - val_rmse: 0.2096 - val_smape: 0.3989

Epoch 14/128

1916/1916 - 13s - 7ms/step - ia: 0.8436 - loss: 0.1010 - mae: 0.2099 - rmse: 0.2933 - smape: 0.4964 - val_ia: 0.6352 - val_loss: 0.0663 - val_mae: 0.1528 - val_rmse: 0.2075 - val_smape: 0.3950

Epoch 15/128

1916/1916 - 20s - 11ms/step - ia: 0.8460 - loss: 0.1008 - mae: 0.2073 - rmse: 0.2915 - smape: 0.4905 - val_ia: 0.6428 - val_loss: 0.0649 - val_mae: 0.1499 - val_rmse: 0.2044 - val_smape: 0.3899

Epoch 16/128

1916/1916 - 21s - 11ms/step - ia: 0.8470 - loss: 0.0985 - mae: 0.2052 - rmse: 0.2883 - smape: 0.4866 - val_ia: 0.6509 - val_loss: 0.0643 - val_mae: 0.1475 - val_rmse: 0.2026 - val_smape: 0.3871

Epoch 17/128

1916/1916 - 12s - 6ms/step - ia: 0.8502 - loss: 0.0958 - mae: 0.2019 - rmse: 0.2849 - smape: 0.4774 - val_ia: 0.6482 - val_loss: 0.0635 - val_mae: 0.1475 - val_rmse: 0.2021 - val_smape: 0.3859

Epoch 18/128

1916/1916 - 13s - 7ms/step - ia: 0.8515 - loss: 0.0944 - mae: 0.1989 - rmse: 0.2819 - smape: 0.4763 - val_ia: 0.6482 - val_loss: 0.0640 - val_mae: 0.1488 - val_rmse: 0.2022 - val_smape: 0.3880

Epoch 19/128

1916/1916 - 13s - 7ms/step - ia: 0.8530 - loss: 0.0933 - mae: 0.1976 - rmse: 0.2795 - smape: 0.4716 - val_ia: 0.6564 - val_loss: 0.0622 - val_mae: 0.1446 - val_rmse: 0.1990 - val_smape: 0.3815

Epoch 20/128

1916/1916 - 20s - 11ms/step - ia: 0.8550 - loss: 0.0902 - mae: 0.1953 - rmse: 0.2757 - smape: 0.4678 - val_ia: 0.6580 - val_loss: 0.0616 - val_mae: 0.1434 - val_rmse: 0.1982 - val_smape: 0.3790

Epoch 21/128

1916/1916 - 18s - 9ms/step - ia: 0.8559 - loss: 0.0902 - mae: 0.1936 - rmse: 0.2743 - smape: 0.4652 - val_ia: 0.6623 - val_loss: 0.0611 - val_mae: 0.1421 - val_rmse: 0.1970 - val_smape: 0.3767

Epoch 22/128

1916/1916 - 10s - 5ms/step - ia: 0.8574 - loss: 0.0885 - mae: 0.1922 - rmse: 0.2713 - smape: 0.4638 - val_ia: 0.6515 - val_loss: 0.0611 - val_mae: 0.1447 - val_rmse: 0.1988 - val_smape: 0.3802

Epoch 23/128

1916/1916 - 12s - 6ms/step - ia: 0.8591 - loss: 0.0882 - mae: 0.1910 - rmse: 0.2717 - smape: 0.4577 - val_ia: 0.6726 - val_loss: 0.0603 - val_mae: 0.1398 - val_rmse: 0.1946 - val_smape: 0.3747

Epoch 24/128

1916/1916 - 12s - 6ms/step - ia: 0.8602 - loss: 0.0868 - mae: 0.1883 - rmse: 0.2684 - smape: 0.4534 - val_ia: 0.6736 - val_loss: 0.0600 - val_mae: 0.1392 - val_rmse: 0.1939 - val_smape: 0.3738

Epoch 25/128

1916/1916 - 12s - 6ms/step - ia: 0.8615 - loss: 0.0855 - mae: 0.1868 - rmse: 0.2669 - smape: 0.4503 - val_ia: 0.6714 - val_loss: 0.0600 - val_mae: 0.1400 - val_rmse: 0.1941 - val_smape: 0.3741

Epoch 26/128

1916/1916 - 13s - 7ms/step - ia: 0.8616 - loss: 0.0854 - mae: 0.1863 - rmse: 0.2654 - smape: 0.4515 - val_ia: 0.6658 - val_loss: 0.0595 - val_mae: 0.1400 - val_rmse: 0.1945 - val_smape: 0.3720

Epoch 27/128

1916/1916 - 12s - 6ms/step - ia: 0.8628 - loss: 0.0840 - mae: 0.1850 - rmse: 0.2638 - smape: 0.4471 - val_ia: 0.6710 - val_loss: 0.0589 - val_mae: 0.1384 - val_rmse: 0.1928 - val_smape: 0.3700

Epoch 28/128

1916/1916 - 13s - 7ms/step - ia: 0.8630 - loss: 0.0842 - mae: 0.1851 - rmse: 0.2633 - smape: 0.4466 - val_ia: 0.6643 - val_loss: 0.0590 - val_mae: 0.1401 - val_rmse: 0.1937 - val_smape: 0.3720

Epoch 29/128

1916/1916 - 13s - 7ms/step - ia: 0.8632 - loss: 0.0837 - mae: 0.1846 - rmse: 0.2637 - smape: 0.4446 - val_ia: 0.6617 - val_loss: 0.0591 - val_mae: 0.1409 - val_rmse: 0.1942 - val_smape: 0.3725

Epoch 30/128

1916/1916 - 12s - 6ms/step - ia: 0.8646 - loss: 0.0835 - mae: 0.1829 - rmse: 0.2624 - smape: 0.4430 - val_ia: 0.6639 - val_loss: 0.0586 - val_mae: 0.1397 - val_rmse: 0.1936 - val_smape: 0.3707

Epoch 31/128

1916/1916 - 12s - 6ms/step - ia: 0.8644 - loss: 0.0824 - mae: 0.1828 - rmse: 0.2614 - smape: 0.4417 - val_ia: 0.6560 - val_loss: 0.0587 - val_mae: 0.1417 - val_rmse: 0.1949 - val_smape: 0.3734

Epoch 32/128

1916/1916 - 12s - 6ms/step - ia: 0.8658 - loss: 0.0810 - mae: 0.1812 - rmse: 0.2596 - smape: 0.4373 - val_ia: 0.6729 - val_loss: 0.0579 - val_mae: 0.1371 - val_rmse: 0.1913 - val_smape: 0.3666

Epoch 33/128

1916/1916 - 12s - 6ms/step - ia: 0.8673 - loss: 0.0804 - mae: 0.1797 - rmse: 0.2575 - smape: 0.4350 - val_ia: 0.6716 - val_loss: 0.0579 - val_mae: 0.1373 - val_rmse: 0.1915 - val_smape: 0.3667

Epoch 34/128

1916/1916 - 14s - 7ms/step - ia: 0.8671 - loss: 0.0814 - mae: 0.1802 - rmse: 0.2589 - smape: 0.4361 - val_ia: 0.6719 - val_loss: 0.0577 - val_mae: 0.1372 - val_rmse: 0.1910 - val_smape: 0.3665

Epoch 35/128

1916/1916 - 22s - 12ms/step - ia: 0.8683 - loss: 0.0804 - mae: 0.1786 - rmse: 0.2568 - smape: 0.4341 - val_ia: 0.6703 - val_loss: 0.0576 - val_mae: 0.1372 - val_rmse: 0.1914 - val_smape: 0.3663

Epoch 36/128

1916/1916 - 15s - 8ms/step - ia: 0.8682 - loss: 0.0796 - mae: 0.1777 - rmse: 0.2560 - smape: 0.4318 - val_ia: 0.6726 - val_loss: 0.0575 - val_mae: 0.1370 - val_rmse: 0.1905 - val_smape: 0.3662

Epoch 37/128

1916/1916 - 15s - 8ms/step - ia: 0.8693 - loss: 0.0799 - mae: 0.1769 - rmse: 0.2562 - smape: 0.4301 - val_ia: 0.6637 - val_loss: 0.0575 - val_mae: 0.1388 - val_rmse: 0.1921 - val_smape: 0.3677

Epoch 38/128

1916/1916 - 13s - 7ms/step - ia: 0.8697 - loss: 0.0786 - mae: 0.1763 - rmse: 0.2542 - smape: 0.4306 - val_ia: 0.6716 - val_loss: 0.0572 - val_mae: 0.1368 - val_rmse: 0.1902 - val_smape: 0.3654

Epoch 39/128

1916/1916 - 15s - 8ms/step - ia: 0.8709 - loss: 0.0779 - mae: 0.1753 - rmse: 0.2520 - smape: 0.4262 - val_ia: 0.6797 - val_loss: 0.0570 - val_mae: 0.1352 - val_rmse: 0.1890 - val_smape: 0.3632

Epoch 40/128

1916/1916 - 16s - 8ms/step - ia: 0.8700 - loss: 0.0786 - mae: 0.1756 - rmse: 0.2538 - smape: 0.4261 - val_ia: 0.6688 - val_loss: 0.0580 - val_mae: 0.1388 - val_rmse: 0.1913 - val_smape: 0.3672

Epoch 41/128

1916/1916 - 13s - 7ms/step - ia: 0.8704 - loss: 0.0785 - mae: 0.1756 - rmse: 0.2530 - smape: 0.4257 - val_ia: 0.6743 - val_loss: 0.0569 - val_mae: 0.1358 - val_rmse: 0.1896 - val_smape: 0.3628

Epoch 42/128

1916/1916 - 13s - 7ms/step - ia: 0.8705 - loss: 0.0781 - mae: 0.1756 - rmse: 0.2536 - smape: 0.4270 - val_ia: 0.6694 - val_loss: 0.0569 - val_mae: 0.1371 - val_rmse: 0.1902 - val_smape: 0.3644

Epoch 43/128

1916/1916 - 16s - 8ms/step - ia: 0.8719 - loss: 0.0783 - mae: 0.1740 - rmse: 0.2524 - smape: 0.4218 - val_ia: 0.6729 - val_loss: 0.0567 - val_mae: 0.1360 - val_rmse: 0.1893 - val_smape: 0.3632

Epoch 44/128

1916/1916 - 19s - 10ms/step - ia: 0.8711 - loss: 0.0786 - mae: 0.1739 - rmse: 0.2519 - smape: 0.4219 - val_ia: 0.6690 - val_loss: 0.0569 - val_mae: 0.1371 - val_rmse: 0.1902 - val_smape: 0.3644

Epoch 45/128

1916/1916 - 14s - 7ms/step - ia: 0.8716 - loss: 0.0778 - mae: 0.1740 - rmse: 0.2519 - smape: 0.4243 - val_ia: 0.6739 - val_loss: 0.0573 - val_mae: 0.1369 - val_rmse: 0.1897 - val_smape: 0.3648

Epoch 46/128

1916/1916 - 13s - 7ms/step - ia: 0.8714 - loss: 0.0771 - mae: 0.1734 - rmse: 0.2515 - smape: 0.4209 - val_ia: 0.6752 - val_loss: 0.0569 - val_mae: 0.1359 - val_rmse: 0.1892 - val_smape: 0.3627

Epoch 47/128

1916/1916 - 17s - 9ms/step - ia: 0.8722 - loss: 0.0775 - mae: 0.1738 - rmse: 0.2516 - smape: 0.4225 - val_ia: 0.6734 - val_loss: 0.0567 - val_mae: 0.1360 - val_rmse: 0.1892 - val_smape: 0.3625

Epoch 48/128

1916/1916 - 21s - 11ms/step - ia: 0.8723 - loss: 0.0768 - mae: 0.1727 - rmse: 0.2503 - smape: 0.4223 - val_ia: 0.6814 - val_loss: 0.0563 - val_mae: 0.1339 - val_rmse: 0.1878 - val_smape: 0.3600

Epoch 49/128

1916/1916 - 11s - 6ms/step - ia: 0.8718 - loss: 0.0776 - mae: 0.1732 - rmse: 0.2521 - smape: 0.4227 - val_ia: 0.6646 - val_loss: 0.0569 - val_mae: 0.1381 - val_rmse: 0.1911 - val_smape: 0.3657

Epoch 50/128

1916/1916 - 10s - 5ms/step - ia: 0.8730 - loss: 0.0763 - mae: 0.1713 - rmse: 0.2492 - smape: 0.4165 - val_ia: 0.6689 - val_loss: 0.0566 - val_mae: 0.1369 - val_rmse: 0.1900 - val_smape: 0.3634

Epoch 51/128

1916/1916 - 22s - 12ms/step - ia: 0.8726 - loss: 0.0759 - mae: 0.1715 - rmse: 0.2490 - smape: 0.4176 - val_ia: 0.6786 - val_loss: 0.0563 - val_mae: 0.1342 - val_rmse: 0.1882 - val_smape: 0.3597

Epoch 52/128

1916/1916 - 16s - 8ms/step - ia: 0.8730 - loss: 0.0760 - mae: 0.1717 - rmse: 0.2488 - smape: 0.4182 - val_ia: 0.6806 - val_loss: 0.0563 - val_mae: 0.1341 - val_rmse: 0.1880 - val_smape: 0.3591

Epoch 53/128

1916/1916 - 16s - 8ms/step - ia: 0.8737 - loss: 0.0759 - mae: 0.1711 - rmse: 0.2486 - smape: 0.4171 - val_ia: 0.6860 - val_loss: 0.0561 - val_mae: 0.1328 - val_rmse: 0.1869 - val_smape: 0.3595

Epoch 54/128

1916/1916 - 14s - 8ms/step - ia: 0.8735 - loss: 0.0767 - mae: 0.1713 - rmse: 0.2500 - smape: 0.4169 - val_ia: 0.6574 - val_loss: 0.0570 - val_mae: 0.1399 - val_rmse: 0.1926 - val_smape: 0.3694

Epoch 55/128

1916/1916 - 14s - 7ms/step - ia: 0.8748 - loss: 0.0757 - mae: 0.1704 - rmse: 0.2475 - smape: 0.4147 - val_ia: 0.6780 - val_loss: 0.0560 - val_mae: 0.1341 - val_rmse: 0.1878 - val_smape: 0.3597

Epoch 56/128

1916/1916 - 23s - 12ms/step - ia: 0.8734 - loss: 0.0772 - mae: 0.1712 - rmse: 0.2500 - smape: 0.4169 - val_ia: 0.6747 - val_loss: 0.0563 - val_mae: 0.1352 - val_rmse: 0.1888 - val_smape: 0.3608

Epoch 57/128

1916/1916 - 21s - 11ms/step - ia: 0.8751 - loss: 0.0756 - mae: 0.1697 - rmse: 0.2476 - smape: 0.4130 - val_ia: 0.6840 - val_loss: 0.0563 - val_mae: 0.1338 - val_rmse: 0.1873 - val_smape: 0.3596

Epoch 58/128

1916/1916 - 15s - 8ms/step - ia: 0.8754 - loss: 0.0751 - mae: 0.1693 - rmse: 0.2466 - smape: 0.4118 - val_ia: 0.6800 - val_loss: 0.0559 - val_mae: 0.1336 - val_rmse: 0.1873 - val_smape: 0.3584

Epoch 59/128

1916/1916 - 16s - 8ms/step - ia: 0.8747 - loss: 0.0747 - mae: 0.1696 - rmse: 0.2471 - smape: 0.4156 - val_ia: 0.6676 - val_loss: 0.0563 - val_mae: 0.1368 - val_rmse: 0.1899 - val_smape: 0.3640

Epoch 60/128

1916/1916 - 16s - 8ms/step - ia: 0.8752 - loss: 0.0748 - mae: 0.1691 - rmse: 0.2472 - smape: 0.4132 - val_ia: 0.6671 - val_loss: 0.0562 - val_mae: 0.1369 - val_rmse: 0.1896 - val_smape: 0.3632

Epoch 61/128

1916/1916 - 16s - 8ms/step - ia: 0.8746 - loss: 0.0760 - mae: 0.1700 - rmse: 0.2480 - smape: 0.4127 - val_ia: 0.6669 - val_loss: 0.0563 - val_mae: 0.1372 - val_rmse: 0.1896 - val_smape: 0.3638

Epoch 62/128

1916/1916 - 16s - 8ms/step - ia: 0.8757 - loss: 0.0753 - mae: 0.1685 - rmse: 0.2464 - smape: 0.4128 - val_ia: 0.6660 - val_loss: 0.0563 - val_mae: 0.1372 - val_rmse: 0.1902 - val_smape: 0.3644

Epoch 63/128

1916/1916 - 16s - 9ms/step - ia: 0.8749 - loss: 0.0753 - mae: 0.1695 - rmse: 0.2471 - smape: 0.4127 - val_ia: 0.6764 - val_loss: 0.0561 - val_mae: 0.1347 - val_rmse: 0.1881 - val_smape: 0.3599

Epoch 64/128

1916/1916 - 17s - 9ms/step - ia: 0.8748 - loss: 0.0750 - mae: 0.1694 - rmse: 0.2472 - smape: 0.4137 - val_ia: 0.6901 - val_loss: 0.0559 - val_mae: 0.1324 - val_rmse: 0.1862 - val_smape: 0.3589

Epoch 65/128

1916/1916 - 16s - 8ms/step - ia: 0.8767 - loss: 0.0746 - mae: 0.1677 - rmse: 0.2455 - smape: 0.4097 - val_ia: 0.6817 - val_loss: 0.0557 - val_mae: 0.1332 - val_rmse: 0.1870 - val_smape: 0.3575

Epoch 66/128

1916/1916 - 16s - 8ms/step - ia: 0.8759 - loss: 0.0745 - mae: 0.1684 - rmse: 0.2456 - smape: 0.4105 - val_ia: 0.6836 - val_loss: 0.0556 - val_mae: 0.1326 - val_rmse: 0.1865 - val_smape: 0.3570

Epoch 67/128

1916/1916 - 20s - 11ms/step - ia: 0.8769 - loss: 0.0741 - mae: 0.1674 - rmse: 0.2441 - smape: 0.4086 - val_ia: 0.6842 - val_loss: 0.0557 - val_mae: 0.1329 - val_rmse: 0.1866 - val_smape: 0.3569

Epoch 68/128

1916/1916 - 16s - 8ms/step - ia: 0.8765 - loss: 0.0745 - mae: 0.1671 - rmse: 0.2455 - smape: 0.4070 - val_ia: 0.6842 - val_loss: 0.0557 - val_mae: 0.1327 - val_rmse: 0.1865 - val_smape: 0.3575

Epoch 69/128

1916/1916 - 20s - 11ms/step - ia: 0.8776 - loss: 0.0744 - mae: 0.1665 - rmse: 0.2450 - smape: 0.4072 - val_ia: 0.6805 - val_loss: 0.0562 - val_mae: 0.1345 - val_rmse: 0.1873 - val_smape: 0.3601

Epoch 70/128

1916/1916 - 16s - 8ms/step - ia: 0.8765 - loss: 0.0750 - mae: 0.1680 - rmse: 0.2465 - smape: 0.4109 - val_ia: 0.6727 - val_loss: 0.0559 - val_mae: 0.1352 - val_rmse: 0.1889 - val_smape: 0.3623

Epoch 71/128

1916/1916 - 21s - 11ms/step - ia: 0.8775 - loss: 0.0736 - mae: 0.1664 - rmse: 0.2435 - smape: 0.4076 - val_ia: 0.6827 - val_loss: 0.0558 - val_mae: 0.1333 - val_rmse: 0.1868 - val_smape: 0.3572

Epoch 72/128

1916/1916 - 20s - 10ms/step - ia: 0.8781 - loss: 0.0732 - mae: 0.1657 - rmse: 0.2428 - smape: 0.4050 - val_ia: 0.6808 - val_loss: 0.0559 - val_mae: 0.1339 - val_rmse: 0.1870 - val_smape: 0.3577

Epoch 73/128

1916/1916 - 10s - 5ms/step - ia: 0.8776 - loss: 0.0736 - mae: 0.1666 - rmse: 0.2444 - smape: 0.4057 - val_ia: 0.6813 - val_loss: 0.0557 - val_mae: 0.1335 - val_rmse: 0.1867 - val_smape: 0.3581

Epoch 74/128

1916/1916 - 9s - 5ms/step - ia: 0.8777 - loss: 0.0727 - mae: 0.1656 - rmse: 0.2430 - smape: 0.4072 - val_ia: 0.6659 - val_loss: 0.0562 - val_mae: 0.1372 - val_rmse: 0.1902 - val_smape: 0.3650

Epoch 75/128

1916/1916 - 15s - 8ms/step - ia: 0.8783 - loss: 0.0732 - mae: 0.1658 - rmse: 0.2432 - smape: 0.4058 - val_ia: 0.6868 - val_loss: 0.0554 - val_mae: 0.1318 - val_rmse: 0.1858 - val_smape: 0.3553

Epoch 76/128

1916/1916 - 22s - 11ms/step - ia: 0.8770 - loss: 0.0744 - mae: 0.1667 - rmse: 0.2447 - smape: 0.4067 - val_ia: 0.6855 - val_loss: 0.0557 - val_mae: 0.1329 - val_rmse: 0.1863 - val_smape: 0.3569

Epoch 77/128

1916/1916 - 18s - 9ms/step - ia: 0.8781 - loss: 0.0735 - mae: 0.1657 - rmse: 0.2432 - smape: 0.4050 - val_ia: 0.6867 - val_loss: 0.0553 - val_mae: 0.1318 - val_rmse: 0.1859 - val_smape: 0.3553

Epoch 78/128

1916/1916 - 16s - 8ms/step - ia: 0.8784 - loss: 0.0732 - mae: 0.1661 - rmse: 0.2427 - smape: 0.4062 - val_ia: 0.6731 - val_loss: 0.0560 - val_mae: 0.1358 - val_rmse: 0.1884 - val_smape: 0.3606

Epoch 79/128

1916/1916 - 20s - 11ms/step - ia: 0.8780 - loss: 0.0733 - mae: 0.1654 - rmse: 0.2434 - smape: 0.4029 - val_ia: 0.6793 - val_loss: 0.0559 - val_mae: 0.1345 - val_rmse: 0.1872 - val_smape: 0.3590

Epoch 80/128

1916/1916 - 15s - 8ms/step - ia: 0.8767 - loss: 0.0739 - mae: 0.1669 - rmse: 0.2455 - smape: 0.4087 - val_ia: 0.6817 - val_loss: 0.0554 - val_mae: 0.1331 - val_rmse: 0.1866 - val_smape: 0.3571

Epoch 81/128

1916/1916 - 20s - 11ms/step - ia: 0.8783 - loss: 0.0721 - mae: 0.1647 - rmse: 0.2413 - smape: 0.4047 - val_ia: 0.6859 - val_loss: 0.0553 - val_mae: 0.1323 - val_rmse: 0.1857 - val_smape: 0.3561

Epoch 82/128

1916/1916 - 16s - 8ms/step - ia: 0.8788 - loss: 0.0721 - mae: 0.1645 - rmse: 0.2416 - smape: 0.4036 - val_ia: 0.6827 - val_loss: 0.0554 - val_mae: 0.1331 - val_rmse: 0.1863 - val_smape: 0.3569

Epoch 83/128

1916/1916 - 17s - 9ms/step - ia: 0.8775 - loss: 0.0737 - mae: 0.1658 - rmse: 0.2441 - smape: 0.4043 - val_ia: 0.6886 - val_loss: 0.0554 - val_mae: 0.1320 - val_rmse: 0.1855 - val_smape: 0.3567

Epoch 84/128

1916/1916 - 24s - 13ms/step - ia: 0.8786 - loss: 0.0729 - mae: 0.1646 - rmse: 0.2422 - smape: 0.4052 - val_ia: 0.6865 - val_loss: 0.0559 - val_mae: 0.1332 - val_rmse: 0.1864 - val_smape: 0.3565

Epoch 85/128

1916/1916 - 16s - 8ms/step - ia: 0.8784 - loss: 0.0723 - mae: 0.1648 - rmse: 0.2418 - smape: 0.4045 - val_ia: 0.6892 - val_loss: 0.0554 - val_mae: 0.1319 - val_rmse: 0.1855 - val_smape: 0.3557

Epoch 86/128

1916/1916 - 20s - 11ms/step - ia: 0.8786 - loss: 0.0729 - mae: 0.1651 - rmse: 0.2426 - smape: 0.4024 - val_ia: 0.6849 - val_loss: 0.0551 - val_mae: 0.1319 - val_rmse: 0.1857 - val_smape: 0.3558

Epoch 87/128

1916/1916 - 21s - 11ms/step - ia: 0.8795 - loss: 0.0722 - mae: 0.1642 - rmse: 0.2409 - smape: 0.4017 - val_ia: 0.6802 - val_loss: 0.0554 - val_mae: 0.1337 - val_rmse: 0.1867 - val_smape: 0.3580

Epoch 88/128

1916/1916 - 14s - 7ms/step - ia: 0.8783 - loss: 0.0727 - mae: 0.1645 - rmse: 0.2422 - smape: 0.4015 - val_ia: 0.6848 - val_loss: 0.0554 - val_mae: 0.1328 - val_rmse: 0.1860 - val_smape: 0.3560

Epoch 89/128

1916/1916 - 16s - 8ms/step - ia: 0.8792 - loss: 0.0718 - mae: 0.1637 - rmse: 0.2405 - smape: 0.4006 - val_ia: 0.6935 - val_loss: 0.0550 - val_mae: 0.1306 - val_rmse: 0.1847 - val_smape: 0.3532

Epoch 90/128

1916/1916 - 16s - 8ms/step - ia: 0.8785 - loss: 0.0737 - mae: 0.1649 - rmse: 0.2433 - smape: 0.4042 - val_ia: 0.6847 - val_loss: 0.0551 - val_mae: 0.1321 - val_rmse: 0.1858 - val_smape: 0.3559

Epoch 91/128

1916/1916 - 20s - 11ms/step - ia: 0.8794 - loss: 0.0715 - mae: 0.1636 - rmse: 0.2407 - smape: 0.4023 - val_ia: 0.6856 - val_loss: 0.0553 - val_mae: 0.1325 - val_rmse: 0.1857 - val_smape: 0.3561

Epoch 92/128

1916/1916 - 19s - 10ms/step - ia: 0.8784 - loss: 0.0738 - mae: 0.1648 - rmse: 0.2431 - smape: 0.4035 - val_ia: 0.6956 - val_loss: 0.0549 - val_mae: 0.1301 - val_rmse: 0.1842 - val_smape: 0.3529

Epoch 93/128

1916/1916 - 15s - 8ms/step - ia: 0.8791 - loss: 0.0723 - mae: 0.1637 - rmse: 0.2404 - smape: 0.4025 - val_ia: 0.6869 - val_loss: 0.0550 - val_mae: 0.1316 - val_rmse: 0.1853 - val_smape: 0.3550

Epoch 94/128

1916/1916 - 20s - 11ms/step - ia: 0.8786 - loss: 0.0729 - mae: 0.1645 - rmse: 0.2431 - smape: 0.4008 - val_ia: 0.6864 - val_loss: 0.0550 - val_mae: 0.1317 - val_rmse: 0.1855 - val_smape: 0.3554

Epoch 95/128

1916/1916 - 14s - 7ms/step - ia: 0.8800 - loss: 0.0726 - mae: 0.1630 - rmse: 0.2411 - smape: 0.3976 - val_ia: 0.6687 - val_loss: 0.0560 - val_mae: 0.1369 - val_rmse: 0.1892 - val_smape: 0.3628

Epoch 96/128

1916/1916 - 14s - 7ms/step - ia: 0.8786 - loss: 0.0730 - mae: 0.1650 - rmse: 0.2425 - smape: 0.4040 - val_ia: 0.6817 - val_loss: 0.0556 - val_mae: 0.1338 - val_rmse: 0.1867 - val_smape: 0.3573

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 11s - 12ms/step - ia: 0.4349 - loss: 0.8032 - mae: 0.6367 - rmse: 0.8697 - smape: 1.2170 - val_ia: 0.4029 - val_loss: 0.4468 - val_mae: 0.4660 - val_rmse: 0.5432 - val_smape: 1.0113

Epoch 2/128

958/958 - 5s - 6ms/step - ia: 0.6285 - loss: 0.4454 - mae: 0.4721 - rmse: 0.6450 - smape: 0.9308 - val_ia: 0.5672 - val_loss: 0.2133 - val_mae: 0.2882 - val_rmse: 0.3612 - val_smape: 0.6234

Epoch 3/128

958/958 - 6s - 6ms/step - ia: 0.7109 - loss: 0.3108 - mae: 0.3905 - rmse: 0.5389 - smape: 0.7829 - val_ia: 0.6074 - val_loss: 0.1580 - val_mae: 0.2445 - val_rmse: 0.3154 - val_smape: 0.5428

Epoch 4/128

958/958 - 6s - 6ms/step - ia: 0.7411 - loss: 0.2578 - mae: 0.3520 - rmse: 0.4888 - smape: 0.7246 - val_ia: 0.6137 - val_loss: 0.1364 - val_mae: 0.2317 - val_rmse: 0.3010 - val_smape: 0.5256

Epoch 5/128

958/958 - 6s - 6ms/step - ia: 0.7578 - loss: 0.2270 - mae: 0.3290 - rmse: 0.4591 - smape: 0.6907 - val_ia: 0.6146 - val_loss: 0.1244 - val_mae: 0.2265 - val_rmse: 0.2937 - val_smape: 0.5212

Epoch 6/128

958/958 - 10s - 10ms/step - ia: 0.7705 - loss: 0.2119 - mae: 0.3126 - rmse: 0.4412 - smape: 0.6636 - val_ia: 0.6279 - val_loss: 0.1142 - val_mae: 0.2165 - val_rmse: 0.2831 - val_smape: 0.5054

Epoch 7/128

958/958 - 6s - 6ms/step - ia: 0.7801 - loss: 0.1972 - mae: 0.3005 - rmse: 0.4255 - smape: 0.6441 - val_ia: 0.6447 - val_loss: 0.1048 - val_mae: 0.2050 - val_rmse: 0.2713 - val_smape: 0.4845

Epoch 8/128

958/958 - 6s - 6ms/step - ia: 0.7854 - loss: 0.1878 - mae: 0.2933 - rmse: 0.4150 - smape: 0.6298 - val_ia: 0.6458 - val_loss: 0.0996 - val_mae: 0.2025 - val_rmse: 0.2672 - val_smape: 0.4799

Epoch 9/128

958/958 - 6s - 6ms/step - ia: 0.7928 - loss: 0.1745 - mae: 0.2839 - rmse: 0.4007 - smape: 0.6185 - val_ia: 0.6606 - val_loss: 0.0943 - val_mae: 0.1941 - val_rmse: 0.2590 - val_smape: 0.4663

Epoch 10/128

958/958 - 6s - 7ms/step - ia: 0.7976 - loss: 0.1676 - mae: 0.2770 - rmse: 0.3926 - smape: 0.6031 - val_ia: 0.6701 - val_loss: 0.0906 - val_mae: 0.1891 - val_rmse: 0.2534 - val_smape: 0.4574

Epoch 11/128

958/958 - 6s - 6ms/step - ia: 0.8017 - loss: 0.1633 - mae: 0.2718 - rmse: 0.3865 - smape: 0.5939 - val_ia: 0.6743 - val_loss: 0.0877 - val_mae: 0.1862 - val_rmse: 0.2500 - val_smape: 0.4517

Epoch 12/128

958/958 - 10s - 11ms/step - ia: 0.8060 - loss: 0.1573 - mae: 0.2665 - rmse: 0.3796 - smape: 0.5801 - val_ia: 0.6783 - val_loss: 0.0842 - val_mae: 0.1829 - val_rmse: 0.2460 - val_smape: 0.4459

Epoch 13/128

958/958 - 10s - 10ms/step - ia: 0.8078 - loss: 0.1566 - mae: 0.2639 - rmse: 0.3776 - smape: 0.5755 - val_ia: 0.6817 - val_loss: 0.0813 - val_mae: 0.1800 - val_rmse: 0.2430 - val_smape: 0.4412

Epoch 14/128

958/958 - 6s - 6ms/step - ia: 0.8111 - loss: 0.1528 - mae: 0.2599 - rmse: 0.3731 - smape: 0.5686 - val_ia: 0.6941 - val_loss: 0.0788 - val_mae: 0.1745 - val_rmse: 0.2378 - val_smape: 0.4321

Epoch 15/128

958/958 - 10s - 10ms/step - ia: 0.8134 - loss: 0.1494 - mae: 0.2569 - rmse: 0.3691 - smape: 0.5645 - val_ia: 0.6901 - val_loss: 0.0773 - val_mae: 0.1751 - val_rmse: 0.2372 - val_smape: 0.4328

Epoch 16/128

958/958 - 6s - 6ms/step - ia: 0.8167 - loss: 0.1435 - mae: 0.2526 - rmse: 0.3626 - smape: 0.5553 - val_ia: 0.6894 - val_loss: 0.0768 - val_mae: 0.1754 - val_rmse: 0.2366 - val_smape: 0.4320

Epoch 17/128

958/958 - 6s - 6ms/step - ia: 0.8171 - loss: 0.1431 - mae: 0.2525 - rmse: 0.3614 - smape: 0.5554 - val_ia: 0.7018 - val_loss: 0.0741 - val_mae: 0.1694 - val_rmse: 0.2315 - val_smape: 0.4233

Epoch 18/128

958/958 - 11s - 11ms/step - ia: 0.8184 - loss: 0.1413 - mae: 0.2502 - rmse: 0.3585 - smape: 0.5477 - val_ia: 0.7055 - val_loss: 0.0729 - val_mae: 0.1677 - val_rmse: 0.2296 - val_smape: 0.4203

Epoch 19/128

958/958 - 6s - 6ms/step - ia: 0.8181 - loss: 0.1431 - mae: 0.2499 - rmse: 0.3615 - smape: 0.5444 - val_ia: 0.7049 - val_loss: 0.0717 - val_mae: 0.1670 - val_rmse: 0.2287 - val_smape: 0.4191

Epoch 20/128

958/958 - 8s - 8ms/step - ia: 0.8215 - loss: 0.1410 - mae: 0.2464 - rmse: 0.3563 - smape: 0.5411 - val_ia: 0.7134 - val_loss: 0.0705 - val_mae: 0.1638 - val_rmse: 0.2256 - val_smape: 0.4140

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.8223 - loss: 0.1383 - mae: 0.2449 - rmse: 0.3545 - smape: 0.5387 - val_ia: 0.7136 - val_loss: 0.0695 - val_mae: 0.1629 - val_rmse: 0.2248 - val_smape: 0.4123

Epoch 22/128

958/958 - 10s - 11ms/step - ia: 0.8242 - loss: 0.1374 - mae: 0.2428 - rmse: 0.3524 - smape: 0.5324 - val_ia: 0.7222 - val_loss: 0.0686 - val_mae: 0.1600 - val_rmse: 0.2223 - val_smape: 0.4073

Epoch 23/128

958/958 - 3s - 3ms/step - ia: 0.8264 - loss: 0.1314 - mae: 0.2400 - rmse: 0.3464 - smape: 0.5308 - val_ia: 0.7287 - val_loss: 0.0671 - val_mae: 0.1570 - val_rmse: 0.2197 - val_smape: 0.4029

Epoch 24/128

958/958 - 4s - 4ms/step - ia: 0.8241 - loss: 0.1415 - mae: 0.2432 - rmse: 0.3561 - smape: 0.5282 - val_ia: 0.7188 - val_loss: 0.0670 - val_mae: 0.1599 - val_rmse: 0.2211 - val_smape: 0.4063

Epoch 25/128

958/958 - 7s - 7ms/step - ia: 0.8274 - loss: 0.1331 - mae: 0.2393 - rmse: 0.3467 - smape: 0.5250 - val_ia: 0.7264 - val_loss: 0.0660 - val_mae: 0.1568 - val_rmse: 0.2186 - val_smape: 0.4018

Epoch 26/128

958/958 - 9s - 9ms/step - ia: 0.8290 - loss: 0.1296 - mae: 0.2364 - rmse: 0.3432 - smape: 0.5220 - val_ia: 0.7258 - val_loss: 0.0654 - val_mae: 0.1565 - val_rmse: 0.2181 - val_smape: 0.4011

Epoch 27/128

958/958 - 3s - 3ms/step - ia: 0.8276 - loss: 0.1355 - mae: 0.2386 - rmse: 0.3484 - smape: 0.5215 - val_ia: 0.7214 - val_loss: 0.0658 - val_mae: 0.1585 - val_rmse: 0.2192 - val_smape: 0.4033

Epoch 28/128

958/958 - 5s - 5ms/step - ia: 0.8291 - loss: 0.1280 - mae: 0.2355 - rmse: 0.3414 - smape: 0.5204 - val_ia: 0.7187 - val_loss: 0.0656 - val_mae: 0.1593 - val_rmse: 0.2195 - val_smape: 0.4038

Epoch 29/128

958/958 - 6s - 6ms/step - ia: 0.8285 - loss: 0.1287 - mae: 0.2363 - rmse: 0.3419 - smape: 0.5199 - val_ia: 0.7343 - val_loss: 0.0638 - val_mae: 0.1528 - val_rmse: 0.2148 - val_smape: 0.3952

Epoch 30/128

958/958 - 10s - 11ms/step - ia: 0.8309 - loss: 0.1277 - mae: 0.2343 - rmse: 0.3401 - smape: 0.5179 - val_ia: 0.7219 - val_loss: 0.0639 - val_mae: 0.1567 - val_rmse: 0.2176 - val_smape: 0.4010

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.8308 - loss: 0.1293 - mae: 0.2339 - rmse: 0.3415 - smape: 0.5144 - val_ia: 0.7358 - val_loss: 0.0630 - val_mae: 0.1519 - val_rmse: 0.2137 - val_smape: 0.3931

Epoch 32/128

958/958 - 5s - 6ms/step - ia: 0.8316 - loss: 0.1271 - mae: 0.2327 - rmse: 0.3386 - smape: 0.5126 - val_ia: 0.7280 - val_loss: 0.0640 - val_mae: 0.1554 - val_rmse: 0.2162 - val_smape: 0.3972

Epoch 33/128

958/958 - 11s - 11ms/step - ia: 0.8303 - loss: 0.1278 - mae: 0.2348 - rmse: 0.3406 - smape: 0.5152 - val_ia: 0.7312 - val_loss: 0.0630 - val_mae: 0.1535 - val_rmse: 0.2147 - val_smape: 0.3948

Epoch 34/128

958/958 - 7s - 7ms/step - ia: 0.8330 - loss: 0.1247 - mae: 0.2312 - rmse: 0.3365 - smape: 0.5081 - val_ia: 0.7341 - val_loss: 0.0641 - val_mae: 0.1541 - val_rmse: 0.2149 - val_smape: 0.3937

Epoch 35/128

958/958 - 6s - 6ms/step - ia: 0.8315 - loss: 0.1290 - mae: 0.2330 - rmse: 0.3416 - smape: 0.5084 - val_ia: 0.7341 - val_loss: 0.0625 - val_mae: 0.1522 - val_rmse: 0.2137 - val_smape: 0.3918

Epoch 36/128

958/958 - 6s - 6ms/step - ia: 0.8331 - loss: 0.1245 - mae: 0.2309 - rmse: 0.3360 - smape: 0.5088 - val_ia: 0.7325 - val_loss: 0.0627 - val_mae: 0.1531 - val_rmse: 0.2140 - val_smape: 0.3927

Epoch 37/128

958/958 - 6s - 6ms/step - ia: 0.8323 - loss: 0.1253 - mae: 0.2315 - rmse: 0.3369 - smape: 0.5103 - val_ia: 0.7402 - val_loss: 0.0617 - val_mae: 0.1499 - val_rmse: 0.2116 - val_smape: 0.3891

Epoch 38/128

958/958 - 10s - 11ms/step - ia: 0.8335 - loss: 0.1235 - mae: 0.2303 - rmse: 0.3353 - smape: 0.5036 - val_ia: 0.7327 - val_loss: 0.0618 - val_mae: 0.1522 - val_rmse: 0.2133 - val_smape: 0.3927

Epoch 39/128

958/958 - 10s - 11ms/step - ia: 0.8352 - loss: 0.1232 - mae: 0.2286 - rmse: 0.3335 - smape: 0.5017 - val_ia: 0.7355 - val_loss: 0.0626 - val_mae: 0.1524 - val_rmse: 0.2133 - val_smape: 0.3914

Epoch 40/128

958/958 - 6s - 6ms/step - ia: 0.8345 - loss: 0.1225 - mae: 0.2284 - rmse: 0.3335 - smape: 0.5029 - val_ia: 0.7394 - val_loss: 0.0618 - val_mae: 0.1504 - val_rmse: 0.2118 - val_smape: 0.3887

Epoch 41/128

958/958 - 6s - 6ms/step - ia: 0.8341 - loss: 0.1258 - mae: 0.2289 - rmse: 0.3363 - smape: 0.5010 - val_ia: 0.7356 - val_loss: 0.0614 - val_mae: 0.1511 - val_rmse: 0.2122 - val_smape: 0.3892

Epoch 42/128

958/958 - 6s - 6ms/step - ia: 0.8339 - loss: 0.1241 - mae: 0.2295 - rmse: 0.3356 - smape: 0.5010 - val_ia: 0.7406 - val_loss: 0.0610 - val_mae: 0.1492 - val_rmse: 0.2107 - val_smape: 0.3866

Epoch 43/128

958/958 - 6s - 6ms/step - ia: 0.8351 - loss: 0.1245 - mae: 0.2285 - rmse: 0.3339 - smape: 0.5034 - val_ia: 0.7440 - val_loss: 0.0612 - val_mae: 0.1487 - val_rmse: 0.2103 - val_smape: 0.3851

Epoch 44/128

958/958 - 10s - 11ms/step - ia: 0.8351 - loss: 0.1252 - mae: 0.2283 - rmse: 0.3348 - smape: 0.4976 - val_ia: 0.7446 - val_loss: 0.0616 - val_mae: 0.1490 - val_rmse: 0.2107 - val_smape: 0.3853

Epoch 45/128

958/958 - 6s - 7ms/step - ia: 0.8351 - loss: 0.1219 - mae: 0.2287 - rmse: 0.3320 - smape: 0.5040 - val_ia: 0.7418 - val_loss: 0.0621 - val_mae: 0.1504 - val_rmse: 0.2115 - val_smape: 0.3867

Epoch 46/128

958/958 - 8s - 8ms/step - ia: 0.8353 - loss: 0.1236 - mae: 0.2285 - rmse: 0.3348 - smape: 0.5002 - val_ia: 0.7414 - val_loss: 0.0617 - val_mae: 0.1500 - val_rmse: 0.2112 - val_smape: 0.3869

Epoch 47/128

958/958 - 6s - 6ms/step - ia: 0.8346 - loss: 0.1246 - mae: 0.2282 - rmse: 0.3351 - smape: 0.4991 - val_ia: 0.7394 - val_loss: 0.0610 - val_mae: 0.1498 - val_rmse: 0.2111 - val_smape: 0.3855

Epoch 48/128

958/958 - 6s - 6ms/step - ia: 0.8350 - loss: 0.1259 - mae: 0.2290 - rmse: 0.3370 - smape: 0.4999 - val_ia: 0.7448 - val_loss: 0.0601 - val_mae: 0.1471 - val_rmse: 0.2093 - val_smape: 0.3829

Epoch 49/128

958/958 - 8s - 9ms/step - ia: 0.8383 - loss: 0.1222 - mae: 0.2252 - rmse: 0.3315 - smape: 0.4946 - val_ia: 0.7333 - val_loss: 0.0609 - val_mae: 0.1516 - val_rmse: 0.2120 - val_smape: 0.3888

Epoch 50/128

958/958 - 4s - 4ms/step - ia: 0.8347 - loss: 0.1264 - mae: 0.2287 - rmse: 0.3367 - smape: 0.4967 - val_ia: 0.7436 - val_loss: 0.0616 - val_mae: 0.1495 - val_rmse: 0.2107 - val_smape: 0.3850

Epoch 51/128

958/958 - 6s - 6ms/step - ia: 0.8354 - loss: 0.1247 - mae: 0.2273 - rmse: 0.3333 - smape: 0.4974 - val_ia: 0.7467 - val_loss: 0.0609 - val_mae: 0.1478 - val_rmse: 0.2094 - val_smape: 0.3830

Epoch 52/128

958/958 - 10s - 10ms/step - ia: 0.8371 - loss: 0.1207 - mae: 0.2259 - rmse: 0.3307 - smape: 0.4977 - val_ia: 0.7427 - val_loss: 0.0611 - val_mae: 0.1493 - val_rmse: 0.2101 - val_smape: 0.3852

Epoch 53/128

958/958 - 11s - 11ms/step - ia: 0.8372 - loss: 0.1206 - mae: 0.2260 - rmse: 0.3292 - smape: 0.4946 - val_ia: 0.7372 - val_loss: 0.0610 - val_mae: 0.1507 - val_rmse: 0.2114 - val_smape: 0.3870

Epoch 54/128

958/958 - 6s - 6ms/step - ia: 0.8372 - loss: 0.1215 - mae: 0.2257 - rmse: 0.3318 - smape: 0.4951 - val_ia: 0.7362 - val_loss: 0.0608 - val_mae: 0.1508 - val_rmse: 0.2116 - val_smape: 0.3874

Epoch 55/128

958/958 - 10s - 10ms/step - ia: 0.8358 - loss: 0.1250 - mae: 0.2274 - rmse: 0.3354 - smape: 0.4975 - val_ia: 0.7403 - val_loss: 0.0608 - val_mae: 0.1495 - val_rmse: 0.2106 - val_smape: 0.3853

Epoch 56/128

958/958 - 6s - 6ms/step - ia: 0.8377 - loss: 0.1211 - mae: 0.2250 - rmse: 0.3304 - smape: 0.4940 - val_ia: 0.7454 - val_loss: 0.0603 - val_mae: 0.1476 - val_rmse: 0.2091 - val_smape: 0.3830

Epoch 57/128

958/958 - 6s - 6ms/step - ia: 0.8371 - loss: 0.1228 - mae: 0.2262 - rmse: 0.3321 - smape: 0.4933 - val_ia: 0.7519 - val_loss: 0.0601 - val_mae: 0.1456 - val_rmse: 0.2077 - val_smape: 0.3802

Epoch 58/128

958/958 - 6s - 6ms/step - ia: 0.8371 - loss: 0.1210 - mae: 0.2254 - rmse: 0.3299 - smape: 0.4956 - val_ia: 0.7386 - val_loss: 0.0607 - val_mae: 0.1500 - val_rmse: 0.2108 - val_smape: 0.3858

Epoch 59/128

958/958 - 11s - 11ms/step - ia: 0.8368 - loss: 0.1227 - mae: 0.2258 - rmse: 0.3325 - smape: 0.4942 - val_ia: 0.7480 - val_loss: 0.0599 - val_mae: 0.1464 - val_rmse: 0.2083 - val_smape: 0.3806

Epoch 60/128

958/958 - 6s - 7ms/step - ia: 0.8372 - loss: 0.1230 - mae: 0.2252 - rmse: 0.3311 - smape: 0.4924 - val_ia: 0.7404 - val_loss: 0.0611 - val_mae: 0.1501 - val_rmse: 0.2111 - val_smape: 0.3851

Epoch 61/128

958/958 - 10s - 10ms/step - ia: 0.8374 - loss: 0.1209 - mae: 0.2255 - rmse: 0.3307 - smape: 0.4933 - val_ia: 0.7435 - val_loss: 0.0603 - val_mae: 0.1482 - val_rmse: 0.2098 - val_smape: 0.3834

Epoch 62/128

958/958 - 11s - 12ms/step - ia: 0.8361 - loss: 0.1217 - mae: 0.2267 - rmse: 0.3319 - smape: 0.4976 - val_ia: 0.7484 - val_loss: 0.0601 - val_mae: 0.1466 - val_rmse: 0.2084 - val_smape: 0.3808

Epoch 63/128

958/958 - 10s - 10ms/step - ia: 0.8378 - loss: 0.1215 - mae: 0.2251 - rmse: 0.3319 - smape: 0.4917 - val_ia: 0.7442 - val_loss: 0.0605 - val_mae: 0.1483 - val_rmse: 0.2095 - val_smape: 0.3835

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.8378 - loss: 0.1196 - mae: 0.2250 - rmse: 0.3298 - smape: 0.4942 - val_ia: 0.7439 - val_loss: 0.0596 - val_mae: 0.1473 - val_rmse: 0.2088 - val_smape: 0.3827

Epoch 65/128

958/958 - 3s - 3ms/step - ia: 0.8376 - loss: 0.1227 - mae: 0.2252 - rmse: 0.3323 - smape: 0.4944 - val_ia: 0.7421 - val_loss: 0.0610 - val_mae: 0.1496 - val_rmse: 0.2105 - val_smape: 0.3848

Epoch 66/128

958/958 - 5s - 5ms/step - ia: 0.8383 - loss: 0.1207 - mae: 0.2242 - rmse: 0.3306 - smape: 0.4907 - val_ia: 0.7437 - val_loss: 0.0604 - val_mae: 0.1484 - val_rmse: 0.2094 - val_smape: 0.3836

Epoch 67/128

958/958 - 6s - 6ms/step - ia: 0.8378 - loss: 0.1222 - mae: 0.2249 - rmse: 0.3324 - smape: 0.4919 - val_ia: 0.7456 - val_loss: 0.0599 - val_mae: 0.1474 - val_rmse: 0.2088 - val_smape: 0.3821

Epoch 68/128

958/958 - 8s - 9ms/step - ia: 0.8373 - loss: 0.1243 - mae: 0.2252 - rmse: 0.3344 - smape: 0.4896 - val_ia: 0.7410 - val_loss: 0.0606 - val_mae: 0.1495 - val_rmse: 0.2101 - val_smape: 0.3849

Epoch 69/128

958/958 - 3s - 3ms/step - ia: 0.8390 - loss: 0.1202 - mae: 0.2236 - rmse: 0.3291 - smape: 0.4887 - val_ia: 0.7326 - val_loss: 0.0610 - val_mae: 0.1524 - val_rmse: 0.2125 - val_smape: 0.3892

Epoch 70/128

958/958 - 6s - 6ms/step - ia: 0.8373 - loss: 0.1235 - mae: 0.2254 - rmse: 0.3328 - smape: 0.4904 - val_ia: 0.7433 - val_loss: 0.0605 - val_mae: 0.1488 - val_rmse: 0.2096 - val_smape: 0.3836

Epoch 71/128

958/958 - 10s - 10ms/step - ia: 0.8381 - loss: 0.1213 - mae: 0.2242 - rmse: 0.3304 - smape: 0.4899 - val_ia: 0.7452 - val_loss: 0.0596 - val_mae: 0.1470 - val_rmse: 0.2086 - val_smape: 0.3817

Epoch 72/128

958/958 - 6s - 6ms/step - ia: 0.8358 - loss: 0.1230 - mae: 0.2271 - rmse: 0.3339 - smape: 0.4950 - val_ia: 0.7477 - val_loss: 0.0602 - val_mae: 0.1471 - val_rmse: 0.2086 - val_smape: 0.3809

Epoch 73/128

958/958 - 6s - 7ms/step - ia: 0.8376 - loss: 0.1234 - mae: 0.2242 - rmse: 0.3327 - smape: 0.4901 - val_ia: 0.7479 - val_loss: 0.0594 - val_mae: 0.1462 - val_rmse: 0.2080 - val_smape: 0.3801

Epoch 74/128

958/958 - 5s - 6ms/step - ia: 0.8390 - loss: 0.1194 - mae: 0.2233 - rmse: 0.3282 - smape: 0.4900 - val_ia: 0.7510 - val_loss: 0.0598 - val_mae: 0.1458 - val_rmse: 0.2076 - val_smape: 0.3795

Epoch 75/128

958/958 - 7s - 8ms/step - ia: 0.8398 - loss: 0.1208 - mae: 0.2227 - rmse: 0.3302 - smape: 0.4864 - val_ia: 0.7398 - val_loss: 0.0609 - val_mae: 0.1502 - val_rmse: 0.2108 - val_smape: 0.3849

Epoch 76/128

958/958 - 7s - 7ms/step - ia: 0.8385 - loss: 0.1212 - mae: 0.2235 - rmse: 0.3302 - smape: 0.4881 - val_ia: 0.7448 - val_loss: 0.0610 - val_mae: 0.1489 - val_rmse: 0.2098 - val_smape: 0.3824

Epoch 77/128

958/958 - 6s - 6ms/step - ia: 0.8384 - loss: 0.1186 - mae: 0.2235 - rmse: 0.3277 - smape: 0.4901 - val_ia: 0.7392 - val_loss: 0.0606 - val_mae: 0.1501 - val_rmse: 0.2105 - val_smape: 0.3849

Epoch 78/128

958/958 - 6s - 7ms/step - ia: 0.8399 - loss: 0.1172 - mae: 0.2220 - rmse: 0.3275 - smape: 0.4854 - val_ia: 0.7421 - val_loss: 0.0611 - val_mae: 0.1498 - val_rmse: 0.2104 - val_smape: 0.3837

Epoch 79/128

958/958 - 6s - 6ms/step - ia: 0.8401 - loss: 0.1170 - mae: 0.2219 - rmse: 0.3267 - smape: 0.4852 - val_ia: 0.7457 - val_loss: 0.0597 - val_mae: 0.1472 - val_rmse: 0.2085 - val_smape: 0.3811

Epoch 80/128

958/958 - 6s - 6ms/step - ia: 0.8388 - loss: 0.1225 - mae: 0.2236 - rmse: 0.3308 - smape: 0.4898 - val_ia: 0.7456 - val_loss: 0.0601 - val_mae: 0.1477 - val_rmse: 0.2089 - val_smape: 0.3816

Epoch 81/128

958/958 - 6s - 6ms/step - ia: 0.8396 - loss: 0.1181 - mae: 0.2227 - rmse: 0.3277 - smape: 0.4891 - val_ia: 0.7480 - val_loss: 0.0605 - val_mae: 0.1475 - val_rmse: 0.2089 - val_smape: 0.3813

Epoch 82/128

958/958 - 6s - 6ms/step - ia: 0.8404 - loss: 0.1220 - mae: 0.2216 - rmse: 0.3296 - smape: 0.4850 - val_ia: 0.7429 - val_loss: 0.0610 - val_mae: 0.1496 - val_rmse: 0.2102 - val_smape: 0.3839

Epoch 83/128

958/958 - 4s - 5ms/step - ia: 0.8392 - loss: 0.1203 - mae: 0.2232 - rmse: 0.3293 - smape: 0.4883 - val_ia: 0.7497 - val_loss: 0.0592 - val_mae: 0.1454 - val_rmse: 0.2074 - val_smape: 0.3787

Epoch 84/128

958/958 - 4s - 4ms/step - ia: 0.8383 - loss: 0.1182 - mae: 0.2231 - rmse: 0.3275 - smape: 0.4883 - val_ia: 0.7440 - val_loss: 0.0609 - val_mae: 0.1491 - val_rmse: 0.2100 - val_smape: 0.3822

Epoch 85/128

958/958 - 7s - 8ms/step - ia: 0.8388 - loss: 0.1232 - mae: 0.2238 - rmse: 0.3317 - smape: 0.4869 - val_ia: 0.7487 - val_loss: 0.0601 - val_mae: 0.1468 - val_rmse: 0.2082 - val_smape: 0.3794

Epoch 86/128

958/958 - 10s - 10ms/step - ia: 0.8406 - loss: 0.1189 - mae: 0.2210 - rmse: 0.3274 - smape: 0.4856 - val_ia: 0.7499 - val_loss: 0.0598 - val_mae: 0.1461 - val_rmse: 0.2075 - val_smape: 0.3794

Epoch 87/128

958/958 - 11s - 11ms/step - ia: 0.8397 - loss: 0.1197 - mae: 0.2225 - rmse: 0.3280 - smape: 0.4876 - val_ia: 0.7471 - val_loss: 0.0602 - val_mae: 0.1473 - val_rmse: 0.2086 - val_smape: 0.3796

Epoch 88/128

958/958 - 10s - 11ms/step - ia: 0.8398 - loss: 0.1182 - mae: 0.2228 - rmse: 0.3265 - smape: 0.4859 - val_ia: 0.7511 - val_loss: 0.0602 - val_mae: 0.1463 - val_rmse: 0.2079 - val_smape: 0.3789

Epoch 89/128

958/958 - 10s - 11ms/step - ia: 0.8396 - loss: 0.1175 - mae: 0.2223 - rmse: 0.3266 - smape: 0.4880 - val_ia: 0.7313 - val_loss: 0.0609 - val_mae: 0.1529 - val_rmse: 0.2126 - val_smape: 0.3900

Epoch 90/128

958/958 - 11s - 11ms/step - ia: 0.8389 - loss: 0.1201 - mae: 0.2226 - rmse: 0.3288 - smape: 0.4857 - val_ia: 0.7413 - val_loss: 0.0602 - val_mae: 0.1491 - val_rmse: 0.2097 - val_smape: 0.3834

Epoch 91/128

958/958 - 6s - 6ms/step - ia: 0.8385 - loss: 0.1197 - mae: 0.2238 - rmse: 0.3298 - smape: 0.4876 - val_ia: 0.7336 - val_loss: 0.0603 - val_mae: 0.1514 - val_rmse: 0.2114 - val_smape: 0.3880

Epoch 92/128

958/958 - 10s - 11ms/step - ia: 0.8396 - loss: 0.1185 - mae: 0.2224 - rmse: 0.3279 - smape: 0.4848 - val_ia: 0.7481 - val_loss: 0.0605 - val_mae: 0.1476 - val_rmse: 0.2087 - val_smape: 0.3805

Epoch 93/128

958/958 - 6s - 6ms/step - ia: 0.8390 - loss: 0.1199 - mae: 0.2238 - rmse: 0.3279 - smape: 0.4862 - val_ia: 0.7420 - val_loss: 0.0603 - val_mae: 0.1491 - val_rmse: 0.2097 - val_smape: 0.3829

Epoch 94/128

958/958 - 11s - 11ms/step - ia: 0.8412 - loss: 0.1151 - mae: 0.2203 - rmse: 0.3230 - smape: 0.4841 - val_ia: 0.7454 - val_loss: 0.0611 - val_mae: 0.1490 - val_rmse: 0.2098 - val_smape: 0.3821

Epoch 95/128

958/958 - 10s - 11ms/step - ia: 0.8401 - loss: 0.1187 - mae: 0.2218 - rmse: 0.3273 - smape: 0.4846 - val_ia: 0.7532 - val_loss: 0.0590 - val_mae: 0.1443 - val_rmse: 0.2064 - val_smape: 0.3764

Epoch 96/128

958/958 - 6s - 6ms/step - ia: 0.8395 - loss: 0.1198 - mae: 0.2231 - rmse: 0.3293 - smape: 0.4874 - val_ia: 0.7402 - val_loss: 0.0608 - val_mae: 0.1502 - val_rmse: 0.2105 - val_smape: 0.3842

Epoch 97/128

958/958 - 6s - 6ms/step - ia: 0.8381 - loss: 0.1219 - mae: 0.2241 - rmse: 0.3309 - smape: 0.4874 - val_ia: 0.7540 - val_loss: 0.0598 - val_mae: 0.1450 - val_rmse: 0.2069 - val_smape: 0.3767

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 26s - 14ms/step - ia: 0.7488 - loss: 0.2298 - mae: 0.3236 - rmse: 0.4334 - smape: 0.6965 - val_ia: 0.5848 - val_loss: 0.0806 - val_mae: 0.1781 - val_rmse: 0.2336 - val_smape: 0.4492

Epoch 2/128

1916/1916 - 17s - 9ms/step - ia: 0.8334 - loss: 0.1122 - mae: 0.2232 - rmse: 0.3105 - smape: 0.5206 - val_ia: 0.5611 - val_loss: 0.0751 - val_mae: 0.1878 - val_rmse: 0.2381 - val_smape: 0.4745

Epoch 3/128

1916/1916 - 16s - 9ms/step - ia: 0.8499 - loss: 0.0955 - mae: 0.2011 - rmse: 0.2824 - smape: 0.4776 - val_ia: 0.6271 - val_loss: 0.0654 - val_mae: 0.1548 - val_rmse: 0.2097 - val_smape: 0.3987

Epoch 4/128

1916/1916 - 22s - 11ms/step - ia: 0.8605 - loss: 0.0857 - mae: 0.1877 - rmse: 0.2671 - smape: 0.4537 - val_ia: 0.6686 - val_loss: 0.0586 - val_mae: 0.1386 - val_rmse: 0.1926 - val_smape: 0.3699

Epoch 5/128

1916/1916 - 17s - 9ms/step - ia: 0.8660 - loss: 0.0820 - mae: 0.1809 - rmse: 0.2592 - smape: 0.4390 - val_ia: 0.6373 - val_loss: 0.0605 - val_mae: 0.1489 - val_rmse: 0.2012 - val_smape: 0.3906

Epoch 6/128

1916/1916 - 16s - 8ms/step - ia: 0.8695 - loss: 0.0788 - mae: 0.1766 - rmse: 0.2547 - smape: 0.4268 - val_ia: 0.6802 - val_loss: 0.0573 - val_mae: 0.1356 - val_rmse: 0.1888 - val_smape: 0.3661

Epoch 7/128

1916/1916 - 16s - 8ms/step - ia: 0.8722 - loss: 0.0778 - mae: 0.1734 - rmse: 0.2515 - smape: 0.4208 - val_ia: 0.6733 - val_loss: 0.0599 - val_mae: 0.1429 - val_rmse: 0.1957 - val_smape: 0.3790

Epoch 8/128

1916/1916 - 16s - 8ms/step - ia: 0.8742 - loss: 0.0765 - mae: 0.1706 - rmse: 0.2490 - smape: 0.4137 - val_ia: 0.6588 - val_loss: 0.0565 - val_mae: 0.1396 - val_rmse: 0.1918 - val_smape: 0.3682

Epoch 9/128

1916/1916 - 18s - 10ms/step - ia: 0.8752 - loss: 0.0754 - mae: 0.1692 - rmse: 0.2471 - smape: 0.4127 - val_ia: 0.6523 - val_loss: 0.0572 - val_mae: 0.1420 - val_rmse: 0.1937 - val_smape: 0.3721

Epoch 10/128

1916/1916 - 18s - 9ms/step - ia: 0.8765 - loss: 0.0737 - mae: 0.1675 - rmse: 0.2446 - smape: 0.4107 - val_ia: 0.6992 - val_loss: 0.0562 - val_mae: 0.1314 - val_rmse: 0.1856 - val_smape: 0.3530

Epoch 11/128

1916/1916 - 17s - 9ms/step - ia: 0.8779 - loss: 0.0744 - mae: 0.1668 - rmse: 0.2449 - smape: 0.4062 - val_ia: 0.6899 - val_loss: 0.0561 - val_mae: 0.1312 - val_rmse: 0.1862 - val_smape: 0.3549

Epoch 12/128

1916/1916 - 16s - 9ms/step - ia: 0.8781 - loss: 0.0730 - mae: 0.1654 - rmse: 0.2428 - smape: 0.4026 - val_ia: 0.6580 - val_loss: 0.0580 - val_mae: 0.1421 - val_rmse: 0.1928 - val_smape: 0.3674

Epoch 13/128

1916/1916 - 17s - 9ms/step - ia: 0.8793 - loss: 0.0731 - mae: 0.1639 - rmse: 0.2423 - smape: 0.3986 - val_ia: 0.6670 - val_loss: 0.0581 - val_mae: 0.1400 - val_rmse: 0.1922 - val_smape: 0.3666

Epoch 14/128

1916/1916 - 16s - 9ms/step - ia: 0.8786 - loss: 0.0733 - mae: 0.1649 - rmse: 0.2429 - smape: 0.4002 - val_ia: 0.6840 - val_loss: 0.0584 - val_mae: 0.1376 - val_rmse: 0.1897 - val_smape: 0.3647

Epoch 15/128

1916/1916 - 16s - 8ms/step - ia: 0.8807 - loss: 0.0717 - mae: 0.1623 - rmse: 0.2404 - smape: 0.3961 - val_ia: 0.6652 - val_loss: 0.0564 - val_mae: 0.1373 - val_rmse: 0.1910 - val_smape: 0.3666

Epoch 16/128

1916/1916 - 17s - 9ms/step - ia: 0.8790 - loss: 0.0725 - mae: 0.1639 - rmse: 0.2421 - smape: 0.3991 - val_ia: 0.6932 - val_loss: 0.0553 - val_mae: 0.1311 - val_rmse: 0.1859 - val_smape: 0.3559

Epoch 17/128

1916/1916 - 13s - 7ms/step - ia: 0.8807 - loss: 0.0711 - mae: 0.1624 - rmse: 0.2398 - smape: 0.3959 - val_ia: 0.6651 - val_loss: 0.0562 - val_mae: 0.1380 - val_rmse: 0.1914 - val_smape: 0.3695

Epoch 18/128

1916/1916 - 12s - 6ms/step - ia: 0.8805 - loss: 0.0713 - mae: 0.1620 - rmse: 0.2403 - smape: 0.3963 - val_ia: 0.6797 - val_loss: 0.0563 - val_mae: 0.1350 - val_rmse: 0.1873 - val_smape: 0.3570

Epoch 19/128

1916/1916 - 13s - 7ms/step - ia: 0.8802 - loss: 0.0714 - mae: 0.1619 - rmse: 0.2391 - smape: 0.3970 - val_ia: 0.6782 - val_loss: 0.0569 - val_mae: 0.1365 - val_rmse: 0.1886 - val_smape: 0.3586

Epoch 20/128

1916/1916 - 13s - 7ms/step - ia: 0.8810 - loss: 0.0705 - mae: 0.1615 - rmse: 0.2385 - smape: 0.3964 - val_ia: 0.6966 - val_loss: 0.0556 - val_mae: 0.1322 - val_rmse: 0.1858 - val_smape: 0.3553

Epoch 21/128

1916/1916 - 12s - 6ms/step - ia: 0.8818 - loss: 0.0707 - mae: 0.1610 - rmse: 0.2390 - smape: 0.3923 - val_ia: 0.6964 - val_loss: 0.0562 - val_mae: 0.1319 - val_rmse: 0.1852 - val_smape: 0.3511

Epoch 22/128

1916/1916 - 16s - 8ms/step - ia: 0.8821 - loss: 0.0699 - mae: 0.1601 - rmse: 0.2370 - smape: 0.3939 - val_ia: 0.6944 - val_loss: 0.0568 - val_mae: 0.1337 - val_rmse: 0.1869 - val_smape: 0.3548

Epoch 23/128

1916/1916 - 14s - 7ms/step - ia: 0.8824 - loss: 0.0706 - mae: 0.1612 - rmse: 0.2381 - smape: 0.3969 - val_ia: 0.6645 - val_loss: 0.0559 - val_mae: 0.1380 - val_rmse: 0.1900 - val_smape: 0.3658

Epoch 24/128

1916/1916 - 19s - 10ms/step - ia: 0.8818 - loss: 0.0697 - mae: 0.1607 - rmse: 0.2370 - smape: 0.3953 - val_ia: 0.7015 - val_loss: 0.0551 - val_mae: 0.1301 - val_rmse: 0.1840 - val_smape: 0.3502

Epoch 25/128

1916/1916 - 12s - 6ms/step - ia: 0.8824 - loss: 0.0700 - mae: 0.1602 - rmse: 0.2368 - smape: 0.3946 - val_ia: 0.6690 - val_loss: 0.0615 - val_mae: 0.1437 - val_rmse: 0.1942 - val_smape: 0.3651

Epoch 26/128

1916/1916 - 12s - 6ms/step - ia: 0.8812 - loss: 0.0706 - mae: 0.1607 - rmse: 0.2388 - smape: 0.3937 - val_ia: 0.6876 - val_loss: 0.0549 - val_mae: 0.1319 - val_rmse: 0.1850 - val_smape: 0.3528

Epoch 27/128

1916/1916 - 12s - 6ms/step - ia: 0.8824 - loss: 0.0688 - mae: 0.1597 - rmse: 0.2362 - smape: 0.3914 - val_ia: 0.7004 - val_loss: 0.0541 - val_mae: 0.1280 - val_rmse: 0.1822 - val_smape: 0.3464

Epoch 28/128

1916/1916 - 12s - 6ms/step - ia: 0.8828 - loss: 0.0693 - mae: 0.1596 - rmse: 0.2364 - smape: 0.3921 - val_ia: 0.6813 - val_loss: 0.0544 - val_mae: 0.1329 - val_rmse: 0.1851 - val_smape: 0.3553

Epoch 29/128

1916/1916 - 12s - 6ms/step - ia: 0.8820 - loss: 0.0701 - mae: 0.1603 - rmse: 0.2372 - smape: 0.3937 - val_ia: 0.6786 - val_loss: 0.0552 - val_mae: 0.1340 - val_rmse: 0.1863 - val_smape: 0.3556

Epoch 30/128

1916/1916 - 12s - 6ms/step - ia: 0.8833 - loss: 0.0688 - mae: 0.1589 - rmse: 0.2352 - smape: 0.3915 - val_ia: 0.6870 - val_loss: 0.0545 - val_mae: 0.1316 - val_rmse: 0.1845 - val_smape: 0.3521

Epoch 31/128

1916/1916 - 12s - 6ms/step - ia: 0.8827 - loss: 0.0701 - mae: 0.1600 - rmse: 0.2371 - smape: 0.3939 - val_ia: 0.7030 - val_loss: 0.0548 - val_mae: 0.1294 - val_rmse: 0.1838 - val_smape: 0.3486

Epoch 32/128

1916/1916 - 12s - 6ms/step - ia: 0.8836 - loss: 0.0683 - mae: 0.1585 - rmse: 0.2341 - smape: 0.3899 - val_ia: 0.6728 - val_loss: 0.0603 - val_mae: 0.1421 - val_rmse: 0.1929 - val_smape: 0.3639

Epoch 33/128

1916/1916 - 12s - 6ms/step - ia: 0.8825 - loss: 0.0687 - mae: 0.1593 - rmse: 0.2365 - smape: 0.3912 - val_ia: 0.6776 - val_loss: 0.0544 - val_mae: 0.1336 - val_rmse: 0.1864 - val_smape: 0.3589

Epoch 34/128

1916/1916 - 12s - 6ms/step - ia: 0.8832 - loss: 0.0679 - mae: 0.1588 - rmse: 0.2342 - smape: 0.3895 - val_ia: 0.6866 - val_loss: 0.0539 - val_mae: 0.1317 - val_rmse: 0.1851 - val_smape: 0.3582

Epoch 35/128

1916/1916 - 12s - 6ms/step - ia: 0.8830 - loss: 0.0691 - mae: 0.1592 - rmse: 0.2358 - smape: 0.3899 - val_ia: 0.7043 - val_loss: 0.0531 - val_mae: 0.1268 - val_rmse: 0.1806 - val_smape: 0.3445

Epoch 36/128

1916/1916 - 12s - 6ms/step - ia: 0.8839 - loss: 0.0677 - mae: 0.1578 - rmse: 0.2344 - smape: 0.3870 - val_ia: 0.6930 - val_loss: 0.0537 - val_mae: 0.1299 - val_rmse: 0.1832 - val_smape: 0.3523

Epoch 37/128

1916/1916 - 12s - 6ms/step - ia: 0.8837 - loss: 0.0681 - mae: 0.1587 - rmse: 0.2343 - smape: 0.3893 - val_ia: 0.7013 - val_loss: 0.0542 - val_mae: 0.1294 - val_rmse: 0.1833 - val_smape: 0.3511

Epoch 38/128

1916/1916 - 12s - 6ms/step - ia: 0.8837 - loss: 0.0697 - mae: 0.1589 - rmse: 0.2360 - smape: 0.3905 - val_ia: 0.6931 - val_loss: 0.0570 - val_mae: 0.1349 - val_rmse: 0.1868 - val_smape: 0.3528

Epoch 39/128

1916/1916 - 20s - 11ms/step - ia: 0.8834 - loss: 0.0673 - mae: 0.1579 - rmse: 0.2330 - smape: 0.3883 - val_ia: 0.6900 - val_loss: 0.0533 - val_mae: 0.1301 - val_rmse: 0.1831 - val_smape: 0.3513

Epoch 40/128

1916/1916 - 12s - 6ms/step - ia: 0.8846 - loss: 0.0670 - mae: 0.1570 - rmse: 0.2324 - smape: 0.3869 - val_ia: 0.6992 - val_loss: 0.0550 - val_mae: 0.1312 - val_rmse: 0.1864 - val_smape: 0.3565

Epoch 41/128

1916/1916 - 12s - 6ms/step - ia: 0.8856 - loss: 0.0658 - mae: 0.1566 - rmse: 0.2314 - smape: 0.3865 - val_ia: 0.6854 - val_loss: 0.0535 - val_mae: 0.1315 - val_rmse: 0.1835 - val_smape: 0.3540

Epoch 42/128

1916/1916 - 13s - 7ms/step - ia: 0.8845 - loss: 0.0677 - mae: 0.1579 - rmse: 0.2338 - smape: 0.3871 - val_ia: 0.6893 - val_loss: 0.0531 - val_mae: 0.1299 - val_rmse: 0.1833 - val_smape: 0.3519

Epoch 43/128

1916/1916 - 20s - 10ms/step - ia: 0.8838 - loss: 0.0672 - mae: 0.1577 - rmse: 0.2333 - smape: 0.3891 - val_ia: 0.7069 - val_loss: 0.0529 - val_mae: 0.1269 - val_rmse: 0.1808 - val_smape: 0.3445

Epoch 44/128

1916/1916 - 12s - 6ms/step - ia: 0.8842 - loss: 0.0672 - mae: 0.1573 - rmse: 0.2330 - smape: 0.3858 - val_ia: 0.6818 - val_loss: 0.0534 - val_mae: 0.1320 - val_rmse: 0.1840 - val_smape: 0.3538

Epoch 45/128

1916/1916 - 12s - 6ms/step - ia: 0.8843 - loss: 0.0667 - mae: 0.1571 - rmse: 0.2327 - smape: 0.3880 - val_ia: 0.6839 - val_loss: 0.0536 - val_mae: 0.1318 - val_rmse: 0.1844 - val_smape: 0.3540

Epoch 46/128

1916/1916 - 12s - 6ms/step - ia: 0.8846 - loss: 0.0667 - mae: 0.1570 - rmse: 0.2321 - smape: 0.3861 - val_ia: 0.7018 - val_loss: 0.0532 - val_mae: 0.1283 - val_rmse: 0.1808 - val_smape: 0.3452

Epoch 47/128

1916/1916 - 21s - 11ms/step - ia: 0.8843 - loss: 0.0666 - mae: 0.1571 - rmse: 0.2322 - smape: 0.3867 - val_ia: 0.6535 - val_loss: 0.0548 - val_mae: 0.1404 - val_rmse: 0.1916 - val_smape: 0.3710

Epoch 48/128

1916/1916 - 18s - 9ms/step - ia: 0.8843 - loss: 0.0672 - mae: 0.1569 - rmse: 0.2321 - smape: 0.3868 - val_ia: 0.6948 - val_loss: 0.0579 - val_mae: 0.1361 - val_rmse: 0.1871 - val_smape: 0.3520

Epoch 49/128

1916/1916 - 10s - 5ms/step - ia: 0.8846 - loss: 0.0669 - mae: 0.1569 - rmse: 0.2319 - smape: 0.3862 - val_ia: 0.6772 - val_loss: 0.0542 - val_mae: 0.1343 - val_rmse: 0.1858 - val_smape: 0.3554

Epoch 50/128

1916/1916 - 12s - 6ms/step - ia: 0.8840 - loss: 0.0673 - mae: 0.1575 - rmse: 0.2334 - smape: 0.3875 - val_ia: 0.6693 - val_loss: 0.0548 - val_mae: 0.1365 - val_rmse: 0.1878 - val_smape: 0.3585

Epoch 51/128

1916/1916 - 12s - 6ms/step - ia: 0.8857 - loss: 0.0665 - mae: 0.1562 - rmse: 0.2317 - smape: 0.3860 - val_ia: 0.6947 - val_loss: 0.0528 - val_mae: 0.1291 - val_rmse: 0.1822 - val_smape: 0.3505

Epoch 52/128

1916/1916 - 12s - 6ms/step - ia: 0.8848 - loss: 0.0656 - mae: 0.1560 - rmse: 0.2302 - smape: 0.3846 - val_ia: 0.6806 - val_loss: 0.0537 - val_mae: 0.1335 - val_rmse: 0.1856 - val_smape: 0.3609

Epoch 53/128

1916/1916 - 20s - 10ms/step - ia: 0.8841 - loss: 0.0668 - mae: 0.1578 - rmse: 0.2334 - smape: 0.3865 - val_ia: 0.6925 - val_loss: 0.0543 - val_mae: 0.1318 - val_rmse: 0.1840 - val_smape: 0.3502

Epoch 54/128

1916/1916 - 9s - 5ms/step - ia: 0.8847 - loss: 0.0663 - mae: 0.1565 - rmse: 0.2321 - smape: 0.3846 - val_ia: 0.7038 - val_loss: 0.0527 - val_mae: 0.1270 - val_rmse: 0.1807 - val_smape: 0.3437

Epoch 55/128

1916/1916 - 11s - 6ms/step - ia: 0.8851 - loss: 0.0655 - mae: 0.1564 - rmse: 0.2304 - smape: 0.3835 - val_ia: 0.6957 - val_loss: 0.0542 - val_mae: 0.1306 - val_rmse: 0.1847 - val_smape: 0.3530

Epoch 56/128

1916/1916 - 21s - 11ms/step - ia: 0.8857 - loss: 0.0653 - mae: 0.1557 - rmse: 0.2300 - smape: 0.3832 - val_ia: 0.6817 - val_loss: 0.0531 - val_mae: 0.1323 - val_rmse: 0.1839 - val_smape: 0.3533

Epoch 57/128

1916/1916 - 12s - 6ms/step - ia: 0.8854 - loss: 0.0658 - mae: 0.1556 - rmse: 0.2300 - smape: 0.3856 - val_ia: 0.6541 - val_loss: 0.0566 - val_mae: 0.1428 - val_rmse: 0.1922 - val_smape: 0.3662

Epoch 58/128

1916/1916 - 12s - 6ms/step - ia: 0.8863 - loss: 0.0657 - mae: 0.1550 - rmse: 0.2297 - smape: 0.3834 - val_ia: 0.6982 - val_loss: 0.0526 - val_mae: 0.1286 - val_rmse: 0.1807 - val_smape: 0.3457

Epoch 59/128

1916/1916 - 12s - 6ms/step - ia: 0.8864 - loss: 0.0652 - mae: 0.1555 - rmse: 0.2304 - smape: 0.3821 - val_ia: 0.6792 - val_loss: 0.0538 - val_mae: 0.1340 - val_rmse: 0.1861 - val_smape: 0.3597

Epoch 60/128

1916/1916 - 20s - 11ms/step - ia: 0.8857 - loss: 0.0651 - mae: 0.1554 - rmse: 0.2296 - smape: 0.3837 - val_ia: 0.7001 - val_loss: 0.0525 - val_mae: 0.1281 - val_rmse: 0.1805 - val_smape: 0.3476

Epoch 61/128

1916/1916 - 12s - 6ms/step - ia: 0.8860 - loss: 0.0645 - mae: 0.1546 - rmse: 0.2287 - smape: 0.3836 - val_ia: 0.7045 - val_loss: 0.0525 - val_mae: 0.1273 - val_rmse: 0.1802 - val_smape: 0.3439

Epoch 62/128

1916/1916 - 21s - 11ms/step - ia: 0.8859 - loss: 0.0655 - mae: 0.1557 - rmse: 0.2305 - smape: 0.3839 - val_ia: 0.6781 - val_loss: 0.0525 - val_mae: 0.1325 - val_rmse: 0.1837 - val_smape: 0.3528

Epoch 63/128

1916/1916 - 12s - 6ms/step - ia: 0.8863 - loss: 0.0646 - mae: 0.1550 - rmse: 0.2294 - smape: 0.3818 - val_ia: 0.6871 - val_loss: 0.0528 - val_mae: 0.1307 - val_rmse: 0.1826 - val_smape: 0.3496

Epoch 64/128

1916/1916 - 18s - 9ms/step - ia: 0.8856 - loss: 0.0658 - mae: 0.1556 - rmse: 0.2302 - smape: 0.3831 - val_ia: 0.6844 - val_loss: 0.0534 - val_mae: 0.1318 - val_rmse: 0.1834 - val_smape: 0.3501

Epoch 65/128

1916/1916 - 11s - 6ms/step - ia: 0.8862 - loss: 0.0648 - mae: 0.1550 - rmse: 0.2297 - smape: 0.3828 - val_ia: 0.7030 - val_loss: 0.0523 - val_mae: 0.1277 - val_rmse: 0.1800 - val_smape: 0.3463

Epoch 66/128

1916/1916 - 12s - 6ms/step - ia: 0.8861 - loss: 0.0651 - mae: 0.1553 - rmse: 0.2297 - smape: 0.3830 - val_ia: 0.7038 - val_loss: 0.0524 - val_mae: 0.1273 - val_rmse: 0.1805 - val_smape: 0.3448

Epoch 67/128

1916/1916 - 12s - 6ms/step - ia: 0.8864 - loss: 0.0643 - mae: 0.1546 - rmse: 0.2283 - smape: 0.3822 - val_ia: 0.6994 - val_loss: 0.0536 - val_mae: 0.1300 - val_rmse: 0.1818 - val_smape: 0.3498

Epoch 68/128

1916/1916 - 12s - 6ms/step - ia: 0.8854 - loss: 0.0643 - mae: 0.1554 - rmse: 0.2294 - smape: 0.3822 - val_ia: 0.6967 - val_loss: 0.0527 - val_mae: 0.1290 - val_rmse: 0.1825 - val_smape: 0.3509

Epoch 69/128

1916/1916 - 12s - 6ms/step - ia: 0.8869 - loss: 0.0641 - mae: 0.1541 - rmse: 0.2285 - smape: 0.3815 - val_ia: 0.6682 - val_loss: 0.0534 - val_mae: 0.1355 - val_rmse: 0.1871 - val_smape: 0.3602

Epoch 70/128

1916/1916 - 12s - 6ms/step - ia: 0.8866 - loss: 0.0646 - mae: 0.1549 - rmse: 0.2293 - smape: 0.3828 - val_ia: 0.7052 - val_loss: 0.0525 - val_mae: 0.1277 - val_rmse: 0.1806 - val_smape: 0.3452

Epoch 71/128

1916/1916 - 12s - 6ms/step - ia: 0.8860 - loss: 0.0646 - mae: 0.1551 - rmse: 0.2294 - smape: 0.3814 - val_ia: 0.6702 - val_loss: 0.0538 - val_mae: 0.1360 - val_rmse: 0.1878 - val_smape: 0.3641

Epoch 72/128

1916/1916 - 12s - 6ms/step - ia: 0.8862 - loss: 0.0636 - mae: 0.1543 - rmse: 0.2282 - smape: 0.3815 - val_ia: 0.6966 - val_loss: 0.0531 - val_mae: 0.1300 - val_rmse: 0.1813 - val_smape: 0.3489

Epoch 73/128

1916/1916 - 12s - 6ms/step - ia: 0.8859 - loss: 0.0650 - mae: 0.1554 - rmse: 0.2294 - smape: 0.3841 - val_ia: 0.6912 - val_loss: 0.0546 - val_mae: 0.1329 - val_rmse: 0.1844 - val_smape: 0.3512

Epoch 74/128

1916/1916 - 12s - 6ms/step - ia: 0.8863 - loss: 0.0633 - mae: 0.1544 - rmse: 0.2272 - smape: 0.3841 - val_ia: 0.7030 - val_loss: 0.0524 - val_mae: 0.1287 - val_rmse: 0.1814 - val_smape: 0.3439

Epoch 75/128

1916/1916 - 12s - 6ms/step - ia: 0.8868 - loss: 0.0637 - mae: 0.1539 - rmse: 0.2277 - smape: 0.3821 - val_ia: 0.6961 - val_loss: 0.0527 - val_mae: 0.1295 - val_rmse: 0.1812 - val_smape: 0.3476

Epoch 76/128

1916/1916 - 12s - 6ms/step - ia: 0.8866 - loss: 0.0636 - mae: 0.1541 - rmse: 0.2278 - smape: 0.3813 - val_ia: 0.6845 - val_loss: 0.0532 - val_mae: 0.1321 - val_rmse: 0.1844 - val_smape: 0.3547

Epoch 77/128

1916/1916 - 12s - 6ms/step - ia: 0.8867 - loss: 0.0633 - mae: 0.1542 - rmse: 0.2275 - smape: 0.3834 - val_ia: 0.7025 - val_loss: 0.0532 - val_mae: 0.1295 - val_rmse: 0.1820 - val_smape: 0.3476

Epoch 78/128

1916/1916 - 12s - 6ms/step - ia: 0.8868 - loss: 0.0634 - mae: 0.1537 - rmse: 0.2272 - smape: 0.3817 - val_ia: 0.6979 - val_loss: 0.0519 - val_mae: 0.1281 - val_rmse: 0.1802 - val_smape: 0.3490

Epoch 79/128

1916/1916 - 12s - 6ms/step - ia: 0.8861 - loss: 0.0636 - mae: 0.1549 - rmse: 0.2277 - smape: 0.3818 - val_ia: 0.7026 - val_loss: 0.0528 - val_mae: 0.1289 - val_rmse: 0.1815 - val_smape: 0.3482

Epoch 80/128

1916/1916 - 12s - 6ms/step - ia: 0.8866 - loss: 0.0629 - mae: 0.1539 - rmse: 0.2268 - smape: 0.3819 - val_ia: 0.6924 - val_loss: 0.0538 - val_mae: 0.1311 - val_rmse: 0.1826 - val_smape: 0.3507

Epoch 81/128

1916/1916 - 12s - 6ms/step - ia: 0.8867 - loss: 0.0637 - mae: 0.1537 - rmse: 0.2281 - smape: 0.3808 - val_ia: 0.7082 - val_loss: 0.0522 - val_mae: 0.1266 - val_rmse: 0.1796 - val_smape: 0.3419

Epoch 82/128

1916/1916 - 20s - 11ms/step - ia: 0.8863 - loss: 0.0635 - mae: 0.1543 - rmse: 0.2272 - smape: 0.3805 - val_ia: 0.7060 - val_loss: 0.0522 - val_mae: 0.1272 - val_rmse: 0.1803 - val_smape: 0.3454

Epoch 83/128

1916/1916 - 21s - 11ms/step - ia: 0.8876 - loss: 0.0628 - mae: 0.1534 - rmse: 0.2262 - smape: 0.3796 - val_ia: 0.7064 - val_loss: 0.0521 - val_mae: 0.1266 - val_rmse: 0.1790 - val_smape: 0.3446

Epoch 84/128

1916/1916 - 12s - 6ms/step - ia: 0.8868 - loss: 0.0627 - mae: 0.1539 - rmse: 0.2265 - smape: 0.3816 - val_ia: 0.7048 - val_loss: 0.0526 - val_mae: 0.1282 - val_rmse: 0.1803 - val_smape: 0.3453

Epoch 85/128

1916/1916 - 20s - 11ms/step - ia: 0.8867 - loss: 0.0627 - mae: 0.1539 - rmse: 0.2273 - smape: 0.3808 - val_ia: 0.7046 - val_loss: 0.0524 - val_mae: 0.1277 - val_rmse: 0.1797 - val_smape: 0.3450

Epoch 86/128

1916/1916 - 12s - 6ms/step - ia: 0.8870 - loss: 0.0627 - mae: 0.1541 - rmse: 0.2274 - smape: 0.3805 - val_ia: 0.6901 - val_loss: 0.0533 - val_mae: 0.1307 - val_rmse: 0.1822 - val_smape: 0.3462

Epoch 87/128

1916/1916 - 12s - 6ms/step - ia: 0.8865 - loss: 0.0630 - mae: 0.1540 - rmse: 0.2277 - smape: 0.3795 - val_ia: 0.7059 - val_loss: 0.0525 - val_mae: 0.1265 - val_rmse: 0.1800 - val_smape: 0.3425

Epoch 88/128

1916/1916 - 12s - 6ms/step - ia: 0.8863 - loss: 0.0626 - mae: 0.1540 - rmse: 0.2270 - smape: 0.3791 - val_ia: 0.7003 - val_loss: 0.0523 - val_mae: 0.1281 - val_rmse: 0.1801 - val_smape: 0.3465

Epoch 89/128

1916/1916 - 20s - 11ms/step - ia: 0.8870 - loss: 0.0620 - mae: 0.1533 - rmse: 0.2258 - smape: 0.3794 - val_ia: 0.6823 - val_loss: 0.0529 - val_mae: 0.1316 - val_rmse: 0.1839 - val_smape: 0.3525

Epoch 90/128

1916/1916 - 12s - 6ms/step - ia: 0.8875 - loss: 0.0630 - mae: 0.1540 - rmse: 0.2270 - smape: 0.3794 - val_ia: 0.6998 - val_loss: 0.0529 - val_mae: 0.1297 - val_rmse: 0.1827 - val_smape: 0.3455

Epoch 91/128

1916/1916 - 12s - 6ms/step - ia: 0.8878 - loss: 0.0622 - mae: 0.1528 - rmse: 0.2260 - smape: 0.3796 - val_ia: 0.7025 - val_loss: 0.0525 - val_mae: 0.1277 - val_rmse: 0.1808 - val_smape: 0.3476

Epoch 92/128

1916/1916 - 12s - 6ms/step - ia: 0.8864 - loss: 0.0623 - mae: 0.1538 - rmse: 0.2264 - smape: 0.3806 - val_ia: 0.7094 - val_loss: 0.0527 - val_mae: 0.1266 - val_rmse: 0.1802 - val_smape: 0.3419

Epoch 93/128

1916/1916 - 12s - 6ms/step - ia: 0.8882 - loss: 0.0628 - mae: 0.1531 - rmse: 0.2260 - smape: 0.3787 - val_ia: 0.7077 - val_loss: 0.0522 - val_mae: 0.1263 - val_rmse: 0.1792 - val_smape: 0.3424

Epoch 93: early stopping

Restoring model weights from the end of the best epoch: 78.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:35 705ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 31s - 16ms/step - ia: 0.7461 - loss: 0.2367 - mae: 0.3240 - rmse: 0.4339 - smape: 0.6931 - val_ia: 0.5801 - val_loss: 0.0757 - val_mae: 0.1753 - val_rmse: 0.2288 - val_smape: 0.4410

Epoch 2/128

1916/1916 - 23s - 12ms/step - ia: 0.8360 - loss: 0.1105 - mae: 0.2204 - rmse: 0.3071 - smape: 0.5140 - val_ia: 0.6341 - val_loss: 0.0652 - val_mae: 0.1539 - val_rmse: 0.2073 - val_smape: 0.4032

Epoch 3/128

1916/1916 - 23s - 12ms/step - ia: 0.8494 - loss: 0.0969 - mae: 0.2023 - rmse: 0.2869 - smape: 0.4754 - val_ia: 0.6519 - val_loss: 0.0607 - val_mae: 0.1452 - val_rmse: 0.1987 - val_smape: 0.3798

Epoch 4/128

1916/1916 - 22s - 12ms/step - ia: 0.8580 - loss: 0.0895 - mae: 0.1921 - rmse: 0.2736 - smape: 0.4580 - val_ia: 0.6254 - val_loss: 0.0597 - val_mae: 0.1518 - val_rmse: 0.2024 - val_smape: 0.3877

Epoch 5/128

1916/1916 - 41s - 21ms/step - ia: 0.8623 - loss: 0.0855 - mae: 0.1857 - rmse: 0.2656 - smape: 0.4429 - val_ia: 0.6732 - val_loss: 0.0565 - val_mae: 0.1371 - val_rmse: 0.1904 - val_smape: 0.3667

Epoch 6/128

1916/1916 - 46s - 24ms/step - ia: 0.8644 - loss: 0.0846 - mae: 0.1838 - rmse: 0.2648 - smape: 0.4365 - val_ia: 0.6709 - val_loss: 0.0573 - val_mae: 0.1375 - val_rmse: 0.1922 - val_smape: 0.3667

Epoch 7/128

1916/1916 - 24s - 12ms/step - ia: 0.8679 - loss: 0.0830 - mae: 0.1798 - rmse: 0.2607 - smape: 0.4288 - val_ia: 0.6732 - val_loss: 0.0560 - val_mae: 0.1368 - val_rmse: 0.1896 - val_smape: 0.3622

Epoch 8/128

1916/1916 - 23s - 12ms/step - ia: 0.8697 - loss: 0.0806 - mae: 0.1773 - rmse: 0.2567 - smape: 0.4224 - val_ia: 0.6629 - val_loss: 0.0556 - val_mae: 0.1381 - val_rmse: 0.1896 - val_smape: 0.3646

Epoch 9/128

1916/1916 - 41s - 21ms/step - ia: 0.8715 - loss: 0.0792 - mae: 0.1749 - rmse: 0.2540 - smape: 0.4210 - val_ia: 0.6871 - val_loss: 0.0556 - val_mae: 0.1331 - val_rmse: 0.1875 - val_smape: 0.3562

Epoch 10/128

1916/1916 - 23s - 12ms/step - ia: 0.8732 - loss: 0.0779 - mae: 0.1729 - rmse: 0.2519 - smape: 0.4162 - val_ia: 0.6884 - val_loss: 0.0552 - val_mae: 0.1313 - val_rmse: 0.1861 - val_smape: 0.3536

Epoch 11/128

1916/1916 - 24s - 12ms/step - ia: 0.8734 - loss: 0.0774 - mae: 0.1719 - rmse: 0.2511 - smape: 0.4130 - val_ia: 0.6857 - val_loss: 0.0547 - val_mae: 0.1334 - val_rmse: 0.1862 - val_smape: 0.3596

Epoch 12/128

1916/1916 - 24s - 12ms/step - ia: 0.8745 - loss: 0.0758 - mae: 0.1705 - rmse: 0.2489 - smape: 0.4082 - val_ia: 0.6730 - val_loss: 0.0537 - val_mae: 0.1335 - val_rmse: 0.1863 - val_smape: 0.3581

Epoch 13/128

1916/1916 - 40s - 21ms/step - ia: 0.8750 - loss: 0.0759 - mae: 0.1698 - rmse: 0.2482 - smape: 0.4099 - val_ia: 0.6899 - val_loss: 0.0559 - val_mae: 0.1339 - val_rmse: 0.1897 - val_smape: 0.3540

Epoch 14/128

1916/1916 - 23s - 12ms/step - ia: 0.8750 - loss: 0.0748 - mae: 0.1689 - rmse: 0.2472 - smape: 0.4071 - val_ia: 0.6965 - val_loss: 0.0537 - val_mae: 0.1298 - val_rmse: 0.1839 - val_smape: 0.3502

Epoch 15/128

1916/1916 - 24s - 12ms/step - ia: 0.8772 - loss: 0.0755 - mae: 0.1680 - rmse: 0.2461 - smape: 0.4052 - val_ia: 0.6825 - val_loss: 0.0567 - val_mae: 0.1363 - val_rmse: 0.1877 - val_smape: 0.3560

Epoch 16/128

1916/1916 - 41s - 21ms/step - ia: 0.8767 - loss: 0.0746 - mae: 0.1681 - rmse: 0.2463 - smape: 0.4033 - val_ia: 0.6724 - val_loss: 0.0533 - val_mae: 0.1335 - val_rmse: 0.1852 - val_smape: 0.3563

Epoch 17/128

1916/1916 - 41s - 21ms/step - ia: 0.8771 - loss: 0.0743 - mae: 0.1676 - rmse: 0.2453 - smape: 0.4045 - val_ia: 0.6906 - val_loss: 0.0541 - val_mae: 0.1304 - val_rmse: 0.1858 - val_smape: 0.3549

Epoch 18/128

1916/1916 - 23s - 12ms/step - ia: 0.8767 - loss: 0.0735 - mae: 0.1674 - rmse: 0.2443 - smape: 0.4048 - val_ia: 0.6845 - val_loss: 0.0531 - val_mae: 0.1302 - val_rmse: 0.1836 - val_smape: 0.3496

Epoch 19/128

1916/1916 - 23s - 12ms/step - ia: 0.8781 - loss: 0.0728 - mae: 0.1658 - rmse: 0.2425 - smape: 0.4029 - val_ia: 0.6895 - val_loss: 0.0532 - val_mae: 0.1304 - val_rmse: 0.1826 - val_smape: 0.3499

Epoch 20/128

1916/1916 - 24s - 12ms/step - ia: 0.8788 - loss: 0.0720 - mae: 0.1653 - rmse: 0.2418 - smape: 0.4020 - val_ia: 0.6727 - val_loss: 0.0530 - val_mae: 0.1328 - val_rmse: 0.1850 - val_smape: 0.3559

Epoch 21/128

1916/1916 - 24s - 12ms/step - ia: 0.8785 - loss: 0.0724 - mae: 0.1657 - rmse: 0.2426 - smape: 0.4008 - val_ia: 0.7017 - val_loss: 0.0526 - val_mae: 0.1267 - val_rmse: 0.1809 - val_smape: 0.3451

Epoch 22/128

1916/1916 - 23s - 12ms/step - ia: 0.8789 - loss: 0.0716 - mae: 0.1652 - rmse: 0.2423 - smape: 0.4007 - val_ia: 0.6947 - val_loss: 0.0525 - val_mae: 0.1271 - val_rmse: 0.1811 - val_smape: 0.3464

Epoch 23/128

1916/1916 - 23s - 12ms/step - ia: 0.8800 - loss: 0.0720 - mae: 0.1645 - rmse: 0.2409 - smape: 0.3978 - val_ia: 0.6963 - val_loss: 0.0536 - val_mae: 0.1283 - val_rmse: 0.1836 - val_smape: 0.3489

Epoch 24/128

1916/1916 - 23s - 12ms/step - ia: 0.8793 - loss: 0.0719 - mae: 0.1644 - rmse: 0.2412 - smape: 0.3980 - val_ia: 0.6777 - val_loss: 0.0544 - val_mae: 0.1341 - val_rmse: 0.1856 - val_smape: 0.3536

Epoch 25/128

1916/1916 - 41s - 22ms/step - ia: 0.8788 - loss: 0.0715 - mae: 0.1649 - rmse: 0.2412 - smape: 0.4013 - val_ia: 0.6600 - val_loss: 0.0543 - val_mae: 0.1377 - val_rmse: 0.1890 - val_smape: 0.3633

Epoch 26/128

1916/1916 - 24s - 12ms/step - ia: 0.8800 - loss: 0.0710 - mae: 0.1639 - rmse: 0.2404 - smape: 0.3961 - val_ia: 0.6990 - val_loss: 0.0529 - val_mae: 0.1288 - val_rmse: 0.1817 - val_smape: 0.3486

Epoch 27/128

1916/1916 - 23s - 12ms/step - ia: 0.8789 - loss: 0.0723 - mae: 0.1645 - rmse: 0.2420 - smape: 0.3979 - val_ia: 0.6938 - val_loss: 0.0540 - val_mae: 0.1321 - val_rmse: 0.1836 - val_smape: 0.3527

Epoch 28/128

1916/1916 - 23s - 12ms/step - ia: 0.8792 - loss: 0.0714 - mae: 0.1643 - rmse: 0.2406 - smape: 0.3985 - val_ia: 0.6729 - val_loss: 0.0527 - val_mae: 0.1325 - val_rmse: 0.1841 - val_smape: 0.3535

Epoch 29/128

1916/1916 - 41s - 21ms/step - ia: 0.8801 - loss: 0.0698 - mae: 0.1627 - rmse: 0.2384 - smape: 0.3954 - val_ia: 0.6683 - val_loss: 0.0539 - val_mae: 0.1345 - val_rmse: 0.1873 - val_smape: 0.3589

Epoch 30/128

1916/1916 - 45s - 24ms/step - ia: 0.8807 - loss: 0.0711 - mae: 0.1625 - rmse: 0.2388 - smape: 0.3955 - val_ia: 0.6761 - val_loss: 0.0542 - val_mae: 0.1338 - val_rmse: 0.1852 - val_smape: 0.3540

Epoch 31/128

1916/1916 - 23s - 12ms/step - ia: 0.8810 - loss: 0.0692 - mae: 0.1625 - rmse: 0.2369 - smape: 0.3950 - val_ia: 0.6803 - val_loss: 0.0531 - val_mae: 0.1313 - val_rmse: 0.1836 - val_smape: 0.3528

Epoch 32/128

1916/1916 - 23s - 12ms/step - ia: 0.8800 - loss: 0.0705 - mae: 0.1634 - rmse: 0.2388 - smape: 0.3951 - val_ia: 0.6986 - val_loss: 0.0531 - val_mae: 0.1285 - val_rmse: 0.1821 - val_smape: 0.3476

Epoch 33/128

1916/1916 - 24s - 12ms/step - ia: 0.8814 - loss: 0.0691 - mae: 0.1613 - rmse: 0.2373 - smape: 0.3930 - val_ia: 0.6796 - val_loss: 0.0537 - val_mae: 0.1318 - val_rmse: 0.1852 - val_smape: 0.3535

Epoch 34/128

1916/1916 - 23s - 12ms/step - ia: 0.8804 - loss: 0.0701 - mae: 0.1628 - rmse: 0.2384 - smape: 0.3950 - val_ia: 0.6711 - val_loss: 0.0548 - val_mae: 0.1359 - val_rmse: 0.1861 - val_smape: 0.3555

Epoch 35/128

1916/1916 - 23s - 12ms/step - ia: 0.8813 - loss: 0.0688 - mae: 0.1610 - rmse: 0.2362 - smape: 0.3907 - val_ia: 0.6886 - val_loss: 0.0540 - val_mae: 0.1296 - val_rmse: 0.1834 - val_smape: 0.3468

Epoch 36/128

1916/1916 - 23s - 12ms/step - ia: 0.8814 - loss: 0.0683 - mae: 0.1613 - rmse: 0.2362 - smape: 0.3940 - val_ia: 0.6928 - val_loss: 0.0534 - val_mae: 0.1286 - val_rmse: 0.1826 - val_smape: 0.3504

Epoch 37/128

1916/1916 - 23s - 12ms/step - ia: 0.8815 - loss: 0.0679 - mae: 0.1613 - rmse: 0.2360 - smape: 0.3938 - val_ia: 0.6588 - val_loss: 0.0549 - val_mae: 0.1394 - val_rmse: 0.1884 - val_smape: 0.3615

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 22.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:01 900ms/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 60%|██████    | 30/50 [12:42:24<9:13:38, 1660.95s/trial, best loss: 0.036925422014018904]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 18s - 10ms/step - ia: 0.8039 - loss: 0.1613 - mae: 0.2565 - rmse: 0.3635 - smape: 0.5700 - val_ia: 0.6254 - val_loss: 0.0724 - val_mae: 0.1596 - val_rmse: 0.2153 - val_smape: 0.4072

Epoch 2/32

1916/1916 - 12s - 6ms/step - ia: 0.8586 - loss: 0.0925 - mae: 0.1912 - rmse: 0.2765 - smape: 0.4503 - val_ia: 0.6845 - val_loss: 0.0603 - val_mae: 0.1380 - val_rmse: 0.1946 - val_smape: 0.3614

Epoch 3/32

1916/1916 - 12s - 6ms/step - ia: 0.8699 - loss: 0.0822 - mae: 0.1773 - rmse: 0.2586 - smape: 0.4206 - val_ia: 0.6305 - val_loss: 0.0605 - val_mae: 0.1510 - val_rmse: 0.2013 - val_smape: 0.3793

Epoch 4/32

1916/1916 - 21s - 11ms/step - ia: 0.8752 - loss: 0.0777 - mae: 0.1706 - rmse: 0.2516 - smape: 0.4058 - val_ia: 0.6730 - val_loss: 0.0552 - val_mae: 0.1350 - val_rmse: 0.1872 - val_smape: 0.3573

Epoch 5/32

1916/1916 - 21s - 11ms/step - ia: 0.8767 - loss: 0.0754 - mae: 0.1674 - rmse: 0.2473 - smape: 0.4011 - val_ia: 0.6801 - val_loss: 0.0553 - val_mae: 0.1338 - val_rmse: 0.1867 - val_smape: 0.3565

Epoch 6/32

1916/1916 - 12s - 6ms/step - ia: 0.8801 - loss: 0.0723 - mae: 0.1634 - rmse: 0.2420 - smape: 0.3926 - val_ia: 0.6965 - val_loss: 0.0529 - val_mae: 0.1277 - val_rmse: 0.1801 - val_smape: 0.3459

Epoch 7/32

1916/1916 - 20s - 11ms/step - ia: 0.8800 - loss: 0.0718 - mae: 0.1633 - rmse: 0.2416 - smape: 0.3912 - val_ia: 0.6867 - val_loss: 0.0572 - val_mae: 0.1355 - val_rmse: 0.1868 - val_smape: 0.3522

Epoch 8/32

1916/1916 - 12s - 6ms/step - ia: 0.8817 - loss: 0.0705 - mae: 0.1612 - rmse: 0.2378 - smape: 0.3879 - val_ia: 0.6943 - val_loss: 0.0555 - val_mae: 0.1306 - val_rmse: 0.1839 - val_smape: 0.3468

Epoch 9/32

1916/1916 - 20s - 11ms/step - ia: 0.8823 - loss: 0.0692 - mae: 0.1601 - rmse: 0.2371 - smape: 0.3863 - val_ia: 0.6882 - val_loss: 0.0542 - val_mae: 0.1309 - val_rmse: 0.1832 - val_smape: 0.3524

Epoch 10/32

1916/1916 - 21s - 11ms/step - ia: 0.8827 - loss: 0.0682 - mae: 0.1589 - rmse: 0.2350 - smape: 0.3850 - val_ia: 0.7026 - val_loss: 0.0549 - val_mae: 0.1298 - val_rmse: 0.1826 - val_smape: 0.3447

Epoch 11/32

1916/1916 - 12s - 6ms/step - ia: 0.8827 - loss: 0.0691 - mae: 0.1592 - rmse: 0.2359 - smape: 0.3850 - val_ia: 0.6844 - val_loss: 0.0549 - val_mae: 0.1328 - val_rmse: 0.1853 - val_smape: 0.3561

Epoch 12/32

1916/1916 - 10s - 5ms/step - ia: 0.8839 - loss: 0.0682 - mae: 0.1576 - rmse: 0.2346 - smape: 0.3824 - val_ia: 0.6995 - val_loss: 0.0534 - val_mae: 0.1280 - val_rmse: 0.1818 - val_smape: 0.3482

Epoch 13/32

1916/1916 - 11s - 6ms/step - ia: 0.8844 - loss: 0.0685 - mae: 0.1581 - rmse: 0.2341 - smape: 0.3822 - val_ia: 0.6930 - val_loss: 0.0531 - val_mae: 0.1287 - val_rmse: 0.1803 - val_smape: 0.3470

Epoch 14/32

1916/1916 - 12s - 6ms/step - ia: 0.8854 - loss: 0.0672 - mae: 0.1574 - rmse: 0.2326 - smape: 0.3824 - val_ia: 0.6513 - val_loss: 0.0569 - val_mae: 0.1422 - val_rmse: 0.1921 - val_smape: 0.3667

Epoch 15/32

1916/1916 - 12s - 6ms/step - ia: 0.8845 - loss: 0.0671 - mae: 0.1572 - rmse: 0.2327 - smape: 0.3804 - val_ia: 0.6645 - val_loss: 0.0550 - val_mae: 0.1376 - val_rmse: 0.1886 - val_smape: 0.3657

Epoch 16/32

1916/1916 - 21s - 11ms/step - ia: 0.8851 - loss: 0.0665 - mae: 0.1567 - rmse: 0.2324 - smape: 0.3798 - val_ia: 0.6921 - val_loss: 0.0527 - val_mae: 0.1286 - val_rmse: 0.1800 - val_smape: 0.3455

Epoch 17/32

1916/1916 - 18s - 9ms/step - ia: 0.8846 - loss: 0.0677 - mae: 0.1571 - rmse: 0.2336 - smape: 0.3798 - val_ia: 0.6777 - val_loss: 0.0632 - val_mae: 0.1427 - val_rmse: 0.1934 - val_smape: 0.3584

Epoch 18/32

1916/1916 - 12s - 6ms/step - ia: 0.8861 - loss: 0.0655 - mae: 0.1560 - rmse: 0.2313 - smape: 0.3780 - val_ia: 0.6945 - val_loss: 0.0538 - val_mae: 0.1298 - val_rmse: 0.1810 - val_smape: 0.3467

Epoch 19/32

1916/1916 - 12s - 6ms/step - ia: 0.8860 - loss: 0.0649 - mae: 0.1550 - rmse: 0.2297 - smape: 0.3783 - val_ia: 0.7011 - val_loss: 0.0531 - val_mae: 0.1278 - val_rmse: 0.1813 - val_smape: 0.3449

Epoch 20/32

1916/1916 - 12s - 6ms/step - ia: 0.8859 - loss: 0.0651 - mae: 0.1557 - rmse: 0.2303 - smape: 0.3784 - val_ia: 0.6864 - val_loss: 0.0533 - val_mae: 0.1312 - val_rmse: 0.1825 - val_smape: 0.3486

Epoch 21/32

1916/1916 - 21s - 11ms/step - ia: 0.8860 - loss: 0.0652 - mae: 0.1554 - rmse: 0.2288 - smape: 0.3789 - val_ia: 0.6789 - val_loss: 0.0531 - val_mae: 0.1315 - val_rmse: 0.1831 - val_smape: 0.3526

Epoch 22/32

1916/1916 - 12s - 6ms/step - ia: 0.8864 - loss: 0.0647 - mae: 0.1552 - rmse: 0.2288 - smape: 0.3798 - val_ia: 0.6926 - val_loss: 0.0537 - val_mae: 0.1292 - val_rmse: 0.1817 - val_smape: 0.3476

Epoch 23/32

1916/1916 - 12s - 6ms/step - ia: 0.8867 - loss: 0.0650 - mae: 0.1551 - rmse: 0.2293 - smape: 0.3783 - val_ia: 0.6912 - val_loss: 0.0531 - val_mae: 0.1293 - val_rmse: 0.1812 - val_smape: 0.3472

Epoch 24/32

1916/1916 - 23s - 12ms/step - ia: 0.8870 - loss: 0.0637 - mae: 0.1545 - rmse: 0.2273 - smape: 0.3786 - val_ia: 0.7045 - val_loss: 0.0549 - val_mae: 0.1287 - val_rmse: 0.1811 - val_smape: 0.3446

Epoch 25/32

1916/1916 - 15s - 8ms/step - ia: 0.8857 - loss: 0.0645 - mae: 0.1554 - rmse: 0.2286 - smape: 0.3793 - val_ia: 0.7016 - val_loss: 0.0533 - val_mae: 0.1285 - val_rmse: 0.1802 - val_smape: 0.3456

Epoch 26/32

1916/1916 - 12s - 6ms/step - ia: 0.8880 - loss: 0.0629 - mae: 0.1534 - rmse: 0.2265 - smape: 0.3742 - val_ia: 0.6876 - val_loss: 0.0559 - val_mae: 0.1320 - val_rmse: 0.1845 - val_smape: 0.3535

Epoch 27/32

1916/1916 - 12s - 6ms/step - ia: 0.8871 - loss: 0.0631 - mae: 0.1543 - rmse: 0.2273 - smape: 0.3773 - val_ia: 0.7080 - val_loss: 0.0535 - val_mae: 0.1272 - val_rmse: 0.1794 - val_smape: 0.3423

Epoch 28/32

1916/1916 - 12s - 6ms/step - ia: 0.8868 - loss: 0.0635 - mae: 0.1542 - rmse: 0.2275 - smape: 0.3763 - val_ia: 0.6788 - val_loss: 0.0530 - val_mae: 0.1318 - val_rmse: 0.1822 - val_smape: 0.3520

Epoch 29/32

1916/1916 - 13s - 7ms/step - ia: 0.8878 - loss: 0.0628 - mae: 0.1532 - rmse: 0.2250 - smape: 0.3747 - val_ia: 0.6934 - val_loss: 0.0531 - val_mae: 0.1293 - val_rmse: 0.1806 - val_smape: 0.3490

Epoch 30/32

1916/1916 - 12s - 6ms/step - ia: 0.8874 - loss: 0.0626 - mae: 0.1534 - rmse: 0.2270 - smape: 0.3765 - val_ia: 0.6931 - val_loss: 0.0545 - val_mae: 0.1307 - val_rmse: 0.1824 - val_smape: 0.3471

Epoch 31/32

1916/1916 - 12s - 6ms/step - ia: 0.8877 - loss: 0.0622 - mae: 0.1533 - rmse: 0.2266 - smape: 0.3762 - val_ia: 0.6932 - val_loss: 0.0536 - val_mae: 0.1296 - val_rmse: 0.1824 - val_smape: 0.3486

Epoch 31: early stopping

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:09 517ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 62%|██████▏   | 31/50 [12:50:02<6:51:39, 1299.99s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 15s - 8ms/step - ia: 0.7242 - loss: 0.2641 - mae: 0.3440 - rmse: 0.4733 - smape: 0.7251 - val_ia: 0.5246 - val_loss: 0.0997 - val_mae: 0.2071 - val_rmse: 0.2638 - val_smape: 0.5087

Epoch 2/32

1916/1916 - 9s - 5ms/step - ia: 0.8028 - loss: 0.1534 - mae: 0.2611 - rmse: 0.3644 - smape: 0.5684 - val_ia: 0.5680 - val_loss: 0.0790 - val_mae: 0.1834 - val_rmse: 0.2340 - val_smape: 0.4437

Epoch 3/32

1916/1916 - 10s - 5ms/step - ia: 0.8217 - loss: 0.1306 - mae: 0.2371 - rmse: 0.3348 - smape: 0.5129 - val_ia: 0.6067 - val_loss: 0.0678 - val_mae: 0.1634 - val_rmse: 0.2130 - val_smape: 0.4021

Epoch 4/32

1916/1916 - 9s - 5ms/step - ia: 0.8314 - loss: 0.1209 - mae: 0.2265 - rmse: 0.3218 - smape: 0.4909 - val_ia: 0.6366 - val_loss: 0.0601 - val_mae: 0.1474 - val_rmse: 0.1986 - val_smape: 0.3774

Epoch 5/32

1916/1916 - 8s - 4ms/step - ia: 0.8339 - loss: 0.1168 - mae: 0.2224 - rmse: 0.3153 - smape: 0.4789 - val_ia: 0.6278 - val_loss: 0.0590 - val_mae: 0.1504 - val_rmse: 0.2005 - val_smape: 0.3806

Epoch 6/32

1916/1916 - 8s - 4ms/step - ia: 0.8396 - loss: 0.1122 - mae: 0.2160 - rmse: 0.3077 - smape: 0.4663 - val_ia: 0.6232 - val_loss: 0.0592 - val_mae: 0.1531 - val_rmse: 0.2021 - val_smape: 0.3839

Epoch 7/32

1916/1916 - 8s - 4ms/step - ia: 0.8408 - loss: 0.1100 - mae: 0.2139 - rmse: 0.3053 - smape: 0.4632 - val_ia: 0.6258 - val_loss: 0.0612 - val_mae: 0.1543 - val_rmse: 0.2034 - val_smape: 0.3807

Epoch 8/32

1916/1916 - 8s - 4ms/step - ia: 0.8417 - loss: 0.1090 - mae: 0.2119 - rmse: 0.3034 - smape: 0.4560 - val_ia: 0.6416 - val_loss: 0.0676 - val_mae: 0.1554 - val_rmse: 0.2039 - val_smape: 0.3759

Epoch 9/32

1916/1916 - 9s - 4ms/step - ia: 0.8418 - loss: 0.1092 - mae: 0.2127 - rmse: 0.3047 - smape: 0.4592 - val_ia: 0.6588 - val_loss: 0.0570 - val_mae: 0.1392 - val_rmse: 0.1906 - val_smape: 0.3588

Epoch 10/32

1916/1916 - 8s - 4ms/step - ia: 0.8436 - loss: 0.1071 - mae: 0.2107 - rmse: 0.3013 - smape: 0.4547 - val_ia: 0.6452 - val_loss: 0.0602 - val_mae: 0.1465 - val_rmse: 0.1966 - val_smape: 0.3699

Epoch 11/32

1916/1916 - 10s - 5ms/step - ia: 0.8433 - loss: 0.1078 - mae: 0.2102 - rmse: 0.3027 - smape: 0.4516 - val_ia: 0.6906 - val_loss: 0.0558 - val_mae: 0.1310 - val_rmse: 0.1848 - val_smape: 0.3466

Epoch 12/32

1916/1916 - 8s - 4ms/step - ia: 0.8454 - loss: 0.1047 - mae: 0.2083 - rmse: 0.2978 - smape: 0.4494 - val_ia: 0.6773 - val_loss: 0.0583 - val_mae: 0.1374 - val_rmse: 0.1883 - val_smape: 0.3626

Epoch 13/32

1916/1916 - 8s - 4ms/step - ia: 0.8466 - loss: 0.1024 - mae: 0.2060 - rmse: 0.2943 - smape: 0.4476 - val_ia: 0.6844 - val_loss: 0.0567 - val_mae: 0.1339 - val_rmse: 0.1863 - val_smape: 0.3505

Epoch 14/32

1916/1916 - 8s - 4ms/step - ia: 0.8477 - loss: 0.1027 - mae: 0.2046 - rmse: 0.2940 - smape: 0.4457 - val_ia: 0.6656 - val_loss: 0.0574 - val_mae: 0.1393 - val_rmse: 0.1896 - val_smape: 0.3574

Epoch 15/32

1916/1916 - 7s - 4ms/step - ia: 0.8478 - loss: 0.1041 - mae: 0.2043 - rmse: 0.2942 - smape: 0.4433 - val_ia: 0.6733 - val_loss: 0.0560 - val_mae: 0.1354 - val_rmse: 0.1868 - val_smape: 0.3530

Epoch 16/32

1916/1916 - 6s - 3ms/step - ia: 0.8469 - loss: 0.1016 - mae: 0.2053 - rmse: 0.2942 - smape: 0.4458 - val_ia: 0.6857 - val_loss: 0.0563 - val_mae: 0.1327 - val_rmse: 0.1851 - val_smape: 0.3502

Epoch 17/32

1916/1916 - 7s - 3ms/step - ia: 0.8484 - loss: 0.1021 - mae: 0.2043 - rmse: 0.2934 - smape: 0.4414 - val_ia: 0.6621 - val_loss: 0.0575 - val_mae: 0.1399 - val_rmse: 0.1907 - val_smape: 0.3609

Epoch 18/32

1916/1916 - 8s - 4ms/step - ia: 0.8498 - loss: 0.1009 - mae: 0.2029 - rmse: 0.2915 - smape: 0.4406 - val_ia: 0.6801 - val_loss: 0.0553 - val_mae: 0.1333 - val_rmse: 0.1855 - val_smape: 0.3489

Epoch 19/32

1916/1916 - 11s - 6ms/step - ia: 0.8497 - loss: 0.0999 - mae: 0.2025 - rmse: 0.2909 - smape: 0.4413 - val_ia: 0.6651 - val_loss: 0.0563 - val_mae: 0.1379 - val_rmse: 0.1883 - val_smape: 0.3606

Epoch 20/32

1916/1916 - 8s - 4ms/step - ia: 0.8486 - loss: 0.1021 - mae: 0.2036 - rmse: 0.2920 - smape: 0.4447 - val_ia: 0.6762 - val_loss: 0.0559 - val_mae: 0.1344 - val_rmse: 0.1867 - val_smape: 0.3552

Epoch 21/32

1916/1916 - 8s - 4ms/step - ia: 0.8498 - loss: 0.1024 - mae: 0.2025 - rmse: 0.2933 - smape: 0.4379 - val_ia: 0.6507 - val_loss: 0.0594 - val_mae: 0.1451 - val_rmse: 0.1944 - val_smape: 0.3660

Epoch 22/32

1916/1916 - 8s - 4ms/step - ia: 0.8499 - loss: 0.0990 - mae: 0.2026 - rmse: 0.2903 - smape: 0.4425 - val_ia: 0.6838 - val_loss: 0.0573 - val_mae: 0.1351 - val_rmse: 0.1866 - val_smape: 0.3539

Epoch 23/32

1916/1916 - 8s - 4ms/step - ia: 0.8499 - loss: 0.1010 - mae: 0.2021 - rmse: 0.2905 - smape: 0.4368 - val_ia: 0.6507 - val_loss: 0.0592 - val_mae: 0.1446 - val_rmse: 0.1945 - val_smape: 0.3662

Epoch 24/32

1916/1916 - 8s - 4ms/step - ia: 0.8502 - loss: 0.1008 - mae: 0.2018 - rmse: 0.2905 - smape: 0.4404 - val_ia: 0.6584 - val_loss: 0.0564 - val_mae: 0.1394 - val_rmse: 0.1908 - val_smape: 0.3660

Epoch 25/32

1916/1916 - 8s - 4ms/step - ia: 0.8518 - loss: 0.0975 - mae: 0.2003 - rmse: 0.2870 - smape: 0.4380 - val_ia: 0.6426 - val_loss: 0.0577 - val_mae: 0.1459 - val_rmse: 0.1957 - val_smape: 0.3722

Epoch 26/32

1916/1916 - 10s - 5ms/step - ia: 0.8509 - loss: 0.0995 - mae: 0.2004 - rmse: 0.2884 - smape: 0.4376 - val_ia: 0.6683 - val_loss: 0.0568 - val_mae: 0.1375 - val_rmse: 0.1887 - val_smape: 0.3593

Epoch 27/32

1916/1916 - 8s - 4ms/step - ia: 0.8520 - loss: 0.0984 - mae: 0.1999 - rmse: 0.2877 - smape: 0.4338 - val_ia: 0.6760 - val_loss: 0.0592 - val_mae: 0.1388 - val_rmse: 0.1892 - val_smape: 0.3562

Epoch 28/32

1916/1916 - 6s - 3ms/step - ia: 0.8513 - loss: 0.0983 - mae: 0.1996 - rmse: 0.2874 - smape: 0.4348 - val_ia: 0.6828 - val_loss: 0.0553 - val_mae: 0.1329 - val_rmse: 0.1850 - val_smape: 0.3519

Epoch 29/32

1916/1916 - 8s - 4ms/step - ia: 0.8519 - loss: 0.0993 - mae: 0.1998 - rmse: 0.2881 - smape: 0.4360 - val_ia: 0.6473 - val_loss: 0.0573 - val_mae: 0.1437 - val_rmse: 0.1936 - val_smape: 0.3699

Epoch 30/32

1916/1916 - 8s - 4ms/step - ia: 0.8523 - loss: 0.0972 - mae: 0.1991 - rmse: 0.2852 - smape: 0.4377 - val_ia: 0.6493 - val_loss: 0.0581 - val_mae: 0.1435 - val_rmse: 0.1941 - val_smape: 0.3675

Epoch 31/32

1916/1916 - 8s - 4ms/step - ia: 0.8509 - loss: 0.0987 - mae: 0.2006 - rmse: 0.2888 - smape: 0.4364 - val_ia: 0.6513 - val_loss: 0.0578 - val_mae: 0.1435 - val_rmse: 0.1930 - val_smape: 0.3648

Epoch 32/32

1916/1916 - 8s - 4ms/step - ia: 0.8505 - loss: 0.0979 - mae: 0.2009 - rmse: 0.2896 - smape: 0.4363 - val_ia: 0.6427 - val_loss: 0.0569 - val_mae: 0.1444 - val_rmse: 0.1947 - val_smape: 0.3711

Restoring model weights from the end of the best epoch: 18.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:20 599ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 64%|██████▍   | 32/50 [12:54:36<4:57:42, 992.34s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 18s - 10ms/step - ia: 0.7089 - loss: 0.2920 - mae: 0.3638 - rmse: 0.5026 - smape: 0.7336 - val_ia: 0.4817 - val_loss: 0.1368 - val_mae: 0.2463 - val_rmse: 0.2954 - val_smape: 0.5430

Epoch 2/32

1916/1916 - 14s - 7ms/step - ia: 0.7554 - loss: 0.2214 - mae: 0.3140 - rmse: 0.4385 - smape: 0.6322 - val_ia: 0.4963 - val_loss: 0.1280 - val_mae: 0.2424 - val_rmse: 0.2873 - val_smape: 0.5197

Epoch 3/32

1916/1916 - 15s - 8ms/step - ia: 0.7636 - loss: 0.2102 - mae: 0.3045 - rmse: 0.4265 - smape: 0.6109 - val_ia: 0.5213 - val_loss: 0.1201 - val_mae: 0.2308 - val_rmse: 0.2752 - val_smape: 0.4862

Epoch 4/32

1916/1916 - 19s - 10ms/step - ia: 0.7695 - loss: 0.2063 - mae: 0.2977 - rmse: 0.4208 - smape: 0.5961 - val_ia: 0.4474 - val_loss: 0.1381 - val_mae: 0.2971 - val_rmse: 0.3392 - val_smape: 0.7194

Epoch 5/32

1916/1916 - 14s - 7ms/step - ia: 0.7783 - loss: 0.1922 - mae: 0.2892 - rmse: 0.4085 - smape: 0.5859 - val_ia: 0.4220 - val_loss: 0.1580 - val_mae: 0.3238 - val_rmse: 0.3671 - val_smape: 0.7687

Epoch 6/32

1916/1916 - 16s - 8ms/step - ia: 0.7793 - loss: 0.1940 - mae: 0.2873 - rmse: 0.4083 - smape: 0.5811 - val_ia: 0.3432 - val_loss: 0.2596 - val_mae: 0.4618 - val_rmse: 0.4982 - val_smape: 1.0454

Epoch 7/32

1916/1916 - 19s - 10ms/step - ia: 0.7807 - loss: 0.1927 - mae: 0.2863 - rmse: 0.4049 - smape: 0.5810 - val_ia: 0.3103 - val_loss: 0.3611 - val_mae: 0.5384 - val_rmse: 0.5810 - val_smape: 1.0522

Epoch 8/32

1916/1916 - 14s - 7ms/step - ia: 0.7782 - loss: 0.1937 - mae: 0.2865 - rmse: 0.4069 - smape: 0.5836 - val_ia: 0.2913 - val_loss: 0.4186 - val_mae: 0.5867 - val_rmse: 0.6251 - val_smape: 1.1468

Epoch 9/32

1916/1916 - 14s - 7ms/step - ia: 0.7792 - loss: 0.1974 - mae: 0.2864 - rmse: 0.4092 - smape: 0.5820 - val_ia: 0.2560 - val_loss: 0.5966 - val_mae: 0.7037 - val_rmse: 0.7465 - val_smape: 1.1987

Epoch 10/32

1916/1916 - 13s - 7ms/step - ia: 0.7807 - loss: 0.1919 - mae: 0.2842 - rmse: 0.4030 - smape: 0.5766 - val_ia: 0.2621 - val_loss: 0.5841 - val_mae: 0.6949 - val_rmse: 0.7396 - val_smape: 1.2028

Epoch 11/32

1916/1916 - 13s - 7ms/step - ia: 0.7800 - loss: 0.1911 - mae: 0.2857 - rmse: 0.4069 - smape: 0.5770 - val_ia: 0.2723 - val_loss: 0.4930 - val_mae: 0.6451 - val_rmse: 0.6860 - val_smape: 1.1894

Epoch 12/32

1916/1916 - 14s - 7ms/step - ia: 0.7833 - loss: 0.1867 - mae: 0.2814 - rmse: 0.3998 - smape: 0.5745 - val_ia: 0.2774 - val_loss: 0.5094 - val_mae: 0.6432 - val_rmse: 0.6889 - val_smape: 1.1415

Epoch 13/32

1916/1916 - 13s - 7ms/step - ia: 0.7828 - loss: 0.1894 - mae: 0.2822 - rmse: 0.4016 - smape: 0.5713 - val_ia: 0.2899 - val_loss: 0.4444 - val_mae: 0.5995 - val_rmse: 0.6452 - val_smape: 1.0931

Epoch 14/32

1916/1916 - 23s - 12ms/step - ia: 0.7836 - loss: 0.1841 - mae: 0.2807 - rmse: 0.3964 - smape: 0.5760 - val_ia: 0.2966 - val_loss: 0.4280 - val_mae: 0.5853 - val_rmse: 0.6315 - val_smape: 1.0821

Epoch 15/32

1916/1916 - 15s - 8ms/step - ia: 0.7825 - loss: 0.1886 - mae: 0.2819 - rmse: 0.4003 - smape: 0.5762 - val_ia: 0.2900 - val_loss: 0.4719 - val_mae: 0.6057 - val_rmse: 0.6579 - val_smape: 1.0493

Epoch 16/32

1916/1916 - 14s - 7ms/step - ia: 0.7844 - loss: 0.1847 - mae: 0.2797 - rmse: 0.3984 - smape: 0.5689 - val_ia: 0.3174 - val_loss: 0.4227 - val_mae: 0.5472 - val_rmse: 0.6095 - val_smape: 0.9230

Epoch 17/32

1916/1916 - 12s - 6ms/step - ia: 0.7886 - loss: 0.1796 - mae: 0.2760 - rmse: 0.3923 - smape: 0.5648 - val_ia: 0.3346 - val_loss: 0.3258 - val_mae: 0.4952 - val_rmse: 0.5469 - val_smape: 0.9292

Epoch 18/32

1916/1916 - 18s - 9ms/step - ia: 0.7868 - loss: 0.1827 - mae: 0.2769 - rmse: 0.3933 - smape: 0.5685 - val_ia: 0.2700 - val_loss: 0.5859 - val_mae: 0.6724 - val_rmse: 0.7274 - val_smape: 1.1007

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:36 717ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 66%|██████▌   | 33/50 [12:59:33<3:42:01, 783.60s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 8s - 70ms/step - ia: 0.5404 - loss: 0.4638 - mae: 0.4953 - rmse: 0.6641 - smape: 1.0885 - val_ia: 0.7129 - val_loss: 0.1995 - val_mae: 0.3062 - val_rmse: 0.4195 - val_smape: 0.6920

Epoch 2/32

120/120 - 4s - 37ms/step - ia: 0.7727 - loss: 0.2125 - mae: 0.3115 - rmse: 0.4575 - smape: 0.6718 - val_ia: 0.7770 - val_loss: 0.1361 - val_mae: 0.2445 - val_rmse: 0.3472 - val_smape: 0.5785

Epoch 3/32

120/120 - 5s - 43ms/step - ia: 0.7987 - loss: 0.1772 - mae: 0.2819 - rmse: 0.4182 - smape: 0.6192 - val_ia: 0.7936 - val_loss: 0.1214 - val_mae: 0.2264 - val_rmse: 0.3280 - val_smape: 0.5437

Epoch 4/32

120/120 - 5s - 45ms/step - ia: 0.8117 - loss: 0.1598 - mae: 0.2661 - rmse: 0.3964 - smape: 0.5920 - val_ia: 0.8075 - val_loss: 0.1095 - val_mae: 0.2124 - val_rmse: 0.3118 - val_smape: 0.5191

Epoch 5/32

120/120 - 4s - 37ms/step - ia: 0.8215 - loss: 0.1451 - mae: 0.2534 - rmse: 0.3780 - smape: 0.5697 - val_ia: 0.8169 - val_loss: 0.0992 - val_mae: 0.2011 - val_rmse: 0.2979 - val_smape: 0.4993

Epoch 6/32

120/120 - 4s - 37ms/step - ia: 0.8311 - loss: 0.1329 - mae: 0.2415 - rmse: 0.3616 - smape: 0.5498 - val_ia: 0.8167 - val_loss: 0.0934 - val_mae: 0.1984 - val_rmse: 0.2908 - val_smape: 0.4964

Epoch 7/32

120/120 - 4s - 36ms/step - ia: 0.8371 - loss: 0.1253 - mae: 0.2334 - rmse: 0.3507 - smape: 0.5355 - val_ia: 0.8389 - val_loss: 0.0844 - val_mae: 0.1794 - val_rmse: 0.2750 - val_smape: 0.4610

Epoch 8/32

120/120 - 4s - 35ms/step - ia: 0.8411 - loss: 0.1202 - mae: 0.2276 - rmse: 0.3432 - smape: 0.5254 - val_ia: 0.8413 - val_loss: 0.0822 - val_mae: 0.1773 - val_rmse: 0.2718 - val_smape: 0.4560

Epoch 9/32

120/120 - 4s - 37ms/step - ia: 0.8471 - loss: 0.1134 - mae: 0.2202 - rmse: 0.3337 - smape: 0.5111 - val_ia: 0.8489 - val_loss: 0.0760 - val_mae: 0.1676 - val_rmse: 0.2610 - val_smape: 0.4388

Epoch 10/32

120/120 - 5s - 44ms/step - ia: 0.8509 - loss: 0.1086 - mae: 0.2150 - rmse: 0.3263 - smape: 0.5020 - val_ia: 0.8458 - val_loss: 0.0758 - val_mae: 0.1692 - val_rmse: 0.2608 - val_smape: 0.4398

Epoch 11/32

120/120 - 5s - 38ms/step - ia: 0.8543 - loss: 0.1042 - mae: 0.2105 - rmse: 0.3198 - smape: 0.4941 - val_ia: 0.8522 - val_loss: 0.0730 - val_mae: 0.1641 - val_rmse: 0.2556 - val_smape: 0.4295

Epoch 12/32

120/120 - 5s - 42ms/step - ia: 0.8574 - loss: 0.1022 - mae: 0.2065 - rmse: 0.3164 - smape: 0.4842 - val_ia: 0.8601 - val_loss: 0.0686 - val_mae: 0.1563 - val_rmse: 0.2471 - val_smape: 0.4139

Epoch 13/32

120/120 - 4s - 37ms/step - ia: 0.8603 - loss: 0.0987 - mae: 0.2024 - rmse: 0.3104 - smape: 0.4776 - val_ia: 0.8586 - val_loss: 0.0673 - val_mae: 0.1563 - val_rmse: 0.2450 - val_smape: 0.4123

Epoch 14/32

120/120 - 4s - 36ms/step - ia: 0.8631 - loss: 0.0947 - mae: 0.1982 - rmse: 0.3047 - smape: 0.4689 - val_ia: 0.8623 - val_loss: 0.0665 - val_mae: 0.1537 - val_rmse: 0.2428 - val_smape: 0.4032

Epoch 15/32

120/120 - 5s - 44ms/step - ia: 0.8650 - loss: 0.0934 - mae: 0.1963 - rmse: 0.3025 - smape: 0.4648 - val_ia: 0.8611 - val_loss: 0.0658 - val_mae: 0.1539 - val_rmse: 0.2415 - val_smape: 0.4007

Epoch 16/32

120/120 - 5s - 43ms/step - ia: 0.8678 - loss: 0.0899 - mae: 0.1921 - rmse: 0.2961 - smape: 0.4562 - val_ia: 0.8682 - val_loss: 0.0621 - val_mae: 0.1461 - val_rmse: 0.2353 - val_smape: 0.3898

Epoch 17/32

120/120 - 4s - 37ms/step - ia: 0.8696 - loss: 0.0886 - mae: 0.1894 - rmse: 0.2941 - smape: 0.4534 - val_ia: 0.8683 - val_loss: 0.0608 - val_mae: 0.1458 - val_rmse: 0.2328 - val_smape: 0.3880

Epoch 18/32

120/120 - 4s - 36ms/step - ia: 0.8724 - loss: 0.0852 - mae: 0.1857 - rmse: 0.2882 - smape: 0.4468 - val_ia: 0.8704 - val_loss: 0.0597 - val_mae: 0.1437 - val_rmse: 0.2303 - val_smape: 0.3829

Epoch 19/32

120/120 - 4s - 36ms/step - ia: 0.8734 - loss: 0.0844 - mae: 0.1844 - rmse: 0.2874 - smape: 0.4433 - val_ia: 0.8779 - val_loss: 0.0582 - val_mae: 0.1375 - val_rmse: 0.2269 - val_smape: 0.3711

Epoch 20/32

120/120 - 4s - 36ms/step - ia: 0.8750 - loss: 0.0822 - mae: 0.1823 - rmse: 0.2839 - smape: 0.4385 - val_ia: 0.8767 - val_loss: 0.0569 - val_mae: 0.1378 - val_rmse: 0.2243 - val_smape: 0.3698

Epoch 21/32

120/120 - 4s - 37ms/step - ia: 0.8766 - loss: 0.0817 - mae: 0.1800 - rmse: 0.2826 - smape: 0.4337 - val_ia: 0.8754 - val_loss: 0.0574 - val_mae: 0.1393 - val_rmse: 0.2250 - val_smape: 0.3685

Epoch 22/32

120/120 - 4s - 37ms/step - ia: 0.8781 - loss: 0.0809 - mae: 0.1780 - rmse: 0.2804 - smape: 0.4292 - val_ia: 0.8779 - val_loss: 0.0561 - val_mae: 0.1364 - val_rmse: 0.2226 - val_smape: 0.3651

Epoch 23/32

120/120 - 4s - 37ms/step - ia: 0.8788 - loss: 0.0795 - mae: 0.1771 - rmse: 0.2786 - smape: 0.4270 - val_ia: 0.8746 - val_loss: 0.0563 - val_mae: 0.1393 - val_rmse: 0.2232 - val_smape: 0.3701

Epoch 24/32

120/120 - 4s - 37ms/step - ia: 0.8809 - loss: 0.0774 - mae: 0.1740 - rmse: 0.2744 - smape: 0.4206 - val_ia: 0.8817 - val_loss: 0.0549 - val_mae: 0.1335 - val_rmse: 0.2200 - val_smape: 0.3594

Epoch 25/32

120/120 - 5s - 43ms/step - ia: 0.8812 - loss: 0.0772 - mae: 0.1736 - rmse: 0.2745 - smape: 0.4193 - val_ia: 0.8831 - val_loss: 0.0540 - val_mae: 0.1318 - val_rmse: 0.2178 - val_smape: 0.3549

Epoch 26/32

120/120 - 5s - 43ms/step - ia: 0.8828 - loss: 0.0752 - mae: 0.1713 - rmse: 0.2704 - smape: 0.4124 - val_ia: 0.8805 - val_loss: 0.0548 - val_mae: 0.1343 - val_rmse: 0.2205 - val_smape: 0.3618

Epoch 27/32

120/120 - 5s - 45ms/step - ia: 0.8836 - loss: 0.0747 - mae: 0.1705 - rmse: 0.2698 - smape: 0.4100 - val_ia: 0.8838 - val_loss: 0.0528 - val_mae: 0.1302 - val_rmse: 0.2154 - val_smape: 0.3507

Epoch 28/32

120/120 - 9s - 78ms/step - ia: 0.8846 - loss: 0.0742 - mae: 0.1686 - rmse: 0.2689 - smape: 0.4074 - val_ia: 0.8850 - val_loss: 0.0528 - val_mae: 0.1299 - val_rmse: 0.2156 - val_smape: 0.3517

Epoch 29/32

120/120 - 5s - 39ms/step - ia: 0.8855 - loss: 0.0730 - mae: 0.1678 - rmse: 0.2670 - smape: 0.4053 - val_ia: 0.8811 - val_loss: 0.0533 - val_mae: 0.1328 - val_rmse: 0.2165 - val_smape: 0.3546

Epoch 30/32

120/120 - 4s - 35ms/step - ia: 0.8851 - loss: 0.0744 - mae: 0.1681 - rmse: 0.2688 - smape: 0.4060 - val_ia: 0.8842 - val_loss: 0.0529 - val_mae: 0.1303 - val_rmse: 0.2150 - val_smape: 0.3491

Epoch 31/32

120/120 - 4s - 37ms/step - ia: 0.8860 - loss: 0.0732 - mae: 0.1669 - rmse: 0.2664 - smape: 0.4028 - val_ia: 0.8756 - val_loss: 0.0557 - val_mae: 0.1394 - val_rmse: 0.2226 - val_smape: 0.3709

Epoch 32/32

120/120 - 5s - 43ms/step - ia: 0.8864 - loss: 0.0722 - mae: 0.1667 - rmse: 0.2653 - smape: 0.4044 - val_ia: 0.8858 - val_loss: 0.0530 - val_mae: 0.1296 - val_rmse: 0.2149 - val_smape: 0.3478

Restoring model weights from the end of the best epoch: 28.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:20 600ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 68%|██████▊   | 34/50 [13:02:14<2:39:09, 596.84s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1916/1916 - 38s - 20ms/step - ia: 0.7854 - loss: 0.1923 - mae: 0.2815 - rmse: 0.3990 - smape: 0.6035 - val_ia: 0.6133 - val_loss: 0.0776 - val_mae: 0.1661 - val_rmse: 0.2255 - val_smape: 0.4252

Epoch 2/64

1916/1916 - 25s - 13ms/step - ia: 0.8363 - loss: 0.1174 - mae: 0.2200 - rmse: 0.3147 - smape: 0.4966 - val_ia: 0.6191 - val_loss: 0.0661 - val_mae: 0.1579 - val_rmse: 0.2119 - val_smape: 0.4031

Epoch 3/64

1916/1916 - 24s - 13ms/step - ia: 0.8510 - loss: 0.1010 - mae: 0.2021 - rmse: 0.2907 - smape: 0.4594 - val_ia: 0.6620 - val_loss: 0.0587 - val_mae: 0.1398 - val_rmse: 0.1939 - val_smape: 0.3688

Epoch 4/64

1916/1916 - 25s - 13ms/step - ia: 0.8586 - loss: 0.0911 - mae: 0.1920 - rmse: 0.2762 - smape: 0.4428 - val_ia: 0.6363 - val_loss: 0.0586 - val_mae: 0.1487 - val_rmse: 0.2001 - val_smape: 0.3846

Epoch 5/64

1916/1916 - 24s - 12ms/step - ia: 0.8606 - loss: 0.0913 - mae: 0.1897 - rmse: 0.2746 - smape: 0.4362 - val_ia: 0.6700 - val_loss: 0.0567 - val_mae: 0.1367 - val_rmse: 0.1902 - val_smape: 0.3572

Epoch 6/64

1916/1916 - 24s - 13ms/step - ia: 0.8641 - loss: 0.0867 - mae: 0.1851 - rmse: 0.2678 - smape: 0.4276 - val_ia: 0.6276 - val_loss: 0.0670 - val_mae: 0.1582 - val_rmse: 0.2066 - val_smape: 0.3929

Epoch 7/64

1916/1916 - 25s - 13ms/step - ia: 0.8652 - loss: 0.0865 - mae: 0.1835 - rmse: 0.2671 - smape: 0.4240 - val_ia: 0.6719 - val_loss: 0.0677 - val_mae: 0.1470 - val_rmse: 0.2017 - val_smape: 0.3616

Epoch 8/64

1916/1916 - 27s - 14ms/step - ia: 0.8663 - loss: 0.0856 - mae: 0.1820 - rmse: 0.2644 - smape: 0.4214 - val_ia: 0.6412 - val_loss: 0.0599 - val_mae: 0.1469 - val_rmse: 0.1971 - val_smape: 0.3729

Epoch 9/64

1916/1916 - 24s - 13ms/step - ia: 0.8685 - loss: 0.0828 - mae: 0.1795 - rmse: 0.2601 - smape: 0.4156 - val_ia: 0.6633 - val_loss: 0.0596 - val_mae: 0.1408 - val_rmse: 0.1935 - val_smape: 0.3666

Epoch 10/64

1916/1916 - 24s - 12ms/step - ia: 0.8690 - loss: 0.0815 - mae: 0.1789 - rmse: 0.2592 - smape: 0.4169 - val_ia: 0.6900 - val_loss: 0.0570 - val_mae: 0.1334 - val_rmse: 0.1886 - val_smape: 0.3500

Epoch 11/64

1916/1916 - 24s - 13ms/step - ia: 0.8692 - loss: 0.0817 - mae: 0.1779 - rmse: 0.2584 - smape: 0.4149 - val_ia: 0.6659 - val_loss: 0.0544 - val_mae: 0.1351 - val_rmse: 0.1862 - val_smape: 0.3589

Epoch 12/64

1916/1916 - 24s - 13ms/step - ia: 0.8700 - loss: 0.0794 - mae: 0.1770 - rmse: 0.2565 - smape: 0.4162 - val_ia: 0.6681 - val_loss: 0.0560 - val_mae: 0.1375 - val_rmse: 0.1872 - val_smape: 0.3567

Epoch 13/64

1916/1916 - 24s - 13ms/step - ia: 0.8697 - loss: 0.0803 - mae: 0.1773 - rmse: 0.2576 - smape: 0.4117 - val_ia: 0.6685 - val_loss: 0.0551 - val_mae: 0.1360 - val_rmse: 0.1864 - val_smape: 0.3595

Epoch 14/64

1916/1916 - 24s - 12ms/step - ia: 0.8712 - loss: 0.0796 - mae: 0.1767 - rmse: 0.2558 - smape: 0.4135 - val_ia: 0.6575 - val_loss: 0.0579 - val_mae: 0.1426 - val_rmse: 0.1922 - val_smape: 0.3772

Epoch 15/64

1916/1916 - 24s - 13ms/step - ia: 0.8707 - loss: 0.0795 - mae: 0.1767 - rmse: 0.2564 - smape: 0.4124 - val_ia: 0.6665 - val_loss: 0.0566 - val_mae: 0.1378 - val_rmse: 0.1894 - val_smape: 0.3636

Epoch 16/64

1916/1916 - 24s - 13ms/step - ia: 0.8707 - loss: 0.0772 - mae: 0.1754 - rmse: 0.2533 - smape: 0.4132 - val_ia: 0.6782 - val_loss: 0.0530 - val_mae: 0.1318 - val_rmse: 0.1827 - val_smape: 0.3571

Epoch 17/64

1916/1916 - 24s - 12ms/step - ia: 0.8723 - loss: 0.0766 - mae: 0.1741 - rmse: 0.2512 - smape: 0.4085 - val_ia: 0.6743 - val_loss: 0.0547 - val_mae: 0.1345 - val_rmse: 0.1857 - val_smape: 0.3599

Epoch 18/64

1916/1916 - 23s - 12ms/step - ia: 0.8731 - loss: 0.0754 - mae: 0.1733 - rmse: 0.2495 - smape: 0.4088 - val_ia: 0.6694 - val_loss: 0.0570 - val_mae: 0.1373 - val_rmse: 0.1881 - val_smape: 0.3523

Epoch 19/64

1916/1916 - 24s - 12ms/step - ia: 0.8730 - loss: 0.0760 - mae: 0.1728 - rmse: 0.2509 - smape: 0.4081 - val_ia: 0.6983 - val_loss: 0.0538 - val_mae: 0.1283 - val_rmse: 0.1812 - val_smape: 0.3446

Epoch 20/64

1916/1916 - 24s - 12ms/step - ia: 0.8738 - loss: 0.0771 - mae: 0.1732 - rmse: 0.2522 - smape: 0.4055 - val_ia: 0.6608 - val_loss: 0.0554 - val_mae: 0.1397 - val_rmse: 0.1891 - val_smape: 0.3605

Epoch 21/64

1916/1916 - 24s - 12ms/step - ia: 0.8722 - loss: 0.0764 - mae: 0.1740 - rmse: 0.2515 - smape: 0.4089 - val_ia: 0.6807 - val_loss: 0.0519 - val_mae: 0.1310 - val_rmse: 0.1815 - val_smape: 0.3515

Epoch 22/64

1916/1916 - 24s - 12ms/step - ia: 0.8733 - loss: 0.0746 - mae: 0.1722 - rmse: 0.2484 - smape: 0.4069 - val_ia: 0.6746 - val_loss: 0.0534 - val_mae: 0.1338 - val_rmse: 0.1845 - val_smape: 0.3594

Epoch 23/64

1916/1916 - 25s - 13ms/step - ia: 0.8738 - loss: 0.0742 - mae: 0.1718 - rmse: 0.2485 - smape: 0.4046 - val_ia: 0.6797 - val_loss: 0.0550 - val_mae: 0.1346 - val_rmse: 0.1852 - val_smape: 0.3515

Epoch 24/64

1916/1916 - 29s - 15ms/step - ia: 0.8742 - loss: 0.0731 - mae: 0.1709 - rmse: 0.2468 - smape: 0.4049 - val_ia: 0.6750 - val_loss: 0.0539 - val_mae: 0.1330 - val_rmse: 0.1848 - val_smape: 0.3549

Epoch 25/64

1916/1916 - 22s - 12ms/step - ia: 0.8739 - loss: 0.0751 - mae: 0.1722 - rmse: 0.2496 - smape: 0.4038 - val_ia: 0.6756 - val_loss: 0.0572 - val_mae: 0.1362 - val_rmse: 0.1877 - val_smape: 0.3566

Epoch 26/64

1916/1916 - 18s - 9ms/step - ia: 0.8749 - loss: 0.0728 - mae: 0.1711 - rmse: 0.2472 - smape: 0.4038 - val_ia: 0.6842 - val_loss: 0.0543 - val_mae: 0.1315 - val_rmse: 0.1844 - val_smape: 0.3503

Epoch 27/64

1916/1916 - 24s - 13ms/step - ia: 0.8748 - loss: 0.0723 - mae: 0.1708 - rmse: 0.2462 - smape: 0.4021 - val_ia: 0.6829 - val_loss: 0.0540 - val_mae: 0.1321 - val_rmse: 0.1841 - val_smape: 0.3533

Epoch 28/64

1916/1916 - 23s - 12ms/step - ia: 0.8749 - loss: 0.0726 - mae: 0.1705 - rmse: 0.2463 - smape: 0.4020 - val_ia: 0.6626 - val_loss: 0.0574 - val_mae: 0.1379 - val_rmse: 0.1896 - val_smape: 0.3663

Epoch 29/64

1916/1916 - 24s - 13ms/step - ia: 0.8751 - loss: 0.0719 - mae: 0.1701 - rmse: 0.2447 - smape: 0.4022 - val_ia: 0.6677 - val_loss: 0.0550 - val_mae: 0.1372 - val_rmse: 0.1865 - val_smape: 0.3563

Epoch 30/64

1916/1916 - 26s - 13ms/step - ia: 0.8752 - loss: 0.0716 - mae: 0.1699 - rmse: 0.2445 - smape: 0.4032 - val_ia: 0.6296 - val_loss: 0.0639 - val_mae: 0.1557 - val_rmse: 0.2037 - val_smape: 0.3864

Epoch 31/64

1916/1916 - 25s - 13ms/step - ia: 0.8745 - loss: 0.0743 - mae: 0.1711 - rmse: 0.2476 - smape: 0.4037 - val_ia: 0.6858 - val_loss: 0.0541 - val_mae: 0.1315 - val_rmse: 0.1835 - val_smape: 0.3533

Epoch 32/64

1916/1916 - 26s - 13ms/step - ia: 0.8762 - loss: 0.0712 - mae: 0.1697 - rmse: 0.2441 - smape: 0.4007 - val_ia: 0.6887 - val_loss: 0.0538 - val_mae: 0.1309 - val_rmse: 0.1837 - val_smape: 0.3566

Epoch 33/64

1916/1916 - 24s - 12ms/step - ia: 0.8764 - loss: 0.0696 - mae: 0.1688 - rmse: 0.2418 - smape: 0.4009 - val_ia: 0.6778 - val_loss: 0.0541 - val_mae: 0.1340 - val_rmse: 0.1843 - val_smape: 0.3568

Epoch 34/64

1916/1916 - 24s - 12ms/step - ia: 0.8756 - loss: 0.0710 - mae: 0.1694 - rmse: 0.2439 - smape: 0.4029 - val_ia: 0.6643 - val_loss: 0.0535 - val_mae: 0.1360 - val_rmse: 0.1865 - val_smape: 0.3617

Epoch 35/64

1916/1916 - 26s - 14ms/step - ia: 0.8758 - loss: 0.0694 - mae: 0.1686 - rmse: 0.2423 - smape: 0.3985 - val_ia: 0.6757 - val_loss: 0.0526 - val_mae: 0.1319 - val_rmse: 0.1821 - val_smape: 0.3542

Epoch 36/64

1916/1916 - 25s - 13ms/step - ia: 0.8761 - loss: 0.0705 - mae: 0.1684 - rmse: 0.2422 - smape: 0.3991 - val_ia: 0.6869 - val_loss: 0.0565 - val_mae: 0.1354 - val_rmse: 0.1888 - val_smape: 0.3563

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 70%|███████   | 35/50 [13:17:06<2:51:20, 685.38s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 20s - 41ms/step - ia: 0.8017 - loss: 0.1748 - mae: 0.2707 - rmse: 0.3970 - smape: 0.5908 - val_ia: 0.7589 - val_loss: 0.0836 - val_mae: 0.1810 - val_rmse: 0.2537 - val_smape: 0.4327

Epoch 2/64

479/479 - 11s - 24ms/step - ia: 0.8539 - loss: 0.1049 - mae: 0.2090 - rmse: 0.3134 - smape: 0.4764 - val_ia: 0.8142 - val_loss: 0.0636 - val_mae: 0.1475 - val_rmse: 0.2242 - val_smape: 0.3900

Epoch 3/64

479/479 - 12s - 24ms/step - ia: 0.8633 - loss: 0.0937 - mae: 0.1964 - rmse: 0.2965 - smape: 0.4529 - val_ia: 0.8248 - val_loss: 0.0621 - val_mae: 0.1425 - val_rmse: 0.2179 - val_smape: 0.3710

Epoch 4/64

479/479 - 11s - 23ms/step - ia: 0.8657 - loss: 0.0925 - mae: 0.1929 - rmse: 0.2925 - smape: 0.4433 - val_ia: 0.8218 - val_loss: 0.0626 - val_mae: 0.1440 - val_rmse: 0.2183 - val_smape: 0.3664

Epoch 5/64

479/479 - 11s - 23ms/step - ia: 0.8704 - loss: 0.0883 - mae: 0.1865 - rmse: 0.2868 - smape: 0.4306 - val_ia: 0.8077 - val_loss: 0.0559 - val_mae: 0.1440 - val_rmse: 0.2102 - val_smape: 0.3721

Epoch 6/64

479/479 - 11s - 23ms/step - ia: 0.8734 - loss: 0.0845 - mae: 0.1824 - rmse: 0.2805 - smape: 0.4210 - val_ia: 0.8271 - val_loss: 0.0591 - val_mae: 0.1413 - val_rmse: 0.2162 - val_smape: 0.3700

Epoch 7/64

479/479 - 11s - 22ms/step - ia: 0.8741 - loss: 0.0810 - mae: 0.1807 - rmse: 0.2754 - smape: 0.4216 - val_ia: 0.8141 - val_loss: 0.0564 - val_mae: 0.1418 - val_rmse: 0.2092 - val_smape: 0.3693

Epoch 8/64

479/479 - 19s - 40ms/step - ia: 0.8734 - loss: 0.0851 - mae: 0.1825 - rmse: 0.2809 - smape: 0.4187 - val_ia: 0.8047 - val_loss: 0.0587 - val_mae: 0.1482 - val_rmse: 0.2146 - val_smape: 0.3905

Epoch 9/64

479/479 - 11s - 22ms/step - ia: 0.8766 - loss: 0.0806 - mae: 0.1781 - rmse: 0.2735 - smape: 0.4150 - val_ia: 0.8366 - val_loss: 0.0582 - val_mae: 0.1359 - val_rmse: 0.2117 - val_smape: 0.3530

Epoch 10/64

479/479 - 11s - 23ms/step - ia: 0.8781 - loss: 0.0800 - mae: 0.1761 - rmse: 0.2724 - smape: 0.4119 - val_ia: 0.8102 - val_loss: 0.0564 - val_mae: 0.1423 - val_rmse: 0.2103 - val_smape: 0.3730

Epoch 11/64

479/479 - 11s - 23ms/step - ia: 0.8781 - loss: 0.0795 - mae: 0.1762 - rmse: 0.2713 - smape: 0.4077 - val_ia: 0.8163 - val_loss: 0.0552 - val_mae: 0.1393 - val_rmse: 0.2076 - val_smape: 0.3681

Epoch 12/64

479/479 - 11s - 22ms/step - ia: 0.8791 - loss: 0.0778 - mae: 0.1743 - rmse: 0.2687 - smape: 0.4098 - val_ia: 0.8343 - val_loss: 0.0558 - val_mae: 0.1366 - val_rmse: 0.2072 - val_smape: 0.3562

Epoch 13/64

479/479 - 11s - 22ms/step - ia: 0.8781 - loss: 0.0808 - mae: 0.1760 - rmse: 0.2734 - smape: 0.4105 - val_ia: 0.8191 - val_loss: 0.0562 - val_mae: 0.1389 - val_rmse: 0.2083 - val_smape: 0.3724

Epoch 14/64

479/479 - 20s - 43ms/step - ia: 0.8785 - loss: 0.0774 - mae: 0.1750 - rmse: 0.2686 - smape: 0.4112 - val_ia: 0.8080 - val_loss: 0.0568 - val_mae: 0.1442 - val_rmse: 0.2097 - val_smape: 0.3763

Epoch 15/64

479/479 - 11s - 23ms/step - ia: 0.8788 - loss: 0.0778 - mae: 0.1749 - rmse: 0.2689 - smape: 0.4122 - val_ia: 0.8251 - val_loss: 0.0548 - val_mae: 0.1354 - val_rmse: 0.2051 - val_smape: 0.3596

Epoch 16/64

479/479 - 11s - 23ms/step - ia: 0.8794 - loss: 0.0770 - mae: 0.1735 - rmse: 0.2675 - smape: 0.4078 - val_ia: 0.8437 - val_loss: 0.0541 - val_mae: 0.1290 - val_rmse: 0.2022 - val_smape: 0.3478

Epoch 17/64

479/479 - 11s - 24ms/step - ia: 0.8800 - loss: 0.0763 - mae: 0.1728 - rmse: 0.2659 - smape: 0.4060 - val_ia: 0.8218 - val_loss: 0.0575 - val_mae: 0.1406 - val_rmse: 0.2094 - val_smape: 0.3731

Epoch 18/64

479/479 - 11s - 24ms/step - ia: 0.8802 - loss: 0.0775 - mae: 0.1731 - rmse: 0.2680 - smape: 0.4050 - val_ia: 0.8394 - val_loss: 0.0557 - val_mae: 0.1319 - val_rmse: 0.2049 - val_smape: 0.3499

Epoch 19/64

479/479 - 11s - 23ms/step - ia: 0.8817 - loss: 0.0744 - mae: 0.1707 - rmse: 0.2633 - smape: 0.4034 - val_ia: 0.7987 - val_loss: 0.0602 - val_mae: 0.1489 - val_rmse: 0.2138 - val_smape: 0.3830

Epoch 20/64

479/479 - 20s - 43ms/step - ia: 0.8815 - loss: 0.0730 - mae: 0.1706 - rmse: 0.2601 - smape: 0.4054 - val_ia: 0.8357 - val_loss: 0.0641 - val_mae: 0.1328 - val_rmse: 0.2065 - val_smape: 0.3484

Epoch 21/64

479/479 - 11s - 22ms/step - ia: 0.8812 - loss: 0.0742 - mae: 0.1719 - rmse: 0.2637 - smape: 0.4042 - val_ia: 0.8395 - val_loss: 0.0575 - val_mae: 0.1315 - val_rmse: 0.2039 - val_smape: 0.3553

Epoch 22/64

479/479 - 11s - 23ms/step - ia: 0.8821 - loss: 0.0730 - mae: 0.1702 - rmse: 0.2608 - smape: 0.4032 - val_ia: 0.8357 - val_loss: 0.0570 - val_mae: 0.1310 - val_rmse: 0.2033 - val_smape: 0.3526

Epoch 23/64

479/479 - 11s - 22ms/step - ia: 0.8816 - loss: 0.0741 - mae: 0.1710 - rmse: 0.2634 - smape: 0.3993 - val_ia: 0.8113 - val_loss: 0.0611 - val_mae: 0.1465 - val_rmse: 0.2165 - val_smape: 0.3854

Epoch 24/64

479/479 - 20s - 43ms/step - ia: 0.8820 - loss: 0.0736 - mae: 0.1706 - rmse: 0.2619 - smape: 0.4026 - val_ia: 0.8222 - val_loss: 0.0568 - val_mae: 0.1384 - val_rmse: 0.2066 - val_smape: 0.3635

Epoch 25/64

479/479 - 11s - 22ms/step - ia: 0.8823 - loss: 0.0723 - mae: 0.1696 - rmse: 0.2602 - smape: 0.3993 - val_ia: 0.8250 - val_loss: 0.0577 - val_mae: 0.1349 - val_rmse: 0.2054 - val_smape: 0.3590

Epoch 26/64

479/479 - 11s - 22ms/step - ia: 0.8832 - loss: 0.0720 - mae: 0.1688 - rmse: 0.2595 - smape: 0.3984 - val_ia: 0.8269 - val_loss: 0.0586 - val_mae: 0.1368 - val_rmse: 0.2086 - val_smape: 0.3685

Epoch 27/64

479/479 - 21s - 43ms/step - ia: 0.8826 - loss: 0.0726 - mae: 0.1698 - rmse: 0.2600 - smape: 0.4020 - val_ia: 0.8306 - val_loss: 0.0624 - val_mae: 0.1374 - val_rmse: 0.2080 - val_smape: 0.3610

Epoch 28/64

479/479 - 11s - 23ms/step - ia: 0.8822 - loss: 0.0727 - mae: 0.1700 - rmse: 0.2602 - smape: 0.4030 - val_ia: 0.7947 - val_loss: 0.0624 - val_mae: 0.1570 - val_rmse: 0.2200 - val_smape: 0.3882

Epoch 29/64

479/479 - 11s - 23ms/step - ia: 0.8838 - loss: 0.0708 - mae: 0.1679 - rmse: 0.2571 - smape: 0.3973 - val_ia: 0.8331 - val_loss: 0.0653 - val_mae: 0.1383 - val_rmse: 0.2131 - val_smape: 0.3575

Epoch 30/64

479/479 - 11s - 23ms/step - ia: 0.8833 - loss: 0.0714 - mae: 0.1683 - rmse: 0.2582 - smape: 0.3975 - val_ia: 0.8309 - val_loss: 0.0606 - val_mae: 0.1340 - val_rmse: 0.2070 - val_smape: 0.3538

Epoch 31/64

479/479 - 11s - 23ms/step - ia: 0.8840 - loss: 0.0706 - mae: 0.1671 - rmse: 0.2570 - smape: 0.3953 - val_ia: 0.8309 - val_loss: 0.0581 - val_mae: 0.1323 - val_rmse: 0.2031 - val_smape: 0.3519

Epoch 31: early stopping

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:10 967ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 72%|███████▏  | 36/50 [13:23:45<2:19:52, 599.46s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1916/1916 - 22s - 12ms/step - ia: 0.4413 - loss: 0.6322 - mae: 0.5856 - rmse: 0.7523 - smape: 1.2684 - val_ia: 0.3070 - val_loss: 0.2842 - val_mae: 0.3783 - val_rmse: 0.4434 - val_smape: 0.8094

Epoch 2/64

1916/1916 - 14s - 7ms/step - ia: 0.6306 - loss: 0.4040 - mae: 0.4463 - rmse: 0.6026 - smape: 0.9083 - val_ia: 0.3312 - val_loss: 0.2408 - val_mae: 0.3391 - val_rmse: 0.4047 - val_smape: 0.7348

Epoch 3/64

1916/1916 - 20s - 11ms/step - ia: 0.6599 - loss: 0.3582 - mae: 0.4176 - rmse: 0.5676 - smape: 0.8525 - val_ia: 0.3489 - val_loss: 0.2223 - val_mae: 0.3231 - val_rmse: 0.3876 - val_smape: 0.7023

Epoch 4/64

1916/1916 - 13s - 7ms/step - ia: 0.6780 - loss: 0.3337 - mae: 0.3990 - rmse: 0.5457 - smape: 0.8167 - val_ia: 0.3639 - val_loss: 0.2036 - val_mae: 0.3117 - val_rmse: 0.3742 - val_smape: 0.6844

Epoch 5/64

1916/1916 - 14s - 7ms/step - ia: 0.6895 - loss: 0.3116 - mae: 0.3861 - rmse: 0.5269 - smape: 0.7985 - val_ia: 0.3831 - val_loss: 0.1875 - val_mae: 0.2984 - val_rmse: 0.3598 - val_smape: 0.6581

Epoch 6/64

1916/1916 - 13s - 7ms/step - ia: 0.7069 - loss: 0.2820 - mae: 0.3683 - rmse: 0.5026 - smape: 0.7659 - val_ia: 0.4031 - val_loss: 0.1624 - val_mae: 0.2778 - val_rmse: 0.3384 - val_smape: 0.6264

Epoch 7/64

1916/1916 - 13s - 7ms/step - ia: 0.7157 - loss: 0.2735 - mae: 0.3597 - rmse: 0.4938 - smape: 0.7429 - val_ia: 0.4120 - val_loss: 0.1568 - val_mae: 0.2748 - val_rmse: 0.3335 - val_smape: 0.6171

Epoch 8/64

1916/1916 - 13s - 7ms/step - ia: 0.7218 - loss: 0.2638 - mae: 0.3524 - rmse: 0.4824 - smape: 0.7309 - val_ia: 0.4285 - val_loss: 0.1469 - val_mae: 0.2611 - val_rmse: 0.3204 - val_smape: 0.5933

Epoch 9/64

1916/1916 - 13s - 7ms/step - ia: 0.7306 - loss: 0.2489 - mae: 0.3444 - rmse: 0.4702 - smape: 0.7188 - val_ia: 0.4390 - val_loss: 0.1388 - val_mae: 0.2545 - val_rmse: 0.3126 - val_smape: 0.5804

Epoch 10/64

1916/1916 - 13s - 7ms/step - ia: 0.7320 - loss: 0.2498 - mae: 0.3421 - rmse: 0.4695 - smape: 0.7125 - val_ia: 0.4461 - val_loss: 0.1344 - val_mae: 0.2484 - val_rmse: 0.3064 - val_smape: 0.5668

Epoch 11/64

1916/1916 - 13s - 7ms/step - ia: 0.7378 - loss: 0.2394 - mae: 0.3354 - rmse: 0.4606 - smape: 0.6963 - val_ia: 0.4569 - val_loss: 0.1249 - val_mae: 0.2405 - val_rmse: 0.2978 - val_smape: 0.5566

Epoch 12/64

1916/1916 - 14s - 7ms/step - ia: 0.7438 - loss: 0.2324 - mae: 0.3289 - rmse: 0.4526 - smape: 0.6842 - val_ia: 0.4580 - val_loss: 0.1253 - val_mae: 0.2422 - val_rmse: 0.2979 - val_smape: 0.5562

Epoch 13/64

1916/1916 - 14s - 7ms/step - ia: 0.7480 - loss: 0.2195 - mae: 0.3239 - rmse: 0.4420 - smape: 0.6783 - val_ia: 0.4714 - val_loss: 0.1181 - val_mae: 0.2321 - val_rmse: 0.2885 - val_smape: 0.5403

Epoch 14/64

1916/1916 - 14s - 7ms/step - ia: 0.7505 - loss: 0.2223 - mae: 0.3223 - rmse: 0.4430 - smape: 0.6713 - val_ia: 0.4750 - val_loss: 0.1165 - val_mae: 0.2314 - val_rmse: 0.2865 - val_smape: 0.5379

Epoch 15/64

1916/1916 - 13s - 7ms/step - ia: 0.7535 - loss: 0.2165 - mae: 0.3177 - rmse: 0.4380 - smape: 0.6658 - val_ia: 0.4839 - val_loss: 0.1112 - val_mae: 0.2269 - val_rmse: 0.2809 - val_smape: 0.5302

Epoch 16/64

1916/1916 - 14s - 7ms/step - ia: 0.7556 - loss: 0.2119 - mae: 0.3148 - rmse: 0.4323 - smape: 0.6586 - val_ia: 0.4914 - val_loss: 0.1069 - val_mae: 0.2207 - val_rmse: 0.2751 - val_smape: 0.5219

Epoch 17/64

1916/1916 - 12s - 6ms/step - ia: 0.7586 - loss: 0.2083 - mae: 0.3124 - rmse: 0.4295 - smape: 0.6542 - val_ia: 0.4954 - val_loss: 0.1056 - val_mae: 0.2187 - val_rmse: 0.2728 - val_smape: 0.5175

Epoch 18/64

1916/1916 - 10s - 5ms/step - ia: 0.7608 - loss: 0.2027 - mae: 0.3083 - rmse: 0.4233 - smape: 0.6472 - val_ia: 0.4995 - val_loss: 0.1057 - val_mae: 0.2177 - val_rmse: 0.2714 - val_smape: 0.5126

Epoch 19/64

1916/1916 - 10s - 5ms/step - ia: 0.7647 - loss: 0.2027 - mae: 0.3053 - rmse: 0.4223 - smape: 0.6401 - val_ia: 0.5010 - val_loss: 0.1072 - val_mae: 0.2201 - val_rmse: 0.2726 - val_smape: 0.5124

Epoch 20/64

1916/1916 - 10s - 5ms/step - ia: 0.7648 - loss: 0.2026 - mae: 0.3044 - rmse: 0.4218 - smape: 0.6382 - val_ia: 0.5148 - val_loss: 0.0987 - val_mae: 0.2097 - val_rmse: 0.2629 - val_smape: 0.4996

Epoch 21/64

1916/1916 - 12s - 6ms/step - ia: 0.7692 - loss: 0.1941 - mae: 0.2991 - rmse: 0.4129 - smape: 0.6302 - val_ia: 0.5151 - val_loss: 0.1006 - val_mae: 0.2114 - val_rmse: 0.2637 - val_smape: 0.4972

Epoch 22/64

1916/1916 - 14s - 7ms/step - ia: 0.7694 - loss: 0.1953 - mae: 0.2995 - rmse: 0.4142 - smape: 0.6300 - val_ia: 0.5136 - val_loss: 0.1011 - val_mae: 0.2132 - val_rmse: 0.2650 - val_smape: 0.4996

Epoch 23/64

1916/1916 - 13s - 7ms/step - ia: 0.7717 - loss: 0.1923 - mae: 0.2968 - rmse: 0.4107 - smape: 0.6267 - val_ia: 0.5232 - val_loss: 0.0943 - val_mae: 0.2054 - val_rmse: 0.2576 - val_smape: 0.4902

Epoch 24/64

1916/1916 - 13s - 7ms/step - ia: 0.7730 - loss: 0.1914 - mae: 0.2954 - rmse: 0.4084 - smape: 0.6243 - val_ia: 0.5260 - val_loss: 0.0924 - val_mae: 0.2038 - val_rmse: 0.2555 - val_smape: 0.4875

Epoch 25/64

1916/1916 - 13s - 7ms/step - ia: 0.7740 - loss: 0.1940 - mae: 0.2939 - rmse: 0.4097 - smape: 0.6190 - val_ia: 0.5339 - val_loss: 0.0897 - val_mae: 0.1988 - val_rmse: 0.2511 - val_smape: 0.4806

Epoch 26/64

1916/1916 - 13s - 7ms/step - ia: 0.7769 - loss: 0.1840 - mae: 0.2903 - rmse: 0.4006 - smape: 0.6157 - val_ia: 0.5281 - val_loss: 0.0938 - val_mae: 0.2038 - val_rmse: 0.2553 - val_smape: 0.4838

Epoch 27/64

1916/1916 - 13s - 7ms/step - ia: 0.7759 - loss: 0.1884 - mae: 0.2919 - rmse: 0.4051 - smape: 0.6137 - val_ia: 0.5363 - val_loss: 0.0928 - val_mae: 0.1996 - val_rmse: 0.2517 - val_smape: 0.4769

Epoch 28/64

1916/1916 - 13s - 7ms/step - ia: 0.7779 - loss: 0.1851 - mae: 0.2884 - rmse: 0.4017 - smape: 0.6078 - val_ia: 0.5395 - val_loss: 0.0902 - val_mae: 0.1977 - val_rmse: 0.2495 - val_smape: 0.4741

Epoch 29/64

1916/1916 - 21s - 11ms/step - ia: 0.7800 - loss: 0.1817 - mae: 0.2861 - rmse: 0.3986 - smape: 0.6050 - val_ia: 0.5409 - val_loss: 0.0899 - val_mae: 0.1977 - val_rmse: 0.2490 - val_smape: 0.4724

Epoch 30/64

1916/1916 - 13s - 7ms/step - ia: 0.7811 - loss: 0.1857 - mae: 0.2871 - rmse: 0.4010 - smape: 0.6028 - val_ia: 0.5425 - val_loss: 0.0912 - val_mae: 0.1981 - val_rmse: 0.2491 - val_smape: 0.4701

Epoch 31/64

1916/1916 - 13s - 7ms/step - ia: 0.7836 - loss: 0.1784 - mae: 0.2834 - rmse: 0.3935 - smape: 0.5984 - val_ia: 0.5416 - val_loss: 0.0935 - val_mae: 0.2007 - val_rmse: 0.2511 - val_smape: 0.4710

Epoch 32/64

1916/1916 - 13s - 7ms/step - ia: 0.7836 - loss: 0.1814 - mae: 0.2843 - rmse: 0.3964 - smape: 0.5991 - val_ia: 0.5438 - val_loss: 0.0920 - val_mae: 0.1986 - val_rmse: 0.2491 - val_smape: 0.4684

Epoch 33/64

1916/1916 - 13s - 7ms/step - ia: 0.7826 - loss: 0.1803 - mae: 0.2839 - rmse: 0.3966 - smape: 0.6004 - val_ia: 0.5522 - val_loss: 0.0862 - val_mae: 0.1921 - val_rmse: 0.2430 - val_smape: 0.4612

Epoch 34/64

1916/1916 - 13s - 7ms/step - ia: 0.7842 - loss: 0.1793 - mae: 0.2833 - rmse: 0.3943 - smape: 0.5987 - val_ia: 0.5506 - val_loss: 0.0894 - val_mae: 0.1942 - val_rmse: 0.2450 - val_smape: 0.4619

Epoch 35/64

1916/1916 - 16s - 8ms/step - ia: 0.7854 - loss: 0.1801 - mae: 0.2812 - rmse: 0.3949 - smape: 0.5938 - val_ia: 0.5484 - val_loss: 0.0903 - val_mae: 0.1969 - val_rmse: 0.2471 - val_smape: 0.4647

Epoch 36/64

1916/1916 - 14s - 7ms/step - ia: 0.7877 - loss: 0.1752 - mae: 0.2778 - rmse: 0.3890 - smape: 0.5865 - val_ia: 0.5503 - val_loss: 0.0917 - val_mae: 0.1968 - val_rmse: 0.2469 - val_smape: 0.4635

Epoch 37/64

1916/1916 - 15s - 8ms/step - ia: 0.7859 - loss: 0.1790 - mae: 0.2804 - rmse: 0.3928 - smape: 0.5897 - val_ia: 0.5601 - val_loss: 0.0839 - val_mae: 0.1879 - val_rmse: 0.2386 - val_smape: 0.4531

Epoch 38/64

1916/1916 - 14s - 7ms/step - ia: 0.7875 - loss: 0.1747 - mae: 0.2784 - rmse: 0.3893 - smape: 0.5901 - val_ia: 0.5568 - val_loss: 0.0915 - val_mae: 0.1950 - val_rmse: 0.2448 - val_smape: 0.4574

Epoch 39/64

1916/1916 - 14s - 7ms/step - ia: 0.7878 - loss: 0.1726 - mae: 0.2779 - rmse: 0.3882 - smape: 0.5846 - val_ia: 0.5536 - val_loss: 0.0873 - val_mae: 0.1932 - val_rmse: 0.2428 - val_smape: 0.4594

Epoch 40/64

1916/1916 - 11s - 6ms/step - ia: 0.7871 - loss: 0.1739 - mae: 0.2777 - rmse: 0.3882 - smape: 0.5871 - val_ia: 0.5509 - val_loss: 0.0948 - val_mae: 0.1989 - val_rmse: 0.2482 - val_smape: 0.4615

Epoch 41/64

1916/1916 - 23s - 12ms/step - ia: 0.7906 - loss: 0.1707 - mae: 0.2735 - rmse: 0.3825 - smape: 0.5811 - val_ia: 0.5568 - val_loss: 0.0857 - val_mae: 0.1918 - val_rmse: 0.2414 - val_smape: 0.4552

Epoch 42/64

1916/1916 - 14s - 7ms/step - ia: 0.7889 - loss: 0.1743 - mae: 0.2760 - rmse: 0.3866 - smape: 0.5816 - val_ia: 0.5659 - val_loss: 0.0850 - val_mae: 0.1872 - val_rmse: 0.2374 - val_smape: 0.4461

Epoch 43/64

1916/1916 - 13s - 7ms/step - ia: 0.7896 - loss: 0.1704 - mae: 0.2760 - rmse: 0.3847 - smape: 0.5858 - val_ia: 0.5624 - val_loss: 0.0878 - val_mae: 0.1905 - val_rmse: 0.2402 - val_smape: 0.4495

Epoch 44/64

1916/1916 - 20s - 11ms/step - ia: 0.7921 - loss: 0.1672 - mae: 0.2724 - rmse: 0.3805 - smape: 0.5791 - val_ia: 0.5645 - val_loss: 0.0837 - val_mae: 0.1877 - val_rmse: 0.2373 - val_smape: 0.4485

Epoch 45/64

1916/1916 - 12s - 6ms/step - ia: 0.7907 - loss: 0.1738 - mae: 0.2749 - rmse: 0.3861 - smape: 0.5785 - val_ia: 0.5693 - val_loss: 0.0832 - val_mae: 0.1845 - val_rmse: 0.2348 - val_smape: 0.4436

Epoch 46/64

1916/1916 - 13s - 7ms/step - ia: 0.7934 - loss: 0.1695 - mae: 0.2722 - rmse: 0.3819 - smape: 0.5757 - val_ia: 0.5593 - val_loss: 0.0895 - val_mae: 0.1938 - val_rmse: 0.2428 - val_smape: 0.4534

Epoch 47/64

1916/1916 - 16s - 9ms/step - ia: 0.7920 - loss: 0.1675 - mae: 0.2726 - rmse: 0.3810 - smape: 0.5792 - val_ia: 0.5683 - val_loss: 0.0843 - val_mae: 0.1863 - val_rmse: 0.2362 - val_smape: 0.4453

Epoch 48/64

1916/1916 - 20s - 10ms/step - ia: 0.7907 - loss: 0.1726 - mae: 0.2743 - rmse: 0.3855 - smape: 0.5787 - val_ia: 0.5626 - val_loss: 0.0874 - val_mae: 0.1909 - val_rmse: 0.2400 - val_smape: 0.4503

Epoch 49/64

1916/1916 - 16s - 8ms/step - ia: 0.7928 - loss: 0.1692 - mae: 0.2710 - rmse: 0.3822 - smape: 0.5739 - val_ia: 0.5707 - val_loss: 0.0847 - val_mae: 0.1862 - val_rmse: 0.2357 - val_smape: 0.4440

Epoch 50/64

1916/1916 - 18s - 9ms/step - ia: 0.7916 - loss: 0.1715 - mae: 0.2729 - rmse: 0.3829 - smape: 0.5760 - val_ia: 0.5630 - val_loss: 0.0887 - val_mae: 0.1912 - val_rmse: 0.2403 - val_smape: 0.4495

Epoch 51/64

1916/1916 - 17s - 9ms/step - ia: 0.7933 - loss: 0.1713 - mae: 0.2717 - rmse: 0.3825 - smape: 0.5737 - val_ia: 0.5699 - val_loss: 0.0884 - val_mae: 0.1888 - val_rmse: 0.2378 - val_smape: 0.4437

Epoch 52/64

1916/1916 - 16s - 8ms/step - ia: 0.7936 - loss: 0.1676 - mae: 0.2708 - rmse: 0.3807 - smape: 0.5712 - val_ia: 0.5747 - val_loss: 0.0813 - val_mae: 0.1831 - val_rmse: 0.2322 - val_smape: 0.4393

Epoch 53/64

1916/1916 - 16s - 9ms/step - ia: 0.7934 - loss: 0.1656 - mae: 0.2713 - rmse: 0.3805 - smape: 0.5743 - val_ia: 0.5795 - val_loss: 0.0815 - val_mae: 0.1810 - val_rmse: 0.2307 - val_smape: 0.4356

Epoch 54/64

1916/1916 - 16s - 8ms/step - ia: 0.7963 - loss: 0.1634 - mae: 0.2684 - rmse: 0.3770 - smape: 0.5685 - val_ia: 0.5726 - val_loss: 0.0869 - val_mae: 0.1877 - val_rmse: 0.2363 - val_smape: 0.4416

Epoch 55/64

1916/1916 - 15s - 8ms/step - ia: 0.7964 - loss: 0.1640 - mae: 0.2669 - rmse: 0.3755 - smape: 0.5670 - val_ia: 0.5698 - val_loss: 0.0875 - val_mae: 0.1888 - val_rmse: 0.2372 - val_smape: 0.4421

Epoch 56/64

1916/1916 - 16s - 8ms/step - ia: 0.7970 - loss: 0.1650 - mae: 0.2677 - rmse: 0.3769 - smape: 0.5685 - val_ia: 0.5719 - val_loss: 0.0888 - val_mae: 0.1889 - val_rmse: 0.2376 - val_smape: 0.4430

Epoch 57/64

1916/1916 - 16s - 8ms/step - ia: 0.7968 - loss: 0.1640 - mae: 0.2674 - rmse: 0.3769 - smape: 0.5659 - val_ia: 0.5842 - val_loss: 0.0793 - val_mae: 0.1781 - val_rmse: 0.2277 - val_smape: 0.4314

Epoch 58/64

1916/1916 - 16s - 8ms/step - ia: 0.7972 - loss: 0.1614 - mae: 0.2663 - rmse: 0.3736 - smape: 0.5651 - val_ia: 0.5825 - val_loss: 0.0795 - val_mae: 0.1788 - val_rmse: 0.2283 - val_smape: 0.4315

Epoch 59/64

1916/1916 - 21s - 11ms/step - ia: 0.7972 - loss: 0.1611 - mae: 0.2653 - rmse: 0.3735 - smape: 0.5632 - val_ia: 0.5789 - val_loss: 0.0845 - val_mae: 0.1836 - val_rmse: 0.2323 - val_smape: 0.4341

Epoch 60/64

1916/1916 - 16s - 8ms/step - ia: 0.7979 - loss: 0.1604 - mae: 0.2658 - rmse: 0.3724 - smape: 0.5618 - val_ia: 0.5720 - val_loss: 0.0921 - val_mae: 0.1912 - val_rmse: 0.2393 - val_smape: 0.4412

Epoch 61/64

1916/1916 - 16s - 8ms/step - ia: 0.7973 - loss: 0.1659 - mae: 0.2666 - rmse: 0.3778 - smape: 0.5652 - val_ia: 0.5798 - val_loss: 0.0851 - val_mae: 0.1840 - val_rmse: 0.2324 - val_smape: 0.4326

Epoch 62/64

1916/1916 - 16s - 8ms/step - ia: 0.7985 - loss: 0.1609 - mae: 0.2653 - rmse: 0.3730 - smape: 0.5637 - val_ia: 0.5828 - val_loss: 0.0849 - val_mae: 0.1831 - val_rmse: 0.2317 - val_smape: 0.4319

Epoch 63/64

1916/1916 - 16s - 8ms/step - ia: 0.7986 - loss: 0.1599 - mae: 0.2651 - rmse: 0.3708 - smape: 0.5658 - val_ia: 0.5838 - val_loss: 0.0859 - val_mae: 0.1826 - val_rmse: 0.2313 - val_smape: 0.4308

Epoch 64/64

1916/1916 - 15s - 8ms/step - ia: 0.7997 - loss: 0.1606 - mae: 0.2642 - rmse: 0.3718 - smape: 0.5609 - val_ia: 0.5839 - val_loss: 0.0837 - val_mae: 0.1814 - val_rmse: 0.2301 - val_smape: 0.4297

Restoring model weights from the end of the best epoch: 57.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:02 1s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step

 74%|███████▍  | 37/50 [13:39:32<2:32:27, 703.67s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

120/120 - 21s - 175ms/step - ia: 0.4997 - loss: 0.5824 - mae: 0.5359 - rmse: 0.7483 - smape: 1.1270 - val_ia: 0.6456 - val_loss: 0.2763 - val_mae: 0.3704 - val_rmse: 0.4958 - val_smape: 0.7797

Epoch 2/64

120/120 - 8s - 64ms/step - ia: 0.7073 - loss: 0.3251 - mae: 0.3910 - rmse: 0.5670 - smape: 0.7910 - val_ia: 0.7233 - val_loss: 0.1988 - val_mae: 0.3004 - val_rmse: 0.4216 - val_smape: 0.6596

Epoch 3/64

120/120 - 8s - 64ms/step - ia: 0.7433 - loss: 0.2661 - mae: 0.3513 - rmse: 0.5127 - smape: 0.7247 - val_ia: 0.7665 - val_loss: 0.1628 - val_mae: 0.2628 - val_rmse: 0.3827 - val_smape: 0.5919

Epoch 4/64

120/120 - 10s - 82ms/step - ia: 0.7641 - loss: 0.2321 - mae: 0.3278 - rmse: 0.4786 - smape: 0.6798 - val_ia: 0.7814 - val_loss: 0.1316 - val_mae: 0.2381 - val_rmse: 0.3440 - val_smape: 0.5616

Epoch 5/64

120/120 - 7s - 55ms/step - ia: 0.7776 - loss: 0.2086 - mae: 0.3108 - rmse: 0.4536 - smape: 0.6562 - val_ia: 0.8031 - val_loss: 0.1150 - val_mae: 0.2157 - val_rmse: 0.3212 - val_smape: 0.5269

Epoch 6/64

120/120 - 11s - 92ms/step - ia: 0.7878 - loss: 0.1889 - mae: 0.2979 - rmse: 0.4319 - smape: 0.6335 - val_ia: 0.8019 - val_loss: 0.1083 - val_mae: 0.2129 - val_rmse: 0.3126 - val_smape: 0.5202

Epoch 7/64

120/120 - 10s - 87ms/step - ia: 0.7969 - loss: 0.1794 - mae: 0.2870 - rmse: 0.4206 - smape: 0.6137 - val_ia: 0.8203 - val_loss: 0.0951 - val_mae: 0.1953 - val_rmse: 0.2926 - val_smape: 0.4889

Epoch 8/64

120/120 - 10s - 86ms/step - ia: 0.8029 - loss: 0.1697 - mae: 0.2791 - rmse: 0.4094 - smape: 0.6011 - val_ia: 0.8257 - val_loss: 0.0892 - val_mae: 0.1888 - val_rmse: 0.2835 - val_smape: 0.4748

Epoch 9/64

120/120 - 8s - 63ms/step - ia: 0.8081 - loss: 0.1621 - mae: 0.2721 - rmse: 0.4001 - smape: 0.5870 - val_ia: 0.8312 - val_loss: 0.0907 - val_mae: 0.1868 - val_rmse: 0.2837 - val_smape: 0.4662

Epoch 10/64

120/120 - 10s - 84ms/step - ia: 0.8153 - loss: 0.1534 - mae: 0.2632 - rmse: 0.3886 - smape: 0.5706 - val_ia: 0.8298 - val_loss: 0.0882 - val_mae: 0.1866 - val_rmse: 0.2797 - val_smape: 0.4646

Epoch 11/64

120/120 - 10s - 83ms/step - ia: 0.8168 - loss: 0.1506 - mae: 0.2610 - rmse: 0.3852 - smape: 0.5680 - val_ia: 0.8337 - val_loss: 0.0830 - val_mae: 0.1812 - val_rmse: 0.2727 - val_smape: 0.4571

Epoch 12/64

120/120 - 11s - 90ms/step - ia: 0.8184 - loss: 0.1495 - mae: 0.2586 - rmse: 0.3834 - smape: 0.5609 - val_ia: 0.8397 - val_loss: 0.0781 - val_mae: 0.1742 - val_rmse: 0.2650 - val_smape: 0.4478

Epoch 13/64

120/120 - 10s - 85ms/step - ia: 0.8231 - loss: 0.1429 - mae: 0.2528 - rmse: 0.3746 - smape: 0.5547 - val_ia: 0.8399 - val_loss: 0.0747 - val_mae: 0.1721 - val_rmse: 0.2592 - val_smape: 0.4423

Epoch 14/64

120/120 - 7s - 60ms/step - ia: 0.8230 - loss: 0.1441 - mae: 0.2526 - rmse: 0.3760 - smape: 0.5501 - val_ia: 0.8448 - val_loss: 0.0727 - val_mae: 0.1679 - val_rmse: 0.2558 - val_smape: 0.4327

Epoch 15/64

120/120 - 7s - 62ms/step - ia: 0.8262 - loss: 0.1399 - mae: 0.2488 - rmse: 0.3709 - smape: 0.5451 - val_ia: 0.8345 - val_loss: 0.0892 - val_mae: 0.1851 - val_rmse: 0.2771 - val_smape: 0.4473

Epoch 16/64

120/120 - 7s - 62ms/step - ia: 0.8272 - loss: 0.1398 - mae: 0.2472 - rmse: 0.3702 - smape: 0.5405 - val_ia: 0.8382 - val_loss: 0.0744 - val_mae: 0.1725 - val_rmse: 0.2587 - val_smape: 0.4449

Epoch 17/64

120/120 - 10s - 82ms/step - ia: 0.8288 - loss: 0.1363 - mae: 0.2451 - rmse: 0.3657 - smape: 0.5357 - val_ia: 0.8446 - val_loss: 0.0749 - val_mae: 0.1710 - val_rmse: 0.2572 - val_smape: 0.4279

Epoch 18/64

120/120 - 6s - 49ms/step - ia: 0.8308 - loss: 0.1321 - mae: 0.2427 - rmse: 0.3603 - smape: 0.5332 - val_ia: 0.8439 - val_loss: 0.0732 - val_mae: 0.1692 - val_rmse: 0.2552 - val_smape: 0.4307

Epoch 19/64

120/120 - 4s - 37ms/step - ia: 0.8336 - loss: 0.1295 - mae: 0.2386 - rmse: 0.3559 - smape: 0.5271 - val_ia: 0.8323 - val_loss: 0.0864 - val_mae: 0.1852 - val_rmse: 0.2717 - val_smape: 0.4392

Epoch 20/64

120/120 - 5s - 43ms/step - ia: 0.8347 - loss: 0.1279 - mae: 0.2375 - rmse: 0.3547 - smape: 0.5254 - val_ia: 0.8459 - val_loss: 0.0705 - val_mae: 0.1668 - val_rmse: 0.2513 - val_smape: 0.4280

Epoch 21/64

120/120 - 5s - 42ms/step - ia: 0.8354 - loss: 0.1288 - mae: 0.2365 - rmse: 0.3557 - smape: 0.5216 - val_ia: 0.8448 - val_loss: 0.0698 - val_mae: 0.1670 - val_rmse: 0.2494 - val_smape: 0.4236

Epoch 22/64

120/120 - 6s - 50ms/step - ia: 0.8370 - loss: 0.1257 - mae: 0.2339 - rmse: 0.3512 - smape: 0.5168 - val_ia: 0.8465 - val_loss: 0.0750 - val_mae: 0.1700 - val_rmse: 0.2554 - val_smape: 0.4230

Epoch 23/64

120/120 - 12s - 103ms/step - ia: 0.8377 - loss: 0.1240 - mae: 0.2336 - rmse: 0.3485 - smape: 0.5141 - val_ia: 0.8534 - val_loss: 0.0681 - val_mae: 0.1617 - val_rmse: 0.2456 - val_smape: 0.4138

Epoch 24/64

120/120 - 7s - 61ms/step - ia: 0.8392 - loss: 0.1223 - mae: 0.2315 - rmse: 0.3463 - smape: 0.5124 - val_ia: 0.8524 - val_loss: 0.0706 - val_mae: 0.1639 - val_rmse: 0.2492 - val_smape: 0.4141

Epoch 25/64

120/120 - 7s - 59ms/step - ia: 0.8404 - loss: 0.1206 - mae: 0.2294 - rmse: 0.3446 - smape: 0.5082 - val_ia: 0.8469 - val_loss: 0.0745 - val_mae: 0.1702 - val_rmse: 0.2536 - val_smape: 0.4129

Epoch 26/64

120/120 - 10s - 87ms/step - ia: 0.8404 - loss: 0.1208 - mae: 0.2296 - rmse: 0.3446 - smape: 0.5076 - val_ia: 0.8451 - val_loss: 0.0761 - val_mae: 0.1712 - val_rmse: 0.2578 - val_smape: 0.4285

Epoch 27/64

120/120 - 7s - 59ms/step - ia: 0.8404 - loss: 0.1230 - mae: 0.2294 - rmse: 0.3468 - smape: 0.5053 - val_ia: 0.8619 - val_loss: 0.0691 - val_mae: 0.1553 - val_rmse: 0.2458 - val_smape: 0.4002

Epoch 28/64

120/120 - 7s - 60ms/step - ia: 0.8436 - loss: 0.1196 - mae: 0.2254 - rmse: 0.3420 - smape: 0.5018 - val_ia: 0.8439 - val_loss: 0.0720 - val_mae: 0.1700 - val_rmse: 0.2508 - val_smape: 0.4183

Epoch 29/64

120/120 - 10s - 86ms/step - ia: 0.8419 - loss: 0.1191 - mae: 0.2273 - rmse: 0.3421 - smape: 0.5019 - val_ia: 0.8594 - val_loss: 0.0636 - val_mae: 0.1545 - val_rmse: 0.2369 - val_smape: 0.3952

Epoch 30/64

120/120 - 7s - 60ms/step - ia: 0.8437 - loss: 0.1167 - mae: 0.2256 - rmse: 0.3392 - smape: 0.4977 - val_ia: 0.8535 - val_loss: 0.0702 - val_mae: 0.1634 - val_rmse: 0.2485 - val_smape: 0.4159

Epoch 31/64

120/120 - 7s - 59ms/step - ia: 0.8443 - loss: 0.1183 - mae: 0.2244 - rmse: 0.3400 - smape: 0.4963 - val_ia: 0.8534 - val_loss: 0.0725 - val_mae: 0.1651 - val_rmse: 0.2503 - val_smape: 0.4041

Epoch 32/64

120/120 - 10s - 86ms/step - ia: 0.8436 - loss: 0.1181 - mae: 0.2253 - rmse: 0.3408 - smape: 0.4972 - val_ia: 0.8569 - val_loss: 0.0645 - val_mae: 0.1561 - val_rmse: 0.2390 - val_smape: 0.3985

Epoch 33/64

120/120 - 7s - 61ms/step - ia: 0.8439 - loss: 0.1161 - mae: 0.2245 - rmse: 0.3379 - smape: 0.4973 - val_ia: 0.8511 - val_loss: 0.0735 - val_mae: 0.1667 - val_rmse: 0.2520 - val_smape: 0.4038

Epoch 34/64

120/120 - 7s - 58ms/step - ia: 0.8449 - loss: 0.1164 - mae: 0.2234 - rmse: 0.3382 - smape: 0.4934 - val_ia: 0.8562 - val_loss: 0.0634 - val_mae: 0.1568 - val_rmse: 0.2375 - val_smape: 0.3942

Epoch 35/64

120/120 - 7s - 61ms/step - ia: 0.8459 - loss: 0.1147 - mae: 0.2223 - rmse: 0.3355 - smape: 0.4910 - val_ia: 0.8633 - val_loss: 0.0647 - val_mae: 0.1523 - val_rmse: 0.2382 - val_smape: 0.3914

Epoch 36/64

120/120 - 7s - 59ms/step - ia: 0.8472 - loss: 0.1125 - mae: 0.2204 - rmse: 0.3327 - smape: 0.4858 - val_ia: 0.8595 - val_loss: 0.0662 - val_mae: 0.1563 - val_rmse: 0.2411 - val_smape: 0.3934

Epoch 37/64

120/120 - 7s - 57ms/step - ia: 0.8470 - loss: 0.1141 - mae: 0.2203 - rmse: 0.3345 - smape: 0.4885 - val_ia: 0.8466 - val_loss: 0.0678 - val_mae: 0.1662 - val_rmse: 0.2453 - val_smape: 0.4113

Epoch 38/64

120/120 - 11s - 88ms/step - ia: 0.8474 - loss: 0.1135 - mae: 0.2200 - rmse: 0.3337 - smape: 0.4866 - val_ia: 0.8679 - val_loss: 0.0634 - val_mae: 0.1490 - val_rmse: 0.2351 - val_smape: 0.3806

Epoch 39/64

120/120 - 10s - 87ms/step - ia: 0.8482 - loss: 0.1111 - mae: 0.2194 - rmse: 0.3293 - smape: 0.4863 - val_ia: 0.8517 - val_loss: 0.0633 - val_mae: 0.1589 - val_rmse: 0.2372 - val_smape: 0.3998

Epoch 40/64

120/120 - 7s - 61ms/step - ia: 0.8483 - loss: 0.1114 - mae: 0.2189 - rmse: 0.3311 - smape: 0.4838 - val_ia: 0.8333 - val_loss: 0.0777 - val_mae: 0.1817 - val_rmse: 0.2596 - val_smape: 0.4236

Epoch 41/64

120/120 - 7s - 59ms/step - ia: 0.8485 - loss: 0.1111 - mae: 0.2185 - rmse: 0.3295 - smape: 0.4852 - val_ia: 0.8537 - val_loss: 0.0701 - val_mae: 0.1636 - val_rmse: 0.2470 - val_smape: 0.3977

Epoch 42/64

120/120 - 7s - 60ms/step - ia: 0.8495 - loss: 0.1114 - mae: 0.2171 - rmse: 0.3301 - smape: 0.4819 - val_ia: 0.8541 - val_loss: 0.0730 - val_mae: 0.1656 - val_rmse: 0.2498 - val_smape: 0.3948

Epoch 43/64

120/120 - 7s - 60ms/step - ia: 0.8487 - loss: 0.1098 - mae: 0.2183 - rmse: 0.3283 - smape: 0.4849 - val_ia: 0.8326 - val_loss: 0.0716 - val_mae: 0.1800 - val_rmse: 0.2533 - val_smape: 0.4394

Epoch 44/64

120/120 - 7s - 57ms/step - ia: 0.8501 - loss: 0.1098 - mae: 0.2166 - rmse: 0.3280 - smape: 0.4798 - val_ia: 0.8560 - val_loss: 0.0682 - val_mae: 0.1621 - val_rmse: 0.2438 - val_smape: 0.3926

Epoch 45/64

120/120 - 7s - 58ms/step - ia: 0.8509 - loss: 0.1085 - mae: 0.2152 - rmse: 0.3260 - smape: 0.4761 - val_ia: 0.8677 - val_loss: 0.0599 - val_mae: 0.1485 - val_rmse: 0.2294 - val_smape: 0.3727

Epoch 46/64

120/120 - 7s - 62ms/step - ia: 0.8523 - loss: 0.1090 - mae: 0.2135 - rmse: 0.3268 - smape: 0.4766 - val_ia: 0.8709 - val_loss: 0.0576 - val_mae: 0.1436 - val_rmse: 0.2263 - val_smape: 0.3751

Epoch 47/64

120/120 - 7s - 59ms/step - ia: 0.8505 - loss: 0.1097 - mae: 0.2157 - rmse: 0.3286 - smape: 0.4757 - val_ia: 0.8513 - val_loss: 0.0625 - val_mae: 0.1609 - val_rmse: 0.2362 - val_smape: 0.3990

Epoch 48/64

120/120 - 10s - 86ms/step - ia: 0.8515 - loss: 0.1070 - mae: 0.2144 - rmse: 0.3243 - smape: 0.4763 - val_ia: 0.8559 - val_loss: 0.0672 - val_mae: 0.1605 - val_rmse: 0.2422 - val_smape: 0.3922

Epoch 49/64

120/120 - 7s - 61ms/step - ia: 0.8522 - loss: 0.1070 - mae: 0.2135 - rmse: 0.3241 - smape: 0.4725 - val_ia: 0.8674 - val_loss: 0.0609 - val_mae: 0.1481 - val_rmse: 0.2309 - val_smape: 0.3772

Epoch 50/64

120/120 - 7s - 61ms/step - ia: 0.8523 - loss: 0.1071 - mae: 0.2135 - rmse: 0.3240 - smape: 0.4756 - val_ia: 0.8572 - val_loss: 0.0665 - val_mae: 0.1590 - val_rmse: 0.2406 - val_smape: 0.3853

Epoch 51/64

120/120 - 7s - 60ms/step - ia: 0.8529 - loss: 0.1061 - mae: 0.2125 - rmse: 0.3225 - smape: 0.4717 - val_ia: 0.8514 - val_loss: 0.0633 - val_mae: 0.1609 - val_rmse: 0.2372 - val_smape: 0.3990

Epoch 52/64

120/120 - 10s - 80ms/step - ia: 0.8520 - loss: 0.1075 - mae: 0.2136 - rmse: 0.3246 - smape: 0.4749 - val_ia: 0.8594 - val_loss: 0.0603 - val_mae: 0.1531 - val_rmse: 0.2329 - val_smape: 0.4007

Epoch 53/64

120/120 - 11s - 91ms/step - ia: 0.8525 - loss: 0.1083 - mae: 0.2133 - rmse: 0.3254 - smape: 0.4700 - val_ia: 0.8407 - val_loss: 0.0682 - val_mae: 0.1716 - val_rmse: 0.2463 - val_smape: 0.4192

Epoch 54/64

120/120 - 11s - 90ms/step - ia: 0.8520 - loss: 0.1066 - mae: 0.2141 - rmse: 0.3236 - smape: 0.4730 - val_ia: 0.8574 - val_loss: 0.0671 - val_mae: 0.1592 - val_rmse: 0.2407 - val_smape: 0.3894

Epoch 55/64

120/120 - 7s - 60ms/step - ia: 0.8526 - loss: 0.1057 - mae: 0.2129 - rmse: 0.3226 - smape: 0.4704 - val_ia: 0.8464 - val_loss: 0.0725 - val_mae: 0.1706 - val_rmse: 0.2502 - val_smape: 0.4014

Epoch 56/64

120/120 - 7s - 62ms/step - ia: 0.8540 - loss: 0.1061 - mae: 0.2110 - rmse: 0.3226 - smape: 0.4685 - val_ia: 0.8465 - val_loss: 0.0784 - val_mae: 0.1745 - val_rmse: 0.2580 - val_smape: 0.4046

Epoch 57/64

120/120 - 10s - 86ms/step - ia: 0.8544 - loss: 0.1044 - mae: 0.2103 - rmse: 0.3198 - smape: 0.4675 - val_ia: 0.8574 - val_loss: 0.0662 - val_mae: 0.1598 - val_rmse: 0.2393 - val_smape: 0.3860

Epoch 58/64

120/120 - 7s - 60ms/step - ia: 0.8551 - loss: 0.1039 - mae: 0.2095 - rmse: 0.3192 - smape: 0.4660 - val_ia: 0.8620 - val_loss: 0.0628 - val_mae: 0.1542 - val_rmse: 0.2344 - val_smape: 0.3886

Epoch 59/64

120/120 - 7s - 56ms/step - ia: 0.8543 - loss: 0.1033 - mae: 0.2105 - rmse: 0.3184 - smape: 0.4655 - val_ia: 0.8587 - val_loss: 0.0636 - val_mae: 0.1570 - val_rmse: 0.2371 - val_smape: 0.3882

Epoch 60/64

120/120 - 7s - 61ms/step - ia: 0.8553 - loss: 0.1029 - mae: 0.2094 - rmse: 0.3178 - smape: 0.4673 - val_ia: 0.8633 - val_loss: 0.0606 - val_mae: 0.1517 - val_rmse: 0.2324 - val_smape: 0.3881

Epoch 61/64

120/120 - 7s - 60ms/step - ia: 0.8557 - loss: 0.1018 - mae: 0.2087 - rmse: 0.3162 - smape: 0.4653 - val_ia: 0.8586 - val_loss: 0.0675 - val_mae: 0.1597 - val_rmse: 0.2417 - val_smape: 0.3912

Epoch 61: early stopping

Restoring model weights from the end of the best epoch: 46.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:24 2s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step

 76%|███████▌  | 38/50 [13:48:08<2:09:27, 647.32s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 28s - 15ms/step - ia: 0.7614 - loss: 0.2247 - mae: 0.3108 - rmse: 0.4323 - smape: 0.6419 - val_ia: 0.5975 - val_loss: 0.0734 - val_mae: 0.1684 - val_rmse: 0.2202 - val_smape: 0.4191

Epoch 2/32

1916/1916 - 16s - 8ms/step - ia: 0.8074 - loss: 0.1514 - mae: 0.2569 - rmse: 0.3588 - smape: 0.5390 - val_ia: 0.6483 - val_loss: 0.0590 - val_mae: 0.1455 - val_rmse: 0.1982 - val_smape: 0.3860

Epoch 3/32

1916/1916 - 16s - 9ms/step - ia: 0.8144 - loss: 0.1435 - mae: 0.2490 - rmse: 0.3501 - smape: 0.5275 - val_ia: 0.5713 - val_loss: 0.0726 - val_mae: 0.1831 - val_rmse: 0.2289 - val_smape: 0.4467

Epoch 4/32

1916/1916 - 17s - 9ms/step - ia: 0.8193 - loss: 0.1357 - mae: 0.2412 - rmse: 0.3398 - smape: 0.5170 - val_ia: 0.6228 - val_loss: 0.0608 - val_mae: 0.1531 - val_rmse: 0.2047 - val_smape: 0.3906

Epoch 5/32

1916/1916 - 16s - 8ms/step - ia: 0.8233 - loss: 0.1295 - mae: 0.2362 - rmse: 0.3333 - smape: 0.5089 - val_ia: 0.6029 - val_loss: 0.0768 - val_mae: 0.1681 - val_rmse: 0.2185 - val_smape: 0.4063

Epoch 6/32

1916/1916 - 16s - 9ms/step - ia: 0.8251 - loss: 0.1296 - mae: 0.2351 - rmse: 0.3316 - smape: 0.5036 - val_ia: 0.6643 - val_loss: 0.0550 - val_mae: 0.1362 - val_rmse: 0.1890 - val_smape: 0.3639

Epoch 7/32

1916/1916 - 16s - 9ms/step - ia: 0.8247 - loss: 0.1279 - mae: 0.2341 - rmse: 0.3305 - smape: 0.5043 - val_ia: 0.5909 - val_loss: 0.0748 - val_mae: 0.1749 - val_rmse: 0.2235 - val_smape: 0.4399

Epoch 8/32

1916/1916 - 16s - 8ms/step - ia: 0.8222 - loss: 0.1357 - mae: 0.2380 - rmse: 0.3366 - smape: 0.5097 - val_ia: 0.6599 - val_loss: 0.0594 - val_mae: 0.1433 - val_rmse: 0.1948 - val_smape: 0.3757

Epoch 9/32

1916/1916 - 21s - 11ms/step - ia: 0.8264 - loss: 0.1296 - mae: 0.2333 - rmse: 0.3306 - smape: 0.5006 - val_ia: 0.5927 - val_loss: 0.0705 - val_mae: 0.1742 - val_rmse: 0.2200 - val_smape: 0.4234

Epoch 10/32

1916/1916 - 16s - 9ms/step - ia: 0.8267 - loss: 0.1280 - mae: 0.2320 - rmse: 0.3286 - smape: 0.4961 - val_ia: 0.6156 - val_loss: 0.0657 - val_mae: 0.1596 - val_rmse: 0.2106 - val_smape: 0.3844

Epoch 11/32

1916/1916 - 12s - 6ms/step - ia: 0.8277 - loss: 0.1274 - mae: 0.2313 - rmse: 0.3278 - smape: 0.4970 - val_ia: 0.6488 - val_loss: 0.0573 - val_mae: 0.1435 - val_rmse: 0.1952 - val_smape: 0.3783

Epoch 12/32

1916/1916 - 10s - 5ms/step - ia: 0.8282 - loss: 0.1257 - mae: 0.2307 - rmse: 0.3264 - smape: 0.4986 - val_ia: 0.6111 - val_loss: 0.0653 - val_mae: 0.1644 - val_rmse: 0.2098 - val_smape: 0.3937

Epoch 13/32

1916/1916 - 10s - 5ms/step - ia: 0.8285 - loss: 0.1240 - mae: 0.2297 - rmse: 0.3253 - smape: 0.4946 - val_ia: 0.6536 - val_loss: 0.0596 - val_mae: 0.1426 - val_rmse: 0.1940 - val_smape: 0.3591

Epoch 14/32

1916/1916 - 13s - 7ms/step - ia: 0.8299 - loss: 0.1243 - mae: 0.2281 - rmse: 0.3229 - smape: 0.4895 - val_ia: 0.6429 - val_loss: 0.0575 - val_mae: 0.1450 - val_rmse: 0.1950 - val_smape: 0.3749

Epoch 15/32

1916/1916 - 16s - 9ms/step - ia: 0.8309 - loss: 0.1235 - mae: 0.2274 - rmse: 0.3230 - smape: 0.4890 - val_ia: 0.5901 - val_loss: 0.0649 - val_mae: 0.1717 - val_rmse: 0.2203 - val_smape: 0.4443

Epoch 16/32

1916/1916 - 16s - 8ms/step - ia: 0.8253 - loss: 0.2201 - mae: 0.2353 - rmse: 0.3375 - smape: 0.5010 - val_ia: 0.5943 - val_loss: 0.0822 - val_mae: 0.1748 - val_rmse: 0.2258 - val_smape: 0.4157

Epoch 17/32

1916/1916 - 20s - 10ms/step - ia: 0.8213 - loss: 0.1375 - mae: 0.2403 - rmse: 0.3409 - smape: 0.5090 - val_ia: 0.6126 - val_loss: 0.0851 - val_mae: 0.1717 - val_rmse: 0.2209 - val_smape: 0.3998

Epoch 18/32

1916/1916 - 17s - 9ms/step - ia: 0.8266 - loss: 0.1263 - mae: 0.2321 - rmse: 0.3277 - smape: 0.4992 - val_ia: 0.6127 - val_loss: 0.0631 - val_mae: 0.1591 - val_rmse: 0.2079 - val_smape: 0.3922

Epoch 19/32

1916/1916 - 16s - 9ms/step - ia: 0.8299 - loss: 0.1201 - mae: 0.2276 - rmse: 0.3197 - smape: 0.4911 - val_ia: 0.6296 - val_loss: 0.0708 - val_mae: 0.1582 - val_rmse: 0.2072 - val_smape: 0.3810

Epoch 20/32

1916/1916 - 15s - 8ms/step - ia: 0.8286 - loss: 0.1280 - mae: 0.2294 - rmse: 0.3247 - smape: 0.4940 - val_ia: 0.6002 - val_loss: 0.0684 - val_mae: 0.1697 - val_rmse: 0.2180 - val_smape: 0.3986

Epoch 21/32

1916/1916 - 17s - 9ms/step - ia: 0.8306 - loss: 0.1205 - mae: 0.2276 - rmse: 0.3206 - smape: 0.4887 - val_ia: 0.5652 - val_loss: 0.0706 - val_mae: 0.1876 - val_rmse: 0.2341 - val_smape: 0.4631

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:37 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 78%|███████▊  | 39/50 [13:53:56<1:42:12, 557.51s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 21s - 44ms/step - ia: 0.1695 - loss: 1.1214 - mae: 0.7596 - rmse: 1.0404 - smape: 1.7053 - val_ia: 0.2452 - val_loss: 0.9605 - val_mae: 0.7233 - val_rmse: 0.8344 - val_smape: 1.8311

Epoch 2/64

479/479 - 7s - 14ms/step - ia: 0.1688 - loss: 1.0742 - mae: 0.7526 - rmse: 1.0201 - smape: 1.7163 - val_ia: 0.2454 - val_loss: 0.9572 - val_mae: 0.7240 - val_rmse: 0.8345 - val_smape: 1.8479

Epoch 3/64

479/479 - 10s - 20ms/step - ia: 0.1619 - loss: 1.0494 - mae: 0.7480 - rmse: 1.0110 - smape: 1.7187 - val_ia: 0.2457 - val_loss: 0.9536 - val_mae: 0.7238 - val_rmse: 0.8340 - val_smape: 1.8571

Epoch 4/64

479/479 - 6s - 14ms/step - ia: 0.1628 - loss: 1.0305 - mae: 0.7433 - rmse: 1.0024 - smape: 1.7266 - val_ia: 0.2461 - val_loss: 0.9495 - val_mae: 0.7229 - val_rmse: 0.8328 - val_smape: 1.8604

Epoch 5/64

479/479 - 6s - 13ms/step - ia: 0.1622 - loss: 1.0160 - mae: 0.7391 - rmse: 0.9956 - smape: 1.7230 - val_ia: 0.2469 - val_loss: 0.9438 - val_mae: 0.7209 - val_rmse: 0.8304 - val_smape: 1.8539

Epoch 6/64

479/479 - 10s - 21ms/step - ia: 0.1654 - loss: 1.0046 - mae: 0.7360 - rmse: 0.9902 - smape: 1.7160 - val_ia: 0.2484 - val_loss: 0.9374 - val_mae: 0.7182 - val_rmse: 0.8273 - val_smape: 1.8417

Epoch 7/64

479/479 - 6s - 12ms/step - ia: 0.1703 - loss: 0.9937 - mae: 0.7308 - rmse: 0.9846 - smape: 1.7042 - val_ia: 0.2506 - val_loss: 0.9285 - val_mae: 0.7136 - val_rmse: 0.8225 - val_smape: 1.8178

Epoch 8/64

479/479 - 10s - 22ms/step - ia: 0.1766 - loss: 0.9799 - mae: 0.7260 - rmse: 0.9780 - smape: 1.6905 - val_ia: 0.2536 - val_loss: 0.9182 - val_mae: 0.7077 - val_rmse: 0.8165 - val_smape: 1.7853

Epoch 9/64

479/479 - 6s - 12ms/step - ia: 0.1880 - loss: 0.9775 - mae: 0.7200 - rmse: 0.9742 - smape: 1.6661 - val_ia: 0.2573 - val_loss: 0.9068 - val_mae: 0.7010 - val_rmse: 0.8097 - val_smape: 1.7471

Epoch 10/64

479/479 - 10s - 21ms/step - ia: 0.1997 - loss: 0.9570 - mae: 0.7129 - rmse: 0.9643 - smape: 1.6432 - val_ia: 0.2616 - val_loss: 0.8949 - val_mae: 0.6937 - val_rmse: 0.8024 - val_smape: 1.7067

Epoch 11/64

479/479 - 11s - 22ms/step - ia: 0.2124 - loss: 0.9470 - mae: 0.7067 - rmse: 0.9605 - smape: 1.6146 - val_ia: 0.2666 - val_loss: 0.8827 - val_mae: 0.6861 - val_rmse: 0.7948 - val_smape: 1.6678

Epoch 12/64

479/479 - 6s - 12ms/step - ia: 0.2265 - loss: 0.9336 - mae: 0.7005 - rmse: 0.9530 - smape: 1.5903 - val_ia: 0.2714 - val_loss: 0.8712 - val_mae: 0.6790 - val_rmse: 0.7877 - val_smape: 1.6326

Epoch 13/64

479/479 - 5s - 11ms/step - ia: 0.2406 - loss: 0.9257 - mae: 0.6941 - rmse: 0.9489 - smape: 1.5673 - val_ia: 0.2771 - val_loss: 0.8588 - val_mae: 0.6711 - val_rmse: 0.7798 - val_smape: 1.5958

Epoch 14/64

479/479 - 6s - 12ms/step - ia: 0.2505 - loss: 0.9118 - mae: 0.6877 - rmse: 0.9415 - smape: 1.5416 - val_ia: 0.2837 - val_loss: 0.8456 - val_mae: 0.6623 - val_rmse: 0.7712 - val_smape: 1.5565

Epoch 15/64

479/479 - 10s - 22ms/step - ia: 0.2693 - loss: 0.9005 - mae: 0.6806 - rmse: 0.9348 - smape: 1.5146 - val_ia: 0.2901 - val_loss: 0.8341 - val_mae: 0.6552 - val_rmse: 0.7642 - val_smape: 1.5244

Epoch 16/64

479/479 - 6s - 12ms/step - ia: 0.2797 - loss: 0.8898 - mae: 0.6743 - rmse: 0.9307 - smape: 1.4910 - val_ia: 0.2970 - val_loss: 0.8231 - val_mae: 0.6487 - val_rmse: 0.7579 - val_smape: 1.4964

Epoch 17/64

479/479 - 10s - 22ms/step - ia: 0.2940 - loss: 0.8787 - mae: 0.6694 - rmse: 0.9222 - smape: 1.4715 - val_ia: 0.3025 - val_loss: 0.8134 - val_mae: 0.6434 - val_rmse: 0.7527 - val_smape: 1.4721

Epoch 18/64

479/479 - 6s - 12ms/step - ia: 0.2992 - loss: 0.8724 - mae: 0.6665 - rmse: 0.9214 - smape: 1.4558 - val_ia: 0.3076 - val_loss: 0.8040 - val_mae: 0.6382 - val_rmse: 0.7476 - val_smape: 1.4489

Epoch 19/64

479/479 - 6s - 12ms/step - ia: 0.3151 - loss: 0.8594 - mae: 0.6595 - rmse: 0.9125 - smape: 1.4329 - val_ia: 0.3139 - val_loss: 0.7927 - val_mae: 0.6313 - val_rmse: 0.7410 - val_smape: 1.4203

Epoch 20/64

479/479 - 5s - 11ms/step - ia: 0.3235 - loss: 0.8524 - mae: 0.6562 - rmse: 0.9096 - smape: 1.4179 - val_ia: 0.3193 - val_loss: 0.7822 - val_mae: 0.6251 - val_rmse: 0.7350 - val_smape: 1.3945

Epoch 21/64

479/479 - 6s - 12ms/step - ia: 0.3331 - loss: 0.8400 - mae: 0.6511 - rmse: 0.9026 - smape: 1.3981 - val_ia: 0.3245 - val_loss: 0.7728 - val_mae: 0.6202 - val_rmse: 0.7302 - val_smape: 1.3724

Epoch 22/64

479/479 - 6s - 12ms/step - ia: 0.3412 - loss: 0.8358 - mae: 0.6502 - rmse: 0.9005 - smape: 1.3893 - val_ia: 0.3272 - val_loss: 0.7654 - val_mae: 0.6178 - val_rmse: 0.7276 - val_smape: 1.3575

Epoch 23/64

479/479 - 6s - 12ms/step - ia: 0.3517 - loss: 0.8233 - mae: 0.6444 - rmse: 0.8946 - smape: 1.3695 - val_ia: 0.3325 - val_loss: 0.7539 - val_mae: 0.6110 - val_rmse: 0.7210 - val_smape: 1.3308

Epoch 24/64

479/479 - 6s - 12ms/step - ia: 0.3609 - loss: 0.8135 - mae: 0.6395 - rmse: 0.8892 - smape: 1.3521 - val_ia: 0.3377 - val_loss: 0.7430 - val_mae: 0.6049 - val_rmse: 0.7152 - val_smape: 1.3066

Epoch 25/64

479/479 - 6s - 13ms/step - ia: 0.3753 - loss: 0.7994 - mae: 0.6332 - rmse: 0.8809 - smape: 1.3261 - val_ia: 0.3416 - val_loss: 0.7328 - val_mae: 0.6003 - val_rmse: 0.7105 - val_smape: 1.2871

Epoch 26/64

479/479 - 10s - 21ms/step - ia: 0.3833 - loss: 0.7918 - mae: 0.6300 - rmse: 0.8761 - smape: 1.3143 - val_ia: 0.3465 - val_loss: 0.7203 - val_mae: 0.5934 - val_rmse: 0.7036 - val_smape: 1.2620

Epoch 27/64

479/479 - 9s - 18ms/step - ia: 0.3940 - loss: 0.7797 - mae: 0.6255 - rmse: 0.8691 - smape: 1.2973 - val_ia: 0.3511 - val_loss: 0.7078 - val_mae: 0.5869 - val_rmse: 0.6969 - val_smape: 1.2390

Epoch 28/64

479/479 - 4s - 7ms/step - ia: 0.4061 - loss: 0.7690 - mae: 0.6189 - rmse: 0.8642 - smape: 1.2777 - val_ia: 0.3559 - val_loss: 0.6942 - val_mae: 0.5795 - val_rmse: 0.6894 - val_smape: 1.2142

Epoch 29/64

479/479 - 4s - 8ms/step - ia: 0.4182 - loss: 0.7567 - mae: 0.6141 - rmse: 0.8555 - smape: 1.2614 - val_ia: 0.3601 - val_loss: 0.6815 - val_mae: 0.5733 - val_rmse: 0.6829 - val_smape: 1.1927

Epoch 30/64

479/479 - 5s - 10ms/step - ia: 0.4278 - loss: 0.7453 - mae: 0.6094 - rmse: 0.8503 - smape: 1.2469 - val_ia: 0.3642 - val_loss: 0.6685 - val_mae: 0.5668 - val_rmse: 0.6761 - val_smape: 1.1716

Epoch 31/64

479/479 - 4s - 8ms/step - ia: 0.4345 - loss: 0.7399 - mae: 0.6068 - rmse: 0.8467 - smape: 1.2331 - val_ia: 0.3673 - val_loss: 0.6564 - val_mae: 0.5618 - val_rmse: 0.6705 - val_smape: 1.1552

Epoch 32/64

479/479 - 4s - 8ms/step - ia: 0.4438 - loss: 0.7229 - mae: 0.6010 - rmse: 0.8366 - smape: 1.2219 - val_ia: 0.3714 - val_loss: 0.6425 - val_mae: 0.5548 - val_rmse: 0.6630 - val_smape: 1.1340

Epoch 33/64

479/479 - 4s - 8ms/step - ia: 0.4548 - loss: 0.7097 - mae: 0.5946 - rmse: 0.8283 - smape: 1.2022 - val_ia: 0.3767 - val_loss: 0.6287 - val_mae: 0.5477 - val_rmse: 0.6559 - val_smape: 1.1139

Epoch 34/64

479/479 - 4s - 7ms/step - ia: 0.4609 - loss: 0.7055 - mae: 0.5932 - rmse: 0.8262 - smape: 1.1945 - val_ia: 0.3803 - val_loss: 0.6159 - val_mae: 0.5421 - val_rmse: 0.6497 - val_smape: 1.0983

Epoch 35/64

479/479 - 4s - 8ms/step - ia: 0.4703 - loss: 0.6935 - mae: 0.5874 - rmse: 0.8215 - smape: 1.1796 - val_ia: 0.3837 - val_loss: 0.6024 - val_mae: 0.5358 - val_rmse: 0.6429 - val_smape: 1.0818

Epoch 36/64

479/479 - 6s - 12ms/step - ia: 0.4758 - loss: 0.6864 - mae: 0.5856 - rmse: 0.8158 - smape: 1.1727 - val_ia: 0.3879 - val_loss: 0.5894 - val_mae: 0.5293 - val_rmse: 0.6361 - val_smape: 1.0658

Epoch 37/64

479/479 - 6s - 13ms/step - ia: 0.4851 - loss: 0.6736 - mae: 0.5801 - rmse: 0.8082 - smape: 1.1591 - val_ia: 0.3913 - val_loss: 0.5766 - val_mae: 0.5239 - val_rmse: 0.6302 - val_smape: 1.0531

Epoch 38/64

479/479 - 6s - 14ms/step - ia: 0.4922 - loss: 0.6661 - mae: 0.5769 - rmse: 0.8038 - smape: 1.1499 - val_ia: 0.3925 - val_loss: 0.5669 - val_mae: 0.5214 - val_rmse: 0.6268 - val_smape: 1.0476

Epoch 39/64

479/479 - 10s - 21ms/step - ia: 0.4998 - loss: 0.6553 - mae: 0.5712 - rmse: 0.7969 - smape: 1.1366 - val_ia: 0.3964 - val_loss: 0.5549 - val_mae: 0.5157 - val_rmse: 0.6209 - val_smape: 1.0350

Epoch 40/64

479/479 - 6s - 14ms/step - ia: 0.5043 - loss: 0.6464 - mae: 0.5679 - rmse: 0.7918 - smape: 1.1302 - val_ia: 0.4001 - val_loss: 0.5424 - val_mae: 0.5097 - val_rmse: 0.6147 - val_smape: 1.0221

Epoch 41/64

479/479 - 6s - 13ms/step - ia: 0.5116 - loss: 0.6390 - mae: 0.5633 - rmse: 0.7873 - smape: 1.1205 - val_ia: 0.4022 - val_loss: 0.5315 - val_mae: 0.5058 - val_rmse: 0.6103 - val_smape: 1.0145

Epoch 42/64

479/479 - 6s - 13ms/step - ia: 0.5172 - loss: 0.6313 - mae: 0.5602 - rmse: 0.7820 - smape: 1.1138 - val_ia: 0.4046 - val_loss: 0.5213 - val_mae: 0.5010 - val_rmse: 0.6050 - val_smape: 1.0042

Epoch 43/64

479/479 - 6s - 12ms/step - ia: 0.5195 - loss: 0.6248 - mae: 0.5582 - rmse: 0.7779 - smape: 1.1105 - val_ia: 0.4086 - val_loss: 0.5106 - val_mae: 0.4959 - val_rmse: 0.6000 - val_smape: 0.9945

Epoch 44/64

479/479 - 6s - 12ms/step - ia: 0.5282 - loss: 0.6074 - mae: 0.5524 - rmse: 0.7679 - smape: 1.1000 - val_ia: 0.4105 - val_loss: 0.4995 - val_mae: 0.4924 - val_rmse: 0.5959 - val_smape: 0.9889

Epoch 45/64

479/479 - 6s - 13ms/step - ia: 0.5328 - loss: 0.6084 - mae: 0.5484 - rmse: 0.7669 - smape: 1.0917 - val_ia: 0.4131 - val_loss: 0.4896 - val_mae: 0.4881 - val_rmse: 0.5914 - val_smape: 0.9811

Epoch 46/64

479/479 - 10s - 21ms/step - ia: 0.5339 - loss: 0.6035 - mae: 0.5487 - rmse: 0.7653 - smape: 1.0912 - val_ia: 0.4163 - val_loss: 0.4797 - val_mae: 0.4834 - val_rmse: 0.5866 - val_smape: 0.9720

Epoch 47/64

479/479 - 10s - 22ms/step - ia: 0.5409 - loss: 0.5934 - mae: 0.5422 - rmse: 0.7578 - smape: 1.0791 - val_ia: 0.4190 - val_loss: 0.4705 - val_mae: 0.4799 - val_rmse: 0.5829 - val_smape: 0.9665

Epoch 48/64

479/479 - 6s - 12ms/step - ia: 0.5460 - loss: 0.5911 - mae: 0.5405 - rmse: 0.7561 - smape: 1.0703 - val_ia: 0.4204 - val_loss: 0.4636 - val_mae: 0.4773 - val_rmse: 0.5800 - val_smape: 0.9632

Epoch 49/64

479/479 - 6s - 13ms/step - ia: 0.5487 - loss: 0.5787 - mae: 0.5374 - rmse: 0.7486 - smape: 1.0716 - val_ia: 0.4226 - val_loss: 0.4554 - val_mae: 0.4738 - val_rmse: 0.5763 - val_smape: 0.9575

Epoch 50/64

479/479 - 6s - 12ms/step - ia: 0.5484 - loss: 0.5778 - mae: 0.5373 - rmse: 0.7484 - smape: 1.0702 - val_ia: 0.4245 - val_loss: 0.4477 - val_mae: 0.4711 - val_rmse: 0.5733 - val_smape: 0.9539

Epoch 51/64

479/479 - 11s - 22ms/step - ia: 0.5550 - loss: 0.5751 - mae: 0.5324 - rmse: 0.7458 - smape: 1.0611 - val_ia: 0.4271 - val_loss: 0.4401 - val_mae: 0.4676 - val_rmse: 0.5697 - val_smape: 0.9479

Epoch 52/64

479/479 - 6s - 13ms/step - ia: 0.5542 - loss: 0.5707 - mae: 0.5334 - rmse: 0.7442 - smape: 1.0612 - val_ia: 0.4290 - val_loss: 0.4339 - val_mae: 0.4651 - val_rmse: 0.5670 - val_smape: 0.9445

Epoch 53/64

479/479 - 6s - 12ms/step - ia: 0.5594 - loss: 0.5655 - mae: 0.5283 - rmse: 0.7400 - smape: 1.0519 - val_ia: 0.4321 - val_loss: 0.4267 - val_mae: 0.4608 - val_rmse: 0.5629 - val_smape: 0.9370

Epoch 54/64

479/479 - 6s - 12ms/step - ia: 0.5623 - loss: 0.5608 - mae: 0.5271 - rmse: 0.7361 - smape: 1.0512 - val_ia: 0.4334 - val_loss: 0.4205 - val_mae: 0.4587 - val_rmse: 0.5604 - val_smape: 0.9350

Epoch 55/64

479/479 - 6s - 12ms/step - ia: 0.5682 - loss: 0.5509 - mae: 0.5223 - rmse: 0.7297 - smape: 1.0412 - val_ia: 0.4346 - val_loss: 0.4154 - val_mae: 0.4573 - val_rmse: 0.5586 - val_smape: 0.9343

Epoch 56/64

479/479 - 6s - 12ms/step - ia: 0.5672 - loss: 0.5549 - mae: 0.5224 - rmse: 0.7325 - smape: 1.0404 - val_ia: 0.4373 - val_loss: 0.4092 - val_mae: 0.4539 - val_rmse: 0.5552 - val_smape: 0.9289

Epoch 57/64

479/479 - 6s - 12ms/step - ia: 0.5685 - loss: 0.5467 - mae: 0.5212 - rmse: 0.7275 - smape: 1.0427 - val_ia: 0.4394 - val_loss: 0.4051 - val_mae: 0.4515 - val_rmse: 0.5527 - val_smape: 0.9245

Epoch 58/64

479/479 - 5s - 11ms/step - ia: 0.5711 - loss: 0.5482 - mae: 0.5187 - rmse: 0.7292 - smape: 1.0350 - val_ia: 0.4406 - val_loss: 0.4009 - val_mae: 0.4500 - val_rmse: 0.5509 - val_smape: 0.9231

Epoch 59/64

479/479 - 6s - 13ms/step - ia: 0.5747 - loss: 0.5344 - mae: 0.5154 - rmse: 0.7194 - smape: 1.0335 - val_ia: 0.4440 - val_loss: 0.3942 - val_mae: 0.4461 - val_rmse: 0.5473 - val_smape: 0.9164

Epoch 60/64

479/479 - 10s - 21ms/step - ia: 0.5781 - loss: 0.5297 - mae: 0.5131 - rmse: 0.7154 - smape: 1.0279 - val_ia: 0.4464 - val_loss: 0.3880 - val_mae: 0.4432 - val_rmse: 0.5442 - val_smape: 0.9118

Epoch 61/64

479/479 - 11s - 22ms/step - ia: 0.5788 - loss: 0.5281 - mae: 0.5116 - rmse: 0.7142 - smape: 1.0253 - val_ia: 0.4498 - val_loss: 0.3823 - val_mae: 0.4396 - val_rmse: 0.5407 - val_smape: 0.9059

Epoch 62/64

479/479 - 6s - 12ms/step - ia: 0.5789 - loss: 0.5337 - mae: 0.5129 - rmse: 0.7193 - smape: 1.0256 - val_ia: 0.4515 - val_loss: 0.3784 - val_mae: 0.4379 - val_rmse: 0.5388 - val_smape: 0.9040

Epoch 63/64

479/479 - 6s - 13ms/step - ia: 0.5793 - loss: 0.5361 - mae: 0.5125 - rmse: 0.7194 - smape: 1.0241 - val_ia: 0.4531 - val_loss: 0.3749 - val_mae: 0.4361 - val_rmse: 0.5367 - val_smape: 0.9017

Epoch 64/64

479/479 - 10s - 20ms/step - ia: 0.5803 - loss: 0.5318 - mae: 0.5109 - rmse: 0.7164 - smape: 1.0226 - val_ia: 0.4560 - val_loss: 0.3708 - val_mae: 0.4331 - val_rmse: 0.5338 - val_smape: 0.8967

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:31 2s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 80%|████████  | 40/50 [14:01:27<1:27:35, 525.58s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 43s - 22ms/step - ia: 0.7261 - loss: 0.6670 - mae: 0.3557 - rmse: 0.5120 - smape: 0.6960 - val_ia: 0.2955 - val_loss: 0.4259 - val_mae: 0.5005 - val_rmse: 0.5562 - val_smape: 1.1209

Epoch 2/32

1916/1916 - 27s - 14ms/step - ia: 0.1365 - loss: 2869181.5000 - mae: 290.9170 - rmse: 575.6465 - smape: 1.6831 - val_ia: 0.0127 - val_loss: 7039.6572 - val_mae: 56.2166 - val_rmse: 68.9472 - val_smape: 1.8643

Epoch 3/32

1916/1916 - 28s - 15ms/step - ia: 0.0104 - loss: 105838.0391 - mae: 111.1709 - rmse: 220.7175 - smape: 1.8419 - val_ia: 0.0326 - val_loss: 377.8882 - val_mae: 10.4213 - val_rmse: 14.6219 - val_smape: 1.7769

Epoch 4/32

1916/1916 - 27s - 14ms/step - ia: 0.0070 - loss: 5961730.0000 - mae: 581.4811 - rmse: 1093.7676 - smape: 1.8761 - val_ia: 3.0431e-04 - val_loss: 3540525.7500 - val_mae: 1237.7570 - val_rmse: 1611.2533 - val_smape: 1.9853

Epoch 5/32

1916/1916 - 27s - 14ms/step - ia: 0.0016 - loss: 23447320.0000 - mae: 1334.1240 - rmse: 2753.8447 - smape: 1.8925 - val_ia: 0.0057 - val_loss: 41766.8398 - val_mae: 80.7835 - val_rmse: 145.0886 - val_smape: 1.7989

Epoch 6/32

1916/1916 - 26s - 14ms/step - ia: 0.0083 - loss: 272969.3125 - mae: 153.0646 - rmse: 344.8568 - smape: 1.7919 - val_ia: 0.0108 - val_loss: 7549.6084 - val_mae: 47.4430 - val_rmse: 69.4367 - val_smape: 1.8240

Epoch 7/32

1916/1916 - 27s - 14ms/step - ia: 0.0071 - loss: 6069728.5000 - mae: 508.5894 - rmse: 1010.2431 - smape: 1.8391 - val_ia: 0.0597 - val_loss: 78.8377 - val_mae: 5.2099 - val_rmse: 7.0346 - val_smape: 1.6063

Epoch 8/32

1916/1916 - 27s - 14ms/step - ia: 0.0355 - loss: 194832.8125 - mae: 83.8357 - rmse: 177.7161 - smape: 1.6920 - val_ia: 0.1070 - val_loss: 16.4029 - val_mae: 2.4111 - val_rmse: 3.2776 - val_smape: 1.5300

Epoch 9/32

1916/1916 - 29s - 15ms/step - ia: 0.0373 - loss: 19200.5664 - mae: 32.5232 - rmse: 74.4113 - smape: 1.6662 - val_ia: 0.0752 - val_loss: 266.4735 - val_mae: 4.2064 - val_rmse: 6.6748 - val_smape: 1.5529

Epoch 10/32

1916/1916 - 27s - 14ms/step - ia: 0.0168 - loss: 723796.0625 - mae: 204.7910 - rmse: 407.8228 - smape: 1.8173 - val_ia: 0.1015 - val_loss: 337.9086 - val_mae: 4.0739 - val_rmse: 8.8107 - val_smape: 1.5386

Epoch 11/32

1916/1916 - 28s - 14ms/step - ia: 0.0148 - loss: 680420.1250 - mae: 130.2079 - rmse: 309.4342 - smape: 1.7057 - val_ia: 0.0724 - val_loss: 1520.0746 - val_mae: 7.7588 - val_rmse: 17.3028 - val_smape: 1.4106

Epoch 12/32

1916/1916 - 28s - 14ms/step - ia: 0.0167 - loss: 226684.3281 - mae: 111.1644 - rmse: 256.9823 - smape: 1.6916 - val_ia: 0.0481 - val_loss: 1432.9617 - val_mae: 8.7164 - val_rmse: 17.5004 - val_smape: 1.5781

Epoch 13/32

1916/1916 - 27s - 14ms/step - ia: 0.0174 - loss: 568783.9375 - mae: 132.2943 - rmse: 312.5247 - smape: 1.7015 - val_ia: 0.0370 - val_loss: 1341.6765 - val_mae: 13.7718 - val_rmse: 23.6199 - val_smape: 1.6154

Epoch 14/32

1916/1916 - 27s - 14ms/step - ia: 0.0131 - loss: 1155057.3750 - mae: 181.6803 - rmse: 441.7382 - smape: 1.6761 - val_ia: 0.0028 - val_loss: 807021.7500 - val_mae: 277.3887 - val_rmse: 549.1322 - val_smape: 1.8881

Epoch 15/32

1916/1916 - 41s - 21ms/step - ia: 0.0123 - loss: 1939629.1250 - mae: 239.7754 - rmse: 591.3502 - smape: 1.7302 - val_ia: 0.0292 - val_loss: 22268.6758 - val_mae: 23.3263 - val_rmse: 57.7865 - val_smape: 1.5559

Epoch 16/32

1916/1916 - 27s - 14ms/step - ia: 0.0266 - loss: 71117.1172 - mae: 57.8662 - rmse: 147.7203 - smape: 1.6626 - val_ia: 0.0489 - val_loss: 17276.6621 - val_mae: 10.7403 - val_rmse: 24.4029 - val_smape: 1.5975

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 45:54 20s/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 25s 38ms/step

 82%|████████▏ | 41/50 [14:09:42<1:17:27, 516.43s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

120/120 - 21s - 172ms/step - ia: 0.4710 - loss: 0.6206 - mae: 0.5529 - rmse: 0.7758 - smape: 1.1588 - val_ia: 0.5931 - val_loss: 0.3920 - val_mae: 0.4296 - val_rmse: 0.5822 - val_smape: 0.8787

Epoch 2/64

120/120 - 10s - 81ms/step - ia: 0.6678 - loss: 0.4121 - mae: 0.4320 - rmse: 0.6383 - smape: 0.8553 - val_ia: 0.6336 - val_loss: 0.3171 - val_mae: 0.3866 - val_rmse: 0.5270 - val_smape: 0.8189

Epoch 3/64

120/120 - 8s - 63ms/step - ia: 0.7034 - loss: 0.3422 - mae: 0.3923 - rmse: 0.5819 - smape: 0.7950 - val_ia: 0.6706 - val_loss: 0.2530 - val_mae: 0.3468 - val_rmse: 0.4749 - val_smape: 0.7586

Epoch 4/64

120/120 - 10s - 87ms/step - ia: 0.7356 - loss: 0.2895 - mae: 0.3575 - rmse: 0.5348 - smape: 0.7371 - val_ia: 0.6985 - val_loss: 0.2160 - val_mae: 0.3162 - val_rmse: 0.4378 - val_smape: 0.6978

Epoch 5/64

120/120 - 8s - 64ms/step - ia: 0.7538 - loss: 0.2586 - mae: 0.3362 - rmse: 0.5056 - smape: 0.7026 - val_ia: 0.7205 - val_loss: 0.1983 - val_mae: 0.3003 - val_rmse: 0.4206 - val_smape: 0.6707

Epoch 6/64

120/120 - 8s - 64ms/step - ia: 0.7668 - loss: 0.2380 - mae: 0.3216 - rmse: 0.4853 - smape: 0.6789 - val_ia: 0.7308 - val_loss: 0.1790 - val_mae: 0.2862 - val_rmse: 0.3997 - val_smape: 0.6501

Epoch 7/64

120/120 - 7s - 62ms/step - ia: 0.7784 - loss: 0.2174 - mae: 0.3066 - rmse: 0.4638 - smape: 0.6570 - val_ia: 0.7434 - val_loss: 0.1648 - val_mae: 0.2740 - val_rmse: 0.3847 - val_smape: 0.6305

Epoch 8/64

120/120 - 10s - 85ms/step - ia: 0.7884 - loss: 0.1989 - mae: 0.2949 - rmse: 0.4428 - smape: 0.6400 - val_ia: 0.7546 - val_loss: 0.1467 - val_mae: 0.2593 - val_rmse: 0.3639 - val_smape: 0.6095

Epoch 9/64

120/120 - 7s - 57ms/step - ia: 0.7962 - loss: 0.1854 - mae: 0.2855 - rmse: 0.4277 - smape: 0.6232 - val_ia: 0.7760 - val_loss: 0.1367 - val_mae: 0.2424 - val_rmse: 0.3505 - val_smape: 0.5775

Epoch 10/64

120/120 - 11s - 92ms/step - ia: 0.8025 - loss: 0.1751 - mae: 0.2771 - rmse: 0.4159 - smape: 0.6094 - val_ia: 0.7862 - val_loss: 0.1221 - val_mae: 0.2291 - val_rmse: 0.3319 - val_smape: 0.5606

Epoch 11/64

120/120 - 8s - 64ms/step - ia: 0.8101 - loss: 0.1636 - mae: 0.2676 - rmse: 0.4018 - smape: 0.5920 - val_ia: 0.7905 - val_loss: 0.1138 - val_mae: 0.2224 - val_rmse: 0.3212 - val_smape: 0.5515

Epoch 12/64

120/120 - 7s - 62ms/step - ia: 0.8153 - loss: 0.1549 - mae: 0.2607 - rmse: 0.3908 - smape: 0.5809 - val_ia: 0.7991 - val_loss: 0.1072 - val_mae: 0.2145 - val_rmse: 0.3119 - val_smape: 0.5355

Epoch 13/64

120/120 - 8s - 64ms/step - ia: 0.8205 - loss: 0.1479 - mae: 0.2538 - rmse: 0.3818 - smape: 0.5694 - val_ia: 0.8107 - val_loss: 0.1003 - val_mae: 0.2038 - val_rmse: 0.3015 - val_smape: 0.5164

Epoch 14/64

120/120 - 7s - 62ms/step - ia: 0.8241 - loss: 0.1436 - mae: 0.2497 - rmse: 0.3762 - smape: 0.5558 - val_ia: 0.8172 - val_loss: 0.0965 - val_mae: 0.1982 - val_rmse: 0.2959 - val_smape: 0.5045

Epoch 15/64

120/120 - 10s - 84ms/step - ia: 0.8290 - loss: 0.1348 - mae: 0.2436 - rmse: 0.3649 - smape: 0.5501 - val_ia: 0.8180 - val_loss: 0.0908 - val_mae: 0.1938 - val_rmse: 0.2875 - val_smape: 0.4970

Epoch 16/64

120/120 - 7s - 60ms/step - ia: 0.8315 - loss: 0.1328 - mae: 0.2402 - rmse: 0.3620 - smape: 0.5433 - val_ia: 0.8235 - val_loss: 0.0864 - val_mae: 0.1884 - val_rmse: 0.2806 - val_smape: 0.4873

Epoch 17/64

120/120 - 5s - 41ms/step - ia: 0.8351 - loss: 0.1302 - mae: 0.2357 - rmse: 0.3573 - smape: 0.5332 - val_ia: 0.8273 - val_loss: 0.0827 - val_mae: 0.1846 - val_rmse: 0.2749 - val_smape: 0.4803

Epoch 18/64

120/120 - 5s - 39ms/step - ia: 0.8379 - loss: 0.1237 - mae: 0.2321 - rmse: 0.3476 - smape: 0.5271 - val_ia: 0.8360 - val_loss: 0.0800 - val_mae: 0.1775 - val_rmse: 0.2699 - val_smape: 0.4657

Epoch 19/64

120/120 - 5s - 43ms/step - ia: 0.8411 - loss: 0.1202 - mae: 0.2280 - rmse: 0.3434 - smape: 0.5187 - val_ia: 0.8340 - val_loss: 0.0765 - val_mae: 0.1764 - val_rmse: 0.2643 - val_smape: 0.4624

Epoch 20/64

120/120 - 5s - 39ms/step - ia: 0.8434 - loss: 0.1155 - mae: 0.2245 - rmse: 0.3373 - smape: 0.5116 - val_ia: 0.8433 - val_loss: 0.0752 - val_mae: 0.1704 - val_rmse: 0.2614 - val_smape: 0.4499

Epoch 21/64

120/120 - 7s - 58ms/step - ia: 0.8447 - loss: 0.1159 - mae: 0.2233 - rmse: 0.3372 - smape: 0.5101 - val_ia: 0.8445 - val_loss: 0.0719 - val_mae: 0.1677 - val_rmse: 0.2558 - val_smape: 0.4451

Epoch 22/64

120/120 - 7s - 61ms/step - ia: 0.8472 - loss: 0.1121 - mae: 0.2196 - rmse: 0.3317 - smape: 0.5042 - val_ia: 0.8465 - val_loss: 0.0698 - val_mae: 0.1650 - val_rmse: 0.2521 - val_smape: 0.4388

Epoch 23/64

120/120 - 8s - 64ms/step - ia: 0.8499 - loss: 0.1101 - mae: 0.2157 - rmse: 0.3284 - smape: 0.4958 - val_ia: 0.8481 - val_loss: 0.0691 - val_mae: 0.1634 - val_rmse: 0.2512 - val_smape: 0.4349

Epoch 24/64

120/120 - 10s - 84ms/step - ia: 0.8515 - loss: 0.1074 - mae: 0.2139 - rmse: 0.3243 - smape: 0.4906 - val_ia: 0.8514 - val_loss: 0.0668 - val_mae: 0.1598 - val_rmse: 0.2467 - val_smape: 0.4263

Epoch 25/64

120/120 - 9s - 72ms/step - ia: 0.8534 - loss: 0.1049 - mae: 0.2116 - rmse: 0.3206 - smape: 0.4884 - val_ia: 0.8507 - val_loss: 0.0654 - val_mae: 0.1597 - val_rmse: 0.2440 - val_smape: 0.4237

Epoch 26/64

120/120 - 8s - 65ms/step - ia: 0.8549 - loss: 0.1033 - mae: 0.2095 - rmse: 0.3181 - smape: 0.4832 - val_ia: 0.8594 - val_loss: 0.0647 - val_mae: 0.1541 - val_rmse: 0.2420 - val_smape: 0.4120

Epoch 27/64

120/120 - 8s - 64ms/step - ia: 0.8574 - loss: 0.0998 - mae: 0.2063 - rmse: 0.3133 - smape: 0.4751 - val_ia: 0.8582 - val_loss: 0.0635 - val_mae: 0.1538 - val_rmse: 0.2403 - val_smape: 0.4110

Epoch 28/64

120/120 - 7s - 61ms/step - ia: 0.8589 - loss: 0.0990 - mae: 0.2041 - rmse: 0.3112 - smape: 0.4713 - val_ia: 0.8530 - val_loss: 0.0630 - val_mae: 0.1583 - val_rmse: 0.2389 - val_smape: 0.4123

Epoch 29/64

120/120 - 7s - 61ms/step - ia: 0.8597 - loss: 0.0971 - mae: 0.2033 - rmse: 0.3089 - smape: 0.4692 - val_ia: 0.8645 - val_loss: 0.0606 - val_mae: 0.1477 - val_rmse: 0.2339 - val_smape: 0.3967

Epoch 30/64

120/120 - 8s - 65ms/step - ia: 0.8604 - loss: 0.0980 - mae: 0.2021 - rmse: 0.3097 - smape: 0.4663 - val_ia: 0.8631 - val_loss: 0.0596 - val_mae: 0.1485 - val_rmse: 0.2321 - val_smape: 0.3970

Epoch 31/64

120/120 - 10s - 84ms/step - ia: 0.8628 - loss: 0.0937 - mae: 0.1987 - rmse: 0.3033 - smape: 0.4620 - val_ia: 0.8649 - val_loss: 0.0592 - val_mae: 0.1472 - val_rmse: 0.2314 - val_smape: 0.3932

Epoch 32/64

120/120 - 8s - 64ms/step - ia: 0.8638 - loss: 0.0927 - mae: 0.1977 - rmse: 0.3016 - smape: 0.4591 - val_ia: 0.8677 - val_loss: 0.0589 - val_mae: 0.1451 - val_rmse: 0.2303 - val_smape: 0.3883

Epoch 33/64

120/120 - 7s - 61ms/step - ia: 0.8644 - loss: 0.0935 - mae: 0.1965 - rmse: 0.3029 - smape: 0.4564 - val_ia: 0.8703 - val_loss: 0.0578 - val_mae: 0.1428 - val_rmse: 0.2280 - val_smape: 0.3847

Epoch 34/64

120/120 - 10s - 87ms/step - ia: 0.8646 - loss: 0.0927 - mae: 0.1967 - rmse: 0.3010 - smape: 0.4562 - val_ia: 0.8713 - val_loss: 0.0578 - val_mae: 0.1423 - val_rmse: 0.2279 - val_smape: 0.3819

Epoch 35/64

120/120 - 10s - 85ms/step - ia: 0.8667 - loss: 0.0909 - mae: 0.1933 - rmse: 0.2982 - smape: 0.4499 - val_ia: 0.8696 - val_loss: 0.0572 - val_mae: 0.1426 - val_rmse: 0.2271 - val_smape: 0.3830

Epoch 36/64

120/120 - 11s - 89ms/step - ia: 0.8662 - loss: 0.0917 - mae: 0.1946 - rmse: 0.3002 - smape: 0.4488 - val_ia: 0.8725 - val_loss: 0.0563 - val_mae: 0.1403 - val_rmse: 0.2246 - val_smape: 0.3773

Epoch 37/64

120/120 - 8s - 63ms/step - ia: 0.8670 - loss: 0.0920 - mae: 0.1935 - rmse: 0.2998 - smape: 0.4461 - val_ia: 0.8717 - val_loss: 0.0562 - val_mae: 0.1409 - val_rmse: 0.2244 - val_smape: 0.3788

Epoch 38/64

120/120 - 7s - 62ms/step - ia: 0.8674 - loss: 0.0904 - mae: 0.1924 - rmse: 0.2975 - smape: 0.4457 - val_ia: 0.8723 - val_loss: 0.0558 - val_mae: 0.1404 - val_rmse: 0.2235 - val_smape: 0.3778

Epoch 39/64

120/120 - 7s - 62ms/step - ia: 0.8699 - loss: 0.0894 - mae: 0.1891 - rmse: 0.2956 - smape: 0.4398 - val_ia: 0.8726 - val_loss: 0.0559 - val_mae: 0.1404 - val_rmse: 0.2236 - val_smape: 0.3767

Epoch 40/64

120/120 - 10s - 87ms/step - ia: 0.8703 - loss: 0.0882 - mae: 0.1887 - rmse: 0.2933 - smape: 0.4386 - val_ia: 0.8758 - val_loss: 0.0553 - val_mae: 0.1370 - val_rmse: 0.2220 - val_smape: 0.3699

Epoch 41/64

120/120 - 8s - 65ms/step - ia: 0.8702 - loss: 0.0885 - mae: 0.1887 - rmse: 0.2940 - smape: 0.4368 - val_ia: 0.8737 - val_loss: 0.0549 - val_mae: 0.1389 - val_rmse: 0.2214 - val_smape: 0.3732

Epoch 42/64

120/120 - 7s - 62ms/step - ia: 0.8706 - loss: 0.0868 - mae: 0.1879 - rmse: 0.2915 - smape: 0.4380 - val_ia: 0.8761 - val_loss: 0.0547 - val_mae: 0.1370 - val_rmse: 0.2208 - val_smape: 0.3695

Epoch 43/64

120/120 - 7s - 56ms/step - ia: 0.8716 - loss: 0.0863 - mae: 0.1867 - rmse: 0.2909 - smape: 0.4342 - val_ia: 0.8778 - val_loss: 0.0560 - val_mae: 0.1374 - val_rmse: 0.2237 - val_smape: 0.3695

Epoch 44/64

120/120 - 7s - 62ms/step - ia: 0.8734 - loss: 0.0852 - mae: 0.1845 - rmse: 0.2887 - smape: 0.4276 - val_ia: 0.8804 - val_loss: 0.0544 - val_mae: 0.1337 - val_rmse: 0.2196 - val_smape: 0.3626

Epoch 45/64

120/120 - 8s - 63ms/step - ia: 0.8739 - loss: 0.0843 - mae: 0.1838 - rmse: 0.2868 - smape: 0.4262 - val_ia: 0.8780 - val_loss: 0.0539 - val_mae: 0.1350 - val_rmse: 0.2188 - val_smape: 0.3635

Epoch 46/64

120/120 - 10s - 86ms/step - ia: 0.8735 - loss: 0.0846 - mae: 0.1843 - rmse: 0.2878 - smape: 0.4284 - val_ia: 0.8795 - val_loss: 0.0554 - val_mae: 0.1355 - val_rmse: 0.2218 - val_smape: 0.3640

Epoch 47/64

120/120 - 8s - 67ms/step - ia: 0.8737 - loss: 0.0858 - mae: 0.1839 - rmse: 0.2896 - smape: 0.4255 - val_ia: 0.8791 - val_loss: 0.0540 - val_mae: 0.1343 - val_rmse: 0.2191 - val_smape: 0.3625

Epoch 48/64

120/120 - 8s - 65ms/step - ia: 0.8747 - loss: 0.0835 - mae: 0.1824 - rmse: 0.2854 - smape: 0.4256 - val_ia: 0.8812 - val_loss: 0.0537 - val_mae: 0.1326 - val_rmse: 0.2181 - val_smape: 0.3586

Epoch 49/64

120/120 - 7s - 62ms/step - ia: 0.8738 - loss: 0.0863 - mae: 0.1838 - rmse: 0.2908 - smape: 0.4258 - val_ia: 0.8775 - val_loss: 0.0536 - val_mae: 0.1351 - val_rmse: 0.2183 - val_smape: 0.3637

Epoch 50/64

120/120 - 8s - 64ms/step - ia: 0.8763 - loss: 0.0825 - mae: 0.1805 - rmse: 0.2835 - smape: 0.4216 - val_ia: 0.8796 - val_loss: 0.0535 - val_mae: 0.1332 - val_rmse: 0.2178 - val_smape: 0.3601

Epoch 51/64

120/120 - 7s - 58ms/step - ia: 0.8755 - loss: 0.0836 - mae: 0.1812 - rmse: 0.2857 - smape: 0.4215 - val_ia: 0.8806 - val_loss: 0.0532 - val_mae: 0.1327 - val_rmse: 0.2169 - val_smape: 0.3589

Epoch 52/64

120/120 - 7s - 61ms/step - ia: 0.8758 - loss: 0.0833 - mae: 0.1809 - rmse: 0.2854 - smape: 0.4217 - val_ia: 0.8820 - val_loss: 0.0547 - val_mae: 0.1331 - val_rmse: 0.2200 - val_smape: 0.3582

Epoch 53/64

120/120 - 8s - 67ms/step - ia: 0.8759 - loss: 0.0842 - mae: 0.1807 - rmse: 0.2862 - smape: 0.4191 - val_ia: 0.8812 - val_loss: 0.0532 - val_mae: 0.1321 - val_rmse: 0.2171 - val_smape: 0.3576

Epoch 54/64

120/120 - 8s - 68ms/step - ia: 0.8764 - loss: 0.0830 - mae: 0.1804 - rmse: 0.2847 - smape: 0.4179 - val_ia: 0.8812 - val_loss: 0.0530 - val_mae: 0.1319 - val_rmse: 0.2164 - val_smape: 0.3569

Epoch 55/64

120/120 - 8s - 69ms/step - ia: 0.8772 - loss: 0.0816 - mae: 0.1791 - rmse: 0.2827 - smape: 0.4166 - val_ia: 0.8816 - val_loss: 0.0531 - val_mae: 0.1319 - val_rmse: 0.2169 - val_smape: 0.3568

Epoch 56/64

120/120 - 8s - 66ms/step - ia: 0.8769 - loss: 0.0825 - mae: 0.1794 - rmse: 0.2842 - smape: 0.4153 - val_ia: 0.8822 - val_loss: 0.0532 - val_mae: 0.1317 - val_rmse: 0.2168 - val_smape: 0.3571

Epoch 57/64

120/120 - 8s - 64ms/step - ia: 0.8771 - loss: 0.0821 - mae: 0.1793 - rmse: 0.2833 - smape: 0.4197 - val_ia: 0.8798 - val_loss: 0.0534 - val_mae: 0.1333 - val_rmse: 0.2179 - val_smape: 0.3610

Epoch 58/64

120/120 - 11s - 88ms/step - ia: 0.8781 - loss: 0.0801 - mae: 0.1780 - rmse: 0.2798 - smape: 0.4170 - val_ia: 0.8813 - val_loss: 0.0533 - val_mae: 0.1320 - val_rmse: 0.2176 - val_smape: 0.3568

Epoch 59/64

120/120 - 8s - 65ms/step - ia: 0.8776 - loss: 0.0820 - mae: 0.1786 - rmse: 0.2826 - smape: 0.4142 - val_ia: 0.8828 - val_loss: 0.0527 - val_mae: 0.1306 - val_rmse: 0.2157 - val_smape: 0.3541

Epoch 60/64

120/120 - 7s - 60ms/step - ia: 0.8783 - loss: 0.0805 - mae: 0.1774 - rmse: 0.2801 - smape: 0.4148 - val_ia: 0.8851 - val_loss: 0.0530 - val_mae: 0.1296 - val_rmse: 0.2161 - val_smape: 0.3515

Epoch 61/64

120/120 - 11s - 91ms/step - ia: 0.8787 - loss: 0.0791 - mae: 0.1769 - rmse: 0.2776 - smape: 0.4119 - val_ia: 0.8821 - val_loss: 0.0527 - val_mae: 0.1314 - val_rmse: 0.2154 - val_smape: 0.3550

Epoch 62/64

120/120 - 8s - 65ms/step - ia: 0.8790 - loss: 0.0804 - mae: 0.1766 - rmse: 0.2802 - smape: 0.4119 - val_ia: 0.8791 - val_loss: 0.0528 - val_mae: 0.1339 - val_rmse: 0.2160 - val_smape: 0.3579

Epoch 63/64

120/120 - 8s - 67ms/step - ia: 0.8786 - loss: 0.0813 - mae: 0.1769 - rmse: 0.2814 - smape: 0.4134 - val_ia: 0.8847 - val_loss: 0.0525 - val_mae: 0.1296 - val_rmse: 0.2152 - val_smape: 0.3520

Epoch 64/64

120/120 - 8s - 63ms/step - ia: 0.8787 - loss: 0.0813 - mae: 0.1769 - rmse: 0.2819 - smape: 0.4114 - val_ia: 0.8848 - val_loss: 0.0539 - val_mae: 0.1304 - val_rmse: 0.2181 - val_smape: 0.3512

Restoring model weights from the end of the best epoch: 63.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 6:57 3s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step

 84%|████████▍ | 42/50 [14:18:37<1:09:37, 522.21s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

3832/3832 - 37s - 10ms/step - ia: 0.7594 - loss: 0.1954 - mae: 0.2903 - rmse: 0.3877 - smape: 0.6163 - val_ia: 0.4400 - val_loss: 0.0797 - val_mae: 0.1920 - val_rmse: 0.2288 - val_smape: 0.4542

Epoch 2/8

3832/3832 - 46s - 12ms/step - ia: 0.8151 - loss: 0.1212 - mae: 0.2282 - rmse: 0.3081 - smape: 0.5005 - val_ia: 0.4951 - val_loss: 0.0630 - val_mae: 0.1619 - val_rmse: 0.2016 - val_smape: 0.4089

Epoch 3/8

3832/3832 - 42s - 11ms/step - ia: 0.8233 - loss: 0.1141 - mae: 0.2185 - rmse: 0.2965 - smape: 0.4802 - val_ia: 0.4557 - val_loss: 0.0738 - val_mae: 0.1916 - val_rmse: 0.2276 - val_smape: 0.4552

Epoch 4/8

3832/3832 - 30s - 8ms/step - ia: 0.8285 - loss: 0.1108 - mae: 0.2125 - rmse: 0.2904 - smape: 0.4686 - val_ia: 0.4838 - val_loss: 0.0655 - val_mae: 0.1690 - val_rmse: 0.2068 - val_smape: 0.4212

Epoch 5/8

3832/3832 - 41s - 11ms/step - ia: 0.8298 - loss: 0.1091 - mae: 0.2112 - rmse: 0.2887 - smape: 0.4620 - val_ia: 0.4362 - val_loss: 0.0786 - val_mae: 0.2078 - val_rmse: 0.2422 - val_smape: 0.5011

Epoch 6/8

3832/3832 - 41s - 11ms/step - ia: 0.8336 - loss: 0.1034 - mae: 0.2068 - rmse: 0.2822 - smape: 0.4544 - val_ia: 0.4678 - val_loss: 0.0672 - val_mae: 0.1792 - val_rmse: 0.2152 - val_smape: 0.4355

Epoch 7/8

3832/3832 - 29s - 8ms/step - ia: 0.8355 - loss: 0.1046 - mae: 0.2052 - rmse: 0.2807 - smape: 0.4511 - val_ia: 0.4610 - val_loss: 0.0697 - val_mae: 0.1865 - val_rmse: 0.2242 - val_smape: 0.4514

Epoch 8/8

3832/3832 - 42s - 11ms/step - ia: 0.8348 - loss: 0.1053 - mae: 0.2055 - rmse: 0.2809 - smape: 0.4541 - val_ia: 0.4415 - val_loss: 0.0790 - val_mae: 0.2006 - val_rmse: 0.2353 - val_smape: 0.4725

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:06 940ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 86%|████████▌ | 43/50 [14:23:50<53:34, 459.26s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1916/1916 - 40s - 21ms/step - ia: 0.7884 - loss: 0.1836 - mae: 0.2772 - rmse: 0.3887 - smape: 0.5924 - val_ia: 0.6141 - val_loss: 0.0742 - val_mae: 0.1623 - val_rmse: 0.2182 - val_smape: 0.4117

Epoch 2/32

1916/1916 - 40s - 21ms/step - ia: 0.8311 - loss: 0.1232 - mae: 0.2262 - rmse: 0.3196 - smape: 0.4975 - val_ia: 0.6361 - val_loss: 0.0628 - val_mae: 0.1503 - val_rmse: 0.2031 - val_smape: 0.3859

Epoch 3/32

1916/1916 - 27s - 14ms/step - ia: 0.8451 - loss: 0.1061 - mae: 0.2097 - rmse: 0.2980 - smape: 0.4687 - val_ia: 0.6357 - val_loss: 0.0635 - val_mae: 0.1504 - val_rmse: 0.2008 - val_smape: 0.3881

Epoch 4/32

1916/1916 - 43s - 22ms/step - ia: 0.8468 - loss: 0.1054 - mae: 0.2070 - rmse: 0.2963 - smape: 0.4603 - val_ia: 0.6512 - val_loss: 0.0627 - val_mae: 0.1456 - val_rmse: 0.1968 - val_smape: 0.3700

Epoch 5/32

1916/1916 - 29s - 15ms/step - ia: 0.8517 - loss: 0.0987 - mae: 0.2016 - rmse: 0.2875 - smape: 0.4528 - val_ia: 0.6396 - val_loss: 0.0593 - val_mae: 0.1485 - val_rmse: 0.1996 - val_smape: 0.3799

Epoch 6/32

1916/1916 - 29s - 15ms/step - ia: 0.8528 - loss: 0.0960 - mae: 0.1983 - rmse: 0.2827 - smape: 0.4473 - val_ia: 0.6079 - val_loss: 0.0652 - val_mae: 0.1630 - val_rmse: 0.2111 - val_smape: 0.4215

Epoch 7/32

1916/1916 - 29s - 15ms/step - ia: 0.8548 - loss: 0.0971 - mae: 0.1973 - rmse: 0.2838 - smape: 0.4433 - val_ia: 0.6341 - val_loss: 0.0586 - val_mae: 0.1481 - val_rmse: 0.1977 - val_smape: 0.3822

Epoch 8/32

1916/1916 - 28s - 15ms/step - ia: 0.8551 - loss: 0.0941 - mae: 0.1965 - rmse: 0.2812 - smape: 0.4418 - val_ia: 0.6498 - val_loss: 0.0733 - val_mae: 0.1585 - val_rmse: 0.2072 - val_smape: 0.3759

Epoch 9/32

1916/1916 - 28s - 14ms/step - ia: 0.8545 - loss: 0.0950 - mae: 0.1970 - rmse: 0.2824 - smape: 0.4441 - val_ia: 0.6499 - val_loss: 0.0567 - val_mae: 0.1413 - val_rmse: 0.1928 - val_smape: 0.3749

Epoch 10/32

1916/1916 - 28s - 14ms/step - ia: 0.8572 - loss: 0.0913 - mae: 0.1943 - rmse: 0.2770 - smape: 0.4414 - val_ia: 0.6474 - val_loss: 0.0567 - val_mae: 0.1414 - val_rmse: 0.1930 - val_smape: 0.3682

Epoch 11/32

1916/1916 - 40s - 21ms/step - ia: 0.8578 - loss: 0.0914 - mae: 0.1935 - rmse: 0.2761 - smape: 0.4377 - val_ia: 0.6582 - val_loss: 0.0618 - val_mae: 0.1444 - val_rmse: 0.1942 - val_smape: 0.3661

Epoch 12/32

1916/1916 - 27s - 14ms/step - ia: 0.8585 - loss: 0.0918 - mae: 0.1918 - rmse: 0.2750 - smape: 0.4357 - val_ia: 0.6447 - val_loss: 0.0562 - val_mae: 0.1435 - val_rmse: 0.1941 - val_smape: 0.3970

Epoch 13/32

1916/1916 - 41s - 22ms/step - ia: 0.8598 - loss: 0.0894 - mae: 0.1905 - rmse: 0.2738 - smape: 0.4337 - val_ia: 0.6353 - val_loss: 0.0605 - val_mae: 0.1507 - val_rmse: 0.1995 - val_smape: 0.3804

Epoch 14/32

1916/1916 - 27s - 14ms/step - ia: 0.8609 - loss: 0.0861 - mae: 0.1891 - rmse: 0.2696 - smape: 0.4308 - val_ia: 0.6650 - val_loss: 0.0577 - val_mae: 0.1388 - val_rmse: 0.1904 - val_smape: 0.3678

Epoch 15/32

1916/1916 - 28s - 15ms/step - ia: 0.8615 - loss: 0.0868 - mae: 0.1878 - rmse: 0.2692 - smape: 0.4305 - val_ia: 0.6590 - val_loss: 0.0587 - val_mae: 0.1400 - val_rmse: 0.1916 - val_smape: 0.3600

Epoch 16/32

1916/1916 - 27s - 14ms/step - ia: 0.8616 - loss: 0.0878 - mae: 0.1878 - rmse: 0.2707 - smape: 0.4279 - val_ia: 0.6406 - val_loss: 0.0592 - val_mae: 0.1451 - val_rmse: 0.1960 - val_smape: 0.3729

Epoch 17/32

1916/1916 - 28s - 14ms/step - ia: 0.8616 - loss: 0.0889 - mae: 0.1881 - rmse: 0.2702 - smape: 0.4303 - val_ia: 0.6706 - val_loss: 0.0595 - val_mae: 0.1402 - val_rmse: 0.1930 - val_smape: 0.3760

Epoch 18/32

1916/1916 - 40s - 21ms/step - ia: 0.8627 - loss: 0.0842 - mae: 0.1860 - rmse: 0.2670 - smape: 0.4264 - val_ia: 0.6307 - val_loss: 0.0620 - val_mae: 0.1534 - val_rmse: 0.2013 - val_smape: 0.3813

Epoch 19/32

1916/1916 - 27s - 14ms/step - ia: 0.8626 - loss: 0.0862 - mae: 0.1863 - rmse: 0.2675 - smape: 0.4260 - val_ia: 0.6831 - val_loss: 0.0566 - val_mae: 0.1319 - val_rmse: 0.1860 - val_smape: 0.3562

Epoch 20/32

1916/1916 - 23s - 12ms/step - ia: 0.8636 - loss: 0.0834 - mae: 0.1853 - rmse: 0.2655 - smape: 0.4271 - val_ia: 0.6705 - val_loss: 0.0552 - val_mae: 0.1358 - val_rmse: 0.1864 - val_smape: 0.3541

Epoch 21/32

1916/1916 - 19s - 10ms/step - ia: 0.8633 - loss: 0.0836 - mae: 0.1851 - rmse: 0.2644 - smape: 0.4282 - val_ia: 0.6852 - val_loss: 0.0538 - val_mae: 0.1305 - val_rmse: 0.1830 - val_smape: 0.3493

Epoch 22/32

1916/1916 - 29s - 15ms/step - ia: 0.8625 - loss: 0.0863 - mae: 0.1864 - rmse: 0.2683 - smape: 0.4262 - val_ia: 0.6789 - val_loss: 0.0545 - val_mae: 0.1323 - val_rmse: 0.1851 - val_smape: 0.3581

Epoch 23/32

1916/1916 - 27s - 14ms/step - ia: 0.8650 - loss: 0.0830 - mae: 0.1839 - rmse: 0.2644 - smape: 0.4241 - val_ia: 0.6582 - val_loss: 0.0565 - val_mae: 0.1407 - val_rmse: 0.1900 - val_smape: 0.3710

Epoch 24/32

1916/1916 - 28s - 15ms/step - ia: 0.8643 - loss: 0.0825 - mae: 0.1836 - rmse: 0.2623 - smape: 0.4234 - val_ia: 0.6567 - val_loss: 0.0557 - val_mae: 0.1400 - val_rmse: 0.1888 - val_smape: 0.3614

Epoch 25/32

1916/1916 - 27s - 14ms/step - ia: 0.8638 - loss: 0.0830 - mae: 0.1849 - rmse: 0.2653 - smape: 0.4253 - val_ia: 0.6682 - val_loss: 0.0585 - val_mae: 0.1372 - val_rmse: 0.1888 - val_smape: 0.3611

Epoch 26/32

1916/1916 - 27s - 14ms/step - ia: 0.8653 - loss: 0.0832 - mae: 0.1835 - rmse: 0.2639 - smape: 0.4222 - val_ia: 0.6333 - val_loss: 0.0620 - val_mae: 0.1516 - val_rmse: 0.2016 - val_smape: 0.3852

Epoch 27/32

1916/1916 - 28s - 14ms/step - ia: 0.8646 - loss: 0.0821 - mae: 0.1829 - rmse: 0.2622 - smape: 0.4230 - val_ia: 0.6745 - val_loss: 0.0541 - val_mae: 0.1339 - val_rmse: 0.1841 - val_smape: 0.3571

Epoch 28/32

1916/1916 - 27s - 14ms/step - ia: 0.8667 - loss: 0.0798 - mae: 0.1815 - rmse: 0.2591 - smape: 0.4201 - val_ia: 0.6801 - val_loss: 0.0558 - val_mae: 0.1344 - val_rmse: 0.1868 - val_smape: 0.3660

Epoch 29/32

1916/1916 - 27s - 14ms/step - ia: 0.8661 - loss: 0.0809 - mae: 0.1823 - rmse: 0.2609 - smape: 0.4213 - val_ia: 0.6572 - val_loss: 0.0548 - val_mae: 0.1392 - val_rmse: 0.1900 - val_smape: 0.3674

Epoch 30/32

1916/1916 - 42s - 22ms/step - ia: 0.8648 - loss: 0.0820 - mae: 0.1838 - rmse: 0.2631 - smape: 0.4241 - val_ia: 0.6429 - val_loss: 0.0604 - val_mae: 0.1466 - val_rmse: 0.1961 - val_smape: 0.3800

Epoch 31/32

1916/1916 - 27s - 14ms/step - ia: 0.8661 - loss: 0.0800 - mae: 0.1815 - rmse: 0.2595 - smape: 0.4227 - val_ia: 0.6605 - val_loss: 0.0590 - val_mae: 0.1396 - val_rmse: 0.1907 - val_smape: 0.3682

Epoch 32/32

1916/1916 - 41s - 21ms/step - ia: 0.8649 - loss: 0.0839 - mae: 0.1840 - rmse: 0.2639 - smape: 0.4233 - val_ia: 0.6837 - val_loss: 0.0564 - val_mae: 0.1339 - val_rmse: 0.1861 - val_smape: 0.3579

Restoring model weights from the end of the best epoch: 21.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:25 1s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step

 88%|████████▊ | 44/50 [14:40:11<1:01:35, 615.97s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

240/240 - 9s - 37ms/step - ia: 0.4310 - loss: 0.7166 - mae: 0.6286 - rmse: 0.8281 - smape: 1.2781 - val_ia: 0.5274 - val_loss: 0.3336 - val_mae: 0.4375 - val_rmse: 0.5471 - val_smape: 0.9827

Epoch 2/64

240/240 - 1s - 6ms/step - ia: 0.7023 - loss: 0.3030 - mae: 0.3849 - rmse: 0.5437 - smape: 0.8132 - val_ia: 0.6853 - val_loss: 0.1709 - val_mae: 0.2894 - val_rmse: 0.3883 - val_smape: 0.6689

Epoch 3/64

240/240 - 3s - 11ms/step - ia: 0.7732 - loss: 0.2176 - mae: 0.3105 - rmse: 0.4608 - smape: 0.6790 - val_ia: 0.7340 - val_loss: 0.1252 - val_mae: 0.2443 - val_rmse: 0.3347 - val_smape: 0.5892

Epoch 4/64

240/240 - 3s - 11ms/step - ia: 0.7944 - loss: 0.1849 - mae: 0.2840 - rmse: 0.4250 - smape: 0.6366 - val_ia: 0.7528 - val_loss: 0.1091 - val_mae: 0.2270 - val_rmse: 0.3137 - val_smape: 0.5589

Epoch 5/64

240/240 - 2s - 8ms/step - ia: 0.8066 - loss: 0.1667 - mae: 0.2690 - rmse: 0.4031 - smape: 0.6144 - val_ia: 0.7606 - val_loss: 0.1024 - val_mae: 0.2191 - val_rmse: 0.3042 - val_smape: 0.5432

Epoch 6/64

240/240 - 2s - 9ms/step - ia: 0.8165 - loss: 0.1570 - mae: 0.2571 - rmse: 0.3901 - smape: 0.5889 - val_ia: 0.7759 - val_loss: 0.0937 - val_mae: 0.2065 - val_rmse: 0.2906 - val_smape: 0.5179

Epoch 7/64

240/240 - 2s - 7ms/step - ia: 0.8217 - loss: 0.1516 - mae: 0.2497 - rmse: 0.3840 - smape: 0.5730 - val_ia: 0.7856 - val_loss: 0.0893 - val_mae: 0.1994 - val_rmse: 0.2832 - val_smape: 0.5021

Epoch 8/64

240/240 - 2s - 10ms/step - ia: 0.8297 - loss: 0.1394 - mae: 0.2402 - rmse: 0.3677 - smape: 0.5581 - val_ia: 0.7991 - val_loss: 0.0833 - val_mae: 0.1890 - val_rmse: 0.2724 - val_smape: 0.4807

Epoch 9/64

240/240 - 2s - 7ms/step - ia: 0.8337 - loss: 0.1348 - mae: 0.2347 - rmse: 0.3621 - smape: 0.5439 - val_ia: 0.8072 - val_loss: 0.0797 - val_mae: 0.1823 - val_rmse: 0.2662 - val_smape: 0.4658

Epoch 10/64

240/240 - 2s - 10ms/step - ia: 0.8378 - loss: 0.1319 - mae: 0.2295 - rmse: 0.3578 - smape: 0.5344 - val_ia: 0.8130 - val_loss: 0.0781 - val_mae: 0.1786 - val_rmse: 0.2624 - val_smape: 0.4551

Epoch 11/64

240/240 - 2s - 7ms/step - ia: 0.8405 - loss: 0.1262 - mae: 0.2262 - rmse: 0.3501 - smape: 0.5251 - val_ia: 0.8210 - val_loss: 0.0749 - val_mae: 0.1723 - val_rmse: 0.2560 - val_smape: 0.4413

Epoch 12/64

240/240 - 2s - 10ms/step - ia: 0.8444 - loss: 0.1221 - mae: 0.2210 - rmse: 0.3439 - smape: 0.5137 - val_ia: 0.8246 - val_loss: 0.0723 - val_mae: 0.1685 - val_rmse: 0.2518 - val_smape: 0.4329

Epoch 13/64

240/240 - 2s - 7ms/step - ia: 0.8482 - loss: 0.1166 - mae: 0.2166 - rmse: 0.3362 - smape: 0.5079 - val_ia: 0.8342 - val_loss: 0.0691 - val_mae: 0.1612 - val_rmse: 0.2452 - val_smape: 0.4191

Epoch 14/64

240/240 - 1s - 6ms/step - ia: 0.8508 - loss: 0.1161 - mae: 0.2133 - rmse: 0.3343 - smape: 0.4986 - val_ia: 0.8317 - val_loss: 0.0695 - val_mae: 0.1631 - val_rmse: 0.2457 - val_smape: 0.4205

Epoch 15/64

240/240 - 1s - 6ms/step - ia: 0.8528 - loss: 0.1134 - mae: 0.2103 - rmse: 0.3313 - smape: 0.4919 - val_ia: 0.8347 - val_loss: 0.0680 - val_mae: 0.1607 - val_rmse: 0.2426 - val_smape: 0.4152

Epoch 16/64

240/240 - 1s - 6ms/step - ia: 0.8539 - loss: 0.1114 - mae: 0.2087 - rmse: 0.3277 - smape: 0.4890 - val_ia: 0.8380 - val_loss: 0.0673 - val_mae: 0.1586 - val_rmse: 0.2407 - val_smape: 0.4104

Epoch 17/64

240/240 - 2s - 6ms/step - ia: 0.8567 - loss: 0.1089 - mae: 0.2055 - rmse: 0.3226 - smape: 0.4823 - val_ia: 0.8365 - val_loss: 0.0668 - val_mae: 0.1593 - val_rmse: 0.2399 - val_smape: 0.4082

Epoch 18/64

240/240 - 2s - 10ms/step - ia: 0.8585 - loss: 0.1084 - mae: 0.2033 - rmse: 0.3232 - smape: 0.4751 - val_ia: 0.8421 - val_loss: 0.0647 - val_mae: 0.1548 - val_rmse: 0.2356 - val_smape: 0.4010

Epoch 19/64

240/240 - 1s - 5ms/step - ia: 0.8590 - loss: 0.1067 - mae: 0.2017 - rmse: 0.3198 - smape: 0.4718 - val_ia: 0.8452 - val_loss: 0.0636 - val_mae: 0.1523 - val_rmse: 0.2334 - val_smape: 0.3953

Epoch 20/64

240/240 - 1s - 5ms/step - ia: 0.8602 - loss: 0.1067 - mae: 0.2002 - rmse: 0.3199 - smape: 0.4709 - val_ia: 0.8514 - val_loss: 0.0615 - val_mae: 0.1472 - val_rmse: 0.2293 - val_smape: 0.3870

Epoch 21/64

240/240 - 1s - 5ms/step - ia: 0.8603 - loss: 0.1059 - mae: 0.2009 - rmse: 0.3194 - smape: 0.4674 - val_ia: 0.8469 - val_loss: 0.0621 - val_mae: 0.1505 - val_rmse: 0.2303 - val_smape: 0.3901

Epoch 22/64

240/240 - 2s - 7ms/step - ia: 0.8620 - loss: 0.1044 - mae: 0.1982 - rmse: 0.3171 - smape: 0.4635 - val_ia: 0.8551 - val_loss: 0.0602 - val_mae: 0.1446 - val_rmse: 0.2261 - val_smape: 0.3803

Epoch 23/64

240/240 - 1s - 6ms/step - ia: 0.8651 - loss: 0.0999 - mae: 0.1943 - rmse: 0.3102 - smape: 0.4588 - val_ia: 0.8521 - val_loss: 0.0606 - val_mae: 0.1468 - val_rmse: 0.2270 - val_smape: 0.3823

Epoch 24/64

240/240 - 1s - 6ms/step - ia: 0.8655 - loss: 0.0969 - mae: 0.1933 - rmse: 0.3059 - smape: 0.4547 - val_ia: 0.8538 - val_loss: 0.0601 - val_mae: 0.1458 - val_rmse: 0.2256 - val_smape: 0.3788

Epoch 25/64

240/240 - 1s - 6ms/step - ia: 0.8652 - loss: 0.1005 - mae: 0.1939 - rmse: 0.3111 - smape: 0.4533 - val_ia: 0.8534 - val_loss: 0.0605 - val_mae: 0.1467 - val_rmse: 0.2257 - val_smape: 0.3795

Epoch 26/64

240/240 - 3s - 11ms/step - ia: 0.8672 - loss: 0.0964 - mae: 0.1909 - rmse: 0.3039 - smape: 0.4491 - val_ia: 0.8549 - val_loss: 0.0592 - val_mae: 0.1446 - val_rmse: 0.2235 - val_smape: 0.3747

Epoch 27/64

240/240 - 3s - 11ms/step - ia: 0.8677 - loss: 0.0980 - mae: 0.1908 - rmse: 0.3066 - smape: 0.4486 - val_ia: 0.8552 - val_loss: 0.0587 - val_mae: 0.1441 - val_rmse: 0.2224 - val_smape: 0.3743

Epoch 28/64

240/240 - 3s - 12ms/step - ia: 0.8683 - loss: 0.0967 - mae: 0.1899 - rmse: 0.3045 - smape: 0.4461 - val_ia: 0.8597 - val_loss: 0.0577 - val_mae: 0.1406 - val_rmse: 0.2199 - val_smape: 0.3678

Epoch 29/64

240/240 - 2s - 10ms/step - ia: 0.8700 - loss: 0.0943 - mae: 0.1874 - rmse: 0.3010 - smape: 0.4430 - val_ia: 0.8603 - val_loss: 0.0573 - val_mae: 0.1399 - val_rmse: 0.2193 - val_smape: 0.3669

Epoch 30/64

240/240 - 2s - 7ms/step - ia: 0.8695 - loss: 0.0956 - mae: 0.1884 - rmse: 0.3025 - smape: 0.4419 - val_ia: 0.8551 - val_loss: 0.0589 - val_mae: 0.1446 - val_rmse: 0.2223 - val_smape: 0.3708

Epoch 31/64

240/240 - 2s - 6ms/step - ia: 0.8698 - loss: 0.0948 - mae: 0.1877 - rmse: 0.3017 - smape: 0.4417 - val_ia: 0.8633 - val_loss: 0.0567 - val_mae: 0.1377 - val_rmse: 0.2177 - val_smape: 0.3627

Epoch 32/64

240/240 - 2s - 6ms/step - ia: 0.8709 - loss: 0.0938 - mae: 0.1864 - rmse: 0.3003 - smape: 0.4371 - val_ia: 0.8609 - val_loss: 0.0565 - val_mae: 0.1388 - val_rmse: 0.2178 - val_smape: 0.3641

Epoch 33/64

240/240 - 2s - 10ms/step - ia: 0.8711 - loss: 0.0945 - mae: 0.1858 - rmse: 0.3002 - smape: 0.4361 - val_ia: 0.8622 - val_loss: 0.0576 - val_mae: 0.1396 - val_rmse: 0.2188 - val_smape: 0.3640

Epoch 34/64

240/240 - 3s - 11ms/step - ia: 0.8720 - loss: 0.0920 - mae: 0.1852 - rmse: 0.2974 - smape: 0.4329 - val_ia: 0.8637 - val_loss: 0.0568 - val_mae: 0.1380 - val_rmse: 0.2174 - val_smape: 0.3618

Epoch 35/64

240/240 - 1s - 6ms/step - ia: 0.8721 - loss: 0.0915 - mae: 0.1843 - rmse: 0.2967 - smape: 0.4323 - val_ia: 0.8621 - val_loss: 0.0567 - val_mae: 0.1388 - val_rmse: 0.2175 - val_smape: 0.3625

Epoch 36/64

240/240 - 1s - 6ms/step - ia: 0.8719 - loss: 0.0924 - mae: 0.1847 - rmse: 0.2979 - smape: 0.4334 - val_ia: 0.8615 - val_loss: 0.0566 - val_mae: 0.1386 - val_rmse: 0.2177 - val_smape: 0.3616

Epoch 37/64

240/240 - 1s - 6ms/step - ia: 0.8725 - loss: 0.0943 - mae: 0.1846 - rmse: 0.2999 - smape: 0.4303 - val_ia: 0.8615 - val_loss: 0.0584 - val_mae: 0.1411 - val_rmse: 0.2196 - val_smape: 0.3628

Epoch 38/64

240/240 - 3s - 11ms/step - ia: 0.8716 - loss: 0.0946 - mae: 0.1853 - rmse: 0.3016 - smape: 0.4300 - val_ia: 0.8634 - val_loss: 0.0567 - val_mae: 0.1381 - val_rmse: 0.2169 - val_smape: 0.3603

Epoch 39/64

240/240 - 1s - 6ms/step - ia: 0.8740 - loss: 0.0900 - mae: 0.1820 - rmse: 0.2938 - smape: 0.4275 - val_ia: 0.8648 - val_loss: 0.0559 - val_mae: 0.1366 - val_rmse: 0.2155 - val_smape: 0.3584

Epoch 40/64

240/240 - 1s - 6ms/step - ia: 0.8744 - loss: 0.0889 - mae: 0.1815 - rmse: 0.2921 - smape: 0.4282 - val_ia: 0.8614 - val_loss: 0.0570 - val_mae: 0.1394 - val_rmse: 0.2179 - val_smape: 0.3616

Epoch 41/64

240/240 - 1s - 6ms/step - ia: 0.8736 - loss: 0.0919 - mae: 0.1825 - rmse: 0.2956 - smape: 0.4269 - val_ia: 0.8649 - val_loss: 0.0561 - val_mae: 0.1367 - val_rmse: 0.2160 - val_smape: 0.3575

Epoch 42/64

240/240 - 1s - 6ms/step - ia: 0.8732 - loss: 0.0924 - mae: 0.1835 - rmse: 0.2971 - smape: 0.4265 - val_ia: 0.8653 - val_loss: 0.0559 - val_mae: 0.1362 - val_rmse: 0.2155 - val_smape: 0.3572

Epoch 43/64

240/240 - 1s - 6ms/step - ia: 0.8724 - loss: 0.0928 - mae: 0.1842 - rmse: 0.2991 - smape: 0.4272 - val_ia: 0.8658 - val_loss: 0.0560 - val_mae: 0.1359 - val_rmse: 0.2153 - val_smape: 0.3564

Epoch 44/64

240/240 - 1s - 6ms/step - ia: 0.8737 - loss: 0.0906 - mae: 0.1826 - rmse: 0.2953 - smape: 0.4254 - val_ia: 0.8672 - val_loss: 0.0558 - val_mae: 0.1346 - val_rmse: 0.2149 - val_smape: 0.3546

Epoch 45/64

240/240 - 1s - 6ms/step - ia: 0.8739 - loss: 0.0915 - mae: 0.1824 - rmse: 0.2947 - smape: 0.4244 - val_ia: 0.8643 - val_loss: 0.0567 - val_mae: 0.1375 - val_rmse: 0.2165 - val_smape: 0.3574

Epoch 46/64

240/240 - 2s - 10ms/step - ia: 0.8738 - loss: 0.0901 - mae: 0.1824 - rmse: 0.2942 - smape: 0.4240 - val_ia: 0.8646 - val_loss: 0.0565 - val_mae: 0.1370 - val_rmse: 0.2161 - val_smape: 0.3563

Epoch 47/64

240/240 - 1s - 6ms/step - ia: 0.8751 - loss: 0.0884 - mae: 0.1807 - rmse: 0.2909 - smape: 0.4240 - val_ia: 0.8637 - val_loss: 0.0562 - val_mae: 0.1370 - val_rmse: 0.2158 - val_smape: 0.3563

Epoch 48/64

240/240 - 2s - 7ms/step - ia: 0.8753 - loss: 0.0887 - mae: 0.1803 - rmse: 0.2919 - smape: 0.4205 - val_ia: 0.8640 - val_loss: 0.0561 - val_mae: 0.1368 - val_rmse: 0.2156 - val_smape: 0.3560

Epoch 49/64

240/240 - 1s - 6ms/step - ia: 0.8748 - loss: 0.0900 - mae: 0.1811 - rmse: 0.2939 - smape: 0.4223 - val_ia: 0.8655 - val_loss: 0.0558 - val_mae: 0.1355 - val_rmse: 0.2151 - val_smape: 0.3547

Epoch 50/64

240/240 - 3s - 11ms/step - ia: 0.8757 - loss: 0.0878 - mae: 0.1796 - rmse: 0.2902 - smape: 0.4204 - val_ia: 0.8676 - val_loss: 0.0556 - val_mae: 0.1343 - val_rmse: 0.2142 - val_smape: 0.3530

Epoch 51/64

240/240 - 3s - 11ms/step - ia: 0.8748 - loss: 0.0902 - mae: 0.1808 - rmse: 0.2939 - smape: 0.4210 - val_ia: 0.8633 - val_loss: 0.0561 - val_mae: 0.1370 - val_rmse: 0.2159 - val_smape: 0.3574

Epoch 52/64

240/240 - 2s - 7ms/step - ia: 0.8758 - loss: 0.0871 - mae: 0.1797 - rmse: 0.2895 - smape: 0.4193 - val_ia: 0.8648 - val_loss: 0.0561 - val_mae: 0.1362 - val_rmse: 0.2155 - val_smape: 0.3566

Epoch 53/64

240/240 - 2s - 10ms/step - ia: 0.8764 - loss: 0.0879 - mae: 0.1789 - rmse: 0.2898 - smape: 0.4182 - val_ia: 0.8685 - val_loss: 0.0554 - val_mae: 0.1333 - val_rmse: 0.2135 - val_smape: 0.3518

Epoch 54/64

240/240 - 1s - 6ms/step - ia: 0.8757 - loss: 0.0873 - mae: 0.1797 - rmse: 0.2889 - smape: 0.4224 - val_ia: 0.8666 - val_loss: 0.0561 - val_mae: 0.1352 - val_rmse: 0.2150 - val_smape: 0.3541

Epoch 55/64

240/240 - 3s - 11ms/step - ia: 0.8766 - loss: 0.0865 - mae: 0.1784 - rmse: 0.2881 - smape: 0.4165 - val_ia: 0.8660 - val_loss: 0.0559 - val_mae: 0.1356 - val_rmse: 0.2146 - val_smape: 0.3554

Epoch 56/64

240/240 - 1s - 6ms/step - ia: 0.8761 - loss: 0.0886 - mae: 0.1793 - rmse: 0.2909 - smape: 0.4155 - val_ia: 0.8649 - val_loss: 0.0567 - val_mae: 0.1369 - val_rmse: 0.2157 - val_smape: 0.3555

Epoch 57/64

240/240 - 2s - 10ms/step - ia: 0.8767 - loss: 0.0859 - mae: 0.1785 - rmse: 0.2880 - smape: 0.4199 - val_ia: 0.8666 - val_loss: 0.0559 - val_mae: 0.1349 - val_rmse: 0.2144 - val_smape: 0.3532

Epoch 58/64

240/240 - 3s - 11ms/step - ia: 0.8764 - loss: 0.0865 - mae: 0.1786 - rmse: 0.2881 - smape: 0.4155 - val_ia: 0.8680 - val_loss: 0.0554 - val_mae: 0.1333 - val_rmse: 0.2135 - val_smape: 0.3527

Epoch 59/64

240/240 - 1s - 6ms/step - ia: 0.8767 - loss: 0.0862 - mae: 0.1785 - rmse: 0.2876 - smape: 0.4150 - val_ia: 0.8638 - val_loss: 0.0556 - val_mae: 0.1363 - val_rmse: 0.2143 - val_smape: 0.3568

Epoch 60/64

240/240 - 1s - 6ms/step - ia: 0.8772 - loss: 0.0867 - mae: 0.1777 - rmse: 0.2879 - smape: 0.4142 - val_ia: 0.8647 - val_loss: 0.0557 - val_mae: 0.1359 - val_rmse: 0.2144 - val_smape: 0.3562

Epoch 61/64

240/240 - 1s - 6ms/step - ia: 0.8776 - loss: 0.0865 - mae: 0.1769 - rmse: 0.2883 - smape: 0.4148 - val_ia: 0.8656 - val_loss: 0.0560 - val_mae: 0.1355 - val_rmse: 0.2148 - val_smape: 0.3550

Epoch 62/64

240/240 - 2s - 6ms/step - ia: 0.8768 - loss: 0.0861 - mae: 0.1781 - rmse: 0.2874 - smape: 0.4170 - val_ia: 0.8654 - val_loss: 0.0559 - val_mae: 0.1357 - val_rmse: 0.2144 - val_smape: 0.3551

Epoch 63/64

240/240 - 1s - 6ms/step - ia: 0.8785 - loss: 0.0847 - mae: 0.1757 - rmse: 0.2846 - smape: 0.4130 - val_ia: 0.8669 - val_loss: 0.0552 - val_mae: 0.1338 - val_rmse: 0.2136 - val_smape: 0.3548

Epoch 64/64

240/240 - 2s - 10ms/step - ia: 0.8774 - loss: 0.0859 - mae: 0.1773 - rmse: 0.2862 - smape: 0.4176 - val_ia: 0.8702 - val_loss: 0.0550 - val_mae: 0.1320 - val_rmse: 0.2126 - val_smape: 0.3512

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:00 450ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 90%|█████████ | 45/50 [14:42:21<39:09, 469.96s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1916/1916 - 27s - 14ms/step - ia: 0.2728 - loss: 0.8597 - mae: 0.6896 - rmse: 0.8851 - smape: 1.5587 - val_ia: 0.2383 - val_loss: 0.6360 - val_mae: 0.5901 - val_rmse: 0.6503 - val_smape: 1.3368

Epoch 2/8

1916/1916 - 20s - 11ms/step - ia: 0.5254 - loss: 0.5330 - mae: 0.5115 - rmse: 0.6916 - smape: 1.0648 - val_ia: 0.2671 - val_loss: 0.4088 - val_mae: 0.4475 - val_rmse: 0.5143 - val_smape: 0.9275

Epoch 3/8

1916/1916 - 16s - 8ms/step - ia: 0.6442 - loss: 0.4182 - mae: 0.4338 - rmse: 0.6118 - smape: 0.8591 - val_ia: 0.2874 - val_loss: 0.3533 - val_mae: 0.4031 - val_rmse: 0.4733 - val_smape: 0.8270

Epoch 4/8

1916/1916 - 16s - 8ms/step - ia: 0.6731 - loss: 0.3833 - mae: 0.4117 - rmse: 0.5847 - smape: 0.8112 - val_ia: 0.2989 - val_loss: 0.3269 - val_mae: 0.3854 - val_rmse: 0.4552 - val_smape: 0.7954

Epoch 5/8

1916/1916 - 16s - 9ms/step - ia: 0.6856 - loss: 0.3614 - mae: 0.3985 - rmse: 0.5675 - smape: 0.7886 - val_ia: 0.3075 - val_loss: 0.3063 - val_mae: 0.3738 - val_rmse: 0.4427 - val_smape: 0.7788

Epoch 6/8

1916/1916 - 16s - 8ms/step - ia: 0.6955 - loss: 0.3422 - mae: 0.3872 - rmse: 0.5510 - smape: 0.7756 - val_ia: 0.3173 - val_loss: 0.2886 - val_mae: 0.3634 - val_rmse: 0.4317 - val_smape: 0.7679

Epoch 7/8

1916/1916 - 16s - 8ms/step - ia: 0.7028 - loss: 0.3286 - mae: 0.3781 - rmse: 0.5399 - smape: 0.7640 - val_ia: 0.3258 - val_loss: 0.2729 - val_mae: 0.3537 - val_rmse: 0.4213 - val_smape: 0.7531

Epoch 8/8

1916/1916 - 21s - 11ms/step - ia: 0.7091 - loss: 0.3137 - mae: 0.3701 - rmse: 0.5263 - smape: 0.7540 - val_ia: 0.3348 - val_loss: 0.2587 - val_mae: 0.3441 - val_rmse: 0.4115 - val_smape: 0.7391

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:13 988ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 92%|█████████▏| 46/50 [14:44:53<24:58, 374.58s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 31s - 258ms/step - ia: 0.5348 - loss: 0.5335 - mae: 0.5099 - rmse: 0.7222 - smape: 1.0735 - val_ia: 0.6109 - val_loss: 0.3706 - val_mae: 0.4176 - val_rmse: 0.5678 - val_smape: 0.8750

Epoch 2/32

120/120 - 19s - 162ms/step - ia: 0.6770 - loss: 0.3940 - mae: 0.4208 - rmse: 0.6248 - smape: 0.8471 - val_ia: 0.6341 - val_loss: 0.3154 - val_mae: 0.3868 - val_rmse: 0.5254 - val_smape: 0.8215

Epoch 3/32

120/120 - 17s - 145ms/step - ia: 0.7092 - loss: 0.3345 - mae: 0.3854 - rmse: 0.5751 - smape: 0.7861 - val_ia: 0.6772 - val_loss: 0.2568 - val_mae: 0.3450 - val_rmse: 0.4775 - val_smape: 0.7496

Epoch 4/32

120/120 - 20s - 166ms/step - ia: 0.7390 - loss: 0.2836 - mae: 0.3521 - rmse: 0.5295 - smape: 0.7325 - val_ia: 0.7056 - val_loss: 0.2260 - val_mae: 0.3195 - val_rmse: 0.4480 - val_smape: 0.7059

Epoch 5/32

120/120 - 21s - 177ms/step - ia: 0.7567 - loss: 0.2579 - mae: 0.3329 - rmse: 0.5047 - smape: 0.6987 - val_ia: 0.7205 - val_loss: 0.2117 - val_mae: 0.3063 - val_rmse: 0.4349 - val_smape: 0.6782

Epoch 6/32

120/120 - 18s - 147ms/step - ia: 0.7684 - loss: 0.2387 - mae: 0.3201 - rmse: 0.4844 - smape: 0.6766 - val_ia: 0.7351 - val_loss: 0.1950 - val_mae: 0.2918 - val_rmse: 0.4170 - val_smape: 0.6532

Epoch 7/32

120/120 - 18s - 148ms/step - ia: 0.7774 - loss: 0.2251 - mae: 0.3084 - rmse: 0.4709 - smape: 0.6599 - val_ia: 0.7440 - val_loss: 0.1796 - val_mae: 0.2796 - val_rmse: 0.4001 - val_smape: 0.6352

Epoch 8/32

120/120 - 21s - 175ms/step - ia: 0.7879 - loss: 0.2066 - mae: 0.2960 - rmse: 0.4509 - smape: 0.6401 - val_ia: 0.7506 - val_loss: 0.1654 - val_mae: 0.2701 - val_rmse: 0.3851 - val_smape: 0.6230

Epoch 9/32

120/120 - 20s - 165ms/step - ia: 0.7944 - loss: 0.1945 - mae: 0.2873 - rmse: 0.4370 - smape: 0.6283 - val_ia: 0.7617 - val_loss: 0.1523 - val_mae: 0.2584 - val_rmse: 0.3703 - val_smape: 0.6053

Epoch 10/32

120/120 - 17s - 146ms/step - ia: 0.8034 - loss: 0.1774 - mae: 0.2759 - rmse: 0.4188 - smape: 0.6106 - val_ia: 0.7690 - val_loss: 0.1402 - val_mae: 0.2480 - val_rmse: 0.3561 - val_smape: 0.5906

Epoch 11/32

120/120 - 18s - 149ms/step - ia: 0.8087 - loss: 0.1695 - mae: 0.2693 - rmse: 0.4082 - smape: 0.6001 - val_ia: 0.7827 - val_loss: 0.1313 - val_mae: 0.2363 - val_rmse: 0.3444 - val_smape: 0.5702

Epoch 12/32

120/120 - 13s - 106ms/step - ia: 0.8156 - loss: 0.1607 - mae: 0.2610 - rmse: 0.3983 - smape: 0.5845 - val_ia: 0.7866 - val_loss: 0.1233 - val_mae: 0.2299 - val_rmse: 0.3334 - val_smape: 0.5578

Epoch 13/32

120/120 - 18s - 149ms/step - ia: 0.8198 - loss: 0.1525 - mae: 0.2555 - rmse: 0.3878 - smape: 0.5777 - val_ia: 0.7972 - val_loss: 0.1153 - val_mae: 0.2195 - val_rmse: 0.3226 - val_smape: 0.5396

Epoch 14/32

120/120 - 17s - 145ms/step - ia: 0.8248 - loss: 0.1461 - mae: 0.2492 - rmse: 0.3792 - smape: 0.5659 - val_ia: 0.8014 - val_loss: 0.1095 - val_mae: 0.2152 - val_rmse: 0.3148 - val_smape: 0.5315

Epoch 15/32

120/120 - 17s - 145ms/step - ia: 0.8284 - loss: 0.1408 - mae: 0.2444 - rmse: 0.3720 - smape: 0.5576 - val_ia: 0.8057 - val_loss: 0.1053 - val_mae: 0.2102 - val_rmse: 0.3083 - val_smape: 0.5197

Epoch 16/32

120/120 - 17s - 138ms/step - ia: 0.8320 - loss: 0.1357 - mae: 0.2399 - rmse: 0.3649 - smape: 0.5524 - val_ia: 0.8130 - val_loss: 0.0995 - val_mae: 0.2028 - val_rmse: 0.3000 - val_smape: 0.5060

Epoch 17/32

120/120 - 17s - 145ms/step - ia: 0.8360 - loss: 0.1311 - mae: 0.2348 - rmse: 0.3586 - smape: 0.5395 - val_ia: 0.8216 - val_loss: 0.0953 - val_mae: 0.1951 - val_rmse: 0.2941 - val_smape: 0.4953

Epoch 18/32

120/120 - 17s - 145ms/step - ia: 0.8385 - loss: 0.1254 - mae: 0.2309 - rmse: 0.3514 - smape: 0.5341 - val_ia: 0.8225 - val_loss: 0.0912 - val_mae: 0.1935 - val_rmse: 0.2881 - val_smape: 0.4939

Epoch 19/32

120/120 - 18s - 148ms/step - ia: 0.8416 - loss: 0.1224 - mae: 0.2275 - rmse: 0.3468 - smape: 0.5283 - val_ia: 0.8293 - val_loss: 0.0872 - val_mae: 0.1857 - val_rmse: 0.2814 - val_smape: 0.4763

Epoch 20/32

120/120 - 18s - 150ms/step - ia: 0.8439 - loss: 0.1182 - mae: 0.2244 - rmse: 0.3415 - smape: 0.5224 - val_ia: 0.8321 - val_loss: 0.0850 - val_mae: 0.1833 - val_rmse: 0.2777 - val_smape: 0.4705

Epoch 21/32

120/120 - 17s - 143ms/step - ia: 0.8475 - loss: 0.1138 - mae: 0.2196 - rmse: 0.3345 - smape: 0.5125 - val_ia: 0.8366 - val_loss: 0.0805 - val_mae: 0.1783 - val_rmse: 0.2708 - val_smape: 0.4636

Epoch 22/32

120/120 - 21s - 174ms/step - ia: 0.8487 - loss: 0.1114 - mae: 0.2181 - rmse: 0.3307 - smape: 0.5096 - val_ia: 0.8345 - val_loss: 0.0804 - val_mae: 0.1791 - val_rmse: 0.2702 - val_smape: 0.4604

Epoch 23/32

120/120 - 17s - 146ms/step - ia: 0.8507 - loss: 0.1095 - mae: 0.2151 - rmse: 0.3282 - smape: 0.5045 - val_ia: 0.8418 - val_loss: 0.0767 - val_mae: 0.1725 - val_rmse: 0.2640 - val_smape: 0.4495

Epoch 24/32

120/120 - 18s - 147ms/step - ia: 0.8540 - loss: 0.1059 - mae: 0.2112 - rmse: 0.3222 - smape: 0.4975 - val_ia: 0.8455 - val_loss: 0.0741 - val_mae: 0.1688 - val_rmse: 0.2593 - val_smape: 0.4411

Epoch 25/32

120/120 - 17s - 138ms/step - ia: 0.8561 - loss: 0.1026 - mae: 0.2082 - rmse: 0.3176 - smape: 0.4904 - val_ia: 0.8479 - val_loss: 0.0716 - val_mae: 0.1658 - val_rmse: 0.2555 - val_smape: 0.4374

Epoch 26/32

120/120 - 18s - 147ms/step - ia: 0.8577 - loss: 0.1019 - mae: 0.2060 - rmse: 0.3156 - smape: 0.4878 - val_ia: 0.8483 - val_loss: 0.0702 - val_mae: 0.1648 - val_rmse: 0.2529 - val_smape: 0.4337

Epoch 27/32

120/120 - 17s - 143ms/step - ia: 0.8594 - loss: 0.0992 - mae: 0.2039 - rmse: 0.3121 - smape: 0.4841 - val_ia: 0.8509 - val_loss: 0.0684 - val_mae: 0.1621 - val_rmse: 0.2496 - val_smape: 0.4268

Epoch 28/32

120/120 - 17s - 145ms/step - ia: 0.8610 - loss: 0.0969 - mae: 0.2014 - rmse: 0.3084 - smape: 0.4791 - val_ia: 0.8534 - val_loss: 0.0670 - val_mae: 0.1594 - val_rmse: 0.2468 - val_smape: 0.4207

Epoch 29/32

120/120 - 17s - 143ms/step - ia: 0.8635 - loss: 0.0937 - mae: 0.1981 - rmse: 0.3035 - smape: 0.4721 - val_ia: 0.8571 - val_loss: 0.0657 - val_mae: 0.1569 - val_rmse: 0.2438 - val_smape: 0.4135

Epoch 30/32

120/120 - 21s - 177ms/step - ia: 0.8644 - loss: 0.0942 - mae: 0.1969 - rmse: 0.3032 - smape: 0.4705 - val_ia: 0.8551 - val_loss: 0.0648 - val_mae: 0.1573 - val_rmse: 0.2433 - val_smape: 0.4198

Epoch 31/32

120/120 - 18s - 146ms/step - ia: 0.8659 - loss: 0.0910 - mae: 0.1949 - rmse: 0.2987 - smape: 0.4661 - val_ia: 0.8602 - val_loss: 0.0628 - val_mae: 0.1531 - val_rmse: 0.2385 - val_smape: 0.4080

Epoch 32/32

120/120 - 17s - 144ms/step - ia: 0.8663 - loss: 0.0904 - mae: 0.1946 - rmse: 0.2973 - smape: 0.4645 - val_ia: 0.8631 - val_loss: 0.0618 - val_mae: 0.1502 - val_rmse: 0.2365 - val_smape: 0.4017

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:19 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 94%|█████████▍| 47/50 [14:54:49<22:03, 441.04s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 12s - 26ms/step - ia: 0.7913 - loss: 0.1884 - mae: 0.2838 - rmse: 0.4144 - smape: 0.6071 - val_ia: 0.7574 - val_loss: 0.0762 - val_mae: 0.1805 - val_rmse: 0.2494 - val_smape: 0.4408

Epoch 2/64

479/479 - 4s - 8ms/step - ia: 0.8432 - loss: 0.1162 - mae: 0.2226 - rmse: 0.3309 - smape: 0.4907 - val_ia: 0.8099 - val_loss: 0.0627 - val_mae: 0.1496 - val_rmse: 0.2198 - val_smape: 0.3833

Epoch 3/64

479/479 - 5s - 11ms/step - ia: 0.8503 - loss: 0.1085 - mae: 0.2130 - rmse: 0.3206 - smape: 0.4668 - val_ia: 0.8158 - val_loss: 0.0602 - val_mae: 0.1441 - val_rmse: 0.2173 - val_smape: 0.3756

Epoch 4/64

479/479 - 5s - 11ms/step - ia: 0.8537 - loss: 0.1043 - mae: 0.2080 - rmse: 0.3132 - smape: 0.4579 - val_ia: 0.8326 - val_loss: 0.0577 - val_mae: 0.1352 - val_rmse: 0.2091 - val_smape: 0.3618

Epoch 5/64

479/479 - 5s - 11ms/step - ia: 0.8564 - loss: 0.1021 - mae: 0.2048 - rmse: 0.3088 - smape: 0.4521 - val_ia: 0.8249 - val_loss: 0.0589 - val_mae: 0.1393 - val_rmse: 0.2106 - val_smape: 0.3655

Epoch 6/64

479/479 - 4s - 8ms/step - ia: 0.8585 - loss: 0.1017 - mae: 0.2025 - rmse: 0.3082 - smape: 0.4429 - val_ia: 0.8096 - val_loss: 0.0588 - val_mae: 0.1437 - val_rmse: 0.2141 - val_smape: 0.3780

Epoch 7/64

479/479 - 4s - 7ms/step - ia: 0.8587 - loss: 0.1001 - mae: 0.2019 - rmse: 0.3060 - smape: 0.4443 - val_ia: 0.8090 - val_loss: 0.0607 - val_mae: 0.1474 - val_rmse: 0.2157 - val_smape: 0.3776

Epoch 8/64

479/479 - 5s - 11ms/step - ia: 0.8607 - loss: 0.0961 - mae: 0.1986 - rmse: 0.3006 - smape: 0.4399 - val_ia: 0.7919 - val_loss: 0.0652 - val_mae: 0.1583 - val_rmse: 0.2237 - val_smape: 0.3890

Epoch 9/64

479/479 - 4s - 7ms/step - ia: 0.8614 - loss: 0.0946 - mae: 0.1977 - rmse: 0.2982 - smape: 0.4365 - val_ia: 0.8250 - val_loss: 0.0575 - val_mae: 0.1376 - val_rmse: 0.2100 - val_smape: 0.3627

Epoch 10/64

479/479 - 3s - 7ms/step - ia: 0.8623 - loss: 0.0957 - mae: 0.1968 - rmse: 0.2994 - smape: 0.4357 - val_ia: 0.8230 - val_loss: 0.0570 - val_mae: 0.1393 - val_rmse: 0.2084 - val_smape: 0.3651

Epoch 11/64

479/479 - 3s - 7ms/step - ia: 0.8612 - loss: 0.0975 - mae: 0.1985 - rmse: 0.3019 - smape: 0.4362 - val_ia: 0.8278 - val_loss: 0.0552 - val_mae: 0.1344 - val_rmse: 0.2044 - val_smape: 0.3553

Epoch 12/64

479/479 - 4s - 8ms/step - ia: 0.8631 - loss: 0.0936 - mae: 0.1958 - rmse: 0.2972 - smape: 0.4340 - val_ia: 0.8396 - val_loss: 0.0547 - val_mae: 0.1303 - val_rmse: 0.2035 - val_smape: 0.3553

Epoch 13/64

479/479 - 5s - 11ms/step - ia: 0.8631 - loss: 0.0960 - mae: 0.1957 - rmse: 0.2988 - smape: 0.4308 - val_ia: 0.8309 - val_loss: 0.0562 - val_mae: 0.1334 - val_rmse: 0.2066 - val_smape: 0.3597

Epoch 14/64

479/479 - 4s - 7ms/step - ia: 0.8637 - loss: 0.0926 - mae: 0.1950 - rmse: 0.2960 - smape: 0.4327 - val_ia: 0.8341 - val_loss: 0.0556 - val_mae: 0.1337 - val_rmse: 0.2049 - val_smape: 0.3576

Epoch 15/64

479/479 - 5s - 11ms/step - ia: 0.8624 - loss: 0.0967 - mae: 0.1965 - rmse: 0.3008 - smape: 0.4316 - val_ia: 0.8329 - val_loss: 0.0544 - val_mae: 0.1325 - val_rmse: 0.2034 - val_smape: 0.3557

Epoch 16/64

479/479 - 5s - 11ms/step - ia: 0.8644 - loss: 0.0919 - mae: 0.1940 - rmse: 0.2942 - smape: 0.4284 - val_ia: 0.7798 - val_loss: 0.0597 - val_mae: 0.1581 - val_rmse: 0.2208 - val_smape: 0.3946

Epoch 17/64

479/479 - 4s - 7ms/step - ia: 0.8631 - loss: 0.0937 - mae: 0.1955 - rmse: 0.2967 - smape: 0.4314 - val_ia: 0.8275 - val_loss: 0.0560 - val_mae: 0.1367 - val_rmse: 0.2069 - val_smape: 0.3581

Epoch 18/64

479/479 - 5s - 11ms/step - ia: 0.8645 - loss: 0.0926 - mae: 0.1939 - rmse: 0.2948 - smape: 0.4289 - val_ia: 0.8316 - val_loss: 0.0544 - val_mae: 0.1336 - val_rmse: 0.2036 - val_smape: 0.3554

Epoch 19/64

479/479 - 5s - 11ms/step - ia: 0.8645 - loss: 0.0936 - mae: 0.1934 - rmse: 0.2958 - smape: 0.4257 - val_ia: 0.8321 - val_loss: 0.0655 - val_mae: 0.1427 - val_rmse: 0.2148 - val_smape: 0.3611

Epoch 20/64

479/479 - 4s - 7ms/step - ia: 0.8650 - loss: 0.0929 - mae: 0.1929 - rmse: 0.2945 - smape: 0.4295 - val_ia: 0.8321 - val_loss: 0.0541 - val_mae: 0.1327 - val_rmse: 0.2031 - val_smape: 0.3536

Epoch 21/64

479/479 - 4s - 8ms/step - ia: 0.8657 - loss: 0.0909 - mae: 0.1922 - rmse: 0.2930 - smape: 0.4244 - val_ia: 0.8294 - val_loss: 0.0568 - val_mae: 0.1368 - val_rmse: 0.2075 - val_smape: 0.3597

Epoch 22/64

479/479 - 3s - 7ms/step - ia: 0.8658 - loss: 0.0918 - mae: 0.1923 - rmse: 0.2942 - smape: 0.4261 - val_ia: 0.8138 - val_loss: 0.0559 - val_mae: 0.1422 - val_rmse: 0.2102 - val_smape: 0.3710

Epoch 23/64

479/479 - 3s - 7ms/step - ia: 0.8649 - loss: 0.0921 - mae: 0.1933 - rmse: 0.2948 - smape: 0.4287 - val_ia: 0.8358 - val_loss: 0.0545 - val_mae: 0.1319 - val_rmse: 0.2035 - val_smape: 0.3532

Epoch 24/64

479/479 - 4s - 8ms/step - ia: 0.8667 - loss: 0.0883 - mae: 0.1908 - rmse: 0.2885 - smape: 0.4253 - val_ia: 0.8206 - val_loss: 0.0550 - val_mae: 0.1390 - val_rmse: 0.2064 - val_smape: 0.3580

Epoch 25/64

479/479 - 5s - 10ms/step - ia: 0.8665 - loss: 0.0901 - mae: 0.1911 - rmse: 0.2912 - smape: 0.4231 - val_ia: 0.8166 - val_loss: 0.0567 - val_mae: 0.1412 - val_rmse: 0.2079 - val_smape: 0.3649

Epoch 26/64

479/479 - 4s - 7ms/step - ia: 0.8662 - loss: 0.0908 - mae: 0.1910 - rmse: 0.2920 - smape: 0.4232 - val_ia: 0.8301 - val_loss: 0.0530 - val_mae: 0.1326 - val_rmse: 0.2024 - val_smape: 0.3596

Epoch 27/64

479/479 - 4s - 7ms/step - ia: 0.8663 - loss: 0.0904 - mae: 0.1910 - rmse: 0.2908 - smape: 0.4244 - val_ia: 0.8427 - val_loss: 0.0532 - val_mae: 0.1295 - val_rmse: 0.2013 - val_smape: 0.3481

Epoch 28/64

479/479 - 3s - 7ms/step - ia: 0.8653 - loss: 0.0928 - mae: 0.1925 - rmse: 0.2943 - smape: 0.4243 - val_ia: 0.8324 - val_loss: 0.0605 - val_mae: 0.1399 - val_rmse: 0.2102 - val_smape: 0.3552

Epoch 29/64

479/479 - 4s - 7ms/step - ia: 0.8666 - loss: 0.0884 - mae: 0.1906 - rmse: 0.2879 - smape: 0.4231 - val_ia: 0.8214 - val_loss: 0.0557 - val_mae: 0.1398 - val_rmse: 0.2073 - val_smape: 0.3613

Epoch 30/64

479/479 - 5s - 11ms/step - ia: 0.8656 - loss: 0.0910 - mae: 0.1918 - rmse: 0.2919 - smape: 0.4264 - val_ia: 0.8448 - val_loss: 0.0528 - val_mae: 0.1271 - val_rmse: 0.2011 - val_smape: 0.3475

Epoch 31/64

479/479 - 3s - 7ms/step - ia: 0.8666 - loss: 0.0889 - mae: 0.1907 - rmse: 0.2889 - smape: 0.4230 - val_ia: 0.8371 - val_loss: 0.0572 - val_mae: 0.1353 - val_rmse: 0.2065 - val_smape: 0.3519

Epoch 32/64

479/479 - 5s - 11ms/step - ia: 0.8673 - loss: 0.0890 - mae: 0.1898 - rmse: 0.2889 - smape: 0.4237 - val_ia: 0.8350 - val_loss: 0.0524 - val_mae: 0.1307 - val_rmse: 0.2017 - val_smape: 0.3508

Epoch 33/64

479/479 - 5s - 11ms/step - ia: 0.8672 - loss: 0.0900 - mae: 0.1901 - rmse: 0.2903 - smape: 0.4214 - val_ia: 0.8175 - val_loss: 0.0558 - val_mae: 0.1411 - val_rmse: 0.2074 - val_smape: 0.3653

Epoch 34/64

479/479 - 4s - 8ms/step - ia: 0.8668 - loss: 0.0899 - mae: 0.1904 - rmse: 0.2911 - smape: 0.4231 - val_ia: 0.8386 - val_loss: 0.0534 - val_mae: 0.1324 - val_rmse: 0.2026 - val_smape: 0.3536

Epoch 35/64

479/479 - 3s - 7ms/step - ia: 0.8676 - loss: 0.0893 - mae: 0.1895 - rmse: 0.2895 - smape: 0.4211 - val_ia: 0.8311 - val_loss: 0.0555 - val_mae: 0.1336 - val_rmse: 0.2050 - val_smape: 0.3519

Epoch 36/64

479/479 - 3s - 6ms/step - ia: 0.8680 - loss: 0.0886 - mae: 0.1890 - rmse: 0.2887 - smape: 0.4229 - val_ia: 0.8377 - val_loss: 0.0541 - val_mae: 0.1325 - val_rmse: 0.2024 - val_smape: 0.3511

Epoch 37/64

479/479 - 6s - 12ms/step - ia: 0.8671 - loss: 0.0885 - mae: 0.1902 - rmse: 0.2891 - smape: 0.4228 - val_ia: 0.8260 - val_loss: 0.0534 - val_mae: 0.1352 - val_rmse: 0.2044 - val_smape: 0.3548

Epoch 38/64

479/479 - 4s - 7ms/step - ia: 0.8671 - loss: 0.0887 - mae: 0.1900 - rmse: 0.2891 - smape: 0.4247 - val_ia: 0.8154 - val_loss: 0.0610 - val_mae: 0.1472 - val_rmse: 0.2134 - val_smape: 0.3636

Epoch 39/64

479/479 - 3s - 7ms/step - ia: 0.8661 - loss: 0.0896 - mae: 0.1912 - rmse: 0.2906 - smape: 0.4227 - val_ia: 0.8448 - val_loss: 0.0525 - val_mae: 0.1291 - val_rmse: 0.2003 - val_smape: 0.3458

Epoch 40/64

479/479 - 4s - 8ms/step - ia: 0.8670 - loss: 0.0916 - mae: 0.1909 - rmse: 0.2912 - smape: 0.4214 - val_ia: 0.8388 - val_loss: 0.0524 - val_mae: 0.1296 - val_rmse: 0.2005 - val_smape: 0.3487

Epoch 41/64

479/479 - 4s - 8ms/step - ia: 0.8678 - loss: 0.0868 - mae: 0.1892 - rmse: 0.2864 - smape: 0.4215 - val_ia: 0.8357 - val_loss: 0.0551 - val_mae: 0.1352 - val_rmse: 0.2047 - val_smape: 0.3573

Epoch 42/64

479/479 - 5s - 10ms/step - ia: 0.8682 - loss: 0.0878 - mae: 0.1889 - rmse: 0.2875 - smape: 0.4198 - val_ia: 0.8313 - val_loss: 0.0524 - val_mae: 0.1319 - val_rmse: 0.2023 - val_smape: 0.3545

Epoch 43/64

479/479 - 4s - 7ms/step - ia: 0.8675 - loss: 0.0884 - mae: 0.1894 - rmse: 0.2884 - smape: 0.4223 - val_ia: 0.8062 - val_loss: 0.0579 - val_mae: 0.1479 - val_rmse: 0.2127 - val_smape: 0.3760

Epoch 44/64

479/479 - 4s - 7ms/step - ia: 0.8679 - loss: 0.0881 - mae: 0.1894 - rmse: 0.2876 - smape: 0.4203 - val_ia: 0.8147 - val_loss: 0.0550 - val_mae: 0.1413 - val_rmse: 0.2076 - val_smape: 0.3674

Epoch 45/64

479/479 - 5s - 11ms/step - ia: 0.8677 - loss: 0.0868 - mae: 0.1887 - rmse: 0.2859 - smape: 0.4200 - val_ia: 0.8380 - val_loss: 0.0534 - val_mae: 0.1312 - val_rmse: 0.2018 - val_smape: 0.3484

Epoch 46/64

479/479 - 4s - 8ms/step - ia: 0.8672 - loss: 0.0887 - mae: 0.1899 - rmse: 0.2891 - smape: 0.4240 - val_ia: 0.8459 - val_loss: 0.0513 - val_mae: 0.1267 - val_rmse: 0.1984 - val_smape: 0.3457

Epoch 47/64

479/479 - 4s - 8ms/step - ia: 0.8667 - loss: 0.0889 - mae: 0.1902 - rmse: 0.2893 - smape: 0.4227 - val_ia: 0.8389 - val_loss: 0.0543 - val_mae: 0.1327 - val_rmse: 0.2033 - val_smape: 0.3490

Epoch 48/64

479/479 - 3s - 7ms/step - ia: 0.8674 - loss: 0.0874 - mae: 0.1896 - rmse: 0.2865 - smape: 0.4216 - val_ia: 0.8329 - val_loss: 0.0564 - val_mae: 0.1362 - val_rmse: 0.2053 - val_smape: 0.3563

Epoch 49/64

479/479 - 6s - 12ms/step - ia: 0.8678 - loss: 0.0874 - mae: 0.1895 - rmse: 0.2875 - smape: 0.4206 - val_ia: 0.8385 - val_loss: 0.0541 - val_mae: 0.1329 - val_rmse: 0.2045 - val_smape: 0.3522

Epoch 50/64

479/479 - 6s - 12ms/step - ia: 0.8679 - loss: 0.0867 - mae: 0.1895 - rmse: 0.2864 - smape: 0.4211 - val_ia: 0.7986 - val_loss: 0.0570 - val_mae: 0.1503 - val_rmse: 0.2146 - val_smape: 0.3785

Epoch 51/64

479/479 - 4s - 7ms/step - ia: 0.8672 - loss: 0.0877 - mae: 0.1895 - rmse: 0.2875 - smape: 0.4208 - val_ia: 0.8237 - val_loss: 0.0563 - val_mae: 0.1396 - val_rmse: 0.2088 - val_smape: 0.3659

Epoch 52/64

479/479 - 6s - 12ms/step - ia: 0.8681 - loss: 0.0865 - mae: 0.1883 - rmse: 0.2856 - smape: 0.4205 - val_ia: 0.8445 - val_loss: 0.0525 - val_mae: 0.1284 - val_rmse: 0.2007 - val_smape: 0.3484

Epoch 53/64

479/479 - 4s - 8ms/step - ia: 0.8685 - loss: 0.0864 - mae: 0.1885 - rmse: 0.2854 - smape: 0.4186 - val_ia: 0.8287 - val_loss: 0.0546 - val_mae: 0.1354 - val_rmse: 0.2051 - val_smape: 0.3572

Epoch 54/64

479/479 - 4s - 8ms/step - ia: 0.8682 - loss: 0.0864 - mae: 0.1885 - rmse: 0.2856 - smape: 0.4197 - val_ia: 0.8203 - val_loss: 0.0581 - val_mae: 0.1426 - val_rmse: 0.2094 - val_smape: 0.3659

Epoch 55/64

479/479 - 4s - 8ms/step - ia: 0.8670 - loss: 0.0881 - mae: 0.1895 - rmse: 0.2887 - smape: 0.4206 - val_ia: 0.8332 - val_loss: 0.0527 - val_mae: 0.1322 - val_rmse: 0.2023 - val_smape: 0.3545

Epoch 56/64

479/479 - 4s - 7ms/step - ia: 0.8677 - loss: 0.0849 - mae: 0.1891 - rmse: 0.2839 - smape: 0.4223 - val_ia: 0.8332 - val_loss: 0.0571 - val_mae: 0.1394 - val_rmse: 0.2086 - val_smape: 0.3620

Epoch 57/64

479/479 - 4s - 8ms/step - ia: 0.8689 - loss: 0.0861 - mae: 0.1876 - rmse: 0.2843 - smape: 0.4183 - val_ia: 0.8312 - val_loss: 0.0533 - val_mae: 0.1341 - val_rmse: 0.2030 - val_smape: 0.3615

Epoch 58/64

479/479 - 4s - 7ms/step - ia: 0.8683 - loss: 0.0865 - mae: 0.1886 - rmse: 0.2860 - smape: 0.4208 - val_ia: 0.8148 - val_loss: 0.0563 - val_mae: 0.1431 - val_rmse: 0.2096 - val_smape: 0.3653

Epoch 59/64

479/479 - 5s - 11ms/step - ia: 0.8687 - loss: 0.0870 - mae: 0.1881 - rmse: 0.2859 - smape: 0.4213 - val_ia: 0.8255 - val_loss: 0.0632 - val_mae: 0.1451 - val_rmse: 0.2142 - val_smape: 0.3613

Epoch 60/64

479/479 - 4s - 8ms/step - ia: 0.8679 - loss: 0.0857 - mae: 0.1888 - rmse: 0.2841 - smape: 0.4208 - val_ia: 0.8379 - val_loss: 0.0520 - val_mae: 0.1300 - val_rmse: 0.1995 - val_smape: 0.3497

Epoch 61/64

479/479 - 5s - 10ms/step - ia: 0.8694 - loss: 0.0838 - mae: 0.1872 - rmse: 0.2817 - smape: 0.4175 - val_ia: 0.8185 - val_loss: 0.0551 - val_mae: 0.1408 - val_rmse: 0.2075 - val_smape: 0.3682

Epoch 61: early stopping

Restoring model weights from the end of the best epoch: 46.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:25 634ms/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 96%|█████████▌| 48/50 [14:59:13<12:55, 387.98s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3832/3832 - 87s - 23ms/step - ia: 0.6931 - loss: 0.3197 - mae: 0.3630 - rmse: 0.4903 - smape: 0.7445 - val_ia: 0.3635 - val_loss: 0.1214 - val_mae: 0.2265 - val_rmse: 0.2708 - val_smape: 0.5390

Epoch 2/32

3832/3832 - 71s - 19ms/step - ia: 0.7753 - loss: 0.1736 - mae: 0.2758 - rmse: 0.3722 - smape: 0.5966 - val_ia: 0.4101 - val_loss: 0.0966 - val_mae: 0.1979 - val_rmse: 0.2421 - val_smape: 0.4793

Epoch 3/32

3832/3832 - 73s - 19ms/step - ia: 0.8018 - loss: 0.1357 - mae: 0.2434 - rmse: 0.3283 - smape: 0.5410 - val_ia: 0.4700 - val_loss: 0.0731 - val_mae: 0.1674 - val_rmse: 0.2095 - val_smape: 0.4292

Epoch 4/32

3832/3832 - 75s - 20ms/step - ia: 0.8160 - loss: 0.1205 - mae: 0.2270 - rmse: 0.3064 - smape: 0.5148 - val_ia: 0.4733 - val_loss: 0.0667 - val_mae: 0.1640 - val_rmse: 0.2043 - val_smape: 0.4276

Epoch 5/32

3832/3832 - 71s - 19ms/step - ia: 0.8278 - loss: 0.1081 - mae: 0.2145 - rmse: 0.2898 - smape: 0.4929 - val_ia: 0.4949 - val_loss: 0.0687 - val_mae: 0.1546 - val_rmse: 0.1979 - val_smape: 0.3989

Epoch 6/32

3832/3832 - 72s - 19ms/step - ia: 0.8307 - loss: 0.1060 - mae: 0.2092 - rmse: 0.2833 - smape: 0.4798 - val_ia: 0.4834 - val_loss: 0.0660 - val_mae: 0.1588 - val_rmse: 0.1985 - val_smape: 0.4193

Epoch 7/32

3832/3832 - 73s - 19ms/step - ia: 0.8370 - loss: 0.1016 - mae: 0.2035 - rmse: 0.2777 - smape: 0.4698 - val_ia: 0.4855 - val_loss: 0.0801 - val_mae: 0.1695 - val_rmse: 0.2081 - val_smape: 0.4092

Epoch 8/32

3832/3832 - 71s - 19ms/step - ia: 0.8399 - loss: 0.0982 - mae: 0.1993 - rmse: 0.2716 - smape: 0.4627 - val_ia: 0.4948 - val_loss: 0.0721 - val_mae: 0.1659 - val_rmse: 0.2035 - val_smape: 0.4090

Epoch 9/32

3832/3832 - 71s - 19ms/step - ia: 0.8425 - loss: 0.0935 - mae: 0.1946 - rmse: 0.2655 - smape: 0.4516 - val_ia: 0.5189 - val_loss: 0.0561 - val_mae: 0.1441 - val_rmse: 0.1831 - val_smape: 0.3790

Epoch 10/32

3832/3832 - 61s - 16ms/step - ia: 0.8456 - loss: 0.0918 - mae: 0.1916 - rmse: 0.2620 - smape: 0.4459 - val_ia: 0.4944 - val_loss: 0.0595 - val_mae: 0.1565 - val_rmse: 0.1949 - val_smape: 0.4018

Epoch 11/32

3832/3832 - 72s - 19ms/step - ia: 0.8471 - loss: 0.0907 - mae: 0.1904 - rmse: 0.2610 - smape: 0.4422 - val_ia: 0.5158 - val_loss: 0.0602 - val_mae: 0.1442 - val_rmse: 0.1854 - val_smape: 0.3846

Epoch 12/32

3832/3832 - 70s - 18ms/step - ia: 0.8475 - loss: 0.0902 - mae: 0.1892 - rmse: 0.2593 - smape: 0.4391 - val_ia: 0.5372 - val_loss: 0.0572 - val_mae: 0.1378 - val_rmse: 0.1795 - val_smape: 0.3636

Epoch 13/32

3832/3832 - 72s - 19ms/step - ia: 0.8503 - loss: 0.0875 - mae: 0.1866 - rmse: 0.2555 - smape: 0.4342 - val_ia: 0.5414 - val_loss: 0.0543 - val_mae: 0.1359 - val_rmse: 0.1763 - val_smape: 0.3614

Epoch 14/32

3832/3832 - 80s - 21ms/step - ia: 0.8496 - loss: 0.0867 - mae: 0.1861 - rmse: 0.2547 - smape: 0.4333 - val_ia: 0.5416 - val_loss: 0.0558 - val_mae: 0.1364 - val_rmse: 0.1776 - val_smape: 0.3667

Epoch 15/32

3832/3832 - 74s - 19ms/step - ia: 0.8507 - loss: 0.0870 - mae: 0.1851 - rmse: 0.2535 - smape: 0.4339 - val_ia: 0.5208 - val_loss: 0.0641 - val_mae: 0.1494 - val_rmse: 0.1887 - val_smape: 0.3845

Epoch 16/32

3832/3832 - 72s - 19ms/step - ia: 0.8513 - loss: 0.0859 - mae: 0.1844 - rmse: 0.2531 - smape: 0.4300 - val_ia: 0.5387 - val_loss: 0.0560 - val_mae: 0.1374 - val_rmse: 0.1776 - val_smape: 0.3629

Epoch 17/32

3832/3832 - 71s - 19ms/step - ia: 0.8542 - loss: 0.0851 - mae: 0.1830 - rmse: 0.2510 - smape: 0.4265 - val_ia: 0.5288 - val_loss: 0.0574 - val_mae: 0.1409 - val_rmse: 0.1807 - val_smape: 0.3741

Epoch 18/32

3832/3832 - 71s - 19ms/step - ia: 0.8538 - loss: 0.0836 - mae: 0.1813 - rmse: 0.2493 - smape: 0.4266 - val_ia: 0.5465 - val_loss: 0.0559 - val_mae: 0.1379 - val_rmse: 0.1762 - val_smape: 0.3615

Epoch 19/32

3832/3832 - 70s - 18ms/step - ia: 0.8540 - loss: 0.0831 - mae: 0.1815 - rmse: 0.2492 - smape: 0.4257 - val_ia: 0.5292 - val_loss: 0.0557 - val_mae: 0.1413 - val_rmse: 0.1798 - val_smape: 0.3715

Epoch 20/32

3832/3832 - 72s - 19ms/step - ia: 0.8558 - loss: 0.0791 - mae: 0.1788 - rmse: 0.2444 - smape: 0.4236 - val_ia: 0.5459 - val_loss: 0.0582 - val_mae: 0.1391 - val_rmse: 0.1779 - val_smape: 0.3521

Epoch 21/32

3832/3832 - 72s - 19ms/step - ia: 0.8556 - loss: 0.0816 - mae: 0.1797 - rmse: 0.2468 - smape: 0.4232 - val_ia: 0.5345 - val_loss: 0.0581 - val_mae: 0.1400 - val_rmse: 0.1796 - val_smape: 0.3660

Epoch 22/32

3832/3832 - 70s - 18ms/step - ia: 0.8573 - loss: 0.0813 - mae: 0.1783 - rmse: 0.2460 - smape: 0.4156 - val_ia: 0.5466 - val_loss: 0.0548 - val_mae: 0.1341 - val_rmse: 0.1739 - val_smape: 0.3553

Epoch 23/32

3832/3832 - 71s - 19ms/step - ia: 0.8577 - loss: 0.0804 - mae: 0.1781 - rmse: 0.2448 - smape: 0.4199 - val_ia: 0.5433 - val_loss: 0.0555 - val_mae: 0.1363 - val_rmse: 0.1757 - val_smape: 0.3578

Epoch 24/32

3832/3832 - 71s - 18ms/step - ia: 0.8557 - loss: 0.0789 - mae: 0.1774 - rmse: 0.2428 - smape: 0.4205 - val_ia: 0.5593 - val_loss: 0.0537 - val_mae: 0.1304 - val_rmse: 0.1705 - val_smape: 0.3513

Epoch 25/32

3832/3832 - 71s - 18ms/step - ia: 0.8572 - loss: 0.0793 - mae: 0.1769 - rmse: 0.2430 - smape: 0.4171 - val_ia: 0.5470 - val_loss: 0.0548 - val_mae: 0.1359 - val_rmse: 0.1754 - val_smape: 0.3623

Epoch 26/32

3832/3832 - 59s - 15ms/step - ia: 0.8590 - loss: 0.0815 - mae: 0.1776 - rmse: 0.2446 - smape: 0.4170 - val_ia: 0.5351 - val_loss: 0.0546 - val_mae: 0.1407 - val_rmse: 0.1790 - val_smape: 0.3683

Epoch 27/32

3832/3832 - 71s - 18ms/step - ia: 0.8591 - loss: 0.0793 - mae: 0.1765 - rmse: 0.2431 - smape: 0.4156 - val_ia: 0.5533 - val_loss: 0.0565 - val_mae: 0.1359 - val_rmse: 0.1750 - val_smape: 0.3501

Epoch 28/32

3832/3832 - 71s - 18ms/step - ia: 0.8600 - loss: 0.0781 - mae: 0.1744 - rmse: 0.2398 - smape: 0.4119 - val_ia: 0.5521 - val_loss: 0.0548 - val_mae: 0.1343 - val_rmse: 0.1733 - val_smape: 0.3543

Epoch 29/32

3832/3832 - 72s - 19ms/step - ia: 0.8574 - loss: 0.0777 - mae: 0.1758 - rmse: 0.2413 - smape: 0.4149 - val_ia: 0.5523 - val_loss: 0.0541 - val_mae: 0.1325 - val_rmse: 0.1719 - val_smape: 0.3473

Epoch 30/32

3832/3832 - 70s - 18ms/step - ia: 0.8597 - loss: 0.0786 - mae: 0.1758 - rmse: 0.2415 - smape: 0.4143 - val_ia: 0.5423 - val_loss: 0.0558 - val_mae: 0.1367 - val_rmse: 0.1768 - val_smape: 0.3640

Epoch 31/32

3832/3832 - 82s - 21ms/step - ia: 0.8598 - loss: 0.0768 - mae: 0.1737 - rmse: 0.2401 - smape: 0.4114 - val_ia: 0.5333 - val_loss: 0.0568 - val_mae: 0.1407 - val_rmse: 0.1796 - val_smape: 0.3673

Epoch 32/32

3832/3832 - 85s - 22ms/step - ia: 0.8596 - loss: 0.0772 - mae: 0.1741 - rmse: 0.2402 - smape: 0.4099 - val_ia: 0.5425 - val_loss: 0.0552 - val_mae: 0.1370 - val_rmse: 0.1757 - val_smape: 0.3604

Restoring model weights from the end of the best epoch: 24.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:52 2s/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

 98%|█████████▊| 49/50 [15:37:51<16:07, 967.04s/trial, best loss: 0.03663246931891314]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1916/1916 - 27s - 14ms/step - ia: 0.3192 - loss: 0.8271 - mae: 0.6569 - rmse: 0.8660 - smape: 1.3995 - val_ia: 0.2431 - val_loss: 0.6415 - val_mae: 0.5707 - val_rmse: 0.6331 - val_smape: 1.1722

Epoch 2/8

1916/1916 - 18s - 9ms/step - ia: 0.5152 - loss: 0.5941 - mae: 0.5312 - rmse: 0.7283 - smape: 1.0453 - val_ia: 0.2646 - val_loss: 0.4552 - val_mae: 0.4584 - val_rmse: 0.5232 - val_smape: 0.8696

Epoch 3/8

1916/1916 - 17s - 9ms/step - ia: 0.6012 - loss: 0.4979 - mae: 0.4791 - rmse: 0.6648 - smape: 0.9131 - val_ia: 0.2832 - val_loss: 0.3885 - val_mae: 0.4191 - val_rmse: 0.4839 - val_smape: 0.8010

Epoch 4/8

1916/1916 - 16s - 8ms/step - ia: 0.6285 - loss: 0.4515 - mae: 0.4541 - rmse: 0.6337 - smape: 0.8707 - val_ia: 0.3007 - val_loss: 0.3435 - val_mae: 0.3950 - val_rmse: 0.4591 - val_smape: 0.7715

Epoch 5/8

1916/1916 - 20s - 11ms/step - ia: 0.6448 - loss: 0.4177 - mae: 0.4388 - rmse: 0.6086 - smape: 0.8499 - val_ia: 0.3173 - val_loss: 0.3082 - val_mae: 0.3748 - val_rmse: 0.4386 - val_smape: 0.7479

Epoch 6/8

1916/1916 - 18s - 9ms/step - ia: 0.6608 - loss: 0.3861 - mae: 0.4210 - rmse: 0.5840 - smape: 0.8240 - val_ia: 0.3317 - val_loss: 0.2791 - val_mae: 0.3574 - val_rmse: 0.4204 - val_smape: 0.7261

Epoch 7/8

1916/1916 - 16s - 8ms/step - ia: 0.6685 - loss: 0.3685 - mae: 0.4109 - rmse: 0.5712 - smape: 0.8087 - val_ia: 0.3467 - val_loss: 0.2541 - val_mae: 0.3415 - val_rmse: 0.4047 - val_smape: 0.7048

Epoch 8/8

1916/1916 - 16s - 9ms/step - ia: 0.6780 - loss: 0.3505 - mae: 0.4013 - rmse: 0.5566 - smape: 0.7982 - val_ia: 0.3593 - val_loss: 0.2334 - val_mae: 0.3279 - val_rmse: 0.3907 - val_smape: 0.6873

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

100%|██████████| 50/50 [15:40:24<00:00, 1128.49s/trial, best loss: 0.03663246931891314]

In [23]:
print(best)

{'activation': 2, 'batch': 1, 'dropout': 0.30000000000000004, 'epochs': 2, 'layers': 1.0, 'learning_rate': 0.00045371747819692945, 'units': 4}