Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\Desktop\\pruebas_collab\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 1
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [15]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 12, 5)
Las dimensiones de testX son:  (10533, 12, 5)
Las dimensiones de valX son:  (5189, 12, 5)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 40s - 35ms/step - ia: 0.6594 - loss: 0.3594 - mae: 0.4662 - rmse: 0.5857 - smape: 0.8911 - val_ia: 0.4277 - val_loss: 0.2560 - val_mae: 0.4025 - val_rmse: 0.4669 - val_smape: 0.7994

Epoch 2/128

1147/1147 - 22s - 19ms/step - ia: 0.7632 - loss: 0.2125 - mae: 0.3565 - rmse: 0.4564 - smape: 0.6891 - val_ia: 0.4799 - val_loss: 0.2142 - val_mae: 0.3719 - val_rmse: 0.4261 - val_smape: 0.7629

Epoch 3/128

1147/1147 - 23s - 20ms/step - ia: 0.7990 - loss: 0.1601 - mae: 0.3080 - rmse: 0.3953 - smape: 0.6168 - val_ia: 0.5332 - val_loss: 0.1487 - val_mae: 0.3038 - val_rmse: 0.3528 - val_smape: 0.6886

Epoch 4/128

1147/1147 - 19s - 17ms/step - ia: 0.8199 - loss: 0.1334 - mae: 0.2784 - rmse: 0.3608 - smape: 0.5656 - val_ia: 0.5693 - val_loss: 0.1143 - val_mae: 0.2638 - val_rmse: 0.3089 - val_smape: 0.6273

Epoch 5/128

1147/1147 - 29s - 25ms/step - ia: 0.8337 - loss: 0.1180 - mae: 0.2583 - rmse: 0.3389 - smape: 0.5211 - val_ia: 0.5937 - val_loss: 0.0948 - val_mae: 0.2437 - val_rmse: 0.2829 - val_smape: 0.5876

Epoch 6/128

1147/1147 - 24s - 21ms/step - ia: 0.8450 - loss: 0.1049 - mae: 0.2416 - rmse: 0.3198 - smape: 0.4904 - val_ia: 0.6189 - val_loss: 0.0775 - val_mae: 0.2211 - val_rmse: 0.2556 - val_smape: 0.5317

Epoch 7/128

1147/1147 - 20s - 17ms/step - ia: 0.8519 - loss: 0.0972 - mae: 0.2312 - rmse: 0.3077 - smape: 0.4687 - val_ia: 0.6420 - val_loss: 0.0636 - val_mae: 0.1998 - val_rmse: 0.2318 - val_smape: 0.4858

Epoch 8/128

1147/1147 - 24s - 21ms/step - ia: 0.8580 - loss: 0.0915 - mae: 0.2230 - rmse: 0.2981 - smape: 0.4494 - val_ia: 0.6269 - val_loss: 0.0677 - val_mae: 0.2095 - val_rmse: 0.2402 - val_smape: 0.4888

Epoch 9/128

1147/1147 - 22s - 19ms/step - ia: 0.8611 - loss: 0.0874 - mae: 0.2175 - rmse: 0.2913 - smape: 0.4400 - val_ia: 0.6580 - val_loss: 0.0550 - val_mae: 0.1855 - val_rmse: 0.2160 - val_smape: 0.4469

Epoch 10/128

1147/1147 - 22s - 19ms/step - ia: 0.8627 - loss: 0.0864 - mae: 0.2152 - rmse: 0.2897 - smape: 0.4334 - val_ia: 0.6454 - val_loss: 0.0594 - val_mae: 0.1951 - val_rmse: 0.2247 - val_smape: 0.4579

Epoch 11/128

1147/1147 - 23s - 20ms/step - ia: 0.8660 - loss: 0.0820 - mae: 0.2099 - rmse: 0.2821 - smape: 0.4247 - val_ia: 0.6413 - val_loss: 0.0595 - val_mae: 0.1977 - val_rmse: 0.2255 - val_smape: 0.4514

Epoch 12/128

1147/1147 - 45s - 39ms/step - ia: 0.8681 - loss: 0.0810 - mae: 0.2072 - rmse: 0.2803 - smape: 0.4166 - val_ia: 0.6319 - val_loss: 0.0635 - val_mae: 0.2058 - val_rmse: 0.2326 - val_smape: 0.4520

Epoch 13/128

1147/1147 - 25s - 22ms/step - ia: 0.8702 - loss: 0.0783 - mae: 0.2042 - rmse: 0.2753 - smape: 0.4101 - val_ia: 0.6919 - val_loss: 0.0430 - val_mae: 0.1634 - val_rmse: 0.1899 - val_smape: 0.3934

Epoch 14/128

1147/1147 - 24s - 21ms/step - ia: 0.8692 - loss: 0.0793 - mae: 0.2051 - rmse: 0.2770 - smape: 0.4105 - val_ia: 0.6817 - val_loss: 0.0441 - val_mae: 0.1688 - val_rmse: 0.1938 - val_smape: 0.3998

Epoch 15/128

1147/1147 - 27s - 24ms/step - ia: 0.8711 - loss: 0.0781 - mae: 0.2027 - rmse: 0.2747 - smape: 0.4077 - val_ia: 0.6625 - val_loss: 0.0521 - val_mae: 0.1833 - val_rmse: 0.2095 - val_smape: 0.4187

Epoch 16/128

1147/1147 - 21s - 19ms/step - ia: 0.8718 - loss: 0.0772 - mae: 0.2013 - rmse: 0.2736 - smape: 0.4010 - val_ia: 0.6789 - val_loss: 0.0454 - val_mae: 0.1713 - val_rmse: 0.1953 - val_smape: 0.3937

Epoch 17/128

1147/1147 - 23s - 20ms/step - ia: 0.8730 - loss: 0.0764 - mae: 0.1996 - rmse: 0.2713 - smape: 0.3985 - val_ia: 0.6967 - val_loss: 0.0405 - val_mae: 0.1596 - val_rmse: 0.1841 - val_smape: 0.3749

Epoch 18/128

1147/1147 - 22s - 19ms/step - ia: 0.8746 - loss: 0.0744 - mae: 0.1972 - rmse: 0.2681 - smape: 0.3925 - val_ia: 0.7163 - val_loss: 0.0347 - val_mae: 0.1468 - val_rmse: 0.1697 - val_smape: 0.3600

Epoch 19/128

1147/1147 - 25s - 22ms/step - ia: 0.8743 - loss: 0.0748 - mae: 0.1975 - rmse: 0.2691 - smape: 0.3884 - val_ia: 0.6916 - val_loss: 0.0419 - val_mae: 0.1635 - val_rmse: 0.1868 - val_smape: 0.3789

Epoch 20/128

1147/1147 - 23s - 20ms/step - ia: 0.8758 - loss: 0.0734 - mae: 0.1957 - rmse: 0.2664 - smape: 0.3851 - val_ia: 0.7063 - val_loss: 0.0371 - val_mae: 0.1528 - val_rmse: 0.1757 - val_smape: 0.3578

Epoch 21/128

1147/1147 - 20s - 17ms/step - ia: 0.8770 - loss: 0.0721 - mae: 0.1938 - rmse: 0.2638 - smape: 0.3825 - val_ia: 0.6736 - val_loss: 0.0470 - val_mae: 0.1754 - val_rmse: 0.1976 - val_smape: 0.3852

Epoch 22/128

1147/1147 - 23s - 20ms/step - ia: 0.8770 - loss: 0.0723 - mae: 0.1938 - rmse: 0.2643 - smape: 0.3815 - val_ia: 0.7201 - val_loss: 0.0352 - val_mae: 0.1459 - val_rmse: 0.1696 - val_smape: 0.3451

Epoch 23/128

1147/1147 - 24s - 21ms/step - ia: 0.8769 - loss: 0.0724 - mae: 0.1938 - rmse: 0.2643 - smape: 0.3797 - val_ia: 0.6632 - val_loss: 0.0500 - val_mae: 0.1821 - val_rmse: 0.2050 - val_smape: 0.3941

Epoch 24/128

1147/1147 - 41s - 35ms/step - ia: 0.8782 - loss: 0.0715 - mae: 0.1920 - rmse: 0.2626 - smape: 0.3781 - val_ia: 0.6852 - val_loss: 0.0427 - val_mae: 0.1678 - val_rmse: 0.1878 - val_smape: 0.3817

Epoch 25/128

1147/1147 - 23s - 20ms/step - ia: 0.8783 - loss: 0.0714 - mae: 0.1920 - rmse: 0.2626 - smape: 0.3771 - val_ia: 0.7234 - val_loss: 0.0321 - val_mae: 0.1419 - val_rmse: 0.1632 - val_smape: 0.3375

Epoch 26/128

1147/1147 - 23s - 20ms/step - ia: 0.8779 - loss: 0.0724 - mae: 0.1920 - rmse: 0.2643 - smape: 0.3752 - val_ia: 0.6953 - val_loss: 0.0399 - val_mae: 0.1584 - val_rmse: 0.1812 - val_smape: 0.3427

Epoch 27/128

1147/1147 - 22s - 20ms/step - ia: 0.8797 - loss: 0.0701 - mae: 0.1894 - rmse: 0.2600 - smape: 0.3719 - val_ia: 0.6876 - val_loss: 0.0415 - val_mae: 0.1636 - val_rmse: 0.1858 - val_smape: 0.3562

Epoch 28/128

1147/1147 - 22s - 19ms/step - ia: 0.8790 - loss: 0.0714 - mae: 0.1905 - rmse: 0.2624 - smape: 0.3719 - val_ia: 0.7092 - val_loss: 0.0366 - val_mae: 0.1505 - val_rmse: 0.1729 - val_smape: 0.3386

Epoch 29/128

1147/1147 - 26s - 23ms/step - ia: 0.8796 - loss: 0.0704 - mae: 0.1899 - rmse: 0.2606 - smape: 0.3675 - val_ia: 0.6943 - val_loss: 0.0410 - val_mae: 0.1600 - val_rmse: 0.1829 - val_smape: 0.3306

Epoch 30/128

1147/1147 - 39s - 34ms/step - ia: 0.8794 - loss: 0.0702 - mae: 0.1895 - rmse: 0.2603 - smape: 0.3680 - val_ia: 0.7200 - val_loss: 0.0339 - val_mae: 0.1440 - val_rmse: 0.1657 - val_smape: 0.3175

Epoch 31/128

1147/1147 - 18s - 16ms/step - ia: 0.8805 - loss: 0.0695 - mae: 0.1883 - rmse: 0.2587 - smape: 0.3666 - val_ia: 0.6695 - val_loss: 0.0480 - val_mae: 0.1774 - val_rmse: 0.1994 - val_smape: 0.3696

Epoch 32/128

1147/1147 - 18s - 16ms/step - ia: 0.8821 - loss: 0.0674 - mae: 0.1856 - rmse: 0.2549 - smape: 0.3622 - val_ia: 0.6807 - val_loss: 0.0436 - val_mae: 0.1685 - val_rmse: 0.1900 - val_smape: 0.3486

Epoch 33/128

1147/1147 - 17s - 15ms/step - ia: 0.8799 - loss: 0.0699 - mae: 0.1893 - rmse: 0.2600 - smape: 0.3658 - val_ia: 0.7005 - val_loss: 0.0379 - val_mae: 0.1546 - val_rmse: 0.1759 - val_smape: 0.3225

Epoch 34/128

1147/1147 - 17s - 15ms/step - ia: 0.8819 - loss: 0.0676 - mae: 0.1861 - rmse: 0.2554 - smape: 0.3629 - val_ia: 0.7049 - val_loss: 0.0365 - val_mae: 0.1523 - val_rmse: 0.1737 - val_smape: 0.3342

Epoch 35/128

1147/1147 - 19s - 17ms/step - ia: 0.8814 - loss: 0.0682 - mae: 0.1868 - rmse: 0.2565 - smape: 0.3622 - val_ia: 0.6886 - val_loss: 0.0408 - val_mae: 0.1617 - val_rmse: 0.1831 - val_smape: 0.3228

Epoch 36/128

1147/1147 - 16s - 14ms/step - ia: 0.8815 - loss: 0.0687 - mae: 0.1866 - rmse: 0.2574 - smape: 0.3607 - val_ia: 0.7088 - val_loss: 0.0352 - val_mae: 0.1485 - val_rmse: 0.1695 - val_smape: 0.3134

Epoch 37/128

1147/1147 - 18s - 16ms/step - ia: 0.8826 - loss: 0.0665 - mae: 0.1848 - rmse: 0.2537 - smape: 0.3582 - val_ia: 0.7051 - val_loss: 0.0357 - val_mae: 0.1509 - val_rmse: 0.1715 - val_smape: 0.3249

Epoch 38/128

1147/1147 - 20s - 17ms/step - ia: 0.8823 - loss: 0.0678 - mae: 0.1856 - rmse: 0.2556 - smape: 0.3593 - val_ia: 0.6926 - val_loss: 0.0394 - val_mae: 0.1591 - val_rmse: 0.1801 - val_smape: 0.3236

Epoch 39/128

1147/1147 - 17s - 15ms/step - ia: 0.8838 - loss: 0.0659 - mae: 0.1834 - rmse: 0.2519 - smape: 0.3542 - val_ia: 0.6951 - val_loss: 0.0400 - val_mae: 0.1591 - val_rmse: 0.1801 - val_smape: 0.3291

Epoch 40/128

1147/1147 - 23s - 20ms/step - ia: 0.8824 - loss: 0.0675 - mae: 0.1857 - rmse: 0.2555 - smape: 0.3568 - val_ia: 0.6894 - val_loss: 0.0422 - val_mae: 0.1630 - val_rmse: 0.1848 - val_smape: 0.3294

Epoch 40: early stopping

Restoring model weights from the end of the best epoch: 25.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9:28 4s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step

  2%|▏         | 1/50 [16:03<13:06:45, 963.38s/trial, best loss: 0.06497607765942928]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 69s - 478ms/step - ia: 0.6996 - loss: 0.2771 - mae: 0.3784 - rmse: 0.4743 - smape: 0.8071 - val_ia: 0.8390 - val_loss: 0.0796 - val_mae: 0.2120 - val_rmse: 0.2773 - val_smape: 0.5331

Epoch 2/16

144/144 - 27s - 185ms/step - ia: 0.9127 - loss: 0.0386 - mae: 0.1423 - rmse: 0.1930 - smape: 0.3824 - val_ia: 0.8619 - val_loss: 0.0516 - val_mae: 0.1812 - val_rmse: 0.2275 - val_smape: 0.4582

Epoch 3/16

144/144 - 25s - 172ms/step - ia: 0.9405 - loss: 0.0184 - mae: 0.0979 - rmse: 0.1340 - smape: 0.2785 - val_ia: 0.8888 - val_loss: 0.0336 - val_mae: 0.1490 - val_rmse: 0.1811 - val_smape: 0.4142

Epoch 4/16

144/144 - 26s - 180ms/step - ia: 0.9501 - loss: 0.0129 - mae: 0.0825 - rmse: 0.1111 - smape: 0.2422 - val_ia: 0.9433 - val_loss: 0.0116 - val_mae: 0.0773 - val_rmse: 0.1053 - val_smape: 0.2384

Epoch 5/16

144/144 - 26s - 181ms/step - ia: 0.9571 - loss: 0.0097 - mae: 0.0710 - rmse: 0.0958 - smape: 0.2171 - val_ia: 0.9364 - val_loss: 0.0116 - val_mae: 0.0860 - val_rmse: 0.1064 - val_smape: 0.2243

Epoch 6/16

144/144 - 41s - 287ms/step - ia: 0.9636 - loss: 0.0072 - mae: 0.0601 - rmse: 0.0830 - smape: 0.1931 - val_ia: 0.9520 - val_loss: 0.0068 - val_mae: 0.0611 - val_rmse: 0.0822 - val_smape: 0.1830

Epoch 7/16

144/144 - 23s - 157ms/step - ia: 0.9648 - loss: 0.0066 - mae: 0.0580 - rmse: 0.0793 - smape: 0.1888 - val_ia: 0.9616 - val_loss: 0.0050 - val_mae: 0.0509 - val_rmse: 0.0684 - val_smape: 0.1574

Epoch 8/16

144/144 - 22s - 156ms/step - ia: 0.9690 - loss: 0.0054 - mae: 0.0513 - rmse: 0.0713 - smape: 0.1706 - val_ia: 0.9612 - val_loss: 0.0051 - val_mae: 0.0519 - val_rmse: 0.0703 - val_smape: 0.1749

Epoch 9/16

144/144 - 18s - 122ms/step - ia: 0.9665 - loss: 0.0060 - mae: 0.0553 - rmse: 0.0748 - smape: 0.1818 - val_ia: 0.9616 - val_loss: 0.0052 - val_mae: 0.0521 - val_rmse: 0.0704 - val_smape: 0.1805

Epoch 10/16

144/144 - 19s - 130ms/step - ia: 0.9726 - loss: 0.0044 - mae: 0.0453 - rmse: 0.0641 - smape: 0.1571 - val_ia: 0.9667 - val_loss: 0.0037 - val_mae: 0.0439 - val_rmse: 0.0601 - val_smape: 0.1377

Epoch 11/16

144/144 - 16s - 112ms/step - ia: 0.9714 - loss: 0.0045 - mae: 0.0471 - rmse: 0.0655 - smape: 0.1605 - val_ia: 0.9569 - val_loss: 0.0056 - val_mae: 0.0585 - val_rmse: 0.0737 - val_smape: 0.1782

Epoch 12/16

144/144 - 21s - 147ms/step - ia: 0.9723 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0640 - smape: 0.1575 - val_ia: 0.9679 - val_loss: 0.0033 - val_mae: 0.0420 - val_rmse: 0.0570 - val_smape: 0.1338

Epoch 13/16

144/144 - 41s - 286ms/step - ia: 0.9742 - loss: 0.0039 - mae: 0.0426 - rmse: 0.0601 - smape: 0.1485 - val_ia: 0.9525 - val_loss: 0.0064 - val_mae: 0.0648 - val_rmse: 0.0783 - val_smape: 0.2026

Epoch 14/16

144/144 - 25s - 175ms/step - ia: 0.9743 - loss: 0.0038 - mae: 0.0425 - rmse: 0.0597 - smape: 0.1497 - val_ia: 0.9644 - val_loss: 0.0043 - val_mae: 0.0473 - val_rmse: 0.0636 - val_smape: 0.1594

Epoch 15/16

144/144 - 25s - 175ms/step - ia: 0.9746 - loss: 0.0037 - mae: 0.0419 - rmse: 0.0590 - smape: 0.1474 - val_ia: 0.9609 - val_loss: 0.0043 - val_mae: 0.0509 - val_rmse: 0.0653 - val_smape: 0.1567

Epoch 16/16

144/144 - 26s - 180ms/step - ia: 0.9743 - loss: 0.0038 - mae: 0.0426 - rmse: 0.0597 - smape: 0.1484 - val_ia: 0.9678 - val_loss: 0.0035 - val_mae: 0.0427 - val_rmse: 0.0575 - val_smape: 0.1376

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 20:38 8s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step

  4%|▍         | 2/50 [23:48<8:56:12, 670.27s/trial, best loss: 0.005043283809393472]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

574/574 - 115s - 201ms/step - ia: 0.1131 - loss: 0.9874 - mae: 0.8228 - rmse: 0.9917 - smape: 1.8431 - val_ia: 0.2753 - val_loss: 0.8408 - val_mae: 0.7626 - val_rmse: 0.8839 - val_smape: 1.8222

Epoch 2/8

574/574 - 25s - 43ms/step - ia: 0.1202 - loss: 0.9788 - mae: 0.8192 - rmse: 0.9870 - smape: 1.8369 - val_ia: 0.2762 - val_loss: 0.8371 - val_mae: 0.7607 - val_rmse: 0.8819 - val_smape: 1.8124

Epoch 3/8

574/574 - 9s - 16ms/step - ia: 0.1209 - loss: 0.9715 - mae: 0.8160 - rmse: 0.9837 - smape: 1.8299 - val_ia: 0.2771 - val_loss: 0.8333 - val_mae: 0.7588 - val_rmse: 0.8799 - val_smape: 1.8026

Epoch 4/8

574/574 - 10s - 17ms/step - ia: 0.1262 - loss: 0.9648 - mae: 0.8131 - rmse: 0.9798 - smape: 1.8203 - val_ia: 0.2781 - val_loss: 0.8292 - val_mae: 0.7568 - val_rmse: 0.8778 - val_smape: 1.7924

Epoch 5/8

574/574 - 8s - 15ms/step - ia: 0.1229 - loss: 0.9576 - mae: 0.8100 - rmse: 0.9761 - smape: 1.8109 - val_ia: 0.2793 - val_loss: 0.8249 - val_mae: 0.7546 - val_rmse: 0.8755 - val_smape: 1.7819

Epoch 6/8

574/574 - 8s - 13ms/step - ia: 0.1342 - loss: 0.9496 - mae: 0.8066 - rmse: 0.9722 - smape: 1.8019 - val_ia: 0.2806 - val_loss: 0.8201 - val_mae: 0.7522 - val_rmse: 0.8730 - val_smape: 1.7712

Epoch 7/8

574/574 - 8s - 14ms/step - ia: 0.1369 - loss: 0.9432 - mae: 0.8035 - rmse: 0.9686 - smape: 1.7910 - val_ia: 0.2820 - val_loss: 0.8150 - val_mae: 0.7497 - val_rmse: 0.8703 - val_smape: 1.7599

Epoch 8/8

574/574 - 8s - 14ms/step - ia: 0.1425 - loss: 0.9352 - mae: 0.7999 - rmse: 0.9647 - smape: 1.7796 - val_ia: 0.2835 - val_loss: 0.8094 - val_mae: 0.7469 - val_rmse: 0.8673 - val_smape: 1.7485

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:38 980ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

  6%|▌         | 3/50 [27:04<5:55:21, 453.65s/trial, best loss: 0.005043283809393472]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 40s - 139ms/step - ia: 0.1834 - loss: 0.8602 - mae: 0.7675 - rmse: 0.9252 - smape: 1.6378 - val_ia: 0.3382 - val_loss: 0.6650 - val_mae: 0.6777 - val_rmse: 0.8087 - val_smape: 1.4928

Epoch 2/32

287/287 - 8s - 27ms/step - ia: 0.4229 - loss: 0.5832 - mae: 0.6281 - rmse: 0.7607 - smape: 1.2361 - val_ia: 0.5005 - val_loss: 0.4518 - val_mae: 0.5501 - val_rmse: 0.6664 - val_smape: 1.1137

Epoch 3/32

287/287 - 8s - 27ms/step - ia: 0.6243 - loss: 0.3695 - mae: 0.4916 - rmse: 0.6061 - smape: 0.9403 - val_ia: 0.6421 - val_loss: 0.3341 - val_mae: 0.4492 - val_rmse: 0.5735 - val_smape: 0.8828

Epoch 4/32

287/287 - 8s - 27ms/step - ia: 0.7103 - loss: 0.2918 - mae: 0.4266 - rmse: 0.5391 - smape: 0.8163 - val_ia: 0.6753 - val_loss: 0.3114 - val_mae: 0.4320 - val_rmse: 0.5529 - val_smape: 0.8349

Epoch 5/32

287/287 - 8s - 26ms/step - ia: 0.7333 - loss: 0.2697 - mae: 0.4064 - rmse: 0.5183 - smape: 0.7773 - val_ia: 0.6826 - val_loss: 0.3043 - val_mae: 0.4281 - val_rmse: 0.5448 - val_smape: 0.8211

Epoch 6/32

287/287 - 8s - 27ms/step - ia: 0.7432 - loss: 0.2538 - mae: 0.3937 - rmse: 0.5028 - smape: 0.7566 - val_ia: 0.6845 - val_loss: 0.3018 - val_mae: 0.4288 - val_rmse: 0.5407 - val_smape: 0.8149

Epoch 7/32

287/287 - 12s - 40ms/step - ia: 0.7528 - loss: 0.2387 - mae: 0.3805 - rmse: 0.4875 - smape: 0.7364 - val_ia: 0.6851 - val_loss: 0.2989 - val_mae: 0.4297 - val_rmse: 0.5369 - val_smape: 0.8105

Epoch 8/32

287/287 - 9s - 33ms/step - ia: 0.7608 - loss: 0.2263 - mae: 0.3696 - rmse: 0.4746 - smape: 0.7201 - val_ia: 0.6837 - val_loss: 0.2969 - val_mae: 0.4328 - val_rmse: 0.5342 - val_smape: 0.8093

Epoch 9/32

287/287 - 10s - 33ms/step - ia: 0.7687 - loss: 0.2131 - mae: 0.3587 - rmse: 0.4605 - smape: 0.7046 - val_ia: 0.6814 - val_loss: 0.2935 - val_mae: 0.4362 - val_rmse: 0.5309 - val_smape: 0.8130

Epoch 10/32

287/287 - 10s - 34ms/step - ia: 0.7750 - loss: 0.2019 - mae: 0.3490 - rmse: 0.4484 - smape: 0.6894 - val_ia: 0.6792 - val_loss: 0.2879 - val_mae: 0.4389 - val_rmse: 0.5260 - val_smape: 0.8196

Epoch 11/32

287/287 - 9s - 33ms/step - ia: 0.7808 - loss: 0.1933 - mae: 0.3414 - rmse: 0.4386 - smape: 0.6760 - val_ia: 0.6808 - val_loss: 0.2777 - val_mae: 0.4366 - val_rmse: 0.5171 - val_smape: 0.8213

Epoch 12/32

287/287 - 9s - 32ms/step - ia: 0.7884 - loss: 0.1815 - mae: 0.3304 - rmse: 0.4249 - smape: 0.6592 - val_ia: 0.6857 - val_loss: 0.2646 - val_mae: 0.4297 - val_rmse: 0.5053 - val_smape: 0.8181

Epoch 13/32

287/287 - 9s - 30ms/step - ia: 0.7953 - loss: 0.1712 - mae: 0.3202 - rmse: 0.4128 - smape: 0.6434 - val_ia: 0.6950 - val_loss: 0.2478 - val_mae: 0.4170 - val_rmse: 0.4895 - val_smape: 0.8056

Epoch 14/32

287/287 - 9s - 30ms/step - ia: 0.8012 - loss: 0.1622 - mae: 0.3119 - rmse: 0.4015 - smape: 0.6307 - val_ia: 0.7069 - val_loss: 0.2291 - val_mae: 0.4003 - val_rmse: 0.4711 - val_smape: 0.7869

Epoch 15/32

287/287 - 8s - 30ms/step - ia: 0.8090 - loss: 0.1513 - mae: 0.3007 - rmse: 0.3879 - smape: 0.6144 - val_ia: 0.7265 - val_loss: 0.2047 - val_mae: 0.3746 - val_rmse: 0.4460 - val_smape: 0.7543

Epoch 16/32

287/287 - 8s - 29ms/step - ia: 0.8154 - loss: 0.1427 - mae: 0.2916 - rmse: 0.3766 - smape: 0.6010 - val_ia: 0.7363 - val_loss: 0.1880 - val_mae: 0.3583 - val_rmse: 0.4275 - val_smape: 0.7367

Epoch 17/32

287/287 - 9s - 32ms/step - ia: 0.8219 - loss: 0.1334 - mae: 0.2820 - rmse: 0.3641 - smape: 0.5848 - val_ia: 0.7521 - val_loss: 0.1691 - val_mae: 0.3364 - val_rmse: 0.4056 - val_smape: 0.7106

Epoch 18/32

287/287 - 9s - 33ms/step - ia: 0.8276 - loss: 0.1264 - mae: 0.2739 - rmse: 0.3545 - smape: 0.5730 - val_ia: 0.7685 - val_loss: 0.1508 - val_mae: 0.3143 - val_rmse: 0.3833 - val_smape: 0.6852

Epoch 19/32

287/287 - 11s - 37ms/step - ia: 0.8334 - loss: 0.1181 - mae: 0.2654 - rmse: 0.3425 - smape: 0.5609 - val_ia: 0.7823 - val_loss: 0.1353 - val_mae: 0.2956 - val_rmse: 0.3633 - val_smape: 0.6637

Epoch 20/32

287/287 - 10s - 36ms/step - ia: 0.8399 - loss: 0.1101 - mae: 0.2557 - rmse: 0.3308 - smape: 0.5448 - val_ia: 0.7916 - val_loss: 0.1243 - val_mae: 0.2819 - val_rmse: 0.3483 - val_smape: 0.6478

Epoch 21/32

287/287 - 10s - 36ms/step - ia: 0.8434 - loss: 0.1058 - mae: 0.2503 - rmse: 0.3242 - smape: 0.5387 - val_ia: 0.8006 - val_loss: 0.1143 - val_mae: 0.2683 - val_rmse: 0.3337 - val_smape: 0.6314

Epoch 22/32

287/287 - 10s - 35ms/step - ia: 0.8476 - loss: 0.1011 - mae: 0.2442 - rmse: 0.3170 - smape: 0.5276 - val_ia: 0.8077 - val_loss: 0.1068 - val_mae: 0.2582 - val_rmse: 0.3225 - val_smape: 0.6197

Epoch 23/32

287/287 - 8s - 29ms/step - ia: 0.8504 - loss: 0.0973 - mae: 0.2398 - rmse: 0.3109 - smape: 0.5212 - val_ia: 0.8148 - val_loss: 0.0995 - val_mae: 0.2479 - val_rmse: 0.3111 - val_smape: 0.6072

Epoch 24/32

287/287 - 9s - 32ms/step - ia: 0.8546 - loss: 0.0930 - mae: 0.2337 - rmse: 0.3040 - smape: 0.5114 - val_ia: 0.8192 - val_loss: 0.0948 - val_mae: 0.2408 - val_rmse: 0.3034 - val_smape: 0.5973

Epoch 25/32

287/287 - 9s - 33ms/step - ia: 0.8562 - loss: 0.0910 - mae: 0.2310 - rmse: 0.3005 - smape: 0.5062 - val_ia: 0.8250 - val_loss: 0.0894 - val_mae: 0.2336 - val_rmse: 0.2948 - val_smape: 0.5882

Epoch 26/32

287/287 - 10s - 36ms/step - ia: 0.8601 - loss: 0.0864 - mae: 0.2252 - rmse: 0.2930 - smape: 0.4971 - val_ia: 0.8276 - val_loss: 0.0869 - val_mae: 0.2303 - val_rmse: 0.2904 - val_smape: 0.5832

Epoch 27/32

287/287 - 10s - 35ms/step - ia: 0.8611 - loss: 0.0851 - mae: 0.2237 - rmse: 0.2909 - smape: 0.4922 - val_ia: 0.8314 - val_loss: 0.0833 - val_mae: 0.2248 - val_rmse: 0.2845 - val_smape: 0.5743

Epoch 28/32

287/287 - 10s - 36ms/step - ia: 0.8635 - loss: 0.0831 - mae: 0.2201 - rmse: 0.2872 - smape: 0.4885 - val_ia: 0.8338 - val_loss: 0.0809 - val_mae: 0.2210 - val_rmse: 0.2800 - val_smape: 0.5679

Epoch 29/32

287/287 - 10s - 36ms/step - ia: 0.8657 - loss: 0.0803 - mae: 0.2163 - rmse: 0.2825 - smape: 0.4815 - val_ia: 0.8354 - val_loss: 0.0792 - val_mae: 0.2184 - val_rmse: 0.2769 - val_smape: 0.5626

Epoch 30/32

287/287 - 10s - 36ms/step - ia: 0.8675 - loss: 0.0787 - mae: 0.2135 - rmse: 0.2798 - smape: 0.4758 - val_ia: 0.8391 - val_loss: 0.0760 - val_mae: 0.2139 - val_rmse: 0.2713 - val_smape: 0.5552

Epoch 31/32

287/287 - 10s - 34ms/step - ia: 0.8694 - loss: 0.0771 - mae: 0.2106 - rmse: 0.2766 - smape: 0.4688 - val_ia: 0.8418 - val_loss: 0.0736 - val_mae: 0.2099 - val_rmse: 0.2670 - val_smape: 0.5465

Epoch 32/32

287/287 - 9s - 30ms/step - ia: 0.8713 - loss: 0.0746 - mae: 0.2075 - rmse: 0.2723 - smape: 0.4677 - val_ia: 0.8443 - val_loss: 0.0715 - val_mae: 0.2067 - val_rmse: 0.2630 - val_smape: 0.5403

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:20 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

  8%|▊         | 4/50 [32:36<5:11:07, 405.82s/trial, best loss: 0.005043283809393472]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4586/4586 - 54s - 12ms/step - ia: 0.2343 - loss: 1.0382 - mae: 0.8437 - rmse: 0.9983 - smape: 1.6042 - val_ia: 0.1396 - val_loss: 0.8606 - val_mae: 0.7724 - val_rmse: 0.7897 - val_smape: 1.7926

Epoch 2/64

4586/4586 - 52s - 11ms/step - ia: 0.2385 - loss: 1.0194 - mae: 0.8365 - rmse: 0.9886 - smape: 1.6040 - val_ia: 0.1401 - val_loss: 0.8400 - val_mae: 0.7628 - val_rmse: 0.7800 - val_smape: 1.8307

Epoch 3/64

4586/4586 - 47s - 10ms/step - ia: 0.2462 - loss: 0.9964 - mae: 0.8276 - rmse: 0.9784 - smape: 1.5980 - val_ia: 0.1414 - val_loss: 0.8205 - val_mae: 0.7537 - val_rmse: 0.7708 - val_smape: 1.8226

Epoch 4/64

4586/4586 - 45s - 10ms/step - ia: 0.2491 - loss: 0.9740 - mae: 0.8172 - rmse: 0.9675 - smape: 1.5795 - val_ia: 0.1430 - val_loss: 0.7984 - val_mae: 0.7433 - val_rmse: 0.7602 - val_smape: 1.7869

Epoch 5/64

4586/4586 - 45s - 10ms/step - ia: 0.2608 - loss: 0.9462 - mae: 0.8055 - rmse: 0.9529 - smape: 1.5590 - val_ia: 0.1450 - val_loss: 0.7725 - val_mae: 0.7309 - val_rmse: 0.7476 - val_smape: 1.7304

Epoch 6/64

4586/4586 - 46s - 10ms/step - ia: 0.2775 - loss: 0.9101 - mae: 0.7885 - rmse: 0.9339 - smape: 1.5263 - val_ia: 0.1475 - val_loss: 0.7410 - val_mae: 0.7155 - val_rmse: 0.7320 - val_smape: 1.6628

Epoch 7/64

4586/4586 - 42s - 9ms/step - ia: 0.2926 - loss: 0.8659 - mae: 0.7686 - rmse: 0.9113 - smape: 1.4893 - val_ia: 0.1507 - val_loss: 0.7027 - val_mae: 0.6964 - val_rmse: 0.7125 - val_smape: 1.5840

Epoch 8/64

4586/4586 - 35s - 8ms/step - ia: 0.3138 - loss: 0.8214 - mae: 0.7467 - rmse: 0.8868 - smape: 1.4364 - val_ia: 0.1545 - val_loss: 0.6575 - val_mae: 0.6730 - val_rmse: 0.6888 - val_smape: 1.4941

Epoch 9/64

4586/4586 - 35s - 8ms/step - ia: 0.3409 - loss: 0.7667 - mae: 0.7208 - rmse: 0.8566 - smape: 1.3831 - val_ia: 0.1591 - val_loss: 0.6053 - val_mae: 0.6449 - val_rmse: 0.6601 - val_smape: 1.3964

Epoch 10/64

4586/4586 - 36s - 8ms/step - ia: 0.3775 - loss: 0.6995 - mae: 0.6876 - rmse: 0.8176 - smape: 1.3124 - val_ia: 0.1638 - val_loss: 0.5474 - val_mae: 0.6121 - val_rmse: 0.6268 - val_smape: 1.2893

Epoch 11/64

4586/4586 - 42s - 9ms/step - ia: 0.4167 - loss: 0.6342 - mae: 0.6510 - rmse: 0.7771 - smape: 1.2321 - val_ia: 0.1698 - val_loss: 0.4858 - val_mae: 0.5750 - val_rmse: 0.5892 - val_smape: 1.1802

Epoch 12/64

4586/4586 - 41s - 9ms/step - ia: 0.4630 - loss: 0.5631 - mae: 0.6102 - rmse: 0.7313 - smape: 1.1438 - val_ia: 0.1783 - val_loss: 0.4220 - val_mae: 0.5333 - val_rmse: 0.5474 - val_smape: 1.0699

Epoch 13/64

4586/4586 - 41s - 9ms/step - ia: 0.5108 - loss: 0.4961 - mae: 0.5687 - rmse: 0.6846 - smape: 1.0609 - val_ia: 0.1900 - val_loss: 0.3618 - val_mae: 0.4900 - val_rmse: 0.5043 - val_smape: 0.9660

Epoch 14/64

4586/4586 - 42s - 9ms/step - ia: 0.5588 - loss: 0.4304 - mae: 0.5266 - rmse: 0.6362 - smape: 0.9746 - val_ia: 0.2068 - val_loss: 0.3079 - val_mae: 0.4461 - val_rmse: 0.4615 - val_smape: 0.8719

Epoch 15/64

4586/4586 - 37s - 8ms/step - ia: 0.6071 - loss: 0.3733 - mae: 0.4864 - rmse: 0.5923 - smape: 0.9028 - val_ia: 0.2296 - val_loss: 0.2658 - val_mae: 0.4074 - val_rmse: 0.4241 - val_smape: 0.7955

Epoch 16/64

4586/4586 - 36s - 8ms/step - ia: 0.6432 - loss: 0.3284 - mae: 0.4543 - rmse: 0.5541 - smape: 0.8434 - val_ia: 0.2503 - val_loss: 0.2354 - val_mae: 0.3766 - val_rmse: 0.3947 - val_smape: 0.7399

Epoch 17/64

4586/4586 - 36s - 8ms/step - ia: 0.6711 - loss: 0.2987 - mae: 0.4302 - rmse: 0.5272 - smape: 0.8025 - val_ia: 0.2505 - val_loss: 0.2171 - val_mae: 0.3601 - val_rmse: 0.3790 - val_smape: 0.7092

Epoch 18/64

4586/4586 - 36s - 8ms/step - ia: 0.6892 - loss: 0.2807 - mae: 0.4161 - rmse: 0.5114 - smape: 0.7725 - val_ia: 0.2474 - val_loss: 0.2075 - val_mae: 0.3538 - val_rmse: 0.3730 - val_smape: 0.6946

Epoch 19/64

4586/4586 - 41s - 9ms/step - ia: 0.7045 - loss: 0.2653 - mae: 0.4041 - rmse: 0.4966 - smape: 0.7496 - val_ia: 0.2438 - val_loss: 0.2022 - val_mae: 0.3514 - val_rmse: 0.3707 - val_smape: 0.6874

Epoch 20/64

4586/4586 - 35s - 8ms/step - ia: 0.7128 - loss: 0.2571 - mae: 0.3975 - rmse: 0.4887 - smape: 0.7357 - val_ia: 0.2421 - val_loss: 0.1997 - val_mae: 0.3508 - val_rmse: 0.3702 - val_smape: 0.6834

Epoch 21/64

4586/4586 - 35s - 8ms/step - ia: 0.7172 - loss: 0.2525 - mae: 0.3941 - rmse: 0.4842 - smape: 0.7250 - val_ia: 0.2408 - val_loss: 0.1971 - val_mae: 0.3498 - val_rmse: 0.3692 - val_smape: 0.6807

Epoch 22/64

4586/4586 - 36s - 8ms/step - ia: 0.7245 - loss: 0.2428 - mae: 0.3867 - rmse: 0.4755 - smape: 0.7190 - val_ia: 0.2412 - val_loss: 0.1950 - val_mae: 0.3489 - val_rmse: 0.3683 - val_smape: 0.6785

Epoch 23/64

4586/4586 - 36s - 8ms/step - ia: 0.7291 - loss: 0.2389 - mae: 0.3835 - rmse: 0.4713 - smape: 0.7091 - val_ia: 0.2424 - val_loss: 0.1929 - val_mae: 0.3475 - val_rmse: 0.3668 - val_smape: 0.6764

Epoch 24/64

4586/4586 - 35s - 8ms/step - ia: 0.7309 - loss: 0.2367 - mae: 0.3811 - rmse: 0.4689 - smape: 0.7056 - val_ia: 0.2436 - val_loss: 0.1904 - val_mae: 0.3456 - val_rmse: 0.3648 - val_smape: 0.6743

Epoch 25/64

4586/4586 - 36s - 8ms/step - ia: 0.7346 - loss: 0.2291 - mae: 0.3751 - rmse: 0.4614 - smape: 0.6975 - val_ia: 0.2447 - val_loss: 0.1882 - val_mae: 0.3438 - val_rmse: 0.3629 - val_smape: 0.6720

Epoch 26/64

4586/4586 - 36s - 8ms/step - ia: 0.7377 - loss: 0.2251 - mae: 0.3715 - rmse: 0.4572 - smape: 0.6919 - val_ia: 0.2459 - val_loss: 0.1856 - val_mae: 0.3418 - val_rmse: 0.3607 - val_smape: 0.6696

Epoch 27/64

4586/4586 - 36s - 8ms/step - ia: 0.7391 - loss: 0.2228 - mae: 0.3703 - rmse: 0.4554 - smape: 0.6912 - val_ia: 0.2474 - val_loss: 0.1835 - val_mae: 0.3398 - val_rmse: 0.3585 - val_smape: 0.6674

Epoch 28/64

4586/4586 - 36s - 8ms/step - ia: 0.7433 - loss: 0.2177 - mae: 0.3645 - rmse: 0.4495 - smape: 0.6808 - val_ia: 0.2487 - val_loss: 0.1806 - val_mae: 0.3374 - val_rmse: 0.3560 - val_smape: 0.6651

Epoch 29/64

4586/4586 - 35s - 8ms/step - ia: 0.7453 - loss: 0.2143 - mae: 0.3616 - rmse: 0.4464 - smape: 0.6786 - val_ia: 0.2500 - val_loss: 0.1782 - val_mae: 0.3353 - val_rmse: 0.3537 - val_smape: 0.6629

Epoch 30/64

4586/4586 - 36s - 8ms/step - ia: 0.7462 - loss: 0.2120 - mae: 0.3598 - rmse: 0.4437 - smape: 0.6764 - val_ia: 0.2512 - val_loss: 0.1758 - val_mae: 0.3332 - val_rmse: 0.3514 - val_smape: 0.6608

Epoch 31/64

4586/4586 - 37s - 8ms/step - ia: 0.7491 - loss: 0.2095 - mae: 0.3573 - rmse: 0.4409 - smape: 0.6723 - val_ia: 0.2525 - val_loss: 0.1731 - val_mae: 0.3308 - val_rmse: 0.3489 - val_smape: 0.6586

Epoch 32/64

4586/4586 - 36s - 8ms/step - ia: 0.7531 - loss: 0.2031 - mae: 0.3525 - rmse: 0.4346 - smape: 0.6662 - val_ia: 0.2534 - val_loss: 0.1712 - val_mae: 0.3291 - val_rmse: 0.3470 - val_smape: 0.6565

Epoch 33/64

4586/4586 - 34s - 8ms/step - ia: 0.7540 - loss: 0.2005 - mae: 0.3493 - rmse: 0.4313 - smape: 0.6595 - val_ia: 0.2546 - val_loss: 0.1686 - val_mae: 0.3268 - val_rmse: 0.3446 - val_smape: 0.6543

Epoch 34/64

4586/4586 - 36s - 8ms/step - ia: 0.7562 - loss: 0.1977 - mae: 0.3472 - rmse: 0.4287 - smape: 0.6583 - val_ia: 0.2559 - val_loss: 0.1661 - val_mae: 0.3245 - val_rmse: 0.3421 - val_smape: 0.6522

Epoch 35/64

4586/4586 - 36s - 8ms/step - ia: 0.7574 - loss: 0.1946 - mae: 0.3445 - rmse: 0.4245 - smape: 0.6563 - val_ia: 0.2570 - val_loss: 0.1636 - val_mae: 0.3222 - val_rmse: 0.3397 - val_smape: 0.6500

Epoch 36/64

4586/4586 - 41s - 9ms/step - ia: 0.7596 - loss: 0.1922 - mae: 0.3418 - rmse: 0.4220 - smape: 0.6503 - val_ia: 0.2580 - val_loss: 0.1612 - val_mae: 0.3201 - val_rmse: 0.3373 - val_smape: 0.6478

Epoch 37/64

4586/4586 - 36s - 8ms/step - ia: 0.7637 - loss: 0.1859 - mae: 0.3364 - rmse: 0.4153 - smape: 0.6445 - val_ia: 0.2588 - val_loss: 0.1595 - val_mae: 0.3184 - val_rmse: 0.3355 - val_smape: 0.6462

Epoch 38/64

4586/4586 - 36s - 8ms/step - ia: 0.7640 - loss: 0.1857 - mae: 0.3350 - rmse: 0.4144 - smape: 0.6416 - val_ia: 0.2600 - val_loss: 0.1569 - val_mae: 0.3160 - val_rmse: 0.3330 - val_smape: 0.6439

Epoch 39/64

4586/4586 - 35s - 8ms/step - ia: 0.7668 - loss: 0.1815 - mae: 0.3303 - rmse: 0.4097 - smape: 0.6350 - val_ia: 0.2608 - val_loss: 0.1550 - val_mae: 0.3141 - val_rmse: 0.3309 - val_smape: 0.6419

Epoch 40/64

4586/4586 - 35s - 8ms/step - ia: 0.7660 - loss: 0.1829 - mae: 0.3331 - rmse: 0.4117 - smape: 0.6403 - val_ia: 0.2620 - val_loss: 0.1526 - val_mae: 0.3119 - val_rmse: 0.3285 - val_smape: 0.6397

Epoch 41/64

4586/4586 - 36s - 8ms/step - ia: 0.7713 - loss: 0.1765 - mae: 0.3264 - rmse: 0.4038 - smape: 0.6320 - val_ia: 0.2627 - val_loss: 0.1508 - val_mae: 0.3101 - val_rmse: 0.3265 - val_smape: 0.6377

Epoch 42/64

4586/4586 - 41s - 9ms/step - ia: 0.7707 - loss: 0.1755 - mae: 0.3262 - rmse: 0.4027 - smape: 0.6299 - val_ia: 0.2637 - val_loss: 0.1488 - val_mae: 0.3081 - val_rmse: 0.3244 - val_smape: 0.6358

Epoch 43/64

4586/4586 - 37s - 8ms/step - ia: 0.7737 - loss: 0.1731 - mae: 0.3233 - rmse: 0.4001 - smape: 0.6273 - val_ia: 0.2649 - val_loss: 0.1463 - val_mae: 0.3059 - val_rmse: 0.3221 - val_smape: 0.6335

Epoch 44/64

4586/4586 - 36s - 8ms/step - ia: 0.7748 - loss: 0.1709 - mae: 0.3224 - rmse: 0.3977 - smape: 0.6245 - val_ia: 0.2658 - val_loss: 0.1446 - val_mae: 0.3041 - val_rmse: 0.3202 - val_smape: 0.6318

Epoch 45/64

4586/4586 - 35s - 8ms/step - ia: 0.7769 - loss: 0.1680 - mae: 0.3177 - rmse: 0.3940 - smape: 0.6169 - val_ia: 0.2669 - val_loss: 0.1429 - val_mae: 0.3022 - val_rmse: 0.3181 - val_smape: 0.6300

Epoch 46/64

4586/4586 - 34s - 7ms/step - ia: 0.7769 - loss: 0.1681 - mae: 0.3185 - rmse: 0.3944 - smape: 0.6202 - val_ia: 0.2680 - val_loss: 0.1409 - val_mae: 0.3003 - val_rmse: 0.3160 - val_smape: 0.6279

Epoch 47/64

4586/4586 - 36s - 8ms/step - ia: 0.7779 - loss: 0.1646 - mae: 0.3155 - rmse: 0.3899 - smape: 0.6154 - val_ia: 0.2693 - val_loss: 0.1387 - val_mae: 0.2981 - val_rmse: 0.3137 - val_smape: 0.6258

Epoch 48/64

4586/4586 - 36s - 8ms/step - ia: 0.7793 - loss: 0.1645 - mae: 0.3147 - rmse: 0.3897 - smape: 0.6146 - val_ia: 0.2702 - val_loss: 0.1371 - val_mae: 0.2964 - val_rmse: 0.3119 - val_smape: 0.6239

Epoch 49/64

4586/4586 - 36s - 8ms/step - ia: 0.7820 - loss: 0.1609 - mae: 0.3115 - rmse: 0.3855 - smape: 0.6083 - val_ia: 0.2713 - val_loss: 0.1352 - val_mae: 0.2944 - val_rmse: 0.3098 - val_smape: 0.6219

Epoch 50/64

4586/4586 - 36s - 8ms/step - ia: 0.7834 - loss: 0.1601 - mae: 0.3100 - rmse: 0.3844 - smape: 0.6064 - val_ia: 0.2721 - val_loss: 0.1335 - val_mae: 0.2928 - val_rmse: 0.3080 - val_smape: 0.6200

Epoch 51/64

4586/4586 - 36s - 8ms/step - ia: 0.7838 - loss: 0.1592 - mae: 0.3088 - rmse: 0.3836 - smape: 0.6037 - val_ia: 0.2731 - val_loss: 0.1318 - val_mae: 0.2911 - val_rmse: 0.3062 - val_smape: 0.6181

Epoch 52/64

4586/4586 - 36s - 8ms/step - ia: 0.7859 - loss: 0.1563 - mae: 0.3065 - rmse: 0.3805 - smape: 0.6003 - val_ia: 0.2742 - val_loss: 0.1303 - val_mae: 0.2894 - val_rmse: 0.3044 - val_smape: 0.6162

Epoch 53/64

4586/4586 - 36s - 8ms/step - ia: 0.7880 - loss: 0.1547 - mae: 0.3050 - rmse: 0.3774 - smape: 0.6003 - val_ia: 0.2752 - val_loss: 0.1289 - val_mae: 0.2879 - val_rmse: 0.3027 - val_smape: 0.6144

Epoch 54/64

4586/4586 - 36s - 8ms/step - ia: 0.7892 - loss: 0.1511 - mae: 0.3019 - rmse: 0.3735 - smape: 0.5957 - val_ia: 0.2761 - val_loss: 0.1277 - val_mae: 0.2865 - val_rmse: 0.3012 - val_smape: 0.6127

Epoch 55/64

4586/4586 - 36s - 8ms/step - ia: 0.7901 - loss: 0.1510 - mae: 0.3008 - rmse: 0.3730 - smape: 0.5941 - val_ia: 0.2773 - val_loss: 0.1257 - val_mae: 0.2844 - val_rmse: 0.2990 - val_smape: 0.6106

Epoch 56/64

4586/4586 - 36s - 8ms/step - ia: 0.7899 - loss: 0.1498 - mae: 0.3001 - rmse: 0.3716 - smape: 0.5922 - val_ia: 0.2784 - val_loss: 0.1243 - val_mae: 0.2828 - val_rmse: 0.2973 - val_smape: 0.6088

Epoch 57/64

4586/4586 - 36s - 8ms/step - ia: 0.7913 - loss: 0.1486 - mae: 0.2987 - rmse: 0.3699 - smape: 0.5909 - val_ia: 0.2792 - val_loss: 0.1230 - val_mae: 0.2814 - val_rmse: 0.2957 - val_smape: 0.6071

Epoch 58/64

4586/4586 - 36s - 8ms/step - ia: 0.7936 - loss: 0.1467 - mae: 0.2961 - rmse: 0.3681 - smape: 0.5839 - val_ia: 0.2805 - val_loss: 0.1209 - val_mae: 0.2791 - val_rmse: 0.2934 - val_smape: 0.6049

Epoch 59/64

4586/4586 - 36s - 8ms/step - ia: 0.7932 - loss: 0.1459 - mae: 0.2962 - rmse: 0.3670 - smape: 0.5874 - val_ia: 0.2818 - val_loss: 0.1191 - val_mae: 0.2771 - val_rmse: 0.2913 - val_smape: 0.6028

Epoch 60/64

4586/4586 - 36s - 8ms/step - ia: 0.7951 - loss: 0.1443 - mae: 0.2943 - rmse: 0.3645 - smape: 0.5830 - val_ia: 0.2829 - val_loss: 0.1178 - val_mae: 0.2755 - val_rmse: 0.2896 - val_smape: 0.6008

Epoch 61/64

4586/4586 - 35s - 8ms/step - ia: 0.7967 - loss: 0.1402 - mae: 0.2904 - rmse: 0.3596 - smape: 0.5793 - val_ia: 0.2838 - val_loss: 0.1167 - val_mae: 0.2742 - val_rmse: 0.2881 - val_smape: 0.5990

Epoch 62/64

4586/4586 - 35s - 8ms/step - ia: 0.7956 - loss: 0.1429 - mae: 0.2928 - rmse: 0.3633 - smape: 0.5811 - val_ia: 0.2849 - val_loss: 0.1151 - val_mae: 0.2724 - val_rmse: 0.2863 - val_smape: 0.5970

Epoch 63/64

4586/4586 - 36s - 8ms/step - ia: 0.7980 - loss: 0.1396 - mae: 0.2896 - rmse: 0.3588 - smape: 0.5763 - val_ia: 0.2859 - val_loss: 0.1135 - val_mae: 0.2706 - val_rmse: 0.2844 - val_smape: 0.5949

Epoch 64/64

4586/4586 - 35s - 8ms/step - ia: 0.7986 - loss: 0.1383 - mae: 0.2880 - rmse: 0.3568 - smape: 0.5751 - val_ia: 0.2870 - val_loss: 0.1122 - val_mae: 0.2690 - val_rmse: 0.2826 - val_smape: 0.5928

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:34 1s/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 10%|█         | 5/50 [1:12:50<14:07:29, 1129.99s/trial, best loss: 0.005043283809393472]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 25s - 22ms/step - ia: 0.5339 - loss: 0.4709 - mae: 0.5425 - rmse: 0.6685 - smape: 1.0795 - val_ia: 0.4405 - val_loss: 0.2453 - val_mae: 0.3841 - val_rmse: 0.4533 - val_smape: 0.8090

Epoch 2/128

1147/1147 - 21s - 18ms/step - ia: 0.7425 - loss: 0.2379 - mae: 0.3808 - rmse: 0.4833 - smape: 0.7618 - val_ia: 0.4578 - val_loss: 0.2240 - val_mae: 0.3652 - val_rmse: 0.4324 - val_smape: 0.7566

Epoch 3/128

1147/1147 - 13s - 11ms/step - ia: 0.7661 - loss: 0.2052 - mae: 0.3530 - rmse: 0.4492 - smape: 0.7124 - val_ia: 0.4669 - val_loss: 0.2282 - val_mae: 0.3741 - val_rmse: 0.4351 - val_smape: 0.7519

Epoch 4/128

1147/1147 - 12s - 11ms/step - ia: 0.7833 - loss: 0.1812 - mae: 0.3304 - rmse: 0.4212 - smape: 0.6738 - val_ia: 0.4721 - val_loss: 0.2285 - val_mae: 0.3802 - val_rmse: 0.4366 - val_smape: 0.7490

Epoch 5/128

1147/1147 - 12s - 11ms/step - ia: 0.7951 - loss: 0.1632 - mae: 0.3139 - rmse: 0.3995 - smape: 0.6468 - val_ia: 0.4783 - val_loss: 0.2203 - val_mae: 0.3775 - val_rmse: 0.4308 - val_smape: 0.7407

Epoch 6/128

1147/1147 - 12s - 11ms/step - ia: 0.8066 - loss: 0.1478 - mae: 0.2978 - rmse: 0.3807 - smape: 0.6215 - val_ia: 0.4875 - val_loss: 0.2058 - val_mae: 0.3679 - val_rmse: 0.4185 - val_smape: 0.7290

Epoch 7/128

1147/1147 - 12s - 11ms/step - ia: 0.8171 - loss: 0.1328 - mae: 0.2821 - rmse: 0.3606 - smape: 0.5961 - val_ia: 0.4991 - val_loss: 0.1888 - val_mae: 0.3549 - val_rmse: 0.4025 - val_smape: 0.7137

Epoch 8/128

1147/1147 - 13s - 11ms/step - ia: 0.8267 - loss: 0.1210 - mae: 0.2686 - rmse: 0.3438 - smape: 0.5734 - val_ia: 0.5154 - val_loss: 0.1669 - val_mae: 0.3346 - val_rmse: 0.3799 - val_smape: 0.6926

Epoch 9/128

1147/1147 - 13s - 11ms/step - ia: 0.8364 - loss: 0.1094 - mae: 0.2545 - rmse: 0.3268 - smape: 0.5507 - val_ia: 0.5309 - val_loss: 0.1485 - val_mae: 0.3163 - val_rmse: 0.3597 - val_smape: 0.6727

Epoch 10/128

1147/1147 - 12s - 11ms/step - ia: 0.8453 - loss: 0.0990 - mae: 0.2413 - rmse: 0.3108 - smape: 0.5288 - val_ia: 0.5517 - val_loss: 0.1289 - val_mae: 0.2937 - val_rmse: 0.3352 - val_smape: 0.6472

Epoch 11/128

1147/1147 - 13s - 11ms/step - ia: 0.8523 - loss: 0.0914 - mae: 0.2312 - rmse: 0.2984 - smape: 0.5130 - val_ia: 0.5697 - val_loss: 0.1127 - val_mae: 0.2740 - val_rmse: 0.3142 - val_smape: 0.6242

Epoch 12/128

1147/1147 - 12s - 11ms/step - ia: 0.8582 - loss: 0.0847 - mae: 0.2221 - rmse: 0.2873 - smape: 0.4954 - val_ia: 0.5862 - val_loss: 0.1001 - val_mae: 0.2573 - val_rmse: 0.2964 - val_smape: 0.6037

Epoch 13/128

1147/1147 - 11s - 10ms/step - ia: 0.8639 - loss: 0.0791 - mae: 0.2137 - rmse: 0.2774 - smape: 0.4818 - val_ia: 0.6060 - val_loss: 0.0868 - val_mae: 0.2371 - val_rmse: 0.2762 - val_smape: 0.5792

Epoch 14/128

1147/1147 - 11s - 10ms/step - ia: 0.8684 - loss: 0.0742 - mae: 0.2069 - rmse: 0.2687 - smape: 0.4692 - val_ia: 0.6185 - val_loss: 0.0792 - val_mae: 0.2253 - val_rmse: 0.2639 - val_smape: 0.5629

Epoch 15/128

1147/1147 - 13s - 11ms/step - ia: 0.8714 - loss: 0.0714 - mae: 0.2024 - rmse: 0.2632 - smape: 0.4590 - val_ia: 0.6307 - val_loss: 0.0725 - val_mae: 0.2141 - val_rmse: 0.2523 - val_smape: 0.5471

Epoch 16/128

1147/1147 - 13s - 11ms/step - ia: 0.8741 - loss: 0.0688 - mae: 0.1985 - rmse: 0.2585 - smape: 0.4510 - val_ia: 0.6402 - val_loss: 0.0674 - val_mae: 0.2055 - val_rmse: 0.2432 - val_smape: 0.5347

Epoch 17/128

1147/1147 - 13s - 11ms/step - ia: 0.8771 - loss: 0.0660 - mae: 0.1939 - rmse: 0.2536 - smape: 0.4423 - val_ia: 0.6494 - val_loss: 0.0627 - val_mae: 0.1975 - val_rmse: 0.2345 - val_smape: 0.5211

Epoch 18/128

1147/1147 - 12s - 10ms/step - ia: 0.8797 - loss: 0.0636 - mae: 0.1897 - rmse: 0.2486 - smape: 0.4336 - val_ia: 0.6560 - val_loss: 0.0596 - val_mae: 0.1921 - val_rmse: 0.2285 - val_smape: 0.5120

Epoch 19/128

1147/1147 - 12s - 10ms/step - ia: 0.8815 - loss: 0.0623 - mae: 0.1873 - rmse: 0.2460 - smape: 0.4286 - val_ia: 0.6633 - val_loss: 0.0562 - val_mae: 0.1857 - val_rmse: 0.2216 - val_smape: 0.5013

Epoch 20/128

1147/1147 - 14s - 12ms/step - ia: 0.8829 - loss: 0.0607 - mae: 0.1849 - rmse: 0.2428 - smape: 0.4214 - val_ia: 0.6653 - val_loss: 0.0555 - val_mae: 0.1850 - val_rmse: 0.2201 - val_smape: 0.4984

Epoch 21/128

1147/1147 - 13s - 12ms/step - ia: 0.8850 - loss: 0.0588 - mae: 0.1816 - rmse: 0.2386 - smape: 0.4168 - val_ia: 0.6703 - val_loss: 0.0532 - val_mae: 0.1809 - val_rmse: 0.2153 - val_smape: 0.4918

Epoch 22/128

1147/1147 - 14s - 12ms/step - ia: 0.8879 - loss: 0.0563 - mae: 0.1774 - rmse: 0.2340 - smape: 0.4095 - val_ia: 0.6735 - val_loss: 0.0516 - val_mae: 0.1783 - val_rmse: 0.2121 - val_smape: 0.4861

Epoch 23/128

1147/1147 - 11s - 10ms/step - ia: 0.8873 - loss: 0.0570 - mae: 0.1783 - rmse: 0.2353 - smape: 0.4078 - val_ia: 0.6782 - val_loss: 0.0497 - val_mae: 0.1744 - val_rmse: 0.2081 - val_smape: 0.4788

Epoch 24/128

1147/1147 - 11s - 10ms/step - ia: 0.8898 - loss: 0.0549 - mae: 0.1744 - rmse: 0.2306 - smape: 0.4025 - val_ia: 0.6827 - val_loss: 0.0480 - val_mae: 0.1711 - val_rmse: 0.2043 - val_smape: 0.4713

Epoch 25/128

1147/1147 - 12s - 10ms/step - ia: 0.8905 - loss: 0.0547 - mae: 0.1735 - rmse: 0.2301 - smape: 0.3971 - val_ia: 0.6857 - val_loss: 0.0467 - val_mae: 0.1688 - val_rmse: 0.2015 - val_smape: 0.4669

Epoch 26/128

1147/1147 - 13s - 11ms/step - ia: 0.8915 - loss: 0.0535 - mae: 0.1718 - rmse: 0.2277 - smape: 0.3959 - val_ia: 0.6881 - val_loss: 0.0458 - val_mae: 0.1671 - val_rmse: 0.1995 - val_smape: 0.4624

Epoch 27/128

1147/1147 - 13s - 11ms/step - ia: 0.8929 - loss: 0.0525 - mae: 0.1699 - rmse: 0.2257 - smape: 0.3901 - val_ia: 0.6896 - val_loss: 0.0453 - val_mae: 0.1660 - val_rmse: 0.1982 - val_smape: 0.4584

Epoch 28/128

1147/1147 - 12s - 10ms/step - ia: 0.8934 - loss: 0.0518 - mae: 0.1689 - rmse: 0.2240 - smape: 0.3881 - val_ia: 0.6929 - val_loss: 0.0441 - val_mae: 0.1639 - val_rmse: 0.1956 - val_smape: 0.4546

Epoch 29/128

1147/1147 - 13s - 11ms/step - ia: 0.8943 - loss: 0.0513 - mae: 0.1675 - rmse: 0.2231 - smape: 0.3848 - val_ia: 0.6952 - val_loss: 0.0432 - val_mae: 0.1622 - val_rmse: 0.1937 - val_smape: 0.4517

Epoch 30/128

1147/1147 - 13s - 11ms/step - ia: 0.8954 - loss: 0.0504 - mae: 0.1661 - rmse: 0.2208 - smape: 0.3810 - val_ia: 0.6975 - val_loss: 0.0425 - val_mae: 0.1610 - val_rmse: 0.1921 - val_smape: 0.4494

Epoch 31/128

1147/1147 - 12s - 11ms/step - ia: 0.8967 - loss: 0.0492 - mae: 0.1641 - rmse: 0.2182 - smape: 0.3803 - val_ia: 0.6995 - val_loss: 0.0419 - val_mae: 0.1595 - val_rmse: 0.1907 - val_smape: 0.4437

Epoch 32/128

1147/1147 - 20s - 17ms/step - ia: 0.8972 - loss: 0.0490 - mae: 0.1632 - rmse: 0.2177 - smape: 0.3757 - val_ia: 0.7037 - val_loss: 0.0405 - val_mae: 0.1565 - val_rmse: 0.1873 - val_smape: 0.4393

Epoch 33/128

1147/1147 - 11s - 10ms/step - ia: 0.8981 - loss: 0.0482 - mae: 0.1623 - rmse: 0.2160 - smape: 0.3730 - val_ia: 0.7041 - val_loss: 0.0403 - val_mae: 0.1563 - val_rmse: 0.1869 - val_smape: 0.4394

Epoch 34/128

1147/1147 - 12s - 10ms/step - ia: 0.8985 - loss: 0.0475 - mae: 0.1611 - rmse: 0.2146 - smape: 0.3722 - val_ia: 0.7060 - val_loss: 0.0397 - val_mae: 0.1550 - val_rmse: 0.1855 - val_smape: 0.4354

Epoch 35/128

1147/1147 - 13s - 11ms/step - ia: 0.8991 - loss: 0.0473 - mae: 0.1603 - rmse: 0.2137 - smape: 0.3693 - val_ia: 0.7059 - val_loss: 0.0398 - val_mae: 0.1549 - val_rmse: 0.1855 - val_smape: 0.4329

Epoch 36/128

1147/1147 - 13s - 11ms/step - ia: 0.8995 - loss: 0.0470 - mae: 0.1597 - rmse: 0.2133 - smape: 0.3681 - val_ia: 0.7086 - val_loss: 0.0389 - val_mae: 0.1533 - val_rmse: 0.1835 - val_smape: 0.4309

Epoch 37/128

1147/1147 - 13s - 11ms/step - ia: 0.9004 - loss: 0.0463 - mae: 0.1583 - rmse: 0.2116 - smape: 0.3626 - val_ia: 0.7088 - val_loss: 0.0390 - val_mae: 0.1536 - val_rmse: 0.1835 - val_smape: 0.4315

Epoch 38/128

1147/1147 - 13s - 11ms/step - ia: 0.9006 - loss: 0.0459 - mae: 0.1580 - rmse: 0.2110 - smape: 0.3624 - val_ia: 0.7126 - val_loss: 0.0375 - val_mae: 0.1500 - val_rmse: 0.1801 - val_smape: 0.4218

Epoch 39/128

1147/1147 - 21s - 18ms/step - ia: 0.9009 - loss: 0.0459 - mae: 0.1575 - rmse: 0.2108 - smape: 0.3612 - val_ia: 0.7122 - val_loss: 0.0377 - val_mae: 0.1506 - val_rmse: 0.1805 - val_smape: 0.4224

Epoch 40/128

1147/1147 - 13s - 12ms/step - ia: 0.9021 - loss: 0.0446 - mae: 0.1556 - rmse: 0.2077 - smape: 0.3574 - val_ia: 0.7151 - val_loss: 0.0369 - val_mae: 0.1489 - val_rmse: 0.1786 - val_smape: 0.4208

Epoch 41/128

1147/1147 - 13s - 11ms/step - ia: 0.9029 - loss: 0.0443 - mae: 0.1547 - rmse: 0.2071 - smape: 0.3561 - val_ia: 0.7181 - val_loss: 0.0359 - val_mae: 0.1466 - val_rmse: 0.1763 - val_smape: 0.4154

Epoch 42/128

1147/1147 - 14s - 12ms/step - ia: 0.9035 - loss: 0.0439 - mae: 0.1537 - rmse: 0.2059 - smape: 0.3551 - val_ia: 0.7188 - val_loss: 0.0356 - val_mae: 0.1458 - val_rmse: 0.1753 - val_smape: 0.4123

Epoch 43/128

1147/1147 - 13s - 12ms/step - ia: 0.9038 - loss: 0.0433 - mae: 0.1531 - rmse: 0.2045 - smape: 0.3534 - val_ia: 0.7213 - val_loss: 0.0349 - val_mae: 0.1440 - val_rmse: 0.1736 - val_smape: 0.4080

Epoch 44/128

1147/1147 - 12s - 11ms/step - ia: 0.9046 - loss: 0.0427 - mae: 0.1517 - rmse: 0.2031 - smape: 0.3501 - val_ia: 0.7215 - val_loss: 0.0349 - val_mae: 0.1442 - val_rmse: 0.1736 - val_smape: 0.4084

Epoch 45/128

1147/1147 - 12s - 11ms/step - ia: 0.9051 - loss: 0.0422 - mae: 0.1508 - rmse: 0.2021 - smape: 0.3482 - val_ia: 0.7228 - val_loss: 0.0345 - val_mae: 0.1434 - val_rmse: 0.1727 - val_smape: 0.4075

Epoch 46/128

1147/1147 - 13s - 12ms/step - ia: 0.9050 - loss: 0.0425 - mae: 0.1510 - rmse: 0.2026 - smape: 0.3483 - val_ia: 0.7233 - val_loss: 0.0347 - val_mae: 0.1438 - val_rmse: 0.1729 - val_smape: 0.4085

Epoch 47/128

1147/1147 - 11s - 10ms/step - ia: 0.9054 - loss: 0.0419 - mae: 0.1507 - rmse: 0.2013 - smape: 0.3461 - val_ia: 0.7243 - val_loss: 0.0341 - val_mae: 0.1423 - val_rmse: 0.1714 - val_smape: 0.4031

Epoch 48/128

1147/1147 - 12s - 10ms/step - ia: 0.9061 - loss: 0.0418 - mae: 0.1497 - rmse: 0.2008 - smape: 0.3429 - val_ia: 0.7276 - val_loss: 0.0331 - val_mae: 0.1401 - val_rmse: 0.1692 - val_smape: 0.3992

Epoch 49/128

1147/1147 - 12s - 11ms/step - ia: 0.9056 - loss: 0.0419 - mae: 0.1503 - rmse: 0.2015 - smape: 0.3447 - val_ia: 0.7268 - val_loss: 0.0333 - val_mae: 0.1404 - val_rmse: 0.1696 - val_smape: 0.3983

Epoch 50/128

1147/1147 - 13s - 12ms/step - ia: 0.9063 - loss: 0.0411 - mae: 0.1490 - rmse: 0.1994 - smape: 0.3451 - val_ia: 0.7281 - val_loss: 0.0330 - val_mae: 0.1396 - val_rmse: 0.1687 - val_smape: 0.3970

Epoch 51/128

1147/1147 - 13s - 11ms/step - ia: 0.9074 - loss: 0.0407 - mae: 0.1479 - rmse: 0.1983 - smape: 0.3421 - val_ia: 0.7311 - val_loss: 0.0323 - val_mae: 0.1381 - val_rmse: 0.1668 - val_smape: 0.3935

Epoch 52/128

1147/1147 - 13s - 12ms/step - ia: 0.9075 - loss: 0.0406 - mae: 0.1476 - rmse: 0.1983 - smape: 0.3388 - val_ia: 0.7307 - val_loss: 0.0323 - val_mae: 0.1380 - val_rmse: 0.1668 - val_smape: 0.3930

Epoch 53/128

1147/1147 - 13s - 12ms/step - ia: 0.9076 - loss: 0.0403 - mae: 0.1474 - rmse: 0.1975 - smape: 0.3396 - val_ia: 0.7331 - val_loss: 0.0318 - val_mae: 0.1368 - val_rmse: 0.1654 - val_smape: 0.3917

Epoch 54/128

1147/1147 - 12s - 11ms/step - ia: 0.9074 - loss: 0.0404 - mae: 0.1475 - rmse: 0.1977 - smape: 0.3378 - val_ia: 0.7335 - val_loss: 0.0317 - val_mae: 0.1367 - val_rmse: 0.1651 - val_smape: 0.3910

Epoch 55/128

1147/1147 - 11s - 10ms/step - ia: 0.9088 - loss: 0.0395 - mae: 0.1455 - rmse: 0.1953 - smape: 0.3345 - val_ia: 0.7346 - val_loss: 0.0313 - val_mae: 0.1359 - val_rmse: 0.1643 - val_smape: 0.3898

Epoch 56/128

1147/1147 - 13s - 11ms/step - ia: 0.9084 - loss: 0.0397 - mae: 0.1456 - rmse: 0.1960 - smape: 0.3343 - val_ia: 0.7353 - val_loss: 0.0309 - val_mae: 0.1348 - val_rmse: 0.1633 - val_smape: 0.3855

Epoch 57/128

1147/1147 - 14s - 12ms/step - ia: 0.9094 - loss: 0.0388 - mae: 0.1444 - rmse: 0.1935 - smape: 0.3317 - val_ia: 0.7358 - val_loss: 0.0309 - val_mae: 0.1348 - val_rmse: 0.1631 - val_smape: 0.3857

Epoch 58/128

1147/1147 - 16s - 14ms/step - ia: 0.9098 - loss: 0.0381 - mae: 0.1435 - rmse: 0.1920 - smape: 0.3312 - val_ia: 0.7360 - val_loss: 0.0307 - val_mae: 0.1343 - val_rmse: 0.1626 - val_smape: 0.3839

Epoch 59/128

1147/1147 - 15s - 13ms/step - ia: 0.9100 - loss: 0.0384 - mae: 0.1434 - rmse: 0.1926 - smape: 0.3316 - val_ia: 0.7370 - val_loss: 0.0305 - val_mae: 0.1341 - val_rmse: 0.1622 - val_smape: 0.3851

Epoch 60/128

1147/1147 - 12s - 11ms/step - ia: 0.9099 - loss: 0.0385 - mae: 0.1435 - rmse: 0.1928 - smape: 0.3286 - val_ia: 0.7373 - val_loss: 0.0304 - val_mae: 0.1336 - val_rmse: 0.1618 - val_smape: 0.3829

Epoch 61/128

1147/1147 - 16s - 14ms/step - ia: 0.9107 - loss: 0.0376 - mae: 0.1422 - rmse: 0.1908 - smape: 0.3282 - val_ia: 0.7403 - val_loss: 0.0295 - val_mae: 0.1314 - val_rmse: 0.1595 - val_smape: 0.3770

Epoch 62/128

1147/1147 - 16s - 14ms/step - ia: 0.9109 - loss: 0.0378 - mae: 0.1421 - rmse: 0.1911 - smape: 0.3276 - val_ia: 0.7400 - val_loss: 0.0295 - val_mae: 0.1313 - val_rmse: 0.1595 - val_smape: 0.3757

Epoch 63/128

1147/1147 - 15s - 13ms/step - ia: 0.9113 - loss: 0.0374 - mae: 0.1417 - rmse: 0.1901 - smape: 0.3278 - val_ia: 0.7431 - val_loss: 0.0289 - val_mae: 0.1300 - val_rmse: 0.1578 - val_smape: 0.3751

Epoch 64/128

1147/1147 - 15s - 13ms/step - ia: 0.9115 - loss: 0.0372 - mae: 0.1410 - rmse: 0.1894 - smape: 0.3250 - val_ia: 0.7415 - val_loss: 0.0292 - val_mae: 0.1306 - val_rmse: 0.1586 - val_smape: 0.3744

Epoch 65/128

1147/1147 - 20s - 18ms/step - ia: 0.9119 - loss: 0.0371 - mae: 0.1404 - rmse: 0.1893 - smape: 0.3235 - val_ia: 0.7442 - val_loss: 0.0287 - val_mae: 0.1294 - val_rmse: 0.1571 - val_smape: 0.3744

Epoch 66/128

1147/1147 - 15s - 13ms/step - ia: 0.9125 - loss: 0.0365 - mae: 0.1396 - rmse: 0.1876 - smape: 0.3211 - val_ia: 0.7439 - val_loss: 0.0285 - val_mae: 0.1287 - val_rmse: 0.1567 - val_smape: 0.3694

Epoch 67/128

1147/1147 - 14s - 12ms/step - ia: 0.9124 - loss: 0.0365 - mae: 0.1397 - rmse: 0.1877 - smape: 0.3222 - val_ia: 0.7444 - val_loss: 0.0283 - val_mae: 0.1286 - val_rmse: 0.1564 - val_smape: 0.3701

Epoch 68/128

1147/1147 - 12s - 10ms/step - ia: 0.9130 - loss: 0.0361 - mae: 0.1387 - rmse: 0.1868 - smape: 0.3206 - val_ia: 0.7443 - val_loss: 0.0286 - val_mae: 0.1294 - val_rmse: 0.1569 - val_smape: 0.3729

Epoch 69/128

1147/1147 - 13s - 12ms/step - ia: 0.9131 - loss: 0.0358 - mae: 0.1389 - rmse: 0.1861 - smape: 0.3216 - val_ia: 0.7463 - val_loss: 0.0280 - val_mae: 0.1275 - val_rmse: 0.1552 - val_smape: 0.3675

Epoch 70/128

1147/1147 - 15s - 13ms/step - ia: 0.9132 - loss: 0.0359 - mae: 0.1384 - rmse: 0.1862 - smape: 0.3209 - val_ia: 0.7505 - val_loss: 0.0269 - val_mae: 0.1248 - val_rmse: 0.1522 - val_smape: 0.3618

Epoch 71/128

1147/1147 - 19s - 17ms/step - ia: 0.9138 - loss: 0.0353 - mae: 0.1379 - rmse: 0.1846 - smape: 0.3198 - val_ia: 0.7502 - val_loss: 0.0269 - val_mae: 0.1251 - val_rmse: 0.1524 - val_smape: 0.3627

Epoch 72/128

1147/1147 - 15s - 13ms/step - ia: 0.9145 - loss: 0.0351 - mae: 0.1365 - rmse: 0.1841 - smape: 0.3160 - val_ia: 0.7494 - val_loss: 0.0272 - val_mae: 0.1257 - val_rmse: 0.1529 - val_smape: 0.3634

Epoch 73/128

1147/1147 - 15s - 13ms/step - ia: 0.9137 - loss: 0.0355 - mae: 0.1376 - rmse: 0.1853 - smape: 0.3166 - val_ia: 0.7506 - val_loss: 0.0268 - val_mae: 0.1245 - val_rmse: 0.1518 - val_smape: 0.3595

Epoch 74/128

1147/1147 - 19s - 16ms/step - ia: 0.9148 - loss: 0.0346 - mae: 0.1362 - rmse: 0.1828 - smape: 0.3152 - val_ia: 0.7527 - val_loss: 0.0265 - val_mae: 0.1239 - val_rmse: 0.1509 - val_smape: 0.3610

Epoch 75/128

1147/1147 - 15s - 13ms/step - ia: 0.9140 - loss: 0.0351 - mae: 0.1370 - rmse: 0.1838 - smape: 0.3143 - val_ia: 0.7524 - val_loss: 0.0264 - val_mae: 0.1236 - val_rmse: 0.1508 - val_smape: 0.3587

Epoch 76/128

1147/1147 - 13s - 11ms/step - ia: 0.9151 - loss: 0.0342 - mae: 0.1357 - rmse: 0.1815 - smape: 0.3128 - val_ia: 0.7544 - val_loss: 0.0260 - val_mae: 0.1226 - val_rmse: 0.1496 - val_smape: 0.3580

Epoch 77/128

1147/1147 - 14s - 12ms/step - ia: 0.9150 - loss: 0.0347 - mae: 0.1358 - rmse: 0.1828 - smape: 0.3139 - val_ia: 0.7533 - val_loss: 0.0261 - val_mae: 0.1228 - val_rmse: 0.1499 - val_smape: 0.3560

Epoch 78/128

1147/1147 - 13s - 12ms/step - ia: 0.9157 - loss: 0.0337 - mae: 0.1345 - rmse: 0.1804 - smape: 0.3121 - val_ia: 0.7548 - val_loss: 0.0257 - val_mae: 0.1218 - val_rmse: 0.1488 - val_smape: 0.3532

Epoch 79/128

1147/1147 - 21s - 19ms/step - ia: 0.9158 - loss: 0.0338 - mae: 0.1344 - rmse: 0.1806 - smape: 0.3109 - val_ia: 0.7566 - val_loss: 0.0254 - val_mae: 0.1210 - val_rmse: 0.1479 - val_smape: 0.3529

Epoch 80/128

1147/1147 - 14s - 12ms/step - ia: 0.9155 - loss: 0.0340 - mae: 0.1349 - rmse: 0.1814 - smape: 0.3106 - val_ia: 0.7587 - val_loss: 0.0248 - val_mae: 0.1194 - val_rmse: 0.1464 - val_smape: 0.3478

Epoch 81/128

1147/1147 - 12s - 10ms/step - ia: 0.9157 - loss: 0.0339 - mae: 0.1345 - rmse: 0.1808 - smape: 0.3101 - val_ia: 0.7590 - val_loss: 0.0247 - val_mae: 0.1189 - val_rmse: 0.1457 - val_smape: 0.3442

Epoch 82/128

1147/1147 - 11s - 10ms/step - ia: 0.9164 - loss: 0.0334 - mae: 0.1335 - rmse: 0.1795 - smape: 0.3090 - val_ia: 0.7603 - val_loss: 0.0245 - val_mae: 0.1187 - val_rmse: 0.1453 - val_smape: 0.3469

Epoch 83/128

1147/1147 - 11s - 10ms/step - ia: 0.9166 - loss: 0.0334 - mae: 0.1335 - rmse: 0.1795 - smape: 0.3076 - val_ia: 0.7605 - val_loss: 0.0244 - val_mae: 0.1185 - val_rmse: 0.1451 - val_smape: 0.3458

Epoch 84/128

1147/1147 - 13s - 11ms/step - ia: 0.9174 - loss: 0.0326 - mae: 0.1322 - rmse: 0.1775 - smape: 0.3061 - val_ia: 0.7597 - val_loss: 0.0246 - val_mae: 0.1192 - val_rmse: 0.1456 - val_smape: 0.3483

Epoch 85/128

1147/1147 - 12s - 11ms/step - ia: 0.9167 - loss: 0.0332 - mae: 0.1332 - rmse: 0.1792 - smape: 0.3090 - val_ia: 0.7624 - val_loss: 0.0239 - val_mae: 0.1169 - val_rmse: 0.1435 - val_smape: 0.3408

Epoch 86/128

1147/1147 - 11s - 10ms/step - ia: 0.9174 - loss: 0.0324 - mae: 0.1322 - rmse: 0.1767 - smape: 0.3058 - val_ia: 0.7637 - val_loss: 0.0237 - val_mae: 0.1166 - val_rmse: 0.1430 - val_smape: 0.3422

Epoch 87/128

1147/1147 - 13s - 11ms/step - ia: 0.9174 - loss: 0.0325 - mae: 0.1316 - rmse: 0.1772 - smape: 0.3044 - val_ia: 0.7648 - val_loss: 0.0234 - val_mae: 0.1155 - val_rmse: 0.1420 - val_smape: 0.3382

Epoch 88/128

1147/1147 - 12s - 11ms/step - ia: 0.9182 - loss: 0.0319 - mae: 0.1307 - rmse: 0.1756 - smape: 0.3040 - val_ia: 0.7643 - val_loss: 0.0234 - val_mae: 0.1155 - val_rmse: 0.1420 - val_smape: 0.3362

Epoch 89/128

1147/1147 - 13s - 11ms/step - ia: 0.9177 - loss: 0.0323 - mae: 0.1314 - rmse: 0.1767 - smape: 0.3049 - val_ia: 0.7662 - val_loss: 0.0230 - val_mae: 0.1145 - val_rmse: 0.1410 - val_smape: 0.3352

Epoch 90/128

1147/1147 - 21s - 19ms/step - ia: 0.9184 - loss: 0.0318 - mae: 0.1304 - rmse: 0.1752 - smape: 0.3025 - val_ia: 0.7672 - val_loss: 0.0227 - val_mae: 0.1136 - val_rmse: 0.1400 - val_smape: 0.3315

Epoch 91/128

1147/1147 - 14s - 12ms/step - ia: 0.9182 - loss: 0.0320 - mae: 0.1306 - rmse: 0.1758 - smape: 0.3028 - val_ia: 0.7665 - val_loss: 0.0229 - val_mae: 0.1145 - val_rmse: 0.1406 - val_smape: 0.3356

Epoch 92/128

1147/1147 - 13s - 12ms/step - ia: 0.9185 - loss: 0.0319 - mae: 0.1303 - rmse: 0.1756 - smape: 0.3011 - val_ia: 0.7693 - val_loss: 0.0222 - val_mae: 0.1123 - val_rmse: 0.1385 - val_smape: 0.3279

Epoch 93/128

1147/1147 - 14s - 12ms/step - ia: 0.9189 - loss: 0.0315 - mae: 0.1297 - rmse: 0.1743 - smape: 0.2992 - val_ia: 0.7660 - val_loss: 0.0229 - val_mae: 0.1144 - val_rmse: 0.1405 - val_smape: 0.3333

Epoch 94/128

1147/1147 - 20s - 18ms/step - ia: 0.9183 - loss: 0.0317 - mae: 0.1305 - rmse: 0.1751 - smape: 0.3008 - val_ia: 0.7673 - val_loss: 0.0227 - val_mae: 0.1139 - val_rmse: 0.1398 - val_smape: 0.3339

Epoch 95/128

1147/1147 - 14s - 12ms/step - ia: 0.9191 - loss: 0.0311 - mae: 0.1293 - rmse: 0.1735 - smape: 0.2995 - val_ia: 0.7665 - val_loss: 0.0228 - val_mae: 0.1143 - val_rmse: 0.1401 - val_smape: 0.3340

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 15s - 102ms/step - ia: 0.8851 - loss: 0.0679 - mae: 0.1826 - rmse: 0.2459 - smape: 0.3808 - val_ia: 0.9384 - val_loss: 0.0125 - val_mae: 0.0824 - val_rmse: 0.1105 - val_smape: 0.1935

Epoch 2/128

144/144 - 2s - 17ms/step - ia: 0.9193 - loss: 0.0335 - mae: 0.1317 - rmse: 0.1824 - smape: 0.2784 - val_ia: 0.9502 - val_loss: 0.0076 - val_mae: 0.0665 - val_rmse: 0.0852 - val_smape: 0.1980

Epoch 3/128

144/144 - 2s - 16ms/step - ia: 0.9222 - loss: 0.0317 - mae: 0.1270 - rmse: 0.1776 - smape: 0.2627 - val_ia: 0.9508 - val_loss: 0.0071 - val_mae: 0.0646 - val_rmse: 0.0813 - val_smape: 0.1805

Epoch 4/128

144/144 - 2s - 16ms/step - ia: 0.9243 - loss: 0.0303 - mae: 0.1236 - rmse: 0.1742 - smape: 0.2531 - val_ia: 0.9509 - val_loss: 0.0071 - val_mae: 0.0664 - val_rmse: 0.0846 - val_smape: 0.1715

Epoch 5/128

144/144 - 2s - 17ms/step - ia: 0.9252 - loss: 0.0298 - mae: 0.1222 - rmse: 0.1720 - smape: 0.2477 - val_ia: 0.9463 - val_loss: 0.0079 - val_mae: 0.0695 - val_rmse: 0.0850 - val_smape: 0.1792

Epoch 6/128

144/144 - 2s - 17ms/step - ia: 0.9269 - loss: 0.0288 - mae: 0.1196 - rmse: 0.1693 - smape: 0.2413 - val_ia: 0.9458 - val_loss: 0.0083 - val_mae: 0.0721 - val_rmse: 0.0897 - val_smape: 0.1675

Epoch 7/128

144/144 - 2s - 16ms/step - ia: 0.9278 - loss: 0.0280 - mae: 0.1181 - rmse: 0.1668 - smape: 0.2387 - val_ia: 0.9628 - val_loss: 0.0044 - val_mae: 0.0485 - val_rmse: 0.0647 - val_smape: 0.1399

Epoch 8/128

144/144 - 2s - 16ms/step - ia: 0.9290 - loss: 0.0274 - mae: 0.1161 - rmse: 0.1650 - smape: 0.2334 - val_ia: 0.9631 - val_loss: 0.0043 - val_mae: 0.0492 - val_rmse: 0.0650 - val_smape: 0.1381

Epoch 9/128

144/144 - 2s - 16ms/step - ia: 0.9289 - loss: 0.0273 - mae: 0.1164 - rmse: 0.1647 - smape: 0.2323 - val_ia: 0.9677 - val_loss: 0.0034 - val_mae: 0.0426 - val_rmse: 0.0582 - val_smape: 0.1327

Epoch 10/128

144/144 - 2s - 16ms/step - ia: 0.9289 - loss: 0.0274 - mae: 0.1162 - rmse: 0.1651 - smape: 0.2321 - val_ia: 0.9600 - val_loss: 0.0057 - val_mae: 0.0542 - val_rmse: 0.0733 - val_smape: 0.1456

Epoch 11/128

144/144 - 2s - 16ms/step - ia: 0.9292 - loss: 0.0274 - mae: 0.1159 - rmse: 0.1648 - smape: 0.2307 - val_ia: 0.9562 - val_loss: 0.0056 - val_mae: 0.0583 - val_rmse: 0.0739 - val_smape: 0.1549

Epoch 12/128

144/144 - 2s - 15ms/step - ia: 0.9299 - loss: 0.0268 - mae: 0.1148 - rmse: 0.1632 - smape: 0.2273 - val_ia: 0.9459 - val_loss: 0.0082 - val_mae: 0.0710 - val_rmse: 0.0867 - val_smape: 0.1702

Epoch 13/128

144/144 - 2s - 16ms/step - ia: 0.9295 - loss: 0.0268 - mae: 0.1154 - rmse: 0.1635 - smape: 0.2291 - val_ia: 0.9564 - val_loss: 0.0055 - val_mae: 0.0577 - val_rmse: 0.0728 - val_smape: 0.1572

Epoch 14/128

144/144 - 2s - 16ms/step - ia: 0.9295 - loss: 0.0272 - mae: 0.1155 - rmse: 0.1644 - smape: 0.2274 - val_ia: 0.9552 - val_loss: 0.0059 - val_mae: 0.0593 - val_rmse: 0.0747 - val_smape: 0.1500

Epoch 15/128

144/144 - 2s - 16ms/step - ia: 0.9308 - loss: 0.0262 - mae: 0.1133 - rmse: 0.1612 - smape: 0.2255 - val_ia: 0.9656 - val_loss: 0.0038 - val_mae: 0.0457 - val_rmse: 0.0607 - val_smape: 0.1365

Epoch 16/128

144/144 - 3s - 18ms/step - ia: 0.9301 - loss: 0.0266 - mae: 0.1143 - rmse: 0.1625 - smape: 0.2242 - val_ia: 0.9459 - val_loss: 0.0083 - val_mae: 0.0719 - val_rmse: 0.0897 - val_smape: 0.1607

Epoch 17/128

144/144 - 3s - 17ms/step - ia: 0.9299 - loss: 0.0268 - mae: 0.1146 - rmse: 0.1631 - smape: 0.2254 - val_ia: 0.9627 - val_loss: 0.0043 - val_mae: 0.0489 - val_rmse: 0.0638 - val_smape: 0.1549

Epoch 18/128

144/144 - 3s - 19ms/step - ia: 0.9307 - loss: 0.0265 - mae: 0.1135 - rmse: 0.1625 - smape: 0.2239 - val_ia: 0.9539 - val_loss: 0.0063 - val_mae: 0.0610 - val_rmse: 0.0767 - val_smape: 0.1485

Epoch 19/128

144/144 - 3s - 18ms/step - ia: 0.9313 - loss: 0.0259 - mae: 0.1124 - rmse: 0.1606 - smape: 0.2223 - val_ia: 0.9551 - val_loss: 0.0060 - val_mae: 0.0602 - val_rmse: 0.0768 - val_smape: 0.1499

Epoch 20/128

144/144 - 2s - 17ms/step - ia: 0.9295 - loss: 0.0274 - mae: 0.1155 - rmse: 0.1646 - smape: 0.2245 - val_ia: 0.9633 - val_loss: 0.0041 - val_mae: 0.0479 - val_rmse: 0.0622 - val_smape: 0.1453

Epoch 21/128

144/144 - 2s - 17ms/step - ia: 0.9304 - loss: 0.0266 - mae: 0.1139 - rmse: 0.1627 - smape: 0.2243 - val_ia: 0.9531 - val_loss: 0.0062 - val_mae: 0.0627 - val_rmse: 0.0780 - val_smape: 0.1545

Epoch 22/128

144/144 - 2s - 16ms/step - ia: 0.9307 - loss: 0.0263 - mae: 0.1134 - rmse: 0.1618 - smape: 0.2221 - val_ia: 0.9369 - val_loss: 0.0107 - val_mae: 0.0826 - val_rmse: 0.0981 - val_smape: 0.2136

Epoch 23/128

144/144 - 2s - 16ms/step - ia: 0.9304 - loss: 0.0267 - mae: 0.1136 - rmse: 0.1631 - smape: 0.2225 - val_ia: 0.9551 - val_loss: 0.0063 - val_mae: 0.0602 - val_rmse: 0.0786 - val_smape: 0.1559

Epoch 24/128

144/144 - 2s - 17ms/step - ia: 0.9307 - loss: 0.0263 - mae: 0.1133 - rmse: 0.1617 - smape: 0.2209 - val_ia: 0.9597 - val_loss: 0.0050 - val_mae: 0.0544 - val_rmse: 0.0695 - val_smape: 0.1500

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:23 514ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 14%|█▍        | 7/50 [1:43:15<11:03:56, 926.44s/trial, best loss: 0.0037532694797689893]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2293/2293 - 47s - 20ms/step - ia: 0.9106 - loss: 0.0391 - mae: 0.1384 - rmse: 0.1808 - smape: 0.3120 - val_ia: 0.7181 - val_loss: 0.0099 - val_mae: 0.0755 - val_rmse: 0.0882 - val_smape: 0.1849

Epoch 2/8

2293/2293 - 30s - 13ms/step - ia: 0.9360 - loss: 0.0192 - mae: 0.1008 - rmse: 0.1337 - smape: 0.2283 - val_ia: 0.8091 - val_loss: 0.0045 - val_mae: 0.0490 - val_rmse: 0.0601 - val_smape: 0.1301

Epoch 3/8

2293/2293 - 26s - 11ms/step - ia: 0.9398 - loss: 0.0173 - mae: 0.0951 - rmse: 0.1264 - smape: 0.2145 - val_ia: 0.8138 - val_loss: 0.0043 - val_mae: 0.0486 - val_rmse: 0.0593 - val_smape: 0.1388

Epoch 4/8

2293/2293 - 30s - 13ms/step - ia: 0.9415 - loss: 0.0162 - mae: 0.0921 - rmse: 0.1224 - smape: 0.2122 - val_ia: 0.7325 - val_loss: 0.0083 - val_mae: 0.0700 - val_rmse: 0.0812 - val_smape: 0.1667

Epoch 5/8

2293/2293 - 30s - 13ms/step - ia: 0.9424 - loss: 0.0158 - mae: 0.0906 - rmse: 0.1206 - smape: 0.2099 - val_ia: 0.8190 - val_loss: 0.0036 - val_mae: 0.0448 - val_rmse: 0.0554 - val_smape: 0.1337

Epoch 6/8

2293/2293 - 29s - 13ms/step - ia: 0.9423 - loss: 0.0157 - mae: 0.0906 - rmse: 0.1204 - smape: 0.2084 - val_ia: 0.7392 - val_loss: 0.0096 - val_mae: 0.0735 - val_rmse: 0.0835 - val_smape: 0.1661

Epoch 7/8

2293/2293 - 30s - 13ms/step - ia: 0.9440 - loss: 0.0150 - mae: 0.0882 - rmse: 0.1176 - smape: 0.2055 - val_ia: 0.7825 - val_loss: 0.0065 - val_mae: 0.0576 - val_rmse: 0.0686 - val_smape: 0.1369

Epoch 8/8

2293/2293 - 30s - 13ms/step - ia: 0.9444 - loss: 0.0146 - mae: 0.0875 - rmse: 0.1163 - smape: 0.2039 - val_ia: 0.7855 - val_loss: 0.0055 - val_mae: 0.0553 - val_rmse: 0.0660 - val_smape: 0.1489

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:54 1s/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

Epoch 1/128

 16%|█▌        | 8/50 [1:47:30<8:18:58, 712.81s/trial, best loss: 0.0036979985241071406]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 6s - 42ms/step - ia: 0.7274 - loss: 0.2851 - mae: 0.4070 - rmse: 0.5226 - smape: 0.7793 - val_ia: 0.7556 - val_loss: 0.1629 - val_mae: 0.3256 - val_rmse: 0.3924 - val_smape: 0.7084

Epoch 2/128

144/144 - 1s - 7ms/step - ia: 0.8041 - loss: 0.1613 - mae: 0.3074 - rmse: 0.4004 - smape: 0.6270 - val_ia: 0.8060 - val_loss: 0.1032 - val_mae: 0.2586 - val_rmse: 0.3134 - val_smape: 0.6193

Epoch 3/128

144/144 - 1s - 9ms/step - ia: 0.8279 - loss: 0.1278 - mae: 0.2717 - rmse: 0.3565 - smape: 0.5649 - val_ia: 0.8337 - val_loss: 0.0759 - val_mae: 0.2211 - val_rmse: 0.2685 - val_smape: 0.5569

Epoch 4/128

144/144 - 1s - 9ms/step - ia: 0.8429 - loss: 0.1102 - mae: 0.2493 - rmse: 0.3309 - smape: 0.5210 - val_ia: 0.8642 - val_loss: 0.0516 - val_mae: 0.1803 - val_rmse: 0.2228 - val_smape: 0.4778

Epoch 5/128

144/144 - 1s - 10ms/step - ia: 0.8573 - loss: 0.0942 - mae: 0.2272 - rmse: 0.3063 - smape: 0.4737 - val_ia: 0.8890 - val_loss: 0.0354 - val_mae: 0.1471 - val_rmse: 0.1843 - val_smape: 0.4032

Epoch 6/128

144/144 - 1s - 10ms/step - ia: 0.8675 - loss: 0.0825 - mae: 0.2118 - rmse: 0.2864 - smape: 0.4452 - val_ia: 0.9049 - val_loss: 0.0276 - val_mae: 0.1261 - val_rmse: 0.1641 - val_smape: 0.3413

Epoch 7/128

144/144 - 3s - 18ms/step - ia: 0.8719 - loss: 0.0779 - mae: 0.2048 - rmse: 0.2787 - smape: 0.4263 - val_ia: 0.9130 - val_loss: 0.0232 - val_mae: 0.1150 - val_rmse: 0.1499 - val_smape: 0.3135

Epoch 8/128

144/144 - 1s - 10ms/step - ia: 0.8770 - loss: 0.0739 - mae: 0.1972 - rmse: 0.2714 - smape: 0.4079 - val_ia: 0.9204 - val_loss: 0.0198 - val_mae: 0.1053 - val_rmse: 0.1386 - val_smape: 0.2902

Epoch 9/128

144/144 - 1s - 8ms/step - ia: 0.8803 - loss: 0.0700 - mae: 0.1922 - rmse: 0.2638 - smape: 0.3951 - val_ia: 0.9230 - val_loss: 0.0188 - val_mae: 0.1018 - val_rmse: 0.1354 - val_smape: 0.2711

Epoch 10/128

144/144 - 1s - 8ms/step - ia: 0.8823 - loss: 0.0687 - mae: 0.1887 - rmse: 0.2615 - smape: 0.3840 - val_ia: 0.9350 - val_loss: 0.0145 - val_mae: 0.0865 - val_rmse: 0.1197 - val_smape: 0.2419

Epoch 11/128

144/144 - 1s - 9ms/step - ia: 0.8851 - loss: 0.0663 - mae: 0.1845 - rmse: 0.2568 - smape: 0.3740 - val_ia: 0.9328 - val_loss: 0.0149 - val_mae: 0.0889 - val_rmse: 0.1212 - val_smape: 0.2320

Epoch 12/128

144/144 - 1s - 9ms/step - ia: 0.8873 - loss: 0.0650 - mae: 0.1813 - rmse: 0.2541 - smape: 0.3620 - val_ia: 0.9365 - val_loss: 0.0134 - val_mae: 0.0840 - val_rmse: 0.1148 - val_smape: 0.2231

Epoch 13/128

144/144 - 1s - 8ms/step - ia: 0.8883 - loss: 0.0636 - mae: 0.1796 - rmse: 0.2519 - smape: 0.3589 - val_ia: 0.9385 - val_loss: 0.0124 - val_mae: 0.0813 - val_rmse: 0.1099 - val_smape: 0.2162

Epoch 14/128

144/144 - 1s - 7ms/step - ia: 0.8897 - loss: 0.0625 - mae: 0.1774 - rmse: 0.2494 - smape: 0.3519 - val_ia: 0.9415 - val_loss: 0.0113 - val_mae: 0.0774 - val_rmse: 0.1048 - val_smape: 0.2167

Epoch 15/128

144/144 - 1s - 6ms/step - ia: 0.8908 - loss: 0.0621 - mae: 0.1759 - rmse: 0.2483 - smape: 0.3439 - val_ia: 0.9360 - val_loss: 0.0127 - val_mae: 0.0840 - val_rmse: 0.1119 - val_smape: 0.2053

Epoch 16/128

144/144 - 1s - 8ms/step - ia: 0.8921 - loss: 0.0610 - mae: 0.1734 - rmse: 0.2463 - smape: 0.3392 - val_ia: 0.9356 - val_loss: 0.0126 - val_mae: 0.0848 - val_rmse: 0.1111 - val_smape: 0.2057

Epoch 17/128

144/144 - 1s - 7ms/step - ia: 0.8926 - loss: 0.0609 - mae: 0.1728 - rmse: 0.2462 - smape: 0.3359 - val_ia: 0.9466 - val_loss: 0.0095 - val_mae: 0.0707 - val_rmse: 0.0959 - val_smape: 0.1930

Epoch 18/128

144/144 - 1s - 7ms/step - ia: 0.8927 - loss: 0.0603 - mae: 0.1723 - rmse: 0.2449 - smape: 0.3337 - val_ia: 0.9371 - val_loss: 0.0119 - val_mae: 0.0828 - val_rmse: 0.1072 - val_smape: 0.2020

Epoch 19/128

144/144 - 1s - 8ms/step - ia: 0.8942 - loss: 0.0599 - mae: 0.1702 - rmse: 0.2441 - smape: 0.3243 - val_ia: 0.9391 - val_loss: 0.0111 - val_mae: 0.0797 - val_rmse: 0.1042 - val_smape: 0.1903

Epoch 20/128

144/144 - 1s - 8ms/step - ia: 0.8947 - loss: 0.0596 - mae: 0.1695 - rmse: 0.2434 - smape: 0.3205 - val_ia: 0.9454 - val_loss: 0.0094 - val_mae: 0.0720 - val_rmse: 0.0960 - val_smape: 0.1854

Epoch 21/128

144/144 - 1s - 8ms/step - ia: 0.8961 - loss: 0.0580 - mae: 0.1672 - rmse: 0.2402 - smape: 0.3160 - val_ia: 0.9482 - val_loss: 0.0086 - val_mae: 0.0684 - val_rmse: 0.0922 - val_smape: 0.1779

Epoch 22/128

144/144 - 1s - 7ms/step - ia: 0.8942 - loss: 0.0605 - mae: 0.1702 - rmse: 0.2453 - smape: 0.3173 - val_ia: 0.9423 - val_loss: 0.0101 - val_mae: 0.0761 - val_rmse: 0.0998 - val_smape: 0.1855

Epoch 23/128

144/144 - 1s - 7ms/step - ia: 0.8959 - loss: 0.0582 - mae: 0.1675 - rmse: 0.2406 - smape: 0.3141 - val_ia: 0.9458 - val_loss: 0.0091 - val_mae: 0.0718 - val_rmse: 0.0940 - val_smape: 0.1891

Epoch 24/128

144/144 - 1s - 6ms/step - ia: 0.8967 - loss: 0.0577 - mae: 0.1665 - rmse: 0.2395 - smape: 0.3129 - val_ia: 0.9492 - val_loss: 0.0083 - val_mae: 0.0674 - val_rmse: 0.0900 - val_smape: 0.1786

Epoch 25/128

144/144 - 1s - 6ms/step - ia: 0.8965 - loss: 0.0575 - mae: 0.1664 - rmse: 0.2394 - smape: 0.3102 - val_ia: 0.9415 - val_loss: 0.0102 - val_mae: 0.0774 - val_rmse: 0.0996 - val_smape: 0.1911

Epoch 26/128

144/144 - 1s - 6ms/step - ia: 0.8971 - loss: 0.0581 - mae: 0.1656 - rmse: 0.2402 - smape: 0.3052 - val_ia: 0.9443 - val_loss: 0.0095 - val_mae: 0.0736 - val_rmse: 0.0966 - val_smape: 0.1774

Epoch 27/128

144/144 - 1s - 6ms/step - ia: 0.8979 - loss: 0.0569 - mae: 0.1644 - rmse: 0.2379 - smape: 0.3055 - val_ia: 0.9487 - val_loss: 0.0082 - val_mae: 0.0681 - val_rmse: 0.0897 - val_smape: 0.1751

Epoch 28/128

144/144 - 1s - 6ms/step - ia: 0.8985 - loss: 0.0559 - mae: 0.1635 - rmse: 0.2357 - smape: 0.3021 - val_ia: 0.9495 - val_loss: 0.0079 - val_mae: 0.0670 - val_rmse: 0.0875 - val_smape: 0.1731

Epoch 29/128

144/144 - 1s - 6ms/step - ia: 0.8972 - loss: 0.0574 - mae: 0.1654 - rmse: 0.2392 - smape: 0.3024 - val_ia: 0.9475 - val_loss: 0.0084 - val_mae: 0.0697 - val_rmse: 0.0899 - val_smape: 0.1807

Epoch 30/128

144/144 - 1s - 7ms/step - ia: 0.8978 - loss: 0.0568 - mae: 0.1647 - rmse: 0.2377 - smape: 0.3017 - val_ia: 0.9438 - val_loss: 0.0093 - val_mae: 0.0744 - val_rmse: 0.0956 - val_smape: 0.1716

Epoch 31/128

144/144 - 1s - 7ms/step - ia: 0.8982 - loss: 0.0570 - mae: 0.1640 - rmse: 0.2380 - smape: 0.2969 - val_ia: 0.9486 - val_loss: 0.0081 - val_mae: 0.0681 - val_rmse: 0.0885 - val_smape: 0.1722

Epoch 32/128

144/144 - 1s - 6ms/step - ia: 0.8982 - loss: 0.0574 - mae: 0.1640 - rmse: 0.2386 - smape: 0.2972 - val_ia: 0.9557 - val_loss: 0.0064 - val_mae: 0.0589 - val_rmse: 0.0794 - val_smape: 0.1573

Epoch 33/128

144/144 - 1s - 6ms/step - ia: 0.8988 - loss: 0.0564 - mae: 0.1633 - rmse: 0.2368 - smape: 0.2953 - val_ia: 0.9501 - val_loss: 0.0078 - val_mae: 0.0665 - val_rmse: 0.0876 - val_smape: 0.1661

Epoch 34/128

144/144 - 1s - 6ms/step - ia: 0.8983 - loss: 0.0575 - mae: 0.1639 - rmse: 0.2390 - smape: 0.2952 - val_ia: 0.9502 - val_loss: 0.0076 - val_mae: 0.0662 - val_rmse: 0.0860 - val_smape: 0.1668

Epoch 35/128

144/144 - 1s - 8ms/step - ia: 0.8983 - loss: 0.0577 - mae: 0.1638 - rmse: 0.2394 - smape: 0.2949 - val_ia: 0.9461 - val_loss: 0.0086 - val_mae: 0.0715 - val_rmse: 0.0913 - val_smape: 0.1688

Epoch 36/128

144/144 - 1s - 8ms/step - ia: 0.8997 - loss: 0.0553 - mae: 0.1617 - rmse: 0.2343 - smape: 0.2923 - val_ia: 0.9431 - val_loss: 0.0095 - val_mae: 0.0754 - val_rmse: 0.0956 - val_smape: 0.1746

Epoch 37/128

144/144 - 1s - 8ms/step - ia: 0.8991 - loss: 0.0568 - mae: 0.1626 - rmse: 0.2376 - smape: 0.2909 - val_ia: 0.9518 - val_loss: 0.0072 - val_mae: 0.0641 - val_rmse: 0.0842 - val_smape: 0.1599

Epoch 38/128

144/144 - 1s - 9ms/step - ia: 0.8995 - loss: 0.0560 - mae: 0.1619 - rmse: 0.2360 - smape: 0.2897 - val_ia: 0.9586 - val_loss: 0.0057 - val_mae: 0.0550 - val_rmse: 0.0746 - val_smape: 0.1530

Epoch 39/128

144/144 - 1s - 8ms/step - ia: 0.8996 - loss: 0.0562 - mae: 0.1616 - rmse: 0.2362 - smape: 0.2883 - val_ia: 0.9505 - val_loss: 0.0076 - val_mae: 0.0660 - val_rmse: 0.0864 - val_smape: 0.1627

Epoch 40/128

144/144 - 1s - 8ms/step - ia: 0.9003 - loss: 0.0556 - mae: 0.1607 - rmse: 0.2350 - smape: 0.2887 - val_ia: 0.9438 - val_loss: 0.0091 - val_mae: 0.0746 - val_rmse: 0.0936 - val_smape: 0.1805

Epoch 41/128

144/144 - 1s - 8ms/step - ia: 0.9001 - loss: 0.0556 - mae: 0.1610 - rmse: 0.2350 - smape: 0.2877 - val_ia: 0.9503 - val_loss: 0.0075 - val_mae: 0.0662 - val_rmse: 0.0857 - val_smape: 0.1663

Epoch 42/128

144/144 - 1s - 7ms/step - ia: 0.9007 - loss: 0.0550 - mae: 0.1603 - rmse: 0.2339 - smape: 0.2863 - val_ia: 0.9519 - val_loss: 0.0072 - val_mae: 0.0641 - val_rmse: 0.0838 - val_smape: 0.1648

Epoch 43/128

144/144 - 1s - 7ms/step - ia: 0.9000 - loss: 0.0559 - mae: 0.1611 - rmse: 0.2356 - smape: 0.2876 - val_ia: 0.9487 - val_loss: 0.0078 - val_mae: 0.0682 - val_rmse: 0.0870 - val_smape: 0.1675

Epoch 44/128

144/144 - 1s - 8ms/step - ia: 0.8998 - loss: 0.0556 - mae: 0.1614 - rmse: 0.2348 - smape: 0.2904 - val_ia: 0.9503 - val_loss: 0.0075 - val_mae: 0.0662 - val_rmse: 0.0852 - val_smape: 0.1636

Epoch 45/128

144/144 - 1s - 8ms/step - ia: 0.8999 - loss: 0.0564 - mae: 0.1611 - rmse: 0.2369 - smape: 0.2846 - val_ia: 0.9548 - val_loss: 0.0063 - val_mae: 0.0602 - val_rmse: 0.0785 - val_smape: 0.1568

Epoch 46/128

144/144 - 1s - 8ms/step - ia: 0.9015 - loss: 0.0545 - mae: 0.1589 - rmse: 0.2330 - smape: 0.2837 - val_ia: 0.9548 - val_loss: 0.0064 - val_mae: 0.0603 - val_rmse: 0.0788 - val_smape: 0.1608

Epoch 47/128

144/144 - 1s - 8ms/step - ia: 0.9008 - loss: 0.0554 - mae: 0.1598 - rmse: 0.2349 - smape: 0.2846 - val_ia: 0.9508 - val_loss: 0.0073 - val_mae: 0.0656 - val_rmse: 0.0838 - val_smape: 0.1657

Epoch 48/128

144/144 - 1s - 6ms/step - ia: 0.8992 - loss: 0.0563 - mae: 0.1623 - rmse: 0.2367 - smape: 0.2881 - val_ia: 0.9465 - val_loss: 0.0084 - val_mae: 0.0713 - val_rmse: 0.0906 - val_smape: 0.1700

Epoch 49/128

144/144 - 1s - 7ms/step - ia: 0.8998 - loss: 0.0557 - mae: 0.1615 - rmse: 0.2356 - smape: 0.2865 - val_ia: 0.9566 - val_loss: 0.0061 - val_mae: 0.0580 - val_rmse: 0.0775 - val_smape: 0.1514

Epoch 50/128

144/144 - 1s - 7ms/step - ia: 0.9006 - loss: 0.0554 - mae: 0.1604 - rmse: 0.2348 - smape: 0.2832 - val_ia: 0.9554 - val_loss: 0.0062 - val_mae: 0.0596 - val_rmse: 0.0782 - val_smape: 0.1567

Epoch 51/128

144/144 - 1s - 7ms/step - ia: 0.9010 - loss: 0.0546 - mae: 0.1595 - rmse: 0.2333 - smape: 0.2840 - val_ia: 0.9463 - val_loss: 0.0084 - val_mae: 0.0717 - val_rmse: 0.0907 - val_smape: 0.1661

Epoch 52/128

144/144 - 1s - 8ms/step - ia: 0.8999 - loss: 0.0567 - mae: 0.1612 - rmse: 0.2376 - smape: 0.2836 - val_ia: 0.9560 - val_loss: 0.0063 - val_mae: 0.0589 - val_rmse: 0.0784 - val_smape: 0.1527

Epoch 53/128

144/144 - 1s - 7ms/step - ia: 0.9009 - loss: 0.0552 - mae: 0.1596 - rmse: 0.2342 - smape: 0.2839 - val_ia: 0.9568 - val_loss: 0.0059 - val_mae: 0.0575 - val_rmse: 0.0759 - val_smape: 0.1519

Epoch 53: early stopping

Restoring model weights from the end of the best epoch: 38.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:23 887ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 18%|█▊        | 9/50 [1:48:37<5:49:14, 511.09s/trial, best loss: 0.0036979985241071406]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

1147/1147 - 34s - 29ms/step - ia: 0.8144 - loss: 0.1397 - mae: 0.2675 - rmse: 0.3435 - smape: 0.5748 - val_ia: 0.7389 - val_loss: 0.0291 - val_mae: 0.1236 - val_rmse: 0.1586 - val_smape: 0.3425

Epoch 2/16

1147/1147 - 21s - 19ms/step - ia: 0.8937 - loss: 0.0499 - mae: 0.1693 - rmse: 0.2200 - smape: 0.3967 - val_ia: 0.7578 - val_loss: 0.0260 - val_mae: 0.1181 - val_rmse: 0.1501 - val_smape: 0.3377

Epoch 3/16

1147/1147 - 22s - 19ms/step - ia: 0.9085 - loss: 0.0384 - mae: 0.1465 - rmse: 0.1926 - smape: 0.3412 - val_ia: 0.7660 - val_loss: 0.0231 - val_mae: 0.1115 - val_rmse: 0.1407 - val_smape: 0.2585

Epoch 4/16

1147/1147 - 42s - 37ms/step - ia: 0.9166 - loss: 0.0326 - mae: 0.1337 - rmse: 0.1774 - smape: 0.3147 - val_ia: 0.7414 - val_loss: 0.0278 - val_mae: 0.1266 - val_rmse: 0.1537 - val_smape: 0.2787

Epoch 5/16

1147/1147 - 23s - 20ms/step - ia: 0.9215 - loss: 0.0291 - mae: 0.1261 - rmse: 0.1675 - smape: 0.2970 - val_ia: 0.7929 - val_loss: 0.0190 - val_mae: 0.0988 - val_rmse: 0.1269 - val_smape: 0.2427

Epoch 6/16

1147/1147 - 23s - 20ms/step - ia: 0.9249 - loss: 0.0268 - mae: 0.1208 - rmse: 0.1605 - smape: 0.2875 - val_ia: 0.7340 - val_loss: 0.0296 - val_mae: 0.1308 - val_rmse: 0.1562 - val_smape: 0.3090

Epoch 7/16

1147/1147 - 23s - 20ms/step - ia: 0.9273 - loss: 0.0250 - mae: 0.1167 - rmse: 0.1551 - smape: 0.2773 - val_ia: 0.7619 - val_loss: 0.0231 - val_mae: 0.1166 - val_rmse: 0.1405 - val_smape: 0.2695

Epoch 8/16

1147/1147 - 23s - 20ms/step - ia: 0.9296 - loss: 0.0237 - mae: 0.1132 - rmse: 0.1509 - smape: 0.2678 - val_ia: 0.7989 - val_loss: 0.0164 - val_mae: 0.0924 - val_rmse: 0.1165 - val_smape: 0.2347

Epoch 9/16

1147/1147 - 22s - 19ms/step - ia: 0.9304 - loss: 0.0232 - mae: 0.1117 - rmse: 0.1494 - smape: 0.2643 - val_ia: 0.8006 - val_loss: 0.0157 - val_mae: 0.0943 - val_rmse: 0.1162 - val_smape: 0.2399

Epoch 10/16

1147/1147 - 19s - 17ms/step - ia: 0.9323 - loss: 0.0220 - mae: 0.1088 - rmse: 0.1453 - smape: 0.2580 - val_ia: 0.7947 - val_loss: 0.0151 - val_mae: 0.0936 - val_rmse: 0.1140 - val_smape: 0.2259

Epoch 11/16

1147/1147 - 20s - 17ms/step - ia: 0.9339 - loss: 0.0211 - mae: 0.1063 - rmse: 0.1424 - smape: 0.2531 - val_ia: 0.7582 - val_loss: 0.0212 - val_mae: 0.1144 - val_rmse: 0.1343 - val_smape: 0.2753

Epoch 12/16

1147/1147 - 21s - 18ms/step - ia: 0.9345 - loss: 0.0207 - mae: 0.1053 - rmse: 0.1411 - smape: 0.2507 - val_ia: 0.8230 - val_loss: 0.0126 - val_mae: 0.0808 - val_rmse: 0.1022 - val_smape: 0.2252

Epoch 13/16

1147/1147 - 19s - 17ms/step - ia: 0.9348 - loss: 0.0204 - mae: 0.1048 - rmse: 0.1400 - smape: 0.2487 - val_ia: 0.7840 - val_loss: 0.0165 - val_mae: 0.0989 - val_rmse: 0.1186 - val_smape: 0.2381

Epoch 14/16

1147/1147 - 20s - 18ms/step - ia: 0.9359 - loss: 0.0199 - mae: 0.1031 - rmse: 0.1382 - smape: 0.2435 - val_ia: 0.8180 - val_loss: 0.0111 - val_mae: 0.0799 - val_rmse: 0.0967 - val_smape: 0.2028

Epoch 15/16

1147/1147 - 19s - 16ms/step - ia: 0.9368 - loss: 0.0195 - mae: 0.1018 - rmse: 0.1366 - smape: 0.2415 - val_ia: 0.8291 - val_loss: 0.0117 - val_mae: 0.0808 - val_rmse: 0.1009 - val_smape: 0.2197

Epoch 16/16

1147/1147 - 17s - 15ms/step - ia: 0.9366 - loss: 0.0195 - mae: 0.1020 - rmse: 0.1368 - smape: 0.2392 - val_ia: 0.8089 - val_loss: 0.0136 - val_mae: 0.0872 - val_rmse: 0.1066 - val_smape: 0.2307

Restoring model weights from the end of the best epoch: 14.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:36 596ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 20%|██        | 10/50 [1:54:47<5:11:30, 467.27s/trial, best loss: 0.0036979985241071406]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 14s - 48ms/step - ia: 0.0508 - loss: 7.9718 - mae: 1.8165 - rmse: 2.7569 - smape: 1.7702 - val_ia: 0.0722 - val_loss: 4.2508 - val_mae: 1.6000 - val_rmse: 1.9740 - val_smape: 1.8494

Epoch 2/8

287/287 - 3s - 9ms/step - ia: 0.0526 - loss: 7.6311 - mae: 1.7772 - rmse: 2.6844 - smape: 1.7663 - val_ia: 0.0732 - val_loss: 4.1306 - val_mae: 1.5801 - val_rmse: 1.9474 - val_smape: 1.8511

Epoch 3/8

287/287 - 3s - 10ms/step - ia: 0.0528 - loss: 7.2617 - mae: 1.7554 - rmse: 2.6359 - smape: 1.7682 - val_ia: 0.0742 - val_loss: 4.0199 - val_mae: 1.5613 - val_rmse: 1.9226 - val_smape: 1.8526

Epoch 4/8

287/287 - 3s - 11ms/step - ia: 0.0540 - loss: 6.8249 - mae: 1.7235 - rmse: 2.5473 - smape: 1.7684 - val_ia: 0.0752 - val_loss: 3.9102 - val_mae: 1.5425 - val_rmse: 1.8976 - val_smape: 1.8540

Epoch 5/8

287/287 - 3s - 12ms/step - ia: 0.0549 - loss: 6.8931 - mae: 1.7086 - rmse: 2.5587 - smape: 1.7644 - val_ia: 0.0762 - val_loss: 3.8063 - val_mae: 1.5244 - val_rmse: 1.8735 - val_smape: 1.8551

Epoch 6/8

287/287 - 3s - 12ms/step - ia: 0.0557 - loss: 6.6273 - mae: 1.6810 - rmse: 2.5055 - smape: 1.7622 - val_ia: 0.0773 - val_loss: 3.7093 - val_mae: 1.5071 - val_rmse: 1.8508 - val_smape: 1.8561

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.0566 - loss: 6.3812 - mae: 1.6615 - rmse: 2.4708 - smape: 1.7621 - val_ia: 0.0784 - val_loss: 3.6120 - val_mae: 1.4895 - val_rmse: 1.8276 - val_smape: 1.8569

Epoch 8/8

287/287 - 3s - 9ms/step - ia: 0.0580 - loss: 5.9459 - mae: 1.6319 - rmse: 2.3840 - smape: 1.7629 - val_ia: 0.0795 - val_loss: 3.5217 - val_mae: 1.4729 - val_rmse: 1.8058 - val_smape: 1.8573

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:32 570ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

Epoch 1/128

 22%|██▏       | 11/50 [1:55:24<3:38:09, 335.63s/trial, best loss: 0.0036979985241071406]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 19s - 16ms/step - ia: 0.7861 - loss: 0.1789 - mae: 0.3098 - rmse: 0.3881 - smape: 0.6547 - val_ia: 0.6235 - val_loss: 0.0943 - val_mae: 0.2398 - val_rmse: 0.2707 - val_smape: 0.5627

Epoch 2/128

1147/1147 - 11s - 10ms/step - ia: 0.8884 - loss: 0.0533 - mae: 0.1785 - rmse: 0.2273 - smape: 0.4329 - val_ia: 0.7554 - val_loss: 0.0265 - val_mae: 0.1272 - val_rmse: 0.1492 - val_smape: 0.3563

Epoch 3/128

1147/1147 - 10s - 8ms/step - ia: 0.9148 - loss: 0.0317 - mae: 0.1372 - rmse: 0.1753 - smape: 0.3521 - val_ia: 0.8081 - val_loss: 0.0134 - val_mae: 0.0883 - val_rmse: 0.1086 - val_smape: 0.2606

Epoch 4/128

1147/1147 - 9s - 8ms/step - ia: 0.9264 - loss: 0.0240 - mae: 0.1187 - rmse: 0.1526 - smape: 0.3098 - val_ia: 0.8091 - val_loss: 0.0128 - val_mae: 0.0864 - val_rmse: 0.1061 - val_smape: 0.2567

Epoch 5/128

1147/1147 - 9s - 8ms/step - ia: 0.9327 - loss: 0.0202 - mae: 0.1085 - rmse: 0.1399 - smape: 0.2873 - val_ia: 0.8432 - val_loss: 0.0094 - val_mae: 0.0696 - val_rmse: 0.0899 - val_smape: 0.2005

Epoch 6/128

1147/1147 - 9s - 8ms/step - ia: 0.9371 - loss: 0.0181 - mae: 0.1013 - rmse: 0.1321 - smape: 0.2705 - val_ia: 0.8338 - val_loss: 0.0100 - val_mae: 0.0734 - val_rmse: 0.0931 - val_smape: 0.2115

Epoch 7/128

1147/1147 - 9s - 8ms/step - ia: 0.9412 - loss: 0.0160 - mae: 0.0946 - rmse: 0.1241 - smape: 0.2552 - val_ia: 0.8399 - val_loss: 0.0093 - val_mae: 0.0702 - val_rmse: 0.0897 - val_smape: 0.1912

Epoch 8/128

1147/1147 - 9s - 8ms/step - ia: 0.9435 - loss: 0.0148 - mae: 0.0907 - rmse: 0.1190 - smape: 0.2454 - val_ia: 0.8701 - val_loss: 0.0067 - val_mae: 0.0572 - val_rmse: 0.0756 - val_smape: 0.1660

Epoch 9/128

1147/1147 - 10s - 8ms/step - ia: 0.9454 - loss: 0.0140 - mae: 0.0879 - rmse: 0.1156 - smape: 0.2373 - val_ia: 0.8526 - val_loss: 0.0077 - val_mae: 0.0640 - val_rmse: 0.0817 - val_smape: 0.1855

Epoch 10/128

1147/1147 - 11s - 9ms/step - ia: 0.9472 - loss: 0.0132 - mae: 0.0851 - rmse: 0.1121 - smape: 0.2301 - val_ia: 0.8565 - val_loss: 0.0072 - val_mae: 0.0621 - val_rmse: 0.0794 - val_smape: 0.1805

Epoch 11/128

1147/1147 - 10s - 9ms/step - ia: 0.9480 - loss: 0.0127 - mae: 0.0838 - rmse: 0.1101 - smape: 0.2285 - val_ia: 0.8571 - val_loss: 0.0070 - val_mae: 0.0618 - val_rmse: 0.0785 - val_smape: 0.1865

Epoch 12/128

1147/1147 - 11s - 9ms/step - ia: 0.9491 - loss: 0.0122 - mae: 0.0820 - rmse: 0.1080 - smape: 0.2232 - val_ia: 0.8638 - val_loss: 0.0065 - val_mae: 0.0589 - val_rmse: 0.0754 - val_smape: 0.1722

Epoch 13/128

1147/1147 - 10s - 9ms/step - ia: 0.9504 - loss: 0.0117 - mae: 0.0799 - rmse: 0.1057 - smape: 0.2177 - val_ia: 0.8472 - val_loss: 0.0074 - val_mae: 0.0647 - val_rmse: 0.0807 - val_smape: 0.1881

Epoch 14/128

1147/1147 - 11s - 10ms/step - ia: 0.9513 - loss: 0.0113 - mae: 0.0786 - rmse: 0.1038 - smape: 0.2155 - val_ia: 0.8535 - val_loss: 0.0070 - val_mae: 0.0624 - val_rmse: 0.0784 - val_smape: 0.1765

Epoch 15/128

1147/1147 - 20s - 17ms/step - ia: 0.9516 - loss: 0.0111 - mae: 0.0779 - rmse: 0.1029 - smape: 0.2125 - val_ia: 0.8572 - val_loss: 0.0066 - val_mae: 0.0602 - val_rmse: 0.0758 - val_smape: 0.1717

Epoch 16/128

1147/1147 - 11s - 9ms/step - ia: 0.9521 - loss: 0.0109 - mae: 0.0770 - rmse: 0.1017 - smape: 0.2099 - val_ia: 0.8585 - val_loss: 0.0065 - val_mae: 0.0599 - val_rmse: 0.0757 - val_smape: 0.1664

Epoch 17/128

1147/1147 - 11s - 9ms/step - ia: 0.9529 - loss: 0.0107 - mae: 0.0761 - rmse: 0.1005 - smape: 0.2079 - val_ia: 0.8751 - val_loss: 0.0053 - val_mae: 0.0533 - val_rmse: 0.0687 - val_smape: 0.1566

Epoch 18/128

1147/1147 - 10s - 9ms/step - ia: 0.9531 - loss: 0.0105 - mae: 0.0754 - rmse: 0.0999 - smape: 0.2065 - val_ia: 0.8841 - val_loss: 0.0048 - val_mae: 0.0503 - val_rmse: 0.0654 - val_smape: 0.1482

Epoch 19/128

1147/1147 - 11s - 9ms/step - ia: 0.9538 - loss: 0.0103 - mae: 0.0744 - rmse: 0.0988 - smape: 0.2040 - val_ia: 0.8610 - val_loss: 0.0060 - val_mae: 0.0584 - val_rmse: 0.0730 - val_smape: 0.1712

Epoch 20/128

1147/1147 - 10s - 9ms/step - ia: 0.9539 - loss: 0.0103 - mae: 0.0742 - rmse: 0.0986 - smape: 0.2037 - val_ia: 0.8715 - val_loss: 0.0055 - val_mae: 0.0548 - val_rmse: 0.0699 - val_smape: 0.1532

Epoch 21/128

1147/1147 - 10s - 9ms/step - ia: 0.9541 - loss: 0.0101 - mae: 0.0740 - rmse: 0.0980 - smape: 0.2008 - val_ia: 0.8744 - val_loss: 0.0053 - val_mae: 0.0536 - val_rmse: 0.0686 - val_smape: 0.1551

Epoch 22/128

1147/1147 - 10s - 9ms/step - ia: 0.9549 - loss: 0.0099 - mae: 0.0729 - rmse: 0.0966 - smape: 0.2012 - val_ia: 0.8699 - val_loss: 0.0054 - val_mae: 0.0548 - val_rmse: 0.0690 - val_smape: 0.1715

Epoch 23/128

1147/1147 - 21s - 18ms/step - ia: 0.9550 - loss: 0.0098 - mae: 0.0726 - rmse: 0.0963 - smape: 0.1988 - val_ia: 0.8593 - val_loss: 0.0060 - val_mae: 0.0585 - val_rmse: 0.0724 - val_smape: 0.1748

Epoch 24/128

1147/1147 - 10s - 9ms/step - ia: 0.9554 - loss: 0.0096 - mae: 0.0721 - rmse: 0.0955 - smape: 0.1970 - val_ia: 0.8787 - val_loss: 0.0048 - val_mae: 0.0512 - val_rmse: 0.0654 - val_smape: 0.1566

Epoch 25/128

1147/1147 - 11s - 9ms/step - ia: 0.9556 - loss: 0.0096 - mae: 0.0717 - rmse: 0.0954 - smape: 0.1976 - val_ia: 0.8732 - val_loss: 0.0051 - val_mae: 0.0534 - val_rmse: 0.0673 - val_smape: 0.1674

Epoch 26/128

1147/1147 - 9s - 8ms/step - ia: 0.9555 - loss: 0.0096 - mae: 0.0717 - rmse: 0.0951 - smape: 0.1972 - val_ia: 0.8759 - val_loss: 0.0049 - val_mae: 0.0521 - val_rmse: 0.0659 - val_smape: 0.1599

Epoch 27/128

1147/1147 - 9s - 8ms/step - ia: 0.9560 - loss: 0.0096 - mae: 0.0711 - rmse: 0.0949 - smape: 0.1959 - val_ia: 0.8917 - val_loss: 0.0041 - val_mae: 0.0465 - val_rmse: 0.0601 - val_smape: 0.1467

Epoch 28/128

1147/1147 - 10s - 8ms/step - ia: 0.9560 - loss: 0.0095 - mae: 0.0711 - rmse: 0.0947 - smape: 0.1936 - val_ia: 0.8827 - val_loss: 0.0045 - val_mae: 0.0490 - val_rmse: 0.0627 - val_smape: 0.1482

Epoch 29/128

1147/1147 - 10s - 8ms/step - ia: 0.9564 - loss: 0.0092 - mae: 0.0702 - rmse: 0.0933 - smape: 0.1930 - val_ia: 0.8852 - val_loss: 0.0044 - val_mae: 0.0490 - val_rmse: 0.0627 - val_smape: 0.1493

Epoch 30/128

1147/1147 - 10s - 9ms/step - ia: 0.9570 - loss: 0.0091 - mae: 0.0696 - rmse: 0.0929 - smape: 0.1911 - val_ia: 0.8808 - val_loss: 0.0046 - val_mae: 0.0500 - val_rmse: 0.0633 - val_smape: 0.1594

Epoch 31/128

1147/1147 - 10s - 9ms/step - ia: 0.9567 - loss: 0.0091 - mae: 0.0698 - rmse: 0.0929 - smape: 0.1937 - val_ia: 0.8769 - val_loss: 0.0047 - val_mae: 0.0510 - val_rmse: 0.0643 - val_smape: 0.1584

Epoch 32/128

1147/1147 - 9s - 8ms/step - ia: 0.9566 - loss: 0.0092 - mae: 0.0701 - rmse: 0.0930 - smape: 0.1917 - val_ia: 0.8927 - val_loss: 0.0040 - val_mae: 0.0457 - val_rmse: 0.0592 - val_smape: 0.1433

Epoch 33/128

1147/1147 - 9s - 8ms/step - ia: 0.9573 - loss: 0.0090 - mae: 0.0689 - rmse: 0.0920 - smape: 0.1898 - val_ia: 0.8732 - val_loss: 0.0050 - val_mae: 0.0530 - val_rmse: 0.0665 - val_smape: 0.1527

Epoch 34/128

1147/1147 - 10s - 9ms/step - ia: 0.9575 - loss: 0.0088 - mae: 0.0685 - rmse: 0.0912 - smape: 0.1887 - val_ia: 0.8921 - val_loss: 0.0040 - val_mae: 0.0464 - val_rmse: 0.0596 - val_smape: 0.1536

Epoch 35/128

1147/1147 - 9s - 8ms/step - ia: 0.9572 - loss: 0.0091 - mae: 0.0692 - rmse: 0.0925 - smape: 0.1897 - val_ia: 0.8723 - val_loss: 0.0049 - val_mae: 0.0527 - val_rmse: 0.0659 - val_smape: 0.1580

Epoch 36/128

1147/1147 - 9s - 8ms/step - ia: 0.9573 - loss: 0.0089 - mae: 0.0688 - rmse: 0.0916 - smape: 0.1894 - val_ia: 0.8783 - val_loss: 0.0046 - val_mae: 0.0508 - val_rmse: 0.0638 - val_smape: 0.1560

Epoch 37/128

1147/1147 - 10s - 8ms/step - ia: 0.9578 - loss: 0.0088 - mae: 0.0682 - rmse: 0.0907 - smape: 0.1885 - val_ia: 0.8640 - val_loss: 0.0054 - val_mae: 0.0556 - val_rmse: 0.0685 - val_smape: 0.1582

Epoch 38/128

1147/1147 - 12s - 10ms/step - ia: 0.9577 - loss: 0.0088 - mae: 0.0683 - rmse: 0.0913 - smape: 0.1888 - val_ia: 0.8911 - val_loss: 0.0039 - val_mae: 0.0460 - val_rmse: 0.0592 - val_smape: 0.1429

Epoch 39/128

1147/1147 - 19s - 16ms/step - ia: 0.9576 - loss: 0.0089 - mae: 0.0683 - rmse: 0.0913 - smape: 0.1870 - val_ia: 0.8930 - val_loss: 0.0039 - val_mae: 0.0459 - val_rmse: 0.0589 - val_smape: 0.1455

Epoch 40/128

1147/1147 - 11s - 10ms/step - ia: 0.9581 - loss: 0.0087 - mae: 0.0678 - rmse: 0.0905 - smape: 0.1872 - val_ia: 0.8930 - val_loss: 0.0038 - val_mae: 0.0454 - val_rmse: 0.0585 - val_smape: 0.1412

Epoch 41/128

1147/1147 - 20s - 17ms/step - ia: 0.9577 - loss: 0.0088 - mae: 0.0681 - rmse: 0.0908 - smape: 0.1889 - val_ia: 0.8748 - val_loss: 0.0047 - val_mae: 0.0517 - val_rmse: 0.0640 - val_smape: 0.1593

Epoch 42/128

1147/1147 - 11s - 10ms/step - ia: 0.9579 - loss: 0.0088 - mae: 0.0680 - rmse: 0.0909 - smape: 0.1863 - val_ia: 0.8999 - val_loss: 0.0035 - val_mae: 0.0434 - val_rmse: 0.0563 - val_smape: 0.1380

Epoch 43/128

1147/1147 - 20s - 18ms/step - ia: 0.9582 - loss: 0.0086 - mae: 0.0674 - rmse: 0.0900 - smape: 0.1845 - val_ia: 0.8815 - val_loss: 0.0044 - val_mae: 0.0496 - val_rmse: 0.0622 - val_smape: 0.1636

Epoch 44/128

1147/1147 - 10s - 9ms/step - ia: 0.9581 - loss: 0.0087 - mae: 0.0678 - rmse: 0.0906 - smape: 0.1855 - val_ia: 0.8844 - val_loss: 0.0042 - val_mae: 0.0477 - val_rmse: 0.0603 - val_smape: 0.1482

Epoch 45/128

1147/1147 - 10s - 9ms/step - ia: 0.9583 - loss: 0.0086 - mae: 0.0674 - rmse: 0.0899 - smape: 0.1853 - val_ia: 0.8861 - val_loss: 0.0043 - val_mae: 0.0490 - val_rmse: 0.0621 - val_smape: 0.1434

Epoch 46/128

1147/1147 - 11s - 9ms/step - ia: 0.9585 - loss: 0.0085 - mae: 0.0669 - rmse: 0.0897 - smape: 0.1835 - val_ia: 0.8928 - val_loss: 0.0039 - val_mae: 0.0459 - val_rmse: 0.0589 - val_smape: 0.1414

Epoch 47/128

1147/1147 - 11s - 10ms/step - ia: 0.9583 - loss: 0.0085 - mae: 0.0673 - rmse: 0.0898 - smape: 0.1846 - val_ia: 0.8918 - val_loss: 0.0039 - val_mae: 0.0458 - val_rmse: 0.0587 - val_smape: 0.1414

Epoch 48/128

1147/1147 - 11s - 10ms/step - ia: 0.9587 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0895 - smape: 0.1829 - val_ia: 0.8712 - val_loss: 0.0048 - val_mae: 0.0526 - val_rmse: 0.0650 - val_smape: 0.1585

Epoch 49/128

1147/1147 - 11s - 10ms/step - ia: 0.9583 - loss: 0.0086 - mae: 0.0672 - rmse: 0.0900 - smape: 0.1848 - val_ia: 0.8957 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0585 - val_smape: 0.1427

Epoch 50/128

1147/1147 - 11s - 10ms/step - ia: 0.9586 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0895 - smape: 0.1834 - val_ia: 0.8875 - val_loss: 0.0040 - val_mae: 0.0467 - val_rmse: 0.0594 - val_smape: 0.1412

Epoch 51/128

1147/1147 - 11s - 10ms/step - ia: 0.9584 - loss: 0.0085 - mae: 0.0670 - rmse: 0.0893 - smape: 0.1832 - val_ia: 0.8984 - val_loss: 0.0035 - val_mae: 0.0433 - val_rmse: 0.0558 - val_smape: 0.1418

Epoch 52/128

1147/1147 - 11s - 10ms/step - ia: 0.9590 - loss: 0.0084 - mae: 0.0661 - rmse: 0.0889 - smape: 0.1820 - val_ia: 0.8968 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0568 - val_smape: 0.1379

Epoch 53/128

1147/1147 - 11s - 9ms/step - ia: 0.9589 - loss: 0.0084 - mae: 0.0663 - rmse: 0.0890 - smape: 0.1807 - val_ia: 0.8721 - val_loss: 0.0050 - val_mae: 0.0539 - val_rmse: 0.0667 - val_smape: 0.1556

Epoch 54/128

1147/1147 - 11s - 10ms/step - ia: 0.9590 - loss: 0.0083 - mae: 0.0661 - rmse: 0.0883 - smape: 0.1819 - val_ia: 0.8795 - val_loss: 0.0043 - val_mae: 0.0493 - val_rmse: 0.0619 - val_smape: 0.1444

Epoch 55/128

1147/1147 - 11s - 10ms/step - ia: 0.9590 - loss: 0.0083 - mae: 0.0662 - rmse: 0.0885 - smape: 0.1813 - val_ia: 0.8899 - val_loss: 0.0039 - val_mae: 0.0462 - val_rmse: 0.0586 - val_smape: 0.1522

Epoch 56/128

1147/1147 - 11s - 10ms/step - ia: 0.9593 - loss: 0.0082 - mae: 0.0656 - rmse: 0.0876 - smape: 0.1804 - val_ia: 0.9051 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0539 - val_smape: 0.1348

Epoch 57/128

1147/1147 - 11s - 10ms/step - ia: 0.9592 - loss: 0.0082 - mae: 0.0658 - rmse: 0.0881 - smape: 0.1818 - val_ia: 0.8970 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0563 - val_smape: 0.1385

Epoch 58/128

1147/1147 - 11s - 10ms/step - ia: 0.9593 - loss: 0.0083 - mae: 0.0659 - rmse: 0.0885 - smape: 0.1813 - val_ia: 0.8960 - val_loss: 0.0037 - val_mae: 0.0440 - val_rmse: 0.0566 - val_smape: 0.1433

Epoch 59/128

1147/1147 - 11s - 10ms/step - ia: 0.9591 - loss: 0.0083 - mae: 0.0661 - rmse: 0.0884 - smape: 0.1822 - val_ia: 0.8978 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0564 - val_smape: 0.1394

Epoch 60/128

1147/1147 - 11s - 10ms/step - ia: 0.9590 - loss: 0.0083 - mae: 0.0660 - rmse: 0.0885 - smape: 0.1802 - val_ia: 0.8851 - val_loss: 0.0041 - val_mae: 0.0475 - val_rmse: 0.0596 - val_smape: 0.1509

Epoch 61/128

1147/1147 - 11s - 10ms/step - ia: 0.9594 - loss: 0.0081 - mae: 0.0655 - rmse: 0.0874 - smape: 0.1811 - val_ia: 0.8986 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0556 - val_smape: 0.1365

Epoch 62/128

1147/1147 - 11s - 9ms/step - ia: 0.9592 - loss: 0.0083 - mae: 0.0658 - rmse: 0.0883 - smape: 0.1786 - val_ia: 0.8924 - val_loss: 0.0040 - val_mae: 0.0469 - val_rmse: 0.0598 - val_smape: 0.1419

Epoch 63/128

1147/1147 - 11s - 9ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0654 - rmse: 0.0877 - smape: 0.1802 - val_ia: 0.8935 - val_loss: 0.0036 - val_mae: 0.0444 - val_rmse: 0.0571 - val_smape: 0.1403

Epoch 64/128

1147/1147 - 11s - 10ms/step - ia: 0.9597 - loss: 0.0081 - mae: 0.0651 - rmse: 0.0872 - smape: 0.1791 - val_ia: 0.8792 - val_loss: 0.0044 - val_mae: 0.0496 - val_rmse: 0.0619 - val_smape: 0.1495

Epoch 65/128

1147/1147 - 11s - 10ms/step - ia: 0.9595 - loss: 0.0082 - mae: 0.0654 - rmse: 0.0877 - smape: 0.1799 - val_ia: 0.8889 - val_loss: 0.0040 - val_mae: 0.0471 - val_rmse: 0.0597 - val_smape: 0.1454

Epoch 66/128

1147/1147 - 11s - 10ms/step - ia: 0.9595 - loss: 0.0082 - mae: 0.0654 - rmse: 0.0878 - smape: 0.1783 - val_ia: 0.8891 - val_loss: 0.0039 - val_mae: 0.0458 - val_rmse: 0.0579 - val_smape: 0.1428

Epoch 67/128

1147/1147 - 11s - 9ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0651 - rmse: 0.0876 - smape: 0.1778 - val_ia: 0.8963 - val_loss: 0.0039 - val_mae: 0.0463 - val_rmse: 0.0591 - val_smape: 0.1418

Epoch 68/128

1147/1147 - 10s - 8ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0652 - rmse: 0.0875 - smape: 0.1786 - val_ia: 0.8958 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0567 - val_smape: 0.1394

Epoch 69/128

1147/1147 - 10s - 8ms/step - ia: 0.9597 - loss: 0.0080 - mae: 0.0649 - rmse: 0.0868 - smape: 0.1779 - val_ia: 0.8902 - val_loss: 0.0038 - val_mae: 0.0456 - val_rmse: 0.0579 - val_smape: 0.1433

Epoch 70/128

1147/1147 - 9s - 8ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0652 - rmse: 0.0875 - smape: 0.1787 - val_ia: 0.8870 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0588 - val_smape: 0.1517

Epoch 71/128

1147/1147 - 10s - 9ms/step - ia: 0.9596 - loss: 0.0082 - mae: 0.0653 - rmse: 0.0876 - smape: 0.1776 - val_ia: 0.9025 - val_loss: 0.0035 - val_mae: 0.0433 - val_rmse: 0.0559 - val_smape: 0.1393

Epoch 71: early stopping

Restoring model weights from the end of the best epoch: 56.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:05 772ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 24%|██▍       | 12/50 [2:08:40<5:01:16, 475.71s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 28s - 97ms/step - ia: 0.7879 - loss: 0.1779 - mae: 0.3121 - rmse: 0.3999 - smape: 0.6549 - val_ia: 0.8405 - val_loss: 0.0728 - val_mae: 0.2107 - val_rmse: 0.2618 - val_smape: 0.5323

Epoch 2/16

287/287 - 5s - 16ms/step - ia: 0.8900 - loss: 0.0556 - mae: 0.1781 - rmse: 0.2343 - smape: 0.4196 - val_ia: 0.9006 - val_loss: 0.0312 - val_mae: 0.1346 - val_rmse: 0.1734 - val_smape: 0.3722

Epoch 3/16

287/287 - 5s - 17ms/step - ia: 0.9098 - loss: 0.0390 - mae: 0.1471 - rmse: 0.1965 - smape: 0.3524 - val_ia: 0.9167 - val_loss: 0.0225 - val_mae: 0.1108 - val_rmse: 0.1458 - val_smape: 0.2873

Epoch 4/16

287/287 - 5s - 18ms/step - ia: 0.9198 - loss: 0.0312 - mae: 0.1311 - rmse: 0.1756 - smape: 0.3180 - val_ia: 0.9119 - val_loss: 0.0248 - val_mae: 0.1169 - val_rmse: 0.1485 - val_smape: 0.3136

Epoch 5/16

287/287 - 5s - 17ms/step - ia: 0.9252 - loss: 0.0273 - mae: 0.1225 - rmse: 0.1643 - smape: 0.2973 - val_ia: 0.9288 - val_loss: 0.0165 - val_mae: 0.0945 - val_rmse: 0.1242 - val_smape: 0.2347

Epoch 6/16

287/287 - 5s - 17ms/step - ia: 0.9297 - loss: 0.0244 - mae: 0.1152 - rmse: 0.1550 - smape: 0.2787 - val_ia: 0.9382 - val_loss: 0.0129 - val_mae: 0.0822 - val_rmse: 0.1102 - val_smape: 0.2109

Epoch 7/16

287/287 - 5s - 16ms/step - ia: 0.9330 - loss: 0.0223 - mae: 0.1099 - rmse: 0.1484 - smape: 0.2662 - val_ia: 0.9389 - val_loss: 0.0120 - val_mae: 0.0811 - val_rmse: 0.1057 - val_smape: 0.2100

Epoch 8/16

287/287 - 5s - 18ms/step - ia: 0.9355 - loss: 0.0206 - mae: 0.1057 - rmse: 0.1425 - smape: 0.2574 - val_ia: 0.9446 - val_loss: 0.0101 - val_mae: 0.0731 - val_rmse: 0.0976 - val_smape: 0.1905

Epoch 9/16

287/287 - 5s - 17ms/step - ia: 0.9376 - loss: 0.0197 - mae: 0.1025 - rmse: 0.1392 - smape: 0.2494 - val_ia: 0.9479 - val_loss: 0.0091 - val_mae: 0.0694 - val_rmse: 0.0937 - val_smape: 0.1872

Epoch 10/16

287/287 - 5s - 18ms/step - ia: 0.9384 - loss: 0.0191 - mae: 0.1011 - rmse: 0.1371 - smape: 0.2439 - val_ia: 0.9493 - val_loss: 0.0085 - val_mae: 0.0678 - val_rmse: 0.0906 - val_smape: 0.1743

Epoch 11/16

287/287 - 5s - 17ms/step - ia: 0.9401 - loss: 0.0181 - mae: 0.0983 - rmse: 0.1334 - smape: 0.2360 - val_ia: 0.9470 - val_loss: 0.0090 - val_mae: 0.0702 - val_rmse: 0.0921 - val_smape: 0.1785

Epoch 12/16

287/287 - 5s - 17ms/step - ia: 0.9415 - loss: 0.0175 - mae: 0.0960 - rmse: 0.1313 - smape: 0.2307 - val_ia: 0.9572 - val_loss: 0.0064 - val_mae: 0.0575 - val_rmse: 0.0790 - val_smape: 0.1581

Epoch 13/16

287/287 - 5s - 18ms/step - ia: 0.9430 - loss: 0.0165 - mae: 0.0936 - rmse: 0.1276 - smape: 0.2258 - val_ia: 0.9579 - val_loss: 0.0060 - val_mae: 0.0573 - val_rmse: 0.0767 - val_smape: 0.1604

Epoch 14/16

287/287 - 5s - 16ms/step - ia: 0.9444 - loss: 0.0159 - mae: 0.0913 - rmse: 0.1251 - smape: 0.2223 - val_ia: 0.9579 - val_loss: 0.0060 - val_mae: 0.0562 - val_rmse: 0.0761 - val_smape: 0.1505

Epoch 15/16

287/287 - 5s - 18ms/step - ia: 0.9451 - loss: 0.0155 - mae: 0.0900 - rmse: 0.1237 - smape: 0.2177 - val_ia: 0.9555 - val_loss: 0.0067 - val_mae: 0.0595 - val_rmse: 0.0808 - val_smape: 0.1531

Epoch 16/16

287/287 - 5s - 17ms/step - ia: 0.9457 - loss: 0.0152 - mae: 0.0890 - rmse: 0.1221 - smape: 0.2153 - val_ia: 0.9655 - val_loss: 0.0044 - val_mae: 0.0463 - val_rmse: 0.0645 - val_smape: 0.1359

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 7:06 3s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step

 26%|██▌       | 13/50 [2:10:28<3:44:39, 364.30s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 15s - 53ms/step - ia: 0.6975 - loss: 0.2999 - mae: 0.4214 - rmse: 0.5321 - smape: 0.8419 - val_ia: 0.7781 - val_loss: 0.1520 - val_mae: 0.3012 - val_rmse: 0.3861 - val_smape: 0.6755

Epoch 2/8

287/287 - 3s - 10ms/step - ia: 0.8190 - loss: 0.1390 - mae: 0.2865 - rmse: 0.3710 - smape: 0.5925 - val_ia: 0.8072 - val_loss: 0.1197 - val_mae: 0.2710 - val_rmse: 0.3350 - val_smape: 0.6271

Epoch 3/8

287/287 - 3s - 10ms/step - ia: 0.8542 - loss: 0.0927 - mae: 0.2338 - rmse: 0.3032 - smape: 0.5088 - val_ia: 0.8497 - val_loss: 0.0692 - val_mae: 0.2075 - val_rmse: 0.2566 - val_smape: 0.5458

Epoch 4/8

287/287 - 5s - 18ms/step - ia: 0.8750 - loss: 0.0697 - mae: 0.2022 - rmse: 0.2631 - smape: 0.4577 - val_ia: 0.8791 - val_loss: 0.0448 - val_mae: 0.1646 - val_rmse: 0.2075 - val_smape: 0.4694

Epoch 5/8

287/287 - 3s - 10ms/step - ia: 0.8879 - loss: 0.0570 - mae: 0.1818 - rmse: 0.2379 - smape: 0.4206 - val_ia: 0.8968 - val_loss: 0.0336 - val_mae: 0.1395 - val_rmse: 0.1798 - val_smape: 0.4148

Epoch 6/8

287/287 - 3s - 10ms/step - ia: 0.8964 - loss: 0.0493 - mae: 0.1681 - rmse: 0.2211 - smape: 0.3973 - val_ia: 0.9085 - val_loss: 0.0272 - val_mae: 0.1242 - val_rmse: 0.1622 - val_smape: 0.3780

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.9028 - loss: 0.0440 - mae: 0.1580 - rmse: 0.2088 - smape: 0.3759 - val_ia: 0.9133 - val_loss: 0.0243 - val_mae: 0.1172 - val_rmse: 0.1531 - val_smape: 0.3517

Epoch 8/8

287/287 - 3s - 10ms/step - ia: 0.9079 - loss: 0.0401 - mae: 0.1498 - rmse: 0.1994 - smape: 0.3602 - val_ia: 0.9188 - val_loss: 0.0217 - val_mae: 0.1092 - val_rmse: 0.1447 - val_smape: 0.3193

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:18 855ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 28%|██▊       | 14/50 [2:11:08<2:39:52, 266.47s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

574/574 - 14s - 24ms/step - ia: 0.8871 - loss: 0.0647 - mae: 0.1793 - rmse: 0.2406 - smape: 0.3687 - val_ia: 0.9288 - val_loss: 0.0092 - val_mae: 0.0717 - val_rmse: 0.0935 - val_smape: 0.2185

Epoch 2/16

574/574 - 4s - 6ms/step - ia: 0.9102 - loss: 0.0409 - mae: 0.1447 - rmse: 0.2005 - smape: 0.2887 - val_ia: 0.9282 - val_loss: 0.0083 - val_mae: 0.0687 - val_rmse: 0.0880 - val_smape: 0.1963

Epoch 3/16

574/574 - 4s - 6ms/step - ia: 0.9135 - loss: 0.0393 - mae: 0.1397 - rmse: 0.1960 - smape: 0.2707 - val_ia: 0.9325 - val_loss: 0.0083 - val_mae: 0.0662 - val_rmse: 0.0877 - val_smape: 0.1660

Epoch 4/16

574/574 - 3s - 6ms/step - ia: 0.9143 - loss: 0.0386 - mae: 0.1383 - rmse: 0.1944 - smape: 0.2649 - val_ia: 0.9463 - val_loss: 0.0053 - val_mae: 0.0528 - val_rmse: 0.0706 - val_smape: 0.1579

Epoch 5/16

574/574 - 3s - 6ms/step - ia: 0.9157 - loss: 0.0379 - mae: 0.1362 - rmse: 0.1925 - smape: 0.2552 - val_ia: 0.9422 - val_loss: 0.0054 - val_mae: 0.0549 - val_rmse: 0.0708 - val_smape: 0.1524

Epoch 6/16

574/574 - 4s - 7ms/step - ia: 0.9168 - loss: 0.0376 - mae: 0.1343 - rmse: 0.1915 - smape: 0.2512 - val_ia: 0.9487 - val_loss: 0.0045 - val_mae: 0.0499 - val_rmse: 0.0649 - val_smape: 0.1602

Epoch 7/16

574/574 - 4s - 6ms/step - ia: 0.9172 - loss: 0.0369 - mae: 0.1336 - rmse: 0.1903 - smape: 0.2503 - val_ia: 0.9070 - val_loss: 0.0120 - val_mae: 0.0869 - val_rmse: 0.1053 - val_smape: 0.1912

Epoch 8/16

574/574 - 4s - 6ms/step - ia: 0.9175 - loss: 0.0366 - mae: 0.1333 - rmse: 0.1894 - smape: 0.2477 - val_ia: 0.9446 - val_loss: 0.0050 - val_mae: 0.0519 - val_rmse: 0.0680 - val_smape: 0.1377

Epoch 9/16

574/574 - 6s - 10ms/step - ia: 0.9177 - loss: 0.0366 - mae: 0.1333 - rmse: 0.1894 - smape: 0.2494 - val_ia: 0.9467 - val_loss: 0.0050 - val_mae: 0.0522 - val_rmse: 0.0685 - val_smape: 0.1353

Epoch 10/16

574/574 - 5s - 9ms/step - ia: 0.9177 - loss: 0.0364 - mae: 0.1332 - rmse: 0.1885 - smape: 0.2479 - val_ia: 0.9230 - val_loss: 0.0078 - val_mae: 0.0707 - val_rmse: 0.0843 - val_smape: 0.1965

Epoch 11/16

574/574 - 4s - 7ms/step - ia: 0.9170 - loss: 0.0369 - mae: 0.1340 - rmse: 0.1901 - smape: 0.2484 - val_ia: 0.9495 - val_loss: 0.0043 - val_mae: 0.0484 - val_rmse: 0.0633 - val_smape: 0.1441

Epoch 12/16

574/574 - 4s - 7ms/step - ia: 0.9175 - loss: 0.0368 - mae: 0.1332 - rmse: 0.1898 - smape: 0.2450 - val_ia: 0.9300 - val_loss: 0.0072 - val_mae: 0.0636 - val_rmse: 0.0799 - val_smape: 0.1496

Epoch 13/16

574/574 - 4s - 7ms/step - ia: 0.9183 - loss: 0.0364 - mae: 0.1321 - rmse: 0.1889 - smape: 0.2434 - val_ia: 0.9460 - val_loss: 0.0050 - val_mae: 0.0522 - val_rmse: 0.0685 - val_smape: 0.1364

Epoch 14/16

574/574 - 4s - 7ms/step - ia: 0.9180 - loss: 0.0363 - mae: 0.1325 - rmse: 0.1887 - smape: 0.2452 - val_ia: 0.9396 - val_loss: 0.0056 - val_mae: 0.0567 - val_rmse: 0.0718 - val_smape: 0.1491

Epoch 15/16

574/574 - 4s - 7ms/step - ia: 0.9181 - loss: 0.0364 - mae: 0.1324 - rmse: 0.1887 - smape: 0.2434 - val_ia: 0.9374 - val_loss: 0.0059 - val_mae: 0.0584 - val_rmse: 0.0736 - val_smape: 0.1475

Epoch 16/16

574/574 - 4s - 6ms/step - ia: 0.9181 - loss: 0.0361 - mae: 0.1324 - rmse: 0.1883 - smape: 0.2440 - val_ia: 0.9232 - val_loss: 0.0085 - val_mae: 0.0718 - val_rmse: 0.0892 - val_smape: 0.1537

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 30%|███       | 15/50 [2:12:25<2:02:01, 209.18s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4586/4586 - 55s - 12ms/step - ia: 0.8760 - loss: 0.0647 - mae: 0.1799 - rmse: 0.2340 - smape: 0.3510 - val_ia: 0.4927 - val_loss: 0.0221 - val_mae: 0.1126 - val_rmse: 0.1217 - val_smape: 0.2418

Epoch 2/256

4586/4586 - 35s - 8ms/step - ia: 0.8917 - loss: 0.0504 - mae: 0.1588 - rmse: 0.2093 - smape: 0.3081 - val_ia: 0.5789 - val_loss: 0.0080 - val_mae: 0.0691 - val_rmse: 0.0788 - val_smape: 0.1754

Epoch 3/256

4586/4586 - 34s - 7ms/step - ia: 0.8911 - loss: 0.0511 - mae: 0.1596 - rmse: 0.2102 - smape: 0.3129 - val_ia: 0.5498 - val_loss: 0.0152 - val_mae: 0.0879 - val_rmse: 0.0985 - val_smape: 0.1878

Epoch 4/256

4586/4586 - 34s - 7ms/step - ia: 0.8930 - loss: 0.0480 - mae: 0.1568 - rmse: 0.2051 - smape: 0.3126 - val_ia: 0.5029 - val_loss: 0.0161 - val_mae: 0.1000 - val_rmse: 0.1104 - val_smape: 0.2398

Epoch 5/256

4586/4586 - 33s - 7ms/step - ia: 0.8817 - loss: 0.0657 - mae: 0.1715 - rmse: 0.2255 - smape: 0.3408 - val_ia: 0.5030 - val_loss: 0.0155 - val_mae: 0.0949 - val_rmse: 0.1055 - val_smape: 0.2254

Epoch 6/256

4586/4586 - 33s - 7ms/step - ia: 0.8891 - loss: 0.0523 - mae: 0.1627 - rmse: 0.2138 - smape: 0.3220 - val_ia: 0.5900 - val_loss: 0.0112 - val_mae: 0.0734 - val_rmse: 0.0832 - val_smape: 0.1596

Epoch 7/256

4586/4586 - 32s - 7ms/step - ia: 0.8640 - loss: 0.1073 - mae: 0.1980 - rmse: 0.2592 - smape: 0.3917 - val_ia: 0.4094 - val_loss: 0.0405 - val_mae: 0.1536 - val_rmse: 0.1681 - val_smape: 0.3538

Epoch 8/256

4586/4586 - 34s - 7ms/step - ia: 0.8610 - loss: 0.0761 - mae: 0.2021 - rmse: 0.2598 - smape: 0.4124 - val_ia: 0.4482 - val_loss: 0.0348 - val_mae: 0.1400 - val_rmse: 0.1526 - val_smape: 0.3476

Epoch 9/256

4586/4586 - 42s - 9ms/step - ia: 0.8869 - loss: 0.0525 - mae: 0.1654 - rmse: 0.2152 - smape: 0.3372 - val_ia: 0.4823 - val_loss: 0.0246 - val_mae: 0.1145 - val_rmse: 0.1261 - val_smape: 0.2513

Epoch 10/256

4586/4586 - 33s - 7ms/step - ia: 0.8950 - loss: 0.0459 - mae: 0.1535 - rmse: 0.2012 - smape: 0.3095 - val_ia: 0.4946 - val_loss: 0.0242 - val_mae: 0.1116 - val_rmse: 0.1218 - val_smape: 0.2031

Epoch 11/256

4586/4586 - 35s - 8ms/step - ia: 0.8968 - loss: 0.0453 - mae: 0.1514 - rmse: 0.1989 - smape: 0.3003 - val_ia: 0.4910 - val_loss: 0.0200 - val_mae: 0.1074 - val_rmse: 0.1170 - val_smape: 0.2449

Epoch 12/256

4586/4586 - 35s - 8ms/step - ia: 0.5312 - loss: 125016.2109 - mae: 6.9465 - rmse: 14.9537 - smape: 0.9956 - val_ia: 0.1964 - val_loss: 2.0826 - val_mae: 0.6579 - val_rmse: 0.7357 - val_smape: 1.1068

Epoch 13/256

4586/4586 - 35s - 8ms/step - ia: 0.3871 - loss: 9.1383 - mae: 1.0569 - rmse: 1.6841 - smape: 1.3282 - val_ia: 0.2033 - val_loss: 0.5838 - val_mae: 0.5229 - val_rmse: 0.5564 - val_smape: 0.9877

Epoch 14/256

4586/4586 - 33s - 7ms/step - ia: 0.4271 - loss: 3.1291 - mae: 0.7632 - rmse: 1.0894 - smape: 1.1837 - val_ia: 0.1890 - val_loss: 0.4379 - val_mae: 0.5345 - val_rmse: 0.5518 - val_smape: 1.0685

Epoch 15/256

4586/4586 - 35s - 8ms/step - ia: 0.4967 - loss: 0.5934 - mae: 0.5895 - rmse: 0.7384 - smape: 1.0665 - val_ia: 0.1997 - val_loss: 0.4058 - val_mae: 0.5103 - val_rmse: 0.5276 - val_smape: 1.0116

Epoch 16/256

4586/4586 - 34s - 7ms/step - ia: 0.4915 - loss: 0.8161 - mae: 0.5872 - rmse: 0.7366 - smape: 1.0632 - val_ia: 0.2045 - val_loss: 0.3683 - val_mae: 0.4904 - val_rmse: 0.5044 - val_smape: 0.9465

Epoch 17/256

4586/4586 - 32s - 7ms/step - ia: 0.7278 - loss: 0.2251 - mae: 0.3521 - rmse: 0.4412 - smape: 0.6735 - val_ia: 0.3721 - val_loss: 0.0818 - val_mae: 0.2084 - val_rmse: 0.2213 - val_smape: 0.3933

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:22 508ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4586/4586 - 83s - 18ms/step - ia: 0.8798 - loss: 0.0624 - mae: 0.1716 - rmse: 0.2124 - smape: 0.3914 - val_ia: 0.5524 - val_loss: 0.0104 - val_mae: 0.0760 - val_rmse: 0.0863 - val_smape: 0.2211

Epoch 2/256

4586/4586 - 61s - 13ms/step - ia: 0.9185 - loss: 0.0248 - mae: 0.1189 - rmse: 0.1492 - smape: 0.2940 - val_ia: 0.5578 - val_loss: 0.0094 - val_mae: 0.0739 - val_rmse: 0.0836 - val_smape: 0.1830

Epoch 3/256

4586/4586 - 69s - 15ms/step - ia: 0.9259 - loss: 0.0211 - mae: 0.1089 - rmse: 0.1370 - smape: 0.2695 - val_ia: 0.5863 - val_loss: 0.0080 - val_mae: 0.0676 - val_rmse: 0.0771 - val_smape: 0.2169

Epoch 4/256

4586/4586 - 69s - 15ms/step - ia: 0.9287 - loss: 0.0193 - mae: 0.1046 - rmse: 0.1317 - smape: 0.2603 - val_ia: 0.5941 - val_loss: 0.0068 - val_mae: 0.0623 - val_rmse: 0.0716 - val_smape: 0.1734

Epoch 5/256

4586/4586 - 66s - 14ms/step - ia: 0.9315 - loss: 0.0182 - mae: 0.1004 - rmse: 0.1269 - smape: 0.2506 - val_ia: 0.6294 - val_loss: 0.0047 - val_mae: 0.0519 - val_rmse: 0.0611 - val_smape: 0.1536

Epoch 6/256

4586/4586 - 64s - 14ms/step - ia: 0.9330 - loss: 0.0176 - mae: 0.0987 - rmse: 0.1251 - smape: 0.2435 - val_ia: 0.5697 - val_loss: 0.0082 - val_mae: 0.0721 - val_rmse: 0.0807 - val_smape: 0.2545

Epoch 7/256

4586/4586 - 61s - 13ms/step - ia: 0.9345 - loss: 0.0168 - mae: 0.0963 - rmse: 0.1221 - smape: 0.2372 - val_ia: 0.6049 - val_loss: 0.0077 - val_mae: 0.0644 - val_rmse: 0.0732 - val_smape: 0.1644

Epoch 8/256

4586/4586 - 64s - 14ms/step - ia: 0.9350 - loss: 0.0168 - mae: 0.0961 - rmse: 0.1217 - smape: 0.2364 - val_ia: 0.5841 - val_loss: 0.0071 - val_mae: 0.0661 - val_rmse: 0.0755 - val_smape: 0.1768

Epoch 9/256

4586/4586 - 64s - 14ms/step - ia: 0.9364 - loss: 0.0162 - mae: 0.0939 - rmse: 0.1197 - smape: 0.2294 - val_ia: 0.5765 - val_loss: 0.0073 - val_mae: 0.0670 - val_rmse: 0.0754 - val_smape: 0.1874

Epoch 10/256

4586/4586 - 62s - 14ms/step - ia: 0.9364 - loss: 0.0163 - mae: 0.0938 - rmse: 0.1197 - smape: 0.2278 - val_ia: 0.6144 - val_loss: 0.0057 - val_mae: 0.0573 - val_rmse: 0.0658 - val_smape: 0.1601

Epoch 11/256

4586/4586 - 61s - 13ms/step - ia: 0.9370 - loss: 0.0159 - mae: 0.0926 - rmse: 0.1182 - smape: 0.2244 - val_ia: 0.5971 - val_loss: 0.0082 - val_mae: 0.0662 - val_rmse: 0.0748 - val_smape: 0.1651

Epoch 12/256

4586/4586 - 58s - 13ms/step - ia: 0.9375 - loss: 0.0156 - mae: 0.0920 - rmse: 0.1175 - smape: 0.2220 - val_ia: 0.6060 - val_loss: 0.0062 - val_mae: 0.0610 - val_rmse: 0.0698 - val_smape: 0.1793

Epoch 13/256

4586/4586 - 89s - 19ms/step - ia: 0.9383 - loss: 0.0152 - mae: 0.0907 - rmse: 0.1159 - smape: 0.2207 - val_ia: 0.6479 - val_loss: 0.0044 - val_mae: 0.0496 - val_rmse: 0.0586 - val_smape: 0.1544

Epoch 14/256

4586/4586 - 78s - 17ms/step - ia: 0.9386 - loss: 0.0152 - mae: 0.0901 - rmse: 0.1157 - smape: 0.2199 - val_ia: 0.6250 - val_loss: 0.0054 - val_mae: 0.0558 - val_rmse: 0.0644 - val_smape: 0.1808

Epoch 15/256

4586/4586 - 63s - 14ms/step - ia: 0.9398 - loss: 0.0150 - mae: 0.0893 - rmse: 0.1147 - smape: 0.2163 - val_ia: 0.6401 - val_loss: 0.0045 - val_mae: 0.0502 - val_rmse: 0.0589 - val_smape: 0.1452

Epoch 16/256

4586/4586 - 57s - 12ms/step - ia: 0.9389 - loss: 0.0151 - mae: 0.0896 - rmse: 0.1151 - smape: 0.2154 - val_ia: 0.6155 - val_loss: 0.0063 - val_mae: 0.0598 - val_rmse: 0.0686 - val_smape: 0.1743

Epoch 17/256

4586/4586 - 65s - 14ms/step - ia: 0.9396 - loss: 0.0148 - mae: 0.0889 - rmse: 0.1142 - smape: 0.2124 - val_ia: 0.5260 - val_loss: 0.0091 - val_mae: 0.0793 - val_rmse: 0.0873 - val_smape: 0.1932

Epoch 18/256

4586/4586 - 63s - 14ms/step - ia: 0.9397 - loss: 0.0147 - mae: 0.0884 - rmse: 0.1137 - smape: 0.2139 - val_ia: 0.6594 - val_loss: 0.0039 - val_mae: 0.0459 - val_rmse: 0.0547 - val_smape: 0.1341

Epoch 19/256

4586/4586 - 63s - 14ms/step - ia: 0.9400 - loss: 0.0146 - mae: 0.0884 - rmse: 0.1133 - smape: 0.2150 - val_ia: 0.6297 - val_loss: 0.0046 - val_mae: 0.0524 - val_rmse: 0.0609 - val_smape: 0.1469

Epoch 20/256

4586/4586 - 63s - 14ms/step - ia: 0.9408 - loss: 0.0144 - mae: 0.0873 - rmse: 0.1121 - smape: 0.2091 - val_ia: 0.6031 - val_loss: 0.0054 - val_mae: 0.0575 - val_rmse: 0.0660 - val_smape: 0.1686

Epoch 21/256

4586/4586 - 59s - 13ms/step - ia: 0.9399 - loss: 0.0148 - mae: 0.0884 - rmse: 0.1136 - smape: 0.2117 - val_ia: 0.5779 - val_loss: 0.0068 - val_mae: 0.0646 - val_rmse: 0.0729 - val_smape: 0.1579

Epoch 22/256

4586/4586 - 63s - 14ms/step - ia: 0.9410 - loss: 0.0143 - mae: 0.0871 - rmse: 0.1118 - smape: 0.2100 - val_ia: 0.6400 - val_loss: 0.0047 - val_mae: 0.0517 - val_rmse: 0.0606 - val_smape: 0.1407

Epoch 23/256

4586/4586 - 58s - 13ms/step - ia: 0.9407 - loss: 0.0143 - mae: 0.0870 - rmse: 0.1119 - smape: 0.2096 - val_ia: 0.6126 - val_loss: 0.0055 - val_mae: 0.0567 - val_rmse: 0.0654 - val_smape: 0.1497

Epoch 24/256

4586/4586 - 65s - 14ms/step - ia: 0.9413 - loss: 0.0142 - mae: 0.0868 - rmse: 0.1115 - smape: 0.2094 - val_ia: 0.6246 - val_loss: 0.0052 - val_mae: 0.0548 - val_rmse: 0.0631 - val_smape: 0.1438

Epoch 25/256

4586/4586 - 65s - 14ms/step - ia: 0.9413 - loss: 0.0142 - mae: 0.0868 - rmse: 0.1116 - smape: 0.2081 - val_ia: 0.6137 - val_loss: 0.0051 - val_mae: 0.0561 - val_rmse: 0.0649 - val_smape: 0.1662

Epoch 26/256

4586/4586 - 64s - 14ms/step - ia: 0.9411 - loss: 0.0143 - mae: 0.0869 - rmse: 0.1116 - smape: 0.2086 - val_ia: 0.6112 - val_loss: 0.0063 - val_mae: 0.0602 - val_rmse: 0.0685 - val_smape: 0.1643

Epoch 27/256

4586/4586 - 62s - 14ms/step - ia: 0.9417 - loss: 0.0140 - mae: 0.0858 - rmse: 0.1107 - smape: 0.2053 - val_ia: 0.6078 - val_loss: 0.0065 - val_mae: 0.0614 - val_rmse: 0.0693 - val_smape: 0.1750

Epoch 28/256

4586/4586 - 66s - 14ms/step - ia: 0.9417 - loss: 0.0142 - mae: 0.0864 - rmse: 0.1112 - smape: 0.2063 - val_ia: 0.6633 - val_loss: 0.0038 - val_mae: 0.0460 - val_rmse: 0.0548 - val_smape: 0.1349

Epoch 29/256

4586/4586 - 67s - 15ms/step - ia: 0.9419 - loss: 0.0141 - mae: 0.0859 - rmse: 0.1108 - smape: 0.2054 - val_ia: 0.6553 - val_loss: 0.0041 - val_mae: 0.0475 - val_rmse: 0.0563 - val_smape: 0.1321

Epoch 30/256

4586/4586 - 62s - 13ms/step - ia: 0.9419 - loss: 0.0140 - mae: 0.0858 - rmse: 0.1107 - smape: 0.2063 - val_ia: 0.6643 - val_loss: 0.0034 - val_mae: 0.0433 - val_rmse: 0.0519 - val_smape: 0.1290

Epoch 31/256

4586/4586 - 64s - 14ms/step - ia: 0.9422 - loss: 0.0140 - mae: 0.0855 - rmse: 0.1103 - smape: 0.2054 - val_ia: 0.6578 - val_loss: 0.0038 - val_mae: 0.0464 - val_rmse: 0.0550 - val_smape: 0.1366

Epoch 32/256

4586/4586 - 65s - 14ms/step - ia: 0.9426 - loss: 0.0136 - mae: 0.0846 - rmse: 0.1092 - smape: 0.2037 - val_ia: 0.6704 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0519 - val_smape: 0.1387

Epoch 33/256

4586/4586 - 65s - 14ms/step - ia: 0.9423 - loss: 0.0138 - mae: 0.0855 - rmse: 0.1099 - smape: 0.2036 - val_ia: 0.6512 - val_loss: 0.0041 - val_mae: 0.0482 - val_rmse: 0.0568 - val_smape: 0.1404

Epoch 34/256

4586/4586 - 65s - 14ms/step - ia: 0.9426 - loss: 0.0136 - mae: 0.0848 - rmse: 0.1091 - smape: 0.2047 - val_ia: 0.6441 - val_loss: 0.0040 - val_mae: 0.0481 - val_rmse: 0.0569 - val_smape: 0.1362

Epoch 35/256

4586/4586 - 61s - 13ms/step - ia: 0.9425 - loss: 0.0138 - mae: 0.0847 - rmse: 0.1098 - smape: 0.2031 - val_ia: 0.6162 - val_loss: 0.0051 - val_mae: 0.0545 - val_rmse: 0.0627 - val_smape: 0.1445

Epoch 36/256

4586/4586 - 61s - 13ms/step - ia: 0.9425 - loss: 0.0138 - mae: 0.0849 - rmse: 0.1097 - smape: 0.2023 - val_ia: 0.6396 - val_loss: 0.0045 - val_mae: 0.0508 - val_rmse: 0.0592 - val_smape: 0.1492

Epoch 37/256

4586/4586 - 59s - 13ms/step - ia: 0.9423 - loss: 0.0138 - mae: 0.0850 - rmse: 0.1098 - smape: 0.2034 - val_ia: 0.6720 - val_loss: 0.0033 - val_mae: 0.0428 - val_rmse: 0.0513 - val_smape: 0.1301

Epoch 38/256

4586/4586 - 61s - 13ms/step - ia: 0.9427 - loss: 0.0137 - mae: 0.0846 - rmse: 0.1091 - smape: 0.2003 - val_ia: 0.6335 - val_loss: 0.0042 - val_mae: 0.0503 - val_rmse: 0.0589 - val_smape: 0.1437

Epoch 39/256

4586/4586 - 61s - 13ms/step - ia: 0.9436 - loss: 0.0133 - mae: 0.0834 - rmse: 0.1077 - smape: 0.1992 - val_ia: 0.6460 - val_loss: 0.0047 - val_mae: 0.0506 - val_rmse: 0.0588 - val_smape: 0.1420

Epoch 40/256

4586/4586 - 67s - 15ms/step - ia: 0.9427 - loss: 0.0136 - mae: 0.0843 - rmse: 0.1088 - smape: 0.2020 - val_ia: 0.6620 - val_loss: 0.0037 - val_mae: 0.0452 - val_rmse: 0.0539 - val_smape: 0.1417

Epoch 41/256

4586/4586 - 58s - 13ms/step - ia: 0.9432 - loss: 0.0136 - mae: 0.0841 - rmse: 0.1089 - smape: 0.2000 - val_ia: 0.6196 - val_loss: 0.0054 - val_mae: 0.0556 - val_rmse: 0.0637 - val_smape: 0.1430

Epoch 42/256

4586/4586 - 64s - 14ms/step - ia: 0.9428 - loss: 0.0136 - mae: 0.0843 - rmse: 0.1088 - smape: 0.1989 - val_ia: 0.5982 - val_loss: 0.0058 - val_mae: 0.0596 - val_rmse: 0.0673 - val_smape: 0.1564

Epoch 43/256

4586/4586 - 63s - 14ms/step - ia: 0.9435 - loss: 0.0134 - mae: 0.0838 - rmse: 0.1081 - smape: 0.1999 - val_ia: 0.6518 - val_loss: 0.0039 - val_mae: 0.0466 - val_rmse: 0.0552 - val_smape: 0.1566

Epoch 44/256

4586/4586 - 64s - 14ms/step - ia: 0.9436 - loss: 0.0133 - mae: 0.0836 - rmse: 0.1079 - smape: 0.1991 - val_ia: 0.6420 - val_loss: 0.0045 - val_mae: 0.0503 - val_rmse: 0.0588 - val_smape: 0.1323

Epoch 45/256

4586/4586 - 55s - 12ms/step - ia: 0.9433 - loss: 0.0133 - mae: 0.0834 - rmse: 0.1077 - smape: 0.1989 - val_ia: 0.6483 - val_loss: 0.0043 - val_mae: 0.0491 - val_rmse: 0.0577 - val_smape: 0.1435

Epoch 46/256

4586/4586 - 61s - 13ms/step - ia: 0.9436 - loss: 0.0135 - mae: 0.0838 - rmse: 0.1083 - smape: 0.1981 - val_ia: 0.6474 - val_loss: 0.0040 - val_mae: 0.0474 - val_rmse: 0.0555 - val_smape: 0.1394

Epoch 47/256

4586/4586 - 57s - 13ms/step - ia: 0.9435 - loss: 0.0134 - mae: 0.0835 - rmse: 0.1080 - smape: 0.1993 - val_ia: 0.6702 - val_loss: 0.0038 - val_mae: 0.0454 - val_rmse: 0.0543 - val_smape: 0.1335

Epoch 48/256

4586/4586 - 66s - 14ms/step - ia: 0.9431 - loss: 0.0135 - mae: 0.0842 - rmse: 0.1088 - smape: 0.2003 - val_ia: 0.6815 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0500 - val_smape: 0.1258

Epoch 49/256

4586/4586 - 64s - 14ms/step - ia: 0.9433 - loss: 0.0136 - mae: 0.0839 - rmse: 0.1086 - smape: 0.1991 - val_ia: 0.6246 - val_loss: 0.0046 - val_mae: 0.0526 - val_rmse: 0.0611 - val_smape: 0.1464

Epoch 50/256

4586/4586 - 81s - 18ms/step - ia: 0.9440 - loss: 0.0131 - mae: 0.0827 - rmse: 0.1068 - smape: 0.1973 - val_ia: 0.6726 - val_loss: 0.0039 - val_mae: 0.0460 - val_rmse: 0.0547 - val_smape: 0.1373

Epoch 51/256

4586/4586 - 80s - 17ms/step - ia: 0.9441 - loss: 0.0132 - mae: 0.0828 - rmse: 0.1073 - smape: 0.1983 - val_ia: 0.6692 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0528 - val_smape: 0.1252

Epoch 52/256

4586/4586 - 84s - 18ms/step - ia: 0.9436 - loss: 0.0134 - mae: 0.0832 - rmse: 0.1079 - smape: 0.1977 - val_ia: 0.6620 - val_loss: 0.0040 - val_mae: 0.0467 - val_rmse: 0.0553 - val_smape: 0.1302

Epoch 53/256

4586/4586 - 64s - 14ms/step - ia: 0.9441 - loss: 0.0132 - mae: 0.0829 - rmse: 0.1072 - smape: 0.1969 - val_ia: 0.6250 - val_loss: 0.0047 - val_mae: 0.0524 - val_rmse: 0.0609 - val_smape: 0.1382

Epoch 54/256

4586/4586 - 63s - 14ms/step - ia: 0.9440 - loss: 0.0132 - mae: 0.0829 - rmse: 0.1069 - smape: 0.1973 - val_ia: 0.6519 - val_loss: 0.0038 - val_mae: 0.0465 - val_rmse: 0.0553 - val_smape: 0.1449

Epoch 55/256

4586/4586 - 81s - 18ms/step - ia: 0.9439 - loss: 0.0133 - mae: 0.0833 - rmse: 0.1076 - smape: 0.1979 - val_ia: 0.6924 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0481 - val_smape: 0.1231

Epoch 56/256

4586/4586 - 58s - 13ms/step - ia: 0.9438 - loss: 0.0132 - mae: 0.0831 - rmse: 0.1074 - smape: 0.1963 - val_ia: 0.6319 - val_loss: 0.0048 - val_mae: 0.0524 - val_rmse: 0.0608 - val_smape: 0.1420

Epoch 57/256

4586/4586 - 65s - 14ms/step - ia: 0.9443 - loss: 0.0131 - mae: 0.0827 - rmse: 0.1070 - smape: 0.1967 - val_ia: 0.6512 - val_loss: 0.0046 - val_mae: 0.0502 - val_rmse: 0.0589 - val_smape: 0.1439

Epoch 58/256

4586/4586 - 65s - 14ms/step - ia: 0.9447 - loss: 0.0130 - mae: 0.0822 - rmse: 0.1065 - smape: 0.1959 - val_ia: 0.6461 - val_loss: 0.0039 - val_mae: 0.0473 - val_rmse: 0.0557 - val_smape: 0.1323

Epoch 59/256

4586/4586 - 75s - 16ms/step - ia: 0.9441 - loss: 0.0132 - mae: 0.0827 - rmse: 0.1073 - smape: 0.1949 - val_ia: 0.6141 - val_loss: 0.0050 - val_mae: 0.0552 - val_rmse: 0.0636 - val_smape: 0.1613

Epoch 60/256

4586/4586 - 78s - 17ms/step - ia: 0.9442 - loss: 0.0130 - mae: 0.0826 - rmse: 0.1067 - smape: 0.1947 - val_ia: 0.6312 - val_loss: 0.0048 - val_mae: 0.0525 - val_rmse: 0.0611 - val_smape: 0.1414

Epoch 61/256

4586/4586 - 77s - 17ms/step - ia: 0.9442 - loss: 0.0131 - mae: 0.0829 - rmse: 0.1068 - smape: 0.1971 - val_ia: 0.6651 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0533 - val_smape: 0.1311

Epoch 62/256

4586/4586 - 71s - 15ms/step - ia: 0.9441 - loss: 0.0132 - mae: 0.0826 - rmse: 0.1072 - smape: 0.1957 - val_ia: 0.6530 - val_loss: 0.0037 - val_mae: 0.0458 - val_rmse: 0.0543 - val_smape: 0.1325

Epoch 63/256

4586/4586 - 77s - 17ms/step - ia: 0.9441 - loss: 0.0132 - mae: 0.0827 - rmse: 0.1072 - smape: 0.1961 - val_ia: 0.6562 - val_loss: 0.0040 - val_mae: 0.0472 - val_rmse: 0.0559 - val_smape: 0.1341

Epoch 64/256

4586/4586 - 77s - 17ms/step - ia: 0.9447 - loss: 0.0131 - mae: 0.0821 - rmse: 0.1067 - smape: 0.1962 - val_ia: 0.6574 - val_loss: 0.0035 - val_mae: 0.0447 - val_rmse: 0.0536 - val_smape: 0.1305

Epoch 65/256

4586/4586 - 70s - 15ms/step - ia: 0.9442 - loss: 0.0132 - mae: 0.0827 - rmse: 0.1072 - smape: 0.1962 - val_ia: 0.6722 - val_loss: 0.0039 - val_mae: 0.0452 - val_rmse: 0.0540 - val_smape: 0.1282

Epoch 66/256

4586/4586 - 74s - 16ms/step - ia: 0.9444 - loss: 0.0131 - mae: 0.0822 - rmse: 0.1065 - smape: 0.1959 - val_ia: 0.6815 - val_loss: 0.0033 - val_mae: 0.0420 - val_rmse: 0.0506 - val_smape: 0.1287

Epoch 67/256

4586/4586 - 77s - 17ms/step - ia: 0.9444 - loss: 0.0129 - mae: 0.0821 - rmse: 0.1061 - smape: 0.1957 - val_ia: 0.6520 - val_loss: 0.0039 - val_mae: 0.0476 - val_rmse: 0.0562 - val_smape: 0.1355

Epoch 68/256

4586/4586 - 72s - 16ms/step - ia: 0.9445 - loss: 0.0132 - mae: 0.0825 - rmse: 0.1070 - smape: 0.1942 - val_ia: 0.6709 - val_loss: 0.0034 - val_mae: 0.0433 - val_rmse: 0.0519 - val_smape: 0.1448

Epoch 69/256

4586/4586 - 74s - 16ms/step - ia: 0.9445 - loss: 0.0130 - mae: 0.0821 - rmse: 0.1064 - smape: 0.1959 - val_ia: 0.6825 - val_loss: 0.0034 - val_mae: 0.0423 - val_rmse: 0.0512 - val_smape: 0.1280

Epoch 70/256

4586/4586 - 81s - 18ms/step - ia: 0.9450 - loss: 0.0129 - mae: 0.0815 - rmse: 0.1058 - smape: 0.1930 - val_ia: 0.6474 - val_loss: 0.0039 - val_mae: 0.0477 - val_rmse: 0.0564 - val_smape: 0.1348

Epoch 70: early stopping

Restoring model weights from the end of the best epoch: 55.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 7:14 3s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step

 34%|███▍      | 17/50 [3:40:39<15:01:44, 1639.52s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 29s - 103ms/step - ia: 0.2308 - loss: 0.8751 - mae: 0.7716 - rmse: 0.9341 - smape: 1.5543 - val_ia: 0.2858 - val_loss: 0.7429 - val_mae: 0.7135 - val_rmse: 0.8570 - val_smape: 1.5648

Epoch 2/16

287/287 - 5s - 16ms/step - ia: 0.2813 - loss: 0.7951 - mae: 0.7343 - rmse: 0.8906 - smape: 1.4741 - val_ia: 0.3219 - val_loss: 0.6788 - val_mae: 0.6806 - val_rmse: 0.8189 - val_smape: 1.4935

Epoch 3/16

287/287 - 5s - 16ms/step - ia: 0.3327 - loss: 0.7220 - mae: 0.6984 - rmse: 0.8487 - smape: 1.3968 - val_ia: 0.3579 - val_loss: 0.6199 - val_mae: 0.6490 - val_rmse: 0.7824 - val_smape: 1.4153

Epoch 4/16

287/287 - 5s - 17ms/step - ia: 0.3808 - loss: 0.6605 - mae: 0.6658 - rmse: 0.8115 - smape: 1.3207 - val_ia: 0.3935 - val_loss: 0.5664 - val_mae: 0.6187 - val_rmse: 0.7476 - val_smape: 1.3427

Epoch 5/16

287/287 - 5s - 16ms/step - ia: 0.4284 - loss: 0.6007 - mae: 0.6335 - rmse: 0.7735 - smape: 1.2493 - val_ia: 0.4287 - val_loss: 0.5178 - val_mae: 0.5898 - val_rmse: 0.7146 - val_smape: 1.2706

Epoch 6/16

287/287 - 4s - 13ms/step - ia: 0.4673 - loss: 0.5552 - mae: 0.6072 - rmse: 0.7438 - smape: 1.1869 - val_ia: 0.4631 - val_loss: 0.4738 - val_mae: 0.5621 - val_rmse: 0.6834 - val_smape: 1.1964

Epoch 7/16

287/287 - 3s - 12ms/step - ia: 0.5093 - loss: 0.5036 - mae: 0.5769 - rmse: 0.7085 - smape: 1.1234 - val_ia: 0.4965 - val_loss: 0.4342 - val_mae: 0.5358 - val_rmse: 0.6541 - val_smape: 1.1261

Epoch 8/16

287/287 - 3s - 12ms/step - ia: 0.5420 - loss: 0.4645 - mae: 0.5541 - rmse: 0.6801 - smape: 1.0708 - val_ia: 0.5285 - val_loss: 0.3992 - val_mae: 0.5110 - val_rmse: 0.6270 - val_smape: 1.0623

Epoch 9/16

287/287 - 3s - 12ms/step - ia: 0.5740 - loss: 0.4287 - mae: 0.5303 - rmse: 0.6535 - smape: 1.0215 - val_ia: 0.5592 - val_loss: 0.3685 - val_mae: 0.4878 - val_rmse: 0.6022 - val_smape: 1.0060

Epoch 10/16

287/287 - 4s - 14ms/step - ia: 0.6009 - loss: 0.3989 - mae: 0.5102 - rmse: 0.6306 - smape: 0.9836 - val_ia: 0.5873 - val_loss: 0.3420 - val_mae: 0.4664 - val_rmse: 0.5800 - val_smape: 0.9569

Epoch 11/16

287/287 - 6s - 20ms/step - ia: 0.6258 - loss: 0.3709 - mae: 0.4907 - rmse: 0.6079 - smape: 0.9439 - val_ia: 0.6125 - val_loss: 0.3192 - val_mae: 0.4470 - val_rmse: 0.5603 - val_smape: 0.9152

Epoch 12/16

287/287 - 5s - 17ms/step - ia: 0.6469 - loss: 0.3495 - mae: 0.4747 - rmse: 0.5898 - smape: 0.9108 - val_ia: 0.6342 - val_loss: 0.3002 - val_mae: 0.4303 - val_rmse: 0.5433 - val_smape: 0.8813

Epoch 13/16

287/287 - 5s - 17ms/step - ia: 0.6661 - loss: 0.3292 - mae: 0.4589 - rmse: 0.5728 - smape: 0.8793 - val_ia: 0.6525 - val_loss: 0.2846 - val_mae: 0.4168 - val_rmse: 0.5290 - val_smape: 0.8541

Epoch 14/16

287/287 - 5s - 17ms/step - ia: 0.6800 - loss: 0.3166 - mae: 0.4489 - rmse: 0.5617 - smape: 0.8584 - val_ia: 0.6671 - val_loss: 0.2721 - val_mae: 0.4065 - val_rmse: 0.5172 - val_smape: 0.8329

Epoch 15/16

287/287 - 4s - 15ms/step - ia: 0.6924 - loss: 0.3036 - mae: 0.4389 - rmse: 0.5499 - smape: 0.8402 - val_ia: 0.6788 - val_loss: 0.2621 - val_mae: 0.3987 - val_rmse: 0.5075 - val_smape: 0.8168

Epoch 16/16

287/287 - 4s - 12ms/step - ia: 0.7023 - loss: 0.2929 - mae: 0.4302 - rmse: 0.5401 - smape: 0.8215 - val_ia: 0.6882 - val_loss: 0.2540 - val_mae: 0.3928 - val_rmse: 0.4996 - val_smape: 0.8042

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/16

 36%|███▌      | 18/50 [3:42:16<10:27:14, 1176.09s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

574/574 - 12s - 21ms/step - ia: 0.8753 - loss: 0.0807 - mae: 0.1956 - rmse: 0.2480 - smape: 0.4542 - val_ia: 0.9354 - val_loss: 0.0081 - val_mae: 0.0636 - val_rmse: 0.0878 - val_smape: 0.1821

Epoch 2/16

574/574 - 8s - 13ms/step - ia: 0.9364 - loss: 0.0187 - mae: 0.1039 - rmse: 0.1352 - smape: 0.2788 - val_ia: 0.9373 - val_loss: 0.0077 - val_mae: 0.0624 - val_rmse: 0.0855 - val_smape: 0.1761

Epoch 3/16

574/574 - 6s - 11ms/step - ia: 0.9437 - loss: 0.0150 - mae: 0.0919 - rmse: 0.1208 - smape: 0.2526 - val_ia: 0.9361 - val_loss: 0.0075 - val_mae: 0.0621 - val_rmse: 0.0836 - val_smape: 0.1766

Epoch 4/16

574/574 - 7s - 12ms/step - ia: 0.9475 - loss: 0.0132 - mae: 0.0857 - rmse: 0.1131 - smape: 0.2342 - val_ia: 0.9279 - val_loss: 0.0082 - val_mae: 0.0684 - val_rmse: 0.0872 - val_smape: 0.1964

Epoch 5/16

574/574 - 7s - 12ms/step - ia: 0.9494 - loss: 0.0123 - mae: 0.0826 - rmse: 0.1093 - smape: 0.2271 - val_ia: 0.9248 - val_loss: 0.0085 - val_mae: 0.0704 - val_rmse: 0.0889 - val_smape: 0.1900

Epoch 6/16

574/574 - 5s - 9ms/step - ia: 0.9512 - loss: 0.0115 - mae: 0.0796 - rmse: 0.1057 - smape: 0.2189 - val_ia: 0.9386 - val_loss: 0.0066 - val_mae: 0.0600 - val_rmse: 0.0792 - val_smape: 0.1668

Epoch 7/16

574/574 - 7s - 11ms/step - ia: 0.9537 - loss: 0.0105 - mae: 0.0756 - rmse: 0.1008 - smape: 0.2091 - val_ia: 0.9400 - val_loss: 0.0060 - val_mae: 0.0586 - val_rmse: 0.0746 - val_smape: 0.1971

Epoch 8/16

574/574 - 8s - 13ms/step - ia: 0.9545 - loss: 0.0102 - mae: 0.0744 - rmse: 0.0992 - smape: 0.2043 - val_ia: 0.9433 - val_loss: 0.0053 - val_mae: 0.0542 - val_rmse: 0.0708 - val_smape: 0.1532

Epoch 9/16

574/574 - 8s - 14ms/step - ia: 0.9556 - loss: 0.0098 - mae: 0.0725 - rmse: 0.0973 - smape: 0.2004 - val_ia: 0.9229 - val_loss: 0.0082 - val_mae: 0.0729 - val_rmse: 0.0871 - val_smape: 0.2366

Epoch 10/16

574/574 - 7s - 12ms/step - ia: 0.9562 - loss: 0.0096 - mae: 0.0717 - rmse: 0.0964 - smape: 0.1978 - val_ia: 0.9510 - val_loss: 0.0046 - val_mae: 0.0488 - val_rmse: 0.0657 - val_smape: 0.1458

Epoch 11/16

574/574 - 7s - 12ms/step - ia: 0.9569 - loss: 0.0093 - mae: 0.0706 - rmse: 0.0947 - smape: 0.1931 - val_ia: 0.9419 - val_loss: 0.0053 - val_mae: 0.0555 - val_rmse: 0.0699 - val_smape: 0.1689

Epoch 12/16

574/574 - 7s - 13ms/step - ia: 0.9573 - loss: 0.0092 - mae: 0.0699 - rmse: 0.0941 - smape: 0.1902 - val_ia: 0.9502 - val_loss: 0.0048 - val_mae: 0.0497 - val_rmse: 0.0665 - val_smape: 0.1447

Epoch 13/16

574/574 - 7s - 13ms/step - ia: 0.9580 - loss: 0.0089 - mae: 0.0686 - rmse: 0.0926 - smape: 0.1867 - val_ia: 0.9548 - val_loss: 0.0037 - val_mae: 0.0439 - val_rmse: 0.0587 - val_smape: 0.1383

Epoch 14/16

574/574 - 7s - 12ms/step - ia: 0.9584 - loss: 0.0088 - mae: 0.0680 - rmse: 0.0921 - smape: 0.1853 - val_ia: 0.9528 - val_loss: 0.0041 - val_mae: 0.0469 - val_rmse: 0.0622 - val_smape: 0.1420

Epoch 15/16

574/574 - 7s - 12ms/step - ia: 0.9583 - loss: 0.0088 - mae: 0.0682 - rmse: 0.0919 - smape: 0.1844 - val_ia: 0.9547 - val_loss: 0.0038 - val_mae: 0.0451 - val_rmse: 0.0600 - val_smape: 0.1385

Epoch 16/16

574/574 - 6s - 11ms/step - ia: 0.9585 - loss: 0.0088 - mae: 0.0679 - rmse: 0.0918 - smape: 0.1832 - val_ia: 0.9551 - val_loss: 0.0036 - val_mae: 0.0433 - val_rmse: 0.0573 - val_smape: 0.1355

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:10 806ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 38%|███▊      | 19/50 [3:44:20<7:24:27, 860.23s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4586/4586 - 98s - 21ms/step - ia: 0.6967 - loss: 0.2860 - mae: 0.3898 - rmse: 0.4753 - smape: 0.7574 - val_ia: 0.3958 - val_loss: 0.0427 - val_mae: 0.1534 - val_rmse: 0.1670 - val_smape: 0.3400

Epoch 2/32

4586/4586 - 71s - 15ms/step - ia: 0.8333 - loss: 0.0987 - mae: 0.2406 - rmse: 0.2997 - smape: 0.5109 - val_ia: 0.4092 - val_loss: 0.0353 - val_mae: 0.1440 - val_rmse: 0.1576 - val_smape: 0.3572

Epoch 3/32

4586/4586 - 66s - 14ms/step - ia: 0.8505 - loss: 0.0800 - mae: 0.2153 - rmse: 0.2693 - smape: 0.4729 - val_ia: 0.4133 - val_loss: 0.0325 - val_mae: 0.1391 - val_rmse: 0.1526 - val_smape: 0.3490

Epoch 4/32

4586/4586 - 68s - 15ms/step - ia: 0.8585 - loss: 0.0738 - mae: 0.2050 - rmse: 0.2577 - smape: 0.4506 - val_ia: 0.4260 - val_loss: 0.0359 - val_mae: 0.1469 - val_rmse: 0.1603 - val_smape: 0.4046

Epoch 5/32

4586/4586 - 67s - 15ms/step - ia: 0.8636 - loss: 0.0691 - mae: 0.1978 - rmse: 0.2493 - smape: 0.4368 - val_ia: 0.4502 - val_loss: 0.0265 - val_mae: 0.1232 - val_rmse: 0.1368 - val_smape: 0.3159

Epoch 6/32

4586/4586 - 69s - 15ms/step - ia: 0.8664 - loss: 0.0662 - mae: 0.1931 - rmse: 0.2434 - smape: 0.4229 - val_ia: 0.4627 - val_loss: 0.0216 - val_mae: 0.1116 - val_rmse: 0.1249 - val_smape: 0.2947

Epoch 7/32

4586/4586 - 67s - 15ms/step - ia: 0.8691 - loss: 0.0638 - mae: 0.1895 - rmse: 0.2395 - smape: 0.4174 - val_ia: 0.4830 - val_loss: 0.0190 - val_mae: 0.1018 - val_rmse: 0.1150 - val_smape: 0.2549

Epoch 8/32

4586/4586 - 68s - 15ms/step - ia: 0.8715 - loss: 0.0612 - mae: 0.1852 - rmse: 0.2342 - smape: 0.4115 - val_ia: 0.4836 - val_loss: 0.0176 - val_mae: 0.0995 - val_rmse: 0.1125 - val_smape: 0.2567

Epoch 9/32

4586/4586 - 68s - 15ms/step - ia: 0.8746 - loss: 0.0596 - mae: 0.1819 - rmse: 0.2305 - smape: 0.4033 - val_ia: 0.4915 - val_loss: 0.0185 - val_mae: 0.1003 - val_rmse: 0.1133 - val_smape: 0.2606

Epoch 10/32

4586/4586 - 70s - 15ms/step - ia: 0.8759 - loss: 0.0588 - mae: 0.1803 - rmse: 0.2283 - smape: 0.4000 - val_ia: 0.5034 - val_loss: 0.0166 - val_mae: 0.0950 - val_rmse: 0.1078 - val_smape: 0.2693

Epoch 11/32

4586/4586 - 66s - 14ms/step - ia: 0.8777 - loss: 0.0572 - mae: 0.1782 - rmse: 0.2258 - smape: 0.3958 - val_ia: 0.5118 - val_loss: 0.0161 - val_mae: 0.0920 - val_rmse: 0.1047 - val_smape: 0.2544

Epoch 12/32

4586/4586 - 64s - 14ms/step - ia: 0.8790 - loss: 0.0566 - mae: 0.1758 - rmse: 0.2238 - smape: 0.3903 - val_ia: 0.4716 - val_loss: 0.0216 - val_mae: 0.1116 - val_rmse: 0.1238 - val_smape: 0.3212

Epoch 13/32

4586/4586 - 85s - 19ms/step - ia: 0.8799 - loss: 0.0552 - mae: 0.1739 - rmse: 0.2209 - smape: 0.3879 - val_ia: 0.5020 - val_loss: 0.0163 - val_mae: 0.0959 - val_rmse: 0.1080 - val_smape: 0.2807

Epoch 14/32

4586/4586 - 64s - 14ms/step - ia: 0.8811 - loss: 0.0546 - mae: 0.1727 - rmse: 0.2200 - smape: 0.3874 - val_ia: 0.5051 - val_loss: 0.0163 - val_mae: 0.0944 - val_rmse: 0.1067 - val_smape: 0.2803

Epoch 15/32

4586/4586 - 65s - 14ms/step - ia: 0.8810 - loss: 0.0549 - mae: 0.1729 - rmse: 0.2199 - smape: 0.3849 - val_ia: 0.5091 - val_loss: 0.0154 - val_mae: 0.0915 - val_rmse: 0.1039 - val_smape: 0.2593

Epoch 16/32

4586/4586 - 65s - 14ms/step - ia: 0.8819 - loss: 0.0543 - mae: 0.1720 - rmse: 0.2190 - smape: 0.3817 - val_ia: 0.4932 - val_loss: 0.0175 - val_mae: 0.0992 - val_rmse: 0.1115 - val_smape: 0.2504

Epoch 17/32

4586/4586 - 64s - 14ms/step - ia: 0.8834 - loss: 0.0530 - mae: 0.1695 - rmse: 0.2165 - smape: 0.3767 - val_ia: 0.5260 - val_loss: 0.0153 - val_mae: 0.0884 - val_rmse: 0.1011 - val_smape: 0.2655

Epoch 18/32

4586/4586 - 66s - 14ms/step - ia: 0.8836 - loss: 0.0525 - mae: 0.1684 - rmse: 0.2148 - smape: 0.3759 - val_ia: 0.5408 - val_loss: 0.0138 - val_mae: 0.0833 - val_rmse: 0.0961 - val_smape: 0.2562

Epoch 19/32

4586/4586 - 68s - 15ms/step - ia: 0.8850 - loss: 0.0513 - mae: 0.1674 - rmse: 0.2131 - smape: 0.3751 - val_ia: 0.5261 - val_loss: 0.0139 - val_mae: 0.0851 - val_rmse: 0.0975 - val_smape: 0.2358

Epoch 20/32

4586/4586 - 67s - 15ms/step - ia: 0.8861 - loss: 0.0512 - mae: 0.1657 - rmse: 0.2120 - smape: 0.3714 - val_ia: 0.5070 - val_loss: 0.0171 - val_mae: 0.0960 - val_rmse: 0.1083 - val_smape: 0.3010

Epoch 21/32

4586/4586 - 81s - 18ms/step - ia: 0.8866 - loss: 0.0506 - mae: 0.1649 - rmse: 0.2109 - smape: 0.3699 - val_ia: 0.5192 - val_loss: 0.0162 - val_mae: 0.0924 - val_rmse: 0.1047 - val_smape: 0.2871

Epoch 22/32

4586/4586 - 67s - 15ms/step - ia: 0.8872 - loss: 0.0495 - mae: 0.1640 - rmse: 0.2088 - smape: 0.3701 - val_ia: 0.5365 - val_loss: 0.0143 - val_mae: 0.0857 - val_rmse: 0.0979 - val_smape: 0.2816

Epoch 23/32

4586/4586 - 64s - 14ms/step - ia: 0.8871 - loss: 0.0497 - mae: 0.1641 - rmse: 0.2091 - smape: 0.3680 - val_ia: 0.5489 - val_loss: 0.0122 - val_mae: 0.0792 - val_rmse: 0.0914 - val_smape: 0.2388

Epoch 24/32

4586/4586 - 83s - 18ms/step - ia: 0.8872 - loss: 0.0497 - mae: 0.1638 - rmse: 0.2090 - smape: 0.3666 - val_ia: 0.5559 - val_loss: 0.0120 - val_mae: 0.0773 - val_rmse: 0.0895 - val_smape: 0.2369

Epoch 25/32

4586/4586 - 67s - 15ms/step - ia: 0.8872 - loss: 0.0506 - mae: 0.1643 - rmse: 0.2102 - smape: 0.3667 - val_ia: 0.5533 - val_loss: 0.0116 - val_mae: 0.0763 - val_rmse: 0.0886 - val_smape: 0.2172

Epoch 26/32

4586/4586 - 65s - 14ms/step - ia: 0.8889 - loss: 0.0488 - mae: 0.1620 - rmse: 0.2067 - smape: 0.3638 - val_ia: 0.5497 - val_loss: 0.0124 - val_mae: 0.0796 - val_rmse: 0.0918 - val_smape: 0.2473

Epoch 27/32

4586/4586 - 65s - 14ms/step - ia: 0.8893 - loss: 0.0487 - mae: 0.1613 - rmse: 0.2065 - smape: 0.3602 - val_ia: 0.5428 - val_loss: 0.0124 - val_mae: 0.0806 - val_rmse: 0.0923 - val_smape: 0.2254

Epoch 28/32

4586/4586 - 68s - 15ms/step - ia: 0.8882 - loss: 0.0489 - mae: 0.1618 - rmse: 0.2070 - smape: 0.3619 - val_ia: 0.5439 - val_loss: 0.0129 - val_mae: 0.0813 - val_rmse: 0.0934 - val_smape: 0.2423

Epoch 29/32

4586/4586 - 68s - 15ms/step - ia: 0.8902 - loss: 0.0476 - mae: 0.1597 - rmse: 0.2044 - smape: 0.3577 - val_ia: 0.5312 - val_loss: 0.0148 - val_mae: 0.0883 - val_rmse: 0.1001 - val_smape: 0.2690

Epoch 30/32

4586/4586 - 70s - 15ms/step - ia: 0.8898 - loss: 0.0477 - mae: 0.1600 - rmse: 0.2046 - smape: 0.3586 - val_ia: 0.5527 - val_loss: 0.0118 - val_mae: 0.0774 - val_rmse: 0.0893 - val_smape: 0.2299

Epoch 31/32

4586/4586 - 65s - 14ms/step - ia: 0.8895 - loss: 0.0485 - mae: 0.1603 - rmse: 0.2057 - smape: 0.3560 - val_ia: 0.5465 - val_loss: 0.0132 - val_mae: 0.0821 - val_rmse: 0.0942 - val_smape: 0.2515

Epoch 32/32

4586/4586 - 68s - 15ms/step - ia: 0.8905 - loss: 0.0476 - mae: 0.1591 - rmse: 0.2038 - smape: 0.3546 - val_ia: 0.5553 - val_loss: 0.0115 - val_mae: 0.0766 - val_rmse: 0.0888 - val_smape: 0.2242

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8:10 3s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step

 40%|████      | 20/50 [4:21:28<10:35:23, 1270.79s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2293/2293 - 58s - 25ms/step - ia: 0.6481 - loss: 0.3439 - mae: 0.4475 - rmse: 0.5537 - smape: 0.8852 - val_ia: 0.2930 - val_loss: 0.2984 - val_mae: 0.4460 - val_rmse: 0.4809 - val_smape: 0.8670

Epoch 2/64

2293/2293 - 30s - 13ms/step - ia: 0.7955 - loss: 0.1627 - mae: 0.3060 - rmse: 0.3935 - smape: 0.6389 - val_ia: 0.3213 - val_loss: 0.2328 - val_mae: 0.3910 - val_rmse: 0.4239 - val_smape: 0.8165

Epoch 3/64

2293/2293 - 31s - 13ms/step - ia: 0.8393 - loss: 0.1045 - mae: 0.2422 - rmse: 0.3132 - smape: 0.5451 - val_ia: 0.4151 - val_loss: 0.1302 - val_mae: 0.2805 - val_rmse: 0.3135 - val_smape: 0.6523

Epoch 4/64

2293/2293 - 30s - 13ms/step - ia: 0.8851 - loss: 0.0577 - mae: 0.1761 - rmse: 0.2312 - smape: 0.4348 - val_ia: 0.4675 - val_loss: 0.0925 - val_mae: 0.2326 - val_rmse: 0.2627 - val_smape: 0.5457

Epoch 5/64

2293/2293 - 30s - 13ms/step - ia: 0.9052 - loss: 0.0419 - mae: 0.1463 - rmse: 0.1967 - smape: 0.3764 - val_ia: 0.4908 - val_loss: 0.0733 - val_mae: 0.2074 - val_rmse: 0.2358 - val_smape: 0.4970

Epoch 6/64

2293/2293 - 30s - 13ms/step - ia: 0.9172 - loss: 0.0336 - mae: 0.1282 - rmse: 0.1757 - smape: 0.3371 - val_ia: 0.5157 - val_loss: 0.0597 - val_mae: 0.1863 - val_rmse: 0.2142 - val_smape: 0.4561

Epoch 7/64

2293/2293 - 29s - 13ms/step - ia: 0.9256 - loss: 0.0279 - mae: 0.1152 - rmse: 0.1596 - smape: 0.3064 - val_ia: 0.5334 - val_loss: 0.0507 - val_mae: 0.1723 - val_rmse: 0.1988 - val_smape: 0.4345

Epoch 8/64

2293/2293 - 32s - 14ms/step - ia: 0.9324 - loss: 0.0237 - mae: 0.1054 - rmse: 0.1467 - smape: 0.2822 - val_ia: 0.5629 - val_loss: 0.0410 - val_mae: 0.1520 - val_rmse: 0.1785 - val_smape: 0.3832

Epoch 9/64

2293/2293 - 29s - 12ms/step - ia: 0.9377 - loss: 0.0202 - mae: 0.0969 - rmse: 0.1351 - smape: 0.2617 - val_ia: 0.5890 - val_loss: 0.0337 - val_mae: 0.1368 - val_rmse: 0.1615 - val_smape: 0.3465

Epoch 10/64

2293/2293 - 29s - 13ms/step - ia: 0.9431 - loss: 0.0169 - mae: 0.0887 - rmse: 0.1234 - smape: 0.2443 - val_ia: 0.6154 - val_loss: 0.0273 - val_mae: 0.1226 - val_rmse: 0.1459 - val_smape: 0.3160

Epoch 11/64

2293/2293 - 28s - 12ms/step - ia: 0.9482 - loss: 0.0140 - mae: 0.0810 - rmse: 0.1123 - smape: 0.2296 - val_ia: 0.6358 - val_loss: 0.0233 - val_mae: 0.1132 - val_rmse: 0.1350 - val_smape: 0.2891

Epoch 12/64

2293/2293 - 30s - 13ms/step - ia: 0.9523 - loss: 0.0117 - mae: 0.0743 - rmse: 0.1022 - smape: 0.2167 - val_ia: 0.6698 - val_loss: 0.0178 - val_mae: 0.0984 - val_rmse: 0.1179 - val_smape: 0.2704

Epoch 13/64

2293/2293 - 30s - 13ms/step - ia: 0.9555 - loss: 0.0101 - mae: 0.0692 - rmse: 0.0949 - smape: 0.2066 - val_ia: 0.6777 - val_loss: 0.0168 - val_mae: 0.0966 - val_rmse: 0.1146 - val_smape: 0.2772

Epoch 14/64

2293/2293 - 30s - 13ms/step - ia: 0.9582 - loss: 0.0090 - mae: 0.0653 - rmse: 0.0893 - smape: 0.1982 - val_ia: 0.6992 - val_loss: 0.0140 - val_mae: 0.0876 - val_rmse: 0.1045 - val_smape: 0.2591

Epoch 15/64

2293/2293 - 30s - 13ms/step - ia: 0.9604 - loss: 0.0082 - mae: 0.0620 - rmse: 0.0848 - smape: 0.1897 - val_ia: 0.7090 - val_loss: 0.0129 - val_mae: 0.0840 - val_rmse: 0.1000 - val_smape: 0.2500

Epoch 16/64

2293/2293 - 30s - 13ms/step - ia: 0.9622 - loss: 0.0075 - mae: 0.0590 - rmse: 0.0806 - smape: 0.1828 - val_ia: 0.7170 - val_loss: 0.0121 - val_mae: 0.0811 - val_rmse: 0.0965 - val_smape: 0.2487

Epoch 17/64

2293/2293 - 30s - 13ms/step - ia: 0.9641 - loss: 0.0068 - mae: 0.0560 - rmse: 0.0769 - smape: 0.1762 - val_ia: 0.7291 - val_loss: 0.0106 - val_mae: 0.0758 - val_rmse: 0.0904 - val_smape: 0.2350

Epoch 18/64

2293/2293 - 26s - 12ms/step - ia: 0.9658 - loss: 0.0062 - mae: 0.0534 - rmse: 0.0731 - smape: 0.1696 - val_ia: 0.7429 - val_loss: 0.0092 - val_mae: 0.0706 - val_rmse: 0.0844 - val_smape: 0.2219

Epoch 19/64

2293/2293 - 31s - 13ms/step - ia: 0.9675 - loss: 0.0057 - mae: 0.0507 - rmse: 0.0697 - smape: 0.1638 - val_ia: 0.7469 - val_loss: 0.0087 - val_mae: 0.0688 - val_rmse: 0.0820 - val_smape: 0.2220

Epoch 20/64

2293/2293 - 44s - 19ms/step - ia: 0.9691 - loss: 0.0053 - mae: 0.0483 - rmse: 0.0666 - smape: 0.1570 - val_ia: 0.7543 - val_loss: 0.0081 - val_mae: 0.0661 - val_rmse: 0.0787 - val_smape: 0.2146

Epoch 21/64

2293/2293 - 29s - 13ms/step - ia: 0.9704 - loss: 0.0049 - mae: 0.0461 - rmse: 0.0638 - smape: 0.1525 - val_ia: 0.7504 - val_loss: 0.0083 - val_mae: 0.0672 - val_rmse: 0.0793 - val_smape: 0.2198

Epoch 22/64

2293/2293 - 27s - 12ms/step - ia: 0.9715 - loss: 0.0045 - mae: 0.0444 - rmse: 0.0614 - smape: 0.1483 - val_ia: 0.7546 - val_loss: 0.0077 - val_mae: 0.0652 - val_rmse: 0.0769 - val_smape: 0.2131

Epoch 23/64

2293/2293 - 27s - 12ms/step - ia: 0.9725 - loss: 0.0043 - mae: 0.0429 - rmse: 0.0594 - smape: 0.1443 - val_ia: 0.7708 - val_loss: 0.0068 - val_mae: 0.0606 - val_rmse: 0.0719 - val_smape: 0.2029

Epoch 24/64

2293/2293 - 31s - 14ms/step - ia: 0.9733 - loss: 0.0040 - mae: 0.0416 - rmse: 0.0576 - smape: 0.1416 - val_ia: 0.7808 - val_loss: 0.0060 - val_mae: 0.0569 - val_rmse: 0.0680 - val_smape: 0.1844

Epoch 25/64

2293/2293 - 32s - 14ms/step - ia: 0.9741 - loss: 0.0038 - mae: 0.0404 - rmse: 0.0560 - smape: 0.1391 - val_ia: 0.7744 - val_loss: 0.0063 - val_mae: 0.0588 - val_rmse: 0.0696 - val_smape: 0.1902

Epoch 26/64

2293/2293 - 31s - 14ms/step - ia: 0.9746 - loss: 0.0037 - mae: 0.0396 - rmse: 0.0547 - smape: 0.1373 - val_ia: 0.7841 - val_loss: 0.0056 - val_mae: 0.0553 - val_rmse: 0.0660 - val_smape: 0.1798

Epoch 27/64

2293/2293 - 33s - 14ms/step - ia: 0.9752 - loss: 0.0035 - mae: 0.0387 - rmse: 0.0534 - smape: 0.1347 - val_ia: 0.7828 - val_loss: 0.0056 - val_mae: 0.0555 - val_rmse: 0.0659 - val_smape: 0.1738

Epoch 28/64

2293/2293 - 29s - 12ms/step - ia: 0.9756 - loss: 0.0034 - mae: 0.0380 - rmse: 0.0525 - smape: 0.1334 - val_ia: 0.7938 - val_loss: 0.0050 - val_mae: 0.0525 - val_rmse: 0.0630 - val_smape: 0.1660

Epoch 29/64

2293/2293 - 32s - 14ms/step - ia: 0.9760 - loss: 0.0033 - mae: 0.0374 - rmse: 0.0515 - smape: 0.1329 - val_ia: 0.7981 - val_loss: 0.0048 - val_mae: 0.0510 - val_rmse: 0.0615 - val_smape: 0.1635

Epoch 30/64

2293/2293 - 32s - 14ms/step - ia: 0.9763 - loss: 0.0032 - mae: 0.0367 - rmse: 0.0507 - smape: 0.1313 - val_ia: 0.7848 - val_loss: 0.0053 - val_mae: 0.0542 - val_rmse: 0.0642 - val_smape: 0.1701

Epoch 31/64

2293/2293 - 30s - 13ms/step - ia: 0.9768 - loss: 0.0032 - mae: 0.0363 - rmse: 0.0502 - smape: 0.1302 - val_ia: 0.8023 - val_loss: 0.0044 - val_mae: 0.0491 - val_rmse: 0.0593 - val_smape: 0.1525

Epoch 32/64

2293/2293 - 30s - 13ms/step - ia: 0.9768 - loss: 0.0031 - mae: 0.0360 - rmse: 0.0497 - smape: 0.1297 - val_ia: 0.8007 - val_loss: 0.0045 - val_mae: 0.0496 - val_rmse: 0.0596 - val_smape: 0.1566

Epoch 33/64

2293/2293 - 27s - 12ms/step - ia: 0.9771 - loss: 0.0031 - mae: 0.0357 - rmse: 0.0492 - smape: 0.1289 - val_ia: 0.8054 - val_loss: 0.0042 - val_mae: 0.0479 - val_rmse: 0.0581 - val_smape: 0.1507

Epoch 34/64

2293/2293 - 29s - 12ms/step - ia: 0.9773 - loss: 0.0030 - mae: 0.0354 - rmse: 0.0489 - smape: 0.1279 - val_ia: 0.8055 - val_loss: 0.0042 - val_mae: 0.0474 - val_rmse: 0.0574 - val_smape: 0.1464

Epoch 35/64

2293/2293 - 32s - 14ms/step - ia: 0.9774 - loss: 0.0030 - mae: 0.0352 - rmse: 0.0486 - smape: 0.1276 - val_ia: 0.8076 - val_loss: 0.0041 - val_mae: 0.0474 - val_rmse: 0.0574 - val_smape: 0.1481

Epoch 36/64

2293/2293 - 32s - 14ms/step - ia: 0.9775 - loss: 0.0030 - mae: 0.0350 - rmse: 0.0482 - smape: 0.1277 - val_ia: 0.8122 - val_loss: 0.0039 - val_mae: 0.0460 - val_rmse: 0.0560 - val_smape: 0.1428

Epoch 37/64

2293/2293 - 34s - 15ms/step - ia: 0.9776 - loss: 0.0030 - mae: 0.0349 - rmse: 0.0480 - smape: 0.1273 - val_ia: 0.8025 - val_loss: 0.0043 - val_mae: 0.0487 - val_rmse: 0.0585 - val_smape: 0.1511

Epoch 38/64

2293/2293 - 32s - 14ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0481 - smape: 0.1273 - val_ia: 0.8017 - val_loss: 0.0042 - val_mae: 0.0485 - val_rmse: 0.0583 - val_smape: 0.1491

Epoch 39/64

2293/2293 - 41s - 18ms/step - ia: 0.9777 - loss: 0.0029 - mae: 0.0347 - rmse: 0.0478 - smape: 0.1271 - val_ia: 0.8093 - val_loss: 0.0040 - val_mae: 0.0466 - val_rmse: 0.0564 - val_smape: 0.1452

Epoch 40/64

2293/2293 - 30s - 13ms/step - ia: 0.9778 - loss: 0.0029 - mae: 0.0345 - rmse: 0.0478 - smape: 0.1263 - val_ia: 0.8212 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0535 - val_smape: 0.1362

Epoch 41/64

2293/2293 - 42s - 18ms/step - ia: 0.9778 - loss: 0.0029 - mae: 0.0345 - rmse: 0.0475 - smape: 0.1263 - val_ia: 0.8221 - val_loss: 0.0035 - val_mae: 0.0430 - val_rmse: 0.0529 - val_smape: 0.1337

Epoch 42/64

2293/2293 - 28s - 12ms/step - ia: 0.9778 - loss: 0.0029 - mae: 0.0345 - rmse: 0.0476 - smape: 0.1267 - val_ia: 0.8205 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0540 - val_smape: 0.1361

Epoch 43/64

2293/2293 - 27s - 12ms/step - ia: 0.9780 - loss: 0.0029 - mae: 0.0344 - rmse: 0.0475 - smape: 0.1266 - val_ia: 0.8196 - val_loss: 0.0037 - val_mae: 0.0443 - val_rmse: 0.0543 - val_smape: 0.1416

Epoch 44/64

2293/2293 - 28s - 12ms/step - ia: 0.9780 - loss: 0.0029 - mae: 0.0343 - rmse: 0.0474 - smape: 0.1263 - val_ia: 0.8169 - val_loss: 0.0037 - val_mae: 0.0442 - val_rmse: 0.0541 - val_smape: 0.1367

Epoch 45/64

2293/2293 - 29s - 13ms/step - ia: 0.9779 - loss: 0.0029 - mae: 0.0343 - rmse: 0.0474 - smape: 0.1260 - val_ia: 0.8081 - val_loss: 0.0040 - val_mae: 0.0467 - val_rmse: 0.0564 - val_smape: 0.1410

Epoch 46/64

2293/2293 - 30s - 13ms/step - ia: 0.9780 - loss: 0.0029 - mae: 0.0343 - rmse: 0.0473 - smape: 0.1261 - val_ia: 0.8196 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0537 - val_smape: 0.1395

Epoch 47/64

2293/2293 - 40s - 18ms/step - ia: 0.9780 - loss: 0.0029 - mae: 0.0342 - rmse: 0.0472 - smape: 0.1259 - val_ia: 0.8220 - val_loss: 0.0035 - val_mae: 0.0430 - val_rmse: 0.0532 - val_smape: 0.1370

Epoch 48/64

2293/2293 - 30s - 13ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0471 - smape: 0.1255 - val_ia: 0.8103 - val_loss: 0.0040 - val_mae: 0.0460 - val_rmse: 0.0558 - val_smape: 0.1425

Epoch 49/64

2293/2293 - 29s - 13ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0471 - smape: 0.1257 - val_ia: 0.8172 - val_loss: 0.0037 - val_mae: 0.0443 - val_rmse: 0.0542 - val_smape: 0.1398

Epoch 50/64

2293/2293 - 31s - 13ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0470 - smape: 0.1256 - val_ia: 0.8235 - val_loss: 0.0035 - val_mae: 0.0427 - val_rmse: 0.0526 - val_smape: 0.1348

Epoch 51/64

2293/2293 - 30s - 13ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0469 - smape: 0.1259 - val_ia: 0.8160 - val_loss: 0.0038 - val_mae: 0.0446 - val_rmse: 0.0545 - val_smape: 0.1427

Epoch 52/64

2293/2293 - 29s - 13ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0469 - smape: 0.1255 - val_ia: 0.8136 - val_loss: 0.0039 - val_mae: 0.0455 - val_rmse: 0.0553 - val_smape: 0.1449

Epoch 53/64

2293/2293 - 27s - 12ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0468 - smape: 0.1249 - val_ia: 0.8210 - val_loss: 0.0037 - val_mae: 0.0439 - val_rmse: 0.0538 - val_smape: 0.1392

Epoch 54/64

2293/2293 - 30s - 13ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0469 - smape: 0.1259 - val_ia: 0.8183 - val_loss: 0.0037 - val_mae: 0.0442 - val_rmse: 0.0542 - val_smape: 0.1406

Epoch 55/64

2293/2293 - 48s - 21ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0467 - smape: 0.1251 - val_ia: 0.8086 - val_loss: 0.0041 - val_mae: 0.0474 - val_rmse: 0.0571 - val_smape: 0.1503

Epoch 56/64

2293/2293 - 38s - 17ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0467 - smape: 0.1250 - val_ia: 0.8175 - val_loss: 0.0038 - val_mae: 0.0445 - val_rmse: 0.0543 - val_smape: 0.1378

Epoch 57/64

2293/2293 - 36s - 16ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0467 - smape: 0.1250 - val_ia: 0.8033 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0576 - val_smape: 0.1504

Epoch 58/64

2293/2293 - 30s - 13ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0467 - smape: 0.1250 - val_ia: 0.8094 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0561 - val_smape: 0.1447

Epoch 59/64

2293/2293 - 31s - 14ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0466 - smape: 0.1250 - val_ia: 0.8047 - val_loss: 0.0042 - val_mae: 0.0477 - val_rmse: 0.0576 - val_smape: 0.1513

Epoch 60/64

2293/2293 - 36s - 16ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0337 - rmse: 0.0467 - smape: 0.1246 - val_ia: 0.8202 - val_loss: 0.0037 - val_mae: 0.0437 - val_rmse: 0.0537 - val_smape: 0.1382

Epoch 61/64

2293/2293 - 30s - 13ms/step - ia: 0.9784 - loss: 0.0028 - mae: 0.0337 - rmse: 0.0466 - smape: 0.1246 - val_ia: 0.8156 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0547 - val_smape: 0.1427

Epoch 62/64

2293/2293 - 33s - 14ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0337 - rmse: 0.0465 - smape: 0.1249 - val_ia: 0.8132 - val_loss: 0.0039 - val_mae: 0.0451 - val_rmse: 0.0550 - val_smape: 0.1427

Epoch 63/64

2293/2293 - 33s - 14ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0336 - rmse: 0.0465 - smape: 0.1242 - val_ia: 0.8184 - val_loss: 0.0037 - val_mae: 0.0444 - val_rmse: 0.0543 - val_smape: 0.1380

Epoch 64/64

2293/2293 - 32s - 14ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0337 - rmse: 0.0464 - smape: 0.1248 - val_ia: 0.8093 - val_loss: 0.0041 - val_mae: 0.0463 - val_rmse: 0.0560 - val_smape: 0.1484

Restoring model weights from the end of the best epoch: 50.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16:31 6s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step

 42%|████▏     | 21/50 [4:55:38<12:07:18, 1504.78s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2293/2293 - 128s - 56ms/step - ia: 0.2274 - loss: 1.1017 - mae: 0.8678 - rmse: 1.0388 - smape: 1.5641 - val_ia: 0.1930 - val_loss: 0.8558 - val_mae: 0.7697 - val_rmse: 0.8090 - val_smape: 1.9766

Epoch 2/8

2293/2293 - 71s - 31ms/step - ia: 0.2462 - loss: 0.9894 - mae: 0.8208 - rmse: 0.9829 - smape: 1.5341 - val_ia: 0.2289 - val_loss: 0.5963 - val_mae: 0.6346 - val_rmse: 0.6725 - val_smape: 1.2860

Epoch 3/8

2293/2293 - 60s - 26ms/step - ia: 0.5718 - loss: 0.4920 - mae: 0.5631 - rmse: 0.6876 - smape: 0.9731 - val_ia: 0.2915 - val_loss: 0.3035 - val_mae: 0.4383 - val_rmse: 0.4780 - val_smape: 0.7610

Epoch 4/8

2293/2293 - 80s - 35ms/step - ia: 0.6873 - loss: 0.3426 - mae: 0.4662 - rmse: 0.5762 - smape: 0.7906 - val_ia: 0.3185 - val_loss: 0.2487 - val_mae: 0.3957 - val_rmse: 0.4321 - val_smape: 0.7233

Epoch 5/8

2293/2293 - 49s - 21ms/step - ia: 0.7211 - loss: 0.2804 - mae: 0.4194 - rmse: 0.5205 - smape: 0.7417 - val_ia: 0.3412 - val_loss: 0.2047 - val_mae: 0.3598 - val_rmse: 0.3936 - val_smape: 0.6869

Epoch 6/8

2293/2293 - 48s - 21ms/step - ia: 0.7418 - loss: 0.2447 - mae: 0.3910 - rmse: 0.4864 - smape: 0.7079 - val_ia: 0.3571 - val_loss: 0.1909 - val_mae: 0.3467 - val_rmse: 0.3758 - val_smape: 0.6771

Epoch 7/8

2293/2293 - 47s - 21ms/step - ia: 0.7592 - loss: 0.2188 - mae: 0.3671 - rmse: 0.4595 - smape: 0.6780 - val_ia: 0.3745 - val_loss: 0.1624 - val_mae: 0.3207 - val_rmse: 0.3483 - val_smape: 0.6486

Epoch 8/8

2293/2293 - 54s - 23ms/step - ia: 0.7709 - loss: 0.1979 - mae: 0.3492 - rmse: 0.4368 - smape: 0.6566 - val_ia: 0.3908 - val_loss: 0.1452 - val_mae: 0.3036 - val_rmse: 0.3294 - val_smape: 0.6303

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9:27 4s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step

 44%|████▍     | 22/50 [5:04:46<9:28:15, 1217.68s/trial, best loss: 0.003175567966079766]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 119s - 52ms/step - ia: 0.9150 - loss: 0.0383 - mae: 0.1300 - rmse: 0.1706 - smape: 0.3223 - val_ia: 0.7257 - val_loss: 0.0100 - val_mae: 0.0743 - val_rmse: 0.0903 - val_smape: 0.2251

Epoch 2/128

2293/2293 - 70s - 30ms/step - ia: 0.9526 - loss: 0.0105 - mae: 0.0743 - rmse: 0.0974 - smape: 0.2060 - val_ia: 0.7828 - val_loss: 0.0059 - val_mae: 0.0565 - val_rmse: 0.0689 - val_smape: 0.1585

Epoch 3/128

2293/2293 - 79s - 35ms/step - ia: 0.9594 - loss: 0.0079 - mae: 0.0638 - rmse: 0.0840 - smape: 0.1792 - val_ia: 0.8353 - val_loss: 0.0034 - val_mae: 0.0413 - val_rmse: 0.0525 - val_smape: 0.1212

Epoch 4/128

2293/2293 - 45s - 20ms/step - ia: 0.9630 - loss: 0.0066 - mae: 0.0581 - rmse: 0.0768 - smape: 0.1645 - val_ia: 0.8335 - val_loss: 0.0031 - val_mae: 0.0397 - val_rmse: 0.0507 - val_smape: 0.1261

Epoch 5/128

2293/2293 - 53s - 23ms/step - ia: 0.9647 - loss: 0.0060 - mae: 0.0555 - rmse: 0.0732 - smape: 0.1588 - val_ia: 0.8299 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0522 - val_smape: 0.1365

Epoch 6/128

2293/2293 - 62s - 27ms/step - ia: 0.9659 - loss: 0.0056 - mae: 0.0535 - rmse: 0.0706 - smape: 0.1547 - val_ia: 0.8542 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0452 - val_smape: 0.1132

Epoch 7/128

2293/2293 - 62s - 27ms/step - ia: 0.9665 - loss: 0.0055 - mae: 0.0525 - rmse: 0.0693 - smape: 0.1519 - val_ia: 0.8262 - val_loss: 0.0036 - val_mae: 0.0436 - val_rmse: 0.0542 - val_smape: 0.1259

Epoch 8/128

2293/2293 - 58s - 25ms/step - ia: 0.9672 - loss: 0.0053 - mae: 0.0515 - rmse: 0.0683 - smape: 0.1507 - val_ia: 0.8351 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0491 - val_smape: 0.1197

Epoch 9/128

2293/2293 - 54s - 24ms/step - ia: 0.9675 - loss: 0.0052 - mae: 0.0509 - rmse: 0.0676 - smape: 0.1494 - val_ia: 0.8222 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0516 - val_smape: 0.1277

Epoch 10/128

2293/2293 - 67s - 29ms/step - ia: 0.9681 - loss: 0.0051 - mae: 0.0502 - rmse: 0.0666 - smape: 0.1470 - val_ia: 0.8107 - val_loss: 0.0041 - val_mae: 0.0489 - val_rmse: 0.0590 - val_smape: 0.1473

Epoch 11/128

2293/2293 - 48s - 21ms/step - ia: 0.9681 - loss: 0.0050 - mae: 0.0500 - rmse: 0.0663 - smape: 0.1469 - val_ia: 0.8375 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0483 - val_smape: 0.1167

Epoch 12/128

2293/2293 - 52s - 23ms/step - ia: 0.9683 - loss: 0.0050 - mae: 0.0498 - rmse: 0.0660 - smape: 0.1462 - val_ia: 0.7971 - val_loss: 0.0041 - val_mae: 0.0489 - val_rmse: 0.0591 - val_smape: 0.1331

Epoch 13/128

2293/2293 - 59s - 26ms/step - ia: 0.9687 - loss: 0.0048 - mae: 0.0491 - rmse: 0.0649 - smape: 0.1460 - val_ia: 0.8301 - val_loss: 0.0031 - val_mae: 0.0406 - val_rmse: 0.0506 - val_smape: 0.1207

Epoch 14/128

2293/2293 - 64s - 28ms/step - ia: 0.9687 - loss: 0.0048 - mae: 0.0490 - rmse: 0.0649 - smape: 0.1456 - val_ia: 0.8251 - val_loss: 0.0031 - val_mae: 0.0410 - val_rmse: 0.0511 - val_smape: 0.1316

Epoch 15/128

2293/2293 - 60s - 26ms/step - ia: 0.9691 - loss: 0.0047 - mae: 0.0484 - rmse: 0.0644 - smape: 0.1441 - val_ia: 0.8500 - val_loss: 0.0026 - val_mae: 0.0356 - val_rmse: 0.0460 - val_smape: 0.1114

Epoch 16/128

2293/2293 - 48s - 21ms/step - ia: 0.9690 - loss: 0.0048 - mae: 0.0485 - rmse: 0.0644 - smape: 0.1443 - val_ia: 0.8469 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0470 - val_smape: 0.1111

Epoch 17/128

2293/2293 - 60s - 26ms/step - ia: 0.9694 - loss: 0.0047 - mae: 0.0479 - rmse: 0.0637 - smape: 0.1443 - val_ia: 0.8288 - val_loss: 0.0030 - val_mae: 0.0398 - val_rmse: 0.0497 - val_smape: 0.1339

Epoch 18/128

2293/2293 - 66s - 29ms/step - ia: 0.9696 - loss: 0.0046 - mae: 0.0478 - rmse: 0.0633 - smape: 0.1433 - val_ia: 0.8556 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0450 - val_smape: 0.1080

Epoch 19/128

2293/2293 - 65s - 28ms/step - ia: 0.9697 - loss: 0.0046 - mae: 0.0476 - rmse: 0.0631 - smape: 0.1427 - val_ia: 0.8408 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0469 - val_smape: 0.1155

Epoch 20/128

2293/2293 - 58s - 25ms/step - ia: 0.9697 - loss: 0.0046 - mae: 0.0476 - rmse: 0.0630 - smape: 0.1442 - val_ia: 0.8123 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0541 - val_smape: 0.1224

Epoch 21/128

2293/2293 - 62s - 27ms/step - ia: 0.9697 - loss: 0.0046 - mae: 0.0475 - rmse: 0.0630 - smape: 0.1429 - val_ia: 0.8211 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0557 - val_smape: 0.1265

Epoch 22/128

2293/2293 - 63s - 28ms/step - ia: 0.9700 - loss: 0.0045 - mae: 0.0470 - rmse: 0.0623 - smape: 0.1424 - val_ia: 0.7999 - val_loss: 0.0040 - val_mae: 0.0475 - val_rmse: 0.0575 - val_smape: 0.1386

Epoch 23/128

2293/2293 - 61s - 27ms/step - ia: 0.9701 - loss: 0.0045 - mae: 0.0470 - rmse: 0.0624 - smape: 0.1416 - val_ia: 0.7748 - val_loss: 0.0049 - val_mae: 0.0546 - val_rmse: 0.0640 - val_smape: 0.1652

Epoch 24/128

2293/2293 - 61s - 27ms/step - ia: 0.9701 - loss: 0.0045 - mae: 0.0468 - rmse: 0.0622 - smape: 0.1416 - val_ia: 0.8135 - val_loss: 0.0035 - val_mae: 0.0438 - val_rmse: 0.0536 - val_smape: 0.1207

Epoch 25/128

2293/2293 - 82s - 36ms/step - ia: 0.9702 - loss: 0.0044 - mae: 0.0466 - rmse: 0.0619 - smape: 0.1409 - val_ia: 0.8193 - val_loss: 0.0031 - val_mae: 0.0416 - val_rmse: 0.0516 - val_smape: 0.1310

Epoch 26/128

2293/2293 - 48s - 21ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0464 - rmse: 0.0616 - smape: 0.1418 - val_ia: 0.7917 - val_loss: 0.0043 - val_mae: 0.0497 - val_rmse: 0.0594 - val_smape: 0.1713

Epoch 27/128

2293/2293 - 45s - 19ms/step - ia: 0.9704 - loss: 0.0044 - mae: 0.0465 - rmse: 0.0617 - smape: 0.1411 - val_ia: 0.8307 - val_loss: 0.0030 - val_mae: 0.0399 - val_rmse: 0.0497 - val_smape: 0.1367

Epoch 28/128

2293/2293 - 44s - 19ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0466 - rmse: 0.0619 - smape: 0.1413 - val_ia: 0.8367 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0491 - val_smape: 0.1305

Epoch 29/128

2293/2293 - 51s - 22ms/step - ia: 0.9708 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0609 - smape: 0.1395 - val_ia: 0.8276 - val_loss: 0.0031 - val_mae: 0.0404 - val_rmse: 0.0502 - val_smape: 0.1360

Epoch 30/128

2293/2293 - 53s - 23ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0462 - rmse: 0.0614 - smape: 0.1411 - val_ia: 0.8424 - val_loss: 0.0026 - val_mae: 0.0364 - val_rmse: 0.0463 - val_smape: 0.1102

Epoch 31/128

2293/2293 - 51s - 22ms/step - ia: 0.9707 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0607 - smape: 0.1406 - val_ia: 0.8173 - val_loss: 0.0032 - val_mae: 0.0421 - val_rmse: 0.0517 - val_smape: 0.1332

Epoch 32/128

2293/2293 - 53s - 23ms/step - ia: 0.9709 - loss: 0.0043 - mae: 0.0457 - rmse: 0.0607 - smape: 0.1400 - val_ia: 0.8116 - val_loss: 0.0033 - val_mae: 0.0429 - val_rmse: 0.0527 - val_smape: 0.1353

Epoch 33/128

2293/2293 - 48s - 21ms/step - ia: 0.9708 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0608 - smape: 0.1390 - val_ia: 0.8250 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0496 - val_smape: 0.1168

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step

 46%|████▌     | 23/50 [5:37:43<10:50:26, 1445.42s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 90s - 39ms/step - ia: 0.9099 - loss: 0.0424 - mae: 0.1373 - rmse: 0.1805 - smape: 0.3373 - val_ia: 0.7208 - val_loss: 0.0110 - val_mae: 0.0764 - val_rmse: 0.0934 - val_smape: 0.2014

Epoch 2/128

2293/2293 - 66s - 29ms/step - ia: 0.9499 - loss: 0.0117 - mae: 0.0782 - rmse: 0.1031 - smape: 0.2140 - val_ia: 0.7695 - val_loss: 0.0063 - val_mae: 0.0593 - val_rmse: 0.0726 - val_smape: 0.1728

Epoch 3/128

2293/2293 - 61s - 26ms/step - ia: 0.9583 - loss: 0.0082 - mae: 0.0653 - rmse: 0.0861 - smape: 0.1841 - val_ia: 0.7457 - val_loss: 0.0067 - val_mae: 0.0640 - val_rmse: 0.0754 - val_smape: 0.1745

Epoch 4/128

2293/2293 - 61s - 27ms/step - ia: 0.9624 - loss: 0.0068 - mae: 0.0591 - rmse: 0.0777 - smape: 0.1670 - val_ia: 0.8235 - val_loss: 0.0034 - val_mae: 0.0422 - val_rmse: 0.0530 - val_smape: 0.1301

Epoch 5/128

2293/2293 - 57s - 25ms/step - ia: 0.9645 - loss: 0.0061 - mae: 0.0557 - rmse: 0.0734 - smape: 0.1607 - val_ia: 0.8244 - val_loss: 0.0033 - val_mae: 0.0420 - val_rmse: 0.0524 - val_smape: 0.1291

Epoch 6/128

2293/2293 - 51s - 22ms/step - ia: 0.9659 - loss: 0.0057 - mae: 0.0535 - rmse: 0.0709 - smape: 0.1535 - val_ia: 0.8240 - val_loss: 0.0033 - val_mae: 0.0427 - val_rmse: 0.0529 - val_smape: 0.1369

Epoch 7/128

2293/2293 - 58s - 25ms/step - ia: 0.9665 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0692 - smape: 0.1518 - val_ia: 0.8472 - val_loss: 0.0028 - val_mae: 0.0369 - val_rmse: 0.0474 - val_smape: 0.1136

Epoch 8/128

2293/2293 - 64s - 28ms/step - ia: 0.9675 - loss: 0.0052 - mae: 0.0511 - rmse: 0.0677 - smape: 0.1487 - val_ia: 0.8113 - val_loss: 0.0041 - val_mae: 0.0470 - val_rmse: 0.0568 - val_smape: 0.1599

Epoch 9/128

2293/2293 - 81s - 35ms/step - ia: 0.9678 - loss: 0.0051 - mae: 0.0505 - rmse: 0.0670 - smape: 0.1476 - val_ia: 0.8269 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0507 - val_smape: 0.1164

Epoch 10/128

2293/2293 - 63s - 28ms/step - ia: 0.9679 - loss: 0.0051 - mae: 0.0504 - rmse: 0.0666 - smape: 0.1471 - val_ia: 0.8168 - val_loss: 0.0036 - val_mae: 0.0456 - val_rmse: 0.0559 - val_smape: 0.1374

Epoch 11/128

2293/2293 - 63s - 27ms/step - ia: 0.9682 - loss: 0.0051 - mae: 0.0500 - rmse: 0.0664 - smape: 0.1465 - val_ia: 0.8578 - val_loss: 0.0025 - val_mae: 0.0342 - val_rmse: 0.0447 - val_smape: 0.1076

Epoch 12/128

2293/2293 - 64s - 28ms/step - ia: 0.9682 - loss: 0.0050 - mae: 0.0499 - rmse: 0.0661 - smape: 0.1471 - val_ia: 0.8269 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0509 - val_smape: 0.1235

Epoch 13/128

2293/2293 - 62s - 27ms/step - ia: 0.9687 - loss: 0.0049 - mae: 0.0492 - rmse: 0.0651 - smape: 0.1459 - val_ia: 0.8337 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0497 - val_smape: 0.1181

Epoch 14/128

2293/2293 - 61s - 26ms/step - ia: 0.9687 - loss: 0.0049 - mae: 0.0491 - rmse: 0.0651 - smape: 0.1449 - val_ia: 0.7804 - val_loss: 0.0047 - val_mae: 0.0515 - val_rmse: 0.0612 - val_smape: 0.1418

Epoch 15/128

2293/2293 - 63s - 27ms/step - ia: 0.9690 - loss: 0.0048 - mae: 0.0486 - rmse: 0.0645 - smape: 0.1448 - val_ia: 0.8469 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0477 - val_smape: 0.1165

Epoch 16/128

2293/2293 - 79s - 35ms/step - ia: 0.9692 - loss: 0.0048 - mae: 0.0485 - rmse: 0.0645 - smape: 0.1446 - val_ia: 0.8269 - val_loss: 0.0033 - val_mae: 0.0424 - val_rmse: 0.0527 - val_smape: 0.1247

Epoch 17/128

2293/2293 - 53s - 23ms/step - ia: 0.9696 - loss: 0.0046 - mae: 0.0478 - rmse: 0.0634 - smape: 0.1432 - val_ia: 0.7818 - val_loss: 0.0046 - val_mae: 0.0518 - val_rmse: 0.0617 - val_smape: 0.1434

Epoch 18/128

2293/2293 - 57s - 25ms/step - ia: 0.9692 - loss: 0.0047 - mae: 0.0481 - rmse: 0.0639 - smape: 0.1436 - val_ia: 0.8288 - val_loss: 0.0032 - val_mae: 0.0418 - val_rmse: 0.0521 - val_smape: 0.1255

Epoch 19/128

2293/2293 - 63s - 28ms/step - ia: 0.9695 - loss: 0.0046 - mae: 0.0477 - rmse: 0.0632 - smape: 0.1430 - val_ia: 0.7983 - val_loss: 0.0040 - val_mae: 0.0482 - val_rmse: 0.0580 - val_smape: 0.1411

Epoch 20/128

2293/2293 - 60s - 26ms/step - ia: 0.9698 - loss: 0.0046 - mae: 0.0475 - rmse: 0.0630 - smape: 0.1432 - val_ia: 0.7752 - val_loss: 0.0048 - val_mae: 0.0533 - val_rmse: 0.0627 - val_smape: 0.1537

Epoch 21/128

2293/2293 - 83s - 36ms/step - ia: 0.9697 - loss: 0.0046 - mae: 0.0474 - rmse: 0.0629 - smape: 0.1424 - val_ia: 0.8047 - val_loss: 0.0038 - val_mae: 0.0466 - val_rmse: 0.0568 - val_smape: 0.1282

Epoch 22/128

2293/2293 - 60s - 26ms/step - ia: 0.9699 - loss: 0.0045 - mae: 0.0472 - rmse: 0.0626 - smape: 0.1426 - val_ia: 0.8423 - val_loss: 0.0031 - val_mae: 0.0397 - val_rmse: 0.0500 - val_smape: 0.1271

Epoch 23/128

2293/2293 - 61s - 27ms/step - ia: 0.9702 - loss: 0.0045 - mae: 0.0468 - rmse: 0.0622 - smape: 0.1425 - val_ia: 0.8262 - val_loss: 0.0031 - val_mae: 0.0411 - val_rmse: 0.0514 - val_smape: 0.1202

Epoch 24/128

2293/2293 - 60s - 26ms/step - ia: 0.9701 - loss: 0.0045 - mae: 0.0470 - rmse: 0.0625 - smape: 0.1417 - val_ia: 0.8416 - val_loss: 0.0029 - val_mae: 0.0381 - val_rmse: 0.0484 - val_smape: 0.1161

Epoch 25/128

2293/2293 - 65s - 28ms/step - ia: 0.9701 - loss: 0.0045 - mae: 0.0468 - rmse: 0.0621 - smape: 0.1419 - val_ia: 0.8492 - val_loss: 0.0026 - val_mae: 0.0357 - val_rmse: 0.0460 - val_smape: 0.1147

Epoch 26/128

2293/2293 - 51s - 22ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0465 - rmse: 0.0619 - smape: 0.1412 - val_ia: 0.8306 - val_loss: 0.0031 - val_mae: 0.0404 - val_rmse: 0.0504 - val_smape: 0.1296

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:13 2s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step

 48%|████▊     | 24/50 [6:05:29<10:55:03, 1511.66s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 107s - 47ms/step - ia: 0.8188 - loss: 0.1376 - mae: 0.2592 - rmse: 0.3330 - smape: 0.5749 - val_ia: 0.4908 - val_loss: 0.0712 - val_mae: 0.2030 - val_rmse: 0.2341 - val_smape: 0.5333

Epoch 2/128

2293/2293 - 65s - 28ms/step - ia: 0.9112 - loss: 0.0386 - mae: 0.1369 - rmse: 0.1880 - smape: 0.3545 - val_ia: 0.5394 - val_loss: 0.0520 - val_mae: 0.1732 - val_rmse: 0.2011 - val_smape: 0.4663

Epoch 3/128

2293/2293 - 59s - 26ms/step - ia: 0.9277 - loss: 0.0269 - mae: 0.1123 - rmse: 0.1565 - smape: 0.3000 - val_ia: 0.5887 - val_loss: 0.0350 - val_mae: 0.1403 - val_rmse: 0.1652 - val_smape: 0.3811

Epoch 4/128

2293/2293 - 58s - 25ms/step - ia: 0.9424 - loss: 0.0173 - mae: 0.0897 - rmse: 0.1247 - smape: 0.2514 - val_ia: 0.6560 - val_loss: 0.0191 - val_mae: 0.1022 - val_rmse: 0.1225 - val_smape: 0.2777

Epoch 5/128

2293/2293 - 58s - 25ms/step - ia: 0.9562 - loss: 0.0101 - mae: 0.0683 - rmse: 0.0942 - smape: 0.2052 - val_ia: 0.7287 - val_loss: 0.0094 - val_mae: 0.0706 - val_rmse: 0.0860 - val_smape: 0.1925

Epoch 6/128

2293/2293 - 52s - 23ms/step - ia: 0.9642 - loss: 0.0068 - mae: 0.0558 - rmse: 0.0765 - smape: 0.1785 - val_ia: 0.7788 - val_loss: 0.0059 - val_mae: 0.0554 - val_rmse: 0.0689 - val_smape: 0.1686

Epoch 7/128

2293/2293 - 58s - 25ms/step - ia: 0.9690 - loss: 0.0051 - mae: 0.0481 - rmse: 0.0658 - smape: 0.1589 - val_ia: 0.8063 - val_loss: 0.0042 - val_mae: 0.0463 - val_rmse: 0.0583 - val_smape: 0.1351

Epoch 8/128

2293/2293 - 58s - 25ms/step - ia: 0.9724 - loss: 0.0043 - mae: 0.0432 - rmse: 0.0591 - smape: 0.1476 - val_ia: 0.8082 - val_loss: 0.0040 - val_mae: 0.0456 - val_rmse: 0.0571 - val_smape: 0.1294

Epoch 9/128

2293/2293 - 46s - 20ms/step - ia: 0.9739 - loss: 0.0037 - mae: 0.0405 - rmse: 0.0552 - smape: 0.1419 - val_ia: 0.8258 - val_loss: 0.0034 - val_mae: 0.0413 - val_rmse: 0.0522 - val_smape: 0.1193

Epoch 10/128

2293/2293 - 49s - 21ms/step - ia: 0.9753 - loss: 0.0034 - mae: 0.0386 - rmse: 0.0525 - smape: 0.1374 - val_ia: 0.8334 - val_loss: 0.0029 - val_mae: 0.0382 - val_rmse: 0.0486 - val_smape: 0.1196

Epoch 11/128

2293/2293 - 47s - 21ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0372 - rmse: 0.0507 - smape: 0.1339 - val_ia: 0.8252 - val_loss: 0.0030 - val_mae: 0.0398 - val_rmse: 0.0498 - val_smape: 0.1208

Epoch 12/128

2293/2293 - 46s - 20ms/step - ia: 0.9763 - loss: 0.0032 - mae: 0.0369 - rmse: 0.0502 - smape: 0.1336 - val_ia: 0.8443 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0462 - val_smape: 0.1126

Epoch 13/128

2293/2293 - 43s - 19ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0364 - rmse: 0.0497 - smape: 0.1325 - val_ia: 0.8383 - val_loss: 0.0028 - val_mae: 0.0381 - val_rmse: 0.0485 - val_smape: 0.1200

Epoch 14/128

2293/2293 - 47s - 20ms/step - ia: 0.9766 - loss: 0.0031 - mae: 0.0363 - rmse: 0.0495 - smape: 0.1303 - val_ia: 0.8414 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0474 - val_smape: 0.1188

Epoch 15/128

2293/2293 - 41s - 18ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0491 - smape: 0.1310 - val_ia: 0.8326 - val_loss: 0.0029 - val_mae: 0.0393 - val_rmse: 0.0494 - val_smape: 0.1245

Epoch 16/128

2293/2293 - 46s - 20ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0359 - rmse: 0.0490 - smape: 0.1302 - val_ia: 0.8437 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0475 - val_smape: 0.1188

Epoch 17/128

2293/2293 - 43s - 19ms/step - ia: 0.9773 - loss: 0.0030 - mae: 0.0355 - rmse: 0.0486 - smape: 0.1294 - val_ia: 0.8022 - val_loss: 0.0035 - val_mae: 0.0453 - val_rmse: 0.0551 - val_smape: 0.1460

Epoch 18/128

2293/2293 - 83s - 36ms/step - ia: 0.9772 - loss: 0.0030 - mae: 0.0356 - rmse: 0.0486 - smape: 0.1300 - val_ia: 0.8391 - val_loss: 0.0027 - val_mae: 0.0375 - val_rmse: 0.0476 - val_smape: 0.1173

Epoch 19/128

2293/2293 - 45s - 20ms/step - ia: 0.9773 - loss: 0.0030 - mae: 0.0353 - rmse: 0.0483 - smape: 0.1286 - val_ia: 0.8395 - val_loss: 0.0027 - val_mae: 0.0372 - val_rmse: 0.0472 - val_smape: 0.1215

Epoch 20/128

2293/2293 - 51s - 22ms/step - ia: 0.9774 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0482 - smape: 0.1292 - val_ia: 0.8315 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0492 - val_smape: 0.1205

Epoch 21/128

2293/2293 - 52s - 23ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0481 - smape: 0.1276 - val_ia: 0.8318 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0489 - val_smape: 0.1244

Epoch 22/128

2293/2293 - 52s - 23ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0480 - smape: 0.1284 - val_ia: 0.8216 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0514 - val_smape: 0.1210

Epoch 23/128

2293/2293 - 54s - 24ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0478 - smape: 0.1275 - val_ia: 0.8436 - val_loss: 0.0027 - val_mae: 0.0377 - val_rmse: 0.0479 - val_smape: 0.1178

Epoch 24/128

2293/2293 - 51s - 22ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0478 - smape: 0.1278 - val_ia: 0.8513 - val_loss: 0.0025 - val_mae: 0.0353 - val_rmse: 0.0455 - val_smape: 0.1148

Epoch 25/128

2293/2293 - 49s - 22ms/step - ia: 0.9778 - loss: 0.0029 - mae: 0.0346 - rmse: 0.0474 - smape: 0.1268 - val_ia: 0.8391 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0480 - val_smape: 0.1276

Epoch 26/128

2293/2293 - 52s - 23ms/step - ia: 0.9778 - loss: 0.0029 - mae: 0.0346 - rmse: 0.0475 - smape: 0.1269 - val_ia: 0.7967 - val_loss: 0.0041 - val_mae: 0.0487 - val_rmse: 0.0583 - val_smape: 0.1521

Epoch 27/128

2293/2293 - 53s - 23ms/step - ia: 0.9779 - loss: 0.0029 - mae: 0.0345 - rmse: 0.0473 - smape: 0.1265 - val_ia: 0.8420 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0470 - val_smape: 0.1215

Epoch 28/128

2293/2293 - 85s - 37ms/step - ia: 0.9779 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0472 - smape: 0.1259 - val_ia: 0.8323 - val_loss: 0.0028 - val_mae: 0.0382 - val_rmse: 0.0481 - val_smape: 0.1209

Epoch 29/128

2293/2293 - 53s - 23ms/step - ia: 0.9779 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0470 - smape: 0.1266 - val_ia: 0.8440 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0473 - val_smape: 0.1227

Epoch 30/128

2293/2293 - 45s - 20ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0468 - smape: 0.1249 - val_ia: 0.8376 - val_loss: 0.0027 - val_mae: 0.0375 - val_rmse: 0.0476 - val_smape: 0.1189

Epoch 31/128

2293/2293 - 85s - 37ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0342 - rmse: 0.0469 - smape: 0.1257 - val_ia: 0.8376 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0479 - val_smape: 0.1269

Epoch 32/128

2293/2293 - 43s - 19ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0466 - smape: 0.1245 - val_ia: 0.8499 - val_loss: 0.0026 - val_mae: 0.0354 - val_rmse: 0.0458 - val_smape: 0.1145

Epoch 33/128

2293/2293 - 42s - 18ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0465 - smape: 0.1237 - val_ia: 0.8416 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0480 - val_smape: 0.1201

Epoch 34/128

2293/2293 - 49s - 21ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0339 - rmse: 0.0465 - smape: 0.1244 - val_ia: 0.8365 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0500 - val_smape: 0.1252

Epoch 35/128

2293/2293 - 50s - 22ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0339 - rmse: 0.0463 - smape: 0.1244 - val_ia: 0.8433 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0468 - val_smape: 0.1244

Epoch 36/128

2293/2293 - 50s - 22ms/step - ia: 0.9784 - loss: 0.0028 - mae: 0.0337 - rmse: 0.0463 - smape: 0.1244 - val_ia: 0.8305 - val_loss: 0.0031 - val_mae: 0.0409 - val_rmse: 0.0511 - val_smape: 0.1303

Epoch 37/128

2293/2293 - 52s - 22ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0336 - rmse: 0.0461 - smape: 0.1237 - val_ia: 0.8449 - val_loss: 0.0026 - val_mae: 0.0363 - val_rmse: 0.0464 - val_smape: 0.1143

Epoch 38/128

2293/2293 - 52s - 23ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0337 - rmse: 0.0462 - smape: 0.1238 - val_ia: 0.8307 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0488 - val_smape: 0.1244

Epoch 39/128

2293/2293 - 54s - 24ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0336 - rmse: 0.0461 - smape: 0.1232 - val_ia: 0.8226 - val_loss: 0.0032 - val_mae: 0.0418 - val_rmse: 0.0515 - val_smape: 0.1377

Epoch 39: early stopping

Restoring model weights from the end of the best epoch: 24.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 10:41 4s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 35ms/step

 50%|█████     | 25/50 [6:41:09<11:48:23, 1700.13s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 137s - 60ms/step - ia: 0.8849 - loss: 0.0656 - mae: 0.1734 - rmse: 0.2258 - smape: 0.4055 - val_ia: 0.6479 - val_loss: 0.0211 - val_mae: 0.1075 - val_rmse: 0.1285 - val_smape: 0.2998

Epoch 2/128

2293/2293 - 75s - 33ms/step - ia: 0.9415 - loss: 0.0157 - mae: 0.0914 - rmse: 0.1200 - smape: 0.2427 - val_ia: 0.7245 - val_loss: 0.0094 - val_mae: 0.0730 - val_rmse: 0.0875 - val_smape: 0.1952

Epoch 3/128

2293/2293 - 77s - 34ms/step - ia: 0.9527 - loss: 0.0103 - mae: 0.0742 - rmse: 0.0971 - smape: 0.2045 - val_ia: 0.8008 - val_loss: 0.0047 - val_mae: 0.0493 - val_rmse: 0.0618 - val_smape: 0.1480

Epoch 4/128

2293/2293 - 75s - 33ms/step - ia: 0.9581 - loss: 0.0082 - mae: 0.0656 - rmse: 0.0861 - smape: 0.1840 - val_ia: 0.8177 - val_loss: 0.0038 - val_mae: 0.0434 - val_rmse: 0.0550 - val_smape: 0.1305

Epoch 5/128

2293/2293 - 76s - 33ms/step - ia: 0.9616 - loss: 0.0069 - mae: 0.0602 - rmse: 0.0788 - smape: 0.1721 - val_ia: 0.8428 - val_loss: 0.0030 - val_mae: 0.0382 - val_rmse: 0.0491 - val_smape: 0.1180

Epoch 6/128

2293/2293 - 78s - 34ms/step - ia: 0.9637 - loss: 0.0063 - mae: 0.0570 - rmse: 0.0748 - smape: 0.1633 - val_ia: 0.8169 - val_loss: 0.0040 - val_mae: 0.0461 - val_rmse: 0.0569 - val_smape: 0.1301

Epoch 7/128

2293/2293 - 71s - 31ms/step - ia: 0.9649 - loss: 0.0059 - mae: 0.0550 - rmse: 0.0723 - smape: 0.1599 - val_ia: 0.8397 - val_loss: 0.0031 - val_mae: 0.0395 - val_rmse: 0.0503 - val_smape: 0.1180

Epoch 8/128

2293/2293 - 76s - 33ms/step - ia: 0.9659 - loss: 0.0056 - mae: 0.0535 - rmse: 0.0701 - smape: 0.1559 - val_ia: 0.7461 - val_loss: 0.0067 - val_mae: 0.0641 - val_rmse: 0.0742 - val_smape: 0.1422

Epoch 9/128

2293/2293 - 76s - 33ms/step - ia: 0.9667 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0688 - smape: 0.1534 - val_ia: 0.8303 - val_loss: 0.0031 - val_mae: 0.0398 - val_rmse: 0.0503 - val_smape: 0.1201

Epoch 10/128

2293/2293 - 69s - 30ms/step - ia: 0.9673 - loss: 0.0053 - mae: 0.0514 - rmse: 0.0680 - smape: 0.1507 - val_ia: 0.8246 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0540 - val_smape: 0.1387

Epoch 11/128

2293/2293 - 67s - 29ms/step - ia: 0.9675 - loss: 0.0052 - mae: 0.0510 - rmse: 0.0673 - smape: 0.1495 - val_ia: 0.8296 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0516 - val_smape: 0.1337

Epoch 12/128

2293/2293 - 65s - 29ms/step - ia: 0.9680 - loss: 0.0051 - mae: 0.0503 - rmse: 0.0666 - smape: 0.1509 - val_ia: 0.8116 - val_loss: 0.0037 - val_mae: 0.0454 - val_rmse: 0.0554 - val_smape: 0.1409

Epoch 13/128

2293/2293 - 74s - 32ms/step - ia: 0.9682 - loss: 0.0050 - mae: 0.0500 - rmse: 0.0660 - smape: 0.1490 - val_ia: 0.8004 - val_loss: 0.0043 - val_mae: 0.0489 - val_rmse: 0.0586 - val_smape: 0.1549

Epoch 14/128

2293/2293 - 75s - 33ms/step - ia: 0.9685 - loss: 0.0050 - mae: 0.0496 - rmse: 0.0657 - smape: 0.1484 - val_ia: 0.8482 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0470 - val_smape: 0.1134

Epoch 15/128

2293/2293 - 71s - 31ms/step - ia: 0.9686 - loss: 0.0049 - mae: 0.0492 - rmse: 0.0652 - smape: 0.1474 - val_ia: 0.8469 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0468 - val_smape: 0.1158

Epoch 16/128

2293/2293 - 71s - 31ms/step - ia: 0.9687 - loss: 0.0049 - mae: 0.0492 - rmse: 0.0651 - smape: 0.1482 - val_ia: 0.8322 - val_loss: 0.0032 - val_mae: 0.0414 - val_rmse: 0.0515 - val_smape: 0.1386

Epoch 17/128

2293/2293 - 71s - 31ms/step - ia: 0.9691 - loss: 0.0047 - mae: 0.0485 - rmse: 0.0642 - smape: 0.1473 - val_ia: 0.8243 - val_loss: 0.0031 - val_mae: 0.0405 - val_rmse: 0.0505 - val_smape: 0.1247

Epoch 18/128

2293/2293 - 63s - 27ms/step - ia: 0.9688 - loss: 0.0048 - mae: 0.0489 - rmse: 0.0646 - smape: 0.1471 - val_ia: 0.7861 - val_loss: 0.0046 - val_mae: 0.0517 - val_rmse: 0.0613 - val_smape: 0.1627

Epoch 19/128

2293/2293 - 59s - 26ms/step - ia: 0.9691 - loss: 0.0047 - mae: 0.0484 - rmse: 0.0641 - smape: 0.1463 - val_ia: 0.8394 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0482 - val_smape: 0.1243

Epoch 20/128

2293/2293 - 71s - 31ms/step - ia: 0.9693 - loss: 0.0047 - mae: 0.0481 - rmse: 0.0636 - smape: 0.1456 - val_ia: 0.8260 - val_loss: 0.0031 - val_mae: 0.0409 - val_rmse: 0.0510 - val_smape: 0.1392

Epoch 21/128

2293/2293 - 72s - 31ms/step - ia: 0.9696 - loss: 0.0046 - mae: 0.0478 - rmse: 0.0634 - smape: 0.1461 - val_ia: 0.8273 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0541 - val_smape: 0.1436

Epoch 22/128

2293/2293 - 71s - 31ms/step - ia: 0.9694 - loss: 0.0046 - mae: 0.0479 - rmse: 0.0634 - smape: 0.1461 - val_ia: 0.8496 - val_loss: 0.0026 - val_mae: 0.0358 - val_rmse: 0.0464 - val_smape: 0.1167

Epoch 23/128

2293/2293 - 71s - 31ms/step - ia: 0.9697 - loss: 0.0046 - mae: 0.0476 - rmse: 0.0629 - smape: 0.1462 - val_ia: 0.8321 - val_loss: 0.0031 - val_mae: 0.0411 - val_rmse: 0.0511 - val_smape: 0.1308

Epoch 24/128

2293/2293 - 68s - 30ms/step - ia: 0.9697 - loss: 0.0045 - mae: 0.0474 - rmse: 0.0628 - smape: 0.1468 - val_ia: 0.8193 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0517 - val_smape: 0.1259

Epoch 25/128

2293/2293 - 69s - 30ms/step - ia: 0.9699 - loss: 0.0045 - mae: 0.0472 - rmse: 0.0626 - smape: 0.1454 - val_ia: 0.8182 - val_loss: 0.0036 - val_mae: 0.0443 - val_rmse: 0.0543 - val_smape: 0.1517

Epoch 26/128

2293/2293 - 61s - 27ms/step - ia: 0.9700 - loss: 0.0045 - mae: 0.0471 - rmse: 0.0622 - smape: 0.1441 - val_ia: 0.8456 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0476 - val_smape: 0.1190

Epoch 27/128

2293/2293 - 85s - 37ms/step - ia: 0.9700 - loss: 0.0045 - mae: 0.0470 - rmse: 0.0624 - smape: 0.1437 - val_ia: 0.8250 - val_loss: 0.0029 - val_mae: 0.0394 - val_rmse: 0.0494 - val_smape: 0.1179

Epoch 28/128

2293/2293 - 69s - 30ms/step - ia: 0.9702 - loss: 0.0044 - mae: 0.0467 - rmse: 0.0620 - smape: 0.1437 - val_ia: 0.8338 - val_loss: 0.0030 - val_mae: 0.0396 - val_rmse: 0.0496 - val_smape: 0.1305

Epoch 29/128

2293/2293 - 65s - 29ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0468 - rmse: 0.0620 - smape: 0.1432 - val_ia: 0.8009 - val_loss: 0.0040 - val_mae: 0.0477 - val_rmse: 0.0574 - val_smape: 0.1541

Epoch 30/128

2293/2293 - 67s - 29ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0466 - rmse: 0.0618 - smape: 0.1433 - val_ia: 0.8292 - val_loss: 0.0030 - val_mae: 0.0400 - val_rmse: 0.0503 - val_smape: 0.1377

Epoch 31/128

2293/2293 - 72s - 31ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0465 - rmse: 0.0617 - smape: 0.1427 - val_ia: 0.8436 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0475 - val_smape: 0.1246

Epoch 32/128

2293/2293 - 72s - 31ms/step - ia: 0.9706 - loss: 0.0044 - mae: 0.0462 - rmse: 0.0613 - smape: 0.1407 - val_ia: 0.8114 - val_loss: 0.0036 - val_mae: 0.0442 - val_rmse: 0.0540 - val_smape: 0.1338

Epoch 33/128

2293/2293 - 69s - 30ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0467 - rmse: 0.0618 - smape: 0.1425 - val_ia: 0.8411 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0493 - val_smape: 0.1245

Epoch 34/128

2293/2293 - 63s - 28ms/step - ia: 0.9706 - loss: 0.0044 - mae: 0.0461 - rmse: 0.0613 - smape: 0.1430 - val_ia: 0.7610 - val_loss: 0.0055 - val_mae: 0.0581 - val_rmse: 0.0675 - val_smape: 0.1694

Epoch 35/128

2293/2293 - 67s - 29ms/step - ia: 0.9704 - loss: 0.0044 - mae: 0.0463 - rmse: 0.0613 - smape: 0.1416 - val_ia: 0.8084 - val_loss: 0.0038 - val_mae: 0.0457 - val_rmse: 0.0553 - val_smape: 0.1545

Epoch 36/128

2293/2293 - 63s - 27ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0464 - rmse: 0.0615 - smape: 0.1428 - val_ia: 0.8312 - val_loss: 0.0029 - val_mae: 0.0392 - val_rmse: 0.0489 - val_smape: 0.1313

Epoch 37/128

2293/2293 - 83s - 36ms/step - ia: 0.9707 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0607 - smape: 0.1417 - val_ia: 0.8274 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0513 - val_smape: 0.1439

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 22.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:10 1s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step

 52%|█████▏    | 26/50 [7:26:01<13:19:04, 1997.68s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 69s - 30ms/step - ia: 0.8470 - loss: 0.1062 - mae: 0.2239 - rmse: 0.2911 - smape: 0.5039 - val_ia: 0.5349 - val_loss: 0.0539 - val_mae: 0.1774 - val_rmse: 0.2040 - val_smape: 0.4694

Epoch 2/128

2293/2293 - 43s - 19ms/step - ia: 0.9182 - loss: 0.0323 - mae: 0.1267 - rmse: 0.1725 - smape: 0.3223 - val_ia: 0.5956 - val_loss: 0.0323 - val_mae: 0.1366 - val_rmse: 0.1594 - val_smape: 0.3851

Epoch 3/128

2293/2293 - 50s - 22ms/step - ia: 0.9330 - loss: 0.0216 - mae: 0.1043 - rmse: 0.1406 - smape: 0.2744 - val_ia: 0.6737 - val_loss: 0.0175 - val_mae: 0.0963 - val_rmse: 0.1169 - val_smape: 0.2687

Epoch 4/128

2293/2293 - 52s - 23ms/step - ia: 0.9423 - loss: 0.0155 - mae: 0.0901 - rmse: 0.1194 - smape: 0.2436 - val_ia: 0.7011 - val_loss: 0.0124 - val_mae: 0.0826 - val_rmse: 0.0996 - val_smape: 0.2314

Epoch 5/128

2293/2293 - 53s - 23ms/step - ia: 0.9484 - loss: 0.0124 - mae: 0.0808 - rmse: 0.1064 - smape: 0.2248 - val_ia: 0.7658 - val_loss: 0.0073 - val_mae: 0.0606 - val_rmse: 0.0759 - val_smape: 0.1781

Epoch 6/128

2293/2293 - 53s - 23ms/step - ia: 0.9523 - loss: 0.0106 - mae: 0.0745 - rmse: 0.0982 - smape: 0.2096 - val_ia: 0.7562 - val_loss: 0.0072 - val_mae: 0.0617 - val_rmse: 0.0756 - val_smape: 0.1751

Epoch 7/128

2293/2293 - 53s - 23ms/step - ia: 0.9555 - loss: 0.0093 - mae: 0.0694 - rmse: 0.0915 - smape: 0.1980 - val_ia: 0.7603 - val_loss: 0.0062 - val_mae: 0.0581 - val_rmse: 0.0708 - val_smape: 0.1750

Epoch 8/128

2293/2293 - 52s - 23ms/step - ia: 0.9579 - loss: 0.0083 - mae: 0.0657 - rmse: 0.0864 - smape: 0.1884 - val_ia: 0.8024 - val_loss: 0.0046 - val_mae: 0.0479 - val_rmse: 0.0603 - val_smape: 0.1431

Epoch 9/128

2293/2293 - 44s - 19ms/step - ia: 0.9601 - loss: 0.0076 - mae: 0.0623 - rmse: 0.0823 - smape: 0.1814 - val_ia: 0.8018 - val_loss: 0.0044 - val_mae: 0.0473 - val_rmse: 0.0589 - val_smape: 0.1519

Epoch 10/128

2293/2293 - 49s - 21ms/step - ia: 0.9617 - loss: 0.0071 - mae: 0.0602 - rmse: 0.0794 - smape: 0.1757 - val_ia: 0.7911 - val_loss: 0.0047 - val_mae: 0.0501 - val_rmse: 0.0615 - val_smape: 0.1433

Epoch 11/128

2293/2293 - 50s - 22ms/step - ia: 0.9629 - loss: 0.0066 - mae: 0.0581 - rmse: 0.0767 - smape: 0.1716 - val_ia: 0.7899 - val_loss: 0.0046 - val_mae: 0.0507 - val_rmse: 0.0616 - val_smape: 0.1569

Epoch 12/128

2293/2293 - 49s - 21ms/step - ia: 0.9640 - loss: 0.0063 - mae: 0.0564 - rmse: 0.0745 - smape: 0.1680 - val_ia: 0.8097 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0564 - val_smape: 0.1476

Epoch 13/128

2293/2293 - 50s - 22ms/step - ia: 0.9650 - loss: 0.0060 - mae: 0.0548 - rmse: 0.0725 - smape: 0.1638 - val_ia: 0.8392 - val_loss: 0.0030 - val_mae: 0.0389 - val_rmse: 0.0497 - val_smape: 0.1214

Epoch 14/128

2293/2293 - 50s - 22ms/step - ia: 0.9655 - loss: 0.0057 - mae: 0.0540 - rmse: 0.0710 - smape: 0.1611 - val_ia: 0.8292 - val_loss: 0.0033 - val_mae: 0.0406 - val_rmse: 0.0516 - val_smape: 0.1209

Epoch 15/128

2293/2293 - 48s - 21ms/step - ia: 0.9663 - loss: 0.0055 - mae: 0.0527 - rmse: 0.0696 - smape: 0.1587 - val_ia: 0.8389 - val_loss: 0.0029 - val_mae: 0.0382 - val_rmse: 0.0489 - val_smape: 0.1232

Epoch 16/128

2293/2293 - 47s - 21ms/step - ia: 0.9670 - loss: 0.0053 - mae: 0.0518 - rmse: 0.0682 - smape: 0.1568 - val_ia: 0.8362 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0494 - val_smape: 0.1169

Epoch 17/128

2293/2293 - 47s - 21ms/step - ia: 0.9675 - loss: 0.0052 - mae: 0.0510 - rmse: 0.0673 - smape: 0.1538 - val_ia: 0.8421 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0478 - val_smape: 0.1181

Epoch 18/128

2293/2293 - 50s - 22ms/step - ia: 0.9680 - loss: 0.0050 - mae: 0.0501 - rmse: 0.0661 - smape: 0.1525 - val_ia: 0.8276 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0514 - val_smape: 0.1361

Epoch 19/128

2293/2293 - 51s - 22ms/step - ia: 0.9686 - loss: 0.0049 - mae: 0.0492 - rmse: 0.0652 - smape: 0.1500 - val_ia: 0.8368 - val_loss: 0.0030 - val_mae: 0.0391 - val_rmse: 0.0497 - val_smape: 0.1204

Epoch 20/128

2293/2293 - 48s - 21ms/step - ia: 0.9686 - loss: 0.0049 - mae: 0.0493 - rmse: 0.0652 - smape: 0.1513 - val_ia: 0.8421 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0471 - val_smape: 0.1226

Epoch 21/128

2293/2293 - 55s - 24ms/step - ia: 0.9689 - loss: 0.0048 - mae: 0.0488 - rmse: 0.0645 - smape: 0.1486 - val_ia: 0.8485 - val_loss: 0.0026 - val_mae: 0.0351 - val_rmse: 0.0455 - val_smape: 0.1150

Epoch 22/128

2293/2293 - 56s - 24ms/step - ia: 0.9691 - loss: 0.0047 - mae: 0.0485 - rmse: 0.0642 - smape: 0.1488 - val_ia: 0.8402 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0478 - val_smape: 0.1256

Epoch 23/128

2293/2293 - 52s - 23ms/step - ia: 0.9695 - loss: 0.0046 - mae: 0.0479 - rmse: 0.0634 - smape: 0.1477 - val_ia: 0.8498 - val_loss: 0.0027 - val_mae: 0.0361 - val_rmse: 0.0468 - val_smape: 0.1110

Epoch 24/128

2293/2293 - 48s - 21ms/step - ia: 0.9695 - loss: 0.0046 - mae: 0.0478 - rmse: 0.0634 - smape: 0.1471 - val_ia: 0.8311 - val_loss: 0.0032 - val_mae: 0.0414 - val_rmse: 0.0517 - val_smape: 0.1338

Epoch 25/128

2293/2293 - 49s - 21ms/step - ia: 0.9696 - loss: 0.0046 - mae: 0.0476 - rmse: 0.0631 - smape: 0.1457 - val_ia: 0.8401 - val_loss: 0.0027 - val_mae: 0.0374 - val_rmse: 0.0476 - val_smape: 0.1212

Epoch 26/128

2293/2293 - 54s - 23ms/step - ia: 0.9698 - loss: 0.0045 - mae: 0.0474 - rmse: 0.0627 - smape: 0.1464 - val_ia: 0.8427 - val_loss: 0.0029 - val_mae: 0.0379 - val_rmse: 0.0485 - val_smape: 0.1219

Epoch 27/128

2293/2293 - 82s - 36ms/step - ia: 0.9698 - loss: 0.0045 - mae: 0.0473 - rmse: 0.0626 - smape: 0.1453 - val_ia: 0.8400 - val_loss: 0.0029 - val_mae: 0.0381 - val_rmse: 0.0483 - val_smape: 0.1257

Epoch 28/128

2293/2293 - 48s - 21ms/step - ia: 0.9700 - loss: 0.0045 - mae: 0.0470 - rmse: 0.0622 - smape: 0.1447 - val_ia: 0.8408 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0486 - val_smape: 0.1186

Epoch 29/128

2293/2293 - 53s - 23ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0465 - rmse: 0.0617 - smape: 0.1440 - val_ia: 0.8247 - val_loss: 0.0035 - val_mae: 0.0435 - val_rmse: 0.0535 - val_smape: 0.1403

Epoch 30/128

2293/2293 - 50s - 22ms/step - ia: 0.9703 - loss: 0.0045 - mae: 0.0465 - rmse: 0.0619 - smape: 0.1435 - val_ia: 0.8380 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0479 - val_smape: 0.1165

Epoch 31/128

2293/2293 - 46s - 20ms/step - ia: 0.9702 - loss: 0.0044 - mae: 0.0465 - rmse: 0.0616 - smape: 0.1437 - val_ia: 0.8407 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0470 - val_smape: 0.1140

Epoch 32/128

2293/2293 - 57s - 25ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0463 - rmse: 0.0614 - smape: 0.1438 - val_ia: 0.8374 - val_loss: 0.0028 - val_mae: 0.0376 - val_rmse: 0.0477 - val_smape: 0.1196

Epoch 33/128

2293/2293 - 49s - 21ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0466 - rmse: 0.0617 - smape: 0.1427 - val_ia: 0.8526 - val_loss: 0.0025 - val_mae: 0.0343 - val_rmse: 0.0446 - val_smape: 0.1109

Epoch 34/128

2293/2293 - 50s - 22ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0462 - rmse: 0.0613 - smape: 0.1427 - val_ia: 0.8231 - val_loss: 0.0033 - val_mae: 0.0421 - val_rmse: 0.0522 - val_smape: 0.1423

Epoch 35/128

2293/2293 - 50s - 22ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0462 - rmse: 0.0615 - smape: 0.1430 - val_ia: 0.8267 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0508 - val_smape: 0.1431

Epoch 36/128

2293/2293 - 48s - 21ms/step - ia: 0.9705 - loss: 0.0044 - mae: 0.0462 - rmse: 0.0615 - smape: 0.1429 - val_ia: 0.8291 - val_loss: 0.0030 - val_mae: 0.0391 - val_rmse: 0.0492 - val_smape: 0.1240

Epoch 37/128

2293/2293 - 56s - 24ms/step - ia: 0.9707 - loss: 0.0043 - mae: 0.0459 - rmse: 0.0610 - smape: 0.1414 - val_ia: 0.8383 - val_loss: 0.0029 - val_mae: 0.0384 - val_rmse: 0.0486 - val_smape: 0.1272

Epoch 38/128

2293/2293 - 78s - 34ms/step - ia: 0.9709 - loss: 0.0043 - mae: 0.0458 - rmse: 0.0609 - smape: 0.1425 - val_ia: 0.8272 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0518 - val_smape: 0.1318

Epoch 39/128

2293/2293 - 49s - 21ms/step - ia: 0.9708 - loss: 0.0043 - mae: 0.0456 - rmse: 0.0608 - smape: 0.1419 - val_ia: 0.8469 - val_loss: 0.0027 - val_mae: 0.0361 - val_rmse: 0.0465 - val_smape: 0.1159

Epoch 40/128

2293/2293 - 82s - 36ms/step - ia: 0.9710 - loss: 0.0043 - mae: 0.0457 - rmse: 0.0608 - smape: 0.1401 - val_ia: 0.8411 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0471 - val_smape: 0.1188

Epoch 41/128

2293/2293 - 50s - 22ms/step - ia: 0.9708 - loss: 0.0043 - mae: 0.0457 - rmse: 0.0609 - smape: 0.1427 - val_ia: 0.8443 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0473 - val_smape: 0.1186

Epoch 42/128

2293/2293 - 49s - 21ms/step - ia: 0.9709 - loss: 0.0043 - mae: 0.0457 - rmse: 0.0607 - smape: 0.1421 - val_ia: 0.8265 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0513 - val_smape: 0.1379

Epoch 43/128

2293/2293 - 50s - 22ms/step - ia: 0.9710 - loss: 0.0043 - mae: 0.0455 - rmse: 0.0604 - smape: 0.1407 - val_ia: 0.8477 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0461 - val_smape: 0.1193

Epoch 44/128

2293/2293 - 48s - 21ms/step - ia: 0.9709 - loss: 0.0043 - mae: 0.0456 - rmse: 0.0606 - smape: 0.1423 - val_ia: 0.8180 - val_loss: 0.0034 - val_mae: 0.0431 - val_rmse: 0.0530 - val_smape: 0.1361

Epoch 45/128

2293/2293 - 44s - 19ms/step - ia: 0.9711 - loss: 0.0042 - mae: 0.0453 - rmse: 0.0602 - smape: 0.1405 - val_ia: 0.8308 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0499 - val_smape: 0.1308

Epoch 46/128

2293/2293 - 48s - 21ms/step - ia: 0.9712 - loss: 0.0042 - mae: 0.0453 - rmse: 0.0600 - smape: 0.1408 - val_ia: 0.8064 - val_loss: 0.0037 - val_mae: 0.0455 - val_rmse: 0.0553 - val_smape: 0.1510

Epoch 47/128

2293/2293 - 48s - 21ms/step - ia: 0.9712 - loss: 0.0042 - mae: 0.0452 - rmse: 0.0601 - smape: 0.1406 - val_ia: 0.8402 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0478 - val_smape: 0.1194

Epoch 48/128

2293/2293 - 50s - 22ms/step - ia: 0.9712 - loss: 0.0042 - mae: 0.0451 - rmse: 0.0600 - smape: 0.1398 - val_ia: 0.8106 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0537 - val_smape: 0.1343

Epoch 48: early stopping

Restoring model weights from the end of the best epoch: 33.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:39 984ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step

 54%|█████▍    | 27/50 [8:07:52<13:44:52, 2151.84s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2293/2293 - 88s - 38ms/step - ia: 0.8965 - loss: 0.0573 - mae: 0.1560 - rmse: 0.2066 - smape: 0.3782 - val_ia: 0.6743 - val_loss: 0.0153 - val_mae: 0.0921 - val_rmse: 0.1098 - val_smape: 0.2522

Epoch 2/256

2293/2293 - 60s - 26ms/step - ia: 0.9649 - loss: 0.0063 - mae: 0.0549 - rmse: 0.0729 - smape: 0.1746 - val_ia: 0.8124 - val_loss: 0.0036 - val_mae: 0.0451 - val_rmse: 0.0556 - val_smape: 0.1442

Epoch 3/256

2293/2293 - 62s - 27ms/step - ia: 0.9726 - loss: 0.0039 - mae: 0.0428 - rmse: 0.0566 - smape: 0.1453 - val_ia: 0.8312 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0493 - val_smape: 0.1250

Epoch 4/256

2293/2293 - 61s - 27ms/step - ia: 0.9742 - loss: 0.0035 - mae: 0.0402 - rmse: 0.0536 - smape: 0.1388 - val_ia: 0.8400 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0473 - val_smape: 0.1193

Epoch 5/256

2293/2293 - 61s - 27ms/step - ia: 0.9745 - loss: 0.0035 - mae: 0.0397 - rmse: 0.0532 - smape: 0.1363 - val_ia: 0.8396 - val_loss: 0.0028 - val_mae: 0.0371 - val_rmse: 0.0475 - val_smape: 0.1285

Epoch 6/256

2293/2293 - 57s - 25ms/step - ia: 0.9755 - loss: 0.0033 - mae: 0.0382 - rmse: 0.0516 - smape: 0.1334 - val_ia: 0.8394 - val_loss: 0.0029 - val_mae: 0.0392 - val_rmse: 0.0494 - val_smape: 0.1212

Epoch 7/256

2293/2293 - 83s - 36ms/step - ia: 0.9757 - loss: 0.0033 - mae: 0.0380 - rmse: 0.0513 - smape: 0.1320 - val_ia: 0.8389 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0470 - val_smape: 0.1242

Epoch 8/256

2293/2293 - 56s - 24ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0374 - rmse: 0.0505 - smape: 0.1299 - val_ia: 0.8466 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0452 - val_smape: 0.1118

Epoch 9/256

2293/2293 - 59s - 26ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0373 - rmse: 0.0505 - smape: 0.1303 - val_ia: 0.8224 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0510 - val_smape: 0.1310

Epoch 10/256

2293/2293 - 59s - 26ms/step - ia: 0.9767 - loss: 0.0030 - mae: 0.0363 - rmse: 0.0493 - smape: 0.1280 - val_ia: 0.7931 - val_loss: 0.0043 - val_mae: 0.0487 - val_rmse: 0.0583 - val_smape: 0.1418

Epoch 11/256

2293/2293 - 59s - 26ms/step - ia: 0.9770 - loss: 0.0030 - mae: 0.0359 - rmse: 0.0489 - smape: 0.1264 - val_ia: 0.7850 - val_loss: 0.0046 - val_mae: 0.0525 - val_rmse: 0.0617 - val_smape: 0.1693

Epoch 12/256

2293/2293 - 60s - 26ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0489 - smape: 0.1274 - val_ia: 0.8559 - val_loss: 0.0023 - val_mae: 0.0331 - val_rmse: 0.0430 - val_smape: 0.1083

Epoch 13/256

2293/2293 - 60s - 26ms/step - ia: 0.9771 - loss: 0.0029 - mae: 0.0357 - rmse: 0.0484 - smape: 0.1262 - val_ia: 0.7872 - val_loss: 0.0044 - val_mae: 0.0494 - val_rmse: 0.0594 - val_smape: 0.1433

Epoch 14/256

2293/2293 - 59s - 26ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0479 - smape: 0.1253 - val_ia: 0.8317 - val_loss: 0.0030 - val_mae: 0.0391 - val_rmse: 0.0491 - val_smape: 0.1315

Epoch 15/256

2293/2293 - 60s - 26ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0475 - smape: 0.1251 - val_ia: 0.8438 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0466 - val_smape: 0.1120

Epoch 16/256

2293/2293 - 60s - 26ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0476 - smape: 0.1241 - val_ia: 0.8491 - val_loss: 0.0027 - val_mae: 0.0367 - val_rmse: 0.0470 - val_smape: 0.1203

Epoch 17/256

2293/2293 - 60s - 26ms/step - ia: 0.9778 - loss: 0.0028 - mae: 0.0347 - rmse: 0.0472 - smape: 0.1254 - val_ia: 0.8392 - val_loss: 0.0027 - val_mae: 0.0370 - val_rmse: 0.0470 - val_smape: 0.1189

Epoch 18/256

2293/2293 - 79s - 35ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0466 - smape: 0.1234 - val_ia: 0.8474 - val_loss: 0.0026 - val_mae: 0.0363 - val_rmse: 0.0465 - val_smape: 0.1135

Epoch 19/256

2293/2293 - 57s - 25ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0340 - rmse: 0.0465 - smape: 0.1226 - val_ia: 0.8419 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0476 - val_smape: 0.1153

Epoch 20/256

2293/2293 - 57s - 25ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0464 - smape: 0.1227 - val_ia: 0.8384 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0465 - val_smape: 0.1195

Epoch 21/256

2293/2293 - 58s - 26ms/step - ia: 0.9783 - loss: 0.0027 - mae: 0.0338 - rmse: 0.0462 - smape: 0.1229 - val_ia: 0.8381 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0494 - val_smape: 0.1210

Epoch 22/256

2293/2293 - 56s - 25ms/step - ia: 0.9783 - loss: 0.0027 - mae: 0.0338 - rmse: 0.0461 - smape: 0.1228 - val_ia: 0.8238 - val_loss: 0.0033 - val_mae: 0.0430 - val_rmse: 0.0529 - val_smape: 0.1387

Epoch 23/256

2293/2293 - 60s - 26ms/step - ia: 0.9785 - loss: 0.0027 - mae: 0.0336 - rmse: 0.0457 - smape: 0.1223 - val_ia: 0.8471 - val_loss: 0.0026 - val_mae: 0.0362 - val_rmse: 0.0461 - val_smape: 0.1231

Epoch 24/256

2293/2293 - 60s - 26ms/step - ia: 0.9786 - loss: 0.0027 - mae: 0.0334 - rmse: 0.0455 - smape: 0.1216 - val_ia: 0.8382 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0493 - val_smape: 0.1174

Epoch 25/256

2293/2293 - 61s - 27ms/step - ia: 0.9784 - loss: 0.0026 - mae: 0.0333 - rmse: 0.0454 - smape: 0.1209 - val_ia: 0.8576 - val_loss: 0.0024 - val_mae: 0.0337 - val_rmse: 0.0436 - val_smape: 0.1069

Epoch 26/256

2293/2293 - 62s - 27ms/step - ia: 0.9787 - loss: 0.0026 - mae: 0.0333 - rmse: 0.0453 - smape: 0.1209 - val_ia: 0.8523 - val_loss: 0.0025 - val_mae: 0.0354 - val_rmse: 0.0451 - val_smape: 0.1154

Epoch 27/256

2293/2293 - 81s - 35ms/step - ia: 0.9787 - loss: 0.0026 - mae: 0.0331 - rmse: 0.0452 - smape: 0.1207 - val_ia: 0.8500 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0463 - val_smape: 0.1127

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:23 2s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step

 56%|█████▌    | 28/50 [8:36:18<12:19:53, 2017.90s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 102s - 44ms/step - ia: 0.9189 - loss: 0.0358 - mae: 0.1245 - rmse: 0.1616 - smape: 0.3045 - val_ia: 0.6967 - val_loss: 0.0121 - val_mae: 0.0862 - val_rmse: 0.0994 - val_smape: 0.2323

Epoch 2/128

2293/2293 - 71s - 31ms/step - ia: 0.9546 - loss: 0.0096 - mae: 0.0713 - rmse: 0.0934 - smape: 0.1925 - val_ia: 0.8213 - val_loss: 0.0039 - val_mae: 0.0446 - val_rmse: 0.0560 - val_smape: 0.1293

Epoch 3/128

2293/2293 - 72s - 31ms/step - ia: 0.9596 - loss: 0.0076 - mae: 0.0632 - rmse: 0.0831 - smape: 0.1708 - val_ia: 0.7399 - val_loss: 0.0066 - val_mae: 0.0651 - val_rmse: 0.0749 - val_smape: 0.1634

Epoch 4/128

2293/2293 - 69s - 30ms/step - ia: 0.9620 - loss: 0.0069 - mae: 0.0597 - rmse: 0.0786 - smape: 0.1652 - val_ia: 0.8380 - val_loss: 0.0031 - val_mae: 0.0407 - val_rmse: 0.0514 - val_smape: 0.1222

Epoch 5/128

2293/2293 - 65s - 28ms/step - ia: 0.9633 - loss: 0.0065 - mae: 0.0577 - rmse: 0.0759 - smape: 0.1605 - val_ia: 0.8131 - val_loss: 0.0035 - val_mae: 0.0444 - val_rmse: 0.0548 - val_smape: 0.1309

Epoch 6/128

2293/2293 - 66s - 29ms/step - ia: 0.9647 - loss: 0.0060 - mae: 0.0554 - rmse: 0.0730 - smape: 0.1546 - val_ia: 0.7772 - val_loss: 0.0053 - val_mae: 0.0578 - val_rmse: 0.0676 - val_smape: 0.1812

Epoch 7/128

2293/2293 - 66s - 29ms/step - ia: 0.9650 - loss: 0.0059 - mae: 0.0550 - rmse: 0.0725 - smape: 0.1574 - val_ia: 0.8163 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0546 - val_smape: 0.1294

Epoch 8/128

2293/2293 - 71s - 31ms/step - ia: 0.9661 - loss: 0.0055 - mae: 0.0531 - rmse: 0.0697 - smape: 0.1548 - val_ia: 0.8438 - val_loss: 0.0027 - val_mae: 0.0361 - val_rmse: 0.0467 - val_smape: 0.1113

Epoch 9/128

2293/2293 - 66s - 29ms/step - ia: 0.9660 - loss: 0.0056 - mae: 0.0534 - rmse: 0.0704 - smape: 0.1558 - val_ia: 0.7359 - val_loss: 0.0072 - val_mae: 0.0682 - val_rmse: 0.0781 - val_smape: 0.1764

Epoch 10/128

2293/2293 - 62s - 27ms/step - ia: 0.9668 - loss: 0.0054 - mae: 0.0522 - rmse: 0.0687 - smape: 0.1539 - val_ia: 0.8156 - val_loss: 0.0034 - val_mae: 0.0423 - val_rmse: 0.0527 - val_smape: 0.1302

Epoch 11/128

2293/2293 - 62s - 27ms/step - ia: 0.9667 - loss: 0.0054 - mae: 0.0522 - rmse: 0.0686 - smape: 0.1541 - val_ia: 0.8171 - val_loss: 0.0038 - val_mae: 0.0464 - val_rmse: 0.0567 - val_smape: 0.1405

Epoch 12/128

2293/2293 - 65s - 28ms/step - ia: 0.9670 - loss: 0.0053 - mae: 0.0518 - rmse: 0.0681 - smape: 0.1532 - val_ia: 0.8400 - val_loss: 0.0036 - val_mae: 0.0414 - val_rmse: 0.0522 - val_smape: 0.1111

Epoch 13/128

2293/2293 - 62s - 27ms/step - ia: 0.9674 - loss: 0.0052 - mae: 0.0512 - rmse: 0.0674 - smape: 0.1522 - val_ia: 0.8431 - val_loss: 0.0028 - val_mae: 0.0385 - val_rmse: 0.0485 - val_smape: 0.1152

Epoch 14/128

2293/2293 - 65s - 28ms/step - ia: 0.9676 - loss: 0.0051 - mae: 0.0508 - rmse: 0.0669 - smape: 0.1514 - val_ia: 0.8281 - val_loss: 0.0030 - val_mae: 0.0399 - val_rmse: 0.0498 - val_smape: 0.1280

Epoch 15/128

2293/2293 - 69s - 30ms/step - ia: 0.9676 - loss: 0.0051 - mae: 0.0508 - rmse: 0.0668 - smape: 0.1531 - val_ia: 0.7856 - val_loss: 0.0044 - val_mae: 0.0509 - val_rmse: 0.0604 - val_smape: 0.1538

Epoch 16/128

2293/2293 - 58s - 25ms/step - ia: 0.9682 - loss: 0.0049 - mae: 0.0498 - rmse: 0.0655 - smape: 0.1506 - val_ia: 0.8345 - val_loss: 0.0031 - val_mae: 0.0406 - val_rmse: 0.0508 - val_smape: 0.1233

Epoch 17/128

2293/2293 - 58s - 25ms/step - ia: 0.9682 - loss: 0.0049 - mae: 0.0499 - rmse: 0.0657 - smape: 0.1494 - val_ia: 0.8539 - val_loss: 0.0024 - val_mae: 0.0344 - val_rmse: 0.0445 - val_smape: 0.1105

Epoch 18/128

2293/2293 - 59s - 26ms/step - ia: 0.9684 - loss: 0.0049 - mae: 0.0496 - rmse: 0.0655 - smape: 0.1487 - val_ia: 0.8210 - val_loss: 0.0031 - val_mae: 0.0414 - val_rmse: 0.0514 - val_smape: 0.1200

Epoch 19/128

2293/2293 - 81s - 35ms/step - ia: 0.9684 - loss: 0.0049 - mae: 0.0497 - rmse: 0.0656 - smape: 0.1492 - val_ia: 0.8188 - val_loss: 0.0031 - val_mae: 0.0414 - val_rmse: 0.0513 - val_smape: 0.1252

Epoch 20/128

2293/2293 - 58s - 25ms/step - ia: 0.9691 - loss: 0.0047 - mae: 0.0486 - rmse: 0.0641 - smape: 0.1469 - val_ia: 0.7820 - val_loss: 0.0044 - val_mae: 0.0511 - val_rmse: 0.0610 - val_smape: 0.1728

Epoch 21/128

2293/2293 - 58s - 25ms/step - ia: 0.9690 - loss: 0.0047 - mae: 0.0485 - rmse: 0.0640 - smape: 0.1469 - val_ia: 0.8100 - val_loss: 0.0038 - val_mae: 0.0462 - val_rmse: 0.0559 - val_smape: 0.1494

Epoch 22/128

2293/2293 - 57s - 25ms/step - ia: 0.9689 - loss: 0.0048 - mae: 0.0487 - rmse: 0.0645 - smape: 0.1463 - val_ia: 0.8297 - val_loss: 0.0031 - val_mae: 0.0411 - val_rmse: 0.0513 - val_smape: 0.1299

Epoch 23/128

2293/2293 - 58s - 25ms/step - ia: 0.9694 - loss: 0.0046 - mae: 0.0479 - rmse: 0.0632 - smape: 0.1460 - val_ia: 0.8176 - val_loss: 0.0034 - val_mae: 0.0444 - val_rmse: 0.0541 - val_smape: 0.1280

Epoch 24/128

2293/2293 - 57s - 25ms/step - ia: 0.9687 - loss: 0.0047 - mae: 0.0488 - rmse: 0.0642 - smape: 0.1473 - val_ia: 0.8278 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0498 - val_smape: 0.1141

Epoch 25/128

2293/2293 - 57s - 25ms/step - ia: 0.9698 - loss: 0.0045 - mae: 0.0472 - rmse: 0.0625 - smape: 0.1437 - val_ia: 0.8272 - val_loss: 0.0031 - val_mae: 0.0404 - val_rmse: 0.0502 - val_smape: 0.1180

Epoch 26/128

2293/2293 - 58s - 25ms/step - ia: 0.9696 - loss: 0.0046 - mae: 0.0476 - rmse: 0.0629 - smape: 0.1455 - val_ia: 0.7894 - val_loss: 0.0049 - val_mae: 0.0543 - val_rmse: 0.0641 - val_smape: 0.1526

Epoch 27/128

2293/2293 - 57s - 25ms/step - ia: 0.9699 - loss: 0.0045 - mae: 0.0472 - rmse: 0.0623 - smape: 0.1429 - val_ia: 0.8031 - val_loss: 0.0038 - val_mae: 0.0458 - val_rmse: 0.0554 - val_smape: 0.1490

Epoch 28/128

2293/2293 - 56s - 25ms/step - ia: 0.9701 - loss: 0.0044 - mae: 0.0469 - rmse: 0.0620 - smape: 0.1435 - val_ia: 0.8519 - val_loss: 0.0026 - val_mae: 0.0363 - val_rmse: 0.0464 - val_smape: 0.1185

Epoch 29/128

2293/2293 - 57s - 25ms/step - ia: 0.9698 - loss: 0.0045 - mae: 0.0471 - rmse: 0.0623 - smape: 0.1429 - val_ia: 0.8153 - val_loss: 0.0037 - val_mae: 0.0457 - val_rmse: 0.0557 - val_smape: 0.1487

Epoch 30/128

2293/2293 - 65s - 29ms/step - ia: 0.9703 - loss: 0.0044 - mae: 0.0464 - rmse: 0.0614 - smape: 0.1427 - val_ia: 0.8085 - val_loss: 0.0036 - val_mae: 0.0448 - val_rmse: 0.0548 - val_smape: 0.1319

Epoch 31/128

2293/2293 - 67s - 29ms/step - ia: 0.9704 - loss: 0.0044 - mae: 0.0464 - rmse: 0.0614 - smape: 0.1417 - val_ia: 0.8107 - val_loss: 0.0037 - val_mae: 0.0455 - val_rmse: 0.0557 - val_smape: 0.1361

Epoch 32/128

2293/2293 - 74s - 32ms/step - ia: 0.9706 - loss: 0.0043 - mae: 0.0462 - rmse: 0.0611 - smape: 0.1405 - val_ia: 0.8280 - val_loss: 0.0033 - val_mae: 0.0422 - val_rmse: 0.0526 - val_smape: 0.1425

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:01 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step

 58%|█████▊    | 29/50 [9:10:50<11:51:58, 2034.19s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2293/2293 - 34s - 15ms/step - ia: 0.8775 - loss: 0.0792 - mae: 0.1768 - rmse: 0.2310 - smape: 0.4160 - val_ia: 0.6610 - val_loss: 0.0206 - val_mae: 0.1042 - val_rmse: 0.1249 - val_smape: 0.2709

Epoch 2/64

2293/2293 - 24s - 10ms/step - ia: 0.9584 - loss: 0.0089 - mae: 0.0650 - rmse: 0.0877 - smape: 0.1945 - val_ia: 0.7699 - val_loss: 0.0068 - val_mae: 0.0613 - val_rmse: 0.0737 - val_smape: 0.1810

Epoch 3/64

2293/2293 - 23s - 10ms/step - ia: 0.9711 - loss: 0.0044 - mae: 0.0452 - rmse: 0.0609 - smape: 0.1518 - val_ia: 0.7713 - val_loss: 0.0053 - val_mae: 0.0562 - val_rmse: 0.0669 - val_smape: 0.1573

Epoch 4/64

2293/2293 - 24s - 10ms/step - ia: 0.9747 - loss: 0.0035 - mae: 0.0395 - rmse: 0.0532 - smape: 0.1388 - val_ia: 0.8156 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0533 - val_smape: 0.1221

Epoch 5/64

2293/2293 - 23s - 10ms/step - ia: 0.9756 - loss: 0.0033 - mae: 0.0380 - rmse: 0.0514 - smape: 0.1353 - val_ia: 0.8105 - val_loss: 0.0041 - val_mae: 0.0474 - val_rmse: 0.0577 - val_smape: 0.1520

Epoch 6/64

2293/2293 - 24s - 10ms/step - ia: 0.9762 - loss: 0.0032 - mae: 0.0372 - rmse: 0.0505 - smape: 0.1325 - val_ia: 0.8426 - val_loss: 0.0029 - val_mae: 0.0379 - val_rmse: 0.0486 - val_smape: 0.1177

Epoch 7/64

2293/2293 - 24s - 11ms/step - ia: 0.9766 - loss: 0.0031 - mae: 0.0366 - rmse: 0.0497 - smape: 0.1312 - val_ia: 0.8344 - val_loss: 0.0031 - val_mae: 0.0388 - val_rmse: 0.0497 - val_smape: 0.1172

Epoch 8/64

2293/2293 - 24s - 10ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0366 - rmse: 0.0497 - smape: 0.1306 - val_ia: 0.8249 - val_loss: 0.0035 - val_mae: 0.0432 - val_rmse: 0.0542 - val_smape: 0.1363

Epoch 9/64

2293/2293 - 27s - 12ms/step - ia: 0.9769 - loss: 0.0030 - mae: 0.0359 - rmse: 0.0489 - smape: 0.1298 - val_ia: 0.8282 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0526 - val_smape: 0.1276

Epoch 10/64

2293/2293 - 23s - 10ms/step - ia: 0.9771 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0487 - smape: 0.1292 - val_ia: 0.8264 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0508 - val_smape: 0.1226

Epoch 11/64

2293/2293 - 23s - 10ms/step - ia: 0.9771 - loss: 0.0030 - mae: 0.0356 - rmse: 0.0484 - smape: 0.1277 - val_ia: 0.8405 - val_loss: 0.0030 - val_mae: 0.0396 - val_rmse: 0.0498 - val_smape: 0.1196

Epoch 12/64

2293/2293 - 23s - 10ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0480 - smape: 0.1269 - val_ia: 0.8586 - val_loss: 0.0024 - val_mae: 0.0336 - val_rmse: 0.0440 - val_smape: 0.1105

Epoch 13/64

2293/2293 - 23s - 10ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0349 - rmse: 0.0476 - smape: 0.1274 - val_ia: 0.8263 - val_loss: 0.0031 - val_mae: 0.0400 - val_rmse: 0.0503 - val_smape: 0.1243

Epoch 14/64

2293/2293 - 23s - 10ms/step - ia: 0.9777 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0475 - smape: 0.1262 - val_ia: 0.8290 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0513 - val_smape: 0.1309

Epoch 15/64

2293/2293 - 23s - 10ms/step - ia: 0.9779 - loss: 0.0029 - mae: 0.0345 - rmse: 0.0472 - smape: 0.1261 - val_ia: 0.8541 - val_loss: 0.0025 - val_mae: 0.0350 - val_rmse: 0.0451 - val_smape: 0.1160

Epoch 16/64

2293/2293 - 23s - 10ms/step - ia: 0.9777 - loss: 0.0029 - mae: 0.0346 - rmse: 0.0472 - smape: 0.1250 - val_ia: 0.8377 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0491 - val_smape: 0.1216

Epoch 17/64

2293/2293 - 23s - 10ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0469 - smape: 0.1256 - val_ia: 0.8367 - val_loss: 0.0032 - val_mae: 0.0397 - val_rmse: 0.0505 - val_smape: 0.1235

Epoch 18/64

2293/2293 - 23s - 10ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0468 - smape: 0.1245 - val_ia: 0.8406 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0493 - val_smape: 0.1237

Epoch 19/64

2293/2293 - 23s - 10ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0466 - smape: 0.1245 - val_ia: 0.8488 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0471 - val_smape: 0.1136

Epoch 20/64

2293/2293 - 23s - 10ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0341 - rmse: 0.0467 - smape: 0.1239 - val_ia: 0.8356 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0492 - val_smape: 0.1232

Epoch 21/64

2293/2293 - 23s - 10ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0339 - rmse: 0.0463 - smape: 0.1239 - val_ia: 0.8456 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0468 - val_smape: 0.1172

Epoch 22/64

2293/2293 - 23s - 10ms/step - ia: 0.9784 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0463 - smape: 0.1238 - val_ia: 0.8317 - val_loss: 0.0031 - val_mae: 0.0400 - val_rmse: 0.0507 - val_smape: 0.1200

Epoch 23/64

2293/2293 - 23s - 10ms/step - ia: 0.9784 - loss: 0.0028 - mae: 0.0338 - rmse: 0.0462 - smape: 0.1232 - val_ia: 0.8510 - val_loss: 0.0027 - val_mae: 0.0356 - val_rmse: 0.0462 - val_smape: 0.1126

Epoch 24/64

2293/2293 - 23s - 10ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0337 - rmse: 0.0460 - smape: 0.1235 - val_ia: 0.8501 - val_loss: 0.0028 - val_mae: 0.0367 - val_rmse: 0.0473 - val_smape: 0.1154

Epoch 25/64

2293/2293 - 23s - 10ms/step - ia: 0.9786 - loss: 0.0027 - mae: 0.0334 - rmse: 0.0457 - smape: 0.1228 - val_ia: 0.8485 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0481 - val_smape: 0.1169

Epoch 26/64

2293/2293 - 24s - 10ms/step - ia: 0.9784 - loss: 0.0027 - mae: 0.0335 - rmse: 0.0457 - smape: 0.1237 - val_ia: 0.8505 - val_loss: 0.0028 - val_mae: 0.0368 - val_rmse: 0.0477 - val_smape: 0.1175

Epoch 27/64

2293/2293 - 23s - 10ms/step - ia: 0.9786 - loss: 0.0027 - mae: 0.0333 - rmse: 0.0456 - smape: 0.1220 - val_ia: 0.8405 - val_loss: 0.0030 - val_mae: 0.0386 - val_rmse: 0.0491 - val_smape: 0.1213

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:07 785ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 60%|██████    | 30/50 [9:21:36<8:59:17, 1617.85s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2293/2293 - 74s - 32ms/step - ia: 0.6935 - loss: 0.2956 - mae: 0.4164 - rmse: 0.5203 - smape: 0.8273 - val_ia: 0.3096 - val_loss: 0.2710 - val_mae: 0.4277 - val_rmse: 0.4630 - val_smape: 0.8000

Epoch 2/32

2293/2293 - 77s - 34ms/step - ia: 0.8185 - loss: 0.1298 - mae: 0.2737 - rmse: 0.3494 - smape: 0.5807 - val_ia: 0.4241 - val_loss: 0.1094 - val_mae: 0.2612 - val_rmse: 0.2916 - val_smape: 0.6282

Epoch 3/32

2293/2293 - 59s - 26ms/step - ia: 0.8590 - loss: 0.0814 - mae: 0.2154 - rmse: 0.2775 - smape: 0.4897 - val_ia: 0.4597 - val_loss: 0.0841 - val_mae: 0.2281 - val_rmse: 0.2559 - val_smape: 0.5827

Epoch 4/32

2293/2293 - 61s - 26ms/step - ia: 0.8751 - loss: 0.0666 - mae: 0.1918 - rmse: 0.2504 - smape: 0.4448 - val_ia: 0.4877 - val_loss: 0.0745 - val_mae: 0.2111 - val_rmse: 0.2398 - val_smape: 0.5434

Epoch 5/32

2293/2293 - 60s - 26ms/step - ia: 0.8853 - loss: 0.0583 - mae: 0.1769 - rmse: 0.2341 - smape: 0.4152 - val_ia: 0.5000 - val_loss: 0.0680 - val_mae: 0.2016 - val_rmse: 0.2305 - val_smape: 0.5252

Epoch 6/32

2293/2293 - 60s - 26ms/step - ia: 0.8904 - loss: 0.0534 - mae: 0.1691 - rmse: 0.2235 - smape: 0.3997 - val_ia: 0.5131 - val_loss: 0.0637 - val_mae: 0.1941 - val_rmse: 0.2230 - val_smape: 0.4993

Epoch 7/32

2293/2293 - 60s - 26ms/step - ia: 0.8959 - loss: 0.0488 - mae: 0.1608 - rmse: 0.2135 - smape: 0.3837 - val_ia: 0.5243 - val_loss: 0.0579 - val_mae: 0.1842 - val_rmse: 0.2132 - val_smape: 0.4790

Epoch 8/32

2293/2293 - 60s - 26ms/step - ia: 0.9003 - loss: 0.0447 - mae: 0.1543 - rmse: 0.2045 - smape: 0.3705 - val_ia: 0.5339 - val_loss: 0.0529 - val_mae: 0.1761 - val_rmse: 0.2036 - val_smape: 0.4682

Epoch 9/32

2293/2293 - 60s - 26ms/step - ia: 0.9038 - loss: 0.0417 - mae: 0.1491 - rmse: 0.1972 - smape: 0.3591 - val_ia: 0.5497 - val_loss: 0.0452 - val_mae: 0.1624 - val_rmse: 0.1884 - val_smape: 0.4384

Epoch 10/32

2293/2293 - 62s - 27ms/step - ia: 0.9064 - loss: 0.0394 - mae: 0.1448 - rmse: 0.1918 - smape: 0.3486 - val_ia: 0.5643 - val_loss: 0.0419 - val_mae: 0.1547 - val_rmse: 0.1811 - val_smape: 0.4152

Epoch 11/32

2293/2293 - 60s - 26ms/step - ia: 0.9109 - loss: 0.0361 - mae: 0.1386 - rmse: 0.1839 - smape: 0.3358 - val_ia: 0.5860 - val_loss: 0.0363 - val_mae: 0.1412 - val_rmse: 0.1678 - val_smape: 0.3675

Epoch 12/32

2293/2293 - 59s - 26ms/step - ia: 0.9132 - loss: 0.0339 - mae: 0.1346 - rmse: 0.1781 - smape: 0.3299 - val_ia: 0.5876 - val_loss: 0.0353 - val_mae: 0.1407 - val_rmse: 0.1660 - val_smape: 0.3743

Epoch 13/32

2293/2293 - 56s - 25ms/step - ia: 0.9163 - loss: 0.0319 - mae: 0.1306 - rmse: 0.1728 - smape: 0.3212 - val_ia: 0.6116 - val_loss: 0.0291 - val_mae: 0.1255 - val_rmse: 0.1503 - val_smape: 0.3267

Epoch 14/32

2293/2293 - 61s - 26ms/step - ia: 0.9187 - loss: 0.0300 - mae: 0.1265 - rmse: 0.1674 - smape: 0.3109 - val_ia: 0.6176 - val_loss: 0.0272 - val_mae: 0.1218 - val_rmse: 0.1459 - val_smape: 0.3220

Epoch 15/32

2293/2293 - 60s - 26ms/step - ia: 0.9209 - loss: 0.0283 - mae: 0.1232 - rmse: 0.1626 - smape: 0.3040 - val_ia: 0.6183 - val_loss: 0.0272 - val_mae: 0.1221 - val_rmse: 0.1460 - val_smape: 0.3236

Epoch 16/32

2293/2293 - 63s - 27ms/step - ia: 0.9228 - loss: 0.0269 - mae: 0.1203 - rmse: 0.1586 - smape: 0.2984 - val_ia: 0.6321 - val_loss: 0.0244 - val_mae: 0.1148 - val_rmse: 0.1379 - val_smape: 0.2989

Epoch 17/32

2293/2293 - 64s - 28ms/step - ia: 0.9245 - loss: 0.0259 - mae: 0.1176 - rmse: 0.1555 - smape: 0.2927 - val_ia: 0.6502 - val_loss: 0.0208 - val_mae: 0.1055 - val_rmse: 0.1274 - val_smape: 0.2827

Epoch 18/32

2293/2293 - 65s - 28ms/step - ia: 0.9267 - loss: 0.0244 - mae: 0.1147 - rmse: 0.1510 - smape: 0.2862 - val_ia: 0.6522 - val_loss: 0.0201 - val_mae: 0.1045 - val_rmse: 0.1257 - val_smape: 0.2824

Epoch 19/32

2293/2293 - 63s - 27ms/step - ia: 0.9281 - loss: 0.0233 - mae: 0.1121 - rmse: 0.1477 - smape: 0.2807 - val_ia: 0.6708 - val_loss: 0.0172 - val_mae: 0.0959 - val_rmse: 0.1162 - val_smape: 0.2563

Epoch 20/32

2293/2293 - 63s - 27ms/step - ia: 0.9299 - loss: 0.0222 - mae: 0.1093 - rmse: 0.1438 - smape: 0.2759 - val_ia: 0.6898 - val_loss: 0.0148 - val_mae: 0.0880 - val_rmse: 0.1077 - val_smape: 0.2306

Epoch 21/32

2293/2293 - 63s - 27ms/step - ia: 0.9312 - loss: 0.0215 - mae: 0.1077 - rmse: 0.1415 - smape: 0.2692 - val_ia: 0.6934 - val_loss: 0.0142 - val_mae: 0.0866 - val_rmse: 0.1058 - val_smape: 0.2318

Epoch 22/32

2293/2293 - 66s - 29ms/step - ia: 0.9330 - loss: 0.0205 - mae: 0.1049 - rmse: 0.1380 - smape: 0.2657 - val_ia: 0.6870 - val_loss: 0.0149 - val_mae: 0.0891 - val_rmse: 0.1081 - val_smape: 0.2307

Epoch 23/32

2293/2293 - 63s - 27ms/step - ia: 0.9339 - loss: 0.0199 - mae: 0.1036 - rmse: 0.1360 - smape: 0.2631 - val_ia: 0.7083 - val_loss: 0.0125 - val_mae: 0.0808 - val_rmse: 0.0990 - val_smape: 0.2172

Epoch 24/32

2293/2293 - 63s - 28ms/step - ia: 0.9349 - loss: 0.0193 - mae: 0.1020 - rmse: 0.1342 - smape: 0.2583 - val_ia: 0.7226 - val_loss: 0.0112 - val_mae: 0.0750 - val_rmse: 0.0929 - val_smape: 0.1988

Epoch 25/32

2293/2293 - 62s - 27ms/step - ia: 0.9363 - loss: 0.0185 - mae: 0.0997 - rmse: 0.1309 - smape: 0.2540 - val_ia: 0.7197 - val_loss: 0.0113 - val_mae: 0.0762 - val_rmse: 0.0938 - val_smape: 0.2048

Epoch 26/32

2293/2293 - 63s - 28ms/step - ia: 0.9371 - loss: 0.0180 - mae: 0.0985 - rmse: 0.1294 - smape: 0.2528 - val_ia: 0.7302 - val_loss: 0.0102 - val_mae: 0.0728 - val_rmse: 0.0897 - val_smape: 0.1985

Epoch 27/32

2293/2293 - 62s - 27ms/step - ia: 0.9379 - loss: 0.0175 - mae: 0.0971 - rmse: 0.1274 - smape: 0.2489 - val_ia: 0.7414 - val_loss: 0.0093 - val_mae: 0.0686 - val_rmse: 0.0851 - val_smape: 0.1895

Epoch 28/32

2293/2293 - 62s - 27ms/step - ia: 0.9386 - loss: 0.0171 - mae: 0.0962 - rmse: 0.1258 - smape: 0.2469 - val_ia: 0.7345 - val_loss: 0.0097 - val_mae: 0.0709 - val_rmse: 0.0874 - val_smape: 0.1898

Epoch 29/32

2293/2293 - 64s - 28ms/step - ia: 0.9397 - loss: 0.0166 - mae: 0.0945 - rmse: 0.1239 - smape: 0.2436 - val_ia: 0.7529 - val_loss: 0.0085 - val_mae: 0.0648 - val_rmse: 0.0808 - val_smape: 0.1785

Epoch 30/32

2293/2293 - 63s - 27ms/step - ia: 0.9401 - loss: 0.0162 - mae: 0.0937 - rmse: 0.1227 - smape: 0.2418 - val_ia: 0.7357 - val_loss: 0.0095 - val_mae: 0.0706 - val_rmse: 0.0862 - val_smape: 0.1960

Epoch 31/32

2293/2293 - 64s - 28ms/step - ia: 0.9408 - loss: 0.0160 - mae: 0.0928 - rmse: 0.1217 - smape: 0.2398 - val_ia: 0.7633 - val_loss: 0.0078 - val_mae: 0.0619 - val_rmse: 0.0773 - val_smape: 0.1733

Epoch 32/32

2293/2293 - 67s - 29ms/step - ia: 0.9415 - loss: 0.0155 - mae: 0.0915 - rmse: 0.1198 - smape: 0.2380 - val_ia: 0.7579 - val_loss: 0.0080 - val_mae: 0.0637 - val_rmse: 0.0790 - val_smape: 0.1809

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:57 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step

 62%|██████▏   | 31/50 [9:55:08<9:09:45, 1736.09s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 29s - 203ms/step - ia: 0.7021 - loss: 0.2756 - mae: 0.3726 - rmse: 0.4701 - smape: 0.8014 - val_ia: 0.8583 - val_loss: 0.0632 - val_mae: 0.1910 - val_rmse: 0.2492 - val_smape: 0.5077

Epoch 2/128

144/144 - 14s - 97ms/step - ia: 0.9187 - loss: 0.0345 - mae: 0.1327 - rmse: 0.1841 - smape: 0.3645 - val_ia: 0.9147 - val_loss: 0.0251 - val_mae: 0.1174 - val_rmse: 0.1577 - val_smape: 0.3212

Epoch 3/128

144/144 - 15s - 102ms/step - ia: 0.9431 - loss: 0.0173 - mae: 0.0934 - rmse: 0.1302 - smape: 0.2762 - val_ia: 0.9304 - val_loss: 0.0154 - val_mae: 0.0905 - val_rmse: 0.1225 - val_smape: 0.2501

Epoch 4/128

144/144 - 22s - 151ms/step - ia: 0.9546 - loss: 0.0109 - mae: 0.0748 - rmse: 0.1029 - smape: 0.2292 - val_ia: 0.9118 - val_loss: 0.0227 - val_mae: 0.1148 - val_rmse: 0.1489 - val_smape: 0.3232

Epoch 5/128

144/144 - 15s - 103ms/step - ia: 0.9607 - loss: 0.0083 - mae: 0.0649 - rmse: 0.0893 - smape: 0.2034 - val_ia: 0.9414 - val_loss: 0.0104 - val_mae: 0.0793 - val_rmse: 0.1000 - val_smape: 0.2357

Epoch 6/128

144/144 - 15s - 103ms/step - ia: 0.9654 - loss: 0.0067 - mae: 0.0571 - rmse: 0.0795 - smape: 0.1837 - val_ia: 0.8847 - val_loss: 0.0310 - val_mae: 0.1611 - val_rmse: 0.1739 - val_smape: 0.4082

Epoch 7/128

144/144 - 15s - 103ms/step - ia: 0.9659 - loss: 0.0064 - mae: 0.0562 - rmse: 0.0781 - smape: 0.1816 - val_ia: 0.9425 - val_loss: 0.0100 - val_mae: 0.0787 - val_rmse: 0.0994 - val_smape: 0.2065

Epoch 8/128

144/144 - 14s - 95ms/step - ia: 0.9692 - loss: 0.0054 - mae: 0.0508 - rmse: 0.0717 - smape: 0.1668 - val_ia: 0.9574 - val_loss: 0.0064 - val_mae: 0.0577 - val_rmse: 0.0796 - val_smape: 0.1552

Epoch 9/128

144/144 - 15s - 102ms/step - ia: 0.9697 - loss: 0.0052 - mae: 0.0502 - rmse: 0.0703 - smape: 0.1662 - val_ia: 0.9374 - val_loss: 0.0100 - val_mae: 0.0863 - val_rmse: 0.0991 - val_smape: 0.2763

Epoch 10/128

144/144 - 15s - 104ms/step - ia: 0.9717 - loss: 0.0046 - mae: 0.0468 - rmse: 0.0665 - smape: 0.1588 - val_ia: 0.9670 - val_loss: 0.0039 - val_mae: 0.0450 - val_rmse: 0.0621 - val_smape: 0.1289

Epoch 11/128

144/144 - 15s - 105ms/step - ia: 0.9697 - loss: 0.0051 - mae: 0.0501 - rmse: 0.0690 - smape: 0.1664 - val_ia: 0.9686 - val_loss: 0.0036 - val_mae: 0.0430 - val_rmse: 0.0592 - val_smape: 0.1317

Epoch 12/128

144/144 - 14s - 98ms/step - ia: 0.9732 - loss: 0.0043 - mae: 0.0443 - rmse: 0.0631 - smape: 0.1533 - val_ia: 0.9659 - val_loss: 0.0043 - val_mae: 0.0462 - val_rmse: 0.0647 - val_smape: 0.1292

Epoch 13/128

144/144 - 12s - 83ms/step - ia: 0.9729 - loss: 0.0043 - mae: 0.0448 - rmse: 0.0630 - smape: 0.1540 - val_ia: 0.9694 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0577 - val_smape: 0.1323

Epoch 14/128

144/144 - 12s - 83ms/step - ia: 0.9725 - loss: 0.0043 - mae: 0.0455 - rmse: 0.0637 - smape: 0.1559 - val_ia: 0.9614 - val_loss: 0.0047 - val_mae: 0.0511 - val_rmse: 0.0683 - val_smape: 0.1380

Epoch 15/128

144/144 - 23s - 159ms/step - ia: 0.9746 - loss: 0.0038 - mae: 0.0420 - rmse: 0.0599 - smape: 0.1485 - val_ia: 0.9696 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0563 - val_smape: 0.1398

Epoch 16/128

144/144 - 14s - 99ms/step - ia: 0.9741 - loss: 0.0039 - mae: 0.0427 - rmse: 0.0605 - smape: 0.1485 - val_ia: 0.9583 - val_loss: 0.0052 - val_mae: 0.0561 - val_rmse: 0.0707 - val_smape: 0.1926

Epoch 17/128

144/144 - 15s - 101ms/step - ia: 0.9742 - loss: 0.0039 - mae: 0.0428 - rmse: 0.0605 - smape: 0.1491 - val_ia: 0.9699 - val_loss: 0.0032 - val_mae: 0.0407 - val_rmse: 0.0554 - val_smape: 0.1336

Epoch 18/128

144/144 - 21s - 146ms/step - ia: 0.9758 - loss: 0.0036 - mae: 0.0401 - rmse: 0.0576 - smape: 0.1418 - val_ia: 0.9698 - val_loss: 0.0033 - val_mae: 0.0402 - val_rmse: 0.0566 - val_smape: 0.1189

Epoch 19/128

144/144 - 12s - 87ms/step - ia: 0.9752 - loss: 0.0036 - mae: 0.0410 - rmse: 0.0583 - smape: 0.1447 - val_ia: 0.9700 - val_loss: 0.0032 - val_mae: 0.0408 - val_rmse: 0.0552 - val_smape: 0.1382

Epoch 20/128

144/144 - 12s - 82ms/step - ia: 0.9757 - loss: 0.0035 - mae: 0.0402 - rmse: 0.0575 - smape: 0.1433 - val_ia: 0.9564 - val_loss: 0.0055 - val_mae: 0.0580 - val_rmse: 0.0717 - val_smape: 0.1982

Epoch 21/128

144/144 - 10s - 70ms/step - ia: 0.9759 - loss: 0.0035 - mae: 0.0399 - rmse: 0.0573 - smape: 0.1411 - val_ia: 0.9718 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0532 - val_smape: 0.1200

Epoch 22/128

144/144 - 10s - 66ms/step - ia: 0.9748 - loss: 0.0037 - mae: 0.0417 - rmse: 0.0590 - smape: 0.1469 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0417 - val_rmse: 0.0568 - val_smape: 0.1252

Epoch 23/128

144/144 - 10s - 69ms/step - ia: 0.9771 - loss: 0.0033 - mae: 0.0380 - rmse: 0.0551 - smape: 0.1360 - val_ia: 0.9626 - val_loss: 0.0043 - val_mae: 0.0507 - val_rmse: 0.0636 - val_smape: 0.1623

Epoch 24/128

144/144 - 10s - 70ms/step - ia: 0.9769 - loss: 0.0033 - mae: 0.0382 - rmse: 0.0554 - smape: 0.1362 - val_ia: 0.9418 - val_loss: 0.0086 - val_mae: 0.0788 - val_rmse: 0.0915 - val_smape: 0.2604

Epoch 25/128

144/144 - 10s - 67ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0376 - rmse: 0.0546 - smape: 0.1350 - val_ia: 0.9522 - val_loss: 0.0063 - val_mae: 0.0642 - val_rmse: 0.0784 - val_smape: 0.2077

Epoch 26/128

144/144 - 10s - 73ms/step - ia: 0.9768 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0552 - smape: 0.1367 - val_ia: 0.9464 - val_loss: 0.0074 - val_mae: 0.0724 - val_rmse: 0.0852 - val_smape: 0.2313

Epoch 27/128

144/144 - 11s - 73ms/step - ia: 0.9770 - loss: 0.0032 - mae: 0.0380 - rmse: 0.0552 - smape: 0.1366 - val_ia: 0.9597 - val_loss: 0.0047 - val_mae: 0.0544 - val_rmse: 0.0673 - val_smape: 0.1818

Epoch 28/128

144/144 - 10s - 70ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0376 - rmse: 0.0548 - smape: 0.1354 - val_ia: 0.9649 - val_loss: 0.0039 - val_mae: 0.0483 - val_rmse: 0.0622 - val_smape: 0.1388

Epoch 29/128

144/144 - 10s - 72ms/step - ia: 0.9768 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0552 - smape: 0.1378 - val_ia: 0.9694 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0560 - val_smape: 0.1238

Epoch 30/128

144/144 - 10s - 72ms/step - ia: 0.9769 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0550 - smape: 0.1374 - val_ia: 0.9715 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0532 - val_smape: 0.1205

Epoch 31/128

144/144 - 10s - 71ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0376 - rmse: 0.0546 - smape: 0.1340 - val_ia: 0.9685 - val_loss: 0.0033 - val_mae: 0.0425 - val_rmse: 0.0562 - val_smape: 0.1418

Epoch 32/128

144/144 - 11s - 73ms/step - ia: 0.9778 - loss: 0.0031 - mae: 0.0366 - rmse: 0.0539 - smape: 0.1307 - val_ia: 0.9684 - val_loss: 0.0033 - val_mae: 0.0425 - val_rmse: 0.0561 - val_smape: 0.1436

Epoch 33/128

144/144 - 20s - 140ms/step - ia: 0.9776 - loss: 0.0031 - mae: 0.0370 - rmse: 0.0539 - smape: 0.1336 - val_ia: 0.9701 - val_loss: 0.0031 - val_mae: 0.0406 - val_rmse: 0.0548 - val_smape: 0.1304

Epoch 34/128

144/144 - 10s - 70ms/step - ia: 0.9786 - loss: 0.0030 - mae: 0.0354 - rmse: 0.0526 - smape: 0.1287 - val_ia: 0.9728 - val_loss: 0.0027 - val_mae: 0.0373 - val_rmse: 0.0515 - val_smape: 0.1191

Epoch 35/128

144/144 - 12s - 80ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0530 - smape: 0.1296 - val_ia: 0.9715 - val_loss: 0.0029 - val_mae: 0.0385 - val_rmse: 0.0525 - val_smape: 0.1266

Epoch 36/128

144/144 - 11s - 79ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0530 - smape: 0.1302 - val_ia: 0.9608 - val_loss: 0.0045 - val_mae: 0.0533 - val_rmse: 0.0666 - val_smape: 0.1588

Epoch 37/128

144/144 - 10s - 72ms/step - ia: 0.9778 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0536 - smape: 0.1331 - val_ia: 0.9717 - val_loss: 0.0028 - val_mae: 0.0383 - val_rmse: 0.0520 - val_smape: 0.1266

Epoch 38/128

144/144 - 11s - 73ms/step - ia: 0.9779 - loss: 0.0031 - mae: 0.0366 - rmse: 0.0536 - smape: 0.1313 - val_ia: 0.9714 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0526 - val_smape: 0.1355

Epoch 39/128

144/144 - 10s - 72ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0531 - smape: 0.1309 - val_ia: 0.9595 - val_loss: 0.0047 - val_mae: 0.0544 - val_rmse: 0.0671 - val_smape: 0.1847

Epoch 40/128

144/144 - 10s - 72ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0359 - rmse: 0.0529 - smape: 0.1296 - val_ia: 0.9686 - val_loss: 0.0033 - val_mae: 0.0423 - val_rmse: 0.0562 - val_smape: 0.1335

Epoch 41/128

144/144 - 10s - 69ms/step - ia: 0.9773 - loss: 0.0031 - mae: 0.0375 - rmse: 0.0540 - smape: 0.1354 - val_ia: 0.9699 - val_loss: 0.0031 - val_mae: 0.0404 - val_rmse: 0.0542 - val_smape: 0.1398

Epoch 42/128

144/144 - 10s - 73ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0523 - smape: 0.1274 - val_ia: 0.9717 - val_loss: 0.0028 - val_mae: 0.0381 - val_rmse: 0.0519 - val_smape: 0.1265

Epoch 43/128

144/144 - 10s - 73ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0376 - rmse: 0.0543 - smape: 0.1347 - val_ia: 0.9696 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0550 - val_smape: 0.1208

Epoch 44/128

144/144 - 10s - 72ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0521 - smape: 0.1277 - val_ia: 0.9729 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0510 - val_smape: 0.1162

Epoch 45/128

144/144 - 11s - 73ms/step - ia: 0.9789 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0517 - smape: 0.1269 - val_ia: 0.9743 - val_loss: 0.0025 - val_mae: 0.0350 - val_rmse: 0.0489 - val_smape: 0.1161

Epoch 46/128

144/144 - 11s - 77ms/step - ia: 0.9791 - loss: 0.0028 - mae: 0.0345 - rmse: 0.0510 - smape: 0.1257 - val_ia: 0.9702 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0539 - val_smape: 0.1334

Epoch 47/128

144/144 - 10s - 70ms/step - ia: 0.9776 - loss: 0.0031 - mae: 0.0370 - rmse: 0.0538 - smape: 0.1319 - val_ia: 0.9653 - val_loss: 0.0037 - val_mae: 0.0469 - val_rmse: 0.0597 - val_smape: 0.1587

Epoch 48/128

144/144 - 10s - 69ms/step - ia: 0.9778 - loss: 0.0031 - mae: 0.0367 - rmse: 0.0533 - smape: 0.1336 - val_ia: 0.9738 - val_loss: 0.0025 - val_mae: 0.0354 - val_rmse: 0.0496 - val_smape: 0.1166

Epoch 49/128

144/144 - 10s - 71ms/step - ia: 0.9789 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0516 - smape: 0.1269 - val_ia: 0.9734 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0502 - val_smape: 0.1163

Epoch 50/128

144/144 - 10s - 71ms/step - ia: 0.9779 - loss: 0.0030 - mae: 0.0365 - rmse: 0.0533 - smape: 0.1310 - val_ia: 0.9731 - val_loss: 0.0027 - val_mae: 0.0364 - val_rmse: 0.0509 - val_smape: 0.1157

Epoch 51/128

144/144 - 10s - 72ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0520 - smape: 0.1277 - val_ia: 0.9739 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0496 - val_smape: 0.1185

Epoch 52/128

144/144 - 10s - 68ms/step - ia: 0.9796 - loss: 0.0027 - mae: 0.0337 - rmse: 0.0502 - smape: 0.1232 - val_ia: 0.9708 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0527 - val_smape: 0.1305

Epoch 53/128

144/144 - 11s - 77ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0519 - smape: 0.1275 - val_ia: 0.9736 - val_loss: 0.0026 - val_mae: 0.0358 - val_rmse: 0.0500 - val_smape: 0.1196

Epoch 54/128

144/144 - 10s - 73ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0517 - smape: 0.1284 - val_ia: 0.9676 - val_loss: 0.0033 - val_mae: 0.0433 - val_rmse: 0.0564 - val_smape: 0.1400

Epoch 55/128

144/144 - 10s - 70ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0518 - smape: 0.1293 - val_ia: 0.9732 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0504 - val_smape: 0.1184

Epoch 56/128

144/144 - 10s - 71ms/step - ia: 0.9791 - loss: 0.0028 - mae: 0.0347 - rmse: 0.0514 - smape: 0.1262 - val_ia: 0.9714 - val_loss: 0.0029 - val_mae: 0.0386 - val_rmse: 0.0533 - val_smape: 0.1225

Epoch 57/128

144/144 - 10s - 72ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0517 - smape: 0.1280 - val_ia: 0.9580 - val_loss: 0.0049 - val_mae: 0.0568 - val_rmse: 0.0689 - val_smape: 0.1783

Epoch 58/128

144/144 - 10s - 72ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0355 - rmse: 0.0521 - smape: 0.1287 - val_ia: 0.9706 - val_loss: 0.0029 - val_mae: 0.0395 - val_rmse: 0.0526 - val_smape: 0.1288

Epoch 59/128

144/144 - 10s - 70ms/step - ia: 0.9792 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0509 - smape: 0.1257 - val_ia: 0.9726 - val_loss: 0.0028 - val_mae: 0.0371 - val_rmse: 0.0518 - val_smape: 0.1195

Epoch 60/128

144/144 - 10s - 72ms/step - ia: 0.9792 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0508 - smape: 0.1248 - val_ia: 0.9748 - val_loss: 0.0024 - val_mae: 0.0338 - val_rmse: 0.0483 - val_smape: 0.1074

Epoch 61/128

144/144 - 10s - 73ms/step - ia: 0.9791 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0510 - smape: 0.1266 - val_ia: 0.9727 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0512 - val_smape: 0.1178

Epoch 62/128

144/144 - 10s - 72ms/step - ia: 0.9792 - loss: 0.0028 - mae: 0.0344 - rmse: 0.0508 - smape: 0.1254 - val_ia: 0.9721 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0517 - val_smape: 0.1183

Epoch 63/128

144/144 - 10s - 71ms/step - ia: 0.9789 - loss: 0.0028 - mae: 0.0349 - rmse: 0.0513 - smape: 0.1268 - val_ia: 0.9624 - val_loss: 0.0043 - val_mae: 0.0516 - val_rmse: 0.0642 - val_smape: 0.1566

Epoch 64/128

144/144 - 11s - 73ms/step - ia: 0.9792 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0510 - smape: 0.1249 - val_ia: 0.9731 - val_loss: 0.0026 - val_mae: 0.0363 - val_rmse: 0.0502 - val_smape: 0.1146

Epoch 65/128

144/144 - 11s - 75ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0361 - rmse: 0.0524 - smape: 0.1306 - val_ia: 0.9620 - val_loss: 0.0042 - val_mae: 0.0498 - val_rmse: 0.0634 - val_smape: 0.1646

Epoch 66/128

144/144 - 10s - 69ms/step - ia: 0.9788 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0517 - smape: 0.1270 - val_ia: 0.9742 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0489 - val_smape: 0.1119

Epoch 67/128

144/144 - 11s - 73ms/step - ia: 0.9793 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0507 - smape: 0.1254 - val_ia: 0.9740 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0489 - val_smape: 0.1116

Epoch 68/128

144/144 - 12s - 84ms/step - ia: 0.9793 - loss: 0.0028 - mae: 0.0343 - rmse: 0.0508 - smape: 0.1250 - val_ia: 0.9725 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0507 - val_smape: 0.1198

Epoch 69/128

144/144 - 11s - 75ms/step - ia: 0.9799 - loss: 0.0027 - mae: 0.0332 - rmse: 0.0496 - smape: 0.1233 - val_ia: 0.9743 - val_loss: 0.0025 - val_mae: 0.0344 - val_rmse: 0.0487 - val_smape: 0.1113

Epoch 70/128

144/144 - 10s - 70ms/step - ia: 0.9799 - loss: 0.0027 - mae: 0.0332 - rmse: 0.0495 - smape: 0.1231 - val_ia: 0.9701 - val_loss: 0.0030 - val_mae: 0.0410 - val_rmse: 0.0544 - val_smape: 0.1301

Epoch 71/128

144/144 - 10s - 73ms/step - ia: 0.9802 - loss: 0.0026 - mae: 0.0328 - rmse: 0.0495 - smape: 0.1223 - val_ia: 0.9743 - val_loss: 0.0024 - val_mae: 0.0346 - val_rmse: 0.0486 - val_smape: 0.1091

Epoch 72/128

144/144 - 11s - 73ms/step - ia: 0.9796 - loss: 0.0027 - mae: 0.0337 - rmse: 0.0501 - smape: 0.1233 - val_ia: 0.9736 - val_loss: 0.0025 - val_mae: 0.0358 - val_rmse: 0.0497 - val_smape: 0.1131

Epoch 73/128

144/144 - 10s - 71ms/step - ia: 0.9795 - loss: 0.0027 - mae: 0.0338 - rmse: 0.0502 - smape: 0.1243 - val_ia: 0.9740 - val_loss: 0.0024 - val_mae: 0.0353 - val_rmse: 0.0486 - val_smape: 0.1107

Epoch 74/128

144/144 - 10s - 72ms/step - ia: 0.9795 - loss: 0.0027 - mae: 0.0339 - rmse: 0.0504 - smape: 0.1249 - val_ia: 0.9675 - val_loss: 0.0035 - val_mae: 0.0446 - val_rmse: 0.0581 - val_smape: 0.1376

Epoch 75/128

144/144 - 10s - 73ms/step - ia: 0.9798 - loss: 0.0027 - mae: 0.0335 - rmse: 0.0496 - smape: 0.1236 - val_ia: 0.9733 - val_loss: 0.0026 - val_mae: 0.0359 - val_rmse: 0.0500 - val_smape: 0.1121

Epoch 75: early stopping

Restoring model weights from the end of the best epoch: 60.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:29 555ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

Epoch 1/128

 64%|██████▍   | 32/50 [10:10:11<7:25:49, 1486.11s/trial, best loss: 0.0018270429778278127]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 17s - 120ms/step - ia: 0.7927 - loss: 0.2178 - mae: 0.2788 - rmse: 0.3667 - smape: 0.5791 - val_ia: 0.9189 - val_loss: 0.0167 - val_mae: 0.1000 - val_rmse: 0.1292 - val_smape: 0.2412

Epoch 2/128

144/144 - 10s - 72ms/step - ia: 0.9625 - loss: 0.0077 - mae: 0.0621 - rmse: 0.0843 - smape: 0.1931 - val_ia: 0.9642 - val_loss: 0.0039 - val_mae: 0.0462 - val_rmse: 0.0614 - val_smape: 0.1379

Epoch 3/128

144/144 - 10s - 72ms/step - ia: 0.9729 - loss: 0.0041 - mae: 0.0448 - rmse: 0.0625 - smape: 0.1518 - val_ia: 0.9693 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0559 - val_smape: 0.1170

Epoch 4/128

144/144 - 10s - 70ms/step - ia: 0.9753 - loss: 0.0036 - mae: 0.0409 - rmse: 0.0581 - smape: 0.1439 - val_ia: 0.9725 - val_loss: 0.0027 - val_mae: 0.0362 - val_rmse: 0.0510 - val_smape: 0.1171

Epoch 5/128

144/144 - 10s - 70ms/step - ia: 0.9761 - loss: 0.0034 - mae: 0.0394 - rmse: 0.0564 - smape: 0.1375 - val_ia: 0.9668 - val_loss: 0.0034 - val_mae: 0.0434 - val_rmse: 0.0581 - val_smape: 0.1415

Epoch 6/128

144/144 - 10s - 72ms/step - ia: 0.9759 - loss: 0.0034 - mae: 0.0398 - rmse: 0.0566 - smape: 0.1392 - val_ia: 0.9700 - val_loss: 0.0030 - val_mae: 0.0409 - val_rmse: 0.0543 - val_smape: 0.1233

Epoch 7/128

144/144 - 10s - 72ms/step - ia: 0.9774 - loss: 0.0031 - mae: 0.0372 - rmse: 0.0543 - smape: 0.1332 - val_ia: 0.9437 - val_loss: 0.0077 - val_mae: 0.0754 - val_rmse: 0.0872 - val_smape: 0.2423

Epoch 8/128

144/144 - 10s - 70ms/step - ia: 0.9759 - loss: 0.0034 - mae: 0.0397 - rmse: 0.0564 - smape: 0.1389 - val_ia: 0.9741 - val_loss: 0.0025 - val_mae: 0.0353 - val_rmse: 0.0491 - val_smape: 0.1114

Epoch 9/128

144/144 - 10s - 71ms/step - ia: 0.9774 - loss: 0.0031 - mae: 0.0373 - rmse: 0.0538 - smape: 0.1330 - val_ia: 0.9743 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0489 - val_smape: 0.1069

Epoch 10/128

144/144 - 10s - 72ms/step - ia: 0.9777 - loss: 0.0030 - mae: 0.0369 - rmse: 0.0534 - smape: 0.1311 - val_ia: 0.9742 - val_loss: 0.0025 - val_mae: 0.0348 - val_rmse: 0.0488 - val_smape: 0.1110

Epoch 11/128

144/144 - 10s - 71ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0523 - smape: 0.1278 - val_ia: 0.9715 - val_loss: 0.0028 - val_mae: 0.0387 - val_rmse: 0.0527 - val_smape: 0.1249

Epoch 12/128

144/144 - 10s - 70ms/step - ia: 0.9773 - loss: 0.0031 - mae: 0.0376 - rmse: 0.0542 - smape: 0.1334 - val_ia: 0.9742 - val_loss: 0.0024 - val_mae: 0.0350 - val_rmse: 0.0484 - val_smape: 0.1106

Epoch 13/128

144/144 - 10s - 70ms/step - ia: 0.9777 - loss: 0.0030 - mae: 0.0368 - rmse: 0.0532 - smape: 0.1311 - val_ia: 0.9751 - val_loss: 0.0023 - val_mae: 0.0339 - val_rmse: 0.0475 - val_smape: 0.1079

Epoch 14/128

144/144 - 10s - 71ms/step - ia: 0.9777 - loss: 0.0030 - mae: 0.0369 - rmse: 0.0534 - smape: 0.1317 - val_ia: 0.9743 - val_loss: 0.0025 - val_mae: 0.0344 - val_rmse: 0.0490 - val_smape: 0.1077

Epoch 15/128

144/144 - 10s - 69ms/step - ia: 0.9784 - loss: 0.0029 - mae: 0.0358 - rmse: 0.0521 - smape: 0.1270 - val_ia: 0.9622 - val_loss: 0.0043 - val_mae: 0.0505 - val_rmse: 0.0639 - val_smape: 0.1459

Epoch 16/128

144/144 - 10s - 71ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0517 - smape: 0.1273 - val_ia: 0.9694 - val_loss: 0.0030 - val_mae: 0.0409 - val_rmse: 0.0544 - val_smape: 0.1379

Epoch 17/128

144/144 - 10s - 71ms/step - ia: 0.9788 - loss: 0.0028 - mae: 0.0351 - rmse: 0.0515 - smape: 0.1271 - val_ia: 0.9649 - val_loss: 0.0038 - val_mae: 0.0476 - val_rmse: 0.0605 - val_smape: 0.1476

Epoch 18/128

144/144 - 10s - 72ms/step - ia: 0.9784 - loss: 0.0029 - mae: 0.0357 - rmse: 0.0519 - smape: 0.1282 - val_ia: 0.9671 - val_loss: 0.0035 - val_mae: 0.0441 - val_rmse: 0.0577 - val_smape: 0.1315

Epoch 19/128

144/144 - 10s - 69ms/step - ia: 0.9781 - loss: 0.0030 - mae: 0.0362 - rmse: 0.0527 - smape: 0.1286 - val_ia: 0.9622 - val_loss: 0.0042 - val_mae: 0.0513 - val_rmse: 0.0634 - val_smape: 0.1651

Epoch 20/128

144/144 - 11s - 74ms/step - ia: 0.9790 - loss: 0.0028 - mae: 0.0347 - rmse: 0.0511 - smape: 0.1254 - val_ia: 0.9740 - val_loss: 0.0025 - val_mae: 0.0358 - val_rmse: 0.0494 - val_smape: 0.1088

Epoch 21/128

144/144 - 11s - 78ms/step - ia: 0.9779 - loss: 0.0030 - mae: 0.0366 - rmse: 0.0530 - smape: 0.1289 - val_ia: 0.9736 - val_loss: 0.0026 - val_mae: 0.0362 - val_rmse: 0.0499 - val_smape: 0.1092

Epoch 22/128

144/144 - 10s - 71ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0522 - smape: 0.1278 - val_ia: 0.9640 - val_loss: 0.0040 - val_mae: 0.0485 - val_rmse: 0.0619 - val_smape: 0.1464

Epoch 23/128

144/144 - 9s - 64ms/step - ia: 0.9783 - loss: 0.0029 - mae: 0.0360 - rmse: 0.0521 - smape: 0.1272 - val_ia: 0.9727 - val_loss: 0.0026 - val_mae: 0.0366 - val_rmse: 0.0502 - val_smape: 0.1114

Epoch 24/128

144/144 - 10s - 67ms/step - ia: 0.9791 - loss: 0.0028 - mae: 0.0345 - rmse: 0.0507 - smape: 0.1254 - val_ia: 0.9710 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0532 - val_smape: 0.1157

Epoch 25/128

144/144 - 10s - 71ms/step - ia: 0.9794 - loss: 0.0027 - mae: 0.0339 - rmse: 0.0500 - smape: 0.1239 - val_ia: 0.9735 - val_loss: 0.0025 - val_mae: 0.0356 - val_rmse: 0.0496 - val_smape: 0.1145

Epoch 26/128

144/144 - 10s - 69ms/step - ia: 0.9786 - loss: 0.0028 - mae: 0.0353 - rmse: 0.0514 - smape: 0.1240 - val_ia: 0.9722 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0524 - val_smape: 0.1077

Epoch 27/128

144/144 - 10s - 70ms/step - ia: 0.9789 - loss: 0.0028 - mae: 0.0348 - rmse: 0.0509 - smape: 0.1251 - val_ia: 0.9685 - val_loss: 0.0033 - val_mae: 0.0422 - val_rmse: 0.0565 - val_smape: 0.1199

Epoch 28/128

144/144 - 10s - 72ms/step - ia: 0.9783 - loss: 0.0029 - mae: 0.0359 - rmse: 0.0520 - smape: 0.1268 - val_ia: 0.9745 - val_loss: 0.0025 - val_mae: 0.0346 - val_rmse: 0.0496 - val_smape: 0.1116

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:27 539ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

Epoch 1/32

 66%|██████▌   | 33/50 [10:15:07<5:19:51, 1128.89s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 11s - 76ms/step - ia: 0.7555 - loss: 0.2397 - mae: 0.3162 - rmse: 0.4022 - smape: 0.6562 - val_ia: 0.8814 - val_loss: 0.0344 - val_mae: 0.1550 - val_rmse: 0.1850 - val_smape: 0.4169

Epoch 2/32

144/144 - 3s - 18ms/step - ia: 0.9592 - loss: 0.0089 - mae: 0.0675 - rmse: 0.0919 - smape: 0.2092 - val_ia: 0.9591 - val_loss: 0.0057 - val_mae: 0.0549 - val_rmse: 0.0743 - val_smape: 0.1702

Epoch 3/32

144/144 - 3s - 18ms/step - ia: 0.9695 - loss: 0.0052 - mae: 0.0503 - rmse: 0.0705 - smape: 0.1661 - val_ia: 0.9549 - val_loss: 0.0061 - val_mae: 0.0611 - val_rmse: 0.0767 - val_smape: 0.1900

Epoch 4/32

144/144 - 3s - 18ms/step - ia: 0.9709 - loss: 0.0047 - mae: 0.0480 - rmse: 0.0668 - smape: 0.1607 - val_ia: 0.9608 - val_loss: 0.0047 - val_mae: 0.0526 - val_rmse: 0.0678 - val_smape: 0.1644

Epoch 5/32

144/144 - 3s - 19ms/step - ia: 0.9731 - loss: 0.0041 - mae: 0.0444 - rmse: 0.0627 - smape: 0.1530 - val_ia: 0.9512 - val_loss: 0.0067 - val_mae: 0.0668 - val_rmse: 0.0809 - val_smape: 0.2006

Epoch 6/32

144/144 - 3s - 19ms/step - ia: 0.9735 - loss: 0.0040 - mae: 0.0436 - rmse: 0.0618 - smape: 0.1496 - val_ia: 0.9330 - val_loss: 0.0114 - val_mae: 0.0925 - val_rmse: 0.1062 - val_smape: 0.2520

Epoch 7/32

144/144 - 3s - 19ms/step - ia: 0.9743 - loss: 0.0038 - mae: 0.0424 - rmse: 0.0601 - smape: 0.1454 - val_ia: 0.9665 - val_loss: 0.0036 - val_mae: 0.0443 - val_rmse: 0.0589 - val_smape: 0.1399

Epoch 8/32

144/144 - 3s - 19ms/step - ia: 0.9748 - loss: 0.0037 - mae: 0.0416 - rmse: 0.0592 - smape: 0.1438 - val_ia: 0.9633 - val_loss: 0.0040 - val_mae: 0.0478 - val_rmse: 0.0637 - val_smape: 0.1526

Epoch 9/32

144/144 - 3s - 18ms/step - ia: 0.9740 - loss: 0.0039 - mae: 0.0429 - rmse: 0.0602 - smape: 0.1480 - val_ia: 0.9687 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0568 - val_smape: 0.1282

Epoch 10/32

144/144 - 3s - 18ms/step - ia: 0.9763 - loss: 0.0034 - mae: 0.0392 - rmse: 0.0568 - smape: 0.1368 - val_ia: 0.9697 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0551 - val_smape: 0.1281

Epoch 11/32

144/144 - 3s - 18ms/step - ia: 0.9763 - loss: 0.0034 - mae: 0.0392 - rmse: 0.0565 - smape: 0.1378 - val_ia: 0.9685 - val_loss: 0.0033 - val_mae: 0.0417 - val_rmse: 0.0564 - val_smape: 0.1272

Epoch 12/32

144/144 - 2s - 16ms/step - ia: 0.9764 - loss: 0.0034 - mae: 0.0391 - rmse: 0.0566 - smape: 0.1364 - val_ia: 0.9678 - val_loss: 0.0034 - val_mae: 0.0427 - val_rmse: 0.0573 - val_smape: 0.1269

Epoch 13/32

144/144 - 3s - 18ms/step - ia: 0.9754 - loss: 0.0036 - mae: 0.0406 - rmse: 0.0579 - smape: 0.1395 - val_ia: 0.9674 - val_loss: 0.0033 - val_mae: 0.0423 - val_rmse: 0.0578 - val_smape: 0.1376

Epoch 14/32

144/144 - 3s - 18ms/step - ia: 0.9769 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0553 - smape: 0.1356 - val_ia: 0.9659 - val_loss: 0.0036 - val_mae: 0.0442 - val_rmse: 0.0598 - val_smape: 0.1436

Epoch 15/32

144/144 - 3s - 18ms/step - ia: 0.9746 - loss: 0.0037 - mae: 0.0420 - rmse: 0.0588 - smape: 0.1438 - val_ia: 0.9675 - val_loss: 0.0034 - val_mae: 0.0428 - val_rmse: 0.0583 - val_smape: 0.1312

Epoch 16/32

144/144 - 2s - 17ms/step - ia: 0.9749 - loss: 0.0036 - mae: 0.0415 - rmse: 0.0585 - smape: 0.1412 - val_ia: 0.9692 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0561 - val_smape: 0.1301

Epoch 17/32

144/144 - 2s - 17ms/step - ia: 0.9774 - loss: 0.0032 - mae: 0.0373 - rmse: 0.0544 - smape: 0.1328 - val_ia: 0.9702 - val_loss: 0.0030 - val_mae: 0.0396 - val_rmse: 0.0546 - val_smape: 0.1257

Epoch 18/32

144/144 - 2s - 17ms/step - ia: 0.9775 - loss: 0.0031 - mae: 0.0371 - rmse: 0.0542 - smape: 0.1315 - val_ia: 0.9700 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0551 - val_smape: 0.1206

Epoch 19/32

144/144 - 2s - 17ms/step - ia: 0.9771 - loss: 0.0032 - mae: 0.0378 - rmse: 0.0549 - smape: 0.1342 - val_ia: 0.9607 - val_loss: 0.0048 - val_mae: 0.0511 - val_rmse: 0.0688 - val_smape: 0.1427

Epoch 20/32

144/144 - 2s - 17ms/step - ia: 0.9766 - loss: 0.0033 - mae: 0.0387 - rmse: 0.0556 - smape: 0.1350 - val_ia: 0.9721 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0514 - val_smape: 0.1139

Epoch 21/32

144/144 - 3s - 17ms/step - ia: 0.9777 - loss: 0.0031 - mae: 0.0369 - rmse: 0.0535 - smape: 0.1311 - val_ia: 0.9700 - val_loss: 0.0030 - val_mae: 0.0390 - val_rmse: 0.0541 - val_smape: 0.1221

Epoch 22/32

144/144 - 2s - 17ms/step - ia: 0.9765 - loss: 0.0033 - mae: 0.0388 - rmse: 0.0557 - smape: 0.1344 - val_ia: 0.9702 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0539 - val_smape: 0.1169

Epoch 23/32

144/144 - 2s - 17ms/step - ia: 0.9785 - loss: 0.0029 - mae: 0.0355 - rmse: 0.0524 - smape: 0.1280 - val_ia: 0.9690 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0560 - val_smape: 0.1269

Epoch 24/32

144/144 - 2s - 16ms/step - ia: 0.9762 - loss: 0.0034 - mae: 0.0394 - rmse: 0.0563 - smape: 0.1370 - val_ia: 0.9596 - val_loss: 0.0051 - val_mae: 0.0548 - val_rmse: 0.0693 - val_smape: 0.1450

Epoch 25/32

144/144 - 2s - 17ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0529 - smape: 0.1286 - val_ia: 0.9738 - val_loss: 0.0026 - val_mae: 0.0351 - val_rmse: 0.0501 - val_smape: 0.1128

Epoch 26/32

144/144 - 3s - 18ms/step - ia: 0.9779 - loss: 0.0030 - mae: 0.0366 - rmse: 0.0532 - smape: 0.1296 - val_ia: 0.9719 - val_loss: 0.0029 - val_mae: 0.0378 - val_rmse: 0.0529 - val_smape: 0.1145

Epoch 27/32

144/144 - 3s - 18ms/step - ia: 0.9784 - loss: 0.0030 - mae: 0.0356 - rmse: 0.0525 - smape: 0.1279 - val_ia: 0.9672 - val_loss: 0.0036 - val_mae: 0.0447 - val_rmse: 0.0593 - val_smape: 0.1292

Epoch 28/32

144/144 - 3s - 18ms/step - ia: 0.9780 - loss: 0.0030 - mae: 0.0364 - rmse: 0.0532 - smape: 0.1289 - val_ia: 0.9735 - val_loss: 0.0026 - val_mae: 0.0353 - val_rmse: 0.0508 - val_smape: 0.1108

Epoch 29/32

144/144 - 2s - 17ms/step - ia: 0.9769 - loss: 0.0032 - mae: 0.0381 - rmse: 0.0547 - smape: 0.1346 - val_ia: 0.9668 - val_loss: 0.0035 - val_mae: 0.0430 - val_rmse: 0.0591 - val_smape: 0.1291

Epoch 30/32

144/144 - 2s - 17ms/step - ia: 0.9778 - loss: 0.0031 - mae: 0.0367 - rmse: 0.0534 - smape: 0.1305 - val_ia: 0.9682 - val_loss: 0.0035 - val_mae: 0.0424 - val_rmse: 0.0585 - val_smape: 0.1311

Epoch 31/32

144/144 - 3s - 18ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0525 - smape: 0.1290 - val_ia: 0.9732 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0506 - val_smape: 0.1111

Epoch 32/32

144/144 - 2s - 17ms/step - ia: 0.9766 - loss: 0.0032 - mae: 0.0387 - rmse: 0.0552 - smape: 0.1370 - val_ia: 0.9681 - val_loss: 0.0034 - val_mae: 0.0422 - val_rmse: 0.0580 - val_smape: 0.1313

Restoring model weights from the end of the best epoch: 25.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:53 701ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 68%|██████▊   | 34/50 [10:16:39<3:38:04, 817.77s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 17s - 117ms/step - ia: 0.8858 - loss: 0.0853 - mae: 0.1627 - rmse: 0.2087 - smape: 0.3776 - val_ia: 0.9502 - val_loss: 0.0069 - val_mae: 0.0644 - val_rmse: 0.0834 - val_smape: 0.1877

Epoch 2/128

144/144 - 10s - 71ms/step - ia: 0.9706 - loss: 0.0047 - mae: 0.0483 - rmse: 0.0672 - smape: 0.1600 - val_ia: 0.9554 - val_loss: 0.0058 - val_mae: 0.0607 - val_rmse: 0.0752 - val_smape: 0.2035

Epoch 3/128

144/144 - 10s - 70ms/step - ia: 0.9738 - loss: 0.0039 - mae: 0.0433 - rmse: 0.0604 - smape: 0.1475 - val_ia: 0.9716 - val_loss: 0.0028 - val_mae: 0.0376 - val_rmse: 0.0522 - val_smape: 0.1155

Epoch 4/128

144/144 - 10s - 68ms/step - ia: 0.9760 - loss: 0.0034 - mae: 0.0396 - rmse: 0.0566 - smape: 0.1378 - val_ia: 0.9706 - val_loss: 0.0028 - val_mae: 0.0386 - val_rmse: 0.0531 - val_smape: 0.1259

Epoch 5/128

144/144 - 10s - 69ms/step - ia: 0.9759 - loss: 0.0034 - mae: 0.0399 - rmse: 0.0567 - smape: 0.1370 - val_ia: 0.9680 - val_loss: 0.0034 - val_mae: 0.0446 - val_rmse: 0.0581 - val_smape: 0.1206

Epoch 6/128

144/144 - 10s - 70ms/step - ia: 0.9761 - loss: 0.0034 - mae: 0.0395 - rmse: 0.0563 - smape: 0.1364 - val_ia: 0.9720 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0523 - val_smape: 0.1270

Epoch 7/128

144/144 - 10s - 71ms/step - ia: 0.9777 - loss: 0.0031 - mae: 0.0369 - rmse: 0.0538 - smape: 0.1298 - val_ia: 0.9687 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0558 - val_smape: 0.1205

Epoch 8/128

144/144 - 10s - 68ms/step - ia: 0.9770 - loss: 0.0032 - mae: 0.0380 - rmse: 0.0549 - smape: 0.1324 - val_ia: 0.9596 - val_loss: 0.0050 - val_mae: 0.0550 - val_rmse: 0.0694 - val_smape: 0.1480

Epoch 9/128

144/144 - 10s - 71ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0527 - smape: 0.1283 - val_ia: 0.9747 - val_loss: 0.0024 - val_mae: 0.0344 - val_rmse: 0.0485 - val_smape: 0.1079

Epoch 10/128

144/144 - 10s - 70ms/step - ia: 0.9779 - loss: 0.0030 - mae: 0.0365 - rmse: 0.0531 - smape: 0.1286 - val_ia: 0.9749 - val_loss: 0.0025 - val_mae: 0.0340 - val_rmse: 0.0489 - val_smape: 0.1079

Epoch 11/128

144/144 - 10s - 68ms/step - ia: 0.9774 - loss: 0.0031 - mae: 0.0373 - rmse: 0.0538 - smape: 0.1300 - val_ia: 0.9756 - val_loss: 0.0023 - val_mae: 0.0331 - val_rmse: 0.0472 - val_smape: 0.1039

Epoch 12/128

144/144 - 10s - 70ms/step - ia: 0.9784 - loss: 0.0029 - mae: 0.0357 - rmse: 0.0522 - smape: 0.1268 - val_ia: 0.9752 - val_loss: 0.0024 - val_mae: 0.0337 - val_rmse: 0.0476 - val_smape: 0.1120

Epoch 13/128

144/144 - 10s - 71ms/step - ia: 0.9776 - loss: 0.0031 - mae: 0.0371 - rmse: 0.0536 - smape: 0.1284 - val_ia: 0.9754 - val_loss: 0.0023 - val_mae: 0.0333 - val_rmse: 0.0475 - val_smape: 0.1066

Epoch 14/128

144/144 - 10s - 70ms/step - ia: 0.9785 - loss: 0.0029 - mae: 0.0355 - rmse: 0.0522 - smape: 0.1266 - val_ia: 0.9742 - val_loss: 0.0025 - val_mae: 0.0351 - val_rmse: 0.0494 - val_smape: 0.1071

Epoch 15/128

144/144 - 10s - 67ms/step - ia: 0.9773 - loss: 0.0031 - mae: 0.0376 - rmse: 0.0540 - smape: 0.1317 - val_ia: 0.9693 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0567 - val_smape: 0.1234

Epoch 16/128

144/144 - 10s - 70ms/step - ia: 0.9782 - loss: 0.0029 - mae: 0.0361 - rmse: 0.0523 - smape: 0.1272 - val_ia: 0.9742 - val_loss: 0.0025 - val_mae: 0.0350 - val_rmse: 0.0493 - val_smape: 0.1141

Epoch 17/128

144/144 - 10s - 70ms/step - ia: 0.9789 - loss: 0.0028 - mae: 0.0349 - rmse: 0.0512 - smape: 0.1240 - val_ia: 0.9733 - val_loss: 0.0026 - val_mae: 0.0360 - val_rmse: 0.0505 - val_smape: 0.1175

Epoch 18/128

144/144 - 10s - 70ms/step - ia: 0.9775 - loss: 0.0031 - mae: 0.0373 - rmse: 0.0534 - smape: 0.1293 - val_ia: 0.9714 - val_loss: 0.0029 - val_mae: 0.0389 - val_rmse: 0.0532 - val_smape: 0.1211

Epoch 19/128

144/144 - 10s - 69ms/step - ia: 0.9792 - loss: 0.0028 - mae: 0.0345 - rmse: 0.0505 - smape: 0.1245 - val_ia: 0.9739 - val_loss: 0.0026 - val_mae: 0.0355 - val_rmse: 0.0501 - val_smape: 0.1123

Epoch 20/128

144/144 - 10s - 71ms/step - ia: 0.9786 - loss: 0.0028 - mae: 0.0354 - rmse: 0.0515 - smape: 0.1250 - val_ia: 0.9727 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0506 - val_smape: 0.1242

Epoch 21/128

144/144 - 10s - 69ms/step - ia: 0.9783 - loss: 0.0029 - mae: 0.0359 - rmse: 0.0519 - smape: 0.1260 - val_ia: 0.9743 - val_loss: 0.0025 - val_mae: 0.0352 - val_rmse: 0.0498 - val_smape: 0.1132

Epoch 22/128

144/144 - 10s - 68ms/step - ia: 0.9788 - loss: 0.0028 - mae: 0.0351 - rmse: 0.0512 - smape: 0.1251 - val_ia: 0.9701 - val_loss: 0.0030 - val_mae: 0.0413 - val_rmse: 0.0543 - val_smape: 0.1165

Epoch 23/128

144/144 - 10s - 69ms/step - ia: 0.9780 - loss: 0.0029 - mae: 0.0364 - rmse: 0.0523 - smape: 0.1261 - val_ia: 0.9698 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0556 - val_smape: 0.1301

Epoch 24/128

144/144 - 10s - 72ms/step - ia: 0.9790 - loss: 0.0028 - mae: 0.0346 - rmse: 0.0507 - smape: 0.1232 - val_ia: 0.9715 - val_loss: 0.0030 - val_mae: 0.0391 - val_rmse: 0.0533 - val_smape: 0.1128

Epoch 25/128

144/144 - 10s - 71ms/step - ia: 0.9779 - loss: 0.0029 - mae: 0.0365 - rmse: 0.0522 - smape: 0.1269 - val_ia: 0.9718 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0520 - val_smape: 0.1223

Epoch 26/128

144/144 - 10s - 68ms/step - ia: 0.9790 - loss: 0.0027 - mae: 0.0347 - rmse: 0.0505 - smape: 0.1241 - val_ia: 0.9725 - val_loss: 0.0027 - val_mae: 0.0363 - val_rmse: 0.0508 - val_smape: 0.1184

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:26 531ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

Epoch 1/64

 70%|███████   | 35/50 [10:21:09<2:43:23, 653.57s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 16s - 114ms/step - ia: 0.8490 - loss: 0.1216 - mae: 0.2175 - rmse: 0.2781 - smape: 0.4772 - val_ia: 0.9309 - val_loss: 0.0157 - val_mae: 0.0926 - val_rmse: 0.1234 - val_smape: 0.2651

Epoch 2/64

144/144 - 7s - 50ms/step - ia: 0.9435 - loss: 0.0159 - mae: 0.0933 - rmse: 0.1253 - smape: 0.2438 - val_ia: 0.9363 - val_loss: 0.0135 - val_mae: 0.0839 - val_rmse: 0.1105 - val_smape: 0.2026

Epoch 3/64

144/144 - 7s - 51ms/step - ia: 0.9508 - loss: 0.0123 - mae: 0.0811 - rmse: 0.1099 - smape: 0.2154 - val_ia: 0.9368 - val_loss: 0.0121 - val_mae: 0.0817 - val_rmse: 0.1089 - val_smape: 0.2050

Epoch 4/64

144/144 - 7s - 52ms/step - ia: 0.9548 - loss: 0.0106 - mae: 0.0746 - rmse: 0.1018 - smape: 0.2016 - val_ia: 0.9496 - val_loss: 0.0081 - val_mae: 0.0666 - val_rmse: 0.0864 - val_smape: 0.1618

Epoch 5/64

144/144 - 7s - 51ms/step - ia: 0.9568 - loss: 0.0098 - mae: 0.0713 - rmse: 0.0980 - smape: 0.1899 - val_ia: 0.9461 - val_loss: 0.0088 - val_mae: 0.0709 - val_rmse: 0.0894 - val_smape: 0.1874

Epoch 6/64

144/144 - 7s - 51ms/step - ia: 0.9580 - loss: 0.0093 - mae: 0.0694 - rmse: 0.0954 - smape: 0.1870 - val_ia: 0.9605 - val_loss: 0.0057 - val_mae: 0.0535 - val_rmse: 0.0741 - val_smape: 0.1469

Epoch 7/64

144/144 - 7s - 48ms/step - ia: 0.9592 - loss: 0.0089 - mae: 0.0674 - rmse: 0.0933 - smape: 0.1809 - val_ia: 0.9567 - val_loss: 0.0064 - val_mae: 0.0578 - val_rmse: 0.0783 - val_smape: 0.1530

Epoch 8/64

144/144 - 7s - 51ms/step - ia: 0.9594 - loss: 0.0088 - mae: 0.0671 - rmse: 0.0927 - smape: 0.1811 - val_ia: 0.9588 - val_loss: 0.0057 - val_mae: 0.0548 - val_rmse: 0.0725 - val_smape: 0.1555

Epoch 9/64

144/144 - 7s - 51ms/step - ia: 0.9611 - loss: 0.0081 - mae: 0.0644 - rmse: 0.0892 - smape: 0.1750 - val_ia: 0.9574 - val_loss: 0.0060 - val_mae: 0.0576 - val_rmse: 0.0746 - val_smape: 0.1511

Epoch 10/64

144/144 - 7s - 51ms/step - ia: 0.9615 - loss: 0.0080 - mae: 0.0635 - rmse: 0.0882 - smape: 0.1740 - val_ia: 0.9647 - val_loss: 0.0043 - val_mae: 0.0471 - val_rmse: 0.0645 - val_smape: 0.1360

Epoch 11/64

144/144 - 7s - 51ms/step - ia: 0.9613 - loss: 0.0080 - mae: 0.0638 - rmse: 0.0884 - smape: 0.1718 - val_ia: 0.9648 - val_loss: 0.0042 - val_mae: 0.0464 - val_rmse: 0.0631 - val_smape: 0.1424

Epoch 12/64

144/144 - 7s - 49ms/step - ia: 0.9625 - loss: 0.0076 - mae: 0.0620 - rmse: 0.0861 - smape: 0.1678 - val_ia: 0.9497 - val_loss: 0.0073 - val_mae: 0.0662 - val_rmse: 0.0835 - val_smape: 0.1666

Epoch 13/64

144/144 - 7s - 50ms/step - ia: 0.9626 - loss: 0.0075 - mae: 0.0618 - rmse: 0.0860 - smape: 0.1664 - val_ia: 0.9653 - val_loss: 0.0041 - val_mae: 0.0453 - val_rmse: 0.0624 - val_smape: 0.1427

Epoch 14/64

144/144 - 7s - 50ms/step - ia: 0.9629 - loss: 0.0074 - mae: 0.0612 - rmse: 0.0850 - smape: 0.1669 - val_ia: 0.9659 - val_loss: 0.0040 - val_mae: 0.0450 - val_rmse: 0.0612 - val_smape: 0.1384

Epoch 15/64

144/144 - 7s - 50ms/step - ia: 0.9634 - loss: 0.0072 - mae: 0.0605 - rmse: 0.0840 - smape: 0.1632 - val_ia: 0.9678 - val_loss: 0.0035 - val_mae: 0.0431 - val_rmse: 0.0587 - val_smape: 0.1252

Epoch 16/64

144/144 - 7s - 51ms/step - ia: 0.9634 - loss: 0.0071 - mae: 0.0603 - rmse: 0.0838 - smape: 0.1626 - val_ia: 0.9645 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0626 - val_smape: 0.1392

Epoch 17/64

144/144 - 7s - 48ms/step - ia: 0.9640 - loss: 0.0069 - mae: 0.0594 - rmse: 0.0823 - smape: 0.1618 - val_ia: 0.9660 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0604 - val_smape: 0.1430

Epoch 18/64

144/144 - 7s - 52ms/step - ia: 0.9640 - loss: 0.0069 - mae: 0.0593 - rmse: 0.0824 - smape: 0.1614 - val_ia: 0.9611 - val_loss: 0.0046 - val_mae: 0.0517 - val_rmse: 0.0663 - val_smape: 0.1519

Epoch 19/64

144/144 - 8s - 55ms/step - ia: 0.9648 - loss: 0.0067 - mae: 0.0580 - rmse: 0.0809 - smape: 0.1582 - val_ia: 0.9612 - val_loss: 0.0047 - val_mae: 0.0514 - val_rmse: 0.0680 - val_smape: 0.1466

Epoch 20/64

144/144 - 8s - 57ms/step - ia: 0.9638 - loss: 0.0070 - mae: 0.0597 - rmse: 0.0827 - smape: 0.1605 - val_ia: 0.9624 - val_loss: 0.0044 - val_mae: 0.0492 - val_rmse: 0.0639 - val_smape: 0.1421

Epoch 21/64

144/144 - 7s - 52ms/step - ia: 0.9646 - loss: 0.0068 - mae: 0.0585 - rmse: 0.0817 - smape: 0.1582 - val_ia: 0.9556 - val_loss: 0.0060 - val_mae: 0.0567 - val_rmse: 0.0764 - val_smape: 0.1600

Epoch 22/64

144/144 - 7s - 49ms/step - ia: 0.9649 - loss: 0.0067 - mae: 0.0581 - rmse: 0.0806 - smape: 0.1570 - val_ia: 0.9597 - val_loss: 0.0048 - val_mae: 0.0521 - val_rmse: 0.0670 - val_smape: 0.1493

Epoch 23/64

144/144 - 7s - 51ms/step - ia: 0.9656 - loss: 0.0064 - mae: 0.0569 - rmse: 0.0792 - smape: 0.1539 - val_ia: 0.9629 - val_loss: 0.0043 - val_mae: 0.0488 - val_rmse: 0.0638 - val_smape: 0.1556

Epoch 24/64

144/144 - 7s - 51ms/step - ia: 0.9656 - loss: 0.0065 - mae: 0.0568 - rmse: 0.0793 - smape: 0.1556 - val_ia: 0.9668 - val_loss: 0.0035 - val_mae: 0.0432 - val_rmse: 0.0584 - val_smape: 0.1445

Epoch 25/64

144/144 - 7s - 51ms/step - ia: 0.9657 - loss: 0.0064 - mae: 0.0566 - rmse: 0.0791 - smape: 0.1540 - val_ia: 0.9642 - val_loss: 0.0041 - val_mae: 0.0465 - val_rmse: 0.0621 - val_smape: 0.1444

Epoch 26/64

144/144 - 7s - 50ms/step - ia: 0.9656 - loss: 0.0064 - mae: 0.0568 - rmse: 0.0792 - smape: 0.1556 - val_ia: 0.9506 - val_loss: 0.0066 - val_mae: 0.0629 - val_rmse: 0.0781 - val_smape: 0.1829

Epoch 27/64

144/144 - 7s - 50ms/step - ia: 0.9659 - loss: 0.0063 - mae: 0.0564 - rmse: 0.0784 - smape: 0.1551 - val_ia: 0.9583 - val_loss: 0.0052 - val_mae: 0.0541 - val_rmse: 0.0697 - val_smape: 0.1501

Epoch 28/64

144/144 - 7s - 51ms/step - ia: 0.9655 - loss: 0.0064 - mae: 0.0568 - rmse: 0.0792 - smape: 0.1532 - val_ia: 0.9668 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0581 - val_smape: 0.1331

Epoch 29/64

144/144 - 7s - 50ms/step - ia: 0.9655 - loss: 0.0064 - mae: 0.0569 - rmse: 0.0792 - smape: 0.1554 - val_ia: 0.9613 - val_loss: 0.0048 - val_mae: 0.0513 - val_rmse: 0.0675 - val_smape: 0.1419

Epoch 30/64

144/144 - 7s - 52ms/step - ia: 0.9663 - loss: 0.0061 - mae: 0.0556 - rmse: 0.0775 - smape: 0.1529 - val_ia: 0.9664 - val_loss: 0.0038 - val_mae: 0.0438 - val_rmse: 0.0592 - val_smape: 0.1265

Epoch 31/64

144/144 - 7s - 49ms/step - ia: 0.9661 - loss: 0.0062 - mae: 0.0560 - rmse: 0.0779 - smape: 0.1526 - val_ia: 0.9635 - val_loss: 0.0043 - val_mae: 0.0477 - val_rmse: 0.0631 - val_smape: 0.1379

Epoch 32/64

144/144 - 7s - 50ms/step - ia: 0.9666 - loss: 0.0060 - mae: 0.0551 - rmse: 0.0766 - smape: 0.1505 - val_ia: 0.9617 - val_loss: 0.0045 - val_mae: 0.0488 - val_rmse: 0.0656 - val_smape: 0.1499

Epoch 33/64

144/144 - 7s - 51ms/step - ia: 0.9666 - loss: 0.0060 - mae: 0.0552 - rmse: 0.0767 - smape: 0.1515 - val_ia: 0.9698 - val_loss: 0.0031 - val_mae: 0.0403 - val_rmse: 0.0552 - val_smape: 0.1382

Epoch 34/64

144/144 - 7s - 51ms/step - ia: 0.9658 - loss: 0.0063 - mae: 0.0565 - rmse: 0.0787 - smape: 0.1527 - val_ia: 0.9678 - val_loss: 0.0033 - val_mae: 0.0426 - val_rmse: 0.0577 - val_smape: 0.1294

Epoch 35/64

144/144 - 8s - 54ms/step - ia: 0.9658 - loss: 0.0063 - mae: 0.0565 - rmse: 0.0784 - smape: 0.1522 - val_ia: 0.9669 - val_loss: 0.0036 - val_mae: 0.0436 - val_rmse: 0.0591 - val_smape: 0.1383

Epoch 36/64

144/144 - 7s - 48ms/step - ia: 0.9669 - loss: 0.0059 - mae: 0.0546 - rmse: 0.0759 - smape: 0.1493 - val_ia: 0.9689 - val_loss: 0.0035 - val_mae: 0.0413 - val_rmse: 0.0572 - val_smape: 0.1223

Epoch 37/64

144/144 - 7s - 51ms/step - ia: 0.9662 - loss: 0.0062 - mae: 0.0558 - rmse: 0.0778 - smape: 0.1516 - val_ia: 0.9576 - val_loss: 0.0056 - val_mae: 0.0567 - val_rmse: 0.0735 - val_smape: 0.1435

Epoch 38/64

144/144 - 7s - 50ms/step - ia: 0.9664 - loss: 0.0062 - mae: 0.0556 - rmse: 0.0777 - smape: 0.1506 - val_ia: 0.9657 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0593 - val_smape: 0.1301

Epoch 39/64

144/144 - 7s - 51ms/step - ia: 0.9663 - loss: 0.0061 - mae: 0.0557 - rmse: 0.0773 - smape: 0.1527 - val_ia: 0.9700 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0552 - val_smape: 0.1291

Epoch 40/64

144/144 - 7s - 50ms/step - ia: 0.9666 - loss: 0.0060 - mae: 0.0553 - rmse: 0.0767 - smape: 0.1510 - val_ia: 0.9669 - val_loss: 0.0037 - val_mae: 0.0433 - val_rmse: 0.0588 - val_smape: 0.1324

Epoch 41/64

144/144 - 10s - 71ms/step - ia: 0.9669 - loss: 0.0059 - mae: 0.0546 - rmse: 0.0760 - smape: 0.1495 - val_ia: 0.9652 - val_loss: 0.0038 - val_mae: 0.0462 - val_rmse: 0.0611 - val_smape: 0.1452

Epoch 42/64

144/144 - 7s - 50ms/step - ia: 0.9667 - loss: 0.0060 - mae: 0.0549 - rmse: 0.0763 - smape: 0.1494 - val_ia: 0.9716 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0522 - val_smape: 0.1206

Epoch 43/64

144/144 - 7s - 50ms/step - ia: 0.9666 - loss: 0.0061 - mae: 0.0552 - rmse: 0.0769 - smape: 0.1509 - val_ia: 0.9700 - val_loss: 0.0030 - val_mae: 0.0394 - val_rmse: 0.0540 - val_smape: 0.1244

Epoch 44/64

144/144 - 7s - 51ms/step - ia: 0.9668 - loss: 0.0059 - mae: 0.0547 - rmse: 0.0761 - smape: 0.1506 - val_ia: 0.9695 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0559 - val_smape: 0.1201

Epoch 45/64

144/144 - 7s - 48ms/step - ia: 0.9669 - loss: 0.0060 - mae: 0.0547 - rmse: 0.0763 - smape: 0.1489 - val_ia: 0.9677 - val_loss: 0.0034 - val_mae: 0.0411 - val_rmse: 0.0568 - val_smape: 0.1256

Epoch 46/64

144/144 - 7s - 50ms/step - ia: 0.9671 - loss: 0.0058 - mae: 0.0544 - rmse: 0.0755 - smape: 0.1501 - val_ia: 0.9646 - val_loss: 0.0039 - val_mae: 0.0454 - val_rmse: 0.0606 - val_smape: 0.1436

Epoch 47/64

144/144 - 7s - 50ms/step - ia: 0.9674 - loss: 0.0057 - mae: 0.0538 - rmse: 0.0750 - smape: 0.1487 - val_ia: 0.9677 - val_loss: 0.0033 - val_mae: 0.0425 - val_rmse: 0.0572 - val_smape: 0.1325

Epoch 48/64

144/144 - 7s - 50ms/step - ia: 0.9671 - loss: 0.0059 - mae: 0.0544 - rmse: 0.0759 - smape: 0.1480 - val_ia: 0.9676 - val_loss: 0.0034 - val_mae: 0.0438 - val_rmse: 0.0577 - val_smape: 0.1332

Epoch 49/64

144/144 - 7s - 50ms/step - ia: 0.9671 - loss: 0.0059 - mae: 0.0545 - rmse: 0.0755 - smape: 0.1502 - val_ia: 0.9682 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0571 - val_smape: 0.1252

Epoch 50/64

144/144 - 7s - 48ms/step - ia: 0.9677 - loss: 0.0056 - mae: 0.0534 - rmse: 0.0740 - smape: 0.1483 - val_ia: 0.9594 - val_loss: 0.0055 - val_mae: 0.0543 - val_rmse: 0.0711 - val_smape: 0.1314

Epoch 51/64

144/144 - 7s - 50ms/step - ia: 0.9675 - loss: 0.0057 - mae: 0.0536 - rmse: 0.0745 - smape: 0.1493 - val_ia: 0.9673 - val_loss: 0.0036 - val_mae: 0.0428 - val_rmse: 0.0592 - val_smape: 0.1165

Epoch 52/64

144/144 - 7s - 50ms/step - ia: 0.9670 - loss: 0.0059 - mae: 0.0545 - rmse: 0.0759 - smape: 0.1482 - val_ia: 0.9687 - val_loss: 0.0034 - val_mae: 0.0411 - val_rmse: 0.0561 - val_smape: 0.1161

Epoch 53/64

144/144 - 7s - 51ms/step - ia: 0.9675 - loss: 0.0058 - mae: 0.0536 - rmse: 0.0749 - smape: 0.1475 - val_ia: 0.9689 - val_loss: 0.0033 - val_mae: 0.0415 - val_rmse: 0.0571 - val_smape: 0.1277

Epoch 54/64

144/144 - 7s - 51ms/step - ia: 0.9675 - loss: 0.0056 - mae: 0.0537 - rmse: 0.0743 - smape: 0.1479 - val_ia: 0.9652 - val_loss: 0.0039 - val_mae: 0.0467 - val_rmse: 0.0621 - val_smape: 0.1286

Epoch 55/64

144/144 - 7s - 48ms/step - ia: 0.9670 - loss: 0.0059 - mae: 0.0545 - rmse: 0.0759 - smape: 0.1493 - val_ia: 0.9634 - val_loss: 0.0044 - val_mae: 0.0488 - val_rmse: 0.0629 - val_smape: 0.1499

Epoch 56/64

144/144 - 7s - 51ms/step - ia: 0.9673 - loss: 0.0058 - mae: 0.0539 - rmse: 0.0754 - smape: 0.1478 - val_ia: 0.9662 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0600 - val_smape: 0.1350

Epoch 57/64

144/144 - 7s - 51ms/step - ia: 0.9674 - loss: 0.0058 - mae: 0.0538 - rmse: 0.0751 - smape: 0.1477 - val_ia: 0.9702 - val_loss: 0.0031 - val_mae: 0.0391 - val_rmse: 0.0544 - val_smape: 0.1153

Epoch 57: early stopping

Restoring model weights from the end of the best epoch: 42.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 59s 368ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/128

 72%|███████▏  | 36/50 [10:28:19<2:16:50, 586.43s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

574/574 - 17s - 30ms/step - ia: 0.7789 - loss: 0.1892 - mae: 0.3123 - rmse: 0.3968 - smape: 0.6561 - val_ia: 0.8210 - val_loss: 0.0439 - val_mae: 0.1581 - val_rmse: 0.1987 - val_smape: 0.4203

Epoch 2/128

574/574 - 9s - 15ms/step - ia: 0.8894 - loss: 0.0564 - mae: 0.1784 - rmse: 0.2352 - smape: 0.3987 - val_ia: 0.8503 - val_loss: 0.0320 - val_mae: 0.1340 - val_rmse: 0.1686 - val_smape: 0.3289

Epoch 3/128

574/574 - 9s - 15ms/step - ia: 0.9025 - loss: 0.0451 - mae: 0.1579 - rmse: 0.2104 - smape: 0.3566 - val_ia: 0.8438 - val_loss: 0.0342 - val_mae: 0.1396 - val_rmse: 0.1738 - val_smape: 0.3293

Epoch 4/128

574/574 - 9s - 15ms/step - ia: 0.9091 - loss: 0.0395 - mae: 0.1468 - rmse: 0.1967 - smape: 0.3317 - val_ia: 0.8497 - val_loss: 0.0303 - val_mae: 0.1338 - val_rmse: 0.1644 - val_smape: 0.3059

Epoch 5/128

574/574 - 9s - 15ms/step - ia: 0.9145 - loss: 0.0352 - mae: 0.1384 - rmse: 0.1856 - smape: 0.3181 - val_ia: 0.8642 - val_loss: 0.0250 - val_mae: 0.1240 - val_rmse: 0.1518 - val_smape: 0.2786

Epoch 6/128

574/574 - 8s - 14ms/step - ia: 0.9179 - loss: 0.0328 - mae: 0.1331 - rmse: 0.1791 - smape: 0.3075 - val_ia: 0.8693 - val_loss: 0.0227 - val_mae: 0.1176 - val_rmse: 0.1421 - val_smape: 0.2846

Epoch 7/128

574/574 - 8s - 14ms/step - ia: 0.9204 - loss: 0.0310 - mae: 0.1292 - rmse: 0.1741 - smape: 0.2947 - val_ia: 0.8759 - val_loss: 0.0214 - val_mae: 0.1149 - val_rmse: 0.1394 - val_smape: 0.2661

Epoch 8/128

574/574 - 8s - 14ms/step - ia: 0.9234 - loss: 0.0290 - mae: 0.1243 - rmse: 0.1683 - smape: 0.2851 - val_ia: 0.8551 - val_loss: 0.0272 - val_mae: 0.1296 - val_rmse: 0.1546 - val_smape: 0.2730

Epoch 9/128

574/574 - 8s - 14ms/step - ia: 0.9242 - loss: 0.0285 - mae: 0.1231 - rmse: 0.1668 - smape: 0.2812 - val_ia: 0.8382 - val_loss: 0.0322 - val_mae: 0.1476 - val_rmse: 0.1709 - val_smape: 0.3253

Epoch 10/128

574/574 - 8s - 14ms/step - ia: 0.9263 - loss: 0.0271 - mae: 0.1197 - rmse: 0.1625 - smape: 0.2736 - val_ia: 0.8779 - val_loss: 0.0193 - val_mae: 0.1108 - val_rmse: 0.1318 - val_smape: 0.2537

Epoch 11/128

574/574 - 8s - 14ms/step - ia: 0.9270 - loss: 0.0266 - mae: 0.1183 - rmse: 0.1611 - smape: 0.2719 - val_ia: 0.8704 - val_loss: 0.0211 - val_mae: 0.1197 - val_rmse: 0.1411 - val_smape: 0.2608

Epoch 12/128

574/574 - 8s - 14ms/step - ia: 0.9280 - loss: 0.0261 - mae: 0.1173 - rmse: 0.1597 - smape: 0.2661 - val_ia: 0.8622 - val_loss: 0.0248 - val_mae: 0.1290 - val_rmse: 0.1520 - val_smape: 0.2791

Epoch 13/128

574/574 - 9s - 15ms/step - ia: 0.9293 - loss: 0.0253 - mae: 0.1150 - rmse: 0.1572 - smape: 0.2611 - val_ia: 0.8896 - val_loss: 0.0149 - val_mae: 0.1007 - val_rmse: 0.1187 - val_smape: 0.2340

Epoch 14/128

574/574 - 9s - 15ms/step - ia: 0.9294 - loss: 0.0253 - mae: 0.1146 - rmse: 0.1567 - smape: 0.2569 - val_ia: 0.8847 - val_loss: 0.0171 - val_mae: 0.1066 - val_rmse: 0.1268 - val_smape: 0.2415

Epoch 15/128

574/574 - 9s - 16ms/step - ia: 0.9314 - loss: 0.0236 - mae: 0.1116 - rmse: 0.1519 - smape: 0.2525 - val_ia: 0.8695 - val_loss: 0.0210 - val_mae: 0.1191 - val_rmse: 0.1394 - val_smape: 0.2694

Epoch 16/128

574/574 - 9s - 16ms/step - ia: 0.9317 - loss: 0.0238 - mae: 0.1112 - rmse: 0.1522 - smape: 0.2498 - val_ia: 0.8785 - val_loss: 0.0199 - val_mae: 0.1115 - val_rmse: 0.1347 - val_smape: 0.2313

Epoch 17/128

574/574 - 9s - 16ms/step - ia: 0.9321 - loss: 0.0235 - mae: 0.1104 - rmse: 0.1513 - smape: 0.2480 - val_ia: 0.8712 - val_loss: 0.0212 - val_mae: 0.1210 - val_rmse: 0.1407 - val_smape: 0.2507

Epoch 18/128

574/574 - 9s - 16ms/step - ia: 0.9324 - loss: 0.0236 - mae: 0.1099 - rmse: 0.1516 - smape: 0.2443 - val_ia: 0.8755 - val_loss: 0.0199 - val_mae: 0.1133 - val_rmse: 0.1351 - val_smape: 0.2266

Epoch 19/128

574/574 - 9s - 16ms/step - ia: 0.9328 - loss: 0.0233 - mae: 0.1093 - rmse: 0.1507 - smape: 0.2415 - val_ia: 0.8630 - val_loss: 0.0229 - val_mae: 0.1251 - val_rmse: 0.1448 - val_smape: 0.2505

Epoch 20/128

574/574 - 9s - 16ms/step - ia: 0.9337 - loss: 0.0227 - mae: 0.1080 - rmse: 0.1487 - smape: 0.2360 - val_ia: 0.8615 - val_loss: 0.0240 - val_mae: 0.1273 - val_rmse: 0.1482 - val_smape: 0.2557

Epoch 21/128

574/574 - 9s - 15ms/step - ia: 0.9333 - loss: 0.0233 - mae: 0.1086 - rmse: 0.1504 - smape: 0.2384 - val_ia: 0.8588 - val_loss: 0.0236 - val_mae: 0.1305 - val_rmse: 0.1488 - val_smape: 0.2712

Epoch 22/128

574/574 - 9s - 16ms/step - ia: 0.9347 - loss: 0.0223 - mae: 0.1063 - rmse: 0.1472 - smape: 0.2331 - val_ia: 0.8591 - val_loss: 0.0241 - val_mae: 0.1316 - val_rmse: 0.1510 - val_smape: 0.2668

Epoch 23/128

574/574 - 9s - 15ms/step - ia: 0.9356 - loss: 0.0218 - mae: 0.1048 - rmse: 0.1456 - smape: 0.2296 - val_ia: 0.8661 - val_loss: 0.0220 - val_mae: 0.1224 - val_rmse: 0.1425 - val_smape: 0.2331

Epoch 24/128

574/574 - 8s - 13ms/step - ia: 0.9365 - loss: 0.0211 - mae: 0.1032 - rmse: 0.1432 - smape: 0.2277 - val_ia: 0.8409 - val_loss: 0.0319 - val_mae: 0.1479 - val_rmse: 0.1727 - val_smape: 0.2779

Epoch 25/128

574/574 - 8s - 14ms/step - ia: 0.9371 - loss: 0.0208 - mae: 0.1025 - rmse: 0.1422 - smape: 0.2259 - val_ia: 0.8430 - val_loss: 0.0324 - val_mae: 0.1467 - val_rmse: 0.1723 - val_smape: 0.2835

Epoch 26/128

574/574 - 8s - 15ms/step - ia: 0.9372 - loss: 0.0207 - mae: 0.1021 - rmse: 0.1419 - smape: 0.2232 - val_ia: 0.8603 - val_loss: 0.0248 - val_mae: 0.1300 - val_rmse: 0.1519 - val_smape: 0.2442

Epoch 27/128

574/574 - 9s - 15ms/step - ia: 0.9373 - loss: 0.0207 - mae: 0.1021 - rmse: 0.1417 - smape: 0.2238 - val_ia: 0.8578 - val_loss: 0.0260 - val_mae: 0.1306 - val_rmse: 0.1542 - val_smape: 0.2396

Epoch 28/128

574/574 - 8s - 14ms/step - ia: 0.9371 - loss: 0.0210 - mae: 0.1023 - rmse: 0.1427 - smape: 0.2241 - val_ia: 0.8502 - val_loss: 0.0263 - val_mae: 0.1362 - val_rmse: 0.1569 - val_smape: 0.2613

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:50 683ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/256

 74%|███████▍  | 37/50 [10:32:30<1:45:16, 485.85s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 12s - 85ms/step - ia: 0.1870 - loss: 0.8322 - mae: 0.7541 - rmse: 0.9077 - smape: 1.6635 - val_ia: 0.4256 - val_loss: 0.5119 - val_mae: 0.5828 - val_rmse: 0.7092 - val_smape: 1.3064

Epoch 2/256

144/144 - 5s - 36ms/step - ia: 0.6885 - loss: 0.3077 - mae: 0.4302 - rmse: 0.5505 - smape: 0.8977 - val_ia: 0.6768 - val_loss: 0.2693 - val_mae: 0.4030 - val_rmse: 0.5137 - val_smape: 0.8849

Epoch 3/256

144/144 - 5s - 35ms/step - ia: 0.7878 - loss: 0.1859 - mae: 0.3241 - rmse: 0.4294 - smape: 0.6829 - val_ia: 0.7415 - val_loss: 0.1945 - val_mae: 0.3484 - val_rmse: 0.4368 - val_smape: 0.7456

Epoch 4/256

144/144 - 5s - 35ms/step - ia: 0.8538 - loss: 0.1018 - mae: 0.2327 - rmse: 0.3173 - smape: 0.5269 - val_ia: 0.8269 - val_loss: 0.0943 - val_mae: 0.2384 - val_rmse: 0.3032 - val_smape: 0.5948

Epoch 5/256

144/144 - 5s - 36ms/step - ia: 0.8863 - loss: 0.0644 - mae: 0.1844 - rmse: 0.2527 - smape: 0.4557 - val_ia: 0.8676 - val_loss: 0.0586 - val_mae: 0.1822 - val_rmse: 0.2371 - val_smape: 0.4995

Epoch 6/256

144/144 - 5s - 35ms/step - ia: 0.9058 - loss: 0.0453 - mae: 0.1537 - rmse: 0.2121 - smape: 0.4063 - val_ia: 0.8868 - val_loss: 0.0438 - val_mae: 0.1550 - val_rmse: 0.2058 - val_smape: 0.4598

Epoch 7/256

144/144 - 5s - 35ms/step - ia: 0.9206 - loss: 0.0330 - mae: 0.1299 - rmse: 0.1811 - smape: 0.3607 - val_ia: 0.8690 - val_loss: 0.0519 - val_mae: 0.1777 - val_rmse: 0.2242 - val_smape: 0.4924

Epoch 8/256

144/144 - 5s - 36ms/step - ia: 0.9303 - loss: 0.0259 - mae: 0.1141 - rmse: 0.1604 - smape: 0.3259 - val_ia: 0.8780 - val_loss: 0.0438 - val_mae: 0.1645 - val_rmse: 0.2074 - val_smape: 0.4601

Epoch 9/256

144/144 - 5s - 35ms/step - ia: 0.9377 - loss: 0.0212 - mae: 0.1022 - rmse: 0.1449 - smape: 0.2977 - val_ia: 0.8739 - val_loss: 0.0485 - val_mae: 0.1702 - val_rmse: 0.2194 - val_smape: 0.4775

Epoch 10/256

144/144 - 5s - 33ms/step - ia: 0.9440 - loss: 0.0175 - mae: 0.0919 - rmse: 0.1315 - smape: 0.2676 - val_ia: 0.9056 - val_loss: 0.0307 - val_mae: 0.1268 - val_rmse: 0.1747 - val_smape: 0.3631

Epoch 11/256

144/144 - 5s - 35ms/step - ia: 0.9495 - loss: 0.0146 - mae: 0.0830 - rmse: 0.1199 - smape: 0.2436 - val_ia: 0.9184 - val_loss: 0.0266 - val_mae: 0.1095 - val_rmse: 0.1622 - val_smape: 0.3045

Epoch 12/256

144/144 - 5s - 35ms/step - ia: 0.9526 - loss: 0.0129 - mae: 0.0779 - rmse: 0.1127 - smape: 0.2308 - val_ia: 0.9249 - val_loss: 0.0200 - val_mae: 0.1003 - val_rmse: 0.1397 - val_smape: 0.2737

Epoch 13/256

144/144 - 5s - 35ms/step - ia: 0.9533 - loss: 0.0124 - mae: 0.0768 - rmse: 0.1101 - smape: 0.2280 - val_ia: 0.9315 - val_loss: 0.0171 - val_mae: 0.0901 - val_rmse: 0.1293 - val_smape: 0.2624

Epoch 14/256

144/144 - 5s - 35ms/step - ia: 0.9581 - loss: 0.0103 - mae: 0.0691 - rmse: 0.1005 - smape: 0.2089 - val_ia: 0.9150 - val_loss: 0.0214 - val_mae: 0.1122 - val_rmse: 0.1436 - val_smape: 0.3018

Epoch 15/256

144/144 - 5s - 38ms/step - ia: 0.9595 - loss: 0.0096 - mae: 0.0668 - rmse: 0.0967 - smape: 0.2037 - val_ia: 0.9305 - val_loss: 0.0170 - val_mae: 0.0903 - val_rmse: 0.1265 - val_smape: 0.2711

Epoch 16/256

144/144 - 5s - 37ms/step - ia: 0.9608 - loss: 0.0089 - mae: 0.0646 - rmse: 0.0935 - smape: 0.1981 - val_ia: 0.9123 - val_loss: 0.0230 - val_mae: 0.1116 - val_rmse: 0.1464 - val_smape: 0.3098

Epoch 17/256

144/144 - 5s - 37ms/step - ia: 0.9620 - loss: 0.0084 - mae: 0.0625 - rmse: 0.0903 - smape: 0.1934 - val_ia: 0.9084 - val_loss: 0.0237 - val_mae: 0.1137 - val_rmse: 0.1499 - val_smape: 0.3264

Epoch 18/256

144/144 - 5s - 36ms/step - ia: 0.9624 - loss: 0.0081 - mae: 0.0620 - rmse: 0.0889 - smape: 0.1918 - val_ia: 0.9222 - val_loss: 0.0204 - val_mae: 0.0975 - val_rmse: 0.1388 - val_smape: 0.2885

Epoch 19/256

144/144 - 5s - 35ms/step - ia: 0.9641 - loss: 0.0075 - mae: 0.0592 - rmse: 0.0857 - smape: 0.1852 - val_ia: 0.9158 - val_loss: 0.0206 - val_mae: 0.1018 - val_rmse: 0.1400 - val_smape: 0.2974

Epoch 20/256

144/144 - 5s - 36ms/step - ia: 0.9654 - loss: 0.0071 - mae: 0.0572 - rmse: 0.0832 - smape: 0.1799 - val_ia: 0.9140 - val_loss: 0.0217 - val_mae: 0.1033 - val_rmse: 0.1445 - val_smape: 0.3016

Epoch 21/256

144/144 - 5s - 35ms/step - ia: 0.9653 - loss: 0.0070 - mae: 0.0572 - rmse: 0.0826 - smape: 0.1806 - val_ia: 0.9156 - val_loss: 0.0202 - val_mae: 0.0995 - val_rmse: 0.1368 - val_smape: 0.2876

Epoch 22/256

144/144 - 5s - 35ms/step - ia: 0.9668 - loss: 0.0066 - mae: 0.0549 - rmse: 0.0798 - smape: 0.1735 - val_ia: 0.9070 - val_loss: 0.0237 - val_mae: 0.1106 - val_rmse: 0.1486 - val_smape: 0.3145

Epoch 23/256

144/144 - 5s - 32ms/step - ia: 0.9677 - loss: 0.0063 - mae: 0.0534 - rmse: 0.0781 - smape: 0.1715 - val_ia: 0.9131 - val_loss: 0.0204 - val_mae: 0.1039 - val_rmse: 0.1401 - val_smape: 0.3007

Epoch 24/256

144/144 - 5s - 36ms/step - ia: 0.9680 - loss: 0.0062 - mae: 0.0528 - rmse: 0.0772 - smape: 0.1694 - val_ia: 0.9183 - val_loss: 0.0182 - val_mae: 0.0957 - val_rmse: 0.1306 - val_smape: 0.2806

Epoch 25/256

144/144 - 5s - 36ms/step - ia: 0.9675 - loss: 0.0062 - mae: 0.0537 - rmse: 0.0775 - smape: 0.1716 - val_ia: 0.9166 - val_loss: 0.0188 - val_mae: 0.0975 - val_rmse: 0.1329 - val_smape: 0.2853

Epoch 26/256

144/144 - 5s - 36ms/step - ia: 0.9690 - loss: 0.0058 - mae: 0.0513 - rmse: 0.0749 - smape: 0.1651 - val_ia: 0.9028 - val_loss: 0.0250 - val_mae: 0.1166 - val_rmse: 0.1521 - val_smape: 0.3195

Epoch 27/256

144/144 - 5s - 35ms/step - ia: 0.9694 - loss: 0.0056 - mae: 0.0505 - rmse: 0.0736 - smape: 0.1639 - val_ia: 0.9145 - val_loss: 0.0194 - val_mae: 0.1013 - val_rmse: 0.1345 - val_smape: 0.2863

Epoch 28/256

144/144 - 5s - 35ms/step - ia: 0.9697 - loss: 0.0055 - mae: 0.0500 - rmse: 0.0731 - smape: 0.1624 - val_ia: 0.8893 - val_loss: 0.0307 - val_mae: 0.1350 - val_rmse: 0.1700 - val_smape: 0.3603

Epoch 29/256

144/144 - 5s - 35ms/step - ia: 0.9698 - loss: 0.0055 - mae: 0.0498 - rmse: 0.0726 - smape: 0.1629 - val_ia: 0.9281 - val_loss: 0.0137 - val_mae: 0.0845 - val_rmse: 0.1136 - val_smape: 0.2451

Epoch 30/256

144/144 - 5s - 34ms/step - ia: 0.9698 - loss: 0.0054 - mae: 0.0499 - rmse: 0.0723 - smape: 0.1629 - val_ia: 0.9296 - val_loss: 0.0127 - val_mae: 0.0829 - val_rmse: 0.1113 - val_smape: 0.2436

Epoch 31/256

144/144 - 5s - 35ms/step - ia: 0.9704 - loss: 0.0052 - mae: 0.0489 - rmse: 0.0710 - smape: 0.1601 - val_ia: 0.9028 - val_loss: 0.0247 - val_mae: 0.1179 - val_rmse: 0.1511 - val_smape: 0.3215

Epoch 32/256

144/144 - 5s - 35ms/step - ia: 0.9702 - loss: 0.0053 - mae: 0.0492 - rmse: 0.0711 - smape: 0.1605 - val_ia: 0.9367 - val_loss: 0.0105 - val_mae: 0.0769 - val_rmse: 0.1019 - val_smape: 0.2273

Epoch 33/256

144/144 - 5s - 35ms/step - ia: 0.9708 - loss: 0.0051 - mae: 0.0481 - rmse: 0.0699 - smape: 0.1588 - val_ia: 0.9282 - val_loss: 0.0141 - val_mae: 0.0853 - val_rmse: 0.1139 - val_smape: 0.2374

Epoch 34/256

144/144 - 5s - 35ms/step - ia: 0.9710 - loss: 0.0050 - mae: 0.0479 - rmse: 0.0694 - smape: 0.1584 - val_ia: 0.9226 - val_loss: 0.0155 - val_mae: 0.0935 - val_rmse: 0.1215 - val_smape: 0.2629

Epoch 35/256

144/144 - 5s - 36ms/step - ia: 0.9716 - loss: 0.0049 - mae: 0.0469 - rmse: 0.0685 - smape: 0.1558 - val_ia: 0.9329 - val_loss: 0.0123 - val_mae: 0.0800 - val_rmse: 0.1072 - val_smape: 0.2281

Epoch 36/256

144/144 - 5s - 33ms/step - ia: 0.9719 - loss: 0.0048 - mae: 0.0464 - rmse: 0.0678 - smape: 0.1547 - val_ia: 0.9302 - val_loss: 0.0130 - val_mae: 0.0841 - val_rmse: 0.1114 - val_smape: 0.2368

Epoch 37/256

144/144 - 5s - 34ms/step - ia: 0.9723 - loss: 0.0047 - mae: 0.0458 - rmse: 0.0671 - smape: 0.1530 - val_ia: 0.9413 - val_loss: 0.0094 - val_mae: 0.0710 - val_rmse: 0.0949 - val_smape: 0.2059

Epoch 38/256

144/144 - 5s - 35ms/step - ia: 0.9725 - loss: 0.0046 - mae: 0.0454 - rmse: 0.0664 - smape: 0.1525 - val_ia: 0.9437 - val_loss: 0.0091 - val_mae: 0.0694 - val_rmse: 0.0936 - val_smape: 0.2037

Epoch 39/256

144/144 - 5s - 35ms/step - ia: 0.9725 - loss: 0.0046 - mae: 0.0454 - rmse: 0.0660 - smape: 0.1527 - val_ia: 0.9391 - val_loss: 0.0105 - val_mae: 0.0738 - val_rmse: 0.1002 - val_smape: 0.2146

Epoch 40/256

144/144 - 5s - 35ms/step - ia: 0.9730 - loss: 0.0044 - mae: 0.0446 - rmse: 0.0651 - smape: 0.1508 - val_ia: 0.9408 - val_loss: 0.0100 - val_mae: 0.0718 - val_rmse: 0.0972 - val_smape: 0.2048

Epoch 41/256

144/144 - 5s - 36ms/step - ia: 0.9735 - loss: 0.0043 - mae: 0.0438 - rmse: 0.0643 - smape: 0.1487 - val_ia: 0.9382 - val_loss: 0.0109 - val_mae: 0.0751 - val_rmse: 0.1016 - val_smape: 0.2159

Epoch 42/256

144/144 - 5s - 35ms/step - ia: 0.9731 - loss: 0.0044 - mae: 0.0444 - rmse: 0.0645 - smape: 0.1514 - val_ia: 0.9465 - val_loss: 0.0091 - val_mae: 0.0662 - val_rmse: 0.0927 - val_smape: 0.1939

Epoch 43/256

144/144 - 5s - 33ms/step - ia: 0.9736 - loss: 0.0043 - mae: 0.0437 - rmse: 0.0637 - smape: 0.1494 - val_ia: 0.9474 - val_loss: 0.0092 - val_mae: 0.0648 - val_rmse: 0.0920 - val_smape: 0.1896

Epoch 44/256

144/144 - 5s - 36ms/step - ia: 0.9742 - loss: 0.0041 - mae: 0.0426 - rmse: 0.0626 - smape: 0.1468 - val_ia: 0.9422 - val_loss: 0.0105 - val_mae: 0.0719 - val_rmse: 0.0989 - val_smape: 0.2044

Epoch 45/256

144/144 - 5s - 36ms/step - ia: 0.9730 - loss: 0.0043 - mae: 0.0447 - rmse: 0.0643 - smape: 0.1522 - val_ia: 0.9472 - val_loss: 0.0096 - val_mae: 0.0661 - val_rmse: 0.0937 - val_smape: 0.1917

Epoch 46/256

144/144 - 5s - 36ms/step - ia: 0.9739 - loss: 0.0041 - mae: 0.0431 - rmse: 0.0627 - smape: 0.1481 - val_ia: 0.9381 - val_loss: 0.0114 - val_mae: 0.0780 - val_rmse: 0.1041 - val_smape: 0.2227

Epoch 47/256

144/144 - 5s - 36ms/step - ia: 0.9746 - loss: 0.0040 - mae: 0.0419 - rmse: 0.0614 - smape: 0.1446 - val_ia: 0.9490 - val_loss: 0.0098 - val_mae: 0.0635 - val_rmse: 0.0937 - val_smape: 0.1865

Epoch 48/256

144/144 - 5s - 35ms/step - ia: 0.9750 - loss: 0.0039 - mae: 0.0412 - rmse: 0.0607 - smape: 0.1440 - val_ia: 0.9453 - val_loss: 0.0099 - val_mae: 0.0678 - val_rmse: 0.0961 - val_smape: 0.1972

Epoch 49/256

144/144 - 5s - 35ms/step - ia: 0.9747 - loss: 0.0039 - mae: 0.0418 - rmse: 0.0610 - smape: 0.1457 - val_ia: 0.9475 - val_loss: 0.0113 - val_mae: 0.0666 - val_rmse: 0.0999 - val_smape: 0.2027

Epoch 50/256

144/144 - 5s - 34ms/step - ia: 0.9755 - loss: 0.0038 - mae: 0.0405 - rmse: 0.0596 - smape: 0.1424 - val_ia: 0.9491 - val_loss: 0.0101 - val_mae: 0.0641 - val_rmse: 0.0950 - val_smape: 0.1881

Epoch 51/256

144/144 - 5s - 35ms/step - ia: 0.9754 - loss: 0.0037 - mae: 0.0406 - rmse: 0.0595 - smape: 0.1423 - val_ia: 0.9475 - val_loss: 0.0114 - val_mae: 0.0672 - val_rmse: 0.0993 - val_smape: 0.2037

Epoch 52/256

144/144 - 5s - 35ms/step - ia: 0.9751 - loss: 0.0038 - mae: 0.0412 - rmse: 0.0601 - smape: 0.1444 - val_ia: 0.9445 - val_loss: 0.0122 - val_mae: 0.0702 - val_rmse: 0.1038 - val_smape: 0.2051

Epoch 53/256

144/144 - 5s - 35ms/step - ia: 0.9734 - loss: 0.0041 - mae: 0.0440 - rmse: 0.0627 - smape: 0.1518 - val_ia: 0.9398 - val_loss: 0.0116 - val_mae: 0.0774 - val_rmse: 0.1036 - val_smape: 0.2162

Epoch 53: early stopping

Restoring model weights from the end of the best epoch: 38.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:28 547ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 76%|███████▌  | 38/50 [10:37:09<1:24:44, 423.69s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 22s - 19ms/step - ia: 0.8940 - loss: 0.0559 - mae: 0.1634 - rmse: 0.2125 - smape: 0.3763 - val_ia: 0.8062 - val_loss: 0.0150 - val_mae: 0.0914 - val_rmse: 0.1144 - val_smape: 0.2603

Epoch 2/128

1147/1147 - 18s - 15ms/step - ia: 0.9325 - loss: 0.0218 - mae: 0.1087 - rmse: 0.1447 - smape: 0.2630 - val_ia: 0.8183 - val_loss: 0.0126 - val_mae: 0.0838 - val_rmse: 0.1048 - val_smape: 0.2373

Epoch 3/128

1147/1147 - 17s - 15ms/step - ia: 0.9385 - loss: 0.0183 - mae: 0.0989 - rmse: 0.1323 - smape: 0.2410 - val_ia: 0.8406 - val_loss: 0.0104 - val_mae: 0.0754 - val_rmse: 0.0947 - val_smape: 0.2134

Epoch 4/128

1147/1147 - 17s - 15ms/step - ia: 0.9416 - loss: 0.0167 - mae: 0.0942 - rmse: 0.1262 - smape: 0.2291 - val_ia: 0.8477 - val_loss: 0.0084 - val_mae: 0.0677 - val_rmse: 0.0851 - val_smape: 0.1901

Epoch 5/128

1147/1147 - 18s - 16ms/step - ia: 0.9441 - loss: 0.0154 - mae: 0.0902 - rmse: 0.1211 - smape: 0.2189 - val_ia: 0.8573 - val_loss: 0.0068 - val_mae: 0.0611 - val_rmse: 0.0766 - val_smape: 0.1717

Epoch 6/128

1147/1147 - 17s - 15ms/step - ia: 0.9449 - loss: 0.0149 - mae: 0.0888 - rmse: 0.1192 - smape: 0.2155 - val_ia: 0.8627 - val_loss: 0.0068 - val_mae: 0.0614 - val_rmse: 0.0770 - val_smape: 0.1797

Epoch 7/128

1147/1147 - 17s - 15ms/step - ia: 0.9461 - loss: 0.0144 - mae: 0.0868 - rmse: 0.1171 - smape: 0.2083 - val_ia: 0.8803 - val_loss: 0.0053 - val_mae: 0.0526 - val_rmse: 0.0683 - val_smape: 0.1702

Epoch 8/128

1147/1147 - 17s - 15ms/step - ia: 0.9473 - loss: 0.0138 - mae: 0.0851 - rmse: 0.1148 - smape: 0.2036 - val_ia: 0.8616 - val_loss: 0.0068 - val_mae: 0.0616 - val_rmse: 0.0767 - val_smape: 0.1830

Epoch 9/128

1147/1147 - 17s - 15ms/step - ia: 0.9478 - loss: 0.0137 - mae: 0.0844 - rmse: 0.1141 - smape: 0.2028 - val_ia: 0.8089 - val_loss: 0.0108 - val_mae: 0.0837 - val_rmse: 0.0963 - val_smape: 0.2488

Epoch 10/128

1147/1147 - 18s - 15ms/step - ia: 0.9480 - loss: 0.0136 - mae: 0.0839 - rmse: 0.1137 - smape: 0.1999 - val_ia: 0.8422 - val_loss: 0.0072 - val_mae: 0.0651 - val_rmse: 0.0777 - val_smape: 0.2041

Epoch 11/128

1147/1147 - 19s - 16ms/step - ia: 0.9492 - loss: 0.0129 - mae: 0.0820 - rmse: 0.1110 - smape: 0.1977 - val_ia: 0.8432 - val_loss: 0.0074 - val_mae: 0.0656 - val_rmse: 0.0794 - val_smape: 0.1723

Epoch 12/128

1147/1147 - 18s - 15ms/step - ia: 0.9494 - loss: 0.0129 - mae: 0.0818 - rmse: 0.1109 - smape: 0.1947 - val_ia: 0.8807 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0655 - val_smape: 0.1716

Epoch 13/128

1147/1147 - 18s - 15ms/step - ia: 0.9502 - loss: 0.0126 - mae: 0.0806 - rmse: 0.1095 - smape: 0.1906 - val_ia: 0.8758 - val_loss: 0.0054 - val_mae: 0.0547 - val_rmse: 0.0688 - val_smape: 0.1561

Epoch 14/128

1147/1147 - 18s - 15ms/step - ia: 0.9501 - loss: 0.0124 - mae: 0.0806 - rmse: 0.1088 - smape: 0.1934 - val_ia: 0.8674 - val_loss: 0.0066 - val_mae: 0.0609 - val_rmse: 0.0755 - val_smape: 0.2059

Epoch 15/128

1147/1147 - 19s - 16ms/step - ia: 0.9504 - loss: 0.0126 - mae: 0.0801 - rmse: 0.1094 - smape: 0.1889 - val_ia: 0.8658 - val_loss: 0.0055 - val_mae: 0.0562 - val_rmse: 0.0693 - val_smape: 0.1722

Epoch 16/128

1147/1147 - 17s - 15ms/step - ia: 0.9516 - loss: 0.0118 - mae: 0.0783 - rmse: 0.1061 - smape: 0.1870 - val_ia: 0.8765 - val_loss: 0.0046 - val_mae: 0.0517 - val_rmse: 0.0642 - val_smape: 0.1467

Epoch 17/128

1147/1147 - 17s - 15ms/step - ia: 0.9512 - loss: 0.0120 - mae: 0.0788 - rmse: 0.1067 - smape: 0.1862 - val_ia: 0.8946 - val_loss: 0.0039 - val_mae: 0.0453 - val_rmse: 0.0584 - val_smape: 0.1488

Epoch 18/128

1147/1147 - 17s - 15ms/step - ia: 0.9514 - loss: 0.0121 - mae: 0.0786 - rmse: 0.1071 - smape: 0.1857 - val_ia: 0.9048 - val_loss: 0.0034 - val_mae: 0.0427 - val_rmse: 0.0549 - val_smape: 0.1358

Epoch 19/128

1147/1147 - 17s - 15ms/step - ia: 0.9512 - loss: 0.0122 - mae: 0.0787 - rmse: 0.1074 - smape: 0.1871 - val_ia: 0.8873 - val_loss: 0.0044 - val_mae: 0.0493 - val_rmse: 0.0618 - val_smape: 0.1505

Epoch 20/128

1147/1147 - 18s - 16ms/step - ia: 0.9512 - loss: 0.0120 - mae: 0.0788 - rmse: 0.1071 - smape: 0.1872 - val_ia: 0.8917 - val_loss: 0.0041 - val_mae: 0.0472 - val_rmse: 0.0604 - val_smape: 0.1339

Epoch 21/128

1147/1147 - 18s - 15ms/step - ia: 0.9517 - loss: 0.0118 - mae: 0.0779 - rmse: 0.1062 - smape: 0.1836 - val_ia: 0.8917 - val_loss: 0.0040 - val_mae: 0.0474 - val_rmse: 0.0597 - val_smape: 0.1460

Epoch 22/128

1147/1147 - 18s - 15ms/step - ia: 0.9521 - loss: 0.0117 - mae: 0.0774 - rmse: 0.1053 - smape: 0.1842 - val_ia: 0.8983 - val_loss: 0.0038 - val_mae: 0.0448 - val_rmse: 0.0579 - val_smape: 0.1478

Epoch 23/128

1147/1147 - 18s - 15ms/step - ia: 0.9520 - loss: 0.0117 - mae: 0.0775 - rmse: 0.1055 - smape: 0.1825 - val_ia: 0.8989 - val_loss: 0.0036 - val_mae: 0.0443 - val_rmse: 0.0569 - val_smape: 0.1383

Epoch 24/128

1147/1147 - 18s - 16ms/step - ia: 0.9522 - loss: 0.0117 - mae: 0.0773 - rmse: 0.1055 - smape: 0.1825 - val_ia: 0.9020 - val_loss: 0.0035 - val_mae: 0.0436 - val_rmse: 0.0559 - val_smape: 0.1330

Epoch 25/128

1147/1147 - 17s - 15ms/step - ia: 0.9529 - loss: 0.0113 - mae: 0.0760 - rmse: 0.1035 - smape: 0.1802 - val_ia: 0.8892 - val_loss: 0.0039 - val_mae: 0.0475 - val_rmse: 0.0596 - val_smape: 0.1394

Epoch 26/128

1147/1147 - 17s - 15ms/step - ia: 0.9521 - loss: 0.0117 - mae: 0.0773 - rmse: 0.1054 - smape: 0.1819 - val_ia: 0.9074 - val_loss: 0.0031 - val_mae: 0.0407 - val_rmse: 0.0529 - val_smape: 0.1285

Epoch 27/128

1147/1147 - 17s - 15ms/step - ia: 0.9520 - loss: 0.0117 - mae: 0.0775 - rmse: 0.1055 - smape: 0.1815 - val_ia: 0.8573 - val_loss: 0.0062 - val_mae: 0.0589 - val_rmse: 0.0710 - val_smape: 0.1548

Epoch 28/128

1147/1147 - 17s - 15ms/step - ia: 0.9526 - loss: 0.0115 - mae: 0.0765 - rmse: 0.1044 - smape: 0.1807 - val_ia: 0.8659 - val_loss: 0.0053 - val_mae: 0.0549 - val_rmse: 0.0676 - val_smape: 0.1578

Epoch 29/128

1147/1147 - 17s - 15ms/step - ia: 0.9528 - loss: 0.0115 - mae: 0.0763 - rmse: 0.1043 - smape: 0.1797 - val_ia: 0.8962 - val_loss: 0.0038 - val_mae: 0.0448 - val_rmse: 0.0573 - val_smape: 0.1401

Epoch 30/128

1147/1147 - 17s - 15ms/step - ia: 0.9529 - loss: 0.0114 - mae: 0.0762 - rmse: 0.1040 - smape: 0.1785 - val_ia: 0.8918 - val_loss: 0.0037 - val_mae: 0.0453 - val_rmse: 0.0571 - val_smape: 0.1352

Epoch 31/128

1147/1147 - 17s - 15ms/step - ia: 0.9532 - loss: 0.0111 - mae: 0.0755 - rmse: 0.1031 - smape: 0.1775 - val_ia: 0.8935 - val_loss: 0.0039 - val_mae: 0.0460 - val_rmse: 0.0587 - val_smape: 0.1495

Epoch 32/128

1147/1147 - 17s - 15ms/step - ia: 0.9532 - loss: 0.0112 - mae: 0.0754 - rmse: 0.1030 - smape: 0.1784 - val_ia: 0.8733 - val_loss: 0.0044 - val_mae: 0.0513 - val_rmse: 0.0628 - val_smape: 0.1482

Epoch 33/128

1147/1147 - 17s - 15ms/step - ia: 0.9529 - loss: 0.0113 - mae: 0.0760 - rmse: 0.1034 - smape: 0.1805 - val_ia: 0.9086 - val_loss: 0.0029 - val_mae: 0.0394 - val_rmse: 0.0507 - val_smape: 0.1269

Epoch 34/128

1147/1147 - 18s - 15ms/step - ia: 0.9531 - loss: 0.0113 - mae: 0.0759 - rmse: 0.1037 - smape: 0.1795 - val_ia: 0.8972 - val_loss: 0.0039 - val_mae: 0.0453 - val_rmse: 0.0585 - val_smape: 0.1397

Epoch 35/128

1147/1147 - 18s - 16ms/step - ia: 0.9532 - loss: 0.0112 - mae: 0.0755 - rmse: 0.1031 - smape: 0.1781 - val_ia: 0.8708 - val_loss: 0.0050 - val_mae: 0.0548 - val_rmse: 0.0665 - val_smape: 0.1605

Epoch 36/128

1147/1147 - 17s - 15ms/step - ia: 0.9533 - loss: 0.0112 - mae: 0.0753 - rmse: 0.1030 - smape: 0.1787 - val_ia: 0.8743 - val_loss: 0.0048 - val_mae: 0.0516 - val_rmse: 0.0638 - val_smape: 0.1318

Epoch 37/128

1147/1147 - 18s - 15ms/step - ia: 0.9530 - loss: 0.0114 - mae: 0.0759 - rmse: 0.1040 - smape: 0.1779 - val_ia: 0.9003 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0576 - val_smape: 0.1294

Epoch 38/128

1147/1147 - 17s - 15ms/step - ia: 0.9535 - loss: 0.0110 - mae: 0.0749 - rmse: 0.1021 - smape: 0.1768 - val_ia: 0.9147 - val_loss: 0.0028 - val_mae: 0.0372 - val_rmse: 0.0496 - val_smape: 0.1234

Epoch 39/128

1147/1147 - 17s - 15ms/step - ia: 0.9536 - loss: 0.0110 - mae: 0.0750 - rmse: 0.1021 - smape: 0.1780 - val_ia: 0.9118 - val_loss: 0.0028 - val_mae: 0.0375 - val_rmse: 0.0492 - val_smape: 0.1225

Epoch 40/128

1147/1147 - 17s - 15ms/step - ia: 0.9543 - loss: 0.0108 - mae: 0.0739 - rmse: 0.1010 - smape: 0.1741 - val_ia: 0.9125 - val_loss: 0.0028 - val_mae: 0.0377 - val_rmse: 0.0498 - val_smape: 0.1282

Epoch 41/128

1147/1147 - 18s - 16ms/step - ia: 0.9534 - loss: 0.0111 - mae: 0.0753 - rmse: 0.1028 - smape: 0.1775 - val_ia: 0.8630 - val_loss: 0.0052 - val_mae: 0.0549 - val_rmse: 0.0666 - val_smape: 0.1372

Epoch 42/128

1147/1147 - 17s - 15ms/step - ia: 0.9539 - loss: 0.0109 - mae: 0.0744 - rmse: 0.1019 - smape: 0.1749 - val_ia: 0.8920 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0544 - val_smape: 0.1279

Epoch 43/128

1147/1147 - 18s - 15ms/step - ia: 0.9539 - loss: 0.0110 - mae: 0.0746 - rmse: 0.1021 - smape: 0.1763 - val_ia: 0.8567 - val_loss: 0.0058 - val_mae: 0.0619 - val_rmse: 0.0726 - val_smape: 0.1796

Epoch 44/128

1147/1147 - 17s - 15ms/step - ia: 0.9538 - loss: 0.0110 - mae: 0.0747 - rmse: 0.1023 - smape: 0.1758 - val_ia: 0.9028 - val_loss: 0.0030 - val_mae: 0.0402 - val_rmse: 0.0517 - val_smape: 0.1262

Epoch 45/128

1147/1147 - 18s - 15ms/step - ia: 0.9539 - loss: 0.0110 - mae: 0.0745 - rmse: 0.1022 - smape: 0.1761 - val_ia: 0.8763 - val_loss: 0.0044 - val_mae: 0.0509 - val_rmse: 0.0625 - val_smape: 0.1640

Epoch 46/128

1147/1147 - 17s - 15ms/step - ia: 0.9544 - loss: 0.0108 - mae: 0.0738 - rmse: 0.1011 - smape: 0.1754 - val_ia: 0.9001 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0557 - val_smape: 0.1575

Epoch 47/128

1147/1147 - 16s - 14ms/step - ia: 0.9536 - loss: 0.0111 - mae: 0.0750 - rmse: 0.1026 - smape: 0.1750 - val_ia: 0.8749 - val_loss: 0.0046 - val_mae: 0.0529 - val_rmse: 0.0647 - val_smape: 0.1595

Epoch 48/128

1147/1147 - 18s - 16ms/step - ia: 0.9541 - loss: 0.0108 - mae: 0.0742 - rmse: 0.1012 - smape: 0.1751 - val_ia: 0.8947 - val_loss: 0.0033 - val_mae: 0.0424 - val_rmse: 0.0543 - val_smape: 0.1298

Epoch 49/128

1147/1147 - 18s - 16ms/step - ia: 0.9541 - loss: 0.0108 - mae: 0.0742 - rmse: 0.1011 - smape: 0.1746 - val_ia: 0.9055 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0497 - val_smape: 0.1265

Epoch 50/128

1147/1147 - 18s - 16ms/step - ia: 0.9541 - loss: 0.0109 - mae: 0.0744 - rmse: 0.1017 - smape: 0.1751 - val_ia: 0.9017 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0532 - val_smape: 0.1380

Epoch 51/128

1147/1147 - 18s - 16ms/step - ia: 0.9543 - loss: 0.0108 - mae: 0.0740 - rmse: 0.1013 - smape: 0.1737 - val_ia: 0.8916 - val_loss: 0.0036 - val_mae: 0.0442 - val_rmse: 0.0565 - val_smape: 0.1357

Epoch 52/128

1147/1147 - 18s - 16ms/step - ia: 0.9540 - loss: 0.0109 - mae: 0.0744 - rmse: 0.1017 - smape: 0.1749 - val_ia: 0.8697 - val_loss: 0.0047 - val_mae: 0.0512 - val_rmse: 0.0632 - val_smape: 0.1327

Epoch 53/128

1147/1147 - 18s - 16ms/step - ia: 0.9542 - loss: 0.0109 - mae: 0.0741 - rmse: 0.1014 - smape: 0.1741 - val_ia: 0.9098 - val_loss: 0.0029 - val_mae: 0.0391 - val_rmse: 0.0509 - val_smape: 0.1270

Epoch 54/128

1147/1147 - 18s - 16ms/step - ia: 0.9548 - loss: 0.0105 - mae: 0.0731 - rmse: 0.1000 - smape: 0.1728 - val_ia: 0.8918 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0555 - val_smape: 0.1272

Epoch 54: early stopping

Restoring model weights from the end of the best epoch: 39.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:14 460ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

Epoch 1/128

 78%|███████▊  | 39/50 [10:53:04<1:46:53, 583.05s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 10s - 66ms/step - ia: 0.0579 - loss: 1.0054 - mae: 0.8318 - rmse: 1.0025 - smape: 1.9280 - val_ia: 0.2180 - val_loss: 0.8456 - val_mae: 0.7630 - val_rmse: 0.9122 - val_smape: 1.8161

Epoch 2/128

144/144 - 2s - 15ms/step - ia: 0.0542 - loss: 1.0009 - mae: 0.8299 - rmse: 0.9996 - smape: 1.9227 - val_ia: 0.2206 - val_loss: 0.8390 - val_mae: 0.7595 - val_rmse: 0.9089 - val_smape: 1.7968

Epoch 3/128

144/144 - 2s - 14ms/step - ia: 0.0618 - loss: 0.9963 - mae: 0.8279 - rmse: 0.9972 - smape: 1.9148 - val_ia: 0.2233 - val_loss: 0.8320 - val_mae: 0.7558 - val_rmse: 0.9053 - val_smape: 1.7743

Epoch 4/128

144/144 - 2s - 15ms/step - ia: 0.0617 - loss: 0.9915 - mae: 0.8258 - rmse: 0.9955 - smape: 1.9044 - val_ia: 0.2264 - val_loss: 0.8245 - val_mae: 0.7517 - val_rmse: 0.9015 - val_smape: 1.7498

Epoch 5/128

144/144 - 2s - 14ms/step - ia: 0.0651 - loss: 0.9866 - mae: 0.8237 - rmse: 0.9929 - smape: 1.8922 - val_ia: 0.2296 - val_loss: 0.8167 - val_mae: 0.7474 - val_rmse: 0.8975 - val_smape: 1.7249

Epoch 6/128

144/144 - 2s - 14ms/step - ia: 0.0680 - loss: 0.9815 - mae: 0.8214 - rmse: 0.9897 - smape: 1.8784 - val_ia: 0.2328 - val_loss: 0.8086 - val_mae: 0.7428 - val_rmse: 0.8934 - val_smape: 1.6990

Epoch 7/128

144/144 - 2s - 13ms/step - ia: 0.0722 - loss: 0.9762 - mae: 0.8191 - rmse: 0.9875 - smape: 1.8642 - val_ia: 0.2361 - val_loss: 0.8001 - val_mae: 0.7379 - val_rmse: 0.8891 - val_smape: 1.6720

Epoch 8/128

144/144 - 2s - 14ms/step - ia: 0.0781 - loss: 0.9707 - mae: 0.8167 - rmse: 0.9847 - smape: 1.8485 - val_ia: 0.2393 - val_loss: 0.7912 - val_mae: 0.7326 - val_rmse: 0.8846 - val_smape: 1.6438

Epoch 9/128

144/144 - 2s - 14ms/step - ia: 0.0812 - loss: 0.9650 - mae: 0.8141 - rmse: 0.9819 - smape: 1.8331 - val_ia: 0.2425 - val_loss: 0.7815 - val_mae: 0.7268 - val_rmse: 0.8798 - val_smape: 1.6141

Epoch 10/128

144/144 - 2s - 15ms/step - ia: 0.0873 - loss: 0.9588 - mae: 0.8113 - rmse: 0.9788 - smape: 1.8167 - val_ia: 0.2456 - val_loss: 0.7713 - val_mae: 0.7207 - val_rmse: 0.8747 - val_smape: 1.5835

Epoch 11/128

144/144 - 2s - 14ms/step - ia: 0.0976 - loss: 0.9522 - mae: 0.8082 - rmse: 0.9754 - smape: 1.8002 - val_ia: 0.2492 - val_loss: 0.7604 - val_mae: 0.7143 - val_rmse: 0.8693 - val_smape: 1.5530

Epoch 12/128

144/144 - 2s - 14ms/step - ia: 0.1038 - loss: 0.9448 - mae: 0.8048 - rmse: 0.9714 - smape: 1.7825 - val_ia: 0.2540 - val_loss: 0.7488 - val_mae: 0.7075 - val_rmse: 0.8637 - val_smape: 1.5221

Epoch 13/128

144/144 - 2s - 14ms/step - ia: 0.1137 - loss: 0.9366 - mae: 0.8009 - rmse: 0.9673 - smape: 1.7642 - val_ia: 0.2606 - val_loss: 0.7368 - val_mae: 0.7006 - val_rmse: 0.8580 - val_smape: 1.4913

Epoch 14/128

144/144 - 2s - 13ms/step - ia: 0.1246 - loss: 0.9272 - mae: 0.7964 - rmse: 0.9623 - smape: 1.7444 - val_ia: 0.2697 - val_loss: 0.7250 - val_mae: 0.6943 - val_rmse: 0.8526 - val_smape: 1.4614

Epoch 15/128

144/144 - 2s - 13ms/step - ia: 0.1383 - loss: 0.9163 - mae: 0.7910 - rmse: 0.9564 - smape: 1.7230 - val_ia: 0.2817 - val_loss: 0.7153 - val_mae: 0.6902 - val_rmse: 0.8488 - val_smape: 1.4332

Epoch 16/128

144/144 - 2s - 14ms/step - ia: 0.1538 - loss: 0.9036 - mae: 0.7844 - rmse: 0.9497 - smape: 1.6993 - val_ia: 0.2961 - val_loss: 0.7116 - val_mae: 0.6898 - val_rmse: 0.8490 - val_smape: 1.4072

Epoch 17/128

144/144 - 2s - 14ms/step - ia: 0.1702 - loss: 0.8886 - mae: 0.7766 - rmse: 0.9417 - smape: 1.6735 - val_ia: 0.3115 - val_loss: 0.7225 - val_mae: 0.6962 - val_rmse: 0.8574 - val_smape: 1.3839

Epoch 18/128

144/144 - 2s - 14ms/step - ia: 0.1920 - loss: 0.8715 - mae: 0.7675 - rmse: 0.9326 - smape: 1.6461 - val_ia: 0.3271 - val_loss: 0.7629 - val_mae: 0.7115 - val_rmse: 0.8802 - val_smape: 1.3639

Epoch 19/128

144/144 - 2s - 14ms/step - ia: 0.2152 - loss: 0.8533 - mae: 0.7583 - rmse: 0.9233 - smape: 1.6190 - val_ia: 0.3404 - val_loss: 0.8476 - val_mae: 0.7366 - val_rmse: 0.9200 - val_smape: 1.3484

Epoch 20/128

144/144 - 2s - 14ms/step - ia: 0.2378 - loss: 0.8363 - mae: 0.7500 - rmse: 0.9141 - smape: 1.5948 - val_ia: 0.3517 - val_loss: 0.9652 - val_mae: 0.7642 - val_rmse: 0.9677 - val_smape: 1.3358

Epoch 21/128

144/144 - 2s - 14ms/step - ia: 0.2559 - loss: 0.8228 - mae: 0.7440 - rmse: 0.9057 - smape: 1.5755 - val_ia: 0.3605 - val_loss: 1.0397 - val_mae: 0.7787 - val_rmse: 0.9951 - val_smape: 1.3250

Epoch 22/128

144/144 - 2s - 14ms/step - ia: 0.2725 - loss: 0.8117 - mae: 0.7394 - rmse: 0.9003 - smape: 1.5589 - val_ia: 0.3685 - val_loss: 1.0948 - val_mae: 0.7881 - val_rmse: 1.0147 - val_smape: 1.3151

Epoch 23/128

144/144 - 2s - 14ms/step - ia: 0.2824 - loss: 0.8021 - mae: 0.7353 - rmse: 0.8951 - smape: 1.5453 - val_ia: 0.3758 - val_loss: 1.0957 - val_mae: 0.7860 - val_rmse: 1.0149 - val_smape: 1.3060

Epoch 24/128

144/144 - 2s - 14ms/step - ia: 0.2921 - loss: 0.7927 - mae: 0.7313 - rmse: 0.8894 - smape: 1.5326 - val_ia: 0.3831 - val_loss: 1.0853 - val_mae: 0.7818 - val_rmse: 1.0111 - val_smape: 1.2968

Epoch 25/128

144/144 - 2s - 14ms/step - ia: 0.3039 - loss: 0.7831 - mae: 0.7273 - rmse: 0.8841 - smape: 1.5192 - val_ia: 0.3903 - val_loss: 1.0549 - val_mae: 0.7732 - val_rmse: 0.9999 - val_smape: 1.2875

Epoch 26/128

144/144 - 2s - 15ms/step - ia: 0.3118 - loss: 0.7728 - mae: 0.7227 - rmse: 0.8785 - smape: 1.5063 - val_ia: 0.3978 - val_loss: 1.0159 - val_mae: 0.7627 - val_rmse: 0.9850 - val_smape: 1.2788

Epoch 27/128

144/144 - 2s - 16ms/step - ia: 0.3210 - loss: 0.7613 - mae: 0.7178 - rmse: 0.8717 - smape: 1.4917 - val_ia: 0.4054 - val_loss: 0.9763 - val_mae: 0.7515 - val_rmse: 0.9692 - val_smape: 1.2699

Epoch 28/128

144/144 - 2s - 17ms/step - ia: 0.3314 - loss: 0.7482 - mae: 0.7121 - rmse: 0.8645 - smape: 1.4746 - val_ia: 0.4134 - val_loss: 0.9328 - val_mae: 0.7391 - val_rmse: 0.9511 - val_smape: 1.2611

Epoch 29/128

144/144 - 2s - 14ms/step - ia: 0.3420 - loss: 0.7335 - mae: 0.7056 - rmse: 0.8557 - smape: 1.4544 - val_ia: 0.4216 - val_loss: 0.8870 - val_mae: 0.7255 - val_rmse: 0.9311 - val_smape: 1.2532

Epoch 30/128

144/144 - 2s - 13ms/step - ia: 0.3549 - loss: 0.7171 - mae: 0.6982 - rmse: 0.8460 - smape: 1.4323 - val_ia: 0.4303 - val_loss: 0.8347 - val_mae: 0.7100 - val_rmse: 0.9071 - val_smape: 1.2443

Epoch 31/128

144/144 - 2s - 16ms/step - ia: 0.3694 - loss: 0.6990 - mae: 0.6899 - rmse: 0.8356 - smape: 1.4085 - val_ia: 0.4396 - val_loss: 0.7872 - val_mae: 0.6949 - val_rmse: 0.8842 - val_smape: 1.2344

Epoch 31: early stopping

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:11 810ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/64

 80%|████████  | 40/50 [10:54:18<1:11:45, 430.54s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 26s - 23ms/step - ia: 0.9209 - loss: 0.0324 - mae: 0.1249 - rmse: 0.1634 - smape: 0.2984 - val_ia: 0.8655 - val_loss: 0.0066 - val_mae: 0.0595 - val_rmse: 0.0756 - val_smape: 0.1741

Epoch 2/64

1147/1147 - 19s - 17ms/step - ia: 0.9455 - loss: 0.0144 - mae: 0.0878 - rmse: 0.1171 - smape: 0.2180 - val_ia: 0.8541 - val_loss: 0.0076 - val_mae: 0.0643 - val_rmse: 0.0808 - val_smape: 0.1588

Epoch 3/64

1147/1147 - 18s - 16ms/step - ia: 0.9499 - loss: 0.0125 - mae: 0.0809 - rmse: 0.1085 - smape: 0.2023 - val_ia: 0.8580 - val_loss: 0.0060 - val_mae: 0.0590 - val_rmse: 0.0725 - val_smape: 0.1611

Epoch 4/64

1147/1147 - 17s - 14ms/step - ia: 0.9524 - loss: 0.0112 - mae: 0.0769 - rmse: 0.1033 - smape: 0.1924 - val_ia: 0.8541 - val_loss: 0.0066 - val_mae: 0.0611 - val_rmse: 0.0744 - val_smape: 0.1668

Epoch 5/64

1147/1147 - 18s - 16ms/step - ia: 0.9539 - loss: 0.0106 - mae: 0.0743 - rmse: 0.1001 - smape: 0.1867 - val_ia: 0.8874 - val_loss: 0.0040 - val_mae: 0.0468 - val_rmse: 0.0589 - val_smape: 0.1399

Epoch 6/64

1147/1147 - 18s - 16ms/step - ia: 0.9545 - loss: 0.0105 - mae: 0.0736 - rmse: 0.0996 - smape: 0.1838 - val_ia: 0.8280 - val_loss: 0.0084 - val_mae: 0.0728 - val_rmse: 0.0847 - val_smape: 0.1706

Epoch 7/64

1147/1147 - 18s - 16ms/step - ia: 0.9548 - loss: 0.0104 - mae: 0.0732 - rmse: 0.0991 - smape: 0.1814 - val_ia: 0.8489 - val_loss: 0.0066 - val_mae: 0.0621 - val_rmse: 0.0752 - val_smape: 0.1557

Epoch 8/64

1147/1147 - 18s - 16ms/step - ia: 0.9565 - loss: 0.0095 - mae: 0.0704 - rmse: 0.0949 - smape: 0.1766 - val_ia: 0.8452 - val_loss: 0.0062 - val_mae: 0.0627 - val_rmse: 0.0749 - val_smape: 0.1626

Epoch 9/64

1147/1147 - 16s - 14ms/step - ia: 0.9561 - loss: 0.0098 - mae: 0.0710 - rmse: 0.0962 - smape: 0.1780 - val_ia: 0.8832 - val_loss: 0.0041 - val_mae: 0.0492 - val_rmse: 0.0612 - val_smape: 0.1373

Epoch 10/64

1147/1147 - 18s - 16ms/step - ia: 0.9572 - loss: 0.0093 - mae: 0.0691 - rmse: 0.0936 - smape: 0.1722 - val_ia: 0.9107 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0521 - val_smape: 0.1312

Epoch 11/64

1147/1147 - 18s - 16ms/step - ia: 0.9572 - loss: 0.0093 - mae: 0.0692 - rmse: 0.0935 - smape: 0.1721 - val_ia: 0.8509 - val_loss: 0.0061 - val_mae: 0.0585 - val_rmse: 0.0704 - val_smape: 0.1474

Epoch 12/64

1147/1147 - 18s - 16ms/step - ia: 0.9583 - loss: 0.0088 - mae: 0.0674 - rmse: 0.0915 - smape: 0.1703 - val_ia: 0.8948 - val_loss: 0.0041 - val_mae: 0.0479 - val_rmse: 0.0608 - val_smape: 0.1430

Epoch 13/64

1147/1147 - 19s - 16ms/step - ia: 0.9579 - loss: 0.0090 - mae: 0.0680 - rmse: 0.0922 - smape: 0.1704 - val_ia: 0.9009 - val_loss: 0.0035 - val_mae: 0.0438 - val_rmse: 0.0557 - val_smape: 0.1229

Epoch 14/64

1147/1147 - 18s - 16ms/step - ia: 0.9578 - loss: 0.0091 - mae: 0.0683 - rmse: 0.0928 - smape: 0.1715 - val_ia: 0.8781 - val_loss: 0.0065 - val_mae: 0.0617 - val_rmse: 0.0745 - val_smape: 0.1657

Epoch 15/64

1147/1147 - 19s - 16ms/step - ia: 0.9584 - loss: 0.0088 - mae: 0.0672 - rmse: 0.0912 - smape: 0.1688 - val_ia: 0.9048 - val_loss: 0.0029 - val_mae: 0.0396 - val_rmse: 0.0510 - val_smape: 0.1218

Epoch 16/64

1147/1147 - 18s - 16ms/step - ia: 0.9586 - loss: 0.0087 - mae: 0.0670 - rmse: 0.0907 - smape: 0.1688 - val_ia: 0.9055 - val_loss: 0.0031 - val_mae: 0.0410 - val_rmse: 0.0528 - val_smape: 0.1327

Epoch 17/64

1147/1147 - 20s - 17ms/step - ia: 0.9589 - loss: 0.0086 - mae: 0.0665 - rmse: 0.0900 - smape: 0.1669 - val_ia: 0.8861 - val_loss: 0.0049 - val_mae: 0.0520 - val_rmse: 0.0658 - val_smape: 0.1523

Epoch 18/64

1147/1147 - 19s - 16ms/step - ia: 0.9587 - loss: 0.0088 - mae: 0.0668 - rmse: 0.0910 - smape: 0.1679 - val_ia: 0.8878 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0569 - val_smape: 0.1309

Epoch 19/64

1147/1147 - 18s - 16ms/step - ia: 0.9588 - loss: 0.0087 - mae: 0.0665 - rmse: 0.0906 - smape: 0.1667 - val_ia: 0.8902 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0561 - val_smape: 0.1306

Epoch 20/64

1147/1147 - 18s - 16ms/step - ia: 0.9591 - loss: 0.0085 - mae: 0.0661 - rmse: 0.0896 - smape: 0.1660 - val_ia: 0.8989 - val_loss: 0.0032 - val_mae: 0.0419 - val_rmse: 0.0540 - val_smape: 0.1355

Epoch 21/64

1147/1147 - 18s - 16ms/step - ia: 0.9592 - loss: 0.0085 - mae: 0.0659 - rmse: 0.0896 - smape: 0.1646 - val_ia: 0.8986 - val_loss: 0.0033 - val_mae: 0.0419 - val_rmse: 0.0538 - val_smape: 0.1350

Epoch 22/64

1147/1147 - 19s - 16ms/step - ia: 0.9594 - loss: 0.0083 - mae: 0.0655 - rmse: 0.0887 - smape: 0.1655 - val_ia: 0.8884 - val_loss: 0.0035 - val_mae: 0.0436 - val_rmse: 0.0552 - val_smape: 0.1220

Epoch 23/64

1147/1147 - 18s - 16ms/step - ia: 0.9592 - loss: 0.0085 - mae: 0.0658 - rmse: 0.0893 - smape: 0.1652 - val_ia: 0.9156 - val_loss: 0.0026 - val_mae: 0.0356 - val_rmse: 0.0475 - val_smape: 0.1150

Epoch 24/64

1147/1147 - 18s - 16ms/step - ia: 0.9596 - loss: 0.0083 - mae: 0.0653 - rmse: 0.0886 - smape: 0.1635 - val_ia: 0.8973 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0532 - val_smape: 0.1201

Epoch 25/64

1147/1147 - 19s - 16ms/step - ia: 0.9597 - loss: 0.0083 - mae: 0.0651 - rmse: 0.0883 - smape: 0.1638 - val_ia: 0.8764 - val_loss: 0.0044 - val_mae: 0.0524 - val_rmse: 0.0636 - val_smape: 0.1370

Epoch 26/64

1147/1147 - 18s - 16ms/step - ia: 0.9597 - loss: 0.0084 - mae: 0.0652 - rmse: 0.0887 - smape: 0.1619 - val_ia: 0.8887 - val_loss: 0.0035 - val_mae: 0.0446 - val_rmse: 0.0566 - val_smape: 0.1391

Epoch 27/64

1147/1147 - 19s - 17ms/step - ia: 0.9600 - loss: 0.0081 - mae: 0.0646 - rmse: 0.0875 - smape: 0.1634 - val_ia: 0.8986 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0577 - val_smape: 0.1291

Epoch 28/64

1147/1147 - 18s - 16ms/step - ia: 0.9601 - loss: 0.0082 - mae: 0.0644 - rmse: 0.0877 - smape: 0.1634 - val_ia: 0.8932 - val_loss: 0.0035 - val_mae: 0.0447 - val_rmse: 0.0564 - val_smape: 0.1346

Epoch 29/64

1147/1147 - 19s - 16ms/step - ia: 0.9600 - loss: 0.0083 - mae: 0.0647 - rmse: 0.0884 - smape: 0.1630 - val_ia: 0.9028 - val_loss: 0.0030 - val_mae: 0.0399 - val_rmse: 0.0517 - val_smape: 0.1264

Epoch 30/64

1147/1147 - 18s - 16ms/step - ia: 0.9602 - loss: 0.0082 - mae: 0.0644 - rmse: 0.0877 - smape: 0.1622 - val_ia: 0.9064 - val_loss: 0.0029 - val_mae: 0.0392 - val_rmse: 0.0509 - val_smape: 0.1286

Epoch 31/64

1147/1147 - 18s - 16ms/step - ia: 0.9603 - loss: 0.0081 - mae: 0.0642 - rmse: 0.0871 - smape: 0.1636 - val_ia: 0.9073 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0516 - val_smape: 0.1250

Epoch 32/64

1147/1147 - 19s - 16ms/step - ia: 0.9601 - loss: 0.0082 - mae: 0.0645 - rmse: 0.0876 - smape: 0.1626 - val_ia: 0.9012 - val_loss: 0.0031 - val_mae: 0.0412 - val_rmse: 0.0527 - val_smape: 0.1317

Epoch 33/64

1147/1147 - 18s - 16ms/step - ia: 0.9602 - loss: 0.0081 - mae: 0.0644 - rmse: 0.0874 - smape: 0.1612 - val_ia: 0.9100 - val_loss: 0.0028 - val_mae: 0.0379 - val_rmse: 0.0496 - val_smape: 0.1267

Epoch 34/64

1147/1147 - 18s - 16ms/step - ia: 0.9606 - loss: 0.0080 - mae: 0.0638 - rmse: 0.0869 - smape: 0.1605 - val_ia: 0.9080 - val_loss: 0.0030 - val_mae: 0.0395 - val_rmse: 0.0515 - val_smape: 0.1275

Epoch 35/64

1147/1147 - 19s - 17ms/step - ia: 0.9603 - loss: 0.0081 - mae: 0.0643 - rmse: 0.0872 - smape: 0.1617 - val_ia: 0.9030 - val_loss: 0.0032 - val_mae: 0.0411 - val_rmse: 0.0527 - val_smape: 0.1274

Epoch 36/64

1147/1147 - 19s - 17ms/step - ia: 0.9606 - loss: 0.0080 - mae: 0.0638 - rmse: 0.0866 - smape: 0.1622 - val_ia: 0.9092 - val_loss: 0.0029 - val_mae: 0.0378 - val_rmse: 0.0500 - val_smape: 0.1216

Epoch 37/64

1147/1147 - 18s - 16ms/step - ia: 0.9608 - loss: 0.0079 - mae: 0.0633 - rmse: 0.0861 - smape: 0.1592 - val_ia: 0.8249 - val_loss: 0.0076 - val_mae: 0.0710 - val_rmse: 0.0816 - val_smape: 0.1915

Epoch 38/64

1147/1147 - 18s - 16ms/step - ia: 0.9606 - loss: 0.0080 - mae: 0.0638 - rmse: 0.0866 - smape: 0.1604 - val_ia: 0.9083 - val_loss: 0.0030 - val_mae: 0.0392 - val_rmse: 0.0512 - val_smape: 0.1300

Epoch 38: early stopping

Restoring model weights from the end of the best epoch: 23.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:13 456ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 82%|████████▏ | 41/50 [11:06:02<1:16:54, 512.68s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

144/144 - 16s - 109ms/step - ia: 0.4484 - loss: 0.5574 - mae: 0.5818 - rmse: 0.7144 - smape: 1.2460 - val_ia: 0.7135 - val_loss: 0.2752 - val_mae: 0.4114 - val_rmse: 0.5168 - val_smape: 0.7756

Epoch 2/32

144/144 - 7s - 49ms/step - ia: 0.8182 - loss: 0.1448 - mae: 0.2864 - rmse: 0.3770 - smape: 0.6015 - val_ia: 0.8066 - val_loss: 0.1135 - val_mae: 0.2624 - val_rmse: 0.3246 - val_smape: 0.6177

Epoch 3/32

144/144 - 8s - 52ms/step - ia: 0.8620 - loss: 0.0862 - mae: 0.2234 - rmse: 0.2924 - smape: 0.5029 - val_ia: 0.8585 - val_loss: 0.0597 - val_mae: 0.1887 - val_rmse: 0.2369 - val_smape: 0.4955

Epoch 4/32

144/144 - 8s - 52ms/step - ia: 0.8862 - loss: 0.0592 - mae: 0.1850 - rmse: 0.2424 - smape: 0.4453 - val_ia: 0.8918 - val_loss: 0.0359 - val_mae: 0.1439 - val_rmse: 0.1838 - val_smape: 0.3908

Epoch 5/32

144/144 - 8s - 52ms/step - ia: 0.9003 - loss: 0.0463 - mae: 0.1626 - rmse: 0.2146 - smape: 0.3993 - val_ia: 0.9074 - val_loss: 0.0258 - val_mae: 0.1200 - val_rmse: 0.1595 - val_smape: 0.3309

Epoch 6/32

144/144 - 7s - 51ms/step - ia: 0.9084 - loss: 0.0396 - mae: 0.1499 - rmse: 0.1985 - smape: 0.3697 - val_ia: 0.9044 - val_loss: 0.0270 - val_mae: 0.1233 - val_rmse: 0.1620 - val_smape: 0.3335

Epoch 7/32

144/144 - 8s - 53ms/step - ia: 0.9131 - loss: 0.0360 - mae: 0.1425 - rmse: 0.1891 - smape: 0.3531 - val_ia: 0.9144 - val_loss: 0.0223 - val_mae: 0.1091 - val_rmse: 0.1481 - val_smape: 0.2840

Epoch 8/32

144/144 - 6s - 45ms/step - ia: 0.9172 - loss: 0.0328 - mae: 0.1356 - rmse: 0.1807 - smape: 0.3403 - val_ia: 0.9106 - val_loss: 0.0233 - val_mae: 0.1126 - val_rmse: 0.1506 - val_smape: 0.2825

Epoch 9/32

144/144 - 6s - 43ms/step - ia: 0.9205 - loss: 0.0305 - mae: 0.1307 - rmse: 0.1741 - smape: 0.3275 - val_ia: 0.9152 - val_loss: 0.0209 - val_mae: 0.1061 - val_rmse: 0.1451 - val_smape: 0.2628

Epoch 10/32

144/144 - 6s - 43ms/step - ia: 0.9219 - loss: 0.0294 - mae: 0.1284 - rmse: 0.1711 - smape: 0.3262 - val_ia: 0.9150 - val_loss: 0.0213 - val_mae: 0.1076 - val_rmse: 0.1441 - val_smape: 0.2767

Epoch 11/32

144/144 - 6s - 44ms/step - ia: 0.9242 - loss: 0.0279 - mae: 0.1248 - rmse: 0.1666 - smape: 0.3164 - val_ia: 0.9163 - val_loss: 0.0212 - val_mae: 0.1062 - val_rmse: 0.1436 - val_smape: 0.2675

Epoch 12/32

144/144 - 6s - 44ms/step - ia: 0.9264 - loss: 0.0261 - mae: 0.1210 - rmse: 0.1609 - smape: 0.3104 - val_ia: 0.9159 - val_loss: 0.0215 - val_mae: 0.1065 - val_rmse: 0.1430 - val_smape: 0.2596

Epoch 13/32

144/144 - 6s - 42ms/step - ia: 0.9278 - loss: 0.0253 - mae: 0.1187 - rmse: 0.1585 - smape: 0.3039 - val_ia: 0.9143 - val_loss: 0.0210 - val_mae: 0.1071 - val_rmse: 0.1435 - val_smape: 0.2490

Epoch 14/32

144/144 - 8s - 52ms/step - ia: 0.9291 - loss: 0.0245 - mae: 0.1166 - rmse: 0.1561 - smape: 0.2993 - val_ia: 0.9181 - val_loss: 0.0196 - val_mae: 0.1028 - val_rmse: 0.1385 - val_smape: 0.2425

Epoch 15/32

144/144 - 8s - 53ms/step - ia: 0.9310 - loss: 0.0232 - mae: 0.1138 - rmse: 0.1519 - smape: 0.2936 - val_ia: 0.9239 - val_loss: 0.0176 - val_mae: 0.0956 - val_rmse: 0.1301 - val_smape: 0.2250

Epoch 16/32

144/144 - 8s - 53ms/step - ia: 0.9319 - loss: 0.0225 - mae: 0.1121 - rmse: 0.1494 - smape: 0.2912 - val_ia: 0.9283 - val_loss: 0.0156 - val_mae: 0.0906 - val_rmse: 0.1243 - val_smape: 0.2191

Epoch 17/32

144/144 - 7s - 51ms/step - ia: 0.9335 - loss: 0.0217 - mae: 0.1096 - rmse: 0.1468 - smape: 0.2852 - val_ia: 0.9293 - val_loss: 0.0156 - val_mae: 0.0895 - val_rmse: 0.1226 - val_smape: 0.2142

Epoch 18/32

144/144 - 8s - 52ms/step - ia: 0.9338 - loss: 0.0214 - mae: 0.1091 - rmse: 0.1457 - smape: 0.2831 - val_ia: 0.9290 - val_loss: 0.0155 - val_mae: 0.0901 - val_rmse: 0.1216 - val_smape: 0.2221

Epoch 19/32

144/144 - 7s - 52ms/step - ia: 0.9356 - loss: 0.0203 - mae: 0.1059 - rmse: 0.1422 - smape: 0.2781 - val_ia: 0.9284 - val_loss: 0.0151 - val_mae: 0.0904 - val_rmse: 0.1217 - val_smape: 0.2138

Epoch 20/32

144/144 - 7s - 51ms/step - ia: 0.9367 - loss: 0.0197 - mae: 0.1044 - rmse: 0.1399 - smape: 0.2728 - val_ia: 0.9354 - val_loss: 0.0131 - val_mae: 0.0827 - val_rmse: 0.1132 - val_smape: 0.2037

Epoch 21/32

144/144 - 7s - 52ms/step - ia: 0.9378 - loss: 0.0190 - mae: 0.1025 - rmse: 0.1372 - smape: 0.2695 - val_ia: 0.9329 - val_loss: 0.0135 - val_mae: 0.0850 - val_rmse: 0.1142 - val_smape: 0.2081

Epoch 22/32

144/144 - 8s - 53ms/step - ia: 0.9386 - loss: 0.0185 - mae: 0.1012 - rmse: 0.1356 - smape: 0.2665 - val_ia: 0.9328 - val_loss: 0.0134 - val_mae: 0.0853 - val_rmse: 0.1138 - val_smape: 0.2075

Epoch 23/32

144/144 - 8s - 52ms/step - ia: 0.9392 - loss: 0.0183 - mae: 0.1002 - rmse: 0.1348 - smape: 0.2618 - val_ia: 0.9335 - val_loss: 0.0137 - val_mae: 0.0850 - val_rmse: 0.1130 - val_smape: 0.2044

Epoch 24/32

144/144 - 7s - 50ms/step - ia: 0.9402 - loss: 0.0175 - mae: 0.0986 - rmse: 0.1319 - smape: 0.2593 - val_ia: 0.9282 - val_loss: 0.0148 - val_mae: 0.0911 - val_rmse: 0.1179 - val_smape: 0.2152

Epoch 25/32

144/144 - 7s - 52ms/step - ia: 0.9407 - loss: 0.0174 - mae: 0.0976 - rmse: 0.1313 - smape: 0.2553 - val_ia: 0.9304 - val_loss: 0.0140 - val_mae: 0.0887 - val_rmse: 0.1157 - val_smape: 0.2092

Epoch 26/32

144/144 - 8s - 54ms/step - ia: 0.9415 - loss: 0.0170 - mae: 0.0964 - rmse: 0.1295 - smape: 0.2543 - val_ia: 0.9360 - val_loss: 0.0121 - val_mae: 0.0820 - val_rmse: 0.1078 - val_smape: 0.2018

Epoch 27/32

144/144 - 9s - 60ms/step - ia: 0.9423 - loss: 0.0165 - mae: 0.0950 - rmse: 0.1279 - smape: 0.2502 - val_ia: 0.9341 - val_loss: 0.0127 - val_mae: 0.0845 - val_rmse: 0.1100 - val_smape: 0.2070

Epoch 28/32

144/144 - 8s - 56ms/step - ia: 0.9427 - loss: 0.0163 - mae: 0.0944 - rmse: 0.1268 - smape: 0.2490 - val_ia: 0.9337 - val_loss: 0.0133 - val_mae: 0.0860 - val_rmse: 0.1112 - val_smape: 0.2157

Epoch 29/32

144/144 - 8s - 56ms/step - ia: 0.9431 - loss: 0.0160 - mae: 0.0938 - rmse: 0.1259 - smape: 0.2499 - val_ia: 0.9336 - val_loss: 0.0134 - val_mae: 0.0865 - val_rmse: 0.1115 - val_smape: 0.2110

Epoch 30/32

144/144 - 8s - 53ms/step - ia: 0.9436 - loss: 0.0159 - mae: 0.0928 - rmse: 0.1255 - smape: 0.2448 - val_ia: 0.9327 - val_loss: 0.0139 - val_mae: 0.0872 - val_rmse: 0.1110 - val_smape: 0.2292

Epoch 31/32

144/144 - 7s - 52ms/step - ia: 0.9439 - loss: 0.0157 - mae: 0.0925 - rmse: 0.1247 - smape: 0.2455 - val_ia: 0.9369 - val_loss: 0.0122 - val_mae: 0.0817 - val_rmse: 0.1058 - val_smape: 0.2102

Epoch 32/32

144/144 - 8s - 53ms/step - ia: 0.9449 - loss: 0.0152 - mae: 0.0908 - rmse: 0.1225 - smape: 0.2425 - val_ia: 0.9408 - val_loss: 0.0107 - val_mae: 0.0767 - val_rmse: 0.1011 - val_smape: 0.1972

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:56 721ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 84%|████████▍ | 42/50 [11:10:08<57:41, 432.67s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

574/574 - 21s - 36ms/step - ia: 0.8527 - loss: 0.1023 - mae: 0.2290 - rmse: 0.2975 - smape: 0.5002 - val_ia: 0.8483 - val_loss: 0.0378 - val_mae: 0.1485 - val_rmse: 0.1836 - val_smape: 0.4308

Epoch 2/8

574/574 - 9s - 16ms/step - ia: 0.9176 - loss: 0.0321 - mae: 0.1339 - rmse: 0.1774 - smape: 0.3182 - val_ia: 0.9034 - val_loss: 0.0163 - val_mae: 0.0933 - val_rmse: 0.1205 - val_smape: 0.2627

Epoch 3/8

574/574 - 9s - 16ms/step - ia: 0.9307 - loss: 0.0230 - mae: 0.1127 - rmse: 0.1502 - smape: 0.2711 - val_ia: 0.9190 - val_loss: 0.0110 - val_mae: 0.0775 - val_rmse: 0.0977 - val_smape: 0.2335

Epoch 4/8

574/574 - 11s - 18ms/step - ia: 0.9365 - loss: 0.0198 - mae: 0.1036 - rmse: 0.1391 - smape: 0.2453 - val_ia: 0.9371 - val_loss: 0.0070 - val_mae: 0.0612 - val_rmse: 0.0804 - val_smape: 0.1739

Epoch 5/8

574/574 - 10s - 17ms/step - ia: 0.9410 - loss: 0.0174 - mae: 0.0962 - rmse: 0.1300 - smape: 0.2288 - val_ia: 0.9425 - val_loss: 0.0062 - val_mae: 0.0569 - val_rmse: 0.0756 - val_smape: 0.1739

Epoch 6/8

574/574 - 10s - 18ms/step - ia: 0.9436 - loss: 0.0160 - mae: 0.0921 - rmse: 0.1249 - smape: 0.2196 - val_ia: 0.9370 - val_loss: 0.0065 - val_mae: 0.0594 - val_rmse: 0.0754 - val_smape: 0.1810

Epoch 7/8

574/574 - 11s - 19ms/step - ia: 0.9442 - loss: 0.0158 - mae: 0.0912 - rmse: 0.1240 - smape: 0.2179 - val_ia: 0.9463 - val_loss: 0.0060 - val_mae: 0.0546 - val_rmse: 0.0740 - val_smape: 0.1509

Epoch 8/8

574/574 - 10s - 17ms/step - ia: 0.9457 - loss: 0.0149 - mae: 0.0887 - rmse: 0.1206 - smape: 0.2117 - val_ia: 0.9305 - val_loss: 0.0072 - val_mae: 0.0648 - val_rmse: 0.0823 - val_smape: 0.1487

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:56 718ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 86%|████████▌ | 43/50 [11:11:42<38:35, 330.82s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4586/4586 - 80s - 18ms/step - ia: 0.2387 - loss: 1.0886 - mae: 0.8619 - rmse: 1.0198 - smape: 1.5864 - val_ia: 0.1402 - val_loss: 0.8430 - val_mae: 0.7640 - val_rmse: 0.7814 - val_smape: 1.9285

Epoch 2/128

4586/4586 - 71s - 15ms/step - ia: 0.2604 - loss: 0.9667 - mae: 0.8137 - rmse: 0.9622 - smape: 1.5587 - val_ia: 0.1509 - val_loss: 0.6952 - val_mae: 0.6926 - val_rmse: 0.7091 - val_smape: 1.5845

Epoch 3/128

4586/4586 - 66s - 14ms/step - ia: 0.5210 - loss: 0.4980 - mae: 0.5658 - rmse: 0.6755 - smape: 1.0729 - val_ia: 0.2316 - val_loss: 0.2164 - val_mae: 0.3641 - val_rmse: 0.3817 - val_smape: 0.7240

Epoch 4/128

4586/4586 - 70s - 15ms/step - ia: 0.7220 - loss: 0.2465 - mae: 0.3953 - rmse: 0.4811 - smape: 0.7460 - val_ia: 0.2297 - val_loss: 0.2093 - val_mae: 0.3592 - val_rmse: 0.3766 - val_smape: 0.7083

Epoch 5/128

4586/4586 - 71s - 15ms/step - ia: 0.7404 - loss: 0.2204 - mae: 0.3726 - rmse: 0.4543 - smape: 0.7170 - val_ia: 0.2331 - val_loss: 0.1949 - val_mae: 0.3477 - val_rmse: 0.3652 - val_smape: 0.6940

Epoch 6/128

4586/4586 - 71s - 15ms/step - ia: 0.7547 - loss: 0.1976 - mae: 0.3511 - rmse: 0.4299 - smape: 0.6859 - val_ia: 0.2412 - val_loss: 0.1816 - val_mae: 0.3358 - val_rmse: 0.3533 - val_smape: 0.6801

Epoch 7/128

4586/4586 - 75s - 16ms/step - ia: 0.7694 - loss: 0.1777 - mae: 0.3313 - rmse: 0.4066 - smape: 0.6596 - val_ia: 0.2501 - val_loss: 0.1703 - val_mae: 0.3246 - val_rmse: 0.3416 - val_smape: 0.6668

Epoch 8/128

4586/4586 - 79s - 17ms/step - ia: 0.7793 - loss: 0.1637 - mae: 0.3185 - rmse: 0.3908 - smape: 0.6398 - val_ia: 0.2569 - val_loss: 0.1632 - val_mae: 0.3167 - val_rmse: 0.3331 - val_smape: 0.6575

Epoch 9/128

4586/4586 - 72s - 16ms/step - ia: 0.7885 - loss: 0.1518 - mae: 0.3052 - rmse: 0.3756 - smape: 0.6217 - val_ia: 0.2620 - val_loss: 0.1523 - val_mae: 0.3066 - val_rmse: 0.3226 - val_smape: 0.6444

Epoch 10/128

4586/4586 - 75s - 16ms/step - ia: 0.7985 - loss: 0.1378 - mae: 0.2899 - rmse: 0.3575 - smape: 0.5998 - val_ia: 0.2633 - val_loss: 0.1525 - val_mae: 0.3056 - val_rmse: 0.3208 - val_smape: 0.6424

Epoch 11/128

4586/4586 - 74s - 16ms/step - ia: 0.8064 - loss: 0.1287 - mae: 0.2799 - rmse: 0.3458 - smape: 0.5813 - val_ia: 0.2709 - val_loss: 0.1402 - val_mae: 0.2936 - val_rmse: 0.3083 - val_smape: 0.6282

Epoch 12/128

4586/4586 - 73s - 16ms/step - ia: 0.8135 - loss: 0.1186 - mae: 0.2688 - rmse: 0.3319 - smape: 0.5669 - val_ia: 0.2777 - val_loss: 0.1305 - val_mae: 0.2835 - val_rmse: 0.2979 - val_smape: 0.6153

Epoch 13/128

4586/4586 - 85s - 19ms/step - ia: 0.8199 - loss: 0.1115 - mae: 0.2605 - rmse: 0.3217 - smape: 0.5567 - val_ia: 0.2844 - val_loss: 0.1218 - val_mae: 0.2741 - val_rmse: 0.2881 - val_smape: 0.6032

Epoch 14/128

4586/4586 - 83s - 18ms/step - ia: 0.8264 - loss: 0.1030 - mae: 0.2509 - rmse: 0.3093 - smape: 0.5411 - val_ia: 0.2927 - val_loss: 0.1148 - val_mae: 0.2659 - val_rmse: 0.2796 - val_smape: 0.5927

Epoch 15/128

4586/4586 - 60s - 13ms/step - ia: 0.8315 - loss: 0.0977 - mae: 0.2443 - rmse: 0.3006 - smape: 0.5318 - val_ia: 0.2999 - val_loss: 0.1099 - val_mae: 0.2599 - val_rmse: 0.2733 - val_smape: 0.5838

Epoch 16/128

4586/4586 - 59s - 13ms/step - ia: 0.8368 - loss: 0.0917 - mae: 0.2360 - rmse: 0.2912 - smape: 0.5190 - val_ia: 0.3098 - val_loss: 0.0969 - val_mae: 0.2449 - val_rmse: 0.2580 - val_smape: 0.5650

Epoch 17/128

4586/4586 - 58s - 13ms/step - ia: 0.8414 - loss: 0.0870 - mae: 0.2299 - rmse: 0.2836 - smape: 0.5064 - val_ia: 0.3152 - val_loss: 0.0981 - val_mae: 0.2457 - val_rmse: 0.2585 - val_smape: 0.5632

Epoch 18/128

4586/4586 - 58s - 13ms/step - ia: 0.8458 - loss: 0.0826 - mae: 0.2237 - rmse: 0.2765 - smape: 0.4975 - val_ia: 0.3229 - val_loss: 0.0928 - val_mae: 0.2388 - val_rmse: 0.2514 - val_smape: 0.5532

Epoch 19/128

4586/4586 - 58s - 13ms/step - ia: 0.8512 - loss: 0.0769 - mae: 0.2150 - rmse: 0.2665 - smape: 0.4814 - val_ia: 0.3327 - val_loss: 0.0858 - val_mae: 0.2300 - val_rmse: 0.2424 - val_smape: 0.5403

Epoch 20/128

4586/4586 - 58s - 13ms/step - ia: 0.8534 - loss: 0.0740 - mae: 0.2118 - rmse: 0.2615 - smape: 0.4776 - val_ia: 0.3419 - val_loss: 0.0780 - val_mae: 0.2195 - val_rmse: 0.2317 - val_smape: 0.5246

Epoch 21/128

4586/4586 - 58s - 13ms/step - ia: 0.8582 - loss: 0.0703 - mae: 0.2062 - rmse: 0.2548 - smape: 0.4667 - val_ia: 0.3513 - val_loss: 0.0736 - val_mae: 0.2132 - val_rmse: 0.2254 - val_smape: 0.5148

Epoch 22/128

4586/4586 - 58s - 13ms/step - ia: 0.8615 - loss: 0.0664 - mae: 0.1998 - rmse: 0.2473 - smape: 0.4567 - val_ia: 0.3586 - val_loss: 0.0689 - val_mae: 0.2063 - val_rmse: 0.2185 - val_smape: 0.5045

Epoch 23/128

4586/4586 - 58s - 13ms/step - ia: 0.8662 - loss: 0.0627 - mae: 0.1950 - rmse: 0.2405 - smape: 0.4492 - val_ia: 0.3685 - val_loss: 0.0626 - val_mae: 0.1970 - val_rmse: 0.2091 - val_smape: 0.4902

Epoch 24/128

4586/4586 - 58s - 13ms/step - ia: 0.8679 - loss: 0.0602 - mae: 0.1903 - rmse: 0.2356 - smape: 0.4399 - val_ia: 0.3761 - val_loss: 0.0603 - val_mae: 0.1940 - val_rmse: 0.2061 - val_smape: 0.4855

Epoch 25/128

4586/4586 - 58s - 13ms/step - ia: 0.8723 - loss: 0.0570 - mae: 0.1854 - rmse: 0.2290 - smape: 0.4327 - val_ia: 0.3804 - val_loss: 0.0579 - val_mae: 0.1910 - val_rmse: 0.2031 - val_smape: 0.4817

Epoch 26/128

4586/4586 - 59s - 13ms/step - ia: 0.8759 - loss: 0.0543 - mae: 0.1803 - rmse: 0.2234 - smape: 0.4221 - val_ia: 0.3971 - val_loss: 0.0465 - val_mae: 0.1705 - val_rmse: 0.1825 - val_smape: 0.4458

Epoch 27/128

4586/4586 - 58s - 13ms/step - ia: 0.8782 - loss: 0.0523 - mae: 0.1772 - rmse: 0.2190 - smape: 0.4151 - val_ia: 0.3971 - val_loss: 0.0471 - val_mae: 0.1730 - val_rmse: 0.1850 - val_smape: 0.4521

Epoch 28/128

4586/4586 - 58s - 13ms/step - ia: 0.8801 - loss: 0.0503 - mae: 0.1737 - rmse: 0.2149 - smape: 0.4120 - val_ia: 0.4115 - val_loss: 0.0401 - val_mae: 0.1589 - val_rmse: 0.1709 - val_smape: 0.4258

Epoch 29/128

4586/4586 - 58s - 13ms/step - ia: 0.8829 - loss: 0.0478 - mae: 0.1688 - rmse: 0.2091 - smape: 0.4040 - val_ia: 0.4165 - val_loss: 0.0377 - val_mae: 0.1545 - val_rmse: 0.1665 - val_smape: 0.4190

Epoch 30/128

4586/4586 - 58s - 13ms/step - ia: 0.8870 - loss: 0.0461 - mae: 0.1657 - rmse: 0.2056 - smape: 0.3956 - val_ia: 0.4335 - val_loss: 0.0307 - val_mae: 0.1379 - val_rmse: 0.1500 - val_smape: 0.3838

Epoch 31/128

4586/4586 - 58s - 13ms/step - ia: 0.8872 - loss: 0.0449 - mae: 0.1638 - rmse: 0.2028 - smape: 0.3912 - val_ia: 0.4448 - val_loss: 0.0273 - val_mae: 0.1293 - val_rmse: 0.1416 - val_smape: 0.3625

Epoch 32/128

4586/4586 - 58s - 13ms/step - ia: 0.8892 - loss: 0.0432 - mae: 0.1606 - rmse: 0.1991 - smape: 0.3860 - val_ia: 0.4429 - val_loss: 0.0285 - val_mae: 0.1330 - val_rmse: 0.1453 - val_smape: 0.3747

Epoch 33/128

4586/4586 - 59s - 13ms/step - ia: 0.8902 - loss: 0.0425 - mae: 0.1586 - rmse: 0.1971 - smape: 0.3831 - val_ia: 0.4585 - val_loss: 0.0246 - val_mae: 0.1219 - val_rmse: 0.1344 - val_smape: 0.3452

Epoch 34/128

4586/4586 - 58s - 13ms/step - ia: 0.8925 - loss: 0.0408 - mae: 0.1560 - rmse: 0.1933 - smape: 0.3763 - val_ia: 0.4648 - val_loss: 0.0226 - val_mae: 0.1160 - val_rmse: 0.1287 - val_smape: 0.3309

Epoch 35/128

4586/4586 - 58s - 13ms/step - ia: 0.8943 - loss: 0.0399 - mae: 0.1533 - rmse: 0.1908 - smape: 0.3715 - val_ia: 0.4570 - val_loss: 0.0243 - val_mae: 0.1220 - val_rmse: 0.1346 - val_smape: 0.3517

Epoch 36/128

4586/4586 - 62s - 14ms/step - ia: 0.8959 - loss: 0.0390 - mae: 0.1515 - rmse: 0.1887 - smape: 0.3678 - val_ia: 0.4714 - val_loss: 0.0219 - val_mae: 0.1141 - val_rmse: 0.1269 - val_smape: 0.3275

Epoch 37/128

4586/4586 - 60s - 13ms/step - ia: 0.8971 - loss: 0.0381 - mae: 0.1498 - rmse: 0.1863 - smape: 0.3648 - val_ia: 0.4690 - val_loss: 0.0221 - val_mae: 0.1152 - val_rmse: 0.1280 - val_smape: 0.3359

Epoch 38/128

4586/4586 - 59s - 13ms/step - ia: 0.8974 - loss: 0.0376 - mae: 0.1491 - rmse: 0.1852 - smape: 0.3628 - val_ia: 0.4809 - val_loss: 0.0201 - val_mae: 0.1082 - val_rmse: 0.1212 - val_smape: 0.3155

Epoch 39/128

4586/4586 - 58s - 13ms/step - ia: 0.8984 - loss: 0.0366 - mae: 0.1467 - rmse: 0.1826 - smape: 0.3588 - val_ia: 0.4777 - val_loss: 0.0209 - val_mae: 0.1110 - val_rmse: 0.1239 - val_smape: 0.3248

Epoch 40/128

4586/4586 - 58s - 13ms/step - ia: 0.9003 - loss: 0.0360 - mae: 0.1449 - rmse: 0.1808 - smape: 0.3551 - val_ia: 0.4898 - val_loss: 0.0183 - val_mae: 0.1024 - val_rmse: 0.1155 - val_smape: 0.3001

Epoch 41/128

4586/4586 - 58s - 13ms/step - ia: 0.9003 - loss: 0.0358 - mae: 0.1448 - rmse: 0.1802 - smape: 0.3566 - val_ia: 0.5037 - val_loss: 0.0175 - val_mae: 0.0978 - val_rmse: 0.1111 - val_smape: 0.2829

Epoch 42/128

4586/4586 - 56s - 12ms/step - ia: 0.9016 - loss: 0.0350 - mae: 0.1432 - rmse: 0.1787 - smape: 0.3519 - val_ia: 0.5051 - val_loss: 0.0175 - val_mae: 0.0977 - val_rmse: 0.1110 - val_smape: 0.2839

Epoch 43/128

4586/4586 - 56s - 12ms/step - ia: 0.9029 - loss: 0.0346 - mae: 0.1419 - rmse: 0.1772 - smape: 0.3500 - val_ia: 0.5111 - val_loss: 0.0165 - val_mae: 0.0937 - val_rmse: 0.1071 - val_smape: 0.2696

Epoch 44/128

4586/4586 - 55s - 12ms/step - ia: 0.9028 - loss: 0.0342 - mae: 0.1416 - rmse: 0.1766 - smape: 0.3478 - val_ia: 0.5064 - val_loss: 0.0171 - val_mae: 0.0966 - val_rmse: 0.1100 - val_smape: 0.2848

Epoch 45/128

4586/4586 - 57s - 12ms/step - ia: 0.9038 - loss: 0.0335 - mae: 0.1396 - rmse: 0.1745 - smape: 0.3444 - val_ia: 0.5189 - val_loss: 0.0159 - val_mae: 0.0907 - val_rmse: 0.1042 - val_smape: 0.2610

Epoch 46/128

4586/4586 - 55s - 12ms/step - ia: 0.9045 - loss: 0.0328 - mae: 0.1386 - rmse: 0.1726 - smape: 0.3423 - val_ia: 0.5212 - val_loss: 0.0154 - val_mae: 0.0893 - val_rmse: 0.1028 - val_smape: 0.2584

Epoch 47/128

4586/4586 - 55s - 12ms/step - ia: 0.9053 - loss: 0.0326 - mae: 0.1379 - rmse: 0.1719 - smape: 0.3409 - val_ia: 0.5262 - val_loss: 0.0146 - val_mae: 0.0859 - val_rmse: 0.0994 - val_smape: 0.2436

Epoch 48/128

4586/4586 - 55s - 12ms/step - ia: 0.9063 - loss: 0.0321 - mae: 0.1361 - rmse: 0.1707 - smape: 0.3404 - val_ia: 0.5247 - val_loss: 0.0152 - val_mae: 0.0881 - val_rmse: 0.1016 - val_smape: 0.2569

Epoch 49/128

4586/4586 - 55s - 12ms/step - ia: 0.9069 - loss: 0.0317 - mae: 0.1356 - rmse: 0.1697 - smape: 0.3358 - val_ia: 0.5256 - val_loss: 0.0148 - val_mae: 0.0871 - val_rmse: 0.1007 - val_smape: 0.2556

Epoch 50/128

4586/4586 - 55s - 12ms/step - ia: 0.9069 - loss: 0.0314 - mae: 0.1349 - rmse: 0.1686 - smape: 0.3374 - val_ia: 0.5325 - val_loss: 0.0146 - val_mae: 0.0850 - val_rmse: 0.0986 - val_smape: 0.2432

Epoch 51/128

4586/4586 - 55s - 12ms/step - ia: 0.9075 - loss: 0.0311 - mae: 0.1344 - rmse: 0.1679 - smape: 0.3376 - val_ia: 0.5302 - val_loss: 0.0149 - val_mae: 0.0867 - val_rmse: 0.1003 - val_smape: 0.2538

Epoch 52/128

4586/4586 - 54s - 12ms/step - ia: 0.9086 - loss: 0.0308 - mae: 0.1338 - rmse: 0.1670 - smape: 0.3347 - val_ia: 0.5332 - val_loss: 0.0142 - val_mae: 0.0844 - val_rmse: 0.0979 - val_smape: 0.2462

Epoch 53/128

4586/4586 - 54s - 12ms/step - ia: 0.9096 - loss: 0.0304 - mae: 0.1324 - rmse: 0.1656 - smape: 0.3309 - val_ia: 0.5343 - val_loss: 0.0142 - val_mae: 0.0842 - val_rmse: 0.0978 - val_smape: 0.2466

Epoch 54/128

4586/4586 - 55s - 12ms/step - ia: 0.9092 - loss: 0.0303 - mae: 0.1323 - rmse: 0.1653 - smape: 0.3298 - val_ia: 0.5374 - val_loss: 0.0143 - val_mae: 0.0840 - val_rmse: 0.0976 - val_smape: 0.2456

Epoch 55/128

4586/4586 - 51s - 11ms/step - ia: 0.9094 - loss: 0.0302 - mae: 0.1318 - rmse: 0.1653 - smape: 0.3296 - val_ia: 0.5363 - val_loss: 0.0143 - val_mae: 0.0844 - val_rmse: 0.0979 - val_smape: 0.2480

Epoch 56/128

4586/4586 - 44s - 10ms/step - ia: 0.9096 - loss: 0.0301 - mae: 0.1315 - rmse: 0.1649 - smape: 0.3270 - val_ia: 0.5340 - val_loss: 0.0142 - val_mae: 0.0848 - val_rmse: 0.0983 - val_smape: 0.2551

Epoch 57/128

4586/4586 - 44s - 10ms/step - ia: 0.9114 - loss: 0.0292 - mae: 0.1298 - rmse: 0.1625 - smape: 0.3241 - val_ia: 0.5372 - val_loss: 0.0142 - val_mae: 0.0842 - val_rmse: 0.0978 - val_smape: 0.2497

Epoch 58/128

4586/4586 - 44s - 10ms/step - ia: 0.9121 - loss: 0.0289 - mae: 0.1287 - rmse: 0.1614 - smape: 0.3234 - val_ia: 0.5458 - val_loss: 0.0129 - val_mae: 0.0787 - val_rmse: 0.0922 - val_smape: 0.2245

Epoch 59/128

4586/4586 - 44s - 10ms/step - ia: 0.9122 - loss: 0.0286 - mae: 0.1281 - rmse: 0.1607 - smape: 0.3213 - val_ia: 0.5410 - val_loss: 0.0141 - val_mae: 0.0833 - val_rmse: 0.0968 - val_smape: 0.2447

Epoch 60/128

4586/4586 - 44s - 10ms/step - ia: 0.9114 - loss: 0.0288 - mae: 0.1285 - rmse: 0.1612 - smape: 0.3244 - val_ia: 0.5384 - val_loss: 0.0143 - val_mae: 0.0845 - val_rmse: 0.0980 - val_smape: 0.2514

Epoch 61/128

4586/4586 - 44s - 10ms/step - ia: 0.9121 - loss: 0.0285 - mae: 0.1281 - rmse: 0.1605 - smape: 0.3219 - val_ia: 0.5445 - val_loss: 0.0135 - val_mae: 0.0810 - val_rmse: 0.0946 - val_smape: 0.2363

Epoch 62/128

4586/4586 - 44s - 9ms/step - ia: 0.9132 - loss: 0.0280 - mae: 0.1267 - rmse: 0.1588 - smape: 0.3240 - val_ia: 0.5370 - val_loss: 0.0143 - val_mae: 0.0848 - val_rmse: 0.0983 - val_smape: 0.2550

Epoch 63/128

4586/4586 - 44s - 10ms/step - ia: 0.9133 - loss: 0.0277 - mae: 0.1262 - rmse: 0.1581 - smape: 0.3189 - val_ia: 0.5458 - val_loss: 0.0134 - val_mae: 0.0807 - val_rmse: 0.0942 - val_smape: 0.2354

Epoch 64/128

4586/4586 - 44s - 10ms/step - ia: 0.9136 - loss: 0.0276 - mae: 0.1258 - rmse: 0.1578 - smape: 0.3190 - val_ia: 0.5383 - val_loss: 0.0141 - val_mae: 0.0842 - val_rmse: 0.0976 - val_smape: 0.2521

Epoch 65/128

4586/4586 - 44s - 10ms/step - ia: 0.9138 - loss: 0.0278 - mae: 0.1258 - rmse: 0.1582 - smape: 0.3177 - val_ia: 0.5413 - val_loss: 0.0139 - val_mae: 0.0831 - val_rmse: 0.0965 - val_smape: 0.2455

Epoch 66/128

4586/4586 - 44s - 10ms/step - ia: 0.9147 - loss: 0.0274 - mae: 0.1250 - rmse: 0.1569 - smape: 0.3181 - val_ia: 0.5465 - val_loss: 0.0134 - val_mae: 0.0808 - val_rmse: 0.0943 - val_smape: 0.2363

Epoch 67/128

4586/4586 - 44s - 10ms/step - ia: 0.9143 - loss: 0.0272 - mae: 0.1250 - rmse: 0.1565 - smape: 0.3164 - val_ia: 0.5480 - val_loss: 0.0131 - val_mae: 0.0799 - val_rmse: 0.0933 - val_smape: 0.2343

Epoch 68/128

4586/4586 - 49s - 11ms/step - ia: 0.9146 - loss: 0.0270 - mae: 0.1240 - rmse: 0.1554 - smape: 0.3153 - val_ia: 0.5434 - val_loss: 0.0138 - val_mae: 0.0824 - val_rmse: 0.0958 - val_smape: 0.2402

Epoch 69/128

4586/4586 - 58s - 13ms/step - ia: 0.9153 - loss: 0.0266 - mae: 0.1233 - rmse: 0.1549 - smape: 0.3146 - val_ia: 0.5452 - val_loss: 0.0135 - val_mae: 0.0816 - val_rmse: 0.0950 - val_smape: 0.2414

Epoch 70/128

4586/4586 - 46s - 10ms/step - ia: 0.9149 - loss: 0.0266 - mae: 0.1237 - rmse: 0.1549 - smape: 0.3149 - val_ia: 0.5542 - val_loss: 0.0123 - val_mae: 0.0768 - val_rmse: 0.0902 - val_smape: 0.2223

Epoch 71/128

4586/4586 - 46s - 10ms/step - ia: 0.9153 - loss: 0.0265 - mae: 0.1231 - rmse: 0.1542 - smape: 0.3120 - val_ia: 0.5535 - val_loss: 0.0125 - val_mae: 0.0775 - val_rmse: 0.0909 - val_smape: 0.2237

Epoch 72/128

4586/4586 - 46s - 10ms/step - ia: 0.9162 - loss: 0.0263 - mae: 0.1226 - rmse: 0.1537 - smape: 0.3133 - val_ia: 0.5512 - val_loss: 0.0129 - val_mae: 0.0787 - val_rmse: 0.0921 - val_smape: 0.2228

Epoch 73/128

4586/4586 - 46s - 10ms/step - ia: 0.9159 - loss: 0.0263 - mae: 0.1226 - rmse: 0.1537 - smape: 0.3133 - val_ia: 0.5488 - val_loss: 0.0130 - val_mae: 0.0797 - val_rmse: 0.0930 - val_smape: 0.2312

Epoch 74/128

4586/4586 - 46s - 10ms/step - ia: 0.9161 - loss: 0.0260 - mae: 0.1220 - rmse: 0.1530 - smape: 0.3125 - val_ia: 0.5540 - val_loss: 0.0123 - val_mae: 0.0771 - val_rmse: 0.0904 - val_smape: 0.2214

Epoch 75/128

4586/4586 - 46s - 10ms/step - ia: 0.9158 - loss: 0.0262 - mae: 0.1227 - rmse: 0.1538 - smape: 0.3112 - val_ia: 0.5524 - val_loss: 0.0127 - val_mae: 0.0784 - val_rmse: 0.0917 - val_smape: 0.2289

Epoch 76/128

4586/4586 - 46s - 10ms/step - ia: 0.9168 - loss: 0.0255 - mae: 0.1208 - rmse: 0.1515 - smape: 0.3095 - val_ia: 0.5434 - val_loss: 0.0133 - val_mae: 0.0816 - val_rmse: 0.0948 - val_smape: 0.2435

Epoch 77/128

4586/4586 - 46s - 10ms/step - ia: 0.9175 - loss: 0.0254 - mae: 0.1202 - rmse: 0.1511 - smape: 0.3053 - val_ia: 0.5504 - val_loss: 0.0128 - val_mae: 0.0791 - val_rmse: 0.0924 - val_smape: 0.2291

Epoch 78/128

4586/4586 - 47s - 10ms/step - ia: 0.9169 - loss: 0.0255 - mae: 0.1210 - rmse: 0.1517 - smape: 0.3059 - val_ia: 0.5571 - val_loss: 0.0122 - val_mae: 0.0765 - val_rmse: 0.0898 - val_smape: 0.2217

Epoch 79/128

4586/4586 - 46s - 10ms/step - ia: 0.9180 - loss: 0.0251 - mae: 0.1195 - rmse: 0.1498 - smape: 0.3059 - val_ia: 0.5572 - val_loss: 0.0121 - val_mae: 0.0763 - val_rmse: 0.0895 - val_smape: 0.2224

Epoch 80/128

4586/4586 - 46s - 10ms/step - ia: 0.9181 - loss: 0.0251 - mae: 0.1194 - rmse: 0.1503 - smape: 0.3068 - val_ia: 0.5528 - val_loss: 0.0124 - val_mae: 0.0779 - val_rmse: 0.0911 - val_smape: 0.2303

Epoch 81/128

4586/4586 - 46s - 10ms/step - ia: 0.9184 - loss: 0.0249 - mae: 0.1191 - rmse: 0.1496 - smape: 0.3036 - val_ia: 0.5510 - val_loss: 0.0126 - val_mae: 0.0788 - val_rmse: 0.0919 - val_smape: 0.2298

Epoch 82/128

4586/4586 - 46s - 10ms/step - ia: 0.9183 - loss: 0.0248 - mae: 0.1186 - rmse: 0.1495 - smape: 0.3037 - val_ia: 0.5556 - val_loss: 0.0122 - val_mae: 0.0769 - val_rmse: 0.0900 - val_smape: 0.2239

Epoch 83/128

4586/4586 - 46s - 10ms/step - ia: 0.9182 - loss: 0.0248 - mae: 0.1189 - rmse: 0.1491 - smape: 0.3050 - val_ia: 0.5585 - val_loss: 0.0118 - val_mae: 0.0753 - val_rmse: 0.0885 - val_smape: 0.2124

Epoch 84/128

4586/4586 - 46s - 10ms/step - ia: 0.9186 - loss: 0.0245 - mae: 0.1183 - rmse: 0.1485 - smape: 0.3030 - val_ia: 0.5549 - val_loss: 0.0123 - val_mae: 0.0773 - val_rmse: 0.0905 - val_smape: 0.2273

Epoch 85/128

4586/4586 - 46s - 10ms/step - ia: 0.9195 - loss: 0.0243 - mae: 0.1175 - rmse: 0.1476 - smape: 0.3035 - val_ia: 0.5627 - val_loss: 0.0114 - val_mae: 0.0736 - val_rmse: 0.0868 - val_smape: 0.2052

Epoch 86/128

4586/4586 - 46s - 10ms/step - ia: 0.9191 - loss: 0.0242 - mae: 0.1177 - rmse: 0.1475 - smape: 0.3016 - val_ia: 0.5588 - val_loss: 0.0118 - val_mae: 0.0756 - val_rmse: 0.0887 - val_smape: 0.2209

Epoch 87/128

4586/4586 - 46s - 10ms/step - ia: 0.9194 - loss: 0.0242 - mae: 0.1169 - rmse: 0.1473 - smape: 0.2999 - val_ia: 0.5507 - val_loss: 0.0122 - val_mae: 0.0780 - val_rmse: 0.0910 - val_smape: 0.2334

Epoch 88/128

4586/4586 - 46s - 10ms/step - ia: 0.9194 - loss: 0.0240 - mae: 0.1173 - rmse: 0.1472 - smape: 0.3009 - val_ia: 0.5580 - val_loss: 0.0119 - val_mae: 0.0759 - val_rmse: 0.0890 - val_smape: 0.2204

Epoch 89/128

4586/4586 - 46s - 10ms/step - ia: 0.9195 - loss: 0.0240 - mae: 0.1171 - rmse: 0.1469 - smape: 0.3013 - val_ia: 0.5544 - val_loss: 0.0120 - val_mae: 0.0769 - val_rmse: 0.0899 - val_smape: 0.2204

Epoch 90/128

4586/4586 - 46s - 10ms/step - ia: 0.9195 - loss: 0.0241 - mae: 0.1173 - rmse: 0.1473 - smape: 0.2979 - val_ia: 0.5663 - val_loss: 0.0108 - val_mae: 0.0714 - val_rmse: 0.0845 - val_smape: 0.1973

Epoch 91/128

4586/4586 - 46s - 10ms/step - ia: 0.9200 - loss: 0.0236 - mae: 0.1160 - rmse: 0.1456 - smape: 0.2989 - val_ia: 0.5593 - val_loss: 0.0117 - val_mae: 0.0753 - val_rmse: 0.0882 - val_smape: 0.2189

Epoch 92/128

4586/4586 - 46s - 10ms/step - ia: 0.9200 - loss: 0.0237 - mae: 0.1162 - rmse: 0.1459 - smape: 0.3001 - val_ia: 0.5585 - val_loss: 0.0116 - val_mae: 0.0754 - val_rmse: 0.0884 - val_smape: 0.2208

Epoch 93/128

4586/4586 - 46s - 10ms/step - ia: 0.9210 - loss: 0.0234 - mae: 0.1155 - rmse: 0.1449 - smape: 0.2976 - val_ia: 0.5632 - val_loss: 0.0113 - val_mae: 0.0736 - val_rmse: 0.0866 - val_smape: 0.2107

Epoch 94/128

4586/4586 - 46s - 10ms/step - ia: 0.9209 - loss: 0.0237 - mae: 0.1161 - rmse: 0.1457 - smape: 0.2988 - val_ia: 0.5621 - val_loss: 0.0112 - val_mae: 0.0739 - val_rmse: 0.0868 - val_smape: 0.2175

Epoch 95/128

4586/4586 - 46s - 10ms/step - ia: 0.9216 - loss: 0.0232 - mae: 0.1145 - rmse: 0.1441 - smape: 0.2930 - val_ia: 0.5623 - val_loss: 0.0113 - val_mae: 0.0739 - val_rmse: 0.0868 - val_smape: 0.2118

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 4s - 15ms/step - ia: 0.9094 - loss: 0.0484 - mae: 0.1427 - rmse: 0.1900 - smape: 0.3650 - val_ia: 0.9269 - val_loss: 0.0177 - val_mae: 0.0961 - val_rmse: 0.1313 - val_smape: 0.2619

Epoch 2/128

287/287 - 1s - 5ms/step - ia: 0.9589 - loss: 0.0097 - mae: 0.0675 - rmse: 0.0958 - smape: 0.2017 - val_ia: 0.9586 - val_loss: 0.0055 - val_mae: 0.0545 - val_rmse: 0.0732 - val_smape: 0.1544

Epoch 3/128

287/287 - 1s - 5ms/step - ia: 0.9728 - loss: 0.0043 - mae: 0.0448 - rmse: 0.0635 - smape: 0.1495 - val_ia: 0.9692 - val_loss: 0.0032 - val_mae: 0.0407 - val_rmse: 0.0552 - val_smape: 0.1223

Epoch 4/128

287/287 - 1s - 5ms/step - ia: 0.9752 - loss: 0.0036 - mae: 0.0408 - rmse: 0.0581 - smape: 0.1402 - val_ia: 0.9619 - val_loss: 0.0043 - val_mae: 0.0505 - val_rmse: 0.0641 - val_smape: 0.1457

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.9764 - loss: 0.0034 - mae: 0.0388 - rmse: 0.0561 - smape: 0.1349 - val_ia: 0.9721 - val_loss: 0.0027 - val_mae: 0.0368 - val_rmse: 0.0512 - val_smape: 0.1114

Epoch 6/128

287/287 - 1s - 5ms/step - ia: 0.9764 - loss: 0.0034 - mae: 0.0388 - rmse: 0.0560 - smape: 0.1350 - val_ia: 0.9689 - val_loss: 0.0032 - val_mae: 0.0422 - val_rmse: 0.0556 - val_smape: 0.1397

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.9761 - loss: 0.0034 - mae: 0.0394 - rmse: 0.0564 - smape: 0.1365 - val_ia: 0.9703 - val_loss: 0.0030 - val_mae: 0.0398 - val_rmse: 0.0532 - val_smape: 0.1193

Epoch 8/128

287/287 - 1s - 5ms/step - ia: 0.9770 - loss: 0.0033 - mae: 0.0379 - rmse: 0.0546 - smape: 0.1331 - val_ia: 0.9727 - val_loss: 0.0027 - val_mae: 0.0366 - val_rmse: 0.0507 - val_smape: 0.1157

Epoch 9/128

287/287 - 1s - 5ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0373 - rmse: 0.0542 - smape: 0.1320 - val_ia: 0.9702 - val_loss: 0.0030 - val_mae: 0.0398 - val_rmse: 0.0533 - val_smape: 0.1162

Epoch 10/128

287/287 - 1s - 5ms/step - ia: 0.9775 - loss: 0.0032 - mae: 0.0371 - rmse: 0.0540 - smape: 0.1312 - val_ia: 0.9726 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0503 - val_smape: 0.1139

Epoch 11/128

287/287 - 1s - 5ms/step - ia: 0.9771 - loss: 0.0033 - mae: 0.0378 - rmse: 0.0546 - smape: 0.1323 - val_ia: 0.9741 - val_loss: 0.0025 - val_mae: 0.0349 - val_rmse: 0.0489 - val_smape: 0.1088

Epoch 12/128

287/287 - 1s - 5ms/step - ia: 0.9779 - loss: 0.0031 - mae: 0.0365 - rmse: 0.0532 - smape: 0.1293 - val_ia: 0.9725 - val_loss: 0.0027 - val_mae: 0.0374 - val_rmse: 0.0512 - val_smape: 0.1187

Epoch 13/128

287/287 - 1s - 5ms/step - ia: 0.9777 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0536 - smape: 0.1312 - val_ia: 0.9713 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0524 - val_smape: 0.1229

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.9773 - loss: 0.0032 - mae: 0.0375 - rmse: 0.0543 - smape: 0.1312 - val_ia: 0.9710 - val_loss: 0.0029 - val_mae: 0.0390 - val_rmse: 0.0526 - val_smape: 0.1147

Epoch 15/128

287/287 - 1s - 5ms/step - ia: 0.9780 - loss: 0.0031 - mae: 0.0362 - rmse: 0.0530 - smape: 0.1296 - val_ia: 0.9730 - val_loss: 0.0027 - val_mae: 0.0365 - val_rmse: 0.0508 - val_smape: 0.1133

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.9781 - loss: 0.0031 - mae: 0.0361 - rmse: 0.0529 - smape: 0.1292 - val_ia: 0.9664 - val_loss: 0.0037 - val_mae: 0.0453 - val_rmse: 0.0589 - val_smape: 0.1319

Epoch 17/128

287/287 - 1s - 5ms/step - ia: 0.9774 - loss: 0.0032 - mae: 0.0372 - rmse: 0.0538 - smape: 0.1301 - val_ia: 0.9710 - val_loss: 0.0029 - val_mae: 0.0392 - val_rmse: 0.0528 - val_smape: 0.1178

Epoch 18/128

287/287 - 2s - 5ms/step - ia: 0.9780 - loss: 0.0031 - mae: 0.0362 - rmse: 0.0531 - smape: 0.1292 - val_ia: 0.9725 - val_loss: 0.0027 - val_mae: 0.0372 - val_rmse: 0.0509 - val_smape: 0.1168

Epoch 19/128

287/287 - 1s - 5ms/step - ia: 0.9781 - loss: 0.0031 - mae: 0.0361 - rmse: 0.0527 - smape: 0.1285 - val_ia: 0.9720 - val_loss: 0.0028 - val_mae: 0.0378 - val_rmse: 0.0513 - val_smape: 0.1254

Epoch 20/128

287/287 - 1s - 5ms/step - ia: 0.9781 - loss: 0.0031 - mae: 0.0361 - rmse: 0.0528 - smape: 0.1288 - val_ia: 0.9718 - val_loss: 0.0028 - val_mae: 0.0382 - val_rmse: 0.0515 - val_smape: 0.1222

Epoch 21/128

287/287 - 1s - 5ms/step - ia: 0.9776 - loss: 0.0031 - mae: 0.0368 - rmse: 0.0535 - smape: 0.1293 - val_ia: 0.9718 - val_loss: 0.0030 - val_mae: 0.0384 - val_rmse: 0.0536 - val_smape: 0.1154

Epoch 22/128

287/287 - 1s - 5ms/step - ia: 0.9782 - loss: 0.0030 - mae: 0.0359 - rmse: 0.0525 - smape: 0.1274 - val_ia: 0.9745 - val_loss: 0.0025 - val_mae: 0.0347 - val_rmse: 0.0486 - val_smape: 0.1144

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.9784 - loss: 0.0030 - mae: 0.0357 - rmse: 0.0524 - smape: 0.1276 - val_ia: 0.9720 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0513 - val_smape: 0.1255

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.9781 - loss: 0.0030 - mae: 0.0360 - rmse: 0.0526 - smape: 0.1283 - val_ia: 0.9713 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0517 - val_smape: 0.1233

Epoch 25/128

287/287 - 1s - 5ms/step - ia: 0.9785 - loss: 0.0030 - mae: 0.0353 - rmse: 0.0518 - smape: 0.1267 - val_ia: 0.9691 - val_loss: 0.0032 - val_mae: 0.0415 - val_rmse: 0.0553 - val_smape: 0.1383

Epoch 26/128

287/287 - 1s - 5ms/step - ia: 0.9783 - loss: 0.0030 - mae: 0.0358 - rmse: 0.0521 - smape: 0.1277 - val_ia: 0.9687 - val_loss: 0.0032 - val_mae: 0.0423 - val_rmse: 0.0555 - val_smape: 0.1331

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.9786 - loss: 0.0029 - mae: 0.0353 - rmse: 0.0518 - smape: 0.1269 - val_ia: 0.9653 - val_loss: 0.0038 - val_mae: 0.0465 - val_rmse: 0.0594 - val_smape: 0.1445

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.9788 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0515 - smape: 0.1261 - val_ia: 0.9722 - val_loss: 0.0028 - val_mae: 0.0380 - val_rmse: 0.0519 - val_smape: 0.1198

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.9785 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0517 - smape: 0.1271 - val_ia: 0.9724 - val_loss: 0.0028 - val_mae: 0.0374 - val_rmse: 0.0512 - val_smape: 0.1226

Epoch 30/128

287/287 - 1s - 5ms/step - ia: 0.9784 - loss: 0.0029 - mae: 0.0356 - rmse: 0.0519 - smape: 0.1273 - val_ia: 0.9657 - val_loss: 0.0038 - val_mae: 0.0460 - val_rmse: 0.0591 - val_smape: 0.1419

Epoch 31/128

287/287 - 1s - 5ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0350 - rmse: 0.0513 - smape: 0.1250 - val_ia: 0.9713 - val_loss: 0.0030 - val_mae: 0.0389 - val_rmse: 0.0530 - val_smape: 0.1255

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0514 - smape: 0.1260 - val_ia: 0.9617 - val_loss: 0.0045 - val_mae: 0.0515 - val_rmse: 0.0645 - val_smape: 0.1497

Epoch 33/128

287/287 - 1s - 5ms/step - ia: 0.9787 - loss: 0.0029 - mae: 0.0351 - rmse: 0.0514 - smape: 0.1262 - val_ia: 0.9728 - val_loss: 0.0027 - val_mae: 0.0369 - val_rmse: 0.0508 - val_smape: 0.1180

Epoch 34/128

287/287 - 1s - 5ms/step - ia: 0.9785 - loss: 0.0029 - mae: 0.0354 - rmse: 0.0515 - smape: 0.1271 - val_ia: 0.9725 - val_loss: 0.0028 - val_mae: 0.0376 - val_rmse: 0.0518 - val_smape: 0.1235

Epoch 35/128

287/287 - 1s - 5ms/step - ia: 0.9789 - loss: 0.0029 - mae: 0.0347 - rmse: 0.0510 - smape: 0.1250 - val_ia: 0.9710 - val_loss: 0.0030 - val_mae: 0.0393 - val_rmse: 0.0532 - val_smape: 0.1261

Epoch 36/128

287/287 - 1s - 5ms/step - ia: 0.9789 - loss: 0.0029 - mae: 0.0348 - rmse: 0.0511 - smape: 0.1254 - val_ia: 0.9691 - val_loss: 0.0035 - val_mae: 0.0416 - val_rmse: 0.0568 - val_smape: 0.1347

Epoch 37/128

287/287 - 1s - 5ms/step - ia: 0.9790 - loss: 0.0028 - mae: 0.0346 - rmse: 0.0508 - smape: 0.1249 - val_ia: 0.9704 - val_loss: 0.0031 - val_mae: 0.0402 - val_rmse: 0.0540 - val_smape: 0.1272

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 22.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 32s 201ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/256

 90%|█████████ | 45/50 [13:05:10<2:13:04, 1596.82s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 7s - 52ms/step - ia: 0.5474 - loss: 0.4690 - mae: 0.5295 - rmse: 0.6609 - smape: 1.0888 - val_ia: 0.7201 - val_loss: 0.2532 - val_mae: 0.3942 - val_rmse: 0.4968 - val_smape: 0.7691

Epoch 2/256

144/144 - 3s - 24ms/step - ia: 0.7833 - loss: 0.1921 - mae: 0.3360 - rmse: 0.4366 - smape: 0.6641 - val_ia: 0.7963 - val_loss: 0.1207 - val_mae: 0.2793 - val_rmse: 0.3420 - val_smape: 0.6359

Epoch 3/256

144/144 - 3s - 24ms/step - ia: 0.8322 - loss: 0.1221 - mae: 0.2678 - rmse: 0.3487 - smape: 0.5497 - val_ia: 0.8359 - val_loss: 0.0685 - val_mae: 0.2056 - val_rmse: 0.2604 - val_smape: 0.4971

Epoch 4/256

144/144 - 3s - 24ms/step - ia: 0.8508 - loss: 0.0971 - mae: 0.2395 - rmse: 0.3109 - smape: 0.5074 - val_ia: 0.8594 - val_loss: 0.0542 - val_mae: 0.1738 - val_rmse: 0.2326 - val_smape: 0.4141

Epoch 5/256

144/144 - 3s - 24ms/step - ia: 0.8641 - loss: 0.0829 - mae: 0.2193 - rmse: 0.2874 - smape: 0.4694 - val_ia: 0.8627 - val_loss: 0.0523 - val_mae: 0.1711 - val_rmse: 0.2263 - val_smape: 0.4027

Epoch 6/256

144/144 - 3s - 24ms/step - ia: 0.8711 - loss: 0.0758 - mae: 0.2084 - rmse: 0.2747 - smape: 0.4492 - val_ia: 0.8451 - val_loss: 0.0599 - val_mae: 0.1891 - val_rmse: 0.2424 - val_smape: 0.4157

Epoch 7/256

144/144 - 3s - 24ms/step - ia: 0.8776 - loss: 0.0690 - mae: 0.1981 - rmse: 0.2620 - smape: 0.4321 - val_ia: 0.8608 - val_loss: 0.0527 - val_mae: 0.1710 - val_rmse: 0.2281 - val_smape: 0.3699

Epoch 8/256

144/144 - 3s - 24ms/step - ia: 0.8823 - loss: 0.0644 - mae: 0.1907 - rmse: 0.2532 - smape: 0.4138 - val_ia: 0.8340 - val_loss: 0.0647 - val_mae: 0.2059 - val_rmse: 0.2495 - val_smape: 0.4554

Epoch 9/256

144/144 - 3s - 24ms/step - ia: 0.8856 - loss: 0.0611 - mae: 0.1852 - rmse: 0.2469 - smape: 0.4023 - val_ia: 0.8622 - val_loss: 0.0498 - val_mae: 0.1706 - val_rmse: 0.2211 - val_smape: 0.3700

Epoch 10/256

144/144 - 3s - 24ms/step - ia: 0.8883 - loss: 0.0594 - mae: 0.1812 - rmse: 0.2431 - smape: 0.3942 - val_ia: 0.8444 - val_loss: 0.0581 - val_mae: 0.1898 - val_rmse: 0.2387 - val_smape: 0.3917

Epoch 11/256

144/144 - 3s - 24ms/step - ia: 0.8901 - loss: 0.0571 - mae: 0.1785 - rmse: 0.2383 - smape: 0.3896 - val_ia: 0.8564 - val_loss: 0.0527 - val_mae: 0.1749 - val_rmse: 0.2281 - val_smape: 0.3527

Epoch 12/256

144/144 - 3s - 24ms/step - ia: 0.8926 - loss: 0.0548 - mae: 0.1744 - rmse: 0.2337 - smape: 0.3799 - val_ia: 0.8636 - val_loss: 0.0482 - val_mae: 0.1686 - val_rmse: 0.2158 - val_smape: 0.3547

Epoch 13/256

144/144 - 3s - 24ms/step - ia: 0.8936 - loss: 0.0536 - mae: 0.1727 - rmse: 0.2313 - smape: 0.3745 - val_ia: 0.8568 - val_loss: 0.0516 - val_mae: 0.1765 - val_rmse: 0.2240 - val_smape: 0.3648

Epoch 14/256

144/144 - 3s - 24ms/step - ia: 0.8942 - loss: 0.0535 - mae: 0.1718 - rmse: 0.2306 - smape: 0.3693 - val_ia: 0.8523 - val_loss: 0.0526 - val_mae: 0.1793 - val_rmse: 0.2277 - val_smape: 0.3566

Epoch 15/256

144/144 - 3s - 24ms/step - ia: 0.8964 - loss: 0.0517 - mae: 0.1682 - rmse: 0.2269 - smape: 0.3631 - val_ia: 0.8440 - val_loss: 0.0599 - val_mae: 0.1919 - val_rmse: 0.2393 - val_smape: 0.3846

Epoch 16/256

144/144 - 3s - 24ms/step - ia: 0.8980 - loss: 0.0500 - mae: 0.1658 - rmse: 0.2231 - smape: 0.3594 - val_ia: 0.8654 - val_loss: 0.0487 - val_mae: 0.1662 - val_rmse: 0.2181 - val_smape: 0.3400

Epoch 17/256

144/144 - 3s - 24ms/step - ia: 0.8989 - loss: 0.0492 - mae: 0.1641 - rmse: 0.2213 - smape: 0.3563 - val_ia: 0.8504 - val_loss: 0.0548 - val_mae: 0.1829 - val_rmse: 0.2304 - val_smape: 0.3545

Epoch 18/256

144/144 - 3s - 24ms/step - ia: 0.9004 - loss: 0.0480 - mae: 0.1621 - rmse: 0.2186 - smape: 0.3494 - val_ia: 0.8504 - val_loss: 0.0536 - val_mae: 0.1823 - val_rmse: 0.2281 - val_smape: 0.3593

Epoch 19/256

144/144 - 3s - 24ms/step - ia: 0.9013 - loss: 0.0476 - mae: 0.1603 - rmse: 0.2177 - smape: 0.3455 - val_ia: 0.8651 - val_loss: 0.0497 - val_mae: 0.1696 - val_rmse: 0.2165 - val_smape: 0.3575

Epoch 20/256

144/144 - 3s - 24ms/step - ia: 0.9009 - loss: 0.0475 - mae: 0.1610 - rmse: 0.2176 - smape: 0.3458 - val_ia: 0.8574 - val_loss: 0.0525 - val_mae: 0.1771 - val_rmse: 0.2252 - val_smape: 0.3559

Epoch 21/256

144/144 - 3s - 24ms/step - ia: 0.9024 - loss: 0.0465 - mae: 0.1587 - rmse: 0.2151 - smape: 0.3412 - val_ia: 0.8703 - val_loss: 0.0480 - val_mae: 0.1644 - val_rmse: 0.2137 - val_smape: 0.3475

Epoch 22/256

144/144 - 3s - 24ms/step - ia: 0.9038 - loss: 0.0451 - mae: 0.1566 - rmse: 0.2117 - smape: 0.3401 - val_ia: 0.8509 - val_loss: 0.0542 - val_mae: 0.1839 - val_rmse: 0.2284 - val_smape: 0.3595

Epoch 23/256

144/144 - 3s - 24ms/step - ia: 0.9032 - loss: 0.0459 - mae: 0.1573 - rmse: 0.2139 - smape: 0.3393 - val_ia: 0.8622 - val_loss: 0.0495 - val_mae: 0.1712 - val_rmse: 0.2194 - val_smape: 0.3536

Epoch 24/256

144/144 - 3s - 24ms/step - ia: 0.9049 - loss: 0.0443 - mae: 0.1548 - rmse: 0.2097 - smape: 0.3362 - val_ia: 0.8538 - val_loss: 0.0539 - val_mae: 0.1828 - val_rmse: 0.2273 - val_smape: 0.3730

Epoch 25/256

144/144 - 3s - 24ms/step - ia: 0.9047 - loss: 0.0445 - mae: 0.1550 - rmse: 0.2104 - smape: 0.3332 - val_ia: 0.8531 - val_loss: 0.0535 - val_mae: 0.1819 - val_rmse: 0.2261 - val_smape: 0.3587

Epoch 26/256

144/144 - 3s - 24ms/step - ia: 0.9053 - loss: 0.0444 - mae: 0.1543 - rmse: 0.2098 - smape: 0.3333 - val_ia: 0.8670 - val_loss: 0.0476 - val_mae: 0.1672 - val_rmse: 0.2134 - val_smape: 0.3448

Epoch 27/256

144/144 - 3s - 24ms/step - ia: 0.9064 - loss: 0.0434 - mae: 0.1522 - rmse: 0.2078 - smape: 0.3302 - val_ia: 0.8650 - val_loss: 0.0471 - val_mae: 0.1689 - val_rmse: 0.2132 - val_smape: 0.3465

Epoch 28/256

144/144 - 3s - 24ms/step - ia: 0.9060 - loss: 0.0436 - mae: 0.1529 - rmse: 0.2083 - smape: 0.3290 - val_ia: 0.8632 - val_loss: 0.0482 - val_mae: 0.1711 - val_rmse: 0.2157 - val_smape: 0.3533

Epoch 29/256

144/144 - 3s - 24ms/step - ia: 0.9064 - loss: 0.0434 - mae: 0.1523 - rmse: 0.2076 - smape: 0.3274 - val_ia: 0.8736 - val_loss: 0.0431 - val_mae: 0.1605 - val_rmse: 0.2016 - val_smape: 0.3375

Epoch 30/256

144/144 - 3s - 24ms/step - ia: 0.9074 - loss: 0.0423 - mae: 0.1506 - rmse: 0.2052 - smape: 0.3251 - val_ia: 0.8531 - val_loss: 0.0528 - val_mae: 0.1832 - val_rmse: 0.2252 - val_smape: 0.3746

Epoch 31/256

144/144 - 3s - 24ms/step - ia: 0.9079 - loss: 0.0425 - mae: 0.1501 - rmse: 0.2055 - smape: 0.3231 - val_ia: 0.8576 - val_loss: 0.0506 - val_mae: 0.1783 - val_rmse: 0.2204 - val_smape: 0.3599

Epoch 32/256

144/144 - 3s - 24ms/step - ia: 0.9082 - loss: 0.0417 - mae: 0.1493 - rmse: 0.2036 - smape: 0.3218 - val_ia: 0.8737 - val_loss: 0.0431 - val_mae: 0.1613 - val_rmse: 0.2029 - val_smape: 0.3418

Epoch 33/256

144/144 - 3s - 24ms/step - ia: 0.9082 - loss: 0.0418 - mae: 0.1493 - rmse: 0.2039 - smape: 0.3211 - val_ia: 0.8700 - val_loss: 0.0444 - val_mae: 0.1653 - val_rmse: 0.2056 - val_smape: 0.3479

Epoch 34/256

144/144 - 3s - 24ms/step - ia: 0.9078 - loss: 0.0423 - mae: 0.1502 - rmse: 0.2051 - smape: 0.3210 - val_ia: 0.8712 - val_loss: 0.0428 - val_mae: 0.1628 - val_rmse: 0.2040 - val_smape: 0.3398

Epoch 35/256

144/144 - 3s - 24ms/step - ia: 0.9102 - loss: 0.0399 - mae: 0.1464 - rmse: 0.1992 - smape: 0.3186 - val_ia: 0.8641 - val_loss: 0.0470 - val_mae: 0.1724 - val_rmse: 0.2120 - val_smape: 0.3650

Epoch 36/256

144/144 - 3s - 24ms/step - ia: 0.9084 - loss: 0.0417 - mae: 0.1491 - rmse: 0.2037 - smape: 0.3185 - val_ia: 0.8698 - val_loss: 0.0416 - val_mae: 0.1643 - val_rmse: 0.2001 - val_smape: 0.3480

Epoch 37/256

144/144 - 3s - 24ms/step - ia: 0.9085 - loss: 0.0416 - mae: 0.1489 - rmse: 0.2035 - smape: 0.3185 - val_ia: 0.8620 - val_loss: 0.0468 - val_mae: 0.1736 - val_rmse: 0.2121 - val_smape: 0.3550

Epoch 38/256

144/144 - 3s - 24ms/step - ia: 0.9095 - loss: 0.0409 - mae: 0.1472 - rmse: 0.2019 - smape: 0.3172 - val_ia: 0.8516 - val_loss: 0.0533 - val_mae: 0.1859 - val_rmse: 0.2262 - val_smape: 0.3741

Epoch 39/256

144/144 - 3s - 24ms/step - ia: 0.9108 - loss: 0.0400 - mae: 0.1453 - rmse: 0.1996 - smape: 0.3111 - val_ia: 0.8725 - val_loss: 0.0420 - val_mae: 0.1627 - val_rmse: 0.2005 - val_smape: 0.3477

Epoch 40/256

144/144 - 3s - 24ms/step - ia: 0.9103 - loss: 0.0404 - mae: 0.1462 - rmse: 0.2005 - smape: 0.3132 - val_ia: 0.8663 - val_loss: 0.0450 - val_mae: 0.1694 - val_rmse: 0.2083 - val_smape: 0.3498

Epoch 41/256

144/144 - 3s - 24ms/step - ia: 0.9099 - loss: 0.0403 - mae: 0.1465 - rmse: 0.2003 - smape: 0.3127 - val_ia: 0.8705 - val_loss: 0.0421 - val_mae: 0.1645 - val_rmse: 0.2012 - val_smape: 0.3422

Epoch 42/256

144/144 - 3s - 24ms/step - ia: 0.9105 - loss: 0.0402 - mae: 0.1456 - rmse: 0.2000 - smape: 0.3129 - val_ia: 0.8692 - val_loss: 0.0440 - val_mae: 0.1664 - val_rmse: 0.2061 - val_smape: 0.3509

Epoch 43/256

144/144 - 3s - 24ms/step - ia: 0.9107 - loss: 0.0399 - mae: 0.1453 - rmse: 0.1991 - smape: 0.3099 - val_ia: 0.8637 - val_loss: 0.0450 - val_mae: 0.1715 - val_rmse: 0.2087 - val_smape: 0.3511

Epoch 44/256

144/144 - 3s - 24ms/step - ia: 0.9114 - loss: 0.0390 - mae: 0.1441 - rmse: 0.1970 - smape: 0.3094 - val_ia: 0.8687 - val_loss: 0.0442 - val_mae: 0.1666 - val_rmse: 0.2062 - val_smape: 0.3448

Epoch 45/256

144/144 - 3s - 24ms/step - ia: 0.9117 - loss: 0.0390 - mae: 0.1437 - rmse: 0.1970 - smape: 0.3093 - val_ia: 0.8635 - val_loss: 0.0455 - val_mae: 0.1713 - val_rmse: 0.2099 - val_smape: 0.3479

Epoch 46/256

144/144 - 3s - 24ms/step - ia: 0.9119 - loss: 0.0393 - mae: 0.1436 - rmse: 0.1976 - smape: 0.3075 - val_ia: 0.8628 - val_loss: 0.0461 - val_mae: 0.1728 - val_rmse: 0.2111 - val_smape: 0.3577

Epoch 47/256

144/144 - 3s - 24ms/step - ia: 0.9120 - loss: 0.0390 - mae: 0.1433 - rmse: 0.1968 - smape: 0.3055 - val_ia: 0.8638 - val_loss: 0.0454 - val_mae: 0.1717 - val_rmse: 0.2089 - val_smape: 0.3498

Epoch 48/256

144/144 - 3s - 24ms/step - ia: 0.9116 - loss: 0.0394 - mae: 0.1438 - rmse: 0.1981 - smape: 0.3064 - val_ia: 0.8582 - val_loss: 0.0478 - val_mae: 0.1775 - val_rmse: 0.2150 - val_smape: 0.3529

Epoch 49/256

144/144 - 3s - 24ms/step - ia: 0.9120 - loss: 0.0392 - mae: 0.1433 - rmse: 0.1973 - smape: 0.3053 - val_ia: 0.8509 - val_loss: 0.0531 - val_mae: 0.1871 - val_rmse: 0.2250 - val_smape: 0.3726

Epoch 50/256

144/144 - 3s - 24ms/step - ia: 0.9123 - loss: 0.0388 - mae: 0.1429 - rmse: 0.1963 - smape: 0.3046 - val_ia: 0.8492 - val_loss: 0.0525 - val_mae: 0.1884 - val_rmse: 0.2235 - val_smape: 0.3781

Epoch 51/256

144/144 - 3s - 24ms/step - ia: 0.9129 - loss: 0.0382 - mae: 0.1420 - rmse: 0.1949 - smape: 0.3043 - val_ia: 0.8599 - val_loss: 0.0463 - val_mae: 0.1754 - val_rmse: 0.2105 - val_smape: 0.3571

Epoch 51: early stopping

Restoring model weights from the end of the best epoch: 36.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 46s 285ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/128

 92%|█████████▏| 46/50 [13:08:10<1:18:07, 1171.89s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 30s - 26ms/step - ia: 0.9296 - loss: 0.0303 - mae: 0.1114 - rmse: 0.1462 - smape: 0.2707 - val_ia: 0.8844 - val_loss: 0.0043 - val_mae: 0.0470 - val_rmse: 0.0609 - val_smape: 0.1376

Epoch 2/128

1147/1147 - 25s - 22ms/step - ia: 0.9578 - loss: 0.0087 - mae: 0.0681 - rmse: 0.0904 - smape: 0.1818 - val_ia: 0.8826 - val_loss: 0.0053 - val_mae: 0.0527 - val_rmse: 0.0661 - val_smape: 0.1367

Epoch 3/128

1147/1147 - 25s - 22ms/step - ia: 0.9605 - loss: 0.0078 - mae: 0.0640 - rmse: 0.0853 - smape: 0.1711 - val_ia: 0.8824 - val_loss: 0.0040 - val_mae: 0.0465 - val_rmse: 0.0590 - val_smape: 0.1392

Epoch 4/128

1147/1147 - 25s - 22ms/step - ia: 0.9630 - loss: 0.0069 - mae: 0.0598 - rmse: 0.0797 - smape: 0.1640 - val_ia: 0.9047 - val_loss: 0.0029 - val_mae: 0.0387 - val_rmse: 0.0508 - val_smape: 0.1153

Epoch 5/128

1147/1147 - 25s - 22ms/step - ia: 0.9633 - loss: 0.0068 - mae: 0.0593 - rmse: 0.0793 - smape: 0.1640 - val_ia: 0.8833 - val_loss: 0.0041 - val_mae: 0.0477 - val_rmse: 0.0602 - val_smape: 0.1288

Epoch 6/128

1147/1147 - 25s - 22ms/step - ia: 0.9646 - loss: 0.0063 - mae: 0.0572 - rmse: 0.0761 - smape: 0.1641 - val_ia: 0.9000 - val_loss: 0.0031 - val_mae: 0.0415 - val_rmse: 0.0533 - val_smape: 0.1306

Epoch 7/128

1147/1147 - 25s - 22ms/step - ia: 0.9649 - loss: 0.0063 - mae: 0.0568 - rmse: 0.0758 - smape: 0.1620 - val_ia: 0.9131 - val_loss: 0.0027 - val_mae: 0.0371 - val_rmse: 0.0492 - val_smape: 0.1134

Epoch 8/128

1147/1147 - 25s - 22ms/step - ia: 0.9655 - loss: 0.0061 - mae: 0.0558 - rmse: 0.0746 - smape: 0.1612 - val_ia: 0.8761 - val_loss: 0.0047 - val_mae: 0.0523 - val_rmse: 0.0645 - val_smape: 0.1585

Epoch 9/128

1147/1147 - 25s - 22ms/step - ia: 0.9660 - loss: 0.0058 - mae: 0.0549 - rmse: 0.0732 - smape: 0.1606 - val_ia: 0.8846 - val_loss: 0.0038 - val_mae: 0.0464 - val_rmse: 0.0576 - val_smape: 0.1425

Epoch 10/128

1147/1147 - 26s - 22ms/step - ia: 0.9660 - loss: 0.0059 - mae: 0.0550 - rmse: 0.0735 - smape: 0.1600 - val_ia: 0.8621 - val_loss: 0.0059 - val_mae: 0.0589 - val_rmse: 0.0709 - val_smape: 0.1398

Epoch 11/128

1147/1147 - 25s - 22ms/step - ia: 0.9669 - loss: 0.0055 - mae: 0.0535 - rmse: 0.0713 - smape: 0.1575 - val_ia: 0.8884 - val_loss: 0.0036 - val_mae: 0.0446 - val_rmse: 0.0559 - val_smape: 0.1363

Epoch 12/128

1147/1147 - 26s - 22ms/step - ia: 0.9675 - loss: 0.0054 - mae: 0.0524 - rmse: 0.0702 - smape: 0.1548 - val_ia: 0.9009 - val_loss: 0.0031 - val_mae: 0.0407 - val_rmse: 0.0525 - val_smape: 0.1256

Epoch 13/128

1147/1147 - 26s - 22ms/step - ia: 0.9677 - loss: 0.0053 - mae: 0.0521 - rmse: 0.0697 - smape: 0.1537 - val_ia: 0.8940 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0534 - val_smape: 0.1173

Epoch 14/128

1147/1147 - 25s - 22ms/step - ia: 0.9677 - loss: 0.0053 - mae: 0.0522 - rmse: 0.0697 - smape: 0.1554 - val_ia: 0.9023 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0518 - val_smape: 0.1118

Epoch 15/128

1147/1147 - 25s - 22ms/step - ia: 0.9683 - loss: 0.0051 - mae: 0.0511 - rmse: 0.0684 - smape: 0.1526 - val_ia: 0.8988 - val_loss: 0.0032 - val_mae: 0.0418 - val_rmse: 0.0534 - val_smape: 0.1203

Epoch 16/128

1147/1147 - 25s - 22ms/step - ia: 0.9682 - loss: 0.0051 - mae: 0.0513 - rmse: 0.0686 - smape: 0.1529 - val_ia: 0.8894 - val_loss: 0.0038 - val_mae: 0.0470 - val_rmse: 0.0581 - val_smape: 0.1436

Epoch 17/128

1147/1147 - 25s - 22ms/step - ia: 0.9688 - loss: 0.0050 - mae: 0.0504 - rmse: 0.0675 - smape: 0.1515 - val_ia: 0.8944 - val_loss: 0.0035 - val_mae: 0.0437 - val_rmse: 0.0551 - val_smape: 0.1327

Epoch 18/128

1147/1147 - 25s - 22ms/step - ia: 0.9684 - loss: 0.0051 - mae: 0.0509 - rmse: 0.0683 - smape: 0.1538 - val_ia: 0.9082 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0523 - val_smape: 0.1241

Epoch 19/128

1147/1147 - 25s - 22ms/step - ia: 0.9689 - loss: 0.0050 - mae: 0.0503 - rmse: 0.0672 - smape: 0.1497 - val_ia: 0.8883 - val_loss: 0.0039 - val_mae: 0.0485 - val_rmse: 0.0596 - val_smape: 0.1599

Epoch 20/128

1147/1147 - 25s - 22ms/step - ia: 0.9694 - loss: 0.0048 - mae: 0.0494 - rmse: 0.0664 - smape: 0.1491 - val_ia: 0.8429 - val_loss: 0.0064 - val_mae: 0.0648 - val_rmse: 0.0763 - val_smape: 0.1730

Epoch 21/128

1147/1147 - 25s - 22ms/step - ia: 0.9691 - loss: 0.0049 - mae: 0.0500 - rmse: 0.0670 - smape: 0.1483 - val_ia: 0.9026 - val_loss: 0.0030 - val_mae: 0.0407 - val_rmse: 0.0520 - val_smape: 0.1225

Epoch 22/128

1147/1147 - 26s - 22ms/step - ia: 0.9697 - loss: 0.0048 - mae: 0.0490 - rmse: 0.0656 - smape: 0.1472 - val_ia: 0.8967 - val_loss: 0.0034 - val_mae: 0.0432 - val_rmse: 0.0549 - val_smape: 0.1377

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:03 392ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

Epoch 1/8

 94%|█████████▍| 47/50 [13:17:35<49:29, 989.80s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

574/574 - 8s - 14ms/step - ia: 0.9168 - loss: 0.0452 - mae: 0.1304 - rmse: 0.1738 - smape: 0.3018 - val_ia: 0.9306 - val_loss: 0.0080 - val_mae: 0.0660 - val_rmse: 0.0850 - val_smape: 0.1988

Epoch 2/8

574/574 - 5s - 9ms/step - ia: 0.9478 - loss: 0.0139 - mae: 0.0853 - rmse: 0.1157 - smape: 0.2083 - val_ia: 0.9477 - val_loss: 0.0045 - val_mae: 0.0486 - val_rmse: 0.0644 - val_smape: 0.1345

Epoch 3/8

574/574 - 5s - 9ms/step - ia: 0.9515 - loss: 0.0121 - mae: 0.0794 - rmse: 0.1082 - smape: 0.1917 - val_ia: 0.9492 - val_loss: 0.0042 - val_mae: 0.0478 - val_rmse: 0.0623 - val_smape: 0.1272

Epoch 4/8

574/574 - 5s - 9ms/step - ia: 0.9534 - loss: 0.0112 - mae: 0.0763 - rmse: 0.1041 - smape: 0.1854 - val_ia: 0.9597 - val_loss: 0.0030 - val_mae: 0.0395 - val_rmse: 0.0532 - val_smape: 0.1182

Epoch 5/8

574/574 - 5s - 9ms/step - ia: 0.9545 - loss: 0.0107 - mae: 0.0745 - rmse: 0.1018 - smape: 0.1812 - val_ia: 0.9541 - val_loss: 0.0037 - val_mae: 0.0446 - val_rmse: 0.0592 - val_smape: 0.1225

Epoch 6/8

574/574 - 5s - 9ms/step - ia: 0.9544 - loss: 0.0107 - mae: 0.0746 - rmse: 0.1016 - smape: 0.1830 - val_ia: 0.9010 - val_loss: 0.0130 - val_mae: 0.0904 - val_rmse: 0.1090 - val_smape: 0.1789

Epoch 7/8

574/574 - 5s - 9ms/step - ia: 0.9546 - loss: 0.0106 - mae: 0.0741 - rmse: 0.1012 - smape: 0.1810 - val_ia: 0.9498 - val_loss: 0.0047 - val_mae: 0.0508 - val_rmse: 0.0664 - val_smape: 0.1414

Epoch 8/8

574/574 - 5s - 9ms/step - ia: 0.9546 - loss: 0.0107 - mae: 0.0743 - rmse: 0.1016 - smape: 0.1817 - val_ia: 0.9006 - val_loss: 0.0135 - val_mae: 0.0902 - val_rmse: 0.1092 - val_smape: 0.1778

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 33s 207ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/16

 96%|█████████▌| 48/50 [13:18:22<23:33, 706.80s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4586/4586 - 47s - 10ms/step - ia: 0.9306 - loss: 0.0414 - mae: 0.0961 - rmse: 0.1178 - smape: 0.2527 - val_ia: 0.6809 - val_loss: 0.0035 - val_mae: 0.0420 - val_rmse: 0.0509 - val_smape: 0.1203

Epoch 2/16

4586/4586 - 44s - 10ms/step - ia: 0.9650 - loss: 0.0050 - mae: 0.0505 - rmse: 0.0629 - smape: 0.1688 - val_ia: 0.6931 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0499 - val_smape: 0.1309

Epoch 3/16

4586/4586 - 44s - 10ms/step - ia: 0.9677 - loss: 0.0044 - mae: 0.0470 - rmse: 0.0592 - smape: 0.1578 - val_ia: 0.6559 - val_loss: 0.0038 - val_mae: 0.0471 - val_rmse: 0.0561 - val_smape: 0.1543

Epoch 4/16

4586/4586 - 44s - 10ms/step - ia: 0.9684 - loss: 0.0042 - mae: 0.0455 - rmse: 0.0576 - smape: 0.1540 - val_ia: 0.6846 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0511 - val_smape: 0.1250

Epoch 5/16

4586/4586 - 48s - 10ms/step - ia: 0.9699 - loss: 0.0040 - mae: 0.0436 - rmse: 0.0554 - smape: 0.1484 - val_ia: 0.6283 - val_loss: 0.0046 - val_mae: 0.0529 - val_rmse: 0.0614 - val_smape: 0.1586

Epoch 6/16

4586/4586 - 44s - 10ms/step - ia: 0.9703 - loss: 0.0039 - mae: 0.0430 - rmse: 0.0547 - smape: 0.1462 - val_ia: 0.6817 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0509 - val_smape: 0.1199

Epoch 7/16

4586/4586 - 44s - 10ms/step - ia: 0.9714 - loss: 0.0036 - mae: 0.0413 - rmse: 0.0529 - smape: 0.1430 - val_ia: 0.6125 - val_loss: 0.0051 - val_mae: 0.0574 - val_rmse: 0.0659 - val_smape: 0.1851

Epoch 8/16

4586/4586 - 44s - 10ms/step - ia: 0.9716 - loss: 0.0036 - mae: 0.0412 - rmse: 0.0527 - smape: 0.1436 - val_ia: 0.6999 - val_loss: 0.0029 - val_mae: 0.0388 - val_rmse: 0.0477 - val_smape: 0.1239

Epoch 9/16

4586/4586 - 44s - 10ms/step - ia: 0.9720 - loss: 0.0035 - mae: 0.0406 - rmse: 0.0520 - smape: 0.1410 - val_ia: 0.6914 - val_loss: 0.0030 - val_mae: 0.0400 - val_rmse: 0.0488 - val_smape: 0.1306

Epoch 10/16

4586/4586 - 45s - 10ms/step - ia: 0.9723 - loss: 0.0034 - mae: 0.0399 - rmse: 0.0512 - smape: 0.1385 - val_ia: 0.6710 - val_loss: 0.0034 - val_mae: 0.0435 - val_rmse: 0.0520 - val_smape: 0.1380

Epoch 11/16

4586/4586 - 47s - 10ms/step - ia: 0.9733 - loss: 0.0033 - mae: 0.0387 - rmse: 0.0500 - smape: 0.1361 - val_ia: 0.6736 - val_loss: 0.0036 - val_mae: 0.0438 - val_rmse: 0.0523 - val_smape: 0.1199

Epoch 12/16

4586/4586 - 44s - 10ms/step - ia: 0.9729 - loss: 0.0034 - mae: 0.0391 - rmse: 0.0503 - smape: 0.1367 - val_ia: 0.6170 - val_loss: 0.0051 - val_mae: 0.0558 - val_rmse: 0.0638 - val_smape: 0.1745

Epoch 13/16

4586/4586 - 44s - 10ms/step - ia: 0.9735 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0494 - smape: 0.1347 - val_ia: 0.6181 - val_loss: 0.0047 - val_mae: 0.0545 - val_rmse: 0.0629 - val_smape: 0.1690

Epoch 14/16

4586/4586 - 44s - 10ms/step - ia: 0.9736 - loss: 0.0032 - mae: 0.0380 - rmse: 0.0490 - smape: 0.1337 - val_ia: 0.6467 - val_loss: 0.0043 - val_mae: 0.0494 - val_rmse: 0.0576 - val_smape: 0.1378

Epoch 15/16

4586/4586 - 44s - 10ms/step - ia: 0.9741 - loss: 0.0032 - mae: 0.0375 - rmse: 0.0486 - smape: 0.1328 - val_ia: 0.6791 - val_loss: 0.0033 - val_mae: 0.0425 - val_rmse: 0.0509 - val_smape: 0.1237

Epoch 16/16

4586/4586 - 44s - 10ms/step - ia: 0.9742 - loss: 0.0031 - mae: 0.0374 - rmse: 0.0483 - smape: 0.1317 - val_ia: 0.6399 - val_loss: 0.0045 - val_mae: 0.0515 - val_rmse: 0.0596 - val_smape: 0.1342

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 48s 301ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/32

 98%|█████████▊| 49/50 [13:30:22<11:50, 710.75s/trial, best loss: 0.0018204432146238458]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 8s - 27ms/step - ia: 0.6098 - loss: 0.4386 - mae: 0.5098 - rmse: 0.6476 - smape: 0.9748 - val_ia: 0.7607 - val_loss: 0.1616 - val_mae: 0.3227 - val_rmse: 0.3932 - val_smape: 0.6881

Epoch 2/32

287/287 - 3s - 11ms/step - ia: 0.7388 - loss: 0.2593 - mae: 0.3871 - rmse: 0.5078 - smape: 0.7591 - val_ia: 0.7765 - val_loss: 0.1268 - val_mae: 0.2850 - val_rmse: 0.3509 - val_smape: 0.6774

Epoch 3/32

287/287 - 3s - 11ms/step - ia: 0.7547 - loss: 0.2379 - mae: 0.3651 - rmse: 0.4864 - smape: 0.7218 - val_ia: 0.7855 - val_loss: 0.1164 - val_mae: 0.2732 - val_rmse: 0.3341 - val_smape: 0.6472

Epoch 4/32

287/287 - 3s - 11ms/step - ia: 0.7667 - loss: 0.2231 - mae: 0.3490 - rmse: 0.4706 - smape: 0.6853 - val_ia: 0.7697 - val_loss: 0.1301 - val_mae: 0.2844 - val_rmse: 0.3541 - val_smape: 0.6610

Epoch 5/32

287/287 - 3s - 11ms/step - ia: 0.7716 - loss: 0.2164 - mae: 0.3424 - rmse: 0.4636 - smape: 0.6688 - val_ia: 0.7675 - val_loss: 0.1358 - val_mae: 0.2872 - val_rmse: 0.3602 - val_smape: 0.6822

Epoch 6/32

287/287 - 3s - 11ms/step - ia: 0.7785 - loss: 0.2067 - mae: 0.3332 - rmse: 0.4533 - smape: 0.6473 - val_ia: 0.7582 - val_loss: 0.1452 - val_mae: 0.2999 - val_rmse: 0.3723 - val_smape: 0.7222

Epoch 7/32

287/287 - 3s - 11ms/step - ia: 0.7819 - loss: 0.2028 - mae: 0.3284 - rmse: 0.4486 - smape: 0.6400 - val_ia: 0.7461 - val_loss: 0.1506 - val_mae: 0.3088 - val_rmse: 0.3826 - val_smape: 0.7444

Epoch 8/32

287/287 - 3s - 11ms/step - ia: 0.7841 - loss: 0.2029 - mae: 0.3253 - rmse: 0.4490 - smape: 0.6304 - val_ia: 0.7317 - val_loss: 0.1758 - val_mae: 0.3389 - val_rmse: 0.4059 - val_smape: 0.7906

Epoch 9/32

287/287 - 3s - 12ms/step - ia: 0.7931 - loss: 0.1860 - mae: 0.3140 - rmse: 0.4296 - smape: 0.6099 - val_ia: 0.7326 - val_loss: 0.1671 - val_mae: 0.3453 - val_rmse: 0.3974 - val_smape: 0.7994

Epoch 10/32

287/287 - 3s - 11ms/step - ia: 0.7964 - loss: 0.1819 - mae: 0.3097 - rmse: 0.4249 - smape: 0.5995 - val_ia: 0.7483 - val_loss: 0.1474 - val_mae: 0.3164 - val_rmse: 0.3748 - val_smape: 0.7573

Epoch 11/32

287/287 - 3s - 11ms/step - ia: 0.8022 - loss: 0.1741 - mae: 0.3019 - rmse: 0.4155 - smape: 0.5842 - val_ia: 0.7006 - val_loss: 0.2067 - val_mae: 0.3876 - val_rmse: 0.4421 - val_smape: 0.8594

Epoch 12/32

287/287 - 3s - 11ms/step - ia: 0.8048 - loss: 0.1711 - mae: 0.2988 - rmse: 0.4117 - smape: 0.5751 - val_ia: 0.7145 - val_loss: 0.1920 - val_mae: 0.3725 - val_rmse: 0.4225 - val_smape: 0.8362

Epoch 13/32

287/287 - 3s - 11ms/step - ia: 0.8030 - loss: 0.1751 - mae: 0.3007 - rmse: 0.4166 - smape: 0.5746 - val_ia: 0.6865 - val_loss: 0.2293 - val_mae: 0.4051 - val_rmse: 0.4638 - val_smape: 0.8748

Epoch 14/32

287/287 - 3s - 11ms/step - ia: 0.8036 - loss: 0.1757 - mae: 0.3000 - rmse: 0.4174 - smape: 0.5720 - val_ia: 0.6848 - val_loss: 0.2225 - val_mae: 0.4056 - val_rmse: 0.4610 - val_smape: 0.8861

Epoch 15/32

287/287 - 3s - 11ms/step - ia: 0.8048 - loss: 0.1725 - mae: 0.2981 - rmse: 0.4135 - smape: 0.5711 - val_ia: 0.7251 - val_loss: 0.1857 - val_mae: 0.3633 - val_rmse: 0.4114 - val_smape: 0.8205

Epoch 16/32

287/287 - 3s - 11ms/step - ia: 0.8069 - loss: 0.1693 - mae: 0.2951 - rmse: 0.4096 - smape: 0.5679 - val_ia: 0.7333 - val_loss: 0.1680 - val_mae: 0.3572 - val_rmse: 0.3938 - val_smape: 0.8009

Epoch 17/32

287/287 - 3s - 11ms/step - ia: 0.8075 - loss: 0.1686 - mae: 0.2942 - rmse: 0.4089 - smape: 0.5627 - val_ia: 0.6790 - val_loss: 0.2489 - val_mae: 0.4457 - val_rmse: 0.4826 - val_smape: 0.9112

Epoch 18/32

287/287 - 3s - 11ms/step - ia: 0.8080 - loss: 0.1696 - mae: 0.2933 - rmse: 0.4106 - smape: 0.5597 - val_ia: 0.6757 - val_loss: 0.2465 - val_mae: 0.4307 - val_rmse: 0.4825 - val_smape: 0.9164

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:00 376ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

100%|██████████| 50/50 [13:31:24<00:00, 973.69s/trial, best loss: 0.0018204432146238458]
{'activation': 2, 'batch': 5, 'dropout': 0.0, 'epochs': 4, 'layers': 3.0, 'learning_rate': 0.00496146976730758, 'units': 4}

In [22]:
print(best)

{'activation': 2, 'batch': 5, 'dropout': 0.0, 'epochs': 4, 'layers': 3.0, 'learning_rate': 0.00496146976730758, 'units': 4}