Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 1
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52404, 12, 5)
Dimensiones de Y: (52404, 1)

In [15]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [16]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (52404, 60)

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36682, 60)
Las dimensiones de testX son:  (10533, 60)
Las dimensiones de valX son:  (5189, 60)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36682, 1)
Las dimensiones de testY son:  (10533, 1)
Las dimensiones de valY son:  (5189, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 9s - 8ms/step - ia: 0.4374 - loss: 1.7772 - mae: 0.9238 - rmse: 1.2108 - smape: 1.2541 - val_ia: 0.4226 - val_loss: 0.2743 - val_mae: 0.4316 - val_rmse: 0.4818 - val_smape: 0.8933

Epoch 2/128

1147/1147 - 3s - 2ms/step - ia: 0.5983 - loss: 0.5611 - mae: 0.5610 - rmse: 0.7380 - smape: 1.0072 - val_ia: 0.5367 - val_loss: 0.1324 - val_mae: 0.2951 - val_rmse: 0.3361 - val_smape: 0.5880

Epoch 3/128

1147/1147 - 3s - 3ms/step - ia: 0.6615 - loss: 0.4114 - mae: 0.4757 - rmse: 0.6334 - smape: 0.8798 - val_ia: 0.5546 - val_loss: 0.1172 - val_mae: 0.2781 - val_rmse: 0.3153 - val_smape: 0.5464

Epoch 4/128

1147/1147 - 7s - 6ms/step - ia: 0.7019 - loss: 0.3322 - mae: 0.4235 - rmse: 0.5689 - smape: 0.7802 - val_ia: 0.6015 - val_loss: 0.0812 - val_mae: 0.2307 - val_rmse: 0.2634 - val_smape: 0.4647

Epoch 5/128

1147/1147 - 5s - 4ms/step - ia: 0.7227 - loss: 0.2943 - mae: 0.3961 - rmse: 0.5350 - smape: 0.7275 - val_ia: 0.6127 - val_loss: 0.0737 - val_mae: 0.2207 - val_rmse: 0.2513 - val_smape: 0.4482

Epoch 6/128

1147/1147 - 4s - 4ms/step - ia: 0.7368 - loss: 0.2711 - mae: 0.3782 - rmse: 0.5134 - smape: 0.6916 - val_ia: 0.6189 - val_loss: 0.0730 - val_mae: 0.2199 - val_rmse: 0.2489 - val_smape: 0.4386

Epoch 7/128

1147/1147 - 3s - 3ms/step - ia: 0.7472 - loss: 0.2542 - mae: 0.3649 - rmse: 0.4975 - smape: 0.6602 - val_ia: 0.6137 - val_loss: 0.0737 - val_mae: 0.2212 - val_rmse: 0.2492 - val_smape: 0.4305

Epoch 8/128

1147/1147 - 5s - 4ms/step - ia: 0.7556 - loss: 0.2412 - mae: 0.3540 - rmse: 0.4843 - smape: 0.6336 - val_ia: 0.6029 - val_loss: 0.0823 - val_mae: 0.2354 - val_rmse: 0.2632 - val_smape: 0.4582

Epoch 9/128

1147/1147 - 5s - 4ms/step - ia: 0.7607 - loss: 0.2323 - mae: 0.3475 - rmse: 0.4749 - smape: 0.6239 - val_ia: 0.6624 - val_loss: 0.0495 - val_mae: 0.1804 - val_rmse: 0.2052 - val_smape: 0.3713

Epoch 10/128

1147/1147 - 5s - 4ms/step - ia: 0.7664 - loss: 0.2249 - mae: 0.3401 - rmse: 0.4670 - smape: 0.6007 - val_ia: 0.6811 - val_loss: 0.0421 - val_mae: 0.1660 - val_rmse: 0.1902 - val_smape: 0.3402

Epoch 11/128

1147/1147 - 4s - 3ms/step - ia: 0.7707 - loss: 0.2181 - mae: 0.3343 - rmse: 0.4601 - smape: 0.5874 - val_ia: 0.7214 - val_loss: 0.0296 - val_mae: 0.1378 - val_rmse: 0.1602 - val_smape: 0.2868

Epoch 12/128

1147/1147 - 4s - 3ms/step - ia: 0.7717 - loss: 0.2186 - mae: 0.3336 - rmse: 0.4602 - smape: 0.5803 - val_ia: 0.6388 - val_loss: 0.0603 - val_mae: 0.2019 - val_rmse: 0.2257 - val_smape: 0.3692

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.7725 - loss: 0.2166 - mae: 0.3322 - rmse: 0.4581 - smape: 0.5766 - val_ia: 0.6647 - val_loss: 0.0482 - val_mae: 0.1810 - val_rmse: 0.2026 - val_smape: 0.3733

Epoch 14/128

1147/1147 - 4s - 4ms/step - ia: 0.7754 - loss: 0.2127 - mae: 0.3286 - rmse: 0.4537 - smape: 0.5698 - val_ia: 0.6818 - val_loss: 0.0407 - val_mae: 0.1651 - val_rmse: 0.1862 - val_smape: 0.3447

Epoch 15/128

1147/1147 - 3s - 3ms/step - ia: 0.7775 - loss: 0.2089 - mae: 0.3261 - rmse: 0.4499 - smape: 0.5636 - val_ia: 0.6595 - val_loss: 0.0484 - val_mae: 0.1812 - val_rmse: 0.2034 - val_smape: 0.3295

Epoch 16/128

1147/1147 - 4s - 4ms/step - ia: 0.7772 - loss: 0.2087 - mae: 0.3260 - rmse: 0.4505 - smape: 0.5603 - val_ia: 0.6884 - val_loss: 0.0380 - val_mae: 0.1593 - val_rmse: 0.1797 - val_smape: 0.3228

Epoch 17/128

1147/1147 - 3s - 3ms/step - ia: 0.7810 - loss: 0.2041 - mae: 0.3218 - rmse: 0.4450 - smape: 0.5526 - val_ia: 0.6610 - val_loss: 0.0508 - val_mae: 0.1848 - val_rmse: 0.2067 - val_smape: 0.3636

Epoch 18/128

1147/1147 - 5s - 5ms/step - ia: 0.7782 - loss: 0.2082 - mae: 0.3250 - rmse: 0.4495 - smape: 0.5611 - val_ia: 0.7064 - val_loss: 0.0332 - val_mae: 0.1478 - val_rmse: 0.1687 - val_smape: 0.3115

Epoch 19/128

1147/1147 - 5s - 4ms/step - ia: 0.7809 - loss: 0.2046 - mae: 0.3220 - rmse: 0.4453 - smape: 0.5515 - val_ia: 0.6316 - val_loss: 0.0641 - val_mae: 0.2080 - val_rmse: 0.2313 - val_smape: 0.3743

Epoch 20/128

1147/1147 - 3s - 3ms/step - ia: 0.7811 - loss: 0.2044 - mae: 0.3207 - rmse: 0.4452 - smape: 0.5488 - val_ia: 0.6445 - val_loss: 0.0579 - val_mae: 0.1982 - val_rmse: 0.2205 - val_smape: 0.3694

Epoch 21/128

1147/1147 - 5s - 5ms/step - ia: 0.7826 - loss: 0.2013 - mae: 0.3193 - rmse: 0.4420 - smape: 0.5462 - val_ia: 0.6618 - val_loss: 0.0484 - val_mae: 0.1808 - val_rmse: 0.2021 - val_smape: 0.3374

Epoch 22/128

1147/1147 - 6s - 5ms/step - ia: 0.7838 - loss: 0.2000 - mae: 0.3178 - rmse: 0.4403 - smape: 0.5420 - val_ia: 0.7445 - val_loss: 0.0237 - val_mae: 0.1226 - val_rmse: 0.1427 - val_smape: 0.2764

Epoch 23/128

1147/1147 - 5s - 4ms/step - ia: 0.7814 - loss: 0.2047 - mae: 0.3213 - rmse: 0.4444 - smape: 0.5487 - val_ia: 0.7401 - val_loss: 0.0243 - val_mae: 0.1253 - val_rmse: 0.1448 - val_smape: 0.2692

Epoch 24/128

1147/1147 - 3s - 2ms/step - ia: 0.7834 - loss: 0.2002 - mae: 0.3178 - rmse: 0.4411 - smape: 0.5442 - val_ia: 0.6869 - val_loss: 0.0398 - val_mae: 0.1629 - val_rmse: 0.1831 - val_smape: 0.3182

Epoch 25/128

1147/1147 - 4s - 3ms/step - ia: 0.7838 - loss: 0.1999 - mae: 0.3177 - rmse: 0.4404 - smape: 0.5414 - val_ia: 0.6756 - val_loss: 0.0430 - val_mae: 0.1695 - val_rmse: 0.1904 - val_smape: 0.3103

Epoch 26/128

1147/1147 - 5s - 4ms/step - ia: 0.7836 - loss: 0.2010 - mae: 0.3183 - rmse: 0.4412 - smape: 0.5431 - val_ia: 0.6364 - val_loss: 0.0599 - val_mae: 0.2013 - val_rmse: 0.2236 - val_smape: 0.3619

Epoch 27/128

1147/1147 - 5s - 4ms/step - ia: 0.7831 - loss: 0.2018 - mae: 0.3182 - rmse: 0.4425 - smape: 0.5373 - val_ia: 0.6523 - val_loss: 0.0540 - val_mae: 0.1914 - val_rmse: 0.2129 - val_smape: 0.3619

Epoch 28/128

1147/1147 - 4s - 4ms/step - ia: 0.7836 - loss: 0.2005 - mae: 0.3178 - rmse: 0.4412 - smape: 0.5401 - val_ia: 0.7119 - val_loss: 0.0313 - val_mae: 0.1443 - val_rmse: 0.1634 - val_smape: 0.2713

Epoch 29/128

1147/1147 - 4s - 3ms/step - ia: 0.7857 - loss: 0.1970 - mae: 0.3154 - rmse: 0.4368 - smape: 0.5340 - val_ia: 0.6730 - val_loss: 0.0450 - val_mae: 0.1744 - val_rmse: 0.1948 - val_smape: 0.3181

Epoch 30/128

1147/1147 - 5s - 4ms/step - ia: 0.7837 - loss: 0.2024 - mae: 0.3183 - rmse: 0.4426 - smape: 0.5360 - val_ia: 0.6629 - val_loss: 0.0500 - val_mae: 0.1829 - val_rmse: 0.2043 - val_smape: 0.3340

Epoch 31/128

1147/1147 - 4s - 3ms/step - ia: 0.7838 - loss: 0.2005 - mae: 0.3181 - rmse: 0.4412 - smape: 0.5349 - val_ia: 0.6774 - val_loss: 0.0433 - val_mae: 0.1708 - val_rmse: 0.1911 - val_smape: 0.3125

Epoch 32/128

1147/1147 - 5s - 4ms/step - ia: 0.7860 - loss: 0.1969 - mae: 0.3145 - rmse: 0.4372 - smape: 0.5290 - val_ia: 0.7531 - val_loss: 0.0209 - val_mae: 0.1167 - val_rmse: 0.1344 - val_smape: 0.2521

Epoch 33/128

1147/1147 - 4s - 3ms/step - ia: 0.7850 - loss: 0.1995 - mae: 0.3160 - rmse: 0.4396 - smape: 0.5342 - val_ia: 0.6024 - val_loss: 0.0796 - val_mae: 0.2339 - val_rmse: 0.2570 - val_smape: 0.4312

Epoch 34/128

1147/1147 - 7s - 6ms/step - ia: 0.7864 - loss: 0.1964 - mae: 0.3141 - rmse: 0.4362 - smape: 0.5308 - val_ia: 0.7161 - val_loss: 0.0298 - val_mae: 0.1406 - val_rmse: 0.1594 - val_smape: 0.2899

Epoch 35/128

1147/1147 - 5s - 4ms/step - ia: 0.7862 - loss: 0.1968 - mae: 0.3142 - rmse: 0.4372 - smape: 0.5283 - val_ia: 0.7144 - val_loss: 0.0304 - val_mae: 0.1418 - val_rmse: 0.1606 - val_smape: 0.2806

Epoch 36/128

1147/1147 - 3s - 3ms/step - ia: 0.7866 - loss: 0.1977 - mae: 0.3143 - rmse: 0.4381 - smape: 0.5277 - val_ia: 0.6400 - val_loss: 0.0582 - val_mae: 0.1996 - val_rmse: 0.2209 - val_smape: 0.3548

Epoch 37/128

1147/1147 - 3s - 2ms/step - ia: 0.7849 - loss: 0.2007 - mae: 0.3167 - rmse: 0.4407 - smape: 0.5307 - val_ia: 0.6429 - val_loss: 0.0578 - val_mae: 0.1984 - val_rmse: 0.2202 - val_smape: 0.3642

Epoch 38/128

1147/1147 - 3s - 2ms/step - ia: 0.7869 - loss: 0.1975 - mae: 0.3135 - rmse: 0.4370 - smape: 0.5277 - val_ia: 0.7292 - val_loss: 0.0267 - val_mae: 0.1332 - val_rmse: 0.1512 - val_smape: 0.2865

Epoch 39/128

1147/1147 - 3s - 3ms/step - ia: 0.7886 - loss: 0.1937 - mae: 0.3116 - rmse: 0.4335 - smape: 0.5225 - val_ia: 0.7416 - val_loss: 0.0235 - val_mae: 0.1243 - val_rmse: 0.1422 - val_smape: 0.2589

Epoch 40/128

1147/1147 - 5s - 5ms/step - ia: 0.7865 - loss: 0.1984 - mae: 0.3148 - rmse: 0.4385 - smape: 0.5264 - val_ia: 0.7018 - val_loss: 0.0345 - val_mae: 0.1521 - val_rmse: 0.1713 - val_smape: 0.2945

Epoch 41/128

1147/1147 - 3s - 3ms/step - ia: 0.7883 - loss: 0.1948 - mae: 0.3120 - rmse: 0.4346 - smape: 0.5218 - val_ia: 0.6830 - val_loss: 0.0416 - val_mae: 0.1672 - val_rmse: 0.1872 - val_smape: 0.3080

Epoch 42/128

1147/1147 - 6s - 5ms/step - ia: 0.7866 - loss: 0.1989 - mae: 0.3138 - rmse: 0.4393 - smape: 0.5260 - val_ia: 0.6800 - val_loss: 0.0411 - val_mae: 0.1666 - val_rmse: 0.1863 - val_smape: 0.2940

Epoch 43/128

1147/1147 - 5s - 5ms/step - ia: 0.7851 - loss: 0.1993 - mae: 0.3156 - rmse: 0.4388 - smape: 0.5272 - val_ia: 0.7205 - val_loss: 0.0292 - val_mae: 0.1382 - val_rmse: 0.1576 - val_smape: 0.2705

Epoch 44/128

1147/1147 - 5s - 5ms/step - ia: 0.7852 - loss: 0.1992 - mae: 0.3156 - rmse: 0.4389 - smape: 0.5301 - val_ia: 0.7074 - val_loss: 0.0322 - val_mae: 0.1468 - val_rmse: 0.1656 - val_smape: 0.2662

Epoch 45/128

1147/1147 - 4s - 4ms/step - ia: 0.7888 - loss: 0.1934 - mae: 0.3109 - rmse: 0.4335 - smape: 0.5201 - val_ia: 0.6948 - val_loss: 0.0374 - val_mae: 0.1590 - val_rmse: 0.1775 - val_smape: 0.3012

Epoch 46/128

1147/1147 - 3s - 3ms/step - ia: 0.7864 - loss: 0.1972 - mae: 0.3138 - rmse: 0.4375 - smape: 0.5211 - val_ia: 0.6564 - val_loss: 0.0506 - val_mae: 0.1859 - val_rmse: 0.2069 - val_smape: 0.3259

Epoch 47/128

1147/1147 - 4s - 3ms/step - ia: 0.7880 - loss: 0.1967 - mae: 0.3126 - rmse: 0.4367 - smape: 0.5188 - val_ia: 0.6721 - val_loss: 0.0434 - val_mae: 0.1714 - val_rmse: 0.1917 - val_smape: 0.3039

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 32s 200ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  2%|▏         | 1/50 [03:31<2:52:22, 211.08s/trial, best loss: 0.02281952228125499]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 7s - 47ms/step - ia: 0.8887 - loss: 0.0827 - mae: 0.1702 - rmse: 0.2299 - smape: 0.4036 - val_ia: 0.9339 - val_loss: 0.0145 - val_mae: 0.0873 - val_rmse: 0.1195 - val_smape: 0.2309

Epoch 2/16

144/144 - 1s - 5ms/step - ia: 0.9614 - loss: 0.0083 - mae: 0.0638 - rmse: 0.0900 - smape: 0.1998 - val_ia: 0.9375 - val_loss: 0.0123 - val_mae: 0.0832 - val_rmse: 0.1087 - val_smape: 0.2162

Epoch 3/16

144/144 - 1s - 4ms/step - ia: 0.9672 - loss: 0.0061 - mae: 0.0542 - rmse: 0.0772 - smape: 0.1783 - val_ia: 0.9448 - val_loss: 0.0102 - val_mae: 0.0741 - val_rmse: 0.0992 - val_smape: 0.2051

Epoch 4/16

144/144 - 1s - 4ms/step - ia: 0.9688 - loss: 0.0054 - mae: 0.0514 - rmse: 0.0730 - smape: 0.1709 - val_ia: 0.9483 - val_loss: 0.0091 - val_mae: 0.0695 - val_rmse: 0.0935 - val_smape: 0.1960

Epoch 5/16

144/144 - 1s - 4ms/step - ia: 0.9709 - loss: 0.0048 - mae: 0.0480 - rmse: 0.0685 - smape: 0.1632 - val_ia: 0.9461 - val_loss: 0.0093 - val_mae: 0.0726 - val_rmse: 0.0955 - val_smape: 0.2078

Epoch 6/16

144/144 - 1s - 5ms/step - ia: 0.9721 - loss: 0.0045 - mae: 0.0462 - rmse: 0.0659 - smape: 0.1582 - val_ia: 0.9508 - val_loss: 0.0083 - val_mae: 0.0658 - val_rmse: 0.0888 - val_smape: 0.1875

Epoch 7/16

144/144 - 1s - 5ms/step - ia: 0.9731 - loss: 0.0042 - mae: 0.0445 - rmse: 0.0635 - smape: 0.1534 - val_ia: 0.9488 - val_loss: 0.0087 - val_mae: 0.0684 - val_rmse: 0.0904 - val_smape: 0.1924

Epoch 8/16

144/144 - 1s - 4ms/step - ia: 0.9739 - loss: 0.0040 - mae: 0.0431 - rmse: 0.0617 - smape: 0.1519 - val_ia: 0.9517 - val_loss: 0.0074 - val_mae: 0.0641 - val_rmse: 0.0848 - val_smape: 0.1795

Epoch 9/16

144/144 - 1s - 5ms/step - ia: 0.9733 - loss: 0.0040 - mae: 0.0440 - rmse: 0.0623 - smape: 0.1504 - val_ia: 0.9471 - val_loss: 0.0091 - val_mae: 0.0706 - val_rmse: 0.0925 - val_smape: 0.2086

Epoch 10/16

144/144 - 1s - 4ms/step - ia: 0.9749 - loss: 0.0037 - mae: 0.0416 - rmse: 0.0594 - smape: 0.1457 - val_ia: 0.9502 - val_loss: 0.0078 - val_mae: 0.0658 - val_rmse: 0.0864 - val_smape: 0.1836

Epoch 11/16

144/144 - 1s - 5ms/step - ia: 0.9745 - loss: 0.0037 - mae: 0.0421 - rmse: 0.0597 - smape: 0.1462 - val_ia: 0.9557 - val_loss: 0.0065 - val_mae: 0.0588 - val_rmse: 0.0787 - val_smape: 0.1730

Epoch 12/16

144/144 - 1s - 4ms/step - ia: 0.9756 - loss: 0.0035 - mae: 0.0403 - rmse: 0.0577 - smape: 0.1431 - val_ia: 0.9543 - val_loss: 0.0069 - val_mae: 0.0612 - val_rmse: 0.0813 - val_smape: 0.1858

Epoch 13/16

144/144 - 1s - 5ms/step - ia: 0.9758 - loss: 0.0034 - mae: 0.0400 - rmse: 0.0570 - smape: 0.1418 - val_ia: 0.9536 - val_loss: 0.0071 - val_mae: 0.0618 - val_rmse: 0.0815 - val_smape: 0.1792

Epoch 14/16

144/144 - 1s - 5ms/step - ia: 0.9760 - loss: 0.0034 - mae: 0.0396 - rmse: 0.0566 - smape: 0.1400 - val_ia: 0.9557 - val_loss: 0.0065 - val_mae: 0.0594 - val_rmse: 0.0787 - val_smape: 0.1816

Epoch 15/16

144/144 - 1s - 5ms/step - ia: 0.9759 - loss: 0.0034 - mae: 0.0398 - rmse: 0.0566 - smape: 0.1404 - val_ia: 0.9560 - val_loss: 0.0064 - val_mae: 0.0585 - val_rmse: 0.0777 - val_smape: 0.1736

Epoch 16/16

144/144 - 1s - 10ms/step - ia: 0.9765 - loss: 0.0033 - mae: 0.0389 - rmse: 0.0556 - smape: 0.1379 - val_ia: 0.9575 - val_loss: 0.0059 - val_mae: 0.0562 - val_rmse: 0.0752 - val_smape: 0.1669

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 26s 166ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  4%|▍         | 2/50 [03:50<1:18:39, 98.32s/trial, best loss: 0.01020940085001529]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

574/574 - 6s - 10ms/step - ia: 0.2283 - loss: 1.1567 - mae: 0.8671 - rmse: 1.0699 - smape: 1.5855 - val_ia: 0.2742 - val_loss: 1.0798 - val_mae: 0.8130 - val_rmse: 0.9854 - val_smape: 1.4144

Epoch 2/8

574/574 - 1s - 2ms/step - ia: 0.2487 - loss: 1.1056 - mae: 0.8467 - rmse: 1.0476 - smape: 1.5710 - val_ia: 0.2845 - val_loss: 1.0265 - val_mae: 0.7912 - val_rmse: 0.9604 - val_smape: 1.3987

Epoch 3/8

574/574 - 3s - 5ms/step - ia: 0.2609 - loss: 1.0627 - mae: 0.8316 - rmse: 1.0268 - smape: 1.5614 - val_ia: 0.2952 - val_loss: 0.9785 - val_mae: 0.7709 - val_rmse: 0.9371 - val_smape: 1.3827

Epoch 4/8

574/574 - 3s - 5ms/step - ia: 0.2768 - loss: 1.0307 - mae: 0.8179 - rmse: 1.0114 - smape: 1.5499 - val_ia: 0.3068 - val_loss: 0.9351 - val_mae: 0.7518 - val_rmse: 0.9153 - val_smape: 1.3671

Epoch 5/8

574/574 - 2s - 3ms/step - ia: 0.2925 - loss: 0.9978 - mae: 0.8042 - rmse: 0.9946 - smape: 1.5375 - val_ia: 0.3184 - val_loss: 0.8963 - val_mae: 0.7342 - val_rmse: 0.8953 - val_smape: 1.3523

Epoch 6/8

574/574 - 3s - 5ms/step - ia: 0.3072 - loss: 0.9685 - mae: 0.7902 - rmse: 0.9800 - smape: 1.5258 - val_ia: 0.3300 - val_loss: 0.8611 - val_mae: 0.7177 - val_rmse: 0.8766 - val_smape: 1.3385

Epoch 7/8

574/574 - 2s - 3ms/step - ia: 0.3156 - loss: 0.9542 - mae: 0.7828 - rmse: 0.9731 - smape: 1.5217 - val_ia: 0.3412 - val_loss: 0.8290 - val_mae: 0.7025 - val_rmse: 0.8593 - val_smape: 1.3265

Epoch 8/8

574/574 - 2s - 4ms/step - ia: 0.3283 - loss: 0.9321 - mae: 0.7728 - rmse: 0.9622 - smape: 1.5151 - val_ia: 0.3517 - val_loss: 0.8003 - val_mae: 0.6886 - val_rmse: 0.8435 - val_smape: 1.3159

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 11s 68ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/32

  6%|▌         | 3/50 [04:12<49:48, 63.59s/trial, best loss: 0.01020940085001529]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 3s - 10ms/step - ia: 0.4571 - loss: 1.2360 - mae: 0.8846 - rmse: 1.1084 - smape: 1.2313 - val_ia: 0.6685 - val_loss: 0.3441 - val_mae: 0.4684 - val_rmse: 0.5776 - val_smape: 0.8626

Epoch 2/32

287/287 - 1s - 2ms/step - ia: 0.5368 - loss: 1.0180 - mae: 0.7998 - rmse: 1.0066 - smape: 1.1086 - val_ia: 0.7124 - val_loss: 0.2898 - val_mae: 0.4321 - val_rmse: 0.5323 - val_smape: 0.7906

Epoch 3/32

287/287 - 1s - 2ms/step - ia: 0.5687 - loss: 0.8980 - mae: 0.7532 - rmse: 0.9452 - smape: 1.0575 - val_ia: 0.7347 - val_loss: 0.2530 - val_mae: 0.4072 - val_rmse: 0.4988 - val_smape: 0.7623

Epoch 4/32

287/287 - 1s - 2ms/step - ia: 0.5858 - loss: 0.8347 - mae: 0.7224 - rmse: 0.9113 - smape: 1.0276 - val_ia: 0.7494 - val_loss: 0.2273 - val_mae: 0.3886 - val_rmse: 0.4735 - val_smape: 0.7423

Epoch 5/32

287/287 - 1s - 2ms/step - ia: 0.5981 - loss: 0.7771 - mae: 0.6993 - rmse: 0.8796 - smape: 1.0109 - val_ia: 0.7615 - val_loss: 0.2045 - val_mae: 0.3698 - val_rmse: 0.4492 - val_smape: 0.7220

Epoch 6/32

287/287 - 1s - 3ms/step - ia: 0.6100 - loss: 0.7286 - mae: 0.6773 - rmse: 0.8518 - smape: 0.9879 - val_ia: 0.7737 - val_loss: 0.1816 - val_mae: 0.3488 - val_rmse: 0.4230 - val_smape: 0.6993

Epoch 7/32

287/287 - 1s - 4ms/step - ia: 0.6188 - loss: 0.6939 - mae: 0.6598 - rmse: 0.8312 - smape: 0.9742 - val_ia: 0.7819 - val_loss: 0.1677 - val_mae: 0.3360 - val_rmse: 0.4063 - val_smape: 0.6853

Epoch 8/32

287/287 - 1s - 4ms/step - ia: 0.6289 - loss: 0.6549 - mae: 0.6421 - rmse: 0.8073 - smape: 0.9598 - val_ia: 0.7910 - val_loss: 0.1522 - val_mae: 0.3198 - val_rmse: 0.3866 - val_smape: 0.6692

Epoch 9/32

287/287 - 1s - 4ms/step - ia: 0.6366 - loss: 0.6214 - mae: 0.6244 - rmse: 0.7863 - smape: 0.9465 - val_ia: 0.7939 - val_loss: 0.1483 - val_mae: 0.3172 - val_rmse: 0.3817 - val_smape: 0.6640

Epoch 10/32

287/287 - 2s - 6ms/step - ia: 0.6441 - loss: 0.5937 - mae: 0.6111 - rmse: 0.7690 - smape: 0.9321 - val_ia: 0.8007 - val_loss: 0.1373 - val_mae: 0.3053 - val_rmse: 0.3669 - val_smape: 0.6523

Epoch 11/32

287/287 - 2s - 9ms/step - ia: 0.6549 - loss: 0.5577 - mae: 0.5908 - rmse: 0.7451 - smape: 0.9164 - val_ia: 0.8068 - val_loss: 0.1278 - val_mae: 0.2949 - val_rmse: 0.3538 - val_smape: 0.6415

Epoch 12/32

287/287 - 1s - 5ms/step - ia: 0.6577 - loss: 0.5455 - mae: 0.5842 - rmse: 0.7369 - smape: 0.9090 - val_ia: 0.8095 - val_loss: 0.1238 - val_mae: 0.2909 - val_rmse: 0.3483 - val_smape: 0.6367

Epoch 13/32

287/287 - 1s - 4ms/step - ia: 0.6656 - loss: 0.5184 - mae: 0.5698 - rmse: 0.7184 - smape: 0.8985 - val_ia: 0.8158 - val_loss: 0.1147 - val_mae: 0.2794 - val_rmse: 0.3349 - val_smape: 0.6260

Epoch 14/32

287/287 - 1s - 4ms/step - ia: 0.6686 - loss: 0.5053 - mae: 0.5627 - rmse: 0.7096 - smape: 0.8893 - val_ia: 0.8186 - val_loss: 0.1108 - val_mae: 0.2751 - val_rmse: 0.3292 - val_smape: 0.6203

Epoch 15/32

287/287 - 1s - 5ms/step - ia: 0.6744 - loss: 0.4838 - mae: 0.5511 - rmse: 0.6941 - smape: 0.8825 - val_ia: 0.8222 - val_loss: 0.1059 - val_mae: 0.2695 - val_rmse: 0.3221 - val_smape: 0.6129

Epoch 16/32

287/287 - 2s - 5ms/step - ia: 0.6823 - loss: 0.4641 - mae: 0.5383 - rmse: 0.6798 - smape: 0.8646 - val_ia: 0.8240 - val_loss: 0.1036 - val_mae: 0.2669 - val_rmse: 0.3186 - val_smape: 0.6082

Epoch 17/32

287/287 - 1s - 4ms/step - ia: 0.6863 - loss: 0.4497 - mae: 0.5302 - rmse: 0.6692 - smape: 0.8619 - val_ia: 0.8279 - val_loss: 0.0986 - val_mae: 0.2603 - val_rmse: 0.3109 - val_smape: 0.5997

Epoch 18/32

287/287 - 1s - 3ms/step - ia: 0.6897 - loss: 0.4395 - mae: 0.5235 - rmse: 0.6614 - smape: 0.8528 - val_ia: 0.8306 - val_loss: 0.0952 - val_mae: 0.2559 - val_rmse: 0.3055 - val_smape: 0.5929

Epoch 19/32

287/287 - 1s - 3ms/step - ia: 0.6921 - loss: 0.4318 - mae: 0.5183 - rmse: 0.6557 - smape: 0.8462 - val_ia: 0.8342 - val_loss: 0.0908 - val_mae: 0.2498 - val_rmse: 0.2985 - val_smape: 0.5837

Epoch 20/32

287/287 - 1s - 3ms/step - ia: 0.7000 - loss: 0.4134 - mae: 0.5059 - rmse: 0.6415 - smape: 0.8365 - val_ia: 0.8378 - val_loss: 0.0865 - val_mae: 0.2435 - val_rmse: 0.2913 - val_smape: 0.5750

Epoch 21/32

287/287 - 1s - 3ms/step - ia: 0.6995 - loss: 0.4062 - mae: 0.5040 - rmse: 0.6355 - smape: 0.8350 - val_ia: 0.8396 - val_loss: 0.0845 - val_mae: 0.2409 - val_rmse: 0.2883 - val_smape: 0.5679

Epoch 22/32

287/287 - 1s - 3ms/step - ia: 0.7038 - loss: 0.3949 - mae: 0.4969 - rmse: 0.6270 - smape: 0.8258 - val_ia: 0.8425 - val_loss: 0.0813 - val_mae: 0.2362 - val_rmse: 0.2829 - val_smape: 0.5594

Epoch 23/32

287/287 - 1s - 4ms/step - ia: 0.7081 - loss: 0.3839 - mae: 0.4887 - rmse: 0.6184 - smape: 0.8228 - val_ia: 0.8426 - val_loss: 0.0814 - val_mae: 0.2366 - val_rmse: 0.2832 - val_smape: 0.5558

Epoch 24/32

287/287 - 1s - 5ms/step - ia: 0.7123 - loss: 0.3740 - mae: 0.4818 - rmse: 0.6099 - smape: 0.8099 - val_ia: 0.8461 - val_loss: 0.0775 - val_mae: 0.2305 - val_rmse: 0.2764 - val_smape: 0.5453

Epoch 25/32

287/287 - 1s - 4ms/step - ia: 0.7155 - loss: 0.3645 - mae: 0.4757 - rmse: 0.6023 - smape: 0.8056 - val_ia: 0.8510 - val_loss: 0.0723 - val_mae: 0.2220 - val_rmse: 0.2670 - val_smape: 0.5325

Epoch 26/32

287/287 - 1s - 5ms/step - ia: 0.7176 - loss: 0.3572 - mae: 0.4708 - rmse: 0.5963 - smape: 0.7988 - val_ia: 0.8494 - val_loss: 0.0744 - val_mae: 0.2256 - val_rmse: 0.2708 - val_smape: 0.5313

Epoch 27/32

287/287 - 1s - 5ms/step - ia: 0.7224 - loss: 0.3474 - mae: 0.4636 - rmse: 0.5880 - smape: 0.7887 - val_ia: 0.8537 - val_loss: 0.0698 - val_mae: 0.2181 - val_rmse: 0.2625 - val_smape: 0.5212

Epoch 28/32

287/287 - 1s - 5ms/step - ia: 0.7238 - loss: 0.3425 - mae: 0.4596 - rmse: 0.5838 - smape: 0.7849 - val_ia: 0.8563 - val_loss: 0.0674 - val_mae: 0.2139 - val_rmse: 0.2579 - val_smape: 0.5118

Epoch 29/32

287/287 - 1s - 5ms/step - ia: 0.7285 - loss: 0.3310 - mae: 0.4519 - rmse: 0.5739 - smape: 0.7802 - val_ia: 0.8576 - val_loss: 0.0664 - val_mae: 0.2121 - val_rmse: 0.2560 - val_smape: 0.5045

Epoch 30/32

287/287 - 1s - 4ms/step - ia: 0.7309 - loss: 0.3243 - mae: 0.4477 - rmse: 0.5683 - smape: 0.7702 - val_ia: 0.8588 - val_loss: 0.0658 - val_mae: 0.2108 - val_rmse: 0.2548 - val_smape: 0.4958

Epoch 31/32

287/287 - 1s - 4ms/step - ia: 0.7342 - loss: 0.3160 - mae: 0.4424 - rmse: 0.5608 - smape: 0.7639 - val_ia: 0.8637 - val_loss: 0.0613 - val_mae: 0.2023 - val_rmse: 0.2458 - val_smape: 0.4813

Epoch 32/32

287/287 - 1s - 4ms/step - ia: 0.7353 - loss: 0.3149 - mae: 0.4406 - rmse: 0.5599 - smape: 0.7634 - val_ia: 0.8643 - val_loss: 0.0608 - val_mae: 0.2016 - val_rmse: 0.2449 - val_smape: 0.4775

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 21s 131ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

  8%|▊         | 4/50 [04:53<41:45, 54.47s/trial, best loss: 0.01020940085001529]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4586/4586 - 18s - 4ms/step - ia: 0.2531 - loss: 1.1493 - mae: 0.8833 - rmse: 1.0474 - smape: 1.5457 - val_ia: 0.1441 - val_loss: 0.8168 - val_mae: 0.7497 - val_rmse: 0.7670 - val_smape: 1.7825

Epoch 2/64

4586/4586 - 20s - 4ms/step - ia: 0.2891 - loss: 1.0236 - mae: 0.8321 - rmse: 0.9881 - smape: 1.4779 - val_ia: 0.1520 - val_loss: 0.7247 - val_mae: 0.7050 - val_rmse: 0.7219 - val_smape: 1.5834

Epoch 3/64

4586/4586 - 12s - 3ms/step - ia: 0.3296 - loss: 0.9184 - mae: 0.7849 - rmse: 0.9355 - smape: 1.3995 - val_ia: 0.1584 - val_loss: 0.6410 - val_mae: 0.6618 - val_rmse: 0.6780 - val_smape: 1.4184

Epoch 4/64

4586/4586 - 19s - 4ms/step - ia: 0.3658 - loss: 0.8284 - mae: 0.7445 - rmse: 0.8877 - smape: 1.3314 - val_ia: 0.1625 - val_loss: 0.5656 - val_mae: 0.6200 - val_rmse: 0.6356 - val_smape: 1.2802

Epoch 5/64

4586/4586 - 21s - 5ms/step - ia: 0.4103 - loss: 0.7365 - mae: 0.6971 - rmse: 0.8359 - smape: 1.2503 - val_ia: 0.1677 - val_loss: 0.4992 - val_mae: 0.5803 - val_rmse: 0.5956 - val_smape: 1.1624

Epoch 6/64

4586/4586 - 10s - 2ms/step - ia: 0.4456 - loss: 0.6738 - mae: 0.6653 - rmse: 0.7985 - smape: 1.1881 - val_ia: 0.1748 - val_loss: 0.4439 - val_mae: 0.5448 - val_rmse: 0.5600 - val_smape: 1.0645

Epoch 7/64

4586/4586 - 13s - 3ms/step - ia: 0.4795 - loss: 0.6153 - mae: 0.6334 - rmse: 0.7622 - smape: 1.1309 - val_ia: 0.1840 - val_loss: 0.3981 - val_mae: 0.5130 - val_rmse: 0.5285 - val_smape: 0.9837

Epoch 8/64

4586/4586 - 14s - 3ms/step - ia: 0.5084 - loss: 0.5705 - mae: 0.6066 - rmse: 0.7336 - smape: 1.0785 - val_ia: 0.1938 - val_loss: 0.3614 - val_mae: 0.4858 - val_rmse: 0.5018 - val_smape: 0.9193

Epoch 9/64

4586/4586 - 13s - 3ms/step - ia: 0.5333 - loss: 0.5327 - mae: 0.5865 - rmse: 0.7081 - smape: 1.0392 - val_ia: 0.2012 - val_loss: 0.3317 - val_mae: 0.4624 - val_rmse: 0.4789 - val_smape: 0.8682

Epoch 10/64

4586/4586 - 11s - 2ms/step - ia: 0.5579 - loss: 0.4977 - mae: 0.5632 - rmse: 0.6837 - smape: 0.9930 - val_ia: 0.2090 - val_loss: 0.3084 - val_mae: 0.4431 - val_rmse: 0.4601 - val_smape: 0.8286

Epoch 11/64

4586/4586 - 18s - 4ms/step - ia: 0.5782 - loss: 0.4659 - mae: 0.5450 - rmse: 0.6616 - smape: 0.9610 - val_ia: 0.2168 - val_loss: 0.2896 - val_mae: 0.4268 - val_rmse: 0.4443 - val_smape: 0.7971

Epoch 12/64

4586/4586 - 13s - 3ms/step - ia: 0.5948 - loss: 0.4455 - mae: 0.5309 - rmse: 0.6464 - smape: 0.9336 - val_ia: 0.2228 - val_loss: 0.2741 - val_mae: 0.4129 - val_rmse: 0.4307 - val_smape: 0.7719

Epoch 13/64

4586/4586 - 20s - 4ms/step - ia: 0.6096 - loss: 0.4265 - mae: 0.5197 - rmse: 0.6327 - smape: 0.9064 - val_ia: 0.2272 - val_loss: 0.2613 - val_mae: 0.4013 - val_rmse: 0.4192 - val_smape: 0.7523

Epoch 14/64

4586/4586 - 18s - 4ms/step - ia: 0.6229 - loss: 0.4064 - mae: 0.5062 - rmse: 0.6168 - smape: 0.8842 - val_ia: 0.2330 - val_loss: 0.2509 - val_mae: 0.3921 - val_rmse: 0.4101 - val_smape: 0.7369

Epoch 15/64

4586/4586 - 11s - 2ms/step - ia: 0.6349 - loss: 0.3893 - mae: 0.4951 - rmse: 0.6043 - smape: 0.8643 - val_ia: 0.2368 - val_loss: 0.2419 - val_mae: 0.3845 - val_rmse: 0.4024 - val_smape: 0.7252

Epoch 16/64

4586/4586 - 10s - 2ms/step - ia: 0.6453 - loss: 0.3755 - mae: 0.4834 - rmse: 0.5920 - smape: 0.8455 - val_ia: 0.2386 - val_loss: 0.2338 - val_mae: 0.3780 - val_rmse: 0.3957 - val_smape: 0.7151

Epoch 17/64

4586/4586 - 13s - 3ms/step - ia: 0.6511 - loss: 0.3684 - mae: 0.4792 - rmse: 0.5867 - smape: 0.8364 - val_ia: 0.2401 - val_loss: 0.2255 - val_mae: 0.3713 - val_rmse: 0.3889 - val_smape: 0.7057

Epoch 18/64

4586/4586 - 16s - 4ms/step - ia: 0.6617 - loss: 0.3498 - mae: 0.4672 - rmse: 0.5713 - smape: 0.8181 - val_ia: 0.2419 - val_loss: 0.2187 - val_mae: 0.3661 - val_rmse: 0.3836 - val_smape: 0.6985

Epoch 19/64

4586/4586 - 12s - 3ms/step - ia: 0.6695 - loss: 0.3394 - mae: 0.4594 - rmse: 0.5629 - smape: 0.8045 - val_ia: 0.2434 - val_loss: 0.2116 - val_mae: 0.3608 - val_rmse: 0.3781 - val_smape: 0.6913

Epoch 20/64

4586/4586 - 19s - 4ms/step - ia: 0.6767 - loss: 0.3278 - mae: 0.4503 - rmse: 0.5525 - smape: 0.7919 - val_ia: 0.2452 - val_loss: 0.2050 - val_mae: 0.3559 - val_rmse: 0.3730 - val_smape: 0.6848

Epoch 21/64

4586/4586 - 10s - 2ms/step - ia: 0.6839 - loss: 0.3172 - mae: 0.4434 - rmse: 0.5439 - smape: 0.7790 - val_ia: 0.2484 - val_loss: 0.1985 - val_mae: 0.3510 - val_rmse: 0.3678 - val_smape: 0.6780

Epoch 22/64

4586/4586 - 12s - 3ms/step - ia: 0.6904 - loss: 0.3039 - mae: 0.4334 - rmse: 0.5313 - smape: 0.7653 - val_ia: 0.2514 - val_loss: 0.1919 - val_mae: 0.3458 - val_rmse: 0.3624 - val_smape: 0.6712

Epoch 23/64

4586/4586 - 12s - 3ms/step - ia: 0.6936 - loss: 0.2996 - mae: 0.4302 - rmse: 0.5284 - smape: 0.7612 - val_ia: 0.2541 - val_loss: 0.1852 - val_mae: 0.3405 - val_rmse: 0.3568 - val_smape: 0.6645

Epoch 24/64

4586/4586 - 10s - 2ms/step - ia: 0.6994 - loss: 0.2897 - mae: 0.4227 - rmse: 0.5188 - smape: 0.7515 - val_ia: 0.2563 - val_loss: 0.1791 - val_mae: 0.3357 - val_rmse: 0.3517 - val_smape: 0.6577

Epoch 25/64

4586/4586 - 12s - 3ms/step - ia: 0.7037 - loss: 0.2823 - mae: 0.4166 - rmse: 0.5125 - smape: 0.7438 - val_ia: 0.2587 - val_loss: 0.1731 - val_mae: 0.3309 - val_rmse: 0.3465 - val_smape: 0.6512

Epoch 26/64

4586/4586 - 21s - 5ms/step - ia: 0.7087 - loss: 0.2760 - mae: 0.4117 - rmse: 0.5059 - smape: 0.7357 - val_ia: 0.2616 - val_loss: 0.1659 - val_mae: 0.3247 - val_rmse: 0.3400 - val_smape: 0.6432

Epoch 27/64

4586/4586 - 20s - 4ms/step - ia: 0.7133 - loss: 0.2668 - mae: 0.4069 - rmse: 0.4980 - smape: 0.7262 - val_ia: 0.2650 - val_loss: 0.1602 - val_mae: 0.3199 - val_rmse: 0.3350 - val_smape: 0.6363

Epoch 28/64

4586/4586 - 16s - 3ms/step - ia: 0.7175 - loss: 0.2593 - mae: 0.4000 - rmse: 0.4907 - smape: 0.7194 - val_ia: 0.2684 - val_loss: 0.1544 - val_mae: 0.3148 - val_rmse: 0.3296 - val_smape: 0.6297

Epoch 29/64

4586/4586 - 7s - 2ms/step - ia: 0.7246 - loss: 0.2485 - mae: 0.3900 - rmse: 0.4800 - smape: 0.7037 - val_ia: 0.2719 - val_loss: 0.1479 - val_mae: 0.3088 - val_rmse: 0.3234 - val_smape: 0.6217

Epoch 30/64

4586/4586 - 16s - 3ms/step - ia: 0.7280 - loss: 0.2457 - mae: 0.3877 - rmse: 0.4772 - smape: 0.7008 - val_ia: 0.2751 - val_loss: 0.1424 - val_mae: 0.3039 - val_rmse: 0.3183 - val_smape: 0.6151

Epoch 31/64

4586/4586 - 17s - 4ms/step - ia: 0.7285 - loss: 0.2418 - mae: 0.3850 - rmse: 0.4735 - smape: 0.6975 - val_ia: 0.2785 - val_loss: 0.1368 - val_mae: 0.2985 - val_rmse: 0.3127 - val_smape: 0.6079

Epoch 32/64

4586/4586 - 8s - 2ms/step - ia: 0.7320 - loss: 0.2381 - mae: 0.3815 - rmse: 0.4700 - smape: 0.6901 - val_ia: 0.2821 - val_loss: 0.1312 - val_mae: 0.2928 - val_rmse: 0.3068 - val_smape: 0.6002

Epoch 33/64

4586/4586 - 12s - 3ms/step - ia: 0.7363 - loss: 0.2307 - mae: 0.3763 - rmse: 0.4627 - smape: 0.6848 - val_ia: 0.2849 - val_loss: 0.1265 - val_mae: 0.2882 - val_rmse: 0.3020 - val_smape: 0.5942

Epoch 34/64

4586/4586 - 41s - 9ms/step - ia: 0.7391 - loss: 0.2275 - mae: 0.3729 - rmse: 0.4592 - smape: 0.6759 - val_ia: 0.2874 - val_loss: 0.1220 - val_mae: 0.2836 - val_rmse: 0.2972 - val_smape: 0.5881

Epoch 35/64

4586/4586 - 39s - 8ms/step - ia: 0.7409 - loss: 0.2230 - mae: 0.3699 - rmse: 0.4545 - smape: 0.6732 - val_ia: 0.2907 - val_loss: 0.1169 - val_mae: 0.2781 - val_rmse: 0.2915 - val_smape: 0.5804

Epoch 36/64

4586/4586 - 28s - 6ms/step - ia: 0.7449 - loss: 0.2192 - mae: 0.3648 - rmse: 0.4508 - smape: 0.6654 - val_ia: 0.2932 - val_loss: 0.1118 - val_mae: 0.2725 - val_rmse: 0.2858 - val_smape: 0.5724

Epoch 37/64

4586/4586 - 18s - 4ms/step - ia: 0.7457 - loss: 0.2167 - mae: 0.3640 - rmse: 0.4478 - smape: 0.6640 - val_ia: 0.2966 - val_loss: 0.1073 - val_mae: 0.2673 - val_rmse: 0.2804 - val_smape: 0.5644

Epoch 38/64

4586/4586 - 30s - 7ms/step - ia: 0.7480 - loss: 0.2121 - mae: 0.3608 - rmse: 0.4440 - smape: 0.6587 - val_ia: 0.3010 - val_loss: 0.1018 - val_mae: 0.2601 - val_rmse: 0.2732 - val_smape: 0.5526

Epoch 39/64

4586/4586 - 27s - 6ms/step - ia: 0.7514 - loss: 0.2110 - mae: 0.3588 - rmse: 0.4421 - smape: 0.6551 - val_ia: 0.3049 - val_loss: 0.0974 - val_mae: 0.2545 - val_rmse: 0.2674 - val_smape: 0.5434

Epoch 40/64

4586/4586 - 40s - 9ms/step - ia: 0.7544 - loss: 0.2033 - mae: 0.3524 - rmse: 0.4339 - smape: 0.6492 - val_ia: 0.3081 - val_loss: 0.0938 - val_mae: 0.2497 - val_rmse: 0.2626 - val_smape: 0.5353

Epoch 41/64

4586/4586 - 24s - 5ms/step - ia: 0.7542 - loss: 0.2021 - mae: 0.3517 - rmse: 0.4326 - smape: 0.6449 - val_ia: 0.3114 - val_loss: 0.0902 - val_mae: 0.2448 - val_rmse: 0.2576 - val_smape: 0.5265

Epoch 42/64

4586/4586 - 46s - 10ms/step - ia: 0.7578 - loss: 0.1968 - mae: 0.3470 - rmse: 0.4267 - smape: 0.6400 - val_ia: 0.3147 - val_loss: 0.0868 - val_mae: 0.2401 - val_rmse: 0.2528 - val_smape: 0.5179

Epoch 43/64

4586/4586 - 22s - 5ms/step - ia: 0.7591 - loss: 0.1957 - mae: 0.3464 - rmse: 0.4257 - smape: 0.6362 - val_ia: 0.3189 - val_loss: 0.0832 - val_mae: 0.2346 - val_rmse: 0.2473 - val_smape: 0.5077

Epoch 44/64

4586/4586 - 55s - 12ms/step - ia: 0.7611 - loss: 0.1958 - mae: 0.3450 - rmse: 0.4256 - smape: 0.6357 - val_ia: 0.3211 - val_loss: 0.0810 - val_mae: 0.2315 - val_rmse: 0.2442 - val_smape: 0.5014

Epoch 45/64

4586/4586 - 22s - 5ms/step - ia: 0.7626 - loss: 0.1902 - mae: 0.3401 - rmse: 0.4189 - smape: 0.6299 - val_ia: 0.3249 - val_loss: 0.0779 - val_mae: 0.2268 - val_rmse: 0.2394 - val_smape: 0.4918

Epoch 46/64

4586/4586 - 27s - 6ms/step - ia: 0.7650 - loss: 0.1865 - mae: 0.3386 - rmse: 0.4158 - smape: 0.6276 - val_ia: 0.3288 - val_loss: 0.0750 - val_mae: 0.2219 - val_rmse: 0.2345 - val_smape: 0.4816

Epoch 47/64

4586/4586 - 10s - 2ms/step - ia: 0.7664 - loss: 0.1839 - mae: 0.3351 - rmse: 0.4126 - smape: 0.6208 - val_ia: 0.3318 - val_loss: 0.0727 - val_mae: 0.2182 - val_rmse: 0.2308 - val_smape: 0.4735

Epoch 48/64

4586/4586 - 17s - 4ms/step - ia: 0.7666 - loss: 0.1855 - mae: 0.3375 - rmse: 0.4144 - smape: 0.6262 - val_ia: 0.3347 - val_loss: 0.0708 - val_mae: 0.2150 - val_rmse: 0.2276 - val_smape: 0.4661

Epoch 49/64

4586/4586 - 21s - 5ms/step - ia: 0.7682 - loss: 0.1842 - mae: 0.3338 - rmse: 0.4118 - smape: 0.6184 - val_ia: 0.3379 - val_loss: 0.0687 - val_mae: 0.2113 - val_rmse: 0.2239 - val_smape: 0.4573

Epoch 50/64

4586/4586 - 25s - 5ms/step - ia: 0.7684 - loss: 0.1827 - mae: 0.3340 - rmse: 0.4110 - smape: 0.6211 - val_ia: 0.3422 - val_loss: 0.0666 - val_mae: 0.2072 - val_rmse: 0.2198 - val_smape: 0.4471

Epoch 51/64

4586/4586 - 27s - 6ms/step - ia: 0.7709 - loss: 0.1789 - mae: 0.3298 - rmse: 0.4061 - smape: 0.6166 - val_ia: 0.3454 - val_loss: 0.0650 - val_mae: 0.2041 - val_rmse: 0.2167 - val_smape: 0.4388

Epoch 52/64

4586/4586 - 10s - 2ms/step - ia: 0.7726 - loss: 0.1787 - mae: 0.3292 - rmse: 0.4066 - smape: 0.6123 - val_ia: 0.3496 - val_loss: 0.0629 - val_mae: 0.2000 - val_rmse: 0.2126 - val_smape: 0.4276

Epoch 53/64

4586/4586 - 16s - 4ms/step - ia: 0.7720 - loss: 0.1757 - mae: 0.3276 - rmse: 0.4035 - smape: 0.6122 - val_ia: 0.3533 - val_loss: 0.0614 - val_mae: 0.1968 - val_rmse: 0.2094 - val_smape: 0.4186

Epoch 54/64

4586/4586 - 19s - 4ms/step - ia: 0.7765 - loss: 0.1707 - mae: 0.3222 - rmse: 0.3972 - smape: 0.6051 - val_ia: 0.3571 - val_loss: 0.0600 - val_mae: 0.1938 - val_rmse: 0.2064 - val_smape: 0.4099

Epoch 55/64

4586/4586 - 15s - 3ms/step - ia: 0.7764 - loss: 0.1709 - mae: 0.3227 - rmse: 0.3977 - smape: 0.6054 - val_ia: 0.3603 - val_loss: 0.0588 - val_mae: 0.1913 - val_rmse: 0.2039 - val_smape: 0.4026

Epoch 56/64

4586/4586 - 14s - 3ms/step - ia: 0.7783 - loss: 0.1677 - mae: 0.3192 - rmse: 0.3938 - smape: 0.5990 - val_ia: 0.3637 - val_loss: 0.0575 - val_mae: 0.1886 - val_rmse: 0.2012 - val_smape: 0.3949

Epoch 57/64

4586/4586 - 18s - 4ms/step - ia: 0.7788 - loss: 0.1674 - mae: 0.3189 - rmse: 0.3927 - smape: 0.6015 - val_ia: 0.3663 - val_loss: 0.0566 - val_mae: 0.1867 - val_rmse: 0.1993 - val_smape: 0.3895

Epoch 58/64

4586/4586 - 20s - 4ms/step - ia: 0.7803 - loss: 0.1662 - mae: 0.3174 - rmse: 0.3918 - smape: 0.5987 - val_ia: 0.3689 - val_loss: 0.0557 - val_mae: 0.1847 - val_rmse: 0.1973 - val_smape: 0.3837

Epoch 59/64

4586/4586 - 10s - 2ms/step - ia: 0.7825 - loss: 0.1632 - mae: 0.3143 - rmse: 0.3883 - smape: 0.5920 - val_ia: 0.3725 - val_loss: 0.0546 - val_mae: 0.1823 - val_rmse: 0.1949 - val_smape: 0.3766

Epoch 60/64

4586/4586 - 25s - 5ms/step - ia: 0.7848 - loss: 0.1597 - mae: 0.3114 - rmse: 0.3837 - smape: 0.5875 - val_ia: 0.3766 - val_loss: 0.0537 - val_mae: 0.1800 - val_rmse: 0.1926 - val_smape: 0.3700

Epoch 61/64

4586/4586 - 36s - 8ms/step - ia: 0.7823 - loss: 0.1614 - mae: 0.3131 - rmse: 0.3862 - smape: 0.5910 - val_ia: 0.3787 - val_loss: 0.0528 - val_mae: 0.1783 - val_rmse: 0.1909 - val_smape: 0.3651

Epoch 62/64

4586/4586 - 11s - 2ms/step - ia: 0.7838 - loss: 0.1593 - mae: 0.3110 - rmse: 0.3836 - smape: 0.5890 - val_ia: 0.3816 - val_loss: 0.0519 - val_mae: 0.1764 - val_rmse: 0.1890 - val_smape: 0.3595

Epoch 63/64

4586/4586 - 19s - 4ms/step - ia: 0.7855 - loss: 0.1572 - mae: 0.3095 - rmse: 0.3811 - smape: 0.5827 - val_ia: 0.3848 - val_loss: 0.0512 - val_mae: 0.1746 - val_rmse: 0.1872 - val_smape: 0.3544

Epoch 64/64

4586/4586 - 23s - 5ms/step - ia: 0.7868 - loss: 0.1564 - mae: 0.3076 - rmse: 0.3793 - smape: 0.5819 - val_ia: 0.3876 - val_loss: 0.0506 - val_mae: 0.1731 - val_rmse: 0.1856 - val_smape: 0.3498

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:11 442ms/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 10%|█         | 5/50 [25:25<5:59:30, 479.33s/trial, best loss: 0.01020940085001529]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 19s - 17ms/step - ia: 0.3799 - loss: 3.0298 - mae: 1.3157 - rmse: 1.7131 - smape: 1.3254 - val_ia: 0.3484 - val_loss: 0.7430 - val_mae: 0.7094 - val_rmse: 0.7571 - val_smape: 1.0653

Epoch 2/128

1147/1147 - 9s - 8ms/step - ia: 0.4472 - loss: 2.2817 - mae: 1.1464 - rmse: 1.4901 - smape: 1.2281 - val_ia: 0.4228 - val_loss: 0.3721 - val_mae: 0.4975 - val_rmse: 0.5434 - val_smape: 0.9229

Epoch 3/128

1147/1147 - 4s - 3ms/step - ia: 0.4850 - loss: 1.8311 - mae: 1.0255 - rmse: 1.3362 - smape: 1.1704 - val_ia: 0.4840 - val_loss: 0.2133 - val_mae: 0.3784 - val_rmse: 0.4218 - val_smape: 0.8171

Epoch 4/128

1147/1147 - 4s - 3ms/step - ia: 0.5194 - loss: 1.4770 - mae: 0.9246 - rmse: 1.1998 - smape: 1.1174 - val_ia: 0.5304 - val_loss: 0.1380 - val_mae: 0.3085 - val_rmse: 0.3483 - val_smape: 0.7530

Epoch 5/128

1147/1147 - 4s - 3ms/step - ia: 0.5418 - loss: 1.2685 - mae: 0.8576 - rmse: 1.1113 - smape: 1.0851 - val_ia: 0.5689 - val_loss: 0.1008 - val_mae: 0.2630 - val_rmse: 0.3004 - val_smape: 0.6481

Epoch 6/128

1147/1147 - 4s - 4ms/step - ia: 0.5707 - loss: 1.0616 - mae: 0.7872 - rmse: 1.0188 - smape: 1.0376 - val_ia: 0.5955 - val_loss: 0.0866 - val_mae: 0.2400 - val_rmse: 0.2762 - val_smape: 0.5958

Epoch 7/128

1147/1147 - 2s - 2ms/step - ia: 0.5932 - loss: 0.9283 - mae: 0.7335 - rmse: 0.9515 - smape: 1.0034 - val_ia: 0.6180 - val_loss: 0.0787 - val_mae: 0.2242 - val_rmse: 0.2605 - val_smape: 0.5565

Epoch 8/128

1147/1147 - 6s - 5ms/step - ia: 0.6126 - loss: 0.8051 - mae: 0.6856 - rmse: 0.8873 - smape: 0.9685 - val_ia: 0.6459 - val_loss: 0.0678 - val_mae: 0.2050 - val_rmse: 0.2407 - val_smape: 0.5218

Epoch 9/128

1147/1147 - 5s - 5ms/step - ia: 0.6303 - loss: 0.7158 - mae: 0.6471 - rmse: 0.8358 - smape: 0.9431 - val_ia: 0.6540 - val_loss: 0.0631 - val_mae: 0.1977 - val_rmse: 0.2321 - val_smape: 0.5011

Epoch 10/128

1147/1147 - 4s - 4ms/step - ia: 0.6488 - loss: 0.6262 - mae: 0.6061 - rmse: 0.7816 - smape: 0.9141 - val_ia: 0.6679 - val_loss: 0.0579 - val_mae: 0.1883 - val_rmse: 0.2222 - val_smape: 0.4852

Epoch 11/128

1147/1147 - 5s - 5ms/step - ia: 0.6664 - loss: 0.5572 - mae: 0.5705 - rmse: 0.7367 - smape: 0.8807 - val_ia: 0.6847 - val_loss: 0.0509 - val_mae: 0.1755 - val_rmse: 0.2091 - val_smape: 0.4636

Epoch 12/128

1147/1147 - 5s - 4ms/step - ia: 0.6817 - loss: 0.5027 - mae: 0.5411 - rmse: 0.7002 - smape: 0.8566 - val_ia: 0.6907 - val_loss: 0.0475 - val_mae: 0.1695 - val_rmse: 0.2026 - val_smape: 0.4478

Epoch 13/128

1147/1147 - 4s - 4ms/step - ia: 0.6944 - loss: 0.4526 - mae: 0.5134 - rmse: 0.6640 - smape: 0.8359 - val_ia: 0.6975 - val_loss: 0.0438 - val_mae: 0.1627 - val_rmse: 0.1952 - val_smape: 0.4289

Epoch 14/128

1147/1147 - 4s - 4ms/step - ia: 0.7062 - loss: 0.4132 - mae: 0.4909 - rmse: 0.6352 - smape: 0.8127 - val_ia: 0.7056 - val_loss: 0.0410 - val_mae: 0.1570 - val_rmse: 0.1891 - val_smape: 0.4180

Epoch 15/128

1147/1147 - 5s - 4ms/step - ia: 0.7206 - loss: 0.3731 - mae: 0.4644 - rmse: 0.6031 - smape: 0.7850 - val_ia: 0.7061 - val_loss: 0.0399 - val_mae: 0.1556 - val_rmse: 0.1867 - val_smape: 0.4125

Epoch 16/128

1147/1147 - 6s - 6ms/step - ia: 0.7277 - loss: 0.3456 - mae: 0.4480 - rmse: 0.5811 - smape: 0.7735 - val_ia: 0.7147 - val_loss: 0.0370 - val_mae: 0.1494 - val_rmse: 0.1800 - val_smape: 0.4025

Epoch 17/128

1147/1147 - 10s - 9ms/step - ia: 0.7374 - loss: 0.3195 - mae: 0.4311 - rmse: 0.5583 - smape: 0.7541 - val_ia: 0.7225 - val_loss: 0.0345 - val_mae: 0.1434 - val_rmse: 0.1739 - val_smape: 0.3826

Epoch 18/128

1147/1147 - 3s - 3ms/step - ia: 0.7459 - loss: 0.2964 - mae: 0.4149 - rmse: 0.5376 - smape: 0.7411 - val_ia: 0.7270 - val_loss: 0.0324 - val_mae: 0.1394 - val_rmse: 0.1688 - val_smape: 0.3749

Epoch 19/128

1147/1147 - 5s - 4ms/step - ia: 0.7554 - loss: 0.2756 - mae: 0.3991 - rmse: 0.5185 - smape: 0.7192 - val_ia: 0.7388 - val_loss: 0.0297 - val_mae: 0.1321 - val_rmse: 0.1618 - val_smape: 0.3572

Epoch 20/128

1147/1147 - 10s - 8ms/step - ia: 0.7625 - loss: 0.2574 - mae: 0.3855 - rmse: 0.5009 - smape: 0.7048 - val_ia: 0.7360 - val_loss: 0.0296 - val_mae: 0.1330 - val_rmse: 0.1615 - val_smape: 0.3583

Epoch 21/128

1147/1147 - 6s - 5ms/step - ia: 0.7690 - loss: 0.2436 - mae: 0.3743 - rmse: 0.4873 - smape: 0.6911 - val_ia: 0.7367 - val_loss: 0.0289 - val_mae: 0.1315 - val_rmse: 0.1597 - val_smape: 0.3466

Epoch 22/128

1147/1147 - 5s - 4ms/step - ia: 0.7726 - loss: 0.2335 - mae: 0.3672 - rmse: 0.4774 - smape: 0.6822 - val_ia: 0.7422 - val_loss: 0.0277 - val_mae: 0.1284 - val_rmse: 0.1563 - val_smape: 0.3469

Epoch 23/128

1147/1147 - 2s - 2ms/step - ia: 0.7821 - loss: 0.2152 - mae: 0.3514 - rmse: 0.4577 - smape: 0.6643 - val_ia: 0.7444 - val_loss: 0.0268 - val_mae: 0.1265 - val_rmse: 0.1539 - val_smape: 0.3419

Epoch 24/128

1147/1147 - 5s - 4ms/step - ia: 0.7861 - loss: 0.2084 - mae: 0.3448 - rmse: 0.4508 - smape: 0.6549 - val_ia: 0.7432 - val_loss: 0.0268 - val_mae: 0.1269 - val_rmse: 0.1541 - val_smape: 0.3378

Epoch 25/128

1147/1147 - 4s - 3ms/step - ia: 0.7903 - loss: 0.1981 - mae: 0.3368 - rmse: 0.4395 - smape: 0.6421 - val_ia: 0.7592 - val_loss: 0.0236 - val_mae: 0.1172 - val_rmse: 0.1446 - val_smape: 0.3201

Epoch 26/128

1147/1147 - 7s - 6ms/step - ia: 0.7958 - loss: 0.1884 - mae: 0.3288 - rmse: 0.4285 - smape: 0.6327 - val_ia: 0.7506 - val_loss: 0.0249 - val_mae: 0.1220 - val_rmse: 0.1486 - val_smape: 0.3282

Epoch 27/128

1147/1147 - 4s - 3ms/step - ia: 0.7974 - loss: 0.1860 - mae: 0.3256 - rmse: 0.4253 - smape: 0.6288 - val_ia: 0.7566 - val_loss: 0.0240 - val_mae: 0.1191 - val_rmse: 0.1456 - val_smape: 0.3255

Epoch 28/128

1147/1147 - 3s - 3ms/step - ia: 0.8036 - loss: 0.1747 - mae: 0.3156 - rmse: 0.4125 - smape: 0.6163 - val_ia: 0.7626 - val_loss: 0.0228 - val_mae: 0.1156 - val_rmse: 0.1420 - val_smape: 0.3183

Epoch 29/128

1147/1147 - 3s - 2ms/step - ia: 0.8078 - loss: 0.1671 - mae: 0.3079 - rmse: 0.4034 - smape: 0.6067 - val_ia: 0.7613 - val_loss: 0.0223 - val_mae: 0.1147 - val_rmse: 0.1407 - val_smape: 0.3107

Epoch 30/128

1147/1147 - 2s - 2ms/step - ia: 0.8096 - loss: 0.1649 - mae: 0.3049 - rmse: 0.4007 - smape: 0.5982 - val_ia: 0.7602 - val_loss: 0.0224 - val_mae: 0.1152 - val_rmse: 0.1411 - val_smape: 0.3087

Epoch 31/128

1147/1147 - 2s - 2ms/step - ia: 0.8153 - loss: 0.1552 - mae: 0.2956 - rmse: 0.3881 - smape: 0.5865 - val_ia: 0.7625 - val_loss: 0.0222 - val_mae: 0.1149 - val_rmse: 0.1404 - val_smape: 0.3166

Epoch 32/128

1147/1147 - 2s - 2ms/step - ia: 0.8191 - loss: 0.1493 - mae: 0.2897 - rmse: 0.3809 - smape: 0.5797 - val_ia: 0.7700 - val_loss: 0.0205 - val_mae: 0.1097 - val_rmse: 0.1351 - val_smape: 0.3030

Epoch 33/128

1147/1147 - 4s - 3ms/step - ia: 0.8202 - loss: 0.1462 - mae: 0.2871 - rmse: 0.3774 - smape: 0.5719 - val_ia: 0.7722 - val_loss: 0.0199 - val_mae: 0.1077 - val_rmse: 0.1329 - val_smape: 0.2963

Epoch 34/128

1147/1147 - 3s - 3ms/step - ia: 0.8256 - loss: 0.1373 - mae: 0.2790 - rmse: 0.3656 - smape: 0.5648 - val_ia: 0.7767 - val_loss: 0.0190 - val_mae: 0.1048 - val_rmse: 0.1299 - val_smape: 0.2900

Epoch 35/128

1147/1147 - 3s - 3ms/step - ia: 0.8261 - loss: 0.1357 - mae: 0.2774 - rmse: 0.3634 - smape: 0.5616 - val_ia: 0.7733 - val_loss: 0.0194 - val_mae: 0.1068 - val_rmse: 0.1313 - val_smape: 0.2953

Epoch 36/128

1147/1147 - 5s - 4ms/step - ia: 0.8304 - loss: 0.1300 - mae: 0.2706 - rmse: 0.3555 - smape: 0.5469 - val_ia: 0.7768 - val_loss: 0.0188 - val_mae: 0.1049 - val_rmse: 0.1294 - val_smape: 0.2910

Epoch 37/128

1147/1147 - 3s - 3ms/step - ia: 0.8332 - loss: 0.1269 - mae: 0.2668 - rmse: 0.3510 - smape: 0.5397 - val_ia: 0.7713 - val_loss: 0.0194 - val_mae: 0.1076 - val_rmse: 0.1315 - val_smape: 0.2957

Epoch 38/128

1147/1147 - 5s - 4ms/step - ia: 0.8347 - loss: 0.1236 - mae: 0.2644 - rmse: 0.3467 - smape: 0.5412 - val_ia: 0.7765 - val_loss: 0.0184 - val_mae: 0.1043 - val_rmse: 0.1282 - val_smape: 0.2881

Epoch 39/128

1147/1147 - 3s - 3ms/step - ia: 0.8379 - loss: 0.1188 - mae: 0.2581 - rmse: 0.3400 - smape: 0.5294 - val_ia: 0.7838 - val_loss: 0.0173 - val_mae: 0.1002 - val_rmse: 0.1242 - val_smape: 0.2768

Epoch 40/128

1147/1147 - 3s - 3ms/step - ia: 0.8405 - loss: 0.1148 - mae: 0.2545 - rmse: 0.3341 - smape: 0.5229 - val_ia: 0.7857 - val_loss: 0.0169 - val_mae: 0.0990 - val_rmse: 0.1228 - val_smape: 0.2759

Epoch 41/128

1147/1147 - 5s - 4ms/step - ia: 0.8427 - loss: 0.1123 - mae: 0.2504 - rmse: 0.3305 - smape: 0.5152 - val_ia: 0.7888 - val_loss: 0.0165 - val_mae: 0.0974 - val_rmse: 0.1212 - val_smape: 0.2713

Epoch 42/128

1147/1147 - 4s - 3ms/step - ia: 0.8441 - loss: 0.1101 - mae: 0.2484 - rmse: 0.3271 - smape: 0.5139 - val_ia: 0.7844 - val_loss: 0.0168 - val_mae: 0.0990 - val_rmse: 0.1224 - val_smape: 0.2721

Epoch 43/128

1147/1147 - 5s - 5ms/step - ia: 0.8468 - loss: 0.1067 - mae: 0.2441 - rmse: 0.3223 - smape: 0.5060 - val_ia: 0.7871 - val_loss: 0.0164 - val_mae: 0.0977 - val_rmse: 0.1208 - val_smape: 0.2724

Epoch 44/128

1147/1147 - 4s - 3ms/step - ia: 0.8484 - loss: 0.1053 - mae: 0.2411 - rmse: 0.3199 - smape: 0.4968 - val_ia: 0.7949 - val_loss: 0.0154 - val_mae: 0.0938 - val_rmse: 0.1170 - val_smape: 0.2635

Epoch 45/128

1147/1147 - 6s - 5ms/step - ia: 0.8521 - loss: 0.1003 - mae: 0.2362 - rmse: 0.3121 - smape: 0.4890 - val_ia: 0.7961 - val_loss: 0.0153 - val_mae: 0.0938 - val_rmse: 0.1169 - val_smape: 0.2656

Epoch 46/128

1147/1147 - 4s - 3ms/step - ia: 0.8527 - loss: 0.0992 - mae: 0.2348 - rmse: 0.3103 - smape: 0.4882 - val_ia: 0.7920 - val_loss: 0.0156 - val_mae: 0.0954 - val_rmse: 0.1181 - val_smape: 0.2696

Epoch 47/128

1147/1147 - 2s - 2ms/step - ia: 0.8535 - loss: 0.0979 - mae: 0.2332 - rmse: 0.3088 - smape: 0.4870 - val_ia: 0.7912 - val_loss: 0.0156 - val_mae: 0.0955 - val_rmse: 0.1178 - val_smape: 0.2699

Epoch 48/128

1147/1147 - 2s - 2ms/step - ia: 0.8555 - loss: 0.0956 - mae: 0.2303 - rmse: 0.3052 - smape: 0.4798 - val_ia: 0.7997 - val_loss: 0.0145 - val_mae: 0.0912 - val_rmse: 0.1137 - val_smape: 0.2578

Epoch 49/128

1147/1147 - 2s - 2ms/step - ia: 0.8581 - loss: 0.0927 - mae: 0.2260 - rmse: 0.3000 - smape: 0.4746 - val_ia: 0.8012 - val_loss: 0.0143 - val_mae: 0.0904 - val_rmse: 0.1125 - val_smape: 0.2585

Epoch 50/128

1147/1147 - 2s - 2ms/step - ia: 0.8589 - loss: 0.0902 - mae: 0.2242 - rmse: 0.2963 - smape: 0.4706 - val_ia: 0.7968 - val_loss: 0.0144 - val_mae: 0.0913 - val_rmse: 0.1133 - val_smape: 0.2557

Epoch 51/128

1147/1147 - 2s - 1ms/step - ia: 0.8605 - loss: 0.0891 - mae: 0.2224 - rmse: 0.2941 - smape: 0.4634 - val_ia: 0.7955 - val_loss: 0.0146 - val_mae: 0.0920 - val_rmse: 0.1140 - val_smape: 0.2562

Epoch 52/128

1147/1147 - 3s - 3ms/step - ia: 0.8623 - loss: 0.0867 - mae: 0.2193 - rmse: 0.2903 - smape: 0.4604 - val_ia: 0.7955 - val_loss: 0.0145 - val_mae: 0.0922 - val_rmse: 0.1139 - val_smape: 0.2583

Epoch 53/128

1147/1147 - 2s - 2ms/step - ia: 0.8632 - loss: 0.0857 - mae: 0.2176 - rmse: 0.2884 - smape: 0.4566 - val_ia: 0.7967 - val_loss: 0.0144 - val_mae: 0.0917 - val_rmse: 0.1132 - val_smape: 0.2566

Epoch 54/128

1147/1147 - 3s - 3ms/step - ia: 0.8654 - loss: 0.0833 - mae: 0.2142 - rmse: 0.2844 - smape: 0.4479 - val_ia: 0.8043 - val_loss: 0.0136 - val_mae: 0.0883 - val_rmse: 0.1100 - val_smape: 0.2535

Epoch 55/128

1147/1147 - 3s - 3ms/step - ia: 0.8672 - loss: 0.0814 - mae: 0.2115 - rmse: 0.2813 - smape: 0.4449 - val_ia: 0.8038 - val_loss: 0.0136 - val_mae: 0.0884 - val_rmse: 0.1099 - val_smape: 0.2518

Epoch 56/128

1147/1147 - 5s - 5ms/step - ia: 0.8689 - loss: 0.0790 - mae: 0.2092 - rmse: 0.2770 - smape: 0.4425 - val_ia: 0.8107 - val_loss: 0.0128 - val_mae: 0.0849 - val_rmse: 0.1067 - val_smape: 0.2418

Epoch 57/128

1147/1147 - 3s - 3ms/step - ia: 0.8691 - loss: 0.0795 - mae: 0.2084 - rmse: 0.2776 - smape: 0.4378 - val_ia: 0.8136 - val_loss: 0.0123 - val_mae: 0.0828 - val_rmse: 0.1047 - val_smape: 0.2333

Epoch 58/128

1147/1147 - 3s - 3ms/step - ia: 0.8718 - loss: 0.0762 - mae: 0.2043 - rmse: 0.2722 - smape: 0.4329 - val_ia: 0.8071 - val_loss: 0.0129 - val_mae: 0.0852 - val_rmse: 0.1068 - val_smape: 0.2334

Epoch 59/128

1147/1147 - 5s - 5ms/step - ia: 0.8724 - loss: 0.0748 - mae: 0.2031 - rmse: 0.2695 - smape: 0.4328 - val_ia: 0.8104 - val_loss: 0.0125 - val_mae: 0.0840 - val_rmse: 0.1054 - val_smape: 0.2361

Epoch 60/128

1147/1147 - 6s - 5ms/step - ia: 0.8726 - loss: 0.0753 - mae: 0.2029 - rmse: 0.2704 - smape: 0.4294 - val_ia: 0.8133 - val_loss: 0.0122 - val_mae: 0.0828 - val_rmse: 0.1042 - val_smape: 0.2350

Epoch 61/128

1147/1147 - 4s - 4ms/step - ia: 0.8736 - loss: 0.0743 - mae: 0.2014 - rmse: 0.2681 - smape: 0.4263 - val_ia: 0.8085 - val_loss: 0.0128 - val_mae: 0.0856 - val_rmse: 0.1065 - val_smape: 0.2454

Epoch 62/128

1147/1147 - 6s - 5ms/step - ia: 0.8761 - loss: 0.0712 - mae: 0.1976 - rmse: 0.2628 - smape: 0.4203 - val_ia: 0.8133 - val_loss: 0.0122 - val_mae: 0.0830 - val_rmse: 0.1041 - val_smape: 0.2380

Epoch 63/128

1147/1147 - 5s - 5ms/step - ia: 0.8771 - loss: 0.0701 - mae: 0.1962 - rmse: 0.2609 - smape: 0.4176 - val_ia: 0.8127 - val_loss: 0.0122 - val_mae: 0.0831 - val_rmse: 0.1041 - val_smape: 0.2331

Epoch 64/128

1147/1147 - 3s - 3ms/step - ia: 0.8783 - loss: 0.0689 - mae: 0.1935 - rmse: 0.2587 - smape: 0.4106 - val_ia: 0.8144 - val_loss: 0.0119 - val_mae: 0.0820 - val_rmse: 0.1029 - val_smape: 0.2324

Epoch 65/128

1147/1147 - 3s - 2ms/step - ia: 0.8782 - loss: 0.0688 - mae: 0.1943 - rmse: 0.2586 - smape: 0.4110 - val_ia: 0.8084 - val_loss: 0.0125 - val_mae: 0.0848 - val_rmse: 0.1054 - val_smape: 0.2380

Epoch 66/128

1147/1147 - 2s - 2ms/step - ia: 0.8796 - loss: 0.0678 - mae: 0.1917 - rmse: 0.2564 - smape: 0.4089 - val_ia: 0.8141 - val_loss: 0.0120 - val_mae: 0.0829 - val_rmse: 0.1034 - val_smape: 0.2395

Epoch 67/128

1147/1147 - 2s - 2ms/step - ia: 0.8809 - loss: 0.0662 - mae: 0.1899 - rmse: 0.2533 - smape: 0.4042 - val_ia: 0.8149 - val_loss: 0.0119 - val_mae: 0.0823 - val_rmse: 0.1028 - val_smape: 0.2348

Epoch 68/128

1147/1147 - 2s - 2ms/step - ia: 0.8813 - loss: 0.0662 - mae: 0.1892 - rmse: 0.2535 - smape: 0.4014 - val_ia: 0.8232 - val_loss: 0.0110 - val_mae: 0.0782 - val_rmse: 0.0990 - val_smape: 0.2271

Epoch 69/128

1147/1147 - 3s - 2ms/step - ia: 0.8826 - loss: 0.0641 - mae: 0.1869 - rmse: 0.2494 - smape: 0.3996 - val_ia: 0.8219 - val_loss: 0.0110 - val_mae: 0.0779 - val_rmse: 0.0986 - val_smape: 0.2204

Epoch 70/128

1147/1147 - 2s - 2ms/step - ia: 0.8816 - loss: 0.0653 - mae: 0.1885 - rmse: 0.2517 - smape: 0.3964 - val_ia: 0.8220 - val_loss: 0.0111 - val_mae: 0.0792 - val_rmse: 0.0995 - val_smape: 0.2319

Epoch 71/128

1147/1147 - 3s - 3ms/step - ia: 0.8843 - loss: 0.0628 - mae: 0.1849 - rmse: 0.2471 - smape: 0.3920 - val_ia: 0.8207 - val_loss: 0.0113 - val_mae: 0.0794 - val_rmse: 0.0997 - val_smape: 0.2280

Epoch 72/128

1147/1147 - 2s - 2ms/step - ia: 0.8849 - loss: 0.0618 - mae: 0.1832 - rmse: 0.2452 - smape: 0.3877 - val_ia: 0.8205 - val_loss: 0.0111 - val_mae: 0.0787 - val_rmse: 0.0988 - val_smape: 0.2235

Epoch 73/128

1147/1147 - 2s - 2ms/step - ia: 0.8864 - loss: 0.0606 - mae: 0.1811 - rmse: 0.2425 - smape: 0.3867 - val_ia: 0.8217 - val_loss: 0.0109 - val_mae: 0.0781 - val_rmse: 0.0982 - val_smape: 0.2223

Epoch 74/128

1147/1147 - 2s - 2ms/step - ia: 0.8870 - loss: 0.0601 - mae: 0.1803 - rmse: 0.2412 - smape: 0.3841 - val_ia: 0.8229 - val_loss: 0.0107 - val_mae: 0.0771 - val_rmse: 0.0972 - val_smape: 0.2176

Epoch 75/128

1147/1147 - 2s - 2ms/step - ia: 0.8870 - loss: 0.0594 - mae: 0.1798 - rmse: 0.2400 - smape: 0.3835 - val_ia: 0.8277 - val_loss: 0.0104 - val_mae: 0.0755 - val_rmse: 0.0957 - val_smape: 0.2162

Epoch 76/128

1147/1147 - 3s - 3ms/step - ia: 0.8878 - loss: 0.0593 - mae: 0.1791 - rmse: 0.2399 - smape: 0.3810 - val_ia: 0.8226 - val_loss: 0.0108 - val_mae: 0.0778 - val_rmse: 0.0976 - val_smape: 0.2218

Epoch 77/128

1147/1147 - 3s - 3ms/step - ia: 0.8884 - loss: 0.0584 - mae: 0.1779 - rmse: 0.2380 - smape: 0.3801 - val_ia: 0.8268 - val_loss: 0.0104 - val_mae: 0.0760 - val_rmse: 0.0958 - val_smape: 0.2199

Epoch 78/128

1147/1147 - 5s - 4ms/step - ia: 0.8902 - loss: 0.0564 - mae: 0.1746 - rmse: 0.2339 - smape: 0.3753 - val_ia: 0.8210 - val_loss: 0.0108 - val_mae: 0.0784 - val_rmse: 0.0979 - val_smape: 0.2243

Epoch 79/128

1147/1147 - 5s - 5ms/step - ia: 0.8902 - loss: 0.0566 - mae: 0.1754 - rmse: 0.2342 - smape: 0.3737 - val_ia: 0.8258 - val_loss: 0.0105 - val_mae: 0.0767 - val_rmse: 0.0963 - val_smape: 0.2230

Epoch 80/128

1147/1147 - 3s - 3ms/step - ia: 0.8907 - loss: 0.0559 - mae: 0.1745 - rmse: 0.2331 - smape: 0.3746 - val_ia: 0.8195 - val_loss: 0.0110 - val_mae: 0.0791 - val_rmse: 0.0984 - val_smape: 0.2246

Epoch 81/128

1147/1147 - 3s - 3ms/step - ia: 0.8908 - loss: 0.0558 - mae: 0.1745 - rmse: 0.2327 - smape: 0.3708 - val_ia: 0.8242 - val_loss: 0.0106 - val_mae: 0.0772 - val_rmse: 0.0966 - val_smape: 0.2241

Epoch 82/128

1147/1147 - 4s - 3ms/step - ia: 0.8920 - loss: 0.0549 - mae: 0.1721 - rmse: 0.2308 - smape: 0.3710 - val_ia: 0.8256 - val_loss: 0.0105 - val_mae: 0.0765 - val_rmse: 0.0960 - val_smape: 0.2193

Epoch 83/128

1147/1147 - 3s - 3ms/step - ia: 0.8923 - loss: 0.0540 - mae: 0.1716 - rmse: 0.2289 - smape: 0.3678 - val_ia: 0.8225 - val_loss: 0.0106 - val_mae: 0.0775 - val_rmse: 0.0968 - val_smape: 0.2206

Epoch 84/128

1147/1147 - 3s - 3ms/step - ia: 0.8929 - loss: 0.0537 - mae: 0.1707 - rmse: 0.2283 - smape: 0.3648 - val_ia: 0.8223 - val_loss: 0.0106 - val_mae: 0.0778 - val_rmse: 0.0970 - val_smape: 0.2214

Epoch 85/128

1147/1147 - 6s - 5ms/step - ia: 0.8933 - loss: 0.0536 - mae: 0.1701 - rmse: 0.2281 - smape: 0.3615 - val_ia: 0.8239 - val_loss: 0.0104 - val_mae: 0.0765 - val_rmse: 0.0958 - val_smape: 0.2145

Epoch 86/128

1147/1147 - 3s - 2ms/step - ia: 0.8936 - loss: 0.0533 - mae: 0.1696 - rmse: 0.2274 - smape: 0.3601 - val_ia: 0.8304 - val_loss: 0.0099 - val_mae: 0.0743 - val_rmse: 0.0937 - val_smape: 0.2164

Epoch 87/128

1147/1147 - 2s - 2ms/step - ia: 0.8950 - loss: 0.0520 - mae: 0.1679 - rmse: 0.2247 - smape: 0.3596 - val_ia: 0.8245 - val_loss: 0.0102 - val_mae: 0.0763 - val_rmse: 0.0953 - val_smape: 0.2185

Epoch 88/128

1147/1147 - 3s - 2ms/step - ia: 0.8950 - loss: 0.0520 - mae: 0.1673 - rmse: 0.2246 - smape: 0.3589 - val_ia: 0.8215 - val_loss: 0.0105 - val_mae: 0.0778 - val_rmse: 0.0966 - val_smape: 0.2246

Epoch 89/128

1147/1147 - 2s - 2ms/step - ia: 0.8954 - loss: 0.0522 - mae: 0.1670 - rmse: 0.2248 - smape: 0.3544 - val_ia: 0.8245 - val_loss: 0.0102 - val_mae: 0.0761 - val_rmse: 0.0950 - val_smape: 0.2154

Epoch 90/128

1147/1147 - 2s - 2ms/step - ia: 0.8965 - loss: 0.0505 - mae: 0.1650 - rmse: 0.2213 - smape: 0.3528 - val_ia: 0.8232 - val_loss: 0.0103 - val_mae: 0.0769 - val_rmse: 0.0956 - val_smape: 0.2215

Epoch 91/128

1147/1147 - 3s - 2ms/step - ia: 0.8959 - loss: 0.0513 - mae: 0.1659 - rmse: 0.2229 - smape: 0.3525 - val_ia: 0.8312 - val_loss: 0.0097 - val_mae: 0.0736 - val_rmse: 0.0924 - val_smape: 0.2128

Epoch 92/128

1147/1147 - 4s - 3ms/step - ia: 0.8980 - loss: 0.0493 - mae: 0.1630 - rmse: 0.2185 - smape: 0.3487 - val_ia: 0.8295 - val_loss: 0.0097 - val_mae: 0.0740 - val_rmse: 0.0929 - val_smape: 0.2113

Epoch 93/128

1147/1147 - 3s - 3ms/step - ia: 0.8970 - loss: 0.0499 - mae: 0.1639 - rmse: 0.2198 - smape: 0.3501 - val_ia: 0.8347 - val_loss: 0.0093 - val_mae: 0.0718 - val_rmse: 0.0908 - val_smape: 0.2077

Epoch 94/128

1147/1147 - 5s - 5ms/step - ia: 0.8980 - loss: 0.0501 - mae: 0.1628 - rmse: 0.2201 - smape: 0.3470 - val_ia: 0.8392 - val_loss: 0.0089 - val_mae: 0.0697 - val_rmse: 0.0887 - val_smape: 0.2024

Epoch 95/128

1147/1147 - 3s - 3ms/step - ia: 0.8993 - loss: 0.0482 - mae: 0.1609 - rmse: 0.2159 - smape: 0.3439 - val_ia: 0.8347 - val_loss: 0.0092 - val_mae: 0.0713 - val_rmse: 0.0902 - val_smape: 0.2042

Epoch 96/128

1147/1147 - 5s - 5ms/step - ia: 0.8992 - loss: 0.0483 - mae: 0.1609 - rmse: 0.2162 - smape: 0.3428 - val_ia: 0.8334 - val_loss: 0.0093 - val_mae: 0.0722 - val_rmse: 0.0909 - val_smape: 0.2087

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 2s - 17ms/step - ia: 0.8478 - loss: 0.1575 - mae: 0.2485 - rmse: 0.3293 - smape: 0.4814 - val_ia: 0.9156 - val_loss: 0.0226 - val_mae: 0.1105 - val_rmse: 0.1487 - val_smape: 0.2526

Epoch 2/128

144/144 - 0s - 3ms/step - ia: 0.9084 - loss: 0.0411 - mae: 0.1490 - rmse: 0.2021 - smape: 0.3252 - val_ia: 0.9396 - val_loss: 0.0122 - val_mae: 0.0806 - val_rmse: 0.1083 - val_smape: 0.1926

Epoch 3/128

144/144 - 1s - 5ms/step - ia: 0.9171 - loss: 0.0346 - mae: 0.1352 - rmse: 0.1857 - smape: 0.2884 - val_ia: 0.9497 - val_loss: 0.0083 - val_mae: 0.0695 - val_rmse: 0.0908 - val_smape: 0.1866

Epoch 4/128

144/144 - 1s - 6ms/step - ia: 0.9208 - loss: 0.0321 - mae: 0.1294 - rmse: 0.1786 - smape: 0.2720 - val_ia: 0.9557 - val_loss: 0.0072 - val_mae: 0.0598 - val_rmse: 0.0839 - val_smape: 0.1576

Epoch 5/128

144/144 - 1s - 8ms/step - ia: 0.9213 - loss: 0.0317 - mae: 0.1285 - rmse: 0.1777 - smape: 0.2658 - val_ia: 0.9495 - val_loss: 0.0083 - val_mae: 0.0663 - val_rmse: 0.0897 - val_smape: 0.1635

Epoch 6/128

144/144 - 1s - 5ms/step - ia: 0.9220 - loss: 0.0317 - mae: 0.1276 - rmse: 0.1772 - smape: 0.2592 - val_ia: 0.9521 - val_loss: 0.0070 - val_mae: 0.0635 - val_rmse: 0.0837 - val_smape: 0.1834

Epoch 7/128

144/144 - 1s - 4ms/step - ia: 0.9243 - loss: 0.0300 - mae: 0.1238 - rmse: 0.1726 - smape: 0.2520 - val_ia: 0.9478 - val_loss: 0.0085 - val_mae: 0.0682 - val_rmse: 0.0921 - val_smape: 0.1749

Epoch 8/128

144/144 - 1s - 5ms/step - ia: 0.9255 - loss: 0.0291 - mae: 0.1217 - rmse: 0.1702 - smape: 0.2491 - val_ia: 0.9619 - val_loss: 0.0053 - val_mae: 0.0513 - val_rmse: 0.0722 - val_smape: 0.1363

Epoch 9/128

144/144 - 1s - 4ms/step - ia: 0.9247 - loss: 0.0300 - mae: 0.1231 - rmse: 0.1724 - smape: 0.2476 - val_ia: 0.9410 - val_loss: 0.0100 - val_mae: 0.0782 - val_rmse: 0.0984 - val_smape: 0.1883

Epoch 10/128

144/144 - 1s - 5ms/step - ia: 0.9261 - loss: 0.0290 - mae: 0.1207 - rmse: 0.1700 - smape: 0.2413 - val_ia: 0.9429 - val_loss: 0.0096 - val_mae: 0.0769 - val_rmse: 0.0986 - val_smape: 0.1931

Epoch 11/128

144/144 - 1s - 5ms/step - ia: 0.9258 - loss: 0.0292 - mae: 0.1214 - rmse: 0.1703 - smape: 0.2417 - val_ia: 0.9599 - val_loss: 0.0056 - val_mae: 0.0540 - val_rmse: 0.0742 - val_smape: 0.1419

Epoch 12/128

144/144 - 0s - 2ms/step - ia: 0.9250 - loss: 0.0299 - mae: 0.1227 - rmse: 0.1723 - smape: 0.2419 - val_ia: 0.9634 - val_loss: 0.0046 - val_mae: 0.0481 - val_rmse: 0.0675 - val_smape: 0.1413

Epoch 13/128

144/144 - 0s - 3ms/step - ia: 0.9237 - loss: 0.0312 - mae: 0.1250 - rmse: 0.1757 - smape: 0.2455 - val_ia: 0.9574 - val_loss: 0.0069 - val_mae: 0.0573 - val_rmse: 0.0813 - val_smape: 0.1404

Epoch 14/128

144/144 - 0s - 3ms/step - ia: 0.9255 - loss: 0.0297 - mae: 0.1217 - rmse: 0.1716 - smape: 0.2393 - val_ia: 0.9495 - val_loss: 0.0077 - val_mae: 0.0672 - val_rmse: 0.0858 - val_smape: 0.1651

Epoch 15/128

144/144 - 0s - 2ms/step - ia: 0.9242 - loss: 0.0308 - mae: 0.1240 - rmse: 0.1750 - smape: 0.2440 - val_ia: 0.9263 - val_loss: 0.0142 - val_mae: 0.0982 - val_rmse: 0.1158 - val_smape: 0.2193

Epoch 16/128

144/144 - 1s - 5ms/step - ia: 0.9243 - loss: 0.0308 - mae: 0.1238 - rmse: 0.1745 - smape: 0.2397 - val_ia: 0.9561 - val_loss: 0.0058 - val_mae: 0.0610 - val_rmse: 0.0757 - val_smape: 0.1727

Epoch 17/128

144/144 - 0s - 3ms/step - ia: 0.9273 - loss: 0.0284 - mae: 0.1191 - rmse: 0.1678 - smape: 0.2341 - val_ia: 0.9446 - val_loss: 0.0085 - val_mae: 0.0744 - val_rmse: 0.0904 - val_smape: 0.2035

Epoch 18/128

144/144 - 0s - 2ms/step - ia: 0.9268 - loss: 0.0289 - mae: 0.1198 - rmse: 0.1692 - smape: 0.2355 - val_ia: 0.9493 - val_loss: 0.0074 - val_mae: 0.0678 - val_rmse: 0.0849 - val_smape: 0.1651

Epoch 19/128

144/144 - 0s - 3ms/step - ia: 0.9274 - loss: 0.0281 - mae: 0.1188 - rmse: 0.1671 - smape: 0.2329 - val_ia: 0.9662 - val_loss: 0.0041 - val_mae: 0.0455 - val_rmse: 0.0637 - val_smape: 0.1402

Epoch 20/128

144/144 - 1s - 4ms/step - ia: 0.9264 - loss: 0.0292 - mae: 0.1204 - rmse: 0.1701 - smape: 0.2350 - val_ia: 0.9539 - val_loss: 0.0061 - val_mae: 0.0625 - val_rmse: 0.0780 - val_smape: 0.1842

Epoch 21/128

144/144 - 1s - 5ms/step - ia: 0.9256 - loss: 0.0297 - mae: 0.1217 - rmse: 0.1715 - smape: 0.2371 - val_ia: 0.9547 - val_loss: 0.0076 - val_mae: 0.0604 - val_rmse: 0.0852 - val_smape: 0.1577

Epoch 22/128

144/144 - 0s - 2ms/step - ia: 0.9251 - loss: 0.0301 - mae: 0.1224 - rmse: 0.1727 - smape: 0.2392 - val_ia: 0.9485 - val_loss: 0.0073 - val_mae: 0.0695 - val_rmse: 0.0835 - val_smape: 0.1959

Epoch 23/128

144/144 - 0s - 3ms/step - ia: 0.9258 - loss: 0.0296 - mae: 0.1212 - rmse: 0.1715 - smape: 0.2348 - val_ia: 0.9276 - val_loss: 0.0132 - val_mae: 0.0944 - val_rmse: 0.1128 - val_smape: 0.2014

Epoch 24/128

144/144 - 0s - 3ms/step - ia: 0.9235 - loss: 0.0316 - mae: 0.1250 - rmse: 0.1770 - smape: 0.2391 - val_ia: 0.9626 - val_loss: 0.0047 - val_mae: 0.0504 - val_rmse: 0.0679 - val_smape: 0.1451

Epoch 25/128

144/144 - 0s - 2ms/step - ia: 0.9275 - loss: 0.0284 - mae: 0.1186 - rmse: 0.1677 - smape: 0.2318 - val_ia: 0.9550 - val_loss: 0.0061 - val_mae: 0.0597 - val_rmse: 0.0758 - val_smape: 0.1857

Epoch 26/128

144/144 - 1s - 5ms/step - ia: 0.9267 - loss: 0.0291 - mae: 0.1199 - rmse: 0.1698 - smape: 0.2320 - val_ia: 0.9536 - val_loss: 0.0060 - val_mae: 0.0613 - val_rmse: 0.0770 - val_smape: 0.1733

Epoch 27/128

144/144 - 0s - 3ms/step - ia: 0.9265 - loss: 0.0292 - mae: 0.1202 - rmse: 0.1704 - smape: 0.2324 - val_ia: 0.9562 - val_loss: 0.0063 - val_mae: 0.0585 - val_rmse: 0.0785 - val_smape: 0.1507

Epoch 28/128

144/144 - 0s - 3ms/step - ia: 0.9269 - loss: 0.0290 - mae: 0.1195 - rmse: 0.1697 - smape: 0.2327 - val_ia: 0.9499 - val_loss: 0.0091 - val_mae: 0.0668 - val_rmse: 0.0927 - val_smape: 0.1566

Epoch 29/128

144/144 - 0s - 3ms/step - ia: 0.9245 - loss: 0.0308 - mae: 0.1234 - rmse: 0.1748 - smape: 0.2392 - val_ia: 0.9540 - val_loss: 0.0067 - val_mae: 0.0626 - val_rmse: 0.0814 - val_smape: 0.1807

Epoch 30/128

144/144 - 1s - 4ms/step - ia: 0.9236 - loss: 0.0315 - mae: 0.1249 - rmse: 0.1769 - smape: 0.2386 - val_ia: 0.9213 - val_loss: 0.0155 - val_mae: 0.1036 - val_rmse: 0.1224 - val_smape: 0.2329

Epoch 31/128

144/144 - 0s - 2ms/step - ia: 0.9257 - loss: 0.0298 - mae: 0.1214 - rmse: 0.1720 - smape: 0.2344 - val_ia: 0.9197 - val_loss: 0.0199 - val_mae: 0.1068 - val_rmse: 0.1360 - val_smape: 0.2266

Epoch 32/128

144/144 - 1s - 5ms/step - ia: 0.9252 - loss: 0.0303 - mae: 0.1223 - rmse: 0.1732 - smape: 0.2335 - val_ia: 0.9619 - val_loss: 0.0047 - val_mae: 0.0522 - val_rmse: 0.0683 - val_smape: 0.1602

Epoch 33/128

144/144 - 0s - 3ms/step - ia: 0.9268 - loss: 0.0289 - mae: 0.1197 - rmse: 0.1693 - smape: 0.2338 - val_ia: 0.9659 - val_loss: 0.0041 - val_mae: 0.0465 - val_rmse: 0.0630 - val_smape: 0.1578

Epoch 34/128

144/144 - 0s - 3ms/step - ia: 0.9267 - loss: 0.0289 - mae: 0.1199 - rmse: 0.1694 - smape: 0.2333 - val_ia: 0.9617 - val_loss: 0.0050 - val_mae: 0.0519 - val_rmse: 0.0700 - val_smape: 0.1449

Epoch 35/128

144/144 - 0s - 2ms/step - ia: 0.9271 - loss: 0.0288 - mae: 0.1193 - rmse: 0.1689 - smape: 0.2323 - val_ia: 0.9633 - val_loss: 0.0044 - val_mae: 0.0495 - val_rmse: 0.0655 - val_smape: 0.1439

Epoch 36/128

144/144 - 0s - 3ms/step - ia: 0.9267 - loss: 0.0294 - mae: 0.1199 - rmse: 0.1708 - smape: 0.2312 - val_ia: 0.9524 - val_loss: 0.0064 - val_mae: 0.0650 - val_rmse: 0.0784 - val_smape: 0.1707

Epoch 37/128

144/144 - 1s - 4ms/step - ia: 0.9272 - loss: 0.0286 - mae: 0.1191 - rmse: 0.1685 - smape: 0.2315 - val_ia: 0.9348 - val_loss: 0.0118 - val_mae: 0.0868 - val_rmse: 0.1065 - val_smape: 0.1834

Epoch 38/128

144/144 - 1s - 4ms/step - ia: 0.9266 - loss: 0.0291 - mae: 0.1202 - rmse: 0.1697 - smape: 0.2321 - val_ia: 0.9569 - val_loss: 0.0057 - val_mae: 0.0574 - val_rmse: 0.0750 - val_smape: 0.1506

Epoch 39/128

144/144 - 1s - 5ms/step - ia: 0.9279 - loss: 0.0282 - mae: 0.1178 - rmse: 0.1673 - smape: 0.2297 - val_ia: 0.9641 - val_loss: 0.0051 - val_mae: 0.0488 - val_rmse: 0.0695 - val_smape: 0.1289

Epoch 40/128

144/144 - 1s - 5ms/step - ia: 0.9268 - loss: 0.0290 - mae: 0.1196 - rmse: 0.1694 - smape: 0.2320 - val_ia: 0.9582 - val_loss: 0.0054 - val_mae: 0.0564 - val_rmse: 0.0721 - val_smape: 0.1419

Epoch 41/128

144/144 - 1s - 5ms/step - ia: 0.9252 - loss: 0.0302 - mae: 0.1224 - rmse: 0.1730 - smape: 0.2359 - val_ia: 0.9183 - val_loss: 0.0183 - val_mae: 0.1082 - val_rmse: 0.1317 - val_smape: 0.2256

Epoch 42/128

144/144 - 1s - 5ms/step - ia: 0.9236 - loss: 0.0315 - mae: 0.1248 - rmse: 0.1766 - smape: 0.2384 - val_ia: 0.9528 - val_loss: 0.0072 - val_mae: 0.0657 - val_rmse: 0.0835 - val_smape: 0.1456

Epoch 43/128

144/144 - 1s - 4ms/step - ia: 0.9272 - loss: 0.0290 - mae: 0.1191 - rmse: 0.1694 - smape: 0.2284 - val_ia: 0.9215 - val_loss: 0.0172 - val_mae: 0.1041 - val_rmse: 0.1270 - val_smape: 0.2329

Epoch 44/128

144/144 - 1s - 4ms/step - ia: 0.9269 - loss: 0.0288 - mae: 0.1194 - rmse: 0.1690 - smape: 0.2313 - val_ia: 0.9562 - val_loss: 0.0070 - val_mae: 0.0597 - val_rmse: 0.0810 - val_smape: 0.1546

Epoch 45/128

144/144 - 1s - 5ms/step - ia: 0.9270 - loss: 0.0290 - mae: 0.1195 - rmse: 0.1695 - smape: 0.2312 - val_ia: 0.9515 - val_loss: 0.0071 - val_mae: 0.0650 - val_rmse: 0.0823 - val_smape: 0.1595

Epoch 46/128

144/144 - 0s - 3ms/step - ia: 0.9275 - loss: 0.0285 - mae: 0.1186 - rmse: 0.1683 - smape: 0.2279 - val_ia: 0.9441 - val_loss: 0.0089 - val_mae: 0.0748 - val_rmse: 0.0931 - val_smape: 0.1699

Epoch 47/128

144/144 - 1s - 4ms/step - ia: 0.9287 - loss: 0.0278 - mae: 0.1165 - rmse: 0.1661 - smape: 0.2250 - val_ia: 0.9502 - val_loss: 0.0076 - val_mae: 0.0696 - val_rmse: 0.0862 - val_smape: 0.1667

Epoch 48/128

144/144 - 0s - 2ms/step - ia: 0.9278 - loss: 0.0285 - mae: 0.1181 - rmse: 0.1683 - smape: 0.2275 - val_ia: 0.9484 - val_loss: 0.0070 - val_mae: 0.0691 - val_rmse: 0.0824 - val_smape: 0.1842

Epoch 48: early stopping

Restoring model weights from the end of the best epoch: 33.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 10s 67ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/8

 14%|█▍        | 7/50 [34:14<4:01:20, 336.75s/trial, best loss: 0.0035199541481683635]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

2293/2293 - 8s - 3ms/step - ia: 0.8709 - loss: 0.0758 - mae: 0.2031 - rmse: 0.2580 - smape: 0.4130 - val_ia: 0.6860 - val_loss: 0.0175 - val_mae: 0.0961 - val_rmse: 0.1133 - val_smape: 0.1977

Epoch 2/8

2293/2293 - 5s - 2ms/step - ia: 0.8968 - loss: 0.0458 - mae: 0.1622 - rmse: 0.2080 - smape: 0.3470 - val_ia: 0.5848 - val_loss: 0.0435 - val_mae: 0.1616 - val_rmse: 0.1784 - val_smape: 0.3165

Epoch 3/8

2293/2293 - 5s - 2ms/step - ia: 0.9009 - loss: 0.0424 - mae: 0.1558 - rmse: 0.2000 - smape: 0.3315 - val_ia: 0.7060 - val_loss: 0.0166 - val_mae: 0.0927 - val_rmse: 0.1060 - val_smape: 0.2114

Epoch 4/8

2293/2293 - 5s - 2ms/step - ia: 0.9036 - loss: 0.0407 - mae: 0.1518 - rmse: 0.1957 - smape: 0.3231 - val_ia: 0.6810 - val_loss: 0.0145 - val_mae: 0.0939 - val_rmse: 0.1062 - val_smape: 0.2213

Epoch 5/8

2293/2293 - 10s - 4ms/step - ia: 0.9051 - loss: 0.0395 - mae: 0.1492 - rmse: 0.1930 - smape: 0.3189 - val_ia: 0.6648 - val_loss: 0.0144 - val_mae: 0.0965 - val_rmse: 0.1097 - val_smape: 0.2713

Epoch 6/8

2293/2293 - 6s - 3ms/step - ia: 0.9065 - loss: 0.0386 - mae: 0.1472 - rmse: 0.1906 - smape: 0.3184 - val_ia: 0.6792 - val_loss: 0.0173 - val_mae: 0.1017 - val_rmse: 0.1161 - val_smape: 0.2242

Epoch 7/8

2293/2293 - 9s - 4ms/step - ia: 0.9056 - loss: 0.0394 - mae: 0.1490 - rmse: 0.1924 - smape: 0.3199 - val_ia: 0.7283 - val_loss: 0.0111 - val_mae: 0.0778 - val_rmse: 0.0901 - val_smape: 0.1697

Epoch 8/8

2293/2293 - 5s - 2ms/step - ia: 0.9057 - loss: 0.0392 - mae: 0.1487 - rmse: 0.1917 - smape: 0.3194 - val_ia: 0.7122 - val_loss: 0.0134 - val_mae: 0.0847 - val_rmse: 0.0980 - val_smape: 0.1993

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 10s 67ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/128

 16%|█▌        | 8/50 [35:08<2:52:35, 246.55s/trial, best loss: 0.0035199541481683635]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 2s - 16ms/step - ia: 0.6589 - loss: 0.8111 - mae: 0.6268 - rmse: 0.8212 - smape: 0.8944 - val_ia: 0.8522 - val_loss: 0.0654 - val_mae: 0.1971 - val_rmse: 0.2528 - val_smape: 0.4993

Epoch 2/128

144/144 - 0s - 2ms/step - ia: 0.8159 - loss: 0.1713 - mae: 0.3009 - rmse: 0.4115 - smape: 0.5864 - val_ia: 0.8907 - val_loss: 0.0380 - val_mae: 0.1448 - val_rmse: 0.1942 - val_smape: 0.3647

Epoch 3/128

144/144 - 1s - 6ms/step - ia: 0.8461 - loss: 0.1191 - mae: 0.2492 - rmse: 0.3442 - smape: 0.4987 - val_ia: 0.8980 - val_loss: 0.0315 - val_mae: 0.1343 - val_rmse: 0.1765 - val_smape: 0.3294

Epoch 4/128

144/144 - 1s - 4ms/step - ia: 0.8603 - loss: 0.0973 - mae: 0.2251 - rmse: 0.3113 - smape: 0.4527 - val_ia: 0.9178 - val_loss: 0.0213 - val_mae: 0.1093 - val_rmse: 0.1455 - val_smape: 0.2863

Epoch 5/128

144/144 - 1s - 5ms/step - ia: 0.8699 - loss: 0.0849 - mae: 0.2097 - rmse: 0.2906 - smape: 0.4234 - val_ia: 0.9169 - val_loss: 0.0205 - val_mae: 0.1098 - val_rmse: 0.1422 - val_smape: 0.2760

Epoch 6/128

144/144 - 0s - 3ms/step - ia: 0.8762 - loss: 0.0769 - mae: 0.1992 - rmse: 0.2770 - smape: 0.4006 - val_ia: 0.9293 - val_loss: 0.0154 - val_mae: 0.0939 - val_rmse: 0.1236 - val_smape: 0.2533

Epoch 7/128

144/144 - 1s - 5ms/step - ia: 0.8793 - loss: 0.0736 - mae: 0.1944 - rmse: 0.2706 - smape: 0.3864 - val_ia: 0.9290 - val_loss: 0.0147 - val_mae: 0.0940 - val_rmse: 0.1201 - val_smape: 0.2670

Epoch 8/128

144/144 - 0s - 3ms/step - ia: 0.8820 - loss: 0.0713 - mae: 0.1900 - rmse: 0.2664 - smape: 0.3745 - val_ia: 0.9344 - val_loss: 0.0128 - val_mae: 0.0873 - val_rmse: 0.1125 - val_smape: 0.2391

Epoch 9/128

144/144 - 0s - 3ms/step - ia: 0.8846 - loss: 0.0678 - mae: 0.1858 - rmse: 0.2600 - smape: 0.3676 - val_ia: 0.9419 - val_loss: 0.0106 - val_mae: 0.0771 - val_rmse: 0.1028 - val_smape: 0.2258

Epoch 10/128

144/144 - 0s - 3ms/step - ia: 0.8849 - loss: 0.0680 - mae: 0.1851 - rmse: 0.2601 - smape: 0.3625 - val_ia: 0.9408 - val_loss: 0.0110 - val_mae: 0.0782 - val_rmse: 0.1044 - val_smape: 0.1976

Epoch 11/128

144/144 - 1s - 4ms/step - ia: 0.8878 - loss: 0.0650 - mae: 0.1806 - rmse: 0.2544 - smape: 0.3534 - val_ia: 0.9357 - val_loss: 0.0122 - val_mae: 0.0843 - val_rmse: 0.1098 - val_smape: 0.1986

Epoch 12/128

144/144 - 1s - 4ms/step - ia: 0.8887 - loss: 0.0638 - mae: 0.1792 - rmse: 0.2520 - smape: 0.3492 - val_ia: 0.9440 - val_loss: 0.0095 - val_mae: 0.0744 - val_rmse: 0.0969 - val_smape: 0.1987

Epoch 13/128

144/144 - 1s - 5ms/step - ia: 0.8896 - loss: 0.0638 - mae: 0.1779 - rmse: 0.2520 - smape: 0.3459 - val_ia: 0.9421 - val_loss: 0.0101 - val_mae: 0.0766 - val_rmse: 0.0996 - val_smape: 0.1916

Epoch 14/128

144/144 - 0s - 3ms/step - ia: 0.8897 - loss: 0.0639 - mae: 0.1775 - rmse: 0.2521 - smape: 0.3420 - val_ia: 0.9302 - val_loss: 0.0136 - val_mae: 0.0918 - val_rmse: 0.1157 - val_smape: 0.2054

Epoch 15/128

144/144 - 1s - 4ms/step - ia: 0.8907 - loss: 0.0620 - mae: 0.1760 - rmse: 0.2487 - smape: 0.3379 - val_ia: 0.9336 - val_loss: 0.0121 - val_mae: 0.0878 - val_rmse: 0.1080 - val_smape: 0.2321

Epoch 16/128

144/144 - 1s - 4ms/step - ia: 0.8912 - loss: 0.0623 - mae: 0.1753 - rmse: 0.2489 - smape: 0.3328 - val_ia: 0.9434 - val_loss: 0.0094 - val_mae: 0.0749 - val_rmse: 0.0960 - val_smape: 0.1930

Epoch 17/128

144/144 - 1s - 5ms/step - ia: 0.8917 - loss: 0.0618 - mae: 0.1742 - rmse: 0.2481 - smape: 0.3329 - val_ia: 0.9467 - val_loss: 0.0086 - val_mae: 0.0708 - val_rmse: 0.0922 - val_smape: 0.1774

Epoch 18/128

144/144 - 1s - 4ms/step - ia: 0.8929 - loss: 0.0612 - mae: 0.1728 - rmse: 0.2465 - smape: 0.3299 - val_ia: 0.9411 - val_loss: 0.0102 - val_mae: 0.0782 - val_rmse: 0.1000 - val_smape: 0.1837

Epoch 19/128

144/144 - 1s - 4ms/step - ia: 0.8930 - loss: 0.0608 - mae: 0.1724 - rmse: 0.2460 - smape: 0.3264 - val_ia: 0.9292 - val_loss: 0.0136 - val_mae: 0.0932 - val_rmse: 0.1150 - val_smape: 0.2110

Epoch 20/128

144/144 - 1s - 4ms/step - ia: 0.8938 - loss: 0.0597 - mae: 0.1709 - rmse: 0.2437 - smape: 0.3239 - val_ia: 0.9473 - val_loss: 0.0085 - val_mae: 0.0703 - val_rmse: 0.0910 - val_smape: 0.1756

Epoch 21/128

144/144 - 1s - 5ms/step - ia: 0.8944 - loss: 0.0590 - mae: 0.1703 - rmse: 0.2423 - smape: 0.3204 - val_ia: 0.9490 - val_loss: 0.0080 - val_mae: 0.0680 - val_rmse: 0.0886 - val_smape: 0.1767

Epoch 22/128

144/144 - 1s - 5ms/step - ia: 0.8951 - loss: 0.0590 - mae: 0.1690 - rmse: 0.2423 - smape: 0.3184 - val_ia: 0.9496 - val_loss: 0.0077 - val_mae: 0.0672 - val_rmse: 0.0867 - val_smape: 0.1714

Epoch 23/128

144/144 - 1s - 5ms/step - ia: 0.8952 - loss: 0.0593 - mae: 0.1690 - rmse: 0.2428 - smape: 0.3160 - val_ia: 0.9503 - val_loss: 0.0074 - val_mae: 0.0661 - val_rmse: 0.0849 - val_smape: 0.1864

Epoch 24/128

144/144 - 0s - 3ms/step - ia: 0.8957 - loss: 0.0584 - mae: 0.1680 - rmse: 0.2408 - smape: 0.3162 - val_ia: 0.9556 - val_loss: 0.0065 - val_mae: 0.0596 - val_rmse: 0.0799 - val_smape: 0.1625

Epoch 25/128

144/144 - 1s - 5ms/step - ia: 0.8958 - loss: 0.0584 - mae: 0.1680 - rmse: 0.2409 - smape: 0.3140 - val_ia: 0.9563 - val_loss: 0.0061 - val_mae: 0.0583 - val_rmse: 0.0773 - val_smape: 0.1724

Epoch 26/128

144/144 - 1s - 5ms/step - ia: 0.8963 - loss: 0.0579 - mae: 0.1671 - rmse: 0.2400 - smape: 0.3123 - val_ia: 0.9570 - val_loss: 0.0059 - val_mae: 0.0574 - val_rmse: 0.0759 - val_smape: 0.1667

Epoch 27/128

144/144 - 1s - 4ms/step - ia: 0.8966 - loss: 0.0579 - mae: 0.1665 - rmse: 0.2403 - smape: 0.3107 - val_ia: 0.9545 - val_loss: 0.0064 - val_mae: 0.0610 - val_rmse: 0.0792 - val_smape: 0.1628

Epoch 28/128

144/144 - 0s - 3ms/step - ia: 0.8962 - loss: 0.0578 - mae: 0.1673 - rmse: 0.2397 - smape: 0.3108 - val_ia: 0.9577 - val_loss: 0.0060 - val_mae: 0.0567 - val_rmse: 0.0766 - val_smape: 0.1579

Epoch 29/128

144/144 - 1s - 5ms/step - ia: 0.8958 - loss: 0.0585 - mae: 0.1679 - rmse: 0.2410 - smape: 0.3102 - val_ia: 0.9574 - val_loss: 0.0058 - val_mae: 0.0569 - val_rmse: 0.0754 - val_smape: 0.1653

Epoch 30/128

144/144 - 1s - 5ms/step - ia: 0.8969 - loss: 0.0573 - mae: 0.1661 - rmse: 0.2388 - smape: 0.3083 - val_ia: 0.9602 - val_loss: 0.0055 - val_mae: 0.0534 - val_rmse: 0.0733 - val_smape: 0.1538

Epoch 31/128

144/144 - 1s - 4ms/step - ia: 0.8954 - loss: 0.0595 - mae: 0.1686 - rmse: 0.2428 - smape: 0.3104 - val_ia: 0.9569 - val_loss: 0.0059 - val_mae: 0.0576 - val_rmse: 0.0756 - val_smape: 0.1680

Epoch 32/128

144/144 - 1s - 4ms/step - ia: 0.8970 - loss: 0.0579 - mae: 0.1658 - rmse: 0.2399 - smape: 0.3051 - val_ia: 0.9457 - val_loss: 0.0084 - val_mae: 0.0724 - val_rmse: 0.0903 - val_smape: 0.1924

Epoch 33/128

144/144 - 1s - 4ms/step - ia: 0.8974 - loss: 0.0569 - mae: 0.1655 - rmse: 0.2377 - smape: 0.3042 - val_ia: 0.9499 - val_loss: 0.0075 - val_mae: 0.0670 - val_rmse: 0.0853 - val_smape: 0.1688

Epoch 34/128

144/144 - 1s - 5ms/step - ia: 0.8965 - loss: 0.0578 - mae: 0.1665 - rmse: 0.2401 - smape: 0.3064 - val_ia: 0.9549 - val_loss: 0.0063 - val_mae: 0.0603 - val_rmse: 0.0783 - val_smape: 0.1665

Epoch 35/128

144/144 - 1s - 6ms/step - ia: 0.8975 - loss: 0.0574 - mae: 0.1651 - rmse: 0.2388 - smape: 0.3018 - val_ia: 0.9458 - val_loss: 0.0086 - val_mae: 0.0724 - val_rmse: 0.0913 - val_smape: 0.1788

Epoch 36/128

144/144 - 1s - 4ms/step - ia: 0.8972 - loss: 0.0575 - mae: 0.1655 - rmse: 0.2392 - smape: 0.3020 - val_ia: 0.9555 - val_loss: 0.0060 - val_mae: 0.0599 - val_rmse: 0.0763 - val_smape: 0.1770

Epoch 37/128

144/144 - 1s - 4ms/step - ia: 0.8988 - loss: 0.0557 - mae: 0.1630 - rmse: 0.2358 - smape: 0.2972 - val_ia: 0.9469 - val_loss: 0.0082 - val_mae: 0.0710 - val_rmse: 0.0890 - val_smape: 0.1812

Epoch 38/128

144/144 - 1s - 5ms/step - ia: 0.8982 - loss: 0.0568 - mae: 0.1640 - rmse: 0.2378 - smape: 0.2995 - val_ia: 0.9515 - val_loss: 0.0072 - val_mae: 0.0650 - val_rmse: 0.0839 - val_smape: 0.1622

Epoch 39/128

144/144 - 1s - 5ms/step - ia: 0.8977 - loss: 0.0570 - mae: 0.1646 - rmse: 0.2386 - smape: 0.2982 - val_ia: 0.9592 - val_loss: 0.0053 - val_mae: 0.0541 - val_rmse: 0.0723 - val_smape: 0.1652

Epoch 40/128

144/144 - 1s - 6ms/step - ia: 0.8989 - loss: 0.0558 - mae: 0.1629 - rmse: 0.2358 - smape: 0.2962 - val_ia: 0.9564 - val_loss: 0.0060 - val_mae: 0.0585 - val_rmse: 0.0767 - val_smape: 0.1488

Epoch 41/128

144/144 - 1s - 4ms/step - ia: 0.8992 - loss: 0.0560 - mae: 0.1622 - rmse: 0.2360 - smape: 0.2932 - val_ia: 0.9558 - val_loss: 0.0059 - val_mae: 0.0588 - val_rmse: 0.0760 - val_smape: 0.1734

Epoch 42/128

144/144 - 1s - 4ms/step - ia: 0.8991 - loss: 0.0557 - mae: 0.1626 - rmse: 0.2355 - smape: 0.2954 - val_ia: 0.9538 - val_loss: 0.0066 - val_mae: 0.0621 - val_rmse: 0.0803 - val_smape: 0.1569

Epoch 43/128

144/144 - 1s - 5ms/step - ia: 0.8986 - loss: 0.0566 - mae: 0.1633 - rmse: 0.2373 - smape: 0.2956 - val_ia: 0.9506 - val_loss: 0.0072 - val_mae: 0.0659 - val_rmse: 0.0832 - val_smape: 0.1755

Epoch 44/128

144/144 - 1s - 5ms/step - ia: 0.8985 - loss: 0.0567 - mae: 0.1634 - rmse: 0.2379 - smape: 0.2935 - val_ia: 0.9498 - val_loss: 0.0076 - val_mae: 0.0674 - val_rmse: 0.0861 - val_smape: 0.1680

Epoch 45/128

144/144 - 1s - 5ms/step - ia: 0.8984 - loss: 0.0565 - mae: 0.1635 - rmse: 0.2369 - smape: 0.2947 - val_ia: 0.9595 - val_loss: 0.0053 - val_mae: 0.0546 - val_rmse: 0.0720 - val_smape: 0.1555

Epoch 46/128

144/144 - 0s - 3ms/step - ia: 0.8982 - loss: 0.0565 - mae: 0.1640 - rmse: 0.2373 - smape: 0.2942 - val_ia: 0.9552 - val_loss: 0.0062 - val_mae: 0.0603 - val_rmse: 0.0778 - val_smape: 0.1504

Epoch 47/128

144/144 - 1s - 4ms/step - ia: 0.8992 - loss: 0.0559 - mae: 0.1623 - rmse: 0.2357 - smape: 0.2914 - val_ia: 0.9620 - val_loss: 0.0047 - val_mae: 0.0506 - val_rmse: 0.0679 - val_smape: 0.1534

Epoch 48/128

144/144 - 1s - 5ms/step - ia: 0.8987 - loss: 0.0565 - mae: 0.1629 - rmse: 0.2372 - smape: 0.2922 - val_ia: 0.9490 - val_loss: 0.0077 - val_mae: 0.0685 - val_rmse: 0.0865 - val_smape: 0.1590

Epoch 49/128

144/144 - 1s - 4ms/step - ia: 0.8995 - loss: 0.0560 - mae: 0.1619 - rmse: 0.2360 - smape: 0.2901 - val_ia: 0.9597 - val_loss: 0.0051 - val_mae: 0.0541 - val_rmse: 0.0703 - val_smape: 0.1595

Epoch 50/128

144/144 - 1s - 5ms/step - ia: 0.8987 - loss: 0.0567 - mae: 0.1632 - rmse: 0.2375 - smape: 0.2933 - val_ia: 0.9490 - val_loss: 0.0071 - val_mae: 0.0667 - val_rmse: 0.0824 - val_smape: 0.2016

Epoch 51/128

144/144 - 1s - 5ms/step - ia: 0.8985 - loss: 0.0566 - mae: 0.1635 - rmse: 0.2373 - smape: 0.2920 - val_ia: 0.9631 - val_loss: 0.0046 - val_mae: 0.0498 - val_rmse: 0.0668 - val_smape: 0.1503

Epoch 52/128

144/144 - 1s - 5ms/step - ia: 0.8999 - loss: 0.0549 - mae: 0.1614 - rmse: 0.2335 - smape: 0.2906 - val_ia: 0.9524 - val_loss: 0.0069 - val_mae: 0.0641 - val_rmse: 0.0820 - val_smape: 0.1532

Epoch 53/128

144/144 - 1s - 5ms/step - ia: 0.8994 - loss: 0.0563 - mae: 0.1622 - rmse: 0.2366 - smape: 0.2906 - val_ia: 0.9509 - val_loss: 0.0073 - val_mae: 0.0659 - val_rmse: 0.0844 - val_smape: 0.1588

Epoch 54/128

144/144 - 1s - 5ms/step - ia: 0.8995 - loss: 0.0558 - mae: 0.1619 - rmse: 0.2355 - smape: 0.2904 - val_ia: 0.9636 - val_loss: 0.0044 - val_mae: 0.0488 - val_rmse: 0.0659 - val_smape: 0.1503

Epoch 55/128

144/144 - 1s - 4ms/step - ia: 0.8995 - loss: 0.0562 - mae: 0.1620 - rmse: 0.2365 - smape: 0.2903 - val_ia: 0.9539 - val_loss: 0.0065 - val_mae: 0.0621 - val_rmse: 0.0791 - val_smape: 0.1546

Epoch 56/128

144/144 - 1s - 4ms/step - ia: 0.8991 - loss: 0.0558 - mae: 0.1621 - rmse: 0.2360 - smape: 0.2888 - val_ia: 0.9537 - val_loss: 0.0066 - val_mae: 0.0623 - val_rmse: 0.0800 - val_smape: 0.1585

Epoch 57/128

144/144 - 1s - 5ms/step - ia: 0.8985 - loss: 0.0575 - mae: 0.1636 - rmse: 0.2392 - smape: 0.2922 - val_ia: 0.9414 - val_loss: 0.0097 - val_mae: 0.0781 - val_rmse: 0.0973 - val_smape: 0.1694

Epoch 58/128

144/144 - 1s - 4ms/step - ia: 0.8989 - loss: 0.0566 - mae: 0.1629 - rmse: 0.2373 - smape: 0.2895 - val_ia: 0.9607 - val_loss: 0.0052 - val_mae: 0.0529 - val_rmse: 0.0712 - val_smape: 0.1377

Epoch 59/128

144/144 - 1s - 6ms/step - ia: 0.8990 - loss: 0.0556 - mae: 0.1627 - rmse: 0.2353 - smape: 0.2908 - val_ia: 0.9554 - val_loss: 0.0062 - val_mae: 0.0602 - val_rmse: 0.0778 - val_smape: 0.1518

Epoch 60/128

144/144 - 0s - 3ms/step - ia: 0.9006 - loss: 0.0547 - mae: 0.1601 - rmse: 0.2333 - smape: 0.2837 - val_ia: 0.9466 - val_loss: 0.0084 - val_mae: 0.0715 - val_rmse: 0.0903 - val_smape: 0.1572

Epoch 61/128

144/144 - 1s - 6ms/step - ia: 0.8987 - loss: 0.0564 - mae: 0.1629 - rmse: 0.2370 - smape: 0.2904 - val_ia: 0.9553 - val_loss: 0.0063 - val_mae: 0.0603 - val_rmse: 0.0780 - val_smape: 0.1537

Epoch 62/128

144/144 - 1s - 4ms/step - ia: 0.9001 - loss: 0.0554 - mae: 0.1609 - rmse: 0.2347 - smape: 0.2879 - val_ia: 0.9590 - val_loss: 0.0051 - val_mae: 0.0548 - val_rmse: 0.0701 - val_smape: 0.1672

Epoch 63/128

144/144 - 0s - 3ms/step - ia: 0.8999 - loss: 0.0555 - mae: 0.1613 - rmse: 0.2348 - smape: 0.2873 - val_ia: 0.9500 - val_loss: 0.0074 - val_mae: 0.0675 - val_rmse: 0.0847 - val_smape: 0.1686

Epoch 64/128

144/144 - 0s - 2ms/step - ia: 0.9004 - loss: 0.0550 - mae: 0.1606 - rmse: 0.2338 - smape: 0.2860 - val_ia: 0.9470 - val_loss: 0.0082 - val_mae: 0.0711 - val_rmse: 0.0886 - val_smape: 0.1732

Epoch 65/128

144/144 - 0s - 2ms/step - ia: 0.8994 - loss: 0.0564 - mae: 0.1620 - rmse: 0.2367 - smape: 0.2878 - val_ia: 0.9561 - val_loss: 0.0060 - val_mae: 0.0589 - val_rmse: 0.0766 - val_smape: 0.1582

Epoch 66/128

144/144 - 0s - 3ms/step - ia: 0.9001 - loss: 0.0552 - mae: 0.1610 - rmse: 0.2343 - smape: 0.2870 - val_ia: 0.9595 - val_loss: 0.0053 - val_mae: 0.0546 - val_rmse: 0.0718 - val_smape: 0.1438

Epoch 67/128

144/144 - 0s - 2ms/step - ia: 0.9009 - loss: 0.0548 - mae: 0.1597 - rmse: 0.2335 - smape: 0.2824 - val_ia: 0.9618 - val_loss: 0.0048 - val_mae: 0.0517 - val_rmse: 0.0682 - val_smape: 0.1468

Epoch 68/128

144/144 - 0s - 2ms/step - ia: 0.9006 - loss: 0.0553 - mae: 0.1601 - rmse: 0.2346 - smape: 0.2848 - val_ia: 0.9406 - val_loss: 0.0101 - val_mae: 0.0796 - val_rmse: 0.0982 - val_smape: 0.1864

Epoch 69/128

144/144 - 0s - 2ms/step - ia: 0.9005 - loss: 0.0549 - mae: 0.1604 - rmse: 0.2335 - smape: 0.2860 - val_ia: 0.9616 - val_loss: 0.0047 - val_mae: 0.0515 - val_rmse: 0.0676 - val_smape: 0.1552

Epoch 69: early stopping

Restoring model weights from the end of the best epoch: 54.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

Epoch 1/16

 18%|█▊        | 9/50 [35:51<2:05:11, 183.20s/trial, best loss: 0.0035199541481683635]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 16s - 14ms/step - ia: 0.7324 - loss: 0.3357 - mae: 0.4212 - rmse: 0.5497 - smape: 0.7551 - val_ia: 0.6151 - val_loss: 0.0983 - val_mae: 0.2456 - val_rmse: 0.2771 - val_smape: 0.5566

Epoch 2/16

1147/1147 - 4s - 4ms/step - ia: 0.8385 - loss: 0.1150 - mae: 0.2557 - rmse: 0.3340 - smape: 0.5214 - val_ia: 0.6144 - val_loss: 0.0835 - val_mae: 0.2364 - val_rmse: 0.2630 - val_smape: 0.5207

Epoch 3/16

1147/1147 - 5s - 4ms/step - ia: 0.8669 - loss: 0.0791 - mae: 0.2114 - rmse: 0.2772 - smape: 0.4465 - val_ia: 0.6235 - val_loss: 0.0704 - val_mae: 0.2206 - val_rmse: 0.2463 - val_smape: 0.4789

Epoch 4/16

1147/1147 - 4s - 3ms/step - ia: 0.8828 - loss: 0.0623 - mae: 0.1863 - rmse: 0.2461 - smape: 0.4015 - val_ia: 0.6363 - val_loss: 0.0624 - val_mae: 0.2072 - val_rmse: 0.2313 - val_smape: 0.4389

Epoch 5/16

1147/1147 - 4s - 3ms/step - ia: 0.8930 - loss: 0.0529 - mae: 0.1707 - rmse: 0.2267 - smape: 0.3644 - val_ia: 0.6390 - val_loss: 0.0578 - val_mae: 0.2000 - val_rmse: 0.2233 - val_smape: 0.4164

Epoch 6/16

1147/1147 - 5s - 4ms/step - ia: 0.9005 - loss: 0.0458 - mae: 0.1589 - rmse: 0.2109 - smape: 0.3438 - val_ia: 0.6496 - val_loss: 0.0529 - val_mae: 0.1897 - val_rmse: 0.2127 - val_smape: 0.3929

Epoch 7/16

1147/1147 - 6s - 5ms/step - ia: 0.9049 - loss: 0.0423 - mae: 0.1519 - rmse: 0.2023 - smape: 0.3273 - val_ia: 0.6580 - val_loss: 0.0487 - val_mae: 0.1820 - val_rmse: 0.2042 - val_smape: 0.3758

Epoch 8/16

1147/1147 - 5s - 4ms/step - ia: 0.9090 - loss: 0.0389 - mae: 0.1455 - rmse: 0.1940 - smape: 0.3129 - val_ia: 0.6694 - val_loss: 0.0441 - val_mae: 0.1733 - val_rmse: 0.1954 - val_smape: 0.3602

Epoch 9/16

1147/1147 - 4s - 3ms/step - ia: 0.9119 - loss: 0.0370 - mae: 0.1410 - rmse: 0.1891 - smape: 0.3028 - val_ia: 0.6696 - val_loss: 0.0436 - val_mae: 0.1736 - val_rmse: 0.1941 - val_smape: 0.3686

Epoch 10/16

1147/1147 - 5s - 5ms/step - ia: 0.9147 - loss: 0.0351 - mae: 0.1368 - rmse: 0.1842 - smape: 0.2925 - val_ia: 0.6694 - val_loss: 0.0432 - val_mae: 0.1734 - val_rmse: 0.1931 - val_smape: 0.3648

Epoch 11/16

1147/1147 - 5s - 5ms/step - ia: 0.9160 - loss: 0.0342 - mae: 0.1346 - rmse: 0.1815 - smape: 0.2871 - val_ia: 0.6797 - val_loss: 0.0386 - val_mae: 0.1651 - val_rmse: 0.1841 - val_smape: 0.3466

Epoch 12/16

1147/1147 - 5s - 4ms/step - ia: 0.9179 - loss: 0.0329 - mae: 0.1318 - rmse: 0.1782 - smape: 0.2799 - val_ia: 0.6877 - val_loss: 0.0362 - val_mae: 0.1599 - val_rmse: 0.1784 - val_smape: 0.3513

Epoch 13/16

1147/1147 - 5s - 4ms/step - ia: 0.9188 - loss: 0.0323 - mae: 0.1304 - rmse: 0.1766 - smape: 0.2763 - val_ia: 0.6775 - val_loss: 0.0390 - val_mae: 0.1675 - val_rmse: 0.1850 - val_smape: 0.3592

Epoch 14/16

1147/1147 - 4s - 4ms/step - ia: 0.9194 - loss: 0.0317 - mae: 0.1294 - rmse: 0.1748 - smape: 0.2738 - val_ia: 0.6820 - val_loss: 0.0378 - val_mae: 0.1639 - val_rmse: 0.1824 - val_smape: 0.3577

Epoch 15/16

1147/1147 - 3s - 2ms/step - ia: 0.9204 - loss: 0.0311 - mae: 0.1279 - rmse: 0.1733 - smape: 0.2692 - val_ia: 0.6906 - val_loss: 0.0354 - val_mae: 0.1578 - val_rmse: 0.1760 - val_smape: 0.3438

Epoch 16/16

1147/1147 - 3s - 3ms/step - ia: 0.9213 - loss: 0.0307 - mae: 0.1265 - rmse: 0.1720 - smape: 0.2686 - val_ia: 0.6989 - val_loss: 0.0334 - val_mae: 0.1535 - val_rmse: 0.1714 - val_smape: 0.3361

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 39s 246ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/8

 20%|██        | 10/50 [37:16<1:41:50, 152.77s/trial, best loss: 0.0035199541481683635]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 9s - 33ms/step - ia: 0.1983 - loss: 9.5888 - mae: 2.2665 - rmse: 3.0861 - smape: 1.5495 - val_ia: 0.1870 - val_loss: 2.4268 - val_mae: 1.2730 - val_rmse: 1.5407 - val_smape: 1.5917

Epoch 2/8

287/287 - 1s - 4ms/step - ia: 0.2025 - loss: 9.4156 - mae: 2.2430 - rmse: 3.0562 - smape: 1.5405 - val_ia: 0.1938 - val_loss: 2.3270 - val_mae: 1.2458 - val_rmse: 1.5082 - val_smape: 1.5818

Epoch 3/8

287/287 - 1s - 4ms/step - ia: 0.2076 - loss: 8.9233 - mae: 2.1941 - rmse: 2.9776 - smape: 1.5371 - val_ia: 0.1999 - val_loss: 2.2401 - val_mae: 1.2216 - val_rmse: 1.4793 - val_smape: 1.5745

Epoch 4/8

287/287 - 1s - 5ms/step - ia: 0.2082 - loss: 8.8460 - mae: 2.1882 - rmse: 2.9626 - smape: 1.5394 - val_ia: 0.2064 - val_loss: 2.1516 - val_mae: 1.1966 - val_rmse: 1.4494 - val_smape: 1.5659

Epoch 5/8

287/287 - 1s - 5ms/step - ia: 0.2135 - loss: 8.6667 - mae: 2.1568 - rmse: 2.9343 - smape: 1.5291 - val_ia: 0.2126 - val_loss: 2.0720 - val_mae: 1.1738 - val_rmse: 1.4219 - val_smape: 1.5568

Epoch 6/8

287/287 - 1s - 3ms/step - ia: 0.2132 - loss: 8.6113 - mae: 2.1552 - rmse: 2.9241 - smape: 1.5283 - val_ia: 0.2189 - val_loss: 1.9938 - val_mae: 1.1510 - val_rmse: 1.3944 - val_smape: 1.5454

Epoch 7/8

287/287 - 1s - 3ms/step - ia: 0.2179 - loss: 8.1902 - mae: 2.1149 - rmse: 2.8520 - smape: 1.5295 - val_ia: 0.2249 - val_loss: 1.9247 - val_mae: 1.1306 - val_rmse: 1.3696 - val_smape: 1.5358

Epoch 8/8

287/287 - 1s - 4ms/step - ia: 0.2211 - loss: 8.1464 - mae: 2.1009 - rmse: 2.8435 - smape: 1.5202 - val_ia: 0.2306 - val_loss: 1.8613 - val_mae: 1.1116 - val_rmse: 1.3466 - val_smape: 1.5269

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 35s 217ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 22%|██▏       | 11/50 [37:35<1:12:38, 111.76s/trial, best loss: 0.0035199541481683635]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 9s - 8ms/step - ia: 0.8026 - loss: 0.1708 - mae: 0.3186 - rmse: 0.3972 - smape: 0.6307 - val_ia: 0.7875 - val_loss: 0.0211 - val_mae: 0.1062 - val_rmse: 0.1340 - val_smape: 0.3031

Epoch 2/128

1147/1147 - 5s - 4ms/step - ia: 0.8687 - loss: 0.0728 - mae: 0.2126 - rmse: 0.2662 - smape: 0.4821 - val_ia: 0.8024 - val_loss: 0.0169 - val_mae: 0.0969 - val_rmse: 0.1207 - val_smape: 0.2772

Epoch 3/128

1147/1147 - 3s - 3ms/step - ia: 0.9002 - loss: 0.0425 - mae: 0.1609 - rmse: 0.2034 - smape: 0.3967 - val_ia: 0.8044 - val_loss: 0.0160 - val_mae: 0.0951 - val_rmse: 0.1169 - val_smape: 0.2573

Epoch 4/128

1147/1147 - 2s - 2ms/step - ia: 0.9153 - loss: 0.0312 - mae: 0.1368 - rmse: 0.1742 - smape: 0.3437 - val_ia: 0.8265 - val_loss: 0.0125 - val_mae: 0.0828 - val_rmse: 0.1033 - val_smape: 0.2211

Epoch 5/128

1147/1147 - 2s - 2ms/step - ia: 0.9227 - loss: 0.0262 - mae: 0.1248 - rmse: 0.1596 - smape: 0.3159 - val_ia: 0.8284 - val_loss: 0.0118 - val_mae: 0.0805 - val_rmse: 0.0999 - val_smape: 0.2063

Epoch 6/128

1147/1147 - 2s - 2ms/step - ia: 0.9273 - loss: 0.0236 - mae: 0.1177 - rmse: 0.1512 - smape: 0.2993 - val_ia: 0.8411 - val_loss: 0.0102 - val_mae: 0.0743 - val_rmse: 0.0929 - val_smape: 0.1880

Epoch 7/128

1147/1147 - 3s - 2ms/step - ia: 0.9300 - loss: 0.0218 - mae: 0.1135 - rmse: 0.1452 - smape: 0.2913 - val_ia: 0.8399 - val_loss: 0.0102 - val_mae: 0.0740 - val_rmse: 0.0923 - val_smape: 0.1787

Epoch 8/128

1147/1147 - 3s - 2ms/step - ia: 0.9316 - loss: 0.0208 - mae: 0.1107 - rmse: 0.1419 - smape: 0.2850 - val_ia: 0.8438 - val_loss: 0.0097 - val_mae: 0.0723 - val_rmse: 0.0900 - val_smape: 0.1747

Epoch 9/128

1147/1147 - 2s - 2ms/step - ia: 0.9335 - loss: 0.0199 - mae: 0.1077 - rmse: 0.1388 - smape: 0.2798 - val_ia: 0.8492 - val_loss: 0.0090 - val_mae: 0.0690 - val_rmse: 0.0864 - val_smape: 0.1657

Epoch 10/128

1147/1147 - 3s - 3ms/step - ia: 0.9352 - loss: 0.0189 - mae: 0.1049 - rmse: 0.1351 - smape: 0.2711 - val_ia: 0.8507 - val_loss: 0.0088 - val_mae: 0.0680 - val_rmse: 0.0855 - val_smape: 0.1643

Epoch 11/128

1147/1147 - 3s - 3ms/step - ia: 0.9363 - loss: 0.0183 - mae: 0.1032 - rmse: 0.1331 - smape: 0.2675 - val_ia: 0.8416 - val_loss: 0.0095 - val_mae: 0.0719 - val_rmse: 0.0881 - val_smape: 0.1725

Epoch 12/128

1147/1147 - 6s - 5ms/step - ia: 0.9382 - loss: 0.0172 - mae: 0.1000 - rmse: 0.1289 - smape: 0.2620 - val_ia: 0.8546 - val_loss: 0.0079 - val_mae: 0.0662 - val_rmse: 0.0822 - val_smape: 0.1683

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.9390 - loss: 0.0169 - mae: 0.0987 - rmse: 0.1276 - smape: 0.2619 - val_ia: 0.8477 - val_loss: 0.0088 - val_mae: 0.0688 - val_rmse: 0.0850 - val_smape: 0.1633

Epoch 14/128

1147/1147 - 3s - 3ms/step - ia: 0.9403 - loss: 0.0162 - mae: 0.0965 - rmse: 0.1250 - smape: 0.2544 - val_ia: 0.8568 - val_loss: 0.0077 - val_mae: 0.0641 - val_rmse: 0.0802 - val_smape: 0.1548

Epoch 15/128

1147/1147 - 3s - 3ms/step - ia: 0.9413 - loss: 0.0158 - mae: 0.0951 - rmse: 0.1235 - smape: 0.2525 - val_ia: 0.8482 - val_loss: 0.0088 - val_mae: 0.0693 - val_rmse: 0.0857 - val_smape: 0.1638

Epoch 16/128

1147/1147 - 3s - 3ms/step - ia: 0.9417 - loss: 0.0155 - mae: 0.0943 - rmse: 0.1223 - smape: 0.2502 - val_ia: 0.8494 - val_loss: 0.0091 - val_mae: 0.0693 - val_rmse: 0.0858 - val_smape: 0.1537

Epoch 17/128

1147/1147 - 5s - 4ms/step - ia: 0.9424 - loss: 0.0153 - mae: 0.0932 - rmse: 0.1213 - smape: 0.2476 - val_ia: 0.8416 - val_loss: 0.0094 - val_mae: 0.0719 - val_rmse: 0.0878 - val_smape: 0.1619

Epoch 18/128

1147/1147 - 3s - 3ms/step - ia: 0.9438 - loss: 0.0147 - mae: 0.0911 - rmse: 0.1185 - smape: 0.2454 - val_ia: 0.8582 - val_loss: 0.0076 - val_mae: 0.0631 - val_rmse: 0.0788 - val_smape: 0.1464

Epoch 19/128

1147/1147 - 3s - 3ms/step - ia: 0.9443 - loss: 0.0142 - mae: 0.0899 - rmse: 0.1169 - smape: 0.2399 - val_ia: 0.8469 - val_loss: 0.0083 - val_mae: 0.0686 - val_rmse: 0.0831 - val_smape: 0.1711

Epoch 20/128

1147/1147 - 4s - 4ms/step - ia: 0.9446 - loss: 0.0142 - mae: 0.0895 - rmse: 0.1166 - smape: 0.2398 - val_ia: 0.8482 - val_loss: 0.0080 - val_mae: 0.0671 - val_rmse: 0.0816 - val_smape: 0.1629

Epoch 21/128

1147/1147 - 2s - 2ms/step - ia: 0.9453 - loss: 0.0138 - mae: 0.0884 - rmse: 0.1151 - smape: 0.2372 - val_ia: 0.8574 - val_loss: 0.0072 - val_mae: 0.0632 - val_rmse: 0.0779 - val_smape: 0.1542

Epoch 22/128

1147/1147 - 2s - 2ms/step - ia: 0.9463 - loss: 0.0133 - mae: 0.0867 - rmse: 0.1127 - smape: 0.2312 - val_ia: 0.8549 - val_loss: 0.0072 - val_mae: 0.0644 - val_rmse: 0.0783 - val_smape: 0.1729

Epoch 23/128

1147/1147 - 2s - 2ms/step - ia: 0.9471 - loss: 0.0130 - mae: 0.0855 - rmse: 0.1113 - smape: 0.2304 - val_ia: 0.8652 - val_loss: 0.0064 - val_mae: 0.0588 - val_rmse: 0.0735 - val_smape: 0.1436

Epoch 24/128

1147/1147 - 4s - 3ms/step - ia: 0.9474 - loss: 0.0129 - mae: 0.0850 - rmse: 0.1113 - smape: 0.2295 - val_ia: 0.8562 - val_loss: 0.0074 - val_mae: 0.0640 - val_rmse: 0.0786 - val_smape: 0.1578

Epoch 25/128

1147/1147 - 4s - 4ms/step - ia: 0.9484 - loss: 0.0124 - mae: 0.0835 - rmse: 0.1088 - smape: 0.2262 - val_ia: 0.8673 - val_loss: 0.0063 - val_mae: 0.0583 - val_rmse: 0.0730 - val_smape: 0.1412

Epoch 26/128

1147/1147 - 2s - 2ms/step - ia: 0.9490 - loss: 0.0122 - mae: 0.0825 - rmse: 0.1079 - smape: 0.2244 - val_ia: 0.8598 - val_loss: 0.0065 - val_mae: 0.0601 - val_rmse: 0.0742 - val_smape: 0.1494

Epoch 27/128

1147/1147 - 3s - 2ms/step - ia: 0.9494 - loss: 0.0120 - mae: 0.0819 - rmse: 0.1074 - smape: 0.2221 - val_ia: 0.8703 - val_loss: 0.0058 - val_mae: 0.0559 - val_rmse: 0.0702 - val_smape: 0.1387

Epoch 28/128

1147/1147 - 2s - 2ms/step - ia: 0.9496 - loss: 0.0118 - mae: 0.0814 - rmse: 0.1061 - smape: 0.2214 - val_ia: 0.8671 - val_loss: 0.0058 - val_mae: 0.0564 - val_rmse: 0.0702 - val_smape: 0.1452

Epoch 29/128

1147/1147 - 3s - 2ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0803 - rmse: 0.1051 - smape: 0.2171 - val_ia: 0.8600 - val_loss: 0.0063 - val_mae: 0.0595 - val_rmse: 0.0732 - val_smape: 0.1510

Epoch 30/128

1147/1147 - 2s - 2ms/step - ia: 0.9513 - loss: 0.0112 - mae: 0.0787 - rmse: 0.1032 - smape: 0.2152 - val_ia: 0.8822 - val_loss: 0.0047 - val_mae: 0.0500 - val_rmse: 0.0635 - val_smape: 0.1363

Epoch 31/128

1147/1147 - 3s - 3ms/step - ia: 0.9515 - loss: 0.0111 - mae: 0.0784 - rmse: 0.1029 - smape: 0.2147 - val_ia: 0.8774 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0655 - val_smape: 0.1433

Epoch 32/128

1147/1147 - 5s - 4ms/step - ia: 0.9521 - loss: 0.0109 - mae: 0.0775 - rmse: 0.1018 - smape: 0.2112 - val_ia: 0.8926 - val_loss: 0.0042 - val_mae: 0.0465 - val_rmse: 0.0603 - val_smape: 0.1303

Epoch 33/128

1147/1147 - 3s - 3ms/step - ia: 0.9523 - loss: 0.0108 - mae: 0.0771 - rmse: 0.1014 - smape: 0.2110 - val_ia: 0.8854 - val_loss: 0.0046 - val_mae: 0.0486 - val_rmse: 0.0625 - val_smape: 0.1297

Epoch 34/128

1147/1147 - 3s - 3ms/step - ia: 0.9522 - loss: 0.0107 - mae: 0.0770 - rmse: 0.1012 - smape: 0.2090 - val_ia: 0.8947 - val_loss: 0.0041 - val_mae: 0.0455 - val_rmse: 0.0593 - val_smape: 0.1286

Epoch 35/128

1147/1147 - 3s - 3ms/step - ia: 0.9530 - loss: 0.0105 - mae: 0.0758 - rmse: 0.0999 - smape: 0.2078 - val_ia: 0.8592 - val_loss: 0.0059 - val_mae: 0.0581 - val_rmse: 0.0713 - val_smape: 0.1513

Epoch 36/128

1147/1147 - 5s - 5ms/step - ia: 0.9535 - loss: 0.0102 - mae: 0.0749 - rmse: 0.0985 - smape: 0.2052 - val_ia: 0.8830 - val_loss: 0.0045 - val_mae: 0.0490 - val_rmse: 0.0625 - val_smape: 0.1330

Epoch 37/128

1147/1147 - 3s - 3ms/step - ia: 0.9539 - loss: 0.0101 - mae: 0.0744 - rmse: 0.0980 - smape: 0.2044 - val_ia: 0.8792 - val_loss: 0.0046 - val_mae: 0.0503 - val_rmse: 0.0634 - val_smape: 0.1453

Epoch 38/128

1147/1147 - 3s - 2ms/step - ia: 0.9542 - loss: 0.0101 - mae: 0.0739 - rmse: 0.0978 - smape: 0.2039 - val_ia: 0.9017 - val_loss: 0.0037 - val_mae: 0.0429 - val_rmse: 0.0568 - val_smape: 0.1259

Epoch 39/128

1147/1147 - 2s - 2ms/step - ia: 0.9545 - loss: 0.0100 - mae: 0.0735 - rmse: 0.0974 - smape: 0.2001 - val_ia: 0.8981 - val_loss: 0.0038 - val_mae: 0.0434 - val_rmse: 0.0572 - val_smape: 0.1247

Epoch 40/128

1147/1147 - 2s - 2ms/step - ia: 0.9547 - loss: 0.0099 - mae: 0.0732 - rmse: 0.0968 - smape: 0.2017 - val_ia: 0.9040 - val_loss: 0.0037 - val_mae: 0.0422 - val_rmse: 0.0560 - val_smape: 0.1280

Epoch 41/128

1147/1147 - 2s - 2ms/step - ia: 0.9551 - loss: 0.0097 - mae: 0.0725 - rmse: 0.0959 - smape: 0.1986 - val_ia: 0.8880 - val_loss: 0.0041 - val_mae: 0.0463 - val_rmse: 0.0597 - val_smape: 0.1328

Epoch 42/128

1147/1147 - 2s - 2ms/step - ia: 0.9553 - loss: 0.0096 - mae: 0.0722 - rmse: 0.0954 - smape: 0.1962 - val_ia: 0.9052 - val_loss: 0.0036 - val_mae: 0.0419 - val_rmse: 0.0556 - val_smape: 0.1288

Epoch 43/128

1147/1147 - 2s - 2ms/step - ia: 0.9553 - loss: 0.0096 - mae: 0.0722 - rmse: 0.0955 - smape: 0.1974 - val_ia: 0.8767 - val_loss: 0.0046 - val_mae: 0.0509 - val_rmse: 0.0636 - val_smape: 0.1554

Epoch 44/128

1147/1147 - 2s - 2ms/step - ia: 0.9557 - loss: 0.0095 - mae: 0.0716 - rmse: 0.0948 - smape: 0.1968 - val_ia: 0.9062 - val_loss: 0.0035 - val_mae: 0.0405 - val_rmse: 0.0542 - val_smape: 0.1250

Epoch 45/128

1147/1147 - 3s - 3ms/step - ia: 0.9561 - loss: 0.0094 - mae: 0.0710 - rmse: 0.0942 - smape: 0.1940 - val_ia: 0.8994 - val_loss: 0.0036 - val_mae: 0.0424 - val_rmse: 0.0559 - val_smape: 0.1291

Epoch 46/128

1147/1147 - 5s - 5ms/step - ia: 0.9560 - loss: 0.0094 - mae: 0.0710 - rmse: 0.0941 - smape: 0.1949 - val_ia: 0.9005 - val_loss: 0.0035 - val_mae: 0.0418 - val_rmse: 0.0553 - val_smape: 0.1304

Epoch 47/128

1147/1147 - 3s - 3ms/step - ia: 0.9563 - loss: 0.0093 - mae: 0.0705 - rmse: 0.0936 - smape: 0.1918 - val_ia: 0.8969 - val_loss: 0.0036 - val_mae: 0.0424 - val_rmse: 0.0559 - val_smape: 0.1257

Epoch 48/128

1147/1147 - 5s - 5ms/step - ia: 0.9565 - loss: 0.0092 - mae: 0.0701 - rmse: 0.0931 - smape: 0.1921 - val_ia: 0.8985 - val_loss: 0.0037 - val_mae: 0.0436 - val_rmse: 0.0568 - val_smape: 0.1376

Epoch 49/128

1147/1147 - 3s - 3ms/step - ia: 0.9566 - loss: 0.0092 - mae: 0.0700 - rmse: 0.0931 - smape: 0.1908 - val_ia: 0.8911 - val_loss: 0.0039 - val_mae: 0.0450 - val_rmse: 0.0583 - val_smape: 0.1374

Epoch 50/128

1147/1147 - 7s - 6ms/step - ia: 0.9568 - loss: 0.0092 - mae: 0.0697 - rmse: 0.0929 - smape: 0.1899 - val_ia: 0.9104 - val_loss: 0.0033 - val_mae: 0.0391 - val_rmse: 0.0529 - val_smape: 0.1188

Epoch 51/128

1147/1147 - 4s - 4ms/step - ia: 0.9570 - loss: 0.0091 - mae: 0.0696 - rmse: 0.0926 - smape: 0.1904 - val_ia: 0.8954 - val_loss: 0.0038 - val_mae: 0.0447 - val_rmse: 0.0577 - val_smape: 0.1412

Epoch 52/128

1147/1147 - 6s - 6ms/step - ia: 0.9569 - loss: 0.0090 - mae: 0.0695 - rmse: 0.0923 - smape: 0.1895 - val_ia: 0.9074 - val_loss: 0.0033 - val_mae: 0.0397 - val_rmse: 0.0534 - val_smape: 0.1243

Epoch 53/128

1147/1147 - 5s - 4ms/step - ia: 0.9575 - loss: 0.0088 - mae: 0.0686 - rmse: 0.0912 - smape: 0.1884 - val_ia: 0.8976 - val_loss: 0.0037 - val_mae: 0.0433 - val_rmse: 0.0566 - val_smape: 0.1350

Epoch 54/128

1147/1147 - 4s - 4ms/step - ia: 0.9572 - loss: 0.0089 - mae: 0.0690 - rmse: 0.0919 - smape: 0.1890 - val_ia: 0.8964 - val_loss: 0.0036 - val_mae: 0.0427 - val_rmse: 0.0562 - val_smape: 0.1305

Epoch 55/128

1147/1147 - 5s - 4ms/step - ia: 0.9574 - loss: 0.0089 - mae: 0.0686 - rmse: 0.0915 - smape: 0.1881 - val_ia: 0.8968 - val_loss: 0.0037 - val_mae: 0.0432 - val_rmse: 0.0566 - val_smape: 0.1359

Epoch 56/128

1147/1147 - 3s - 3ms/step - ia: 0.9576 - loss: 0.0088 - mae: 0.0684 - rmse: 0.0912 - smape: 0.1892 - val_ia: 0.8977 - val_loss: 0.0035 - val_mae: 0.0423 - val_rmse: 0.0556 - val_smape: 0.1333

Epoch 57/128

1147/1147 - 3s - 3ms/step - ia: 0.9576 - loss: 0.0088 - mae: 0.0685 - rmse: 0.0912 - smape: 0.1880 - val_ia: 0.9110 - val_loss: 0.0031 - val_mae: 0.0380 - val_rmse: 0.0514 - val_smape: 0.1198

Epoch 58/128

1147/1147 - 3s - 3ms/step - ia: 0.9579 - loss: 0.0087 - mae: 0.0679 - rmse: 0.0907 - smape: 0.1866 - val_ia: 0.8933 - val_loss: 0.0037 - val_mae: 0.0442 - val_rmse: 0.0572 - val_smape: 0.1384

Epoch 59/128

1147/1147 - 5s - 5ms/step - ia: 0.9576 - loss: 0.0088 - mae: 0.0683 - rmse: 0.0913 - smape: 0.1850 - val_ia: 0.9053 - val_loss: 0.0034 - val_mae: 0.0409 - val_rmse: 0.0542 - val_smape: 0.1315

Epoch 60/128

1147/1147 - 5s - 4ms/step - ia: 0.9579 - loss: 0.0087 - mae: 0.0678 - rmse: 0.0905 - smape: 0.1860 - val_ia: 0.9021 - val_loss: 0.0034 - val_mae: 0.0411 - val_rmse: 0.0545 - val_smape: 0.1302

Epoch 61/128

1147/1147 - 5s - 5ms/step - ia: 0.9580 - loss: 0.0086 - mae: 0.0678 - rmse: 0.0903 - smape: 0.1860 - val_ia: 0.8988 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0558 - val_smape: 0.1331

Epoch 62/128

1147/1147 - 3s - 3ms/step - ia: 0.9578 - loss: 0.0088 - mae: 0.0680 - rmse: 0.0908 - smape: 0.1851 - val_ia: 0.8989 - val_loss: 0.0035 - val_mae: 0.0418 - val_rmse: 0.0551 - val_smape: 0.1328

Epoch 63/128

1147/1147 - 5s - 5ms/step - ia: 0.9582 - loss: 0.0087 - mae: 0.0674 - rmse: 0.0903 - smape: 0.1843 - val_ia: 0.9109 - val_loss: 0.0031 - val_mae: 0.0384 - val_rmse: 0.0518 - val_smape: 0.1226

Epoch 64/128

1147/1147 - 4s - 4ms/step - ia: 0.9580 - loss: 0.0087 - mae: 0.0677 - rmse: 0.0906 - smape: 0.1837 - val_ia: 0.8960 - val_loss: 0.0035 - val_mae: 0.0426 - val_rmse: 0.0557 - val_smape: 0.1339

Epoch 65/128

1147/1147 - 2s - 2ms/step - ia: 0.9580 - loss: 0.0086 - mae: 0.0675 - rmse: 0.0902 - smape: 0.1847 - val_ia: 0.9000 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0547 - val_smape: 0.1326

Epoch 66/128

1147/1147 - 3s - 2ms/step - ia: 0.9585 - loss: 0.0084 - mae: 0.0668 - rmse: 0.0892 - smape: 0.1829 - val_ia: 0.8813 - val_loss: 0.0041 - val_mae: 0.0477 - val_rmse: 0.0604 - val_smape: 0.1472

Epoch 67/128

1147/1147 - 2s - 2ms/step - ia: 0.9583 - loss: 0.0085 - mae: 0.0672 - rmse: 0.0897 - smape: 0.1836 - val_ia: 0.9036 - val_loss: 0.0034 - val_mae: 0.0407 - val_rmse: 0.0542 - val_smape: 0.1292

Epoch 68/128

1147/1147 - 3s - 2ms/step - ia: 0.9586 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0894 - smape: 0.1834 - val_ia: 0.9015 - val_loss: 0.0034 - val_mae: 0.0411 - val_rmse: 0.0544 - val_smape: 0.1301

Epoch 69/128

1147/1147 - 2s - 2ms/step - ia: 0.9586 - loss: 0.0084 - mae: 0.0666 - rmse: 0.0893 - smape: 0.1807 - val_ia: 0.9094 - val_loss: 0.0032 - val_mae: 0.0389 - val_rmse: 0.0523 - val_smape: 0.1276

Epoch 70/128

1147/1147 - 2s - 2ms/step - ia: 0.9585 - loss: 0.0085 - mae: 0.0669 - rmse: 0.0894 - smape: 0.1805 - val_ia: 0.8862 - val_loss: 0.0038 - val_mae: 0.0451 - val_rmse: 0.0580 - val_smape: 0.1392

Epoch 71/128

1147/1147 - 3s - 3ms/step - ia: 0.9584 - loss: 0.0086 - mae: 0.0671 - rmse: 0.0899 - smape: 0.1826 - val_ia: 0.8957 - val_loss: 0.0036 - val_mae: 0.0433 - val_rmse: 0.0564 - val_smape: 0.1397

Epoch 72/128

1147/1147 - 5s - 5ms/step - ia: 0.9588 - loss: 0.0084 - mae: 0.0665 - rmse: 0.0889 - smape: 0.1831 - val_ia: 0.9094 - val_loss: 0.0032 - val_mae: 0.0389 - val_rmse: 0.0523 - val_smape: 0.1302

Epoch 72: early stopping

Restoring model weights from the end of the best epoch: 57.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 21s 132ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 24%|██▍       | 12/50 [41:50<1:38:30, 155.54s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 7s - 25ms/step - ia: 0.6464 - loss: 0.9621 - mae: 0.6382 - rmse: 0.8332 - smape: 0.9093 - val_ia: 0.8304 - val_loss: 0.0929 - val_mae: 0.2350 - val_rmse: 0.2945 - val_smape: 0.5628

Epoch 2/16

287/287 - 1s - 4ms/step - ia: 0.8090 - loss: 0.1697 - mae: 0.3090 - rmse: 0.4093 - smape: 0.6081 - val_ia: 0.8726 - val_loss: 0.0509 - val_mae: 0.1733 - val_rmse: 0.2197 - val_smape: 0.4592

Epoch 3/16

287/287 - 1s - 5ms/step - ia: 0.8454 - loss: 0.1122 - mae: 0.2497 - rmse: 0.3333 - smape: 0.5132 - val_ia: 0.8923 - val_loss: 0.0358 - val_mae: 0.1451 - val_rmse: 0.1846 - val_smape: 0.3935

Epoch 4/16

287/287 - 1s - 5ms/step - ia: 0.8633 - loss: 0.0898 - mae: 0.2211 - rmse: 0.2981 - smape: 0.4636 - val_ia: 0.8940 - val_loss: 0.0320 - val_mae: 0.1417 - val_rmse: 0.1741 - val_smape: 0.3803

Epoch 5/16

287/287 - 1s - 5ms/step - ia: 0.8744 - loss: 0.0770 - mae: 0.2031 - rmse: 0.2763 - smape: 0.4265 - val_ia: 0.9155 - val_loss: 0.0216 - val_mae: 0.1125 - val_rmse: 0.1444 - val_smape: 0.2983

Epoch 6/16

287/287 - 1s - 4ms/step - ia: 0.8844 - loss: 0.0655 - mae: 0.1871 - rmse: 0.2548 - smape: 0.3978 - val_ia: 0.9170 - val_loss: 0.0204 - val_mae: 0.1113 - val_rmse: 0.1388 - val_smape: 0.3079

Epoch 7/16

287/287 - 1s - 3ms/step - ia: 0.8917 - loss: 0.0587 - mae: 0.1756 - rmse: 0.2410 - smape: 0.3726 - val_ia: 0.9153 - val_loss: 0.0202 - val_mae: 0.1133 - val_rmse: 0.1377 - val_smape: 0.3161

Epoch 8/16

287/287 - 2s - 6ms/step - ia: 0.8964 - loss: 0.0538 - mae: 0.1679 - rmse: 0.2310 - smape: 0.3569 - val_ia: 0.9303 - val_loss: 0.0146 - val_mae: 0.0934 - val_rmse: 0.1176 - val_smape: 0.2660

Epoch 9/16

287/287 - 1s - 4ms/step - ia: 0.9002 - loss: 0.0503 - mae: 0.1620 - rmse: 0.2230 - smape: 0.3412 - val_ia: 0.9319 - val_loss: 0.0139 - val_mae: 0.0907 - val_rmse: 0.1149 - val_smape: 0.2532

Epoch 10/16

287/287 - 1s - 3ms/step - ia: 0.9049 - loss: 0.0458 - mae: 0.1542 - rmse: 0.2130 - smape: 0.3287 - val_ia: 0.9434 - val_loss: 0.0103 - val_mae: 0.0761 - val_rmse: 0.0991 - val_smape: 0.2248

Epoch 11/16

287/287 - 1s - 5ms/step - ia: 0.9071 - loss: 0.0440 - mae: 0.1509 - rmse: 0.2087 - smape: 0.3194 - val_ia: 0.9388 - val_loss: 0.0112 - val_mae: 0.0817 - val_rmse: 0.1034 - val_smape: 0.2248

Epoch 12/16

287/287 - 1s - 4ms/step - ia: 0.9104 - loss: 0.0415 - mae: 0.1458 - rmse: 0.2027 - smape: 0.3073 - val_ia: 0.9389 - val_loss: 0.0111 - val_mae: 0.0814 - val_rmse: 0.1031 - val_smape: 0.2153

Epoch 13/16

287/287 - 1s - 3ms/step - ia: 0.9128 - loss: 0.0393 - mae: 0.1416 - rmse: 0.1969 - smape: 0.2973 - val_ia: 0.9341 - val_loss: 0.0122 - val_mae: 0.0877 - val_rmse: 0.1070 - val_smape: 0.2442

Epoch 14/16

287/287 - 1s - 5ms/step - ia: 0.9153 - loss: 0.0371 - mae: 0.1377 - rmse: 0.1917 - smape: 0.2893 - val_ia: 0.9489 - val_loss: 0.0080 - val_mae: 0.0688 - val_rmse: 0.0873 - val_smape: 0.1997

Epoch 15/16

287/287 - 1s - 5ms/step - ia: 0.9174 - loss: 0.0355 - mae: 0.1343 - rmse: 0.1875 - smape: 0.2822 - val_ia: 0.9479 - val_loss: 0.0083 - val_mae: 0.0694 - val_rmse: 0.0884 - val_smape: 0.2060

Epoch 16/16

287/287 - 2s - 5ms/step - ia: 0.9189 - loss: 0.0344 - mae: 0.1319 - rmse: 0.1845 - smape: 0.2770 - val_ia: 0.9541 - val_loss: 0.0066 - val_mae: 0.0619 - val_rmse: 0.0796 - val_smape: 0.1835

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 17s 111ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 26%|██▌       | 13/50 [42:19<1:12:10, 117.05s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 6s - 19ms/step - ia: 0.5164 - loss: 1.5185 - mae: 0.9242 - rmse: 1.2143 - smape: 1.1367 - val_ia: 0.8064 - val_loss: 0.1344 - val_mae: 0.2658 - val_rmse: 0.3639 - val_smape: 0.6317

Epoch 2/8

287/287 - 1s - 4ms/step - ia: 0.6439 - loss: 0.7158 - mae: 0.6387 - rmse: 0.8407 - smape: 0.9246 - val_ia: 0.8725 - val_loss: 0.0661 - val_mae: 0.1735 - val_rmse: 0.2550 - val_smape: 0.4358

Epoch 3/8

287/287 - 1s - 4ms/step - ia: 0.7132 - loss: 0.4411 - mae: 0.5010 - rmse: 0.6606 - smape: 0.8049 - val_ia: 0.8953 - val_loss: 0.0453 - val_mae: 0.1390 - val_rmse: 0.2118 - val_smape: 0.3399

Epoch 4/8

287/287 - 1s - 3ms/step - ia: 0.7574 - loss: 0.3124 - mae: 0.4173 - rmse: 0.5563 - smape: 0.7245 - val_ia: 0.9095 - val_loss: 0.0345 - val_mae: 0.1229 - val_rmse: 0.1847 - val_smape: 0.3240

Epoch 5/8

287/287 - 1s - 5ms/step - ia: 0.7845 - loss: 0.2453 - mae: 0.3672 - rmse: 0.4927 - smape: 0.6727 - val_ia: 0.9182 - val_loss: 0.0277 - val_mae: 0.1106 - val_rmse: 0.1655 - val_smape: 0.2911

Epoch 6/8

287/287 - 1s - 3ms/step - ia: 0.8049 - loss: 0.1989 - mae: 0.3293 - rmse: 0.4439 - smape: 0.6282 - val_ia: 0.9244 - val_loss: 0.0231 - val_mae: 0.1025 - val_rmse: 0.1512 - val_smape: 0.2788

Epoch 7/8

287/287 - 1s - 5ms/step - ia: 0.8224 - loss: 0.1640 - mae: 0.2983 - rmse: 0.4029 - smape: 0.5909 - val_ia: 0.9287 - val_loss: 0.0196 - val_mae: 0.0964 - val_rmse: 0.1394 - val_smape: 0.2649

Epoch 8/8

287/287 - 1s - 4ms/step - ia: 0.8379 - loss: 0.1356 - mae: 0.2707 - rmse: 0.3664 - smape: 0.5551 - val_ia: 0.9303 - val_loss: 0.0175 - val_mae: 0.0933 - val_rmse: 0.1317 - val_smape: 0.2507

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 47s 292ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 28%|██▊       | 14/50 [42:34<51:47, 86.33s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

574/574 - 6s - 11ms/step - ia: 0.8654 - loss: 0.1083 - mae: 0.2228 - rmse: 0.2937 - smape: 0.4283 - val_ia: 0.8936 - val_loss: 0.0187 - val_mae: 0.1089 - val_rmse: 0.1328 - val_smape: 0.2711

Epoch 2/16

574/574 - 2s - 3ms/step - ia: 0.8998 - loss: 0.0499 - mae: 0.1629 - rmse: 0.2213 - smape: 0.3225 - val_ia: 0.9095 - val_loss: 0.0128 - val_mae: 0.0889 - val_rmse: 0.1102 - val_smape: 0.2235

Epoch 3/16

574/574 - 2s - 3ms/step - ia: 0.9040 - loss: 0.0466 - mae: 0.1563 - rmse: 0.2139 - smape: 0.3079 - val_ia: 0.9276 - val_loss: 0.0086 - val_mae: 0.0730 - val_rmse: 0.0910 - val_smape: 0.1712

Epoch 4/16

574/574 - 2s - 4ms/step - ia: 0.9053 - loss: 0.0455 - mae: 0.1544 - rmse: 0.2114 - smape: 0.3001 - val_ia: 0.9031 - val_loss: 0.0150 - val_mae: 0.0889 - val_rmse: 0.1134 - val_smape: 0.1842

Epoch 5/16

574/574 - 1s - 2ms/step - ia: 0.9051 - loss: 0.0458 - mae: 0.1545 - rmse: 0.2121 - smape: 0.2995 - val_ia: 0.9192 - val_loss: 0.0108 - val_mae: 0.0827 - val_rmse: 0.1016 - val_smape: 0.2078

Epoch 6/16

574/574 - 2s - 3ms/step - ia: 0.9056 - loss: 0.0453 - mae: 0.1532 - rmse: 0.2109 - smape: 0.2977 - val_ia: 0.9188 - val_loss: 0.0102 - val_mae: 0.0795 - val_rmse: 0.0972 - val_smape: 0.2047

Epoch 7/16

574/574 - 2s - 4ms/step - ia: 0.9057 - loss: 0.0452 - mae: 0.1536 - rmse: 0.2106 - smape: 0.2970 - val_ia: 0.9325 - val_loss: 0.0078 - val_mae: 0.0641 - val_rmse: 0.0834 - val_smape: 0.1523

Epoch 8/16

574/574 - 1s - 2ms/step - ia: 0.9067 - loss: 0.0446 - mae: 0.1521 - rmse: 0.2089 - smape: 0.2953 - val_ia: 0.9228 - val_loss: 0.0097 - val_mae: 0.0733 - val_rmse: 0.0924 - val_smape: 0.1739

Epoch 9/16

574/574 - 2s - 4ms/step - ia: 0.9052 - loss: 0.0461 - mae: 0.1544 - rmse: 0.2128 - smape: 0.2990 - val_ia: 0.8946 - val_loss: 0.0148 - val_mae: 0.0977 - val_rmse: 0.1167 - val_smape: 0.2230

Epoch 10/16

574/574 - 2s - 3ms/step - ia: 0.9054 - loss: 0.0457 - mae: 0.1538 - rmse: 0.2114 - smape: 0.2961 - val_ia: 0.9257 - val_loss: 0.0094 - val_mae: 0.0758 - val_rmse: 0.0937 - val_smape: 0.1911

Epoch 11/16

574/574 - 2s - 4ms/step - ia: 0.9059 - loss: 0.0453 - mae: 0.1534 - rmse: 0.2108 - smape: 0.2942 - val_ia: 0.9363 - val_loss: 0.0068 - val_mae: 0.0622 - val_rmse: 0.0793 - val_smape: 0.1545

Epoch 12/16

574/574 - 3s - 4ms/step - ia: 0.9063 - loss: 0.0447 - mae: 0.1525 - rmse: 0.2094 - smape: 0.2930 - val_ia: 0.9119 - val_loss: 0.0118 - val_mae: 0.0884 - val_rmse: 0.1052 - val_smape: 0.2232

Epoch 13/16

574/574 - 3s - 5ms/step - ia: 0.9063 - loss: 0.0452 - mae: 0.1527 - rmse: 0.2105 - smape: 0.2973 - val_ia: 0.9076 - val_loss: 0.0128 - val_mae: 0.0884 - val_rmse: 0.1072 - val_smape: 0.2281

Epoch 14/16

574/574 - 2s - 3ms/step - ia: 0.9065 - loss: 0.0450 - mae: 0.1523 - rmse: 0.2101 - smape: 0.2912 - val_ia: 0.9128 - val_loss: 0.0118 - val_mae: 0.0842 - val_rmse: 0.1029 - val_smape: 0.2155

Epoch 15/16

574/574 - 3s - 5ms/step - ia: 0.9052 - loss: 0.0460 - mae: 0.1544 - rmse: 0.2122 - smape: 0.2960 - val_ia: 0.9142 - val_loss: 0.0107 - val_mae: 0.0792 - val_rmse: 0.0983 - val_smape: 0.1795

Epoch 16/16

574/574 - 2s - 4ms/step - ia: 0.9054 - loss: 0.0462 - mae: 0.1543 - rmse: 0.2131 - smape: 0.2931 - val_ia: 0.9324 - val_loss: 0.0074 - val_mae: 0.0674 - val_rmse: 0.0840 - val_smape: 0.1635

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 29s 180ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/256

 30%|███       | 15/50 [43:13<42:03, 72.09s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4586/4586 - 16s - 3ms/step - ia: 0.8382 - loss: 0.1122 - mae: 0.2329 - rmse: 0.3047 - smape: 0.4288 - val_ia: 0.4516 - val_loss: 0.0239 - val_mae: 0.1220 - val_rmse: 0.1316 - val_smape: 0.2744

Epoch 2/256

4586/4586 - 10s - 2ms/step - ia: 0.8500 - loss: 0.0927 - mae: 0.2154 - rmse: 0.2838 - smape: 0.3902 - val_ia: 0.3430 - val_loss: 0.0703 - val_mae: 0.2195 - val_rmse: 0.2277 - val_smape: 0.3987

Epoch 3/256

4586/4586 - 12s - 3ms/step - ia: 0.8511 - loss: 0.0911 - mae: 0.2136 - rmse: 0.2820 - smape: 0.3815 - val_ia: 0.4533 - val_loss: 0.0165 - val_mae: 0.1116 - val_rmse: 0.1195 - val_smape: 0.3166

Epoch 4/256

4586/4586 - 9s - 2ms/step - ia: 0.8519 - loss: 0.0917 - mae: 0.2135 - rmse: 0.2828 - smape: 0.3767 - val_ia: 0.5020 - val_loss: 0.0149 - val_mae: 0.0966 - val_rmse: 0.1054 - val_smape: 0.2081

Epoch 5/256

4586/4586 - 8s - 2ms/step - ia: 0.8510 - loss: 0.0911 - mae: 0.2129 - rmse: 0.2821 - smape: 0.3764 - val_ia: 0.3692 - val_loss: 0.0535 - val_mae: 0.1900 - val_rmse: 0.1976 - val_smape: 0.3518

Epoch 6/256

4586/4586 - 13s - 3ms/step - ia: 0.8540 - loss: 0.0896 - mae: 0.2107 - rmse: 0.2795 - smape: 0.3747 - val_ia: 0.3763 - val_loss: 0.0487 - val_mae: 0.1828 - val_rmse: 0.1900 - val_smape: 0.3445

Epoch 7/256

4586/4586 - 18s - 4ms/step - ia: 0.8552 - loss: 0.0889 - mae: 0.2094 - rmse: 0.2787 - smape: 0.3699 - val_ia: 0.5687 - val_loss: 0.0080 - val_mae: 0.0700 - val_rmse: 0.0791 - val_smape: 0.1797

Epoch 8/256

4586/4586 - 12s - 3ms/step - ia: 0.8533 - loss: 0.0902 - mae: 0.2107 - rmse: 0.2796 - smape: 0.3707 - val_ia: 0.4818 - val_loss: 0.0194 - val_mae: 0.1120 - val_rmse: 0.1199 - val_smape: 0.2405

Epoch 9/256

4586/4586 - 20s - 4ms/step - ia: 0.8528 - loss: 0.0916 - mae: 0.2123 - rmse: 0.2816 - smape: 0.3740 - val_ia: 0.3803 - val_loss: 0.0561 - val_mae: 0.1971 - val_rmse: 0.2067 - val_smape: 0.3115

Epoch 10/256

4586/4586 - 13s - 3ms/step - ia: 0.8539 - loss: 0.0895 - mae: 0.2097 - rmse: 0.2785 - smape: 0.3681 - val_ia: 0.5485 - val_loss: 0.0090 - val_mae: 0.0761 - val_rmse: 0.0848 - val_smape: 0.1943

Epoch 11/256

4586/4586 - 12s - 3ms/step - ia: 0.8554 - loss: 0.0880 - mae: 0.2081 - rmse: 0.2764 - smape: 0.3691 - val_ia: 0.5840 - val_loss: 0.0072 - val_mae: 0.0659 - val_rmse: 0.0749 - val_smape: 0.1749

Epoch 12/256

4586/4586 - 12s - 3ms/step - ia: 0.8545 - loss: 0.0902 - mae: 0.2097 - rmse: 0.2784 - smape: 0.3682 - val_ia: 0.3253 - val_loss: 0.0907 - val_mae: 0.2484 - val_rmse: 0.2564 - val_smape: 0.4209

Epoch 13/256

4586/4586 - 17s - 4ms/step - ia: 0.8545 - loss: 0.0887 - mae: 0.2101 - rmse: 0.2784 - smape: 0.3678 - val_ia: 0.4148 - val_loss: 0.0368 - val_mae: 0.1568 - val_rmse: 0.1645 - val_smape: 0.2908

Epoch 14/256

4586/4586 - 8s - 2ms/step - ia: 0.8548 - loss: 0.0887 - mae: 0.2094 - rmse: 0.2775 - smape: 0.3681 - val_ia: 0.5773 - val_loss: 0.0065 - val_mae: 0.0644 - val_rmse: 0.0737 - val_smape: 0.1920

Epoch 15/256

4586/4586 - 12s - 3ms/step - ia: 0.8510 - loss: 0.0929 - mae: 0.2137 - rmse: 0.2839 - smape: 0.3742 - val_ia: 0.4374 - val_loss: 0.0253 - val_mae: 0.1306 - val_rmse: 0.1385 - val_smape: 0.2639

Epoch 16/256

4586/4586 - 12s - 3ms/step - ia: 0.8509 - loss: 0.0928 - mae: 0.2136 - rmse: 0.2834 - smape: 0.3754 - val_ia: 0.5196 - val_loss: 0.0128 - val_mae: 0.0907 - val_rmse: 0.0994 - val_smape: 0.1933

Epoch 17/256

4586/4586 - 14s - 3ms/step - ia: 0.8546 - loss: 0.0886 - mae: 0.2090 - rmse: 0.2776 - smape: 0.3675 - val_ia: 0.4061 - val_loss: 0.0476 - val_mae: 0.1780 - val_rmse: 0.1869 - val_smape: 0.2968

Epoch 18/256

4586/4586 - 14s - 3ms/step - ia: 0.8552 - loss: 0.0889 - mae: 0.2092 - rmse: 0.2775 - smape: 0.3694 - val_ia: 0.4477 - val_loss: 0.0263 - val_mae: 0.1366 - val_rmse: 0.1440 - val_smape: 0.2616

Epoch 19/256

4586/4586 - 15s - 3ms/step - ia: 0.8560 - loss: 0.0875 - mae: 0.2077 - rmse: 0.2759 - smape: 0.3640 - val_ia: 0.6196 - val_loss: 0.0061 - val_mae: 0.0584 - val_rmse: 0.0676 - val_smape: 0.1771

Epoch 20/256

4586/4586 - 11s - 2ms/step - ia: 0.8540 - loss: 0.0901 - mae: 0.2108 - rmse: 0.2796 - smape: 0.3708 - val_ia: 0.6003 - val_loss: 0.0066 - val_mae: 0.0612 - val_rmse: 0.0705 - val_smape: 0.1740

Epoch 21/256

4586/4586 - 12s - 3ms/step - ia: 0.8535 - loss: 0.0900 - mae: 0.2109 - rmse: 0.2799 - smape: 0.3701 - val_ia: 0.5701 - val_loss: 0.0086 - val_mae: 0.0718 - val_rmse: 0.0808 - val_smape: 0.1680

Epoch 22/256

4586/4586 - 18s - 4ms/step - ia: 0.8540 - loss: 0.0899 - mae: 0.2101 - rmse: 0.2791 - smape: 0.3701 - val_ia: 0.5683 - val_loss: 0.0076 - val_mae: 0.0692 - val_rmse: 0.0784 - val_smape: 0.1787

Epoch 23/256

4586/4586 - 12s - 3ms/step - ia: 0.8520 - loss: 0.0923 - mae: 0.2123 - rmse: 0.2821 - smape: 0.3717 - val_ia: 0.5403 - val_loss: 0.0105 - val_mae: 0.0841 - val_rmse: 0.0932 - val_smape: 0.2135

Epoch 24/256

4586/4586 - 12s - 3ms/step - ia: 0.8536 - loss: 0.0901 - mae: 0.2111 - rmse: 0.2801 - smape: 0.3727 - val_ia: 0.4670 - val_loss: 0.0205 - val_mae: 0.1143 - val_rmse: 0.1222 - val_smape: 0.2407

Epoch 25/256

4586/4586 - 21s - 5ms/step - ia: 0.8548 - loss: 0.0895 - mae: 0.2092 - rmse: 0.2787 - smape: 0.3678 - val_ia: 0.4429 - val_loss: 0.0267 - val_mae: 0.1338 - val_rmse: 0.1415 - val_smape: 0.2450

Epoch 26/256

4586/4586 - 9s - 2ms/step - ia: 0.8540 - loss: 0.0905 - mae: 0.2110 - rmse: 0.2802 - smape: 0.3707 - val_ia: 0.5587 - val_loss: 0.0074 - val_mae: 0.0709 - val_rmse: 0.0800 - val_smape: 0.2031

Epoch 27/256

4586/4586 - 10s - 2ms/step - ia: 0.8529 - loss: 0.0908 - mae: 0.2121 - rmse: 0.2808 - smape: 0.3719 - val_ia: 0.4001 - val_loss: 0.0404 - val_mae: 0.1652 - val_rmse: 0.1729 - val_smape: 0.2838

Epoch 28/256

4586/4586 - 13s - 3ms/step - ia: 0.8534 - loss: 0.0901 - mae: 0.2103 - rmse: 0.2793 - smape: 0.3684 - val_ia: 0.3794 - val_loss: 0.0434 - val_mae: 0.1729 - val_rmse: 0.1803 - val_smape: 0.3134

Epoch 29/256

4586/4586 - 20s - 4ms/step - ia: 0.8534 - loss: 0.0906 - mae: 0.2112 - rmse: 0.2808 - smape: 0.3713 - val_ia: 0.5345 - val_loss: 0.0136 - val_mae: 0.0924 - val_rmse: 0.1017 - val_smape: 0.2440

Epoch 30/256

4586/4586 - 21s - 5ms/step - ia: 0.8560 - loss: 0.0870 - mae: 0.2078 - rmse: 0.2756 - smape: 0.3648 - val_ia: 0.3865 - val_loss: 0.0454 - val_mae: 0.1752 - val_rmse: 0.1828 - val_smape: 0.2969

Epoch 31/256

4586/4586 - 20s - 4ms/step - ia: 0.8526 - loss: 0.0909 - mae: 0.2120 - rmse: 0.2814 - smape: 0.3728 - val_ia: 0.3564 - val_loss: 0.0604 - val_mae: 0.2036 - val_rmse: 0.2110 - val_smape: 0.3556

Epoch 32/256

4586/4586 - 18s - 4ms/step - ia: 0.8548 - loss: 0.0885 - mae: 0.2089 - rmse: 0.2776 - smape: 0.3687 - val_ia: 0.4298 - val_loss: 0.0275 - val_mae: 0.1374 - val_rmse: 0.1450 - val_smape: 0.2703

Epoch 33/256

4586/4586 - 10s - 2ms/step - ia: 0.8542 - loss: 0.0893 - mae: 0.2099 - rmse: 0.2779 - smape: 0.3682 - val_ia: 0.4336 - val_loss: 0.0258 - val_mae: 0.1342 - val_rmse: 0.1417 - val_smape: 0.2858

Epoch 34/256

4586/4586 - 12s - 3ms/step - ia: 0.8556 - loss: 0.0874 - mae: 0.2074 - rmse: 0.2754 - smape: 0.3674 - val_ia: 0.4583 - val_loss: 0.0231 - val_mae: 0.1252 - val_rmse: 0.1330 - val_smape: 0.2409

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 19s 119ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 32%|███▏      | 16/50 [51:01<1:48:15, 191.05s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4586/4586 - 13s - 3ms/step - ia: 0.8724 - loss: 0.0669 - mae: 0.1848 - rmse: 0.2295 - smape: 0.4104 - val_ia: 0.5481 - val_loss: 0.0109 - val_mae: 0.0789 - val_rmse: 0.0895 - val_smape: 0.2143

Epoch 2/256

4586/4586 - 12s - 3ms/step - ia: 0.9103 - loss: 0.0301 - mae: 0.1312 - rmse: 0.1645 - smape: 0.3161 - val_ia: 0.4992 - val_loss: 0.0164 - val_mae: 0.1008 - val_rmse: 0.1101 - val_smape: 0.2132

Epoch 3/256

4586/4586 - 20s - 4ms/step - ia: 0.9177 - loss: 0.0256 - mae: 0.1203 - rmse: 0.1517 - smape: 0.2893 - val_ia: 0.5407 - val_loss: 0.0128 - val_mae: 0.0850 - val_rmse: 0.0943 - val_smape: 0.1949

Epoch 4/256

4586/4586 - 9s - 2ms/step - ia: 0.9211 - loss: 0.0238 - mae: 0.1153 - rmse: 0.1456 - smape: 0.2777 - val_ia: 0.5610 - val_loss: 0.0116 - val_mae: 0.0799 - val_rmse: 0.0894 - val_smape: 0.2085

Epoch 5/256

4586/4586 - 12s - 3ms/step - ia: 0.9231 - loss: 0.0227 - mae: 0.1127 - rmse: 0.1424 - smape: 0.2713 - val_ia: 0.5662 - val_loss: 0.0097 - val_mae: 0.0739 - val_rmse: 0.0833 - val_smape: 0.1734

Epoch 6/256

4586/4586 - 22s - 5ms/step - ia: 0.9246 - loss: 0.0220 - mae: 0.1107 - rmse: 0.1398 - smape: 0.2644 - val_ia: 0.6005 - val_loss: 0.0062 - val_mae: 0.0601 - val_rmse: 0.0695 - val_smape: 0.1618

Epoch 7/256

4586/4586 - 20s - 4ms/step - ia: 0.9246 - loss: 0.0219 - mae: 0.1104 - rmse: 0.1395 - smape: 0.2635 - val_ia: 0.5901 - val_loss: 0.0086 - val_mae: 0.0684 - val_rmse: 0.0779 - val_smape: 0.1762

Epoch 8/256

4586/4586 - 13s - 3ms/step - ia: 0.9259 - loss: 0.0214 - mae: 0.1086 - rmse: 0.1377 - smape: 0.2585 - val_ia: 0.5888 - val_loss: 0.0073 - val_mae: 0.0653 - val_rmse: 0.0749 - val_smape: 0.1728

Epoch 9/256

4586/4586 - 13s - 3ms/step - ia: 0.9269 - loss: 0.0208 - mae: 0.1073 - rmse: 0.1359 - smape: 0.2560 - val_ia: 0.5055 - val_loss: 0.0135 - val_mae: 0.0944 - val_rmse: 0.1024 - val_smape: 0.2282

Epoch 10/256

4586/4586 - 10s - 2ms/step - ia: 0.9272 - loss: 0.0208 - mae: 0.1072 - rmse: 0.1358 - smape: 0.2555 - val_ia: 0.6035 - val_loss: 0.0062 - val_mae: 0.0603 - val_rmse: 0.0698 - val_smape: 0.1717

Epoch 11/256

4586/4586 - 11s - 2ms/step - ia: 0.9282 - loss: 0.0202 - mae: 0.1053 - rmse: 0.1339 - smape: 0.2524 - val_ia: 0.5366 - val_loss: 0.0112 - val_mae: 0.0835 - val_rmse: 0.0923 - val_smape: 0.2038

Epoch 12/256

4586/4586 - 13s - 3ms/step - ia: 0.9274 - loss: 0.0206 - mae: 0.1061 - rmse: 0.1349 - smape: 0.2518 - val_ia: 0.5915 - val_loss: 0.0069 - val_mae: 0.0638 - val_rmse: 0.0733 - val_smape: 0.1772

Epoch 13/256

4586/4586 - 9s - 2ms/step - ia: 0.9285 - loss: 0.0198 - mae: 0.1045 - rmse: 0.1327 - smape: 0.2489 - val_ia: 0.6225 - val_loss: 0.0057 - val_mae: 0.0562 - val_rmse: 0.0658 - val_smape: 0.1428

Epoch 14/256

4586/4586 - 9s - 2ms/step - ia: 0.9291 - loss: 0.0198 - mae: 0.1043 - rmse: 0.1325 - smape: 0.2479 - val_ia: 0.6398 - val_loss: 0.0050 - val_mae: 0.0523 - val_rmse: 0.0620 - val_smape: 0.1506

Epoch 15/256

4586/4586 - 10s - 2ms/step - ia: 0.9297 - loss: 0.0194 - mae: 0.1034 - rmse: 0.1313 - smape: 0.2468 - val_ia: 0.5335 - val_loss: 0.0105 - val_mae: 0.0814 - val_rmse: 0.0895 - val_smape: 0.1941

Epoch 16/256

4586/4586 - 13s - 3ms/step - ia: 0.9301 - loss: 0.0192 - mae: 0.1029 - rmse: 0.1304 - smape: 0.2482 - val_ia: 0.5974 - val_loss: 0.0059 - val_mae: 0.0604 - val_rmse: 0.0696 - val_smape: 0.1691

Epoch 17/256

4586/4586 - 9s - 2ms/step - ia: 0.9301 - loss: 0.0191 - mae: 0.1026 - rmse: 0.1301 - smape: 0.2457 - val_ia: 0.5786 - val_loss: 0.0082 - val_mae: 0.0686 - val_rmse: 0.0774 - val_smape: 0.1564

Epoch 18/256

4586/4586 - 12s - 3ms/step - ia: 0.9306 - loss: 0.0190 - mae: 0.1025 - rmse: 0.1297 - smape: 0.2468 - val_ia: 0.6497 - val_loss: 0.0045 - val_mae: 0.0489 - val_rmse: 0.0583 - val_smape: 0.1377

Epoch 19/256

4586/4586 - 21s - 5ms/step - ia: 0.9305 - loss: 0.0190 - mae: 0.1022 - rmse: 0.1299 - smape: 0.2437 - val_ia: 0.6760 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0527 - val_smape: 0.1362

Epoch 20/256

4586/4586 - 21s - 4ms/step - ia: 0.9315 - loss: 0.0186 - mae: 0.1005 - rmse: 0.1282 - smape: 0.2415 - val_ia: 0.6189 - val_loss: 0.0061 - val_mae: 0.0584 - val_rmse: 0.0680 - val_smape: 0.1601

Epoch 21/256

4586/4586 - 18s - 4ms/step - ia: 0.9313 - loss: 0.0187 - mae: 0.1011 - rmse: 0.1288 - smape: 0.2418 - val_ia: 0.6215 - val_loss: 0.0051 - val_mae: 0.0548 - val_rmse: 0.0639 - val_smape: 0.1510

Epoch 22/256

4586/4586 - 13s - 3ms/step - ia: 0.9312 - loss: 0.0188 - mae: 0.1015 - rmse: 0.1290 - smape: 0.2434 - val_ia: 0.5998 - val_loss: 0.0063 - val_mae: 0.0615 - val_rmse: 0.0703 - val_smape: 0.1648

Epoch 23/256

4586/4586 - 17s - 4ms/step - ia: 0.9317 - loss: 0.0183 - mae: 0.1003 - rmse: 0.1275 - smape: 0.2401 - val_ia: 0.6318 - val_loss: 0.0051 - val_mae: 0.0539 - val_rmse: 0.0628 - val_smape: 0.1481

Epoch 24/256

4586/4586 - 11s - 2ms/step - ia: 0.9319 - loss: 0.0182 - mae: 0.0998 - rmse: 0.1269 - smape: 0.2405 - val_ia: 0.5301 - val_loss: 0.0137 - val_mae: 0.0904 - val_rmse: 0.0982 - val_smape: 0.1811

Epoch 25/256

4586/4586 - 23s - 5ms/step - ia: 0.9323 - loss: 0.0184 - mae: 0.0996 - rmse: 0.1271 - smape: 0.2376 - val_ia: 0.6227 - val_loss: 0.0059 - val_mae: 0.0566 - val_rmse: 0.0653 - val_smape: 0.1601

Epoch 26/256

4586/4586 - 12s - 3ms/step - ia: 0.9322 - loss: 0.0184 - mae: 0.1002 - rmse: 0.1276 - smape: 0.2378 - val_ia: 0.6076 - val_loss: 0.0058 - val_mae: 0.0573 - val_rmse: 0.0660 - val_smape: 0.1642

Epoch 27/256

4586/4586 - 23s - 5ms/step - ia: 0.9327 - loss: 0.0180 - mae: 0.0992 - rmse: 0.1262 - smape: 0.2369 - val_ia: 0.5854 - val_loss: 0.0067 - val_mae: 0.0649 - val_rmse: 0.0738 - val_smape: 0.1725

Epoch 28/256

4586/4586 - 17s - 4ms/step - ia: 0.9328 - loss: 0.0179 - mae: 0.0991 - rmse: 0.1260 - smape: 0.2371 - val_ia: 0.6544 - val_loss: 0.0044 - val_mae: 0.0480 - val_rmse: 0.0570 - val_smape: 0.1499

Epoch 29/256

4586/4586 - 12s - 3ms/step - ia: 0.9331 - loss: 0.0180 - mae: 0.0987 - rmse: 0.1261 - smape: 0.2368 - val_ia: 0.6368 - val_loss: 0.0047 - val_mae: 0.0519 - val_rmse: 0.0612 - val_smape: 0.1591

Epoch 30/256

4586/4586 - 22s - 5ms/step - ia: 0.9321 - loss: 0.0182 - mae: 0.1002 - rmse: 0.1272 - smape: 0.2381 - val_ia: 0.6386 - val_loss: 0.0049 - val_mae: 0.0516 - val_rmse: 0.0603 - val_smape: 0.1497

Epoch 31/256

4586/4586 - 22s - 5ms/step - ia: 0.9325 - loss: 0.0179 - mae: 0.0992 - rmse: 0.1260 - smape: 0.2384 - val_ia: 0.5326 - val_loss: 0.0116 - val_mae: 0.0857 - val_rmse: 0.0939 - val_smape: 0.1725

Epoch 32/256

4586/4586 - 19s - 4ms/step - ia: 0.9327 - loss: 0.0178 - mae: 0.0990 - rmse: 0.1258 - smape: 0.2380 - val_ia: 0.5918 - val_loss: 0.0064 - val_mae: 0.0629 - val_rmse: 0.0717 - val_smape: 0.1568

Epoch 33/256

4586/4586 - 10s - 2ms/step - ia: 0.9329 - loss: 0.0178 - mae: 0.0986 - rmse: 0.1255 - smape: 0.2364 - val_ia: 0.6428 - val_loss: 0.0045 - val_mae: 0.0497 - val_rmse: 0.0587 - val_smape: 0.1589

Epoch 34/256

4586/4586 - 14s - 3ms/step - ia: 0.9331 - loss: 0.0180 - mae: 0.0988 - rmse: 0.1260 - smape: 0.2359 - val_ia: 0.5556 - val_loss: 0.0085 - val_mae: 0.0736 - val_rmse: 0.0819 - val_smape: 0.1804

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 100ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/16

 34%|███▍      | 17/50 [59:26<2:37:04, 285.61s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 3s - 11ms/step - ia: 0.3823 - loss: 1.9352 - mae: 1.0972 - rmse: 1.3877 - smape: 1.3301 - val_ia: 0.5202 - val_loss: 0.6911 - val_mae: 0.6850 - val_rmse: 0.8014 - val_smape: 1.2086

Epoch 2/16

287/287 - 1s - 3ms/step - ia: 0.4135 - loss: 1.7701 - mae: 1.0486 - rmse: 1.3278 - smape: 1.2891 - val_ia: 0.5535 - val_loss: 0.6183 - val_mae: 0.6479 - val_rmse: 0.7594 - val_smape: 1.1492

Epoch 3/16

287/287 - 1s - 2ms/step - ia: 0.4316 - loss: 1.6566 - mae: 1.0176 - rmse: 1.2840 - smape: 1.2601 - val_ia: 0.5794 - val_loss: 0.5643 - val_mae: 0.6202 - val_rmse: 0.7274 - val_smape: 1.1023

Epoch 4/16

287/287 - 1s - 2ms/step - ia: 0.4521 - loss: 1.5722 - mae: 0.9887 - rmse: 1.2510 - smape: 1.2318 - val_ia: 0.5990 - val_loss: 0.5248 - val_mae: 0.6001 - val_rmse: 0.7036 - val_smape: 1.0644

Epoch 5/16

287/287 - 1s - 2ms/step - ia: 0.4668 - loss: 1.5168 - mae: 0.9723 - rmse: 1.2285 - smape: 1.2124 - val_ia: 0.6144 - val_loss: 0.4960 - val_mae: 0.5848 - val_rmse: 0.6859 - val_smape: 1.0323

Epoch 6/16

287/287 - 1s - 2ms/step - ia: 0.4818 - loss: 1.4403 - mae: 0.9490 - rmse: 1.1972 - smape: 1.1867 - val_ia: 0.6271 - val_loss: 0.4744 - val_mae: 0.5724 - val_rmse: 0.6725 - val_smape: 1.0051

Epoch 7/16

287/287 - 1s - 3ms/step - ia: 0.4911 - loss: 1.4010 - mae: 0.9346 - rmse: 1.1811 - smape: 1.1756 - val_ia: 0.6377 - val_loss: 0.4568 - val_mae: 0.5614 - val_rmse: 0.6613 - val_smape: 0.9817

Epoch 8/16

287/287 - 2s - 6ms/step - ia: 0.5012 - loss: 1.3670 - mae: 0.9220 - rmse: 1.1670 - smape: 1.1586 - val_ia: 0.6466 - val_loss: 0.4421 - val_mae: 0.5514 - val_rmse: 0.6516 - val_smape: 0.9616

Epoch 9/16

287/287 - 1s - 4ms/step - ia: 0.5104 - loss: 1.3122 - mae: 0.9076 - rmse: 1.1429 - smape: 1.1462 - val_ia: 0.6543 - val_loss: 0.4299 - val_mae: 0.5425 - val_rmse: 0.6433 - val_smape: 0.9439

Epoch 10/16

287/287 - 1s - 5ms/step - ia: 0.5184 - loss: 1.2776 - mae: 0.8944 - rmse: 1.1279 - smape: 1.1365 - val_ia: 0.6613 - val_loss: 0.4182 - val_mae: 0.5335 - val_rmse: 0.6348 - val_smape: 0.9286

Epoch 11/16

287/287 - 1s - 5ms/step - ia: 0.5283 - loss: 1.2317 - mae: 0.8779 - rmse: 1.1072 - smape: 1.1182 - val_ia: 0.6679 - val_loss: 0.4065 - val_mae: 0.5244 - val_rmse: 0.6260 - val_smape: 0.9144

Epoch 12/16

287/287 - 1s - 5ms/step - ia: 0.5300 - loss: 1.2241 - mae: 0.8753 - rmse: 1.1036 - smape: 1.1141 - val_ia: 0.6741 - val_loss: 0.3961 - val_mae: 0.5160 - val_rmse: 0.6181 - val_smape: 0.9013

Epoch 13/16

287/287 - 1s - 4ms/step - ia: 0.5349 - loss: 1.1922 - mae: 0.8655 - rmse: 1.0896 - smape: 1.1096 - val_ia: 0.6796 - val_loss: 0.3840 - val_mae: 0.5070 - val_rmse: 0.6084 - val_smape: 0.8902

Epoch 14/16

287/287 - 1s - 5ms/step - ia: 0.5386 - loss: 1.1817 - mae: 0.8622 - rmse: 1.0848 - smape: 1.0985 - val_ia: 0.6846 - val_loss: 0.3734 - val_mae: 0.4989 - val_rmse: 0.5997 - val_smape: 0.8804

Epoch 15/16

287/287 - 1s - 4ms/step - ia: 0.5420 - loss: 1.1633 - mae: 0.8536 - rmse: 1.0760 - smape: 1.0952 - val_ia: 0.6894 - val_loss: 0.3643 - val_mae: 0.4917 - val_rmse: 0.5922 - val_smape: 0.8713

Epoch 16/16

287/287 - 1s - 3ms/step - ia: 0.5455 - loss: 1.1400 - mae: 0.8461 - rmse: 1.0659 - smape: 1.0934 - val_ia: 0.6938 - val_loss: 0.3549 - val_mae: 0.4845 - val_rmse: 0.5842 - val_smape: 0.8629

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 17s 109ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/16

 36%|███▌      | 18/50 [59:46<1:49:47, 205.86s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

574/574 - 3s - 5ms/step - ia: 0.8700 - loss: 0.0851 - mae: 0.2140 - rmse: 0.2700 - smape: 0.4736 - val_ia: 0.8989 - val_loss: 0.0169 - val_mae: 0.1003 - val_rmse: 0.1252 - val_smape: 0.2710

Epoch 2/16

574/574 - 1s - 2ms/step - ia: 0.9246 - loss: 0.0259 - mae: 0.1237 - rmse: 0.1594 - smape: 0.3118 - val_ia: 0.9191 - val_loss: 0.0118 - val_mae: 0.0798 - val_rmse: 0.1050 - val_smape: 0.2028

Epoch 3/16

574/574 - 1s - 2ms/step - ia: 0.9318 - loss: 0.0212 - mae: 0.1118 - rmse: 0.1442 - smape: 0.2884 - val_ia: 0.9137 - val_loss: 0.0129 - val_mae: 0.0834 - val_rmse: 0.1083 - val_smape: 0.1919

Epoch 4/16

574/574 - 1s - 2ms/step - ia: 0.9356 - loss: 0.0191 - mae: 0.1056 - rmse: 0.1366 - smape: 0.2741 - val_ia: 0.9077 - val_loss: 0.0130 - val_mae: 0.0867 - val_rmse: 0.1067 - val_smape: 0.2037

Epoch 5/16

574/574 - 2s - 3ms/step - ia: 0.9393 - loss: 0.0173 - mae: 0.0995 - rmse: 0.1301 - smape: 0.2611 - val_ia: 0.9143 - val_loss: 0.0112 - val_mae: 0.0821 - val_rmse: 0.0988 - val_smape: 0.2205

Epoch 6/16

574/574 - 2s - 4ms/step - ia: 0.9417 - loss: 0.0160 - mae: 0.0956 - rmse: 0.1249 - smape: 0.2546 - val_ia: 0.9342 - val_loss: 0.0073 - val_mae: 0.0640 - val_rmse: 0.0823 - val_smape: 0.1617

Epoch 7/16

574/574 - 3s - 4ms/step - ia: 0.9435 - loss: 0.0150 - mae: 0.0924 - rmse: 0.1209 - smape: 0.2465 - val_ia: 0.9154 - val_loss: 0.0104 - val_mae: 0.0814 - val_rmse: 0.0953 - val_smape: 0.2376

Epoch 8/16

574/574 - 3s - 5ms/step - ia: 0.9458 - loss: 0.0140 - mae: 0.0886 - rmse: 0.1166 - smape: 0.2355 - val_ia: 0.9253 - val_loss: 0.0089 - val_mae: 0.0707 - val_rmse: 0.0898 - val_smape: 0.1592

Epoch 9/16

574/574 - 2s - 4ms/step - ia: 0.9482 - loss: 0.0130 - mae: 0.0847 - rmse: 0.1122 - smape: 0.2276 - val_ia: 0.9470 - val_loss: 0.0050 - val_mae: 0.0516 - val_rmse: 0.0685 - val_smape: 0.1437

Epoch 10/16

574/574 - 2s - 4ms/step - ia: 0.9497 - loss: 0.0122 - mae: 0.0823 - rmse: 0.1089 - smape: 0.2220 - val_ia: 0.9423 - val_loss: 0.0059 - val_mae: 0.0579 - val_rmse: 0.0741 - val_smape: 0.1699

Epoch 11/16

574/574 - 3s - 5ms/step - ia: 0.9509 - loss: 0.0117 - mae: 0.0804 - rmse: 0.1067 - smape: 0.2171 - val_ia: 0.9457 - val_loss: 0.0048 - val_mae: 0.0521 - val_rmse: 0.0666 - val_smape: 0.1614

Epoch 12/16

574/574 - 5s - 9ms/step - ia: 0.9523 - loss: 0.0111 - mae: 0.0780 - rmse: 0.1038 - smape: 0.2110 - val_ia: 0.9569 - val_loss: 0.0037 - val_mae: 0.0421 - val_rmse: 0.0582 - val_smape: 0.1303

Epoch 13/16

574/574 - 2s - 4ms/step - ia: 0.9534 - loss: 0.0107 - mae: 0.0762 - rmse: 0.1017 - smape: 0.2039 - val_ia: 0.9546 - val_loss: 0.0039 - val_mae: 0.0443 - val_rmse: 0.0602 - val_smape: 0.1357

Epoch 14/16

574/574 - 2s - 4ms/step - ia: 0.9534 - loss: 0.0107 - mae: 0.0761 - rmse: 0.1016 - smape: 0.2050 - val_ia: 0.9436 - val_loss: 0.0061 - val_mae: 0.0588 - val_rmse: 0.0751 - val_smape: 0.1691

Epoch 15/16

574/574 - 3s - 5ms/step - ia: 0.9547 - loss: 0.0102 - mae: 0.0741 - rmse: 0.0993 - smape: 0.1978 - val_ia: 0.9529 - val_loss: 0.0042 - val_mae: 0.0460 - val_rmse: 0.0621 - val_smape: 0.1360

Epoch 16/16

574/574 - 2s - 4ms/step - ia: 0.9559 - loss: 0.0097 - mae: 0.0721 - rmse: 0.0966 - smape: 0.1947 - val_ia: 0.9530 - val_loss: 0.0041 - val_mae: 0.0459 - val_rmse: 0.0609 - val_smape: 0.1556

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 14s 88ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 38%|███▊      | 19/50 [1:00:26<1:20:35, 155.99s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4586/4586 - 23s - 5ms/step - ia: 0.6403 - loss: 0.4051 - mae: 0.4769 - rmse: 0.5815 - smape: 0.8253 - val_ia: 0.3758 - val_loss: 0.0697 - val_mae: 0.1947 - val_rmse: 0.2081 - val_smape: 0.3537

Epoch 2/32

4586/4586 - 16s - 4ms/step - ia: 0.7838 - loss: 0.1664 - mae: 0.3123 - rmse: 0.3895 - smape: 0.5826 - val_ia: 0.4557 - val_loss: 0.0445 - val_mae: 0.1460 - val_rmse: 0.1572 - val_smape: 0.3032

Epoch 3/32

4586/4586 - 15s - 3ms/step - ia: 0.8134 - loss: 0.1264 - mae: 0.2680 - rmse: 0.3381 - smape: 0.5353 - val_ia: 0.4308 - val_loss: 0.0384 - val_mae: 0.1502 - val_rmse: 0.1611 - val_smape: 0.3618

Epoch 4/32

4586/4586 - 14s - 3ms/step - ia: 0.8284 - loss: 0.1095 - mae: 0.2475 - rmse: 0.3134 - smape: 0.5143 - val_ia: 0.4593 - val_loss: 0.0273 - val_mae: 0.1262 - val_rmse: 0.1381 - val_smape: 0.3158

Epoch 5/32

4586/4586 - 9s - 2ms/step - ia: 0.8356 - loss: 0.1010 - mae: 0.2378 - rmse: 0.3011 - smape: 0.4995 - val_ia: 0.4840 - val_loss: 0.0252 - val_mae: 0.1174 - val_rmse: 0.1291 - val_smape: 0.2839

Epoch 6/32

4586/4586 - 15s - 3ms/step - ia: 0.8399 - loss: 0.0963 - mae: 0.2310 - rmse: 0.2939 - smape: 0.4844 - val_ia: 0.4689 - val_loss: 0.0281 - val_mae: 0.1262 - val_rmse: 0.1379 - val_smape: 0.3060

Epoch 7/32

4586/4586 - 10s - 2ms/step - ia: 0.8449 - loss: 0.0910 - mae: 0.2245 - rmse: 0.2847 - smape: 0.4733 - val_ia: 0.4696 - val_loss: 0.0247 - val_mae: 0.1200 - val_rmse: 0.1315 - val_smape: 0.2965

Epoch 8/32

4586/4586 - 23s - 5ms/step - ia: 0.8480 - loss: 0.0894 - mae: 0.2213 - rmse: 0.2824 - smape: 0.4611 - val_ia: 0.4898 - val_loss: 0.0220 - val_mae: 0.1122 - val_rmse: 0.1233 - val_smape: 0.2673

Epoch 9/32

4586/4586 - 10s - 2ms/step - ia: 0.8500 - loss: 0.0860 - mae: 0.2179 - rmse: 0.2767 - smape: 0.4538 - val_ia: 0.5059 - val_loss: 0.0202 - val_mae: 0.1049 - val_rmse: 0.1162 - val_smape: 0.2378

Epoch 10/32

4586/4586 - 22s - 5ms/step - ia: 0.8500 - loss: 0.0858 - mae: 0.2167 - rmse: 0.2762 - smape: 0.4462 - val_ia: 0.4897 - val_loss: 0.0196 - val_mae: 0.1078 - val_rmse: 0.1186 - val_smape: 0.2554

Epoch 11/32

4586/4586 - 23s - 5ms/step - ia: 0.8535 - loss: 0.0830 - mae: 0.2125 - rmse: 0.2711 - smape: 0.4377 - val_ia: 0.5177 - val_loss: 0.0173 - val_mae: 0.0977 - val_rmse: 0.1088 - val_smape: 0.2207

Epoch 12/32

4586/4586 - 21s - 5ms/step - ia: 0.8554 - loss: 0.0817 - mae: 0.2106 - rmse: 0.2691 - smape: 0.4320 - val_ia: 0.5127 - val_loss: 0.0173 - val_mae: 0.0984 - val_rmse: 0.1090 - val_smape: 0.2178

Epoch 13/32

4586/4586 - 15s - 3ms/step - ia: 0.8566 - loss: 0.0799 - mae: 0.2078 - rmse: 0.2659 - smape: 0.4253 - val_ia: 0.5293 - val_loss: 0.0156 - val_mae: 0.0920 - val_rmse: 0.1031 - val_smape: 0.2069

Epoch 14/32

4586/4586 - 11s - 2ms/step - ia: 0.8585 - loss: 0.0786 - mae: 0.2057 - rmse: 0.2634 - smape: 0.4222 - val_ia: 0.5561 - val_loss: 0.0123 - val_mae: 0.0804 - val_rmse: 0.0909 - val_smape: 0.1871

Epoch 15/32

4586/4586 - 12s - 3ms/step - ia: 0.8605 - loss: 0.0754 - mae: 0.2018 - rmse: 0.2581 - smape: 0.4117 - val_ia: 0.5548 - val_loss: 0.0128 - val_mae: 0.0821 - val_rmse: 0.0929 - val_smape: 0.1834

Epoch 16/32

4586/4586 - 15s - 3ms/step - ia: 0.8626 - loss: 0.0746 - mae: 0.2000 - rmse: 0.2559 - smape: 0.4078 - val_ia: 0.5757 - val_loss: 0.0120 - val_mae: 0.0766 - val_rmse: 0.0872 - val_smape: 0.1539

Epoch 17/32

4586/4586 - 18s - 4ms/step - ia: 0.8630 - loss: 0.0728 - mae: 0.1983 - rmse: 0.2540 - smape: 0.4043 - val_ia: 0.5459 - val_loss: 0.0122 - val_mae: 0.0826 - val_rmse: 0.0932 - val_smape: 0.2036

Epoch 18/32

4586/4586 - 13s - 3ms/step - ia: 0.8631 - loss: 0.0739 - mae: 0.1984 - rmse: 0.2548 - smape: 0.4022 - val_ia: 0.5722 - val_loss: 0.0115 - val_mae: 0.0759 - val_rmse: 0.0865 - val_smape: 0.1738

Epoch 19/32

4586/4586 - 20s - 4ms/step - ia: 0.8643 - loss: 0.0716 - mae: 0.1961 - rmse: 0.2511 - smape: 0.3997 - val_ia: 0.5762 - val_loss: 0.0111 - val_mae: 0.0743 - val_rmse: 0.0847 - val_smape: 0.1601

Epoch 20/32

4586/4586 - 20s - 4ms/step - ia: 0.8662 - loss: 0.0718 - mae: 0.1950 - rmse: 0.2502 - smape: 0.3983 - val_ia: 0.5614 - val_loss: 0.0118 - val_mae: 0.0785 - val_rmse: 0.0890 - val_smape: 0.1896

Epoch 21/32

4586/4586 - 19s - 4ms/step - ia: 0.8665 - loss: 0.0694 - mae: 0.1938 - rmse: 0.2476 - smape: 0.3946 - val_ia: 0.5570 - val_loss: 0.0111 - val_mae: 0.0781 - val_rmse: 0.0888 - val_smape: 0.1867

Epoch 22/32

4586/4586 - 19s - 4ms/step - ia: 0.8658 - loss: 0.0705 - mae: 0.1937 - rmse: 0.2484 - smape: 0.3954 - val_ia: 0.5870 - val_loss: 0.0092 - val_mae: 0.0681 - val_rmse: 0.0789 - val_smape: 0.1558

Epoch 23/32

4586/4586 - 12s - 3ms/step - ia: 0.8671 - loss: 0.0696 - mae: 0.1928 - rmse: 0.2472 - smape: 0.3916 - val_ia: 0.5716 - val_loss: 0.0101 - val_mae: 0.0728 - val_rmse: 0.0831 - val_smape: 0.1878

Epoch 24/32

4586/4586 - 14s - 3ms/step - ia: 0.8667 - loss: 0.0701 - mae: 0.1929 - rmse: 0.2478 - smape: 0.3941 - val_ia: 0.5942 - val_loss: 0.0098 - val_mae: 0.0694 - val_rmse: 0.0801 - val_smape: 0.1671

Epoch 25/32

4586/4586 - 18s - 4ms/step - ia: 0.8700 - loss: 0.0668 - mae: 0.1895 - rmse: 0.2425 - smape: 0.3858 - val_ia: 0.5817 - val_loss: 0.0102 - val_mae: 0.0709 - val_rmse: 0.0816 - val_smape: 0.1719

Epoch 26/32

4586/4586 - 20s - 4ms/step - ia: 0.8709 - loss: 0.0666 - mae: 0.1886 - rmse: 0.2418 - smape: 0.3846 - val_ia: 0.5568 - val_loss: 0.0107 - val_mae: 0.0766 - val_rmse: 0.0871 - val_smape: 0.1766

Epoch 27/32

4586/4586 - 18s - 4ms/step - ia: 0.8696 - loss: 0.0665 - mae: 0.1892 - rmse: 0.2422 - smape: 0.3890 - val_ia: 0.5883 - val_loss: 0.0096 - val_mae: 0.0692 - val_rmse: 0.0799 - val_smape: 0.1657

Epoch 28/32

4586/4586 - 21s - 5ms/step - ia: 0.8693 - loss: 0.0676 - mae: 0.1895 - rmse: 0.2435 - smape: 0.3884 - val_ia: 0.5980 - val_loss: 0.0095 - val_mae: 0.0669 - val_rmse: 0.0775 - val_smape: 0.1695

Epoch 29/32

4586/4586 - 18s - 4ms/step - ia: 0.8693 - loss: 0.0668 - mae: 0.1891 - rmse: 0.2421 - smape: 0.3876 - val_ia: 0.5767 - val_loss: 0.0102 - val_mae: 0.0720 - val_rmse: 0.0827 - val_smape: 0.1660

Epoch 30/32

4586/4586 - 14s - 3ms/step - ia: 0.8713 - loss: 0.0657 - mae: 0.1872 - rmse: 0.2399 - smape: 0.3850 - val_ia: 0.6055 - val_loss: 0.0085 - val_mae: 0.0638 - val_rmse: 0.0742 - val_smape: 0.1592

Epoch 31/32

4586/4586 - 19s - 4ms/step - ia: 0.8711 - loss: 0.0661 - mae: 0.1869 - rmse: 0.2399 - smape: 0.3845 - val_ia: 0.6065 - val_loss: 0.0082 - val_mae: 0.0630 - val_rmse: 0.0735 - val_smape: 0.1582

Epoch 32/32

4586/4586 - 14s - 3ms/step - ia: 0.8722 - loss: 0.0649 - mae: 0.1861 - rmse: 0.2385 - smape: 0.3847 - val_ia: 0.6118 - val_loss: 0.0079 - val_mae: 0.0619 - val_rmse: 0.0727 - val_smape: 0.1493

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 33s 204ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 40%|████      | 20/50 [1:09:21<2:14:52, 269.75s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

574/574 - 8s - 14ms/step - ia: 0.6352 - loss: 0.3618 - mae: 0.4701 - rmse: 0.5770 - smape: 0.9197 - val_ia: 0.6617 - val_loss: 0.1911 - val_mae: 0.3363 - val_rmse: 0.4203 - val_smape: 0.7022

Epoch 2/64

574/574 - 3s - 6ms/step - ia: 0.8198 - loss: 0.1346 - mae: 0.2811 - rmse: 0.3643 - smape: 0.6146 - val_ia: 0.6974 - val_loss: 0.1611 - val_mae: 0.3125 - val_rmse: 0.3830 - val_smape: 0.6638

Epoch 3/64

574/574 - 2s - 3ms/step - ia: 0.8594 - loss: 0.0893 - mae: 0.2226 - rmse: 0.2963 - smape: 0.5129 - val_ia: 0.7280 - val_loss: 0.1278 - val_mae: 0.2809 - val_rmse: 0.3367 - val_smape: 0.6237

Epoch 4/64

574/574 - 3s - 5ms/step - ia: 0.8876 - loss: 0.0604 - mae: 0.1800 - rmse: 0.2435 - smape: 0.4375 - val_ia: 0.7602 - val_loss: 0.0982 - val_mae: 0.2456 - val_rmse: 0.2921 - val_smape: 0.5773

Epoch 5/64

574/574 - 3s - 5ms/step - ia: 0.9079 - loss: 0.0426 - mae: 0.1486 - rmse: 0.2042 - smape: 0.3777 - val_ia: 0.7984 - val_loss: 0.0674 - val_mae: 0.2023 - val_rmse: 0.2432 - val_smape: 0.5155

Epoch 6/64

574/574 - 2s - 4ms/step - ia: 0.9213 - loss: 0.0320 - mae: 0.1273 - rmse: 0.1767 - smape: 0.3309 - val_ia: 0.8325 - val_loss: 0.0462 - val_mae: 0.1652 - val_rmse: 0.2033 - val_smape: 0.4494

Epoch 7/64

574/574 - 2s - 3ms/step - ia: 0.9301 - loss: 0.0258 - mae: 0.1134 - rmse: 0.1587 - smape: 0.2968 - val_ia: 0.8637 - val_loss: 0.0316 - val_mae: 0.1336 - val_rmse: 0.1706 - val_smape: 0.3772

Epoch 8/64

574/574 - 3s - 5ms/step - ia: 0.9359 - loss: 0.0221 - mae: 0.1043 - rmse: 0.1466 - smape: 0.2743 - val_ia: 0.8789 - val_loss: 0.0252 - val_mae: 0.1178 - val_rmse: 0.1528 - val_smape: 0.3328

Epoch 9/64

574/574 - 3s - 5ms/step - ia: 0.9401 - loss: 0.0195 - mae: 0.0975 - rmse: 0.1374 - smape: 0.2587 - val_ia: 0.8887 - val_loss: 0.0213 - val_mae: 0.1080 - val_rmse: 0.1409 - val_smape: 0.3066

Epoch 10/64

574/574 - 2s - 4ms/step - ia: 0.9437 - loss: 0.0174 - mae: 0.0919 - rmse: 0.1296 - smape: 0.2478 - val_ia: 0.8984 - val_loss: 0.0182 - val_mae: 0.0986 - val_rmse: 0.1305 - val_smape: 0.2783

Epoch 11/64

574/574 - 2s - 3ms/step - ia: 0.9469 - loss: 0.0155 - mae: 0.0865 - rmse: 0.1225 - smape: 0.2371 - val_ia: 0.9030 - val_loss: 0.0163 - val_mae: 0.0939 - val_rmse: 0.1235 - val_smape: 0.2659

Epoch 12/64

574/574 - 2s - 4ms/step - ia: 0.9498 - loss: 0.0139 - mae: 0.0817 - rmse: 0.1156 - smape: 0.2273 - val_ia: 0.9095 - val_loss: 0.0144 - val_mae: 0.0881 - val_rmse: 0.1162 - val_smape: 0.2533

Epoch 13/64

574/574 - 2s - 3ms/step - ia: 0.9525 - loss: 0.0126 - mae: 0.0773 - rmse: 0.1099 - smape: 0.2183 - val_ia: 0.9122 - val_loss: 0.0132 - val_mae: 0.0854 - val_rmse: 0.1115 - val_smape: 0.2453

Epoch 14/64

574/574 - 2s - 4ms/step - ia: 0.9549 - loss: 0.0115 - mae: 0.0737 - rmse: 0.1049 - smape: 0.2098 - val_ia: 0.9165 - val_loss: 0.0121 - val_mae: 0.0811 - val_rmse: 0.1064 - val_smape: 0.2305

Epoch 15/64

574/574 - 3s - 5ms/step - ia: 0.9568 - loss: 0.0105 - mae: 0.0703 - rmse: 0.1003 - smape: 0.2026 - val_ia: 0.9199 - val_loss: 0.0111 - val_mae: 0.0780 - val_rmse: 0.1022 - val_smape: 0.2226

Epoch 16/64

574/574 - 1s - 3ms/step - ia: 0.9587 - loss: 0.0098 - mae: 0.0675 - rmse: 0.0966 - smape: 0.1962 - val_ia: 0.9234 - val_loss: 0.0103 - val_mae: 0.0746 - val_rmse: 0.0982 - val_smape: 0.2140

Epoch 17/64

574/574 - 3s - 6ms/step - ia: 0.9602 - loss: 0.0091 - mae: 0.0650 - rmse: 0.0932 - smape: 0.1899 - val_ia: 0.9262 - val_loss: 0.0096 - val_mae: 0.0722 - val_rmse: 0.0949 - val_smape: 0.2099

Epoch 18/64

574/574 - 3s - 6ms/step - ia: 0.9615 - loss: 0.0086 - mae: 0.0628 - rmse: 0.0903 - smape: 0.1849 - val_ia: 0.9305 - val_loss: 0.0088 - val_mae: 0.0681 - val_rmse: 0.0908 - val_smape: 0.1973

Epoch 19/64

574/574 - 3s - 6ms/step - ia: 0.9628 - loss: 0.0081 - mae: 0.0608 - rmse: 0.0876 - smape: 0.1803 - val_ia: 0.9272 - val_loss: 0.0090 - val_mae: 0.0710 - val_rmse: 0.0918 - val_smape: 0.2084

Epoch 20/64

574/574 - 4s - 7ms/step - ia: 0.9639 - loss: 0.0077 - mae: 0.0590 - rmse: 0.0854 - smape: 0.1766 - val_ia: 0.9322 - val_loss: 0.0082 - val_mae: 0.0661 - val_rmse: 0.0875 - val_smape: 0.1867

Epoch 21/64

574/574 - 4s - 8ms/step - ia: 0.9648 - loss: 0.0074 - mae: 0.0575 - rmse: 0.0835 - smape: 0.1729 - val_ia: 0.9350 - val_loss: 0.0077 - val_mae: 0.0635 - val_rmse: 0.0846 - val_smape: 0.1824

Epoch 22/64

574/574 - 3s - 5ms/step - ia: 0.9657 - loss: 0.0071 - mae: 0.0561 - rmse: 0.0816 - smape: 0.1700 - val_ia: 0.9347 - val_loss: 0.0075 - val_mae: 0.0639 - val_rmse: 0.0840 - val_smape: 0.1877

Epoch 23/64

574/574 - 2s - 3ms/step - ia: 0.9665 - loss: 0.0068 - mae: 0.0548 - rmse: 0.0800 - smape: 0.1668 - val_ia: 0.9359 - val_loss: 0.0073 - val_mae: 0.0627 - val_rmse: 0.0828 - val_smape: 0.1833

Epoch 24/64

574/574 - 2s - 4ms/step - ia: 0.9672 - loss: 0.0066 - mae: 0.0537 - rmse: 0.0784 - smape: 0.1645 - val_ia: 0.9393 - val_loss: 0.0068 - val_mae: 0.0593 - val_rmse: 0.0796 - val_smape: 0.1703

Epoch 25/64

574/574 - 1s - 2ms/step - ia: 0.9678 - loss: 0.0064 - mae: 0.0526 - rmse: 0.0772 - smape: 0.1618 - val_ia: 0.9390 - val_loss: 0.0067 - val_mae: 0.0597 - val_rmse: 0.0793 - val_smape: 0.1740

Epoch 26/64

574/574 - 1s - 2ms/step - ia: 0.9683 - loss: 0.0062 - mae: 0.0518 - rmse: 0.0760 - smape: 0.1602 - val_ia: 0.9411 - val_loss: 0.0064 - val_mae: 0.0577 - val_rmse: 0.0772 - val_smape: 0.1686

Epoch 27/64

574/574 - 1s - 2ms/step - ia: 0.9688 - loss: 0.0060 - mae: 0.0510 - rmse: 0.0750 - smape: 0.1586 - val_ia: 0.9405 - val_loss: 0.0064 - val_mae: 0.0580 - val_rmse: 0.0770 - val_smape: 0.1708

Epoch 28/64

574/574 - 1s - 2ms/step - ia: 0.9693 - loss: 0.0059 - mae: 0.0502 - rmse: 0.0737 - smape: 0.1569 - val_ia: 0.9416 - val_loss: 0.0062 - val_mae: 0.0571 - val_rmse: 0.0762 - val_smape: 0.1644

Epoch 29/64

574/574 - 1s - 2ms/step - ia: 0.9696 - loss: 0.0057 - mae: 0.0496 - rmse: 0.0729 - smape: 0.1560 - val_ia: 0.9423 - val_loss: 0.0061 - val_mae: 0.0564 - val_rmse: 0.0752 - val_smape: 0.1637

Epoch 30/64

574/574 - 1s - 3ms/step - ia: 0.9700 - loss: 0.0056 - mae: 0.0490 - rmse: 0.0720 - smape: 0.1548 - val_ia: 0.9428 - val_loss: 0.0060 - val_mae: 0.0560 - val_rmse: 0.0746 - val_smape: 0.1641

Epoch 31/64

574/574 - 1s - 2ms/step - ia: 0.9704 - loss: 0.0055 - mae: 0.0485 - rmse: 0.0712 - smape: 0.1536 - val_ia: 0.9448 - val_loss: 0.0057 - val_mae: 0.0542 - val_rmse: 0.0731 - val_smape: 0.1590

Epoch 32/64

574/574 - 1s - 2ms/step - ia: 0.9706 - loss: 0.0054 - mae: 0.0479 - rmse: 0.0706 - smape: 0.1526 - val_ia: 0.9451 - val_loss: 0.0056 - val_mae: 0.0537 - val_rmse: 0.0723 - val_smape: 0.1561

Epoch 33/64

574/574 - 1s - 2ms/step - ia: 0.9710 - loss: 0.0053 - mae: 0.0474 - rmse: 0.0699 - smape: 0.1512 - val_ia: 0.9450 - val_loss: 0.0056 - val_mae: 0.0538 - val_rmse: 0.0720 - val_smape: 0.1591

Epoch 34/64

574/574 - 1s - 2ms/step - ia: 0.9713 - loss: 0.0052 - mae: 0.0470 - rmse: 0.0692 - smape: 0.1509 - val_ia: 0.9430 - val_loss: 0.0057 - val_mae: 0.0555 - val_rmse: 0.0730 - val_smape: 0.1638

Epoch 35/64

574/574 - 1s - 2ms/step - ia: 0.9715 - loss: 0.0051 - mae: 0.0467 - rmse: 0.0686 - smape: 0.1504 - val_ia: 0.9465 - val_loss: 0.0053 - val_mae: 0.0524 - val_rmse: 0.0704 - val_smape: 0.1524

Epoch 36/64

574/574 - 1s - 2ms/step - ia: 0.9717 - loss: 0.0050 - mae: 0.0462 - rmse: 0.0680 - smape: 0.1488 - val_ia: 0.9458 - val_loss: 0.0054 - val_mae: 0.0529 - val_rmse: 0.0707 - val_smape: 0.1537

Epoch 37/64

574/574 - 4s - 6ms/step - ia: 0.9720 - loss: 0.0050 - mae: 0.0459 - rmse: 0.0673 - smape: 0.1483 - val_ia: 0.9482 - val_loss: 0.0051 - val_mae: 0.0509 - val_rmse: 0.0693 - val_smape: 0.1467

Epoch 38/64

574/574 - 4s - 7ms/step - ia: 0.9722 - loss: 0.0049 - mae: 0.0455 - rmse: 0.0669 - smape: 0.1472 - val_ia: 0.9476 - val_loss: 0.0051 - val_mae: 0.0513 - val_rmse: 0.0689 - val_smape: 0.1510

Epoch 39/64

574/574 - 5s - 8ms/step - ia: 0.9724 - loss: 0.0048 - mae: 0.0451 - rmse: 0.0665 - smape: 0.1465 - val_ia: 0.9484 - val_loss: 0.0050 - val_mae: 0.0506 - val_rmse: 0.0682 - val_smape: 0.1505

Epoch 40/64

574/574 - 3s - 5ms/step - ia: 0.9726 - loss: 0.0048 - mae: 0.0449 - rmse: 0.0660 - smape: 0.1461 - val_ia: 0.9470 - val_loss: 0.0051 - val_mae: 0.0518 - val_rmse: 0.0688 - val_smape: 0.1547

Epoch 41/64

574/574 - 5s - 9ms/step - ia: 0.9728 - loss: 0.0047 - mae: 0.0445 - rmse: 0.0654 - smape: 0.1456 - val_ia: 0.9494 - val_loss: 0.0048 - val_mae: 0.0497 - val_rmse: 0.0672 - val_smape: 0.1494

Epoch 42/64

574/574 - 5s - 9ms/step - ia: 0.9730 - loss: 0.0046 - mae: 0.0442 - rmse: 0.0651 - smape: 0.1446 - val_ia: 0.9501 - val_loss: 0.0048 - val_mae: 0.0490 - val_rmse: 0.0668 - val_smape: 0.1440

Epoch 43/64

574/574 - 4s - 6ms/step - ia: 0.9731 - loss: 0.0046 - mae: 0.0439 - rmse: 0.0648 - smape: 0.1444 - val_ia: 0.9484 - val_loss: 0.0049 - val_mae: 0.0505 - val_rmse: 0.0676 - val_smape: 0.1460

Epoch 44/64

574/574 - 5s - 8ms/step - ia: 0.9733 - loss: 0.0045 - mae: 0.0437 - rmse: 0.0643 - smape: 0.1436 - val_ia: 0.9489 - val_loss: 0.0048 - val_mae: 0.0502 - val_rmse: 0.0669 - val_smape: 0.1525

Epoch 45/64

574/574 - 5s - 8ms/step - ia: 0.9735 - loss: 0.0045 - mae: 0.0434 - rmse: 0.0637 - smape: 0.1427 - val_ia: 0.9494 - val_loss: 0.0047 - val_mae: 0.0496 - val_rmse: 0.0664 - val_smape: 0.1487

Epoch 46/64

574/574 - 1s - 2ms/step - ia: 0.9736 - loss: 0.0044 - mae: 0.0432 - rmse: 0.0636 - smape: 0.1426 - val_ia: 0.9503 - val_loss: 0.0046 - val_mae: 0.0488 - val_rmse: 0.0659 - val_smape: 0.1437

Epoch 47/64

574/574 - 1s - 2ms/step - ia: 0.9738 - loss: 0.0044 - mae: 0.0429 - rmse: 0.0632 - smape: 0.1422 - val_ia: 0.9518 - val_loss: 0.0045 - val_mae: 0.0474 - val_rmse: 0.0647 - val_smape: 0.1403

Epoch 48/64

574/574 - 3s - 5ms/step - ia: 0.9739 - loss: 0.0043 - mae: 0.0427 - rmse: 0.0628 - smape: 0.1414 - val_ia: 0.9512 - val_loss: 0.0045 - val_mae: 0.0480 - val_rmse: 0.0652 - val_smape: 0.1399

Epoch 49/64

574/574 - 2s - 4ms/step - ia: 0.9741 - loss: 0.0043 - mae: 0.0425 - rmse: 0.0625 - smape: 0.1409 - val_ia: 0.9511 - val_loss: 0.0045 - val_mae: 0.0480 - val_rmse: 0.0647 - val_smape: 0.1421

Epoch 50/64

574/574 - 4s - 6ms/step - ia: 0.9741 - loss: 0.0043 - mae: 0.0423 - rmse: 0.0623 - smape: 0.1409 - val_ia: 0.9517 - val_loss: 0.0044 - val_mae: 0.0475 - val_rmse: 0.0644 - val_smape: 0.1407

Epoch 51/64

574/574 - 6s - 10ms/step - ia: 0.9743 - loss: 0.0042 - mae: 0.0421 - rmse: 0.0620 - smape: 0.1404 - val_ia: 0.9508 - val_loss: 0.0045 - val_mae: 0.0482 - val_rmse: 0.0648 - val_smape: 0.1408

Epoch 52/64

574/574 - 2s - 4ms/step - ia: 0.9744 - loss: 0.0042 - mae: 0.0418 - rmse: 0.0617 - smape: 0.1399 - val_ia: 0.9505 - val_loss: 0.0045 - val_mae: 0.0485 - val_rmse: 0.0647 - val_smape: 0.1457

Epoch 53/64

574/574 - 2s - 3ms/step - ia: 0.9745 - loss: 0.0042 - mae: 0.0417 - rmse: 0.0615 - smape: 0.1396 - val_ia: 0.9521 - val_loss: 0.0044 - val_mae: 0.0471 - val_rmse: 0.0639 - val_smape: 0.1373

Epoch 54/64

574/574 - 1s - 2ms/step - ia: 0.9746 - loss: 0.0041 - mae: 0.0415 - rmse: 0.0611 - smape: 0.1389 - val_ia: 0.9530 - val_loss: 0.0042 - val_mae: 0.0462 - val_rmse: 0.0628 - val_smape: 0.1395

Epoch 55/64

574/574 - 2s - 3ms/step - ia: 0.9747 - loss: 0.0041 - mae: 0.0413 - rmse: 0.0609 - smape: 0.1388 - val_ia: 0.9519 - val_loss: 0.0043 - val_mae: 0.0471 - val_rmse: 0.0634 - val_smape: 0.1397

Epoch 56/64

574/574 - 3s - 5ms/step - ia: 0.9748 - loss: 0.0041 - mae: 0.0412 - rmse: 0.0606 - smape: 0.1387 - val_ia: 0.9521 - val_loss: 0.0043 - val_mae: 0.0471 - val_rmse: 0.0634 - val_smape: 0.1410

Epoch 57/64

574/574 - 3s - 5ms/step - ia: 0.9749 - loss: 0.0040 - mae: 0.0410 - rmse: 0.0605 - smape: 0.1378 - val_ia: 0.9528 - val_loss: 0.0042 - val_mae: 0.0464 - val_rmse: 0.0628 - val_smape: 0.1378

Epoch 58/64

574/574 - 5s - 9ms/step - ia: 0.9750 - loss: 0.0040 - mae: 0.0409 - rmse: 0.0602 - smape: 0.1378 - val_ia: 0.9527 - val_loss: 0.0042 - val_mae: 0.0465 - val_rmse: 0.0630 - val_smape: 0.1399

Epoch 59/64

574/574 - 6s - 10ms/step - ia: 0.9751 - loss: 0.0040 - mae: 0.0408 - rmse: 0.0602 - smape: 0.1376 - val_ia: 0.9534 - val_loss: 0.0041 - val_mae: 0.0459 - val_rmse: 0.0622 - val_smape: 0.1374

Epoch 60/64

574/574 - 2s - 4ms/step - ia: 0.9752 - loss: 0.0040 - mae: 0.0406 - rmse: 0.0599 - smape: 0.1376 - val_ia: 0.9527 - val_loss: 0.0042 - val_mae: 0.0464 - val_rmse: 0.0626 - val_smape: 0.1386

Epoch 61/64

574/574 - 3s - 5ms/step - ia: 0.9753 - loss: 0.0039 - mae: 0.0405 - rmse: 0.0596 - smape: 0.1372 - val_ia: 0.9517 - val_loss: 0.0042 - val_mae: 0.0473 - val_rmse: 0.0630 - val_smape: 0.1435

Epoch 62/64

574/574 - 5s - 9ms/step - ia: 0.9754 - loss: 0.0039 - mae: 0.0403 - rmse: 0.0593 - smape: 0.1366 - val_ia: 0.9514 - val_loss: 0.0043 - val_mae: 0.0475 - val_rmse: 0.0634 - val_smape: 0.1387

Epoch 63/64

574/574 - 2s - 4ms/step - ia: 0.9754 - loss: 0.0039 - mae: 0.0402 - rmse: 0.0593 - smape: 0.1365 - val_ia: 0.9521 - val_loss: 0.0042 - val_mae: 0.0470 - val_rmse: 0.0628 - val_smape: 0.1422

Epoch 64/64

574/574 - 2s - 3ms/step - ia: 0.9755 - loss: 0.0039 - mae: 0.0401 - rmse: 0.0590 - smape: 0.1364 - val_ia: 0.9533 - val_loss: 0.0041 - val_mae: 0.0461 - val_rmse: 0.0623 - val_smape: 0.1408

Restoring model weights from the end of the best epoch: 59.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 32s 200ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 42%|████▏     | 21/50 [1:12:32<1:58:59, 246.20s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 17s - 7ms/step - ia: 0.7894 - loss: 0.1899 - mae: 0.3342 - rmse: 0.4133 - smape: 0.6463 - val_ia: 0.6461 - val_loss: 0.0239 - val_mae: 0.1164 - val_rmse: 0.1355 - val_smape: 0.3259

Epoch 2/128

2293/2293 - 11s - 5ms/step - ia: 0.8812 - loss: 0.0563 - mae: 0.1854 - rmse: 0.2313 - smape: 0.4333 - val_ia: 0.6689 - val_loss: 0.0190 - val_mae: 0.1043 - val_rmse: 0.1216 - val_smape: 0.2785

Epoch 3/128

2293/2293 - 22s - 9ms/step - ia: 0.9040 - loss: 0.0375 - mae: 0.1502 - rmse: 0.1892 - smape: 0.3592 - val_ia: 0.7041 - val_loss: 0.0151 - val_mae: 0.0903 - val_rmse: 0.1056 - val_smape: 0.2215

Epoch 4/128

2293/2293 - 10s - 4ms/step - ia: 0.9124 - loss: 0.0319 - mae: 0.1376 - rmse: 0.1741 - smape: 0.3340 - val_ia: 0.7333 - val_loss: 0.0118 - val_mae: 0.0778 - val_rmse: 0.0927 - val_smape: 0.1868

Epoch 5/128

2293/2293 - 9s - 4ms/step - ia: 0.9163 - loss: 0.0291 - mae: 0.1315 - rmse: 0.1663 - smape: 0.3185 - val_ia: 0.7338 - val_loss: 0.0114 - val_mae: 0.0772 - val_rmse: 0.0912 - val_smape: 0.1851

Epoch 6/128

2293/2293 - 8s - 3ms/step - ia: 0.9202 - loss: 0.0265 - mae: 0.1252 - rmse: 0.1586 - smape: 0.3079 - val_ia: 0.7323 - val_loss: 0.0114 - val_mae: 0.0776 - val_rmse: 0.0916 - val_smape: 0.1807

Epoch 7/128

2293/2293 - 13s - 6ms/step - ia: 0.9236 - loss: 0.0247 - mae: 0.1202 - rmse: 0.1530 - smape: 0.2977 - val_ia: 0.7088 - val_loss: 0.0123 - val_mae: 0.0841 - val_rmse: 0.0973 - val_smape: 0.2048

Epoch 8/128

2293/2293 - 10s - 4ms/step - ia: 0.9249 - loss: 0.0241 - mae: 0.1183 - rmse: 0.1510 - smape: 0.2965 - val_ia: 0.7226 - val_loss: 0.0123 - val_mae: 0.0808 - val_rmse: 0.0941 - val_smape: 0.1799

Epoch 9/128

2293/2293 - 6s - 3ms/step - ia: 0.9273 - loss: 0.0225 - mae: 0.1146 - rmse: 0.1458 - smape: 0.2834 - val_ia: 0.7108 - val_loss: 0.0130 - val_mae: 0.0841 - val_rmse: 0.0971 - val_smape: 0.1820

Epoch 10/128

2293/2293 - 14s - 6ms/step - ia: 0.9285 - loss: 0.0217 - mae: 0.1121 - rmse: 0.1431 - smape: 0.2802 - val_ia: 0.7401 - val_loss: 0.0097 - val_mae: 0.0724 - val_rmse: 0.0851 - val_smape: 0.1689

Epoch 11/128

2293/2293 - 11s - 5ms/step - ia: 0.9307 - loss: 0.0206 - mae: 0.1090 - rmse: 0.1392 - smape: 0.2754 - val_ia: 0.7271 - val_loss: 0.0107 - val_mae: 0.0773 - val_rmse: 0.0898 - val_smape: 0.1847

Epoch 12/128

2293/2293 - 7s - 3ms/step - ia: 0.9324 - loss: 0.0198 - mae: 0.1062 - rmse: 0.1364 - smape: 0.2676 - val_ia: 0.7187 - val_loss: 0.0115 - val_mae: 0.0804 - val_rmse: 0.0925 - val_smape: 0.1838

Epoch 13/128

2293/2293 - 6s - 3ms/step - ia: 0.9333 - loss: 0.0191 - mae: 0.1047 - rmse: 0.1342 - smape: 0.2654 - val_ia: 0.7554 - val_loss: 0.0081 - val_mae: 0.0665 - val_rmse: 0.0788 - val_smape: 0.1624

Epoch 14/128

2293/2293 - 5s - 2ms/step - ia: 0.9352 - loss: 0.0182 - mae: 0.1020 - rmse: 0.1310 - smape: 0.2604 - val_ia: 0.7693 - val_loss: 0.0071 - val_mae: 0.0611 - val_rmse: 0.0731 - val_smape: 0.1505

Epoch 15/128

2293/2293 - 5s - 2ms/step - ia: 0.9364 - loss: 0.0178 - mae: 0.1000 - rmse: 0.1290 - smape: 0.2546 - val_ia: 0.7622 - val_loss: 0.0074 - val_mae: 0.0635 - val_rmse: 0.0754 - val_smape: 0.1592

Epoch 16/128

2293/2293 - 10s - 4ms/step - ia: 0.9370 - loss: 0.0171 - mae: 0.0988 - rmse: 0.1268 - smape: 0.2519 - val_ia: 0.7628 - val_loss: 0.0071 - val_mae: 0.0635 - val_rmse: 0.0754 - val_smape: 0.1635

Epoch 17/128

2293/2293 - 10s - 4ms/step - ia: 0.9387 - loss: 0.0165 - mae: 0.0963 - rmse: 0.1243 - smape: 0.2475 - val_ia: 0.7590 - val_loss: 0.0076 - val_mae: 0.0636 - val_rmse: 0.0755 - val_smape: 0.1466

Epoch 18/128

2293/2293 - 12s - 5ms/step - ia: 0.9388 - loss: 0.0163 - mae: 0.0959 - rmse: 0.1235 - smape: 0.2443 - val_ia: 0.7823 - val_loss: 0.0059 - val_mae: 0.0559 - val_rmse: 0.0675 - val_smape: 0.1445

Epoch 19/128

2293/2293 - 10s - 4ms/step - ia: 0.9411 - loss: 0.0154 - mae: 0.0925 - rmse: 0.1200 - smape: 0.2382 - val_ia: 0.8024 - val_loss: 0.0050 - val_mae: 0.0509 - val_rmse: 0.0627 - val_smape: 0.1376

Epoch 20/128

2293/2293 - 11s - 5ms/step - ia: 0.9414 - loss: 0.0152 - mae: 0.0920 - rmse: 0.1193 - smape: 0.2358 - val_ia: 0.7817 - val_loss: 0.0056 - val_mae: 0.0547 - val_rmse: 0.0662 - val_smape: 0.1462

Epoch 21/128

2293/2293 - 20s - 9ms/step - ia: 0.9419 - loss: 0.0150 - mae: 0.0912 - rmse: 0.1184 - smape: 0.2326 - val_ia: 0.7728 - val_loss: 0.0059 - val_mae: 0.0565 - val_rmse: 0.0680 - val_smape: 0.1450

Epoch 22/128

2293/2293 - 16s - 7ms/step - ia: 0.9428 - loss: 0.0145 - mae: 0.0896 - rmse: 0.1161 - smape: 0.2309 - val_ia: 0.7727 - val_loss: 0.0056 - val_mae: 0.0555 - val_rmse: 0.0669 - val_smape: 0.1489

Epoch 23/128

2293/2293 - 7s - 3ms/step - ia: 0.9437 - loss: 0.0142 - mae: 0.0882 - rmse: 0.1149 - smape: 0.2272 - val_ia: 0.8044 - val_loss: 0.0047 - val_mae: 0.0500 - val_rmse: 0.0614 - val_smape: 0.1514

Epoch 24/128

2293/2293 - 12s - 5ms/step - ia: 0.9444 - loss: 0.0139 - mae: 0.0873 - rmse: 0.1139 - smape: 0.2250 - val_ia: 0.8006 - val_loss: 0.0047 - val_mae: 0.0493 - val_rmse: 0.0606 - val_smape: 0.1460

Epoch 25/128

2293/2293 - 10s - 4ms/step - ia: 0.9449 - loss: 0.0137 - mae: 0.0864 - rmse: 0.1127 - smape: 0.2244 - val_ia: 0.8285 - val_loss: 0.0040 - val_mae: 0.0430 - val_rmse: 0.0548 - val_smape: 0.1243

Epoch 26/128

2293/2293 - 6s - 3ms/step - ia: 0.9454 - loss: 0.0135 - mae: 0.0856 - rmse: 0.1118 - smape: 0.2196 - val_ia: 0.7976 - val_loss: 0.0047 - val_mae: 0.0504 - val_rmse: 0.0617 - val_smape: 0.1541

Epoch 27/128

2293/2293 - 14s - 6ms/step - ia: 0.9455 - loss: 0.0134 - mae: 0.0855 - rmse: 0.1116 - smape: 0.2208 - val_ia: 0.8287 - val_loss: 0.0039 - val_mae: 0.0432 - val_rmse: 0.0549 - val_smape: 0.1338

Epoch 28/128

2293/2293 - 8s - 4ms/step - ia: 0.9458 - loss: 0.0132 - mae: 0.0850 - rmse: 0.1110 - smape: 0.2194 - val_ia: 0.7978 - val_loss: 0.0046 - val_mae: 0.0494 - val_rmse: 0.0609 - val_smape: 0.1478

Epoch 29/128

2293/2293 - 6s - 2ms/step - ia: 0.9462 - loss: 0.0131 - mae: 0.0844 - rmse: 0.1103 - smape: 0.2171 - val_ia: 0.8289 - val_loss: 0.0038 - val_mae: 0.0422 - val_rmse: 0.0539 - val_smape: 0.1303

Epoch 30/128

2293/2293 - 6s - 3ms/step - ia: 0.9464 - loss: 0.0131 - mae: 0.0839 - rmse: 0.1101 - smape: 0.2148 - val_ia: 0.7876 - val_loss: 0.0048 - val_mae: 0.0504 - val_rmse: 0.0622 - val_smape: 0.1383

Epoch 31/128

2293/2293 - 9s - 4ms/step - ia: 0.9471 - loss: 0.0129 - mae: 0.0832 - rmse: 0.1093 - smape: 0.2128 - val_ia: 0.8276 - val_loss: 0.0037 - val_mae: 0.0420 - val_rmse: 0.0536 - val_smape: 0.1318

Epoch 32/128

2293/2293 - 9s - 4ms/step - ia: 0.9468 - loss: 0.0129 - mae: 0.0835 - rmse: 0.1092 - smape: 0.2133 - val_ia: 0.7927 - val_loss: 0.0045 - val_mae: 0.0496 - val_rmse: 0.0610 - val_smape: 0.1543

Epoch 33/128

2293/2293 - 9s - 4ms/step - ia: 0.9473 - loss: 0.0127 - mae: 0.0827 - rmse: 0.1085 - smape: 0.2118 - val_ia: 0.7988 - val_loss: 0.0046 - val_mae: 0.0503 - val_rmse: 0.0616 - val_smape: 0.1603

Epoch 34/128

2293/2293 - 12s - 5ms/step - ia: 0.9473 - loss: 0.0127 - mae: 0.0826 - rmse: 0.1085 - smape: 0.2111 - val_ia: 0.8221 - val_loss: 0.0039 - val_mae: 0.0440 - val_rmse: 0.0556 - val_smape: 0.1390

Epoch 35/128

2293/2293 - 9s - 4ms/step - ia: 0.9479 - loss: 0.0124 - mae: 0.0818 - rmse: 0.1071 - smape: 0.2107 - val_ia: 0.8247 - val_loss: 0.0036 - val_mae: 0.0418 - val_rmse: 0.0534 - val_smape: 0.1317

Epoch 36/128

2293/2293 - 9s - 4ms/step - ia: 0.9478 - loss: 0.0124 - mae: 0.0817 - rmse: 0.1071 - smape: 0.2089 - val_ia: 0.8283 - val_loss: 0.0037 - val_mae: 0.0422 - val_rmse: 0.0538 - val_smape: 0.1378

Epoch 37/128

2293/2293 - 12s - 5ms/step - ia: 0.9480 - loss: 0.0123 - mae: 0.0815 - rmse: 0.1066 - smape: 0.2100 - val_ia: 0.8304 - val_loss: 0.0036 - val_mae: 0.0420 - val_rmse: 0.0535 - val_smape: 0.1354

Epoch 38/128

2293/2293 - 8s - 4ms/step - ia: 0.9480 - loss: 0.0125 - mae: 0.0817 - rmse: 0.1074 - smape: 0.2068 - val_ia: 0.8148 - val_loss: 0.0041 - val_mae: 0.0452 - val_rmse: 0.0568 - val_smape: 0.1431

Epoch 39/128

2293/2293 - 6s - 3ms/step - ia: 0.9482 - loss: 0.0124 - mae: 0.0811 - rmse: 0.1068 - smape: 0.2076 - val_ia: 0.8281 - val_loss: 0.0037 - val_mae: 0.0427 - val_rmse: 0.0542 - val_smape: 0.1391

Epoch 40/128

2293/2293 - 6s - 2ms/step - ia: 0.9482 - loss: 0.0123 - mae: 0.0812 - rmse: 0.1069 - smape: 0.2067 - val_ia: 0.8225 - val_loss: 0.0037 - val_mae: 0.0428 - val_rmse: 0.0544 - val_smape: 0.1378

Epoch 41/128

2293/2293 - 5s - 2ms/step - ia: 0.9486 - loss: 0.0123 - mae: 0.0807 - rmse: 0.1066 - smape: 0.2065 - val_ia: 0.8236 - val_loss: 0.0038 - val_mae: 0.0430 - val_rmse: 0.0546 - val_smape: 0.1391

Epoch 42/128

2293/2293 - 9s - 4ms/step - ia: 0.9484 - loss: 0.0122 - mae: 0.0808 - rmse: 0.1062 - smape: 0.2056 - val_ia: 0.8139 - val_loss: 0.0041 - val_mae: 0.0468 - val_rmse: 0.0583 - val_smape: 0.1537

Epoch 43/128

2293/2293 - 10s - 4ms/step - ia: 0.9487 - loss: 0.0121 - mae: 0.0805 - rmse: 0.1060 - smape: 0.2062 - val_ia: 0.8001 - val_loss: 0.0043 - val_mae: 0.0483 - val_rmse: 0.0596 - val_smape: 0.1544

Epoch 44/128

2293/2293 - 8s - 4ms/step - ia: 0.9489 - loss: 0.0121 - mae: 0.0802 - rmse: 0.1056 - smape: 0.2039 - val_ia: 0.8015 - val_loss: 0.0043 - val_mae: 0.0478 - val_rmse: 0.0591 - val_smape: 0.1535

Epoch 45/128

2293/2293 - 11s - 5ms/step - ia: 0.9488 - loss: 0.0121 - mae: 0.0804 - rmse: 0.1060 - smape: 0.2042 - val_ia: 0.8084 - val_loss: 0.0042 - val_mae: 0.0476 - val_rmse: 0.0589 - val_smape: 0.1574

Epoch 46/128

2293/2293 - 9s - 4ms/step - ia: 0.9488 - loss: 0.0122 - mae: 0.0802 - rmse: 0.1062 - smape: 0.2029 - val_ia: 0.8262 - val_loss: 0.0037 - val_mae: 0.0430 - val_rmse: 0.0543 - val_smape: 0.1466

Epoch 47/128

2293/2293 - 6s - 3ms/step - ia: 0.9494 - loss: 0.0119 - mae: 0.0794 - rmse: 0.1047 - smape: 0.2015 - val_ia: 0.8182 - val_loss: 0.0040 - val_mae: 0.0456 - val_rmse: 0.0569 - val_smape: 0.1588

Epoch 48/128

2293/2293 - 5s - 2ms/step - ia: 0.9494 - loss: 0.0120 - mae: 0.0796 - rmse: 0.1050 - smape: 0.2015 - val_ia: 0.7902 - val_loss: 0.0044 - val_mae: 0.0492 - val_rmse: 0.0603 - val_smape: 0.1479

Epoch 49/128

2293/2293 - 12s - 5ms/step - ia: 0.9491 - loss: 0.0120 - mae: 0.0799 - rmse: 0.1052 - smape: 0.2031 - val_ia: 0.8347 - val_loss: 0.0035 - val_mae: 0.0406 - val_rmse: 0.0520 - val_smape: 0.1326

Epoch 50/128

2293/2293 - 8s - 4ms/step - ia: 0.9493 - loss: 0.0120 - mae: 0.0795 - rmse: 0.1051 - smape: 0.2010 - val_ia: 0.8251 - val_loss: 0.0038 - val_mae: 0.0443 - val_rmse: 0.0556 - val_smape: 0.1513

Epoch 51/128

2293/2293 - 9s - 4ms/step - ia: 0.9494 - loss: 0.0119 - mae: 0.0794 - rmse: 0.1048 - smape: 0.1999 - val_ia: 0.8036 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0578 - val_smape: 0.1423

Epoch 52/128

2293/2293 - 7s - 3ms/step - ia: 0.9495 - loss: 0.0119 - mae: 0.0795 - rmse: 0.1048 - smape: 0.2018 - val_ia: 0.8194 - val_loss: 0.0037 - val_mae: 0.0435 - val_rmse: 0.0550 - val_smape: 0.1456

Epoch 53/128

2293/2293 - 10s - 4ms/step - ia: 0.9499 - loss: 0.0117 - mae: 0.0787 - rmse: 0.1038 - smape: 0.1992 - val_ia: 0.8302 - val_loss: 0.0036 - val_mae: 0.0422 - val_rmse: 0.0537 - val_smape: 0.1394

Epoch 54/128

2293/2293 - 10s - 4ms/step - ia: 0.9496 - loss: 0.0117 - mae: 0.0790 - rmse: 0.1041 - smape: 0.2001 - val_ia: 0.8313 - val_loss: 0.0035 - val_mae: 0.0420 - val_rmse: 0.0534 - val_smape: 0.1407

Epoch 55/128

2293/2293 - 8s - 4ms/step - ia: 0.9495 - loss: 0.0118 - mae: 0.0792 - rmse: 0.1046 - smape: 0.2000 - val_ia: 0.8181 - val_loss: 0.0037 - val_mae: 0.0437 - val_rmse: 0.0551 - val_smape: 0.1455

Epoch 56/128

2293/2293 - 10s - 5ms/step - ia: 0.9496 - loss: 0.0119 - mae: 0.0790 - rmse: 0.1045 - smape: 0.1988 - val_ia: 0.8185 - val_loss: 0.0040 - val_mae: 0.0456 - val_rmse: 0.0567 - val_smape: 0.1568

Epoch 57/128

2293/2293 - 11s - 5ms/step - ia: 0.9501 - loss: 0.0116 - mae: 0.0784 - rmse: 0.1034 - smape: 0.1968 - val_ia: 0.8330 - val_loss: 0.0036 - val_mae: 0.0414 - val_rmse: 0.0527 - val_smape: 0.1345

Epoch 58/128

2293/2293 - 9s - 4ms/step - ia: 0.9499 - loss: 0.0117 - mae: 0.0786 - rmse: 0.1039 - smape: 0.1975 - val_ia: 0.8308 - val_loss: 0.0036 - val_mae: 0.0416 - val_rmse: 0.0530 - val_smape: 0.1347

Epoch 59/128

2293/2293 - 7s - 3ms/step - ia: 0.9503 - loss: 0.0116 - mae: 0.0783 - rmse: 0.1034 - smape: 0.1972 - val_ia: 0.8340 - val_loss: 0.0034 - val_mae: 0.0402 - val_rmse: 0.0516 - val_smape: 0.1356

Epoch 60/128

2293/2293 - 9s - 4ms/step - ia: 0.9500 - loss: 0.0117 - mae: 0.0785 - rmse: 0.1035 - smape: 0.1978 - val_ia: 0.8226 - val_loss: 0.0037 - val_mae: 0.0429 - val_rmse: 0.0543 - val_smape: 0.1360

Epoch 61/128

2293/2293 - 6s - 3ms/step - ia: 0.9498 - loss: 0.0117 - mae: 0.0788 - rmse: 0.1042 - smape: 0.1970 - val_ia: 0.8289 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0535 - val_smape: 0.1430

Epoch 62/128

2293/2293 - 7s - 3ms/step - ia: 0.9500 - loss: 0.0117 - mae: 0.0785 - rmse: 0.1035 - smape: 0.1965 - val_ia: 0.8159 - val_loss: 0.0038 - val_mae: 0.0444 - val_rmse: 0.0557 - val_smape: 0.1475

Epoch 63/128

2293/2293 - 10s - 4ms/step - ia: 0.9507 - loss: 0.0114 - mae: 0.0775 - rmse: 0.1025 - smape: 0.1937 - val_ia: 0.8263 - val_loss: 0.0036 - val_mae: 0.0429 - val_rmse: 0.0541 - val_smape: 0.1394

Epoch 64/128

2293/2293 - 10s - 4ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0783 - rmse: 0.1036 - smape: 0.1940 - val_ia: 0.7897 - val_loss: 0.0045 - val_mae: 0.0511 - val_rmse: 0.0621 - val_smape: 0.1594

Epoch 65/128

2293/2293 - 6s - 3ms/step - ia: 0.9502 - loss: 0.0117 - mae: 0.0783 - rmse: 0.1039 - smape: 0.1956 - val_ia: 0.8073 - val_loss: 0.0039 - val_mae: 0.0456 - val_rmse: 0.0567 - val_smape: 0.1538

Epoch 66/128

2293/2293 - 15s - 7ms/step - ia: 0.9503 - loss: 0.0116 - mae: 0.0779 - rmse: 0.1033 - smape: 0.1937 - val_ia: 0.8275 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0528 - val_smape: 0.1342

Epoch 67/128

2293/2293 - 8s - 4ms/step - ia: 0.9500 - loss: 0.0117 - mae: 0.0784 - rmse: 0.1039 - smape: 0.1939 - val_ia: 0.8275 - val_loss: 0.0033 - val_mae: 0.0407 - val_rmse: 0.0520 - val_smape: 0.1292

Epoch 68/128

2293/2293 - 10s - 4ms/step - ia: 0.9504 - loss: 0.0116 - mae: 0.0779 - rmse: 0.1034 - smape: 0.1938 - val_ia: 0.8214 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0546 - val_smape: 0.1427

Epoch 69/128

2293/2293 - 9s - 4ms/step - ia: 0.9507 - loss: 0.0115 - mae: 0.0775 - rmse: 0.1026 - smape: 0.1929 - val_ia: 0.8351 - val_loss: 0.0033 - val_mae: 0.0397 - val_rmse: 0.0510 - val_smape: 0.1360

Epoch 70/128

2293/2293 - 8s - 4ms/step - ia: 0.9505 - loss: 0.0114 - mae: 0.0777 - rmse: 0.1026 - smape: 0.1948 - val_ia: 0.8382 - val_loss: 0.0033 - val_mae: 0.0399 - val_rmse: 0.0512 - val_smape: 0.1309

Epoch 71/128

2293/2293 - 12s - 5ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0780 - rmse: 0.1033 - smape: 0.1926 - val_ia: 0.8173 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0545 - val_smape: 0.1401

Epoch 72/128

2293/2293 - 8s - 3ms/step - ia: 0.9505 - loss: 0.0115 - mae: 0.0775 - rmse: 0.1025 - smape: 0.1935 - val_ia: 0.8278 - val_loss: 0.0035 - val_mae: 0.0414 - val_rmse: 0.0526 - val_smape: 0.1432

Epoch 73/128

2293/2293 - 11s - 5ms/step - ia: 0.9507 - loss: 0.0114 - mae: 0.0773 - rmse: 0.1025 - smape: 0.1917 - val_ia: 0.8204 - val_loss: 0.0038 - val_mae: 0.0447 - val_rmse: 0.0558 - val_smape: 0.1501

Epoch 74/128

2293/2293 - 19s - 8ms/step - ia: 0.9510 - loss: 0.0113 - mae: 0.0770 - rmse: 0.1018 - smape: 0.1908 - val_ia: 0.8254 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0535 - val_smape: 0.1408

Epoch 75/128

2293/2293 - 6s - 2ms/step - ia: 0.9505 - loss: 0.0115 - mae: 0.0777 - rmse: 0.1029 - smape: 0.1919 - val_ia: 0.8325 - val_loss: 0.0035 - val_mae: 0.0414 - val_rmse: 0.0524 - val_smape: 0.1377

Epoch 76/128

2293/2293 - 9s - 4ms/step - ia: 0.9505 - loss: 0.0114 - mae: 0.0776 - rmse: 0.1027 - smape: 0.1936 - val_ia: 0.8300 - val_loss: 0.0034 - val_mae: 0.0416 - val_rmse: 0.0526 - val_smape: 0.1352

Epoch 77/128

2293/2293 - 6s - 3ms/step - ia: 0.9510 - loss: 0.0113 - mae: 0.0770 - rmse: 0.1019 - smape: 0.1906 - val_ia: 0.8299 - val_loss: 0.0034 - val_mae: 0.0422 - val_rmse: 0.0534 - val_smape: 0.1391

Epoch 78/128

2293/2293 - 10s - 4ms/step - ia: 0.9509 - loss: 0.0113 - mae: 0.0772 - rmse: 0.1019 - smape: 0.1913 - val_ia: 0.8272 - val_loss: 0.0035 - val_mae: 0.0416 - val_rmse: 0.0529 - val_smape: 0.1355

Epoch 79/128

2293/2293 - 9s - 4ms/step - ia: 0.9511 - loss: 0.0112 - mae: 0.0769 - rmse: 0.1015 - smape: 0.1920 - val_ia: 0.8357 - val_loss: 0.0032 - val_mae: 0.0399 - val_rmse: 0.0511 - val_smape: 0.1358

Epoch 80/128

2293/2293 - 8s - 4ms/step - ia: 0.9505 - loss: 0.0116 - mae: 0.0777 - rmse: 0.1032 - smape: 0.1911 - val_ia: 0.8309 - val_loss: 0.0033 - val_mae: 0.0404 - val_rmse: 0.0516 - val_smape: 0.1366

Epoch 81/128

2293/2293 - 12s - 5ms/step - ia: 0.9515 - loss: 0.0113 - mae: 0.0764 - rmse: 0.1018 - smape: 0.1894 - val_ia: 0.8274 - val_loss: 0.0035 - val_mae: 0.0419 - val_rmse: 0.0532 - val_smape: 0.1347

Epoch 82/128

2293/2293 - 10s - 4ms/step - ia: 0.9511 - loss: 0.0113 - mae: 0.0768 - rmse: 0.1020 - smape: 0.1905 - val_ia: 0.8409 - val_loss: 0.0031 - val_mae: 0.0384 - val_rmse: 0.0495 - val_smape: 0.1296

Epoch 83/128

2293/2293 - 12s - 5ms/step - ia: 0.9510 - loss: 0.0113 - mae: 0.0770 - rmse: 0.1018 - smape: 0.1901 - val_ia: 0.8133 - val_loss: 0.0037 - val_mae: 0.0443 - val_rmse: 0.0554 - val_smape: 0.1397

Epoch 84/128

2293/2293 - 11s - 5ms/step - ia: 0.9513 - loss: 0.0112 - mae: 0.0765 - rmse: 0.1015 - smape: 0.1897 - val_ia: 0.8352 - val_loss: 0.0033 - val_mae: 0.0398 - val_rmse: 0.0509 - val_smape: 0.1340

Epoch 85/128

2293/2293 - 18s - 8ms/step - ia: 0.9511 - loss: 0.0114 - mae: 0.0768 - rmse: 0.1023 - smape: 0.1884 - val_ia: 0.8376 - val_loss: 0.0031 - val_mae: 0.0394 - val_rmse: 0.0506 - val_smape: 0.1349

Epoch 86/128

2293/2293 - 8s - 4ms/step - ia: 0.9510 - loss: 0.0114 - mae: 0.0770 - rmse: 0.1025 - smape: 0.1907 - val_ia: 0.8169 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0549 - val_smape: 0.1422

Epoch 87/128

2293/2293 - 8s - 4ms/step - ia: 0.9511 - loss: 0.0112 - mae: 0.0768 - rmse: 0.1017 - smape: 0.1907 - val_ia: 0.8318 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0522 - val_smape: 0.1394

Epoch 88/128

2293/2293 - 9s - 4ms/step - ia: 0.9512 - loss: 0.0113 - mae: 0.0769 - rmse: 0.1020 - smape: 0.1906 - val_ia: 0.8288 - val_loss: 0.0033 - val_mae: 0.0407 - val_rmse: 0.0519 - val_smape: 0.1349

Epoch 89/128

2293/2293 - 13s - 6ms/step - ia: 0.9515 - loss: 0.0110 - mae: 0.0762 - rmse: 0.1006 - smape: 0.1899 - val_ia: 0.8395 - val_loss: 0.0031 - val_mae: 0.0389 - val_rmse: 0.0500 - val_smape: 0.1286

Epoch 90/128

2293/2293 - 8s - 4ms/step - ia: 0.9515 - loss: 0.0111 - mae: 0.0762 - rmse: 0.1009 - smape: 0.1904 - val_ia: 0.8205 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0541 - val_smape: 0.1455

Epoch 91/128

2293/2293 - 11s - 5ms/step - ia: 0.9515 - loss: 0.0111 - mae: 0.0763 - rmse: 0.1010 - smape: 0.1896 - val_ia: 0.8360 - val_loss: 0.0032 - val_mae: 0.0393 - val_rmse: 0.0504 - val_smape: 0.1335

Epoch 92/128

2293/2293 - 19s - 8ms/step - ia: 0.9516 - loss: 0.0112 - mae: 0.0762 - rmse: 0.1012 - smape: 0.1878 - val_ia: 0.8366 - val_loss: 0.0032 - val_mae: 0.0397 - val_rmse: 0.0509 - val_smape: 0.1355

Epoch 93/128

2293/2293 - 8s - 3ms/step - ia: 0.9513 - loss: 0.0112 - mae: 0.0767 - rmse: 0.1017 - smape: 0.1898 - val_ia: 0.8240 - val_loss: 0.0035 - val_mae: 0.0420 - val_rmse: 0.0531 - val_smape: 0.1438

Epoch 94/128

2293/2293 - 8s - 4ms/step - ia: 0.9517 - loss: 0.0110 - mae: 0.0760 - rmse: 0.1007 - smape: 0.1887 - val_ia: 0.8006 - val_loss: 0.0039 - val_mae: 0.0461 - val_rmse: 0.0571 - val_smape: 0.1383

Epoch 95/128

2293/2293 - 5s - 2ms/step - ia: 0.9517 - loss: 0.0112 - mae: 0.0760 - rmse: 0.1013 - smape: 0.1874 - val_ia: 0.8381 - val_loss: 0.0031 - val_mae: 0.0390 - val_rmse: 0.0500 - val_smape: 0.1313

Epoch 96/128

2293/2293 - 5s - 2ms/step - ia: 0.9514 - loss: 0.0112 - mae: 0.0764 - rmse: 0.1013 - smape: 0.1859 - val_ia: 0.8361 - val_loss: 0.0033 - val_mae: 0.0400 - val_rmse: 0.0511 - val_smape: 0.1256

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 11s - 5ms/step - ia: 0.6849 - loss: 0.3857 - mae: 0.4878 - rmse: 0.6020 - smape: 0.8438 - val_ia: 0.4484 - val_loss: 0.1015 - val_mae: 0.2502 - val_rmse: 0.2724 - val_smape: 0.5873

Epoch 2/128

2293/2293 - 12s - 5ms/step - ia: 0.7616 - loss: 0.2308 - mae: 0.3807 - rmse: 0.4719 - smape: 0.7030 - val_ia: 0.5521 - val_loss: 0.0497 - val_mae: 0.1722 - val_rmse: 0.1948 - val_smape: 0.4611

Epoch 3/128

2293/2293 - 10s - 4ms/step - ia: 0.7873 - loss: 0.1828 - mae: 0.3398 - rmse: 0.4203 - smape: 0.6565 - val_ia: 0.5991 - val_loss: 0.0346 - val_mae: 0.1419 - val_rmse: 0.1633 - val_smape: 0.4013

Epoch 4/128

2293/2293 - 8s - 3ms/step - ia: 0.8062 - loss: 0.1507 - mae: 0.3080 - rmse: 0.3817 - smape: 0.6164 - val_ia: 0.6402 - val_loss: 0.0256 - val_mae: 0.1191 - val_rmse: 0.1399 - val_smape: 0.3393

Epoch 5/128

2293/2293 - 5s - 2ms/step - ia: 0.8236 - loss: 0.1237 - mae: 0.2795 - rmse: 0.3459 - smape: 0.5803 - val_ia: 0.6460 - val_loss: 0.0241 - val_mae: 0.1157 - val_rmse: 0.1362 - val_smape: 0.3231

Epoch 6/128

2293/2293 - 14s - 6ms/step - ia: 0.8402 - loss: 0.1005 - mae: 0.2514 - rmse: 0.3117 - smape: 0.5406 - val_ia: 0.6398 - val_loss: 0.0233 - val_mae: 0.1157 - val_rmse: 0.1355 - val_smape: 0.3274

Epoch 7/128

2293/2293 - 9s - 4ms/step - ia: 0.8539 - loss: 0.0836 - mae: 0.2281 - rmse: 0.2839 - smape: 0.5043 - val_ia: 0.6465 - val_loss: 0.0223 - val_mae: 0.1133 - val_rmse: 0.1325 - val_smape: 0.3237

Epoch 8/128

2293/2293 - 9s - 4ms/step - ia: 0.8658 - loss: 0.0708 - mae: 0.2096 - rmse: 0.2612 - smape: 0.4786 - val_ia: 0.6428 - val_loss: 0.0222 - val_mae: 0.1142 - val_rmse: 0.1328 - val_smape: 0.3208

Epoch 9/128

2293/2293 - 7s - 3ms/step - ia: 0.8762 - loss: 0.0610 - mae: 0.1940 - rmse: 0.2422 - smape: 0.4510 - val_ia: 0.6546 - val_loss: 0.0209 - val_mae: 0.1099 - val_rmse: 0.1282 - val_smape: 0.3050

Epoch 10/128

2293/2293 - 11s - 5ms/step - ia: 0.8837 - loss: 0.0537 - mae: 0.1814 - rmse: 0.2273 - smape: 0.4284 - val_ia: 0.6560 - val_loss: 0.0205 - val_mae: 0.1086 - val_rmse: 0.1265 - val_smape: 0.2940

Epoch 11/128

2293/2293 - 11s - 5ms/step - ia: 0.8906 - loss: 0.0477 - mae: 0.1704 - rmse: 0.2137 - smape: 0.4054 - val_ia: 0.6730 - val_loss: 0.0183 - val_mae: 0.1014 - val_rmse: 0.1189 - val_smape: 0.2754

Epoch 12/128

2293/2293 - 10s - 4ms/step - ia: 0.8958 - loss: 0.0439 - mae: 0.1628 - rmse: 0.2048 - smape: 0.3904 - val_ia: 0.6772 - val_loss: 0.0179 - val_mae: 0.0996 - val_rmse: 0.1170 - val_smape: 0.2629

Epoch 13/128

2293/2293 - 6s - 3ms/step - ia: 0.8991 - loss: 0.0416 - mae: 0.1580 - rmse: 0.1996 - smape: 0.3781 - val_ia: 0.6724 - val_loss: 0.0174 - val_mae: 0.1001 - val_rmse: 0.1173 - val_smape: 0.2677

Epoch 14/128

2293/2293 - 6s - 3ms/step - ia: 0.9016 - loss: 0.0394 - mae: 0.1541 - rmse: 0.1939 - smape: 0.3703 - val_ia: 0.6861 - val_loss: 0.0160 - val_mae: 0.0947 - val_rmse: 0.1116 - val_smape: 0.2494

Epoch 15/128

2293/2293 - 7s - 3ms/step - ia: 0.9038 - loss: 0.0375 - mae: 0.1505 - rmse: 0.1894 - smape: 0.3627 - val_ia: 0.6866 - val_loss: 0.0160 - val_mae: 0.0940 - val_rmse: 0.1109 - val_smape: 0.2397

Epoch 16/128

2293/2293 - 8s - 3ms/step - ia: 0.9058 - loss: 0.0364 - mae: 0.1475 - rmse: 0.1863 - smape: 0.3558 - val_ia: 0.6961 - val_loss: 0.0152 - val_mae: 0.0909 - val_rmse: 0.1075 - val_smape: 0.2309

Epoch 17/128

2293/2293 - 11s - 5ms/step - ia: 0.9068 - loss: 0.0355 - mae: 0.1457 - rmse: 0.1840 - smape: 0.3496 - val_ia: 0.7032 - val_loss: 0.0146 - val_mae: 0.0885 - val_rmse: 0.1049 - val_smape: 0.2218

Epoch 18/128

2293/2293 - 8s - 3ms/step - ia: 0.9087 - loss: 0.0344 - mae: 0.1434 - rmse: 0.1811 - smape: 0.3457 - val_ia: 0.7028 - val_loss: 0.0142 - val_mae: 0.0881 - val_rmse: 0.1043 - val_smape: 0.2220

Epoch 19/128

2293/2293 - 10s - 5ms/step - ia: 0.9090 - loss: 0.0336 - mae: 0.1419 - rmse: 0.1790 - smape: 0.3398 - val_ia: 0.7099 - val_loss: 0.0138 - val_mae: 0.0858 - val_rmse: 0.1018 - val_smape: 0.2112

Epoch 20/128

2293/2293 - 8s - 3ms/step - ia: 0.9106 - loss: 0.0328 - mae: 0.1401 - rmse: 0.1769 - smape: 0.3389 - val_ia: 0.7127 - val_loss: 0.0133 - val_mae: 0.0844 - val_rmse: 0.1002 - val_smape: 0.2077

Epoch 21/128

2293/2293 - 8s - 3ms/step - ia: 0.9111 - loss: 0.0325 - mae: 0.1397 - rmse: 0.1761 - smape: 0.3354 - val_ia: 0.7092 - val_loss: 0.0135 - val_mae: 0.0853 - val_rmse: 0.1011 - val_smape: 0.2089

Epoch 22/128

2293/2293 - 10s - 4ms/step - ia: 0.9117 - loss: 0.0321 - mae: 0.1385 - rmse: 0.1747 - smape: 0.3341 - val_ia: 0.7120 - val_loss: 0.0133 - val_mae: 0.0845 - val_rmse: 0.1002 - val_smape: 0.2043

Epoch 23/128

2293/2293 - 6s - 2ms/step - ia: 0.9130 - loss: 0.0312 - mae: 0.1363 - rmse: 0.1725 - smape: 0.3297 - val_ia: 0.7169 - val_loss: 0.0132 - val_mae: 0.0834 - val_rmse: 0.0990 - val_smape: 0.1980

Epoch 24/128

2293/2293 - 6s - 3ms/step - ia: 0.9140 - loss: 0.0307 - mae: 0.1351 - rmse: 0.1708 - smape: 0.3270 - val_ia: 0.7171 - val_loss: 0.0126 - val_mae: 0.0823 - val_rmse: 0.0978 - val_smape: 0.1992

Epoch 25/128

2293/2293 - 8s - 4ms/step - ia: 0.9143 - loss: 0.0305 - mae: 0.1345 - rmse: 0.1704 - smape: 0.3276 - val_ia: 0.7248 - val_loss: 0.0124 - val_mae: 0.0805 - val_rmse: 0.0958 - val_smape: 0.1921

Epoch 26/128

2293/2293 - 6s - 3ms/step - ia: 0.9156 - loss: 0.0297 - mae: 0.1325 - rmse: 0.1680 - smape: 0.3222 - val_ia: 0.7222 - val_loss: 0.0124 - val_mae: 0.0814 - val_rmse: 0.0966 - val_smape: 0.1943

Epoch 27/128

2293/2293 - 8s - 3ms/step - ia: 0.9159 - loss: 0.0295 - mae: 0.1324 - rmse: 0.1677 - smape: 0.3214 - val_ia: 0.7242 - val_loss: 0.0121 - val_mae: 0.0799 - val_rmse: 0.0952 - val_smape: 0.1891

Epoch 28/128

2293/2293 - 10s - 4ms/step - ia: 0.9163 - loss: 0.0290 - mae: 0.1313 - rmse: 0.1661 - smape: 0.3181 - val_ia: 0.7287 - val_loss: 0.0118 - val_mae: 0.0786 - val_rmse: 0.0937 - val_smape: 0.1857

Epoch 29/128

2293/2293 - 8s - 4ms/step - ia: 0.9168 - loss: 0.0288 - mae: 0.1306 - rmse: 0.1654 - smape: 0.3175 - val_ia: 0.7308 - val_loss: 0.0117 - val_mae: 0.0779 - val_rmse: 0.0929 - val_smape: 0.1838

Epoch 30/128

2293/2293 - 9s - 4ms/step - ia: 0.9173 - loss: 0.0284 - mae: 0.1299 - rmse: 0.1643 - smape: 0.3152 - val_ia: 0.7337 - val_loss: 0.0113 - val_mae: 0.0767 - val_rmse: 0.0915 - val_smape: 0.1812

Epoch 31/128

2293/2293 - 10s - 5ms/step - ia: 0.9176 - loss: 0.0283 - mae: 0.1293 - rmse: 0.1640 - smape: 0.3146 - val_ia: 0.7272 - val_loss: 0.0117 - val_mae: 0.0787 - val_rmse: 0.0936 - val_smape: 0.1849

Epoch 32/128

2293/2293 - 8s - 3ms/step - ia: 0.9179 - loss: 0.0283 - mae: 0.1292 - rmse: 0.1638 - smape: 0.3144 - val_ia: 0.7311 - val_loss: 0.0114 - val_mae: 0.0772 - val_rmse: 0.0920 - val_smape: 0.1809

Epoch 33/128

2293/2293 - 9s - 4ms/step - ia: 0.9184 - loss: 0.0279 - mae: 0.1282 - rmse: 0.1628 - smape: 0.3122 - val_ia: 0.7301 - val_loss: 0.0115 - val_mae: 0.0778 - val_rmse: 0.0925 - val_smape: 0.1809

Epoch 34/128

2293/2293 - 9s - 4ms/step - ia: 0.9188 - loss: 0.0272 - mae: 0.1273 - rmse: 0.1610 - smape: 0.3123 - val_ia: 0.7341 - val_loss: 0.0111 - val_mae: 0.0766 - val_rmse: 0.0911 - val_smape: 0.1805

Epoch 35/128

2293/2293 - 8s - 3ms/step - ia: 0.9200 - loss: 0.0268 - mae: 0.1257 - rmse: 0.1593 - smape: 0.3079 - val_ia: 0.7335 - val_loss: 0.0112 - val_mae: 0.0769 - val_rmse: 0.0912 - val_smape: 0.1803

Epoch 36/128

2293/2293 - 11s - 5ms/step - ia: 0.9201 - loss: 0.0268 - mae: 0.1256 - rmse: 0.1596 - smape: 0.3079 - val_ia: 0.7345 - val_loss: 0.0111 - val_mae: 0.0766 - val_rmse: 0.0910 - val_smape: 0.1795

Epoch 37/128

2293/2293 - 8s - 4ms/step - ia: 0.9205 - loss: 0.0267 - mae: 0.1250 - rmse: 0.1587 - smape: 0.3052 - val_ia: 0.7329 - val_loss: 0.0112 - val_mae: 0.0769 - val_rmse: 0.0913 - val_smape: 0.1791

Epoch 38/128

2293/2293 - 8s - 4ms/step - ia: 0.9201 - loss: 0.0265 - mae: 0.1253 - rmse: 0.1587 - smape: 0.3074 - val_ia: 0.7264 - val_loss: 0.0115 - val_mae: 0.0787 - val_rmse: 0.0930 - val_smape: 0.1836

Epoch 39/128

2293/2293 - 7s - 3ms/step - ia: 0.9213 - loss: 0.0259 - mae: 0.1237 - rmse: 0.1566 - smape: 0.3038 - val_ia: 0.7380 - val_loss: 0.0110 - val_mae: 0.0753 - val_rmse: 0.0895 - val_smape: 0.1719

Epoch 40/128

2293/2293 - 11s - 5ms/step - ia: 0.9217 - loss: 0.0257 - mae: 0.1230 - rmse: 0.1560 - smape: 0.3054 - val_ia: 0.7302 - val_loss: 0.0113 - val_mae: 0.0775 - val_rmse: 0.0917 - val_smape: 0.1791

Epoch 41/128

2293/2293 - 10s - 4ms/step - ia: 0.9225 - loss: 0.0255 - mae: 0.1221 - rmse: 0.1555 - smape: 0.3004 - val_ia: 0.7261 - val_loss: 0.0117 - val_mae: 0.0791 - val_rmse: 0.0932 - val_smape: 0.1814

Epoch 42/128

2293/2293 - 6s - 3ms/step - ia: 0.9217 - loss: 0.0256 - mae: 0.1228 - rmse: 0.1558 - smape: 0.3013 - val_ia: 0.7295 - val_loss: 0.0116 - val_mae: 0.0782 - val_rmse: 0.0923 - val_smape: 0.1773

Epoch 43/128

2293/2293 - 6s - 2ms/step - ia: 0.9232 - loss: 0.0251 - mae: 0.1211 - rmse: 0.1540 - smape: 0.2995 - val_ia: 0.7366 - val_loss: 0.0107 - val_mae: 0.0751 - val_rmse: 0.0891 - val_smape: 0.1746

Epoch 44/128

2293/2293 - 8s - 4ms/step - ia: 0.9224 - loss: 0.0254 - mae: 0.1216 - rmse: 0.1552 - smape: 0.2990 - val_ia: 0.7379 - val_loss: 0.0105 - val_mae: 0.0747 - val_rmse: 0.0887 - val_smape: 0.1746

Epoch 45/128

2293/2293 - 10s - 5ms/step - ia: 0.9230 - loss: 0.0250 - mae: 0.1210 - rmse: 0.1539 - smape: 0.2980 - val_ia: 0.7385 - val_loss: 0.0106 - val_mae: 0.0745 - val_rmse: 0.0885 - val_smape: 0.1711

Epoch 46/128

2293/2293 - 10s - 4ms/step - ia: 0.9235 - loss: 0.0247 - mae: 0.1201 - rmse: 0.1528 - smape: 0.2976 - val_ia: 0.7360 - val_loss: 0.0107 - val_mae: 0.0752 - val_rmse: 0.0891 - val_smape: 0.1738

Epoch 47/128

2293/2293 - 5s - 2ms/step - ia: 0.9243 - loss: 0.0243 - mae: 0.1190 - rmse: 0.1516 - smape: 0.2959 - val_ia: 0.7364 - val_loss: 0.0104 - val_mae: 0.0747 - val_rmse: 0.0885 - val_smape: 0.1744

Epoch 48/128

2293/2293 - 12s - 5ms/step - ia: 0.9242 - loss: 0.0241 - mae: 0.1191 - rmse: 0.1512 - smape: 0.2966 - val_ia: 0.7390 - val_loss: 0.0104 - val_mae: 0.0741 - val_rmse: 0.0879 - val_smape: 0.1712

Epoch 49/128

2293/2293 - 5s - 2ms/step - ia: 0.9246 - loss: 0.0242 - mae: 0.1184 - rmse: 0.1510 - smape: 0.2941 - val_ia: 0.7360 - val_loss: 0.0105 - val_mae: 0.0748 - val_rmse: 0.0885 - val_smape: 0.1732

Epoch 50/128

2293/2293 - 5s - 2ms/step - ia: 0.9246 - loss: 0.0240 - mae: 0.1184 - rmse: 0.1506 - smape: 0.2929 - val_ia: 0.7403 - val_loss: 0.0103 - val_mae: 0.0734 - val_rmse: 0.0872 - val_smape: 0.1689

Epoch 51/128

2293/2293 - 6s - 3ms/step - ia: 0.9249 - loss: 0.0237 - mae: 0.1177 - rmse: 0.1498 - smape: 0.2909 - val_ia: 0.7318 - val_loss: 0.0113 - val_mae: 0.0769 - val_rmse: 0.0906 - val_smape: 0.1722

Epoch 52/128

2293/2293 - 10s - 4ms/step - ia: 0.9254 - loss: 0.0235 - mae: 0.1174 - rmse: 0.1492 - smape: 0.2916 - val_ia: 0.7351 - val_loss: 0.0110 - val_mae: 0.0756 - val_rmse: 0.0893 - val_smape: 0.1691

Epoch 53/128

2293/2293 - 5s - 2ms/step - ia: 0.9252 - loss: 0.0237 - mae: 0.1177 - rmse: 0.1499 - smape: 0.2936 - val_ia: 0.7348 - val_loss: 0.0106 - val_mae: 0.0755 - val_rmse: 0.0891 - val_smape: 0.1752

Epoch 54/128

2293/2293 - 5s - 2ms/step - ia: 0.9262 - loss: 0.0232 - mae: 0.1160 - rmse: 0.1480 - smape: 0.2861 - val_ia: 0.7312 - val_loss: 0.0110 - val_mae: 0.0766 - val_rmse: 0.0902 - val_smape: 0.1762

Epoch 55/128

2293/2293 - 6s - 3ms/step - ia: 0.9257 - loss: 0.0233 - mae: 0.1163 - rmse: 0.1485 - smape: 0.2885 - val_ia: 0.7347 - val_loss: 0.0108 - val_mae: 0.0756 - val_rmse: 0.0892 - val_smape: 0.1723

Epoch 56/128

2293/2293 - 10s - 4ms/step - ia: 0.9263 - loss: 0.0231 - mae: 0.1157 - rmse: 0.1477 - smape: 0.2855 - val_ia: 0.7327 - val_loss: 0.0110 - val_mae: 0.0763 - val_rmse: 0.0898 - val_smape: 0.1730

Epoch 57/128

2293/2293 - 6s - 3ms/step - ia: 0.9263 - loss: 0.0231 - mae: 0.1159 - rmse: 0.1476 - smape: 0.2890 - val_ia: 0.7312 - val_loss: 0.0111 - val_mae: 0.0767 - val_rmse: 0.0903 - val_smape: 0.1728

Epoch 58/128

2293/2293 - 11s - 5ms/step - ia: 0.9268 - loss: 0.0228 - mae: 0.1148 - rmse: 0.1466 - smape: 0.2852 - val_ia: 0.7325 - val_loss: 0.0108 - val_mae: 0.0760 - val_rmse: 0.0895 - val_smape: 0.1749

Epoch 59/128

2293/2293 - 8s - 4ms/step - ia: 0.9273 - loss: 0.0226 - mae: 0.1145 - rmse: 0.1459 - smape: 0.2845 - val_ia: 0.7390 - val_loss: 0.0102 - val_mae: 0.0736 - val_rmse: 0.0870 - val_smape: 0.1693

Epoch 60/128

2293/2293 - 5s - 2ms/step - ia: 0.9271 - loss: 0.0226 - mae: 0.1146 - rmse: 0.1460 - smape: 0.2834 - val_ia: 0.7357 - val_loss: 0.0106 - val_mae: 0.0749 - val_rmse: 0.0884 - val_smape: 0.1701

Epoch 61/128

2293/2293 - 6s - 3ms/step - ia: 0.9270 - loss: 0.0226 - mae: 0.1148 - rmse: 0.1461 - smape: 0.2858 - val_ia: 0.7358 - val_loss: 0.0107 - val_mae: 0.0750 - val_rmse: 0.0884 - val_smape: 0.1692

Epoch 62/128

2293/2293 - 6s - 2ms/step - ia: 0.9281 - loss: 0.0222 - mae: 0.1132 - rmse: 0.1444 - smape: 0.2831 - val_ia: 0.7313 - val_loss: 0.0111 - val_mae: 0.0768 - val_rmse: 0.0902 - val_smape: 0.1722

Epoch 63/128

2293/2293 - 5s - 2ms/step - ia: 0.9279 - loss: 0.0222 - mae: 0.1131 - rmse: 0.1445 - smape: 0.2831 - val_ia: 0.7318 - val_loss: 0.0111 - val_mae: 0.0766 - val_rmse: 0.0900 - val_smape: 0.1711

Epoch 64/128

2293/2293 - 5s - 2ms/step - ia: 0.9282 - loss: 0.0220 - mae: 0.1128 - rmse: 0.1440 - smape: 0.2815 - val_ia: 0.7364 - val_loss: 0.0104 - val_mae: 0.0744 - val_rmse: 0.0877 - val_smape: 0.1697

Epoch 65/128

2293/2293 - 5s - 2ms/step - ia: 0.9283 - loss: 0.0218 - mae: 0.1127 - rmse: 0.1435 - smape: 0.2831 - val_ia: 0.7378 - val_loss: 0.0104 - val_mae: 0.0742 - val_rmse: 0.0875 - val_smape: 0.1666

Epoch 66/128

2293/2293 - 6s - 3ms/step - ia: 0.9291 - loss: 0.0215 - mae: 0.1115 - rmse: 0.1424 - smape: 0.2798 - val_ia: 0.7330 - val_loss: 0.0108 - val_mae: 0.0759 - val_rmse: 0.0892 - val_smape: 0.1705

Epoch 67/128

2293/2293 - 6s - 3ms/step - ia: 0.9287 - loss: 0.0218 - mae: 0.1121 - rmse: 0.1434 - smape: 0.2808 - val_ia: 0.7228 - val_loss: 0.0115 - val_mae: 0.0793 - val_rmse: 0.0924 - val_smape: 0.1809

Epoch 68/128

2293/2293 - 11s - 5ms/step - ia: 0.9293 - loss: 0.0215 - mae: 0.1118 - rmse: 0.1425 - smape: 0.2787 - val_ia: 0.7335 - val_loss: 0.0108 - val_mae: 0.0758 - val_rmse: 0.0890 - val_smape: 0.1689

Epoch 69/128

2293/2293 - 10s - 5ms/step - ia: 0.9295 - loss: 0.0212 - mae: 0.1109 - rmse: 0.1417 - smape: 0.2777 - val_ia: 0.7266 - val_loss: 0.0112 - val_mae: 0.0781 - val_rmse: 0.0910 - val_smape: 0.1780

Epoch 70/128

2293/2293 - 9s - 4ms/step - ia: 0.9302 - loss: 0.0209 - mae: 0.1098 - rmse: 0.1406 - smape: 0.2756 - val_ia: 0.7364 - val_loss: 0.0104 - val_mae: 0.0743 - val_rmse: 0.0874 - val_smape: 0.1660

Epoch 71/128

2293/2293 - 5s - 2ms/step - ia: 0.9297 - loss: 0.0212 - mae: 0.1106 - rmse: 0.1415 - smape: 0.2778 - val_ia: 0.7304 - val_loss: 0.0108 - val_mae: 0.0766 - val_rmse: 0.0897 - val_smape: 0.1728

Epoch 72/128

2293/2293 - 5s - 2ms/step - ia: 0.9303 - loss: 0.0209 - mae: 0.1096 - rmse: 0.1405 - smape: 0.2765 - val_ia: 0.7228 - val_loss: 0.0116 - val_mae: 0.0795 - val_rmse: 0.0924 - val_smape: 0.1769

Epoch 73/128

2293/2293 - 9s - 4ms/step - ia: 0.9301 - loss: 0.0209 - mae: 0.1097 - rmse: 0.1404 - smape: 0.2770 - val_ia: 0.7251 - val_loss: 0.0115 - val_mae: 0.0789 - val_rmse: 0.0919 - val_smape: 0.1769

Epoch 74/128

2293/2293 - 6s - 2ms/step - ia: 0.9300 - loss: 0.0210 - mae: 0.1098 - rmse: 0.1406 - smape: 0.2764 - val_ia: 0.7329 - val_loss: 0.0106 - val_mae: 0.0758 - val_rmse: 0.0887 - val_smape: 0.1732

Epoch 74: early stopping

Restoring model weights from the end of the best epoch: 59.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 46s 289ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 46%|████▌     | 23/50 [1:38:06<3:43:14, 496.09s/trial, best loss: 0.002580119351838799]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 10s - 5ms/step - ia: 0.8104 - loss: 0.1541 - mae: 0.3005 - rmse: 0.3716 - smape: 0.6027 - val_ia: 0.6584 - val_loss: 0.0212 - val_mae: 0.1096 - val_rmse: 0.1276 - val_smape: 0.3046

Epoch 2/128

2293/2293 - 7s - 3ms/step - ia: 0.8920 - loss: 0.0470 - mae: 0.1685 - rmse: 0.2118 - smape: 0.3982 - val_ia: 0.6751 - val_loss: 0.0183 - val_mae: 0.1006 - val_rmse: 0.1172 - val_smape: 0.2518

Epoch 3/128

2293/2293 - 6s - 3ms/step - ia: 0.9085 - loss: 0.0346 - mae: 0.1439 - rmse: 0.1815 - smape: 0.3447 - val_ia: 0.7149 - val_loss: 0.0133 - val_mae: 0.0849 - val_rmse: 0.0998 - val_smape: 0.2074

Epoch 4/128

2293/2293 - 10s - 5ms/step - ia: 0.9146 - loss: 0.0305 - mae: 0.1338 - rmse: 0.1701 - smape: 0.3255 - val_ia: 0.7260 - val_loss: 0.0118 - val_mae: 0.0796 - val_rmse: 0.0936 - val_smape: 0.1941

Epoch 5/128

2293/2293 - 10s - 5ms/step - ia: 0.9189 - loss: 0.0278 - mae: 0.1278 - rmse: 0.1622 - smape: 0.3123 - val_ia: 0.7284 - val_loss: 0.0114 - val_mae: 0.0787 - val_rmse: 0.0928 - val_smape: 0.1842

Epoch 6/128

2293/2293 - 6s - 3ms/step - ia: 0.9223 - loss: 0.0254 - mae: 0.1221 - rmse: 0.1552 - smape: 0.3015 - val_ia: 0.7255 - val_loss: 0.0116 - val_mae: 0.0792 - val_rmse: 0.0927 - val_smape: 0.1813

Epoch 7/128

2293/2293 - 5s - 2ms/step - ia: 0.9247 - loss: 0.0242 - mae: 0.1185 - rmse: 0.1513 - smape: 0.2937 - val_ia: 0.7222 - val_loss: 0.0117 - val_mae: 0.0807 - val_rmse: 0.0939 - val_smape: 0.1887

Epoch 8/128

2293/2293 - 4s - 2ms/step - ia: 0.9271 - loss: 0.0225 - mae: 0.1145 - rmse: 0.1459 - smape: 0.2858 - val_ia: 0.7343 - val_loss: 0.0101 - val_mae: 0.0741 - val_rmse: 0.0869 - val_smape: 0.1707

Epoch 9/128

2293/2293 - 5s - 2ms/step - ia: 0.9287 - loss: 0.0215 - mae: 0.1119 - rmse: 0.1430 - smape: 0.2811 - val_ia: 0.7363 - val_loss: 0.0101 - val_mae: 0.0739 - val_rmse: 0.0868 - val_smape: 0.1671

Epoch 10/128

2293/2293 - 6s - 3ms/step - ia: 0.9303 - loss: 0.0209 - mae: 0.1096 - rmse: 0.1403 - smape: 0.2742 - val_ia: 0.7426 - val_loss: 0.0094 - val_mae: 0.0713 - val_rmse: 0.0840 - val_smape: 0.1654

Epoch 11/128

2293/2293 - 10s - 4ms/step - ia: 0.9324 - loss: 0.0198 - mae: 0.1063 - rmse: 0.1365 - smape: 0.2690 - val_ia: 0.7478 - val_loss: 0.0090 - val_mae: 0.0695 - val_rmse: 0.0820 - val_smape: 0.1591

Epoch 12/128

2293/2293 - 6s - 3ms/step - ia: 0.9342 - loss: 0.0189 - mae: 0.1034 - rmse: 0.1332 - smape: 0.2618 - val_ia: 0.7350 - val_loss: 0.0098 - val_mae: 0.0731 - val_rmse: 0.0854 - val_smape: 0.1632

Epoch 13/128

2293/2293 - 10s - 4ms/step - ia: 0.9358 - loss: 0.0179 - mae: 0.1006 - rmse: 0.1296 - smape: 0.2558 - val_ia: 0.7682 - val_loss: 0.0073 - val_mae: 0.0616 - val_rmse: 0.0739 - val_smape: 0.1449

Epoch 14/128

2293/2293 - 10s - 5ms/step - ia: 0.9374 - loss: 0.0171 - mae: 0.0984 - rmse: 0.1268 - smape: 0.2497 - val_ia: 0.7594 - val_loss: 0.0077 - val_mae: 0.0644 - val_rmse: 0.0764 - val_smape: 0.1491

Epoch 15/128

2293/2293 - 6s - 3ms/step - ia: 0.9383 - loss: 0.0167 - mae: 0.0970 - rmse: 0.1252 - smape: 0.2482 - val_ia: 0.7537 - val_loss: 0.0081 - val_mae: 0.0661 - val_rmse: 0.0779 - val_smape: 0.1532

Epoch 16/128

2293/2293 - 6s - 3ms/step - ia: 0.9397 - loss: 0.0160 - mae: 0.0946 - rmse: 0.1225 - smape: 0.2424 - val_ia: 0.7768 - val_loss: 0.0060 - val_mae: 0.0568 - val_rmse: 0.0686 - val_smape: 0.1491

Epoch 17/128

2293/2293 - 6s - 3ms/step - ia: 0.9404 - loss: 0.0158 - mae: 0.0936 - rmse: 0.1213 - smape: 0.2379 - val_ia: 0.8011 - val_loss: 0.0048 - val_mae: 0.0505 - val_rmse: 0.0622 - val_smape: 0.1454

Epoch 18/128

2293/2293 - 4s - 2ms/step - ia: 0.9416 - loss: 0.0152 - mae: 0.0916 - rmse: 0.1190 - smape: 0.2342 - val_ia: 0.8023 - val_loss: 0.0047 - val_mae: 0.0489 - val_rmse: 0.0606 - val_smape: 0.1403

Epoch 19/128

2293/2293 - 4s - 2ms/step - ia: 0.9426 - loss: 0.0148 - mae: 0.0904 - rmse: 0.1172 - smape: 0.2327 - val_ia: 0.8009 - val_loss: 0.0047 - val_mae: 0.0490 - val_rmse: 0.0607 - val_smape: 0.1395

Epoch 20/128

2293/2293 - 5s - 2ms/step - ia: 0.9433 - loss: 0.0143 - mae: 0.0887 - rmse: 0.1155 - smape: 0.2299 - val_ia: 0.8073 - val_loss: 0.0047 - val_mae: 0.0487 - val_rmse: 0.0604 - val_smape: 0.1407

Epoch 21/128

2293/2293 - 4s - 2ms/step - ia: 0.9437 - loss: 0.0142 - mae: 0.0882 - rmse: 0.1148 - smape: 0.2263 - val_ia: 0.7846 - val_loss: 0.0052 - val_mae: 0.0531 - val_rmse: 0.0645 - val_smape: 0.1511

Epoch 22/128

2293/2293 - 5s - 2ms/step - ia: 0.9448 - loss: 0.0138 - mae: 0.0868 - rmse: 0.1133 - smape: 0.2228 - val_ia: 0.7697 - val_loss: 0.0057 - val_mae: 0.0563 - val_rmse: 0.0678 - val_smape: 0.1506

Epoch 23/128

2293/2293 - 5s - 2ms/step - ia: 0.9451 - loss: 0.0138 - mae: 0.0863 - rmse: 0.1129 - smape: 0.2199 - val_ia: 0.8309 - val_loss: 0.0040 - val_mae: 0.0428 - val_rmse: 0.0546 - val_smape: 0.1268

Epoch 24/128

2293/2293 - 4s - 2ms/step - ia: 0.9457 - loss: 0.0133 - mae: 0.0852 - rmse: 0.1113 - smape: 0.2205 - val_ia: 0.8257 - val_loss: 0.0039 - val_mae: 0.0431 - val_rmse: 0.0548 - val_smape: 0.1379

Epoch 25/128

2293/2293 - 4s - 2ms/step - ia: 0.9462 - loss: 0.0133 - mae: 0.0847 - rmse: 0.1112 - smape: 0.2168 - val_ia: 0.8296 - val_loss: 0.0038 - val_mae: 0.0423 - val_rmse: 0.0540 - val_smape: 0.1307

Epoch 26/128

2293/2293 - 5s - 2ms/step - ia: 0.9461 - loss: 0.0133 - mae: 0.0845 - rmse: 0.1109 - smape: 0.2168 - val_ia: 0.7734 - val_loss: 0.0053 - val_mae: 0.0550 - val_rmse: 0.0663 - val_smape: 0.1614

Epoch 27/128

2293/2293 - 11s - 5ms/step - ia: 0.9461 - loss: 0.0131 - mae: 0.0844 - rmse: 0.1104 - smape: 0.2154 - val_ia: 0.7967 - val_loss: 0.0044 - val_mae: 0.0477 - val_rmse: 0.0592 - val_smape: 0.1411

Epoch 28/128

2293/2293 - 10s - 4ms/step - ia: 0.9468 - loss: 0.0130 - mae: 0.0834 - rmse: 0.1096 - smape: 0.2123 - val_ia: 0.8181 - val_loss: 0.0041 - val_mae: 0.0449 - val_rmse: 0.0567 - val_smape: 0.1338

Epoch 29/128

2293/2293 - 4s - 2ms/step - ia: 0.9470 - loss: 0.0129 - mae: 0.0832 - rmse: 0.1091 - smape: 0.2125 - val_ia: 0.8292 - val_loss: 0.0037 - val_mae: 0.0415 - val_rmse: 0.0531 - val_smape: 0.1312

Epoch 30/128

2293/2293 - 4s - 2ms/step - ia: 0.9475 - loss: 0.0126 - mae: 0.0822 - rmse: 0.1079 - smape: 0.2135 - val_ia: 0.8241 - val_loss: 0.0038 - val_mae: 0.0431 - val_rmse: 0.0547 - val_smape: 0.1438

Epoch 31/128

2293/2293 - 4s - 2ms/step - ia: 0.9478 - loss: 0.0126 - mae: 0.0821 - rmse: 0.1080 - smape: 0.2089 - val_ia: 0.8294 - val_loss: 0.0038 - val_mae: 0.0428 - val_rmse: 0.0544 - val_smape: 0.1360

Epoch 32/128

2293/2293 - 6s - 3ms/step - ia: 0.9476 - loss: 0.0127 - mae: 0.0823 - rmse: 0.1083 - smape: 0.2098 - val_ia: 0.7912 - val_loss: 0.0045 - val_mae: 0.0486 - val_rmse: 0.0601 - val_smape: 0.1407

Epoch 33/128

2293/2293 - 8s - 3ms/step - ia: 0.9478 - loss: 0.0126 - mae: 0.0819 - rmse: 0.1078 - smape: 0.2083 - val_ia: 0.8298 - val_loss: 0.0036 - val_mae: 0.0410 - val_rmse: 0.0525 - val_smape: 0.1338

Epoch 34/128

2293/2293 - 8s - 3ms/step - ia: 0.9484 - loss: 0.0123 - mae: 0.0811 - rmse: 0.1064 - smape: 0.2065 - val_ia: 0.8303 - val_loss: 0.0037 - val_mae: 0.0419 - val_rmse: 0.0534 - val_smape: 0.1385

Epoch 35/128

2293/2293 - 10s - 5ms/step - ia: 0.9484 - loss: 0.0123 - mae: 0.0809 - rmse: 0.1066 - smape: 0.2058 - val_ia: 0.8263 - val_loss: 0.0037 - val_mae: 0.0424 - val_rmse: 0.0539 - val_smape: 0.1398

Epoch 36/128

2293/2293 - 8s - 3ms/step - ia: 0.9484 - loss: 0.0123 - mae: 0.0811 - rmse: 0.1065 - smape: 0.2076 - val_ia: 0.8310 - val_loss: 0.0037 - val_mae: 0.0414 - val_rmse: 0.0530 - val_smape: 0.1312

Epoch 37/128

2293/2293 - 8s - 3ms/step - ia: 0.9486 - loss: 0.0122 - mae: 0.0805 - rmse: 0.1060 - smape: 0.2055 - val_ia: 0.8228 - val_loss: 0.0037 - val_mae: 0.0422 - val_rmse: 0.0537 - val_smape: 0.1355

Epoch 38/128

2293/2293 - 6s - 3ms/step - ia: 0.9487 - loss: 0.0122 - mae: 0.0805 - rmse: 0.1061 - smape: 0.2035 - val_ia: 0.8155 - val_loss: 0.0038 - val_mae: 0.0436 - val_rmse: 0.0550 - val_smape: 0.1392

Epoch 39/128

2293/2293 - 5s - 2ms/step - ia: 0.9486 - loss: 0.0122 - mae: 0.0804 - rmse: 0.1061 - smape: 0.2036 - val_ia: 0.8273 - val_loss: 0.0037 - val_mae: 0.0431 - val_rmse: 0.0546 - val_smape: 0.1417

Epoch 40/128

2293/2293 - 4s - 2ms/step - ia: 0.9486 - loss: 0.0123 - mae: 0.0808 - rmse: 0.1065 - smape: 0.2043 - val_ia: 0.7993 - val_loss: 0.0043 - val_mae: 0.0476 - val_rmse: 0.0591 - val_smape: 0.1456

Epoch 41/128

2293/2293 - 5s - 2ms/step - ia: 0.9487 - loss: 0.0122 - mae: 0.0803 - rmse: 0.1060 - smape: 0.2016 - val_ia: 0.8172 - val_loss: 0.0038 - val_mae: 0.0439 - val_rmse: 0.0554 - val_smape: 0.1460

Epoch 42/128

2293/2293 - 4s - 2ms/step - ia: 0.9491 - loss: 0.0121 - mae: 0.0799 - rmse: 0.1056 - smape: 0.2020 - val_ia: 0.8215 - val_loss: 0.0038 - val_mae: 0.0436 - val_rmse: 0.0550 - val_smape: 0.1527

Epoch 43/128

2293/2293 - 4s - 2ms/step - ia: 0.9493 - loss: 0.0120 - mae: 0.0796 - rmse: 0.1051 - smape: 0.2006 - val_ia: 0.8321 - val_loss: 0.0035 - val_mae: 0.0419 - val_rmse: 0.0533 - val_smape: 0.1348

Epoch 44/128

2293/2293 - 4s - 2ms/step - ia: 0.9492 - loss: 0.0121 - mae: 0.0798 - rmse: 0.1056 - smape: 0.2003 - val_ia: 0.8325 - val_loss: 0.0035 - val_mae: 0.0416 - val_rmse: 0.0530 - val_smape: 0.1370

Epoch 45/128

2293/2293 - 6s - 3ms/step - ia: 0.9490 - loss: 0.0122 - mae: 0.0802 - rmse: 0.1060 - smape: 0.2007 - val_ia: 0.7908 - val_loss: 0.0044 - val_mae: 0.0496 - val_rmse: 0.0608 - val_smape: 0.1512

Epoch 46/128

2293/2293 - 8s - 3ms/step - ia: 0.9496 - loss: 0.0118 - mae: 0.0791 - rmse: 0.1044 - smape: 0.2000 - val_ia: 0.8174 - val_loss: 0.0036 - val_mae: 0.0427 - val_rmse: 0.0540 - val_smape: 0.1426

Epoch 47/128

2293/2293 - 7s - 3ms/step - ia: 0.9493 - loss: 0.0120 - mae: 0.0795 - rmse: 0.1052 - smape: 0.2012 - val_ia: 0.8188 - val_loss: 0.0039 - val_mae: 0.0446 - val_rmse: 0.0561 - val_smape: 0.1457

Epoch 48/128

2293/2293 - 11s - 5ms/step - ia: 0.9495 - loss: 0.0120 - mae: 0.0794 - rmse: 0.1050 - smape: 0.1990 - val_ia: 0.8289 - val_loss: 0.0035 - val_mae: 0.0411 - val_rmse: 0.0525 - val_smape: 0.1382

Epoch 49/128

2293/2293 - 8s - 3ms/step - ia: 0.9500 - loss: 0.0117 - mae: 0.0788 - rmse: 0.1040 - smape: 0.1981 - val_ia: 0.8277 - val_loss: 0.0036 - val_mae: 0.0427 - val_rmse: 0.0540 - val_smape: 0.1465

Epoch 50/128

2293/2293 - 7s - 3ms/step - ia: 0.9496 - loss: 0.0119 - mae: 0.0791 - rmse: 0.1046 - smape: 0.1987 - val_ia: 0.7807 - val_loss: 0.0048 - val_mae: 0.0522 - val_rmse: 0.0631 - val_smape: 0.1593

Epoch 51/128

2293/2293 - 9s - 4ms/step - ia: 0.9496 - loss: 0.0117 - mae: 0.0789 - rmse: 0.1040 - smape: 0.1987 - val_ia: 0.7911 - val_loss: 0.0044 - val_mae: 0.0494 - val_rmse: 0.0606 - val_smape: 0.1506

Epoch 52/128

2293/2293 - 12s - 5ms/step - ia: 0.9497 - loss: 0.0118 - mae: 0.0790 - rmse: 0.1042 - smape: 0.1979 - val_ia: 0.8128 - val_loss: 0.0038 - val_mae: 0.0441 - val_rmse: 0.0553 - val_smape: 0.1460

Epoch 53/128

2293/2293 - 10s - 4ms/step - ia: 0.9497 - loss: 0.0118 - mae: 0.0789 - rmse: 0.1040 - smape: 0.1955 - val_ia: 0.8334 - val_loss: 0.0033 - val_mae: 0.0401 - val_rmse: 0.0514 - val_smape: 0.1369

Epoch 54/128

2293/2293 - 10s - 5ms/step - ia: 0.9499 - loss: 0.0118 - mae: 0.0789 - rmse: 0.1041 - smape: 0.1976 - val_ia: 0.8361 - val_loss: 0.0033 - val_mae: 0.0396 - val_rmse: 0.0507 - val_smape: 0.1344

Epoch 55/128

2293/2293 - 11s - 5ms/step - ia: 0.9502 - loss: 0.0118 - mae: 0.0784 - rmse: 0.1038 - smape: 0.1945 - val_ia: 0.8324 - val_loss: 0.0033 - val_mae: 0.0396 - val_rmse: 0.0509 - val_smape: 0.1338

Epoch 56/128

2293/2293 - 7s - 3ms/step - ia: 0.9503 - loss: 0.0116 - mae: 0.0781 - rmse: 0.1034 - smape: 0.1956 - val_ia: 0.8265 - val_loss: 0.0035 - val_mae: 0.0418 - val_rmse: 0.0533 - val_smape: 0.1367

Epoch 57/128

2293/2293 - 5s - 2ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0782 - rmse: 0.1035 - smape: 0.1940 - val_ia: 0.8326 - val_loss: 0.0034 - val_mae: 0.0407 - val_rmse: 0.0519 - val_smape: 0.1393

Epoch 58/128

2293/2293 - 5s - 2ms/step - ia: 0.9500 - loss: 0.0117 - mae: 0.0784 - rmse: 0.1038 - smape: 0.1963 - val_ia: 0.8161 - val_loss: 0.0037 - val_mae: 0.0436 - val_rmse: 0.0549 - val_smape: 0.1406

Epoch 59/128

2293/2293 - 8s - 3ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0779 - rmse: 0.1033 - smape: 0.1940 - val_ia: 0.8372 - val_loss: 0.0032 - val_mae: 0.0393 - val_rmse: 0.0505 - val_smape: 0.1334

Epoch 60/128

2293/2293 - 10s - 5ms/step - ia: 0.9506 - loss: 0.0114 - mae: 0.0778 - rmse: 0.1028 - smape: 0.1932 - val_ia: 0.8190 - val_loss: 0.0037 - val_mae: 0.0432 - val_rmse: 0.0545 - val_smape: 0.1395

Epoch 61/128

2293/2293 - 7s - 3ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0779 - rmse: 0.1033 - smape: 0.1947 - val_ia: 0.8301 - val_loss: 0.0036 - val_mae: 0.0418 - val_rmse: 0.0530 - val_smape: 0.1436

Epoch 62/128

2293/2293 - 5s - 2ms/step - ia: 0.9505 - loss: 0.0115 - mae: 0.0778 - rmse: 0.1030 - smape: 0.1933 - val_ia: 0.8291 - val_loss: 0.0036 - val_mae: 0.0425 - val_rmse: 0.0535 - val_smape: 0.1359

Epoch 63/128

2293/2293 - 5s - 2ms/step - ia: 0.9505 - loss: 0.0115 - mae: 0.0777 - rmse: 0.1030 - smape: 0.1930 - val_ia: 0.8107 - val_loss: 0.0038 - val_mae: 0.0451 - val_rmse: 0.0562 - val_smape: 0.1423

Epoch 64/128

2293/2293 - 5s - 2ms/step - ia: 0.9507 - loss: 0.0116 - mae: 0.0777 - rmse: 0.1033 - smape: 0.1917 - val_ia: 0.8262 - val_loss: 0.0036 - val_mae: 0.0431 - val_rmse: 0.0542 - val_smape: 0.1409

Epoch 65/128

2293/2293 - 5s - 2ms/step - ia: 0.9507 - loss: 0.0114 - mae: 0.0772 - rmse: 0.1022 - smape: 0.1918 - val_ia: 0.8238 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0538 - val_smape: 0.1344

Epoch 66/128

2293/2293 - 5s - 2ms/step - ia: 0.9509 - loss: 0.0115 - mae: 0.0773 - rmse: 0.1030 - smape: 0.1912 - val_ia: 0.8231 - val_loss: 0.0039 - val_mae: 0.0453 - val_rmse: 0.0563 - val_smape: 0.1504

Epoch 67/128

2293/2293 - 4s - 2ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0779 - rmse: 0.1032 - smape: 0.1917 - val_ia: 0.7850 - val_loss: 0.0043 - val_mae: 0.0498 - val_rmse: 0.0607 - val_smape: 0.1515

Epoch 68/128

2293/2293 - 4s - 2ms/step - ia: 0.9510 - loss: 0.0114 - mae: 0.0770 - rmse: 0.1020 - smape: 0.1913 - val_ia: 0.8147 - val_loss: 0.0037 - val_mae: 0.0441 - val_rmse: 0.0551 - val_smape: 0.1429

Epoch 69/128

2293/2293 - 4s - 2ms/step - ia: 0.9506 - loss: 0.0116 - mae: 0.0778 - rmse: 0.1032 - smape: 0.1916 - val_ia: 0.8347 - val_loss: 0.0033 - val_mae: 0.0398 - val_rmse: 0.0511 - val_smape: 0.1353

Epoch 70/128

2293/2293 - 4s - 2ms/step - ia: 0.9505 - loss: 0.0114 - mae: 0.0775 - rmse: 0.1026 - smape: 0.1912 - val_ia: 0.8277 - val_loss: 0.0035 - val_mae: 0.0416 - val_rmse: 0.0529 - val_smape: 0.1411

Epoch 71/128

2293/2293 - 4s - 2ms/step - ia: 0.9508 - loss: 0.0114 - mae: 0.0771 - rmse: 0.1022 - smape: 0.1896 - val_ia: 0.8307 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0519 - val_smape: 0.1315

Epoch 72/128

2293/2293 - 5s - 2ms/step - ia: 0.9510 - loss: 0.0114 - mae: 0.0770 - rmse: 0.1022 - smape: 0.1900 - val_ia: 0.8303 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0520 - val_smape: 0.1268

Epoch 73/128

2293/2293 - 8s - 4ms/step - ia: 0.9509 - loss: 0.0114 - mae: 0.0773 - rmse: 0.1026 - smape: 0.1905 - val_ia: 0.7895 - val_loss: 0.0043 - val_mae: 0.0496 - val_rmse: 0.0605 - val_smape: 0.1566

Epoch 74/128

2293/2293 - 10s - 5ms/step - ia: 0.9510 - loss: 0.0114 - mae: 0.0770 - rmse: 0.1022 - smape: 0.1907 - val_ia: 0.8393 - val_loss: 0.0030 - val_mae: 0.0379 - val_rmse: 0.0488 - val_smape: 0.1330

Epoch 75/128

2293/2293 - 10s - 4ms/step - ia: 0.9509 - loss: 0.0116 - mae: 0.0773 - rmse: 0.1030 - smape: 0.1888 - val_ia: 0.8318 - val_loss: 0.0033 - val_mae: 0.0403 - val_rmse: 0.0514 - val_smape: 0.1393

Epoch 76/128

2293/2293 - 9s - 4ms/step - ia: 0.9507 - loss: 0.0115 - mae: 0.0774 - rmse: 0.1025 - smape: 0.1908 - val_ia: 0.8366 - val_loss: 0.0033 - val_mae: 0.0402 - val_rmse: 0.0512 - val_smape: 0.1319

Epoch 77/128

2293/2293 - 8s - 4ms/step - ia: 0.9512 - loss: 0.0112 - mae: 0.0768 - rmse: 0.1016 - smape: 0.1888 - val_ia: 0.8188 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0547 - val_smape: 0.1440

Epoch 78/128

2293/2293 - 5s - 2ms/step - ia: 0.9511 - loss: 0.0113 - mae: 0.0767 - rmse: 0.1018 - smape: 0.1895 - val_ia: 0.8109 - val_loss: 0.0038 - val_mae: 0.0450 - val_rmse: 0.0560 - val_smape: 0.1445

Epoch 79/128

2293/2293 - 4s - 2ms/step - ia: 0.9515 - loss: 0.0113 - mae: 0.0763 - rmse: 0.1014 - smape: 0.1888 - val_ia: 0.8293 - val_loss: 0.0033 - val_mae: 0.0406 - val_rmse: 0.0517 - val_smape: 0.1328

Epoch 80/128

2293/2293 - 5s - 2ms/step - ia: 0.9514 - loss: 0.0113 - mae: 0.0764 - rmse: 0.1017 - smape: 0.1887 - val_ia: 0.7998 - val_loss: 0.0040 - val_mae: 0.0471 - val_rmse: 0.0582 - val_smape: 0.1484

Epoch 81/128

2293/2293 - 5s - 2ms/step - ia: 0.9511 - loss: 0.0114 - mae: 0.0770 - rmse: 0.1024 - smape: 0.1889 - val_ia: 0.8377 - val_loss: 0.0031 - val_mae: 0.0386 - val_rmse: 0.0496 - val_smape: 0.1313

Epoch 82/128

2293/2293 - 5s - 2ms/step - ia: 0.9512 - loss: 0.0113 - mae: 0.0766 - rmse: 0.1019 - smape: 0.1895 - val_ia: 0.8374 - val_loss: 0.0032 - val_mae: 0.0391 - val_rmse: 0.0503 - val_smape: 0.1307

Epoch 83/128

2293/2293 - 5s - 2ms/step - ia: 0.9514 - loss: 0.0113 - mae: 0.0764 - rmse: 0.1016 - smape: 0.1892 - val_ia: 0.8371 - val_loss: 0.0031 - val_mae: 0.0392 - val_rmse: 0.0501 - val_smape: 0.1293

Epoch 84/128

2293/2293 - 7s - 3ms/step - ia: 0.9515 - loss: 0.0112 - mae: 0.0762 - rmse: 0.1013 - smape: 0.1879 - val_ia: 0.8459 - val_loss: 0.0029 - val_mae: 0.0366 - val_rmse: 0.0477 - val_smape: 0.1202

Epoch 85/128

2293/2293 - 12s - 5ms/step - ia: 0.9510 - loss: 0.0113 - mae: 0.0768 - rmse: 0.1022 - smape: 0.1871 - val_ia: 0.8435 - val_loss: 0.0030 - val_mae: 0.0374 - val_rmse: 0.0485 - val_smape: 0.1257

Epoch 86/128

2293/2293 - 10s - 4ms/step - ia: 0.9517 - loss: 0.0112 - mae: 0.0760 - rmse: 0.1012 - smape: 0.1865 - val_ia: 0.8317 - val_loss: 0.0036 - val_mae: 0.0421 - val_rmse: 0.0531 - val_smape: 0.1329

Epoch 87/128

2293/2293 - 7s - 3ms/step - ia: 0.9515 - loss: 0.0110 - mae: 0.0761 - rmse: 0.1009 - smape: 0.1878 - val_ia: 0.8116 - val_loss: 0.0038 - val_mae: 0.0461 - val_rmse: 0.0569 - val_smape: 0.1359

Epoch 88/128

2293/2293 - 5s - 2ms/step - ia: 0.9517 - loss: 0.0111 - mae: 0.0758 - rmse: 0.1008 - smape: 0.1862 - val_ia: 0.8351 - val_loss: 0.0033 - val_mae: 0.0401 - val_rmse: 0.0513 - val_smape: 0.1344

Epoch 89/128

2293/2293 - 5s - 2ms/step - ia: 0.9515 - loss: 0.0113 - mae: 0.0764 - rmse: 0.1018 - smape: 0.1862 - val_ia: 0.8220 - val_loss: 0.0035 - val_mae: 0.0421 - val_rmse: 0.0532 - val_smape: 0.1349

Epoch 90/128

2293/2293 - 5s - 2ms/step - ia: 0.9510 - loss: 0.0115 - mae: 0.0770 - rmse: 0.1028 - smape: 0.1863 - val_ia: 0.8339 - val_loss: 0.0033 - val_mae: 0.0403 - val_rmse: 0.0515 - val_smape: 0.1365

Epoch 91/128

2293/2293 - 5s - 2ms/step - ia: 0.9519 - loss: 0.0112 - mae: 0.0758 - rmse: 0.1010 - smape: 0.1866 - val_ia: 0.8243 - val_loss: 0.0037 - val_mae: 0.0430 - val_rmse: 0.0541 - val_smape: 0.1270

Epoch 92/128

2293/2293 - 5s - 2ms/step - ia: 0.9513 - loss: 0.0113 - mae: 0.0765 - rmse: 0.1017 - smape: 0.1879 - val_ia: 0.8316 - val_loss: 0.0034 - val_mae: 0.0414 - val_rmse: 0.0522 - val_smape: 0.1368

Epoch 93/128

2293/2293 - 8s - 4ms/step - ia: 0.9514 - loss: 0.0112 - mae: 0.0764 - rmse: 0.1015 - smape: 0.1860 - val_ia: 0.8287 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0528 - val_smape: 0.1254

Epoch 94/128

2293/2293 - 9s - 4ms/step - ia: 0.9515 - loss: 0.0112 - mae: 0.0761 - rmse: 0.1016 - smape: 0.1855 - val_ia: 0.8265 - val_loss: 0.0035 - val_mae: 0.0423 - val_rmse: 0.0535 - val_smape: 0.1417

Epoch 95/128

2293/2293 - 10s - 4ms/step - ia: 0.9516 - loss: 0.0113 - mae: 0.0760 - rmse: 0.1016 - smape: 0.1865 - val_ia: 0.8391 - val_loss: 0.0030 - val_mae: 0.0383 - val_rmse: 0.0492 - val_smape: 0.1283

Epoch 96/128

2293/2293 - 6s - 3ms/step - ia: 0.9513 - loss: 0.0113 - mae: 0.0766 - rmse: 0.1020 - smape: 0.1862 - val_ia: 0.8403 - val_loss: 0.0030 - val_mae: 0.0381 - val_rmse: 0.0492 - val_smape: 0.1291

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 6s - 5ms/step - ia: 0.6816 - loss: 0.3758 - mae: 0.4665 - rmse: 0.5759 - smape: 0.8420 - val_ia: 0.5215 - val_loss: 0.1671 - val_mae: 0.3156 - val_rmse: 0.3715 - val_smape: 0.6576

Epoch 2/128

1147/1147 - 5s - 4ms/step - ia: 0.8164 - loss: 0.1416 - mae: 0.2928 - rmse: 0.3715 - smape: 0.6011 - val_ia: 0.6111 - val_loss: 0.0966 - val_mae: 0.2417 - val_rmse: 0.2833 - val_smape: 0.5675

Epoch 3/128

1147/1147 - 3s - 2ms/step - ia: 0.8444 - loss: 0.1029 - mae: 0.2513 - rmse: 0.3172 - smape: 0.5404 - val_ia: 0.7005 - val_loss: 0.0473 - val_mae: 0.1657 - val_rmse: 0.2011 - val_smape: 0.4447

Epoch 4/128

1147/1147 - 5s - 4ms/step - ia: 0.8551 - loss: 0.0900 - mae: 0.2354 - rmse: 0.2969 - smape: 0.5132 - val_ia: 0.7416 - val_loss: 0.0315 - val_mae: 0.1328 - val_rmse: 0.1650 - val_smape: 0.3627

Epoch 5/128

1147/1147 - 6s - 5ms/step - ia: 0.8630 - loss: 0.0803 - mae: 0.2224 - rmse: 0.2805 - smape: 0.4932 - val_ia: 0.7629 - val_loss: 0.0255 - val_mae: 0.1188 - val_rmse: 0.1489 - val_smape: 0.3317

Epoch 6/128

1147/1147 - 10s - 9ms/step - ia: 0.8690 - loss: 0.0730 - mae: 0.2125 - rmse: 0.2675 - smape: 0.4821 - val_ia: 0.7785 - val_loss: 0.0213 - val_mae: 0.1082 - val_rmse: 0.1362 - val_smape: 0.3064

Epoch 7/128

1147/1147 - 5s - 4ms/step - ia: 0.8746 - loss: 0.0669 - mae: 0.2029 - rmse: 0.2561 - smape: 0.4685 - val_ia: 0.7939 - val_loss: 0.0186 - val_mae: 0.1005 - val_rmse: 0.1271 - val_smape: 0.2900

Epoch 8/128

1147/1147 - 6s - 5ms/step - ia: 0.8799 - loss: 0.0613 - mae: 0.1944 - rmse: 0.2447 - smape: 0.4541 - val_ia: 0.7932 - val_loss: 0.0169 - val_mae: 0.0977 - val_rmse: 0.1222 - val_smape: 0.2814

Epoch 9/128

1147/1147 - 5s - 4ms/step - ia: 0.8840 - loss: 0.0570 - mae: 0.1877 - rmse: 0.2362 - smape: 0.4410 - val_ia: 0.8099 - val_loss: 0.0147 - val_mae: 0.0896 - val_rmse: 0.1132 - val_smape: 0.2601

Epoch 10/128

1147/1147 - 4s - 3ms/step - ia: 0.8884 - loss: 0.0530 - mae: 0.1806 - rmse: 0.2277 - smape: 0.4330 - val_ia: 0.8181 - val_loss: 0.0134 - val_mae: 0.0856 - val_rmse: 0.1084 - val_smape: 0.2537

Epoch 11/128

1147/1147 - 6s - 6ms/step - ia: 0.8927 - loss: 0.0486 - mae: 0.1734 - rmse: 0.2182 - smape: 0.4215 - val_ia: 0.8237 - val_loss: 0.0127 - val_mae: 0.0821 - val_rmse: 0.1041 - val_smape: 0.2366

Epoch 12/128

1147/1147 - 4s - 3ms/step - ia: 0.8963 - loss: 0.0455 - mae: 0.1675 - rmse: 0.2110 - smape: 0.4097 - val_ia: 0.8119 - val_loss: 0.0133 - val_mae: 0.0875 - val_rmse: 0.1085 - val_smape: 0.2571

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.9000 - loss: 0.0424 - mae: 0.1614 - rmse: 0.2037 - smape: 0.4023 - val_ia: 0.8195 - val_loss: 0.0125 - val_mae: 0.0844 - val_rmse: 0.1050 - val_smape: 0.2510

Epoch 14/128

1147/1147 - 5s - 4ms/step - ia: 0.9043 - loss: 0.0390 - mae: 0.1543 - rmse: 0.1953 - smape: 0.3857 - val_ia: 0.8379 - val_loss: 0.0109 - val_mae: 0.0768 - val_rmse: 0.0973 - val_smape: 0.2310

Epoch 15/128

1147/1147 - 5s - 5ms/step - ia: 0.9068 - loss: 0.0370 - mae: 0.1505 - rmse: 0.1900 - smape: 0.3830 - val_ia: 0.8400 - val_loss: 0.0105 - val_mae: 0.0753 - val_rmse: 0.0956 - val_smape: 0.2247

Epoch 16/128

1147/1147 - 4s - 4ms/step - ia: 0.9096 - loss: 0.0348 - mae: 0.1462 - rmse: 0.1843 - smape: 0.3746 - val_ia: 0.8453 - val_loss: 0.0101 - val_mae: 0.0731 - val_rmse: 0.0931 - val_smape: 0.2175

Epoch 17/128

1147/1147 - 5s - 5ms/step - ia: 0.9128 - loss: 0.0323 - mae: 0.1407 - rmse: 0.1776 - smape: 0.3611 - val_ia: 0.8437 - val_loss: 0.0099 - val_mae: 0.0718 - val_rmse: 0.0916 - val_smape: 0.2057

Epoch 18/128

1147/1147 - 5s - 4ms/step - ia: 0.9150 - loss: 0.0309 - mae: 0.1372 - rmse: 0.1737 - smape: 0.3569 - val_ia: 0.8395 - val_loss: 0.0100 - val_mae: 0.0734 - val_rmse: 0.0928 - val_smape: 0.2137

Epoch 19/128

1147/1147 - 6s - 5ms/step - ia: 0.9183 - loss: 0.0286 - mae: 0.1317 - rmse: 0.1671 - smape: 0.3464 - val_ia: 0.8369 - val_loss: 0.0100 - val_mae: 0.0745 - val_rmse: 0.0935 - val_smape: 0.2176

Epoch 20/128

1147/1147 - 5s - 4ms/step - ia: 0.9203 - loss: 0.0273 - mae: 0.1285 - rmse: 0.1631 - smape: 0.3396 - val_ia: 0.8457 - val_loss: 0.0094 - val_mae: 0.0715 - val_rmse: 0.0906 - val_smape: 0.2108

Epoch 21/128

1147/1147 - 5s - 4ms/step - ia: 0.9234 - loss: 0.0254 - mae: 0.1237 - rmse: 0.1571 - smape: 0.3301 - val_ia: 0.8400 - val_loss: 0.0096 - val_mae: 0.0727 - val_rmse: 0.0914 - val_smape: 0.2088

Epoch 22/128

1147/1147 - 3s - 3ms/step - ia: 0.9239 - loss: 0.0249 - mae: 0.1225 - rmse: 0.1558 - smape: 0.3264 - val_ia: 0.8463 - val_loss: 0.0090 - val_mae: 0.0698 - val_rmse: 0.0885 - val_smape: 0.2011

Epoch 23/128

1147/1147 - 7s - 6ms/step - ia: 0.9266 - loss: 0.0233 - mae: 0.1183 - rmse: 0.1504 - smape: 0.3174 - val_ia: 0.8524 - val_loss: 0.0086 - val_mae: 0.0668 - val_rmse: 0.0857 - val_smape: 0.1859

Epoch 24/128

1147/1147 - 5s - 4ms/step - ia: 0.9277 - loss: 0.0227 - mae: 0.1168 - rmse: 0.1487 - smape: 0.3135 - val_ia: 0.8443 - val_loss: 0.0092 - val_mae: 0.0716 - val_rmse: 0.0897 - val_smape: 0.2070

Epoch 25/128

1147/1147 - 4s - 4ms/step - ia: 0.9299 - loss: 0.0215 - mae: 0.1130 - rmse: 0.1444 - smape: 0.3052 - val_ia: 0.8482 - val_loss: 0.0088 - val_mae: 0.0689 - val_rmse: 0.0872 - val_smape: 0.1930

Epoch 26/128

1147/1147 - 5s - 4ms/step - ia: 0.9309 - loss: 0.0208 - mae: 0.1115 - rmse: 0.1421 - smape: 0.2999 - val_ia: 0.8556 - val_loss: 0.0083 - val_mae: 0.0661 - val_rmse: 0.0844 - val_smape: 0.1872

Epoch 27/128

1147/1147 - 6s - 5ms/step - ia: 0.9323 - loss: 0.0201 - mae: 0.1094 - rmse: 0.1395 - smape: 0.2964 - val_ia: 0.8522 - val_loss: 0.0085 - val_mae: 0.0678 - val_rmse: 0.0859 - val_smape: 0.1914

Epoch 28/128

1147/1147 - 5s - 5ms/step - ia: 0.9332 - loss: 0.0195 - mae: 0.1077 - rmse: 0.1375 - smape: 0.2924 - val_ia: 0.8546 - val_loss: 0.0083 - val_mae: 0.0664 - val_rmse: 0.0844 - val_smape: 0.1860

Epoch 29/128

1147/1147 - 5s - 4ms/step - ia: 0.9350 - loss: 0.0187 - mae: 0.1051 - rmse: 0.1347 - smape: 0.2867 - val_ia: 0.8550 - val_loss: 0.0082 - val_mae: 0.0656 - val_rmse: 0.0836 - val_smape: 0.1801

Epoch 30/128

1147/1147 - 5s - 5ms/step - ia: 0.9354 - loss: 0.0184 - mae: 0.1043 - rmse: 0.1334 - smape: 0.2852 - val_ia: 0.8535 - val_loss: 0.0082 - val_mae: 0.0665 - val_rmse: 0.0842 - val_smape: 0.1834

Epoch 31/128

1147/1147 - 8s - 7ms/step - ia: 0.9367 - loss: 0.0178 - mae: 0.1021 - rmse: 0.1313 - smape: 0.2792 - val_ia: 0.8525 - val_loss: 0.0082 - val_mae: 0.0663 - val_rmse: 0.0839 - val_smape: 0.1822

Epoch 32/128

1147/1147 - 2s - 2ms/step - ia: 0.9375 - loss: 0.0174 - mae: 0.1012 - rmse: 0.1297 - smape: 0.2764 - val_ia: 0.8599 - val_loss: 0.0077 - val_mae: 0.0634 - val_rmse: 0.0811 - val_smape: 0.1723

Epoch 33/128

1147/1147 - 2s - 2ms/step - ia: 0.9378 - loss: 0.0171 - mae: 0.1004 - rmse: 0.1286 - smape: 0.2759 - val_ia: 0.8613 - val_loss: 0.0075 - val_mae: 0.0629 - val_rmse: 0.0804 - val_smape: 0.1719

Epoch 34/128

1147/1147 - 2s - 2ms/step - ia: 0.9379 - loss: 0.0170 - mae: 0.1002 - rmse: 0.1284 - smape: 0.2737 - val_ia: 0.8582 - val_loss: 0.0077 - val_mae: 0.0641 - val_rmse: 0.0814 - val_smape: 0.1742

Epoch 35/128

1147/1147 - 2s - 1ms/step - ia: 0.9392 - loss: 0.0165 - mae: 0.0982 - rmse: 0.1262 - smape: 0.2688 - val_ia: 0.8591 - val_loss: 0.0076 - val_mae: 0.0635 - val_rmse: 0.0808 - val_smape: 0.1713

Epoch 36/128

1147/1147 - 3s - 2ms/step - ia: 0.9400 - loss: 0.0161 - mae: 0.0968 - rmse: 0.1245 - smape: 0.2665 - val_ia: 0.8638 - val_loss: 0.0073 - val_mae: 0.0618 - val_rmse: 0.0790 - val_smape: 0.1665

Epoch 37/128

1147/1147 - 1s - 1ms/step - ia: 0.9404 - loss: 0.0159 - mae: 0.0963 - rmse: 0.1239 - smape: 0.2650 - val_ia: 0.8577 - val_loss: 0.0076 - val_mae: 0.0645 - val_rmse: 0.0813 - val_smape: 0.1756

Epoch 38/128

1147/1147 - 2s - 1ms/step - ia: 0.9408 - loss: 0.0157 - mae: 0.0955 - rmse: 0.1231 - smape: 0.2620 - val_ia: 0.8638 - val_loss: 0.0072 - val_mae: 0.0615 - val_rmse: 0.0786 - val_smape: 0.1635

Epoch 39/128

1147/1147 - 2s - 1ms/step - ia: 0.9411 - loss: 0.0155 - mae: 0.0950 - rmse: 0.1222 - smape: 0.2630 - val_ia: 0.8653 - val_loss: 0.0071 - val_mae: 0.0606 - val_rmse: 0.0777 - val_smape: 0.1609

Epoch 40/128

1147/1147 - 1s - 1ms/step - ia: 0.9418 - loss: 0.0152 - mae: 0.0940 - rmse: 0.1210 - smape: 0.2617 - val_ia: 0.8638 - val_loss: 0.0071 - val_mae: 0.0612 - val_rmse: 0.0780 - val_smape: 0.1631

Epoch 41/128

1147/1147 - 2s - 1ms/step - ia: 0.9422 - loss: 0.0151 - mae: 0.0935 - rmse: 0.1206 - smape: 0.2587 - val_ia: 0.8664 - val_loss: 0.0069 - val_mae: 0.0605 - val_rmse: 0.0772 - val_smape: 0.1611

Epoch 42/128

1147/1147 - 2s - 1ms/step - ia: 0.9425 - loss: 0.0149 - mae: 0.0929 - rmse: 0.1197 - smape: 0.2565 - val_ia: 0.8670 - val_loss: 0.0069 - val_mae: 0.0599 - val_rmse: 0.0767 - val_smape: 0.1574

Epoch 43/128

1147/1147 - 2s - 1ms/step - ia: 0.9428 - loss: 0.0147 - mae: 0.0926 - rmse: 0.1190 - smape: 0.2569 - val_ia: 0.8632 - val_loss: 0.0071 - val_mae: 0.0609 - val_rmse: 0.0777 - val_smape: 0.1584

Epoch 44/128

1147/1147 - 1s - 1ms/step - ia: 0.9432 - loss: 0.0146 - mae: 0.0918 - rmse: 0.1182 - smape: 0.2538 - val_ia: 0.8661 - val_loss: 0.0069 - val_mae: 0.0603 - val_rmse: 0.0768 - val_smape: 0.1595

Epoch 45/128

1147/1147 - 2s - 1ms/step - ia: 0.9438 - loss: 0.0144 - mae: 0.0910 - rmse: 0.1177 - smape: 0.2508 - val_ia: 0.8676 - val_loss: 0.0068 - val_mae: 0.0593 - val_rmse: 0.0759 - val_smape: 0.1551

Epoch 46/128

1147/1147 - 3s - 2ms/step - ia: 0.9441 - loss: 0.0140 - mae: 0.0902 - rmse: 0.1163 - smape: 0.2510 - val_ia: 0.8688 - val_loss: 0.0067 - val_mae: 0.0589 - val_rmse: 0.0754 - val_smape: 0.1540

Epoch 47/128

1147/1147 - 2s - 1ms/step - ia: 0.9441 - loss: 0.0141 - mae: 0.0904 - rmse: 0.1166 - smape: 0.2516 - val_ia: 0.8682 - val_loss: 0.0066 - val_mae: 0.0586 - val_rmse: 0.0751 - val_smape: 0.1520

Epoch 48/128

1147/1147 - 2s - 1ms/step - ia: 0.9444 - loss: 0.0140 - mae: 0.0900 - rmse: 0.1160 - smape: 0.2499 - val_ia: 0.8683 - val_loss: 0.0067 - val_mae: 0.0592 - val_rmse: 0.0755 - val_smape: 0.1552

Epoch 49/128

1147/1147 - 2s - 1ms/step - ia: 0.9446 - loss: 0.0139 - mae: 0.0895 - rmse: 0.1157 - smape: 0.2484 - val_ia: 0.8697 - val_loss: 0.0066 - val_mae: 0.0586 - val_rmse: 0.0750 - val_smape: 0.1531

Epoch 50/128

1147/1147 - 4s - 3ms/step - ia: 0.9447 - loss: 0.0139 - mae: 0.0894 - rmse: 0.1153 - smape: 0.2475 - val_ia: 0.8675 - val_loss: 0.0067 - val_mae: 0.0587 - val_rmse: 0.0751 - val_smape: 0.1496

Epoch 51/128

1147/1147 - 6s - 5ms/step - ia: 0.9450 - loss: 0.0136 - mae: 0.0886 - rmse: 0.1143 - smape: 0.2484 - val_ia: 0.8687 - val_loss: 0.0065 - val_mae: 0.0587 - val_rmse: 0.0748 - val_smape: 0.1522

Epoch 52/128

1147/1147 - 5s - 4ms/step - ia: 0.9451 - loss: 0.0136 - mae: 0.0887 - rmse: 0.1145 - smape: 0.2475 - val_ia: 0.8697 - val_loss: 0.0065 - val_mae: 0.0581 - val_rmse: 0.0743 - val_smape: 0.1499

Epoch 53/128

1147/1147 - 5s - 4ms/step - ia: 0.9453 - loss: 0.0136 - mae: 0.0884 - rmse: 0.1142 - smape: 0.2464 - val_ia: 0.8709 - val_loss: 0.0064 - val_mae: 0.0574 - val_rmse: 0.0736 - val_smape: 0.1464

Epoch 54/128

1147/1147 - 6s - 5ms/step - ia: 0.9458 - loss: 0.0135 - mae: 0.0877 - rmse: 0.1136 - smape: 0.2449 - val_ia: 0.8694 - val_loss: 0.0064 - val_mae: 0.0579 - val_rmse: 0.0740 - val_smape: 0.1485

Epoch 55/128

1147/1147 - 6s - 5ms/step - ia: 0.9460 - loss: 0.0132 - mae: 0.0874 - rmse: 0.1129 - smape: 0.2434 - val_ia: 0.8714 - val_loss: 0.0063 - val_mae: 0.0568 - val_rmse: 0.0730 - val_smape: 0.1444

Epoch 56/128

1147/1147 - 6s - 5ms/step - ia: 0.9459 - loss: 0.0133 - mae: 0.0874 - rmse: 0.1128 - smape: 0.2429 - val_ia: 0.8695 - val_loss: 0.0064 - val_mae: 0.0580 - val_rmse: 0.0738 - val_smape: 0.1503

Epoch 57/128

1147/1147 - 5s - 4ms/step - ia: 0.9463 - loss: 0.0131 - mae: 0.0867 - rmse: 0.1122 - smape: 0.2433 - val_ia: 0.8709 - val_loss: 0.0063 - val_mae: 0.0576 - val_rmse: 0.0734 - val_smape: 0.1482

Epoch 58/128

1147/1147 - 4s - 4ms/step - ia: 0.9463 - loss: 0.0131 - mae: 0.0868 - rmse: 0.1120 - smape: 0.2407 - val_ia: 0.8690 - val_loss: 0.0064 - val_mae: 0.0575 - val_rmse: 0.0735 - val_smape: 0.1442

Epoch 59/128

1147/1147 - 5s - 5ms/step - ia: 0.9468 - loss: 0.0130 - mae: 0.0861 - rmse: 0.1115 - smape: 0.2420 - val_ia: 0.8735 - val_loss: 0.0062 - val_mae: 0.0561 - val_rmse: 0.0720 - val_smape: 0.1432

Epoch 60/128

1147/1147 - 5s - 4ms/step - ia: 0.9467 - loss: 0.0129 - mae: 0.0861 - rmse: 0.1114 - smape: 0.2416 - val_ia: 0.8718 - val_loss: 0.0062 - val_mae: 0.0567 - val_rmse: 0.0726 - val_smape: 0.1439

Epoch 61/128

1147/1147 - 4s - 3ms/step - ia: 0.9470 - loss: 0.0128 - mae: 0.0858 - rmse: 0.1108 - smape: 0.2402 - val_ia: 0.8717 - val_loss: 0.0062 - val_mae: 0.0570 - val_rmse: 0.0726 - val_smape: 0.1462

Epoch 62/128

1147/1147 - 3s - 2ms/step - ia: 0.9471 - loss: 0.0128 - mae: 0.0856 - rmse: 0.1107 - smape: 0.2403 - val_ia: 0.8694 - val_loss: 0.0063 - val_mae: 0.0580 - val_rmse: 0.0735 - val_smape: 0.1481

Epoch 63/128

1147/1147 - 3s - 2ms/step - ia: 0.9473 - loss: 0.0127 - mae: 0.0853 - rmse: 0.1104 - smape: 0.2380 - val_ia: 0.8700 - val_loss: 0.0063 - val_mae: 0.0576 - val_rmse: 0.0731 - val_smape: 0.1468

Epoch 64/128

1147/1147 - 3s - 2ms/step - ia: 0.9478 - loss: 0.0126 - mae: 0.0847 - rmse: 0.1096 - smape: 0.2384 - val_ia: 0.8722 - val_loss: 0.0062 - val_mae: 0.0563 - val_rmse: 0.0721 - val_smape: 0.1409

Epoch 65/128

1147/1147 - 2s - 2ms/step - ia: 0.9477 - loss: 0.0126 - mae: 0.0848 - rmse: 0.1100 - smape: 0.2371 - val_ia: 0.8732 - val_loss: 0.0061 - val_mae: 0.0559 - val_rmse: 0.0716 - val_smape: 0.1413

Epoch 66/128

1147/1147 - 3s - 2ms/step - ia: 0.9476 - loss: 0.0125 - mae: 0.0847 - rmse: 0.1097 - smape: 0.2367 - val_ia: 0.8738 - val_loss: 0.0060 - val_mae: 0.0557 - val_rmse: 0.0714 - val_smape: 0.1408

Epoch 67/128

1147/1147 - 3s - 2ms/step - ia: 0.9481 - loss: 0.0123 - mae: 0.0839 - rmse: 0.1086 - smape: 0.2346 - val_ia: 0.8725 - val_loss: 0.0061 - val_mae: 0.0568 - val_rmse: 0.0722 - val_smape: 0.1454

Epoch 68/128

1147/1147 - 3s - 2ms/step - ia: 0.9481 - loss: 0.0124 - mae: 0.0842 - rmse: 0.1089 - smape: 0.2368 - val_ia: 0.8696 - val_loss: 0.0063 - val_mae: 0.0580 - val_rmse: 0.0733 - val_smape: 0.1483

Epoch 69/128

1147/1147 - 3s - 2ms/step - ia: 0.9482 - loss: 0.0123 - mae: 0.0837 - rmse: 0.1082 - smape: 0.2342 - val_ia: 0.8734 - val_loss: 0.0061 - val_mae: 0.0556 - val_rmse: 0.0714 - val_smape: 0.1379

Epoch 70/128

1147/1147 - 2s - 2ms/step - ia: 0.9484 - loss: 0.0122 - mae: 0.0834 - rmse: 0.1080 - smape: 0.2339 - val_ia: 0.8732 - val_loss: 0.0060 - val_mae: 0.0558 - val_rmse: 0.0712 - val_smape: 0.1395

Epoch 71/128

1147/1147 - 4s - 3ms/step - ia: 0.9487 - loss: 0.0122 - mae: 0.0831 - rmse: 0.1078 - smape: 0.2335 - val_ia: 0.8713 - val_loss: 0.0061 - val_mae: 0.0566 - val_rmse: 0.0720 - val_smape: 0.1419

Epoch 72/128

1147/1147 - 5s - 5ms/step - ia: 0.9483 - loss: 0.0122 - mae: 0.0835 - rmse: 0.1079 - smape: 0.2354 - val_ia: 0.8725 - val_loss: 0.0060 - val_mae: 0.0562 - val_rmse: 0.0714 - val_smape: 0.1416

Epoch 73/128

1147/1147 - 5s - 4ms/step - ia: 0.9489 - loss: 0.0120 - mae: 0.0827 - rmse: 0.1071 - smape: 0.2357 - val_ia: 0.8748 - val_loss: 0.0059 - val_mae: 0.0552 - val_rmse: 0.0707 - val_smape: 0.1390

Epoch 74/128

1147/1147 - 5s - 5ms/step - ia: 0.9487 - loss: 0.0122 - mae: 0.0831 - rmse: 0.1078 - smape: 0.2336 - val_ia: 0.8725 - val_loss: 0.0060 - val_mae: 0.0561 - val_rmse: 0.0713 - val_smape: 0.1410

Epoch 75/128

1147/1147 - 5s - 5ms/step - ia: 0.9492 - loss: 0.0118 - mae: 0.0823 - rmse: 0.1065 - smape: 0.2313 - val_ia: 0.8742 - val_loss: 0.0059 - val_mae: 0.0555 - val_rmse: 0.0706 - val_smape: 0.1406

Epoch 76/128

1147/1147 - 5s - 4ms/step - ia: 0.9489 - loss: 0.0120 - mae: 0.0826 - rmse: 0.1070 - smape: 0.2303 - val_ia: 0.8723 - val_loss: 0.0061 - val_mae: 0.0561 - val_rmse: 0.0715 - val_smape: 0.1385

Epoch 77/128

1147/1147 - 5s - 5ms/step - ia: 0.9494 - loss: 0.0118 - mae: 0.0818 - rmse: 0.1061 - smape: 0.2314 - val_ia: 0.8689 - val_loss: 0.0062 - val_mae: 0.0575 - val_rmse: 0.0724 - val_smape: 0.1441

Epoch 78/128

1147/1147 - 5s - 4ms/step - ia: 0.9498 - loss: 0.0116 - mae: 0.0811 - rmse: 0.1052 - smape: 0.2285 - val_ia: 0.8738 - val_loss: 0.0059 - val_mae: 0.0556 - val_rmse: 0.0707 - val_smape: 0.1404

Epoch 79/128

1147/1147 - 5s - 4ms/step - ia: 0.9492 - loss: 0.0118 - mae: 0.0822 - rmse: 0.1064 - smape: 0.2302 - val_ia: 0.8738 - val_loss: 0.0060 - val_mae: 0.0555 - val_rmse: 0.0710 - val_smape: 0.1380

Epoch 80/128

1147/1147 - 5s - 4ms/step - ia: 0.9497 - loss: 0.0118 - mae: 0.0816 - rmse: 0.1060 - smape: 0.2296 - val_ia: 0.8700 - val_loss: 0.0062 - val_mae: 0.0573 - val_rmse: 0.0722 - val_smape: 0.1438

Epoch 81/128

1147/1147 - 5s - 4ms/step - ia: 0.9501 - loss: 0.0116 - mae: 0.0807 - rmse: 0.1051 - smape: 0.2281 - val_ia: 0.8709 - val_loss: 0.0061 - val_mae: 0.0570 - val_rmse: 0.0719 - val_smape: 0.1427

Epoch 82/128

1147/1147 - 4s - 3ms/step - ia: 0.9500 - loss: 0.0115 - mae: 0.0808 - rmse: 0.1049 - smape: 0.2294 - val_ia: 0.8711 - val_loss: 0.0061 - val_mae: 0.0565 - val_rmse: 0.0714 - val_smape: 0.1410

Epoch 83/128

1147/1147 - 3s - 2ms/step - ia: 0.9499 - loss: 0.0116 - mae: 0.0810 - rmse: 0.1051 - smape: 0.2285 - val_ia: 0.8729 - val_loss: 0.0059 - val_mae: 0.0559 - val_rmse: 0.0709 - val_smape: 0.1400

Epoch 84/128

1147/1147 - 5s - 4ms/step - ia: 0.9503 - loss: 0.0115 - mae: 0.0803 - rmse: 0.1046 - smape: 0.2280 - val_ia: 0.8713 - val_loss: 0.0061 - val_mae: 0.0566 - val_rmse: 0.0717 - val_smape: 0.1390

Epoch 85/128

1147/1147 - 3s - 2ms/step - ia: 0.9503 - loss: 0.0114 - mae: 0.0803 - rmse: 0.1045 - smape: 0.2284 - val_ia: 0.8773 - val_loss: 0.0057 - val_mae: 0.0539 - val_rmse: 0.0690 - val_smape: 0.1344

Epoch 86/128

1147/1147 - 3s - 2ms/step - ia: 0.9500 - loss: 0.0116 - mae: 0.0810 - rmse: 0.1051 - smape: 0.2293 - val_ia: 0.8684 - val_loss: 0.0062 - val_mae: 0.0577 - val_rmse: 0.0724 - val_smape: 0.1449

Epoch 87/128

1147/1147 - 3s - 2ms/step - ia: 0.9504 - loss: 0.0113 - mae: 0.0801 - rmse: 0.1039 - smape: 0.2271 - val_ia: 0.8719 - val_loss: 0.0060 - val_mae: 0.0560 - val_rmse: 0.0710 - val_smape: 0.1383

Epoch 88/128

1147/1147 - 2s - 2ms/step - ia: 0.9504 - loss: 0.0114 - mae: 0.0802 - rmse: 0.1042 - smape: 0.2263 - val_ia: 0.8749 - val_loss: 0.0058 - val_mae: 0.0551 - val_rmse: 0.0701 - val_smape: 0.1383

Epoch 89/128

1147/1147 - 2s - 2ms/step - ia: 0.9505 - loss: 0.0113 - mae: 0.0800 - rmse: 0.1040 - smape: 0.2266 - val_ia: 0.8731 - val_loss: 0.0059 - val_mae: 0.0561 - val_rmse: 0.0709 - val_smape: 0.1413

Epoch 90/128

1147/1147 - 3s - 2ms/step - ia: 0.9506 - loss: 0.0113 - mae: 0.0798 - rmse: 0.1037 - smape: 0.2260 - val_ia: 0.8718 - val_loss: 0.0060 - val_mae: 0.0563 - val_rmse: 0.0712 - val_smape: 0.1394

Epoch 91/128

1147/1147 - 3s - 2ms/step - ia: 0.9511 - loss: 0.0111 - mae: 0.0791 - rmse: 0.1029 - smape: 0.2241 - val_ia: 0.8715 - val_loss: 0.0060 - val_mae: 0.0567 - val_rmse: 0.0715 - val_smape: 0.1414

Epoch 92/128

1147/1147 - 2s - 2ms/step - ia: 0.9507 - loss: 0.0112 - mae: 0.0797 - rmse: 0.1033 - smape: 0.2262 - val_ia: 0.8722 - val_loss: 0.0060 - val_mae: 0.0561 - val_rmse: 0.0710 - val_smape: 0.1399

Epoch 93/128

1147/1147 - 3s - 2ms/step - ia: 0.9509 - loss: 0.0112 - mae: 0.0792 - rmse: 0.1033 - smape: 0.2247 - val_ia: 0.8745 - val_loss: 0.0058 - val_mae: 0.0552 - val_rmse: 0.0701 - val_smape: 0.1383

Epoch 94/128

1147/1147 - 5s - 4ms/step - ia: 0.9506 - loss: 0.0112 - mae: 0.0798 - rmse: 0.1035 - smape: 0.2274 - val_ia: 0.8726 - val_loss: 0.0059 - val_mae: 0.0559 - val_rmse: 0.0707 - val_smape: 0.1389

Epoch 95/128

1147/1147 - 5s - 4ms/step - ia: 0.9506 - loss: 0.0112 - mae: 0.0799 - rmse: 0.1035 - smape: 0.2277 - val_ia: 0.8726 - val_loss: 0.0059 - val_mae: 0.0559 - val_rmse: 0.0707 - val_smape: 0.1397

Epoch 96/128

1147/1147 - 4s - 4ms/step - ia: 0.9513 - loss: 0.0110 - mae: 0.0788 - rmse: 0.1024 - smape: 0.2244 - val_ia: 0.8704 - val_loss: 0.0061 - val_mae: 0.0569 - val_rmse: 0.0717 - val_smape: 0.1408

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 18s - 8ms/step - ia: 0.7441 - loss: 0.2654 - mae: 0.3881 - rmse: 0.4810 - smape: 0.7210 - val_ia: 0.5235 - val_loss: 0.0576 - val_mae: 0.1912 - val_rmse: 0.2109 - val_smape: 0.4853

Epoch 2/128

2293/2293 - 10s - 4ms/step - ia: 0.8645 - loss: 0.0738 - mae: 0.2106 - rmse: 0.2647 - smape: 0.4703 - val_ia: 0.5957 - val_loss: 0.0351 - val_mae: 0.1448 - val_rmse: 0.1636 - val_smape: 0.3697

Epoch 3/128

2293/2293 - 10s - 4ms/step - ia: 0.8947 - loss: 0.0459 - mae: 0.1640 - rmse: 0.2090 - smape: 0.3899 - val_ia: 0.6065 - val_loss: 0.0317 - val_mae: 0.1359 - val_rmse: 0.1540 - val_smape: 0.3323

Epoch 4/128

2293/2293 - 9s - 4ms/step - ia: 0.9075 - loss: 0.0356 - mae: 0.1437 - rmse: 0.1836 - smape: 0.3549 - val_ia: 0.6116 - val_loss: 0.0268 - val_mae: 0.1281 - val_rmse: 0.1454 - val_smape: 0.3349

Epoch 5/128

2293/2293 - 10s - 4ms/step - ia: 0.9148 - loss: 0.0304 - mae: 0.1324 - rmse: 0.1696 - smape: 0.3349 - val_ia: 0.6147 - val_loss: 0.0246 - val_mae: 0.1239 - val_rmse: 0.1405 - val_smape: 0.3242

Epoch 6/128

2293/2293 - 9s - 4ms/step - ia: 0.9187 - loss: 0.0277 - mae: 0.1263 - rmse: 0.1618 - smape: 0.3245 - val_ia: 0.6533 - val_loss: 0.0183 - val_mae: 0.1048 - val_rmse: 0.1210 - val_smape: 0.2929

Epoch 7/128

2293/2293 - 13s - 6ms/step - ia: 0.9221 - loss: 0.0258 - mae: 0.1213 - rmse: 0.1558 - smape: 0.3117 - val_ia: 0.6553 - val_loss: 0.0176 - val_mae: 0.1026 - val_rmse: 0.1186 - val_smape: 0.2760

Epoch 8/128

2293/2293 - 20s - 9ms/step - ia: 0.9237 - loss: 0.0248 - mae: 0.1187 - rmse: 0.1528 - smape: 0.3064 - val_ia: 0.6667 - val_loss: 0.0159 - val_mae: 0.0968 - val_rmse: 0.1127 - val_smape: 0.2614

Epoch 9/128

2293/2293 - 7s - 3ms/step - ia: 0.9255 - loss: 0.0234 - mae: 0.1158 - rmse: 0.1487 - smape: 0.3012 - val_ia: 0.6910 - val_loss: 0.0136 - val_mae: 0.0883 - val_rmse: 0.1036 - val_smape: 0.2509

Epoch 10/128

2293/2293 - 7s - 3ms/step - ia: 0.9268 - loss: 0.0228 - mae: 0.1141 - rmse: 0.1465 - smape: 0.2959 - val_ia: 0.7049 - val_loss: 0.0119 - val_mae: 0.0816 - val_rmse: 0.0965 - val_smape: 0.2344

Epoch 11/128

2293/2293 - 6s - 3ms/step - ia: 0.9274 - loss: 0.0224 - mae: 0.1130 - rmse: 0.1453 - smape: 0.2931 - val_ia: 0.7138 - val_loss: 0.0111 - val_mae: 0.0789 - val_rmse: 0.0935 - val_smape: 0.2298

Epoch 12/128

2293/2293 - 13s - 6ms/step - ia: 0.9290 - loss: 0.0215 - mae: 0.1107 - rmse: 0.1422 - smape: 0.2881 - val_ia: 0.7109 - val_loss: 0.0116 - val_mae: 0.0798 - val_rmse: 0.0949 - val_smape: 0.2185

Epoch 13/128

2293/2293 - 11s - 5ms/step - ia: 0.9293 - loss: 0.0214 - mae: 0.1101 - rmse: 0.1421 - smape: 0.2854 - val_ia: 0.7067 - val_loss: 0.0112 - val_mae: 0.0797 - val_rmse: 0.0940 - val_smape: 0.2201

Epoch 14/128

2293/2293 - 10s - 4ms/step - ia: 0.9303 - loss: 0.0208 - mae: 0.1088 - rmse: 0.1399 - smape: 0.2824 - val_ia: 0.7308 - val_loss: 0.0098 - val_mae: 0.0730 - val_rmse: 0.0872 - val_smape: 0.2097

Epoch 15/128

2293/2293 - 10s - 4ms/step - ia: 0.9307 - loss: 0.0204 - mae: 0.1080 - rmse: 0.1387 - smape: 0.2801 - val_ia: 0.7218 - val_loss: 0.0102 - val_mae: 0.0753 - val_rmse: 0.0895 - val_smape: 0.2072

Epoch 16/128

2293/2293 - 10s - 4ms/step - ia: 0.9314 - loss: 0.0203 - mae: 0.1072 - rmse: 0.1380 - smape: 0.2774 - val_ia: 0.7343 - val_loss: 0.0095 - val_mae: 0.0714 - val_rmse: 0.0857 - val_smape: 0.1977

Epoch 17/128

2293/2293 - 10s - 5ms/step - ia: 0.9325 - loss: 0.0196 - mae: 0.1052 - rmse: 0.1356 - smape: 0.2720 - val_ia: 0.7387 - val_loss: 0.0089 - val_mae: 0.0695 - val_rmse: 0.0834 - val_smape: 0.1950

Epoch 18/128

2293/2293 - 10s - 4ms/step - ia: 0.9330 - loss: 0.0193 - mae: 0.1044 - rmse: 0.1346 - smape: 0.2711 - val_ia: 0.7633 - val_loss: 0.0081 - val_mae: 0.0634 - val_rmse: 0.0776 - val_smape: 0.1752

Epoch 19/128

2293/2293 - 10s - 4ms/step - ia: 0.9334 - loss: 0.0192 - mae: 0.1039 - rmse: 0.1341 - smape: 0.2688 - val_ia: 0.7721 - val_loss: 0.0072 - val_mae: 0.0592 - val_rmse: 0.0730 - val_smape: 0.1668

Epoch 20/128

2293/2293 - 10s - 4ms/step - ia: 0.9338 - loss: 0.0189 - mae: 0.1033 - rmse: 0.1331 - smape: 0.2667 - val_ia: 0.7472 - val_loss: 0.0085 - val_mae: 0.0676 - val_rmse: 0.0813 - val_smape: 0.1886

Epoch 21/128

2293/2293 - 10s - 4ms/step - ia: 0.9338 - loss: 0.0187 - mae: 0.1031 - rmse: 0.1326 - smape: 0.2649 - val_ia: 0.7549 - val_loss: 0.0081 - val_mae: 0.0649 - val_rmse: 0.0786 - val_smape: 0.1773

Epoch 22/128

2293/2293 - 10s - 4ms/step - ia: 0.9346 - loss: 0.0185 - mae: 0.1021 - rmse: 0.1316 - smape: 0.2632 - val_ia: 0.7507 - val_loss: 0.0079 - val_mae: 0.0647 - val_rmse: 0.0782 - val_smape: 0.1729

Epoch 23/128

2293/2293 - 10s - 4ms/step - ia: 0.9351 - loss: 0.0182 - mae: 0.1012 - rmse: 0.1308 - smape: 0.2599 - val_ia: 0.7838 - val_loss: 0.0065 - val_mae: 0.0563 - val_rmse: 0.0698 - val_smape: 0.1694

Epoch 24/128

2293/2293 - 9s - 4ms/step - ia: 0.9353 - loss: 0.0182 - mae: 0.1012 - rmse: 0.1305 - smape: 0.2608 - val_ia: 0.7618 - val_loss: 0.0072 - val_mae: 0.0612 - val_rmse: 0.0746 - val_smape: 0.1682

Epoch 25/128

2293/2293 - 9s - 4ms/step - ia: 0.9357 - loss: 0.0180 - mae: 0.1005 - rmse: 0.1299 - smape: 0.2595 - val_ia: 0.7753 - val_loss: 0.0066 - val_mae: 0.0581 - val_rmse: 0.0715 - val_smape: 0.1692

Epoch 26/128

2293/2293 - 9s - 4ms/step - ia: 0.9359 - loss: 0.0179 - mae: 0.1002 - rmse: 0.1295 - smape: 0.2586 - val_ia: 0.7484 - val_loss: 0.0077 - val_mae: 0.0647 - val_rmse: 0.0778 - val_smape: 0.1762

Epoch 27/128

2293/2293 - 10s - 4ms/step - ia: 0.9366 - loss: 0.0175 - mae: 0.0990 - rmse: 0.1280 - smape: 0.2554 - val_ia: 0.7636 - val_loss: 0.0070 - val_mae: 0.0608 - val_rmse: 0.0740 - val_smape: 0.1712

Epoch 28/128

2293/2293 - 10s - 4ms/step - ia: 0.9366 - loss: 0.0176 - mae: 0.0991 - rmse: 0.1283 - smape: 0.2545 - val_ia: 0.7954 - val_loss: 0.0060 - val_mae: 0.0544 - val_rmse: 0.0674 - val_smape: 0.1667

Epoch 29/128

2293/2293 - 11s - 5ms/step - ia: 0.9370 - loss: 0.0174 - mae: 0.0983 - rmse: 0.1272 - smape: 0.2536 - val_ia: 0.7844 - val_loss: 0.0061 - val_mae: 0.0553 - val_rmse: 0.0684 - val_smape: 0.1675

Epoch 30/128

2293/2293 - 9s - 4ms/step - ia: 0.9371 - loss: 0.0172 - mae: 0.0981 - rmse: 0.1272 - smape: 0.2528 - val_ia: 0.7618 - val_loss: 0.0070 - val_mae: 0.0614 - val_rmse: 0.0743 - val_smape: 0.1751

Epoch 31/128

2293/2293 - 11s - 5ms/step - ia: 0.9376 - loss: 0.0171 - mae: 0.0976 - rmse: 0.1264 - smape: 0.2517 - val_ia: 0.7595 - val_loss: 0.0069 - val_mae: 0.0614 - val_rmse: 0.0741 - val_smape: 0.1786

Epoch 32/128

2293/2293 - 11s - 5ms/step - ia: 0.9384 - loss: 0.0167 - mae: 0.0965 - rmse: 0.1250 - smape: 0.2485 - val_ia: 0.7562 - val_loss: 0.0070 - val_mae: 0.0617 - val_rmse: 0.0746 - val_smape: 0.1709

Epoch 33/128

2293/2293 - 11s - 5ms/step - ia: 0.9381 - loss: 0.0169 - mae: 0.0968 - rmse: 0.1257 - smape: 0.2508 - val_ia: 0.7596 - val_loss: 0.0071 - val_mae: 0.0617 - val_rmse: 0.0744 - val_smape: 0.1727

Epoch 34/128

2293/2293 - 11s - 5ms/step - ia: 0.9382 - loss: 0.0168 - mae: 0.0968 - rmse: 0.1254 - smape: 0.2475 - val_ia: 0.7538 - val_loss: 0.0073 - val_mae: 0.0634 - val_rmse: 0.0758 - val_smape: 0.1827

Epoch 35/128

2293/2293 - 17s - 7ms/step - ia: 0.9383 - loss: 0.0169 - mae: 0.0966 - rmse: 0.1255 - smape: 0.2492 - val_ia: 0.7633 - val_loss: 0.0068 - val_mae: 0.0606 - val_rmse: 0.0733 - val_smape: 0.1684

Epoch 36/128

2293/2293 - 7s - 3ms/step - ia: 0.9387 - loss: 0.0165 - mae: 0.0959 - rmse: 0.1245 - smape: 0.2470 - val_ia: 0.7553 - val_loss: 0.0071 - val_mae: 0.0627 - val_rmse: 0.0751 - val_smape: 0.1738

Epoch 37/128

2293/2293 - 8s - 3ms/step - ia: 0.9389 - loss: 0.0164 - mae: 0.0955 - rmse: 0.1238 - smape: 0.2457 - val_ia: 0.7513 - val_loss: 0.0073 - val_mae: 0.0639 - val_rmse: 0.0762 - val_smape: 0.1790

Epoch 38/128

2293/2293 - 7s - 3ms/step - ia: 0.9391 - loss: 0.0163 - mae: 0.0952 - rmse: 0.1233 - smape: 0.2457 - val_ia: 0.7928 - val_loss: 0.0058 - val_mae: 0.0539 - val_rmse: 0.0666 - val_smape: 0.1619

Epoch 39/128

2293/2293 - 7s - 3ms/step - ia: 0.9392 - loss: 0.0163 - mae: 0.0952 - rmse: 0.1233 - smape: 0.2429 - val_ia: 0.7963 - val_loss: 0.0058 - val_mae: 0.0536 - val_rmse: 0.0662 - val_smape: 0.1628

Epoch 40/128

2293/2293 - 12s - 5ms/step - ia: 0.9397 - loss: 0.0161 - mae: 0.0944 - rmse: 0.1224 - smape: 0.2434 - val_ia: 0.7699 - val_loss: 0.0063 - val_mae: 0.0585 - val_rmse: 0.0710 - val_smape: 0.1797

Epoch 41/128

2293/2293 - 11s - 5ms/step - ia: 0.9396 - loss: 0.0160 - mae: 0.0946 - rmse: 0.1223 - smape: 0.2440 - val_ia: 0.7516 - val_loss: 0.0070 - val_mae: 0.0634 - val_rmse: 0.0756 - val_smape: 0.1803

Epoch 42/128

2293/2293 - 8s - 4ms/step - ia: 0.9397 - loss: 0.0160 - mae: 0.0943 - rmse: 0.1221 - smape: 0.2422 - val_ia: 0.8020 - val_loss: 0.0052 - val_mae: 0.0505 - val_rmse: 0.0630 - val_smape: 0.1588

Epoch 43/128

2293/2293 - 9s - 4ms/step - ia: 0.9397 - loss: 0.0160 - mae: 0.0942 - rmse: 0.1222 - smape: 0.2413 - val_ia: 0.8067 - val_loss: 0.0052 - val_mae: 0.0503 - val_rmse: 0.0627 - val_smape: 0.1548

Epoch 44/128

2293/2293 - 7s - 3ms/step - ia: 0.9401 - loss: 0.0160 - mae: 0.0938 - rmse: 0.1219 - smape: 0.2389 - val_ia: 0.7889 - val_loss: 0.0057 - val_mae: 0.0543 - val_rmse: 0.0668 - val_smape: 0.1619

Epoch 45/128

2293/2293 - 12s - 5ms/step - ia: 0.9406 - loss: 0.0158 - mae: 0.0932 - rmse: 0.1212 - smape: 0.2399 - val_ia: 0.7852 - val_loss: 0.0057 - val_mae: 0.0545 - val_rmse: 0.0669 - val_smape: 0.1637

Epoch 46/128

2293/2293 - 8s - 4ms/step - ia: 0.9409 - loss: 0.0155 - mae: 0.0928 - rmse: 0.1203 - smape: 0.2398 - val_ia: 0.7819 - val_loss: 0.0058 - val_mae: 0.0549 - val_rmse: 0.0673 - val_smape: 0.1607

Epoch 47/128

2293/2293 - 8s - 4ms/step - ia: 0.9405 - loss: 0.0157 - mae: 0.0931 - rmse: 0.1208 - smape: 0.2393 - val_ia: 0.7989 - val_loss: 0.0052 - val_mae: 0.0508 - val_rmse: 0.0631 - val_smape: 0.1560

Epoch 48/128

2293/2293 - 14s - 6ms/step - ia: 0.9408 - loss: 0.0156 - mae: 0.0927 - rmse: 0.1204 - smape: 0.2387 - val_ia: 0.8089 - val_loss: 0.0050 - val_mae: 0.0495 - val_rmse: 0.0618 - val_smape: 0.1528

Epoch 49/128

2293/2293 - 8s - 3ms/step - ia: 0.9405 - loss: 0.0157 - mae: 0.0930 - rmse: 0.1210 - smape: 0.2381 - val_ia: 0.7800 - val_loss: 0.0058 - val_mae: 0.0556 - val_rmse: 0.0678 - val_smape: 0.1734

Epoch 50/128

2293/2293 - 7s - 3ms/step - ia: 0.9412 - loss: 0.0153 - mae: 0.0920 - rmse: 0.1194 - smape: 0.2366 - val_ia: 0.7814 - val_loss: 0.0058 - val_mae: 0.0558 - val_rmse: 0.0679 - val_smape: 0.1649

Epoch 51/128

2293/2293 - 8s - 4ms/step - ia: 0.9414 - loss: 0.0153 - mae: 0.0919 - rmse: 0.1193 - smape: 0.2349 - val_ia: 0.7793 - val_loss: 0.0057 - val_mae: 0.0552 - val_rmse: 0.0674 - val_smape: 0.1657

Epoch 52/128

2293/2293 - 8s - 4ms/step - ia: 0.9411 - loss: 0.0154 - mae: 0.0923 - rmse: 0.1201 - smape: 0.2368 - val_ia: 0.7617 - val_loss: 0.0066 - val_mae: 0.0609 - val_rmse: 0.0727 - val_smape: 0.1732

Epoch 53/128

2293/2293 - 7s - 3ms/step - ia: 0.9416 - loss: 0.0152 - mae: 0.0915 - rmse: 0.1187 - smape: 0.2348 - val_ia: 0.7919 - val_loss: 0.0053 - val_mae: 0.0522 - val_rmse: 0.0644 - val_smape: 0.1536

Epoch 54/128

2293/2293 - 9s - 4ms/step - ia: 0.9417 - loss: 0.0151 - mae: 0.0913 - rmse: 0.1188 - smape: 0.2329 - val_ia: 0.7830 - val_loss: 0.0057 - val_mae: 0.0549 - val_rmse: 0.0671 - val_smape: 0.1654

Epoch 55/128

2293/2293 - 8s - 3ms/step - ia: 0.9421 - loss: 0.0150 - mae: 0.0907 - rmse: 0.1181 - smape: 0.2329 - val_ia: 0.7826 - val_loss: 0.0057 - val_mae: 0.0549 - val_rmse: 0.0670 - val_smape: 0.1646

Epoch 56/128

2293/2293 - 8s - 4ms/step - ia: 0.9422 - loss: 0.0150 - mae: 0.0907 - rmse: 0.1180 - smape: 0.2328 - val_ia: 0.7912 - val_loss: 0.0053 - val_mae: 0.0526 - val_rmse: 0.0645 - val_smape: 0.1581

Epoch 57/128

2293/2293 - 8s - 4ms/step - ia: 0.9419 - loss: 0.0150 - mae: 0.0910 - rmse: 0.1180 - smape: 0.2328 - val_ia: 0.7502 - val_loss: 0.0072 - val_mae: 0.0641 - val_rmse: 0.0758 - val_smape: 0.1748

Epoch 58/128

2293/2293 - 8s - 4ms/step - ia: 0.9414 - loss: 0.0153 - mae: 0.0918 - rmse: 0.1194 - smape: 0.2351 - val_ia: 0.8208 - val_loss: 0.0044 - val_mae: 0.0453 - val_rmse: 0.0576 - val_smape: 0.1443

Epoch 59/128

2293/2293 - 9s - 4ms/step - ia: 0.9421 - loss: 0.0150 - mae: 0.0908 - rmse: 0.1182 - smape: 0.2310 - val_ia: 0.7840 - val_loss: 0.0056 - val_mae: 0.0548 - val_rmse: 0.0668 - val_smape: 0.1611

Epoch 60/128

2293/2293 - 8s - 4ms/step - ia: 0.9419 - loss: 0.0147 - mae: 0.0906 - rmse: 0.1173 - smape: 0.2329 - val_ia: 0.7785 - val_loss: 0.0057 - val_mae: 0.0561 - val_rmse: 0.0678 - val_smape: 0.1756

Epoch 61/128

2293/2293 - 7s - 3ms/step - ia: 0.9425 - loss: 0.0147 - mae: 0.0901 - rmse: 0.1172 - smape: 0.2300 - val_ia: 0.7800 - val_loss: 0.0057 - val_mae: 0.0556 - val_rmse: 0.0675 - val_smape: 0.1683

Epoch 62/128

2293/2293 - 6s - 3ms/step - ia: 0.9424 - loss: 0.0147 - mae: 0.0901 - rmse: 0.1173 - smape: 0.2298 - val_ia: 0.8193 - val_loss: 0.0044 - val_mae: 0.0464 - val_rmse: 0.0584 - val_smape: 0.1469

Epoch 63/128

2293/2293 - 11s - 5ms/step - ia: 0.9423 - loss: 0.0148 - mae: 0.0906 - rmse: 0.1173 - smape: 0.2323 - val_ia: 0.8012 - val_loss: 0.0048 - val_mae: 0.0497 - val_rmse: 0.0616 - val_smape: 0.1609

Epoch 64/128

2293/2293 - 9s - 4ms/step - ia: 0.9423 - loss: 0.0149 - mae: 0.0904 - rmse: 0.1177 - smape: 0.2295 - val_ia: 0.7707 - val_loss: 0.0059 - val_mae: 0.0571 - val_rmse: 0.0690 - val_smape: 0.1613

Epoch 65/128

2293/2293 - 6s - 3ms/step - ia: 0.9425 - loss: 0.0149 - mae: 0.0900 - rmse: 0.1178 - smape: 0.2307 - val_ia: 0.7804 - val_loss: 0.0054 - val_mae: 0.0541 - val_rmse: 0.0659 - val_smape: 0.1650

Epoch 66/128

2293/2293 - 6s - 3ms/step - ia: 0.9427 - loss: 0.0148 - mae: 0.0899 - rmse: 0.1171 - smape: 0.2303 - val_ia: 0.7831 - val_loss: 0.0054 - val_mae: 0.0538 - val_rmse: 0.0658 - val_smape: 0.1604

Epoch 67/128

2293/2293 - 10s - 4ms/step - ia: 0.9424 - loss: 0.0147 - mae: 0.0899 - rmse: 0.1171 - smape: 0.2324 - val_ia: 0.7885 - val_loss: 0.0052 - val_mae: 0.0527 - val_rmse: 0.0645 - val_smape: 0.1622

Epoch 68/128

2293/2293 - 6s - 3ms/step - ia: 0.9425 - loss: 0.0147 - mae: 0.0899 - rmse: 0.1170 - smape: 0.2295 - val_ia: 0.8077 - val_loss: 0.0046 - val_mae: 0.0483 - val_rmse: 0.0604 - val_smape: 0.1541

Epoch 69/128

2293/2293 - 8s - 4ms/step - ia: 0.9429 - loss: 0.0145 - mae: 0.0896 - rmse: 0.1162 - smape: 0.2273 - val_ia: 0.7917 - val_loss: 0.0054 - val_mae: 0.0536 - val_rmse: 0.0654 - val_smape: 0.1619

Epoch 70/128

2293/2293 - 9s - 4ms/step - ia: 0.9429 - loss: 0.0146 - mae: 0.0894 - rmse: 0.1165 - smape: 0.2285 - val_ia: 0.7703 - val_loss: 0.0060 - val_mae: 0.0575 - val_rmse: 0.0693 - val_smape: 0.1633

Epoch 71/128

2293/2293 - 10s - 4ms/step - ia: 0.9429 - loss: 0.0145 - mae: 0.0893 - rmse: 0.1162 - smape: 0.2291 - val_ia: 0.7804 - val_loss: 0.0055 - val_mae: 0.0547 - val_rmse: 0.0665 - val_smape: 0.1601

Epoch 72/128

2293/2293 - 9s - 4ms/step - ia: 0.9433 - loss: 0.0145 - mae: 0.0890 - rmse: 0.1161 - smape: 0.2264 - val_ia: 0.8066 - val_loss: 0.0045 - val_mae: 0.0475 - val_rmse: 0.0594 - val_smape: 0.1434

Epoch 73/128

2293/2293 - 8s - 3ms/step - ia: 0.9429 - loss: 0.0147 - mae: 0.0896 - rmse: 0.1167 - smape: 0.2272 - val_ia: 0.7905 - val_loss: 0.0050 - val_mae: 0.0513 - val_rmse: 0.0631 - val_smape: 0.1493

Epoch 73: early stopping

Restoring model weights from the end of the best epoch: 58.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 39s 244ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 52%|█████▏    | 26/50 [2:07:22<3:43:57, 559.88s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 7s - 6ms/step - ia: 0.8280 - loss: 0.1388 - mae: 0.2795 - rmse: 0.3489 - smape: 0.5765 - val_ia: 0.8164 - val_loss: 0.0160 - val_mae: 0.0897 - val_rmse: 0.1139 - val_smape: 0.2452

Epoch 2/128

1147/1147 - 2s - 2ms/step - ia: 0.9016 - loss: 0.0413 - mae: 0.1584 - rmse: 0.2002 - smape: 0.3881 - val_ia: 0.8156 - val_loss: 0.0143 - val_mae: 0.0891 - val_rmse: 0.1103 - val_smape: 0.2391

Epoch 3/128

1147/1147 - 2s - 2ms/step - ia: 0.9207 - loss: 0.0273 - mae: 0.1280 - rmse: 0.1628 - smape: 0.3224 - val_ia: 0.8394 - val_loss: 0.0115 - val_mae: 0.0757 - val_rmse: 0.0961 - val_smape: 0.1854

Epoch 4/128

1147/1147 - 3s - 2ms/step - ia: 0.9270 - loss: 0.0235 - mae: 0.1181 - rmse: 0.1508 - smape: 0.3009 - val_ia: 0.8356 - val_loss: 0.0108 - val_mae: 0.0766 - val_rmse: 0.0951 - val_smape: 0.1859

Epoch 5/128

1147/1147 - 2s - 2ms/step - ia: 0.9307 - loss: 0.0214 - mae: 0.1121 - rmse: 0.1439 - smape: 0.2893 - val_ia: 0.8474 - val_loss: 0.0093 - val_mae: 0.0706 - val_rmse: 0.0884 - val_smape: 0.1763

Epoch 6/128

1147/1147 - 3s - 2ms/step - ia: 0.9335 - loss: 0.0198 - mae: 0.1076 - rmse: 0.1382 - smape: 0.2793 - val_ia: 0.8531 - val_loss: 0.0085 - val_mae: 0.0678 - val_rmse: 0.0848 - val_smape: 0.1693

Epoch 7/128

1147/1147 - 3s - 2ms/step - ia: 0.9360 - loss: 0.0183 - mae: 0.1036 - rmse: 0.1332 - smape: 0.2704 - val_ia: 0.8388 - val_loss: 0.0098 - val_mae: 0.0747 - val_rmse: 0.0903 - val_smape: 0.1901

Epoch 8/128

1147/1147 - 3s - 2ms/step - ia: 0.9381 - loss: 0.0175 - mae: 0.1002 - rmse: 0.1297 - smape: 0.2620 - val_ia: 0.8440 - val_loss: 0.0096 - val_mae: 0.0714 - val_rmse: 0.0884 - val_smape: 0.1633

Epoch 9/128

1147/1147 - 3s - 2ms/step - ia: 0.9403 - loss: 0.0163 - mae: 0.0965 - rmse: 0.1252 - smape: 0.2550 - val_ia: 0.8360 - val_loss: 0.0101 - val_mae: 0.0743 - val_rmse: 0.0908 - val_smape: 0.1600

Epoch 10/128

1147/1147 - 2s - 2ms/step - ia: 0.9418 - loss: 0.0156 - mae: 0.0941 - rmse: 0.1224 - smape: 0.2504 - val_ia: 0.8535 - val_loss: 0.0075 - val_mae: 0.0653 - val_rmse: 0.0799 - val_smape: 0.1676

Epoch 11/128

1147/1147 - 2s - 2ms/step - ia: 0.9437 - loss: 0.0145 - mae: 0.0909 - rmse: 0.1180 - smape: 0.2433 - val_ia: 0.8408 - val_loss: 0.0091 - val_mae: 0.0712 - val_rmse: 0.0867 - val_smape: 0.1587

Epoch 12/128

1147/1147 - 4s - 3ms/step - ia: 0.9450 - loss: 0.0139 - mae: 0.0889 - rmse: 0.1156 - smape: 0.2389 - val_ia: 0.8354 - val_loss: 0.0087 - val_mae: 0.0723 - val_rmse: 0.0858 - val_smape: 0.1855

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.9457 - loss: 0.0136 - mae: 0.0877 - rmse: 0.1141 - smape: 0.2357 - val_ia: 0.8721 - val_loss: 0.0059 - val_mae: 0.0564 - val_rmse: 0.0710 - val_smape: 0.1410

Epoch 14/128

1147/1147 - 5s - 5ms/step - ia: 0.9474 - loss: 0.0129 - mae: 0.0849 - rmse: 0.1110 - smape: 0.2278 - val_ia: 0.8671 - val_loss: 0.0064 - val_mae: 0.0586 - val_rmse: 0.0732 - val_smape: 0.1457

Epoch 15/128

1147/1147 - 4s - 3ms/step - ia: 0.9484 - loss: 0.0124 - mae: 0.0835 - rmse: 0.1088 - smape: 0.2254 - val_ia: 0.8689 - val_loss: 0.0056 - val_mae: 0.0557 - val_rmse: 0.0694 - val_smape: 0.1450

Epoch 16/128

1147/1147 - 5s - 4ms/step - ia: 0.9494 - loss: 0.0120 - mae: 0.0817 - rmse: 0.1071 - smape: 0.2186 - val_ia: 0.8710 - val_loss: 0.0055 - val_mae: 0.0543 - val_rmse: 0.0683 - val_smape: 0.1389

Epoch 17/128

1147/1147 - 5s - 4ms/step - ia: 0.9509 - loss: 0.0114 - mae: 0.0792 - rmse: 0.1042 - smape: 0.2164 - val_ia: 0.8859 - val_loss: 0.0046 - val_mae: 0.0489 - val_rmse: 0.0627 - val_smape: 0.1337

Epoch 18/128

1147/1147 - 5s - 5ms/step - ia: 0.9517 - loss: 0.0111 - mae: 0.0780 - rmse: 0.1025 - smape: 0.2137 - val_ia: 0.8647 - val_loss: 0.0056 - val_mae: 0.0566 - val_rmse: 0.0699 - val_smape: 0.1490

Epoch 19/128

1147/1147 - 5s - 4ms/step - ia: 0.9525 - loss: 0.0107 - mae: 0.0767 - rmse: 0.1009 - smape: 0.2085 - val_ia: 0.8869 - val_loss: 0.0045 - val_mae: 0.0489 - val_rmse: 0.0626 - val_smape: 0.1383

Epoch 20/128

1147/1147 - 6s - 5ms/step - ia: 0.9535 - loss: 0.0104 - mae: 0.0751 - rmse: 0.0991 - smape: 0.2062 - val_ia: 0.8853 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0612 - val_smape: 0.1388

Epoch 21/128

1147/1147 - 7s - 6ms/step - ia: 0.9536 - loss: 0.0102 - mae: 0.0748 - rmse: 0.0987 - smape: 0.2019 - val_ia: 0.8738 - val_loss: 0.0053 - val_mae: 0.0538 - val_rmse: 0.0666 - val_smape: 0.1557

Epoch 22/128

1147/1147 - 5s - 4ms/step - ia: 0.9543 - loss: 0.0101 - mae: 0.0739 - rmse: 0.0978 - smape: 0.2014 - val_ia: 0.8801 - val_loss: 0.0046 - val_mae: 0.0503 - val_rmse: 0.0632 - val_smape: 0.1486

Epoch 23/128

1147/1147 - 5s - 5ms/step - ia: 0.9547 - loss: 0.0099 - mae: 0.0731 - rmse: 0.0970 - smape: 0.2005 - val_ia: 0.9014 - val_loss: 0.0038 - val_mae: 0.0427 - val_rmse: 0.0567 - val_smape: 0.1235

Epoch 24/128

1147/1147 - 4s - 4ms/step - ia: 0.9553 - loss: 0.0096 - mae: 0.0720 - rmse: 0.0955 - smape: 0.1971 - val_ia: 0.8703 - val_loss: 0.0051 - val_mae: 0.0533 - val_rmse: 0.0669 - val_smape: 0.1361

Epoch 25/128

1147/1147 - 5s - 4ms/step - ia: 0.9554 - loss: 0.0096 - mae: 0.0718 - rmse: 0.0952 - smape: 0.1936 - val_ia: 0.9028 - val_loss: 0.0036 - val_mae: 0.0419 - val_rmse: 0.0553 - val_smape: 0.1298

Epoch 26/128

1147/1147 - 4s - 4ms/step - ia: 0.9559 - loss: 0.0094 - mae: 0.0710 - rmse: 0.0943 - smape: 0.1937 - val_ia: 0.8664 - val_loss: 0.0050 - val_mae: 0.0545 - val_rmse: 0.0669 - val_smape: 0.1519

Epoch 27/128

1147/1147 - 4s - 3ms/step - ia: 0.9565 - loss: 0.0092 - mae: 0.0701 - rmse: 0.0931 - smape: 0.1916 - val_ia: 0.8864 - val_loss: 0.0042 - val_mae: 0.0481 - val_rmse: 0.0611 - val_smape: 0.1474

Epoch 28/128

1147/1147 - 5s - 4ms/step - ia: 0.9565 - loss: 0.0092 - mae: 0.0703 - rmse: 0.0934 - smape: 0.1917 - val_ia: 0.9091 - val_loss: 0.0032 - val_mae: 0.0389 - val_rmse: 0.0522 - val_smape: 0.1249

Epoch 29/128

1147/1147 - 4s - 3ms/step - ia: 0.9568 - loss: 0.0091 - mae: 0.0697 - rmse: 0.0929 - smape: 0.1908 - val_ia: 0.9071 - val_loss: 0.0035 - val_mae: 0.0408 - val_rmse: 0.0545 - val_smape: 0.1279

Epoch 30/128

1147/1147 - 6s - 5ms/step - ia: 0.9566 - loss: 0.0092 - mae: 0.0700 - rmse: 0.0934 - smape: 0.1898 - val_ia: 0.8966 - val_loss: 0.0039 - val_mae: 0.0447 - val_rmse: 0.0579 - val_smape: 0.1483

Epoch 31/128

1147/1147 - 4s - 3ms/step - ia: 0.9568 - loss: 0.0092 - mae: 0.0697 - rmse: 0.0932 - smape: 0.1889 - val_ia: 0.9067 - val_loss: 0.0034 - val_mae: 0.0410 - val_rmse: 0.0542 - val_smape: 0.1309

Epoch 32/128

1147/1147 - 5s - 5ms/step - ia: 0.9570 - loss: 0.0091 - mae: 0.0692 - rmse: 0.0925 - smape: 0.1881 - val_ia: 0.8921 - val_loss: 0.0038 - val_mae: 0.0448 - val_rmse: 0.0578 - val_smape: 0.1375

Epoch 33/128

1147/1147 - 3s - 2ms/step - ia: 0.9574 - loss: 0.0089 - mae: 0.0686 - rmse: 0.0915 - smape: 0.1870 - val_ia: 0.9033 - val_loss: 0.0034 - val_mae: 0.0406 - val_rmse: 0.0537 - val_smape: 0.1352

Epoch 34/128

1147/1147 - 6s - 5ms/step - ia: 0.9576 - loss: 0.0088 - mae: 0.0683 - rmse: 0.0913 - smape: 0.1853 - val_ia: 0.9069 - val_loss: 0.0034 - val_mae: 0.0405 - val_rmse: 0.0539 - val_smape: 0.1265

Epoch 35/128

1147/1147 - 4s - 4ms/step - ia: 0.9575 - loss: 0.0088 - mae: 0.0684 - rmse: 0.0910 - smape: 0.1853 - val_ia: 0.8866 - val_loss: 0.0040 - val_mae: 0.0461 - val_rmse: 0.0590 - val_smape: 0.1458

Epoch 36/128

1147/1147 - 3s - 2ms/step - ia: 0.9573 - loss: 0.0090 - mae: 0.0687 - rmse: 0.0919 - smape: 0.1856 - val_ia: 0.8923 - val_loss: 0.0037 - val_mae: 0.0443 - val_rmse: 0.0570 - val_smape: 0.1387

Epoch 37/128

1147/1147 - 3s - 3ms/step - ia: 0.9577 - loss: 0.0088 - mae: 0.0682 - rmse: 0.0911 - smape: 0.1857 - val_ia: 0.9070 - val_loss: 0.0033 - val_mae: 0.0398 - val_rmse: 0.0532 - val_smape: 0.1297

Epoch 38/128

1147/1147 - 6s - 6ms/step - ia: 0.9583 - loss: 0.0086 - mae: 0.0673 - rmse: 0.0899 - smape: 0.1835 - val_ia: 0.9034 - val_loss: 0.0033 - val_mae: 0.0402 - val_rmse: 0.0535 - val_smape: 0.1260

Epoch 39/128

1147/1147 - 5s - 4ms/step - ia: 0.9583 - loss: 0.0087 - mae: 0.0672 - rmse: 0.0902 - smape: 0.1817 - val_ia: 0.9059 - val_loss: 0.0033 - val_mae: 0.0401 - val_rmse: 0.0530 - val_smape: 0.1321

Epoch 40/128

1147/1147 - 5s - 5ms/step - ia: 0.9580 - loss: 0.0087 - mae: 0.0677 - rmse: 0.0905 - smape: 0.1816 - val_ia: 0.9045 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0537 - val_smape: 0.1290

Epoch 41/128

1147/1147 - 3s - 3ms/step - ia: 0.9583 - loss: 0.0086 - mae: 0.0672 - rmse: 0.0899 - smape: 0.1811 - val_ia: 0.8878 - val_loss: 0.0039 - val_mae: 0.0454 - val_rmse: 0.0581 - val_smape: 0.1445

Epoch 42/128

1147/1147 - 5s - 4ms/step - ia: 0.9586 - loss: 0.0085 - mae: 0.0668 - rmse: 0.0893 - smape: 0.1807 - val_ia: 0.9096 - val_loss: 0.0032 - val_mae: 0.0391 - val_rmse: 0.0526 - val_smape: 0.1271

Epoch 43/128

1147/1147 - 3s - 3ms/step - ia: 0.9585 - loss: 0.0086 - mae: 0.0670 - rmse: 0.0899 - smape: 0.1805 - val_ia: 0.8761 - val_loss: 0.0044 - val_mae: 0.0498 - val_rmse: 0.0622 - val_smape: 0.1532

Epoch 43: early stopping

Restoring model weights from the end of the best epoch: 28.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 19s 119ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/32

 54%|█████▍    | 27/50 [2:10:24<2:51:01, 446.17s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

2293/2293 - 7s - 3ms/step - ia: 0.7106 - loss: 0.3452 - mae: 0.4447 - rmse: 0.5559 - smape: 0.7917 - val_ia: 0.4749 - val_loss: 0.0924 - val_mae: 0.2417 - val_rmse: 0.2615 - val_smape: 0.5667

Epoch 2/32

2293/2293 - 4s - 2ms/step - ia: 0.7982 - loss: 0.1598 - mae: 0.3114 - rmse: 0.3911 - smape: 0.6083 - val_ia: 0.5550 - val_loss: 0.0490 - val_mae: 0.1703 - val_rmse: 0.1900 - val_smape: 0.4086

Epoch 3/32

2293/2293 - 5s - 2ms/step - ia: 0.8206 - loss: 0.1287 - mae: 0.2768 - rmse: 0.3507 - smape: 0.5461 - val_ia: 0.5955 - val_loss: 0.0404 - val_mae: 0.1470 - val_rmse: 0.1663 - val_smape: 0.3226

Epoch 4/32

2293/2293 - 5s - 2ms/step - ia: 0.8298 - loss: 0.1172 - mae: 0.2631 - rmse: 0.3340 - smape: 0.5184 - val_ia: 0.6168 - val_loss: 0.0380 - val_mae: 0.1376 - val_rmse: 0.1566 - val_smape: 0.2791

Epoch 5/32

2293/2293 - 5s - 2ms/step - ia: 0.8363 - loss: 0.1090 - mae: 0.2524 - rmse: 0.3224 - smape: 0.4977 - val_ia: 0.6119 - val_loss: 0.0387 - val_mae: 0.1410 - val_rmse: 0.1591 - val_smape: 0.2905

Epoch 6/32

2293/2293 - 3s - 1ms/step - ia: 0.8427 - loss: 0.1024 - mae: 0.2428 - rmse: 0.3119 - smape: 0.4790 - val_ia: 0.6209 - val_loss: 0.0346 - val_mae: 0.1345 - val_rmse: 0.1520 - val_smape: 0.2857

Epoch 7/32

2293/2293 - 10s - 4ms/step - ia: 0.8467 - loss: 0.0997 - mae: 0.2373 - rmse: 0.3074 - smape: 0.4683 - val_ia: 0.5973 - val_loss: 0.0392 - val_mae: 0.1466 - val_rmse: 0.1635 - val_smape: 0.3056

Epoch 8/32

2293/2293 - 8s - 3ms/step - ia: 0.8507 - loss: 0.0936 - mae: 0.2303 - rmse: 0.2976 - smape: 0.4582 - val_ia: 0.5951 - val_loss: 0.0376 - val_mae: 0.1455 - val_rmse: 0.1621 - val_smape: 0.3081

Epoch 9/32

2293/2293 - 7s - 3ms/step - ia: 0.8547 - loss: 0.0906 - mae: 0.2245 - rmse: 0.2925 - smape: 0.4493 - val_ia: 0.6099 - val_loss: 0.0333 - val_mae: 0.1371 - val_rmse: 0.1534 - val_smape: 0.3029

Epoch 10/32

2293/2293 - 9s - 4ms/step - ia: 0.8578 - loss: 0.0869 - mae: 0.2192 - rmse: 0.2857 - smape: 0.4363 - val_ia: 0.6102 - val_loss: 0.0321 - val_mae: 0.1352 - val_rmse: 0.1511 - val_smape: 0.2942

Epoch 11/32

2293/2293 - 7s - 3ms/step - ia: 0.8604 - loss: 0.0841 - mae: 0.2157 - rmse: 0.2813 - smape: 0.4355 - val_ia: 0.6103 - val_loss: 0.0301 - val_mae: 0.1326 - val_rmse: 0.1482 - val_smape: 0.2902

Epoch 12/32

2293/2293 - 7s - 3ms/step - ia: 0.8647 - loss: 0.0793 - mae: 0.2090 - rmse: 0.2731 - smape: 0.4232 - val_ia: 0.5991 - val_loss: 0.0311 - val_mae: 0.1375 - val_rmse: 0.1524 - val_smape: 0.3095

Epoch 13/32

2293/2293 - 5s - 2ms/step - ia: 0.8663 - loss: 0.0781 - mae: 0.2058 - rmse: 0.2707 - smape: 0.4167 - val_ia: 0.6500 - val_loss: 0.0222 - val_mae: 0.1118 - val_rmse: 0.1274 - val_smape: 0.2620

Epoch 14/32

2293/2293 - 4s - 2ms/step - ia: 0.8688 - loss: 0.0755 - mae: 0.2025 - rmse: 0.2663 - smape: 0.4082 - val_ia: 0.6431 - val_loss: 0.0224 - val_mae: 0.1142 - val_rmse: 0.1294 - val_smape: 0.2686

Epoch 15/32

2293/2293 - 4s - 2ms/step - ia: 0.8694 - loss: 0.0750 - mae: 0.2011 - rmse: 0.2648 - smape: 0.4090 - val_ia: 0.6577 - val_loss: 0.0194 - val_mae: 0.1054 - val_rmse: 0.1204 - val_smape: 0.2504

Epoch 16/32

2293/2293 - 4s - 2ms/step - ia: 0.8739 - loss: 0.0708 - mae: 0.1950 - rmse: 0.2577 - smape: 0.3946 - val_ia: 0.6537 - val_loss: 0.0191 - val_mae: 0.1068 - val_rmse: 0.1216 - val_smape: 0.2682

Epoch 17/32

2293/2293 - 4s - 2ms/step - ia: 0.8737 - loss: 0.0703 - mae: 0.1945 - rmse: 0.2566 - smape: 0.3956 - val_ia: 0.6445 - val_loss: 0.0195 - val_mae: 0.1087 - val_rmse: 0.1230 - val_smape: 0.2616

Epoch 18/32

2293/2293 - 5s - 2ms/step - ia: 0.8753 - loss: 0.0700 - mae: 0.1925 - rmse: 0.2562 - smape: 0.3917 - val_ia: 0.6706 - val_loss: 0.0164 - val_mae: 0.0974 - val_rmse: 0.1121 - val_smape: 0.2384

Epoch 19/32

2293/2293 - 5s - 2ms/step - ia: 0.8769 - loss: 0.0685 - mae: 0.1894 - rmse: 0.2528 - smape: 0.3879 - val_ia: 0.6677 - val_loss: 0.0156 - val_mae: 0.0974 - val_rmse: 0.1119 - val_smape: 0.2564

Epoch 20/32

2293/2293 - 8s - 3ms/step - ia: 0.8764 - loss: 0.0689 - mae: 0.1906 - rmse: 0.2539 - smape: 0.3889 - val_ia: 0.6957 - val_loss: 0.0129 - val_mae: 0.0859 - val_rmse: 0.1008 - val_smape: 0.2306

Epoch 21/32

2293/2293 - 11s - 5ms/step - ia: 0.8773 - loss: 0.0677 - mae: 0.1888 - rmse: 0.2517 - smape: 0.3848 - val_ia: 0.6768 - val_loss: 0.0142 - val_mae: 0.0927 - val_rmse: 0.1070 - val_smape: 0.2514

Epoch 22/32

2293/2293 - 10s - 4ms/step - ia: 0.8787 - loss: 0.0674 - mae: 0.1870 - rmse: 0.2506 - smape: 0.3811 - val_ia: 0.6931 - val_loss: 0.0126 - val_mae: 0.0863 - val_rmse: 0.1007 - val_smape: 0.2425

Epoch 23/32

2293/2293 - 7s - 3ms/step - ia: 0.8785 - loss: 0.0668 - mae: 0.1866 - rmse: 0.2496 - smape: 0.3827 - val_ia: 0.6762 - val_loss: 0.0138 - val_mae: 0.0916 - val_rmse: 0.1056 - val_smape: 0.2430

Epoch 24/32

2293/2293 - 9s - 4ms/step - ia: 0.8804 - loss: 0.0655 - mae: 0.1843 - rmse: 0.2475 - smape: 0.3784 - val_ia: 0.7054 - val_loss: 0.0115 - val_mae: 0.0810 - val_rmse: 0.0957 - val_smape: 0.2342

Epoch 25/32

2293/2293 - 5s - 2ms/step - ia: 0.8807 - loss: 0.0650 - mae: 0.1835 - rmse: 0.2462 - smape: 0.3745 - val_ia: 0.7002 - val_loss: 0.0117 - val_mae: 0.0827 - val_rmse: 0.0972 - val_smape: 0.2390

Epoch 26/32

2293/2293 - 4s - 2ms/step - ia: 0.8801 - loss: 0.0652 - mae: 0.1846 - rmse: 0.2470 - smape: 0.3773 - val_ia: 0.6784 - val_loss: 0.0135 - val_mae: 0.0902 - val_rmse: 0.1043 - val_smape: 0.2387

Epoch 27/32

2293/2293 - 4s - 2ms/step - ia: 0.8801 - loss: 0.0657 - mae: 0.1842 - rmse: 0.2474 - smape: 0.3744 - val_ia: 0.7309 - val_loss: 0.0100 - val_mae: 0.0736 - val_rmse: 0.0887 - val_smape: 0.2250

Epoch 28/32

2293/2293 - 5s - 2ms/step - ia: 0.8819 - loss: 0.0639 - mae: 0.1818 - rmse: 0.2442 - smape: 0.3733 - val_ia: 0.7029 - val_loss: 0.0111 - val_mae: 0.0811 - val_rmse: 0.0953 - val_smape: 0.2407

Epoch 29/32

2293/2293 - 6s - 3ms/step - ia: 0.8815 - loss: 0.0648 - mae: 0.1826 - rmse: 0.2460 - smape: 0.3710 - val_ia: 0.7298 - val_loss: 0.0098 - val_mae: 0.0736 - val_rmse: 0.0885 - val_smape: 0.2222

Epoch 30/32

2293/2293 - 5s - 2ms/step - ia: 0.8811 - loss: 0.0646 - mae: 0.1826 - rmse: 0.2457 - smape: 0.3733 - val_ia: 0.6836 - val_loss: 0.0125 - val_mae: 0.0877 - val_rmse: 0.1015 - val_smape: 0.2492

Epoch 31/32

2293/2293 - 5s - 2ms/step - ia: 0.8817 - loss: 0.0639 - mae: 0.1819 - rmse: 0.2442 - smape: 0.3701 - val_ia: 0.7133 - val_loss: 0.0106 - val_mae: 0.0782 - val_rmse: 0.0927 - val_smape: 0.2325

Epoch 32/32

2293/2293 - 4s - 2ms/step - ia: 0.8822 - loss: 0.0641 - mae: 0.1812 - rmse: 0.2441 - smape: 0.3687 - val_ia: 0.7072 - val_loss: 0.0106 - val_mae: 0.0787 - val_rmse: 0.0930 - val_smape: 0.2329

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 100ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 56%|█████▌    | 28/50 [2:13:36<2:15:42, 370.11s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1147/1147 - 8s - 7ms/step - ia: 0.8451 - loss: 0.1180 - mae: 0.2438 - rmse: 0.3056 - smape: 0.5174 - val_ia: 0.7991 - val_loss: 0.0184 - val_mae: 0.0972 - val_rmse: 0.1225 - val_smape: 0.2407

Epoch 2/256

1147/1147 - 5s - 5ms/step - ia: 0.9181 - loss: 0.0297 - mae: 0.1320 - rmse: 0.1693 - smape: 0.3375 - val_ia: 0.7957 - val_loss: 0.0161 - val_mae: 0.0964 - val_rmse: 0.1169 - val_smape: 0.2473

Epoch 3/256

1147/1147 - 5s - 5ms/step - ia: 0.9344 - loss: 0.0194 - mae: 0.1054 - rmse: 0.1365 - smape: 0.2860 - val_ia: 0.8215 - val_loss: 0.0116 - val_mae: 0.0811 - val_rmse: 0.1000 - val_smape: 0.2188

Epoch 4/256

1147/1147 - 4s - 4ms/step - ia: 0.9432 - loss: 0.0149 - mae: 0.0916 - rmse: 0.1194 - smape: 0.2589 - val_ia: 0.8420 - val_loss: 0.0092 - val_mae: 0.0704 - val_rmse: 0.0891 - val_smape: 0.1955

Epoch 5/256

1147/1147 - 5s - 4ms/step - ia: 0.9476 - loss: 0.0128 - mae: 0.0844 - rmse: 0.1106 - smape: 0.2410 - val_ia: 0.8654 - val_loss: 0.0074 - val_mae: 0.0611 - val_rmse: 0.0792 - val_smape: 0.1769

Epoch 6/256

1147/1147 - 4s - 3ms/step - ia: 0.9502 - loss: 0.0116 - mae: 0.0801 - rmse: 0.1049 - smape: 0.2329 - val_ia: 0.8518 - val_loss: 0.0079 - val_mae: 0.0647 - val_rmse: 0.0820 - val_smape: 0.1755

Epoch 7/256

1147/1147 - 4s - 3ms/step - ia: 0.9518 - loss: 0.0109 - mae: 0.0774 - rmse: 0.1017 - smape: 0.2254 - val_ia: 0.8634 - val_loss: 0.0063 - val_mae: 0.0575 - val_rmse: 0.0739 - val_smape: 0.1613

Epoch 8/256

1147/1147 - 4s - 3ms/step - ia: 0.9533 - loss: 0.0103 - mae: 0.0754 - rmse: 0.0990 - smape: 0.2203 - val_ia: 0.8785 - val_loss: 0.0054 - val_mae: 0.0522 - val_rmse: 0.0682 - val_smape: 0.1582

Epoch 9/256

1147/1147 - 5s - 5ms/step - ia: 0.9541 - loss: 0.0100 - mae: 0.0740 - rmse: 0.0973 - smape: 0.2166 - val_ia: 0.8728 - val_loss: 0.0063 - val_mae: 0.0569 - val_rmse: 0.0730 - val_smape: 0.1610

Epoch 10/256

1147/1147 - 5s - 5ms/step - ia: 0.9551 - loss: 0.0095 - mae: 0.0723 - rmse: 0.0949 - smape: 0.2128 - val_ia: 0.8752 - val_loss: 0.0056 - val_mae: 0.0541 - val_rmse: 0.0695 - val_smape: 0.1728

Epoch 11/256

1147/1147 - 5s - 5ms/step - ia: 0.9558 - loss: 0.0093 - mae: 0.0712 - rmse: 0.0937 - smape: 0.2079 - val_ia: 0.8804 - val_loss: 0.0053 - val_mae: 0.0527 - val_rmse: 0.0675 - val_smape: 0.1744

Epoch 12/256

1147/1147 - 5s - 4ms/step - ia: 0.9559 - loss: 0.0093 - mae: 0.0708 - rmse: 0.0933 - smape: 0.2076 - val_ia: 0.8795 - val_loss: 0.0051 - val_mae: 0.0510 - val_rmse: 0.0664 - val_smape: 0.1420

Epoch 13/256

1147/1147 - 4s - 3ms/step - ia: 0.9569 - loss: 0.0089 - mae: 0.0695 - rmse: 0.0915 - smape: 0.2028 - val_ia: 0.8962 - val_loss: 0.0043 - val_mae: 0.0461 - val_rmse: 0.0607 - val_smape: 0.1479

Epoch 14/256

1147/1147 - 5s - 4ms/step - ia: 0.9576 - loss: 0.0086 - mae: 0.0685 - rmse: 0.0902 - smape: 0.1989 - val_ia: 0.8824 - val_loss: 0.0058 - val_mae: 0.0539 - val_rmse: 0.0692 - val_smape: 0.1488

Epoch 15/256

1147/1147 - 4s - 4ms/step - ia: 0.9584 - loss: 0.0083 - mae: 0.0670 - rmse: 0.0884 - smape: 0.1981 - val_ia: 0.8998 - val_loss: 0.0042 - val_mae: 0.0449 - val_rmse: 0.0597 - val_smape: 0.1378

Epoch 16/256

1147/1147 - 5s - 5ms/step - ia: 0.9585 - loss: 0.0083 - mae: 0.0669 - rmse: 0.0883 - smape: 0.1966 - val_ia: 0.8645 - val_loss: 0.0054 - val_mae: 0.0551 - val_rmse: 0.0691 - val_smape: 0.1527

Epoch 17/256

1147/1147 - 4s - 4ms/step - ia: 0.9590 - loss: 0.0081 - mae: 0.0660 - rmse: 0.0869 - smape: 0.1931 - val_ia: 0.8905 - val_loss: 0.0049 - val_mae: 0.0499 - val_rmse: 0.0644 - val_smape: 0.1433

Epoch 18/256

1147/1147 - 4s - 3ms/step - ia: 0.9597 - loss: 0.0079 - mae: 0.0650 - rmse: 0.0858 - smape: 0.1920 - val_ia: 0.8842 - val_loss: 0.0046 - val_mae: 0.0491 - val_rmse: 0.0632 - val_smape: 0.1496

Epoch 19/256

1147/1147 - 5s - 5ms/step - ia: 0.9594 - loss: 0.0080 - mae: 0.0656 - rmse: 0.0865 - smape: 0.1900 - val_ia: 0.8791 - val_loss: 0.0050 - val_mae: 0.0521 - val_rmse: 0.0662 - val_smape: 0.1483

Epoch 20/256

1147/1147 - 3s - 3ms/step - ia: 0.9599 - loss: 0.0077 - mae: 0.0645 - rmse: 0.0852 - smape: 0.1917 - val_ia: 0.8778 - val_loss: 0.0047 - val_mae: 0.0495 - val_rmse: 0.0633 - val_smape: 0.1368

Epoch 21/256

1147/1147 - 3s - 2ms/step - ia: 0.9605 - loss: 0.0075 - mae: 0.0636 - rmse: 0.0840 - smape: 0.1879 - val_ia: 0.8966 - val_loss: 0.0040 - val_mae: 0.0449 - val_rmse: 0.0589 - val_smape: 0.1442

Epoch 22/256

1147/1147 - 3s - 2ms/step - ia: 0.9610 - loss: 0.0074 - mae: 0.0629 - rmse: 0.0832 - smape: 0.1863 - val_ia: 0.9034 - val_loss: 0.0036 - val_mae: 0.0414 - val_rmse: 0.0553 - val_smape: 0.1358

Epoch 23/256

1147/1147 - 3s - 2ms/step - ia: 0.9609 - loss: 0.0074 - mae: 0.0630 - rmse: 0.0834 - smape: 0.1847 - val_ia: 0.9033 - val_loss: 0.0038 - val_mae: 0.0431 - val_rmse: 0.0569 - val_smape: 0.1312

Epoch 24/256

1147/1147 - 3s - 2ms/step - ia: 0.9611 - loss: 0.0074 - mae: 0.0627 - rmse: 0.0829 - smape: 0.1847 - val_ia: 0.8940 - val_loss: 0.0043 - val_mae: 0.0470 - val_rmse: 0.0607 - val_smape: 0.1472

Epoch 25/256

1147/1147 - 3s - 2ms/step - ia: 0.9617 - loss: 0.0072 - mae: 0.0619 - rmse: 0.0818 - smape: 0.1843 - val_ia: 0.8886 - val_loss: 0.0042 - val_mae: 0.0464 - val_rmse: 0.0599 - val_smape: 0.1455

Epoch 26/256

1147/1147 - 2s - 2ms/step - ia: 0.9615 - loss: 0.0072 - mae: 0.0619 - rmse: 0.0819 - smape: 0.1835 - val_ia: 0.8835 - val_loss: 0.0043 - val_mae: 0.0481 - val_rmse: 0.0616 - val_smape: 0.1481

Epoch 27/256

1147/1147 - 2s - 2ms/step - ia: 0.9618 - loss: 0.0071 - mae: 0.0616 - rmse: 0.0813 - smape: 0.1829 - val_ia: 0.8994 - val_loss: 0.0040 - val_mae: 0.0451 - val_rmse: 0.0589 - val_smape: 0.1396

Epoch 28/256

1147/1147 - 3s - 2ms/step - ia: 0.9621 - loss: 0.0071 - mae: 0.0611 - rmse: 0.0811 - smape: 0.1817 - val_ia: 0.8964 - val_loss: 0.0041 - val_mae: 0.0456 - val_rmse: 0.0594 - val_smape: 0.1424

Epoch 29/256

1147/1147 - 5s - 4ms/step - ia: 0.9623 - loss: 0.0070 - mae: 0.0609 - rmse: 0.0808 - smape: 0.1820 - val_ia: 0.8744 - val_loss: 0.0052 - val_mae: 0.0542 - val_rmse: 0.0678 - val_smape: 0.1420

Epoch 30/256

1147/1147 - 3s - 2ms/step - ia: 0.9620 - loss: 0.0071 - mae: 0.0612 - rmse: 0.0815 - smape: 0.1795 - val_ia: 0.9007 - val_loss: 0.0038 - val_mae: 0.0436 - val_rmse: 0.0570 - val_smape: 0.1383

Epoch 31/256

1147/1147 - 3s - 2ms/step - ia: 0.9625 - loss: 0.0069 - mae: 0.0605 - rmse: 0.0804 - smape: 0.1789 - val_ia: 0.8918 - val_loss: 0.0039 - val_mae: 0.0446 - val_rmse: 0.0578 - val_smape: 0.1371

Epoch 32/256

1147/1147 - 3s - 2ms/step - ia: 0.9627 - loss: 0.0069 - mae: 0.0602 - rmse: 0.0798 - smape: 0.1789 - val_ia: 0.8913 - val_loss: 0.0039 - val_mae: 0.0452 - val_rmse: 0.0583 - val_smape: 0.1406

Epoch 33/256

1147/1147 - 4s - 3ms/step - ia: 0.9630 - loss: 0.0067 - mae: 0.0598 - rmse: 0.0792 - smape: 0.1769 - val_ia: 0.8793 - val_loss: 0.0044 - val_mae: 0.0491 - val_rmse: 0.0621 - val_smape: 0.1439

Epoch 34/256

1147/1147 - 4s - 3ms/step - ia: 0.9631 - loss: 0.0067 - mae: 0.0594 - rmse: 0.0790 - smape: 0.1762 - val_ia: 0.8832 - val_loss: 0.0041 - val_mae: 0.0473 - val_rmse: 0.0602 - val_smape: 0.1404

Epoch 35/256

1147/1147 - 6s - 5ms/step - ia: 0.9633 - loss: 0.0066 - mae: 0.0591 - rmse: 0.0785 - smape: 0.1762 - val_ia: 0.9066 - val_loss: 0.0033 - val_mae: 0.0400 - val_rmse: 0.0532 - val_smape: 0.1306

Epoch 36/256

1147/1147 - 7s - 6ms/step - ia: 0.9632 - loss: 0.0067 - mae: 0.0594 - rmse: 0.0789 - smape: 0.1764 - val_ia: 0.9075 - val_loss: 0.0034 - val_mae: 0.0404 - val_rmse: 0.0537 - val_smape: 0.1282

Epoch 37/256

1147/1147 - 8s - 7ms/step - ia: 0.9635 - loss: 0.0066 - mae: 0.0589 - rmse: 0.0783 - smape: 0.1750 - val_ia: 0.8689 - val_loss: 0.0053 - val_mae: 0.0551 - val_rmse: 0.0682 - val_smape: 0.1464

Epoch 38/256

1147/1147 - 4s - 4ms/step - ia: 0.9633 - loss: 0.0067 - mae: 0.0592 - rmse: 0.0787 - smape: 0.1748 - val_ia: 0.8888 - val_loss: 0.0040 - val_mae: 0.0464 - val_rmse: 0.0591 - val_smape: 0.1458

Epoch 39/256

1147/1147 - 5s - 4ms/step - ia: 0.9635 - loss: 0.0066 - mae: 0.0588 - rmse: 0.0782 - smape: 0.1734 - val_ia: 0.9085 - val_loss: 0.0032 - val_mae: 0.0393 - val_rmse: 0.0524 - val_smape: 0.1243

Epoch 40/256

1147/1147 - 4s - 4ms/step - ia: 0.9640 - loss: 0.0065 - mae: 0.0582 - rmse: 0.0775 - smape: 0.1728 - val_ia: 0.8861 - val_loss: 0.0041 - val_mae: 0.0465 - val_rmse: 0.0593 - val_smape: 0.1346

Epoch 41/256

1147/1147 - 5s - 4ms/step - ia: 0.9636 - loss: 0.0066 - mae: 0.0587 - rmse: 0.0781 - smape: 0.1732 - val_ia: 0.9037 - val_loss: 0.0037 - val_mae: 0.0435 - val_rmse: 0.0567 - val_smape: 0.1314

Epoch 42/256

1147/1147 - 3s - 3ms/step - ia: 0.9638 - loss: 0.0065 - mae: 0.0584 - rmse: 0.0778 - smape: 0.1725 - val_ia: 0.8945 - val_loss: 0.0037 - val_mae: 0.0440 - val_rmse: 0.0567 - val_smape: 0.1394

Epoch 43/256

1147/1147 - 3s - 3ms/step - ia: 0.9637 - loss: 0.0065 - mae: 0.0586 - rmse: 0.0778 - smape: 0.1723 - val_ia: 0.9058 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0535 - val_smape: 0.1340

Epoch 44/256

1147/1147 - 5s - 4ms/step - ia: 0.9639 - loss: 0.0065 - mae: 0.0582 - rmse: 0.0775 - smape: 0.1704 - val_ia: 0.8944 - val_loss: 0.0036 - val_mae: 0.0429 - val_rmse: 0.0558 - val_smape: 0.1316

Epoch 45/256

1147/1147 - 3s - 2ms/step - ia: 0.9639 - loss: 0.0065 - mae: 0.0582 - rmse: 0.0776 - smape: 0.1726 - val_ia: 0.8921 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0576 - val_smape: 0.1378

Epoch 46/256

1147/1147 - 3s - 3ms/step - ia: 0.9642 - loss: 0.0064 - mae: 0.0576 - rmse: 0.0768 - smape: 0.1698 - val_ia: 0.8990 - val_loss: 0.0037 - val_mae: 0.0436 - val_rmse: 0.0565 - val_smape: 0.1292

Epoch 47/256

1147/1147 - 4s - 3ms/step - ia: 0.9640 - loss: 0.0064 - mae: 0.0580 - rmse: 0.0773 - smape: 0.1715 - val_ia: 0.9001 - val_loss: 0.0036 - val_mae: 0.0435 - val_rmse: 0.0564 - val_smape: 0.1375

Epoch 48/256

1147/1147 - 7s - 6ms/step - ia: 0.9642 - loss: 0.0064 - mae: 0.0577 - rmse: 0.0770 - smape: 0.1690 - val_ia: 0.9008 - val_loss: 0.0036 - val_mae: 0.0434 - val_rmse: 0.0559 - val_smape: 0.1397

Epoch 49/256

1147/1147 - 5s - 5ms/step - ia: 0.9644 - loss: 0.0063 - mae: 0.0574 - rmse: 0.0764 - smape: 0.1709 - val_ia: 0.9066 - val_loss: 0.0033 - val_mae: 0.0406 - val_rmse: 0.0534 - val_smape: 0.1273

Epoch 50/256

1147/1147 - 10s - 9ms/step - ia: 0.9642 - loss: 0.0064 - mae: 0.0578 - rmse: 0.0770 - smape: 0.1706 - val_ia: 0.8889 - val_loss: 0.0039 - val_mae: 0.0459 - val_rmse: 0.0585 - val_smape: 0.1372

Epoch 51/256

1147/1147 - 9s - 8ms/step - ia: 0.9645 - loss: 0.0063 - mae: 0.0572 - rmse: 0.0762 - smape: 0.1697 - val_ia: 0.8980 - val_loss: 0.0035 - val_mae: 0.0430 - val_rmse: 0.0553 - val_smape: 0.1326

Epoch 52/256

1147/1147 - 5s - 4ms/step - ia: 0.9646 - loss: 0.0062 - mae: 0.0571 - rmse: 0.0761 - smape: 0.1704 - val_ia: 0.8990 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0546 - val_smape: 0.1302

Epoch 53/256

1147/1147 - 4s - 4ms/step - ia: 0.9644 - loss: 0.0063 - mae: 0.0574 - rmse: 0.0764 - smape: 0.1678 - val_ia: 0.8897 - val_loss: 0.0040 - val_mae: 0.0469 - val_rmse: 0.0595 - val_smape: 0.1320

Epoch 54/256

1147/1147 - 5s - 5ms/step - ia: 0.9647 - loss: 0.0062 - mae: 0.0569 - rmse: 0.0758 - smape: 0.1671 - val_ia: 0.9045 - val_loss: 0.0034 - val_mae: 0.0418 - val_rmse: 0.0547 - val_smape: 0.1283

Epoch 54: early stopping

Restoring model weights from the end of the best epoch: 39.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 105ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/64

 58%|█████▊    | 29/50 [2:17:40<1:56:16, 332.21s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

2293/2293 - 10s - 5ms/step - ia: 0.7128 - loss: 0.3496 - mae: 0.4588 - rmse: 0.5667 - smape: 0.7941 - val_ia: 0.5364 - val_loss: 0.0594 - val_mae: 0.1903 - val_rmse: 0.2117 - val_smape: 0.4956

Epoch 2/64

2293/2293 - 7s - 3ms/step - ia: 0.7854 - loss: 0.1878 - mae: 0.3441 - rmse: 0.4259 - smape: 0.6593 - val_ia: 0.6322 - val_loss: 0.0263 - val_mae: 0.1222 - val_rmse: 0.1427 - val_smape: 0.3456

Epoch 3/64

2293/2293 - 10s - 5ms/step - ia: 0.8181 - loss: 0.1325 - mae: 0.2886 - rmse: 0.3574 - smape: 0.5952 - val_ia: 0.6410 - val_loss: 0.0234 - val_mae: 0.1160 - val_rmse: 0.1353 - val_smape: 0.3269

Epoch 4/64

2293/2293 - 6s - 3ms/step - ia: 0.8447 - loss: 0.0949 - mae: 0.2438 - rmse: 0.3022 - smape: 0.5316 - val_ia: 0.6541 - val_loss: 0.0214 - val_mae: 0.1106 - val_rmse: 0.1291 - val_smape: 0.3131

Epoch 5/64

2293/2293 - 11s - 5ms/step - ia: 0.8686 - loss: 0.0681 - mae: 0.2059 - rmse: 0.2560 - smape: 0.4710 - val_ia: 0.6630 - val_loss: 0.0198 - val_mae: 0.1064 - val_rmse: 0.1242 - val_smape: 0.2954

Epoch 6/64

2293/2293 - 10s - 5ms/step - ia: 0.8834 - loss: 0.0538 - mae: 0.1822 - rmse: 0.2271 - smape: 0.4274 - val_ia: 0.6593 - val_loss: 0.0196 - val_mae: 0.1074 - val_rmse: 0.1246 - val_smape: 0.2964

Epoch 7/64

2293/2293 - 11s - 5ms/step - ia: 0.8950 - loss: 0.0444 - mae: 0.1641 - rmse: 0.2060 - smape: 0.3930 - val_ia: 0.6865 - val_loss: 0.0168 - val_mae: 0.0960 - val_rmse: 0.1127 - val_smape: 0.2525

Epoch 8/64

2293/2293 - 7s - 3ms/step - ia: 0.9013 - loss: 0.0393 - mae: 0.1541 - rmse: 0.1940 - smape: 0.3730 - val_ia: 0.6819 - val_loss: 0.0163 - val_mae: 0.0956 - val_rmse: 0.1123 - val_smape: 0.2483

Epoch 9/64

2293/2293 - 12s - 5ms/step - ia: 0.9053 - loss: 0.0363 - mae: 0.1482 - rmse: 0.1863 - smape: 0.3589 - val_ia: 0.6970 - val_loss: 0.0150 - val_mae: 0.0905 - val_rmse: 0.1069 - val_smape: 0.2289

Epoch 10/64

2293/2293 - 7s - 3ms/step - ia: 0.9085 - loss: 0.0347 - mae: 0.1435 - rmse: 0.1817 - smape: 0.3471 - val_ia: 0.6948 - val_loss: 0.0147 - val_mae: 0.0907 - val_rmse: 0.1067 - val_smape: 0.2304

Epoch 11/64

2293/2293 - 10s - 5ms/step - ia: 0.9104 - loss: 0.0331 - mae: 0.1406 - rmse: 0.1775 - smape: 0.3405 - val_ia: 0.7143 - val_loss: 0.0134 - val_mae: 0.0843 - val_rmse: 0.0999 - val_smape: 0.2066

Epoch 12/64

2293/2293 - 7s - 3ms/step - ia: 0.9119 - loss: 0.0322 - mae: 0.1383 - rmse: 0.1750 - smape: 0.3362 - val_ia: 0.7167 - val_loss: 0.0130 - val_mae: 0.0834 - val_rmse: 0.0988 - val_smape: 0.2037

Epoch 13/64

2293/2293 - 7s - 3ms/step - ia: 0.9136 - loss: 0.0309 - mae: 0.1358 - rmse: 0.1716 - smape: 0.3313 - val_ia: 0.7189 - val_loss: 0.0128 - val_mae: 0.0829 - val_rmse: 0.0981 - val_smape: 0.2002

Epoch 14/64

2293/2293 - 6s - 3ms/step - ia: 0.9147 - loss: 0.0304 - mae: 0.1345 - rmse: 0.1702 - smape: 0.3258 - val_ia: 0.7193 - val_loss: 0.0124 - val_mae: 0.0821 - val_rmse: 0.0971 - val_smape: 0.1990

Epoch 15/64

2293/2293 - 10s - 5ms/step - ia: 0.9159 - loss: 0.0295 - mae: 0.1323 - rmse: 0.1675 - smape: 0.3243 - val_ia: 0.7269 - val_loss: 0.0119 - val_mae: 0.0797 - val_rmse: 0.0945 - val_smape: 0.1918

Epoch 16/64

2293/2293 - 11s - 5ms/step - ia: 0.9165 - loss: 0.0289 - mae: 0.1311 - rmse: 0.1659 - smape: 0.3186 - val_ia: 0.7321 - val_loss: 0.0115 - val_mae: 0.0778 - val_rmse: 0.0923 - val_smape: 0.1854

Epoch 17/64

2293/2293 - 7s - 3ms/step - ia: 0.9177 - loss: 0.0285 - mae: 0.1297 - rmse: 0.1643 - smape: 0.3161 - val_ia: 0.7300 - val_loss: 0.0114 - val_mae: 0.0783 - val_rmse: 0.0927 - val_smape: 0.1876

Epoch 18/64

2293/2293 - 7s - 3ms/step - ia: 0.9187 - loss: 0.0276 - mae: 0.1277 - rmse: 0.1618 - smape: 0.3114 - val_ia: 0.7329 - val_loss: 0.0116 - val_mae: 0.0781 - val_rmse: 0.0925 - val_smape: 0.1809

Epoch 19/64

2293/2293 - 11s - 5ms/step - ia: 0.9191 - loss: 0.0275 - mae: 0.1273 - rmse: 0.1615 - smape: 0.3118 - val_ia: 0.7318 - val_loss: 0.0110 - val_mae: 0.0772 - val_rmse: 0.0914 - val_smape: 0.1849

Epoch 20/64

2293/2293 - 6s - 3ms/step - ia: 0.9206 - loss: 0.0266 - mae: 0.1248 - rmse: 0.1588 - smape: 0.3077 - val_ia: 0.7311 - val_loss: 0.0112 - val_mae: 0.0775 - val_rmse: 0.0917 - val_smape: 0.1818

Epoch 21/64

2293/2293 - 11s - 5ms/step - ia: 0.9207 - loss: 0.0263 - mae: 0.1246 - rmse: 0.1578 - smape: 0.3054 - val_ia: 0.7387 - val_loss: 0.0105 - val_mae: 0.0752 - val_rmse: 0.0889 - val_smape: 0.1793

Epoch 22/64

2293/2293 - 7s - 3ms/step - ia: 0.9220 - loss: 0.0258 - mae: 0.1228 - rmse: 0.1562 - smape: 0.3037 - val_ia: 0.7377 - val_loss: 0.0108 - val_mae: 0.0754 - val_rmse: 0.0893 - val_smape: 0.1756

Epoch 23/64

2293/2293 - 7s - 3ms/step - ia: 0.9212 - loss: 0.0259 - mae: 0.1233 - rmse: 0.1568 - smape: 0.3057 - val_ia: 0.7424 - val_loss: 0.0105 - val_mae: 0.0736 - val_rmse: 0.0874 - val_smape: 0.1692

Epoch 24/64

2293/2293 - 7s - 3ms/step - ia: 0.9224 - loss: 0.0256 - mae: 0.1220 - rmse: 0.1556 - smape: 0.2997 - val_ia: 0.7404 - val_loss: 0.0102 - val_mae: 0.0743 - val_rmse: 0.0878 - val_smape: 0.1765

Epoch 25/64

2293/2293 - 10s - 5ms/step - ia: 0.9232 - loss: 0.0249 - mae: 0.1209 - rmse: 0.1535 - smape: 0.2999 - val_ia: 0.7357 - val_loss: 0.0105 - val_mae: 0.0755 - val_rmse: 0.0890 - val_smape: 0.1776

Epoch 26/64

2293/2293 - 6s - 3ms/step - ia: 0.9236 - loss: 0.0246 - mae: 0.1200 - rmse: 0.1526 - smape: 0.2989 - val_ia: 0.7393 - val_loss: 0.0108 - val_mae: 0.0750 - val_rmse: 0.0886 - val_smape: 0.1701

Epoch 27/64

2293/2293 - 10s - 4ms/step - ia: 0.9244 - loss: 0.0243 - mae: 0.1190 - rmse: 0.1514 - smape: 0.2974 - val_ia: 0.7349 - val_loss: 0.0109 - val_mae: 0.0767 - val_rmse: 0.0901 - val_smape: 0.1794

Epoch 28/64

2293/2293 - 5s - 2ms/step - ia: 0.9242 - loss: 0.0243 - mae: 0.1190 - rmse: 0.1517 - smape: 0.2961 - val_ia: 0.7356 - val_loss: 0.0108 - val_mae: 0.0758 - val_rmse: 0.0892 - val_smape: 0.1735

Epoch 29/64

2293/2293 - 5s - 2ms/step - ia: 0.9257 - loss: 0.0234 - mae: 0.1172 - rmse: 0.1490 - smape: 0.2912 - val_ia: 0.7382 - val_loss: 0.0106 - val_mae: 0.0748 - val_rmse: 0.0882 - val_smape: 0.1727

Epoch 30/64

2293/2293 - 4s - 2ms/step - ia: 0.9263 - loss: 0.0233 - mae: 0.1162 - rmse: 0.1484 - smape: 0.2876 - val_ia: 0.7394 - val_loss: 0.0104 - val_mae: 0.0744 - val_rmse: 0.0878 - val_smape: 0.1715

Epoch 31/64

2293/2293 - 4s - 2ms/step - ia: 0.9267 - loss: 0.0229 - mae: 0.1153 - rmse: 0.1471 - smape: 0.2884 - val_ia: 0.7392 - val_loss: 0.0104 - val_mae: 0.0743 - val_rmse: 0.0875 - val_smape: 0.1721

Epoch 32/64

2293/2293 - 5s - 2ms/step - ia: 0.9263 - loss: 0.0229 - mae: 0.1154 - rmse: 0.1471 - smape: 0.2885 - val_ia: 0.7411 - val_loss: 0.0101 - val_mae: 0.0736 - val_rmse: 0.0867 - val_smape: 0.1720

Epoch 33/64

2293/2293 - 5s - 2ms/step - ia: 0.9274 - loss: 0.0226 - mae: 0.1143 - rmse: 0.1460 - smape: 0.2843 - val_ia: 0.7356 - val_loss: 0.0108 - val_mae: 0.0757 - val_rmse: 0.0889 - val_smape: 0.1715

Epoch 34/64

2293/2293 - 7s - 3ms/step - ia: 0.9281 - loss: 0.0223 - mae: 0.1132 - rmse: 0.1449 - smape: 0.2827 - val_ia: 0.7400 - val_loss: 0.0101 - val_mae: 0.0736 - val_rmse: 0.0866 - val_smape: 0.1717

Epoch 35/64

2293/2293 - 7s - 3ms/step - ia: 0.9281 - loss: 0.0221 - mae: 0.1134 - rmse: 0.1448 - smape: 0.2839 - val_ia: 0.7372 - val_loss: 0.0102 - val_mae: 0.0746 - val_rmse: 0.0876 - val_smape: 0.1769

Epoch 36/64

2293/2293 - 10s - 4ms/step - ia: 0.9285 - loss: 0.0220 - mae: 0.1127 - rmse: 0.1441 - smape: 0.2811 - val_ia: 0.7309 - val_loss: 0.0110 - val_mae: 0.0771 - val_rmse: 0.0902 - val_smape: 0.1738

Epoch 37/64

2293/2293 - 7s - 3ms/step - ia: 0.9290 - loss: 0.0218 - mae: 0.1118 - rmse: 0.1432 - smape: 0.2795 - val_ia: 0.7269 - val_loss: 0.0113 - val_mae: 0.0788 - val_rmse: 0.0916 - val_smape: 0.1809

Epoch 38/64

2293/2293 - 7s - 3ms/step - ia: 0.9291 - loss: 0.0217 - mae: 0.1119 - rmse: 0.1431 - smape: 0.2796 - val_ia: 0.7381 - val_loss: 0.0102 - val_mae: 0.0738 - val_rmse: 0.0867 - val_smape: 0.1673

Epoch 39/64

2293/2293 - 10s - 4ms/step - ia: 0.9297 - loss: 0.0211 - mae: 0.1106 - rmse: 0.1413 - smape: 0.2776 - val_ia: 0.7332 - val_loss: 0.0107 - val_mae: 0.0762 - val_rmse: 0.0891 - val_smape: 0.1734

Epoch 40/64

2293/2293 - 11s - 5ms/step - ia: 0.9301 - loss: 0.0211 - mae: 0.1102 - rmse: 0.1408 - smape: 0.2792 - val_ia: 0.7299 - val_loss: 0.0110 - val_mae: 0.0774 - val_rmse: 0.0901 - val_smape: 0.1769

Epoch 41/64

2293/2293 - 7s - 3ms/step - ia: 0.9306 - loss: 0.0208 - mae: 0.1092 - rmse: 0.1398 - smape: 0.2759 - val_ia: 0.7387 - val_loss: 0.0101 - val_mae: 0.0738 - val_rmse: 0.0865 - val_smape: 0.1694

Epoch 42/64

2293/2293 - 10s - 4ms/step - ia: 0.9304 - loss: 0.0208 - mae: 0.1094 - rmse: 0.1400 - smape: 0.2763 - val_ia: 0.7333 - val_loss: 0.0106 - val_mae: 0.0757 - val_rmse: 0.0885 - val_smape: 0.1691

Epoch 43/64

2293/2293 - 7s - 3ms/step - ia: 0.9311 - loss: 0.0204 - mae: 0.1083 - rmse: 0.1386 - smape: 0.2729 - val_ia: 0.7338 - val_loss: 0.0105 - val_mae: 0.0758 - val_rmse: 0.0883 - val_smape: 0.1755

Epoch 44/64

2293/2293 - 6s - 3ms/step - ia: 0.9316 - loss: 0.0201 - mae: 0.1073 - rmse: 0.1376 - smape: 0.2712 - val_ia: 0.7333 - val_loss: 0.0106 - val_mae: 0.0758 - val_rmse: 0.0883 - val_smape: 0.1716

Epoch 45/64

2293/2293 - 7s - 3ms/step - ia: 0.9314 - loss: 0.0202 - mae: 0.1077 - rmse: 0.1379 - smape: 0.2702 - val_ia: 0.7380 - val_loss: 0.0102 - val_mae: 0.0738 - val_rmse: 0.0865 - val_smape: 0.1635

Epoch 46/64

2293/2293 - 7s - 3ms/step - ia: 0.9325 - loss: 0.0197 - mae: 0.1063 - rmse: 0.1361 - smape: 0.2705 - val_ia: 0.7422 - val_loss: 0.0098 - val_mae: 0.0722 - val_rmse: 0.0848 - val_smape: 0.1623

Epoch 47/64

2293/2293 - 8s - 4ms/step - ia: 0.9322 - loss: 0.0197 - mae: 0.1064 - rmse: 0.1361 - smape: 0.2698 - val_ia: 0.7322 - val_loss: 0.0106 - val_mae: 0.0762 - val_rmse: 0.0888 - val_smape: 0.1740

Epoch 48/64

2293/2293 - 5s - 2ms/step - ia: 0.9327 - loss: 0.0195 - mae: 0.1059 - rmse: 0.1354 - smape: 0.2667 - val_ia: 0.7418 - val_loss: 0.0096 - val_mae: 0.0721 - val_rmse: 0.0846 - val_smape: 0.1661

Epoch 49/64

2293/2293 - 9s - 4ms/step - ia: 0.9329 - loss: 0.0195 - mae: 0.1058 - rmse: 0.1355 - smape: 0.2697 - val_ia: 0.7466 - val_loss: 0.0092 - val_mae: 0.0702 - val_rmse: 0.0827 - val_smape: 0.1608

Epoch 50/64

2293/2293 - 5s - 2ms/step - ia: 0.9335 - loss: 0.0193 - mae: 0.1046 - rmse: 0.1345 - smape: 0.2660 - val_ia: 0.7342 - val_loss: 0.0103 - val_mae: 0.0750 - val_rmse: 0.0875 - val_smape: 0.1683

Epoch 51/64

2293/2293 - 8s - 3ms/step - ia: 0.9333 - loss: 0.0192 - mae: 0.1047 - rmse: 0.1342 - smape: 0.2641 - val_ia: 0.7446 - val_loss: 0.0093 - val_mae: 0.0709 - val_rmse: 0.0834 - val_smape: 0.1624

Epoch 52/64

2293/2293 - 7s - 3ms/step - ia: 0.9340 - loss: 0.0188 - mae: 0.1038 - rmse: 0.1331 - smape: 0.2642 - val_ia: 0.7448 - val_loss: 0.0091 - val_mae: 0.0710 - val_rmse: 0.0833 - val_smape: 0.1689

Epoch 53/64

2293/2293 - 7s - 3ms/step - ia: 0.9344 - loss: 0.0185 - mae: 0.1029 - rmse: 0.1317 - smape: 0.2623 - val_ia: 0.7401 - val_loss: 0.0098 - val_mae: 0.0727 - val_rmse: 0.0850 - val_smape: 0.1606

Epoch 54/64

2293/2293 - 7s - 3ms/step - ia: 0.9350 - loss: 0.0184 - mae: 0.1023 - rmse: 0.1314 - smape: 0.2638 - val_ia: 0.7419 - val_loss: 0.0094 - val_mae: 0.0719 - val_rmse: 0.0841 - val_smape: 0.1665

Epoch 55/64

2293/2293 - 7s - 3ms/step - ia: 0.9352 - loss: 0.0182 - mae: 0.1018 - rmse: 0.1309 - smape: 0.2604 - val_ia: 0.7464 - val_loss: 0.0089 - val_mae: 0.0700 - val_rmse: 0.0821 - val_smape: 0.1650

Epoch 56/64

2293/2293 - 7s - 3ms/step - ia: 0.9352 - loss: 0.0182 - mae: 0.1018 - rmse: 0.1311 - smape: 0.2604 - val_ia: 0.7508 - val_loss: 0.0086 - val_mae: 0.0685 - val_rmse: 0.0806 - val_smape: 0.1608

Epoch 57/64

2293/2293 - 5s - 2ms/step - ia: 0.9356 - loss: 0.0179 - mae: 0.1009 - rmse: 0.1295 - smape: 0.2578 - val_ia: 0.7551 - val_loss: 0.0083 - val_mae: 0.0667 - val_rmse: 0.0789 - val_smape: 0.1544

Epoch 58/64

2293/2293 - 12s - 5ms/step - ia: 0.9357 - loss: 0.0180 - mae: 0.1011 - rmse: 0.1299 - smape: 0.2577 - val_ia: 0.7559 - val_loss: 0.0081 - val_mae: 0.0664 - val_rmse: 0.0785 - val_smape: 0.1573

Epoch 59/64

2293/2293 - 10s - 4ms/step - ia: 0.9360 - loss: 0.0176 - mae: 0.1001 - rmse: 0.1287 - smape: 0.2561 - val_ia: 0.7595 - val_loss: 0.0079 - val_mae: 0.0652 - val_rmse: 0.0773 - val_smape: 0.1547

Epoch 60/64

2293/2293 - 11s - 5ms/step - ia: 0.9361 - loss: 0.0179 - mae: 0.1006 - rmse: 0.1296 - smape: 0.2576 - val_ia: 0.7580 - val_loss: 0.0079 - val_mae: 0.0656 - val_rmse: 0.0776 - val_smape: 0.1579

Epoch 61/64

2293/2293 - 7s - 3ms/step - ia: 0.9366 - loss: 0.0176 - mae: 0.0999 - rmse: 0.1285 - smape: 0.2553 - val_ia: 0.7577 - val_loss: 0.0079 - val_mae: 0.0657 - val_rmse: 0.0777 - val_smape: 0.1596

Epoch 62/64

2293/2293 - 8s - 4ms/step - ia: 0.9368 - loss: 0.0173 - mae: 0.0992 - rmse: 0.1274 - smape: 0.2536 - val_ia: 0.7626 - val_loss: 0.0075 - val_mae: 0.0640 - val_rmse: 0.0759 - val_smape: 0.1554

Epoch 63/64

2293/2293 - 5s - 2ms/step - ia: 0.9372 - loss: 0.0173 - mae: 0.0987 - rmse: 0.1271 - smape: 0.2529 - val_ia: 0.7622 - val_loss: 0.0076 - val_mae: 0.0640 - val_rmse: 0.0760 - val_smape: 0.1533

Epoch 64/64

2293/2293 - 4s - 2ms/step - ia: 0.9372 - loss: 0.0171 - mae: 0.0987 - rmse: 0.1265 - smape: 0.2517 - val_ia: 0.7678 - val_loss: 0.0071 - val_mae: 0.0618 - val_rmse: 0.0737 - val_smape: 0.1513

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 60%|██████    | 30/50 [2:25:56<2:07:09, 381.46s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1147/1147 - 7s - 6ms/step - ia: 0.6276 - loss: 0.4176 - mae: 0.4976 - rmse: 0.6240 - smape: 0.9466 - val_ia: 0.4864 - val_loss: 0.2507 - val_mae: 0.3914 - val_rmse: 0.4517 - val_smape: 0.7429

Epoch 2/128

1147/1147 - 5s - 4ms/step - ia: 0.7795 - loss: 0.1912 - mae: 0.3384 - rmse: 0.4322 - smape: 0.6688 - val_ia: 0.5369 - val_loss: 0.1752 - val_mae: 0.3293 - val_rmse: 0.3687 - val_smape: 0.6690

Epoch 3/128

1147/1147 - 5s - 4ms/step - ia: 0.8188 - loss: 0.1369 - mae: 0.2825 - rmse: 0.3656 - smape: 0.5703 - val_ia: 0.5827 - val_loss: 0.1239 - val_mae: 0.2776 - val_rmse: 0.3076 - val_smape: 0.6040

Epoch 4/128

1147/1147 - 3s - 3ms/step - ia: 0.8418 - loss: 0.1066 - mae: 0.2489 - rmse: 0.3227 - smape: 0.5097 - val_ia: 0.6171 - val_loss: 0.0930 - val_mae: 0.2406 - val_rmse: 0.2682 - val_smape: 0.5513

Epoch 5/128

1147/1147 - 3s - 3ms/step - ia: 0.8544 - loss: 0.0915 - mae: 0.2300 - rmse: 0.2987 - smape: 0.4775 - val_ia: 0.6392 - val_loss: 0.0712 - val_mae: 0.2127 - val_rmse: 0.2400 - val_smape: 0.5018

Epoch 6/128

1147/1147 - 5s - 4ms/step - ia: 0.8651 - loss: 0.0798 - mae: 0.2137 - rmse: 0.2790 - smape: 0.4465 - val_ia: 0.6401 - val_loss: 0.0651 - val_mae: 0.2057 - val_rmse: 0.2328 - val_smape: 0.4770

Epoch 7/128

1147/1147 - 6s - 5ms/step - ia: 0.8752 - loss: 0.0683 - mae: 0.1980 - rmse: 0.2580 - smape: 0.4212 - val_ia: 0.6392 - val_loss: 0.0622 - val_mae: 0.2028 - val_rmse: 0.2294 - val_smape: 0.4593

Epoch 8/128

1147/1147 - 10s - 8ms/step - ia: 0.8815 - loss: 0.0624 - mae: 0.1890 - rmse: 0.2466 - smape: 0.4049 - val_ia: 0.6380 - val_loss: 0.0612 - val_mae: 0.2024 - val_rmse: 0.2283 - val_smape: 0.4504

Epoch 9/128

1147/1147 - 5s - 4ms/step - ia: 0.8862 - loss: 0.0576 - mae: 0.1810 - rmse: 0.2368 - smape: 0.3903 - val_ia: 0.6284 - val_loss: 0.0649 - val_mae: 0.2088 - val_rmse: 0.2357 - val_smape: 0.4527

Epoch 10/128

1147/1147 - 6s - 5ms/step - ia: 0.8915 - loss: 0.0530 - mae: 0.1730 - rmse: 0.2270 - smape: 0.3733 - val_ia: 0.6210 - val_loss: 0.0684 - val_mae: 0.2146 - val_rmse: 0.2416 - val_smape: 0.4543

Epoch 11/128

1147/1147 - 5s - 4ms/step - ia: 0.8948 - loss: 0.0496 - mae: 0.1676 - rmse: 0.2195 - smape: 0.3648 - val_ia: 0.6246 - val_loss: 0.0665 - val_mae: 0.2112 - val_rmse: 0.2381 - val_smape: 0.4421

Epoch 12/128

1147/1147 - 5s - 4ms/step - ia: 0.8985 - loss: 0.0467 - mae: 0.1621 - rmse: 0.2132 - smape: 0.3530 - val_ia: 0.6103 - val_loss: 0.0750 - val_mae: 0.2239 - val_rmse: 0.2521 - val_smape: 0.4517

Epoch 13/128

1147/1147 - 5s - 4ms/step - ia: 0.9009 - loss: 0.0444 - mae: 0.1587 - rmse: 0.2076 - smape: 0.3454 - val_ia: 0.6066 - val_loss: 0.0769 - val_mae: 0.2270 - val_rmse: 0.2552 - val_smape: 0.4528

Epoch 14/128

1147/1147 - 6s - 5ms/step - ia: 0.9049 - loss: 0.0417 - mae: 0.1525 - rmse: 0.2012 - smape: 0.3355 - val_ia: 0.6062 - val_loss: 0.0765 - val_mae: 0.2267 - val_rmse: 0.2551 - val_smape: 0.4496

Epoch 15/128

1147/1147 - 5s - 5ms/step - ia: 0.9068 - loss: 0.0399 - mae: 0.1495 - rmse: 0.1969 - smape: 0.3301 - val_ia: 0.5985 - val_loss: 0.0812 - val_mae: 0.2340 - val_rmse: 0.2623 - val_smape: 0.4591

Epoch 16/128

1147/1147 - 6s - 5ms/step - ia: 0.9081 - loss: 0.0387 - mae: 0.1471 - rmse: 0.1938 - smape: 0.3252 - val_ia: 0.6079 - val_loss: 0.0750 - val_mae: 0.2250 - val_rmse: 0.2526 - val_smape: 0.4383

Epoch 17/128

1147/1147 - 5s - 5ms/step - ia: 0.9111 - loss: 0.0366 - mae: 0.1428 - rmse: 0.1884 - smape: 0.3174 - val_ia: 0.5929 - val_loss: 0.0852 - val_mae: 0.2401 - val_rmse: 0.2684 - val_smape: 0.4659

Epoch 18/128

1147/1147 - 5s - 4ms/step - ia: 0.9127 - loss: 0.0354 - mae: 0.1401 - rmse: 0.1853 - smape: 0.3107 - val_ia: 0.5914 - val_loss: 0.0862 - val_mae: 0.2414 - val_rmse: 0.2695 - val_smape: 0.4646

Epoch 19/128

1147/1147 - 5s - 4ms/step - ia: 0.9144 - loss: 0.0341 - mae: 0.1375 - rmse: 0.1819 - smape: 0.3049 - val_ia: 0.5904 - val_loss: 0.0857 - val_mae: 0.2414 - val_rmse: 0.2691 - val_smape: 0.4657

Epoch 20/128

1147/1147 - 5s - 4ms/step - ia: 0.9155 - loss: 0.0332 - mae: 0.1356 - rmse: 0.1793 - smape: 0.3010 - val_ia: 0.5866 - val_loss: 0.0891 - val_mae: 0.2461 - val_rmse: 0.2740 - val_smape: 0.4679

Epoch 21/128

1147/1147 - 5s - 4ms/step - ia: 0.9170 - loss: 0.0323 - mae: 0.1332 - rmse: 0.1766 - smape: 0.2980 - val_ia: 0.5843 - val_loss: 0.0901 - val_mae: 0.2475 - val_rmse: 0.2758 - val_smape: 0.4699

Epoch 22/128

1147/1147 - 5s - 4ms/step - ia: 0.9186 - loss: 0.0309 - mae: 0.1309 - rmse: 0.1732 - smape: 0.2944 - val_ia: 0.5807 - val_loss: 0.0922 - val_mae: 0.2505 - val_rmse: 0.2789 - val_smape: 0.4693

Epoch 23/128

1147/1147 - 5s - 4ms/step - ia: 0.9193 - loss: 0.0305 - mae: 0.1297 - rmse: 0.1719 - smape: 0.2918 - val_ia: 0.5758 - val_loss: 0.0962 - val_mae: 0.2562 - val_rmse: 0.2845 - val_smape: 0.4813

Epoch 23: early stopping

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 21s 133ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 62%|██████▏   | 31/50 [2:27:57<1:36:00, 303.17s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2293/2293 - 11s - 5ms/step - ia: 0.8421 - loss: 0.1161 - mae: 0.2135 - rmse: 0.2685 - smape: 0.4579 - val_ia: 0.6719 - val_loss: 0.0189 - val_mae: 0.1012 - val_rmse: 0.1178 - val_smape: 0.2458

Epoch 2/128

2293/2293 - 10s - 4ms/step - ia: 0.9487 - loss: 0.0129 - mae: 0.0807 - rmse: 0.1078 - smape: 0.2175 - val_ia: 0.7270 - val_loss: 0.0107 - val_mae: 0.0763 - val_rmse: 0.0908 - val_smape: 0.1885

Epoch 3/128

2293/2293 - 10s - 5ms/step - ia: 0.9600 - loss: 0.0081 - mae: 0.0629 - rmse: 0.0847 - smape: 0.1805 - val_ia: 0.7465 - val_loss: 0.0086 - val_mae: 0.0685 - val_rmse: 0.0820 - val_smape: 0.1623

Epoch 4/128

2293/2293 - 6s - 3ms/step - ia: 0.9651 - loss: 0.0064 - mae: 0.0550 - rmse: 0.0744 - smape: 0.1645 - val_ia: 0.7609 - val_loss: 0.0069 - val_mae: 0.0621 - val_rmse: 0.0746 - val_smape: 0.1744

Epoch 5/128

2293/2293 - 12s - 5ms/step - ia: 0.9677 - loss: 0.0055 - mae: 0.0508 - rmse: 0.0689 - smape: 0.1563 - val_ia: 0.7845 - val_loss: 0.0055 - val_mae: 0.0541 - val_rmse: 0.0663 - val_smape: 0.1406

Epoch 6/128

2293/2293 - 7s - 3ms/step - ia: 0.9692 - loss: 0.0050 - mae: 0.0483 - rmse: 0.0656 - smape: 0.1514 - val_ia: 0.7924 - val_loss: 0.0051 - val_mae: 0.0526 - val_rmse: 0.0643 - val_smape: 0.1426

Epoch 7/128

2293/2293 - 7s - 3ms/step - ia: 0.9703 - loss: 0.0047 - mae: 0.0464 - rmse: 0.0629 - smape: 0.1476 - val_ia: 0.8012 - val_loss: 0.0045 - val_mae: 0.0495 - val_rmse: 0.0610 - val_smape: 0.1379

Epoch 8/128

2293/2293 - 11s - 5ms/step - ia: 0.9714 - loss: 0.0044 - mae: 0.0446 - rmse: 0.0608 - smape: 0.1445 - val_ia: 0.8067 - val_loss: 0.0044 - val_mae: 0.0493 - val_rmse: 0.0606 - val_smape: 0.1380

Epoch 9/128

2293/2293 - 10s - 4ms/step - ia: 0.9720 - loss: 0.0042 - mae: 0.0437 - rmse: 0.0594 - smape: 0.1420 - val_ia: 0.7967 - val_loss: 0.0045 - val_mae: 0.0493 - val_rmse: 0.0606 - val_smape: 0.1272

Epoch 10/128

2293/2293 - 9s - 4ms/step - ia: 0.9728 - loss: 0.0041 - mae: 0.0426 - rmse: 0.0579 - smape: 0.1408 - val_ia: 0.8042 - val_loss: 0.0043 - val_mae: 0.0488 - val_rmse: 0.0598 - val_smape: 0.1349

Epoch 11/128

2293/2293 - 4s - 2ms/step - ia: 0.9732 - loss: 0.0039 - mae: 0.0420 - rmse: 0.0570 - smape: 0.1396 - val_ia: 0.7913 - val_loss: 0.0046 - val_mae: 0.0510 - val_rmse: 0.0619 - val_smape: 0.1322

Epoch 12/128

2293/2293 - 4s - 2ms/step - ia: 0.9735 - loss: 0.0038 - mae: 0.0415 - rmse: 0.0563 - smape: 0.1391 - val_ia: 0.8003 - val_loss: 0.0046 - val_mae: 0.0513 - val_rmse: 0.0620 - val_smape: 0.1453

Epoch 13/128

2293/2293 - 4s - 2ms/step - ia: 0.9739 - loss: 0.0037 - mae: 0.0408 - rmse: 0.0555 - smape: 0.1369 - val_ia: 0.8072 - val_loss: 0.0042 - val_mae: 0.0481 - val_rmse: 0.0592 - val_smape: 0.1343

Epoch 14/128

2293/2293 - 4s - 2ms/step - ia: 0.9738 - loss: 0.0037 - mae: 0.0409 - rmse: 0.0554 - smape: 0.1369 - val_ia: 0.7951 - val_loss: 0.0046 - val_mae: 0.0504 - val_rmse: 0.0615 - val_smape: 0.1275

Epoch 15/128

2293/2293 - 5s - 2ms/step - ia: 0.9742 - loss: 0.0037 - mae: 0.0403 - rmse: 0.0548 - smape: 0.1359 - val_ia: 0.7900 - val_loss: 0.0044 - val_mae: 0.0502 - val_rmse: 0.0609 - val_smape: 0.1320

Epoch 16/128

2293/2293 - 4s - 2ms/step - ia: 0.9745 - loss: 0.0036 - mae: 0.0399 - rmse: 0.0542 - smape: 0.1356 - val_ia: 0.8021 - val_loss: 0.0043 - val_mae: 0.0479 - val_rmse: 0.0590 - val_smape: 0.1226

Epoch 17/128

2293/2293 - 5s - 2ms/step - ia: 0.9745 - loss: 0.0036 - mae: 0.0399 - rmse: 0.0539 - smape: 0.1358 - val_ia: 0.8143 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0563 - val_smape: 0.1240

Epoch 18/128

2293/2293 - 12s - 5ms/step - ia: 0.9748 - loss: 0.0035 - mae: 0.0394 - rmse: 0.0535 - smape: 0.1358 - val_ia: 0.7901 - val_loss: 0.0045 - val_mae: 0.0510 - val_rmse: 0.0616 - val_smape: 0.1422

Epoch 19/128

2293/2293 - 11s - 5ms/step - ia: 0.9748 - loss: 0.0035 - mae: 0.0394 - rmse: 0.0534 - smape: 0.1354 - val_ia: 0.7810 - val_loss: 0.0048 - val_mae: 0.0533 - val_rmse: 0.0636 - val_smape: 0.1439

Epoch 20/128

2293/2293 - 7s - 3ms/step - ia: 0.9751 - loss: 0.0035 - mae: 0.0390 - rmse: 0.0531 - smape: 0.1335 - val_ia: 0.8098 - val_loss: 0.0039 - val_mae: 0.0468 - val_rmse: 0.0574 - val_smape: 0.1334

Epoch 21/128

2293/2293 - 7s - 3ms/step - ia: 0.9750 - loss: 0.0035 - mae: 0.0391 - rmse: 0.0531 - smape: 0.1344 - val_ia: 0.7681 - val_loss: 0.0051 - val_mae: 0.0560 - val_rmse: 0.0661 - val_smape: 0.1550

Epoch 22/128

2293/2293 - 9s - 4ms/step - ia: 0.9753 - loss: 0.0034 - mae: 0.0388 - rmse: 0.0526 - smape: 0.1334 - val_ia: 0.8013 - val_loss: 0.0041 - val_mae: 0.0476 - val_rmse: 0.0582 - val_smape: 0.1243

Epoch 23/128

2293/2293 - 11s - 5ms/step - ia: 0.9752 - loss: 0.0034 - mae: 0.0388 - rmse: 0.0527 - smape: 0.1344 - val_ia: 0.8276 - val_loss: 0.0034 - val_mae: 0.0417 - val_rmse: 0.0525 - val_smape: 0.1187

Epoch 24/128

2293/2293 - 10s - 5ms/step - ia: 0.9752 - loss: 0.0034 - mae: 0.0387 - rmse: 0.0526 - smape: 0.1336 - val_ia: 0.7883 - val_loss: 0.0045 - val_mae: 0.0513 - val_rmse: 0.0616 - val_smape: 0.1386

Epoch 25/128

2293/2293 - 10s - 5ms/step - ia: 0.9753 - loss: 0.0034 - mae: 0.0386 - rmse: 0.0523 - smape: 0.1331 - val_ia: 0.8254 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0535 - val_smape: 0.1216

Epoch 26/128

2293/2293 - 10s - 4ms/step - ia: 0.9753 - loss: 0.0034 - mae: 0.0386 - rmse: 0.0524 - smape: 0.1330 - val_ia: 0.8242 - val_loss: 0.0036 - val_mae: 0.0429 - val_rmse: 0.0538 - val_smape: 0.1188

Epoch 27/128

2293/2293 - 10s - 4ms/step - ia: 0.9755 - loss: 0.0034 - mae: 0.0384 - rmse: 0.0523 - smape: 0.1327 - val_ia: 0.8224 - val_loss: 0.0036 - val_mae: 0.0449 - val_rmse: 0.0553 - val_smape: 0.1409

Epoch 28/128

2293/2293 - 11s - 5ms/step - ia: 0.9754 - loss: 0.0034 - mae: 0.0384 - rmse: 0.0521 - smape: 0.1331 - val_ia: 0.7734 - val_loss: 0.0050 - val_mae: 0.0553 - val_rmse: 0.0653 - val_smape: 0.1580

Epoch 29/128

2293/2293 - 10s - 5ms/step - ia: 0.9754 - loss: 0.0034 - mae: 0.0384 - rmse: 0.0521 - smape: 0.1334 - val_ia: 0.7907 - val_loss: 0.0042 - val_mae: 0.0496 - val_rmse: 0.0597 - val_smape: 0.1459

Epoch 30/128

2293/2293 - 7s - 3ms/step - ia: 0.9755 - loss: 0.0033 - mae: 0.0382 - rmse: 0.0519 - smape: 0.1335 - val_ia: 0.8233 - val_loss: 0.0034 - val_mae: 0.0426 - val_rmse: 0.0532 - val_smape: 0.1215

Epoch 31/128

2293/2293 - 10s - 4ms/step - ia: 0.9755 - loss: 0.0033 - mae: 0.0383 - rmse: 0.0518 - smape: 0.1337 - val_ia: 0.8132 - val_loss: 0.0039 - val_mae: 0.0460 - val_rmse: 0.0565 - val_smape: 0.1268

Epoch 32/128

2293/2293 - 7s - 3ms/step - ia: 0.9757 - loss: 0.0033 - mae: 0.0380 - rmse: 0.0517 - smape: 0.1329 - val_ia: 0.8080 - val_loss: 0.0037 - val_mae: 0.0457 - val_rmse: 0.0560 - val_smape: 0.1295

Epoch 33/128

2293/2293 - 10s - 4ms/step - ia: 0.9756 - loss: 0.0033 - mae: 0.0381 - rmse: 0.0517 - smape: 0.1323 - val_ia: 0.8308 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0516 - val_smape: 0.1163

Epoch 34/128

2293/2293 - 11s - 5ms/step - ia: 0.9754 - loss: 0.0033 - mae: 0.0382 - rmse: 0.0518 - smape: 0.1325 - val_ia: 0.7992 - val_loss: 0.0043 - val_mae: 0.0498 - val_rmse: 0.0598 - val_smape: 0.1552

Epoch 35/128

2293/2293 - 10s - 4ms/step - ia: 0.9757 - loss: 0.0033 - mae: 0.0379 - rmse: 0.0515 - smape: 0.1328 - val_ia: 0.8088 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0560 - val_smape: 0.1259

Epoch 36/128

2293/2293 - 11s - 5ms/step - ia: 0.9759 - loss: 0.0033 - mae: 0.0376 - rmse: 0.0512 - smape: 0.1318 - val_ia: 0.7918 - val_loss: 0.0043 - val_mae: 0.0505 - val_rmse: 0.0606 - val_smape: 0.1552

Epoch 37/128

2293/2293 - 10s - 5ms/step - ia: 0.9759 - loss: 0.0033 - mae: 0.0377 - rmse: 0.0513 - smape: 0.1317 - val_ia: 0.8307 - val_loss: 0.0033 - val_mae: 0.0414 - val_rmse: 0.0520 - val_smape: 0.1179

Epoch 38/128

2293/2293 - 10s - 5ms/step - ia: 0.9760 - loss: 0.0033 - mae: 0.0375 - rmse: 0.0510 - smape: 0.1324 - val_ia: 0.8373 - val_loss: 0.0033 - val_mae: 0.0407 - val_rmse: 0.0515 - val_smape: 0.1181

Epoch 39/128

2293/2293 - 10s - 4ms/step - ia: 0.9757 - loss: 0.0033 - mae: 0.0378 - rmse: 0.0512 - smape: 0.1334 - val_ia: 0.7955 - val_loss: 0.0042 - val_mae: 0.0496 - val_rmse: 0.0598 - val_smape: 0.1400

Epoch 40/128

2293/2293 - 10s - 5ms/step - ia: 0.9759 - loss: 0.0033 - mae: 0.0377 - rmse: 0.0512 - smape: 0.1314 - val_ia: 0.8093 - val_loss: 0.0036 - val_mae: 0.0456 - val_rmse: 0.0559 - val_smape: 0.1348

Epoch 41/128

2293/2293 - 8s - 4ms/step - ia: 0.9760 - loss: 0.0032 - mae: 0.0375 - rmse: 0.0510 - smape: 0.1314 - val_ia: 0.8174 - val_loss: 0.0036 - val_mae: 0.0451 - val_rmse: 0.0553 - val_smape: 0.1408

Epoch 42/128

2293/2293 - 7s - 3ms/step - ia: 0.9759 - loss: 0.0032 - mae: 0.0376 - rmse: 0.0511 - smape: 0.1317 - val_ia: 0.7993 - val_loss: 0.0039 - val_mae: 0.0474 - val_rmse: 0.0578 - val_smape: 0.1345

Epoch 43/128

2293/2293 - 7s - 3ms/step - ia: 0.9760 - loss: 0.0032 - mae: 0.0375 - rmse: 0.0511 - smape: 0.1313 - val_ia: 0.7991 - val_loss: 0.0041 - val_mae: 0.0491 - val_rmse: 0.0593 - val_smape: 0.1448

Epoch 44/128

2293/2293 - 8s - 4ms/step - ia: 0.9758 - loss: 0.0033 - mae: 0.0377 - rmse: 0.0512 - smape: 0.1327 - val_ia: 0.8247 - val_loss: 0.0034 - val_mae: 0.0427 - val_rmse: 0.0531 - val_smape: 0.1277

Epoch 45/128

2293/2293 - 4s - 2ms/step - ia: 0.9760 - loss: 0.0032 - mae: 0.0373 - rmse: 0.0507 - smape: 0.1315 - val_ia: 0.8277 - val_loss: 0.0034 - val_mae: 0.0429 - val_rmse: 0.0534 - val_smape: 0.1266

Epoch 46/128

2293/2293 - 4s - 2ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0374 - rmse: 0.0509 - smape: 0.1312 - val_ia: 0.7796 - val_loss: 0.0050 - val_mae: 0.0550 - val_rmse: 0.0648 - val_smape: 0.1703

Epoch 47/128

2293/2293 - 4s - 2ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0374 - rmse: 0.0509 - smape: 0.1323 - val_ia: 0.8172 - val_loss: 0.0035 - val_mae: 0.0440 - val_rmse: 0.0544 - val_smape: 0.1373

Epoch 48/128

2293/2293 - 4s - 2ms/step - ia: 0.9761 - loss: 0.0032 - mae: 0.0373 - rmse: 0.0508 - smape: 0.1315 - val_ia: 0.8159 - val_loss: 0.0036 - val_mae: 0.0441 - val_rmse: 0.0547 - val_smape: 0.1214

Epoch 48: early stopping

Restoring model weights from the end of the best epoch: 33.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/128

 64%|██████▍   | 32/50 [2:34:32<1:39:11, 330.67s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 4s - 25ms/step - ia: 0.8370 - loss: 0.1522 - mae: 0.2738 - rmse: 0.3539 - smape: 0.5212 - val_ia: 0.9188 - val_loss: 0.0215 - val_mae: 0.1052 - val_rmse: 0.1458 - val_smape: 0.2391

Epoch 2/128

144/144 - 1s - 4ms/step - ia: 0.9013 - loss: 0.0485 - mae: 0.1621 - rmse: 0.2194 - smape: 0.3360 - val_ia: 0.9433 - val_loss: 0.0105 - val_mae: 0.0757 - val_rmse: 0.1019 - val_smape: 0.1844

Epoch 3/128

144/144 - 1s - 5ms/step - ia: 0.9087 - loss: 0.0420 - mae: 0.1499 - rmse: 0.2045 - smape: 0.3046 - val_ia: 0.9406 - val_loss: 0.0111 - val_mae: 0.0826 - val_rmse: 0.1042 - val_smape: 0.2089

Epoch 4/128

144/144 - 0s - 3ms/step - ia: 0.9133 - loss: 0.0389 - mae: 0.1425 - rmse: 0.1968 - smape: 0.2903 - val_ia: 0.9555 - val_loss: 0.0066 - val_mae: 0.0597 - val_rmse: 0.0805 - val_smape: 0.1555

Epoch 5/128

144/144 - 1s - 5ms/step - ia: 0.9138 - loss: 0.0385 - mae: 0.1416 - rmse: 0.1956 - smape: 0.2857 - val_ia: 0.9518 - val_loss: 0.0080 - val_mae: 0.0648 - val_rmse: 0.0881 - val_smape: 0.1504

Epoch 6/128

144/144 - 0s - 3ms/step - ia: 0.9157 - loss: 0.0372 - mae: 0.1385 - rmse: 0.1922 - smape: 0.2774 - val_ia: 0.9413 - val_loss: 0.0103 - val_mae: 0.0808 - val_rmse: 0.1012 - val_smape: 0.2118

Epoch 7/128

144/144 - 1s - 4ms/step - ia: 0.9159 - loss: 0.0373 - mae: 0.1382 - rmse: 0.1924 - smape: 0.2734 - val_ia: 0.9576 - val_loss: 0.0062 - val_mae: 0.0568 - val_rmse: 0.0777 - val_smape: 0.1421

Epoch 8/128

144/144 - 1s - 4ms/step - ia: 0.9175 - loss: 0.0359 - mae: 0.1355 - rmse: 0.1889 - smape: 0.2688 - val_ia: 0.9549 - val_loss: 0.0061 - val_mae: 0.0606 - val_rmse: 0.0784 - val_smape: 0.1525

Epoch 9/128

144/144 - 0s - 3ms/step - ia: 0.9181 - loss: 0.0357 - mae: 0.1348 - rmse: 0.1880 - smape: 0.2645 - val_ia: 0.9472 - val_loss: 0.0083 - val_mae: 0.0716 - val_rmse: 0.0914 - val_smape: 0.1866

Epoch 10/128

144/144 - 0s - 3ms/step - ia: 0.9164 - loss: 0.0368 - mae: 0.1375 - rmse: 0.1909 - smape: 0.2707 - val_ia: 0.9433 - val_loss: 0.0097 - val_mae: 0.0760 - val_rmse: 0.0967 - val_smape: 0.1819

Epoch 11/128

144/144 - 1s - 4ms/step - ia: 0.9177 - loss: 0.0361 - mae: 0.1351 - rmse: 0.1894 - smape: 0.2626 - val_ia: 0.9571 - val_loss: 0.0062 - val_mae: 0.0577 - val_rmse: 0.0777 - val_smape: 0.1479

Epoch 12/128

144/144 - 1s - 4ms/step - ia: 0.9158 - loss: 0.0378 - mae: 0.1385 - rmse: 0.1934 - smape: 0.2671 - val_ia: 0.9460 - val_loss: 0.0088 - val_mae: 0.0724 - val_rmse: 0.0922 - val_smape: 0.1739

Epoch 13/128

144/144 - 1s - 4ms/step - ia: 0.9194 - loss: 0.0345 - mae: 0.1324 - rmse: 0.1851 - smape: 0.2576 - val_ia: 0.9552 - val_loss: 0.0058 - val_mae: 0.0603 - val_rmse: 0.0762 - val_smape: 0.1685

Epoch 14/128

144/144 - 1s - 5ms/step - ia: 0.9184 - loss: 0.0354 - mae: 0.1338 - rmse: 0.1877 - smape: 0.2603 - val_ia: 0.9607 - val_loss: 0.0055 - val_mae: 0.0528 - val_rmse: 0.0732 - val_smape: 0.1283

Epoch 15/128

144/144 - 1s - 6ms/step - ia: 0.9193 - loss: 0.0352 - mae: 0.1327 - rmse: 0.1870 - smape: 0.2582 - val_ia: 0.9127 - val_loss: 0.0198 - val_mae: 0.1136 - val_rmse: 0.1386 - val_smape: 0.2408

Epoch 16/128

144/144 - 1s - 10ms/step - ia: 0.9191 - loss: 0.0350 - mae: 0.1330 - rmse: 0.1863 - smape: 0.2605 - val_ia: 0.9615 - val_loss: 0.0048 - val_mae: 0.0517 - val_rmse: 0.0692 - val_smape: 0.1336

Epoch 17/128

144/144 - 1s - 7ms/step - ia: 0.9182 - loss: 0.0354 - mae: 0.1341 - rmse: 0.1876 - smape: 0.2626 - val_ia: 0.9510 - val_loss: 0.0070 - val_mae: 0.0654 - val_rmse: 0.0841 - val_smape: 0.1665

Epoch 18/128

144/144 - 1s - 7ms/step - ia: 0.9202 - loss: 0.0341 - mae: 0.1310 - rmse: 0.1845 - smape: 0.2528 - val_ia: 0.9516 - val_loss: 0.0070 - val_mae: 0.0667 - val_rmse: 0.0839 - val_smape: 0.1699

Epoch 19/128

144/144 - 2s - 10ms/step - ia: 0.9191 - loss: 0.0353 - mae: 0.1331 - rmse: 0.1868 - smape: 0.2580 - val_ia: 0.9599 - val_loss: 0.0057 - val_mae: 0.0541 - val_rmse: 0.0746 - val_smape: 0.1349

Epoch 20/128

144/144 - 1s - 10ms/step - ia: 0.9204 - loss: 0.0343 - mae: 0.1307 - rmse: 0.1845 - smape: 0.2510 - val_ia: 0.9578 - val_loss: 0.0053 - val_mae: 0.0562 - val_rmse: 0.0725 - val_smape: 0.1484

Epoch 21/128

144/144 - 1s - 8ms/step - ia: 0.9183 - loss: 0.0356 - mae: 0.1341 - rmse: 0.1879 - smape: 0.2577 - val_ia: 0.9601 - val_loss: 0.0051 - val_mae: 0.0533 - val_rmse: 0.0712 - val_smape: 0.1338

Epoch 22/128

144/144 - 2s - 11ms/step - ia: 0.9214 - loss: 0.0337 - mae: 0.1291 - rmse: 0.1830 - smape: 0.2501 - val_ia: 0.9524 - val_loss: 0.0074 - val_mae: 0.0635 - val_rmse: 0.0843 - val_smape: 0.1476

Epoch 23/128

144/144 - 1s - 6ms/step - ia: 0.9208 - loss: 0.0337 - mae: 0.1301 - rmse: 0.1832 - smape: 0.2531 - val_ia: 0.9473 - val_loss: 0.0082 - val_mae: 0.0696 - val_rmse: 0.0895 - val_smape: 0.1693

Epoch 24/128

144/144 - 1s - 9ms/step - ia: 0.9193 - loss: 0.0347 - mae: 0.1326 - rmse: 0.1857 - smape: 0.2578 - val_ia: 0.9477 - val_loss: 0.0080 - val_mae: 0.0696 - val_rmse: 0.0902 - val_smape: 0.1839

Epoch 25/128

144/144 - 1s - 8ms/step - ia: 0.9182 - loss: 0.0361 - mae: 0.1344 - rmse: 0.1893 - smape: 0.2557 - val_ia: 0.9587 - val_loss: 0.0054 - val_mae: 0.0553 - val_rmse: 0.0731 - val_smape: 0.1457

Epoch 26/128

144/144 - 1s - 5ms/step - ia: 0.9188 - loss: 0.0352 - mae: 0.1333 - rmse: 0.1870 - smape: 0.2572 - val_ia: 0.9538 - val_loss: 0.0074 - val_mae: 0.0625 - val_rmse: 0.0849 - val_smape: 0.1511

Epoch 27/128

144/144 - 2s - 11ms/step - ia: 0.9191 - loss: 0.0351 - mae: 0.1328 - rmse: 0.1868 - smape: 0.2559 - val_ia: 0.9558 - val_loss: 0.0066 - val_mae: 0.0591 - val_rmse: 0.0803 - val_smape: 0.1384

Epoch 28/128

144/144 - 1s - 6ms/step - ia: 0.9207 - loss: 0.0342 - mae: 0.1303 - rmse: 0.1845 - smape: 0.2527 - val_ia: 0.9423 - val_loss: 0.0097 - val_mae: 0.0785 - val_rmse: 0.0995 - val_smape: 0.1949

Epoch 29/128

144/144 - 1s - 6ms/step - ia: 0.9209 - loss: 0.0334 - mae: 0.1298 - rmse: 0.1824 - smape: 0.2520 - val_ia: 0.9550 - val_loss: 0.0060 - val_mae: 0.0612 - val_rmse: 0.0768 - val_smape: 0.1724

Epoch 30/128

144/144 - 1s - 6ms/step - ia: 0.9190 - loss: 0.0350 - mae: 0.1331 - rmse: 0.1864 - smape: 0.2602 - val_ia: 0.9512 - val_loss: 0.0069 - val_mae: 0.0661 - val_rmse: 0.0837 - val_smape: 0.1741

Epoch 31/128

144/144 - 1s - 4ms/step - ia: 0.9199 - loss: 0.0347 - mae: 0.1316 - rmse: 0.1856 - smape: 0.2515 - val_ia: 0.9442 - val_loss: 0.0096 - val_mae: 0.0744 - val_rmse: 0.0966 - val_smape: 0.1675

Epoch 31: early stopping

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/32

 66%|██████▌   | 33/50 [2:35:03<1:08:13, 240.80s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 31s - 27ms/step - ia: 0.9464 - loss: 0.0210 - mae: 0.0856 - rmse: 0.1141 - smape: 0.2418 - val_ia: 0.8085 - val_loss: 0.0131 - val_mae: 0.0876 - val_rmse: 0.1067 - val_smape: 0.2546

Epoch 2/32

1147/1147 - 8s - 7ms/step - ia: 0.9654 - loss: 0.0060 - mae: 0.0556 - rmse: 0.0740 - smape: 0.1770 - val_ia: 0.8566 - val_loss: 0.0071 - val_mae: 0.0632 - val_rmse: 0.0796 - val_smape: 0.1733

Epoch 3/32

1147/1147 - 11s - 9ms/step - ia: 0.9690 - loss: 0.0049 - mae: 0.0499 - rmse: 0.0666 - smape: 0.1640 - val_ia: 0.8653 - val_loss: 0.0064 - val_mae: 0.0603 - val_rmse: 0.0758 - val_smape: 0.1801

Epoch 4/32

1147/1147 - 7s - 6ms/step - ia: 0.9705 - loss: 0.0045 - mae: 0.0476 - rmse: 0.0636 - smape: 0.1576 - val_ia: 0.8216 - val_loss: 0.0098 - val_mae: 0.0795 - val_rmse: 0.0930 - val_smape: 0.2369

Epoch 5/32

1147/1147 - 9s - 8ms/step - ia: 0.9712 - loss: 0.0043 - mae: 0.0463 - rmse: 0.0618 - smape: 0.1538 - val_ia: 0.8860 - val_loss: 0.0049 - val_mae: 0.0508 - val_rmse: 0.0656 - val_smape: 0.1682

Epoch 6/32

1147/1147 - 5s - 5ms/step - ia: 0.9727 - loss: 0.0039 - mae: 0.0439 - rmse: 0.0589 - smape: 0.1490 - val_ia: 0.8725 - val_loss: 0.0056 - val_mae: 0.0566 - val_rmse: 0.0716 - val_smape: 0.1902

Epoch 7/32

1147/1147 - 5s - 5ms/step - ia: 0.9734 - loss: 0.0038 - mae: 0.0428 - rmse: 0.0576 - smape: 0.1456 - val_ia: 0.8636 - val_loss: 0.0053 - val_mae: 0.0559 - val_rmse: 0.0697 - val_smape: 0.1737

Epoch 8/32

1147/1147 - 10s - 9ms/step - ia: 0.9735 - loss: 0.0038 - mae: 0.0428 - rmse: 0.0576 - smape: 0.1459 - val_ia: 0.8804 - val_loss: 0.0047 - val_mae: 0.0508 - val_rmse: 0.0644 - val_smape: 0.1678

Epoch 9/32

1147/1147 - 5s - 5ms/step - ia: 0.9744 - loss: 0.0035 - mae: 0.0413 - rmse: 0.0556 - smape: 0.1423 - val_ia: 0.8921 - val_loss: 0.0041 - val_mae: 0.0459 - val_rmse: 0.0604 - val_smape: 0.1399

Epoch 10/32

1147/1147 - 5s - 4ms/step - ia: 0.9746 - loss: 0.0035 - mae: 0.0409 - rmse: 0.0553 - smape: 0.1395 - val_ia: 0.8636 - val_loss: 0.0054 - val_mae: 0.0556 - val_rmse: 0.0692 - val_smape: 0.1603

Epoch 11/32

1147/1147 - 5s - 5ms/step - ia: 0.9756 - loss: 0.0033 - mae: 0.0393 - rmse: 0.0533 - smape: 0.1378 - val_ia: 0.8743 - val_loss: 0.0048 - val_mae: 0.0522 - val_rmse: 0.0657 - val_smape: 0.1560

Epoch 12/32

1147/1147 - 5s - 4ms/step - ia: 0.9757 - loss: 0.0032 - mae: 0.0392 - rmse: 0.0530 - smape: 0.1373 - val_ia: 0.8431 - val_loss: 0.0076 - val_mae: 0.0695 - val_rmse: 0.0829 - val_smape: 0.1998

Epoch 13/32

1147/1147 - 5s - 4ms/step - ia: 0.9758 - loss: 0.0032 - mae: 0.0390 - rmse: 0.0530 - smape: 0.1347 - val_ia: 0.8851 - val_loss: 0.0044 - val_mae: 0.0498 - val_rmse: 0.0623 - val_smape: 0.1565

Epoch 14/32

1147/1147 - 4s - 4ms/step - ia: 0.9762 - loss: 0.0031 - mae: 0.0383 - rmse: 0.0521 - smape: 0.1346 - val_ia: 0.8965 - val_loss: 0.0036 - val_mae: 0.0449 - val_rmse: 0.0574 - val_smape: 0.1431

Epoch 15/32

1147/1147 - 6s - 5ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0379 - rmse: 0.0515 - smape: 0.1340 - val_ia: 0.8854 - val_loss: 0.0041 - val_mae: 0.0468 - val_rmse: 0.0599 - val_smape: 0.1406

Epoch 16/32

1147/1147 - 5s - 5ms/step - ia: 0.9768 - loss: 0.0030 - mae: 0.0373 - rmse: 0.0509 - smape: 0.1316 - val_ia: 0.8931 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0573 - val_smape: 0.1409

Epoch 17/32

1147/1147 - 6s - 5ms/step - ia: 0.9765 - loss: 0.0031 - mae: 0.0377 - rmse: 0.0515 - smape: 0.1317 - val_ia: 0.8940 - val_loss: 0.0037 - val_mae: 0.0446 - val_rmse: 0.0572 - val_smape: 0.1391

Epoch 18/32

1147/1147 - 5s - 5ms/step - ia: 0.9770 - loss: 0.0030 - mae: 0.0370 - rmse: 0.0505 - smape: 0.1316 - val_ia: 0.8898 - val_loss: 0.0037 - val_mae: 0.0449 - val_rmse: 0.0573 - val_smape: 0.1455

Epoch 19/32

1147/1147 - 5s - 5ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0363 - rmse: 0.0496 - smape: 0.1292 - val_ia: 0.8809 - val_loss: 0.0042 - val_mae: 0.0491 - val_rmse: 0.0608 - val_smape: 0.1499

Epoch 20/32

1147/1147 - 9s - 8ms/step - ia: 0.9776 - loss: 0.0029 - mae: 0.0361 - rmse: 0.0495 - smape: 0.1295 - val_ia: 0.9027 - val_loss: 0.0032 - val_mae: 0.0413 - val_rmse: 0.0537 - val_smape: 0.1384

Epoch 21/32

1147/1147 - 5s - 4ms/step - ia: 0.9775 - loss: 0.0029 - mae: 0.0363 - rmse: 0.0494 - smape: 0.1284 - val_ia: 0.9061 - val_loss: 0.0030 - val_mae: 0.0397 - val_rmse: 0.0518 - val_smape: 0.1294

Epoch 22/32

1147/1147 - 6s - 5ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0353 - rmse: 0.0486 - smape: 0.1272 - val_ia: 0.8969 - val_loss: 0.0042 - val_mae: 0.0480 - val_rmse: 0.0608 - val_smape: 0.1653

Epoch 23/32

1147/1147 - 5s - 5ms/step - ia: 0.9780 - loss: 0.0028 - mae: 0.0355 - rmse: 0.0488 - smape: 0.1285 - val_ia: 0.9111 - val_loss: 0.0028 - val_mae: 0.0382 - val_rmse: 0.0504 - val_smape: 0.1267

Epoch 24/32

1147/1147 - 5s - 5ms/step - ia: 0.9783 - loss: 0.0028 - mae: 0.0351 - rmse: 0.0482 - smape: 0.1262 - val_ia: 0.9014 - val_loss: 0.0033 - val_mae: 0.0426 - val_rmse: 0.0548 - val_smape: 0.1443

Epoch 25/32

1147/1147 - 5s - 4ms/step - ia: 0.9781 - loss: 0.0028 - mae: 0.0353 - rmse: 0.0485 - smape: 0.1259 - val_ia: 0.9069 - val_loss: 0.0031 - val_mae: 0.0406 - val_rmse: 0.0526 - val_smape: 0.1386

Epoch 26/32

1147/1147 - 5s - 4ms/step - ia: 0.9782 - loss: 0.0028 - mae: 0.0352 - rmse: 0.0483 - smape: 0.1260 - val_ia: 0.9081 - val_loss: 0.0031 - val_mae: 0.0397 - val_rmse: 0.0518 - val_smape: 0.1261

Epoch 27/32

1147/1147 - 5s - 5ms/step - ia: 0.9785 - loss: 0.0027 - mae: 0.0346 - rmse: 0.0475 - smape: 0.1245 - val_ia: 0.8974 - val_loss: 0.0035 - val_mae: 0.0439 - val_rmse: 0.0559 - val_smape: 0.1353

Epoch 28/32

1147/1147 - 4s - 4ms/step - ia: 0.9785 - loss: 0.0027 - mae: 0.0347 - rmse: 0.0476 - smape: 0.1257 - val_ia: 0.8936 - val_loss: 0.0035 - val_mae: 0.0439 - val_rmse: 0.0558 - val_smape: 0.1293

Epoch 29/32

1147/1147 - 6s - 6ms/step - ia: 0.9785 - loss: 0.0027 - mae: 0.0346 - rmse: 0.0476 - smape: 0.1244 - val_ia: 0.8977 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0535 - val_smape: 0.1291

Epoch 30/32

1147/1147 - 10s - 9ms/step - ia: 0.9786 - loss: 0.0027 - mae: 0.0345 - rmse: 0.0475 - smape: 0.1242 - val_ia: 0.9081 - val_loss: 0.0031 - val_mae: 0.0401 - val_rmse: 0.0524 - val_smape: 0.1378

Epoch 31/32

1147/1147 - 6s - 5ms/step - ia: 0.9787 - loss: 0.0026 - mae: 0.0343 - rmse: 0.0471 - smape: 0.1240 - val_ia: 0.8952 - val_loss: 0.0038 - val_mae: 0.0462 - val_rmse: 0.0578 - val_smape: 0.1412

Epoch 32/32

1147/1147 - 5s - 5ms/step - ia: 0.9788 - loss: 0.0026 - mae: 0.0341 - rmse: 0.0470 - smape: 0.1239 - val_ia: 0.9063 - val_loss: 0.0031 - val_mae: 0.0411 - val_rmse: 0.0534 - val_smape: 0.1373

Restoring model weights from the end of the best epoch: 23.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 51s 317ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 68%|██████▊   | 34/50 [2:38:47<1:02:55, 235.94s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1147/1147 - 14s - 12ms/step - ia: 0.8154 - loss: 0.1613 - mae: 0.2867 - rmse: 0.3762 - smape: 0.5463 - val_ia: 0.5478 - val_loss: 0.1367 - val_mae: 0.2937 - val_rmse: 0.3309 - val_smape: 0.5098

Epoch 2/32

1147/1147 - 9s - 8ms/step - ia: 0.8829 - loss: 0.0640 - mae: 0.1863 - rmse: 0.2489 - smape: 0.3663 - val_ia: 0.5499 - val_loss: 0.1293 - val_mae: 0.2868 - val_rmse: 0.3235 - val_smape: 0.4819

Epoch 3/32

1147/1147 - 5s - 4ms/step - ia: 0.8958 - loss: 0.0514 - mae: 0.1665 - rmse: 0.2234 - smape: 0.3295 - val_ia: 0.6036 - val_loss: 0.0910 - val_mae: 0.2364 - val_rmse: 0.2693 - val_smape: 0.3775

Epoch 4/32

1147/1147 - 4s - 4ms/step - ia: 0.9014 - loss: 0.0470 - mae: 0.1579 - rmse: 0.2133 - smape: 0.3179 - val_ia: 0.5782 - val_loss: 0.1194 - val_mae: 0.2663 - val_rmse: 0.3049 - val_smape: 0.4091

Epoch 5/32

1147/1147 - 5s - 4ms/step - ia: 0.9055 - loss: 0.0436 - mae: 0.1517 - rmse: 0.2051 - smape: 0.3117 - val_ia: 0.6412 - val_loss: 0.0728 - val_mae: 0.2062 - val_rmse: 0.2366 - val_smape: 0.3380

Epoch 6/32

1147/1147 - 4s - 4ms/step - ia: 0.9084 - loss: 0.0410 - mae: 0.1470 - rmse: 0.1991 - smape: 0.3114 - val_ia: 0.6324 - val_loss: 0.0787 - val_mae: 0.2151 - val_rmse: 0.2458 - val_smape: 0.3622

Epoch 7/32

1147/1147 - 6s - 5ms/step - ia: 0.9098 - loss: 0.0395 - mae: 0.1446 - rmse: 0.1953 - smape: 0.3128 - val_ia: 0.6974 - val_loss: 0.0548 - val_mae: 0.1667 - val_rmse: 0.1970 - val_smape: 0.2991

Epoch 8/32

1147/1147 - 10s - 9ms/step - ia: 0.9108 - loss: 0.0386 - mae: 0.1429 - rmse: 0.1927 - smape: 0.3063 - val_ia: 0.6749 - val_loss: 0.0626 - val_mae: 0.1816 - val_rmse: 0.2126 - val_smape: 0.3164

Epoch 9/32

1147/1147 - 6s - 5ms/step - ia: 0.9134 - loss: 0.0365 - mae: 0.1391 - rmse: 0.1877 - smape: 0.3024 - val_ia: 0.6674 - val_loss: 0.0638 - val_mae: 0.1868 - val_rmse: 0.2163 - val_smape: 0.3217

Epoch 10/32

1147/1147 - 6s - 5ms/step - ia: 0.9144 - loss: 0.0354 - mae: 0.1375 - rmse: 0.1848 - smape: 0.3009 - val_ia: 0.7157 - val_loss: 0.0420 - val_mae: 0.1509 - val_rmse: 0.1764 - val_smape: 0.3031

Epoch 11/32

1147/1147 - 6s - 5ms/step - ia: 0.9161 - loss: 0.0341 - mae: 0.1347 - rmse: 0.1812 - smape: 0.3009 - val_ia: 0.7652 - val_loss: 0.0294 - val_mae: 0.1204 - val_rmse: 0.1449 - val_smape: 0.2471

Epoch 12/32

1147/1147 - 10s - 9ms/step - ia: 0.9170 - loss: 0.0331 - mae: 0.1333 - rmse: 0.1788 - smape: 0.2972 - val_ia: 0.7089 - val_loss: 0.0421 - val_mae: 0.1531 - val_rmse: 0.1781 - val_smape: 0.2980

Epoch 13/32

1147/1147 - 6s - 5ms/step - ia: 0.9180 - loss: 0.0322 - mae: 0.1318 - rmse: 0.1763 - smape: 0.2940 - val_ia: 0.7639 - val_loss: 0.0291 - val_mae: 0.1200 - val_rmse: 0.1431 - val_smape: 0.2539

Epoch 14/32

1147/1147 - 6s - 5ms/step - ia: 0.9192 - loss: 0.0311 - mae: 0.1298 - rmse: 0.1735 - smape: 0.2940 - val_ia: 0.7866 - val_loss: 0.0189 - val_mae: 0.1011 - val_rmse: 0.1211 - val_smape: 0.2127

Epoch 15/32

1147/1147 - 6s - 5ms/step - ia: 0.9198 - loss: 0.0311 - mae: 0.1291 - rmse: 0.1730 - smape: 0.2935 - val_ia: 0.8159 - val_loss: 0.0153 - val_mae: 0.0888 - val_rmse: 0.1086 - val_smape: 0.2118

Epoch 16/32

1147/1147 - 5s - 5ms/step - ia: 0.9196 - loss: 0.0308 - mae: 0.1291 - rmse: 0.1724 - smape: 0.2950 - val_ia: 0.8199 - val_loss: 0.0142 - val_mae: 0.0841 - val_rmse: 0.1044 - val_smape: 0.2024

Epoch 17/32

1147/1147 - 5s - 5ms/step - ia: 0.9213 - loss: 0.0295 - mae: 0.1267 - rmse: 0.1688 - smape: 0.2893 - val_ia: 0.8038 - val_loss: 0.0168 - val_mae: 0.0948 - val_rmse: 0.1144 - val_smape: 0.2497

Epoch 18/32

1147/1147 - 11s - 9ms/step - ia: 0.9205 - loss: 0.0299 - mae: 0.1278 - rmse: 0.1699 - smape: 0.2938 - val_ia: 0.7818 - val_loss: 0.0159 - val_mae: 0.1017 - val_rmse: 0.1186 - val_smape: 0.2457

Epoch 19/32

1147/1147 - 10s - 9ms/step - ia: 0.9208 - loss: 0.0298 - mae: 0.1273 - rmse: 0.1695 - smape: 0.2937 - val_ia: 0.8000 - val_loss: 0.0146 - val_mae: 0.0948 - val_rmse: 0.1127 - val_smape: 0.2535

Epoch 20/32

1147/1147 - 11s - 9ms/step - ia: 0.9224 - loss: 0.0287 - mae: 0.1250 - rmse: 0.1664 - smape: 0.2911 - val_ia: 0.8036 - val_loss: 0.0144 - val_mae: 0.0903 - val_rmse: 0.1086 - val_smape: 0.1986

Epoch 21/32

1147/1147 - 9s - 7ms/step - ia: 0.9224 - loss: 0.0283 - mae: 0.1245 - rmse: 0.1653 - smape: 0.2908 - val_ia: 0.7766 - val_loss: 0.0217 - val_mae: 0.1076 - val_rmse: 0.1284 - val_smape: 0.2165

Epoch 22/32

1147/1147 - 7s - 6ms/step - ia: 0.9232 - loss: 0.0279 - mae: 0.1232 - rmse: 0.1640 - smape: 0.2870 - val_ia: 0.8059 - val_loss: 0.0158 - val_mae: 0.0912 - val_rmse: 0.1107 - val_smape: 0.1969

Epoch 23/32

1147/1147 - 6s - 5ms/step - ia: 0.9228 - loss: 0.0286 - mae: 0.1242 - rmse: 0.1657 - smape: 0.2886 - val_ia: 0.8359 - val_loss: 0.0131 - val_mae: 0.0783 - val_rmse: 0.0980 - val_smape: 0.1822

Epoch 24/32

1147/1147 - 5s - 5ms/step - ia: 0.9233 - loss: 0.0281 - mae: 0.1236 - rmse: 0.1644 - smape: 0.2872 - val_ia: 0.8113 - val_loss: 0.0200 - val_mae: 0.0936 - val_rmse: 0.1156 - val_smape: 0.1850

Epoch 25/32

1147/1147 - 6s - 5ms/step - ia: 0.9234 - loss: 0.0277 - mae: 0.1233 - rmse: 0.1636 - smape: 0.2887 - val_ia: 0.8126 - val_loss: 0.0163 - val_mae: 0.0905 - val_rmse: 0.1096 - val_smape: 0.2052

Epoch 26/32

1147/1147 - 6s - 5ms/step - ia: 0.9246 - loss: 0.0271 - mae: 0.1214 - rmse: 0.1615 - smape: 0.2857 - val_ia: 0.7880 - val_loss: 0.0198 - val_mae: 0.1021 - val_rmse: 0.1226 - val_smape: 0.2000

Epoch 27/32

1147/1147 - 6s - 5ms/step - ia: 0.9238 - loss: 0.0274 - mae: 0.1225 - rmse: 0.1625 - smape: 0.2867 - val_ia: 0.7890 - val_loss: 0.0174 - val_mae: 0.0999 - val_rmse: 0.1186 - val_smape: 0.2493

Epoch 28/32

1147/1147 - 10s - 9ms/step - ia: 0.9242 - loss: 0.0273 - mae: 0.1217 - rmse: 0.1622 - smape: 0.2850 - val_ia: 0.8138 - val_loss: 0.0166 - val_mae: 0.0891 - val_rmse: 0.1099 - val_smape: 0.1863

Epoch 29/32

1147/1147 - 10s - 9ms/step - ia: 0.9238 - loss: 0.0276 - mae: 0.1225 - rmse: 0.1630 - smape: 0.2855 - val_ia: 0.8151 - val_loss: 0.0151 - val_mae: 0.0878 - val_rmse: 0.1069 - val_smape: 0.1954

Epoch 30/32

1147/1147 - 6s - 5ms/step - ia: 0.9253 - loss: 0.0265 - mae: 0.1203 - rmse: 0.1598 - smape: 0.2834 - val_ia: 0.7863 - val_loss: 0.0182 - val_mae: 0.1015 - val_rmse: 0.1206 - val_smape: 0.2103

Epoch 31/32

1147/1147 - 6s - 5ms/step - ia: 0.9253 - loss: 0.0264 - mae: 0.1201 - rmse: 0.1596 - smape: 0.2820 - val_ia: 0.8237 - val_loss: 0.0122 - val_mae: 0.0816 - val_rmse: 0.0988 - val_smape: 0.1929

Epoch 32/32

1147/1147 - 10s - 9ms/step - ia: 0.9262 - loss: 0.0261 - mae: 0.1189 - rmse: 0.1584 - smape: 0.2789 - val_ia: 0.7808 - val_loss: 0.0171 - val_mae: 0.1028 - val_rmse: 0.1201 - val_smape: 0.2185

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 44s 276ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 70%|███████   | 35/50 [2:42:42<58:54, 235.62s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2293/2293 - 27s - 12ms/step - ia: 0.7475 - loss: 0.2534 - mae: 0.3681 - rmse: 0.4735 - smape: 0.6831 - val_ia: 0.3931 - val_loss: 0.1699 - val_mae: 0.3306 - val_rmse: 0.3529 - val_smape: 0.6247

Epoch 2/32

2293/2293 - 10s - 4ms/step - ia: 0.8491 - loss: 0.0972 - mae: 0.2304 - rmse: 0.3032 - smape: 0.4396 - val_ia: 0.3874 - val_loss: 0.1982 - val_mae: 0.3505 - val_rmse: 0.3750 - val_smape: 0.5617

Epoch 3/32

2293/2293 - 12s - 5ms/step - ia: 0.8731 - loss: 0.0706 - mae: 0.1961 - rmse: 0.2585 - smape: 0.3756 - val_ia: 0.3872 - val_loss: 0.2023 - val_mae: 0.3512 - val_rmse: 0.3763 - val_smape: 0.5622

Epoch 4/32

2293/2293 - 19s - 8ms/step - ia: 0.8843 - loss: 0.0600 - mae: 0.1796 - rmse: 0.2378 - smape: 0.3511 - val_ia: 0.3980 - val_loss: 0.1784 - val_mae: 0.3310 - val_rmse: 0.3544 - val_smape: 0.5483

Epoch 5/32

2293/2293 - 10s - 5ms/step - ia: 0.8921 - loss: 0.0535 - mae: 0.1684 - rmse: 0.2241 - smape: 0.3437 - val_ia: 0.4114 - val_loss: 0.1574 - val_mae: 0.3102 - val_rmse: 0.3320 - val_smape: 0.5565

Epoch 6/32

2293/2293 - 12s - 5ms/step - ia: 0.8958 - loss: 0.0495 - mae: 0.1627 - rmse: 0.2157 - smape: 0.3460 - val_ia: 0.4018 - val_loss: 0.1733 - val_mae: 0.3217 - val_rmse: 0.3442 - val_smape: 0.5755

Epoch 7/32

2293/2293 - 17s - 7ms/step - ia: 0.8990 - loss: 0.0459 - mae: 0.1573 - rmse: 0.2077 - smape: 0.3408 - val_ia: 0.4374 - val_loss: 0.1504 - val_mae: 0.2910 - val_rmse: 0.3140 - val_smape: 0.5058

Epoch 8/32

2293/2293 - 12s - 5ms/step - ia: 0.9006 - loss: 0.0446 - mae: 0.1551 - rmse: 0.2047 - smape: 0.3408 - val_ia: 0.4481 - val_loss: 0.1378 - val_mae: 0.2777 - val_rmse: 0.2995 - val_smape: 0.4798

Epoch 9/32

2293/2293 - 21s - 9ms/step - ia: 0.9039 - loss: 0.0421 - mae: 0.1505 - rmse: 0.1986 - smape: 0.3336 - val_ia: 0.4540 - val_loss: 0.1422 - val_mae: 0.2793 - val_rmse: 0.3015 - val_smape: 0.4832

Epoch 10/32

2293/2293 - 19s - 8ms/step - ia: 0.9048 - loss: 0.0408 - mae: 0.1489 - rmse: 0.1959 - smape: 0.3321 - val_ia: 0.5001 - val_loss: 0.1093 - val_mae: 0.2346 - val_rmse: 0.2576 - val_smape: 0.3785

Epoch 11/32

2293/2293 - 10s - 4ms/step - ia: 0.9056 - loss: 0.0402 - mae: 0.1475 - rmse: 0.1945 - smape: 0.3289 - val_ia: 0.5011 - val_loss: 0.1127 - val_mae: 0.2379 - val_rmse: 0.2601 - val_smape: 0.3761

Epoch 12/32

2293/2293 - 11s - 5ms/step - ia: 0.9076 - loss: 0.0384 - mae: 0.1447 - rmse: 0.1896 - smape: 0.3266 - val_ia: 0.5051 - val_loss: 0.1045 - val_mae: 0.2289 - val_rmse: 0.2507 - val_smape: 0.4000

Epoch 13/32

2293/2293 - 23s - 10ms/step - ia: 0.9083 - loss: 0.0377 - mae: 0.1435 - rmse: 0.1880 - smape: 0.3265 - val_ia: 0.5426 - val_loss: 0.0840 - val_mae: 0.2023 - val_rmse: 0.2229 - val_smape: 0.3448

Epoch 14/32

2293/2293 - 21s - 9ms/step - ia: 0.9094 - loss: 0.0370 - mae: 0.1419 - rmse: 0.1863 - smape: 0.3225 - val_ia: 0.4926 - val_loss: 0.0969 - val_mae: 0.2317 - val_rmse: 0.2500 - val_smape: 0.4137

Epoch 15/32

2293/2293 - 20s - 9ms/step - ia: 0.9100 - loss: 0.0363 - mae: 0.1405 - rmse: 0.1848 - smape: 0.3214 - val_ia: 0.5298 - val_loss: 0.0766 - val_mae: 0.2007 - val_rmse: 0.2193 - val_smape: 0.3655

Epoch 16/32

2293/2293 - 21s - 9ms/step - ia: 0.9123 - loss: 0.0344 - mae: 0.1374 - rmse: 0.1798 - smape: 0.3193 - val_ia: 0.5561 - val_loss: 0.0668 - val_mae: 0.1806 - val_rmse: 0.2003 - val_smape: 0.3424

Epoch 17/32

2293/2293 - 21s - 9ms/step - ia: 0.9138 - loss: 0.0334 - mae: 0.1345 - rmse: 0.1769 - smape: 0.3114 - val_ia: 0.5600 - val_loss: 0.0653 - val_mae: 0.1797 - val_rmse: 0.1990 - val_smape: 0.3199

Epoch 18/32

2293/2293 - 19s - 8ms/step - ia: 0.9145 - loss: 0.0327 - mae: 0.1339 - rmse: 0.1752 - smape: 0.3120 - val_ia: 0.5723 - val_loss: 0.0560 - val_mae: 0.1687 - val_rmse: 0.1872 - val_smape: 0.3091

Epoch 19/32

2293/2293 - 13s - 6ms/step - ia: 0.9144 - loss: 0.0332 - mae: 0.1341 - rmse: 0.1763 - smape: 0.3116 - val_ia: 0.5684 - val_loss: 0.0607 - val_mae: 0.1730 - val_rmse: 0.1912 - val_smape: 0.3163

Epoch 20/32

2293/2293 - 12s - 5ms/step - ia: 0.9155 - loss: 0.0320 - mae: 0.1319 - rmse: 0.1733 - smape: 0.3087 - val_ia: 0.5683 - val_loss: 0.0563 - val_mae: 0.1693 - val_rmse: 0.1879 - val_smape: 0.3144

Epoch 21/32

2293/2293 - 15s - 7ms/step - ia: 0.9168 - loss: 0.0313 - mae: 0.1305 - rmse: 0.1711 - smape: 0.3045 - val_ia: 0.5949 - val_loss: 0.0508 - val_mae: 0.1560 - val_rmse: 0.1744 - val_smape: 0.2857

Epoch 22/32

2293/2293 - 8s - 3ms/step - ia: 0.9178 - loss: 0.0304 - mae: 0.1289 - rmse: 0.1687 - smape: 0.2992 - val_ia: 0.5896 - val_loss: 0.0507 - val_mae: 0.1578 - val_rmse: 0.1756 - val_smape: 0.2647

Epoch 23/32

2293/2293 - 8s - 3ms/step - ia: 0.9183 - loss: 0.0299 - mae: 0.1277 - rmse: 0.1675 - smape: 0.2998 - val_ia: 0.5880 - val_loss: 0.0441 - val_mae: 0.1507 - val_rmse: 0.1682 - val_smape: 0.2809

Epoch 24/32

2293/2293 - 10s - 4ms/step - ia: 0.9193 - loss: 0.0292 - mae: 0.1264 - rmse: 0.1655 - smape: 0.2962 - val_ia: 0.5901 - val_loss: 0.0476 - val_mae: 0.1524 - val_rmse: 0.1703 - val_smape: 0.2685

Epoch 25/32

2293/2293 - 11s - 5ms/step - ia: 0.9196 - loss: 0.0293 - mae: 0.1261 - rmse: 0.1657 - smape: 0.2940 - val_ia: 0.5449 - val_loss: 0.0526 - val_mae: 0.1751 - val_rmse: 0.1903 - val_smape: 0.3289

Epoch 26/32

2293/2293 - 8s - 3ms/step - ia: 0.9214 - loss: 0.0283 - mae: 0.1236 - rmse: 0.1628 - smape: 0.2882 - val_ia: 0.5728 - val_loss: 0.0504 - val_mae: 0.1603 - val_rmse: 0.1775 - val_smape: 0.2811

Epoch 27/32

2293/2293 - 11s - 5ms/step - ia: 0.9212 - loss: 0.0280 - mae: 0.1234 - rmse: 0.1619 - smape: 0.2870 - val_ia: 0.5857 - val_loss: 0.0430 - val_mae: 0.1508 - val_rmse: 0.1673 - val_smape: 0.2856

Epoch 28/32

2293/2293 - 23s - 10ms/step - ia: 0.9220 - loss: 0.0277 - mae: 0.1226 - rmse: 0.1608 - smape: 0.2865 - val_ia: 0.5866 - val_loss: 0.0425 - val_mae: 0.1492 - val_rmse: 0.1665 - val_smape: 0.2654

Epoch 29/32

2293/2293 - 13s - 6ms/step - ia: 0.9222 - loss: 0.0273 - mae: 0.1220 - rmse: 0.1597 - smape: 0.2832 - val_ia: 0.6195 - val_loss: 0.0325 - val_mae: 0.1293 - val_rmse: 0.1446 - val_smape: 0.2468

Epoch 30/32

2293/2293 - 12s - 5ms/step - ia: 0.9227 - loss: 0.0270 - mae: 0.1212 - rmse: 0.1590 - smape: 0.2811 - val_ia: 0.6132 - val_loss: 0.0350 - val_mae: 0.1359 - val_rmse: 0.1517 - val_smape: 0.2395

Epoch 31/32

2293/2293 - 13s - 6ms/step - ia: 0.9228 - loss: 0.0268 - mae: 0.1209 - rmse: 0.1584 - smape: 0.2819 - val_ia: 0.6274 - val_loss: 0.0329 - val_mae: 0.1275 - val_rmse: 0.1434 - val_smape: 0.2256

Epoch 32/32

2293/2293 - 13s - 6ms/step - ia: 0.9240 - loss: 0.0260 - mae: 0.1191 - rmse: 0.1561 - smape: 0.2790 - val_ia: 0.6161 - val_loss: 0.0316 - val_mae: 0.1307 - val_rmse: 0.1451 - val_smape: 0.2549

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 43s 270ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 72%|███████▏  | 36/50 [2:50:42<1:12:05, 309.00s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

144/144 - 11s - 75ms/step - ia: 0.5205 - loss: 0.6791 - mae: 0.6709 - rmse: 0.8233 - smape: 1.2028 - val_ia: 0.4638 - val_loss: 0.7346 - val_mae: 0.7126 - val_rmse: 0.8234 - val_smape: 1.3256

Epoch 2/32

144/144 - 1s - 7ms/step - ia: 0.5479 - loss: 0.5925 - mae: 0.6234 - rmse: 0.7690 - smape: 1.1284 - val_ia: 0.4854 - val_loss: 0.6611 - val_mae: 0.6727 - val_rmse: 0.7808 - val_smape: 1.2742

Epoch 3/32

144/144 - 2s - 11ms/step - ia: 0.5745 - loss: 0.5226 - mae: 0.5829 - rmse: 0.7220 - smape: 1.0661 - val_ia: 0.5094 - val_loss: 0.5923 - val_mae: 0.6336 - val_rmse: 0.7390 - val_smape: 1.2170

Epoch 4/32

144/144 - 1s - 10ms/step - ia: 0.6012 - loss: 0.4611 - mae: 0.5463 - rmse: 0.6783 - smape: 1.0098 - val_ia: 0.5358 - val_loss: 0.5261 - val_mae: 0.5938 - val_rmse: 0.6969 - val_smape: 1.1595

Epoch 5/32

144/144 - 1s - 9ms/step - ia: 0.6298 - loss: 0.4026 - mae: 0.5107 - rmse: 0.6338 - smape: 0.9568 - val_ia: 0.5631 - val_loss: 0.4642 - val_mae: 0.5542 - val_rmse: 0.6559 - val_smape: 1.1061

Epoch 6/32

144/144 - 1s - 9ms/step - ia: 0.6611 - loss: 0.3468 - mae: 0.4744 - rmse: 0.5880 - smape: 0.9056 - val_ia: 0.5907 - val_loss: 0.4084 - val_mae: 0.5165 - val_rmse: 0.6174 - val_smape: 1.0593

Epoch 7/32

144/144 - 1s - 10ms/step - ia: 0.6921 - loss: 0.2964 - mae: 0.4384 - rmse: 0.5437 - smape: 0.8573 - val_ia: 0.6185 - val_loss: 0.3615 - val_mae: 0.4838 - val_rmse: 0.5837 - val_smape: 1.0209

Epoch 8/32

144/144 - 1s - 8ms/step - ia: 0.7189 - loss: 0.2574 - mae: 0.4069 - rmse: 0.5064 - smape: 0.8180 - val_ia: 0.6434 - val_loss: 0.3252 - val_mae: 0.4579 - val_rmse: 0.5562 - val_smape: 0.9906

Epoch 9/32

144/144 - 1s - 8ms/step - ia: 0.7405 - loss: 0.2293 - mae: 0.3820 - rmse: 0.4779 - smape: 0.7881 - val_ia: 0.6630 - val_loss: 0.2978 - val_mae: 0.4390 - val_rmse: 0.5341 - val_smape: 0.9665

Epoch 10/32

144/144 - 2s - 12ms/step - ia: 0.7577 - loss: 0.2082 - mae: 0.3615 - rmse: 0.4560 - smape: 0.7638 - val_ia: 0.6781 - val_loss: 0.2770 - val_mae: 0.4253 - val_rmse: 0.5166 - val_smape: 0.9483

Epoch 11/32

144/144 - 1s - 9ms/step - ia: 0.7715 - loss: 0.1920 - mae: 0.3446 - rmse: 0.4376 - smape: 0.7432 - val_ia: 0.6902 - val_loss: 0.2610 - val_mae: 0.4147 - val_rmse: 0.5023 - val_smape: 0.9331

Epoch 12/32

144/144 - 1s - 9ms/step - ia: 0.7836 - loss: 0.1790 - mae: 0.3301 - rmse: 0.4228 - smape: 0.7253 - val_ia: 0.6996 - val_loss: 0.2483 - val_mae: 0.4067 - val_rmse: 0.4905 - val_smape: 0.9202

Epoch 13/32

144/144 - 1s - 10ms/step - ia: 0.7936 - loss: 0.1683 - mae: 0.3175 - rmse: 0.4095 - smape: 0.7093 - val_ia: 0.7073 - val_loss: 0.2378 - val_mae: 0.4001 - val_rmse: 0.4803 - val_smape: 0.9078

Epoch 14/32

144/144 - 1s - 7ms/step - ia: 0.8021 - loss: 0.1590 - mae: 0.3064 - rmse: 0.3982 - smape: 0.6945 - val_ia: 0.7137 - val_loss: 0.2290 - val_mae: 0.3944 - val_rmse: 0.4711 - val_smape: 0.8959

Epoch 15/32

144/144 - 2s - 12ms/step - ia: 0.8097 - loss: 0.1508 - mae: 0.2964 - rmse: 0.3875 - smape: 0.6806 - val_ia: 0.7192 - val_loss: 0.2212 - val_mae: 0.3893 - val_rmse: 0.4628 - val_smape: 0.8838

Epoch 16/32

144/144 - 1s - 9ms/step - ia: 0.8159 - loss: 0.1434 - mae: 0.2874 - rmse: 0.3782 - smape: 0.6674 - val_ia: 0.7241 - val_loss: 0.2143 - val_mae: 0.3845 - val_rmse: 0.4550 - val_smape: 0.8724

Epoch 17/32

144/144 - 1s - 7ms/step - ia: 0.8221 - loss: 0.1364 - mae: 0.2792 - rmse: 0.3687 - smape: 0.6549 - val_ia: 0.7284 - val_loss: 0.2080 - val_mae: 0.3799 - val_rmse: 0.4475 - val_smape: 0.8618

Epoch 18/32

144/144 - 1s - 10ms/step - ia: 0.8273 - loss: 0.1299 - mae: 0.2715 - rmse: 0.3599 - smape: 0.6425 - val_ia: 0.7327 - val_loss: 0.2020 - val_mae: 0.3752 - val_rmse: 0.4402 - val_smape: 0.8515

Epoch 19/32

144/144 - 1s - 9ms/step - ia: 0.8321 - loss: 0.1237 - mae: 0.2643 - rmse: 0.3513 - smape: 0.6307 - val_ia: 0.7367 - val_loss: 0.1962 - val_mae: 0.3706 - val_rmse: 0.4330 - val_smape: 0.8414

Epoch 20/32

144/144 - 1s - 9ms/step - ia: 0.8369 - loss: 0.1178 - mae: 0.2573 - rmse: 0.3428 - smape: 0.6189 - val_ia: 0.7407 - val_loss: 0.1905 - val_mae: 0.3659 - val_rmse: 0.4259 - val_smape: 0.8322

Epoch 21/32

144/144 - 1s - 7ms/step - ia: 0.8413 - loss: 0.1121 - mae: 0.2505 - rmse: 0.3344 - smape: 0.6074 - val_ia: 0.7445 - val_loss: 0.1851 - val_mae: 0.3613 - val_rmse: 0.4189 - val_smape: 0.8225

Epoch 22/32

144/144 - 2s - 11ms/step - ia: 0.8458 - loss: 0.1068 - mae: 0.2439 - rmse: 0.3262 - smape: 0.5958 - val_ia: 0.7486 - val_loss: 0.1794 - val_mae: 0.3561 - val_rmse: 0.4115 - val_smape: 0.8138

Epoch 23/32

144/144 - 1s - 8ms/step - ia: 0.8502 - loss: 0.1017 - mae: 0.2375 - rmse: 0.3181 - smape: 0.5846 - val_ia: 0.7526 - val_loss: 0.1738 - val_mae: 0.3507 - val_rmse: 0.4042 - val_smape: 0.8053

Epoch 24/32

144/144 - 1s - 10ms/step - ia: 0.8542 - loss: 0.0969 - mae: 0.2313 - rmse: 0.3106 - smape: 0.5737 - val_ia: 0.7566 - val_loss: 0.1683 - val_mae: 0.3452 - val_rmse: 0.3969 - val_smape: 0.7967

Epoch 25/32

144/144 - 1s - 9ms/step - ia: 0.8586 - loss: 0.0923 - mae: 0.2253 - rmse: 0.3028 - smape: 0.5628 - val_ia: 0.7606 - val_loss: 0.1627 - val_mae: 0.3394 - val_rmse: 0.3895 - val_smape: 0.7874

Epoch 26/32

144/144 - 1s - 9ms/step - ia: 0.8621 - loss: 0.0879 - mae: 0.2194 - rmse: 0.2960 - smape: 0.5519 - val_ia: 0.7648 - val_loss: 0.1571 - val_mae: 0.3331 - val_rmse: 0.3819 - val_smape: 0.7770

Epoch 27/32

144/144 - 1s - 10ms/step - ia: 0.8660 - loss: 0.0838 - mae: 0.2138 - rmse: 0.2889 - smape: 0.5412 - val_ia: 0.7693 - val_loss: 0.1513 - val_mae: 0.3262 - val_rmse: 0.3741 - val_smape: 0.7659

Epoch 28/32

144/144 - 1s - 5ms/step - ia: 0.8691 - loss: 0.0799 - mae: 0.2082 - rmse: 0.2824 - smape: 0.5310 - val_ia: 0.7738 - val_loss: 0.1457 - val_mae: 0.3194 - val_rmse: 0.3666 - val_smape: 0.7534

Epoch 29/32

144/144 - 1s - 10ms/step - ia: 0.8731 - loss: 0.0761 - mae: 0.2029 - rmse: 0.2751 - smape: 0.5209 - val_ia: 0.7787 - val_loss: 0.1399 - val_mae: 0.3117 - val_rmse: 0.3586 - val_smape: 0.7385

Epoch 30/32

144/144 - 1s - 7ms/step - ia: 0.8764 - loss: 0.0726 - mae: 0.1977 - rmse: 0.2690 - smape: 0.5108 - val_ia: 0.7833 - val_loss: 0.1346 - val_mae: 0.3046 - val_rmse: 0.3512 - val_smape: 0.7226

Epoch 31/32

144/144 - 2s - 11ms/step - ia: 0.8797 - loss: 0.0693 - mae: 0.1928 - rmse: 0.2625 - smape: 0.5014 - val_ia: 0.7882 - val_loss: 0.1291 - val_mae: 0.2970 - val_rmse: 0.3436 - val_smape: 0.7050

Epoch 32/32

144/144 - 1s - 8ms/step - ia: 0.8825 - loss: 0.0663 - mae: 0.1882 - rmse: 0.2568 - smape: 0.4921 - val_ia: 0.7929 - val_loss: 0.1239 - val_mae: 0.2897 - val_rmse: 0.3364 - val_smape: 0.6865

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 58s 361ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 74%|███████▍  | 37/50 [2:51:37<50:25, 232.69s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

574/574 - 14s - 25ms/step - ia: 0.8083 - loss: 0.1606 - mae: 0.2948 - rmse: 0.3724 - smape: 0.6228 - val_ia: 0.7888 - val_loss: 0.0641 - val_mae: 0.1983 - val_rmse: 0.2458 - val_smape: 0.4995

Epoch 2/32

574/574 - 3s - 6ms/step - ia: 0.9229 - loss: 0.0293 - mae: 0.1246 - rmse: 0.1680 - smape: 0.3443 - val_ia: 0.8299 - val_loss: 0.0422 - val_mae: 0.1553 - val_rmse: 0.1935 - val_smape: 0.3943

Epoch 3/32

574/574 - 3s - 5ms/step - ia: 0.9417 - loss: 0.0175 - mae: 0.0946 - rmse: 0.1304 - smape: 0.2713 - val_ia: 0.8493 - val_loss: 0.0347 - val_mae: 0.1391 - val_rmse: 0.1722 - val_smape: 0.3575

Epoch 4/32

574/574 - 2s - 4ms/step - ia: 0.9497 - loss: 0.0133 - mae: 0.0818 - rmse: 0.1135 - smape: 0.2435 - val_ia: 0.8676 - val_loss: 0.0287 - val_mae: 0.1245 - val_rmse: 0.1552 - val_smape: 0.3269

Epoch 5/32

574/574 - 3s - 5ms/step - ia: 0.9543 - loss: 0.0111 - mae: 0.0746 - rmse: 0.1032 - smape: 0.2283 - val_ia: 0.8816 - val_loss: 0.0235 - val_mae: 0.1126 - val_rmse: 0.1410 - val_smape: 0.3019

Epoch 6/32

574/574 - 3s - 5ms/step - ia: 0.9575 - loss: 0.0097 - mae: 0.0694 - rmse: 0.0962 - smape: 0.2169 - val_ia: 0.9000 - val_loss: 0.0182 - val_mae: 0.0972 - val_rmse: 0.1248 - val_smape: 0.2727

Epoch 7/32

574/574 - 3s - 4ms/step - ia: 0.9599 - loss: 0.0087 - mae: 0.0654 - rmse: 0.0908 - smape: 0.2073 - val_ia: 0.9047 - val_loss: 0.0165 - val_mae: 0.0926 - val_rmse: 0.1190 - val_smape: 0.2603

Epoch 8/32

574/574 - 2s - 4ms/step - ia: 0.9620 - loss: 0.0079 - mae: 0.0622 - rmse: 0.0866 - smape: 0.2003 - val_ia: 0.9101 - val_loss: 0.0148 - val_mae: 0.0881 - val_rmse: 0.1137 - val_smape: 0.2498

Epoch 9/32

574/574 - 4s - 6ms/step - ia: 0.9634 - loss: 0.0074 - mae: 0.0599 - rmse: 0.0835 - smape: 0.1943 - val_ia: 0.9146 - val_loss: 0.0134 - val_mae: 0.0837 - val_rmse: 0.1088 - val_smape: 0.2417

Epoch 10/32

574/574 - 5s - 9ms/step - ia: 0.9644 - loss: 0.0069 - mae: 0.0580 - rmse: 0.0811 - smape: 0.1900 - val_ia: 0.9140 - val_loss: 0.0133 - val_mae: 0.0840 - val_rmse: 0.1081 - val_smape: 0.2415

Epoch 11/32

574/574 - 5s - 9ms/step - ia: 0.9654 - loss: 0.0066 - mae: 0.0565 - rmse: 0.0788 - smape: 0.1856 - val_ia: 0.9224 - val_loss: 0.0111 - val_mae: 0.0762 - val_rmse: 0.1001 - val_smape: 0.2267

Epoch 12/32

574/574 - 5s - 8ms/step - ia: 0.9663 - loss: 0.0063 - mae: 0.0551 - rmse: 0.0768 - smape: 0.1817 - val_ia: 0.9254 - val_loss: 0.0103 - val_mae: 0.0734 - val_rmse: 0.0970 - val_smape: 0.2194

Epoch 13/32

574/574 - 5s - 10ms/step - ia: 0.9671 - loss: 0.0060 - mae: 0.0539 - rmse: 0.0751 - smape: 0.1789 - val_ia: 0.9274 - val_loss: 0.0100 - val_mae: 0.0717 - val_rmse: 0.0952 - val_smape: 0.2134

Epoch 14/32

574/574 - 5s - 9ms/step - ia: 0.9678 - loss: 0.0058 - mae: 0.0526 - rmse: 0.0736 - smape: 0.1750 - val_ia: 0.9263 - val_loss: 0.0098 - val_mae: 0.0723 - val_rmse: 0.0950 - val_smape: 0.2134

Epoch 15/32

574/574 - 5s - 9ms/step - ia: 0.9685 - loss: 0.0056 - mae: 0.0515 - rmse: 0.0721 - smape: 0.1723 - val_ia: 0.9268 - val_loss: 0.0099 - val_mae: 0.0726 - val_rmse: 0.0948 - val_smape: 0.2114

Epoch 16/32

574/574 - 2s - 4ms/step - ia: 0.9689 - loss: 0.0054 - mae: 0.0507 - rmse: 0.0710 - smape: 0.1699 - val_ia: 0.9280 - val_loss: 0.0095 - val_mae: 0.0712 - val_rmse: 0.0933 - val_smape: 0.2073

Epoch 17/32

574/574 - 3s - 5ms/step - ia: 0.9694 - loss: 0.0052 - mae: 0.0499 - rmse: 0.0698 - smape: 0.1681 - val_ia: 0.9341 - val_loss: 0.0083 - val_mae: 0.0650 - val_rmse: 0.0875 - val_smape: 0.1951

Epoch 18/32

574/574 - 6s - 10ms/step - ia: 0.9699 - loss: 0.0051 - mae: 0.0491 - rmse: 0.0688 - smape: 0.1659 - val_ia: 0.9345 - val_loss: 0.0081 - val_mae: 0.0648 - val_rmse: 0.0866 - val_smape: 0.1936

Epoch 19/32

574/574 - 3s - 6ms/step - ia: 0.9703 - loss: 0.0050 - mae: 0.0485 - rmse: 0.0680 - smape: 0.1642 - val_ia: 0.9313 - val_loss: 0.0086 - val_mae: 0.0680 - val_rmse: 0.0893 - val_smape: 0.1975

Epoch 20/32

574/574 - 5s - 9ms/step - ia: 0.9709 - loss: 0.0048 - mae: 0.0477 - rmse: 0.0670 - smape: 0.1620 - val_ia: 0.9351 - val_loss: 0.0078 - val_mae: 0.0640 - val_rmse: 0.0854 - val_smape: 0.1892

Epoch 21/32

574/574 - 5s - 9ms/step - ia: 0.9712 - loss: 0.0047 - mae: 0.0472 - rmse: 0.0661 - smape: 0.1605 - val_ia: 0.9352 - val_loss: 0.0078 - val_mae: 0.0641 - val_rmse: 0.0854 - val_smape: 0.1881

Epoch 22/32

574/574 - 3s - 6ms/step - ia: 0.9714 - loss: 0.0046 - mae: 0.0466 - rmse: 0.0655 - smape: 0.1585 - val_ia: 0.9349 - val_loss: 0.0078 - val_mae: 0.0642 - val_rmse: 0.0854 - val_smape: 0.1874

Epoch 23/32

574/574 - 5s - 8ms/step - ia: 0.9718 - loss: 0.0046 - mae: 0.0461 - rmse: 0.0648 - smape: 0.1571 - val_ia: 0.9370 - val_loss: 0.0073 - val_mae: 0.0619 - val_rmse: 0.0828 - val_smape: 0.1823

Epoch 24/32

574/574 - 3s - 5ms/step - ia: 0.9721 - loss: 0.0045 - mae: 0.0457 - rmse: 0.0642 - smape: 0.1564 - val_ia: 0.9379 - val_loss: 0.0073 - val_mae: 0.0616 - val_rmse: 0.0824 - val_smape: 0.1817

Epoch 25/32

574/574 - 2s - 4ms/step - ia: 0.9724 - loss: 0.0044 - mae: 0.0451 - rmse: 0.0634 - smape: 0.1551 - val_ia: 0.9416 - val_loss: 0.0066 - val_mae: 0.0579 - val_rmse: 0.0789 - val_smape: 0.1719

Epoch 26/32

574/574 - 2s - 3ms/step - ia: 0.9726 - loss: 0.0043 - mae: 0.0448 - rmse: 0.0630 - smape: 0.1537 - val_ia: 0.9383 - val_loss: 0.0071 - val_mae: 0.0612 - val_rmse: 0.0817 - val_smape: 0.1772

Epoch 27/32

574/574 - 2s - 3ms/step - ia: 0.9729 - loss: 0.0042 - mae: 0.0444 - rmse: 0.0625 - smape: 0.1530 - val_ia: 0.9409 - val_loss: 0.0067 - val_mae: 0.0584 - val_rmse: 0.0792 - val_smape: 0.1713

Epoch 28/32

574/574 - 4s - 7ms/step - ia: 0.9731 - loss: 0.0042 - mae: 0.0440 - rmse: 0.0619 - smape: 0.1524 - val_ia: 0.9400 - val_loss: 0.0067 - val_mae: 0.0592 - val_rmse: 0.0795 - val_smape: 0.1721

Epoch 29/32

574/574 - 3s - 5ms/step - ia: 0.9733 - loss: 0.0041 - mae: 0.0436 - rmse: 0.0615 - smape: 0.1510 - val_ia: 0.9418 - val_loss: 0.0065 - val_mae: 0.0576 - val_rmse: 0.0778 - val_smape: 0.1701

Epoch 30/32

574/574 - 5s - 9ms/step - ia: 0.9735 - loss: 0.0041 - mae: 0.0433 - rmse: 0.0610 - smape: 0.1501 - val_ia: 0.9408 - val_loss: 0.0066 - val_mae: 0.0589 - val_rmse: 0.0788 - val_smape: 0.1711

Epoch 31/32

574/574 - 3s - 6ms/step - ia: 0.9737 - loss: 0.0040 - mae: 0.0430 - rmse: 0.0606 - smape: 0.1496 - val_ia: 0.9423 - val_loss: 0.0064 - val_mae: 0.0576 - val_rmse: 0.0774 - val_smape: 0.1665

Epoch 32/32

574/574 - 3s - 5ms/step - ia: 0.9739 - loss: 0.0040 - mae: 0.0427 - rmse: 0.0601 - smape: 0.1493 - val_ia: 0.9419 - val_loss: 0.0064 - val_mae: 0.0577 - val_rmse: 0.0775 - val_smape: 0.1687

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 54s 334ms/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 76%|███████▌  | 38/50 [2:53:50<40:34, 202.85s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1147/1147 - 19s - 16ms/step - ia: 0.8665 - loss: 0.0945 - mae: 0.2084 - rmse: 0.2748 - smape: 0.4326 - val_ia: 0.7467 - val_loss: 0.0222 - val_mae: 0.1168 - val_rmse: 0.1411 - val_smape: 0.2818

Epoch 2/64

1147/1147 - 6s - 6ms/step - ia: 0.9181 - loss: 0.0326 - mae: 0.1314 - rmse: 0.1770 - smape: 0.2908 - val_ia: 0.7249 - val_loss: 0.0302 - val_mae: 0.1370 - val_rmse: 0.1583 - val_smape: 0.2679

Epoch 3/64

1147/1147 - 6s - 5ms/step - ia: 0.9274 - loss: 0.0261 - mae: 0.1166 - rmse: 0.1583 - smape: 0.2614 - val_ia: 0.7570 - val_loss: 0.0230 - val_mae: 0.1173 - val_rmse: 0.1377 - val_smape: 0.2455

Epoch 4/64

1147/1147 - 6s - 5ms/step - ia: 0.9315 - loss: 0.0236 - mae: 0.1104 - rmse: 0.1502 - smape: 0.2499 - val_ia: 0.7630 - val_loss: 0.0212 - val_mae: 0.1143 - val_rmse: 0.1331 - val_smape: 0.2250

Epoch 5/64

1147/1147 - 11s - 9ms/step - ia: 0.9347 - loss: 0.0215 - mae: 0.1052 - rmse: 0.1432 - smape: 0.2408 - val_ia: 0.7501 - val_loss: 0.0244 - val_mae: 0.1214 - val_rmse: 0.1409 - val_smape: 0.2269

Epoch 6/64

1147/1147 - 8s - 7ms/step - ia: 0.9371 - loss: 0.0199 - mae: 0.1012 - rmse: 0.1379 - smape: 0.2353 - val_ia: 0.7252 - val_loss: 0.0311 - val_mae: 0.1372 - val_rmse: 0.1571 - val_smape: 0.2603

Epoch 7/64

1147/1147 - 6s - 5ms/step - ia: 0.9382 - loss: 0.0194 - mae: 0.0997 - rmse: 0.1363 - smape: 0.2310 - val_ia: 0.7714 - val_loss: 0.0181 - val_mae: 0.1051 - val_rmse: 0.1232 - val_smape: 0.2316

Epoch 8/64

1147/1147 - 10s - 9ms/step - ia: 0.9390 - loss: 0.0190 - mae: 0.0985 - rmse: 0.1346 - smape: 0.2288 - val_ia: 0.6801 - val_loss: 0.0459 - val_mae: 0.1697 - val_rmse: 0.1917 - val_smape: 0.2853

Epoch 9/64

1147/1147 - 6s - 6ms/step - ia: 0.9408 - loss: 0.0179 - mae: 0.0954 - rmse: 0.1306 - smape: 0.2237 - val_ia: 0.7351 - val_loss: 0.0272 - val_mae: 0.1296 - val_rmse: 0.1493 - val_smape: 0.2284

Epoch 10/64

1147/1147 - 6s - 5ms/step - ia: 0.9414 - loss: 0.0177 - mae: 0.0945 - rmse: 0.1295 - smape: 0.2209 - val_ia: 0.7032 - val_loss: 0.0363 - val_mae: 0.1517 - val_rmse: 0.1717 - val_smape: 0.2613

Epoch 11/64

1147/1147 - 6s - 5ms/step - ia: 0.9418 - loss: 0.0174 - mae: 0.0939 - rmse: 0.1287 - smape: 0.2213 - val_ia: 0.7441 - val_loss: 0.0276 - val_mae: 0.1270 - val_rmse: 0.1465 - val_smape: 0.2197

Epoch 12/64

1147/1147 - 5s - 5ms/step - ia: 0.9422 - loss: 0.0172 - mae: 0.0931 - rmse: 0.1279 - smape: 0.2178 - val_ia: 0.7108 - val_loss: 0.0347 - val_mae: 0.1474 - val_rmse: 0.1677 - val_smape: 0.2608

Epoch 13/64

1147/1147 - 4s - 4ms/step - ia: 0.9429 - loss: 0.0167 - mae: 0.0921 - rmse: 0.1262 - smape: 0.2161 - val_ia: 0.7429 - val_loss: 0.0266 - val_mae: 0.1263 - val_rmse: 0.1459 - val_smape: 0.2224

Epoch 14/64

1147/1147 - 7s - 6ms/step - ia: 0.9432 - loss: 0.0165 - mae: 0.0914 - rmse: 0.1253 - smape: 0.2158 - val_ia: 0.7654 - val_loss: 0.0209 - val_mae: 0.1116 - val_rmse: 0.1304 - val_smape: 0.1994

Epoch 15/64

1147/1147 - 11s - 9ms/step - ia: 0.9442 - loss: 0.0161 - mae: 0.0900 - rmse: 0.1237 - smape: 0.2137 - val_ia: 0.7122 - val_loss: 0.0345 - val_mae: 0.1486 - val_rmse: 0.1674 - val_smape: 0.2685

Epoch 16/64

1147/1147 - 10s - 9ms/step - ia: 0.9444 - loss: 0.0159 - mae: 0.0896 - rmse: 0.1230 - smape: 0.2133 - val_ia: 0.7041 - val_loss: 0.0361 - val_mae: 0.1529 - val_rmse: 0.1716 - val_smape: 0.2747

Epoch 17/64

1147/1147 - 8s - 7ms/step - ia: 0.9449 - loss: 0.0157 - mae: 0.0889 - rmse: 0.1221 - smape: 0.2095 - val_ia: 0.7484 - val_loss: 0.0251 - val_mae: 0.1234 - val_rmse: 0.1425 - val_smape: 0.2160

Epoch 18/64

1147/1147 - 5s - 4ms/step - ia: 0.9452 - loss: 0.0156 - mae: 0.0885 - rmse: 0.1216 - smape: 0.2084 - val_ia: 0.7935 - val_loss: 0.0158 - val_mae: 0.0957 - val_rmse: 0.1133 - val_smape: 0.1978

Epoch 19/64

1147/1147 - 6s - 5ms/step - ia: 0.9451 - loss: 0.0157 - mae: 0.0886 - rmse: 0.1221 - smape: 0.2089 - val_ia: 0.7418 - val_loss: 0.0256 - val_mae: 0.1268 - val_rmse: 0.1447 - val_smape: 0.2363

Epoch 20/64

1147/1147 - 6s - 6ms/step - ia: 0.9462 - loss: 0.0150 - mae: 0.0869 - rmse: 0.1192 - smape: 0.2051 - val_ia: 0.7291 - val_loss: 0.0292 - val_mae: 0.1350 - val_rmse: 0.1531 - val_smape: 0.2558

Epoch 21/64

1147/1147 - 6s - 5ms/step - ia: 0.9462 - loss: 0.0152 - mae: 0.0871 - rmse: 0.1199 - smape: 0.2060 - val_ia: 0.7555 - val_loss: 0.0207 - val_mae: 0.1146 - val_rmse: 0.1300 - val_smape: 0.2249

Epoch 22/64

1147/1147 - 10s - 9ms/step - ia: 0.9465 - loss: 0.0148 - mae: 0.0862 - rmse: 0.1185 - smape: 0.2040 - val_ia: 0.7692 - val_loss: 0.0184 - val_mae: 0.1083 - val_rmse: 0.1244 - val_smape: 0.2103

Epoch 23/64

1147/1147 - 9s - 8ms/step - ia: 0.9460 - loss: 0.0152 - mae: 0.0872 - rmse: 0.1199 - smape: 0.2052 - val_ia: 0.7317 - val_loss: 0.0283 - val_mae: 0.1338 - val_rmse: 0.1522 - val_smape: 0.2398

Epoch 24/64

1147/1147 - 7s - 6ms/step - ia: 0.9463 - loss: 0.0149 - mae: 0.0865 - rmse: 0.1188 - smape: 0.2018 - val_ia: 0.7431 - val_loss: 0.0265 - val_mae: 0.1267 - val_rmse: 0.1458 - val_smape: 0.2190

Epoch 25/64

1147/1147 - 6s - 6ms/step - ia: 0.9470 - loss: 0.0148 - mae: 0.0856 - rmse: 0.1183 - smape: 0.2025 - val_ia: 0.7192 - val_loss: 0.0329 - val_mae: 0.1432 - val_rmse: 0.1629 - val_smape: 0.2366

Epoch 26/64

1147/1147 - 6s - 6ms/step - ia: 0.9471 - loss: 0.0145 - mae: 0.0851 - rmse: 0.1174 - smape: 0.1991 - val_ia: 0.7247 - val_loss: 0.0307 - val_mae: 0.1380 - val_rmse: 0.1578 - val_smape: 0.2290

Epoch 27/64

1147/1147 - 10s - 9ms/step - ia: 0.9479 - loss: 0.0142 - mae: 0.0842 - rmse: 0.1162 - smape: 0.1971 - val_ia: 0.7318 - val_loss: 0.0277 - val_mae: 0.1323 - val_rmse: 0.1494 - val_smape: 0.2411

Epoch 28/64

1147/1147 - 9s - 8ms/step - ia: 0.9472 - loss: 0.0147 - mae: 0.0853 - rmse: 0.1177 - smape: 0.2004 - val_ia: 0.7204 - val_loss: 0.0320 - val_mae: 0.1416 - val_rmse: 0.1610 - val_smape: 0.2444

Epoch 29/64

1147/1147 - 8s - 7ms/step - ia: 0.9475 - loss: 0.0146 - mae: 0.0848 - rmse: 0.1173 - smape: 0.1975 - val_ia: 0.7244 - val_loss: 0.0294 - val_mae: 0.1369 - val_rmse: 0.1550 - val_smape: 0.2487

Epoch 30/64

1147/1147 - 6s - 5ms/step - ia: 0.9480 - loss: 0.0143 - mae: 0.0841 - rmse: 0.1161 - smape: 0.1977 - val_ia: 0.6925 - val_loss: 0.0414 - val_mae: 0.1621 - val_rmse: 0.1831 - val_smape: 0.2692

Epoch 31/64

1147/1147 - 11s - 10ms/step - ia: 0.9479 - loss: 0.0142 - mae: 0.0841 - rmse: 0.1160 - smape: 0.1965 - val_ia: 0.7062 - val_loss: 0.0367 - val_mae: 0.1524 - val_rmse: 0.1720 - val_smape: 0.2523

Epoch 32/64

1147/1147 - 6s - 5ms/step - ia: 0.9470 - loss: 0.0147 - mae: 0.0855 - rmse: 0.1179 - smape: 0.1992 - val_ia: 0.7558 - val_loss: 0.0219 - val_mae: 0.1161 - val_rmse: 0.1340 - val_smape: 0.2129

Epoch 33/64

1147/1147 - 9s - 8ms/step - ia: 0.9481 - loss: 0.0140 - mae: 0.0837 - rmse: 0.1153 - smape: 0.1962 - val_ia: 0.7688 - val_loss: 0.0211 - val_mae: 0.1116 - val_rmse: 0.1294 - val_smape: 0.2072

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 50s 312ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 78%|███████▊  | 39/50 [2:58:13<40:28, 220.75s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2293/2293 - 11s - 5ms/step - ia: 0.6091 - loss: 0.4756 - mae: 0.5136 - rmse: 0.6678 - smape: 0.9442 - val_ia: 0.4125 - val_loss: 0.1554 - val_mae: 0.3007 - val_rmse: 0.3238 - val_smape: 0.5368

Epoch 2/32

2293/2293 - 6s - 3ms/step - ia: 0.6644 - loss: 0.3816 - mae: 0.4570 - rmse: 0.6024 - smape: 0.8452 - val_ia: 0.4486 - val_loss: 0.1332 - val_mae: 0.2748 - val_rmse: 0.2967 - val_smape: 0.4861

Epoch 3/32

2293/2293 - 5s - 2ms/step - ia: 0.6645 - loss: 0.3776 - mae: 0.4549 - rmse: 0.5998 - smape: 0.8451 - val_ia: 0.4068 - val_loss: 0.1607 - val_mae: 0.3098 - val_rmse: 0.3331 - val_smape: 0.5562

Epoch 4/32

2293/2293 - 5s - 2ms/step - ia: 0.6679 - loss: 0.3750 - mae: 0.4518 - rmse: 0.5978 - smape: 0.8420 - val_ia: 0.4279 - val_loss: 0.1405 - val_mae: 0.2874 - val_rmse: 0.3096 - val_smape: 0.5295

Epoch 5/32

2293/2293 - 5s - 2ms/step - ia: 0.6662 - loss: 0.3789 - mae: 0.4535 - rmse: 0.6004 - smape: 0.8420 - val_ia: 0.3927 - val_loss: 0.1852 - val_mae: 0.3350 - val_rmse: 0.3574 - val_smape: 0.6873

Epoch 6/32

2293/2293 - 5s - 2ms/step - ia: 0.6728 - loss: 0.3695 - mae: 0.4472 - rmse: 0.5927 - smape: 0.8373 - val_ia: 0.3981 - val_loss: 0.1718 - val_mae: 0.3231 - val_rmse: 0.3452 - val_smape: 0.6711

Epoch 7/32

2293/2293 - 10s - 4ms/step - ia: 0.6719 - loss: 0.3691 - mae: 0.4480 - rmse: 0.5923 - smape: 0.8369 - val_ia: 0.4028 - val_loss: 0.1683 - val_mae: 0.3181 - val_rmse: 0.3408 - val_smape: 0.5742

Epoch 8/32

2293/2293 - 12s - 5ms/step - ia: 0.6739 - loss: 0.3671 - mae: 0.4455 - rmse: 0.5909 - smape: 0.8329 - val_ia: 0.4121 - val_loss: 0.1689 - val_mae: 0.3164 - val_rmse: 0.3392 - val_smape: 0.6148

Epoch 9/32

2293/2293 - 19s - 8ms/step - ia: 0.6715 - loss: 0.3753 - mae: 0.4488 - rmse: 0.5962 - smape: 0.8374 - val_ia: 0.3908 - val_loss: 0.2021 - val_mae: 0.3482 - val_rmse: 0.3725 - val_smape: 0.6793

Epoch 10/32

2293/2293 - 10s - 4ms/step - ia: 0.6721 - loss: 0.3705 - mae: 0.4477 - rmse: 0.5939 - smape: 0.8382 - val_ia: 0.3981 - val_loss: 0.1923 - val_mae: 0.3386 - val_rmse: 0.3620 - val_smape: 0.7143

Epoch 11/32

2293/2293 - 11s - 5ms/step - ia: 0.6732 - loss: 0.3704 - mae: 0.4455 - rmse: 0.5930 - smape: 0.8297 - val_ia: 0.4386 - val_loss: 0.1180 - val_mae: 0.2665 - val_rmse: 0.2871 - val_smape: 0.5253

Epoch 12/32

2293/2293 - 10s - 4ms/step - ia: 0.6720 - loss: 0.3696 - mae: 0.4475 - rmse: 0.5928 - smape: 0.8392 - val_ia: 0.3873 - val_loss: 0.2077 - val_mae: 0.3501 - val_rmse: 0.3749 - val_smape: 0.6652

Epoch 13/32

2293/2293 - 11s - 5ms/step - ia: 0.6713 - loss: 0.3717 - mae: 0.4478 - rmse: 0.5942 - smape: 0.8406 - val_ia: 0.3945 - val_loss: 0.1644 - val_mae: 0.3188 - val_rmse: 0.3412 - val_smape: 0.6001

Epoch 14/32

2293/2293 - 21s - 9ms/step - ia: 0.6704 - loss: 0.3723 - mae: 0.4487 - rmse: 0.5952 - smape: 0.8415 - val_ia: 0.4098 - val_loss: 0.1542 - val_mae: 0.3049 - val_rmse: 0.3270 - val_smape: 0.5730

Epoch 15/32

2293/2293 - 12s - 5ms/step - ia: 0.6708 - loss: 0.3730 - mae: 0.4483 - rmse: 0.5956 - smape: 0.8378 - val_ia: 0.3879 - val_loss: 0.1940 - val_mae: 0.3416 - val_rmse: 0.3653 - val_smape: 0.6937

Epoch 16/32

2293/2293 - 9s - 4ms/step - ia: 0.6729 - loss: 0.3678 - mae: 0.4457 - rmse: 0.5912 - smape: 0.8311 - val_ia: 0.4177 - val_loss: 0.1545 - val_mae: 0.3008 - val_rmse: 0.3238 - val_smape: 0.5502

Epoch 17/32

2293/2293 - 13s - 6ms/step - ia: 0.6721 - loss: 0.3698 - mae: 0.4476 - rmse: 0.5931 - smape: 0.8376 - val_ia: 0.3911 - val_loss: 0.1963 - val_mae: 0.3433 - val_rmse: 0.3679 - val_smape: 0.6596

Epoch 18/32

2293/2293 - 20s - 9ms/step - ia: 0.6723 - loss: 0.3705 - mae: 0.4469 - rmse: 0.5935 - smape: 0.8300 - val_ia: 0.4040 - val_loss: 0.1810 - val_mae: 0.3248 - val_rmse: 0.3490 - val_smape: 0.6187

Epoch 19/32

2293/2293 - 7s - 3ms/step - ia: 0.6738 - loss: 0.3654 - mae: 0.4457 - rmse: 0.5900 - smape: 0.8322 - val_ia: 0.4005 - val_loss: 0.2010 - val_mae: 0.3397 - val_rmse: 0.3644 - val_smape: 0.6846

Epoch 20/32

2293/2293 - 15s - 7ms/step - ia: 0.6734 - loss: 0.3712 - mae: 0.4460 - rmse: 0.5941 - smape: 0.8291 - val_ia: 0.4082 - val_loss: 0.1487 - val_mae: 0.3028 - val_rmse: 0.3244 - val_smape: 0.5924

Epoch 21/32

2293/2293 - 11s - 5ms/step - ia: 0.6730 - loss: 0.3699 - mae: 0.4465 - rmse: 0.5933 - smape: 0.8326 - val_ia: 0.4070 - val_loss: 0.1774 - val_mae: 0.3227 - val_rmse: 0.3467 - val_smape: 0.5774

Epoch 22/32

2293/2293 - 16s - 7ms/step - ia: 0.6742 - loss: 0.3662 - mae: 0.4451 - rmse: 0.5902 - smape: 0.8362 - val_ia: 0.4252 - val_loss: 0.1543 - val_mae: 0.2996 - val_rmse: 0.3226 - val_smape: 0.5603

Epoch 23/32

2293/2293 - 11s - 5ms/step - ia: 0.6734 - loss: 0.3698 - mae: 0.4463 - rmse: 0.5925 - smape: 0.8359 - val_ia: 0.4014 - val_loss: 0.1736 - val_mae: 0.3251 - val_rmse: 0.3468 - val_smape: 0.6017

Epoch 24/32

2293/2293 - 9s - 4ms/step - ia: 0.6696 - loss: 0.3750 - mae: 0.4497 - rmse: 0.5969 - smape: 0.8399 - val_ia: 0.3732 - val_loss: 0.2689 - val_mae: 0.3914 - val_rmse: 0.4194 - val_smape: 0.8369

Epoch 25/32

2293/2293 - 12s - 5ms/step - ia: 0.6751 - loss: 0.3675 - mae: 0.4439 - rmse: 0.5907 - smape: 0.8343 - val_ia: 0.4058 - val_loss: 0.1540 - val_mae: 0.3062 - val_rmse: 0.3286 - val_smape: 0.5916

Epoch 26/32

2293/2293 - 20s - 9ms/step - ia: 0.6722 - loss: 0.3703 - mae: 0.4464 - rmse: 0.5928 - smape: 0.8358 - val_ia: 0.3920 - val_loss: 0.1736 - val_mae: 0.3254 - val_rmse: 0.3481 - val_smape: 0.6036

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 36s 222ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 80%|████████  | 40/50 [3:03:11<40:41, 244.13s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

4586/4586 - 33s - 7ms/step - ia: 0.8603 - loss: 0.0855 - mae: 0.2044 - rmse: 0.2641 - smape: 0.3935 - val_ia: 0.3799 - val_loss: 0.0422 - val_mae: 0.1693 - val_rmse: 0.1789 - val_smape: 0.3782

Epoch 2/8

4586/4586 - 34s - 7ms/step - ia: 0.8811 - loss: 0.0581 - mae: 0.1745 - rmse: 0.2262 - smape: 0.3376 - val_ia: 0.4747 - val_loss: 0.0200 - val_mae: 0.1094 - val_rmse: 0.1191 - val_smape: 0.2462

Epoch 3/8

4586/4586 - 28s - 6ms/step - ia: 0.8849 - loss: 0.0538 - mae: 0.1689 - rmse: 0.2178 - smape: 0.3417 - val_ia: 0.4427 - val_loss: 0.0293 - val_mae: 0.1328 - val_rmse: 0.1426 - val_smape: 0.2921

Epoch 4/8

4586/4586 - 36s - 8ms/step - ia: 0.8868 - loss: 0.0516 - mae: 0.1660 - rmse: 0.2136 - smape: 0.3467 - val_ia: 0.5136 - val_loss: 0.0148 - val_mae: 0.0948 - val_rmse: 0.1038 - val_smape: 0.2355

Epoch 5/8

4586/4586 - 23s - 5ms/step - ia: 0.8859 - loss: 0.0517 - mae: 0.1672 - rmse: 0.2136 - smape: 0.3541 - val_ia: 0.4392 - val_loss: 0.0299 - val_mae: 0.1382 - val_rmse: 0.1464 - val_smape: 0.3723

Epoch 6/8

4586/4586 - 43s - 9ms/step - ia: 0.8876 - loss: 0.0503 - mae: 0.1653 - rmse: 0.2115 - smape: 0.3552 - val_ia: 0.4061 - val_loss: 0.0597 - val_mae: 0.1876 - val_rmse: 0.1957 - val_smape: 0.3930

Epoch 7/8

4586/4586 - 38s - 8ms/step - ia: 0.8883 - loss: 0.0490 - mae: 0.1639 - rmse: 0.2084 - smape: 0.3542 - val_ia: 0.4335 - val_loss: 0.0358 - val_mae: 0.1489 - val_rmse: 0.1582 - val_smape: 0.2708

Epoch 8/8

4586/4586 - 23s - 5ms/step - ia: 0.8874 - loss: 0.0496 - mae: 0.1646 - rmse: 0.2099 - smape: 0.3568 - val_ia: 0.4556 - val_loss: 0.0263 - val_mae: 0.1244 - val_rmse: 0.1339 - val_smape: 0.2679

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 42s 262ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 82%|████████▏ | 41/50 [3:07:32<37:22, 249.20s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 18s - 126ms/step - ia: 0.7223 - loss: 0.3665 - mae: 0.4686 - rmse: 0.5932 - smape: 0.7786 - val_ia: 0.8920 - val_loss: 0.0390 - val_mae: 0.1530 - val_rmse: 0.1945 - val_smape: 0.3561

Epoch 2/256

144/144 - 1s - 10ms/step - ia: 0.8029 - loss: 0.1781 - mae: 0.3275 - rmse: 0.4205 - smape: 0.6160 - val_ia: 0.9148 - val_loss: 0.0234 - val_mae: 0.1157 - val_rmse: 0.1510 - val_smape: 0.2699

Epoch 3/256

144/144 - 2s - 16ms/step - ia: 0.8371 - loss: 0.1224 - mae: 0.2689 - rmse: 0.3488 - smape: 0.5305 - val_ia: 0.9230 - val_loss: 0.0180 - val_mae: 0.1023 - val_rmse: 0.1339 - val_smape: 0.2618

Epoch 4/256

144/144 - 1s - 10ms/step - ia: 0.8575 - loss: 0.0949 - mae: 0.2344 - rmse: 0.3072 - smape: 0.4754 - val_ia: 0.9350 - val_loss: 0.0134 - val_mae: 0.0873 - val_rmse: 0.1155 - val_smape: 0.2232

Epoch 5/256

144/144 - 1s - 6ms/step - ia: 0.8709 - loss: 0.0790 - mae: 0.2124 - rmse: 0.2805 - smape: 0.4319 - val_ia: 0.9446 - val_loss: 0.0102 - val_mae: 0.0748 - val_rmse: 0.1006 - val_smape: 0.1933

Epoch 6/256

144/144 - 1s - 6ms/step - ia: 0.8820 - loss: 0.0669 - mae: 0.1941 - rmse: 0.2582 - smape: 0.3994 - val_ia: 0.9487 - val_loss: 0.0090 - val_mae: 0.0702 - val_rmse: 0.0943 - val_smape: 0.1834

Epoch 7/256

144/144 - 1s - 5ms/step - ia: 0.8899 - loss: 0.0594 - mae: 0.1813 - rmse: 0.2430 - smape: 0.3735 - val_ia: 0.9495 - val_loss: 0.0086 - val_mae: 0.0694 - val_rmse: 0.0919 - val_smape: 0.1841

Epoch 8/256

144/144 - 1s - 5ms/step - ia: 0.8956 - loss: 0.0537 - mae: 0.1720 - rmse: 0.2313 - smape: 0.3528 - val_ia: 0.9516 - val_loss: 0.0078 - val_mae: 0.0664 - val_rmse: 0.0880 - val_smape: 0.1787

Epoch 9/256

144/144 - 1s - 6ms/step - ia: 0.8984 - loss: 0.0510 - mae: 0.1671 - rmse: 0.2254 - smape: 0.3424 - val_ia: 0.9500 - val_loss: 0.0081 - val_mae: 0.0687 - val_rmse: 0.0896 - val_smape: 0.1850

Epoch 10/256

144/144 - 2s - 13ms/step - ia: 0.9037 - loss: 0.0460 - mae: 0.1588 - rmse: 0.2141 - smape: 0.3291 - val_ia: 0.9538 - val_loss: 0.0070 - val_mae: 0.0634 - val_rmse: 0.0835 - val_smape: 0.1666

Epoch 11/256

144/144 - 1s - 10ms/step - ia: 0.9071 - loss: 0.0434 - mae: 0.1535 - rmse: 0.2080 - smape: 0.3172 - val_ia: 0.9567 - val_loss: 0.0061 - val_mae: 0.0584 - val_rmse: 0.0777 - val_smape: 0.1605

Epoch 12/256

144/144 - 2s - 11ms/step - ia: 0.9091 - loss: 0.0413 - mae: 0.1499 - rmse: 0.2029 - smape: 0.3089 - val_ia: 0.9458 - val_loss: 0.0092 - val_mae: 0.0756 - val_rmse: 0.0955 - val_smape: 0.1931

Epoch 13/256

144/144 - 2s - 16ms/step - ia: 0.9112 - loss: 0.0399 - mae: 0.1466 - rmse: 0.1991 - smape: 0.3029 - val_ia: 0.9532 - val_loss: 0.0068 - val_mae: 0.0626 - val_rmse: 0.0823 - val_smape: 0.1865

Epoch 14/256

144/144 - 1s - 10ms/step - ia: 0.9128 - loss: 0.0384 - mae: 0.1442 - rmse: 0.1953 - smape: 0.2968 - val_ia: 0.9541 - val_loss: 0.0066 - val_mae: 0.0629 - val_rmse: 0.0813 - val_smape: 0.1676

Epoch 15/256

144/144 - 1s - 9ms/step - ia: 0.9152 - loss: 0.0365 - mae: 0.1402 - rmse: 0.1905 - smape: 0.2889 - val_ia: 0.9549 - val_loss: 0.0064 - val_mae: 0.0612 - val_rmse: 0.0796 - val_smape: 0.1714

Epoch 16/256

144/144 - 1s - 9ms/step - ia: 0.9154 - loss: 0.0364 - mae: 0.1397 - rmse: 0.1904 - smape: 0.2879 - val_ia: 0.9533 - val_loss: 0.0068 - val_mae: 0.0640 - val_rmse: 0.0823 - val_smape: 0.1744

Epoch 17/256

144/144 - 1s - 9ms/step - ia: 0.9157 - loss: 0.0360 - mae: 0.1394 - rmse: 0.1893 - smape: 0.2869 - val_ia: 0.9555 - val_loss: 0.0062 - val_mae: 0.0604 - val_rmse: 0.0788 - val_smape: 0.1606

Epoch 18/256

144/144 - 1s - 5ms/step - ia: 0.9179 - loss: 0.0343 - mae: 0.1358 - rmse: 0.1848 - smape: 0.2809 - val_ia: 0.9488 - val_loss: 0.0080 - val_mae: 0.0706 - val_rmse: 0.0894 - val_smape: 0.1881

Epoch 19/256

144/144 - 2s - 11ms/step - ia: 0.9182 - loss: 0.0341 - mae: 0.1353 - rmse: 0.1841 - smape: 0.2804 - val_ia: 0.9564 - val_loss: 0.0061 - val_mae: 0.0584 - val_rmse: 0.0771 - val_smape: 0.1618

Epoch 20/256

144/144 - 2s - 11ms/step - ia: 0.9189 - loss: 0.0335 - mae: 0.1342 - rmse: 0.1825 - smape: 0.2782 - val_ia: 0.9565 - val_loss: 0.0059 - val_mae: 0.0584 - val_rmse: 0.0764 - val_smape: 0.1682

Epoch 21/256

144/144 - 2s - 17ms/step - ia: 0.9197 - loss: 0.0327 - mae: 0.1327 - rmse: 0.1802 - smape: 0.2756 - val_ia: 0.9550 - val_loss: 0.0063 - val_mae: 0.0615 - val_rmse: 0.0793 - val_smape: 0.1573

Epoch 22/256

144/144 - 1s - 10ms/step - ia: 0.9203 - loss: 0.0323 - mae: 0.1318 - rmse: 0.1791 - smape: 0.2734 - val_ia: 0.9556 - val_loss: 0.0062 - val_mae: 0.0603 - val_rmse: 0.0788 - val_smape: 0.1508

Epoch 23/256

144/144 - 1s - 10ms/step - ia: 0.9210 - loss: 0.0320 - mae: 0.1307 - rmse: 0.1783 - smape: 0.2709 - val_ia: 0.9568 - val_loss: 0.0058 - val_mae: 0.0584 - val_rmse: 0.0761 - val_smape: 0.1512

Epoch 24/256

144/144 - 3s - 18ms/step - ia: 0.9214 - loss: 0.0316 - mae: 0.1299 - rmse: 0.1773 - smape: 0.2682 - val_ia: 0.9541 - val_loss: 0.0064 - val_mae: 0.0623 - val_rmse: 0.0801 - val_smape: 0.1720

Epoch 25/256

144/144 - 2s - 11ms/step - ia: 0.9224 - loss: 0.0312 - mae: 0.1284 - rmse: 0.1759 - smape: 0.2663 - val_ia: 0.9546 - val_loss: 0.0063 - val_mae: 0.0614 - val_rmse: 0.0790 - val_smape: 0.1769

Epoch 26/256

144/144 - 2s - 11ms/step - ia: 0.9220 - loss: 0.0312 - mae: 0.1290 - rmse: 0.1760 - smape: 0.2662 - val_ia: 0.9573 - val_loss: 0.0057 - val_mae: 0.0572 - val_rmse: 0.0747 - val_smape: 0.1594

Epoch 27/256

144/144 - 3s - 19ms/step - ia: 0.9224 - loss: 0.0309 - mae: 0.1284 - rmse: 0.1754 - smape: 0.2659 - val_ia: 0.9581 - val_loss: 0.0056 - val_mae: 0.0557 - val_rmse: 0.0736 - val_smape: 0.1509

Epoch 28/256

144/144 - 1s - 10ms/step - ia: 0.9229 - loss: 0.0303 - mae: 0.1274 - rmse: 0.1738 - smape: 0.2635 - val_ia: 0.9562 - val_loss: 0.0058 - val_mae: 0.0581 - val_rmse: 0.0761 - val_smape: 0.1535

Epoch 29/256

144/144 - 3s - 18ms/step - ia: 0.9240 - loss: 0.0295 - mae: 0.1255 - rmse: 0.1714 - smape: 0.2595 - val_ia: 0.9551 - val_loss: 0.0062 - val_mae: 0.0610 - val_rmse: 0.0787 - val_smape: 0.1630

Epoch 30/256

144/144 - 3s - 19ms/step - ia: 0.9236 - loss: 0.0299 - mae: 0.1264 - rmse: 0.1724 - smape: 0.2621 - val_ia: 0.9559 - val_loss: 0.0059 - val_mae: 0.0581 - val_rmse: 0.0762 - val_smape: 0.1498

Epoch 31/256

144/144 - 3s - 19ms/step - ia: 0.9238 - loss: 0.0297 - mae: 0.1260 - rmse: 0.1720 - smape: 0.2591 - val_ia: 0.9577 - val_loss: 0.0055 - val_mae: 0.0567 - val_rmse: 0.0738 - val_smape: 0.1485

Epoch 32/256

144/144 - 1s - 9ms/step - ia: 0.9242 - loss: 0.0292 - mae: 0.1252 - rmse: 0.1705 - smape: 0.2601 - val_ia: 0.9556 - val_loss: 0.0061 - val_mae: 0.0606 - val_rmse: 0.0779 - val_smape: 0.1588

Epoch 33/256

144/144 - 2s - 11ms/step - ia: 0.9252 - loss: 0.0289 - mae: 0.1237 - rmse: 0.1694 - smape: 0.2555 - val_ia: 0.9596 - val_loss: 0.0051 - val_mae: 0.0540 - val_rmse: 0.0711 - val_smape: 0.1395

Epoch 34/256

144/144 - 2s - 17ms/step - ia: 0.9247 - loss: 0.0293 - mae: 0.1245 - rmse: 0.1706 - smape: 0.2546 - val_ia: 0.9591 - val_loss: 0.0052 - val_mae: 0.0546 - val_rmse: 0.0717 - val_smape: 0.1437

Epoch 35/256

144/144 - 1s - 9ms/step - ia: 0.9249 - loss: 0.0291 - mae: 0.1243 - rmse: 0.1700 - smape: 0.2566 - val_ia: 0.9579 - val_loss: 0.0055 - val_mae: 0.0566 - val_rmse: 0.0743 - val_smape: 0.1431

Epoch 36/256

144/144 - 3s - 18ms/step - ia: 0.9257 - loss: 0.0287 - mae: 0.1229 - rmse: 0.1690 - smape: 0.2529 - val_ia: 0.9604 - val_loss: 0.0050 - val_mae: 0.0529 - val_rmse: 0.0703 - val_smape: 0.1365

Epoch 37/256

144/144 - 1s - 9ms/step - ia: 0.9258 - loss: 0.0285 - mae: 0.1226 - rmse: 0.1684 - smape: 0.2523 - val_ia: 0.9589 - val_loss: 0.0053 - val_mae: 0.0551 - val_rmse: 0.0723 - val_smape: 0.1492

Epoch 38/256

144/144 - 1s - 7ms/step - ia: 0.9260 - loss: 0.0282 - mae: 0.1225 - rmse: 0.1676 - smape: 0.2522 - val_ia: 0.9603 - val_loss: 0.0051 - val_mae: 0.0530 - val_rmse: 0.0708 - val_smape: 0.1368

Epoch 39/256

144/144 - 1s - 9ms/step - ia: 0.9264 - loss: 0.0280 - mae: 0.1216 - rmse: 0.1670 - smape: 0.2496 - val_ia: 0.9597 - val_loss: 0.0051 - val_mae: 0.0541 - val_rmse: 0.0711 - val_smape: 0.1390

Epoch 40/256

144/144 - 2s - 12ms/step - ia: 0.9266 - loss: 0.0279 - mae: 0.1215 - rmse: 0.1666 - smape: 0.2488 - val_ia: 0.9597 - val_loss: 0.0051 - val_mae: 0.0539 - val_rmse: 0.0712 - val_smape: 0.1533

Epoch 41/256

144/144 - 2s - 12ms/step - ia: 0.9261 - loss: 0.0283 - mae: 0.1222 - rmse: 0.1680 - smape: 0.2506 - val_ia: 0.9579 - val_loss: 0.0054 - val_mae: 0.0563 - val_rmse: 0.0737 - val_smape: 0.1440

Epoch 42/256

144/144 - 2s - 12ms/step - ia: 0.9275 - loss: 0.0275 - mae: 0.1201 - rmse: 0.1653 - smape: 0.2457 - val_ia: 0.9566 - val_loss: 0.0058 - val_mae: 0.0589 - val_rmse: 0.0761 - val_smape: 0.1491

Epoch 43/256

144/144 - 1s - 9ms/step - ia: 0.9275 - loss: 0.0274 - mae: 0.1200 - rmse: 0.1652 - smape: 0.2470 - val_ia: 0.9601 - val_loss: 0.0050 - val_mae: 0.0533 - val_rmse: 0.0705 - val_smape: 0.1439

Epoch 44/256

144/144 - 2s - 11ms/step - ia: 0.9274 - loss: 0.0273 - mae: 0.1201 - rmse: 0.1648 - smape: 0.2470 - val_ia: 0.9566 - val_loss: 0.0056 - val_mae: 0.0581 - val_rmse: 0.0752 - val_smape: 0.1517

Epoch 45/256

144/144 - 2s - 12ms/step - ia: 0.9270 - loss: 0.0277 - mae: 0.1207 - rmse: 0.1659 - smape: 0.2458 - val_ia: 0.9586 - val_loss: 0.0052 - val_mae: 0.0558 - val_rmse: 0.0723 - val_smape: 0.1516

Epoch 46/256

144/144 - 2s - 13ms/step - ia: 0.9278 - loss: 0.0271 - mae: 0.1194 - rmse: 0.1642 - smape: 0.2458 - val_ia: 0.9574 - val_loss: 0.0055 - val_mae: 0.0565 - val_rmse: 0.0745 - val_smape: 0.1442

Epoch 47/256

144/144 - 3s - 18ms/step - ia: 0.9277 - loss: 0.0271 - mae: 0.1198 - rmse: 0.1641 - smape: 0.2455 - val_ia: 0.9591 - val_loss: 0.0052 - val_mae: 0.0546 - val_rmse: 0.0718 - val_smape: 0.1449

Epoch 48/256

144/144 - 1s - 9ms/step - ia: 0.9279 - loss: 0.0268 - mae: 0.1190 - rmse: 0.1634 - smape: 0.2432 - val_ia: 0.9610 - val_loss: 0.0048 - val_mae: 0.0519 - val_rmse: 0.0688 - val_smape: 0.1360

Epoch 49/256

144/144 - 3s - 19ms/step - ia: 0.9279 - loss: 0.0273 - mae: 0.1192 - rmse: 0.1647 - smape: 0.2438 - val_ia: 0.9611 - val_loss: 0.0050 - val_mae: 0.0519 - val_rmse: 0.0696 - val_smape: 0.1380

Epoch 50/256

144/144 - 1s - 9ms/step - ia: 0.9279 - loss: 0.0270 - mae: 0.1191 - rmse: 0.1638 - smape: 0.2416 - val_ia: 0.9594 - val_loss: 0.0050 - val_mae: 0.0538 - val_rmse: 0.0705 - val_smape: 0.1363

Epoch 51/256

144/144 - 1s - 9ms/step - ia: 0.9282 - loss: 0.0268 - mae: 0.1187 - rmse: 0.1634 - smape: 0.2435 - val_ia: 0.9602 - val_loss: 0.0050 - val_mae: 0.0539 - val_rmse: 0.0702 - val_smape: 0.1489

Epoch 52/256

144/144 - 1s - 10ms/step - ia: 0.9290 - loss: 0.0264 - mae: 0.1173 - rmse: 0.1619 - smape: 0.2389 - val_ia: 0.9523 - val_loss: 0.0069 - val_mae: 0.0650 - val_rmse: 0.0836 - val_smape: 0.1630

Epoch 53/256

144/144 - 1s - 8ms/step - ia: 0.9282 - loss: 0.0268 - mae: 0.1187 - rmse: 0.1634 - smape: 0.2421 - val_ia: 0.9572 - val_loss: 0.0056 - val_mae: 0.0562 - val_rmse: 0.0736 - val_smape: 0.1393

Epoch 54/256

144/144 - 1s - 9ms/step - ia: 0.9282 - loss: 0.0269 - mae: 0.1187 - rmse: 0.1636 - smape: 0.2411 - val_ia: 0.9605 - val_loss: 0.0053 - val_mae: 0.0533 - val_rmse: 0.0717 - val_smape: 0.1432

Epoch 55/256

144/144 - 1s - 10ms/step - ia: 0.9293 - loss: 0.0262 - mae: 0.1170 - rmse: 0.1614 - smape: 0.2389 - val_ia: 0.9596 - val_loss: 0.0053 - val_mae: 0.0539 - val_rmse: 0.0717 - val_smape: 0.1403

Epoch 56/256

144/144 - 1s - 9ms/step - ia: 0.9286 - loss: 0.0267 - mae: 0.1178 - rmse: 0.1628 - smape: 0.2392 - val_ia: 0.9594 - val_loss: 0.0050 - val_mae: 0.0544 - val_rmse: 0.0712 - val_smape: 0.1392

Epoch 57/256

144/144 - 2s - 12ms/step - ia: 0.9296 - loss: 0.0258 - mae: 0.1164 - rmse: 0.1600 - smape: 0.2385 - val_ia: 0.9598 - val_loss: 0.0051 - val_mae: 0.0546 - val_rmse: 0.0709 - val_smape: 0.1456

Epoch 58/256

144/144 - 3s - 19ms/step - ia: 0.9291 - loss: 0.0263 - mae: 0.1172 - rmse: 0.1617 - smape: 0.2380 - val_ia: 0.9607 - val_loss: 0.0048 - val_mae: 0.0529 - val_rmse: 0.0693 - val_smape: 0.1345

Epoch 59/256

144/144 - 2s - 10ms/step - ia: 0.9292 - loss: 0.0262 - mae: 0.1170 - rmse: 0.1614 - smape: 0.2378 - val_ia: 0.9574 - val_loss: 0.0056 - val_mae: 0.0572 - val_rmse: 0.0742 - val_smape: 0.1639

Epoch 60/256

144/144 - 2s - 17ms/step - ia: 0.9296 - loss: 0.0259 - mae: 0.1165 - rmse: 0.1606 - smape: 0.2380 - val_ia: 0.9600 - val_loss: 0.0050 - val_mae: 0.0528 - val_rmse: 0.0702 - val_smape: 0.1331

Epoch 61/256

144/144 - 1s - 9ms/step - ia: 0.9302 - loss: 0.0254 - mae: 0.1154 - rmse: 0.1591 - smape: 0.2349 - val_ia: 0.9600 - val_loss: 0.0050 - val_mae: 0.0534 - val_rmse: 0.0705 - val_smape: 0.1421

Epoch 62/256

144/144 - 2s - 11ms/step - ia: 0.9290 - loss: 0.0263 - mae: 0.1172 - rmse: 0.1620 - smape: 0.2383 - val_ia: 0.9584 - val_loss: 0.0053 - val_mae: 0.0559 - val_rmse: 0.0731 - val_smape: 0.1442

Epoch 63/256

144/144 - 1s - 6ms/step - ia: 0.9298 - loss: 0.0258 - mae: 0.1161 - rmse: 0.1601 - smape: 0.2355 - val_ia: 0.9539 - val_loss: 0.0064 - val_mae: 0.0626 - val_rmse: 0.0807 - val_smape: 0.1577

Epoch 63: early stopping

Restoring model weights from the end of the best epoch: 48.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 23s 145ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/32

 84%|████████▍ | 42/50 [3:09:35<28:08, 211.06s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 21s - 18ms/step - ia: 0.2315 - loss: 3.1849 - mae: 1.2608 - rmse: 1.7550 - smape: 1.4547 - val_ia: 0.2105 - val_loss: 1.4711 - val_mae: 0.9222 - val_rmse: 1.0408 - val_smape: 1.4023

Epoch 2/32

1147/1147 - 8s - 7ms/step - ia: 0.3336 - loss: 2.2601 - mae: 1.0383 - rmse: 1.4787 - smape: 1.3330 - val_ia: 0.2708 - val_loss: 1.0438 - val_mae: 0.7520 - val_rmse: 0.8584 - val_smape: 1.2362

Epoch 3/32

1147/1147 - 6s - 5ms/step - ia: 0.4231 - loss: 1.6331 - mae: 0.8618 - rmse: 1.2553 - smape: 1.2387 - val_ia: 0.3446 - val_loss: 0.7578 - val_mae: 0.6148 - val_rmse: 0.7142 - val_smape: 1.1273

Epoch 4/32

1147/1147 - 4s - 4ms/step - ia: 0.4976 - loss: 1.2058 - mae: 0.7245 - rmse: 1.0785 - smape: 1.1537 - val_ia: 0.4136 - val_loss: 0.5681 - val_mae: 0.5123 - val_rmse: 0.6083 - val_smape: 1.0413

Epoch 5/32

1147/1147 - 7s - 6ms/step - ia: 0.5597 - loss: 0.9124 - mae: 0.6198 - rmse: 0.9367 - smape: 1.0619 - val_ia: 0.4540 - val_loss: 0.4432 - val_mae: 0.4476 - val_rmse: 0.5377 - val_smape: 0.9684

Epoch 6/32

1147/1147 - 10s - 9ms/step - ia: 0.6102 - loss: 0.7035 - mae: 0.5397 - rmse: 0.8233 - smape: 0.9727 - val_ia: 0.4667 - val_loss: 0.3571 - val_mae: 0.4069 - val_rmse: 0.4905 - val_smape: 0.9031

Epoch 7/32

1147/1147 - 5s - 4ms/step - ia: 0.6573 - loss: 0.5491 - mae: 0.4748 - rmse: 0.7268 - smape: 0.8964 - val_ia: 0.4745 - val_loss: 0.2931 - val_mae: 0.3758 - val_rmse: 0.4536 - val_smape: 0.8349

Epoch 8/32

1147/1147 - 5s - 4ms/step - ia: 0.6986 - loss: 0.4311 - mae: 0.4214 - rmse: 0.6441 - smape: 0.8362 - val_ia: 0.4830 - val_loss: 0.2442 - val_mae: 0.3497 - val_rmse: 0.4221 - val_smape: 0.7750

Epoch 9/32

1147/1147 - 6s - 5ms/step - ia: 0.7326 - loss: 0.3420 - mae: 0.3793 - rmse: 0.5731 - smape: 0.7868 - val_ia: 0.4931 - val_loss: 0.2066 - val_mae: 0.3280 - val_rmse: 0.3952 - val_smape: 0.7279

Epoch 10/32

1147/1147 - 5s - 4ms/step - ia: 0.7611 - loss: 0.2762 - mae: 0.3459 - rmse: 0.5150 - smape: 0.7356 - val_ia: 0.5069 - val_loss: 0.1781 - val_mae: 0.3092 - val_rmse: 0.3724 - val_smape: 0.6929

Epoch 11/32

1147/1147 - 3s - 3ms/step - ia: 0.7833 - loss: 0.2272 - mae: 0.3182 - rmse: 0.4675 - smape: 0.6820 - val_ia: 0.5219 - val_loss: 0.1570 - val_mae: 0.2939 - val_rmse: 0.3536 - val_smape: 0.6627

Epoch 12/32

1147/1147 - 6s - 5ms/step - ia: 0.8030 - loss: 0.1898 - mae: 0.2941 - rmse: 0.4273 - smape: 0.6332 - val_ia: 0.5370 - val_loss: 0.1401 - val_mae: 0.2799 - val_rmse: 0.3364 - val_smape: 0.6347

Epoch 13/32

1147/1147 - 10s - 9ms/step - ia: 0.8191 - loss: 0.1600 - mae: 0.2720 - rmse: 0.3924 - smape: 0.5898 - val_ia: 0.5512 - val_loss: 0.1260 - val_mae: 0.2670 - val_rmse: 0.3208 - val_smape: 0.6088

Epoch 14/32

1147/1147 - 10s - 9ms/step - ia: 0.8339 - loss: 0.1358 - mae: 0.2514 - rmse: 0.3614 - smape: 0.5511 - val_ia: 0.5641 - val_loss: 0.1141 - val_mae: 0.2554 - val_rmse: 0.3066 - val_smape: 0.5840

Epoch 15/32

1147/1147 - 6s - 5ms/step - ia: 0.8475 - loss: 0.1162 - mae: 0.2328 - rmse: 0.3340 - smape: 0.5174 - val_ia: 0.5743 - val_loss: 0.1043 - val_mae: 0.2463 - val_rmse: 0.2949 - val_smape: 0.5636

Epoch 16/32

1147/1147 - 8s - 7ms/step - ia: 0.8589 - loss: 0.1005 - mae: 0.2168 - rmse: 0.3108 - smape: 0.4887 - val_ia: 0.5891 - val_loss: 0.0935 - val_mae: 0.2336 - val_rmse: 0.2802 - val_smape: 0.5389

Epoch 17/32

1147/1147 - 5s - 4ms/step - ia: 0.8682 - loss: 0.0879 - mae: 0.2030 - rmse: 0.2904 - smape: 0.4637 - val_ia: 0.6038 - val_loss: 0.0833 - val_mae: 0.2210 - val_rmse: 0.2655 - val_smape: 0.5148

Epoch 18/32

1147/1147 - 6s - 5ms/step - ia: 0.8767 - loss: 0.0774 - mae: 0.1912 - rmse: 0.2726 - smape: 0.4424 - val_ia: 0.6167 - val_loss: 0.0746 - val_mae: 0.2096 - val_rmse: 0.2523 - val_smape: 0.4917

Epoch 19/32

1147/1147 - 6s - 5ms/step - ia: 0.8836 - loss: 0.0685 - mae: 0.1808 - rmse: 0.2568 - smape: 0.4242 - val_ia: 0.6315 - val_loss: 0.0662 - val_mae: 0.1968 - val_rmse: 0.2384 - val_smape: 0.4646

Epoch 20/32

1147/1147 - 5s - 4ms/step - ia: 0.8900 - loss: 0.0609 - mae: 0.1714 - rmse: 0.2419 - smape: 0.4072 - val_ia: 0.6437 - val_loss: 0.0593 - val_mae: 0.1862 - val_rmse: 0.2267 - val_smape: 0.4414

Epoch 21/32

1147/1147 - 5s - 5ms/step - ia: 0.8959 - loss: 0.0543 - mae: 0.1628 - rmse: 0.2286 - smape: 0.3928 - val_ia: 0.6552 - val_loss: 0.0532 - val_mae: 0.1767 - val_rmse: 0.2160 - val_smape: 0.4211

Epoch 22/32

1147/1147 - 5s - 5ms/step - ia: 0.9011 - loss: 0.0487 - mae: 0.1553 - rmse: 0.2166 - smape: 0.3806 - val_ia: 0.6668 - val_loss: 0.0479 - val_mae: 0.1668 - val_rmse: 0.2059 - val_smape: 0.4022

Epoch 23/32

1147/1147 - 5s - 4ms/step - ia: 0.9059 - loss: 0.0440 - mae: 0.1484 - rmse: 0.2057 - smape: 0.3701 - val_ia: 0.6789 - val_loss: 0.0433 - val_mae: 0.1581 - val_rmse: 0.1968 - val_smape: 0.3895

Epoch 24/32

1147/1147 - 5s - 4ms/step - ia: 0.9101 - loss: 0.0399 - mae: 0.1422 - rmse: 0.1958 - smape: 0.3612 - val_ia: 0.6868 - val_loss: 0.0403 - val_mae: 0.1527 - val_rmse: 0.1909 - val_smape: 0.3821

Epoch 25/32

1147/1147 - 6s - 5ms/step - ia: 0.9136 - loss: 0.0366 - mae: 0.1369 - rmse: 0.1875 - smape: 0.3536 - val_ia: 0.6929 - val_loss: 0.0381 - val_mae: 0.1487 - val_rmse: 0.1865 - val_smape: 0.3762

Epoch 26/32

1147/1147 - 10s - 9ms/step - ia: 0.9167 - loss: 0.0339 - mae: 0.1324 - rmse: 0.1807 - smape: 0.3469 - val_ia: 0.7000 - val_loss: 0.0365 - val_mae: 0.1453 - val_rmse: 0.1827 - val_smape: 0.3719

Epoch 27/32

1147/1147 - 10s - 9ms/step - ia: 0.9192 - loss: 0.0317 - mae: 0.1287 - rmse: 0.1749 - smape: 0.3410 - val_ia: 0.7064 - val_loss: 0.0355 - val_mae: 0.1427 - val_rmse: 0.1799 - val_smape: 0.3676

Epoch 28/32

1147/1147 - 6s - 5ms/step - ia: 0.9213 - loss: 0.0300 - mae: 0.1255 - rmse: 0.1702 - smape: 0.3357 - val_ia: 0.7109 - val_loss: 0.0351 - val_mae: 0.1416 - val_rmse: 0.1783 - val_smape: 0.3650

Epoch 29/32

1147/1147 - 4s - 4ms/step - ia: 0.9230 - loss: 0.0286 - mae: 0.1229 - rmse: 0.1660 - smape: 0.3309 - val_ia: 0.7149 - val_loss: 0.0350 - val_mae: 0.1408 - val_rmse: 0.1771 - val_smape: 0.3623

Epoch 30/32

1147/1147 - 5s - 5ms/step - ia: 0.9245 - loss: 0.0275 - mae: 0.1206 - rmse: 0.1626 - smape: 0.3263 - val_ia: 0.7161 - val_loss: 0.0354 - val_mae: 0.1415 - val_rmse: 0.1772 - val_smape: 0.3618

Epoch 31/32

1147/1147 - 6s - 5ms/step - ia: 0.9256 - loss: 0.0265 - mae: 0.1187 - rmse: 0.1599 - smape: 0.3221 - val_ia: 0.7207 - val_loss: 0.0355 - val_mae: 0.1407 - val_rmse: 0.1762 - val_smape: 0.3585

Epoch 32/32

1147/1147 - 6s - 5ms/step - ia: 0.9268 - loss: 0.0257 - mae: 0.1170 - rmse: 0.1573 - smape: 0.3188 - val_ia: 0.7219 - val_loss: 0.0361 - val_mae: 0.1413 - val_rmse: 0.1765 - val_smape: 0.3578

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:24 519ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 86%|████████▌ | 43/50 [3:13:14<24:55, 213.65s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 11s - 38ms/step - ia: 0.7526 - loss: 0.3330 - mae: 0.4195 - rmse: 0.5457 - smape: 0.7180 - val_ia: 0.8980 - val_loss: 0.0302 - val_mae: 0.1371 - val_rmse: 0.1707 - val_smape: 0.3831

Epoch 2/8

287/287 - 2s - 7ms/step - ia: 0.8524 - loss: 0.1025 - mae: 0.2439 - rmse: 0.3179 - smape: 0.5126 - val_ia: 0.9183 - val_loss: 0.0201 - val_mae: 0.1088 - val_rmse: 0.1390 - val_smape: 0.3051

Epoch 3/8

287/287 - 3s - 9ms/step - ia: 0.8821 - loss: 0.0649 - mae: 0.1938 - rmse: 0.2539 - smape: 0.4377 - val_ia: 0.9294 - val_loss: 0.0152 - val_mae: 0.0945 - val_rmse: 0.1213 - val_smape: 0.2741

Epoch 4/8

287/287 - 2s - 7ms/step - ia: 0.8964 - loss: 0.0501 - mae: 0.1700 - rmse: 0.2229 - smape: 0.3976 - val_ia: 0.9275 - val_loss: 0.0156 - val_mae: 0.0976 - val_rmse: 0.1218 - val_smape: 0.2902

Epoch 5/8

287/287 - 2s - 6ms/step - ia: 0.9066 - loss: 0.0410 - mae: 0.1534 - rmse: 0.2018 - smape: 0.3671 - val_ia: 0.9435 - val_loss: 0.0102 - val_mae: 0.0762 - val_rmse: 0.0994 - val_smape: 0.2336

Epoch 6/8

287/287 - 2s - 7ms/step - ia: 0.9141 - loss: 0.0348 - mae: 0.1410 - rmse: 0.1858 - smape: 0.3443 - val_ia: 0.9429 - val_loss: 0.0100 - val_mae: 0.0773 - val_rmse: 0.0985 - val_smape: 0.2372

Epoch 7/8

287/287 - 3s - 11ms/step - ia: 0.9194 - loss: 0.0309 - mae: 0.1322 - rmse: 0.1748 - smape: 0.3284 - val_ia: 0.9461 - val_loss: 0.0093 - val_mae: 0.0724 - val_rmse: 0.0942 - val_smape: 0.2206

Epoch 8/8

287/287 - 2s - 8ms/step - ia: 0.9238 - loss: 0.0275 - mae: 0.1252 - rmse: 0.1652 - smape: 0.3159 - val_ia: 0.9541 - val_loss: 0.0072 - val_mae: 0.0618 - val_rmse: 0.0835 - val_smape: 0.1821

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 35s 217ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 88%|████████▊ | 44/50 [3:13:45<15:52, 158.69s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2293/2293 - 27s - 12ms/step - ia: 0.7797 - loss: 0.1883 - mae: 0.3366 - rmse: 0.4219 - smape: 0.6267 - val_ia: 0.4654 - val_loss: 0.0670 - val_mae: 0.2161 - val_rmse: 0.2389 - val_smape: 0.4788

Epoch 2/64

2293/2293 - 20s - 9ms/step - ia: 0.7978 - loss: 0.1586 - mae: 0.3097 - rmse: 0.3902 - smape: 0.6068 - val_ia: 0.4863 - val_loss: 0.0751 - val_mae: 0.2169 - val_rmse: 0.2486 - val_smape: 0.4801

Epoch 3/64

2293/2293 - 12s - 5ms/step - ia: 0.7940 - loss: 0.1639 - mae: 0.3154 - rmse: 0.3970 - smape: 0.6142 - val_ia: 0.4766 - val_loss: 0.0722 - val_mae: 0.2160 - val_rmse: 0.2443 - val_smape: 0.4376

Epoch 4/64

2293/2293 - 10s - 4ms/step - ia: 0.7953 - loss: 0.1616 - mae: 0.3139 - rmse: 0.3937 - smape: 0.6207 - val_ia: 0.4810 - val_loss: 0.0747 - val_mae: 0.2134 - val_rmse: 0.2434 - val_smape: 0.4676

Epoch 5/64

2293/2293 - 12s - 5ms/step - ia: 0.7937 - loss: 0.1647 - mae: 0.3154 - rmse: 0.3972 - smape: 0.6189 - val_ia: 0.4323 - val_loss: 0.0947 - val_mae: 0.2592 - val_rmse: 0.2846 - val_smape: 0.5759

Epoch 6/64

2293/2293 - 12s - 5ms/step - ia: 0.7926 - loss: 0.1666 - mae: 0.3182 - rmse: 0.4001 - smape: 0.6267 - val_ia: 0.4360 - val_loss: 0.0929 - val_mae: 0.2525 - val_rmse: 0.2806 - val_smape: 0.6163

Epoch 7/64

2293/2293 - 17s - 7ms/step - ia: 0.7934 - loss: 0.1653 - mae: 0.3168 - rmse: 0.3984 - smape: 0.6231 - val_ia: 0.4877 - val_loss: 0.0803 - val_mae: 0.2214 - val_rmse: 0.2482 - val_smape: 0.4664

Epoch 8/64

2293/2293 - 14s - 6ms/step - ia: 0.7943 - loss: 0.1660 - mae: 0.3161 - rmse: 0.3991 - smape: 0.6191 - val_ia: 0.4572 - val_loss: 0.0837 - val_mae: 0.2340 - val_rmse: 0.2625 - val_smape: 0.5208

Epoch 9/64

2293/2293 - 19s - 8ms/step - ia: 0.7895 - loss: 0.1719 - mae: 0.3228 - rmse: 0.4065 - smape: 0.6249 - val_ia: 0.4466 - val_loss: 0.0962 - val_mae: 0.2462 - val_rmse: 0.2810 - val_smape: 0.5476

Epoch 10/64

2293/2293 - 7s - 3ms/step - ia: 0.7899 - loss: 0.1727 - mae: 0.3231 - rmse: 0.4072 - smape: 0.6240 - val_ia: 0.4865 - val_loss: 0.0776 - val_mae: 0.2158 - val_rmse: 0.2473 - val_smape: 0.4196

Epoch 11/64

2293/2293 - 14s - 6ms/step - ia: 0.7911 - loss: 0.1685 - mae: 0.3201 - rmse: 0.4023 - smape: 0.6283 - val_ia: 0.4738 - val_loss: 0.0748 - val_mae: 0.2198 - val_rmse: 0.2459 - val_smape: 0.4847

Epoch 12/64

2293/2293 - 19s - 8ms/step - ia: 0.7891 - loss: 0.1721 - mae: 0.3228 - rmse: 0.4063 - smape: 0.6354 - val_ia: 0.4335 - val_loss: 0.0970 - val_mae: 0.2540 - val_rmse: 0.2883 - val_smape: 0.5467

Epoch 13/64

2293/2293 - 9s - 4ms/step - ia: 0.7927 - loss: 0.1678 - mae: 0.3185 - rmse: 0.4010 - smape: 0.6247 - val_ia: 0.4462 - val_loss: 0.0942 - val_mae: 0.2475 - val_rmse: 0.2789 - val_smape: 0.6014

Epoch 14/64

2293/2293 - 6s - 2ms/step - ia: 0.7938 - loss: 0.1668 - mae: 0.3166 - rmse: 0.3998 - smape: 0.6235 - val_ia: 0.4512 - val_loss: 0.0754 - val_mae: 0.2295 - val_rmse: 0.2565 - val_smape: 0.5724

Epoch 15/64

2293/2293 - 6s - 2ms/step - ia: 0.7938 - loss: 0.1652 - mae: 0.3170 - rmse: 0.3982 - smape: 0.6204 - val_ia: 0.4254 - val_loss: 0.0972 - val_mae: 0.2593 - val_rmse: 0.2889 - val_smape: 0.5861

Epoch 16/64

2293/2293 - 9s - 4ms/step - ia: 0.7922 - loss: 0.1658 - mae: 0.3175 - rmse: 0.3987 - smape: 0.6299 - val_ia: 0.4343 - val_loss: 0.0921 - val_mae: 0.2504 - val_rmse: 0.2746 - val_smape: 0.6178

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

Epoch 1/32

 90%|█████████ | 45/50 [3:17:19<14:36, 175.24s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1147/1147 - 4s - 3ms/step - ia: 0.7677 - loss: 0.2466 - mae: 0.3505 - rmse: 0.4663 - smape: 0.6282 - val_ia: 0.6464 - val_loss: 0.0828 - val_mae: 0.2039 - val_rmse: 0.2419 - val_smape: 0.3391

Epoch 2/32

1147/1147 - 2s - 1ms/step - ia: 0.8248 - loss: 0.1361 - mae: 0.2699 - rmse: 0.3637 - smape: 0.4962 - val_ia: 0.6557 - val_loss: 0.0634 - val_mae: 0.1939 - val_rmse: 0.2232 - val_smape: 0.3707

Epoch 3/32

1147/1147 - 2s - 1ms/step - ia: 0.8324 - loss: 0.1260 - mae: 0.2603 - rmse: 0.3494 - smape: 0.4986 - val_ia: 0.7628 - val_loss: 0.0253 - val_mae: 0.1206 - val_rmse: 0.1425 - val_smape: 0.2763

Epoch 4/32

1147/1147 - 2s - 1ms/step - ia: 0.8383 - loss: 0.1171 - mae: 0.2520 - rmse: 0.3369 - smape: 0.4899 - val_ia: 0.7591 - val_loss: 0.0223 - val_mae: 0.1168 - val_rmse: 0.1377 - val_smape: 0.2623

Epoch 5/32

1147/1147 - 2s - 2ms/step - ia: 0.8397 - loss: 0.1146 - mae: 0.2502 - rmse: 0.3331 - smape: 0.4869 - val_ia: 0.7944 - val_loss: 0.0166 - val_mae: 0.1003 - val_rmse: 0.1192 - val_smape: 0.2472

Epoch 6/32

1147/1147 - 3s - 3ms/step - ia: 0.8403 - loss: 0.1138 - mae: 0.2494 - rmse: 0.3320 - smape: 0.4858 - val_ia: 0.7161 - val_loss: 0.0360 - val_mae: 0.1455 - val_rmse: 0.1694 - val_smape: 0.2822

Epoch 7/32

1147/1147 - 3s - 2ms/step - ia: 0.8417 - loss: 0.1117 - mae: 0.2467 - rmse: 0.3290 - smape: 0.4792 - val_ia: 0.7832 - val_loss: 0.0217 - val_mae: 0.1061 - val_rmse: 0.1291 - val_smape: 0.2501

Epoch 8/32

1147/1147 - 3s - 3ms/step - ia: 0.8417 - loss: 0.1120 - mae: 0.2470 - rmse: 0.3296 - smape: 0.4809 - val_ia: 0.7842 - val_loss: 0.0194 - val_mae: 0.1050 - val_rmse: 0.1261 - val_smape: 0.2637

Epoch 9/32

1147/1147 - 8s - 7ms/step - ia: 0.8431 - loss: 0.1101 - mae: 0.2449 - rmse: 0.3264 - smape: 0.4752 - val_ia: 0.7015 - val_loss: 0.0407 - val_mae: 0.1566 - val_rmse: 0.1803 - val_smape: 0.2847

Epoch 10/32

1147/1147 - 6s - 5ms/step - ia: 0.8423 - loss: 0.1111 - mae: 0.2458 - rmse: 0.3280 - smape: 0.4785 - val_ia: 0.7220 - val_loss: 0.0349 - val_mae: 0.1428 - val_rmse: 0.1658 - val_smape: 0.2692

Epoch 11/32

1147/1147 - 10s - 9ms/step - ia: 0.8428 - loss: 0.1105 - mae: 0.2453 - rmse: 0.3274 - smape: 0.4775 - val_ia: 0.7274 - val_loss: 0.0295 - val_mae: 0.1367 - val_rmse: 0.1568 - val_smape: 0.3247

Epoch 12/32

1147/1147 - 10s - 9ms/step - ia: 0.8427 - loss: 0.1113 - mae: 0.2457 - rmse: 0.3283 - smape: 0.4780 - val_ia: 0.7681 - val_loss: 0.0188 - val_mae: 0.1083 - val_rmse: 0.1263 - val_smape: 0.2520

Epoch 13/32

1147/1147 - 5s - 4ms/step - ia: 0.8442 - loss: 0.1085 - mae: 0.2431 - rmse: 0.3244 - smape: 0.4705 - val_ia: 0.7997 - val_loss: 0.0208 - val_mae: 0.1011 - val_rmse: 0.1235 - val_smape: 0.2358

Epoch 14/32

1147/1147 - 7s - 6ms/step - ia: 0.8427 - loss: 0.1103 - mae: 0.2459 - rmse: 0.3274 - smape: 0.4801 - val_ia: 0.7181 - val_loss: 0.0317 - val_mae: 0.1404 - val_rmse: 0.1612 - val_smape: 0.2990

Epoch 15/32

1147/1147 - 10s - 9ms/step - ia: 0.8428 - loss: 0.1106 - mae: 0.2447 - rmse: 0.3274 - smape: 0.4734 - val_ia: 0.7074 - val_loss: 0.0415 - val_mae: 0.1529 - val_rmse: 0.1756 - val_smape: 0.2844

Epoch 16/32

1147/1147 - 6s - 5ms/step - ia: 0.8424 - loss: 0.1117 - mae: 0.2463 - rmse: 0.3291 - smape: 0.4770 - val_ia: 0.7915 - val_loss: 0.0135 - val_mae: 0.0945 - val_rmse: 0.1119 - val_smape: 0.2650

Epoch 17/32

1147/1147 - 5s - 4ms/step - ia: 0.8435 - loss: 0.1093 - mae: 0.2442 - rmse: 0.3252 - smape: 0.4781 - val_ia: 0.7606 - val_loss: 0.0314 - val_mae: 0.1248 - val_rmse: 0.1475 - val_smape: 0.2633

Epoch 18/32

1147/1147 - 5s - 4ms/step - ia: 0.8456 - loss: 0.1068 - mae: 0.2411 - rmse: 0.3220 - smape: 0.4716 - val_ia: 0.8223 - val_loss: 0.0140 - val_mae: 0.0850 - val_rmse: 0.1053 - val_smape: 0.1968

Epoch 19/32

1147/1147 - 5s - 4ms/step - ia: 0.8443 - loss: 0.1089 - mae: 0.2433 - rmse: 0.3247 - smape: 0.4709 - val_ia: 0.7854 - val_loss: 0.0244 - val_mae: 0.1098 - val_rmse: 0.1318 - val_smape: 0.2229

Epoch 20/32

1147/1147 - 6s - 5ms/step - ia: 0.8434 - loss: 0.1100 - mae: 0.2445 - rmse: 0.3263 - smape: 0.4783 - val_ia: 0.7522 - val_loss: 0.0200 - val_mae: 0.1157 - val_rmse: 0.1347 - val_smape: 0.2615

Epoch 21/32

1147/1147 - 11s - 9ms/step - ia: 0.8449 - loss: 0.1084 - mae: 0.2422 - rmse: 0.3239 - smape: 0.4719 - val_ia: 0.7175 - val_loss: 0.0345 - val_mae: 0.1447 - val_rmse: 0.1641 - val_smape: 0.3011

Epoch 22/32

1147/1147 - 6s - 5ms/step - ia: 0.8438 - loss: 0.1085 - mae: 0.2434 - rmse: 0.3245 - smape: 0.4745 - val_ia: 0.7394 - val_loss: 0.0306 - val_mae: 0.1314 - val_rmse: 0.1532 - val_smape: 0.2377

Epoch 23/32

1147/1147 - 6s - 5ms/step - ia: 0.8441 - loss: 0.1098 - mae: 0.2437 - rmse: 0.3259 - smape: 0.4732 - val_ia: 0.7659 - val_loss: 0.0190 - val_mae: 0.1099 - val_rmse: 0.1283 - val_smape: 0.2739

Epoch 24/32

1147/1147 - 10s - 8ms/step - ia: 0.8443 - loss: 0.1089 - mae: 0.2432 - rmse: 0.3251 - smape: 0.4722 - val_ia: 0.7682 - val_loss: 0.0308 - val_mae: 0.1194 - val_rmse: 0.1448 - val_smape: 0.2290

Epoch 25/32

1147/1147 - 5s - 5ms/step - ia: 0.8426 - loss: 0.1105 - mae: 0.2453 - rmse: 0.3274 - smape: 0.4699 - val_ia: 0.7893 - val_loss: 0.0173 - val_mae: 0.1027 - val_rmse: 0.1224 - val_smape: 0.2743

Epoch 26/32

1147/1147 - 6s - 5ms/step - ia: 0.8429 - loss: 0.1106 - mae: 0.2454 - rmse: 0.3273 - smape: 0.4730 - val_ia: 0.7792 - val_loss: 0.0202 - val_mae: 0.1068 - val_rmse: 0.1268 - val_smape: 0.2450

Epoch 27/32

1147/1147 - 6s - 5ms/step - ia: 0.8432 - loss: 0.1107 - mae: 0.2451 - rmse: 0.3276 - smape: 0.4762 - val_ia: 0.7468 - val_loss: 0.0354 - val_mae: 0.1324 - val_rmse: 0.1577 - val_smape: 0.2458

Epoch 28/32

1147/1147 - 6s - 5ms/step - ia: 0.8444 - loss: 0.1090 - mae: 0.2430 - rmse: 0.3250 - smape: 0.4730 - val_ia: 0.7640 - val_loss: 0.0348 - val_mae: 0.1260 - val_rmse: 0.1515 - val_smape: 0.2504

Epoch 29/32

1147/1147 - 6s - 5ms/step - ia: 0.8445 - loss: 0.1090 - mae: 0.2431 - rmse: 0.3249 - smape: 0.4710 - val_ia: 0.7595 - val_loss: 0.0190 - val_mae: 0.1104 - val_rmse: 0.1275 - val_smape: 0.2557

Epoch 30/32

1147/1147 - 5s - 4ms/step - ia: 0.8426 - loss: 0.1111 - mae: 0.2460 - rmse: 0.3283 - smape: 0.4765 - val_ia: 0.8282 - val_loss: 0.0114 - val_mae: 0.0806 - val_rmse: 0.0979 - val_smape: 0.2267

Epoch 31/32

1147/1147 - 5s - 5ms/step - ia: 0.8441 - loss: 0.1097 - mae: 0.2441 - rmse: 0.3257 - smape: 0.4761 - val_ia: 0.7648 - val_loss: 0.0304 - val_mae: 0.1204 - val_rmse: 0.1444 - val_smape: 0.2299

Epoch 32/32

1147/1147 - 4s - 3ms/step - ia: 0.8448 - loss: 0.1074 - mae: 0.2429 - rmse: 0.3229 - smape: 0.4744 - val_ia: 0.7192 - val_loss: 0.0321 - val_mae: 0.1397 - val_rmse: 0.1603 - val_smape: 0.2727

Restoring model weights from the end of the best epoch: 30.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 32s 200ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 92%|█████████▏| 46/50 [3:20:16<11:44, 176.08s/trial, best loss: 0.002207251890576192]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 35s - 242ms/step - ia: 0.7847 - loss: 0.2927 - mae: 0.3745 - rmse: 0.4909 - smape: 0.6616 - val_ia: 0.9193 - val_loss: 0.0181 - val_mae: 0.1060 - val_rmse: 0.1325 - val_smape: 0.2981

Epoch 2/256

144/144 - 1s - 6ms/step - ia: 0.8900 - loss: 0.0604 - mae: 0.1821 - rmse: 0.2437 - smape: 0.4231 - val_ia: 0.9340 - val_loss: 0.0129 - val_mae: 0.0907 - val_rmse: 0.1137 - val_smape: 0.2454

Epoch 3/256

144/144 - 1s - 6ms/step - ia: 0.9191 - loss: 0.0333 - mae: 0.1337 - rmse: 0.1816 - smape: 0.3304 - val_ia: 0.9472 - val_loss: 0.0084 - val_mae: 0.0696 - val_rmse: 0.0908 - val_smape: 0.2095

Epoch 4/256

144/144 - 1s - 6ms/step - ia: 0.9317 - loss: 0.0234 - mae: 0.1127 - rmse: 0.1524 - smape: 0.2872 - val_ia: 0.9608 - val_loss: 0.0057 - val_mae: 0.0527 - val_rmse: 0.0747 - val_smape: 0.1637

Epoch 5/256

144/144 - 2s - 15ms/step - ia: 0.9387 - loss: 0.0190 - mae: 0.1011 - rmse: 0.1375 - smape: 0.2589 - val_ia: 0.9601 - val_loss: 0.0055 - val_mae: 0.0535 - val_rmse: 0.0737 - val_smape: 0.1629

Epoch 6/256

144/144 - 1s - 9ms/step - ia: 0.9424 - loss: 0.0168 - mae: 0.0948 - rmse: 0.1290 - smape: 0.2409 - val_ia: 0.9666 - val_loss: 0.0044 - val_mae: 0.0449 - val_rmse: 0.0659 - val_smape: 0.1381

Epoch 7/256

144/144 - 1s - 9ms/step - ia: 0.9451 - loss: 0.0155 - mae: 0.0904 - rmse: 0.1239 - smape: 0.2307 - val_ia: 0.9551 - val_loss: 0.0063 - val_mae: 0.0597 - val_rmse: 0.0785 - val_smape: 0.1708

Epoch 8/256

144/144 - 2s - 11ms/step - ia: 0.9469 - loss: 0.0144 - mae: 0.0875 - rmse: 0.1193 - smape: 0.2205 - val_ia: 0.9589 - val_loss: 0.0054 - val_mae: 0.0542 - val_rmse: 0.0723 - val_smape: 0.1666

Epoch 9/256

144/144 - 2s - 17ms/step - ia: 0.9489 - loss: 0.0134 - mae: 0.0843 - rmse: 0.1152 - smape: 0.2153 - val_ia: 0.9628 - val_loss: 0.0047 - val_mae: 0.0495 - val_rmse: 0.0679 - val_smape: 0.1490

Epoch 10/256

144/144 - 1s - 9ms/step - ia: 0.9498 - loss: 0.0130 - mae: 0.0827 - rmse: 0.1137 - smape: 0.2107 - val_ia: 0.9653 - val_loss: 0.0043 - val_mae: 0.0466 - val_rmse: 0.0650 - val_smape: 0.1458

Epoch 11/256

144/144 - 1s - 8ms/step - ia: 0.9512 - loss: 0.0124 - mae: 0.0804 - rmse: 0.1106 - smape: 0.2039 - val_ia: 0.9671 - val_loss: 0.0040 - val_mae: 0.0439 - val_rmse: 0.0629 - val_smape: 0.1364

Epoch 12/256

144/144 - 2s - 12ms/step - ia: 0.9512 - loss: 0.0122 - mae: 0.0803 - rmse: 0.1100 - smape: 0.2029 - val_ia: 0.9599 - val_loss: 0.0053 - val_mae: 0.0536 - val_rmse: 0.0720 - val_smape: 0.1466

Epoch 13/256

144/144 - 2s - 11ms/step - ia: 0.9522 - loss: 0.0118 - mae: 0.0787 - rmse: 0.1080 - smape: 0.1994 - val_ia: 0.9638 - val_loss: 0.0043 - val_mae: 0.0484 - val_rmse: 0.0651 - val_smape: 0.1562

Epoch 14/256

144/144 - 3s - 19ms/step - ia: 0.9523 - loss: 0.0116 - mae: 0.0786 - rmse: 0.1072 - smape: 0.1981 - val_ia: 0.9661 - val_loss: 0.0041 - val_mae: 0.0455 - val_rmse: 0.0635 - val_smape: 0.1321

Epoch 15/256

144/144 - 1s - 8ms/step - ia: 0.9533 - loss: 0.0114 - mae: 0.0769 - rmse: 0.1060 - smape: 0.1941 - val_ia: 0.9650 - val_loss: 0.0041 - val_mae: 0.0469 - val_rmse: 0.0641 - val_smape: 0.1496

Epoch 16/256

144/144 - 2s - 11ms/step - ia: 0.9535 - loss: 0.0113 - mae: 0.0767 - rmse: 0.1057 - smape: 0.1918 - val_ia: 0.9685 - val_loss: 0.0037 - val_mae: 0.0425 - val_rmse: 0.0600 - val_smape: 0.1282

Epoch 17/256

144/144 - 3s - 18ms/step - ia: 0.9538 - loss: 0.0112 - mae: 0.0762 - rmse: 0.1054 - smape: 0.1901 - val_ia: 0.9647 - val_loss: 0.0043 - val_mae: 0.0475 - val_rmse: 0.0646 - val_smape: 0.1334

Epoch 18/256

144/144 - 1s - 9ms/step - ia: 0.9545 - loss: 0.0109 - mae: 0.0750 - rmse: 0.1036 - smape: 0.1874 - val_ia: 0.9691 - val_loss: 0.0035 - val_mae: 0.0414 - val_rmse: 0.0590 - val_smape: 0.1319

Epoch 19/256

144/144 - 1s - 10ms/step - ia: 0.9544 - loss: 0.0108 - mae: 0.0751 - rmse: 0.1036 - smape: 0.1862 - val_ia: 0.9710 - val_loss: 0.0033 - val_mae: 0.0391 - val_rmse: 0.0570 - val_smape: 0.1213

Epoch 20/256

144/144 - 1s - 10ms/step - ia: 0.9552 - loss: 0.0105 - mae: 0.0738 - rmse: 0.1019 - smape: 0.1839 - val_ia: 0.9651 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0628 - val_smape: 0.1494

Epoch 21/256

144/144 - 1s - 10ms/step - ia: 0.9552 - loss: 0.0105 - mae: 0.0737 - rmse: 0.1018 - smape: 0.1832 - val_ia: 0.9709 - val_loss: 0.0032 - val_mae: 0.0392 - val_rmse: 0.0562 - val_smape: 0.1217

Epoch 22/256

144/144 - 1s - 7ms/step - ia: 0.9559 - loss: 0.0103 - mae: 0.0728 - rmse: 0.1008 - smape: 0.1807 - val_ia: 0.9666 - val_loss: 0.0039 - val_mae: 0.0450 - val_rmse: 0.0613 - val_smape: 0.1341

Epoch 23/256

144/144 - 1s - 7ms/step - ia: 0.9553 - loss: 0.0105 - mae: 0.0737 - rmse: 0.1018 - smape: 0.1833 - val_ia: 0.9652 - val_loss: 0.0040 - val_mae: 0.0464 - val_rmse: 0.0622 - val_smape: 0.1424

Epoch 24/256

144/144 - 2s - 11ms/step - ia: 0.9556 - loss: 0.0104 - mae: 0.0731 - rmse: 0.1013 - smape: 0.1814 - val_ia: 0.9595 - val_loss: 0.0050 - val_mae: 0.0537 - val_rmse: 0.0693 - val_smape: 0.1568

Epoch 25/256

144/144 - 1s - 8ms/step - ia: 0.9559 - loss: 0.0103 - mae: 0.0727 - rmse: 0.1006 - smape: 0.1799 - val_ia: 0.9702 - val_loss: 0.0033 - val_mae: 0.0398 - val_rmse: 0.0568 - val_smape: 0.1259

Epoch 26/256

144/144 - 1s - 7ms/step - ia: 0.9563 - loss: 0.0102 - mae: 0.0721 - rmse: 0.1001 - smape: 0.1788 - val_ia: 0.9681 - val_loss: 0.0037 - val_mae: 0.0430 - val_rmse: 0.0601 - val_smape: 0.1223

Epoch 27/256

144/144 - 2s - 12ms/step - ia: 0.9559 - loss: 0.0102 - mae: 0.0726 - rmse: 0.1006 - smape: 0.1797 - val_ia: 0.9727 - val_loss: 0.0030 - val_mae: 0.0368 - val_rmse: 0.0539 - val_smape: 0.1158

Epoch 28/256

144/144 - 1s - 6ms/step - ia: 0.9561 - loss: 0.0102 - mae: 0.0723 - rmse: 0.1006 - smape: 0.1788 - val_ia: 0.9698 - val_loss: 0.0034 - val_mae: 0.0406 - val_rmse: 0.0575 - val_smape: 0.1295

Epoch 29/256

144/144 - 1s - 5ms/step - ia: 0.9568 - loss: 0.0100 - mae: 0.0712 - rmse: 0.0992 - smape: 0.1761 - val_ia: 0.9677 - val_loss: 0.0036 - val_mae: 0.0436 - val_rmse: 0.0596 - val_smape: 0.1389

Epoch 30/256

144/144 - 1s - 7ms/step - ia: 0.9569 - loss: 0.0099 - mae: 0.0710 - rmse: 0.0986 - smape: 0.1760 - val_ia: 0.9695 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0572 - val_smape: 0.1257

Epoch 31/256

144/144 - 1s - 8ms/step - ia: 0.9570 - loss: 0.0098 - mae: 0.0708 - rmse: 0.0983 - smape: 0.1745 - val_ia: 0.9677 - val_loss: 0.0036 - val_mae: 0.0430 - val_rmse: 0.0594 - val_smape: 0.1375

Epoch 32/256

144/144 - 2s - 13ms/step - ia: 0.9559 - loss: 0.0103 - mae: 0.0727 - rmse: 0.1007 - smape: 0.1779 - val_ia: 0.9624 - val_loss: 0.0044 - val_mae: 0.0498 - val_rmse: 0.0660 - val_smape: 0.1612

Epoch 33/256

144/144 - 2s - 11ms/step - ia: 0.9573 - loss: 0.0098 - mae: 0.0704 - rmse: 0.0981 - smape: 0.1747 - val_ia: 0.9726 - val_loss: 0.0030 - val_mae: 0.0369 - val_rmse: 0.0537 - val_smape: 0.1154

Epoch 34/256

144/144 - 1s - 10ms/step - ia: 0.9572 - loss: 0.0097 - mae: 0.0705 - rmse: 0.0981 - smape: 0.1735 - val_ia: 0.9679 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0588 - val_smape: 0.1320

Epoch 35/256

144/144 - 2s - 11ms/step - ia: 0.9573 - loss: 0.0098 - mae: 0.0704 - rmse: 0.0983 - smape: 0.1740 - val_ia: 0.9599 - val_loss: 0.0050 - val_mae: 0.0540 - val_rmse: 0.0698 - val_smape: 0.1426

Epoch 36/256

144/144 - 1s - 9ms/step - ia: 0.9562 - loss: 0.0102 - mae: 0.0723 - rmse: 0.1004 - smape: 0.1752 - val_ia: 0.9725 - val_loss: 0.0030 - val_mae: 0.0371 - val_rmse: 0.0539 - val_smape: 0.1163

Epoch 37/256

144/144 - 3s - 18ms/step - ia: 0.9579 - loss: 0.0095 - mae: 0.0694 - rmse: 0.0969 - smape: 0.1712 - val_ia: 0.9660 - val_loss: 0.0037 - val_mae: 0.0456 - val_rmse: 0.0606 - val_smape: 0.1492

Epoch 38/256

144/144 - 2s - 11ms/step - ia: 0.9572 - loss: 0.0097 - mae: 0.0705 - rmse: 0.0978 - smape: 0.1732 - val_ia: 0.9684 - val_loss: 0.0034 - val_mae: 0.0426 - val_rmse: 0.0579 - val_smape: 0.1344

Epoch 39/256

144/144 - 1s - 9ms/step - ia: 0.9576 - loss: 0.0096 - mae: 0.0698 - rmse: 0.0972 - smape: 0.1723 - val_ia: 0.9697 - val_loss: 0.0034 - val_mae: 0.0409 - val_rmse: 0.0572 - val_smape: 0.1232

Epoch 40/256

144/144 - 1s - 9ms/step - ia: 0.9577 - loss: 0.0096 - mae: 0.0697 - rmse: 0.0973 - smape: 0.1726 - val_ia: 0.9712 - val_loss: 0.0031 - val_mae: 0.0386 - val_rmse: 0.0549 - val_smape: 0.1229

Epoch 41/256

144/144 - 1s - 10ms/step - ia: 0.9582 - loss: 0.0094 - mae: 0.0690 - rmse: 0.0961 - smape: 0.1691 - val_ia: 0.9677 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0585 - val_smape: 0.1393

Epoch 42/256

144/144 - 1s - 8ms/step - ia: 0.9577 - loss: 0.0095 - mae: 0.0697 - rmse: 0.0969 - smape: 0.1712 - val_ia: 0.9665 - val_loss: 0.0037 - val_mae: 0.0450 - val_rmse: 0.0600 - val_smape: 0.1392

Epoch 43/256

144/144 - 1s - 8ms/step - ia: 0.9576 - loss: 0.0097 - mae: 0.0699 - rmse: 0.0976 - smape: 0.1702 - val_ia: 0.9711 - val_loss: 0.0031 - val_mae: 0.0389 - val_rmse: 0.0550 - val_smape: 0.1224

Epoch 44/256

144/144 - 1s - 10ms/step - ia: 0.9582 - loss: 0.0094 - mae: 0.0689 - rmse: 0.0962 - smape: 0.1698 - val_ia: 0.9693 - val_loss: 0.0033 - val_mae: 0.0410 - val_rmse: 0.0568 - val_smape: 0.1335

Epoch 45/256

144/144 - 2s - 11ms/step - ia: 0.9574 - loss: 0.0097 - mae: 0.0702 - rmse: 0.0976 - smape: 0.1717 - val_ia: 0.9706 - val_loss: 0.0031 - val_mae: 0.0391 - val_rmse: 0.0552 - val_smape: 0.1253

Epoch 46/256

144/144 - 2s - 17ms/step - ia: 0.9580 - loss: 0.0095 - mae: 0.0693 - rmse: 0.0965 - smape: 0.1689 - val_ia: 0.9612 - val_loss: 0.0046 - val_mae: 0.0525 - val_rmse: 0.0676 - val_smape: 0.1586

Epoch 47/256

144/144 - 2s - 11ms/step - ia: 0.9573 - loss: 0.0098 - mae: 0.0703 - rmse: 0.0983 - smape: 0.1717 - val_ia: 0.9730 - val_loss: 0.0029 - val_mae: 0.0366 - val_rmse: 0.0536 - val_smape: 0.1180

Epoch 48/256

144/144 - 2s - 11ms/step - ia: 0.9576 - loss: 0.0096 - mae: 0.0699 - rmse: 0.0972 - smape: 0.1710 - val_ia: 0.9717 - val_loss: 0.0030 - val_mae: 0.0380 - val_rmse: 0.0543 - val_smape: 0.1218

Epoch 49/256

144/144 - 1s - 10ms/step - ia: 0.9578 - loss: 0.0095 - mae: 0.0696 - rmse: 0.0970 - smape: 0.1703 - val_ia: 0.9657 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0620 - val_smape: 0.1292

Epoch 50/256

144/144 - 3s - 18ms/step - ia: 0.9582 - loss: 0.0094 - mae: 0.0689 - rmse: 0.0961 - smape: 0.1689 - val_ia: 0.9719 - val_loss: 0.0031 - val_mae: 0.0380 - val_rmse: 0.0547 - val_smape: 0.1125

Epoch 51/256

144/144 - 2s - 11ms/step - ia: 0.9578 - loss: 0.0095 - mae: 0.0696 - rmse: 0.0969 - smape: 0.1692 - val_ia: 0.9726 - val_loss: 0.0029 - val_mae: 0.0370 - val_rmse: 0.0533 - val_smape: 0.1210

Epoch 52/256

144/144 - 2s - 17ms/step - ia: 0.9580 - loss: 0.0095 - mae: 0.0692 - rmse: 0.0966 - smape: 0.1688 - val_ia: 0.9674 - val_loss: 0.0035 - val_mae: 0.0434 - val_rmse: 0.0584 - val_smape: 0.1396

Epoch 53/256

144/144 - 1s - 10ms/step - ia: 0.9579 - loss: 0.0095 - mae: 0.0694 - rmse: 0.0969 - smape: 0.1682 - val_ia: 0.9699 - val_loss: 0.0032 - val_mae: 0.0404 - val_rmse: 0.0558 - val_smape: 0.1281

Epoch 54/256

144/144 - 1s - 7ms/step - ia: 0.9573 - loss: 0.0099 - mae: 0.0704 - rmse: 0.0988 - smape: 0.1705 - val_ia: 0.9684 - val_loss: 0.0034 - val_mae: 0.0422 - val_rmse: 0.0579 - val_smape: 0.1332

Epoch 55/256

144/144 - 1s - 10ms/step - ia: 0.9579 - loss: 0.0095 - mae: 0.0694 - rmse: 0.0969 - smape: 0.1686 - val_ia: 0.9582 - val_loss: 0.0051 - val_mae: 0.0554 - val_rmse: 0.0698 - val_smape: 0.1621

Epoch 56/256

144/144 - 1s - 9ms/step - ia: 0.9584 - loss: 0.0094 - mae: 0.0687 - rmse: 0.0959 - smape: 0.1680 - val_ia: 0.9689 - val_loss: 0.0033 - val_mae: 0.0413 - val_rmse: 0.0575 - val_smape: 0.1344

Epoch 57/256

144/144 - 2s - 12ms/step - ia: 0.9585 - loss: 0.0093 - mae: 0.0685 - rmse: 0.0955 - smape: 0.1669 - val_ia: 0.9676 - val_loss: 0.0035 - val_mae: 0.0431 - val_rmse: 0.0581 - val_smape: 0.1370

Epoch 58/256

144/144 - 1s - 9ms/step - ia: 0.9583 - loss: 0.0094 - mae: 0.0687 - rmse: 0.0963 - smape: 0.1682 - val_ia: 0.9626 - val_loss: 0.0045 - val_mae: 0.0505 - val_rmse: 0.0663 - val_smape: 0.1339

Epoch 59/256

144/144 - 3s - 18ms/step - ia: 0.9580 - loss: 0.0095 - mae: 0.0693 - rmse: 0.0968 - smape: 0.1683 - val_ia: 0.9706 - val_loss: 0.0031 - val_mae: 0.0395 - val_rmse: 0.0553 - val_smape: 0.1216

Epoch 60/256

144/144 - 2s - 11ms/step - ia: 0.9584 - loss: 0.0094 - mae: 0.0686 - rmse: 0.0961 - smape: 0.1682 - val_ia: 0.9667 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0604 - val_smape: 0.1454

Epoch 61/256

144/144 - 2s - 11ms/step - ia: 0.9582 - loss: 0.0094 - mae: 0.0689 - rmse: 0.0960 - smape: 0.1679 - val_ia: 0.9666 - val_loss: 0.0036 - val_mae: 0.0447 - val_rmse: 0.0602 - val_smape: 0.1361

Epoch 62/256

144/144 - 3s - 18ms/step - ia: 0.9582 - loss: 0.0094 - mae: 0.0690 - rmse: 0.0962 - smape: 0.1676 - val_ia: 0.9695 - val_loss: 0.0033 - val_mae: 0.0407 - val_rmse: 0.0564 - val_smape: 0.1258

Epoch 63/256

144/144 - 1s - 9ms/step - ia: 0.9589 - loss: 0.0091 - mae: 0.0677 - rmse: 0.0949 - smape: 0.1653 - val_ia: 0.9686 - val_loss: 0.0035 - val_mae: 0.0424 - val_rmse: 0.0581 - val_smape: 0.1218

Epoch 64/256

144/144 - 2s - 12ms/step - ia: 0.9588 - loss: 0.0092 - mae: 0.0680 - rmse: 0.0952 - smape: 0.1652 - val_ia: 0.9684 - val_loss: 0.0035 - val_mae: 0.0426 - val_rmse: 0.0580 - val_smape: 0.1249

Epoch 65/256

144/144 - 3s - 19ms/step - ia: 0.9584 - loss: 0.0093 - mae: 0.0686 - rmse: 0.0958 - smape: 0.1669 - val_ia: 0.9658 - val_loss: 0.0038 - val_mae: 0.0455 - val_rmse: 0.0610 - val_smape: 0.1351

Epoch 66/256

144/144 - 3s - 19ms/step - ia: 0.9591 - loss: 0.0090 - mae: 0.0674 - rmse: 0.0944 - smape: 0.1663 - val_ia: 0.9704 - val_loss: 0.0031 - val_mae: 0.0399 - val_rmse: 0.0554 - val_smape: 0.1259

Epoch 66: early stopping

Restoring model weights from the end of the best epoch: 51.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 43s 267ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 94%|█████████▍| 47/50 [3:22:37<08:16, 165.55s/trial, best loss: 0.0019293013493423897]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 9s - 63ms/step - ia: 0.6967 - loss: 0.6324 - mae: 0.5467 - rmse: 0.7123 - smape: 0.8259 - val_ia: 0.9060 - val_loss: 0.0290 - val_mae: 0.1253 - val_rmse: 0.1705 - val_smape: 0.3286

Epoch 2/256

144/144 - 1s - 6ms/step - ia: 0.8459 - loss: 0.1182 - mae: 0.2568 - rmse: 0.3412 - smape: 0.5381 - val_ia: 0.9126 - val_loss: 0.0228 - val_mae: 0.1172 - val_rmse: 0.1505 - val_smape: 0.3312

Epoch 3/256

144/144 - 1s - 7ms/step - ia: 0.8817 - loss: 0.0695 - mae: 0.1954 - rmse: 0.2622 - smape: 0.4362 - val_ia: 0.9275 - val_loss: 0.0161 - val_mae: 0.0965 - val_rmse: 0.1267 - val_smape: 0.2828

Epoch 4/256

144/144 - 1s - 10ms/step - ia: 0.9008 - loss: 0.0489 - mae: 0.1632 - rmse: 0.2206 - smape: 0.3796 - val_ia: 0.9377 - val_loss: 0.0121 - val_mae: 0.0829 - val_rmse: 0.1093 - val_smape: 0.2384

Epoch 5/256

144/144 - 1s - 8ms/step - ia: 0.9122 - loss: 0.0385 - mae: 0.1442 - rmse: 0.1955 - smape: 0.3388 - val_ia: 0.9519 - val_loss: 0.0087 - val_mae: 0.0642 - val_rmse: 0.0930 - val_smape: 0.1857

Epoch 6/256

144/144 - 1s - 9ms/step - ia: 0.9193 - loss: 0.0325 - mae: 0.1325 - rmse: 0.1797 - smape: 0.3127 - val_ia: 0.9481 - val_loss: 0.0087 - val_mae: 0.0686 - val_rmse: 0.0930 - val_smape: 0.2002

Epoch 7/256

144/144 - 1s - 9ms/step - ia: 0.9245 - loss: 0.0286 - mae: 0.1240 - rmse: 0.1688 - smape: 0.2924 - val_ia: 0.9504 - val_loss: 0.0080 - val_mae: 0.0654 - val_rmse: 0.0888 - val_smape: 0.1957

Epoch 8/256

144/144 - 1s - 10ms/step - ia: 0.9281 - loss: 0.0259 - mae: 0.1182 - rmse: 0.1606 - smape: 0.2790 - val_ia: 0.9502 - val_loss: 0.0078 - val_mae: 0.0659 - val_rmse: 0.0878 - val_smape: 0.1872

Epoch 9/256

144/144 - 1s - 10ms/step - ia: 0.9300 - loss: 0.0246 - mae: 0.1149 - rmse: 0.1566 - smape: 0.2709 - val_ia: 0.9562 - val_loss: 0.0065 - val_mae: 0.0578 - val_rmse: 0.0805 - val_smape: 0.1727

Epoch 10/256

144/144 - 1s - 10ms/step - ia: 0.9322 - loss: 0.0231 - mae: 0.1112 - rmse: 0.1514 - smape: 0.2619 - val_ia: 0.9537 - val_loss: 0.0070 - val_mae: 0.0611 - val_rmse: 0.0828 - val_smape: 0.1779

Epoch 11/256

144/144 - 2s - 11ms/step - ia: 0.9336 - loss: 0.0223 - mae: 0.1090 - rmse: 0.1488 - smape: 0.2553 - val_ia: 0.9536 - val_loss: 0.0068 - val_mae: 0.0616 - val_rmse: 0.0817 - val_smape: 0.1756

Epoch 12/256

144/144 - 3s - 17ms/step - ia: 0.9357 - loss: 0.0211 - mae: 0.1057 - rmse: 0.1447 - smape: 0.2478 - val_ia: 0.9542 - val_loss: 0.0067 - val_mae: 0.0607 - val_rmse: 0.0812 - val_smape: 0.1644

Epoch 13/256

144/144 - 3s - 18ms/step - ia: 0.9361 - loss: 0.0208 - mae: 0.1048 - rmse: 0.1439 - smape: 0.2443 - val_ia: 0.9604 - val_loss: 0.0054 - val_mae: 0.0525 - val_rmse: 0.0733 - val_smape: 0.1504

Epoch 14/256

144/144 - 2s - 11ms/step - ia: 0.9377 - loss: 0.0198 - mae: 0.1023 - rmse: 0.1403 - smape: 0.2379 - val_ia: 0.9572 - val_loss: 0.0059 - val_mae: 0.0570 - val_rmse: 0.0759 - val_smape: 0.1671

Epoch 15/256

144/144 - 2s - 11ms/step - ia: 0.9380 - loss: 0.0197 - mae: 0.1019 - rmse: 0.1398 - smape: 0.2378 - val_ia: 0.9579 - val_loss: 0.0058 - val_mae: 0.0559 - val_rmse: 0.0756 - val_smape: 0.1506

Epoch 16/256

144/144 - 3s - 17ms/step - ia: 0.9389 - loss: 0.0191 - mae: 0.1005 - rmse: 0.1379 - smape: 0.2325 - val_ia: 0.9612 - val_loss: 0.0051 - val_mae: 0.0513 - val_rmse: 0.0710 - val_smape: 0.1618

Epoch 17/256

144/144 - 1s - 9ms/step - ia: 0.9397 - loss: 0.0187 - mae: 0.0990 - rmse: 0.1363 - smape: 0.2299 - val_ia: 0.9646 - val_loss: 0.0046 - val_mae: 0.0470 - val_rmse: 0.0674 - val_smape: 0.1360

Epoch 18/256

144/144 - 1s - 10ms/step - ia: 0.9404 - loss: 0.0183 - mae: 0.0980 - rmse: 0.1346 - smape: 0.2281 - val_ia: 0.9624 - val_loss: 0.0048 - val_mae: 0.0500 - val_rmse: 0.0688 - val_smape: 0.1489

Epoch 19/256

144/144 - 1s - 10ms/step - ia: 0.9415 - loss: 0.0176 - mae: 0.0961 - rmse: 0.1319 - smape: 0.2242 - val_ia: 0.9573 - val_loss: 0.0057 - val_mae: 0.0570 - val_rmse: 0.0758 - val_smape: 0.1776

Epoch 20/256

144/144 - 2s - 17ms/step - ia: 0.9411 - loss: 0.0178 - mae: 0.0967 - rmse: 0.1332 - smape: 0.2230 - val_ia: 0.9660 - val_loss: 0.0042 - val_mae: 0.0455 - val_rmse: 0.0646 - val_smape: 0.1458

Epoch 21/256

144/144 - 1s - 8ms/step - ia: 0.9421 - loss: 0.0172 - mae: 0.0951 - rmse: 0.1308 - smape: 0.2197 - val_ia: 0.9594 - val_loss: 0.0053 - val_mae: 0.0540 - val_rmse: 0.0720 - val_smape: 0.1533

Epoch 22/256

144/144 - 1s - 9ms/step - ia: 0.9424 - loss: 0.0172 - mae: 0.0947 - rmse: 0.1306 - smape: 0.2183 - val_ia: 0.9605 - val_loss: 0.0051 - val_mae: 0.0527 - val_rmse: 0.0706 - val_smape: 0.1488

Epoch 23/256

144/144 - 1s - 9ms/step - ia: 0.9427 - loss: 0.0169 - mae: 0.0941 - rmse: 0.1295 - smape: 0.2166 - val_ia: 0.9679 - val_loss: 0.0038 - val_mae: 0.0430 - val_rmse: 0.0612 - val_smape: 0.1361

Epoch 24/256

144/144 - 2s - 14ms/step - ia: 0.9432 - loss: 0.0169 - mae: 0.0934 - rmse: 0.1293 - smape: 0.2122 - val_ia: 0.9632 - val_loss: 0.0045 - val_mae: 0.0486 - val_rmse: 0.0663 - val_smape: 0.1513

Epoch 25/256

144/144 - 3s - 17ms/step - ia: 0.9433 - loss: 0.0166 - mae: 0.0931 - rmse: 0.1283 - smape: 0.2131 - val_ia: 0.9643 - val_loss: 0.0044 - val_mae: 0.0479 - val_rmse: 0.0656 - val_smape: 0.1381

Epoch 26/256

144/144 - 3s - 17ms/step - ia: 0.9437 - loss: 0.0166 - mae: 0.0925 - rmse: 0.1283 - smape: 0.2103 - val_ia: 0.9680 - val_loss: 0.0038 - val_mae: 0.0428 - val_rmse: 0.0611 - val_smape: 0.1320

Epoch 27/256

144/144 - 1s - 10ms/step - ia: 0.9442 - loss: 0.0163 - mae: 0.0918 - rmse: 0.1272 - smape: 0.2085 - val_ia: 0.9632 - val_loss: 0.0045 - val_mae: 0.0492 - val_rmse: 0.0659 - val_smape: 0.1438

Epoch 28/256

144/144 - 1s - 9ms/step - ia: 0.9438 - loss: 0.0165 - mae: 0.0923 - rmse: 0.1279 - smape: 0.2096 - val_ia: 0.9637 - val_loss: 0.0045 - val_mae: 0.0488 - val_rmse: 0.0663 - val_smape: 0.1379

Epoch 29/256

144/144 - 1s - 8ms/step - ia: 0.9447 - loss: 0.0161 - mae: 0.0909 - rmse: 0.1262 - smape: 0.2044 - val_ia: 0.9640 - val_loss: 0.0043 - val_mae: 0.0480 - val_rmse: 0.0650 - val_smape: 0.1420

Epoch 30/256

144/144 - 1s - 10ms/step - ia: 0.9446 - loss: 0.0162 - mae: 0.0909 - rmse: 0.1268 - smape: 0.2055 - val_ia: 0.9654 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0641 - val_smape: 0.1461

Epoch 31/256

144/144 - 2s - 12ms/step - ia: 0.9449 - loss: 0.0161 - mae: 0.0906 - rmse: 0.1262 - smape: 0.2040 - val_ia: 0.9595 - val_loss: 0.0051 - val_mae: 0.0540 - val_rmse: 0.0706 - val_smape: 0.1514

Epoch 32/256

144/144 - 3s - 18ms/step - ia: 0.9452 - loss: 0.0158 - mae: 0.0901 - rmse: 0.1251 - smape: 0.2039 - val_ia: 0.9689 - val_loss: 0.0036 - val_mae: 0.0418 - val_rmse: 0.0590 - val_smape: 0.1303

Epoch 33/256

144/144 - 1s - 10ms/step - ia: 0.9452 - loss: 0.0160 - mae: 0.0900 - rmse: 0.1260 - smape: 0.2024 - val_ia: 0.9674 - val_loss: 0.0037 - val_mae: 0.0435 - val_rmse: 0.0600 - val_smape: 0.1372

Epoch 34/256

144/144 - 3s - 17ms/step - ia: 0.9450 - loss: 0.0160 - mae: 0.0903 - rmse: 0.1260 - smape: 0.2011 - val_ia: 0.9664 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0613 - val_smape: 0.1444

Epoch 35/256

144/144 - 2s - 11ms/step - ia: 0.9453 - loss: 0.0160 - mae: 0.0900 - rmse: 0.1260 - smape: 0.2021 - val_ia: 0.9628 - val_loss: 0.0043 - val_mae: 0.0491 - val_rmse: 0.0651 - val_smape: 0.1622

Epoch 36/256

144/144 - 3s - 18ms/step - ia: 0.9463 - loss: 0.0153 - mae: 0.0884 - rmse: 0.1231 - smape: 0.1982 - val_ia: 0.9605 - val_loss: 0.0048 - val_mae: 0.0519 - val_rmse: 0.0693 - val_smape: 0.1689

Epoch 37/256

144/144 - 1s - 10ms/step - ia: 0.9460 - loss: 0.0155 - mae: 0.0887 - rmse: 0.1238 - smape: 0.1979 - val_ia: 0.9663 - val_loss: 0.0038 - val_mae: 0.0445 - val_rmse: 0.0612 - val_smape: 0.1415

Epoch 38/256

144/144 - 1s - 10ms/step - ia: 0.9463 - loss: 0.0153 - mae: 0.0883 - rmse: 0.1231 - smape: 0.1966 - val_ia: 0.9646 - val_loss: 0.0040 - val_mae: 0.0474 - val_rmse: 0.0629 - val_smape: 0.1506

Epoch 39/256

144/144 - 1s - 9ms/step - ia: 0.9469 - loss: 0.0151 - mae: 0.0874 - rmse: 0.1221 - smape: 0.1952 - val_ia: 0.9642 - val_loss: 0.0041 - val_mae: 0.0473 - val_rmse: 0.0636 - val_smape: 0.1561

Epoch 40/256

144/144 - 1s - 10ms/step - ia: 0.9461 - loss: 0.0154 - mae: 0.0885 - rmse: 0.1235 - smape: 0.1984 - val_ia: 0.9668 - val_loss: 0.0038 - val_mae: 0.0438 - val_rmse: 0.0613 - val_smape: 0.1395

Epoch 41/256

144/144 - 1s - 10ms/step - ia: 0.9471 - loss: 0.0150 - mae: 0.0871 - rmse: 0.1219 - smape: 0.1947 - val_ia: 0.9620 - val_loss: 0.0044 - val_mae: 0.0503 - val_rmse: 0.0656 - val_smape: 0.1627

Epoch 42/256

144/144 - 1s - 7ms/step - ia: 0.9468 - loss: 0.0152 - mae: 0.0875 - rmse: 0.1227 - smape: 0.1926 - val_ia: 0.9570 - val_loss: 0.0056 - val_mae: 0.0574 - val_rmse: 0.0733 - val_smape: 0.1581

Epoch 43/256

144/144 - 2s - 10ms/step - ia: 0.9462 - loss: 0.0154 - mae: 0.0884 - rmse: 0.1235 - smape: 0.1957 - val_ia: 0.9679 - val_loss: 0.0036 - val_mae: 0.0432 - val_rmse: 0.0599 - val_smape: 0.1389

Epoch 44/256

144/144 - 1s - 9ms/step - ia: 0.9467 - loss: 0.0153 - mae: 0.0877 - rmse: 0.1229 - smape: 0.1945 - val_ia: 0.9666 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0605 - val_smape: 0.1446

Epoch 45/256

144/144 - 1s - 10ms/step - ia: 0.9463 - loss: 0.0154 - mae: 0.0882 - rmse: 0.1236 - smape: 0.1939 - val_ia: 0.9643 - val_loss: 0.0041 - val_mae: 0.0470 - val_rmse: 0.0632 - val_smape: 0.1514

Epoch 46/256

144/144 - 2s - 10ms/step - ia: 0.9460 - loss: 0.0156 - mae: 0.0887 - rmse: 0.1242 - smape: 0.1948 - val_ia: 0.9584 - val_loss: 0.0051 - val_mae: 0.0562 - val_rmse: 0.0718 - val_smape: 0.1623

Epoch 47/256

144/144 - 3s - 17ms/step - ia: 0.9476 - loss: 0.0149 - mae: 0.0864 - rmse: 0.1213 - smape: 0.1902 - val_ia: 0.9680 - val_loss: 0.0035 - val_mae: 0.0423 - val_rmse: 0.0589 - val_smape: 0.1350

Epoch 48/256

144/144 - 2s - 11ms/step - ia: 0.9470 - loss: 0.0150 - mae: 0.0871 - rmse: 0.1222 - smape: 0.1932 - val_ia: 0.9658 - val_loss: 0.0038 - val_mae: 0.0457 - val_rmse: 0.0611 - val_smape: 0.1423

Epoch 49/256

144/144 - 3s - 19ms/step - ia: 0.9471 - loss: 0.0150 - mae: 0.0869 - rmse: 0.1222 - smape: 0.1918 - val_ia: 0.9621 - val_loss: 0.0046 - val_mae: 0.0511 - val_rmse: 0.0666 - val_smape: 0.1434

Epoch 50/256

144/144 - 1s - 8ms/step - ia: 0.9467 - loss: 0.0153 - mae: 0.0876 - rmse: 0.1231 - smape: 0.1925 - val_ia: 0.9679 - val_loss: 0.0036 - val_mae: 0.0428 - val_rmse: 0.0594 - val_smape: 0.1310

Epoch 51/256

144/144 - 1s - 9ms/step - ia: 0.9469 - loss: 0.0152 - mae: 0.0874 - rmse: 0.1227 - smape: 0.1924 - val_ia: 0.9680 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0587 - val_smape: 0.1315

Epoch 52/256

144/144 - 1s - 6ms/step - ia: 0.9473 - loss: 0.0149 - mae: 0.0867 - rmse: 0.1216 - smape: 0.1893 - val_ia: 0.9647 - val_loss: 0.0041 - val_mae: 0.0473 - val_rmse: 0.0628 - val_smape: 0.1413

Epoch 53/256

144/144 - 1s - 5ms/step - ia: 0.9473 - loss: 0.0149 - mae: 0.0866 - rmse: 0.1213 - smape: 0.1912 - val_ia: 0.9684 - val_loss: 0.0036 - val_mae: 0.0426 - val_rmse: 0.0596 - val_smape: 0.1196

Epoch 54/256

144/144 - 1s - 5ms/step - ia: 0.9476 - loss: 0.0149 - mae: 0.0862 - rmse: 0.1214 - smape: 0.1899 - val_ia: 0.9716 - val_loss: 0.0031 - val_mae: 0.0383 - val_rmse: 0.0551 - val_smape: 0.1200

Epoch 55/256

144/144 - 1s - 5ms/step - ia: 0.9472 - loss: 0.0151 - mae: 0.0868 - rmse: 0.1222 - smape: 0.1902 - val_ia: 0.9621 - val_loss: 0.0046 - val_mae: 0.0512 - val_rmse: 0.0666 - val_smape: 0.1399

Epoch 56/256

144/144 - 1s - 4ms/step - ia: 0.9471 - loss: 0.0151 - mae: 0.0870 - rmse: 0.1223 - smape: 0.1908 - val_ia: 0.9596 - val_loss: 0.0048 - val_mae: 0.0536 - val_rmse: 0.0681 - val_smape: 0.1601

Epoch 57/256

144/144 - 1s - 5ms/step - ia: 0.9476 - loss: 0.0147 - mae: 0.0861 - rmse: 0.1208 - smape: 0.1899 - val_ia: 0.9717 - val_loss: 0.0031 - val_mae: 0.0384 - val_rmse: 0.0551 - val_smape: 0.1204

Epoch 58/256

144/144 - 1s - 7ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0871 - rmse: 0.1227 - smape: 0.1897 - val_ia: 0.9661 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0605 - val_smape: 0.1378

Epoch 59/256

144/144 - 2s - 12ms/step - ia: 0.9465 - loss: 0.0154 - mae: 0.0879 - rmse: 0.1235 - smape: 0.1914 - val_ia: 0.9676 - val_loss: 0.0036 - val_mae: 0.0433 - val_rmse: 0.0596 - val_smape: 0.1412

Epoch 60/256

144/144 - 1s - 7ms/step - ia: 0.9476 - loss: 0.0149 - mae: 0.0861 - rmse: 0.1213 - smape: 0.1881 - val_ia: 0.9600 - val_loss: 0.0050 - val_mae: 0.0539 - val_rmse: 0.0694 - val_smape: 0.1450

Epoch 61/256

144/144 - 2s - 12ms/step - ia: 0.9468 - loss: 0.0153 - mae: 0.0874 - rmse: 0.1234 - smape: 0.1908 - val_ia: 0.9684 - val_loss: 0.0034 - val_mae: 0.0421 - val_rmse: 0.0577 - val_smape: 0.1383

Epoch 62/256

144/144 - 2s - 17ms/step - ia: 0.9473 - loss: 0.0150 - mae: 0.0865 - rmse: 0.1218 - smape: 0.1877 - val_ia: 0.9611 - val_loss: 0.0047 - val_mae: 0.0530 - val_rmse: 0.0684 - val_smape: 0.1534

Epoch 63/256

144/144 - 1s - 10ms/step - ia: 0.9464 - loss: 0.0156 - mae: 0.0882 - rmse: 0.1242 - smape: 0.1912 - val_ia: 0.9612 - val_loss: 0.0050 - val_mae: 0.0524 - val_rmse: 0.0701 - val_smape: 0.1344

Epoch 64/256

144/144 - 1s - 10ms/step - ia: 0.9472 - loss: 0.0150 - mae: 0.0868 - rmse: 0.1220 - smape: 0.1897 - val_ia: 0.9665 - val_loss: 0.0039 - val_mae: 0.0452 - val_rmse: 0.0617 - val_smape: 0.1263

Epoch 65/256

144/144 - 1s - 9ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0872 - rmse: 0.1222 - smape: 0.1914 - val_ia: 0.9638 - val_loss: 0.0044 - val_mae: 0.0487 - val_rmse: 0.0654 - val_smape: 0.1320

Epoch 66/256

144/144 - 1s - 8ms/step - ia: 0.9478 - loss: 0.0146 - mae: 0.0858 - rmse: 0.1202 - smape: 0.1885 - val_ia: 0.9669 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0598 - val_smape: 0.1438

Epoch 67/256

144/144 - 3s - 19ms/step - ia: 0.9476 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1210 - smape: 0.1881 - val_ia: 0.9672 - val_loss: 0.0036 - val_mae: 0.0437 - val_rmse: 0.0597 - val_smape: 0.1426

Epoch 68/256

144/144 - 1s - 9ms/step - ia: 0.9479 - loss: 0.0148 - mae: 0.0857 - rmse: 0.1209 - smape: 0.1866 - val_ia: 0.9675 - val_loss: 0.0037 - val_mae: 0.0439 - val_rmse: 0.0598 - val_smape: 0.1233

Epoch 69/256

144/144 - 1s - 9ms/step - ia: 0.9475 - loss: 0.0148 - mae: 0.0863 - rmse: 0.1212 - smape: 0.1882 - val_ia: 0.9689 - val_loss: 0.0034 - val_mae: 0.0416 - val_rmse: 0.0572 - val_smape: 0.1293

Epoch 70/256

144/144 - 1s - 9ms/step - ia: 0.9485 - loss: 0.0144 - mae: 0.0847 - rmse: 0.1195 - smape: 0.1851 - val_ia: 0.9563 - val_loss: 0.0058 - val_mae: 0.0589 - val_rmse: 0.0746 - val_smape: 0.1534

Epoch 71/256

144/144 - 2s - 11ms/step - ia: 0.9476 - loss: 0.0150 - mae: 0.0861 - rmse: 0.1220 - smape: 0.1876 - val_ia: 0.9569 - val_loss: 0.0058 - val_mae: 0.0581 - val_rmse: 0.0752 - val_smape: 0.1412

Epoch 72/256

144/144 - 1s - 10ms/step - ia: 0.9478 - loss: 0.0148 - mae: 0.0859 - rmse: 0.1211 - smape: 0.1879 - val_ia: 0.9577 - val_loss: 0.0056 - val_mae: 0.0570 - val_rmse: 0.0735 - val_smape: 0.1463

Epoch 72: early stopping

Restoring model weights from the end of the best epoch: 57.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 41s 258ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 96%|█████████▌| 48/50 [3:24:41<05:05, 152.86s/trial, best loss: 0.0019293013493423897]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 10s - 68ms/step - ia: 0.7584 - loss: 0.3670 - mae: 0.4220 - rmse: 0.5518 - smape: 0.7165 - val_ia: 0.9112 - val_loss: 0.0231 - val_mae: 0.1185 - val_rmse: 0.1513 - val_smape: 0.3367

Epoch 2/256

144/144 - 1s - 6ms/step - ia: 0.8759 - loss: 0.0773 - mae: 0.2055 - rmse: 0.2757 - smape: 0.4592 - val_ia: 0.9395 - val_loss: 0.0119 - val_mae: 0.0804 - val_rmse: 0.1080 - val_smape: 0.2052

Epoch 3/256

144/144 - 1s - 6ms/step - ia: 0.9038 - loss: 0.0463 - mae: 0.1586 - rmse: 0.2140 - smape: 0.3687 - val_ia: 0.9435 - val_loss: 0.0097 - val_mae: 0.0747 - val_rmse: 0.0972 - val_smape: 0.2204

Epoch 4/256

144/144 - 1s - 10ms/step - ia: 0.9180 - loss: 0.0342 - mae: 0.1349 - rmse: 0.1843 - smape: 0.3171 - val_ia: 0.9522 - val_loss: 0.0074 - val_mae: 0.0630 - val_rmse: 0.0852 - val_smape: 0.1950

Epoch 5/256

144/144 - 1s - 8ms/step - ia: 0.9250 - loss: 0.0284 - mae: 0.1233 - rmse: 0.1679 - smape: 0.2915 - val_ia: 0.9498 - val_loss: 0.0078 - val_mae: 0.0663 - val_rmse: 0.0872 - val_smape: 0.1878

Epoch 6/256

144/144 - 1s - 10ms/step - ia: 0.9297 - loss: 0.0251 - mae: 0.1155 - rmse: 0.1580 - smape: 0.2704 - val_ia: 0.9550 - val_loss: 0.0066 - val_mae: 0.0599 - val_rmse: 0.0807 - val_smape: 0.1912

Epoch 7/256

144/144 - 1s - 8ms/step - ia: 0.9334 - loss: 0.0228 - mae: 0.1093 - rmse: 0.1512 - smape: 0.2571 - val_ia: 0.9529 - val_loss: 0.0068 - val_mae: 0.0618 - val_rmse: 0.0815 - val_smape: 0.1891

Epoch 8/256

144/144 - 1s - 10ms/step - ia: 0.9351 - loss: 0.0213 - mae: 0.1067 - rmse: 0.1456 - smape: 0.2488 - val_ia: 0.9595 - val_loss: 0.0057 - val_mae: 0.0540 - val_rmse: 0.0748 - val_smape: 0.1601

Epoch 9/256

144/144 - 3s - 18ms/step - ia: 0.9367 - loss: 0.0206 - mae: 0.1039 - rmse: 0.1430 - smape: 0.2411 - val_ia: 0.9547 - val_loss: 0.0065 - val_mae: 0.0601 - val_rmse: 0.0794 - val_smape: 0.1717

Epoch 10/256

144/144 - 1s - 10ms/step - ia: 0.9380 - loss: 0.0198 - mae: 0.1017 - rmse: 0.1403 - smape: 0.2341 - val_ia: 0.9606 - val_loss: 0.0052 - val_mae: 0.0524 - val_rmse: 0.0714 - val_smape: 0.1632

Epoch 11/256

144/144 - 1s - 8ms/step - ia: 0.9393 - loss: 0.0189 - mae: 0.0997 - rmse: 0.1371 - smape: 0.2305 - val_ia: 0.9632 - val_loss: 0.0047 - val_mae: 0.0490 - val_rmse: 0.0684 - val_smape: 0.1569

Epoch 12/256

144/144 - 1s - 10ms/step - ia: 0.9399 - loss: 0.0186 - mae: 0.0987 - rmse: 0.1358 - smape: 0.2264 - val_ia: 0.9618 - val_loss: 0.0050 - val_mae: 0.0512 - val_rmse: 0.0699 - val_smape: 0.1493

Epoch 13/256

144/144 - 2s - 11ms/step - ia: 0.9408 - loss: 0.0182 - mae: 0.0974 - rmse: 0.1345 - smape: 0.2244 - val_ia: 0.9645 - val_loss: 0.0045 - val_mae: 0.0475 - val_rmse: 0.0667 - val_smape: 0.1511

Epoch 14/256

144/144 - 1s - 10ms/step - ia: 0.9417 - loss: 0.0177 - mae: 0.0958 - rmse: 0.1327 - smape: 0.2187 - val_ia: 0.9577 - val_loss: 0.0055 - val_mae: 0.0562 - val_rmse: 0.0732 - val_smape: 0.1733

Epoch 15/256

144/144 - 1s - 9ms/step - ia: 0.9420 - loss: 0.0174 - mae: 0.0952 - rmse: 0.1316 - smape: 0.2178 - val_ia: 0.9537 - val_loss: 0.0064 - val_mae: 0.0613 - val_rmse: 0.0783 - val_smape: 0.1735

Epoch 16/256

144/144 - 2s - 11ms/step - ia: 0.9420 - loss: 0.0174 - mae: 0.0953 - rmse: 0.1315 - smape: 0.2161 - val_ia: 0.9644 - val_loss: 0.0044 - val_mae: 0.0477 - val_rmse: 0.0654 - val_smape: 0.1474

Epoch 17/256

144/144 - 1s - 9ms/step - ia: 0.9429 - loss: 0.0171 - mae: 0.0939 - rmse: 0.1299 - smape: 0.2133 - val_ia: 0.9585 - val_loss: 0.0053 - val_mae: 0.0558 - val_rmse: 0.0720 - val_smape: 0.1681

Epoch 18/256

144/144 - 1s - 10ms/step - ia: 0.9433 - loss: 0.0169 - mae: 0.0932 - rmse: 0.1295 - smape: 0.2116 - val_ia: 0.9633 - val_loss: 0.0044 - val_mae: 0.0490 - val_rmse: 0.0658 - val_smape: 0.1577

Epoch 19/256

144/144 - 2s - 17ms/step - ia: 0.9435 - loss: 0.0168 - mae: 0.0928 - rmse: 0.1291 - smape: 0.2079 - val_ia: 0.9681 - val_loss: 0.0038 - val_mae: 0.0428 - val_rmse: 0.0611 - val_smape: 0.1267

Epoch 20/256

144/144 - 1s - 9ms/step - ia: 0.9437 - loss: 0.0166 - mae: 0.0925 - rmse: 0.1282 - smape: 0.2094 - val_ia: 0.9649 - val_loss: 0.0044 - val_mae: 0.0470 - val_rmse: 0.0659 - val_smape: 0.1348

Epoch 21/256

144/144 - 1s - 10ms/step - ia: 0.9444 - loss: 0.0163 - mae: 0.0914 - rmse: 0.1272 - smape: 0.2070 - val_ia: 0.9671 - val_loss: 0.0039 - val_mae: 0.0443 - val_rmse: 0.0621 - val_smape: 0.1311

Epoch 22/256

144/144 - 1s - 8ms/step - ia: 0.9440 - loss: 0.0164 - mae: 0.0921 - rmse: 0.1274 - smape: 0.2071 - val_ia: 0.9630 - val_loss: 0.0044 - val_mae: 0.0493 - val_rmse: 0.0657 - val_smape: 0.1607

Epoch 23/256

144/144 - 2s - 12ms/step - ia: 0.9442 - loss: 0.0164 - mae: 0.0916 - rmse: 0.1273 - smape: 0.2062 - val_ia: 0.9702 - val_loss: 0.0035 - val_mae: 0.0403 - val_rmse: 0.0586 - val_smape: 0.1310

Epoch 24/256

144/144 - 3s - 18ms/step - ia: 0.9452 - loss: 0.0159 - mae: 0.0902 - rmse: 0.1254 - smape: 0.2041 - val_ia: 0.9655 - val_loss: 0.0041 - val_mae: 0.0459 - val_rmse: 0.0633 - val_smape: 0.1412

Epoch 25/256

144/144 - 1s - 9ms/step - ia: 0.9455 - loss: 0.0156 - mae: 0.0895 - rmse: 0.1243 - smape: 0.2009 - val_ia: 0.9646 - val_loss: 0.0042 - val_mae: 0.0470 - val_rmse: 0.0641 - val_smape: 0.1451

Epoch 26/256

144/144 - 1s - 9ms/step - ia: 0.9452 - loss: 0.0158 - mae: 0.0900 - rmse: 0.1253 - smape: 0.2012 - val_ia: 0.9701 - val_loss: 0.0035 - val_mae: 0.0403 - val_rmse: 0.0585 - val_smape: 0.1255

Epoch 27/256

144/144 - 1s - 9ms/step - ia: 0.9450 - loss: 0.0160 - mae: 0.0904 - rmse: 0.1260 - smape: 0.2023 - val_ia: 0.9507 - val_loss: 0.0073 - val_mae: 0.0658 - val_rmse: 0.0847 - val_smape: 0.1516

Epoch 28/256

144/144 - 1s - 6ms/step - ia: 0.9456 - loss: 0.0158 - mae: 0.0895 - rmse: 0.1251 - smape: 0.2000 - val_ia: 0.9605 - val_loss: 0.0050 - val_mae: 0.0532 - val_rmse: 0.0700 - val_smape: 0.1457

Epoch 29/256

144/144 - 1s - 5ms/step - ia: 0.9455 - loss: 0.0158 - mae: 0.0897 - rmse: 0.1254 - smape: 0.1995 - val_ia: 0.9698 - val_loss: 0.0034 - val_mae: 0.0406 - val_rmse: 0.0581 - val_smape: 0.1286

Epoch 30/256

144/144 - 1s - 4ms/step - ia: 0.9457 - loss: 0.0156 - mae: 0.0893 - rmse: 0.1246 - smape: 0.1987 - val_ia: 0.9604 - val_loss: 0.0050 - val_mae: 0.0526 - val_rmse: 0.0691 - val_smape: 0.1482

Epoch 31/256

144/144 - 1s - 4ms/step - ia: 0.9457 - loss: 0.0157 - mae: 0.0892 - rmse: 0.1247 - smape: 0.1978 - val_ia: 0.9685 - val_loss: 0.0036 - val_mae: 0.0428 - val_rmse: 0.0596 - val_smape: 0.1383

Epoch 32/256

144/144 - 1s - 5ms/step - ia: 0.9457 - loss: 0.0157 - mae: 0.0892 - rmse: 0.1249 - smape: 0.1981 - val_ia: 0.9633 - val_loss: 0.0043 - val_mae: 0.0487 - val_rmse: 0.0646 - val_smape: 0.1525

Epoch 33/256

144/144 - 1s - 4ms/step - ia: 0.9459 - loss: 0.0156 - mae: 0.0889 - rmse: 0.1243 - smape: 0.1957 - val_ia: 0.9685 - val_loss: 0.0037 - val_mae: 0.0429 - val_rmse: 0.0604 - val_smape: 0.1323

Epoch 34/256

144/144 - 1s - 7ms/step - ia: 0.9462 - loss: 0.0154 - mae: 0.0884 - rmse: 0.1236 - smape: 0.1954 - val_ia: 0.9648 - val_loss: 0.0041 - val_mae: 0.0469 - val_rmse: 0.0634 - val_smape: 0.1425

Epoch 35/256

144/144 - 1s - 6ms/step - ia: 0.9464 - loss: 0.0154 - mae: 0.0882 - rmse: 0.1235 - smape: 0.1939 - val_ia: 0.9611 - val_loss: 0.0049 - val_mae: 0.0525 - val_rmse: 0.0690 - val_smape: 0.1447

Epoch 36/256

144/144 - 2s - 12ms/step - ia: 0.9460 - loss: 0.0155 - mae: 0.0888 - rmse: 0.1237 - smape: 0.1953 - val_ia: 0.9650 - val_loss: 0.0041 - val_mae: 0.0471 - val_rmse: 0.0634 - val_smape: 0.1326

Epoch 37/256

144/144 - 2s - 11ms/step - ia: 0.9460 - loss: 0.0156 - mae: 0.0888 - rmse: 0.1244 - smape: 0.1947 - val_ia: 0.9701 - val_loss: 0.0033 - val_mae: 0.0402 - val_rmse: 0.0573 - val_smape: 0.1297

Epoch 38/256

144/144 - 1s - 10ms/step - ia: 0.9467 - loss: 0.0151 - mae: 0.0875 - rmse: 0.1224 - smape: 0.1952 - val_ia: 0.9584 - val_loss: 0.0051 - val_mae: 0.0546 - val_rmse: 0.0707 - val_smape: 0.1815

Epoch 39/256

144/144 - 2s - 11ms/step - ia: 0.9462 - loss: 0.0155 - mae: 0.0884 - rmse: 0.1240 - smape: 0.1944 - val_ia: 0.9661 - val_loss: 0.0038 - val_mae: 0.0452 - val_rmse: 0.0616 - val_smape: 0.1436

Epoch 40/256

144/144 - 1s - 9ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0873 - rmse: 0.1224 - smape: 0.1934 - val_ia: 0.9707 - val_loss: 0.0033 - val_mae: 0.0395 - val_rmse: 0.0570 - val_smape: 0.1214

Epoch 41/256

144/144 - 1s - 10ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0872 - rmse: 0.1224 - smape: 0.1911 - val_ia: 0.9686 - val_loss: 0.0035 - val_mae: 0.0422 - val_rmse: 0.0588 - val_smape: 0.1308

Epoch 42/256

144/144 - 1s - 10ms/step - ia: 0.9468 - loss: 0.0152 - mae: 0.0875 - rmse: 0.1225 - smape: 0.1927 - val_ia: 0.9549 - val_loss: 0.0062 - val_mae: 0.0602 - val_rmse: 0.0783 - val_smape: 0.1412

Epoch 43/256

144/144 - 3s - 17ms/step - ia: 0.9464 - loss: 0.0155 - mae: 0.0881 - rmse: 0.1238 - smape: 0.1929 - val_ia: 0.9644 - val_loss: 0.0043 - val_mae: 0.0479 - val_rmse: 0.0644 - val_smape: 0.1300

Epoch 44/256

144/144 - 1s - 9ms/step - ia: 0.9472 - loss: 0.0150 - mae: 0.0868 - rmse: 0.1220 - smape: 0.1922 - val_ia: 0.9656 - val_loss: 0.0041 - val_mae: 0.0464 - val_rmse: 0.0630 - val_smape: 0.1318

Epoch 45/256

144/144 - 2s - 11ms/step - ia: 0.9468 - loss: 0.0153 - mae: 0.0874 - rmse: 0.1231 - smape: 0.1917 - val_ia: 0.9708 - val_loss: 0.0032 - val_mae: 0.0394 - val_rmse: 0.0556 - val_smape: 0.1289

Epoch 46/256

144/144 - 1s - 9ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0871 - rmse: 0.1222 - smape: 0.1909 - val_ia: 0.9661 - val_loss: 0.0037 - val_mae: 0.0452 - val_rmse: 0.0608 - val_smape: 0.1490

Epoch 47/256

144/144 - 1s - 10ms/step - ia: 0.9475 - loss: 0.0149 - mae: 0.0863 - rmse: 0.1214 - smape: 0.1905 - val_ia: 0.9613 - val_loss: 0.0047 - val_mae: 0.0520 - val_rmse: 0.0673 - val_smape: 0.1470

Epoch 48/256

144/144 - 1s - 10ms/step - ia: 0.9472 - loss: 0.0150 - mae: 0.0868 - rmse: 0.1221 - smape: 0.1884 - val_ia: 0.9646 - val_loss: 0.0042 - val_mae: 0.0477 - val_rmse: 0.0639 - val_smape: 0.1306

Epoch 49/256

144/144 - 3s - 18ms/step - ia: 0.9470 - loss: 0.0151 - mae: 0.0871 - rmse: 0.1222 - smape: 0.1900 - val_ia: 0.9682 - val_loss: 0.0035 - val_mae: 0.0425 - val_rmse: 0.0583 - val_smape: 0.1364

Epoch 50/256

144/144 - 1s - 10ms/step - ia: 0.9474 - loss: 0.0149 - mae: 0.0865 - rmse: 0.1214 - smape: 0.1888 - val_ia: 0.9657 - val_loss: 0.0038 - val_mae: 0.0463 - val_rmse: 0.0610 - val_smape: 0.1451

Epoch 51/256

144/144 - 2s - 11ms/step - ia: 0.9473 - loss: 0.0150 - mae: 0.0867 - rmse: 0.1217 - smape: 0.1899 - val_ia: 0.9666 - val_loss: 0.0038 - val_mae: 0.0452 - val_rmse: 0.0605 - val_smape: 0.1331

Epoch 52/256

144/144 - 1s - 9ms/step - ia: 0.9476 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1214 - smape: 0.1888 - val_ia: 0.9668 - val_loss: 0.0038 - val_mae: 0.0449 - val_rmse: 0.0612 - val_smape: 0.1232

Epoch 53/256

144/144 - 2s - 11ms/step - ia: 0.9476 - loss: 0.0147 - mae: 0.0861 - rmse: 0.1208 - smape: 0.1893 - val_ia: 0.9697 - val_loss: 0.0033 - val_mae: 0.0408 - val_rmse: 0.0565 - val_smape: 0.1261

Epoch 54/256

144/144 - 1s - 9ms/step - ia: 0.9476 - loss: 0.0147 - mae: 0.0862 - rmse: 0.1208 - smape: 0.1881 - val_ia: 0.9715 - val_loss: 0.0031 - val_mae: 0.0385 - val_rmse: 0.0550 - val_smape: 0.1260

Epoch 55/256

144/144 - 1s - 10ms/step - ia: 0.9478 - loss: 0.0147 - mae: 0.0858 - rmse: 0.1209 - smape: 0.1871 - val_ia: 0.9657 - val_loss: 0.0039 - val_mae: 0.0457 - val_rmse: 0.0612 - val_smape: 0.1367

Epoch 56/256

144/144 - 1s - 10ms/step - ia: 0.9473 - loss: 0.0151 - mae: 0.0868 - rmse: 0.1223 - smape: 0.1882 - val_ia: 0.9714 - val_loss: 0.0032 - val_mae: 0.0387 - val_rmse: 0.0556 - val_smape: 0.1196

Epoch 57/256

144/144 - 1s - 8ms/step - ia: 0.9477 - loss: 0.0147 - mae: 0.0861 - rmse: 0.1208 - smape: 0.1895 - val_ia: 0.9570 - val_loss: 0.0058 - val_mae: 0.0580 - val_rmse: 0.0752 - val_smape: 0.1390

Epoch 58/256

144/144 - 1s - 6ms/step - ia: 0.9477 - loss: 0.0147 - mae: 0.0860 - rmse: 0.1207 - smape: 0.1885 - val_ia: 0.9686 - val_loss: 0.0034 - val_mae: 0.0419 - val_rmse: 0.0574 - val_smape: 0.1344

Epoch 59/256

144/144 - 1s - 10ms/step - ia: 0.9480 - loss: 0.0148 - mae: 0.0854 - rmse: 0.1211 - smape: 0.1865 - val_ia: 0.9544 - val_loss: 0.0062 - val_mae: 0.0613 - val_rmse: 0.0769 - val_smape: 0.1636

Epoch 60/256

144/144 - 1s - 6ms/step - ia: 0.9473 - loss: 0.0150 - mae: 0.0866 - rmse: 0.1219 - smape: 0.1890 - val_ia: 0.9686 - val_loss: 0.0034 - val_mae: 0.0420 - val_rmse: 0.0579 - val_smape: 0.1364

Epoch 61/256

144/144 - 2s - 15ms/step - ia: 0.9470 - loss: 0.0152 - mae: 0.0872 - rmse: 0.1226 - smape: 0.1908 - val_ia: 0.9642 - val_loss: 0.0043 - val_mae: 0.0483 - val_rmse: 0.0645 - val_smape: 0.1298

Epoch 62/256

144/144 - 1s - 10ms/step - ia: 0.9483 - loss: 0.0144 - mae: 0.0851 - rmse: 0.1194 - smape: 0.1859 - val_ia: 0.9698 - val_loss: 0.0032 - val_mae: 0.0409 - val_rmse: 0.0562 - val_smape: 0.1307

Epoch 63/256

144/144 - 3s - 19ms/step - ia: 0.9480 - loss: 0.0146 - mae: 0.0855 - rmse: 0.1205 - smape: 0.1864 - val_ia: 0.9614 - val_loss: 0.0046 - val_mae: 0.0518 - val_rmse: 0.0669 - val_smape: 0.1468

Epoch 64/256

144/144 - 1s - 9ms/step - ia: 0.9484 - loss: 0.0145 - mae: 0.0850 - rmse: 0.1200 - smape: 0.1848 - val_ia: 0.9660 - val_loss: 0.0039 - val_mae: 0.0457 - val_rmse: 0.0615 - val_smape: 0.1359

Epoch 65/256

144/144 - 1s - 10ms/step - ia: 0.9485 - loss: 0.0145 - mae: 0.0847 - rmse: 0.1197 - smape: 0.1843 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0571 - val_smape: 0.1311

Epoch 66/256

144/144 - 2s - 11ms/step - ia: 0.9484 - loss: 0.0145 - mae: 0.0849 - rmse: 0.1198 - smape: 0.1853 - val_ia: 0.9694 - val_loss: 0.0033 - val_mae: 0.0413 - val_rmse: 0.0567 - val_smape: 0.1264

Epoch 67/256

144/144 - 1s - 8ms/step - ia: 0.9476 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1210 - smape: 0.1866 - val_ia: 0.9614 - val_loss: 0.0046 - val_mae: 0.0515 - val_rmse: 0.0665 - val_smape: 0.1478

Epoch 68/256

144/144 - 2s - 11ms/step - ia: 0.9482 - loss: 0.0145 - mae: 0.0851 - rmse: 0.1198 - smape: 0.1857 - val_ia: 0.9699 - val_loss: 0.0032 - val_mae: 0.0406 - val_rmse: 0.0556 - val_smape: 0.1332

Epoch 69/256

144/144 - 1s - 9ms/step - ia: 0.9477 - loss: 0.0147 - mae: 0.0860 - rmse: 0.1209 - smape: 0.1861 - val_ia: 0.9719 - val_loss: 0.0030 - val_mae: 0.0381 - val_rmse: 0.0547 - val_smape: 0.1228

Epoch 70/256

144/144 - 2s - 12ms/step - ia: 0.9478 - loss: 0.0148 - mae: 0.0858 - rmse: 0.1212 - smape: 0.1862 - val_ia: 0.9708 - val_loss: 0.0031 - val_mae: 0.0394 - val_rmse: 0.0554 - val_smape: 0.1291

Epoch 71/256

144/144 - 1s - 9ms/step - ia: 0.9474 - loss: 0.0149 - mae: 0.0865 - rmse: 0.1215 - smape: 0.1874 - val_ia: 0.9680 - val_loss: 0.0034 - val_mae: 0.0424 - val_rmse: 0.0580 - val_smape: 0.1380

Epoch 72/256

144/144 - 2s - 11ms/step - ia: 0.9481 - loss: 0.0146 - mae: 0.0853 - rmse: 0.1203 - smape: 0.1853 - val_ia: 0.9703 - val_loss: 0.0032 - val_mae: 0.0401 - val_rmse: 0.0562 - val_smape: 0.1174

Epoch 73/256

144/144 - 1s - 10ms/step - ia: 0.9480 - loss: 0.0146 - mae: 0.0857 - rmse: 0.1206 - smape: 0.1866 - val_ia: 0.9564 - val_loss: 0.0058 - val_mae: 0.0587 - val_rmse: 0.0748 - val_smape: 0.1487

Epoch 74/256

144/144 - 3s - 18ms/step - ia: 0.9487 - loss: 0.0143 - mae: 0.0844 - rmse: 0.1190 - smape: 0.1842 - val_ia: 0.9629 - val_loss: 0.0042 - val_mae: 0.0499 - val_rmse: 0.0651 - val_smape: 0.1487

Epoch 75/256

144/144 - 1s - 10ms/step - ia: 0.9476 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1213 - smape: 0.1872 - val_ia: 0.9704 - val_loss: 0.0031 - val_mae: 0.0398 - val_rmse: 0.0554 - val_smape: 0.1324

Epoch 76/256

144/144 - 2s - 17ms/step - ia: 0.9483 - loss: 0.0145 - mae: 0.0851 - rmse: 0.1201 - smape: 0.1862 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0439 - val_rmse: 0.0594 - val_smape: 0.1437

Epoch 77/256

144/144 - 2s - 12ms/step - ia: 0.9477 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1211 - smape: 0.1864 - val_ia: 0.9640 - val_loss: 0.0040 - val_mae: 0.0484 - val_rmse: 0.0626 - val_smape: 0.1501

Epoch 78/256

144/144 - 2s - 11ms/step - ia: 0.9484 - loss: 0.0144 - mae: 0.0847 - rmse: 0.1199 - smape: 0.1837 - val_ia: 0.9599 - val_loss: 0.0050 - val_mae: 0.0540 - val_rmse: 0.0696 - val_smape: 0.1390

Epoch 79/256

144/144 - 1s - 9ms/step - ia: 0.9480 - loss: 0.0146 - mae: 0.0854 - rmse: 0.1202 - smape: 0.1850 - val_ia: 0.9657 - val_loss: 0.0039 - val_mae: 0.0462 - val_rmse: 0.0613 - val_smape: 0.1380

Epoch 80/256

144/144 - 1s - 10ms/step - ia: 0.9483 - loss: 0.0146 - mae: 0.0851 - rmse: 0.1199 - smape: 0.1840 - val_ia: 0.9713 - val_loss: 0.0030 - val_mae: 0.0388 - val_rmse: 0.0546 - val_smape: 0.1270

Epoch 81/256

144/144 - 3s - 17ms/step - ia: 0.9476 - loss: 0.0149 - mae: 0.0862 - rmse: 0.1214 - smape: 0.1874 - val_ia: 0.9696 - val_loss: 0.0032 - val_mae: 0.0412 - val_rmse: 0.0561 - val_smape: 0.1311

Epoch 82/256

144/144 - 1s - 10ms/step - ia: 0.9477 - loss: 0.0148 - mae: 0.0861 - rmse: 0.1212 - smape: 0.1862 - val_ia: 0.9647 - val_loss: 0.0041 - val_mae: 0.0479 - val_rmse: 0.0635 - val_smape: 0.1323

Epoch 83/256

144/144 - 1s - 7ms/step - ia: 0.9480 - loss: 0.0146 - mae: 0.0854 - rmse: 0.1205 - smape: 0.1852 - val_ia: 0.9699 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0558 - val_smape: 0.1295

Epoch 84/256

144/144 - 2s - 11ms/step - ia: 0.9484 - loss: 0.0145 - mae: 0.0848 - rmse: 0.1199 - smape: 0.1846 - val_ia: 0.9652 - val_loss: 0.0040 - val_mae: 0.0471 - val_rmse: 0.0624 - val_smape: 0.1304

Epoch 85/256

144/144 - 1s - 9ms/step - ia: 0.9477 - loss: 0.0148 - mae: 0.0859 - rmse: 0.1212 - smape: 0.1854 - val_ia: 0.9621 - val_loss: 0.0045 - val_mae: 0.0513 - val_rmse: 0.0668 - val_smape: 0.1472

Epoch 86/256

144/144 - 2s - 11ms/step - ia: 0.9477 - loss: 0.0149 - mae: 0.0862 - rmse: 0.1217 - smape: 0.1852 - val_ia: 0.9719 - val_loss: 0.0030 - val_mae: 0.0379 - val_rmse: 0.0539 - val_smape: 0.1175

Epoch 87/256

144/144 - 1s - 7ms/step - ia: 0.9488 - loss: 0.0144 - mae: 0.0843 - rmse: 0.1193 - smape: 0.1822 - val_ia: 0.9666 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0602 - val_smape: 0.1315

Epoch 88/256

144/144 - 1s - 9ms/step - ia: 0.9487 - loss: 0.0143 - mae: 0.0844 - rmse: 0.1192 - smape: 0.1833 - val_ia: 0.9661 - val_loss: 0.0037 - val_mae: 0.0447 - val_rmse: 0.0596 - val_smape: 0.1405

Epoch 89/256

144/144 - 1s - 8ms/step - ia: 0.9485 - loss: 0.0145 - mae: 0.0848 - rmse: 0.1197 - smape: 0.1843 - val_ia: 0.9661 - val_loss: 0.0037 - val_mae: 0.0449 - val_rmse: 0.0602 - val_smape: 0.1449

Epoch 90/256

144/144 - 2s - 11ms/step - ia: 0.9484 - loss: 0.0146 - mae: 0.0848 - rmse: 0.1203 - smape: 0.1835 - val_ia: 0.9692 - val_loss: 0.0033 - val_mae: 0.0412 - val_rmse: 0.0566 - val_smape: 0.1317

Epoch 91/256

144/144 - 1s - 10ms/step - ia: 0.9484 - loss: 0.0145 - mae: 0.0849 - rmse: 0.1197 - smape: 0.1837 - val_ia: 0.9671 - val_loss: 0.0036 - val_mae: 0.0445 - val_rmse: 0.0592 - val_smape: 0.1339

Epoch 92/256

144/144 - 3s - 19ms/step - ia: 0.9481 - loss: 0.0146 - mae: 0.0853 - rmse: 0.1201 - smape: 0.1845 - val_ia: 0.9699 - val_loss: 0.0032 - val_mae: 0.0405 - val_rmse: 0.0561 - val_smape: 0.1251

Epoch 93/256

144/144 - 2s - 11ms/step - ia: 0.9481 - loss: 0.0146 - mae: 0.0853 - rmse: 0.1203 - smape: 0.1845 - val_ia: 0.9703 - val_loss: 0.0032 - val_mae: 0.0400 - val_rmse: 0.0557 - val_smape: 0.1231

Epoch 94/256

144/144 - 1s - 10ms/step - ia: 0.9486 - loss: 0.0144 - mae: 0.0845 - rmse: 0.1194 - smape: 0.1836 - val_ia: 0.9702 - val_loss: 0.0032 - val_mae: 0.0399 - val_rmse: 0.0555 - val_smape: 0.1273

Epoch 95/256

144/144 - 2s - 11ms/step - ia: 0.9491 - loss: 0.0139 - mae: 0.0837 - rmse: 0.1173 - smape: 0.1832 - val_ia: 0.9678 - val_loss: 0.0035 - val_mae: 0.0429 - val_rmse: 0.0589 - val_smape: 0.1384

Epoch 96/256

144/144 - 1s - 9ms/step - ia: 0.9490 - loss: 0.0141 - mae: 0.0840 - rmse: 0.1181 - smape: 0.1827 - val_ia: 0.9690 - val_loss: 0.0033 - val_mae: 0.0416 - val_rmse: 0.0565 - val_smape: 0.1308

Epoch 97/256

144/144 - 2s - 11ms/step - ia: 0.9482 - loss: 0.0146 - mae: 0.0852 - rmse: 0.1203 - smape: 0.1833 - val_ia: 0.9648 - val_loss: 0.0041 - val_mae: 0.0477 - val_rmse: 0.0630 - val_smape: 0.1320

Epoch 98/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 8s - 59ms/step - ia: 0.8301 - loss: 0.2207 - mae: 0.2934 - rmse: 0.3877 - smape: 0.5371 - val_ia: 0.9359 - val_loss: 0.0128 - val_mae: 0.0852 - val_rmse: 0.1120 - val_smape: 0.2402

Epoch 2/256

144/144 - 2s - 15ms/step - ia: 0.9121 - loss: 0.0380 - mae: 0.1440 - rmse: 0.1943 - smape: 0.3246 - val_ia: 0.9501 - val_loss: 0.0084 - val_mae: 0.0661 - val_rmse: 0.0913 - val_smape: 0.1997

Epoch 3/256

144/144 - 2s - 12ms/step - ia: 0.9221 - loss: 0.0304 - mae: 0.1274 - rmse: 0.1738 - smape: 0.2863 - val_ia: 0.9422 - val_loss: 0.0101 - val_mae: 0.0762 - val_rmse: 0.0990 - val_smape: 0.2088

Epoch 4/256

144/144 - 1s - 10ms/step - ia: 0.9263 - loss: 0.0275 - mae: 0.1204 - rmse: 0.1656 - smape: 0.2659 - val_ia: 0.9447 - val_loss: 0.0092 - val_mae: 0.0736 - val_rmse: 0.0945 - val_smape: 0.1868

Epoch 5/256

144/144 - 2s - 11ms/step - ia: 0.9280 - loss: 0.0263 - mae: 0.1178 - rmse: 0.1616 - smape: 0.2565 - val_ia: 0.9584 - val_loss: 0.0059 - val_mae: 0.0560 - val_rmse: 0.0760 - val_smape: 0.1740

Epoch 6/256

144/144 - 3s - 18ms/step - ia: 0.9309 - loss: 0.0248 - mae: 0.1133 - rmse: 0.1569 - smape: 0.2451 - val_ia: 0.9609 - val_loss: 0.0054 - val_mae: 0.0523 - val_rmse: 0.0732 - val_smape: 0.1679

Epoch 7/256

144/144 - 3s - 18ms/step - ia: 0.9317 - loss: 0.0241 - mae: 0.1120 - rmse: 0.1546 - smape: 0.2433 - val_ia: 0.9428 - val_loss: 0.0090 - val_mae: 0.0757 - val_rmse: 0.0929 - val_smape: 0.2196

Epoch 8/256

144/144 - 2s - 11ms/step - ia: 0.9327 - loss: 0.0237 - mae: 0.1102 - rmse: 0.1534 - smape: 0.2355 - val_ia: 0.9601 - val_loss: 0.0052 - val_mae: 0.0535 - val_rmse: 0.0714 - val_smape: 0.1605

Epoch 9/256

144/144 - 2s - 17ms/step - ia: 0.9332 - loss: 0.0234 - mae: 0.1094 - rmse: 0.1525 - smape: 0.2333 - val_ia: 0.9619 - val_loss: 0.0049 - val_mae: 0.0503 - val_rmse: 0.0697 - val_smape: 0.1638

Epoch 10/256

144/144 - 2s - 13ms/step - ia: 0.9342 - loss: 0.0230 - mae: 0.1079 - rmse: 0.1510 - smape: 0.2303 - val_ia: 0.9377 - val_loss: 0.0109 - val_mae: 0.0820 - val_rmse: 0.1035 - val_smape: 0.1773

Epoch 11/256

144/144 - 3s - 18ms/step - ia: 0.9337 - loss: 0.0231 - mae: 0.1084 - rmse: 0.1523 - smape: 0.2278 - val_ia: 0.9554 - val_loss: 0.0062 - val_mae: 0.0598 - val_rmse: 0.0775 - val_smape: 0.1561

Epoch 12/256

144/144 - 2s - 17ms/step - ia: 0.9349 - loss: 0.0223 - mae: 0.1067 - rmse: 0.1489 - smape: 0.2251 - val_ia: 0.9669 - val_loss: 0.0041 - val_mae: 0.0447 - val_rmse: 0.0634 - val_smape: 0.1425

Epoch 13/256

144/144 - 1s - 10ms/step - ia: 0.9354 - loss: 0.0221 - mae: 0.1060 - rmse: 0.1481 - smape: 0.2237 - val_ia: 0.9587 - val_loss: 0.0053 - val_mae: 0.0558 - val_rmse: 0.0726 - val_smape: 0.1711

Epoch 14/256

144/144 - 1s - 9ms/step - ia: 0.9358 - loss: 0.0218 - mae: 0.1052 - rmse: 0.1471 - smape: 0.2202 - val_ia: 0.9617 - val_loss: 0.0047 - val_mae: 0.0514 - val_rmse: 0.0678 - val_smape: 0.1553

Epoch 15/256

144/144 - 1s - 9ms/step - ia: 0.9356 - loss: 0.0220 - mae: 0.1054 - rmse: 0.1479 - smape: 0.2214 - val_ia: 0.9674 - val_loss: 0.0039 - val_mae: 0.0437 - val_rmse: 0.0618 - val_smape: 0.1407

Epoch 16/256

144/144 - 3s - 19ms/step - ia: 0.9357 - loss: 0.0221 - mae: 0.1054 - rmse: 0.1479 - smape: 0.2187 - val_ia: 0.9537 - val_loss: 0.0065 - val_mae: 0.0633 - val_rmse: 0.0805 - val_smape: 0.1722

Epoch 17/256

144/144 - 2s - 17ms/step - ia: 0.9349 - loss: 0.0226 - mae: 0.1066 - rmse: 0.1495 - smape: 0.2198 - val_ia: 0.9565 - val_loss: 0.0058 - val_mae: 0.0594 - val_rmse: 0.0762 - val_smape: 0.1610

Epoch 18/256

144/144 - 2s - 11ms/step - ia: 0.9355 - loss: 0.0222 - mae: 0.1057 - rmse: 0.1485 - smape: 0.2187 - val_ia: 0.9630 - val_loss: 0.0045 - val_mae: 0.0497 - val_rmse: 0.0663 - val_smape: 0.1553

Epoch 19/256

144/144 - 1s - 10ms/step - ia: 0.9345 - loss: 0.0227 - mae: 0.1070 - rmse: 0.1504 - smape: 0.2214 - val_ia: 0.9661 - val_loss: 0.0041 - val_mae: 0.0452 - val_rmse: 0.0630 - val_smape: 0.1356

Epoch 20/256

144/144 - 2s - 11ms/step - ia: 0.9353 - loss: 0.0225 - mae: 0.1062 - rmse: 0.1494 - smape: 0.2184 - val_ia: 0.9511 - val_loss: 0.0072 - val_mae: 0.0656 - val_rmse: 0.0839 - val_smape: 0.1538

Epoch 21/256

144/144 - 1s - 7ms/step - ia: 0.9352 - loss: 0.0225 - mae: 0.1062 - rmse: 0.1493 - smape: 0.2178 - val_ia: 0.9531 - val_loss: 0.0069 - val_mae: 0.0630 - val_rmse: 0.0821 - val_smape: 0.1499

Epoch 22/256

144/144 - 2s - 11ms/step - ia: 0.9362 - loss: 0.0220 - mae: 0.1045 - rmse: 0.1479 - smape: 0.2151 - val_ia: 0.9532 - val_loss: 0.0065 - val_mae: 0.0624 - val_rmse: 0.0793 - val_smape: 0.1666

Epoch 23/256

144/144 - 2s - 11ms/step - ia: 0.9339 - loss: 0.0234 - mae: 0.1083 - rmse: 0.1523 - smape: 0.2212 - val_ia: 0.9558 - val_loss: 0.0057 - val_mae: 0.0579 - val_rmse: 0.0740 - val_smape: 0.1714

Epoch 24/256

144/144 - 1s - 10ms/step - ia: 0.9365 - loss: 0.0218 - mae: 0.1043 - rmse: 0.1471 - smape: 0.2130 - val_ia: 0.9676 - val_loss: 0.0037 - val_mae: 0.0429 - val_rmse: 0.0605 - val_smape: 0.1394

Epoch 25/256

144/144 - 1s - 9ms/step - ia: 0.9364 - loss: 0.0218 - mae: 0.1043 - rmse: 0.1470 - smape: 0.2135 - val_ia: 0.9682 - val_loss: 0.0036 - val_mae: 0.0430 - val_rmse: 0.0591 - val_smape: 0.1338

Epoch 26/256

144/144 - 1s - 10ms/step - ia: 0.9366 - loss: 0.0218 - mae: 0.1041 - rmse: 0.1469 - smape: 0.2159 - val_ia: 0.9425 - val_loss: 0.0090 - val_mae: 0.0758 - val_rmse: 0.0923 - val_smape: 0.1969

Epoch 27/256

144/144 - 1s - 10ms/step - ia: 0.9358 - loss: 0.0220 - mae: 0.1051 - rmse: 0.1479 - smape: 0.2162 - val_ia: 0.9634 - val_loss: 0.0042 - val_mae: 0.0482 - val_rmse: 0.0640 - val_smape: 0.1551

Epoch 28/256

144/144 - 1s - 9ms/step - ia: 0.9372 - loss: 0.0216 - mae: 0.1030 - rmse: 0.1463 - smape: 0.2106 - val_ia: 0.9642 - val_loss: 0.0042 - val_mae: 0.0480 - val_rmse: 0.0649 - val_smape: 0.1434

Epoch 29/256

144/144 - 1s - 7ms/step - ia: 0.9354 - loss: 0.0225 - mae: 0.1060 - rmse: 0.1492 - smape: 0.2156 - val_ia: 0.9692 - val_loss: 0.0035 - val_mae: 0.0415 - val_rmse: 0.0581 - val_smape: 0.1318

Epoch 30/256

144/144 - 2s - 10ms/step - ia: 0.9365 - loss: 0.0216 - mae: 0.1041 - rmse: 0.1464 - smape: 0.2132 - val_ia: 0.9663 - val_loss: 0.0039 - val_mae: 0.0459 - val_rmse: 0.0624 - val_smape: 0.1319

Epoch 31/256

144/144 - 1s - 10ms/step - ia: 0.9373 - loss: 0.0212 - mae: 0.1030 - rmse: 0.1448 - smape: 0.2113 - val_ia: 0.9629 - val_loss: 0.0044 - val_mae: 0.0493 - val_rmse: 0.0657 - val_smape: 0.1470

Epoch 32/256

144/144 - 1s - 10ms/step - ia: 0.9358 - loss: 0.0223 - mae: 0.1052 - rmse: 0.1486 - smape: 0.2144 - val_ia: 0.9621 - val_loss: 0.0048 - val_mae: 0.0511 - val_rmse: 0.0681 - val_smape: 0.1316

Epoch 33/256

144/144 - 1s - 9ms/step - ia: 0.9349 - loss: 0.0229 - mae: 0.1067 - rmse: 0.1504 - smape: 0.2169 - val_ia: 0.9656 - val_loss: 0.0038 - val_mae: 0.0464 - val_rmse: 0.0616 - val_smape: 0.1512

Epoch 34/256

144/144 - 2s - 10ms/step - ia: 0.9350 - loss: 0.0227 - mae: 0.1064 - rmse: 0.1500 - smape: 0.2156 - val_ia: 0.9713 - val_loss: 0.0032 - val_mae: 0.0386 - val_rmse: 0.0556 - val_smape: 0.1169

Epoch 35/256

144/144 - 1s - 8ms/step - ia: 0.9369 - loss: 0.0215 - mae: 0.1035 - rmse: 0.1458 - smape: 0.2106 - val_ia: 0.9614 - val_loss: 0.0046 - val_mae: 0.0512 - val_rmse: 0.0667 - val_smape: 0.1523

Epoch 36/256

144/144 - 2s - 12ms/step - ia: 0.9376 - loss: 0.0212 - mae: 0.1024 - rmse: 0.1450 - smape: 0.2081 - val_ia: 0.9473 - val_loss: 0.0083 - val_mae: 0.0708 - val_rmse: 0.0898 - val_smape: 0.1604

Epoch 37/256

144/144 - 1s - 8ms/step - ia: 0.9362 - loss: 0.0219 - mae: 0.1046 - rmse: 0.1475 - smape: 0.2121 - val_ia: 0.9728 - val_loss: 0.0029 - val_mae: 0.0368 - val_rmse: 0.0533 - val_smape: 0.1163

Epoch 38/256

144/144 - 2s - 11ms/step - ia: 0.9361 - loss: 0.0221 - mae: 0.1047 - rmse: 0.1480 - smape: 0.2133 - val_ia: 0.9489 - val_loss: 0.0077 - val_mae: 0.0687 - val_rmse: 0.0864 - val_smape: 0.1591

Epoch 39/256

144/144 - 1s - 9ms/step - ia: 0.9357 - loss: 0.0220 - mae: 0.1051 - rmse: 0.1478 - smape: 0.2136 - val_ia: 0.9588 - val_loss: 0.0051 - val_mae: 0.0548 - val_rmse: 0.0717 - val_smape: 0.1616

Epoch 40/256

144/144 - 2s - 11ms/step - ia: 0.9363 - loss: 0.0219 - mae: 0.1044 - rmse: 0.1473 - smape: 0.2118 - val_ia: 0.9389 - val_loss: 0.0104 - val_mae: 0.0815 - val_rmse: 0.0997 - val_smape: 0.1817

Epoch 41/256

144/144 - 1s - 10ms/step - ia: 0.9362 - loss: 0.0220 - mae: 0.1044 - rmse: 0.1479 - smape: 0.2124 - val_ia: 0.9641 - val_loss: 0.0041 - val_mae: 0.0475 - val_rmse: 0.0642 - val_smape: 0.1561

Epoch 42/256

144/144 - 2s - 17ms/step - ia: 0.9372 - loss: 0.0212 - mae: 0.1029 - rmse: 0.1452 - smape: 0.2094 - val_ia: 0.9584 - val_loss: 0.0055 - val_mae: 0.0564 - val_rmse: 0.0735 - val_smape: 0.1443

Epoch 43/256

144/144 - 1s - 7ms/step - ia: 0.9367 - loss: 0.0216 - mae: 0.1037 - rmse: 0.1462 - smape: 0.2106 - val_ia: 0.9622 - val_loss: 0.0045 - val_mae: 0.0513 - val_rmse: 0.0673 - val_smape: 0.1523

Epoch 44/256

144/144 - 2s - 11ms/step - ia: 0.9375 - loss: 0.0213 - mae: 0.1025 - rmse: 0.1452 - smape: 0.2095 - val_ia: 0.9572 - val_loss: 0.0056 - val_mae: 0.0573 - val_rmse: 0.0734 - val_smape: 0.1516

Epoch 45/256

144/144 - 1s - 10ms/step - ia: 0.9368 - loss: 0.0217 - mae: 0.1036 - rmse: 0.1467 - smape: 0.2098 - val_ia: 0.8931 - val_loss: 0.0285 - val_mae: 0.1383 - val_rmse: 0.1656 - val_smape: 0.2731

Epoch 46/256

144/144 - 1s - 10ms/step - ia: 0.9364 - loss: 0.0219 - mae: 0.1042 - rmse: 0.1474 - smape: 0.2115 - val_ia: 0.9577 - val_loss: 0.0055 - val_mae: 0.0568 - val_rmse: 0.0737 - val_smape: 0.1339

Epoch 47/256

144/144 - 1s - 10ms/step - ia: 0.9347 - loss: 0.0230 - mae: 0.1070 - rmse: 0.1509 - smape: 0.2141 - val_ia: 0.9651 - val_loss: 0.0041 - val_mae: 0.0472 - val_rmse: 0.0631 - val_smape: 0.1338

Epoch 48/256

144/144 - 1s - 7ms/step - ia: 0.9368 - loss: 0.0218 - mae: 0.1037 - rmse: 0.1468 - smape: 0.2088 - val_ia: 0.9647 - val_loss: 0.0039 - val_mae: 0.0474 - val_rmse: 0.0619 - val_smape: 0.1474

Epoch 49/256

144/144 - 1s - 9ms/step - ia: 0.9378 - loss: 0.0209 - mae: 0.1019 - rmse: 0.1437 - smape: 0.2067 - val_ia: 0.9715 - val_loss: 0.0030 - val_mae: 0.0383 - val_rmse: 0.0542 - val_smape: 0.1213

Epoch 50/256

144/144 - 1s - 10ms/step - ia: 0.9367 - loss: 0.0217 - mae: 0.1038 - rmse: 0.1465 - smape: 0.2105 - val_ia: 0.9693 - val_loss: 0.0033 - val_mae: 0.0409 - val_rmse: 0.0573 - val_smape: 0.1282

Epoch 51/256

144/144 - 2s - 13ms/step - ia: 0.9363 - loss: 0.0221 - mae: 0.1044 - rmse: 0.1479 - smape: 0.2102 - val_ia: 0.9656 - val_loss: 0.0040 - val_mae: 0.0463 - val_rmse: 0.0623 - val_smape: 0.1257

Epoch 52/256

144/144 - 2s - 17ms/step - ia: 0.9371 - loss: 0.0217 - mae: 0.1033 - rmse: 0.1467 - smape: 0.2088 - val_ia: 0.9683 - val_loss: 0.0035 - val_mae: 0.0428 - val_rmse: 0.0581 - val_smape: 0.1312

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 40s 247ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

100%|██████████| 50/50 [3:28:58<00:00, 250.78s/trial, best loss: 0.00185367915076116]
{'activation': 3, 'batch': 5, 'dropout': 0.5, 'epochs': 5, 'layers': 1.0, 'learning_rate': 0.005194930724034002, 'units': 3}

In [23]:
print(best)

{'activation': 3, 'batch': 5, 'dropout': 0.5, 'epochs': 5, 'layers': 1.0, 'learning_rate': 0.005194930724034002, 'units': 3}