Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 1
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43788, 12, 6)
Dimensiones de Y: (43788, 1)

In [16]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [17]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (43788, 72)

Se dividen nuevamente los conjuntos de datos

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30651, 72)
Las dimensiones de testX son:  (8801, 72)
Las dimensiones de valX son:  (4336, 72)

In [19]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30651, 1)
Las dimensiones de testY son:  (8801, 1)
Las dimensiones de valY son:  (4336, 1)

Se crean métricas para medir desempeño

In [20]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [21]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [22]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [23]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 9s - 9ms/step - ia: 0.3315 - loss: 1.5169 - mae: 0.8856 - rmse: 1.1891 - smape: 1.3978 - val_ia: 0.2779 - val_loss: 0.6564 - val_mae: 0.6074 - val_rmse: 0.6891 - val_smape: 1.3486

Epoch 2/128

958/958 - 2s - 3ms/step - ia: 0.4725 - loss: 0.7613 - mae: 0.6317 - rmse: 0.8491 - smape: 1.2168 - val_ia: 0.4203 - val_loss: 0.2952 - val_mae: 0.4005 - val_rmse: 0.4707 - val_smape: 0.8611

Epoch 3/128

958/958 - 2s - 3ms/step - ia: 0.5821 - loss: 0.5244 - mae: 0.5139 - rmse: 0.7032 - smape: 1.0360 - val_ia: 0.5003 - val_loss: 0.1954 - val_mae: 0.3219 - val_rmse: 0.3862 - val_smape: 0.7006

Epoch 4/128

958/958 - 3s - 3ms/step - ia: 0.6293 - loss: 0.4354 - mae: 0.4613 - rmse: 0.6395 - smape: 0.9411 - val_ia: 0.5244 - val_loss: 0.1769 - val_mae: 0.3043 - val_rmse: 0.3654 - val_smape: 0.6538

Epoch 5/128

958/958 - 3s - 3ms/step - ia: 0.6633 - loss: 0.3721 - mae: 0.4251 - rmse: 0.5916 - smape: 0.8743 - val_ia: 0.5489 - val_loss: 0.1629 - val_mae: 0.2879 - val_rmse: 0.3467 - val_smape: 0.6122

Epoch 6/128

958/958 - 2s - 2ms/step - ia: 0.6843 - loss: 0.3368 - mae: 0.4000 - rmse: 0.5624 - smape: 0.8229 - val_ia: 0.5856 - val_loss: 0.1290 - val_mae: 0.2548 - val_rmse: 0.3124 - val_smape: 0.5552

Epoch 7/128

958/958 - 3s - 3ms/step - ia: 0.6942 - loss: 0.3252 - mae: 0.3895 - rmse: 0.5505 - smape: 0.7966 - val_ia: 0.6446 - val_loss: 0.0976 - val_mae: 0.2099 - val_rmse: 0.2716 - val_smape: 0.4900

Epoch 8/128

958/958 - 3s - 3ms/step - ia: 0.7043 - loss: 0.3117 - mae: 0.3783 - rmse: 0.5378 - smape: 0.7701 - val_ia: 0.6059 - val_loss: 0.1198 - val_mae: 0.2401 - val_rmse: 0.2976 - val_smape: 0.5353

Epoch 9/128

958/958 - 3s - 3ms/step - ia: 0.7116 - loss: 0.3011 - mae: 0.3694 - rmse: 0.5270 - smape: 0.7510 - val_ia: 0.5963 - val_loss: 0.1264 - val_mae: 0.2496 - val_rmse: 0.3048 - val_smape: 0.5368

Epoch 10/128

958/958 - 6s - 7ms/step - ia: 0.7203 - loss: 0.2843 - mae: 0.3611 - rmse: 0.5134 - smape: 0.7331 - val_ia: 0.6320 - val_loss: 0.1008 - val_mae: 0.2203 - val_rmse: 0.2757 - val_smape: 0.4929

Epoch 11/128

958/958 - 4s - 4ms/step - ia: 0.7236 - loss: 0.2803 - mae: 0.3566 - rmse: 0.5106 - smape: 0.7202 - val_ia: 0.6254 - val_loss: 0.1106 - val_mae: 0.2299 - val_rmse: 0.2843 - val_smape: 0.4989

Epoch 12/128

958/958 - 4s - 4ms/step - ia: 0.7245 - loss: 0.2809 - mae: 0.3554 - rmse: 0.5096 - smape: 0.7145 - val_ia: 0.6100 - val_loss: 0.1128 - val_mae: 0.2370 - val_rmse: 0.2905 - val_smape: 0.5137

Epoch 13/128

958/958 - 2s - 3ms/step - ia: 0.7284 - loss: 0.2741 - mae: 0.3508 - rmse: 0.5024 - smape: 0.7036 - val_ia: 0.6261 - val_loss: 0.1026 - val_mae: 0.2225 - val_rmse: 0.2769 - val_smape: 0.4916

Epoch 14/128

958/958 - 3s - 3ms/step - ia: 0.7302 - loss: 0.2729 - mae: 0.3493 - rmse: 0.5018 - smape: 0.7027 - val_ia: 0.6354 - val_loss: 0.1014 - val_mae: 0.2182 - val_rmse: 0.2724 - val_smape: 0.4799

Epoch 15/128

958/958 - 6s - 6ms/step - ia: 0.7281 - loss: 0.2713 - mae: 0.3488 - rmse: 0.5009 - smape: 0.7019 - val_ia: 0.5747 - val_loss: 0.1469 - val_mae: 0.2720 - val_rmse: 0.3253 - val_smape: 0.5751

Epoch 16/128

958/958 - 4s - 4ms/step - ia: 0.7330 - loss: 0.2630 - mae: 0.3455 - rmse: 0.4932 - smape: 0.6931 - val_ia: 0.6056 - val_loss: 0.1159 - val_mae: 0.2422 - val_rmse: 0.2939 - val_smape: 0.5171

Epoch 17/128

958/958 - 3s - 3ms/step - ia: 0.7358 - loss: 0.2635 - mae: 0.3424 - rmse: 0.4934 - smape: 0.6835 - val_ia: 0.6222 - val_loss: 0.1125 - val_mae: 0.2317 - val_rmse: 0.2848 - val_smape: 0.4969

Epoch 18/128

958/958 - 2s - 2ms/step - ia: 0.7354 - loss: 0.2598 - mae: 0.3426 - rmse: 0.4908 - smape: 0.6891 - val_ia: 0.6628 - val_loss: 0.0839 - val_mae: 0.1957 - val_rmse: 0.2507 - val_smape: 0.4444

Epoch 19/128

958/958 - 2s - 3ms/step - ia: 0.7374 - loss: 0.2649 - mae: 0.3403 - rmse: 0.4934 - smape: 0.6777 - val_ia: 0.6408 - val_loss: 0.0983 - val_mae: 0.2138 - val_rmse: 0.2678 - val_smape: 0.4725

Epoch 20/128

958/958 - 3s - 3ms/step - ia: 0.7400 - loss: 0.2543 - mae: 0.3375 - rmse: 0.4846 - smape: 0.6747 - val_ia: 0.6031 - val_loss: 0.1187 - val_mae: 0.2433 - val_rmse: 0.2952 - val_smape: 0.5125

Epoch 21/128

958/958 - 4s - 4ms/step - ia: 0.7372 - loss: 0.2639 - mae: 0.3401 - rmse: 0.4925 - smape: 0.6784 - val_ia: 0.6305 - val_loss: 0.1006 - val_mae: 0.2198 - val_rmse: 0.2734 - val_smape: 0.4902

Epoch 22/128

958/958 - 5s - 5ms/step - ia: 0.7391 - loss: 0.2584 - mae: 0.3384 - rmse: 0.4876 - smape: 0.6758 - val_ia: 0.5969 - val_loss: 0.1307 - val_mae: 0.2511 - val_rmse: 0.3032 - val_smape: 0.5253

Epoch 23/128

958/958 - 6s - 6ms/step - ia: 0.7399 - loss: 0.2623 - mae: 0.3379 - rmse: 0.4895 - smape: 0.6730 - val_ia: 0.6121 - val_loss: 0.1117 - val_mae: 0.2351 - val_rmse: 0.2874 - val_smape: 0.5229

Epoch 24/128

958/958 - 5s - 5ms/step - ia: 0.7401 - loss: 0.2576 - mae: 0.3377 - rmse: 0.4864 - smape: 0.6723 - val_ia: 0.6260 - val_loss: 0.1013 - val_mae: 0.2226 - val_rmse: 0.2743 - val_smape: 0.4853

Epoch 25/128

958/958 - 6s - 6ms/step - ia: 0.7423 - loss: 0.2628 - mae: 0.3358 - rmse: 0.4899 - smape: 0.6646 - val_ia: 0.6757 - val_loss: 0.0802 - val_mae: 0.1879 - val_rmse: 0.2439 - val_smape: 0.4375

Epoch 26/128

958/958 - 3s - 3ms/step - ia: 0.7419 - loss: 0.2552 - mae: 0.3345 - rmse: 0.4839 - smape: 0.6634 - val_ia: 0.6156 - val_loss: 0.1082 - val_mae: 0.2316 - val_rmse: 0.2834 - val_smape: 0.4972

Epoch 27/128

958/958 - 2s - 2ms/step - ia: 0.7412 - loss: 0.2539 - mae: 0.3348 - rmse: 0.4843 - smape: 0.6694 - val_ia: 0.6389 - val_loss: 0.1007 - val_mae: 0.2165 - val_rmse: 0.2686 - val_smape: 0.4659

Epoch 28/128

958/958 - 2s - 2ms/step - ia: 0.7436 - loss: 0.2484 - mae: 0.3338 - rmse: 0.4799 - smape: 0.6628 - val_ia: 0.6132 - val_loss: 0.1137 - val_mae: 0.2361 - val_rmse: 0.2879 - val_smape: 0.4993

Epoch 29/128

958/958 - 2s - 3ms/step - ia: 0.7432 - loss: 0.2519 - mae: 0.3333 - rmse: 0.4820 - smape: 0.6600 - val_ia: 0.6386 - val_loss: 0.0960 - val_mae: 0.2127 - val_rmse: 0.2651 - val_smape: 0.4661

Epoch 30/128

958/958 - 3s - 3ms/step - ia: 0.7425 - loss: 0.2515 - mae: 0.3340 - rmse: 0.4811 - smape: 0.6645 - val_ia: 0.6192 - val_loss: 0.1082 - val_mae: 0.2307 - val_rmse: 0.2815 - val_smape: 0.4897

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.7397 - loss: 0.2617 - mae: 0.3371 - rmse: 0.4890 - smape: 0.6648 - val_ia: 0.5717 - val_loss: 0.1461 - val_mae: 0.2745 - val_rmse: 0.3250 - val_smape: 0.5624

Epoch 32/128

958/958 - 4s - 5ms/step - ia: 0.7413 - loss: 0.2515 - mae: 0.3352 - rmse: 0.4843 - smape: 0.6662 - val_ia: 0.6536 - val_loss: 0.0956 - val_mae: 0.2076 - val_rmse: 0.2618 - val_smape: 0.4712

Epoch 33/128

958/958 - 1s - 2ms/step - ia: 0.7446 - loss: 0.2535 - mae: 0.3315 - rmse: 0.4811 - smape: 0.6587 - val_ia: 0.6375 - val_loss: 0.0990 - val_mae: 0.2164 - val_rmse: 0.2684 - val_smape: 0.4717

Epoch 34/128

958/958 - 2s - 2ms/step - ia: 0.7385 - loss: 0.2639 - mae: 0.3370 - rmse: 0.4889 - smape: 0.6680 - val_ia: 0.6308 - val_loss: 0.0989 - val_mae: 0.2191 - val_rmse: 0.2700 - val_smape: 0.4778

Epoch 35/128

958/958 - 4s - 4ms/step - ia: 0.7465 - loss: 0.2459 - mae: 0.3307 - rmse: 0.4774 - smape: 0.6594 - val_ia: 0.6339 - val_loss: 0.0979 - val_mae: 0.2171 - val_rmse: 0.2689 - val_smape: 0.4771

Epoch 36/128

958/958 - 4s - 4ms/step - ia: 0.7462 - loss: 0.2443 - mae: 0.3307 - rmse: 0.4755 - smape: 0.6568 - val_ia: 0.6620 - val_loss: 0.0878 - val_mae: 0.2011 - val_rmse: 0.2535 - val_smape: 0.4515

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.7443 - loss: 0.2471 - mae: 0.3324 - rmse: 0.4786 - smape: 0.6605 - val_ia: 0.6642 - val_loss: 0.0857 - val_mae: 0.1971 - val_rmse: 0.2504 - val_smape: 0.4448

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.7466 - loss: 0.2451 - mae: 0.3293 - rmse: 0.4752 - smape: 0.6510 - val_ia: 0.6678 - val_loss: 0.0845 - val_mae: 0.1961 - val_rmse: 0.2486 - val_smape: 0.4408

Epoch 39/128

958/958 - 3s - 3ms/step - ia: 0.7442 - loss: 0.2486 - mae: 0.3312 - rmse: 0.4793 - smape: 0.6570 - val_ia: 0.6486 - val_loss: 0.0903 - val_mae: 0.2060 - val_rmse: 0.2576 - val_smape: 0.4528

Epoch 40/128

958/958 - 3s - 3ms/step - ia: 0.7457 - loss: 0.2496 - mae: 0.3302 - rmse: 0.4765 - smape: 0.6571 - val_ia: 0.6109 - val_loss: 0.1099 - val_mae: 0.2342 - val_rmse: 0.2847 - val_smape: 0.4996

Epoch 40: early stopping

Restoring model weights from the end of the best epoch: 25.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 15s 116ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/16

  2%|▏         | 1/50 [02:24<1:58:13, 144.76s/trial, best loss: 0.06459772663990161]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 9s - 71ms/step - ia: 0.7700 - loss: 0.2170 - mae: 0.3027 - rmse: 0.4412 - smape: 0.6677 - val_ia: 0.8184 - val_loss: 0.0931 - val_mae: 0.2018 - val_rmse: 0.2922 - val_smape: 0.4989

Epoch 2/16

120/120 - 1s - 8ms/step - ia: 0.8644 - loss: 0.0936 - mae: 0.1975 - rmse: 0.3014 - smape: 0.4750 - val_ia: 0.8419 - val_loss: 0.0761 - val_mae: 0.1785 - val_rmse: 0.2619 - val_smape: 0.4477

Epoch 3/16

120/120 - 1s - 12ms/step - ia: 0.8753 - loss: 0.0808 - mae: 0.1821 - rmse: 0.2814 - smape: 0.4477 - val_ia: 0.8463 - val_loss: 0.0757 - val_mae: 0.1778 - val_rmse: 0.2596 - val_smape: 0.4387

Epoch 4/16

120/120 - 1s - 9ms/step - ia: 0.8817 - loss: 0.0747 - mae: 0.1731 - rmse: 0.2694 - smape: 0.4315 - val_ia: 0.8471 - val_loss: 0.0721 - val_mae: 0.1765 - val_rmse: 0.2552 - val_smape: 0.4306

Epoch 5/16

120/120 - 0s - 4ms/step - ia: 0.8866 - loss: 0.0698 - mae: 0.1662 - rmse: 0.2611 - smape: 0.4172 - val_ia: 0.8612 - val_loss: 0.0631 - val_mae: 0.1561 - val_rmse: 0.2381 - val_smape: 0.4009

Epoch 6/16

120/120 - 1s - 5ms/step - ia: 0.8905 - loss: 0.0666 - mae: 0.1608 - rmse: 0.2544 - smape: 0.4071 - val_ia: 0.8622 - val_loss: 0.0621 - val_mae: 0.1554 - val_rmse: 0.2368 - val_smape: 0.4008

Epoch 7/16

120/120 - 1s - 6ms/step - ia: 0.8916 - loss: 0.0649 - mae: 0.1593 - rmse: 0.2515 - smape: 0.4043 - val_ia: 0.8651 - val_loss: 0.0613 - val_mae: 0.1527 - val_rmse: 0.2343 - val_smape: 0.3977

Epoch 8/16

120/120 - 1s - 5ms/step - ia: 0.8940 - loss: 0.0628 - mae: 0.1559 - rmse: 0.2468 - smape: 0.4008 - val_ia: 0.8637 - val_loss: 0.0627 - val_mae: 0.1553 - val_rmse: 0.2362 - val_smape: 0.3959

Epoch 9/16

120/120 - 1s - 5ms/step - ia: 0.8958 - loss: 0.0607 - mae: 0.1533 - rmse: 0.2431 - smape: 0.3950 - val_ia: 0.8567 - val_loss: 0.0673 - val_mae: 0.1643 - val_rmse: 0.2442 - val_smape: 0.4113

Epoch 10/16

120/120 - 0s - 3ms/step - ia: 0.8976 - loss: 0.0594 - mae: 0.1507 - rmse: 0.2408 - smape: 0.3892 - val_ia: 0.8671 - val_loss: 0.0596 - val_mae: 0.1497 - val_rmse: 0.2316 - val_smape: 0.3887

Epoch 11/16

120/120 - 0s - 4ms/step - ia: 0.8996 - loss: 0.0573 - mae: 0.1476 - rmse: 0.2360 - smape: 0.3832 - val_ia: 0.8690 - val_loss: 0.0595 - val_mae: 0.1495 - val_rmse: 0.2308 - val_smape: 0.3898

Epoch 12/16

120/120 - 1s - 5ms/step - ia: 0.9006 - loss: 0.0564 - mae: 0.1465 - rmse: 0.2344 - smape: 0.3805 - val_ia: 0.8670 - val_loss: 0.0607 - val_mae: 0.1518 - val_rmse: 0.2324 - val_smape: 0.3904

Epoch 13/16

120/120 - 0s - 4ms/step - ia: 0.9010 - loss: 0.0556 - mae: 0.1457 - rmse: 0.2324 - smape: 0.3795 - val_ia: 0.8688 - val_loss: 0.0588 - val_mae: 0.1489 - val_rmse: 0.2291 - val_smape: 0.3893

Epoch 14/16

120/120 - 1s - 6ms/step - ia: 0.9019 - loss: 0.0545 - mae: 0.1444 - rmse: 0.2306 - smape: 0.3768 - val_ia: 0.8656 - val_loss: 0.0596 - val_mae: 0.1512 - val_rmse: 0.2312 - val_smape: 0.3973

Epoch 15/16

120/120 - 1s - 8ms/step - ia: 0.9031 - loss: 0.0535 - mae: 0.1429 - rmse: 0.2281 - smape: 0.3739 - val_ia: 0.8692 - val_loss: 0.0586 - val_mae: 0.1482 - val_rmse: 0.2282 - val_smape: 0.3902

Epoch 16/16

120/120 - 2s - 13ms/step - ia: 0.9037 - loss: 0.0525 - mae: 0.1417 - rmse: 0.2261 - smape: 0.3734 - val_ia: 0.8696 - val_loss: 0.0585 - val_mae: 0.1478 - val_rmse: 0.2287 - val_smape: 0.3864

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:09 513ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

  4%|▍         | 2/50 [02:47<58:15, 72.83s/trial, best loss: 0.04486145343913409]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 10s - 22ms/step - ia: 0.3607 - loss: 1.2602 - mae: 0.7790 - rmse: 1.1090 - smape: 1.3012 - val_ia: 0.3012 - val_loss: 1.0274 - val_mae: 0.6764 - val_rmse: 0.8262 - val_smape: 1.2155

Epoch 2/8

479/479 - 1s - 3ms/step - ia: 0.3592 - loss: 1.2424 - mae: 0.7723 - rmse: 1.1008 - smape: 1.3034 - val_ia: 0.3001 - val_loss: 1.0140 - val_mae: 0.6725 - val_rmse: 0.8204 - val_smape: 1.2246

Epoch 3/8

479/479 - 1s - 3ms/step - ia: 0.3602 - loss: 1.2090 - mae: 0.7625 - rmse: 1.0841 - smape: 1.3071 - val_ia: 0.2989 - val_loss: 1.0020 - val_mae: 0.6692 - val_rmse: 0.8153 - val_smape: 1.2339

Epoch 4/8

479/479 - 1s - 3ms/step - ia: 0.3587 - loss: 1.1881 - mae: 0.7536 - rmse: 1.0753 - smape: 1.3130 - val_ia: 0.2975 - val_loss: 0.9911 - val_mae: 0.6665 - val_rmse: 0.8108 - val_smape: 1.2435

Epoch 5/8

479/479 - 1s - 3ms/step - ia: 0.3569 - loss: 1.1660 - mae: 0.7466 - rmse: 1.0651 - smape: 1.3184 - val_ia: 0.2961 - val_loss: 0.9812 - val_mae: 0.6642 - val_rmse: 0.8069 - val_smape: 1.2529

Epoch 6/8

479/479 - 2s - 4ms/step - ia: 0.3567 - loss: 1.1479 - mae: 0.7390 - rmse: 1.0568 - smape: 1.3196 - val_ia: 0.2947 - val_loss: 0.9719 - val_mae: 0.6622 - val_rmse: 0.8032 - val_smape: 1.2626

Epoch 7/8

479/479 - 2s - 4ms/step - ia: 0.3556 - loss: 1.1250 - mae: 0.7319 - rmse: 1.0476 - smape: 1.3261 - val_ia: 0.2934 - val_loss: 0.9633 - val_mae: 0.6606 - val_rmse: 0.8000 - val_smape: 1.2725

Epoch 8/8

479/479 - 2s - 4ms/step - ia: 0.3537 - loss: 1.1108 - mae: 0.7273 - rmse: 1.0405 - smape: 1.3325 - val_ia: 0.2922 - val_loss: 0.9555 - val_mae: 0.6592 - val_rmse: 0.7972 - val_smape: 1.2828

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 22s 170ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

  6%|▌         | 3/50 [03:10<39:25, 50.33s/trial, best loss: 0.04486145343913409]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

240/240 - 10s - 42ms/step - ia: 0.3256 - loss: 1.7477 - mae: 1.0161 - rmse: 1.3162 - smape: 1.3843 - val_ia: 0.3956 - val_loss: 0.8273 - val_mae: 0.6696 - val_rmse: 0.8209 - val_smape: 1.2902

Epoch 2/32

240/240 - 1s - 3ms/step - ia: 0.3773 - loss: 1.4611 - mae: 0.9315 - rmse: 1.2048 - smape: 1.3212 - val_ia: 0.4868 - val_loss: 0.5822 - val_mae: 0.5497 - val_rmse: 0.6844 - val_smape: 1.0997

Epoch 3/32

240/240 - 1s - 3ms/step - ia: 0.4215 - loss: 1.2919 - mae: 0.8771 - rmse: 1.1335 - smape: 1.2582 - val_ia: 0.5576 - val_loss: 0.4459 - val_mae: 0.4722 - val_rmse: 0.5989 - val_smape: 0.9431

Epoch 4/32

240/240 - 1s - 3ms/step - ia: 0.4540 - loss: 1.1808 - mae: 0.8372 - rmse: 1.0820 - smape: 1.2124 - val_ia: 0.6039 - val_loss: 0.3737 - val_mae: 0.4269 - val_rmse: 0.5512 - val_smape: 0.8436

Epoch 5/32

240/240 - 1s - 3ms/step - ia: 0.4799 - loss: 1.0932 - mae: 0.8057 - rmse: 1.0421 - smape: 1.1756 - val_ia: 0.6343 - val_loss: 0.3318 - val_mae: 0.3997 - val_rmse: 0.5230 - val_smape: 0.7844

Epoch 6/32

240/240 - 1s - 6ms/step - ia: 0.4963 - loss: 1.0455 - mae: 0.7890 - rmse: 1.0182 - smape: 1.1535 - val_ia: 0.6538 - val_loss: 0.3065 - val_mae: 0.3830 - val_rmse: 0.5058 - val_smape: 0.7462

Epoch 7/32

240/240 - 1s - 3ms/step - ia: 0.5097 - loss: 0.9956 - mae: 0.7692 - rmse: 0.9940 - smape: 1.1324 - val_ia: 0.6664 - val_loss: 0.2890 - val_mae: 0.3717 - val_rmse: 0.4935 - val_smape: 0.7218

Epoch 8/32

240/240 - 1s - 6ms/step - ia: 0.5224 - loss: 0.9503 - mae: 0.7515 - rmse: 0.9711 - smape: 1.1115 - val_ia: 0.6753 - val_loss: 0.2760 - val_mae: 0.3634 - val_rmse: 0.4839 - val_smape: 0.7022

Epoch 9/32

240/240 - 1s - 4ms/step - ia: 0.5299 - loss: 0.9317 - mae: 0.7434 - rmse: 0.9616 - smape: 1.1001 - val_ia: 0.6824 - val_loss: 0.2650 - val_mae: 0.3557 - val_rmse: 0.4747 - val_smape: 0.6867

Epoch 10/32

240/240 - 2s - 7ms/step - ia: 0.5367 - loss: 0.8898 - mae: 0.7263 - rmse: 0.9395 - smape: 1.0912 - val_ia: 0.6879 - val_loss: 0.2570 - val_mae: 0.3506 - val_rmse: 0.4684 - val_smape: 0.6749

Epoch 11/32

240/240 - 3s - 11ms/step - ia: 0.5433 - loss: 0.8728 - mae: 0.7202 - rmse: 0.9301 - smape: 1.0812 - val_ia: 0.6924 - val_loss: 0.2500 - val_mae: 0.3463 - val_rmse: 0.4628 - val_smape: 0.6655

Epoch 12/32

240/240 - 1s - 5ms/step - ia: 0.5487 - loss: 0.8520 - mae: 0.7086 - rmse: 0.9191 - smape: 1.0689 - val_ia: 0.6971 - val_loss: 0.2432 - val_mae: 0.3411 - val_rmse: 0.4566 - val_smape: 0.6571

Epoch 13/32

240/240 - 1s - 4ms/step - ia: 0.5529 - loss: 0.8253 - mae: 0.6982 - rmse: 0.9047 - smape: 1.0681 - val_ia: 0.7014 - val_loss: 0.2369 - val_mae: 0.3360 - val_rmse: 0.4506 - val_smape: 0.6472

Epoch 14/32

240/240 - 2s - 7ms/step - ia: 0.5597 - loss: 0.8004 - mae: 0.6878 - rmse: 0.8916 - smape: 1.0578 - val_ia: 0.7048 - val_loss: 0.2320 - val_mae: 0.3323 - val_rmse: 0.4461 - val_smape: 0.6401

Epoch 15/32

240/240 - 1s - 6ms/step - ia: 0.5623 - loss: 0.7917 - mae: 0.6816 - rmse: 0.8857 - smape: 1.0520 - val_ia: 0.7082 - val_loss: 0.2271 - val_mae: 0.3282 - val_rmse: 0.4413 - val_smape: 0.6332

Epoch 16/32

240/240 - 2s - 9ms/step - ia: 0.5700 - loss: 0.7646 - mae: 0.6696 - rmse: 0.8713 - smape: 1.0384 - val_ia: 0.7107 - val_loss: 0.2228 - val_mae: 0.3246 - val_rmse: 0.4372 - val_smape: 0.6276

Epoch 17/32

240/240 - 1s - 3ms/step - ia: 0.5695 - loss: 0.7595 - mae: 0.6679 - rmse: 0.8682 - smape: 1.0401 - val_ia: 0.7146 - val_loss: 0.2189 - val_mae: 0.3212 - val_rmse: 0.4331 - val_smape: 0.6231

Epoch 18/32

240/240 - 1s - 3ms/step - ia: 0.5747 - loss: 0.7456 - mae: 0.6587 - rmse: 0.8595 - smape: 1.0284 - val_ia: 0.7168 - val_loss: 0.2160 - val_mae: 0.3192 - val_rmse: 0.4307 - val_smape: 0.6197

Epoch 19/32

240/240 - 1s - 3ms/step - ia: 0.5764 - loss: 0.7323 - mae: 0.6565 - rmse: 0.8527 - smape: 1.0313 - val_ia: 0.7198 - val_loss: 0.2123 - val_mae: 0.3154 - val_rmse: 0.4264 - val_smape: 0.6147

Epoch 20/32

240/240 - 1s - 3ms/step - ia: 0.5798 - loss: 0.7179 - mae: 0.6481 - rmse: 0.8434 - smape: 1.0256 - val_ia: 0.7219 - val_loss: 0.2090 - val_mae: 0.3127 - val_rmse: 0.4233 - val_smape: 0.6093

Epoch 21/32

240/240 - 2s - 7ms/step - ia: 0.5834 - loss: 0.7120 - mae: 0.6430 - rmse: 0.8399 - smape: 1.0146 - val_ia: 0.7238 - val_loss: 0.2061 - val_mae: 0.3103 - val_rmse: 0.4205 - val_smape: 0.6042

Epoch 22/32

240/240 - 1s - 6ms/step - ia: 0.5866 - loss: 0.6971 - mae: 0.6359 - rmse: 0.8317 - smape: 1.0132 - val_ia: 0.7252 - val_loss: 0.2042 - val_mae: 0.3089 - val_rmse: 0.4187 - val_smape: 0.6015

Epoch 23/32

240/240 - 1s - 6ms/step - ia: 0.5890 - loss: 0.6893 - mae: 0.6340 - rmse: 0.8270 - smape: 1.0085 - val_ia: 0.7282 - val_loss: 0.2011 - val_mae: 0.3054 - val_rmse: 0.4148 - val_smape: 0.5975

Epoch 24/32

240/240 - 1s - 6ms/step - ia: 0.5921 - loss: 0.6725 - mae: 0.6262 - rmse: 0.8170 - smape: 1.0028 - val_ia: 0.7310 - val_loss: 0.1982 - val_mae: 0.3024 - val_rmse: 0.4114 - val_smape: 0.5939

Epoch 25/32

240/240 - 1s - 5ms/step - ia: 0.5974 - loss: 0.6541 - mae: 0.6160 - rmse: 0.8043 - smape: 0.9952 - val_ia: 0.7311 - val_loss: 0.1969 - val_mae: 0.3020 - val_rmse: 0.4105 - val_smape: 0.5907

Epoch 26/32

240/240 - 1s - 6ms/step - ia: 0.5995 - loss: 0.6494 - mae: 0.6124 - rmse: 0.8021 - smape: 0.9916 - val_ia: 0.7333 - val_loss: 0.1943 - val_mae: 0.2997 - val_rmse: 0.4077 - val_smape: 0.5876

Epoch 27/32

240/240 - 1s - 5ms/step - ia: 0.6018 - loss: 0.6446 - mae: 0.6093 - rmse: 0.7983 - smape: 0.9899 - val_ia: 0.7341 - val_loss: 0.1934 - val_mae: 0.2996 - val_rmse: 0.4073 - val_smape: 0.5866

Epoch 28/32

240/240 - 2s - 7ms/step - ia: 0.6045 - loss: 0.6333 - mae: 0.6055 - rmse: 0.7925 - smape: 0.9840 - val_ia: 0.7361 - val_loss: 0.1908 - val_mae: 0.2966 - val_rmse: 0.4041 - val_smape: 0.5823

Epoch 29/32

240/240 - 1s - 4ms/step - ia: 0.6063 - loss: 0.6213 - mae: 0.5987 - rmse: 0.7841 - smape: 0.9800 - val_ia: 0.7363 - val_loss: 0.1904 - val_mae: 0.2972 - val_rmse: 0.4043 - val_smape: 0.5813

Epoch 30/32

240/240 - 1s - 4ms/step - ia: 0.6076 - loss: 0.6197 - mae: 0.5986 - rmse: 0.7837 - smape: 0.9782 - val_ia: 0.7369 - val_loss: 0.1893 - val_mae: 0.2964 - val_rmse: 0.4032 - val_smape: 0.5792

Epoch 31/32

240/240 - 1s - 6ms/step - ia: 0.6108 - loss: 0.6092 - mae: 0.5925 - rmse: 0.7764 - smape: 0.9705 - val_ia: 0.7373 - val_loss: 0.1885 - val_mae: 0.2962 - val_rmse: 0.4028 - val_smape: 0.5773

Epoch 32/32

240/240 - 1s - 5ms/step - ia: 0.6134 - loss: 0.6034 - mae: 0.5879 - rmse: 0.7726 - smape: 0.9654 - val_ia: 0.7382 - val_loss: 0.1872 - val_mae: 0.2953 - val_rmse: 0.4017 - val_smape: 0.5752

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 24s 180ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

  8%|▊         | 4/50 [04:00<38:32, 50.26s/trial, best loss: 0.04486145343913409]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

3832/3832 - 16s - 4ms/step - ia: 0.3526 - loss: 1.1952 - mae: 0.7507 - rmse: 1.0039 - smape: 1.2646 - val_ia: 0.2045 - val_loss: 0.9996 - val_mae: 0.6626 - val_rmse: 0.7035 - val_smape: 1.1447

Epoch 2/64

3832/3832 - 12s - 3ms/step - ia: 0.3405 - loss: 1.1177 - mae: 0.7358 - rmse: 0.9734 - smape: 1.3079 - val_ia: 0.2016 - val_loss: 0.9450 - val_mae: 0.6596 - val_rmse: 0.6997 - val_smape: 1.2381

Epoch 3/64

3832/3832 - 18s - 5ms/step - ia: 0.3384 - loss: 1.0593 - mae: 0.7230 - rmse: 0.9458 - smape: 1.3342 - val_ia: 0.2004 - val_loss: 0.9057 - val_mae: 0.6587 - val_rmse: 0.6982 - val_smape: 1.3407

Epoch 4/64

3832/3832 - 9s - 2ms/step - ia: 0.3392 - loss: 1.0161 - mae: 0.7153 - rmse: 0.9307 - smape: 1.3459 - val_ia: 0.1985 - val_loss: 0.8747 - val_mae: 0.6574 - val_rmse: 0.6964 - val_smape: 1.4232

Epoch 5/64

3832/3832 - 10s - 3ms/step - ia: 0.3443 - loss: 0.9787 - mae: 0.7051 - rmse: 0.9122 - smape: 1.3418 - val_ia: 0.1973 - val_loss: 0.8481 - val_mae: 0.6544 - val_rmse: 0.6930 - val_smape: 1.4526

Epoch 6/64

3832/3832 - 8s - 2ms/step - ia: 0.3495 - loss: 0.9518 - mae: 0.6981 - rmse: 0.9015 - smape: 1.3356 - val_ia: 0.1973 - val_loss: 0.8228 - val_mae: 0.6494 - val_rmse: 0.6878 - val_smape: 1.4502

Epoch 7/64

3832/3832 - 9s - 2ms/step - ia: 0.3542 - loss: 0.9262 - mae: 0.6928 - rmse: 0.8905 - smape: 1.3383 - val_ia: 0.1983 - val_loss: 0.7987 - val_mae: 0.6421 - val_rmse: 0.6804 - val_smape: 1.4309

Epoch 8/64

3832/3832 - 8s - 2ms/step - ia: 0.3698 - loss: 0.8975 - mae: 0.6794 - rmse: 0.8735 - smape: 1.3103 - val_ia: 0.1995 - val_loss: 0.7752 - val_mae: 0.6339 - val_rmse: 0.6721 - val_smape: 1.4044

Epoch 9/64

3832/3832 - 15s - 4ms/step - ia: 0.3727 - loss: 0.8789 - mae: 0.6746 - rmse: 0.8671 - smape: 1.3015 - val_ia: 0.2012 - val_loss: 0.7516 - val_mae: 0.6240 - val_rmse: 0.6623 - val_smape: 1.3707

Epoch 10/64

3832/3832 - 8s - 2ms/step - ia: 0.3870 - loss: 0.8454 - mae: 0.6610 - rmse: 0.8492 - smape: 1.2800 - val_ia: 0.2032 - val_loss: 0.7281 - val_mae: 0.6132 - val_rmse: 0.6516 - val_smape: 1.3352

Epoch 11/64

3832/3832 - 14s - 4ms/step - ia: 0.4003 - loss: 0.8214 - mae: 0.6493 - rmse: 0.8345 - smape: 1.2569 - val_ia: 0.2050 - val_loss: 0.7048 - val_mae: 0.6016 - val_rmse: 0.6402 - val_smape: 1.2965

Epoch 12/64

3832/3832 - 8s - 2ms/step - ia: 0.4099 - loss: 0.8062 - mae: 0.6420 - rmse: 0.8279 - smape: 1.2399 - val_ia: 0.2067 - val_loss: 0.6819 - val_mae: 0.5899 - val_rmse: 0.6286 - val_smape: 1.2579

Epoch 13/64

3832/3832 - 13s - 3ms/step - ia: 0.4238 - loss: 0.7828 - mae: 0.6316 - rmse: 0.8160 - smape: 1.2162 - val_ia: 0.2086 - val_loss: 0.6593 - val_mae: 0.5776 - val_rmse: 0.6165 - val_smape: 1.2202

Epoch 14/64

3832/3832 - 7s - 2ms/step - ia: 0.4345 - loss: 0.7628 - mae: 0.6213 - rmse: 0.8036 - smape: 1.1966 - val_ia: 0.2107 - val_loss: 0.6373 - val_mae: 0.5654 - val_rmse: 0.6044 - val_smape: 1.1829

Epoch 15/64

3832/3832 - 9s - 2ms/step - ia: 0.4483 - loss: 0.7391 - mae: 0.6096 - rmse: 0.7889 - smape: 1.1748 - val_ia: 0.2128 - val_loss: 0.6161 - val_mae: 0.5532 - val_rmse: 0.5923 - val_smape: 1.1464

Epoch 16/64

3832/3832 - 10s - 3ms/step - ia: 0.4592 - loss: 0.7217 - mae: 0.6000 - rmse: 0.7794 - smape: 1.1531 - val_ia: 0.2153 - val_loss: 0.5954 - val_mae: 0.5408 - val_rmse: 0.5800 - val_smape: 1.1106

Epoch 17/64

3832/3832 - 19s - 5ms/step - ia: 0.4683 - loss: 0.7011 - mae: 0.5915 - rmse: 0.7691 - smape: 1.1367 - val_ia: 0.2177 - val_loss: 0.5756 - val_mae: 0.5287 - val_rmse: 0.5681 - val_smape: 1.0766

Epoch 18/64

3832/3832 - 11s - 3ms/step - ia: 0.4832 - loss: 0.6835 - mae: 0.5807 - rmse: 0.7571 - smape: 1.1120 - val_ia: 0.2203 - val_loss: 0.5566 - val_mae: 0.5169 - val_rmse: 0.5564 - val_smape: 1.0449

Epoch 19/64

3832/3832 - 10s - 3ms/step - ia: 0.4917 - loss: 0.6681 - mae: 0.5734 - rmse: 0.7485 - smape: 1.0919 - val_ia: 0.2232 - val_loss: 0.5386 - val_mae: 0.5044 - val_rmse: 0.5440 - val_smape: 1.0122

Epoch 20/64

3832/3832 - 21s - 6ms/step - ia: 0.5061 - loss: 0.6475 - mae: 0.5617 - rmse: 0.7366 - smape: 1.0677 - val_ia: 0.2261 - val_loss: 0.5217 - val_mae: 0.4937 - val_rmse: 0.5336 - val_smape: 0.9857

Epoch 21/64

3832/3832 - 7s - 2ms/step - ia: 0.5148 - loss: 0.6382 - mae: 0.5549 - rmse: 0.7289 - smape: 1.0515 - val_ia: 0.2292 - val_loss: 0.5057 - val_mae: 0.4828 - val_rmse: 0.5228 - val_smape: 0.9586

Epoch 22/64

3832/3832 - 6s - 2ms/step - ia: 0.5247 - loss: 0.6213 - mae: 0.5473 - rmse: 0.7204 - smape: 1.0390 - val_ia: 0.2326 - val_loss: 0.4909 - val_mae: 0.4725 - val_rmse: 0.5128 - val_smape: 0.9340

Epoch 23/64

3832/3832 - 16s - 4ms/step - ia: 0.5365 - loss: 0.6163 - mae: 0.5398 - rmse: 0.7124 - smape: 1.0184 - val_ia: 0.2363 - val_loss: 0.4773 - val_mae: 0.4627 - val_rmse: 0.5033 - val_smape: 0.9110

Epoch 24/64

3832/3832 - 24s - 6ms/step - ia: 0.5461 - loss: 0.5931 - mae: 0.5319 - rmse: 0.7032 - smape: 0.9986 - val_ia: 0.2398 - val_loss: 0.4644 - val_mae: 0.4535 - val_rmse: 0.4943 - val_smape: 0.8897

Epoch 25/64

3832/3832 - 20s - 5ms/step - ia: 0.5513 - loss: 0.5837 - mae: 0.5270 - rmse: 0.6965 - smape: 0.9881 - val_ia: 0.2432 - val_loss: 0.4522 - val_mae: 0.4441 - val_rmse: 0.4852 - val_smape: 0.8684

Epoch 26/64

3832/3832 - 19s - 5ms/step - ia: 0.5597 - loss: 0.5743 - mae: 0.5225 - rmse: 0.6909 - smape: 0.9757 - val_ia: 0.2459 - val_loss: 0.4410 - val_mae: 0.4361 - val_rmse: 0.4773 - val_smape: 0.8506

Epoch 27/64

3832/3832 - 20s - 5ms/step - ia: 0.5658 - loss: 0.5605 - mae: 0.5168 - rmse: 0.6825 - smape: 0.9656 - val_ia: 0.2481 - val_loss: 0.4309 - val_mae: 0.4287 - val_rmse: 0.4702 - val_smape: 0.8348

Epoch 28/64

3832/3832 - 16s - 4ms/step - ia: 0.5734 - loss: 0.5574 - mae: 0.5111 - rmse: 0.6789 - smape: 0.9520 - val_ia: 0.2506 - val_loss: 0.4212 - val_mae: 0.4216 - val_rmse: 0.4632 - val_smape: 0.8196

Epoch 29/64

3832/3832 - 20s - 5ms/step - ia: 0.5791 - loss: 0.5421 - mae: 0.5060 - rmse: 0.6699 - smape: 0.9423 - val_ia: 0.2534 - val_loss: 0.4122 - val_mae: 0.4142 - val_rmse: 0.4561 - val_smape: 0.8043

Epoch 30/64

3832/3832 - 18s - 5ms/step - ia: 0.5835 - loss: 0.5392 - mae: 0.5021 - rmse: 0.6674 - smape: 0.9331 - val_ia: 0.2564 - val_loss: 0.4038 - val_mae: 0.4076 - val_rmse: 0.4497 - val_smape: 0.7908

Epoch 31/64

3832/3832 - 7s - 2ms/step - ia: 0.5917 - loss: 0.5246 - mae: 0.4946 - rmse: 0.6581 - smape: 0.9138 - val_ia: 0.2593 - val_loss: 0.3959 - val_mae: 0.4019 - val_rmse: 0.4442 - val_smape: 0.7795

Epoch 32/64

3832/3832 - 9s - 2ms/step - ia: 0.5914 - loss: 0.5275 - mae: 0.4963 - rmse: 0.6588 - smape: 0.9159 - val_ia: 0.2623 - val_loss: 0.3884 - val_mae: 0.3962 - val_rmse: 0.4387 - val_smape: 0.7686

Epoch 33/64

3832/3832 - 22s - 6ms/step - ia: 0.5972 - loss: 0.5114 - mae: 0.4903 - rmse: 0.6501 - smape: 0.9096 - val_ia: 0.2658 - val_loss: 0.3813 - val_mae: 0.3904 - val_rmse: 0.4330 - val_smape: 0.7574

Epoch 34/64

3832/3832 - 18s - 5ms/step - ia: 0.6029 - loss: 0.5137 - mae: 0.4861 - rmse: 0.6501 - smape: 0.8943 - val_ia: 0.2687 - val_loss: 0.3746 - val_mae: 0.3856 - val_rmse: 0.4284 - val_smape: 0.7484

Epoch 35/64

3832/3832 - 23s - 6ms/step - ia: 0.6088 - loss: 0.4942 - mae: 0.4815 - rmse: 0.6383 - smape: 0.8898 - val_ia: 0.2720 - val_loss: 0.3682 - val_mae: 0.3803 - val_rmse: 0.4233 - val_smape: 0.7380

Epoch 36/64

3832/3832 - 20s - 5ms/step - ia: 0.6098 - loss: 0.4991 - mae: 0.4808 - rmse: 0.6387 - smape: 0.8849 - val_ia: 0.2752 - val_loss: 0.3620 - val_mae: 0.3754 - val_rmse: 0.4186 - val_smape: 0.7288

Epoch 37/64

3832/3832 - 21s - 5ms/step - ia: 0.6135 - loss: 0.4919 - mae: 0.4782 - rmse: 0.6358 - smape: 0.8804 - val_ia: 0.2781 - val_loss: 0.3563 - val_mae: 0.3711 - val_rmse: 0.4143 - val_smape: 0.7202

Epoch 38/64

3832/3832 - 8s - 2ms/step - ia: 0.6177 - loss: 0.4869 - mae: 0.4729 - rmse: 0.6319 - smape: 0.8701 - val_ia: 0.2814 - val_loss: 0.3505 - val_mae: 0.3664 - val_rmse: 0.4098 - val_smape: 0.7108

Epoch 39/64

3832/3832 - 5s - 1ms/step - ia: 0.6212 - loss: 0.4764 - mae: 0.4700 - rmse: 0.6259 - smape: 0.8618 - val_ia: 0.2842 - val_loss: 0.3452 - val_mae: 0.3625 - val_rmse: 0.4060 - val_smape: 0.7034

Epoch 40/64

3832/3832 - 14s - 4ms/step - ia: 0.6228 - loss: 0.4754 - mae: 0.4680 - rmse: 0.6256 - smape: 0.8642 - val_ia: 0.2866 - val_loss: 0.3400 - val_mae: 0.3589 - val_rmse: 0.4025 - val_smape: 0.6962

Epoch 41/64

3832/3832 - 19s - 5ms/step - ia: 0.6281 - loss: 0.4716 - mae: 0.4639 - rmse: 0.6202 - smape: 0.8513 - val_ia: 0.2892 - val_loss: 0.3350 - val_mae: 0.3550 - val_rmse: 0.3987 - val_smape: 0.6886

Epoch 42/64

3832/3832 - 6s - 2ms/step - ia: 0.6307 - loss: 0.4601 - mae: 0.4596 - rmse: 0.6125 - smape: 0.8504 - val_ia: 0.2920 - val_loss: 0.3302 - val_mae: 0.3513 - val_rmse: 0.3951 - val_smape: 0.6817

Epoch 43/64

3832/3832 - 5s - 1ms/step - ia: 0.6343 - loss: 0.4577 - mae: 0.4581 - rmse: 0.6106 - smape: 0.8440 - val_ia: 0.2946 - val_loss: 0.3255 - val_mae: 0.3477 - val_rmse: 0.3916 - val_smape: 0.6751

Epoch 44/64

3832/3832 - 22s - 6ms/step - ia: 0.6350 - loss: 0.4533 - mae: 0.4561 - rmse: 0.6069 - smape: 0.8448 - val_ia: 0.2972 - val_loss: 0.3210 - val_mae: 0.3443 - val_rmse: 0.3882 - val_smape: 0.6688

Epoch 45/64

3832/3832 - 38s - 10ms/step - ia: 0.6393 - loss: 0.4451 - mae: 0.4514 - rmse: 0.6020 - smape: 0.8349 - val_ia: 0.2999 - val_loss: 0.3167 - val_mae: 0.3410 - val_rmse: 0.3850 - val_smape: 0.6632

Epoch 46/64

3832/3832 - 14s - 4ms/step - ia: 0.6418 - loss: 0.4386 - mae: 0.4480 - rmse: 0.5974 - smape: 0.8258 - val_ia: 0.3025 - val_loss: 0.3125 - val_mae: 0.3375 - val_rmse: 0.3816 - val_smape: 0.6566

Epoch 47/64

3832/3832 - 6s - 2ms/step - ia: 0.6429 - loss: 0.4381 - mae: 0.4484 - rmse: 0.5970 - smape: 0.8280 - val_ia: 0.3050 - val_loss: 0.3084 - val_mae: 0.3345 - val_rmse: 0.3786 - val_smape: 0.6508

Epoch 48/64

3832/3832 - 20s - 5ms/step - ia: 0.6458 - loss: 0.4341 - mae: 0.4438 - rmse: 0.5930 - smape: 0.8252 - val_ia: 0.3075 - val_loss: 0.3043 - val_mae: 0.3316 - val_rmse: 0.3758 - val_smape: 0.6456

Epoch 49/64

3832/3832 - 24s - 6ms/step - ia: 0.6473 - loss: 0.4287 - mae: 0.4428 - rmse: 0.5906 - smape: 0.8166 - val_ia: 0.3104 - val_loss: 0.3003 - val_mae: 0.3281 - val_rmse: 0.3724 - val_smape: 0.6394

Epoch 50/64

3832/3832 - 42s - 11ms/step - ia: 0.6490 - loss: 0.4214 - mae: 0.4392 - rmse: 0.5861 - smape: 0.8181 - val_ia: 0.3130 - val_loss: 0.2964 - val_mae: 0.3251 - val_rmse: 0.3694 - val_smape: 0.6344

Epoch 51/64

3832/3832 - 35s - 9ms/step - ia: 0.6553 - loss: 0.4130 - mae: 0.4330 - rmse: 0.5792 - smape: 0.8069 - val_ia: 0.3155 - val_loss: 0.2926 - val_mae: 0.3223 - val_rmse: 0.3667 - val_smape: 0.6299

Epoch 52/64

3832/3832 - 14s - 4ms/step - ia: 0.6547 - loss: 0.4178 - mae: 0.4353 - rmse: 0.5809 - smape: 0.8091 - val_ia: 0.3182 - val_loss: 0.2889 - val_mae: 0.3192 - val_rmse: 0.3637 - val_smape: 0.6247

Epoch 53/64

3832/3832 - 17s - 5ms/step - ia: 0.6567 - loss: 0.4128 - mae: 0.4321 - rmse: 0.5776 - smape: 0.8044 - val_ia: 0.3205 - val_loss: 0.2853 - val_mae: 0.3166 - val_rmse: 0.3611 - val_smape: 0.6206

Epoch 54/64

3832/3832 - 20s - 5ms/step - ia: 0.6591 - loss: 0.4043 - mae: 0.4272 - rmse: 0.5719 - smape: 0.7956 - val_ia: 0.3227 - val_loss: 0.2817 - val_mae: 0.3143 - val_rmse: 0.3587 - val_smape: 0.6171

Epoch 55/64

3832/3832 - 12s - 3ms/step - ia: 0.6584 - loss: 0.4069 - mae: 0.4299 - rmse: 0.5737 - smape: 0.7984 - val_ia: 0.3249 - val_loss: 0.2784 - val_mae: 0.3117 - val_rmse: 0.3561 - val_smape: 0.6127

Epoch 56/64

3832/3832 - 9s - 2ms/step - ia: 0.6631 - loss: 0.3970 - mae: 0.4235 - rmse: 0.5676 - smape: 0.7896 - val_ia: 0.3273 - val_loss: 0.2751 - val_mae: 0.3090 - val_rmse: 0.3533 - val_smape: 0.6076

Epoch 57/64

3832/3832 - 12s - 3ms/step - ia: 0.6644 - loss: 0.3959 - mae: 0.4226 - rmse: 0.5650 - smape: 0.7890 - val_ia: 0.3297 - val_loss: 0.2718 - val_mae: 0.3064 - val_rmse: 0.3508 - val_smape: 0.6032

Epoch 58/64

3832/3832 - 19s - 5ms/step - ia: 0.6649 - loss: 0.3980 - mae: 0.4220 - rmse: 0.5652 - smape: 0.7869 - val_ia: 0.3317 - val_loss: 0.2687 - val_mae: 0.3042 - val_rmse: 0.3485 - val_smape: 0.5993

Epoch 59/64

3832/3832 - 21s - 6ms/step - ia: 0.6679 - loss: 0.3905 - mae: 0.4188 - rmse: 0.5603 - smape: 0.7850 - val_ia: 0.3335 - val_loss: 0.2656 - val_mae: 0.3023 - val_rmse: 0.3465 - val_smape: 0.5965

Epoch 60/64

3832/3832 - 19s - 5ms/step - ia: 0.6691 - loss: 0.3863 - mae: 0.4168 - rmse: 0.5575 - smape: 0.7826 - val_ia: 0.3355 - val_loss: 0.2626 - val_mae: 0.3000 - val_rmse: 0.3443 - val_smape: 0.5929

Epoch 61/64

3832/3832 - 12s - 3ms/step - ia: 0.6703 - loss: 0.3859 - mae: 0.4159 - rmse: 0.5576 - smape: 0.7776 - val_ia: 0.3377 - val_loss: 0.2596 - val_mae: 0.2976 - val_rmse: 0.3419 - val_smape: 0.5887

Epoch 62/64

3832/3832 - 13s - 3ms/step - ia: 0.6732 - loss: 0.3813 - mae: 0.4106 - rmse: 0.5512 - smape: 0.7667 - val_ia: 0.3393 - val_loss: 0.2567 - val_mae: 0.2957 - val_rmse: 0.3399 - val_smape: 0.5853

Epoch 63/64

3832/3832 - 22s - 6ms/step - ia: 0.6709 - loss: 0.3769 - mae: 0.4132 - rmse: 0.5514 - smape: 0.7740 - val_ia: 0.3416 - val_loss: 0.2539 - val_mae: 0.2933 - val_rmse: 0.3374 - val_smape: 0.5809

Epoch 64/64

3832/3832 - 21s - 5ms/step - ia: 0.6765 - loss: 0.3774 - mae: 0.4090 - rmse: 0.5491 - smape: 0.7703 - val_ia: 0.3437 - val_loss: 0.2511 - val_mae: 0.2910 - val_rmse: 0.3352 - val_smape: 0.5773

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:05 927ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 10%|█         | 5/50 [20:35<4:52:59, 390.65s/trial, best loss: 0.04486145343913409]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 11s - 12ms/step - ia: 0.3110 - loss: 3.6566 - mae: 1.4502 - rmse: 1.8852 - smape: 1.3980 - val_ia: 0.2683 - val_loss: 0.7801 - val_mae: 0.6631 - val_rmse: 0.8010 - val_smape: 1.1829

Epoch 2/128

958/958 - 5s - 5ms/step - ia: 0.3456 - loss: 3.1022 - mae: 1.3376 - rmse: 1.7342 - smape: 1.3542 - val_ia: 0.3071 - val_loss: 0.5895 - val_mae: 0.5690 - val_rmse: 0.6941 - val_smape: 1.0519

Epoch 3/128

958/958 - 9s - 9ms/step - ia: 0.3729 - loss: 2.6835 - mae: 1.2407 - rmse: 1.6145 - smape: 1.3135 - val_ia: 0.3398 - val_loss: 0.4811 - val_mae: 0.5083 - val_rmse: 0.6253 - val_smape: 0.9654

Epoch 4/128

958/958 - 8s - 8ms/step - ia: 0.3959 - loss: 2.3847 - mae: 1.1697 - rmse: 1.5220 - smape: 1.2858 - val_ia: 0.3684 - val_loss: 0.4081 - val_mae: 0.4641 - val_rmse: 0.5739 - val_smape: 0.9116

Epoch 5/128

958/958 - 7s - 7ms/step - ia: 0.4114 - loss: 2.1578 - mae: 1.1135 - rmse: 1.4465 - smape: 1.2632 - val_ia: 0.3959 - val_loss: 0.3532 - val_mae: 0.4283 - val_rmse: 0.5321 - val_smape: 0.8637

Epoch 6/128

958/958 - 7s - 8ms/step - ia: 0.4267 - loss: 1.9822 - mae: 1.0612 - rmse: 1.3839 - smape: 1.2419 - val_ia: 0.4181 - val_loss: 0.3139 - val_mae: 0.4013 - val_rmse: 0.4998 - val_smape: 0.8312

Epoch 7/128

958/958 - 11s - 11ms/step - ia: 0.4449 - loss: 1.7682 - mae: 1.0017 - rmse: 1.3084 - smape: 1.2177 - val_ia: 0.4374 - val_loss: 0.2839 - val_mae: 0.3792 - val_rmse: 0.4731 - val_smape: 0.8010

Epoch 8/128

958/958 - 8s - 8ms/step - ia: 0.4594 - loss: 1.5753 - mae: 0.9504 - rmse: 1.2371 - smape: 1.1960 - val_ia: 0.4585 - val_loss: 0.2580 - val_mae: 0.3587 - val_rmse: 0.4492 - val_smape: 0.7688

Epoch 9/128

958/958 - 4s - 4ms/step - ia: 0.4728 - loss: 1.4650 - mae: 0.9121 - rmse: 1.1908 - smape: 1.1835 - val_ia: 0.4758 - val_loss: 0.2377 - val_mae: 0.3420 - val_rmse: 0.4296 - val_smape: 0.7439

Epoch 10/128

958/958 - 8s - 9ms/step - ia: 0.4856 - loss: 1.3329 - mae: 0.8733 - rmse: 1.1373 - smape: 1.1649 - val_ia: 0.4916 - val_loss: 0.2214 - val_mae: 0.3277 - val_rmse: 0.4131 - val_smape: 0.7215

Epoch 11/128

958/958 - 6s - 7ms/step - ia: 0.4956 - loss: 1.2500 - mae: 0.8430 - rmse: 1.1014 - smape: 1.1522 - val_ia: 0.5055 - val_loss: 0.2085 - val_mae: 0.3157 - val_rmse: 0.3997 - val_smape: 0.7022

Epoch 12/128

958/958 - 10s - 10ms/step - ia: 0.5086 - loss: 1.1673 - mae: 0.8100 - rmse: 1.0614 - smape: 1.1337 - val_ia: 0.5167 - val_loss: 0.1983 - val_mae: 0.3057 - val_rmse: 0.3892 - val_smape: 0.6884

Epoch 13/128

958/958 - 11s - 11ms/step - ia: 0.5178 - loss: 1.0931 - mae: 0.7862 - rmse: 1.0282 - smape: 1.1197 - val_ia: 0.5285 - val_loss: 0.1877 - val_mae: 0.2957 - val_rmse: 0.3775 - val_smape: 0.6689

Epoch 14/128

958/958 - 4s - 5ms/step - ia: 0.5258 - loss: 1.0502 - mae: 0.7679 - rmse: 1.0059 - smape: 1.1103 - val_ia: 0.5353 - val_loss: 0.1816 - val_mae: 0.2903 - val_rmse: 0.3710 - val_smape: 0.6621

Epoch 15/128

958/958 - 4s - 4ms/step - ia: 0.5409 - loss: 0.9474 - mae: 0.7325 - rmse: 0.9594 - smape: 1.0821 - val_ia: 0.5436 - val_loss: 0.1743 - val_mae: 0.2836 - val_rmse: 0.3626 - val_smape: 0.6448

Epoch 16/128

958/958 - 5s - 5ms/step - ia: 0.5463 - loss: 0.9156 - mae: 0.7153 - rmse: 0.9406 - smape: 1.0768 - val_ia: 0.5517 - val_loss: 0.1687 - val_mae: 0.2775 - val_rmse: 0.3564 - val_smape: 0.6352

Epoch 17/128

958/958 - 3s - 3ms/step - ia: 0.5559 - loss: 0.8740 - mae: 0.6978 - rmse: 0.9184 - smape: 1.0618 - val_ia: 0.5583 - val_loss: 0.1638 - val_mae: 0.2727 - val_rmse: 0.3510 - val_smape: 0.6260

Epoch 18/128

958/958 - 3s - 3ms/step - ia: 0.5623 - loss: 0.8274 - mae: 0.6812 - rmse: 0.8942 - smape: 1.0555 - val_ia: 0.5625 - val_loss: 0.1604 - val_mae: 0.2696 - val_rmse: 0.3478 - val_smape: 0.6221

Epoch 19/128

958/958 - 4s - 4ms/step - ia: 0.5690 - loss: 0.7947 - mae: 0.6642 - rmse: 0.8768 - smape: 1.0415 - val_ia: 0.5688 - val_loss: 0.1558 - val_mae: 0.2650 - val_rmse: 0.3426 - val_smape: 0.6118

Epoch 20/128

958/958 - 4s - 4ms/step - ia: 0.5795 - loss: 0.7405 - mae: 0.6448 - rmse: 0.8461 - smape: 1.0270 - val_ia: 0.5728 - val_loss: 0.1524 - val_mae: 0.2620 - val_rmse: 0.3385 - val_smape: 0.6041

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.5831 - loss: 0.7232 - mae: 0.6338 - rmse: 0.8363 - smape: 1.0211 - val_ia: 0.5795 - val_loss: 0.1482 - val_mae: 0.2573 - val_rmse: 0.3341 - val_smape: 0.5965

Epoch 22/128

958/958 - 5s - 5ms/step - ia: 0.5913 - loss: 0.6931 - mae: 0.6214 - rmse: 0.8182 - smape: 1.0102 - val_ia: 0.5826 - val_loss: 0.1457 - val_mae: 0.2550 - val_rmse: 0.3311 - val_smape: 0.5910

Epoch 23/128

958/958 - 4s - 4ms/step - ia: 0.5988 - loss: 0.6677 - mae: 0.6072 - rmse: 0.8019 - smape: 0.9974 - val_ia: 0.5860 - val_loss: 0.1437 - val_mae: 0.2527 - val_rmse: 0.3287 - val_smape: 0.5877

Epoch 24/128

958/958 - 5s - 5ms/step - ia: 0.6016 - loss: 0.6445 - mae: 0.5964 - rmse: 0.7878 - smape: 0.9937 - val_ia: 0.5893 - val_loss: 0.1417 - val_mae: 0.2505 - val_rmse: 0.3263 - val_smape: 0.5828

Epoch 25/128

958/958 - 2s - 2ms/step - ia: 0.6084 - loss: 0.6178 - mae: 0.5860 - rmse: 0.7724 - smape: 0.9809 - val_ia: 0.5923 - val_loss: 0.1393 - val_mae: 0.2481 - val_rmse: 0.3234 - val_smape: 0.5777

Epoch 26/128

958/958 - 3s - 3ms/step - ia: 0.6148 - loss: 0.6023 - mae: 0.5747 - rmse: 0.7612 - smape: 0.9713 - val_ia: 0.5964 - val_loss: 0.1373 - val_mae: 0.2458 - val_rmse: 0.3206 - val_smape: 0.5717

Epoch 27/128

958/958 - 7s - 8ms/step - ia: 0.6167 - loss: 0.5851 - mae: 0.5681 - rmse: 0.7504 - smape: 0.9693 - val_ia: 0.5994 - val_loss: 0.1351 - val_mae: 0.2434 - val_rmse: 0.3185 - val_smape: 0.5686

Epoch 28/128

958/958 - 5s - 5ms/step - ia: 0.6242 - loss: 0.5639 - mae: 0.5558 - rmse: 0.7365 - smape: 0.9506 - val_ia: 0.6037 - val_loss: 0.1328 - val_mae: 0.2407 - val_rmse: 0.3160 - val_smape: 0.5639

Epoch 29/128

958/958 - 4s - 5ms/step - ia: 0.6274 - loss: 0.5469 - mae: 0.5482 - rmse: 0.7255 - smape: 0.9512 - val_ia: 0.6066 - val_loss: 0.1305 - val_mae: 0.2386 - val_rmse: 0.3131 - val_smape: 0.5591

Epoch 30/128

958/958 - 5s - 5ms/step - ia: 0.6287 - loss: 0.5337 - mae: 0.5446 - rmse: 0.7172 - smape: 0.9482 - val_ia: 0.6079 - val_loss: 0.1293 - val_mae: 0.2374 - val_rmse: 0.3115 - val_smape: 0.5561

Epoch 31/128

958/958 - 4s - 4ms/step - ia: 0.6384 - loss: 0.5117 - mae: 0.5289 - rmse: 0.7023 - smape: 0.9318 - val_ia: 0.6110 - val_loss: 0.1279 - val_mae: 0.2356 - val_rmse: 0.3098 - val_smape: 0.5529

Epoch 32/128

958/958 - 5s - 5ms/step - ia: 0.6426 - loss: 0.4949 - mae: 0.5209 - rmse: 0.6904 - smape: 0.9227 - val_ia: 0.6138 - val_loss: 0.1259 - val_mae: 0.2335 - val_rmse: 0.3074 - val_smape: 0.5484

Epoch 33/128

958/958 - 5s - 5ms/step - ia: 0.6490 - loss: 0.4694 - mae: 0.5112 - rmse: 0.6741 - smape: 0.9147 - val_ia: 0.6167 - val_loss: 0.1245 - val_mae: 0.2317 - val_rmse: 0.3058 - val_smape: 0.5461

Epoch 34/128

958/958 - 5s - 5ms/step - ia: 0.6501 - loss: 0.4744 - mae: 0.5079 - rmse: 0.6757 - smape: 0.9068 - val_ia: 0.6207 - val_loss: 0.1223 - val_mae: 0.2290 - val_rmse: 0.3030 - val_smape: 0.5412

Epoch 35/128

958/958 - 6s - 7ms/step - ia: 0.6522 - loss: 0.4670 - mae: 0.5056 - rmse: 0.6711 - smape: 0.9038 - val_ia: 0.6232 - val_loss: 0.1212 - val_mae: 0.2276 - val_rmse: 0.3017 - val_smape: 0.5389

Epoch 36/128

958/958 - 6s - 6ms/step - ia: 0.6615 - loss: 0.4445 - mae: 0.4911 - rmse: 0.6542 - smape: 0.8909 - val_ia: 0.6262 - val_loss: 0.1198 - val_mae: 0.2260 - val_rmse: 0.2999 - val_smape: 0.5359

Epoch 37/128

958/958 - 3s - 3ms/step - ia: 0.6643 - loss: 0.4324 - mae: 0.4863 - rmse: 0.6451 - smape: 0.8843 - val_ia: 0.6276 - val_loss: 0.1185 - val_mae: 0.2249 - val_rmse: 0.2983 - val_smape: 0.5325

Epoch 38/128

958/958 - 7s - 7ms/step - ia: 0.6656 - loss: 0.4267 - mae: 0.4818 - rmse: 0.6415 - smape: 0.8821 - val_ia: 0.6303 - val_loss: 0.1173 - val_mae: 0.2231 - val_rmse: 0.2967 - val_smape: 0.5293

Epoch 39/128

958/958 - 4s - 4ms/step - ia: 0.6698 - loss: 0.4116 - mae: 0.4755 - rmse: 0.6294 - smape: 0.8765 - val_ia: 0.6312 - val_loss: 0.1166 - val_mae: 0.2226 - val_rmse: 0.2955 - val_smape: 0.5277

Epoch 40/128

958/958 - 2s - 2ms/step - ia: 0.6731 - loss: 0.4089 - mae: 0.4698 - rmse: 0.6258 - smape: 0.8704 - val_ia: 0.6309 - val_loss: 0.1161 - val_mae: 0.2223 - val_rmse: 0.2947 - val_smape: 0.5259

Epoch 41/128

958/958 - 3s - 3ms/step - ia: 0.6759 - loss: 0.4014 - mae: 0.4642 - rmse: 0.6189 - smape: 0.8608 - val_ia: 0.6380 - val_loss: 0.1136 - val_mae: 0.2184 - val_rmse: 0.2918 - val_smape: 0.5208

Epoch 42/128

958/958 - 5s - 5ms/step - ia: 0.6785 - loss: 0.3918 - mae: 0.4596 - rmse: 0.6134 - smape: 0.8556 - val_ia: 0.6395 - val_loss: 0.1126 - val_mae: 0.2173 - val_rmse: 0.2904 - val_smape: 0.5182

Epoch 43/128

958/958 - 3s - 3ms/step - ia: 0.6811 - loss: 0.3851 - mae: 0.4567 - rmse: 0.6075 - smape: 0.8572 - val_ia: 0.6424 - val_loss: 0.1113 - val_mae: 0.2154 - val_rmse: 0.2883 - val_smape: 0.5144

Epoch 44/128

958/958 - 2s - 2ms/step - ia: 0.6851 - loss: 0.3743 - mae: 0.4496 - rmse: 0.5994 - smape: 0.8432 - val_ia: 0.6457 - val_loss: 0.1097 - val_mae: 0.2136 - val_rmse: 0.2866 - val_smape: 0.5112

Epoch 45/128

958/958 - 2s - 2ms/step - ia: 0.6855 - loss: 0.3678 - mae: 0.4476 - rmse: 0.5953 - smape: 0.8440 - val_ia: 0.6481 - val_loss: 0.1085 - val_mae: 0.2120 - val_rmse: 0.2849 - val_smape: 0.5085

Epoch 46/128

958/958 - 3s - 3ms/step - ia: 0.6907 - loss: 0.3604 - mae: 0.4415 - rmse: 0.5886 - smape: 0.8412 - val_ia: 0.6508 - val_loss: 0.1075 - val_mae: 0.2105 - val_rmse: 0.2834 - val_smape: 0.5060

Epoch 47/128

958/958 - 2s - 3ms/step - ia: 0.6951 - loss: 0.3537 - mae: 0.4366 - rmse: 0.5828 - smape: 0.8287 - val_ia: 0.6511 - val_loss: 0.1067 - val_mae: 0.2099 - val_rmse: 0.2826 - val_smape: 0.5048

Epoch 48/128

958/958 - 2s - 2ms/step - ia: 0.6967 - loss: 0.3482 - mae: 0.4320 - rmse: 0.5776 - smape: 0.8266 - val_ia: 0.6500 - val_loss: 0.1066 - val_mae: 0.2103 - val_rmse: 0.2824 - val_smape: 0.5044

Epoch 49/128

958/958 - 4s - 4ms/step - ia: 0.6987 - loss: 0.3417 - mae: 0.4276 - rmse: 0.5717 - smape: 0.8191 - val_ia: 0.6516 - val_loss: 0.1055 - val_mae: 0.2091 - val_rmse: 0.2808 - val_smape: 0.5022

Epoch 50/128

958/958 - 5s - 6ms/step - ia: 0.7020 - loss: 0.3365 - mae: 0.4226 - rmse: 0.5676 - smape: 0.8138 - val_ia: 0.6529 - val_loss: 0.1050 - val_mae: 0.2084 - val_rmse: 0.2801 - val_smape: 0.5005

Epoch 51/128

958/958 - 3s - 3ms/step - ia: 0.7045 - loss: 0.3266 - mae: 0.4183 - rmse: 0.5579 - smape: 0.8094 - val_ia: 0.6546 - val_loss: 0.1041 - val_mae: 0.2073 - val_rmse: 0.2789 - val_smape: 0.4988

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.7054 - loss: 0.3263 - mae: 0.4177 - rmse: 0.5591 - smape: 0.8091 - val_ia: 0.6566 - val_loss: 0.1034 - val_mae: 0.2063 - val_rmse: 0.2780 - val_smape: 0.4971

Epoch 53/128

958/958 - 5s - 6ms/step - ia: 0.7086 - loss: 0.3188 - mae: 0.4121 - rmse: 0.5526 - smape: 0.7976 - val_ia: 0.6592 - val_loss: 0.1022 - val_mae: 0.2047 - val_rmse: 0.2763 - val_smape: 0.4939

Epoch 54/128

958/958 - 5s - 5ms/step - ia: 0.7122 - loss: 0.3121 - mae: 0.4069 - rmse: 0.5467 - smape: 0.7928 - val_ia: 0.6588 - val_loss: 0.1019 - val_mae: 0.2048 - val_rmse: 0.2757 - val_smape: 0.4936

Epoch 55/128

958/958 - 5s - 5ms/step - ia: 0.7161 - loss: 0.3045 - mae: 0.4015 - rmse: 0.5401 - smape: 0.7846 - val_ia: 0.6602 - val_loss: 0.1013 - val_mae: 0.2038 - val_rmse: 0.2748 - val_smape: 0.4920

Epoch 56/128

958/958 - 5s - 6ms/step - ia: 0.7167 - loss: 0.3038 - mae: 0.4012 - rmse: 0.5382 - smape: 0.7891 - val_ia: 0.6628 - val_loss: 0.1003 - val_mae: 0.2024 - val_rmse: 0.2733 - val_smape: 0.4898

Epoch 57/128

958/958 - 4s - 4ms/step - ia: 0.7185 - loss: 0.2977 - mae: 0.3968 - rmse: 0.5336 - smape: 0.7781 - val_ia: 0.6631 - val_loss: 0.1000 - val_mae: 0.2022 - val_rmse: 0.2730 - val_smape: 0.4890

Epoch 58/128

958/958 - 3s - 3ms/step - ia: 0.7184 - loss: 0.3025 - mae: 0.3968 - rmse: 0.5357 - smape: 0.7773 - val_ia: 0.6678 - val_loss: 0.0985 - val_mae: 0.1997 - val_rmse: 0.2709 - val_smape: 0.4853

Epoch 59/128

958/958 - 5s - 5ms/step - ia: 0.7237 - loss: 0.2852 - mae: 0.3885 - rmse: 0.5233 - smape: 0.7703 - val_ia: 0.6706 - val_loss: 0.0974 - val_mae: 0.1981 - val_rmse: 0.2693 - val_smape: 0.4825

Epoch 60/128

958/958 - 3s - 4ms/step - ia: 0.7268 - loss: 0.2793 - mae: 0.3846 - rmse: 0.5175 - smape: 0.7644 - val_ia: 0.6710 - val_loss: 0.0970 - val_mae: 0.1978 - val_rmse: 0.2689 - val_smape: 0.4817

Epoch 61/128

958/958 - 3s - 4ms/step - ia: 0.7270 - loss: 0.2810 - mae: 0.3837 - rmse: 0.5172 - smape: 0.7637 - val_ia: 0.6718 - val_loss: 0.0967 - val_mae: 0.1973 - val_rmse: 0.2683 - val_smape: 0.4802

Epoch 62/128

958/958 - 5s - 6ms/step - ia: 0.7310 - loss: 0.2750 - mae: 0.3794 - rmse: 0.5122 - smape: 0.7599 - val_ia: 0.6721 - val_loss: 0.0963 - val_mae: 0.1970 - val_rmse: 0.2676 - val_smape: 0.4791

Epoch 63/128

958/958 - 7s - 7ms/step - ia: 0.7323 - loss: 0.2744 - mae: 0.3771 - rmse: 0.5104 - smape: 0.7541 - val_ia: 0.6743 - val_loss: 0.0956 - val_mae: 0.1959 - val_rmse: 0.2668 - val_smape: 0.4776

Epoch 64/128

958/958 - 5s - 5ms/step - ia: 0.7344 - loss: 0.2690 - mae: 0.3744 - rmse: 0.5064 - smape: 0.7480 - val_ia: 0.6763 - val_loss: 0.0944 - val_mae: 0.1944 - val_rmse: 0.2651 - val_smape: 0.4754

Epoch 65/128

958/958 - 4s - 4ms/step - ia: 0.7371 - loss: 0.2619 - mae: 0.3703 - rmse: 0.4996 - smape: 0.7438 - val_ia: 0.6748 - val_loss: 0.0945 - val_mae: 0.1950 - val_rmse: 0.2652 - val_smape: 0.4758

Epoch 66/128

958/958 - 5s - 6ms/step - ia: 0.7335 - loss: 0.2693 - mae: 0.3738 - rmse: 0.5061 - smape: 0.7495 - val_ia: 0.6776 - val_loss: 0.0936 - val_mae: 0.1935 - val_rmse: 0.2639 - val_smape: 0.4730

Epoch 67/128

958/958 - 9s - 9ms/step - ia: 0.7397 - loss: 0.2586 - mae: 0.3666 - rmse: 0.4950 - smape: 0.7403 - val_ia: 0.6795 - val_loss: 0.0928 - val_mae: 0.1924 - val_rmse: 0.2627 - val_smape: 0.4715

Epoch 68/128

958/958 - 2s - 3ms/step - ia: 0.7409 - loss: 0.2545 - mae: 0.3639 - rmse: 0.4916 - smape: 0.7359 - val_ia: 0.6807 - val_loss: 0.0924 - val_mae: 0.1917 - val_rmse: 0.2620 - val_smape: 0.4703

Epoch 69/128

958/958 - 5s - 5ms/step - ia: 0.7414 - loss: 0.2547 - mae: 0.3633 - rmse: 0.4925 - smape: 0.7330 - val_ia: 0.6786 - val_loss: 0.0928 - val_mae: 0.1928 - val_rmse: 0.2627 - val_smape: 0.4715

Epoch 70/128

958/958 - 5s - 5ms/step - ia: 0.7455 - loss: 0.2486 - mae: 0.3573 - rmse: 0.4849 - smape: 0.7227 - val_ia: 0.6815 - val_loss: 0.0919 - val_mae: 0.1913 - val_rmse: 0.2614 - val_smape: 0.4689

Epoch 71/128

958/958 - 5s - 5ms/step - ia: 0.7450 - loss: 0.2504 - mae: 0.3578 - rmse: 0.4871 - smape: 0.7261 - val_ia: 0.6860 - val_loss: 0.0905 - val_mae: 0.1889 - val_rmse: 0.2594 - val_smape: 0.4655

Epoch 72/128

958/958 - 2s - 2ms/step - ia: 0.7462 - loss: 0.2441 - mae: 0.3555 - rmse: 0.4815 - smape: 0.7160 - val_ia: 0.6858 - val_loss: 0.0904 - val_mae: 0.1887 - val_rmse: 0.2590 - val_smape: 0.4645

Epoch 73/128

958/958 - 3s - 3ms/step - ia: 0.7502 - loss: 0.2392 - mae: 0.3504 - rmse: 0.4767 - smape: 0.7116 - val_ia: 0.6887 - val_loss: 0.0895 - val_mae: 0.1873 - val_rmse: 0.2577 - val_smape: 0.4625

Epoch 74/128

958/958 - 4s - 4ms/step - ia: 0.7504 - loss: 0.2366 - mae: 0.3499 - rmse: 0.4741 - smape: 0.7143 - val_ia: 0.6858 - val_loss: 0.0900 - val_mae: 0.1887 - val_rmse: 0.2585 - val_smape: 0.4638

Epoch 75/128

958/958 - 3s - 4ms/step - ia: 0.7525 - loss: 0.2301 - mae: 0.3464 - rmse: 0.4679 - smape: 0.7138 - val_ia: 0.6882 - val_loss: 0.0893 - val_mae: 0.1875 - val_rmse: 0.2573 - val_smape: 0.4614

Epoch 76/128

958/958 - 5s - 5ms/step - ia: 0.7541 - loss: 0.2320 - mae: 0.3441 - rmse: 0.4679 - smape: 0.7061 - val_ia: 0.6899 - val_loss: 0.0887 - val_mae: 0.1865 - val_rmse: 0.2563 - val_smape: 0.4600

Epoch 77/128

958/958 - 2s - 2ms/step - ia: 0.7555 - loss: 0.2289 - mae: 0.3428 - rmse: 0.4657 - smape: 0.7040 - val_ia: 0.6898 - val_loss: 0.0885 - val_mae: 0.1864 - val_rmse: 0.2560 - val_smape: 0.4592

Epoch 78/128

958/958 - 2s - 2ms/step - ia: 0.7567 - loss: 0.2277 - mae: 0.3408 - rmse: 0.4637 - smape: 0.6988 - val_ia: 0.6925 - val_loss: 0.0876 - val_mae: 0.1849 - val_rmse: 0.2545 - val_smape: 0.4570

Epoch 79/128

958/958 - 3s - 3ms/step - ia: 0.7601 - loss: 0.2178 - mae: 0.3350 - rmse: 0.4554 - smape: 0.6913 - val_ia: 0.6957 - val_loss: 0.0867 - val_mae: 0.1834 - val_rmse: 0.2532 - val_smape: 0.4544

Epoch 80/128

958/958 - 3s - 4ms/step - ia: 0.7587 - loss: 0.2235 - mae: 0.3371 - rmse: 0.4588 - smape: 0.6969 - val_ia: 0.6942 - val_loss: 0.0870 - val_mae: 0.1839 - val_rmse: 0.2536 - val_smape: 0.4544

Epoch 81/128

958/958 - 2s - 2ms/step - ia: 0.7615 - loss: 0.2156 - mae: 0.3328 - rmse: 0.4520 - smape: 0.6913 - val_ia: 0.6926 - val_loss: 0.0872 - val_mae: 0.1846 - val_rmse: 0.2538 - val_smape: 0.4549

Epoch 82/128

958/958 - 2s - 2ms/step - ia: 0.7632 - loss: 0.2144 - mae: 0.3317 - rmse: 0.4516 - smape: 0.6851 - val_ia: 0.6965 - val_loss: 0.0860 - val_mae: 0.1826 - val_rmse: 0.2521 - val_smape: 0.4524

Epoch 83/128

958/958 - 4s - 5ms/step - ia: 0.7649 - loss: 0.2115 - mae: 0.3290 - rmse: 0.4474 - smape: 0.6856 - val_ia: 0.6958 - val_loss: 0.0859 - val_mae: 0.1827 - val_rmse: 0.2519 - val_smape: 0.4523

Epoch 84/128

958/958 - 6s - 7ms/step - ia: 0.7662 - loss: 0.2115 - mae: 0.3273 - rmse: 0.4461 - smape: 0.6789 - val_ia: 0.6980 - val_loss: 0.0854 - val_mae: 0.1818 - val_rmse: 0.2512 - val_smape: 0.4508

Epoch 85/128

958/958 - 5s - 5ms/step - ia: 0.7673 - loss: 0.2080 - mae: 0.3255 - rmse: 0.4434 - smape: 0.6777 - val_ia: 0.6987 - val_loss: 0.0851 - val_mae: 0.1814 - val_rmse: 0.2507 - val_smape: 0.4501

Epoch 86/128

958/958 - 2s - 2ms/step - ia: 0.7671 - loss: 0.2111 - mae: 0.3258 - rmse: 0.4463 - smape: 0.6761 - val_ia: 0.7008 - val_loss: 0.0844 - val_mae: 0.1803 - val_rmse: 0.2498 - val_smape: 0.4486

Epoch 87/128

958/958 - 4s - 4ms/step - ia: 0.7691 - loss: 0.2044 - mae: 0.3219 - rmse: 0.4389 - smape: 0.6734 - val_ia: 0.7024 - val_loss: 0.0838 - val_mae: 0.1793 - val_rmse: 0.2486 - val_smape: 0.4472

Epoch 88/128

958/958 - 5s - 5ms/step - ia: 0.7738 - loss: 0.1980 - mae: 0.3163 - rmse: 0.4326 - smape: 0.6663 - val_ia: 0.6999 - val_loss: 0.0844 - val_mae: 0.1806 - val_rmse: 0.2495 - val_smape: 0.4486

Epoch 89/128

958/958 - 4s - 4ms/step - ia: 0.7721 - loss: 0.2009 - mae: 0.3181 - rmse: 0.4361 - smape: 0.6662 - val_ia: 0.7032 - val_loss: 0.0834 - val_mae: 0.1789 - val_rmse: 0.2480 - val_smape: 0.4459

Epoch 90/128

958/958 - 6s - 6ms/step - ia: 0.7741 - loss: 0.1969 - mae: 0.3145 - rmse: 0.4312 - smape: 0.6602 - val_ia: 0.7045 - val_loss: 0.0830 - val_mae: 0.1782 - val_rmse: 0.2473 - val_smape: 0.4447

Epoch 91/128

958/958 - 3s - 3ms/step - ia: 0.7743 - loss: 0.1959 - mae: 0.3145 - rmse: 0.4304 - smape: 0.6605 - val_ia: 0.7035 - val_loss: 0.0831 - val_mae: 0.1786 - val_rmse: 0.2474 - val_smape: 0.4450

Epoch 92/128

958/958 - 4s - 4ms/step - ia: 0.7758 - loss: 0.1975 - mae: 0.3137 - rmse: 0.4312 - smape: 0.6593 - val_ia: 0.7066 - val_loss: 0.0822 - val_mae: 0.1770 - val_rmse: 0.2459 - val_smape: 0.4423

Epoch 93/128

958/958 - 4s - 5ms/step - ia: 0.7767 - loss: 0.1947 - mae: 0.3116 - rmse: 0.4279 - smape: 0.6550 - val_ia: 0.7073 - val_loss: 0.0818 - val_mae: 0.1765 - val_rmse: 0.2452 - val_smape: 0.4411

Epoch 94/128

958/958 - 5s - 5ms/step - ia: 0.7781 - loss: 0.1931 - mae: 0.3102 - rmse: 0.4261 - smape: 0.6559 - val_ia: 0.7086 - val_loss: 0.0814 - val_mae: 0.1758 - val_rmse: 0.2445 - val_smape: 0.4397

Epoch 95/128

958/958 - 5s - 5ms/step - ia: 0.7797 - loss: 0.1891 - mae: 0.3075 - rmse: 0.4224 - smape: 0.6481 - val_ia: 0.7087 - val_loss: 0.0814 - val_mae: 0.1757 - val_rmse: 0.2445 - val_smape: 0.4392

Epoch 96/128

958/958 - 6s - 6ms/step - ia: 0.7801 - loss: 0.1895 - mae: 0.3065 - rmse: 0.4228 - smape: 0.6490 - val_ia: 0.7098 - val_loss: 0.0810 - val_mae: 0.1752 - val_rmse: 0.2439 - val_smape: 0.4385

Epoch 97/128

958/958 - 9s - 9ms/step - ia: 0.7826 - loss: 0.1867 - mae: 0.3039 - rmse: 0.4181 - smape: 0.6404 - val_ia: 0.7104 - val_loss: 0.0806 - val_mae: 0.1747 - val_rmse: 0.2434 - val_smape: 0.4377

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 7s - 59ms/step - ia: 0.7783 - loss: 0.2408 - mae: 0.3230 - rmse: 0.4533 - smape: 0.6520 - val_ia: 0.8550 - val_loss: 0.0674 - val_mae: 0.1607 - val_rmse: 0.2456 - val_smape: 0.4127

Epoch 2/128

120/120 - 1s - 8ms/step - ia: 0.8483 - loss: 0.1126 - mae: 0.2187 - rmse: 0.3326 - smape: 0.4893 - val_ia: 0.8509 - val_loss: 0.0716 - val_mae: 0.1668 - val_rmse: 0.2493 - val_smape: 0.4113

Epoch 3/128

120/120 - 1s - 5ms/step - ia: 0.8595 - loss: 0.0984 - mae: 0.2034 - rmse: 0.3101 - smape: 0.4622 - val_ia: 0.8741 - val_loss: 0.0581 - val_mae: 0.1413 - val_rmse: 0.2264 - val_smape: 0.3747

Epoch 4/128

120/120 - 1s - 7ms/step - ia: 0.8632 - loss: 0.0963 - mae: 0.1985 - rmse: 0.3071 - smape: 0.4479 - val_ia: 0.8625 - val_loss: 0.0599 - val_mae: 0.1500 - val_rmse: 0.2301 - val_smape: 0.3800

Epoch 5/128

120/120 - 1s - 7ms/step - ia: 0.8657 - loss: 0.0935 - mae: 0.1949 - rmse: 0.3024 - smape: 0.4407 - val_ia: 0.8758 - val_loss: 0.0578 - val_mae: 0.1398 - val_rmse: 0.2242 - val_smape: 0.3708

Epoch 6/128

120/120 - 2s - 13ms/step - ia: 0.8657 - loss: 0.0944 - mae: 0.1949 - rmse: 0.3040 - smape: 0.4388 - val_ia: 0.8618 - val_loss: 0.0625 - val_mae: 0.1535 - val_rmse: 0.2339 - val_smape: 0.3829

Epoch 7/128

120/120 - 1s - 7ms/step - ia: 0.8625 - loss: 0.0977 - mae: 0.1992 - rmse: 0.3093 - smape: 0.4465 - val_ia: 0.8733 - val_loss: 0.0593 - val_mae: 0.1437 - val_rmse: 0.2289 - val_smape: 0.3790

Epoch 8/128

120/120 - 1s - 7ms/step - ia: 0.8661 - loss: 0.0955 - mae: 0.1948 - rmse: 0.3057 - smape: 0.4359 - val_ia: 0.8700 - val_loss: 0.0616 - val_mae: 0.1487 - val_rmse: 0.2302 - val_smape: 0.3722

Epoch 9/128

120/120 - 1s - 6ms/step - ia: 0.8672 - loss: 0.0919 - mae: 0.1932 - rmse: 0.2998 - smape: 0.4356 - val_ia: 0.8683 - val_loss: 0.0662 - val_mae: 0.1541 - val_rmse: 0.2378 - val_smape: 0.3823

Epoch 10/128

120/120 - 1s - 7ms/step - ia: 0.8658 - loss: 0.0938 - mae: 0.1949 - rmse: 0.3029 - smape: 0.4372 - val_ia: 0.8611 - val_loss: 0.0744 - val_mae: 0.1624 - val_rmse: 0.2493 - val_smape: 0.3861

Epoch 11/128

120/120 - 2s - 16ms/step - ia: 0.8658 - loss: 0.0929 - mae: 0.1947 - rmse: 0.3013 - smape: 0.4363 - val_ia: 0.8760 - val_loss: 0.0580 - val_mae: 0.1388 - val_rmse: 0.2248 - val_smape: 0.3667

Epoch 12/128

120/120 - 0s - 4ms/step - ia: 0.8674 - loss: 0.0912 - mae: 0.1929 - rmse: 0.2986 - smape: 0.4342 - val_ia: 0.8707 - val_loss: 0.0619 - val_mae: 0.1477 - val_rmse: 0.2317 - val_smape: 0.3724

Epoch 13/128

120/120 - 1s - 6ms/step - ia: 0.8658 - loss: 0.0950 - mae: 0.1949 - rmse: 0.3048 - smape: 0.4366 - val_ia: 0.8766 - val_loss: 0.0562 - val_mae: 0.1380 - val_rmse: 0.2220 - val_smape: 0.3607

Epoch 14/128

120/120 - 1s - 6ms/step - ia: 0.8669 - loss: 0.0912 - mae: 0.1937 - rmse: 0.2987 - smape: 0.4351 - val_ia: 0.8781 - val_loss: 0.0597 - val_mae: 0.1411 - val_rmse: 0.2268 - val_smape: 0.3628

Epoch 15/128

120/120 - 1s - 8ms/step - ia: 0.8676 - loss: 0.0927 - mae: 0.1923 - rmse: 0.3014 - smape: 0.4309 - val_ia: 0.8712 - val_loss: 0.0666 - val_mae: 0.1503 - val_rmse: 0.2372 - val_smape: 0.3695

Epoch 16/128

120/120 - 1s - 6ms/step - ia: 0.8638 - loss: 0.0967 - mae: 0.1979 - rmse: 0.3060 - smape: 0.4412 - val_ia: 0.8804 - val_loss: 0.0592 - val_mae: 0.1384 - val_rmse: 0.2276 - val_smape: 0.3622

Epoch 17/128

120/120 - 1s - 6ms/step - ia: 0.8637 - loss: 0.0944 - mae: 0.1980 - rmse: 0.3042 - smape: 0.4413 - val_ia: 0.8704 - val_loss: 0.0691 - val_mae: 0.1573 - val_rmse: 0.2411 - val_smape: 0.3788

Epoch 18/128

120/120 - 1s - 6ms/step - ia: 0.8661 - loss: 0.0918 - mae: 0.1948 - rmse: 0.2997 - smape: 0.4385 - val_ia: 0.8776 - val_loss: 0.0613 - val_mae: 0.1429 - val_rmse: 0.2293 - val_smape: 0.3575

Epoch 19/128

120/120 - 1s - 6ms/step - ia: 0.8632 - loss: 0.0975 - mae: 0.1988 - rmse: 0.3084 - smape: 0.4406 - val_ia: 0.8791 - val_loss: 0.0601 - val_mae: 0.1389 - val_rmse: 0.2277 - val_smape: 0.3628

Epoch 20/128

120/120 - 0s - 4ms/step - ia: 0.8665 - loss: 0.0910 - mae: 0.1942 - rmse: 0.2983 - smape: 0.4348 - val_ia: 0.8438 - val_loss: 0.0713 - val_mae: 0.1697 - val_rmse: 0.2510 - val_smape: 0.4077

Epoch 21/128

120/120 - 1s - 6ms/step - ia: 0.8652 - loss: 0.0922 - mae: 0.1960 - rmse: 0.3003 - smape: 0.4352 - val_ia: 0.8581 - val_loss: 0.0715 - val_mae: 0.1610 - val_rmse: 0.2461 - val_smape: 0.3842

Epoch 22/128

120/120 - 1s - 5ms/step - ia: 0.8659 - loss: 0.0912 - mae: 0.1948 - rmse: 0.2991 - smape: 0.4354 - val_ia: 0.8237 - val_loss: 0.0716 - val_mae: 0.1821 - val_rmse: 0.2549 - val_smape: 0.4478

Epoch 23/128

120/120 - 0s - 3ms/step - ia: 0.8643 - loss: 0.0935 - mae: 0.1972 - rmse: 0.3025 - smape: 0.4374 - val_ia: 0.8771 - val_loss: 0.0580 - val_mae: 0.1421 - val_rmse: 0.2256 - val_smape: 0.3682

Epoch 24/128

120/120 - 0s - 4ms/step - ia: 0.8631 - loss: 0.0955 - mae: 0.1989 - rmse: 0.3058 - smape: 0.4393 - val_ia: 0.8722 - val_loss: 0.0616 - val_mae: 0.1468 - val_rmse: 0.2302 - val_smape: 0.3744

Epoch 25/128

120/120 - 0s - 4ms/step - ia: 0.8651 - loss: 0.0930 - mae: 0.1957 - rmse: 0.3012 - smape: 0.4395 - val_ia: 0.8707 - val_loss: 0.0601 - val_mae: 0.1443 - val_rmse: 0.2290 - val_smape: 0.3731

Epoch 26/128

120/120 - 1s - 5ms/step - ia: 0.8661 - loss: 0.0918 - mae: 0.1945 - rmse: 0.2998 - smape: 0.4363 - val_ia: 0.8707 - val_loss: 0.0568 - val_mae: 0.1433 - val_rmse: 0.2234 - val_smape: 0.3721

Epoch 27/128

120/120 - 0s - 3ms/step - ia: 0.8625 - loss: 0.0977 - mae: 0.1997 - rmse: 0.3093 - smape: 0.4425 - val_ia: 0.8659 - val_loss: 0.0711 - val_mae: 0.1629 - val_rmse: 0.2454 - val_smape: 0.3815

Epoch 28/128

120/120 - 0s - 3ms/step - ia: 0.8625 - loss: 0.0956 - mae: 0.1994 - rmse: 0.3059 - smape: 0.4419 - val_ia: 0.8626 - val_loss: 0.0669 - val_mae: 0.1584 - val_rmse: 0.2415 - val_smape: 0.3839

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 13s 101ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 14%|█▍        | 7/50 [30:53<3:47:48, 317.87s/trial, best loss: 0.04101697135307742]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1916/1916 - 18s - 9ms/step - ia: 0.7626 - loss: 0.2291 - mae: 0.3256 - rmse: 0.4410 - smape: 0.6502 - val_ia: 0.6029 - val_loss: 0.0987 - val_mae: 0.1815 - val_rmse: 0.2373 - val_smape: 0.4246

Epoch 2/8

1916/1916 - 7s - 4ms/step - ia: 0.8056 - loss: 0.1523 - mae: 0.2654 - rmse: 0.3611 - smape: 0.5700 - val_ia: 0.5884 - val_loss: 0.0939 - val_mae: 0.1897 - val_rmse: 0.2414 - val_smape: 0.4560

Epoch 3/8

1916/1916 - 10s - 5ms/step - ia: 0.8136 - loss: 0.1390 - mae: 0.2540 - rmse: 0.3450 - smape: 0.5487 - val_ia: 0.6513 - val_loss: 0.0777 - val_mae: 0.1550 - val_rmse: 0.2111 - val_smape: 0.3793

Epoch 4/8

1916/1916 - 13s - 7ms/step - ia: 0.8185 - loss: 0.1311 - mae: 0.2466 - rmse: 0.3352 - smape: 0.5414 - val_ia: 0.5883 - val_loss: 0.0879 - val_mae: 0.1854 - val_rmse: 0.2392 - val_smape: 0.4725

Epoch 5/8

1916/1916 - 9s - 4ms/step - ia: 0.8190 - loss: 0.1336 - mae: 0.2475 - rmse: 0.3370 - smape: 0.5456 - val_ia: 0.6139 - val_loss: 0.0780 - val_mae: 0.1665 - val_rmse: 0.2192 - val_smape: 0.4003

Epoch 6/8

1916/1916 - 12s - 6ms/step - ia: 0.8204 - loss: 0.1310 - mae: 0.2452 - rmse: 0.3350 - smape: 0.5439 - val_ia: 0.6480 - val_loss: 0.0767 - val_mae: 0.1626 - val_rmse: 0.2181 - val_smape: 0.3841

Epoch 7/8

1916/1916 - 8s - 4ms/step - ia: 0.8180 - loss: 0.1297 - mae: 0.2473 - rmse: 0.3344 - smape: 0.5478 - val_ia: 0.6393 - val_loss: 0.0766 - val_mae: 0.1593 - val_rmse: 0.2143 - val_smape: 0.3745

Epoch 8/8

1916/1916 - 7s - 4ms/step - ia: 0.8193 - loss: 0.1292 - mae: 0.2447 - rmse: 0.3326 - smape: 0.5462 - val_ia: 0.6353 - val_loss: 0.0733 - val_mae: 0.1581 - val_rmse: 0.2107 - val_smape: 0.3876

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 43s 319ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 16%|█▌        | 8/50 [32:20<2:50:59, 244.27s/trial, best loss: 0.04101697135307742]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 18s - 154ms/step - ia: 0.6469 - loss: 0.5737 - mae: 0.5490 - rmse: 0.7348 - smape: 0.9214 - val_ia: 0.7722 - val_loss: 0.1300 - val_mae: 0.2515 - val_rmse: 0.3423 - val_smape: 0.5892

Epoch 2/128

120/120 - 1s - 7ms/step - ia: 0.7544 - loss: 0.2522 - mae: 0.3544 - rmse: 0.4991 - smape: 0.7197 - val_ia: 0.8215 - val_loss: 0.0909 - val_mae: 0.1978 - val_rmse: 0.2839 - val_smape: 0.4840

Epoch 3/128

120/120 - 2s - 14ms/step - ia: 0.7881 - loss: 0.1930 - mae: 0.3045 - rmse: 0.4366 - smape: 0.6439 - val_ia: 0.8422 - val_loss: 0.0779 - val_mae: 0.1760 - val_rmse: 0.2619 - val_smape: 0.4371

Epoch 4/128

120/120 - 1s - 9ms/step - ia: 0.8078 - loss: 0.1631 - mae: 0.2747 - rmse: 0.4008 - smape: 0.5924 - val_ia: 0.8551 - val_loss: 0.0710 - val_mae: 0.1629 - val_rmse: 0.2501 - val_smape: 0.4147

Epoch 5/128

120/120 - 1s - 6ms/step - ia: 0.8181 - loss: 0.1479 - mae: 0.2600 - rmse: 0.3821 - smape: 0.5637 - val_ia: 0.8466 - val_loss: 0.0725 - val_mae: 0.1680 - val_rmse: 0.2537 - val_smape: 0.4244

Epoch 6/128

120/120 - 1s - 7ms/step - ia: 0.8255 - loss: 0.1427 - mae: 0.2492 - rmse: 0.3742 - smape: 0.5426 - val_ia: 0.8559 - val_loss: 0.0691 - val_mae: 0.1606 - val_rmse: 0.2461 - val_smape: 0.4028

Epoch 7/128

120/120 - 1s - 7ms/step - ia: 0.8316 - loss: 0.1338 - mae: 0.2411 - rmse: 0.3625 - smape: 0.5232 - val_ia: 0.8569 - val_loss: 0.0679 - val_mae: 0.1583 - val_rmse: 0.2444 - val_smape: 0.3998

Epoch 8/128

120/120 - 1s - 8ms/step - ia: 0.8346 - loss: 0.1295 - mae: 0.2363 - rmse: 0.3567 - smape: 0.5144 - val_ia: 0.8709 - val_loss: 0.0625 - val_mae: 0.1459 - val_rmse: 0.2345 - val_smape: 0.3836

Epoch 9/128

120/120 - 1s - 9ms/step - ia: 0.8366 - loss: 0.1275 - mae: 0.2341 - rmse: 0.3541 - smape: 0.5073 - val_ia: 0.8576 - val_loss: 0.0667 - val_mae: 0.1576 - val_rmse: 0.2418 - val_smape: 0.3936

Epoch 10/128

120/120 - 1s - 6ms/step - ia: 0.8400 - loss: 0.1241 - mae: 0.2285 - rmse: 0.3489 - smape: 0.4967 - val_ia: 0.8697 - val_loss: 0.0618 - val_mae: 0.1463 - val_rmse: 0.2324 - val_smape: 0.3768

Epoch 11/128

120/120 - 1s - 5ms/step - ia: 0.8413 - loss: 0.1218 - mae: 0.2275 - rmse: 0.3461 - smape: 0.4928 - val_ia: 0.8552 - val_loss: 0.0667 - val_mae: 0.1587 - val_rmse: 0.2419 - val_smape: 0.3922

Epoch 12/128

120/120 - 1s - 7ms/step - ia: 0.8438 - loss: 0.1195 - mae: 0.2239 - rmse: 0.3418 - smape: 0.4842 - val_ia: 0.8647 - val_loss: 0.0626 - val_mae: 0.1506 - val_rmse: 0.2339 - val_smape: 0.3805

Epoch 13/128

120/120 - 1s - 7ms/step - ia: 0.8432 - loss: 0.1213 - mae: 0.2245 - rmse: 0.3457 - smape: 0.4836 - val_ia: 0.8716 - val_loss: 0.0605 - val_mae: 0.1452 - val_rmse: 0.2295 - val_smape: 0.3730

Epoch 14/128

120/120 - 1s - 6ms/step - ia: 0.8446 - loss: 0.1191 - mae: 0.2219 - rmse: 0.3415 - smape: 0.4806 - val_ia: 0.8670 - val_loss: 0.0623 - val_mae: 0.1497 - val_rmse: 0.2329 - val_smape: 0.3759

Epoch 15/128

120/120 - 1s - 7ms/step - ia: 0.8461 - loss: 0.1192 - mae: 0.2205 - rmse: 0.3415 - smape: 0.4741 - val_ia: 0.8645 - val_loss: 0.0631 - val_mae: 0.1506 - val_rmse: 0.2346 - val_smape: 0.3778

Epoch 16/128

120/120 - 1s - 6ms/step - ia: 0.8452 - loss: 0.1206 - mae: 0.2216 - rmse: 0.3438 - smape: 0.4754 - val_ia: 0.8704 - val_loss: 0.0608 - val_mae: 0.1448 - val_rmse: 0.2304 - val_smape: 0.3722

Epoch 17/128

120/120 - 1s - 7ms/step - ia: 0.8454 - loss: 0.1215 - mae: 0.2211 - rmse: 0.3444 - smape: 0.4756 - val_ia: 0.8762 - val_loss: 0.0589 - val_mae: 0.1399 - val_rmse: 0.2261 - val_smape: 0.3626

Epoch 18/128

120/120 - 1s - 12ms/step - ia: 0.8479 - loss: 0.1176 - mae: 0.2180 - rmse: 0.3385 - smape: 0.4673 - val_ia: 0.8613 - val_loss: 0.0628 - val_mae: 0.1513 - val_rmse: 0.2351 - val_smape: 0.3866

Epoch 19/128

120/120 - 1s - 7ms/step - ia: 0.8488 - loss: 0.1155 - mae: 0.2168 - rmse: 0.3359 - smape: 0.4665 - val_ia: 0.8731 - val_loss: 0.0592 - val_mae: 0.1430 - val_rmse: 0.2269 - val_smape: 0.3699

Epoch 20/128

120/120 - 2s - 13ms/step - ia: 0.8479 - loss: 0.1171 - mae: 0.2181 - rmse: 0.3396 - smape: 0.4680 - val_ia: 0.8749 - val_loss: 0.0594 - val_mae: 0.1412 - val_rmse: 0.2270 - val_smape: 0.3650

Epoch 21/128

120/120 - 1s - 11ms/step - ia: 0.8481 - loss: 0.1147 - mae: 0.2175 - rmse: 0.3358 - smape: 0.4665 - val_ia: 0.8716 - val_loss: 0.0600 - val_mae: 0.1438 - val_rmse: 0.2281 - val_smape: 0.3678

Epoch 22/128

120/120 - 1s - 5ms/step - ia: 0.8484 - loss: 0.1164 - mae: 0.2176 - rmse: 0.3384 - smape: 0.4654 - val_ia: 0.8707 - val_loss: 0.0595 - val_mae: 0.1457 - val_rmse: 0.2281 - val_smape: 0.3774

Epoch 23/128

120/120 - 1s - 7ms/step - ia: 0.8477 - loss: 0.1176 - mae: 0.2180 - rmse: 0.3398 - smape: 0.4670 - val_ia: 0.8681 - val_loss: 0.0613 - val_mae: 0.1477 - val_rmse: 0.2306 - val_smape: 0.3714

Epoch 24/128

120/120 - 1s - 10ms/step - ia: 0.8500 - loss: 0.1135 - mae: 0.2154 - rmse: 0.3339 - smape: 0.4636 - val_ia: 0.8673 - val_loss: 0.0613 - val_mae: 0.1488 - val_rmse: 0.2310 - val_smape: 0.3749

Epoch 25/128

120/120 - 1s - 6ms/step - ia: 0.8498 - loss: 0.1124 - mae: 0.2155 - rmse: 0.3318 - smape: 0.4608 - val_ia: 0.8749 - val_loss: 0.0587 - val_mae: 0.1405 - val_rmse: 0.2263 - val_smape: 0.3662

Epoch 26/128

120/120 - 1s - 12ms/step - ia: 0.8517 - loss: 0.1124 - mae: 0.2127 - rmse: 0.3314 - smape: 0.4607 - val_ia: 0.8720 - val_loss: 0.0595 - val_mae: 0.1431 - val_rmse: 0.2274 - val_smape: 0.3688

Epoch 27/128

120/120 - 1s - 5ms/step - ia: 0.8505 - loss: 0.1135 - mae: 0.2148 - rmse: 0.3335 - smape: 0.4573 - val_ia: 0.8740 - val_loss: 0.0595 - val_mae: 0.1414 - val_rmse: 0.2273 - val_smape: 0.3647

Epoch 28/128

120/120 - 1s - 8ms/step - ia: 0.8476 - loss: 0.1170 - mae: 0.2181 - rmse: 0.3389 - smape: 0.4661 - val_ia: 0.8729 - val_loss: 0.0588 - val_mae: 0.1433 - val_rmse: 0.2268 - val_smape: 0.3741

Epoch 29/128

120/120 - 1s - 6ms/step - ia: 0.8502 - loss: 0.1172 - mae: 0.2148 - rmse: 0.3388 - smape: 0.4585 - val_ia: 0.8798 - val_loss: 0.0569 - val_mae: 0.1360 - val_rmse: 0.2222 - val_smape: 0.3586

Epoch 30/128

120/120 - 0s - 3ms/step - ia: 0.8509 - loss: 0.1147 - mae: 0.2136 - rmse: 0.3349 - smape: 0.4591 - val_ia: 0.8753 - val_loss: 0.0579 - val_mae: 0.1409 - val_rmse: 0.2248 - val_smape: 0.3695

Epoch 31/128

120/120 - 0s - 3ms/step - ia: 0.8519 - loss: 0.1112 - mae: 0.2128 - rmse: 0.3305 - smape: 0.4563 - val_ia: 0.8626 - val_loss: 0.0625 - val_mae: 0.1508 - val_rmse: 0.2342 - val_smape: 0.3821

Epoch 32/128

120/120 - 0s - 3ms/step - ia: 0.8514 - loss: 0.1132 - mae: 0.2130 - rmse: 0.3327 - smape: 0.4572 - val_ia: 0.8815 - val_loss: 0.0571 - val_mae: 0.1340 - val_rmse: 0.2225 - val_smape: 0.3566

Epoch 33/128

120/120 - 1s - 7ms/step - ia: 0.8503 - loss: 0.1111 - mae: 0.2141 - rmse: 0.3303 - smape: 0.4580 - val_ia: 0.8754 - val_loss: 0.0589 - val_mae: 0.1401 - val_rmse: 0.2261 - val_smape: 0.3625

Epoch 34/128

120/120 - 1s - 5ms/step - ia: 0.8516 - loss: 0.1126 - mae: 0.2129 - rmse: 0.3328 - smape: 0.4555 - val_ia: 0.8697 - val_loss: 0.0609 - val_mae: 0.1485 - val_rmse: 0.2302 - val_smape: 0.3792

Epoch 35/128

120/120 - 1s - 5ms/step - ia: 0.8506 - loss: 0.1126 - mae: 0.2141 - rmse: 0.3325 - smape: 0.4586 - val_ia: 0.8694 - val_loss: 0.0609 - val_mae: 0.1469 - val_rmse: 0.2295 - val_smape: 0.3698

Epoch 36/128

120/120 - 1s - 8ms/step - ia: 0.8520 - loss: 0.1137 - mae: 0.2125 - rmse: 0.3341 - smape: 0.4536 - val_ia: 0.8767 - val_loss: 0.0581 - val_mae: 0.1386 - val_rmse: 0.2244 - val_smape: 0.3604

Epoch 37/128

120/120 - 1s - 6ms/step - ia: 0.8513 - loss: 0.1126 - mae: 0.2135 - rmse: 0.3312 - smape: 0.4584 - val_ia: 0.8652 - val_loss: 0.0625 - val_mae: 0.1493 - val_rmse: 0.2334 - val_smape: 0.3761

Epoch 38/128

120/120 - 1s - 5ms/step - ia: 0.8521 - loss: 0.1104 - mae: 0.2121 - rmse: 0.3290 - smape: 0.4550 - val_ia: 0.8723 - val_loss: 0.0588 - val_mae: 0.1424 - val_rmse: 0.2263 - val_smape: 0.3668

Epoch 39/128

120/120 - 1s - 5ms/step - ia: 0.8524 - loss: 0.1128 - mae: 0.2118 - rmse: 0.3327 - smape: 0.4527 - val_ia: 0.8723 - val_loss: 0.0590 - val_mae: 0.1427 - val_rmse: 0.2265 - val_smape: 0.3659

Epoch 40/128

120/120 - 1s - 6ms/step - ia: 0.8518 - loss: 0.1126 - mae: 0.2128 - rmse: 0.3325 - smape: 0.4542 - val_ia: 0.8588 - val_loss: 0.0640 - val_mae: 0.1545 - val_rmse: 0.2362 - val_smape: 0.3820

Epoch 41/128

120/120 - 1s - 6ms/step - ia: 0.8515 - loss: 0.1126 - mae: 0.2130 - rmse: 0.3320 - smape: 0.4545 - val_ia: 0.8713 - val_loss: 0.0594 - val_mae: 0.1437 - val_rmse: 0.2272 - val_smape: 0.3686

Epoch 42/128

120/120 - 1s - 5ms/step - ia: 0.8508 - loss: 0.1124 - mae: 0.2138 - rmse: 0.3324 - smape: 0.4575 - val_ia: 0.8741 - val_loss: 0.0591 - val_mae: 0.1406 - val_rmse: 0.2266 - val_smape: 0.3631

Epoch 43/128

120/120 - 1s - 7ms/step - ia: 0.8504 - loss: 0.1145 - mae: 0.2147 - rmse: 0.3348 - smape: 0.4595 - val_ia: 0.8742 - val_loss: 0.0584 - val_mae: 0.1411 - val_rmse: 0.2253 - val_smape: 0.3656

Epoch 44/128

120/120 - 1s - 10ms/step - ia: 0.8516 - loss: 0.1131 - mae: 0.2127 - rmse: 0.3324 - smape: 0.4564 - val_ia: 0.8815 - val_loss: 0.0570 - val_mae: 0.1346 - val_rmse: 0.2218 - val_smape: 0.3546

Epoch 44: early stopping

Restoring model weights from the end of the best epoch: 29.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 36s 274ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 18%|█▊        | 9/50 [33:18<2:07:14, 186.21s/trial, best loss: 0.040197158344431334]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 18s - 18ms/step - ia: 0.5998 - loss: 0.5881 - mae: 0.5571 - rmse: 0.7379 - smape: 0.9942 - val_ia: 0.5586 - val_loss: 0.1505 - val_mae: 0.2666 - val_rmse: 0.3440 - val_smape: 0.6305

Epoch 2/16

958/958 - 8s - 8ms/step - ia: 0.7111 - loss: 0.3008 - mae: 0.3939 - rmse: 0.5339 - smape: 0.7942 - val_ia: 0.5732 - val_loss: 0.1276 - val_mae: 0.2515 - val_rmse: 0.3194 - val_smape: 0.5912

Epoch 3/16

958/958 - 3s - 3ms/step - ia: 0.7539 - loss: 0.2276 - mae: 0.3364 - rmse: 0.4621 - smape: 0.7026 - val_ia: 0.5869 - val_loss: 0.1211 - val_mae: 0.2436 - val_rmse: 0.3073 - val_smape: 0.5609

Epoch 4/16

958/958 - 3s - 3ms/step - ia: 0.7782 - loss: 0.1850 - mae: 0.3027 - rmse: 0.4173 - smape: 0.6464 - val_ia: 0.5743 - val_loss: 0.1213 - val_mae: 0.2507 - val_rmse: 0.3093 - val_smape: 0.5634

Epoch 5/16

958/958 - 4s - 4ms/step - ia: 0.7947 - loss: 0.1694 - mae: 0.2830 - rmse: 0.3970 - smape: 0.6087 - val_ia: 0.5699 - val_loss: 0.1153 - val_mae: 0.2514 - val_rmse: 0.3068 - val_smape: 0.5679

Epoch 6/16

958/958 - 5s - 6ms/step - ia: 0.8077 - loss: 0.1516 - mae: 0.2652 - rmse: 0.3749 - smape: 0.5774 - val_ia: 0.5722 - val_loss: 0.1241 - val_mae: 0.2553 - val_rmse: 0.3097 - val_smape: 0.5626

Epoch 7/16

958/958 - 6s - 6ms/step - ia: 0.8170 - loss: 0.1384 - mae: 0.2531 - rmse: 0.3573 - smape: 0.5545 - val_ia: 0.5788 - val_loss: 0.1140 - val_mae: 0.2478 - val_rmse: 0.3010 - val_smape: 0.5511

Epoch 8/16

958/958 - 4s - 4ms/step - ia: 0.8235 - loss: 0.1318 - mae: 0.2443 - rmse: 0.3485 - smape: 0.5396 - val_ia: 0.5905 - val_loss: 0.1079 - val_mae: 0.2401 - val_rmse: 0.2926 - val_smape: 0.5354

Epoch 9/16

958/958 - 4s - 4ms/step - ia: 0.8306 - loss: 0.1229 - mae: 0.2351 - rmse: 0.3356 - smape: 0.5218 - val_ia: 0.5979 - val_loss: 0.1044 - val_mae: 0.2341 - val_rmse: 0.2869 - val_smape: 0.5271

Epoch 10/16

958/958 - 2s - 3ms/step - ia: 0.8334 - loss: 0.1205 - mae: 0.2311 - rmse: 0.3320 - smape: 0.5124 - val_ia: 0.6033 - val_loss: 0.0979 - val_mae: 0.2291 - val_rmse: 0.2814 - val_smape: 0.5202

Epoch 11/16

958/958 - 2s - 2ms/step - ia: 0.8373 - loss: 0.1154 - mae: 0.2272 - rmse: 0.3249 - smape: 0.5042 - val_ia: 0.6157 - val_loss: 0.0973 - val_mae: 0.2233 - val_rmse: 0.2758 - val_smape: 0.5049

Epoch 12/16

958/958 - 4s - 4ms/step - ia: 0.8409 - loss: 0.1128 - mae: 0.2219 - rmse: 0.3194 - smape: 0.4925 - val_ia: 0.6033 - val_loss: 0.1011 - val_mae: 0.2313 - val_rmse: 0.2828 - val_smape: 0.5165

Epoch 13/16

958/958 - 4s - 4ms/step - ia: 0.8448 - loss: 0.1069 - mae: 0.2173 - rmse: 0.3127 - smape: 0.4864 - val_ia: 0.6291 - val_loss: 0.0913 - val_mae: 0.2134 - val_rmse: 0.2663 - val_smape: 0.4900

Epoch 14/16

958/958 - 7s - 8ms/step - ia: 0.8466 - loss: 0.1064 - mae: 0.2143 - rmse: 0.3103 - smape: 0.4787 - val_ia: 0.6367 - val_loss: 0.0886 - val_mae: 0.2087 - val_rmse: 0.2617 - val_smape: 0.4781

Epoch 15/16

958/958 - 14s - 14ms/step - ia: 0.8493 - loss: 0.1059 - mae: 0.2114 - rmse: 0.3090 - smape: 0.4734 - val_ia: 0.6314 - val_loss: 0.0848 - val_mae: 0.2084 - val_rmse: 0.2603 - val_smape: 0.4838

Epoch 16/16

958/958 - 7s - 7ms/step - ia: 0.8495 - loss: 0.1031 - mae: 0.2110 - rmse: 0.3057 - smape: 0.4713 - val_ia: 0.6335 - val_loss: 0.0876 - val_mae: 0.2095 - val_rmse: 0.2616 - val_smape: 0.4804

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 30s 229ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 20%|██        | 10/50 [34:56<1:45:53, 158.85s/trial, best loss: 0.040197158344431334]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 14s - 59ms/step - ia: 0.1987 - loss: 14.4434 - mae: 2.6948 - rmse: 3.7812 - smape: 1.5341 - val_ia: 0.2639 - val_loss: 4.6034 - val_mae: 1.7860 - val_rmse: 2.0422 - val_smape: 1.5148

Epoch 2/8

240/240 - 3s - 11ms/step - ia: 0.2012 - loss: 14.2479 - mae: 2.6732 - rmse: 3.7545 - smape: 1.5320 - val_ia: 0.2662 - val_loss: 4.4573 - val_mae: 1.7548 - val_rmse: 2.0104 - val_smape: 1.5109

Epoch 3/8

240/240 - 2s - 7ms/step - ia: 0.2026 - loss: 13.8418 - mae: 2.6322 - rmse: 3.6985 - smape: 1.5269 - val_ia: 0.2685 - val_loss: 4.3171 - val_mae: 1.7244 - val_rmse: 1.9795 - val_smape: 1.5067

Epoch 4/8

240/240 - 2s - 6ms/step - ia: 0.2020 - loss: 13.8628 - mae: 2.6462 - rmse: 3.7027 - smape: 1.5314 - val_ia: 0.2709 - val_loss: 4.1796 - val_mae: 1.6940 - val_rmse: 1.9486 - val_smape: 1.5028

Epoch 5/8

240/240 - 2s - 10ms/step - ia: 0.2053 - loss: 13.3514 - mae: 2.5818 - rmse: 3.6327 - smape: 1.5253 - val_ia: 0.2732 - val_loss: 4.0505 - val_mae: 1.6649 - val_rmse: 1.9192 - val_smape: 1.4983

Epoch 6/8

240/240 - 3s - 11ms/step - ia: 0.2080 - loss: 12.7703 - mae: 2.5488 - rmse: 3.5562 - smape: 1.5208 - val_ia: 0.2755 - val_loss: 3.9276 - val_mae: 1.6368 - val_rmse: 1.8906 - val_smape: 1.4946

Epoch 7/8

240/240 - 2s - 8ms/step - ia: 0.2078 - loss: 12.6861 - mae: 2.5348 - rmse: 3.5405 - smape: 1.5245 - val_ia: 0.2777 - val_loss: 3.8093 - val_mae: 1.6092 - val_rmse: 1.8628 - val_smape: 1.4906

Epoch 8/8

240/240 - 1s - 4ms/step - ia: 0.2095 - loss: 12.4752 - mae: 2.5237 - rmse: 3.5183 - smape: 1.5194 - val_ia: 0.2800 - val_loss: 3.6948 - val_mae: 1.5821 - val_rmse: 1.8353 - val_smape: 1.4868

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 19s 141ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 18s - 19ms/step - ia: 0.6944 - loss: 0.3544 - mae: 0.4346 - rmse: 0.5719 - smape: 0.8326 - val_ia: 0.6770 - val_loss: 0.1065 - val_mae: 0.2009 - val_rmse: 0.2753 - val_smape: 0.4845

Epoch 2/128

958/958 - 5s - 6ms/step - ia: 0.7696 - loss: 0.2057 - mae: 0.3315 - rmse: 0.4415 - smape: 0.6881 - val_ia: 0.7196 - val_loss: 0.0844 - val_mae: 0.1730 - val_rmse: 0.2443 - val_smape: 0.4279

Epoch 3/128

958/958 - 5s - 6ms/step - ia: 0.7979 - loss: 0.1627 - mae: 0.2881 - rmse: 0.3904 - smape: 0.6234 - val_ia: 0.7306 - val_loss: 0.0787 - val_mae: 0.1660 - val_rmse: 0.2359 - val_smape: 0.4185

Epoch 4/128

958/958 - 4s - 4ms/step - ia: 0.8181 - loss: 0.1388 - mae: 0.2602 - rmse: 0.3585 - smape: 0.5728 - val_ia: 0.7501 - val_loss: 0.0742 - val_mae: 0.1559 - val_rmse: 0.2253 - val_smape: 0.3918

Epoch 5/128

958/958 - 6s - 6ms/step - ia: 0.8300 - loss: 0.1264 - mae: 0.2426 - rmse: 0.3398 - smape: 0.5435 - val_ia: 0.7568 - val_loss: 0.0730 - val_mae: 0.1526 - val_rmse: 0.2239 - val_smape: 0.3838

Epoch 6/128

958/958 - 4s - 4ms/step - ia: 0.8398 - loss: 0.1177 - mae: 0.2303 - rmse: 0.3263 - smape: 0.5202 - val_ia: 0.7600 - val_loss: 0.0710 - val_mae: 0.1508 - val_rmse: 0.2181 - val_smape: 0.3775

Epoch 7/128

958/958 - 4s - 4ms/step - ia: 0.8437 - loss: 0.1121 - mae: 0.2235 - rmse: 0.3191 - smape: 0.5080 - val_ia: 0.7726 - val_loss: 0.0681 - val_mae: 0.1438 - val_rmse: 0.2140 - val_smape: 0.3646

Epoch 8/128

958/958 - 4s - 5ms/step - ia: 0.8485 - loss: 0.1076 - mae: 0.2172 - rmse: 0.3112 - smape: 0.4964 - val_ia: 0.7723 - val_loss: 0.0665 - val_mae: 0.1415 - val_rmse: 0.2110 - val_smape: 0.3608

Epoch 9/128

958/958 - 6s - 6ms/step - ia: 0.8522 - loss: 0.1029 - mae: 0.2115 - rmse: 0.3039 - smape: 0.4863 - val_ia: 0.7782 - val_loss: 0.0652 - val_mae: 0.1391 - val_rmse: 0.2066 - val_smape: 0.3564

Epoch 10/128

958/958 - 4s - 4ms/step - ia: 0.8548 - loss: 0.1010 - mae: 0.2080 - rmse: 0.3002 - smape: 0.4804 - val_ia: 0.7728 - val_loss: 0.0650 - val_mae: 0.1398 - val_rmse: 0.2091 - val_smape: 0.3589

Epoch 11/128

958/958 - 5s - 6ms/step - ia: 0.8573 - loss: 0.0982 - mae: 0.2037 - rmse: 0.2962 - smape: 0.4714 - val_ia: 0.7733 - val_loss: 0.0651 - val_mae: 0.1403 - val_rmse: 0.2055 - val_smape: 0.3565

Epoch 12/128

958/958 - 5s - 5ms/step - ia: 0.8600 - loss: 0.0965 - mae: 0.2007 - rmse: 0.2934 - smape: 0.4670 - val_ia: 0.7726 - val_loss: 0.0628 - val_mae: 0.1381 - val_rmse: 0.2061 - val_smape: 0.3576

Epoch 13/128

958/958 - 3s - 4ms/step - ia: 0.8625 - loss: 0.0934 - mae: 0.1967 - rmse: 0.2878 - smape: 0.4627 - val_ia: 0.7811 - val_loss: 0.0623 - val_mae: 0.1358 - val_rmse: 0.2017 - val_smape: 0.3521

Epoch 14/128

958/958 - 5s - 5ms/step - ia: 0.8638 - loss: 0.0921 - mae: 0.1949 - rmse: 0.2855 - smape: 0.4601 - val_ia: 0.7801 - val_loss: 0.0621 - val_mae: 0.1354 - val_rmse: 0.2014 - val_smape: 0.3504

Epoch 15/128

958/958 - 6s - 6ms/step - ia: 0.8657 - loss: 0.0909 - mae: 0.1920 - rmse: 0.2821 - smape: 0.4546 - val_ia: 0.7728 - val_loss: 0.0614 - val_mae: 0.1375 - val_rmse: 0.2058 - val_smape: 0.3571

Epoch 16/128

958/958 - 4s - 4ms/step - ia: 0.8668 - loss: 0.0887 - mae: 0.1898 - rmse: 0.2793 - smape: 0.4499 - val_ia: 0.7479 - val_loss: 0.0623 - val_mae: 0.1456 - val_rmse: 0.2100 - val_smape: 0.3722

Epoch 17/128

958/958 - 2s - 2ms/step - ia: 0.8682 - loss: 0.0873 - mae: 0.1878 - rmse: 0.2770 - smape: 0.4485 - val_ia: 0.7723 - val_loss: 0.0608 - val_mae: 0.1366 - val_rmse: 0.2022 - val_smape: 0.3550

Epoch 18/128

958/958 - 4s - 4ms/step - ia: 0.8693 - loss: 0.0865 - mae: 0.1861 - rmse: 0.2757 - smape: 0.4451 - val_ia: 0.7737 - val_loss: 0.0588 - val_mae: 0.1343 - val_rmse: 0.1998 - val_smape: 0.3525

Epoch 19/128

958/958 - 4s - 4ms/step - ia: 0.8705 - loss: 0.0854 - mae: 0.1840 - rmse: 0.2732 - smape: 0.4433 - val_ia: 0.7768 - val_loss: 0.0590 - val_mae: 0.1339 - val_rmse: 0.1988 - val_smape: 0.3502

Epoch 20/128

958/958 - 5s - 6ms/step - ia: 0.8712 - loss: 0.0849 - mae: 0.1831 - rmse: 0.2731 - smape: 0.4399 - val_ia: 0.7564 - val_loss: 0.0594 - val_mae: 0.1397 - val_rmse: 0.2043 - val_smape: 0.3617

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.8721 - loss: 0.0835 - mae: 0.1821 - rmse: 0.2696 - smape: 0.4393 - val_ia: 0.7752 - val_loss: 0.0583 - val_mae: 0.1335 - val_rmse: 0.1983 - val_smape: 0.3521

Epoch 22/128

958/958 - 6s - 6ms/step - ia: 0.8739 - loss: 0.0822 - mae: 0.1791 - rmse: 0.2675 - smape: 0.4363 - val_ia: 0.7820 - val_loss: 0.0576 - val_mae: 0.1323 - val_rmse: 0.1975 - val_smape: 0.3524

Epoch 23/128

958/958 - 5s - 5ms/step - ia: 0.8739 - loss: 0.0817 - mae: 0.1795 - rmse: 0.2678 - smape: 0.4312 - val_ia: 0.7762 - val_loss: 0.0579 - val_mae: 0.1334 - val_rmse: 0.1981 - val_smape: 0.3540

Epoch 24/128

958/958 - 6s - 6ms/step - ia: 0.8754 - loss: 0.0806 - mae: 0.1766 - rmse: 0.2647 - smape: 0.4297 - val_ia: 0.7709 - val_loss: 0.0582 - val_mae: 0.1363 - val_rmse: 0.1994 - val_smape: 0.3581

Epoch 25/128

958/958 - 5s - 5ms/step - ia: 0.8756 - loss: 0.0801 - mae: 0.1764 - rmse: 0.2645 - smape: 0.4291 - val_ia: 0.7648 - val_loss: 0.0576 - val_mae: 0.1356 - val_rmse: 0.1999 - val_smape: 0.3548

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.8760 - loss: 0.0799 - mae: 0.1756 - rmse: 0.2630 - smape: 0.4255 - val_ia: 0.7607 - val_loss: 0.0582 - val_mae: 0.1388 - val_rmse: 0.2011 - val_smape: 0.3651

Epoch 27/128

958/958 - 4s - 4ms/step - ia: 0.8770 - loss: 0.0784 - mae: 0.1741 - rmse: 0.2609 - smape: 0.4255 - val_ia: 0.7641 - val_loss: 0.0579 - val_mae: 0.1368 - val_rmse: 0.2006 - val_smape: 0.3585

Epoch 28/128

958/958 - 5s - 6ms/step - ia: 0.8770 - loss: 0.0781 - mae: 0.1744 - rmse: 0.2605 - smape: 0.4260 - val_ia: 0.7745 - val_loss: 0.0568 - val_mae: 0.1332 - val_rmse: 0.1967 - val_smape: 0.3540

Epoch 29/128

958/958 - 5s - 5ms/step - ia: 0.8774 - loss: 0.0780 - mae: 0.1738 - rmse: 0.2610 - smape: 0.4255 - val_ia: 0.7711 - val_loss: 0.0568 - val_mae: 0.1340 - val_rmse: 0.1982 - val_smape: 0.3531

Epoch 30/128

958/958 - 3s - 4ms/step - ia: 0.8783 - loss: 0.0787 - mae: 0.1729 - rmse: 0.2610 - smape: 0.4244 - val_ia: 0.7585 - val_loss: 0.0571 - val_mae: 0.1374 - val_rmse: 0.2005 - val_smape: 0.3582

Epoch 31/128

958/958 - 5s - 5ms/step - ia: 0.8790 - loss: 0.0772 - mae: 0.1714 - rmse: 0.2585 - smape: 0.4187 - val_ia: 0.7727 - val_loss: 0.0563 - val_mae: 0.1334 - val_rmse: 0.1964 - val_smape: 0.3545

Epoch 32/128

958/958 - 4s - 4ms/step - ia: 0.8799 - loss: 0.0762 - mae: 0.1703 - rmse: 0.2571 - smape: 0.4166 - val_ia: 0.7725 - val_loss: 0.0570 - val_mae: 0.1333 - val_rmse: 0.1987 - val_smape: 0.3504

Epoch 33/128

958/958 - 4s - 4ms/step - ia: 0.8812 - loss: 0.0759 - mae: 0.1690 - rmse: 0.2562 - smape: 0.4158 - val_ia: 0.7714 - val_loss: 0.0569 - val_mae: 0.1339 - val_rmse: 0.1993 - val_smape: 0.3521

Epoch 34/128

958/958 - 4s - 4ms/step - ia: 0.8795 - loss: 0.0763 - mae: 0.1705 - rmse: 0.2575 - smape: 0.4171 - val_ia: 0.7751 - val_loss: 0.0566 - val_mae: 0.1333 - val_rmse: 0.1965 - val_smape: 0.3528

Epoch 35/128

958/958 - 3s - 4ms/step - ia: 0.8813 - loss: 0.0753 - mae: 0.1685 - rmse: 0.2552 - smape: 0.4124 - val_ia: 0.7811 - val_loss: 0.0558 - val_mae: 0.1305 - val_rmse: 0.1952 - val_smape: 0.3486

Epoch 36/128

958/958 - 6s - 6ms/step - ia: 0.8819 - loss: 0.0753 - mae: 0.1676 - rmse: 0.2546 - smape: 0.4112 - val_ia: 0.7834 - val_loss: 0.0564 - val_mae: 0.1318 - val_rmse: 0.1959 - val_smape: 0.3534

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.8817 - loss: 0.0755 - mae: 0.1678 - rmse: 0.2550 - smape: 0.4097 - val_ia: 0.7804 - val_loss: 0.0565 - val_mae: 0.1326 - val_rmse: 0.1971 - val_smape: 0.3520

Epoch 38/128

958/958 - 6s - 6ms/step - ia: 0.8824 - loss: 0.0738 - mae: 0.1666 - rmse: 0.2523 - smape: 0.4102 - val_ia: 0.7746 - val_loss: 0.0557 - val_mae: 0.1326 - val_rmse: 0.1960 - val_smape: 0.3531

Epoch 39/128

958/958 - 6s - 6ms/step - ia: 0.8824 - loss: 0.0738 - mae: 0.1666 - rmse: 0.2526 - smape: 0.4092 - val_ia: 0.7814 - val_loss: 0.0561 - val_mae: 0.1319 - val_rmse: 0.1952 - val_smape: 0.3508

Epoch 40/128

958/958 - 4s - 4ms/step - ia: 0.8828 - loss: 0.0739 - mae: 0.1665 - rmse: 0.2529 - smape: 0.4089 - val_ia: 0.7808 - val_loss: 0.0554 - val_mae: 0.1305 - val_rmse: 0.1951 - val_smape: 0.3484

Epoch 41/128

958/958 - 4s - 4ms/step - ia: 0.8839 - loss: 0.0724 - mae: 0.1645 - rmse: 0.2497 - smape: 0.4049 - val_ia: 0.7573 - val_loss: 0.0564 - val_mae: 0.1376 - val_rmse: 0.2002 - val_smape: 0.3591

Epoch 42/128

958/958 - 7s - 7ms/step - ia: 0.8845 - loss: 0.0731 - mae: 0.1639 - rmse: 0.2505 - smape: 0.4061 - val_ia: 0.7728 - val_loss: 0.0556 - val_mae: 0.1318 - val_rmse: 0.1966 - val_smape: 0.3493

Epoch 43/128

958/958 - 4s - 4ms/step - ia: 0.8843 - loss: 0.0729 - mae: 0.1642 - rmse: 0.2497 - smape: 0.4023 - val_ia: 0.7771 - val_loss: 0.0552 - val_mae: 0.1309 - val_rmse: 0.1953 - val_smape: 0.3478

Epoch 44/128

958/958 - 4s - 4ms/step - ia: 0.8855 - loss: 0.0722 - mae: 0.1628 - rmse: 0.2484 - smape: 0.4013 - val_ia: 0.7859 - val_loss: 0.0554 - val_mae: 0.1300 - val_rmse: 0.1950 - val_smape: 0.3464

Epoch 45/128

958/958 - 2s - 2ms/step - ia: 0.8854 - loss: 0.0716 - mae: 0.1624 - rmse: 0.2487 - smape: 0.4003 - val_ia: 0.7797 - val_loss: 0.0552 - val_mae: 0.1313 - val_rmse: 0.1945 - val_smape: 0.3487

Epoch 46/128

958/958 - 3s - 3ms/step - ia: 0.8863 - loss: 0.0710 - mae: 0.1616 - rmse: 0.2468 - smape: 0.4017 - val_ia: 0.7806 - val_loss: 0.0551 - val_mae: 0.1305 - val_rmse: 0.1942 - val_smape: 0.3467

Epoch 47/128

958/958 - 2s - 2ms/step - ia: 0.8866 - loss: 0.0711 - mae: 0.1613 - rmse: 0.2468 - smape: 0.3990 - val_ia: 0.7783 - val_loss: 0.0551 - val_mae: 0.1309 - val_rmse: 0.1956 - val_smape: 0.3489

Epoch 48/128

958/958 - 3s - 3ms/step - ia: 0.8864 - loss: 0.0710 - mae: 0.1617 - rmse: 0.2472 - smape: 0.4010 - val_ia: 0.7841 - val_loss: 0.0548 - val_mae: 0.1291 - val_rmse: 0.1935 - val_smape: 0.3454

Epoch 49/128

958/958 - 2s - 2ms/step - ia: 0.8857 - loss: 0.0711 - mae: 0.1620 - rmse: 0.2479 - smape: 0.4014 - val_ia: 0.7794 - val_loss: 0.0553 - val_mae: 0.1308 - val_rmse: 0.1952 - val_smape: 0.3498

Epoch 50/128

958/958 - 2s - 2ms/step - ia: 0.8867 - loss: 0.0712 - mae: 0.1607 - rmse: 0.2474 - smape: 0.3967 - val_ia: 0.7845 - val_loss: 0.0549 - val_mae: 0.1297 - val_rmse: 0.1939 - val_smape: 0.3465

Epoch 51/128

958/958 - 2s - 2ms/step - ia: 0.8868 - loss: 0.0706 - mae: 0.1603 - rmse: 0.2458 - smape: 0.3966 - val_ia: 0.7498 - val_loss: 0.0571 - val_mae: 0.1409 - val_rmse: 0.2035 - val_smape: 0.3721

Epoch 52/128

958/958 - 2s - 2ms/step - ia: 0.8869 - loss: 0.0710 - mae: 0.1605 - rmse: 0.2464 - smape: 0.3956 - val_ia: 0.7815 - val_loss: 0.0559 - val_mae: 0.1336 - val_rmse: 0.1961 - val_smape: 0.3544

Epoch 53/128

958/958 - 3s - 3ms/step - ia: 0.8876 - loss: 0.0707 - mae: 0.1600 - rmse: 0.2464 - smape: 0.3967 - val_ia: 0.7776 - val_loss: 0.0546 - val_mae: 0.1306 - val_rmse: 0.1939 - val_smape: 0.3468

Epoch 54/128

958/958 - 2s - 2ms/step - ia: 0.8879 - loss: 0.0698 - mae: 0.1596 - rmse: 0.2453 - smape: 0.3939 - val_ia: 0.7653 - val_loss: 0.0555 - val_mae: 0.1358 - val_rmse: 0.1965 - val_smape: 0.3550

Epoch 55/128

958/958 - 2s - 2ms/step - ia: 0.8874 - loss: 0.0697 - mae: 0.1597 - rmse: 0.2449 - smape: 0.3944 - val_ia: 0.7821 - val_loss: 0.0543 - val_mae: 0.1293 - val_rmse: 0.1931 - val_smape: 0.3451

Epoch 56/128

958/958 - 3s - 3ms/step - ia: 0.8883 - loss: 0.0697 - mae: 0.1585 - rmse: 0.2443 - smape: 0.3919 - val_ia: 0.7833 - val_loss: 0.0542 - val_mae: 0.1286 - val_rmse: 0.1932 - val_smape: 0.3442

Epoch 57/128

958/958 - 3s - 3ms/step - ia: 0.8886 - loss: 0.0692 - mae: 0.1585 - rmse: 0.2438 - smape: 0.3914 - val_ia: 0.7754 - val_loss: 0.0551 - val_mae: 0.1324 - val_rmse: 0.1952 - val_smape: 0.3496

Epoch 58/128

958/958 - 3s - 3ms/step - ia: 0.8883 - loss: 0.0698 - mae: 0.1582 - rmse: 0.2452 - smape: 0.3907 - val_ia: 0.7884 - val_loss: 0.0549 - val_mae: 0.1285 - val_rmse: 0.1941 - val_smape: 0.3454

Epoch 59/128

958/958 - 3s - 3ms/step - ia: 0.8892 - loss: 0.0688 - mae: 0.1574 - rmse: 0.2423 - smape: 0.3914 - val_ia: 0.7780 - val_loss: 0.0545 - val_mae: 0.1304 - val_rmse: 0.1944 - val_smape: 0.3481

Epoch 60/128

958/958 - 3s - 4ms/step - ia: 0.8896 - loss: 0.0687 - mae: 0.1573 - rmse: 0.2428 - smape: 0.3909 - val_ia: 0.7700 - val_loss: 0.0560 - val_mae: 0.1352 - val_rmse: 0.1981 - val_smape: 0.3559

Epoch 61/128

958/958 - 6s - 6ms/step - ia: 0.8895 - loss: 0.0684 - mae: 0.1571 - rmse: 0.2432 - smape: 0.3900 - val_ia: 0.7815 - val_loss: 0.0541 - val_mae: 0.1294 - val_rmse: 0.1929 - val_smape: 0.3459

Epoch 62/128

958/958 - 5s - 5ms/step - ia: 0.8894 - loss: 0.0687 - mae: 0.1574 - rmse: 0.2433 - smape: 0.3890 - val_ia: 0.7667 - val_loss: 0.0562 - val_mae: 0.1358 - val_rmse: 0.1989 - val_smape: 0.3563

Epoch 63/128

958/958 - 3s - 3ms/step - ia: 0.8893 - loss: 0.0689 - mae: 0.1571 - rmse: 0.2430 - smape: 0.3884 - val_ia: 0.7711 - val_loss: 0.0544 - val_mae: 0.1328 - val_rmse: 0.1946 - val_smape: 0.3517

Epoch 64/128

958/958 - 3s - 3ms/step - ia: 0.8899 - loss: 0.0680 - mae: 0.1564 - rmse: 0.2416 - smape: 0.3893 - val_ia: 0.7790 - val_loss: 0.0546 - val_mae: 0.1306 - val_rmse: 0.1942 - val_smape: 0.3469

Epoch 65/128

958/958 - 6s - 6ms/step - ia: 0.8901 - loss: 0.0687 - mae: 0.1569 - rmse: 0.2430 - smape: 0.3864 - val_ia: 0.7869 - val_loss: 0.0546 - val_mae: 0.1293 - val_rmse: 0.1932 - val_smape: 0.3449

Epoch 66/128

958/958 - 3s - 3ms/step - ia: 0.8895 - loss: 0.0686 - mae: 0.1571 - rmse: 0.2426 - smape: 0.3884 - val_ia: 0.7817 - val_loss: 0.0544 - val_mae: 0.1298 - val_rmse: 0.1936 - val_smape: 0.3467

Epoch 67/128

958/958 - 3s - 4ms/step - ia: 0.8895 - loss: 0.0685 - mae: 0.1569 - rmse: 0.2430 - smape: 0.3892 - val_ia: 0.7619 - val_loss: 0.0559 - val_mae: 0.1376 - val_rmse: 0.1981 - val_smape: 0.3555

Epoch 68/128

958/958 - 4s - 4ms/step - ia: 0.8900 - loss: 0.0682 - mae: 0.1561 - rmse: 0.2409 - smape: 0.3867 - val_ia: 0.7709 - val_loss: 0.0547 - val_mae: 0.1332 - val_rmse: 0.1957 - val_smape: 0.3523

Epoch 69/128

958/958 - 5s - 5ms/step - ia: 0.8899 - loss: 0.0681 - mae: 0.1559 - rmse: 0.2413 - smape: 0.3865 - val_ia: 0.7781 - val_loss: 0.0549 - val_mae: 0.1323 - val_rmse: 0.1942 - val_smape: 0.3475

Epoch 70/128

958/958 - 5s - 6ms/step - ia: 0.8905 - loss: 0.0680 - mae: 0.1560 - rmse: 0.2417 - smape: 0.3872 - val_ia: 0.7886 - val_loss: 0.0547 - val_mae: 0.1295 - val_rmse: 0.1934 - val_smape: 0.3438

Epoch 71/128

958/958 - 3s - 3ms/step - ia: 0.8906 - loss: 0.0683 - mae: 0.1558 - rmse: 0.2418 - smape: 0.3841 - val_ia: 0.7869 - val_loss: 0.0543 - val_mae: 0.1290 - val_rmse: 0.1924 - val_smape: 0.3438

Epoch 72/128

958/958 - 3s - 3ms/step - ia: 0.8902 - loss: 0.0685 - mae: 0.1560 - rmse: 0.2420 - smape: 0.3848 - val_ia: 0.7773 - val_loss: 0.0548 - val_mae: 0.1316 - val_rmse: 0.1955 - val_smape: 0.3519

Epoch 73/128

958/958 - 5s - 5ms/step - ia: 0.8907 - loss: 0.0679 - mae: 0.1555 - rmse: 0.2416 - smape: 0.3876 - val_ia: 0.7907 - val_loss: 0.0543 - val_mae: 0.1281 - val_rmse: 0.1932 - val_smape: 0.3425

Epoch 74/128

958/958 - 3s - 3ms/step - ia: 0.8904 - loss: 0.0681 - mae: 0.1561 - rmse: 0.2419 - smape: 0.3868 - val_ia: 0.7765 - val_loss: 0.0543 - val_mae: 0.1313 - val_rmse: 0.1934 - val_smape: 0.3483

Epoch 75/128

958/958 - 3s - 4ms/step - ia: 0.8906 - loss: 0.0680 - mae: 0.1559 - rmse: 0.2421 - smape: 0.3857 - val_ia: 0.7759 - val_loss: 0.0542 - val_mae: 0.1315 - val_rmse: 0.1937 - val_smape: 0.3500

Epoch 76/128

958/958 - 5s - 6ms/step - ia: 0.8911 - loss: 0.0673 - mae: 0.1546 - rmse: 0.2403 - smape: 0.3840 - val_ia: 0.7732 - val_loss: 0.0561 - val_mae: 0.1348 - val_rmse: 0.1970 - val_smape: 0.3517

Epoch 76: early stopping

Restoring model weights from the end of the best epoch: 61.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 35s 264ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 24%|██▍       | 12/50 [40:52<1:55:29, 182.34s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 11s - 46ms/step - ia: 0.6440 - loss: 0.6732 - mae: 0.5604 - rmse: 0.7679 - smape: 0.9212 - val_ia: 0.7739 - val_loss: 0.1140 - val_mae: 0.2259 - val_rmse: 0.3136 - val_smape: 0.5347

Epoch 2/16

240/240 - 2s - 8ms/step - ia: 0.7596 - loss: 0.2461 - mae: 0.3468 - rmse: 0.4906 - smape: 0.7082 - val_ia: 0.8089 - val_loss: 0.0888 - val_mae: 0.1929 - val_rmse: 0.2759 - val_smape: 0.4721

Epoch 3/16

240/240 - 1s - 4ms/step - ia: 0.7963 - loss: 0.1821 - mae: 0.2935 - rmse: 0.4216 - smape: 0.6225 - val_ia: 0.8228 - val_loss: 0.0783 - val_mae: 0.1780 - val_rmse: 0.2570 - val_smape: 0.4338

Epoch 4/16

240/240 - 1s - 4ms/step - ia: 0.8161 - loss: 0.1526 - mae: 0.2647 - rmse: 0.3851 - smape: 0.5759 - val_ia: 0.8443 - val_loss: 0.0683 - val_mae: 0.1588 - val_rmse: 0.2408 - val_smape: 0.4071

Epoch 5/16

240/240 - 1s - 5ms/step - ia: 0.8297 - loss: 0.1341 - mae: 0.2452 - rmse: 0.3611 - smape: 0.5408 - val_ia: 0.8340 - val_loss: 0.0701 - val_mae: 0.1647 - val_rmse: 0.2446 - val_smape: 0.4135

Epoch 6/16

240/240 - 2s - 7ms/step - ia: 0.8390 - loss: 0.1253 - mae: 0.2315 - rmse: 0.3467 - smape: 0.5161 - val_ia: 0.8534 - val_loss: 0.0623 - val_mae: 0.1485 - val_rmse: 0.2288 - val_smape: 0.3846

Epoch 7/16

240/240 - 2s - 8ms/step - ia: 0.8459 - loss: 0.1148 - mae: 0.2221 - rmse: 0.3330 - smape: 0.4972 - val_ia: 0.8611 - val_loss: 0.0612 - val_mae: 0.1442 - val_rmse: 0.2263 - val_smape: 0.3731

Epoch 8/16

240/240 - 1s - 5ms/step - ia: 0.8513 - loss: 0.1108 - mae: 0.2147 - rmse: 0.3263 - smape: 0.4791 - val_ia: 0.8534 - val_loss: 0.0622 - val_mae: 0.1483 - val_rmse: 0.2281 - val_smape: 0.3822

Epoch 9/16

240/240 - 1s - 6ms/step - ia: 0.8537 - loss: 0.1071 - mae: 0.2106 - rmse: 0.3210 - smape: 0.4725 - val_ia: 0.8642 - val_loss: 0.0586 - val_mae: 0.1386 - val_rmse: 0.2207 - val_smape: 0.3632

Epoch 10/16

240/240 - 1s - 4ms/step - ia: 0.8580 - loss: 0.1000 - mae: 0.2051 - rmse: 0.3106 - smape: 0.4634 - val_ia: 0.8562 - val_loss: 0.0601 - val_mae: 0.1462 - val_rmse: 0.2238 - val_smape: 0.3773

Epoch 11/16

240/240 - 1s - 4ms/step - ia: 0.8602 - loss: 0.1000 - mae: 0.2022 - rmse: 0.3098 - smape: 0.4554 - val_ia: 0.8598 - val_loss: 0.0600 - val_mae: 0.1434 - val_rmse: 0.2233 - val_smape: 0.3700

Epoch 12/16

240/240 - 1s - 6ms/step - ia: 0.8624 - loss: 0.0967 - mae: 0.1989 - rmse: 0.3056 - smape: 0.4491 - val_ia: 0.8651 - val_loss: 0.0591 - val_mae: 0.1394 - val_rmse: 0.2208 - val_smape: 0.3631

Epoch 13/16

240/240 - 2s - 7ms/step - ia: 0.8635 - loss: 0.0960 - mae: 0.1976 - rmse: 0.3045 - smape: 0.4432 - val_ia: 0.8606 - val_loss: 0.0590 - val_mae: 0.1419 - val_rmse: 0.2207 - val_smape: 0.3660

Epoch 14/16

240/240 - 1s - 5ms/step - ia: 0.8655 - loss: 0.0937 - mae: 0.1944 - rmse: 0.2990 - smape: 0.4394 - val_ia: 0.8507 - val_loss: 0.0624 - val_mae: 0.1516 - val_rmse: 0.2278 - val_smape: 0.3854

Epoch 15/16

240/240 - 1s - 5ms/step - ia: 0.8671 - loss: 0.0929 - mae: 0.1924 - rmse: 0.2990 - smape: 0.4334 - val_ia: 0.8627 - val_loss: 0.0585 - val_mae: 0.1395 - val_rmse: 0.2209 - val_smape: 0.3682

Epoch 16/16

240/240 - 1s - 6ms/step - ia: 0.8673 - loss: 0.0920 - mae: 0.1922 - rmse: 0.2962 - smape: 0.4333 - val_ia: 0.8475 - val_loss: 0.0615 - val_mae: 0.1504 - val_rmse: 0.2273 - val_smape: 0.3838

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 35s 260ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 26%|██▌       | 13/50 [41:25<1:24:34, 137.16s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 9s - 37ms/step - ia: 0.3010 - loss: 2.9444 - mae: 1.2638 - rmse: 1.6845 - smape: 1.4141 - val_ia: 0.4404 - val_loss: 0.7900 - val_mae: 0.6539 - val_rmse: 0.8391 - val_smape: 1.1397

Epoch 2/8

240/240 - 2s - 7ms/step - ia: 0.4504 - loss: 1.5310 - mae: 0.9249 - rmse: 1.2301 - smape: 1.2179 - val_ia: 0.5584 - val_loss: 0.4408 - val_mae: 0.4706 - val_rmse: 0.6234 - val_smape: 0.9232

Epoch 3/8

240/240 - 2s - 6ms/step - ia: 0.5214 - loss: 1.0942 - mae: 0.7720 - rmse: 1.0390 - smape: 1.1180 - val_ia: 0.6334 - val_loss: 0.2977 - val_mae: 0.3779 - val_rmse: 0.5103 - val_smape: 0.8002

Epoch 4/8

240/240 - 1s - 6ms/step - ia: 0.5686 - loss: 0.8334 - mae: 0.6766 - rmse: 0.9078 - smape: 1.0521 - val_ia: 0.6811 - val_loss: 0.2251 - val_mae: 0.3254 - val_rmse: 0.4432 - val_smape: 0.7252

Epoch 5/8

240/240 - 1s - 6ms/step - ia: 0.6052 - loss: 0.6832 - mae: 0.6097 - rmse: 0.8218 - smape: 0.9961 - val_ia: 0.7193 - val_loss: 0.1771 - val_mae: 0.2821 - val_rmse: 0.3908 - val_smape: 0.6408

Epoch 6/8

240/240 - 1s - 5ms/step - ia: 0.6361 - loss: 0.5663 - mae: 0.5545 - rmse: 0.7477 - smape: 0.9453 - val_ia: 0.7496 - val_loss: 0.1489 - val_mae: 0.2546 - val_rmse: 0.3587 - val_smape: 0.5883

Epoch 7/8

240/240 - 1s - 5ms/step - ia: 0.6576 - loss: 0.5043 - mae: 0.5201 - rmse: 0.7059 - smape: 0.9090 - val_ia: 0.7576 - val_loss: 0.1364 - val_mae: 0.2440 - val_rmse: 0.3434 - val_smape: 0.5756

Epoch 8/8

240/240 - 1s - 5ms/step - ia: 0.6778 - loss: 0.4402 - mae: 0.4868 - rmse: 0.6594 - smape: 0.8711 - val_ia: 0.7773 - val_loss: 0.1196 - val_mae: 0.2255 - val_rmse: 0.3209 - val_smape: 0.5400

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 15s 115ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 28%|██▊       | 14/50 [41:45<1:01:04, 101.80s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 11s - 22ms/step - ia: 0.7675 - loss: 0.2696 - mae: 0.3469 - rmse: 0.4804 - smape: 0.6622 - val_ia: 0.8109 - val_loss: 0.0880 - val_mae: 0.1643 - val_rmse: 0.2448 - val_smape: 0.3875

Epoch 2/16

479/479 - 2s - 5ms/step - ia: 0.8240 - loss: 0.1473 - mae: 0.2552 - rmse: 0.3710 - smape: 0.5342 - val_ia: 0.8197 - val_loss: 0.0776 - val_mae: 0.1543 - val_rmse: 0.2305 - val_smape: 0.3645

Epoch 3/16

479/479 - 3s - 7ms/step - ia: 0.8267 - loss: 0.1412 - mae: 0.2515 - rmse: 0.3647 - smape: 0.5319 - val_ia: 0.7727 - val_loss: 0.0896 - val_mae: 0.1804 - val_rmse: 0.2533 - val_smape: 0.4443

Epoch 4/16

479/479 - 3s - 5ms/step - ia: 0.8285 - loss: 0.1369 - mae: 0.2486 - rmse: 0.3599 - smape: 0.5279 - val_ia: 0.8128 - val_loss: 0.0797 - val_mae: 0.1574 - val_rmse: 0.2330 - val_smape: 0.3787

Epoch 5/16

479/479 - 2s - 5ms/step - ia: 0.8285 - loss: 0.1372 - mae: 0.2488 - rmse: 0.3600 - smape: 0.5292 - val_ia: 0.8123 - val_loss: 0.0809 - val_mae: 0.1623 - val_rmse: 0.2367 - val_smape: 0.3807

Epoch 6/16

479/479 - 3s - 6ms/step - ia: 0.8294 - loss: 0.1373 - mae: 0.2474 - rmse: 0.3589 - smape: 0.5291 - val_ia: 0.7562 - val_loss: 0.0961 - val_mae: 0.1931 - val_rmse: 0.2644 - val_smape: 0.4627

Epoch 7/16

479/479 - 2s - 4ms/step - ia: 0.8266 - loss: 0.1398 - mae: 0.2516 - rmse: 0.3627 - smape: 0.5368 - val_ia: 0.8028 - val_loss: 0.0795 - val_mae: 0.1629 - val_rmse: 0.2360 - val_smape: 0.3947

Epoch 8/16

479/479 - 2s - 4ms/step - ia: 0.8272 - loss: 0.1384 - mae: 0.2507 - rmse: 0.3611 - smape: 0.5348 - val_ia: 0.7895 - val_loss: 0.0885 - val_mae: 0.1748 - val_rmse: 0.2481 - val_smape: 0.4205

Epoch 9/16

479/479 - 3s - 7ms/step - ia: 0.8271 - loss: 0.1370 - mae: 0.2496 - rmse: 0.3593 - smape: 0.5322 - val_ia: 0.7908 - val_loss: 0.0902 - val_mae: 0.1699 - val_rmse: 0.2437 - val_smape: 0.3946

Epoch 10/16

479/479 - 3s - 5ms/step - ia: 0.8255 - loss: 0.1418 - mae: 0.2534 - rmse: 0.3656 - smape: 0.5368 - val_ia: 0.7985 - val_loss: 0.0857 - val_mae: 0.1654 - val_rmse: 0.2407 - val_smape: 0.4005

Epoch 11/16

479/479 - 1s - 3ms/step - ia: 0.8277 - loss: 0.1384 - mae: 0.2503 - rmse: 0.3610 - smape: 0.5300 - val_ia: 0.8125 - val_loss: 0.0748 - val_mae: 0.1538 - val_rmse: 0.2288 - val_smape: 0.3738

Epoch 12/16

479/479 - 3s - 6ms/step - ia: 0.8267 - loss: 0.1394 - mae: 0.2510 - rmse: 0.3625 - smape: 0.5351 - val_ia: 0.8229 - val_loss: 0.0777 - val_mae: 0.1506 - val_rmse: 0.2257 - val_smape: 0.3634

Epoch 13/16

479/479 - 2s - 3ms/step - ia: 0.8286 - loss: 0.1377 - mae: 0.2487 - rmse: 0.3605 - smape: 0.5302 - val_ia: 0.7750 - val_loss: 0.0877 - val_mae: 0.1768 - val_rmse: 0.2476 - val_smape: 0.4064

Epoch 14/16

479/479 - 2s - 4ms/step - ia: 0.8280 - loss: 0.1371 - mae: 0.2491 - rmse: 0.3588 - smape: 0.5303 - val_ia: 0.8100 - val_loss: 0.0822 - val_mae: 0.1581 - val_rmse: 0.2336 - val_smape: 0.3797

Epoch 15/16

479/479 - 3s - 5ms/step - ia: 0.8275 - loss: 0.1361 - mae: 0.2504 - rmse: 0.3588 - smape: 0.5325 - val_ia: 0.7763 - val_loss: 0.0855 - val_mae: 0.1762 - val_rmse: 0.2473 - val_smape: 0.4160

Epoch 16/16

479/479 - 2s - 4ms/step - ia: 0.8277 - loss: 0.1373 - mae: 0.2497 - rmse: 0.3596 - smape: 0.5321 - val_ia: 0.8150 - val_loss: 0.0786 - val_mae: 0.1535 - val_rmse: 0.2274 - val_smape: 0.3715

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 22s 166ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 30%|███       | 15/50 [42:34<50:03, 85.82s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3832/3832 - 20s - 5ms/step - ia: 0.7490 - loss: 0.2063 - mae: 0.3061 - rmse: 0.4022 - smape: 0.6292 - val_ia: 0.5263 - val_loss: 0.0620 - val_mae: 0.1478 - val_rmse: 0.1899 - val_smape: 0.3880

Epoch 2/256

3832/3832 - 12s - 3ms/step - ia: 0.7653 - loss: 0.1841 - mae: 0.2878 - rmse: 0.3817 - smape: 0.5921 - val_ia: 0.5377 - val_loss: 0.0659 - val_mae: 0.1514 - val_rmse: 0.1956 - val_smape: 0.3820

Epoch 3/256

3832/3832 - 20s - 5ms/step - ia: 0.7626 - loss: 0.1855 - mae: 0.2894 - rmse: 0.3825 - smape: 0.5947 - val_ia: 0.4423 - val_loss: 0.0907 - val_mae: 0.2050 - val_rmse: 0.2400 - val_smape: 0.4621

Epoch 4/256

3832/3832 - 21s - 6ms/step - ia: 0.7677 - loss: 0.1763 - mae: 0.2813 - rmse: 0.3731 - smape: 0.5809 - val_ia: 0.3692 - val_loss: 0.1430 - val_mae: 0.2797 - val_rmse: 0.3126 - val_smape: 0.6004

Epoch 5/256

3832/3832 - 19s - 5ms/step - ia: 0.7605 - loss: 0.1875 - mae: 0.2905 - rmse: 0.3837 - smape: 0.5985 - val_ia: 0.4903 - val_loss: 0.0776 - val_mae: 0.1782 - val_rmse: 0.2246 - val_smape: 0.4487

Epoch 6/256

3832/3832 - 22s - 6ms/step - ia: 0.7624 - loss: 0.1856 - mae: 0.2869 - rmse: 0.3812 - smape: 0.5921 - val_ia: 0.5295 - val_loss: 0.0623 - val_mae: 0.1495 - val_rmse: 0.1923 - val_smape: 0.3893

Epoch 7/256

3832/3832 - 20s - 5ms/step - ia: 0.7638 - loss: 0.1854 - mae: 0.2878 - rmse: 0.3813 - smape: 0.5930 - val_ia: 0.5119 - val_loss: 0.0712 - val_mae: 0.1619 - val_rmse: 0.2055 - val_smape: 0.4017

Epoch 8/256

3832/3832 - 19s - 5ms/step - ia: 0.7696 - loss: 0.1774 - mae: 0.2821 - rmse: 0.3749 - smape: 0.5760 - val_ia: 0.1931 - val_loss: 0.9114 - val_mae: 0.7139 - val_rmse: 0.7503 - val_smape: 1.8210

Epoch 9/256

3832/3832 - 12s - 3ms/step - ia: 0.7638 - loss: 0.1842 - mae: 0.2861 - rmse: 0.3794 - smape: 0.5896 - val_ia: 0.5259 - val_loss: 0.0620 - val_mae: 0.1503 - val_rmse: 0.1925 - val_smape: 0.3928

Epoch 10/256

3832/3832 - 22s - 6ms/step - ia: 0.7605 - loss: 0.1902 - mae: 0.2898 - rmse: 0.3847 - smape: 0.5945 - val_ia: 0.3978 - val_loss: 0.1250 - val_mae: 0.2660 - val_rmse: 0.3031 - val_smape: 0.6295

Epoch 11/256

3832/3832 - 21s - 5ms/step - ia: 0.7679 - loss: 0.1754 - mae: 0.2805 - rmse: 0.3714 - smape: 0.5796 - val_ia: 0.4639 - val_loss: 0.0833 - val_mae: 0.1894 - val_rmse: 0.2258 - val_smape: 0.4345

Epoch 12/256

3832/3832 - 11s - 3ms/step - ia: 0.7676 - loss: 0.1774 - mae: 0.2825 - rmse: 0.3747 - smape: 0.5789 - val_ia: 0.5296 - val_loss: 0.0622 - val_mae: 0.1491 - val_rmse: 0.1907 - val_smape: 0.3791

Epoch 13/256

3832/3832 - 20s - 5ms/step - ia: 0.7614 - loss: 0.1895 - mae: 0.2900 - rmse: 0.3840 - smape: 0.5928 - val_ia: 0.4941 - val_loss: 0.0750 - val_mae: 0.1753 - val_rmse: 0.2193 - val_smape: 0.4406

Epoch 14/256

3832/3832 - 11s - 3ms/step - ia: 0.7662 - loss: 0.1794 - mae: 0.2848 - rmse: 0.3766 - smape: 0.5834 - val_ia: 0.4514 - val_loss: 0.0825 - val_mae: 0.1971 - val_rmse: 0.2374 - val_smape: 0.4931

Epoch 15/256

3832/3832 - 13s - 3ms/step - ia: 0.7658 - loss: 0.1798 - mae: 0.2823 - rmse: 0.3747 - smape: 0.5865 - val_ia: 0.5401 - val_loss: 0.0606 - val_mae: 0.1473 - val_rmse: 0.1886 - val_smape: 0.3778

Epoch 16/256

3832/3832 - 14s - 4ms/step - ia: 0.7700 - loss: 0.1768 - mae: 0.2810 - rmse: 0.3735 - smape: 0.5731 - val_ia: 0.3599 - val_loss: 0.1741 - val_mae: 0.3097 - val_rmse: 0.3424 - val_smape: 0.6902

Epoch 17/256

3832/3832 - 12s - 3ms/step - ia: 0.7679 - loss: 0.1773 - mae: 0.2812 - rmse: 0.3724 - smape: 0.5769 - val_ia: 0.4824 - val_loss: 0.0727 - val_mae: 0.1752 - val_rmse: 0.2153 - val_smape: 0.4355

Epoch 18/256

3832/3832 - 22s - 6ms/step - ia: 0.7713 - loss: 0.1728 - mae: 0.2793 - rmse: 0.3715 - smape: 0.5733 - val_ia: 0.4916 - val_loss: 0.0818 - val_mae: 0.1876 - val_rmse: 0.2280 - val_smape: 0.4694

Epoch 19/256

3832/3832 - 12s - 3ms/step - ia: 0.7662 - loss: 0.1761 - mae: 0.2836 - rmse: 0.3759 - smape: 0.5838 - val_ia: 0.4524 - val_loss: 0.0889 - val_mae: 0.1993 - val_rmse: 0.2358 - val_smape: 0.4566

Epoch 20/256

3832/3832 - 22s - 6ms/step - ia: 0.7671 - loss: 0.1755 - mae: 0.2812 - rmse: 0.3731 - smape: 0.5796 - val_ia: 0.4599 - val_loss: 0.0862 - val_mae: 0.2006 - val_rmse: 0.2440 - val_smape: 0.4637

Epoch 21/256

3832/3832 - 21s - 6ms/step - ia: 0.7694 - loss: 0.1775 - mae: 0.2805 - rmse: 0.3724 - smape: 0.5770 - val_ia: 0.4912 - val_loss: 0.0686 - val_mae: 0.1665 - val_rmse: 0.2064 - val_smape: 0.4372

Epoch 22/256

3832/3832 - 19s - 5ms/step - ia: 0.7618 - loss: 0.1859 - mae: 0.2894 - rmse: 0.3826 - smape: 0.5897 - val_ia: 0.4985 - val_loss: 0.0682 - val_mae: 0.1670 - val_rmse: 0.2085 - val_smape: 0.4215

Epoch 23/256

3832/3832 - 22s - 6ms/step - ia: 0.7654 - loss: 0.1811 - mae: 0.2832 - rmse: 0.3753 - smape: 0.5843 - val_ia: 0.4351 - val_loss: 0.0914 - val_mae: 0.2138 - val_rmse: 0.2525 - val_smape: 0.5161

Epoch 24/256

3832/3832 - 21s - 6ms/step - ia: 0.7624 - loss: 0.1877 - mae: 0.2891 - rmse: 0.3838 - smape: 0.5905 - val_ia: 0.4170 - val_loss: 0.1176 - val_mae: 0.2391 - val_rmse: 0.2739 - val_smape: 0.5203

Epoch 25/256

3832/3832 - 20s - 5ms/step - ia: 0.7665 - loss: 0.1809 - mae: 0.2839 - rmse: 0.3769 - smape: 0.5846 - val_ia: 0.4527 - val_loss: 0.0859 - val_mae: 0.1986 - val_rmse: 0.2370 - val_smape: 0.4742

Epoch 26/256

3832/3832 - 13s - 3ms/step - ia: 0.7607 - loss: 0.1914 - mae: 0.2908 - rmse: 0.3864 - smape: 0.5962 - val_ia: 0.4932 - val_loss: 0.0737 - val_mae: 0.1736 - val_rmse: 0.2136 - val_smape: 0.4168

Epoch 27/256

3832/3832 - 22s - 6ms/step - ia: 0.7697 - loss: 0.1785 - mae: 0.2809 - rmse: 0.3747 - smape: 0.5749 - val_ia: 0.4111 - val_loss: 0.1183 - val_mae: 0.2359 - val_rmse: 0.2711 - val_smape: 0.5122

Epoch 28/256

3832/3832 - 20s - 5ms/step - ia: 0.7644 - loss: 0.1865 - mae: 0.2877 - rmse: 0.3820 - smape: 0.5894 - val_ia: 0.4648 - val_loss: 0.0797 - val_mae: 0.1908 - val_rmse: 0.2286 - val_smape: 0.4607

Epoch 29/256

3832/3832 - 13s - 3ms/step - ia: 0.7626 - loss: 0.1857 - mae: 0.2878 - rmse: 0.3817 - smape: 0.5949 - val_ia: 0.4192 - val_loss: 0.1178 - val_mae: 0.2367 - val_rmse: 0.2698 - val_smape: 0.5067

Epoch 30/256

3832/3832 - 9s - 2ms/step - ia: 0.7661 - loss: 0.1806 - mae: 0.2845 - rmse: 0.3780 - smape: 0.5834 - val_ia: 0.5276 - val_loss: 0.0627 - val_mae: 0.1514 - val_rmse: 0.1935 - val_smape: 0.3926

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 19s 148ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 32%|███▏      | 16/50 [51:22<2:04:05, 218.97s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3832/3832 - 23s - 6ms/step - ia: 0.7746 - loss: 0.1736 - mae: 0.2735 - rmse: 0.3621 - smape: 0.5898 - val_ia: 0.5017 - val_loss: 0.0785 - val_mae: 0.1657 - val_rmse: 0.2069 - val_smape: 0.4044

Epoch 2/256

3832/3832 - 13s - 3ms/step - ia: 0.8279 - loss: 0.1096 - mae: 0.2130 - rmse: 0.2882 - smape: 0.4891 - val_ia: 0.4983 - val_loss: 0.0648 - val_mae: 0.1627 - val_rmse: 0.2005 - val_smape: 0.4103

Epoch 3/256

3832/3832 - 12s - 3ms/step - ia: 0.8386 - loss: 0.0993 - mae: 0.2010 - rmse: 0.2740 - smape: 0.4650 - val_ia: 0.5266 - val_loss: 0.0596 - val_mae: 0.1478 - val_rmse: 0.1868 - val_smape: 0.3809

Epoch 4/256

3832/3832 - 14s - 4ms/step - ia: 0.8432 - loss: 0.0947 - mae: 0.1959 - rmse: 0.2669 - smape: 0.4499 - val_ia: 0.4991 - val_loss: 0.0658 - val_mae: 0.1625 - val_rmse: 0.2002 - val_smape: 0.3986

Epoch 5/256

3832/3832 - 14s - 4ms/step - ia: 0.8478 - loss: 0.0929 - mae: 0.1919 - rmse: 0.2626 - smape: 0.4408 - val_ia: 0.5485 - val_loss: 0.0604 - val_mae: 0.1416 - val_rmse: 0.1818 - val_smape: 0.3574

Epoch 6/256

3832/3832 - 10s - 3ms/step - ia: 0.8476 - loss: 0.0917 - mae: 0.1901 - rmse: 0.2602 - smape: 0.4369 - val_ia: 0.5165 - val_loss: 0.0729 - val_mae: 0.1627 - val_rmse: 0.2035 - val_smape: 0.3832

Epoch 7/256

3832/3832 - 15s - 4ms/step - ia: 0.8467 - loss: 0.0923 - mae: 0.1914 - rmse: 0.2617 - smape: 0.4376 - val_ia: 0.5123 - val_loss: 0.0659 - val_mae: 0.1591 - val_rmse: 0.2005 - val_smape: 0.3857

Epoch 8/256

3832/3832 - 15s - 4ms/step - ia: 0.8488 - loss: 0.0894 - mae: 0.1901 - rmse: 0.2594 - smape: 0.4354 - val_ia: 0.5376 - val_loss: 0.0728 - val_mae: 0.1537 - val_rmse: 0.1941 - val_smape: 0.3690

Epoch 9/256

3832/3832 - 21s - 5ms/step - ia: 0.8478 - loss: 0.0915 - mae: 0.1900 - rmse: 0.2610 - smape: 0.4315 - val_ia: 0.5489 - val_loss: 0.0638 - val_mae: 0.1414 - val_rmse: 0.1813 - val_smape: 0.3572

Epoch 10/256

3832/3832 - 17s - 4ms/step - ia: 0.8495 - loss: 0.0894 - mae: 0.1882 - rmse: 0.2581 - smape: 0.4306 - val_ia: 0.5150 - val_loss: 0.0650 - val_mae: 0.1558 - val_rmse: 0.1967 - val_smape: 0.3913

Epoch 11/256

3832/3832 - 11s - 3ms/step - ia: 0.8512 - loss: 0.0863 - mae: 0.1865 - rmse: 0.2545 - smape: 0.4280 - val_ia: 0.5563 - val_loss: 0.0684 - val_mae: 0.1416 - val_rmse: 0.1817 - val_smape: 0.3501

Epoch 12/256

3832/3832 - 13s - 3ms/step - ia: 0.8505 - loss: 0.0860 - mae: 0.1867 - rmse: 0.2549 - smape: 0.4289 - val_ia: 0.5081 - val_loss: 0.0716 - val_mae: 0.1623 - val_rmse: 0.2014 - val_smape: 0.4008

Epoch 13/256

3832/3832 - 12s - 3ms/step - ia: 0.8500 - loss: 0.0847 - mae: 0.1861 - rmse: 0.2542 - smape: 0.4296 - val_ia: 0.5557 - val_loss: 0.0648 - val_mae: 0.1422 - val_rmse: 0.1827 - val_smape: 0.3605

Epoch 14/256

3832/3832 - 12s - 3ms/step - ia: 0.8498 - loss: 0.0861 - mae: 0.1854 - rmse: 0.2540 - smape: 0.4274 - val_ia: 0.5609 - val_loss: 0.0553 - val_mae: 0.1351 - val_rmse: 0.1756 - val_smape: 0.3490

Epoch 15/256

3832/3832 - 24s - 6ms/step - ia: 0.8510 - loss: 0.0865 - mae: 0.1868 - rmse: 0.2547 - smape: 0.4274 - val_ia: 0.5471 - val_loss: 0.0569 - val_mae: 0.1384 - val_rmse: 0.1784 - val_smape: 0.3602

Epoch 16/256

3832/3832 - 37s - 10ms/step - ia: 0.8497 - loss: 0.0852 - mae: 0.1864 - rmse: 0.2541 - smape: 0.4310 - val_ia: 0.5552 - val_loss: 0.0563 - val_mae: 0.1373 - val_rmse: 0.1777 - val_smape: 0.3554

Epoch 17/256

3832/3832 - 14s - 4ms/step - ia: 0.8518 - loss: 0.0851 - mae: 0.1859 - rmse: 0.2532 - smape: 0.4281 - val_ia: 0.5254 - val_loss: 0.0625 - val_mae: 0.1493 - val_rmse: 0.1911 - val_smape: 0.4064

Epoch 18/256

3832/3832 - 16s - 4ms/step - ia: 0.8520 - loss: 0.0842 - mae: 0.1848 - rmse: 0.2524 - smape: 0.4270 - val_ia: 0.5129 - val_loss: 0.0629 - val_mae: 0.1575 - val_rmse: 0.1973 - val_smape: 0.3825

Epoch 19/256

3832/3832 - 9s - 2ms/step - ia: 0.8538 - loss: 0.0819 - mae: 0.1832 - rmse: 0.2499 - smape: 0.4268 - val_ia: 0.5539 - val_loss: 0.0722 - val_mae: 0.1482 - val_rmse: 0.1880 - val_smape: 0.3599

Epoch 20/256

3832/3832 - 12s - 3ms/step - ia: 0.8518 - loss: 0.0836 - mae: 0.1845 - rmse: 0.2517 - smape: 0.4261 - val_ia: 0.5462 - val_loss: 0.0614 - val_mae: 0.1453 - val_rmse: 0.1851 - val_smape: 0.3623

Epoch 21/256

3832/3832 - 16s - 4ms/step - ia: 0.8528 - loss: 0.0858 - mae: 0.1852 - rmse: 0.2539 - smape: 0.4274 - val_ia: 0.5359 - val_loss: 0.0587 - val_mae: 0.1445 - val_rmse: 0.1835 - val_smape: 0.3625

Epoch 22/256

3832/3832 - 10s - 3ms/step - ia: 0.8522 - loss: 0.0837 - mae: 0.1849 - rmse: 0.2524 - smape: 0.4269 - val_ia: 0.5451 - val_loss: 0.0622 - val_mae: 0.1443 - val_rmse: 0.1846 - val_smape: 0.3683

Epoch 23/256

3832/3832 - 11s - 3ms/step - ia: 0.8525 - loss: 0.0819 - mae: 0.1839 - rmse: 0.2508 - smape: 0.4272 - val_ia: 0.5442 - val_loss: 0.0640 - val_mae: 0.1465 - val_rmse: 0.1892 - val_smape: 0.3765

Epoch 24/256

3832/3832 - 14s - 4ms/step - ia: 0.8542 - loss: 0.0830 - mae: 0.1838 - rmse: 0.2516 - smape: 0.4255 - val_ia: 0.5262 - val_loss: 0.0609 - val_mae: 0.1510 - val_rmse: 0.1895 - val_smape: 0.3682

Epoch 25/256

3832/3832 - 19s - 5ms/step - ia: 0.8531 - loss: 0.0829 - mae: 0.1833 - rmse: 0.2501 - smape: 0.4260 - val_ia: 0.5486 - val_loss: 0.0673 - val_mae: 0.1493 - val_rmse: 0.1884 - val_smape: 0.3700

Epoch 26/256

3832/3832 - 33s - 8ms/step - ia: 0.8551 - loss: 0.0800 - mae: 0.1816 - rmse: 0.2478 - smape: 0.4216 - val_ia: 0.5341 - val_loss: 0.0705 - val_mae: 0.1551 - val_rmse: 0.1937 - val_smape: 0.3740

Epoch 27/256

3832/3832 - 32s - 8ms/step - ia: 0.8542 - loss: 0.0821 - mae: 0.1828 - rmse: 0.2501 - smape: 0.4236 - val_ia: 0.4811 - val_loss: 0.0681 - val_mae: 0.1753 - val_rmse: 0.2133 - val_smape: 0.4257

Epoch 28/256

3832/3832 - 11s - 3ms/step - ia: 0.8543 - loss: 0.0814 - mae: 0.1821 - rmse: 0.2485 - smape: 0.4215 - val_ia: 0.5607 - val_loss: 0.0593 - val_mae: 0.1388 - val_rmse: 0.1796 - val_smape: 0.3641

Epoch 29/256

3832/3832 - 16s - 4ms/step - ia: 0.8539 - loss: 0.0826 - mae: 0.1819 - rmse: 0.2493 - smape: 0.4240 - val_ia: 0.5481 - val_loss: 0.0603 - val_mae: 0.1420 - val_rmse: 0.1838 - val_smape: 0.3605

Epoch 29: early stopping

Restoring model weights from the end of the best epoch: 14.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:31 681ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 34%|███▍      | 17/50 [59:18<2:42:56, 296.26s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 7s - 27ms/step - ia: 0.2488 - loss: 2.4415 - mae: 1.2237 - rmse: 1.5576 - smape: 1.4898 - val_ia: 0.2426 - val_loss: 1.3031 - val_mae: 0.8554 - val_rmse: 1.0337 - val_smape: 1.5151

Epoch 2/16

240/240 - 2s - 7ms/step - ia: 0.2628 - loss: 2.3223 - mae: 1.1860 - rmse: 1.5200 - smape: 1.4685 - val_ia: 0.2575 - val_loss: 1.2239 - val_mae: 0.8260 - val_rmse: 1.0009 - val_smape: 1.5074

Epoch 3/16

240/240 - 1s - 5ms/step - ia: 0.2732 - loss: 2.2353 - mae: 1.1632 - rmse: 1.4915 - smape: 1.4557 - val_ia: 0.2728 - val_loss: 1.1520 - val_mae: 0.7987 - val_rmse: 0.9704 - val_smape: 1.4932

Epoch 4/16

240/240 - 2s - 6ms/step - ia: 0.2830 - loss: 2.1839 - mae: 1.1482 - rmse: 1.4736 - smape: 1.4394 - val_ia: 0.2887 - val_loss: 1.0863 - val_mae: 0.7730 - val_rmse: 0.9419 - val_smape: 1.4719

Epoch 5/16

240/240 - 2s - 6ms/step - ia: 0.2949 - loss: 2.0781 - mae: 1.1199 - rmse: 1.4374 - smape: 1.4251 - val_ia: 0.3049 - val_loss: 1.0255 - val_mae: 0.7485 - val_rmse: 0.9148 - val_smape: 1.4394

Epoch 6/16

240/240 - 2s - 8ms/step - ia: 0.2983 - loss: 2.0583 - mae: 1.1149 - rmse: 1.4304 - smape: 1.4209 - val_ia: 0.3214 - val_loss: 0.9702 - val_mae: 0.7257 - val_rmse: 0.8897 - val_smape: 1.4034

Epoch 7/16

240/240 - 2s - 9ms/step - ia: 0.3109 - loss: 2.0001 - mae: 1.0943 - rmse: 1.4101 - smape: 1.4035 - val_ia: 0.3382 - val_loss: 0.9191 - val_mae: 0.7039 - val_rmse: 0.8658 - val_smape: 1.3677

Epoch 8/16

240/240 - 1s - 5ms/step - ia: 0.3182 - loss: 1.9404 - mae: 1.0794 - rmse: 1.3880 - smape: 1.3956 - val_ia: 0.3552 - val_loss: 0.8717 - val_mae: 0.6832 - val_rmse: 0.8431 - val_smape: 1.3319

Epoch 9/16

240/240 - 1s - 3ms/step - ia: 0.3269 - loss: 1.8849 - mae: 1.0653 - rmse: 1.3684 - smape: 1.3855 - val_ia: 0.3722 - val_loss: 0.8281 - val_mae: 0.6635 - val_rmse: 0.8217 - val_smape: 1.2973

Epoch 10/16

240/240 - 1s - 3ms/step - ia: 0.3324 - loss: 1.8509 - mae: 1.0581 - rmse: 1.3568 - smape: 1.3795 - val_ia: 0.3889 - val_loss: 0.7877 - val_mae: 0.6448 - val_rmse: 0.8014 - val_smape: 1.2644

Epoch 11/16

240/240 - 1s - 3ms/step - ia: 0.3432 - loss: 1.7949 - mae: 1.0399 - rmse: 1.3360 - smape: 1.3607 - val_ia: 0.4053 - val_loss: 0.7507 - val_mae: 0.6271 - val_rmse: 0.7824 - val_smape: 1.2321

Epoch 12/16

240/240 - 1s - 6ms/step - ia: 0.3472 - loss: 1.7549 - mae: 1.0303 - rmse: 1.3208 - smape: 1.3624 - val_ia: 0.4212 - val_loss: 0.7152 - val_mae: 0.6097 - val_rmse: 0.7637 - val_smape: 1.2004

Epoch 13/16

240/240 - 1s - 5ms/step - ia: 0.3578 - loss: 1.7180 - mae: 1.0185 - rmse: 1.3075 - smape: 1.3477 - val_ia: 0.4363 - val_loss: 0.6824 - val_mae: 0.5934 - val_rmse: 0.7460 - val_smape: 1.1700

Epoch 14/16

240/240 - 1s - 3ms/step - ia: 0.3675 - loss: 1.6684 - mae: 1.0021 - rmse: 1.2883 - smape: 1.3279 - val_ia: 0.4508 - val_loss: 0.6516 - val_mae: 0.5777 - val_rmse: 0.7290 - val_smape: 1.1406

Epoch 15/16

240/240 - 1s - 5ms/step - ia: 0.3724 - loss: 1.6403 - mae: 0.9954 - rmse: 1.2769 - smape: 1.3274 - val_ia: 0.4649 - val_loss: 0.6240 - val_mae: 0.5631 - val_rmse: 0.7135 - val_smape: 1.1125

Epoch 16/16

240/240 - 1s - 6ms/step - ia: 0.3833 - loss: 1.5939 - mae: 0.9789 - rmse: 1.2586 - smape: 1.3103 - val_ia: 0.4782 - val_loss: 0.5975 - val_mae: 0.5491 - val_rmse: 0.6984 - val_smape: 1.0858

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 43s 321ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 36%|███▌      | 18/50 [59:47<1:55:04, 215.76s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 11s - 23ms/step - ia: 0.7648 - loss: 0.2501 - mae: 0.3493 - rmse: 0.4701 - smape: 0.6955 - val_ia: 0.8105 - val_loss: 0.0761 - val_mae: 0.1590 - val_rmse: 0.2409 - val_smape: 0.3993

Epoch 2/16

479/479 - 1s - 3ms/step - ia: 0.8341 - loss: 0.1252 - mae: 0.2427 - rmse: 0.3442 - smape: 0.5392 - val_ia: 0.7791 - val_loss: 0.0808 - val_mae: 0.1775 - val_rmse: 0.2474 - val_smape: 0.4320

Epoch 3/16

479/479 - 1s - 2ms/step - ia: 0.8507 - loss: 0.1088 - mae: 0.2180 - rmse: 0.3189 - smape: 0.4967 - val_ia: 0.8166 - val_loss: 0.0679 - val_mae: 0.1480 - val_rmse: 0.2233 - val_smape: 0.3754

Epoch 4/16

479/479 - 1s - 3ms/step - ia: 0.8590 - loss: 0.0995 - mae: 0.2060 - rmse: 0.3049 - smape: 0.4776 - val_ia: 0.8204 - val_loss: 0.0661 - val_mae: 0.1458 - val_rmse: 0.2208 - val_smape: 0.3742

Epoch 5/16

479/479 - 1s - 2ms/step - ia: 0.8653 - loss: 0.0940 - mae: 0.1959 - rmse: 0.2942 - smape: 0.4607 - val_ia: 0.8301 - val_loss: 0.0619 - val_mae: 0.1407 - val_rmse: 0.2149 - val_smape: 0.3600

Epoch 6/16

479/479 - 2s - 5ms/step - ia: 0.8700 - loss: 0.0875 - mae: 0.1885 - rmse: 0.2835 - smape: 0.4490 - val_ia: 0.8107 - val_loss: 0.0612 - val_mae: 0.1461 - val_rmse: 0.2169 - val_smape: 0.3751

Epoch 7/16

479/479 - 2s - 4ms/step - ia: 0.8728 - loss: 0.0848 - mae: 0.1836 - rmse: 0.2796 - smape: 0.4409 - val_ia: 0.8148 - val_loss: 0.0600 - val_mae: 0.1435 - val_rmse: 0.2142 - val_smape: 0.3687

Epoch 8/16

479/479 - 2s - 3ms/step - ia: 0.8758 - loss: 0.0823 - mae: 0.1797 - rmse: 0.2752 - smape: 0.4351 - val_ia: 0.8212 - val_loss: 0.0589 - val_mae: 0.1388 - val_rmse: 0.2120 - val_smape: 0.3628

Epoch 9/16

479/479 - 4s - 8ms/step - ia: 0.8780 - loss: 0.0807 - mae: 0.1762 - rmse: 0.2716 - smape: 0.4261 - val_ia: 0.7891 - val_loss: 0.0644 - val_mae: 0.1581 - val_rmse: 0.2248 - val_smape: 0.3907

Epoch 10/16

479/479 - 2s - 5ms/step - ia: 0.8792 - loss: 0.0785 - mae: 0.1745 - rmse: 0.2678 - smape: 0.4228 - val_ia: 0.8336 - val_loss: 0.0588 - val_mae: 0.1380 - val_rmse: 0.2102 - val_smape: 0.3584

Epoch 11/16

479/479 - 2s - 4ms/step - ia: 0.8816 - loss: 0.0765 - mae: 0.1712 - rmse: 0.2647 - smape: 0.4178 - val_ia: 0.8165 - val_loss: 0.0621 - val_mae: 0.1480 - val_rmse: 0.2181 - val_smape: 0.3825

Epoch 12/16

479/479 - 2s - 4ms/step - ia: 0.8814 - loss: 0.0764 - mae: 0.1712 - rmse: 0.2649 - smape: 0.4180 - val_ia: 0.8036 - val_loss: 0.0615 - val_mae: 0.1511 - val_rmse: 0.2189 - val_smape: 0.3816

Epoch 13/16

479/479 - 1s - 3ms/step - ia: 0.8837 - loss: 0.0750 - mae: 0.1684 - rmse: 0.2620 - smape: 0.4101 - val_ia: 0.8360 - val_loss: 0.0553 - val_mae: 0.1321 - val_rmse: 0.2043 - val_smape: 0.3517

Epoch 14/16

479/479 - 1s - 3ms/step - ia: 0.8858 - loss: 0.0723 - mae: 0.1652 - rmse: 0.2585 - smape: 0.4027 - val_ia: 0.8018 - val_loss: 0.0608 - val_mae: 0.1512 - val_rmse: 0.2171 - val_smape: 0.3754

Epoch 15/16

479/479 - 1s - 3ms/step - ia: 0.8868 - loss: 0.0734 - mae: 0.1646 - rmse: 0.2593 - smape: 0.3991 - val_ia: 0.8109 - val_loss: 0.0587 - val_mae: 0.1443 - val_rmse: 0.2148 - val_smape: 0.3816

Epoch 16/16

479/479 - 3s - 6ms/step - ia: 0.8860 - loss: 0.0727 - mae: 0.1651 - rmse: 0.2585 - smape: 0.4018 - val_ia: 0.8349 - val_loss: 0.0553 - val_mae: 0.1334 - val_rmse: 0.2042 - val_smape: 0.3541

Restoring model weights from the end of the best epoch: 13.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 28s 210ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 38%|███▊      | 19/50 [1:00:28<1:24:22, 163.32s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3832/3832 - 53s - 14ms/step - ia: 0.5440 - loss: 0.5423 - mae: 0.5078 - rmse: 0.6549 - smape: 0.9737 - val_ia: 0.3293 - val_loss: 0.2132 - val_mae: 0.3123 - val_rmse: 0.3537 - val_smape: 0.6075

Epoch 2/32

3832/3832 - 18s - 5ms/step - ia: 0.6824 - loss: 0.2848 - mae: 0.3764 - rmse: 0.4841 - smape: 0.7235 - val_ia: 0.3683 - val_loss: 0.1657 - val_mae: 0.2711 - val_rmse: 0.3117 - val_smape: 0.5682

Epoch 3/32

3832/3832 - 19s - 5ms/step - ia: 0.7077 - loss: 0.2458 - mae: 0.3476 - rmse: 0.4495 - smape: 0.6862 - val_ia: 0.4009 - val_loss: 0.1309 - val_mae: 0.2374 - val_rmse: 0.2767 - val_smape: 0.5141

Epoch 4/32

3832/3832 - 15s - 4ms/step - ia: 0.7287 - loss: 0.2225 - mae: 0.3262 - rmse: 0.4254 - smape: 0.6605 - val_ia: 0.4165 - val_loss: 0.1143 - val_mae: 0.2200 - val_rmse: 0.2567 - val_smape: 0.5104

Epoch 5/32

3832/3832 - 23s - 6ms/step - ia: 0.7430 - loss: 0.2053 - mae: 0.3110 - rmse: 0.4075 - smape: 0.6457 - val_ia: 0.4397 - val_loss: 0.1002 - val_mae: 0.2019 - val_rmse: 0.2385 - val_smape: 0.4687

Epoch 6/32

3832/3832 - 17s - 5ms/step - ia: 0.7545 - loss: 0.1974 - mae: 0.2992 - rmse: 0.3960 - smape: 0.6248 - val_ia: 0.4637 - val_loss: 0.0903 - val_mae: 0.1854 - val_rmse: 0.2232 - val_smape: 0.4386

Epoch 7/32

3832/3832 - 20s - 5ms/step - ia: 0.7625 - loss: 0.1851 - mae: 0.2900 - rmse: 0.3845 - smape: 0.6073 - val_ia: 0.4636 - val_loss: 0.0958 - val_mae: 0.1931 - val_rmse: 0.2298 - val_smape: 0.4367

Epoch 8/32

3832/3832 - 16s - 4ms/step - ia: 0.7683 - loss: 0.1776 - mae: 0.2827 - rmse: 0.3762 - smape: 0.5967 - val_ia: 0.4839 - val_loss: 0.0802 - val_mae: 0.1712 - val_rmse: 0.2089 - val_smape: 0.4072

Epoch 9/32

3832/3832 - 14s - 4ms/step - ia: 0.7735 - loss: 0.1709 - mae: 0.2773 - rmse: 0.3696 - smape: 0.5898 - val_ia: 0.4963 - val_loss: 0.0772 - val_mae: 0.1654 - val_rmse: 0.2045 - val_smape: 0.3939

Epoch 10/32

3832/3832 - 14s - 4ms/step - ia: 0.7784 - loss: 0.1656 - mae: 0.2711 - rmse: 0.3624 - smape: 0.5770 - val_ia: 0.5091 - val_loss: 0.0741 - val_mae: 0.1594 - val_rmse: 0.1981 - val_smape: 0.3850

Epoch 11/32

3832/3832 - 15s - 4ms/step - ia: 0.7818 - loss: 0.1621 - mae: 0.2672 - rmse: 0.3581 - smape: 0.5720 - val_ia: 0.5104 - val_loss: 0.0725 - val_mae: 0.1571 - val_rmse: 0.1962 - val_smape: 0.3782

Epoch 12/32

3832/3832 - 21s - 6ms/step - ia: 0.7868 - loss: 0.1599 - mae: 0.2635 - rmse: 0.3546 - smape: 0.5639 - val_ia: 0.5017 - val_loss: 0.0723 - val_mae: 0.1632 - val_rmse: 0.2007 - val_smape: 0.3903

Epoch 13/32

3832/3832 - 21s - 5ms/step - ia: 0.7880 - loss: 0.1563 - mae: 0.2606 - rmse: 0.3502 - smape: 0.5666 - val_ia: 0.4968 - val_loss: 0.0718 - val_mae: 0.1652 - val_rmse: 0.2026 - val_smape: 0.4003

Epoch 14/32

3832/3832 - 13s - 3ms/step - ia: 0.7902 - loss: 0.1520 - mae: 0.2572 - rmse: 0.3456 - smape: 0.5584 - val_ia: 0.5160 - val_loss: 0.0683 - val_mae: 0.1550 - val_rmse: 0.1936 - val_smape: 0.3797

Epoch 15/32

3832/3832 - 11s - 3ms/step - ia: 0.7926 - loss: 0.1494 - mae: 0.2546 - rmse: 0.3430 - smape: 0.5529 - val_ia: 0.5054 - val_loss: 0.0691 - val_mae: 0.1602 - val_rmse: 0.1987 - val_smape: 0.3939

Epoch 16/32

3832/3832 - 11s - 3ms/step - ia: 0.7943 - loss: 0.1492 - mae: 0.2535 - rmse: 0.3414 - smape: 0.5515 - val_ia: 0.5027 - val_loss: 0.0707 - val_mae: 0.1628 - val_rmse: 0.2007 - val_smape: 0.3984

Epoch 17/32

3832/3832 - 12s - 3ms/step - ia: 0.7975 - loss: 0.1445 - mae: 0.2496 - rmse: 0.3354 - smape: 0.5515 - val_ia: 0.5194 - val_loss: 0.0658 - val_mae: 0.1525 - val_rmse: 0.1910 - val_smape: 0.3782

Epoch 18/32

3832/3832 - 16s - 4ms/step - ia: 0.7978 - loss: 0.1425 - mae: 0.2482 - rmse: 0.3340 - smape: 0.5474 - val_ia: 0.5175 - val_loss: 0.0660 - val_mae: 0.1540 - val_rmse: 0.1921 - val_smape: 0.3802

Epoch 19/32

3832/3832 - 16s - 4ms/step - ia: 0.7987 - loss: 0.1419 - mae: 0.2477 - rmse: 0.3339 - smape: 0.5436 - val_ia: 0.5201 - val_loss: 0.0646 - val_mae: 0.1532 - val_rmse: 0.1918 - val_smape: 0.3779

Epoch 20/32

3832/3832 - 16s - 4ms/step - ia: 0.8008 - loss: 0.1394 - mae: 0.2458 - rmse: 0.3310 - smape: 0.5432 - val_ia: 0.5196 - val_loss: 0.0646 - val_mae: 0.1520 - val_rmse: 0.1907 - val_smape: 0.3775

Epoch 21/32

3832/3832 - 17s - 4ms/step - ia: 0.8036 - loss: 0.1414 - mae: 0.2435 - rmse: 0.3292 - smape: 0.5355 - val_ia: 0.5025 - val_loss: 0.0736 - val_mae: 0.1672 - val_rmse: 0.2049 - val_smape: 0.3984

Epoch 22/32

3832/3832 - 15s - 4ms/step - ia: 0.8016 - loss: 0.1381 - mae: 0.2420 - rmse: 0.3270 - smape: 0.5343 - val_ia: 0.5163 - val_loss: 0.0654 - val_mae: 0.1555 - val_rmse: 0.1938 - val_smape: 0.3884

Epoch 23/32

3832/3832 - 17s - 4ms/step - ia: 0.8058 - loss: 0.1350 - mae: 0.2396 - rmse: 0.3236 - smape: 0.5338 - val_ia: 0.5219 - val_loss: 0.0643 - val_mae: 0.1517 - val_rmse: 0.1903 - val_smape: 0.3795

Epoch 24/32

3832/3832 - 14s - 4ms/step - ia: 0.8059 - loss: 0.1345 - mae: 0.2400 - rmse: 0.3245 - smape: 0.5349 - val_ia: 0.5101 - val_loss: 0.0671 - val_mae: 0.1583 - val_rmse: 0.1964 - val_smape: 0.3944

Epoch 25/32

3832/3832 - 17s - 4ms/step - ia: 0.8057 - loss: 0.1336 - mae: 0.2381 - rmse: 0.3230 - smape: 0.5315 - val_ia: 0.5167 - val_loss: 0.0640 - val_mae: 0.1532 - val_rmse: 0.1925 - val_smape: 0.3864

Epoch 26/32

3832/3832 - 17s - 4ms/step - ia: 0.8073 - loss: 0.1364 - mae: 0.2381 - rmse: 0.3225 - smape: 0.5261 - val_ia: 0.5258 - val_loss: 0.0635 - val_mae: 0.1494 - val_rmse: 0.1899 - val_smape: 0.3758

Epoch 27/32

3832/3832 - 15s - 4ms/step - ia: 0.8082 - loss: 0.1366 - mae: 0.2384 - rmse: 0.3239 - smape: 0.5293 - val_ia: 0.5153 - val_loss: 0.0639 - val_mae: 0.1537 - val_rmse: 0.1916 - val_smape: 0.3874

Epoch 28/32

3832/3832 - 11s - 3ms/step - ia: 0.8099 - loss: 0.1300 - mae: 0.2350 - rmse: 0.3187 - smape: 0.5221 - val_ia: 0.5190 - val_loss: 0.0640 - val_mae: 0.1517 - val_rmse: 0.1911 - val_smape: 0.3764

Epoch 29/32

3832/3832 - 13s - 3ms/step - ia: 0.8080 - loss: 0.1337 - mae: 0.2366 - rmse: 0.3217 - smape: 0.5246 - val_ia: 0.5139 - val_loss: 0.0652 - val_mae: 0.1558 - val_rmse: 0.1940 - val_smape: 0.3875

Epoch 30/32

3832/3832 - 15s - 4ms/step - ia: 0.8091 - loss: 0.1307 - mae: 0.2348 - rmse: 0.3183 - smape: 0.5221 - val_ia: 0.5151 - val_loss: 0.0650 - val_mae: 0.1554 - val_rmse: 0.1935 - val_smape: 0.3816

Epoch 31/32

3832/3832 - 26s - 7ms/step - ia: 0.8117 - loss: 0.1285 - mae: 0.2334 - rmse: 0.3164 - smape: 0.5197 - val_ia: 0.5224 - val_loss: 0.0614 - val_mae: 0.1506 - val_rmse: 0.1893 - val_smape: 0.3732

Epoch 32/32

3832/3832 - 17s - 5ms/step - ia: 0.8107 - loss: 0.1303 - mae: 0.2342 - rmse: 0.3179 - smape: 0.5228 - val_ia: 0.5217 - val_loss: 0.0643 - val_mae: 0.1524 - val_rmse: 0.1914 - val_smape: 0.3754

Restoring model weights from the end of the best epoch: 31.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:04 926ms/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 40%|████      | 20/50 [1:09:48<2:21:14, 282.47s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 7s - 14ms/step - ia: 0.4127 - loss: 0.7643 - mae: 0.7079 - rmse: 0.8587 - smape: 1.3358 - val_ia: 0.4233 - val_loss: 0.4673 - val_mae: 0.5295 - val_rmse: 0.6206 - val_smape: 1.1461

Epoch 2/64

479/479 - 2s - 5ms/step - ia: 0.6459 - loss: 0.3798 - mae: 0.4323 - rmse: 0.6048 - smape: 0.9126 - val_ia: 0.5495 - val_loss: 0.3027 - val_mae: 0.3804 - val_rmse: 0.4812 - val_smape: 0.8260

Epoch 3/64

479/479 - 3s - 5ms/step - ia: 0.7253 - loss: 0.2930 - mae: 0.3595 - rmse: 0.5308 - smape: 0.7597 - val_ia: 0.6022 - val_loss: 0.2457 - val_mae: 0.3309 - val_rmse: 0.4323 - val_smape: 0.7224

Epoch 4/64

479/479 - 3s - 6ms/step - ia: 0.7577 - loss: 0.2532 - mae: 0.3270 - rmse: 0.4928 - smape: 0.6942 - val_ia: 0.6345 - val_loss: 0.2143 - val_mae: 0.3030 - val_rmse: 0.4027 - val_smape: 0.6684

Epoch 5/64

479/479 - 3s - 6ms/step - ia: 0.7777 - loss: 0.2254 - mae: 0.3038 - rmse: 0.4645 - smape: 0.6499 - val_ia: 0.6577 - val_loss: 0.1919 - val_mae: 0.2839 - val_rmse: 0.3817 - val_smape: 0.6371

Epoch 6/64

479/479 - 2s - 5ms/step - ia: 0.7934 - loss: 0.2030 - mae: 0.2848 - rmse: 0.4398 - smape: 0.6147 - val_ia: 0.6801 - val_loss: 0.1716 - val_mae: 0.2652 - val_rmse: 0.3603 - val_smape: 0.5992

Epoch 7/64

479/479 - 2s - 4ms/step - ia: 0.8061 - loss: 0.1843 - mae: 0.2686 - rmse: 0.4186 - smape: 0.5857 - val_ia: 0.6967 - val_loss: 0.1564 - val_mae: 0.2518 - val_rmse: 0.3450 - val_smape: 0.5771

Epoch 8/64

479/479 - 3s - 6ms/step - ia: 0.8175 - loss: 0.1686 - mae: 0.2544 - rmse: 0.3994 - smape: 0.5604 - val_ia: 0.7103 - val_loss: 0.1433 - val_mae: 0.2399 - val_rmse: 0.3314 - val_smape: 0.5579

Epoch 9/64

479/479 - 2s - 5ms/step - ia: 0.8270 - loss: 0.1555 - mae: 0.2423 - rmse: 0.3828 - smape: 0.5395 - val_ia: 0.7243 - val_loss: 0.1321 - val_mae: 0.2287 - val_rmse: 0.3178 - val_smape: 0.5351

Epoch 10/64

479/479 - 3s - 5ms/step - ia: 0.8352 - loss: 0.1444 - mae: 0.2320 - rmse: 0.3684 - smape: 0.5215 - val_ia: 0.7365 - val_loss: 0.1231 - val_mae: 0.2192 - val_rmse: 0.3065 - val_smape: 0.5163

Epoch 11/64

479/479 - 3s - 6ms/step - ia: 0.8423 - loss: 0.1350 - mae: 0.2227 - rmse: 0.3559 - smape: 0.5045 - val_ia: 0.7462 - val_loss: 0.1152 - val_mae: 0.2111 - val_rmse: 0.2971 - val_smape: 0.5018

Epoch 12/64

479/479 - 3s - 6ms/step - ia: 0.8484 - loss: 0.1269 - mae: 0.2147 - rmse: 0.3451 - smape: 0.4900 - val_ia: 0.7536 - val_loss: 0.1084 - val_mae: 0.2041 - val_rmse: 0.2887 - val_smape: 0.4898

Epoch 13/64

479/479 - 2s - 4ms/step - ia: 0.8541 - loss: 0.1199 - mae: 0.2078 - rmse: 0.3342 - smape: 0.4776 - val_ia: 0.7610 - val_loss: 0.1029 - val_mae: 0.1981 - val_rmse: 0.2822 - val_smape: 0.4797

Epoch 14/64

479/479 - 2s - 3ms/step - ia: 0.8588 - loss: 0.1139 - mae: 0.2016 - rmse: 0.3259 - smape: 0.4669 - val_ia: 0.7678 - val_loss: 0.0976 - val_mae: 0.1922 - val_rmse: 0.2752 - val_smape: 0.4680

Epoch 15/64

479/479 - 2s - 4ms/step - ia: 0.8626 - loss: 0.1087 - mae: 0.1962 - rmse: 0.3181 - smape: 0.4571 - val_ia: 0.7751 - val_loss: 0.0931 - val_mae: 0.1866 - val_rmse: 0.2684 - val_smape: 0.4564

Epoch 16/64

479/479 - 1s - 3ms/step - ia: 0.8667 - loss: 0.1041 - mae: 0.1911 - rmse: 0.3098 - smape: 0.4485 - val_ia: 0.7797 - val_loss: 0.0894 - val_mae: 0.1824 - val_rmse: 0.2629 - val_smape: 0.4477

Epoch 17/64

479/479 - 2s - 3ms/step - ia: 0.8699 - loss: 0.1001 - mae: 0.1868 - rmse: 0.3046 - smape: 0.4409 - val_ia: 0.7848 - val_loss: 0.0861 - val_mae: 0.1784 - val_rmse: 0.2577 - val_smape: 0.4398

Epoch 18/64

479/479 - 2s - 5ms/step - ia: 0.8727 - loss: 0.0966 - mae: 0.1830 - rmse: 0.2996 - smape: 0.4342 - val_ia: 0.7889 - val_loss: 0.0830 - val_mae: 0.1741 - val_rmse: 0.2535 - val_smape: 0.4335

Epoch 19/64

479/479 - 2s - 5ms/step - ia: 0.8753 - loss: 0.0936 - mae: 0.1795 - rmse: 0.2942 - smape: 0.4276 - val_ia: 0.7933 - val_loss: 0.0804 - val_mae: 0.1703 - val_rmse: 0.2498 - val_smape: 0.4265

Epoch 20/64

479/479 - 3s - 6ms/step - ia: 0.8778 - loss: 0.0908 - mae: 0.1759 - rmse: 0.2889 - smape: 0.4206 - val_ia: 0.7957 - val_loss: 0.0785 - val_mae: 0.1683 - val_rmse: 0.2472 - val_smape: 0.4230

Epoch 21/64

479/479 - 3s - 5ms/step - ia: 0.8801 - loss: 0.0884 - mae: 0.1732 - rmse: 0.2857 - smape: 0.4163 - val_ia: 0.8006 - val_loss: 0.0763 - val_mae: 0.1649 - val_rmse: 0.2429 - val_smape: 0.4143

Epoch 22/64

479/479 - 2s - 5ms/step - ia: 0.8819 - loss: 0.0863 - mae: 0.1705 - rmse: 0.2812 - smape: 0.4111 - val_ia: 0.8012 - val_loss: 0.0748 - val_mae: 0.1630 - val_rmse: 0.2413 - val_smape: 0.4128

Epoch 23/64

479/479 - 2s - 5ms/step - ia: 0.8834 - loss: 0.0844 - mae: 0.1682 - rmse: 0.2776 - smape: 0.4070 - val_ia: 0.8057 - val_loss: 0.0729 - val_mae: 0.1598 - val_rmse: 0.2377 - val_smape: 0.4064

Epoch 24/64

479/479 - 3s - 6ms/step - ia: 0.8854 - loss: 0.0826 - mae: 0.1656 - rmse: 0.2746 - smape: 0.4022 - val_ia: 0.8085 - val_loss: 0.0715 - val_mae: 0.1577 - val_rmse: 0.2355 - val_smape: 0.4023

Epoch 25/64

479/479 - 2s - 5ms/step - ia: 0.8866 - loss: 0.0811 - mae: 0.1638 - rmse: 0.2720 - smape: 0.3993 - val_ia: 0.8112 - val_loss: 0.0701 - val_mae: 0.1553 - val_rmse: 0.2331 - val_smape: 0.3975

Epoch 26/64

479/479 - 1s - 3ms/step - ia: 0.8881 - loss: 0.0797 - mae: 0.1618 - rmse: 0.2706 - smape: 0.3953 - val_ia: 0.8134 - val_loss: 0.0690 - val_mae: 0.1533 - val_rmse: 0.2312 - val_smape: 0.3938

Epoch 27/64

479/479 - 1s - 3ms/step - ia: 0.8896 - loss: 0.0784 - mae: 0.1599 - rmse: 0.2670 - smape: 0.3918 - val_ia: 0.8132 - val_loss: 0.0684 - val_mae: 0.1530 - val_rmse: 0.2299 - val_smape: 0.3923

Epoch 28/64

479/479 - 1s - 3ms/step - ia: 0.8905 - loss: 0.0773 - mae: 0.1583 - rmse: 0.2654 - smape: 0.3890 - val_ia: 0.8167 - val_loss: 0.0672 - val_mae: 0.1507 - val_rmse: 0.2277 - val_smape: 0.3872

Epoch 29/64

479/479 - 1s - 2ms/step - ia: 0.8919 - loss: 0.0762 - mae: 0.1568 - rmse: 0.2630 - smape: 0.3861 - val_ia: 0.8187 - val_loss: 0.0661 - val_mae: 0.1489 - val_rmse: 0.2258 - val_smape: 0.3847

Epoch 30/64

479/479 - 3s - 6ms/step - ia: 0.8925 - loss: 0.0752 - mae: 0.1554 - rmse: 0.2609 - smape: 0.3837 - val_ia: 0.8190 - val_loss: 0.0655 - val_mae: 0.1484 - val_rmse: 0.2247 - val_smape: 0.3831

Epoch 31/64

479/479 - 2s - 4ms/step - ia: 0.8934 - loss: 0.0743 - mae: 0.1543 - rmse: 0.2595 - smape: 0.3815 - val_ia: 0.8221 - val_loss: 0.0646 - val_mae: 0.1465 - val_rmse: 0.2232 - val_smape: 0.3797

Epoch 32/64

479/479 - 2s - 5ms/step - ia: 0.8944 - loss: 0.0736 - mae: 0.1530 - rmse: 0.2574 - smape: 0.3791 - val_ia: 0.8221 - val_loss: 0.0641 - val_mae: 0.1460 - val_rmse: 0.2218 - val_smape: 0.3783

Epoch 33/64

479/479 - 3s - 6ms/step - ia: 0.8949 - loss: 0.0728 - mae: 0.1521 - rmse: 0.2574 - smape: 0.3772 - val_ia: 0.8233 - val_loss: 0.0634 - val_mae: 0.1449 - val_rmse: 0.2210 - val_smape: 0.3774

Epoch 34/64

479/479 - 3s - 5ms/step - ia: 0.8955 - loss: 0.0721 - mae: 0.1510 - rmse: 0.2548 - smape: 0.3752 - val_ia: 0.8247 - val_loss: 0.0630 - val_mae: 0.1435 - val_rmse: 0.2205 - val_smape: 0.3752

Epoch 35/64

479/479 - 3s - 6ms/step - ia: 0.8965 - loss: 0.0715 - mae: 0.1501 - rmse: 0.2542 - smape: 0.3738 - val_ia: 0.8265 - val_loss: 0.0626 - val_mae: 0.1428 - val_rmse: 0.2196 - val_smape: 0.3729

Epoch 36/64

479/479 - 2s - 5ms/step - ia: 0.8971 - loss: 0.0710 - mae: 0.1493 - rmse: 0.2539 - smape: 0.3720 - val_ia: 0.8269 - val_loss: 0.0621 - val_mae: 0.1419 - val_rmse: 0.2184 - val_smape: 0.3719

Epoch 37/64

479/479 - 1s - 3ms/step - ia: 0.8976 - loss: 0.0705 - mae: 0.1485 - rmse: 0.2524 - smape: 0.3702 - val_ia: 0.8280 - val_loss: 0.0618 - val_mae: 0.1416 - val_rmse: 0.2174 - val_smape: 0.3696

Epoch 38/64

479/479 - 3s - 5ms/step - ia: 0.8980 - loss: 0.0700 - mae: 0.1478 - rmse: 0.2509 - smape: 0.3690 - val_ia: 0.8272 - val_loss: 0.0617 - val_mae: 0.1417 - val_rmse: 0.2173 - val_smape: 0.3699

Epoch 39/64

479/479 - 1s - 3ms/step - ia: 0.8987 - loss: 0.0695 - mae: 0.1471 - rmse: 0.2498 - smape: 0.3675 - val_ia: 0.8296 - val_loss: 0.0609 - val_mae: 0.1399 - val_rmse: 0.2162 - val_smape: 0.3675

Epoch 40/64

479/479 - 1s - 3ms/step - ia: 0.8989 - loss: 0.0691 - mae: 0.1464 - rmse: 0.2498 - smape: 0.3667 - val_ia: 0.8299 - val_loss: 0.0606 - val_mae: 0.1398 - val_rmse: 0.2152 - val_smape: 0.3661

Epoch 41/64

479/479 - 1s - 3ms/step - ia: 0.8995 - loss: 0.0687 - mae: 0.1462 - rmse: 0.2489 - smape: 0.3656 - val_ia: 0.8299 - val_loss: 0.0602 - val_mae: 0.1390 - val_rmse: 0.2147 - val_smape: 0.3658

Epoch 42/64

479/479 - 4s - 8ms/step - ia: 0.9000 - loss: 0.0684 - mae: 0.1454 - rmse: 0.2474 - smape: 0.3644 - val_ia: 0.8303 - val_loss: 0.0599 - val_mae: 0.1389 - val_rmse: 0.2141 - val_smape: 0.3648

Epoch 43/64

479/479 - 3s - 7ms/step - ia: 0.9003 - loss: 0.0681 - mae: 0.1448 - rmse: 0.2480 - smape: 0.3627 - val_ia: 0.8307 - val_loss: 0.0598 - val_mae: 0.1383 - val_rmse: 0.2137 - val_smape: 0.3640

Epoch 44/64

479/479 - 4s - 8ms/step - ia: 0.9007 - loss: 0.0677 - mae: 0.1444 - rmse: 0.2466 - smape: 0.3628 - val_ia: 0.8318 - val_loss: 0.0597 - val_mae: 0.1378 - val_rmse: 0.2138 - val_smape: 0.3637

Epoch 45/64

479/479 - 3s - 6ms/step - ia: 0.9007 - loss: 0.0675 - mae: 0.1442 - rmse: 0.2461 - smape: 0.3622 - val_ia: 0.8334 - val_loss: 0.0593 - val_mae: 0.1369 - val_rmse: 0.2129 - val_smape: 0.3614

Epoch 46/64

479/479 - 3s - 6ms/step - ia: 0.9012 - loss: 0.0672 - mae: 0.1437 - rmse: 0.2453 - smape: 0.3612 - val_ia: 0.8335 - val_loss: 0.0591 - val_mae: 0.1368 - val_rmse: 0.2123 - val_smape: 0.3605

Epoch 47/64

479/479 - 5s - 10ms/step - ia: 0.9011 - loss: 0.0669 - mae: 0.1435 - rmse: 0.2456 - smape: 0.3605 - val_ia: 0.8347 - val_loss: 0.0590 - val_mae: 0.1361 - val_rmse: 0.2125 - val_smape: 0.3589

Epoch 48/64

479/479 - 2s - 4ms/step - ia: 0.9020 - loss: 0.0667 - mae: 0.1428 - rmse: 0.2443 - smape: 0.3587 - val_ia: 0.8338 - val_loss: 0.0590 - val_mae: 0.1364 - val_rmse: 0.2123 - val_smape: 0.3603

Epoch 49/64

479/479 - 2s - 4ms/step - ia: 0.9018 - loss: 0.0664 - mae: 0.1425 - rmse: 0.2437 - smape: 0.3584 - val_ia: 0.8342 - val_loss: 0.0586 - val_mae: 0.1361 - val_rmse: 0.2114 - val_smape: 0.3594

Epoch 50/64

479/479 - 1s - 3ms/step - ia: 0.9021 - loss: 0.0662 - mae: 0.1424 - rmse: 0.2433 - smape: 0.3581 - val_ia: 0.8348 - val_loss: 0.0587 - val_mae: 0.1355 - val_rmse: 0.2120 - val_smape: 0.3587

Epoch 51/64

479/479 - 2s - 3ms/step - ia: 0.9022 - loss: 0.0660 - mae: 0.1419 - rmse: 0.2430 - smape: 0.3573 - val_ia: 0.8343 - val_loss: 0.0584 - val_mae: 0.1360 - val_rmse: 0.2107 - val_smape: 0.3577

Epoch 52/64

479/479 - 2s - 3ms/step - ia: 0.9022 - loss: 0.0658 - mae: 0.1418 - rmse: 0.2433 - smape: 0.3573 - val_ia: 0.8354 - val_loss: 0.0583 - val_mae: 0.1349 - val_rmse: 0.2110 - val_smape: 0.3566

Epoch 53/64

479/479 - 1s - 2ms/step - ia: 0.9026 - loss: 0.0656 - mae: 0.1415 - rmse: 0.2424 - smape: 0.3568 - val_ia: 0.8359 - val_loss: 0.0583 - val_mae: 0.1347 - val_rmse: 0.2110 - val_smape: 0.3563

Epoch 54/64

479/479 - 1s - 3ms/step - ia: 0.9030 - loss: 0.0654 - mae: 0.1412 - rmse: 0.2424 - smape: 0.3562 - val_ia: 0.8360 - val_loss: 0.0580 - val_mae: 0.1344 - val_rmse: 0.2104 - val_smape: 0.3559

Epoch 55/64

479/479 - 1s - 3ms/step - ia: 0.9029 - loss: 0.0653 - mae: 0.1409 - rmse: 0.2418 - smape: 0.3551 - val_ia: 0.8359 - val_loss: 0.0578 - val_mae: 0.1344 - val_rmse: 0.2098 - val_smape: 0.3560

Epoch 56/64

479/479 - 2s - 5ms/step - ia: 0.9031 - loss: 0.0651 - mae: 0.1408 - rmse: 0.2421 - smape: 0.3552 - val_ia: 0.8359 - val_loss: 0.0580 - val_mae: 0.1343 - val_rmse: 0.2105 - val_smape: 0.3567

Epoch 57/64

479/479 - 2s - 4ms/step - ia: 0.9036 - loss: 0.0650 - mae: 0.1404 - rmse: 0.2406 - smape: 0.3544 - val_ia: 0.8361 - val_loss: 0.0578 - val_mae: 0.1342 - val_rmse: 0.2095 - val_smape: 0.3546

Epoch 58/64

479/479 - 2s - 4ms/step - ia: 0.9032 - loss: 0.0649 - mae: 0.1404 - rmse: 0.2402 - smape: 0.3551 - val_ia: 0.8364 - val_loss: 0.0577 - val_mae: 0.1339 - val_rmse: 0.2097 - val_smape: 0.3553

Epoch 59/64

479/479 - 2s - 5ms/step - ia: 0.9036 - loss: 0.0647 - mae: 0.1402 - rmse: 0.2405 - smape: 0.3541 - val_ia: 0.8364 - val_loss: 0.0574 - val_mae: 0.1337 - val_rmse: 0.2090 - val_smape: 0.3538

Epoch 60/64

479/479 - 3s - 6ms/step - ia: 0.9037 - loss: 0.0646 - mae: 0.1400 - rmse: 0.2402 - smape: 0.3540 - val_ia: 0.8376 - val_loss: 0.0573 - val_mae: 0.1332 - val_rmse: 0.2085 - val_smape: 0.3523

Epoch 61/64

479/479 - 6s - 12ms/step - ia: 0.9037 - loss: 0.0645 - mae: 0.1399 - rmse: 0.2398 - smape: 0.3532 - val_ia: 0.8351 - val_loss: 0.0578 - val_mae: 0.1347 - val_rmse: 0.2105 - val_smape: 0.3580

Epoch 62/64

479/479 - 3s - 6ms/step - ia: 0.9040 - loss: 0.0644 - mae: 0.1398 - rmse: 0.2402 - smape: 0.3536 - val_ia: 0.8375 - val_loss: 0.0573 - val_mae: 0.1333 - val_rmse: 0.2089 - val_smape: 0.3539

Epoch 63/64

479/479 - 4s - 7ms/step - ia: 0.9043 - loss: 0.0642 - mae: 0.1396 - rmse: 0.2395 - smape: 0.3534 - val_ia: 0.8381 - val_loss: 0.0573 - val_mae: 0.1331 - val_rmse: 0.2084 - val_smape: 0.3520

Epoch 64/64

479/479 - 3s - 7ms/step - ia: 0.9043 - loss: 0.0641 - mae: 0.1394 - rmse: 0.2387 - smape: 0.3525 - val_ia: 0.8376 - val_loss: 0.0572 - val_mae: 0.1330 - val_rmse: 0.2087 - val_smape: 0.3540

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:26 638ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 42%|████▏     | 21/50 [1:12:30<1:59:02, 246.29s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 15s - 8ms/step - ia: 0.6819 - loss: 0.3567 - mae: 0.4378 - rmse: 0.5662 - smape: 0.8343 - val_ia: 0.5875 - val_loss: 0.1033 - val_mae: 0.1912 - val_rmse: 0.2505 - val_smape: 0.4590

Epoch 2/128

1916/1916 - 9s - 5ms/step - ia: 0.7747 - loss: 0.1882 - mae: 0.3104 - rmse: 0.4111 - smape: 0.6529 - val_ia: 0.6208 - val_loss: 0.0895 - val_mae: 0.1731 - val_rmse: 0.2319 - val_smape: 0.4267

Epoch 3/128

1916/1916 - 10s - 5ms/step - ia: 0.8051 - loss: 0.1486 - mae: 0.2658 - rmse: 0.3609 - smape: 0.5757 - val_ia: 0.6373 - val_loss: 0.0845 - val_mae: 0.1674 - val_rmse: 0.2224 - val_smape: 0.4015

Epoch 4/128

1916/1916 - 9s - 5ms/step - ia: 0.8186 - loss: 0.1372 - mae: 0.2499 - rmse: 0.3432 - smape: 0.5494 - val_ia: 0.6591 - val_loss: 0.0772 - val_mae: 0.1544 - val_rmse: 0.2115 - val_smape: 0.3817

Epoch 5/128

1916/1916 - 6s - 3ms/step - ia: 0.8293 - loss: 0.1242 - mae: 0.2355 - rmse: 0.3254 - smape: 0.5222 - val_ia: 0.6605 - val_loss: 0.0740 - val_mae: 0.1506 - val_rmse: 0.2070 - val_smape: 0.3763

Epoch 6/128

1916/1916 - 11s - 6ms/step - ia: 0.8374 - loss: 0.1156 - mae: 0.2251 - rmse: 0.3125 - smape: 0.5070 - val_ia: 0.6723 - val_loss: 0.0697 - val_mae: 0.1442 - val_rmse: 0.1993 - val_smape: 0.3642

Epoch 7/128

1916/1916 - 14s - 7ms/step - ia: 0.8395 - loss: 0.1112 - mae: 0.2201 - rmse: 0.3070 - smape: 0.4955 - val_ia: 0.6773 - val_loss: 0.0680 - val_mae: 0.1416 - val_rmse: 0.1962 - val_smape: 0.3589

Epoch 8/128

1916/1916 - 10s - 5ms/step - ia: 0.8442 - loss: 0.1065 - mae: 0.2135 - rmse: 0.2981 - smape: 0.4875 - val_ia: 0.6712 - val_loss: 0.0664 - val_mae: 0.1429 - val_rmse: 0.1991 - val_smape: 0.3650

Epoch 9/128

1916/1916 - 11s - 6ms/step - ia: 0.8477 - loss: 0.1033 - mae: 0.2085 - rmse: 0.2924 - smape: 0.4785 - val_ia: 0.6884 - val_loss: 0.0634 - val_mae: 0.1367 - val_rmse: 0.1923 - val_smape: 0.3546

Epoch 10/128

1916/1916 - 10s - 5ms/step - ia: 0.8497 - loss: 0.1005 - mae: 0.2044 - rmse: 0.2885 - smape: 0.4732 - val_ia: 0.6695 - val_loss: 0.0649 - val_mae: 0.1431 - val_rmse: 0.1988 - val_smape: 0.3661

Epoch 11/128

1916/1916 - 10s - 5ms/step - ia: 0.8533 - loss: 0.0976 - mae: 0.2009 - rmse: 0.2832 - smape: 0.4687 - val_ia: 0.6859 - val_loss: 0.0616 - val_mae: 0.1353 - val_rmse: 0.1910 - val_smape: 0.3506

Epoch 12/128

1916/1916 - 11s - 6ms/step - ia: 0.8560 - loss: 0.0945 - mae: 0.1973 - rmse: 0.2794 - smape: 0.4611 - val_ia: 0.6478 - val_loss: 0.0632 - val_mae: 0.1460 - val_rmse: 0.1982 - val_smape: 0.3700

Epoch 13/128

1916/1916 - 21s - 11ms/step - ia: 0.8563 - loss: 0.0941 - mae: 0.1950 - rmse: 0.2776 - smape: 0.4591 - val_ia: 0.6832 - val_loss: 0.0606 - val_mae: 0.1364 - val_rmse: 0.1902 - val_smape: 0.3558

Epoch 14/128

1916/1916 - 15s - 8ms/step - ia: 0.8594 - loss: 0.0906 - mae: 0.1915 - rmse: 0.2723 - smape: 0.4560 - val_ia: 0.6569 - val_loss: 0.0618 - val_mae: 0.1431 - val_rmse: 0.1946 - val_smape: 0.3650

Epoch 15/128

1916/1916 - 14s - 7ms/step - ia: 0.8609 - loss: 0.0888 - mae: 0.1896 - rmse: 0.2697 - smape: 0.4513 - val_ia: 0.6694 - val_loss: 0.0598 - val_mae: 0.1377 - val_rmse: 0.1913 - val_smape: 0.3579

Epoch 16/128

1916/1916 - 8s - 4ms/step - ia: 0.8622 - loss: 0.0885 - mae: 0.1878 - rmse: 0.2685 - smape: 0.4470 - val_ia: 0.6825 - val_loss: 0.0589 - val_mae: 0.1343 - val_rmse: 0.1882 - val_smape: 0.3524

Epoch 17/128

1916/1916 - 14s - 7ms/step - ia: 0.8626 - loss: 0.0869 - mae: 0.1867 - rmse: 0.2660 - smape: 0.4433 - val_ia: 0.6595 - val_loss: 0.0593 - val_mae: 0.1406 - val_rmse: 0.1929 - val_smape: 0.3631

Epoch 18/128

1916/1916 - 11s - 6ms/step - ia: 0.8631 - loss: 0.0852 - mae: 0.1848 - rmse: 0.2639 - smape: 0.4419 - val_ia: 0.6717 - val_loss: 0.0590 - val_mae: 0.1372 - val_rmse: 0.1897 - val_smape: 0.3575

Epoch 19/128

1916/1916 - 16s - 8ms/step - ia: 0.8662 - loss: 0.0843 - mae: 0.1825 - rmse: 0.2621 - smape: 0.4370 - val_ia: 0.6769 - val_loss: 0.0577 - val_mae: 0.1347 - val_rmse: 0.1878 - val_smape: 0.3541

Epoch 20/128

1916/1916 - 12s - 6ms/step - ia: 0.8672 - loss: 0.0834 - mae: 0.1804 - rmse: 0.2602 - smape: 0.4331 - val_ia: 0.6661 - val_loss: 0.0581 - val_mae: 0.1386 - val_rmse: 0.1902 - val_smape: 0.3600

Epoch 21/128

1916/1916 - 13s - 7ms/step - ia: 0.8678 - loss: 0.0825 - mae: 0.1796 - rmse: 0.2574 - smape: 0.4311 - val_ia: 0.6697 - val_loss: 0.0581 - val_mae: 0.1372 - val_rmse: 0.1900 - val_smape: 0.3586

Epoch 22/128

1916/1916 - 7s - 4ms/step - ia: 0.8694 - loss: 0.0814 - mae: 0.1778 - rmse: 0.2570 - smape: 0.4279 - val_ia: 0.6810 - val_loss: 0.0567 - val_mae: 0.1334 - val_rmse: 0.1861 - val_smape: 0.3540

Epoch 23/128

1916/1916 - 6s - 3ms/step - ia: 0.8706 - loss: 0.0808 - mae: 0.1762 - rmse: 0.2549 - smape: 0.4246 - val_ia: 0.6765 - val_loss: 0.0570 - val_mae: 0.1344 - val_rmse: 0.1873 - val_smape: 0.3536

Epoch 24/128

1916/1916 - 5s - 3ms/step - ia: 0.8703 - loss: 0.0803 - mae: 0.1763 - rmse: 0.2551 - smape: 0.4266 - val_ia: 0.6870 - val_loss: 0.0565 - val_mae: 0.1319 - val_rmse: 0.1852 - val_smape: 0.3505

Epoch 25/128

1916/1916 - 7s - 4ms/step - ia: 0.8724 - loss: 0.0797 - mae: 0.1747 - rmse: 0.2526 - smape: 0.4200 - val_ia: 0.6730 - val_loss: 0.0571 - val_mae: 0.1356 - val_rmse: 0.1892 - val_smape: 0.3578

Epoch 26/128

1916/1916 - 14s - 7ms/step - ia: 0.8720 - loss: 0.0793 - mae: 0.1744 - rmse: 0.2523 - smape: 0.4228 - val_ia: 0.6785 - val_loss: 0.0564 - val_mae: 0.1334 - val_rmse: 0.1860 - val_smape: 0.3497

Epoch 27/128

1916/1916 - 8s - 4ms/step - ia: 0.8723 - loss: 0.0771 - mae: 0.1732 - rmse: 0.2505 - smape: 0.4170 - val_ia: 0.6751 - val_loss: 0.0574 - val_mae: 0.1359 - val_rmse: 0.1883 - val_smape: 0.3531

Epoch 28/128

1916/1916 - 9s - 5ms/step - ia: 0.8737 - loss: 0.0778 - mae: 0.1719 - rmse: 0.2500 - smape: 0.4163 - val_ia: 0.6550 - val_loss: 0.0570 - val_mae: 0.1400 - val_rmse: 0.1919 - val_smape: 0.3642

Epoch 29/128

1916/1916 - 6s - 3ms/step - ia: 0.8738 - loss: 0.0776 - mae: 0.1719 - rmse: 0.2496 - smape: 0.4166 - val_ia: 0.6886 - val_loss: 0.0553 - val_mae: 0.1300 - val_rmse: 0.1837 - val_smape: 0.3473

Epoch 30/128

1916/1916 - 8s - 4ms/step - ia: 0.8740 - loss: 0.0769 - mae: 0.1714 - rmse: 0.2493 - smape: 0.4147 - val_ia: 0.6793 - val_loss: 0.0557 - val_mae: 0.1325 - val_rmse: 0.1861 - val_smape: 0.3521

Epoch 31/128

1916/1916 - 11s - 6ms/step - ia: 0.8757 - loss: 0.0768 - mae: 0.1695 - rmse: 0.2472 - smape: 0.4103 - val_ia: 0.6718 - val_loss: 0.0569 - val_mae: 0.1371 - val_rmse: 0.1883 - val_smape: 0.3553

Epoch 32/128

1916/1916 - 8s - 4ms/step - ia: 0.8755 - loss: 0.0761 - mae: 0.1694 - rmse: 0.2474 - smape: 0.4112 - val_ia: 0.6881 - val_loss: 0.0551 - val_mae: 0.1313 - val_rmse: 0.1836 - val_smape: 0.3499

Epoch 33/128

1916/1916 - 5s - 3ms/step - ia: 0.8767 - loss: 0.0750 - mae: 0.1679 - rmse: 0.2454 - smape: 0.4063 - val_ia: 0.6869 - val_loss: 0.0546 - val_mae: 0.1302 - val_rmse: 0.1827 - val_smape: 0.3460

Epoch 34/128

1916/1916 - 6s - 3ms/step - ia: 0.8772 - loss: 0.0751 - mae: 0.1678 - rmse: 0.2451 - smape: 0.4065 - val_ia: 0.6822 - val_loss: 0.0558 - val_mae: 0.1331 - val_rmse: 0.1850 - val_smape: 0.3483

Epoch 35/128

1916/1916 - 15s - 8ms/step - ia: 0.8775 - loss: 0.0745 - mae: 0.1674 - rmse: 0.2445 - smape: 0.4079 - val_ia: 0.6698 - val_loss: 0.0554 - val_mae: 0.1353 - val_rmse: 0.1866 - val_smape: 0.3535

Epoch 36/128

1916/1916 - 12s - 6ms/step - ia: 0.8777 - loss: 0.0743 - mae: 0.1664 - rmse: 0.2438 - smape: 0.4051 - val_ia: 0.6793 - val_loss: 0.0555 - val_mae: 0.1344 - val_rmse: 0.1861 - val_smape: 0.3561

Epoch 37/128

1916/1916 - 14s - 7ms/step - ia: 0.8772 - loss: 0.0748 - mae: 0.1669 - rmse: 0.2443 - smape: 0.4037 - val_ia: 0.6897 - val_loss: 0.0568 - val_mae: 0.1336 - val_rmse: 0.1860 - val_smape: 0.3494

Epoch 38/128

1916/1916 - 8s - 4ms/step - ia: 0.8781 - loss: 0.0737 - mae: 0.1658 - rmse: 0.2435 - smape: 0.4047 - val_ia: 0.6641 - val_loss: 0.0559 - val_mae: 0.1377 - val_rmse: 0.1896 - val_smape: 0.3612

Epoch 39/128

1916/1916 - 6s - 3ms/step - ia: 0.8781 - loss: 0.0745 - mae: 0.1661 - rmse: 0.2437 - smape: 0.4026 - val_ia: 0.6939 - val_loss: 0.0550 - val_mae: 0.1301 - val_rmse: 0.1832 - val_smape: 0.3464

Epoch 40/128

1916/1916 - 7s - 4ms/step - ia: 0.8786 - loss: 0.0735 - mae: 0.1656 - rmse: 0.2426 - smape: 0.4016 - val_ia: 0.6879 - val_loss: 0.0547 - val_mae: 0.1308 - val_rmse: 0.1829 - val_smape: 0.3466

Epoch 41/128

1916/1916 - 10s - 5ms/step - ia: 0.8802 - loss: 0.0724 - mae: 0.1644 - rmse: 0.2414 - smape: 0.3995 - val_ia: 0.6793 - val_loss: 0.0545 - val_mae: 0.1322 - val_rmse: 0.1846 - val_smape: 0.3499

Epoch 42/128

1916/1916 - 7s - 4ms/step - ia: 0.8797 - loss: 0.0735 - mae: 0.1646 - rmse: 0.2420 - smape: 0.3983 - val_ia: 0.6697 - val_loss: 0.0561 - val_mae: 0.1367 - val_rmse: 0.1886 - val_smape: 0.3583

Epoch 43/128

1916/1916 - 10s - 5ms/step - ia: 0.8788 - loss: 0.0744 - mae: 0.1650 - rmse: 0.2429 - smape: 0.4023 - val_ia: 0.6749 - val_loss: 0.0562 - val_mae: 0.1353 - val_rmse: 0.1881 - val_smape: 0.3562

Epoch 44/128

1916/1916 - 11s - 6ms/step - ia: 0.8799 - loss: 0.0732 - mae: 0.1640 - rmse: 0.2412 - smape: 0.4001 - val_ia: 0.6695 - val_loss: 0.0563 - val_mae: 0.1371 - val_rmse: 0.1884 - val_smape: 0.3540

Epoch 45/128

1916/1916 - 9s - 5ms/step - ia: 0.8797 - loss: 0.0723 - mae: 0.1632 - rmse: 0.2395 - smape: 0.3977 - val_ia: 0.6996 - val_loss: 0.0547 - val_mae: 0.1294 - val_rmse: 0.1826 - val_smape: 0.3434

Epoch 46/128

1916/1916 - 5s - 2ms/step - ia: 0.8800 - loss: 0.0726 - mae: 0.1635 - rmse: 0.2409 - smape: 0.3959 - val_ia: 0.6952 - val_loss: 0.0540 - val_mae: 0.1286 - val_rmse: 0.1815 - val_smape: 0.3440

Epoch 47/128

1916/1916 - 9s - 5ms/step - ia: 0.8804 - loss: 0.0718 - mae: 0.1629 - rmse: 0.2404 - smape: 0.3960 - val_ia: 0.6975 - val_loss: 0.0555 - val_mae: 0.1318 - val_rmse: 0.1837 - val_smape: 0.3454

Epoch 48/128

1916/1916 - 11s - 5ms/step - ia: 0.8798 - loss: 0.0725 - mae: 0.1636 - rmse: 0.2411 - smape: 0.3973 - val_ia: 0.6911 - val_loss: 0.0578 - val_mae: 0.1351 - val_rmse: 0.1872 - val_smape: 0.3484

Epoch 49/128

1916/1916 - 8s - 4ms/step - ia: 0.8810 - loss: 0.0723 - mae: 0.1630 - rmse: 0.2396 - smape: 0.3955 - val_ia: 0.6962 - val_loss: 0.0555 - val_mae: 0.1324 - val_rmse: 0.1844 - val_smape: 0.3459

Epoch 50/128

1916/1916 - 5s - 3ms/step - ia: 0.8812 - loss: 0.0712 - mae: 0.1625 - rmse: 0.2388 - smape: 0.3960 - val_ia: 0.6860 - val_loss: 0.0548 - val_mae: 0.1323 - val_rmse: 0.1837 - val_smape: 0.3479

Epoch 51/128

1916/1916 - 11s - 6ms/step - ia: 0.8805 - loss: 0.0721 - mae: 0.1626 - rmse: 0.2395 - smape: 0.3947 - val_ia: 0.6817 - val_loss: 0.0573 - val_mae: 0.1365 - val_rmse: 0.1879 - val_smape: 0.3526

Epoch 52/128

1916/1916 - 13s - 7ms/step - ia: 0.8799 - loss: 0.0717 - mae: 0.1635 - rmse: 0.2405 - smape: 0.3978 - val_ia: 0.6986 - val_loss: 0.0553 - val_mae: 0.1301 - val_rmse: 0.1834 - val_smape: 0.3450

Epoch 53/128

1916/1916 - 9s - 5ms/step - ia: 0.8809 - loss: 0.0716 - mae: 0.1627 - rmse: 0.2390 - smape: 0.3948 - val_ia: 0.6849 - val_loss: 0.0549 - val_mae: 0.1319 - val_rmse: 0.1846 - val_smape: 0.3506

Epoch 54/128

1916/1916 - 5s - 3ms/step - ia: 0.8814 - loss: 0.0713 - mae: 0.1621 - rmse: 0.2392 - smape: 0.3949 - val_ia: 0.6884 - val_loss: 0.0544 - val_mae: 0.1307 - val_rmse: 0.1832 - val_smape: 0.3476

Epoch 55/128

1916/1916 - 4s - 2ms/step - ia: 0.8802 - loss: 0.0727 - mae: 0.1631 - rmse: 0.2409 - smape: 0.3965 - val_ia: 0.6927 - val_loss: 0.0545 - val_mae: 0.1301 - val_rmse: 0.1827 - val_smape: 0.3456

Epoch 56/128

1916/1916 - 7s - 4ms/step - ia: 0.8802 - loss: 0.0722 - mae: 0.1633 - rmse: 0.2401 - smape: 0.3950 - val_ia: 0.6694 - val_loss: 0.0554 - val_mae: 0.1368 - val_rmse: 0.1875 - val_smape: 0.3556

Epoch 57/128

1916/1916 - 14s - 7ms/step - ia: 0.8804 - loss: 0.0721 - mae: 0.1632 - rmse: 0.2403 - smape: 0.3936 - val_ia: 0.6889 - val_loss: 0.0546 - val_mae: 0.1315 - val_rmse: 0.1831 - val_smape: 0.3471

Epoch 58/128

1916/1916 - 9s - 5ms/step - ia: 0.8812 - loss: 0.0716 - mae: 0.1618 - rmse: 0.2383 - smape: 0.3939 - val_ia: 0.6936 - val_loss: 0.0547 - val_mae: 0.1301 - val_rmse: 0.1830 - val_smape: 0.3460

Epoch 59/128

1916/1916 - 4s - 2ms/step - ia: 0.8811 - loss: 0.0710 - mae: 0.1625 - rmse: 0.2386 - smape: 0.3951 - val_ia: 0.6747 - val_loss: 0.0547 - val_mae: 0.1341 - val_rmse: 0.1856 - val_smape: 0.3534

Epoch 60/128

1916/1916 - 6s - 3ms/step - ia: 0.8805 - loss: 0.0717 - mae: 0.1625 - rmse: 0.2392 - smape: 0.3944 - val_ia: 0.6914 - val_loss: 0.0545 - val_mae: 0.1311 - val_rmse: 0.1829 - val_smape: 0.3486

Epoch 61/128

1916/1916 - 8s - 4ms/step - ia: 0.8822 - loss: 0.0713 - mae: 0.1616 - rmse: 0.2389 - smape: 0.3918 - val_ia: 0.6807 - val_loss: 0.0556 - val_mae: 0.1342 - val_rmse: 0.1863 - val_smape: 0.3532

Epoch 61: early stopping

Restoring model weights from the end of the best epoch: 46.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 220ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 44%|████▍     | 22/50 [1:22:22<2:43:23, 350.11s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 21s - 11ms/step - ia: 0.5016 - loss: 0.8789 - mae: 0.6717 - rmse: 0.8851 - smape: 1.1099 - val_ia: 0.3466 - val_loss: 0.2999 - val_mae: 0.3652 - val_rmse: 0.4359 - val_smape: 0.7698

Epoch 2/128

1916/1916 - 15s - 8ms/step - ia: 0.6192 - loss: 0.5062 - mae: 0.5338 - rmse: 0.6885 - smape: 0.9441 - val_ia: 0.4210 - val_loss: 0.2075 - val_mae: 0.2956 - val_rmse: 0.3633 - val_smape: 0.6501

Epoch 3/128

1916/1916 - 17s - 9ms/step - ia: 0.6565 - loss: 0.4153 - mae: 0.4840 - rmse: 0.6237 - smape: 0.8860 - val_ia: 0.4782 - val_loss: 0.1609 - val_mae: 0.2543 - val_rmse: 0.3190 - val_smape: 0.5811

Epoch 4/128

1916/1916 - 9s - 4ms/step - ia: 0.6795 - loss: 0.3565 - mae: 0.4498 - rmse: 0.5781 - smape: 0.8451 - val_ia: 0.5178 - val_loss: 0.1359 - val_mae: 0.2297 - val_rmse: 0.2921 - val_smape: 0.5354

Epoch 5/128

1916/1916 - 6s - 3ms/step - ia: 0.6999 - loss: 0.3131 - mae: 0.4192 - rmse: 0.5411 - smape: 0.8041 - val_ia: 0.5451 - val_loss: 0.1207 - val_mae: 0.2132 - val_rmse: 0.2748 - val_smape: 0.5057

Epoch 6/128

1916/1916 - 13s - 7ms/step - ia: 0.7133 - loss: 0.2850 - mae: 0.3996 - rmse: 0.5152 - smape: 0.7821 - val_ia: 0.5653 - val_loss: 0.1115 - val_mae: 0.2025 - val_rmse: 0.2627 - val_smape: 0.4825

Epoch 7/128

1916/1916 - 6s - 3ms/step - ia: 0.7278 - loss: 0.2584 - mae: 0.3781 - rmse: 0.4898 - smape: 0.7513 - val_ia: 0.5812 - val_loss: 0.1039 - val_mae: 0.1937 - val_rmse: 0.2533 - val_smape: 0.4656

Epoch 8/128

1916/1916 - 8s - 4ms/step - ia: 0.7392 - loss: 0.2373 - mae: 0.3606 - rmse: 0.4677 - smape: 0.7307 - val_ia: 0.5928 - val_loss: 0.0993 - val_mae: 0.1876 - val_rmse: 0.2469 - val_smape: 0.4532

Epoch 9/128

1916/1916 - 8s - 4ms/step - ia: 0.7498 - loss: 0.2227 - mae: 0.3475 - rmse: 0.4528 - smape: 0.7101 - val_ia: 0.5995 - val_loss: 0.0967 - val_mae: 0.1842 - val_rmse: 0.2436 - val_smape: 0.4472

Epoch 10/128

1916/1916 - 7s - 4ms/step - ia: 0.7575 - loss: 0.2078 - mae: 0.3340 - rmse: 0.4353 - smape: 0.6927 - val_ia: 0.6076 - val_loss: 0.0932 - val_mae: 0.1795 - val_rmse: 0.2387 - val_smape: 0.4379

Epoch 11/128

1916/1916 - 9s - 5ms/step - ia: 0.7672 - loss: 0.1966 - mae: 0.3217 - rmse: 0.4229 - smape: 0.6694 - val_ia: 0.6112 - val_loss: 0.0915 - val_mae: 0.1776 - val_rmse: 0.2358 - val_smape: 0.4325

Epoch 12/128

1916/1916 - 10s - 5ms/step - ia: 0.7738 - loss: 0.1878 - mae: 0.3123 - rmse: 0.4124 - smape: 0.6548 - val_ia: 0.6195 - val_loss: 0.0896 - val_mae: 0.1739 - val_rmse: 0.2321 - val_smape: 0.4257

Epoch 13/128

1916/1916 - 8s - 4ms/step - ia: 0.7803 - loss: 0.1776 - mae: 0.3021 - rmse: 0.4002 - smape: 0.6412 - val_ia: 0.6243 - val_loss: 0.0882 - val_mae: 0.1714 - val_rmse: 0.2294 - val_smape: 0.4189

Epoch 14/128

1916/1916 - 8s - 4ms/step - ia: 0.7865 - loss: 0.1728 - mae: 0.2954 - rmse: 0.3932 - smape: 0.6283 - val_ia: 0.6293 - val_loss: 0.0874 - val_mae: 0.1696 - val_rmse: 0.2274 - val_smape: 0.4153

Epoch 15/128

1916/1916 - 12s - 6ms/step - ia: 0.7915 - loss: 0.1659 - mae: 0.2868 - rmse: 0.3840 - smape: 0.6145 - val_ia: 0.6337 - val_loss: 0.0869 - val_mae: 0.1685 - val_rmse: 0.2255 - val_smape: 0.4101

Epoch 16/128

1916/1916 - 4s - 2ms/step - ia: 0.7950 - loss: 0.1616 - mae: 0.2820 - rmse: 0.3793 - smape: 0.6050 - val_ia: 0.6323 - val_loss: 0.0859 - val_mae: 0.1675 - val_rmse: 0.2250 - val_smape: 0.4105

Epoch 17/128

1916/1916 - 3s - 2ms/step - ia: 0.7983 - loss: 0.1572 - mae: 0.2773 - rmse: 0.3729 - smape: 0.5999 - val_ia: 0.6394 - val_loss: 0.0850 - val_mae: 0.1655 - val_rmse: 0.2220 - val_smape: 0.4039

Epoch 18/128

1916/1916 - 11s - 5ms/step - ia: 0.8034 - loss: 0.1521 - mae: 0.2700 - rmse: 0.3665 - smape: 0.5856 - val_ia: 0.6413 - val_loss: 0.0838 - val_mae: 0.1641 - val_rmse: 0.2207 - val_smape: 0.4015

Epoch 19/128

1916/1916 - 8s - 4ms/step - ia: 0.8035 - loss: 0.1524 - mae: 0.2701 - rmse: 0.3658 - smape: 0.5850 - val_ia: 0.6449 - val_loss: 0.0829 - val_mae: 0.1622 - val_rmse: 0.2193 - val_smape: 0.3987

Epoch 20/128

1916/1916 - 9s - 5ms/step - ia: 0.8069 - loss: 0.1480 - mae: 0.2654 - rmse: 0.3596 - smape: 0.5789 - val_ia: 0.6500 - val_loss: 0.0825 - val_mae: 0.1605 - val_rmse: 0.2177 - val_smape: 0.3938

Epoch 21/128

1916/1916 - 11s - 6ms/step - ia: 0.8089 - loss: 0.1462 - mae: 0.2622 - rmse: 0.3563 - smape: 0.5683 - val_ia: 0.6509 - val_loss: 0.0818 - val_mae: 0.1596 - val_rmse: 0.2165 - val_smape: 0.3924

Epoch 22/128

1916/1916 - 8s - 4ms/step - ia: 0.8123 - loss: 0.1438 - mae: 0.2577 - rmse: 0.3527 - smape: 0.5626 - val_ia: 0.6527 - val_loss: 0.0810 - val_mae: 0.1586 - val_rmse: 0.2160 - val_smape: 0.3916

Epoch 23/128

1916/1916 - 8s - 4ms/step - ia: 0.8148 - loss: 0.1384 - mae: 0.2545 - rmse: 0.3463 - smape: 0.5597 - val_ia: 0.6561 - val_loss: 0.0808 - val_mae: 0.1576 - val_rmse: 0.2140 - val_smape: 0.3879

Epoch 24/128

1916/1916 - 5s - 3ms/step - ia: 0.8161 - loss: 0.1376 - mae: 0.2531 - rmse: 0.3457 - smape: 0.5552 - val_ia: 0.6586 - val_loss: 0.0799 - val_mae: 0.1562 - val_rmse: 0.2130 - val_smape: 0.3858

Epoch 25/128

1916/1916 - 7s - 4ms/step - ia: 0.8178 - loss: 0.1363 - mae: 0.2509 - rmse: 0.3437 - smape: 0.5511 - val_ia: 0.6605 - val_loss: 0.0791 - val_mae: 0.1553 - val_rmse: 0.2119 - val_smape: 0.3840

Epoch 26/128

1916/1916 - 8s - 4ms/step - ia: 0.8183 - loss: 0.1364 - mae: 0.2506 - rmse: 0.3438 - smape: 0.5503 - val_ia: 0.6630 - val_loss: 0.0786 - val_mae: 0.1541 - val_rmse: 0.2112 - val_smape: 0.3818

Epoch 27/128

1916/1916 - 18s - 9ms/step - ia: 0.8215 - loss: 0.1329 - mae: 0.2463 - rmse: 0.3382 - smape: 0.5427 - val_ia: 0.6644 - val_loss: 0.0783 - val_mae: 0.1536 - val_rmse: 0.2103 - val_smape: 0.3799

Epoch 28/128

1916/1916 - 18s - 10ms/step - ia: 0.8241 - loss: 0.1305 - mae: 0.2434 - rmse: 0.3351 - smape: 0.5385 - val_ia: 0.6661 - val_loss: 0.0776 - val_mae: 0.1527 - val_rmse: 0.2094 - val_smape: 0.3779

Epoch 29/128

1916/1916 - 20s - 10ms/step - ia: 0.8235 - loss: 0.1309 - mae: 0.2443 - rmse: 0.3356 - smape: 0.5390 - val_ia: 0.6669 - val_loss: 0.0769 - val_mae: 0.1518 - val_rmse: 0.2088 - val_smape: 0.3777

Epoch 30/128

1916/1916 - 10s - 5ms/step - ia: 0.8258 - loss: 0.1303 - mae: 0.2421 - rmse: 0.3346 - smape: 0.5351 - val_ia: 0.6636 - val_loss: 0.0777 - val_mae: 0.1531 - val_rmse: 0.2095 - val_smape: 0.3784

Epoch 31/128

1916/1916 - 9s - 5ms/step - ia: 0.8250 - loss: 0.1293 - mae: 0.2410 - rmse: 0.3328 - smape: 0.5363 - val_ia: 0.6689 - val_loss: 0.0763 - val_mae: 0.1506 - val_rmse: 0.2069 - val_smape: 0.3750

Epoch 32/128

1916/1916 - 6s - 3ms/step - ia: 0.8288 - loss: 0.1270 - mae: 0.2376 - rmse: 0.3286 - smape: 0.5286 - val_ia: 0.6714 - val_loss: 0.0758 - val_mae: 0.1498 - val_rmse: 0.2060 - val_smape: 0.3736

Epoch 33/128

1916/1916 - 15s - 8ms/step - ia: 0.8283 - loss: 0.1266 - mae: 0.2370 - rmse: 0.3285 - smape: 0.5256 - val_ia: 0.6730 - val_loss: 0.0752 - val_mae: 0.1489 - val_rmse: 0.2050 - val_smape: 0.3711

Epoch 34/128

1916/1916 - 9s - 4ms/step - ia: 0.8289 - loss: 0.1243 - mae: 0.2355 - rmse: 0.3251 - smape: 0.5260 - val_ia: 0.6739 - val_loss: 0.0750 - val_mae: 0.1485 - val_rmse: 0.2044 - val_smape: 0.3707

Epoch 35/128

1916/1916 - 6s - 3ms/step - ia: 0.8299 - loss: 0.1255 - mae: 0.2356 - rmse: 0.3264 - smape: 0.5246 - val_ia: 0.6729 - val_loss: 0.0745 - val_mae: 0.1480 - val_rmse: 0.2043 - val_smape: 0.3691

Epoch 36/128

1916/1916 - 6s - 3ms/step - ia: 0.8319 - loss: 0.1206 - mae: 0.2313 - rmse: 0.3208 - smape: 0.5199 - val_ia: 0.6729 - val_loss: 0.0737 - val_mae: 0.1477 - val_rmse: 0.2042 - val_smape: 0.3699

Epoch 37/128

1916/1916 - 13s - 7ms/step - ia: 0.8315 - loss: 0.1238 - mae: 0.2325 - rmse: 0.3240 - smape: 0.5176 - val_ia: 0.6768 - val_loss: 0.0734 - val_mae: 0.1467 - val_rmse: 0.2025 - val_smape: 0.3684

Epoch 38/128

1916/1916 - 8s - 4ms/step - ia: 0.8321 - loss: 0.1218 - mae: 0.2309 - rmse: 0.3209 - smape: 0.5151 - val_ia: 0.6773 - val_loss: 0.0731 - val_mae: 0.1464 - val_rmse: 0.2017 - val_smape: 0.3674

Epoch 39/128

1916/1916 - 7s - 3ms/step - ia: 0.8340 - loss: 0.1204 - mae: 0.2292 - rmse: 0.3189 - smape: 0.5126 - val_ia: 0.6759 - val_loss: 0.0730 - val_mae: 0.1461 - val_rmse: 0.2019 - val_smape: 0.3669

Epoch 40/128

1916/1916 - 12s - 6ms/step - ia: 0.8340 - loss: 0.1189 - mae: 0.2283 - rmse: 0.3173 - smape: 0.5128 - val_ia: 0.6803 - val_loss: 0.0723 - val_mae: 0.1449 - val_rmse: 0.2006 - val_smape: 0.3652

Epoch 41/128

1916/1916 - 6s - 3ms/step - ia: 0.8340 - loss: 0.1197 - mae: 0.2285 - rmse: 0.3182 - smape: 0.5108 - val_ia: 0.6777 - val_loss: 0.0725 - val_mae: 0.1455 - val_rmse: 0.2012 - val_smape: 0.3653

Epoch 42/128

1916/1916 - 7s - 4ms/step - ia: 0.8359 - loss: 0.1163 - mae: 0.2248 - rmse: 0.3134 - smape: 0.5063 - val_ia: 0.6748 - val_loss: 0.0717 - val_mae: 0.1455 - val_rmse: 0.2018 - val_smape: 0.3664

Epoch 43/128

1916/1916 - 12s - 6ms/step - ia: 0.8356 - loss: 0.1173 - mae: 0.2270 - rmse: 0.3158 - smape: 0.5120 - val_ia: 0.6802 - val_loss: 0.0713 - val_mae: 0.1439 - val_rmse: 0.1997 - val_smape: 0.3634

Epoch 44/128

1916/1916 - 9s - 5ms/step - ia: 0.8376 - loss: 0.1155 - mae: 0.2236 - rmse: 0.3119 - smape: 0.5033 - val_ia: 0.6788 - val_loss: 0.0713 - val_mae: 0.1443 - val_rmse: 0.2000 - val_smape: 0.3641

Epoch 45/128

1916/1916 - 8s - 4ms/step - ia: 0.8382 - loss: 0.1154 - mae: 0.2237 - rmse: 0.3122 - smape: 0.5030 - val_ia: 0.6805 - val_loss: 0.0707 - val_mae: 0.1434 - val_rmse: 0.1988 - val_smape: 0.3626

Epoch 46/128

1916/1916 - 5s - 2ms/step - ia: 0.8368 - loss: 0.1163 - mae: 0.2240 - rmse: 0.3129 - smape: 0.5017 - val_ia: 0.6803 - val_loss: 0.0702 - val_mae: 0.1430 - val_rmse: 0.1992 - val_smape: 0.3618

Epoch 47/128

1916/1916 - 4s - 2ms/step - ia: 0.8395 - loss: 0.1132 - mae: 0.2213 - rmse: 0.3082 - smape: 0.5008 - val_ia: 0.6769 - val_loss: 0.0702 - val_mae: 0.1436 - val_rmse: 0.1993 - val_smape: 0.3630

Epoch 48/128

1916/1916 - 9s - 5ms/step - ia: 0.8386 - loss: 0.1136 - mae: 0.2210 - rmse: 0.3095 - smape: 0.5020 - val_ia: 0.6828 - val_loss: 0.0696 - val_mae: 0.1419 - val_rmse: 0.1975 - val_smape: 0.3599

Epoch 49/128

1916/1916 - 7s - 4ms/step - ia: 0.8392 - loss: 0.1120 - mae: 0.2208 - rmse: 0.3083 - smape: 0.4987 - val_ia: 0.6827 - val_loss: 0.0691 - val_mae: 0.1418 - val_rmse: 0.1967 - val_smape: 0.3605

Epoch 50/128

1916/1916 - 14s - 7ms/step - ia: 0.8400 - loss: 0.1125 - mae: 0.2198 - rmse: 0.3067 - smape: 0.4960 - val_ia: 0.6735 - val_loss: 0.0693 - val_mae: 0.1435 - val_rmse: 0.1992 - val_smape: 0.3626

Epoch 51/128

1916/1916 - 10s - 5ms/step - ia: 0.8408 - loss: 0.1117 - mae: 0.2196 - rmse: 0.3073 - smape: 0.4996 - val_ia: 0.6847 - val_loss: 0.0686 - val_mae: 0.1408 - val_rmse: 0.1964 - val_smape: 0.3587

Epoch 52/128

1916/1916 - 8s - 4ms/step - ia: 0.8415 - loss: 0.1102 - mae: 0.2183 - rmse: 0.3042 - smape: 0.4987 - val_ia: 0.6811 - val_loss: 0.0683 - val_mae: 0.1412 - val_rmse: 0.1967 - val_smape: 0.3593

Epoch 53/128

1916/1916 - 10s - 5ms/step - ia: 0.8414 - loss: 0.1105 - mae: 0.2173 - rmse: 0.3044 - smape: 0.4932 - val_ia: 0.6802 - val_loss: 0.0682 - val_mae: 0.1414 - val_rmse: 0.1966 - val_smape: 0.3596

Epoch 54/128

1916/1916 - 5s - 3ms/step - ia: 0.8430 - loss: 0.1104 - mae: 0.2168 - rmse: 0.3031 - smape: 0.4898 - val_ia: 0.6868 - val_loss: 0.0679 - val_mae: 0.1399 - val_rmse: 0.1951 - val_smape: 0.3567

Epoch 55/128

1916/1916 - 6s - 3ms/step - ia: 0.8432 - loss: 0.1094 - mae: 0.2164 - rmse: 0.3034 - smape: 0.4913 - val_ia: 0.6827 - val_loss: 0.0678 - val_mae: 0.1404 - val_rmse: 0.1952 - val_smape: 0.3585

Epoch 56/128

1916/1916 - 13s - 7ms/step - ia: 0.8432 - loss: 0.1100 - mae: 0.2165 - rmse: 0.3034 - smape: 0.4926 - val_ia: 0.6824 - val_loss: 0.0675 - val_mae: 0.1402 - val_rmse: 0.1950 - val_smape: 0.3579

Epoch 57/128

1916/1916 - 6s - 3ms/step - ia: 0.8435 - loss: 0.1082 - mae: 0.2149 - rmse: 0.3005 - smape: 0.4900 - val_ia: 0.6815 - val_loss: 0.0673 - val_mae: 0.1401 - val_rmse: 0.1955 - val_smape: 0.3571

Epoch 58/128

1916/1916 - 4s - 2ms/step - ia: 0.8453 - loss: 0.1076 - mae: 0.2129 - rmse: 0.3000 - smape: 0.4846 - val_ia: 0.6830 - val_loss: 0.0667 - val_mae: 0.1395 - val_rmse: 0.1950 - val_smape: 0.3562

Epoch 59/128

1916/1916 - 5s - 2ms/step - ia: 0.8445 - loss: 0.1070 - mae: 0.2128 - rmse: 0.2990 - smape: 0.4872 - val_ia: 0.6867 - val_loss: 0.0666 - val_mae: 0.1385 - val_rmse: 0.1938 - val_smape: 0.3548

Epoch 60/128

1916/1916 - 7s - 4ms/step - ia: 0.8444 - loss: 0.1072 - mae: 0.2132 - rmse: 0.2995 - smape: 0.4864 - val_ia: 0.6877 - val_loss: 0.0662 - val_mae: 0.1383 - val_rmse: 0.1935 - val_smape: 0.3550

Epoch 61/128

1916/1916 - 10s - 5ms/step - ia: 0.8459 - loss: 0.1056 - mae: 0.2115 - rmse: 0.2963 - smape: 0.4841 - val_ia: 0.6843 - val_loss: 0.0662 - val_mae: 0.1387 - val_rmse: 0.1936 - val_smape: 0.3558

Epoch 62/128

1916/1916 - 6s - 3ms/step - ia: 0.8456 - loss: 0.1066 - mae: 0.2124 - rmse: 0.2978 - smape: 0.4870 - val_ia: 0.6858 - val_loss: 0.0659 - val_mae: 0.1382 - val_rmse: 0.1935 - val_smape: 0.3547

Epoch 63/128

1916/1916 - 14s - 7ms/step - ia: 0.8460 - loss: 0.1054 - mae: 0.2112 - rmse: 0.2957 - smape: 0.4842 - val_ia: 0.6833 - val_loss: 0.0658 - val_mae: 0.1386 - val_rmse: 0.1941 - val_smape: 0.3558

Epoch 64/128

1916/1916 - 5s - 3ms/step - ia: 0.8478 - loss: 0.1042 - mae: 0.2097 - rmse: 0.2945 - smape: 0.4817 - val_ia: 0.6860 - val_loss: 0.0654 - val_mae: 0.1377 - val_rmse: 0.1926 - val_smape: 0.3547

Epoch 65/128

1916/1916 - 3s - 2ms/step - ia: 0.8479 - loss: 0.1046 - mae: 0.2095 - rmse: 0.2952 - smape: 0.4806 - val_ia: 0.6838 - val_loss: 0.0653 - val_mae: 0.1381 - val_rmse: 0.1930 - val_smape: 0.3549

Epoch 66/128

1916/1916 - 7s - 4ms/step - ia: 0.8468 - loss: 0.1048 - mae: 0.2104 - rmse: 0.2956 - smape: 0.4837 - val_ia: 0.6815 - val_loss: 0.0653 - val_mae: 0.1384 - val_rmse: 0.1932 - val_smape: 0.3550

Epoch 67/128

1916/1916 - 9s - 5ms/step - ia: 0.8479 - loss: 0.1038 - mae: 0.2094 - rmse: 0.2934 - smape: 0.4816 - val_ia: 0.6887 - val_loss: 0.0647 - val_mae: 0.1368 - val_rmse: 0.1918 - val_smape: 0.3527

Epoch 68/128

1916/1916 - 6s - 3ms/step - ia: 0.8467 - loss: 0.1042 - mae: 0.2097 - rmse: 0.2944 - smape: 0.4806 - val_ia: 0.6829 - val_loss: 0.0646 - val_mae: 0.1379 - val_rmse: 0.1930 - val_smape: 0.3549

Epoch 69/128

1916/1916 - 12s - 6ms/step - ia: 0.8487 - loss: 0.1024 - mae: 0.2076 - rmse: 0.2911 - smape: 0.4788 - val_ia: 0.6786 - val_loss: 0.0650 - val_mae: 0.1391 - val_rmse: 0.1943 - val_smape: 0.3577

Epoch 70/128

1916/1916 - 6s - 3ms/step - ia: 0.8494 - loss: 0.1031 - mae: 0.2076 - rmse: 0.2927 - smape: 0.4796 - val_ia: 0.6866 - val_loss: 0.0643 - val_mae: 0.1369 - val_rmse: 0.1916 - val_smape: 0.3530

Epoch 71/128

1916/1916 - 8s - 4ms/step - ia: 0.8493 - loss: 0.1020 - mae: 0.2068 - rmse: 0.2914 - smape: 0.4737 - val_ia: 0.6813 - val_loss: 0.0641 - val_mae: 0.1378 - val_rmse: 0.1924 - val_smape: 0.3552

Epoch 72/128

1916/1916 - 6s - 3ms/step - ia: 0.8494 - loss: 0.1024 - mae: 0.2064 - rmse: 0.2916 - smape: 0.4749 - val_ia: 0.6824 - val_loss: 0.0640 - val_mae: 0.1373 - val_rmse: 0.1920 - val_smape: 0.3538

Epoch 73/128

1916/1916 - 7s - 3ms/step - ia: 0.8497 - loss: 0.1012 - mae: 0.2060 - rmse: 0.2893 - smape: 0.4771 - val_ia: 0.6832 - val_loss: 0.0639 - val_mae: 0.1373 - val_rmse: 0.1923 - val_smape: 0.3546

Epoch 74/128

1916/1916 - 11s - 6ms/step - ia: 0.8508 - loss: 0.0995 - mae: 0.2045 - rmse: 0.2877 - smape: 0.4735 - val_ia: 0.6878 - val_loss: 0.0636 - val_mae: 0.1360 - val_rmse: 0.1910 - val_smape: 0.3516

Epoch 75/128

1916/1916 - 10s - 5ms/step - ia: 0.8507 - loss: 0.0999 - mae: 0.2042 - rmse: 0.2879 - smape: 0.4739 - val_ia: 0.6823 - val_loss: 0.0635 - val_mae: 0.1369 - val_rmse: 0.1915 - val_smape: 0.3532

Epoch 76/128

1916/1916 - 9s - 5ms/step - ia: 0.8507 - loss: 0.1000 - mae: 0.2047 - rmse: 0.2884 - smape: 0.4740 - val_ia: 0.6859 - val_loss: 0.0634 - val_mae: 0.1363 - val_rmse: 0.1909 - val_smape: 0.3524

Epoch 77/128

1916/1916 - 9s - 4ms/step - ia: 0.8524 - loss: 0.0993 - mae: 0.2023 - rmse: 0.2863 - smape: 0.4696 - val_ia: 0.6843 - val_loss: 0.0631 - val_mae: 0.1362 - val_rmse: 0.1908 - val_smape: 0.3527

Epoch 78/128

1916/1916 - 7s - 4ms/step - ia: 0.8533 - loss: 0.0984 - mae: 0.2014 - rmse: 0.2851 - smape: 0.4700 - val_ia: 0.6826 - val_loss: 0.0633 - val_mae: 0.1369 - val_rmse: 0.1915 - val_smape: 0.3538

Epoch 79/128

1916/1916 - 12s - 6ms/step - ia: 0.8514 - loss: 0.0997 - mae: 0.2037 - rmse: 0.2880 - smape: 0.4728 - val_ia: 0.6799 - val_loss: 0.0629 - val_mae: 0.1370 - val_rmse: 0.1916 - val_smape: 0.3543

Epoch 80/128

1916/1916 - 9s - 5ms/step - ia: 0.8525 - loss: 0.0986 - mae: 0.2011 - rmse: 0.2852 - smape: 0.4695 - val_ia: 0.6862 - val_loss: 0.0628 - val_mae: 0.1357 - val_rmse: 0.1904 - val_smape: 0.3520

Epoch 81/128

1916/1916 - 6s - 3ms/step - ia: 0.8529 - loss: 0.0970 - mae: 0.2009 - rmse: 0.2833 - smape: 0.4717 - val_ia: 0.6834 - val_loss: 0.0625 - val_mae: 0.1360 - val_rmse: 0.1903 - val_smape: 0.3524

Epoch 82/128

1916/1916 - 11s - 6ms/step - ia: 0.8541 - loss: 0.0987 - mae: 0.2007 - rmse: 0.2841 - smape: 0.4675 - val_ia: 0.6867 - val_loss: 0.0624 - val_mae: 0.1354 - val_rmse: 0.1896 - val_smape: 0.3519

Epoch 83/128

1916/1916 - 12s - 6ms/step - ia: 0.8533 - loss: 0.0974 - mae: 0.2013 - rmse: 0.2839 - smape: 0.4690 - val_ia: 0.6867 - val_loss: 0.0623 - val_mae: 0.1354 - val_rmse: 0.1893 - val_smape: 0.3527

Epoch 84/128

1916/1916 - 16s - 8ms/step - ia: 0.8542 - loss: 0.0965 - mae: 0.1998 - rmse: 0.2826 - smape: 0.4691 - val_ia: 0.6743 - val_loss: 0.0627 - val_mae: 0.1382 - val_rmse: 0.1929 - val_smape: 0.3570

Epoch 85/128

1916/1916 - 9s - 5ms/step - ia: 0.8547 - loss: 0.0961 - mae: 0.1990 - rmse: 0.2814 - smape: 0.4631 - val_ia: 0.6804 - val_loss: 0.0622 - val_mae: 0.1365 - val_rmse: 0.1906 - val_smape: 0.3533

Epoch 86/128

1916/1916 - 8s - 4ms/step - ia: 0.8540 - loss: 0.0977 - mae: 0.1997 - rmse: 0.2825 - smape: 0.4661 - val_ia: 0.6818 - val_loss: 0.0620 - val_mae: 0.1360 - val_rmse: 0.1902 - val_smape: 0.3529

Epoch 87/128

1916/1916 - 4s - 2ms/step - ia: 0.8548 - loss: 0.0956 - mae: 0.1987 - rmse: 0.2804 - smape: 0.4670 - val_ia: 0.6806 - val_loss: 0.0618 - val_mae: 0.1360 - val_rmse: 0.1903 - val_smape: 0.3526

Epoch 88/128

1916/1916 - 7s - 4ms/step - ia: 0.8547 - loss: 0.0960 - mae: 0.1983 - rmse: 0.2810 - smape: 0.4641 - val_ia: 0.6840 - val_loss: 0.0616 - val_mae: 0.1352 - val_rmse: 0.1896 - val_smape: 0.3514

Epoch 89/128

1916/1916 - 11s - 6ms/step - ia: 0.8561 - loss: 0.0950 - mae: 0.1973 - rmse: 0.2786 - smape: 0.4636 - val_ia: 0.6852 - val_loss: 0.0617 - val_mae: 0.1351 - val_rmse: 0.1896 - val_smape: 0.3511

Epoch 90/128

1916/1916 - 9s - 5ms/step - ia: 0.8556 - loss: 0.0950 - mae: 0.1975 - rmse: 0.2798 - smape: 0.4632 - val_ia: 0.6811 - val_loss: 0.0615 - val_mae: 0.1358 - val_rmse: 0.1903 - val_smape: 0.3524

Epoch 91/128

1916/1916 - 9s - 4ms/step - ia: 0.8556 - loss: 0.0959 - mae: 0.1984 - rmse: 0.2808 - smape: 0.4641 - val_ia: 0.6777 - val_loss: 0.0616 - val_mae: 0.1367 - val_rmse: 0.1903 - val_smape: 0.3544

Epoch 92/128

1916/1916 - 8s - 4ms/step - ia: 0.8558 - loss: 0.0948 - mae: 0.1974 - rmse: 0.2787 - smape: 0.4651 - val_ia: 0.6720 - val_loss: 0.0618 - val_mae: 0.1381 - val_rmse: 0.1921 - val_smape: 0.3564

Epoch 93/128

1916/1916 - 10s - 5ms/step - ia: 0.8561 - loss: 0.0952 - mae: 0.1969 - rmse: 0.2802 - smape: 0.4631 - val_ia: 0.6817 - val_loss: 0.0612 - val_mae: 0.1354 - val_rmse: 0.1894 - val_smape: 0.3522

Epoch 94/128

1916/1916 - 7s - 4ms/step - ia: 0.8558 - loss: 0.0953 - mae: 0.1963 - rmse: 0.2793 - smape: 0.4581 - val_ia: 0.6787 - val_loss: 0.0611 - val_mae: 0.1362 - val_rmse: 0.1905 - val_smape: 0.3541

Epoch 95/128

1916/1916 - 9s - 5ms/step - ia: 0.8564 - loss: 0.0946 - mae: 0.1964 - rmse: 0.2786 - smape: 0.4617 - val_ia: 0.6840 - val_loss: 0.0612 - val_mae: 0.1353 - val_rmse: 0.1892 - val_smape: 0.3522

Epoch 96/128

1916/1916 - 6s - 3ms/step - ia: 0.8569 - loss: 0.0936 - mae: 0.1956 - rmse: 0.2777 - smape: 0.4624 - val_ia: 0.6775 - val_loss: 0.0612 - val_mae: 0.1364 - val_rmse: 0.1908 - val_smape: 0.3544

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1916/1916 - 13s - 7ms/step - ia: 0.6913 - loss: 0.3331 - mae: 0.4274 - rmse: 0.5493 - smape: 0.8213 - val_ia: 0.5857 - val_loss: 0.1003 - val_mae: 0.1919 - val_rmse: 0.2482 - val_smape: 0.4542

Epoch 2/128

1916/1916 - 7s - 4ms/step - ia: 0.7818 - loss: 0.1765 - mae: 0.3004 - rmse: 0.3973 - smape: 0.6368 - val_ia: 0.6291 - val_loss: 0.0919 - val_mae: 0.1748 - val_rmse: 0.2285 - val_smape: 0.4129

Epoch 3/128

1916/1916 - 11s - 6ms/step - ia: 0.8108 - loss: 0.1442 - mae: 0.2603 - rmse: 0.3543 - smape: 0.5675 - val_ia: 0.6540 - val_loss: 0.0792 - val_mae: 0.1570 - val_rmse: 0.2135 - val_smape: 0.3872

Epoch 4/128

1916/1916 - 9s - 5ms/step - ia: 0.8241 - loss: 0.1310 - mae: 0.2436 - rmse: 0.3359 - smape: 0.5368 - val_ia: 0.6676 - val_loss: 0.0749 - val_mae: 0.1506 - val_rmse: 0.2051 - val_smape: 0.3749

Epoch 5/128

1916/1916 - 7s - 4ms/step - ia: 0.8325 - loss: 0.1201 - mae: 0.2311 - rmse: 0.3189 - smape: 0.5183 - val_ia: 0.6715 - val_loss: 0.0714 - val_mae: 0.1466 - val_rmse: 0.2005 - val_smape: 0.3673

Epoch 6/128

1916/1916 - 15s - 8ms/step - ia: 0.8394 - loss: 0.1122 - mae: 0.2209 - rmse: 0.3080 - smape: 0.5016 - val_ia: 0.6766 - val_loss: 0.0689 - val_mae: 0.1436 - val_rmse: 0.1990 - val_smape: 0.3641

Epoch 7/128

1916/1916 - 19s - 10ms/step - ia: 0.8440 - loss: 0.1058 - mae: 0.2141 - rmse: 0.2988 - smape: 0.4887 - val_ia: 0.6691 - val_loss: 0.0668 - val_mae: 0.1432 - val_rmse: 0.1973 - val_smape: 0.3662

Epoch 8/128

1916/1916 - 7s - 3ms/step - ia: 0.8487 - loss: 0.1024 - mae: 0.2077 - rmse: 0.2914 - smape: 0.4784 - val_ia: 0.6635 - val_loss: 0.0641 - val_mae: 0.1422 - val_rmse: 0.1963 - val_smape: 0.3629

Epoch 9/128

1916/1916 - 6s - 3ms/step - ia: 0.8518 - loss: 0.0993 - mae: 0.2029 - rmse: 0.2869 - smape: 0.4712 - val_ia: 0.6750 - val_loss: 0.0626 - val_mae: 0.1382 - val_rmse: 0.1915 - val_smape: 0.3557

Epoch 10/128

1916/1916 - 6s - 3ms/step - ia: 0.8536 - loss: 0.0964 - mae: 0.2004 - rmse: 0.2823 - smape: 0.4698 - val_ia: 0.6750 - val_loss: 0.0616 - val_mae: 0.1374 - val_rmse: 0.1908 - val_smape: 0.3559

Epoch 11/128

1916/1916 - 13s - 7ms/step - ia: 0.8569 - loss: 0.0938 - mae: 0.1957 - rmse: 0.2769 - smape: 0.4609 - val_ia: 0.6799 - val_loss: 0.0602 - val_mae: 0.1354 - val_rmse: 0.1895 - val_smape: 0.3533

Epoch 12/128

1916/1916 - 8s - 4ms/step - ia: 0.8597 - loss: 0.0902 - mae: 0.1921 - rmse: 0.2720 - smape: 0.4550 - val_ia: 0.6353 - val_loss: 0.0624 - val_mae: 0.1499 - val_rmse: 0.2007 - val_smape: 0.3763

Epoch 13/128

1916/1916 - 9s - 5ms/step - ia: 0.8585 - loss: 0.0899 - mae: 0.1914 - rmse: 0.2715 - smape: 0.4552 - val_ia: 0.6640 - val_loss: 0.0613 - val_mae: 0.1410 - val_rmse: 0.1940 - val_smape: 0.3641

Epoch 14/128

1916/1916 - 8s - 4ms/step - ia: 0.8620 - loss: 0.0868 - mae: 0.1864 - rmse: 0.2659 - smape: 0.4461 - val_ia: 0.6676 - val_loss: 0.0598 - val_mae: 0.1386 - val_rmse: 0.1909 - val_smape: 0.3595

Epoch 15/128

1916/1916 - 8s - 4ms/step - ia: 0.8633 - loss: 0.0855 - mae: 0.1856 - rmse: 0.2644 - smape: 0.4446 - val_ia: 0.6753 - val_loss: 0.0591 - val_mae: 0.1372 - val_rmse: 0.1890 - val_smape: 0.3658

Epoch 16/128

1916/1916 - 9s - 5ms/step - ia: 0.8650 - loss: 0.0841 - mae: 0.1829 - rmse: 0.2615 - smape: 0.4368 - val_ia: 0.6828 - val_loss: 0.0594 - val_mae: 0.1355 - val_rmse: 0.1906 - val_smape: 0.3530

Epoch 17/128

1916/1916 - 8s - 4ms/step - ia: 0.8671 - loss: 0.0828 - mae: 0.1808 - rmse: 0.2599 - smape: 0.4352 - val_ia: 0.6736 - val_loss: 0.0577 - val_mae: 0.1357 - val_rmse: 0.1876 - val_smape: 0.3568

Epoch 18/128

1916/1916 - 6s - 3ms/step - ia: 0.8678 - loss: 0.0820 - mae: 0.1793 - rmse: 0.2573 - smape: 0.4327 - val_ia: 0.6754 - val_loss: 0.0591 - val_mae: 0.1384 - val_rmse: 0.1894 - val_smape: 0.3644

Epoch 19/128

1916/1916 - 5s - 3ms/step - ia: 0.8690 - loss: 0.0818 - mae: 0.1781 - rmse: 0.2574 - smape: 0.4290 - val_ia: 0.6454 - val_loss: 0.0592 - val_mae: 0.1451 - val_rmse: 0.1969 - val_smape: 0.3721

Epoch 20/128

1916/1916 - 8s - 4ms/step - ia: 0.8698 - loss: 0.0808 - mae: 0.1768 - rmse: 0.2550 - smape: 0.4266 - val_ia: 0.6719 - val_loss: 0.0573 - val_mae: 0.1357 - val_rmse: 0.1877 - val_smape: 0.3558

Epoch 21/128

1916/1916 - 10s - 5ms/step - ia: 0.8707 - loss: 0.0790 - mae: 0.1752 - rmse: 0.2532 - smape: 0.4224 - val_ia: 0.6909 - val_loss: 0.0564 - val_mae: 0.1310 - val_rmse: 0.1843 - val_smape: 0.3503

Epoch 22/128

1916/1916 - 9s - 5ms/step - ia: 0.8714 - loss: 0.0788 - mae: 0.1745 - rmse: 0.2527 - smape: 0.4211 - val_ia: 0.6798 - val_loss: 0.0581 - val_mae: 0.1350 - val_rmse: 0.1886 - val_smape: 0.3560

Epoch 23/128

1916/1916 - 11s - 6ms/step - ia: 0.8735 - loss: 0.0784 - mae: 0.1725 - rmse: 0.2502 - smape: 0.4155 - val_ia: 0.6526 - val_loss: 0.0580 - val_mae: 0.1424 - val_rmse: 0.1939 - val_smape: 0.3669

Epoch 24/128

1916/1916 - 12s - 6ms/step - ia: 0.8739 - loss: 0.0776 - mae: 0.1720 - rmse: 0.2499 - smape: 0.4177 - val_ia: 0.6707 - val_loss: 0.0566 - val_mae: 0.1373 - val_rmse: 0.1882 - val_smape: 0.3634

Epoch 25/128

1916/1916 - 8s - 4ms/step - ia: 0.8748 - loss: 0.0769 - mae: 0.1708 - rmse: 0.2478 - smape: 0.4139 - val_ia: 0.6595 - val_loss: 0.0568 - val_mae: 0.1387 - val_rmse: 0.1911 - val_smape: 0.3616

Epoch 26/128

1916/1916 - 8s - 4ms/step - ia: 0.8749 - loss: 0.0765 - mae: 0.1697 - rmse: 0.2472 - smape: 0.4111 - val_ia: 0.6835 - val_loss: 0.0557 - val_mae: 0.1315 - val_rmse: 0.1853 - val_smape: 0.3501

Epoch 27/128

1916/1916 - 5s - 3ms/step - ia: 0.8755 - loss: 0.0756 - mae: 0.1696 - rmse: 0.2469 - smape: 0.4126 - val_ia: 0.6772 - val_loss: 0.0556 - val_mae: 0.1331 - val_rmse: 0.1852 - val_smape: 0.3500

Epoch 28/128

1916/1916 - 5s - 2ms/step - ia: 0.8768 - loss: 0.0758 - mae: 0.1679 - rmse: 0.2459 - smape: 0.4066 - val_ia: 0.6992 - val_loss: 0.0553 - val_mae: 0.1291 - val_rmse: 0.1827 - val_smape: 0.3454

Epoch 29/128

1916/1916 - 5s - 3ms/step - ia: 0.8763 - loss: 0.0755 - mae: 0.1674 - rmse: 0.2451 - smape: 0.4049 - val_ia: 0.6903 - val_loss: 0.0550 - val_mae: 0.1298 - val_rmse: 0.1835 - val_smape: 0.3458

Epoch 30/128

1916/1916 - 8s - 4ms/step - ia: 0.8779 - loss: 0.0738 - mae: 0.1663 - rmse: 0.2428 - smape: 0.4051 - val_ia: 0.6883 - val_loss: 0.0561 - val_mae: 0.1331 - val_rmse: 0.1847 - val_smape: 0.3504

Epoch 31/128

1916/1916 - 8s - 4ms/step - ia: 0.8784 - loss: 0.0738 - mae: 0.1659 - rmse: 0.2424 - smape: 0.4050 - val_ia: 0.6845 - val_loss: 0.0548 - val_mae: 0.1317 - val_rmse: 0.1842 - val_smape: 0.3518

Epoch 32/128

1916/1916 - 9s - 5ms/step - ia: 0.8778 - loss: 0.0743 - mae: 0.1661 - rmse: 0.2434 - smape: 0.4028 - val_ia: 0.6799 - val_loss: 0.0555 - val_mae: 0.1331 - val_rmse: 0.1855 - val_smape: 0.3500

Epoch 33/128

1916/1916 - 11s - 6ms/step - ia: 0.8777 - loss: 0.0756 - mae: 0.1671 - rmse: 0.2449 - smape: 0.4032 - val_ia: 0.6797 - val_loss: 0.0548 - val_mae: 0.1331 - val_rmse: 0.1847 - val_smape: 0.3522

Epoch 34/128

1916/1916 - 9s - 5ms/step - ia: 0.8780 - loss: 0.0741 - mae: 0.1662 - rmse: 0.2429 - smape: 0.4040 - val_ia: 0.6697 - val_loss: 0.0557 - val_mae: 0.1362 - val_rmse: 0.1874 - val_smape: 0.3554

Epoch 35/128

1916/1916 - 10s - 5ms/step - ia: 0.8789 - loss: 0.0733 - mae: 0.1649 - rmse: 0.2417 - smape: 0.4001 - val_ia: 0.6831 - val_loss: 0.0551 - val_mae: 0.1321 - val_rmse: 0.1846 - val_smape: 0.3496

Epoch 36/128

1916/1916 - 11s - 6ms/step - ia: 0.8794 - loss: 0.0733 - mae: 0.1645 - rmse: 0.2418 - smape: 0.4009 - val_ia: 0.6676 - val_loss: 0.0551 - val_mae: 0.1352 - val_rmse: 0.1871 - val_smape: 0.3538

Epoch 37/128

1916/1916 - 10s - 5ms/step - ia: 0.8797 - loss: 0.0736 - mae: 0.1646 - rmse: 0.2416 - smape: 0.3997 - val_ia: 0.6724 - val_loss: 0.0565 - val_mae: 0.1370 - val_rmse: 0.1883 - val_smape: 0.3569

Epoch 38/128

1916/1916 - 11s - 6ms/step - ia: 0.8795 - loss: 0.0727 - mae: 0.1638 - rmse: 0.2417 - smape: 0.3993 - val_ia: 0.6809 - val_loss: 0.0547 - val_mae: 0.1324 - val_rmse: 0.1846 - val_smape: 0.3502

Epoch 39/128

1916/1916 - 11s - 6ms/step - ia: 0.8800 - loss: 0.0728 - mae: 0.1641 - rmse: 0.2405 - smape: 0.3983 - val_ia: 0.6932 - val_loss: 0.0550 - val_mae: 0.1314 - val_rmse: 0.1836 - val_smape: 0.3475

Epoch 40/128

1916/1916 - 7s - 4ms/step - ia: 0.8799 - loss: 0.0736 - mae: 0.1645 - rmse: 0.2414 - smape: 0.4001 - val_ia: 0.6988 - val_loss: 0.0550 - val_mae: 0.1301 - val_rmse: 0.1829 - val_smape: 0.3433

Epoch 41/128

1916/1916 - 5s - 3ms/step - ia: 0.8799 - loss: 0.0732 - mae: 0.1636 - rmse: 0.2413 - smape: 0.3975 - val_ia: 0.6859 - val_loss: 0.0551 - val_mae: 0.1320 - val_rmse: 0.1841 - val_smape: 0.3476

Epoch 42/128

1916/1916 - 4s - 2ms/step - ia: 0.8804 - loss: 0.0723 - mae: 0.1634 - rmse: 0.2403 - smape: 0.3976 - val_ia: 0.6943 - val_loss: 0.0548 - val_mae: 0.1304 - val_rmse: 0.1827 - val_smape: 0.3461

Epoch 43/128

1916/1916 - 5s - 3ms/step - ia: 0.8807 - loss: 0.0725 - mae: 0.1637 - rmse: 0.2402 - smape: 0.3976 - val_ia: 0.6671 - val_loss: 0.0562 - val_mae: 0.1374 - val_rmse: 0.1891 - val_smape: 0.3566

Epoch 44/128

1916/1916 - 6s - 3ms/step - ia: 0.8794 - loss: 0.0722 - mae: 0.1637 - rmse: 0.2402 - smape: 0.3982 - val_ia: 0.6825 - val_loss: 0.0561 - val_mae: 0.1347 - val_rmse: 0.1861 - val_smape: 0.3499

Epoch 45/128

1916/1916 - 6s - 3ms/step - ia: 0.8796 - loss: 0.0737 - mae: 0.1640 - rmse: 0.2425 - smape: 0.3991 - val_ia: 0.6808 - val_loss: 0.0542 - val_mae: 0.1318 - val_rmse: 0.1836 - val_smape: 0.3483

Epoch 46/128

1916/1916 - 6s - 3ms/step - ia: 0.8808 - loss: 0.0727 - mae: 0.1627 - rmse: 0.2403 - smape: 0.3957 - val_ia: 0.6746 - val_loss: 0.0546 - val_mae: 0.1338 - val_rmse: 0.1853 - val_smape: 0.3518

Epoch 47/128

1916/1916 - 6s - 3ms/step - ia: 0.8809 - loss: 0.0723 - mae: 0.1629 - rmse: 0.2401 - smape: 0.3963 - val_ia: 0.6842 - val_loss: 0.0555 - val_mae: 0.1336 - val_rmse: 0.1852 - val_smape: 0.3500

Epoch 48/128

1916/1916 - 11s - 6ms/step - ia: 0.8806 - loss: 0.0711 - mae: 0.1625 - rmse: 0.2388 - smape: 0.3967 - val_ia: 0.6793 - val_loss: 0.0547 - val_mae: 0.1328 - val_rmse: 0.1846 - val_smape: 0.3508

Epoch 49/128

1916/1916 - 7s - 3ms/step - ia: 0.8816 - loss: 0.0713 - mae: 0.1620 - rmse: 0.2386 - smape: 0.3950 - val_ia: 0.6814 - val_loss: 0.0556 - val_mae: 0.1342 - val_rmse: 0.1861 - val_smape: 0.3517

Epoch 50/128

1916/1916 - 7s - 4ms/step - ia: 0.8808 - loss: 0.0723 - mae: 0.1619 - rmse: 0.2395 - smape: 0.3956 - val_ia: 0.6861 - val_loss: 0.0547 - val_mae: 0.1317 - val_rmse: 0.1835 - val_smape: 0.3478

Epoch 51/128

1916/1916 - 10s - 5ms/step - ia: 0.8819 - loss: 0.0711 - mae: 0.1617 - rmse: 0.2380 - smape: 0.3938 - val_ia: 0.6854 - val_loss: 0.0561 - val_mae: 0.1342 - val_rmse: 0.1861 - val_smape: 0.3510

Epoch 52/128

1916/1916 - 6s - 3ms/step - ia: 0.8814 - loss: 0.0714 - mae: 0.1620 - rmse: 0.2382 - smape: 0.3955 - val_ia: 0.6877 - val_loss: 0.0574 - val_mae: 0.1354 - val_rmse: 0.1889 - val_smape: 0.3549

Epoch 53/128

1916/1916 - 10s - 5ms/step - ia: 0.8813 - loss: 0.0711 - mae: 0.1622 - rmse: 0.2386 - smape: 0.3949 - val_ia: 0.6824 - val_loss: 0.0577 - val_mae: 0.1367 - val_rmse: 0.1883 - val_smape: 0.3527

Epoch 54/128

1916/1916 - 9s - 5ms/step - ia: 0.8816 - loss: 0.0716 - mae: 0.1619 - rmse: 0.2392 - smape: 0.3936 - val_ia: 0.6826 - val_loss: 0.0547 - val_mae: 0.1326 - val_rmse: 0.1840 - val_smape: 0.3499

Epoch 55/128

1916/1916 - 6s - 3ms/step - ia: 0.8824 - loss: 0.0704 - mae: 0.1607 - rmse: 0.2364 - smape: 0.3917 - val_ia: 0.6826 - val_loss: 0.0544 - val_mae: 0.1320 - val_rmse: 0.1837 - val_smape: 0.3491

Epoch 56/128

1916/1916 - 14s - 7ms/step - ia: 0.8810 - loss: 0.0715 - mae: 0.1620 - rmse: 0.2391 - smape: 0.3937 - val_ia: 0.6815 - val_loss: 0.0566 - val_mae: 0.1357 - val_rmse: 0.1866 - val_smape: 0.3509

Epoch 57/128

1916/1916 - 8s - 4ms/step - ia: 0.8817 - loss: 0.0717 - mae: 0.1622 - rmse: 0.2386 - smape: 0.3949 - val_ia: 0.6955 - val_loss: 0.0543 - val_mae: 0.1294 - val_rmse: 0.1818 - val_smape: 0.3435

Epoch 58/128

1916/1916 - 8s - 4ms/step - ia: 0.8813 - loss: 0.0717 - mae: 0.1617 - rmse: 0.2390 - smape: 0.3926 - val_ia: 0.6955 - val_loss: 0.0549 - val_mae: 0.1305 - val_rmse: 0.1831 - val_smape: 0.3457

Epoch 59/128

1916/1916 - 8s - 4ms/step - ia: 0.8818 - loss: 0.0719 - mae: 0.1617 - rmse: 0.2389 - smape: 0.3950 - val_ia: 0.6805 - val_loss: 0.0556 - val_mae: 0.1344 - val_rmse: 0.1856 - val_smape: 0.3505

Epoch 60/128

1916/1916 - 6s - 3ms/step - ia: 0.8814 - loss: 0.0710 - mae: 0.1616 - rmse: 0.2383 - smape: 0.3948 - val_ia: 0.6909 - val_loss: 0.0542 - val_mae: 0.1303 - val_rmse: 0.1828 - val_smape: 0.3473

Epoch 60: early stopping

Restoring model weights from the end of the best epoch: 45.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:10 524ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 48%|████▊     | 24/50 [1:49:43<4:03:48, 562.65s/trial, best loss: 0.03754306115671187]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 15s - 16ms/step - ia: 0.6973 - loss: 0.3476 - mae: 0.4029 - rmse: 0.5601 - smape: 0.8038 - val_ia: 0.6345 - val_loss: 0.1347 - val_mae: 0.2325 - val_rmse: 0.3098 - val_smape: 0.5415

Epoch 2/128

958/958 - 6s - 6ms/step - ia: 0.7874 - loss: 0.1843 - mae: 0.3012 - rmse: 0.4147 - smape: 0.6420 - val_ia: 0.7072 - val_loss: 0.0944 - val_mae: 0.1846 - val_rmse: 0.2587 - val_smape: 0.4480

Epoch 3/128

958/958 - 10s - 10ms/step - ia: 0.8074 - loss: 0.1536 - mae: 0.2750 - rmse: 0.3777 - smape: 0.6027 - val_ia: 0.7314 - val_loss: 0.0809 - val_mae: 0.1674 - val_rmse: 0.2388 - val_smape: 0.4162

Epoch 4/128

958/958 - 6s - 6ms/step - ia: 0.8209 - loss: 0.1351 - mae: 0.2559 - rmse: 0.3540 - smape: 0.5710 - val_ia: 0.7414 - val_loss: 0.0741 - val_mae: 0.1592 - val_rmse: 0.2296 - val_smape: 0.4028

Epoch 5/128

958/958 - 5s - 6ms/step - ia: 0.8291 - loss: 0.1255 - mae: 0.2448 - rmse: 0.3408 - smape: 0.5507 - val_ia: 0.7455 - val_loss: 0.0710 - val_mae: 0.1567 - val_rmse: 0.2260 - val_smape: 0.3980

Epoch 6/128

958/958 - 11s - 11ms/step - ia: 0.8378 - loss: 0.1152 - mae: 0.2325 - rmse: 0.3246 - smape: 0.5322 - val_ia: 0.7584 - val_loss: 0.0670 - val_mae: 0.1478 - val_rmse: 0.2154 - val_smape: 0.3784

Epoch 7/128

958/958 - 10s - 11ms/step - ia: 0.8432 - loss: 0.1089 - mae: 0.2241 - rmse: 0.3153 - smape: 0.5122 - val_ia: 0.7652 - val_loss: 0.0654 - val_mae: 0.1453 - val_rmse: 0.2126 - val_smape: 0.3731

Epoch 8/128

958/958 - 3s - 3ms/step - ia: 0.8481 - loss: 0.1051 - mae: 0.2175 - rmse: 0.3084 - smape: 0.5037 - val_ia: 0.7670 - val_loss: 0.0646 - val_mae: 0.1442 - val_rmse: 0.2125 - val_smape: 0.3707

Epoch 9/128

958/958 - 7s - 7ms/step - ia: 0.8515 - loss: 0.1010 - mae: 0.2125 - rmse: 0.3028 - smape: 0.4927 - val_ia: 0.7736 - val_loss: 0.0637 - val_mae: 0.1414 - val_rmse: 0.2091 - val_smape: 0.3615

Epoch 10/128

958/958 - 4s - 4ms/step - ia: 0.8557 - loss: 0.0986 - mae: 0.2068 - rmse: 0.2982 - smape: 0.4819 - val_ia: 0.7737 - val_loss: 0.0635 - val_mae: 0.1405 - val_rmse: 0.2078 - val_smape: 0.3614

Epoch 11/128

958/958 - 5s - 5ms/step - ia: 0.8582 - loss: 0.0961 - mae: 0.2025 - rmse: 0.2937 - smape: 0.4712 - val_ia: 0.7755 - val_loss: 0.0627 - val_mae: 0.1399 - val_rmse: 0.2065 - val_smape: 0.3597

Epoch 12/128

958/958 - 6s - 6ms/step - ia: 0.8604 - loss: 0.0942 - mae: 0.2001 - rmse: 0.2902 - smape: 0.4722 - val_ia: 0.7757 - val_loss: 0.0619 - val_mae: 0.1379 - val_rmse: 0.2053 - val_smape: 0.3573

Epoch 13/128

958/958 - 10s - 10ms/step - ia: 0.8618 - loss: 0.0929 - mae: 0.1978 - rmse: 0.2878 - smape: 0.4649 - val_ia: 0.7790 - val_loss: 0.0618 - val_mae: 0.1373 - val_rmse: 0.2041 - val_smape: 0.3550

Epoch 14/128

958/958 - 6s - 6ms/step - ia: 0.8641 - loss: 0.0899 - mae: 0.1950 - rmse: 0.2823 - smape: 0.4608 - val_ia: 0.7825 - val_loss: 0.0612 - val_mae: 0.1354 - val_rmse: 0.2037 - val_smape: 0.3500

Epoch 15/128

958/958 - 12s - 13ms/step - ia: 0.8658 - loss: 0.0888 - mae: 0.1923 - rmse: 0.2804 - smape: 0.4540 - val_ia: 0.7792 - val_loss: 0.0617 - val_mae: 0.1367 - val_rmse: 0.2061 - val_smape: 0.3556

Epoch 16/128

958/958 - 11s - 12ms/step - ia: 0.8667 - loss: 0.0883 - mae: 0.1907 - rmse: 0.2795 - smape: 0.4514 - val_ia: 0.7815 - val_loss: 0.0612 - val_mae: 0.1354 - val_rmse: 0.2039 - val_smape: 0.3521

Epoch 17/128

958/958 - 16s - 16ms/step - ia: 0.8674 - loss: 0.0881 - mae: 0.1901 - rmse: 0.2793 - smape: 0.4500 - val_ia: 0.7824 - val_loss: 0.0610 - val_mae: 0.1352 - val_rmse: 0.2022 - val_smape: 0.3504

Epoch 18/128

958/958 - 11s - 11ms/step - ia: 0.8694 - loss: 0.0872 - mae: 0.1871 - rmse: 0.2776 - smape: 0.4445 - val_ia: 0.7794 - val_loss: 0.0605 - val_mae: 0.1358 - val_rmse: 0.2024 - val_smape: 0.3527

Epoch 19/128

958/958 - 3s - 3ms/step - ia: 0.8700 - loss: 0.0863 - mae: 0.1863 - rmse: 0.2749 - smape: 0.4445 - val_ia: 0.7835 - val_loss: 0.0600 - val_mae: 0.1340 - val_rmse: 0.2018 - val_smape: 0.3494

Epoch 20/128

958/958 - 6s - 6ms/step - ia: 0.8712 - loss: 0.0853 - mae: 0.1852 - rmse: 0.2737 - smape: 0.4403 - val_ia: 0.7854 - val_loss: 0.0597 - val_mae: 0.1328 - val_rmse: 0.2009 - val_smape: 0.3460

Epoch 21/128

958/958 - 4s - 4ms/step - ia: 0.8720 - loss: 0.0845 - mae: 0.1835 - rmse: 0.2729 - smape: 0.4375 - val_ia: 0.7821 - val_loss: 0.0599 - val_mae: 0.1350 - val_rmse: 0.2005 - val_smape: 0.3507

Epoch 22/128

958/958 - 3s - 3ms/step - ia: 0.8726 - loss: 0.0844 - mae: 0.1822 - rmse: 0.2718 - smape: 0.4354 - val_ia: 0.7824 - val_loss: 0.0592 - val_mae: 0.1332 - val_rmse: 0.1997 - val_smape: 0.3472

Epoch 23/128

958/958 - 3s - 4ms/step - ia: 0.8733 - loss: 0.0834 - mae: 0.1816 - rmse: 0.2695 - smape: 0.4348 - val_ia: 0.7808 - val_loss: 0.0592 - val_mae: 0.1330 - val_rmse: 0.2005 - val_smape: 0.3489

Epoch 24/128

958/958 - 8s - 8ms/step - ia: 0.8744 - loss: 0.0825 - mae: 0.1802 - rmse: 0.2686 - smape: 0.4322 - val_ia: 0.7833 - val_loss: 0.0596 - val_mae: 0.1343 - val_rmse: 0.2024 - val_smape: 0.3490

Epoch 25/128

958/958 - 10s - 10ms/step - ia: 0.8742 - loss: 0.0831 - mae: 0.1804 - rmse: 0.2697 - smape: 0.4323 - val_ia: 0.7761 - val_loss: 0.0593 - val_mae: 0.1358 - val_rmse: 0.2009 - val_smape: 0.3545

Epoch 26/128

958/958 - 5s - 6ms/step - ia: 0.8747 - loss: 0.0818 - mae: 0.1788 - rmse: 0.2663 - smape: 0.4330 - val_ia: 0.7816 - val_loss: 0.0585 - val_mae: 0.1326 - val_rmse: 0.1997 - val_smape: 0.3471

Epoch 27/128

958/958 - 5s - 5ms/step - ia: 0.8759 - loss: 0.0810 - mae: 0.1780 - rmse: 0.2652 - smape: 0.4295 - val_ia: 0.7862 - val_loss: 0.0583 - val_mae: 0.1313 - val_rmse: 0.1989 - val_smape: 0.3445

Epoch 28/128

958/958 - 6s - 6ms/step - ia: 0.8764 - loss: 0.0808 - mae: 0.1775 - rmse: 0.2655 - smape: 0.4287 - val_ia: 0.7835 - val_loss: 0.0588 - val_mae: 0.1333 - val_rmse: 0.1988 - val_smape: 0.3486

Epoch 29/128

958/958 - 5s - 6ms/step - ia: 0.8770 - loss: 0.0805 - mae: 0.1761 - rmse: 0.2652 - smape: 0.4267 - val_ia: 0.7861 - val_loss: 0.0577 - val_mae: 0.1307 - val_rmse: 0.1970 - val_smape: 0.3445

Epoch 30/128

958/958 - 6s - 6ms/step - ia: 0.8771 - loss: 0.0798 - mae: 0.1754 - rmse: 0.2635 - smape: 0.4260 - val_ia: 0.7845 - val_loss: 0.0579 - val_mae: 0.1311 - val_rmse: 0.1986 - val_smape: 0.3462

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.8782 - loss: 0.0794 - mae: 0.1747 - rmse: 0.2624 - smape: 0.4244 - val_ia: 0.7870 - val_loss: 0.0574 - val_mae: 0.1307 - val_rmse: 0.1967 - val_smape: 0.3442

Epoch 32/128

958/958 - 9s - 10ms/step - ia: 0.8777 - loss: 0.0791 - mae: 0.1749 - rmse: 0.2622 - smape: 0.4249 - val_ia: 0.7821 - val_loss: 0.0581 - val_mae: 0.1325 - val_rmse: 0.1995 - val_smape: 0.3488

Epoch 33/128

958/958 - 4s - 4ms/step - ia: 0.8786 - loss: 0.0787 - mae: 0.1737 - rmse: 0.2617 - smape: 0.4232 - val_ia: 0.7848 - val_loss: 0.0574 - val_mae: 0.1317 - val_rmse: 0.1972 - val_smape: 0.3489

Epoch 34/128

958/958 - 6s - 6ms/step - ia: 0.8788 - loss: 0.0780 - mae: 0.1735 - rmse: 0.2605 - smape: 0.4224 - val_ia: 0.7768 - val_loss: 0.0580 - val_mae: 0.1338 - val_rmse: 0.2003 - val_smape: 0.3526

Epoch 35/128

958/958 - 5s - 5ms/step - ia: 0.8791 - loss: 0.0781 - mae: 0.1728 - rmse: 0.2603 - smape: 0.4212 - val_ia: 0.7825 - val_loss: 0.0571 - val_mae: 0.1315 - val_rmse: 0.1964 - val_smape: 0.3488

Epoch 36/128

958/958 - 5s - 6ms/step - ia: 0.8798 - loss: 0.0772 - mae: 0.1717 - rmse: 0.2591 - smape: 0.4196 - val_ia: 0.7858 - val_loss: 0.0571 - val_mae: 0.1304 - val_rmse: 0.1972 - val_smape: 0.3447

Epoch 37/128

958/958 - 6s - 6ms/step - ia: 0.8793 - loss: 0.0772 - mae: 0.1716 - rmse: 0.2588 - smape: 0.4205 - val_ia: 0.7848 - val_loss: 0.0573 - val_mae: 0.1306 - val_rmse: 0.1978 - val_smape: 0.3446

Epoch 38/128

958/958 - 6s - 7ms/step - ia: 0.8804 - loss: 0.0775 - mae: 0.1711 - rmse: 0.2597 - smape: 0.4185 - val_ia: 0.7785 - val_loss: 0.0572 - val_mae: 0.1327 - val_rmse: 0.1977 - val_smape: 0.3512

Epoch 39/128

958/958 - 5s - 6ms/step - ia: 0.8806 - loss: 0.0769 - mae: 0.1702 - rmse: 0.2579 - smape: 0.4190 - val_ia: 0.7793 - val_loss: 0.0576 - val_mae: 0.1332 - val_rmse: 0.1973 - val_smape: 0.3494

Epoch 40/128

958/958 - 3s - 3ms/step - ia: 0.8810 - loss: 0.0763 - mae: 0.1694 - rmse: 0.2567 - smape: 0.4139 - val_ia: 0.7861 - val_loss: 0.0566 - val_mae: 0.1297 - val_rmse: 0.1959 - val_smape: 0.3441

Epoch 41/128

958/958 - 3s - 3ms/step - ia: 0.8815 - loss: 0.0760 - mae: 0.1691 - rmse: 0.2559 - smape: 0.4163 - val_ia: 0.7756 - val_loss: 0.0574 - val_mae: 0.1331 - val_rmse: 0.1990 - val_smape: 0.3508

Epoch 42/128

958/958 - 5s - 5ms/step - ia: 0.8813 - loss: 0.0768 - mae: 0.1696 - rmse: 0.2574 - smape: 0.4185 - val_ia: 0.7835 - val_loss: 0.0565 - val_mae: 0.1302 - val_rmse: 0.1959 - val_smape: 0.3459

Epoch 43/128

958/958 - 5s - 5ms/step - ia: 0.8819 - loss: 0.0756 - mae: 0.1685 - rmse: 0.2559 - smape: 0.4116 - val_ia: 0.7665 - val_loss: 0.0575 - val_mae: 0.1357 - val_rmse: 0.2011 - val_smape: 0.3576

Epoch 44/128

958/958 - 6s - 6ms/step - ia: 0.8817 - loss: 0.0762 - mae: 0.1686 - rmse: 0.2560 - smape: 0.4162 - val_ia: 0.7795 - val_loss: 0.0565 - val_mae: 0.1314 - val_rmse: 0.1972 - val_smape: 0.3474

Epoch 45/128

958/958 - 7s - 7ms/step - ia: 0.8823 - loss: 0.0751 - mae: 0.1676 - rmse: 0.2540 - smape: 0.4124 - val_ia: 0.7816 - val_loss: 0.0567 - val_mae: 0.1308 - val_rmse: 0.1978 - val_smape: 0.3466

Epoch 46/128

958/958 - 9s - 10ms/step - ia: 0.8833 - loss: 0.0743 - mae: 0.1662 - rmse: 0.2525 - smape: 0.4092 - val_ia: 0.7787 - val_loss: 0.0561 - val_mae: 0.1317 - val_rmse: 0.1957 - val_smape: 0.3512

Epoch 47/128

958/958 - 4s - 4ms/step - ia: 0.8827 - loss: 0.0741 - mae: 0.1661 - rmse: 0.2532 - smape: 0.4094 - val_ia: 0.7745 - val_loss: 0.0571 - val_mae: 0.1329 - val_rmse: 0.1995 - val_smape: 0.3504

Epoch 48/128

958/958 - 4s - 4ms/step - ia: 0.8826 - loss: 0.0750 - mae: 0.1670 - rmse: 0.2547 - smape: 0.4112 - val_ia: 0.7745 - val_loss: 0.0563 - val_mae: 0.1327 - val_rmse: 0.1969 - val_smape: 0.3512

Epoch 49/128

958/958 - 3s - 3ms/step - ia: 0.8833 - loss: 0.0737 - mae: 0.1661 - rmse: 0.2525 - smape: 0.4098 - val_ia: 0.7841 - val_loss: 0.0558 - val_mae: 0.1296 - val_rmse: 0.1954 - val_smape: 0.3441

Epoch 50/128

958/958 - 5s - 5ms/step - ia: 0.8833 - loss: 0.0741 - mae: 0.1659 - rmse: 0.2524 - smape: 0.4111 - val_ia: 0.7632 - val_loss: 0.0566 - val_mae: 0.1360 - val_rmse: 0.1990 - val_smape: 0.3553

Epoch 51/128

958/958 - 2s - 2ms/step - ia: 0.8837 - loss: 0.0738 - mae: 0.1653 - rmse: 0.2518 - smape: 0.4088 - val_ia: 0.7770 - val_loss: 0.0563 - val_mae: 0.1322 - val_rmse: 0.1975 - val_smape: 0.3493

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.8835 - loss: 0.0737 - mae: 0.1650 - rmse: 0.2516 - smape: 0.4098 - val_ia: 0.7779 - val_loss: 0.0565 - val_mae: 0.1325 - val_rmse: 0.1967 - val_smape: 0.3503

Epoch 53/128

958/958 - 6s - 6ms/step - ia: 0.8848 - loss: 0.0733 - mae: 0.1642 - rmse: 0.2502 - smape: 0.4079 - val_ia: 0.7682 - val_loss: 0.0572 - val_mae: 0.1355 - val_rmse: 0.2008 - val_smape: 0.3573

Epoch 54/128

958/958 - 5s - 5ms/step - ia: 0.8845 - loss: 0.0735 - mae: 0.1640 - rmse: 0.2506 - smape: 0.4051 - val_ia: 0.7760 - val_loss: 0.0557 - val_mae: 0.1318 - val_rmse: 0.1961 - val_smape: 0.3501

Epoch 55/128

958/958 - 5s - 5ms/step - ia: 0.8840 - loss: 0.0737 - mae: 0.1645 - rmse: 0.2523 - smape: 0.4059 - val_ia: 0.7822 - val_loss: 0.0556 - val_mae: 0.1302 - val_rmse: 0.1953 - val_smape: 0.3469

Epoch 56/128

958/958 - 3s - 4ms/step - ia: 0.8845 - loss: 0.0729 - mae: 0.1642 - rmse: 0.2504 - smape: 0.4071 - val_ia: 0.7802 - val_loss: 0.0560 - val_mae: 0.1310 - val_rmse: 0.1968 - val_smape: 0.3485

Epoch 57/128

958/958 - 5s - 6ms/step - ia: 0.8852 - loss: 0.0726 - mae: 0.1630 - rmse: 0.2492 - smape: 0.4063 - val_ia: 0.7819 - val_loss: 0.0557 - val_mae: 0.1309 - val_rmse: 0.1950 - val_smape: 0.3486

Epoch 58/128

958/958 - 3s - 3ms/step - ia: 0.8856 - loss: 0.0719 - mae: 0.1625 - rmse: 0.2481 - smape: 0.4054 - val_ia: 0.7821 - val_loss: 0.0553 - val_mae: 0.1302 - val_rmse: 0.1944 - val_smape: 0.3489

Epoch 59/128

958/958 - 4s - 4ms/step - ia: 0.8855 - loss: 0.0724 - mae: 0.1627 - rmse: 0.2482 - smape: 0.4043 - val_ia: 0.7684 - val_loss: 0.0560 - val_mae: 0.1340 - val_rmse: 0.1979 - val_smape: 0.3532

Epoch 60/128

958/958 - 4s - 5ms/step - ia: 0.8862 - loss: 0.0717 - mae: 0.1619 - rmse: 0.2487 - smape: 0.4027 - val_ia: 0.7870 - val_loss: 0.0555 - val_mae: 0.1291 - val_rmse: 0.1945 - val_smape: 0.3455

Epoch 61/128

958/958 - 6s - 6ms/step - ia: 0.8859 - loss: 0.0716 - mae: 0.1622 - rmse: 0.2473 - smape: 0.4036 - val_ia: 0.7719 - val_loss: 0.0568 - val_mae: 0.1349 - val_rmse: 0.1995 - val_smape: 0.3574

Epoch 62/128

958/958 - 5s - 5ms/step - ia: 0.8863 - loss: 0.0713 - mae: 0.1620 - rmse: 0.2476 - smape: 0.4030 - val_ia: 0.7802 - val_loss: 0.0559 - val_mae: 0.1312 - val_rmse: 0.1959 - val_smape: 0.3496

Epoch 63/128

958/958 - 5s - 5ms/step - ia: 0.8859 - loss: 0.0718 - mae: 0.1620 - rmse: 0.2478 - smape: 0.4020 - val_ia: 0.7834 - val_loss: 0.0560 - val_mae: 0.1313 - val_rmse: 0.1958 - val_smape: 0.3487

Epoch 64/128

958/958 - 5s - 5ms/step - ia: 0.8864 - loss: 0.0717 - mae: 0.1614 - rmse: 0.2486 - smape: 0.4013 - val_ia: 0.7760 - val_loss: 0.0555 - val_mae: 0.1318 - val_rmse: 0.1959 - val_smape: 0.3493

Epoch 65/128

958/958 - 4s - 4ms/step - ia: 0.8863 - loss: 0.0716 - mae: 0.1612 - rmse: 0.2474 - smape: 0.4018 - val_ia: 0.7835 - val_loss: 0.0556 - val_mae: 0.1300 - val_rmse: 0.1956 - val_smape: 0.3462

Epoch 66/128

958/958 - 5s - 5ms/step - ia: 0.8865 - loss: 0.0721 - mae: 0.1615 - rmse: 0.2492 - smape: 0.4016 - val_ia: 0.7846 - val_loss: 0.0554 - val_mae: 0.1301 - val_rmse: 0.1940 - val_smape: 0.3493

Epoch 67/128

958/958 - 4s - 4ms/step - ia: 0.8870 - loss: 0.0704 - mae: 0.1605 - rmse: 0.2469 - smape: 0.4005 - val_ia: 0.7849 - val_loss: 0.0551 - val_mae: 0.1290 - val_rmse: 0.1941 - val_smape: 0.3461

Epoch 68/128

958/958 - 5s - 5ms/step - ia: 0.8874 - loss: 0.0706 - mae: 0.1605 - rmse: 0.2461 - smape: 0.3997 - val_ia: 0.7853 - val_loss: 0.0552 - val_mae: 0.1291 - val_rmse: 0.1947 - val_smape: 0.3451

Epoch 69/128

958/958 - 4s - 5ms/step - ia: 0.8873 - loss: 0.0702 - mae: 0.1603 - rmse: 0.2452 - smape: 0.3995 - val_ia: 0.7853 - val_loss: 0.0551 - val_mae: 0.1294 - val_rmse: 0.1938 - val_smape: 0.3474

Epoch 70/128

958/958 - 5s - 5ms/step - ia: 0.8883 - loss: 0.0703 - mae: 0.1594 - rmse: 0.2456 - smape: 0.3990 - val_ia: 0.7741 - val_loss: 0.0555 - val_mae: 0.1321 - val_rmse: 0.1969 - val_smape: 0.3510

Epoch 71/128

958/958 - 3s - 3ms/step - ia: 0.8871 - loss: 0.0705 - mae: 0.1598 - rmse: 0.2460 - smape: 0.3988 - val_ia: 0.7810 - val_loss: 0.0551 - val_mae: 0.1300 - val_rmse: 0.1943 - val_smape: 0.3468

Epoch 72/128

958/958 - 4s - 4ms/step - ia: 0.8874 - loss: 0.0697 - mae: 0.1593 - rmse: 0.2454 - smape: 0.3988 - val_ia: 0.7726 - val_loss: 0.0560 - val_mae: 0.1338 - val_rmse: 0.1965 - val_smape: 0.3520

Epoch 73/128

958/958 - 5s - 5ms/step - ia: 0.8869 - loss: 0.0705 - mae: 0.1604 - rmse: 0.2459 - smape: 0.4010 - val_ia: 0.7794 - val_loss: 0.0554 - val_mae: 0.1309 - val_rmse: 0.1959 - val_smape: 0.3487

Epoch 74/128

958/958 - 4s - 4ms/step - ia: 0.8883 - loss: 0.0705 - mae: 0.1592 - rmse: 0.2459 - smape: 0.3974 - val_ia: 0.7791 - val_loss: 0.0554 - val_mae: 0.1314 - val_rmse: 0.1950 - val_smape: 0.3495

Epoch 75/128

958/958 - 5s - 6ms/step - ia: 0.8875 - loss: 0.0703 - mae: 0.1596 - rmse: 0.2453 - smape: 0.3972 - val_ia: 0.7614 - val_loss: 0.0564 - val_mae: 0.1370 - val_rmse: 0.2001 - val_smape: 0.3609

Epoch 76/128

958/958 - 5s - 5ms/step - ia: 0.8881 - loss: 0.0694 - mae: 0.1589 - rmse: 0.2439 - smape: 0.3979 - val_ia: 0.7749 - val_loss: 0.0551 - val_mae: 0.1319 - val_rmse: 0.1955 - val_smape: 0.3502

Epoch 77/128

958/958 - 3s - 3ms/step - ia: 0.8886 - loss: 0.0691 - mae: 0.1581 - rmse: 0.2438 - smape: 0.3936 - val_ia: 0.7767 - val_loss: 0.0555 - val_mae: 0.1323 - val_rmse: 0.1960 - val_smape: 0.3514

Epoch 78/128

958/958 - 2s - 2ms/step - ia: 0.8879 - loss: 0.0696 - mae: 0.1593 - rmse: 0.2450 - smape: 0.3982 - val_ia: 0.7710 - val_loss: 0.0551 - val_mae: 0.1329 - val_rmse: 0.1959 - val_smape: 0.3512

Epoch 79/128

958/958 - 3s - 3ms/step - ia: 0.8879 - loss: 0.0698 - mae: 0.1593 - rmse: 0.2446 - smape: 0.3968 - val_ia: 0.7738 - val_loss: 0.0559 - val_mae: 0.1331 - val_rmse: 0.1974 - val_smape: 0.3528

Epoch 80/128

958/958 - 8s - 9ms/step - ia: 0.8888 - loss: 0.0689 - mae: 0.1578 - rmse: 0.2433 - smape: 0.3954 - val_ia: 0.7666 - val_loss: 0.0561 - val_mae: 0.1352 - val_rmse: 0.1985 - val_smape: 0.3553

Epoch 81/128

958/958 - 4s - 4ms/step - ia: 0.8887 - loss: 0.0689 - mae: 0.1579 - rmse: 0.2435 - smape: 0.3941 - val_ia: 0.7837 - val_loss: 0.0548 - val_mae: 0.1299 - val_rmse: 0.1934 - val_smape: 0.3480

Epoch 82/128

958/958 - 3s - 4ms/step - ia: 0.8885 - loss: 0.0693 - mae: 0.1583 - rmse: 0.2430 - smape: 0.3969 - val_ia: 0.7838 - val_loss: 0.0548 - val_mae: 0.1297 - val_rmse: 0.1934 - val_smape: 0.3481

Epoch 83/128

958/958 - 5s - 5ms/step - ia: 0.8892 - loss: 0.0689 - mae: 0.1576 - rmse: 0.2428 - smape: 0.3948 - val_ia: 0.7800 - val_loss: 0.0549 - val_mae: 0.1298 - val_rmse: 0.1944 - val_smape: 0.3465

Epoch 84/128

958/958 - 5s - 5ms/step - ia: 0.8893 - loss: 0.0684 - mae: 0.1571 - rmse: 0.2422 - smape: 0.3939 - val_ia: 0.7785 - val_loss: 0.0549 - val_mae: 0.1302 - val_rmse: 0.1943 - val_smape: 0.3471

Epoch 85/128

958/958 - 6s - 6ms/step - ia: 0.8897 - loss: 0.0689 - mae: 0.1566 - rmse: 0.2422 - smape: 0.3941 - val_ia: 0.7811 - val_loss: 0.0550 - val_mae: 0.1305 - val_rmse: 0.1938 - val_smape: 0.3475

Epoch 86/128

958/958 - 7s - 8ms/step - ia: 0.8896 - loss: 0.0686 - mae: 0.1567 - rmse: 0.2424 - smape: 0.3928 - val_ia: 0.7843 - val_loss: 0.0544 - val_mae: 0.1288 - val_rmse: 0.1929 - val_smape: 0.3462

Epoch 87/128

958/958 - 4s - 4ms/step - ia: 0.8893 - loss: 0.0682 - mae: 0.1574 - rmse: 0.2428 - smape: 0.3931 - val_ia: 0.7822 - val_loss: 0.0548 - val_mae: 0.1299 - val_rmse: 0.1939 - val_smape: 0.3474

Epoch 88/128

958/958 - 7s - 7ms/step - ia: 0.8896 - loss: 0.0685 - mae: 0.1568 - rmse: 0.2423 - smape: 0.3921 - val_ia: 0.7739 - val_loss: 0.0548 - val_mae: 0.1318 - val_rmse: 0.1950 - val_smape: 0.3494

Epoch 89/128

958/958 - 5s - 6ms/step - ia: 0.8899 - loss: 0.0681 - mae: 0.1562 - rmse: 0.2410 - smape: 0.3926 - val_ia: 0.7867 - val_loss: 0.0548 - val_mae: 0.1294 - val_rmse: 0.1933 - val_smape: 0.3478

Epoch 90/128

958/958 - 5s - 6ms/step - ia: 0.8902 - loss: 0.0679 - mae: 0.1562 - rmse: 0.2413 - smape: 0.3917 - val_ia: 0.7697 - val_loss: 0.0548 - val_mae: 0.1332 - val_rmse: 0.1952 - val_smape: 0.3519

Epoch 91/128

958/958 - 4s - 4ms/step - ia: 0.8897 - loss: 0.0685 - mae: 0.1567 - rmse: 0.2426 - smape: 0.3934 - val_ia: 0.7834 - val_loss: 0.0544 - val_mae: 0.1292 - val_rmse: 0.1933 - val_smape: 0.3463

Epoch 92/128

958/958 - 3s - 3ms/step - ia: 0.8903 - loss: 0.0678 - mae: 0.1553 - rmse: 0.2398 - smape: 0.3885 - val_ia: 0.7797 - val_loss: 0.0545 - val_mae: 0.1304 - val_rmse: 0.1934 - val_smape: 0.3501

Epoch 93/128

958/958 - 2s - 2ms/step - ia: 0.8900 - loss: 0.0679 - mae: 0.1565 - rmse: 0.2419 - smape: 0.3915 - val_ia: 0.7786 - val_loss: 0.0550 - val_mae: 0.1312 - val_rmse: 0.1953 - val_smape: 0.3488

Epoch 94/128

958/958 - 2s - 3ms/step - ia: 0.8905 - loss: 0.0676 - mae: 0.1553 - rmse: 0.2400 - smape: 0.3899 - val_ia: 0.7786 - val_loss: 0.0553 - val_mae: 0.1318 - val_rmse: 0.1950 - val_smape: 0.3486

Epoch 95/128

958/958 - 3s - 3ms/step - ia: 0.8901 - loss: 0.0673 - mae: 0.1560 - rmse: 0.2401 - smape: 0.3922 - val_ia: 0.7859 - val_loss: 0.0550 - val_mae: 0.1299 - val_rmse: 0.1937 - val_smape: 0.3499

Epoch 96/128

958/958 - 2s - 2ms/step - ia: 0.8907 - loss: 0.0672 - mae: 0.1549 - rmse: 0.2397 - smape: 0.3880 - val_ia: 0.7864 - val_loss: 0.0545 - val_mae: 0.1280 - val_rmse: 0.1933 - val_smape: 0.3439

Epoch 97/128

958/958 - 2s - 2ms/step - ia: 0.8904 - loss: 0.0673 - mae: 0.1550 - rmse: 0.2401 - smape: 0.3905 - val_ia: 0.7816 - val_loss: 0.0550 - val_mae: 0.1305 - val_rmse: 0.1955 - val_smape: 0.3483

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 11s - 12ms/step - ia: 0.3685 - loss: 0.8693 - mae: 0.6617 - rmse: 0.9037 - smape: 1.3013 - val_ia: 0.3223 - val_loss: 0.5723 - val_mae: 0.5480 - val_rmse: 0.6278 - val_smape: 1.2026

Epoch 2/128

958/958 - 3s - 4ms/step - ia: 0.5751 - loss: 0.5069 - mae: 0.5019 - rmse: 0.6908 - smape: 1.0060 - val_ia: 0.4349 - val_loss: 0.3338 - val_mae: 0.3939 - val_rmse: 0.4775 - val_smape: 0.8336

Epoch 3/128

958/958 - 5s - 5ms/step - ia: 0.6797 - loss: 0.3719 - mae: 0.4248 - rmse: 0.5916 - smape: 0.8370 - val_ia: 0.5101 - val_loss: 0.2545 - val_mae: 0.3286 - val_rmse: 0.4136 - val_smape: 0.7013

Epoch 4/128

958/958 - 6s - 6ms/step - ia: 0.7159 - loss: 0.3176 - mae: 0.3905 - rmse: 0.5473 - smape: 0.7716 - val_ia: 0.5555 - val_loss: 0.2137 - val_mae: 0.2941 - val_rmse: 0.3771 - val_smape: 0.6340

Epoch 5/128

958/958 - 4s - 4ms/step - ia: 0.7341 - loss: 0.2822 - mae: 0.3678 - rmse: 0.5147 - smape: 0.7375 - val_ia: 0.5909 - val_loss: 0.1837 - val_mae: 0.2684 - val_rmse: 0.3497 - val_smape: 0.5906

Epoch 6/128

958/958 - 5s - 6ms/step - ia: 0.7523 - loss: 0.2542 - mae: 0.3471 - rmse: 0.4864 - smape: 0.7019 - val_ia: 0.6203 - val_loss: 0.1610 - val_mae: 0.2471 - val_rmse: 0.3253 - val_smape: 0.5493

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.7638 - loss: 0.2313 - mae: 0.3315 - rmse: 0.4646 - smape: 0.6814 - val_ia: 0.6434 - val_loss: 0.1441 - val_mae: 0.2316 - val_rmse: 0.3096 - val_smape: 0.5258

Epoch 8/128

958/958 - 7s - 7ms/step - ia: 0.7754 - loss: 0.2097 - mae: 0.3157 - rmse: 0.4420 - smape: 0.6593 - val_ia: 0.6607 - val_loss: 0.1318 - val_mae: 0.2200 - val_rmse: 0.2972 - val_smape: 0.5063

Epoch 9/128

958/958 - 4s - 4ms/step - ia: 0.7836 - loss: 0.1992 - mae: 0.3062 - rmse: 0.4300 - smape: 0.6379 - val_ia: 0.6745 - val_loss: 0.1229 - val_mae: 0.2103 - val_rmse: 0.2862 - val_smape: 0.4889

Epoch 10/128

958/958 - 5s - 5ms/step - ia: 0.7895 - loss: 0.1892 - mae: 0.2980 - rmse: 0.4195 - smape: 0.6314 - val_ia: 0.6856 - val_loss: 0.1151 - val_mae: 0.2024 - val_rmse: 0.2775 - val_smape: 0.4758

Epoch 11/128

958/958 - 4s - 4ms/step - ia: 0.7967 - loss: 0.1780 - mae: 0.2877 - rmse: 0.4063 - smape: 0.6147 - val_ia: 0.6952 - val_loss: 0.1090 - val_mae: 0.1957 - val_rmse: 0.2702 - val_smape: 0.4628

Epoch 12/128

958/958 - 5s - 6ms/step - ia: 0.8023 - loss: 0.1690 - mae: 0.2805 - rmse: 0.3945 - smape: 0.6052 - val_ia: 0.7003 - val_loss: 0.1043 - val_mae: 0.1907 - val_rmse: 0.2647 - val_smape: 0.4549

Epoch 13/128

958/958 - 12s - 12ms/step - ia: 0.8064 - loss: 0.1628 - mae: 0.2746 - rmse: 0.3864 - smape: 0.5974 - val_ia: 0.7086 - val_loss: 0.0996 - val_mae: 0.1854 - val_rmse: 0.2586 - val_smape: 0.4456

Epoch 14/128

958/958 - 10s - 11ms/step - ia: 0.8126 - loss: 0.1550 - mae: 0.2652 - rmse: 0.3758 - smape: 0.5806 - val_ia: 0.7102 - val_loss: 0.0960 - val_mae: 0.1818 - val_rmse: 0.2563 - val_smape: 0.4422

Epoch 15/128

958/958 - 6s - 6ms/step - ia: 0.8158 - loss: 0.1502 - mae: 0.2615 - rmse: 0.3718 - smape: 0.5762 - val_ia: 0.7177 - val_loss: 0.0924 - val_mae: 0.1773 - val_rmse: 0.2501 - val_smape: 0.4339

Epoch 16/128

958/958 - 6s - 6ms/step - ia: 0.8204 - loss: 0.1436 - mae: 0.2547 - rmse: 0.3620 - smape: 0.5661 - val_ia: 0.7191 - val_loss: 0.0895 - val_mae: 0.1747 - val_rmse: 0.2468 - val_smape: 0.4297

Epoch 17/128

958/958 - 10s - 10ms/step - ia: 0.8223 - loss: 0.1379 - mae: 0.2508 - rmse: 0.3560 - smape: 0.5606 - val_ia: 0.7217 - val_loss: 0.0870 - val_mae: 0.1723 - val_rmse: 0.2438 - val_smape: 0.4266

Epoch 18/128

958/958 - 3s - 3ms/step - ia: 0.8268 - loss: 0.1349 - mae: 0.2452 - rmse: 0.3503 - smape: 0.5547 - val_ia: 0.7256 - val_loss: 0.0846 - val_mae: 0.1698 - val_rmse: 0.2406 - val_smape: 0.4225

Epoch 19/128

958/958 - 8s - 8ms/step - ia: 0.8281 - loss: 0.1328 - mae: 0.2425 - rmse: 0.3468 - smape: 0.5493 - val_ia: 0.7287 - val_loss: 0.0826 - val_mae: 0.1676 - val_rmse: 0.2377 - val_smape: 0.4197

Epoch 20/128

958/958 - 5s - 5ms/step - ia: 0.8321 - loss: 0.1281 - mae: 0.2379 - rmse: 0.3409 - smape: 0.5417 - val_ia: 0.7303 - val_loss: 0.0807 - val_mae: 0.1656 - val_rmse: 0.2355 - val_smape: 0.4173

Epoch 21/128

958/958 - 6s - 6ms/step - ia: 0.8347 - loss: 0.1240 - mae: 0.2331 - rmse: 0.3343 - smape: 0.5342 - val_ia: 0.7284 - val_loss: 0.0792 - val_mae: 0.1644 - val_rmse: 0.2348 - val_smape: 0.4157

Epoch 22/128

958/958 - 8s - 9ms/step - ia: 0.8362 - loss: 0.1218 - mae: 0.2303 - rmse: 0.3323 - smape: 0.5335 - val_ia: 0.7287 - val_loss: 0.0778 - val_mae: 0.1635 - val_rmse: 0.2326 - val_smape: 0.4154

Epoch 23/128

958/958 - 5s - 6ms/step - ia: 0.8381 - loss: 0.1197 - mae: 0.2278 - rmse: 0.3284 - smape: 0.5261 - val_ia: 0.7303 - val_loss: 0.0767 - val_mae: 0.1624 - val_rmse: 0.2311 - val_smape: 0.4142

Epoch 24/128

958/958 - 5s - 5ms/step - ia: 0.8395 - loss: 0.1173 - mae: 0.2257 - rmse: 0.3263 - smape: 0.5262 - val_ia: 0.7262 - val_loss: 0.0758 - val_mae: 0.1625 - val_rmse: 0.2310 - val_smape: 0.4145

Epoch 25/128

958/958 - 5s - 5ms/step - ia: 0.8419 - loss: 0.1147 - mae: 0.2217 - rmse: 0.3211 - smape: 0.5181 - val_ia: 0.7275 - val_loss: 0.0747 - val_mae: 0.1613 - val_rmse: 0.2304 - val_smape: 0.4123

Epoch 26/128

958/958 - 5s - 6ms/step - ia: 0.8434 - loss: 0.1120 - mae: 0.2198 - rmse: 0.3182 - smape: 0.5177 - val_ia: 0.7274 - val_loss: 0.0740 - val_mae: 0.1608 - val_rmse: 0.2296 - val_smape: 0.4118

Epoch 27/128

958/958 - 4s - 4ms/step - ia: 0.8442 - loss: 0.1119 - mae: 0.2194 - rmse: 0.3177 - smape: 0.5126 - val_ia: 0.7290 - val_loss: 0.0730 - val_mae: 0.1599 - val_rmse: 0.2275 - val_smape: 0.4107

Epoch 28/128

958/958 - 7s - 7ms/step - ia: 0.8456 - loss: 0.1098 - mae: 0.2161 - rmse: 0.3136 - smape: 0.5087 - val_ia: 0.7355 - val_loss: 0.0719 - val_mae: 0.1575 - val_rmse: 0.2251 - val_smape: 0.4071

Epoch 29/128

958/958 - 3s - 4ms/step - ia: 0.8476 - loss: 0.1078 - mae: 0.2140 - rmse: 0.3119 - smape: 0.5052 - val_ia: 0.7327 - val_loss: 0.0713 - val_mae: 0.1578 - val_rmse: 0.2248 - val_smape: 0.4074

Epoch 30/128

958/958 - 6s - 6ms/step - ia: 0.8481 - loss: 0.1069 - mae: 0.2131 - rmse: 0.3094 - smape: 0.5063 - val_ia: 0.7316 - val_loss: 0.0713 - val_mae: 0.1582 - val_rmse: 0.2252 - val_smape: 0.4080

Epoch 31/128

958/958 - 10s - 10ms/step - ia: 0.8487 - loss: 0.1059 - mae: 0.2122 - rmse: 0.3087 - smape: 0.5037 - val_ia: 0.7304 - val_loss: 0.0704 - val_mae: 0.1576 - val_rmse: 0.2243 - val_smape: 0.4070

Epoch 32/128

958/958 - 5s - 6ms/step - ia: 0.8508 - loss: 0.1041 - mae: 0.2094 - rmse: 0.3060 - smape: 0.4995 - val_ia: 0.7359 - val_loss: 0.0700 - val_mae: 0.1564 - val_rmse: 0.2224 - val_smape: 0.4060

Epoch 33/128

958/958 - 6s - 6ms/step - ia: 0.8512 - loss: 0.1030 - mae: 0.2084 - rmse: 0.3035 - smape: 0.4998 - val_ia: 0.7321 - val_loss: 0.0695 - val_mae: 0.1564 - val_rmse: 0.2231 - val_smape: 0.4051

Epoch 34/128

958/958 - 6s - 6ms/step - ia: 0.8529 - loss: 0.1014 - mae: 0.2063 - rmse: 0.3008 - smape: 0.4938 - val_ia: 0.7375 - val_loss: 0.0686 - val_mae: 0.1543 - val_rmse: 0.2211 - val_smape: 0.4016

Epoch 35/128

958/958 - 5s - 5ms/step - ia: 0.8528 - loss: 0.1011 - mae: 0.2058 - rmse: 0.3011 - smape: 0.4946 - val_ia: 0.7390 - val_loss: 0.0679 - val_mae: 0.1535 - val_rmse: 0.2198 - val_smape: 0.4001

Epoch 36/128

958/958 - 5s - 5ms/step - ia: 0.8530 - loss: 0.1017 - mae: 0.2063 - rmse: 0.3015 - smape: 0.4938 - val_ia: 0.7398 - val_loss: 0.0678 - val_mae: 0.1534 - val_rmse: 0.2196 - val_smape: 0.4002

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.8545 - loss: 0.0994 - mae: 0.2041 - rmse: 0.2981 - smape: 0.4893 - val_ia: 0.7411 - val_loss: 0.0673 - val_mae: 0.1524 - val_rmse: 0.2189 - val_smape: 0.3981

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.8555 - loss: 0.0983 - mae: 0.2029 - rmse: 0.2958 - smape: 0.4883 - val_ia: 0.7421 - val_loss: 0.0668 - val_mae: 0.1518 - val_rmse: 0.2182 - val_smape: 0.3969

Epoch 39/128

958/958 - 5s - 5ms/step - ia: 0.8558 - loss: 0.0974 - mae: 0.2017 - rmse: 0.2945 - smape: 0.4867 - val_ia: 0.7444 - val_loss: 0.0668 - val_mae: 0.1518 - val_rmse: 0.2174 - val_smape: 0.3973

Epoch 40/128

958/958 - 4s - 4ms/step - ia: 0.8575 - loss: 0.0968 - mae: 0.2004 - rmse: 0.2934 - smape: 0.4827 - val_ia: 0.7461 - val_loss: 0.0666 - val_mae: 0.1513 - val_rmse: 0.2169 - val_smape: 0.3968

Epoch 41/128

958/958 - 5s - 5ms/step - ia: 0.8583 - loss: 0.0952 - mae: 0.1998 - rmse: 0.2912 - smape: 0.4834 - val_ia: 0.7446 - val_loss: 0.0659 - val_mae: 0.1505 - val_rmse: 0.2166 - val_smape: 0.3946

Epoch 42/128

958/958 - 7s - 7ms/step - ia: 0.8583 - loss: 0.0950 - mae: 0.1987 - rmse: 0.2910 - smape: 0.4799 - val_ia: 0.7432 - val_loss: 0.0659 - val_mae: 0.1509 - val_rmse: 0.2170 - val_smape: 0.3954

Epoch 43/128

958/958 - 11s - 11ms/step - ia: 0.8586 - loss: 0.0949 - mae: 0.1981 - rmse: 0.2907 - smape: 0.4788 - val_ia: 0.7449 - val_loss: 0.0655 - val_mae: 0.1503 - val_rmse: 0.2159 - val_smape: 0.3938

Epoch 44/128

958/958 - 5s - 5ms/step - ia: 0.8596 - loss: 0.0943 - mae: 0.1972 - rmse: 0.2896 - smape: 0.4796 - val_ia: 0.7540 - val_loss: 0.0648 - val_mae: 0.1476 - val_rmse: 0.2136 - val_smape: 0.3898

Epoch 45/128

958/958 - 3s - 3ms/step - ia: 0.8603 - loss: 0.0935 - mae: 0.1957 - rmse: 0.2884 - smape: 0.4732 - val_ia: 0.7507 - val_loss: 0.0649 - val_mae: 0.1488 - val_rmse: 0.2139 - val_smape: 0.3918

Epoch 46/128

958/958 - 2s - 2ms/step - ia: 0.8601 - loss: 0.0939 - mae: 0.1954 - rmse: 0.2889 - smape: 0.4731 - val_ia: 0.7529 - val_loss: 0.0645 - val_mae: 0.1481 - val_rmse: 0.2131 - val_smape: 0.3909

Epoch 47/128

958/958 - 2s - 2ms/step - ia: 0.8625 - loss: 0.0918 - mae: 0.1937 - rmse: 0.2849 - smape: 0.4720 - val_ia: 0.7484 - val_loss: 0.0647 - val_mae: 0.1491 - val_rmse: 0.2142 - val_smape: 0.3913

Epoch 48/128

958/958 - 3s - 3ms/step - ia: 0.8619 - loss: 0.0924 - mae: 0.1935 - rmse: 0.2854 - smape: 0.4667 - val_ia: 0.7490 - val_loss: 0.0643 - val_mae: 0.1486 - val_rmse: 0.2135 - val_smape: 0.3900

Epoch 49/128

958/958 - 4s - 4ms/step - ia: 0.8626 - loss: 0.0905 - mae: 0.1921 - rmse: 0.2836 - smape: 0.4666 - val_ia: 0.7490 - val_loss: 0.0638 - val_mae: 0.1476 - val_rmse: 0.2132 - val_smape: 0.3879

Epoch 50/128

958/958 - 11s - 11ms/step - ia: 0.8632 - loss: 0.0901 - mae: 0.1922 - rmse: 0.2835 - smape: 0.4671 - val_ia: 0.7522 - val_loss: 0.0636 - val_mae: 0.1469 - val_rmse: 0.2121 - val_smape: 0.3869

Epoch 51/128

958/958 - 7s - 7ms/step - ia: 0.8630 - loss: 0.0897 - mae: 0.1917 - rmse: 0.2830 - smape: 0.4693 - val_ia: 0.7539 - val_loss: 0.0632 - val_mae: 0.1462 - val_rmse: 0.2113 - val_smape: 0.3853

Epoch 52/128

958/958 - 5s - 5ms/step - ia: 0.8649 - loss: 0.0898 - mae: 0.1902 - rmse: 0.2818 - smape: 0.4613 - val_ia: 0.7515 - val_loss: 0.0631 - val_mae: 0.1467 - val_rmse: 0.2116 - val_smape: 0.3863

Epoch 53/128

958/958 - 5s - 5ms/step - ia: 0.8651 - loss: 0.0897 - mae: 0.1898 - rmse: 0.2816 - smape: 0.4631 - val_ia: 0.7430 - val_loss: 0.0634 - val_mae: 0.1492 - val_rmse: 0.2135 - val_smape: 0.3896

Epoch 54/128

958/958 - 6s - 6ms/step - ia: 0.8646 - loss: 0.0900 - mae: 0.1902 - rmse: 0.2825 - smape: 0.4620 - val_ia: 0.7569 - val_loss: 0.0624 - val_mae: 0.1449 - val_rmse: 0.2097 - val_smape: 0.3828

Epoch 55/128

958/958 - 4s - 5ms/step - ia: 0.8656 - loss: 0.0883 - mae: 0.1891 - rmse: 0.2799 - smape: 0.4607 - val_ia: 0.7539 - val_loss: 0.0623 - val_mae: 0.1453 - val_rmse: 0.2102 - val_smape: 0.3831

Epoch 56/128

958/958 - 5s - 5ms/step - ia: 0.8649 - loss: 0.0888 - mae: 0.1893 - rmse: 0.2807 - smape: 0.4594 - val_ia: 0.7560 - val_loss: 0.0624 - val_mae: 0.1451 - val_rmse: 0.2100 - val_smape: 0.3833

Epoch 57/128

958/958 - 4s - 4ms/step - ia: 0.8671 - loss: 0.0872 - mae: 0.1871 - rmse: 0.2775 - smape: 0.4559 - val_ia: 0.7532 - val_loss: 0.0624 - val_mae: 0.1461 - val_rmse: 0.2100 - val_smape: 0.3843

Epoch 58/128

958/958 - 5s - 5ms/step - ia: 0.8680 - loss: 0.0871 - mae: 0.1858 - rmse: 0.2774 - smape: 0.4540 - val_ia: 0.7556 - val_loss: 0.0619 - val_mae: 0.1447 - val_rmse: 0.2094 - val_smape: 0.3823

Epoch 59/128

958/958 - 6s - 6ms/step - ia: 0.8674 - loss: 0.0876 - mae: 0.1866 - rmse: 0.2776 - smape: 0.4568 - val_ia: 0.7537 - val_loss: 0.0621 - val_mae: 0.1452 - val_rmse: 0.2102 - val_smape: 0.3828

Epoch 60/128

958/958 - 6s - 6ms/step - ia: 0.8686 - loss: 0.0860 - mae: 0.1849 - rmse: 0.2756 - smape: 0.4538 - val_ia: 0.7620 - val_loss: 0.0612 - val_mae: 0.1424 - val_rmse: 0.2075 - val_smape: 0.3778

Epoch 61/128

958/958 - 6s - 6ms/step - ia: 0.8679 - loss: 0.0871 - mae: 0.1860 - rmse: 0.2776 - smape: 0.4555 - val_ia: 0.7616 - val_loss: 0.0616 - val_mae: 0.1433 - val_rmse: 0.2080 - val_smape: 0.3801

Epoch 62/128

958/958 - 5s - 5ms/step - ia: 0.8687 - loss: 0.0854 - mae: 0.1846 - rmse: 0.2740 - smape: 0.4539 - val_ia: 0.7587 - val_loss: 0.0611 - val_mae: 0.1428 - val_rmse: 0.2082 - val_smape: 0.3779

Epoch 63/128

958/958 - 3s - 3ms/step - ia: 0.8692 - loss: 0.0854 - mae: 0.1837 - rmse: 0.2743 - smape: 0.4495 - val_ia: 0.7615 - val_loss: 0.0609 - val_mae: 0.1422 - val_rmse: 0.2071 - val_smape: 0.3773

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.8698 - loss: 0.0847 - mae: 0.1832 - rmse: 0.2728 - smape: 0.4494 - val_ia: 0.7636 - val_loss: 0.0607 - val_mae: 0.1416 - val_rmse: 0.2066 - val_smape: 0.3761

Epoch 65/128

958/958 - 3s - 3ms/step - ia: 0.8702 - loss: 0.0847 - mae: 0.1828 - rmse: 0.2732 - smape: 0.4484 - val_ia: 0.7596 - val_loss: 0.0606 - val_mae: 0.1422 - val_rmse: 0.2072 - val_smape: 0.3763

Epoch 66/128

958/958 - 5s - 5ms/step - ia: 0.8702 - loss: 0.0838 - mae: 0.1824 - rmse: 0.2722 - smape: 0.4477 - val_ia: 0.7642 - val_loss: 0.0609 - val_mae: 0.1422 - val_rmse: 0.2067 - val_smape: 0.3773

Epoch 67/128

958/958 - 5s - 5ms/step - ia: 0.8705 - loss: 0.0842 - mae: 0.1822 - rmse: 0.2719 - smape: 0.4476 - val_ia: 0.7627 - val_loss: 0.0608 - val_mae: 0.1424 - val_rmse: 0.2064 - val_smape: 0.3773

Epoch 68/128

958/958 - 5s - 5ms/step - ia: 0.8717 - loss: 0.0835 - mae: 0.1807 - rmse: 0.2708 - smape: 0.4440 - val_ia: 0.7585 - val_loss: 0.0604 - val_mae: 0.1424 - val_rmse: 0.2070 - val_smape: 0.3766

Epoch 69/128

958/958 - 5s - 6ms/step - ia: 0.8709 - loss: 0.0832 - mae: 0.1815 - rmse: 0.2702 - smape: 0.4452 - val_ia: 0.7680 - val_loss: 0.0599 - val_mae: 0.1397 - val_rmse: 0.2049 - val_smape: 0.3722

Epoch 70/128

958/958 - 5s - 5ms/step - ia: 0.8717 - loss: 0.0829 - mae: 0.1811 - rmse: 0.2696 - smape: 0.4438 - val_ia: 0.7653 - val_loss: 0.0602 - val_mae: 0.1408 - val_rmse: 0.2057 - val_smape: 0.3745

Epoch 71/128

958/958 - 4s - 4ms/step - ia: 0.8710 - loss: 0.0833 - mae: 0.1809 - rmse: 0.2712 - smape: 0.4465 - val_ia: 0.7648 - val_loss: 0.0601 - val_mae: 0.1407 - val_rmse: 0.2059 - val_smape: 0.3734

Epoch 72/128

958/958 - 5s - 6ms/step - ia: 0.8717 - loss: 0.0826 - mae: 0.1807 - rmse: 0.2708 - smape: 0.4443 - val_ia: 0.7608 - val_loss: 0.0600 - val_mae: 0.1417 - val_rmse: 0.2059 - val_smape: 0.3750

Epoch 73/128

958/958 - 4s - 4ms/step - ia: 0.8724 - loss: 0.0826 - mae: 0.1800 - rmse: 0.2694 - smape: 0.4445 - val_ia: 0.7654 - val_loss: 0.0597 - val_mae: 0.1401 - val_rmse: 0.2049 - val_smape: 0.3723

Epoch 74/128

958/958 - 4s - 4ms/step - ia: 0.8722 - loss: 0.0825 - mae: 0.1800 - rmse: 0.2696 - smape: 0.4449 - val_ia: 0.7688 - val_loss: 0.0596 - val_mae: 0.1394 - val_rmse: 0.2043 - val_smape: 0.3715

Epoch 75/128

958/958 - 2s - 2ms/step - ia: 0.8728 - loss: 0.0827 - mae: 0.1797 - rmse: 0.2689 - smape: 0.4414 - val_ia: 0.7627 - val_loss: 0.0604 - val_mae: 0.1422 - val_rmse: 0.2061 - val_smape: 0.3756

Epoch 76/128

958/958 - 2s - 3ms/step - ia: 0.8736 - loss: 0.0813 - mae: 0.1778 - rmse: 0.2669 - smape: 0.4395 - val_ia: 0.7685 - val_loss: 0.0591 - val_mae: 0.1387 - val_rmse: 0.2037 - val_smape: 0.3701

Epoch 77/128

958/958 - 3s - 3ms/step - ia: 0.8736 - loss: 0.0819 - mae: 0.1781 - rmse: 0.2678 - smape: 0.4404 - val_ia: 0.7643 - val_loss: 0.0597 - val_mae: 0.1406 - val_rmse: 0.2050 - val_smape: 0.3729

Epoch 78/128

958/958 - 3s - 3ms/step - ia: 0.8736 - loss: 0.0820 - mae: 0.1780 - rmse: 0.2686 - smape: 0.4383 - val_ia: 0.7685 - val_loss: 0.0595 - val_mae: 0.1396 - val_rmse: 0.2040 - val_smape: 0.3712

Epoch 79/128

958/958 - 5s - 5ms/step - ia: 0.8739 - loss: 0.0819 - mae: 0.1775 - rmse: 0.2673 - smape: 0.4360 - val_ia: 0.7658 - val_loss: 0.0590 - val_mae: 0.1392 - val_rmse: 0.2041 - val_smape: 0.3706

Epoch 80/128

958/958 - 6s - 6ms/step - ia: 0.8741 - loss: 0.0813 - mae: 0.1772 - rmse: 0.2662 - smape: 0.4362 - val_ia: 0.7660 - val_loss: 0.0589 - val_mae: 0.1392 - val_rmse: 0.2037 - val_smape: 0.3703

Epoch 81/128

958/958 - 7s - 7ms/step - ia: 0.8745 - loss: 0.0808 - mae: 0.1765 - rmse: 0.2661 - smape: 0.4335 - val_ia: 0.7648 - val_loss: 0.0590 - val_mae: 0.1397 - val_rmse: 0.2040 - val_smape: 0.3708

Epoch 82/128

958/958 - 4s - 4ms/step - ia: 0.8746 - loss: 0.0808 - mae: 0.1766 - rmse: 0.2660 - smape: 0.4354 - val_ia: 0.7662 - val_loss: 0.0587 - val_mae: 0.1390 - val_rmse: 0.2033 - val_smape: 0.3697

Epoch 83/128

958/958 - 6s - 6ms/step - ia: 0.8750 - loss: 0.0803 - mae: 0.1762 - rmse: 0.2647 - smape: 0.4358 - val_ia: 0.7679 - val_loss: 0.0591 - val_mae: 0.1393 - val_rmse: 0.2037 - val_smape: 0.3700

Epoch 84/128

958/958 - 6s - 6ms/step - ia: 0.8761 - loss: 0.0796 - mae: 0.1754 - rmse: 0.2639 - smape: 0.4328 - val_ia: 0.7700 - val_loss: 0.0587 - val_mae: 0.1382 - val_rmse: 0.2026 - val_smape: 0.3679

Epoch 85/128

958/958 - 6s - 6ms/step - ia: 0.8754 - loss: 0.0803 - mae: 0.1761 - rmse: 0.2649 - smape: 0.4345 - val_ia: 0.7656 - val_loss: 0.0587 - val_mae: 0.1390 - val_rmse: 0.2034 - val_smape: 0.3693

Epoch 86/128

958/958 - 4s - 5ms/step - ia: 0.8762 - loss: 0.0792 - mae: 0.1747 - rmse: 0.2633 - smape: 0.4346 - val_ia: 0.7661 - val_loss: 0.0587 - val_mae: 0.1388 - val_rmse: 0.2039 - val_smape: 0.3689

Epoch 87/128

958/958 - 5s - 5ms/step - ia: 0.8761 - loss: 0.0793 - mae: 0.1747 - rmse: 0.2634 - smape: 0.4341 - val_ia: 0.7668 - val_loss: 0.0585 - val_mae: 0.1384 - val_rmse: 0.2033 - val_smape: 0.3682

Epoch 88/128

958/958 - 5s - 5ms/step - ia: 0.8761 - loss: 0.0804 - mae: 0.1750 - rmse: 0.2646 - smape: 0.4304 - val_ia: 0.7678 - val_loss: 0.0588 - val_mae: 0.1390 - val_rmse: 0.2029 - val_smape: 0.3685

Epoch 89/128

958/958 - 4s - 4ms/step - ia: 0.8769 - loss: 0.0793 - mae: 0.1737 - rmse: 0.2636 - smape: 0.4285 - val_ia: 0.7630 - val_loss: 0.0587 - val_mae: 0.1399 - val_rmse: 0.2038 - val_smape: 0.3700

Epoch 90/128

958/958 - 5s - 6ms/step - ia: 0.8759 - loss: 0.0797 - mae: 0.1749 - rmse: 0.2634 - smape: 0.4292 - val_ia: 0.7727 - val_loss: 0.0582 - val_mae: 0.1365 - val_rmse: 0.2021 - val_smape: 0.3649

Epoch 91/128

958/958 - 6s - 6ms/step - ia: 0.8776 - loss: 0.0784 - mae: 0.1731 - rmse: 0.2620 - smape: 0.4293 - val_ia: 0.7710 - val_loss: 0.0583 - val_mae: 0.1376 - val_rmse: 0.2021 - val_smape: 0.3664

Epoch 92/128

958/958 - 4s - 4ms/step - ia: 0.8766 - loss: 0.0787 - mae: 0.1741 - rmse: 0.2627 - smape: 0.4307 - val_ia: 0.7713 - val_loss: 0.0578 - val_mae: 0.1366 - val_rmse: 0.2013 - val_smape: 0.3653

Epoch 93/128

958/958 - 5s - 5ms/step - ia: 0.8771 - loss: 0.0779 - mae: 0.1732 - rmse: 0.2619 - smape: 0.4299 - val_ia: 0.7663 - val_loss: 0.0582 - val_mae: 0.1385 - val_rmse: 0.2025 - val_smape: 0.3676

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.8775 - loss: 0.0786 - mae: 0.1729 - rmse: 0.2620 - smape: 0.4274 - val_ia: 0.7679 - val_loss: 0.0582 - val_mae: 0.1382 - val_rmse: 0.2022 - val_smape: 0.3664

Epoch 95/128

958/958 - 2s - 2ms/step - ia: 0.8782 - loss: 0.0777 - mae: 0.1722 - rmse: 0.2607 - smape: 0.4278 - val_ia: 0.7675 - val_loss: 0.0582 - val_mae: 0.1381 - val_rmse: 0.2027 - val_smape: 0.3664

Epoch 96/128

958/958 - 3s - 4ms/step - ia: 0.8781 - loss: 0.0786 - mae: 0.1720 - rmse: 0.2618 - smape: 0.4229 - val_ia: 0.7739 - val_loss: 0.0576 - val_mae: 0.1357 - val_rmse: 0.2008 - val_smape: 0.3630

Epoch 97/128

958/958 - 3s - 3ms/step - ia: 0.8788 - loss: 0.0775 - mae: 0.1712 - rmse: 0.2603 - smape: 0.4236 - val_ia: 0.7729 - val_loss: 0.0579 - val_mae: 0.1367 - val_rmse: 0.2010 - val_smape: 0.3639

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 7s - 7ms/step - ia: 0.6443 - loss: 0.4188 - mae: 0.4290 - rmse: 0.6146 - smape: 0.8867 - val_ia: 0.5134 - val_loss: 0.2374 - val_mae: 0.3218 - val_rmse: 0.4086 - val_smape: 0.6966

Epoch 2/128

958/958 - 3s - 3ms/step - ia: 0.7815 - loss: 0.2179 - mae: 0.2963 - rmse: 0.4464 - smape: 0.6345 - val_ia: 0.5960 - val_loss: 0.1623 - val_mae: 0.2582 - val_rmse: 0.3376 - val_smape: 0.5871

Epoch 3/128

958/958 - 4s - 5ms/step - ia: 0.8202 - loss: 0.1604 - mae: 0.2476 - rmse: 0.3808 - smape: 0.5496 - val_ia: 0.6487 - val_loss: 0.1256 - val_mae: 0.2228 - val_rmse: 0.2993 - val_smape: 0.5276

Epoch 4/128

958/958 - 5s - 5ms/step - ia: 0.8446 - loss: 0.1294 - mae: 0.2175 - rmse: 0.3397 - smape: 0.4950 - val_ia: 0.6840 - val_loss: 0.1048 - val_mae: 0.2000 - val_rmse: 0.2728 - val_smape: 0.4805

Epoch 5/128

958/958 - 5s - 5ms/step - ia: 0.8596 - loss: 0.1103 - mae: 0.1977 - rmse: 0.3117 - smape: 0.4600 - val_ia: 0.7038 - val_loss: 0.0915 - val_mae: 0.1847 - val_rmse: 0.2567 - val_smape: 0.4530

Epoch 6/128

958/958 - 4s - 5ms/step - ia: 0.8699 - loss: 0.0982 - mae: 0.1839 - rmse: 0.2934 - smape: 0.4349 - val_ia: 0.7238 - val_loss: 0.0820 - val_mae: 0.1723 - val_rmse: 0.2419 - val_smape: 0.4268

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.8767 - loss: 0.0900 - mae: 0.1748 - rmse: 0.2795 - smape: 0.4176 - val_ia: 0.7390 - val_loss: 0.0760 - val_mae: 0.1628 - val_rmse: 0.2335 - val_smape: 0.4090

Epoch 8/128

958/958 - 4s - 5ms/step - ia: 0.8821 - loss: 0.0844 - mae: 0.1674 - rmse: 0.2697 - smape: 0.4051 - val_ia: 0.7455 - val_loss: 0.0716 - val_mae: 0.1579 - val_rmse: 0.2260 - val_smape: 0.4005

Epoch 9/128

958/958 - 6s - 6ms/step - ia: 0.8863 - loss: 0.0803 - mae: 0.1619 - rmse: 0.2620 - smape: 0.3948 - val_ia: 0.7521 - val_loss: 0.0685 - val_mae: 0.1534 - val_rmse: 0.2205 - val_smape: 0.3931

Epoch 10/128

958/958 - 5s - 5ms/step - ia: 0.8893 - loss: 0.0771 - mae: 0.1579 - rmse: 0.2566 - smape: 0.3875 - val_ia: 0.7559 - val_loss: 0.0662 - val_mae: 0.1492 - val_rmse: 0.2170 - val_smape: 0.3858

Epoch 11/128

958/958 - 5s - 5ms/step - ia: 0.8916 - loss: 0.0747 - mae: 0.1544 - rmse: 0.2526 - smape: 0.3808 - val_ia: 0.7633 - val_loss: 0.0645 - val_mae: 0.1461 - val_rmse: 0.2134 - val_smape: 0.3771

Epoch 12/128

958/958 - 5s - 5ms/step - ia: 0.8935 - loss: 0.0727 - mae: 0.1517 - rmse: 0.2483 - smape: 0.3757 - val_ia: 0.7668 - val_loss: 0.0628 - val_mae: 0.1434 - val_rmse: 0.2103 - val_smape: 0.3731

Epoch 13/128

958/958 - 4s - 4ms/step - ia: 0.8949 - loss: 0.0712 - mae: 0.1497 - rmse: 0.2457 - smape: 0.3715 - val_ia: 0.7685 - val_loss: 0.0619 - val_mae: 0.1416 - val_rmse: 0.2091 - val_smape: 0.3702

Epoch 14/128

958/958 - 6s - 6ms/step - ia: 0.8960 - loss: 0.0700 - mae: 0.1480 - rmse: 0.2430 - smape: 0.3679 - val_ia: 0.7709 - val_loss: 0.0610 - val_mae: 0.1404 - val_rmse: 0.2069 - val_smape: 0.3664

Epoch 15/128

958/958 - 5s - 5ms/step - ia: 0.8976 - loss: 0.0689 - mae: 0.1464 - rmse: 0.2409 - smape: 0.3652 - val_ia: 0.7756 - val_loss: 0.0600 - val_mae: 0.1383 - val_rmse: 0.2050 - val_smape: 0.3623

Epoch 16/128

958/958 - 5s - 5ms/step - ia: 0.8983 - loss: 0.0680 - mae: 0.1454 - rmse: 0.2392 - smape: 0.3629 - val_ia: 0.7773 - val_loss: 0.0596 - val_mae: 0.1370 - val_rmse: 0.2047 - val_smape: 0.3598

Epoch 17/128

958/958 - 5s - 6ms/step - ia: 0.8988 - loss: 0.0672 - mae: 0.1443 - rmse: 0.2377 - smape: 0.3613 - val_ia: 0.7764 - val_loss: 0.0594 - val_mae: 0.1369 - val_rmse: 0.2049 - val_smape: 0.3609

Epoch 18/128

958/958 - 4s - 4ms/step - ia: 0.8995 - loss: 0.0667 - mae: 0.1436 - rmse: 0.2369 - smape: 0.3595 - val_ia: 0.7791 - val_loss: 0.0585 - val_mae: 0.1352 - val_rmse: 0.2022 - val_smape: 0.3549

Epoch 19/128

958/958 - 3s - 3ms/step - ia: 0.9001 - loss: 0.0661 - mae: 0.1426 - rmse: 0.2351 - smape: 0.3583 - val_ia: 0.7811 - val_loss: 0.0585 - val_mae: 0.1350 - val_rmse: 0.2026 - val_smape: 0.3538

Epoch 20/128

958/958 - 3s - 3ms/step - ia: 0.9006 - loss: 0.0656 - mae: 0.1421 - rmse: 0.2346 - smape: 0.3574 - val_ia: 0.7821 - val_loss: 0.0579 - val_mae: 0.1340 - val_rmse: 0.2011 - val_smape: 0.3524

Epoch 21/128

958/958 - 3s - 3ms/step - ia: 0.9013 - loss: 0.0653 - mae: 0.1416 - rmse: 0.2335 - smape: 0.3558 - val_ia: 0.7759 - val_loss: 0.0581 - val_mae: 0.1356 - val_rmse: 0.2023 - val_smape: 0.3582

Epoch 22/128

958/958 - 3s - 4ms/step - ia: 0.9015 - loss: 0.0649 - mae: 0.1409 - rmse: 0.2324 - smape: 0.3555 - val_ia: 0.7822 - val_loss: 0.0573 - val_mae: 0.1335 - val_rmse: 0.2001 - val_smape: 0.3520

Epoch 23/128

958/958 - 5s - 6ms/step - ia: 0.9022 - loss: 0.0644 - mae: 0.1406 - rmse: 0.2315 - smape: 0.3553 - val_ia: 0.7813 - val_loss: 0.0573 - val_mae: 0.1339 - val_rmse: 0.2001 - val_smape: 0.3539

Epoch 24/128

958/958 - 7s - 7ms/step - ia: 0.9016 - loss: 0.0642 - mae: 0.1405 - rmse: 0.2320 - smape: 0.3543 - val_ia: 0.7816 - val_loss: 0.0573 - val_mae: 0.1337 - val_rmse: 0.1990 - val_smape: 0.3512

Epoch 25/128

958/958 - 5s - 5ms/step - ia: 0.9024 - loss: 0.0640 - mae: 0.1399 - rmse: 0.2312 - smape: 0.3530 - val_ia: 0.7811 - val_loss: 0.0569 - val_mae: 0.1334 - val_rmse: 0.1994 - val_smape: 0.3510

Epoch 26/128

958/958 - 4s - 4ms/step - ia: 0.9025 - loss: 0.0638 - mae: 0.1399 - rmse: 0.2313 - smape: 0.3534 - val_ia: 0.7847 - val_loss: 0.0569 - val_mae: 0.1322 - val_rmse: 0.1990 - val_smape: 0.3494

Epoch 27/128

958/958 - 4s - 4ms/step - ia: 0.9025 - loss: 0.0636 - mae: 0.1394 - rmse: 0.2301 - smape: 0.3524 - val_ia: 0.7820 - val_loss: 0.0564 - val_mae: 0.1321 - val_rmse: 0.1983 - val_smape: 0.3486

Epoch 28/128

958/958 - 4s - 4ms/step - ia: 0.9025 - loss: 0.0634 - mae: 0.1391 - rmse: 0.2305 - smape: 0.3522 - val_ia: 0.7816 - val_loss: 0.0567 - val_mae: 0.1327 - val_rmse: 0.1992 - val_smape: 0.3517

Epoch 29/128

958/958 - 3s - 3ms/step - ia: 0.9028 - loss: 0.0631 - mae: 0.1390 - rmse: 0.2297 - smape: 0.3521 - val_ia: 0.7832 - val_loss: 0.0563 - val_mae: 0.1320 - val_rmse: 0.1978 - val_smape: 0.3481

Epoch 30/128

958/958 - 5s - 5ms/step - ia: 0.9024 - loss: 0.0630 - mae: 0.1390 - rmse: 0.2292 - smape: 0.3520 - val_ia: 0.7853 - val_loss: 0.0563 - val_mae: 0.1313 - val_rmse: 0.1978 - val_smape: 0.3479

Epoch 31/128

958/958 - 2s - 2ms/step - ia: 0.9030 - loss: 0.0629 - mae: 0.1385 - rmse: 0.2285 - smape: 0.3514 - val_ia: 0.7853 - val_loss: 0.0565 - val_mae: 0.1312 - val_rmse: 0.1986 - val_smape: 0.3490

Epoch 32/128

958/958 - 2s - 2ms/step - ia: 0.9030 - loss: 0.0628 - mae: 0.1386 - rmse: 0.2290 - smape: 0.3514 - val_ia: 0.7826 - val_loss: 0.0566 - val_mae: 0.1324 - val_rmse: 0.1986 - val_smape: 0.3518

Epoch 33/128

958/958 - 2s - 2ms/step - ia: 0.9030 - loss: 0.0627 - mae: 0.1385 - rmse: 0.2292 - smape: 0.3514 - val_ia: 0.7834 - val_loss: 0.0559 - val_mae: 0.1315 - val_rmse: 0.1973 - val_smape: 0.3480

Epoch 34/128

958/958 - 2s - 2ms/step - ia: 0.9026 - loss: 0.0625 - mae: 0.1384 - rmse: 0.2289 - smape: 0.3510 - val_ia: 0.7861 - val_loss: 0.0562 - val_mae: 0.1307 - val_rmse: 0.1976 - val_smape: 0.3462

Epoch 35/128

958/958 - 2s - 2ms/step - ia: 0.9037 - loss: 0.0625 - mae: 0.1380 - rmse: 0.2288 - smape: 0.3504 - val_ia: 0.7847 - val_loss: 0.0560 - val_mae: 0.1309 - val_rmse: 0.1971 - val_smape: 0.3476

Epoch 36/128

958/958 - 3s - 3ms/step - ia: 0.9034 - loss: 0.0624 - mae: 0.1381 - rmse: 0.2286 - smape: 0.3507 - val_ia: 0.7838 - val_loss: 0.0559 - val_mae: 0.1316 - val_rmse: 0.1968 - val_smape: 0.3465

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.9036 - loss: 0.0623 - mae: 0.1382 - rmse: 0.2284 - smape: 0.3511 - val_ia: 0.7839 - val_loss: 0.0559 - val_mae: 0.1312 - val_rmse: 0.1975 - val_smape: 0.3488

Epoch 38/128

958/958 - 2s - 3ms/step - ia: 0.9034 - loss: 0.0621 - mae: 0.1382 - rmse: 0.2287 - smape: 0.3515 - val_ia: 0.7852 - val_loss: 0.0561 - val_mae: 0.1313 - val_rmse: 0.1973 - val_smape: 0.3467

Epoch 39/128

958/958 - 3s - 3ms/step - ia: 0.9038 - loss: 0.0622 - mae: 0.1378 - rmse: 0.2276 - smape: 0.3500 - val_ia: 0.7797 - val_loss: 0.0562 - val_mae: 0.1323 - val_rmse: 0.1988 - val_smape: 0.3530

Epoch 40/128

958/958 - 5s - 5ms/step - ia: 0.9040 - loss: 0.0620 - mae: 0.1377 - rmse: 0.2269 - smape: 0.3501 - val_ia: 0.7837 - val_loss: 0.0561 - val_mae: 0.1308 - val_rmse: 0.1978 - val_smape: 0.3488

Epoch 41/128

958/958 - 5s - 5ms/step - ia: 0.9036 - loss: 0.0620 - mae: 0.1378 - rmse: 0.2283 - smape: 0.3502 - val_ia: 0.7817 - val_loss: 0.0565 - val_mae: 0.1325 - val_rmse: 0.1997 - val_smape: 0.3543

Epoch 42/128

958/958 - 4s - 4ms/step - ia: 0.9040 - loss: 0.0620 - mae: 0.1376 - rmse: 0.2276 - smape: 0.3496 - val_ia: 0.7856 - val_loss: 0.0559 - val_mae: 0.1306 - val_rmse: 0.1975 - val_smape: 0.3487

Epoch 43/128

958/958 - 4s - 4ms/step - ia: 0.9042 - loss: 0.0619 - mae: 0.1373 - rmse: 0.2272 - smape: 0.3490 - val_ia: 0.7811 - val_loss: 0.0565 - val_mae: 0.1328 - val_rmse: 0.1990 - val_smape: 0.3531

Epoch 44/128

958/958 - 4s - 5ms/step - ia: 0.9038 - loss: 0.0618 - mae: 0.1375 - rmse: 0.2273 - smape: 0.3506 - val_ia: 0.7860 - val_loss: 0.0556 - val_mae: 0.1303 - val_rmse: 0.1963 - val_smape: 0.3465

Epoch 45/128

958/958 - 5s - 6ms/step - ia: 0.9036 - loss: 0.0618 - mae: 0.1374 - rmse: 0.2267 - smape: 0.3502 - val_ia: 0.7793 - val_loss: 0.0562 - val_mae: 0.1325 - val_rmse: 0.1987 - val_smape: 0.3522

Epoch 46/128

958/958 - 5s - 5ms/step - ia: 0.9036 - loss: 0.0618 - mae: 0.1376 - rmse: 0.2270 - smape: 0.3498 - val_ia: 0.7865 - val_loss: 0.0557 - val_mae: 0.1310 - val_rmse: 0.1965 - val_smape: 0.3456

Epoch 47/128

958/958 - 5s - 5ms/step - ia: 0.9039 - loss: 0.0618 - mae: 0.1374 - rmse: 0.2275 - smape: 0.3491 - val_ia: 0.7807 - val_loss: 0.0557 - val_mae: 0.1312 - val_rmse: 0.1968 - val_smape: 0.3482

Epoch 48/128

958/958 - 5s - 5ms/step - ia: 0.9040 - loss: 0.0616 - mae: 0.1373 - rmse: 0.2266 - smape: 0.3491 - val_ia: 0.7802 - val_loss: 0.0565 - val_mae: 0.1325 - val_rmse: 0.1994 - val_smape: 0.3542

Epoch 49/128

958/958 - 4s - 4ms/step - ia: 0.9036 - loss: 0.0616 - mae: 0.1373 - rmse: 0.2275 - smape: 0.3500 - val_ia: 0.7844 - val_loss: 0.0559 - val_mae: 0.1307 - val_rmse: 0.1972 - val_smape: 0.3493

Epoch 50/128

958/958 - 5s - 6ms/step - ia: 0.9037 - loss: 0.0616 - mae: 0.1372 - rmse: 0.2267 - smape: 0.3494 - val_ia: 0.7827 - val_loss: 0.0562 - val_mae: 0.1319 - val_rmse: 0.1980 - val_smape: 0.3507

Epoch 51/128

958/958 - 4s - 4ms/step - ia: 0.9035 - loss: 0.0616 - mae: 0.1375 - rmse: 0.2272 - smape: 0.3502 - val_ia: 0.7854 - val_loss: 0.0555 - val_mae: 0.1301 - val_rmse: 0.1961 - val_smape: 0.3463

Epoch 52/128

958/958 - 5s - 5ms/step - ia: 0.9042 - loss: 0.0615 - mae: 0.1372 - rmse: 0.2266 - smape: 0.3491 - val_ia: 0.7845 - val_loss: 0.0555 - val_mae: 0.1305 - val_rmse: 0.1961 - val_smape: 0.3473

Epoch 53/128

958/958 - 4s - 4ms/step - ia: 0.9042 - loss: 0.0614 - mae: 0.1370 - rmse: 0.2261 - smape: 0.3489 - val_ia: 0.7838 - val_loss: 0.0558 - val_mae: 0.1313 - val_rmse: 0.1968 - val_smape: 0.3491

Epoch 54/128

958/958 - 5s - 6ms/step - ia: 0.9038 - loss: 0.0614 - mae: 0.1373 - rmse: 0.2266 - smape: 0.3503 - val_ia: 0.7845 - val_loss: 0.0554 - val_mae: 0.1302 - val_rmse: 0.1961 - val_smape: 0.3465

Epoch 55/128

958/958 - 5s - 5ms/step - ia: 0.9039 - loss: 0.0614 - mae: 0.1374 - rmse: 0.2275 - smape: 0.3505 - val_ia: 0.7850 - val_loss: 0.0555 - val_mae: 0.1306 - val_rmse: 0.1965 - val_smape: 0.3472

Epoch 56/128

958/958 - 3s - 3ms/step - ia: 0.9040 - loss: 0.0613 - mae: 0.1372 - rmse: 0.2270 - smape: 0.3499 - val_ia: 0.7815 - val_loss: 0.0561 - val_mae: 0.1323 - val_rmse: 0.1971 - val_smape: 0.3511

Epoch 57/128

958/958 - 6s - 6ms/step - ia: 0.9042 - loss: 0.0613 - mae: 0.1372 - rmse: 0.2266 - smape: 0.3503 - val_ia: 0.7848 - val_loss: 0.0556 - val_mae: 0.1307 - val_rmse: 0.1966 - val_smape: 0.3474

Epoch 58/128

958/958 - 4s - 4ms/step - ia: 0.9040 - loss: 0.0613 - mae: 0.1371 - rmse: 0.2262 - smape: 0.3497 - val_ia: 0.7841 - val_loss: 0.0560 - val_mae: 0.1315 - val_rmse: 0.1966 - val_smape: 0.3491

Epoch 59/128

958/958 - 6s - 6ms/step - ia: 0.9044 - loss: 0.0613 - mae: 0.1371 - rmse: 0.2261 - smape: 0.3494 - val_ia: 0.7839 - val_loss: 0.0560 - val_mae: 0.1315 - val_rmse: 0.1970 - val_smape: 0.3496

Epoch 60/128

958/958 - 5s - 5ms/step - ia: 0.9041 - loss: 0.0612 - mae: 0.1370 - rmse: 0.2251 - smape: 0.3488 - val_ia: 0.7833 - val_loss: 0.0555 - val_mae: 0.1311 - val_rmse: 0.1960 - val_smape: 0.3476

Epoch 61/128

958/958 - 5s - 5ms/step - ia: 0.9041 - loss: 0.0612 - mae: 0.1372 - rmse: 0.2263 - smape: 0.3499 - val_ia: 0.7848 - val_loss: 0.0556 - val_mae: 0.1305 - val_rmse: 0.1964 - val_smape: 0.3484

Epoch 62/128

958/958 - 4s - 4ms/step - ia: 0.9041 - loss: 0.0612 - mae: 0.1372 - rmse: 0.2257 - smape: 0.3506 - val_ia: 0.7841 - val_loss: 0.0555 - val_mae: 0.1304 - val_rmse: 0.1965 - val_smape: 0.3467

Epoch 63/128

958/958 - 6s - 6ms/step - ia: 0.9042 - loss: 0.0612 - mae: 0.1371 - rmse: 0.2262 - smape: 0.3501 - val_ia: 0.7796 - val_loss: 0.0566 - val_mae: 0.1333 - val_rmse: 0.1993 - val_smape: 0.3552

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.9041 - loss: 0.0611 - mae: 0.1371 - rmse: 0.2257 - smape: 0.3494 - val_ia: 0.7842 - val_loss: 0.0561 - val_mae: 0.1311 - val_rmse: 0.1980 - val_smape: 0.3483

Epoch 65/128

958/958 - 4s - 5ms/step - ia: 0.9041 - loss: 0.0611 - mae: 0.1371 - rmse: 0.2264 - smape: 0.3494 - val_ia: 0.7818 - val_loss: 0.0554 - val_mae: 0.1311 - val_rmse: 0.1963 - val_smape: 0.3476

Epoch 66/128

958/958 - 5s - 5ms/step - ia: 0.9040 - loss: 0.0611 - mae: 0.1370 - rmse: 0.2265 - smape: 0.3488 - val_ia: 0.7826 - val_loss: 0.0553 - val_mae: 0.1307 - val_rmse: 0.1962 - val_smape: 0.3491

Epoch 67/128

958/958 - 4s - 4ms/step - ia: 0.9038 - loss: 0.0611 - mae: 0.1371 - rmse: 0.2251 - smape: 0.3503 - val_ia: 0.7824 - val_loss: 0.0553 - val_mae: 0.1306 - val_rmse: 0.1962 - val_smape: 0.3485

Epoch 68/128

958/958 - 3s - 3ms/step - ia: 0.9045 - loss: 0.0610 - mae: 0.1369 - rmse: 0.2250 - smape: 0.3494 - val_ia: 0.7836 - val_loss: 0.0556 - val_mae: 0.1306 - val_rmse: 0.1971 - val_smape: 0.3500

Epoch 69/128

958/958 - 2s - 2ms/step - ia: 0.9043 - loss: 0.0610 - mae: 0.1367 - rmse: 0.2258 - smape: 0.3485 - val_ia: 0.7763 - val_loss: 0.0557 - val_mae: 0.1330 - val_rmse: 0.1979 - val_smape: 0.3536

Epoch 70/128

958/958 - 3s - 3ms/step - ia: 0.9041 - loss: 0.0609 - mae: 0.1366 - rmse: 0.2253 - smape: 0.3484 - val_ia: 0.7762 - val_loss: 0.0559 - val_mae: 0.1341 - val_rmse: 0.1971 - val_smape: 0.3524

Epoch 71/128

958/958 - 2s - 2ms/step - ia: 0.9039 - loss: 0.0610 - mae: 0.1374 - rmse: 0.2256 - smape: 0.3507 - val_ia: 0.7847 - val_loss: 0.0553 - val_mae: 0.1300 - val_rmse: 0.1957 - val_smape: 0.3476

Epoch 72/128

958/958 - 3s - 3ms/step - ia: 0.9038 - loss: 0.0609 - mae: 0.1369 - rmse: 0.2265 - smape: 0.3489 - val_ia: 0.7840 - val_loss: 0.0552 - val_mae: 0.1307 - val_rmse: 0.1956 - val_smape: 0.3470

Epoch 73/128

958/958 - 2s - 2ms/step - ia: 0.9044 - loss: 0.0609 - mae: 0.1370 - rmse: 0.2261 - smape: 0.3494 - val_ia: 0.7853 - val_loss: 0.0556 - val_mae: 0.1301 - val_rmse: 0.1968 - val_smape: 0.3464

Epoch 74/128

958/958 - 3s - 3ms/step - ia: 0.9042 - loss: 0.0608 - mae: 0.1370 - rmse: 0.2247 - smape: 0.3495 - val_ia: 0.7833 - val_loss: 0.0556 - val_mae: 0.1308 - val_rmse: 0.1968 - val_smape: 0.3475

Epoch 75/128

958/958 - 3s - 3ms/step - ia: 0.9047 - loss: 0.0609 - mae: 0.1366 - rmse: 0.2256 - smape: 0.3489 - val_ia: 0.7809 - val_loss: 0.0554 - val_mae: 0.1320 - val_rmse: 0.1961 - val_smape: 0.3495

Epoch 76/128

958/958 - 6s - 7ms/step - ia: 0.9043 - loss: 0.0608 - mae: 0.1369 - rmse: 0.2259 - smape: 0.3487 - val_ia: 0.7852 - val_loss: 0.0552 - val_mae: 0.1298 - val_rmse: 0.1956 - val_smape: 0.3474

Epoch 77/128

958/958 - 6s - 6ms/step - ia: 0.9039 - loss: 0.0608 - mae: 0.1369 - rmse: 0.2261 - smape: 0.3489 - val_ia: 0.7843 - val_loss: 0.0559 - val_mae: 0.1315 - val_rmse: 0.1971 - val_smape: 0.3499

Epoch 78/128

958/958 - 6s - 6ms/step - ia: 0.9039 - loss: 0.0608 - mae: 0.1371 - rmse: 0.2250 - smape: 0.3498 - val_ia: 0.7829 - val_loss: 0.0553 - val_mae: 0.1305 - val_rmse: 0.1960 - val_smape: 0.3479

Epoch 79/128

958/958 - 11s - 11ms/step - ia: 0.9044 - loss: 0.0608 - mae: 0.1369 - rmse: 0.2249 - smape: 0.3497 - val_ia: 0.7833 - val_loss: 0.0556 - val_mae: 0.1308 - val_rmse: 0.1972 - val_smape: 0.3514

Epoch 80/128

958/958 - 5s - 5ms/step - ia: 0.9042 - loss: 0.0607 - mae: 0.1369 - rmse: 0.2255 - smape: 0.3500 - val_ia: 0.7847 - val_loss: 0.0555 - val_mae: 0.1301 - val_rmse: 0.1966 - val_smape: 0.3490

Epoch 81/128

958/958 - 5s - 5ms/step - ia: 0.9042 - loss: 0.0607 - mae: 0.1368 - rmse: 0.2249 - smape: 0.3497 - val_ia: 0.7861 - val_loss: 0.0553 - val_mae: 0.1304 - val_rmse: 0.1956 - val_smape: 0.3457

Epoch 82/128

958/958 - 6s - 6ms/step - ia: 0.9042 - loss: 0.0607 - mae: 0.1367 - rmse: 0.2254 - smape: 0.3487 - val_ia: 0.7832 - val_loss: 0.0560 - val_mae: 0.1317 - val_rmse: 0.1978 - val_smape: 0.3507

Epoch 83/128

958/958 - 5s - 6ms/step - ia: 0.9043 - loss: 0.0606 - mae: 0.1367 - rmse: 0.2248 - smape: 0.3492 - val_ia: 0.7852 - val_loss: 0.0553 - val_mae: 0.1310 - val_rmse: 0.1957 - val_smape: 0.3470

Epoch 84/128

958/958 - 4s - 5ms/step - ia: 0.9045 - loss: 0.0606 - mae: 0.1367 - rmse: 0.2254 - smape: 0.3493 - val_ia: 0.7826 - val_loss: 0.0556 - val_mae: 0.1309 - val_rmse: 0.1969 - val_smape: 0.3501

Epoch 85/128

958/958 - 4s - 4ms/step - ia: 0.9040 - loss: 0.0607 - mae: 0.1369 - rmse: 0.2256 - smape: 0.3509 - val_ia: 0.7850 - val_loss: 0.0551 - val_mae: 0.1299 - val_rmse: 0.1955 - val_smape: 0.3465

Epoch 86/128

958/958 - 4s - 4ms/step - ia: 0.9042 - loss: 0.0607 - mae: 0.1368 - rmse: 0.2253 - smape: 0.3494 - val_ia: 0.7843 - val_loss: 0.0553 - val_mae: 0.1299 - val_rmse: 0.1961 - val_smape: 0.3481

Epoch 87/128

958/958 - 4s - 4ms/step - ia: 0.9040 - loss: 0.0606 - mae: 0.1365 - rmse: 0.2244 - smape: 0.3496 - val_ia: 0.7830 - val_loss: 0.0557 - val_mae: 0.1319 - val_rmse: 0.1967 - val_smape: 0.3517

Epoch 88/128

958/958 - 5s - 6ms/step - ia: 0.9041 - loss: 0.0606 - mae: 0.1367 - rmse: 0.2253 - smape: 0.3492 - val_ia: 0.7832 - val_loss: 0.0555 - val_mae: 0.1309 - val_rmse: 0.1968 - val_smape: 0.3496

Epoch 89/128

958/958 - 5s - 5ms/step - ia: 0.9042 - loss: 0.0605 - mae: 0.1368 - rmse: 0.2247 - smape: 0.3493 - val_ia: 0.7851 - val_loss: 0.0549 - val_mae: 0.1296 - val_rmse: 0.1951 - val_smape: 0.3468

Epoch 90/128

958/958 - 6s - 7ms/step - ia: 0.9044 - loss: 0.0605 - mae: 0.1366 - rmse: 0.2254 - smape: 0.3493 - val_ia: 0.7824 - val_loss: 0.0551 - val_mae: 0.1309 - val_rmse: 0.1959 - val_smape: 0.3497

Epoch 91/128

958/958 - 6s - 6ms/step - ia: 0.9045 - loss: 0.0605 - mae: 0.1366 - rmse: 0.2244 - smape: 0.3490 - val_ia: 0.7807 - val_loss: 0.0560 - val_mae: 0.1329 - val_rmse: 0.1975 - val_smape: 0.3539

Epoch 92/128

958/958 - 9s - 10ms/step - ia: 0.9043 - loss: 0.0605 - mae: 0.1368 - rmse: 0.2251 - smape: 0.3499 - val_ia: 0.7802 - val_loss: 0.0551 - val_mae: 0.1312 - val_rmse: 0.1962 - val_smape: 0.3491

Epoch 93/128

958/958 - 5s - 5ms/step - ia: 0.9042 - loss: 0.0605 - mae: 0.1368 - rmse: 0.2254 - smape: 0.3492 - val_ia: 0.7742 - val_loss: 0.0556 - val_mae: 0.1344 - val_rmse: 0.1978 - val_smape: 0.3547

Epoch 94/128

958/958 - 4s - 4ms/step - ia: 0.9044 - loss: 0.0604 - mae: 0.1365 - rmse: 0.2248 - smape: 0.3488 - val_ia: 0.7806 - val_loss: 0.0551 - val_mae: 0.1313 - val_rmse: 0.1956 - val_smape: 0.3488

Epoch 95/128

958/958 - 4s - 4ms/step - ia: 0.9039 - loss: 0.0605 - mae: 0.1368 - rmse: 0.2257 - smape: 0.3499 - val_ia: 0.7845 - val_loss: 0.0557 - val_mae: 0.1312 - val_rmse: 0.1968 - val_smape: 0.3496

Epoch 96/128

958/958 - 4s - 4ms/step - ia: 0.9041 - loss: 0.0604 - mae: 0.1366 - rmse: 0.2256 - smape: 0.3494 - val_ia: 0.7811 - val_loss: 0.0556 - val_mae: 0.1323 - val_rmse: 0.1963 - val_smape: 0.3511

Epoch 97/128

958/958 - 6s - 7ms/step - ia: 0.9043 - loss: 0.0604 - mae: 0.1366 - rmse: 0.2251 - smape: 0.3490 - val_ia: 0.7823 - val_loss: 0.0560 - val_mae: 0.1322 - val_rmse: 0.1977 - val_smape: 0.3533

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 14s - 15ms/step - ia: 0.5762 - loss: 0.6947 - mae: 0.5620 - rmse: 0.7930 - smape: 0.9663 - val_ia: 0.4655 - val_loss: 0.3077 - val_mae: 0.3642 - val_rmse: 0.4533 - val_smape: 0.7541

Epoch 2/32

958/958 - 5s - 5ms/step - ia: 0.7035 - loss: 0.3423 - mae: 0.4011 - rmse: 0.5666 - smape: 0.7855 - val_ia: 0.5550 - val_loss: 0.2212 - val_mae: 0.2951 - val_rmse: 0.3776 - val_smape: 0.6331

Epoch 3/32

958/958 - 6s - 6ms/step - ia: 0.7409 - loss: 0.2770 - mae: 0.3557 - rmse: 0.5063 - smape: 0.7156 - val_ia: 0.6171 - val_loss: 0.1746 - val_mae: 0.2535 - val_rmse: 0.3327 - val_smape: 0.5570

Epoch 4/32

958/958 - 5s - 5ms/step - ia: 0.7648 - loss: 0.2419 - mae: 0.3295 - rmse: 0.4717 - smape: 0.6716 - val_ia: 0.6599 - val_loss: 0.1471 - val_mae: 0.2248 - val_rmse: 0.3023 - val_smape: 0.5031

Epoch 5/32

958/958 - 6s - 6ms/step - ia: 0.7783 - loss: 0.2187 - mae: 0.3126 - rmse: 0.4478 - smape: 0.6393 - val_ia: 0.6871 - val_loss: 0.1293 - val_mae: 0.2061 - val_rmse: 0.2832 - val_smape: 0.4696

Epoch 6/32

958/958 - 7s - 7ms/step - ia: 0.7884 - loss: 0.1996 - mae: 0.2998 - rmse: 0.4274 - smape: 0.6205 - val_ia: 0.7098 - val_loss: 0.1174 - val_mae: 0.1929 - val_rmse: 0.2683 - val_smape: 0.4441

Epoch 7/32

958/958 - 10s - 10ms/step - ia: 0.7984 - loss: 0.1862 - mae: 0.2875 - rmse: 0.4116 - smape: 0.5988 - val_ia: 0.7194 - val_loss: 0.1078 - val_mae: 0.1832 - val_rmse: 0.2570 - val_smape: 0.4265

Epoch 8/32

958/958 - 5s - 5ms/step - ia: 0.8058 - loss: 0.1747 - mae: 0.2771 - rmse: 0.3987 - smape: 0.5825 - val_ia: 0.7322 - val_loss: 0.1011 - val_mae: 0.1741 - val_rmse: 0.2479 - val_smape: 0.4085

Epoch 9/32

958/958 - 6s - 6ms/step - ia: 0.8122 - loss: 0.1641 - mae: 0.2691 - rmse: 0.3858 - smape: 0.5717 - val_ia: 0.7380 - val_loss: 0.0971 - val_mae: 0.1698 - val_rmse: 0.2411 - val_smape: 0.4004

Epoch 10/32

958/958 - 4s - 5ms/step - ia: 0.8154 - loss: 0.1569 - mae: 0.2635 - rmse: 0.3775 - smape: 0.5635 - val_ia: 0.7435 - val_loss: 0.0914 - val_mae: 0.1642 - val_rmse: 0.2362 - val_smape: 0.3921

Epoch 11/32

958/958 - 4s - 4ms/step - ia: 0.8208 - loss: 0.1502 - mae: 0.2563 - rmse: 0.3683 - smape: 0.5543 - val_ia: 0.7513 - val_loss: 0.0879 - val_mae: 0.1595 - val_rmse: 0.2302 - val_smape: 0.3852

Epoch 12/32

958/958 - 4s - 4ms/step - ia: 0.8246 - loss: 0.1445 - mae: 0.2508 - rmse: 0.3612 - smape: 0.5421 - val_ia: 0.7518 - val_loss: 0.0853 - val_mae: 0.1574 - val_rmse: 0.2277 - val_smape: 0.3806

Epoch 13/32

958/958 - 5s - 5ms/step - ia: 0.8285 - loss: 0.1385 - mae: 0.2450 - rmse: 0.3528 - smape: 0.5343 - val_ia: 0.7541 - val_loss: 0.0822 - val_mae: 0.1545 - val_rmse: 0.2249 - val_smape: 0.3782

Epoch 14/32

958/958 - 4s - 4ms/step - ia: 0.8312 - loss: 0.1338 - mae: 0.2409 - rmse: 0.3471 - smape: 0.5300 - val_ia: 0.7534 - val_loss: 0.0797 - val_mae: 0.1534 - val_rmse: 0.2210 - val_smape: 0.3755

Epoch 15/32

958/958 - 6s - 6ms/step - ia: 0.8343 - loss: 0.1312 - mae: 0.2367 - rmse: 0.3425 - smape: 0.5229 - val_ia: 0.7609 - val_loss: 0.0771 - val_mae: 0.1493 - val_rmse: 0.2185 - val_smape: 0.3699

Epoch 16/32

958/958 - 5s - 5ms/step - ia: 0.8367 - loss: 0.1283 - mae: 0.2331 - rmse: 0.3381 - smape: 0.5188 - val_ia: 0.7571 - val_loss: 0.0757 - val_mae: 0.1492 - val_rmse: 0.2176 - val_smape: 0.3704

Epoch 17/32

958/958 - 3s - 3ms/step - ia: 0.8379 - loss: 0.1255 - mae: 0.2297 - rmse: 0.3331 - smape: 0.5149 - val_ia: 0.7659 - val_loss: 0.0737 - val_mae: 0.1453 - val_rmse: 0.2148 - val_smape: 0.3623

Epoch 18/32

958/958 - 3s - 3ms/step - ia: 0.8409 - loss: 0.1214 - mae: 0.2262 - rmse: 0.3293 - smape: 0.5071 - val_ia: 0.7671 - val_loss: 0.0719 - val_mae: 0.1440 - val_rmse: 0.2121 - val_smape: 0.3621

Epoch 19/32

958/958 - 5s - 6ms/step - ia: 0.8424 - loss: 0.1189 - mae: 0.2239 - rmse: 0.3251 - smape: 0.5046 - val_ia: 0.7592 - val_loss: 0.0712 - val_mae: 0.1461 - val_rmse: 0.2128 - val_smape: 0.3677

Epoch 20/32

958/958 - 3s - 3ms/step - ia: 0.8442 - loss: 0.1171 - mae: 0.2212 - rmse: 0.3220 - smape: 0.5012 - val_ia: 0.7565 - val_loss: 0.0700 - val_mae: 0.1453 - val_rmse: 0.2117 - val_smape: 0.3646

Epoch 21/32

958/958 - 4s - 4ms/step - ia: 0.8451 - loss: 0.1140 - mae: 0.2192 - rmse: 0.3190 - smape: 0.4992 - val_ia: 0.7570 - val_loss: 0.0688 - val_mae: 0.1445 - val_rmse: 0.2104 - val_smape: 0.3634

Epoch 22/32

958/958 - 5s - 6ms/step - ia: 0.8473 - loss: 0.1117 - mae: 0.2168 - rmse: 0.3157 - smape: 0.4940 - val_ia: 0.7618 - val_loss: 0.0680 - val_mae: 0.1427 - val_rmse: 0.2092 - val_smape: 0.3603

Epoch 23/32

958/958 - 4s - 4ms/step - ia: 0.8489 - loss: 0.1104 - mae: 0.2141 - rmse: 0.3126 - smape: 0.4884 - val_ia: 0.7567 - val_loss: 0.0672 - val_mae: 0.1437 - val_rmse: 0.2095 - val_smape: 0.3630

Epoch 24/32

958/958 - 2s - 2ms/step - ia: 0.8496 - loss: 0.1092 - mae: 0.2126 - rmse: 0.3110 - smape: 0.4873 - val_ia: 0.7539 - val_loss: 0.0665 - val_mae: 0.1442 - val_rmse: 0.2092 - val_smape: 0.3645

Epoch 25/32

958/958 - 3s - 3ms/step - ia: 0.8514 - loss: 0.1068 - mae: 0.2110 - rmse: 0.3069 - smape: 0.4867 - val_ia: 0.7638 - val_loss: 0.0654 - val_mae: 0.1408 - val_rmse: 0.2064 - val_smape: 0.3590

Epoch 26/32

958/958 - 3s - 3ms/step - ia: 0.8526 - loss: 0.1075 - mae: 0.2082 - rmse: 0.3072 - smape: 0.4809 - val_ia: 0.7629 - val_loss: 0.0650 - val_mae: 0.1406 - val_rmse: 0.2067 - val_smape: 0.3586

Epoch 27/32

958/958 - 5s - 5ms/step - ia: 0.8538 - loss: 0.1066 - mae: 0.2075 - rmse: 0.3052 - smape: 0.4796 - val_ia: 0.7608 - val_loss: 0.0644 - val_mae: 0.1409 - val_rmse: 0.2060 - val_smape: 0.3607

Epoch 28/32

958/958 - 5s - 5ms/step - ia: 0.8552 - loss: 0.1028 - mae: 0.2050 - rmse: 0.3002 - smape: 0.4763 - val_ia: 0.7561 - val_loss: 0.0645 - val_mae: 0.1426 - val_rmse: 0.2078 - val_smape: 0.3631

Epoch 29/32

958/958 - 5s - 6ms/step - ia: 0.8549 - loss: 0.1034 - mae: 0.2053 - rmse: 0.3031 - smape: 0.4753 - val_ia: 0.7613 - val_loss: 0.0633 - val_mae: 0.1403 - val_rmse: 0.2051 - val_smape: 0.3600

Epoch 30/32

958/958 - 3s - 3ms/step - ia: 0.8568 - loss: 0.1017 - mae: 0.2032 - rmse: 0.2997 - smape: 0.4727 - val_ia: 0.7580 - val_loss: 0.0630 - val_mae: 0.1409 - val_rmse: 0.2054 - val_smape: 0.3609

Epoch 31/32

958/958 - 6s - 7ms/step - ia: 0.8572 - loss: 0.1000 - mae: 0.2017 - rmse: 0.2963 - smape: 0.4712 - val_ia: 0.7648 - val_loss: 0.0624 - val_mae: 0.1387 - val_rmse: 0.2042 - val_smape: 0.3572

Epoch 32/32

958/958 - 5s - 5ms/step - ia: 0.8585 - loss: 0.0982 - mae: 0.2000 - rmse: 0.2936 - smape: 0.4683 - val_ia: 0.7623 - val_loss: 0.0620 - val_mae: 0.1390 - val_rmse: 0.2040 - val_smape: 0.3583

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:08 504ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 56%|█████▌    | 28/50 [2:22:54<2:45:46, 452.10s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 16s - 16ms/step - ia: 0.8252 - loss: 0.1564 - mae: 0.2329 - rmse: 0.3530 - smape: 0.5225 - val_ia: 0.7367 - val_loss: 0.0695 - val_mae: 0.1592 - val_rmse: 0.2250 - val_smape: 0.4025

Epoch 2/256

958/958 - 8s - 9ms/step - ia: 0.8863 - loss: 0.0739 - mae: 0.1615 - rmse: 0.2515 - smape: 0.3979 - val_ia: 0.7651 - val_loss: 0.0607 - val_mae: 0.1420 - val_rmse: 0.2086 - val_smape: 0.3696

Epoch 3/256

958/958 - 5s - 6ms/step - ia: 0.8916 - loss: 0.0680 - mae: 0.1539 - rmse: 0.2409 - smape: 0.3876 - val_ia: 0.7691 - val_loss: 0.0578 - val_mae: 0.1385 - val_rmse: 0.2016 - val_smape: 0.3642

Epoch 4/256

958/958 - 4s - 4ms/step - ia: 0.8909 - loss: 0.0674 - mae: 0.1539 - rmse: 0.2392 - smape: 0.3881 - val_ia: 0.7590 - val_loss: 0.0595 - val_mae: 0.1463 - val_rmse: 0.2059 - val_smape: 0.3909

Epoch 5/256

958/958 - 5s - 5ms/step - ia: 0.8919 - loss: 0.0666 - mae: 0.1534 - rmse: 0.2379 - smape: 0.3887 - val_ia: 0.7562 - val_loss: 0.0588 - val_mae: 0.1427 - val_rmse: 0.2061 - val_smape: 0.3753

Epoch 6/256

958/958 - 5s - 5ms/step - ia: 0.8919 - loss: 0.0662 - mae: 0.1535 - rmse: 0.2373 - smape: 0.3901 - val_ia: 0.7597 - val_loss: 0.0559 - val_mae: 0.1377 - val_rmse: 0.2000 - val_smape: 0.3612

Epoch 7/256

958/958 - 6s - 7ms/step - ia: 0.8927 - loss: 0.0652 - mae: 0.1522 - rmse: 0.2364 - smape: 0.3837 - val_ia: 0.7481 - val_loss: 0.0605 - val_mae: 0.1514 - val_rmse: 0.2113 - val_smape: 0.3972

Epoch 8/256

958/958 - 6s - 6ms/step - ia: 0.8923 - loss: 0.0647 - mae: 0.1520 - rmse: 0.2359 - smape: 0.3835 - val_ia: 0.7752 - val_loss: 0.0558 - val_mae: 0.1346 - val_rmse: 0.1977 - val_smape: 0.3625

Epoch 9/256

958/958 - 6s - 6ms/step - ia: 0.8943 - loss: 0.0642 - mae: 0.1499 - rmse: 0.2338 - smape: 0.3807 - val_ia: 0.7544 - val_loss: 0.0605 - val_mae: 0.1499 - val_rmse: 0.2101 - val_smape: 0.3755

Epoch 10/256

958/958 - 10s - 10ms/step - ia: 0.8944 - loss: 0.0635 - mae: 0.1498 - rmse: 0.2330 - smape: 0.3815 - val_ia: 0.7644 - val_loss: 0.0571 - val_mae: 0.1374 - val_rmse: 0.2023 - val_smape: 0.3621

Epoch 11/256

958/958 - 6s - 6ms/step - ia: 0.8940 - loss: 0.0637 - mae: 0.1504 - rmse: 0.2336 - smape: 0.3794 - val_ia: 0.7543 - val_loss: 0.0616 - val_mae: 0.1496 - val_rmse: 0.2107 - val_smape: 0.3845

Epoch 12/256

958/958 - 6s - 6ms/step - ia: 0.8951 - loss: 0.0634 - mae: 0.1491 - rmse: 0.2324 - smape: 0.3790 - val_ia: 0.7614 - val_loss: 0.0578 - val_mae: 0.1423 - val_rmse: 0.2024 - val_smape: 0.3756

Epoch 13/256

958/958 - 9s - 9ms/step - ia: 0.8965 - loss: 0.0623 - mae: 0.1472 - rmse: 0.2313 - smape: 0.3740 - val_ia: 0.7497 - val_loss: 0.0583 - val_mae: 0.1433 - val_rmse: 0.2063 - val_smape: 0.3729

Epoch 14/256

958/958 - 4s - 5ms/step - ia: 0.8965 - loss: 0.0618 - mae: 0.1467 - rmse: 0.2297 - smape: 0.3720 - val_ia: 0.7702 - val_loss: 0.0604 - val_mae: 0.1399 - val_rmse: 0.2052 - val_smape: 0.3642

Epoch 15/256

958/958 - 3s - 3ms/step - ia: 0.8961 - loss: 0.0624 - mae: 0.1478 - rmse: 0.2314 - smape: 0.3749 - val_ia: 0.7619 - val_loss: 0.0567 - val_mae: 0.1372 - val_rmse: 0.2011 - val_smape: 0.3581

Epoch 16/256

958/958 - 7s - 8ms/step - ia: 0.8979 - loss: 0.0612 - mae: 0.1451 - rmse: 0.2291 - smape: 0.3705 - val_ia: 0.7696 - val_loss: 0.0565 - val_mae: 0.1366 - val_rmse: 0.1999 - val_smape: 0.3603

Epoch 17/256

958/958 - 6s - 6ms/step - ia: 0.8980 - loss: 0.0608 - mae: 0.1449 - rmse: 0.2286 - smape: 0.3682 - val_ia: 0.7638 - val_loss: 0.0589 - val_mae: 0.1440 - val_rmse: 0.2057 - val_smape: 0.3763

Epoch 18/256

958/958 - 10s - 11ms/step - ia: 0.8977 - loss: 0.0608 - mae: 0.1455 - rmse: 0.2288 - smape: 0.3702 - val_ia: 0.7409 - val_loss: 0.0568 - val_mae: 0.1447 - val_rmse: 0.2036 - val_smape: 0.3674

Epoch 19/256

958/958 - 9s - 9ms/step - ia: 0.8985 - loss: 0.0605 - mae: 0.1447 - rmse: 0.2285 - smape: 0.3698 - val_ia: 0.7712 - val_loss: 0.0550 - val_mae: 0.1344 - val_rmse: 0.1969 - val_smape: 0.3533

Epoch 20/256

958/958 - 4s - 4ms/step - ia: 0.8983 - loss: 0.0607 - mae: 0.1449 - rmse: 0.2281 - smape: 0.3712 - val_ia: 0.7746 - val_loss: 0.0564 - val_mae: 0.1344 - val_rmse: 0.2002 - val_smape: 0.3543

Epoch 21/256

958/958 - 6s - 6ms/step - ia: 0.8989 - loss: 0.0599 - mae: 0.1439 - rmse: 0.2269 - smape: 0.3655 - val_ia: 0.7427 - val_loss: 0.0590 - val_mae: 0.1469 - val_rmse: 0.2063 - val_smape: 0.3704

Epoch 22/256

958/958 - 6s - 6ms/step - ia: 0.8990 - loss: 0.0595 - mae: 0.1432 - rmse: 0.2255 - smape: 0.3643 - val_ia: 0.7721 - val_loss: 0.0585 - val_mae: 0.1380 - val_rmse: 0.2051 - val_smape: 0.3568

Epoch 23/256

958/958 - 5s - 5ms/step - ia: 0.8995 - loss: 0.0594 - mae: 0.1428 - rmse: 0.2263 - smape: 0.3649 - val_ia: 0.7627 - val_loss: 0.0584 - val_mae: 0.1409 - val_rmse: 0.2016 - val_smape: 0.3569

Epoch 24/256

958/958 - 4s - 4ms/step - ia: 0.8986 - loss: 0.0599 - mae: 0.1440 - rmse: 0.2273 - smape: 0.3668 - val_ia: 0.7684 - val_loss: 0.0551 - val_mae: 0.1350 - val_rmse: 0.1973 - val_smape: 0.3539

Epoch 25/256

958/958 - 3s - 3ms/step - ia: 0.9006 - loss: 0.0589 - mae: 0.1422 - rmse: 0.2246 - smape: 0.3636 - val_ia: 0.7755 - val_loss: 0.0553 - val_mae: 0.1340 - val_rmse: 0.1969 - val_smape: 0.3573

Epoch 26/256

958/958 - 5s - 5ms/step - ia: 0.8998 - loss: 0.0590 - mae: 0.1424 - rmse: 0.2262 - smape: 0.3638 - val_ia: 0.7525 - val_loss: 0.0562 - val_mae: 0.1408 - val_rmse: 0.2018 - val_smape: 0.3626

Epoch 27/256

958/958 - 5s - 6ms/step - ia: 0.9000 - loss: 0.0584 - mae: 0.1420 - rmse: 0.2244 - smape: 0.3627 - val_ia: 0.7829 - val_loss: 0.0557 - val_mae: 0.1322 - val_rmse: 0.1981 - val_smape: 0.3479

Epoch 28/256

958/958 - 5s - 5ms/step - ia: 0.9009 - loss: 0.0581 - mae: 0.1409 - rmse: 0.2233 - smape: 0.3593 - val_ia: 0.7726 - val_loss: 0.0556 - val_mae: 0.1357 - val_rmse: 0.1977 - val_smape: 0.3532

Epoch 29/256

958/958 - 3s - 3ms/step - ia: 0.9006 - loss: 0.0585 - mae: 0.1412 - rmse: 0.2243 - smape: 0.3629 - val_ia: 0.7425 - val_loss: 0.0571 - val_mae: 0.1449 - val_rmse: 0.2041 - val_smape: 0.3684

Epoch 30/256

958/958 - 7s - 7ms/step - ia: 0.9000 - loss: 0.0583 - mae: 0.1420 - rmse: 0.2244 - smape: 0.3636 - val_ia: 0.7684 - val_loss: 0.0574 - val_mae: 0.1377 - val_rmse: 0.2022 - val_smape: 0.3586

Epoch 31/256

958/958 - 5s - 6ms/step - ia: 0.9019 - loss: 0.0576 - mae: 0.1399 - rmse: 0.2230 - smape: 0.3589 - val_ia: 0.7405 - val_loss: 0.0567 - val_mae: 0.1464 - val_rmse: 0.2050 - val_smape: 0.3756

Epoch 32/256

958/958 - 5s - 6ms/step - ia: 0.9005 - loss: 0.0576 - mae: 0.1411 - rmse: 0.2233 - smape: 0.3626 - val_ia: 0.7716 - val_loss: 0.0539 - val_mae: 0.1328 - val_rmse: 0.1959 - val_smape: 0.3523

Epoch 33/256

958/958 - 6s - 6ms/step - ia: 0.9015 - loss: 0.0573 - mae: 0.1403 - rmse: 0.2223 - smape: 0.3614 - val_ia: 0.7712 - val_loss: 0.0549 - val_mae: 0.1331 - val_rmse: 0.1964 - val_smape: 0.3509

Epoch 34/256

958/958 - 5s - 5ms/step - ia: 0.9015 - loss: 0.0572 - mae: 0.1403 - rmse: 0.2220 - smape: 0.3594 - val_ia: 0.7521 - val_loss: 0.0559 - val_mae: 0.1410 - val_rmse: 0.2027 - val_smape: 0.3669

Epoch 35/256

958/958 - 6s - 6ms/step - ia: 0.9017 - loss: 0.0572 - mae: 0.1407 - rmse: 0.2218 - smape: 0.3627 - val_ia: 0.7393 - val_loss: 0.0608 - val_mae: 0.1557 - val_rmse: 0.2152 - val_smape: 0.3948

Epoch 36/256

958/958 - 5s - 6ms/step - ia: 0.9024 - loss: 0.0567 - mae: 0.1394 - rmse: 0.2212 - smape: 0.3587 - val_ia: 0.7313 - val_loss: 0.0578 - val_mae: 0.1489 - val_rmse: 0.2087 - val_smape: 0.3861

Epoch 37/256

958/958 - 5s - 5ms/step - ia: 0.9020 - loss: 0.0567 - mae: 0.1394 - rmse: 0.2210 - smape: 0.3572 - val_ia: 0.7808 - val_loss: 0.0555 - val_mae: 0.1338 - val_rmse: 0.1961 - val_smape: 0.3517

Epoch 38/256

958/958 - 11s - 11ms/step - ia: 0.9022 - loss: 0.0565 - mae: 0.1393 - rmse: 0.2207 - smape: 0.3583 - val_ia: 0.7698 - val_loss: 0.0565 - val_mae: 0.1396 - val_rmse: 0.2001 - val_smape: 0.3655

Epoch 39/256

958/958 - 6s - 6ms/step - ia: 0.9015 - loss: 0.0565 - mae: 0.1402 - rmse: 0.2216 - smape: 0.3596 - val_ia: 0.7768 - val_loss: 0.0535 - val_mae: 0.1315 - val_rmse: 0.1944 - val_smape: 0.3491

Epoch 40/256

958/958 - 6s - 6ms/step - ia: 0.9022 - loss: 0.0560 - mae: 0.1391 - rmse: 0.2208 - smape: 0.3576 - val_ia: 0.7774 - val_loss: 0.0544 - val_mae: 0.1330 - val_rmse: 0.1952 - val_smape: 0.3510

Epoch 41/256

958/958 - 5s - 5ms/step - ia: 0.9019 - loss: 0.0558 - mae: 0.1396 - rmse: 0.2203 - smape: 0.3603 - val_ia: 0.7743 - val_loss: 0.0581 - val_mae: 0.1357 - val_rmse: 0.2015 - val_smape: 0.3564

Epoch 42/256

958/958 - 5s - 5ms/step - ia: 0.9031 - loss: 0.0552 - mae: 0.1380 - rmse: 0.2186 - smape: 0.3564 - val_ia: 0.7646 - val_loss: 0.0569 - val_mae: 0.1380 - val_rmse: 0.2017 - val_smape: 0.3631

Epoch 43/256

958/958 - 5s - 5ms/step - ia: 0.9016 - loss: 0.0558 - mae: 0.1398 - rmse: 0.2206 - smape: 0.3605 - val_ia: 0.7692 - val_loss: 0.0567 - val_mae: 0.1402 - val_rmse: 0.2013 - val_smape: 0.3614

Epoch 44/256

958/958 - 5s - 6ms/step - ia: 0.9023 - loss: 0.0552 - mae: 0.1387 - rmse: 0.2186 - smape: 0.3585 - val_ia: 0.7748 - val_loss: 0.0534 - val_mae: 0.1329 - val_rmse: 0.1952 - val_smape: 0.3516

Epoch 45/256

958/958 - 6s - 6ms/step - ia: 0.9028 - loss: 0.0548 - mae: 0.1379 - rmse: 0.2180 - smape: 0.3563 - val_ia: 0.7352 - val_loss: 0.0601 - val_mae: 0.1522 - val_rmse: 0.2127 - val_smape: 0.3979

Epoch 46/256

958/958 - 5s - 5ms/step - ia: 0.9030 - loss: 0.0548 - mae: 0.1385 - rmse: 0.2180 - smape: 0.3591 - val_ia: 0.7621 - val_loss: 0.0564 - val_mae: 0.1396 - val_rmse: 0.1999 - val_smape: 0.3578

Epoch 47/256

958/958 - 5s - 5ms/step - ia: 0.9028 - loss: 0.0547 - mae: 0.1384 - rmse: 0.2179 - smape: 0.3576 - val_ia: 0.7585 - val_loss: 0.0563 - val_mae: 0.1397 - val_rmse: 0.2015 - val_smape: 0.3690

Epoch 48/256

958/958 - 5s - 6ms/step - ia: 0.9033 - loss: 0.0541 - mae: 0.1374 - rmse: 0.2168 - smape: 0.3557 - val_ia: 0.7808 - val_loss: 0.0545 - val_mae: 0.1337 - val_rmse: 0.1952 - val_smape: 0.3524

Epoch 49/256

958/958 - 6s - 6ms/step - ia: 0.9033 - loss: 0.0544 - mae: 0.1377 - rmse: 0.2174 - smape: 0.3564 - val_ia: 0.7801 - val_loss: 0.0539 - val_mae: 0.1318 - val_rmse: 0.1944 - val_smape: 0.3513

Epoch 50/256

958/958 - 6s - 6ms/step - ia: 0.9036 - loss: 0.0539 - mae: 0.1369 - rmse: 0.2163 - smape: 0.3560 - val_ia: 0.7716 - val_loss: 0.0542 - val_mae: 0.1340 - val_rmse: 0.1962 - val_smape: 0.3560

Epoch 51/256

958/958 - 3s - 4ms/step - ia: 0.9035 - loss: 0.0538 - mae: 0.1371 - rmse: 0.2168 - smape: 0.3556 - val_ia: 0.7583 - val_loss: 0.0549 - val_mae: 0.1396 - val_rmse: 0.1995 - val_smape: 0.3663

Epoch 52/256

958/958 - 5s - 5ms/step - ia: 0.9040 - loss: 0.0537 - mae: 0.1368 - rmse: 0.2164 - smape: 0.3552 - val_ia: 0.7484 - val_loss: 0.0568 - val_mae: 0.1440 - val_rmse: 0.2041 - val_smape: 0.3736

Epoch 53/256

958/958 - 3s - 3ms/step - ia: 0.9043 - loss: 0.0530 - mae: 0.1362 - rmse: 0.2147 - smape: 0.3552 - val_ia: 0.7664 - val_loss: 0.0542 - val_mae: 0.1350 - val_rmse: 0.1961 - val_smape: 0.3553

Epoch 54/256

958/958 - 6s - 6ms/step - ia: 0.9041 - loss: 0.0533 - mae: 0.1365 - rmse: 0.2155 - smape: 0.3543 - val_ia: 0.7688 - val_loss: 0.0555 - val_mae: 0.1352 - val_rmse: 0.1965 - val_smape: 0.3549

Epoch 55/256

958/958 - 5s - 5ms/step - ia: 0.9041 - loss: 0.0531 - mae: 0.1367 - rmse: 0.2158 - smape: 0.3563 - val_ia: 0.7590 - val_loss: 0.0576 - val_mae: 0.1406 - val_rmse: 0.2033 - val_smape: 0.3728

Epoch 56/256

958/958 - 3s - 3ms/step - ia: 0.9043 - loss: 0.0530 - mae: 0.1361 - rmse: 0.2149 - smape: 0.3555 - val_ia: 0.7700 - val_loss: 0.0542 - val_mae: 0.1350 - val_rmse: 0.1956 - val_smape: 0.3572

Epoch 57/256

958/958 - 6s - 6ms/step - ia: 0.9038 - loss: 0.0526 - mae: 0.1367 - rmse: 0.2155 - smape: 0.3551 - val_ia: 0.7733 - val_loss: 0.0537 - val_mae: 0.1339 - val_rmse: 0.1953 - val_smape: 0.3566

Epoch 58/256

958/958 - 5s - 6ms/step - ia: 0.9039 - loss: 0.0525 - mae: 0.1367 - rmse: 0.2144 - smape: 0.3576 - val_ia: 0.7745 - val_loss: 0.0547 - val_mae: 0.1349 - val_rmse: 0.1959 - val_smape: 0.3563

Epoch 59/256

958/958 - 5s - 5ms/step - ia: 0.9048 - loss: 0.0524 - mae: 0.1359 - rmse: 0.2140 - smape: 0.3535 - val_ia: 0.7664 - val_loss: 0.0572 - val_mae: 0.1388 - val_rmse: 0.2036 - val_smape: 0.3651

Epoch 59: early stopping

Restoring model weights from the end of the best epoch: 44.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 33s 245ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 58%|█████▊    | 29/50 [2:28:37<2:26:44, 419.25s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

958/958 - 9s - 9ms/step - ia: 0.6706 - loss: 0.3823 - mae: 0.4272 - rmse: 0.5836 - smape: 0.8548 - val_ia: 0.6250 - val_loss: 0.1403 - val_mae: 0.2382 - val_rmse: 0.3160 - val_smape: 0.5579

Epoch 2/64

958/958 - 5s - 5ms/step - ia: 0.7790 - loss: 0.1964 - mae: 0.3121 - rmse: 0.4289 - smape: 0.6614 - val_ia: 0.6977 - val_loss: 0.0991 - val_mae: 0.1923 - val_rmse: 0.2637 - val_smape: 0.4609

Epoch 3/64

958/958 - 5s - 5ms/step - ia: 0.8004 - loss: 0.1628 - mae: 0.2849 - rmse: 0.3903 - smape: 0.6185 - val_ia: 0.7179 - val_loss: 0.0836 - val_mae: 0.1737 - val_rmse: 0.2463 - val_smape: 0.4368

Epoch 4/64

958/958 - 5s - 5ms/step - ia: 0.8161 - loss: 0.1393 - mae: 0.2627 - rmse: 0.3604 - smape: 0.5832 - val_ia: 0.7350 - val_loss: 0.0749 - val_mae: 0.1622 - val_rmse: 0.2300 - val_smape: 0.4074

Epoch 5/64

958/958 - 6s - 6ms/step - ia: 0.8254 - loss: 0.1292 - mae: 0.2499 - rmse: 0.3457 - smape: 0.5597 - val_ia: 0.7535 - val_loss: 0.0703 - val_mae: 0.1523 - val_rmse: 0.2222 - val_smape: 0.3891

Epoch 6/64

958/958 - 4s - 4ms/step - ia: 0.8318 - loss: 0.1209 - mae: 0.2408 - rmse: 0.3337 - smape: 0.5444 - val_ia: 0.7604 - val_loss: 0.0675 - val_mae: 0.1484 - val_rmse: 0.2175 - val_smape: 0.3793

Epoch 7/64

958/958 - 5s - 5ms/step - ia: 0.8393 - loss: 0.1129 - mae: 0.2300 - rmse: 0.3218 - smape: 0.5251 - val_ia: 0.7636 - val_loss: 0.0663 - val_mae: 0.1462 - val_rmse: 0.2161 - val_smape: 0.3757

Epoch 8/64

958/958 - 5s - 5ms/step - ia: 0.8447 - loss: 0.1083 - mae: 0.2224 - rmse: 0.3137 - smape: 0.5128 - val_ia: 0.7712 - val_loss: 0.0643 - val_mae: 0.1422 - val_rmse: 0.2114 - val_smape: 0.3681

Epoch 9/64

958/958 - 7s - 7ms/step - ia: 0.8492 - loss: 0.1040 - mae: 0.2162 - rmse: 0.3068 - smape: 0.5013 - val_ia: 0.7740 - val_loss: 0.0636 - val_mae: 0.1410 - val_rmse: 0.2090 - val_smape: 0.3628

Epoch 10/64

958/958 - 10s - 10ms/step - ia: 0.8514 - loss: 0.1002 - mae: 0.2116 - rmse: 0.3006 - smape: 0.4920 - val_ia: 0.7749 - val_loss: 0.0632 - val_mae: 0.1405 - val_rmse: 0.2087 - val_smape: 0.3610

Epoch 11/64

958/958 - 5s - 5ms/step - ia: 0.8555 - loss: 0.0982 - mae: 0.2069 - rmse: 0.2971 - smape: 0.4820 - val_ia: 0.7758 - val_loss: 0.0626 - val_mae: 0.1388 - val_rmse: 0.2068 - val_smape: 0.3600

Epoch 12/64

958/958 - 6s - 6ms/step - ia: 0.8581 - loss: 0.0964 - mae: 0.2034 - rmse: 0.2943 - smape: 0.4757 - val_ia: 0.7697 - val_loss: 0.0634 - val_mae: 0.1410 - val_rmse: 0.2091 - val_smape: 0.3629

Epoch 13/64

958/958 - 5s - 5ms/step - ia: 0.8605 - loss: 0.0941 - mae: 0.1998 - rmse: 0.2894 - smape: 0.4686 - val_ia: 0.7768 - val_loss: 0.0621 - val_mae: 0.1381 - val_rmse: 0.2049 - val_smape: 0.3557

Epoch 14/64

958/958 - 6s - 6ms/step - ia: 0.8612 - loss: 0.0927 - mae: 0.1984 - rmse: 0.2873 - smape: 0.4678 - val_ia: 0.7813 - val_loss: 0.0617 - val_mae: 0.1367 - val_rmse: 0.2056 - val_smape: 0.3534

Epoch 15/64

958/958 - 6s - 6ms/step - ia: 0.8637 - loss: 0.0916 - mae: 0.1955 - rmse: 0.2860 - smape: 0.4615 - val_ia: 0.7785 - val_loss: 0.0614 - val_mae: 0.1363 - val_rmse: 0.2038 - val_smape: 0.3533

Epoch 16/64

958/958 - 5s - 5ms/step - ia: 0.8653 - loss: 0.0903 - mae: 0.1926 - rmse: 0.2831 - smape: 0.4571 - val_ia: 0.7823 - val_loss: 0.0609 - val_mae: 0.1358 - val_rmse: 0.2027 - val_smape: 0.3517

Epoch 17/64

958/958 - 6s - 6ms/step - ia: 0.8663 - loss: 0.0895 - mae: 0.1926 - rmse: 0.2819 - smape: 0.4542 - val_ia: 0.7807 - val_loss: 0.0607 - val_mae: 0.1350 - val_rmse: 0.2026 - val_smape: 0.3499

Epoch 18/64

958/958 - 6s - 6ms/step - ia: 0.8674 - loss: 0.0886 - mae: 0.1901 - rmse: 0.2796 - smape: 0.4498 - val_ia: 0.7828 - val_loss: 0.0603 - val_mae: 0.1347 - val_rmse: 0.2029 - val_smape: 0.3494

Epoch 19/64

958/958 - 6s - 6ms/step - ia: 0.8679 - loss: 0.0875 - mae: 0.1887 - rmse: 0.2785 - smape: 0.4473 - val_ia: 0.7845 - val_loss: 0.0605 - val_mae: 0.1344 - val_rmse: 0.2013 - val_smape: 0.3473

Epoch 20/64

958/958 - 5s - 6ms/step - ia: 0.8697 - loss: 0.0863 - mae: 0.1868 - rmse: 0.2758 - smape: 0.4482 - val_ia: 0.7808 - val_loss: 0.0600 - val_mae: 0.1355 - val_rmse: 0.2013 - val_smape: 0.3508

Epoch 21/64

958/958 - 5s - 5ms/step - ia: 0.8709 - loss: 0.0856 - mae: 0.1854 - rmse: 0.2745 - smape: 0.4419 - val_ia: 0.7834 - val_loss: 0.0606 - val_mae: 0.1351 - val_rmse: 0.2045 - val_smape: 0.3519

Epoch 22/64

958/958 - 5s - 5ms/step - ia: 0.8712 - loss: 0.0851 - mae: 0.1847 - rmse: 0.2731 - smape: 0.4404 - val_ia: 0.7825 - val_loss: 0.0597 - val_mae: 0.1340 - val_rmse: 0.2016 - val_smape: 0.3482

Epoch 23/64

958/958 - 6s - 6ms/step - ia: 0.8732 - loss: 0.0836 - mae: 0.1823 - rmse: 0.2705 - smape: 0.4377 - val_ia: 0.7808 - val_loss: 0.0595 - val_mae: 0.1343 - val_rmse: 0.2017 - val_smape: 0.3511

Epoch 24/64

958/958 - 6s - 6ms/step - ia: 0.8735 - loss: 0.0836 - mae: 0.1819 - rmse: 0.2707 - smape: 0.4353 - val_ia: 0.7787 - val_loss: 0.0599 - val_mae: 0.1348 - val_rmse: 0.2022 - val_smape: 0.3514

Epoch 25/64

958/958 - 5s - 5ms/step - ia: 0.8733 - loss: 0.0838 - mae: 0.1820 - rmse: 0.2709 - smape: 0.4380 - val_ia: 0.7843 - val_loss: 0.0592 - val_mae: 0.1328 - val_rmse: 0.1994 - val_smape: 0.3467

Epoch 26/64

958/958 - 6s - 7ms/step - ia: 0.8741 - loss: 0.0821 - mae: 0.1802 - rmse: 0.2678 - smape: 0.4345 - val_ia: 0.7829 - val_loss: 0.0587 - val_mae: 0.1327 - val_rmse: 0.1991 - val_smape: 0.3472

Epoch 27/64

958/958 - 9s - 10ms/step - ia: 0.8743 - loss: 0.0825 - mae: 0.1802 - rmse: 0.2695 - smape: 0.4323 - val_ia: 0.7832 - val_loss: 0.0587 - val_mae: 0.1328 - val_rmse: 0.2002 - val_smape: 0.3481

Epoch 28/64

958/958 - 6s - 6ms/step - ia: 0.8749 - loss: 0.0821 - mae: 0.1785 - rmse: 0.2678 - smape: 0.4301 - val_ia: 0.7790 - val_loss: 0.0588 - val_mae: 0.1336 - val_rmse: 0.2000 - val_smape: 0.3491

Epoch 29/64

958/958 - 5s - 6ms/step - ia: 0.8754 - loss: 0.0813 - mae: 0.1779 - rmse: 0.2664 - smape: 0.4294 - val_ia: 0.7870 - val_loss: 0.0579 - val_mae: 0.1312 - val_rmse: 0.1983 - val_smape: 0.3441

Epoch 30/64

958/958 - 5s - 6ms/step - ia: 0.8768 - loss: 0.0802 - mae: 0.1763 - rmse: 0.2645 - smape: 0.4285 - val_ia: 0.7828 - val_loss: 0.0582 - val_mae: 0.1321 - val_rmse: 0.1998 - val_smape: 0.3473

Epoch 31/64

958/958 - 9s - 10ms/step - ia: 0.8766 - loss: 0.0807 - mae: 0.1769 - rmse: 0.2653 - smape: 0.4264 - val_ia: 0.7754 - val_loss: 0.0585 - val_mae: 0.1341 - val_rmse: 0.2007 - val_smape: 0.3521

Epoch 32/64

958/958 - 5s - 5ms/step - ia: 0.8776 - loss: 0.0798 - mae: 0.1751 - rmse: 0.2641 - smape: 0.4260 - val_ia: 0.7853 - val_loss: 0.0575 - val_mae: 0.1313 - val_rmse: 0.1978 - val_smape: 0.3459

Epoch 33/64

958/958 - 4s - 4ms/step - ia: 0.8770 - loss: 0.0794 - mae: 0.1755 - rmse: 0.2626 - smape: 0.4269 - val_ia: 0.7808 - val_loss: 0.0579 - val_mae: 0.1324 - val_rmse: 0.1980 - val_smape: 0.3483

Epoch 34/64

958/958 - 6s - 6ms/step - ia: 0.8783 - loss: 0.0791 - mae: 0.1739 - rmse: 0.2624 - smape: 0.4209 - val_ia: 0.7808 - val_loss: 0.0576 - val_mae: 0.1315 - val_rmse: 0.1984 - val_smape: 0.3465

Epoch 35/64

958/958 - 5s - 5ms/step - ia: 0.8787 - loss: 0.0790 - mae: 0.1734 - rmse: 0.2608 - smape: 0.4216 - val_ia: 0.7792 - val_loss: 0.0579 - val_mae: 0.1329 - val_rmse: 0.1996 - val_smape: 0.3501

Epoch 36/64

958/958 - 4s - 4ms/step - ia: 0.8795 - loss: 0.0783 - mae: 0.1728 - rmse: 0.2605 - smape: 0.4236 - val_ia: 0.7810 - val_loss: 0.0577 - val_mae: 0.1325 - val_rmse: 0.1991 - val_smape: 0.3503

Epoch 37/64

958/958 - 3s - 3ms/step - ia: 0.8797 - loss: 0.0770 - mae: 0.1721 - rmse: 0.2586 - smape: 0.4203 - val_ia: 0.7778 - val_loss: 0.0581 - val_mae: 0.1343 - val_rmse: 0.1990 - val_smape: 0.3526

Epoch 38/64

958/958 - 5s - 6ms/step - ia: 0.8801 - loss: 0.0773 - mae: 0.1716 - rmse: 0.2582 - smape: 0.4186 - val_ia: 0.7830 - val_loss: 0.0573 - val_mae: 0.1319 - val_rmse: 0.1981 - val_smape: 0.3484

Epoch 39/64

958/958 - 5s - 5ms/step - ia: 0.8803 - loss: 0.0763 - mae: 0.1708 - rmse: 0.2577 - smape: 0.4192 - val_ia: 0.7853 - val_loss: 0.0568 - val_mae: 0.1305 - val_rmse: 0.1967 - val_smape: 0.3450

Epoch 40/64

958/958 - 3s - 3ms/step - ia: 0.8808 - loss: 0.0764 - mae: 0.1700 - rmse: 0.2580 - smape: 0.4169 - val_ia: 0.7773 - val_loss: 0.0574 - val_mae: 0.1327 - val_rmse: 0.1997 - val_smape: 0.3514

Epoch 41/64

958/958 - 8s - 9ms/step - ia: 0.8809 - loss: 0.0767 - mae: 0.1705 - rmse: 0.2571 - smape: 0.4189 - val_ia: 0.7758 - val_loss: 0.0568 - val_mae: 0.1326 - val_rmse: 0.1974 - val_smape: 0.3497

Epoch 42/64

958/958 - 5s - 5ms/step - ia: 0.8811 - loss: 0.0764 - mae: 0.1697 - rmse: 0.2569 - smape: 0.4145 - val_ia: 0.7824 - val_loss: 0.0568 - val_mae: 0.1310 - val_rmse: 0.1972 - val_smape: 0.3467

Epoch 43/64

958/958 - 4s - 4ms/step - ia: 0.8814 - loss: 0.0760 - mae: 0.1694 - rmse: 0.2555 - smape: 0.4137 - val_ia: 0.7665 - val_loss: 0.0576 - val_mae: 0.1362 - val_rmse: 0.2012 - val_smape: 0.3579

Epoch 44/64

958/958 - 4s - 4ms/step - ia: 0.8818 - loss: 0.0755 - mae: 0.1689 - rmse: 0.2552 - smape: 0.4169 - val_ia: 0.7867 - val_loss: 0.0565 - val_mae: 0.1305 - val_rmse: 0.1956 - val_smape: 0.3490

Epoch 45/64

958/958 - 4s - 4ms/step - ia: 0.8829 - loss: 0.0751 - mae: 0.1676 - rmse: 0.2547 - smape: 0.4135 - val_ia: 0.7796 - val_loss: 0.0567 - val_mae: 0.1319 - val_rmse: 0.1975 - val_smape: 0.3486

Epoch 46/64

958/958 - 5s - 6ms/step - ia: 0.8824 - loss: 0.0748 - mae: 0.1676 - rmse: 0.2543 - smape: 0.4112 - val_ia: 0.7693 - val_loss: 0.0569 - val_mae: 0.1346 - val_rmse: 0.1999 - val_smape: 0.3555

Epoch 47/64

958/958 - 4s - 4ms/step - ia: 0.8820 - loss: 0.0750 - mae: 0.1678 - rmse: 0.2541 - smape: 0.4143 - val_ia: 0.7852 - val_loss: 0.0560 - val_mae: 0.1301 - val_rmse: 0.1954 - val_smape: 0.3466

Epoch 48/64

958/958 - 5s - 5ms/step - ia: 0.8823 - loss: 0.0749 - mae: 0.1676 - rmse: 0.2548 - smape: 0.4114 - val_ia: 0.7821 - val_loss: 0.0559 - val_mae: 0.1304 - val_rmse: 0.1951 - val_smape: 0.3474

Epoch 49/64

958/958 - 3s - 3ms/step - ia: 0.8835 - loss: 0.0743 - mae: 0.1663 - rmse: 0.2530 - smape: 0.4099 - val_ia: 0.7725 - val_loss: 0.0564 - val_mae: 0.1330 - val_rmse: 0.1985 - val_smape: 0.3510

Epoch 50/64

958/958 - 5s - 5ms/step - ia: 0.8831 - loss: 0.0743 - mae: 0.1661 - rmse: 0.2530 - smape: 0.4112 - val_ia: 0.7813 - val_loss: 0.0565 - val_mae: 0.1316 - val_rmse: 0.1961 - val_smape: 0.3486

Epoch 51/64

958/958 - 3s - 3ms/step - ia: 0.8835 - loss: 0.0743 - mae: 0.1657 - rmse: 0.2532 - smape: 0.4094 - val_ia: 0.7797 - val_loss: 0.0560 - val_mae: 0.1314 - val_rmse: 0.1959 - val_smape: 0.3490

Epoch 52/64

958/958 - 3s - 3ms/step - ia: 0.8846 - loss: 0.0738 - mae: 0.1647 - rmse: 0.2517 - smape: 0.4053 - val_ia: 0.7759 - val_loss: 0.0562 - val_mae: 0.1320 - val_rmse: 0.1977 - val_smape: 0.3501

Epoch 53/64

958/958 - 2s - 3ms/step - ia: 0.8836 - loss: 0.0737 - mae: 0.1657 - rmse: 0.2521 - smape: 0.4100 - val_ia: 0.7846 - val_loss: 0.0557 - val_mae: 0.1292 - val_rmse: 0.1954 - val_smape: 0.3438

Epoch 54/64

958/958 - 3s - 3ms/step - ia: 0.8837 - loss: 0.0734 - mae: 0.1655 - rmse: 0.2514 - smape: 0.4084 - val_ia: 0.7805 - val_loss: 0.0555 - val_mae: 0.1305 - val_rmse: 0.1952 - val_smape: 0.3477

Epoch 55/64

958/958 - 2s - 2ms/step - ia: 0.8843 - loss: 0.0737 - mae: 0.1647 - rmse: 0.2519 - smape: 0.4082 - val_ia: 0.7780 - val_loss: 0.0558 - val_mae: 0.1318 - val_rmse: 0.1966 - val_smape: 0.3493

Epoch 56/64

958/958 - 2s - 2ms/step - ia: 0.8838 - loss: 0.0740 - mae: 0.1653 - rmse: 0.2519 - smape: 0.4088 - val_ia: 0.7711 - val_loss: 0.0560 - val_mae: 0.1332 - val_rmse: 0.1976 - val_smape: 0.3520

Epoch 57/64

958/958 - 2s - 2ms/step - ia: 0.8840 - loss: 0.0737 - mae: 0.1652 - rmse: 0.2523 - smape: 0.4082 - val_ia: 0.7848 - val_loss: 0.0554 - val_mae: 0.1297 - val_rmse: 0.1943 - val_smape: 0.3483

Epoch 58/64

958/958 - 4s - 4ms/step - ia: 0.8842 - loss: 0.0732 - mae: 0.1645 - rmse: 0.2512 - smape: 0.4066 - val_ia: 0.7822 - val_loss: 0.0561 - val_mae: 0.1323 - val_rmse: 0.1961 - val_smape: 0.3503

Epoch 59/64

958/958 - 5s - 6ms/step - ia: 0.8843 - loss: 0.0734 - mae: 0.1644 - rmse: 0.2506 - smape: 0.4084 - val_ia: 0.7810 - val_loss: 0.0555 - val_mae: 0.1304 - val_rmse: 0.1953 - val_smape: 0.3461

Epoch 60/64

958/958 - 4s - 5ms/step - ia: 0.8851 - loss: 0.0722 - mae: 0.1631 - rmse: 0.2490 - smape: 0.4056 - val_ia: 0.7758 - val_loss: 0.0559 - val_mae: 0.1325 - val_rmse: 0.1967 - val_smape: 0.3506

Epoch 61/64

958/958 - 2s - 2ms/step - ia: 0.8856 - loss: 0.0719 - mae: 0.1622 - rmse: 0.2493 - smape: 0.4036 - val_ia: 0.7726 - val_loss: 0.0570 - val_mae: 0.1345 - val_rmse: 0.1995 - val_smape: 0.3560

Epoch 62/64

958/958 - 2s - 2ms/step - ia: 0.8856 - loss: 0.0721 - mae: 0.1628 - rmse: 0.2485 - smape: 0.4056 - val_ia: 0.7842 - val_loss: 0.0557 - val_mae: 0.1307 - val_rmse: 0.1953 - val_smape: 0.3475

Epoch 63/64

958/958 - 5s - 6ms/step - ia: 0.8862 - loss: 0.0720 - mae: 0.1620 - rmse: 0.2483 - smape: 0.4033 - val_ia: 0.7751 - val_loss: 0.0555 - val_mae: 0.1321 - val_rmse: 0.1963 - val_smape: 0.3502

Epoch 64/64

958/958 - 5s - 6ms/step - ia: 0.8857 - loss: 0.0718 - mae: 0.1626 - rmse: 0.2486 - smape: 0.4044 - val_ia: 0.7670 - val_loss: 0.0559 - val_mae: 0.1356 - val_rmse: 0.1974 - val_smape: 0.3578

Restoring model weights from the end of the best epoch: 57.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:18 581ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 60%|██████    | 30/50 [2:33:57<2:09:50, 389.51s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 20s - 21ms/step - ia: 0.6106 - loss: 0.4366 - mae: 0.4403 - rmse: 0.6246 - smape: 0.9048 - val_ia: 0.5318 - val_loss: 0.1935 - val_mae: 0.2977 - val_rmse: 0.3820 - val_smape: 0.6486

Epoch 2/128

958/958 - 6s - 6ms/step - ia: 0.7968 - loss: 0.1804 - mae: 0.2786 - rmse: 0.4087 - smape: 0.6048 - val_ia: 0.6036 - val_loss: 0.1354 - val_mae: 0.2449 - val_rmse: 0.3247 - val_smape: 0.5649

Epoch 3/128

958/958 - 6s - 6ms/step - ia: 0.8239 - loss: 0.1418 - mae: 0.2439 - rmse: 0.3602 - smape: 0.5492 - val_ia: 0.6297 - val_loss: 0.1174 - val_mae: 0.2271 - val_rmse: 0.3029 - val_smape: 0.5352

Epoch 4/128

958/958 - 5s - 5ms/step - ia: 0.8368 - loss: 0.1243 - mae: 0.2273 - rmse: 0.3366 - smape: 0.5232 - val_ia: 0.6463 - val_loss: 0.1065 - val_mae: 0.2148 - val_rmse: 0.2897 - val_smape: 0.5164

Epoch 5/128

958/958 - 6s - 6ms/step - ia: 0.8459 - loss: 0.1126 - mae: 0.2150 - rmse: 0.3195 - smape: 0.5035 - val_ia: 0.6638 - val_loss: 0.0975 - val_mae: 0.2035 - val_rmse: 0.2761 - val_smape: 0.4962

Epoch 6/128

958/958 - 10s - 10ms/step - ia: 0.8521 - loss: 0.1042 - mae: 0.2060 - rmse: 0.3068 - smape: 0.4884 - val_ia: 0.6731 - val_loss: 0.0920 - val_mae: 0.1970 - val_rmse: 0.2689 - val_smape: 0.4853

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.8581 - loss: 0.0976 - mae: 0.1987 - rmse: 0.2954 - smape: 0.4766 - val_ia: 0.6793 - val_loss: 0.0872 - val_mae: 0.1913 - val_rmse: 0.2620 - val_smape: 0.4763

Epoch 8/128

958/958 - 6s - 7ms/step - ia: 0.8630 - loss: 0.0925 - mae: 0.1930 - rmse: 0.2881 - smape: 0.4667 - val_ia: 0.6914 - val_loss: 0.0829 - val_mae: 0.1846 - val_rmse: 0.2534 - val_smape: 0.4624

Epoch 9/128

958/958 - 9s - 9ms/step - ia: 0.8656 - loss: 0.0885 - mae: 0.1883 - rmse: 0.2816 - smape: 0.4587 - val_ia: 0.6991 - val_loss: 0.0797 - val_mae: 0.1802 - val_rmse: 0.2485 - val_smape: 0.4539

Epoch 10/128

958/958 - 4s - 4ms/step - ia: 0.8694 - loss: 0.0852 - mae: 0.1843 - rmse: 0.2756 - smape: 0.4516 - val_ia: 0.7027 - val_loss: 0.0772 - val_mae: 0.1769 - val_rmse: 0.2449 - val_smape: 0.4483

Epoch 11/128

958/958 - 5s - 5ms/step - ia: 0.8710 - loss: 0.0825 - mae: 0.1811 - rmse: 0.2706 - smape: 0.4459 - val_ia: 0.7080 - val_loss: 0.0757 - val_mae: 0.1747 - val_rmse: 0.2420 - val_smape: 0.4436

Epoch 12/128

958/958 - 5s - 5ms/step - ia: 0.8734 - loss: 0.0802 - mae: 0.1782 - rmse: 0.2664 - smape: 0.4401 - val_ia: 0.7070 - val_loss: 0.0747 - val_mae: 0.1738 - val_rmse: 0.2416 - val_smape: 0.4430

Epoch 13/128

958/958 - 3s - 3ms/step - ia: 0.8754 - loss: 0.0782 - mae: 0.1755 - rmse: 0.2631 - smape: 0.4360 - val_ia: 0.7130 - val_loss: 0.0725 - val_mae: 0.1708 - val_rmse: 0.2364 - val_smape: 0.4366

Epoch 14/128

958/958 - 3s - 3ms/step - ia: 0.8770 - loss: 0.0765 - mae: 0.1734 - rmse: 0.2604 - smape: 0.4318 - val_ia: 0.7170 - val_loss: 0.0718 - val_mae: 0.1691 - val_rmse: 0.2349 - val_smape: 0.4328

Epoch 15/128

958/958 - 3s - 4ms/step - ia: 0.8785 - loss: 0.0750 - mae: 0.1716 - rmse: 0.2575 - smape: 0.4281 - val_ia: 0.7178 - val_loss: 0.0709 - val_mae: 0.1675 - val_rmse: 0.2337 - val_smape: 0.4296

Epoch 16/128

958/958 - 3s - 4ms/step - ia: 0.8797 - loss: 0.0737 - mae: 0.1698 - rmse: 0.2550 - smape: 0.4245 - val_ia: 0.7202 - val_loss: 0.0707 - val_mae: 0.1667 - val_rmse: 0.2338 - val_smape: 0.4288

Epoch 17/128

958/958 - 6s - 6ms/step - ia: 0.8810 - loss: 0.0724 - mae: 0.1681 - rmse: 0.2530 - smape: 0.4213 - val_ia: 0.7218 - val_loss: 0.0701 - val_mae: 0.1652 - val_rmse: 0.2323 - val_smape: 0.4248

Epoch 18/128

958/958 - 4s - 4ms/step - ia: 0.8819 - loss: 0.0713 - mae: 0.1667 - rmse: 0.2514 - smape: 0.4194 - val_ia: 0.7225 - val_loss: 0.0696 - val_mae: 0.1653 - val_rmse: 0.2323 - val_smape: 0.4253

Epoch 19/128

958/958 - 7s - 7ms/step - ia: 0.8832 - loss: 0.0703 - mae: 0.1650 - rmse: 0.2494 - smape: 0.4156 - val_ia: 0.7274 - val_loss: 0.0678 - val_mae: 0.1624 - val_rmse: 0.2276 - val_smape: 0.4184

Epoch 20/128

958/958 - 6s - 6ms/step - ia: 0.8840 - loss: 0.0694 - mae: 0.1635 - rmse: 0.2466 - smape: 0.4134 - val_ia: 0.7246 - val_loss: 0.0677 - val_mae: 0.1632 - val_rmse: 0.2282 - val_smape: 0.4200

Epoch 21/128

958/958 - 6s - 6ms/step - ia: 0.8849 - loss: 0.0686 - mae: 0.1626 - rmse: 0.2456 - smape: 0.4111 - val_ia: 0.7280 - val_loss: 0.0669 - val_mae: 0.1610 - val_rmse: 0.2265 - val_smape: 0.4158

Epoch 22/128

958/958 - 9s - 10ms/step - ia: 0.8861 - loss: 0.0677 - mae: 0.1614 - rmse: 0.2442 - smape: 0.4086 - val_ia: 0.7295 - val_loss: 0.0674 - val_mae: 0.1615 - val_rmse: 0.2268 - val_smape: 0.4149

Epoch 23/128

958/958 - 7s - 7ms/step - ia: 0.8870 - loss: 0.0671 - mae: 0.1603 - rmse: 0.2431 - smape: 0.4065 - val_ia: 0.7324 - val_loss: 0.0663 - val_mae: 0.1602 - val_rmse: 0.2247 - val_smape: 0.4130

Epoch 24/128

958/958 - 5s - 6ms/step - ia: 0.8872 - loss: 0.0664 - mae: 0.1595 - rmse: 0.2414 - smape: 0.4050 - val_ia: 0.7324 - val_loss: 0.0660 - val_mae: 0.1589 - val_rmse: 0.2246 - val_smape: 0.4098

Epoch 25/128

958/958 - 11s - 11ms/step - ia: 0.8882 - loss: 0.0657 - mae: 0.1586 - rmse: 0.2403 - smape: 0.4029 - val_ia: 0.7310 - val_loss: 0.0660 - val_mae: 0.1593 - val_rmse: 0.2250 - val_smape: 0.4119

Epoch 26/128

958/958 - 6s - 6ms/step - ia: 0.8885 - loss: 0.0652 - mae: 0.1578 - rmse: 0.2394 - smape: 0.4011 - val_ia: 0.7352 - val_loss: 0.0650 - val_mae: 0.1574 - val_rmse: 0.2222 - val_smape: 0.4063

Epoch 27/128

958/958 - 9s - 10ms/step - ia: 0.8890 - loss: 0.0645 - mae: 0.1568 - rmse: 0.2382 - smape: 0.3998 - val_ia: 0.7322 - val_loss: 0.0650 - val_mae: 0.1580 - val_rmse: 0.2227 - val_smape: 0.4078

Epoch 28/128

958/958 - 5s - 5ms/step - ia: 0.8900 - loss: 0.0640 - mae: 0.1560 - rmse: 0.2371 - smape: 0.3986 - val_ia: 0.7349 - val_loss: 0.0649 - val_mae: 0.1574 - val_rmse: 0.2218 - val_smape: 0.4058

Epoch 29/128

958/958 - 5s - 5ms/step - ia: 0.8901 - loss: 0.0636 - mae: 0.1555 - rmse: 0.2366 - smape: 0.3967 - val_ia: 0.7361 - val_loss: 0.0645 - val_mae: 0.1563 - val_rmse: 0.2216 - val_smape: 0.4047

Epoch 30/128

958/958 - 7s - 7ms/step - ia: 0.8910 - loss: 0.0631 - mae: 0.1544 - rmse: 0.2349 - smape: 0.3941 - val_ia: 0.7371 - val_loss: 0.0642 - val_mae: 0.1559 - val_rmse: 0.2207 - val_smape: 0.4039

Epoch 31/128

958/958 - 10s - 10ms/step - ia: 0.8911 - loss: 0.0626 - mae: 0.1541 - rmse: 0.2340 - smape: 0.3945 - val_ia: 0.7390 - val_loss: 0.0646 - val_mae: 0.1562 - val_rmse: 0.2211 - val_smape: 0.4038

Epoch 32/128

958/958 - 10s - 11ms/step - ia: 0.8920 - loss: 0.0623 - mae: 0.1534 - rmse: 0.2338 - smape: 0.3931 - val_ia: 0.7375 - val_loss: 0.0644 - val_mae: 0.1557 - val_rmse: 0.2215 - val_smape: 0.4027

Epoch 33/128

958/958 - 5s - 5ms/step - ia: 0.8924 - loss: 0.0617 - mae: 0.1527 - rmse: 0.2322 - smape: 0.3916 - val_ia: 0.7364 - val_loss: 0.0649 - val_mae: 0.1579 - val_rmse: 0.2209 - val_smape: 0.4056

Epoch 34/128

958/958 - 6s - 6ms/step - ia: 0.8924 - loss: 0.0615 - mae: 0.1524 - rmse: 0.2322 - smape: 0.3910 - val_ia: 0.7428 - val_loss: 0.0641 - val_mae: 0.1547 - val_rmse: 0.2204 - val_smape: 0.3990

Epoch 35/128

958/958 - 11s - 11ms/step - ia: 0.8933 - loss: 0.0611 - mae: 0.1516 - rmse: 0.2308 - smape: 0.3888 - val_ia: 0.7377 - val_loss: 0.0638 - val_mae: 0.1554 - val_rmse: 0.2203 - val_smape: 0.4026

Epoch 36/128

958/958 - 10s - 11ms/step - ia: 0.8934 - loss: 0.0606 - mae: 0.1510 - rmse: 0.2308 - smape: 0.3879 - val_ia: 0.7414 - val_loss: 0.0636 - val_mae: 0.1542 - val_rmse: 0.2191 - val_smape: 0.3991

Epoch 37/128

958/958 - 5s - 5ms/step - ia: 0.8941 - loss: 0.0603 - mae: 0.1504 - rmse: 0.2297 - smape: 0.3875 - val_ia: 0.7435 - val_loss: 0.0634 - val_mae: 0.1537 - val_rmse: 0.2185 - val_smape: 0.3986

Epoch 38/128

958/958 - 6s - 6ms/step - ia: 0.8941 - loss: 0.0601 - mae: 0.1502 - rmse: 0.2296 - smape: 0.3869 - val_ia: 0.7426 - val_loss: 0.0630 - val_mae: 0.1533 - val_rmse: 0.2183 - val_smape: 0.3983

Epoch 39/128

958/958 - 10s - 11ms/step - ia: 0.8946 - loss: 0.0596 - mae: 0.1496 - rmse: 0.2287 - smape: 0.3858 - val_ia: 0.7406 - val_loss: 0.0634 - val_mae: 0.1544 - val_rmse: 0.2190 - val_smape: 0.3995

Epoch 40/128

958/958 - 11s - 11ms/step - ia: 0.8949 - loss: 0.0593 - mae: 0.1492 - rmse: 0.2280 - smape: 0.3842 - val_ia: 0.7420 - val_loss: 0.0629 - val_mae: 0.1534 - val_rmse: 0.2178 - val_smape: 0.3971

Epoch 41/128

958/958 - 6s - 7ms/step - ia: 0.8955 - loss: 0.0591 - mae: 0.1486 - rmse: 0.2274 - smape: 0.3836 - val_ia: 0.7395 - val_loss: 0.0629 - val_mae: 0.1536 - val_rmse: 0.2181 - val_smape: 0.3993

Epoch 42/128

958/958 - 10s - 11ms/step - ia: 0.8954 - loss: 0.0587 - mae: 0.1484 - rmse: 0.2267 - smape: 0.3829 - val_ia: 0.7426 - val_loss: 0.0632 - val_mae: 0.1531 - val_rmse: 0.2186 - val_smape: 0.3985

Epoch 43/128

958/958 - 6s - 6ms/step - ia: 0.8960 - loss: 0.0584 - mae: 0.1476 - rmse: 0.2264 - smape: 0.3818 - val_ia: 0.7430 - val_loss: 0.0628 - val_mae: 0.1531 - val_rmse: 0.2172 - val_smape: 0.3978

Epoch 44/128

958/958 - 9s - 9ms/step - ia: 0.8960 - loss: 0.0582 - mae: 0.1475 - rmse: 0.2256 - smape: 0.3813 - val_ia: 0.7459 - val_loss: 0.0627 - val_mae: 0.1521 - val_rmse: 0.2169 - val_smape: 0.3955

Epoch 45/128

958/958 - 5s - 5ms/step - ia: 0.8963 - loss: 0.0578 - mae: 0.1471 - rmse: 0.2249 - smape: 0.3801 - val_ia: 0.7443 - val_loss: 0.0630 - val_mae: 0.1528 - val_rmse: 0.2183 - val_smape: 0.3973

Epoch 46/128

958/958 - 5s - 5ms/step - ia: 0.8965 - loss: 0.0576 - mae: 0.1467 - rmse: 0.2246 - smape: 0.3797 - val_ia: 0.7430 - val_loss: 0.0632 - val_mae: 0.1538 - val_rmse: 0.2174 - val_smape: 0.3970

Epoch 47/128

958/958 - 3s - 3ms/step - ia: 0.8971 - loss: 0.0573 - mae: 0.1463 - rmse: 0.2238 - smape: 0.3786 - val_ia: 0.7428 - val_loss: 0.0626 - val_mae: 0.1526 - val_rmse: 0.2165 - val_smape: 0.3967

Epoch 48/128

958/958 - 3s - 3ms/step - ia: 0.8970 - loss: 0.0571 - mae: 0.1462 - rmse: 0.2236 - smape: 0.3787 - val_ia: 0.7421 - val_loss: 0.0632 - val_mae: 0.1533 - val_rmse: 0.2189 - val_smape: 0.3998

Epoch 49/128

958/958 - 4s - 4ms/step - ia: 0.8975 - loss: 0.0568 - mae: 0.1455 - rmse: 0.2237 - smape: 0.3768 - val_ia: 0.7443 - val_loss: 0.0629 - val_mae: 0.1534 - val_rmse: 0.2164 - val_smape: 0.3969

Epoch 50/128

958/958 - 4s - 4ms/step - ia: 0.8975 - loss: 0.0566 - mae: 0.1453 - rmse: 0.2229 - smape: 0.3763 - val_ia: 0.7460 - val_loss: 0.0620 - val_mae: 0.1513 - val_rmse: 0.2151 - val_smape: 0.3944

Epoch 51/128

958/958 - 6s - 7ms/step - ia: 0.8977 - loss: 0.0564 - mae: 0.1450 - rmse: 0.2218 - smape: 0.3765 - val_ia: 0.7464 - val_loss: 0.0622 - val_mae: 0.1515 - val_rmse: 0.2161 - val_smape: 0.3952

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.8977 - loss: 0.0561 - mae: 0.1447 - rmse: 0.2217 - smape: 0.3753 - val_ia: 0.7391 - val_loss: 0.0628 - val_mae: 0.1535 - val_rmse: 0.2183 - val_smape: 0.4003

Epoch 53/128

958/958 - 3s - 3ms/step - ia: 0.8982 - loss: 0.0560 - mae: 0.1444 - rmse: 0.2213 - smape: 0.3760 - val_ia: 0.7453 - val_loss: 0.0624 - val_mae: 0.1519 - val_rmse: 0.2165 - val_smape: 0.3955

Epoch 54/128

958/958 - 5s - 5ms/step - ia: 0.8986 - loss: 0.0557 - mae: 0.1439 - rmse: 0.2204 - smape: 0.3745 - val_ia: 0.7447 - val_loss: 0.0620 - val_mae: 0.1515 - val_rmse: 0.2158 - val_smape: 0.3959

Epoch 55/128

958/958 - 4s - 4ms/step - ia: 0.8989 - loss: 0.0555 - mae: 0.1438 - rmse: 0.2200 - smape: 0.3739 - val_ia: 0.7465 - val_loss: 0.0620 - val_mae: 0.1514 - val_rmse: 0.2155 - val_smape: 0.3948

Epoch 56/128

958/958 - 5s - 5ms/step - ia: 0.8991 - loss: 0.0552 - mae: 0.1436 - rmse: 0.2204 - smape: 0.3734 - val_ia: 0.7460 - val_loss: 0.0619 - val_mae: 0.1511 - val_rmse: 0.2153 - val_smape: 0.3934

Epoch 57/128

958/958 - 6s - 6ms/step - ia: 0.8987 - loss: 0.0551 - mae: 0.1435 - rmse: 0.2193 - smape: 0.3735 - val_ia: 0.7477 - val_loss: 0.0616 - val_mae: 0.1504 - val_rmse: 0.2143 - val_smape: 0.3921

Epoch 58/128

958/958 - 4s - 4ms/step - ia: 0.8992 - loss: 0.0549 - mae: 0.1429 - rmse: 0.2193 - smape: 0.3719 - val_ia: 0.7479 - val_loss: 0.0618 - val_mae: 0.1508 - val_rmse: 0.2145 - val_smape: 0.3920

Epoch 59/128

958/958 - 7s - 7ms/step - ia: 0.9000 - loss: 0.0547 - mae: 0.1426 - rmse: 0.2186 - smape: 0.3722 - val_ia: 0.7468 - val_loss: 0.0619 - val_mae: 0.1509 - val_rmse: 0.2148 - val_smape: 0.3927

Epoch 60/128

958/958 - 5s - 5ms/step - ia: 0.8998 - loss: 0.0545 - mae: 0.1423 - rmse: 0.2186 - smape: 0.3716 - val_ia: 0.7446 - val_loss: 0.0622 - val_mae: 0.1520 - val_rmse: 0.2168 - val_smape: 0.3972

Epoch 61/128

958/958 - 3s - 3ms/step - ia: 0.8998 - loss: 0.0544 - mae: 0.1422 - rmse: 0.2183 - smape: 0.3706 - val_ia: 0.7467 - val_loss: 0.0620 - val_mae: 0.1510 - val_rmse: 0.2156 - val_smape: 0.3939

Epoch 62/128

958/958 - 5s - 5ms/step - ia: 0.9004 - loss: 0.0541 - mae: 0.1421 - rmse: 0.2176 - smape: 0.3714 - val_ia: 0.7476 - val_loss: 0.0626 - val_mae: 0.1524 - val_rmse: 0.2155 - val_smape: 0.3935

Epoch 63/128

958/958 - 4s - 4ms/step - ia: 0.9002 - loss: 0.0539 - mae: 0.1417 - rmse: 0.2170 - smape: 0.3695 - val_ia: 0.7476 - val_loss: 0.0619 - val_mae: 0.1510 - val_rmse: 0.2143 - val_smape: 0.3918

Epoch 64/128

958/958 - 5s - 5ms/step - ia: 0.9004 - loss: 0.0537 - mae: 0.1414 - rmse: 0.2173 - smape: 0.3698 - val_ia: 0.7440 - val_loss: 0.0617 - val_mae: 0.1511 - val_rmse: 0.2151 - val_smape: 0.3937

Epoch 65/128

958/958 - 5s - 5ms/step - ia: 0.9006 - loss: 0.0535 - mae: 0.1411 - rmse: 0.2161 - smape: 0.3687 - val_ia: 0.7455 - val_loss: 0.0619 - val_mae: 0.1509 - val_rmse: 0.2154 - val_smape: 0.3940

Epoch 66/128

958/958 - 5s - 6ms/step - ia: 0.9010 - loss: 0.0534 - mae: 0.1409 - rmse: 0.2162 - smape: 0.3691 - val_ia: 0.7502 - val_loss: 0.0615 - val_mae: 0.1500 - val_rmse: 0.2138 - val_smape: 0.3910

Epoch 67/128

958/958 - 5s - 5ms/step - ia: 0.9010 - loss: 0.0531 - mae: 0.1406 - rmse: 0.2159 - smape: 0.3679 - val_ia: 0.7479 - val_loss: 0.0629 - val_mae: 0.1523 - val_rmse: 0.2155 - val_smape: 0.3935

Epoch 68/128

958/958 - 5s - 5ms/step - ia: 0.9012 - loss: 0.0531 - mae: 0.1406 - rmse: 0.2156 - smape: 0.3682 - val_ia: 0.7517 - val_loss: 0.0614 - val_mae: 0.1495 - val_rmse: 0.2134 - val_smape: 0.3889

Epoch 69/128

958/958 - 5s - 5ms/step - ia: 0.9011 - loss: 0.0529 - mae: 0.1404 - rmse: 0.2154 - smape: 0.3678 - val_ia: 0.7472 - val_loss: 0.0614 - val_mae: 0.1503 - val_rmse: 0.2139 - val_smape: 0.3915

Epoch 70/128

958/958 - 6s - 6ms/step - ia: 0.9018 - loss: 0.0526 - mae: 0.1400 - rmse: 0.2145 - smape: 0.3677 - val_ia: 0.7496 - val_loss: 0.0613 - val_mae: 0.1498 - val_rmse: 0.2135 - val_smape: 0.3905

Epoch 71/128

958/958 - 11s - 11ms/step - ia: 0.9013 - loss: 0.0525 - mae: 0.1397 - rmse: 0.2145 - smape: 0.3661 - val_ia: 0.7501 - val_loss: 0.0617 - val_mae: 0.1503 - val_rmse: 0.2140 - val_smape: 0.3904

Epoch 72/128

958/958 - 9s - 9ms/step - ia: 0.9019 - loss: 0.0523 - mae: 0.1396 - rmse: 0.2139 - smape: 0.3660 - val_ia: 0.7494 - val_loss: 0.0617 - val_mae: 0.1499 - val_rmse: 0.2143 - val_smape: 0.3915

Epoch 73/128

958/958 - 5s - 5ms/step - ia: 0.9020 - loss: 0.0522 - mae: 0.1394 - rmse: 0.2137 - smape: 0.3658 - val_ia: 0.7459 - val_loss: 0.0615 - val_mae: 0.1506 - val_rmse: 0.2136 - val_smape: 0.3916

Epoch 74/128

958/958 - 5s - 5ms/step - ia: 0.9019 - loss: 0.0520 - mae: 0.1391 - rmse: 0.2134 - smape: 0.3657 - val_ia: 0.7483 - val_loss: 0.0626 - val_mae: 0.1523 - val_rmse: 0.2146 - val_smape: 0.3926

Epoch 75/128

958/958 - 5s - 5ms/step - ia: 0.9021 - loss: 0.0519 - mae: 0.1390 - rmse: 0.2137 - smape: 0.3653 - val_ia: 0.7493 - val_loss: 0.0613 - val_mae: 0.1498 - val_rmse: 0.2130 - val_smape: 0.3897

Epoch 76/128

958/958 - 5s - 5ms/step - ia: 0.9023 - loss: 0.0516 - mae: 0.1387 - rmse: 0.2125 - smape: 0.3657 - val_ia: 0.7487 - val_loss: 0.0620 - val_mae: 0.1501 - val_rmse: 0.2151 - val_smape: 0.3910

Epoch 77/128

958/958 - 7s - 7ms/step - ia: 0.9021 - loss: 0.0515 - mae: 0.1389 - rmse: 0.2125 - smape: 0.3647 - val_ia: 0.7437 - val_loss: 0.0629 - val_mae: 0.1530 - val_rmse: 0.2174 - val_smape: 0.3983

Epoch 78/128

958/958 - 6s - 7ms/step - ia: 0.9025 - loss: 0.0514 - mae: 0.1384 - rmse: 0.2123 - smape: 0.3644 - val_ia: 0.7484 - val_loss: 0.0612 - val_mae: 0.1498 - val_rmse: 0.2132 - val_smape: 0.3897

Epoch 79/128

958/958 - 5s - 5ms/step - ia: 0.9025 - loss: 0.0512 - mae: 0.1382 - rmse: 0.2114 - smape: 0.3638 - val_ia: 0.7455 - val_loss: 0.0618 - val_mae: 0.1509 - val_rmse: 0.2150 - val_smape: 0.3932

Epoch 80/128

958/958 - 5s - 6ms/step - ia: 0.9028 - loss: 0.0510 - mae: 0.1381 - rmse: 0.2109 - smape: 0.3632 - val_ia: 0.7515 - val_loss: 0.0611 - val_mae: 0.1491 - val_rmse: 0.2126 - val_smape: 0.3883

Epoch 81/128

958/958 - 6s - 6ms/step - ia: 0.9033 - loss: 0.0509 - mae: 0.1379 - rmse: 0.2114 - smape: 0.3631 - val_ia: 0.7493 - val_loss: 0.0618 - val_mae: 0.1498 - val_rmse: 0.2145 - val_smape: 0.3905

Epoch 82/128

958/958 - 9s - 10ms/step - ia: 0.9027 - loss: 0.0508 - mae: 0.1378 - rmse: 0.2108 - smape: 0.3627 - val_ia: 0.7476 - val_loss: 0.0613 - val_mae: 0.1500 - val_rmse: 0.2132 - val_smape: 0.3908

Epoch 83/128

958/958 - 6s - 6ms/step - ia: 0.9033 - loss: 0.0506 - mae: 0.1374 - rmse: 0.2106 - smape: 0.3619 - val_ia: 0.7442 - val_loss: 0.0617 - val_mae: 0.1513 - val_rmse: 0.2150 - val_smape: 0.3947

Epoch 84/128

958/958 - 3s - 3ms/step - ia: 0.9035 - loss: 0.0505 - mae: 0.1374 - rmse: 0.2106 - smape: 0.3624 - val_ia: 0.7510 - val_loss: 0.0619 - val_mae: 0.1507 - val_rmse: 0.2142 - val_smape: 0.3892

Epoch 85/128

958/958 - 8s - 8ms/step - ia: 0.9032 - loss: 0.0503 - mae: 0.1372 - rmse: 0.2095 - smape: 0.3621 - val_ia: 0.7515 - val_loss: 0.0615 - val_mae: 0.1492 - val_rmse: 0.2132 - val_smape: 0.3886

Epoch 86/128

958/958 - 7s - 7ms/step - ia: 0.9041 - loss: 0.0502 - mae: 0.1369 - rmse: 0.2100 - smape: 0.3616 - val_ia: 0.7518 - val_loss: 0.0611 - val_mae: 0.1491 - val_rmse: 0.2123 - val_smape: 0.3885

Epoch 87/128

958/958 - 8s - 9ms/step - ia: 0.9041 - loss: 0.0500 - mae: 0.1368 - rmse: 0.2093 - smape: 0.3610 - val_ia: 0.7483 - val_loss: 0.0614 - val_mae: 0.1503 - val_rmse: 0.2135 - val_smape: 0.3919

Epoch 88/128

958/958 - 6s - 6ms/step - ia: 0.9034 - loss: 0.0498 - mae: 0.1367 - rmse: 0.2089 - smape: 0.3605 - val_ia: 0.7488 - val_loss: 0.0617 - val_mae: 0.1503 - val_rmse: 0.2136 - val_smape: 0.3900

Epoch 89/128

958/958 - 12s - 13ms/step - ia: 0.9038 - loss: 0.0498 - mae: 0.1365 - rmse: 0.2097 - smape: 0.3606 - val_ia: 0.7511 - val_loss: 0.0614 - val_mae: 0.1493 - val_rmse: 0.2130 - val_smape: 0.3890

Epoch 90/128

958/958 - 6s - 6ms/step - ia: 0.9041 - loss: 0.0496 - mae: 0.1364 - rmse: 0.2095 - smape: 0.3605 - val_ia: 0.7485 - val_loss: 0.0616 - val_mae: 0.1501 - val_rmse: 0.2141 - val_smape: 0.3917

Epoch 91/128

958/958 - 3s - 3ms/step - ia: 0.9039 - loss: 0.0495 - mae: 0.1363 - rmse: 0.2085 - smape: 0.3603 - val_ia: 0.7513 - val_loss: 0.0613 - val_mae: 0.1494 - val_rmse: 0.2130 - val_smape: 0.3891

Epoch 92/128

958/958 - 5s - 5ms/step - ia: 0.9043 - loss: 0.0493 - mae: 0.1361 - rmse: 0.2081 - smape: 0.3600 - val_ia: 0.7439 - val_loss: 0.0619 - val_mae: 0.1515 - val_rmse: 0.2153 - val_smape: 0.3945

Epoch 93/128

958/958 - 4s - 4ms/step - ia: 0.9046 - loss: 0.0491 - mae: 0.1359 - rmse: 0.2080 - smape: 0.3599 - val_ia: 0.7488 - val_loss: 0.0627 - val_mae: 0.1516 - val_rmse: 0.2154 - val_smape: 0.3915

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.9046 - loss: 0.0490 - mae: 0.1355 - rmse: 0.2075 - smape: 0.3582 - val_ia: 0.7492 - val_loss: 0.0619 - val_mae: 0.1505 - val_rmse: 0.2140 - val_smape: 0.3904

Epoch 95/128

958/958 - 7s - 7ms/step - ia: 0.9048 - loss: 0.0489 - mae: 0.1353 - rmse: 0.2075 - smape: 0.3580 - val_ia: 0.7480 - val_loss: 0.0623 - val_mae: 0.1516 - val_rmse: 0.2149 - val_smape: 0.3921

Epoch 96/128

958/958 - 3s - 3ms/step - ia: 0.9049 - loss: 0.0488 - mae: 0.1353 - rmse: 0.2076 - smape: 0.3586 - val_ia: 0.7507 - val_loss: 0.0616 - val_mae: 0.1496 - val_rmse: 0.2136 - val_smape: 0.3889

Epoch 97/128

958/958 - 9s - 9ms/step - ia: 0.9049 - loss: 0.0487 - mae: 0.1351 - rmse: 0.2068 - smape: 0.3575 - val_ia: 0.7523 - val_loss: 0.0613 - val_mae: 0.1494 - val_rmse: 0.2126 - val_smape: 0.3889

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 27s - 28ms/step - ia: 0.2675 - loss: 1.1186 - mae: 0.8129 - rmse: 1.0361 - smape: 1.4908 - val_ia: 0.2873 - val_loss: 0.7558 - val_mae: 0.6361 - val_rmse: 0.7171 - val_smape: 1.4448

Epoch 2/128

958/958 - 10s - 10ms/step - ia: 0.4526 - loss: 0.7425 - mae: 0.6236 - rmse: 0.8405 - smape: 1.1987 - val_ia: 0.3650 - val_loss: 0.4969 - val_mae: 0.4903 - val_rmse: 0.5738 - val_smape: 1.0288

Epoch 3/128

958/958 - 6s - 6ms/step - ia: 0.5749 - loss: 0.5622 - mae: 0.5366 - rmse: 0.7305 - smape: 1.0119 - val_ia: 0.4494 - val_loss: 0.3644 - val_mae: 0.3936 - val_rmse: 0.4801 - val_smape: 0.8097

Epoch 4/128

958/958 - 5s - 5ms/step - ia: 0.6331 - loss: 0.4790 - mae: 0.4922 - rmse: 0.6729 - smape: 0.9130 - val_ia: 0.5096 - val_loss: 0.2994 - val_mae: 0.3425 - val_rmse: 0.4287 - val_smape: 0.7051

Epoch 5/128

958/958 - 7s - 7ms/step - ia: 0.6635 - loss: 0.4198 - mae: 0.4589 - rmse: 0.6297 - smape: 0.8574 - val_ia: 0.5509 - val_loss: 0.2549 - val_mae: 0.3085 - val_rmse: 0.3930 - val_smape: 0.6423

Epoch 6/128

958/958 - 5s - 5ms/step - ia: 0.6887 - loss: 0.3697 - mae: 0.4282 - rmse: 0.5897 - smape: 0.8187 - val_ia: 0.5826 - val_loss: 0.2225 - val_mae: 0.2835 - val_rmse: 0.3663 - val_smape: 0.6030

Epoch 7/128

958/958 - 4s - 5ms/step - ia: 0.7078 - loss: 0.3348 - mae: 0.4045 - rmse: 0.5598 - smape: 0.7823 - val_ia: 0.6096 - val_loss: 0.1964 - val_mae: 0.2619 - val_rmse: 0.3428 - val_smape: 0.5642

Epoch 8/128

958/958 - 6s - 6ms/step - ia: 0.7252 - loss: 0.3048 - mae: 0.3825 - rmse: 0.5330 - smape: 0.7521 - val_ia: 0.6310 - val_loss: 0.1760 - val_mae: 0.2447 - val_rmse: 0.3243 - val_smape: 0.5328

Epoch 9/128

958/958 - 5s - 6ms/step - ia: 0.7408 - loss: 0.2732 - mae: 0.3618 - rmse: 0.5040 - smape: 0.7206 - val_ia: 0.6381 - val_loss: 0.1603 - val_mae: 0.2345 - val_rmse: 0.3127 - val_smape: 0.5188

Epoch 10/128

958/958 - 3s - 3ms/step - ia: 0.7509 - loss: 0.2565 - mae: 0.3480 - rmse: 0.4874 - smape: 0.7026 - val_ia: 0.6469 - val_loss: 0.1484 - val_mae: 0.2251 - val_rmse: 0.3023 - val_smape: 0.5021

Epoch 11/128

958/958 - 4s - 5ms/step - ia: 0.7603 - loss: 0.2400 - mae: 0.3351 - rmse: 0.4706 - smape: 0.6860 - val_ia: 0.6533 - val_loss: 0.1394 - val_mae: 0.2179 - val_rmse: 0.2926 - val_smape: 0.4894

Epoch 12/128

958/958 - 6s - 6ms/step - ia: 0.7681 - loss: 0.2268 - mae: 0.3228 - rmse: 0.4567 - smape: 0.6656 - val_ia: 0.6561 - val_loss: 0.1311 - val_mae: 0.2125 - val_rmse: 0.2863 - val_smape: 0.4816

Epoch 13/128

958/958 - 5s - 5ms/step - ia: 0.7738 - loss: 0.2134 - mae: 0.3144 - rmse: 0.4427 - smape: 0.6537 - val_ia: 0.6556 - val_loss: 0.1249 - val_mae: 0.2096 - val_rmse: 0.2815 - val_smape: 0.4796

Epoch 14/128

958/958 - 4s - 4ms/step - ia: 0.7819 - loss: 0.2020 - mae: 0.3028 - rmse: 0.4309 - smape: 0.6403 - val_ia: 0.6535 - val_loss: 0.1194 - val_mae: 0.2075 - val_rmse: 0.2785 - val_smape: 0.4771

Epoch 15/128

958/958 - 7s - 7ms/step - ia: 0.7852 - loss: 0.1926 - mae: 0.2976 - rmse: 0.4213 - smape: 0.6325 - val_ia: 0.6525 - val_loss: 0.1153 - val_mae: 0.2061 - val_rmse: 0.2760 - val_smape: 0.4768

Epoch 16/128

958/958 - 10s - 10ms/step - ia: 0.7899 - loss: 0.1864 - mae: 0.2911 - rmse: 0.4127 - smape: 0.6210 - val_ia: 0.6558 - val_loss: 0.1113 - val_mae: 0.2030 - val_rmse: 0.2722 - val_smape: 0.4739

Epoch 17/128

958/958 - 5s - 5ms/step - ia: 0.7945 - loss: 0.1810 - mae: 0.2858 - rmse: 0.4071 - smape: 0.6151 - val_ia: 0.6545 - val_loss: 0.1091 - val_mae: 0.2026 - val_rmse: 0.2705 - val_smape: 0.4758

Epoch 18/128

958/958 - 6s - 6ms/step - ia: 0.7931 - loss: 0.1784 - mae: 0.2853 - rmse: 0.4048 - smape: 0.6144 - val_ia: 0.6530 - val_loss: 0.1064 - val_mae: 0.2019 - val_rmse: 0.2691 - val_smape: 0.4746

Epoch 19/128

958/958 - 6s - 6ms/step - ia: 0.7992 - loss: 0.1708 - mae: 0.2782 - rmse: 0.3944 - smape: 0.6051 - val_ia: 0.6607 - val_loss: 0.1031 - val_mae: 0.1975 - val_rmse: 0.2649 - val_smape: 0.4697

Epoch 20/128

958/958 - 5s - 5ms/step - ia: 0.8008 - loss: 0.1658 - mae: 0.2752 - rmse: 0.3899 - smape: 0.6023 - val_ia: 0.6606 - val_loss: 0.1010 - val_mae: 0.1966 - val_rmse: 0.2630 - val_smape: 0.4686

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.8035 - loss: 0.1632 - mae: 0.2714 - rmse: 0.3852 - smape: 0.5954 - val_ia: 0.6609 - val_loss: 0.0999 - val_mae: 0.1962 - val_rmse: 0.2626 - val_smape: 0.4685

Epoch 22/128

958/958 - 3s - 4ms/step - ia: 0.8049 - loss: 0.1613 - mae: 0.2695 - rmse: 0.3833 - smape: 0.5937 - val_ia: 0.6729 - val_loss: 0.0965 - val_mae: 0.1902 - val_rmse: 0.2566 - val_smape: 0.4610

Epoch 23/128

958/958 - 5s - 5ms/step - ia: 0.8077 - loss: 0.1577 - mae: 0.2649 - rmse: 0.3789 - smape: 0.5845 - val_ia: 0.6731 - val_loss: 0.0957 - val_mae: 0.1899 - val_rmse: 0.2562 - val_smape: 0.4611

Epoch 24/128

958/958 - 3s - 4ms/step - ia: 0.8088 - loss: 0.1554 - mae: 0.2642 - rmse: 0.3769 - smape: 0.5849 - val_ia: 0.6755 - val_loss: 0.0928 - val_mae: 0.1874 - val_rmse: 0.2530 - val_smape: 0.4559

Epoch 25/128

958/958 - 5s - 5ms/step - ia: 0.8126 - loss: 0.1517 - mae: 0.2599 - rmse: 0.3714 - smape: 0.5775 - val_ia: 0.6768 - val_loss: 0.0918 - val_mae: 0.1866 - val_rmse: 0.2517 - val_smape: 0.4550

Epoch 26/128

958/958 - 2s - 3ms/step - ia: 0.8141 - loss: 0.1498 - mae: 0.2575 - rmse: 0.3690 - smape: 0.5744 - val_ia: 0.6858 - val_loss: 0.0899 - val_mae: 0.1825 - val_rmse: 0.2485 - val_smape: 0.4488

Epoch 27/128

958/958 - 3s - 3ms/step - ia: 0.8156 - loss: 0.1481 - mae: 0.2558 - rmse: 0.3672 - smape: 0.5699 - val_ia: 0.6829 - val_loss: 0.0887 - val_mae: 0.1827 - val_rmse: 0.2478 - val_smape: 0.4483

Epoch 28/128

958/958 - 4s - 5ms/step - ia: 0.8181 - loss: 0.1437 - mae: 0.2525 - rmse: 0.3615 - smape: 0.5668 - val_ia: 0.6910 - val_loss: 0.0871 - val_mae: 0.1793 - val_rmse: 0.2446 - val_smape: 0.4445

Epoch 29/128

958/958 - 4s - 4ms/step - ia: 0.8203 - loss: 0.1422 - mae: 0.2495 - rmse: 0.3589 - smape: 0.5601 - val_ia: 0.6904 - val_loss: 0.0861 - val_mae: 0.1790 - val_rmse: 0.2440 - val_smape: 0.4432

Epoch 30/128

958/958 - 4s - 4ms/step - ia: 0.8199 - loss: 0.1401 - mae: 0.2491 - rmse: 0.3565 - smape: 0.5600 - val_ia: 0.6973 - val_loss: 0.0847 - val_mae: 0.1760 - val_rmse: 0.2415 - val_smape: 0.4387

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.8214 - loss: 0.1398 - mae: 0.2471 - rmse: 0.3565 - smape: 0.5557 - val_ia: 0.7015 - val_loss: 0.0829 - val_mae: 0.1735 - val_rmse: 0.2393 - val_smape: 0.4343

Epoch 32/128

958/958 - 6s - 6ms/step - ia: 0.8233 - loss: 0.1377 - mae: 0.2450 - rmse: 0.3529 - smape: 0.5502 - val_ia: 0.7024 - val_loss: 0.0824 - val_mae: 0.1733 - val_rmse: 0.2381 - val_smape: 0.4345

Epoch 33/128

958/958 - 5s - 5ms/step - ia: 0.8263 - loss: 0.1344 - mae: 0.2417 - rmse: 0.3490 - smape: 0.5461 - val_ia: 0.7035 - val_loss: 0.0817 - val_mae: 0.1724 - val_rmse: 0.2375 - val_smape: 0.4329

Epoch 34/128

958/958 - 5s - 5ms/step - ia: 0.8269 - loss: 0.1341 - mae: 0.2410 - rmse: 0.3475 - smape: 0.5472 - val_ia: 0.7072 - val_loss: 0.0805 - val_mae: 0.1707 - val_rmse: 0.2354 - val_smape: 0.4303

Epoch 35/128

958/958 - 5s - 5ms/step - ia: 0.8276 - loss: 0.1327 - mae: 0.2396 - rmse: 0.3456 - smape: 0.5438 - val_ia: 0.7087 - val_loss: 0.0797 - val_mae: 0.1695 - val_rmse: 0.2348 - val_smape: 0.4268

Epoch 36/128

958/958 - 3s - 4ms/step - ia: 0.8284 - loss: 0.1300 - mae: 0.2382 - rmse: 0.3435 - smape: 0.5398 - val_ia: 0.7134 - val_loss: 0.0785 - val_mae: 0.1673 - val_rmse: 0.2325 - val_smape: 0.4238

Epoch 37/128

958/958 - 7s - 7ms/step - ia: 0.8284 - loss: 0.1312 - mae: 0.2381 - rmse: 0.3445 - smape: 0.5380 - val_ia: 0.7144 - val_loss: 0.0781 - val_mae: 0.1669 - val_rmse: 0.2319 - val_smape: 0.4229

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.8316 - loss: 0.1273 - mae: 0.2348 - rmse: 0.3392 - smape: 0.5332 - val_ia: 0.7118 - val_loss: 0.0781 - val_mae: 0.1679 - val_rmse: 0.2324 - val_smape: 0.4240

Epoch 39/128

958/958 - 5s - 6ms/step - ia: 0.8335 - loss: 0.1237 - mae: 0.2316 - rmse: 0.3348 - smape: 0.5287 - val_ia: 0.7131 - val_loss: 0.0770 - val_mae: 0.1668 - val_rmse: 0.2310 - val_smape: 0.4214

Epoch 40/128

958/958 - 5s - 5ms/step - ia: 0.8326 - loss: 0.1252 - mae: 0.2324 - rmse: 0.3362 - smape: 0.5256 - val_ia: 0.7154 - val_loss: 0.0766 - val_mae: 0.1659 - val_rmse: 0.2301 - val_smape: 0.4196

Epoch 41/128

958/958 - 5s - 5ms/step - ia: 0.8345 - loss: 0.1249 - mae: 0.2307 - rmse: 0.3351 - smape: 0.5252 - val_ia: 0.7204 - val_loss: 0.0753 - val_mae: 0.1633 - val_rmse: 0.2280 - val_smape: 0.4146

Epoch 42/128

958/958 - 5s - 5ms/step - ia: 0.8357 - loss: 0.1227 - mae: 0.2288 - rmse: 0.3323 - smape: 0.5246 - val_ia: 0.7233 - val_loss: 0.0747 - val_mae: 0.1621 - val_rmse: 0.2269 - val_smape: 0.4126

Epoch 43/128

958/958 - 4s - 4ms/step - ia: 0.8364 - loss: 0.1213 - mae: 0.2274 - rmse: 0.3303 - smape: 0.5192 - val_ia: 0.7269 - val_loss: 0.0736 - val_mae: 0.1603 - val_rmse: 0.2249 - val_smape: 0.4099

Epoch 44/128

958/958 - 6s - 6ms/step - ia: 0.8369 - loss: 0.1238 - mae: 0.2273 - rmse: 0.3326 - smape: 0.5156 - val_ia: 0.7196 - val_loss: 0.0743 - val_mae: 0.1632 - val_rmse: 0.2268 - val_smape: 0.4131

Epoch 45/128

958/958 - 5s - 5ms/step - ia: 0.8369 - loss: 0.1202 - mae: 0.2270 - rmse: 0.3292 - smape: 0.5178 - val_ia: 0.7285 - val_loss: 0.0727 - val_mae: 0.1594 - val_rmse: 0.2239 - val_smape: 0.4073

Epoch 46/128

958/958 - 4s - 5ms/step - ia: 0.8375 - loss: 0.1202 - mae: 0.2264 - rmse: 0.3294 - smape: 0.5170 - val_ia: 0.7295 - val_loss: 0.0734 - val_mae: 0.1601 - val_rmse: 0.2243 - val_smape: 0.4078

Epoch 47/128

958/958 - 5s - 5ms/step - ia: 0.8393 - loss: 0.1178 - mae: 0.2244 - rmse: 0.3259 - smape: 0.5113 - val_ia: 0.7284 - val_loss: 0.0726 - val_mae: 0.1596 - val_rmse: 0.2237 - val_smape: 0.4068

Epoch 48/128

958/958 - 4s - 5ms/step - ia: 0.8407 - loss: 0.1180 - mae: 0.2230 - rmse: 0.3258 - smape: 0.5105 - val_ia: 0.7293 - val_loss: 0.0720 - val_mae: 0.1588 - val_rmse: 0.2229 - val_smape: 0.4047

Epoch 49/128

958/958 - 8s - 8ms/step - ia: 0.8407 - loss: 0.1174 - mae: 0.2225 - rmse: 0.3236 - smape: 0.5100 - val_ia: 0.7258 - val_loss: 0.0716 - val_mae: 0.1596 - val_rmse: 0.2231 - val_smape: 0.4062

Epoch 50/128

958/958 - 3s - 3ms/step - ia: 0.8409 - loss: 0.1160 - mae: 0.2218 - rmse: 0.3236 - smape: 0.5071 - val_ia: 0.7291 - val_loss: 0.0712 - val_mae: 0.1583 - val_rmse: 0.2225 - val_smape: 0.4041

Epoch 51/128

958/958 - 7s - 7ms/step - ia: 0.8423 - loss: 0.1160 - mae: 0.2208 - rmse: 0.3218 - smape: 0.5054 - val_ia: 0.7297 - val_loss: 0.0717 - val_mae: 0.1588 - val_rmse: 0.2224 - val_smape: 0.4030

Epoch 52/128

958/958 - 3s - 3ms/step - ia: 0.8425 - loss: 0.1157 - mae: 0.2201 - rmse: 0.3221 - smape: 0.5013 - val_ia: 0.7362 - val_loss: 0.0705 - val_mae: 0.1559 - val_rmse: 0.2201 - val_smape: 0.3988

Epoch 53/128

958/958 - 5s - 5ms/step - ia: 0.8436 - loss: 0.1139 - mae: 0.2186 - rmse: 0.3204 - smape: 0.5007 - val_ia: 0.7323 - val_loss: 0.0699 - val_mae: 0.1564 - val_rmse: 0.2202 - val_smape: 0.3994

Epoch 54/128

958/958 - 5s - 5ms/step - ia: 0.8449 - loss: 0.1116 - mae: 0.2171 - rmse: 0.3162 - smape: 0.5020 - val_ia: 0.7312 - val_loss: 0.0701 - val_mae: 0.1570 - val_rmse: 0.2207 - val_smape: 0.3999

Epoch 55/128

958/958 - 6s - 6ms/step - ia: 0.8458 - loss: 0.1115 - mae: 0.2160 - rmse: 0.3167 - smape: 0.4942 - val_ia: 0.7347 - val_loss: 0.0704 - val_mae: 0.1568 - val_rmse: 0.2203 - val_smape: 0.3980

Epoch 56/128

958/958 - 5s - 5ms/step - ia: 0.8445 - loss: 0.1142 - mae: 0.2182 - rmse: 0.3190 - smape: 0.4980 - val_ia: 0.7355 - val_loss: 0.0690 - val_mae: 0.1551 - val_rmse: 0.2188 - val_smape: 0.3960

Epoch 57/128

958/958 - 5s - 6ms/step - ia: 0.8459 - loss: 0.1113 - mae: 0.2162 - rmse: 0.3162 - smape: 0.4939 - val_ia: 0.7392 - val_loss: 0.0686 - val_mae: 0.1539 - val_rmse: 0.2177 - val_smape: 0.3937

Epoch 58/128

958/958 - 3s - 4ms/step - ia: 0.8465 - loss: 0.1106 - mae: 0.2146 - rmse: 0.3148 - smape: 0.4905 - val_ia: 0.7399 - val_loss: 0.0683 - val_mae: 0.1534 - val_rmse: 0.2173 - val_smape: 0.3926

Epoch 59/128

958/958 - 5s - 5ms/step - ia: 0.8454 - loss: 0.1129 - mae: 0.2163 - rmse: 0.3171 - smape: 0.4949 - val_ia: 0.7374 - val_loss: 0.0684 - val_mae: 0.1544 - val_rmse: 0.2178 - val_smape: 0.3935

Epoch 60/128

958/958 - 4s - 4ms/step - ia: 0.8463 - loss: 0.1113 - mae: 0.2152 - rmse: 0.3158 - smape: 0.4946 - val_ia: 0.7392 - val_loss: 0.0677 - val_mae: 0.1532 - val_rmse: 0.2166 - val_smape: 0.3915

Epoch 61/128

958/958 - 3s - 3ms/step - ia: 0.8471 - loss: 0.1096 - mae: 0.2144 - rmse: 0.3135 - smape: 0.4898 - val_ia: 0.7413 - val_loss: 0.0674 - val_mae: 0.1522 - val_rmse: 0.2161 - val_smape: 0.3895

Epoch 62/128

958/958 - 7s - 7ms/step - ia: 0.8470 - loss: 0.1097 - mae: 0.2149 - rmse: 0.3140 - smape: 0.4925 - val_ia: 0.7373 - val_loss: 0.0672 - val_mae: 0.1534 - val_rmse: 0.2165 - val_smape: 0.3916

Epoch 63/128

958/958 - 6s - 6ms/step - ia: 0.8477 - loss: 0.1084 - mae: 0.2135 - rmse: 0.3122 - smape: 0.4883 - val_ia: 0.7413 - val_loss: 0.0669 - val_mae: 0.1518 - val_rmse: 0.2156 - val_smape: 0.3885

Epoch 64/128

958/958 - 4s - 4ms/step - ia: 0.8470 - loss: 0.1095 - mae: 0.2140 - rmse: 0.3133 - smape: 0.4907 - val_ia: 0.7459 - val_loss: 0.0664 - val_mae: 0.1502 - val_rmse: 0.2141 - val_smape: 0.3861

Epoch 65/128

958/958 - 5s - 5ms/step - ia: 0.8492 - loss: 0.1082 - mae: 0.2117 - rmse: 0.3098 - smape: 0.4836 - val_ia: 0.7396 - val_loss: 0.0665 - val_mae: 0.1520 - val_rmse: 0.2153 - val_smape: 0.3886

Epoch 66/128

958/958 - 6s - 6ms/step - ia: 0.8491 - loss: 0.1077 - mae: 0.2109 - rmse: 0.3110 - smape: 0.4827 - val_ia: 0.7429 - val_loss: 0.0662 - val_mae: 0.1510 - val_rmse: 0.2144 - val_smape: 0.3868

Epoch 67/128

958/958 - 5s - 6ms/step - ia: 0.8484 - loss: 0.1091 - mae: 0.2123 - rmse: 0.3120 - smape: 0.4856 - val_ia: 0.7412 - val_loss: 0.0660 - val_mae: 0.1511 - val_rmse: 0.2144 - val_smape: 0.3870

Epoch 68/128

958/958 - 3s - 4ms/step - ia: 0.8501 - loss: 0.1078 - mae: 0.2106 - rmse: 0.3108 - smape: 0.4812 - val_ia: 0.7406 - val_loss: 0.0668 - val_mae: 0.1524 - val_rmse: 0.2156 - val_smape: 0.3877

Epoch 69/128

958/958 - 5s - 5ms/step - ia: 0.8497 - loss: 0.1069 - mae: 0.2110 - rmse: 0.3092 - smape: 0.4839 - val_ia: 0.7466 - val_loss: 0.0657 - val_mae: 0.1496 - val_rmse: 0.2133 - val_smape: 0.3832

Epoch 70/128

958/958 - 4s - 4ms/step - ia: 0.8498 - loss: 0.1082 - mae: 0.2108 - rmse: 0.3102 - smape: 0.4837 - val_ia: 0.7386 - val_loss: 0.0659 - val_mae: 0.1521 - val_rmse: 0.2150 - val_smape: 0.3876

Epoch 71/128

958/958 - 6s - 6ms/step - ia: 0.8513 - loss: 0.1056 - mae: 0.2093 - rmse: 0.3076 - smape: 0.4792 - val_ia: 0.7423 - val_loss: 0.0651 - val_mae: 0.1504 - val_rmse: 0.2133 - val_smape: 0.3849

Epoch 72/128

958/958 - 5s - 5ms/step - ia: 0.8499 - loss: 0.1063 - mae: 0.2100 - rmse: 0.3081 - smape: 0.4832 - val_ia: 0.7418 - val_loss: 0.0651 - val_mae: 0.1504 - val_rmse: 0.2133 - val_smape: 0.3844

Epoch 73/128

958/958 - 3s - 4ms/step - ia: 0.8504 - loss: 0.1072 - mae: 0.2105 - rmse: 0.3091 - smape: 0.4810 - val_ia: 0.7491 - val_loss: 0.0650 - val_mae: 0.1486 - val_rmse: 0.2120 - val_smape: 0.3809

Epoch 74/128

958/958 - 5s - 5ms/step - ia: 0.8504 - loss: 0.1059 - mae: 0.2096 - rmse: 0.3078 - smape: 0.4803 - val_ia: 0.7433 - val_loss: 0.0648 - val_mae: 0.1498 - val_rmse: 0.2127 - val_smape: 0.3829

Epoch 75/128

958/958 - 6s - 6ms/step - ia: 0.8512 - loss: 0.1082 - mae: 0.2095 - rmse: 0.3107 - smape: 0.4784 - val_ia: 0.7456 - val_loss: 0.0651 - val_mae: 0.1496 - val_rmse: 0.2125 - val_smape: 0.3818

Epoch 76/128

958/958 - 5s - 6ms/step - ia: 0.8520 - loss: 0.1036 - mae: 0.2081 - rmse: 0.3054 - smape: 0.4784 - val_ia: 0.7455 - val_loss: 0.0650 - val_mae: 0.1498 - val_rmse: 0.2126 - val_smape: 0.3819

Epoch 77/128

958/958 - 5s - 5ms/step - ia: 0.8521 - loss: 0.1030 - mae: 0.2081 - rmse: 0.3038 - smape: 0.4777 - val_ia: 0.7502 - val_loss: 0.0640 - val_mae: 0.1471 - val_rmse: 0.2107 - val_smape: 0.3781

Epoch 78/128

958/958 - 3s - 3ms/step - ia: 0.8533 - loss: 0.1041 - mae: 0.2066 - rmse: 0.3043 - smape: 0.4762 - val_ia: 0.7476 - val_loss: 0.0644 - val_mae: 0.1483 - val_rmse: 0.2115 - val_smape: 0.3794

Epoch 79/128

958/958 - 8s - 8ms/step - ia: 0.8532 - loss: 0.1030 - mae: 0.2063 - rmse: 0.3031 - smape: 0.4756 - val_ia: 0.7469 - val_loss: 0.0639 - val_mae: 0.1479 - val_rmse: 0.2112 - val_smape: 0.3790

Epoch 80/128

958/958 - 4s - 4ms/step - ia: 0.8539 - loss: 0.1040 - mae: 0.2063 - rmse: 0.3035 - smape: 0.4719 - val_ia: 0.7459 - val_loss: 0.0641 - val_mae: 0.1486 - val_rmse: 0.2115 - val_smape: 0.3802

Epoch 81/128

958/958 - 4s - 4ms/step - ia: 0.8531 - loss: 0.1026 - mae: 0.2066 - rmse: 0.3033 - smape: 0.4730 - val_ia: 0.7468 - val_loss: 0.0641 - val_mae: 0.1486 - val_rmse: 0.2114 - val_smape: 0.3795

Epoch 82/128

958/958 - 3s - 4ms/step - ia: 0.8529 - loss: 0.1050 - mae: 0.2072 - rmse: 0.3048 - smape: 0.4744 - val_ia: 0.7492 - val_loss: 0.0635 - val_mae: 0.1470 - val_rmse: 0.2102 - val_smape: 0.3774

Epoch 83/128

958/958 - 3s - 3ms/step - ia: 0.8537 - loss: 0.1018 - mae: 0.2055 - rmse: 0.3019 - smape: 0.4706 - val_ia: 0.7506 - val_loss: 0.0630 - val_mae: 0.1462 - val_rmse: 0.2094 - val_smape: 0.3764

Epoch 84/128

958/958 - 4s - 4ms/step - ia: 0.8550 - loss: 0.1029 - mae: 0.2051 - rmse: 0.3031 - smape: 0.4689 - val_ia: 0.7461 - val_loss: 0.0634 - val_mae: 0.1482 - val_rmse: 0.2107 - val_smape: 0.3789

Epoch 85/128

958/958 - 3s - 4ms/step - ia: 0.8539 - loss: 0.1017 - mae: 0.2054 - rmse: 0.3018 - smape: 0.4704 - val_ia: 0.7499 - val_loss: 0.0631 - val_mae: 0.1466 - val_rmse: 0.2097 - val_smape: 0.3764

Epoch 86/128

958/958 - 3s - 4ms/step - ia: 0.8541 - loss: 0.1027 - mae: 0.2051 - rmse: 0.3026 - smape: 0.4710 - val_ia: 0.7475 - val_loss: 0.0634 - val_mae: 0.1479 - val_rmse: 0.2103 - val_smape: 0.3776

Epoch 87/128

958/958 - 3s - 3ms/step - ia: 0.8537 - loss: 0.1026 - mae: 0.2060 - rmse: 0.3032 - smape: 0.4724 - val_ia: 0.7492 - val_loss: 0.0632 - val_mae: 0.1472 - val_rmse: 0.2098 - val_smape: 0.3763

Epoch 88/128

958/958 - 3s - 3ms/step - ia: 0.8544 - loss: 0.1024 - mae: 0.2049 - rmse: 0.3022 - smape: 0.4677 - val_ia: 0.7444 - val_loss: 0.0635 - val_mae: 0.1491 - val_rmse: 0.2112 - val_smape: 0.3794

Epoch 89/128

958/958 - 3s - 4ms/step - ia: 0.8546 - loss: 0.1001 - mae: 0.2038 - rmse: 0.3000 - smape: 0.4672 - val_ia: 0.7486 - val_loss: 0.0624 - val_mae: 0.1465 - val_rmse: 0.2091 - val_smape: 0.3758

Epoch 90/128

958/958 - 3s - 3ms/step - ia: 0.8541 - loss: 0.1017 - mae: 0.2047 - rmse: 0.3015 - smape: 0.4686 - val_ia: 0.7478 - val_loss: 0.0628 - val_mae: 0.1473 - val_rmse: 0.2096 - val_smape: 0.3764

Epoch 91/128

958/958 - 3s - 3ms/step - ia: 0.8563 - loss: 0.0997 - mae: 0.2019 - rmse: 0.2990 - smape: 0.4641 - val_ia: 0.7509 - val_loss: 0.0626 - val_mae: 0.1462 - val_rmse: 0.2088 - val_smape: 0.3746

Epoch 92/128

958/958 - 3s - 3ms/step - ia: 0.8550 - loss: 0.1011 - mae: 0.2041 - rmse: 0.3000 - smape: 0.4676 - val_ia: 0.7501 - val_loss: 0.0629 - val_mae: 0.1469 - val_rmse: 0.2095 - val_smape: 0.3757

Epoch 93/128

958/958 - 3s - 3ms/step - ia: 0.8553 - loss: 0.1003 - mae: 0.2039 - rmse: 0.3000 - smape: 0.4650 - val_ia: 0.7471 - val_loss: 0.0635 - val_mae: 0.1485 - val_rmse: 0.2105 - val_smape: 0.3771

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.8562 - loss: 0.1005 - mae: 0.2023 - rmse: 0.2990 - smape: 0.4639 - val_ia: 0.7507 - val_loss: 0.0620 - val_mae: 0.1456 - val_rmse: 0.2083 - val_smape: 0.3741

Epoch 95/128

958/958 - 3s - 3ms/step - ia: 0.8563 - loss: 0.1027 - mae: 0.2030 - rmse: 0.3009 - smape: 0.4644 - val_ia: 0.7485 - val_loss: 0.0625 - val_mae: 0.1470 - val_rmse: 0.2092 - val_smape: 0.3755

Epoch 96/128

958/958 - 3s - 3ms/step - ia: 0.8561 - loss: 0.0993 - mae: 0.2028 - rmse: 0.2977 - smape: 0.4655 - val_ia: 0.7489 - val_loss: 0.0625 - val_mae: 0.1472 - val_rmse: 0.2093 - val_smape: 0.3759

Epoch 97/128

958/958 - 9s - 9ms/step - ia: 0.8563 - loss: 0.1007 - mae: 0.2025 - rmse: 0.2991 - smape: 0.4631 - val_ia: 0.7526 - val_loss: 0.0620 - val_mae: 0.1453 - val_rmse: 0.2080 - val_smape: 0.3730

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 10s - 81ms/step - ia: 0.5189 - loss: 0.8313 - mae: 0.6536 - rmse: 0.8928 - smape: 1.1041 - val_ia: 0.6459 - val_loss: 0.3701 - val_mae: 0.4142 - val_rmse: 0.5637 - val_smape: 0.8115

Epoch 2/128

120/120 - 1s - 8ms/step - ia: 0.6728 - loss: 0.4318 - mae: 0.4690 - rmse: 0.6543 - smape: 0.8641 - val_ia: 0.7165 - val_loss: 0.2481 - val_mae: 0.3307 - val_rmse: 0.4599 - val_smape: 0.6877

Epoch 3/128

120/120 - 1s - 11ms/step - ia: 0.7206 - loss: 0.3245 - mae: 0.4033 - rmse: 0.5669 - smape: 0.7774 - val_ia: 0.7520 - val_loss: 0.1938 - val_mae: 0.2890 - val_rmse: 0.4054 - val_smape: 0.6235

Epoch 4/128

120/120 - 1s - 7ms/step - ia: 0.7544 - loss: 0.2597 - mae: 0.3572 - rmse: 0.5063 - smape: 0.7101 - val_ia: 0.7830 - val_loss: 0.1577 - val_mae: 0.2553 - val_rmse: 0.3651 - val_smape: 0.5604

Epoch 5/128

120/120 - 1s - 12ms/step - ia: 0.7748 - loss: 0.2225 - mae: 0.3299 - rmse: 0.4694 - smape: 0.6713 - val_ia: 0.8043 - val_loss: 0.1327 - val_mae: 0.2321 - val_rmse: 0.3348 - val_smape: 0.5147

Epoch 6/128

120/120 - 2s - 18ms/step - ia: 0.7949 - loss: 0.1890 - mae: 0.3020 - rmse: 0.4321 - smape: 0.6274 - val_ia: 0.8192 - val_loss: 0.1139 - val_mae: 0.2136 - val_rmse: 0.3106 - val_smape: 0.4886

Epoch 7/128

120/120 - 1s - 11ms/step - ia: 0.8110 - loss: 0.1643 - mae: 0.2789 - rmse: 0.4025 - smape: 0.5930 - val_ia: 0.8298 - val_loss: 0.1030 - val_mae: 0.1992 - val_rmse: 0.2941 - val_smape: 0.4634

Epoch 8/128

120/120 - 1s - 11ms/step - ia: 0.8220 - loss: 0.1510 - mae: 0.2627 - rmse: 0.3856 - smape: 0.5637 - val_ia: 0.8390 - val_loss: 0.0932 - val_mae: 0.1885 - val_rmse: 0.2801 - val_smape: 0.4398

Epoch 9/128

120/120 - 2s - 14ms/step - ia: 0.8312 - loss: 0.1385 - mae: 0.2490 - rmse: 0.3691 - smape: 0.5429 - val_ia: 0.8442 - val_loss: 0.0878 - val_mae: 0.1820 - val_rmse: 0.2723 - val_smape: 0.4288

Epoch 10/128

120/120 - 1s - 10ms/step - ia: 0.8399 - loss: 0.1276 - mae: 0.2368 - rmse: 0.3540 - smape: 0.5227 - val_ia: 0.8546 - val_loss: 0.0832 - val_mae: 0.1721 - val_rmse: 0.2646 - val_smape: 0.4123

Epoch 11/128

120/120 - 1s - 8ms/step - ia: 0.8450 - loss: 0.1211 - mae: 0.2290 - rmse: 0.3439 - smape: 0.5089 - val_ia: 0.8598 - val_loss: 0.0788 - val_mae: 0.1662 - val_rmse: 0.2576 - val_smape: 0.4003

Epoch 12/128

120/120 - 1s - 7ms/step - ia: 0.8501 - loss: 0.1157 - mae: 0.2220 - rmse: 0.3361 - smape: 0.4974 - val_ia: 0.8642 - val_loss: 0.0758 - val_mae: 0.1605 - val_rmse: 0.2518 - val_smape: 0.3909

Epoch 13/128

120/120 - 1s - 11ms/step - ia: 0.8544 - loss: 0.1103 - mae: 0.2156 - rmse: 0.3285 - smape: 0.4843 - val_ia: 0.8646 - val_loss: 0.0747 - val_mae: 0.1592 - val_rmse: 0.2505 - val_smape: 0.3899

Epoch 14/128

120/120 - 2s - 13ms/step - ia: 0.8586 - loss: 0.1069 - mae: 0.2096 - rmse: 0.3233 - smape: 0.4727 - val_ia: 0.8685 - val_loss: 0.0713 - val_mae: 0.1561 - val_rmse: 0.2455 - val_smape: 0.3832

Epoch 15/128

120/120 - 2s - 14ms/step - ia: 0.8603 - loss: 0.1043 - mae: 0.2071 - rmse: 0.3193 - smape: 0.4701 - val_ia: 0.8711 - val_loss: 0.0697 - val_mae: 0.1519 - val_rmse: 0.2416 - val_smape: 0.3754

Epoch 16/128

120/120 - 1s - 8ms/step - ia: 0.8636 - loss: 0.1010 - mae: 0.2020 - rmse: 0.3139 - smape: 0.4601 - val_ia: 0.8711 - val_loss: 0.0689 - val_mae: 0.1520 - val_rmse: 0.2406 - val_smape: 0.3779

Epoch 17/128

120/120 - 1s - 8ms/step - ia: 0.8662 - loss: 0.0979 - mae: 0.1984 - rmse: 0.3080 - smape: 0.4539 - val_ia: 0.8731 - val_loss: 0.0683 - val_mae: 0.1495 - val_rmse: 0.2401 - val_smape: 0.3733

Epoch 18/128

120/120 - 1s - 8ms/step - ia: 0.8680 - loss: 0.0968 - mae: 0.1959 - rmse: 0.3070 - smape: 0.4460 - val_ia: 0.8751 - val_loss: 0.0671 - val_mae: 0.1476 - val_rmse: 0.2379 - val_smape: 0.3675

Epoch 19/128

120/120 - 1s - 10ms/step - ia: 0.8693 - loss: 0.0952 - mae: 0.1936 - rmse: 0.3051 - smape: 0.4431 - val_ia: 0.8744 - val_loss: 0.0664 - val_mae: 0.1475 - val_rmse: 0.2362 - val_smape: 0.3678

Epoch 20/128

120/120 - 1s - 5ms/step - ia: 0.8701 - loss: 0.0949 - mae: 0.1927 - rmse: 0.3042 - smape: 0.4423 - val_ia: 0.8770 - val_loss: 0.0652 - val_mae: 0.1449 - val_rmse: 0.2345 - val_smape: 0.3644

Epoch 21/128

120/120 - 1s - 4ms/step - ia: 0.8726 - loss: 0.0919 - mae: 0.1890 - rmse: 0.2995 - smape: 0.4329 - val_ia: 0.8736 - val_loss: 0.0654 - val_mae: 0.1475 - val_rmse: 0.2353 - val_smape: 0.3707

Epoch 22/128

120/120 - 1s - 5ms/step - ia: 0.8736 - loss: 0.0911 - mae: 0.1875 - rmse: 0.2973 - smape: 0.4311 - val_ia: 0.8779 - val_loss: 0.0643 - val_mae: 0.1434 - val_rmse: 0.2328 - val_smape: 0.3606

Epoch 23/128

120/120 - 1s - 7ms/step - ia: 0.8733 - loss: 0.0906 - mae: 0.1879 - rmse: 0.2975 - smape: 0.4322 - val_ia: 0.8776 - val_loss: 0.0640 - val_mae: 0.1437 - val_rmse: 0.2330 - val_smape: 0.3611

Epoch 24/128

120/120 - 2s - 14ms/step - ia: 0.8752 - loss: 0.0891 - mae: 0.1852 - rmse: 0.2953 - smape: 0.4266 - val_ia: 0.8783 - val_loss: 0.0635 - val_mae: 0.1429 - val_rmse: 0.2318 - val_smape: 0.3622

Epoch 25/128

120/120 - 1s - 12ms/step - ia: 0.8761 - loss: 0.0881 - mae: 0.1838 - rmse: 0.2936 - smape: 0.4243 - val_ia: 0.8746 - val_loss: 0.0652 - val_mae: 0.1466 - val_rmse: 0.2357 - val_smape: 0.3716

Epoch 26/128

120/120 - 1s - 7ms/step - ia: 0.8761 - loss: 0.0880 - mae: 0.1839 - rmse: 0.2927 - smape: 0.4236 - val_ia: 0.8794 - val_loss: 0.0627 - val_mae: 0.1414 - val_rmse: 0.2305 - val_smape: 0.3613

Epoch 27/128

120/120 - 1s - 7ms/step - ia: 0.8764 - loss: 0.0883 - mae: 0.1832 - rmse: 0.2937 - smape: 0.4235 - val_ia: 0.8798 - val_loss: 0.0632 - val_mae: 0.1401 - val_rmse: 0.2301 - val_smape: 0.3553

Epoch 28/128

120/120 - 1s - 12ms/step - ia: 0.8766 - loss: 0.0863 - mae: 0.1829 - rmse: 0.2901 - smape: 0.4247 - val_ia: 0.8814 - val_loss: 0.0623 - val_mae: 0.1391 - val_rmse: 0.2298 - val_smape: 0.3555

Epoch 29/128

120/120 - 1s - 9ms/step - ia: 0.8777 - loss: 0.0860 - mae: 0.1814 - rmse: 0.2898 - smape: 0.4204 - val_ia: 0.8822 - val_loss: 0.0618 - val_mae: 0.1378 - val_rmse: 0.2280 - val_smape: 0.3523

Epoch 30/128

120/120 - 1s - 9ms/step - ia: 0.8780 - loss: 0.0866 - mae: 0.1808 - rmse: 0.2903 - smape: 0.4205 - val_ia: 0.8792 - val_loss: 0.0626 - val_mae: 0.1407 - val_rmse: 0.2300 - val_smape: 0.3586

Epoch 31/128

120/120 - 2s - 14ms/step - ia: 0.8790 - loss: 0.0844 - mae: 0.1796 - rmse: 0.2871 - smape: 0.4182 - val_ia: 0.8813 - val_loss: 0.0614 - val_mae: 0.1387 - val_rmse: 0.2284 - val_smape: 0.3537

Epoch 32/128

120/120 - 1s - 9ms/step - ia: 0.8790 - loss: 0.0856 - mae: 0.1794 - rmse: 0.2883 - smape: 0.4174 - val_ia: 0.8805 - val_loss: 0.0617 - val_mae: 0.1388 - val_rmse: 0.2287 - val_smape: 0.3569

Epoch 33/128

120/120 - 1s - 9ms/step - ia: 0.8802 - loss: 0.0838 - mae: 0.1780 - rmse: 0.2857 - smape: 0.4141 - val_ia: 0.8822 - val_loss: 0.0613 - val_mae: 0.1374 - val_rmse: 0.2273 - val_smape: 0.3510

Epoch 34/128

120/120 - 1s - 8ms/step - ia: 0.8790 - loss: 0.0839 - mae: 0.1793 - rmse: 0.2867 - smape: 0.4163 - val_ia: 0.8823 - val_loss: 0.0603 - val_mae: 0.1372 - val_rmse: 0.2266 - val_smape: 0.3533

Epoch 35/128

120/120 - 1s - 10ms/step - ia: 0.8805 - loss: 0.0816 - mae: 0.1772 - rmse: 0.2819 - smape: 0.4137 - val_ia: 0.8813 - val_loss: 0.0602 - val_mae: 0.1380 - val_rmse: 0.2267 - val_smape: 0.3552

Epoch 36/128

120/120 - 1s - 5ms/step - ia: 0.8805 - loss: 0.0835 - mae: 0.1772 - rmse: 0.2856 - smape: 0.4131 - val_ia: 0.8818 - val_loss: 0.0605 - val_mae: 0.1372 - val_rmse: 0.2266 - val_smape: 0.3516

Epoch 37/128

120/120 - 1s - 7ms/step - ia: 0.8805 - loss: 0.0820 - mae: 0.1771 - rmse: 0.2831 - smape: 0.4136 - val_ia: 0.8839 - val_loss: 0.0599 - val_mae: 0.1355 - val_rmse: 0.2254 - val_smape: 0.3501

Epoch 38/128

120/120 - 1s - 10ms/step - ia: 0.8810 - loss: 0.0831 - mae: 0.1764 - rmse: 0.2842 - smape: 0.4114 - val_ia: 0.8771 - val_loss: 0.0612 - val_mae: 0.1422 - val_rmse: 0.2286 - val_smape: 0.3638

Epoch 39/128

120/120 - 1s - 7ms/step - ia: 0.8810 - loss: 0.0823 - mae: 0.1764 - rmse: 0.2828 - smape: 0.4116 - val_ia: 0.8828 - val_loss: 0.0597 - val_mae: 0.1370 - val_rmse: 0.2262 - val_smape: 0.3521

Epoch 40/128

120/120 - 1s - 8ms/step - ia: 0.8816 - loss: 0.0813 - mae: 0.1755 - rmse: 0.2816 - smape: 0.4099 - val_ia: 0.8822 - val_loss: 0.0594 - val_mae: 0.1364 - val_rmse: 0.2254 - val_smape: 0.3535

Epoch 41/128

120/120 - 1s - 8ms/step - ia: 0.8807 - loss: 0.0831 - mae: 0.1769 - rmse: 0.2841 - smape: 0.4128 - val_ia: 0.8787 - val_loss: 0.0603 - val_mae: 0.1403 - val_rmse: 0.2277 - val_smape: 0.3587

Epoch 42/128

120/120 - 1s - 8ms/step - ia: 0.8813 - loss: 0.0816 - mae: 0.1760 - rmse: 0.2823 - smape: 0.4103 - val_ia: 0.8784 - val_loss: 0.0599 - val_mae: 0.1399 - val_rmse: 0.2274 - val_smape: 0.3585

Epoch 43/128

120/120 - 2s - 13ms/step - ia: 0.8817 - loss: 0.0825 - mae: 0.1753 - rmse: 0.2830 - smape: 0.4102 - val_ia: 0.8780 - val_loss: 0.0600 - val_mae: 0.1401 - val_rmse: 0.2274 - val_smape: 0.3606

Epoch 44/128

120/120 - 1s - 7ms/step - ia: 0.8823 - loss: 0.0805 - mae: 0.1745 - rmse: 0.2799 - smape: 0.4080 - val_ia: 0.8793 - val_loss: 0.0604 - val_mae: 0.1399 - val_rmse: 0.2265 - val_smape: 0.3595

Epoch 45/128

120/120 - 1s - 12ms/step - ia: 0.8819 - loss: 0.0818 - mae: 0.1748 - rmse: 0.2818 - smape: 0.4092 - val_ia: 0.8794 - val_loss: 0.0599 - val_mae: 0.1394 - val_rmse: 0.2271 - val_smape: 0.3563

Epoch 46/128

120/120 - 1s - 8ms/step - ia: 0.8828 - loss: 0.0796 - mae: 0.1736 - rmse: 0.2782 - smape: 0.4065 - val_ia: 0.8822 - val_loss: 0.0597 - val_mae: 0.1368 - val_rmse: 0.2253 - val_smape: 0.3551

Epoch 47/128

120/120 - 1s - 12ms/step - ia: 0.8823 - loss: 0.0803 - mae: 0.1741 - rmse: 0.2794 - smape: 0.4084 - val_ia: 0.8835 - val_loss: 0.0591 - val_mae: 0.1351 - val_rmse: 0.2244 - val_smape: 0.3503

Epoch 48/128

120/120 - 2s - 14ms/step - ia: 0.8825 - loss: 0.0799 - mae: 0.1741 - rmse: 0.2792 - smape: 0.4077 - val_ia: 0.8848 - val_loss: 0.0585 - val_mae: 0.1340 - val_rmse: 0.2237 - val_smape: 0.3484

Epoch 49/128

120/120 - 1s - 9ms/step - ia: 0.8832 - loss: 0.0808 - mae: 0.1728 - rmse: 0.2806 - smape: 0.4047 - val_ia: 0.8785 - val_loss: 0.0595 - val_mae: 0.1397 - val_rmse: 0.2265 - val_smape: 0.3588

Epoch 50/128

120/120 - 1s - 7ms/step - ia: 0.8838 - loss: 0.0791 - mae: 0.1723 - rmse: 0.2773 - smape: 0.4057 - val_ia: 0.8818 - val_loss: 0.0590 - val_mae: 0.1374 - val_rmse: 0.2255 - val_smape: 0.3569

Epoch 51/128

120/120 - 1s - 7ms/step - ia: 0.8834 - loss: 0.0794 - mae: 0.1727 - rmse: 0.2785 - smape: 0.4047 - val_ia: 0.8797 - val_loss: 0.0597 - val_mae: 0.1392 - val_rmse: 0.2275 - val_smape: 0.3573

Epoch 52/128

120/120 - 1s - 12ms/step - ia: 0.8834 - loss: 0.0792 - mae: 0.1727 - rmse: 0.2778 - smape: 0.4044 - val_ia: 0.8744 - val_loss: 0.0605 - val_mae: 0.1437 - val_rmse: 0.2280 - val_smape: 0.3658

Epoch 53/128

120/120 - 1s - 11ms/step - ia: 0.8830 - loss: 0.0800 - mae: 0.1733 - rmse: 0.2785 - smape: 0.4053 - val_ia: 0.8816 - val_loss: 0.0597 - val_mae: 0.1375 - val_rmse: 0.2265 - val_smape: 0.3565

Epoch 54/128

120/120 - 1s - 6ms/step - ia: 0.8835 - loss: 0.0784 - mae: 0.1725 - rmse: 0.2764 - smape: 0.4052 - val_ia: 0.8802 - val_loss: 0.0597 - val_mae: 0.1381 - val_rmse: 0.2251 - val_smape: 0.3539

Epoch 55/128

120/120 - 1s - 7ms/step - ia: 0.8830 - loss: 0.0804 - mae: 0.1731 - rmse: 0.2800 - smape: 0.4051 - val_ia: 0.8830 - val_loss: 0.0584 - val_mae: 0.1355 - val_rmse: 0.2240 - val_smape: 0.3516

Epoch 56/128

120/120 - 2s - 13ms/step - ia: 0.8845 - loss: 0.0788 - mae: 0.1713 - rmse: 0.2772 - smape: 0.4019 - val_ia: 0.8827 - val_loss: 0.0589 - val_mae: 0.1356 - val_rmse: 0.2247 - val_smape: 0.3522

Epoch 57/128

120/120 - 1s - 11ms/step - ia: 0.8847 - loss: 0.0784 - mae: 0.1709 - rmse: 0.2761 - smape: 0.4017 - val_ia: 0.8837 - val_loss: 0.0582 - val_mae: 0.1344 - val_rmse: 0.2231 - val_smape: 0.3489

Epoch 58/128

120/120 - 1s - 6ms/step - ia: 0.8838 - loss: 0.0790 - mae: 0.1718 - rmse: 0.2778 - smape: 0.4030 - val_ia: 0.8827 - val_loss: 0.0585 - val_mae: 0.1355 - val_rmse: 0.2235 - val_smape: 0.3502

Epoch 59/128

120/120 - 1s - 7ms/step - ia: 0.8840 - loss: 0.0781 - mae: 0.1716 - rmse: 0.2754 - smape: 0.4038 - val_ia: 0.8835 - val_loss: 0.0578 - val_mae: 0.1343 - val_rmse: 0.2228 - val_smape: 0.3496

Epoch 60/128

120/120 - 2s - 13ms/step - ia: 0.8838 - loss: 0.0776 - mae: 0.1721 - rmse: 0.2747 - smape: 0.4076 - val_ia: 0.8817 - val_loss: 0.0598 - val_mae: 0.1399 - val_rmse: 0.2279 - val_smape: 0.3555

Epoch 61/128

120/120 - 1s - 6ms/step - ia: 0.8840 - loss: 0.0791 - mae: 0.1717 - rmse: 0.2774 - smape: 0.4010 - val_ia: 0.8833 - val_loss: 0.0579 - val_mae: 0.1346 - val_rmse: 0.2227 - val_smape: 0.3495

Epoch 62/128

120/120 - 1s - 10ms/step - ia: 0.8842 - loss: 0.0787 - mae: 0.1715 - rmse: 0.2760 - smape: 0.4032 - val_ia: 0.8857 - val_loss: 0.0578 - val_mae: 0.1328 - val_rmse: 0.2227 - val_smape: 0.3472

Epoch 63/128

120/120 - 0s - 4ms/step - ia: 0.8845 - loss: 0.0779 - mae: 0.1711 - rmse: 0.2751 - smape: 0.4034 - val_ia: 0.8761 - val_loss: 0.0606 - val_mae: 0.1417 - val_rmse: 0.2297 - val_smape: 0.3648

Epoch 64/128

120/120 - 0s - 4ms/step - ia: 0.8847 - loss: 0.0772 - mae: 0.1705 - rmse: 0.2741 - smape: 0.4033 - val_ia: 0.8829 - val_loss: 0.0577 - val_mae: 0.1351 - val_rmse: 0.2232 - val_smape: 0.3523

Epoch 65/128

120/120 - 1s - 7ms/step - ia: 0.8846 - loss: 0.0779 - mae: 0.1707 - rmse: 0.2747 - smape: 0.4026 - val_ia: 0.8829 - val_loss: 0.0576 - val_mae: 0.1353 - val_rmse: 0.2229 - val_smape: 0.3522

Epoch 66/128

120/120 - 1s - 5ms/step - ia: 0.8849 - loss: 0.0783 - mae: 0.1702 - rmse: 0.2764 - smape: 0.4031 - val_ia: 0.8829 - val_loss: 0.0587 - val_mae: 0.1360 - val_rmse: 0.2254 - val_smape: 0.3532

Epoch 67/128

120/120 - 1s - 6ms/step - ia: 0.8864 - loss: 0.0760 - mae: 0.1684 - rmse: 0.2723 - smape: 0.3977 - val_ia: 0.8819 - val_loss: 0.0589 - val_mae: 0.1362 - val_rmse: 0.2242 - val_smape: 0.3522

Epoch 68/128

120/120 - 1s - 5ms/step - ia: 0.8844 - loss: 0.0768 - mae: 0.1713 - rmse: 0.2734 - smape: 0.4044 - val_ia: 0.8793 - val_loss: 0.0581 - val_mae: 0.1386 - val_rmse: 0.2240 - val_smape: 0.3591

Epoch 69/128

120/120 - 1s - 4ms/step - ia: 0.8853 - loss: 0.0774 - mae: 0.1697 - rmse: 0.2744 - smape: 0.4023 - val_ia: 0.8838 - val_loss: 0.0575 - val_mae: 0.1339 - val_rmse: 0.2228 - val_smape: 0.3501

Epoch 70/128

120/120 - 0s - 4ms/step - ia: 0.8855 - loss: 0.0763 - mae: 0.1697 - rmse: 0.2725 - smape: 0.4020 - val_ia: 0.8841 - val_loss: 0.0578 - val_mae: 0.1342 - val_rmse: 0.2225 - val_smape: 0.3486

Epoch 71/128

120/120 - 1s - 5ms/step - ia: 0.8864 - loss: 0.0765 - mae: 0.1683 - rmse: 0.2725 - smape: 0.3964 - val_ia: 0.8808 - val_loss: 0.0580 - val_mae: 0.1374 - val_rmse: 0.2230 - val_smape: 0.3548

Epoch 72/128

120/120 - 0s - 3ms/step - ia: 0.8849 - loss: 0.0771 - mae: 0.1701 - rmse: 0.2746 - smape: 0.4026 - val_ia: 0.8854 - val_loss: 0.0574 - val_mae: 0.1327 - val_rmse: 0.2222 - val_smape: 0.3479

Epoch 73/128

120/120 - 0s - 3ms/step - ia: 0.8852 - loss: 0.0772 - mae: 0.1697 - rmse: 0.2744 - smape: 0.4007 - val_ia: 0.8854 - val_loss: 0.0575 - val_mae: 0.1327 - val_rmse: 0.2222 - val_smape: 0.3470

Epoch 74/128

120/120 - 0s - 3ms/step - ia: 0.8861 - loss: 0.0766 - mae: 0.1685 - rmse: 0.2736 - smape: 0.3989 - val_ia: 0.8858 - val_loss: 0.0569 - val_mae: 0.1319 - val_rmse: 0.2216 - val_smape: 0.3469

Epoch 75/128

120/120 - 0s - 3ms/step - ia: 0.8856 - loss: 0.0766 - mae: 0.1693 - rmse: 0.2725 - smape: 0.3981 - val_ia: 0.8838 - val_loss: 0.0574 - val_mae: 0.1342 - val_rmse: 0.2221 - val_smape: 0.3514

Epoch 76/128

120/120 - 1s - 6ms/step - ia: 0.8865 - loss: 0.0756 - mae: 0.1681 - rmse: 0.2717 - smape: 0.3984 - val_ia: 0.8858 - val_loss: 0.0570 - val_mae: 0.1317 - val_rmse: 0.2216 - val_smape: 0.3457

Epoch 77/128

120/120 - 1s - 6ms/step - ia: 0.8856 - loss: 0.0768 - mae: 0.1692 - rmse: 0.2728 - smape: 0.4007 - val_ia: 0.8823 - val_loss: 0.0580 - val_mae: 0.1354 - val_rmse: 0.2226 - val_smape: 0.3519

Epoch 78/128

120/120 - 0s - 4ms/step - ia: 0.8851 - loss: 0.0776 - mae: 0.1699 - rmse: 0.2752 - smape: 0.4012 - val_ia: 0.8769 - val_loss: 0.0592 - val_mae: 0.1416 - val_rmse: 0.2259 - val_smape: 0.3648

Epoch 79/128

120/120 - 0s - 4ms/step - ia: 0.8849 - loss: 0.0780 - mae: 0.1704 - rmse: 0.2761 - smape: 0.4002 - val_ia: 0.8811 - val_loss: 0.0577 - val_mae: 0.1364 - val_rmse: 0.2229 - val_smape: 0.3536

Epoch 80/128

120/120 - 0s - 3ms/step - ia: 0.8851 - loss: 0.0767 - mae: 0.1697 - rmse: 0.2733 - smape: 0.4024 - val_ia: 0.8820 - val_loss: 0.0577 - val_mae: 0.1357 - val_rmse: 0.2227 - val_smape: 0.3519

Epoch 81/128

120/120 - 1s - 6ms/step - ia: 0.8855 - loss: 0.0762 - mae: 0.1697 - rmse: 0.2722 - smape: 0.4014 - val_ia: 0.8816 - val_loss: 0.0583 - val_mae: 0.1371 - val_rmse: 0.2237 - val_smape: 0.3545

Epoch 82/128

120/120 - 1s - 6ms/step - ia: 0.8849 - loss: 0.0761 - mae: 0.1701 - rmse: 0.2722 - smape: 0.4021 - val_ia: 0.8850 - val_loss: 0.0576 - val_mae: 0.1331 - val_rmse: 0.2229 - val_smape: 0.3497

Epoch 83/128

120/120 - 1s - 5ms/step - ia: 0.8863 - loss: 0.0754 - mae: 0.1682 - rmse: 0.2711 - smape: 0.3981 - val_ia: 0.8835 - val_loss: 0.0572 - val_mae: 0.1336 - val_rmse: 0.2220 - val_smape: 0.3504

Epoch 84/128

120/120 - 1s - 6ms/step - ia: 0.8867 - loss: 0.0757 - mae: 0.1677 - rmse: 0.2715 - smape: 0.3969 - val_ia: 0.8799 - val_loss: 0.0586 - val_mae: 0.1377 - val_rmse: 0.2243 - val_smape: 0.3554

Epoch 85/128

120/120 - 0s - 4ms/step - ia: 0.8868 - loss: 0.0752 - mae: 0.1676 - rmse: 0.2702 - smape: 0.3989 - val_ia: 0.8760 - val_loss: 0.0602 - val_mae: 0.1410 - val_rmse: 0.2284 - val_smape: 0.3652

Epoch 86/128

120/120 - 1s - 6ms/step - ia: 0.8863 - loss: 0.0760 - mae: 0.1682 - rmse: 0.2717 - smape: 0.3973 - val_ia: 0.8845 - val_loss: 0.0576 - val_mae: 0.1331 - val_rmse: 0.2222 - val_smape: 0.3482

Epoch 87/128

120/120 - 1s - 5ms/step - ia: 0.8861 - loss: 0.0759 - mae: 0.1684 - rmse: 0.2721 - smape: 0.3991 - val_ia: 0.8809 - val_loss: 0.0582 - val_mae: 0.1374 - val_rmse: 0.2232 - val_smape: 0.3548

Epoch 88/128

120/120 - 1s - 5ms/step - ia: 0.8874 - loss: 0.0747 - mae: 0.1664 - rmse: 0.2694 - smape: 0.3961 - val_ia: 0.8847 - val_loss: 0.0568 - val_mae: 0.1326 - val_rmse: 0.2213 - val_smape: 0.3479

Epoch 89/128

120/120 - 1s - 4ms/step - ia: 0.8857 - loss: 0.0756 - mae: 0.1691 - rmse: 0.2720 - smape: 0.4005 - val_ia: 0.8832 - val_loss: 0.0573 - val_mae: 0.1348 - val_rmse: 0.2220 - val_smape: 0.3532

Epoch 90/128

120/120 - 1s - 6ms/step - ia: 0.8862 - loss: 0.0758 - mae: 0.1682 - rmse: 0.2719 - smape: 0.3985 - val_ia: 0.8839 - val_loss: 0.0573 - val_mae: 0.1345 - val_rmse: 0.2234 - val_smape: 0.3517

Epoch 91/128

120/120 - 0s - 4ms/step - ia: 0.8861 - loss: 0.0763 - mae: 0.1686 - rmse: 0.2732 - smape: 0.4004 - val_ia: 0.8844 - val_loss: 0.0568 - val_mae: 0.1333 - val_rmse: 0.2213 - val_smape: 0.3504

Epoch 92/128

120/120 - 0s - 4ms/step - ia: 0.8871 - loss: 0.0750 - mae: 0.1672 - rmse: 0.2702 - smape: 0.3963 - val_ia: 0.8857 - val_loss: 0.0567 - val_mae: 0.1320 - val_rmse: 0.2212 - val_smape: 0.3478

Epoch 93/128

120/120 - 1s - 6ms/step - ia: 0.8863 - loss: 0.0754 - mae: 0.1682 - rmse: 0.2711 - smape: 0.3988 - val_ia: 0.8825 - val_loss: 0.0570 - val_mae: 0.1348 - val_rmse: 0.2224 - val_smape: 0.3540

Epoch 94/128

120/120 - 0s - 3ms/step - ia: 0.8873 - loss: 0.0752 - mae: 0.1670 - rmse: 0.2710 - smape: 0.3947 - val_ia: 0.8841 - val_loss: 0.0569 - val_mae: 0.1335 - val_rmse: 0.2218 - val_smape: 0.3501

Epoch 95/128

120/120 - 0s - 4ms/step - ia: 0.8868 - loss: 0.0757 - mae: 0.1674 - rmse: 0.2712 - smape: 0.3977 - val_ia: 0.8853 - val_loss: 0.0569 - val_mae: 0.1325 - val_rmse: 0.2215 - val_smape: 0.3489

Epoch 96/128

120/120 - 1s - 5ms/step - ia: 0.8860 - loss: 0.0763 - mae: 0.1686 - rmse: 0.2719 - smape: 0.3971 - val_ia: 0.8785 - val_loss: 0.0600 - val_mae: 0.1409 - val_rmse: 0.2301 - val_smape: 0.3646

Epoch 97/128

120/120 - 1s - 7ms/step - ia: 0.8866 - loss: 0.0751 - mae: 0.1678 - rmse: 0.2701 - smape: 0.4007 - val_ia: 0.8833 - val_loss: 0.0569 - val_mae: 0.1342 - val_rmse: 0.2222 - val_smape: 0.3498

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 14s - 15ms/step - ia: 0.7377 - loss: 0.2671 - mae: 0.3631 - rmse: 0.4928 - smape: 0.7340 - val_ia: 0.6453 - val_loss: 0.0932 - val_mae: 0.2031 - val_rmse: 0.2723 - val_smape: 0.4997

Epoch 2/32

958/958 - 8s - 9ms/step - ia: 0.8170 - loss: 0.1385 - mae: 0.2553 - rmse: 0.3578 - smape: 0.5668 - val_ia: 0.6630 - val_loss: 0.0784 - val_mae: 0.1876 - val_rmse: 0.2494 - val_smape: 0.4620

Epoch 3/32

958/958 - 5s - 6ms/step - ia: 0.8378 - loss: 0.1159 - mae: 0.2273 - rmse: 0.3259 - smape: 0.5165 - val_ia: 0.6639 - val_loss: 0.0823 - val_mae: 0.1921 - val_rmse: 0.2520 - val_smape: 0.4599

Epoch 4/32

958/958 - 5s - 5ms/step - ia: 0.8512 - loss: 0.0990 - mae: 0.2088 - rmse: 0.2996 - smape: 0.4860 - val_ia: 0.6691 - val_loss: 0.0724 - val_mae: 0.1817 - val_rmse: 0.2407 - val_smape: 0.4471

Epoch 5/32

958/958 - 5s - 5ms/step - ia: 0.8588 - loss: 0.0944 - mae: 0.1991 - rmse: 0.2909 - smape: 0.4661 - val_ia: 0.6653 - val_loss: 0.0731 - val_mae: 0.1860 - val_rmse: 0.2409 - val_smape: 0.4473

Epoch 6/32

958/958 - 7s - 7ms/step - ia: 0.8639 - loss: 0.0895 - mae: 0.1921 - rmse: 0.2823 - smape: 0.4510 - val_ia: 0.6823 - val_loss: 0.0714 - val_mae: 0.1773 - val_rmse: 0.2346 - val_smape: 0.4309

Epoch 7/32

958/958 - 3s - 4ms/step - ia: 0.8677 - loss: 0.0840 - mae: 0.1861 - rmse: 0.2744 - smape: 0.4390 - val_ia: 0.7078 - val_loss: 0.0660 - val_mae: 0.1639 - val_rmse: 0.2232 - val_smape: 0.4073

Epoch 8/32

958/958 - 6s - 6ms/step - ia: 0.8714 - loss: 0.0820 - mae: 0.1814 - rmse: 0.2705 - smape: 0.4312 - val_ia: 0.7070 - val_loss: 0.0682 - val_mae: 0.1676 - val_rmse: 0.2250 - val_smape: 0.4091

Epoch 9/32

958/958 - 6s - 6ms/step - ia: 0.8733 - loss: 0.0798 - mae: 0.1791 - rmse: 0.2656 - smape: 0.4264 - val_ia: 0.7118 - val_loss: 0.0619 - val_mae: 0.1593 - val_rmse: 0.2182 - val_smape: 0.4013

Epoch 10/32

958/958 - 5s - 5ms/step - ia: 0.8757 - loss: 0.0782 - mae: 0.1756 - rmse: 0.2628 - smape: 0.4205 - val_ia: 0.6952 - val_loss: 0.0725 - val_mae: 0.1756 - val_rmse: 0.2316 - val_smape: 0.4173

Epoch 11/32

958/958 - 4s - 5ms/step - ia: 0.8772 - loss: 0.0761 - mae: 0.1737 - rmse: 0.2606 - smape: 0.4147 - val_ia: 0.7382 - val_loss: 0.0586 - val_mae: 0.1472 - val_rmse: 0.2087 - val_smape: 0.3815

Epoch 12/32

958/958 - 5s - 5ms/step - ia: 0.8773 - loss: 0.0765 - mae: 0.1732 - rmse: 0.2602 - smape: 0.4135 - val_ia: 0.7016 - val_loss: 0.0640 - val_mae: 0.1657 - val_rmse: 0.2219 - val_smape: 0.4097

Epoch 13/32

958/958 - 4s - 4ms/step - ia: 0.8803 - loss: 0.0735 - mae: 0.1698 - rmse: 0.2545 - smape: 0.4078 - val_ia: 0.7118 - val_loss: 0.0608 - val_mae: 0.1590 - val_rmse: 0.2165 - val_smape: 0.3980

Epoch 14/32

958/958 - 5s - 5ms/step - ia: 0.8810 - loss: 0.0731 - mae: 0.1687 - rmse: 0.2533 - smape: 0.4046 - val_ia: 0.6948 - val_loss: 0.0633 - val_mae: 0.1669 - val_rmse: 0.2214 - val_smape: 0.4076

Epoch 15/32

958/958 - 6s - 6ms/step - ia: 0.8820 - loss: 0.0721 - mae: 0.1668 - rmse: 0.2514 - smape: 0.4003 - val_ia: 0.6910 - val_loss: 0.0738 - val_mae: 0.1777 - val_rmse: 0.2323 - val_smape: 0.4132

Epoch 16/32

958/958 - 5s - 5ms/step - ia: 0.8815 - loss: 0.0730 - mae: 0.1679 - rmse: 0.2533 - smape: 0.4009 - val_ia: 0.7204 - val_loss: 0.0612 - val_mae: 0.1566 - val_rmse: 0.2146 - val_smape: 0.3933

Epoch 17/32

958/958 - 4s - 5ms/step - ia: 0.8829 - loss: 0.0726 - mae: 0.1659 - rmse: 0.2523 - smape: 0.3976 - val_ia: 0.7035 - val_loss: 0.0650 - val_mae: 0.1668 - val_rmse: 0.2214 - val_smape: 0.4064

Epoch 18/32

958/958 - 5s - 5ms/step - ia: 0.8846 - loss: 0.0696 - mae: 0.1638 - rmse: 0.2474 - smape: 0.3956 - val_ia: 0.7230 - val_loss: 0.0594 - val_mae: 0.1545 - val_rmse: 0.2109 - val_smape: 0.3891

Epoch 19/32

958/958 - 5s - 5ms/step - ia: 0.8843 - loss: 0.0698 - mae: 0.1636 - rmse: 0.2479 - smape: 0.3955 - val_ia: 0.6962 - val_loss: 0.0664 - val_mae: 0.1701 - val_rmse: 0.2242 - val_smape: 0.4082

Epoch 20/32

958/958 - 4s - 4ms/step - ia: 0.8844 - loss: 0.0690 - mae: 0.1638 - rmse: 0.2470 - smape: 0.3958 - val_ia: 0.7144 - val_loss: 0.0647 - val_mae: 0.1622 - val_rmse: 0.2184 - val_smape: 0.3949

Epoch 21/32

958/958 - 4s - 5ms/step - ia: 0.8856 - loss: 0.0692 - mae: 0.1625 - rmse: 0.2469 - smape: 0.3928 - val_ia: 0.6907 - val_loss: 0.0660 - val_mae: 0.1717 - val_rmse: 0.2249 - val_smape: 0.4107

Epoch 22/32

958/958 - 3s - 3ms/step - ia: 0.8860 - loss: 0.0687 - mae: 0.1618 - rmse: 0.2460 - smape: 0.3908 - val_ia: 0.7018 - val_loss: 0.0661 - val_mae: 0.1687 - val_rmse: 0.2233 - val_smape: 0.4067

Epoch 23/32

958/958 - 2s - 2ms/step - ia: 0.8868 - loss: 0.0671 - mae: 0.1609 - rmse: 0.2438 - smape: 0.3897 - val_ia: 0.7073 - val_loss: 0.0638 - val_mae: 0.1638 - val_rmse: 0.2192 - val_smape: 0.3997

Epoch 24/32

958/958 - 3s - 3ms/step - ia: 0.8858 - loss: 0.0693 - mae: 0.1623 - rmse: 0.2467 - smape: 0.3899 - val_ia: 0.6814 - val_loss: 0.0735 - val_mae: 0.1818 - val_rmse: 0.2353 - val_smape: 0.4264

Epoch 25/32

958/958 - 5s - 5ms/step - ia: 0.8870 - loss: 0.0672 - mae: 0.1601 - rmse: 0.2434 - smape: 0.3867 - val_ia: 0.6995 - val_loss: 0.0653 - val_mae: 0.1675 - val_rmse: 0.2227 - val_smape: 0.4046

Epoch 26/32

958/958 - 7s - 7ms/step - ia: 0.8873 - loss: 0.0677 - mae: 0.1602 - rmse: 0.2435 - smape: 0.3875 - val_ia: 0.7080 - val_loss: 0.0615 - val_mae: 0.1626 - val_rmse: 0.2165 - val_smape: 0.3984

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:15 562ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 68%|██████▊   | 34/50 [2:58:57<1:24:22, 316.43s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

958/958 - 16s - 16ms/step - ia: 0.5891 - loss: 0.4735 - mae: 0.4428 - rmse: 0.6285 - smape: 0.9582 - val_ia: 0.6236 - val_loss: 0.1452 - val_mae: 0.2354 - val_rmse: 0.3139 - val_smape: 0.5383

Epoch 2/64

958/958 - 10s - 10ms/step - ia: 0.8507 - loss: 0.1230 - mae: 0.2095 - rmse: 0.3279 - smape: 0.4837 - val_ia: 0.7117 - val_loss: 0.0866 - val_mae: 0.1774 - val_rmse: 0.2472 - val_smape: 0.4416

Epoch 3/64

958/958 - 6s - 6ms/step - ia: 0.8719 - loss: 0.0917 - mae: 0.1800 - rmse: 0.2809 - smape: 0.4377 - val_ia: 0.6876 - val_loss: 0.0778 - val_mae: 0.1786 - val_rmse: 0.2448 - val_smape: 0.4434

Epoch 4/64

958/958 - 5s - 5ms/step - ia: 0.8802 - loss: 0.0813 - mae: 0.1684 - rmse: 0.2634 - smape: 0.4171 - val_ia: 0.7412 - val_loss: 0.0693 - val_mae: 0.1589 - val_rmse: 0.2219 - val_smape: 0.4152

Epoch 5/64

958/958 - 6s - 6ms/step - ia: 0.8850 - loss: 0.0762 - mae: 0.1619 - rmse: 0.2550 - smape: 0.4039 - val_ia: 0.7515 - val_loss: 0.0655 - val_mae: 0.1522 - val_rmse: 0.2151 - val_smape: 0.3977

Epoch 6/64

958/958 - 4s - 5ms/step - ia: 0.8881 - loss: 0.0727 - mae: 0.1577 - rmse: 0.2473 - smape: 0.3961 - val_ia: 0.7358 - val_loss: 0.0654 - val_mae: 0.1535 - val_rmse: 0.2204 - val_smape: 0.3922

Epoch 7/64

958/958 - 5s - 6ms/step - ia: 0.8907 - loss: 0.0705 - mae: 0.1544 - rmse: 0.2439 - smape: 0.3890 - val_ia: 0.7505 - val_loss: 0.0627 - val_mae: 0.1503 - val_rmse: 0.2108 - val_smape: 0.3997

Epoch 8/64

958/958 - 10s - 10ms/step - ia: 0.8926 - loss: 0.0689 - mae: 0.1518 - rmse: 0.2402 - smape: 0.3834 - val_ia: 0.7629 - val_loss: 0.0619 - val_mae: 0.1466 - val_rmse: 0.2079 - val_smape: 0.3885

Epoch 9/64

958/958 - 6s - 6ms/step - ia: 0.8931 - loss: 0.0680 - mae: 0.1511 - rmse: 0.2393 - smape: 0.3829 - val_ia: 0.7449 - val_loss: 0.0596 - val_mae: 0.1461 - val_rmse: 0.2059 - val_smape: 0.3808

Epoch 10/64

958/958 - 5s - 5ms/step - ia: 0.8934 - loss: 0.0673 - mae: 0.1503 - rmse: 0.2387 - smape: 0.3810 - val_ia: 0.7372 - val_loss: 0.0659 - val_mae: 0.1607 - val_rmse: 0.2203 - val_smape: 0.4229

Epoch 11/64

958/958 - 5s - 5ms/step - ia: 0.8955 - loss: 0.0663 - mae: 0.1483 - rmse: 0.2359 - smape: 0.3787 - val_ia: 0.7639 - val_loss: 0.0575 - val_mae: 0.1375 - val_rmse: 0.2018 - val_smape: 0.3608

Epoch 12/64

958/958 - 5s - 5ms/step - ia: 0.8960 - loss: 0.0660 - mae: 0.1474 - rmse: 0.2356 - smape: 0.3750 - val_ia: 0.7500 - val_loss: 0.0587 - val_mae: 0.1433 - val_rmse: 0.2047 - val_smape: 0.3708

Epoch 13/64

958/958 - 5s - 5ms/step - ia: 0.8960 - loss: 0.0656 - mae: 0.1474 - rmse: 0.2352 - smape: 0.3761 - val_ia: 0.7616 - val_loss: 0.0578 - val_mae: 0.1393 - val_rmse: 0.2035 - val_smape: 0.3663

Epoch 14/64

958/958 - 5s - 6ms/step - ia: 0.8956 - loss: 0.0655 - mae: 0.1473 - rmse: 0.2343 - smape: 0.3759 - val_ia: 0.7526 - val_loss: 0.0576 - val_mae: 0.1414 - val_rmse: 0.2037 - val_smape: 0.3692

Epoch 15/64

958/958 - 5s - 5ms/step - ia: 0.8963 - loss: 0.0652 - mae: 0.1473 - rmse: 0.2342 - smape: 0.3750 - val_ia: 0.7701 - val_loss: 0.0570 - val_mae: 0.1350 - val_rmse: 0.2005 - val_smape: 0.3553

Epoch 16/64

958/958 - 5s - 5ms/step - ia: 0.8965 - loss: 0.0646 - mae: 0.1464 - rmse: 0.2324 - smape: 0.3737 - val_ia: 0.7648 - val_loss: 0.0565 - val_mae: 0.1368 - val_rmse: 0.1998 - val_smape: 0.3616

Epoch 17/64

958/958 - 3s - 3ms/step - ia: 0.8969 - loss: 0.0645 - mae: 0.1460 - rmse: 0.2328 - smape: 0.3736 - val_ia: 0.7760 - val_loss: 0.0562 - val_mae: 0.1336 - val_rmse: 0.1976 - val_smape: 0.3555

Epoch 18/64

958/958 - 3s - 3ms/step - ia: 0.8965 - loss: 0.0645 - mae: 0.1466 - rmse: 0.2336 - smape: 0.3749 - val_ia: 0.7652 - val_loss: 0.0594 - val_mae: 0.1390 - val_rmse: 0.2052 - val_smape: 0.3610

Epoch 19/64

958/958 - 5s - 5ms/step - ia: 0.8969 - loss: 0.0642 - mae: 0.1460 - rmse: 0.2324 - smape: 0.3723 - val_ia: 0.7566 - val_loss: 0.0579 - val_mae: 0.1403 - val_rmse: 0.2036 - val_smape: 0.3681

Epoch 20/64

958/958 - 3s - 3ms/step - ia: 0.8970 - loss: 0.0640 - mae: 0.1459 - rmse: 0.2320 - smape: 0.3737 - val_ia: 0.6969 - val_loss: 0.0647 - val_mae: 0.1670 - val_rmse: 0.2260 - val_smape: 0.4332

Epoch 21/64

958/958 - 6s - 6ms/step - ia: 0.8966 - loss: 0.0639 - mae: 0.1462 - rmse: 0.2323 - smape: 0.3752 - val_ia: 0.7492 - val_loss: 0.0576 - val_mae: 0.1420 - val_rmse: 0.2047 - val_smape: 0.3711

Epoch 22/64

958/958 - 5s - 5ms/step - ia: 0.8981 - loss: 0.0638 - mae: 0.1453 - rmse: 0.2312 - smape: 0.3721 - val_ia: 0.7762 - val_loss: 0.0569 - val_mae: 0.1359 - val_rmse: 0.1985 - val_smape: 0.3617

Epoch 23/64

958/958 - 7s - 7ms/step - ia: 0.8981 - loss: 0.0636 - mae: 0.1448 - rmse: 0.2314 - smape: 0.3690 - val_ia: 0.7545 - val_loss: 0.0629 - val_mae: 0.1522 - val_rmse: 0.2112 - val_smape: 0.3970

Epoch 24/64

958/958 - 5s - 5ms/step - ia: 0.8977 - loss: 0.0636 - mae: 0.1454 - rmse: 0.2315 - smape: 0.3720 - val_ia: 0.7709 - val_loss: 0.0582 - val_mae: 0.1396 - val_rmse: 0.2010 - val_smape: 0.3705

Epoch 25/64

958/958 - 5s - 5ms/step - ia: 0.8987 - loss: 0.0632 - mae: 0.1444 - rmse: 0.2308 - smape: 0.3697 - val_ia: 0.7328 - val_loss: 0.0612 - val_mae: 0.1512 - val_rmse: 0.2147 - val_smape: 0.3984

Epoch 26/64

958/958 - 6s - 6ms/step - ia: 0.8975 - loss: 0.0634 - mae: 0.1452 - rmse: 0.2311 - smape: 0.3716 - val_ia: 0.7776 - val_loss: 0.0563 - val_mae: 0.1340 - val_rmse: 0.1969 - val_smape: 0.3576

Epoch 27/64

958/958 - 7s - 7ms/step - ia: 0.8978 - loss: 0.0632 - mae: 0.1449 - rmse: 0.2312 - smape: 0.3718 - val_ia: 0.7417 - val_loss: 0.0592 - val_mae: 0.1458 - val_rmse: 0.2094 - val_smape: 0.3838

Epoch 28/64

958/958 - 11s - 11ms/step - ia: 0.8981 - loss: 0.0627 - mae: 0.1445 - rmse: 0.2299 - smape: 0.3691 - val_ia: 0.7520 - val_loss: 0.0584 - val_mae: 0.1420 - val_rmse: 0.2063 - val_smape: 0.3767

Epoch 29/64

958/958 - 12s - 13ms/step - ia: 0.8975 - loss: 0.0630 - mae: 0.1449 - rmse: 0.2298 - smape: 0.3712 - val_ia: 0.7633 - val_loss: 0.0558 - val_mae: 0.1359 - val_rmse: 0.1982 - val_smape: 0.3580

Epoch 30/64

958/958 - 14s - 14ms/step - ia: 0.8982 - loss: 0.0626 - mae: 0.1444 - rmse: 0.2299 - smape: 0.3703 - val_ia: 0.7689 - val_loss: 0.0580 - val_mae: 0.1402 - val_rmse: 0.2016 - val_smape: 0.3732

Epoch 31/64

958/958 - 9s - 9ms/step - ia: 0.8987 - loss: 0.0625 - mae: 0.1442 - rmse: 0.2292 - smape: 0.3678 - val_ia: 0.7657 - val_loss: 0.0576 - val_mae: 0.1401 - val_rmse: 0.2006 - val_smape: 0.3732

Epoch 32/64

958/958 - 10s - 10ms/step - ia: 0.8979 - loss: 0.0623 - mae: 0.1443 - rmse: 0.2296 - smape: 0.3695 - val_ia: 0.7763 - val_loss: 0.0558 - val_mae: 0.1321 - val_rmse: 0.1966 - val_smape: 0.3527

Epoch 33/64

958/958 - 8s - 8ms/step - ia: 0.8980 - loss: 0.0625 - mae: 0.1448 - rmse: 0.2296 - smape: 0.3699 - val_ia: 0.7409 - val_loss: 0.0583 - val_mae: 0.1447 - val_rmse: 0.2070 - val_smape: 0.3787

Epoch 34/64

958/958 - 5s - 6ms/step - ia: 0.8982 - loss: 0.0623 - mae: 0.1442 - rmse: 0.2293 - smape: 0.3689 - val_ia: 0.7697 - val_loss: 0.0562 - val_mae: 0.1349 - val_rmse: 0.1993 - val_smape: 0.3578

Epoch 35/64

958/958 - 5s - 5ms/step - ia: 0.8978 - loss: 0.0625 - mae: 0.1449 - rmse: 0.2287 - smape: 0.3707 - val_ia: 0.7545 - val_loss: 0.0573 - val_mae: 0.1405 - val_rmse: 0.2023 - val_smape: 0.3650

Epoch 36/64

958/958 - 5s - 5ms/step - ia: 0.8971 - loss: 0.0627 - mae: 0.1458 - rmse: 0.2309 - smape: 0.3715 - val_ia: 0.7177 - val_loss: 0.0613 - val_mae: 0.1563 - val_rmse: 0.2167 - val_smape: 0.4000

Epoch 37/64

958/958 - 5s - 5ms/step - ia: 0.8982 - loss: 0.0622 - mae: 0.1444 - rmse: 0.2290 - smape: 0.3689 - val_ia: 0.7707 - val_loss: 0.0570 - val_mae: 0.1370 - val_rmse: 0.1996 - val_smape: 0.3612

Epoch 38/64

958/958 - 5s - 5ms/step - ia: 0.8994 - loss: 0.0618 - mae: 0.1432 - rmse: 0.2289 - smape: 0.3661 - val_ia: 0.7479 - val_loss: 0.0610 - val_mae: 0.1518 - val_rmse: 0.2113 - val_smape: 0.3998

Epoch 39/64

958/958 - 5s - 5ms/step - ia: 0.8995 - loss: 0.0617 - mae: 0.1428 - rmse: 0.2281 - smape: 0.3654 - val_ia: 0.7650 - val_loss: 0.0571 - val_mae: 0.1370 - val_rmse: 0.2012 - val_smape: 0.3603

Epoch 40/64

958/958 - 5s - 5ms/step - ia: 0.8983 - loss: 0.0618 - mae: 0.1442 - rmse: 0.2278 - smape: 0.3693 - val_ia: 0.7450 - val_loss: 0.0594 - val_mae: 0.1455 - val_rmse: 0.2081 - val_smape: 0.3791

Epoch 41/64

958/958 - 5s - 5ms/step - ia: 0.8986 - loss: 0.0618 - mae: 0.1439 - rmse: 0.2279 - smape: 0.3685 - val_ia: 0.7746 - val_loss: 0.0569 - val_mae: 0.1367 - val_rmse: 0.1988 - val_smape: 0.3667

Epoch 42/64

958/958 - 5s - 5ms/step - ia: 0.8990 - loss: 0.0616 - mae: 0.1430 - rmse: 0.2281 - smape: 0.3668 - val_ia: 0.7550 - val_loss: 0.0583 - val_mae: 0.1409 - val_rmse: 0.2060 - val_smape: 0.3732

Epoch 43/64

958/958 - 4s - 4ms/step - ia: 0.9000 - loss: 0.0612 - mae: 0.1425 - rmse: 0.2270 - smape: 0.3657 - val_ia: 0.7706 - val_loss: 0.0561 - val_mae: 0.1349 - val_rmse: 0.1988 - val_smape: 0.3559

Epoch 44/64

958/958 - 4s - 4ms/step - ia: 0.8987 - loss: 0.0614 - mae: 0.1437 - rmse: 0.2283 - smape: 0.3697 - val_ia: 0.7696 - val_loss: 0.0566 - val_mae: 0.1368 - val_rmse: 0.1978 - val_smape: 0.3617

Epoch 44: early stopping

Restoring model weights from the end of the best epoch: 29.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:01 456ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 70%|███████   | 35/50 [3:03:32<1:16:03, 304.26s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 12s - 13ms/step - ia: 0.7074 - loss: 0.3310 - mae: 0.3793 - rmse: 0.5260 - smape: 0.7691 - val_ia: 0.6548 - val_loss: 0.0935 - val_mae: 0.1971 - val_rmse: 0.2631 - val_smape: 0.4760

Epoch 2/128

958/958 - 10s - 10ms/step - ia: 0.8281 - loss: 0.1269 - mae: 0.2400 - rmse: 0.3390 - smape: 0.5530 - val_ia: 0.7293 - val_loss: 0.0726 - val_mae: 0.1603 - val_rmse: 0.2269 - val_smape: 0.4117

Epoch 3/128

958/958 - 5s - 5ms/step - ia: 0.8477 - loss: 0.1043 - mae: 0.2130 - rmse: 0.3065 - smape: 0.5057 - val_ia: 0.7447 - val_loss: 0.0654 - val_mae: 0.1508 - val_rmse: 0.2147 - val_smape: 0.3918

Epoch 4/128

958/958 - 5s - 5ms/step - ia: 0.8585 - loss: 0.0945 - mae: 0.1987 - rmse: 0.2902 - smape: 0.4756 - val_ia: 0.7348 - val_loss: 0.0643 - val_mae: 0.1531 - val_rmse: 0.2151 - val_smape: 0.3896

Epoch 5/128

958/958 - 5s - 5ms/step - ia: 0.8645 - loss: 0.0889 - mae: 0.1913 - rmse: 0.2812 - smape: 0.4570 - val_ia: 0.7447 - val_loss: 0.0610 - val_mae: 0.1458 - val_rmse: 0.2093 - val_smape: 0.3737

Epoch 6/128

958/958 - 5s - 5ms/step - ia: 0.8699 - loss: 0.0847 - mae: 0.1841 - rmse: 0.2730 - smape: 0.4418 - val_ia: 0.7636 - val_loss: 0.0595 - val_mae: 0.1400 - val_rmse: 0.2052 - val_smape: 0.3628

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.8724 - loss: 0.0837 - mae: 0.1811 - rmse: 0.2709 - smape: 0.4336 - val_ia: 0.7352 - val_loss: 0.0611 - val_mae: 0.1495 - val_rmse: 0.2117 - val_smape: 0.3791

Epoch 8/128

958/958 - 6s - 6ms/step - ia: 0.8740 - loss: 0.0810 - mae: 0.1782 - rmse: 0.2669 - smape: 0.4280 - val_ia: 0.7645 - val_loss: 0.0589 - val_mae: 0.1415 - val_rmse: 0.2046 - val_smape: 0.3719

Epoch 9/128

958/958 - 10s - 10ms/step - ia: 0.8767 - loss: 0.0792 - mae: 0.1746 - rmse: 0.2640 - smape: 0.4240 - val_ia: 0.7430 - val_loss: 0.0602 - val_mae: 0.1469 - val_rmse: 0.2100 - val_smape: 0.3806

Epoch 10/128

958/958 - 5s - 5ms/step - ia: 0.8795 - loss: 0.0770 - mae: 0.1700 - rmse: 0.2591 - smape: 0.4137 - val_ia: 0.7819 - val_loss: 0.0591 - val_mae: 0.1358 - val_rmse: 0.2043 - val_smape: 0.3541

Epoch 11/128

958/958 - 6s - 6ms/step - ia: 0.8811 - loss: 0.0753 - mae: 0.1688 - rmse: 0.2568 - smape: 0.4144 - val_ia: 0.7599 - val_loss: 0.0592 - val_mae: 0.1424 - val_rmse: 0.2035 - val_smape: 0.3653

Epoch 12/128

958/958 - 5s - 6ms/step - ia: 0.8821 - loss: 0.0753 - mae: 0.1673 - rmse: 0.2563 - smape: 0.4109 - val_ia: 0.7484 - val_loss: 0.0596 - val_mae: 0.1460 - val_rmse: 0.2052 - val_smape: 0.3742

Epoch 13/128

958/958 - 5s - 5ms/step - ia: 0.8835 - loss: 0.0733 - mae: 0.1654 - rmse: 0.2527 - smape: 0.4094 - val_ia: 0.7498 - val_loss: 0.0596 - val_mae: 0.1448 - val_rmse: 0.2047 - val_smape: 0.3672

Epoch 14/128

958/958 - 5s - 5ms/step - ia: 0.8843 - loss: 0.0728 - mae: 0.1642 - rmse: 0.2516 - smape: 0.4087 - val_ia: 0.7766 - val_loss: 0.0564 - val_mae: 0.1346 - val_rmse: 0.1979 - val_smape: 0.3552

Epoch 15/128

958/958 - 5s - 5ms/step - ia: 0.8850 - loss: 0.0722 - mae: 0.1632 - rmse: 0.2514 - smape: 0.4055 - val_ia: 0.7729 - val_loss: 0.0548 - val_mae: 0.1330 - val_rmse: 0.1965 - val_smape: 0.3568

Epoch 16/128

958/958 - 6s - 6ms/step - ia: 0.8856 - loss: 0.0711 - mae: 0.1619 - rmse: 0.2483 - smape: 0.4019 - val_ia: 0.7569 - val_loss: 0.0578 - val_mae: 0.1408 - val_rmse: 0.2026 - val_smape: 0.3709

Epoch 17/128

958/958 - 4s - 4ms/step - ia: 0.8856 - loss: 0.0723 - mae: 0.1623 - rmse: 0.2502 - smape: 0.4042 - val_ia: 0.7843 - val_loss: 0.0553 - val_mae: 0.1318 - val_rmse: 0.1964 - val_smape: 0.3546

Epoch 18/128

958/958 - 5s - 5ms/step - ia: 0.8866 - loss: 0.0716 - mae: 0.1610 - rmse: 0.2493 - smape: 0.4013 - val_ia: 0.7651 - val_loss: 0.0551 - val_mae: 0.1346 - val_rmse: 0.1984 - val_smape: 0.3622

Epoch 19/128

958/958 - 5s - 6ms/step - ia: 0.8871 - loss: 0.0709 - mae: 0.1603 - rmse: 0.2482 - smape: 0.3990 - val_ia: 0.7733 - val_loss: 0.0548 - val_mae: 0.1343 - val_rmse: 0.1963 - val_smape: 0.3650

Epoch 20/128

958/958 - 5s - 5ms/step - ia: 0.8881 - loss: 0.0689 - mae: 0.1591 - rmse: 0.2458 - smape: 0.3971 - val_ia: 0.7674 - val_loss: 0.0561 - val_mae: 0.1344 - val_rmse: 0.1994 - val_smape: 0.3594

Epoch 21/128

958/958 - 5s - 6ms/step - ia: 0.8889 - loss: 0.0684 - mae: 0.1579 - rmse: 0.2441 - smape: 0.3972 - val_ia: 0.7720 - val_loss: 0.0557 - val_mae: 0.1337 - val_rmse: 0.1999 - val_smape: 0.3591

Epoch 22/128

958/958 - 5s - 6ms/step - ia: 0.8892 - loss: 0.0683 - mae: 0.1572 - rmse: 0.2433 - smape: 0.3936 - val_ia: 0.7837 - val_loss: 0.0556 - val_mae: 0.1320 - val_rmse: 0.1960 - val_smape: 0.3520

Epoch 23/128

958/958 - 4s - 4ms/step - ia: 0.8896 - loss: 0.0681 - mae: 0.1568 - rmse: 0.2431 - smape: 0.3910 - val_ia: 0.7621 - val_loss: 0.0555 - val_mae: 0.1362 - val_rmse: 0.1991 - val_smape: 0.3619

Epoch 24/128

958/958 - 5s - 6ms/step - ia: 0.8891 - loss: 0.0688 - mae: 0.1576 - rmse: 0.2449 - smape: 0.3944 - val_ia: 0.7617 - val_loss: 0.0541 - val_mae: 0.1358 - val_rmse: 0.1969 - val_smape: 0.3596

Epoch 25/128

958/958 - 6s - 6ms/step - ia: 0.8895 - loss: 0.0683 - mae: 0.1569 - rmse: 0.2438 - smape: 0.3921 - val_ia: 0.7797 - val_loss: 0.0531 - val_mae: 0.1290 - val_rmse: 0.1929 - val_smape: 0.3483

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.8904 - loss: 0.0678 - mae: 0.1562 - rmse: 0.2422 - smape: 0.3917 - val_ia: 0.7728 - val_loss: 0.0552 - val_mae: 0.1345 - val_rmse: 0.1968 - val_smape: 0.3548

Epoch 27/128

958/958 - 5s - 5ms/step - ia: 0.8905 - loss: 0.0671 - mae: 0.1557 - rmse: 0.2417 - smape: 0.3886 - val_ia: 0.7825 - val_loss: 0.0555 - val_mae: 0.1329 - val_rmse: 0.1971 - val_smape: 0.3538

Epoch 28/128

958/958 - 4s - 4ms/step - ia: 0.8909 - loss: 0.0667 - mae: 0.1550 - rmse: 0.2410 - smape: 0.3882 - val_ia: 0.7759 - val_loss: 0.0542 - val_mae: 0.1307 - val_rmse: 0.1949 - val_smape: 0.3493

Epoch 29/128

958/958 - 3s - 3ms/step - ia: 0.8907 - loss: 0.0668 - mae: 0.1556 - rmse: 0.2414 - smape: 0.3878 - val_ia: 0.7859 - val_loss: 0.0545 - val_mae: 0.1299 - val_rmse: 0.1957 - val_smape: 0.3497

Epoch 30/128

958/958 - 3s - 3ms/step - ia: 0.8907 - loss: 0.0664 - mae: 0.1553 - rmse: 0.2407 - smape: 0.3889 - val_ia: 0.7755 - val_loss: 0.0539 - val_mae: 0.1313 - val_rmse: 0.1954 - val_smape: 0.3522

Epoch 31/128

958/958 - 2s - 2ms/step - ia: 0.8921 - loss: 0.0653 - mae: 0.1535 - rmse: 0.2388 - smape: 0.3847 - val_ia: 0.7762 - val_loss: 0.0539 - val_mae: 0.1312 - val_rmse: 0.1949 - val_smape: 0.3508

Epoch 32/128

958/958 - 3s - 3ms/step - ia: 0.8915 - loss: 0.0655 - mae: 0.1537 - rmse: 0.2397 - smape: 0.3859 - val_ia: 0.7763 - val_loss: 0.0566 - val_mae: 0.1329 - val_rmse: 0.1986 - val_smape: 0.3521

Epoch 33/128

958/958 - 3s - 3ms/step - ia: 0.8914 - loss: 0.0652 - mae: 0.1543 - rmse: 0.2390 - smape: 0.3852 - val_ia: 0.7853 - val_loss: 0.0533 - val_mae: 0.1283 - val_rmse: 0.1940 - val_smape: 0.3457

Epoch 34/128

958/958 - 3s - 3ms/step - ia: 0.8920 - loss: 0.0655 - mae: 0.1536 - rmse: 0.2393 - smape: 0.3827 - val_ia: 0.7918 - val_loss: 0.0531 - val_mae: 0.1271 - val_rmse: 0.1927 - val_smape: 0.3451

Epoch 35/128

958/958 - 3s - 3ms/step - ia: 0.8922 - loss: 0.0652 - mae: 0.1531 - rmse: 0.2389 - smape: 0.3857 - val_ia: 0.7744 - val_loss: 0.0547 - val_mae: 0.1335 - val_rmse: 0.1957 - val_smape: 0.3504

Epoch 36/128

958/958 - 3s - 3ms/step - ia: 0.8928 - loss: 0.0645 - mae: 0.1522 - rmse: 0.2370 - smape: 0.3827 - val_ia: 0.7900 - val_loss: 0.0557 - val_mae: 0.1294 - val_rmse: 0.1964 - val_smape: 0.3456

Epoch 37/128

958/958 - 4s - 4ms/step - ia: 0.8927 - loss: 0.0639 - mae: 0.1521 - rmse: 0.2361 - smape: 0.3828 - val_ia: 0.7437 - val_loss: 0.0641 - val_mae: 0.1533 - val_rmse: 0.2116 - val_smape: 0.3695

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.8927 - loss: 0.0645 - mae: 0.1524 - rmse: 0.2378 - smape: 0.3822 - val_ia: 0.7866 - val_loss: 0.0545 - val_mae: 0.1289 - val_rmse: 0.1942 - val_smape: 0.3454

Epoch 39/128

958/958 - 4s - 5ms/step - ia: 0.8927 - loss: 0.0645 - mae: 0.1523 - rmse: 0.2382 - smape: 0.3829 - val_ia: 0.7654 - val_loss: 0.0549 - val_mae: 0.1353 - val_rmse: 0.1981 - val_smape: 0.3532

Epoch 40/128

958/958 - 5s - 5ms/step - ia: 0.8937 - loss: 0.0638 - mae: 0.1515 - rmse: 0.2359 - smape: 0.3782 - val_ia: 0.7849 - val_loss: 0.0534 - val_mae: 0.1291 - val_rmse: 0.1928 - val_smape: 0.3492

Epoch 41/128

958/958 - 6s - 6ms/step - ia: 0.8929 - loss: 0.0634 - mae: 0.1518 - rmse: 0.2360 - smape: 0.3801 - val_ia: 0.7872 - val_loss: 0.0570 - val_mae: 0.1326 - val_rmse: 0.1996 - val_smape: 0.3463

Epoch 42/128

958/958 - 5s - 6ms/step - ia: 0.8939 - loss: 0.0634 - mae: 0.1513 - rmse: 0.2356 - smape: 0.3779 - val_ia: 0.7682 - val_loss: 0.0536 - val_mae: 0.1340 - val_rmse: 0.1954 - val_smape: 0.3547

Epoch 43/128

958/958 - 5s - 5ms/step - ia: 0.8937 - loss: 0.0628 - mae: 0.1506 - rmse: 0.2339 - smape: 0.3782 - val_ia: 0.7879 - val_loss: 0.0561 - val_mae: 0.1323 - val_rmse: 0.1979 - val_smape: 0.3457

Epoch 44/128

958/958 - 4s - 5ms/step - ia: 0.8940 - loss: 0.0631 - mae: 0.1509 - rmse: 0.2345 - smape: 0.3758 - val_ia: 0.7792 - val_loss: 0.0553 - val_mae: 0.1319 - val_rmse: 0.1950 - val_smape: 0.3501

Epoch 45/128

958/958 - 6s - 6ms/step - ia: 0.8942 - loss: 0.0626 - mae: 0.1504 - rmse: 0.2338 - smape: 0.3759 - val_ia: 0.7836 - val_loss: 0.0532 - val_mae: 0.1305 - val_rmse: 0.1929 - val_smape: 0.3489

Epoch 46/128

958/958 - 5s - 5ms/step - ia: 0.8933 - loss: 0.0642 - mae: 0.1517 - rmse: 0.2368 - smape: 0.3784 - val_ia: 0.7705 - val_loss: 0.0535 - val_mae: 0.1332 - val_rmse: 0.1951 - val_smape: 0.3492

Epoch 47/128

958/958 - 6s - 6ms/step - ia: 0.8946 - loss: 0.0629 - mae: 0.1501 - rmse: 0.2341 - smape: 0.3765 - val_ia: 0.7688 - val_loss: 0.0538 - val_mae: 0.1348 - val_rmse: 0.1960 - val_smape: 0.3587

Epoch 48/128

958/958 - 5s - 5ms/step - ia: 0.8938 - loss: 0.0633 - mae: 0.1507 - rmse: 0.2348 - smape: 0.3766 - val_ia: 0.7683 - val_loss: 0.0541 - val_mae: 0.1340 - val_rmse: 0.1957 - val_smape: 0.3531

Epoch 49/128

958/958 - 5s - 5ms/step - ia: 0.8945 - loss: 0.0628 - mae: 0.1500 - rmse: 0.2333 - smape: 0.3754 - val_ia: 0.7604 - val_loss: 0.0559 - val_mae: 0.1379 - val_rmse: 0.2016 - val_smape: 0.3678

Epoch 49: early stopping

Restoring model weights from the end of the best epoch: 34.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 41s 308ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 72%|███████▏  | 36/50 [3:07:41<1:07:06, 287.63s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

120/120 - 5s - 38ms/step - ia: 0.7109 - loss: 0.3696 - mae: 0.4171 - rmse: 0.5749 - smape: 0.8134 - val_ia: 0.7986 - val_loss: 0.0986 - val_mae: 0.2120 - val_rmse: 0.3006 - val_smape: 0.5218

Epoch 2/256

120/120 - 1s - 6ms/step - ia: 0.8064 - loss: 0.1630 - mae: 0.2725 - rmse: 0.3994 - smape: 0.5995 - val_ia: 0.8274 - val_loss: 0.0795 - val_mae: 0.1855 - val_rmse: 0.2681 - val_smape: 0.4627

Epoch 3/256

120/120 - 0s - 3ms/step - ia: 0.8254 - loss: 0.1401 - mae: 0.2473 - rmse: 0.3710 - smape: 0.5405 - val_ia: 0.8337 - val_loss: 0.0752 - val_mae: 0.1809 - val_rmse: 0.2592 - val_smape: 0.4386

Epoch 4/256

120/120 - 1s - 6ms/step - ia: 0.8330 - loss: 0.1300 - mae: 0.2375 - rmse: 0.3570 - smape: 0.5219 - val_ia: 0.8465 - val_loss: 0.0743 - val_mae: 0.1712 - val_rmse: 0.2549 - val_smape: 0.4227

Epoch 5/256

120/120 - 0s - 4ms/step - ia: 0.8380 - loss: 0.1247 - mae: 0.2314 - rmse: 0.3496 - smape: 0.5033 - val_ia: 0.8472 - val_loss: 0.0684 - val_mae: 0.1678 - val_rmse: 0.2472 - val_smape: 0.4170

Epoch 6/256

120/120 - 1s - 5ms/step - ia: 0.8429 - loss: 0.1218 - mae: 0.2252 - rmse: 0.3452 - smape: 0.4898 - val_ia: 0.8606 - val_loss: 0.0617 - val_mae: 0.1514 - val_rmse: 0.2341 - val_smape: 0.3886

Epoch 7/256

120/120 - 0s - 4ms/step - ia: 0.8446 - loss: 0.1177 - mae: 0.2227 - rmse: 0.3393 - smape: 0.4870 - val_ia: 0.8555 - val_loss: 0.0664 - val_mae: 0.1602 - val_rmse: 0.2414 - val_smape: 0.3978

Epoch 8/256

120/120 - 0s - 4ms/step - ia: 0.8459 - loss: 0.1172 - mae: 0.2207 - rmse: 0.3396 - smape: 0.4791 - val_ia: 0.8410 - val_loss: 0.0782 - val_mae: 0.1772 - val_rmse: 0.2614 - val_smape: 0.4374

Epoch 9/256

120/120 - 1s - 4ms/step - ia: 0.8441 - loss: 0.1218 - mae: 0.2232 - rmse: 0.3445 - smape: 0.4794 - val_ia: 0.8463 - val_loss: 0.0632 - val_mae: 0.1603 - val_rmse: 0.2391 - val_smape: 0.4046

Epoch 10/256

120/120 - 1s - 6ms/step - ia: 0.8475 - loss: 0.1163 - mae: 0.2188 - rmse: 0.3380 - smape: 0.4746 - val_ia: 0.8644 - val_loss: 0.0601 - val_mae: 0.1496 - val_rmse: 0.2299 - val_smape: 0.3779

Epoch 11/256

120/120 - 1s - 5ms/step - ia: 0.8473 - loss: 0.1179 - mae: 0.2192 - rmse: 0.3393 - smape: 0.4720 - val_ia: 0.8683 - val_loss: 0.0599 - val_mae: 0.1475 - val_rmse: 0.2291 - val_smape: 0.3770

Epoch 12/256

120/120 - 1s - 5ms/step - ia: 0.8482 - loss: 0.1129 - mae: 0.2177 - rmse: 0.3335 - smape: 0.4714 - val_ia: 0.8729 - val_loss: 0.0587 - val_mae: 0.1430 - val_rmse: 0.2262 - val_smape: 0.3688

Epoch 13/256

120/120 - 0s - 4ms/step - ia: 0.8482 - loss: 0.1160 - mae: 0.2177 - rmse: 0.3374 - smape: 0.4702 - val_ia: 0.8684 - val_loss: 0.0592 - val_mae: 0.1452 - val_rmse: 0.2286 - val_smape: 0.3787

Epoch 14/256

120/120 - 0s - 4ms/step - ia: 0.8485 - loss: 0.1166 - mae: 0.2174 - rmse: 0.3373 - smape: 0.4685 - val_ia: 0.8689 - val_loss: 0.0637 - val_mae: 0.1496 - val_rmse: 0.2334 - val_smape: 0.3730

Epoch 15/256

120/120 - 1s - 7ms/step - ia: 0.8515 - loss: 0.1088 - mae: 0.2134 - rmse: 0.3267 - smape: 0.4637 - val_ia: 0.8579 - val_loss: 0.0738 - val_mae: 0.1647 - val_rmse: 0.2494 - val_smape: 0.3924

Epoch 16/256

120/120 - 0s - 3ms/step - ia: 0.8490 - loss: 0.1131 - mae: 0.2166 - rmse: 0.3329 - smape: 0.4687 - val_ia: 0.8609 - val_loss: 0.0608 - val_mae: 0.1497 - val_rmse: 0.2320 - val_smape: 0.3854

Epoch 17/256

120/120 - 1s - 6ms/step - ia: 0.8504 - loss: 0.1147 - mae: 0.2148 - rmse: 0.3352 - smape: 0.4631 - val_ia: 0.8595 - val_loss: 0.0581 - val_mae: 0.1468 - val_rmse: 0.2283 - val_smape: 0.3859

Epoch 18/256

120/120 - 1s - 6ms/step - ia: 0.8495 - loss: 0.1134 - mae: 0.2161 - rmse: 0.3341 - smape: 0.4685 - val_ia: 0.8728 - val_loss: 0.0600 - val_mae: 0.1439 - val_rmse: 0.2277 - val_smape: 0.3676

Epoch 19/256

120/120 - 1s - 6ms/step - ia: 0.8522 - loss: 0.1097 - mae: 0.2120 - rmse: 0.3277 - smape: 0.4605 - val_ia: 0.8552 - val_loss: 0.0724 - val_mae: 0.1633 - val_rmse: 0.2476 - val_smape: 0.3912

Epoch 20/256

120/120 - 1s - 7ms/step - ia: 0.8508 - loss: 0.1110 - mae: 0.2142 - rmse: 0.3296 - smape: 0.4638 - val_ia: 0.8578 - val_loss: 0.0599 - val_mae: 0.1499 - val_rmse: 0.2310 - val_smape: 0.3864

Epoch 21/256

120/120 - 1s - 8ms/step - ia: 0.8519 - loss: 0.1118 - mae: 0.2126 - rmse: 0.3314 - smape: 0.4614 - val_ia: 0.8589 - val_loss: 0.0619 - val_mae: 0.1531 - val_rmse: 0.2336 - val_smape: 0.3825

Epoch 22/256

120/120 - 1s - 5ms/step - ia: 0.8508 - loss: 0.1137 - mae: 0.2139 - rmse: 0.3339 - smape: 0.4614 - val_ia: 0.8721 - val_loss: 0.0605 - val_mae: 0.1449 - val_rmse: 0.2290 - val_smape: 0.3682

Epoch 23/256

120/120 - 0s - 3ms/step - ia: 0.8520 - loss: 0.1090 - mae: 0.2130 - rmse: 0.3273 - smape: 0.4612 - val_ia: 0.8726 - val_loss: 0.0591 - val_mae: 0.1453 - val_rmse: 0.2266 - val_smape: 0.3696

Epoch 24/256

120/120 - 0s - 3ms/step - ia: 0.8498 - loss: 0.1118 - mae: 0.2154 - rmse: 0.3316 - smape: 0.4648 - val_ia: 0.8790 - val_loss: 0.0584 - val_mae: 0.1400 - val_rmse: 0.2249 - val_smape: 0.3626

Epoch 25/256

120/120 - 1s - 5ms/step - ia: 0.8517 - loss: 0.1114 - mae: 0.2128 - rmse: 0.3299 - smape: 0.4602 - val_ia: 0.8643 - val_loss: 0.0613 - val_mae: 0.1501 - val_rmse: 0.2320 - val_smape: 0.3779

Epoch 26/256

120/120 - 0s - 3ms/step - ia: 0.8518 - loss: 0.1122 - mae: 0.2131 - rmse: 0.3315 - smape: 0.4606 - val_ia: 0.8636 - val_loss: 0.0609 - val_mae: 0.1497 - val_rmse: 0.2310 - val_smape: 0.3797

Epoch 27/256

120/120 - 0s - 2ms/step - ia: 0.8520 - loss: 0.1094 - mae: 0.2129 - rmse: 0.3274 - smape: 0.4629 - val_ia: 0.8669 - val_loss: 0.0620 - val_mae: 0.1489 - val_rmse: 0.2326 - val_smape: 0.3793

Epoch 28/256

120/120 - 0s - 2ms/step - ia: 0.8517 - loss: 0.1117 - mae: 0.2130 - rmse: 0.3310 - smape: 0.4592 - val_ia: 0.8640 - val_loss: 0.0621 - val_mae: 0.1518 - val_rmse: 0.2324 - val_smape: 0.3884

Epoch 29/256

120/120 - 0s - 3ms/step - ia: 0.8522 - loss: 0.1108 - mae: 0.2122 - rmse: 0.3299 - smape: 0.4585 - val_ia: 0.8649 - val_loss: 0.0605 - val_mae: 0.1490 - val_rmse: 0.2310 - val_smape: 0.3801

Epoch 30/256

120/120 - 0s - 2ms/step - ia: 0.8524 - loss: 0.1090 - mae: 0.2118 - rmse: 0.3268 - smape: 0.4613 - val_ia: 0.8671 - val_loss: 0.0615 - val_mae: 0.1490 - val_rmse: 0.2315 - val_smape: 0.3823

Epoch 31/256

120/120 - 0s - 3ms/step - ia: 0.8531 - loss: 0.1106 - mae: 0.2112 - rmse: 0.3287 - smape: 0.4560 - val_ia: 0.8809 - val_loss: 0.0562 - val_mae: 0.1360 - val_rmse: 0.2208 - val_smape: 0.3595

Epoch 32/256

120/120 - 0s - 4ms/step - ia: 0.8527 - loss: 0.1096 - mae: 0.2115 - rmse: 0.3272 - smape: 0.4579 - val_ia: 0.8618 - val_loss: 0.0612 - val_mae: 0.1513 - val_rmse: 0.2314 - val_smape: 0.3810

Epoch 33/256

120/120 - 1s - 6ms/step - ia: 0.8520 - loss: 0.1088 - mae: 0.2124 - rmse: 0.3267 - smape: 0.4603 - val_ia: 0.8741 - val_loss: 0.0558 - val_mae: 0.1393 - val_rmse: 0.2207 - val_smape: 0.3608

Epoch 34/256

120/120 - 1s - 4ms/step - ia: 0.8529 - loss: 0.1087 - mae: 0.2113 - rmse: 0.3263 - smape: 0.4568 - val_ia: 0.8629 - val_loss: 0.0622 - val_mae: 0.1541 - val_rmse: 0.2321 - val_smape: 0.3844

Epoch 35/256

120/120 - 1s - 5ms/step - ia: 0.8521 - loss: 0.1100 - mae: 0.2122 - rmse: 0.3284 - smape: 0.4590 - val_ia: 0.8572 - val_loss: 0.0606 - val_mae: 0.1534 - val_rmse: 0.2316 - val_smape: 0.3854

Epoch 36/256

120/120 - 0s - 4ms/step - ia: 0.8520 - loss: 0.1114 - mae: 0.2126 - rmse: 0.3305 - smape: 0.4600 - val_ia: 0.8634 - val_loss: 0.0584 - val_mae: 0.1480 - val_rmse: 0.2268 - val_smape: 0.3775

Epoch 37/256

120/120 - 1s - 5ms/step - ia: 0.8500 - loss: 0.1141 - mae: 0.2150 - rmse: 0.3346 - smape: 0.4640 - val_ia: 0.8633 - val_loss: 0.0635 - val_mae: 0.1531 - val_rmse: 0.2349 - val_smape: 0.3855

Epoch 38/256

120/120 - 1s - 6ms/step - ia: 0.8520 - loss: 0.1124 - mae: 0.2124 - rmse: 0.3316 - smape: 0.4566 - val_ia: 0.8667 - val_loss: 0.0579 - val_mae: 0.1455 - val_rmse: 0.2261 - val_smape: 0.3762

Epoch 39/256

120/120 - 1s - 4ms/step - ia: 0.8523 - loss: 0.1119 - mae: 0.2123 - rmse: 0.3307 - smape: 0.4587 - val_ia: 0.8769 - val_loss: 0.0569 - val_mae: 0.1373 - val_rmse: 0.2229 - val_smape: 0.3635

Epoch 40/256

120/120 - 1s - 5ms/step - ia: 0.8533 - loss: 0.1080 - mae: 0.2109 - rmse: 0.3260 - smape: 0.4576 - val_ia: 0.8686 - val_loss: 0.0664 - val_mae: 0.1516 - val_rmse: 0.2379 - val_smape: 0.3821

Epoch 41/256

120/120 - 1s - 7ms/step - ia: 0.8505 - loss: 0.1142 - mae: 0.2145 - rmse: 0.3343 - smape: 0.4629 - val_ia: 0.8613 - val_loss: 0.0653 - val_mae: 0.1563 - val_rmse: 0.2374 - val_smape: 0.3842

Epoch 42/256

120/120 - 1s - 7ms/step - ia: 0.8510 - loss: 0.1119 - mae: 0.2137 - rmse: 0.3305 - smape: 0.4618 - val_ia: 0.8741 - val_loss: 0.0582 - val_mae: 0.1414 - val_rmse: 0.2253 - val_smape: 0.3650

Epoch 43/256

120/120 - 1s - 11ms/step - ia: 0.8527 - loss: 0.1113 - mae: 0.2117 - rmse: 0.3301 - smape: 0.4575 - val_ia: 0.8730 - val_loss: 0.0603 - val_mae: 0.1436 - val_rmse: 0.2280 - val_smape: 0.3650

Epoch 44/256

120/120 - 2s - 14ms/step - ia: 0.8532 - loss: 0.1085 - mae: 0.2108 - rmse: 0.3261 - smape: 0.4573 - val_ia: 0.8807 - val_loss: 0.0554 - val_mae: 0.1353 - val_rmse: 0.2196 - val_smape: 0.3554

Epoch 45/256

120/120 - 1s - 10ms/step - ia: 0.8537 - loss: 0.1092 - mae: 0.2103 - rmse: 0.3268 - smape: 0.4567 - val_ia: 0.8664 - val_loss: 0.0639 - val_mae: 0.1522 - val_rmse: 0.2339 - val_smape: 0.3747

Epoch 46/256

120/120 - 1s - 8ms/step - ia: 0.8519 - loss: 0.1112 - mae: 0.2126 - rmse: 0.3310 - smape: 0.4597 - val_ia: 0.8792 - val_loss: 0.0561 - val_mae: 0.1369 - val_rmse: 0.2206 - val_smape: 0.3594

Epoch 47/256

120/120 - 2s - 15ms/step - ia: 0.8529 - loss: 0.1134 - mae: 0.2115 - rmse: 0.3331 - smape: 0.4536 - val_ia: 0.8584 - val_loss: 0.0652 - val_mae: 0.1570 - val_rmse: 0.2374 - val_smape: 0.3837

Epoch 48/256

120/120 - 1s - 10ms/step - ia: 0.8522 - loss: 0.1105 - mae: 0.2121 - rmse: 0.3292 - smape: 0.4589 - val_ia: 0.8586 - val_loss: 0.0648 - val_mae: 0.1547 - val_rmse: 0.2375 - val_smape: 0.3891

Epoch 49/256

120/120 - 1s - 11ms/step - ia: 0.8533 - loss: 0.1100 - mae: 0.2106 - rmse: 0.3281 - smape: 0.4567 - val_ia: 0.8776 - val_loss: 0.0581 - val_mae: 0.1397 - val_rmse: 0.2238 - val_smape: 0.3603

Epoch 50/256

120/120 - 1s - 9ms/step - ia: 0.8533 - loss: 0.1086 - mae: 0.2110 - rmse: 0.3263 - smape: 0.4554 - val_ia: 0.8700 - val_loss: 0.0565 - val_mae: 0.1416 - val_rmse: 0.2228 - val_smape: 0.3729

Epoch 51/256

120/120 - 2s - 13ms/step - ia: 0.8514 - loss: 0.1124 - mae: 0.2132 - rmse: 0.3319 - smape: 0.4575 - val_ia: 0.8673 - val_loss: 0.0578 - val_mae: 0.1431 - val_rmse: 0.2253 - val_smape: 0.3709

Epoch 52/256

120/120 - 1s - 11ms/step - ia: 0.8532 - loss: 0.1084 - mae: 0.2110 - rmse: 0.3260 - smape: 0.4571 - val_ia: 0.8807 - val_loss: 0.0559 - val_mae: 0.1343 - val_rmse: 0.2199 - val_smape: 0.3549

Epoch 53/256

120/120 - 1s - 5ms/step - ia: 0.8531 - loss: 0.1086 - mae: 0.2114 - rmse: 0.3257 - smape: 0.4586 - val_ia: 0.8756 - val_loss: 0.0605 - val_mae: 0.1427 - val_rmse: 0.2281 - val_smape: 0.3669

Epoch 54/256

120/120 - 1s - 7ms/step - ia: 0.8534 - loss: 0.1070 - mae: 0.2108 - rmse: 0.3240 - smape: 0.4579 - val_ia: 0.8462 - val_loss: 0.0625 - val_mae: 0.1576 - val_rmse: 0.2377 - val_smape: 0.4076

Epoch 55/256

120/120 - 1s - 7ms/step - ia: 0.8514 - loss: 0.1116 - mae: 0.2133 - rmse: 0.3312 - smape: 0.4594 - val_ia: 0.8687 - val_loss: 0.0622 - val_mae: 0.1511 - val_rmse: 0.2311 - val_smape: 0.3743

Epoch 56/256

120/120 - 1s - 6ms/step - ia: 0.8532 - loss: 0.1099 - mae: 0.2108 - rmse: 0.3278 - smape: 0.4539 - val_ia: 0.8732 - val_loss: 0.0587 - val_mae: 0.1411 - val_rmse: 0.2261 - val_smape: 0.3695

Epoch 57/256

120/120 - 1s - 6ms/step - ia: 0.8530 - loss: 0.1096 - mae: 0.2106 - rmse: 0.3279 - smape: 0.4557 - val_ia: 0.8787 - val_loss: 0.0567 - val_mae: 0.1370 - val_rmse: 0.2219 - val_smape: 0.3580

Epoch 58/256

120/120 - 2s - 14ms/step - ia: 0.8541 - loss: 0.1084 - mae: 0.2099 - rmse: 0.3255 - smape: 0.4541 - val_ia: 0.8768 - val_loss: 0.0561 - val_mae: 0.1370 - val_rmse: 0.2210 - val_smape: 0.3621

Epoch 59/256

120/120 - 1s - 5ms/step - ia: 0.8521 - loss: 0.1108 - mae: 0.2121 - rmse: 0.3296 - smape: 0.4576 - val_ia: 0.8714 - val_loss: 0.0566 - val_mae: 0.1407 - val_rmse: 0.2232 - val_smape: 0.3718

Epoch 59: early stopping

Restoring model weights from the end of the best epoch: 44.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 32s 242ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 74%|███████▍  | 37/50 [3:08:32<46:55, 216.57s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

958/958 - 11s - 12ms/step - ia: 0.5242 - loss: 0.9169 - mae: 0.7342 - rmse: 0.9378 - smape: 1.0984 - val_ia: 0.3988 - val_loss: 0.4407 - val_mae: 0.4834 - val_rmse: 0.6019 - val_smape: 0.8801

Epoch 2/8

958/958 - 4s - 4ms/step - ia: 0.6060 - loss: 0.5979 - mae: 0.5859 - rmse: 0.7608 - smape: 0.9701 - val_ia: 0.4803 - val_loss: 0.2943 - val_mae: 0.3772 - val_rmse: 0.4771 - val_smape: 0.7479

Epoch 3/8

958/958 - 4s - 4ms/step - ia: 0.6423 - loss: 0.4918 - mae: 0.5267 - rmse: 0.6881 - smape: 0.9153 - val_ia: 0.5390 - val_loss: 0.2203 - val_mae: 0.3168 - val_rmse: 0.4073 - val_smape: 0.6552

Epoch 4/8

958/958 - 5s - 6ms/step - ia: 0.6712 - loss: 0.4155 - mae: 0.4815 - rmse: 0.6323 - smape: 0.8624 - val_ia: 0.5778 - val_loss: 0.1846 - val_mae: 0.2850 - val_rmse: 0.3710 - val_smape: 0.6019

Epoch 5/8

958/958 - 7s - 7ms/step - ia: 0.6904 - loss: 0.3723 - mae: 0.4543 - rmse: 0.5986 - smape: 0.8271 - val_ia: 0.6017 - val_loss: 0.1632 - val_mae: 0.2647 - val_rmse: 0.3475 - val_smape: 0.5695

Epoch 6/8

958/958 - 5s - 6ms/step - ia: 0.7008 - loss: 0.3444 - mae: 0.4369 - rmse: 0.5746 - smape: 0.8093 - val_ia: 0.6208 - val_loss: 0.1487 - val_mae: 0.2504 - val_rmse: 0.3317 - val_smape: 0.5439

Epoch 7/8

958/958 - 4s - 5ms/step - ia: 0.7150 - loss: 0.3166 - mae: 0.4168 - rmse: 0.5505 - smape: 0.7849 - val_ia: 0.6355 - val_loss: 0.1382 - val_mae: 0.2400 - val_rmse: 0.3198 - val_smape: 0.5279

Epoch 8/8

958/958 - 4s - 4ms/step - ia: 0.7207 - loss: 0.3001 - mae: 0.4067 - rmse: 0.5366 - smape: 0.7703 - val_ia: 0.6476 - val_loss: 0.1295 - val_mae: 0.2302 - val_rmse: 0.3079 - val_smape: 0.5139

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 42s 317ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 76%|███████▌  | 38/50 [3:09:19<33:09, 165.76s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 10s - 20ms/step - ia: 0.3664 - loss: 1.2907 - mae: 0.9752 - rmse: 1.1241 - smape: 1.4689 - val_ia: 0.3453 - val_loss: 0.7529 - val_mae: 0.7515 - val_rmse: 0.8461 - val_smape: 1.4493

Epoch 2/128

479/479 - 2s - 5ms/step - ia: 0.5406 - loss: 0.6122 - mae: 0.6221 - rmse: 0.7749 - smape: 1.1685 - val_ia: 0.4724 - val_loss: 0.3805 - val_mae: 0.4697 - val_rmse: 0.5766 - val_smape: 0.9974

Epoch 3/128

479/479 - 2s - 5ms/step - ia: 0.6621 - loss: 0.4052 - mae: 0.4595 - rmse: 0.6283 - smape: 0.9071 - val_ia: 0.5773 - val_loss: 0.2734 - val_mae: 0.3525 - val_rmse: 0.4622 - val_smape: 0.7592

Epoch 4/128

479/479 - 3s - 6ms/step - ia: 0.7047 - loss: 0.3420 - mae: 0.4092 - rmse: 0.5754 - smape: 0.8085 - val_ia: 0.6273 - val_loss: 0.2335 - val_mae: 0.3122 - val_rmse: 0.4170 - val_smape: 0.6750

Epoch 5/128

479/479 - 2s - 5ms/step - ia: 0.7217 - loss: 0.3106 - mae: 0.3889 - rmse: 0.5483 - smape: 0.7709 - val_ia: 0.6542 - val_loss: 0.2089 - val_mae: 0.2913 - val_rmse: 0.3922 - val_smape: 0.6355

Epoch 6/128

479/479 - 2s - 5ms/step - ia: 0.7343 - loss: 0.2879 - mae: 0.3744 - rmse: 0.5281 - smape: 0.7502 - val_ia: 0.6737 - val_loss: 0.1899 - val_mae: 0.2751 - val_rmse: 0.3730 - val_smape: 0.6052

Epoch 7/128

479/479 - 2s - 5ms/step - ia: 0.7436 - loss: 0.2700 - mae: 0.3628 - rmse: 0.5104 - smape: 0.7335 - val_ia: 0.6895 - val_loss: 0.1744 - val_mae: 0.2616 - val_rmse: 0.3570 - val_smape: 0.5816

Epoch 8/128

479/479 - 3s - 6ms/step - ia: 0.7528 - loss: 0.2546 - mae: 0.3522 - rmse: 0.4961 - smape: 0.7157 - val_ia: 0.7030 - val_loss: 0.1617 - val_mae: 0.2500 - val_rmse: 0.3436 - val_smape: 0.5621

Epoch 9/128

479/479 - 2s - 5ms/step - ia: 0.7599 - loss: 0.2424 - mae: 0.3427 - rmse: 0.4837 - smape: 0.6996 - val_ia: 0.7141 - val_loss: 0.1512 - val_mae: 0.2403 - val_rmse: 0.3313 - val_smape: 0.5440

Epoch 10/128

479/479 - 2s - 5ms/step - ia: 0.7657 - loss: 0.2317 - mae: 0.3347 - rmse: 0.4718 - smape: 0.6880 - val_ia: 0.7276 - val_loss: 0.1415 - val_mae: 0.2304 - val_rmse: 0.3212 - val_smape: 0.5268

Epoch 11/128

479/479 - 2s - 3ms/step - ia: 0.7733 - loss: 0.2193 - mae: 0.3260 - rmse: 0.4589 - smape: 0.6751 - val_ia: 0.7375 - val_loss: 0.1334 - val_mae: 0.2222 - val_rmse: 0.3123 - val_smape: 0.5125

Epoch 12/128

479/479 - 2s - 5ms/step - ia: 0.7779 - loss: 0.2133 - mae: 0.3200 - rmse: 0.4526 - smape: 0.6645 - val_ia: 0.7446 - val_loss: 0.1266 - val_mae: 0.2158 - val_rmse: 0.3040 - val_smape: 0.5001

Epoch 13/128

479/479 - 3s - 5ms/step - ia: 0.7815 - loss: 0.2041 - mae: 0.3154 - rmse: 0.4433 - smape: 0.6563 - val_ia: 0.7523 - val_loss: 0.1211 - val_mae: 0.2094 - val_rmse: 0.2969 - val_smape: 0.4887

Epoch 14/128

479/479 - 2s - 5ms/step - ia: 0.7858 - loss: 0.1978 - mae: 0.3095 - rmse: 0.4354 - smape: 0.6509 - val_ia: 0.7598 - val_loss: 0.1161 - val_mae: 0.2036 - val_rmse: 0.2907 - val_smape: 0.4776

Epoch 15/128

479/479 - 2s - 4ms/step - ia: 0.7897 - loss: 0.1941 - mae: 0.3047 - rmse: 0.4305 - smape: 0.6392 - val_ia: 0.7656 - val_loss: 0.1114 - val_mae: 0.1982 - val_rmse: 0.2842 - val_smape: 0.4669

Epoch 16/128

479/479 - 2s - 5ms/step - ia: 0.7932 - loss: 0.1859 - mae: 0.2992 - rmse: 0.4222 - smape: 0.6325 - val_ia: 0.7702 - val_loss: 0.1080 - val_mae: 0.1943 - val_rmse: 0.2801 - val_smape: 0.4611

Epoch 17/128

479/479 - 2s - 5ms/step - ia: 0.7958 - loss: 0.1825 - mae: 0.2967 - rmse: 0.4185 - smape: 0.6296 - val_ia: 0.7750 - val_loss: 0.1049 - val_mae: 0.1904 - val_rmse: 0.2746 - val_smape: 0.4512

Epoch 18/128

479/479 - 2s - 5ms/step - ia: 0.7989 - loss: 0.1781 - mae: 0.2921 - rmse: 0.4121 - smape: 0.6214 - val_ia: 0.7792 - val_loss: 0.1019 - val_mae: 0.1868 - val_rmse: 0.2708 - val_smape: 0.4450

Epoch 19/128

479/479 - 2s - 4ms/step - ia: 0.8019 - loss: 0.1727 - mae: 0.2880 - rmse: 0.4070 - smape: 0.6154 - val_ia: 0.7845 - val_loss: 0.0993 - val_mae: 0.1831 - val_rmse: 0.2669 - val_smape: 0.4371

Epoch 20/128

479/479 - 3s - 6ms/step - ia: 0.8044 - loss: 0.1696 - mae: 0.2845 - rmse: 0.4031 - smape: 0.6085 - val_ia: 0.7862 - val_loss: 0.0970 - val_mae: 0.1807 - val_rmse: 0.2637 - val_smape: 0.4328

Epoch 21/128

479/479 - 3s - 6ms/step - ia: 0.8085 - loss: 0.1649 - mae: 0.2792 - rmse: 0.3963 - smape: 0.5991 - val_ia: 0.7909 - val_loss: 0.0948 - val_mae: 0.1776 - val_rmse: 0.2604 - val_smape: 0.4267

Epoch 22/128

479/479 - 2s - 5ms/step - ia: 0.8100 - loss: 0.1624 - mae: 0.2767 - rmse: 0.3944 - smape: 0.5969 - val_ia: 0.7931 - val_loss: 0.0929 - val_mae: 0.1751 - val_rmse: 0.2580 - val_smape: 0.4227

Epoch 23/128

479/479 - 3s - 6ms/step - ia: 0.8122 - loss: 0.1587 - mae: 0.2740 - rmse: 0.3901 - smape: 0.5907 - val_ia: 0.7970 - val_loss: 0.0912 - val_mae: 0.1727 - val_rmse: 0.2554 - val_smape: 0.4171

Epoch 24/128

479/479 - 2s - 5ms/step - ia: 0.8125 - loss: 0.1584 - mae: 0.2730 - rmse: 0.3890 - smape: 0.5883 - val_ia: 0.7990 - val_loss: 0.0898 - val_mae: 0.1708 - val_rmse: 0.2527 - val_smape: 0.4129

Epoch 25/128

479/479 - 2s - 5ms/step - ia: 0.8144 - loss: 0.1554 - mae: 0.2698 - rmse: 0.3851 - smape: 0.5828 - val_ia: 0.8018 - val_loss: 0.0885 - val_mae: 0.1688 - val_rmse: 0.2504 - val_smape: 0.4087

Epoch 26/128

479/479 - 2s - 5ms/step - ia: 0.8169 - loss: 0.1517 - mae: 0.2663 - rmse: 0.3808 - smape: 0.5767 - val_ia: 0.8044 - val_loss: 0.0872 - val_mae: 0.1670 - val_rmse: 0.2488 - val_smape: 0.4049

Epoch 27/128

479/479 - 2s - 4ms/step - ia: 0.8196 - loss: 0.1495 - mae: 0.2634 - rmse: 0.3767 - smape: 0.5693 - val_ia: 0.8055 - val_loss: 0.0860 - val_mae: 0.1654 - val_rmse: 0.2466 - val_smape: 0.4018

Epoch 28/128

479/479 - 2s - 5ms/step - ia: 0.8204 - loss: 0.1474 - mae: 0.2618 - rmse: 0.3740 - smape: 0.5749 - val_ia: 0.8070 - val_loss: 0.0848 - val_mae: 0.1638 - val_rmse: 0.2453 - val_smape: 0.3992

Epoch 29/128

479/479 - 3s - 6ms/step - ia: 0.8219 - loss: 0.1446 - mae: 0.2597 - rmse: 0.3710 - smape: 0.5687 - val_ia: 0.8093 - val_loss: 0.0839 - val_mae: 0.1624 - val_rmse: 0.2433 - val_smape: 0.3957

Epoch 30/128

479/479 - 3s - 6ms/step - ia: 0.8239 - loss: 0.1431 - mae: 0.2570 - rmse: 0.3674 - smape: 0.5622 - val_ia: 0.8097 - val_loss: 0.0833 - val_mae: 0.1617 - val_rmse: 0.2412 - val_smape: 0.3939

Epoch 31/128

479/479 - 2s - 4ms/step - ia: 0.8250 - loss: 0.1426 - mae: 0.2550 - rmse: 0.3673 - smape: 0.5574 - val_ia: 0.8102 - val_loss: 0.0821 - val_mae: 0.1607 - val_rmse: 0.2404 - val_smape: 0.3940

Epoch 32/128

479/479 - 2s - 4ms/step - ia: 0.8263 - loss: 0.1383 - mae: 0.2532 - rmse: 0.3624 - smape: 0.5556 - val_ia: 0.8130 - val_loss: 0.0812 - val_mae: 0.1589 - val_rmse: 0.2387 - val_smape: 0.3902

Epoch 33/128

479/479 - 2s - 4ms/step - ia: 0.8278 - loss: 0.1376 - mae: 0.2516 - rmse: 0.3610 - smape: 0.5529 - val_ia: 0.8134 - val_loss: 0.0803 - val_mae: 0.1579 - val_rmse: 0.2375 - val_smape: 0.3880

Epoch 34/128

479/479 - 2s - 4ms/step - ia: 0.8292 - loss: 0.1369 - mae: 0.2492 - rmse: 0.3597 - smape: 0.5468 - val_ia: 0.8143 - val_loss: 0.0795 - val_mae: 0.1572 - val_rmse: 0.2365 - val_smape: 0.3870

Epoch 35/128

479/479 - 3s - 6ms/step - ia: 0.8303 - loss: 0.1346 - mae: 0.2477 - rmse: 0.3576 - smape: 0.5457 - val_ia: 0.8165 - val_loss: 0.0787 - val_mae: 0.1557 - val_rmse: 0.2353 - val_smape: 0.3845

Epoch 36/128

479/479 - 2s - 5ms/step - ia: 0.8315 - loss: 0.1339 - mae: 0.2454 - rmse: 0.3558 - smape: 0.5429 - val_ia: 0.8180 - val_loss: 0.0783 - val_mae: 0.1547 - val_rmse: 0.2345 - val_smape: 0.3818

Epoch 37/128

479/479 - 2s - 4ms/step - ia: 0.8324 - loss: 0.1322 - mae: 0.2450 - rmse: 0.3533 - smape: 0.5428 - val_ia: 0.8192 - val_loss: 0.0776 - val_mae: 0.1538 - val_rmse: 0.2328 - val_smape: 0.3808

Epoch 38/128

479/479 - 3s - 7ms/step - ia: 0.8340 - loss: 0.1305 - mae: 0.2421 - rmse: 0.3507 - smape: 0.5344 - val_ia: 0.8179 - val_loss: 0.0769 - val_mae: 0.1540 - val_rmse: 0.2327 - val_smape: 0.3814

Epoch 39/128

479/479 - 2s - 4ms/step - ia: 0.8344 - loss: 0.1296 - mae: 0.2419 - rmse: 0.3491 - smape: 0.5370 - val_ia: 0.8201 - val_loss: 0.0767 - val_mae: 0.1526 - val_rmse: 0.2313 - val_smape: 0.3793

Epoch 40/128

479/479 - 2s - 4ms/step - ia: 0.8367 - loss: 0.1266 - mae: 0.2386 - rmse: 0.3461 - smape: 0.5315 - val_ia: 0.8214 - val_loss: 0.0761 - val_mae: 0.1516 - val_rmse: 0.2303 - val_smape: 0.3773

Epoch 41/128

479/479 - 2s - 4ms/step - ia: 0.8366 - loss: 0.1271 - mae: 0.2384 - rmse: 0.3459 - smape: 0.5325 - val_ia: 0.8211 - val_loss: 0.0756 - val_mae: 0.1512 - val_rmse: 0.2294 - val_smape: 0.3758

Epoch 42/128

479/479 - 2s - 5ms/step - ia: 0.8382 - loss: 0.1246 - mae: 0.2356 - rmse: 0.3431 - smape: 0.5269 - val_ia: 0.8230 - val_loss: 0.0749 - val_mae: 0.1503 - val_rmse: 0.2288 - val_smape: 0.3750

Epoch 43/128

479/479 - 2s - 5ms/step - ia: 0.8395 - loss: 0.1248 - mae: 0.2346 - rmse: 0.3420 - smape: 0.5234 - val_ia: 0.8221 - val_loss: 0.0748 - val_mae: 0.1501 - val_rmse: 0.2279 - val_smape: 0.3744

Epoch 44/128

479/479 - 3s - 6ms/step - ia: 0.8385 - loss: 0.1239 - mae: 0.2354 - rmse: 0.3414 - smape: 0.5252 - val_ia: 0.8248 - val_loss: 0.0741 - val_mae: 0.1488 - val_rmse: 0.2271 - val_smape: 0.3723

Epoch 45/128

479/479 - 2s - 5ms/step - ia: 0.8395 - loss: 0.1229 - mae: 0.2342 - rmse: 0.3398 - smape: 0.5243 - val_ia: 0.8259 - val_loss: 0.0735 - val_mae: 0.1480 - val_rmse: 0.2267 - val_smape: 0.3712

Epoch 46/128

479/479 - 2s - 4ms/step - ia: 0.8421 - loss: 0.1214 - mae: 0.2306 - rmse: 0.3376 - smape: 0.5156 - val_ia: 0.8264 - val_loss: 0.0731 - val_mae: 0.1474 - val_rmse: 0.2257 - val_smape: 0.3689

Epoch 47/128

479/479 - 3s - 5ms/step - ia: 0.8413 - loss: 0.1211 - mae: 0.2314 - rmse: 0.3379 - smape: 0.5182 - val_ia: 0.8252 - val_loss: 0.0732 - val_mae: 0.1480 - val_rmse: 0.2263 - val_smape: 0.3699

Epoch 48/128

479/479 - 2s - 5ms/step - ia: 0.8419 - loss: 0.1216 - mae: 0.2310 - rmse: 0.3377 - smape: 0.5172 - val_ia: 0.8272 - val_loss: 0.0724 - val_mae: 0.1465 - val_rmse: 0.2247 - val_smape: 0.3675

Epoch 49/128

479/479 - 2s - 5ms/step - ia: 0.8435 - loss: 0.1190 - mae: 0.2288 - rmse: 0.3334 - smape: 0.5094 - val_ia: 0.8253 - val_loss: 0.0724 - val_mae: 0.1471 - val_rmse: 0.2247 - val_smape: 0.3683

Epoch 50/128

479/479 - 3s - 5ms/step - ia: 0.8442 - loss: 0.1176 - mae: 0.2273 - rmse: 0.3319 - smape: 0.5097 - val_ia: 0.8273 - val_loss: 0.0717 - val_mae: 0.1458 - val_rmse: 0.2234 - val_smape: 0.3660

Epoch 51/128

479/479 - 3s - 6ms/step - ia: 0.8451 - loss: 0.1163 - mae: 0.2261 - rmse: 0.3299 - smape: 0.5084 - val_ia: 0.8279 - val_loss: 0.0713 - val_mae: 0.1455 - val_rmse: 0.2231 - val_smape: 0.3663

Epoch 52/128

479/479 - 3s - 7ms/step - ia: 0.8443 - loss: 0.1183 - mae: 0.2270 - rmse: 0.3333 - smape: 0.5109 - val_ia: 0.8272 - val_loss: 0.0710 - val_mae: 0.1453 - val_rmse: 0.2226 - val_smape: 0.3657

Epoch 53/128

479/479 - 5s - 10ms/step - ia: 0.8460 - loss: 0.1157 - mae: 0.2247 - rmse: 0.3287 - smape: 0.5062 - val_ia: 0.8281 - val_loss: 0.0707 - val_mae: 0.1448 - val_rmse: 0.2225 - val_smape: 0.3652

Epoch 54/128

479/479 - 2s - 4ms/step - ia: 0.8457 - loss: 0.1181 - mae: 0.2253 - rmse: 0.3324 - smape: 0.5066 - val_ia: 0.8287 - val_loss: 0.0704 - val_mae: 0.1442 - val_rmse: 0.2214 - val_smape: 0.3632

Epoch 55/128

479/479 - 2s - 4ms/step - ia: 0.8473 - loss: 0.1137 - mae: 0.2230 - rmse: 0.3270 - smape: 0.5044 - val_ia: 0.8299 - val_loss: 0.0700 - val_mae: 0.1437 - val_rmse: 0.2217 - val_smape: 0.3628

Epoch 56/128

479/479 - 3s - 6ms/step - ia: 0.8477 - loss: 0.1144 - mae: 0.2221 - rmse: 0.3269 - smape: 0.5028 - val_ia: 0.8279 - val_loss: 0.0697 - val_mae: 0.1440 - val_rmse: 0.2210 - val_smape: 0.3630

Epoch 57/128

479/479 - 2s - 5ms/step - ia: 0.8483 - loss: 0.1123 - mae: 0.2210 - rmse: 0.3255 - smape: 0.5038 - val_ia: 0.8293 - val_loss: 0.0696 - val_mae: 0.1434 - val_rmse: 0.2203 - val_smape: 0.3612

Epoch 58/128

479/479 - 2s - 5ms/step - ia: 0.8478 - loss: 0.1140 - mae: 0.2219 - rmse: 0.3260 - smape: 0.4999 - val_ia: 0.8295 - val_loss: 0.0694 - val_mae: 0.1431 - val_rmse: 0.2206 - val_smape: 0.3607

Epoch 59/128

479/479 - 3s - 6ms/step - ia: 0.8490 - loss: 0.1127 - mae: 0.2207 - rmse: 0.3241 - smape: 0.5003 - val_ia: 0.8287 - val_loss: 0.0690 - val_mae: 0.1430 - val_rmse: 0.2197 - val_smape: 0.3604

Epoch 60/128

479/479 - 4s - 9ms/step - ia: 0.8504 - loss: 0.1094 - mae: 0.2180 - rmse: 0.3204 - smape: 0.5000 - val_ia: 0.8296 - val_loss: 0.0686 - val_mae: 0.1424 - val_rmse: 0.2189 - val_smape: 0.3594

Epoch 61/128

479/479 - 2s - 4ms/step - ia: 0.8489 - loss: 0.1122 - mae: 0.2202 - rmse: 0.3239 - smape: 0.4970 - val_ia: 0.8296 - val_loss: 0.0684 - val_mae: 0.1422 - val_rmse: 0.2192 - val_smape: 0.3591

Epoch 62/128

479/479 - 2s - 4ms/step - ia: 0.8513 - loss: 0.1093 - mae: 0.2171 - rmse: 0.3192 - smape: 0.4928 - val_ia: 0.8308 - val_loss: 0.0680 - val_mae: 0.1416 - val_rmse: 0.2184 - val_smape: 0.3580

Epoch 63/128

479/479 - 2s - 4ms/step - ia: 0.8503 - loss: 0.1104 - mae: 0.2175 - rmse: 0.3208 - smape: 0.4943 - val_ia: 0.8285 - val_loss: 0.0682 - val_mae: 0.1424 - val_rmse: 0.2189 - val_smape: 0.3596

Epoch 64/128

479/479 - 3s - 6ms/step - ia: 0.8511 - loss: 0.1092 - mae: 0.2164 - rmse: 0.3194 - smape: 0.4967 - val_ia: 0.8310 - val_loss: 0.0677 - val_mae: 0.1412 - val_rmse: 0.2183 - val_smape: 0.3577

Epoch 65/128

479/479 - 3s - 6ms/step - ia: 0.8518 - loss: 0.1095 - mae: 0.2160 - rmse: 0.3191 - smape: 0.4944 - val_ia: 0.8306 - val_loss: 0.0673 - val_mae: 0.1410 - val_rmse: 0.2174 - val_smape: 0.3576

Epoch 66/128

479/479 - 2s - 5ms/step - ia: 0.8531 - loss: 0.1075 - mae: 0.2137 - rmse: 0.3169 - smape: 0.4915 - val_ia: 0.8324 - val_loss: 0.0670 - val_mae: 0.1403 - val_rmse: 0.2174 - val_smape: 0.3562

Epoch 67/128

479/479 - 2s - 5ms/step - ia: 0.8535 - loss: 0.1072 - mae: 0.2136 - rmse: 0.3158 - smape: 0.4902 - val_ia: 0.8321 - val_loss: 0.0667 - val_mae: 0.1402 - val_rmse: 0.2167 - val_smape: 0.3568

Epoch 68/128

479/479 - 2s - 5ms/step - ia: 0.8544 - loss: 0.1065 - mae: 0.2123 - rmse: 0.3154 - smape: 0.4853 - val_ia: 0.8306 - val_loss: 0.0666 - val_mae: 0.1404 - val_rmse: 0.2165 - val_smape: 0.3568

Epoch 69/128

479/479 - 2s - 5ms/step - ia: 0.8535 - loss: 0.1064 - mae: 0.2132 - rmse: 0.3151 - smape: 0.4891 - val_ia: 0.8314 - val_loss: 0.0666 - val_mae: 0.1403 - val_rmse: 0.2169 - val_smape: 0.3567

Epoch 70/128

479/479 - 2s - 5ms/step - ia: 0.8547 - loss: 0.1068 - mae: 0.2119 - rmse: 0.3140 - smape: 0.4864 - val_ia: 0.8312 - val_loss: 0.0662 - val_mae: 0.1401 - val_rmse: 0.2161 - val_smape: 0.3566

Epoch 71/128

479/479 - 2s - 4ms/step - ia: 0.8547 - loss: 0.1062 - mae: 0.2114 - rmse: 0.3143 - smape: 0.4847 - val_ia: 0.8319 - val_loss: 0.0660 - val_mae: 0.1396 - val_rmse: 0.2156 - val_smape: 0.3555

Epoch 72/128

479/479 - 3s - 5ms/step - ia: 0.8559 - loss: 0.1044 - mae: 0.2101 - rmse: 0.3112 - smape: 0.4842 - val_ia: 0.8305 - val_loss: 0.0658 - val_mae: 0.1402 - val_rmse: 0.2155 - val_smape: 0.3578

Epoch 73/128

479/479 - 3s - 6ms/step - ia: 0.8554 - loss: 0.1046 - mae: 0.2104 - rmse: 0.3117 - smape: 0.4839 - val_ia: 0.8306 - val_loss: 0.0656 - val_mae: 0.1398 - val_rmse: 0.2158 - val_smape: 0.3559

Epoch 74/128

479/479 - 2s - 4ms/step - ia: 0.8562 - loss: 0.1031 - mae: 0.2090 - rmse: 0.3103 - smape: 0.4829 - val_ia: 0.8309 - val_loss: 0.0654 - val_mae: 0.1394 - val_rmse: 0.2154 - val_smape: 0.3557

Epoch 75/128

479/479 - 2s - 4ms/step - ia: 0.8563 - loss: 0.1048 - mae: 0.2095 - rmse: 0.3112 - smape: 0.4819 - val_ia: 0.8299 - val_loss: 0.0654 - val_mae: 0.1397 - val_rmse: 0.2155 - val_smape: 0.3559

Epoch 76/128

479/479 - 2s - 5ms/step - ia: 0.8567 - loss: 0.1030 - mae: 0.2083 - rmse: 0.3095 - smape: 0.4811 - val_ia: 0.8326 - val_loss: 0.0650 - val_mae: 0.1387 - val_rmse: 0.2147 - val_smape: 0.3549

Epoch 77/128

479/479 - 3s - 5ms/step - ia: 0.8566 - loss: 0.1041 - mae: 0.2087 - rmse: 0.3108 - smape: 0.4820 - val_ia: 0.8299 - val_loss: 0.0653 - val_mae: 0.1398 - val_rmse: 0.2156 - val_smape: 0.3565

Epoch 78/128

479/479 - 2s - 4ms/step - ia: 0.8582 - loss: 0.1018 - mae: 0.2062 - rmse: 0.3073 - smape: 0.4778 - val_ia: 0.8315 - val_loss: 0.0647 - val_mae: 0.1386 - val_rmse: 0.2141 - val_smape: 0.3544

Epoch 79/128

479/479 - 3s - 6ms/step - ia: 0.8570 - loss: 0.1028 - mae: 0.2076 - rmse: 0.3088 - smape: 0.4832 - val_ia: 0.8295 - val_loss: 0.0647 - val_mae: 0.1394 - val_rmse: 0.2151 - val_smape: 0.3561

Epoch 80/128

479/479 - 2s - 5ms/step - ia: 0.8583 - loss: 0.1011 - mae: 0.2059 - rmse: 0.3072 - smape: 0.4767 - val_ia: 0.8318 - val_loss: 0.0644 - val_mae: 0.1384 - val_rmse: 0.2141 - val_smape: 0.3543

Epoch 81/128

479/479 - 2s - 5ms/step - ia: 0.8585 - loss: 0.1010 - mae: 0.2059 - rmse: 0.3063 - smape: 0.4772 - val_ia: 0.8312 - val_loss: 0.0642 - val_mae: 0.1386 - val_rmse: 0.2137 - val_smape: 0.3554

Epoch 82/128

479/479 - 2s - 5ms/step - ia: 0.8588 - loss: 0.1011 - mae: 0.2052 - rmse: 0.3064 - smape: 0.4746 - val_ia: 0.8314 - val_loss: 0.0642 - val_mae: 0.1383 - val_rmse: 0.2136 - val_smape: 0.3541

Epoch 83/128

479/479 - 2s - 5ms/step - ia: 0.8598 - loss: 0.0991 - mae: 0.2038 - rmse: 0.3032 - smape: 0.4735 - val_ia: 0.8333 - val_loss: 0.0639 - val_mae: 0.1375 - val_rmse: 0.2135 - val_smape: 0.3529

Epoch 84/128

479/479 - 3s - 5ms/step - ia: 0.8598 - loss: 0.0995 - mae: 0.2037 - rmse: 0.3041 - smape: 0.4740 - val_ia: 0.8331 - val_loss: 0.0637 - val_mae: 0.1374 - val_rmse: 0.2130 - val_smape: 0.3531

Epoch 85/128

479/479 - 3s - 5ms/step - ia: 0.8596 - loss: 0.1001 - mae: 0.2039 - rmse: 0.3056 - smape: 0.4712 - val_ia: 0.8319 - val_loss: 0.0636 - val_mae: 0.1378 - val_rmse: 0.2127 - val_smape: 0.3542

Epoch 86/128

479/479 - 3s - 6ms/step - ia: 0.8604 - loss: 0.0992 - mae: 0.2031 - rmse: 0.3026 - smape: 0.4736 - val_ia: 0.8312 - val_loss: 0.0635 - val_mae: 0.1379 - val_rmse: 0.2130 - val_smape: 0.3536

Epoch 87/128

479/479 - 2s - 5ms/step - ia: 0.8594 - loss: 0.1006 - mae: 0.2037 - rmse: 0.3053 - smape: 0.4743 - val_ia: 0.8318 - val_loss: 0.0633 - val_mae: 0.1376 - val_rmse: 0.2124 - val_smape: 0.3537

Epoch 88/128

479/479 - 3s - 6ms/step - ia: 0.8606 - loss: 0.0991 - mae: 0.2020 - rmse: 0.3039 - smape: 0.4706 - val_ia: 0.8300 - val_loss: 0.0633 - val_mae: 0.1383 - val_rmse: 0.2127 - val_smape: 0.3552

Epoch 89/128

479/479 - 3s - 6ms/step - ia: 0.8616 - loss: 0.0978 - mae: 0.2010 - rmse: 0.3012 - smape: 0.4692 - val_ia: 0.8307 - val_loss: 0.0632 - val_mae: 0.1379 - val_rmse: 0.2128 - val_smape: 0.3536

Epoch 90/128

479/479 - 2s - 4ms/step - ia: 0.8611 - loss: 0.0987 - mae: 0.2020 - rmse: 0.3021 - smape: 0.4721 - val_ia: 0.8301 - val_loss: 0.0631 - val_mae: 0.1380 - val_rmse: 0.2125 - val_smape: 0.3544

Epoch 91/128

479/479 - 3s - 5ms/step - ia: 0.8621 - loss: 0.0973 - mae: 0.2003 - rmse: 0.3013 - smape: 0.4706 - val_ia: 0.8317 - val_loss: 0.0628 - val_mae: 0.1372 - val_rmse: 0.2122 - val_smape: 0.3534

Epoch 92/128

479/479 - 2s - 5ms/step - ia: 0.8620 - loss: 0.0969 - mae: 0.2008 - rmse: 0.2998 - smape: 0.4711 - val_ia: 0.8297 - val_loss: 0.0627 - val_mae: 0.1378 - val_rmse: 0.2124 - val_smape: 0.3542

Epoch 93/128

479/479 - 2s - 5ms/step - ia: 0.8630 - loss: 0.0968 - mae: 0.1993 - rmse: 0.3003 - smape: 0.4663 - val_ia: 0.8292 - val_loss: 0.0625 - val_mae: 0.1380 - val_rmse: 0.2118 - val_smape: 0.3558

Epoch 94/128

479/479 - 2s - 5ms/step - ia: 0.8624 - loss: 0.0962 - mae: 0.1993 - rmse: 0.2988 - smape: 0.4677 - val_ia: 0.8319 - val_loss: 0.0623 - val_mae: 0.1368 - val_rmse: 0.2114 - val_smape: 0.3533

Epoch 95/128

479/479 - 2s - 5ms/step - ia: 0.8629 - loss: 0.0957 - mae: 0.1985 - rmse: 0.2980 - smape: 0.4663 - val_ia: 0.8297 - val_loss: 0.0623 - val_mae: 0.1377 - val_rmse: 0.2116 - val_smape: 0.3554

Epoch 96/128

479/479 - 2s - 5ms/step - ia: 0.8631 - loss: 0.0957 - mae: 0.1986 - rmse: 0.2970 - smape: 0.4680 - val_ia: 0.8325 - val_loss: 0.0621 - val_mae: 0.1366 - val_rmse: 0.2109 - val_smape: 0.3540

Epoch 97/128

479/479 - 2s - 5ms/step - ia: 0.8641 - loss: 0.0951 - mae: 0.1969 - rmse: 0.2967 - smape: 0.4628 - val_ia: 0.8298 - val_loss: 0.0621 - val_mae: 0.1375 - val_rmse: 0.2119 - val_smape: 0.3543

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3832/3832 - 19s - 5ms/step - ia: 0.8113 - loss: 0.1312 - mae: 0.2285 - rmse: 0.3080 - smape: 0.5268 - val_ia: 0.5057 - val_loss: 0.0694 - val_mae: 0.1609 - val_rmse: 0.2044 - val_smape: 0.4057

Epoch 2/128

3832/3832 - 14s - 4ms/step - ia: 0.8693 - loss: 0.0730 - mae: 0.1619 - rmse: 0.2275 - smape: 0.4004 - val_ia: 0.5478 - val_loss: 0.0581 - val_mae: 0.1387 - val_rmse: 0.1811 - val_smape: 0.3647

Epoch 3/128

3832/3832 - 25s - 7ms/step - ia: 0.8775 - loss: 0.0677 - mae: 0.1523 - rmse: 0.2175 - smape: 0.3842 - val_ia: 0.5253 - val_loss: 0.0619 - val_mae: 0.1532 - val_rmse: 0.1933 - val_smape: 0.4030

Epoch 4/128

3832/3832 - 16s - 4ms/step - ia: 0.8801 - loss: 0.0659 - mae: 0.1492 - rmse: 0.2140 - smape: 0.3793 - val_ia: 0.5427 - val_loss: 0.0554 - val_mae: 0.1382 - val_rmse: 0.1785 - val_smape: 0.3727

Epoch 5/128

3832/3832 - 15s - 4ms/step - ia: 0.8831 - loss: 0.0646 - mae: 0.1466 - rmse: 0.2108 - smape: 0.3730 - val_ia: 0.5527 - val_loss: 0.0546 - val_mae: 0.1358 - val_rmse: 0.1765 - val_smape: 0.3603

Epoch 6/128

3832/3832 - 18s - 5ms/step - ia: 0.8830 - loss: 0.0644 - mae: 0.1469 - rmse: 0.2107 - smape: 0.3702 - val_ia: 0.5506 - val_loss: 0.0609 - val_mae: 0.1412 - val_rmse: 0.1832 - val_smape: 0.3636

Epoch 7/128

3832/3832 - 17s - 4ms/step - ia: 0.8831 - loss: 0.0635 - mae: 0.1459 - rmse: 0.2101 - smape: 0.3682 - val_ia: 0.5617 - val_loss: 0.0547 - val_mae: 0.1336 - val_rmse: 0.1739 - val_smape: 0.3612

Epoch 8/128

3832/3832 - 16s - 4ms/step - ia: 0.8851 - loss: 0.0630 - mae: 0.1443 - rmse: 0.2081 - smape: 0.3661 - val_ia: 0.5305 - val_loss: 0.0742 - val_mae: 0.1611 - val_rmse: 0.2011 - val_smape: 0.3944

Epoch 9/128

3832/3832 - 12s - 3ms/step - ia: 0.8833 - loss: 0.0632 - mae: 0.1452 - rmse: 0.2088 - smape: 0.3659 - val_ia: 0.5615 - val_loss: 0.0561 - val_mae: 0.1349 - val_rmse: 0.1763 - val_smape: 0.3559

Epoch 10/128

3832/3832 - 14s - 4ms/step - ia: 0.8855 - loss: 0.0621 - mae: 0.1437 - rmse: 0.2075 - smape: 0.3632 - val_ia: 0.5674 - val_loss: 0.0553 - val_mae: 0.1342 - val_rmse: 0.1755 - val_smape: 0.3586

Epoch 11/128

3832/3832 - 18s - 5ms/step - ia: 0.8849 - loss: 0.0624 - mae: 0.1437 - rmse: 0.2070 - smape: 0.3620 - val_ia: 0.5468 - val_loss: 0.0571 - val_mae: 0.1397 - val_rmse: 0.1816 - val_smape: 0.3702

Epoch 12/128

3832/3832 - 20s - 5ms/step - ia: 0.8862 - loss: 0.0624 - mae: 0.1432 - rmse: 0.2072 - smape: 0.3603 - val_ia: 0.5627 - val_loss: 0.0540 - val_mae: 0.1331 - val_rmse: 0.1735 - val_smape: 0.3573

Epoch 13/128

3832/3832 - 18s - 5ms/step - ia: 0.8865 - loss: 0.0616 - mae: 0.1418 - rmse: 0.2055 - smape: 0.3591 - val_ia: 0.5709 - val_loss: 0.0548 - val_mae: 0.1324 - val_rmse: 0.1720 - val_smape: 0.3514

Epoch 14/128

3832/3832 - 17s - 4ms/step - ia: 0.8863 - loss: 0.0610 - mae: 0.1419 - rmse: 0.2058 - smape: 0.3621 - val_ia: 0.5545 - val_loss: 0.0551 - val_mae: 0.1357 - val_rmse: 0.1765 - val_smape: 0.3589

Epoch 15/128

3832/3832 - 15s - 4ms/step - ia: 0.8869 - loss: 0.0611 - mae: 0.1408 - rmse: 0.2044 - smape: 0.3576 - val_ia: 0.5256 - val_loss: 0.0571 - val_mae: 0.1473 - val_rmse: 0.1854 - val_smape: 0.3823

Epoch 16/128

3832/3832 - 13s - 3ms/step - ia: 0.8868 - loss: 0.0604 - mae: 0.1410 - rmse: 0.2037 - smape: 0.3607 - val_ia: 0.5583 - val_loss: 0.0544 - val_mae: 0.1344 - val_rmse: 0.1743 - val_smape: 0.3574

Epoch 17/128

3832/3832 - 15s - 4ms/step - ia: 0.8875 - loss: 0.0604 - mae: 0.1409 - rmse: 0.2036 - smape: 0.3586 - val_ia: 0.5578 - val_loss: 0.0570 - val_mae: 0.1374 - val_rmse: 0.1790 - val_smape: 0.3618

Epoch 18/128

3832/3832 - 15s - 4ms/step - ia: 0.8864 - loss: 0.0603 - mae: 0.1408 - rmse: 0.2042 - smape: 0.3570 - val_ia: 0.5569 - val_loss: 0.0602 - val_mae: 0.1431 - val_rmse: 0.1832 - val_smape: 0.3689

Epoch 19/128

3832/3832 - 22s - 6ms/step - ia: 0.8879 - loss: 0.0603 - mae: 0.1410 - rmse: 0.2040 - smape: 0.3588 - val_ia: 0.5364 - val_loss: 0.0594 - val_mae: 0.1444 - val_rmse: 0.1848 - val_smape: 0.3867

Epoch 20/128

3832/3832 - 14s - 4ms/step - ia: 0.8882 - loss: 0.0601 - mae: 0.1404 - rmse: 0.2026 - smape: 0.3582 - val_ia: 0.5784 - val_loss: 0.0543 - val_mae: 0.1304 - val_rmse: 0.1718 - val_smape: 0.3498

Epoch 21/128

3832/3832 - 23s - 6ms/step - ia: 0.8880 - loss: 0.0596 - mae: 0.1397 - rmse: 0.2026 - smape: 0.3571 - val_ia: 0.5708 - val_loss: 0.0552 - val_mae: 0.1346 - val_rmse: 0.1743 - val_smape: 0.3541

Epoch 22/128

3832/3832 - 9s - 2ms/step - ia: 0.8880 - loss: 0.0595 - mae: 0.1406 - rmse: 0.2034 - smape: 0.3565 - val_ia: 0.5565 - val_loss: 0.0553 - val_mae: 0.1362 - val_rmse: 0.1782 - val_smape: 0.3688

Epoch 23/128

3832/3832 - 13s - 3ms/step - ia: 0.8887 - loss: 0.0591 - mae: 0.1390 - rmse: 0.2013 - smape: 0.3558 - val_ia: 0.5713 - val_loss: 0.0527 - val_mae: 0.1291 - val_rmse: 0.1693 - val_smape: 0.3475

Epoch 24/128

3832/3832 - 16s - 4ms/step - ia: 0.8881 - loss: 0.0592 - mae: 0.1398 - rmse: 0.2020 - smape: 0.3560 - val_ia: 0.5817 - val_loss: 0.0530 - val_mae: 0.1286 - val_rmse: 0.1694 - val_smape: 0.3468

Epoch 25/128

3832/3832 - 14s - 4ms/step - ia: 0.8885 - loss: 0.0591 - mae: 0.1393 - rmse: 0.2018 - smape: 0.3549 - val_ia: 0.5624 - val_loss: 0.0532 - val_mae: 0.1318 - val_rmse: 0.1718 - val_smape: 0.3532

Epoch 26/128

3832/3832 - 15s - 4ms/step - ia: 0.8887 - loss: 0.0589 - mae: 0.1393 - rmse: 0.2017 - smape: 0.3562 - val_ia: 0.5635 - val_loss: 0.0567 - val_mae: 0.1356 - val_rmse: 0.1757 - val_smape: 0.3533

Epoch 27/128

3832/3832 - 15s - 4ms/step - ia: 0.8888 - loss: 0.0592 - mae: 0.1394 - rmse: 0.2015 - smape: 0.3557 - val_ia: 0.5668 - val_loss: 0.0540 - val_mae: 0.1322 - val_rmse: 0.1734 - val_smape: 0.3551

Epoch 28/128

3832/3832 - 18s - 5ms/step - ia: 0.8882 - loss: 0.0590 - mae: 0.1395 - rmse: 0.2020 - smape: 0.3559 - val_ia: 0.5751 - val_loss: 0.0538 - val_mae: 0.1321 - val_rmse: 0.1719 - val_smape: 0.3531

Epoch 29/128

3832/3832 - 14s - 4ms/step - ia: 0.8881 - loss: 0.0585 - mae: 0.1390 - rmse: 0.2018 - smape: 0.3550 - val_ia: 0.5581 - val_loss: 0.0546 - val_mae: 0.1361 - val_rmse: 0.1772 - val_smape: 0.3634

Epoch 30/128

3832/3832 - 29s - 8ms/step - ia: 0.8891 - loss: 0.0584 - mae: 0.1383 - rmse: 0.1996 - smape: 0.3536 - val_ia: 0.5733 - val_loss: 0.0538 - val_mae: 0.1312 - val_rmse: 0.1718 - val_smape: 0.3482

Epoch 31/128

3832/3832 - 41s - 11ms/step - ia: 0.8886 - loss: 0.0585 - mae: 0.1387 - rmse: 0.2011 - smape: 0.3531 - val_ia: 0.5471 - val_loss: 0.0610 - val_mae: 0.1457 - val_rmse: 0.1842 - val_smape: 0.3714

Epoch 32/128

3832/3832 - 23s - 6ms/step - ia: 0.8891 - loss: 0.0579 - mae: 0.1382 - rmse: 0.2004 - smape: 0.3539 - val_ia: 0.5791 - val_loss: 0.0554 - val_mae: 0.1302 - val_rmse: 0.1728 - val_smape: 0.3463

Epoch 33/128

3832/3832 - 23s - 6ms/step - ia: 0.8892 - loss: 0.0583 - mae: 0.1383 - rmse: 0.2000 - smape: 0.3541 - val_ia: 0.5726 - val_loss: 0.0556 - val_mae: 0.1316 - val_rmse: 0.1736 - val_smape: 0.3496

Epoch 34/128

3832/3832 - 29s - 8ms/step - ia: 0.8889 - loss: 0.0577 - mae: 0.1382 - rmse: 0.1996 - smape: 0.3536 - val_ia: 0.5654 - val_loss: 0.0629 - val_mae: 0.1396 - val_rmse: 0.1832 - val_smape: 0.3540

Epoch 35/128

3832/3832 - 21s - 5ms/step - ia: 0.8904 - loss: 0.0575 - mae: 0.1377 - rmse: 0.1994 - smape: 0.3540 - val_ia: 0.5512 - val_loss: 0.0553 - val_mae: 0.1384 - val_rmse: 0.1783 - val_smape: 0.3625

Epoch 36/128

3832/3832 - 17s - 5ms/step - ia: 0.8887 - loss: 0.0576 - mae: 0.1382 - rmse: 0.2001 - smape: 0.3550 - val_ia: 0.5748 - val_loss: 0.0532 - val_mae: 0.1311 - val_rmse: 0.1711 - val_smape: 0.3499

Epoch 37/128

3832/3832 - 22s - 6ms/step - ia: 0.8891 - loss: 0.0575 - mae: 0.1384 - rmse: 0.1999 - smape: 0.3550 - val_ia: 0.5581 - val_loss: 0.0526 - val_mae: 0.1325 - val_rmse: 0.1733 - val_smape: 0.3564

Epoch 38/128

3832/3832 - 26s - 7ms/step - ia: 0.8896 - loss: 0.0572 - mae: 0.1377 - rmse: 0.1993 - smape: 0.3532 - val_ia: 0.5614 - val_loss: 0.0526 - val_mae: 0.1320 - val_rmse: 0.1724 - val_smape: 0.3569

Epoch 39/128

3832/3832 - 30s - 8ms/step - ia: 0.8898 - loss: 0.0574 - mae: 0.1376 - rmse: 0.1993 - smape: 0.3527 - val_ia: 0.5666 - val_loss: 0.0545 - val_mae: 0.1322 - val_rmse: 0.1739 - val_smape: 0.3533

Epoch 40/128

3832/3832 - 30s - 8ms/step - ia: 0.8892 - loss: 0.0576 - mae: 0.1381 - rmse: 0.1998 - smape: 0.3538 - val_ia: 0.5745 - val_loss: 0.0549 - val_mae: 0.1330 - val_rmse: 0.1737 - val_smape: 0.3481

Epoch 41/128

3832/3832 - 39s - 10ms/step - ia: 0.8895 - loss: 0.0573 - mae: 0.1376 - rmse: 0.1990 - smape: 0.3514 - val_ia: 0.5692 - val_loss: 0.0557 - val_mae: 0.1334 - val_rmse: 0.1749 - val_smape: 0.3566

Epoch 42/128

3832/3832 - 27s - 7ms/step - ia: 0.8892 - loss: 0.0570 - mae: 0.1376 - rmse: 0.1994 - smape: 0.3522 - val_ia: 0.5732 - val_loss: 0.0535 - val_mae: 0.1307 - val_rmse: 0.1716 - val_smape: 0.3506

Epoch 43/128

3832/3832 - 29s - 7ms/step - ia: 0.8902 - loss: 0.0568 - mae: 0.1372 - rmse: 0.1985 - smape: 0.3510 - val_ia: 0.5595 - val_loss: 0.0533 - val_mae: 0.1330 - val_rmse: 0.1733 - val_smape: 0.3567

Epoch 44/128

3832/3832 - 28s - 7ms/step - ia: 0.8894 - loss: 0.0569 - mae: 0.1373 - rmse: 0.1990 - smape: 0.3510 - val_ia: 0.5657 - val_loss: 0.0541 - val_mae: 0.1341 - val_rmse: 0.1745 - val_smape: 0.3587

Epoch 45/128

3832/3832 - 28s - 7ms/step - ia: 0.8893 - loss: 0.0571 - mae: 0.1374 - rmse: 0.1987 - smape: 0.3522 - val_ia: 0.5501 - val_loss: 0.0596 - val_mae: 0.1438 - val_rmse: 0.1833 - val_smape: 0.3675

Epoch 46/128

3832/3832 - 21s - 5ms/step - ia: 0.8900 - loss: 0.0564 - mae: 0.1373 - rmse: 0.1982 - smape: 0.3527 - val_ia: 0.5623 - val_loss: 0.0546 - val_mae: 0.1341 - val_rmse: 0.1744 - val_smape: 0.3567

Epoch 47/128

3832/3832 - 20s - 5ms/step - ia: 0.8899 - loss: 0.0568 - mae: 0.1373 - rmse: 0.1991 - smape: 0.3526 - val_ia: 0.5365 - val_loss: 0.0629 - val_mae: 0.1485 - val_rmse: 0.1879 - val_smape: 0.3691

Epoch 48/128

3832/3832 - 28s - 7ms/step - ia: 0.8899 - loss: 0.0568 - mae: 0.1371 - rmse: 0.1982 - smape: 0.3530 - val_ia: 0.5704 - val_loss: 0.0537 - val_mae: 0.1309 - val_rmse: 0.1719 - val_smape: 0.3527

Epoch 49/128

3832/3832 - 22s - 6ms/step - ia: 0.8906 - loss: 0.0570 - mae: 0.1371 - rmse: 0.1991 - smape: 0.3529 - val_ia: 0.5710 - val_loss: 0.0542 - val_mae: 0.1334 - val_rmse: 0.1735 - val_smape: 0.3531

Epoch 50/128

3832/3832 - 48s - 12ms/step - ia: 0.8896 - loss: 0.0567 - mae: 0.1373 - rmse: 0.1987 - smape: 0.3517 - val_ia: 0.5722 - val_loss: 0.0547 - val_mae: 0.1308 - val_rmse: 0.1722 - val_smape: 0.3492

Epoch 51/128

3832/3832 - 25s - 7ms/step - ia: 0.8898 - loss: 0.0567 - mae: 0.1378 - rmse: 0.1994 - smape: 0.3536 - val_ia: 0.5628 - val_loss: 0.0542 - val_mae: 0.1326 - val_rmse: 0.1736 - val_smape: 0.3530

Epoch 52/128

3832/3832 - 24s - 6ms/step - ia: 0.8908 - loss: 0.0568 - mae: 0.1375 - rmse: 0.1986 - smape: 0.3530 - val_ia: 0.5761 - val_loss: 0.0539 - val_mae: 0.1305 - val_rmse: 0.1713 - val_smape: 0.3472

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:04 923ms/step
  2/136 ━━━━━━━━━━━━━━━━━━━━ 7s 54ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 80%|████████  | 40/50 [3:33:12<1:20:15, 481.59s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 10s - 82ms/step - ia: 0.3660 - loss: 2.5553 - mae: 1.2321 - rmse: 1.5963 - smape: 1.2362 - val_ia: 0.3562 - val_loss: 2.0947 - val_mae: 1.1062 - val_rmse: 1.3679 - val_smape: 1.1728

Epoch 2/32

120/120 - 1s - 10ms/step - ia: 0.3744 - loss: 2.3932 - mae: 1.1897 - rmse: 1.5442 - smape: 1.2296 - val_ia: 0.3667 - val_loss: 1.9586 - val_mae: 1.0589 - val_rmse: 1.3138 - val_smape: 1.1587

Epoch 3/32

120/120 - 1s - 12ms/step - ia: 0.3838 - loss: 2.2338 - mae: 1.1455 - rmse: 1.4920 - smape: 1.2217 - val_ia: 0.3774 - val_loss: 1.8360 - val_mae: 1.0146 - val_rmse: 1.2639 - val_smape: 1.1443

Epoch 4/32

120/120 - 1s - 7ms/step - ia: 0.3897 - loss: 2.1212 - mae: 1.1124 - rmse: 1.4537 - smape: 1.2164 - val_ia: 0.3880 - val_loss: 1.7227 - val_mae: 0.9729 - val_rmse: 1.2174 - val_smape: 1.1301

Epoch 5/32

120/120 - 1s - 6ms/step - ia: 0.3977 - loss: 1.9948 - mae: 1.0732 - rmse: 1.4096 - smape: 1.2077 - val_ia: 0.3985 - val_loss: 1.6177 - val_mae: 0.9334 - val_rmse: 1.1737 - val_smape: 1.1162

Epoch 6/32

120/120 - 1s - 6ms/step - ia: 0.4019 - loss: 1.8933 - mae: 1.0434 - rmse: 1.3736 - smape: 1.2060 - val_ia: 0.4087 - val_loss: 1.5202 - val_mae: 0.8961 - val_rmse: 1.1324 - val_smape: 1.1028

Epoch 7/32

120/120 - 1s - 7ms/step - ia: 0.4104 - loss: 1.7799 - mae: 1.0077 - rmse: 1.3315 - smape: 1.1970 - val_ia: 0.4185 - val_loss: 1.4289 - val_mae: 0.8609 - val_rmse: 1.0936 - val_smape: 1.0902

Epoch 8/32

120/120 - 1s - 7ms/step - ia: 0.4175 - loss: 1.6738 - mae: 0.9749 - rmse: 1.2919 - smape: 1.1918 - val_ia: 0.4278 - val_loss: 1.3431 - val_mae: 0.8275 - val_rmse: 1.0568 - val_smape: 1.0785

Epoch 9/32

120/120 - 1s - 6ms/step - ia: 0.4230 - loss: 1.5887 - mae: 0.9475 - rmse: 1.2580 - smape: 1.1867 - val_ia: 0.4365 - val_loss: 1.2631 - val_mae: 0.7962 - val_rmse: 1.0221 - val_smape: 1.0676

Epoch 10/32

120/120 - 1s - 10ms/step - ia: 0.4304 - loss: 1.5081 - mae: 0.9191 - rmse: 1.2261 - smape: 1.1795 - val_ia: 0.4450 - val_loss: 1.1870 - val_mae: 0.7662 - val_rmse: 0.9886 - val_smape: 1.0574

Epoch 11/32

120/120 - 1s - 8ms/step - ia: 0.4384 - loss: 1.4208 - mae: 0.8878 - rmse: 1.1895 - smape: 1.1686 - val_ia: 0.4535 - val_loss: 1.1159 - val_mae: 0.7377 - val_rmse: 0.9565 - val_smape: 1.0473

Epoch 12/32

120/120 - 1s - 7ms/step - ia: 0.4462 - loss: 1.3462 - mae: 0.8603 - rmse: 1.1576 - smape: 1.1620 - val_ia: 0.4620 - val_loss: 1.0494 - val_mae: 0.7105 - val_rmse: 0.9259 - val_smape: 1.0367

Epoch 13/32

120/120 - 1s - 12ms/step - ia: 0.4543 - loss: 1.2708 - mae: 0.8340 - rmse: 1.1251 - smape: 1.1498 - val_ia: 0.4705 - val_loss: 0.9872 - val_mae: 0.6849 - val_rmse: 0.8965 - val_smape: 1.0262

Epoch 14/32

120/120 - 1s - 6ms/step - ia: 0.4605 - loss: 1.2188 - mae: 0.8146 - rmse: 1.1015 - smape: 1.1442 - val_ia: 0.4793 - val_loss: 0.9287 - val_mae: 0.6601 - val_rmse: 0.8678 - val_smape: 1.0147

Epoch 15/32

120/120 - 1s - 8ms/step - ia: 0.4681 - loss: 1.1524 - mae: 0.7896 - rmse: 1.0704 - smape: 1.1364 - val_ia: 0.4883 - val_loss: 0.8747 - val_mae: 0.6370 - val_rmse: 0.8405 - val_smape: 1.0024

Epoch 16/32

120/120 - 1s - 12ms/step - ia: 0.4775 - loss: 1.0917 - mae: 0.7673 - rmse: 1.0424 - smape: 1.1249 - val_ia: 0.4973 - val_loss: 0.8238 - val_mae: 0.6151 - val_rmse: 0.8145 - val_smape: 0.9905

Epoch 17/32

120/120 - 2s - 19ms/step - ia: 0.4869 - loss: 1.0292 - mae: 0.7459 - rmse: 1.0123 - smape: 1.1149 - val_ia: 0.5067 - val_loss: 0.7766 - val_mae: 0.5944 - val_rmse: 0.7895 - val_smape: 0.9775

Epoch 18/32

120/120 - 2s - 18ms/step - ia: 0.4954 - loss: 0.9900 - mae: 0.7267 - rmse: 0.9922 - smape: 1.1000 - val_ia: 0.5162 - val_loss: 0.7319 - val_mae: 0.5747 - val_rmse: 0.7656 - val_smape: 0.9630

Epoch 19/32

120/120 - 2s - 19ms/step - ia: 0.5041 - loss: 0.9354 - mae: 0.7071 - rmse: 0.9641 - smape: 1.0919 - val_ia: 0.5258 - val_loss: 0.6910 - val_mae: 0.5562 - val_rmse: 0.7430 - val_smape: 0.9492

Epoch 20/32

120/120 - 1s - 12ms/step - ia: 0.5136 - loss: 0.8914 - mae: 0.6867 - rmse: 0.9413 - smape: 1.0768 - val_ia: 0.5357 - val_loss: 0.6529 - val_mae: 0.5388 - val_rmse: 0.7212 - val_smape: 0.9362

Epoch 21/32

120/120 - 3s - 24ms/step - ia: 0.5213 - loss: 0.8520 - mae: 0.6719 - rmse: 0.9200 - smape: 1.0691 - val_ia: 0.5454 - val_loss: 0.6174 - val_mae: 0.5226 - val_rmse: 0.7007 - val_smape: 0.9220

Epoch 22/32

120/120 - 2s - 14ms/step - ia: 0.5306 - loss: 0.8138 - mae: 0.6539 - rmse: 0.8991 - smape: 1.0524 - val_ia: 0.5549 - val_loss: 0.5849 - val_mae: 0.5075 - val_rmse: 0.6814 - val_smape: 0.9083

Epoch 23/32

120/120 - 1s - 9ms/step - ia: 0.5387 - loss: 0.7777 - mae: 0.6412 - rmse: 0.8796 - smape: 1.0467 - val_ia: 0.5642 - val_loss: 0.5541 - val_mae: 0.4933 - val_rmse: 0.6630 - val_smape: 0.8953

Epoch 24/32

120/120 - 2s - 13ms/step - ia: 0.5462 - loss: 0.7439 - mae: 0.6269 - rmse: 0.8603 - smape: 1.0376 - val_ia: 0.5732 - val_loss: 0.5262 - val_mae: 0.4802 - val_rmse: 0.6459 - val_smape: 0.8823

Epoch 25/32

120/120 - 2s - 15ms/step - ia: 0.5565 - loss: 0.7129 - mae: 0.6134 - rmse: 0.8418 - smape: 1.0216 - val_ia: 0.5817 - val_loss: 0.5001 - val_mae: 0.4680 - val_rmse: 0.6298 - val_smape: 0.8700

Epoch 26/32

120/120 - 3s - 24ms/step - ia: 0.5619 - loss: 0.6881 - mae: 0.6018 - rmse: 0.8266 - smape: 1.0173 - val_ia: 0.5902 - val_loss: 0.4762 - val_mae: 0.4566 - val_rmse: 0.6147 - val_smape: 0.8578

Epoch 27/32

120/120 - 3s - 23ms/step - ia: 0.5722 - loss: 0.6617 - mae: 0.5882 - rmse: 0.8107 - smape: 1.0010 - val_ia: 0.5984 - val_loss: 0.4549 - val_mae: 0.4461 - val_rmse: 0.6008 - val_smape: 0.8477

Epoch 28/32

120/120 - 3s - 24ms/step - ia: 0.5792 - loss: 0.6360 - mae: 0.5770 - rmse: 0.7952 - smape: 0.9922 - val_ia: 0.6058 - val_loss: 0.4348 - val_mae: 0.4365 - val_rmse: 0.5879 - val_smape: 0.8371

Epoch 29/32

120/120 - 3s - 22ms/step - ia: 0.5856 - loss: 0.6107 - mae: 0.5681 - rmse: 0.7793 - smape: 0.9880 - val_ia: 0.6129 - val_loss: 0.4168 - val_mae: 0.4277 - val_rmse: 0.5760 - val_smape: 0.8283

Epoch 30/32

120/120 - 3s - 26ms/step - ia: 0.5914 - loss: 0.5917 - mae: 0.5583 - rmse: 0.7670 - smape: 0.9798 - val_ia: 0.6197 - val_loss: 0.4003 - val_mae: 0.4197 - val_rmse: 0.5650 - val_smape: 0.8213

Epoch 31/32

120/120 - 2s - 17ms/step - ia: 0.5970 - loss: 0.5775 - mae: 0.5520 - rmse: 0.7578 - smape: 0.9745 - val_ia: 0.6260 - val_loss: 0.3852 - val_mae: 0.4123 - val_rmse: 0.5550 - val_smape: 0.8143

Epoch 32/32

120/120 - 3s - 22ms/step - ia: 0.6006 - loss: 0.5615 - mae: 0.5460 - rmse: 0.7476 - smape: 0.9719 - val_ia: 0.6318 - val_loss: 0.3712 - val_mae: 0.4055 - val_rmse: 0.5458 - val_smape: 0.8075

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:29 1s/step
  2/136 ━━━━━━━━━━━━━━━━━━━━ 18s 136ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 82%|████████▏ | 41/50 [3:34:20<53:39, 357.76s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

958/958 - 28s - 29ms/step - ia: 0.6448 - loss: 0.6186 - mae: 0.5509 - rmse: 0.7285 - smape: 0.9077 - val_ia: 0.7067 - val_loss: 0.0820 - val_mae: 0.1777 - val_rmse: 0.2463 - val_smape: 0.4514

Epoch 2/64

958/958 - 7s - 8ms/step - ia: 0.7701 - loss: 0.2047 - mae: 0.3252 - rmse: 0.4403 - smape: 0.6756 - val_ia: 0.7411 - val_loss: 0.0674 - val_mae: 0.1555 - val_rmse: 0.2224 - val_smape: 0.4036

Epoch 3/64

958/958 - 11s - 11ms/step - ia: 0.8154 - loss: 0.1420 - mae: 0.2605 - rmse: 0.3627 - smape: 0.5704 - val_ia: 0.7562 - val_loss: 0.0622 - val_mae: 0.1471 - val_rmse: 0.2131 - val_smape: 0.3857

Epoch 4/64

958/958 - 4s - 4ms/step - ia: 0.8382 - loss: 0.1147 - mae: 0.2271 - rmse: 0.3233 - smape: 0.5118 - val_ia: 0.7625 - val_loss: 0.0599 - val_mae: 0.1429 - val_rmse: 0.2068 - val_smape: 0.3745

Epoch 5/64

958/958 - 5s - 5ms/step - ia: 0.8513 - loss: 0.1025 - mae: 0.2097 - rmse: 0.3040 - smape: 0.4772 - val_ia: 0.7454 - val_loss: 0.0610 - val_mae: 0.1495 - val_rmse: 0.2105 - val_smape: 0.3848

Epoch 6/64

958/958 - 7s - 7ms/step - ia: 0.8580 - loss: 0.0948 - mae: 0.2001 - rmse: 0.2906 - smape: 0.4584 - val_ia: 0.7655 - val_loss: 0.0581 - val_mae: 0.1406 - val_rmse: 0.2039 - val_smape: 0.3709

Epoch 7/64

958/958 - 7s - 7ms/step - ia: 0.8639 - loss: 0.0903 - mae: 0.1919 - rmse: 0.2828 - smape: 0.4437 - val_ia: 0.7721 - val_loss: 0.0575 - val_mae: 0.1363 - val_rmse: 0.2013 - val_smape: 0.3588

Epoch 8/64

958/958 - 8s - 8ms/step - ia: 0.8667 - loss: 0.0877 - mae: 0.1875 - rmse: 0.2785 - smape: 0.4333 - val_ia: 0.7677 - val_loss: 0.0582 - val_mae: 0.1399 - val_rmse: 0.2036 - val_smape: 0.3626

Epoch 9/64

958/958 - 8s - 8ms/step - ia: 0.8689 - loss: 0.0858 - mae: 0.1845 - rmse: 0.2743 - smape: 0.4244 - val_ia: 0.7635 - val_loss: 0.0609 - val_mae: 0.1444 - val_rmse: 0.2102 - val_smape: 0.3656

Epoch 10/64

958/958 - 11s - 11ms/step - ia: 0.8706 - loss: 0.0857 - mae: 0.1832 - rmse: 0.2745 - smape: 0.4234 - val_ia: 0.7716 - val_loss: 0.0574 - val_mae: 0.1377 - val_rmse: 0.2021 - val_smape: 0.3655

Epoch 11/64

958/958 - 7s - 8ms/step - ia: 0.8712 - loss: 0.0835 - mae: 0.1813 - rmse: 0.2724 - smape: 0.4190 - val_ia: 0.7322 - val_loss: 0.0656 - val_mae: 0.1588 - val_rmse: 0.2204 - val_smape: 0.4063

Epoch 12/64

958/958 - 10s - 10ms/step - ia: 0.8726 - loss: 0.0835 - mae: 0.1794 - rmse: 0.2696 - smape: 0.4142 - val_ia: 0.7738 - val_loss: 0.0573 - val_mae: 0.1361 - val_rmse: 0.2007 - val_smape: 0.3582

Epoch 13/64

958/958 - 9s - 9ms/step - ia: 0.8730 - loss: 0.0843 - mae: 0.1794 - rmse: 0.2710 - smape: 0.4136 - val_ia: 0.7682 - val_loss: 0.0579 - val_mae: 0.1388 - val_rmse: 0.2033 - val_smape: 0.3641

Epoch 14/64

958/958 - 6s - 6ms/step - ia: 0.8749 - loss: 0.0816 - mae: 0.1771 - rmse: 0.2667 - smape: 0.4107 - val_ia: 0.7541 - val_loss: 0.0601 - val_mae: 0.1455 - val_rmse: 0.2067 - val_smape: 0.3707

Epoch 15/64

958/958 - 7s - 7ms/step - ia: 0.8722 - loss: 0.0839 - mae: 0.1800 - rmse: 0.2705 - smape: 0.4125 - val_ia: 0.7655 - val_loss: 0.0583 - val_mae: 0.1403 - val_rmse: 0.2028 - val_smape: 0.3645

Epoch 16/64

958/958 - 12s - 13ms/step - ia: 0.8756 - loss: 0.0796 - mae: 0.1759 - rmse: 0.2648 - smape: 0.4097 - val_ia: 0.7811 - val_loss: 0.0566 - val_mae: 0.1331 - val_rmse: 0.1981 - val_smape: 0.3528

Epoch 17/64

958/958 - 10s - 11ms/step - ia: 0.8743 - loss: 0.0813 - mae: 0.1772 - rmse: 0.2669 - smape: 0.4087 - val_ia: 0.7241 - val_loss: 0.0673 - val_mae: 0.1620 - val_rmse: 0.2188 - val_smape: 0.3933

Epoch 18/64

958/958 - 12s - 13ms/step - ia: 0.8757 - loss: 0.0806 - mae: 0.1756 - rmse: 0.2656 - smape: 0.4071 - val_ia: 0.7795 - val_loss: 0.0568 - val_mae: 0.1344 - val_rmse: 0.1997 - val_smape: 0.3559

Epoch 19/64

958/958 - 7s - 7ms/step - ia: 0.8761 - loss: 0.0803 - mae: 0.1751 - rmse: 0.2647 - smape: 0.4048 - val_ia: 0.7576 - val_loss: 0.0598 - val_mae: 0.1437 - val_rmse: 0.2070 - val_smape: 0.3736

Epoch 20/64

958/958 - 6s - 7ms/step - ia: 0.8772 - loss: 0.0796 - mae: 0.1742 - rmse: 0.2637 - smape: 0.4014 - val_ia: 0.7759 - val_loss: 0.0566 - val_mae: 0.1347 - val_rmse: 0.1991 - val_smape: 0.3577

Epoch 21/64

958/958 - 7s - 8ms/step - ia: 0.8767 - loss: 0.0800 - mae: 0.1743 - rmse: 0.2644 - smape: 0.4033 - val_ia: 0.7637 - val_loss: 0.0596 - val_mae: 0.1414 - val_rmse: 0.2042 - val_smape: 0.3661

Epoch 22/64

958/958 - 6s - 7ms/step - ia: 0.8767 - loss: 0.0808 - mae: 0.1742 - rmse: 0.2649 - smape: 0.4026 - val_ia: 0.7647 - val_loss: 0.0579 - val_mae: 0.1395 - val_rmse: 0.2010 - val_smape: 0.3626

Epoch 23/64

958/958 - 10s - 10ms/step - ia: 0.8759 - loss: 0.0819 - mae: 0.1754 - rmse: 0.2673 - smape: 0.4043 - val_ia: 0.7805 - val_loss: 0.0565 - val_mae: 0.1324 - val_rmse: 0.1984 - val_smape: 0.3523

Epoch 24/64

958/958 - 12s - 12ms/step - ia: 0.8767 - loss: 0.0799 - mae: 0.1746 - rmse: 0.2636 - smape: 0.4029 - val_ia: 0.7713 - val_loss: 0.0574 - val_mae: 0.1364 - val_rmse: 0.2003 - val_smape: 0.3590

Epoch 25/64

958/958 - 6s - 7ms/step - ia: 0.8763 - loss: 0.0801 - mae: 0.1750 - rmse: 0.2644 - smape: 0.4028 - val_ia: 0.7659 - val_loss: 0.0593 - val_mae: 0.1410 - val_rmse: 0.2043 - val_smape: 0.3670

Epoch 26/64

958/958 - 11s - 11ms/step - ia: 0.8779 - loss: 0.0780 - mae: 0.1728 - rmse: 0.2613 - smape: 0.4003 - val_ia: 0.7729 - val_loss: 0.0576 - val_mae: 0.1365 - val_rmse: 0.2011 - val_smape: 0.3608

Epoch 27/64

958/958 - 7s - 7ms/step - ia: 0.8770 - loss: 0.0805 - mae: 0.1739 - rmse: 0.2644 - smape: 0.4004 - val_ia: 0.7495 - val_loss: 0.0603 - val_mae: 0.1456 - val_rmse: 0.2078 - val_smape: 0.3741

Epoch 28/64

958/958 - 6s - 6ms/step - ia: 0.8775 - loss: 0.0792 - mae: 0.1731 - rmse: 0.2629 - smape: 0.4000 - val_ia: 0.7827 - val_loss: 0.0561 - val_mae: 0.1321 - val_rmse: 0.1968 - val_smape: 0.3504

Epoch 29/64

958/958 - 6s - 6ms/step - ia: 0.8777 - loss: 0.0787 - mae: 0.1730 - rmse: 0.2625 - smape: 0.4001 - val_ia: 0.7826 - val_loss: 0.0576 - val_mae: 0.1331 - val_rmse: 0.1997 - val_smape: 0.3525

Epoch 30/64

958/958 - 7s - 8ms/step - ia: 0.8767 - loss: 0.0800 - mae: 0.1738 - rmse: 0.2646 - smape: 0.4003 - val_ia: 0.7731 - val_loss: 0.0572 - val_mae: 0.1367 - val_rmse: 0.2002 - val_smape: 0.3585

Epoch 31/64

958/958 - 5s - 5ms/step - ia: 0.8769 - loss: 0.0798 - mae: 0.1738 - rmse: 0.2641 - smape: 0.4006 - val_ia: 0.7747 - val_loss: 0.0565 - val_mae: 0.1349 - val_rmse: 0.1980 - val_smape: 0.3567

Epoch 32/64

958/958 - 4s - 4ms/step - ia: 0.8774 - loss: 0.0797 - mae: 0.1732 - rmse: 0.2638 - smape: 0.3996 - val_ia: 0.7856 - val_loss: 0.0573 - val_mae: 0.1309 - val_rmse: 0.1984 - val_smape: 0.3494

Epoch 33/64

958/958 - 2336s - 2s/step - ia: 0.8777 - loss: 0.0796 - mae: 0.1733 - rmse: 0.2634 - smape: 0.3983 - val_ia: 0.7643 - val_loss: 0.0629 - val_mae: 0.1455 - val_rmse: 0.2119 - val_smape: 0.3689

Epoch 34/64

958/958 - 4s - 4ms/step - ia: 0.8772 - loss: 0.0794 - mae: 0.1736 - rmse: 0.2640 - smape: 0.3984 - val_ia: 0.7523 - val_loss: 0.0609 - val_mae: 0.1464 - val_rmse: 0.2096 - val_smape: 0.3814

Epoch 35/64

958/958 - 6s - 6ms/step - ia: 0.8768 - loss: 0.0806 - mae: 0.1742 - rmse: 0.2650 - smape: 0.4011 - val_ia: 0.7286 - val_loss: 0.0642 - val_mae: 0.1568 - val_rmse: 0.2146 - val_smape: 0.3847

Epoch 36/64

958/958 - 11s - 11ms/step - ia: 0.8768 - loss: 0.0798 - mae: 0.1737 - rmse: 0.2639 - smape: 0.3993 - val_ia: 0.7786 - val_loss: 0.0570 - val_mae: 0.1346 - val_rmse: 0.1998 - val_smape: 0.3525

Epoch 37/64

958/958 - 6s - 6ms/step - ia: 0.8779 - loss: 0.0782 - mae: 0.1720 - rmse: 0.2621 - smape: 0.3989 - val_ia: 0.7809 - val_loss: 0.0560 - val_mae: 0.1326 - val_rmse: 0.1969 - val_smape: 0.3520

Epoch 38/64

958/958 - 5s - 5ms/step - ia: 0.8765 - loss: 0.0803 - mae: 0.1742 - rmse: 0.2647 - smape: 0.4002 - val_ia: 0.7524 - val_loss: 0.0604 - val_mae: 0.1451 - val_rmse: 0.2077 - val_smape: 0.3731

Epoch 39/64

958/958 - 7s - 7ms/step - ia: 0.8774 - loss: 0.0808 - mae: 0.1733 - rmse: 0.2652 - smape: 0.3991 - val_ia: 0.7771 - val_loss: 0.0577 - val_mae: 0.1357 - val_rmse: 0.2011 - val_smape: 0.3598

Epoch 40/64

958/958 - 6s - 6ms/step - ia: 0.8781 - loss: 0.0794 - mae: 0.1724 - rmse: 0.2626 - smape: 0.3995 - val_ia: 0.7469 - val_loss: 0.0621 - val_mae: 0.1486 - val_rmse: 0.2094 - val_smape: 0.3736

Epoch 41/64

958/958 - 4s - 4ms/step - ia: 0.8770 - loss: 0.0790 - mae: 0.1733 - rmse: 0.2627 - smape: 0.4015 - val_ia: 0.7641 - val_loss: 0.0596 - val_mae: 0.1432 - val_rmse: 0.2072 - val_smape: 0.3659

Epoch 42/64

958/958 - 5s - 5ms/step - ia: 0.8778 - loss: 0.0805 - mae: 0.1728 - rmse: 0.2646 - smape: 0.3980 - val_ia: 0.7554 - val_loss: 0.0600 - val_mae: 0.1442 - val_rmse: 0.2063 - val_smape: 0.3686

Epoch 43/64

958/958 - 12s - 12ms/step - ia: 0.8782 - loss: 0.0780 - mae: 0.1717 - rmse: 0.2604 - smape: 0.3982 - val_ia: 0.7800 - val_loss: 0.0566 - val_mae: 0.1332 - val_rmse: 0.1985 - val_smape: 0.3568

Epoch 44/64

958/958 - 7s - 7ms/step - ia: 0.8781 - loss: 0.0802 - mae: 0.1729 - rmse: 0.2641 - smape: 0.3981 - val_ia: 0.7795 - val_loss: 0.0569 - val_mae: 0.1326 - val_rmse: 0.1986 - val_smape: 0.3521

Epoch 45/64

958/958 - 9s - 9ms/step - ia: 0.8784 - loss: 0.0794 - mae: 0.1721 - rmse: 0.2631 - smape: 0.3965 - val_ia: 0.7782 - val_loss: 0.0563 - val_mae: 0.1337 - val_rmse: 0.1974 - val_smape: 0.3541

Epoch 46/64

958/958 - 8s - 8ms/step - ia: 0.8783 - loss: 0.0792 - mae: 0.1725 - rmse: 0.2628 - smape: 0.3985 - val_ia: 0.7511 - val_loss: 0.0607 - val_mae: 0.1457 - val_rmse: 0.2076 - val_smape: 0.3712

Epoch 47/64

958/958 - 7s - 7ms/step - ia: 0.8789 - loss: 0.0775 - mae: 0.1711 - rmse: 0.2608 - smape: 0.3956 - val_ia: 0.7821 - val_loss: 0.0577 - val_mae: 0.1334 - val_rmse: 0.1998 - val_smape: 0.3503

Epoch 48/64

958/958 - 8s - 8ms/step - ia: 0.8779 - loss: 0.0778 - mae: 0.1721 - rmse: 0.2608 - smape: 0.3984 - val_ia: 0.7818 - val_loss: 0.0564 - val_mae: 0.1323 - val_rmse: 0.1977 - val_smape: 0.3521

Epoch 49/64

958/958 - 8s - 8ms/step - ia: 0.8782 - loss: 0.0786 - mae: 0.1722 - rmse: 0.2622 - smape: 0.3972 - val_ia: 0.7778 - val_loss: 0.0567 - val_mae: 0.1342 - val_rmse: 0.1991 - val_smape: 0.3553

Epoch 50/64

958/958 - 8s - 9ms/step - ia: 0.8770 - loss: 0.0809 - mae: 0.1743 - rmse: 0.2648 - smape: 0.4002 - val_ia: 0.7683 - val_loss: 0.0577 - val_mae: 0.1375 - val_rmse: 0.2003 - val_smape: 0.3577

Epoch 51/64

958/958 - 6s - 6ms/step - ia: 0.8782 - loss: 0.0790 - mae: 0.1725 - rmse: 0.2632 - smape: 0.3988 - val_ia: 0.7613 - val_loss: 0.0586 - val_mae: 0.1404 - val_rmse: 0.2046 - val_smape: 0.3685

Epoch 52/64

958/958 - 12s - 12ms/step - ia: 0.8775 - loss: 0.0801 - mae: 0.1736 - rmse: 0.2641 - smape: 0.3992 - val_ia: 0.7736 - val_loss: 0.0577 - val_mae: 0.1372 - val_rmse: 0.2020 - val_smape: 0.3585

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:20 593ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 84%|████████▍ | 42/50 [4:20:11<2:23:24, 1075.60s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1916/1916 - 17s - 9ms/step - ia: 0.8153 - loss: 0.1542 - mae: 0.2564 - rmse: 0.3558 - smape: 0.5432 - val_ia: 0.5998 - val_loss: 0.0877 - val_mae: 0.1878 - val_rmse: 0.2389 - val_smape: 0.4470

Epoch 2/8

1916/1916 - 13s - 7ms/step - ia: 0.8524 - loss: 0.1019 - mae: 0.2056 - rmse: 0.2903 - smape: 0.4593 - val_ia: 0.6456 - val_loss: 0.0744 - val_mae: 0.1624 - val_rmse: 0.2175 - val_smape: 0.3899

Epoch 3/8

1916/1916 - 12s - 6ms/step - ia: 0.8569 - loss: 0.0968 - mae: 0.1977 - rmse: 0.2815 - smape: 0.4478 - val_ia: 0.6471 - val_loss: 0.0688 - val_mae: 0.1554 - val_rmse: 0.2076 - val_smape: 0.3863

Epoch 4/8

1916/1916 - 7s - 4ms/step - ia: 0.8593 - loss: 0.0952 - mae: 0.1952 - rmse: 0.2778 - smape: 0.4455 - val_ia: 0.6528 - val_loss: 0.0669 - val_mae: 0.1536 - val_rmse: 0.2076 - val_smape: 0.3840

Epoch 5/8

1916/1916 - 12s - 6ms/step - ia: 0.8600 - loss: 0.0918 - mae: 0.1930 - rmse: 0.2738 - smape: 0.4445 - val_ia: 0.6261 - val_loss: 0.0741 - val_mae: 0.1658 - val_rmse: 0.2162 - val_smape: 0.3952

Epoch 6/8

1916/1916 - 8s - 4ms/step - ia: 0.8598 - loss: 0.0919 - mae: 0.1931 - rmse: 0.2750 - smape: 0.4451 - val_ia: 0.6062 - val_loss: 0.0790 - val_mae: 0.1800 - val_rmse: 0.2321 - val_smape: 0.4578

Epoch 7/8

1916/1916 - 8s - 4ms/step - ia: 0.8598 - loss: 0.0907 - mae: 0.1927 - rmse: 0.2728 - smape: 0.4467 - val_ia: 0.6610 - val_loss: 0.0648 - val_mae: 0.1470 - val_rmse: 0.2003 - val_smape: 0.3713

Epoch 8/8

1916/1916 - 12s - 6ms/step - ia: 0.8596 - loss: 0.0917 - mae: 0.1934 - rmse: 0.2740 - smape: 0.4467 - val_ia: 0.6276 - val_loss: 0.0699 - val_mae: 0.1614 - val_rmse: 0.2105 - val_smape: 0.4008

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 45s 338ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 86%|████████▌ | 43/50 [4:21:43<1:31:02, 780.42s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 10s - 43ms/step - ia: 0.4930 - loss: 1.2101 - mae: 0.8224 - rmse: 1.0883 - smape: 1.1629 - val_ia: 0.6364 - val_loss: 0.2870 - val_mae: 0.3755 - val_rmse: 0.5071 - val_smape: 0.7905

Epoch 2/128

240/240 - 2s - 7ms/step - ia: 0.5979 - loss: 0.7155 - mae: 0.6326 - rmse: 0.8407 - smape: 1.0103 - val_ia: 0.7343 - val_loss: 0.1620 - val_mae: 0.2704 - val_rmse: 0.3768 - val_smape: 0.6269

Epoch 3/128

240/240 - 2s - 9ms/step - ia: 0.6427 - loss: 0.5428 - mae: 0.5509 - rmse: 0.7335 - smape: 0.9386 - val_ia: 0.7763 - val_loss: 0.1190 - val_mae: 0.2258 - val_rmse: 0.3200 - val_smape: 0.5392

Epoch 4/128

240/240 - 2s - 10ms/step - ia: 0.6776 - loss: 0.4369 - mae: 0.4916 - rmse: 0.6565 - smape: 0.8751 - val_ia: 0.7951 - val_loss: 0.1010 - val_mae: 0.2051 - val_rmse: 0.2937 - val_smape: 0.4980

Epoch 5/128

240/240 - 2s - 8ms/step - ia: 0.6989 - loss: 0.3782 - mae: 0.4550 - rmse: 0.6110 - smape: 0.8367 - val_ia: 0.8150 - val_loss: 0.0901 - val_mae: 0.1883 - val_rmse: 0.2778 - val_smape: 0.4670

Epoch 6/128

240/240 - 2s - 8ms/step - ia: 0.7186 - loss: 0.3239 - mae: 0.4217 - rmse: 0.5662 - smape: 0.7997 - val_ia: 0.8260 - val_loss: 0.0824 - val_mae: 0.1773 - val_rmse: 0.2646 - val_smape: 0.4467

Epoch 7/128

240/240 - 1s - 6ms/step - ia: 0.7337 - loss: 0.2914 - mae: 0.3976 - rmse: 0.5363 - smape: 0.7679 - val_ia: 0.8258 - val_loss: 0.0796 - val_mae: 0.1752 - val_rmse: 0.2598 - val_smape: 0.4413

Epoch 8/128

240/240 - 1s - 4ms/step - ia: 0.7449 - loss: 0.2669 - mae: 0.3790 - rmse: 0.5126 - smape: 0.7482 - val_ia: 0.8321 - val_loss: 0.0762 - val_mae: 0.1701 - val_rmse: 0.2542 - val_smape: 0.4318

Epoch 9/128

240/240 - 2s - 7ms/step - ia: 0.7562 - loss: 0.2435 - mae: 0.3623 - rmse: 0.4903 - smape: 0.7255 - val_ia: 0.8318 - val_loss: 0.0749 - val_mae: 0.1693 - val_rmse: 0.2521 - val_smape: 0.4299

Epoch 10/128

240/240 - 3s - 12ms/step - ia: 0.7649 - loss: 0.2235 - mae: 0.3477 - rmse: 0.4698 - smape: 0.7100 - val_ia: 0.8398 - val_loss: 0.0716 - val_mae: 0.1623 - val_rmse: 0.2455 - val_smape: 0.4148

Epoch 11/128

240/240 - 2s - 10ms/step - ia: 0.7726 - loss: 0.2122 - mae: 0.3361 - rmse: 0.4568 - smape: 0.6920 - val_ia: 0.8490 - val_loss: 0.0693 - val_mae: 0.1554 - val_rmse: 0.2415 - val_smape: 0.4029

Epoch 12/128

240/240 - 2s - 10ms/step - ia: 0.7791 - loss: 0.2016 - mae: 0.3263 - rmse: 0.4457 - smape: 0.6769 - val_ia: 0.8492 - val_loss: 0.0681 - val_mae: 0.1545 - val_rmse: 0.2396 - val_smape: 0.4025

Epoch 13/128

240/240 - 2s - 10ms/step - ia: 0.7841 - loss: 0.1930 - mae: 0.3181 - rmse: 0.4347 - smape: 0.6668 - val_ia: 0.8454 - val_loss: 0.0686 - val_mae: 0.1569 - val_rmse: 0.2405 - val_smape: 0.4022

Epoch 14/128

240/240 - 3s - 11ms/step - ia: 0.7912 - loss: 0.1803 - mae: 0.3074 - rmse: 0.4211 - smape: 0.6523 - val_ia: 0.8495 - val_loss: 0.0664 - val_mae: 0.1536 - val_rmse: 0.2368 - val_smape: 0.3984

Epoch 15/128

240/240 - 3s - 13ms/step - ia: 0.7968 - loss: 0.1735 - mae: 0.2993 - rmse: 0.4129 - smape: 0.6388 - val_ia: 0.8513 - val_loss: 0.0652 - val_mae: 0.1518 - val_rmse: 0.2344 - val_smape: 0.3955

Epoch 16/128

240/240 - 2s - 6ms/step - ia: 0.8007 - loss: 0.1667 - mae: 0.2930 - rmse: 0.4042 - smape: 0.6275 - val_ia: 0.8542 - val_loss: 0.0648 - val_mae: 0.1496 - val_rmse: 0.2335 - val_smape: 0.3919

Epoch 17/128

240/240 - 2s - 8ms/step - ia: 0.8055 - loss: 0.1595 - mae: 0.2847 - rmse: 0.3952 - smape: 0.6138 - val_ia: 0.8525 - val_loss: 0.0649 - val_mae: 0.1507 - val_rmse: 0.2335 - val_smape: 0.3905

Epoch 18/128

240/240 - 3s - 11ms/step - ia: 0.8071 - loss: 0.1575 - mae: 0.2827 - rmse: 0.3932 - smape: 0.6126 - val_ia: 0.8541 - val_loss: 0.0636 - val_mae: 0.1491 - val_rmse: 0.2311 - val_smape: 0.3888

Epoch 19/128

240/240 - 3s - 13ms/step - ia: 0.8127 - loss: 0.1511 - mae: 0.2743 - rmse: 0.3846 - smape: 0.5991 - val_ia: 0.8548 - val_loss: 0.0635 - val_mae: 0.1482 - val_rmse: 0.2306 - val_smape: 0.3848

Epoch 20/128

240/240 - 2s - 10ms/step - ia: 0.8161 - loss: 0.1432 - mae: 0.2690 - rmse: 0.3744 - smape: 0.5922 - val_ia: 0.8575 - val_loss: 0.0626 - val_mae: 0.1464 - val_rmse: 0.2287 - val_smape: 0.3822

Epoch 21/128

240/240 - 3s - 14ms/step - ia: 0.8196 - loss: 0.1402 - mae: 0.2642 - rmse: 0.3703 - smape: 0.5828 - val_ia: 0.8570 - val_loss: 0.0622 - val_mae: 0.1461 - val_rmse: 0.2284 - val_smape: 0.3829

Epoch 22/128

240/240 - 2s - 7ms/step - ia: 0.8217 - loss: 0.1386 - mae: 0.2607 - rmse: 0.3683 - smape: 0.5781 - val_ia: 0.8598 - val_loss: 0.0615 - val_mae: 0.1440 - val_rmse: 0.2271 - val_smape: 0.3797

Epoch 23/128

240/240 - 3s - 12ms/step - ia: 0.8255 - loss: 0.1341 - mae: 0.2552 - rmse: 0.3619 - smape: 0.5675 - val_ia: 0.8618 - val_loss: 0.0608 - val_mae: 0.1420 - val_rmse: 0.2253 - val_smape: 0.3751

Epoch 24/128

240/240 - 2s - 8ms/step - ia: 0.8279 - loss: 0.1306 - mae: 0.2518 - rmse: 0.3565 - smape: 0.5645 - val_ia: 0.8556 - val_loss: 0.0618 - val_mae: 0.1463 - val_rmse: 0.2277 - val_smape: 0.3820

Epoch 25/128

240/240 - 2s - 10ms/step - ia: 0.8313 - loss: 0.1263 - mae: 0.2467 - rmse: 0.3501 - smape: 0.5560 - val_ia: 0.8580 - val_loss: 0.0615 - val_mae: 0.1452 - val_rmse: 0.2270 - val_smape: 0.3814

Epoch 26/128

240/240 - 3s - 11ms/step - ia: 0.8327 - loss: 0.1250 - mae: 0.2446 - rmse: 0.3494 - smape: 0.5482 - val_ia: 0.8611 - val_loss: 0.0603 - val_mae: 0.1426 - val_rmse: 0.2245 - val_smape: 0.3747

Epoch 27/128

240/240 - 3s - 12ms/step - ia: 0.8362 - loss: 0.1211 - mae: 0.2395 - rmse: 0.3431 - smape: 0.5383 - val_ia: 0.8623 - val_loss: 0.0602 - val_mae: 0.1417 - val_rmse: 0.2243 - val_smape: 0.3731

Epoch 28/128

240/240 - 3s - 12ms/step - ia: 0.8383 - loss: 0.1182 - mae: 0.2358 - rmse: 0.3388 - smape: 0.5341 - val_ia: 0.8643 - val_loss: 0.0597 - val_mae: 0.1399 - val_rmse: 0.2230 - val_smape: 0.3690

Epoch 29/128

240/240 - 3s - 14ms/step - ia: 0.8402 - loss: 0.1175 - mae: 0.2336 - rmse: 0.3374 - smape: 0.5294 - val_ia: 0.8611 - val_loss: 0.0602 - val_mae: 0.1421 - val_rmse: 0.2239 - val_smape: 0.3716

Epoch 30/128

240/240 - 2s - 7ms/step - ia: 0.8428 - loss: 0.1138 - mae: 0.2293 - rmse: 0.3322 - smape: 0.5242 - val_ia: 0.8633 - val_loss: 0.0596 - val_mae: 0.1404 - val_rmse: 0.2227 - val_smape: 0.3697

Epoch 31/128

240/240 - 3s - 12ms/step - ia: 0.8438 - loss: 0.1121 - mae: 0.2275 - rmse: 0.3293 - smape: 0.5205 - val_ia: 0.8645 - val_loss: 0.0590 - val_mae: 0.1391 - val_rmse: 0.2213 - val_smape: 0.3665

Epoch 32/128

240/240 - 1s - 6ms/step - ia: 0.8459 - loss: 0.1104 - mae: 0.2253 - rmse: 0.3263 - smape: 0.5157 - val_ia: 0.8661 - val_loss: 0.0586 - val_mae: 0.1379 - val_rmse: 0.2207 - val_smape: 0.3654

Epoch 33/128

240/240 - 2s - 7ms/step - ia: 0.8478 - loss: 0.1075 - mae: 0.2220 - rmse: 0.3230 - smape: 0.5104 - val_ia: 0.8677 - val_loss: 0.0586 - val_mae: 0.1366 - val_rmse: 0.2204 - val_smape: 0.3624

Epoch 34/128

240/240 - 3s - 11ms/step - ia: 0.8496 - loss: 0.1060 - mae: 0.2197 - rmse: 0.3204 - smape: 0.5084 - val_ia: 0.8653 - val_loss: 0.0586 - val_mae: 0.1384 - val_rmse: 0.2207 - val_smape: 0.3651

Epoch 35/128

240/240 - 2s - 8ms/step - ia: 0.8513 - loss: 0.1042 - mae: 0.2171 - rmse: 0.3168 - smape: 0.5028 - val_ia: 0.8633 - val_loss: 0.0590 - val_mae: 0.1401 - val_rmse: 0.2217 - val_smape: 0.3695

Epoch 36/128

240/240 - 2s - 8ms/step - ia: 0.8516 - loss: 0.1034 - mae: 0.2161 - rmse: 0.3154 - smape: 0.5011 - val_ia: 0.8662 - val_loss: 0.0585 - val_mae: 0.1376 - val_rmse: 0.2206 - val_smape: 0.3633

Epoch 37/128

240/240 - 2s - 10ms/step - ia: 0.8531 - loss: 0.1028 - mae: 0.2147 - rmse: 0.3152 - smape: 0.4980 - val_ia: 0.8631 - val_loss: 0.0589 - val_mae: 0.1397 - val_rmse: 0.2212 - val_smape: 0.3674

Epoch 38/128

240/240 - 1s - 6ms/step - ia: 0.8557 - loss: 0.0988 - mae: 0.2105 - rmse: 0.3097 - smape: 0.4899 - val_ia: 0.8648 - val_loss: 0.0585 - val_mae: 0.1385 - val_rmse: 0.2205 - val_smape: 0.3648

Epoch 39/128

240/240 - 3s - 11ms/step - ia: 0.8557 - loss: 0.0995 - mae: 0.2099 - rmse: 0.3101 - smape: 0.4902 - val_ia: 0.8664 - val_loss: 0.0579 - val_mae: 0.1370 - val_rmse: 0.2189 - val_smape: 0.3633

Epoch 40/128

240/240 - 2s - 7ms/step - ia: 0.8567 - loss: 0.0993 - mae: 0.2092 - rmse: 0.3087 - smape: 0.4893 - val_ia: 0.8682 - val_loss: 0.0578 - val_mae: 0.1362 - val_rmse: 0.2188 - val_smape: 0.3602

Epoch 41/128

240/240 - 2s - 8ms/step - ia: 0.8582 - loss: 0.0980 - mae: 0.2071 - rmse: 0.3070 - smape: 0.4841 - val_ia: 0.8684 - val_loss: 0.0578 - val_mae: 0.1362 - val_rmse: 0.2189 - val_smape: 0.3609

Epoch 42/128

240/240 - 2s - 10ms/step - ia: 0.8597 - loss: 0.0956 - mae: 0.2049 - rmse: 0.3042 - smape: 0.4779 - val_ia: 0.8679 - val_loss: 0.0577 - val_mae: 0.1362 - val_rmse: 0.2188 - val_smape: 0.3618

Epoch 43/128

240/240 - 2s - 9ms/step - ia: 0.8605 - loss: 0.0949 - mae: 0.2036 - rmse: 0.3026 - smape: 0.4767 - val_ia: 0.8693 - val_loss: 0.0576 - val_mae: 0.1347 - val_rmse: 0.2181 - val_smape: 0.3578

Epoch 44/128

240/240 - 3s - 12ms/step - ia: 0.8618 - loss: 0.0946 - mae: 0.2019 - rmse: 0.3022 - smape: 0.4742 - val_ia: 0.8631 - val_loss: 0.0586 - val_mae: 0.1397 - val_rmse: 0.2204 - val_smape: 0.3657

Epoch 45/128

240/240 - 2s - 10ms/step - ia: 0.8630 - loss: 0.0928 - mae: 0.1998 - rmse: 0.2985 - smape: 0.4673 - val_ia: 0.8683 - val_loss: 0.0575 - val_mae: 0.1356 - val_rmse: 0.2182 - val_smape: 0.3612

Epoch 46/128

240/240 - 2s - 10ms/step - ia: 0.8641 - loss: 0.0915 - mae: 0.1985 - rmse: 0.2968 - smape: 0.4649 - val_ia: 0.8652 - val_loss: 0.0583 - val_mae: 0.1378 - val_rmse: 0.2197 - val_smape: 0.3624

Epoch 47/128

240/240 - 3s - 13ms/step - ia: 0.8643 - loss: 0.0913 - mae: 0.1975 - rmse: 0.2968 - smape: 0.4664 - val_ia: 0.8661 - val_loss: 0.0580 - val_mae: 0.1369 - val_rmse: 0.2192 - val_smape: 0.3620

Epoch 48/128

240/240 - 2s - 10ms/step - ia: 0.8648 - loss: 0.0914 - mae: 0.1973 - rmse: 0.2968 - smape: 0.4631 - val_ia: 0.8686 - val_loss: 0.0574 - val_mae: 0.1353 - val_rmse: 0.2179 - val_smape: 0.3593

Epoch 49/128

240/240 - 2s - 10ms/step - ia: 0.8664 - loss: 0.0890 - mae: 0.1952 - rmse: 0.2932 - smape: 0.4620 - val_ia: 0.8677 - val_loss: 0.0575 - val_mae: 0.1357 - val_rmse: 0.2179 - val_smape: 0.3590

Epoch 50/128

240/240 - 3s - 13ms/step - ia: 0.8661 - loss: 0.0904 - mae: 0.1952 - rmse: 0.2938 - smape: 0.4614 - val_ia: 0.8703 - val_loss: 0.0572 - val_mae: 0.1340 - val_rmse: 0.2173 - val_smape: 0.3570

Epoch 51/128

240/240 - 2s - 8ms/step - ia: 0.8682 - loss: 0.0896 - mae: 0.1927 - rmse: 0.2922 - smape: 0.4540 - val_ia: 0.8670 - val_loss: 0.0574 - val_mae: 0.1361 - val_rmse: 0.2179 - val_smape: 0.3601

Epoch 52/128

240/240 - 3s - 13ms/step - ia: 0.8681 - loss: 0.0870 - mae: 0.1924 - rmse: 0.2890 - smape: 0.4568 - val_ia: 0.8660 - val_loss: 0.0577 - val_mae: 0.1368 - val_rmse: 0.2187 - val_smape: 0.3620

Epoch 53/128

240/240 - 3s - 14ms/step - ia: 0.8686 - loss: 0.0873 - mae: 0.1914 - rmse: 0.2898 - smape: 0.4533 - val_ia: 0.8668 - val_loss: 0.0574 - val_mae: 0.1365 - val_rmse: 0.2180 - val_smape: 0.3616

Epoch 54/128

240/240 - 2s - 7ms/step - ia: 0.8700 - loss: 0.0861 - mae: 0.1901 - rmse: 0.2872 - smape: 0.4520 - val_ia: 0.8703 - val_loss: 0.0570 - val_mae: 0.1337 - val_rmse: 0.2169 - val_smape: 0.3557

Epoch 55/128

240/240 - 2s - 7ms/step - ia: 0.8709 - loss: 0.0866 - mae: 0.1881 - rmse: 0.2881 - smape: 0.4448 - val_ia: 0.8676 - val_loss: 0.0575 - val_mae: 0.1360 - val_rmse: 0.2181 - val_smape: 0.3610

Epoch 56/128

240/240 - 1s - 6ms/step - ia: 0.8722 - loss: 0.0848 - mae: 0.1867 - rmse: 0.2846 - smape: 0.4465 - val_ia: 0.8695 - val_loss: 0.0571 - val_mae: 0.1342 - val_rmse: 0.2171 - val_smape: 0.3564

Epoch 57/128

240/240 - 2s - 8ms/step - ia: 0.8725 - loss: 0.0848 - mae: 0.1861 - rmse: 0.2844 - smape: 0.4448 - val_ia: 0.8702 - val_loss: 0.0570 - val_mae: 0.1336 - val_rmse: 0.2166 - val_smape: 0.3558

Epoch 58/128

240/240 - 2s - 7ms/step - ia: 0.8727 - loss: 0.0834 - mae: 0.1856 - rmse: 0.2826 - smape: 0.4445 - val_ia: 0.8711 - val_loss: 0.0568 - val_mae: 0.1330 - val_rmse: 0.2164 - val_smape: 0.3550

Epoch 59/128

240/240 - 3s - 11ms/step - ia: 0.8725 - loss: 0.0846 - mae: 0.1857 - rmse: 0.2845 - smape: 0.4428 - val_ia: 0.8677 - val_loss: 0.0571 - val_mae: 0.1353 - val_rmse: 0.2169 - val_smape: 0.3579

Epoch 60/128

240/240 - 3s - 12ms/step - ia: 0.8734 - loss: 0.0830 - mae: 0.1844 - rmse: 0.2817 - smape: 0.4397 - val_ia: 0.8664 - val_loss: 0.0578 - val_mae: 0.1367 - val_rmse: 0.2184 - val_smape: 0.3601

Epoch 61/128

240/240 - 2s - 7ms/step - ia: 0.8745 - loss: 0.0821 - mae: 0.1830 - rmse: 0.2803 - smape: 0.4377 - val_ia: 0.8679 - val_loss: 0.0572 - val_mae: 0.1352 - val_rmse: 0.2176 - val_smape: 0.3588

Epoch 62/128

240/240 - 2s - 7ms/step - ia: 0.8747 - loss: 0.0822 - mae: 0.1826 - rmse: 0.2797 - smape: 0.4376 - val_ia: 0.8720 - val_loss: 0.0566 - val_mae: 0.1324 - val_rmse: 0.2158 - val_smape: 0.3537

Epoch 63/128

240/240 - 3s - 12ms/step - ia: 0.8748 - loss: 0.0824 - mae: 0.1824 - rmse: 0.2803 - smape: 0.4347 - val_ia: 0.8680 - val_loss: 0.0573 - val_mae: 0.1353 - val_rmse: 0.2174 - val_smape: 0.3577

Epoch 64/128

240/240 - 3s - 12ms/step - ia: 0.8759 - loss: 0.0823 - mae: 0.1812 - rmse: 0.2789 - smape: 0.4339 - val_ia: 0.8704 - val_loss: 0.0566 - val_mae: 0.1332 - val_rmse: 0.2159 - val_smape: 0.3561

Epoch 65/128

240/240 - 2s - 6ms/step - ia: 0.8762 - loss: 0.0821 - mae: 0.1808 - rmse: 0.2796 - smape: 0.4346 - val_ia: 0.8710 - val_loss: 0.0567 - val_mae: 0.1328 - val_rmse: 0.2160 - val_smape: 0.3542

Epoch 66/128

240/240 - 3s - 12ms/step - ia: 0.8767 - loss: 0.0813 - mae: 0.1800 - rmse: 0.2780 - smape: 0.4320 - val_ia: 0.8716 - val_loss: 0.0565 - val_mae: 0.1323 - val_rmse: 0.2157 - val_smape: 0.3548

Epoch 67/128

240/240 - 2s - 7ms/step - ia: 0.8768 - loss: 0.0808 - mae: 0.1799 - rmse: 0.2778 - smape: 0.4312 - val_ia: 0.8700 - val_loss: 0.0567 - val_mae: 0.1334 - val_rmse: 0.2160 - val_smape: 0.3548

Epoch 68/128

240/240 - 1s - 6ms/step - ia: 0.8769 - loss: 0.0810 - mae: 0.1794 - rmse: 0.2787 - smape: 0.4289 - val_ia: 0.8720 - val_loss: 0.0564 - val_mae: 0.1321 - val_rmse: 0.2155 - val_smape: 0.3531

Epoch 69/128

240/240 - 2s - 8ms/step - ia: 0.8779 - loss: 0.0800 - mae: 0.1781 - rmse: 0.2760 - smape: 0.4284 - val_ia: 0.8689 - val_loss: 0.0571 - val_mae: 0.1343 - val_rmse: 0.2170 - val_smape: 0.3558

Epoch 70/128

240/240 - 3s - 11ms/step - ia: 0.8785 - loss: 0.0797 - mae: 0.1774 - rmse: 0.2758 - smape: 0.4265 - val_ia: 0.8698 - val_loss: 0.0568 - val_mae: 0.1335 - val_rmse: 0.2165 - val_smape: 0.3560

Epoch 71/128

240/240 - 3s - 13ms/step - ia: 0.8788 - loss: 0.0794 - mae: 0.1769 - rmse: 0.2749 - smape: 0.4229 - val_ia: 0.8702 - val_loss: 0.0566 - val_mae: 0.1332 - val_rmse: 0.2159 - val_smape: 0.3548

Epoch 72/128

240/240 - 1s - 5ms/step - ia: 0.8787 - loss: 0.0793 - mae: 0.1767 - rmse: 0.2746 - smape: 0.4245 - val_ia: 0.8700 - val_loss: 0.0568 - val_mae: 0.1334 - val_rmse: 0.2161 - val_smape: 0.3541

Epoch 73/128

240/240 - 2s - 7ms/step - ia: 0.8793 - loss: 0.0788 - mae: 0.1760 - rmse: 0.2744 - smape: 0.4247 - val_ia: 0.8696 - val_loss: 0.0567 - val_mae: 0.1337 - val_rmse: 0.2162 - val_smape: 0.3559

Epoch 74/128

240/240 - 3s - 11ms/step - ia: 0.8794 - loss: 0.0780 - mae: 0.1759 - rmse: 0.2723 - smape: 0.4242 - val_ia: 0.8695 - val_loss: 0.0566 - val_mae: 0.1337 - val_rmse: 0.2158 - val_smape: 0.3553

Epoch 75/128

240/240 - 2s - 10ms/step - ia: 0.8797 - loss: 0.0788 - mae: 0.1752 - rmse: 0.2735 - smape: 0.4224 - val_ia: 0.8701 - val_loss: 0.0568 - val_mae: 0.1334 - val_rmse: 0.2160 - val_smape: 0.3537

Epoch 76/128

240/240 - 1s - 6ms/step - ia: 0.8799 - loss: 0.0792 - mae: 0.1747 - rmse: 0.2747 - smape: 0.4202 - val_ia: 0.8706 - val_loss: 0.0567 - val_mae: 0.1330 - val_rmse: 0.2160 - val_smape: 0.3533

Epoch 77/128

240/240 - 1s - 6ms/step - ia: 0.8808 - loss: 0.0777 - mae: 0.1739 - rmse: 0.2716 - smape: 0.4189 - val_ia: 0.8729 - val_loss: 0.0562 - val_mae: 0.1312 - val_rmse: 0.2148 - val_smape: 0.3514

Epoch 78/128

240/240 - 1s - 4ms/step - ia: 0.8811 - loss: 0.0780 - mae: 0.1736 - rmse: 0.2720 - smape: 0.4210 - val_ia: 0.8685 - val_loss: 0.0570 - val_mae: 0.1346 - val_rmse: 0.2165 - val_smape: 0.3555

Epoch 79/128

240/240 - 1s - 6ms/step - ia: 0.8810 - loss: 0.0776 - mae: 0.1733 - rmse: 0.2715 - smape: 0.4209 - val_ia: 0.8690 - val_loss: 0.0570 - val_mae: 0.1343 - val_rmse: 0.2164 - val_smape: 0.3547

Epoch 80/128

240/240 - 3s - 13ms/step - ia: 0.8812 - loss: 0.0780 - mae: 0.1735 - rmse: 0.2721 - smape: 0.4177 - val_ia: 0.8720 - val_loss: 0.0563 - val_mae: 0.1318 - val_rmse: 0.2149 - val_smape: 0.3521

Epoch 81/128

240/240 - 3s - 11ms/step - ia: 0.8816 - loss: 0.0776 - mae: 0.1728 - rmse: 0.2709 - smape: 0.4187 - val_ia: 0.8703 - val_loss: 0.0566 - val_mae: 0.1332 - val_rmse: 0.2158 - val_smape: 0.3536

Epoch 82/128

240/240 - 2s - 7ms/step - ia: 0.8815 - loss: 0.0772 - mae: 0.1725 - rmse: 0.2706 - smape: 0.4175 - val_ia: 0.8676 - val_loss: 0.0572 - val_mae: 0.1352 - val_rmse: 0.2169 - val_smape: 0.3559

Epoch 83/128

240/240 - 2s - 6ms/step - ia: 0.8821 - loss: 0.0768 - mae: 0.1718 - rmse: 0.2702 - smape: 0.4156 - val_ia: 0.8728 - val_loss: 0.0565 - val_mae: 0.1318 - val_rmse: 0.2155 - val_smape: 0.3512

Epoch 84/128

240/240 - 2s - 7ms/step - ia: 0.8826 - loss: 0.0765 - mae: 0.1713 - rmse: 0.2692 - smape: 0.4158 - val_ia: 0.8705 - val_loss: 0.0566 - val_mae: 0.1330 - val_rmse: 0.2155 - val_smape: 0.3528

Epoch 85/128

240/240 - 3s - 11ms/step - ia: 0.8832 - loss: 0.0750 - mae: 0.1704 - rmse: 0.2670 - smape: 0.4140 - val_ia: 0.8732 - val_loss: 0.0563 - val_mae: 0.1313 - val_rmse: 0.2150 - val_smape: 0.3506

Epoch 86/128

240/240 - 3s - 12ms/step - ia: 0.8833 - loss: 0.0757 - mae: 0.1705 - rmse: 0.2678 - smape: 0.4136 - val_ia: 0.8721 - val_loss: 0.0562 - val_mae: 0.1316 - val_rmse: 0.2148 - val_smape: 0.3520

Epoch 87/128

240/240 - 2s - 7ms/step - ia: 0.8823 - loss: 0.0770 - mae: 0.1712 - rmse: 0.2702 - smape: 0.4131 - val_ia: 0.8715 - val_loss: 0.0563 - val_mae: 0.1320 - val_rmse: 0.2152 - val_smape: 0.3529

Epoch 88/128

240/240 - 2s - 6ms/step - ia: 0.8840 - loss: 0.0759 - mae: 0.1695 - rmse: 0.2681 - smape: 0.4124 - val_ia: 0.8691 - val_loss: 0.0569 - val_mae: 0.1339 - val_rmse: 0.2162 - val_smape: 0.3537

Epoch 89/128

240/240 - 3s - 11ms/step - ia: 0.8836 - loss: 0.0765 - mae: 0.1699 - rmse: 0.2690 - smape: 0.4102 - val_ia: 0.8727 - val_loss: 0.0561 - val_mae: 0.1313 - val_rmse: 0.2146 - val_smape: 0.3516

Epoch 90/128

240/240 - 2s - 7ms/step - ia: 0.8843 - loss: 0.0759 - mae: 0.1688 - rmse: 0.2675 - smape: 0.4083 - val_ia: 0.8707 - val_loss: 0.0563 - val_mae: 0.1326 - val_rmse: 0.2151 - val_smape: 0.3535

Epoch 91/128

240/240 - 3s - 12ms/step - ia: 0.8843 - loss: 0.0751 - mae: 0.1690 - rmse: 0.2668 - smape: 0.4105 - val_ia: 0.8721 - val_loss: 0.0561 - val_mae: 0.1317 - val_rmse: 0.2146 - val_smape: 0.3520

Epoch 92/128

240/240 - 2s - 10ms/step - ia: 0.8852 - loss: 0.0746 - mae: 0.1678 - rmse: 0.2660 - smape: 0.4066 - val_ia: 0.8698 - val_loss: 0.0565 - val_mae: 0.1333 - val_rmse: 0.2158 - val_smape: 0.3544

Epoch 93/128

240/240 - 1s - 6ms/step - ia: 0.8841 - loss: 0.0749 - mae: 0.1687 - rmse: 0.2654 - smape: 0.4110 - val_ia: 0.8712 - val_loss: 0.0564 - val_mae: 0.1324 - val_rmse: 0.2154 - val_smape: 0.3525

Epoch 94/128

240/240 - 2s - 7ms/step - ia: 0.8847 - loss: 0.0755 - mae: 0.1685 - rmse: 0.2677 - smape: 0.4078 - val_ia: 0.8725 - val_loss: 0.0562 - val_mae: 0.1313 - val_rmse: 0.2147 - val_smape: 0.3513

Epoch 95/128

240/240 - 1s - 6ms/step - ia: 0.8846 - loss: 0.0750 - mae: 0.1681 - rmse: 0.2671 - smape: 0.4083 - val_ia: 0.8730 - val_loss: 0.0561 - val_mae: 0.1310 - val_rmse: 0.2145 - val_smape: 0.3508

Epoch 96/128

240/240 - 2s - 7ms/step - ia: 0.8857 - loss: 0.0743 - mae: 0.1667 - rmse: 0.2652 - smape: 0.4062 - val_ia: 0.8730 - val_loss: 0.0560 - val_mae: 0.1308 - val_rmse: 0.2143 - val_smape: 0.3500

Epoch 97/128

240/240 - 2s - 7ms/step - ia: 0.8854 - loss: 0.0747 - mae: 0.1670 - rmse: 0.2659 - smape: 0.4055 - val_ia: 0.8711 - val_loss: 0.0563 - val_mae: 0.1327 - val_rmse: 0.2152 - val_smape: 0.3526

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 15s - 16ms/step - ia: 0.2742 - loss: 1.6089 - mae: 1.0092 - rmse: 1.2536 - smape: 1.4832 - val_ia: 0.2364 - val_loss: 0.9760 - val_mae: 0.7747 - val_rmse: 0.8568 - val_smape: 1.7179

Epoch 2/128

958/958 - 9s - 9ms/step - ia: 0.2942 - loss: 1.3124 - mae: 0.8797 - rmse: 1.1278 - smape: 1.4380 - val_ia: 0.2454 - val_loss: 0.9102 - val_mae: 0.7200 - val_rmse: 0.8031 - val_smape: 1.7987

Epoch 3/128

958/958 - 5s - 5ms/step - ia: 0.3008 - loss: 1.1848 - mae: 0.8220 - rmse: 1.0689 - smape: 1.4236 - val_ia: 0.2534 - val_loss: 0.8699 - val_mae: 0.6903 - val_rmse: 0.7733 - val_smape: 1.6711

Epoch 4/128

958/958 - 5s - 5ms/step - ia: 0.3051 - loss: 1.0850 - mae: 0.7789 - rmse: 1.0212 - smape: 1.4143 - val_ia: 0.2624 - val_loss: 0.8280 - val_mae: 0.6669 - val_rmse: 0.7488 - val_smape: 1.5456

Epoch 5/128

958/958 - 3s - 4ms/step - ia: 0.3193 - loss: 1.0080 - mae: 0.7438 - rmse: 0.9832 - smape: 1.3891 - val_ia: 0.2740 - val_loss: 0.7790 - val_mae: 0.6414 - val_rmse: 0.7218 - val_smape: 1.4223

Epoch 6/128

958/958 - 3s - 3ms/step - ia: 0.3431 - loss: 0.9371 - mae: 0.7095 - rmse: 0.9458 - smape: 1.3537 - val_ia: 0.2905 - val_loss: 0.7215 - val_mae: 0.6086 - val_rmse: 0.6876 - val_smape: 1.2829

Epoch 7/128

958/958 - 3s - 3ms/step - ia: 0.3738 - loss: 0.8745 - mae: 0.6813 - rmse: 0.9127 - smape: 1.3032 - val_ia: 0.3108 - val_loss: 0.6612 - val_mae: 0.5729 - val_rmse: 0.6506 - val_smape: 1.1486

Epoch 8/128

958/958 - 4s - 4ms/step - ia: 0.3992 - loss: 0.8384 - mae: 0.6596 - rmse: 0.8923 - smape: 1.2586 - val_ia: 0.3348 - val_loss: 0.6058 - val_mae: 0.5377 - val_rmse: 0.6147 - val_smape: 1.0338

Epoch 9/128

958/958 - 4s - 4ms/step - ia: 0.4370 - loss: 0.7849 - mae: 0.6322 - rmse: 0.8633 - smape: 1.1951 - val_ia: 0.3612 - val_loss: 0.5559 - val_mae: 0.5036 - val_rmse: 0.5804 - val_smape: 0.9347

Epoch 10/128

958/958 - 4s - 5ms/step - ia: 0.4592 - loss: 0.7513 - mae: 0.6180 - rmse: 0.8439 - smape: 1.1558 - val_ia: 0.3856 - val_loss: 0.5137 - val_mae: 0.4764 - val_rmse: 0.5531 - val_smape: 0.8659

Epoch 11/128

958/958 - 5s - 6ms/step - ia: 0.4847 - loss: 0.7219 - mae: 0.5995 - rmse: 0.8271 - smape: 1.1124 - val_ia: 0.4053 - val_loss: 0.4804 - val_mae: 0.4533 - val_rmse: 0.5299 - val_smape: 0.8116

Epoch 12/128

958/958 - 5s - 5ms/step - ia: 0.5036 - loss: 0.6934 - mae: 0.5850 - rmse: 0.8082 - smape: 1.0821 - val_ia: 0.4215 - val_loss: 0.4508 - val_mae: 0.4354 - val_rmse: 0.5118 - val_smape: 0.7726

Epoch 13/128

958/958 - 6s - 6ms/step - ia: 0.5145 - loss: 0.6685 - mae: 0.5778 - rmse: 0.7956 - smape: 1.0649 - val_ia: 0.4379 - val_loss: 0.4255 - val_mae: 0.4177 - val_rmse: 0.4943 - val_smape: 0.7347

Epoch 14/128

958/958 - 9s - 9ms/step - ia: 0.5288 - loss: 0.6584 - mae: 0.5678 - rmse: 0.7869 - smape: 1.0417 - val_ia: 0.4466 - val_loss: 0.4090 - val_mae: 0.4071 - val_rmse: 0.4833 - val_smape: 0.7158

Epoch 15/128

958/958 - 7s - 7ms/step - ia: 0.5389 - loss: 0.6322 - mae: 0.5574 - rmse: 0.7732 - smape: 1.0220 - val_ia: 0.4566 - val_loss: 0.3909 - val_mae: 0.3969 - val_rmse: 0.4726 - val_smape: 0.6978

Epoch 16/128

958/958 - 6s - 7ms/step - ia: 0.5455 - loss: 0.6248 - mae: 0.5520 - rmse: 0.7670 - smape: 1.0117 - val_ia: 0.4653 - val_loss: 0.3770 - val_mae: 0.3878 - val_rmse: 0.4633 - val_smape: 0.6815

Epoch 17/128

958/958 - 3s - 4ms/step - ia: 0.5563 - loss: 0.6113 - mae: 0.5449 - rmse: 0.7577 - smape: 0.9929 - val_ia: 0.4698 - val_loss: 0.3656 - val_mae: 0.3825 - val_rmse: 0.4574 - val_smape: 0.6734

Epoch 18/128

958/958 - 5s - 5ms/step - ia: 0.5608 - loss: 0.5941 - mae: 0.5391 - rmse: 0.7482 - smape: 0.9853 - val_ia: 0.4749 - val_loss: 0.3540 - val_mae: 0.3761 - val_rmse: 0.4503 - val_smape: 0.6655

Epoch 19/128

958/958 - 7s - 7ms/step - ia: 0.5623 - loss: 0.5994 - mae: 0.5399 - rmse: 0.7499 - smape: 0.9796 - val_ia: 0.4762 - val_loss: 0.3481 - val_mae: 0.3732 - val_rmse: 0.4468 - val_smape: 0.6625

Epoch 20/128

958/958 - 10s - 11ms/step - ia: 0.5681 - loss: 0.5812 - mae: 0.5327 - rmse: 0.7392 - smape: 0.9719 - val_ia: 0.4799 - val_loss: 0.3384 - val_mae: 0.3682 - val_rmse: 0.4412 - val_smape: 0.6550

Epoch 21/128

958/958 - 7s - 7ms/step - ia: 0.5770 - loss: 0.5709 - mae: 0.5250 - rmse: 0.7314 - smape: 0.9573 - val_ia: 0.4837 - val_loss: 0.3314 - val_mae: 0.3640 - val_rmse: 0.4367 - val_smape: 0.6486

Epoch 22/128

958/958 - 9s - 10ms/step - ia: 0.5779 - loss: 0.5627 - mae: 0.5231 - rmse: 0.7270 - smape: 0.9585 - val_ia: 0.4845 - val_loss: 0.3240 - val_mae: 0.3593 - val_rmse: 0.4316 - val_smape: 0.6428

Epoch 23/128

958/958 - 6s - 6ms/step - ia: 0.5851 - loss: 0.5540 - mae: 0.5187 - rmse: 0.7201 - smape: 0.9475 - val_ia: 0.4890 - val_loss: 0.3180 - val_mae: 0.3558 - val_rmse: 0.4280 - val_smape: 0.6363

Epoch 24/128

958/958 - 6s - 6ms/step - ia: 0.5861 - loss: 0.5548 - mae: 0.5171 - rmse: 0.7222 - smape: 0.9453 - val_ia: 0.4893 - val_loss: 0.3133 - val_mae: 0.3537 - val_rmse: 0.4254 - val_smape: 0.6352

Epoch 25/128

958/958 - 7s - 7ms/step - ia: 0.5869 - loss: 0.5526 - mae: 0.5173 - rmse: 0.7199 - smape: 0.9443 - val_ia: 0.4903 - val_loss: 0.3086 - val_mae: 0.3521 - val_rmse: 0.4234 - val_smape: 0.6346

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.5904 - loss: 0.5449 - mae: 0.5114 - rmse: 0.7141 - smape: 0.9307 - val_ia: 0.4928 - val_loss: 0.3041 - val_mae: 0.3482 - val_rmse: 0.4194 - val_smape: 0.6275

Epoch 27/128

958/958 - 5s - 6ms/step - ia: 0.5939 - loss: 0.5344 - mae: 0.5086 - rmse: 0.7081 - smape: 0.9295 - val_ia: 0.4959 - val_loss: 0.2969 - val_mae: 0.3454 - val_rmse: 0.4163 - val_smape: 0.6252

Epoch 28/128

958/958 - 6s - 6ms/step - ia: 0.6010 - loss: 0.5244 - mae: 0.5030 - rmse: 0.7015 - smape: 0.9208 - val_ia: 0.4966 - val_loss: 0.2936 - val_mae: 0.3429 - val_rmse: 0.4135 - val_smape: 0.6213

Epoch 29/128

958/958 - 6s - 6ms/step - ia: 0.5991 - loss: 0.5293 - mae: 0.5040 - rmse: 0.7038 - smape: 0.9233 - val_ia: 0.4986 - val_loss: 0.2898 - val_mae: 0.3404 - val_rmse: 0.4107 - val_smape: 0.6189

Epoch 30/128

958/958 - 5s - 5ms/step - ia: 0.6004 - loss: 0.5301 - mae: 0.5040 - rmse: 0.7039 - smape: 0.9227 - val_ia: 0.4985 - val_loss: 0.2883 - val_mae: 0.3396 - val_rmse: 0.4094 - val_smape: 0.6195

Epoch 31/128

958/958 - 7s - 7ms/step - ia: 0.6028 - loss: 0.5237 - mae: 0.5009 - rmse: 0.6995 - smape: 0.9140 - val_ia: 0.5019 - val_loss: 0.2849 - val_mae: 0.3382 - val_rmse: 0.4078 - val_smape: 0.6176

Epoch 32/128

958/958 - 10s - 10ms/step - ia: 0.6049 - loss: 0.5131 - mae: 0.4971 - rmse: 0.6932 - smape: 0.9121 - val_ia: 0.5021 - val_loss: 0.2803 - val_mae: 0.3353 - val_rmse: 0.4045 - val_smape: 0.6152

Epoch 33/128

958/958 - 5s - 5ms/step - ia: 0.6106 - loss: 0.5095 - mae: 0.4918 - rmse: 0.6908 - smape: 0.8997 - val_ia: 0.5042 - val_loss: 0.2773 - val_mae: 0.3328 - val_rmse: 0.4017 - val_smape: 0.6130

Epoch 34/128

958/958 - 6s - 6ms/step - ia: 0.6106 - loss: 0.5021 - mae: 0.4920 - rmse: 0.6867 - smape: 0.9052 - val_ia: 0.5038 - val_loss: 0.2717 - val_mae: 0.3312 - val_rmse: 0.3998 - val_smape: 0.6130

Epoch 35/128

958/958 - 6s - 6ms/step - ia: 0.6114 - loss: 0.5091 - mae: 0.4923 - rmse: 0.6891 - smape: 0.9078 - val_ia: 0.5062 - val_loss: 0.2697 - val_mae: 0.3299 - val_rmse: 0.3981 - val_smape: 0.6115

Epoch 36/128

958/958 - 5s - 5ms/step - ia: 0.6151 - loss: 0.4958 - mae: 0.4881 - rmse: 0.6813 - smape: 0.9024 - val_ia: 0.5067 - val_loss: 0.2671 - val_mae: 0.3283 - val_rmse: 0.3964 - val_smape: 0.6097

Epoch 37/128

958/958 - 6s - 7ms/step - ia: 0.6192 - loss: 0.4925 - mae: 0.4836 - rmse: 0.6773 - smape: 0.8920 - val_ia: 0.5110 - val_loss: 0.2638 - val_mae: 0.3251 - val_rmse: 0.3931 - val_smape: 0.6024

Epoch 38/128

958/958 - 10s - 11ms/step - ia: 0.6196 - loss: 0.4860 - mae: 0.4827 - rmse: 0.6739 - smape: 0.8952 - val_ia: 0.5123 - val_loss: 0.2599 - val_mae: 0.3229 - val_rmse: 0.3908 - val_smape: 0.5999

Epoch 39/128

958/958 - 11s - 11ms/step - ia: 0.6227 - loss: 0.4823 - mae: 0.4812 - rmse: 0.6727 - smape: 0.8938 - val_ia: 0.5122 - val_loss: 0.2564 - val_mae: 0.3213 - val_rmse: 0.3890 - val_smape: 0.6000

Epoch 40/128

958/958 - 10s - 10ms/step - ia: 0.6231 - loss: 0.4765 - mae: 0.4813 - rmse: 0.6681 - smape: 0.8928 - val_ia: 0.5120 - val_loss: 0.2560 - val_mae: 0.3207 - val_rmse: 0.3883 - val_smape: 0.6002

Epoch 41/128

958/958 - 6s - 7ms/step - ia: 0.6238 - loss: 0.4842 - mae: 0.4794 - rmse: 0.6717 - smape: 0.8894 - val_ia: 0.5160 - val_loss: 0.2516 - val_mae: 0.3185 - val_rmse: 0.3859 - val_smape: 0.5952

Epoch 42/128

958/958 - 6s - 7ms/step - ia: 0.6244 - loss: 0.4773 - mae: 0.4774 - rmse: 0.6675 - smape: 0.8922 - val_ia: 0.5166 - val_loss: 0.2503 - val_mae: 0.3174 - val_rmse: 0.3846 - val_smape: 0.5953

Epoch 43/128

958/958 - 6s - 6ms/step - ia: 0.6272 - loss: 0.4741 - mae: 0.4738 - rmse: 0.6663 - smape: 0.8831 - val_ia: 0.5203 - val_loss: 0.2468 - val_mae: 0.3149 - val_rmse: 0.3818 - val_smape: 0.5914

Epoch 44/128

958/958 - 5s - 5ms/step - ia: 0.6285 - loss: 0.4708 - mae: 0.4742 - rmse: 0.6638 - smape: 0.8872 - val_ia: 0.5211 - val_loss: 0.2448 - val_mae: 0.3136 - val_rmse: 0.3803 - val_smape: 0.5902

Epoch 45/128

958/958 - 6s - 6ms/step - ia: 0.6304 - loss: 0.4642 - mae: 0.4709 - rmse: 0.6581 - smape: 0.8817 - val_ia: 0.5222 - val_loss: 0.2403 - val_mae: 0.3113 - val_rmse: 0.3778 - val_smape: 0.5883

Epoch 46/128

958/958 - 6s - 6ms/step - ia: 0.6330 - loss: 0.4639 - mae: 0.4695 - rmse: 0.6569 - smape: 0.8799 - val_ia: 0.5258 - val_loss: 0.2380 - val_mae: 0.3089 - val_rmse: 0.3752 - val_smape: 0.5836

Epoch 47/128

958/958 - 6s - 6ms/step - ia: 0.6304 - loss: 0.4646 - mae: 0.4712 - rmse: 0.6580 - smape: 0.8831 - val_ia: 0.5287 - val_loss: 0.2356 - val_mae: 0.3071 - val_rmse: 0.3734 - val_smape: 0.5797

Epoch 48/128

958/958 - 11s - 11ms/step - ia: 0.6283 - loss: 0.4687 - mae: 0.4730 - rmse: 0.6620 - smape: 0.8861 - val_ia: 0.5288 - val_loss: 0.2339 - val_mae: 0.3061 - val_rmse: 0.3724 - val_smape: 0.5782

Epoch 49/128

958/958 - 6s - 6ms/step - ia: 0.6316 - loss: 0.4626 - mae: 0.4705 - rmse: 0.6575 - smape: 0.8805 - val_ia: 0.5299 - val_loss: 0.2314 - val_mae: 0.3046 - val_rmse: 0.3706 - val_smape: 0.5765

Epoch 50/128

958/958 - 6s - 6ms/step - ia: 0.6345 - loss: 0.4590 - mae: 0.4673 - rmse: 0.6544 - smape: 0.8753 - val_ia: 0.5316 - val_loss: 0.2303 - val_mae: 0.3032 - val_rmse: 0.3691 - val_smape: 0.5750

Epoch 51/128

958/958 - 9s - 10ms/step - ia: 0.6360 - loss: 0.4581 - mae: 0.4646 - rmse: 0.6517 - smape: 0.8731 - val_ia: 0.5327 - val_loss: 0.2258 - val_mae: 0.3011 - val_rmse: 0.3670 - val_smape: 0.5725

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.6387 - loss: 0.4474 - mae: 0.4625 - rmse: 0.6460 - smape: 0.8701 - val_ia: 0.5352 - val_loss: 0.2240 - val_mae: 0.2990 - val_rmse: 0.3645 - val_smape: 0.5697

Epoch 53/128

958/958 - 4s - 4ms/step - ia: 0.6375 - loss: 0.4519 - mae: 0.4648 - rmse: 0.6492 - smape: 0.8721 - val_ia: 0.5337 - val_loss: 0.2231 - val_mae: 0.2992 - val_rmse: 0.3646 - val_smape: 0.5718

Epoch 54/128

958/958 - 4s - 4ms/step - ia: 0.6354 - loss: 0.4526 - mae: 0.4650 - rmse: 0.6506 - smape: 0.8753 - val_ia: 0.5355 - val_loss: 0.2210 - val_mae: 0.2976 - val_rmse: 0.3627 - val_smape: 0.5695

Epoch 55/128

958/958 - 5s - 5ms/step - ia: 0.6390 - loss: 0.4482 - mae: 0.4622 - rmse: 0.6467 - smape: 0.8713 - val_ia: 0.5395 - val_loss: 0.2181 - val_mae: 0.2949 - val_rmse: 0.3605 - val_smape: 0.5631

Epoch 56/128

958/958 - 6s - 6ms/step - ia: 0.6422 - loss: 0.4430 - mae: 0.4592 - rmse: 0.6423 - smape: 0.8679 - val_ia: 0.5396 - val_loss: 0.2157 - val_mae: 0.2944 - val_rmse: 0.3591 - val_smape: 0.5649

Epoch 57/128

958/958 - 5s - 5ms/step - ia: 0.6412 - loss: 0.4446 - mae: 0.4607 - rmse: 0.6451 - smape: 0.8712 - val_ia: 0.5402 - val_loss: 0.2170 - val_mae: 0.2948 - val_rmse: 0.3594 - val_smape: 0.5643

Epoch 58/128

958/958 - 5s - 6ms/step - ia: 0.6427 - loss: 0.4392 - mae: 0.4576 - rmse: 0.6401 - smape: 0.8624 - val_ia: 0.5420 - val_loss: 0.2139 - val_mae: 0.2928 - val_rmse: 0.3573 - val_smape: 0.5620

Epoch 59/128

958/958 - 5s - 5ms/step - ia: 0.6439 - loss: 0.4421 - mae: 0.4566 - rmse: 0.6421 - smape: 0.8629 - val_ia: 0.5438 - val_loss: 0.2113 - val_mae: 0.2906 - val_rmse: 0.3549 - val_smape: 0.5590

Epoch 60/128

958/958 - 6s - 7ms/step - ia: 0.6459 - loss: 0.4365 - mae: 0.4553 - rmse: 0.6375 - smape: 0.8601 - val_ia: 0.5460 - val_loss: 0.2097 - val_mae: 0.2896 - val_rmse: 0.3539 - val_smape: 0.5572

Epoch 61/128

958/958 - 9s - 10ms/step - ia: 0.6443 - loss: 0.4369 - mae: 0.4564 - rmse: 0.6374 - smape: 0.8659 - val_ia: 0.5445 - val_loss: 0.2087 - val_mae: 0.2894 - val_rmse: 0.3535 - val_smape: 0.5582

Epoch 62/128

958/958 - 6s - 6ms/step - ia: 0.6464 - loss: 0.4372 - mae: 0.4548 - rmse: 0.6380 - smape: 0.8581 - val_ia: 0.5448 - val_loss: 0.2070 - val_mae: 0.2883 - val_rmse: 0.3521 - val_smape: 0.5571

Epoch 63/128

958/958 - 6s - 6ms/step - ia: 0.6475 - loss: 0.4319 - mae: 0.4533 - rmse: 0.6349 - smape: 0.8589 - val_ia: 0.5493 - val_loss: 0.2038 - val_mae: 0.2856 - val_rmse: 0.3496 - val_smape: 0.5507

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.6473 - loss: 0.4339 - mae: 0.4526 - rmse: 0.6341 - smape: 0.8599 - val_ia: 0.5523 - val_loss: 0.2022 - val_mae: 0.2839 - val_rmse: 0.3477 - val_smape: 0.5496

Epoch 65/128

958/958 - 5s - 5ms/step - ia: 0.6500 - loss: 0.4251 - mae: 0.4509 - rmse: 0.6304 - smape: 0.8552 - val_ia: 0.5535 - val_loss: 0.2003 - val_mae: 0.2827 - val_rmse: 0.3463 - val_smape: 0.5480

Epoch 66/128

958/958 - 6s - 6ms/step - ia: 0.6467 - loss: 0.4313 - mae: 0.4534 - rmse: 0.6347 - smape: 0.8601 - val_ia: 0.5538 - val_loss: 0.2000 - val_mae: 0.2831 - val_rmse: 0.3459 - val_smape: 0.5497

Epoch 67/128

958/958 - 10s - 10ms/step - ia: 0.6511 - loss: 0.4198 - mae: 0.4474 - rmse: 0.6257 - smape: 0.8551 - val_ia: 0.5574 - val_loss: 0.1968 - val_mae: 0.2801 - val_rmse: 0.3433 - val_smape: 0.5451

Epoch 68/128

958/958 - 4s - 4ms/step - ia: 0.6523 - loss: 0.4257 - mae: 0.4480 - rmse: 0.6301 - smape: 0.8502 - val_ia: 0.5573 - val_loss: 0.1946 - val_mae: 0.2790 - val_rmse: 0.3420 - val_smape: 0.5428

Epoch 69/128

958/958 - 6s - 6ms/step - ia: 0.6533 - loss: 0.4181 - mae: 0.4465 - rmse: 0.6247 - smape: 0.8537 - val_ia: 0.5585 - val_loss: 0.1929 - val_mae: 0.2782 - val_rmse: 0.3408 - val_smape: 0.5426

Epoch 70/128

958/958 - 6s - 6ms/step - ia: 0.6512 - loss: 0.4202 - mae: 0.4488 - rmse: 0.6262 - smape: 0.8556 - val_ia: 0.5588 - val_loss: 0.1912 - val_mae: 0.2774 - val_rmse: 0.3399 - val_smape: 0.5414

Epoch 71/128

958/958 - 6s - 6ms/step - ia: 0.6548 - loss: 0.4140 - mae: 0.4436 - rmse: 0.6223 - smape: 0.8476 - val_ia: 0.5596 - val_loss: 0.1898 - val_mae: 0.2759 - val_rmse: 0.3385 - val_smape: 0.5393

Epoch 72/128

958/958 - 6s - 6ms/step - ia: 0.6540 - loss: 0.4148 - mae: 0.4437 - rmse: 0.6226 - smape: 0.8478 - val_ia: 0.5614 - val_loss: 0.1878 - val_mae: 0.2751 - val_rmse: 0.3369 - val_smape: 0.5388

Epoch 73/128

958/958 - 6s - 6ms/step - ia: 0.6542 - loss: 0.4184 - mae: 0.4456 - rmse: 0.6239 - smape: 0.8503 - val_ia: 0.5641 - val_loss: 0.1869 - val_mae: 0.2736 - val_rmse: 0.3356 - val_smape: 0.5360

Epoch 74/128

958/958 - 6s - 6ms/step - ia: 0.6553 - loss: 0.4135 - mae: 0.4448 - rmse: 0.6210 - smape: 0.8496 - val_ia: 0.5642 - val_loss: 0.1862 - val_mae: 0.2733 - val_rmse: 0.3352 - val_smape: 0.5366

Epoch 75/128

958/958 - 4s - 4ms/step - ia: 0.6552 - loss: 0.4125 - mae: 0.4440 - rmse: 0.6197 - smape: 0.8449 - val_ia: 0.5650 - val_loss: 0.1852 - val_mae: 0.2728 - val_rmse: 0.3344 - val_smape: 0.5349

Epoch 76/128

958/958 - 5s - 5ms/step - ia: 0.6571 - loss: 0.4143 - mae: 0.4408 - rmse: 0.6200 - smape: 0.8433 - val_ia: 0.5672 - val_loss: 0.1829 - val_mae: 0.2710 - val_rmse: 0.3327 - val_smape: 0.5315

Epoch 77/128

958/958 - 4s - 5ms/step - ia: 0.6577 - loss: 0.4114 - mae: 0.4419 - rmse: 0.6194 - smape: 0.8414 - val_ia: 0.5696 - val_loss: 0.1817 - val_mae: 0.2691 - val_rmse: 0.3309 - val_smape: 0.5298

Epoch 78/128

958/958 - 6s - 6ms/step - ia: 0.6570 - loss: 0.4142 - mae: 0.4412 - rmse: 0.6200 - smape: 0.8434 - val_ia: 0.5701 - val_loss: 0.1802 - val_mae: 0.2684 - val_rmse: 0.3299 - val_smape: 0.5285

Epoch 79/128

958/958 - 6s - 6ms/step - ia: 0.6594 - loss: 0.4072 - mae: 0.4399 - rmse: 0.6166 - smape: 0.8424 - val_ia: 0.5704 - val_loss: 0.1790 - val_mae: 0.2677 - val_rmse: 0.3292 - val_smape: 0.5259

Epoch 80/128

958/958 - 6s - 6ms/step - ia: 0.6585 - loss: 0.4094 - mae: 0.4406 - rmse: 0.6173 - smape: 0.8413 - val_ia: 0.5716 - val_loss: 0.1793 - val_mae: 0.2676 - val_rmse: 0.3288 - val_smape: 0.5265

Epoch 81/128

958/958 - 10s - 11ms/step - ia: 0.6609 - loss: 0.4086 - mae: 0.4379 - rmse: 0.6149 - smape: 0.8395 - val_ia: 0.5754 - val_loss: 0.1768 - val_mae: 0.2649 - val_rmse: 0.3264 - val_smape: 0.5231

Epoch 82/128

958/958 - 5s - 5ms/step - ia: 0.6619 - loss: 0.4046 - mae: 0.4367 - rmse: 0.6134 - smape: 0.8361 - val_ia: 0.5745 - val_loss: 0.1753 - val_mae: 0.2648 - val_rmse: 0.3259 - val_smape: 0.5199

Epoch 83/128

958/958 - 7s - 7ms/step - ia: 0.6589 - loss: 0.4067 - mae: 0.4393 - rmse: 0.6167 - smape: 0.8406 - val_ia: 0.5780 - val_loss: 0.1735 - val_mae: 0.2627 - val_rmse: 0.3238 - val_smape: 0.5175

Epoch 84/128

958/958 - 10s - 10ms/step - ia: 0.6645 - loss: 0.3996 - mae: 0.4331 - rmse: 0.6105 - smape: 0.8296 - val_ia: 0.5822 - val_loss: 0.1714 - val_mae: 0.2600 - val_rmse: 0.3218 - val_smape: 0.5136

Epoch 85/128

958/958 - 6s - 7ms/step - ia: 0.6636 - loss: 0.4010 - mae: 0.4358 - rmse: 0.6122 - smape: 0.8307 - val_ia: 0.5801 - val_loss: 0.1725 - val_mae: 0.2618 - val_rmse: 0.3227 - val_smape: 0.5171

Epoch 86/128

958/958 - 10s - 11ms/step - ia: 0.6621 - loss: 0.4010 - mae: 0.4360 - rmse: 0.6119 - smape: 0.8338 - val_ia: 0.5800 - val_loss: 0.1704 - val_mae: 0.2608 - val_rmse: 0.3217 - val_smape: 0.5140

Epoch 87/128

958/958 - 5s - 5ms/step - ia: 0.6636 - loss: 0.4025 - mae: 0.4340 - rmse: 0.6128 - smape: 0.8321 - val_ia: 0.5824 - val_loss: 0.1686 - val_mae: 0.2589 - val_rmse: 0.3198 - val_smape: 0.5112

Epoch 88/128

958/958 - 6s - 6ms/step - ia: 0.6634 - loss: 0.4001 - mae: 0.4349 - rmse: 0.6106 - smape: 0.8340 - val_ia: 0.5843 - val_loss: 0.1680 - val_mae: 0.2579 - val_rmse: 0.3188 - val_smape: 0.5106

Epoch 89/128

958/958 - 9s - 10ms/step - ia: 0.6649 - loss: 0.3970 - mae: 0.4329 - rmse: 0.6079 - smape: 0.8287 - val_ia: 0.5851 - val_loss: 0.1661 - val_mae: 0.2568 - val_rmse: 0.3177 - val_smape: 0.5077

Epoch 90/128

958/958 - 3s - 3ms/step - ia: 0.6682 - loss: 0.3949 - mae: 0.4291 - rmse: 0.6073 - smape: 0.8213 - val_ia: 0.5867 - val_loss: 0.1653 - val_mae: 0.2560 - val_rmse: 0.3166 - val_smape: 0.5066

Epoch 91/128

958/958 - 3s - 3ms/step - ia: 0.6664 - loss: 0.3955 - mae: 0.4318 - rmse: 0.6070 - smape: 0.8261 - val_ia: 0.5859 - val_loss: 0.1634 - val_mae: 0.2551 - val_rmse: 0.3158 - val_smape: 0.5051

Epoch 92/128

958/958 - 3s - 4ms/step - ia: 0.6658 - loss: 0.3962 - mae: 0.4321 - rmse: 0.6074 - smape: 0.8313 - val_ia: 0.5871 - val_loss: 0.1635 - val_mae: 0.2551 - val_rmse: 0.3156 - val_smape: 0.5042

Epoch 93/128

958/958 - 4s - 4ms/step - ia: 0.6672 - loss: 0.3952 - mae: 0.4306 - rmse: 0.6056 - smape: 0.8248 - val_ia: 0.5899 - val_loss: 0.1630 - val_mae: 0.2542 - val_rmse: 0.3145 - val_smape: 0.5031

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.6686 - loss: 0.3925 - mae: 0.4288 - rmse: 0.6036 - smape: 0.8250 - val_ia: 0.5880 - val_loss: 0.1619 - val_mae: 0.2543 - val_rmse: 0.3144 - val_smape: 0.5035

Epoch 95/128

958/958 - 4s - 5ms/step - ia: 0.6689 - loss: 0.3912 - mae: 0.4280 - rmse: 0.6026 - smape: 0.8228 - val_ia: 0.5932 - val_loss: 0.1600 - val_mae: 0.2519 - val_rmse: 0.3120 - val_smape: 0.4991

Epoch 96/128

958/958 - 4s - 5ms/step - ia: 0.6669 - loss: 0.3963 - mae: 0.4303 - rmse: 0.6074 - smape: 0.8255 - val_ia: 0.5909 - val_loss: 0.1607 - val_mae: 0.2538 - val_rmse: 0.3135 - val_smape: 0.5021

Epoch 97/128

958/958 - 5s - 5ms/step - ia: 0.6683 - loss: 0.3847 - mae: 0.4283 - rmse: 0.5986 - smape: 0.8242 - val_ia: 0.5951 - val_loss: 0.1568 - val_mae: 0.2494 - val_rmse: 0.3094 - val_smape: 0.4962

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

479/479 - 43s - 90ms/step - ia: 0.7974 - loss: 0.1890 - mae: 0.2824 - rmse: 0.4139 - smape: 0.5757 - val_ia: 0.7078 - val_loss: 0.0894 - val_mae: 0.2108 - val_rmse: 0.2725 - val_smape: 0.4786

Epoch 2/256

479/479 - 3s - 6ms/step - ia: 0.8473 - loss: 0.1125 - mae: 0.2187 - rmse: 0.3260 - smape: 0.4777 - val_ia: 0.7777 - val_loss: 0.0699 - val_mae: 0.1715 - val_rmse: 0.2384 - val_smape: 0.4163

Epoch 3/256

479/479 - 2s - 5ms/step - ia: 0.8501 - loss: 0.1104 - mae: 0.2145 - rmse: 0.3219 - smape: 0.4694 - val_ia: 0.6887 - val_loss: 0.1129 - val_mae: 0.2405 - val_rmse: 0.3001 - val_smape: 0.5190

Epoch 4/256

479/479 - 4s - 9ms/step - ia: 0.8588 - loss: 0.1009 - mae: 0.2031 - rmse: 0.3075 - smape: 0.4489 - val_ia: 0.6849 - val_loss: 0.0849 - val_mae: 0.2211 - val_rmse: 0.2776 - val_smape: 0.5442

Epoch 5/256

479/479 - 6s - 12ms/step - ia: 0.8544 - loss: 0.1063 - mae: 0.2089 - rmse: 0.3147 - smape: 0.4595 - val_ia: 0.7091 - val_loss: 0.0923 - val_mae: 0.2190 - val_rmse: 0.2773 - val_smape: 0.4806

Epoch 6/256

479/479 - 6s - 12ms/step - ia: 0.8571 - loss: 0.1065 - mae: 0.2057 - rmse: 0.3131 - smape: 0.4528 - val_ia: 0.6846 - val_loss: 0.1059 - val_mae: 0.2331 - val_rmse: 0.2925 - val_smape: 0.5192

Epoch 7/256

479/479 - 5s - 9ms/step - ia: 0.8558 - loss: 0.1033 - mae: 0.2070 - rmse: 0.3120 - smape: 0.4569 - val_ia: 0.6769 - val_loss: 0.1175 - val_mae: 0.2435 - val_rmse: 0.3034 - val_smape: 0.5177

Epoch 8/256

479/479 - 6s - 12ms/step - ia: 0.8612 - loss: 0.0989 - mae: 0.1998 - rmse: 0.3048 - smape: 0.4390 - val_ia: 0.6572 - val_loss: 0.1059 - val_mae: 0.2518 - val_rmse: 0.3064 - val_smape: 0.5860

Epoch 9/256

479/479 - 6s - 12ms/step - ia: 0.8647 - loss: 0.0934 - mae: 0.1944 - rmse: 0.2960 - smape: 0.4354 - val_ia: 0.6887 - val_loss: 0.0941 - val_mae: 0.2260 - val_rmse: 0.2825 - val_smape: 0.4943

Epoch 10/256

479/479 - 4s - 9ms/step - ia: 0.8568 - loss: 0.1061 - mae: 0.2051 - rmse: 0.3144 - smape: 0.4504 - val_ia: 0.6906 - val_loss: 0.1062 - val_mae: 0.2360 - val_rmse: 0.2956 - val_smape: 0.5189

Epoch 11/256

479/479 - 3s - 7ms/step - ia: 0.8635 - loss: 0.0949 - mae: 0.1960 - rmse: 0.2984 - smape: 0.4375 - val_ia: 0.7108 - val_loss: 0.0839 - val_mae: 0.2076 - val_rmse: 0.2646 - val_smape: 0.4744

Epoch 12/256

479/479 - 3s - 6ms/step - ia: 0.8630 - loss: 0.0965 - mae: 0.1968 - rmse: 0.3002 - smape: 0.4370 - val_ia: 0.6342 - val_loss: 0.1286 - val_mae: 0.2749 - val_rmse: 0.3303 - val_smape: 0.6036

Epoch 13/256

479/479 - 3s - 6ms/step - ia: 0.8612 - loss: 0.0991 - mae: 0.1994 - rmse: 0.3042 - smape: 0.4398 - val_ia: 0.6380 - val_loss: 0.1148 - val_mae: 0.2667 - val_rmse: 0.3245 - val_smape: 0.6031

Epoch 14/256

479/479 - 2s - 5ms/step - ia: 0.8604 - loss: 0.0990 - mae: 0.2007 - rmse: 0.3040 - smape: 0.4461 - val_ia: 0.6110 - val_loss: 0.1298 - val_mae: 0.2949 - val_rmse: 0.3489 - val_smape: 0.7258

Epoch 15/256

479/479 - 3s - 7ms/step - ia: 0.8596 - loss: 0.1010 - mae: 0.2014 - rmse: 0.3069 - smape: 0.4447 - val_ia: 0.6952 - val_loss: 0.0987 - val_mae: 0.2279 - val_rmse: 0.2834 - val_smape: 0.5132

Epoch 16/256

479/479 - 3s - 6ms/step - ia: 0.8608 - loss: 0.0978 - mae: 0.1993 - rmse: 0.3027 - smape: 0.4448 - val_ia: 0.6970 - val_loss: 0.0936 - val_mae: 0.2201 - val_rmse: 0.2783 - val_smape: 0.4986

Epoch 17/256

479/479 - 3s - 6ms/step - ia: 0.8594 - loss: 0.0981 - mae: 0.2014 - rmse: 0.3031 - smape: 0.4471 - val_ia: 0.6134 - val_loss: 0.1311 - val_mae: 0.2909 - val_rmse: 0.3457 - val_smape: 0.6800

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:53 843ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 92%|█████████▏| 46/50 [4:40:09<32:54, 493.56s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

3832/3832 - 30s - 8ms/step - ia: 0.7494 - loss: 0.2097 - mae: 0.3192 - rmse: 0.4122 - smape: 0.6478 - val_ia: 0.4532 - val_loss: 0.1010 - val_mae: 0.2035 - val_rmse: 0.2471 - val_smape: 0.4559

Epoch 2/8

3832/3832 - 18s - 5ms/step - ia: 0.7708 - loss: 0.1683 - mae: 0.2877 - rmse: 0.3708 - smape: 0.6078 - val_ia: 0.4410 - val_loss: 0.1059 - val_mae: 0.2146 - val_rmse: 0.2589 - val_smape: 0.4716

Epoch 3/8

3832/3832 - 18s - 5ms/step - ia: 0.7794 - loss: 0.1553 - mae: 0.2759 - rmse: 0.3566 - smape: 0.5885 - val_ia: 0.4305 - val_loss: 0.1042 - val_mae: 0.2071 - val_rmse: 0.2490 - val_smape: 0.4776

Epoch 4/8

3832/3832 - 17s - 4ms/step - ia: 0.7777 - loss: 0.1540 - mae: 0.2772 - rmse: 0.3568 - smape: 0.5962 - val_ia: 0.4467 - val_loss: 0.0866 - val_mae: 0.1957 - val_rmse: 0.2359 - val_smape: 0.4831

Epoch 5/8

3832/3832 - 21s - 5ms/step - ia: 0.7846 - loss: 0.1472 - mae: 0.2680 - rmse: 0.3464 - smape: 0.5812 - val_ia: 0.4322 - val_loss: 0.1138 - val_mae: 0.2303 - val_rmse: 0.2790 - val_smape: 0.5071

Epoch 6/8

3832/3832 - 16s - 4ms/step - ia: 0.7824 - loss: 0.1493 - mae: 0.2717 - rmse: 0.3507 - smape: 0.5901 - val_ia: 0.4058 - val_loss: 0.1028 - val_mae: 0.2305 - val_rmse: 0.2703 - val_smape: 0.5508

Epoch 7/8

3832/3832 - 15s - 4ms/step - ia: 0.7841 - loss: 0.1461 - mae: 0.2697 - rmse: 0.3467 - smape: 0.5896 - val_ia: 0.4489 - val_loss: 0.0919 - val_mae: 0.2030 - val_rmse: 0.2458 - val_smape: 0.4764

Epoch 8/8

3832/3832 - 17s - 4ms/step - ia: 0.7815 - loss: 0.1503 - mae: 0.2724 - rmse: 0.3513 - smape: 0.5893 - val_ia: 0.4431 - val_loss: 0.1022 - val_mae: 0.2021 - val_rmse: 0.2410 - val_smape: 0.4593

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:12 535ms/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 94%|█████████▍| 47/50 [4:42:45<19:36, 392.25s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 10s - 41ms/step - ia: 0.7615 - loss: 0.2936 - mae: 0.3338 - rmse: 0.4859 - smape: 0.6780 - val_ia: 0.7987 - val_loss: 0.1018 - val_mae: 0.2042 - val_rmse: 0.2956 - val_smape: 0.4940

Epoch 2/16

240/240 - 2s - 7ms/step - ia: 0.8661 - loss: 0.0996 - mae: 0.1936 - rmse: 0.3078 - smape: 0.4605 - val_ia: 0.8337 - val_loss: 0.0770 - val_mae: 0.1703 - val_rmse: 0.2558 - val_smape: 0.4296

Epoch 3/16

240/240 - 2s - 6ms/step - ia: 0.8809 - loss: 0.0831 - mae: 0.1731 - rmse: 0.2804 - smape: 0.4216 - val_ia: 0.8435 - val_loss: 0.0683 - val_mae: 0.1589 - val_rmse: 0.2405 - val_smape: 0.4055

Epoch 4/16

240/240 - 1s - 6ms/step - ia: 0.8893 - loss: 0.0747 - mae: 0.1612 - rmse: 0.2657 - smape: 0.3995 - val_ia: 0.8525 - val_loss: 0.0643 - val_mae: 0.1515 - val_rmse: 0.2325 - val_smape: 0.3896

Epoch 5/16

240/240 - 3s - 11ms/step - ia: 0.8922 - loss: 0.0719 - mae: 0.1573 - rmse: 0.2593 - smape: 0.3903 - val_ia: 0.8434 - val_loss: 0.0673 - val_mae: 0.1593 - val_rmse: 0.2401 - val_smape: 0.4078

Epoch 6/16

240/240 - 1s - 6ms/step - ia: 0.8958 - loss: 0.0689 - mae: 0.1523 - rmse: 0.2536 - smape: 0.3803 - val_ia: 0.8488 - val_loss: 0.0634 - val_mae: 0.1530 - val_rmse: 0.2318 - val_smape: 0.3935

Epoch 7/16

240/240 - 2s - 7ms/step - ia: 0.8963 - loss: 0.0675 - mae: 0.1512 - rmse: 0.2514 - smape: 0.3791 - val_ia: 0.8452 - val_loss: 0.0652 - val_mae: 0.1559 - val_rmse: 0.2321 - val_smape: 0.3863

Epoch 8/16

240/240 - 2s - 10ms/step - ia: 0.8973 - loss: 0.0665 - mae: 0.1498 - rmse: 0.2493 - smape: 0.3758 - val_ia: 0.8607 - val_loss: 0.0592 - val_mae: 0.1423 - val_rmse: 0.2221 - val_smape: 0.3711

Epoch 9/16

240/240 - 1s - 4ms/step - ia: 0.8995 - loss: 0.0652 - mae: 0.1469 - rmse: 0.2470 - smape: 0.3692 - val_ia: 0.8665 - val_loss: 0.0581 - val_mae: 0.1376 - val_rmse: 0.2188 - val_smape: 0.3603

Epoch 10/16

240/240 - 1s - 4ms/step - ia: 0.8995 - loss: 0.0649 - mae: 0.1470 - rmse: 0.2466 - smape: 0.3716 - val_ia: 0.8608 - val_loss: 0.0589 - val_mae: 0.1412 - val_rmse: 0.2206 - val_smape: 0.3684

Epoch 11/16

240/240 - 2s - 7ms/step - ia: 0.8996 - loss: 0.0649 - mae: 0.1472 - rmse: 0.2461 - smape: 0.3695 - val_ia: 0.8678 - val_loss: 0.0581 - val_mae: 0.1365 - val_rmse: 0.2188 - val_smape: 0.3583

Epoch 12/16

240/240 - 1s - 5ms/step - ia: 0.8996 - loss: 0.0647 - mae: 0.1468 - rmse: 0.2457 - smape: 0.3696 - val_ia: 0.8647 - val_loss: 0.0596 - val_mae: 0.1400 - val_rmse: 0.2220 - val_smape: 0.3625

Epoch 13/16

240/240 - 2s - 8ms/step - ia: 0.9000 - loss: 0.0646 - mae: 0.1467 - rmse: 0.2460 - smape: 0.3688 - val_ia: 0.8527 - val_loss: 0.0614 - val_mae: 0.1487 - val_rmse: 0.2266 - val_smape: 0.3801

Epoch 14/16

240/240 - 1s - 6ms/step - ia: 0.9006 - loss: 0.0642 - mae: 0.1457 - rmse: 0.2453 - smape: 0.3677 - val_ia: 0.8643 - val_loss: 0.0578 - val_mae: 0.1393 - val_rmse: 0.2186 - val_smape: 0.3640

Epoch 15/16

240/240 - 2s - 9ms/step - ia: 0.9007 - loss: 0.0641 - mae: 0.1454 - rmse: 0.2446 - smape: 0.3671 - val_ia: 0.8682 - val_loss: 0.0572 - val_mae: 0.1353 - val_rmse: 0.2168 - val_smape: 0.3563

Epoch 16/16

240/240 - 1s - 4ms/step - ia: 0.9007 - loss: 0.0640 - mae: 0.1453 - rmse: 0.2448 - smape: 0.3670 - val_ia: 0.8667 - val_loss: 0.0572 - val_mae: 0.1359 - val_rmse: 0.2169 - val_smape: 0.3600

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 20s 155ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 96%|█████████▌| 48/50 [4:43:22<09:31, 285.60s/trial, best loss: 0.03740939164650774]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 9s - 73ms/step - ia: 0.3767 - loss: 2.1730 - mae: 1.0718 - rmse: 1.4714 - smape: 1.2229 - val_ia: 0.3982 - val_loss: 1.7822 - val_mae: 0.9018 - val_rmse: 1.1779 - val_smape: 1.0672

Epoch 2/128

120/120 - 1s - 7ms/step - ia: 0.3780 - loss: 2.1541 - mae: 1.0655 - rmse: 1.4640 - smape: 1.2217 - val_ia: 0.4012 - val_loss: 1.7438 - val_mae: 0.8924 - val_rmse: 1.1641 - val_smape: 1.0662

Epoch 3/128

120/120 - 2s - 13ms/step - ia: 0.3816 - loss: 2.0859 - mae: 1.0521 - rmse: 1.4419 - smape: 1.2200 - val_ia: 0.4042 - val_loss: 1.7069 - val_mae: 0.8832 - val_rmse: 1.1510 - val_smape: 1.0651

Epoch 4/128

120/120 - 2s - 15ms/step - ia: 0.3842 - loss: 2.0570 - mae: 1.0429 - rmse: 1.4315 - smape: 1.2194 - val_ia: 0.4071 - val_loss: 1.6713 - val_mae: 0.8742 - val_rmse: 1.1382 - val_smape: 1.0640

Epoch 5/128

120/120 - 2s - 14ms/step - ia: 0.3867 - loss: 2.0045 - mae: 1.0309 - rmse: 1.4129 - smape: 1.2187 - val_ia: 0.4101 - val_loss: 1.6365 - val_mae: 0.8653 - val_rmse: 1.1261 - val_smape: 1.0629

Epoch 6/128

120/120 - 1s - 8ms/step - ia: 0.3878 - loss: 1.9823 - mae: 1.0271 - rmse: 1.4057 - smape: 1.2175 - val_ia: 0.4130 - val_loss: 1.6024 - val_mae: 0.8565 - val_rmse: 1.1140 - val_smape: 1.0618

Epoch 7/128

120/120 - 1s - 11ms/step - ia: 0.3919 - loss: 1.9292 - mae: 1.0146 - rmse: 1.3866 - smape: 1.2153 - val_ia: 0.4159 - val_loss: 1.5701 - val_mae: 0.8480 - val_rmse: 1.1023 - val_smape: 1.0609

Epoch 8/128

120/120 - 2s - 16ms/step - ia: 0.3945 - loss: 1.8966 - mae: 1.0055 - rmse: 1.3745 - smape: 1.2113 - val_ia: 0.4187 - val_loss: 1.5384 - val_mae: 0.8396 - val_rmse: 1.0909 - val_smape: 1.0600

Epoch 9/128

120/120 - 1s - 12ms/step - ia: 0.3965 - loss: 1.8802 - mae: 1.0004 - rmse: 1.3684 - smape: 1.2091 - val_ia: 0.4216 - val_loss: 1.5074 - val_mae: 0.8312 - val_rmse: 1.0797 - val_smape: 1.0589

Epoch 10/128

120/120 - 2s - 13ms/step - ia: 0.3983 - loss: 1.8324 - mae: 0.9885 - rmse: 1.3498 - smape: 1.2104 - val_ia: 0.4243 - val_loss: 1.4774 - val_mae: 0.8230 - val_rmse: 1.0690 - val_smape: 1.0579

Epoch 11/128

120/120 - 2s - 13ms/step - ia: 0.4003 - loss: 1.8048 - mae: 0.9814 - rmse: 1.3412 - smape: 1.2098 - val_ia: 0.4269 - val_loss: 1.4486 - val_mae: 0.8150 - val_rmse: 1.0584 - val_smape: 1.0569

Epoch 12/128

120/120 - 2s - 14ms/step - ia: 0.4013 - loss: 1.7726 - mae: 0.9742 - rmse: 1.3288 - smape: 1.2122 - val_ia: 0.4295 - val_loss: 1.4202 - val_mae: 0.8071 - val_rmse: 1.0482 - val_smape: 1.0559

Epoch 13/128

120/120 - 2s - 13ms/step - ia: 0.4044 - loss: 1.7539 - mae: 0.9667 - rmse: 1.3213 - smape: 1.2074 - val_ia: 0.4321 - val_loss: 1.3928 - val_mae: 0.7992 - val_rmse: 1.0380 - val_smape: 1.0549

Epoch 14/128

120/120 - 1s - 8ms/step - ia: 0.4084 - loss: 1.7152 - mae: 0.9545 - rmse: 1.3070 - smape: 1.2001 - val_ia: 0.4347 - val_loss: 1.3660 - val_mae: 0.7915 - val_rmse: 1.0280 - val_smape: 1.0540

Epoch 15/128

120/120 - 1s - 6ms/step - ia: 0.4116 - loss: 1.6833 - mae: 0.9472 - rmse: 1.2949 - smape: 1.1987 - val_ia: 0.4372 - val_loss: 1.3400 - val_mae: 0.7839 - val_rmse: 1.0182 - val_smape: 1.0530

Epoch 16/128

120/120 - 2s - 13ms/step - ia: 0.4129 - loss: 1.6641 - mae: 0.9406 - rmse: 1.2873 - smape: 1.1980 - val_ia: 0.4397 - val_loss: 1.3149 - val_mae: 0.7763 - val_rmse: 1.0084 - val_smape: 1.0520

Epoch 17/128

120/120 - 2s - 20ms/step - ia: 0.4153 - loss: 1.6314 - mae: 0.9314 - rmse: 1.2749 - smape: 1.1955 - val_ia: 0.4423 - val_loss: 1.2902 - val_mae: 0.7689 - val_rmse: 0.9988 - val_smape: 1.0512

Epoch 18/128

120/120 - 2s - 14ms/step - ia: 0.4166 - loss: 1.6035 - mae: 0.9259 - rmse: 1.2637 - smape: 1.1982 - val_ia: 0.4447 - val_loss: 1.2659 - val_mae: 0.7615 - val_rmse: 0.9895 - val_smape: 1.0503

Epoch 19/128

120/120 - 2s - 13ms/step - ia: 0.4202 - loss: 1.5651 - mae: 0.9129 - rmse: 1.2481 - smape: 1.1941 - val_ia: 0.4472 - val_loss: 1.2422 - val_mae: 0.7541 - val_rmse: 0.9803 - val_smape: 1.0495

Epoch 20/128

120/120 - 1s - 7ms/step - ia: 0.4232 - loss: 1.5442 - mae: 0.9073 - rmse: 1.2396 - smape: 1.1907 - val_ia: 0.4498 - val_loss: 1.2193 - val_mae: 0.7469 - val_rmse: 0.9712 - val_smape: 1.0485

Epoch 21/128

120/120 - 2s - 16ms/step - ia: 0.4242 - loss: 1.5118 - mae: 0.8988 - rmse: 1.2270 - smape: 1.1921 - val_ia: 0.4523 - val_loss: 1.1968 - val_mae: 0.7397 - val_rmse: 0.9621 - val_smape: 1.0476

Epoch 22/128

120/120 - 3s - 24ms/step - ia: 0.4257 - loss: 1.5109 - mae: 0.8965 - rmse: 1.2268 - smape: 1.1871 - val_ia: 0.4549 - val_loss: 1.1745 - val_mae: 0.7325 - val_rmse: 0.9533 - val_smape: 1.0465

Epoch 23/128

120/120 - 1s - 7ms/step - ia: 0.4296 - loss: 1.4743 - mae: 0.8865 - rmse: 1.2119 - smape: 1.1818 - val_ia: 0.4575 - val_loss: 1.1532 - val_mae: 0.7254 - val_rmse: 0.9443 - val_smape: 1.0452

Epoch 24/128

120/120 - 0s - 4ms/step - ia: 0.4313 - loss: 1.4513 - mae: 0.8797 - rmse: 1.2012 - smape: 1.1833 - val_ia: 0.4600 - val_loss: 1.1317 - val_mae: 0.7183 - val_rmse: 0.9356 - val_smape: 1.0443

Epoch 25/128

120/120 - 1s - 6ms/step - ia: 0.4351 - loss: 1.4259 - mae: 0.8687 - rmse: 1.1911 - smape: 1.1770 - val_ia: 0.4624 - val_loss: 1.1104 - val_mae: 0.7113 - val_rmse: 0.9273 - val_smape: 1.0432

Epoch 26/128

120/120 - 1s - 5ms/step - ia: 0.4362 - loss: 1.4036 - mae: 0.8633 - rmse: 1.1821 - smape: 1.1750 - val_ia: 0.4650 - val_loss: 1.0900 - val_mae: 0.7044 - val_rmse: 0.9187 - val_smape: 1.0418

Epoch 27/128

120/120 - 0s - 4ms/step - ia: 0.4396 - loss: 1.3856 - mae: 0.8540 - rmse: 1.1745 - smape: 1.1708 - val_ia: 0.4676 - val_loss: 1.0699 - val_mae: 0.6976 - val_rmse: 0.9102 - val_smape: 1.0403

Epoch 28/128

120/120 - 1s - 6ms/step - ia: 0.4416 - loss: 1.3556 - mae: 0.8488 - rmse: 1.1607 - smape: 1.1687 - val_ia: 0.4703 - val_loss: 1.0504 - val_mae: 0.6909 - val_rmse: 0.9017 - val_smape: 1.0385

Epoch 29/128

120/120 - 1s - 6ms/step - ia: 0.4448 - loss: 1.3328 - mae: 0.8398 - rmse: 1.1520 - smape: 1.1668 - val_ia: 0.4729 - val_loss: 1.0308 - val_mae: 0.6842 - val_rmse: 0.8935 - val_smape: 1.0364

Epoch 30/128

120/120 - 2s - 16ms/step - ia: 0.4470 - loss: 1.3101 - mae: 0.8345 - rmse: 1.1418 - smape: 1.1638 - val_ia: 0.4756 - val_loss: 1.0120 - val_mae: 0.6776 - val_rmse: 0.8853 - val_smape: 1.0342

Epoch 31/128

120/120 - 1s - 9ms/step - ia: 0.4496 - loss: 1.2857 - mae: 0.8256 - rmse: 1.1311 - smape: 1.1595 - val_ia: 0.4784 - val_loss: 0.9938 - val_mae: 0.6711 - val_rmse: 0.8771 - val_smape: 1.0319

Epoch 32/128

120/120 - 2s - 16ms/step - ia: 0.4514 - loss: 1.2715 - mae: 0.8212 - rmse: 1.1250 - smape: 1.1568 - val_ia: 0.4812 - val_loss: 0.9756 - val_mae: 0.6646 - val_rmse: 0.8690 - val_smape: 1.0295

Epoch 33/128

120/120 - 3s - 25ms/step - ia: 0.4585 - loss: 1.2433 - mae: 0.8116 - rmse: 1.1127 - smape: 1.1478 - val_ia: 0.4839 - val_loss: 0.9577 - val_mae: 0.6581 - val_rmse: 0.8611 - val_smape: 1.0268

Epoch 34/128

120/120 - 1s - 10ms/step - ia: 0.4576 - loss: 1.2334 - mae: 0.8069 - rmse: 1.1078 - smape: 1.1495 - val_ia: 0.4867 - val_loss: 0.9402 - val_mae: 0.6517 - val_rmse: 0.8532 - val_smape: 1.0238

Epoch 35/128

120/120 - 2s - 13ms/step - ia: 0.4609 - loss: 1.2146 - mae: 0.7992 - rmse: 1.0982 - smape: 1.1447 - val_ia: 0.4895 - val_loss: 0.9228 - val_mae: 0.6454 - val_rmse: 0.8454 - val_smape: 1.0202

Epoch 36/128

120/120 - 2s - 13ms/step - ia: 0.4636 - loss: 1.1865 - mae: 0.7942 - rmse: 1.0869 - smape: 1.1431 - val_ia: 0.4924 - val_loss: 0.9061 - val_mae: 0.6391 - val_rmse: 0.8377 - val_smape: 1.0164

Epoch 37/128

120/120 - 1s - 5ms/step - ia: 0.4651 - loss: 1.1726 - mae: 0.7861 - rmse: 1.0800 - smape: 1.1401 - val_ia: 0.4953 - val_loss: 0.8900 - val_mae: 0.6329 - val_rmse: 0.8300 - val_smape: 1.0124

Epoch 38/128

120/120 - 1s - 5ms/step - ia: 0.4708 - loss: 1.1495 - mae: 0.7775 - rmse: 1.0684 - smape: 1.1308 - val_ia: 0.4981 - val_loss: 0.8735 - val_mae: 0.6268 - val_rmse: 0.8226 - val_smape: 1.0081

Epoch 39/128

120/120 - 1s - 4ms/step - ia: 0.4740 - loss: 1.1270 - mae: 0.7698 - rmse: 1.0594 - smape: 1.1261 - val_ia: 0.5010 - val_loss: 0.8578 - val_mae: 0.6207 - val_rmse: 0.8152 - val_smape: 1.0039

Epoch 40/128

120/120 - 0s - 4ms/step - ia: 0.4750 - loss: 1.1163 - mae: 0.7676 - rmse: 1.0541 - smape: 1.1261 - val_ia: 0.5038 - val_loss: 0.8421 - val_mae: 0.6147 - val_rmse: 0.8080 - val_smape: 0.9993

Epoch 41/128

120/120 - 1s - 7ms/step - ia: 0.4783 - loss: 1.1039 - mae: 0.7614 - rmse: 1.0480 - smape: 1.1220 - val_ia: 0.5066 - val_loss: 0.8265 - val_mae: 0.6088 - val_rmse: 0.8008 - val_smape: 0.9947

Epoch 42/128

120/120 - 1s - 5ms/step - ia: 0.4811 - loss: 1.0888 - mae: 0.7556 - rmse: 1.0399 - smape: 1.1177 - val_ia: 0.5095 - val_loss: 0.8115 - val_mae: 0.6030 - val_rmse: 0.7937 - val_smape: 0.9902

Epoch 43/128

120/120 - 1s - 6ms/step - ia: 0.4816 - loss: 1.0688 - mae: 0.7507 - rmse: 1.0311 - smape: 1.1194 - val_ia: 0.5125 - val_loss: 0.7971 - val_mae: 0.5971 - val_rmse: 0.7865 - val_smape: 0.9859

Epoch 44/128

120/120 - 2s - 16ms/step - ia: 0.4862 - loss: 1.0477 - mae: 0.7418 - rmse: 1.0210 - smape: 1.1110 - val_ia: 0.5155 - val_loss: 0.7832 - val_mae: 0.5915 - val_rmse: 0.7795 - val_smape: 0.9817

Epoch 45/128

120/120 - 1s - 12ms/step - ia: 0.4908 - loss: 1.0313 - mae: 0.7356 - rmse: 1.0128 - smape: 1.1054 - val_ia: 0.5185 - val_loss: 0.7696 - val_mae: 0.5859 - val_rmse: 0.7726 - val_smape: 0.9773

Epoch 46/128

120/120 - 2s - 13ms/step - ia: 0.4923 - loss: 1.0201 - mae: 0.7312 - rmse: 1.0066 - smape: 1.1024 - val_ia: 0.5212 - val_loss: 0.7559 - val_mae: 0.5803 - val_rmse: 0.7659 - val_smape: 0.9728

Epoch 47/128

120/120 - 2s - 14ms/step - ia: 0.4934 - loss: 1.0144 - mae: 0.7282 - rmse: 1.0048 - smape: 1.0998 - val_ia: 0.5242 - val_loss: 0.7428 - val_mae: 0.5748 - val_rmse: 0.7592 - val_smape: 0.9681

Epoch 48/128

120/120 - 2s - 17ms/step - ia: 0.4969 - loss: 0.9878 - mae: 0.7211 - rmse: 0.9906 - smape: 1.0996 - val_ia: 0.5271 - val_loss: 0.7301 - val_mae: 0.5694 - val_rmse: 0.7526 - val_smape: 0.9637

Epoch 49/128

120/120 - 2s - 19ms/step - ia: 0.5018 - loss: 0.9770 - mae: 0.7133 - rmse: 0.9854 - smape: 1.0861 - val_ia: 0.5300 - val_loss: 0.7177 - val_mae: 0.5642 - val_rmse: 0.7460 - val_smape: 0.9597

Epoch 50/128

120/120 - 2s - 13ms/step - ia: 0.5028 - loss: 0.9647 - mae: 0.7105 - rmse: 0.9788 - smape: 1.0868 - val_ia: 0.5329 - val_loss: 0.7058 - val_mae: 0.5590 - val_rmse: 0.7397 - val_smape: 0.9554

Epoch 51/128

120/120 - 1s - 8ms/step - ia: 0.5057 - loss: 0.9541 - mae: 0.7029 - rmse: 0.9744 - smape: 1.0820 - val_ia: 0.5358 - val_loss: 0.6944 - val_mae: 0.5541 - val_rmse: 0.7335 - val_smape: 0.9514

Epoch 52/128

120/120 - 1s - 9ms/step - ia: 0.5081 - loss: 0.9384 - mae: 0.6987 - rmse: 0.9659 - smape: 1.0794 - val_ia: 0.5385 - val_loss: 0.6827 - val_mae: 0.5490 - val_rmse: 0.7274 - val_smape: 0.9468

Epoch 53/128

120/120 - 1s - 12ms/step - ia: 0.5091 - loss: 0.9325 - mae: 0.6960 - rmse: 0.9626 - smape: 1.0785 - val_ia: 0.5413 - val_loss: 0.6717 - val_mae: 0.5441 - val_rmse: 0.7215 - val_smape: 0.9424

Epoch 54/128

120/120 - 1s - 9ms/step - ia: 0.5115 - loss: 0.9238 - mae: 0.6907 - rmse: 0.9583 - smape: 1.0754 - val_ia: 0.5441 - val_loss: 0.6610 - val_mae: 0.5393 - val_rmse: 0.7156 - val_smape: 0.9378

Epoch 55/128

120/120 - 1s - 5ms/step - ia: 0.5151 - loss: 0.9011 - mae: 0.6845 - rmse: 0.9471 - smape: 1.0707 - val_ia: 0.5469 - val_loss: 0.6507 - val_mae: 0.5345 - val_rmse: 0.7098 - val_smape: 0.9332

Epoch 56/128

120/120 - 1s - 8ms/step - ia: 0.5167 - loss: 0.8889 - mae: 0.6796 - rmse: 0.9393 - smape: 1.0684 - val_ia: 0.5498 - val_loss: 0.6408 - val_mae: 0.5299 - val_rmse: 0.7042 - val_smape: 0.9291

Epoch 57/128

120/120 - 1s - 10ms/step - ia: 0.5203 - loss: 0.8818 - mae: 0.6749 - rmse: 0.9349 - smape: 1.0612 - val_ia: 0.5527 - val_loss: 0.6313 - val_mae: 0.5254 - val_rmse: 0.6985 - val_smape: 0.9248

Epoch 58/128

120/120 - 2s - 15ms/step - ia: 0.5245 - loss: 0.8641 - mae: 0.6680 - rmse: 0.9273 - smape: 1.0562 - val_ia: 0.5555 - val_loss: 0.6219 - val_mae: 0.5209 - val_rmse: 0.6931 - val_smape: 0.9205

Epoch 59/128

120/120 - 1s - 9ms/step - ia: 0.5238 - loss: 0.8682 - mae: 0.6689 - rmse: 0.9290 - smape: 1.0599 - val_ia: 0.5582 - val_loss: 0.6127 - val_mae: 0.5166 - val_rmse: 0.6878 - val_smape: 0.9164

Epoch 60/128

120/120 - 2s - 14ms/step - ia: 0.5273 - loss: 0.8460 - mae: 0.6624 - rmse: 0.9170 - smape: 1.0536 - val_ia: 0.5608 - val_loss: 0.6036 - val_mae: 0.5121 - val_rmse: 0.6826 - val_smape: 0.9120

Epoch 61/128

120/120 - 1s - 6ms/step - ia: 0.5302 - loss: 0.8390 - mae: 0.6554 - rmse: 0.9135 - smape: 1.0479 - val_ia: 0.5635 - val_loss: 0.5948 - val_mae: 0.5078 - val_rmse: 0.6775 - val_smape: 0.9077

Epoch 62/128

120/120 - 1s - 9ms/step - ia: 0.5347 - loss: 0.8233 - mae: 0.6483 - rmse: 0.9043 - smape: 1.0413 - val_ia: 0.5662 - val_loss: 0.5865 - val_mae: 0.5036 - val_rmse: 0.6725 - val_smape: 0.9035

Epoch 63/128

120/120 - 2s - 13ms/step - ia: 0.5320 - loss: 0.8252 - mae: 0.6515 - rmse: 0.9059 - smape: 1.0483 - val_ia: 0.5687 - val_loss: 0.5783 - val_mae: 0.4994 - val_rmse: 0.6676 - val_smape: 0.8993

Epoch 64/128

120/120 - 2s - 15ms/step - ia: 0.5364 - loss: 0.8048 - mae: 0.6437 - rmse: 0.8942 - smape: 1.0417 - val_ia: 0.5712 - val_loss: 0.5701 - val_mae: 0.4952 - val_rmse: 0.6628 - val_smape: 0.8949

Epoch 65/128

120/120 - 3s - 21ms/step - ia: 0.5389 - loss: 0.8016 - mae: 0.6397 - rmse: 0.8924 - smape: 1.0351 - val_ia: 0.5737 - val_loss: 0.5626 - val_mae: 0.4913 - val_rmse: 0.6581 - val_smape: 0.8918

Epoch 66/128

120/120 - 1s - 8ms/step - ia: 0.5383 - loss: 0.7964 - mae: 0.6386 - rmse: 0.8895 - smape: 1.0390 - val_ia: 0.5763 - val_loss: 0.5554 - val_mae: 0.4875 - val_rmse: 0.6535 - val_smape: 0.8888

Epoch 67/128

120/120 - 1s - 7ms/step - ia: 0.5424 - loss: 0.7835 - mae: 0.6340 - rmse: 0.8817 - smape: 1.0338 - val_ia: 0.5787 - val_loss: 0.5481 - val_mae: 0.4837 - val_rmse: 0.6490 - val_smape: 0.8849

Epoch 68/128

120/120 - 1s - 6ms/step - ia: 0.5427 - loss: 0.7840 - mae: 0.6306 - rmse: 0.8827 - smape: 1.0321 - val_ia: 0.5812 - val_loss: 0.5413 - val_mae: 0.4801 - val_rmse: 0.6446 - val_smape: 0.8813

Epoch 69/128

120/120 - 1s - 11ms/step - ia: 0.5440 - loss: 0.7747 - mae: 0.6299 - rmse: 0.8780 - smape: 1.0317 - val_ia: 0.5835 - val_loss: 0.5346 - val_mae: 0.4765 - val_rmse: 0.6403 - val_smape: 0.8778

Epoch 70/128

120/120 - 2s - 14ms/step - ia: 0.5456 - loss: 0.7649 - mae: 0.6240 - rmse: 0.8713 - smape: 1.0313 - val_ia: 0.5859 - val_loss: 0.5281 - val_mae: 0.4730 - val_rmse: 0.6362 - val_smape: 0.8744

Epoch 71/128

120/120 - 1s - 8ms/step - ia: 0.5519 - loss: 0.7477 - mae: 0.6162 - rmse: 0.8620 - smape: 1.0214 - val_ia: 0.5881 - val_loss: 0.5218 - val_mae: 0.4695 - val_rmse: 0.6321 - val_smape: 0.8707

Epoch 72/128

120/120 - 2s - 14ms/step - ia: 0.5511 - loss: 0.7443 - mae: 0.6142 - rmse: 0.8605 - smape: 1.0248 - val_ia: 0.5904 - val_loss: 0.5157 - val_mae: 0.4661 - val_rmse: 0.6281 - val_smape: 0.8671

Epoch 73/128

120/120 - 2s - 15ms/step - ia: 0.5550 - loss: 0.7323 - mae: 0.6096 - rmse: 0.8528 - smape: 1.0186 - val_ia: 0.5926 - val_loss: 0.5098 - val_mae: 0.4628 - val_rmse: 0.6243 - val_smape: 0.8631

Epoch 74/128

120/120 - 2s - 17ms/step - ia: 0.5576 - loss: 0.7251 - mae: 0.6066 - rmse: 0.8489 - smape: 1.0128 - val_ia: 0.5947 - val_loss: 0.5040 - val_mae: 0.4596 - val_rmse: 0.6204 - val_smape: 0.8596

Epoch 75/128

120/120 - 1s - 12ms/step - ia: 0.5578 - loss: 0.7210 - mae: 0.6051 - rmse: 0.8460 - smape: 1.0137 - val_ia: 0.5968 - val_loss: 0.4985 - val_mae: 0.4564 - val_rmse: 0.6167 - val_smape: 0.8561

Epoch 76/128

120/120 - 1s - 5ms/step - ia: 0.5611 - loss: 0.7126 - mae: 0.5997 - rmse: 0.8402 - smape: 1.0092 - val_ia: 0.5989 - val_loss: 0.4931 - val_mae: 0.4534 - val_rmse: 0.6131 - val_smape: 0.8526

Epoch 77/128

120/120 - 1s - 6ms/step - ia: 0.5611 - loss: 0.7105 - mae: 0.5983 - rmse: 0.8403 - smape: 1.0092 - val_ia: 0.6009 - val_loss: 0.4878 - val_mae: 0.4503 - val_rmse: 0.6096 - val_smape: 0.8488

Epoch 78/128

120/120 - 1s - 6ms/step - ia: 0.5628 - loss: 0.7035 - mae: 0.5950 - rmse: 0.8349 - smape: 1.0073 - val_ia: 0.6029 - val_loss: 0.4828 - val_mae: 0.4475 - val_rmse: 0.6062 - val_smape: 0.8457

Epoch 79/128

120/120 - 1s - 5ms/step - ia: 0.5660 - loss: 0.6930 - mae: 0.5908 - rmse: 0.8290 - smape: 1.0032 - val_ia: 0.6048 - val_loss: 0.4780 - val_mae: 0.4446 - val_rmse: 0.6029 - val_smape: 0.8428

Epoch 80/128

120/120 - 1s - 4ms/step - ia: 0.5677 - loss: 0.6819 - mae: 0.5872 - rmse: 0.8227 - smape: 1.0008 - val_ia: 0.6067 - val_loss: 0.4731 - val_mae: 0.4419 - val_rmse: 0.5996 - val_smape: 0.8395

Epoch 81/128

120/120 - 1s - 4ms/step - ia: 0.5670 - loss: 0.6843 - mae: 0.5873 - rmse: 0.8233 - smape: 1.0035 - val_ia: 0.6086 - val_loss: 0.4686 - val_mae: 0.4393 - val_rmse: 0.5965 - val_smape: 0.8365

Epoch 82/128

120/120 - 0s - 4ms/step - ia: 0.5669 - loss: 0.6827 - mae: 0.5865 - rmse: 0.8231 - smape: 1.0066 - val_ia: 0.6104 - val_loss: 0.4643 - val_mae: 0.4368 - val_rmse: 0.5935 - val_smape: 0.8338

Epoch 83/128

120/120 - 0s - 3ms/step - ia: 0.5712 - loss: 0.6722 - mae: 0.5800 - rmse: 0.8174 - smape: 0.9965 - val_ia: 0.6122 - val_loss: 0.4601 - val_mae: 0.4343 - val_rmse: 0.5905 - val_smape: 0.8312

Epoch 84/128

120/120 - 1s - 4ms/step - ia: 0.5727 - loss: 0.6699 - mae: 0.5797 - rmse: 0.8159 - smape: 0.9953 - val_ia: 0.6139 - val_loss: 0.4556 - val_mae: 0.4317 - val_rmse: 0.5875 - val_smape: 0.8280

Epoch 85/128

120/120 - 1s - 6ms/step - ia: 0.5751 - loss: 0.6574 - mae: 0.5747 - rmse: 0.8081 - smape: 0.9943 - val_ia: 0.6157 - val_loss: 0.4516 - val_mae: 0.4293 - val_rmse: 0.5846 - val_smape: 0.8251

Epoch 86/128

120/120 - 1s - 6ms/step - ia: 0.5731 - loss: 0.6618 - mae: 0.5770 - rmse: 0.8105 - smape: 0.9969 - val_ia: 0.6174 - val_loss: 0.4474 - val_mae: 0.4267 - val_rmse: 0.5817 - val_smape: 0.8220

Epoch 87/128

120/120 - 0s - 4ms/step - ia: 0.5748 - loss: 0.6613 - mae: 0.5737 - rmse: 0.8098 - smape: 0.9965 - val_ia: 0.6191 - val_loss: 0.4435 - val_mae: 0.4244 - val_rmse: 0.5789 - val_smape: 0.8195

Epoch 88/128

120/120 - 1s - 6ms/step - ia: 0.5781 - loss: 0.6477 - mae: 0.5693 - rmse: 0.8018 - smape: 0.9907 - val_ia: 0.6207 - val_loss: 0.4399 - val_mae: 0.4223 - val_rmse: 0.5764 - val_smape: 0.8177

Epoch 89/128

120/120 - 0s - 3ms/step - ia: 0.5777 - loss: 0.6451 - mae: 0.5675 - rmse: 0.8003 - smape: 0.9935 - val_ia: 0.6223 - val_loss: 0.4362 - val_mae: 0.4201 - val_rmse: 0.5737 - val_smape: 0.8153

Epoch 90/128

120/120 - 0s - 4ms/step - ia: 0.5802 - loss: 0.6383 - mae: 0.5647 - rmse: 0.7958 - smape: 0.9895 - val_ia: 0.6238 - val_loss: 0.4328 - val_mae: 0.4181 - val_rmse: 0.5713 - val_smape: 0.8134

Epoch 91/128

120/120 - 1s - 10ms/step - ia: 0.5817 - loss: 0.6366 - mae: 0.5622 - rmse: 0.7938 - smape: 0.9836 - val_ia: 0.6253 - val_loss: 0.4293 - val_mae: 0.4161 - val_rmse: 0.5688 - val_smape: 0.8110

Epoch 92/128

120/120 - 2s - 15ms/step - ia: 0.5824 - loss: 0.6343 - mae: 0.5604 - rmse: 0.7924 - smape: 0.9842 - val_ia: 0.6268 - val_loss: 0.4259 - val_mae: 0.4141 - val_rmse: 0.5664 - val_smape: 0.8088

Epoch 93/128

120/120 - 1s - 8ms/step - ia: 0.5848 - loss: 0.6213 - mae: 0.5575 - rmse: 0.7852 - smape: 0.9816 - val_ia: 0.6282 - val_loss: 0.4227 - val_mae: 0.4122 - val_rmse: 0.5641 - val_smape: 0.8067

Epoch 94/128

120/120 - 1s - 7ms/step - ia: 0.5851 - loss: 0.6218 - mae: 0.5572 - rmse: 0.7855 - smape: 0.9829 - val_ia: 0.6295 - val_loss: 0.4195 - val_mae: 0.4103 - val_rmse: 0.5618 - val_smape: 0.8046

Epoch 95/128

120/120 - 1s - 12ms/step - ia: 0.5868 - loss: 0.6146 - mae: 0.5535 - rmse: 0.7817 - smape: 0.9791 - val_ia: 0.6307 - val_loss: 0.4165 - val_mae: 0.4087 - val_rmse: 0.5597 - val_smape: 0.8031

Epoch 96/128

120/120 - 2s - 15ms/step - ia: 0.5847 - loss: 0.6188 - mae: 0.5556 - rmse: 0.7841 - smape: 0.9857 - val_ia: 0.6322 - val_loss: 0.4133 - val_mae: 0.4067 - val_rmse: 0.5574 - val_smape: 0.8006

Epoch 97/128

120/120 - 1s - 12ms/step - ia: 0.5890 - loss: 0.6121 - mae: 0.5503 - rmse: 0.7791 - smape: 0.9785 - val_ia: 0.6334 - val_loss: 0.4105 - val_mae: 0.4051 - val_rmse: 0.5553 - val_smape: 0.7991

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 17s - 18ms/step - ia: 0.4675 - loss: 0.7290 - mae: 0.6149 - rmse: 0.8228 - smape: 1.1666 - val_ia: 0.4877 - val_loss: 0.2828 - val_mae: 0.3495 - val_rmse: 0.4384 - val_smape: 0.7387

Epoch 2/32

958/958 - 4s - 5ms/step - ia: 0.6968 - loss: 0.3537 - mae: 0.4237 - rmse: 0.5784 - smape: 0.8130 - val_ia: 0.5968 - val_loss: 0.1745 - val_mae: 0.2565 - val_rmse: 0.3379 - val_smape: 0.5700

Epoch 3/32

958/958 - 4s - 4ms/step - ia: 0.7464 - loss: 0.2557 - mae: 0.3546 - rmse: 0.4887 - smape: 0.7211 - val_ia: 0.6251 - val_loss: 0.1305 - val_mae: 0.2251 - val_rmse: 0.2999 - val_smape: 0.5243

Epoch 4/32

958/958 - 5s - 5ms/step - ia: 0.7736 - loss: 0.2023 - mae: 0.3132 - rmse: 0.4351 - smape: 0.6659 - val_ia: 0.6469 - val_loss: 0.1137 - val_mae: 0.2105 - val_rmse: 0.2825 - val_smape: 0.5069

Epoch 5/32

958/958 - 5s - 5ms/step - ia: 0.7869 - loss: 0.1782 - mae: 0.2932 - rmse: 0.4075 - smape: 0.6391 - val_ia: 0.6455 - val_loss: 0.1018 - val_mae: 0.2046 - val_rmse: 0.2733 - val_smape: 0.4913

Epoch 6/32

958/958 - 5s - 6ms/step - ia: 0.7987 - loss: 0.1629 - mae: 0.2775 - rmse: 0.3871 - smape: 0.6150 - val_ia: 0.6567 - val_loss: 0.0957 - val_mae: 0.1973 - val_rmse: 0.2648 - val_smape: 0.4837

Epoch 7/32

958/958 - 6s - 6ms/step - ia: 0.8083 - loss: 0.1506 - mae: 0.2647 - rmse: 0.3727 - smape: 0.5966 - val_ia: 0.6618 - val_loss: 0.0912 - val_mae: 0.1933 - val_rmse: 0.2601 - val_smape: 0.4714

Epoch 8/32

958/958 - 5s - 6ms/step - ia: 0.8137 - loss: 0.1424 - mae: 0.2573 - rmse: 0.3614 - smape: 0.5846 - val_ia: 0.6765 - val_loss: 0.0862 - val_mae: 0.1853 - val_rmse: 0.2512 - val_smape: 0.4592

Epoch 9/32

958/958 - 5s - 5ms/step - ia: 0.8184 - loss: 0.1393 - mae: 0.2514 - rmse: 0.3571 - smape: 0.5735 - val_ia: 0.6870 - val_loss: 0.0829 - val_mae: 0.1797 - val_rmse: 0.2451 - val_smape: 0.4498

Epoch 10/32

958/958 - 6s - 6ms/step - ia: 0.8241 - loss: 0.1322 - mae: 0.2451 - rmse: 0.3483 - smape: 0.5595 - val_ia: 0.6914 - val_loss: 0.0829 - val_mae: 0.1796 - val_rmse: 0.2436 - val_smape: 0.4541

Epoch 11/32

958/958 - 5s - 6ms/step - ia: 0.8276 - loss: 0.1265 - mae: 0.2394 - rmse: 0.3394 - smape: 0.5506 - val_ia: 0.7028 - val_loss: 0.0778 - val_mae: 0.1716 - val_rmse: 0.2370 - val_smape: 0.4360

Epoch 12/32

958/958 - 5s - 5ms/step - ia: 0.8310 - loss: 0.1240 - mae: 0.2350 - rmse: 0.3355 - smape: 0.5429 - val_ia: 0.7125 - val_loss: 0.0754 - val_mae: 0.1672 - val_rmse: 0.2327 - val_smape: 0.4282

Epoch 13/32

958/958 - 6s - 6ms/step - ia: 0.8333 - loss: 0.1214 - mae: 0.2324 - rmse: 0.3325 - smape: 0.5375 - val_ia: 0.7044 - val_loss: 0.0756 - val_mae: 0.1701 - val_rmse: 0.2340 - val_smape: 0.4315

Epoch 14/32

958/958 - 14s - 14ms/step - ia: 0.8386 - loss: 0.1148 - mae: 0.2254 - rmse: 0.3222 - smape: 0.5264 - val_ia: 0.7032 - val_loss: 0.0750 - val_mae: 0.1706 - val_rmse: 0.2326 - val_smape: 0.4274

Epoch 15/32

958/958 - 6s - 6ms/step - ia: 0.8406 - loss: 0.1134 - mae: 0.2229 - rmse: 0.3203 - smape: 0.5183 - val_ia: 0.7052 - val_loss: 0.0723 - val_mae: 0.1677 - val_rmse: 0.2294 - val_smape: 0.4235

Epoch 16/32

958/958 - 5s - 6ms/step - ia: 0.8433 - loss: 0.1108 - mae: 0.2195 - rmse: 0.3161 - smape: 0.5109 - val_ia: 0.7098 - val_loss: 0.0735 - val_mae: 0.1680 - val_rmse: 0.2296 - val_smape: 0.4196

Epoch 17/32

958/958 - 11s - 11ms/step - ia: 0.8446 - loss: 0.1094 - mae: 0.2178 - rmse: 0.3140 - smape: 0.5057 - val_ia: 0.7216 - val_loss: 0.0702 - val_mae: 0.1614 - val_rmse: 0.2240 - val_smape: 0.4091

Epoch 18/32

958/958 - 4s - 4ms/step - ia: 0.8465 - loss: 0.1070 - mae: 0.2157 - rmse: 0.3107 - smape: 0.5045 - val_ia: 0.7116 - val_loss: 0.0747 - val_mae: 0.1691 - val_rmse: 0.2305 - val_smape: 0.4158

Epoch 19/32

958/958 - 5s - 5ms/step - ia: 0.8494 - loss: 0.1046 - mae: 0.2114 - rmse: 0.3067 - smape: 0.4913 - val_ia: 0.7264 - val_loss: 0.0672 - val_mae: 0.1570 - val_rmse: 0.2199 - val_smape: 0.3986

Epoch 20/32

958/958 - 5s - 5ms/step - ia: 0.8499 - loss: 0.1040 - mae: 0.2101 - rmse: 0.3050 - smape: 0.4892 - val_ia: 0.7329 - val_loss: 0.0665 - val_mae: 0.1542 - val_rmse: 0.2181 - val_smape: 0.3929

Epoch 21/32

958/958 - 5s - 5ms/step - ia: 0.8513 - loss: 0.1021 - mae: 0.2094 - rmse: 0.3029 - smape: 0.4888 - val_ia: 0.7384 - val_loss: 0.0671 - val_mae: 0.1545 - val_rmse: 0.2179 - val_smape: 0.3918

Epoch 22/32

958/958 - 6s - 6ms/step - ia: 0.8526 - loss: 0.1006 - mae: 0.2074 - rmse: 0.3005 - smape: 0.4845 - val_ia: 0.7288 - val_loss: 0.0668 - val_mae: 0.1568 - val_rmse: 0.2187 - val_smape: 0.3931

Epoch 23/32

958/958 - 9s - 9ms/step - ia: 0.8535 - loss: 0.0998 - mae: 0.2066 - rmse: 0.3000 - smape: 0.4840 - val_ia: 0.7296 - val_loss: 0.0653 - val_mae: 0.1546 - val_rmse: 0.2165 - val_smape: 0.3899

Epoch 24/32

958/958 - 5s - 5ms/step - ia: 0.8555 - loss: 0.0974 - mae: 0.2037 - rmse: 0.2955 - smape: 0.4781 - val_ia: 0.7319 - val_loss: 0.0655 - val_mae: 0.1546 - val_rmse: 0.2166 - val_smape: 0.3891

Epoch 25/32

958/958 - 5s - 5ms/step - ia: 0.8554 - loss: 0.0984 - mae: 0.2031 - rmse: 0.2967 - smape: 0.4757 - val_ia: 0.7440 - val_loss: 0.0651 - val_mae: 0.1517 - val_rmse: 0.2145 - val_smape: 0.3882

Epoch 26/32

958/958 - 5s - 5ms/step - ia: 0.8575 - loss: 0.0964 - mae: 0.2013 - rmse: 0.2931 - smape: 0.4718 - val_ia: 0.7293 - val_loss: 0.0652 - val_mae: 0.1554 - val_rmse: 0.2166 - val_smape: 0.3889

Epoch 27/32

958/958 - 5s - 6ms/step - ia: 0.8577 - loss: 0.0966 - mae: 0.2003 - rmse: 0.2938 - smape: 0.4719 - val_ia: 0.7418 - val_loss: 0.0639 - val_mae: 0.1507 - val_rmse: 0.2129 - val_smape: 0.3822

Epoch 28/32

958/958 - 5s - 5ms/step - ia: 0.8587 - loss: 0.0954 - mae: 0.1992 - rmse: 0.2911 - smape: 0.4690 - val_ia: 0.7412 - val_loss: 0.0630 - val_mae: 0.1496 - val_rmse: 0.2117 - val_smape: 0.3810

Epoch 29/32

958/958 - 5s - 5ms/step - ia: 0.8596 - loss: 0.0956 - mae: 0.1982 - rmse: 0.2916 - smape: 0.4673 - val_ia: 0.7381 - val_loss: 0.0633 - val_mae: 0.1512 - val_rmse: 0.2125 - val_smape: 0.3833

Epoch 30/32

958/958 - 6s - 6ms/step - ia: 0.8608 - loss: 0.0943 - mae: 0.1969 - rmse: 0.2885 - smape: 0.4642 - val_ia: 0.7371 - val_loss: 0.0622 - val_mae: 0.1496 - val_rmse: 0.2116 - val_smape: 0.3806

Epoch 31/32

958/958 - 5s - 5ms/step - ia: 0.8618 - loss: 0.0927 - mae: 0.1958 - rmse: 0.2867 - smape: 0.4602 - val_ia: 0.7453 - val_loss: 0.0623 - val_mae: 0.1482 - val_rmse: 0.2101 - val_smape: 0.3785

Epoch 32/32

958/958 - 4s - 5ms/step - ia: 0.8619 - loss: 0.0918 - mae: 0.1952 - rmse: 0.2857 - smape: 0.4606 - val_ia: 0.7459 - val_loss: 0.0616 - val_mae: 0.1471 - val_rmse: 0.2091 - val_smape: 0.3768

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:16 569ms/step
  2/136 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

100%|██████████| 50/50 [4:49:31<00:00, 347.44s/trial, best loss: 0.03740939164650774]
{'activation': 1, 'batch': 2, 'dropout': 0.1, 'epochs': 4, 'layers': 1.0, 'learning_rate': 0.0001524958564276629, 'units': 4}

In [24]:
print(best)

{'activation': 1, 'batch': 2, 'dropout': 0.1, 'epochs': 4, 'layers': 1.0, 'learning_rate': 0.0001524958564276629, 'units': 4}