Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\Desktop\\pruebas_collab\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 24
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [16]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 12, 6)
Las dimensiones de testX son:  (8797, 12, 6)
Las dimensiones de valX son:  (4333, 12, 6)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 61s - 64ms/step - ia: 0.2709 - loss: 0.9545 - mae: 0.7350 - rmse: 0.9563 - smape: 1.4958 - val_ia: 0.2460 - val_loss: 0.8096 - val_mae: 0.6709 - val_rmse: 0.7570 - val_smape: 1.4127

Epoch 2/128

958/958 - 23s - 24ms/step - ia: 0.3115 - loss: 0.8886 - mae: 0.7019 - rmse: 0.9244 - smape: 1.4277 - val_ia: 0.2498 - val_loss: 0.7889 - val_mae: 0.6623 - val_rmse: 0.7517 - val_smape: 1.3544

Epoch 3/128

958/958 - 19s - 20ms/step - ia: 0.3278 - loss: 0.8708 - mae: 0.6940 - rmse: 0.9152 - smape: 1.4021 - val_ia: 0.2491 - val_loss: 0.7961 - val_mae: 0.6679 - val_rmse: 0.7568 - val_smape: 1.3859

Epoch 4/128

958/958 - 32s - 34ms/step - ia: 0.3362 - loss: 0.8622 - mae: 0.6879 - rmse: 0.9099 - smape: 1.3847 - val_ia: 0.2503 - val_loss: 0.7816 - val_mae: 0.6595 - val_rmse: 0.7503 - val_smape: 1.3423

Epoch 5/128

958/958 - 31s - 32ms/step - ia: 0.3454 - loss: 0.8524 - mae: 0.6844 - rmse: 0.9053 - smape: 1.3685 - val_ia: 0.2507 - val_loss: 0.7771 - val_mae: 0.6540 - val_rmse: 0.7440 - val_smape: 1.3309

Epoch 6/128

958/958 - 21s - 22ms/step - ia: 0.3521 - loss: 0.8441 - mae: 0.6810 - rmse: 0.9009 - smape: 1.3555 - val_ia: 0.2516 - val_loss: 0.7728 - val_mae: 0.6547 - val_rmse: 0.7446 - val_smape: 1.3399

Epoch 7/128

958/958 - 23s - 24ms/step - ia: 0.3590 - loss: 0.8397 - mae: 0.6772 - rmse: 0.8975 - smape: 1.3455 - val_ia: 0.2512 - val_loss: 0.7699 - val_mae: 0.6512 - val_rmse: 0.7413 - val_smape: 1.3280

Epoch 8/128

958/958 - 22s - 23ms/step - ia: 0.3586 - loss: 0.8359 - mae: 0.6762 - rmse: 0.8959 - smape: 1.3456 - val_ia: 0.2535 - val_loss: 0.7654 - val_mae: 0.6541 - val_rmse: 0.7458 - val_smape: 1.3185

Epoch 9/128

958/958 - 21s - 22ms/step - ia: 0.3653 - loss: 0.8318 - mae: 0.6730 - rmse: 0.8935 - smape: 1.3302 - val_ia: 0.2528 - val_loss: 0.7620 - val_mae: 0.6442 - val_rmse: 0.7346 - val_smape: 1.2959

Epoch 10/128

958/958 - 41s - 42ms/step - ia: 0.3690 - loss: 0.8266 - mae: 0.6700 - rmse: 0.8908 - smape: 1.3275 - val_ia: 0.2523 - val_loss: 0.7697 - val_mae: 0.6514 - val_rmse: 0.7431 - val_smape: 1.3151

Epoch 11/128

958/958 - 27s - 28ms/step - ia: 0.3681 - loss: 0.8269 - mae: 0.6713 - rmse: 0.8901 - smape: 1.3281 - val_ia: 0.2538 - val_loss: 0.7662 - val_mae: 0.6479 - val_rmse: 0.7375 - val_smape: 1.3281

Epoch 12/128

958/958 - 25s - 26ms/step - ia: 0.3707 - loss: 0.8212 - mae: 0.6673 - rmse: 0.8870 - smape: 1.3238 - val_ia: 0.2553 - val_loss: 0.7652 - val_mae: 0.6512 - val_rmse: 0.7442 - val_smape: 1.3006

Epoch 13/128

958/958 - 25s - 26ms/step - ia: 0.3776 - loss: 0.8147 - mae: 0.6651 - rmse: 0.8830 - smape: 1.3157 - val_ia: 0.2568 - val_loss: 0.7635 - val_mae: 0.6507 - val_rmse: 0.7447 - val_smape: 1.2910

Epoch 14/128

958/958 - 27s - 28ms/step - ia: 0.3792 - loss: 0.8136 - mae: 0.6639 - rmse: 0.8830 - smape: 1.3120 - val_ia: 0.2558 - val_loss: 0.7635 - val_mae: 0.6462 - val_rmse: 0.7390 - val_smape: 1.2922

Epoch 15/128

958/958 - 37s - 38ms/step - ia: 0.3765 - loss: 0.8146 - mae: 0.6654 - rmse: 0.8843 - smape: 1.3190 - val_ia: 0.2562 - val_loss: 0.7632 - val_mae: 0.6479 - val_rmse: 0.7397 - val_smape: 1.3034

Epoch 16/128

958/958 - 21s - 22ms/step - ia: 0.3798 - loss: 0.8122 - mae: 0.6629 - rmse: 0.8823 - smape: 1.3110 - val_ia: 0.2585 - val_loss: 0.7604 - val_mae: 0.6439 - val_rmse: 0.7386 - val_smape: 1.2670

Epoch 17/128

958/958 - 25s - 26ms/step - ia: 0.3858 - loss: 0.8069 - mae: 0.6606 - rmse: 0.8802 - smape: 1.3002 - val_ia: 0.2584 - val_loss: 0.7713 - val_mae: 0.6547 - val_rmse: 0.7500 - val_smape: 1.2900

Epoch 18/128

958/958 - 22s - 23ms/step - ia: 0.3842 - loss: 0.8064 - mae: 0.6601 - rmse: 0.8796 - smape: 1.3036 - val_ia: 0.2591 - val_loss: 0.7545 - val_mae: 0.6377 - val_rmse: 0.7300 - val_smape: 1.2723

Epoch 19/128

958/958 - 19s - 20ms/step - ia: 0.3834 - loss: 0.8088 - mae: 0.6600 - rmse: 0.8813 - smape: 1.3009 - val_ia: 0.2599 - val_loss: 0.7646 - val_mae: 0.6482 - val_rmse: 0.7436 - val_smape: 1.2705

Epoch 20/128

958/958 - 23s - 24ms/step - ia: 0.3878 - loss: 0.8042 - mae: 0.6596 - rmse: 0.8787 - smape: 1.2972 - val_ia: 0.2615 - val_loss: 0.7575 - val_mae: 0.6418 - val_rmse: 0.7368 - val_smape: 1.2635

Epoch 21/128

958/958 - 24s - 25ms/step - ia: 0.3884 - loss: 0.7998 - mae: 0.6579 - rmse: 0.8766 - smape: 1.2973 - val_ia: 0.2596 - val_loss: 0.7599 - val_mae: 0.6445 - val_rmse: 0.7378 - val_smape: 1.2848

Epoch 22/128

958/958 - 26s - 27ms/step - ia: 0.3918 - loss: 0.7989 - mae: 0.6566 - rmse: 0.8758 - smape: 1.2932 - val_ia: 0.2615 - val_loss: 0.7531 - val_mae: 0.6397 - val_rmse: 0.7318 - val_smape: 1.2832

Epoch 23/128

958/958 - 22s - 23ms/step - ia: 0.3893 - loss: 0.8040 - mae: 0.6577 - rmse: 0.8784 - smape: 1.2941 - val_ia: 0.2614 - val_loss: 0.7559 - val_mae: 0.6429 - val_rmse: 0.7352 - val_smape: 1.2875

Epoch 24/128

958/958 - 22s - 23ms/step - ia: 0.3914 - loss: 0.7982 - mae: 0.6562 - rmse: 0.8758 - smape: 1.2884 - val_ia: 0.2623 - val_loss: 0.7575 - val_mae: 0.6464 - val_rmse: 0.7394 - val_smape: 1.2904

Epoch 25/128

958/958 - 23s - 24ms/step - ia: 0.3922 - loss: 0.7976 - mae: 0.6553 - rmse: 0.8752 - smape: 1.2859 - val_ia: 0.2623 - val_loss: 0.7562 - val_mae: 0.6421 - val_rmse: 0.7358 - val_smape: 1.2745

Epoch 26/128

958/958 - 22s - 22ms/step - ia: 0.3940 - loss: 0.7944 - mae: 0.6539 - rmse: 0.8722 - smape: 1.2871 - val_ia: 0.2635 - val_loss: 0.7559 - val_mae: 0.6396 - val_rmse: 0.7350 - val_smape: 1.2599

Epoch 27/128

958/958 - 24s - 25ms/step - ia: 0.3953 - loss: 0.7942 - mae: 0.6551 - rmse: 0.8733 - smape: 1.2857 - val_ia: 0.2629 - val_loss: 0.7582 - val_mae: 0.6455 - val_rmse: 0.7395 - val_smape: 1.2812

Epoch 28/128

958/958 - 23s - 24ms/step - ia: 0.3933 - loss: 0.7975 - mae: 0.6552 - rmse: 0.8738 - smape: 1.2843 - val_ia: 0.2656 - val_loss: 0.7516 - val_mae: 0.6380 - val_rmse: 0.7333 - val_smape: 1.2530

Epoch 29/128

958/958 - 23s - 24ms/step - ia: 0.3956 - loss: 0.7954 - mae: 0.6544 - rmse: 0.8728 - smape: 1.2829 - val_ia: 0.2653 - val_loss: 0.7540 - val_mae: 0.6381 - val_rmse: 0.7338 - val_smape: 1.2493

Epoch 30/128

958/958 - 20s - 21ms/step - ia: 0.3957 - loss: 0.7922 - mae: 0.6544 - rmse: 0.8712 - smape: 1.2820 - val_ia: 0.2632 - val_loss: 0.7570 - val_mae: 0.6427 - val_rmse: 0.7363 - val_smape: 1.2732

Epoch 31/128

958/958 - 17s - 18ms/step - ia: 0.3961 - loss: 0.7916 - mae: 0.6533 - rmse: 0.8714 - smape: 1.2801 - val_ia: 0.2646 - val_loss: 0.7522 - val_mae: 0.6401 - val_rmse: 0.7328 - val_smape: 1.2770

Epoch 32/128

958/958 - 18s - 19ms/step - ia: 0.3951 - loss: 0.7937 - mae: 0.6542 - rmse: 0.8725 - smape: 1.2789 - val_ia: 0.2660 - val_loss: 0.7547 - val_mae: 0.6389 - val_rmse: 0.7347 - val_smape: 1.2509

Epoch 33/128

958/958 - 15s - 16ms/step - ia: 0.3970 - loss: 0.7909 - mae: 0.6523 - rmse: 0.8728 - smape: 1.2772 - val_ia: 0.2653 - val_loss: 0.7553 - val_mae: 0.6400 - val_rmse: 0.7351 - val_smape: 1.2580

Epoch 34/128

958/958 - 17s - 17ms/step - ia: 0.4001 - loss: 0.7866 - mae: 0.6510 - rmse: 0.8684 - smape: 1.2765 - val_ia: 0.2668 - val_loss: 0.7593 - val_mae: 0.6439 - val_rmse: 0.7401 - val_smape: 1.2620

Epoch 35/128

958/958 - 19s - 20ms/step - ia: 0.4009 - loss: 0.7867 - mae: 0.6501 - rmse: 0.8684 - smape: 1.2735 - val_ia: 0.2663 - val_loss: 0.7534 - val_mae: 0.6365 - val_rmse: 0.7319 - val_smape: 1.2448

Epoch 36/128

958/958 - 15s - 16ms/step - ia: 0.3991 - loss: 0.7877 - mae: 0.6522 - rmse: 0.8694 - smape: 1.2746 - val_ia: 0.2683 - val_loss: 0.7470 - val_mae: 0.6342 - val_rmse: 0.7291 - val_smape: 1.2484

Epoch 37/128

958/958 - 19s - 20ms/step - ia: 0.4022 - loss: 0.7840 - mae: 0.6496 - rmse: 0.8666 - smape: 1.2721 - val_ia: 0.2681 - val_loss: 0.7516 - val_mae: 0.6351 - val_rmse: 0.7314 - val_smape: 1.2377

Epoch 38/128

958/958 - 16s - 17ms/step - ia: 0.4014 - loss: 0.7870 - mae: 0.6508 - rmse: 0.8682 - smape: 1.2714 - val_ia: 0.2660 - val_loss: 0.7489 - val_mae: 0.6385 - val_rmse: 0.7312 - val_smape: 1.2705

Epoch 39/128

958/958 - 17s - 18ms/step - ia: 0.3986 - loss: 0.7882 - mae: 0.6510 - rmse: 0.8703 - smape: 1.2730 - val_ia: 0.2691 - val_loss: 0.7530 - val_mae: 0.6354 - val_rmse: 0.7322 - val_smape: 1.2323

Epoch 40/128

958/958 - 22s - 23ms/step - ia: 0.3995 - loss: 0.7854 - mae: 0.6514 - rmse: 0.8686 - smape: 1.2757 - val_ia: 0.2699 - val_loss: 0.7554 - val_mae: 0.6359 - val_rmse: 0.7333 - val_smape: 1.2332

Epoch 41/128

958/958 - 18s - 19ms/step - ia: 0.4044 - loss: 0.7791 - mae: 0.6473 - rmse: 0.8657 - smape: 1.2639 - val_ia: 0.2688 - val_loss: 0.7494 - val_mae: 0.6356 - val_rmse: 0.7315 - val_smape: 1.2432

Epoch 42/128

958/958 - 23s - 24ms/step - ia: 0.4035 - loss: 0.7814 - mae: 0.6486 - rmse: 0.8667 - smape: 1.2683 - val_ia: 0.2673 - val_loss: 0.7505 - val_mae: 0.6361 - val_rmse: 0.7305 - val_smape: 1.2518

Epoch 43/128

958/958 - 45s - 47ms/step - ia: 0.3995 - loss: 0.7855 - mae: 0.6509 - rmse: 0.8691 - smape: 1.2737 - val_ia: 0.2687 - val_loss: 0.7504 - val_mae: 0.6358 - val_rmse: 0.7310 - val_smape: 1.2467

Epoch 44/128

958/958 - 27s - 28ms/step - ia: 0.4020 - loss: 0.7811 - mae: 0.6499 - rmse: 0.8665 - smape: 1.2699 - val_ia: 0.2675 - val_loss: 0.7535 - val_mae: 0.6394 - val_rmse: 0.7339 - val_smape: 1.2572

Epoch 45/128

958/958 - 27s - 29ms/step - ia: 0.4042 - loss: 0.7788 - mae: 0.6487 - rmse: 0.8635 - smape: 1.2706 - val_ia: 0.2691 - val_loss: 0.7474 - val_mae: 0.6349 - val_rmse: 0.7300 - val_smape: 1.2459

Epoch 46/128

958/958 - 27s - 28ms/step - ia: 0.4050 - loss: 0.7809 - mae: 0.6485 - rmse: 0.8667 - smape: 1.2643 - val_ia: 0.2686 - val_loss: 0.7531 - val_mae: 0.6393 - val_rmse: 0.7348 - val_smape: 1.2545

Epoch 47/128

958/958 - 23s - 24ms/step - ia: 0.4067 - loss: 0.7752 - mae: 0.6468 - rmse: 0.8619 - smape: 1.2662 - val_ia: 0.2672 - val_loss: 0.7569 - val_mae: 0.6404 - val_rmse: 0.7364 - val_smape: 1.2449

Epoch 48/128

958/958 - 27s - 28ms/step - ia: 0.4025 - loss: 0.7765 - mae: 0.6485 - rmse: 0.8646 - smape: 1.2693 - val_ia: 0.2726 - val_loss: 0.7488 - val_mae: 0.6364 - val_rmse: 0.7334 - val_smape: 1.2429

Epoch 49/128

958/958 - 25s - 26ms/step - ia: 0.4075 - loss: 0.7772 - mae: 0.6474 - rmse: 0.8633 - smape: 1.2626 - val_ia: 0.2691 - val_loss: 0.7523 - val_mae: 0.6348 - val_rmse: 0.7307 - val_smape: 1.2378

Epoch 50/128

958/958 - 24s - 25ms/step - ia: 0.4049 - loss: 0.7787 - mae: 0.6474 - rmse: 0.8644 - smape: 1.2655 - val_ia: 0.2714 - val_loss: 0.7574 - val_mae: 0.6366 - val_rmse: 0.7350 - val_smape: 1.2251

Epoch 51/128

958/958 - 19s - 19ms/step - ia: 0.4068 - loss: 0.7761 - mae: 0.6461 - rmse: 0.8632 - smape: 1.2611 - val_ia: 0.2719 - val_loss: 0.7571 - val_mae: 0.6368 - val_rmse: 0.7347 - val_smape: 1.2272

Epoch 51: early stopping

Restoring model weights from the end of the best epoch: 36.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:50 821ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step

  2%|▏         | 1/50 [20:39<16:52:25, 1239.71s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

120/120 - 52s - 433ms/step - ia: 0.3223 - loss: 0.8546 - mae: 0.6816 - rmse: 0.9212 - smape: 1.3849 - val_ia: 0.3292 - val_loss: 0.8074 - val_mae: 0.6810 - val_rmse: 0.8409 - val_smape: 1.3433

Epoch 2/16

120/120 - 11s - 93ms/step - ia: 0.4086 - loss: 0.7937 - mae: 0.6500 - rmse: 0.8880 - smape: 1.2460 - val_ia: 0.3384 - val_loss: 0.7580 - val_mae: 0.6398 - val_rmse: 0.8035 - val_smape: 1.2824

Epoch 3/16

120/120 - 13s - 109ms/step - ia: 0.4218 - loss: 0.7768 - mae: 0.6414 - rmse: 0.8793 - smape: 1.2287 - val_ia: 0.3525 - val_loss: 0.8028 - val_mae: 0.6718 - val_rmse: 0.8406 - val_smape: 1.3069

Epoch 4/16

120/120 - 15s - 128ms/step - ia: 0.4370 - loss: 0.7601 - mae: 0.6326 - rmse: 0.8691 - smape: 1.2056 - val_ia: 0.3614 - val_loss: 0.7752 - val_mae: 0.6502 - val_rmse: 0.8186 - val_smape: 1.2733

Epoch 5/16

120/120 - 20s - 163ms/step - ia: 0.4477 - loss: 0.7463 - mae: 0.6258 - rmse: 0.8606 - smape: 1.1921 - val_ia: 0.3631 - val_loss: 0.7795 - val_mae: 0.6568 - val_rmse: 0.8248 - val_smape: 1.2637

Epoch 6/16

120/120 - 17s - 140ms/step - ia: 0.4576 - loss: 0.7287 - mae: 0.6189 - rmse: 0.8513 - smape: 1.1786 - val_ia: 0.3664 - val_loss: 0.7845 - val_mae: 0.6512 - val_rmse: 0.8214 - val_smape: 1.2403

Epoch 7/16

120/120 - 19s - 156ms/step - ia: 0.4687 - loss: 0.7125 - mae: 0.6120 - rmse: 0.8419 - smape: 1.1643 - val_ia: 0.3652 - val_loss: 0.8063 - val_mae: 0.6510 - val_rmse: 0.8258 - val_smape: 1.2386

Epoch 8/16

120/120 - 19s - 160ms/step - ia: 0.4754 - loss: 0.6962 - mae: 0.6058 - rmse: 0.8318 - smape: 1.1592 - val_ia: 0.3727 - val_loss: 0.8309 - val_mae: 0.6678 - val_rmse: 0.8461 - val_smape: 1.2720

Epoch 9/16

120/120 - 18s - 147ms/step - ia: 0.4837 - loss: 0.6826 - mae: 0.5995 - rmse: 0.8237 - smape: 1.1503 - val_ia: 0.3730 - val_loss: 0.8372 - val_mae: 0.6670 - val_rmse: 0.8451 - val_smape: 1.2547

Epoch 10/16

120/120 - 18s - 147ms/step - ia: 0.4918 - loss: 0.6648 - mae: 0.5920 - rmse: 0.8134 - smape: 1.1390 - val_ia: 0.3673 - val_loss: 0.8990 - val_mae: 0.6920 - val_rmse: 0.8780 - val_smape: 1.2777

Epoch 11/16

120/120 - 17s - 143ms/step - ia: 0.4958 - loss: 0.6563 - mae: 0.5896 - rmse: 0.8079 - smape: 1.1378 - val_ia: 0.3733 - val_loss: 0.8978 - val_mae: 0.6829 - val_rmse: 0.8711 - val_smape: 1.2646

Epoch 12/16

120/120 - 18s - 147ms/step - ia: 0.5027 - loss: 0.6380 - mae: 0.5825 - rmse: 0.7968 - smape: 1.1320 - val_ia: 0.3719 - val_loss: 0.9465 - val_mae: 0.6976 - val_rmse: 0.8976 - val_smape: 1.2556

Epoch 13/16

120/120 - 17s - 143ms/step - ia: 0.5124 - loss: 0.6249 - mae: 0.5758 - rmse: 0.7886 - smape: 1.1185 - val_ia: 0.3831 - val_loss: 0.8953 - val_mae: 0.6706 - val_rmse: 0.8636 - val_smape: 1.2118

Epoch 14/16

120/120 - 18s - 147ms/step - ia: 0.5192 - loss: 0.6066 - mae: 0.5683 - rmse: 0.7765 - smape: 1.1124 - val_ia: 0.3715 - val_loss: 0.9500 - val_mae: 0.6898 - val_rmse: 0.8849 - val_smape: 1.2539

Epoch 15/16

120/120 - 20s - 168ms/step - ia: 0.5220 - loss: 0.5993 - mae: 0.5663 - rmse: 0.7720 - smape: 1.1146 - val_ia: 0.3697 - val_loss: 0.9807 - val_mae: 0.7070 - val_rmse: 0.9006 - val_smape: 1.2861

Epoch 16/16

120/120 - 18s - 147ms/step - ia: 0.5325 - loss: 0.5804 - mae: 0.5568 - rmse: 0.7594 - smape: 1.1030 - val_ia: 0.3801 - val_loss: 0.9513 - val_mae: 0.6880 - val_rmse: 0.8878 - val_smape: 1.2531

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 8:00 4s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 19s 112ms/step

  4%|▍         | 2/50 [26:10<9:23:52, 704.83s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 40s - 83ms/step - ia: 0.1168 - loss: 1.0024 - mae: 0.7718 - rmse: 0.9910 - smape: 1.7725 - val_ia: 0.2416 - val_loss: 0.9779 - val_mae: 0.7637 - val_rmse: 0.8763 - val_smape: 1.7842

Epoch 2/8

479/479 - 17s - 36ms/step - ia: 0.1199 - loss: 1.0006 - mae: 0.7705 - rmse: 0.9885 - smape: 1.7766 - val_ia: 0.2417 - val_loss: 0.9757 - val_mae: 0.7621 - val_rmse: 0.8747 - val_smape: 1.7877

Epoch 3/8

479/479 - 8s - 16ms/step - ia: 0.1133 - loss: 0.9989 - mae: 0.7694 - rmse: 0.9903 - smape: 1.7805 - val_ia: 0.2417 - val_loss: 0.9734 - val_mae: 0.7605 - val_rmse: 0.8732 - val_smape: 1.7913

Epoch 4/8

479/479 - 8s - 17ms/step - ia: 0.1169 - loss: 0.9967 - mae: 0.7677 - rmse: 0.9878 - smape: 1.7825 - val_ia: 0.2418 - val_loss: 0.9713 - val_mae: 0.7590 - val_rmse: 0.8717 - val_smape: 1.7950

Epoch 5/8

479/479 - 7s - 14ms/step - ia: 0.1123 - loss: 0.9959 - mae: 0.7670 - rmse: 0.9885 - smape: 1.7876 - val_ia: 0.2418 - val_loss: 0.9691 - val_mae: 0.7574 - val_rmse: 0.8703 - val_smape: 1.7988

Epoch 6/8

479/479 - 6s - 13ms/step - ia: 0.1173 - loss: 0.9938 - mae: 0.7658 - rmse: 0.9862 - smape: 1.7898 - val_ia: 0.2419 - val_loss: 0.9671 - val_mae: 0.7560 - val_rmse: 0.8688 - val_smape: 1.8027

Epoch 7/8

479/479 - 11s - 22ms/step - ia: 0.1215 - loss: 0.9918 - mae: 0.7639 - rmse: 0.9848 - smape: 1.7914 - val_ia: 0.2419 - val_loss: 0.9650 - val_mae: 0.7546 - val_rmse: 0.8675 - val_smape: 1.8070

Epoch 8/8

479/479 - 6s - 14ms/step - ia: 0.1195 - loss: 0.9896 - mae: 0.7630 - rmse: 0.9843 - smape: 1.7962 - val_ia: 0.2420 - val_loss: 0.9631 - val_mae: 0.7532 - val_rmse: 0.8661 - val_smape: 1.8111

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:38 1s/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

  6%|▌         | 3/50 [27:57<5:38:24, 432.01s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

240/240 - 31s - 130ms/step - ia: 0.1879 - loss: 1.0765 - mae: 0.7689 - rmse: 1.0307 - smape: 1.5894 - val_ia: 0.2685 - val_loss: 0.9831 - val_mae: 0.7469 - val_rmse: 0.8908 - val_smape: 1.7184

Epoch 2/32

240/240 - 7s - 30ms/step - ia: 0.2065 - loss: 0.9721 - mae: 0.7335 - rmse: 0.9796 - smape: 1.5692 - val_ia: 0.2731 - val_loss: 0.8813 - val_mae: 0.7043 - val_rmse: 0.8424 - val_smape: 1.6080

Epoch 3/32

240/240 - 7s - 30ms/step - ia: 0.2496 - loss: 0.9217 - mae: 0.7140 - rmse: 0.9533 - smape: 1.4971 - val_ia: 0.2820 - val_loss: 0.8271 - val_mae: 0.6788 - val_rmse: 0.8165 - val_smape: 1.4570

Epoch 4/32

240/240 - 7s - 30ms/step - ia: 0.2960 - loss: 0.8908 - mae: 0.7015 - rmse: 0.9380 - smape: 1.4250 - val_ia: 0.2910 - val_loss: 0.8029 - val_mae: 0.6652 - val_rmse: 0.8052 - val_smape: 1.3706

Epoch 5/32

240/240 - 7s - 30ms/step - ia: 0.3256 - loss: 0.8753 - mae: 0.6944 - rmse: 0.9306 - smape: 1.3766 - val_ia: 0.2979 - val_loss: 0.7929 - val_mae: 0.6585 - val_rmse: 0.8007 - val_smape: 1.3252

Epoch 6/32

240/240 - 7s - 30ms/step - ia: 0.3383 - loss: 0.8702 - mae: 0.6928 - rmse: 0.9285 - smape: 1.3600 - val_ia: 0.3023 - val_loss: 0.7887 - val_mae: 0.6556 - val_rmse: 0.7992 - val_smape: 1.3032

Epoch 7/32

240/240 - 7s - 29ms/step - ia: 0.3501 - loss: 0.8688 - mae: 0.6905 - rmse: 0.9263 - smape: 1.3427 - val_ia: 0.3046 - val_loss: 0.7868 - val_mae: 0.6544 - val_rmse: 0.7987 - val_smape: 1.2937

Epoch 8/32

240/240 - 6s - 27ms/step - ia: 0.3511 - loss: 0.8626 - mae: 0.6893 - rmse: 0.9236 - smape: 1.3399 - val_ia: 0.3057 - val_loss: 0.7853 - val_mae: 0.6537 - val_rmse: 0.7982 - val_smape: 1.2884

Epoch 9/32

240/240 - 6s - 27ms/step - ia: 0.3559 - loss: 0.8626 - mae: 0.6881 - rmse: 0.9228 - smape: 1.3338 - val_ia: 0.3057 - val_loss: 0.7843 - val_mae: 0.6532 - val_rmse: 0.7977 - val_smape: 1.2873

Epoch 10/32

240/240 - 7s - 27ms/step - ia: 0.3554 - loss: 0.8617 - mae: 0.6884 - rmse: 0.9231 - smape: 1.3344 - val_ia: 0.3064 - val_loss: 0.7831 - val_mae: 0.6526 - val_rmse: 0.7972 - val_smape: 1.2844

Epoch 11/32

240/240 - 6s - 27ms/step - ia: 0.3578 - loss: 0.8562 - mae: 0.6856 - rmse: 0.9201 - smape: 1.3294 - val_ia: 0.3068 - val_loss: 0.7819 - val_mae: 0.6523 - val_rmse: 0.7968 - val_smape: 1.2827

Epoch 12/32

240/240 - 6s - 26ms/step - ia: 0.3578 - loss: 0.8594 - mae: 0.6878 - rmse: 0.9217 - smape: 1.3293 - val_ia: 0.3062 - val_loss: 0.7818 - val_mae: 0.6525 - val_rmse: 0.7967 - val_smape: 1.2860

Epoch 13/32

240/240 - 6s - 26ms/step - ia: 0.3570 - loss: 0.8583 - mae: 0.6865 - rmse: 0.9208 - smape: 1.3329 - val_ia: 0.3066 - val_loss: 0.7804 - val_mae: 0.6518 - val_rmse: 0.7961 - val_smape: 1.2835

Epoch 14/32

240/240 - 7s - 29ms/step - ia: 0.3599 - loss: 0.8524 - mae: 0.6845 - rmse: 0.9180 - smape: 1.3273 - val_ia: 0.3064 - val_loss: 0.7797 - val_mae: 0.6517 - val_rmse: 0.7957 - val_smape: 1.2848

Epoch 15/32

240/240 - 7s - 31ms/step - ia: 0.3581 - loss: 0.8554 - mae: 0.6860 - rmse: 0.9199 - smape: 1.3305 - val_ia: 0.3061 - val_loss: 0.7787 - val_mae: 0.6514 - val_rmse: 0.7952 - val_smape: 1.2853

Epoch 16/32

240/240 - 7s - 30ms/step - ia: 0.3575 - loss: 0.8563 - mae: 0.6843 - rmse: 0.9212 - smape: 1.3259 - val_ia: 0.3069 - val_loss: 0.7783 - val_mae: 0.6512 - val_rmse: 0.7952 - val_smape: 1.2845

Epoch 17/32

240/240 - 8s - 34ms/step - ia: 0.3618 - loss: 0.8520 - mae: 0.6833 - rmse: 0.9174 - smape: 1.3257 - val_ia: 0.3072 - val_loss: 0.7776 - val_mae: 0.6510 - val_rmse: 0.7949 - val_smape: 1.2842

Epoch 18/32

240/240 - 8s - 33ms/step - ia: 0.3591 - loss: 0.8561 - mae: 0.6844 - rmse: 0.9187 - smape: 1.3269 - val_ia: 0.3072 - val_loss: 0.7771 - val_mae: 0.6510 - val_rmse: 0.7948 - val_smape: 1.2857

Epoch 19/32

240/240 - 8s - 33ms/step - ia: 0.3609 - loss: 0.8506 - mae: 0.6825 - rmse: 0.9174 - smape: 1.3258 - val_ia: 0.3076 - val_loss: 0.7770 - val_mae: 0.6511 - val_rmse: 0.7950 - val_smape: 1.2858

Epoch 20/32

240/240 - 8s - 33ms/step - ia: 0.3615 - loss: 0.8507 - mae: 0.6821 - rmse: 0.9172 - smape: 1.3206 - val_ia: 0.3077 - val_loss: 0.7755 - val_mae: 0.6502 - val_rmse: 0.7940 - val_smape: 1.2828

Epoch 21/32

240/240 - 7s - 29ms/step - ia: 0.3611 - loss: 0.8481 - mae: 0.6812 - rmse: 0.9158 - smape: 1.3237 - val_ia: 0.3081 - val_loss: 0.7751 - val_mae: 0.6501 - val_rmse: 0.7939 - val_smape: 1.2829

Epoch 22/32

240/240 - 10s - 42ms/step - ia: 0.3627 - loss: 0.8476 - mae: 0.6813 - rmse: 0.9160 - smape: 1.3218 - val_ia: 0.3079 - val_loss: 0.7745 - val_mae: 0.6498 - val_rmse: 0.7935 - val_smape: 1.2826

Epoch 23/32

240/240 - 7s - 28ms/step - ia: 0.3624 - loss: 0.8486 - mae: 0.6806 - rmse: 0.9153 - smape: 1.3210 - val_ia: 0.3084 - val_loss: 0.7742 - val_mae: 0.6497 - val_rmse: 0.7935 - val_smape: 1.2820

Epoch 24/32

240/240 - 7s - 30ms/step - ia: 0.3633 - loss: 0.8479 - mae: 0.6809 - rmse: 0.9158 - smape: 1.3218 - val_ia: 0.3086 - val_loss: 0.7736 - val_mae: 0.6493 - val_rmse: 0.7931 - val_smape: 1.2812

Epoch 25/32

240/240 - 8s - 33ms/step - ia: 0.3636 - loss: 0.8464 - mae: 0.6802 - rmse: 0.9141 - smape: 1.3198 - val_ia: 0.3086 - val_loss: 0.7734 - val_mae: 0.6493 - val_rmse: 0.7930 - val_smape: 1.2819

Epoch 26/32

240/240 - 8s - 31ms/step - ia: 0.3638 - loss: 0.8439 - mae: 0.6792 - rmse: 0.9135 - smape: 1.3187 - val_ia: 0.3092 - val_loss: 0.7729 - val_mae: 0.6491 - val_rmse: 0.7930 - val_smape: 1.2809

Epoch 27/32

240/240 - 8s - 33ms/step - ia: 0.3647 - loss: 0.8445 - mae: 0.6795 - rmse: 0.9141 - smape: 1.3185 - val_ia: 0.3094 - val_loss: 0.7727 - val_mae: 0.6491 - val_rmse: 0.7929 - val_smape: 1.2813

Epoch 28/32

240/240 - 8s - 33ms/step - ia: 0.3652 - loss: 0.8429 - mae: 0.6781 - rmse: 0.9129 - smape: 1.3168 - val_ia: 0.3095 - val_loss: 0.7722 - val_mae: 0.6490 - val_rmse: 0.7927 - val_smape: 1.2815

Epoch 29/32

240/240 - 8s - 33ms/step - ia: 0.3653 - loss: 0.8451 - mae: 0.6789 - rmse: 0.9136 - smape: 1.3201 - val_ia: 0.3092 - val_loss: 0.7713 - val_mae: 0.6487 - val_rmse: 0.7922 - val_smape: 1.2817

Epoch 30/32

240/240 - 8s - 33ms/step - ia: 0.3648 - loss: 0.8457 - mae: 0.6798 - rmse: 0.9143 - smape: 1.3163 - val_ia: 0.3095 - val_loss: 0.7714 - val_mae: 0.6489 - val_rmse: 0.7924 - val_smape: 1.2827

Epoch 31/32

240/240 - 8s - 31ms/step - ia: 0.3673 - loss: 0.8379 - mae: 0.6770 - rmse: 0.9096 - smape: 1.3180 - val_ia: 0.3097 - val_loss: 0.7710 - val_mae: 0.6487 - val_rmse: 0.7922 - val_smape: 1.2824

Epoch 32/32

240/240 - 7s - 31ms/step - ia: 0.3656 - loss: 0.8413 - mae: 0.6780 - rmse: 0.9121 - smape: 1.3177 - val_ia: 0.3098 - val_loss: 0.7708 - val_mae: 0.6485 - val_rmse: 0.7921 - val_smape: 1.2826

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 7:07 3s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step

  8%|▊         | 4/50 [32:25<4:41:32, 367.23s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

3830/3830 - 54s - 14ms/step - ia: 0.3589 - loss: 1.3593 - mae: 0.7909 - rmse: 1.0723 - smape: 1.2073 - val_ia: 0.2084 - val_loss: 1.1251 - val_mae: 0.6883 - val_rmse: 0.7286 - val_smape: 1.0744

Epoch 2/64

3830/3830 - 51s - 13ms/step - ia: 0.3309 - loss: 1.2305 - mae: 0.7631 - rmse: 1.0204 - smape: 1.2783 - val_ia: 0.2037 - val_loss: 1.0406 - val_mae: 0.6845 - val_rmse: 0.7234 - val_smape: 1.1805

Epoch 3/64

3830/3830 - 47s - 12ms/step - ia: 0.3014 - loss: 1.1542 - mae: 0.7547 - rmse: 0.9881 - smape: 1.3608 - val_ia: 0.1939 - val_loss: 0.9970 - val_mae: 0.6938 - val_rmse: 0.7312 - val_smape: 1.3237

Epoch 4/64

3830/3830 - 42s - 11ms/step - ia: 0.2809 - loss: 1.1128 - mae: 0.7568 - rmse: 0.9759 - smape: 1.4338 - val_ia: 0.1904 - val_loss: 0.9782 - val_mae: 0.7061 - val_rmse: 0.7430 - val_smape: 1.4786

Epoch 5/64

3830/3830 - 44s - 12ms/step - ia: 0.2691 - loss: 1.0927 - mae: 0.7603 - rmse: 0.9700 - smape: 1.4757 - val_ia: 0.1891 - val_loss: 0.9717 - val_mae: 0.7169 - val_rmse: 0.7535 - val_smape: 1.6223

Epoch 6/64

3830/3830 - 44s - 11ms/step - ia: 0.2641 - loss: 1.0791 - mae: 0.7631 - rmse: 0.9671 - smape: 1.5042 - val_ia: 0.1874 - val_loss: 0.9698 - val_mae: 0.7249 - val_rmse: 0.7612 - val_smape: 1.7450

Epoch 7/64

3830/3830 - 43s - 11ms/step - ia: 0.2536 - loss: 1.0772 - mae: 0.7691 - rmse: 0.9693 - smape: 1.5377 - val_ia: 0.1865 - val_loss: 0.9692 - val_mae: 0.7301 - val_rmse: 0.7662 - val_smape: 1.8415

Epoch 8/64

3830/3830 - 32s - 8ms/step - ia: 0.2566 - loss: 1.0720 - mae: 0.7696 - rmse: 0.9668 - smape: 1.5462 - val_ia: 0.1859 - val_loss: 0.9690 - val_mae: 0.7336 - val_rmse: 0.7696 - val_smape: 1.9130

Epoch 9/64

3830/3830 - 34s - 9ms/step - ia: 0.2530 - loss: 1.0726 - mae: 0.7738 - rmse: 0.9683 - smape: 1.5639 - val_ia: 0.1855 - val_loss: 0.9685 - val_mae: 0.7355 - val_rmse: 0.7714 - val_smape: 1.9344

Epoch 10/64

3830/3830 - 32s - 8ms/step - ia: 0.2508 - loss: 1.0645 - mae: 0.7715 - rmse: 0.9632 - smape: 1.5638 - val_ia: 0.1853 - val_loss: 0.9677 - val_mae: 0.7361 - val_rmse: 0.7721 - val_smape: 1.9359

Epoch 11/64

3830/3830 - 48s - 13ms/step - ia: 0.2543 - loss: 1.0644 - mae: 0.7717 - rmse: 0.9628 - smape: 1.5668 - val_ia: 0.1850 - val_loss: 0.9670 - val_mae: 0.7368 - val_rmse: 0.7727 - val_smape: 1.9330

Epoch 12/64

3830/3830 - 40s - 10ms/step - ia: 0.2507 - loss: 1.0591 - mae: 0.7711 - rmse: 0.9621 - smape: 1.5732 - val_ia: 0.1849 - val_loss: 0.9661 - val_mae: 0.7369 - val_rmse: 0.7728 - val_smape: 1.9290

Epoch 13/64

3830/3830 - 39s - 10ms/step - ia: 0.2498 - loss: 1.0598 - mae: 0.7708 - rmse: 0.9635 - smape: 1.5711 - val_ia: 0.1848 - val_loss: 0.9651 - val_mae: 0.7368 - val_rmse: 0.7727 - val_smape: 1.9256

Epoch 14/64

3830/3830 - 39s - 10ms/step - ia: 0.2514 - loss: 1.0471 - mae: 0.7670 - rmse: 0.9557 - smape: 1.5701 - val_ia: 0.1849 - val_loss: 0.9641 - val_mae: 0.7366 - val_rmse: 0.7725 - val_smape: 1.9227

Epoch 15/64

3830/3830 - 39s - 10ms/step - ia: 0.2519 - loss: 1.0493 - mae: 0.7668 - rmse: 0.9575 - smape: 1.5671 - val_ia: 0.1849 - val_loss: 0.9631 - val_mae: 0.7362 - val_rmse: 0.7721 - val_smape: 1.9206

Epoch 16/64

3830/3830 - 33s - 9ms/step - ia: 0.2503 - loss: 1.0474 - mae: 0.7670 - rmse: 0.9583 - smape: 1.5753 - val_ia: 0.1850 - val_loss: 0.9620 - val_mae: 0.7359 - val_rmse: 0.7718 - val_smape: 1.9183

Epoch 17/64

3830/3830 - 34s - 9ms/step - ia: 0.2503 - loss: 1.0489 - mae: 0.7684 - rmse: 0.9597 - smape: 1.5789 - val_ia: 0.1850 - val_loss: 0.9610 - val_mae: 0.7357 - val_rmse: 0.7716 - val_smape: 1.9147

Epoch 18/64

3830/3830 - 34s - 9ms/step - ia: 0.2483 - loss: 1.0486 - mae: 0.7687 - rmse: 0.9588 - smape: 1.5837 - val_ia: 0.1852 - val_loss: 0.9598 - val_mae: 0.7352 - val_rmse: 0.7711 - val_smape: 1.9134

Epoch 19/64

3830/3830 - 33s - 9ms/step - ia: 0.2486 - loss: 1.0430 - mae: 0.7639 - rmse: 0.9551 - smape: 1.5742 - val_ia: 0.1853 - val_loss: 0.9587 - val_mae: 0.7347 - val_rmse: 0.7706 - val_smape: 1.9114

Epoch 20/64

3830/3830 - 34s - 9ms/step - ia: 0.2497 - loss: 1.0373 - mae: 0.7638 - rmse: 0.9529 - smape: 1.5781 - val_ia: 0.1853 - val_loss: 0.9576 - val_mae: 0.7343 - val_rmse: 0.7702 - val_smape: 1.9085

Epoch 21/64

3830/3830 - 34s - 9ms/step - ia: 0.2474 - loss: 1.0440 - mae: 0.7662 - rmse: 0.9546 - smape: 1.5807 - val_ia: 0.1854 - val_loss: 0.9564 - val_mae: 0.7339 - val_rmse: 0.7697 - val_smape: 1.9059

Epoch 22/64

3830/3830 - 34s - 9ms/step - ia: 0.2469 - loss: 1.0371 - mae: 0.7616 - rmse: 0.9506 - smape: 1.5772 - val_ia: 0.1855 - val_loss: 0.9552 - val_mae: 0.7334 - val_rmse: 0.7693 - val_smape: 1.9032

Epoch 23/64

3830/3830 - 34s - 9ms/step - ia: 0.2496 - loss: 1.0375 - mae: 0.7618 - rmse: 0.9519 - smape: 1.5786 - val_ia: 0.1855 - val_loss: 0.9541 - val_mae: 0.7332 - val_rmse: 0.7690 - val_smape: 1.8993

Epoch 24/64

3830/3830 - 33s - 9ms/step - ia: 0.2476 - loss: 1.0352 - mae: 0.7627 - rmse: 0.9509 - smape: 1.5842 - val_ia: 0.1856 - val_loss: 0.9529 - val_mae: 0.7327 - val_rmse: 0.7685 - val_smape: 1.8960

Epoch 25/64

3830/3830 - 34s - 9ms/step - ia: 0.2470 - loss: 1.0342 - mae: 0.7625 - rmse: 0.9516 - smape: 1.5847 - val_ia: 0.1856 - val_loss: 0.9517 - val_mae: 0.7325 - val_rmse: 0.7684 - val_smape: 1.8916

Epoch 26/64

3830/3830 - 42s - 11ms/step - ia: 0.2458 - loss: 1.0295 - mae: 0.7610 - rmse: 0.9482 - smape: 1.5873 - val_ia: 0.1857 - val_loss: 0.9505 - val_mae: 0.7320 - val_rmse: 0.7679 - val_smape: 1.8879

Epoch 27/64

3830/3830 - 34s - 9ms/step - ia: 0.2467 - loss: 1.0276 - mae: 0.7605 - rmse: 0.9482 - smape: 1.5863 - val_ia: 0.1859 - val_loss: 0.9491 - val_mae: 0.7313 - val_rmse: 0.7671 - val_smape: 1.8844

Epoch 28/64

3830/3830 - 34s - 9ms/step - ia: 0.2478 - loss: 1.0224 - mae: 0.7581 - rmse: 0.9460 - smape: 1.5841 - val_ia: 0.1860 - val_loss: 0.9477 - val_mae: 0.7308 - val_rmse: 0.7666 - val_smape: 1.8801

Epoch 29/64

3830/3830 - 34s - 9ms/step - ia: 0.2475 - loss: 1.0251 - mae: 0.7593 - rmse: 0.9476 - smape: 1.5861 - val_ia: 0.1860 - val_loss: 0.9466 - val_mae: 0.7308 - val_rmse: 0.7666 - val_smape: 1.8749

Epoch 30/64

3830/3830 - 34s - 9ms/step - ia: 0.2531 - loss: 1.0191 - mae: 0.7573 - rmse: 0.9430 - smape: 1.5832 - val_ia: 0.1861 - val_loss: 0.9451 - val_mae: 0.7300 - val_rmse: 0.7659 - val_smape: 1.8703

Epoch 31/64

3830/3830 - 32s - 8ms/step - ia: 0.2463 - loss: 1.0184 - mae: 0.7566 - rmse: 0.9431 - smape: 1.5859 - val_ia: 0.1863 - val_loss: 0.9436 - val_mae: 0.7293 - val_rmse: 0.7651 - val_smape: 1.8655

Epoch 32/64

3830/3830 - 34s - 9ms/step - ia: 0.2497 - loss: 1.0149 - mae: 0.7560 - rmse: 0.9412 - smape: 1.5854 - val_ia: 0.1863 - val_loss: 0.9422 - val_mae: 0.7288 - val_rmse: 0.7647 - val_smape: 1.8603

Epoch 33/64

3830/3830 - 34s - 9ms/step - ia: 0.2501 - loss: 1.0147 - mae: 0.7548 - rmse: 0.9412 - smape: 1.5846 - val_ia: 0.1864 - val_loss: 0.9407 - val_mae: 0.7281 - val_rmse: 0.7640 - val_smape: 1.8551

Epoch 34/64

3830/3830 - 34s - 9ms/step - ia: 0.2496 - loss: 1.0148 - mae: 0.7552 - rmse: 0.9413 - smape: 1.5885 - val_ia: 0.1865 - val_loss: 0.9392 - val_mae: 0.7277 - val_rmse: 0.7635 - val_smape: 1.8497

Epoch 35/64

3830/3830 - 32s - 8ms/step - ia: 0.2498 - loss: 1.0092 - mae: 0.7531 - rmse: 0.9391 - smape: 1.5867 - val_ia: 0.1866 - val_loss: 0.9377 - val_mae: 0.7270 - val_rmse: 0.7628 - val_smape: 1.8439

Epoch 36/64

3830/3830 - 34s - 9ms/step - ia: 0.2491 - loss: 1.0083 - mae: 0.7530 - rmse: 0.9392 - smape: 1.5841 - val_ia: 0.1866 - val_loss: 0.9362 - val_mae: 0.7266 - val_rmse: 0.7625 - val_smape: 1.8385

Epoch 37/64

3830/3830 - 33s - 9ms/step - ia: 0.2494 - loss: 1.0120 - mae: 0.7551 - rmse: 0.9395 - smape: 1.5900 - val_ia: 0.1867 - val_loss: 0.9345 - val_mae: 0.7259 - val_rmse: 0.7617 - val_smape: 1.8323

Epoch 38/64

3830/3830 - 34s - 9ms/step - ia: 0.2489 - loss: 1.0088 - mae: 0.7527 - rmse: 0.9393 - smape: 1.5902 - val_ia: 0.1867 - val_loss: 0.9330 - val_mae: 0.7256 - val_rmse: 0.7615 - val_smape: 1.8269

Epoch 39/64

3830/3830 - 34s - 9ms/step - ia: 0.2501 - loss: 1.0036 - mae: 0.7517 - rmse: 0.9362 - smape: 1.5886 - val_ia: 0.1868 - val_loss: 0.9312 - val_mae: 0.7248 - val_rmse: 0.7606 - val_smape: 1.8205

Epoch 40/64

3830/3830 - 34s - 9ms/step - ia: 0.2520 - loss: 1.0018 - mae: 0.7505 - rmse: 0.9356 - smape: 1.5813 - val_ia: 0.1869 - val_loss: 0.9294 - val_mae: 0.7241 - val_rmse: 0.7599 - val_smape: 1.8140

Epoch 41/64

3830/3830 - 34s - 9ms/step - ia: 0.2526 - loss: 0.9980 - mae: 0.7486 - rmse: 0.9331 - smape: 1.5838 - val_ia: 0.1870 - val_loss: 0.9277 - val_mae: 0.7235 - val_rmse: 0.7594 - val_smape: 1.8078

Epoch 42/64

3830/3830 - 41s - 11ms/step - ia: 0.2537 - loss: 0.9991 - mae: 0.7495 - rmse: 0.9339 - smape: 1.5852 - val_ia: 0.1872 - val_loss: 0.9258 - val_mae: 0.7225 - val_rmse: 0.7584 - val_smape: 1.8006

Epoch 43/64

3830/3830 - 34s - 9ms/step - ia: 0.2533 - loss: 0.9967 - mae: 0.7476 - rmse: 0.9330 - smape: 1.5796 - val_ia: 0.1873 - val_loss: 0.9239 - val_mae: 0.7217 - val_rmse: 0.7576 - val_smape: 1.7935

Epoch 44/64

3830/3830 - 41s - 11ms/step - ia: 0.2560 - loss: 0.9927 - mae: 0.7463 - rmse: 0.9307 - smape: 1.5794 - val_ia: 0.1874 - val_loss: 0.9220 - val_mae: 0.7209 - val_rmse: 0.7568 - val_smape: 1.7865

Epoch 45/64

3830/3830 - 34s - 9ms/step - ia: 0.2540 - loss: 0.9876 - mae: 0.7442 - rmse: 0.9286 - smape: 1.5760 - val_ia: 0.1875 - val_loss: 0.9201 - val_mae: 0.7203 - val_rmse: 0.7562 - val_smape: 1.7798

Epoch 46/64

3830/3830 - 34s - 9ms/step - ia: 0.2562 - loss: 0.9876 - mae: 0.7443 - rmse: 0.9285 - smape: 1.5730 - val_ia: 0.1876 - val_loss: 0.9181 - val_mae: 0.7195 - val_rmse: 0.7554 - val_smape: 1.7725

Epoch 47/64

3830/3830 - 34s - 9ms/step - ia: 0.2550 - loss: 0.9850 - mae: 0.7437 - rmse: 0.9289 - smape: 1.5731 - val_ia: 0.1876 - val_loss: 0.9162 - val_mae: 0.7189 - val_rmse: 0.7548 - val_smape: 1.7661

Epoch 48/64

3830/3830 - 33s - 9ms/step - ia: 0.2584 - loss: 0.9849 - mae: 0.7426 - rmse: 0.9260 - smape: 1.5706 - val_ia: 0.1877 - val_loss: 0.9142 - val_mae: 0.7181 - val_rmse: 0.7540 - val_smape: 1.7587

Epoch 49/64

3830/3830 - 42s - 11ms/step - ia: 0.2564 - loss: 0.9850 - mae: 0.7432 - rmse: 0.9271 - smape: 1.5726 - val_ia: 0.1878 - val_loss: 0.9121 - val_mae: 0.7174 - val_rmse: 0.7533 - val_smape: 1.7514

Epoch 50/64

3830/3830 - 34s - 9ms/step - ia: 0.2597 - loss: 0.9765 - mae: 0.7402 - rmse: 0.9236 - smape: 1.5648 - val_ia: 0.1880 - val_loss: 0.9100 - val_mae: 0.7164 - val_rmse: 0.7523 - val_smape: 1.7432

Epoch 51/64

3830/3830 - 34s - 9ms/step - ia: 0.2608 - loss: 0.9766 - mae: 0.7392 - rmse: 0.9231 - smape: 1.5627 - val_ia: 0.1882 - val_loss: 0.9078 - val_mae: 0.7153 - val_rmse: 0.7513 - val_smape: 1.7350

Epoch 52/64

3830/3830 - 34s - 9ms/step - ia: 0.2630 - loss: 0.9744 - mae: 0.7383 - rmse: 0.9225 - smape: 1.5609 - val_ia: 0.1883 - val_loss: 0.9056 - val_mae: 0.7145 - val_rmse: 0.7504 - val_smape: 1.7275

Epoch 53/64

3830/3830 - 34s - 9ms/step - ia: 0.2618 - loss: 0.9721 - mae: 0.7374 - rmse: 0.9207 - smape: 1.5585 - val_ia: 0.1885 - val_loss: 0.9034 - val_mae: 0.7135 - val_rmse: 0.7495 - val_smape: 1.7194

Epoch 54/64

3830/3830 - 34s - 9ms/step - ia: 0.2627 - loss: 0.9734 - mae: 0.7381 - rmse: 0.9201 - smape: 1.5608 - val_ia: 0.1886 - val_loss: 0.9012 - val_mae: 0.7126 - val_rmse: 0.7485 - val_smape: 1.7114

Epoch 55/64

3830/3830 - 34s - 9ms/step - ia: 0.2671 - loss: 0.9665 - mae: 0.7353 - rmse: 0.9178 - smape: 1.5502 - val_ia: 0.1888 - val_loss: 0.8990 - val_mae: 0.7119 - val_rmse: 0.7478 - val_smape: 1.7046

Epoch 56/64

3830/3830 - 34s - 9ms/step - ia: 0.2644 - loss: 0.9661 - mae: 0.7368 - rmse: 0.9193 - smape: 1.5549 - val_ia: 0.1890 - val_loss: 0.8967 - val_mae: 0.7108 - val_rmse: 0.7468 - val_smape: 1.6960

Epoch 57/64

3830/3830 - 34s - 9ms/step - ia: 0.2667 - loss: 0.9643 - mae: 0.7347 - rmse: 0.9171 - smape: 1.5505 - val_ia: 0.1891 - val_loss: 0.8943 - val_mae: 0.7097 - val_rmse: 0.7457 - val_smape: 1.6874

Epoch 58/64

3830/3830 - 34s - 9ms/step - ia: 0.2703 - loss: 0.9544 - mae: 0.7310 - rmse: 0.9127 - smape: 1.5418 - val_ia: 0.1893 - val_loss: 0.8919 - val_mae: 0.7084 - val_rmse: 0.7444 - val_smape: 1.6779

Epoch 59/64

3830/3830 - 34s - 9ms/step - ia: 0.2701 - loss: 0.9587 - mae: 0.7314 - rmse: 0.9146 - smape: 1.5371 - val_ia: 0.1895 - val_loss: 0.8896 - val_mae: 0.7076 - val_rmse: 0.7436 - val_smape: 1.6704

Epoch 60/64

3830/3830 - 34s - 9ms/step - ia: 0.2718 - loss: 0.9557 - mae: 0.7286 - rmse: 0.9136 - smape: 1.5277 - val_ia: 0.1896 - val_loss: 0.8873 - val_mae: 0.7066 - val_rmse: 0.7426 - val_smape: 1.6624

Epoch 61/64

3830/3830 - 34s - 9ms/step - ia: 0.2711 - loss: 0.9537 - mae: 0.7296 - rmse: 0.9130 - smape: 1.5340 - val_ia: 0.1897 - val_loss: 0.8850 - val_mae: 0.7057 - val_rmse: 0.7418 - val_smape: 1.6550

Epoch 62/64

3830/3830 - 34s - 9ms/step - ia: 0.2733 - loss: 0.9546 - mae: 0.7296 - rmse: 0.9120 - smape: 1.5309 - val_ia: 0.1898 - val_loss: 0.8826 - val_mae: 0.7048 - val_rmse: 0.7409 - val_smape: 1.6472

Epoch 63/64

3830/3830 - 34s - 9ms/step - ia: 0.2738 - loss: 0.9509 - mae: 0.7289 - rmse: 0.9113 - smape: 1.5274 - val_ia: 0.1899 - val_loss: 0.8802 - val_mae: 0.7036 - val_rmse: 0.7398 - val_smape: 1.6384

Epoch 64/64

3830/3830 - 32s - 8ms/step - ia: 0.2748 - loss: 0.9463 - mae: 0.7269 - rmse: 0.9091 - smape: 1.5239 - val_ia: 0.1900 - val_loss: 0.8779 - val_mae: 0.7026 - val_rmse: 0.7388 - val_smape: 1.6306

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:35 1s/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 10%|█         | 5/50 [1:11:00<13:22:16, 1069.69s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 29s - 30ms/step - ia: 0.2400 - loss: 1.0427 - mae: 0.7630 - rmse: 0.9993 - smape: 1.5447 - val_ia: 0.2396 - val_loss: 0.8901 - val_mae: 0.7124 - val_rmse: 0.7989 - val_smape: 1.6058

Epoch 2/128

958/958 - 19s - 20ms/step - ia: 0.2849 - loss: 0.9573 - mae: 0.7328 - rmse: 0.9585 - smape: 1.4703 - val_ia: 0.2479 - val_loss: 0.8246 - val_mae: 0.6801 - val_rmse: 0.7685 - val_smape: 1.4540

Epoch 3/128

958/958 - 12s - 13ms/step - ia: 0.3213 - loss: 0.9120 - mae: 0.7131 - rmse: 0.9365 - smape: 1.4044 - val_ia: 0.2528 - val_loss: 0.7995 - val_mae: 0.6646 - val_rmse: 0.7552 - val_smape: 1.3710

Epoch 4/128

958/958 - 12s - 13ms/step - ia: 0.3407 - loss: 0.8952 - mae: 0.7053 - rmse: 0.9282 - smape: 1.3739 - val_ia: 0.2556 - val_loss: 0.7890 - val_mae: 0.6570 - val_rmse: 0.7485 - val_smape: 1.3324

Epoch 5/128

958/958 - 11s - 11ms/step - ia: 0.3500 - loss: 0.8842 - mae: 0.6999 - rmse: 0.9219 - smape: 1.3553 - val_ia: 0.2574 - val_loss: 0.7843 - val_mae: 0.6531 - val_rmse: 0.7454 - val_smape: 1.3118

Epoch 6/128

958/958 - 11s - 11ms/step - ia: 0.3588 - loss: 0.8765 - mae: 0.6951 - rmse: 0.9184 - smape: 1.3433 - val_ia: 0.2581 - val_loss: 0.7821 - val_mae: 0.6512 - val_rmse: 0.7437 - val_smape: 1.3017

Epoch 7/128

958/958 - 12s - 12ms/step - ia: 0.3617 - loss: 0.8711 - mae: 0.6928 - rmse: 0.9156 - smape: 1.3364 - val_ia: 0.2580 - val_loss: 0.7814 - val_mae: 0.6508 - val_rmse: 0.7434 - val_smape: 1.2988

Epoch 8/128

958/958 - 12s - 13ms/step - ia: 0.3626 - loss: 0.8702 - mae: 0.6920 - rmse: 0.9146 - smape: 1.3362 - val_ia: 0.2582 - val_loss: 0.7796 - val_mae: 0.6497 - val_rmse: 0.7424 - val_smape: 1.2945

Epoch 9/128

958/958 - 20s - 21ms/step - ia: 0.3636 - loss: 0.8687 - mae: 0.6905 - rmse: 0.9137 - smape: 1.3323 - val_ia: 0.2579 - val_loss: 0.7793 - val_mae: 0.6498 - val_rmse: 0.7423 - val_smape: 1.2958

Epoch 10/128

958/958 - 14s - 14ms/step - ia: 0.3645 - loss: 0.8656 - mae: 0.6899 - rmse: 0.9125 - smape: 1.3310 - val_ia: 0.2578 - val_loss: 0.7785 - val_mae: 0.6495 - val_rmse: 0.7420 - val_smape: 1.2953

Epoch 11/128

958/958 - 14s - 14ms/step - ia: 0.3634 - loss: 0.8617 - mae: 0.6884 - rmse: 0.9111 - smape: 1.3325 - val_ia: 0.2577 - val_loss: 0.7780 - val_mae: 0.6491 - val_rmse: 0.7420 - val_smape: 1.2910

Epoch 12/128

958/958 - 13s - 14ms/step - ia: 0.3667 - loss: 0.8594 - mae: 0.6867 - rmse: 0.9076 - smape: 1.3253 - val_ia: 0.2576 - val_loss: 0.7773 - val_mae: 0.6489 - val_rmse: 0.7418 - val_smape: 1.2913

Epoch 13/128

958/958 - 14s - 14ms/step - ia: 0.3662 - loss: 0.8608 - mae: 0.6861 - rmse: 0.9102 - smape: 1.3280 - val_ia: 0.2577 - val_loss: 0.7755 - val_mae: 0.6482 - val_rmse: 0.7408 - val_smape: 1.2906

Epoch 14/128

958/958 - 14s - 14ms/step - ia: 0.3686 - loss: 0.8558 - mae: 0.6844 - rmse: 0.9060 - smape: 1.3254 - val_ia: 0.2575 - val_loss: 0.7754 - val_mae: 0.6481 - val_rmse: 0.7409 - val_smape: 1.2896

Epoch 15/128

958/958 - 14s - 14ms/step - ia: 0.3674 - loss: 0.8566 - mae: 0.6841 - rmse: 0.9087 - smape: 1.3255 - val_ia: 0.2574 - val_loss: 0.7751 - val_mae: 0.6483 - val_rmse: 0.7410 - val_smape: 1.2904

Epoch 16/128

958/958 - 14s - 15ms/step - ia: 0.3679 - loss: 0.8516 - mae: 0.6831 - rmse: 0.9053 - smape: 1.3234 - val_ia: 0.2580 - val_loss: 0.7727 - val_mae: 0.6471 - val_rmse: 0.7399 - val_smape: 1.2859

Epoch 17/128

958/958 - 13s - 14ms/step - ia: 0.3702 - loss: 0.8523 - mae: 0.6824 - rmse: 0.9062 - smape: 1.3226 - val_ia: 0.2573 - val_loss: 0.7738 - val_mae: 0.6480 - val_rmse: 0.7406 - val_smape: 1.2903

Epoch 18/128

958/958 - 14s - 14ms/step - ia: 0.3684 - loss: 0.8510 - mae: 0.6824 - rmse: 0.9038 - smape: 1.3245 - val_ia: 0.2576 - val_loss: 0.7722 - val_mae: 0.6473 - val_rmse: 0.7399 - val_smape: 1.2883

Epoch 19/128

958/958 - 13s - 14ms/step - ia: 0.3675 - loss: 0.8502 - mae: 0.6821 - rmse: 0.9050 - smape: 1.3244 - val_ia: 0.2577 - val_loss: 0.7715 - val_mae: 0.6468 - val_rmse: 0.7395 - val_smape: 1.2868

Epoch 20/128

958/958 - 13s - 13ms/step - ia: 0.3702 - loss: 0.8479 - mae: 0.6798 - rmse: 0.9038 - smape: 1.3174 - val_ia: 0.2576 - val_loss: 0.7711 - val_mae: 0.6467 - val_rmse: 0.7395 - val_smape: 1.2854

Epoch 21/128

958/958 - 13s - 13ms/step - ia: 0.3692 - loss: 0.8491 - mae: 0.6817 - rmse: 0.9035 - smape: 1.3206 - val_ia: 0.2575 - val_loss: 0.7709 - val_mae: 0.6467 - val_rmse: 0.7395 - val_smape: 1.2860

Epoch 22/128

958/958 - 14s - 15ms/step - ia: 0.3718 - loss: 0.8416 - mae: 0.6789 - rmse: 0.9003 - smape: 1.3170 - val_ia: 0.2574 - val_loss: 0.7708 - val_mae: 0.6466 - val_rmse: 0.7395 - val_smape: 1.2850

Epoch 23/128

958/958 - 14s - 15ms/step - ia: 0.3717 - loss: 0.8445 - mae: 0.6796 - rmse: 0.9011 - smape: 1.3181 - val_ia: 0.2574 - val_loss: 0.7701 - val_mae: 0.6465 - val_rmse: 0.7392 - val_smape: 1.2864

Epoch 24/128

958/958 - 14s - 14ms/step - ia: 0.3717 - loss: 0.8453 - mae: 0.6791 - rmse: 0.9017 - smape: 1.3163 - val_ia: 0.2576 - val_loss: 0.7689 - val_mae: 0.6460 - val_rmse: 0.7386 - val_smape: 1.2851

Epoch 25/128

958/958 - 12s - 13ms/step - ia: 0.3708 - loss: 0.8434 - mae: 0.6787 - rmse: 0.9005 - smape: 1.3166 - val_ia: 0.2574 - val_loss: 0.7691 - val_mae: 0.6464 - val_rmse: 0.7390 - val_smape: 1.2868

Epoch 26/128

958/958 - 15s - 15ms/step - ia: 0.3694 - loss: 0.8434 - mae: 0.6793 - rmse: 0.9020 - smape: 1.3221 - val_ia: 0.2575 - val_loss: 0.7681 - val_mae: 0.6458 - val_rmse: 0.7383 - val_smape: 1.2849

Epoch 27/128

958/958 - 15s - 15ms/step - ia: 0.3708 - loss: 0.8428 - mae: 0.6781 - rmse: 0.8999 - smape: 1.3174 - val_ia: 0.2573 - val_loss: 0.7681 - val_mae: 0.6458 - val_rmse: 0.7384 - val_smape: 1.2859

Epoch 28/128

958/958 - 15s - 16ms/step - ia: 0.3727 - loss: 0.8395 - mae: 0.6771 - rmse: 0.8990 - smape: 1.3124 - val_ia: 0.2576 - val_loss: 0.7672 - val_mae: 0.6454 - val_rmse: 0.7380 - val_smape: 1.2840

Epoch 29/128

958/958 - 17s - 18ms/step - ia: 0.3738 - loss: 0.8396 - mae: 0.6764 - rmse: 0.8972 - smape: 1.3121 - val_ia: 0.2577 - val_loss: 0.7669 - val_mae: 0.6452 - val_rmse: 0.7379 - val_smape: 1.2827

Epoch 30/128

958/958 - 12s - 13ms/step - ia: 0.3725 - loss: 0.8385 - mae: 0.6764 - rmse: 0.8981 - smape: 1.3136 - val_ia: 0.2577 - val_loss: 0.7669 - val_mae: 0.6452 - val_rmse: 0.7380 - val_smape: 1.2825

Epoch 31/128

958/958 - 14s - 15ms/step - ia: 0.3740 - loss: 0.8368 - mae: 0.6753 - rmse: 0.8969 - smape: 1.3141 - val_ia: 0.2577 - val_loss: 0.7663 - val_mae: 0.6449 - val_rmse: 0.7377 - val_smape: 1.2818

Epoch 32/128

958/958 - 14s - 15ms/step - ia: 0.3731 - loss: 0.8359 - mae: 0.6753 - rmse: 0.8957 - smape: 1.3133 - val_ia: 0.2578 - val_loss: 0.7654 - val_mae: 0.6444 - val_rmse: 0.7372 - val_smape: 1.2798

Epoch 33/128

958/958 - 13s - 14ms/step - ia: 0.3718 - loss: 0.8422 - mae: 0.6771 - rmse: 0.9006 - smape: 1.3137 - val_ia: 0.2577 - val_loss: 0.7650 - val_mae: 0.6444 - val_rmse: 0.7371 - val_smape: 1.2806

Epoch 34/128

958/958 - 14s - 15ms/step - ia: 0.3741 - loss: 0.8349 - mae: 0.6746 - rmse: 0.8960 - smape: 1.3121 - val_ia: 0.2577 - val_loss: 0.7649 - val_mae: 0.6443 - val_rmse: 0.7372 - val_smape: 1.2795

Epoch 35/128

958/958 - 14s - 14ms/step - ia: 0.3746 - loss: 0.8369 - mae: 0.6757 - rmse: 0.8959 - smape: 1.3108 - val_ia: 0.2577 - val_loss: 0.7648 - val_mae: 0.6443 - val_rmse: 0.7372 - val_smape: 1.2802

Epoch 36/128

958/958 - 13s - 14ms/step - ia: 0.3746 - loss: 0.8371 - mae: 0.6752 - rmse: 0.8960 - smape: 1.3095 - val_ia: 0.2577 - val_loss: 0.7643 - val_mae: 0.6443 - val_rmse: 0.7371 - val_smape: 1.2805

Epoch 37/128

958/958 - 12s - 13ms/step - ia: 0.3752 - loss: 0.8324 - mae: 0.6741 - rmse: 0.8944 - smape: 1.3089 - val_ia: 0.2575 - val_loss: 0.7643 - val_mae: 0.6446 - val_rmse: 0.7374 - val_smape: 1.2813

Epoch 38/128

958/958 - 12s - 13ms/step - ia: 0.3742 - loss: 0.8365 - mae: 0.6750 - rmse: 0.8962 - smape: 1.3133 - val_ia: 0.2575 - val_loss: 0.7640 - val_mae: 0.6444 - val_rmse: 0.7372 - val_smape: 1.2809

Epoch 39/128

958/958 - 12s - 13ms/step - ia: 0.3741 - loss: 0.8362 - mae: 0.6748 - rmse: 0.8973 - smape: 1.3103 - val_ia: 0.2575 - val_loss: 0.7639 - val_mae: 0.6443 - val_rmse: 0.7372 - val_smape: 1.2804

Epoch 40/128

958/958 - 15s - 15ms/step - ia: 0.3727 - loss: 0.8351 - mae: 0.6744 - rmse: 0.8964 - smape: 1.3137 - val_ia: 0.2576 - val_loss: 0.7632 - val_mae: 0.6441 - val_rmse: 0.7369 - val_smape: 1.2800

Epoch 41/128

958/958 - 14s - 14ms/step - ia: 0.3735 - loss: 0.8352 - mae: 0.6748 - rmse: 0.8964 - smape: 1.3130 - val_ia: 0.2575 - val_loss: 0.7633 - val_mae: 0.6440 - val_rmse: 0.7369 - val_smape: 1.2796

Epoch 42/128

958/958 - 14s - 15ms/step - ia: 0.3758 - loss: 0.8314 - mae: 0.6727 - rmse: 0.8937 - smape: 1.3082 - val_ia: 0.2577 - val_loss: 0.7622 - val_mae: 0.6437 - val_rmse: 0.7366 - val_smape: 1.2780

Epoch 43/128

958/958 - 14s - 15ms/step - ia: 0.3764 - loss: 0.8311 - mae: 0.6724 - rmse: 0.8934 - smape: 1.3063 - val_ia: 0.2577 - val_loss: 0.7620 - val_mae: 0.6435 - val_rmse: 0.7364 - val_smape: 1.2777

Epoch 44/128

958/958 - 13s - 14ms/step - ia: 0.3796 - loss: 0.8265 - mae: 0.6709 - rmse: 0.8916 - smape: 1.3062 - val_ia: 0.2579 - val_loss: 0.7613 - val_mae: 0.6433 - val_rmse: 0.7362 - val_smape: 1.2769

Epoch 45/128

958/958 - 14s - 15ms/step - ia: 0.3760 - loss: 0.8315 - mae: 0.6727 - rmse: 0.8935 - smape: 1.3073 - val_ia: 0.2577 - val_loss: 0.7614 - val_mae: 0.6433 - val_rmse: 0.7362 - val_smape: 1.2773

Epoch 46/128

958/958 - 14s - 15ms/step - ia: 0.3782 - loss: 0.8288 - mae: 0.6720 - rmse: 0.8931 - smape: 1.3068 - val_ia: 0.2579 - val_loss: 0.7606 - val_mae: 0.6430 - val_rmse: 0.7359 - val_smape: 1.2768

Epoch 47/128

958/958 - 15s - 15ms/step - ia: 0.3757 - loss: 0.8321 - mae: 0.6728 - rmse: 0.8945 - smape: 1.3073 - val_ia: 0.2578 - val_loss: 0.7603 - val_mae: 0.6429 - val_rmse: 0.7358 - val_smape: 1.2763

Epoch 48/128

958/958 - 14s - 15ms/step - ia: 0.3762 - loss: 0.8304 - mae: 0.6727 - rmse: 0.8936 - smape: 1.3086 - val_ia: 0.2577 - val_loss: 0.7602 - val_mae: 0.6429 - val_rmse: 0.7358 - val_smape: 1.2764

Epoch 49/128

958/958 - 13s - 14ms/step - ia: 0.3769 - loss: 0.8281 - mae: 0.6717 - rmse: 0.8920 - smape: 1.3058 - val_ia: 0.2576 - val_loss: 0.7599 - val_mae: 0.6427 - val_rmse: 0.7356 - val_smape: 1.2762

Epoch 50/128

958/958 - 14s - 14ms/step - ia: 0.3766 - loss: 0.8308 - mae: 0.6725 - rmse: 0.8931 - smape: 1.3073 - val_ia: 0.2572 - val_loss: 0.7605 - val_mae: 0.6431 - val_rmse: 0.7359 - val_smape: 1.2782

Epoch 51/128

958/958 - 15s - 15ms/step - ia: 0.3762 - loss: 0.8273 - mae: 0.6711 - rmse: 0.8932 - smape: 1.3057 - val_ia: 0.2576 - val_loss: 0.7592 - val_mae: 0.6425 - val_rmse: 0.7353 - val_smape: 1.2770

Epoch 52/128

958/958 - 18s - 19ms/step - ia: 0.3758 - loss: 0.8305 - mae: 0.6717 - rmse: 0.8946 - smape: 1.3042 - val_ia: 0.2576 - val_loss: 0.7589 - val_mae: 0.6424 - val_rmse: 0.7353 - val_smape: 1.2757

Epoch 53/128

958/958 - 13s - 13ms/step - ia: 0.3769 - loss: 0.8283 - mae: 0.6715 - rmse: 0.8924 - smape: 1.3063 - val_ia: 0.2577 - val_loss: 0.7585 - val_mae: 0.6423 - val_rmse: 0.7351 - val_smape: 1.2757

Epoch 54/128

958/958 - 15s - 15ms/step - ia: 0.3766 - loss: 0.8276 - mae: 0.6716 - rmse: 0.8917 - smape: 1.3064 - val_ia: 0.2576 - val_loss: 0.7585 - val_mae: 0.6422 - val_rmse: 0.7351 - val_smape: 1.2747

Epoch 55/128

958/958 - 14s - 15ms/step - ia: 0.3800 - loss: 0.8269 - mae: 0.6703 - rmse: 0.8909 - smape: 1.3031 - val_ia: 0.2577 - val_loss: 0.7581 - val_mae: 0.6421 - val_rmse: 0.7350 - val_smape: 1.2742

Epoch 56/128

958/958 - 15s - 15ms/step - ia: 0.3795 - loss: 0.8274 - mae: 0.6700 - rmse: 0.8911 - smape: 1.3009 - val_ia: 0.2576 - val_loss: 0.7577 - val_mae: 0.6420 - val_rmse: 0.7350 - val_smape: 1.2750

Epoch 57/128

958/958 - 14s - 15ms/step - ia: 0.3795 - loss: 0.8248 - mae: 0.6697 - rmse: 0.8900 - smape: 1.3016 - val_ia: 0.2573 - val_loss: 0.7580 - val_mae: 0.6423 - val_rmse: 0.7353 - val_smape: 1.2753

Epoch 58/128

958/958 - 13s - 13ms/step - ia: 0.3803 - loss: 0.8252 - mae: 0.6695 - rmse: 0.8911 - smape: 1.3001 - val_ia: 0.2577 - val_loss: 0.7568 - val_mae: 0.6420 - val_rmse: 0.7349 - val_smape: 1.2751

Epoch 59/128

958/958 - 13s - 13ms/step - ia: 0.3790 - loss: 0.8216 - mae: 0.6701 - rmse: 0.8888 - smape: 1.3029 - val_ia: 0.2578 - val_loss: 0.7568 - val_mae: 0.6419 - val_rmse: 0.7349 - val_smape: 1.2738

Epoch 60/128

958/958 - 16s - 17ms/step - ia: 0.3805 - loss: 0.8236 - mae: 0.6706 - rmse: 0.8898 - smape: 1.3036 - val_ia: 0.2576 - val_loss: 0.7569 - val_mae: 0.6417 - val_rmse: 0.7348 - val_smape: 1.2727

Epoch 61/128

958/958 - 17s - 18ms/step - ia: 0.3811 - loss: 0.8250 - mae: 0.6696 - rmse: 0.8894 - smape: 1.2978 - val_ia: 0.2576 - val_loss: 0.7563 - val_mae: 0.6415 - val_rmse: 0.7345 - val_smape: 1.2730

Epoch 62/128

958/958 - 17s - 18ms/step - ia: 0.3802 - loss: 0.8244 - mae: 0.6691 - rmse: 0.8906 - smape: 1.3005 - val_ia: 0.2575 - val_loss: 0.7566 - val_mae: 0.6417 - val_rmse: 0.7348 - val_smape: 1.2735

Epoch 63/128

958/958 - 14s - 14ms/step - ia: 0.3797 - loss: 0.8242 - mae: 0.6691 - rmse: 0.8904 - smape: 1.3010 - val_ia: 0.2577 - val_loss: 0.7562 - val_mae: 0.6413 - val_rmse: 0.7346 - val_smape: 1.2709

Epoch 64/128

958/958 - 18s - 19ms/step - ia: 0.3806 - loss: 0.8235 - mae: 0.6694 - rmse: 0.8911 - smape: 1.2997 - val_ia: 0.2578 - val_loss: 0.7553 - val_mae: 0.6408 - val_rmse: 0.7340 - val_smape: 1.2694

Epoch 65/128

958/958 - 18s - 18ms/step - ia: 0.3835 - loss: 0.8228 - mae: 0.6676 - rmse: 0.8894 - smape: 1.2953 - val_ia: 0.2579 - val_loss: 0.7550 - val_mae: 0.6408 - val_rmse: 0.7339 - val_smape: 1.2692

Epoch 66/128

958/958 - 17s - 18ms/step - ia: 0.3814 - loss: 0.8216 - mae: 0.6687 - rmse: 0.8889 - smape: 1.2984 - val_ia: 0.2577 - val_loss: 0.7547 - val_mae: 0.6409 - val_rmse: 0.7340 - val_smape: 1.2707

Epoch 67/128

958/958 - 15s - 16ms/step - ia: 0.3810 - loss: 0.8236 - mae: 0.6686 - rmse: 0.8902 - smape: 1.2987 - val_ia: 0.2576 - val_loss: 0.7546 - val_mae: 0.6409 - val_rmse: 0.7340 - val_smape: 1.2712

Epoch 68/128

958/958 - 16s - 17ms/step - ia: 0.3819 - loss: 0.8212 - mae: 0.6686 - rmse: 0.8889 - smape: 1.3002 - val_ia: 0.2576 - val_loss: 0.7542 - val_mae: 0.6408 - val_rmse: 0.7339 - val_smape: 1.2710

Epoch 69/128

958/958 - 16s - 17ms/step - ia: 0.3826 - loss: 0.8228 - mae: 0.6688 - rmse: 0.8893 - smape: 1.2976 - val_ia: 0.2578 - val_loss: 0.7537 - val_mae: 0.6405 - val_rmse: 0.7336 - val_smape: 1.2698

Epoch 70/128

958/958 - 15s - 15ms/step - ia: 0.3818 - loss: 0.8198 - mae: 0.6672 - rmse: 0.8873 - smape: 1.2977 - val_ia: 0.2578 - val_loss: 0.7538 - val_mae: 0.6407 - val_rmse: 0.7339 - val_smape: 1.2695

Epoch 71/128

958/958 - 13s - 13ms/step - ia: 0.3801 - loss: 0.8228 - mae: 0.6690 - rmse: 0.8890 - smape: 1.3007 - val_ia: 0.2578 - val_loss: 0.7534 - val_mae: 0.6404 - val_rmse: 0.7337 - val_smape: 1.2684

Epoch 72/128

958/958 - 16s - 17ms/step - ia: 0.3842 - loss: 0.8209 - mae: 0.6674 - rmse: 0.8884 - smape: 1.2966 - val_ia: 0.2576 - val_loss: 0.7534 - val_mae: 0.6405 - val_rmse: 0.7337 - val_smape: 1.2693

Epoch 73/128

958/958 - 15s - 15ms/step - ia: 0.3829 - loss: 0.8198 - mae: 0.6675 - rmse: 0.8876 - smape: 1.2991 - val_ia: 0.2577 - val_loss: 0.7528 - val_mae: 0.6403 - val_rmse: 0.7335 - val_smape: 1.2690

Epoch 74/128

958/958 - 22s - 23ms/step - ia: 0.3822 - loss: 0.8207 - mae: 0.6680 - rmse: 0.8890 - smape: 1.2980 - val_ia: 0.2575 - val_loss: 0.7531 - val_mae: 0.6406 - val_rmse: 0.7339 - val_smape: 1.2704

Epoch 75/128

958/958 - 16s - 17ms/step - ia: 0.3834 - loss: 0.8196 - mae: 0.6673 - rmse: 0.8880 - smape: 1.2951 - val_ia: 0.2574 - val_loss: 0.7532 - val_mae: 0.6404 - val_rmse: 0.7338 - val_smape: 1.2691

Epoch 76/128

958/958 - 15s - 15ms/step - ia: 0.3834 - loss: 0.8221 - mae: 0.6679 - rmse: 0.8882 - smape: 1.2989 - val_ia: 0.2576 - val_loss: 0.7521 - val_mae: 0.6402 - val_rmse: 0.7333 - val_smape: 1.2695

Epoch 77/128

958/958 - 22s - 23ms/step - ia: 0.3814 - loss: 0.8214 - mae: 0.6678 - rmse: 0.8891 - smape: 1.2977 - val_ia: 0.2575 - val_loss: 0.7525 - val_mae: 0.6404 - val_rmse: 0.7338 - val_smape: 1.2700

Epoch 78/128

958/958 - 14s - 15ms/step - ia: 0.3840 - loss: 0.8196 - mae: 0.6667 - rmse: 0.8866 - smape: 1.2940 - val_ia: 0.2575 - val_loss: 0.7520 - val_mae: 0.6401 - val_rmse: 0.7335 - val_smape: 1.2694

Epoch 79/128

958/958 - 16s - 17ms/step - ia: 0.3824 - loss: 0.8169 - mae: 0.6672 - rmse: 0.8864 - smape: 1.3000 - val_ia: 0.2576 - val_loss: 0.7517 - val_mae: 0.6397 - val_rmse: 0.7333 - val_smape: 1.2665

Epoch 80/128

958/958 - 19s - 20ms/step - ia: 0.3847 - loss: 0.8192 - mae: 0.6667 - rmse: 0.8869 - smape: 1.2955 - val_ia: 0.2576 - val_loss: 0.7513 - val_mae: 0.6397 - val_rmse: 0.7332 - val_smape: 1.2669

Epoch 81/128

958/958 - 16s - 17ms/step - ia: 0.3840 - loss: 0.8180 - mae: 0.6666 - rmse: 0.8880 - smape: 1.2961 - val_ia: 0.2575 - val_loss: 0.7514 - val_mae: 0.6399 - val_rmse: 0.7335 - val_smape: 1.2674

Epoch 82/128

958/958 - 15s - 15ms/step - ia: 0.3852 - loss: 0.8184 - mae: 0.6658 - rmse: 0.8875 - smape: 1.2921 - val_ia: 0.2575 - val_loss: 0.7514 - val_mae: 0.6400 - val_rmse: 0.7336 - val_smape: 1.2680

Epoch 83/128

958/958 - 12s - 13ms/step - ia: 0.3858 - loss: 0.8188 - mae: 0.6664 - rmse: 0.8863 - smape: 1.2920 - val_ia: 0.2575 - val_loss: 0.7513 - val_mae: 0.6401 - val_rmse: 0.7337 - val_smape: 1.2683

Epoch 84/128

958/958 - 12s - 13ms/step - ia: 0.3848 - loss: 0.8168 - mae: 0.6660 - rmse: 0.8858 - smape: 1.2951 - val_ia: 0.2575 - val_loss: 0.7507 - val_mae: 0.6398 - val_rmse: 0.7333 - val_smape: 1.2684

Epoch 85/128

958/958 - 22s - 23ms/step - ia: 0.3859 - loss: 0.8181 - mae: 0.6654 - rmse: 0.8855 - smape: 1.2951 - val_ia: 0.2573 - val_loss: 0.7513 - val_mae: 0.6402 - val_rmse: 0.7338 - val_smape: 1.2690

Epoch 86/128

958/958 - 13s - 14ms/step - ia: 0.3845 - loss: 0.8193 - mae: 0.6673 - rmse: 0.8881 - smape: 1.2952 - val_ia: 0.2574 - val_loss: 0.7507 - val_mae: 0.6401 - val_rmse: 0.7335 - val_smape: 1.2698

Epoch 87/128

958/958 - 12s - 13ms/step - ia: 0.3853 - loss: 0.8181 - mae: 0.6666 - rmse: 0.8857 - smape: 1.2954 - val_ia: 0.2576 - val_loss: 0.7500 - val_mae: 0.6398 - val_rmse: 0.7332 - val_smape: 1.2683

Epoch 88/128

958/958 - 14s - 15ms/step - ia: 0.3874 - loss: 0.8151 - mae: 0.6645 - rmse: 0.8855 - smape: 1.2908 - val_ia: 0.2575 - val_loss: 0.7502 - val_mae: 0.6399 - val_rmse: 0.7334 - val_smape: 1.2690

Epoch 89/128

958/958 - 14s - 15ms/step - ia: 0.3872 - loss: 0.8156 - mae: 0.6653 - rmse: 0.8853 - smape: 1.2925 - val_ia: 0.2577 - val_loss: 0.7492 - val_mae: 0.6392 - val_rmse: 0.7326 - val_smape: 1.2664

Epoch 90/128

958/958 - 21s - 22ms/step - ia: 0.3844 - loss: 0.8164 - mae: 0.6653 - rmse: 0.8857 - smape: 1.2933 - val_ia: 0.2577 - val_loss: 0.7492 - val_mae: 0.6391 - val_rmse: 0.7327 - val_smape: 1.2649

Epoch 91/128

958/958 - 15s - 16ms/step - ia: 0.3883 - loss: 0.8149 - mae: 0.6648 - rmse: 0.8847 - smape: 1.2893 - val_ia: 0.2576 - val_loss: 0.7488 - val_mae: 0.6391 - val_rmse: 0.7326 - val_smape: 1.2661

Epoch 92/128

958/958 - 15s - 15ms/step - ia: 0.3876 - loss: 0.8167 - mae: 0.6649 - rmse: 0.8850 - smape: 1.2900 - val_ia: 0.2575 - val_loss: 0.7493 - val_mae: 0.6396 - val_rmse: 0.7331 - val_smape: 1.2682

Epoch 93/128

958/958 - 15s - 16ms/step - ia: 0.3862 - loss: 0.8177 - mae: 0.6659 - rmse: 0.8859 - smape: 1.2919 - val_ia: 0.2575 - val_loss: 0.7488 - val_mae: 0.6394 - val_rmse: 0.7329 - val_smape: 1.2676

Epoch 94/128

958/958 - 14s - 14ms/step - ia: 0.3849 - loss: 0.8149 - mae: 0.6648 - rmse: 0.8855 - smape: 1.2920 - val_ia: 0.2574 - val_loss: 0.7497 - val_mae: 0.6395 - val_rmse: 0.7334 - val_smape: 1.2659

Epoch 95/128

958/958 - 15s - 16ms/step - ia: 0.3906 - loss: 0.8137 - mae: 0.6639 - rmse: 0.8839 - smape: 1.2867 - val_ia: 0.2576 - val_loss: 0.7477 - val_mae: 0.6390 - val_rmse: 0.7324 - val_smape: 1.2667

Epoch 96/128

958/958 - 15s - 16ms/step - ia: 0.3876 - loss: 0.8140 - mae: 0.6647 - rmse: 0.8847 - smape: 1.2903 - val_ia: 0.2577 - val_loss: 0.7474 - val_mae: 0.6389 - val_rmse: 0.7323 - val_smape: 1.2658

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 14s - 113ms/step - ia: 0.3813 - loss: 0.8263 - mae: 0.6669 - rmse: 0.9066 - smape: 1.2879 - val_ia: 0.3353 - val_loss: 0.7576 - val_mae: 0.6502 - val_rmse: 0.8089 - val_smape: 1.3056

Epoch 2/128

120/120 - 2s - 18ms/step - ia: 0.4061 - loss: 0.7981 - mae: 0.6515 - rmse: 0.8905 - smape: 1.2559 - val_ia: 0.3347 - val_loss: 0.7940 - val_mae: 0.6560 - val_rmse: 0.8187 - val_smape: 1.3344

Epoch 3/128

120/120 - 2s - 20ms/step - ia: 0.4194 - loss: 0.7765 - mae: 0.6434 - rmse: 0.8779 - smape: 1.2389 - val_ia: 0.3661 - val_loss: 0.7916 - val_mae: 0.6494 - val_rmse: 0.8216 - val_smape: 1.2368

Epoch 4/128

120/120 - 2s - 18ms/step - ia: 0.4281 - loss: 0.7658 - mae: 0.6372 - rmse: 0.8727 - smape: 1.2304 - val_ia: 0.3676 - val_loss: 0.7765 - val_mae: 0.6473 - val_rmse: 0.8219 - val_smape: 1.2622

Epoch 5/128

120/120 - 2s - 17ms/step - ia: 0.4455 - loss: 0.7371 - mae: 0.6253 - rmse: 0.8559 - smape: 1.2109 - val_ia: 0.3644 - val_loss: 0.7623 - val_mae: 0.6356 - val_rmse: 0.8019 - val_smape: 1.2358

Epoch 6/128

120/120 - 2s - 17ms/step - ia: 0.4558 - loss: 0.7172 - mae: 0.6162 - rmse: 0.8445 - smape: 1.2024 - val_ia: 0.3741 - val_loss: 0.7703 - val_mae: 0.6340 - val_rmse: 0.8094 - val_smape: 1.2436

Epoch 7/128

120/120 - 2s - 16ms/step - ia: 0.4663 - loss: 0.7014 - mae: 0.6098 - rmse: 0.8347 - smape: 1.1922 - val_ia: 0.3453 - val_loss: 0.7835 - val_mae: 0.6373 - val_rmse: 0.8072 - val_smape: 1.2664

Epoch 8/128

120/120 - 2s - 16ms/step - ia: 0.4760 - loss: 0.6735 - mae: 0.5997 - rmse: 0.8180 - smape: 1.1847 - val_ia: 0.3715 - val_loss: 0.7991 - val_mae: 0.6476 - val_rmse: 0.8250 - val_smape: 1.2575

Epoch 9/128

120/120 - 2s - 16ms/step - ia: 0.4868 - loss: 0.6513 - mae: 0.5909 - rmse: 0.8041 - smape: 1.1760 - val_ia: 0.3659 - val_loss: 0.9786 - val_mae: 0.6889 - val_rmse: 0.8979 - val_smape: 1.2704

Epoch 10/128

120/120 - 2s - 17ms/step - ia: 0.4849 - loss: 0.6596 - mae: 0.5939 - rmse: 0.8102 - smape: 1.1797 - val_ia: 0.3664 - val_loss: 0.8627 - val_mae: 0.6730 - val_rmse: 0.8567 - val_smape: 1.2639

Epoch 11/128

120/120 - 2s - 16ms/step - ia: 0.5027 - loss: 0.6252 - mae: 0.5798 - rmse: 0.7884 - smape: 1.1501 - val_ia: 0.3402 - val_loss: 0.8697 - val_mae: 0.6805 - val_rmse: 0.8589 - val_smape: 1.3356

Epoch 12/128

120/120 - 2s - 14ms/step - ia: 0.5006 - loss: 0.6323 - mae: 0.5806 - rmse: 0.7931 - smape: 1.1534 - val_ia: 0.3646 - val_loss: 0.9425 - val_mae: 0.6826 - val_rmse: 0.8848 - val_smape: 1.2479

Epoch 13/128

120/120 - 2s - 15ms/step - ia: 0.5150 - loss: 0.6030 - mae: 0.5706 - rmse: 0.7737 - smape: 1.1376 - val_ia: 0.3626 - val_loss: 0.8706 - val_mae: 0.6655 - val_rmse: 0.8525 - val_smape: 1.2351

Epoch 14/128

120/120 - 2s - 16ms/step - ia: 0.5233 - loss: 0.5818 - mae: 0.5616 - rmse: 0.7605 - smape: 1.1310 - val_ia: 0.3561 - val_loss: 0.9252 - val_mae: 0.6817 - val_rmse: 0.8807 - val_smape: 1.2397

Epoch 15/128

120/120 - 2s - 16ms/step - ia: 0.5127 - loss: 0.6032 - mae: 0.5693 - rmse: 0.7738 - smape: 1.1460 - val_ia: 0.3590 - val_loss: 0.9724 - val_mae: 0.6929 - val_rmse: 0.8961 - val_smape: 1.2628

Epoch 16/128

120/120 - 2s - 16ms/step - ia: 0.5274 - loss: 0.5729 - mae: 0.5592 - rmse: 0.7548 - smape: 1.1256 - val_ia: 0.3745 - val_loss: 0.9270 - val_mae: 0.6713 - val_rmse: 0.8745 - val_smape: 1.2102

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 55s 413ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 14%|█▍        | 7/50 [1:43:18<11:01:34, 923.12s/trial, best loss: 0.7730072598657926]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 52s - 27ms/step - ia: 0.3869 - loss: 0.8236 - mae: 0.6652 - rmse: 0.8729 - smape: 1.2802 - val_ia: 0.2644 - val_loss: 0.7433 - val_mae: 0.6183 - val_rmse: 0.6906 - val_smape: 1.1467

Epoch 2/8

1915/1915 - 31s - 16ms/step - ia: 0.4111 - loss: 0.7872 - mae: 0.6475 - rmse: 0.8549 - smape: 1.2457 - val_ia: 0.2584 - val_loss: 0.8006 - val_mae: 0.6515 - val_rmse: 0.7297 - val_smape: 1.1908

Epoch 3/8

1915/1915 - 41s - 21ms/step - ia: 0.4214 - loss: 0.7675 - mae: 0.6392 - rmse: 0.8437 - smape: 1.2254 - val_ia: 0.2481 - val_loss: 0.7576 - val_mae: 0.6436 - val_rmse: 0.7143 - val_smape: 1.2414

Epoch 4/8

1915/1915 - 31s - 16ms/step - ia: 0.4331 - loss: 0.7390 - mae: 0.6289 - rmse: 0.8277 - smape: 1.2157 - val_ia: 0.2533 - val_loss: 0.7469 - val_mae: 0.6234 - val_rmse: 0.6975 - val_smape: 1.2112

Epoch 5/8

1915/1915 - 29s - 15ms/step - ia: 0.4465 - loss: 0.7132 - mae: 0.6177 - rmse: 0.8133 - smape: 1.2011 - val_ia: 0.2487 - val_loss: 0.7786 - val_mae: 0.6422 - val_rmse: 0.7167 - val_smape: 1.2501

Epoch 6/8

1915/1915 - 30s - 16ms/step - ia: 0.4581 - loss: 0.6845 - mae: 0.6063 - rmse: 0.7967 - smape: 1.1840 - val_ia: 0.2503 - val_loss: 0.8228 - val_mae: 0.6588 - val_rmse: 0.7408 - val_smape: 1.2343

Epoch 7/8

1915/1915 - 30s - 16ms/step - ia: 0.4685 - loss: 0.6550 - mae: 0.5958 - rmse: 0.7798 - smape: 1.1732 - val_ia: 0.2485 - val_loss: 0.8043 - val_mae: 0.6480 - val_rmse: 0.7228 - val_smape: 1.2693

Epoch 8/8

1915/1915 - 33s - 17ms/step - ia: 0.4811 - loss: 0.6254 - mae: 0.5841 - rmse: 0.7629 - smape: 1.1607 - val_ia: 0.2351 - val_loss: 0.8915 - val_mae: 0.6855 - val_rmse: 0.7617 - val_smape: 1.3150

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:14 2s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 16%|█▌        | 8/50 [1:47:59<8:23:01, 718.61s/trial, best loss: 0.7672588490218757]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 10s - 85ms/step - ia: 0.3081 - loss: 1.0602 - mae: 0.7634 - rmse: 1.0250 - smape: 1.3997 - val_ia: 0.3204 - val_loss: 0.7880 - val_mae: 0.6612 - val_rmse: 0.8199 - val_smape: 1.3590

Epoch 2/128

120/120 - 1s - 9ms/step - ia: 0.3647 - loss: 0.8542 - mae: 0.6817 - rmse: 0.9220 - smape: 1.3242 - val_ia: 0.3284 - val_loss: 0.7639 - val_mae: 0.6456 - val_rmse: 0.8052 - val_smape: 1.3014

Epoch 3/128

120/120 - 1s - 10ms/step - ia: 0.3716 - loss: 0.8346 - mae: 0.6719 - rmse: 0.9101 - smape: 1.3101 - val_ia: 0.3299 - val_loss: 0.7589 - val_mae: 0.6458 - val_rmse: 0.8048 - val_smape: 1.2953

Epoch 4/128

120/120 - 1s - 9ms/step - ia: 0.3745 - loss: 0.8287 - mae: 0.6686 - rmse: 0.9072 - smape: 1.3027 - val_ia: 0.3323 - val_loss: 0.7543 - val_mae: 0.6418 - val_rmse: 0.8017 - val_smape: 1.2848

Epoch 5/128

120/120 - 1s - 9ms/step - ia: 0.3814 - loss: 0.8194 - mae: 0.6650 - rmse: 0.9028 - smape: 1.2939 - val_ia: 0.3304 - val_loss: 0.7534 - val_mae: 0.6446 - val_rmse: 0.8032 - val_smape: 1.2875

Epoch 6/128

120/120 - 1s - 11ms/step - ia: 0.3805 - loss: 0.8198 - mae: 0.6643 - rmse: 0.9027 - smape: 1.2949 - val_ia: 0.3374 - val_loss: 0.7541 - val_mae: 0.6429 - val_rmse: 0.8036 - val_smape: 1.2791

Epoch 7/128

120/120 - 1s - 8ms/step - ia: 0.3809 - loss: 0.8186 - mae: 0.6633 - rmse: 0.9023 - smape: 1.2912 - val_ia: 0.3478 - val_loss: 0.7525 - val_mae: 0.6427 - val_rmse: 0.8052 - val_smape: 1.2611

Epoch 8/128

120/120 - 1s - 8ms/step - ia: 0.3872 - loss: 0.8132 - mae: 0.6616 - rmse: 0.8992 - smape: 1.2846 - val_ia: 0.3418 - val_loss: 0.7506 - val_mae: 0.6406 - val_rmse: 0.8023 - val_smape: 1.2627

Epoch 9/128

120/120 - 1s - 8ms/step - ia: 0.3873 - loss: 0.8104 - mae: 0.6605 - rmse: 0.8974 - smape: 1.2839 - val_ia: 0.3471 - val_loss: 0.7529 - val_mae: 0.6410 - val_rmse: 0.8043 - val_smape: 1.2598

Epoch 10/128

120/120 - 1s - 9ms/step - ia: 0.3882 - loss: 0.8106 - mae: 0.6598 - rmse: 0.8978 - smape: 1.2836 - val_ia: 0.3462 - val_loss: 0.7571 - val_mae: 0.6441 - val_rmse: 0.8072 - val_smape: 1.2755

Epoch 11/128

120/120 - 1s - 8ms/step - ia: 0.3917 - loss: 0.8057 - mae: 0.6585 - rmse: 0.8949 - smape: 1.2782 - val_ia: 0.3438 - val_loss: 0.7508 - val_mae: 0.6377 - val_rmse: 0.8009 - val_smape: 1.2527

Epoch 12/128

120/120 - 1s - 7ms/step - ia: 0.3906 - loss: 0.8069 - mae: 0.6578 - rmse: 0.8957 - smape: 1.2797 - val_ia: 0.3534 - val_loss: 0.7568 - val_mae: 0.6421 - val_rmse: 0.8072 - val_smape: 1.2503

Epoch 13/128

120/120 - 1s - 7ms/step - ia: 0.3933 - loss: 0.8054 - mae: 0.6579 - rmse: 0.8940 - smape: 1.2776 - val_ia: 0.3418 - val_loss: 0.7519 - val_mae: 0.6400 - val_rmse: 0.8020 - val_smape: 1.2666

Epoch 14/128

120/120 - 1s - 8ms/step - ia: 0.3965 - loss: 0.8012 - mae: 0.6560 - rmse: 0.8919 - smape: 1.2702 - val_ia: 0.3567 - val_loss: 0.7521 - val_mae: 0.6350 - val_rmse: 0.8016 - val_smape: 1.2241

Epoch 15/128

120/120 - 1s - 8ms/step - ia: 0.3948 - loss: 0.8031 - mae: 0.6565 - rmse: 0.8934 - smape: 1.2762 - val_ia: 0.3511 - val_loss: 0.7552 - val_mae: 0.6404 - val_rmse: 0.8049 - val_smape: 1.2463

Epoch 16/128

120/120 - 1s - 8ms/step - ia: 0.3968 - loss: 0.8008 - mae: 0.6556 - rmse: 0.8916 - smape: 1.2709 - val_ia: 0.3415 - val_loss: 0.7512 - val_mae: 0.6412 - val_rmse: 0.8029 - val_smape: 1.2673

Epoch 17/128

120/120 - 1s - 8ms/step - ia: 0.3980 - loss: 0.7981 - mae: 0.6544 - rmse: 0.8914 - smape: 1.2706 - val_ia: 0.3475 - val_loss: 0.7497 - val_mae: 0.6375 - val_rmse: 0.8010 - val_smape: 1.2490

Epoch 18/128

120/120 - 1s - 8ms/step - ia: 0.4009 - loss: 0.7980 - mae: 0.6529 - rmse: 0.8908 - smape: 1.2635 - val_ia: 0.3628 - val_loss: 0.7708 - val_mae: 0.6467 - val_rmse: 0.8164 - val_smape: 1.2442

Epoch 19/128

120/120 - 1s - 8ms/step - ia: 0.4003 - loss: 0.7986 - mae: 0.6551 - rmse: 0.8907 - smape: 1.2656 - val_ia: 0.3435 - val_loss: 0.7545 - val_mae: 0.6424 - val_rmse: 0.8047 - val_smape: 1.2597

Epoch 20/128

120/120 - 1s - 8ms/step - ia: 0.3993 - loss: 0.7950 - mae: 0.6545 - rmse: 0.8893 - smape: 1.2701 - val_ia: 0.3522 - val_loss: 0.7499 - val_mae: 0.6361 - val_rmse: 0.8009 - val_smape: 1.2478

Epoch 21/128

120/120 - 1s - 8ms/step - ia: 0.4014 - loss: 0.7940 - mae: 0.6536 - rmse: 0.8887 - smape: 1.2672 - val_ia: 0.3485 - val_loss: 0.7573 - val_mae: 0.6419 - val_rmse: 0.8058 - val_smape: 1.2522

Epoch 22/128

120/120 - 1s - 8ms/step - ia: 0.4025 - loss: 0.7896 - mae: 0.6528 - rmse: 0.8860 - smape: 1.2644 - val_ia: 0.3630 - val_loss: 0.7631 - val_mae: 0.6417 - val_rmse: 0.8106 - val_smape: 1.2320

Epoch 23/128

120/120 - 1s - 7ms/step - ia: 0.4067 - loss: 0.7899 - mae: 0.6515 - rmse: 0.8868 - smape: 1.2608 - val_ia: 0.3537 - val_loss: 0.7635 - val_mae: 0.6447 - val_rmse: 0.8107 - val_smape: 1.2549

Epoch 24/128

120/120 - 1s - 7ms/step - ia: 0.4059 - loss: 0.7854 - mae: 0.6507 - rmse: 0.8841 - smape: 1.2633 - val_ia: 0.3551 - val_loss: 0.7618 - val_mae: 0.6420 - val_rmse: 0.8086 - val_smape: 1.2510

Epoch 25/128

120/120 - 1s - 8ms/step - ia: 0.4047 - loss: 0.7875 - mae: 0.6511 - rmse: 0.8847 - smape: 1.2645 - val_ia: 0.3585 - val_loss: 0.7627 - val_mae: 0.6388 - val_rmse: 0.8069 - val_smape: 1.2415

Epoch 26/128

120/120 - 1s - 8ms/step - ia: 0.4085 - loss: 0.7857 - mae: 0.6503 - rmse: 0.8833 - smape: 1.2601 - val_ia: 0.3541 - val_loss: 0.7559 - val_mae: 0.6337 - val_rmse: 0.8009 - val_smape: 1.2298

Epoch 27/128

120/120 - 1s - 7ms/step - ia: 0.4098 - loss: 0.7823 - mae: 0.6480 - rmse: 0.8818 - smape: 1.2581 - val_ia: 0.3542 - val_loss: 0.7661 - val_mae: 0.6439 - val_rmse: 0.8107 - val_smape: 1.2570

Epoch 28/128

120/120 - 1s - 7ms/step - ia: 0.4067 - loss: 0.7830 - mae: 0.6493 - rmse: 0.8827 - smape: 1.2619 - val_ia: 0.3553 - val_loss: 0.7587 - val_mae: 0.6418 - val_rmse: 0.8075 - val_smape: 1.2479

Epoch 29/128

120/120 - 1s - 7ms/step - ia: 0.4114 - loss: 0.7807 - mae: 0.6485 - rmse: 0.8805 - smape: 1.2582 - val_ia: 0.3566 - val_loss: 0.7605 - val_mae: 0.6415 - val_rmse: 0.8081 - val_smape: 1.2549

Epoch 30/128

120/120 - 1s - 7ms/step - ia: 0.4113 - loss: 0.7768 - mae: 0.6467 - rmse: 0.8789 - smape: 1.2587 - val_ia: 0.3588 - val_loss: 0.7626 - val_mae: 0.6365 - val_rmse: 0.8057 - val_smape: 1.2365

Epoch 31/128

120/120 - 1s - 7ms/step - ia: 0.4131 - loss: 0.7759 - mae: 0.6469 - rmse: 0.8786 - smape: 1.2555 - val_ia: 0.3494 - val_loss: 0.7575 - val_mae: 0.6414 - val_rmse: 0.8053 - val_smape: 1.2503

Epoch 32/128

120/120 - 1s - 11ms/step - ia: 0.4121 - loss: 0.7760 - mae: 0.6467 - rmse: 0.8787 - smape: 1.2573 - val_ia: 0.3566 - val_loss: 0.7697 - val_mae: 0.6395 - val_rmse: 0.8087 - val_smape: 1.2445

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:10 524ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 18%|█▊        | 9/50 [1:48:41<5:46:37, 507.25s/trial, best loss: 0.7672588490218757]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 48s - 50ms/step - ia: 0.3381 - loss: 0.8514 - mae: 0.6824 - rmse: 0.9051 - smape: 1.3663 - val_ia: 0.2559 - val_loss: 0.7690 - val_mae: 0.6455 - val_rmse: 0.7384 - val_smape: 1.2752

Epoch 2/16

958/958 - 20s - 21ms/step - ia: 0.3891 - loss: 0.8100 - mae: 0.6601 - rmse: 0.8829 - smape: 1.2782 - val_ia: 0.2573 - val_loss: 0.7685 - val_mae: 0.6486 - val_rmse: 0.7451 - val_smape: 1.2586

Epoch 3/16

958/958 - 16s - 16ms/step - ia: 0.4018 - loss: 0.7975 - mae: 0.6535 - rmse: 0.8750 - smape: 1.2603 - val_ia: 0.2561 - val_loss: 0.7698 - val_mae: 0.6520 - val_rmse: 0.7477 - val_smape: 1.2858

Epoch 4/16

958/958 - 20s - 21ms/step - ia: 0.4051 - loss: 0.7933 - mae: 0.6504 - rmse: 0.8719 - smape: 1.2536 - val_ia: 0.2575 - val_loss: 0.7768 - val_mae: 0.6512 - val_rmse: 0.7482 - val_smape: 1.2662

Epoch 5/16

958/958 - 20s - 21ms/step - ia: 0.4115 - loss: 0.7850 - mae: 0.6462 - rmse: 0.8686 - smape: 1.2442 - val_ia: 0.2590 - val_loss: 0.7619 - val_mae: 0.6442 - val_rmse: 0.7405 - val_smape: 1.2621

Epoch 6/16

958/958 - 20s - 21ms/step - ia: 0.4169 - loss: 0.7777 - mae: 0.6434 - rmse: 0.8642 - smape: 1.2388 - val_ia: 0.2604 - val_loss: 0.7749 - val_mae: 0.6484 - val_rmse: 0.7462 - val_smape: 1.2586

Epoch 7/16

958/958 - 21s - 21ms/step - ia: 0.4212 - loss: 0.7735 - mae: 0.6408 - rmse: 0.8615 - smape: 1.2324 - val_ia: 0.2597 - val_loss: 0.7730 - val_mae: 0.6528 - val_rmse: 0.7485 - val_smape: 1.2887

Epoch 8/16

958/958 - 21s - 21ms/step - ia: 0.4244 - loss: 0.7666 - mae: 0.6386 - rmse: 0.8567 - smape: 1.2282 - val_ia: 0.2629 - val_loss: 0.8051 - val_mae: 0.6588 - val_rmse: 0.7598 - val_smape: 1.2571

Epoch 9/16

958/958 - 21s - 22ms/step - ia: 0.4299 - loss: 0.7594 - mae: 0.6359 - rmse: 0.8543 - smape: 1.2208 - val_ia: 0.2612 - val_loss: 0.7768 - val_mae: 0.6507 - val_rmse: 0.7470 - val_smape: 1.2730

Epoch 10/16

958/958 - 19s - 20ms/step - ia: 0.4325 - loss: 0.7573 - mae: 0.6333 - rmse: 0.8520 - smape: 1.2145 - val_ia: 0.2620 - val_loss: 0.7982 - val_mae: 0.6574 - val_rmse: 0.7568 - val_smape: 1.2825

Epoch 11/16

958/958 - 17s - 18ms/step - ia: 0.4337 - loss: 0.7528 - mae: 0.6315 - rmse: 0.8499 - smape: 1.2124 - val_ia: 0.2626 - val_loss: 0.7717 - val_mae: 0.6483 - val_rmse: 0.7449 - val_smape: 1.2785

Epoch 12/16

958/958 - 17s - 18ms/step - ia: 0.4365 - loss: 0.7473 - mae: 0.6298 - rmse: 0.8466 - smape: 1.2093 - val_ia: 0.2615 - val_loss: 0.7718 - val_mae: 0.6489 - val_rmse: 0.7452 - val_smape: 1.2834

Epoch 13/16

958/958 - 19s - 19ms/step - ia: 0.4372 - loss: 0.7412 - mae: 0.6274 - rmse: 0.8441 - smape: 1.2080 - val_ia: 0.2671 - val_loss: 0.8332 - val_mae: 0.6728 - val_rmse: 0.7751 - val_smape: 1.3044

Epoch 14/16

958/958 - 17s - 18ms/step - ia: 0.4415 - loss: 0.7359 - mae: 0.6251 - rmse: 0.8398 - smape: 1.2014 - val_ia: 0.2651 - val_loss: 0.7872 - val_mae: 0.6570 - val_rmse: 0.7552 - val_smape: 1.3116

Epoch 15/16

958/958 - 18s - 18ms/step - ia: 0.4445 - loss: 0.7317 - mae: 0.6229 - rmse: 0.8375 - smape: 1.1997 - val_ia: 0.2661 - val_loss: 0.7898 - val_mae: 0.6560 - val_rmse: 0.7567 - val_smape: 1.2901

Epoch 16/16

958/958 - 18s - 19ms/step - ia: 0.4464 - loss: 0.7296 - mae: 0.6218 - rmse: 0.8361 - smape: 1.1977 - val_ia: 0.2661 - val_loss: 0.7886 - val_mae: 0.6561 - val_rmse: 0.7560 - val_smape: 1.2906

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:21 1s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 20%|██        | 10/50 [1:54:15<5:02:29, 453.74s/trial, best loss: 0.7672588490218757]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 13s - 56ms/step - ia: 0.2940 - loss: 3.2896 - mae: 1.3677 - rmse: 1.8069 - smape: 1.4272 - val_ia: 0.3063 - val_loss: 1.2112 - val_mae: 0.8438 - val_rmse: 1.0296 - val_smape: 1.2963

Epoch 2/8

240/240 - 4s - 16ms/step - ia: 0.2926 - loss: 3.3104 - mae: 1.3698 - rmse: 1.8119 - smape: 1.4294 - val_ia: 0.3070 - val_loss: 1.2059 - val_mae: 0.8417 - val_rmse: 1.0271 - val_smape: 1.2978

Epoch 3/8

240/240 - 3s - 11ms/step - ia: 0.2944 - loss: 3.2615 - mae: 1.3648 - rmse: 1.7983 - smape: 1.4261 - val_ia: 0.3075 - val_loss: 1.2006 - val_mae: 0.8396 - val_rmse: 1.0246 - val_smape: 1.2989

Epoch 4/8

240/240 - 3s - 11ms/step - ia: 0.2962 - loss: 3.2071 - mae: 1.3540 - rmse: 1.7835 - smape: 1.4268 - val_ia: 0.3081 - val_loss: 1.1957 - val_mae: 0.8376 - val_rmse: 1.0223 - val_smape: 1.3002

Epoch 5/8

240/240 - 3s - 11ms/step - ia: 0.2973 - loss: 3.1948 - mae: 1.3507 - rmse: 1.7786 - smape: 1.4241 - val_ia: 0.3086 - val_loss: 1.1909 - val_mae: 0.8357 - val_rmse: 1.0200 - val_smape: 1.3014

Epoch 6/8

240/240 - 2s - 10ms/step - ia: 0.2947 - loss: 3.1532 - mae: 1.3445 - rmse: 1.7695 - smape: 1.4281 - val_ia: 0.3091 - val_loss: 1.1863 - val_mae: 0.8339 - val_rmse: 1.0179 - val_smape: 1.3025

Epoch 7/8

240/240 - 2s - 10ms/step - ia: 0.2972 - loss: 3.1584 - mae: 1.3396 - rmse: 1.7688 - smape: 1.4237 - val_ia: 0.3096 - val_loss: 1.1818 - val_mae: 0.8321 - val_rmse: 1.0158 - val_smape: 1.3036

Epoch 8/8

240/240 - 3s - 11ms/step - ia: 0.2936 - loss: 3.1835 - mae: 1.3414 - rmse: 1.7773 - smape: 1.4294 - val_ia: 0.3101 - val_loss: 1.1773 - val_mae: 0.8302 - val_rmse: 1.0137 - val_smape: 1.3048

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:26 643ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step

 22%|██▏       | 11/50 [1:54:51<3:31:45, 325.79s/trial, best loss: 0.7672588490218757]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 20s - 21ms/step - ia: 0.3417 - loss: 0.9449 - mae: 0.7243 - rmse: 0.9527 - smape: 1.3590 - val_ia: 0.2601 - val_loss: 0.7708 - val_mae: 0.6456 - val_rmse: 0.7387 - val_smape: 1.2790

Epoch 2/128

958/958 - 19s - 20ms/step - ia: 0.3787 - loss: 0.8622 - mae: 0.6875 - rmse: 0.9112 - smape: 1.3014 - val_ia: 0.2580 - val_loss: 0.7800 - val_mae: 0.6607 - val_rmse: 0.7552 - val_smape: 1.3048

Epoch 3/128

958/958 - 10s - 10ms/step - ia: 0.3835 - loss: 0.8390 - mae: 0.6763 - rmse: 0.8985 - smape: 1.2882 - val_ia: 0.2604 - val_loss: 0.7622 - val_mae: 0.6424 - val_rmse: 0.7358 - val_smape: 1.2660

Epoch 4/128

958/958 - 9s - 10ms/step - ia: 0.3862 - loss: 0.8299 - mae: 0.6715 - rmse: 0.8939 - smape: 1.2839 - val_ia: 0.2581 - val_loss: 0.7614 - val_mae: 0.6356 - val_rmse: 0.7292 - val_smape: 1.2415

Epoch 5/128

958/958 - 8s - 9ms/step - ia: 0.3866 - loss: 0.8254 - mae: 0.6693 - rmse: 0.8914 - smape: 1.2814 - val_ia: 0.2591 - val_loss: 0.7575 - val_mae: 0.6381 - val_rmse: 0.7329 - val_smape: 1.2468

Epoch 6/128

958/958 - 8s - 8ms/step - ia: 0.3908 - loss: 0.8178 - mae: 0.6664 - rmse: 0.8861 - smape: 1.2795 - val_ia: 0.2575 - val_loss: 0.7558 - val_mae: 0.6436 - val_rmse: 0.7372 - val_smape: 1.2730

Epoch 7/128

958/958 - 8s - 9ms/step - ia: 0.3935 - loss: 0.8135 - mae: 0.6633 - rmse: 0.8844 - smape: 1.2718 - val_ia: 0.2585 - val_loss: 0.7460 - val_mae: 0.6271 - val_rmse: 0.7211 - val_smape: 1.2162

Epoch 8/128

958/958 - 8s - 8ms/step - ia: 0.3936 - loss: 0.8079 - mae: 0.6611 - rmse: 0.8816 - smape: 1.2730 - val_ia: 0.2582 - val_loss: 0.7550 - val_mae: 0.6365 - val_rmse: 0.7337 - val_smape: 1.2285

Epoch 9/128

958/958 - 8s - 8ms/step - ia: 0.3986 - loss: 0.8053 - mae: 0.6596 - rmse: 0.8796 - smape: 1.2659 - val_ia: 0.2580 - val_loss: 0.7420 - val_mae: 0.6304 - val_rmse: 0.7244 - val_smape: 1.2346

Epoch 10/128

958/958 - 8s - 8ms/step - ia: 0.3999 - loss: 0.8016 - mae: 0.6575 - rmse: 0.8775 - smape: 1.2641 - val_ia: 0.2580 - val_loss: 0.7459 - val_mae: 0.6396 - val_rmse: 0.7335 - val_smape: 1.2633

Epoch 11/128

958/958 - 8s - 8ms/step - ia: 0.4013 - loss: 0.7985 - mae: 0.6562 - rmse: 0.8746 - smape: 1.2634 - val_ia: 0.2578 - val_loss: 0.7428 - val_mae: 0.6304 - val_rmse: 0.7261 - val_smape: 1.2282

Epoch 12/128

958/958 - 8s - 9ms/step - ia: 0.4046 - loss: 0.7972 - mae: 0.6543 - rmse: 0.8757 - smape: 1.2583 - val_ia: 0.2589 - val_loss: 0.7428 - val_mae: 0.6314 - val_rmse: 0.7273 - val_smape: 1.2293

Epoch 13/128

958/958 - 10s - 10ms/step - ia: 0.4091 - loss: 0.7917 - mae: 0.6516 - rmse: 0.8722 - smape: 1.2531 - val_ia: 0.2576 - val_loss: 0.7380 - val_mae: 0.6301 - val_rmse: 0.7230 - val_smape: 1.2545

Epoch 14/128

958/958 - 10s - 10ms/step - ia: 0.4095 - loss: 0.7884 - mae: 0.6504 - rmse: 0.8703 - smape: 1.2498 - val_ia: 0.2614 - val_loss: 0.7457 - val_mae: 0.6307 - val_rmse: 0.7282 - val_smape: 1.2154

Epoch 15/128

958/958 - 9s - 9ms/step - ia: 0.4109 - loss: 0.7870 - mae: 0.6489 - rmse: 0.8692 - smape: 1.2494 - val_ia: 0.2606 - val_loss: 0.7531 - val_mae: 0.6436 - val_rmse: 0.7403 - val_smape: 1.2516

Epoch 16/128

958/958 - 9s - 9ms/step - ia: 0.4163 - loss: 0.7821 - mae: 0.6462 - rmse: 0.8651 - smape: 1.2405 - val_ia: 0.2615 - val_loss: 0.7433 - val_mae: 0.6375 - val_rmse: 0.7318 - val_smape: 1.2644

Epoch 17/128

958/958 - 9s - 10ms/step - ia: 0.4147 - loss: 0.7826 - mae: 0.6469 - rmse: 0.8670 - smape: 1.2457 - val_ia: 0.2630 - val_loss: 0.7426 - val_mae: 0.6258 - val_rmse: 0.7231 - val_smape: 1.2042

Epoch 18/128

958/958 - 9s - 9ms/step - ia: 0.4187 - loss: 0.7792 - mae: 0.6444 - rmse: 0.8642 - smape: 1.2362 - val_ia: 0.2636 - val_loss: 0.7322 - val_mae: 0.6191 - val_rmse: 0.7143 - val_smape: 1.2076

Epoch 19/128

958/958 - 7s - 7ms/step - ia: 0.4180 - loss: 0.7772 - mae: 0.6439 - rmse: 0.8645 - smape: 1.2390 - val_ia: 0.2639 - val_loss: 0.7564 - val_mae: 0.6456 - val_rmse: 0.7427 - val_smape: 1.2613

Epoch 20/128

958/958 - 9s - 10ms/step - ia: 0.4213 - loss: 0.7738 - mae: 0.6427 - rmse: 0.8628 - smape: 1.2338 - val_ia: 0.2618 - val_loss: 0.7557 - val_mae: 0.6336 - val_rmse: 0.7308 - val_smape: 1.2281

Epoch 21/128

958/958 - 9s - 9ms/step - ia: 0.4225 - loss: 0.7709 - mae: 0.6408 - rmse: 0.8609 - smape: 1.2305 - val_ia: 0.2624 - val_loss: 0.7450 - val_mae: 0.6320 - val_rmse: 0.7272 - val_smape: 1.2459

Epoch 22/128

958/958 - 9s - 10ms/step - ia: 0.4223 - loss: 0.7704 - mae: 0.6404 - rmse: 0.8600 - smape: 1.2326 - val_ia: 0.2678 - val_loss: 0.7728 - val_mae: 0.6528 - val_rmse: 0.7525 - val_smape: 1.2539

Epoch 23/128

958/958 - 9s - 10ms/step - ia: 0.4244 - loss: 0.7694 - mae: 0.6401 - rmse: 0.8598 - smape: 1.2313 - val_ia: 0.2657 - val_loss: 0.7554 - val_mae: 0.6414 - val_rmse: 0.7377 - val_smape: 1.2579

Epoch 24/128

958/958 - 9s - 10ms/step - ia: 0.4245 - loss: 0.7669 - mae: 0.6388 - rmse: 0.8574 - smape: 1.2293 - val_ia: 0.2636 - val_loss: 0.7472 - val_mae: 0.6295 - val_rmse: 0.7257 - val_smape: 1.2298

Epoch 25/128

958/958 - 9s - 10ms/step - ia: 0.4268 - loss: 0.7635 - mae: 0.6371 - rmse: 0.8560 - smape: 1.2258 - val_ia: 0.2663 - val_loss: 0.7523 - val_mae: 0.6385 - val_rmse: 0.7352 - val_smape: 1.2488

Epoch 26/128

958/958 - 9s - 10ms/step - ia: 0.4276 - loss: 0.7648 - mae: 0.6377 - rmse: 0.8567 - smape: 1.2267 - val_ia: 0.2645 - val_loss: 0.7565 - val_mae: 0.6383 - val_rmse: 0.7358 - val_smape: 1.2340

Epoch 27/128

958/958 - 9s - 10ms/step - ia: 0.4292 - loss: 0.7605 - mae: 0.6357 - rmse: 0.8540 - smape: 1.2216 - val_ia: 0.2667 - val_loss: 0.7665 - val_mae: 0.6419 - val_rmse: 0.7411 - val_smape: 1.2335

Epoch 28/128

958/958 - 9s - 9ms/step - ia: 0.4297 - loss: 0.7595 - mae: 0.6350 - rmse: 0.8536 - smape: 1.2204 - val_ia: 0.2686 - val_loss: 0.7587 - val_mae: 0.6370 - val_rmse: 0.7356 - val_smape: 1.2338

Epoch 29/128

958/958 - 8s - 8ms/step - ia: 0.4309 - loss: 0.7566 - mae: 0.6346 - rmse: 0.8518 - smape: 1.2225 - val_ia: 0.2682 - val_loss: 0.7857 - val_mae: 0.6548 - val_rmse: 0.7551 - val_smape: 1.2534

Epoch 30/128

958/958 - 9s - 9ms/step - ia: 0.4320 - loss: 0.7562 - mae: 0.6336 - rmse: 0.8519 - smape: 1.2186 - val_ia: 0.2673 - val_loss: 0.7637 - val_mae: 0.6369 - val_rmse: 0.7362 - val_smape: 1.2240

Epoch 31/128

958/958 - 9s - 9ms/step - ia: 0.4340 - loss: 0.7544 - mae: 0.6323 - rmse: 0.8509 - smape: 1.2155 - val_ia: 0.2662 - val_loss: 0.7581 - val_mae: 0.6332 - val_rmse: 0.7314 - val_smape: 1.2238

Epoch 32/128

958/958 - 9s - 9ms/step - ia: 0.4345 - loss: 0.7517 - mae: 0.6316 - rmse: 0.8490 - smape: 1.2162 - val_ia: 0.2703 - val_loss: 0.7804 - val_mae: 0.6543 - val_rmse: 0.7533 - val_smape: 1.2712

Epoch 33/128

958/958 - 9s - 10ms/step - ia: 0.4352 - loss: 0.7498 - mae: 0.6305 - rmse: 0.8489 - smape: 1.2144 - val_ia: 0.2688 - val_loss: 0.7671 - val_mae: 0.6403 - val_rmse: 0.7405 - val_smape: 1.2241

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:08 954ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 24%|██▍       | 12/50 [2:00:05<3:24:09, 322.34s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 30s - 125ms/step - ia: 0.3428 - loss: 0.8658 - mae: 0.6903 - rmse: 0.9248 - smape: 1.3539 - val_ia: 0.3132 - val_loss: 0.7633 - val_mae: 0.6359 - val_rmse: 0.7834 - val_smape: 1.2330

Epoch 2/16

240/240 - 7s - 29ms/step - ia: 0.3721 - loss: 0.8230 - mae: 0.6704 - rmse: 0.9021 - smape: 1.3138 - val_ia: 0.3232 - val_loss: 0.7533 - val_mae: 0.6386 - val_rmse: 0.7854 - val_smape: 1.2603

Epoch 3/16

240/240 - 5s - 20ms/step - ia: 0.3856 - loss: 0.8111 - mae: 0.6632 - rmse: 0.8950 - smape: 1.2923 - val_ia: 0.3216 - val_loss: 0.7432 - val_mae: 0.6344 - val_rmse: 0.7794 - val_smape: 1.2685

Epoch 4/16

240/240 - 5s - 19ms/step - ia: 0.3898 - loss: 0.8062 - mae: 0.6593 - rmse: 0.8931 - smape: 1.2888 - val_ia: 0.3323 - val_loss: 0.7378 - val_mae: 0.6287 - val_rmse: 0.7770 - val_smape: 1.2164

Epoch 5/16

240/240 - 5s - 20ms/step - ia: 0.3993 - loss: 0.7974 - mae: 0.6547 - rmse: 0.8879 - smape: 1.2740 - val_ia: 0.3338 - val_loss: 0.7585 - val_mae: 0.6457 - val_rmse: 0.7957 - val_smape: 1.2819

Epoch 6/16

240/240 - 4s - 18ms/step - ia: 0.4033 - loss: 0.7935 - mae: 0.6519 - rmse: 0.8857 - smape: 1.2691 - val_ia: 0.3312 - val_loss: 0.7442 - val_mae: 0.6373 - val_rmse: 0.7846 - val_smape: 1.2627

Epoch 7/16

240/240 - 4s - 18ms/step - ia: 0.4084 - loss: 0.7861 - mae: 0.6491 - rmse: 0.8816 - smape: 1.2632 - val_ia: 0.3345 - val_loss: 0.7424 - val_mae: 0.6347 - val_rmse: 0.7832 - val_smape: 1.2596

Epoch 8/16

240/240 - 4s - 16ms/step - ia: 0.4125 - loss: 0.7817 - mae: 0.6471 - rmse: 0.8796 - smape: 1.2555 - val_ia: 0.3393 - val_loss: 0.7436 - val_mae: 0.6259 - val_rmse: 0.7790 - val_smape: 1.2178

Epoch 9/16

240/240 - 4s - 16ms/step - ia: 0.4160 - loss: 0.7778 - mae: 0.6441 - rmse: 0.8783 - smape: 1.2483 - val_ia: 0.3425 - val_loss: 0.7564 - val_mae: 0.6462 - val_rmse: 0.7973 - val_smape: 1.2641

Epoch 10/16

240/240 - 4s - 17ms/step - ia: 0.4190 - loss: 0.7723 - mae: 0.6432 - rmse: 0.8739 - smape: 1.2459 - val_ia: 0.3459 - val_loss: 0.7567 - val_mae: 0.6410 - val_rmse: 0.7947 - val_smape: 1.2520

Epoch 11/16

240/240 - 4s - 17ms/step - ia: 0.4219 - loss: 0.7690 - mae: 0.6411 - rmse: 0.8724 - smape: 1.2423 - val_ia: 0.3445 - val_loss: 0.7722 - val_mae: 0.6472 - val_rmse: 0.8033 - val_smape: 1.2666

Epoch 12/16

240/240 - 4s - 18ms/step - ia: 0.4234 - loss: 0.7665 - mae: 0.6401 - rmse: 0.8710 - smape: 1.2396 - val_ia: 0.3424 - val_loss: 0.7410 - val_mae: 0.6302 - val_rmse: 0.7811 - val_smape: 1.2294

Epoch 13/16

240/240 - 4s - 17ms/step - ia: 0.4262 - loss: 0.7642 - mae: 0.6379 - rmse: 0.8699 - smape: 1.2338 - val_ia: 0.3493 - val_loss: 0.7571 - val_mae: 0.6356 - val_rmse: 0.7908 - val_smape: 1.2290

Epoch 14/16

240/240 - 4s - 17ms/step - ia: 0.4280 - loss: 0.7601 - mae: 0.6371 - rmse: 0.8662 - smape: 1.2316 - val_ia: 0.3598 - val_loss: 0.7608 - val_mae: 0.6359 - val_rmse: 0.7951 - val_smape: 1.2104

Epoch 15/16

240/240 - 4s - 16ms/step - ia: 0.4316 - loss: 0.7578 - mae: 0.6351 - rmse: 0.8657 - smape: 1.2237 - val_ia: 0.3476 - val_loss: 0.7526 - val_mae: 0.6437 - val_rmse: 0.7943 - val_smape: 1.2731

Epoch 16/16

240/240 - 4s - 17ms/step - ia: 0.4331 - loss: 0.7552 - mae: 0.6342 - rmse: 0.8639 - smape: 1.2213 - val_ia: 0.3563 - val_loss: 0.7552 - val_mae: 0.6360 - val_rmse: 0.7912 - val_smape: 1.2310

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:34 1s/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step

 26%|██▌       | 13/50 [2:01:47<2:37:28, 255.37s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 14s - 59ms/step - ia: 0.2850 - loss: 0.9522 - mae: 0.7297 - rmse: 0.9700 - smape: 1.4484 - val_ia: 0.2980 - val_loss: 0.7790 - val_mae: 0.6548 - val_rmse: 0.7954 - val_smape: 1.3298

Epoch 2/8

240/240 - 3s - 12ms/step - ia: 0.3613 - loss: 0.8789 - mae: 0.6969 - rmse: 0.9320 - smape: 1.3336 - val_ia: 0.3081 - val_loss: 0.7675 - val_mae: 0.6456 - val_rmse: 0.7890 - val_smape: 1.2819

Epoch 3/8

240/240 - 3s - 11ms/step - ia: 0.3697 - loss: 0.8645 - mae: 0.6897 - rmse: 0.9252 - smape: 1.3211 - val_ia: 0.3128 - val_loss: 0.7649 - val_mae: 0.6437 - val_rmse: 0.7884 - val_smape: 1.2707

Epoch 4/8

240/240 - 3s - 10ms/step - ia: 0.3762 - loss: 0.8550 - mae: 0.6849 - rmse: 0.9200 - smape: 1.3122 - val_ia: 0.3114 - val_loss: 0.7643 - val_mae: 0.6439 - val_rmse: 0.7881 - val_smape: 1.2784

Epoch 5/8

240/240 - 2s - 9ms/step - ia: 0.3789 - loss: 0.8461 - mae: 0.6799 - rmse: 0.9151 - smape: 1.3058 - val_ia: 0.3142 - val_loss: 0.7637 - val_mae: 0.6438 - val_rmse: 0.7887 - val_smape: 1.2773

Epoch 6/8

240/240 - 2s - 9ms/step - ia: 0.3756 - loss: 0.8446 - mae: 0.6794 - rmse: 0.9149 - smape: 1.3082 - val_ia: 0.3159 - val_loss: 0.7600 - val_mae: 0.6419 - val_rmse: 0.7870 - val_smape: 1.2672

Epoch 7/8

240/240 - 2s - 9ms/step - ia: 0.3818 - loss: 0.8408 - mae: 0.6764 - rmse: 0.9121 - smape: 1.2984 - val_ia: 0.3145 - val_loss: 0.7597 - val_mae: 0.6426 - val_rmse: 0.7872 - val_smape: 1.2758

Epoch 8/8

240/240 - 2s - 9ms/step - ia: 0.3808 - loss: 0.8342 - mae: 0.6742 - rmse: 0.9086 - smape: 1.2982 - val_ia: 0.3158 - val_loss: 0.7566 - val_mae: 0.6405 - val_rmse: 0.7853 - val_smape: 1.2695

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 43s 320ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 28%|██▊       | 14/50 [2:02:19<1:52:50, 188.06s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 10s - 20ms/step - ia: 0.3763 - loss: 0.8439 - mae: 0.6751 - rmse: 0.9083 - smape: 1.3019 - val_ia: 0.2936 - val_loss: 0.7429 - val_mae: 0.6376 - val_rmse: 0.7646 - val_smape: 1.2563

Epoch 2/16

479/479 - 4s - 9ms/step - ia: 0.4062 - loss: 0.7970 - mae: 0.6522 - rmse: 0.8837 - smape: 1.2554 - val_ia: 0.2798 - val_loss: 0.7469 - val_mae: 0.6446 - val_rmse: 0.7646 - val_smape: 1.3111

Epoch 3/16

479/479 - 4s - 9ms/step - ia: 0.4132 - loss: 0.7855 - mae: 0.6478 - rmse: 0.8760 - smape: 1.2446 - val_ia: 0.3006 - val_loss: 0.7426 - val_mae: 0.6261 - val_rmse: 0.7614 - val_smape: 1.1786

Epoch 4/16

479/479 - 3s - 7ms/step - ia: 0.4229 - loss: 0.7738 - mae: 0.6428 - rmse: 0.8699 - smape: 1.2348 - val_ia: 0.2994 - val_loss: 0.7498 - val_mae: 0.6274 - val_rmse: 0.7642 - val_smape: 1.2050

Epoch 5/16

479/479 - 3s - 7ms/step - ia: 0.4298 - loss: 0.7587 - mae: 0.6371 - rmse: 0.8620 - smape: 1.2264 - val_ia: 0.2977 - val_loss: 0.7835 - val_mae: 0.6527 - val_rmse: 0.7877 - val_smape: 1.2590

Epoch 6/16

479/479 - 3s - 6ms/step - ia: 0.4379 - loss: 0.7464 - mae: 0.6306 - rmse: 0.8547 - smape: 1.2186 - val_ia: 0.2933 - val_loss: 0.7706 - val_mae: 0.6405 - val_rmse: 0.7770 - val_smape: 1.2441

Epoch 7/16

479/479 - 3s - 6ms/step - ia: 0.4414 - loss: 0.7391 - mae: 0.6284 - rmse: 0.8500 - smape: 1.2223 - val_ia: 0.2931 - val_loss: 0.7546 - val_mae: 0.6440 - val_rmse: 0.7760 - val_smape: 1.2602

Epoch 8/16

479/479 - 4s - 8ms/step - ia: 0.4489 - loss: 0.7234 - mae: 0.6227 - rmse: 0.8409 - smape: 1.2128 - val_ia: 0.2937 - val_loss: 0.7821 - val_mae: 0.6516 - val_rmse: 0.7841 - val_smape: 1.2951

Epoch 9/16

479/479 - 4s - 8ms/step - ia: 0.4549 - loss: 0.7073 - mae: 0.6162 - rmse: 0.8324 - smape: 1.2071 - val_ia: 0.2976 - val_loss: 0.7871 - val_mae: 0.6463 - val_rmse: 0.7905 - val_smape: 1.2278

Epoch 10/16

479/479 - 5s - 11ms/step - ia: 0.4647 - loss: 0.6945 - mae: 0.6116 - rmse: 0.8251 - smape: 1.1950 - val_ia: 0.2949 - val_loss: 0.8036 - val_mae: 0.6405 - val_rmse: 0.7850 - val_smape: 1.2173

Epoch 11/16

479/479 - 4s - 8ms/step - ia: 0.4701 - loss: 0.6877 - mae: 0.6059 - rmse: 0.8204 - smape: 1.1863 - val_ia: 0.2968 - val_loss: 0.7806 - val_mae: 0.6409 - val_rmse: 0.7808 - val_smape: 1.2199

Epoch 12/16

479/479 - 3s - 7ms/step - ia: 0.4786 - loss: 0.6677 - mae: 0.6001 - rmse: 0.8088 - smape: 1.1794 - val_ia: 0.2855 - val_loss: 0.8342 - val_mae: 0.6750 - val_rmse: 0.8150 - val_smape: 1.3121

Epoch 13/16

479/479 - 3s - 7ms/step - ia: 0.4840 - loss: 0.6589 - mae: 0.5968 - rmse: 0.8031 - smape: 1.1717 - val_ia: 0.2887 - val_loss: 0.8301 - val_mae: 0.6598 - val_rmse: 0.8031 - val_smape: 1.2700

Epoch 14/16

479/479 - 3s - 7ms/step - ia: 0.4856 - loss: 0.6524 - mae: 0.5941 - rmse: 0.7988 - smape: 1.1725 - val_ia: 0.2961 - val_loss: 0.8148 - val_mae: 0.6470 - val_rmse: 0.7949 - val_smape: 1.2400

Epoch 15/16

479/479 - 4s - 8ms/step - ia: 0.4971 - loss: 0.6253 - mae: 0.5847 - rmse: 0.7828 - smape: 1.1607 - val_ia: 0.2975 - val_loss: 0.8605 - val_mae: 0.6645 - val_rmse: 0.8182 - val_smape: 1.2262

Epoch 16/16

479/479 - 4s - 8ms/step - ia: 0.4993 - loss: 0.6207 - mae: 0.5835 - rmse: 0.7807 - smape: 1.1584 - val_ia: 0.2931 - val_loss: 0.8178 - val_mae: 0.6550 - val_rmse: 0.7948 - val_smape: 1.2838

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:41 1s/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 30%|███       | 15/50 [2:03:27<1:28:33, 151.81s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 75s - 20ms/step - ia: 0.3673 - loss: 0.8403 - mae: 0.6742 - rmse: 0.8564 - smape: 1.3206 - val_ia: 0.1950 - val_loss: 0.8157 - val_mae: 0.6824 - val_rmse: 0.7210 - val_smape: 1.3842

Epoch 2/256

3830/3830 - 43s - 11ms/step - ia: 0.3846 - loss: 0.8172 - mae: 0.6642 - rmse: 0.8449 - smape: 1.2909 - val_ia: 0.2125 - val_loss: 0.7315 - val_mae: 0.6179 - val_rmse: 0.6598 - val_smape: 1.1972

Epoch 3/256

3830/3830 - 43s - 11ms/step - ia: 0.3708 - loss: 0.9233 - mae: 0.6859 - rmse: 0.8733 - smape: 1.3191 - val_ia: 0.1915 - val_loss: 0.8784 - val_mae: 0.7029 - val_rmse: 0.7431 - val_smape: 1.5070

Epoch 4/256

3830/3830 - 43s - 11ms/step - ia: 0.3158 - loss: 0.9215 - mae: 0.7150 - rmse: 0.8988 - smape: 1.4438 - val_ia: 0.1919 - val_loss: 0.8107 - val_mae: 0.6853 - val_rmse: 0.7225 - val_smape: 1.4654

Epoch 5/256

3830/3830 - 43s - 11ms/step - ia: 0.2951 - loss: 1.1331 - mae: 0.7528 - rmse: 0.9502 - smape: 1.5011 - val_ia: 0.1906 - val_loss: 0.9715 - val_mae: 0.7212 - val_rmse: 0.7608 - val_smape: 1.6260

Epoch 6/256

3830/3830 - 38s - 10ms/step - ia: 0.3059 - loss: 0.9259 - mae: 0.7192 - rmse: 0.9012 - smape: 1.4865 - val_ia: 0.2000 - val_loss: 0.7691 - val_mae: 0.6546 - val_rmse: 0.6965 - val_smape: 1.3400

Epoch 7/256

3830/3830 - 35s - 9ms/step - ia: 0.3393 - loss: 1.1911 - mae: 0.7367 - rmse: 0.9480 - smape: 1.3967 - val_ia: 0.1865 - val_loss: 0.9589 - val_mae: 0.7330 - val_rmse: 0.7739 - val_smape: 1.7313

Epoch 8/256

3830/3830 - 38s - 10ms/step - ia: 0.1982 - loss: 271.9301 - mae: 3.3016 - rmse: 5.5446 - smape: 1.6290 - val_ia: 0.1791 - val_loss: 1.3255 - val_mae: 0.7870 - val_rmse: 0.8740 - val_smape: 1.8030

Epoch 9/256

3830/3830 - 40s - 11ms/step - ia: 0.2251 - loss: 44.0407 - mae: 1.5895 - rmse: 2.4075 - smape: 1.6160 - val_ia: 0.0449 - val_loss: 224.5840 - val_mae: 6.1444 - val_rmse: 9.3698 - val_smape: 1.6071

Epoch 10/256

3830/3830 - 37s - 10ms/step - ia: 0.2043 - loss: 266.1112 - mae: 4.0208 - rmse: 6.4542 - smape: 1.5289 - val_ia: 0.1112 - val_loss: 14.6362 - val_mae: 1.6889 - val_rmse: 2.2757 - val_smape: 1.6404

Epoch 11/256

3830/3830 - 38s - 10ms/step - ia: 0.2295 - loss: 46.6015 - mae: 1.5315 - rmse: 2.1577 - smape: 1.6054 - val_ia: 0.1860 - val_loss: 0.9521 - val_mae: 0.7271 - val_rmse: 0.7686 - val_smape: 1.7309

Epoch 12/256

3830/3830 - 40s - 11ms/step - ia: 0.2452 - loss: 29.6234 - mae: 1.2504 - rmse: 1.7502 - smape: 1.6027 - val_ia: 0.0321 - val_loss: 851.2707 - val_mae: 12.8957 - val_rmse: 18.1938 - val_smape: 1.6708

Epoch 13/256

3830/3830 - 40s - 10ms/step - ia: 0.2089 - loss: 257.6411 - mae: 2.6219 - rmse: 4.1245 - smape: 1.6358 - val_ia: 0.1797 - val_loss: 1.6972 - val_mae: 0.8107 - val_rmse: 0.9249 - val_smape: 1.3153

Epoch 14/256

3830/3830 - 34s - 9ms/step - ia: 0.2469 - loss: 20.5615 - mae: 1.2077 - rmse: 1.6332 - smape: 1.5717 - val_ia: 0.1841 - val_loss: 1.0336 - val_mae: 0.7411 - val_rmse: 0.7974 - val_smape: 1.5648

Epoch 15/256

3830/3830 - 38s - 10ms/step - ia: 0.2380 - loss: 288.3571 - mae: 2.3783 - rmse: 3.5824 - smape: 1.5583 - val_ia: 0.1014 - val_loss: 13.0960 - val_mae: 2.0932 - val_rmse: 2.6343 - val_smape: 1.5286

Epoch 16/256

3830/3830 - 35s - 9ms/step - ia: 0.1423 - loss: 5118.3369 - mae: 10.0395 - rmse: 16.6953 - smape: 1.6412 - val_ia: 0.1142 - val_loss: 3.6279 - val_mae: 1.4182 - val_rmse: 1.6659 - val_smape: 1.5471

Epoch 17/256

3830/3830 - 36s - 9ms/step - ia: 0.2379 - loss: 1.5823 - mae: 0.9204 - rmse: 1.1333 - smape: 1.6529 - val_ia: 0.1836 - val_loss: 0.9563 - val_mae: 0.7454 - val_rmse: 0.7862 - val_smape: 1.7964

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:37 1s/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step

 32%|███▏      | 16/50 [2:15:09<2:59:51, 317.41s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 81s - 21ms/step - ia: 0.3642 - loss: 0.8607 - mae: 0.6828 - rmse: 0.8675 - smape: 1.3013 - val_ia: 0.2068 - val_loss: 0.7597 - val_mae: 0.6323 - val_rmse: 0.6765 - val_smape: 1.1911

Epoch 2/256

3830/3830 - 58s - 15ms/step - ia: 0.3881 - loss: 0.8094 - mae: 0.6609 - rmse: 0.8438 - smape: 1.2640 - val_ia: 0.2016 - val_loss: 0.7801 - val_mae: 0.6475 - val_rmse: 0.6913 - val_smape: 1.2510

Epoch 3/256

3830/3830 - 60s - 16ms/step - ia: 0.4000 - loss: 0.7912 - mae: 0.6511 - rmse: 0.8327 - smape: 1.2549 - val_ia: 0.2082 - val_loss: 0.7572 - val_mae: 0.6314 - val_rmse: 0.6737 - val_smape: 1.2071

Epoch 4/256

3830/3830 - 63s - 16ms/step - ia: 0.4081 - loss: 0.7791 - mae: 0.6453 - rmse: 0.8258 - smape: 1.2409 - val_ia: 0.2018 - val_loss: 0.7616 - val_mae: 0.6448 - val_rmse: 0.6895 - val_smape: 1.2219

Epoch 5/256

3830/3830 - 62s - 16ms/step - ia: 0.4134 - loss: 0.7658 - mae: 0.6394 - rmse: 0.8179 - smape: 1.2369 - val_ia: 0.2006 - val_loss: 0.7673 - val_mae: 0.6459 - val_rmse: 0.6875 - val_smape: 1.3046

Epoch 6/256

3830/3830 - 62s - 16ms/step - ia: 0.4249 - loss: 0.7469 - mae: 0.6297 - rmse: 0.8074 - smape: 1.2187 - val_ia: 0.2010 - val_loss: 0.7954 - val_mae: 0.6576 - val_rmse: 0.7004 - val_smape: 1.2712

Epoch 7/256

3830/3830 - 56s - 15ms/step - ia: 0.4290 - loss: 0.7364 - mae: 0.6258 - rmse: 0.8015 - smape: 1.2092 - val_ia: 0.2035 - val_loss: 0.7737 - val_mae: 0.6377 - val_rmse: 0.6809 - val_smape: 1.2485

Epoch 8/256

3830/3830 - 63s - 17ms/step - ia: 0.4368 - loss: 0.7183 - mae: 0.6190 - rmse: 0.7924 - smape: 1.2018 - val_ia: 0.2002 - val_loss: 0.7833 - val_mae: 0.6514 - val_rmse: 0.6947 - val_smape: 1.2806

Epoch 9/256

3830/3830 - 59s - 15ms/step - ia: 0.4433 - loss: 0.7018 - mae: 0.6106 - rmse: 0.7823 - smape: 1.1903 - val_ia: 0.2031 - val_loss: 0.8149 - val_mae: 0.6519 - val_rmse: 0.6985 - val_smape: 1.2629

Epoch 10/256

3830/3830 - 65s - 17ms/step - ia: 0.4512 - loss: 0.6879 - mae: 0.6048 - rmse: 0.7766 - smape: 1.1822 - val_ia: 0.2022 - val_loss: 0.8123 - val_mae: 0.6512 - val_rmse: 0.6972 - val_smape: 1.2528

Epoch 11/256

3830/3830 - 66s - 17ms/step - ia: 0.4557 - loss: 0.6674 - mae: 0.5986 - rmse: 0.7657 - smape: 1.1744 - val_ia: 0.2012 - val_loss: 0.8437 - val_mae: 0.6671 - val_rmse: 0.7145 - val_smape: 1.2697

Epoch 12/256

3830/3830 - 65s - 17ms/step - ia: 0.4658 - loss: 0.6505 - mae: 0.5893 - rmse: 0.7553 - smape: 1.1559 - val_ia: 0.1968 - val_loss: 0.9353 - val_mae: 0.6961 - val_rmse: 0.7440 - val_smape: 1.3299

Epoch 13/256

3830/3830 - 61s - 16ms/step - ia: 0.4688 - loss: 0.6315 - mae: 0.5831 - rmse: 0.7453 - smape: 1.1558 - val_ia: 0.1958 - val_loss: 0.9754 - val_mae: 0.7066 - val_rmse: 0.7586 - val_smape: 1.3117

Epoch 14/256

3830/3830 - 58s - 15ms/step - ia: 0.4775 - loss: 0.6139 - mae: 0.5744 - rmse: 0.7347 - smape: 1.1399 - val_ia: 0.2021 - val_loss: 0.8697 - val_mae: 0.6688 - val_rmse: 0.7197 - val_smape: 1.2757

Epoch 15/256

3830/3830 - 64s - 17ms/step - ia: 0.4852 - loss: 0.5909 - mae: 0.5657 - rmse: 0.7219 - smape: 1.1270 - val_ia: 0.2030 - val_loss: 0.8863 - val_mae: 0.6619 - val_rmse: 0.7091 - val_smape: 1.2533

Epoch 16/256

3830/3830 - 60s - 16ms/step - ia: 0.4938 - loss: 0.5717 - mae: 0.5576 - rmse: 0.7099 - smape: 1.1184 - val_ia: 0.2058 - val_loss: 0.9184 - val_mae: 0.6641 - val_rmse: 0.7148 - val_smape: 1.2415

Epoch 17/256

3830/3830 - 62s - 16ms/step - ia: 0.5012 - loss: 0.5540 - mae: 0.5494 - rmse: 0.6985 - smape: 1.1102 - val_ia: 0.2014 - val_loss: 0.9240 - val_mae: 0.6719 - val_rmse: 0.7238 - val_smape: 1.2508

Epoch 18/256

3830/3830 - 59s - 15ms/step - ia: 0.5053 - loss: 0.5368 - mae: 0.5423 - rmse: 0.6887 - smape: 1.1007 - val_ia: 0.2028 - val_loss: 0.9396 - val_mae: 0.6798 - val_rmse: 0.7322 - val_smape: 1.2318

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:11 2s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 34%|███▍      | 17/50 [2:33:58<5:08:52, 561.59s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 22s - 90ms/step - ia: 0.2213 - loss: 1.3009 - mae: 0.8534 - rmse: 1.1333 - smape: 1.5359 - val_ia: 0.2591 - val_loss: 1.0728 - val_mae: 0.7636 - val_rmse: 0.9149 - val_smape: 1.5810

Epoch 2/16

240/240 - 3s - 14ms/step - ia: 0.2210 - loss: 1.2819 - mae: 0.8453 - rmse: 1.1254 - smape: 1.5371 - val_ia: 0.2594 - val_loss: 1.0506 - val_mae: 0.7574 - val_rmse: 0.9066 - val_smape: 1.5989

Epoch 3/16

240/240 - 3s - 14ms/step - ia: 0.2246 - loss: 1.2422 - mae: 0.8343 - rmse: 1.1080 - smape: 1.5310 - val_ia: 0.2602 - val_loss: 1.0305 - val_mae: 0.7516 - val_rmse: 0.8990 - val_smape: 1.6149

Epoch 4/16

240/240 - 5s - 21ms/step - ia: 0.2308 - loss: 1.2148 - mae: 0.8231 - rmse: 1.0956 - smape: 1.5218 - val_ia: 0.2609 - val_loss: 1.0111 - val_mae: 0.7458 - val_rmse: 0.8916 - val_smape: 1.6267

Epoch 5/16

240/240 - 3s - 14ms/step - ia: 0.2306 - loss: 1.1985 - mae: 0.8181 - rmse: 1.0890 - smape: 1.5211 - val_ia: 0.2617 - val_loss: 0.9929 - val_mae: 0.7402 - val_rmse: 0.8845 - val_smape: 1.6361

Epoch 6/16

240/240 - 3s - 14ms/step - ia: 0.2330 - loss: 1.1725 - mae: 0.8089 - rmse: 1.0766 - smape: 1.5171 - val_ia: 0.2629 - val_loss: 0.9762 - val_mae: 0.7350 - val_rmse: 0.8781 - val_smape: 1.6434

Epoch 7/16

240/240 - 3s - 14ms/step - ia: 0.2361 - loss: 1.1522 - mae: 0.8030 - rmse: 1.0690 - smape: 1.5125 - val_ia: 0.2639 - val_loss: 0.9599 - val_mae: 0.7297 - val_rmse: 0.8716 - val_smape: 1.6443

Epoch 8/16

240/240 - 3s - 13ms/step - ia: 0.2404 - loss: 1.1363 - mae: 0.7950 - rmse: 1.0597 - smape: 1.5042 - val_ia: 0.2651 - val_loss: 0.9449 - val_mae: 0.7247 - val_rmse: 0.8656 - val_smape: 1.6430

Epoch 9/16

240/240 - 3s - 12ms/step - ia: 0.2435 - loss: 1.1145 - mae: 0.7906 - rmse: 1.0504 - smape: 1.5022 - val_ia: 0.2663 - val_loss: 0.9308 - val_mae: 0.7199 - val_rmse: 0.8599 - val_smape: 1.6378

Epoch 10/16

240/240 - 3s - 12ms/step - ia: 0.2475 - loss: 1.1121 - mae: 0.7848 - rmse: 1.0477 - smape: 1.4941 - val_ia: 0.2675 - val_loss: 0.9176 - val_mae: 0.7153 - val_rmse: 0.8545 - val_smape: 1.6283

Epoch 11/16

240/240 - 3s - 12ms/step - ia: 0.2535 - loss: 1.0852 - mae: 0.7777 - rmse: 1.0368 - smape: 1.4851 - val_ia: 0.2687 - val_loss: 0.9054 - val_mae: 0.7111 - val_rmse: 0.8496 - val_smape: 1.6124

Epoch 12/16

240/240 - 3s - 12ms/step - ia: 0.2563 - loss: 1.0815 - mae: 0.7764 - rmse: 1.0341 - smape: 1.4857 - val_ia: 0.2699 - val_loss: 0.8933 - val_mae: 0.7068 - val_rmse: 0.8447 - val_smape: 1.5924

Epoch 13/16

240/240 - 3s - 12ms/step - ia: 0.2632 - loss: 1.0631 - mae: 0.7705 - rmse: 1.0253 - smape: 1.4720 - val_ia: 0.2711 - val_loss: 0.8826 - val_mae: 0.7029 - val_rmse: 0.8403 - val_smape: 1.5736

Epoch 14/16

240/240 - 3s - 12ms/step - ia: 0.2657 - loss: 1.0486 - mae: 0.7673 - rmse: 1.0185 - smape: 1.4723 - val_ia: 0.2726 - val_loss: 0.8728 - val_mae: 0.6991 - val_rmse: 0.8363 - val_smape: 1.5549

Epoch 15/16

240/240 - 3s - 12ms/step - ia: 0.2730 - loss: 1.0370 - mae: 0.7621 - rmse: 1.0119 - smape: 1.4637 - val_ia: 0.2745 - val_loss: 0.8633 - val_mae: 0.6954 - val_rmse: 0.8323 - val_smape: 1.5358

Epoch 16/16

240/240 - 3s - 12ms/step - ia: 0.2770 - loss: 1.0273 - mae: 0.7584 - rmse: 1.0077 - smape: 1.4590 - val_ia: 0.2767 - val_loss: 0.8541 - val_mae: 0.6918 - val_rmse: 0.8285 - val_smape: 1.5167

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:30 669ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/16

 36%|███▌      | 18/50 [2:35:11<3:41:05, 414.53s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

479/479 - 11s - 23ms/step - ia: 0.3723 - loss: 0.8644 - mae: 0.6875 - rmse: 0.9208 - smape: 1.3054 - val_ia: 0.2771 - val_loss: 0.7514 - val_mae: 0.6403 - val_rmse: 0.7626 - val_smape: 1.2625

Epoch 2/16

479/479 - 5s - 11ms/step - ia: 0.3921 - loss: 0.8173 - mae: 0.6646 - rmse: 0.8942 - smape: 1.2782 - val_ia: 0.2763 - val_loss: 0.7524 - val_mae: 0.6436 - val_rmse: 0.7653 - val_smape: 1.2839

Epoch 3/16

479/479 - 5s - 10ms/step - ia: 0.4020 - loss: 0.8011 - mae: 0.6562 - rmse: 0.8857 - smape: 1.2592 - val_ia: 0.2870 - val_loss: 0.7497 - val_mae: 0.6431 - val_rmse: 0.7688 - val_smape: 1.2610

Epoch 4/16

479/479 - 5s - 10ms/step - ia: 0.4095 - loss: 0.7938 - mae: 0.6526 - rmse: 0.8810 - smape: 1.2486 - val_ia: 0.2893 - val_loss: 0.7524 - val_mae: 0.6315 - val_rmse: 0.7623 - val_smape: 1.2186

Epoch 5/16

479/479 - 5s - 10ms/step - ia: 0.4181 - loss: 0.7787 - mae: 0.6461 - rmse: 0.8740 - smape: 1.2392 - val_ia: 0.2932 - val_loss: 0.7268 - val_mae: 0.6211 - val_rmse: 0.7491 - val_smape: 1.1977

Epoch 6/16

479/479 - 5s - 10ms/step - ia: 0.4263 - loss: 0.7692 - mae: 0.6404 - rmse: 0.8671 - smape: 1.2261 - val_ia: 0.2987 - val_loss: 0.8024 - val_mae: 0.6436 - val_rmse: 0.7848 - val_smape: 1.1880

Epoch 7/16

479/479 - 6s - 12ms/step - ia: 0.4319 - loss: 0.7618 - mae: 0.6368 - rmse: 0.8626 - smape: 1.2216 - val_ia: 0.2927 - val_loss: 0.7631 - val_mae: 0.6464 - val_rmse: 0.7748 - val_smape: 1.2762

Epoch 8/16

479/479 - 6s - 12ms/step - ia: 0.4379 - loss: 0.7499 - mae: 0.6312 - rmse: 0.8562 - smape: 1.2128 - val_ia: 0.3045 - val_loss: 0.7820 - val_mae: 0.6444 - val_rmse: 0.7805 - val_smape: 1.2186

Epoch 9/16

479/479 - 6s - 12ms/step - ia: 0.4450 - loss: 0.7383 - mae: 0.6262 - rmse: 0.8508 - smape: 1.2022 - val_ia: 0.3092 - val_loss: 0.7928 - val_mae: 0.6373 - val_rmse: 0.7786 - val_smape: 1.1797

Epoch 10/16

479/479 - 6s - 12ms/step - ia: 0.4512 - loss: 0.7327 - mae: 0.6235 - rmse: 0.8464 - smape: 1.1951 - val_ia: 0.3097 - val_loss: 0.8151 - val_mae: 0.6618 - val_rmse: 0.8040 - val_smape: 1.2398

Epoch 11/16

479/479 - 6s - 12ms/step - ia: 0.4597 - loss: 0.7173 - mae: 0.6171 - rmse: 0.8387 - smape: 1.1826 - val_ia: 0.3032 - val_loss: 0.7743 - val_mae: 0.6412 - val_rmse: 0.7750 - val_smape: 1.2451

Epoch 12/16

479/479 - 6s - 12ms/step - ia: 0.4675 - loss: 0.6995 - mae: 0.6098 - rmse: 0.8287 - smape: 1.1758 - val_ia: 0.3077 - val_loss: 0.7838 - val_mae: 0.6440 - val_rmse: 0.7807 - val_smape: 1.2343

Epoch 13/16

479/479 - 6s - 12ms/step - ia: 0.4764 - loss: 0.6802 - mae: 0.6031 - rmse: 0.8164 - smape: 1.1650 - val_ia: 0.3009 - val_loss: 0.7853 - val_mae: 0.6351 - val_rmse: 0.7681 - val_smape: 1.2163

Epoch 14/16

479/479 - 6s - 12ms/step - ia: 0.4862 - loss: 0.6544 - mae: 0.5945 - rmse: 0.8007 - smape: 1.1596 - val_ia: 0.3054 - val_loss: 0.8410 - val_mae: 0.6586 - val_rmse: 0.7991 - val_smape: 1.2419

Epoch 15/16

479/479 - 6s - 12ms/step - ia: 0.4982 - loss: 0.6293 - mae: 0.5840 - rmse: 0.7856 - smape: 1.1474 - val_ia: 0.3113 - val_loss: 0.8798 - val_mae: 0.6610 - val_rmse: 0.8116 - val_smape: 1.2130

Epoch 16/16

479/479 - 6s - 12ms/step - ia: 0.5077 - loss: 0.6013 - mae: 0.5734 - rmse: 0.7687 - smape: 1.1381 - val_ia: 0.3058 - val_loss: 0.8473 - val_mae: 0.6564 - val_rmse: 0.7956 - val_smape: 1.2659

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:35 709ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 38%|███▊      | 19/50 [2:36:47<2:44:47, 318.95s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 83s - 22ms/step - ia: 0.2843 - loss: 0.9625 - mae: 0.7306 - rmse: 0.9158 - smape: 1.5052 - val_ia: 0.2012 - val_loss: 0.8147 - val_mae: 0.6642 - val_rmse: 0.7045 - val_smape: 1.2801

Epoch 2/32

3830/3830 - 66s - 17ms/step - ia: 0.3625 - loss: 0.8566 - mae: 0.6820 - rmse: 0.8669 - smape: 1.2838 - val_ia: 0.2037 - val_loss: 0.7851 - val_mae: 0.6488 - val_rmse: 0.6897 - val_smape: 1.2429

Epoch 3/32

3830/3830 - 60s - 16ms/step - ia: 0.3655 - loss: 0.8492 - mae: 0.6781 - rmse: 0.8640 - smape: 1.2815 - val_ia: 0.2045 - val_loss: 0.7772 - val_mae: 0.6469 - val_rmse: 0.6872 - val_smape: 1.2495

Epoch 4/32

3830/3830 - 65s - 17ms/step - ia: 0.3674 - loss: 0.8384 - mae: 0.6747 - rmse: 0.8581 - smape: 1.2805 - val_ia: 0.2043 - val_loss: 0.7695 - val_mae: 0.6416 - val_rmse: 0.6830 - val_smape: 1.2139

Epoch 5/32

3830/3830 - 65s - 17ms/step - ia: 0.3756 - loss: 0.8288 - mae: 0.6707 - rmse: 0.8536 - smape: 1.2771 - val_ia: 0.2043 - val_loss: 0.7711 - val_mae: 0.6383 - val_rmse: 0.6785 - val_smape: 1.2343

Epoch 6/32

3830/3830 - 65s - 17ms/step - ia: 0.3783 - loss: 0.8204 - mae: 0.6675 - rmse: 0.8483 - smape: 1.2778 - val_ia: 0.2036 - val_loss: 0.7667 - val_mae: 0.6434 - val_rmse: 0.6846 - val_smape: 1.2343

Epoch 7/32

3830/3830 - 65s - 17ms/step - ia: 0.3838 - loss: 0.8161 - mae: 0.6637 - rmse: 0.8448 - smape: 1.2723 - val_ia: 0.2027 - val_loss: 0.7725 - val_mae: 0.6492 - val_rmse: 0.6904 - val_smape: 1.2493

Epoch 8/32

3830/3830 - 64s - 17ms/step - ia: 0.3860 - loss: 0.8102 - mae: 0.6619 - rmse: 0.8434 - smape: 1.2663 - val_ia: 0.2023 - val_loss: 0.7778 - val_mae: 0.6536 - val_rmse: 0.6946 - val_smape: 1.2630

Epoch 9/32

3830/3830 - 66s - 17ms/step - ia: 0.3890 - loss: 0.8055 - mae: 0.6583 - rmse: 0.8406 - smape: 1.2653 - val_ia: 0.2058 - val_loss: 0.7693 - val_mae: 0.6405 - val_rmse: 0.6819 - val_smape: 1.2481

Epoch 10/32

3830/3830 - 61s - 16ms/step - ia: 0.3917 - loss: 0.8032 - mae: 0.6577 - rmse: 0.8385 - smape: 1.2613 - val_ia: 0.2006 - val_loss: 0.7828 - val_mae: 0.6547 - val_rmse: 0.6959 - val_smape: 1.2832

Epoch 11/32

3830/3830 - 68s - 18ms/step - ia: 0.3912 - loss: 0.8017 - mae: 0.6566 - rmse: 0.8379 - smape: 1.2639 - val_ia: 0.2029 - val_loss: 0.7756 - val_mae: 0.6466 - val_rmse: 0.6880 - val_smape: 1.2587

Epoch 12/32

3830/3830 - 66s - 17ms/step - ia: 0.3943 - loss: 0.7993 - mae: 0.6558 - rmse: 0.8382 - smape: 1.2625 - val_ia: 0.1977 - val_loss: 0.8194 - val_mae: 0.6726 - val_rmse: 0.7150 - val_smape: 1.2713

Epoch 13/32

3830/3830 - 66s - 17ms/step - ia: 0.3973 - loss: 0.7950 - mae: 0.6526 - rmse: 0.8345 - smape: 1.2583 - val_ia: 0.2019 - val_loss: 0.7784 - val_mae: 0.6486 - val_rmse: 0.6906 - val_smape: 1.2600

Epoch 14/32

3830/3830 - 67s - 17ms/step - ia: 0.3995 - loss: 0.7944 - mae: 0.6525 - rmse: 0.8353 - smape: 1.2539 - val_ia: 0.2014 - val_loss: 0.7771 - val_mae: 0.6483 - val_rmse: 0.6900 - val_smape: 1.2627

Epoch 15/32

3830/3830 - 68s - 18ms/step - ia: 0.3952 - loss: 0.7953 - mae: 0.6536 - rmse: 0.8342 - smape: 1.2616 - val_ia: 0.2039 - val_loss: 0.7668 - val_mae: 0.6400 - val_rmse: 0.6818 - val_smape: 1.2472

Epoch 16/32

3830/3830 - 67s - 18ms/step - ia: 0.3983 - loss: 0.7920 - mae: 0.6514 - rmse: 0.8332 - smape: 1.2573 - val_ia: 0.2015 - val_loss: 0.7790 - val_mae: 0.6489 - val_rmse: 0.6910 - val_smape: 1.2680

Epoch 17/32

3830/3830 - 64s - 17ms/step - ia: 0.4018 - loss: 0.7874 - mae: 0.6496 - rmse: 0.8315 - smape: 1.2557 - val_ia: 0.1994 - val_loss: 0.7889 - val_mae: 0.6559 - val_rmse: 0.6988 - val_smape: 1.2565

Epoch 18/32

3830/3830 - 66s - 17ms/step - ia: 0.4007 - loss: 0.7857 - mae: 0.6489 - rmse: 0.8293 - smape: 1.2513 - val_ia: 0.1996 - val_loss: 0.8013 - val_mae: 0.6601 - val_rmse: 0.7030 - val_smape: 1.2431

Epoch 19/32

3830/3830 - 68s - 18ms/step - ia: 0.4030 - loss: 0.7859 - mae: 0.6492 - rmse: 0.8290 - smape: 1.2524 - val_ia: 0.2014 - val_loss: 0.7742 - val_mae: 0.6475 - val_rmse: 0.6896 - val_smape: 1.2480

Epoch 20/32

3830/3830 - 67s - 18ms/step - ia: 0.4027 - loss: 0.7868 - mae: 0.6489 - rmse: 0.8311 - smape: 1.2467 - val_ia: 0.1987 - val_loss: 0.7824 - val_mae: 0.6566 - val_rmse: 0.6986 - val_smape: 1.2780

Epoch 21/32

3830/3830 - 65s - 17ms/step - ia: 0.4043 - loss: 0.7789 - mae: 0.6463 - rmse: 0.8248 - smape: 1.2469 - val_ia: 0.2005 - val_loss: 0.7952 - val_mae: 0.6539 - val_rmse: 0.6970 - val_smape: 1.2454

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:27 2s/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step

 40%|████      | 20/50 [3:00:06<5:21:40, 643.34s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1915/1915 - 60s - 31ms/step - ia: 0.2886 - loss: 0.9157 - mae: 0.7099 - rmse: 0.9181 - smape: 1.4483 - val_ia: 0.2402 - val_loss: 0.7967 - val_mae: 0.6582 - val_rmse: 0.7249 - val_smape: 1.3002

Epoch 2/64

1915/1915 - 29s - 15ms/step - ia: 0.3638 - loss: 0.8366 - mae: 0.6763 - rmse: 0.8832 - smape: 1.3114 - val_ia: 0.2414 - val_loss: 0.7863 - val_mae: 0.6531 - val_rmse: 0.7203 - val_smape: 1.2898

Epoch 3/64

1915/1915 - 24s - 13ms/step - ia: 0.3718 - loss: 0.8276 - mae: 0.6713 - rmse: 0.8773 - smape: 1.3020 - val_ia: 0.2420 - val_loss: 0.7799 - val_mae: 0.6519 - val_rmse: 0.7200 - val_smape: 1.2811

Epoch 4/64

1915/1915 - 27s - 14ms/step - ia: 0.3781 - loss: 0.8208 - mae: 0.6676 - rmse: 0.8748 - smape: 1.2896 - val_ia: 0.2450 - val_loss: 0.7700 - val_mae: 0.6497 - val_rmse: 0.7172 - val_smape: 1.2826

Epoch 5/64

1915/1915 - 29s - 15ms/step - ia: 0.3800 - loss: 0.8153 - mae: 0.6660 - rmse: 0.8728 - smape: 1.2880 - val_ia: 0.2463 - val_loss: 0.7624 - val_mae: 0.6432 - val_rmse: 0.7114 - val_smape: 1.2632

Epoch 6/64

1915/1915 - 25s - 13ms/step - ia: 0.3837 - loss: 0.8102 - mae: 0.6624 - rmse: 0.8689 - smape: 1.2801 - val_ia: 0.2468 - val_loss: 0.7587 - val_mae: 0.6435 - val_rmse: 0.7124 - val_smape: 1.2614

Epoch 7/64

1915/1915 - 28s - 15ms/step - ia: 0.3864 - loss: 0.8055 - mae: 0.6602 - rmse: 0.8649 - smape: 1.2764 - val_ia: 0.2472 - val_loss: 0.7576 - val_mae: 0.6428 - val_rmse: 0.7128 - val_smape: 1.2532

Epoch 8/64

1915/1915 - 42s - 22ms/step - ia: 0.3922 - loss: 0.8016 - mae: 0.6581 - rmse: 0.8637 - smape: 1.2692 - val_ia: 0.2472 - val_loss: 0.7542 - val_mae: 0.6430 - val_rmse: 0.7125 - val_smape: 1.2621

Epoch 9/64

1915/1915 - 30s - 16ms/step - ia: 0.3943 - loss: 0.7982 - mae: 0.6563 - rmse: 0.8613 - smape: 1.2654 - val_ia: 0.2478 - val_loss: 0.7511 - val_mae: 0.6411 - val_rmse: 0.7104 - val_smape: 1.2640

Epoch 10/64

1915/1915 - 29s - 15ms/step - ia: 0.3967 - loss: 0.7951 - mae: 0.6541 - rmse: 0.8601 - smape: 1.2619 - val_ia: 0.2479 - val_loss: 0.7518 - val_mae: 0.6425 - val_rmse: 0.7124 - val_smape: 1.2631

Epoch 11/64

1915/1915 - 25s - 13ms/step - ia: 0.4003 - loss: 0.7925 - mae: 0.6526 - rmse: 0.8579 - smape: 1.2582 - val_ia: 0.2467 - val_loss: 0.7543 - val_mae: 0.6456 - val_rmse: 0.7151 - val_smape: 1.2755

Epoch 12/64

1915/1915 - 27s - 14ms/step - ia: 0.4007 - loss: 0.7901 - mae: 0.6515 - rmse: 0.8575 - smape: 1.2570 - val_ia: 0.2483 - val_loss: 0.7499 - val_mae: 0.6420 - val_rmse: 0.7117 - val_smape: 1.2655

Epoch 13/64

1915/1915 - 28s - 15ms/step - ia: 0.4051 - loss: 0.7880 - mae: 0.6499 - rmse: 0.8556 - smape: 1.2512 - val_ia: 0.2492 - val_loss: 0.7474 - val_mae: 0.6412 - val_rmse: 0.7113 - val_smape: 1.2596

Epoch 14/64

1915/1915 - 29s - 15ms/step - ia: 0.4062 - loss: 0.7860 - mae: 0.6488 - rmse: 0.8536 - smape: 1.2490 - val_ia: 0.2496 - val_loss: 0.7490 - val_mae: 0.6409 - val_rmse: 0.7111 - val_smape: 1.2571

Epoch 15/64

1915/1915 - 28s - 15ms/step - ia: 0.4077 - loss: 0.7837 - mae: 0.6478 - rmse: 0.8532 - smape: 1.2466 - val_ia: 0.2498 - val_loss: 0.7521 - val_mae: 0.6416 - val_rmse: 0.7124 - val_smape: 1.2547

Epoch 16/64

1915/1915 - 29s - 15ms/step - ia: 0.4103 - loss: 0.7824 - mae: 0.6463 - rmse: 0.8530 - smape: 1.2427 - val_ia: 0.2493 - val_loss: 0.7491 - val_mae: 0.6419 - val_rmse: 0.7119 - val_smape: 1.2634

Epoch 17/64

1915/1915 - 29s - 15ms/step - ia: 0.4110 - loss: 0.7805 - mae: 0.6457 - rmse: 0.8504 - smape: 1.2426 - val_ia: 0.2525 - val_loss: 0.7471 - val_mae: 0.6372 - val_rmse: 0.7086 - val_smape: 1.2326

Epoch 18/64

1915/1915 - 29s - 15ms/step - ia: 0.4144 - loss: 0.7788 - mae: 0.6441 - rmse: 0.8520 - smape: 1.2355 - val_ia: 0.2483 - val_loss: 0.7552 - val_mae: 0.6459 - val_rmse: 0.7160 - val_smape: 1.2686

Epoch 19/64

1915/1915 - 29s - 15ms/step - ia: 0.4135 - loss: 0.7773 - mae: 0.6444 - rmse: 0.8487 - smape: 1.2376 - val_ia: 0.2518 - val_loss: 0.7418 - val_mae: 0.6356 - val_rmse: 0.7053 - val_smape: 1.2510

Epoch 20/64

1915/1915 - 37s - 19ms/step - ia: 0.4160 - loss: 0.7760 - mae: 0.6424 - rmse: 0.8484 - smape: 1.2329 - val_ia: 0.2502 - val_loss: 0.7495 - val_mae: 0.6419 - val_rmse: 0.7122 - val_smape: 1.2580

Epoch 21/64

1915/1915 - 27s - 14ms/step - ia: 0.4163 - loss: 0.7744 - mae: 0.6422 - rmse: 0.8476 - smape: 1.2316 - val_ia: 0.2508 - val_loss: 0.7469 - val_mae: 0.6393 - val_rmse: 0.7090 - val_smape: 1.2571

Epoch 22/64

1915/1915 - 29s - 15ms/step - ia: 0.4187 - loss: 0.7734 - mae: 0.6414 - rmse: 0.8465 - smape: 1.2317 - val_ia: 0.2536 - val_loss: 0.7497 - val_mae: 0.6367 - val_rmse: 0.7079 - val_smape: 1.2311

Epoch 23/64

1915/1915 - 25s - 13ms/step - ia: 0.4187 - loss: 0.7721 - mae: 0.6407 - rmse: 0.8474 - smape: 1.2289 - val_ia: 0.2520 - val_loss: 0.7494 - val_mae: 0.6396 - val_rmse: 0.7103 - val_smape: 1.2456

Epoch 24/64

1915/1915 - 45s - 23ms/step - ia: 0.4204 - loss: 0.7709 - mae: 0.6403 - rmse: 0.8467 - smape: 1.2269 - val_ia: 0.2536 - val_loss: 0.7461 - val_mae: 0.6358 - val_rmse: 0.7064 - val_smape: 1.2365

Epoch 25/64

1915/1915 - 30s - 16ms/step - ia: 0.4202 - loss: 0.7697 - mae: 0.6394 - rmse: 0.8442 - smape: 1.2260 - val_ia: 0.2524 - val_loss: 0.7541 - val_mae: 0.6398 - val_rmse: 0.7110 - val_smape: 1.2384

Epoch 26/64

1915/1915 - 31s - 16ms/step - ia: 0.4231 - loss: 0.7687 - mae: 0.6387 - rmse: 0.8438 - smape: 1.2233 - val_ia: 0.2526 - val_loss: 0.7507 - val_mae: 0.6394 - val_rmse: 0.7101 - val_smape: 1.2412

Epoch 27/64

1915/1915 - 28s - 15ms/step - ia: 0.4207 - loss: 0.7673 - mae: 0.6388 - rmse: 0.8425 - smape: 1.2256 - val_ia: 0.2532 - val_loss: 0.7539 - val_mae: 0.6386 - val_rmse: 0.7100 - val_smape: 1.2322

Epoch 28/64

1915/1915 - 29s - 15ms/step - ia: 0.4239 - loss: 0.7663 - mae: 0.6380 - rmse: 0.8432 - smape: 1.2233 - val_ia: 0.2557 - val_loss: 0.7580 - val_mae: 0.6370 - val_rmse: 0.7093 - val_smape: 1.2158

Epoch 29/64

1915/1915 - 27s - 14ms/step - ia: 0.4244 - loss: 0.7661 - mae: 0.6376 - rmse: 0.8430 - smape: 1.2215 - val_ia: 0.2521 - val_loss: 0.7553 - val_mae: 0.6411 - val_rmse: 0.7121 - val_smape: 1.2411

Epoch 30/64

1915/1915 - 27s - 14ms/step - ia: 0.4241 - loss: 0.7647 - mae: 0.6373 - rmse: 0.8419 - smape: 1.2221 - val_ia: 0.2538 - val_loss: 0.7502 - val_mae: 0.6374 - val_rmse: 0.7084 - val_smape: 1.2338

Epoch 31/64

1915/1915 - 28s - 15ms/step - ia: 0.4250 - loss: 0.7642 - mae: 0.6370 - rmse: 0.8417 - smape: 1.2214 - val_ia: 0.2532 - val_loss: 0.7538 - val_mae: 0.6395 - val_rmse: 0.7108 - val_smape: 1.2352

Epoch 32/64

1915/1915 - 26s - 14ms/step - ia: 0.4243 - loss: 0.7634 - mae: 0.6364 - rmse: 0.8413 - smape: 1.2209 - val_ia: 0.2531 - val_loss: 0.7548 - val_mae: 0.6393 - val_rmse: 0.7105 - val_smape: 1.2325

Epoch 33/64

1915/1915 - 27s - 14ms/step - ia: 0.4260 - loss: 0.7625 - mae: 0.6360 - rmse: 0.8399 - smape: 1.2202 - val_ia: 0.2535 - val_loss: 0.7646 - val_mae: 0.6429 - val_rmse: 0.7149 - val_smape: 1.2285

Epoch 34/64

1915/1915 - 28s - 15ms/step - ia: 0.4257 - loss: 0.7619 - mae: 0.6359 - rmse: 0.8419 - smape: 1.2185 - val_ia: 0.2543 - val_loss: 0.7565 - val_mae: 0.6390 - val_rmse: 0.7107 - val_smape: 1.2272

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:01 2s/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step

 42%|████▏     | 21/50 [3:17:12<6:06:24, 758.10s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 60s - 31ms/step - ia: 0.2534 - loss: 1.2072 - mae: 0.8457 - rmse: 1.0639 - smape: 1.5127 - val_ia: 0.2207 - val_loss: 0.9667 - val_mae: 0.7316 - val_rmse: 0.7916 - val_smape: 1.8708

Epoch 2/8

1915/1915 - 41s - 22ms/step - ia: 0.2493 - loss: 1.1205 - mae: 0.7969 - rmse: 1.0205 - smape: 1.5206 - val_ia: 0.2207 - val_loss: 0.9664 - val_mae: 0.7314 - val_rmse: 0.7913 - val_smape: 1.8675

Epoch 3/8

1915/1915 - 41s - 22ms/step - ia: 0.2367 - loss: 1.0839 - mae: 0.7826 - rmse: 1.0048 - smape: 1.5461 - val_ia: 0.2199 - val_loss: 0.9674 - val_mae: 0.7363 - val_rmse: 0.7959 - val_smape: 1.9838

Epoch 4/8

1915/1915 - 42s - 22ms/step - ia: 0.2300 - loss: 1.0632 - mae: 0.7745 - rmse: 0.9926 - smape: 1.5654 - val_ia: 0.2204 - val_loss: 0.9663 - val_mae: 0.7337 - val_rmse: 0.7935 - val_smape: 1.9214

Epoch 5/8

1915/1915 - 40s - 21ms/step - ia: 0.2193 - loss: 1.0521 - mae: 0.7682 - rmse: 0.9860 - smape: 1.5901 - val_ia: 0.2196 - val_loss: 0.9674 - val_mae: 0.7387 - val_rmse: 0.7982 - val_smape: 1.9558

Epoch 6/8

1915/1915 - 38s - 20ms/step - ia: 0.2147 - loss: 1.0378 - mae: 0.7646 - rmse: 0.9793 - smape: 1.6091 - val_ia: 0.2212 - val_loss: 0.9636 - val_mae: 0.7284 - val_rmse: 0.7885 - val_smape: 1.8236

Epoch 7/8

1915/1915 - 41s - 21ms/step - ia: 0.2091 - loss: 1.0304 - mae: 0.7616 - rmse: 0.9759 - smape: 1.6267 - val_ia: 0.2205 - val_loss: 0.9629 - val_mae: 0.7324 - val_rmse: 0.7921 - val_smape: 1.9128

Epoch 8/8

1915/1915 - 41s - 21ms/step - ia: 0.2065 - loss: 1.0191 - mae: 0.7567 - rmse: 0.9695 - smape: 1.6375 - val_ia: 0.2211 - val_loss: 0.9586 - val_mae: 0.7282 - val_rmse: 0.7881 - val_smape: 1.8485

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:09 1s/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 44%|████▍     | 22/50 [3:22:59<4:56:15, 634.83s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 56s - 29ms/step - ia: 0.3865 - loss: 0.8213 - mae: 0.6650 - rmse: 0.8722 - smape: 1.2857 - val_ia: 0.2566 - val_loss: 0.7597 - val_mae: 0.6379 - val_rmse: 0.7112 - val_smape: 1.1964

Epoch 2/128

1915/1915 - 40s - 21ms/step - ia: 0.4073 - loss: 0.7913 - mae: 0.6503 - rmse: 0.8573 - smape: 1.2525 - val_ia: 0.2516 - val_loss: 0.7736 - val_mae: 0.6448 - val_rmse: 0.7200 - val_smape: 1.2262

Epoch 3/128

1915/1915 - 40s - 21ms/step - ia: 0.4174 - loss: 0.7808 - mae: 0.6447 - rmse: 0.8528 - smape: 1.2370 - val_ia: 0.2509 - val_loss: 0.7518 - val_mae: 0.6403 - val_rmse: 0.7093 - val_smape: 1.2562

Epoch 4/128

1915/1915 - 43s - 23ms/step - ia: 0.4205 - loss: 0.7721 - mae: 0.6411 - rmse: 0.8460 - smape: 1.2331 - val_ia: 0.2552 - val_loss: 0.7542 - val_mae: 0.6370 - val_rmse: 0.7097 - val_smape: 1.2063

Epoch 5/128

1915/1915 - 47s - 25ms/step - ia: 0.4277 - loss: 0.7627 - mae: 0.6365 - rmse: 0.8410 - smape: 1.2209 - val_ia: 0.2469 - val_loss: 0.7559 - val_mae: 0.6402 - val_rmse: 0.7080 - val_smape: 1.2587

Epoch 6/128

1915/1915 - 48s - 25ms/step - ia: 0.4330 - loss: 0.7516 - mae: 0.6327 - rmse: 0.8355 - smape: 1.2164 - val_ia: 0.2513 - val_loss: 0.7731 - val_mae: 0.6418 - val_rmse: 0.7155 - val_smape: 1.2306

Epoch 7/128

1915/1915 - 47s - 25ms/step - ia: 0.4388 - loss: 0.7365 - mae: 0.6263 - rmse: 0.8259 - smape: 1.2041 - val_ia: 0.2600 - val_loss: 0.7964 - val_mae: 0.6340 - val_rmse: 0.7113 - val_smape: 1.1885

Epoch 8/128

1915/1915 - 48s - 25ms/step - ia: 0.4450 - loss: 0.7238 - mae: 0.6221 - rmse: 0.8209 - smape: 1.1978 - val_ia: 0.2535 - val_loss: 0.8271 - val_mae: 0.6450 - val_rmse: 0.7170 - val_smape: 1.2212

Epoch 9/128

1915/1915 - 41s - 21ms/step - ia: 0.4518 - loss: 0.7063 - mae: 0.6144 - rmse: 0.8098 - smape: 1.1898 - val_ia: 0.2421 - val_loss: 0.8295 - val_mae: 0.6638 - val_rmse: 0.7389 - val_smape: 1.2665

Epoch 10/128

1915/1915 - 45s - 24ms/step - ia: 0.4584 - loss: 0.6898 - mae: 0.6079 - rmse: 0.8016 - smape: 1.1812 - val_ia: 0.2564 - val_loss: 0.8451 - val_mae: 0.6497 - val_rmse: 0.7290 - val_smape: 1.2178

Epoch 11/128

1915/1915 - 46s - 24ms/step - ia: 0.4669 - loss: 0.6713 - mae: 0.6010 - rmse: 0.7909 - smape: 1.1697 - val_ia: 0.2446 - val_loss: 0.9022 - val_mae: 0.6744 - val_rmse: 0.7509 - val_smape: 1.2878

Epoch 12/128

1915/1915 - 48s - 25ms/step - ia: 0.4757 - loss: 0.6516 - mae: 0.5927 - rmse: 0.7791 - smape: 1.1595 - val_ia: 0.2432 - val_loss: 0.8391 - val_mae: 0.6615 - val_rmse: 0.7387 - val_smape: 1.2914

Epoch 13/128

1915/1915 - 47s - 25ms/step - ia: 0.4849 - loss: 0.6307 - mae: 0.5837 - rmse: 0.7665 - smape: 1.1494 - val_ia: 0.2454 - val_loss: 0.9318 - val_mae: 0.6734 - val_rmse: 0.7503 - val_smape: 1.2549

Epoch 14/128

1915/1915 - 46s - 24ms/step - ia: 0.4929 - loss: 0.6067 - mae: 0.5747 - rmse: 0.7535 - smape: 1.1374 - val_ia: 0.2521 - val_loss: 0.9273 - val_mae: 0.6598 - val_rmse: 0.7382 - val_smape: 1.2102

Epoch 15/128

1915/1915 - 84s - 44ms/step - ia: 0.5022 - loss: 0.5830 - mae: 0.5646 - rmse: 0.7385 - smape: 1.1288 - val_ia: 0.2580 - val_loss: 0.9674 - val_mae: 0.6679 - val_rmse: 0.7554 - val_smape: 1.1911

Epoch 16/128

1915/1915 - 47s - 24ms/step - ia: 0.5149 - loss: 0.5573 - mae: 0.5534 - rmse: 0.7211 - smape: 1.1097 - val_ia: 0.2440 - val_loss: 0.9222 - val_mae: 0.6748 - val_rmse: 0.7548 - val_smape: 1.2699

Epoch 17/128

1915/1915 - 46s - 24ms/step - ia: 0.5264 - loss: 0.5314 - mae: 0.5424 - rmse: 0.7057 - smape: 1.0983 - val_ia: 0.2475 - val_loss: 0.9386 - val_mae: 0.6715 - val_rmse: 0.7541 - val_smape: 1.2424

Epoch 18/128

1915/1915 - 48s - 25ms/step - ia: 0.5380 - loss: 0.5067 - mae: 0.5305 - rmse: 0.6883 - smape: 1.0850 - val_ia: 0.2527 - val_loss: 0.9243 - val_mae: 0.6609 - val_rmse: 0.7452 - val_smape: 1.2038

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 6:32 3s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 33ms/step

 46%|████▌     | 23/50 [3:37:36<5:18:22, 707.49s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

958/958 - 62s - 65ms/step - ia: 0.3840 - loss: 0.8362 - mae: 0.6714 - rmse: 0.8949 - smape: 1.2843 - val_ia: 0.2664 - val_loss: 0.7490 - val_mae: 0.6333 - val_rmse: 0.7323 - val_smape: 1.1837

Epoch 2/8

958/958 - 27s - 28ms/step - ia: 0.4032 - loss: 0.8089 - mae: 0.6583 - rmse: 0.8810 - smape: 1.2502 - val_ia: 0.2597 - val_loss: 0.7883 - val_mae: 0.6480 - val_rmse: 0.7454 - val_smape: 1.2031

Epoch 3/8

958/958 - 28s - 29ms/step - ia: 0.4224 - loss: 0.7800 - mae: 0.6465 - rmse: 0.8656 - smape: 1.2276 - val_ia: 0.2569 - val_loss: 0.7905 - val_mae: 0.6598 - val_rmse: 0.7542 - val_smape: 1.3087

Epoch 4/8

958/958 - 27s - 29ms/step - ia: 0.4354 - loss: 0.7531 - mae: 0.6355 - rmse: 0.8502 - smape: 1.2148 - val_ia: 0.2708 - val_loss: 0.7964 - val_mae: 0.6281 - val_rmse: 0.7309 - val_smape: 1.1905

Epoch 5/8

958/958 - 28s - 29ms/step - ia: 0.4477 - loss: 0.7270 - mae: 0.6239 - rmse: 0.8337 - smape: 1.2054 - val_ia: 0.2565 - val_loss: 0.8366 - val_mae: 0.6732 - val_rmse: 0.7760 - val_smape: 1.3675

Epoch 6/8

958/958 - 25s - 26ms/step - ia: 0.4640 - loss: 0.6936 - mae: 0.6110 - rmse: 0.8168 - smape: 1.1898 - val_ia: 0.2543 - val_loss: 0.9054 - val_mae: 0.6971 - val_rmse: 0.8120 - val_smape: 1.3300

Epoch 7/8

958/958 - 28s - 29ms/step - ia: 0.4827 - loss: 0.6521 - mae: 0.5929 - rmse: 0.7904 - smape: 1.1659 - val_ia: 0.2645 - val_loss: 0.8974 - val_mae: 0.6755 - val_rmse: 0.7916 - val_smape: 1.2622

Epoch 8/8

958/958 - 42s - 43ms/step - ia: 0.4927 - loss: 0.6326 - mae: 0.5849 - rmse: 0.7795 - smape: 1.1561 - val_ia: 0.2625 - val_loss: 0.8297 - val_mae: 0.6487 - val_rmse: 0.7549 - val_smape: 1.2588

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 7:39 3s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 6s 20ms/step

 48%|████▊     | 24/50 [3:42:09<4:10:05, 577.13s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 76s - 40ms/step - ia: 0.2644 - loss: 1.0319 - mae: 0.7623 - rmse: 0.9747 - smape: 1.4923 - val_ia: 0.2314 - val_loss: 0.8196 - val_mae: 0.6806 - val_rmse: 0.7469 - val_smape: 1.2915

Epoch 2/128

1915/1915 - 43s - 22ms/step - ia: 0.3546 - loss: 0.8635 - mae: 0.6877 - rmse: 0.8959 - smape: 1.3050 - val_ia: 0.2419 - val_loss: 0.7835 - val_mae: 0.6482 - val_rmse: 0.7153 - val_smape: 1.2351

Epoch 3/128

1915/1915 - 36s - 19ms/step - ia: 0.3654 - loss: 0.8476 - mae: 0.6791 - rmse: 0.8877 - smape: 1.2922 - val_ia: 0.2412 - val_loss: 0.7790 - val_mae: 0.6598 - val_rmse: 0.7275 - val_smape: 1.2773

Epoch 4/128

1915/1915 - 46s - 24ms/step - ia: 0.3729 - loss: 0.8329 - mae: 0.6725 - rmse: 0.8794 - smape: 1.2902 - val_ia: 0.2439 - val_loss: 0.7690 - val_mae: 0.6457 - val_rmse: 0.7137 - val_smape: 1.2518

Epoch 5/128

1915/1915 - 45s - 24ms/step - ia: 0.3762 - loss: 0.8277 - mae: 0.6704 - rmse: 0.8776 - smape: 1.2923 - val_ia: 0.2449 - val_loss: 0.7637 - val_mae: 0.6465 - val_rmse: 0.7133 - val_smape: 1.2677

Epoch 6/128

1915/1915 - 48s - 25ms/step - ia: 0.3787 - loss: 0.8238 - mae: 0.6687 - rmse: 0.8746 - smape: 1.2860 - val_ia: 0.2422 - val_loss: 0.7621 - val_mae: 0.6473 - val_rmse: 0.7151 - val_smape: 1.2935

Epoch 7/128

1915/1915 - 43s - 23ms/step - ia: 0.3812 - loss: 0.8215 - mae: 0.6673 - rmse: 0.8744 - smape: 1.2853 - val_ia: 0.2442 - val_loss: 0.7622 - val_mae: 0.6462 - val_rmse: 0.7149 - val_smape: 1.2608

Epoch 8/128

1915/1915 - 45s - 23ms/step - ia: 0.3843 - loss: 0.8171 - mae: 0.6656 - rmse: 0.8736 - smape: 1.2821 - val_ia: 0.2455 - val_loss: 0.7548 - val_mae: 0.6357 - val_rmse: 0.7044 - val_smape: 1.2524

Epoch 9/128

1915/1915 - 80s - 42ms/step - ia: 0.3875 - loss: 0.8128 - mae: 0.6631 - rmse: 0.8696 - smape: 1.2802 - val_ia: 0.2462 - val_loss: 0.7587 - val_mae: 0.6348 - val_rmse: 0.7062 - val_smape: 1.2065

Epoch 10/128

1915/1915 - 45s - 23ms/step - ia: 0.3920 - loss: 0.8098 - mae: 0.6600 - rmse: 0.8672 - smape: 1.2698 - val_ia: 0.2445 - val_loss: 0.7616 - val_mae: 0.6406 - val_rmse: 0.7109 - val_smape: 1.2383

Epoch 11/128

1915/1915 - 47s - 25ms/step - ia: 0.3934 - loss: 0.8053 - mae: 0.6599 - rmse: 0.8648 - smape: 1.2697 - val_ia: 0.2430 - val_loss: 0.7579 - val_mae: 0.6382 - val_rmse: 0.7070 - val_smape: 1.2756

Epoch 12/128

1915/1915 - 80s - 42ms/step - ia: 0.3944 - loss: 0.8031 - mae: 0.6576 - rmse: 0.8639 - smape: 1.2673 - val_ia: 0.2451 - val_loss: 0.7630 - val_mae: 0.6343 - val_rmse: 0.7058 - val_smape: 1.2266

Epoch 13/128

1915/1915 - 45s - 23ms/step - ia: 0.3991 - loss: 0.8023 - mae: 0.6560 - rmse: 0.8624 - smape: 1.2625 - val_ia: 0.2450 - val_loss: 0.7529 - val_mae: 0.6335 - val_rmse: 0.7031 - val_smape: 1.2658

Epoch 14/128

1915/1915 - 40s - 21ms/step - ia: 0.3985 - loss: 0.7960 - mae: 0.6546 - rmse: 0.8603 - smape: 1.2636 - val_ia: 0.2433 - val_loss: 0.7740 - val_mae: 0.6431 - val_rmse: 0.7155 - val_smape: 1.2294

Epoch 15/128

1915/1915 - 45s - 24ms/step - ia: 0.4003 - loss: 0.7969 - mae: 0.6550 - rmse: 0.8603 - smape: 1.2644 - val_ia: 0.2469 - val_loss: 0.7520 - val_mae: 0.6295 - val_rmse: 0.7001 - val_smape: 1.2311

Epoch 16/128

1915/1915 - 46s - 24ms/step - ia: 0.4027 - loss: 0.7943 - mae: 0.6521 - rmse: 0.8583 - smape: 1.2624 - val_ia: 0.2439 - val_loss: 0.7563 - val_mae: 0.6387 - val_rmse: 0.7086 - val_smape: 1.2592

Epoch 17/128

1915/1915 - 43s - 23ms/step - ia: 0.4036 - loss: 0.7927 - mae: 0.6512 - rmse: 0.8577 - smape: 1.2510 - val_ia: 0.2423 - val_loss: 0.7591 - val_mae: 0.6416 - val_rmse: 0.7100 - val_smape: 1.3010

Epoch 18/128

1915/1915 - 44s - 23ms/step - ia: 0.4036 - loss: 0.7877 - mae: 0.6499 - rmse: 0.8554 - smape: 1.2582 - val_ia: 0.2433 - val_loss: 0.7596 - val_mae: 0.6431 - val_rmse: 0.7131 - val_smape: 1.2691

Epoch 19/128

1915/1915 - 39s - 21ms/step - ia: 0.4088 - loss: 0.7847 - mae: 0.6486 - rmse: 0.8542 - smape: 1.2508 - val_ia: 0.2417 - val_loss: 0.7658 - val_mae: 0.6436 - val_rmse: 0.7148 - val_smape: 1.2782

Epoch 20/128

1915/1915 - 41s - 21ms/step - ia: 0.4089 - loss: 0.7806 - mae: 0.6480 - rmse: 0.8519 - smape: 1.2508 - val_ia: 0.2477 - val_loss: 0.7511 - val_mae: 0.6336 - val_rmse: 0.7047 - val_smape: 1.2564

Epoch 21/128

1915/1915 - 44s - 23ms/step - ia: 0.4128 - loss: 0.7774 - mae: 0.6450 - rmse: 0.8497 - smape: 1.2466 - val_ia: 0.2440 - val_loss: 0.7840 - val_mae: 0.6419 - val_rmse: 0.7144 - val_smape: 1.2578

Epoch 22/128

1915/1915 - 43s - 23ms/step - ia: 0.4126 - loss: 0.7733 - mae: 0.6437 - rmse: 0.8491 - smape: 1.2484 - val_ia: 0.2443 - val_loss: 0.7757 - val_mae: 0.6432 - val_rmse: 0.7168 - val_smape: 1.2289

Epoch 23/128

1915/1915 - 82s - 43ms/step - ia: 0.4145 - loss: 0.7722 - mae: 0.6421 - rmse: 0.8455 - smape: 1.2448 - val_ia: 0.2472 - val_loss: 0.7522 - val_mae: 0.6341 - val_rmse: 0.7050 - val_smape: 1.2609

Epoch 24/128

1915/1915 - 39s - 20ms/step - ia: 0.4174 - loss: 0.7691 - mae: 0.6417 - rmse: 0.8449 - smape: 1.2427 - val_ia: 0.2492 - val_loss: 0.7582 - val_mae: 0.6343 - val_rmse: 0.7061 - val_smape: 1.2539

Epoch 25/128

1915/1915 - 44s - 23ms/step - ia: 0.4217 - loss: 0.7647 - mae: 0.6394 - rmse: 0.8435 - smape: 1.2364 - val_ia: 0.2410 - val_loss: 0.7948 - val_mae: 0.6552 - val_rmse: 0.7262 - val_smape: 1.2841

Epoch 26/128

1915/1915 - 40s - 21ms/step - ia: 0.4189 - loss: 0.7678 - mae: 0.6402 - rmse: 0.8429 - smape: 1.2421 - val_ia: 0.2435 - val_loss: 0.7687 - val_mae: 0.6442 - val_rmse: 0.7152 - val_smape: 1.2729

Epoch 27/128

1915/1915 - 37s - 19ms/step - ia: 0.4197 - loss: 0.7637 - mae: 0.6390 - rmse: 0.8424 - smape: 1.2461 - val_ia: 0.2404 - val_loss: 0.7831 - val_mae: 0.6545 - val_rmse: 0.7258 - val_smape: 1.2945

Epoch 28/128

1915/1915 - 43s - 22ms/step - ia: 0.4248 - loss: 0.7560 - mae: 0.6349 - rmse: 0.8385 - smape: 1.2314 - val_ia: 0.2487 - val_loss: 0.7590 - val_mae: 0.6318 - val_rmse: 0.7032 - val_smape: 1.2581

Epoch 29/128

1915/1915 - 46s - 24ms/step - ia: 0.4230 - loss: 0.7582 - mae: 0.6365 - rmse: 0.8388 - smape: 1.2398 - val_ia: 0.2491 - val_loss: 0.7686 - val_mae: 0.6385 - val_rmse: 0.7116 - val_smape: 1.2423

Epoch 30/128

1915/1915 - 45s - 23ms/step - ia: 0.4253 - loss: 0.7551 - mae: 0.6344 - rmse: 0.8366 - smape: 1.2301 - val_ia: 0.2425 - val_loss: 0.7728 - val_mae: 0.6459 - val_rmse: 0.7166 - val_smape: 1.3005

Epoch 31/128

1915/1915 - 45s - 24ms/step - ia: 0.4237 - loss: 0.7552 - mae: 0.6351 - rmse: 0.8369 - smape: 1.2364 - val_ia: 0.2472 - val_loss: 0.7618 - val_mae: 0.6388 - val_rmse: 0.7098 - val_smape: 1.2527

Epoch 32/128

1915/1915 - 43s - 23ms/step - ia: 0.4266 - loss: 0.7514 - mae: 0.6333 - rmse: 0.8348 - smape: 1.2369 - val_ia: 0.2408 - val_loss: 0.7862 - val_mae: 0.6559 - val_rmse: 0.7261 - val_smape: 1.3156

Epoch 33/128

1915/1915 - 46s - 24ms/step - ia: 0.4282 - loss: 0.7479 - mae: 0.6322 - rmse: 0.8323 - smape: 1.2354 - val_ia: 0.2481 - val_loss: 0.7835 - val_mae: 0.6438 - val_rmse: 0.7179 - val_smape: 1.2495

Epoch 34/128

1915/1915 - 43s - 23ms/step - ia: 0.4299 - loss: 0.7460 - mae: 0.6309 - rmse: 0.8310 - smape: 1.2292 - val_ia: 0.2454 - val_loss: 0.8089 - val_mae: 0.6539 - val_rmse: 0.7295 - val_smape: 1.2517

Epoch 35/128

1915/1915 - 44s - 23ms/step - ia: 0.4298 - loss: 0.7461 - mae: 0.6315 - rmse: 0.8317 - smape: 1.2312 - val_ia: 0.2440 - val_loss: 0.7726 - val_mae: 0.6459 - val_rmse: 0.7159 - val_smape: 1.3159

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 7:35 3s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 8s 35ms/step

 50%|█████     | 25/50 [4:10:01<6:17:21, 905.65s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 57s - 60ms/step - ia: 0.2159 - loss: 1.0568 - mae: 0.7672 - rmse: 1.0058 - smape: 1.5698 - val_ia: 0.2320 - val_loss: 0.9453 - val_mae: 0.7355 - val_rmse: 0.8187 - val_smape: 1.8570

Epoch 2/256

958/958 - 12s - 13ms/step - ia: 0.2548 - loss: 0.9538 - mae: 0.7287 - rmse: 0.9557 - smape: 1.4966 - val_ia: 0.2514 - val_loss: 0.8119 - val_mae: 0.6642 - val_rmse: 0.7529 - val_smape: 1.3579

Epoch 3/256

958/958 - 15s - 15ms/step - ia: 0.3538 - loss: 0.8804 - mae: 0.6946 - rmse: 0.9210 - smape: 1.3222 - val_ia: 0.2536 - val_loss: 0.7959 - val_mae: 0.6657 - val_rmse: 0.7571 - val_smape: 1.3193

Epoch 4/256

958/958 - 18s - 19ms/step - ia: 0.3670 - loss: 0.8593 - mae: 0.6839 - rmse: 0.9087 - smape: 1.2951 - val_ia: 0.2559 - val_loss: 0.7868 - val_mae: 0.6585 - val_rmse: 0.7512 - val_smape: 1.2875

Epoch 5/256

958/958 - 18s - 19ms/step - ia: 0.3697 - loss: 0.8548 - mae: 0.6817 - rmse: 0.9060 - smape: 1.2910 - val_ia: 0.2574 - val_loss: 0.7790 - val_mae: 0.6492 - val_rmse: 0.7422 - val_smape: 1.2560

Epoch 6/256

958/958 - 17s - 18ms/step - ia: 0.3756 - loss: 0.8467 - mae: 0.6777 - rmse: 0.9027 - smape: 1.2817 - val_ia: 0.2573 - val_loss: 0.7756 - val_mae: 0.6455 - val_rmse: 0.7379 - val_smape: 1.2487

Epoch 7/256

958/958 - 18s - 18ms/step - ia: 0.3737 - loss: 0.8450 - mae: 0.6781 - rmse: 0.9017 - smape: 1.2850 - val_ia: 0.2571 - val_loss: 0.7746 - val_mae: 0.6452 - val_rmse: 0.7377 - val_smape: 1.2484

Epoch 8/256

958/958 - 17s - 18ms/step - ia: 0.3777 - loss: 0.8379 - mae: 0.6740 - rmse: 0.8963 - smape: 1.2782 - val_ia: 0.2582 - val_loss: 0.7700 - val_mae: 0.6435 - val_rmse: 0.7369 - val_smape: 1.2357

Epoch 9/256

958/958 - 19s - 20ms/step - ia: 0.3828 - loss: 0.8349 - mae: 0.6724 - rmse: 0.8958 - smape: 1.2704 - val_ia: 0.2571 - val_loss: 0.7694 - val_mae: 0.6458 - val_rmse: 0.7375 - val_smape: 1.2573

Epoch 10/256

958/958 - 18s - 18ms/step - ia: 0.3786 - loss: 0.8334 - mae: 0.6723 - rmse: 0.8945 - smape: 1.2786 - val_ia: 0.2560 - val_loss: 0.7788 - val_mae: 0.6615 - val_rmse: 0.7544 - val_smape: 1.2961

Epoch 11/256

958/958 - 19s - 20ms/step - ia: 0.3846 - loss: 0.8275 - mae: 0.6699 - rmse: 0.8910 - smape: 1.2702 - val_ia: 0.2579 - val_loss: 0.7665 - val_mae: 0.6459 - val_rmse: 0.7391 - val_smape: 1.2490

Epoch 12/256

958/958 - 17s - 18ms/step - ia: 0.3844 - loss: 0.8242 - mae: 0.6686 - rmse: 0.8888 - smape: 1.2695 - val_ia: 0.2583 - val_loss: 0.7647 - val_mae: 0.6434 - val_rmse: 0.7375 - val_smape: 1.2367

Epoch 13/256

958/958 - 16s - 16ms/step - ia: 0.3866 - loss: 0.8259 - mae: 0.6685 - rmse: 0.8903 - smape: 1.2680 - val_ia: 0.2571 - val_loss: 0.7631 - val_mae: 0.6399 - val_rmse: 0.7324 - val_smape: 1.2392

Epoch 14/256

958/958 - 15s - 16ms/step - ia: 0.3862 - loss: 0.8221 - mae: 0.6669 - rmse: 0.8895 - smape: 1.2688 - val_ia: 0.2580 - val_loss: 0.7644 - val_mae: 0.6476 - val_rmse: 0.7415 - val_smape: 1.2545

Epoch 15/256

958/958 - 17s - 18ms/step - ia: 0.3879 - loss: 0.8207 - mae: 0.6666 - rmse: 0.8893 - smape: 1.2645 - val_ia: 0.2576 - val_loss: 0.7586 - val_mae: 0.6401 - val_rmse: 0.7327 - val_smape: 1.2437

Epoch 16/256

958/958 - 17s - 17ms/step - ia: 0.3865 - loss: 0.8196 - mae: 0.6658 - rmse: 0.8872 - smape: 1.2700 - val_ia: 0.2580 - val_loss: 0.7593 - val_mae: 0.6398 - val_rmse: 0.7339 - val_smape: 1.2327

Epoch 17/256

958/958 - 17s - 18ms/step - ia: 0.3897 - loss: 0.8174 - mae: 0.6646 - rmse: 0.8863 - smape: 1.2645 - val_ia: 0.2582 - val_loss: 0.7591 - val_mae: 0.6431 - val_rmse: 0.7373 - val_smape: 1.2442

Epoch 18/256

958/958 - 18s - 19ms/step - ia: 0.3917 - loss: 0.8145 - mae: 0.6633 - rmse: 0.8860 - smape: 1.2642 - val_ia: 0.2586 - val_loss: 0.7525 - val_mae: 0.6310 - val_rmse: 0.7242 - val_smape: 1.2132

Epoch 19/256

958/958 - 18s - 19ms/step - ia: 0.3930 - loss: 0.8150 - mae: 0.6627 - rmse: 0.8857 - smape: 1.2621 - val_ia: 0.2576 - val_loss: 0.7546 - val_mae: 0.6401 - val_rmse: 0.7325 - val_smape: 1.2542

Epoch 20/256

958/958 - 18s - 19ms/step - ia: 0.3918 - loss: 0.8127 - mae: 0.6621 - rmse: 0.8824 - smape: 1.2647 - val_ia: 0.2580 - val_loss: 0.7569 - val_mae: 0.6421 - val_rmse: 0.7361 - val_smape: 1.2473

Epoch 21/256

958/958 - 18s - 19ms/step - ia: 0.3941 - loss: 0.8115 - mae: 0.6614 - rmse: 0.8833 - smape: 1.2595 - val_ia: 0.2577 - val_loss: 0.7544 - val_mae: 0.6422 - val_rmse: 0.7350 - val_smape: 1.2604

Epoch 22/256

958/958 - 18s - 19ms/step - ia: 0.3941 - loss: 0.8098 - mae: 0.6617 - rmse: 0.8818 - smape: 1.2620 - val_ia: 0.2581 - val_loss: 0.7507 - val_mae: 0.6365 - val_rmse: 0.7298 - val_smape: 1.2406

Epoch 23/256

958/958 - 19s - 20ms/step - ia: 0.3956 - loss: 0.8075 - mae: 0.6593 - rmse: 0.8833 - smape: 1.2592 - val_ia: 0.2580 - val_loss: 0.7525 - val_mae: 0.6406 - val_rmse: 0.7339 - val_smape: 1.2553

Epoch 24/256

958/958 - 18s - 19ms/step - ia: 0.3968 - loss: 0.8083 - mae: 0.6597 - rmse: 0.8813 - smape: 1.2571 - val_ia: 0.2591 - val_loss: 0.7542 - val_mae: 0.6442 - val_rmse: 0.7388 - val_smape: 1.2548

Epoch 25/256

958/958 - 19s - 20ms/step - ia: 0.3965 - loss: 0.8070 - mae: 0.6591 - rmse: 0.8802 - smape: 1.2558 - val_ia: 0.2588 - val_loss: 0.7485 - val_mae: 0.6327 - val_rmse: 0.7272 - val_smape: 1.2249

Epoch 26/256

958/958 - 18s - 19ms/step - ia: 0.3974 - loss: 0.8064 - mae: 0.6585 - rmse: 0.8800 - smape: 1.2578 - val_ia: 0.2597 - val_loss: 0.7468 - val_mae: 0.6291 - val_rmse: 0.7243 - val_smape: 1.2068

Epoch 27/256

958/958 - 19s - 19ms/step - ia: 0.3991 - loss: 0.8059 - mae: 0.6584 - rmse: 0.8801 - smape: 1.2546 - val_ia: 0.2590 - val_loss: 0.7516 - val_mae: 0.6433 - val_rmse: 0.7373 - val_smape: 1.2598

Epoch 28/256

958/958 - 19s - 19ms/step - ia: 0.3963 - loss: 0.8047 - mae: 0.6588 - rmse: 0.8803 - smape: 1.2594 - val_ia: 0.2594 - val_loss: 0.7476 - val_mae: 0.6334 - val_rmse: 0.7284 - val_smape: 1.2228

Epoch 29/256

958/958 - 19s - 20ms/step - ia: 0.4007 - loss: 0.8026 - mae: 0.6573 - rmse: 0.8776 - smape: 1.2518 - val_ia: 0.2597 - val_loss: 0.7527 - val_mae: 0.6418 - val_rmse: 0.7374 - val_smape: 1.2442

Epoch 30/256

958/958 - 18s - 19ms/step - ia: 0.4010 - loss: 0.8021 - mae: 0.6571 - rmse: 0.8776 - smape: 1.2518 - val_ia: 0.2591 - val_loss: 0.7477 - val_mae: 0.6382 - val_rmse: 0.7322 - val_smape: 1.2483

Epoch 31/256

958/958 - 18s - 19ms/step - ia: 0.3999 - loss: 0.8004 - mae: 0.6566 - rmse: 0.8778 - smape: 1.2519 - val_ia: 0.2602 - val_loss: 0.7467 - val_mae: 0.6341 - val_rmse: 0.7296 - val_smape: 1.2259

Epoch 32/256

958/958 - 14s - 15ms/step - ia: 0.4027 - loss: 0.7999 - mae: 0.6556 - rmse: 0.8767 - smape: 1.2518 - val_ia: 0.2599 - val_loss: 0.7463 - val_mae: 0.6358 - val_rmse: 0.7309 - val_smape: 1.2367

Epoch 33/256

958/958 - 18s - 19ms/step - ia: 0.4031 - loss: 0.7995 - mae: 0.6559 - rmse: 0.8763 - smape: 1.2531 - val_ia: 0.2600 - val_loss: 0.7491 - val_mae: 0.6380 - val_rmse: 0.7334 - val_smape: 1.2376

Epoch 34/256

958/958 - 18s - 19ms/step - ia: 0.4037 - loss: 0.7977 - mae: 0.6554 - rmse: 0.8750 - smape: 1.2504 - val_ia: 0.2593 - val_loss: 0.7420 - val_mae: 0.6305 - val_rmse: 0.7243 - val_smape: 1.2308

Epoch 35/256

958/958 - 19s - 20ms/step - ia: 0.4043 - loss: 0.7960 - mae: 0.6539 - rmse: 0.8750 - smape: 1.2475 - val_ia: 0.2610 - val_loss: 0.7509 - val_mae: 0.6392 - val_rmse: 0.7354 - val_smape: 1.2356

Epoch 36/256

958/958 - 18s - 19ms/step - ia: 0.4029 - loss: 0.7963 - mae: 0.6543 - rmse: 0.8748 - smape: 1.2502 - val_ia: 0.2612 - val_loss: 0.7569 - val_mae: 0.6446 - val_rmse: 0.7415 - val_smape: 1.2426

Epoch 37/256

958/958 - 16s - 17ms/step - ia: 0.4065 - loss: 0.7981 - mae: 0.6547 - rmse: 0.8753 - smape: 1.2459 - val_ia: 0.2600 - val_loss: 0.7463 - val_mae: 0.6383 - val_rmse: 0.7331 - val_smape: 1.2502

Epoch 38/256

958/958 - 15s - 16ms/step - ia: 0.4037 - loss: 0.7962 - mae: 0.6541 - rmse: 0.8748 - smape: 1.2529 - val_ia: 0.2614 - val_loss: 0.7515 - val_mae: 0.6377 - val_rmse: 0.7349 - val_smape: 1.2258

Epoch 39/256

958/958 - 20s - 21ms/step - ia: 0.4072 - loss: 0.7954 - mae: 0.6536 - rmse: 0.8742 - smape: 1.2471 - val_ia: 0.2605 - val_loss: 0.7486 - val_mae: 0.6358 - val_rmse: 0.7319 - val_smape: 1.2301

Epoch 40/256

958/958 - 18s - 19ms/step - ia: 0.4076 - loss: 0.7917 - mae: 0.6521 - rmse: 0.8709 - smape: 1.2468 - val_ia: 0.2609 - val_loss: 0.7464 - val_mae: 0.6321 - val_rmse: 0.7286 - val_smape: 1.2197

Epoch 41/256

958/958 - 21s - 22ms/step - ia: 0.4077 - loss: 0.7916 - mae: 0.6517 - rmse: 0.8716 - smape: 1.2444 - val_ia: 0.2609 - val_loss: 0.7489 - val_mae: 0.6401 - val_rmse: 0.7360 - val_smape: 1.2468

Epoch 42/256

958/958 - 18s - 19ms/step - ia: 0.4100 - loss: 0.7899 - mae: 0.6506 - rmse: 0.8719 - smape: 1.2421 - val_ia: 0.2609 - val_loss: 0.7448 - val_mae: 0.6407 - val_rmse: 0.7349 - val_smape: 1.2661

Epoch 43/256

958/958 - 20s - 21ms/step - ia: 0.4085 - loss: 0.7900 - mae: 0.6512 - rmse: 0.8716 - smape: 1.2460 - val_ia: 0.2607 - val_loss: 0.7421 - val_mae: 0.6318 - val_rmse: 0.7270 - val_smape: 1.2343

Epoch 44/256

958/958 - 19s - 20ms/step - ia: 0.4092 - loss: 0.7917 - mae: 0.6518 - rmse: 0.8711 - smape: 1.2447 - val_ia: 0.2599 - val_loss: 0.7409 - val_mae: 0.6332 - val_rmse: 0.7269 - val_smape: 1.2509

Epoch 45/256

958/958 - 19s - 20ms/step - ia: 0.4086 - loss: 0.7888 - mae: 0.6508 - rmse: 0.8712 - smape: 1.2465 - val_ia: 0.2617 - val_loss: 0.7438 - val_mae: 0.6306 - val_rmse: 0.7269 - val_smape: 1.2208

Epoch 46/256

958/958 - 19s - 20ms/step - ia: 0.4109 - loss: 0.7870 - mae: 0.6496 - rmse: 0.8690 - smape: 1.2446 - val_ia: 0.2619 - val_loss: 0.7449 - val_mae: 0.6350 - val_rmse: 0.7312 - val_smape: 1.2346

Epoch 47/256

958/958 - 18s - 19ms/step - ia: 0.4106 - loss: 0.7873 - mae: 0.6505 - rmse: 0.8695 - smape: 1.2451 - val_ia: 0.2622 - val_loss: 0.7464 - val_mae: 0.6355 - val_rmse: 0.7318 - val_smape: 1.2344

Epoch 48/256

958/958 - 19s - 20ms/step - ia: 0.4109 - loss: 0.7897 - mae: 0.6505 - rmse: 0.8716 - smape: 1.2426 - val_ia: 0.2615 - val_loss: 0.7485 - val_mae: 0.6357 - val_rmse: 0.7316 - val_smape: 1.2352

Epoch 49/256

958/958 - 18s - 19ms/step - ia: 0.4084 - loss: 0.7865 - mae: 0.6498 - rmse: 0.8682 - smape: 1.2435 - val_ia: 0.2626 - val_loss: 0.7471 - val_mae: 0.6328 - val_rmse: 0.7296 - val_smape: 1.2236

Epoch 50/256

958/958 - 18s - 19ms/step - ia: 0.4140 - loss: 0.7842 - mae: 0.6487 - rmse: 0.8689 - smape: 1.2397 - val_ia: 0.2612 - val_loss: 0.7375 - val_mae: 0.6294 - val_rmse: 0.7234 - val_smape: 1.2416

Epoch 51/256

958/958 - 20s - 20ms/step - ia: 0.4122 - loss: 0.7826 - mae: 0.6478 - rmse: 0.8670 - smape: 1.2424 - val_ia: 0.2625 - val_loss: 0.7398 - val_mae: 0.6293 - val_rmse: 0.7252 - val_smape: 1.2291

Epoch 52/256

958/958 - 18s - 19ms/step - ia: 0.4149 - loss: 0.7822 - mae: 0.6474 - rmse: 0.8670 - smape: 1.2394 - val_ia: 0.2634 - val_loss: 0.7557 - val_mae: 0.6439 - val_rmse: 0.7411 - val_smape: 1.2510

Epoch 53/256

958/958 - 18s - 19ms/step - ia: 0.4130 - loss: 0.7827 - mae: 0.6474 - rmse: 0.8663 - smape: 1.2395 - val_ia: 0.2623 - val_loss: 0.7473 - val_mae: 0.6365 - val_rmse: 0.7327 - val_smape: 1.2438

Epoch 54/256

958/958 - 18s - 19ms/step - ia: 0.4134 - loss: 0.7824 - mae: 0.6477 - rmse: 0.8665 - smape: 1.2437 - val_ia: 0.2636 - val_loss: 0.7485 - val_mae: 0.6345 - val_rmse: 0.7320 - val_smape: 1.2258

Epoch 55/256

958/958 - 20s - 21ms/step - ia: 0.4146 - loss: 0.7822 - mae: 0.6478 - rmse: 0.8673 - smape: 1.2378 - val_ia: 0.2645 - val_loss: 0.7592 - val_mae: 0.6420 - val_rmse: 0.7404 - val_smape: 1.2353

Epoch 56/256

958/958 - 18s - 19ms/step - ia: 0.4171 - loss: 0.7797 - mae: 0.6463 - rmse: 0.8644 - smape: 1.2366 - val_ia: 0.2627 - val_loss: 0.7397 - val_mae: 0.6287 - val_rmse: 0.7240 - val_smape: 1.2324

Epoch 57/256

958/958 - 19s - 20ms/step - ia: 0.4159 - loss: 0.7795 - mae: 0.6454 - rmse: 0.8634 - smape: 1.2351 - val_ia: 0.2644 - val_loss: 0.7577 - val_mae: 0.6418 - val_rmse: 0.7398 - val_smape: 1.2394

Epoch 58/256

958/958 - 20s - 21ms/step - ia: 0.4167 - loss: 0.7774 - mae: 0.6458 - rmse: 0.8644 - smape: 1.2351 - val_ia: 0.2648 - val_loss: 0.7599 - val_mae: 0.6392 - val_rmse: 0.7383 - val_smape: 1.2225

Epoch 59/256

958/958 - 18s - 19ms/step - ia: 0.4158 - loss: 0.7781 - mae: 0.6468 - rmse: 0.8638 - smape: 1.2365 - val_ia: 0.2645 - val_loss: 0.7556 - val_mae: 0.6382 - val_rmse: 0.7362 - val_smape: 1.2339

Epoch 60/256

958/958 - 21s - 22ms/step - ia: 0.4181 - loss: 0.7772 - mae: 0.6449 - rmse: 0.8641 - smape: 1.2335 - val_ia: 0.2639 - val_loss: 0.7561 - val_mae: 0.6434 - val_rmse: 0.7405 - val_smape: 1.2551

Epoch 61/256

958/958 - 18s - 19ms/step - ia: 0.4154 - loss: 0.7774 - mae: 0.6459 - rmse: 0.8637 - smape: 1.2390 - val_ia: 0.2650 - val_loss: 0.7673 - val_mae: 0.6452 - val_rmse: 0.7449 - val_smape: 1.2350

Epoch 62/256

958/958 - 20s - 20ms/step - ia: 0.4193 - loss: 0.7743 - mae: 0.6445 - rmse: 0.8629 - smape: 1.2350 - val_ia: 0.2641 - val_loss: 0.7444 - val_mae: 0.6287 - val_rmse: 0.7255 - val_smape: 1.2198

Epoch 63/256

958/958 - 19s - 19ms/step - ia: 0.4181 - loss: 0.7764 - mae: 0.6451 - rmse: 0.8623 - smape: 1.2361 - val_ia: 0.2646 - val_loss: 0.7447 - val_mae: 0.6305 - val_rmse: 0.7273 - val_smape: 1.2276

Epoch 64/256

958/958 - 18s - 19ms/step - ia: 0.4190 - loss: 0.7748 - mae: 0.6437 - rmse: 0.8617 - smape: 1.2336 - val_ia: 0.2656 - val_loss: 0.7610 - val_mae: 0.6424 - val_rmse: 0.7412 - val_smape: 1.2395

Epoch 65/256

958/958 - 19s - 20ms/step - ia: 0.4186 - loss: 0.7754 - mae: 0.6443 - rmse: 0.8636 - smape: 1.2341 - val_ia: 0.2651 - val_loss: 0.7537 - val_mae: 0.6369 - val_rmse: 0.7351 - val_smape: 1.2325

Epoch 65: early stopping

Restoring model weights from the end of the best epoch: 50.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 6:59 3s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step

 52%|█████▏    | 26/50 [4:30:26<6:40:33, 1001.38s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1915/1915 - 51s - 27ms/step - ia: 0.3657 - loss: 0.8293 - mae: 0.6714 - rmse: 0.8776 - smape: 1.3134 - val_ia: 0.2497 - val_loss: 0.7602 - val_mae: 0.6420 - val_rmse: 0.7137 - val_smape: 1.2373

Epoch 2/64

1915/1915 - 30s - 16ms/step - ia: 0.3911 - loss: 0.8039 - mae: 0.6587 - rmse: 0.8655 - smape: 1.2736 - val_ia: 0.2457 - val_loss: 0.7477 - val_mae: 0.6441 - val_rmse: 0.7124 - val_smape: 1.2944

Epoch 3/64

1915/1915 - 31s - 16ms/step - ia: 0.4004 - loss: 0.7948 - mae: 0.6534 - rmse: 0.8592 - smape: 1.2607 - val_ia: 0.2474 - val_loss: 0.7647 - val_mae: 0.6450 - val_rmse: 0.7156 - val_smape: 1.2508

Epoch 4/64

1915/1915 - 36s - 19ms/step - ia: 0.4062 - loss: 0.7887 - mae: 0.6496 - rmse: 0.8552 - smape: 1.2487 - val_ia: 0.2532 - val_loss: 0.7435 - val_mae: 0.6356 - val_rmse: 0.7066 - val_smape: 1.2157

Epoch 5/64

1915/1915 - 26s - 13ms/step - ia: 0.4116 - loss: 0.7829 - mae: 0.6465 - rmse: 0.8521 - smape: 1.2411 - val_ia: 0.2528 - val_loss: 0.7421 - val_mae: 0.6339 - val_rmse: 0.7044 - val_smape: 1.2279

Epoch 6/64

1915/1915 - 29s - 15ms/step - ia: 0.4151 - loss: 0.7770 - mae: 0.6433 - rmse: 0.8500 - smape: 1.2334 - val_ia: 0.2461 - val_loss: 0.7610 - val_mae: 0.6487 - val_rmse: 0.7187 - val_smape: 1.2661

Epoch 7/64

1915/1915 - 30s - 15ms/step - ia: 0.4170 - loss: 0.7732 - mae: 0.6414 - rmse: 0.8476 - smape: 1.2280 - val_ia: 0.2490 - val_loss: 0.7632 - val_mae: 0.6440 - val_rmse: 0.7146 - val_smape: 1.2459

Epoch 8/64

1915/1915 - 30s - 16ms/step - ia: 0.4216 - loss: 0.7702 - mae: 0.6398 - rmse: 0.8452 - smape: 1.2272 - val_ia: 0.2557 - val_loss: 0.7543 - val_mae: 0.6335 - val_rmse: 0.7060 - val_smape: 1.2144

Epoch 9/64

1915/1915 - 31s - 16ms/step - ia: 0.4243 - loss: 0.7662 - mae: 0.6374 - rmse: 0.8436 - smape: 1.2220 - val_ia: 0.2595 - val_loss: 0.7566 - val_mae: 0.6317 - val_rmse: 0.7053 - val_smape: 1.1942

Epoch 10/64

1915/1915 - 30s - 16ms/step - ia: 0.4274 - loss: 0.7638 - mae: 0.6366 - rmse: 0.8412 - smape: 1.2192 - val_ia: 0.2534 - val_loss: 0.7405 - val_mae: 0.6344 - val_rmse: 0.7036 - val_smape: 1.2535

Epoch 11/64

1915/1915 - 42s - 22ms/step - ia: 0.4282 - loss: 0.7605 - mae: 0.6347 - rmse: 0.8398 - smape: 1.2186 - val_ia: 0.2535 - val_loss: 0.7440 - val_mae: 0.6366 - val_rmse: 0.7062 - val_smape: 1.2580

Epoch 12/64

1915/1915 - 30s - 15ms/step - ia: 0.4272 - loss: 0.7576 - mae: 0.6347 - rmse: 0.8387 - smape: 1.2221 - val_ia: 0.2614 - val_loss: 0.7497 - val_mae: 0.6284 - val_rmse: 0.7018 - val_smape: 1.2020

Epoch 13/64

1915/1915 - 28s - 14ms/step - ia: 0.4295 - loss: 0.7556 - mae: 0.6334 - rmse: 0.8362 - smape: 1.2197 - val_ia: 0.2490 - val_loss: 0.7679 - val_mae: 0.6487 - val_rmse: 0.7188 - val_smape: 1.2738

Epoch 14/64

1915/1915 - 29s - 15ms/step - ia: 0.4314 - loss: 0.7521 - mae: 0.6315 - rmse: 0.8354 - smape: 1.2145 - val_ia: 0.2600 - val_loss: 0.7719 - val_mae: 0.6353 - val_rmse: 0.7092 - val_smape: 1.1996

Epoch 15/64

1915/1915 - 24s - 13ms/step - ia: 0.4326 - loss: 0.7497 - mae: 0.6306 - rmse: 0.8355 - smape: 1.2154 - val_ia: 0.2562 - val_loss: 0.7582 - val_mae: 0.6387 - val_rmse: 0.7104 - val_smape: 1.2402

Epoch 16/64

1915/1915 - 25s - 13ms/step - ia: 0.4342 - loss: 0.7470 - mae: 0.6297 - rmse: 0.8302 - smape: 1.2152 - val_ia: 0.2523 - val_loss: 0.7684 - val_mae: 0.6423 - val_rmse: 0.7128 - val_smape: 1.2472

Epoch 17/64

1915/1915 - 29s - 15ms/step - ia: 0.4365 - loss: 0.7438 - mae: 0.6279 - rmse: 0.8304 - smape: 1.2083 - val_ia: 0.2559 - val_loss: 0.7606 - val_mae: 0.6388 - val_rmse: 0.7102 - val_smape: 1.2370

Epoch 18/64

1915/1915 - 29s - 15ms/step - ia: 0.4362 - loss: 0.7402 - mae: 0.6268 - rmse: 0.8283 - smape: 1.2099 - val_ia: 0.2586 - val_loss: 0.7815 - val_mae: 0.6374 - val_rmse: 0.7106 - val_smape: 1.2094

Epoch 19/64

1915/1915 - 30s - 16ms/step - ia: 0.4399 - loss: 0.7370 - mae: 0.6254 - rmse: 0.8276 - smape: 1.2070 - val_ia: 0.2583 - val_loss: 0.7716 - val_mae: 0.6321 - val_rmse: 0.7042 - val_smape: 1.2125

Epoch 20/64

1915/1915 - 31s - 16ms/step - ia: 0.4408 - loss: 0.7329 - mae: 0.6232 - rmse: 0.8255 - smape: 1.2042 - val_ia: 0.2507 - val_loss: 0.8001 - val_mae: 0.6512 - val_rmse: 0.7234 - val_smape: 1.2411

Epoch 21/64

1915/1915 - 29s - 15ms/step - ia: 0.4425 - loss: 0.7298 - mae: 0.6222 - rmse: 0.8224 - smape: 1.2004 - val_ia: 0.2604 - val_loss: 0.7922 - val_mae: 0.6427 - val_rmse: 0.7172 - val_smape: 1.2148

Epoch 22/64

1915/1915 - 29s - 15ms/step - ia: 0.4435 - loss: 0.7263 - mae: 0.6214 - rmse: 0.8212 - smape: 1.2012 - val_ia: 0.2589 - val_loss: 0.8074 - val_mae: 0.6453 - val_rmse: 0.7202 - val_smape: 1.2129

Epoch 23/64

1915/1915 - 28s - 14ms/step - ia: 0.4443 - loss: 0.7224 - mae: 0.6204 - rmse: 0.8187 - smape: 1.1978 - val_ia: 0.2536 - val_loss: 0.7823 - val_mae: 0.6431 - val_rmse: 0.7156 - val_smape: 1.2397

Epoch 24/64

1915/1915 - 28s - 14ms/step - ia: 0.4484 - loss: 0.7189 - mae: 0.6180 - rmse: 0.8165 - smape: 1.1923 - val_ia: 0.2622 - val_loss: 0.7968 - val_mae: 0.6387 - val_rmse: 0.7150 - val_smape: 1.1982

Epoch 25/64

1915/1915 - 30s - 15ms/step - ia: 0.4513 - loss: 0.7155 - mae: 0.6171 - rmse: 0.8147 - smape: 1.1893 - val_ia: 0.2494 - val_loss: 0.8163 - val_mae: 0.6527 - val_rmse: 0.7263 - val_smape: 1.2482

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:19 2s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 54%|█████▍    | 27/50 [4:43:14<5:57:03, 931.44s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 69s - 72ms/step - ia: 0.3088 - loss: 0.9286 - mae: 0.7117 - rmse: 0.9413 - smape: 1.3871 - val_ia: 0.2574 - val_loss: 0.7998 - val_mae: 0.6683 - val_rmse: 0.7636 - val_smape: 1.2605

Epoch 2/32

958/958 - 23s - 24ms/step - ia: 0.3820 - loss: 0.8353 - mae: 0.6718 - rmse: 0.8949 - smape: 1.2649 - val_ia: 0.2593 - val_loss: 0.7845 - val_mae: 0.6307 - val_rmse: 0.7256 - val_smape: 1.1796

Epoch 3/32

958/958 - 23s - 24ms/step - ia: 0.3932 - loss: 0.8098 - mae: 0.6618 - rmse: 0.8825 - smape: 1.2639 - val_ia: 0.2631 - val_loss: 0.7564 - val_mae: 0.6375 - val_rmse: 0.7361 - val_smape: 1.2189

Epoch 4/32

958/958 - 21s - 22ms/step - ia: 0.4037 - loss: 0.7950 - mae: 0.6547 - rmse: 0.8742 - smape: 1.2539 - val_ia: 0.2619 - val_loss: 0.7868 - val_mae: 0.6569 - val_rmse: 0.7585 - val_smape: 1.2428

Epoch 5/32

958/958 - 22s - 23ms/step - ia: 0.4052 - loss: 0.7898 - mae: 0.6529 - rmse: 0.8707 - smape: 1.2548 - val_ia: 0.2605 - val_loss: 0.7724 - val_mae: 0.6560 - val_rmse: 0.7546 - val_smape: 1.2702

Epoch 6/32

958/958 - 24s - 25ms/step - ia: 0.4074 - loss: 0.7857 - mae: 0.6501 - rmse: 0.8673 - smape: 1.2529 - val_ia: 0.2602 - val_loss: 0.7546 - val_mae: 0.6427 - val_rmse: 0.7383 - val_smape: 1.3020

Epoch 7/32

958/958 - 23s - 24ms/step - ia: 0.4103 - loss: 0.7838 - mae: 0.6484 - rmse: 0.8675 - smape: 1.2488 - val_ia: 0.2678 - val_loss: 0.7779 - val_mae: 0.6425 - val_rmse: 0.7480 - val_smape: 1.1897

Epoch 8/32

958/958 - 23s - 24ms/step - ia: 0.4139 - loss: 0.7775 - mae: 0.6455 - rmse: 0.8626 - smape: 1.2435 - val_ia: 0.2647 - val_loss: 0.7664 - val_mae: 0.6382 - val_rmse: 0.7404 - val_smape: 1.2073

Epoch 9/32

958/958 - 24s - 25ms/step - ia: 0.4164 - loss: 0.7718 - mae: 0.6441 - rmse: 0.8610 - smape: 1.2443 - val_ia: 0.2639 - val_loss: 0.7701 - val_mae: 0.6384 - val_rmse: 0.7388 - val_smape: 1.2442

Epoch 10/32

958/958 - 23s - 24ms/step - ia: 0.4210 - loss: 0.7647 - mae: 0.6402 - rmse: 0.8566 - smape: 1.2403 - val_ia: 0.2602 - val_loss: 0.7420 - val_mae: 0.6234 - val_rmse: 0.7180 - val_smape: 1.2567

Epoch 11/32

958/958 - 23s - 24ms/step - ia: 0.4227 - loss: 0.7592 - mae: 0.6378 - rmse: 0.8538 - smape: 1.2368 - val_ia: 0.2652 - val_loss: 0.7917 - val_mae: 0.6487 - val_rmse: 0.7539 - val_smape: 1.2449

Epoch 12/32

958/958 - 22s - 23ms/step - ia: 0.4249 - loss: 0.7575 - mae: 0.6368 - rmse: 0.8540 - smape: 1.2386 - val_ia: 0.2659 - val_loss: 0.7786 - val_mae: 0.6422 - val_rmse: 0.7463 - val_smape: 1.2319

Epoch 13/32

958/958 - 21s - 21ms/step - ia: 0.4312 - loss: 0.7454 - mae: 0.6326 - rmse: 0.8457 - smape: 1.2284 - val_ia: 0.2650 - val_loss: 0.7750 - val_mae: 0.6456 - val_rmse: 0.7496 - val_smape: 1.2375

Epoch 14/32

958/958 - 20s - 21ms/step - ia: 0.4312 - loss: 0.7442 - mae: 0.6312 - rmse: 0.8453 - smape: 1.2300 - val_ia: 0.2661 - val_loss: 0.7729 - val_mae: 0.6434 - val_rmse: 0.7477 - val_smape: 1.2404

Epoch 15/32

958/958 - 24s - 25ms/step - ia: 0.4318 - loss: 0.7426 - mae: 0.6326 - rmse: 0.8457 - smape: 1.2318 - val_ia: 0.2641 - val_loss: 0.7680 - val_mae: 0.6456 - val_rmse: 0.7465 - val_smape: 1.2781

Epoch 16/32

958/958 - 30s - 32ms/step - ia: 0.4364 - loss: 0.7389 - mae: 0.6286 - rmse: 0.8430 - smape: 1.2220 - val_ia: 0.2671 - val_loss: 0.8338 - val_mae: 0.6691 - val_rmse: 0.7761 - val_smape: 1.2997

Epoch 17/32

958/958 - 31s - 32ms/step - ia: 0.4369 - loss: 0.7340 - mae: 0.6284 - rmse: 0.8405 - smape: 1.2287 - val_ia: 0.2665 - val_loss: 0.7996 - val_mae: 0.6615 - val_rmse: 0.7666 - val_smape: 1.2937

Epoch 18/32

958/958 - 28s - 30ms/step - ia: 0.4383 - loss: 0.7313 - mae: 0.6276 - rmse: 0.8380 - smape: 1.2266 - val_ia: 0.2626 - val_loss: 0.7690 - val_mae: 0.6473 - val_rmse: 0.7483 - val_smape: 1.2955

Epoch 19/32

958/958 - 29s - 30ms/step - ia: 0.4402 - loss: 0.7240 - mae: 0.6244 - rmse: 0.8338 - smape: 1.2211 - val_ia: 0.2662 - val_loss: 0.7832 - val_mae: 0.6498 - val_rmse: 0.7534 - val_smape: 1.2743

Epoch 20/32

958/958 - 22s - 23ms/step - ia: 0.4433 - loss: 0.7211 - mae: 0.6219 - rmse: 0.8335 - smape: 1.2212 - val_ia: 0.2657 - val_loss: 0.7729 - val_mae: 0.6426 - val_rmse: 0.7447 - val_smape: 1.2718

Epoch 21/32

958/958 - 21s - 22ms/step - ia: 0.4457 - loss: 0.7168 - mae: 0.6215 - rmse: 0.8297 - smape: 1.2165 - val_ia: 0.2717 - val_loss: 0.7969 - val_mae: 0.6397 - val_rmse: 0.7487 - val_smape: 1.2331

Epoch 22/32

958/958 - 28s - 29ms/step - ia: 0.4479 - loss: 0.7141 - mae: 0.6199 - rmse: 0.8284 - smape: 1.2154 - val_ia: 0.2633 - val_loss: 0.7909 - val_mae: 0.6452 - val_rmse: 0.7490 - val_smape: 1.2791

Epoch 23/32

958/958 - 26s - 28ms/step - ia: 0.4490 - loss: 0.7071 - mae: 0.6172 - rmse: 0.8243 - smape: 1.2201 - val_ia: 0.2698 - val_loss: 0.8165 - val_mae: 0.6610 - val_rmse: 0.7700 - val_smape: 1.2618

Epoch 24/32

958/958 - 22s - 23ms/step - ia: 0.4492 - loss: 0.7089 - mae: 0.6164 - rmse: 0.8261 - smape: 1.2159 - val_ia: 0.2693 - val_loss: 0.7797 - val_mae: 0.6450 - val_rmse: 0.7510 - val_smape: 1.2646

Epoch 25/32

958/958 - 24s - 25ms/step - ia: 0.4498 - loss: 0.7089 - mae: 0.6178 - rmse: 0.8256 - smape: 1.2129 - val_ia: 0.2660 - val_loss: 0.8010 - val_mae: 0.6643 - val_rmse: 0.7687 - val_smape: 1.2992

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 16:42 7s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 14s 50ms/step

 56%|█████▌    | 28/50 [4:54:19<5:12:06, 851.23s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 102s - 53ms/step - ia: 0.3787 - loss: 0.8317 - mae: 0.6712 - rmse: 0.8785 - smape: 1.2987 - val_ia: 0.2445 - val_loss: 0.7733 - val_mae: 0.6633 - val_rmse: 0.7338 - val_smape: 1.3222

Epoch 2/8

1915/1915 - 54s - 28ms/step - ia: 0.3989 - loss: 0.8045 - mae: 0.6576 - rmse: 0.8646 - smape: 1.2698 - val_ia: 0.2593 - val_loss: 0.7479 - val_mae: 0.6206 - val_rmse: 0.6934 - val_smape: 1.1826

Epoch 3/8

1915/1915 - 54s - 28ms/step - ia: 0.4083 - loss: 0.7888 - mae: 0.6489 - rmse: 0.8556 - smape: 1.2522 - val_ia: 0.2591 - val_loss: 0.7400 - val_mae: 0.6257 - val_rmse: 0.6975 - val_smape: 1.2042

Epoch 4/8

1915/1915 - 57s - 30ms/step - ia: 0.4138 - loss: 0.7785 - mae: 0.6451 - rmse: 0.8513 - smape: 1.2454 - val_ia: 0.2474 - val_loss: 0.7524 - val_mae: 0.6483 - val_rmse: 0.7153 - val_smape: 1.3134

Epoch 5/8

1915/1915 - 59s - 31ms/step - ia: 0.4198 - loss: 0.7694 - mae: 0.6406 - rmse: 0.8437 - smape: 1.2367 - val_ia: 0.2537 - val_loss: 0.7447 - val_mae: 0.6339 - val_rmse: 0.7045 - val_smape: 1.2300

Epoch 6/8

1915/1915 - 54s - 28ms/step - ia: 0.4238 - loss: 0.7623 - mae: 0.6368 - rmse: 0.8418 - smape: 1.2292 - val_ia: 0.2507 - val_loss: 0.7602 - val_mae: 0.6454 - val_rmse: 0.7140 - val_smape: 1.2500

Epoch 7/8

1915/1915 - 56s - 29ms/step - ia: 0.4300 - loss: 0.7521 - mae: 0.6332 - rmse: 0.8355 - smape: 1.2192 - val_ia: 0.2506 - val_loss: 0.7629 - val_mae: 0.6359 - val_rmse: 0.7076 - val_smape: 1.2221

Epoch 8/8

1915/1915 - 48s - 25ms/step - ia: 0.4335 - loss: 0.7394 - mae: 0.6293 - rmse: 0.8286 - smape: 1.2134 - val_ia: 0.2518 - val_loss: 0.7579 - val_mae: 0.6346 - val_rmse: 0.7075 - val_smape: 1.2336

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:25 2s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step

 58%|█████▊    | 29/50 [5:02:31<4:20:15, 743.61s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 69s - 72ms/step - ia: 0.3362 - loss: 0.8670 - mae: 0.6912 - rmse: 0.9120 - smape: 1.3668 - val_ia: 0.2516 - val_loss: 0.7760 - val_mae: 0.6536 - val_rmse: 0.7455 - val_smape: 1.2953

Epoch 2/128

958/958 - 29s - 30ms/step - ia: 0.3647 - loss: 0.8397 - mae: 0.6779 - rmse: 0.8972 - smape: 1.3202 - val_ia: 0.2521 - val_loss: 0.7633 - val_mae: 0.6473 - val_rmse: 0.7397 - val_smape: 1.2866

Epoch 3/128

958/958 - 28s - 29ms/step - ia: 0.3729 - loss: 0.8296 - mae: 0.6721 - rmse: 0.8928 - smape: 1.3064 - val_ia: 0.2573 - val_loss: 0.7545 - val_mae: 0.6409 - val_rmse: 0.7365 - val_smape: 1.2370

Epoch 4/128

958/958 - 26s - 27ms/step - ia: 0.3843 - loss: 0.8176 - mae: 0.6660 - rmse: 0.8862 - smape: 1.2900 - val_ia: 0.2557 - val_loss: 0.7514 - val_mae: 0.6423 - val_rmse: 0.7364 - val_smape: 1.2716

Epoch 5/128

958/958 - 25s - 27ms/step - ia: 0.3913 - loss: 0.8101 - mae: 0.6611 - rmse: 0.8816 - smape: 1.2818 - val_ia: 0.2598 - val_loss: 0.7385 - val_mae: 0.6346 - val_rmse: 0.7271 - val_smape: 1.2596

Epoch 6/128

958/958 - 33s - 35ms/step - ia: 0.3914 - loss: 0.8088 - mae: 0.6602 - rmse: 0.8811 - smape: 1.2837 - val_ia: 0.2616 - val_loss: 0.7535 - val_mae: 0.6402 - val_rmse: 0.7370 - val_smape: 1.2422

Epoch 7/128

958/958 - 32s - 33ms/step - ia: 0.3982 - loss: 0.7991 - mae: 0.6563 - rmse: 0.8758 - smape: 1.2736 - val_ia: 0.2624 - val_loss: 0.7545 - val_mae: 0.6387 - val_rmse: 0.7354 - val_smape: 1.2505

Epoch 8/128

958/958 - 28s - 30ms/step - ia: 0.3983 - loss: 0.7977 - mae: 0.6547 - rmse: 0.8754 - smape: 1.2728 - val_ia: 0.2649 - val_loss: 0.7567 - val_mae: 0.6459 - val_rmse: 0.7416 - val_smape: 1.2798

Epoch 9/128

958/958 - 44s - 46ms/step - ia: 0.4033 - loss: 0.7920 - mae: 0.6527 - rmse: 0.8723 - smape: 1.2669 - val_ia: 0.2687 - val_loss: 0.7488 - val_mae: 0.6312 - val_rmse: 0.7295 - val_smape: 1.2157

Epoch 10/128

958/958 - 22s - 23ms/step - ia: 0.4029 - loss: 0.7912 - mae: 0.6511 - rmse: 0.8721 - smape: 1.2642 - val_ia: 0.2671 - val_loss: 0.7655 - val_mae: 0.6393 - val_rmse: 0.7385 - val_smape: 1.2176

Epoch 11/128

958/958 - 32s - 33ms/step - ia: 0.4081 - loss: 0.7868 - mae: 0.6495 - rmse: 0.8690 - smape: 1.2572 - val_ia: 0.2647 - val_loss: 0.7478 - val_mae: 0.6350 - val_rmse: 0.7299 - val_smape: 1.2546

Epoch 12/128

958/958 - 26s - 27ms/step - ia: 0.4103 - loss: 0.7836 - mae: 0.6481 - rmse: 0.8679 - smape: 1.2536 - val_ia: 0.2711 - val_loss: 0.7572 - val_mae: 0.6415 - val_rmse: 0.7391 - val_smape: 1.2577

Epoch 13/128

958/958 - 22s - 23ms/step - ia: 0.4112 - loss: 0.7824 - mae: 0.6470 - rmse: 0.8663 - smape: 1.2518 - val_ia: 0.2689 - val_loss: 0.7608 - val_mae: 0.6424 - val_rmse: 0.7406 - val_smape: 1.2528

Epoch 14/128

958/958 - 23s - 24ms/step - ia: 0.4118 - loss: 0.7848 - mae: 0.6467 - rmse: 0.8682 - smape: 1.2514 - val_ia: 0.2675 - val_loss: 0.7513 - val_mae: 0.6367 - val_rmse: 0.7330 - val_smape: 1.2501

Epoch 15/128

958/958 - 23s - 24ms/step - ia: 0.4156 - loss: 0.7722 - mae: 0.6434 - rmse: 0.8604 - smape: 1.2447 - val_ia: 0.2704 - val_loss: 0.7608 - val_mae: 0.6360 - val_rmse: 0.7358 - val_smape: 1.2260

Epoch 16/128

958/958 - 50s - 52ms/step - ia: 0.4157 - loss: 0.7736 - mae: 0.6438 - rmse: 0.8612 - smape: 1.2464 - val_ia: 0.2691 - val_loss: 0.7683 - val_mae: 0.6375 - val_rmse: 0.7384 - val_smape: 1.2201

Epoch 17/128

958/958 - 33s - 35ms/step - ia: 0.4187 - loss: 0.7687 - mae: 0.6422 - rmse: 0.8585 - smape: 1.2421 - val_ia: 0.2704 - val_loss: 0.7570 - val_mae: 0.6343 - val_rmse: 0.7327 - val_smape: 1.2326

Epoch 18/128

958/958 - 32s - 34ms/step - ia: 0.4186 - loss: 0.7709 - mae: 0.6422 - rmse: 0.8606 - smape: 1.2407 - val_ia: 0.2684 - val_loss: 0.7556 - val_mae: 0.6341 - val_rmse: 0.7311 - val_smape: 1.2357

Epoch 19/128

958/958 - 33s - 35ms/step - ia: 0.4189 - loss: 0.7698 - mae: 0.6419 - rmse: 0.8600 - smape: 1.2412 - val_ia: 0.2693 - val_loss: 0.7854 - val_mae: 0.6459 - val_rmse: 0.7484 - val_smape: 1.2205

Epoch 20/128

958/958 - 30s - 32ms/step - ia: 0.4217 - loss: 0.7649 - mae: 0.6405 - rmse: 0.8556 - smape: 1.2399 - val_ia: 0.2738 - val_loss: 0.7889 - val_mae: 0.6422 - val_rmse: 0.7467 - val_smape: 1.2031

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 20:01 9s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 18s 70ms/step

 60%|██████    | 30/50 [5:13:44<4:00:48, 722.41s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 140s - 73ms/step - ia: 0.3634 - loss: 0.8704 - mae: 0.6881 - rmse: 0.8995 - smape: 1.3014 - val_ia: 0.2431 - val_loss: 0.7659 - val_mae: 0.6534 - val_rmse: 0.7203 - val_smape: 1.2752

Epoch 2/8

1915/1915 - 58s - 30ms/step - ia: 0.3949 - loss: 0.8098 - mae: 0.6598 - rmse: 0.8668 - smape: 1.2574 - val_ia: 0.2441 - val_loss: 0.8566 - val_mae: 0.6755 - val_rmse: 0.7545 - val_smape: 1.1863

Epoch 3/8

1915/1915 - 72s - 38ms/step - ia: 0.4056 - loss: 0.7916 - mae: 0.6509 - rmse: 0.8584 - smape: 1.2490 - val_ia: 0.2487 - val_loss: 0.7444 - val_mae: 0.6287 - val_rmse: 0.6994 - val_smape: 1.2455

Epoch 4/8

1915/1915 - 78s - 41ms/step - ia: 0.4150 - loss: 0.7772 - mae: 0.6442 - rmse: 0.8473 - smape: 1.2461 - val_ia: 0.2534 - val_loss: 0.7556 - val_mae: 0.6321 - val_rmse: 0.7067 - val_smape: 1.2464

Epoch 5/8

1915/1915 - 71s - 37ms/step - ia: 0.4220 - loss: 0.7621 - mae: 0.6372 - rmse: 0.8405 - smape: 1.2390 - val_ia: 0.2497 - val_loss: 0.7408 - val_mae: 0.6296 - val_rmse: 0.6982 - val_smape: 1.2628

Epoch 6/8

1915/1915 - 62s - 33ms/step - ia: 0.4304 - loss: 0.7461 - mae: 0.6299 - rmse: 0.8319 - smape: 1.2290 - val_ia: 0.2413 - val_loss: 0.7579 - val_mae: 0.6473 - val_rmse: 0.7189 - val_smape: 1.3179

Epoch 7/8

1915/1915 - 80s - 42ms/step - ia: 0.4374 - loss: 0.7338 - mae: 0.6249 - rmse: 0.8253 - smape: 1.2183 - val_ia: 0.2490 - val_loss: 0.7744 - val_mae: 0.6386 - val_rmse: 0.7144 - val_smape: 1.2319

Epoch 8/8

1915/1915 - 81s - 42ms/step - ia: 0.4478 - loss: 0.7148 - mae: 0.6169 - rmse: 0.8144 - smape: 1.2042 - val_ia: 0.2554 - val_loss: 0.8236 - val_mae: 0.6450 - val_rmse: 0.7266 - val_smape: 1.1964

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:08:49 31s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 41s 79ms/step

 62%|██████▏   | 31/50 [5:25:08<3:45:07, 710.94s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 112s - 117ms/step - ia: 0.3695 - loss: 0.8333 - mae: 0.6708 - rmse: 0.8953 - smape: 1.3037 - val_ia: 0.2592 - val_loss: 0.7587 - val_mae: 0.6364 - val_rmse: 0.7333 - val_smape: 1.2005

Epoch 2/128

958/958 - 26s - 27ms/step - ia: 0.3999 - loss: 0.7957 - mae: 0.6545 - rmse: 0.8738 - smape: 1.2534 - val_ia: 0.2584 - val_loss: 0.7768 - val_mae: 0.6600 - val_rmse: 0.7571 - val_smape: 1.3075

Epoch 3/128

958/958 - 22s - 23ms/step - ia: 0.4137 - loss: 0.7785 - mae: 0.6450 - rmse: 0.8649 - smape: 1.2339 - val_ia: 0.2634 - val_loss: 0.7638 - val_mae: 0.6404 - val_rmse: 0.7399 - val_smape: 1.2353

Epoch 4/128

958/958 - 25s - 26ms/step - ia: 0.4196 - loss: 0.7664 - mae: 0.6404 - rmse: 0.8569 - smape: 1.2375 - val_ia: 0.2580 - val_loss: 0.7660 - val_mae: 0.6376 - val_rmse: 0.7310 - val_smape: 1.3033

Epoch 5/128

958/958 - 22s - 23ms/step - ia: 0.4218 - loss: 0.7571 - mae: 0.6360 - rmse: 0.8533 - smape: 1.2456 - val_ia: 0.2610 - val_loss: 0.7793 - val_mae: 0.6488 - val_rmse: 0.7463 - val_smape: 1.3025

Epoch 6/128

958/958 - 22s - 22ms/step - ia: 0.4257 - loss: 0.7452 - mae: 0.6332 - rmse: 0.8461 - smape: 1.2453 - val_ia: 0.2618 - val_loss: 0.7992 - val_mae: 0.6481 - val_rmse: 0.7449 - val_smape: 1.3797

Epoch 7/128

958/958 - 25s - 26ms/step - ia: 0.4305 - loss: 0.7315 - mae: 0.6282 - rmse: 0.8383 - smape: 1.2522 - val_ia: 0.2648 - val_loss: 0.7677 - val_mae: 0.6342 - val_rmse: 0.7339 - val_smape: 1.2795

Epoch 8/128

958/958 - 21s - 22ms/step - ia: 0.4361 - loss: 0.7248 - mae: 0.6259 - rmse: 0.8333 - smape: 1.2326 - val_ia: 0.2675 - val_loss: 0.7962 - val_mae: 0.6481 - val_rmse: 0.7483 - val_smape: 1.2786

Epoch 9/128

958/958 - 18s - 19ms/step - ia: 0.4432 - loss: 0.7106 - mae: 0.6196 - rmse: 0.8260 - smape: 1.2254 - val_ia: 0.2597 - val_loss: 0.7800 - val_mae: 0.6491 - val_rmse: 0.7428 - val_smape: 1.3751

Epoch 10/128

958/958 - 26s - 27ms/step - ia: 0.4383 - loss: 0.7139 - mae: 0.6225 - rmse: 0.8282 - smape: 1.2310 - val_ia: 0.2677 - val_loss: 0.8099 - val_mae: 0.6533 - val_rmse: 0.7540 - val_smape: 1.3155

Epoch 11/128

958/958 - 23s - 24ms/step - ia: 0.4419 - loss: 0.7064 - mae: 0.6187 - rmse: 0.8242 - smape: 1.2332 - val_ia: 0.2639 - val_loss: 0.7587 - val_mae: 0.6405 - val_rmse: 0.7357 - val_smape: 1.3365

Epoch 12/128

958/958 - 17s - 18ms/step - ia: 0.4490 - loss: 0.7008 - mae: 0.6141 - rmse: 0.8193 - smape: 1.2178 - val_ia: 0.2636 - val_loss: 0.8029 - val_mae: 0.6618 - val_rmse: 0.7604 - val_smape: 1.3247

Epoch 13/128

958/958 - 18s - 19ms/step - ia: 0.4507 - loss: 0.6915 - mae: 0.6128 - rmse: 0.8138 - smape: 1.2133 - val_ia: 0.2597 - val_loss: 0.8440 - val_mae: 0.6738 - val_rmse: 0.7791 - val_smape: 1.3151

Epoch 14/128

958/958 - 19s - 19ms/step - ia: 0.4504 - loss: 0.6890 - mae: 0.6116 - rmse: 0.8130 - smape: 1.2148 - val_ia: 0.2609 - val_loss: 0.7819 - val_mae: 0.6415 - val_rmse: 0.7371 - val_smape: 1.3185

Epoch 15/128

958/958 - 18s - 19ms/step - ia: 0.4515 - loss: 0.6898 - mae: 0.6116 - rmse: 0.8133 - smape: 1.2194 - val_ia: 0.2661 - val_loss: 0.7724 - val_mae: 0.6450 - val_rmse: 0.7422 - val_smape: 1.3209

Epoch 16/128

958/958 - 17s - 18ms/step - ia: 0.4499 - loss: 0.6928 - mae: 0.6131 - rmse: 0.8163 - smape: 1.2137 - val_ia: 0.2662 - val_loss: 0.8135 - val_mae: 0.6460 - val_rmse: 0.7482 - val_smape: 1.2708

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:10 968ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

Epoch 1/8

 64%|██████▍   | 32/50 [5:32:22<3:08:20, 627.78s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 9s - 78ms/step - ia: 0.2872 - loss: 0.8744 - mae: 0.6863 - rmse: 0.9318 - smape: 1.4294 - val_ia: 0.3425 - val_loss: 0.7702 - val_mae: 0.6488 - val_rmse: 0.8113 - val_smape: 1.2767

Epoch 2/8

120/120 - 4s - 36ms/step - ia: 0.3960 - loss: 0.8050 - mae: 0.6582 - rmse: 0.8952 - smape: 1.2644 - val_ia: 0.3478 - val_loss: 0.7588 - val_mae: 0.6413 - val_rmse: 0.8057 - val_smape: 1.2566

Epoch 3/8

120/120 - 2s - 17ms/step - ia: 0.4075 - loss: 0.7919 - mae: 0.6506 - rmse: 0.8873 - smape: 1.2487 - val_ia: 0.3583 - val_loss: 0.7532 - val_mae: 0.6330 - val_rmse: 0.8012 - val_smape: 1.2217

Epoch 4/8

120/120 - 2s - 19ms/step - ia: 0.4161 - loss: 0.7818 - mae: 0.6446 - rmse: 0.8814 - smape: 1.2353 - val_ia: 0.3556 - val_loss: 0.7540 - val_mae: 0.6386 - val_rmse: 0.8052 - val_smape: 1.2418

Epoch 5/8

120/120 - 2s - 19ms/step - ia: 0.4246 - loss: 0.7734 - mae: 0.6394 - rmse: 0.8773 - smape: 1.2255 - val_ia: 0.3656 - val_loss: 0.7551 - val_mae: 0.6331 - val_rmse: 0.8040 - val_smape: 1.2190

Epoch 6/8

120/120 - 2s - 19ms/step - ia: 0.4297 - loss: 0.7645 - mae: 0.6343 - rmse: 0.8718 - smape: 1.2159 - val_ia: 0.3565 - val_loss: 0.7765 - val_mae: 0.6534 - val_rmse: 0.8216 - val_smape: 1.2680

Epoch 7/8

120/120 - 2s - 19ms/step - ia: 0.4365 - loss: 0.7570 - mae: 0.6313 - rmse: 0.8680 - smape: 1.2091 - val_ia: 0.3683 - val_loss: 0.7705 - val_mae: 0.6417 - val_rmse: 0.8148 - val_smape: 1.2181

Epoch 8/8

120/120 - 3s - 22ms/step - ia: 0.4441 - loss: 0.7497 - mae: 0.6272 - rmse: 0.8638 - smape: 1.1998 - val_ia: 0.3601 - val_loss: 0.7698 - val_mae: 0.6456 - val_rmse: 0.8144 - val_smape: 1.2390

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:31 2s/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step

 66%|██████▌   | 33/50 [5:32:56<2:07:22, 449.59s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

479/479 - 24s - 49ms/step - ia: 0.1645 - loss: 1.0113 - mae: 0.7497 - rmse: 0.9919 - smape: 1.6735 - val_ia: 0.2511 - val_loss: 0.8574 - val_mae: 0.6904 - val_rmse: 0.8069 - val_smape: 1.5220

Epoch 2/32

479/479 - 8s - 16ms/step - ia: 0.3049 - loss: 0.8687 - mae: 0.6927 - rmse: 0.9213 - smape: 1.4187 - val_ia: 0.2682 - val_loss: 0.7964 - val_mae: 0.6596 - val_rmse: 0.7818 - val_smape: 1.3306

Epoch 3/32

479/479 - 7s - 15ms/step - ia: 0.3580 - loss: 0.8431 - mae: 0.6800 - rmse: 0.9087 - smape: 1.3311 - val_ia: 0.2711 - val_loss: 0.7892 - val_mae: 0.6540 - val_rmse: 0.7775 - val_smape: 1.2999

Epoch 4/32

479/479 - 6s - 13ms/step - ia: 0.3678 - loss: 0.8369 - mae: 0.6753 - rmse: 0.9059 - smape: 1.3107 - val_ia: 0.2725 - val_loss: 0.7813 - val_mae: 0.6502 - val_rmse: 0.7743 - val_smape: 1.2808

Epoch 5/32

479/479 - 7s - 14ms/step - ia: 0.3714 - loss: 0.8339 - mae: 0.6741 - rmse: 0.9045 - smape: 1.3078 - val_ia: 0.2726 - val_loss: 0.7783 - val_mae: 0.6489 - val_rmse: 0.7730 - val_smape: 1.2787

Epoch 6/32

479/479 - 7s - 14ms/step - ia: 0.3769 - loss: 0.8297 - mae: 0.6722 - rmse: 0.9016 - smape: 1.3009 - val_ia: 0.2716 - val_loss: 0.7752 - val_mae: 0.6486 - val_rmse: 0.7718 - val_smape: 1.2833

Epoch 7/32

479/479 - 7s - 14ms/step - ia: 0.3742 - loss: 0.8261 - mae: 0.6707 - rmse: 0.8990 - smape: 1.3033 - val_ia: 0.2723 - val_loss: 0.7705 - val_mae: 0.6462 - val_rmse: 0.7695 - val_smape: 1.2755

Epoch 8/32

479/479 - 6s - 13ms/step - ia: 0.3775 - loss: 0.8246 - mae: 0.6688 - rmse: 0.8991 - smape: 1.2967 - val_ia: 0.2733 - val_loss: 0.7692 - val_mae: 0.6456 - val_rmse: 0.7695 - val_smape: 1.2718

Epoch 9/32

479/479 - 7s - 15ms/step - ia: 0.3781 - loss: 0.8229 - mae: 0.6691 - rmse: 0.8977 - smape: 1.2979 - val_ia: 0.2733 - val_loss: 0.7677 - val_mae: 0.6453 - val_rmse: 0.7690 - val_smape: 1.2740

Epoch 10/32

479/479 - 7s - 15ms/step - ia: 0.3800 - loss: 0.8214 - mae: 0.6677 - rmse: 0.8976 - smape: 1.2939 - val_ia: 0.2733 - val_loss: 0.7650 - val_mae: 0.6445 - val_rmse: 0.7678 - val_smape: 1.2736

Epoch 11/32

479/479 - 6s - 13ms/step - ia: 0.3823 - loss: 0.8194 - mae: 0.6665 - rmse: 0.8956 - smape: 1.2915 - val_ia: 0.2731 - val_loss: 0.7602 - val_mae: 0.6424 - val_rmse: 0.7652 - val_smape: 1.2690

Epoch 12/32

479/479 - 7s - 15ms/step - ia: 0.3808 - loss: 0.8165 - mae: 0.6653 - rmse: 0.8940 - smape: 1.2929 - val_ia: 0.2744 - val_loss: 0.7586 - val_mae: 0.6415 - val_rmse: 0.7649 - val_smape: 1.2633

Epoch 13/32

479/479 - 7s - 15ms/step - ia: 0.3825 - loss: 0.8165 - mae: 0.6654 - rmse: 0.8945 - smape: 1.2908 - val_ia: 0.2746 - val_loss: 0.7597 - val_mae: 0.6429 - val_rmse: 0.7662 - val_smape: 1.2711

Epoch 14/32

479/479 - 8s - 16ms/step - ia: 0.3830 - loss: 0.8158 - mae: 0.6642 - rmse: 0.8934 - smape: 1.2893 - val_ia: 0.2750 - val_loss: 0.7542 - val_mae: 0.6397 - val_rmse: 0.7629 - val_smape: 1.2568

Epoch 15/32

479/479 - 7s - 15ms/step - ia: 0.3851 - loss: 0.8134 - mae: 0.6641 - rmse: 0.8915 - smape: 1.2885 - val_ia: 0.2752 - val_loss: 0.7543 - val_mae: 0.6402 - val_rmse: 0.7634 - val_smape: 1.2639

Epoch 16/32

479/479 - 7s - 15ms/step - ia: 0.3871 - loss: 0.8106 - mae: 0.6617 - rmse: 0.8914 - smape: 1.2825 - val_ia: 0.2745 - val_loss: 0.7536 - val_mae: 0.6408 - val_rmse: 0.7633 - val_smape: 1.2702

Epoch 17/32

479/479 - 7s - 14ms/step - ia: 0.3867 - loss: 0.8097 - mae: 0.6615 - rmse: 0.8898 - smape: 1.2831 - val_ia: 0.2759 - val_loss: 0.7532 - val_mae: 0.6408 - val_rmse: 0.7640 - val_smape: 1.2688

Epoch 18/32

479/479 - 6s - 13ms/step - ia: 0.3871 - loss: 0.8097 - mae: 0.6617 - rmse: 0.8900 - smape: 1.2835 - val_ia: 0.2761 - val_loss: 0.7530 - val_mae: 0.6408 - val_rmse: 0.7640 - val_smape: 1.2699

Epoch 19/32

479/479 - 6s - 13ms/step - ia: 0.3880 - loss: 0.8082 - mae: 0.6604 - rmse: 0.8893 - smape: 1.2793 - val_ia: 0.2767 - val_loss: 0.7484 - val_mae: 0.6383 - val_rmse: 0.7614 - val_smape: 1.2610

Epoch 20/32

479/479 - 7s - 14ms/step - ia: 0.3882 - loss: 0.8069 - mae: 0.6607 - rmse: 0.8883 - smape: 1.2828 - val_ia: 0.2782 - val_loss: 0.7490 - val_mae: 0.6385 - val_rmse: 0.7625 - val_smape: 1.2588

Epoch 21/32

479/479 - 8s - 16ms/step - ia: 0.3909 - loss: 0.8049 - mae: 0.6592 - rmse: 0.8883 - smape: 1.2795 - val_ia: 0.2785 - val_loss: 0.7464 - val_mae: 0.6371 - val_rmse: 0.7610 - val_smape: 1.2556

Epoch 22/32

479/479 - 7s - 14ms/step - ia: 0.3927 - loss: 0.8045 - mae: 0.6587 - rmse: 0.8871 - smape: 1.2764 - val_ia: 0.2785 - val_loss: 0.7476 - val_mae: 0.6385 - val_rmse: 0.7624 - val_smape: 1.2613

Epoch 23/32

479/479 - 7s - 14ms/step - ia: 0.3929 - loss: 0.8034 - mae: 0.6582 - rmse: 0.8865 - smape: 1.2747 - val_ia: 0.2792 - val_loss: 0.7470 - val_mae: 0.6388 - val_rmse: 0.7628 - val_smape: 1.2637

Epoch 24/32

479/479 - 7s - 15ms/step - ia: 0.3946 - loss: 0.8022 - mae: 0.6579 - rmse: 0.8862 - smape: 1.2761 - val_ia: 0.2799 - val_loss: 0.7462 - val_mae: 0.6384 - val_rmse: 0.7627 - val_smape: 1.2624

Epoch 25/32

479/479 - 7s - 15ms/step - ia: 0.3939 - loss: 0.8018 - mae: 0.6577 - rmse: 0.8867 - smape: 1.2746 - val_ia: 0.2798 - val_loss: 0.7442 - val_mae: 0.6374 - val_rmse: 0.7615 - val_smape: 1.2593

Epoch 26/32

479/479 - 7s - 14ms/step - ia: 0.3977 - loss: 0.8002 - mae: 0.6566 - rmse: 0.8854 - smape: 1.2715 - val_ia: 0.2793 - val_loss: 0.7422 - val_mae: 0.6367 - val_rmse: 0.7603 - val_smape: 1.2607

Epoch 27/32

479/479 - 7s - 16ms/step - ia: 0.3953 - loss: 0.7982 - mae: 0.6560 - rmse: 0.8841 - smape: 1.2746 - val_ia: 0.2813 - val_loss: 0.7445 - val_mae: 0.6369 - val_rmse: 0.7620 - val_smape: 1.2566

Epoch 28/32

479/479 - 10s - 21ms/step - ia: 0.3970 - loss: 0.7976 - mae: 0.6551 - rmse: 0.8841 - smape: 1.2725 - val_ia: 0.2822 - val_loss: 0.7441 - val_mae: 0.6367 - val_rmse: 0.7621 - val_smape: 1.2549

Epoch 29/32

479/479 - 7s - 15ms/step - ia: 0.3986 - loss: 0.7975 - mae: 0.6553 - rmse: 0.8840 - smape: 1.2697 - val_ia: 0.2827 - val_loss: 0.7430 - val_mae: 0.6362 - val_rmse: 0.7618 - val_smape: 1.2513

Epoch 30/32

479/479 - 7s - 15ms/step - ia: 0.4010 - loss: 0.7959 - mae: 0.6540 - rmse: 0.8831 - smape: 1.2638 - val_ia: 0.2822 - val_loss: 0.7425 - val_mae: 0.6374 - val_rmse: 0.7621 - val_smape: 1.2641

Epoch 31/32

479/479 - 8s - 16ms/step - ia: 0.4004 - loss: 0.7947 - mae: 0.6537 - rmse: 0.8819 - smape: 1.2684 - val_ia: 0.2820 - val_loss: 0.7394 - val_mae: 0.6346 - val_rmse: 0.7593 - val_smape: 1.2502

Epoch 32/32

479/479 - 8s - 16ms/step - ia: 0.4012 - loss: 0.7933 - mae: 0.6534 - rmse: 0.8815 - smape: 1.2673 - val_ia: 0.2834 - val_loss: 0.7419 - val_mae: 0.6357 - val_rmse: 0.7613 - val_smape: 1.2524

Restoring model weights from the end of the best epoch: 31.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:46 788ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 68%|██████▊   | 34/50 [5:37:03<1:43:41, 388.87s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

958/958 - 46s - 48ms/step - ia: 0.2557 - loss: 1.2331 - mae: 0.8553 - rmse: 1.0919 - smape: 1.5024 - val_ia: 0.2326 - val_loss: 0.9625 - val_mae: 0.7345 - val_rmse: 0.8188 - val_smape: 1.9565

Epoch 2/64

958/958 - 15s - 16ms/step - ia: 0.2460 - loss: 1.1193 - mae: 0.7985 - rmse: 1.0382 - smape: 1.5114 - val_ia: 0.2337 - val_loss: 0.9570 - val_mae: 0.7286 - val_rmse: 0.8130 - val_smape: 1.8661

Epoch 3/64

958/958 - 21s - 22ms/step - ia: 0.2285 - loss: 1.0788 - mae: 0.7808 - rmse: 1.0178 - smape: 1.5395 - val_ia: 0.2332 - val_loss: 0.9524 - val_mae: 0.7317 - val_rmse: 0.8156 - val_smape: 1.9111

Epoch 4/64

958/958 - 22s - 23ms/step - ia: 0.2140 - loss: 1.0516 - mae: 0.7712 - rmse: 1.0049 - smape: 1.5679 - val_ia: 0.2344 - val_loss: 0.9392 - val_mae: 0.7242 - val_rmse: 0.8079 - val_smape: 1.8334

Epoch 5/64

958/958 - 22s - 23ms/step - ia: 0.2165 - loss: 1.0098 - mae: 0.7538 - rmse: 0.9835 - smape: 1.5672 - val_ia: 0.2368 - val_loss: 0.9117 - val_mae: 0.7101 - val_rmse: 0.7935 - val_smape: 1.7020

Epoch 6/64

958/958 - 25s - 26ms/step - ia: 0.2371 - loss: 0.9722 - mae: 0.7361 - rmse: 0.9647 - smape: 1.5277 - val_ia: 0.2396 - val_loss: 0.8712 - val_mae: 0.7027 - val_rmse: 0.7859 - val_smape: 1.5911

Epoch 7/64

958/958 - 24s - 25ms/step - ia: 0.2775 - loss: 0.9293 - mae: 0.7189 - rmse: 0.9443 - smape: 1.4559 - val_ia: 0.2479 - val_loss: 0.8250 - val_mae: 0.6741 - val_rmse: 0.7608 - val_smape: 1.4003

Epoch 8/64

958/958 - 25s - 26ms/step - ia: 0.3216 - loss: 0.8978 - mae: 0.7042 - rmse: 0.9293 - smape: 1.3763 - val_ia: 0.2527 - val_loss: 0.8076 - val_mae: 0.6635 - val_rmse: 0.7533 - val_smape: 1.3233

Epoch 9/64

958/958 - 41s - 43ms/step - ia: 0.3429 - loss: 0.8867 - mae: 0.6982 - rmse: 0.9225 - smape: 1.3413 - val_ia: 0.2541 - val_loss: 0.8020 - val_mae: 0.6613 - val_rmse: 0.7522 - val_smape: 1.3018

Epoch 10/64

958/958 - 19s - 20ms/step - ia: 0.3498 - loss: 0.8765 - mae: 0.6944 - rmse: 0.9175 - smape: 1.3305 - val_ia: 0.2549 - val_loss: 0.7977 - val_mae: 0.6587 - val_rmse: 0.7500 - val_smape: 1.2876

Epoch 11/64

958/958 - 20s - 21ms/step - ia: 0.3506 - loss: 0.8750 - mae: 0.6931 - rmse: 0.9155 - smape: 1.3233 - val_ia: 0.2555 - val_loss: 0.7943 - val_mae: 0.6559 - val_rmse: 0.7474 - val_smape: 1.2750

Epoch 12/64

958/958 - 25s - 26ms/step - ia: 0.3550 - loss: 0.8715 - mae: 0.6908 - rmse: 0.9145 - smape: 1.3168 - val_ia: 0.2555 - val_loss: 0.7936 - val_mae: 0.6584 - val_rmse: 0.7501 - val_smape: 1.2824

Epoch 13/64

958/958 - 24s - 25ms/step - ia: 0.3554 - loss: 0.8688 - mae: 0.6894 - rmse: 0.9132 - smape: 1.3127 - val_ia: 0.2555 - val_loss: 0.7916 - val_mae: 0.6560 - val_rmse: 0.7473 - val_smape: 1.2776

Epoch 14/64

958/958 - 21s - 22ms/step - ia: 0.3570 - loss: 0.8623 - mae: 0.6856 - rmse: 0.9107 - smape: 1.3100 - val_ia: 0.2557 - val_loss: 0.7899 - val_mae: 0.6578 - val_rmse: 0.7494 - val_smape: 1.2797

Epoch 15/64

958/958 - 17s - 18ms/step - ia: 0.3583 - loss: 0.8588 - mae: 0.6853 - rmse: 0.9087 - smape: 1.3074 - val_ia: 0.2559 - val_loss: 0.7882 - val_mae: 0.6565 - val_rmse: 0.7482 - val_smape: 1.2767

Epoch 16/64

958/958 - 17s - 18ms/step - ia: 0.3583 - loss: 0.8585 - mae: 0.6855 - rmse: 0.9086 - smape: 1.3067 - val_ia: 0.2561 - val_loss: 0.7863 - val_mae: 0.6556 - val_rmse: 0.7471 - val_smape: 1.2750

Epoch 17/64

958/958 - 18s - 18ms/step - ia: 0.3631 - loss: 0.8542 - mae: 0.6825 - rmse: 0.9070 - smape: 1.3018 - val_ia: 0.2562 - val_loss: 0.7844 - val_mae: 0.6543 - val_rmse: 0.7458 - val_smape: 1.2720

Epoch 18/64

958/958 - 19s - 20ms/step - ia: 0.3625 - loss: 0.8532 - mae: 0.6826 - rmse: 0.9062 - smape: 1.3037 - val_ia: 0.2566 - val_loss: 0.7819 - val_mae: 0.6503 - val_rmse: 0.7420 - val_smape: 1.2583

Epoch 19/64

958/958 - 19s - 20ms/step - ia: 0.3669 - loss: 0.8482 - mae: 0.6809 - rmse: 0.9017 - smape: 1.2968 - val_ia: 0.2563 - val_loss: 0.7822 - val_mae: 0.6544 - val_rmse: 0.7462 - val_smape: 1.2708

Epoch 20/64

958/958 - 22s - 23ms/step - ia: 0.3647 - loss: 0.8502 - mae: 0.6809 - rmse: 0.9046 - smape: 1.2972 - val_ia: 0.2563 - val_loss: 0.7808 - val_mae: 0.6525 - val_rmse: 0.7440 - val_smape: 1.2695

Epoch 21/64

958/958 - 23s - 24ms/step - ia: 0.3643 - loss: 0.8481 - mae: 0.6800 - rmse: 0.9029 - smape: 1.2979 - val_ia: 0.2569 - val_loss: 0.7773 - val_mae: 0.6467 - val_rmse: 0.7385 - val_smape: 1.2483

Epoch 22/64

958/958 - 24s - 25ms/step - ia: 0.3676 - loss: 0.8459 - mae: 0.6780 - rmse: 0.9002 - smape: 1.2922 - val_ia: 0.2567 - val_loss: 0.7782 - val_mae: 0.6520 - val_rmse: 0.7441 - val_smape: 1.2648

Epoch 23/64

958/958 - 25s - 26ms/step - ia: 0.3680 - loss: 0.8439 - mae: 0.6771 - rmse: 0.8996 - smape: 1.2898 - val_ia: 0.2564 - val_loss: 0.7785 - val_mae: 0.6553 - val_rmse: 0.7474 - val_smape: 1.2757

Epoch 24/64

958/958 - 20s - 21ms/step - ia: 0.3681 - loss: 0.8439 - mae: 0.6782 - rmse: 0.9006 - smape: 1.2945 - val_ia: 0.2568 - val_loss: 0.7752 - val_mae: 0.6502 - val_rmse: 0.7422 - val_smape: 1.2611

Epoch 25/64

958/958 - 24s - 25ms/step - ia: 0.3717 - loss: 0.8437 - mae: 0.6772 - rmse: 0.8993 - smape: 1.2891 - val_ia: 0.2565 - val_loss: 0.7736 - val_mae: 0.6451 - val_rmse: 0.7364 - val_smape: 1.2517

Epoch 26/64

958/958 - 24s - 25ms/step - ia: 0.3672 - loss: 0.8423 - mae: 0.6769 - rmse: 0.8990 - smape: 1.2952 - val_ia: 0.2566 - val_loss: 0.7751 - val_mae: 0.6532 - val_rmse: 0.7454 - val_smape: 1.2720

Epoch 27/64

958/958 - 23s - 24ms/step - ia: 0.3711 - loss: 0.8389 - mae: 0.6761 - rmse: 0.8972 - smape: 1.2890 - val_ia: 0.2569 - val_loss: 0.7719 - val_mae: 0.6481 - val_rmse: 0.7403 - val_smape: 1.2576

Epoch 28/64

958/958 - 24s - 25ms/step - ia: 0.3705 - loss: 0.8415 - mae: 0.6758 - rmse: 0.8998 - smape: 1.2912 - val_ia: 0.2567 - val_loss: 0.7712 - val_mae: 0.6468 - val_rmse: 0.7385 - val_smape: 1.2581

Epoch 29/64

958/958 - 23s - 24ms/step - ia: 0.3701 - loss: 0.8382 - mae: 0.6753 - rmse: 0.8975 - smape: 1.2937 - val_ia: 0.2568 - val_loss: 0.7709 - val_mae: 0.6485 - val_rmse: 0.7407 - val_smape: 1.2619

Epoch 30/64

958/958 - 24s - 25ms/step - ia: 0.3726 - loss: 0.8363 - mae: 0.6752 - rmse: 0.8958 - smape: 1.2969 - val_ia: 0.2570 - val_loss: 0.7701 - val_mae: 0.6474 - val_rmse: 0.7400 - val_smape: 1.2556

Epoch 31/64

958/958 - 25s - 26ms/step - ia: 0.3731 - loss: 0.8357 - mae: 0.6746 - rmse: 0.8957 - smape: 1.2904 - val_ia: 0.2569 - val_loss: 0.7697 - val_mae: 0.6477 - val_rmse: 0.7402 - val_smape: 1.2587

Epoch 32/64

958/958 - 39s - 40ms/step - ia: 0.3739 - loss: 0.8363 - mae: 0.6742 - rmse: 0.8957 - smape: 1.2907 - val_ia: 0.2565 - val_loss: 0.7700 - val_mae: 0.6491 - val_rmse: 0.7412 - val_smape: 1.2683

Epoch 33/64

958/958 - 24s - 25ms/step - ia: 0.3719 - loss: 0.8399 - mae: 0.6752 - rmse: 0.8980 - smape: 1.2920 - val_ia: 0.2561 - val_loss: 0.7706 - val_mae: 0.6510 - val_rmse: 0.7427 - val_smape: 1.2792

Epoch 34/64

958/958 - 25s - 26ms/step - ia: 0.3706 - loss: 0.8329 - mae: 0.6736 - rmse: 0.8951 - smape: 1.2974 - val_ia: 0.2568 - val_loss: 0.7674 - val_mae: 0.6450 - val_rmse: 0.7375 - val_smape: 1.2529

Epoch 35/64

958/958 - 23s - 24ms/step - ia: 0.3720 - loss: 0.8354 - mae: 0.6748 - rmse: 0.8962 - smape: 1.2951 - val_ia: 0.2568 - val_loss: 0.7671 - val_mae: 0.6461 - val_rmse: 0.7387 - val_smape: 1.2580

Epoch 36/64

958/958 - 23s - 24ms/step - ia: 0.3737 - loss: 0.8334 - mae: 0.6730 - rmse: 0.8953 - smape: 1.2921 - val_ia: 0.2566 - val_loss: 0.7660 - val_mae: 0.6436 - val_rmse: 0.7359 - val_smape: 1.2523

Epoch 37/64

958/958 - 23s - 24ms/step - ia: 0.3733 - loss: 0.8330 - mae: 0.6725 - rmse: 0.8942 - smape: 1.2913 - val_ia: 0.2567 - val_loss: 0.7659 - val_mae: 0.6454 - val_rmse: 0.7378 - val_smape: 1.2594

Epoch 38/64

958/958 - 22s - 23ms/step - ia: 0.3749 - loss: 0.8305 - mae: 0.6713 - rmse: 0.8938 - smape: 1.2884 - val_ia: 0.2567 - val_loss: 0.7646 - val_mae: 0.6428 - val_rmse: 0.7352 - val_smape: 1.2528

Epoch 39/64

958/958 - 24s - 25ms/step - ia: 0.3753 - loss: 0.8288 - mae: 0.6707 - rmse: 0.8934 - smape: 1.2909 - val_ia: 0.2567 - val_loss: 0.7674 - val_mae: 0.6498 - val_rmse: 0.7428 - val_smape: 1.2700

Epoch 40/64

958/958 - 20s - 21ms/step - ia: 0.3773 - loss: 0.8270 - mae: 0.6719 - rmse: 0.8911 - smape: 1.2904 - val_ia: 0.2565 - val_loss: 0.7638 - val_mae: 0.6422 - val_rmse: 0.7344 - val_smape: 1.2546

Epoch 41/64

958/958 - 25s - 26ms/step - ia: 0.3743 - loss: 0.8299 - mae: 0.6718 - rmse: 0.8939 - smape: 1.2935 - val_ia: 0.2569 - val_loss: 0.7636 - val_mae: 0.6442 - val_rmse: 0.7371 - val_smape: 1.2569

Epoch 42/64

958/958 - 24s - 25ms/step - ia: 0.3789 - loss: 0.8279 - mae: 0.6698 - rmse: 0.8930 - smape: 1.2865 - val_ia: 0.2567 - val_loss: 0.7631 - val_mae: 0.6438 - val_rmse: 0.7363 - val_smape: 1.2592

Epoch 43/64

958/958 - 19s - 19ms/step - ia: 0.3778 - loss: 0.8274 - mae: 0.6700 - rmse: 0.8917 - smape: 1.2878 - val_ia: 0.2567 - val_loss: 0.7638 - val_mae: 0.6454 - val_rmse: 0.7381 - val_smape: 1.2630

Epoch 44/64

958/958 - 21s - 22ms/step - ia: 0.3771 - loss: 0.8288 - mae: 0.6704 - rmse: 0.8939 - smape: 1.2888 - val_ia: 0.2565 - val_loss: 0.7638 - val_mae: 0.6454 - val_rmse: 0.7378 - val_smape: 1.2656

Epoch 45/64

958/958 - 23s - 24ms/step - ia: 0.3771 - loss: 0.8249 - mae: 0.6699 - rmse: 0.8906 - smape: 1.2890 - val_ia: 0.2567 - val_loss: 0.7621 - val_mae: 0.6419 - val_rmse: 0.7347 - val_smape: 1.2523

Epoch 46/64

958/958 - 22s - 23ms/step - ia: 0.3766 - loss: 0.8282 - mae: 0.6708 - rmse: 0.8915 - smape: 1.2909 - val_ia: 0.2565 - val_loss: 0.7646 - val_mae: 0.6483 - val_rmse: 0.7411 - val_smape: 1.2713

Epoch 47/64

958/958 - 24s - 25ms/step - ia: 0.3777 - loss: 0.8273 - mae: 0.6706 - rmse: 0.8929 - smape: 1.2908 - val_ia: 0.2567 - val_loss: 0.7620 - val_mae: 0.6434 - val_rmse: 0.7363 - val_smape: 1.2588

Epoch 48/64

958/958 - 18s - 18ms/step - ia: 0.3783 - loss: 0.8232 - mae: 0.6694 - rmse: 0.8892 - smape: 1.2909 - val_ia: 0.2567 - val_loss: 0.7625 - val_mae: 0.6443 - val_rmse: 0.7374 - val_smape: 1.2597

Epoch 49/64

958/958 - 16s - 17ms/step - ia: 0.3781 - loss: 0.8258 - mae: 0.6692 - rmse: 0.8909 - smape: 1.2885 - val_ia: 0.2565 - val_loss: 0.7611 - val_mae: 0.6413 - val_rmse: 0.7340 - val_smape: 1.2554

Epoch 50/64

958/958 - 22s - 22ms/step - ia: 0.3779 - loss: 0.8239 - mae: 0.6689 - rmse: 0.8901 - smape: 1.2914 - val_ia: 0.2568 - val_loss: 0.7614 - val_mae: 0.6428 - val_rmse: 0.7362 - val_smape: 1.2547

Epoch 51/64

958/958 - 43s - 45ms/step - ia: 0.3796 - loss: 0.8263 - mae: 0.6696 - rmse: 0.8903 - smape: 1.2865 - val_ia: 0.2563 - val_loss: 0.7605 - val_mae: 0.6407 - val_rmse: 0.7328 - val_smape: 1.2596

Epoch 52/64

958/958 - 25s - 26ms/step - ia: 0.3795 - loss: 0.8231 - mae: 0.6684 - rmse: 0.8890 - smape: 1.2886 - val_ia: 0.2567 - val_loss: 0.7603 - val_mae: 0.6422 - val_rmse: 0.7352 - val_smape: 1.2579

Epoch 53/64

958/958 - 23s - 24ms/step - ia: 0.3822 - loss: 0.8233 - mae: 0.6685 - rmse: 0.8904 - smape: 1.2874 - val_ia: 0.2566 - val_loss: 0.7600 - val_mae: 0.6426 - val_rmse: 0.7353 - val_smape: 1.2614

Epoch 54/64

958/958 - 24s - 25ms/step - ia: 0.3781 - loss: 0.8251 - mae: 0.6684 - rmse: 0.8914 - smape: 1.2884 - val_ia: 0.2567 - val_loss: 0.7597 - val_mae: 0.6418 - val_rmse: 0.7347 - val_smape: 1.2564

Epoch 55/64

958/958 - 24s - 25ms/step - ia: 0.3806 - loss: 0.8252 - mae: 0.6686 - rmse: 0.8907 - smape: 1.2861 - val_ia: 0.2566 - val_loss: 0.7607 - val_mae: 0.6438 - val_rmse: 0.7369 - val_smape: 1.2627

Epoch 56/64

958/958 - 19s - 20ms/step - ia: 0.3798 - loss: 0.8203 - mae: 0.6680 - rmse: 0.8889 - smape: 1.2882 - val_ia: 0.2569 - val_loss: 0.7589 - val_mae: 0.6397 - val_rmse: 0.7332 - val_smape: 1.2470

Epoch 57/64

958/958 - 19s - 20ms/step - ia: 0.3827 - loss: 0.8214 - mae: 0.6666 - rmse: 0.8888 - smape: 1.2814 - val_ia: 0.2568 - val_loss: 0.7590 - val_mae: 0.6410 - val_rmse: 0.7342 - val_smape: 1.2542

Epoch 58/64

958/958 - 23s - 24ms/step - ia: 0.3814 - loss: 0.8225 - mae: 0.6673 - rmse: 0.8892 - smape: 1.2861 - val_ia: 0.2567 - val_loss: 0.7600 - val_mae: 0.6433 - val_rmse: 0.7365 - val_smape: 1.2614

Epoch 59/64

958/958 - 42s - 44ms/step - ia: 0.3797 - loss: 0.8212 - mae: 0.6674 - rmse: 0.8888 - smape: 1.2875 - val_ia: 0.2570 - val_loss: 0.7598 - val_mae: 0.6418 - val_rmse: 0.7358 - val_smape: 1.2513

Epoch 60/64

958/958 - 23s - 24ms/step - ia: 0.3836 - loss: 0.8223 - mae: 0.6671 - rmse: 0.8887 - smape: 1.2815 - val_ia: 0.2565 - val_loss: 0.7612 - val_mae: 0.6464 - val_rmse: 0.7394 - val_smape: 1.2731

Epoch 61/64

958/958 - 24s - 25ms/step - ia: 0.3846 - loss: 0.8172 - mae: 0.6661 - rmse: 0.8858 - smape: 1.2848 - val_ia: 0.2568 - val_loss: 0.7578 - val_mae: 0.6389 - val_rmse: 0.7324 - val_smape: 1.2480

Epoch 62/64

958/958 - 18s - 19ms/step - ia: 0.3832 - loss: 0.8224 - mae: 0.6663 - rmse: 0.8883 - smape: 1.2812 - val_ia: 0.2568 - val_loss: 0.7596 - val_mae: 0.6438 - val_rmse: 0.7372 - val_smape: 1.2634

Epoch 63/64

958/958 - 24s - 25ms/step - ia: 0.3813 - loss: 0.8204 - mae: 0.6673 - rmse: 0.8877 - smape: 1.2869 - val_ia: 0.2571 - val_loss: 0.7595 - val_mae: 0.6428 - val_rmse: 0.7368 - val_smape: 1.2558

Epoch 64/64

958/958 - 23s - 24ms/step - ia: 0.3839 - loss: 0.8210 - mae: 0.6666 - rmse: 0.8874 - smape: 1.2821 - val_ia: 0.2567 - val_loss: 0.7596 - val_mae: 0.6441 - val_rmse: 0.7374 - val_smape: 1.2664

Restoring model weights from the end of the best epoch: 61.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:34 2s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 70%|███████   | 35/50 [6:02:18<3:01:40, 726.72s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 79s - 41ms/step - ia: 0.3803 - loss: 0.8253 - mae: 0.6696 - rmse: 0.8767 - smape: 1.2942 - val_ia: 0.2466 - val_loss: 0.7480 - val_mae: 0.6401 - val_rmse: 0.7082 - val_smape: 1.2739

Epoch 2/128

1915/1915 - 42s - 22ms/step - ia: 0.3969 - loss: 0.8033 - mae: 0.6567 - rmse: 0.8649 - smape: 1.2649 - val_ia: 0.2508 - val_loss: 0.7529 - val_mae: 0.6394 - val_rmse: 0.7100 - val_smape: 1.2452

Epoch 3/128

1915/1915 - 34s - 18ms/step - ia: 0.4065 - loss: 0.7928 - mae: 0.6511 - rmse: 0.8584 - smape: 1.2532 - val_ia: 0.2447 - val_loss: 0.7556 - val_mae: 0.6435 - val_rmse: 0.7107 - val_smape: 1.2948

Epoch 4/128

1915/1915 - 29s - 15ms/step - ia: 0.4119 - loss: 0.7856 - mae: 0.6463 - rmse: 0.8536 - smape: 1.2460 - val_ia: 0.2547 - val_loss: 0.7535 - val_mae: 0.6332 - val_rmse: 0.7053 - val_smape: 1.2199

Epoch 5/128

1915/1915 - 32s - 17ms/step - ia: 0.4158 - loss: 0.7786 - mae: 0.6441 - rmse: 0.8505 - smape: 1.2429 - val_ia: 0.2552 - val_loss: 0.7525 - val_mae: 0.6368 - val_rmse: 0.7088 - val_smape: 1.2288

Epoch 6/128

1915/1915 - 43s - 22ms/step - ia: 0.4193 - loss: 0.7728 - mae: 0.6421 - rmse: 0.8475 - smape: 1.2338 - val_ia: 0.2568 - val_loss: 0.7528 - val_mae: 0.6306 - val_rmse: 0.7008 - val_smape: 1.2236

Epoch 7/128

1915/1915 - 39s - 20ms/step - ia: 0.4223 - loss: 0.7702 - mae: 0.6403 - rmse: 0.8442 - smape: 1.2333 - val_ia: 0.2529 - val_loss: 0.7530 - val_mae: 0.6379 - val_rmse: 0.7091 - val_smape: 1.2477

Epoch 8/128

1915/1915 - 41s - 21ms/step - ia: 0.4261 - loss: 0.7635 - mae: 0.6370 - rmse: 0.8406 - smape: 1.2276 - val_ia: 0.2536 - val_loss: 0.7540 - val_mae: 0.6360 - val_rmse: 0.7060 - val_smape: 1.2316

Epoch 9/128

1915/1915 - 38s - 20ms/step - ia: 0.4280 - loss: 0.7592 - mae: 0.6362 - rmse: 0.8380 - smape: 1.2263 - val_ia: 0.2539 - val_loss: 0.7757 - val_mae: 0.6420 - val_rmse: 0.7142 - val_smape: 1.2234

Epoch 10/128

1915/1915 - 42s - 22ms/step - ia: 0.4292 - loss: 0.7561 - mae: 0.6335 - rmse: 0.8371 - smape: 1.2212 - val_ia: 0.2563 - val_loss: 0.7410 - val_mae: 0.6364 - val_rmse: 0.7073 - val_smape: 1.2511

Epoch 11/128

1915/1915 - 44s - 23ms/step - ia: 0.4349 - loss: 0.7473 - mae: 0.6299 - rmse: 0.8329 - smape: 1.2165 - val_ia: 0.2574 - val_loss: 0.7606 - val_mae: 0.6372 - val_rmse: 0.7098 - val_smape: 1.2298

Epoch 12/128

1915/1915 - 43s - 22ms/step - ia: 0.4356 - loss: 0.7437 - mae: 0.6290 - rmse: 0.8313 - smape: 1.2141 - val_ia: 0.2553 - val_loss: 0.7608 - val_mae: 0.6393 - val_rmse: 0.7087 - val_smape: 1.2328

Epoch 13/128

1915/1915 - 42s - 22ms/step - ia: 0.4400 - loss: 0.7366 - mae: 0.6258 - rmse: 0.8261 - smape: 1.2076 - val_ia: 0.2551 - val_loss: 0.7746 - val_mae: 0.6429 - val_rmse: 0.7156 - val_smape: 1.2209

Epoch 14/128

1915/1915 - 84s - 44ms/step - ia: 0.4415 - loss: 0.7321 - mae: 0.6242 - rmse: 0.8255 - smape: 1.2031 - val_ia: 0.2520 - val_loss: 0.7902 - val_mae: 0.6467 - val_rmse: 0.7183 - val_smape: 1.2335

Epoch 15/128

1915/1915 - 44s - 23ms/step - ia: 0.4475 - loss: 0.7196 - mae: 0.6188 - rmse: 0.8177 - smape: 1.1941 - val_ia: 0.2589 - val_loss: 0.7762 - val_mae: 0.6321 - val_rmse: 0.7069 - val_smape: 1.2085

Epoch 16/128

1915/1915 - 37s - 19ms/step - ia: 0.4500 - loss: 0.7140 - mae: 0.6174 - rmse: 0.8128 - smape: 1.1914 - val_ia: 0.2576 - val_loss: 0.7735 - val_mae: 0.6335 - val_rmse: 0.7085 - val_smape: 1.2054

Epoch 17/128

1915/1915 - 34s - 18ms/step - ia: 0.4535 - loss: 0.7031 - mae: 0.6143 - rmse: 0.8096 - smape: 1.1874 - val_ia: 0.2518 - val_loss: 0.8158 - val_mae: 0.6493 - val_rmse: 0.7228 - val_smape: 1.2219

Epoch 18/128

1915/1915 - 37s - 19ms/step - ia: 0.4574 - loss: 0.6925 - mae: 0.6103 - rmse: 0.8031 - smape: 1.1846 - val_ia: 0.2572 - val_loss: 0.8095 - val_mae: 0.6377 - val_rmse: 0.7148 - val_smape: 1.1930

Epoch 19/128

1915/1915 - 36s - 19ms/step - ia: 0.4601 - loss: 0.6863 - mae: 0.6082 - rmse: 0.8012 - smape: 1.1799 - val_ia: 0.2493 - val_loss: 0.8369 - val_mae: 0.6585 - val_rmse: 0.7358 - val_smape: 1.2507

Epoch 20/128

1915/1915 - 34s - 18ms/step - ia: 0.4675 - loss: 0.6733 - mae: 0.6019 - rmse: 0.7916 - smape: 1.1704 - val_ia: 0.2566 - val_loss: 0.8614 - val_mae: 0.6548 - val_rmse: 0.7378 - val_smape: 1.2095

Epoch 21/128

1915/1915 - 34s - 18ms/step - ia: 0.4706 - loss: 0.6623 - mae: 0.5979 - rmse: 0.7866 - smape: 1.1661 - val_ia: 0.2533 - val_loss: 0.8533 - val_mae: 0.6607 - val_rmse: 0.7386 - val_smape: 1.2569

Epoch 22/128

1915/1915 - 30s - 16ms/step - ia: 0.4744 - loss: 0.6519 - mae: 0.5935 - rmse: 0.7801 - smape: 1.1599 - val_ia: 0.2486 - val_loss: 0.8698 - val_mae: 0.6646 - val_rmse: 0.7436 - val_smape: 1.2541

Epoch 23/128

1915/1915 - 35s - 18ms/step - ia: 0.4816 - loss: 0.6422 - mae: 0.5885 - rmse: 0.7745 - smape: 1.1520 - val_ia: 0.2514 - val_loss: 0.8792 - val_mae: 0.6581 - val_rmse: 0.7391 - val_smape: 1.2206

Epoch 24/128

1915/1915 - 41s - 21ms/step - ia: 0.4850 - loss: 0.6311 - mae: 0.5839 - rmse: 0.7676 - smape: 1.1473 - val_ia: 0.2454 - val_loss: 0.9133 - val_mae: 0.6745 - val_rmse: 0.7556 - val_smape: 1.2775

Epoch 25/128

1915/1915 - 26s - 14ms/step - ia: 0.4893 - loss: 0.6176 - mae: 0.5793 - rmse: 0.7586 - smape: 1.1415 - val_ia: 0.2504 - val_loss: 0.8757 - val_mae: 0.6662 - val_rmse: 0.7493 - val_smape: 1.2564

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:45 784ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

Epoch 1/128

 72%|███████▏  | 36/50 [6:19:22<3:10:20, 815.78s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 22s - 182ms/step - ia: 0.2676 - loss: 0.8783 - mae: 0.6961 - rmse: 0.9336 - smape: 1.4686 - val_ia: 0.3230 - val_loss: 0.7802 - val_mae: 0.6534 - val_rmse: 0.8128 - val_smape: 1.3216

Epoch 2/128

120/120 - 7s - 62ms/step - ia: 0.3792 - loss: 0.8164 - mae: 0.6645 - rmse: 0.9016 - smape: 1.2960 - val_ia: 0.3384 - val_loss: 0.7640 - val_mae: 0.6441 - val_rmse: 0.8062 - val_smape: 1.2813

Epoch 3/128

120/120 - 5s - 44ms/step - ia: 0.3953 - loss: 0.8056 - mae: 0.6575 - rmse: 0.8944 - smape: 1.2688 - val_ia: 0.3452 - val_loss: 0.7571 - val_mae: 0.6394 - val_rmse: 0.8035 - val_smape: 1.2598

Epoch 4/128

120/120 - 5s - 39ms/step - ia: 0.4023 - loss: 0.7993 - mae: 0.6533 - rmse: 0.8918 - smape: 1.2574 - val_ia: 0.3494 - val_loss: 0.7644 - val_mae: 0.6444 - val_rmse: 0.8101 - val_smape: 1.2620

Epoch 5/128

120/120 - 5s - 38ms/step - ia: 0.4095 - loss: 0.7945 - mae: 0.6506 - rmse: 0.8894 - smape: 1.2469 - val_ia: 0.3511 - val_loss: 0.7515 - val_mae: 0.6329 - val_rmse: 0.8001 - val_smape: 1.2347

Epoch 6/128

120/120 - 5s - 40ms/step - ia: 0.4104 - loss: 0.7915 - mae: 0.6478 - rmse: 0.8870 - smape: 1.2426 - val_ia: 0.3506 - val_loss: 0.7577 - val_mae: 0.6397 - val_rmse: 0.8058 - val_smape: 1.2495

Epoch 7/128

120/120 - 4s - 36ms/step - ia: 0.4153 - loss: 0.7874 - mae: 0.6461 - rmse: 0.8851 - smape: 1.2389 - val_ia: 0.3505 - val_loss: 0.7593 - val_mae: 0.6413 - val_rmse: 0.8076 - val_smape: 1.2515

Epoch 8/128

120/120 - 4s - 32ms/step - ia: 0.4196 - loss: 0.7819 - mae: 0.6433 - rmse: 0.8817 - smape: 1.2318 - val_ia: 0.3521 - val_loss: 0.7621 - val_mae: 0.6429 - val_rmse: 0.8100 - val_smape: 1.2544

Epoch 9/128

120/120 - 3s - 29ms/step - ia: 0.4218 - loss: 0.7769 - mae: 0.6410 - rmse: 0.8792 - smape: 1.2314 - val_ia: 0.3589 - val_loss: 0.7615 - val_mae: 0.6393 - val_rmse: 0.8084 - val_smape: 1.2379

Epoch 10/128

120/120 - 3s - 29ms/step - ia: 0.4244 - loss: 0.7743 - mae: 0.6408 - rmse: 0.8783 - smape: 1.2301 - val_ia: 0.3565 - val_loss: 0.7567 - val_mae: 0.6359 - val_rmse: 0.8041 - val_smape: 1.2365

Epoch 11/128

120/120 - 3s - 28ms/step - ia: 0.4294 - loss: 0.7689 - mae: 0.6370 - rmse: 0.8734 - smape: 1.2213 - val_ia: 0.3579 - val_loss: 0.7758 - val_mae: 0.6489 - val_rmse: 0.8179 - val_smape: 1.2580

Epoch 12/128

120/120 - 3s - 29ms/step - ia: 0.4299 - loss: 0.7669 - mae: 0.6364 - rmse: 0.8733 - smape: 1.2215 - val_ia: 0.3615 - val_loss: 0.7755 - val_mae: 0.6456 - val_rmse: 0.8157 - val_smape: 1.2424

Epoch 13/128

120/120 - 3s - 29ms/step - ia: 0.4334 - loss: 0.7616 - mae: 0.6347 - rmse: 0.8697 - smape: 1.2161 - val_ia: 0.3715 - val_loss: 0.7707 - val_mae: 0.6370 - val_rmse: 0.8101 - val_smape: 1.2146

Epoch 14/128

120/120 - 4s - 29ms/step - ia: 0.4376 - loss: 0.7584 - mae: 0.6327 - rmse: 0.8682 - smape: 1.2119 - val_ia: 0.3748 - val_loss: 0.7821 - val_mae: 0.6427 - val_rmse: 0.8176 - val_smape: 1.2261

Epoch 15/128

120/120 - 3s - 28ms/step - ia: 0.4387 - loss: 0.7531 - mae: 0.6310 - rmse: 0.8646 - smape: 1.2122 - val_ia: 0.3720 - val_loss: 0.7599 - val_mae: 0.6377 - val_rmse: 0.8073 - val_smape: 1.2318

Epoch 16/128

120/120 - 3s - 26ms/step - ia: 0.4425 - loss: 0.7500 - mae: 0.6294 - rmse: 0.8635 - smape: 1.2053 - val_ia: 0.3743 - val_loss: 0.7614 - val_mae: 0.6382 - val_rmse: 0.8087 - val_smape: 1.2334

Epoch 17/128

120/120 - 4s - 31ms/step - ia: 0.4429 - loss: 0.7453 - mae: 0.6278 - rmse: 0.8607 - smape: 1.2040 - val_ia: 0.3836 - val_loss: 0.7934 - val_mae: 0.6433 - val_rmse: 0.8218 - val_smape: 1.2061

Epoch 18/128

120/120 - 3s - 28ms/step - ia: 0.4485 - loss: 0.7407 - mae: 0.6247 - rmse: 0.8582 - smape: 1.1979 - val_ia: 0.3803 - val_loss: 0.7898 - val_mae: 0.6459 - val_rmse: 0.8218 - val_smape: 1.2218

Epoch 19/128

120/120 - 3s - 28ms/step - ia: 0.4510 - loss: 0.7364 - mae: 0.6241 - rmse: 0.8560 - smape: 1.1922 - val_ia: 0.3803 - val_loss: 0.7753 - val_mae: 0.6394 - val_rmse: 0.8132 - val_smape: 1.2221

Epoch 20/128

120/120 - 3s - 28ms/step - ia: 0.4517 - loss: 0.7335 - mae: 0.6229 - rmse: 0.8539 - smape: 1.1941 - val_ia: 0.3779 - val_loss: 0.7690 - val_mae: 0.6376 - val_rmse: 0.8103 - val_smape: 1.2270

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 49s 368ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 74%|███████▍  | 37/50 [6:21:01<2:10:12, 600.97s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

479/479 - 11s - 22ms/step - ia: 0.2455 - loss: 1.4307 - mae: 1.0244 - rmse: 1.1890 - smape: 1.5407 - val_ia: 0.2498 - val_loss: 1.1362 - val_mae: 0.8885 - val_rmse: 0.9964 - val_smape: 1.6157

Epoch 2/128

479/479 - 9s - 20ms/step - ia: 0.1513 - loss: 1.0543 - mae: 0.8159 - rmse: 1.0173 - smape: 1.6716 - val_ia: 0.2427 - val_loss: 0.9699 - val_mae: 0.7585 - val_rmse: 0.8710 - val_smape: 1.7848

Epoch 3/128

479/479 - 5s - 10ms/step - ia: 0.1123 - loss: 0.9898 - mae: 0.7564 - rmse: 0.9843 - smape: 1.8459 - val_ia: 0.2421 - val_loss: 0.9398 - val_mae: 0.7268 - val_rmse: 0.8415 - val_smape: 1.8313

Epoch 4/128

479/479 - 7s - 14ms/step - ia: 0.1237 - loss: 0.9702 - mae: 0.7389 - rmse: 0.9740 - smape: 1.8157 - val_ia: 0.2438 - val_loss: 0.9242 - val_mae: 0.7207 - val_rmse: 0.8349 - val_smape: 1.7828

Epoch 5/128

479/479 - 7s - 15ms/step - ia: 0.1392 - loss: 0.9536 - mae: 0.7329 - rmse: 0.9649 - smape: 1.7663 - val_ia: 0.2453 - val_loss: 0.9077 - val_mae: 0.7108 - val_rmse: 0.8250 - val_smape: 1.7106

Epoch 6/128

479/479 - 6s - 14ms/step - ia: 0.1538 - loss: 0.9378 - mae: 0.7251 - rmse: 0.9575 - smape: 1.7053 - val_ia: 0.2466 - val_loss: 0.8928 - val_mae: 0.7049 - val_rmse: 0.8187 - val_smape: 1.6662

Epoch 7/128

479/479 - 6s - 13ms/step - ia: 0.1716 - loss: 0.9228 - mae: 0.7171 - rmse: 0.9498 - smape: 1.6505 - val_ia: 0.2485 - val_loss: 0.8805 - val_mae: 0.7051 - val_rmse: 0.8180 - val_smape: 1.6493

Epoch 8/128

479/479 - 6s - 13ms/step - ia: 0.1922 - loss: 0.9093 - mae: 0.7126 - rmse: 0.9411 - smape: 1.6151 - val_ia: 0.2498 - val_loss: 0.8659 - val_mae: 0.6959 - val_rmse: 0.8092 - val_smape: 1.5977

Epoch 9/128

479/479 - 6s - 13ms/step - ia: 0.2131 - loss: 0.8970 - mae: 0.7067 - rmse: 0.9355 - smape: 1.5757 - val_ia: 0.2516 - val_loss: 0.8538 - val_mae: 0.6903 - val_rmse: 0.8038 - val_smape: 1.5613

Epoch 10/128

479/479 - 6s - 12ms/step - ia: 0.2271 - loss: 0.8863 - mae: 0.7017 - rmse: 0.9304 - smape: 1.5430 - val_ia: 0.2536 - val_loss: 0.8432 - val_mae: 0.6867 - val_rmse: 0.8004 - val_smape: 1.5347

Epoch 11/128

479/479 - 6s - 12ms/step - ia: 0.2419 - loss: 0.8767 - mae: 0.6976 - rmse: 0.9261 - smape: 1.5152 - val_ia: 0.2555 - val_loss: 0.8325 - val_mae: 0.6797 - val_rmse: 0.7942 - val_smape: 1.4969

Epoch 12/128

479/479 - 6s - 13ms/step - ia: 0.2569 - loss: 0.8681 - mae: 0.6928 - rmse: 0.9214 - smape: 1.4870 - val_ia: 0.2576 - val_loss: 0.8253 - val_mae: 0.6804 - val_rmse: 0.7949 - val_smape: 1.4880

Epoch 13/128

479/479 - 7s - 14ms/step - ia: 0.2701 - loss: 0.8609 - mae: 0.6902 - rmse: 0.9176 - smape: 1.4669 - val_ia: 0.2595 - val_loss: 0.8165 - val_mae: 0.6740 - val_rmse: 0.7894 - val_smape: 1.4561

Epoch 14/128

479/479 - 7s - 14ms/step - ia: 0.2817 - loss: 0.8545 - mae: 0.6874 - rmse: 0.9143 - smape: 1.4475 - val_ia: 0.2611 - val_loss: 0.8083 - val_mae: 0.6663 - val_rmse: 0.7828 - val_smape: 1.4196

Epoch 15/128

479/479 - 7s - 15ms/step - ia: 0.2934 - loss: 0.8491 - mae: 0.6840 - rmse: 0.9118 - smape: 1.4275 - val_ia: 0.2629 - val_loss: 0.8030 - val_mae: 0.6659 - val_rmse: 0.7827 - val_smape: 1.4109

Epoch 16/128

479/479 - 7s - 14ms/step - ia: 0.3030 - loss: 0.8445 - mae: 0.6822 - rmse: 0.9086 - smape: 1.4135 - val_ia: 0.2645 - val_loss: 0.7975 - val_mae: 0.6625 - val_rmse: 0.7800 - val_smape: 1.3918

Epoch 17/128

479/479 - 8s - 16ms/step - ia: 0.3111 - loss: 0.8404 - mae: 0.6799 - rmse: 0.9068 - smape: 1.3977 - val_ia: 0.2660 - val_loss: 0.7929 - val_mae: 0.6597 - val_rmse: 0.7778 - val_smape: 1.3758

Epoch 18/128

479/479 - 8s - 16ms/step - ia: 0.3188 - loss: 0.8370 - mae: 0.6782 - rmse: 0.9051 - smape: 1.3863 - val_ia: 0.2676 - val_loss: 0.7890 - val_mae: 0.6576 - val_rmse: 0.7763 - val_smape: 1.3631

Epoch 19/128

479/479 - 7s - 15ms/step - ia: 0.3278 - loss: 0.8341 - mae: 0.6763 - rmse: 0.9024 - smape: 1.3742 - val_ia: 0.2689 - val_loss: 0.7862 - val_mae: 0.6572 - val_rmse: 0.7763 - val_smape: 1.3565

Epoch 20/128

479/479 - 8s - 17ms/step - ia: 0.3332 - loss: 0.8315 - mae: 0.6751 - rmse: 0.9027 - smape: 1.3652 - val_ia: 0.2702 - val_loss: 0.7831 - val_mae: 0.6545 - val_rmse: 0.7742 - val_smape: 1.3430

Epoch 21/128

479/479 - 10s - 21ms/step - ia: 0.3377 - loss: 0.8292 - mae: 0.6737 - rmse: 0.9007 - smape: 1.3562 - val_ia: 0.2714 - val_loss: 0.7812 - val_mae: 0.6547 - val_rmse: 0.7746 - val_smape: 1.3391

Epoch 22/128

479/479 - 10s - 21ms/step - ia: 0.3434 - loss: 0.8273 - mae: 0.6728 - rmse: 0.8994 - smape: 1.3485 - val_ia: 0.2724 - val_loss: 0.7792 - val_mae: 0.6533 - val_rmse: 0.7738 - val_smape: 1.3308

Epoch 23/128

479/479 - 8s - 16ms/step - ia: 0.3478 - loss: 0.8256 - mae: 0.6720 - rmse: 0.8981 - smape: 1.3423 - val_ia: 0.2734 - val_loss: 0.7762 - val_mae: 0.6484 - val_rmse: 0.7696 - val_smape: 1.3112

Epoch 24/128

479/479 - 11s - 23ms/step - ia: 0.3516 - loss: 0.8243 - mae: 0.6707 - rmse: 0.8975 - smape: 1.3351 - val_ia: 0.2742 - val_loss: 0.7749 - val_mae: 0.6484 - val_rmse: 0.7698 - val_smape: 1.3083

Epoch 25/128

479/479 - 7s - 15ms/step - ia: 0.3552 - loss: 0.8231 - mae: 0.6696 - rmse: 0.8983 - smape: 1.3289 - val_ia: 0.2749 - val_loss: 0.7749 - val_mae: 0.6509 - val_rmse: 0.7724 - val_smape: 1.3137

Epoch 26/128

479/479 - 8s - 17ms/step - ia: 0.3578 - loss: 0.8221 - mae: 0.6692 - rmse: 0.8964 - smape: 1.3249 - val_ia: 0.2755 - val_loss: 0.7749 - val_mae: 0.6522 - val_rmse: 0.7738 - val_smape: 1.3150

Epoch 27/128

479/479 - 9s - 18ms/step - ia: 0.3603 - loss: 0.8212 - mae: 0.6690 - rmse: 0.8965 - smape: 1.3221 - val_ia: 0.2761 - val_loss: 0.7725 - val_mae: 0.6482 - val_rmse: 0.7702 - val_smape: 1.3005

Epoch 28/128

479/479 - 10s - 20ms/step - ia: 0.3633 - loss: 0.8204 - mae: 0.6682 - rmse: 0.8960 - smape: 1.3173 - val_ia: 0.2766 - val_loss: 0.7713 - val_mae: 0.6463 - val_rmse: 0.7687 - val_smape: 1.2926

Epoch 29/128

479/479 - 8s - 16ms/step - ia: 0.3649 - loss: 0.8197 - mae: 0.6678 - rmse: 0.8959 - smape: 1.3138 - val_ia: 0.2771 - val_loss: 0.7707 - val_mae: 0.6463 - val_rmse: 0.7688 - val_smape: 1.2908

Epoch 30/128

479/479 - 8s - 17ms/step - ia: 0.3661 - loss: 0.8190 - mae: 0.6671 - rmse: 0.8956 - smape: 1.3104 - val_ia: 0.2774 - val_loss: 0.7697 - val_mae: 0.6446 - val_rmse: 0.7674 - val_smape: 1.2836

Epoch 31/128

479/479 - 8s - 17ms/step - ia: 0.3683 - loss: 0.8185 - mae: 0.6671 - rmse: 0.8949 - smape: 1.3090 - val_ia: 0.2777 - val_loss: 0.7686 - val_mae: 0.6418 - val_rmse: 0.7649 - val_smape: 1.2730

Epoch 32/128

479/479 - 7s - 15ms/step - ia: 0.3708 - loss: 0.8180 - mae: 0.6659 - rmse: 0.8950 - smape: 1.3044 - val_ia: 0.2780 - val_loss: 0.7699 - val_mae: 0.6469 - val_rmse: 0.7698 - val_smape: 1.2891

Epoch 33/128

479/479 - 8s - 16ms/step - ia: 0.3709 - loss: 0.8176 - mae: 0.6663 - rmse: 0.8949 - smape: 1.3036 - val_ia: 0.2783 - val_loss: 0.7687 - val_mae: 0.6447 - val_rmse: 0.7678 - val_smape: 1.2806

Epoch 34/128

479/479 - 8s - 18ms/step - ia: 0.3734 - loss: 0.8173 - mae: 0.6657 - rmse: 0.8940 - smape: 1.3011 - val_ia: 0.2785 - val_loss: 0.7686 - val_mae: 0.6451 - val_rmse: 0.7683 - val_smape: 1.2810

Epoch 35/128

479/479 - 8s - 16ms/step - ia: 0.3729 - loss: 0.8168 - mae: 0.6659 - rmse: 0.8945 - smape: 1.3005 - val_ia: 0.2787 - val_loss: 0.7671 - val_mae: 0.6411 - val_rmse: 0.7647 - val_smape: 1.2667

Epoch 36/128

479/479 - 8s - 16ms/step - ia: 0.3760 - loss: 0.8165 - mae: 0.6650 - rmse: 0.8938 - smape: 1.2971 - val_ia: 0.2789 - val_loss: 0.7678 - val_mae: 0.6443 - val_rmse: 0.7677 - val_smape: 1.2770

Epoch 37/128

479/479 - 8s - 17ms/step - ia: 0.3751 - loss: 0.8162 - mae: 0.6653 - rmse: 0.8949 - smape: 1.2970 - val_ia: 0.2790 - val_loss: 0.7673 - val_mae: 0.6433 - val_rmse: 0.7668 - val_smape: 1.2728

Epoch 38/128

479/479 - 10s - 21ms/step - ia: 0.3771 - loss: 0.8159 - mae: 0.6648 - rmse: 0.8933 - smape: 1.2951 - val_ia: 0.2791 - val_loss: 0.7672 - val_mae: 0.6436 - val_rmse: 0.7671 - val_smape: 1.2732

Epoch 39/128

479/479 - 8s - 16ms/step - ia: 0.3774 - loss: 0.8156 - mae: 0.6646 - rmse: 0.8939 - smape: 1.2934 - val_ia: 0.2793 - val_loss: 0.7666 - val_mae: 0.6424 - val_rmse: 0.7660 - val_smape: 1.2688

Epoch 40/128

479/479 - 9s - 18ms/step - ia: 0.3776 - loss: 0.8154 - mae: 0.6644 - rmse: 0.8931 - smape: 1.2927 - val_ia: 0.2793 - val_loss: 0.7669 - val_mae: 0.6436 - val_rmse: 0.7671 - val_smape: 1.2722

Epoch 41/128

479/479 - 9s - 18ms/step - ia: 0.3779 - loss: 0.8151 - mae: 0.6647 - rmse: 0.8931 - smape: 1.2929 - val_ia: 0.2795 - val_loss: 0.7658 - val_mae: 0.6404 - val_rmse: 0.7642 - val_smape: 1.2606

Epoch 42/128

479/479 - 8s - 17ms/step - ia: 0.3795 - loss: 0.8150 - mae: 0.6639 - rmse: 0.8941 - smape: 1.2898 - val_ia: 0.2795 - val_loss: 0.7662 - val_mae: 0.6423 - val_rmse: 0.7660 - val_smape: 1.2672

Epoch 43/128

479/479 - 8s - 17ms/step - ia: 0.3806 - loss: 0.8147 - mae: 0.6636 - rmse: 0.8932 - smape: 1.2887 - val_ia: 0.2795 - val_loss: 0.7675 - val_mae: 0.6456 - val_rmse: 0.7691 - val_smape: 1.2775

Epoch 44/128

479/479 - 8s - 16ms/step - ia: 0.3791 - loss: 0.8146 - mae: 0.6643 - rmse: 0.8930 - smape: 1.2907 - val_ia: 0.2796 - val_loss: 0.7660 - val_mae: 0.6424 - val_rmse: 0.7662 - val_smape: 1.2672

Epoch 45/128

479/479 - 8s - 16ms/step - ia: 0.3802 - loss: 0.8144 - mae: 0.6639 - rmse: 0.8917 - smape: 1.2888 - val_ia: 0.2796 - val_loss: 0.7655 - val_mae: 0.6414 - val_rmse: 0.7652 - val_smape: 1.2632

Epoch 46/128

479/479 - 8s - 17ms/step - ia: 0.3800 - loss: 0.8142 - mae: 0.6639 - rmse: 0.8934 - smape: 1.2884 - val_ia: 0.2798 - val_loss: 0.7650 - val_mae: 0.6401 - val_rmse: 0.7641 - val_smape: 1.2584

Epoch 47/128

479/479 - 7s - 14ms/step - ia: 0.3800 - loss: 0.8141 - mae: 0.6638 - rmse: 0.8934 - smape: 1.2878 - val_ia: 0.2799 - val_loss: 0.7645 - val_mae: 0.6388 - val_rmse: 0.7628 - val_smape: 1.2537

Epoch 48/128

479/479 - 7s - 15ms/step - ia: 0.3821 - loss: 0.8140 - mae: 0.6628 - rmse: 0.8929 - smape: 1.2848 - val_ia: 0.2797 - val_loss: 0.7657 - val_mae: 0.6432 - val_rmse: 0.7669 - val_smape: 1.2688

Epoch 49/128

479/479 - 7s - 16ms/step - ia: 0.3817 - loss: 0.8138 - mae: 0.6634 - rmse: 0.8925 - smape: 1.2870 - val_ia: 0.2798 - val_loss: 0.7650 - val_mae: 0.6418 - val_rmse: 0.7656 - val_smape: 1.2643

Epoch 50/128

479/479 - 8s - 17ms/step - ia: 0.3817 - loss: 0.8136 - mae: 0.6632 - rmse: 0.8932 - smape: 1.2857 - val_ia: 0.2798 - val_loss: 0.7653 - val_mae: 0.6430 - val_rmse: 0.7667 - val_smape: 1.2679

Epoch 51/128

479/479 - 8s - 16ms/step - ia: 0.3824 - loss: 0.8135 - mae: 0.6634 - rmse: 0.8915 - smape: 1.2863 - val_ia: 0.2798 - val_loss: 0.7649 - val_mae: 0.6423 - val_rmse: 0.7660 - val_smape: 1.2653

Epoch 52/128

479/479 - 8s - 17ms/step - ia: 0.3821 - loss: 0.8133 - mae: 0.6629 - rmse: 0.8917 - smape: 1.2847 - val_ia: 0.2798 - val_loss: 0.7658 - val_mae: 0.6442 - val_rmse: 0.7679 - val_smape: 1.2714

Epoch 53/128

479/479 - 8s - 18ms/step - ia: 0.3820 - loss: 0.8132 - mae: 0.6635 - rmse: 0.8923 - smape: 1.2857 - val_ia: 0.2800 - val_loss: 0.7636 - val_mae: 0.6386 - val_rmse: 0.7627 - val_smape: 1.2526

Epoch 54/128

479/479 - 7s - 15ms/step - ia: 0.3833 - loss: 0.8130 - mae: 0.6626 - rmse: 0.8924 - smape: 1.2831 - val_ia: 0.2799 - val_loss: 0.7642 - val_mae: 0.6410 - val_rmse: 0.7649 - val_smape: 1.2609

Epoch 55/128

479/479 - 11s - 23ms/step - ia: 0.3831 - loss: 0.8130 - mae: 0.6630 - rmse: 0.8922 - smape: 1.2845 - val_ia: 0.2799 - val_loss: 0.7639 - val_mae: 0.6403 - val_rmse: 0.7643 - val_smape: 1.2586

Epoch 56/128

479/479 - 8s - 17ms/step - ia: 0.3824 - loss: 0.8127 - mae: 0.6629 - rmse: 0.8923 - smape: 1.2841 - val_ia: 0.2800 - val_loss: 0.7632 - val_mae: 0.6387 - val_rmse: 0.7628 - val_smape: 1.2527

Epoch 57/128

479/479 - 9s - 18ms/step - ia: 0.3841 - loss: 0.8126 - mae: 0.6620 - rmse: 0.8922 - smape: 1.2812 - val_ia: 0.2798 - val_loss: 0.7646 - val_mae: 0.6428 - val_rmse: 0.7666 - val_smape: 1.2670

Epoch 58/128

479/479 - 7s - 15ms/step - ia: 0.3831 - loss: 0.8125 - mae: 0.6627 - rmse: 0.8918 - smape: 1.2840 - val_ia: 0.2799 - val_loss: 0.7642 - val_mae: 0.6424 - val_rmse: 0.7661 - val_smape: 1.2656

Epoch 59/128

479/479 - 8s - 17ms/step - ia: 0.3845 - loss: 0.8125 - mae: 0.6625 - rmse: 0.8926 - smape: 1.2832 - val_ia: 0.2799 - val_loss: 0.7640 - val_mae: 0.6421 - val_rmse: 0.7658 - val_smape: 1.2646

Epoch 60/128

479/479 - 8s - 17ms/step - ia: 0.3835 - loss: 0.8124 - mae: 0.6628 - rmse: 0.8912 - smape: 1.2841 - val_ia: 0.2800 - val_loss: 0.7634 - val_mae: 0.6408 - val_rmse: 0.7646 - val_smape: 1.2599

Epoch 61/128

479/479 - 7s - 15ms/step - ia: 0.3840 - loss: 0.8122 - mae: 0.6622 - rmse: 0.8914 - smape: 1.2817 - val_ia: 0.2799 - val_loss: 0.7638 - val_mae: 0.6419 - val_rmse: 0.7657 - val_smape: 1.2639

Epoch 62/128

479/479 - 8s - 17ms/step - ia: 0.3834 - loss: 0.8122 - mae: 0.6624 - rmse: 0.8914 - smape: 1.2826 - val_ia: 0.2800 - val_loss: 0.7631 - val_mae: 0.6403 - val_rmse: 0.7642 - val_smape: 1.2587

Epoch 63/128

479/479 - 8s - 17ms/step - ia: 0.3850 - loss: 0.8120 - mae: 0.6619 - rmse: 0.8913 - smape: 1.2808 - val_ia: 0.2799 - val_loss: 0.7641 - val_mae: 0.6431 - val_rmse: 0.7668 - val_smape: 1.2674

Epoch 64/128

479/479 - 8s - 17ms/step - ia: 0.3853 - loss: 0.8119 - mae: 0.6623 - rmse: 0.8911 - smape: 1.2824 - val_ia: 0.2799 - val_loss: 0.7637 - val_mae: 0.6425 - val_rmse: 0.7662 - val_smape: 1.2656

Epoch 65/128

479/479 - 8s - 17ms/step - ia: 0.3843 - loss: 0.8118 - mae: 0.6618 - rmse: 0.8922 - smape: 1.2809 - val_ia: 0.2799 - val_loss: 0.7639 - val_mae: 0.6433 - val_rmse: 0.7670 - val_smape: 1.2678

Epoch 66/128

479/479 - 8s - 17ms/step - ia: 0.3841 - loss: 0.8118 - mae: 0.6623 - rmse: 0.8924 - smape: 1.2824 - val_ia: 0.2800 - val_loss: 0.7636 - val_mae: 0.6427 - val_rmse: 0.7664 - val_smape: 1.2661

Epoch 67/128

479/479 - 7s - 16ms/step - ia: 0.3848 - loss: 0.8117 - mae: 0.6624 - rmse: 0.8911 - smape: 1.2824 - val_ia: 0.2801 - val_loss: 0.7620 - val_mae: 0.6389 - val_rmse: 0.7629 - val_smape: 1.2537

Epoch 68/128

479/479 - 6s - 13ms/step - ia: 0.3847 - loss: 0.8115 - mae: 0.6617 - rmse: 0.8928 - smape: 1.2806 - val_ia: 0.2801 - val_loss: 0.7620 - val_mae: 0.6396 - val_rmse: 0.7635 - val_smape: 1.2562

Epoch 69/128

479/479 - 5s - 11ms/step - ia: 0.3855 - loss: 0.8115 - mae: 0.6620 - rmse: 0.8913 - smape: 1.2813 - val_ia: 0.2800 - val_loss: 0.7624 - val_mae: 0.6405 - val_rmse: 0.7644 - val_smape: 1.2595

Epoch 70/128

479/479 - 5s - 11ms/step - ia: 0.3862 - loss: 0.8114 - mae: 0.6619 - rmse: 0.8909 - smape: 1.2807 - val_ia: 0.2800 - val_loss: 0.7621 - val_mae: 0.6401 - val_rmse: 0.7640 - val_smape: 1.2581

Epoch 71/128

479/479 - 5s - 11ms/step - ia: 0.3854 - loss: 0.8113 - mae: 0.6618 - rmse: 0.8917 - smape: 1.2807 - val_ia: 0.2800 - val_loss: 0.7622 - val_mae: 0.6403 - val_rmse: 0.7641 - val_smape: 1.2587

Epoch 72/128

479/479 - 5s - 11ms/step - ia: 0.3858 - loss: 0.8111 - mae: 0.6614 - rmse: 0.8911 - smape: 1.2794 - val_ia: 0.2800 - val_loss: 0.7625 - val_mae: 0.6417 - val_rmse: 0.7654 - val_smape: 1.2631

Epoch 73/128

479/479 - 6s - 13ms/step - ia: 0.3854 - loss: 0.8111 - mae: 0.6620 - rmse: 0.8908 - smape: 1.2813 - val_ia: 0.2800 - val_loss: 0.7617 - val_mae: 0.6398 - val_rmse: 0.7636 - val_smape: 1.2571

Epoch 74/128

479/479 - 7s - 15ms/step - ia: 0.3857 - loss: 0.8110 - mae: 0.6613 - rmse: 0.8908 - smape: 1.2792 - val_ia: 0.2799 - val_loss: 0.7626 - val_mae: 0.6421 - val_rmse: 0.7658 - val_smape: 1.2646

Epoch 75/128

479/479 - 8s - 17ms/step - ia: 0.3855 - loss: 0.8110 - mae: 0.6617 - rmse: 0.8910 - smape: 1.2810 - val_ia: 0.2800 - val_loss: 0.7629 - val_mae: 0.6429 - val_rmse: 0.7665 - val_smape: 1.2666

Epoch 76/128

479/479 - 8s - 16ms/step - ia: 0.3845 - loss: 0.8109 - mae: 0.6620 - rmse: 0.8911 - smape: 1.2816 - val_ia: 0.2801 - val_loss: 0.7607 - val_mae: 0.6379 - val_rmse: 0.7619 - val_smape: 1.2507

Epoch 77/128

479/479 - 7s - 16ms/step - ia: 0.3871 - loss: 0.8108 - mae: 0.6609 - rmse: 0.8905 - smape: 1.2788 - val_ia: 0.2800 - val_loss: 0.7620 - val_mae: 0.6414 - val_rmse: 0.7651 - val_smape: 1.2622

Epoch 78/128

479/479 - 8s - 17ms/step - ia: 0.3861 - loss: 0.8107 - mae: 0.6615 - rmse: 0.8909 - smape: 1.2803 - val_ia: 0.2800 - val_loss: 0.7618 - val_mae: 0.6412 - val_rmse: 0.7649 - val_smape: 1.2618

Epoch 79/128

479/479 - 8s - 17ms/step - ia: 0.3853 - loss: 0.8106 - mae: 0.6618 - rmse: 0.8905 - smape: 1.2808 - val_ia: 0.2801 - val_loss: 0.7606 - val_mae: 0.6382 - val_rmse: 0.7621 - val_smape: 1.2520

Epoch 80/128

479/479 - 7s - 14ms/step - ia: 0.3864 - loss: 0.8105 - mae: 0.6610 - rmse: 0.8908 - smape: 1.2786 - val_ia: 0.2800 - val_loss: 0.7610 - val_mae: 0.6396 - val_rmse: 0.7634 - val_smape: 1.2569

Epoch 81/128

479/479 - 8s - 17ms/step - ia: 0.3848 - loss: 0.8104 - mae: 0.6615 - rmse: 0.8908 - smape: 1.2806 - val_ia: 0.2801 - val_loss: 0.7608 - val_mae: 0.6394 - val_rmse: 0.7633 - val_smape: 1.2562

Epoch 82/128

479/479 - 8s - 17ms/step - ia: 0.3865 - loss: 0.8103 - mae: 0.6614 - rmse: 0.8895 - smape: 1.2796 - val_ia: 0.2801 - val_loss: 0.7602 - val_mae: 0.6377 - val_rmse: 0.7616 - val_smape: 1.2501

Epoch 83/128

479/479 - 8s - 17ms/step - ia: 0.3875 - loss: 0.8103 - mae: 0.6609 - rmse: 0.8911 - smape: 1.2785 - val_ia: 0.2801 - val_loss: 0.7605 - val_mae: 0.6392 - val_rmse: 0.7630 - val_smape: 1.2555

Epoch 84/128

479/479 - 7s - 15ms/step - ia: 0.3871 - loss: 0.8103 - mae: 0.6609 - rmse: 0.8901 - smape: 1.2788 - val_ia: 0.2800 - val_loss: 0.7607 - val_mae: 0.6399 - val_rmse: 0.7636 - val_smape: 1.2579

Epoch 85/128

479/479 - 8s - 17ms/step - ia: 0.3857 - loss: 0.8101 - mae: 0.6610 - rmse: 0.8907 - smape: 1.2787 - val_ia: 0.2800 - val_loss: 0.7605 - val_mae: 0.6397 - val_rmse: 0.7635 - val_smape: 1.2574

Epoch 86/128

479/479 - 8s - 16ms/step - ia: 0.3861 - loss: 0.8100 - mae: 0.6611 - rmse: 0.8912 - smape: 1.2796 - val_ia: 0.2800 - val_loss: 0.7610 - val_mae: 0.6408 - val_rmse: 0.7645 - val_smape: 1.2607

Epoch 87/128

479/479 - 8s - 16ms/step - ia: 0.3865 - loss: 0.8100 - mae: 0.6611 - rmse: 0.8899 - smape: 1.2797 - val_ia: 0.2801 - val_loss: 0.7605 - val_mae: 0.6402 - val_rmse: 0.7639 - val_smape: 1.2588

Epoch 88/128

479/479 - 8s - 17ms/step - ia: 0.3869 - loss: 0.8099 - mae: 0.6609 - rmse: 0.8907 - smape: 1.2784 - val_ia: 0.2800 - val_loss: 0.7600 - val_mae: 0.6390 - val_rmse: 0.7628 - val_smape: 1.2554

Epoch 89/128

479/479 - 8s - 16ms/step - ia: 0.3875 - loss: 0.8098 - mae: 0.6605 - rmse: 0.8903 - smape: 1.2777 - val_ia: 0.2800 - val_loss: 0.7628 - val_mae: 0.6446 - val_rmse: 0.7681 - val_smape: 1.2721

Epoch 90/128

479/479 - 6s - 13ms/step - ia: 0.3862 - loss: 0.8099 - mae: 0.6613 - rmse: 0.8896 - smape: 1.2797 - val_ia: 0.2800 - val_loss: 0.7609 - val_mae: 0.6415 - val_rmse: 0.7651 - val_smape: 1.2629

Epoch 91/128

479/479 - 10s - 20ms/step - ia: 0.3867 - loss: 0.8098 - mae: 0.6609 - rmse: 0.8906 - smape: 1.2788 - val_ia: 0.2801 - val_loss: 0.7597 - val_mae: 0.6390 - val_rmse: 0.7628 - val_smape: 1.2553

Epoch 92/128

479/479 - 6s - 12ms/step - ia: 0.3876 - loss: 0.8096 - mae: 0.6607 - rmse: 0.8903 - smape: 1.2784 - val_ia: 0.2801 - val_loss: 0.7597 - val_mae: 0.6393 - val_rmse: 0.7630 - val_smape: 1.2561

Epoch 93/128

479/479 - 6s - 14ms/step - ia: 0.3870 - loss: 0.8097 - mae: 0.6609 - rmse: 0.8894 - smape: 1.2792 - val_ia: 0.2801 - val_loss: 0.7592 - val_mae: 0.6382 - val_rmse: 0.7620 - val_smape: 1.2528

Epoch 94/128

479/479 - 6s - 13ms/step - ia: 0.3872 - loss: 0.8095 - mae: 0.6609 - rmse: 0.8907 - smape: 1.2791 - val_ia: 0.2801 - val_loss: 0.7589 - val_mae: 0.6376 - val_rmse: 0.7615 - val_smape: 1.2508

Epoch 95/128

479/479 - 6s - 13ms/step - ia: 0.3873 - loss: 0.8094 - mae: 0.6603 - rmse: 0.8902 - smape: 1.2771 - val_ia: 0.2801 - val_loss: 0.7595 - val_mae: 0.6394 - val_rmse: 0.7631 - val_smape: 1.2567

Epoch 96/128

479/479 - 7s - 14ms/step - ia: 0.3871 - loss: 0.8094 - mae: 0.6610 - rmse: 0.8892 - smape: 1.2796 - val_ia: 0.2801 - val_loss: 0.7588 - val_mae: 0.6379 - val_rmse: 0.7617 - val_smape: 1.2517

Epoch 97/128

479/479 - 7s - 14ms/step - ia: 0.3870 - loss: 0.8093 - mae: 0.6607 - rmse: 0.8904 - smape: 1.2788 - val_ia: 0.2801 - val_loss: 0.7590 - val_mae: 0.6383 - val_rmse: 0.7621 - val_smape: 1.2532

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 67s - 70ms/step - ia: 0.3835 - loss: 0.8223 - mae: 0.6677 - rmse: 0.8878 - smape: 1.2931 - val_ia: 0.2555 - val_loss: 0.7617 - val_mae: 0.6509 - val_rmse: 0.7422 - val_smape: 1.3221

Epoch 2/128

958/958 - 23s - 24ms/step - ia: 0.4036 - loss: 0.8021 - mae: 0.6553 - rmse: 0.8778 - smape: 1.2592 - val_ia: 0.2624 - val_loss: 0.7372 - val_mae: 0.6337 - val_rmse: 0.7271 - val_smape: 1.2575

Epoch 3/128

958/958 - 22s - 23ms/step - ia: 0.4092 - loss: 0.7912 - mae: 0.6498 - rmse: 0.8714 - smape: 1.2530 - val_ia: 0.2787 - val_loss: 0.7409 - val_mae: 0.6251 - val_rmse: 0.7261 - val_smape: 1.1762

Epoch 4/128

958/958 - 23s - 24ms/step - ia: 0.4175 - loss: 0.7819 - mae: 0.6466 - rmse: 0.8659 - smape: 1.2432 - val_ia: 0.2697 - val_loss: 0.7523 - val_mae: 0.6324 - val_rmse: 0.7313 - val_smape: 1.1975

Epoch 5/128

958/958 - 23s - 24ms/step - ia: 0.4230 - loss: 0.7740 - mae: 0.6415 - rmse: 0.8613 - smape: 1.2365 - val_ia: 0.2675 - val_loss: 0.7404 - val_mae: 0.6226 - val_rmse: 0.7195 - val_smape: 1.1998

Epoch 6/128

958/958 - 22s - 23ms/step - ia: 0.4250 - loss: 0.7684 - mae: 0.6394 - rmse: 0.8586 - smape: 1.2325 - val_ia: 0.2711 - val_loss: 0.7933 - val_mae: 0.6455 - val_rmse: 0.7504 - val_smape: 1.2170

Epoch 7/128

958/958 - 25s - 26ms/step - ia: 0.4286 - loss: 0.7622 - mae: 0.6364 - rmse: 0.8562 - smape: 1.2271 - val_ia: 0.2687 - val_loss: 0.7693 - val_mae: 0.6464 - val_rmse: 0.7468 - val_smape: 1.2456

Epoch 8/128

958/958 - 24s - 25ms/step - ia: 0.4324 - loss: 0.7549 - mae: 0.6340 - rmse: 0.8503 - smape: 1.2234 - val_ia: 0.2638 - val_loss: 0.7607 - val_mae: 0.6449 - val_rmse: 0.7388 - val_smape: 1.2707

Epoch 9/128

958/958 - 21s - 21ms/step - ia: 0.4368 - loss: 0.7484 - mae: 0.6304 - rmse: 0.8474 - smape: 1.2138 - val_ia: 0.2754 - val_loss: 0.7861 - val_mae: 0.6475 - val_rmse: 0.7538 - val_smape: 1.2238

Epoch 10/128

958/958 - 18s - 19ms/step - ia: 0.4435 - loss: 0.7388 - mae: 0.6267 - rmse: 0.8419 - smape: 1.2073 - val_ia: 0.2649 - val_loss: 0.7739 - val_mae: 0.6418 - val_rmse: 0.7399 - val_smape: 1.2347

Epoch 11/128

958/958 - 18s - 19ms/step - ia: 0.4452 - loss: 0.7321 - mae: 0.6246 - rmse: 0.8393 - smape: 1.2064 - val_ia: 0.2684 - val_loss: 0.7783 - val_mae: 0.6443 - val_rmse: 0.7447 - val_smape: 1.2487

Epoch 12/128

958/958 - 23s - 24ms/step - ia: 0.4507 - loss: 0.7230 - mae: 0.6210 - rmse: 0.8335 - smape: 1.1983 - val_ia: 0.2612 - val_loss: 0.7932 - val_mae: 0.6561 - val_rmse: 0.7520 - val_smape: 1.2917

Epoch 13/128

958/958 - 22s - 23ms/step - ia: 0.4541 - loss: 0.7146 - mae: 0.6179 - rmse: 0.8282 - smape: 1.1950 - val_ia: 0.2684 - val_loss: 0.7884 - val_mae: 0.6486 - val_rmse: 0.7485 - val_smape: 1.2558

Epoch 14/128

958/958 - 24s - 25ms/step - ia: 0.4627 - loss: 0.6989 - mae: 0.6114 - rmse: 0.8184 - smape: 1.1855 - val_ia: 0.2690 - val_loss: 0.7886 - val_mae: 0.6521 - val_rmse: 0.7511 - val_smape: 1.2800

Epoch 15/128

958/958 - 24s - 25ms/step - ia: 0.4697 - loss: 0.6859 - mae: 0.6059 - rmse: 0.8127 - smape: 1.1745 - val_ia: 0.2678 - val_loss: 0.8132 - val_mae: 0.6436 - val_rmse: 0.7479 - val_smape: 1.2155

Epoch 16/128

958/958 - 23s - 24ms/step - ia: 0.4772 - loss: 0.6696 - mae: 0.5986 - rmse: 0.8033 - smape: 1.1629 - val_ia: 0.2628 - val_loss: 0.8270 - val_mae: 0.6660 - val_rmse: 0.7668 - val_smape: 1.3121

Epoch 17/128

958/958 - 41s - 43ms/step - ia: 0.4831 - loss: 0.6556 - mae: 0.5939 - rmse: 0.7944 - smape: 1.1595 - val_ia: 0.2702 - val_loss: 0.8319 - val_mae: 0.6625 - val_rmse: 0.7691 - val_smape: 1.2692

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 6:09 3s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step

 78%|███████▊  | 39/50 [6:44:29<1:55:38, 630.78s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 45s - 23ms/step - ia: 0.3012 - loss: 1.2238 - mae: 0.8410 - rmse: 1.0723 - smape: 1.4313 - val_ia: 0.2264 - val_loss: 0.8473 - val_mae: 0.6915 - val_rmse: 0.7507 - val_smape: 1.5645

Epoch 2/128

1915/1915 - 20s - 11ms/step - ia: 0.3291 - loss: 1.0676 - mae: 0.7779 - rmse: 1.0008 - smape: 1.3859 - val_ia: 0.2362 - val_loss: 0.7990 - val_mae: 0.6620 - val_rmse: 0.7245 - val_smape: 1.3964

Epoch 3/128

1915/1915 - 20s - 11ms/step - ia: 0.3449 - loss: 0.9813 - mae: 0.7445 - rmse: 0.9584 - smape: 1.3609 - val_ia: 0.2411 - val_loss: 0.7837 - val_mae: 0.6547 - val_rmse: 0.7191 - val_smape: 1.3481

Epoch 4/128

1915/1915 - 20s - 10ms/step - ia: 0.3548 - loss: 0.9409 - mae: 0.7259 - rmse: 0.9386 - smape: 1.3447 - val_ia: 0.2449 - val_loss: 0.7773 - val_mae: 0.6447 - val_rmse: 0.7106 - val_smape: 1.3010

Epoch 5/128

1915/1915 - 21s - 11ms/step - ia: 0.3607 - loss: 0.9139 - mae: 0.7135 - rmse: 0.9246 - smape: 1.3332 - val_ia: 0.2446 - val_loss: 0.7752 - val_mae: 0.6485 - val_rmse: 0.7145 - val_smape: 1.3118

Epoch 6/128

1915/1915 - 21s - 11ms/step - ia: 0.3613 - loss: 0.8950 - mae: 0.7048 - rmse: 0.9143 - smape: 1.3331 - val_ia: 0.2442 - val_loss: 0.7747 - val_mae: 0.6520 - val_rmse: 0.7181 - val_smape: 1.3183

Epoch 7/128

1915/1915 - 41s - 21ms/step - ia: 0.3640 - loss: 0.8807 - mae: 0.6991 - rmse: 0.9080 - smape: 1.3297 - val_ia: 0.2459 - val_loss: 0.7709 - val_mae: 0.6469 - val_rmse: 0.7135 - val_smape: 1.2987

Epoch 8/128

1915/1915 - 20s - 11ms/step - ia: 0.3692 - loss: 0.8757 - mae: 0.6931 - rmse: 0.9041 - smape: 1.3156 - val_ia: 0.2459 - val_loss: 0.7702 - val_mae: 0.6473 - val_rmse: 0.7138 - val_smape: 1.2988

Epoch 9/128

1915/1915 - 20s - 10ms/step - ia: 0.3705 - loss: 0.8603 - mae: 0.6870 - rmse: 0.8961 - smape: 1.3105 - val_ia: 0.2462 - val_loss: 0.7689 - val_mae: 0.6475 - val_rmse: 0.7144 - val_smape: 1.2960

Epoch 10/128

1915/1915 - 20s - 10ms/step - ia: 0.3718 - loss: 0.8575 - mae: 0.6860 - rmse: 0.8949 - smape: 1.3130 - val_ia: 0.2476 - val_loss: 0.7662 - val_mae: 0.6421 - val_rmse: 0.7094 - val_smape: 1.2753

Epoch 11/128

1915/1915 - 20s - 10ms/step - ia: 0.3723 - loss: 0.8539 - mae: 0.6836 - rmse: 0.8932 - smape: 1.3096 - val_ia: 0.2459 - val_loss: 0.7686 - val_mae: 0.6488 - val_rmse: 0.7159 - val_smape: 1.2969

Epoch 12/128

1915/1915 - 21s - 11ms/step - ia: 0.3725 - loss: 0.8494 - mae: 0.6815 - rmse: 0.8890 - smape: 1.3087 - val_ia: 0.2467 - val_loss: 0.7667 - val_mae: 0.6458 - val_rmse: 0.7130 - val_smape: 1.2875

Epoch 13/128

1915/1915 - 20s - 10ms/step - ia: 0.3739 - loss: 0.8433 - mae: 0.6799 - rmse: 0.8854 - smape: 1.3082 - val_ia: 0.2479 - val_loss: 0.7640 - val_mae: 0.6421 - val_rmse: 0.7096 - val_smape: 1.2724

Epoch 14/128

1915/1915 - 19s - 10ms/step - ia: 0.3728 - loss: 0.8453 - mae: 0.6799 - rmse: 0.8878 - smape: 1.3060 - val_ia: 0.2462 - val_loss: 0.7664 - val_mae: 0.6484 - val_rmse: 0.7157 - val_smape: 1.2929

Epoch 15/128

1915/1915 - 19s - 10ms/step - ia: 0.3752 - loss: 0.8402 - mae: 0.6769 - rmse: 0.8856 - smape: 1.3028 - val_ia: 0.2467 - val_loss: 0.7648 - val_mae: 0.6469 - val_rmse: 0.7142 - val_smape: 1.2877

Epoch 16/128

1915/1915 - 17s - 9ms/step - ia: 0.3761 - loss: 0.8358 - mae: 0.6757 - rmse: 0.8810 - smape: 1.3040 - val_ia: 0.2487 - val_loss: 0.7615 - val_mae: 0.6385 - val_rmse: 0.7067 - val_smape: 1.2559

Epoch 17/128

1915/1915 - 15s - 8ms/step - ia: 0.3790 - loss: 0.8321 - mae: 0.6737 - rmse: 0.8811 - smape: 1.2978 - val_ia: 0.2492 - val_loss: 0.7613 - val_mae: 0.6345 - val_rmse: 0.7027 - val_smape: 1.2407

Epoch 18/128

1915/1915 - 19s - 10ms/step - ia: 0.3789 - loss: 0.8328 - mae: 0.6725 - rmse: 0.8822 - smape: 1.2946 - val_ia: 0.2456 - val_loss: 0.7654 - val_mae: 0.6504 - val_rmse: 0.7179 - val_smape: 1.2950

Epoch 19/128

1915/1915 - 20s - 10ms/step - ia: 0.3794 - loss: 0.8307 - mae: 0.6724 - rmse: 0.8791 - smape: 1.2953 - val_ia: 0.2473 - val_loss: 0.7615 - val_mae: 0.6435 - val_rmse: 0.7111 - val_smape: 1.2762

Epoch 20/128

1915/1915 - 20s - 10ms/step - ia: 0.3781 - loss: 0.8275 - mae: 0.6710 - rmse: 0.8770 - smape: 1.2934 - val_ia: 0.2473 - val_loss: 0.7610 - val_mae: 0.6439 - val_rmse: 0.7118 - val_smape: 1.2753

Epoch 21/128

1915/1915 - 20s - 10ms/step - ia: 0.3782 - loss: 0.8296 - mae: 0.6723 - rmse: 0.8795 - smape: 1.2980 - val_ia: 0.2478 - val_loss: 0.7596 - val_mae: 0.6401 - val_rmse: 0.7080 - val_smape: 1.2645

Epoch 22/128

1915/1915 - 20s - 11ms/step - ia: 0.3798 - loss: 0.8264 - mae: 0.6702 - rmse: 0.8764 - smape: 1.2942 - val_ia: 0.2479 - val_loss: 0.7590 - val_mae: 0.6411 - val_rmse: 0.7091 - val_smape: 1.2654

Epoch 23/128

1915/1915 - 20s - 11ms/step - ia: 0.3804 - loss: 0.8271 - mae: 0.6702 - rmse: 0.8780 - smape: 1.2935 - val_ia: 0.2481 - val_loss: 0.7583 - val_mae: 0.6390 - val_rmse: 0.7070 - val_smape: 1.2600

Epoch 24/128

1915/1915 - 19s - 10ms/step - ia: 0.3812 - loss: 0.8215 - mae: 0.6678 - rmse: 0.8754 - smape: 1.2868 - val_ia: 0.2474 - val_loss: 0.7592 - val_mae: 0.6438 - val_rmse: 0.7119 - val_smape: 1.2723

Epoch 25/128

1915/1915 - 19s - 10ms/step - ia: 0.3830 - loss: 0.8193 - mae: 0.6663 - rmse: 0.8736 - smape: 1.2838 - val_ia: 0.2470 - val_loss: 0.7595 - val_mae: 0.6432 - val_rmse: 0.7114 - val_smape: 1.2714

Epoch 26/128

1915/1915 - 20s - 11ms/step - ia: 0.3845 - loss: 0.8199 - mae: 0.6662 - rmse: 0.8733 - smape: 1.2860 - val_ia: 0.2468 - val_loss: 0.7592 - val_mae: 0.6445 - val_rmse: 0.7125 - val_smape: 1.2763

Epoch 27/128

1915/1915 - 20s - 10ms/step - ia: 0.3855 - loss: 0.8195 - mae: 0.6658 - rmse: 0.8747 - smape: 1.2832 - val_ia: 0.2474 - val_loss: 0.7571 - val_mae: 0.6406 - val_rmse: 0.7083 - val_smape: 1.2667

Epoch 28/128

1915/1915 - 15s - 8ms/step - ia: 0.3817 - loss: 0.8191 - mae: 0.6672 - rmse: 0.8736 - smape: 1.2899 - val_ia: 0.2480 - val_loss: 0.7559 - val_mae: 0.6395 - val_rmse: 0.7077 - val_smape: 1.2604

Epoch 29/128

1915/1915 - 16s - 8ms/step - ia: 0.3826 - loss: 0.8208 - mae: 0.6672 - rmse: 0.8735 - smape: 1.2883 - val_ia: 0.2484 - val_loss: 0.7550 - val_mae: 0.6386 - val_rmse: 0.7070 - val_smape: 1.2556

Epoch 30/128

1915/1915 - 18s - 9ms/step - ia: 0.3842 - loss: 0.8187 - mae: 0.6655 - rmse: 0.8739 - smape: 1.2849 - val_ia: 0.2489 - val_loss: 0.7544 - val_mae: 0.6365 - val_rmse: 0.7051 - val_smape: 1.2480

Epoch 31/128

1915/1915 - 20s - 11ms/step - ia: 0.3861 - loss: 0.8169 - mae: 0.6650 - rmse: 0.8725 - smape: 1.2857 - val_ia: 0.2480 - val_loss: 0.7553 - val_mae: 0.6397 - val_rmse: 0.7082 - val_smape: 1.2587

Epoch 32/128

1915/1915 - 18s - 9ms/step - ia: 0.3844 - loss: 0.8178 - mae: 0.6651 - rmse: 0.8721 - smape: 1.2867 - val_ia: 0.2474 - val_loss: 0.7571 - val_mae: 0.6431 - val_rmse: 0.7117 - val_smape: 1.2661

Epoch 33/128

1915/1915 - 16s - 8ms/step - ia: 0.3876 - loss: 0.8161 - mae: 0.6647 - rmse: 0.8723 - smape: 1.2828 - val_ia: 0.2485 - val_loss: 0.7538 - val_mae: 0.6374 - val_rmse: 0.7060 - val_smape: 1.2517

Epoch 34/128

1915/1915 - 17s - 9ms/step - ia: 0.3883 - loss: 0.8149 - mae: 0.6642 - rmse: 0.8708 - smape: 1.2816 - val_ia: 0.2480 - val_loss: 0.7539 - val_mae: 0.6393 - val_rmse: 0.7076 - val_smape: 1.2586

Epoch 35/128

1915/1915 - 18s - 10ms/step - ia: 0.3866 - loss: 0.8173 - mae: 0.6649 - rmse: 0.8726 - smape: 1.2842 - val_ia: 0.2489 - val_loss: 0.7525 - val_mae: 0.6356 - val_rmse: 0.7040 - val_smape: 1.2467

Epoch 36/128

1915/1915 - 18s - 9ms/step - ia: 0.3879 - loss: 0.8129 - mae: 0.6624 - rmse: 0.8708 - smape: 1.2814 - val_ia: 0.2475 - val_loss: 0.7552 - val_mae: 0.6424 - val_rmse: 0.7110 - val_smape: 1.2650

Epoch 37/128

1915/1915 - 19s - 10ms/step - ia: 0.3877 - loss: 0.8149 - mae: 0.6640 - rmse: 0.8704 - smape: 1.2786 - val_ia: 0.2487 - val_loss: 0.7521 - val_mae: 0.6362 - val_rmse: 0.7046 - val_smape: 1.2488

Epoch 38/128

1915/1915 - 19s - 10ms/step - ia: 0.3848 - loss: 0.8130 - mae: 0.6636 - rmse: 0.8695 - smape: 1.2828 - val_ia: 0.2478 - val_loss: 0.7546 - val_mae: 0.6413 - val_rmse: 0.7102 - val_smape: 1.2608

Epoch 39/128

1915/1915 - 18s - 10ms/step - ia: 0.3888 - loss: 0.8119 - mae: 0.6628 - rmse: 0.8682 - smape: 1.2808 - val_ia: 0.2485 - val_loss: 0.7529 - val_mae: 0.6391 - val_rmse: 0.7080 - val_smape: 1.2537

Epoch 40/128

1915/1915 - 19s - 10ms/step - ia: 0.3914 - loss: 0.8104 - mae: 0.6617 - rmse: 0.8697 - smape: 1.2761 - val_ia: 0.2489 - val_loss: 0.7516 - val_mae: 0.6363 - val_rmse: 0.7051 - val_smape: 1.2471

Epoch 41/128

1915/1915 - 19s - 10ms/step - ia: 0.3921 - loss: 0.8098 - mae: 0.6615 - rmse: 0.8674 - smape: 1.2748 - val_ia: 0.2489 - val_loss: 0.7508 - val_mae: 0.6363 - val_rmse: 0.7049 - val_smape: 1.2491

Epoch 42/128

1915/1915 - 20s - 11ms/step - ia: 0.3889 - loss: 0.8114 - mae: 0.6626 - rmse: 0.8681 - smape: 1.2803 - val_ia: 0.2473 - val_loss: 0.7528 - val_mae: 0.6398 - val_rmse: 0.7078 - val_smape: 1.2641

Epoch 43/128

1915/1915 - 20s - 11ms/step - ia: 0.3900 - loss: 0.8110 - mae: 0.6624 - rmse: 0.8683 - smape: 1.2793 - val_ia: 0.2477 - val_loss: 0.7519 - val_mae: 0.6388 - val_rmse: 0.7070 - val_smape: 1.2607

Epoch 44/128

1915/1915 - 18s - 10ms/step - ia: 0.3901 - loss: 0.8088 - mae: 0.6609 - rmse: 0.8678 - smape: 1.2769 - val_ia: 0.2469 - val_loss: 0.7534 - val_mae: 0.6419 - val_rmse: 0.7100 - val_smape: 1.2699

Epoch 45/128

1915/1915 - 18s - 10ms/step - ia: 0.3912 - loss: 0.8097 - mae: 0.6618 - rmse: 0.8672 - smape: 1.2785 - val_ia: 0.2474 - val_loss: 0.7531 - val_mae: 0.6405 - val_rmse: 0.7089 - val_smape: 1.2632

Epoch 46/128

1915/1915 - 19s - 10ms/step - ia: 0.3907 - loss: 0.8083 - mae: 0.6615 - rmse: 0.8673 - smape: 1.2764 - val_ia: 0.2489 - val_loss: 0.7508 - val_mae: 0.6358 - val_rmse: 0.7048 - val_smape: 1.2459

Epoch 47/128

1915/1915 - 19s - 10ms/step - ia: 0.3928 - loss: 0.8074 - mae: 0.6594 - rmse: 0.8661 - smape: 1.2708 - val_ia: 0.2474 - val_loss: 0.7522 - val_mae: 0.6405 - val_rmse: 0.7088 - val_smape: 1.2641

Epoch 48/128

1915/1915 - 18s - 9ms/step - ia: 0.3907 - loss: 0.8053 - mae: 0.6602 - rmse: 0.8665 - smape: 1.2767 - val_ia: 0.2502 - val_loss: 0.7499 - val_mae: 0.6328 - val_rmse: 0.7026 - val_smape: 1.2306

Epoch 49/128

1915/1915 - 19s - 10ms/step - ia: 0.3950 - loss: 0.8054 - mae: 0.6592 - rmse: 0.8664 - smape: 1.2698 - val_ia: 0.2473 - val_loss: 0.7518 - val_mae: 0.6403 - val_rmse: 0.7086 - val_smape: 1.2647

Epoch 50/128

1915/1915 - 19s - 10ms/step - ia: 0.3927 - loss: 0.8057 - mae: 0.6592 - rmse: 0.8658 - smape: 1.2728 - val_ia: 0.2484 - val_loss: 0.7506 - val_mae: 0.6374 - val_rmse: 0.7062 - val_smape: 1.2531

Epoch 51/128

1915/1915 - 21s - 11ms/step - ia: 0.3938 - loss: 0.8061 - mae: 0.6594 - rmse: 0.8660 - smape: 1.2737 - val_ia: 0.2489 - val_loss: 0.7490 - val_mae: 0.6356 - val_rmse: 0.7042 - val_smape: 1.2489

Epoch 52/128

1915/1915 - 18s - 9ms/step - ia: 0.3923 - loss: 0.8050 - mae: 0.6598 - rmse: 0.8655 - smape: 1.2747 - val_ia: 0.2493 - val_loss: 0.7490 - val_mae: 0.6352 - val_rmse: 0.7043 - val_smape: 1.2436

Epoch 53/128

1915/1915 - 18s - 9ms/step - ia: 0.3934 - loss: 0.8061 - mae: 0.6593 - rmse: 0.8662 - smape: 1.2727 - val_ia: 0.2493 - val_loss: 0.7489 - val_mae: 0.6349 - val_rmse: 0.7040 - val_smape: 1.2428

Epoch 54/128

1915/1915 - 19s - 10ms/step - ia: 0.3933 - loss: 0.8064 - mae: 0.6591 - rmse: 0.8670 - smape: 1.2704 - val_ia: 0.2467 - val_loss: 0.7532 - val_mae: 0.6435 - val_rmse: 0.7118 - val_smape: 1.2711

Epoch 55/128

1915/1915 - 19s - 10ms/step - ia: 0.3951 - loss: 0.8051 - mae: 0.6587 - rmse: 0.8652 - smape: 1.2702 - val_ia: 0.2477 - val_loss: 0.7506 - val_mae: 0.6390 - val_rmse: 0.7074 - val_smape: 1.2607

Epoch 56/128

1915/1915 - 17s - 9ms/step - ia: 0.3947 - loss: 0.8020 - mae: 0.6579 - rmse: 0.8640 - smape: 1.2703 - val_ia: 0.2489 - val_loss: 0.7494 - val_mae: 0.6354 - val_rmse: 0.7044 - val_smape: 1.2463

Epoch 57/128

1915/1915 - 14s - 7ms/step - ia: 0.3934 - loss: 0.8015 - mae: 0.6579 - rmse: 0.8643 - smape: 1.2714 - val_ia: 0.2491 - val_loss: 0.7518 - val_mae: 0.6375 - val_rmse: 0.7075 - val_smape: 1.2418

Epoch 58/128

1915/1915 - 15s - 8ms/step - ia: 0.3975 - loss: 0.8030 - mae: 0.6579 - rmse: 0.8643 - smape: 1.2647 - val_ia: 0.2474 - val_loss: 0.7505 - val_mae: 0.6398 - val_rmse: 0.7082 - val_smape: 1.2626

Epoch 59/128

1915/1915 - 19s - 10ms/step - ia: 0.3960 - loss: 0.8015 - mae: 0.6570 - rmse: 0.8642 - smape: 1.2672 - val_ia: 0.2491 - val_loss: 0.7478 - val_mae: 0.6339 - val_rmse: 0.7027 - val_smape: 1.2447

Epoch 60/128

1915/1915 - 18s - 9ms/step - ia: 0.3940 - loss: 0.8002 - mae: 0.6572 - rmse: 0.8619 - smape: 1.2713 - val_ia: 0.2479 - val_loss: 0.7512 - val_mae: 0.6395 - val_rmse: 0.7086 - val_smape: 1.2541

Epoch 61/128

1915/1915 - 17s - 9ms/step - ia: 0.3959 - loss: 0.8023 - mae: 0.6567 - rmse: 0.8630 - smape: 1.2660 - val_ia: 0.2477 - val_loss: 0.7515 - val_mae: 0.6394 - val_rmse: 0.7085 - val_smape: 1.2559

Epoch 62/128

1915/1915 - 13s - 7ms/step - ia: 0.3980 - loss: 0.8004 - mae: 0.6569 - rmse: 0.8637 - smape: 1.2662 - val_ia: 0.2483 - val_loss: 0.7494 - val_mae: 0.6371 - val_rmse: 0.7061 - val_smape: 1.2515

Epoch 63/128

1915/1915 - 24s - 12ms/step - ia: 0.3969 - loss: 0.7998 - mae: 0.6568 - rmse: 0.8630 - smape: 1.2688 - val_ia: 0.2494 - val_loss: 0.7475 - val_mae: 0.6341 - val_rmse: 0.7033 - val_smape: 1.2408

Epoch 64/128

1915/1915 - 23s - 12ms/step - ia: 0.3997 - loss: 0.7986 - mae: 0.6560 - rmse: 0.8625 - smape: 1.2640 - val_ia: 0.2485 - val_loss: 0.7467 - val_mae: 0.6344 - val_rmse: 0.7028 - val_smape: 1.2510

Epoch 65/128

1915/1915 - 18s - 10ms/step - ia: 0.3965 - loss: 0.7991 - mae: 0.6560 - rmse: 0.8612 - smape: 1.2665 - val_ia: 0.2498 - val_loss: 0.7460 - val_mae: 0.6316 - val_rmse: 0.7007 - val_smape: 1.2374

Epoch 66/128

1915/1915 - 19s - 10ms/step - ia: 0.3984 - loss: 0.7982 - mae: 0.6554 - rmse: 0.8617 - smape: 1.2677 - val_ia: 0.2479 - val_loss: 0.7494 - val_mae: 0.6383 - val_rmse: 0.7073 - val_smape: 1.2551

Epoch 67/128

1915/1915 - 19s - 10ms/step - ia: 0.3971 - loss: 0.7998 - mae: 0.6564 - rmse: 0.8630 - smape: 1.2685 - val_ia: 0.2484 - val_loss: 0.7477 - val_mae: 0.6362 - val_rmse: 0.7050 - val_smape: 1.2499

Epoch 68/128

1915/1915 - 18s - 10ms/step - ia: 0.3996 - loss: 0.7975 - mae: 0.6549 - rmse: 0.8614 - smape: 1.2636 - val_ia: 0.2471 - val_loss: 0.7500 - val_mae: 0.6397 - val_rmse: 0.7083 - val_smape: 1.2612

Epoch 69/128

1915/1915 - 19s - 10ms/step - ia: 0.3976 - loss: 0.7980 - mae: 0.6557 - rmse: 0.8606 - smape: 1.2662 - val_ia: 0.2496 - val_loss: 0.7469 - val_mae: 0.6334 - val_rmse: 0.7027 - val_smape: 1.2385

Epoch 70/128

1915/1915 - 18s - 10ms/step - ia: 0.4008 - loss: 0.7977 - mae: 0.6546 - rmse: 0.8614 - smape: 1.2626 - val_ia: 0.2502 - val_loss: 0.7457 - val_mae: 0.6309 - val_rmse: 0.7002 - val_smape: 1.2342

Epoch 71/128

1915/1915 - 21s - 11ms/step - ia: 0.3999 - loss: 0.7943 - mae: 0.6541 - rmse: 0.8599 - smape: 1.2648 - val_ia: 0.2505 - val_loss: 0.7451 - val_mae: 0.6313 - val_rmse: 0.7008 - val_smape: 1.2328

Epoch 72/128

1915/1915 - 19s - 10ms/step - ia: 0.4011 - loss: 0.7962 - mae: 0.6549 - rmse: 0.8607 - smape: 1.2636 - val_ia: 0.2493 - val_loss: 0.7450 - val_mae: 0.6331 - val_rmse: 0.7020 - val_smape: 1.2445

Epoch 73/128

1915/1915 - 19s - 10ms/step - ia: 0.4020 - loss: 0.7932 - mae: 0.6533 - rmse: 0.8576 - smape: 1.2632 - val_ia: 0.2479 - val_loss: 0.7476 - val_mae: 0.6373 - val_rmse: 0.7061 - val_smape: 1.2546

Epoch 74/128

1915/1915 - 17s - 9ms/step - ia: 0.4020 - loss: 0.7930 - mae: 0.6533 - rmse: 0.8590 - smape: 1.2631 - val_ia: 0.2469 - val_loss: 0.7501 - val_mae: 0.6399 - val_rmse: 0.7088 - val_smape: 1.2582

Epoch 75/128

1915/1915 - 19s - 10ms/step - ia: 0.4005 - loss: 0.7959 - mae: 0.6545 - rmse: 0.8594 - smape: 1.2634 - val_ia: 0.2491 - val_loss: 0.7454 - val_mae: 0.6331 - val_rmse: 0.7022 - val_smape: 1.2424

Epoch 76/128

1915/1915 - 18s - 10ms/step - ia: 0.4007 - loss: 0.7958 - mae: 0.6544 - rmse: 0.8602 - smape: 1.2619 - val_ia: 0.2486 - val_loss: 0.7456 - val_mae: 0.6347 - val_rmse: 0.7036 - val_smape: 1.2498

Epoch 77/128

1915/1915 - 18s - 10ms/step - ia: 0.4010 - loss: 0.7926 - mae: 0.6526 - rmse: 0.8582 - smape: 1.2625 - val_ia: 0.2475 - val_loss: 0.7502 - val_mae: 0.6393 - val_rmse: 0.7086 - val_smape: 1.2521

Epoch 78/128

1915/1915 - 18s - 9ms/step - ia: 0.4033 - loss: 0.7925 - mae: 0.6531 - rmse: 0.8576 - smape: 1.2587 - val_ia: 0.2496 - val_loss: 0.7443 - val_mae: 0.6319 - val_rmse: 0.7010 - val_smape: 1.2393

Epoch 79/128

1915/1915 - 18s - 9ms/step - ia: 0.4040 - loss: 0.7939 - mae: 0.6523 - rmse: 0.8587 - smape: 1.2591 - val_ia: 0.2498 - val_loss: 0.7432 - val_mae: 0.6309 - val_rmse: 0.6999 - val_smape: 1.2391

Epoch 80/128

1915/1915 - 22s - 11ms/step - ia: 0.4040 - loss: 0.7922 - mae: 0.6517 - rmse: 0.8569 - smape: 1.2612 - val_ia: 0.2490 - val_loss: 0.7446 - val_mae: 0.6329 - val_rmse: 0.7020 - val_smape: 1.2433

Epoch 81/128

1915/1915 - 18s - 10ms/step - ia: 0.4022 - loss: 0.7929 - mae: 0.6530 - rmse: 0.8582 - smape: 1.2619 - val_ia: 0.2486 - val_loss: 0.7459 - val_mae: 0.6341 - val_rmse: 0.7033 - val_smape: 1.2438

Epoch 82/128

1915/1915 - 19s - 10ms/step - ia: 0.4038 - loss: 0.7901 - mae: 0.6517 - rmse: 0.8564 - smape: 1.2582 - val_ia: 0.2472 - val_loss: 0.7480 - val_mae: 0.6379 - val_rmse: 0.7069 - val_smape: 1.2543

Epoch 83/128

1915/1915 - 18s - 9ms/step - ia: 0.4044 - loss: 0.7904 - mae: 0.6518 - rmse: 0.8570 - smape: 1.2593 - val_ia: 0.2482 - val_loss: 0.7466 - val_mae: 0.6356 - val_rmse: 0.7049 - val_smape: 1.2464

Epoch 84/128

1915/1915 - 18s - 9ms/step - ia: 0.4027 - loss: 0.7936 - mae: 0.6526 - rmse: 0.8588 - smape: 1.2600 - val_ia: 0.2469 - val_loss: 0.7504 - val_mae: 0.6399 - val_rmse: 0.7092 - val_smape: 1.2535

Epoch 85/128

1915/1915 - 17s - 9ms/step - ia: 0.4042 - loss: 0.7903 - mae: 0.6519 - rmse: 0.8565 - smape: 1.2568 - val_ia: 0.2484 - val_loss: 0.7442 - val_mae: 0.6344 - val_rmse: 0.7032 - val_smape: 1.2485

Epoch 86/128

1915/1915 - 22s - 11ms/step - ia: 0.4041 - loss: 0.7889 - mae: 0.6505 - rmse: 0.8569 - smape: 1.2583 - val_ia: 0.2472 - val_loss: 0.7498 - val_mae: 0.6392 - val_rmse: 0.7085 - val_smape: 1.2512

Epoch 87/128

1915/1915 - 17s - 9ms/step - ia: 0.4047 - loss: 0.7888 - mae: 0.6505 - rmse: 0.8556 - smape: 1.2569 - val_ia: 0.2479 - val_loss: 0.7487 - val_mae: 0.6370 - val_rmse: 0.7066 - val_smape: 1.2438

Epoch 88/128

1915/1915 - 14s - 7ms/step - ia: 0.4074 - loss: 0.7886 - mae: 0.6508 - rmse: 0.8558 - smape: 1.2559 - val_ia: 0.2486 - val_loss: 0.7440 - val_mae: 0.6337 - val_rmse: 0.7027 - val_smape: 1.2456

Epoch 89/128

1915/1915 - 12s - 6ms/step - ia: 0.4063 - loss: 0.7884 - mae: 0.6498 - rmse: 0.8560 - smape: 1.2541 - val_ia: 0.2485 - val_loss: 0.7449 - val_mae: 0.6339 - val_rmse: 0.7032 - val_smape: 1.2441

Epoch 90/128

1915/1915 - 12s - 6ms/step - ia: 0.4041 - loss: 0.7880 - mae: 0.6502 - rmse: 0.8554 - smape: 1.2586 - val_ia: 0.2484 - val_loss: 0.7467 - val_mae: 0.6350 - val_rmse: 0.7046 - val_smape: 1.2412

Epoch 91/128

1915/1915 - 16s - 8ms/step - ia: 0.4050 - loss: 0.7863 - mae: 0.6500 - rmse: 0.8551 - smape: 1.2556 - val_ia: 0.2494 - val_loss: 0.7429 - val_mae: 0.6313 - val_rmse: 0.7007 - val_smape: 1.2379

Epoch 92/128

1915/1915 - 22s - 11ms/step - ia: 0.4059 - loss: 0.7872 - mae: 0.6497 - rmse: 0.8550 - smape: 1.2556 - val_ia: 0.2472 - val_loss: 0.7483 - val_mae: 0.6391 - val_rmse: 0.7083 - val_smape: 1.2540

Epoch 93/128

1915/1915 - 16s - 8ms/step - ia: 0.4084 - loss: 0.7867 - mae: 0.6497 - rmse: 0.8542 - smape: 1.2552 - val_ia: 0.2497 - val_loss: 0.7421 - val_mae: 0.6306 - val_rmse: 0.6998 - val_smape: 1.2360

Epoch 94/128

1915/1915 - 22s - 11ms/step - ia: 0.4087 - loss: 0.7839 - mae: 0.6488 - rmse: 0.8538 - smape: 1.2524 - val_ia: 0.2477 - val_loss: 0.7466 - val_mae: 0.6369 - val_rmse: 0.7061 - val_smape: 1.2489

Epoch 95/128

1915/1915 - 21s - 11ms/step - ia: 0.4071 - loss: 0.7844 - mae: 0.6488 - rmse: 0.8539 - smape: 1.2504 - val_ia: 0.2476 - val_loss: 0.7443 - val_mae: 0.6354 - val_rmse: 0.7042 - val_smape: 1.2515

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 79s - 21ms/step - ia: 0.3690 - loss: 0.8239 - mae: 0.6689 - rmse: 0.8503 - smape: 1.3174 - val_ia: 0.2033 - val_loss: 0.7577 - val_mae: 0.6395 - val_rmse: 0.6815 - val_smape: 1.2411

Epoch 2/128

3830/3830 - 45s - 12ms/step - ia: 0.4047 - loss: 0.7904 - mae: 0.6485 - rmse: 0.8312 - smape: 1.2393 - val_ia: 0.2039 - val_loss: 0.7606 - val_mae: 0.6370 - val_rmse: 0.6791 - val_smape: 1.2284

Epoch 3/128

3830/3830 - 45s - 12ms/step - ia: 0.4099 - loss: 0.7792 - mae: 0.6430 - rmse: 0.8265 - smape: 1.2321 - val_ia: 0.2002 - val_loss: 0.7659 - val_mae: 0.6493 - val_rmse: 0.6908 - val_smape: 1.2777

Epoch 4/128

3830/3830 - 50s - 13ms/step - ia: 0.4171 - loss: 0.7682 - mae: 0.6382 - rmse: 0.8192 - smape: 1.2205 - val_ia: 0.2041 - val_loss: 0.7489 - val_mae: 0.6342 - val_rmse: 0.6756 - val_smape: 1.2409

Epoch 5/128

3830/3830 - 42s - 11ms/step - ia: 0.4223 - loss: 0.7602 - mae: 0.6351 - rmse: 0.8147 - smape: 1.2180 - val_ia: 0.2063 - val_loss: 0.7514 - val_mae: 0.6317 - val_rmse: 0.6735 - val_smape: 1.2226

Epoch 6/128

3830/3830 - 47s - 12ms/step - ia: 0.4239 - loss: 0.7534 - mae: 0.6313 - rmse: 0.8109 - smape: 1.2092 - val_ia: 0.2046 - val_loss: 0.7524 - val_mae: 0.6351 - val_rmse: 0.6771 - val_smape: 1.2340

Epoch 7/128

3830/3830 - 85s - 22ms/step - ia: 0.4284 - loss: 0.7468 - mae: 0.6286 - rmse: 0.8077 - smape: 1.2003 - val_ia: 0.2021 - val_loss: 0.7786 - val_mae: 0.6476 - val_rmse: 0.6896 - val_smape: 1.2535

Epoch 8/128

3830/3830 - 53s - 14ms/step - ia: 0.4307 - loss: 0.7378 - mae: 0.6258 - rmse: 0.8032 - smape: 1.2006 - val_ia: 0.2067 - val_loss: 0.7698 - val_mae: 0.6391 - val_rmse: 0.6824 - val_smape: 1.2204

Epoch 9/128

3830/3830 - 54s - 14ms/step - ia: 0.4370 - loss: 0.7303 - mae: 0.6216 - rmse: 0.7991 - smape: 1.1909 - val_ia: 0.2072 - val_loss: 0.7986 - val_mae: 0.6473 - val_rmse: 0.6919 - val_smape: 1.2194

Epoch 10/128

3830/3830 - 53s - 14ms/step - ia: 0.4381 - loss: 0.7244 - mae: 0.6190 - rmse: 0.7945 - smape: 1.1885 - val_ia: 0.2048 - val_loss: 0.7853 - val_mae: 0.6471 - val_rmse: 0.6905 - val_smape: 1.2397

Epoch 11/128

3830/3830 - 53s - 14ms/step - ia: 0.4409 - loss: 0.7165 - mae: 0.6163 - rmse: 0.7908 - smape: 1.1845 - val_ia: 0.2052 - val_loss: 0.7551 - val_mae: 0.6388 - val_rmse: 0.6822 - val_smape: 1.2548

Epoch 12/128

3830/3830 - 52s - 14ms/step - ia: 0.4445 - loss: 0.7093 - mae: 0.6132 - rmse: 0.7876 - smape: 1.1800 - val_ia: 0.2015 - val_loss: 0.7792 - val_mae: 0.6501 - val_rmse: 0.6926 - val_smape: 1.2708

Epoch 13/128

3830/3830 - 44s - 11ms/step - ia: 0.4453 - loss: 0.7027 - mae: 0.6107 - rmse: 0.7838 - smape: 1.1769 - val_ia: 0.2053 - val_loss: 0.7846 - val_mae: 0.6417 - val_rmse: 0.6859 - val_smape: 1.2292

Epoch 14/128

3830/3830 - 48s - 13ms/step - ia: 0.4490 - loss: 0.6936 - mae: 0.6070 - rmse: 0.7790 - smape: 1.1710 - val_ia: 0.2056 - val_loss: 0.8003 - val_mae: 0.6476 - val_rmse: 0.6934 - val_smape: 1.2334

Epoch 15/128

3830/3830 - 49s - 13ms/step - ia: 0.4541 - loss: 0.6839 - mae: 0.6041 - rmse: 0.7744 - smape: 1.1670 - val_ia: 0.2050 - val_loss: 0.8042 - val_mae: 0.6488 - val_rmse: 0.6943 - val_smape: 1.2514

Epoch 16/128

3830/3830 - 49s - 13ms/step - ia: 0.4541 - loss: 0.6764 - mae: 0.6017 - rmse: 0.7702 - smape: 1.1678 - val_ia: 0.2057 - val_loss: 0.7872 - val_mae: 0.6381 - val_rmse: 0.6817 - val_smape: 1.2608

Epoch 17/128

3830/3830 - 50s - 13ms/step - ia: 0.4574 - loss: 0.6700 - mae: 0.5981 - rmse: 0.7660 - smape: 1.1620 - val_ia: 0.2005 - val_loss: 0.9063 - val_mae: 0.6837 - val_rmse: 0.7316 - val_smape: 1.2702

Epoch 18/128

3830/3830 - 50s - 13ms/step - ia: 0.4596 - loss: 0.6634 - mae: 0.5959 - rmse: 0.7637 - smape: 1.1591 - val_ia: 0.2026 - val_loss: 0.8481 - val_mae: 0.6648 - val_rmse: 0.7120 - val_smape: 1.2700

Epoch 19/128

3830/3830 - 48s - 13ms/step - ia: 0.4619 - loss: 0.6587 - mae: 0.5942 - rmse: 0.7602 - smape: 1.1567 - val_ia: 0.2041 - val_loss: 0.8380 - val_mae: 0.6620 - val_rmse: 0.7084 - val_smape: 1.2649

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:18 1s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

Epoch 1/128

 82%|████████▏ | 41/50 [7:38:37<2:42:09, 1081.06s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 25s - 207ms/step - ia: 0.3398 - loss: 1.0679 - mae: 0.7694 - rmse: 1.0264 - smape: 1.3702 - val_ia: 0.3253 - val_loss: 0.7664 - val_mae: 0.6453 - val_rmse: 0.8060 - val_smape: 1.2829

Epoch 2/128

120/120 - 2s - 15ms/step - ia: 0.3671 - loss: 0.8927 - mae: 0.7027 - rmse: 0.9421 - smape: 1.3304 - val_ia: 0.3320 - val_loss: 0.7557 - val_mae: 0.6429 - val_rmse: 0.8026 - val_smape: 1.2712

Epoch 3/128

120/120 - 2s - 13ms/step - ia: 0.3772 - loss: 0.8538 - mae: 0.6838 - rmse: 0.9208 - smape: 1.3097 - val_ia: 0.3345 - val_loss: 0.7524 - val_mae: 0.6412 - val_rmse: 0.8011 - val_smape: 1.2627

Epoch 4/128

120/120 - 1s - 12ms/step - ia: 0.3828 - loss: 0.8313 - mae: 0.6726 - rmse: 0.9091 - smape: 1.2965 - val_ia: 0.3339 - val_loss: 0.7466 - val_mae: 0.6358 - val_rmse: 0.7961 - val_smape: 1.2615

Epoch 5/128

120/120 - 1s - 12ms/step - ia: 0.3886 - loss: 0.8177 - mae: 0.6651 - rmse: 0.9012 - smape: 1.2844 - val_ia: 0.3405 - val_loss: 0.7448 - val_mae: 0.6346 - val_rmse: 0.7962 - val_smape: 1.2500

Epoch 6/128

120/120 - 3s - 22ms/step - ia: 0.3903 - loss: 0.8140 - mae: 0.6633 - rmse: 0.9002 - smape: 1.2817 - val_ia: 0.3462 - val_loss: 0.7453 - val_mae: 0.6370 - val_rmse: 0.7989 - val_smape: 1.2505

Epoch 7/128

120/120 - 1s - 12ms/step - ia: 0.3957 - loss: 0.8062 - mae: 0.6585 - rmse: 0.8953 - smape: 1.2769 - val_ia: 0.3462 - val_loss: 0.7475 - val_mae: 0.6384 - val_rmse: 0.8005 - val_smape: 1.2516

Epoch 8/128

120/120 - 2s - 13ms/step - ia: 0.3978 - loss: 0.8044 - mae: 0.6584 - rmse: 0.8948 - smape: 1.2736 - val_ia: 0.3504 - val_loss: 0.7474 - val_mae: 0.6392 - val_rmse: 0.8021 - val_smape: 1.2550

Epoch 9/128

120/120 - 1s - 12ms/step - ia: 0.4043 - loss: 0.7962 - mae: 0.6542 - rmse: 0.8893 - smape: 1.2614 - val_ia: 0.3569 - val_loss: 0.7482 - val_mae: 0.6364 - val_rmse: 0.8015 - val_smape: 1.2349

Epoch 10/128

120/120 - 1s - 12ms/step - ia: 0.4083 - loss: 0.7913 - mae: 0.6520 - rmse: 0.8872 - smape: 1.2577 - val_ia: 0.3662 - val_loss: 0.7636 - val_mae: 0.6429 - val_rmse: 0.8119 - val_smape: 1.2429

Epoch 11/128

120/120 - 2s - 13ms/step - ia: 0.4068 - loss: 0.7872 - mae: 0.6507 - rmse: 0.8846 - smape: 1.2608 - val_ia: 0.3638 - val_loss: 0.7559 - val_mae: 0.6387 - val_rmse: 0.8064 - val_smape: 1.2324

Epoch 12/128

120/120 - 1s - 11ms/step - ia: 0.4143 - loss: 0.7839 - mae: 0.6481 - rmse: 0.8830 - smape: 1.2492 - val_ia: 0.3614 - val_loss: 0.7738 - val_mae: 0.6507 - val_rmse: 0.8191 - val_smape: 1.2626

Epoch 13/128

120/120 - 2s - 21ms/step - ia: 0.4143 - loss: 0.7798 - mae: 0.6474 - rmse: 0.8800 - smape: 1.2550 - val_ia: 0.3641 - val_loss: 0.7621 - val_mae: 0.6380 - val_rmse: 0.8078 - val_smape: 1.2295

Epoch 14/128

120/120 - 1s - 11ms/step - ia: 0.4143 - loss: 0.7787 - mae: 0.6468 - rmse: 0.8789 - smape: 1.2517 - val_ia: 0.3612 - val_loss: 0.7520 - val_mae: 0.6362 - val_rmse: 0.8027 - val_smape: 1.2304

Epoch 15/128

120/120 - 1s - 9ms/step - ia: 0.4178 - loss: 0.7737 - mae: 0.6446 - rmse: 0.8772 - smape: 1.2467 - val_ia: 0.3594 - val_loss: 0.7620 - val_mae: 0.6449 - val_rmse: 0.8108 - val_smape: 1.2575

Epoch 16/128

120/120 - 1s - 11ms/step - ia: 0.4156 - loss: 0.7760 - mae: 0.6450 - rmse: 0.8781 - smape: 1.2483 - val_ia: 0.3725 - val_loss: 0.7768 - val_mae: 0.6461 - val_rmse: 0.8195 - val_smape: 1.2361

Epoch 17/128

120/120 - 1s - 11ms/step - ia: 0.4182 - loss: 0.7723 - mae: 0.6433 - rmse: 0.8761 - smape: 1.2456 - val_ia: 0.3679 - val_loss: 0.7771 - val_mae: 0.6421 - val_rmse: 0.8156 - val_smape: 1.2173

Epoch 18/128

120/120 - 1s - 11ms/step - ia: 0.4205 - loss: 0.7695 - mae: 0.6422 - rmse: 0.8754 - smape: 1.2433 - val_ia: 0.3587 - val_loss: 0.7570 - val_mae: 0.6383 - val_rmse: 0.8054 - val_smape: 1.2465

Epoch 19/128

120/120 - 3s - 22ms/step - ia: 0.4213 - loss: 0.7685 - mae: 0.6421 - rmse: 0.8733 - smape: 1.2402 - val_ia: 0.3609 - val_loss: 0.7637 - val_mae: 0.6399 - val_rmse: 0.8087 - val_smape: 1.2349

Epoch 20/128

120/120 - 3s - 22ms/step - ia: 0.4202 - loss: 0.7673 - mae: 0.6416 - rmse: 0.8732 - smape: 1.2426 - val_ia: 0.3650 - val_loss: 0.7669 - val_mae: 0.6394 - val_rmse: 0.8099 - val_smape: 1.2299

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:28 657ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 84%|████████▍ | 42/50 [7:39:37<1:43:17, 774.72s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 49s - 51ms/step - ia: 0.3122 - loss: 0.8847 - mae: 0.7001 - rmse: 0.9211 - smape: 1.4110 - val_ia: 0.2564 - val_loss: 0.7841 - val_mae: 0.6510 - val_rmse: 0.7426 - val_smape: 1.2983

Epoch 2/128

958/958 - 21s - 22ms/step - ia: 0.3684 - loss: 0.8526 - mae: 0.6819 - rmse: 0.9054 - smape: 1.3141 - val_ia: 0.2568 - val_loss: 0.7765 - val_mae: 0.6472 - val_rmse: 0.7408 - val_smape: 1.2700

Epoch 3/128

958/958 - 18s - 18ms/step - ia: 0.3744 - loss: 0.8450 - mae: 0.6790 - rmse: 0.9012 - smape: 1.3075 - val_ia: 0.2552 - val_loss: 0.7754 - val_mae: 0.6483 - val_rmse: 0.7413 - val_smape: 1.2829

Epoch 4/128

958/958 - 21s - 22ms/step - ia: 0.3738 - loss: 0.8449 - mae: 0.6780 - rmse: 0.9018 - smape: 1.3058 - val_ia: 0.2565 - val_loss: 0.7679 - val_mae: 0.6457 - val_rmse: 0.7389 - val_smape: 1.2780

Epoch 5/128

958/958 - 22s - 23ms/step - ia: 0.3733 - loss: 0.8402 - mae: 0.6765 - rmse: 0.8986 - smape: 1.3082 - val_ia: 0.2563 - val_loss: 0.7669 - val_mae: 0.6449 - val_rmse: 0.7386 - val_smape: 1.2726

Epoch 6/128

958/958 - 38s - 40ms/step - ia: 0.3782 - loss: 0.8369 - mae: 0.6743 - rmse: 0.8977 - smape: 1.3008 - val_ia: 0.2572 - val_loss: 0.7615 - val_mae: 0.6431 - val_rmse: 0.7360 - val_smape: 1.2745

Epoch 7/128

958/958 - 19s - 20ms/step - ia: 0.3744 - loss: 0.8364 - mae: 0.6749 - rmse: 0.8981 - smape: 1.3074 - val_ia: 0.2579 - val_loss: 0.7607 - val_mae: 0.6420 - val_rmse: 0.7356 - val_smape: 1.2641

Epoch 8/128

958/958 - 22s - 22ms/step - ia: 0.3770 - loss: 0.8340 - mae: 0.6740 - rmse: 0.8957 - smape: 1.3029 - val_ia: 0.2571 - val_loss: 0.7610 - val_mae: 0.6430 - val_rmse: 0.7366 - val_smape: 1.2714

Epoch 9/128

958/958 - 23s - 24ms/step - ia: 0.3786 - loss: 0.8291 - mae: 0.6712 - rmse: 0.8937 - smape: 1.2977 - val_ia: 0.2577 - val_loss: 0.7589 - val_mae: 0.6416 - val_rmse: 0.7354 - val_smape: 1.2649

Epoch 10/128

958/958 - 22s - 23ms/step - ia: 0.3815 - loss: 0.8290 - mae: 0.6708 - rmse: 0.8926 - smape: 1.2931 - val_ia: 0.2570 - val_loss: 0.7596 - val_mae: 0.6419 - val_rmse: 0.7356 - val_smape: 1.2673

Epoch 11/128

958/958 - 22s - 23ms/step - ia: 0.3826 - loss: 0.8264 - mae: 0.6689 - rmse: 0.8911 - smape: 1.2927 - val_ia: 0.2579 - val_loss: 0.7563 - val_mae: 0.6404 - val_rmse: 0.7344 - val_smape: 1.2622

Epoch 12/128

958/958 - 22s - 23ms/step - ia: 0.3801 - loss: 0.8263 - mae: 0.6697 - rmse: 0.8910 - smape: 1.2964 - val_ia: 0.2587 - val_loss: 0.7554 - val_mae: 0.6391 - val_rmse: 0.7336 - val_smape: 1.2522

Epoch 13/128

958/958 - 21s - 22ms/step - ia: 0.3842 - loss: 0.8254 - mae: 0.6690 - rmse: 0.8908 - smape: 1.2925 - val_ia: 0.2579 - val_loss: 0.7567 - val_mae: 0.6405 - val_rmse: 0.7350 - val_smape: 1.2588

Epoch 14/128

958/958 - 22s - 23ms/step - ia: 0.3844 - loss: 0.8211 - mae: 0.6671 - rmse: 0.8878 - smape: 1.2922 - val_ia: 0.2582 - val_loss: 0.7546 - val_mae: 0.6395 - val_rmse: 0.7340 - val_smape: 1.2556

Epoch 15/128

958/958 - 41s - 43ms/step - ia: 0.3877 - loss: 0.8190 - mae: 0.6654 - rmse: 0.8875 - smape: 1.2856 - val_ia: 0.2580 - val_loss: 0.7527 - val_mae: 0.6390 - val_rmse: 0.7332 - val_smape: 1.2589

Epoch 16/128

958/958 - 41s - 42ms/step - ia: 0.3861 - loss: 0.8198 - mae: 0.6658 - rmse: 0.8868 - smape: 1.2872 - val_ia: 0.2598 - val_loss: 0.7510 - val_mae: 0.6382 - val_rmse: 0.7329 - val_smape: 1.2482

Epoch 17/128

958/958 - 40s - 42ms/step - ia: 0.3898 - loss: 0.8181 - mae: 0.6658 - rmse: 0.8868 - smape: 1.2849 - val_ia: 0.2581 - val_loss: 0.7505 - val_mae: 0.6387 - val_rmse: 0.7327 - val_smape: 1.2595

Epoch 18/128

958/958 - 21s - 22ms/step - ia: 0.3887 - loss: 0.8164 - mae: 0.6643 - rmse: 0.8865 - smape: 1.2823 - val_ia: 0.2585 - val_loss: 0.7484 - val_mae: 0.6377 - val_rmse: 0.7316 - val_smape: 1.2566

Epoch 19/128

958/958 - 20s - 21ms/step - ia: 0.3896 - loss: 0.8152 - mae: 0.6639 - rmse: 0.8843 - smape: 1.2805 - val_ia: 0.2583 - val_loss: 0.7482 - val_mae: 0.6385 - val_rmse: 0.7324 - val_smape: 1.2601

Epoch 20/128

958/958 - 16s - 17ms/step - ia: 0.3876 - loss: 0.8133 - mae: 0.6634 - rmse: 0.8848 - smape: 1.2846 - val_ia: 0.2591 - val_loss: 0.7472 - val_mae: 0.6361 - val_rmse: 0.7310 - val_smape: 1.2462

Epoch 21/128

958/958 - 18s - 19ms/step - ia: 0.3930 - loss: 0.8132 - mae: 0.6623 - rmse: 0.8849 - smape: 1.2772 - val_ia: 0.2590 - val_loss: 0.7459 - val_mae: 0.6375 - val_rmse: 0.7319 - val_smape: 1.2550

Epoch 22/128

958/958 - 21s - 22ms/step - ia: 0.3895 - loss: 0.8118 - mae: 0.6630 - rmse: 0.8825 - smape: 1.2821 - val_ia: 0.2597 - val_loss: 0.7453 - val_mae: 0.6356 - val_rmse: 0.7309 - val_smape: 1.2428

Epoch 23/128

958/958 - 21s - 22ms/step - ia: 0.3949 - loss: 0.8109 - mae: 0.6623 - rmse: 0.8821 - smape: 1.2768 - val_ia: 0.2587 - val_loss: 0.7449 - val_mae: 0.6373 - val_rmse: 0.7317 - val_smape: 1.2568

Epoch 24/128

958/958 - 21s - 22ms/step - ia: 0.3940 - loss: 0.8102 - mae: 0.6609 - rmse: 0.8815 - smape: 1.2804 - val_ia: 0.2594 - val_loss: 0.7443 - val_mae: 0.6364 - val_rmse: 0.7316 - val_smape: 1.2490

Epoch 25/128

958/958 - 40s - 42ms/step - ia: 0.3941 - loss: 0.8096 - mae: 0.6612 - rmse: 0.8822 - smape: 1.2766 - val_ia: 0.2594 - val_loss: 0.7444 - val_mae: 0.6375 - val_rmse: 0.7325 - val_smape: 1.2556

Epoch 26/128

958/958 - 22s - 22ms/step - ia: 0.3945 - loss: 0.8081 - mae: 0.6611 - rmse: 0.8805 - smape: 1.2792 - val_ia: 0.2589 - val_loss: 0.7472 - val_mae: 0.6375 - val_rmse: 0.7329 - val_smape: 1.2502

Epoch 27/128

958/958 - 21s - 21ms/step - ia: 0.3955 - loss: 0.8074 - mae: 0.6599 - rmse: 0.8802 - smape: 1.2746 - val_ia: 0.2588 - val_loss: 0.7485 - val_mae: 0.6383 - val_rmse: 0.7341 - val_smape: 1.2535

Epoch 28/128

958/958 - 19s - 20ms/step - ia: 0.3970 - loss: 0.8105 - mae: 0.6609 - rmse: 0.8820 - smape: 1.2751 - val_ia: 0.2590 - val_loss: 0.7434 - val_mae: 0.6379 - val_rmse: 0.7325 - val_smape: 1.2630

Epoch 29/128

958/958 - 20s - 21ms/step - ia: 0.3957 - loss: 0.8050 - mae: 0.6594 - rmse: 0.8802 - smape: 1.2766 - val_ia: 0.2589 - val_loss: 0.7455 - val_mae: 0.6369 - val_rmse: 0.7322 - val_smape: 1.2520

Epoch 30/128

958/958 - 19s - 20ms/step - ia: 0.3987 - loss: 0.8055 - mae: 0.6582 - rmse: 0.8796 - smape: 1.2693 - val_ia: 0.2594 - val_loss: 0.7437 - val_mae: 0.6377 - val_rmse: 0.7327 - val_smape: 1.2579

Epoch 31/128

958/958 - 18s - 19ms/step - ia: 0.3966 - loss: 0.8076 - mae: 0.6596 - rmse: 0.8797 - smape: 1.2720 - val_ia: 0.2597 - val_loss: 0.7426 - val_mae: 0.6372 - val_rmse: 0.7323 - val_smape: 1.2601

Epoch 32/128

958/958 - 17s - 18ms/step - ia: 0.3973 - loss: 0.8026 - mae: 0.6577 - rmse: 0.8777 - smape: 1.2727 - val_ia: 0.2594 - val_loss: 0.7487 - val_mae: 0.6381 - val_rmse: 0.7344 - val_smape: 1.2522

Epoch 33/128

958/958 - 21s - 22ms/step - ia: 0.4005 - loss: 0.8023 - mae: 0.6573 - rmse: 0.8776 - smape: 1.2667 - val_ia: 0.2604 - val_loss: 0.7454 - val_mae: 0.6366 - val_rmse: 0.7328 - val_smape: 1.2475

Epoch 34/128

958/958 - 23s - 24ms/step - ia: 0.4005 - loss: 0.8014 - mae: 0.6567 - rmse: 0.8770 - smape: 1.2683 - val_ia: 0.2597 - val_loss: 0.7493 - val_mae: 0.6389 - val_rmse: 0.7352 - val_smape: 1.2544

Epoch 35/128

958/958 - 22s - 23ms/step - ia: 0.4015 - loss: 0.8029 - mae: 0.6574 - rmse: 0.8785 - smape: 1.2671 - val_ia: 0.2606 - val_loss: 0.7429 - val_mae: 0.6372 - val_rmse: 0.7326 - val_smape: 1.2570

Epoch 36/128

958/958 - 21s - 22ms/step - ia: 0.4005 - loss: 0.8003 - mae: 0.6562 - rmse: 0.8766 - smape: 1.2681 - val_ia: 0.2610 - val_loss: 0.7449 - val_mae: 0.6365 - val_rmse: 0.7327 - val_smape: 1.2486

Epoch 37/128

958/958 - 17s - 17ms/step - ia: 0.4037 - loss: 0.7995 - mae: 0.6552 - rmse: 0.8765 - smape: 1.2653 - val_ia: 0.2615 - val_loss: 0.7400 - val_mae: 0.6359 - val_rmse: 0.7311 - val_smape: 1.2543

Epoch 38/128

958/958 - 16s - 17ms/step - ia: 0.4006 - loss: 0.7986 - mae: 0.6554 - rmse: 0.8753 - smape: 1.2694 - val_ia: 0.2617 - val_loss: 0.7460 - val_mae: 0.6362 - val_rmse: 0.7325 - val_smape: 1.2430

Epoch 39/128

958/958 - 21s - 22ms/step - ia: 0.4025 - loss: 0.8007 - mae: 0.6566 - rmse: 0.8767 - smape: 1.2657 - val_ia: 0.2617 - val_loss: 0.7460 - val_mae: 0.6383 - val_rmse: 0.7344 - val_smape: 1.2562

Epoch 40/128

958/958 - 21s - 22ms/step - ia: 0.4028 - loss: 0.7972 - mae: 0.6549 - rmse: 0.8752 - smape: 1.2662 - val_ia: 0.2614 - val_loss: 0.7501 - val_mae: 0.6395 - val_rmse: 0.7361 - val_smape: 1.2578

Epoch 41/128

958/958 - 21s - 22ms/step - ia: 0.4029 - loss: 0.7995 - mae: 0.6555 - rmse: 0.8775 - smape: 1.2651 - val_ia: 0.2617 - val_loss: 0.7452 - val_mae: 0.6369 - val_rmse: 0.7332 - val_smape: 1.2532

Epoch 42/128

958/958 - 20s - 20ms/step - ia: 0.4030 - loss: 0.7987 - mae: 0.6550 - rmse: 0.8761 - smape: 1.2651 - val_ia: 0.2623 - val_loss: 0.7435 - val_mae: 0.6359 - val_rmse: 0.7320 - val_smape: 1.2509

Epoch 43/128

958/958 - 19s - 20ms/step - ia: 0.4036 - loss: 0.7979 - mae: 0.6544 - rmse: 0.8743 - smape: 1.2652 - val_ia: 0.2620 - val_loss: 0.7450 - val_mae: 0.6369 - val_rmse: 0.7330 - val_smape: 1.2558

Epoch 44/128

958/958 - 19s - 19ms/step - ia: 0.4034 - loss: 0.7977 - mae: 0.6545 - rmse: 0.8748 - smape: 1.2650 - val_ia: 0.2629 - val_loss: 0.7509 - val_mae: 0.6368 - val_rmse: 0.7339 - val_smape: 1.2399

Epoch 45/128

958/958 - 18s - 19ms/step - ia: 0.4062 - loss: 0.7938 - mae: 0.6527 - rmse: 0.8742 - smape: 1.2582 - val_ia: 0.2628 - val_loss: 0.7477 - val_mae: 0.6376 - val_rmse: 0.7340 - val_smape: 1.2522

Epoch 46/128

958/958 - 22s - 23ms/step - ia: 0.4048 - loss: 0.7953 - mae: 0.6532 - rmse: 0.8729 - smape: 1.2604 - val_ia: 0.2630 - val_loss: 0.7475 - val_mae: 0.6371 - val_rmse: 0.7335 - val_smape: 1.2508

Epoch 47/128

958/958 - 22s - 23ms/step - ia: 0.4052 - loss: 0.7948 - mae: 0.6535 - rmse: 0.8752 - smape: 1.2614 - val_ia: 0.2626 - val_loss: 0.7459 - val_mae: 0.6388 - val_rmse: 0.7344 - val_smape: 1.2653

Epoch 48/128

958/958 - 18s - 19ms/step - ia: 0.4037 - loss: 0.7941 - mae: 0.6541 - rmse: 0.8727 - smape: 1.2656 - val_ia: 0.2637 - val_loss: 0.7460 - val_mae: 0.6360 - val_rmse: 0.7325 - val_smape: 1.2475

Epoch 49/128

958/958 - 18s - 18ms/step - ia: 0.4055 - loss: 0.7959 - mae: 0.6530 - rmse: 0.8742 - smape: 1.2603 - val_ia: 0.2636 - val_loss: 0.7470 - val_mae: 0.6366 - val_rmse: 0.7330 - val_smape: 1.2492

Epoch 50/128

958/958 - 22s - 23ms/step - ia: 0.4043 - loss: 0.7952 - mae: 0.6535 - rmse: 0.8744 - smape: 1.2617 - val_ia: 0.2635 - val_loss: 0.7487 - val_mae: 0.6371 - val_rmse: 0.7335 - val_smape: 1.2498

Epoch 51/128

958/958 - 20s - 21ms/step - ia: 0.4049 - loss: 0.7959 - mae: 0.6534 - rmse: 0.8743 - smape: 1.2616 - val_ia: 0.2639 - val_loss: 0.7431 - val_mae: 0.6366 - val_rmse: 0.7326 - val_smape: 1.2583

Epoch 52/128

958/958 - 19s - 20ms/step - ia: 0.4053 - loss: 0.7935 - mae: 0.6525 - rmse: 0.8736 - smape: 1.2615 - val_ia: 0.2647 - val_loss: 0.7441 - val_mae: 0.6355 - val_rmse: 0.7320 - val_smape: 1.2473

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:29 2s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step

 86%|████████▌ | 43/50 [7:59:21<1:44:42, 897.49s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

240/240 - 16s - 66ms/step - ia: 0.3247 - loss: 1.1024 - mae: 0.7848 - rmse: 1.0446 - smape: 1.3982 - val_ia: 0.3022 - val_loss: 0.9316 - val_mae: 0.7410 - val_rmse: 0.8921 - val_smape: 1.4596

Epoch 2/256

240/240 - 2s - 9ms/step - ia: 0.3217 - loss: 1.1057 - mae: 0.7858 - rmse: 1.0467 - smape: 1.4034 - val_ia: 0.3021 - val_loss: 0.9271 - val_mae: 0.7389 - val_rmse: 0.8896 - val_smape: 1.4585

Epoch 3/256

240/240 - 2s - 9ms/step - ia: 0.3269 - loss: 1.1002 - mae: 0.7829 - rmse: 1.0438 - smape: 1.3945 - val_ia: 0.3020 - val_loss: 0.9228 - val_mae: 0.7369 - val_rmse: 0.8871 - val_smape: 1.4572

Epoch 4/256

240/240 - 2s - 8ms/step - ia: 0.3271 - loss: 1.0915 - mae: 0.7785 - rmse: 1.0391 - smape: 1.3918 - val_ia: 0.3020 - val_loss: 0.9188 - val_mae: 0.7350 - val_rmse: 0.8848 - val_smape: 1.4559

Epoch 5/256

240/240 - 3s - 12ms/step - ia: 0.3239 - loss: 1.0858 - mae: 0.7788 - rmse: 1.0376 - smape: 1.3989 - val_ia: 0.3019 - val_loss: 0.9151 - val_mae: 0.7333 - val_rmse: 0.8827 - val_smape: 1.4544

Epoch 6/256

240/240 - 2s - 8ms/step - ia: 0.3278 - loss: 1.0772 - mae: 0.7765 - rmse: 1.0328 - smape: 1.3950 - val_ia: 0.3019 - val_loss: 0.9115 - val_mae: 0.7316 - val_rmse: 0.8806 - val_smape: 1.4530

Epoch 7/256

240/240 - 2s - 7ms/step - ia: 0.3252 - loss: 1.0727 - mae: 0.7753 - rmse: 1.0303 - smape: 1.3987 - val_ia: 0.3018 - val_loss: 0.9081 - val_mae: 0.7299 - val_rmse: 0.8786 - val_smape: 1.4516

Epoch 8/256

240/240 - 2s - 7ms/step - ia: 0.3256 - loss: 1.0712 - mae: 0.7738 - rmse: 1.0284 - smape: 1.3995 - val_ia: 0.3017 - val_loss: 0.9048 - val_mae: 0.7283 - val_rmse: 0.8767 - val_smape: 1.4502

Epoch 9/256

240/240 - 2s - 7ms/step - ia: 0.3262 - loss: 1.0679 - mae: 0.7738 - rmse: 1.0284 - smape: 1.3983 - val_ia: 0.3017 - val_loss: 0.9017 - val_mae: 0.7268 - val_rmse: 0.8749 - val_smape: 1.4489

Epoch 10/256

240/240 - 2s - 7ms/step - ia: 0.3249 - loss: 1.0698 - mae: 0.7730 - rmse: 1.0288 - smape: 1.3984 - val_ia: 0.3016 - val_loss: 0.8985 - val_mae: 0.7253 - val_rmse: 0.8730 - val_smape: 1.4474

Epoch 11/256

240/240 - 1s - 6ms/step - ia: 0.3267 - loss: 1.0631 - mae: 0.7703 - rmse: 1.0257 - smape: 1.3965 - val_ia: 0.3015 - val_loss: 0.8956 - val_mae: 0.7239 - val_rmse: 0.8714 - val_smape: 1.4463

Epoch 12/256

240/240 - 1s - 6ms/step - ia: 0.3258 - loss: 1.0608 - mae: 0.7689 - rmse: 1.0245 - smape: 1.3980 - val_ia: 0.3015 - val_loss: 0.8928 - val_mae: 0.7225 - val_rmse: 0.8697 - val_smape: 1.4449

Epoch 13/256

240/240 - 2s - 6ms/step - ia: 0.3251 - loss: 1.0583 - mae: 0.7691 - rmse: 1.0250 - smape: 1.4006 - val_ia: 0.3014 - val_loss: 0.8902 - val_mae: 0.7213 - val_rmse: 0.8682 - val_smape: 1.4437

Epoch 14/256

240/240 - 1s - 6ms/step - ia: 0.3309 - loss: 1.0464 - mae: 0.7630 - rmse: 1.0176 - smape: 1.3908 - val_ia: 0.3014 - val_loss: 0.8876 - val_mae: 0.7200 - val_rmse: 0.8666 - val_smape: 1.4423

Epoch 15/256

240/240 - 1s - 6ms/step - ia: 0.3275 - loss: 1.0438 - mae: 0.7643 - rmse: 1.0168 - smape: 1.3976 - val_ia: 0.3014 - val_loss: 0.8851 - val_mae: 0.7187 - val_rmse: 0.8652 - val_smape: 1.4409

Epoch 16/256

240/240 - 1s - 6ms/step - ia: 0.3276 - loss: 1.0419 - mae: 0.7628 - rmse: 1.0148 - smape: 1.3942 - val_ia: 0.3013 - val_loss: 0.8826 - val_mae: 0.7175 - val_rmse: 0.8637 - val_smape: 1.4396

Epoch 17/256

240/240 - 1s - 6ms/step - ia: 0.3260 - loss: 1.0425 - mae: 0.7646 - rmse: 1.0149 - smape: 1.3985 - val_ia: 0.3013 - val_loss: 0.8801 - val_mae: 0.7162 - val_rmse: 0.8622 - val_smape: 1.4382

Epoch 18/256

240/240 - 1s - 6ms/step - ia: 0.3253 - loss: 1.0425 - mae: 0.7642 - rmse: 1.0165 - smape: 1.4009 - val_ia: 0.3012 - val_loss: 0.8778 - val_mae: 0.7151 - val_rmse: 0.8608 - val_smape: 1.4369

Epoch 19/256

240/240 - 1s - 6ms/step - ia: 0.3254 - loss: 1.0400 - mae: 0.7630 - rmse: 1.0149 - smape: 1.3990 - val_ia: 0.3012 - val_loss: 0.8756 - val_mae: 0.7140 - val_rmse: 0.8595 - val_smape: 1.4355

Epoch 20/256

240/240 - 1s - 6ms/step - ia: 0.3262 - loss: 1.0313 - mae: 0.7595 - rmse: 1.0108 - smape: 1.3974 - val_ia: 0.3012 - val_loss: 0.8734 - val_mae: 0.7129 - val_rmse: 0.8582 - val_smape: 1.4342

Epoch 21/256

240/240 - 1s - 6ms/step - ia: 0.3268 - loss: 1.0348 - mae: 0.7589 - rmse: 1.0112 - smape: 1.3982 - val_ia: 0.3011 - val_loss: 0.8713 - val_mae: 0.7118 - val_rmse: 0.8569 - val_smape: 1.4330

Epoch 22/256

240/240 - 1s - 6ms/step - ia: 0.3261 - loss: 1.0309 - mae: 0.7582 - rmse: 1.0102 - smape: 1.3996 - val_ia: 0.3011 - val_loss: 0.8692 - val_mae: 0.7108 - val_rmse: 0.8557 - val_smape: 1.4316

Epoch 23/256

240/240 - 1s - 6ms/step - ia: 0.3293 - loss: 1.0194 - mae: 0.7547 - rmse: 1.0050 - smape: 1.3916 - val_ia: 0.3011 - val_loss: 0.8672 - val_mae: 0.7098 - val_rmse: 0.8545 - val_smape: 1.4304

Epoch 24/256

240/240 - 1s - 6ms/step - ia: 0.3285 - loss: 1.0149 - mae: 0.7537 - rmse: 1.0029 - smape: 1.3962 - val_ia: 0.3010 - val_loss: 0.8652 - val_mae: 0.7088 - val_rmse: 0.8533 - val_smape: 1.4294

Epoch 25/256

240/240 - 1s - 6ms/step - ia: 0.3265 - loss: 1.0271 - mae: 0.7550 - rmse: 1.0071 - smape: 1.3970 - val_ia: 0.3010 - val_loss: 0.8634 - val_mae: 0.7078 - val_rmse: 0.8522 - val_smape: 1.4283

Epoch 26/256

240/240 - 1s - 6ms/step - ia: 0.3282 - loss: 1.0060 - mae: 0.7518 - rmse: 0.9985 - smape: 1.3976 - val_ia: 0.3010 - val_loss: 0.8615 - val_mae: 0.7069 - val_rmse: 0.8511 - val_smape: 1.4272

Epoch 27/256

240/240 - 1s - 6ms/step - ia: 0.3274 - loss: 1.0071 - mae: 0.7503 - rmse: 0.9985 - smape: 1.3943 - val_ia: 0.3010 - val_loss: 0.8597 - val_mae: 0.7060 - val_rmse: 0.8500 - val_smape: 1.4262

Epoch 28/256

240/240 - 1s - 5ms/step - ia: 0.3250 - loss: 1.0154 - mae: 0.7536 - rmse: 1.0030 - smape: 1.4005 - val_ia: 0.3009 - val_loss: 0.8579 - val_mae: 0.7051 - val_rmse: 0.8490 - val_smape: 1.4251

Epoch 29/256

240/240 - 1s - 5ms/step - ia: 0.3293 - loss: 1.0026 - mae: 0.7494 - rmse: 0.9960 - smape: 1.3952 - val_ia: 0.3009 - val_loss: 0.8561 - val_mae: 0.7042 - val_rmse: 0.8479 - val_smape: 1.4240

Epoch 30/256

240/240 - 1s - 6ms/step - ia: 0.3276 - loss: 1.0038 - mae: 0.7487 - rmse: 0.9965 - smape: 1.3955 - val_ia: 0.3009 - val_loss: 0.8543 - val_mae: 0.7032 - val_rmse: 0.8468 - val_smape: 1.4229

Epoch 31/256

240/240 - 1s - 6ms/step - ia: 0.3281 - loss: 0.9972 - mae: 0.7466 - rmse: 0.9934 - smape: 1.3965 - val_ia: 0.3009 - val_loss: 0.8527 - val_mae: 0.7024 - val_rmse: 0.8458 - val_smape: 1.4219

Epoch 32/256

240/240 - 1s - 6ms/step - ia: 0.3295 - loss: 0.9917 - mae: 0.7453 - rmse: 0.9903 - smape: 1.3946 - val_ia: 0.3009 - val_loss: 0.8511 - val_mae: 0.7015 - val_rmse: 0.8448 - val_smape: 1.4210

Epoch 33/256

240/240 - 2s - 8ms/step - ia: 0.3270 - loss: 1.0072 - mae: 0.7472 - rmse: 0.9978 - smape: 1.3947 - val_ia: 0.3009 - val_loss: 0.8495 - val_mae: 0.7007 - val_rmse: 0.8438 - val_smape: 1.4200

Epoch 34/256

240/240 - 2s - 8ms/step - ia: 0.3267 - loss: 0.9982 - mae: 0.7466 - rmse: 0.9937 - smape: 1.3982 - val_ia: 0.3009 - val_loss: 0.8480 - val_mae: 0.6999 - val_rmse: 0.8429 - val_smape: 1.4190

Epoch 35/256

240/240 - 2s - 8ms/step - ia: 0.3298 - loss: 0.9951 - mae: 0.7442 - rmse: 0.9925 - smape: 1.3928 - val_ia: 0.3009 - val_loss: 0.8464 - val_mae: 0.6991 - val_rmse: 0.8419 - val_smape: 1.4179

Epoch 36/256

240/240 - 2s - 9ms/step - ia: 0.3294 - loss: 0.9826 - mae: 0.7413 - rmse: 0.9874 - smape: 1.3919 - val_ia: 0.3009 - val_loss: 0.8449 - val_mae: 0.6982 - val_rmse: 0.8410 - val_smape: 1.4169

Epoch 37/256

240/240 - 2s - 8ms/step - ia: 0.3293 - loss: 0.9848 - mae: 0.7404 - rmse: 0.9874 - smape: 1.3932 - val_ia: 0.3009 - val_loss: 0.8435 - val_mae: 0.6975 - val_rmse: 0.8402 - val_smape: 1.4160

Epoch 38/256

240/240 - 2s - 8ms/step - ia: 0.3284 - loss: 0.9844 - mae: 0.7406 - rmse: 0.9872 - smape: 1.3938 - val_ia: 0.3009 - val_loss: 0.8420 - val_mae: 0.6967 - val_rmse: 0.8392 - val_smape: 1.4151

Epoch 39/256

240/240 - 2s - 8ms/step - ia: 0.3306 - loss: 0.9847 - mae: 0.7392 - rmse: 0.9866 - smape: 1.3884 - val_ia: 0.3008 - val_loss: 0.8406 - val_mae: 0.6960 - val_rmse: 0.8384 - val_smape: 1.4143

Epoch 40/256

240/240 - 2s - 8ms/step - ia: 0.3291 - loss: 0.9831 - mae: 0.7401 - rmse: 0.9858 - smape: 1.3941 - val_ia: 0.3008 - val_loss: 0.8393 - val_mae: 0.6952 - val_rmse: 0.8376 - val_smape: 1.4135

Epoch 41/256

240/240 - 2s - 8ms/step - ia: 0.3287 - loss: 0.9763 - mae: 0.7388 - rmse: 0.9814 - smape: 1.3946 - val_ia: 0.3008 - val_loss: 0.8379 - val_mae: 0.6945 - val_rmse: 0.8367 - val_smape: 1.4126

Epoch 42/256

240/240 - 2s - 8ms/step - ia: 0.3301 - loss: 0.9701 - mae: 0.7363 - rmse: 0.9796 - smape: 1.3931 - val_ia: 0.3008 - val_loss: 0.8365 - val_mae: 0.6937 - val_rmse: 0.8358 - val_smape: 1.4116

Epoch 43/256

240/240 - 2s - 9ms/step - ia: 0.3298 - loss: 0.9661 - mae: 0.7364 - rmse: 0.9773 - smape: 1.3955 - val_ia: 0.3008 - val_loss: 0.8352 - val_mae: 0.6930 - val_rmse: 0.8350 - val_smape: 1.4108

Epoch 44/256

240/240 - 2s - 8ms/step - ia: 0.3312 - loss: 0.9710 - mae: 0.7352 - rmse: 0.9791 - smape: 1.3926 - val_ia: 0.3009 - val_loss: 0.8340 - val_mae: 0.6924 - val_rmse: 0.8343 - val_smape: 1.4099

Epoch 45/256

240/240 - 2s - 9ms/step - ia: 0.3315 - loss: 0.9625 - mae: 0.7318 - rmse: 0.9764 - smape: 1.3902 - val_ia: 0.3009 - val_loss: 0.8328 - val_mae: 0.6917 - val_rmse: 0.8335 - val_smape: 1.4090

Epoch 46/256

240/240 - 2s - 8ms/step - ia: 0.3295 - loss: 0.9686 - mae: 0.7339 - rmse: 0.9786 - smape: 1.3898 - val_ia: 0.3009 - val_loss: 0.8316 - val_mae: 0.6910 - val_rmse: 0.8328 - val_smape: 1.4081

Epoch 47/256

240/240 - 2s - 8ms/step - ia: 0.3314 - loss: 0.9615 - mae: 0.7322 - rmse: 0.9748 - smape: 1.3908 - val_ia: 0.3009 - val_loss: 0.8304 - val_mae: 0.6904 - val_rmse: 0.8320 - val_smape: 1.4072

Epoch 48/256

240/240 - 2s - 7ms/step - ia: 0.3295 - loss: 0.9667 - mae: 0.7326 - rmse: 0.9776 - smape: 1.3915 - val_ia: 0.3010 - val_loss: 0.8293 - val_mae: 0.6897 - val_rmse: 0.8314 - val_smape: 1.4066

Epoch 49/256

240/240 - 2s - 7ms/step - ia: 0.3297 - loss: 0.9614 - mae: 0.7306 - rmse: 0.9750 - smape: 1.3891 - val_ia: 0.3010 - val_loss: 0.8282 - val_mae: 0.6891 - val_rmse: 0.8307 - val_smape: 1.4058

Epoch 50/256

240/240 - 1s - 6ms/step - ia: 0.3290 - loss: 0.9560 - mae: 0.7296 - rmse: 0.9726 - smape: 1.3919 - val_ia: 0.3010 - val_loss: 0.8271 - val_mae: 0.6885 - val_rmse: 0.8300 - val_smape: 1.4045

Epoch 51/256

240/240 - 1s - 6ms/step - ia: 0.3306 - loss: 0.9576 - mae: 0.7287 - rmse: 0.9739 - smape: 1.3919 - val_ia: 0.3010 - val_loss: 0.8260 - val_mae: 0.6878 - val_rmse: 0.8292 - val_smape: 1.4038

Epoch 52/256

240/240 - 2s - 6ms/step - ia: 0.3293 - loss: 0.9509 - mae: 0.7288 - rmse: 0.9699 - smape: 1.3935 - val_ia: 0.3011 - val_loss: 0.8248 - val_mae: 0.6872 - val_rmse: 0.8285 - val_smape: 1.4030

Epoch 53/256

240/240 - 2s - 9ms/step - ia: 0.3300 - loss: 0.9481 - mae: 0.7276 - rmse: 0.9691 - smape: 1.3919 - val_ia: 0.3011 - val_loss: 0.8238 - val_mae: 0.6866 - val_rmse: 0.8279 - val_smape: 1.4024

Epoch 54/256

240/240 - 2s - 8ms/step - ia: 0.3296 - loss: 0.9513 - mae: 0.7285 - rmse: 0.9703 - smape: 1.3933 - val_ia: 0.3011 - val_loss: 0.8228 - val_mae: 0.6860 - val_rmse: 0.8273 - val_smape: 1.4019

Epoch 55/256

240/240 - 3s - 11ms/step - ia: 0.3292 - loss: 0.9493 - mae: 0.7279 - rmse: 0.9703 - smape: 1.3918 - val_ia: 0.3012 - val_loss: 0.8219 - val_mae: 0.6854 - val_rmse: 0.8266 - val_smape: 1.4012

Epoch 56/256

240/240 - 2s - 7ms/step - ia: 0.3309 - loss: 0.9482 - mae: 0.7252 - rmse: 0.9690 - smape: 1.3902 - val_ia: 0.3012 - val_loss: 0.8208 - val_mae: 0.6849 - val_rmse: 0.8260 - val_smape: 1.4005

Epoch 57/256

240/240 - 2s - 7ms/step - ia: 0.3289 - loss: 0.9512 - mae: 0.7268 - rmse: 0.9702 - smape: 1.3893 - val_ia: 0.3012 - val_loss: 0.8199 - val_mae: 0.6843 - val_rmse: 0.8254 - val_smape: 1.4000

Epoch 58/256

240/240 - 2s - 8ms/step - ia: 0.3289 - loss: 0.9472 - mae: 0.7258 - rmse: 0.9685 - smape: 1.3912 - val_ia: 0.3012 - val_loss: 0.8189 - val_mae: 0.6837 - val_rmse: 0.8248 - val_smape: 1.3993

Epoch 59/256

240/240 - 2s - 8ms/step - ia: 0.3302 - loss: 0.9421 - mae: 0.7240 - rmse: 0.9648 - smape: 1.3910 - val_ia: 0.3013 - val_loss: 0.8179 - val_mae: 0.6832 - val_rmse: 0.8242 - val_smape: 1.3985

Epoch 60/256

240/240 - 2s - 8ms/step - ia: 0.3321 - loss: 0.9405 - mae: 0.7234 - rmse: 0.9637 - smape: 1.3901 - val_ia: 0.3013 - val_loss: 0.8170 - val_mae: 0.6826 - val_rmse: 0.8236 - val_smape: 1.3977

Epoch 61/256

240/240 - 2s - 8ms/step - ia: 0.3300 - loss: 0.9429 - mae: 0.7241 - rmse: 0.9654 - smape: 1.3903 - val_ia: 0.3013 - val_loss: 0.8161 - val_mae: 0.6821 - val_rmse: 0.8230 - val_smape: 1.3968

Epoch 62/256

240/240 - 2s - 8ms/step - ia: 0.3331 - loss: 0.9338 - mae: 0.7201 - rmse: 0.9603 - smape: 1.3866 - val_ia: 0.3014 - val_loss: 0.8152 - val_mae: 0.6815 - val_rmse: 0.8224 - val_smape: 1.3962

Epoch 63/256

240/240 - 2s - 8ms/step - ia: 0.3340 - loss: 0.9299 - mae: 0.7192 - rmse: 0.9584 - smape: 1.3853 - val_ia: 0.3014 - val_loss: 0.8144 - val_mae: 0.6811 - val_rmse: 0.8219 - val_smape: 1.3958

Epoch 64/256

240/240 - 2s - 8ms/step - ia: 0.3340 - loss: 0.9332 - mae: 0.7192 - rmse: 0.9615 - smape: 1.3843 - val_ia: 0.3014 - val_loss: 0.8135 - val_mae: 0.6805 - val_rmse: 0.8213 - val_smape: 1.3951

Epoch 65/256

240/240 - 2s - 9ms/step - ia: 0.3335 - loss: 0.9301 - mae: 0.7178 - rmse: 0.9592 - smape: 1.3839 - val_ia: 0.3015 - val_loss: 0.8127 - val_mae: 0.6800 - val_rmse: 0.8208 - val_smape: 1.3944

Epoch 66/256

240/240 - 2s - 9ms/step - ia: 0.3319 - loss: 0.9352 - mae: 0.7193 - rmse: 0.9606 - smape: 1.3857 - val_ia: 0.3015 - val_loss: 0.8119 - val_mae: 0.6795 - val_rmse: 0.8203 - val_smape: 1.3938

Epoch 67/256

240/240 - 2s - 9ms/step - ia: 0.3323 - loss: 0.9298 - mae: 0.7181 - rmse: 0.9585 - smape: 1.3854 - val_ia: 0.3015 - val_loss: 0.8110 - val_mae: 0.6790 - val_rmse: 0.8197 - val_smape: 1.3930

Epoch 68/256

240/240 - 2s - 8ms/step - ia: 0.3349 - loss: 0.9258 - mae: 0.7164 - rmse: 0.9569 - smape: 1.3828 - val_ia: 0.3015 - val_loss: 0.8102 - val_mae: 0.6785 - val_rmse: 0.8192 - val_smape: 1.3923

Epoch 69/256

240/240 - 2s - 7ms/step - ia: 0.3316 - loss: 0.9316 - mae: 0.7182 - rmse: 0.9594 - smape: 1.3866 - val_ia: 0.3015 - val_loss: 0.8094 - val_mae: 0.6780 - val_rmse: 0.8186 - val_smape: 1.3915

Epoch 70/256

240/240 - 2s - 7ms/step - ia: 0.3340 - loss: 0.9210 - mae: 0.7147 - rmse: 0.9548 - smape: 1.3831 - val_ia: 0.3016 - val_loss: 0.8086 - val_mae: 0.6775 - val_rmse: 0.8181 - val_smape: 1.3907

Epoch 71/256

240/240 - 2s - 8ms/step - ia: 0.3330 - loss: 0.9233 - mae: 0.7149 - rmse: 0.9565 - smape: 1.3855 - val_ia: 0.3016 - val_loss: 0.8078 - val_mae: 0.6770 - val_rmse: 0.8176 - val_smape: 1.3899

Epoch 72/256

240/240 - 2s - 9ms/step - ia: 0.3331 - loss: 0.9293 - mae: 0.7164 - rmse: 0.9588 - smape: 1.3865 - val_ia: 0.3016 - val_loss: 0.8070 - val_mae: 0.6765 - val_rmse: 0.8171 - val_smape: 1.3892

Epoch 73/256

240/240 - 2s - 8ms/step - ia: 0.3348 - loss: 0.9234 - mae: 0.7130 - rmse: 0.9562 - smape: 1.3803 - val_ia: 0.3016 - val_loss: 0.8063 - val_mae: 0.6761 - val_rmse: 0.8166 - val_smape: 1.3885

Epoch 74/256

240/240 - 2s - 9ms/step - ia: 0.3349 - loss: 0.9175 - mae: 0.7127 - rmse: 0.9527 - smape: 1.3810 - val_ia: 0.3017 - val_loss: 0.8056 - val_mae: 0.6756 - val_rmse: 0.8162 - val_smape: 1.3877

Epoch 75/256

240/240 - 2s - 9ms/step - ia: 0.3356 - loss: 0.9177 - mae: 0.7129 - rmse: 0.9520 - smape: 1.3827 - val_ia: 0.3017 - val_loss: 0.8049 - val_mae: 0.6752 - val_rmse: 0.8157 - val_smape: 1.3870

Epoch 76/256

240/240 - 2s - 8ms/step - ia: 0.3323 - loss: 0.9204 - mae: 0.7139 - rmse: 0.9542 - smape: 1.3862 - val_ia: 0.3017 - val_loss: 0.8042 - val_mae: 0.6748 - val_rmse: 0.8152 - val_smape: 1.3862

Epoch 77/256

240/240 - 2s - 8ms/step - ia: 0.3362 - loss: 0.9165 - mae: 0.7116 - rmse: 0.9508 - smape: 1.3811 - val_ia: 0.3017 - val_loss: 0.8035 - val_mae: 0.6743 - val_rmse: 0.8148 - val_smape: 1.3856

Epoch 78/256

240/240 - 3s - 10ms/step - ia: 0.3374 - loss: 0.9111 - mae: 0.7091 - rmse: 0.9485 - smape: 1.3792 - val_ia: 0.3017 - val_loss: 0.8028 - val_mae: 0.6739 - val_rmse: 0.8143 - val_smape: 1.3847

Epoch 79/256

240/240 - 2s - 9ms/step - ia: 0.3330 - loss: 0.9133 - mae: 0.7120 - rmse: 0.9510 - smape: 1.3836 - val_ia: 0.3018 - val_loss: 0.8021 - val_mae: 0.6735 - val_rmse: 0.8139 - val_smape: 1.3838

Epoch 80/256

240/240 - 2s - 8ms/step - ia: 0.3351 - loss: 0.9137 - mae: 0.7099 - rmse: 0.9510 - smape: 1.3788 - val_ia: 0.3018 - val_loss: 0.8014 - val_mae: 0.6730 - val_rmse: 0.8134 - val_smape: 1.3830

Epoch 81/256

240/240 - 2s - 7ms/step - ia: 0.3341 - loss: 0.9166 - mae: 0.7116 - rmse: 0.9509 - smape: 1.3823 - val_ia: 0.3018 - val_loss: 0.8008 - val_mae: 0.6726 - val_rmse: 0.8129 - val_smape: 1.3823

Epoch 82/256

240/240 - 2s - 7ms/step - ia: 0.3366 - loss: 0.9106 - mae: 0.7078 - rmse: 0.9490 - smape: 1.3796 - val_ia: 0.3018 - val_loss: 0.8001 - val_mae: 0.6721 - val_rmse: 0.8125 - val_smape: 1.3814

Epoch 83/256

240/240 - 2s - 8ms/step - ia: 0.3361 - loss: 0.9060 - mae: 0.7092 - rmse: 0.9462 - smape: 1.3829 - val_ia: 0.3019 - val_loss: 0.7995 - val_mae: 0.6717 - val_rmse: 0.8121 - val_smape: 1.3806

Epoch 84/256

240/240 - 2s - 8ms/step - ia: 0.3364 - loss: 0.9061 - mae: 0.7077 - rmse: 0.9482 - smape: 1.3789 - val_ia: 0.3019 - val_loss: 0.7989 - val_mae: 0.6713 - val_rmse: 0.8117 - val_smape: 1.3800

Epoch 85/256

240/240 - 2s - 9ms/step - ia: 0.3389 - loss: 0.8992 - mae: 0.7045 - rmse: 0.9425 - smape: 1.3738 - val_ia: 0.3020 - val_loss: 0.7983 - val_mae: 0.6709 - val_rmse: 0.8113 - val_smape: 1.3792

Epoch 86/256

240/240 - 2s - 8ms/step - ia: 0.3372 - loss: 0.9045 - mae: 0.7051 - rmse: 0.9460 - smape: 1.3771 - val_ia: 0.3020 - val_loss: 0.7977 - val_mae: 0.6706 - val_rmse: 0.8109 - val_smape: 1.3785

Epoch 87/256

240/240 - 2s - 7ms/step - ia: 0.3366 - loss: 0.9057 - mae: 0.7066 - rmse: 0.9470 - smape: 1.3771 - val_ia: 0.3020 - val_loss: 0.7971 - val_mae: 0.6702 - val_rmse: 0.8106 - val_smape: 1.3779

Epoch 88/256

240/240 - 1s - 6ms/step - ia: 0.3325 - loss: 0.9107 - mae: 0.7091 - rmse: 0.9497 - smape: 1.3827 - val_ia: 0.3021 - val_loss: 0.7965 - val_mae: 0.6698 - val_rmse: 0.8102 - val_smape: 1.3772

Epoch 89/256

240/240 - 1s - 6ms/step - ia: 0.3383 - loss: 0.9020 - mae: 0.7050 - rmse: 0.9446 - smape: 1.3751 - val_ia: 0.3021 - val_loss: 0.7960 - val_mae: 0.6694 - val_rmse: 0.8098 - val_smape: 1.3767

Epoch 90/256

240/240 - 2s - 8ms/step - ia: 0.3382 - loss: 0.8976 - mae: 0.7030 - rmse: 0.9427 - smape: 1.3736 - val_ia: 0.3021 - val_loss: 0.7954 - val_mae: 0.6690 - val_rmse: 0.8094 - val_smape: 1.3759

Epoch 91/256

240/240 - 2s - 8ms/step - ia: 0.3375 - loss: 0.8989 - mae: 0.7036 - rmse: 0.9427 - smape: 1.3763 - val_ia: 0.3022 - val_loss: 0.7948 - val_mae: 0.6687 - val_rmse: 0.8091 - val_smape: 1.3752

Epoch 92/256

240/240 - 2s - 8ms/step - ia: 0.3404 - loss: 0.8961 - mae: 0.7007 - rmse: 0.9418 - smape: 1.3713 - val_ia: 0.3023 - val_loss: 0.7943 - val_mae: 0.6683 - val_rmse: 0.8087 - val_smape: 1.3745

Epoch 93/256

240/240 - 2s - 8ms/step - ia: 0.3382 - loss: 0.8950 - mae: 0.7029 - rmse: 0.9416 - smape: 1.3753 - val_ia: 0.3023 - val_loss: 0.7938 - val_mae: 0.6679 - val_rmse: 0.8083 - val_smape: 1.3738

Epoch 94/256

240/240 - 3s - 11ms/step - ia: 0.3373 - loss: 0.9010 - mae: 0.7041 - rmse: 0.9449 - smape: 1.3768 - val_ia: 0.3024 - val_loss: 0.7933 - val_mae: 0.6676 - val_rmse: 0.8080 - val_smape: 1.3733

Epoch 95/256

240/240 - 2s - 8ms/step - ia: 0.3395 - loss: 0.8963 - mae: 0.7022 - rmse: 0.9422 - smape: 1.3733 - val_ia: 0.3024 - val_loss: 0.7929 - val_mae: 0.6673 - val_rmse: 0.8077 - val_smape: 1.3727

Epoch 96/256

240/240 - 2s - 8ms/step - ia: 0.3404 - loss: 0.8959 - mae: 0.7008 - rmse: 0.9417 - smape: 1.3705 - val_ia: 0.3025 - val_loss: 0.7923 - val_mae: 0.6669 - val_rmse: 0.8073 - val_smape: 1.3719

Epoch 97/256

240/240 - 2s - 8ms/step - ia: 0.3395 - loss: 0.8934 - mae: 0.7010 - rmse: 0.9393 - smape: 1.3714 - val_ia: 0.3025 - val_loss: 0.7918 - val_mae: 0.6665 - val_rmse: 0.8070 - val_smape: 1.3710

Epoch 98/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1915/1915 - 42s - 22ms/step - ia: 0.2669 - loss: 1.0898 - mae: 0.7828 - rmse: 1.0077 - smape: 1.4883 - val_ia: 0.2247 - val_loss: 0.8746 - val_mae: 0.6989 - val_rmse: 0.7575 - val_smape: 1.6214

Epoch 2/32

1915/1915 - 37s - 19ms/step - ia: 0.3146 - loss: 0.9233 - mae: 0.7174 - rmse: 0.9278 - smape: 1.4110 - val_ia: 0.2406 - val_loss: 0.7885 - val_mae: 0.6583 - val_rmse: 0.7226 - val_smape: 1.3484

Epoch 3/32

1915/1915 - 35s - 18ms/step - ia: 0.3572 - loss: 0.8726 - mae: 0.6927 - rmse: 0.9006 - smape: 1.3326 - val_ia: 0.2428 - val_loss: 0.7804 - val_mae: 0.6560 - val_rmse: 0.7218 - val_smape: 1.3191

Epoch 4/32

1915/1915 - 33s - 17ms/step - ia: 0.3606 - loss: 0.8585 - mae: 0.6880 - rmse: 0.8948 - smape: 1.3241 - val_ia: 0.2435 - val_loss: 0.7767 - val_mae: 0.6531 - val_rmse: 0.7195 - val_smape: 1.3026

Epoch 5/32

1915/1915 - 35s - 18ms/step - ia: 0.3698 - loss: 0.8455 - mae: 0.6803 - rmse: 0.8862 - smape: 1.3060 - val_ia: 0.2420 - val_loss: 0.7768 - val_mae: 0.6556 - val_rmse: 0.7214 - val_smape: 1.3137

Epoch 6/32

1915/1915 - 36s - 19ms/step - ia: 0.3703 - loss: 0.8388 - mae: 0.6770 - rmse: 0.8848 - smape: 1.3028 - val_ia: 0.2440 - val_loss: 0.7726 - val_mae: 0.6525 - val_rmse: 0.7201 - val_smape: 1.2885

Epoch 7/32

1915/1915 - 41s - 21ms/step - ia: 0.3754 - loss: 0.8358 - mae: 0.6746 - rmse: 0.8819 - smape: 1.2929 - val_ia: 0.2452 - val_loss: 0.7697 - val_mae: 0.6427 - val_rmse: 0.7091 - val_smape: 1.2713

Epoch 8/32

1915/1915 - 35s - 18ms/step - ia: 0.3743 - loss: 0.8315 - mae: 0.6722 - rmse: 0.8795 - smape: 1.2936 - val_ia: 0.2448 - val_loss: 0.7674 - val_mae: 0.6473 - val_rmse: 0.7149 - val_smape: 1.2751

Epoch 9/32

1915/1915 - 36s - 19ms/step - ia: 0.3771 - loss: 0.8304 - mae: 0.6720 - rmse: 0.8797 - smape: 1.2920 - val_ia: 0.2429 - val_loss: 0.7695 - val_mae: 0.6530 - val_rmse: 0.7201 - val_smape: 1.2957

Epoch 10/32

1915/1915 - 31s - 16ms/step - ia: 0.3769 - loss: 0.8268 - mae: 0.6705 - rmse: 0.8781 - smape: 1.2882 - val_ia: 0.2453 - val_loss: 0.7643 - val_mae: 0.6444 - val_rmse: 0.7126 - val_smape: 1.2616

Epoch 11/32

1915/1915 - 33s - 17ms/step - ia: 0.3786 - loss: 0.8256 - mae: 0.6699 - rmse: 0.8768 - smape: 1.2865 - val_ia: 0.2446 - val_loss: 0.7634 - val_mae: 0.6454 - val_rmse: 0.7130 - val_smape: 1.2705

Epoch 12/32

1915/1915 - 27s - 14ms/step - ia: 0.3810 - loss: 0.8234 - mae: 0.6686 - rmse: 0.8749 - smape: 1.2890 - val_ia: 0.2444 - val_loss: 0.7643 - val_mae: 0.6485 - val_rmse: 0.7168 - val_smape: 1.2741

Epoch 13/32

1915/1915 - 32s - 17ms/step - ia: 0.3843 - loss: 0.8216 - mae: 0.6671 - rmse: 0.8743 - smape: 1.2826 - val_ia: 0.2437 - val_loss: 0.7631 - val_mae: 0.6472 - val_rmse: 0.7147 - val_smape: 1.2814

Epoch 14/32

1915/1915 - 32s - 17ms/step - ia: 0.3834 - loss: 0.8200 - mae: 0.6664 - rmse: 0.8744 - smape: 1.2810 - val_ia: 0.2450 - val_loss: 0.7606 - val_mae: 0.6392 - val_rmse: 0.7064 - val_smape: 1.2599

Epoch 15/32

1915/1915 - 31s - 16ms/step - ia: 0.3842 - loss: 0.8182 - mae: 0.6654 - rmse: 0.8730 - smape: 1.2809 - val_ia: 0.2429 - val_loss: 0.7647 - val_mae: 0.6517 - val_rmse: 0.7189 - val_smape: 1.2958

Epoch 16/32

1915/1915 - 32s - 17ms/step - ia: 0.3834 - loss: 0.8174 - mae: 0.6658 - rmse: 0.8727 - smape: 1.2818 - val_ia: 0.2451 - val_loss: 0.7606 - val_mae: 0.6424 - val_rmse: 0.7111 - val_smape: 1.2576

Epoch 17/32

1915/1915 - 34s - 18ms/step - ia: 0.3838 - loss: 0.8162 - mae: 0.6651 - rmse: 0.8718 - smape: 1.2813 - val_ia: 0.2467 - val_loss: 0.7589 - val_mae: 0.6408 - val_rmse: 0.7107 - val_smape: 1.2433

Epoch 18/32

1915/1915 - 33s - 17ms/step - ia: 0.3870 - loss: 0.8153 - mae: 0.6639 - rmse: 0.8711 - smape: 1.2762 - val_ia: 0.2488 - val_loss: 0.7577 - val_mae: 0.6326 - val_rmse: 0.7031 - val_smape: 1.2147

Epoch 19/32

1915/1915 - 34s - 18ms/step - ia: 0.3896 - loss: 0.8140 - mae: 0.6629 - rmse: 0.8700 - smape: 1.2729 - val_ia: 0.2449 - val_loss: 0.7591 - val_mae: 0.6436 - val_rmse: 0.7116 - val_smape: 1.2678

Epoch 20/32

1915/1915 - 35s - 18ms/step - ia: 0.3866 - loss: 0.8155 - mae: 0.6637 - rmse: 0.8708 - smape: 1.2763 - val_ia: 0.2437 - val_loss: 0.7602 - val_mae: 0.6468 - val_rmse: 0.7137 - val_smape: 1.2875

Epoch 21/32

1915/1915 - 34s - 18ms/step - ia: 0.3872 - loss: 0.8121 - mae: 0.6627 - rmse: 0.8706 - smape: 1.2752 - val_ia: 0.2440 - val_loss: 0.7631 - val_mae: 0.6505 - val_rmse: 0.7190 - val_smape: 1.2793

Epoch 22/32

1915/1915 - 35s - 18ms/step - ia: 0.3897 - loss: 0.8101 - mae: 0.6622 - rmse: 0.8684 - smape: 1.2731 - val_ia: 0.2478 - val_loss: 0.7556 - val_mae: 0.6342 - val_rmse: 0.7040 - val_smape: 1.2311

Epoch 23/32

1915/1915 - 35s - 18ms/step - ia: 0.3909 - loss: 0.8112 - mae: 0.6619 - rmse: 0.8684 - smape: 1.2707 - val_ia: 0.2454 - val_loss: 0.7582 - val_mae: 0.6450 - val_rmse: 0.7134 - val_smape: 1.2681

Epoch 24/32

1915/1915 - 36s - 19ms/step - ia: 0.3905 - loss: 0.8113 - mae: 0.6618 - rmse: 0.8682 - smape: 1.2702 - val_ia: 0.2448 - val_loss: 0.7587 - val_mae: 0.6454 - val_rmse: 0.7136 - val_smape: 1.2713

Epoch 25/32

1915/1915 - 31s - 16ms/step - ia: 0.3933 - loss: 0.8080 - mae: 0.6606 - rmse: 0.8668 - smape: 1.2668 - val_ia: 0.2493 - val_loss: 0.7547 - val_mae: 0.6317 - val_rmse: 0.7021 - val_smape: 1.2181

Epoch 26/32

1915/1915 - 35s - 18ms/step - ia: 0.3915 - loss: 0.8094 - mae: 0.6603 - rmse: 0.8692 - smape: 1.2672 - val_ia: 0.2463 - val_loss: 0.7557 - val_mae: 0.6405 - val_rmse: 0.7095 - val_smape: 1.2540

Epoch 27/32

1915/1915 - 36s - 19ms/step - ia: 0.3941 - loss: 0.8071 - mae: 0.6596 - rmse: 0.8657 - smape: 1.2636 - val_ia: 0.2446 - val_loss: 0.7590 - val_mae: 0.6479 - val_rmse: 0.7156 - val_smape: 1.2854

Epoch 28/32

1915/1915 - 40s - 21ms/step - ia: 0.3930 - loss: 0.8062 - mae: 0.6589 - rmse: 0.8673 - smape: 1.2645 - val_ia: 0.2447 - val_loss: 0.7577 - val_mae: 0.6450 - val_rmse: 0.7130 - val_smape: 1.2772

Epoch 29/32

1915/1915 - 35s - 18ms/step - ia: 0.3937 - loss: 0.8059 - mae: 0.6590 - rmse: 0.8661 - smape: 1.2642 - val_ia: 0.2457 - val_loss: 0.7547 - val_mae: 0.6392 - val_rmse: 0.7073 - val_smape: 1.2625

Epoch 30/32

1915/1915 - 34s - 18ms/step - ia: 0.3937 - loss: 0.8051 - mae: 0.6588 - rmse: 0.8655 - smape: 1.2636 - val_ia: 0.2460 - val_loss: 0.7560 - val_mae: 0.6420 - val_rmse: 0.7107 - val_smape: 1.2615

Epoch 31/32

1915/1915 - 34s - 18ms/step - ia: 0.3976 - loss: 0.8026 - mae: 0.6575 - rmse: 0.8635 - smape: 1.2626 - val_ia: 0.2480 - val_loss: 0.7543 - val_mae: 0.6356 - val_rmse: 0.7055 - val_smape: 1.2355

Epoch 32/32

1915/1915 - 26s - 14ms/step - ia: 0.3965 - loss: 0.8046 - mae: 0.6587 - rmse: 0.8668 - smape: 1.2640 - val_ia: 0.2477 - val_loss: 0.7568 - val_mae: 0.6382 - val_rmse: 0.7084 - val_smape: 1.2358

Restoring model weights from the end of the best epoch: 31.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:06 1s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step

 90%|█████████ | 45/50 [8:26:02<1:12:55, 875.11s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 16s - 33ms/step - ia: 0.1325 - loss: 1.0236 - mae: 0.7941 - rmse: 1.0024 - smape: 1.7491 - val_ia: 0.2411 - val_loss: 0.9205 - val_mae: 0.7414 - val_rmse: 0.8521 - val_smape: 1.7643

Epoch 2/64

479/479 - 5s - 10ms/step - ia: 0.1865 - loss: 0.9119 - mae: 0.7273 - rmse: 0.9439 - smape: 1.6614 - val_ia: 0.2455 - val_loss: 0.8367 - val_mae: 0.6899 - val_rmse: 0.8015 - val_smape: 1.5500

Epoch 3/64

479/479 - 5s - 9ms/step - ia: 0.2652 - loss: 0.8598 - mae: 0.6942 - rmse: 0.9178 - smape: 1.4899 - val_ia: 0.2558 - val_loss: 0.7973 - val_mae: 0.6657 - val_rmse: 0.7807 - val_smape: 1.4167

Epoch 4/64

479/479 - 5s - 10ms/step - ia: 0.3174 - loss: 0.8349 - mae: 0.6791 - rmse: 0.9039 - smape: 1.3993 - val_ia: 0.2652 - val_loss: 0.7792 - val_mae: 0.6539 - val_rmse: 0.7724 - val_smape: 1.3498

Epoch 5/64

479/479 - 5s - 11ms/step - ia: 0.3483 - loss: 0.8226 - mae: 0.6706 - rmse: 0.8955 - smape: 1.3473 - val_ia: 0.2720 - val_loss: 0.7715 - val_mae: 0.6489 - val_rmse: 0.7698 - val_smape: 1.3172

Epoch 6/64

479/479 - 5s - 11ms/step - ia: 0.3662 - loss: 0.8157 - mae: 0.6665 - rmse: 0.8930 - smape: 1.3200 - val_ia: 0.2762 - val_loss: 0.7666 - val_mae: 0.6445 - val_rmse: 0.7672 - val_smape: 1.2930

Epoch 7/64

479/479 - 4s - 9ms/step - ia: 0.3765 - loss: 0.8114 - mae: 0.6631 - rmse: 0.8906 - smape: 1.3005 - val_ia: 0.2785 - val_loss: 0.7645 - val_mae: 0.6437 - val_rmse: 0.7672 - val_smape: 1.2846

Epoch 8/64

479/479 - 4s - 8ms/step - ia: 0.3831 - loss: 0.8082 - mae: 0.6610 - rmse: 0.8898 - smape: 1.2883 - val_ia: 0.2800 - val_loss: 0.7633 - val_mae: 0.6437 - val_rmse: 0.7677 - val_smape: 1.2807

Epoch 9/64

479/479 - 4s - 9ms/step - ia: 0.3887 - loss: 0.8057 - mae: 0.6595 - rmse: 0.8877 - smape: 1.2798 - val_ia: 0.2805 - val_loss: 0.7624 - val_mae: 0.6427 - val_rmse: 0.7670 - val_smape: 1.2760

Epoch 10/64

479/479 - 4s - 9ms/step - ia: 0.3907 - loss: 0.8036 - mae: 0.6580 - rmse: 0.8872 - smape: 1.2751 - val_ia: 0.2809 - val_loss: 0.7615 - val_mae: 0.6417 - val_rmse: 0.7664 - val_smape: 1.2718

Epoch 11/64

479/479 - 5s - 9ms/step - ia: 0.3934 - loss: 0.8015 - mae: 0.6565 - rmse: 0.8861 - smape: 1.2703 - val_ia: 0.2816 - val_loss: 0.7600 - val_mae: 0.6413 - val_rmse: 0.7663 - val_smape: 1.2681

Epoch 12/64

479/479 - 4s - 9ms/step - ia: 0.3963 - loss: 0.7997 - mae: 0.6552 - rmse: 0.8845 - smape: 1.2656 - val_ia: 0.2816 - val_loss: 0.7592 - val_mae: 0.6411 - val_rmse: 0.7661 - val_smape: 1.2675

Epoch 13/64

479/479 - 5s - 10ms/step - ia: 0.3982 - loss: 0.7980 - mae: 0.6546 - rmse: 0.8845 - smape: 1.2630 - val_ia: 0.2817 - val_loss: 0.7571 - val_mae: 0.6393 - val_rmse: 0.7645 - val_smape: 1.2615

Epoch 14/64

479/479 - 5s - 9ms/step - ia: 0.3997 - loss: 0.7964 - mae: 0.6534 - rmse: 0.8829 - smape: 1.2600 - val_ia: 0.2817 - val_loss: 0.7560 - val_mae: 0.6381 - val_rmse: 0.7636 - val_smape: 1.2575

Epoch 15/64

479/479 - 5s - 9ms/step - ia: 0.4001 - loss: 0.7949 - mae: 0.6520 - rmse: 0.8828 - smape: 1.2576 - val_ia: 0.2820 - val_loss: 0.7570 - val_mae: 0.6406 - val_rmse: 0.7660 - val_smape: 1.2641

Epoch 16/64

479/479 - 5s - 10ms/step - ia: 0.4023 - loss: 0.7936 - mae: 0.6516 - rmse: 0.8811 - smape: 1.2547 - val_ia: 0.2818 - val_loss: 0.7551 - val_mae: 0.6390 - val_rmse: 0.7645 - val_smape: 1.2599

Epoch 17/64

479/479 - 4s - 9ms/step - ia: 0.4045 - loss: 0.7923 - mae: 0.6508 - rmse: 0.8807 - smape: 1.2523 - val_ia: 0.2818 - val_loss: 0.7551 - val_mae: 0.6394 - val_rmse: 0.7650 - val_smape: 1.2609

Epoch 18/64

479/479 - 4s - 9ms/step - ia: 0.4054 - loss: 0.7910 - mae: 0.6495 - rmse: 0.8801 - smape: 1.2502 - val_ia: 0.2818 - val_loss: 0.7549 - val_mae: 0.6408 - val_rmse: 0.7662 - val_smape: 1.2663

Epoch 19/64

479/479 - 4s - 8ms/step - ia: 0.4050 - loss: 0.7898 - mae: 0.6493 - rmse: 0.8794 - smape: 1.2497 - val_ia: 0.2823 - val_loss: 0.7547 - val_mae: 0.6407 - val_rmse: 0.7664 - val_smape: 1.2646

Epoch 20/64

479/479 - 4s - 9ms/step - ia: 0.4065 - loss: 0.7887 - mae: 0.6486 - rmse: 0.8777 - smape: 1.2481 - val_ia: 0.2823 - val_loss: 0.7537 - val_mae: 0.6397 - val_rmse: 0.7655 - val_smape: 1.2612

Epoch 21/64

479/479 - 4s - 8ms/step - ia: 0.4078 - loss: 0.7876 - mae: 0.6480 - rmse: 0.8785 - smape: 1.2459 - val_ia: 0.2825 - val_loss: 0.7524 - val_mae: 0.6385 - val_rmse: 0.7646 - val_smape: 1.2576

Epoch 22/64

479/479 - 4s - 8ms/step - ia: 0.4079 - loss: 0.7864 - mae: 0.6466 - rmse: 0.8782 - smape: 1.2438 - val_ia: 0.2828 - val_loss: 0.7534 - val_mae: 0.6407 - val_rmse: 0.7666 - val_smape: 1.2646

Epoch 23/64

479/479 - 4s - 9ms/step - ia: 0.4096 - loss: 0.7854 - mae: 0.6469 - rmse: 0.8768 - smape: 1.2438 - val_ia: 0.2827 - val_loss: 0.7519 - val_mae: 0.6393 - val_rmse: 0.7653 - val_smape: 1.2595

Epoch 24/64

479/479 - 4s - 9ms/step - ia: 0.4099 - loss: 0.7844 - mae: 0.6460 - rmse: 0.8763 - smape: 1.2414 - val_ia: 0.2831 - val_loss: 0.7515 - val_mae: 0.6385 - val_rmse: 0.7648 - val_smape: 1.2563

Epoch 25/64

479/479 - 4s - 8ms/step - ia: 0.4118 - loss: 0.7834 - mae: 0.6455 - rmse: 0.8757 - smape: 1.2400 - val_ia: 0.2829 - val_loss: 0.7499 - val_mae: 0.6367 - val_rmse: 0.7632 - val_smape: 1.2510

Epoch 26/64

479/479 - 4s - 9ms/step - ia: 0.4136 - loss: 0.7823 - mae: 0.6445 - rmse: 0.8750 - smape: 1.2366 - val_ia: 0.2831 - val_loss: 0.7503 - val_mae: 0.6383 - val_rmse: 0.7646 - val_smape: 1.2577

Epoch 27/64

479/479 - 4s - 9ms/step - ia: 0.4125 - loss: 0.7814 - mae: 0.6442 - rmse: 0.8737 - smape: 1.2380 - val_ia: 0.2836 - val_loss: 0.7508 - val_mae: 0.6384 - val_rmse: 0.7651 - val_smape: 1.2566

Epoch 28/64

479/479 - 4s - 8ms/step - ia: 0.4145 - loss: 0.7805 - mae: 0.6436 - rmse: 0.8731 - smape: 1.2359 - val_ia: 0.2838 - val_loss: 0.7515 - val_mae: 0.6394 - val_rmse: 0.7661 - val_smape: 1.2599

Epoch 29/64

479/479 - 4s - 8ms/step - ia: 0.4146 - loss: 0.7795 - mae: 0.6429 - rmse: 0.8741 - smape: 1.2351 - val_ia: 0.2842 - val_loss: 0.7513 - val_mae: 0.6401 - val_rmse: 0.7667 - val_smape: 1.2619

Epoch 30/64

479/479 - 5s - 10ms/step - ia: 0.4160 - loss: 0.7786 - mae: 0.6428 - rmse: 0.8722 - smape: 1.2343 - val_ia: 0.2845 - val_loss: 0.7513 - val_mae: 0.6395 - val_rmse: 0.7665 - val_smape: 1.2599

Epoch 31/64

479/479 - 5s - 10ms/step - ia: 0.4170 - loss: 0.7776 - mae: 0.6421 - rmse: 0.8736 - smape: 1.2322 - val_ia: 0.2843 - val_loss: 0.7518 - val_mae: 0.6404 - val_rmse: 0.7670 - val_smape: 1.2633

Epoch 32/64

479/479 - 4s - 9ms/step - ia: 0.4163 - loss: 0.7769 - mae: 0.6413 - rmse: 0.8724 - smape: 1.2313 - val_ia: 0.2851 - val_loss: 0.7495 - val_mae: 0.6395 - val_rmse: 0.7663 - val_smape: 1.2595

Epoch 33/64

479/479 - 5s - 10ms/step - ia: 0.4177 - loss: 0.7760 - mae: 0.6412 - rmse: 0.8713 - smape: 1.2311 - val_ia: 0.2858 - val_loss: 0.7510 - val_mae: 0.6401 - val_rmse: 0.7674 - val_smape: 1.2598

Epoch 34/64

479/479 - 4s - 9ms/step - ia: 0.4195 - loss: 0.7752 - mae: 0.6407 - rmse: 0.8704 - smape: 1.2286 - val_ia: 0.2857 - val_loss: 0.7504 - val_mae: 0.6399 - val_rmse: 0.7670 - val_smape: 1.2599

Epoch 35/64

479/479 - 4s - 9ms/step - ia: 0.4213 - loss: 0.7744 - mae: 0.6404 - rmse: 0.8700 - smape: 1.2275 - val_ia: 0.2857 - val_loss: 0.7492 - val_mae: 0.6380 - val_rmse: 0.7654 - val_smape: 1.2555

Epoch 36/64

479/479 - 5s - 10ms/step - ia: 0.4200 - loss: 0.7736 - mae: 0.6394 - rmse: 0.8696 - smape: 1.2280 - val_ia: 0.2869 - val_loss: 0.7495 - val_mae: 0.6394 - val_rmse: 0.7670 - val_smape: 1.2571

Epoch 37/64

479/479 - 5s - 10ms/step - ia: 0.4215 - loss: 0.7729 - mae: 0.6394 - rmse: 0.8695 - smape: 1.2264 - val_ia: 0.2870 - val_loss: 0.7494 - val_mae: 0.6387 - val_rmse: 0.7664 - val_smape: 1.2551

Epoch 38/64

479/479 - 5s - 10ms/step - ia: 0.4209 - loss: 0.7721 - mae: 0.6390 - rmse: 0.8689 - smape: 1.2260 - val_ia: 0.2877 - val_loss: 0.7483 - val_mae: 0.6372 - val_rmse: 0.7653 - val_smape: 1.2490

Epoch 39/64

479/479 - 4s - 9ms/step - ia: 0.4238 - loss: 0.7714 - mae: 0.6382 - rmse: 0.8686 - smape: 1.2228 - val_ia: 0.2880 - val_loss: 0.7516 - val_mae: 0.6412 - val_rmse: 0.7691 - val_smape: 1.2609

Epoch 40/64

479/479 - 5s - 10ms/step - ia: 0.4243 - loss: 0.7707 - mae: 0.6382 - rmse: 0.8689 - smape: 1.2230 - val_ia: 0.2881 - val_loss: 0.7495 - val_mae: 0.6390 - val_rmse: 0.7671 - val_smape: 1.2545

Epoch 41/64

479/479 - 4s - 9ms/step - ia: 0.4249 - loss: 0.7700 - mae: 0.6376 - rmse: 0.8673 - smape: 1.2226 - val_ia: 0.2885 - val_loss: 0.7487 - val_mae: 0.6388 - val_rmse: 0.7667 - val_smape: 1.2541

Epoch 42/64

479/479 - 5s - 11ms/step - ia: 0.4253 - loss: 0.7693 - mae: 0.6375 - rmse: 0.8677 - smape: 1.2221 - val_ia: 0.2889 - val_loss: 0.7497 - val_mae: 0.6393 - val_rmse: 0.7675 - val_smape: 1.2549

Epoch 43/64

479/479 - 5s - 10ms/step - ia: 0.4251 - loss: 0.7686 - mae: 0.6369 - rmse: 0.8661 - smape: 1.2208 - val_ia: 0.2897 - val_loss: 0.7480 - val_mae: 0.6376 - val_rmse: 0.7661 - val_smape: 1.2478

Epoch 44/64

479/479 - 5s - 10ms/step - ia: 0.4272 - loss: 0.7680 - mae: 0.6367 - rmse: 0.8671 - smape: 1.2203 - val_ia: 0.2896 - val_loss: 0.7488 - val_mae: 0.6380 - val_rmse: 0.7665 - val_smape: 1.2492

Epoch 45/64

479/479 - 5s - 9ms/step - ia: 0.4270 - loss: 0.7674 - mae: 0.6363 - rmse: 0.8663 - smape: 1.2194 - val_ia: 0.2903 - val_loss: 0.7506 - val_mae: 0.6400 - val_rmse: 0.7687 - val_smape: 1.2545

Epoch 46/64

479/479 - 5s - 10ms/step - ia: 0.4275 - loss: 0.7668 - mae: 0.6359 - rmse: 0.8662 - smape: 1.2188 - val_ia: 0.2908 - val_loss: 0.7507 - val_mae: 0.6403 - val_rmse: 0.7690 - val_smape: 1.2547

Epoch 47/64

479/479 - 4s - 8ms/step - ia: 0.4285 - loss: 0.7661 - mae: 0.6354 - rmse: 0.8659 - smape: 1.2176 - val_ia: 0.2914 - val_loss: 0.7510 - val_mae: 0.6411 - val_rmse: 0.7698 - val_smape: 1.2557

Epoch 48/64

479/479 - 4s - 8ms/step - ia: 0.4294 - loss: 0.7655 - mae: 0.6354 - rmse: 0.8646 - smape: 1.2171 - val_ia: 0.2914 - val_loss: 0.7485 - val_mae: 0.6384 - val_rmse: 0.7672 - val_smape: 1.2481

Epoch 49/64

479/479 - 4s - 8ms/step - ia: 0.4300 - loss: 0.7650 - mae: 0.6353 - rmse: 0.8653 - smape: 1.2164 - val_ia: 0.2912 - val_loss: 0.7497 - val_mae: 0.6386 - val_rmse: 0.7678 - val_smape: 1.2488

Epoch 50/64

479/479 - 4s - 8ms/step - ia: 0.4310 - loss: 0.7644 - mae: 0.6342 - rmse: 0.8654 - smape: 1.2149 - val_ia: 0.2920 - val_loss: 0.7517 - val_mae: 0.6419 - val_rmse: 0.7707 - val_smape: 1.2580

Epoch 51/64

479/479 - 5s - 10ms/step - ia: 0.4311 - loss: 0.7638 - mae: 0.6346 - rmse: 0.8652 - smape: 1.2153 - val_ia: 0.2922 - val_loss: 0.7503 - val_mae: 0.6405 - val_rmse: 0.7693 - val_smape: 1.2538

Epoch 52/64

479/479 - 5s - 10ms/step - ia: 0.4310 - loss: 0.7632 - mae: 0.6338 - rmse: 0.8639 - smape: 1.2150 - val_ia: 0.2930 - val_loss: 0.7517 - val_mae: 0.6413 - val_rmse: 0.7706 - val_smape: 1.2533

Epoch 53/64

479/479 - 5s - 10ms/step - ia: 0.4321 - loss: 0.7628 - mae: 0.6342 - rmse: 0.8646 - smape: 1.2140 - val_ia: 0.2929 - val_loss: 0.7497 - val_mae: 0.6390 - val_rmse: 0.7684 - val_smape: 1.2467

Epoch 54/64

479/479 - 5s - 10ms/step - ia: 0.4318 - loss: 0.7622 - mae: 0.6336 - rmse: 0.8635 - smape: 1.2136 - val_ia: 0.2934 - val_loss: 0.7490 - val_mae: 0.6381 - val_rmse: 0.7677 - val_smape: 1.2437

Epoch 55/64

479/479 - 5s - 10ms/step - ia: 0.4332 - loss: 0.7617 - mae: 0.6332 - rmse: 0.8630 - smape: 1.2122 - val_ia: 0.2932 - val_loss: 0.7494 - val_mae: 0.6385 - val_rmse: 0.7680 - val_smape: 1.2457

Epoch 56/64

479/479 - 5s - 10ms/step - ia: 0.4329 - loss: 0.7611 - mae: 0.6329 - rmse: 0.8632 - smape: 1.2120 - val_ia: 0.2934 - val_loss: 0.7498 - val_mae: 0.6397 - val_rmse: 0.7688 - val_smape: 1.2495

Epoch 57/64

479/479 - 4s - 8ms/step - ia: 0.4337 - loss: 0.7606 - mae: 0.6328 - rmse: 0.8630 - smape: 1.2116 - val_ia: 0.2936 - val_loss: 0.7489 - val_mae: 0.6386 - val_rmse: 0.7678 - val_smape: 1.2455

Epoch 58/64

479/479 - 4s - 9ms/step - ia: 0.4332 - loss: 0.7600 - mae: 0.6324 - rmse: 0.8624 - smape: 1.2124 - val_ia: 0.2944 - val_loss: 0.7514 - val_mae: 0.6404 - val_rmse: 0.7701 - val_smape: 1.2485

Epoch 58: early stopping

Restoring model weights from the end of the best epoch: 43.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:02 461ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 92%|█████████▏| 46/50 [8:30:32<46:13, 693.47s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 77s - 20ms/step - ia: 0.3899 - loss: 0.8142 - mae: 0.6608 - rmse: 0.8436 - smape: 1.2690 - val_ia: 0.2033 - val_loss: 0.7655 - val_mae: 0.6485 - val_rmse: 0.6917 - val_smape: 1.2624

Epoch 2/128

3830/3830 - 61s - 16ms/step - ia: 0.4090 - loss: 0.7852 - mae: 0.6463 - rmse: 0.8284 - smape: 1.2346 - val_ia: 0.2104 - val_loss: 0.7428 - val_mae: 0.6298 - val_rmse: 0.6719 - val_smape: 1.2264

Epoch 3/128

3830/3830 - 62s - 16ms/step - ia: 0.4225 - loss: 0.7602 - mae: 0.6346 - rmse: 0.8152 - smape: 1.2121 - val_ia: 0.2080 - val_loss: 0.7475 - val_mae: 0.6338 - val_rmse: 0.6751 - val_smape: 1.2470

Epoch 4/128

3830/3830 - 58s - 15ms/step - ia: 0.4361 - loss: 0.7282 - mae: 0.6212 - rmse: 0.7981 - smape: 1.1889 - val_ia: 0.2078 - val_loss: 0.8181 - val_mae: 0.6507 - val_rmse: 0.6979 - val_smape: 1.2361

Epoch 5/128

3830/3830 - 58s - 15ms/step - ia: 0.4546 - loss: 0.6841 - mae: 0.6042 - rmse: 0.7746 - smape: 1.1676 - val_ia: 0.2034 - val_loss: 0.8243 - val_mae: 0.6531 - val_rmse: 0.7004 - val_smape: 1.2514

Epoch 6/128

3830/3830 - 51s - 13ms/step - ia: 0.4761 - loss: 0.6267 - mae: 0.5798 - rmse: 0.7416 - smape: 1.1349 - val_ia: 0.2082 - val_loss: 0.8370 - val_mae: 0.6466 - val_rmse: 0.6973 - val_smape: 1.2148

Epoch 7/128

3830/3830 - 55s - 14ms/step - ia: 0.5062 - loss: 0.5509 - mae: 0.5480 - rmse: 0.6989 - smape: 1.0970 - val_ia: 0.2019 - val_loss: 1.0143 - val_mae: 0.6970 - val_rmse: 0.7509 - val_smape: 1.2511

Epoch 8/128

3830/3830 - 58s - 15ms/step - ia: 0.5410 - loss: 0.4720 - mae: 0.5111 - rmse: 0.6479 - smape: 1.0423 - val_ia: 0.1998 - val_loss: 1.0732 - val_mae: 0.7168 - val_rmse: 0.7750 - val_smape: 1.2576

Epoch 9/128

3830/3830 - 60s - 16ms/step - ia: 0.5723 - loss: 0.4084 - mae: 0.4773 - rmse: 0.6037 - smape: 0.9927 - val_ia: 0.2009 - val_loss: 1.0103 - val_mae: 0.6970 - val_rmse: 0.7573 - val_smape: 1.2463

Epoch 10/128

3830/3830 - 60s - 16ms/step - ia: 0.6038 - loss: 0.3509 - mae: 0.4447 - rmse: 0.5606 - smape: 0.9428 - val_ia: 0.1960 - val_loss: 1.0875 - val_mae: 0.7241 - val_rmse: 0.7865 - val_smape: 1.2570

Epoch 11/128

3830/3830 - 55s - 14ms/step - ia: 0.6317 - loss: 0.3106 - mae: 0.4171 - rmse: 0.5272 - smape: 0.8937 - val_ia: 0.2048 - val_loss: 1.0599 - val_mae: 0.6978 - val_rmse: 0.7622 - val_smape: 1.2007

Epoch 12/128

3830/3830 - 52s - 14ms/step - ia: 0.6545 - loss: 0.2717 - mae: 0.3926 - rmse: 0.4936 - smape: 0.8544 - val_ia: 0.1959 - val_loss: 1.1172 - val_mae: 0.7329 - val_rmse: 0.8001 - val_smape: 1.2473

Epoch 13/128

3830/3830 - 59s - 15ms/step - ia: 0.6764 - loss: 0.2430 - mae: 0.3697 - rmse: 0.4655 - smape: 0.8104 - val_ia: 0.1958 - val_loss: 1.0934 - val_mae: 0.7251 - val_rmse: 0.7973 - val_smape: 1.2073

Epoch 14/128

3830/3830 - 47s - 12ms/step - ia: 0.6972 - loss: 0.2152 - mae: 0.3491 - rmse: 0.4393 - smape: 0.7747 - val_ia: 0.1956 - val_loss: 1.1027 - val_mae: 0.7273 - val_rmse: 0.7983 - val_smape: 1.2348

Epoch 15/128

3830/3830 - 59s - 15ms/step - ia: 0.7130 - loss: 0.1949 - mae: 0.3322 - rmse: 0.4184 - smape: 0.7414 - val_ia: 0.1956 - val_loss: 1.1215 - val_mae: 0.7330 - val_rmse: 0.8039 - val_smape: 1.2443

Epoch 16/128

3830/3830 - 60s - 16ms/step - ia: 0.7265 - loss: 0.1755 - mae: 0.3165 - rmse: 0.3974 - smape: 0.7107 - val_ia: 0.1954 - val_loss: 1.1572 - val_mae: 0.7448 - val_rmse: 0.8167 - val_smape: 1.2385

Epoch 17/128

3830/3830 - 54s - 14ms/step - ia: 0.7403 - loss: 0.1622 - mae: 0.3026 - rmse: 0.3813 - smape: 0.6870 - val_ia: 0.1970 - val_loss: 1.1037 - val_mae: 0.7219 - val_rmse: 0.7936 - val_smape: 1.2175

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:06 489ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

Epoch 1/256

 94%|█████████▍| 47/50 [8:47:00<39:05, 781.70s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 6s - 51ms/step - ia: 0.3158 - loss: 1.0417 - mae: 0.7505 - rmse: 1.0170 - smape: 1.3767 - val_ia: 0.3034 - val_loss: 0.8873 - val_mae: 0.7052 - val_rmse: 0.8695 - val_smape: 1.4352

Epoch 2/256

120/120 - 1s - 8ms/step - ia: 0.3230 - loss: 0.9372 - mae: 0.7171 - rmse: 0.9655 - smape: 1.3797 - val_ia: 0.3129 - val_loss: 0.8229 - val_mae: 0.6784 - val_rmse: 0.8368 - val_smape: 1.3832

Epoch 3/256

120/120 - 1s - 7ms/step - ia: 0.3407 - loss: 0.8999 - mae: 0.7039 - rmse: 0.9460 - smape: 1.3608 - val_ia: 0.3202 - val_loss: 0.7962 - val_mae: 0.6648 - val_rmse: 0.8227 - val_smape: 1.3482

Epoch 4/256

120/120 - 1s - 11ms/step - ia: 0.3582 - loss: 0.8745 - mae: 0.6909 - rmse: 0.9332 - smape: 1.3329 - val_ia: 0.3228 - val_loss: 0.7793 - val_mae: 0.6551 - val_rmse: 0.8128 - val_smape: 1.3198

Epoch 5/256

120/120 - 1s - 8ms/step - ia: 0.3638 - loss: 0.8657 - mae: 0.6879 - rmse: 0.9275 - smape: 1.3233 - val_ia: 0.3261 - val_loss: 0.7729 - val_mae: 0.6516 - val_rmse: 0.8098 - val_smape: 1.3113

Epoch 6/256

120/120 - 1s - 7ms/step - ia: 0.3685 - loss: 0.8576 - mae: 0.6833 - rmse: 0.9231 - smape: 1.3180 - val_ia: 0.3283 - val_loss: 0.7676 - val_mae: 0.6483 - val_rmse: 0.8069 - val_smape: 1.2993

Epoch 7/256

120/120 - 1s - 7ms/step - ia: 0.3726 - loss: 0.8506 - mae: 0.6797 - rmse: 0.9192 - smape: 1.3113 - val_ia: 0.3300 - val_loss: 0.7642 - val_mae: 0.6459 - val_rmse: 0.8050 - val_smape: 1.2911

Epoch 8/256

120/120 - 1s - 8ms/step - ia: 0.3739 - loss: 0.8440 - mae: 0.6773 - rmse: 0.9164 - smape: 1.3078 - val_ia: 0.3327 - val_loss: 0.7628 - val_mae: 0.6448 - val_rmse: 0.8047 - val_smape: 1.2869

Epoch 9/256

120/120 - 1s - 8ms/step - ia: 0.3757 - loss: 0.8433 - mae: 0.6761 - rmse: 0.9157 - smape: 1.3036 - val_ia: 0.3340 - val_loss: 0.7599 - val_mae: 0.6433 - val_rmse: 0.8032 - val_smape: 1.2803

Epoch 10/256

120/120 - 1s - 8ms/step - ia: 0.3785 - loss: 0.8394 - mae: 0.6734 - rmse: 0.9140 - smape: 1.3004 - val_ia: 0.3355 - val_loss: 0.7598 - val_mae: 0.6430 - val_rmse: 0.8034 - val_smape: 1.2804

Epoch 11/256

120/120 - 1s - 8ms/step - ia: 0.3775 - loss: 0.8387 - mae: 0.6730 - rmse: 0.9135 - smape: 1.3013 - val_ia: 0.3368 - val_loss: 0.7550 - val_mae: 0.6398 - val_rmse: 0.8004 - val_smape: 1.2680

Epoch 12/256

120/120 - 1s - 9ms/step - ia: 0.3802 - loss: 0.8343 - mae: 0.6710 - rmse: 0.9109 - smape: 1.2967 - val_ia: 0.3383 - val_loss: 0.7543 - val_mae: 0.6404 - val_rmse: 0.8009 - val_smape: 1.2695

Epoch 13/256

120/120 - 1s - 10ms/step - ia: 0.3797 - loss: 0.8326 - mae: 0.6701 - rmse: 0.9096 - smape: 1.2945 - val_ia: 0.3403 - val_loss: 0.7522 - val_mae: 0.6391 - val_rmse: 0.7999 - val_smape: 1.2623

Epoch 14/256

120/120 - 1s - 7ms/step - ia: 0.3859 - loss: 0.8275 - mae: 0.6679 - rmse: 0.9068 - smape: 1.2888 - val_ia: 0.3404 - val_loss: 0.7538 - val_mae: 0.6398 - val_rmse: 0.8010 - val_smape: 1.2677

Epoch 15/256

120/120 - 1s - 8ms/step - ia: 0.3812 - loss: 0.8276 - mae: 0.6684 - rmse: 0.9071 - smape: 1.2941 - val_ia: 0.3421 - val_loss: 0.7520 - val_mae: 0.6391 - val_rmse: 0.8003 - val_smape: 1.2628

Epoch 16/256

120/120 - 1s - 8ms/step - ia: 0.3852 - loss: 0.8229 - mae: 0.6655 - rmse: 0.9048 - smape: 1.2880 - val_ia: 0.3435 - val_loss: 0.7486 - val_mae: 0.6373 - val_rmse: 0.7985 - val_smape: 1.2535

Epoch 17/256

120/120 - 1s - 8ms/step - ia: 0.3875 - loss: 0.8223 - mae: 0.6650 - rmse: 0.9043 - smape: 1.2836 - val_ia: 0.3440 - val_loss: 0.7493 - val_mae: 0.6380 - val_rmse: 0.7993 - val_smape: 1.2575

Epoch 18/256

120/120 - 1s - 9ms/step - ia: 0.3903 - loss: 0.8166 - mae: 0.6621 - rmse: 0.9008 - smape: 1.2793 - val_ia: 0.3437 - val_loss: 0.7509 - val_mae: 0.6399 - val_rmse: 0.8011 - val_smape: 1.2635

Epoch 19/256

120/120 - 1s - 8ms/step - ia: 0.3880 - loss: 0.8176 - mae: 0.6637 - rmse: 0.9007 - smape: 1.2842 - val_ia: 0.3451 - val_loss: 0.7472 - val_mae: 0.6377 - val_rmse: 0.7989 - val_smape: 1.2542

Epoch 20/256

120/120 - 1s - 8ms/step - ia: 0.3920 - loss: 0.8120 - mae: 0.6606 - rmse: 0.8987 - smape: 1.2756 - val_ia: 0.3461 - val_loss: 0.7453 - val_mae: 0.6363 - val_rmse: 0.7977 - val_smape: 1.2477

Epoch 21/256

120/120 - 1s - 8ms/step - ia: 0.3915 - loss: 0.8132 - mae: 0.6608 - rmse: 0.8989 - smape: 1.2770 - val_ia: 0.3459 - val_loss: 0.7456 - val_mae: 0.6381 - val_rmse: 0.7989 - val_smape: 1.2529

Epoch 22/256

120/120 - 1s - 8ms/step - ia: 0.3929 - loss: 0.8131 - mae: 0.6612 - rmse: 0.9000 - smape: 1.2749 - val_ia: 0.3471 - val_loss: 0.7447 - val_mae: 0.6363 - val_rmse: 0.7978 - val_smape: 1.2483

Epoch 23/256

120/120 - 1s - 8ms/step - ia: 0.3943 - loss: 0.8113 - mae: 0.6607 - rmse: 0.8983 - smape: 1.2740 - val_ia: 0.3464 - val_loss: 0.7440 - val_mae: 0.6362 - val_rmse: 0.7975 - val_smape: 1.2504

Epoch 24/256

120/120 - 1s - 11ms/step - ia: 0.3916 - loss: 0.8141 - mae: 0.6606 - rmse: 0.8995 - smape: 1.2737 - val_ia: 0.3459 - val_loss: 0.7414 - val_mae: 0.6353 - val_rmse: 0.7961 - val_smape: 1.2443

Epoch 25/256

120/120 - 1s - 7ms/step - ia: 0.3948 - loss: 0.8099 - mae: 0.6591 - rmse: 0.8975 - smape: 1.2721 - val_ia: 0.3478 - val_loss: 0.7428 - val_mae: 0.6361 - val_rmse: 0.7974 - val_smape: 1.2459

Epoch 26/256

120/120 - 1s - 7ms/step - ia: 0.3955 - loss: 0.8066 - mae: 0.6578 - rmse: 0.8950 - smape: 1.2708 - val_ia: 0.3488 - val_loss: 0.7425 - val_mae: 0.6354 - val_rmse: 0.7971 - val_smape: 1.2438

Epoch 27/256

120/120 - 1s - 7ms/step - ia: 0.3954 - loss: 0.8068 - mae: 0.6579 - rmse: 0.8963 - smape: 1.2697 - val_ia: 0.3506 - val_loss: 0.7428 - val_mae: 0.6360 - val_rmse: 0.7979 - val_smape: 1.2443

Epoch 28/256

120/120 - 1s - 7ms/step - ia: 0.3982 - loss: 0.8039 - mae: 0.6566 - rmse: 0.8940 - smape: 1.2662 - val_ia: 0.3504 - val_loss: 0.7410 - val_mae: 0.6348 - val_rmse: 0.7966 - val_smape: 1.2364

Epoch 29/256

120/120 - 1s - 8ms/step - ia: 0.3994 - loss: 0.8030 - mae: 0.6561 - rmse: 0.8936 - smape: 1.2627 - val_ia: 0.3516 - val_loss: 0.7411 - val_mae: 0.6354 - val_rmse: 0.7973 - val_smape: 1.2365

Epoch 30/256

120/120 - 1s - 9ms/step - ia: 0.4015 - loss: 0.8038 - mae: 0.6562 - rmse: 0.8939 - smape: 1.2604 - val_ia: 0.3530 - val_loss: 0.7406 - val_mae: 0.6343 - val_rmse: 0.7968 - val_smape: 1.2335

Epoch 31/256

120/120 - 1s - 9ms/step - ia: 0.4006 - loss: 0.8010 - mae: 0.6556 - rmse: 0.8926 - smape: 1.2628 - val_ia: 0.3538 - val_loss: 0.7422 - val_mae: 0.6349 - val_rmse: 0.7978 - val_smape: 1.2383

Epoch 32/256

120/120 - 1s - 10ms/step - ia: 0.4038 - loss: 0.7975 - mae: 0.6544 - rmse: 0.8898 - smape: 1.2584 - val_ia: 0.3536 - val_loss: 0.7399 - val_mae: 0.6343 - val_rmse: 0.7967 - val_smape: 1.2340

Epoch 33/256

120/120 - 1s - 10ms/step - ia: 0.4032 - loss: 0.8005 - mae: 0.6543 - rmse: 0.8926 - smape: 1.2573 - val_ia: 0.3544 - val_loss: 0.7410 - val_mae: 0.6353 - val_rmse: 0.7979 - val_smape: 1.2383

Epoch 34/256

120/120 - 1s - 9ms/step - ia: 0.4046 - loss: 0.7940 - mae: 0.6523 - rmse: 0.8886 - smape: 1.2567 - val_ia: 0.3547 - val_loss: 0.7405 - val_mae: 0.6352 - val_rmse: 0.7977 - val_smape: 1.2363

Epoch 35/256

120/120 - 1s - 9ms/step - ia: 0.4030 - loss: 0.7984 - mae: 0.6541 - rmse: 0.8915 - smape: 1.2594 - val_ia: 0.3560 - val_loss: 0.7405 - val_mae: 0.6344 - val_rmse: 0.7975 - val_smape: 1.2339

Epoch 36/256

120/120 - 1s - 8ms/step - ia: 0.4041 - loss: 0.7984 - mae: 0.6533 - rmse: 0.8903 - smape: 1.2556 - val_ia: 0.3583 - val_loss: 0.7421 - val_mae: 0.6349 - val_rmse: 0.7986 - val_smape: 1.2283

Epoch 37/256

120/120 - 1s - 10ms/step - ia: 0.4079 - loss: 0.7972 - mae: 0.6518 - rmse: 0.8896 - smape: 1.2491 - val_ia: 0.3577 - val_loss: 0.7409 - val_mae: 0.6347 - val_rmse: 0.7980 - val_smape: 1.2334

Epoch 38/256

120/120 - 1s - 9ms/step - ia: 0.4069 - loss: 0.7959 - mae: 0.6523 - rmse: 0.8889 - smape: 1.2543 - val_ia: 0.3581 - val_loss: 0.7394 - val_mae: 0.6335 - val_rmse: 0.7969 - val_smape: 1.2285

Epoch 39/256

120/120 - 1s - 9ms/step - ia: 0.4083 - loss: 0.7930 - mae: 0.6509 - rmse: 0.8882 - smape: 1.2500 - val_ia: 0.3590 - val_loss: 0.7392 - val_mae: 0.6331 - val_rmse: 0.7966 - val_smape: 1.2228

Epoch 40/256

120/120 - 1s - 10ms/step - ia: 0.4093 - loss: 0.7932 - mae: 0.6509 - rmse: 0.8880 - smape: 1.2495 - val_ia: 0.3587 - val_loss: 0.7385 - val_mae: 0.6331 - val_rmse: 0.7964 - val_smape: 1.2258

Epoch 41/256

120/120 - 1s - 9ms/step - ia: 0.4062 - loss: 0.7940 - mae: 0.6522 - rmse: 0.8888 - smape: 1.2557 - val_ia: 0.3598 - val_loss: 0.7421 - val_mae: 0.6355 - val_rmse: 0.7992 - val_smape: 1.2330

Epoch 42/256

120/120 - 1s - 11ms/step - ia: 0.4091 - loss: 0.7940 - mae: 0.6508 - rmse: 0.8879 - smape: 1.2489 - val_ia: 0.3596 - val_loss: 0.7401 - val_mae: 0.6337 - val_rmse: 0.7974 - val_smape: 1.2279

Epoch 43/256

120/120 - 1s - 10ms/step - ia: 0.4092 - loss: 0.7923 - mae: 0.6507 - rmse: 0.8873 - smape: 1.2514 - val_ia: 0.3607 - val_loss: 0.7411 - val_mae: 0.6340 - val_rmse: 0.7981 - val_smape: 1.2276

Epoch 44/256

120/120 - 1s - 9ms/step - ia: 0.4100 - loss: 0.7910 - mae: 0.6498 - rmse: 0.8861 - smape: 1.2498 - val_ia: 0.3602 - val_loss: 0.7394 - val_mae: 0.6328 - val_rmse: 0.7968 - val_smape: 1.2256

Epoch 45/256

120/120 - 1s - 10ms/step - ia: 0.4102 - loss: 0.7880 - mae: 0.6495 - rmse: 0.8860 - smape: 1.2497 - val_ia: 0.3627 - val_loss: 0.7404 - val_mae: 0.6331 - val_rmse: 0.7976 - val_smape: 1.2245

Epoch 46/256

120/120 - 1s - 9ms/step - ia: 0.4081 - loss: 0.7918 - mae: 0.6504 - rmse: 0.8872 - smape: 1.2515 - val_ia: 0.3640 - val_loss: 0.7435 - val_mae: 0.6346 - val_rmse: 0.7997 - val_smape: 1.2256

Epoch 47/256

120/120 - 1s - 9ms/step - ia: 0.4115 - loss: 0.7904 - mae: 0.6492 - rmse: 0.8865 - smape: 1.2467 - val_ia: 0.3644 - val_loss: 0.7443 - val_mae: 0.6343 - val_rmse: 0.7997 - val_smape: 1.2208

Epoch 48/256

120/120 - 1s - 8ms/step - ia: 0.4121 - loss: 0.7878 - mae: 0.6485 - rmse: 0.8851 - smape: 1.2479 - val_ia: 0.3653 - val_loss: 0.7447 - val_mae: 0.6344 - val_rmse: 0.8000 - val_smape: 1.2230

Epoch 49/256

120/120 - 1s - 8ms/step - ia: 0.4137 - loss: 0.7865 - mae: 0.6473 - rmse: 0.8844 - smape: 1.2441 - val_ia: 0.3654 - val_loss: 0.7441 - val_mae: 0.6343 - val_rmse: 0.7999 - val_smape: 1.2251

Epoch 50/256

120/120 - 1s - 8ms/step - ia: 0.4106 - loss: 0.7883 - mae: 0.6488 - rmse: 0.8853 - smape: 1.2501 - val_ia: 0.3671 - val_loss: 0.7485 - val_mae: 0.6358 - val_rmse: 0.8024 - val_smape: 1.2240

Epoch 51/256

120/120 - 1s - 8ms/step - ia: 0.4134 - loss: 0.7869 - mae: 0.6484 - rmse: 0.8839 - smape: 1.2455 - val_ia: 0.3650 - val_loss: 0.7434 - val_mae: 0.6344 - val_rmse: 0.7997 - val_smape: 1.2269

Epoch 52/256

120/120 - 1s - 8ms/step - ia: 0.4109 - loss: 0.7865 - mae: 0.6487 - rmse: 0.8843 - smape: 1.2478 - val_ia: 0.3673 - val_loss: 0.7449 - val_mae: 0.6336 - val_rmse: 0.7999 - val_smape: 1.2204

Epoch 53/256

120/120 - 1s - 12ms/step - ia: 0.4142 - loss: 0.7872 - mae: 0.6480 - rmse: 0.8844 - smape: 1.2425 - val_ia: 0.3654 - val_loss: 0.7428 - val_mae: 0.6336 - val_rmse: 0.7990 - val_smape: 1.2255

Epoch 54/256

120/120 - 1s - 9ms/step - ia: 0.4146 - loss: 0.7843 - mae: 0.6471 - rmse: 0.8825 - smape: 1.2450 - val_ia: 0.3643 - val_loss: 0.7418 - val_mae: 0.6344 - val_rmse: 0.7990 - val_smape: 1.2337

Epoch 55/256

120/120 - 1s - 9ms/step - ia: 0.4130 - loss: 0.7826 - mae: 0.6470 - rmse: 0.8822 - smape: 1.2460 - val_ia: 0.3697 - val_loss: 0.7481 - val_mae: 0.6344 - val_rmse: 0.8018 - val_smape: 1.2204

Epoch 55: early stopping

Restoring model weights from the end of the best epoch: 40.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:41 752ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 96%|█████████▌| 48/50 [8:48:05<18:53, 566.80s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 28s - 29ms/step - ia: 0.2844 - loss: 1.0469 - mae: 0.7551 - rmse: 0.9981 - smape: 1.4409 - val_ia: 0.2488 - val_loss: 0.8187 - val_mae: 0.6639 - val_rmse: 0.7505 - val_smape: 1.3924

Epoch 2/16

958/958 - 12s - 12ms/step - ia: 0.3382 - loss: 0.8876 - mae: 0.6975 - rmse: 0.9239 - smape: 1.3528 - val_ia: 0.2554 - val_loss: 0.7846 - val_mae: 0.6490 - val_rmse: 0.7398 - val_smape: 1.2844

Epoch 3/16

958/958 - 11s - 12ms/step - ia: 0.3622 - loss: 0.8551 - mae: 0.6815 - rmse: 0.9074 - smape: 1.3101 - val_ia: 0.2564 - val_loss: 0.7777 - val_mae: 0.6509 - val_rmse: 0.7427 - val_smape: 1.2777

Epoch 4/16

958/958 - 21s - 22ms/step - ia: 0.3713 - loss: 0.8426 - mae: 0.6768 - rmse: 0.8989 - smape: 1.2997 - val_ia: 0.2563 - val_loss: 0.7720 - val_mae: 0.6473 - val_rmse: 0.7392 - val_smape: 1.2688

Epoch 5/16

958/958 - 11s - 12ms/step - ia: 0.3759 - loss: 0.8338 - mae: 0.6718 - rmse: 0.8934 - smape: 1.2902 - val_ia: 0.2570 - val_loss: 0.7660 - val_mae: 0.6440 - val_rmse: 0.7365 - val_smape: 1.2584

Epoch 6/16

958/958 - 12s - 12ms/step - ia: 0.3774 - loss: 0.8312 - mae: 0.6709 - rmse: 0.8938 - smape: 1.2882 - val_ia: 0.2577 - val_loss: 0.7640 - val_mae: 0.6473 - val_rmse: 0.7401 - val_smape: 1.2678

Epoch 7/16

958/958 - 12s - 13ms/step - ia: 0.3810 - loss: 0.8246 - mae: 0.6689 - rmse: 0.8914 - smape: 1.2836 - val_ia: 0.2578 - val_loss: 0.7622 - val_mae: 0.6488 - val_rmse: 0.7419 - val_smape: 1.2694

Epoch 8/16

958/958 - 12s - 12ms/step - ia: 0.3833 - loss: 0.8219 - mae: 0.6670 - rmse: 0.8879 - smape: 1.2809 - val_ia: 0.2574 - val_loss: 0.7590 - val_mae: 0.6426 - val_rmse: 0.7362 - val_smape: 1.2545

Epoch 9/16

958/958 - 11s - 12ms/step - ia: 0.3877 - loss: 0.8181 - mae: 0.6637 - rmse: 0.8862 - smape: 1.2724 - val_ia: 0.2578 - val_loss: 0.7579 - val_mae: 0.6442 - val_rmse: 0.7382 - val_smape: 1.2550

Epoch 10/16

958/958 - 12s - 12ms/step - ia: 0.3895 - loss: 0.8157 - mae: 0.6631 - rmse: 0.8860 - smape: 1.2711 - val_ia: 0.2566 - val_loss: 0.7584 - val_mae: 0.6478 - val_rmse: 0.7403 - val_smape: 1.2837

Epoch 11/16

958/958 - 11s - 12ms/step - ia: 0.3878 - loss: 0.8162 - mae: 0.6630 - rmse: 0.8858 - smape: 1.2738 - val_ia: 0.2576 - val_loss: 0.7516 - val_mae: 0.6350 - val_rmse: 0.7291 - val_smape: 1.2391

Epoch 12/16

958/958 - 10s - 11ms/step - ia: 0.3917 - loss: 0.8129 - mae: 0.6609 - rmse: 0.8843 - smape: 1.2688 - val_ia: 0.2568 - val_loss: 0.7540 - val_mae: 0.6432 - val_rmse: 0.7366 - val_smape: 1.2702

Epoch 13/16

958/958 - 10s - 11ms/step - ia: 0.3912 - loss: 0.8095 - mae: 0.6607 - rmse: 0.8820 - smape: 1.2700 - val_ia: 0.2569 - val_loss: 0.7545 - val_mae: 0.6446 - val_rmse: 0.7385 - val_smape: 1.2721

Epoch 14/16

958/958 - 12s - 12ms/step - ia: 0.3919 - loss: 0.8085 - mae: 0.6597 - rmse: 0.8800 - smape: 1.2689 - val_ia: 0.2575 - val_loss: 0.7517 - val_mae: 0.6416 - val_rmse: 0.7357 - val_smape: 1.2632

Epoch 15/16

958/958 - 12s - 13ms/step - ia: 0.3935 - loss: 0.8076 - mae: 0.6590 - rmse: 0.8811 - smape: 1.2666 - val_ia: 0.2571 - val_loss: 0.7521 - val_mae: 0.6402 - val_rmse: 0.7348 - val_smape: 1.2564

Epoch 16/16

958/958 - 12s - 12ms/step - ia: 0.3947 - loss: 0.8062 - mae: 0.6583 - rmse: 0.8803 - smape: 1.2661 - val_ia: 0.2572 - val_loss: 0.7518 - val_mae: 0.6427 - val_rmse: 0.7369 - val_smape: 1.2688

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:51 2s/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

 98%|█████████▊| 49/50 [8:51:39<07:41, 461.00s/trial, best loss: 0.7632547446416105]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 12s - 50ms/step - ia: 0.2859 - loss: 0.9719 - mae: 0.7370 - rmse: 0.9781 - smape: 1.4358 - val_ia: 0.3005 - val_loss: 0.7832 - val_mae: 0.6514 - val_rmse: 0.7961 - val_smape: 1.2869

Epoch 2/128

240/240 - 3s - 11ms/step - ia: 0.3736 - loss: 0.8523 - mae: 0.6837 - rmse: 0.9182 - smape: 1.3106 - val_ia: 0.3171 - val_loss: 0.7623 - val_mae: 0.6412 - val_rmse: 0.7872 - val_smape: 1.2567

Epoch 3/128

240/240 - 3s - 12ms/step - ia: 0.3780 - loss: 0.8399 - mae: 0.6771 - rmse: 0.9125 - smape: 1.3048 - val_ia: 0.3253 - val_loss: 0.7577 - val_mae: 0.6382 - val_rmse: 0.7862 - val_smape: 1.2402

Epoch 4/128

240/240 - 3s - 12ms/step - ia: 0.3875 - loss: 0.8340 - mae: 0.6735 - rmse: 0.9089 - smape: 1.2886 - val_ia: 0.3189 - val_loss: 0.7541 - val_mae: 0.6400 - val_rmse: 0.7851 - val_smape: 1.2654

Epoch 5/128

240/240 - 3s - 12ms/step - ia: 0.3834 - loss: 0.8291 - mae: 0.6721 - rmse: 0.9055 - smape: 1.2962 - val_ia: 0.3244 - val_loss: 0.7501 - val_mae: 0.6361 - val_rmse: 0.7829 - val_smape: 1.2483

Epoch 6/128

240/240 - 3s - 11ms/step - ia: 0.3917 - loss: 0.8230 - mae: 0.6667 - rmse: 0.9020 - smape: 1.2810 - val_ia: 0.3251 - val_loss: 0.7542 - val_mae: 0.6418 - val_rmse: 0.7883 - val_smape: 1.2747

Epoch 7/128

240/240 - 3s - 11ms/step - ia: 0.3904 - loss: 0.8186 - mae: 0.6664 - rmse: 0.8988 - smape: 1.2849 - val_ia: 0.3292 - val_loss: 0.7463 - val_mae: 0.6356 - val_rmse: 0.7835 - val_smape: 1.2435

Epoch 8/128

240/240 - 3s - 11ms/step - ia: 0.3974 - loss: 0.8105 - mae: 0.6616 - rmse: 0.8953 - smape: 1.2761 - val_ia: 0.3284 - val_loss: 0.7443 - val_mae: 0.6363 - val_rmse: 0.7832 - val_smape: 1.2558

Epoch 9/128

240/240 - 3s - 11ms/step - ia: 0.4001 - loss: 0.8089 - mae: 0.6597 - rmse: 0.8946 - smape: 1.2715 - val_ia: 0.3309 - val_loss: 0.7441 - val_mae: 0.6372 - val_rmse: 0.7843 - val_smape: 1.2653

Epoch 10/128

240/240 - 3s - 12ms/step - ia: 0.4029 - loss: 0.8038 - mae: 0.6570 - rmse: 0.8911 - smape: 1.2646 - val_ia: 0.3310 - val_loss: 0.7429 - val_mae: 0.6384 - val_rmse: 0.7855 - val_smape: 1.2658

Epoch 11/128

240/240 - 3s - 13ms/step - ia: 0.4041 - loss: 0.8021 - mae: 0.6569 - rmse: 0.8891 - smape: 1.2672 - val_ia: 0.3341 - val_loss: 0.7421 - val_mae: 0.6359 - val_rmse: 0.7840 - val_smape: 1.2567

Epoch 12/128

240/240 - 3s - 12ms/step - ia: 0.4078 - loss: 0.7974 - mae: 0.6548 - rmse: 0.8874 - smape: 1.2604 - val_ia: 0.3324 - val_loss: 0.7380 - val_mae: 0.6350 - val_rmse: 0.7819 - val_smape: 1.2599

Epoch 13/128

240/240 - 3s - 13ms/step - ia: 0.4097 - loss: 0.7943 - mae: 0.6528 - rmse: 0.8854 - smape: 1.2580 - val_ia: 0.3348 - val_loss: 0.7356 - val_mae: 0.6331 - val_rmse: 0.7802 - val_smape: 1.2606

Epoch 14/128

240/240 - 3s - 13ms/step - ia: 0.4085 - loss: 0.7956 - mae: 0.6527 - rmse: 0.8883 - smape: 1.2573 - val_ia: 0.3351 - val_loss: 0.7371 - val_mae: 0.6314 - val_rmse: 0.7801 - val_smape: 1.2390

Epoch 15/128

240/240 - 3s - 13ms/step - ia: 0.4121 - loss: 0.7917 - mae: 0.6505 - rmse: 0.8850 - smape: 1.2506 - val_ia: 0.3410 - val_loss: 0.7488 - val_mae: 0.6395 - val_rmse: 0.7904 - val_smape: 1.2584

Epoch 16/128

240/240 - 3s - 13ms/step - ia: 0.4104 - loss: 0.7893 - mae: 0.6502 - rmse: 0.8843 - smape: 1.2537 - val_ia: 0.3410 - val_loss: 0.7491 - val_mae: 0.6370 - val_rmse: 0.7888 - val_smape: 1.2421

Epoch 17/128

240/240 - 5s - 21ms/step - ia: 0.4130 - loss: 0.7902 - mae: 0.6499 - rmse: 0.8847 - smape: 1.2498 - val_ia: 0.3372 - val_loss: 0.7424 - val_mae: 0.6345 - val_rmse: 0.7842 - val_smape: 1.2440

Epoch 18/128

240/240 - 5s - 22ms/step - ia: 0.4154 - loss: 0.7868 - mae: 0.6476 - rmse: 0.8814 - smape: 1.2453 - val_ia: 0.3420 - val_loss: 0.7454 - val_mae: 0.6368 - val_rmse: 0.7881 - val_smape: 1.2476

Epoch 19/128

240/240 - 3s - 12ms/step - ia: 0.4145 - loss: 0.7839 - mae: 0.6475 - rmse: 0.8801 - smape: 1.2482 - val_ia: 0.3444 - val_loss: 0.7496 - val_mae: 0.6365 - val_rmse: 0.7898 - val_smape: 1.2395

Epoch 20/128

240/240 - 3s - 11ms/step - ia: 0.4164 - loss: 0.7827 - mae: 0.6476 - rmse: 0.8795 - smape: 1.2480 - val_ia: 0.3460 - val_loss: 0.7484 - val_mae: 0.6352 - val_rmse: 0.7888 - val_smape: 1.2368

Epoch 21/128

240/240 - 3s - 12ms/step - ia: 0.4180 - loss: 0.7818 - mae: 0.6456 - rmse: 0.8793 - smape: 1.2446 - val_ia: 0.3445 - val_loss: 0.7452 - val_mae: 0.6360 - val_rmse: 0.7880 - val_smape: 1.2445

Epoch 22/128

240/240 - 5s - 21ms/step - ia: 0.4185 - loss: 0.7789 - mae: 0.6451 - rmse: 0.8776 - smape: 1.2421 - val_ia: 0.3456 - val_loss: 0.7448 - val_mae: 0.6293 - val_rmse: 0.7835 - val_smape: 1.2102

Epoch 23/128

240/240 - 3s - 12ms/step - ia: 0.4192 - loss: 0.7792 - mae: 0.6453 - rmse: 0.8777 - smape: 1.2413 - val_ia: 0.3467 - val_loss: 0.7486 - val_mae: 0.6348 - val_rmse: 0.7890 - val_smape: 1.2327

Epoch 24/128

240/240 - 4s - 15ms/step - ia: 0.4220 - loss: 0.7755 - mae: 0.6439 - rmse: 0.8767 - smape: 1.2385 - val_ia: 0.3448 - val_loss: 0.7438 - val_mae: 0.6315 - val_rmse: 0.7846 - val_smape: 1.2247

Epoch 25/128

240/240 - 3s - 13ms/step - ia: 0.4215 - loss: 0.7765 - mae: 0.6437 - rmse: 0.8777 - smape: 1.2371 - val_ia: 0.3476 - val_loss: 0.7399 - val_mae: 0.6318 - val_rmse: 0.7841 - val_smape: 1.2337

Epoch 26/128

240/240 - 3s - 13ms/step - ia: 0.4221 - loss: 0.7765 - mae: 0.6435 - rmse: 0.8759 - smape: 1.2372 - val_ia: 0.3476 - val_loss: 0.7392 - val_mae: 0.6330 - val_rmse: 0.7848 - val_smape: 1.2394

Epoch 27/128

240/240 - 3s - 13ms/step - ia: 0.4215 - loss: 0.7729 - mae: 0.6425 - rmse: 0.8742 - smape: 1.2385 - val_ia: 0.3473 - val_loss: 0.7459 - val_mae: 0.6355 - val_rmse: 0.7887 - val_smape: 1.2402

Epoch 28/128

240/240 - 3s - 14ms/step - ia: 0.4233 - loss: 0.7710 - mae: 0.6411 - rmse: 0.8725 - smape: 1.2331 - val_ia: 0.3469 - val_loss: 0.7413 - val_mae: 0.6315 - val_rmse: 0.7840 - val_smape: 1.2274

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:21 604ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

100%|██████████| 50/50 [8:53:19<00:00, 640.00s/trial, best loss: 0.7632547446416105]

In [23]:
print(best)

{'activation': 1, 'batch': 2, 'dropout': 0.2, 'epochs': 4, 'layers': 1.0, 'learning_rate': 0.0002707756079796208, 'units': 4}