Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\Desktop\\pruebas_collab\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(37)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823
2017-01-01 02:10:00 -2.308740 -1.464790 -1.131650 -0.649995 -1.371823
2017-01-01 02:20:00 -2.307607 -1.497449 -1.188510 -0.673256 -1.371823
2017-01-01 02:30:00 -2.320226 -1.523410 -1.251127 -0.684886 -1.371823
2017-01-01 02:40:00 -2.300328 -1.553557 -1.278478 -0.698305 -1.371823
2017-01-01 02:50:00 -2.237721 -1.581192 -1.348293 -0.725144 -1.371823
2017-01-01 03:00:00 -2.276223 -1.633112 -1.363408 -0.755561 -1.227305
2017-01-01 03:10:00 -2.290459 -1.648186 -1.395796 -0.768086 -1.227305
2017-01-01 03:20:00 -2.296930 -1.665772 -1.430344 -0.775243 -1.227305
2017-01-01 03:30:00 -2.298063 -1.665772 -1.436102 -0.793136 -1.227305
2017-01-01 03:40:00 -2.320388 -1.703456 -1.441860 -0.838762 -1.227305
2017-01-01 03:50:00 -2.335109 -1.727742 -1.487204 -0.840551 -1.227305
2017-01-01 04:00:00 -2.343522 -1.713505 -1.504477 -0.841445 -1.082788
2017-01-01 04:10:00 -2.319579 -1.719367 -1.462732 -0.862022 -1.082788
2017-01-01 04:20:00 -2.270723 -1.712668 -1.483605 -0.896018 -1.082788
2017-01-01 04:30:00 -2.239824 -1.715180 -1.479286 -0.907648 -1.082788
2017-01-01 04:40:00 -2.278326 -1.717693 -1.484325 -0.896018 -1.082788
2017-01-01 04:50:00 -2.274605 -1.742815 -1.492962 -0.894228 -1.082788
2017-01-01 05:00:00 -2.314240 -1.710993 -1.507356 -0.894228 -0.938270
2017-01-01 05:10:00 -2.349184 -1.700107 -1.498000 -0.915699 -0.938270
2017-01-01 05:20:00 -2.215234 -1.699269 -1.500159 -0.890650 -0.938270
2017-01-01 05:30:00 -2.358890 -1.675821 -1.441860 -0.877230 -0.938270
2017-01-01 05:40:00 -2.403540 -1.667447 -1.428904 -0.848602 -0.938270
2017-01-01 05:50:00 -2.431042 -1.593753 -1.355490 -0.798503 -0.938270
2017-01-01 06:00:00 -2.415511 -1.479863 -1.258325 -0.791346 -0.793753

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [15]:
print(datosY[0])

[-1.59375341]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 12, 5)
Las dimensiones de testX son:  (10529, 12, 5)
Las dimensiones de valX son:  (5186, 12, 5)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 57s - 49ms/step - ia: 0.5085 - loss: 0.6067 - mae: 0.6334 - rmse: 0.7696 - smape: 1.1461 - val_ia: 0.2861 - val_loss: 0.8767 - val_mae: 0.7783 - val_rmse: 0.8430 - val_smape: 1.2252

Epoch 2/128

1146/1146 - 27s - 24ms/step - ia: 0.6525 - loss: 0.3908 - mae: 0.5014 - rmse: 0.6201 - smape: 0.8963 - val_ia: 0.2893 - val_loss: 0.9018 - val_mae: 0.7791 - val_rmse: 0.8448 - val_smape: 1.1804

Epoch 3/128

1146/1146 - 46s - 40ms/step - ia: 0.6887 - loss: 0.3367 - mae: 0.4613 - rmse: 0.5756 - smape: 0.8325 - val_ia: 0.2995 - val_loss: 0.7411 - val_mae: 0.7119 - val_rmse: 0.7755 - val_smape: 1.1236

Epoch 4/128

1146/1146 - 29s - 25ms/step - ia: 0.7049 - loss: 0.3084 - mae: 0.4394 - rmse: 0.5505 - smape: 0.8094 - val_ia: 0.3057 - val_loss: 0.6868 - val_mae: 0.6767 - val_rmse: 0.7454 - val_smape: 1.0681

Epoch 5/128

1146/1146 - 40s - 35ms/step - ia: 0.7204 - loss: 0.2816 - mae: 0.4179 - rmse: 0.5258 - smape: 0.7938 - val_ia: 0.3293 - val_loss: 0.5655 - val_mae: 0.6170 - val_rmse: 0.6770 - val_smape: 1.0060

Epoch 6/128

1146/1146 - 26s - 23ms/step - ia: 0.7380 - loss: 0.2507 - mae: 0.3921 - rmse: 0.4957 - smape: 0.7656 - val_ia: 0.3555 - val_loss: 0.5390 - val_mae: 0.6012 - val_rmse: 0.6549 - val_smape: 0.9817

Epoch 7/128

1146/1146 - 42s - 37ms/step - ia: 0.7532 - loss: 0.2254 - mae: 0.3708 - rmse: 0.4699 - smape: 0.7408 - val_ia: 0.3762 - val_loss: 0.5081 - val_mae: 0.5753 - val_rmse: 0.6296 - val_smape: 0.9565

Epoch 8/128

1146/1146 - 20s - 18ms/step - ia: 0.7646 - loss: 0.2102 - mae: 0.3550 - rmse: 0.4533 - smape: 0.7167 - val_ia: 0.3792 - val_loss: 0.5223 - val_mae: 0.5805 - val_rmse: 0.6360 - val_smape: 0.9667

Epoch 9/128

1146/1146 - 32s - 27ms/step - ia: 0.7686 - loss: 0.2033 - mae: 0.3484 - rmse: 0.4460 - smape: 0.7118 - val_ia: 0.3964 - val_loss: 0.4583 - val_mae: 0.5436 - val_rmse: 0.5970 - val_smape: 0.9261

Epoch 10/128

1146/1146 - 29s - 26ms/step - ia: 0.7746 - loss: 0.1945 - mae: 0.3406 - rmse: 0.4362 - smape: 0.7001 - val_ia: 0.3899 - val_loss: 0.4975 - val_mae: 0.5698 - val_rmse: 0.6221 - val_smape: 0.9536

Epoch 11/128

1146/1146 - 30s - 26ms/step - ia: 0.7776 - loss: 0.1903 - mae: 0.3363 - rmse: 0.4309 - smape: 0.6954 - val_ia: 0.3928 - val_loss: 0.4739 - val_mae: 0.5505 - val_rmse: 0.6056 - val_smape: 0.9432

Epoch 12/128

1146/1146 - 28s - 25ms/step - ia: 0.7795 - loss: 0.1874 - mae: 0.3329 - rmse: 0.4278 - smape: 0.6919 - val_ia: 0.3906 - val_loss: 0.4913 - val_mae: 0.5571 - val_rmse: 0.6151 - val_smape: 0.9441

Epoch 13/128

1146/1146 - 26s - 23ms/step - ia: 0.7846 - loss: 0.1812 - mae: 0.3267 - rmse: 0.4205 - smape: 0.6832 - val_ia: 0.3901 - val_loss: 0.4997 - val_mae: 0.5531 - val_rmse: 0.6149 - val_smape: 0.9426

Epoch 14/128

1146/1146 - 24s - 21ms/step - ia: 0.7860 - loss: 0.1781 - mae: 0.3237 - rmse: 0.4175 - smape: 0.6803 - val_ia: 0.4026 - val_loss: 0.4571 - val_mae: 0.5318 - val_rmse: 0.5907 - val_smape: 0.9309

Epoch 15/128

1146/1146 - 29s - 25ms/step - ia: 0.7872 - loss: 0.1753 - mae: 0.3217 - rmse: 0.4137 - smape: 0.6796 - val_ia: 0.3996 - val_loss: 0.4830 - val_mae: 0.5429 - val_rmse: 0.6062 - val_smape: 0.9235

Epoch 16/128

1146/1146 - 27s - 23ms/step - ia: 0.7891 - loss: 0.1727 - mae: 0.3187 - rmse: 0.4105 - smape: 0.6772 - val_ia: 0.4054 - val_loss: 0.4659 - val_mae: 0.5313 - val_rmse: 0.5937 - val_smape: 0.9179

Epoch 17/128

1146/1146 - 23s - 20ms/step - ia: 0.7909 - loss: 0.1703 - mae: 0.3170 - rmse: 0.4076 - smape: 0.6751 - val_ia: 0.3899 - val_loss: 0.5796 - val_mae: 0.5782 - val_rmse: 0.6506 - val_smape: 0.9452

Epoch 18/128

1146/1146 - 29s - 25ms/step - ia: 0.7925 - loss: 0.1692 - mae: 0.3145 - rmse: 0.4064 - smape: 0.6695 - val_ia: 0.4012 - val_loss: 0.4886 - val_mae: 0.5358 - val_rmse: 0.6040 - val_smape: 0.9189

Epoch 19/128

1146/1146 - 30s - 26ms/step - ia: 0.7938 - loss: 0.1667 - mae: 0.3130 - rmse: 0.4036 - smape: 0.6667 - val_ia: 0.3956 - val_loss: 0.5198 - val_mae: 0.5481 - val_rmse: 0.6193 - val_smape: 0.9266

Epoch 20/128

1146/1146 - 26s - 22ms/step - ia: 0.7942 - loss: 0.1670 - mae: 0.3120 - rmse: 0.4035 - smape: 0.6635 - val_ia: 0.3960 - val_loss: 0.5239 - val_mae: 0.5519 - val_rmse: 0.6241 - val_smape: 0.9281

Epoch 21/128

1146/1146 - 27s - 23ms/step - ia: 0.7961 - loss: 0.1643 - mae: 0.3098 - rmse: 0.4007 - smape: 0.6609 - val_ia: 0.3822 - val_loss: 0.6298 - val_mae: 0.5939 - val_rmse: 0.6739 - val_smape: 0.9413

Epoch 22/128

1146/1146 - 27s - 24ms/step - ia: 0.7964 - loss: 0.1641 - mae: 0.3092 - rmse: 0.4003 - smape: 0.6595 - val_ia: 0.4063 - val_loss: 0.4883 - val_mae: 0.5250 - val_rmse: 0.5982 - val_smape: 0.8956

Epoch 23/128

1146/1146 - 45s - 39ms/step - ia: 0.7973 - loss: 0.1619 - mae: 0.3078 - rmse: 0.3974 - smape: 0.6591 - val_ia: 0.3855 - val_loss: 0.5770 - val_mae: 0.5713 - val_rmse: 0.6512 - val_smape: 0.9245

Epoch 24/128

1146/1146 - 21s - 19ms/step - ia: 0.7987 - loss: 0.1602 - mae: 0.3063 - rmse: 0.3955 - smape: 0.6604 - val_ia: 0.3925 - val_loss: 0.5488 - val_mae: 0.5581 - val_rmse: 0.6360 - val_smape: 0.9184

Epoch 25/128

1146/1146 - 27s - 24ms/step - ia: 0.7994 - loss: 0.1588 - mae: 0.3050 - rmse: 0.3937 - smape: 0.6560 - val_ia: 0.3938 - val_loss: 0.5422 - val_mae: 0.5510 - val_rmse: 0.6312 - val_smape: 0.9132

Epoch 26/128

1146/1146 - 20s - 18ms/step - ia: 0.8003 - loss: 0.1581 - mae: 0.3034 - rmse: 0.3932 - smape: 0.6539 - val_ia: 0.3950 - val_loss: 0.5517 - val_mae: 0.5552 - val_rmse: 0.6330 - val_smape: 0.9066

Epoch 27/128

1146/1146 - 21s - 18ms/step - ia: 0.8006 - loss: 0.1580 - mae: 0.3033 - rmse: 0.3926 - smape: 0.6543 - val_ia: 0.3871 - val_loss: 0.6007 - val_mae: 0.5713 - val_rmse: 0.6568 - val_smape: 0.9145

Epoch 28/128

1146/1146 - 18s - 16ms/step - ia: 0.8025 - loss: 0.1553 - mae: 0.3010 - rmse: 0.3894 - smape: 0.6494 - val_ia: 0.3916 - val_loss: 0.5319 - val_mae: 0.5471 - val_rmse: 0.6289 - val_smape: 0.9041

Epoch 29/128

1146/1146 - 19s - 17ms/step - ia: 0.8019 - loss: 0.1558 - mae: 0.3014 - rmse: 0.3901 - smape: 0.6520 - val_ia: 0.3860 - val_loss: 0.5597 - val_mae: 0.5569 - val_rmse: 0.6403 - val_smape: 0.9198

Epoch 29: early stopping

Restoring model weights from the end of the best epoch: 14.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:38 2s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step

  2%|▏         | 1/50 [14:12<11:36:27, 852.81s/trial, best loss: 0.5969085779931618]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 52s - 362ms/step - ia: 0.6397 - loss: 0.3715 - mae: 0.4688 - rmse: 0.5830 - smape: 0.9209 - val_ia: 0.6020 - val_loss: 0.5068 - val_mae: 0.5843 - val_rmse: 0.6800 - val_smape: 1.0461

Epoch 2/16

144/144 - 37s - 259ms/step - ia: 0.8207 - loss: 0.1425 - mae: 0.2841 - rmse: 0.3755 - smape: 0.6389 - val_ia: 0.6889 - val_loss: 0.2994 - val_mae: 0.4360 - val_rmse: 0.5310 - val_smape: 0.9005

Epoch 3/16

144/144 - 17s - 116ms/step - ia: 0.8548 - loss: 0.0986 - mae: 0.2309 - rmse: 0.3129 - smape: 0.5761 - val_ia: 0.7384 - val_loss: 0.2117 - val_mae: 0.3572 - val_rmse: 0.4407 - val_smape: 0.7567

Epoch 4/16

144/144 - 20s - 137ms/step - ia: 0.8678 - loss: 0.0846 - mae: 0.2114 - rmse: 0.2900 - smape: 0.5338 - val_ia: 0.7699 - val_loss: 0.1682 - val_mae: 0.3306 - val_rmse: 0.4029 - val_smape: 0.6899

Epoch 5/16

144/144 - 16s - 109ms/step - ia: 0.8765 - loss: 0.0751 - mae: 0.1980 - rmse: 0.2733 - smape: 0.5041 - val_ia: 0.7592 - val_loss: 0.1889 - val_mae: 0.3396 - val_rmse: 0.4145 - val_smape: 0.6915

Epoch 6/16

144/144 - 18s - 124ms/step - ia: 0.8838 - loss: 0.0679 - mae: 0.1871 - rmse: 0.2602 - smape: 0.4807 - val_ia: 0.7663 - val_loss: 0.1826 - val_mae: 0.3333 - val_rmse: 0.4126 - val_smape: 0.6812

Epoch 7/16

144/144 - 18s - 127ms/step - ia: 0.8858 - loss: 0.0653 - mae: 0.1844 - rmse: 0.2545 - smape: 0.4743 - val_ia: 0.7477 - val_loss: 0.2183 - val_mae: 0.3603 - val_rmse: 0.4398 - val_smape: 0.7218

Epoch 8/16

144/144 - 22s - 156ms/step - ia: 0.8899 - loss: 0.0609 - mae: 0.1781 - rmse: 0.2459 - smape: 0.4607 - val_ia: 0.7573 - val_loss: 0.2026 - val_mae: 0.3438 - val_rmse: 0.4272 - val_smape: 0.7048

Epoch 9/16

144/144 - 21s - 143ms/step - ia: 0.8904 - loss: 0.0601 - mae: 0.1771 - rmse: 0.2448 - smape: 0.4571 - val_ia: 0.7641 - val_loss: 0.1802 - val_mae: 0.3310 - val_rmse: 0.4125 - val_smape: 0.7025

Epoch 10/16

144/144 - 21s - 148ms/step - ia: 0.8926 - loss: 0.0579 - mae: 0.1742 - rmse: 0.2394 - smape: 0.4524 - val_ia: 0.7497 - val_loss: 0.2422 - val_mae: 0.3668 - val_rmse: 0.4662 - val_smape: 0.7159

Epoch 11/16

144/144 - 22s - 152ms/step - ia: 0.8963 - loss: 0.0541 - mae: 0.1681 - rmse: 0.2322 - smape: 0.4421 - val_ia: 0.7215 - val_loss: 0.3242 - val_mae: 0.4156 - val_rmse: 0.5399 - val_smape: 0.7594

Epoch 12/16

144/144 - 20s - 136ms/step - ia: 0.8969 - loss: 0.0533 - mae: 0.1673 - rmse: 0.2301 - smape: 0.4390 - val_ia: 0.7588 - val_loss: 0.2192 - val_mae: 0.3477 - val_rmse: 0.4399 - val_smape: 0.7076

Epoch 13/16

144/144 - 17s - 120ms/step - ia: 0.9008 - loss: 0.0498 - mae: 0.1615 - rmse: 0.2223 - smape: 0.4277 - val_ia: 0.7279 - val_loss: 0.2842 - val_mae: 0.3900 - val_rmse: 0.5038 - val_smape: 0.7565

Epoch 14/16

144/144 - 22s - 152ms/step - ia: 0.9010 - loss: 0.0495 - mae: 0.1610 - rmse: 0.2215 - smape: 0.4275 - val_ia: 0.7412 - val_loss: 0.2589 - val_mae: 0.3682 - val_rmse: 0.4770 - val_smape: 0.7252

Epoch 15/16

144/144 - 19s - 132ms/step - ia: 0.9030 - loss: 0.0479 - mae: 0.1577 - rmse: 0.2182 - smape: 0.4204 - val_ia: 0.7331 - val_loss: 0.2707 - val_mae: 0.3824 - val_rmse: 0.4813 - val_smape: 0.7470

Epoch 16/16

144/144 - 20s - 139ms/step - ia: 0.9052 - loss: 0.0457 - mae: 0.1545 - rmse: 0.2130 - smape: 0.4162 - val_ia: 0.7086 - val_loss: 0.3279 - val_mae: 0.4182 - val_rmse: 0.5389 - val_smape: 0.7869

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8:37 3s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step

  4%|▍         | 2/50 [20:25<7:36:13, 570.29s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

573/573 - 36s - 63ms/step - ia: 0.1183 - loss: 0.9630 - mae: 0.8172 - rmse: 0.9789 - smape: 1.8304 - val_ia: 0.2869 - val_loss: 0.8265 - val_mae: 0.7564 - val_rmse: 0.8751 - val_smape: 1.7727

Epoch 2/8

573/573 - 9s - 16ms/step - ia: 0.1197 - loss: 0.9613 - mae: 0.8165 - rmse: 0.9784 - smape: 1.8260 - val_ia: 0.2870 - val_loss: 0.8254 - val_mae: 0.7561 - val_rmse: 0.8746 - val_smape: 1.7709

Epoch 3/8

573/573 - 11s - 19ms/step - ia: 0.1210 - loss: 0.9594 - mae: 0.8159 - rmse: 0.9771 - smape: 1.8230 - val_ia: 0.2872 - val_loss: 0.8244 - val_mae: 0.7557 - val_rmse: 0.8740 - val_smape: 1.7691

Epoch 4/8

573/573 - 11s - 20ms/step - ia: 0.1195 - loss: 0.9573 - mae: 0.8152 - rmse: 0.9760 - smape: 1.8193 - val_ia: 0.2874 - val_loss: 0.8232 - val_mae: 0.7553 - val_rmse: 0.8734 - val_smape: 1.7668

Epoch 5/8

573/573 - 8s - 14ms/step - ia: 0.1214 - loss: 0.9551 - mae: 0.8144 - rmse: 0.9749 - smape: 1.8152 - val_ia: 0.2876 - val_loss: 0.8221 - val_mae: 0.7549 - val_rmse: 0.8728 - val_smape: 1.7642

Epoch 6/8

573/573 - 8s - 14ms/step - ia: 0.1227 - loss: 0.9537 - mae: 0.8139 - rmse: 0.9742 - smape: 1.8106 - val_ia: 0.2877 - val_loss: 0.8209 - val_mae: 0.7545 - val_rmse: 0.8722 - val_smape: 1.7614

Epoch 7/8

573/573 - 10s - 18ms/step - ia: 0.1207 - loss: 0.9522 - mae: 0.8134 - rmse: 0.9734 - smape: 1.8072 - val_ia: 0.2879 - val_loss: 0.8197 - val_mae: 0.7541 - val_rmse: 0.8716 - val_smape: 1.7584

Epoch 8/8

573/573 - 12s - 21ms/step - ia: 0.1260 - loss: 0.9492 - mae: 0.8122 - rmse: 0.9719 - smape: 1.8012 - val_ia: 0.2881 - val_loss: 0.8184 - val_mae: 0.7536 - val_rmse: 0.8710 - val_smape: 1.7550

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:09 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step

  6%|▌         | 3/50 [22:25<4:45:36, 364.60s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 79s - 275ms/step - ia: 0.1862 - loss: 0.9470 - mae: 0.8047 - rmse: 0.9715 - smape: 1.5955 - val_ia: 0.2855 - val_loss: 0.8004 - val_mae: 0.7443 - val_rmse: 0.8861 - val_smape: 1.4916

Epoch 2/32

287/287 - 11s - 39ms/step - ia: 0.2959 - loss: 0.8092 - mae: 0.7525 - rmse: 0.8982 - smape: 1.4490 - val_ia: 0.3456 - val_loss: 0.8277 - val_mae: 0.7545 - val_rmse: 0.8986 - val_smape: 1.3746

Epoch 3/32

287/287 - 11s - 38ms/step - ia: 0.3726 - loss: 0.7286 - mae: 0.7142 - rmse: 0.8528 - smape: 1.3358 - val_ia: 0.3881 - val_loss: 0.9158 - val_mae: 0.7883 - val_rmse: 0.9417 - val_smape: 1.3338

Epoch 4/32

287/287 - 11s - 39ms/step - ia: 0.4326 - loss: 0.6652 - mae: 0.6802 - rmse: 0.8145 - smape: 1.2491 - val_ia: 0.4075 - val_loss: 1.0671 - val_mae: 0.8510 - val_rmse: 1.0132 - val_smape: 1.3345

Epoch 5/32

287/287 - 11s - 39ms/step - ia: 0.4898 - loss: 0.6100 - mae: 0.6456 - rmse: 0.7796 - smape: 1.1633 - val_ia: 0.4088 - val_loss: 1.2619 - val_mae: 0.9320 - val_rmse: 1.0993 - val_smape: 1.3567

Epoch 6/32

287/287 - 11s - 39ms/step - ia: 0.5250 - loss: 0.5802 - mae: 0.6242 - rmse: 0.7607 - smape: 1.1075 - val_ia: 0.4040 - val_loss: 1.4343 - val_mae: 1.0010 - val_rmse: 1.1701 - val_smape: 1.3772

Epoch 7/32

287/287 - 11s - 39ms/step - ia: 0.5501 - loss: 0.5599 - mae: 0.6088 - rmse: 0.7470 - smape: 1.0728 - val_ia: 0.4002 - val_loss: 1.5324 - val_mae: 1.0409 - val_rmse: 1.2070 - val_smape: 1.3937

Epoch 8/32

287/287 - 11s - 40ms/step - ia: 0.5650 - loss: 0.5443 - mae: 0.5972 - rmse: 0.7363 - smape: 1.0493 - val_ia: 0.3972 - val_loss: 1.6033 - val_mae: 1.0691 - val_rmse: 1.2320 - val_smape: 1.4047

Epoch 9/32

287/287 - 11s - 39ms/step - ia: 0.5766 - loss: 0.5289 - mae: 0.5865 - rmse: 0.7258 - smape: 1.0326 - val_ia: 0.3990 - val_loss: 1.6293 - val_mae: 1.0760 - val_rmse: 1.2395 - val_smape: 1.4010

Epoch 10/32

287/287 - 13s - 45ms/step - ia: 0.5869 - loss: 0.5137 - mae: 0.5769 - rmse: 0.7152 - smape: 1.0155 - val_ia: 0.3988 - val_loss: 1.6402 - val_mae: 1.0836 - val_rmse: 1.2399 - val_smape: 1.4089

Epoch 11/32

287/287 - 12s - 41ms/step - ia: 0.5962 - loss: 0.4984 - mae: 0.5673 - rmse: 0.7047 - smape: 0.9986 - val_ia: 0.4022 - val_loss: 1.6423 - val_mae: 1.0828 - val_rmse: 1.2381 - val_smape: 1.4028

Epoch 12/32

287/287 - 11s - 40ms/step - ia: 0.6037 - loss: 0.4879 - mae: 0.5608 - rmse: 0.6970 - smape: 0.9868 - val_ia: 0.4068 - val_loss: 1.6333 - val_mae: 1.0770 - val_rmse: 1.2325 - val_smape: 1.3925

Epoch 13/32

287/287 - 9s - 32ms/step - ia: 0.6154 - loss: 0.4685 - mae: 0.5485 - rmse: 0.6832 - smape: 0.9673 - val_ia: 0.4148 - val_loss: 1.5772 - val_mae: 1.0542 - val_rmse: 1.2084 - val_smape: 1.3745

Epoch 14/32

287/287 - 9s - 32ms/step - ia: 0.6235 - loss: 0.4568 - mae: 0.5399 - rmse: 0.6746 - smape: 0.9527 - val_ia: 0.4195 - val_loss: 1.5575 - val_mae: 1.0475 - val_rmse: 1.1988 - val_smape: 1.3657

Epoch 15/32

287/287 - 9s - 31ms/step - ia: 0.6307 - loss: 0.4456 - mae: 0.5332 - rmse: 0.6662 - smape: 0.9361 - val_ia: 0.4295 - val_loss: 1.4900 - val_mae: 1.0194 - val_rmse: 1.1703 - val_smape: 1.3398

Epoch 16/32

287/287 - 9s - 32ms/step - ia: 0.6390 - loss: 0.4331 - mae: 0.5253 - rmse: 0.6568 - smape: 0.9235 - val_ia: 0.4378 - val_loss: 1.4293 - val_mae: 0.9958 - val_rmse: 1.1448 - val_smape: 1.3193

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:57 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

  8%|▊         | 4/50 [26:33<4:04:25, 318.82s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4584/4584 - 64s - 14ms/step - ia: 0.2874 - loss: 1.4376 - mae: 0.9747 - rmse: 1.1672 - smape: 1.4527 - val_ia: 0.1423 - val_loss: 0.8886 - val_mae: 0.7633 - val_rmse: 0.7805 - val_smape: 1.3030

Epoch 2/64

4584/4584 - 40s - 9ms/step - ia: 0.2709 - loss: 1.2641 - mae: 0.9221 - rmse: 1.0968 - smape: 1.4972 - val_ia: 0.1387 - val_loss: 0.8419 - val_mae: 0.7544 - val_rmse: 0.7717 - val_smape: 1.4656

Epoch 3/64

4584/4584 - 49s - 11ms/step - ia: 0.2624 - loss: 1.2072 - mae: 0.9036 - rmse: 1.0722 - smape: 1.5222 - val_ia: 0.1395 - val_loss: 0.8397 - val_mae: 0.7591 - val_rmse: 0.7764 - val_smape: 1.6425

Epoch 4/64

4584/4584 - 46s - 10ms/step - ia: 0.2621 - loss: 1.1837 - mae: 0.8953 - rmse: 1.0635 - smape: 1.5241 - val_ia: 0.1390 - val_loss: 0.8447 - val_mae: 0.7635 - val_rmse: 0.7810 - val_smape: 1.7811

Epoch 5/64

4584/4584 - 56s - 12ms/step - ia: 0.2591 - loss: 1.1633 - mae: 0.8904 - rmse: 1.0549 - smape: 1.5269 - val_ia: 0.1401 - val_loss: 0.8472 - val_mae: 0.7653 - val_rmse: 0.7829 - val_smape: 1.8245

Epoch 6/64

4584/4584 - 84s - 18ms/step - ia: 0.2641 - loss: 1.1469 - mae: 0.8830 - rmse: 1.0466 - smape: 1.5197 - val_ia: 0.1404 - val_loss: 0.8470 - val_mae: 0.7655 - val_rmse: 0.7832 - val_smape: 1.8314

Epoch 7/64

4584/4584 - 42s - 9ms/step - ia: 0.2639 - loss: 1.1343 - mae: 0.8795 - rmse: 1.0426 - smape: 1.5197 - val_ia: 0.1405 - val_loss: 0.8455 - val_mae: 0.7650 - val_rmse: 0.7828 - val_smape: 1.8236

Epoch 8/64

4584/4584 - 53s - 12ms/step - ia: 0.2631 - loss: 1.1310 - mae: 0.8779 - rmse: 1.0399 - smape: 1.5200 - val_ia: 0.1407 - val_loss: 0.8435 - val_mae: 0.7642 - val_rmse: 0.7820 - val_smape: 1.8085

Epoch 9/64

4584/4584 - 59s - 13ms/step - ia: 0.2630 - loss: 1.1216 - mae: 0.8757 - rmse: 1.0355 - smape: 1.5217 - val_ia: 0.1408 - val_loss: 0.8418 - val_mae: 0.7634 - val_rmse: 0.7814 - val_smape: 1.7931

Epoch 10/64

4584/4584 - 50s - 11ms/step - ia: 0.2652 - loss: 1.1156 - mae: 0.8724 - rmse: 1.0327 - smape: 1.5189 - val_ia: 0.1409 - val_loss: 0.8399 - val_mae: 0.7626 - val_rmse: 0.7806 - val_smape: 1.7773

Epoch 11/64

4584/4584 - 52s - 11ms/step - ia: 0.2639 - loss: 1.1037 - mae: 0.8689 - rmse: 1.0282 - smape: 1.5176 - val_ia: 0.1411 - val_loss: 0.8364 - val_mae: 0.7609 - val_rmse: 0.7791 - val_smape: 1.7610

Epoch 12/64

4584/4584 - 52s - 11ms/step - ia: 0.2687 - loss: 1.0948 - mae: 0.8641 - rmse: 1.0244 - smape: 1.5151 - val_ia: 0.1413 - val_loss: 0.8339 - val_mae: 0.7598 - val_rmse: 0.7780 - val_smape: 1.7457

Epoch 13/64

4584/4584 - 46s - 10ms/step - ia: 0.2698 - loss: 1.0819 - mae: 0.8603 - rmse: 1.0179 - smape: 1.5126 - val_ia: 0.1416 - val_loss: 0.8315 - val_mae: 0.7586 - val_rmse: 0.7770 - val_smape: 1.7310

Epoch 14/64

4584/4584 - 39s - 9ms/step - ia: 0.2673 - loss: 1.0772 - mae: 0.8604 - rmse: 1.0160 - smape: 1.5172 - val_ia: 0.1420 - val_loss: 0.8282 - val_mae: 0.7570 - val_rmse: 0.7755 - val_smape: 1.7159

Epoch 15/64

4584/4584 - 39s - 8ms/step - ia: 0.2715 - loss: 1.0708 - mae: 0.8571 - rmse: 1.0129 - smape: 1.5146 - val_ia: 0.1422 - val_loss: 0.8257 - val_mae: 0.7558 - val_rmse: 0.7743 - val_smape: 1.7018

Epoch 16/64

4584/4584 - 44s - 10ms/step - ia: 0.2714 - loss: 1.0617 - mae: 0.8528 - rmse: 1.0086 - smape: 1.5114 - val_ia: 0.1426 - val_loss: 0.8226 - val_mae: 0.7543 - val_rmse: 0.7729 - val_smape: 1.6875

Epoch 17/64

4584/4584 - 47s - 10ms/step - ia: 0.2755 - loss: 1.0504 - mae: 0.8490 - rmse: 1.0015 - smape: 1.5086 - val_ia: 0.1426 - val_loss: 0.8210 - val_mae: 0.7536 - val_rmse: 0.7722 - val_smape: 1.6735

Epoch 18/64

4584/4584 - 47s - 10ms/step - ia: 0.2724 - loss: 1.0457 - mae: 0.8490 - rmse: 1.0010 - smape: 1.5154 - val_ia: 0.1426 - val_loss: 0.8187 - val_mae: 0.7524 - val_rmse: 0.7712 - val_smape: 1.6594

Epoch 19/64

4584/4584 - 47s - 10ms/step - ia: 0.2764 - loss: 1.0424 - mae: 0.8440 - rmse: 0.9986 - smape: 1.4992 - val_ia: 0.1427 - val_loss: 0.8157 - val_mae: 0.7509 - val_rmse: 0.7698 - val_smape: 1.6456

Epoch 20/64

4584/4584 - 43s - 9ms/step - ia: 0.2763 - loss: 1.0265 - mae: 0.8403 - rmse: 0.9916 - smape: 1.5014 - val_ia: 0.1429 - val_loss: 0.8129 - val_mae: 0.7496 - val_rmse: 0.7684 - val_smape: 1.6318

Epoch 21/64

4584/4584 - 41s - 9ms/step - ia: 0.2816 - loss: 1.0163 - mae: 0.8361 - rmse: 0.9874 - smape: 1.4942 - val_ia: 0.1431 - val_loss: 0.8108 - val_mae: 0.7485 - val_rmse: 0.7674 - val_smape: 1.6180

Epoch 22/64

4584/4584 - 40s - 9ms/step - ia: 0.2777 - loss: 1.0227 - mae: 0.8399 - rmse: 0.9907 - smape: 1.5022 - val_ia: 0.1434 - val_loss: 0.8083 - val_mae: 0.7472 - val_rmse: 0.7662 - val_smape: 1.6045

Epoch 23/64

4584/4584 - 40s - 9ms/step - ia: 0.2807 - loss: 1.0117 - mae: 0.8342 - rmse: 0.9846 - smape: 1.4953 - val_ia: 0.1437 - val_loss: 0.8059 - val_mae: 0.7460 - val_rmse: 0.7650 - val_smape: 1.5910

Epoch 24/64

4584/4584 - 40s - 9ms/step - ia: 0.2825 - loss: 1.0013 - mae: 0.8314 - rmse: 0.9804 - smape: 1.4914 - val_ia: 0.1443 - val_loss: 0.8028 - val_mae: 0.7443 - val_rmse: 0.7634 - val_smape: 1.5785

Epoch 25/64

4584/4584 - 40s - 9ms/step - ia: 0.2831 - loss: 0.9969 - mae: 0.8298 - rmse: 0.9775 - smape: 1.4875 - val_ia: 0.1447 - val_loss: 0.8005 - val_mae: 0.7431 - val_rmse: 0.7622 - val_smape: 1.5661

Epoch 26/64

4584/4584 - 39s - 9ms/step - ia: 0.2878 - loss: 0.9876 - mae: 0.8257 - rmse: 0.9724 - smape: 1.4841 - val_ia: 0.1450 - val_loss: 0.7980 - val_mae: 0.7418 - val_rmse: 0.7610 - val_smape: 1.5536

Epoch 27/64

4584/4584 - 40s - 9ms/step - ia: 0.2899 - loss: 0.9818 - mae: 0.8232 - rmse: 0.9708 - smape: 1.4795 - val_ia: 0.1454 - val_loss: 0.7955 - val_mae: 0.7404 - val_rmse: 0.7596 - val_smape: 1.5412

Epoch 28/64

4584/4584 - 40s - 9ms/step - ia: 0.2923 - loss: 0.9773 - mae: 0.8210 - rmse: 0.9674 - smape: 1.4750 - val_ia: 0.1458 - val_loss: 0.7926 - val_mae: 0.7388 - val_rmse: 0.7581 - val_smape: 1.5293

Epoch 29/64

4584/4584 - 39s - 8ms/step - ia: 0.2928 - loss: 0.9678 - mae: 0.8195 - rmse: 0.9628 - smape: 1.4753 - val_ia: 0.1460 - val_loss: 0.7900 - val_mae: 0.7374 - val_rmse: 0.7567 - val_smape: 1.5174

Epoch 30/64

4584/4584 - 40s - 9ms/step - ia: 0.2987 - loss: 0.9601 - mae: 0.8140 - rmse: 0.9590 - smape: 1.4649 - val_ia: 0.1459 - val_loss: 0.7885 - val_mae: 0.7365 - val_rmse: 0.7557 - val_smape: 1.5055

Epoch 31/64

4584/4584 - 40s - 9ms/step - ia: 0.2963 - loss: 0.9571 - mae: 0.8153 - rmse: 0.9583 - smape: 1.4689 - val_ia: 0.1458 - val_loss: 0.7870 - val_mae: 0.7355 - val_rmse: 0.7547 - val_smape: 1.4940

Epoch 32/64

4584/4584 - 40s - 9ms/step - ia: 0.3006 - loss: 0.9488 - mae: 0.8111 - rmse: 0.9534 - smape: 1.4615 - val_ia: 0.1458 - val_loss: 0.7844 - val_mae: 0.7340 - val_rmse: 0.7533 - val_smape: 1.4831

Epoch 33/64

4584/4584 - 39s - 8ms/step - ia: 0.3014 - loss: 0.9468 - mae: 0.8104 - rmse: 0.9535 - smape: 1.4560 - val_ia: 0.1454 - val_loss: 0.7821 - val_mae: 0.7327 - val_rmse: 0.7519 - val_smape: 1.4726

Epoch 34/64

4584/4584 - 40s - 9ms/step - ia: 0.3043 - loss: 0.9305 - mae: 0.8031 - rmse: 0.9446 - smape: 1.4499 - val_ia: 0.1448 - val_loss: 0.7803 - val_mae: 0.7315 - val_rmse: 0.7507 - val_smape: 1.4615

Epoch 35/64

4584/4584 - 40s - 9ms/step - ia: 0.3068 - loss: 0.9329 - mae: 0.8038 - rmse: 0.9463 - smape: 1.4482 - val_ia: 0.1441 - val_loss: 0.7790 - val_mae: 0.7306 - val_rmse: 0.7497 - val_smape: 1.4509

Epoch 36/64

4584/4584 - 40s - 9ms/step - ia: 0.3125 - loss: 0.9219 - mae: 0.7987 - rmse: 0.9396 - smape: 1.4378 - val_ia: 0.1437 - val_loss: 0.7771 - val_mae: 0.7294 - val_rmse: 0.7485 - val_smape: 1.4410

Epoch 37/64

4584/4584 - 40s - 9ms/step - ia: 0.3103 - loss: 0.9201 - mae: 0.8004 - rmse: 0.9391 - smape: 1.4426 - val_ia: 0.1434 - val_loss: 0.7744 - val_mae: 0.7279 - val_rmse: 0.7469 - val_smape: 1.4316

Epoch 38/64

4584/4584 - 40s - 9ms/step - ia: 0.3168 - loss: 0.9088 - mae: 0.7942 - rmse: 0.9343 - smape: 1.4308 - val_ia: 0.1431 - val_loss: 0.7721 - val_mae: 0.7265 - val_rmse: 0.7455 - val_smape: 1.4222

Epoch 39/64

4584/4584 - 39s - 8ms/step - ia: 0.3149 - loss: 0.9065 - mae: 0.7938 - rmse: 0.9326 - smape: 1.4307 - val_ia: 0.1422 - val_loss: 0.7714 - val_mae: 0.7259 - val_rmse: 0.7447 - val_smape: 1.4127

Epoch 40/64

4584/4584 - 39s - 9ms/step - ia: 0.3229 - loss: 0.8960 - mae: 0.7886 - rmse: 0.9267 - smape: 1.4207 - val_ia: 0.1415 - val_loss: 0.7690 - val_mae: 0.7245 - val_rmse: 0.7433 - val_smape: 1.4042

Epoch 41/64

4584/4584 - 40s - 9ms/step - ia: 0.3221 - loss: 0.8986 - mae: 0.7908 - rmse: 0.9284 - smape: 1.4241 - val_ia: 0.1403 - val_loss: 0.7688 - val_mae: 0.7240 - val_rmse: 0.7427 - val_smape: 1.3959

Epoch 42/64

4584/4584 - 38s - 8ms/step - ia: 0.3266 - loss: 0.8885 - mae: 0.7842 - rmse: 0.9233 - smape: 1.4121 - val_ia: 0.1394 - val_loss: 0.7674 - val_mae: 0.7231 - val_rmse: 0.7416 - val_smape: 1.3877

Epoch 43/64

4584/4584 - 40s - 9ms/step - ia: 0.3284 - loss: 0.8789 - mae: 0.7819 - rmse: 0.9188 - smape: 1.4099 - val_ia: 0.1393 - val_loss: 0.7647 - val_mae: 0.7215 - val_rmse: 0.7401 - val_smape: 1.3798

Epoch 44/64

4584/4584 - 39s - 9ms/step - ia: 0.3294 - loss: 0.8772 - mae: 0.7808 - rmse: 0.9170 - smape: 1.4088 - val_ia: 0.1391 - val_loss: 0.7636 - val_mae: 0.7207 - val_rmse: 0.7391 - val_smape: 1.3725

Epoch 45/64

4584/4584 - 40s - 9ms/step - ia: 0.3340 - loss: 0.8690 - mae: 0.7775 - rmse: 0.9126 - smape: 1.4017 - val_ia: 0.1390 - val_loss: 0.7630 - val_mae: 0.7201 - val_rmse: 0.7385 - val_smape: 1.3656

Epoch 46/64

4584/4584 - 40s - 9ms/step - ia: 0.3339 - loss: 0.8673 - mae: 0.7763 - rmse: 0.9120 - smape: 1.4002 - val_ia: 0.1387 - val_loss: 0.7620 - val_mae: 0.7193 - val_rmse: 0.7376 - val_smape: 1.3588

Epoch 47/64

4584/4584 - 40s - 9ms/step - ia: 0.3408 - loss: 0.8553 - mae: 0.7696 - rmse: 0.9055 - smape: 1.3855 - val_ia: 0.1386 - val_loss: 0.7599 - val_mae: 0.7181 - val_rmse: 0.7364 - val_smape: 1.3518

Epoch 48/64

4584/4584 - 39s - 8ms/step - ia: 0.3429 - loss: 0.8523 - mae: 0.7694 - rmse: 0.9040 - smape: 1.3860 - val_ia: 0.1383 - val_loss: 0.7599 - val_mae: 0.7177 - val_rmse: 0.7360 - val_smape: 1.3454

Epoch 49/64

4584/4584 - 39s - 8ms/step - ia: 0.3449 - loss: 0.8458 - mae: 0.7654 - rmse: 0.9006 - smape: 1.3772 - val_ia: 0.1380 - val_loss: 0.7586 - val_mae: 0.7169 - val_rmse: 0.7350 - val_smape: 1.3391

Epoch 50/64

4584/4584 - 40s - 9ms/step - ia: 0.3463 - loss: 0.8428 - mae: 0.7653 - rmse: 0.8989 - smape: 1.3781 - val_ia: 0.1374 - val_loss: 0.7576 - val_mae: 0.7162 - val_rmse: 0.7343 - val_smape: 1.3331

Epoch 51/64

4584/4584 - 40s - 9ms/step - ia: 0.3512 - loss: 0.8359 - mae: 0.7610 - rmse: 0.8952 - smape: 1.3684 - val_ia: 0.1370 - val_loss: 0.7577 - val_mae: 0.7159 - val_rmse: 0.7339 - val_smape: 1.3281

Epoch 52/64

4584/4584 - 40s - 9ms/step - ia: 0.3543 - loss: 0.8255 - mae: 0.7565 - rmse: 0.8903 - smape: 1.3626 - val_ia: 0.1369 - val_loss: 0.7584 - val_mae: 0.7160 - val_rmse: 0.7339 - val_smape: 1.3230

Epoch 53/64

4584/4584 - 40s - 9ms/step - ia: 0.3606 - loss: 0.8158 - mae: 0.7520 - rmse: 0.8844 - smape: 1.3582 - val_ia: 0.1367 - val_loss: 0.7583 - val_mae: 0.7157 - val_rmse: 0.7336 - val_smape: 1.3177

Epoch 54/64

4584/4584 - 40s - 9ms/step - ia: 0.3612 - loss: 0.8113 - mae: 0.7508 - rmse: 0.8824 - smape: 1.3526 - val_ia: 0.1367 - val_loss: 0.7567 - val_mae: 0.7147 - val_rmse: 0.7325 - val_smape: 1.3123

Epoch 55/64

4584/4584 - 40s - 9ms/step - ia: 0.3672 - loss: 0.8043 - mae: 0.7456 - rmse: 0.8780 - smape: 1.3412 - val_ia: 0.1363 - val_loss: 0.7575 - val_mae: 0.7148 - val_rmse: 0.7326 - val_smape: 1.3078

Epoch 56/64

4584/4584 - 40s - 9ms/step - ia: 0.3690 - loss: 0.7963 - mae: 0.7417 - rmse: 0.8733 - smape: 1.3356 - val_ia: 0.1360 - val_loss: 0.7567 - val_mae: 0.7142 - val_rmse: 0.7319 - val_smape: 1.3030

Epoch 57/64

4584/4584 - 39s - 9ms/step - ia: 0.3733 - loss: 0.7872 - mae: 0.7377 - rmse: 0.8684 - smape: 1.3317 - val_ia: 0.1358 - val_loss: 0.7577 - val_mae: 0.7144 - val_rmse: 0.7322 - val_smape: 1.2991

Epoch 58/64

4584/4584 - 40s - 9ms/step - ia: 0.3774 - loss: 0.7852 - mae: 0.7363 - rmse: 0.8677 - smape: 1.3252 - val_ia: 0.1363 - val_loss: 0.7592 - val_mae: 0.7149 - val_rmse: 0.7326 - val_smape: 1.2954

Epoch 59/64

4584/4584 - 40s - 9ms/step - ia: 0.3803 - loss: 0.7770 - mae: 0.7323 - rmse: 0.8626 - smape: 1.3183 - val_ia: 0.1370 - val_loss: 0.7594 - val_mae: 0.7148 - val_rmse: 0.7325 - val_smape: 1.2913

Epoch 60/64

4584/4584 - 40s - 9ms/step - ia: 0.3847 - loss: 0.7703 - mae: 0.7294 - rmse: 0.8587 - smape: 1.3142 - val_ia: 0.1377 - val_loss: 0.7609 - val_mae: 0.7153 - val_rmse: 0.7330 - val_smape: 1.2883

Epoch 61/64

4584/4584 - 40s - 9ms/step - ia: 0.3865 - loss: 0.7678 - mae: 0.7270 - rmse: 0.8573 - smape: 1.3055 - val_ia: 0.1382 - val_loss: 0.7619 - val_mae: 0.7155 - val_rmse: 0.7332 - val_smape: 1.2854

Epoch 62/64

4584/4584 - 38s - 8ms/step - ia: 0.3900 - loss: 0.7573 - mae: 0.7230 - rmse: 0.8516 - smape: 1.3010 - val_ia: 0.1388 - val_loss: 0.7644 - val_mae: 0.7165 - val_rmse: 0.7342 - val_smape: 1.2833

Epoch 63/64

4584/4584 - 38s - 8ms/step - ia: 0.3941 - loss: 0.7529 - mae: 0.7202 - rmse: 0.8490 - smape: 1.2940 - val_ia: 0.1393 - val_loss: 0.7661 - val_mae: 0.7172 - val_rmse: 0.7349 - val_smape: 1.2810

Epoch 64/64

4584/4584 - 41s - 9ms/step - ia: 0.4011 - loss: 0.7431 - mae: 0.7134 - rmse: 0.8433 - smape: 1.2819 - val_ia: 0.1401 - val_loss: 0.7679 - val_mae: 0.7179 - val_rmse: 0.7356 - val_smape: 1.2785

Restoring model weights from the end of the best epoch: 56.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:36 1s/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 10%|█         | 5/50 [1:12:22<14:56:09, 1194.89s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 31s - 27ms/step - ia: 0.2014 - loss: 1.0645 - mae: 0.8653 - rmse: 1.0266 - smape: 1.6214 - val_ia: 0.2365 - val_loss: 0.7917 - val_mae: 0.7418 - val_rmse: 0.8188 - val_smape: 1.5424

Epoch 2/128

1146/1146 - 13s - 11ms/step - ia: 0.3128 - loss: 0.8490 - mae: 0.7731 - rmse: 0.9169 - smape: 1.4452 - val_ia: 0.2438 - val_loss: 0.7635 - val_mae: 0.7190 - val_rmse: 0.7896 - val_smape: 1.3481

Epoch 3/128

1146/1146 - 12s - 10ms/step - ia: 0.4112 - loss: 0.7031 - mae: 0.6981 - rmse: 0.8341 - smape: 1.2843 - val_ia: 0.2600 - val_loss: 0.8809 - val_mae: 0.7642 - val_rmse: 0.8340 - val_smape: 1.2959

Epoch 4/128

1146/1146 - 14s - 12ms/step - ia: 0.4889 - loss: 0.6146 - mae: 0.6455 - rmse: 0.7796 - smape: 1.1629 - val_ia: 0.2675 - val_loss: 1.0993 - val_mae: 0.8585 - val_rmse: 0.9335 - val_smape: 1.3140

Epoch 5/128

1146/1146 - 15s - 13ms/step - ia: 0.5367 - loss: 0.5684 - mae: 0.6141 - rmse: 0.7490 - smape: 1.0921 - val_ia: 0.2626 - val_loss: 1.2595 - val_mae: 0.9284 - val_rmse: 1.0060 - val_smape: 1.3391

Epoch 6/128

1146/1146 - 14s - 13ms/step - ia: 0.5593 - loss: 0.5431 - mae: 0.5968 - rmse: 0.7319 - smape: 1.0546 - val_ia: 0.2591 - val_loss: 1.3408 - val_mae: 0.9619 - val_rmse: 1.0407 - val_smape: 1.3474

Epoch 7/128

1146/1146 - 15s - 13ms/step - ia: 0.5755 - loss: 0.5215 - mae: 0.5833 - rmse: 0.7171 - smape: 1.0285 - val_ia: 0.2567 - val_loss: 1.3771 - val_mae: 0.9778 - val_rmse: 1.0564 - val_smape: 1.3508

Epoch 8/128

1146/1146 - 15s - 13ms/step - ia: 0.5895 - loss: 0.4998 - mae: 0.5696 - rmse: 0.7020 - smape: 1.0038 - val_ia: 0.2552 - val_loss: 1.3858 - val_mae: 0.9836 - val_rmse: 1.0609 - val_smape: 1.3515

Epoch 9/128

1146/1146 - 15s - 13ms/step - ia: 0.6042 - loss: 0.4793 - mae: 0.5549 - rmse: 0.6873 - smape: 0.9768 - val_ia: 0.2555 - val_loss: 1.3759 - val_mae: 0.9804 - val_rmse: 1.0567 - val_smape: 1.3418

Epoch 10/128

1146/1146 - 15s - 13ms/step - ia: 0.6162 - loss: 0.4595 - mae: 0.5420 - rmse: 0.6730 - smape: 0.9548 - val_ia: 0.2565 - val_loss: 1.3589 - val_mae: 0.9758 - val_rmse: 1.0506 - val_smape: 1.3342

Epoch 11/128

1146/1146 - 14s - 13ms/step - ia: 0.6276 - loss: 0.4446 - mae: 0.5318 - rmse: 0.6620 - smape: 0.9322 - val_ia: 0.2599 - val_loss: 1.3358 - val_mae: 0.9611 - val_rmse: 1.0371 - val_smape: 1.3033

Epoch 12/128

1146/1146 - 15s - 13ms/step - ia: 0.6361 - loss: 0.4300 - mae: 0.5239 - rmse: 0.6507 - smape: 0.9169 - val_ia: 0.2629 - val_loss: 1.2900 - val_mae: 0.9458 - val_rmse: 1.0195 - val_smape: 1.2938

Epoch 13/128

1146/1146 - 14s - 13ms/step - ia: 0.6417 - loss: 0.4253 - mae: 0.5207 - rmse: 0.6473 - smape: 0.9085 - val_ia: 0.2664 - val_loss: 1.2608 - val_mae: 0.9311 - val_rmse: 1.0053 - val_smape: 1.2721

Epoch 14/128

1146/1146 - 13s - 12ms/step - ia: 0.6469 - loss: 0.4148 - mae: 0.5143 - rmse: 0.6391 - smape: 0.8950 - val_ia: 0.2699 - val_loss: 1.2119 - val_mae: 0.9114 - val_rmse: 0.9844 - val_smape: 1.2571

Epoch 15/128

1146/1146 - 15s - 13ms/step - ia: 0.6520 - loss: 0.4066 - mae: 0.5092 - rmse: 0.6329 - smape: 0.8853 - val_ia: 0.2740 - val_loss: 1.1720 - val_mae: 0.8923 - val_rmse: 0.9656 - val_smape: 1.2359

Epoch 16/128

1146/1146 - 15s - 13ms/step - ia: 0.6550 - loss: 0.4019 - mae: 0.5065 - rmse: 0.6292 - smape: 0.8802 - val_ia: 0.2780 - val_loss: 1.1175 - val_mae: 0.8716 - val_rmse: 0.9431 - val_smape: 1.2254

Epoch 17/128

1146/1146 - 15s - 13ms/step - ia: 0.6591 - loss: 0.3958 - mae: 0.5014 - rmse: 0.6242 - smape: 0.8712 - val_ia: 0.2819 - val_loss: 1.0867 - val_mae: 0.8550 - val_rmse: 0.9274 - val_smape: 1.2073

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:26 2s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step

 12%|█▏        | 6/50 [1:16:46<10:44:18, 878.60s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 14s - 99ms/step - ia: 0.7342 - loss: 0.2696 - mae: 0.3992 - rmse: 0.5044 - smape: 0.7770 - val_ia: 0.7279 - val_loss: 0.2183 - val_mae: 0.3707 - val_rmse: 0.4485 - val_smape: 0.7645

Epoch 2/128

144/144 - 2s - 15ms/step - ia: 0.8111 - loss: 0.1489 - mae: 0.2950 - rmse: 0.3846 - smape: 0.6509 - val_ia: 0.7802 - val_loss: 0.1358 - val_mae: 0.2979 - val_rmse: 0.3572 - val_smape: 0.7161

Epoch 3/128

144/144 - 2s - 16ms/step - ia: 0.8274 - loss: 0.1267 - mae: 0.2708 - rmse: 0.3552 - smape: 0.6173 - val_ia: 0.8023 - val_loss: 0.1191 - val_mae: 0.2757 - val_rmse: 0.3347 - val_smape: 0.6244

Epoch 4/128

144/144 - 3s - 17ms/step - ia: 0.8390 - loss: 0.1116 - mae: 0.2545 - rmse: 0.3331 - smape: 0.5787 - val_ia: 0.7799 - val_loss: 0.1642 - val_mae: 0.3123 - val_rmse: 0.3714 - val_smape: 0.6704

Epoch 5/128

144/144 - 2s - 16ms/step - ia: 0.8394 - loss: 0.1112 - mae: 0.2537 - rmse: 0.3326 - smape: 0.5766 - val_ia: 0.7915 - val_loss: 0.1383 - val_mae: 0.2906 - val_rmse: 0.3585 - val_smape: 0.6658

Epoch 6/128

144/144 - 2s - 16ms/step - ia: 0.8515 - loss: 0.0960 - mae: 0.2363 - rmse: 0.3095 - smape: 0.5369 - val_ia: 0.7986 - val_loss: 0.1166 - val_mae: 0.2774 - val_rmse: 0.3274 - val_smape: 0.6498

Epoch 7/128

144/144 - 2s - 15ms/step - ia: 0.8550 - loss: 0.0917 - mae: 0.2314 - rmse: 0.3020 - smape: 0.5265 - val_ia: 0.7720 - val_loss: 0.1679 - val_mae: 0.3224 - val_rmse: 0.3804 - val_smape: 0.7021

Epoch 8/128

144/144 - 2s - 16ms/step - ia: 0.8569 - loss: 0.0900 - mae: 0.2288 - rmse: 0.2990 - smape: 0.5182 - val_ia: 0.7703 - val_loss: 0.1749 - val_mae: 0.3189 - val_rmse: 0.3787 - val_smape: 0.6940

Epoch 9/128

144/144 - 2s - 15ms/step - ia: 0.8597 - loss: 0.0869 - mae: 0.2242 - rmse: 0.2942 - smape: 0.5093 - val_ia: 0.7773 - val_loss: 0.1539 - val_mae: 0.3048 - val_rmse: 0.3757 - val_smape: 0.6824

Epoch 10/128

144/144 - 2s - 16ms/step - ia: 0.8588 - loss: 0.0893 - mae: 0.2257 - rmse: 0.2978 - smape: 0.5083 - val_ia: 0.7621 - val_loss: 0.1782 - val_mae: 0.3292 - val_rmse: 0.3855 - val_smape: 0.7079

Epoch 11/128

144/144 - 2s - 16ms/step - ia: 0.8616 - loss: 0.0848 - mae: 0.2213 - rmse: 0.2910 - smape: 0.5034 - val_ia: 0.7770 - val_loss: 0.1578 - val_mae: 0.3059 - val_rmse: 0.3702 - val_smape: 0.6844

Epoch 12/128

144/144 - 2s - 16ms/step - ia: 0.8627 - loss: 0.0838 - mae: 0.2197 - rmse: 0.2890 - smape: 0.5021 - val_ia: 0.7765 - val_loss: 0.1589 - val_mae: 0.3070 - val_rmse: 0.3650 - val_smape: 0.6927

Epoch 13/128

144/144 - 2s - 15ms/step - ia: 0.8645 - loss: 0.0827 - mae: 0.2174 - rmse: 0.2869 - smape: 0.4919 - val_ia: 0.7635 - val_loss: 0.1822 - val_mae: 0.3290 - val_rmse: 0.3942 - val_smape: 0.7219

Epoch 14/128

144/144 - 3s - 18ms/step - ia: 0.8671 - loss: 0.0789 - mae: 0.2131 - rmse: 0.2802 - smape: 0.4864 - val_ia: 0.7481 - val_loss: 0.2084 - val_mae: 0.3544 - val_rmse: 0.4229 - val_smape: 0.7507

Epoch 15/128

144/144 - 2s - 16ms/step - ia: 0.8658 - loss: 0.0802 - mae: 0.2152 - rmse: 0.2822 - smape: 0.4888 - val_ia: 0.7614 - val_loss: 0.1896 - val_mae: 0.3327 - val_rmse: 0.3968 - val_smape: 0.7223

Epoch 16/128

144/144 - 2s - 16ms/step - ia: 0.8687 - loss: 0.0773 - mae: 0.2109 - rmse: 0.2775 - smape: 0.4815 - val_ia: 0.7639 - val_loss: 0.1845 - val_mae: 0.3297 - val_rmse: 0.3846 - val_smape: 0.7088

Epoch 17/128

144/144 - 2s - 16ms/step - ia: 0.8693 - loss: 0.0766 - mae: 0.2098 - rmse: 0.2762 - smape: 0.4769 - val_ia: 0.7622 - val_loss: 0.1819 - val_mae: 0.3302 - val_rmse: 0.3933 - val_smape: 0.7214

Epoch 18/128

144/144 - 2s - 16ms/step - ia: 0.8707 - loss: 0.0748 - mae: 0.2077 - rmse: 0.2730 - smape: 0.4750 - val_ia: 0.7654 - val_loss: 0.1790 - val_mae: 0.3266 - val_rmse: 0.3892 - val_smape: 0.7115

Epoch 19/128

144/144 - 2s - 15ms/step - ia: 0.8699 - loss: 0.0765 - mae: 0.2092 - rmse: 0.2758 - smape: 0.4776 - val_ia: 0.7768 - val_loss: 0.1744 - val_mae: 0.3110 - val_rmse: 0.3894 - val_smape: 0.6897

Epoch 20/128

144/144 - 2s - 15ms/step - ia: 0.8701 - loss: 0.0760 - mae: 0.2085 - rmse: 0.2751 - smape: 0.4738 - val_ia: 0.7602 - val_loss: 0.1946 - val_mae: 0.3312 - val_rmse: 0.4064 - val_smape: 0.7204

Epoch 21/128

144/144 - 2s - 14ms/step - ia: 0.8730 - loss: 0.0724 - mae: 0.2043 - rmse: 0.2686 - smape: 0.4674 - val_ia: 0.7655 - val_loss: 0.1844 - val_mae: 0.3248 - val_rmse: 0.3929 - val_smape: 0.7265

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:03 393ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 14%|█▍        | 7/50 [1:17:48<7:18:16, 611.55s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2292/2292 - 65s - 28ms/step - ia: 0.7750 - loss: 0.1975 - mae: 0.3323 - rmse: 0.4231 - smape: 0.6938 - val_ia: 0.2982 - val_loss: 0.2423 - val_mae: 0.3935 - val_rmse: 0.4299 - val_smape: 0.8324

Epoch 2/8

2292/2292 - 36s - 16ms/step - ia: 0.8344 - loss: 0.1110 - mae: 0.2500 - rmse: 0.3235 - smape: 0.5830 - val_ia: 0.3618 - val_loss: 0.1970 - val_mae: 0.3422 - val_rmse: 0.3766 - val_smape: 0.7056

Epoch 3/8

2292/2292 - 32s - 14ms/step - ia: 0.8476 - loss: 0.0954 - mae: 0.2315 - rmse: 0.2996 - smape: 0.5426 - val_ia: 0.3256 - val_loss: 0.2504 - val_mae: 0.3882 - val_rmse: 0.4301 - val_smape: 0.7571

Epoch 4/8

2292/2292 - 35s - 15ms/step - ia: 0.8572 - loss: 0.0843 - mae: 0.2175 - rmse: 0.2815 - smape: 0.5183 - val_ia: 0.3601 - val_loss: 0.1790 - val_mae: 0.3351 - val_rmse: 0.3621 - val_smape: 0.6853

Epoch 5/8

2292/2292 - 36s - 16ms/step - ia: 0.8634 - loss: 0.0779 - mae: 0.2084 - rmse: 0.2707 - smape: 0.5002 - val_ia: 0.3337 - val_loss: 0.2056 - val_mae: 0.3598 - val_rmse: 0.3923 - val_smape: 0.7457

Epoch 6/8

2292/2292 - 37s - 16ms/step - ia: 0.8666 - loss: 0.0744 - mae: 0.2037 - rmse: 0.2645 - smape: 0.4883 - val_ia: 0.3468 - val_loss: 0.1960 - val_mae: 0.3477 - val_rmse: 0.3788 - val_smape: 0.7138

Epoch 7/8

2292/2292 - 38s - 17ms/step - ia: 0.8696 - loss: 0.0718 - mae: 0.1994 - rmse: 0.2589 - smape: 0.4792 - val_ia: 0.3188 - val_loss: 0.2868 - val_mae: 0.4161 - val_rmse: 0.4540 - val_smape: 0.8079

Epoch 8/8

2292/2292 - 35s - 15ms/step - ia: 0.8725 - loss: 0.0685 - mae: 0.1953 - rmse: 0.2534 - smape: 0.4705 - val_ia: 0.3358 - val_loss: 0.2147 - val_mae: 0.3641 - val_rmse: 0.3952 - val_smape: 0.7275

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:58 1s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

Epoch 1/128

 16%|█▌        | 8/50 [1:23:07<6:02:46, 518.26s/trial, best loss: 0.13756526288013654]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 13s - 93ms/step - ia: 0.4228 - loss: 0.9692 - mae: 0.7957 - rmse: 0.9752 - smape: 1.2833 - val_ia: 0.4376 - val_loss: 1.0116 - val_mae: 0.8231 - val_rmse: 0.9773 - val_smape: 1.2972

Epoch 2/128

144/144 - 1s - 7ms/step - ia: 0.5463 - loss: 0.6085 - mae: 0.6272 - rmse: 0.7784 - smape: 1.0987 - val_ia: 0.4422 - val_loss: 1.2435 - val_mae: 0.9274 - val_rmse: 1.0796 - val_smape: 1.3195

Epoch 3/128

144/144 - 1s - 7ms/step - ia: 0.6052 - loss: 0.4950 - mae: 0.5610 - rmse: 0.7019 - smape: 0.9998 - val_ia: 0.4844 - val_loss: 1.0182 - val_mae: 0.8376 - val_rmse: 0.9650 - val_smape: 1.2508

Epoch 4/128

144/144 - 1s - 6ms/step - ia: 0.6533 - loss: 0.4108 - mae: 0.5089 - rmse: 0.6401 - smape: 0.9127 - val_ia: 0.5243 - val_loss: 0.8552 - val_mae: 0.7471 - val_rmse: 0.8790 - val_smape: 1.1608

Epoch 5/128

144/144 - 1s - 7ms/step - ia: 0.6935 - loss: 0.3421 - mae: 0.4624 - rmse: 0.5841 - smape: 0.8561 - val_ia: 0.5458 - val_loss: 0.6915 - val_mae: 0.6704 - val_rmse: 0.7873 - val_smape: 1.1273

Epoch 6/128

144/144 - 1s - 7ms/step - ia: 0.7132 - loss: 0.3063 - mae: 0.4365 - rmse: 0.5522 - smape: 0.8304 - val_ia: 0.5857 - val_loss: 0.4840 - val_mae: 0.5737 - val_rmse: 0.6660 - val_smape: 1.0646

Epoch 7/128

144/144 - 1s - 7ms/step - ia: 0.7254 - loss: 0.2834 - mae: 0.4187 - rmse: 0.5314 - smape: 0.8071 - val_ia: 0.6233 - val_loss: 0.3609 - val_mae: 0.5058 - val_rmse: 0.5827 - val_smape: 1.0022

Epoch 8/128

144/144 - 1s - 6ms/step - ia: 0.7348 - loss: 0.2647 - mae: 0.4041 - rmse: 0.5138 - smape: 0.7861 - val_ia: 0.6540 - val_loss: 0.3162 - val_mae: 0.4782 - val_rmse: 0.5491 - val_smape: 0.9942

Epoch 9/128

144/144 - 1s - 7ms/step - ia: 0.7458 - loss: 0.2444 - mae: 0.3878 - rmse: 0.4938 - smape: 0.7675 - val_ia: 0.6848 - val_loss: 0.2682 - val_mae: 0.4390 - val_rmse: 0.5080 - val_smape: 0.9515

Epoch 10/128

144/144 - 1s - 10ms/step - ia: 0.7579 - loss: 0.2242 - mae: 0.3697 - rmse: 0.4726 - smape: 0.7543 - val_ia: 0.7065 - val_loss: 0.2375 - val_mae: 0.4128 - val_rmse: 0.4802 - val_smape: 0.9143

Epoch 11/128

144/144 - 1s - 8ms/step - ia: 0.7679 - loss: 0.2083 - mae: 0.3549 - rmse: 0.4557 - smape: 0.7367 - val_ia: 0.7112 - val_loss: 0.2244 - val_mae: 0.3967 - val_rmse: 0.4630 - val_smape: 0.8941

Epoch 12/128

144/144 - 1s - 8ms/step - ia: 0.7759 - loss: 0.1967 - mae: 0.3437 - rmse: 0.4429 - smape: 0.7272 - val_ia: 0.7204 - val_loss: 0.2104 - val_mae: 0.3854 - val_rmse: 0.4480 - val_smape: 0.8807

Epoch 13/128

144/144 - 1s - 8ms/step - ia: 0.7829 - loss: 0.1864 - mae: 0.3328 - rmse: 0.4311 - smape: 0.7122 - val_ia: 0.7187 - val_loss: 0.2175 - val_mae: 0.3871 - val_rmse: 0.4539 - val_smape: 0.8722

Epoch 14/128

144/144 - 1s - 8ms/step - ia: 0.7857 - loss: 0.1826 - mae: 0.3287 - rmse: 0.4270 - smape: 0.7079 - val_ia: 0.7280 - val_loss: 0.1986 - val_mae: 0.3731 - val_rmse: 0.4322 - val_smape: 0.8458

Epoch 15/128

144/144 - 1s - 8ms/step - ia: 0.7893 - loss: 0.1782 - mae: 0.3234 - rmse: 0.4213 - smape: 0.7000 - val_ia: 0.7312 - val_loss: 0.2105 - val_mae: 0.3771 - val_rmse: 0.4448 - val_smape: 0.8356

Epoch 16/128

144/144 - 1s - 8ms/step - ia: 0.7898 - loss: 0.1780 - mae: 0.3232 - rmse: 0.4209 - smape: 0.6952 - val_ia: 0.7331 - val_loss: 0.1961 - val_mae: 0.3667 - val_rmse: 0.4295 - val_smape: 0.8116

Epoch 17/128

144/144 - 1s - 9ms/step - ia: 0.7906 - loss: 0.1763 - mae: 0.3217 - rmse: 0.4190 - smape: 0.6950 - val_ia: 0.7374 - val_loss: 0.1933 - val_mae: 0.3621 - val_rmse: 0.4261 - val_smape: 0.8073

Epoch 18/128

144/144 - 1s - 9ms/step - ia: 0.7918 - loss: 0.1728 - mae: 0.3194 - rmse: 0.4155 - smape: 0.6921 - val_ia: 0.7422 - val_loss: 0.1849 - val_mae: 0.3559 - val_rmse: 0.4179 - val_smape: 0.7940

Epoch 19/128

144/144 - 1s - 8ms/step - ia: 0.7949 - loss: 0.1708 - mae: 0.3157 - rmse: 0.4125 - smape: 0.6832 - val_ia: 0.7443 - val_loss: 0.1890 - val_mae: 0.3582 - val_rmse: 0.4216 - val_smape: 0.7898

Epoch 20/128

144/144 - 1s - 8ms/step - ia: 0.7956 - loss: 0.1691 - mae: 0.3144 - rmse: 0.4107 - smape: 0.6822 - val_ia: 0.7477 - val_loss: 0.1795 - val_mae: 0.3495 - val_rmse: 0.4093 - val_smape: 0.7813

Epoch 21/128

144/144 - 1s - 10ms/step - ia: 0.7957 - loss: 0.1685 - mae: 0.3144 - rmse: 0.4101 - smape: 0.6828 - val_ia: 0.7386 - val_loss: 0.1954 - val_mae: 0.3608 - val_rmse: 0.4296 - val_smape: 0.7949

Epoch 22/128

144/144 - 1s - 9ms/step - ia: 0.7960 - loss: 0.1682 - mae: 0.3136 - rmse: 0.4097 - smape: 0.6794 - val_ia: 0.7425 - val_loss: 0.1906 - val_mae: 0.3571 - val_rmse: 0.4238 - val_smape: 0.7862

Epoch 23/128

144/144 - 1s - 9ms/step - ia: 0.7982 - loss: 0.1652 - mae: 0.3112 - rmse: 0.4057 - smape: 0.6768 - val_ia: 0.7483 - val_loss: 0.1757 - val_mae: 0.3460 - val_rmse: 0.4069 - val_smape: 0.7761

Epoch 24/128

144/144 - 1s - 9ms/step - ia: 0.7983 - loss: 0.1662 - mae: 0.3110 - rmse: 0.4063 - smape: 0.6755 - val_ia: 0.7565 - val_loss: 0.1683 - val_mae: 0.3369 - val_rmse: 0.3958 - val_smape: 0.7579

Epoch 25/128

144/144 - 1s - 8ms/step - ia: 0.7970 - loss: 0.1665 - mae: 0.3126 - rmse: 0.4071 - smape: 0.6790 - val_ia: 0.7543 - val_loss: 0.1710 - val_mae: 0.3401 - val_rmse: 0.4005 - val_smape: 0.7602

Epoch 26/128

144/144 - 1s - 8ms/step - ia: 0.7997 - loss: 0.1635 - mae: 0.3090 - rmse: 0.4036 - smape: 0.6750 - val_ia: 0.7509 - val_loss: 0.1781 - val_mae: 0.3448 - val_rmse: 0.4090 - val_smape: 0.7674

Epoch 27/128

144/144 - 1s - 8ms/step - ia: 0.7988 - loss: 0.1645 - mae: 0.3097 - rmse: 0.4054 - smape: 0.6681 - val_ia: 0.7535 - val_loss: 0.1758 - val_mae: 0.3433 - val_rmse: 0.4075 - val_smape: 0.7622

Epoch 28/128

144/144 - 1s - 8ms/step - ia: 0.8010 - loss: 0.1619 - mae: 0.3072 - rmse: 0.4018 - smape: 0.6678 - val_ia: 0.7466 - val_loss: 0.1950 - val_mae: 0.3554 - val_rmse: 0.4307 - val_smape: 0.7702

Epoch 29/128

144/144 - 1s - 8ms/step - ia: 0.8007 - loss: 0.1625 - mae: 0.3078 - rmse: 0.4026 - smape: 0.6654 - val_ia: 0.7502 - val_loss: 0.1851 - val_mae: 0.3489 - val_rmse: 0.4189 - val_smape: 0.7658

Epoch 30/128

144/144 - 1s - 9ms/step - ia: 0.8013 - loss: 0.1618 - mae: 0.3071 - rmse: 0.4013 - smape: 0.6656 - val_ia: 0.7553 - val_loss: 0.1795 - val_mae: 0.3431 - val_rmse: 0.4110 - val_smape: 0.7587

Epoch 31/128

144/144 - 1s - 8ms/step - ia: 0.8013 - loss: 0.1615 - mae: 0.3070 - rmse: 0.4012 - smape: 0.6645 - val_ia: 0.7546 - val_loss: 0.1786 - val_mae: 0.3427 - val_rmse: 0.4104 - val_smape: 0.7613

Epoch 32/128

144/144 - 1s - 8ms/step - ia: 0.8020 - loss: 0.1605 - mae: 0.3057 - rmse: 0.4003 - smape: 0.6607 - val_ia: 0.7524 - val_loss: 0.1833 - val_mae: 0.3465 - val_rmse: 0.4168 - val_smape: 0.7643

Epoch 33/128

144/144 - 1s - 8ms/step - ia: 0.8008 - loss: 0.1634 - mae: 0.3075 - rmse: 0.4040 - smape: 0.6644 - val_ia: 0.7487 - val_loss: 0.1889 - val_mae: 0.3491 - val_rmse: 0.4241 - val_smape: 0.7666

Epoch 34/128

144/144 - 1s - 8ms/step - ia: 0.8024 - loss: 0.1612 - mae: 0.3055 - rmse: 0.4010 - smape: 0.6579 - val_ia: 0.7604 - val_loss: 0.1690 - val_mae: 0.3339 - val_rmse: 0.4002 - val_smape: 0.7500

Epoch 35/128

144/144 - 1s - 9ms/step - ia: 0.8016 - loss: 0.1609 - mae: 0.3065 - rmse: 0.4006 - smape: 0.6620 - val_ia: 0.7649 - val_loss: 0.1621 - val_mae: 0.3288 - val_rmse: 0.3915 - val_smape: 0.7356

Epoch 36/128

144/144 - 2s - 16ms/step - ia: 0.8039 - loss: 0.1594 - mae: 0.3038 - rmse: 0.3984 - smape: 0.6534 - val_ia: 0.7496 - val_loss: 0.1795 - val_mae: 0.3435 - val_rmse: 0.4130 - val_smape: 0.7631

Epoch 37/128

144/144 - 1s - 8ms/step - ia: 0.8034 - loss: 0.1593 - mae: 0.3041 - rmse: 0.3984 - smape: 0.6583 - val_ia: 0.7682 - val_loss: 0.1603 - val_mae: 0.3239 - val_rmse: 0.3879 - val_smape: 0.7284

Epoch 38/128

144/144 - 1s - 9ms/step - ia: 0.8053 - loss: 0.1578 - mae: 0.3017 - rmse: 0.3961 - smape: 0.6515 - val_ia: 0.7595 - val_loss: 0.1721 - val_mae: 0.3346 - val_rmse: 0.4040 - val_smape: 0.7456

Epoch 39/128

144/144 - 1s - 10ms/step - ia: 0.8047 - loss: 0.1579 - mae: 0.3023 - rmse: 0.3968 - smape: 0.6526 - val_ia: 0.7577 - val_loss: 0.1784 - val_mae: 0.3393 - val_rmse: 0.4123 - val_smape: 0.7450

Epoch 40/128

144/144 - 1s - 8ms/step - ia: 0.8044 - loss: 0.1580 - mae: 0.3026 - rmse: 0.3970 - smape: 0.6545 - val_ia: 0.7642 - val_loss: 0.1671 - val_mae: 0.3297 - val_rmse: 0.3980 - val_smape: 0.7364

Epoch 41/128

144/144 - 1s - 8ms/step - ia: 0.8054 - loss: 0.1571 - mae: 0.3016 - rmse: 0.3954 - smape: 0.6511 - val_ia: 0.7542 - val_loss: 0.1834 - val_mae: 0.3428 - val_rmse: 0.4188 - val_smape: 0.7497

Epoch 42/128

144/144 - 1s - 8ms/step - ia: 0.8059 - loss: 0.1556 - mae: 0.3004 - rmse: 0.3939 - smape: 0.6487 - val_ia: 0.7715 - val_loss: 0.1526 - val_mae: 0.3166 - val_rmse: 0.3786 - val_smape: 0.7242

Epoch 43/128

144/144 - 1s - 8ms/step - ia: 0.8065 - loss: 0.1562 - mae: 0.2999 - rmse: 0.3945 - smape: 0.6463 - val_ia: 0.7700 - val_loss: 0.1612 - val_mae: 0.3226 - val_rmse: 0.3906 - val_smape: 0.7252

Epoch 44/128

144/144 - 1s - 9ms/step - ia: 0.8063 - loss: 0.1558 - mae: 0.3000 - rmse: 0.3939 - smape: 0.6490 - val_ia: 0.7602 - val_loss: 0.1844 - val_mae: 0.3394 - val_rmse: 0.4199 - val_smape: 0.7430

Epoch 45/128

144/144 - 1s - 8ms/step - ia: 0.8068 - loss: 0.1546 - mae: 0.2998 - rmse: 0.3925 - smape: 0.6478 - val_ia: 0.7748 - val_loss: 0.1514 - val_mae: 0.3157 - val_rmse: 0.3781 - val_smape: 0.7162

Epoch 46/128

144/144 - 1s - 7ms/step - ia: 0.8078 - loss: 0.1542 - mae: 0.2984 - rmse: 0.3920 - smape: 0.6473 - val_ia: 0.7633 - val_loss: 0.1709 - val_mae: 0.3303 - val_rmse: 0.4046 - val_smape: 0.7322

Epoch 47/128

144/144 - 1s - 7ms/step - ia: 0.8070 - loss: 0.1547 - mae: 0.2990 - rmse: 0.3925 - smape: 0.6440 - val_ia: 0.7602 - val_loss: 0.1677 - val_mae: 0.3316 - val_rmse: 0.4004 - val_smape: 0.7402

Epoch 48/128

144/144 - 1s - 8ms/step - ia: 0.8071 - loss: 0.1553 - mae: 0.2991 - rmse: 0.3935 - smape: 0.6452 - val_ia: 0.7763 - val_loss: 0.1520 - val_mae: 0.3141 - val_rmse: 0.3801 - val_smape: 0.7105

Epoch 49/128

144/144 - 1s - 9ms/step - ia: 0.8070 - loss: 0.1541 - mae: 0.2993 - rmse: 0.3917 - smape: 0.6459 - val_ia: 0.7653 - val_loss: 0.1659 - val_mae: 0.3271 - val_rmse: 0.3977 - val_smape: 0.7265

Epoch 50/128

144/144 - 1s - 9ms/step - ia: 0.8075 - loss: 0.1542 - mae: 0.2987 - rmse: 0.3922 - smape: 0.6455 - val_ia: 0.7654 - val_loss: 0.1627 - val_mae: 0.3241 - val_rmse: 0.3933 - val_smape: 0.7242

Epoch 51/128

144/144 - 1s - 8ms/step - ia: 0.8073 - loss: 0.1541 - mae: 0.2985 - rmse: 0.3924 - smape: 0.6416 - val_ia: 0.7749 - val_loss: 0.1560 - val_mae: 0.3169 - val_rmse: 0.3856 - val_smape: 0.7140

Epoch 52/128

144/144 - 1s - 9ms/step - ia: 0.8079 - loss: 0.1542 - mae: 0.2979 - rmse: 0.3922 - smape: 0.6396 - val_ia: 0.7712 - val_loss: 0.1593 - val_mae: 0.3198 - val_rmse: 0.3903 - val_smape: 0.7142

Epoch 53/128

144/144 - 1s - 8ms/step - ia: 0.8080 - loss: 0.1543 - mae: 0.2979 - rmse: 0.3921 - smape: 0.6399 - val_ia: 0.7658 - val_loss: 0.1636 - val_mae: 0.3245 - val_rmse: 0.3964 - val_smape: 0.7209

Epoch 54/128

144/144 - 1s - 8ms/step - ia: 0.8079 - loss: 0.1535 - mae: 0.2980 - rmse: 0.3912 - smape: 0.6419 - val_ia: 0.7669 - val_loss: 0.1643 - val_mae: 0.3231 - val_rmse: 0.3957 - val_smape: 0.7195

Epoch 55/128

144/144 - 1s - 9ms/step - ia: 0.8102 - loss: 0.1511 - mae: 0.2945 - rmse: 0.3882 - smape: 0.6370 - val_ia: 0.7750 - val_loss: 0.1626 - val_mae: 0.3199 - val_rmse: 0.3949 - val_smape: 0.7077

Epoch 56/128

144/144 - 1s - 9ms/step - ia: 0.8091 - loss: 0.1523 - mae: 0.2964 - rmse: 0.3897 - smape: 0.6401 - val_ia: 0.7718 - val_loss: 0.1644 - val_mae: 0.3206 - val_rmse: 0.3966 - val_smape: 0.7132

Epoch 57/128

144/144 - 1s - 8ms/step - ia: 0.8089 - loss: 0.1531 - mae: 0.2968 - rmse: 0.3906 - smape: 0.6412 - val_ia: 0.7735 - val_loss: 0.1552 - val_mae: 0.3150 - val_rmse: 0.3851 - val_smape: 0.7054

Epoch 58/128

144/144 - 1s - 8ms/step - ia: 0.8078 - loss: 0.1536 - mae: 0.2979 - rmse: 0.3917 - smape: 0.6393 - val_ia: 0.7648 - val_loss: 0.1695 - val_mae: 0.3286 - val_rmse: 0.4018 - val_smape: 0.7211

Epoch 59/128

144/144 - 1s - 9ms/step - ia: 0.8096 - loss: 0.1522 - mae: 0.2955 - rmse: 0.3898 - smape: 0.6344 - val_ia: 0.7693 - val_loss: 0.1685 - val_mae: 0.3252 - val_rmse: 0.4017 - val_smape: 0.7120

Epoch 60/128

144/144 - 1s - 7ms/step - ia: 0.8104 - loss: 0.1504 - mae: 0.2948 - rmse: 0.3871 - smape: 0.6338 - val_ia: 0.7693 - val_loss: 0.1686 - val_mae: 0.3255 - val_rmse: 0.4022 - val_smape: 0.7120

Epoch 60: early stopping

Restoring model weights from the end of the best epoch: 45.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:09 800ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 18%|█▊        | 9/50 [1:24:34<4:22:11, 383.69s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

1146/1146 - 46s - 40ms/step - ia: 0.6433 - loss: 0.3825 - mae: 0.4857 - rmse: 0.6017 - smape: 0.9081 - val_ia: 0.3354 - val_loss: 0.7100 - val_mae: 0.6666 - val_rmse: 0.7299 - val_smape: 1.1074

Epoch 2/16

1146/1146 - 23s - 20ms/step - ia: 0.7632 - loss: 0.2174 - mae: 0.3625 - rmse: 0.4616 - smape: 0.7262 - val_ia: 0.3909 - val_loss: 0.3759 - val_mae: 0.5021 - val_rmse: 0.5506 - val_smape: 0.9668

Epoch 3/16

1146/1146 - 42s - 36ms/step - ia: 0.7851 - loss: 0.1806 - mae: 0.3284 - rmse: 0.4205 - smape: 0.6859 - val_ia: 0.4539 - val_loss: 0.2569 - val_mae: 0.3935 - val_rmse: 0.4431 - val_smape: 0.8263

Epoch 4/16

1146/1146 - 22s - 19ms/step - ia: 0.8024 - loss: 0.1559 - mae: 0.3033 - rmse: 0.3904 - smape: 0.6533 - val_ia: 0.4618 - val_loss: 0.2514 - val_mae: 0.3902 - val_rmse: 0.4397 - val_smape: 0.7967

Epoch 5/16

1146/1146 - 21s - 18ms/step - ia: 0.8165 - loss: 0.1370 - mae: 0.2833 - rmse: 0.3658 - smape: 0.6278 - val_ia: 0.4816 - val_loss: 0.2277 - val_mae: 0.3646 - val_rmse: 0.4176 - val_smape: 0.7864

Epoch 6/16

1146/1146 - 21s - 18ms/step - ia: 0.8260 - loss: 0.1237 - mae: 0.2686 - rmse: 0.3474 - smape: 0.6104 - val_ia: 0.4917 - val_loss: 0.2083 - val_mae: 0.3519 - val_rmse: 0.4021 - val_smape: 0.7675

Epoch 7/16

1146/1146 - 22s - 19ms/step - ia: 0.8346 - loss: 0.1126 - mae: 0.2561 - rmse: 0.3316 - smape: 0.5977 - val_ia: 0.4808 - val_loss: 0.2279 - val_mae: 0.3712 - val_rmse: 0.4251 - val_smape: 0.7692

Epoch 8/16

1146/1146 - 41s - 36ms/step - ia: 0.8426 - loss: 0.1039 - mae: 0.2447 - rmse: 0.3185 - smape: 0.5785 - val_ia: 0.4993 - val_loss: 0.1880 - val_mae: 0.3380 - val_rmse: 0.3906 - val_smape: 0.7326

Epoch 9/16

1146/1146 - 19s - 16ms/step - ia: 0.8467 - loss: 0.0989 - mae: 0.2383 - rmse: 0.3102 - smape: 0.5705 - val_ia: 0.5099 - val_loss: 0.1753 - val_mae: 0.3249 - val_rmse: 0.3772 - val_smape: 0.7005

Epoch 10/16

1146/1146 - 21s - 18ms/step - ia: 0.8514 - loss: 0.0935 - mae: 0.2312 - rmse: 0.3019 - smape: 0.5564 - val_ia: 0.5070 - val_loss: 0.1862 - val_mae: 0.3315 - val_rmse: 0.3853 - val_smape: 0.7046

Epoch 11/16

1146/1146 - 20s - 17ms/step - ia: 0.8553 - loss: 0.0891 - mae: 0.2256 - rmse: 0.2941 - smape: 0.5465 - val_ia: 0.4978 - val_loss: 0.2037 - val_mae: 0.3474 - val_rmse: 0.3996 - val_smape: 0.7120

Epoch 12/16

1146/1146 - 20s - 18ms/step - ia: 0.8573 - loss: 0.0866 - mae: 0.2228 - rmse: 0.2901 - smape: 0.5383 - val_ia: 0.5107 - val_loss: 0.1697 - val_mae: 0.3159 - val_rmse: 0.3709 - val_smape: 0.6974

Epoch 13/16

1146/1146 - 19s - 17ms/step - ia: 0.8601 - loss: 0.0840 - mae: 0.2187 - rmse: 0.2856 - smape: 0.5273 - val_ia: 0.5000 - val_loss: 0.1921 - val_mae: 0.3298 - val_rmse: 0.3894 - val_smape: 0.7170

Epoch 14/16

1146/1146 - 20s - 18ms/step - ia: 0.8629 - loss: 0.0808 - mae: 0.2146 - rmse: 0.2803 - smape: 0.5197 - val_ia: 0.4915 - val_loss: 0.2034 - val_mae: 0.3447 - val_rmse: 0.4016 - val_smape: 0.7283

Epoch 15/16

1146/1146 - 19s - 17ms/step - ia: 0.8643 - loss: 0.0792 - mae: 0.2126 - rmse: 0.2776 - smape: 0.5155 - val_ia: 0.5038 - val_loss: 0.1830 - val_mae: 0.3250 - val_rmse: 0.3797 - val_smape: 0.6972

Epoch 16/16

1146/1146 - 21s - 18ms/step - ia: 0.8673 - loss: 0.0763 - mae: 0.2080 - rmse: 0.2720 - smape: 0.5028 - val_ia: 0.5096 - val_loss: 0.1735 - val_mae: 0.3194 - val_rmse: 0.3690 - val_smape: 0.6926

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:38 2s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 20%|██        | 10/50 [1:31:14<4:19:10, 388.76s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 29s - 101ms/step - ia: 0.2091 - loss: 2.0229 - mae: 1.1321 - rmse: 1.4194 - smape: 1.5504 - val_ia: 0.2551 - val_loss: 1.3299 - val_mae: 0.9601 - val_rmse: 1.1413 - val_smape: 1.5586

Epoch 2/8

287/287 - 3s - 10ms/step - ia: 0.2087 - loss: 1.9944 - mae: 1.1270 - rmse: 1.4095 - smape: 1.5552 - val_ia: 0.2551 - val_loss: 1.3189 - val_mae: 0.9560 - val_rmse: 1.1366 - val_smape: 1.5589

Epoch 3/8

287/287 - 3s - 12ms/step - ia: 0.2087 - loss: 1.9717 - mae: 1.1211 - rmse: 1.4019 - smape: 1.5551 - val_ia: 0.2550 - val_loss: 1.3082 - val_mae: 0.9519 - val_rmse: 1.1320 - val_smape: 1.5592

Epoch 4/8

287/287 - 4s - 14ms/step - ia: 0.2123 - loss: 1.9567 - mae: 1.1156 - rmse: 1.3950 - smape: 1.5462 - val_ia: 0.2549 - val_loss: 1.2977 - val_mae: 0.9479 - val_rmse: 1.1275 - val_smape: 1.5595

Epoch 5/8

287/287 - 4s - 13ms/step - ia: 0.2113 - loss: 1.9495 - mae: 1.1127 - rmse: 1.3931 - smape: 1.5482 - val_ia: 0.2549 - val_loss: 1.2873 - val_mae: 0.9440 - val_rmse: 1.1231 - val_smape: 1.5598

Epoch 6/8

287/287 - 4s - 13ms/step - ia: 0.2126 - loss: 1.9235 - mae: 1.1067 - rmse: 1.3845 - smape: 1.5478 - val_ia: 0.2548 - val_loss: 1.2770 - val_mae: 0.9401 - val_rmse: 1.1186 - val_smape: 1.5602

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.2094 - loss: 1.9025 - mae: 1.1024 - rmse: 1.3761 - smape: 1.5555 - val_ia: 0.2547 - val_loss: 1.2672 - val_mae: 0.9363 - val_rmse: 1.1144 - val_smape: 1.5605

Epoch 8/8

287/287 - 3s - 12ms/step - ia: 0.2101 - loss: 1.9002 - mae: 1.1021 - rmse: 1.3753 - smape: 1.5521 - val_ia: 0.2545 - val_loss: 1.2573 - val_mae: 0.9325 - val_rmse: 1.1101 - val_smape: 1.5609

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:32 1s/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step

 22%|██▏       | 11/50 [1:32:13<3:07:03, 287.78s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 27s - 24ms/step - ia: 0.5041 - loss: 0.6389 - mae: 0.6457 - rmse: 0.7894 - smape: 1.1267 - val_ia: 0.2384 - val_loss: 1.3098 - val_mae: 0.9718 - val_rmse: 1.0502 - val_smape: 1.3583

Epoch 2/128

1146/1146 - 10s - 9ms/step - ia: 0.6513 - loss: 0.4173 - mae: 0.5128 - rmse: 0.6401 - smape: 0.8835 - val_ia: 0.2645 - val_loss: 1.0874 - val_mae: 0.8598 - val_rmse: 0.9331 - val_smape: 1.2292

Epoch 3/128

1146/1146 - 10s - 9ms/step - ia: 0.6963 - loss: 0.3370 - mae: 0.4594 - rmse: 0.5756 - smape: 0.8086 - val_ia: 0.3067 - val_loss: 0.8222 - val_mae: 0.7334 - val_rmse: 0.8008 - val_smape: 1.1433

Epoch 4/128

1146/1146 - 10s - 9ms/step - ia: 0.7209 - loss: 0.2934 - mae: 0.4253 - rmse: 0.5368 - smape: 0.7663 - val_ia: 0.3272 - val_loss: 0.6947 - val_mae: 0.6681 - val_rmse: 0.7309 - val_smape: 1.0841

Epoch 5/128

1146/1146 - 11s - 10ms/step - ia: 0.7362 - loss: 0.2659 - mae: 0.4039 - rmse: 0.5110 - smape: 0.7460 - val_ia: 0.3548 - val_loss: 0.5540 - val_mae: 0.5866 - val_rmse: 0.6488 - val_smape: 1.0075

Epoch 6/128

1146/1146 - 11s - 10ms/step - ia: 0.7487 - loss: 0.2432 - mae: 0.3847 - rmse: 0.4885 - smape: 0.7294 - val_ia: 0.3534 - val_loss: 0.5841 - val_mae: 0.6017 - val_rmse: 0.6597 - val_smape: 1.0017

Epoch 7/128

1146/1146 - 13s - 11ms/step - ia: 0.7637 - loss: 0.2182 - mae: 0.3625 - rmse: 0.4625 - smape: 0.7127 - val_ia: 0.3887 - val_loss: 0.4340 - val_mae: 0.5198 - val_rmse: 0.5780 - val_smape: 0.9110

Epoch 8/128

1146/1146 - 12s - 10ms/step - ia: 0.7827 - loss: 0.1876 - mae: 0.3334 - rmse: 0.4286 - smape: 0.6863 - val_ia: 0.4205 - val_loss: 0.3718 - val_mae: 0.4743 - val_rmse: 0.5349 - val_smape: 0.8550

Epoch 9/128

1146/1146 - 10s - 9ms/step - ia: 0.8061 - loss: 0.1530 - mae: 0.2986 - rmse: 0.3863 - smape: 0.6527 - val_ia: 0.4527 - val_loss: 0.3237 - val_mae: 0.4469 - val_rmse: 0.5035 - val_smape: 0.8214

Epoch 10/128

1146/1146 - 12s - 10ms/step - ia: 0.8246 - loss: 0.1286 - mae: 0.2717 - rmse: 0.3538 - smape: 0.6214 - val_ia: 0.4972 - val_loss: 0.2009 - val_mae: 0.3617 - val_rmse: 0.4120 - val_smape: 0.7569

Epoch 11/128

1146/1146 - 11s - 10ms/step - ia: 0.8349 - loss: 0.1158 - mae: 0.2562 - rmse: 0.3354 - smape: 0.5979 - val_ia: 0.5078 - val_loss: 0.1925 - val_mae: 0.3532 - val_rmse: 0.4028 - val_smape: 0.7398

Epoch 12/128

1146/1146 - 11s - 10ms/step - ia: 0.8400 - loss: 0.1098 - mae: 0.2482 - rmse: 0.3263 - smape: 0.5868 - val_ia: 0.5237 - val_loss: 0.1855 - val_mae: 0.3467 - val_rmse: 0.3906 - val_smape: 0.7249

Epoch 13/128

1146/1146 - 12s - 10ms/step - ia: 0.8445 - loss: 0.1046 - mae: 0.2415 - rmse: 0.3184 - smape: 0.5812 - val_ia: 0.5298 - val_loss: 0.1583 - val_mae: 0.3173 - val_rmse: 0.3687 - val_smape: 0.7109

Epoch 14/128

1146/1146 - 11s - 9ms/step - ia: 0.8466 - loss: 0.1017 - mae: 0.2383 - rmse: 0.3139 - smape: 0.5771 - val_ia: 0.5333 - val_loss: 0.1722 - val_mae: 0.3330 - val_rmse: 0.3779 - val_smape: 0.7148

Epoch 15/128

1146/1146 - 11s - 10ms/step - ia: 0.8495 - loss: 0.0984 - mae: 0.2340 - rmse: 0.3092 - smape: 0.5689 - val_ia: 0.5487 - val_loss: 0.1468 - val_mae: 0.3056 - val_rmse: 0.3534 - val_smape: 0.6852

Epoch 16/128

1146/1146 - 21s - 18ms/step - ia: 0.8509 - loss: 0.0964 - mae: 0.2314 - rmse: 0.3058 - smape: 0.5647 - val_ia: 0.5513 - val_loss: 0.1414 - val_mae: 0.3009 - val_rmse: 0.3459 - val_smape: 0.6754

Epoch 17/128

1146/1146 - 12s - 10ms/step - ia: 0.8524 - loss: 0.0947 - mae: 0.2295 - rmse: 0.3032 - smape: 0.5603 - val_ia: 0.5474 - val_loss: 0.1452 - val_mae: 0.3049 - val_rmse: 0.3514 - val_smape: 0.6855

Epoch 18/128

1146/1146 - 12s - 10ms/step - ia: 0.8539 - loss: 0.0926 - mae: 0.2276 - rmse: 0.2999 - smape: 0.5579 - val_ia: 0.5417 - val_loss: 0.1558 - val_mae: 0.3172 - val_rmse: 0.3624 - val_smape: 0.6908

Epoch 19/128

1146/1146 - 11s - 10ms/step - ia: 0.8554 - loss: 0.0909 - mae: 0.2251 - rmse: 0.2971 - smape: 0.5520 - val_ia: 0.5274 - val_loss: 0.1732 - val_mae: 0.3325 - val_rmse: 0.3786 - val_smape: 0.7161

Epoch 20/128

1146/1146 - 21s - 18ms/step - ia: 0.8574 - loss: 0.0887 - mae: 0.2223 - rmse: 0.2934 - smape: 0.5472 - val_ia: 0.5525 - val_loss: 0.1428 - val_mae: 0.2978 - val_rmse: 0.3479 - val_smape: 0.6720

Epoch 21/128

1146/1146 - 12s - 10ms/step - ia: 0.8590 - loss: 0.0871 - mae: 0.2201 - rmse: 0.2906 - smape: 0.5437 - val_ia: 0.5474 - val_loss: 0.1479 - val_mae: 0.3054 - val_rmse: 0.3548 - val_smape: 0.6813

Epoch 22/128

1146/1146 - 11s - 10ms/step - ia: 0.8595 - loss: 0.0857 - mae: 0.2189 - rmse: 0.2883 - smape: 0.5420 - val_ia: 0.5373 - val_loss: 0.1595 - val_mae: 0.3154 - val_rmse: 0.3682 - val_smape: 0.6947

Epoch 23/128

1146/1146 - 12s - 10ms/step - ia: 0.8600 - loss: 0.0847 - mae: 0.2181 - rmse: 0.2867 - smape: 0.5373 - val_ia: 0.5292 - val_loss: 0.1661 - val_mae: 0.3190 - val_rmse: 0.3751 - val_smape: 0.6971

Epoch 24/128

1146/1146 - 11s - 10ms/step - ia: 0.8612 - loss: 0.0834 - mae: 0.2166 - rmse: 0.2847 - smape: 0.5348 - val_ia: 0.5441 - val_loss: 0.1549 - val_mae: 0.3102 - val_rmse: 0.3596 - val_smape: 0.6821

Epoch 25/128

1146/1146 - 11s - 9ms/step - ia: 0.8627 - loss: 0.0822 - mae: 0.2148 - rmse: 0.2826 - smape: 0.5331 - val_ia: 0.5255 - val_loss: 0.1858 - val_mae: 0.3363 - val_rmse: 0.3909 - val_smape: 0.7197

Epoch 26/128

1146/1146 - 12s - 10ms/step - ia: 0.8638 - loss: 0.0805 - mae: 0.2130 - rmse: 0.2796 - smape: 0.5293 - val_ia: 0.5360 - val_loss: 0.1667 - val_mae: 0.3202 - val_rmse: 0.3714 - val_smape: 0.6982

Epoch 27/128

1146/1146 - 12s - 11ms/step - ia: 0.8653 - loss: 0.0792 - mae: 0.2111 - rmse: 0.2772 - smape: 0.5237 - val_ia: 0.5452 - val_loss: 0.1530 - val_mae: 0.3057 - val_rmse: 0.3588 - val_smape: 0.6806

Epoch 28/128

1146/1146 - 12s - 10ms/step - ia: 0.8668 - loss: 0.0771 - mae: 0.2085 - rmse: 0.2736 - smape: 0.5193 - val_ia: 0.5259 - val_loss: 0.1780 - val_mae: 0.3266 - val_rmse: 0.3875 - val_smape: 0.7065

Epoch 29/128

1146/1146 - 12s - 10ms/step - ia: 0.8679 - loss: 0.0760 - mae: 0.2074 - rmse: 0.2717 - smape: 0.5152 - val_ia: 0.5437 - val_loss: 0.1674 - val_mae: 0.3162 - val_rmse: 0.3722 - val_smape: 0.6914

Epoch 30/128

1146/1146 - 12s - 10ms/step - ia: 0.8690 - loss: 0.0747 - mae: 0.2055 - rmse: 0.2695 - smape: 0.5112 - val_ia: 0.5175 - val_loss: 0.1927 - val_mae: 0.3416 - val_rmse: 0.4003 - val_smape: 0.7267

Epoch 31/128

1146/1146 - 12s - 10ms/step - ia: 0.8703 - loss: 0.0738 - mae: 0.2038 - rmse: 0.2675 - smape: 0.5064 - val_ia: 0.5435 - val_loss: 0.1557 - val_mae: 0.3049 - val_rmse: 0.3630 - val_smape: 0.6784

Epoch 31: early stopping

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 24%|██▍       | 12/50 [1:38:46<3:22:24, 319.60s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 34s - 119ms/step - ia: 0.6545 - loss: 0.3941 - mae: 0.4975 - rmse: 0.6202 - smape: 0.8898 - val_ia: 0.5592 - val_loss: 0.6060 - val_mae: 0.6469 - val_rmse: 0.7512 - val_smape: 1.0962

Epoch 2/16

287/287 - 6s - 20ms/step - ia: 0.7430 - loss: 0.2617 - mae: 0.4006 - rmse: 0.5103 - smape: 0.7513 - val_ia: 0.6179 - val_loss: 0.4594 - val_mae: 0.5588 - val_rmse: 0.6622 - val_smape: 1.0086

Epoch 3/16

287/287 - 6s - 19ms/step - ia: 0.7765 - loss: 0.2067 - mae: 0.3489 - rmse: 0.4530 - smape: 0.7130 - val_ia: 0.7014 - val_loss: 0.2837 - val_mae: 0.4340 - val_rmse: 0.5054 - val_smape: 0.9029

Epoch 4/16

287/287 - 6s - 20ms/step - ia: 0.8032 - loss: 0.1623 - mae: 0.3081 - rmse: 0.4014 - smape: 0.6684 - val_ia: 0.7452 - val_loss: 0.2084 - val_mae: 0.3669 - val_rmse: 0.4318 - val_smape: 0.7796

Epoch 5/16

287/287 - 6s - 20ms/step - ia: 0.8248 - loss: 0.1333 - mae: 0.2758 - rmse: 0.3636 - smape: 0.6292 - val_ia: 0.7815 - val_loss: 0.1487 - val_mae: 0.3143 - val_rmse: 0.3689 - val_smape: 0.7036

Epoch 6/16

287/287 - 5s - 17ms/step - ia: 0.8339 - loss: 0.1215 - mae: 0.2626 - rmse: 0.3471 - smape: 0.6087 - val_ia: 0.7453 - val_loss: 0.2288 - val_mae: 0.3777 - val_rmse: 0.4613 - val_smape: 0.7696

Epoch 7/16

287/287 - 5s - 17ms/step - ia: 0.8403 - loss: 0.1139 - mae: 0.2531 - rmse: 0.3360 - smape: 0.5949 - val_ia: 0.7648 - val_loss: 0.1947 - val_mae: 0.3492 - val_rmse: 0.4276 - val_smape: 0.7309

Epoch 8/16

287/287 - 5s - 17ms/step - ia: 0.8426 - loss: 0.1107 - mae: 0.2494 - rmse: 0.3315 - smape: 0.5870 - val_ia: 0.7516 - val_loss: 0.2191 - val_mae: 0.3652 - val_rmse: 0.4549 - val_smape: 0.7477

Epoch 9/16

287/287 - 5s - 16ms/step - ia: 0.8453 - loss: 0.1072 - mae: 0.2452 - rmse: 0.3259 - smape: 0.5803 - val_ia: 0.7539 - val_loss: 0.2115 - val_mae: 0.3636 - val_rmse: 0.4415 - val_smape: 0.7513

Epoch 10/16

287/287 - 5s - 16ms/step - ia: 0.8483 - loss: 0.1040 - mae: 0.2409 - rmse: 0.3210 - smape: 0.5711 - val_ia: 0.7492 - val_loss: 0.2122 - val_mae: 0.3611 - val_rmse: 0.4470 - val_smape: 0.7565

Epoch 11/16

287/287 - 5s - 18ms/step - ia: 0.8506 - loss: 0.1008 - mae: 0.2372 - rmse: 0.3162 - smape: 0.5654 - val_ia: 0.7529 - val_loss: 0.2080 - val_mae: 0.3622 - val_rmse: 0.4363 - val_smape: 0.7501

Epoch 12/16

287/287 - 6s - 22ms/step - ia: 0.8525 - loss: 0.0984 - mae: 0.2345 - rmse: 0.3125 - smape: 0.5613 - val_ia: 0.7607 - val_loss: 0.1949 - val_mae: 0.3508 - val_rmse: 0.4223 - val_smape: 0.7354

Epoch 13/16

287/287 - 6s - 21ms/step - ia: 0.8538 - loss: 0.0959 - mae: 0.2326 - rmse: 0.3082 - smape: 0.5586 - val_ia: 0.7635 - val_loss: 0.1965 - val_mae: 0.3499 - val_rmse: 0.4220 - val_smape: 0.7199

Epoch 14/16

287/287 - 6s - 21ms/step - ia: 0.8555 - loss: 0.0944 - mae: 0.2302 - rmse: 0.3060 - smape: 0.5532 - val_ia: 0.7680 - val_loss: 0.1798 - val_mae: 0.3359 - val_rmse: 0.3989 - val_smape: 0.7188

Epoch 15/16

287/287 - 10s - 35ms/step - ia: 0.8600 - loss: 0.0890 - mae: 0.2235 - rmse: 0.2970 - smape: 0.5399 - val_ia: 0.7588 - val_loss: 0.2047 - val_mae: 0.3538 - val_rmse: 0.4247 - val_smape: 0.7375

Epoch 16/16

287/287 - 6s - 21ms/step - ia: 0.8604 - loss: 0.0879 - mae: 0.2231 - rmse: 0.2956 - smape: 0.5378 - val_ia: 0.7537 - val_loss: 0.2111 - val_mae: 0.3606 - val_rmse: 0.4311 - val_smape: 0.7368

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 8:52 3s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step

 26%|██▌       | 13/50 [1:40:54<2:41:17, 261.55s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 19s - 68ms/step - ia: 0.3754 - loss: 0.7593 - mae: 0.7205 - rmse: 0.8672 - smape: 1.3414 - val_ia: 0.4297 - val_loss: 1.0933 - val_mae: 0.8449 - val_rmse: 1.0151 - val_smape: 1.2987

Epoch 2/8

287/287 - 3s - 11ms/step - ia: 0.5808 - loss: 0.5222 - mae: 0.5805 - rmse: 0.7207 - smape: 1.0291 - val_ia: 0.4204 - val_loss: 1.5766 - val_mae: 1.0476 - val_rmse: 1.2067 - val_smape: 1.3589

Epoch 3/8

287/287 - 3s - 11ms/step - ia: 0.6511 - loss: 0.4236 - mae: 0.5179 - rmse: 0.6490 - smape: 0.9018 - val_ia: 0.4707 - val_loss: 1.2707 - val_mae: 0.9206 - val_rmse: 1.0804 - val_smape: 1.2298

Epoch 4/8

287/287 - 3s - 10ms/step - ia: 0.6811 - loss: 0.3720 - mae: 0.4843 - rmse: 0.6085 - smape: 0.8472 - val_ia: 0.5144 - val_loss: 0.9881 - val_mae: 0.8002 - val_rmse: 0.9560 - val_smape: 1.1583

Epoch 5/8

287/287 - 3s - 9ms/step - ia: 0.6994 - loss: 0.3396 - mae: 0.4618 - rmse: 0.5817 - smape: 0.8176 - val_ia: 0.5381 - val_loss: 0.8200 - val_mae: 0.7288 - val_rmse: 0.8729 - val_smape: 1.1286

Epoch 6/8

287/287 - 3s - 11ms/step - ia: 0.7084 - loss: 0.3213 - mae: 0.4496 - rmse: 0.5658 - smape: 0.8031 - val_ia: 0.5536 - val_loss: 0.7171 - val_mae: 0.6856 - val_rmse: 0.8174 - val_smape: 1.1116

Epoch 7/8

287/287 - 3s - 11ms/step - ia: 0.7148 - loss: 0.3096 - mae: 0.4412 - rmse: 0.5553 - smape: 0.7950 - val_ia: 0.5572 - val_loss: 0.6965 - val_mae: 0.6805 - val_rmse: 0.8031 - val_smape: 1.1115

Epoch 8/8

287/287 - 3s - 11ms/step - ia: 0.7203 - loss: 0.2995 - mae: 0.4331 - rmse: 0.5463 - smape: 0.7864 - val_ia: 0.5632 - val_loss: 0.6566 - val_mae: 0.6644 - val_rmse: 0.7819 - val_smape: 1.1034

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:17 1s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 28%|██▊       | 14/50 [1:41:39<1:57:41, 196.14s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 18s - 31ms/step - ia: 0.7411 - loss: 0.2621 - mae: 0.3920 - rmse: 0.4982 - smape: 0.7581 - val_ia: 0.6316 - val_loss: 0.2747 - val_mae: 0.4258 - val_rmse: 0.4895 - val_smape: 0.8446

Epoch 2/16

573/573 - 3s - 6ms/step - ia: 0.8078 - loss: 0.1515 - mae: 0.2973 - rmse: 0.3865 - smape: 0.6491 - val_ia: 0.7146 - val_loss: 0.1336 - val_mae: 0.2992 - val_rmse: 0.3491 - val_smape: 0.7012

Epoch 3/16

573/573 - 4s - 6ms/step - ia: 0.8189 - loss: 0.1350 - mae: 0.2811 - rmse: 0.3649 - smape: 0.6234 - val_ia: 0.7135 - val_loss: 0.1435 - val_mae: 0.3070 - val_rmse: 0.3561 - val_smape: 0.6993

Epoch 4/16

573/573 - 6s - 10ms/step - ia: 0.8258 - loss: 0.1269 - mae: 0.2716 - rmse: 0.3538 - smape: 0.6019 - val_ia: 0.6973 - val_loss: 0.2040 - val_mae: 0.3320 - val_rmse: 0.4226 - val_smape: 0.6778

Epoch 5/16

573/573 - 4s - 6ms/step - ia: 0.8328 - loss: 0.1163 - mae: 0.2617 - rmse: 0.3389 - smape: 0.5784 - val_ia: 0.7296 - val_loss: 0.1429 - val_mae: 0.2849 - val_rmse: 0.3520 - val_smape: 0.6328

Epoch 6/16

573/573 - 4s - 7ms/step - ia: 0.8361 - loss: 0.1137 - mae: 0.2574 - rmse: 0.3349 - smape: 0.5700 - val_ia: 0.7031 - val_loss: 0.1759 - val_mae: 0.3240 - val_rmse: 0.3866 - val_smape: 0.6784

Epoch 7/16

573/573 - 4s - 6ms/step - ia: 0.8392 - loss: 0.1090 - mae: 0.2531 - rmse: 0.3279 - smape: 0.5616 - val_ia: 0.7262 - val_loss: 0.1283 - val_mae: 0.2779 - val_rmse: 0.3311 - val_smape: 0.6261

Epoch 8/16

573/573 - 4s - 6ms/step - ia: 0.8432 - loss: 0.1048 - mae: 0.2476 - rmse: 0.3216 - smape: 0.5443 - val_ia: 0.7132 - val_loss: 0.1535 - val_mae: 0.3049 - val_rmse: 0.3571 - val_smape: 0.6650

Epoch 9/16

573/573 - 4s - 7ms/step - ia: 0.8450 - loss: 0.1026 - mae: 0.2446 - rmse: 0.3182 - smape: 0.5393 - val_ia: 0.7050 - val_loss: 0.1531 - val_mae: 0.3048 - val_rmse: 0.3594 - val_smape: 0.6586

Epoch 10/16

573/573 - 4s - 6ms/step - ia: 0.8462 - loss: 0.1010 - mae: 0.2430 - rmse: 0.3158 - smape: 0.5393 - val_ia: 0.7235 - val_loss: 0.1244 - val_mae: 0.2762 - val_rmse: 0.3313 - val_smape: 0.6219

Epoch 11/16

573/573 - 4s - 6ms/step - ia: 0.8484 - loss: 0.0985 - mae: 0.2398 - rmse: 0.3116 - smape: 0.5305 - val_ia: 0.7008 - val_loss: 0.1533 - val_mae: 0.3012 - val_rmse: 0.3608 - val_smape: 0.6489

Epoch 12/16

573/573 - 3s - 6ms/step - ia: 0.8485 - loss: 0.0984 - mae: 0.2396 - rmse: 0.3117 - smape: 0.5276 - val_ia: 0.7000 - val_loss: 0.1423 - val_mae: 0.2996 - val_rmse: 0.3481 - val_smape: 0.6411

Epoch 13/16

573/573 - 4s - 6ms/step - ia: 0.8504 - loss: 0.0963 - mae: 0.2366 - rmse: 0.3084 - smape: 0.5214 - val_ia: 0.6975 - val_loss: 0.1539 - val_mae: 0.3018 - val_rmse: 0.3600 - val_smape: 0.6664

Epoch 14/16

573/573 - 4s - 6ms/step - ia: 0.8525 - loss: 0.0933 - mae: 0.2335 - rmse: 0.3033 - smape: 0.5187 - val_ia: 0.6847 - val_loss: 0.1692 - val_mae: 0.3116 - val_rmse: 0.3799 - val_smape: 0.6903

Epoch 15/16

573/573 - 4s - 7ms/step - ia: 0.8528 - loss: 0.0936 - mae: 0.2331 - rmse: 0.3038 - smape: 0.5180 - val_ia: 0.6661 - val_loss: 0.1823 - val_mae: 0.3323 - val_rmse: 0.3986 - val_smape: 0.7088

Epoch 16/16

573/573 - 5s - 10ms/step - ia: 0.8517 - loss: 0.0941 - mae: 0.2345 - rmse: 0.3048 - smape: 0.5185 - val_ia: 0.6718 - val_loss: 0.1841 - val_mae: 0.3294 - val_rmse: 0.3952 - val_smape: 0.7023

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:25 901ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 30%|███       | 15/50 [1:42:57<1:33:47, 160.77s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 55s - 12ms/step - ia: 0.7287 - loss: 0.2326 - mae: 0.3708 - rmse: 0.4572 - smape: 0.7490 - val_ia: 0.2137 - val_loss: 0.3079 - val_mae: 0.4539 - val_rmse: 0.4710 - val_smape: 0.8850

Epoch 2/256

4584/4584 - 39s - 9ms/step - ia: 0.7533 - loss: 0.1974 - mae: 0.3408 - rmse: 0.4222 - smape: 0.7181 - val_ia: 0.2123 - val_loss: 0.2805 - val_mae: 0.4229 - val_rmse: 0.4392 - val_smape: 0.8324

Epoch 3/256

4584/4584 - 36s - 8ms/step - ia: 0.6382 - loss: 0.5723 - mae: 0.4765 - rmse: 0.5883 - smape: 0.8872 - val_ia: 0.1550 - val_loss: 0.6756 - val_mae: 0.6695 - val_rmse: 0.6857 - val_smape: 1.3900

Epoch 4/256

4584/4584 - 39s - 9ms/step - ia: 0.4732 - loss: 0.6628 - mae: 0.6462 - rmse: 0.7807 - smape: 1.1987 - val_ia: 0.1812 - val_loss: 0.4163 - val_mae: 0.5143 - val_rmse: 0.5389 - val_smape: 1.0463

Epoch 5/256

4584/4584 - 38s - 8ms/step - ia: 0.6579 - loss: 0.3399 - mae: 0.4566 - rmse: 0.5590 - smape: 0.8644 - val_ia: 0.1884 - val_loss: 0.3921 - val_mae: 0.4909 - val_rmse: 0.5130 - val_smape: 0.8813

Epoch 6/256

4584/4584 - 39s - 9ms/step - ia: 0.7497 - loss: 0.2011 - mae: 0.3461 - rmse: 0.4293 - smape: 0.7247 - val_ia: 0.2315 - val_loss: 0.2229 - val_mae: 0.3760 - val_rmse: 0.3941 - val_smape: 0.7904

Epoch 7/256

4584/4584 - 41s - 9ms/step - ia: 0.7862 - loss: 0.1504 - mae: 0.2977 - rmse: 0.3711 - smape: 0.6573 - val_ia: 0.2413 - val_loss: 0.2347 - val_mae: 0.3784 - val_rmse: 0.3960 - val_smape: 0.7563

Epoch 8/256

4584/4584 - 43s - 9ms/step - ia: 0.7832 - loss: 0.1580 - mae: 0.3016 - rmse: 0.3771 - smape: 0.6499 - val_ia: 0.2570 - val_loss: 0.2122 - val_mae: 0.3623 - val_rmse: 0.3774 - val_smape: 0.7437

Epoch 9/256

4584/4584 - 42s - 9ms/step - ia: 0.5900 - loss: 6.5383 - mae: 0.6133 - rmse: 0.8608 - smape: 0.9829 - val_ia: 0.1088 - val_loss: 1.5301 - val_mae: 0.9404 - val_rmse: 0.9992 - val_smape: 1.5908

Epoch 10/256

4584/4584 - 50s - 11ms/step - ia: 0.3216 - loss: 28.4833 - mae: 0.9649 - rmse: 1.3220 - smape: 1.4324 - val_ia: 0.1347 - val_loss: 0.9975 - val_mae: 0.8332 - val_rmse: 0.8514 - val_smape: 1.6527

Epoch 11/256

4584/4584 - 52s - 11ms/step - ia: 0.2228 - loss: 6699.2773 - mae: 10.6820 - rmse: 18.1758 - smape: 1.5712 - val_ia: 0.0908 - val_loss: 2.3852 - val_mae: 1.2792 - val_rmse: 1.3266 - val_smape: 1.2621

Epoch 12/256

4584/4584 - 55s - 12ms/step - ia: 0.2741 - loss: 16.3677 - mae: 1.3745 - rmse: 1.8717 - smape: 1.4837 - val_ia: 0.0933 - val_loss: 3.6863 - val_mae: 1.1913 - val_rmse: 1.4607 - val_smape: 1.6000

Epoch 13/256

4584/4584 - 51s - 11ms/step - ia: 0.2170 - loss: 668.5010 - mae: 4.0868 - rmse: 6.7398 - smape: 1.5954 - val_ia: 0.0258 - val_loss: 1002.6768 - val_mae: 12.7503 - val_rmse: 16.8635 - val_smape: 1.6531

Epoch 14/256

4584/4584 - 47s - 10ms/step - ia: 0.1505 - loss: 5066.4365 - mae: 7.1694 - rmse: 13.1851 - smape: 1.6009 - val_ia: 0.0884 - val_loss: 20.1601 - val_mae: 1.5482 - val_rmse: 2.0947 - val_smape: 1.5502

Epoch 15/256

4584/4584 - 48s - 10ms/step - ia: 0.2569 - loss: 19.0520 - mae: 1.4448 - rmse: 2.1108 - smape: 1.4742 - val_ia: 0.1364 - val_loss: 2.0042 - val_mae: 0.8288 - val_rmse: 0.9349 - val_smape: 1.5744

Epoch 16/256

4584/4584 - 76s - 17ms/step - ia: 0.2250 - loss: 1.1585 - mae: 0.8611 - rmse: 1.0313 - smape: 1.6942 - val_ia: 0.1346 - val_loss: 0.8781 - val_mae: 0.7709 - val_rmse: 0.7932 - val_smape: 1.7439

Epoch 17/256

4584/4584 - 44s - 9ms/step - ia: 0.2071 - loss: 884.2302 - mae: 3.8129 - rmse: 6.7727 - smape: 1.5897 - val_ia: 0.1356 - val_loss: 0.9950 - val_mae: 0.7929 - val_rmse: 0.8337 - val_smape: 1.4692

Epoch 18/256

4584/4584 - 84s - 18ms/step - ia: 0.2192 - loss: 1.1601 - mae: 0.8672 - rmse: 1.0328 - smape: 1.7327 - val_ia: 0.1391 - val_loss: 0.8998 - val_mae: 0.7888 - val_rmse: 0.8083 - val_smape: 1.6620

Epoch 19/256

4584/4584 - 43s - 9ms/step - ia: 0.2108 - loss: 65.8083 - mae: 1.6634 - rmse: 2.3920 - smape: 1.6558 - val_ia: 0.1347 - val_loss: 0.8430 - val_mae: 0.7608 - val_rmse: 0.7834 - val_smape: 1.7544

Epoch 20/256

4584/4584 - 45s - 10ms/step - ia: 0.2231 - loss: 27.6777 - mae: 1.3986 - rmse: 1.9349 - smape: 1.6502 - val_ia: 0.1399 - val_loss: 0.8225 - val_mae: 0.7508 - val_rmse: 0.7707 - val_smape: 1.7488

Epoch 21/256

4584/4584 - 43s - 9ms/step - ia: 0.2127 - loss: 1923.7133 - mae: 5.0668 - rmse: 9.3019 - smape: 1.6635 - val_ia: 0.1392 - val_loss: 0.8448 - val_mae: 0.7464 - val_rmse: 0.7707 - val_smape: 1.6433

Epoch 22/256

4584/4584 - 41s - 9ms/step - ia: 0.2097 - loss: 3227.4402 - mae: 8.1153 - rmse: 14.6208 - smape: 1.5616 - val_ia: 0.0849 - val_loss: 24.3618 - val_mae: 2.3553 - val_rmse: 3.0093 - val_smape: 1.4256

Epoch 23/256

4584/4584 - 43s - 9ms/step - ia: 0.2308 - loss: 1792.4664 - mae: 5.1373 - rmse: 8.7392 - smape: 1.4702 - val_ia: 0.1359 - val_loss: 0.9001 - val_mae: 0.7558 - val_rmse: 0.7952 - val_smape: 1.4562

Epoch 23: early stopping

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:39 616ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 32%|███▏      | 16/50 [2:01:14<4:10:45, 442.51s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 109s - 24ms/step - ia: 0.7017 - loss: 0.2831 - mae: 0.4034 - rmse: 0.4956 - smape: 0.7848 - val_ia: 0.2333 - val_loss: 0.2449 - val_mae: 0.3914 - val_rmse: 0.4073 - val_smape: 0.8004

Epoch 2/256

4584/4584 - 77s - 17ms/step - ia: 0.8132 - loss: 0.1210 - mae: 0.2621 - rmse: 0.3303 - smape: 0.6213 - val_ia: 0.2775 - val_loss: 0.1486 - val_mae: 0.3068 - val_rmse: 0.3241 - val_smape: 0.6826

Epoch 3/256

4584/4584 - 82s - 18ms/step - ia: 0.8352 - loss: 0.0963 - mae: 0.2329 - rmse: 0.2943 - smape: 0.5633 - val_ia: 0.2821 - val_loss: 0.1385 - val_mae: 0.2926 - val_rmse: 0.3108 - val_smape: 0.6840

Epoch 4/256

4584/4584 - 83s - 18ms/step - ia: 0.8462 - loss: 0.0841 - mae: 0.2174 - rmse: 0.2747 - smape: 0.5257 - val_ia: 0.2714 - val_loss: 0.1733 - val_mae: 0.3238 - val_rmse: 0.3425 - val_smape: 0.7049

Epoch 5/256

4584/4584 - 77s - 17ms/step - ia: 0.8531 - loss: 0.0775 - mae: 0.2086 - rmse: 0.2632 - smape: 0.5031 - val_ia: 0.3046 - val_loss: 0.1395 - val_mae: 0.2878 - val_rmse: 0.3050 - val_smape: 0.6473

Epoch 6/256

4584/4584 - 71s - 16ms/step - ia: 0.8571 - loss: 0.0742 - mae: 0.2032 - rmse: 0.2571 - smape: 0.4918 - val_ia: 0.2864 - val_loss: 0.1402 - val_mae: 0.2963 - val_rmse: 0.3114 - val_smape: 0.6744

Epoch 7/256

4584/4584 - 75s - 16ms/step - ia: 0.8607 - loss: 0.0713 - mae: 0.1988 - rmse: 0.2521 - smape: 0.4815 - val_ia: 0.2638 - val_loss: 0.1768 - val_mae: 0.3251 - val_rmse: 0.3439 - val_smape: 0.7309

Epoch 8/256

4584/4584 - 76s - 17ms/step - ia: 0.8625 - loss: 0.0687 - mae: 0.1955 - rmse: 0.2479 - smape: 0.4775 - val_ia: 0.2751 - val_loss: 0.1889 - val_mae: 0.3317 - val_rmse: 0.3515 - val_smape: 0.7188

Epoch 9/256

4584/4584 - 71s - 16ms/step - ia: 0.8653 - loss: 0.0664 - mae: 0.1921 - rmse: 0.2437 - smape: 0.4683 - val_ia: 0.2992 - val_loss: 0.1425 - val_mae: 0.2909 - val_rmse: 0.3081 - val_smape: 0.6830

Epoch 10/256

4584/4584 - 71s - 16ms/step - ia: 0.8687 - loss: 0.0634 - mae: 0.1871 - rmse: 0.2374 - smape: 0.4626 - val_ia: 0.2696 - val_loss: 0.1711 - val_mae: 0.3266 - val_rmse: 0.3444 - val_smape: 0.7078

Epoch 11/256

4584/4584 - 67s - 15ms/step - ia: 0.8707 - loss: 0.0612 - mae: 0.1843 - rmse: 0.2335 - smape: 0.4585 - val_ia: 0.2743 - val_loss: 0.1880 - val_mae: 0.3291 - val_rmse: 0.3483 - val_smape: 0.7530

Epoch 12/256

4584/4584 - 67s - 15ms/step - ia: 0.8720 - loss: 0.0605 - mae: 0.1827 - rmse: 0.2321 - smape: 0.4507 - val_ia: 0.2649 - val_loss: 0.2073 - val_mae: 0.3533 - val_rmse: 0.3712 - val_smape: 0.7488

Epoch 13/256

4584/4584 - 70s - 15ms/step - ia: 0.8751 - loss: 0.0575 - mae: 0.1787 - rmse: 0.2265 - smape: 0.4468 - val_ia: 0.2758 - val_loss: 0.1714 - val_mae: 0.3222 - val_rmse: 0.3399 - val_smape: 0.7115

Epoch 14/256

4584/4584 - 85s - 19ms/step - ia: 0.8765 - loss: 0.0570 - mae: 0.1772 - rmse: 0.2253 - smape: 0.4422 - val_ia: 0.2657 - val_loss: 0.1788 - val_mae: 0.3326 - val_rmse: 0.3520 - val_smape: 0.7415

Epoch 15/256

4584/4584 - 73s - 16ms/step - ia: 0.8784 - loss: 0.0553 - mae: 0.1745 - rmse: 0.2219 - smape: 0.4382 - val_ia: 0.2709 - val_loss: 0.1923 - val_mae: 0.3412 - val_rmse: 0.3590 - val_smape: 0.7311

Epoch 16/256

4584/4584 - 70s - 15ms/step - ia: 0.8797 - loss: 0.0542 - mae: 0.1727 - rmse: 0.2196 - smape: 0.4336 - val_ia: 0.2536 - val_loss: 0.2099 - val_mae: 0.3634 - val_rmse: 0.3813 - val_smape: 0.7672

Epoch 17/256

4584/4584 - 65s - 14ms/step - ia: 0.8812 - loss: 0.0531 - mae: 0.1712 - rmse: 0.2172 - smape: 0.4304 - val_ia: 0.2779 - val_loss: 0.1799 - val_mae: 0.3234 - val_rmse: 0.3414 - val_smape: 0.7184

Epoch 18/256

4584/4584 - 74s - 16ms/step - ia: 0.8812 - loss: 0.0530 - mae: 0.1698 - rmse: 0.2162 - smape: 0.4287 - val_ia: 0.2579 - val_loss: 0.2020 - val_mae: 0.3511 - val_rmse: 0.3688 - val_smape: 0.7455

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:55 2s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step

 34%|███▍      | 17/50 [2:24:02<6:36:30, 720.91s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 23s - 80ms/step - ia: 0.1485 - loss: 1.2833 - mae: 0.9305 - rmse: 1.1309 - smape: 1.6400 - val_ia: 0.2048 - val_loss: 0.9549 - val_mae: 0.8090 - val_rmse: 0.9694 - val_smape: 1.7735

Epoch 2/16

287/287 - 4s - 13ms/step - ia: 0.1568 - loss: 1.2243 - mae: 0.9091 - rmse: 1.1052 - smape: 1.6289 - val_ia: 0.2027 - val_loss: 0.9239 - val_mae: 0.7975 - val_rmse: 0.9538 - val_smape: 1.8212

Epoch 3/16

287/287 - 4s - 13ms/step - ia: 0.1641 - loss: 1.1822 - mae: 0.8943 - rmse: 1.0857 - smape: 1.6224 - val_ia: 0.2034 - val_loss: 0.8976 - val_mae: 0.7873 - val_rmse: 0.9403 - val_smape: 1.8333

Epoch 4/16

287/287 - 4s - 13ms/step - ia: 0.1692 - loss: 1.1505 - mae: 0.8845 - rmse: 1.0708 - smape: 1.6167 - val_ia: 0.2071 - val_loss: 0.8750 - val_mae: 0.7782 - val_rmse: 0.9285 - val_smape: 1.8145

Epoch 5/16

287/287 - 4s - 13ms/step - ia: 0.1853 - loss: 1.1058 - mae: 0.8667 - rmse: 1.0501 - smape: 1.5973 - val_ia: 0.2140 - val_loss: 0.8560 - val_mae: 0.7702 - val_rmse: 0.9184 - val_smape: 1.7567

Epoch 6/16

287/287 - 5s - 18ms/step - ia: 0.1933 - loss: 1.0828 - mae: 0.8589 - rmse: 1.0393 - smape: 1.5873 - val_ia: 0.2234 - val_loss: 0.8397 - val_mae: 0.7629 - val_rmse: 0.9098 - val_smape: 1.6883

Epoch 7/16

287/287 - 4s - 13ms/step - ia: 0.2040 - loss: 1.0533 - mae: 0.8488 - rmse: 1.0250 - smape: 1.5747 - val_ia: 0.2347 - val_loss: 0.8264 - val_mae: 0.7565 - val_rmse: 0.9026 - val_smape: 1.6262

Epoch 8/16

287/287 - 4s - 14ms/step - ia: 0.2191 - loss: 1.0203 - mae: 0.8359 - rmse: 1.0090 - smape: 1.5549 - val_ia: 0.2468 - val_loss: 0.8154 - val_mae: 0.7509 - val_rmse: 0.8965 - val_smape: 1.5721

Epoch 9/16

287/287 - 4s - 15ms/step - ia: 0.2306 - loss: 0.9982 - mae: 0.8277 - rmse: 0.9978 - smape: 1.5423 - val_ia: 0.2588 - val_loss: 0.8062 - val_mae: 0.7459 - val_rmse: 0.8914 - val_smape: 1.5267

Epoch 10/16

287/287 - 4s - 16ms/step - ia: 0.2413 - loss: 0.9821 - mae: 0.8210 - rmse: 0.9899 - smape: 1.5255 - val_ia: 0.2711 - val_loss: 0.7988 - val_mae: 0.7416 - val_rmse: 0.8872 - val_smape: 1.4872

Epoch 11/16

287/287 - 4s - 16ms/step - ia: 0.2551 - loss: 0.9594 - mae: 0.8122 - rmse: 0.9781 - smape: 1.5086 - val_ia: 0.2831 - val_loss: 0.7928 - val_mae: 0.7380 - val_rmse: 0.8838 - val_smape: 1.4534

Epoch 12/16

287/287 - 5s - 16ms/step - ia: 0.2690 - loss: 0.9383 - mae: 0.8036 - rmse: 0.9673 - smape: 1.4908 - val_ia: 0.2944 - val_loss: 0.7884 - val_mae: 0.7350 - val_rmse: 0.8811 - val_smape: 1.4247

Epoch 13/16

287/287 - 5s - 17ms/step - ia: 0.2812 - loss: 0.9197 - mae: 0.7957 - rmse: 0.9576 - smape: 1.4717 - val_ia: 0.3050 - val_loss: 0.7849 - val_mae: 0.7326 - val_rmse: 0.8790 - val_smape: 1.4006

Epoch 14/16

287/287 - 4s - 15ms/step - ia: 0.2924 - loss: 0.9056 - mae: 0.7895 - rmse: 0.9506 - smape: 1.4585 - val_ia: 0.3150 - val_loss: 0.7827 - val_mae: 0.7308 - val_rmse: 0.8776 - val_smape: 1.3797

Epoch 15/16

287/287 - 4s - 16ms/step - ia: 0.3020 - loss: 0.8894 - mae: 0.7823 - rmse: 0.9418 - smape: 1.4448 - val_ia: 0.3245 - val_loss: 0.7811 - val_mae: 0.7293 - val_rmse: 0.8765 - val_smape: 1.3615

Epoch 16/16

287/287 - 5s - 16ms/step - ia: 0.3141 - loss: 0.8721 - mae: 0.7749 - rmse: 0.9325 - smape: 1.4292 - val_ia: 0.3335 - val_loss: 0.7806 - val_mae: 0.7282 - val_rmse: 0.8759 - val_smape: 1.3460

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:58 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step

 36%|███▌      | 18/50 [2:25:34<4:43:40, 531.89s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 18s - 31ms/step - ia: 0.6487 - loss: 0.4204 - mae: 0.5080 - rmse: 0.6324 - smape: 0.9004 - val_ia: 0.4966 - val_loss: 0.7329 - val_mae: 0.6426 - val_rmse: 0.7510 - val_smape: 1.0444

Epoch 2/16

573/573 - 7s - 12ms/step - ia: 0.7868 - loss: 0.1873 - mae: 0.3310 - rmse: 0.4282 - smape: 0.6997 - val_ia: 0.5916 - val_loss: 0.5463 - val_mae: 0.5172 - val_rmse: 0.6295 - val_smape: 0.8717

Epoch 3/16

573/573 - 7s - 13ms/step - ia: 0.8407 - loss: 0.1118 - mae: 0.2507 - rmse: 0.3315 - smape: 0.5984 - val_ia: 0.6925 - val_loss: 0.2042 - val_mae: 0.3393 - val_rmse: 0.4224 - val_smape: 0.7138

Epoch 4/16

573/573 - 7s - 12ms/step - ia: 0.8543 - loss: 0.0948 - mae: 0.2303 - rmse: 0.3054 - smape: 0.5620 - val_ia: 0.6790 - val_loss: 0.2179 - val_mae: 0.3578 - val_rmse: 0.4388 - val_smape: 0.7313

Epoch 5/16

573/573 - 7s - 13ms/step - ia: 0.8622 - loss: 0.0853 - mae: 0.2187 - rmse: 0.2897 - smape: 0.5343 - val_ia: 0.6947 - val_loss: 0.1741 - val_mae: 0.3221 - val_rmse: 0.3796 - val_smape: 0.7163

Epoch 6/16

573/573 - 7s - 12ms/step - ia: 0.8703 - loss: 0.0763 - mae: 0.2067 - rmse: 0.2738 - smape: 0.5128 - val_ia: 0.7129 - val_loss: 0.1637 - val_mae: 0.3114 - val_rmse: 0.3723 - val_smape: 0.6869

Epoch 7/16

573/573 - 7s - 13ms/step - ia: 0.8731 - loss: 0.0729 - mae: 0.2026 - rmse: 0.2676 - smape: 0.5006 - val_ia: 0.6975 - val_loss: 0.1749 - val_mae: 0.3179 - val_rmse: 0.3897 - val_smape: 0.7091

Epoch 8/16

573/573 - 7s - 13ms/step - ia: 0.8768 - loss: 0.0691 - mae: 0.1969 - rmse: 0.2605 - smape: 0.4887 - val_ia: 0.6899 - val_loss: 0.1826 - val_mae: 0.3257 - val_rmse: 0.3959 - val_smape: 0.7154

Epoch 9/16

573/573 - 10s - 18ms/step - ia: 0.8777 - loss: 0.0686 - mae: 0.1955 - rmse: 0.2596 - smape: 0.4856 - val_ia: 0.7209 - val_loss: 0.1388 - val_mae: 0.2911 - val_rmse: 0.3575 - val_smape: 0.6668

Epoch 10/16

573/573 - 7s - 12ms/step - ia: 0.8805 - loss: 0.0660 - mae: 0.1912 - rmse: 0.2545 - smape: 0.4749 - val_ia: 0.7199 - val_loss: 0.1434 - val_mae: 0.2904 - val_rmse: 0.3515 - val_smape: 0.6635

Epoch 11/16

573/573 - 6s - 10ms/step - ia: 0.8826 - loss: 0.0640 - mae: 0.1883 - rmse: 0.2507 - smape: 0.4710 - val_ia: 0.7086 - val_loss: 0.1474 - val_mae: 0.2958 - val_rmse: 0.3600 - val_smape: 0.6846

Epoch 12/16

573/573 - 7s - 12ms/step - ia: 0.8850 - loss: 0.0609 - mae: 0.1841 - rmse: 0.2447 - smape: 0.4614 - val_ia: 0.7207 - val_loss: 0.1357 - val_mae: 0.2843 - val_rmse: 0.3520 - val_smape: 0.6747

Epoch 13/16

573/573 - 7s - 13ms/step - ia: 0.8870 - loss: 0.0592 - mae: 0.1815 - rmse: 0.2411 - smape: 0.4585 - val_ia: 0.7204 - val_loss: 0.1382 - val_mae: 0.2889 - val_rmse: 0.3531 - val_smape: 0.6758

Epoch 14/16

573/573 - 7s - 13ms/step - ia: 0.8872 - loss: 0.0591 - mae: 0.1809 - rmse: 0.2408 - smape: 0.4537 - val_ia: 0.7193 - val_loss: 0.1467 - val_mae: 0.2924 - val_rmse: 0.3466 - val_smape: 0.6680

Epoch 15/16

573/573 - 7s - 13ms/step - ia: 0.8895 - loss: 0.0570 - mae: 0.1774 - rmse: 0.2364 - smape: 0.4482 - val_ia: 0.7272 - val_loss: 0.1304 - val_mae: 0.2769 - val_rmse: 0.3377 - val_smape: 0.6639

Epoch 16/16

573/573 - 7s - 13ms/step - ia: 0.8903 - loss: 0.0560 - mae: 0.1761 - rmse: 0.2345 - smape: 0.4429 - val_ia: 0.7255 - val_loss: 0.1403 - val_mae: 0.2854 - val_rmse: 0.3416 - val_smape: 0.6683

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:15 835ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 38%|███▊      | 19/50 [2:27:45<3:32:28, 411.25s/trial, best loss: 0.13398275240030408]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 109s - 24ms/step - ia: 0.5198 - loss: 0.5678 - mae: 0.5983 - rmse: 0.7162 - smape: 1.0674 - val_ia: 0.1772 - val_loss: 0.6674 - val_mae: 0.6651 - val_rmse: 0.6831 - val_smape: 1.1035

Epoch 2/32

4584/4584 - 78s - 17ms/step - ia: 0.6760 - loss: 0.3252 - mae: 0.4477 - rmse: 0.5507 - smape: 0.7963 - val_ia: 0.1694 - val_loss: 0.5354 - val_mae: 0.5919 - val_rmse: 0.6110 - val_smape: 1.0296

Epoch 3/32

4584/4584 - 76s - 17ms/step - ia: 0.7003 - loss: 0.2783 - mae: 0.4133 - rmse: 0.5090 - smape: 0.7762 - val_ia: 0.1705 - val_loss: 0.4892 - val_mae: 0.5610 - val_rmse: 0.5783 - val_smape: 0.9909

Epoch 4/32

4584/4584 - 76s - 17ms/step - ia: 0.7299 - loss: 0.2298 - mae: 0.3715 - rmse: 0.4612 - smape: 0.7557 - val_ia: 0.1859 - val_loss: 0.3446 - val_mae: 0.4770 - val_rmse: 0.4936 - val_smape: 0.9557

Epoch 5/32

4584/4584 - 73s - 16ms/step - ia: 0.7531 - loss: 0.1944 - mae: 0.3390 - rmse: 0.4224 - smape: 0.7305 - val_ia: 0.2006 - val_loss: 0.2684 - val_mae: 0.4264 - val_rmse: 0.4427 - val_smape: 0.8717

Epoch 6/32

4584/4584 - 70s - 15ms/step - ia: 0.7699 - loss: 0.1720 - mae: 0.3178 - rmse: 0.3970 - smape: 0.7015 - val_ia: 0.2148 - val_loss: 0.2157 - val_mae: 0.3860 - val_rmse: 0.4012 - val_smape: 0.8350

Epoch 7/32

4584/4584 - 76s - 16ms/step - ia: 0.7808 - loss: 0.1585 - mae: 0.3043 - rmse: 0.3802 - smape: 0.6879 - val_ia: 0.2222 - val_loss: 0.1982 - val_mae: 0.3677 - val_rmse: 0.3834 - val_smape: 0.8327

Epoch 8/32

4584/4584 - 71s - 16ms/step - ia: 0.7890 - loss: 0.1486 - mae: 0.2941 - rmse: 0.3683 - smape: 0.6705 - val_ia: 0.2356 - val_loss: 0.1804 - val_mae: 0.3476 - val_rmse: 0.3640 - val_smape: 0.8076

Epoch 9/32

4584/4584 - 75s - 16ms/step - ia: 0.7923 - loss: 0.1419 - mae: 0.2872 - rmse: 0.3599 - smape: 0.6588 - val_ia: 0.2362 - val_loss: 0.1803 - val_mae: 0.3465 - val_rmse: 0.3620 - val_smape: 0.7928

Epoch 10/32

4584/4584 - 70s - 15ms/step - ia: 0.7981 - loss: 0.1363 - mae: 0.2809 - rmse: 0.3522 - smape: 0.6456 - val_ia: 0.2424 - val_loss: 0.1717 - val_mae: 0.3379 - val_rmse: 0.3527 - val_smape: 0.7776

Epoch 11/32

4584/4584 - 74s - 16ms/step - ia: 0.8033 - loss: 0.1319 - mae: 0.2754 - rmse: 0.3463 - smape: 0.6338 - val_ia: 0.2497 - val_loss: 0.1675 - val_mae: 0.3304 - val_rmse: 0.3457 - val_smape: 0.7463

Epoch 12/32

4584/4584 - 74s - 16ms/step - ia: 0.8055 - loss: 0.1274 - mae: 0.2714 - rmse: 0.3407 - smape: 0.6278 - val_ia: 0.2500 - val_loss: 0.1646 - val_mae: 0.3278 - val_rmse: 0.3426 - val_smape: 0.7516

Epoch 13/32

4584/4584 - 75s - 16ms/step - ia: 0.8078 - loss: 0.1254 - mae: 0.2694 - rmse: 0.3378 - smape: 0.6243 - val_ia: 0.2564 - val_loss: 0.1507 - val_mae: 0.3155 - val_rmse: 0.3308 - val_smape: 0.7643

Epoch 14/32

4584/4584 - 71s - 16ms/step - ia: 0.8106 - loss: 0.1213 - mae: 0.2646 - rmse: 0.3318 - smape: 0.6151 - val_ia: 0.2476 - val_loss: 0.1657 - val_mae: 0.3281 - val_rmse: 0.3438 - val_smape: 0.7644

Epoch 15/32

4584/4584 - 75s - 16ms/step - ia: 0.8122 - loss: 0.1201 - mae: 0.2633 - rmse: 0.3298 - smape: 0.6121 - val_ia: 0.2506 - val_loss: 0.1684 - val_mae: 0.3286 - val_rmse: 0.3447 - val_smape: 0.7550

Epoch 16/32

4584/4584 - 71s - 15ms/step - ia: 0.8127 - loss: 0.1193 - mae: 0.2625 - rmse: 0.3293 - smape: 0.6085 - val_ia: 0.2540 - val_loss: 0.1529 - val_mae: 0.3173 - val_rmse: 0.3321 - val_smape: 0.7434

Epoch 17/32

4584/4584 - 77s - 17ms/step - ia: 0.8147 - loss: 0.1161 - mae: 0.2594 - rmse: 0.3245 - smape: 0.6045 - val_ia: 0.2562 - val_loss: 0.1783 - val_mae: 0.3338 - val_rmse: 0.3493 - val_smape: 0.7322

Epoch 18/32

4584/4584 - 76s - 17ms/step - ia: 0.8173 - loss: 0.1140 - mae: 0.2566 - rmse: 0.3221 - smape: 0.5984 - val_ia: 0.2593 - val_loss: 0.1573 - val_mae: 0.3172 - val_rmse: 0.3329 - val_smape: 0.7408

Epoch 19/32

4584/4584 - 74s - 16ms/step - ia: 0.8171 - loss: 0.1134 - mae: 0.2570 - rmse: 0.3215 - smape: 0.5971 - val_ia: 0.2427 - val_loss: 0.1957 - val_mae: 0.3506 - val_rmse: 0.3672 - val_smape: 0.7673

Epoch 20/32

4584/4584 - 77s - 17ms/step - ia: 0.8201 - loss: 0.1099 - mae: 0.2527 - rmse: 0.3163 - smape: 0.5880 - val_ia: 0.2499 - val_loss: 0.1792 - val_mae: 0.3339 - val_rmse: 0.3506 - val_smape: 0.7339

Epoch 21/32

4584/4584 - 79s - 17ms/step - ia: 0.8200 - loss: 0.1092 - mae: 0.2522 - rmse: 0.3159 - smape: 0.5864 - val_ia: 0.2474 - val_loss: 0.1819 - val_mae: 0.3389 - val_rmse: 0.3552 - val_smape: 0.7483

Epoch 22/32

4584/4584 - 72s - 16ms/step - ia: 0.8222 - loss: 0.1082 - mae: 0.2510 - rmse: 0.3142 - smape: 0.5810 - val_ia: 0.2574 - val_loss: 0.1630 - val_mae: 0.3215 - val_rmse: 0.3374 - val_smape: 0.7384

Epoch 23/32

4584/4584 - 75s - 16ms/step - ia: 0.8242 - loss: 0.1059 - mae: 0.2478 - rmse: 0.3107 - smape: 0.5776 - val_ia: 0.2487 - val_loss: 0.1809 - val_mae: 0.3351 - val_rmse: 0.3530 - val_smape: 0.7499

Epoch 24/32

4584/4584 - 77s - 17ms/step - ia: 0.8242 - loss: 0.1052 - mae: 0.2472 - rmse: 0.3099 - smape: 0.5750 - val_ia: 0.2511 - val_loss: 0.1702 - val_mae: 0.3276 - val_rmse: 0.3441 - val_smape: 0.7354

Epoch 25/32

4584/4584 - 74s - 16ms/step - ia: 0.8254 - loss: 0.1037 - mae: 0.2452 - rmse: 0.3073 - smape: 0.5719 - val_ia: 0.2478 - val_loss: 0.1857 - val_mae: 0.3386 - val_rmse: 0.3570 - val_smape: 0.7677

Epoch 26/32

4584/4584 - 72s - 16ms/step - ia: 0.8256 - loss: 0.1043 - mae: 0.2462 - rmse: 0.3083 - smape: 0.5719 - val_ia: 0.2502 - val_loss: 0.1789 - val_mae: 0.3341 - val_rmse: 0.3515 - val_smape: 0.7580

Epoch 27/32

4584/4584 - 75s - 16ms/step - ia: 0.8263 - loss: 0.1033 - mae: 0.2448 - rmse: 0.3064 - smape: 0.5675 - val_ia: 0.2520 - val_loss: 0.1818 - val_mae: 0.3327 - val_rmse: 0.3513 - val_smape: 0.7520

Epoch 28/32

4584/4584 - 72s - 16ms/step - ia: 0.8281 - loss: 0.1011 - mae: 0.2420 - rmse: 0.3032 - smape: 0.5641 - val_ia: 0.2600 - val_loss: 0.1557 - val_mae: 0.3132 - val_rmse: 0.3301 - val_smape: 0.7285

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:22 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step

 40%|████      | 20/50 [3:03:03<7:41:57, 923.91s/trial, best loss: 0.12201317346183038]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

144/144 - 36s - 250ms/step - ia: 0.2592 - loss: 1.2814 - mae: 0.9308 - rmse: 1.1309 - smape: 1.4868 - val_ia: 0.2197 - val_loss: 0.9536 - val_mae: 0.8124 - val_rmse: 0.9603 - val_smape: 1.5848

Epoch 2/32

144/144 - 4s - 25ms/step - ia: 0.2544 - loss: 1.2571 - mae: 0.9238 - rmse: 1.1201 - smape: 1.4961 - val_ia: 0.2146 - val_loss: 0.9332 - val_mae: 0.8040 - val_rmse: 0.9511 - val_smape: 1.6193

Epoch 3/32

144/144 - 4s - 26ms/step - ia: 0.2536 - loss: 1.2401 - mae: 0.9160 - rmse: 1.1123 - smape: 1.4935 - val_ia: 0.2116 - val_loss: 0.9188 - val_mae: 0.7980 - val_rmse: 0.9446 - val_smape: 1.6513

Epoch 4/32

144/144 - 3s - 24ms/step - ia: 0.2486 - loss: 1.2325 - mae: 0.9140 - rmse: 1.1095 - smape: 1.5004 - val_ia: 0.2108 - val_loss: 0.9081 - val_mae: 0.7935 - val_rmse: 0.9398 - val_smape: 1.6805

Epoch 5/32

144/144 - 3s - 22ms/step - ia: 0.2481 - loss: 1.2176 - mae: 0.9082 - rmse: 1.1027 - smape: 1.5044 - val_ia: 0.2113 - val_loss: 0.9004 - val_mae: 0.7903 - val_rmse: 0.9363 - val_smape: 1.7052

Epoch 6/32

144/144 - 3s - 20ms/step - ia: 0.2436 - loss: 1.2111 - mae: 0.9065 - rmse: 1.0999 - smape: 1.5079 - val_ia: 0.2114 - val_loss: 0.8945 - val_mae: 0.7877 - val_rmse: 0.9336 - val_smape: 1.7273

Epoch 7/32

144/144 - 3s - 20ms/step - ia: 0.2434 - loss: 1.2069 - mae: 0.9052 - rmse: 1.0981 - smape: 1.5100 - val_ia: 0.2113 - val_loss: 0.8905 - val_mae: 0.7860 - val_rmse: 0.9318 - val_smape: 1.7439

Epoch 8/32

144/144 - 3s - 20ms/step - ia: 0.2385 - loss: 1.2049 - mae: 0.9042 - rmse: 1.0965 - smape: 1.5192 - val_ia: 0.2111 - val_loss: 0.8870 - val_mae: 0.7844 - val_rmse: 0.9303 - val_smape: 1.7596

Epoch 9/32

144/144 - 3s - 21ms/step - ia: 0.2377 - loss: 1.1894 - mae: 0.8993 - rmse: 1.0895 - smape: 1.5175 - val_ia: 0.2109 - val_loss: 0.8843 - val_mae: 0.7832 - val_rmse: 0.9290 - val_smape: 1.7731

Epoch 10/32

144/144 - 6s - 39ms/step - ia: 0.2339 - loss: 1.1854 - mae: 0.8990 - rmse: 1.0884 - smape: 1.5234 - val_ia: 0.2106 - val_loss: 0.8818 - val_mae: 0.7821 - val_rmse: 0.9279 - val_smape: 1.7861

Epoch 11/32

144/144 - 3s - 24ms/step - ia: 0.2346 - loss: 1.1693 - mae: 0.8938 - rmse: 1.0804 - smape: 1.5252 - val_ia: 0.2107 - val_loss: 0.8799 - val_mae: 0.7813 - val_rmse: 0.9271 - val_smape: 1.7966

Epoch 12/32

144/144 - 4s - 25ms/step - ia: 0.2338 - loss: 1.1633 - mae: 0.8900 - rmse: 1.0782 - smape: 1.5184 - val_ia: 0.2110 - val_loss: 0.8778 - val_mae: 0.7803 - val_rmse: 0.9261 - val_smape: 1.8094

Epoch 13/32

144/144 - 3s - 24ms/step - ia: 0.2309 - loss: 1.1557 - mae: 0.8869 - rmse: 1.0742 - smape: 1.5252 - val_ia: 0.2111 - val_loss: 0.8764 - val_mae: 0.7796 - val_rmse: 0.9255 - val_smape: 1.8183

Epoch 14/32

144/144 - 4s - 24ms/step - ia: 0.2257 - loss: 1.1533 - mae: 0.8861 - rmse: 1.0732 - smape: 1.5322 - val_ia: 0.2113 - val_loss: 0.8751 - val_mae: 0.7791 - val_rmse: 0.9249 - val_smape: 1.8266

Epoch 15/32

144/144 - 4s - 25ms/step - ia: 0.2259 - loss: 1.1436 - mae: 0.8836 - rmse: 1.0692 - smape: 1.5322 - val_ia: 0.2114 - val_loss: 0.8740 - val_mae: 0.7785 - val_rmse: 0.9244 - val_smape: 1.8347

Epoch 16/32

144/144 - 3s - 24ms/step - ia: 0.2220 - loss: 1.1403 - mae: 0.8816 - rmse: 1.0671 - smape: 1.5352 - val_ia: 0.2114 - val_loss: 0.8732 - val_mae: 0.7782 - val_rmse: 0.9240 - val_smape: 1.8400

Epoch 17/32

144/144 - 4s - 25ms/step - ia: 0.2187 - loss: 1.1373 - mae: 0.8803 - rmse: 1.0658 - smape: 1.5421 - val_ia: 0.2115 - val_loss: 0.8726 - val_mae: 0.7779 - val_rmse: 0.9238 - val_smape: 1.8448

Epoch 18/32

144/144 - 4s - 25ms/step - ia: 0.2177 - loss: 1.1314 - mae: 0.8799 - rmse: 1.0625 - smape: 1.5454 - val_ia: 0.2115 - val_loss: 0.8717 - val_mae: 0.7775 - val_rmse: 0.9233 - val_smape: 1.8519

Epoch 19/32

144/144 - 4s - 25ms/step - ia: 0.2136 - loss: 1.1288 - mae: 0.8784 - rmse: 1.0623 - smape: 1.5504 - val_ia: 0.2116 - val_loss: 0.8706 - val_mae: 0.7770 - val_rmse: 0.9229 - val_smape: 1.8604

Epoch 20/32

144/144 - 4s - 25ms/step - ia: 0.2102 - loss: 1.1225 - mae: 0.8770 - rmse: 1.0590 - smape: 1.5545 - val_ia: 0.2116 - val_loss: 0.8698 - val_mae: 0.7766 - val_rmse: 0.9225 - val_smape: 1.8668

Epoch 21/32

144/144 - 3s - 24ms/step - ia: 0.2088 - loss: 1.1174 - mae: 0.8749 - rmse: 1.0564 - smape: 1.5572 - val_ia: 0.2118 - val_loss: 0.8689 - val_mae: 0.7761 - val_rmse: 0.9221 - val_smape: 1.8752

Epoch 22/32

144/144 - 4s - 25ms/step - ia: 0.2058 - loss: 1.1133 - mae: 0.8739 - rmse: 1.0550 - smape: 1.5587 - val_ia: 0.2119 - val_loss: 0.8682 - val_mae: 0.7758 - val_rmse: 0.9218 - val_smape: 1.8816

Epoch 23/32

144/144 - 4s - 26ms/step - ia: 0.2056 - loss: 1.1038 - mae: 0.8703 - rmse: 1.0502 - smape: 1.5614 - val_ia: 0.2120 - val_loss: 0.8679 - val_mae: 0.7757 - val_rmse: 0.9216 - val_smape: 1.8840

Epoch 24/32

144/144 - 4s - 25ms/step - ia: 0.2040 - loss: 1.1025 - mae: 0.8688 - rmse: 1.0483 - smape: 1.5621 - val_ia: 0.2121 - val_loss: 0.8672 - val_mae: 0.7754 - val_rmse: 0.9213 - val_smape: 1.8907

Epoch 25/32

144/144 - 3s - 24ms/step - ia: 0.2028 - loss: 1.0924 - mae: 0.8649 - rmse: 1.0445 - smape: 1.5648 - val_ia: 0.2122 - val_loss: 0.8665 - val_mae: 0.7750 - val_rmse: 0.9210 - val_smape: 1.8978

Epoch 26/32

144/144 - 4s - 26ms/step - ia: 0.1987 - loss: 1.0933 - mae: 0.8656 - rmse: 1.0453 - smape: 1.5695 - val_ia: 0.2123 - val_loss: 0.8659 - val_mae: 0.7747 - val_rmse: 0.9207 - val_smape: 1.9041

Epoch 27/32

144/144 - 4s - 25ms/step - ia: 0.1971 - loss: 1.0878 - mae: 0.8638 - rmse: 1.0414 - smape: 1.5733 - val_ia: 0.2124 - val_loss: 0.8656 - val_mae: 0.7746 - val_rmse: 0.9206 - val_smape: 1.9075

Epoch 28/32

144/144 - 4s - 25ms/step - ia: 0.1925 - loss: 1.0929 - mae: 0.8654 - rmse: 1.0450 - smape: 1.5761 - val_ia: 0.2125 - val_loss: 0.8654 - val_mae: 0.7745 - val_rmse: 0.9205 - val_smape: 1.9102

Epoch 29/32

144/144 - 4s - 25ms/step - ia: 0.1917 - loss: 1.0823 - mae: 0.8617 - rmse: 1.0396 - smape: 1.5807 - val_ia: 0.2126 - val_loss: 0.8651 - val_mae: 0.7743 - val_rmse: 0.9204 - val_smape: 1.9135

Epoch 30/32

144/144 - 4s - 25ms/step - ia: 0.1908 - loss: 1.0787 - mae: 0.8603 - rmse: 1.0377 - smape: 1.5814 - val_ia: 0.2127 - val_loss: 0.8649 - val_mae: 0.7743 - val_rmse: 0.9203 - val_smape: 1.9150

Epoch 31/32

144/144 - 3s - 23ms/step - ia: 0.1877 - loss: 1.0738 - mae: 0.8590 - rmse: 1.0354 - smape: 1.5849 - val_ia: 0.2127 - val_loss: 0.8647 - val_mae: 0.7741 - val_rmse: 0.9202 - val_smape: 1.9178

Epoch 32/32

144/144 - 3s - 23ms/step - ia: 0.1882 - loss: 1.0713 - mae: 0.8572 - rmse: 1.0349 - smape: 1.5850 - val_ia: 0.2127 - val_loss: 0.8647 - val_mae: 0.7741 - val_rmse: 0.9202 - val_smape: 1.9175

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:56 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step

 42%|████▏     | 21/50 [3:05:36<5:34:41, 692.45s/trial, best loss: 0.12201317346183038]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 82s - 36ms/step - ia: 0.4069 - loss: 0.7153 - mae: 0.6774 - rmse: 0.8138 - smape: 1.3031 - val_ia: 0.2060 - val_loss: 0.9358 - val_mae: 0.7832 - val_rmse: 0.8133 - val_smape: 1.2183

Epoch 2/32

2292/2292 - 41s - 18ms/step - ia: 0.7158 - loss: 0.2907 - mae: 0.4172 - rmse: 0.5293 - smape: 0.7516 - val_ia: 0.2194 - val_loss: 0.7251 - val_mae: 0.6714 - val_rmse: 0.7056 - val_smape: 1.1020

Epoch 3/32

2292/2292 - 42s - 18ms/step - ia: 0.7370 - loss: 0.2545 - mae: 0.3915 - rmse: 0.4953 - smape: 0.7283 - val_ia: 0.2226 - val_loss: 0.6512 - val_mae: 0.6211 - val_rmse: 0.6564 - val_smape: 1.0433

Epoch 4/32

2292/2292 - 41s - 18ms/step - ia: 0.7546 - loss: 0.2253 - mae: 0.3669 - rmse: 0.4651 - smape: 0.7031 - val_ia: 0.2568 - val_loss: 0.4851 - val_mae: 0.5411 - val_rmse: 0.5735 - val_smape: 0.9710

Epoch 5/32

2292/2292 - 41s - 18ms/step - ia: 0.7824 - loss: 0.1822 - mae: 0.3277 - rmse: 0.4176 - smape: 0.6665 - val_ia: 0.2972 - val_loss: 0.3001 - val_mae: 0.4363 - val_rmse: 0.4687 - val_smape: 0.8333

Epoch 6/32

2292/2292 - 35s - 15ms/step - ia: 0.8059 - loss: 0.1477 - mae: 0.2933 - rmse: 0.3754 - smape: 0.6270 - val_ia: 0.3218 - val_loss: 0.2513 - val_mae: 0.3979 - val_rmse: 0.4319 - val_smape: 0.7881

Epoch 7/32

2292/2292 - 40s - 17ms/step - ia: 0.8232 - loss: 0.1242 - mae: 0.2675 - rmse: 0.3435 - smape: 0.5966 - val_ia: 0.3404 - val_loss: 0.2265 - val_mae: 0.3769 - val_rmse: 0.4103 - val_smape: 0.7484

Epoch 8/32

2292/2292 - 39s - 17ms/step - ia: 0.8346 - loss: 0.1106 - mae: 0.2501 - rmse: 0.3237 - smape: 0.5755 - val_ia: 0.3480 - val_loss: 0.1897 - val_mae: 0.3468 - val_rmse: 0.3790 - val_smape: 0.7377

Epoch 9/32

2292/2292 - 35s - 15ms/step - ia: 0.8421 - loss: 0.1022 - mae: 0.2381 - rmse: 0.3106 - smape: 0.5624 - val_ia: 0.3532 - val_loss: 0.1999 - val_mae: 0.3528 - val_rmse: 0.3863 - val_smape: 0.7177

Epoch 10/32

2292/2292 - 43s - 19ms/step - ia: 0.8468 - loss: 0.0980 - mae: 0.2320 - rmse: 0.3039 - smape: 0.5534 - val_ia: 0.3695 - val_loss: 0.1609 - val_mae: 0.3165 - val_rmse: 0.3486 - val_smape: 0.6917

Epoch 11/32

2292/2292 - 43s - 19ms/step - ia: 0.8505 - loss: 0.0942 - mae: 0.2265 - rmse: 0.2974 - smape: 0.5457 - val_ia: 0.3623 - val_loss: 0.1905 - val_mae: 0.3448 - val_rmse: 0.3775 - val_smape: 0.7002

Epoch 12/32

2292/2292 - 42s - 18ms/step - ia: 0.8540 - loss: 0.0912 - mae: 0.2221 - rmse: 0.2929 - smape: 0.5374 - val_ia: 0.3804 - val_loss: 0.1571 - val_mae: 0.3119 - val_rmse: 0.3429 - val_smape: 0.6657

Epoch 13/32

2292/2292 - 38s - 17ms/step - ia: 0.8551 - loss: 0.0891 - mae: 0.2195 - rmse: 0.2893 - smape: 0.5331 - val_ia: 0.3810 - val_loss: 0.1535 - val_mae: 0.3084 - val_rmse: 0.3386 - val_smape: 0.6652

Epoch 14/32

2292/2292 - 41s - 18ms/step - ia: 0.8570 - loss: 0.0870 - mae: 0.2165 - rmse: 0.2860 - smape: 0.5296 - val_ia: 0.3491 - val_loss: 0.1992 - val_mae: 0.3593 - val_rmse: 0.3891 - val_smape: 0.7115

Epoch 15/32

2292/2292 - 38s - 17ms/step - ia: 0.8587 - loss: 0.0851 - mae: 0.2141 - rmse: 0.2826 - smape: 0.5240 - val_ia: 0.3882 - val_loss: 0.1445 - val_mae: 0.2994 - val_rmse: 0.3294 - val_smape: 0.6441

Epoch 16/32

2292/2292 - 40s - 18ms/step - ia: 0.8610 - loss: 0.0830 - mae: 0.2108 - rmse: 0.2786 - smape: 0.5181 - val_ia: 0.3908 - val_loss: 0.1395 - val_mae: 0.2939 - val_rmse: 0.3237 - val_smape: 0.6372

Epoch 17/32

2292/2292 - 35s - 15ms/step - ia: 0.8627 - loss: 0.0811 - mae: 0.2083 - rmse: 0.2755 - smape: 0.5131 - val_ia: 0.3871 - val_loss: 0.1490 - val_mae: 0.3043 - val_rmse: 0.3331 - val_smape: 0.6529

Epoch 18/32

2292/2292 - 38s - 17ms/step - ia: 0.8636 - loss: 0.0801 - mae: 0.2070 - rmse: 0.2740 - smape: 0.5096 - val_ia: 0.3864 - val_loss: 0.1458 - val_mae: 0.3030 - val_rmse: 0.3315 - val_smape: 0.6510

Epoch 19/32

2292/2292 - 41s - 18ms/step - ia: 0.8649 - loss: 0.0781 - mae: 0.2045 - rmse: 0.2703 - smape: 0.5063 - val_ia: 0.3881 - val_loss: 0.1376 - val_mae: 0.2950 - val_rmse: 0.3226 - val_smape: 0.6397

Epoch 20/32

2292/2292 - 41s - 18ms/step - ia: 0.8667 - loss: 0.0772 - mae: 0.2030 - rmse: 0.2691 - smape: 0.5004 - val_ia: 0.3828 - val_loss: 0.1459 - val_mae: 0.3043 - val_rmse: 0.3326 - val_smape: 0.6534

Epoch 21/32

2292/2292 - 42s - 18ms/step - ia: 0.8680 - loss: 0.0758 - mae: 0.2010 - rmse: 0.2663 - smape: 0.4969 - val_ia: 0.3925 - val_loss: 0.1208 - val_mae: 0.2765 - val_rmse: 0.3050 - val_smape: 0.6189

Epoch 22/32

2292/2292 - 41s - 18ms/step - ia: 0.8685 - loss: 0.0751 - mae: 0.2003 - rmse: 0.2648 - smape: 0.4963 - val_ia: 0.3811 - val_loss: 0.1386 - val_mae: 0.2981 - val_rmse: 0.3268 - val_smape: 0.6520

Epoch 23/32

2292/2292 - 37s - 16ms/step - ia: 0.8698 - loss: 0.0740 - mae: 0.1982 - rmse: 0.2627 - smape: 0.4918 - val_ia: 0.3754 - val_loss: 0.1473 - val_mae: 0.3087 - val_rmse: 0.3382 - val_smape: 0.6613

Epoch 24/32

2292/2292 - 43s - 19ms/step - ia: 0.8710 - loss: 0.0728 - mae: 0.1965 - rmse: 0.2605 - smape: 0.4893 - val_ia: 0.3763 - val_loss: 0.1418 - val_mae: 0.3018 - val_rmse: 0.3311 - val_smape: 0.6553

Epoch 25/32

2292/2292 - 41s - 18ms/step - ia: 0.8719 - loss: 0.0722 - mae: 0.1956 - rmse: 0.2601 - smape: 0.4872 - val_ia: 0.3647 - val_loss: 0.1595 - val_mae: 0.3234 - val_rmse: 0.3520 - val_smape: 0.6817

Epoch 26/32

2292/2292 - 36s - 16ms/step - ia: 0.8722 - loss: 0.0714 - mae: 0.1948 - rmse: 0.2581 - smape: 0.4862 - val_ia: 0.3716 - val_loss: 0.1497 - val_mae: 0.3108 - val_rmse: 0.3408 - val_smape: 0.6691

Epoch 27/32

2292/2292 - 48s - 21ms/step - ia: 0.8732 - loss: 0.0707 - mae: 0.1932 - rmse: 0.2565 - smape: 0.4836 - val_ia: 0.3775 - val_loss: 0.1413 - val_mae: 0.3018 - val_rmse: 0.3316 - val_smape: 0.6582

Epoch 28/32

2292/2292 - 42s - 18ms/step - ia: 0.8738 - loss: 0.0702 - mae: 0.1927 - rmse: 0.2555 - smape: 0.4836 - val_ia: 0.3791 - val_loss: 0.1329 - val_mae: 0.2925 - val_rmse: 0.3214 - val_smape: 0.6524

Epoch 29/32

2292/2292 - 92s - 40ms/step - ia: 0.8742 - loss: 0.0695 - mae: 0.1919 - rmse: 0.2544 - smape: 0.4807 - val_ia: 0.3689 - val_loss: 0.1441 - val_mae: 0.3065 - val_rmse: 0.3372 - val_smape: 0.6680

Epoch 30/32

2292/2292 - 50s - 22ms/step - ia: 0.8741 - loss: 0.0690 - mae: 0.1913 - rmse: 0.2533 - smape: 0.4827 - val_ia: 0.3798 - val_loss: 0.1300 - val_mae: 0.2890 - val_rmse: 0.3196 - val_smape: 0.6506

Epoch 31/32

2292/2292 - 50s - 22ms/step - ia: 0.8751 - loss: 0.0682 - mae: 0.1903 - rmse: 0.2521 - smape: 0.4798 - val_ia: 0.3753 - val_loss: 0.1387 - val_mae: 0.2992 - val_rmse: 0.3310 - val_smape: 0.6563

Epoch 32/32

2292/2292 - 52s - 23ms/step - ia: 0.8753 - loss: 0.0680 - mae: 0.1899 - rmse: 0.2518 - smape: 0.4802 - val_ia: 0.3691 - val_loss: 0.1480 - val_mae: 0.3086 - val_rmse: 0.3408 - val_smape: 0.6726

Restoring model weights from the end of the best epoch: 21.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 9:01 3s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step

 44%|████▍     | 22/50 [3:29:15<7:04:56, 910.57s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 107s - 47ms/step - ia: 0.4774 - loss: 0.5915 - mae: 0.6111 - rmse: 0.7385 - smape: 1.1816 - val_ia: 0.2135 - val_loss: 0.8373 - val_mae: 0.7470 - val_rmse: 0.7802 - val_smape: 1.1588

Epoch 2/32

2292/2292 - 50s - 22ms/step - ia: 0.7155 - loss: 0.2859 - mae: 0.4214 - rmse: 0.5257 - smape: 0.7580 - val_ia: 0.2170 - val_loss: 0.6168 - val_mae: 0.6342 - val_rmse: 0.6689 - val_smape: 1.0762

Epoch 3/32

2292/2292 - 51s - 22ms/step - ia: 0.7324 - loss: 0.2527 - mae: 0.3986 - rmse: 0.4950 - smape: 0.7396 - val_ia: 0.2264 - val_loss: 0.5775 - val_mae: 0.6020 - val_rmse: 0.6369 - val_smape: 1.0147

Epoch 4/32

2292/2292 - 50s - 22ms/step - ia: 0.7515 - loss: 0.2222 - mae: 0.3711 - rmse: 0.4632 - smape: 0.7147 - val_ia: 0.2717 - val_loss: 0.4200 - val_mae: 0.5038 - val_rmse: 0.5404 - val_smape: 0.9071

Epoch 5/32

2292/2292 - 41s - 18ms/step - ia: 0.7782 - loss: 0.1846 - mae: 0.3345 - rmse: 0.4213 - smape: 0.6756 - val_ia: 0.3117 - val_loss: 0.3032 - val_mae: 0.4265 - val_rmse: 0.4603 - val_smape: 0.7941

Epoch 6/32

2292/2292 - 50s - 22ms/step - ia: 0.7996 - loss: 0.1529 - mae: 0.3029 - rmse: 0.3830 - smape: 0.6455 - val_ia: 0.3316 - val_loss: 0.2647 - val_mae: 0.3971 - val_rmse: 0.4311 - val_smape: 0.7260

Epoch 7/32

2292/2292 - 50s - 22ms/step - ia: 0.8168 - loss: 0.1309 - mae: 0.2774 - rmse: 0.3533 - smape: 0.6175 - val_ia: 0.3199 - val_loss: 0.2636 - val_mae: 0.3975 - val_rmse: 0.4323 - val_smape: 0.7451

Epoch 8/32

2292/2292 - 50s - 22ms/step - ia: 0.8286 - loss: 0.1163 - mae: 0.2593 - rmse: 0.3333 - smape: 0.5976 - val_ia: 0.3508 - val_loss: 0.1918 - val_mae: 0.3450 - val_rmse: 0.3765 - val_smape: 0.6906

Epoch 9/32

2292/2292 - 51s - 22ms/step - ia: 0.8366 - loss: 0.1064 - mae: 0.2471 - rmse: 0.3177 - smape: 0.5826 - val_ia: 0.3299 - val_loss: 0.2059 - val_mae: 0.3687 - val_rmse: 0.3993 - val_smape: 0.7332

Epoch 10/32

2292/2292 - 42s - 18ms/step - ia: 0.8418 - loss: 0.1004 - mae: 0.2388 - rmse: 0.3089 - smape: 0.5714 - val_ia: 0.3431 - val_loss: 0.1814 - val_mae: 0.3461 - val_rmse: 0.3778 - val_smape: 0.7101

Epoch 11/32

2292/2292 - 51s - 22ms/step - ia: 0.8452 - loss: 0.0973 - mae: 0.2347 - rmse: 0.3035 - smape: 0.5661 - val_ia: 0.3398 - val_loss: 0.1892 - val_mae: 0.3591 - val_rmse: 0.3896 - val_smape: 0.7298

Epoch 12/32

2292/2292 - 53s - 23ms/step - ia: 0.8474 - loss: 0.0944 - mae: 0.2309 - rmse: 0.2989 - smape: 0.5608 - val_ia: 0.3412 - val_loss: 0.1911 - val_mae: 0.3555 - val_rmse: 0.3893 - val_smape: 0.7231

Epoch 13/32

2292/2292 - 50s - 22ms/step - ia: 0.8496 - loss: 0.0925 - mae: 0.2280 - rmse: 0.2956 - smape: 0.5556 - val_ia: 0.3725 - val_loss: 0.1456 - val_mae: 0.3092 - val_rmse: 0.3416 - val_smape: 0.6728

Epoch 14/32

2292/2292 - 48s - 21ms/step - ia: 0.8506 - loss: 0.0911 - mae: 0.2258 - rmse: 0.2929 - smape: 0.5511 - val_ia: 0.3570 - val_loss: 0.1654 - val_mae: 0.3281 - val_rmse: 0.3623 - val_smape: 0.6908

Epoch 15/32

2292/2292 - 49s - 21ms/step - ia: 0.8521 - loss: 0.0894 - mae: 0.2241 - rmse: 0.2909 - smape: 0.5484 - val_ia: 0.3674 - val_loss: 0.1540 - val_mae: 0.3132 - val_rmse: 0.3479 - val_smape: 0.6670

Epoch 16/32

2292/2292 - 82s - 36ms/step - ia: 0.8540 - loss: 0.0880 - mae: 0.2220 - rmse: 0.2883 - smape: 0.5470 - val_ia: 0.3620 - val_loss: 0.1627 - val_mae: 0.3261 - val_rmse: 0.3594 - val_smape: 0.6892

Epoch 17/32

2292/2292 - 74s - 32ms/step - ia: 0.8547 - loss: 0.0869 - mae: 0.2204 - rmse: 0.2864 - smape: 0.5412 - val_ia: 0.3633 - val_loss: 0.1612 - val_mae: 0.3261 - val_rmse: 0.3582 - val_smape: 0.6910

Epoch 18/32

2292/2292 - 47s - 21ms/step - ia: 0.8560 - loss: 0.0857 - mae: 0.2191 - rmse: 0.2847 - smape: 0.5409 - val_ia: 0.3339 - val_loss: 0.2052 - val_mae: 0.3670 - val_rmse: 0.4023 - val_smape: 0.7397

Epoch 19/32

2292/2292 - 47s - 20ms/step - ia: 0.8567 - loss: 0.0846 - mae: 0.2178 - rmse: 0.2825 - smape: 0.5371 - val_ia: 0.3611 - val_loss: 0.1693 - val_mae: 0.3258 - val_rmse: 0.3612 - val_smape: 0.6857

Epoch 20/32

2292/2292 - 46s - 20ms/step - ia: 0.8574 - loss: 0.0836 - mae: 0.2164 - rmse: 0.2809 - smape: 0.5346 - val_ia: 0.3553 - val_loss: 0.1739 - val_mae: 0.3292 - val_rmse: 0.3665 - val_smape: 0.6897

Epoch 21/32

2292/2292 - 45s - 20ms/step - ia: 0.8589 - loss: 0.0825 - mae: 0.2147 - rmse: 0.2790 - smape: 0.5316 - val_ia: 0.3391 - val_loss: 0.2051 - val_mae: 0.3597 - val_rmse: 0.3957 - val_smape: 0.7287

Epoch 22/32

2292/2292 - 41s - 18ms/step - ia: 0.8592 - loss: 0.0817 - mae: 0.2138 - rmse: 0.2776 - smape: 0.5306 - val_ia: 0.3588 - val_loss: 0.1702 - val_mae: 0.3260 - val_rmse: 0.3620 - val_smape: 0.6871

Epoch 23/32

2292/2292 - 42s - 18ms/step - ia: 0.8601 - loss: 0.0810 - mae: 0.2129 - rmse: 0.2765 - smape: 0.5290 - val_ia: 0.3701 - val_loss: 0.1578 - val_mae: 0.3151 - val_rmse: 0.3493 - val_smape: 0.6732

Epoch 24/32

2292/2292 - 44s - 19ms/step - ia: 0.8602 - loss: 0.0802 - mae: 0.2121 - rmse: 0.2750 - smape: 0.5280 - val_ia: 0.3499 - val_loss: 0.1953 - val_mae: 0.3429 - val_rmse: 0.3810 - val_smape: 0.7062

Epoch 25/32

2292/2292 - 47s - 20ms/step - ia: 0.8622 - loss: 0.0789 - mae: 0.2095 - rmse: 0.2729 - smape: 0.5234 - val_ia: 0.3265 - val_loss: 0.2291 - val_mae: 0.3774 - val_rmse: 0.4148 - val_smape: 0.7482

Epoch 26/32

2292/2292 - 44s - 19ms/step - ia: 0.8620 - loss: 0.0785 - mae: 0.2094 - rmse: 0.2720 - smape: 0.5231 - val_ia: 0.3745 - val_loss: 0.1518 - val_mae: 0.3092 - val_rmse: 0.3423 - val_smape: 0.6664

Epoch 27/32

2292/2292 - 44s - 19ms/step - ia: 0.8634 - loss: 0.0777 - mae: 0.2078 - rmse: 0.2706 - smape: 0.5197 - val_ia: 0.3573 - val_loss: 0.1802 - val_mae: 0.3339 - val_rmse: 0.3686 - val_smape: 0.6990

Epoch 28/32

2292/2292 - 47s - 20ms/step - ia: 0.8638 - loss: 0.0770 - mae: 0.2075 - rmse: 0.2693 - smape: 0.5212 - val_ia: 0.3608 - val_loss: 0.1708 - val_mae: 0.3236 - val_rmse: 0.3598 - val_smape: 0.6865

Epoch 28: early stopping

Restoring model weights from the end of the best epoch: 13.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:45 3s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step

 46%|████▌     | 23/50 [3:53:25<8:02:30, 1072.25s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 94s - 41ms/step - ia: 0.2042 - loss: 1.0566 - mae: 0.8505 - rmse: 1.0180 - smape: 1.5962 - val_ia: 0.1784 - val_loss: 0.8713 - val_mae: 0.7773 - val_rmse: 0.8137 - val_smape: 1.8501

Epoch 2/32

2292/2292 - 52s - 22ms/step - ia: 0.1869 - loss: 1.0281 - mae: 0.8409 - rmse: 1.0034 - smape: 1.7502 - val_ia: 0.1801 - val_loss: 0.8633 - val_mae: 0.7735 - val_rmse: 0.8100 - val_smape: 1.9213

Epoch 3/32

2292/2292 - 49s - 21ms/step - ia: 0.1863 - loss: 1.0212 - mae: 0.8386 - rmse: 1.0008 - smape: 1.7526 - val_ia: 0.1809 - val_loss: 0.8560 - val_mae: 0.7699 - val_rmse: 0.8066 - val_smape: 1.9664

Epoch 4/32

2292/2292 - 46s - 20ms/step - ia: 0.1825 - loss: 1.0170 - mae: 0.8376 - rmse: 0.9989 - smape: 1.7618 - val_ia: 0.1800 - val_loss: 0.8574 - val_mae: 0.7707 - val_rmse: 0.8074 - val_smape: 1.9543

Epoch 5/32

2292/2292 - 47s - 20ms/step - ia: 0.1837 - loss: 1.0129 - mae: 0.8358 - rmse: 0.9966 - smape: 1.7615 - val_ia: 0.1795 - val_loss: 0.8549 - val_mae: 0.7696 - val_rmse: 0.8062 - val_smape: 1.9286

Epoch 6/32

2292/2292 - 48s - 21ms/step - ia: 0.1826 - loss: 1.0037 - mae: 0.8326 - rmse: 0.9921 - smape: 1.7543 - val_ia: 0.1796 - val_loss: 0.8483 - val_mae: 0.7664 - val_rmse: 0.8031 - val_smape: 1.8867

Epoch 7/32

2292/2292 - 47s - 21ms/step - ia: 0.1913 - loss: 0.9884 - mae: 0.8260 - rmse: 0.9851 - smape: 1.7275 - val_ia: 0.1786 - val_loss: 0.8420 - val_mae: 0.7633 - val_rmse: 0.7999 - val_smape: 1.8127

Epoch 8/32

2292/2292 - 44s - 19ms/step - ia: 0.1970 - loss: 0.9629 - mae: 0.8163 - rmse: 0.9719 - smape: 1.6823 - val_ia: 0.1795 - val_loss: 0.8236 - val_mae: 0.7537 - val_rmse: 0.7904 - val_smape: 1.7084

Epoch 9/32

2292/2292 - 48s - 21ms/step - ia: 0.2196 - loss: 0.9206 - mae: 0.7997 - rmse: 0.9508 - smape: 1.6096 - val_ia: 0.1833 - val_loss: 0.8147 - val_mae: 0.7465 - val_rmse: 0.7829 - val_smape: 1.5554

Epoch 10/32

2292/2292 - 43s - 19ms/step - ia: 0.2717 - loss: 0.8442 - mae: 0.7656 - rmse: 0.9099 - smape: 1.4780 - val_ia: 0.1987 - val_loss: 0.8312 - val_mae: 0.7485 - val_rmse: 0.7841 - val_smape: 1.4100

Epoch 11/32

2292/2292 - 48s - 21ms/step - ia: 0.3410 - loss: 0.7617 - mae: 0.7276 - rmse: 0.8639 - smape: 1.3400 - val_ia: 0.1972 - val_loss: 0.8951 - val_mae: 0.7740 - val_rmse: 0.8073 - val_smape: 1.3338

Epoch 12/32

2292/2292 - 45s - 19ms/step - ia: 0.4123 - loss: 0.6851 - mae: 0.6902 - rmse: 0.8190 - smape: 1.2164 - val_ia: 0.1954 - val_loss: 0.9990 - val_mae: 0.8195 - val_rmse: 0.8521 - val_smape: 1.3097

Epoch 13/32

2292/2292 - 43s - 19ms/step - ia: 0.4678 - loss: 0.6351 - mae: 0.6624 - rmse: 0.7877 - smape: 1.1262 - val_ia: 0.1920 - val_loss: 1.0832 - val_mae: 0.8576 - val_rmse: 0.8898 - val_smape: 1.3112

Epoch 14/32

2292/2292 - 49s - 22ms/step - ia: 0.5051 - loss: 0.6019 - mae: 0.6427 - rmse: 0.7661 - smape: 1.0699 - val_ia: 0.1849 - val_loss: 1.1531 - val_mae: 0.8894 - val_rmse: 0.9212 - val_smape: 1.3228

Epoch 15/32

2292/2292 - 53s - 23ms/step - ia: 0.5271 - loss: 0.5823 - mae: 0.6289 - rmse: 0.7537 - smape: 1.0320 - val_ia: 0.1797 - val_loss: 1.1969 - val_mae: 0.9098 - val_rmse: 0.9412 - val_smape: 1.3363

Epoch 16/32

2292/2292 - 50s - 22ms/step - ia: 0.5434 - loss: 0.5632 - mae: 0.6166 - rmse: 0.7407 - smape: 1.0069 - val_ia: 0.1761 - val_loss: 1.2246 - val_mae: 0.9231 - val_rmse: 0.9540 - val_smape: 1.3462

Epoch 17/32

2292/2292 - 49s - 21ms/step - ia: 0.5570 - loss: 0.5478 - mae: 0.6049 - rmse: 0.7303 - smape: 0.9868 - val_ia: 0.1749 - val_loss: 1.2426 - val_mae: 0.9317 - val_rmse: 0.9623 - val_smape: 1.3531

Epoch 18/32

2292/2292 - 51s - 22ms/step - ia: 0.5685 - loss: 0.5321 - mae: 0.5949 - rmse: 0.7195 - smape: 0.9665 - val_ia: 0.1751 - val_loss: 1.2504 - val_mae: 0.9358 - val_rmse: 0.9661 - val_smape: 1.3570

Epoch 19/32

2292/2292 - 49s - 22ms/step - ia: 0.5733 - loss: 0.5216 - mae: 0.5889 - rmse: 0.7121 - smape: 0.9606 - val_ia: 0.1743 - val_loss: 1.2650 - val_mae: 0.9428 - val_rmse: 0.9730 - val_smape: 1.3612

Epoch 20/32

2292/2292 - 48s - 21ms/step - ia: 0.5810 - loss: 0.5114 - mae: 0.5818 - rmse: 0.7053 - smape: 0.9495 - val_ia: 0.1752 - val_loss: 1.2540 - val_mae: 0.9383 - val_rmse: 0.9685 - val_smape: 1.3613

Epoch 21/32

2292/2292 - 45s - 20ms/step - ia: 0.5908 - loss: 0.4977 - mae: 0.5716 - rmse: 0.6955 - smape: 0.9344 - val_ia: 0.1733 - val_loss: 1.2716 - val_mae: 0.9465 - val_rmse: 0.9765 - val_smape: 1.3664

Epoch 22/32

2292/2292 - 87s - 38ms/step - ia: 0.5971 - loss: 0.4866 - mae: 0.5656 - rmse: 0.6878 - smape: 0.9251 - val_ia: 0.1739 - val_loss: 1.2623 - val_mae: 0.9427 - val_rmse: 0.9727 - val_smape: 1.3657

Epoch 23/32

2292/2292 - 50s - 22ms/step - ia: 0.6048 - loss: 0.4723 - mae: 0.5556 - rmse: 0.6773 - smape: 0.9108 - val_ia: 0.1767 - val_loss: 1.2351 - val_mae: 0.9298 - val_rmse: 0.9603 - val_smape: 1.3557

Epoch 24/32

2292/2292 - 52s - 23ms/step - ia: 0.6096 - loss: 0.4647 - mae: 0.5503 - rmse: 0.6716 - smape: 0.9059 - val_ia: 0.1764 - val_loss: 1.2334 - val_mae: 0.9294 - val_rmse: 0.9598 - val_smape: 1.3554

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:11 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step

 48%|████▊     | 24/50 [4:14:13<8:07:31, 1125.08s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 124s - 27ms/step - ia: 0.4939 - loss: 0.5775 - mae: 0.6021 - rmse: 0.7210 - smape: 1.1425 - val_ia: 0.1655 - val_loss: 1.0026 - val_mae: 0.8051 - val_rmse: 0.8247 - val_smape: 1.1939

Epoch 2/32

4584/4584 - 83s - 18ms/step - ia: 0.7025 - loss: 0.2857 - mae: 0.4142 - rmse: 0.5156 - smape: 0.7396 - val_ia: 0.1629 - val_loss: 0.7477 - val_mae: 0.6788 - val_rmse: 0.7021 - val_smape: 1.0819

Epoch 3/32

4584/4584 - 84s - 18ms/step - ia: 0.7172 - loss: 0.2536 - mae: 0.3943 - rmse: 0.4870 - smape: 0.7244 - val_ia: 0.1686 - val_loss: 0.6491 - val_mae: 0.6171 - val_rmse: 0.6397 - val_smape: 1.0269

Epoch 4/32

4584/4584 - 79s - 17ms/step - ia: 0.7471 - loss: 0.2069 - mae: 0.3540 - rmse: 0.4378 - smape: 0.7011 - val_ia: 0.1748 - val_loss: 0.4955 - val_mae: 0.5364 - val_rmse: 0.5549 - val_smape: 0.9467

Epoch 5/32

4584/4584 - 80s - 17ms/step - ia: 0.7898 - loss: 0.1480 - mae: 0.2924 - rmse: 0.3664 - smape: 0.6490 - val_ia: 0.1991 - val_loss: 0.3784 - val_mae: 0.4717 - val_rmse: 0.4902 - val_smape: 0.8816

Epoch 6/32

4584/4584 - 85s - 18ms/step - ia: 0.8127 - loss: 0.1219 - mae: 0.2627 - rmse: 0.3316 - smape: 0.6125 - val_ia: 0.2090 - val_loss: 0.3008 - val_mae: 0.4283 - val_rmse: 0.4475 - val_smape: 0.8578

Epoch 7/32

4584/4584 - 87s - 19ms/step - ia: 0.8235 - loss: 0.1101 - mae: 0.2478 - rmse: 0.3145 - smape: 0.5908 - val_ia: 0.2321 - val_loss: 0.2609 - val_mae: 0.3974 - val_rmse: 0.4163 - val_smape: 0.7665

Epoch 8/32

4584/4584 - 84s - 18ms/step - ia: 0.8294 - loss: 0.1033 - mae: 0.2384 - rmse: 0.3035 - smape: 0.5761 - val_ia: 0.2383 - val_loss: 0.2101 - val_mae: 0.3639 - val_rmse: 0.3838 - val_smape: 0.7731

Epoch 9/32

4584/4584 - 80s - 18ms/step - ia: 0.8352 - loss: 0.0988 - mae: 0.2317 - rmse: 0.2957 - smape: 0.5663 - val_ia: 0.2425 - val_loss: 0.1943 - val_mae: 0.3519 - val_rmse: 0.3723 - val_smape: 0.7723

Epoch 10/32

4584/4584 - 86s - 19ms/step - ia: 0.8379 - loss: 0.0955 - mae: 0.2273 - rmse: 0.2905 - smape: 0.5581 - val_ia: 0.2435 - val_loss: 0.2138 - val_mae: 0.3663 - val_rmse: 0.3861 - val_smape: 0.7509

Epoch 11/32

4584/4584 - 85s - 18ms/step - ia: 0.8397 - loss: 0.0934 - mae: 0.2246 - rmse: 0.2878 - smape: 0.5541 - val_ia: 0.2465 - val_loss: 0.1947 - val_mae: 0.3500 - val_rmse: 0.3707 - val_smape: 0.7394

Epoch 12/32

4584/4584 - 81s - 18ms/step - ia: 0.8417 - loss: 0.0916 - mae: 0.2219 - rmse: 0.2845 - smape: 0.5496 - val_ia: 0.2440 - val_loss: 0.2003 - val_mae: 0.3568 - val_rmse: 0.3765 - val_smape: 0.7347

Epoch 13/32

4584/4584 - 85s - 18ms/step - ia: 0.8442 - loss: 0.0902 - mae: 0.2204 - rmse: 0.2827 - smape: 0.5480 - val_ia: 0.2510 - val_loss: 0.1831 - val_mae: 0.3391 - val_rmse: 0.3593 - val_smape: 0.7202

Epoch 14/32

4584/4584 - 84s - 18ms/step - ia: 0.8440 - loss: 0.0893 - mae: 0.2191 - rmse: 0.2807 - smape: 0.5460 - val_ia: 0.2469 - val_loss: 0.1883 - val_mae: 0.3458 - val_rmse: 0.3655 - val_smape: 0.7304

Epoch 15/32

4584/4584 - 92s - 20ms/step - ia: 0.8456 - loss: 0.0883 - mae: 0.2182 - rmse: 0.2794 - smape: 0.5446 - val_ia: 0.2614 - val_loss: 0.1670 - val_mae: 0.3250 - val_rmse: 0.3438 - val_smape: 0.6955

Epoch 16/32

4584/4584 - 86s - 19ms/step - ia: 0.8459 - loss: 0.0875 - mae: 0.2171 - rmse: 0.2782 - smape: 0.5401 - val_ia: 0.2544 - val_loss: 0.1845 - val_mae: 0.3413 - val_rmse: 0.3600 - val_smape: 0.7137

Epoch 17/32

4584/4584 - 81s - 18ms/step - ia: 0.8457 - loss: 0.0865 - mae: 0.2158 - rmse: 0.2769 - smape: 0.5397 - val_ia: 0.2617 - val_loss: 0.1553 - val_mae: 0.3160 - val_rmse: 0.3348 - val_smape: 0.6912

Epoch 18/32

4584/4584 - 88s - 19ms/step - ia: 0.8472 - loss: 0.0858 - mae: 0.2148 - rmse: 0.2755 - smape: 0.5381 - val_ia: 0.2504 - val_loss: 0.1818 - val_mae: 0.3392 - val_rmse: 0.3585 - val_smape: 0.7159

Epoch 19/32

4584/4584 - 90s - 20ms/step - ia: 0.8488 - loss: 0.0850 - mae: 0.2134 - rmse: 0.2743 - smape: 0.5332 - val_ia: 0.2428 - val_loss: 0.2142 - val_mae: 0.3649 - val_rmse: 0.3835 - val_smape: 0.7399

Epoch 20/32

4584/4584 - 86s - 19ms/step - ia: 0.8480 - loss: 0.0845 - mae: 0.2132 - rmse: 0.2737 - smape: 0.5331 - val_ia: 0.2577 - val_loss: 0.1601 - val_mae: 0.3213 - val_rmse: 0.3399 - val_smape: 0.6990

Epoch 21/32

4584/4584 - 79s - 17ms/step - ia: 0.8490 - loss: 0.0839 - mae: 0.2125 - rmse: 0.2730 - smape: 0.5330 - val_ia: 0.2552 - val_loss: 0.1746 - val_mae: 0.3333 - val_rmse: 0.3518 - val_smape: 0.7097

Epoch 22/32

4584/4584 - 83s - 18ms/step - ia: 0.8493 - loss: 0.0831 - mae: 0.2113 - rmse: 0.2715 - smape: 0.5307 - val_ia: 0.2574 - val_loss: 0.1751 - val_mae: 0.3330 - val_rmse: 0.3515 - val_smape: 0.7005

Epoch 23/32

4584/4584 - 83s - 18ms/step - ia: 0.8501 - loss: 0.0823 - mae: 0.2101 - rmse: 0.2700 - smape: 0.5276 - val_ia: 0.2587 - val_loss: 0.1711 - val_mae: 0.3289 - val_rmse: 0.3477 - val_smape: 0.7000

Epoch 24/32

4584/4584 - 85s - 18ms/step - ia: 0.8514 - loss: 0.0817 - mae: 0.2096 - rmse: 0.2693 - smape: 0.5276 - val_ia: 0.2569 - val_loss: 0.1632 - val_mae: 0.3237 - val_rmse: 0.3428 - val_smape: 0.7002

Epoch 25/32

4584/4584 - 83s - 18ms/step - ia: 0.8517 - loss: 0.0810 - mae: 0.2083 - rmse: 0.2682 - smape: 0.5231 - val_ia: 0.2524 - val_loss: 0.1699 - val_mae: 0.3307 - val_rmse: 0.3496 - val_smape: 0.7144

Epoch 26/32

4584/4584 - 105s - 23ms/step - ia: 0.8515 - loss: 0.0805 - mae: 0.2078 - rmse: 0.2674 - smape: 0.5239 - val_ia: 0.2632 - val_loss: 0.1660 - val_mae: 0.3247 - val_rmse: 0.3435 - val_smape: 0.6929

Epoch 27/32

4584/4584 - 90s - 20ms/step - ia: 0.8541 - loss: 0.0796 - mae: 0.2066 - rmse: 0.2657 - smape: 0.5197 - val_ia: 0.2583 - val_loss: 0.1891 - val_mae: 0.3418 - val_rmse: 0.3600 - val_smape: 0.7106

Epoch 28/32

4584/4584 - 144s - 31ms/step - ia: 0.8536 - loss: 0.0790 - mae: 0.2062 - rmse: 0.2649 - smape: 0.5216 - val_ia: 0.2512 - val_loss: 0.2055 - val_mae: 0.3551 - val_rmse: 0.3745 - val_smape: 0.7269

Epoch 29/32

4584/4584 - 99s - 22ms/step - ia: 0.8548 - loss: 0.0781 - mae: 0.2045 - rmse: 0.2631 - smape: 0.5191 - val_ia: 0.2503 - val_loss: 0.1683 - val_mae: 0.3285 - val_rmse: 0.3478 - val_smape: 0.7153

Epoch 30/32

4584/4584 - 106s - 23ms/step - ia: 0.8550 - loss: 0.0776 - mae: 0.2043 - rmse: 0.2627 - smape: 0.5175 - val_ia: 0.2510 - val_loss: 0.2162 - val_mae: 0.3669 - val_rmse: 0.3860 - val_smape: 0.7308

Epoch 31/32

4584/4584 - 107s - 23ms/step - ia: 0.8559 - loss: 0.0769 - mae: 0.2032 - rmse: 0.2611 - smape: 0.5140 - val_ia: 0.2577 - val_loss: 0.1901 - val_mae: 0.3425 - val_rmse: 0.3618 - val_smape: 0.7136

Epoch 32/32

4584/4584 - 98s - 21ms/step - ia: 0.8562 - loss: 0.0763 - mae: 0.2027 - rmse: 0.2602 - smape: 0.5137 - val_ia: 0.2560 - val_loss: 0.2033 - val_mae: 0.3516 - val_rmse: 0.3712 - val_smape: 0.7219

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 11:07 4s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step

 50%|█████     | 25/50 [5:02:36<11:31:05, 1658.62s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 123s - 54ms/step - ia: 0.2193 - loss: 1.2636 - mae: 0.9200 - rmse: 1.0958 - smape: 1.6123 - val_ia: 0.1791 - val_loss: 0.8661 - val_mae: 0.7749 - val_rmse: 0.8114 - val_smape: 1.8801

Epoch 2/64

2292/2292 - 55s - 24ms/step - ia: 0.1883 - loss: 0.9967 - mae: 0.8293 - rmse: 0.9886 - smape: 1.7099 - val_ia: 0.1770 - val_loss: 0.8271 - val_mae: 0.7561 - val_rmse: 0.7928 - val_smape: 1.7070

Epoch 3/64

2292/2292 - 69s - 30ms/step - ia: 0.3798 - loss: 0.7156 - mae: 0.6990 - rmse: 0.8328 - smape: 1.3035 - val_ia: 0.1703 - val_loss: 1.2370 - val_mae: 0.9398 - val_rmse: 0.9678 - val_smape: 1.3693

Epoch 4/64

2292/2292 - 64s - 28ms/step - ia: 0.6126 - loss: 0.4560 - mae: 0.5427 - rmse: 0.6652 - smape: 0.9043 - val_ia: 0.1679 - val_loss: 1.2429 - val_mae: 0.9440 - val_rmse: 0.9718 - val_smape: 1.3808

Epoch 5/64

2292/2292 - 57s - 25ms/step - ia: 0.6498 - loss: 0.4070 - mae: 0.5038 - rmse: 0.6266 - smape: 0.8551 - val_ia: 0.1883 - val_loss: 1.0924 - val_mae: 0.8607 - val_rmse: 0.8910 - val_smape: 1.2708

Epoch 6/64

2292/2292 - 50s - 22ms/step - ia: 0.6639 - loss: 0.3844 - mae: 0.4861 - rmse: 0.6098 - smape: 0.8351 - val_ia: 0.2018 - val_loss: 0.9976 - val_mae: 0.8077 - val_rmse: 0.8395 - val_smape: 1.2105

Epoch 7/64

2292/2292 - 51s - 22ms/step - ia: 0.6754 - loss: 0.3640 - mae: 0.4729 - rmse: 0.5927 - smape: 0.8142 - val_ia: 0.2129 - val_loss: 0.9827 - val_mae: 0.7883 - val_rmse: 0.8208 - val_smape: 1.1624

Epoch 8/64

2292/2292 - 67s - 29ms/step - ia: 0.6818 - loss: 0.3537 - mae: 0.4648 - rmse: 0.5843 - smape: 0.8075 - val_ia: 0.2246 - val_loss: 0.9709 - val_mae: 0.7736 - val_rmse: 0.8069 - val_smape: 1.1288

Epoch 9/64

2292/2292 - 71s - 31ms/step - ia: 0.6905 - loss: 0.3393 - mae: 0.4552 - rmse: 0.5723 - smape: 0.7990 - val_ia: 0.2285 - val_loss: 0.9798 - val_mae: 0.7748 - val_rmse: 0.8085 - val_smape: 1.1209

Epoch 10/64

2292/2292 - 74s - 32ms/step - ia: 0.6963 - loss: 0.3261 - mae: 0.4458 - rmse: 0.5611 - smape: 0.7911 - val_ia: 0.2269 - val_loss: 0.8908 - val_mae: 0.7311 - val_rmse: 0.7650 - val_smape: 1.1059

Epoch 11/64

2292/2292 - 87s - 38ms/step - ia: 0.7020 - loss: 0.3165 - mae: 0.4393 - rmse: 0.5533 - smape: 0.7855 - val_ia: 0.2247 - val_loss: 0.8368 - val_mae: 0.7070 - val_rmse: 0.7410 - val_smape: 1.1069

Epoch 12/64

2292/2292 - 60s - 26ms/step - ia: 0.7061 - loss: 0.3050 - mae: 0.4326 - rmse: 0.5428 - smape: 0.7819 - val_ia: 0.2238 - val_loss: 0.8503 - val_mae: 0.7099 - val_rmse: 0.7439 - val_smape: 1.1064

Epoch 13/64

2292/2292 - 54s - 23ms/step - ia: 0.7113 - loss: 0.2953 - mae: 0.4253 - rmse: 0.5340 - smape: 0.7742 - val_ia: 0.2237 - val_loss: 0.8698 - val_mae: 0.7139 - val_rmse: 0.7488 - val_smape: 1.1054

Epoch 14/64

2292/2292 - 65s - 28ms/step - ia: 0.7175 - loss: 0.2846 - mae: 0.4174 - rmse: 0.5239 - smape: 0.7684 - val_ia: 0.2269 - val_loss: 0.7519 - val_mae: 0.6612 - val_rmse: 0.6960 - val_smape: 1.0896

Epoch 15/64

2292/2292 - 71s - 31ms/step - ia: 0.7192 - loss: 0.2778 - mae: 0.4133 - rmse: 0.5186 - smape: 0.7673 - val_ia: 0.2315 - val_loss: 0.7185 - val_mae: 0.6428 - val_rmse: 0.6787 - val_smape: 1.0706

Epoch 16/64

2292/2292 - 66s - 29ms/step - ia: 0.7231 - loss: 0.2726 - mae: 0.4093 - rmse: 0.5126 - smape: 0.7634 - val_ia: 0.2333 - val_loss: 0.7337 - val_mae: 0.6461 - val_rmse: 0.6825 - val_smape: 1.0760

Epoch 17/64

2292/2292 - 51s - 22ms/step - ia: 0.7256 - loss: 0.2667 - mae: 0.4049 - rmse: 0.5075 - smape: 0.7616 - val_ia: 0.2374 - val_loss: 0.7036 - val_mae: 0.6297 - val_rmse: 0.6673 - val_smape: 1.0601

Epoch 18/64

2292/2292 - 71s - 31ms/step - ia: 0.7302 - loss: 0.2597 - mae: 0.3996 - rmse: 0.5011 - smape: 0.7580 - val_ia: 0.2406 - val_loss: 0.7249 - val_mae: 0.6366 - val_rmse: 0.6758 - val_smape: 1.0484

Epoch 19/64

2292/2292 - 75s - 33ms/step - ia: 0.7307 - loss: 0.2572 - mae: 0.3976 - rmse: 0.4984 - smape: 0.7536 - val_ia: 0.2454 - val_loss: 0.6761 - val_mae: 0.6123 - val_rmse: 0.6515 - val_smape: 1.0388

Epoch 20/64

2292/2292 - 66s - 29ms/step - ia: 0.7349 - loss: 0.2511 - mae: 0.3923 - rmse: 0.4926 - smape: 0.7507 - val_ia: 0.2490 - val_loss: 0.6669 - val_mae: 0.6052 - val_rmse: 0.6453 - val_smape: 1.0340

Epoch 21/64

2292/2292 - 67s - 29ms/step - ia: 0.7401 - loss: 0.2415 - mae: 0.3845 - rmse: 0.4829 - smape: 0.7433 - val_ia: 0.2560 - val_loss: 0.6055 - val_mae: 0.5749 - val_rmse: 0.6155 - val_smape: 0.9987

Epoch 22/64

2292/2292 - 69s - 30ms/step - ia: 0.7437 - loss: 0.2369 - mae: 0.3807 - rmse: 0.4777 - smape: 0.7395 - val_ia: 0.2562 - val_loss: 0.6246 - val_mae: 0.5821 - val_rmse: 0.6235 - val_smape: 1.0036

Epoch 23/64

2292/2292 - 70s - 31ms/step - ia: 0.7466 - loss: 0.2321 - mae: 0.3761 - rmse: 0.4732 - smape: 0.7339 - val_ia: 0.2590 - val_loss: 0.6078 - val_mae: 0.5726 - val_rmse: 0.6148 - val_smape: 0.9839

Epoch 24/64

2292/2292 - 78s - 34ms/step - ia: 0.7501 - loss: 0.2255 - mae: 0.3709 - rmse: 0.4665 - smape: 0.7278 - val_ia: 0.2601 - val_loss: 0.6232 - val_mae: 0.5815 - val_rmse: 0.6236 - val_smape: 0.9879

Epoch 25/64

2292/2292 - 82s - 36ms/step - ia: 0.7543 - loss: 0.2202 - mae: 0.3656 - rmse: 0.4604 - smape: 0.7210 - val_ia: 0.2697 - val_loss: 0.5493 - val_mae: 0.5432 - val_rmse: 0.5862 - val_smape: 0.9509

Epoch 26/64

2292/2292 - 55s - 24ms/step - ia: 0.7577 - loss: 0.2144 - mae: 0.3606 - rmse: 0.4545 - smape: 0.7153 - val_ia: 0.2738 - val_loss: 0.5334 - val_mae: 0.5335 - val_rmse: 0.5759 - val_smape: 0.9480

Epoch 27/64

2292/2292 - 41s - 18ms/step - ia: 0.7609 - loss: 0.2083 - mae: 0.3557 - rmse: 0.4478 - smape: 0.7107 - val_ia: 0.2775 - val_loss: 0.5297 - val_mae: 0.5292 - val_rmse: 0.5723 - val_smape: 0.9409

Epoch 28/64

2292/2292 - 53s - 23ms/step - ia: 0.7661 - loss: 0.2008 - mae: 0.3487 - rmse: 0.4393 - smape: 0.7035 - val_ia: 0.2796 - val_loss: 0.5272 - val_mae: 0.5255 - val_rmse: 0.5703 - val_smape: 0.9325

Epoch 29/64

2292/2292 - 88s - 38ms/step - ia: 0.7685 - loss: 0.1977 - mae: 0.3459 - rmse: 0.4361 - smape: 0.6997 - val_ia: 0.2837 - val_loss: 0.5131 - val_mae: 0.5194 - val_rmse: 0.5631 - val_smape: 0.9269

Epoch 30/64

2292/2292 - 81s - 35ms/step - ia: 0.7707 - loss: 0.1930 - mae: 0.3421 - rmse: 0.4312 - smape: 0.6961 - val_ia: 0.2869 - val_loss: 0.5185 - val_mae: 0.5200 - val_rmse: 0.5652 - val_smape: 0.9232

Epoch 31/64

2292/2292 - 55s - 24ms/step - ia: 0.7737 - loss: 0.1905 - mae: 0.3386 - rmse: 0.4279 - smape: 0.6918 - val_ia: 0.2840 - val_loss: 0.5324 - val_mae: 0.5264 - val_rmse: 0.5719 - val_smape: 0.9328

Epoch 32/64

2292/2292 - 44s - 19ms/step - ia: 0.7752 - loss: 0.1852 - mae: 0.3346 - rmse: 0.4220 - smape: 0.6878 - val_ia: 0.2927 - val_loss: 0.4808 - val_mae: 0.5006 - val_rmse: 0.5449 - val_smape: 0.9052

Epoch 33/64

2292/2292 - 61s - 27ms/step - ia: 0.7784 - loss: 0.1828 - mae: 0.3320 - rmse: 0.4192 - smape: 0.6857 - val_ia: 0.2912 - val_loss: 0.4909 - val_mae: 0.5078 - val_rmse: 0.5517 - val_smape: 0.9139

Epoch 34/64

2292/2292 - 71s - 31ms/step - ia: 0.7799 - loss: 0.1796 - mae: 0.3285 - rmse: 0.4155 - smape: 0.6851 - val_ia: 0.2956 - val_loss: 0.4665 - val_mae: 0.4920 - val_rmse: 0.5359 - val_smape: 0.8999

Epoch 35/64

2292/2292 - 64s - 28ms/step - ia: 0.7838 - loss: 0.1748 - mae: 0.3232 - rmse: 0.4097 - smape: 0.6774 - val_ia: 0.2933 - val_loss: 0.5044 - val_mae: 0.5125 - val_rmse: 0.5575 - val_smape: 0.9083

Epoch 36/64

2292/2292 - 87s - 38ms/step - ia: 0.7846 - loss: 0.1726 - mae: 0.3223 - rmse: 0.4071 - smape: 0.6761 - val_ia: 0.3028 - val_loss: 0.4372 - val_mae: 0.4782 - val_rmse: 0.5223 - val_smape: 0.8772

Epoch 37/64

2292/2292 - 50s - 22ms/step - ia: 0.7860 - loss: 0.1707 - mae: 0.3202 - rmse: 0.4050 - smape: 0.6753 - val_ia: 0.3033 - val_loss: 0.4311 - val_mae: 0.4747 - val_rmse: 0.5181 - val_smape: 0.8753

Epoch 38/64

2292/2292 - 56s - 25ms/step - ia: 0.7883 - loss: 0.1682 - mae: 0.3171 - rmse: 0.4019 - smape: 0.6705 - val_ia: 0.3021 - val_loss: 0.4418 - val_mae: 0.4811 - val_rmse: 0.5240 - val_smape: 0.8814

Epoch 39/64

2292/2292 - 69s - 30ms/step - ia: 0.7898 - loss: 0.1668 - mae: 0.3155 - rmse: 0.4002 - smape: 0.6677 - val_ia: 0.3020 - val_loss: 0.4348 - val_mae: 0.4792 - val_rmse: 0.5214 - val_smape: 0.8842

Epoch 40/64

2292/2292 - 66s - 29ms/step - ia: 0.7899 - loss: 0.1638 - mae: 0.3137 - rmse: 0.3968 - smape: 0.6679 - val_ia: 0.3056 - val_loss: 0.4191 - val_mae: 0.4680 - val_rmse: 0.5119 - val_smape: 0.8670

Epoch 41/64

2292/2292 - 68s - 30ms/step - ia: 0.7924 - loss: 0.1614 - mae: 0.3105 - rmse: 0.3930 - smape: 0.6658 - val_ia: 0.3091 - val_loss: 0.3723 - val_mae: 0.4445 - val_rmse: 0.4870 - val_smape: 0.8580

Epoch 42/64

2292/2292 - 68s - 30ms/step - ia: 0.7945 - loss: 0.1596 - mae: 0.3081 - rmse: 0.3910 - smape: 0.6628 - val_ia: 0.3094 - val_loss: 0.3720 - val_mae: 0.4437 - val_rmse: 0.4861 - val_smape: 0.8598

Epoch 43/64

2292/2292 - 64s - 28ms/step - ia: 0.7964 - loss: 0.1572 - mae: 0.3055 - rmse: 0.3883 - smape: 0.6576 - val_ia: 0.3087 - val_loss: 0.3974 - val_mae: 0.4608 - val_rmse: 0.5029 - val_smape: 0.8587

Epoch 44/64

2292/2292 - 68s - 30ms/step - ia: 0.7970 - loss: 0.1564 - mae: 0.3048 - rmse: 0.3873 - smape: 0.6571 - val_ia: 0.3132 - val_loss: 0.3683 - val_mae: 0.4442 - val_rmse: 0.4862 - val_smape: 0.8466

Epoch 45/64

2292/2292 - 67s - 29ms/step - ia: 0.7985 - loss: 0.1539 - mae: 0.3020 - rmse: 0.3843 - smape: 0.6540 - val_ia: 0.3172 - val_loss: 0.3527 - val_mae: 0.4343 - val_rmse: 0.4754 - val_smape: 0.8332

Epoch 46/64

2292/2292 - 82s - 36ms/step - ia: 0.7986 - loss: 0.1529 - mae: 0.3017 - rmse: 0.3830 - smape: 0.6550 - val_ia: 0.3158 - val_loss: 0.3586 - val_mae: 0.4389 - val_rmse: 0.4810 - val_smape: 0.8339

Epoch 47/64

2292/2292 - 62s - 27ms/step - ia: 0.8010 - loss: 0.1500 - mae: 0.2978 - rmse: 0.3790 - smape: 0.6467 - val_ia: 0.3199 - val_loss: 0.3513 - val_mae: 0.4334 - val_rmse: 0.4746 - val_smape: 0.8239

Epoch 48/64

2292/2292 - 58s - 25ms/step - ia: 0.8021 - loss: 0.1478 - mae: 0.2958 - rmse: 0.3763 - smape: 0.6487 - val_ia: 0.3259 - val_loss: 0.3167 - val_mae: 0.4143 - val_rmse: 0.4558 - val_smape: 0.8028

Epoch 49/64

2292/2292 - 56s - 25ms/step - ia: 0.8031 - loss: 0.1481 - mae: 0.2957 - rmse: 0.3764 - smape: 0.6452 - val_ia: 0.3190 - val_loss: 0.3339 - val_mae: 0.4272 - val_rmse: 0.4682 - val_smape: 0.8199

Epoch 50/64

2292/2292 - 67s - 29ms/step - ia: 0.8038 - loss: 0.1458 - mae: 0.2940 - rmse: 0.3736 - smape: 0.6462 - val_ia: 0.3223 - val_loss: 0.3324 - val_mae: 0.4261 - val_rmse: 0.4670 - val_smape: 0.8118

Epoch 51/64

2292/2292 - 63s - 27ms/step - ia: 0.8042 - loss: 0.1457 - mae: 0.2934 - rmse: 0.3733 - smape: 0.6425 - val_ia: 0.3262 - val_loss: 0.3074 - val_mae: 0.4118 - val_rmse: 0.4519 - val_smape: 0.7951

Epoch 52/64

2292/2292 - 59s - 26ms/step - ia: 0.8055 - loss: 0.1445 - mae: 0.2916 - rmse: 0.3723 - smape: 0.6410 - val_ia: 0.3275 - val_loss: 0.2961 - val_mae: 0.4042 - val_rmse: 0.4444 - val_smape: 0.7917

Epoch 53/64

2292/2292 - 67s - 29ms/step - ia: 0.8073 - loss: 0.1412 - mae: 0.2889 - rmse: 0.3675 - smape: 0.6384 - val_ia: 0.3296 - val_loss: 0.2900 - val_mae: 0.4009 - val_rmse: 0.4410 - val_smape: 0.7843

Epoch 54/64

2292/2292 - 64s - 28ms/step - ia: 0.8084 - loss: 0.1408 - mae: 0.2878 - rmse: 0.3667 - smape: 0.6380 - val_ia: 0.3347 - val_loss: 0.2647 - val_mae: 0.3839 - val_rmse: 0.4247 - val_smape: 0.7665

Epoch 55/64

2292/2292 - 83s - 36ms/step - ia: 0.8103 - loss: 0.1380 - mae: 0.2850 - rmse: 0.3635 - smape: 0.6328 - val_ia: 0.3308 - val_loss: 0.2835 - val_mae: 0.3977 - val_rmse: 0.4397 - val_smape: 0.7741

Epoch 56/64

2292/2292 - 69s - 30ms/step - ia: 0.8108 - loss: 0.1381 - mae: 0.2845 - rmse: 0.3632 - smape: 0.6320 - val_ia: 0.3335 - val_loss: 0.2647 - val_mae: 0.3864 - val_rmse: 0.4261 - val_smape: 0.7666

Epoch 57/64

2292/2292 - 50s - 22ms/step - ia: 0.8116 - loss: 0.1356 - mae: 0.2827 - rmse: 0.3600 - smape: 0.6282 - val_ia: 0.3337 - val_loss: 0.2726 - val_mae: 0.3917 - val_rmse: 0.4323 - val_smape: 0.7643

Epoch 58/64

2292/2292 - 64s - 28ms/step - ia: 0.8113 - loss: 0.1362 - mae: 0.2828 - rmse: 0.3606 - smape: 0.6293 - val_ia: 0.3347 - val_loss: 0.2654 - val_mae: 0.3877 - val_rmse: 0.4263 - val_smape: 0.7600

Epoch 59/64

2292/2292 - 69s - 30ms/step - ia: 0.8137 - loss: 0.1341 - mae: 0.2807 - rmse: 0.3582 - smape: 0.6265 - val_ia: 0.3348 - val_loss: 0.2581 - val_mae: 0.3820 - val_rmse: 0.4222 - val_smape: 0.7576

Epoch 60/64

2292/2292 - 67s - 29ms/step - ia: 0.8142 - loss: 0.1333 - mae: 0.2794 - rmse: 0.3570 - smape: 0.6268 - val_ia: 0.3374 - val_loss: 0.2515 - val_mae: 0.3783 - val_rmse: 0.4176 - val_smape: 0.7507

Epoch 61/64

2292/2292 - 74s - 32ms/step - ia: 0.8141 - loss: 0.1335 - mae: 0.2795 - rmse: 0.3574 - smape: 0.6248 - val_ia: 0.3388 - val_loss: 0.2448 - val_mae: 0.3727 - val_rmse: 0.4125 - val_smape: 0.7431

Epoch 62/64

2292/2292 - 79s - 34ms/step - ia: 0.8153 - loss: 0.1315 - mae: 0.2777 - rmse: 0.3545 - smape: 0.6244 - val_ia: 0.3374 - val_loss: 0.2506 - val_mae: 0.3773 - val_rmse: 0.4166 - val_smape: 0.7477

Epoch 63/64

2292/2292 - 62s - 27ms/step - ia: 0.8162 - loss: 0.1304 - mae: 0.2765 - rmse: 0.3531 - smape: 0.6209 - val_ia: 0.3372 - val_loss: 0.2469 - val_mae: 0.3757 - val_rmse: 0.4153 - val_smape: 0.7462

Epoch 64/64

2292/2292 - 77s - 34ms/step - ia: 0.8182 - loss: 0.1288 - mae: 0.2739 - rmse: 0.3507 - smape: 0.6161 - val_ia: 0.3415 - val_loss: 0.2234 - val_mae: 0.3605 - val_rmse: 0.3989 - val_smape: 0.7339

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 14:56 6s/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 11s 31ms/step

 52%|█████▏    | 26/50 [6:13:55<16:17:54, 2444.79s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 93s - 40ms/step - ia: 0.7138 - loss: 0.2806 - mae: 0.3941 - rmse: 0.4937 - smape: 0.7901 - val_ia: 0.2784 - val_loss: 0.2597 - val_mae: 0.4110 - val_rmse: 0.4509 - val_smape: 0.8302

Epoch 2/32

2292/2292 - 54s - 23ms/step - ia: 0.8395 - loss: 0.1060 - mae: 0.2412 - rmse: 0.3157 - smape: 0.5907 - val_ia: 0.3336 - val_loss: 0.1927 - val_mae: 0.3408 - val_rmse: 0.3859 - val_smape: 0.7331

Epoch 3/32

2292/2292 - 51s - 22ms/step - ia: 0.8519 - loss: 0.0926 - mae: 0.2232 - rmse: 0.2944 - smape: 0.5528 - val_ia: 0.3661 - val_loss: 0.1601 - val_mae: 0.3106 - val_rmse: 0.3429 - val_smape: 0.6780

Epoch 4/32

2292/2292 - 84s - 37ms/step - ia: 0.8578 - loss: 0.0860 - mae: 0.2150 - rmse: 0.2832 - smape: 0.5394 - val_ia: 0.3651 - val_loss: 0.1737 - val_mae: 0.3237 - val_rmse: 0.3584 - val_smape: 0.6711

Epoch 5/32

2292/2292 - 44s - 19ms/step - ia: 0.8623 - loss: 0.0812 - mae: 0.2089 - rmse: 0.2755 - smape: 0.5250 - val_ia: 0.3827 - val_loss: 0.1307 - val_mae: 0.2855 - val_rmse: 0.3213 - val_smape: 0.6257

Epoch 6/32

2292/2292 - 50s - 22ms/step - ia: 0.8656 - loss: 0.0772 - mae: 0.2040 - rmse: 0.2686 - smape: 0.5156 - val_ia: 0.3668 - val_loss: 0.1578 - val_mae: 0.3085 - val_rmse: 0.3486 - val_smape: 0.6492

Epoch 7/32

2292/2292 - 44s - 19ms/step - ia: 0.8688 - loss: 0.0738 - mae: 0.1986 - rmse: 0.2622 - smape: 0.5037 - val_ia: 0.3529 - val_loss: 0.1780 - val_mae: 0.3240 - val_rmse: 0.3656 - val_smape: 0.6659

Epoch 8/32

2292/2292 - 38s - 16ms/step - ia: 0.8722 - loss: 0.0709 - mae: 0.1947 - rmse: 0.2569 - smape: 0.4967 - val_ia: 0.3603 - val_loss: 0.1759 - val_mae: 0.3207 - val_rmse: 0.3611 - val_smape: 0.6596

Epoch 9/32

2292/2292 - 47s - 21ms/step - ia: 0.8738 - loss: 0.0692 - mae: 0.1924 - rmse: 0.2540 - smape: 0.4927 - val_ia: 0.3673 - val_loss: 0.1774 - val_mae: 0.3224 - val_rmse: 0.3587 - val_smape: 0.6392

Epoch 10/32

2292/2292 - 53s - 23ms/step - ia: 0.8751 - loss: 0.0677 - mae: 0.1901 - rmse: 0.2517 - smape: 0.4886 - val_ia: 0.3691 - val_loss: 0.1627 - val_mae: 0.3123 - val_rmse: 0.3499 - val_smape: 0.6471

Epoch 11/32

2292/2292 - 58s - 25ms/step - ia: 0.8779 - loss: 0.0653 - mae: 0.1867 - rmse: 0.2469 - smape: 0.4822 - val_ia: 0.3401 - val_loss: 0.2070 - val_mae: 0.3426 - val_rmse: 0.3889 - val_smape: 0.6877

Epoch 12/32

2292/2292 - 60s - 26ms/step - ia: 0.8781 - loss: 0.0652 - mae: 0.1865 - rmse: 0.2465 - smape: 0.4788 - val_ia: 0.3407 - val_loss: 0.2049 - val_mae: 0.3518 - val_rmse: 0.3913 - val_smape: 0.6946

Epoch 13/32

2292/2292 - 61s - 27ms/step - ia: 0.8793 - loss: 0.0643 - mae: 0.1845 - rmse: 0.2445 - smape: 0.4751 - val_ia: 0.3365 - val_loss: 0.2283 - val_mae: 0.3636 - val_rmse: 0.4082 - val_smape: 0.7034

Epoch 14/32

2292/2292 - 60s - 26ms/step - ia: 0.8800 - loss: 0.0633 - mae: 0.1832 - rmse: 0.2429 - smape: 0.4733 - val_ia: 0.3380 - val_loss: 0.2052 - val_mae: 0.3519 - val_rmse: 0.3919 - val_smape: 0.6971

Epoch 15/32

2292/2292 - 55s - 24ms/step - ia: 0.8806 - loss: 0.0626 - mae: 0.1824 - rmse: 0.2414 - smape: 0.4708 - val_ia: 0.3470 - val_loss: 0.1848 - val_mae: 0.3326 - val_rmse: 0.3759 - val_smape: 0.6922

Epoch 16/32

2292/2292 - 61s - 26ms/step - ia: 0.8817 - loss: 0.0618 - mae: 0.1813 - rmse: 0.2399 - smape: 0.4674 - val_ia: 0.3270 - val_loss: 0.2104 - val_mae: 0.3570 - val_rmse: 0.4019 - val_smape: 0.7170

Epoch 17/32

2292/2292 - 55s - 24ms/step - ia: 0.8827 - loss: 0.0606 - mae: 0.1796 - rmse: 0.2376 - smape: 0.4637 - val_ia: 0.3636 - val_loss: 0.1555 - val_mae: 0.3087 - val_rmse: 0.3462 - val_smape: 0.6578

Epoch 18/32

2292/2292 - 85s - 37ms/step - ia: 0.8835 - loss: 0.0599 - mae: 0.1784 - rmse: 0.2362 - smape: 0.4609 - val_ia: 0.3294 - val_loss: 0.2282 - val_mae: 0.3654 - val_rmse: 0.4092 - val_smape: 0.7276

Epoch 19/32

2292/2292 - 60s - 26ms/step - ia: 0.8845 - loss: 0.0591 - mae: 0.1773 - rmse: 0.2352 - smape: 0.4591 - val_ia: 0.3626 - val_loss: 0.1520 - val_mae: 0.3069 - val_rmse: 0.3439 - val_smape: 0.6624

Epoch 20/32

2292/2292 - 71s - 31ms/step - ia: 0.8856 - loss: 0.0578 - mae: 0.1748 - rmse: 0.2322 - smape: 0.4545 - val_ia: 0.3401 - val_loss: 0.1969 - val_mae: 0.3439 - val_rmse: 0.3857 - val_smape: 0.7091

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 12:57 5s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step

 54%|█████▍    | 27/50 [6:33:54<13:13:50, 2070.90s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 110s - 24ms/step - ia: 0.2424 - loss: 0.9847 - mae: 0.8238 - rmse: 0.9717 - smape: 1.6299 - val_ia: 0.1552 - val_loss: 0.7183 - val_mae: 0.6961 - val_rmse: 0.7146 - val_smape: 1.3810

Epoch 2/32

4584/4584 - 80s - 17ms/step - ia: 0.5345 - loss: 0.5183 - mae: 0.5784 - rmse: 0.6954 - smape: 1.0130 - val_ia: 0.1466 - val_loss: 0.7231 - val_mae: 0.7240 - val_rmse: 0.7423 - val_smape: 1.2181

Epoch 3/32

4584/4584 - 81s - 18ms/step - ia: 0.6441 - loss: 0.3761 - mae: 0.4884 - rmse: 0.5946 - smape: 0.8336 - val_ia: 0.1568 - val_loss: 0.6961 - val_mae: 0.7001 - val_rmse: 0.7186 - val_smape: 1.1626

Epoch 4/32

4584/4584 - 88s - 19ms/step - ia: 0.6631 - loss: 0.3423 - mae: 0.4643 - rmse: 0.5668 - smape: 0.8090 - val_ia: 0.1743 - val_loss: 0.5796 - val_mae: 0.6300 - val_rmse: 0.6492 - val_smape: 1.0684

Epoch 5/32

4584/4584 - 84s - 18ms/step - ia: 0.6719 - loss: 0.3254 - mae: 0.4520 - rmse: 0.5526 - smape: 0.7964 - val_ia: 0.1782 - val_loss: 0.5613 - val_mae: 0.6157 - val_rmse: 0.6352 - val_smape: 1.0437

Epoch 6/32

4584/4584 - 79s - 17ms/step - ia: 0.6807 - loss: 0.3111 - mae: 0.4419 - rmse: 0.5405 - smape: 0.7878 - val_ia: 0.1724 - val_loss: 0.5414 - val_mae: 0.6044 - val_rmse: 0.6236 - val_smape: 1.0225

Epoch 7/32

4584/4584 - 85s - 19ms/step - ia: 0.6864 - loss: 0.2961 - mae: 0.4323 - rmse: 0.5272 - smape: 0.7828 - val_ia: 0.1727 - val_loss: 0.4947 - val_mae: 0.5767 - val_rmse: 0.5952 - val_smape: 0.9972

Epoch 8/32

4584/4584 - 80s - 18ms/step - ia: 0.6989 - loss: 0.2800 - mae: 0.4183 - rmse: 0.5115 - smape: 0.7729 - val_ia: 0.1696 - val_loss: 0.4654 - val_mae: 0.5572 - val_rmse: 0.5743 - val_smape: 0.9741

Epoch 9/32

4584/4584 - 85s - 19ms/step - ia: 0.7118 - loss: 0.2582 - mae: 0.4006 - rmse: 0.4908 - smape: 0.7668 - val_ia: 0.1718 - val_loss: 0.4538 - val_mae: 0.5441 - val_rmse: 0.5597 - val_smape: 0.9557

Epoch 10/32

4584/4584 - 78s - 17ms/step - ia: 0.7251 - loss: 0.2373 - mae: 0.3812 - rmse: 0.4697 - smape: 0.7555 - val_ia: 0.1752 - val_loss: 0.4287 - val_mae: 0.5215 - val_rmse: 0.5366 - val_smape: 0.9406

Epoch 11/32

4584/4584 - 83s - 18ms/step - ia: 0.7374 - loss: 0.2202 - mae: 0.3653 - rmse: 0.4509 - smape: 0.7469 - val_ia: 0.1872 - val_loss: 0.3971 - val_mae: 0.4932 - val_rmse: 0.5091 - val_smape: 0.9111

Epoch 12/32

4584/4584 - 75s - 16ms/step - ia: 0.7480 - loss: 0.2031 - mae: 0.3481 - rmse: 0.4327 - smape: 0.7316 - val_ia: 0.1921 - val_loss: 0.4116 - val_mae: 0.4947 - val_rmse: 0.5114 - val_smape: 0.8986

Epoch 13/32

4584/4584 - 78s - 17ms/step - ia: 0.7543 - loss: 0.1934 - mae: 0.3384 - rmse: 0.4216 - smape: 0.7231 - val_ia: 0.1970 - val_loss: 0.3762 - val_mae: 0.4752 - val_rmse: 0.4916 - val_smape: 0.8807

Epoch 14/32

4584/4584 - 81s - 18ms/step - ia: 0.7617 - loss: 0.1836 - mae: 0.3296 - rmse: 0.4106 - smape: 0.7122 - val_ia: 0.1981 - val_loss: 0.3570 - val_mae: 0.4644 - val_rmse: 0.4814 - val_smape: 0.8718

Epoch 15/32

4584/4584 - 74s - 16ms/step - ia: 0.7649 - loss: 0.1782 - mae: 0.3239 - rmse: 0.4047 - smape: 0.7036 - val_ia: 0.2015 - val_loss: 0.3298 - val_mae: 0.4497 - val_rmse: 0.4665 - val_smape: 0.8559

Epoch 16/32

4584/4584 - 72s - 16ms/step - ia: 0.7679 - loss: 0.1741 - mae: 0.3197 - rmse: 0.3998 - smape: 0.6996 - val_ia: 0.2028 - val_loss: 0.3132 - val_mae: 0.4405 - val_rmse: 0.4577 - val_smape: 0.8460

Epoch 17/32

4584/4584 - 87s - 19ms/step - ia: 0.7704 - loss: 0.1699 - mae: 0.3162 - rmse: 0.3950 - smape: 0.6935 - val_ia: 0.2085 - val_loss: 0.2757 - val_mae: 0.4180 - val_rmse: 0.4347 - val_smape: 0.8294

Epoch 18/32

4584/4584 - 84s - 18ms/step - ia: 0.7710 - loss: 0.1683 - mae: 0.3141 - rmse: 0.3932 - smape: 0.6906 - val_ia: 0.2100 - val_loss: 0.2599 - val_mae: 0.4085 - val_rmse: 0.4254 - val_smape: 0.8242

Epoch 19/32

4584/4584 - 78s - 17ms/step - ia: 0.7754 - loss: 0.1654 - mae: 0.3105 - rmse: 0.3895 - smape: 0.6820 - val_ia: 0.2135 - val_loss: 0.2506 - val_mae: 0.4012 - val_rmse: 0.4181 - val_smape: 0.8123

Epoch 20/32

4584/4584 - 76s - 17ms/step - ia: 0.7748 - loss: 0.1640 - mae: 0.3103 - rmse: 0.3880 - smape: 0.6833 - val_ia: 0.2143 - val_loss: 0.2498 - val_mae: 0.4002 - val_rmse: 0.4168 - val_smape: 0.8077

Epoch 21/32

4584/4584 - 76s - 17ms/step - ia: 0.7798 - loss: 0.1617 - mae: 0.3074 - rmse: 0.3850 - smape: 0.6780 - val_ia: 0.2169 - val_loss: 0.2369 - val_mae: 0.3915 - val_rmse: 0.4082 - val_smape: 0.8000

Epoch 22/32

4584/4584 - 67s - 15ms/step - ia: 0.7794 - loss: 0.1602 - mae: 0.3055 - rmse: 0.3826 - smape: 0.6765 - val_ia: 0.2172 - val_loss: 0.2463 - val_mae: 0.3962 - val_rmse: 0.4136 - val_smape: 0.8022

Epoch 23/32

4584/4584 - 67s - 15ms/step - ia: 0.7804 - loss: 0.1578 - mae: 0.3042 - rmse: 0.3802 - smape: 0.6772 - val_ia: 0.2192 - val_loss: 0.2310 - val_mae: 0.3859 - val_rmse: 0.4032 - val_smape: 0.7971

Epoch 24/32

4584/4584 - 72s - 16ms/step - ia: 0.7811 - loss: 0.1564 - mae: 0.3023 - rmse: 0.3788 - smape: 0.6728 - val_ia: 0.2212 - val_loss: 0.2195 - val_mae: 0.3779 - val_rmse: 0.3952 - val_smape: 0.7879

Epoch 25/32

4584/4584 - 77s - 17ms/step - ia: 0.7821 - loss: 0.1562 - mae: 0.3017 - rmse: 0.3785 - smape: 0.6719 - val_ia: 0.2213 - val_loss: 0.2235 - val_mae: 0.3803 - val_rmse: 0.3975 - val_smape: 0.7843

Epoch 26/32

4584/4584 - 75s - 16ms/step - ia: 0.7834 - loss: 0.1528 - mae: 0.2984 - rmse: 0.3737 - smape: 0.6682 - val_ia: 0.2283 - val_loss: 0.2077 - val_mae: 0.3678 - val_rmse: 0.3847 - val_smape: 0.7772

Epoch 27/32

4584/4584 - 76s - 17ms/step - ia: 0.7840 - loss: 0.1527 - mae: 0.2984 - rmse: 0.3738 - smape: 0.6657 - val_ia: 0.2253 - val_loss: 0.2285 - val_mae: 0.3813 - val_rmse: 0.3988 - val_smape: 0.7800

Epoch 28/32

4584/4584 - 72s - 16ms/step - ia: 0.7860 - loss: 0.1517 - mae: 0.2971 - rmse: 0.3722 - smape: 0.6658 - val_ia: 0.2277 - val_loss: 0.2117 - val_mae: 0.3698 - val_rmse: 0.3871 - val_smape: 0.7740

Epoch 29/32

4584/4584 - 73s - 16ms/step - ia: 0.7873 - loss: 0.1500 - mae: 0.2958 - rmse: 0.3708 - smape: 0.6644 - val_ia: 0.2266 - val_loss: 0.2075 - val_mae: 0.3669 - val_rmse: 0.3844 - val_smape: 0.7742

Epoch 30/32

4584/4584 - 59s - 13ms/step - ia: 0.7881 - loss: 0.1492 - mae: 0.2943 - rmse: 0.3699 - smape: 0.6604 - val_ia: 0.2297 - val_loss: 0.2127 - val_mae: 0.3693 - val_rmse: 0.3866 - val_smape: 0.7698

Epoch 31/32

4584/4584 - 65s - 14ms/step - ia: 0.7879 - loss: 0.1484 - mae: 0.2937 - rmse: 0.3683 - smape: 0.6630 - val_ia: 0.2289 - val_loss: 0.2052 - val_mae: 0.3651 - val_rmse: 0.3824 - val_smape: 0.7735

Epoch 32/32

4584/4584 - 74s - 16ms/step - ia: 0.7879 - loss: 0.1482 - mae: 0.2939 - rmse: 0.3684 - smape: 0.6620 - val_ia: 0.2273 - val_loss: 0.2162 - val_mae: 0.3722 - val_rmse: 0.3897 - val_smape: 0.7758

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:07 2s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 56%|█████▌    | 28/50 [7:15:29<13:26:00, 2198.22s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 100s - 44ms/step - ia: 0.3445 - loss: 1.9166 - mae: 1.1235 - rmse: 1.3577 - smape: 1.3363 - val_ia: 0.1885 - val_loss: 0.9755 - val_mae: 0.7887 - val_rmse: 0.8282 - val_smape: 1.2207

Epoch 2/32

2292/2292 - 78s - 34ms/step - ia: 0.2152 - loss: 1.0961 - mae: 0.8691 - rmse: 1.0339 - smape: 1.5165 - val_ia: 0.1896 - val_loss: 0.8347 - val_mae: 0.7563 - val_rmse: 0.7944 - val_smape: 1.6100

Epoch 3/32

2292/2292 - 51s - 22ms/step - ia: 0.1669 - loss: 0.9992 - mae: 0.8304 - rmse: 0.9907 - smape: 1.8257 - val_ia: 0.1814 - val_loss: 0.8525 - val_mae: 0.7682 - val_rmse: 0.8050 - val_smape: 1.9269

Epoch 4/32

2292/2292 - 52s - 23ms/step - ia: 0.1684 - loss: 0.9917 - mae: 0.8270 - rmse: 0.9866 - smape: 1.9356 - val_ia: 0.1805 - val_loss: 0.8487 - val_mae: 0.7666 - val_rmse: 0.8034 - val_smape: 1.9193

Epoch 5/32

2292/2292 - 52s - 23ms/step - ia: 0.1657 - loss: 0.9816 - mae: 0.8233 - rmse: 0.9809 - smape: 1.8935 - val_ia: 0.1805 - val_loss: 0.8357 - val_mae: 0.7603 - val_rmse: 0.7973 - val_smape: 1.8511

Epoch 6/32

2292/2292 - 77s - 34ms/step - ia: 0.1762 - loss: 0.9629 - mae: 0.8167 - rmse: 0.9722 - smape: 1.8275 - val_ia: 0.1796 - val_loss: 0.8164 - val_mae: 0.7508 - val_rmse: 0.7878 - val_smape: 1.7487

Epoch 7/32

2292/2292 - 49s - 21ms/step - ia: 0.1929 - loss: 0.9302 - mae: 0.8043 - rmse: 0.9557 - smape: 1.7308 - val_ia: 0.1800 - val_loss: 0.7806 - val_mae: 0.7323 - val_rmse: 0.7697 - val_smape: 1.6159

Epoch 8/32

2292/2292 - 45s - 19ms/step - ia: 0.2285 - loss: 0.8756 - mae: 0.7823 - rmse: 0.9269 - smape: 1.6043 - val_ia: 0.1835 - val_loss: 0.7309 - val_mae: 0.7042 - val_rmse: 0.7422 - val_smape: 1.4612

Epoch 9/32

2292/2292 - 44s - 19ms/step - ia: 0.2960 - loss: 0.7922 - mae: 0.7430 - rmse: 0.8808 - smape: 1.4492 - val_ia: 0.2035 - val_loss: 0.6803 - val_mae: 0.6705 - val_rmse: 0.7086 - val_smape: 1.3134

Epoch 10/32

2292/2292 - 45s - 20ms/step - ia: 0.3902 - loss: 0.6768 - mae: 0.6770 - rmse: 0.8128 - smape: 1.2774 - val_ia: 0.2213 - val_loss: 0.6521 - val_mae: 0.6487 - val_rmse: 0.6867 - val_smape: 1.2133

Epoch 11/32

2292/2292 - 82s - 36ms/step - ia: 0.5062 - loss: 0.5392 - mae: 0.5901 - rmse: 0.7235 - smape: 1.0748 - val_ia: 0.2204 - val_loss: 0.6846 - val_mae: 0.6641 - val_rmse: 0.7016 - val_smape: 1.1634

Epoch 12/32

2292/2292 - 81s - 35ms/step - ia: 0.5958 - loss: 0.4409 - mae: 0.5260 - rmse: 0.6535 - smape: 0.9239 - val_ia: 0.2153 - val_loss: 0.7469 - val_mae: 0.6974 - val_rmse: 0.7346 - val_smape: 1.1532

Epoch 13/32

2292/2292 - 48s - 21ms/step - ia: 0.6399 - loss: 0.3971 - mae: 0.4972 - rmse: 0.6202 - smape: 0.8562 - val_ia: 0.2096 - val_loss: 0.7894 - val_mae: 0.7176 - val_rmse: 0.7543 - val_smape: 1.1433

Epoch 14/32

2292/2292 - 51s - 22ms/step - ia: 0.6604 - loss: 0.3746 - mae: 0.4816 - rmse: 0.6023 - smape: 0.8244 - val_ia: 0.2116 - val_loss: 0.7892 - val_mae: 0.7138 - val_rmse: 0.7505 - val_smape: 1.1243

Epoch 15/32

2292/2292 - 52s - 23ms/step - ia: 0.6736 - loss: 0.3596 - mae: 0.4702 - rmse: 0.5894 - smape: 0.8069 - val_ia: 0.2196 - val_loss: 0.7850 - val_mae: 0.7078 - val_rmse: 0.7450 - val_smape: 1.1073

Epoch 16/32

2292/2292 - 50s - 22ms/step - ia: 0.6823 - loss: 0.3485 - mae: 0.4610 - rmse: 0.5798 - smape: 0.7948 - val_ia: 0.2247 - val_loss: 0.7869 - val_mae: 0.7062 - val_rmse: 0.7437 - val_smape: 1.0971

Epoch 17/32

2292/2292 - 50s - 22ms/step - ia: 0.6879 - loss: 0.3399 - mae: 0.4543 - rmse: 0.5728 - smape: 0.7853 - val_ia: 0.2314 - val_loss: 0.7667 - val_mae: 0.6931 - val_rmse: 0.7313 - val_smape: 1.0789

Epoch 18/32

2292/2292 - 49s - 21ms/step - ia: 0.6926 - loss: 0.3331 - mae: 0.4487 - rmse: 0.5667 - smape: 0.7787 - val_ia: 0.2327 - val_loss: 0.7693 - val_mae: 0.6938 - val_rmse: 0.7321 - val_smape: 1.0759

Epoch 19/32

2292/2292 - 42s - 18ms/step - ia: 0.6969 - loss: 0.3275 - mae: 0.4442 - rmse: 0.5615 - smape: 0.7737 - val_ia: 0.2335 - val_loss: 0.7610 - val_mae: 0.6892 - val_rmse: 0.7276 - val_smape: 1.0696

Epoch 20/32

2292/2292 - 47s - 21ms/step - ia: 0.6997 - loss: 0.3227 - mae: 0.4404 - rmse: 0.5574 - smape: 0.7687 - val_ia: 0.2329 - val_loss: 0.7578 - val_mae: 0.6874 - val_rmse: 0.7257 - val_smape: 1.0672

Epoch 21/32

2292/2292 - 47s - 21ms/step - ia: 0.7015 - loss: 0.3184 - mae: 0.4371 - rmse: 0.5539 - smape: 0.7652 - val_ia: 0.2315 - val_loss: 0.7510 - val_mae: 0.6843 - val_rmse: 0.7225 - val_smape: 1.0662

Epoch 22/32

2292/2292 - 47s - 21ms/step - ia: 0.7046 - loss: 0.3146 - mae: 0.4345 - rmse: 0.5503 - smape: 0.7639 - val_ia: 0.2301 - val_loss: 0.7517 - val_mae: 0.6854 - val_rmse: 0.7236 - val_smape: 1.0679

Epoch 23/32

2292/2292 - 48s - 21ms/step - ia: 0.7059 - loss: 0.3111 - mae: 0.4318 - rmse: 0.5476 - smape: 0.7603 - val_ia: 0.2288 - val_loss: 0.7443 - val_mae: 0.6821 - val_rmse: 0.7205 - val_smape: 1.0666

Epoch 24/32

2292/2292 - 48s - 21ms/step - ia: 0.7078 - loss: 0.3079 - mae: 0.4295 - rmse: 0.5450 - smape: 0.7587 - val_ia: 0.2275 - val_loss: 0.7415 - val_mae: 0.6812 - val_rmse: 0.7196 - val_smape: 1.0669

Epoch 25/32

2292/2292 - 46s - 20ms/step - ia: 0.7103 - loss: 0.3049 - mae: 0.4275 - rmse: 0.5421 - smape: 0.7568 - val_ia: 0.2260 - val_loss: 0.7294 - val_mae: 0.6761 - val_rmse: 0.7146 - val_smape: 1.0654

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:44 2s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step

 58%|█████▊    | 29/50 [7:38:38<11:24:21, 1955.29s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4584/4584 - 131s - 29ms/step - ia: 0.4724 - loss: 0.6787 - mae: 0.6513 - rmse: 0.7797 - smape: 1.1472 - val_ia: 0.1373 - val_loss: 1.1149 - val_mae: 0.8793 - val_rmse: 0.8962 - val_smape: 1.3024

Epoch 2/64

4584/4584 - 137s - 30ms/step - ia: 0.6730 - loss: 0.3323 - mae: 0.4508 - rmse: 0.5565 - smape: 0.7948 - val_ia: 0.1713 - val_loss: 0.7413 - val_mae: 0.6921 - val_rmse: 0.7117 - val_smape: 1.1364

Epoch 3/64

4584/4584 - 118s - 26ms/step - ia: 0.6986 - loss: 0.2869 - mae: 0.4188 - rmse: 0.5173 - smape: 0.7683 - val_ia: 0.1718 - val_loss: 0.5658 - val_mae: 0.6012 - val_rmse: 0.6212 - val_smape: 1.0641

Epoch 4/64

4584/4584 - 104s - 23ms/step - ia: 0.7109 - loss: 0.2618 - mae: 0.4019 - rmse: 0.4950 - smape: 0.7547 - val_ia: 0.1790 - val_loss: 0.5081 - val_mae: 0.5631 - val_rmse: 0.5838 - val_smape: 1.0071

Epoch 5/64

4584/4584 - 101s - 22ms/step - ia: 0.7258 - loss: 0.2380 - mae: 0.3819 - rmse: 0.4712 - smape: 0.7388 - val_ia: 0.1869 - val_loss: 0.3825 - val_mae: 0.4952 - val_rmse: 0.5131 - val_smape: 0.9618

Epoch 6/64

4584/4584 - 109s - 24ms/step - ia: 0.7521 - loss: 0.1974 - mae: 0.3433 - rmse: 0.4267 - smape: 0.7162 - val_ia: 0.2102 - val_loss: 0.2197 - val_mae: 0.3890 - val_rmse: 0.4045 - val_smape: 0.8179

Epoch 7/64

4584/4584 - 108s - 24ms/step - ia: 0.7725 - loss: 0.1677 - mae: 0.3147 - rmse: 0.3933 - smape: 0.6919 - val_ia: 0.2130 - val_loss: 0.2289 - val_mae: 0.3920 - val_rmse: 0.4070 - val_smape: 0.8107

Epoch 8/64

4584/4584 - 145s - 32ms/step - ia: 0.7831 - loss: 0.1531 - mae: 0.2992 - rmse: 0.3747 - smape: 0.6752 - val_ia: 0.2304 - val_loss: 0.1866 - val_mae: 0.3558 - val_rmse: 0.3708 - val_smape: 0.7951

Epoch 9/64

4584/4584 - 106s - 23ms/step - ia: 0.7906 - loss: 0.1442 - mae: 0.2907 - rmse: 0.3639 - smape: 0.6658 - val_ia: 0.2523 - val_loss: 0.1567 - val_mae: 0.3250 - val_rmse: 0.3410 - val_smape: 0.7517

Epoch 10/64

4584/4584 - 146s - 32ms/step - ia: 0.7989 - loss: 0.1344 - mae: 0.2801 - rmse: 0.3512 - smape: 0.6495 - val_ia: 0.2491 - val_loss: 0.1700 - val_mae: 0.3379 - val_rmse: 0.3533 - val_smape: 0.7647

Epoch 11/64

4584/4584 - 124s - 27ms/step - ia: 0.8068 - loss: 0.1251 - mae: 0.2702 - rmse: 0.3385 - smape: 0.6390 - val_ia: 0.2579 - val_loss: 0.1689 - val_mae: 0.3305 - val_rmse: 0.3474 - val_smape: 0.7377

Epoch 12/64

4584/4584 - 102s - 22ms/step - ia: 0.8122 - loss: 0.1190 - mae: 0.2631 - rmse: 0.3297 - smape: 0.6290 - val_ia: 0.2505 - val_loss: 0.1818 - val_mae: 0.3414 - val_rmse: 0.3590 - val_smape: 0.7328

Epoch 13/64

4584/4584 - 104s - 23ms/step - ia: 0.8182 - loss: 0.1126 - mae: 0.2560 - rmse: 0.3205 - smape: 0.6196 - val_ia: 0.2596 - val_loss: 0.1767 - val_mae: 0.3347 - val_rmse: 0.3523 - val_smape: 0.6992

Epoch 14/64

4584/4584 - 136s - 30ms/step - ia: 0.8222 - loss: 0.1082 - mae: 0.2499 - rmse: 0.3137 - smape: 0.6042 - val_ia: 0.2585 - val_loss: 0.1697 - val_mae: 0.3296 - val_rmse: 0.3476 - val_smape: 0.7090

Epoch 15/64

4584/4584 - 98s - 21ms/step - ia: 0.8237 - loss: 0.1055 - mae: 0.2473 - rmse: 0.3100 - smape: 0.5986 - val_ia: 0.2573 - val_loss: 0.1795 - val_mae: 0.3386 - val_rmse: 0.3561 - val_smape: 0.7030

Epoch 16/64

4584/4584 - 112s - 25ms/step - ia: 0.8267 - loss: 0.1026 - mae: 0.2439 - rmse: 0.3056 - smape: 0.5911 - val_ia: 0.2621 - val_loss: 0.1728 - val_mae: 0.3347 - val_rmse: 0.3509 - val_smape: 0.6898

Epoch 17/64

4584/4584 - 109s - 24ms/step - ia: 0.8294 - loss: 0.0997 - mae: 0.2406 - rmse: 0.3015 - smape: 0.5838 - val_ia: 0.2593 - val_loss: 0.1711 - val_mae: 0.3321 - val_rmse: 0.3492 - val_smape: 0.6961

Epoch 18/64

4584/4584 - 111s - 24ms/step - ia: 0.8300 - loss: 0.0979 - mae: 0.2390 - rmse: 0.2986 - smape: 0.5796 - val_ia: 0.2474 - val_loss: 0.2025 - val_mae: 0.3624 - val_rmse: 0.3793 - val_smape: 0.7211

Epoch 19/64

4584/4584 - 97s - 21ms/step - ia: 0.8322 - loss: 0.0959 - mae: 0.2359 - rmse: 0.2954 - smape: 0.5718 - val_ia: 0.2540 - val_loss: 0.1839 - val_mae: 0.3427 - val_rmse: 0.3604 - val_smape: 0.7018

Epoch 20/64

4584/4584 - 101s - 22ms/step - ia: 0.8339 - loss: 0.0947 - mae: 0.2343 - rmse: 0.2934 - smape: 0.5663 - val_ia: 0.2580 - val_loss: 0.1747 - val_mae: 0.3316 - val_rmse: 0.3496 - val_smape: 0.6986

Epoch 21/64

4584/4584 - 108s - 23ms/step - ia: 0.8350 - loss: 0.0934 - mae: 0.2327 - rmse: 0.2912 - smape: 0.5642 - val_ia: 0.2533 - val_loss: 0.1839 - val_mae: 0.3433 - val_rmse: 0.3603 - val_smape: 0.7046

Epoch 22/64

4584/4584 - 110s - 24ms/step - ia: 0.8384 - loss: 0.0908 - mae: 0.2293 - rmse: 0.2874 - smape: 0.5556 - val_ia: 0.2557 - val_loss: 0.1866 - val_mae: 0.3454 - val_rmse: 0.3624 - val_smape: 0.7059

Epoch 23/64

4584/4584 - 110s - 24ms/step - ia: 0.8380 - loss: 0.0903 - mae: 0.2284 - rmse: 0.2865 - smape: 0.5518 - val_ia: 0.2513 - val_loss: 0.1906 - val_mae: 0.3503 - val_rmse: 0.3677 - val_smape: 0.7060

Epoch 24/64

4584/4584 - 111s - 24ms/step - ia: 0.8399 - loss: 0.0889 - mae: 0.2269 - rmse: 0.2842 - smape: 0.5462 - val_ia: 0.2673 - val_loss: 0.1503 - val_mae: 0.3111 - val_rmse: 0.3272 - val_smape: 0.6674

Epoch 25/64

4584/4584 - 101s - 22ms/step - ia: 0.8408 - loss: 0.0877 - mae: 0.2250 - rmse: 0.2818 - smape: 0.5429 - val_ia: 0.2496 - val_loss: 0.1962 - val_mae: 0.3541 - val_rmse: 0.3717 - val_smape: 0.7144

Epoch 26/64

4584/4584 - 102s - 22ms/step - ia: 0.8411 - loss: 0.0876 - mae: 0.2246 - rmse: 0.2815 - smape: 0.5385 - val_ia: 0.2643 - val_loss: 0.1730 - val_mae: 0.3288 - val_rmse: 0.3464 - val_smape: 0.6861

Epoch 27/64

4584/4584 - 100s - 22ms/step - ia: 0.8425 - loss: 0.0864 - mae: 0.2232 - rmse: 0.2802 - smape: 0.5360 - val_ia: 0.2724 - val_loss: 0.1617 - val_mae: 0.3178 - val_rmse: 0.3348 - val_smape: 0.6706

Epoch 28/64

4584/4584 - 101s - 22ms/step - ia: 0.8435 - loss: 0.0856 - mae: 0.2222 - rmse: 0.2788 - smape: 0.5339 - val_ia: 0.2611 - val_loss: 0.1800 - val_mae: 0.3348 - val_rmse: 0.3526 - val_smape: 0.6929

Epoch 29/64

4584/4584 - 110s - 24ms/step - ia: 0.8437 - loss: 0.0851 - mae: 0.2219 - rmse: 0.2781 - smape: 0.5327 - val_ia: 0.2572 - val_loss: 0.1938 - val_mae: 0.3473 - val_rmse: 0.3654 - val_smape: 0.7036

Epoch 30/64

4584/4584 - 112s - 24ms/step - ia: 0.8441 - loss: 0.0844 - mae: 0.2206 - rmse: 0.2764 - smape: 0.5282 - val_ia: 0.2703 - val_loss: 0.1657 - val_mae: 0.3232 - val_rmse: 0.3401 - val_smape: 0.6722

Epoch 31/64

4584/4584 - 100s - 22ms/step - ia: 0.8453 - loss: 0.0829 - mae: 0.2185 - rmse: 0.2744 - smape: 0.5255 - val_ia: 0.2664 - val_loss: 0.1710 - val_mae: 0.3286 - val_rmse: 0.3457 - val_smape: 0.6796

Epoch 32/64

4584/4584 - 97s - 21ms/step - ia: 0.8468 - loss: 0.0821 - mae: 0.2175 - rmse: 0.2730 - smape: 0.5206 - val_ia: 0.2632 - val_loss: 0.1942 - val_mae: 0.3456 - val_rmse: 0.3639 - val_smape: 0.6945

Epoch 33/64

4584/4584 - 110s - 24ms/step - ia: 0.8463 - loss: 0.0818 - mae: 0.2168 - rmse: 0.2719 - smape: 0.5218 - val_ia: 0.2476 - val_loss: 0.2111 - val_mae: 0.3645 - val_rmse: 0.3821 - val_smape: 0.7250

Epoch 34/64

4584/4584 - 104s - 23ms/step - ia: 0.8475 - loss: 0.0807 - mae: 0.2161 - rmse: 0.2705 - smape: 0.5213 - val_ia: 0.2724 - val_loss: 0.1756 - val_mae: 0.3291 - val_rmse: 0.3467 - val_smape: 0.6814

Epoch 35/64

4584/4584 - 103s - 22ms/step - ia: 0.8478 - loss: 0.0810 - mae: 0.2157 - rmse: 0.2705 - smape: 0.5172 - val_ia: 0.2694 - val_loss: 0.1669 - val_mae: 0.3235 - val_rmse: 0.3410 - val_smape: 0.6733

Epoch 36/64

4584/4584 - 96s - 21ms/step - ia: 0.8500 - loss: 0.0791 - mae: 0.2131 - rmse: 0.2675 - smape: 0.5124 - val_ia: 0.2715 - val_loss: 0.1806 - val_mae: 0.3329 - val_rmse: 0.3513 - val_smape: 0.6783

Epoch 37/64

4584/4584 - 108s - 24ms/step - ia: 0.8504 - loss: 0.0793 - mae: 0.2136 - rmse: 0.2680 - smape: 0.5119 - val_ia: 0.2664 - val_loss: 0.1666 - val_mae: 0.3235 - val_rmse: 0.3410 - val_smape: 0.6803

Epoch 38/64

4584/4584 - 128s - 28ms/step - ia: 0.8494 - loss: 0.0792 - mae: 0.2131 - rmse: 0.2675 - smape: 0.5121 - val_ia: 0.2644 - val_loss: 0.1853 - val_mae: 0.3380 - val_rmse: 0.3555 - val_smape: 0.7010

Epoch 39/64

4584/4584 - 96s - 21ms/step - ia: 0.8518 - loss: 0.0779 - mae: 0.2115 - rmse: 0.2657 - smape: 0.5103 - val_ia: 0.2638 - val_loss: 0.1791 - val_mae: 0.3337 - val_rmse: 0.3516 - val_smape: 0.6915

Epoch 39: early stopping

Restoring model weights from the end of the best epoch: 24.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 6:46 3s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step

 60%|██████    | 30/50 [8:50:34<14:47:53, 2663.69s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2292/2292 - 97s - 42ms/step - ia: 0.8138 - loss: 0.1428 - mae: 0.2764 - rmse: 0.3583 - smape: 0.6258 - val_ia: 0.2830 - val_loss: 0.2848 - val_mae: 0.4190 - val_rmse: 0.4564 - val_smape: 0.8257

Epoch 2/256

2292/2292 - 50s - 22ms/step - ia: 0.8655 - loss: 0.0803 - mae: 0.2047 - rmse: 0.2723 - smape: 0.5019 - val_ia: 0.3483 - val_loss: 0.2056 - val_mae: 0.3501 - val_rmse: 0.3824 - val_smape: 0.7335

Epoch 3/256

2292/2292 - 46s - 20ms/step - ia: 0.8794 - loss: 0.0653 - mae: 0.1851 - rmse: 0.2455 - smape: 0.4631 - val_ia: 0.3504 - val_loss: 0.1943 - val_mae: 0.3405 - val_rmse: 0.3740 - val_smape: 0.7172

Epoch 4/256

2292/2292 - 41s - 18ms/step - ia: 0.8848 - loss: 0.0595 - mae: 0.1762 - rmse: 0.2342 - smape: 0.4491 - val_ia: 0.3738 - val_loss: 0.1698 - val_mae: 0.3123 - val_rmse: 0.3449 - val_smape: 0.6974

Epoch 5/256

2292/2292 - 41s - 18ms/step - ia: 0.8918 - loss: 0.0531 - mae: 0.1660 - rmse: 0.2211 - smape: 0.4305 - val_ia: 0.3728 - val_loss: 0.1631 - val_mae: 0.3089 - val_rmse: 0.3436 - val_smape: 0.6789

Epoch 6/256

2292/2292 - 41s - 18ms/step - ia: 0.8945 - loss: 0.0514 - mae: 0.1620 - rmse: 0.2171 - smape: 0.4241 - val_ia: 0.3794 - val_loss: 0.1712 - val_mae: 0.3065 - val_rmse: 0.3356 - val_smape: 0.6795

Epoch 7/256

2292/2292 - 38s - 16ms/step - ia: 0.8990 - loss: 0.0467 - mae: 0.1550 - rmse: 0.2071 - smape: 0.4072 - val_ia: 0.3558 - val_loss: 0.1984 - val_mae: 0.3448 - val_rmse: 0.3746 - val_smape: 0.7235

Epoch 8/256

2292/2292 - 36s - 16ms/step - ia: 0.9023 - loss: 0.0439 - mae: 0.1500 - rmse: 0.2006 - smape: 0.4009 - val_ia: 0.3621 - val_loss: 0.1794 - val_mae: 0.3209 - val_rmse: 0.3605 - val_smape: 0.6950

Epoch 9/256

2292/2292 - 40s - 18ms/step - ia: 0.9039 - loss: 0.0425 - mae: 0.1477 - rmse: 0.1975 - smape: 0.3971 - val_ia: 0.3473 - val_loss: 0.1994 - val_mae: 0.3418 - val_rmse: 0.3788 - val_smape: 0.7288

Epoch 10/256

2292/2292 - 41s - 18ms/step - ia: 0.9078 - loss: 0.0391 - mae: 0.1417 - rmse: 0.1892 - smape: 0.3856 - val_ia: 0.3516 - val_loss: 0.2045 - val_mae: 0.3434 - val_rmse: 0.3872 - val_smape: 0.7350

Epoch 11/256

2292/2292 - 40s - 18ms/step - ia: 0.9089 - loss: 0.0381 - mae: 0.1401 - rmse: 0.1871 - smape: 0.3804 - val_ia: 0.3463 - val_loss: 0.2238 - val_mae: 0.3651 - val_rmse: 0.4015 - val_smape: 0.7789

Epoch 12/256

2292/2292 - 40s - 18ms/step - ia: 0.9106 - loss: 0.0369 - mae: 0.1375 - rmse: 0.1839 - smape: 0.3760 - val_ia: 0.3787 - val_loss: 0.1992 - val_mae: 0.3311 - val_rmse: 0.3639 - val_smape: 0.6880

Epoch 13/256

2292/2292 - 40s - 18ms/step - ia: 0.9121 - loss: 0.0359 - mae: 0.1355 - rmse: 0.1811 - smape: 0.3717 - val_ia: 0.3525 - val_loss: 0.2072 - val_mae: 0.3367 - val_rmse: 0.3918 - val_smape: 0.6929

Epoch 14/256

2292/2292 - 40s - 18ms/step - ia: 0.9144 - loss: 0.0342 - mae: 0.1321 - rmse: 0.1764 - smape: 0.3628 - val_ia: 0.3639 - val_loss: 0.1938 - val_mae: 0.3311 - val_rmse: 0.3703 - val_smape: 0.6974

Epoch 15/256

2292/2292 - 40s - 17ms/step - ia: 0.9141 - loss: 0.0340 - mae: 0.1325 - rmse: 0.1766 - smape: 0.3669 - val_ia: 0.3492 - val_loss: 0.2164 - val_mae: 0.3459 - val_rmse: 0.3937 - val_smape: 0.7186

Epoch 16/256

2292/2292 - 40s - 18ms/step - ia: 0.9159 - loss: 0.0324 - mae: 0.1294 - rmse: 0.1721 - smape: 0.3613 - val_ia: 0.3751 - val_loss: 0.1745 - val_mae: 0.3103 - val_rmse: 0.3492 - val_smape: 0.6768

Epoch 17/256

2292/2292 - 41s - 18ms/step - ia: 0.9162 - loss: 0.0324 - mae: 0.1292 - rmse: 0.1723 - smape: 0.3615 - val_ia: 0.3579 - val_loss: 0.2002 - val_mae: 0.3287 - val_rmse: 0.3808 - val_smape: 0.7098

Epoch 18/256

2292/2292 - 40s - 18ms/step - ia: 0.9160 - loss: 0.0332 - mae: 0.1295 - rmse: 0.1731 - smape: 0.3624 - val_ia: 0.2984 - val_loss: 0.3105 - val_mae: 0.4320 - val_rmse: 0.4831 - val_smape: 0.8628

Epoch 19/256

2292/2292 - 40s - 18ms/step - ia: 0.9174 - loss: 0.0316 - mae: 0.1274 - rmse: 0.1699 - smape: 0.3564 - val_ia: 0.3296 - val_loss: 0.2565 - val_mae: 0.3843 - val_rmse: 0.4373 - val_smape: 0.7178

Epoch 20/256

2292/2292 - 41s - 18ms/step - ia: 0.9200 - loss: 0.0296 - mae: 0.1232 - rmse: 0.1644 - smape: 0.3458 - val_ia: 0.3409 - val_loss: 0.2348 - val_mae: 0.3579 - val_rmse: 0.4017 - val_smape: 0.7355

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:09 2s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

 62%|██████▏   | 31/50 [9:05:12<11:13:52, 2128.03s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 66s - 14ms/step - ia: 0.2706 - loss: 0.9410 - mae: 0.8022 - rmse: 0.9440 - smape: 1.5806 - val_ia: 0.1422 - val_loss: 0.9279 - val_mae: 0.7947 - val_rmse: 0.8110 - val_smape: 1.3128

Epoch 2/32

4584/4584 - 55s - 12ms/step - ia: 0.5712 - loss: 0.4505 - mae: 0.5513 - rmse: 0.6526 - smape: 0.9462 - val_ia: 0.1481 - val_loss: 1.0383 - val_mae: 0.8357 - val_rmse: 0.8547 - val_smape: 1.2218

Epoch 3/32

4584/4584 - 62s - 14ms/step - ia: 0.6631 - loss: 0.3356 - mae: 0.4631 - rmse: 0.5608 - smape: 0.8015 - val_ia: 0.1687 - val_loss: 0.8747 - val_mae: 0.7504 - val_rmse: 0.7720 - val_smape: 1.1419

Epoch 4/32

4584/4584 - 64s - 14ms/step - ia: 0.6913 - loss: 0.2956 - mae: 0.4294 - rmse: 0.5263 - smape: 0.7651 - val_ia: 0.1757 - val_loss: 0.8214 - val_mae: 0.7186 - val_rmse: 0.7430 - val_smape: 1.1087

Epoch 5/32

4584/4584 - 52s - 11ms/step - ia: 0.7077 - loss: 0.2680 - mae: 0.4078 - rmse: 0.5003 - smape: 0.7485 - val_ia: 0.1663 - val_loss: 0.6948 - val_mae: 0.6576 - val_rmse: 0.6832 - val_smape: 1.1022

Epoch 6/32

4584/4584 - 53s - 12ms/step - ia: 0.7221 - loss: 0.2460 - mae: 0.3899 - rmse: 0.4792 - smape: 0.7388 - val_ia: 0.1727 - val_loss: 0.6440 - val_mae: 0.6261 - val_rmse: 0.6508 - val_smape: 1.0675

Epoch 7/32

4584/4584 - 51s - 11ms/step - ia: 0.7351 - loss: 0.2279 - mae: 0.3721 - rmse: 0.4593 - smape: 0.7249 - val_ia: 0.1644 - val_loss: 0.6631 - val_mae: 0.6303 - val_rmse: 0.6532 - val_smape: 1.0766

Epoch 8/32

4584/4584 - 51s - 11ms/step - ia: 0.7470 - loss: 0.2119 - mae: 0.3558 - rmse: 0.4421 - smape: 0.7110 - val_ia: 0.1680 - val_loss: 0.5914 - val_mae: 0.5964 - val_rmse: 0.6167 - val_smape: 1.0507

Epoch 9/32

4584/4584 - 52s - 11ms/step - ia: 0.7590 - loss: 0.1945 - mae: 0.3381 - rmse: 0.4225 - smape: 0.6924 - val_ia: 0.1675 - val_loss: 0.6114 - val_mae: 0.6042 - val_rmse: 0.6227 - val_smape: 1.0087

Epoch 10/32

4584/4584 - 55s - 12ms/step - ia: 0.7742 - loss: 0.1728 - mae: 0.3160 - rmse: 0.3972 - smape: 0.6685 - val_ia: 0.1772 - val_loss: 0.5636 - val_mae: 0.5823 - val_rmse: 0.6005 - val_smape: 0.9506

Epoch 11/32

4584/4584 - 52s - 11ms/step - ia: 0.7916 - loss: 0.1493 - mae: 0.2928 - rmse: 0.3686 - smape: 0.6468 - val_ia: 0.1861 - val_loss: 0.4732 - val_mae: 0.5332 - val_rmse: 0.5522 - val_smape: 0.8961

Epoch 12/32

4584/4584 - 51s - 11ms/step - ia: 0.8079 - loss: 0.1280 - mae: 0.2703 - rmse: 0.3413 - smape: 0.6250 - val_ia: 0.2024 - val_loss: 0.3279 - val_mae: 0.4491 - val_rmse: 0.4672 - val_smape: 0.8254

Epoch 13/32

4584/4584 - 51s - 11ms/step - ia: 0.8201 - loss: 0.1134 - mae: 0.2522 - rmse: 0.3195 - smape: 0.6050 - val_ia: 0.2154 - val_loss: 0.2580 - val_mae: 0.4038 - val_rmse: 0.4210 - val_smape: 0.7911

Epoch 14/32

4584/4584 - 51s - 11ms/step - ia: 0.8286 - loss: 0.1051 - mae: 0.2406 - rmse: 0.3066 - smape: 0.5861 - val_ia: 0.2145 - val_loss: 0.2581 - val_mae: 0.4048 - val_rmse: 0.4218 - val_smape: 0.7883

Epoch 15/32

4584/4584 - 51s - 11ms/step - ia: 0.8327 - loss: 0.1006 - mae: 0.2340 - rmse: 0.2991 - smape: 0.5758 - val_ia: 0.2341 - val_loss: 0.2156 - val_mae: 0.3678 - val_rmse: 0.3846 - val_smape: 0.7599

Epoch 16/32

4584/4584 - 50s - 11ms/step - ia: 0.8360 - loss: 0.0980 - mae: 0.2299 - rmse: 0.2951 - smape: 0.5653 - val_ia: 0.2422 - val_loss: 0.1978 - val_mae: 0.3505 - val_rmse: 0.3694 - val_smape: 0.7505

Epoch 17/32

4584/4584 - 51s - 11ms/step - ia: 0.8375 - loss: 0.0963 - mae: 0.2280 - rmse: 0.2926 - smape: 0.5628 - val_ia: 0.2501 - val_loss: 0.1849 - val_mae: 0.3384 - val_rmse: 0.3555 - val_smape: 0.7296

Epoch 18/32

4584/4584 - 51s - 11ms/step - ia: 0.8401 - loss: 0.0949 - mae: 0.2257 - rmse: 0.2901 - smape: 0.5586 - val_ia: 0.2435 - val_loss: 0.2047 - val_mae: 0.3546 - val_rmse: 0.3715 - val_smape: 0.7468

Epoch 19/32

4584/4584 - 54s - 12ms/step - ia: 0.8397 - loss: 0.0938 - mae: 0.2242 - rmse: 0.2882 - smape: 0.5555 - val_ia: 0.2537 - val_loss: 0.1888 - val_mae: 0.3412 - val_rmse: 0.3579 - val_smape: 0.7314

Epoch 20/32

4584/4584 - 51s - 11ms/step - ia: 0.8410 - loss: 0.0928 - mae: 0.2231 - rmse: 0.2870 - smape: 0.5542 - val_ia: 0.2519 - val_loss: 0.1999 - val_mae: 0.3500 - val_rmse: 0.3669 - val_smape: 0.7363

Epoch 21/32

4584/4584 - 57s - 12ms/step - ia: 0.8418 - loss: 0.0917 - mae: 0.2217 - rmse: 0.2851 - smape: 0.5513 - val_ia: 0.2520 - val_loss: 0.1910 - val_mae: 0.3415 - val_rmse: 0.3581 - val_smape: 0.7327

Epoch 22/32

4584/4584 - 58s - 13ms/step - ia: 0.8424 - loss: 0.0907 - mae: 0.2205 - rmse: 0.2833 - smape: 0.5493 - val_ia: 0.2608 - val_loss: 0.1773 - val_mae: 0.3291 - val_rmse: 0.3457 - val_smape: 0.7196

Epoch 23/32

4584/4584 - 58s - 13ms/step - ia: 0.8434 - loss: 0.0896 - mae: 0.2193 - rmse: 0.2815 - smape: 0.5476 - val_ia: 0.2666 - val_loss: 0.1680 - val_mae: 0.3195 - val_rmse: 0.3361 - val_smape: 0.7048

Epoch 24/32

4584/4584 - 59s - 13ms/step - ia: 0.8439 - loss: 0.0888 - mae: 0.2185 - rmse: 0.2808 - smape: 0.5455 - val_ia: 0.2614 - val_loss: 0.1872 - val_mae: 0.3367 - val_rmse: 0.3532 - val_smape: 0.7225

Epoch 25/32

4584/4584 - 58s - 13ms/step - ia: 0.8455 - loss: 0.0879 - mae: 0.2170 - rmse: 0.2792 - smape: 0.5418 - val_ia: 0.2680 - val_loss: 0.1659 - val_mae: 0.3162 - val_rmse: 0.3330 - val_smape: 0.7020

Epoch 26/32

4584/4584 - 58s - 13ms/step - ia: 0.8463 - loss: 0.0871 - mae: 0.2161 - rmse: 0.2782 - smape: 0.5416 - val_ia: 0.2687 - val_loss: 0.1766 - val_mae: 0.3261 - val_rmse: 0.3428 - val_smape: 0.7125

Epoch 27/32

4584/4584 - 57s - 13ms/step - ia: 0.8463 - loss: 0.0864 - mae: 0.2153 - rmse: 0.2766 - smape: 0.5388 - val_ia: 0.2764 - val_loss: 0.1486 - val_mae: 0.2993 - val_rmse: 0.3161 - val_smape: 0.6818

Epoch 28/32

4584/4584 - 58s - 13ms/step - ia: 0.8471 - loss: 0.0857 - mae: 0.2143 - rmse: 0.2751 - smape: 0.5372 - val_ia: 0.2737 - val_loss: 0.1656 - val_mae: 0.3140 - val_rmse: 0.3310 - val_smape: 0.6934

Epoch 29/32

4584/4584 - 58s - 13ms/step - ia: 0.8482 - loss: 0.0851 - mae: 0.2136 - rmse: 0.2745 - smape: 0.5369 - val_ia: 0.2664 - val_loss: 0.1831 - val_mae: 0.3300 - val_rmse: 0.3469 - val_smape: 0.7101

Epoch 30/32

4584/4584 - 59s - 13ms/step - ia: 0.8488 - loss: 0.0844 - mae: 0.2125 - rmse: 0.2737 - smape: 0.5345 - val_ia: 0.2662 - val_loss: 0.1876 - val_mae: 0.3336 - val_rmse: 0.3506 - val_smape: 0.7134

Epoch 31/32

4584/4584 - 57s - 12ms/step - ia: 0.8497 - loss: 0.0836 - mae: 0.2116 - rmse: 0.2718 - smape: 0.5324 - val_ia: 0.2809 - val_loss: 0.1577 - val_mae: 0.3060 - val_rmse: 0.3227 - val_smape: 0.6835

Epoch 32/32

4584/4584 - 55s - 12ms/step - ia: 0.8495 - loss: 0.0829 - mae: 0.2108 - rmse: 0.2711 - smape: 0.5316 - val_ia: 0.2701 - val_loss: 0.1856 - val_mae: 0.3306 - val_rmse: 0.3476 - val_smape: 0.7096

Restoring model weights from the end of the best epoch: 27.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:08 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 64%|██████▍   | 32/50 [9:34:41<10:06:03, 2020.17s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

573/573 - 22s - 38ms/step - ia: 0.2016 - loss: 1.0216 - mae: 0.8206 - rmse: 1.0080 - smape: 1.5221 - val_ia: 0.2992 - val_loss: 0.9192 - val_mae: 0.8016 - val_rmse: 0.9152 - val_smape: 1.4826

Epoch 2/32

573/573 - 8s - 13ms/step - ia: 0.2079 - loss: 0.9290 - mae: 0.7860 - rmse: 0.9612 - smape: 1.5404 - val_ia: 0.2981 - val_loss: 0.8829 - val_mae: 0.7899 - val_rmse: 0.8971 - val_smape: 1.4859

Epoch 3/32

573/573 - 8s - 14ms/step - ia: 0.2411 - loss: 0.8678 - mae: 0.7649 - rmse: 0.9293 - smape: 1.4986 - val_ia: 0.2979 - val_loss: 0.8710 - val_mae: 0.7883 - val_rmse: 0.8906 - val_smape: 1.4719

Epoch 4/32

573/573 - 8s - 14ms/step - ia: 0.2858 - loss: 0.8212 - mae: 0.7482 - rmse: 0.9040 - smape: 1.4346 - val_ia: 0.2999 - val_loss: 0.8772 - val_mae: 0.7936 - val_rmse: 0.8930 - val_smape: 1.4477

Epoch 5/32

573/573 - 8s - 14ms/step - ia: 0.3280 - loss: 0.7799 - mae: 0.7310 - rmse: 0.8809 - smape: 1.3731 - val_ia: 0.3051 - val_loss: 0.8958 - val_mae: 0.8038 - val_rmse: 0.9016 - val_smape: 1.4274

Epoch 6/32

573/573 - 8s - 14ms/step - ia: 0.3660 - loss: 0.7377 - mae: 0.7118 - rmse: 0.8569 - smape: 1.3221 - val_ia: 0.3131 - val_loss: 0.9385 - val_mae: 0.8241 - val_rmse: 0.9220 - val_smape: 1.4138

Epoch 7/32

573/573 - 8s - 15ms/step - ia: 0.4035 - loss: 0.6921 - mae: 0.6898 - rmse: 0.8296 - smape: 1.2722 - val_ia: 0.3199 - val_loss: 1.0016 - val_mae: 0.8528 - val_rmse: 0.9521 - val_smape: 1.4079

Epoch 8/32

573/573 - 8s - 14ms/step - ia: 0.4426 - loss: 0.6432 - mae: 0.6645 - rmse: 0.7998 - smape: 1.2182 - val_ia: 0.3263 - val_loss: 1.0903 - val_mae: 0.8918 - val_rmse: 0.9935 - val_smape: 1.4091

Epoch 9/32

573/573 - 8s - 14ms/step - ia: 0.4835 - loss: 0.5933 - mae: 0.6368 - rmse: 0.7681 - smape: 1.1560 - val_ia: 0.3301 - val_loss: 1.2070 - val_mae: 0.9411 - val_rmse: 1.0461 - val_smape: 1.4150

Epoch 10/32

573/573 - 8s - 14ms/step - ia: 0.5236 - loss: 0.5472 - mae: 0.6088 - rmse: 0.7376 - smape: 1.0934 - val_ia: 0.3315 - val_loss: 1.3130 - val_mae: 0.9837 - val_rmse: 1.0916 - val_smape: 1.4192

Epoch 11/32

573/573 - 8s - 14ms/step - ia: 0.5602 - loss: 0.5095 - mae: 0.5827 - rmse: 0.7116 - smape: 1.0380 - val_ia: 0.3314 - val_loss: 1.4046 - val_mae: 1.0193 - val_rmse: 1.1293 - val_smape: 1.4226

Epoch 12/32

573/573 - 8s - 14ms/step - ia: 0.5895 - loss: 0.4825 - mae: 0.5613 - rmse: 0.6923 - smape: 0.9938 - val_ia: 0.3294 - val_loss: 1.4879 - val_mae: 1.0516 - val_rmse: 1.1625 - val_smape: 1.4285

Epoch 13/32

573/573 - 8s - 14ms/step - ia: 0.6089 - loss: 0.4647 - mae: 0.5463 - rmse: 0.6791 - smape: 0.9612 - val_ia: 0.3297 - val_loss: 1.5184 - val_mae: 1.0623 - val_rmse: 1.1736 - val_smape: 1.4251

Epoch 14/32

573/573 - 8s - 14ms/step - ia: 0.6230 - loss: 0.4528 - mae: 0.5362 - rmse: 0.6703 - smape: 0.9390 - val_ia: 0.3301 - val_loss: 1.5192 - val_mae: 1.0624 - val_rmse: 1.1728 - val_smape: 1.4219

Epoch 15/32

573/573 - 7s - 13ms/step - ia: 0.6310 - loss: 0.4441 - mae: 0.5294 - rmse: 0.6638 - smape: 0.9264 - val_ia: 0.3305 - val_loss: 1.5136 - val_mae: 1.0606 - val_rmse: 1.1697 - val_smape: 1.4194

Epoch 16/32

573/573 - 8s - 13ms/step - ia: 0.6368 - loss: 0.4368 - mae: 0.5243 - rmse: 0.6586 - smape: 0.9170 - val_ia: 0.3309 - val_loss: 1.5051 - val_mae: 1.0575 - val_rmse: 1.1656 - val_smape: 1.4170

Epoch 17/32

573/573 - 8s - 15ms/step - ia: 0.6413 - loss: 0.4303 - mae: 0.5200 - rmse: 0.6534 - smape: 0.9095 - val_ia: 0.3313 - val_loss: 1.4998 - val_mae: 1.0552 - val_rmse: 1.1630 - val_smape: 1.4143

Epoch 18/32

573/573 - 8s - 14ms/step - ia: 0.6447 - loss: 0.4243 - mae: 0.5163 - rmse: 0.6492 - smape: 0.9034 - val_ia: 0.3324 - val_loss: 1.4774 - val_mae: 1.0470 - val_rmse: 1.1535 - val_smape: 1.4107

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 66%|██████▌   | 33/50 [9:37:23<6:54:26, 1462.72s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 103s - 22ms/step - ia: 0.7942 - loss: 0.1526 - mae: 0.2837 - rmse: 0.3598 - smape: 0.6347 - val_ia: 0.2828 - val_loss: 0.1447 - val_mae: 0.2993 - val_rmse: 0.3145 - val_smape: 0.6717

Epoch 2/32

4584/4584 - 81s - 18ms/step - ia: 0.8570 - loss: 0.0774 - mae: 0.2016 - rmse: 0.2605 - smape: 0.5049 - val_ia: 0.2666 - val_loss: 0.1778 - val_mae: 0.3232 - val_rmse: 0.3408 - val_smape: 0.6818

Epoch 3/32

4584/4584 - 83s - 18ms/step - ia: 0.8712 - loss: 0.0635 - mae: 0.1824 - rmse: 0.2354 - smape: 0.4645 - val_ia: 0.2254 - val_loss: 0.3000 - val_mae: 0.4129 - val_rmse: 0.4332 - val_smape: 0.8163

Epoch 4/32

4584/4584 - 83s - 18ms/step - ia: 0.8796 - loss: 0.0562 - mae: 0.1704 - rmse: 0.2209 - smape: 0.4415 - val_ia: 0.2797 - val_loss: 0.1575 - val_mae: 0.3035 - val_rmse: 0.3199 - val_smape: 0.6697

Epoch 5/32

4584/4584 - 83s - 18ms/step - ia: 0.8840 - loss: 0.0520 - mae: 0.1638 - rmse: 0.2120 - smape: 0.4267 - val_ia: 0.2645 - val_loss: 0.2357 - val_mae: 0.3623 - val_rmse: 0.3800 - val_smape: 0.7651

Epoch 6/32

4584/4584 - 82s - 18ms/step - ia: 0.8897 - loss: 0.0479 - mae: 0.1565 - rmse: 0.2035 - smape: 0.4159 - val_ia: 0.2899 - val_loss: 0.1758 - val_mae: 0.3121 - val_rmse: 0.3292 - val_smape: 0.6872

Epoch 7/32

4584/4584 - 83s - 18ms/step - ia: 0.8940 - loss: 0.0450 - mae: 0.1511 - rmse: 0.1967 - smape: 0.4042 - val_ia: 0.2607 - val_loss: 0.2034 - val_mae: 0.3450 - val_rmse: 0.3618 - val_smape: 0.7448

Epoch 8/32

4584/4584 - 82s - 18ms/step - ia: 0.8972 - loss: 0.0427 - mae: 0.1466 - rmse: 0.1910 - smape: 0.3952 - val_ia: 0.2868 - val_loss: 0.1917 - val_mae: 0.3253 - val_rmse: 0.3425 - val_smape: 0.6965

Epoch 9/32

4584/4584 - 80s - 17ms/step - ia: 0.9006 - loss: 0.0402 - mae: 0.1419 - rmse: 0.1857 - smape: 0.3871 - val_ia: 0.2834 - val_loss: 0.1945 - val_mae: 0.3310 - val_rmse: 0.3476 - val_smape: 0.7098

Epoch 10/32

4584/4584 - 84s - 18ms/step - ia: 0.9034 - loss: 0.0377 - mae: 0.1379 - rmse: 0.1799 - smape: 0.3811 - val_ia: 0.2791 - val_loss: 0.2055 - val_mae: 0.3343 - val_rmse: 0.3532 - val_smape: 0.7070

Epoch 11/32

4584/4584 - 82s - 18ms/step - ia: 0.9054 - loss: 0.0368 - mae: 0.1355 - rmse: 0.1767 - smape: 0.3739 - val_ia: 0.2814 - val_loss: 0.2029 - val_mae: 0.3324 - val_rmse: 0.3507 - val_smape: 0.6970

Epoch 12/32

4584/4584 - 84s - 18ms/step - ia: 0.9073 - loss: 0.0348 - mae: 0.1322 - rmse: 0.1722 - smape: 0.3679 - val_ia: 0.2998 - val_loss: 0.1799 - val_mae: 0.3165 - val_rmse: 0.3333 - val_smape: 0.6807

Epoch 13/32

4584/4584 - 87s - 19ms/step - ia: 0.9094 - loss: 0.0333 - mae: 0.1290 - rmse: 0.1683 - smape: 0.3612 - val_ia: 0.2912 - val_loss: 0.2168 - val_mae: 0.3429 - val_rmse: 0.3612 - val_smape: 0.7065

Epoch 14/32

4584/4584 - 103s - 22ms/step - ia: 0.9113 - loss: 0.0316 - mae: 0.1261 - rmse: 0.1642 - smape: 0.3557 - val_ia: 0.2935 - val_loss: 0.1887 - val_mae: 0.3188 - val_rmse: 0.3368 - val_smape: 0.6800

Epoch 15/32

4584/4584 - 92s - 20ms/step - ia: 0.9131 - loss: 0.0305 - mae: 0.1238 - rmse: 0.1612 - smape: 0.3493 - val_ia: 0.2688 - val_loss: 0.2396 - val_mae: 0.3633 - val_rmse: 0.3822 - val_smape: 0.7429

Epoch 16/32

4584/4584 - 97s - 21ms/step - ia: 0.9152 - loss: 0.0288 - mae: 0.1209 - rmse: 0.1571 - smape: 0.3451 - val_ia: 0.2909 - val_loss: 0.2129 - val_mae: 0.3385 - val_rmse: 0.3573 - val_smape: 0.7097

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:16 842ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step

 68%|██████▊   | 34/50 [10:00:35<6:24:25, 1441.58s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1146/1146 - 28s - 24ms/step - ia: 0.1926 - loss: 0.9198 - mae: 0.7985 - rmse: 0.9536 - smape: 1.6665 - val_ia: 0.2461 - val_loss: 0.7659 - val_mae: 0.7140 - val_rmse: 0.7864 - val_smape: 1.2838

Epoch 2/64

1146/1146 - 19s - 17ms/step - ia: 0.6133 - loss: 0.4269 - mae: 0.5268 - rmse: 0.6443 - smape: 0.9192 - val_ia: 0.2690 - val_loss: 0.9325 - val_mae: 0.8079 - val_rmse: 0.8791 - val_smape: 1.2749

Epoch 3/64

1146/1146 - 15s - 13ms/step - ia: 0.7088 - loss: 0.3114 - mae: 0.4415 - rmse: 0.5537 - smape: 0.7763 - val_ia: 0.2861 - val_loss: 0.7943 - val_mae: 0.7371 - val_rmse: 0.8089 - val_smape: 1.2027

Epoch 4/64

1146/1146 - 15s - 13ms/step - ia: 0.7241 - loss: 0.2858 - mae: 0.4211 - rmse: 0.5303 - smape: 0.7533 - val_ia: 0.2985 - val_loss: 0.7344 - val_mae: 0.6986 - val_rmse: 0.7717 - val_smape: 1.1373

Epoch 5/64

1146/1146 - 16s - 14ms/step - ia: 0.7330 - loss: 0.2693 - mae: 0.4085 - rmse: 0.5151 - smape: 0.7389 - val_ia: 0.3279 - val_loss: 0.6146 - val_mae: 0.6200 - val_rmse: 0.6944 - val_smape: 1.0405

Epoch 6/64

1146/1146 - 15s - 13ms/step - ia: 0.7413 - loss: 0.2547 - mae: 0.3966 - rmse: 0.5006 - smape: 0.7268 - val_ia: 0.3479 - val_loss: 0.5746 - val_mae: 0.5871 - val_rmse: 0.6635 - val_smape: 0.9912

Epoch 7/64

1146/1146 - 10s - 9ms/step - ia: 0.7500 - loss: 0.2382 - mae: 0.3825 - rmse: 0.4841 - smape: 0.7132 - val_ia: 0.3537 - val_loss: 0.5986 - val_mae: 0.5902 - val_rmse: 0.6671 - val_smape: 0.9737

Epoch 8/64

1146/1146 - 15s - 13ms/step - ia: 0.7633 - loss: 0.2178 - mae: 0.3636 - rmse: 0.4623 - smape: 0.6973 - val_ia: 0.3549 - val_loss: 0.6474 - val_mae: 0.6072 - val_rmse: 0.6834 - val_smape: 0.9729

Epoch 9/64

1146/1146 - 17s - 14ms/step - ia: 0.7767 - loss: 0.1974 - mae: 0.3440 - rmse: 0.4400 - smape: 0.6836 - val_ia: 0.3766 - val_loss: 0.5812 - val_mae: 0.5739 - val_rmse: 0.6443 - val_smape: 0.9380

Epoch 10/64

1146/1146 - 16s - 14ms/step - ia: 0.7884 - loss: 0.1802 - mae: 0.3266 - rmse: 0.4201 - smape: 0.6716 - val_ia: 0.4064 - val_loss: 0.4547 - val_mae: 0.5103 - val_rmse: 0.5748 - val_smape: 0.8953

Epoch 11/64

1146/1146 - 15s - 13ms/step - ia: 0.7996 - loss: 0.1635 - mae: 0.3095 - rmse: 0.4001 - smape: 0.6576 - val_ia: 0.4247 - val_loss: 0.4071 - val_mae: 0.4837 - val_rmse: 0.5448 - val_smape: 0.8686

Epoch 12/64

1146/1146 - 15s - 13ms/step - ia: 0.8112 - loss: 0.1474 - mae: 0.2921 - rmse: 0.3795 - smape: 0.6413 - val_ia: 0.4368 - val_loss: 0.3966 - val_mae: 0.4721 - val_rmse: 0.5350 - val_smape: 0.8449

Epoch 13/64

1146/1146 - 15s - 13ms/step - ia: 0.8224 - loss: 0.1321 - mae: 0.2746 - rmse: 0.3591 - smape: 0.6236 - val_ia: 0.4471 - val_loss: 0.3617 - val_mae: 0.4492 - val_rmse: 0.5142 - val_smape: 0.8387

Epoch 14/64

1146/1146 - 15s - 13ms/step - ia: 0.8321 - loss: 0.1193 - mae: 0.2598 - rmse: 0.3408 - smape: 0.6066 - val_ia: 0.4692 - val_loss: 0.3057 - val_mae: 0.4152 - val_rmse: 0.4776 - val_smape: 0.7858

Epoch 15/64

1146/1146 - 16s - 14ms/step - ia: 0.8403 - loss: 0.1092 - mae: 0.2471 - rmse: 0.3261 - smape: 0.5887 - val_ia: 0.4864 - val_loss: 0.2511 - val_mae: 0.3816 - val_rmse: 0.4406 - val_smape: 0.7597

Epoch 16/64

1146/1146 - 15s - 13ms/step - ia: 0.8467 - loss: 0.1019 - mae: 0.2381 - rmse: 0.3147 - smape: 0.5726 - val_ia: 0.4991 - val_loss: 0.2369 - val_mae: 0.3693 - val_rmse: 0.4281 - val_smape: 0.7315

Epoch 17/64

1146/1146 - 16s - 14ms/step - ia: 0.8508 - loss: 0.0974 - mae: 0.2323 - rmse: 0.3077 - smape: 0.5631 - val_ia: 0.5069 - val_loss: 0.2119 - val_mae: 0.3506 - val_rmse: 0.4100 - val_smape: 0.7170

Epoch 18/64

1146/1146 - 15s - 13ms/step - ia: 0.8541 - loss: 0.0937 - mae: 0.2276 - rmse: 0.3019 - smape: 0.5527 - val_ia: 0.5190 - val_loss: 0.2019 - val_mae: 0.3432 - val_rmse: 0.4004 - val_smape: 0.7106

Epoch 19/64

1146/1146 - 15s - 13ms/step - ia: 0.8563 - loss: 0.0913 - mae: 0.2243 - rmse: 0.2976 - smape: 0.5456 - val_ia: 0.5312 - val_loss: 0.1794 - val_mae: 0.3241 - val_rmse: 0.3797 - val_smape: 0.6809

Epoch 20/64

1146/1146 - 15s - 13ms/step - ia: 0.8581 - loss: 0.0894 - mae: 0.2219 - rmse: 0.2943 - smape: 0.5418 - val_ia: 0.5300 - val_loss: 0.1762 - val_mae: 0.3213 - val_rmse: 0.3776 - val_smape: 0.6844

Epoch 21/64

1146/1146 - 15s - 13ms/step - ia: 0.8595 - loss: 0.0879 - mae: 0.2198 - rmse: 0.2921 - smape: 0.5382 - val_ia: 0.5311 - val_loss: 0.1833 - val_mae: 0.3266 - val_rmse: 0.3833 - val_smape: 0.6859

Epoch 22/64

1146/1146 - 16s - 14ms/step - ia: 0.8605 - loss: 0.0867 - mae: 0.2185 - rmse: 0.2901 - smape: 0.5356 - val_ia: 0.5344 - val_loss: 0.1720 - val_mae: 0.3173 - val_rmse: 0.3738 - val_smape: 0.6714

Epoch 23/64

1146/1146 - 15s - 13ms/step - ia: 0.8613 - loss: 0.0856 - mae: 0.2169 - rmse: 0.2881 - smape: 0.5325 - val_ia: 0.5342 - val_loss: 0.1789 - val_mae: 0.3227 - val_rmse: 0.3797 - val_smape: 0.6776

Epoch 24/64

1146/1146 - 15s - 13ms/step - ia: 0.8624 - loss: 0.0846 - mae: 0.2155 - rmse: 0.2863 - smape: 0.5301 - val_ia: 0.5341 - val_loss: 0.1680 - val_mae: 0.3145 - val_rmse: 0.3714 - val_smape: 0.6775

Epoch 25/64

1146/1146 - 15s - 13ms/step - ia: 0.8633 - loss: 0.0835 - mae: 0.2140 - rmse: 0.2844 - smape: 0.5278 - val_ia: 0.5277 - val_loss: 0.1855 - val_mae: 0.3280 - val_rmse: 0.3875 - val_smape: 0.6890

Epoch 26/64

1146/1146 - 15s - 13ms/step - ia: 0.8638 - loss: 0.0829 - mae: 0.2130 - rmse: 0.2833 - smape: 0.5258 - val_ia: 0.5390 - val_loss: 0.1666 - val_mae: 0.3120 - val_rmse: 0.3683 - val_smape: 0.6615

Epoch 27/64

1146/1146 - 15s - 13ms/step - ia: 0.8643 - loss: 0.0822 - mae: 0.2124 - rmse: 0.2820 - smape: 0.5257 - val_ia: 0.5425 - val_loss: 0.1617 - val_mae: 0.3093 - val_rmse: 0.3642 - val_smape: 0.6626

Epoch 28/64

1146/1146 - 15s - 13ms/step - ia: 0.8650 - loss: 0.0817 - mae: 0.2115 - rmse: 0.2811 - smape: 0.5237 - val_ia: 0.5369 - val_loss: 0.1623 - val_mae: 0.3093 - val_rmse: 0.3661 - val_smape: 0.6627

Epoch 29/64

1146/1146 - 16s - 14ms/step - ia: 0.8656 - loss: 0.0810 - mae: 0.2107 - rmse: 0.2799 - smape: 0.5227 - val_ia: 0.5385 - val_loss: 0.1580 - val_mae: 0.3073 - val_rmse: 0.3629 - val_smape: 0.6749

Epoch 30/64

1146/1146 - 15s - 13ms/step - ia: 0.8662 - loss: 0.0804 - mae: 0.2097 - rmse: 0.2788 - smape: 0.5210 - val_ia: 0.5342 - val_loss: 0.1673 - val_mae: 0.3140 - val_rmse: 0.3713 - val_smape: 0.6722

Epoch 31/64

1146/1146 - 16s - 14ms/step - ia: 0.8664 - loss: 0.0799 - mae: 0.2093 - rmse: 0.2780 - smape: 0.5214 - val_ia: 0.5357 - val_loss: 0.1701 - val_mae: 0.3164 - val_rmse: 0.3737 - val_smape: 0.6772

Epoch 32/64

1146/1146 - 17s - 15ms/step - ia: 0.8672 - loss: 0.0794 - mae: 0.2085 - rmse: 0.2775 - smape: 0.5197 - val_ia: 0.5388 - val_loss: 0.1544 - val_mae: 0.3036 - val_rmse: 0.3594 - val_smape: 0.6643

Epoch 33/64

1146/1146 - 15s - 13ms/step - ia: 0.8673 - loss: 0.0788 - mae: 0.2077 - rmse: 0.2763 - smape: 0.5194 - val_ia: 0.5406 - val_loss: 0.1583 - val_mae: 0.3069 - val_rmse: 0.3618 - val_smape: 0.6664

Epoch 34/64

1146/1146 - 16s - 14ms/step - ia: 0.8676 - loss: 0.0784 - mae: 0.2074 - rmse: 0.2756 - smape: 0.5180 - val_ia: 0.5353 - val_loss: 0.1654 - val_mae: 0.3127 - val_rmse: 0.3701 - val_smape: 0.6696

Epoch 35/64

1146/1146 - 15s - 13ms/step - ia: 0.8682 - loss: 0.0778 - mae: 0.2065 - rmse: 0.2746 - smape: 0.5161 - val_ia: 0.5359 - val_loss: 0.1692 - val_mae: 0.3164 - val_rmse: 0.3732 - val_smape: 0.6747

Epoch 36/64

1146/1146 - 16s - 14ms/step - ia: 0.8687 - loss: 0.0775 - mae: 0.2063 - rmse: 0.2740 - smape: 0.5173 - val_ia: 0.5335 - val_loss: 0.1685 - val_mae: 0.3156 - val_rmse: 0.3734 - val_smape: 0.6762

Epoch 37/64

1146/1146 - 12s - 10ms/step - ia: 0.8687 - loss: 0.0773 - mae: 0.2059 - rmse: 0.2738 - smape: 0.5140 - val_ia: 0.5404 - val_loss: 0.1494 - val_mae: 0.3014 - val_rmse: 0.3554 - val_smape: 0.6666

Epoch 38/64

1146/1146 - 14s - 13ms/step - ia: 0.8694 - loss: 0.0766 - mae: 0.2049 - rmse: 0.2725 - smape: 0.5127 - val_ia: 0.5345 - val_loss: 0.1735 - val_mae: 0.3223 - val_rmse: 0.3774 - val_smape: 0.6863

Epoch 39/64

1146/1146 - 15s - 13ms/step - ia: 0.8695 - loss: 0.0766 - mae: 0.2047 - rmse: 0.2724 - smape: 0.5119 - val_ia: 0.5374 - val_loss: 0.1536 - val_mae: 0.3060 - val_rmse: 0.3606 - val_smape: 0.6768

Epoch 40/64

1146/1146 - 15s - 13ms/step - ia: 0.8697 - loss: 0.0762 - mae: 0.2045 - rmse: 0.2718 - smape: 0.5130 - val_ia: 0.5383 - val_loss: 0.1577 - val_mae: 0.3097 - val_rmse: 0.3636 - val_smape: 0.6745

Epoch 41/64

1146/1146 - 15s - 13ms/step - ia: 0.8699 - loss: 0.0758 - mae: 0.2040 - rmse: 0.2708 - smape: 0.5119 - val_ia: 0.5359 - val_loss: 0.1625 - val_mae: 0.3138 - val_rmse: 0.3678 - val_smape: 0.6834

Epoch 42/64

1146/1146 - 15s - 13ms/step - ia: 0.8699 - loss: 0.0753 - mae: 0.2034 - rmse: 0.2698 - smape: 0.5109 - val_ia: 0.5401 - val_loss: 0.1586 - val_mae: 0.3083 - val_rmse: 0.3627 - val_smape: 0.6675

Epoch 43/64

1146/1146 - 15s - 13ms/step - ia: 0.8705 - loss: 0.0749 - mae: 0.2027 - rmse: 0.2692 - smape: 0.5098 - val_ia: 0.5352 - val_loss: 0.1554 - val_mae: 0.3067 - val_rmse: 0.3625 - val_smape: 0.6785

Epoch 44/64

1146/1146 - 15s - 13ms/step - ia: 0.8708 - loss: 0.0747 - mae: 0.2024 - rmse: 0.2690 - smape: 0.5102 - val_ia: 0.5376 - val_loss: 0.1594 - val_mae: 0.3110 - val_rmse: 0.3648 - val_smape: 0.6770

Epoch 45/64

1146/1146 - 15s - 13ms/step - ia: 0.8718 - loss: 0.0743 - mae: 0.2016 - rmse: 0.2685 - smape: 0.5069 - val_ia: 0.5386 - val_loss: 0.1559 - val_mae: 0.3085 - val_rmse: 0.3612 - val_smape: 0.6771

Epoch 46/64

1146/1146 - 15s - 13ms/step - ia: 0.8719 - loss: 0.0739 - mae: 0.2011 - rmse: 0.2675 - smape: 0.5061 - val_ia: 0.5430 - val_loss: 0.1495 - val_mae: 0.3017 - val_rmse: 0.3540 - val_smape: 0.6595

Epoch 47/64

1146/1146 - 15s - 13ms/step - ia: 0.8719 - loss: 0.0738 - mae: 0.2010 - rmse: 0.2671 - smape: 0.5055 - val_ia: 0.5386 - val_loss: 0.1534 - val_mae: 0.3053 - val_rmse: 0.3594 - val_smape: 0.6743

Epoch 48/64

1146/1146 - 15s - 13ms/step - ia: 0.8727 - loss: 0.0731 - mae: 0.2002 - rmse: 0.2663 - smape: 0.5052 - val_ia: 0.5396 - val_loss: 0.1512 - val_mae: 0.3033 - val_rmse: 0.3580 - val_smape: 0.6729

Epoch 49/64

1146/1146 - 16s - 14ms/step - ia: 0.8726 - loss: 0.0731 - mae: 0.2000 - rmse: 0.2660 - smape: 0.5052 - val_ia: 0.5398 - val_loss: 0.1500 - val_mae: 0.3042 - val_rmse: 0.3567 - val_smape: 0.6763

Epoch 50/64

1146/1146 - 15s - 13ms/step - ia: 0.8729 - loss: 0.0725 - mae: 0.1993 - rmse: 0.2652 - smape: 0.5043 - val_ia: 0.5361 - val_loss: 0.1577 - val_mae: 0.3091 - val_rmse: 0.3635 - val_smape: 0.6743

Epoch 51/64

1146/1146 - 16s - 14ms/step - ia: 0.8734 - loss: 0.0722 - mae: 0.1989 - rmse: 0.2645 - smape: 0.5029 - val_ia: 0.5379 - val_loss: 0.1566 - val_mae: 0.3081 - val_rmse: 0.3616 - val_smape: 0.6731

Epoch 52/64

1146/1146 - 15s - 13ms/step - ia: 0.8732 - loss: 0.0723 - mae: 0.1991 - rmse: 0.2649 - smape: 0.5037 - val_ia: 0.5365 - val_loss: 0.1563 - val_mae: 0.3083 - val_rmse: 0.3628 - val_smape: 0.6745

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:19 863ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 70%|███████   | 35/50 [10:14:03<5:12:53, 1251.56s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 46s - 20ms/step - ia: 0.2235 - loss: 1.1162 - mae: 0.8729 - rmse: 1.0449 - smape: 1.5617 - val_ia: 0.1769 - val_loss: 0.8880 - val_mae: 0.7842 - val_rmse: 0.8204 - val_smape: 1.7836

Epoch 2/32

2292/2292 - 26s - 11ms/step - ia: 0.2196 - loss: 1.1001 - mae: 0.8653 - rmse: 1.0384 - smape: 1.6217 - val_ia: 0.1800 - val_loss: 0.8691 - val_mae: 0.7756 - val_rmse: 0.8120 - val_smape: 1.8961

Epoch 3/32

2292/2292 - 28s - 12ms/step - ia: 0.2177 - loss: 1.0850 - mae: 0.8607 - rmse: 1.0312 - smape: 1.6364 - val_ia: 0.1806 - val_loss: 0.8622 - val_mae: 0.7724 - val_rmse: 0.8089 - val_smape: 1.9408

Epoch 4/32

2292/2292 - 27s - 12ms/step - ia: 0.2165 - loss: 1.0799 - mae: 0.8603 - rmse: 1.0286 - smape: 1.6478 - val_ia: 0.1802 - val_loss: 0.8588 - val_mae: 0.7710 - val_rmse: 0.8075 - val_smape: 1.9476

Epoch 5/32

2292/2292 - 26s - 11ms/step - ia: 0.2182 - loss: 1.0703 - mae: 0.8563 - rmse: 1.0244 - smape: 1.6438 - val_ia: 0.1793 - val_loss: 0.8579 - val_mae: 0.7707 - val_rmse: 0.8073 - val_smape: 1.9211

Epoch 6/32

2292/2292 - 29s - 13ms/step - ia: 0.2193 - loss: 1.0589 - mae: 0.8519 - rmse: 1.0182 - smape: 1.6403 - val_ia: 0.1788 - val_loss: 0.8556 - val_mae: 0.7697 - val_rmse: 0.8064 - val_smape: 1.9073

Epoch 7/32

2292/2292 - 32s - 14ms/step - ia: 0.2213 - loss: 1.0550 - mae: 0.8512 - rmse: 1.0164 - smape: 1.6426 - val_ia: 0.1784 - val_loss: 0.8531 - val_mae: 0.7687 - val_rmse: 0.8053 - val_smape: 1.8893

Epoch 8/32

2292/2292 - 32s - 14ms/step - ia: 0.2190 - loss: 1.0478 - mae: 0.8482 - rmse: 1.0134 - smape: 1.6392 - val_ia: 0.1784 - val_loss: 0.8494 - val_mae: 0.7670 - val_rmse: 0.8037 - val_smape: 1.8697

Epoch 9/32

2292/2292 - 32s - 14ms/step - ia: 0.2209 - loss: 1.0386 - mae: 0.8448 - rmse: 1.0091 - smape: 1.6303 - val_ia: 0.1783 - val_loss: 0.8460 - val_mae: 0.7655 - val_rmse: 0.8023 - val_smape: 1.8464

Epoch 10/32

2292/2292 - 32s - 14ms/step - ia: 0.2211 - loss: 1.0322 - mae: 0.8422 - rmse: 1.0055 - smape: 1.6263 - val_ia: 0.1780 - val_loss: 0.8428 - val_mae: 0.7641 - val_rmse: 0.8009 - val_smape: 1.8217

Epoch 11/32

2292/2292 - 32s - 14ms/step - ia: 0.2203 - loss: 1.0280 - mae: 0.8420 - rmse: 1.0037 - smape: 1.6263 - val_ia: 0.1777 - val_loss: 0.8385 - val_mae: 0.7621 - val_rmse: 0.7990 - val_smape: 1.7970

Epoch 12/32

2292/2292 - 32s - 14ms/step - ia: 0.2226 - loss: 1.0170 - mae: 0.8371 - rmse: 0.9982 - smape: 1.6126 - val_ia: 0.1773 - val_loss: 0.8347 - val_mae: 0.7603 - val_rmse: 0.7972 - val_smape: 1.7708

Epoch 13/32

2292/2292 - 32s - 14ms/step - ia: 0.2261 - loss: 1.0042 - mae: 0.8328 - rmse: 0.9926 - smape: 1.6052 - val_ia: 0.1770 - val_loss: 0.8299 - val_mae: 0.7579 - val_rmse: 0.7950 - val_smape: 1.7437

Epoch 14/32

2292/2292 - 27s - 12ms/step - ia: 0.2285 - loss: 0.9989 - mae: 0.8301 - rmse: 0.9894 - smape: 1.5906 - val_ia: 0.1762 - val_loss: 0.8282 - val_mae: 0.7570 - val_rmse: 0.7941 - val_smape: 1.7156

Epoch 15/32

2292/2292 - 31s - 13ms/step - ia: 0.2294 - loss: 0.9908 - mae: 0.8278 - rmse: 0.9852 - smape: 1.5856 - val_ia: 0.1762 - val_loss: 0.8248 - val_mae: 0.7553 - val_rmse: 0.7923 - val_smape: 1.6870

Epoch 16/32

2292/2292 - 31s - 13ms/step - ia: 0.2393 - loss: 0.9697 - mae: 0.8186 - rmse: 0.9753 - smape: 1.5692 - val_ia: 0.1766 - val_loss: 0.8192 - val_mae: 0.7524 - val_rmse: 0.7895 - val_smape: 1.6578

Epoch 17/32

2292/2292 - 30s - 13ms/step - ia: 0.2412 - loss: 0.9633 - mae: 0.8184 - rmse: 0.9723 - smape: 1.5636 - val_ia: 0.1769 - val_loss: 0.8142 - val_mae: 0.7497 - val_rmse: 0.7868 - val_smape: 1.6282

Epoch 18/32

2292/2292 - 30s - 13ms/step - ia: 0.2465 - loss: 0.9512 - mae: 0.8126 - rmse: 0.9658 - smape: 1.5476 - val_ia: 0.1776 - val_loss: 0.8099 - val_mae: 0.7472 - val_rmse: 0.7843 - val_smape: 1.5989

Epoch 19/32

2292/2292 - 33s - 14ms/step - ia: 0.2547 - loss: 0.9304 - mae: 0.8034 - rmse: 0.9553 - smape: 1.5295 - val_ia: 0.1793 - val_loss: 0.8021 - val_mae: 0.7430 - val_rmse: 0.7802 - val_smape: 1.5684

Epoch 20/32

2292/2292 - 31s - 13ms/step - ia: 0.2627 - loss: 0.9142 - mae: 0.7971 - rmse: 0.9472 - smape: 1.5147 - val_ia: 0.1824 - val_loss: 0.7986 - val_mae: 0.7407 - val_rmse: 0.7778 - val_smape: 1.5388

Epoch 21/32

2292/2292 - 31s - 13ms/step - ia: 0.2700 - loss: 0.9044 - mae: 0.7929 - rmse: 0.9420 - smape: 1.5017 - val_ia: 0.1848 - val_loss: 0.7929 - val_mae: 0.7372 - val_rmse: 0.7743 - val_smape: 1.5095

Epoch 22/32

2292/2292 - 31s - 13ms/step - ia: 0.2796 - loss: 0.8890 - mae: 0.7859 - rmse: 0.9333 - smape: 1.4831 - val_ia: 0.1877 - val_loss: 0.7901 - val_mae: 0.7351 - val_rmse: 0.7720 - val_smape: 1.4821

Epoch 23/32

2292/2292 - 31s - 13ms/step - ia: 0.2928 - loss: 0.8648 - mae: 0.7759 - rmse: 0.9209 - smape: 1.4623 - val_ia: 0.1901 - val_loss: 0.7873 - val_mae: 0.7329 - val_rmse: 0.7696 - val_smape: 1.4555

Epoch 24/32

2292/2292 - 29s - 13ms/step - ia: 0.3010 - loss: 0.8524 - mae: 0.7707 - rmse: 0.9146 - smape: 1.4447 - val_ia: 0.1906 - val_loss: 0.7838 - val_mae: 0.7305 - val_rmse: 0.7668 - val_smape: 1.4301

Epoch 25/32

2292/2292 - 31s - 13ms/step - ia: 0.3126 - loss: 0.8329 - mae: 0.7623 - rmse: 0.9041 - smape: 1.4230 - val_ia: 0.1916 - val_loss: 0.7846 - val_mae: 0.7301 - val_rmse: 0.7658 - val_smape: 1.4075

Epoch 26/32

2292/2292 - 30s - 13ms/step - ia: 0.3313 - loss: 0.8061 - mae: 0.7488 - rmse: 0.8888 - smape: 1.3917 - val_ia: 0.1926 - val_loss: 0.7840 - val_mae: 0.7289 - val_rmse: 0.7642 - val_smape: 1.3851

Epoch 27/32

2292/2292 - 31s - 13ms/step - ia: 0.3457 - loss: 0.7862 - mae: 0.7398 - rmse: 0.8779 - smape: 1.3653 - val_ia: 0.1931 - val_loss: 0.7879 - val_mae: 0.7299 - val_rmse: 0.7646 - val_smape: 1.3652

Epoch 28/32

2292/2292 - 27s - 12ms/step - ia: 0.3610 - loss: 0.7639 - mae: 0.7284 - rmse: 0.8647 - smape: 1.3384 - val_ia: 0.1931 - val_loss: 0.7960 - val_mae: 0.7328 - val_rmse: 0.7669 - val_smape: 1.3481

Epoch 29/32

2292/2292 - 24s - 11ms/step - ia: 0.3780 - loss: 0.7422 - mae: 0.7174 - rmse: 0.8529 - smape: 1.3105 - val_ia: 0.1933 - val_loss: 0.8085 - val_mae: 0.7378 - val_rmse: 0.7712 - val_smape: 1.3340

Epoch 30/32

2292/2292 - 25s - 11ms/step - ia: 0.3950 - loss: 0.7210 - mae: 0.7064 - rmse: 0.8403 - smape: 1.2802 - val_ia: 0.1931 - val_loss: 0.8224 - val_mae: 0.7436 - val_rmse: 0.7764 - val_smape: 1.3230

Epoch 31/32

2292/2292 - 24s - 11ms/step - ia: 0.4135 - loss: 0.6972 - mae: 0.6933 - rmse: 0.8262 - smape: 1.2486 - val_ia: 0.1926 - val_loss: 0.8420 - val_mae: 0.7522 - val_rmse: 0.7847 - val_smape: 1.3153

Epoch 32/32

2292/2292 - 24s - 11ms/step - ia: 0.4301 - loss: 0.6778 - mae: 0.6832 - rmse: 0.8144 - smape: 1.2242 - val_ia: 0.1921 - val_loss: 0.8638 - val_mae: 0.7621 - val_rmse: 0.7941 - val_smape: 1.3097

Restoring model weights from the end of the best epoch: 24.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:44 644ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/256

 72%|███████▏  | 36/50 [10:30:02<4:31:32, 1163.75s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 11s - 80ms/step - ia: 0.1002 - loss: 1.0176 - mae: 0.8358 - rmse: 1.0079 - smape: 1.7460 - val_ia: 0.2300 - val_loss: 0.8188 - val_mae: 0.7528 - val_rmse: 0.8953 - val_smape: 1.7338

Epoch 2/256

144/144 - 2s - 16ms/step - ia: 0.1323 - loss: 0.9609 - mae: 0.8149 - rmse: 0.9794 - smape: 1.7005 - val_ia: 0.2560 - val_loss: 0.7794 - val_mae: 0.7331 - val_rmse: 0.8727 - val_smape: 1.5555

Epoch 3/256

144/144 - 2s - 16ms/step - ia: 0.2037 - loss: 0.8881 - mae: 0.7860 - rmse: 0.9413 - smape: 1.5940 - val_ia: 0.3083 - val_loss: 0.7429 - val_mae: 0.7139 - val_rmse: 0.8503 - val_smape: 1.3954

Epoch 4/256

144/144 - 2s - 14ms/step - ia: 0.2882 - loss: 0.8070 - mae: 0.7514 - rmse: 0.8981 - smape: 1.4723 - val_ia: 0.3758 - val_loss: 0.7029 - val_mae: 0.6936 - val_rmse: 0.8241 - val_smape: 1.2873

Epoch 5/256

144/144 - 2s - 15ms/step - ia: 0.3826 - loss: 0.7071 - mae: 0.7009 - rmse: 0.8400 - smape: 1.3376 - val_ia: 0.4366 - val_loss: 0.6967 - val_mae: 0.6878 - val_rmse: 0.8168 - val_smape: 1.2133

Epoch 6/256

144/144 - 2s - 16ms/step - ia: 0.4879 - loss: 0.6037 - mae: 0.6378 - rmse: 0.7760 - smape: 1.1800 - val_ia: 0.4616 - val_loss: 0.7700 - val_mae: 0.7186 - val_rmse: 0.8578 - val_smape: 1.1901

Epoch 7/256

144/144 - 2s - 15ms/step - ia: 0.5551 - loss: 0.5331 - mae: 0.5928 - rmse: 0.7287 - smape: 1.0765 - val_ia: 0.4787 - val_loss: 0.7769 - val_mae: 0.7183 - val_rmse: 0.8620 - val_smape: 1.1594

Epoch 8/256

144/144 - 2s - 15ms/step - ia: 0.5895 - loss: 0.4904 - mae: 0.5643 - rmse: 0.6996 - smape: 1.0144 - val_ia: 0.4930 - val_loss: 0.7494 - val_mae: 0.7082 - val_rmse: 0.8465 - val_smape: 1.1450

Epoch 9/256

144/144 - 2s - 15ms/step - ia: 0.6070 - loss: 0.4673 - mae: 0.5495 - rmse: 0.6828 - smape: 0.9819 - val_ia: 0.5090 - val_loss: 0.6935 - val_mae: 0.6858 - val_rmse: 0.8138 - val_smape: 1.1274

Epoch 10/256

144/144 - 2s - 16ms/step - ia: 0.6252 - loss: 0.4427 - mae: 0.5334 - rmse: 0.6648 - smape: 0.9477 - val_ia: 0.5192 - val_loss: 0.6526 - val_mae: 0.6702 - val_rmse: 0.7891 - val_smape: 1.1201

Epoch 11/256

144/144 - 2s - 15ms/step - ia: 0.6378 - loss: 0.4246 - mae: 0.5209 - rmse: 0.6507 - smape: 0.9222 - val_ia: 0.5262 - val_loss: 0.6265 - val_mae: 0.6608 - val_rmse: 0.7727 - val_smape: 1.1164

Epoch 12/256

144/144 - 2s - 15ms/step - ia: 0.6489 - loss: 0.4053 - mae: 0.5086 - rmse: 0.6368 - smape: 0.8998 - val_ia: 0.5427 - val_loss: 0.5683 - val_mae: 0.6321 - val_rmse: 0.7354 - val_smape: 1.0939

Epoch 13/256

144/144 - 2s - 15ms/step - ia: 0.6590 - loss: 0.3896 - mae: 0.4986 - rmse: 0.6239 - smape: 0.8852 - val_ia: 0.5493 - val_loss: 0.5535 - val_mae: 0.6262 - val_rmse: 0.7252 - val_smape: 1.0909

Epoch 14/256

144/144 - 2s - 16ms/step - ia: 0.6671 - loss: 0.3790 - mae: 0.4903 - rmse: 0.6145 - smape: 0.8666 - val_ia: 0.5591 - val_loss: 0.5191 - val_mae: 0.6094 - val_rmse: 0.7013 - val_smape: 1.0843

Epoch 15/256

144/144 - 2s - 15ms/step - ia: 0.6754 - loss: 0.3662 - mae: 0.4802 - rmse: 0.6044 - smape: 0.8539 - val_ia: 0.5684 - val_loss: 0.4976 - val_mae: 0.5990 - val_rmse: 0.6854 - val_smape: 1.0768

Epoch 16/256

144/144 - 2s - 15ms/step - ia: 0.6801 - loss: 0.3597 - mae: 0.4759 - rmse: 0.5992 - smape: 0.8466 - val_ia: 0.5784 - val_loss: 0.4708 - val_mae: 0.5842 - val_rmse: 0.6655 - val_smape: 1.0635

Epoch 17/256

144/144 - 2s - 15ms/step - ia: 0.6851 - loss: 0.3492 - mae: 0.4697 - rmse: 0.5901 - smape: 0.8399 - val_ia: 0.5873 - val_loss: 0.4503 - val_mae: 0.5725 - val_rmse: 0.6498 - val_smape: 1.0498

Epoch 18/256

144/144 - 2s - 14ms/step - ia: 0.6926 - loss: 0.3390 - mae: 0.4604 - rmse: 0.5819 - smape: 0.8287 - val_ia: 0.5920 - val_loss: 0.4389 - val_mae: 0.5657 - val_rmse: 0.6410 - val_smape: 1.0423

Epoch 19/256

144/144 - 2s - 15ms/step - ia: 0.6969 - loss: 0.3317 - mae: 0.4555 - rmse: 0.5753 - smape: 0.8215 - val_ia: 0.6001 - val_loss: 0.4249 - val_mae: 0.5564 - val_rmse: 0.6298 - val_smape: 1.0279

Epoch 20/256

144/144 - 2s - 15ms/step - ia: 0.7023 - loss: 0.3211 - mae: 0.4480 - rmse: 0.5660 - smape: 0.8128 - val_ia: 0.6076 - val_loss: 0.4135 - val_mae: 0.5482 - val_rmse: 0.6204 - val_smape: 1.0159

Epoch 21/256

144/144 - 2s - 15ms/step - ia: 0.7058 - loss: 0.3171 - mae: 0.4445 - rmse: 0.5628 - smape: 0.8104 - val_ia: 0.6101 - val_loss: 0.4103 - val_mae: 0.5452 - val_rmse: 0.6172 - val_smape: 1.0147

Epoch 22/256

144/144 - 2s - 16ms/step - ia: 0.7100 - loss: 0.3095 - mae: 0.4391 - rmse: 0.5559 - smape: 0.8067 - val_ia: 0.6122 - val_loss: 0.4077 - val_mae: 0.5428 - val_rmse: 0.6140 - val_smape: 1.0138

Epoch 23/256

144/144 - 2s - 16ms/step - ia: 0.7110 - loss: 0.3068 - mae: 0.4365 - rmse: 0.5532 - smape: 0.8041 - val_ia: 0.6151 - val_loss: 0.4062 - val_mae: 0.5410 - val_rmse: 0.6129 - val_smape: 1.0149

Epoch 24/256

144/144 - 2s - 15ms/step - ia: 0.7158 - loss: 0.2999 - mae: 0.4306 - rmse: 0.5470 - smape: 0.7994 - val_ia: 0.6153 - val_loss: 0.4082 - val_mae: 0.5415 - val_rmse: 0.6138 - val_smape: 1.0187

Epoch 25/256

144/144 - 2s - 15ms/step - ia: 0.7188 - loss: 0.2942 - mae: 0.4266 - rmse: 0.5420 - smape: 0.7988 - val_ia: 0.6248 - val_loss: 0.3931 - val_mae: 0.5286 - val_rmse: 0.6018 - val_smape: 1.0053

Epoch 26/256

144/144 - 3s - 18ms/step - ia: 0.7196 - loss: 0.2920 - mae: 0.4246 - rmse: 0.5400 - smape: 0.7959 - val_ia: 0.6246 - val_loss: 0.3975 - val_mae: 0.5306 - val_rmse: 0.6045 - val_smape: 1.0113

Epoch 27/256

144/144 - 2s - 15ms/step - ia: 0.7245 - loss: 0.2840 - mae: 0.4183 - rmse: 0.5326 - smape: 0.7913 - val_ia: 0.6223 - val_loss: 0.4084 - val_mae: 0.5374 - val_rmse: 0.6110 - val_smape: 1.0195

Epoch 28/256

144/144 - 2s - 15ms/step - ia: 0.7260 - loss: 0.2816 - mae: 0.4157 - rmse: 0.5298 - smape: 0.7900 - val_ia: 0.6264 - val_loss: 0.4050 - val_mae: 0.5339 - val_rmse: 0.6080 - val_smape: 1.0153

Epoch 29/256

144/144 - 2s - 15ms/step - ia: 0.7292 - loss: 0.2755 - mae: 0.4112 - rmse: 0.5243 - smape: 0.7883 - val_ia: 0.6296 - val_loss: 0.3977 - val_mae: 0.5277 - val_rmse: 0.6032 - val_smape: 1.0156

Epoch 30/256

144/144 - 2s - 15ms/step - ia: 0.7320 - loss: 0.2714 - mae: 0.4071 - rmse: 0.5201 - smape: 0.7834 - val_ia: 0.6319 - val_loss: 0.4026 - val_mae: 0.5295 - val_rmse: 0.6043 - val_smape: 1.0105

Epoch 31/256

144/144 - 2s - 15ms/step - ia: 0.7352 - loss: 0.2665 - mae: 0.4033 - rmse: 0.5154 - smape: 0.7785 - val_ia: 0.6320 - val_loss: 0.3983 - val_mae: 0.5261 - val_rmse: 0.6027 - val_smape: 1.0179

Epoch 32/256

144/144 - 2s - 15ms/step - ia: 0.7350 - loss: 0.2653 - mae: 0.4026 - rmse: 0.5143 - smape: 0.7802 - val_ia: 0.6349 - val_loss: 0.4002 - val_mae: 0.5256 - val_rmse: 0.6028 - val_smape: 1.0172

Epoch 33/256

144/144 - 2s - 15ms/step - ia: 0.7387 - loss: 0.2590 - mae: 0.3977 - rmse: 0.5080 - smape: 0.7780 - val_ia: 0.6377 - val_loss: 0.3961 - val_mae: 0.5223 - val_rmse: 0.5992 - val_smape: 1.0118

Epoch 34/256

144/144 - 2s - 16ms/step - ia: 0.7402 - loss: 0.2561 - mae: 0.3949 - rmse: 0.5060 - smape: 0.7751 - val_ia: 0.6340 - val_loss: 0.4087 - val_mae: 0.5308 - val_rmse: 0.6081 - val_smape: 1.0199

Epoch 35/256

144/144 - 2s - 15ms/step - ia: 0.7432 - loss: 0.2518 - mae: 0.3913 - rmse: 0.5008 - smape: 0.7728 - val_ia: 0.6385 - val_loss: 0.4000 - val_mae: 0.5230 - val_rmse: 0.6005 - val_smape: 1.0115

Epoch 36/256

144/144 - 2s - 16ms/step - ia: 0.7461 - loss: 0.2459 - mae: 0.3866 - rmse: 0.4955 - smape: 0.7674 - val_ia: 0.6373 - val_loss: 0.4044 - val_mae: 0.5257 - val_rmse: 0.6035 - val_smape: 1.0167

Epoch 37/256

144/144 - 2s - 15ms/step - ia: 0.7467 - loss: 0.2440 - mae: 0.3859 - rmse: 0.4937 - smape: 0.7661 - val_ia: 0.6366 - val_loss: 0.4067 - val_mae: 0.5267 - val_rmse: 0.6047 - val_smape: 1.0185

Epoch 38/256

144/144 - 2s - 16ms/step - ia: 0.7491 - loss: 0.2416 - mae: 0.3825 - rmse: 0.4907 - smape: 0.7628 - val_ia: 0.6388 - val_loss: 0.4063 - val_mae: 0.5263 - val_rmse: 0.6036 - val_smape: 1.0136

Epoch 39/256

144/144 - 2s - 16ms/step - ia: 0.7507 - loss: 0.2383 - mae: 0.3806 - rmse: 0.4877 - smape: 0.7582 - val_ia: 0.6399 - val_loss: 0.4030 - val_mae: 0.5242 - val_rmse: 0.6014 - val_smape: 1.0148

Epoch 40/256

144/144 - 2s - 15ms/step - ia: 0.7520 - loss: 0.2361 - mae: 0.3787 - rmse: 0.4850 - smape: 0.7577 - val_ia: 0.6414 - val_loss: 0.3950 - val_mae: 0.5187 - val_rmse: 0.5970 - val_smape: 1.0161

Epoch 40: early stopping

Restoring model weights from the end of the best epoch: 25.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:41 629ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/8

 74%|███████▍  | 37/50 [10:31:43<3:03:02, 844.79s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4584/4584 - 42s - 9ms/step - ia: 0.7801 - loss: 0.1721 - mae: 0.3059 - rmse: 0.3838 - smape: 0.6623 - val_ia: 0.2570 - val_loss: 0.2135 - val_mae: 0.3583 - val_rmse: 0.3762 - val_smape: 0.7412

Epoch 2/8

4584/4584 - 41s - 9ms/step - ia: 0.8385 - loss: 0.0954 - mae: 0.2272 - rmse: 0.2903 - smape: 0.5479 - val_ia: 0.2686 - val_loss: 0.1676 - val_mae: 0.3188 - val_rmse: 0.3368 - val_smape: 0.6895

Epoch 3/8

4584/4584 - 43s - 9ms/step - ia: 0.8567 - loss: 0.0767 - mae: 0.2032 - rmse: 0.2598 - smape: 0.4970 - val_ia: 0.2349 - val_loss: 0.2881 - val_mae: 0.4027 - val_rmse: 0.4218 - val_smape: 0.7888

Epoch 4/8

4584/4584 - 43s - 9ms/step - ia: 0.8670 - loss: 0.0659 - mae: 0.1881 - rmse: 0.2407 - smape: 0.4648 - val_ia: 0.2442 - val_loss: 0.2956 - val_mae: 0.4058 - val_rmse: 0.4271 - val_smape: 0.8013

Epoch 5/8

4584/4584 - 42s - 9ms/step - ia: 0.8744 - loss: 0.0597 - mae: 0.1788 - rmse: 0.2293 - smape: 0.4488 - val_ia: 0.2595 - val_loss: 0.2578 - val_mae: 0.3788 - val_rmse: 0.3996 - val_smape: 0.7571

Epoch 6/8

4584/4584 - 42s - 9ms/step - ia: 0.8797 - loss: 0.0549 - mae: 0.1717 - rmse: 0.2197 - smape: 0.4347 - val_ia: 0.2473 - val_loss: 0.2369 - val_mae: 0.3779 - val_rmse: 0.3966 - val_smape: 0.7758

Epoch 7/8

4584/4584 - 43s - 9ms/step - ia: 0.8826 - loss: 0.0531 - mae: 0.1679 - rmse: 0.2159 - smape: 0.4255 - val_ia: 0.2730 - val_loss: 0.2179 - val_mae: 0.3491 - val_rmse: 0.3691 - val_smape: 0.7326

Epoch 8/8

4584/4584 - 40s - 9ms/step - ia: 0.8872 - loss: 0.0495 - mae: 0.1622 - rmse: 0.2081 - smape: 0.4151 - val_ia: 0.2876 - val_loss: 0.1867 - val_mae: 0.3216 - val_rmse: 0.3410 - val_smape: 0.6883

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:25 530ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

Epoch 1/128

 76%|███████▌  | 38/50 [10:37:22<2:18:36, 693.00s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

573/573 - 24s - 42ms/step - ia: 0.1050 - loss: 0.9865 - mae: 0.8254 - rmse: 0.9909 - smape: 1.8799 - val_ia: 0.2870 - val_loss: 0.8360 - val_mae: 0.7611 - val_rmse: 0.8771 - val_smape: 1.7666

Epoch 2/128

573/573 - 8s - 14ms/step - ia: 0.2890 - loss: 0.7926 - mae: 0.7450 - rmse: 0.8859 - smape: 1.4577 - val_ia: 0.3512 - val_loss: 0.8651 - val_mae: 0.7703 - val_rmse: 0.8751 - val_smape: 1.2909

Epoch 3/128

573/573 - 8s - 14ms/step - ia: 0.6275 - loss: 0.4301 - mae: 0.5283 - rmse: 0.6525 - smape: 0.9198 - val_ia: 0.3547 - val_loss: 1.0624 - val_mae: 0.8687 - val_rmse: 0.9758 - val_smape: 1.3079

Epoch 4/128

573/573 - 8s - 14ms/step - ia: 0.6823 - loss: 0.3646 - mae: 0.4800 - rmse: 0.6014 - smape: 0.8302 - val_ia: 0.3705 - val_loss: 0.9429 - val_mae: 0.8105 - val_rmse: 0.9170 - val_smape: 1.2472

Epoch 5/128

573/573 - 8s - 13ms/step - ia: 0.6946 - loss: 0.3437 - mae: 0.4653 - rmse: 0.5839 - smape: 0.8080 - val_ia: 0.3867 - val_loss: 0.8792 - val_mae: 0.7782 - val_rmse: 0.8843 - val_smape: 1.2052

Epoch 6/128

573/573 - 8s - 14ms/step - ia: 0.7030 - loss: 0.3311 - mae: 0.4560 - rmse: 0.5730 - smape: 0.7932 - val_ia: 0.3890 - val_loss: 0.8825 - val_mae: 0.7825 - val_rmse: 0.8853 - val_smape: 1.2129

Epoch 7/128

573/573 - 8s - 14ms/step - ia: 0.7091 - loss: 0.3210 - mae: 0.4481 - rmse: 0.5647 - smape: 0.7809 - val_ia: 0.4126 - val_loss: 0.7789 - val_mae: 0.7279 - val_rmse: 0.8297 - val_smape: 1.1614

Epoch 8/128

573/573 - 8s - 14ms/step - ia: 0.7144 - loss: 0.3118 - mae: 0.4411 - rmse: 0.5562 - smape: 0.7731 - val_ia: 0.4240 - val_loss: 0.7457 - val_mae: 0.7118 - val_rmse: 0.8107 - val_smape: 1.1470

Epoch 9/128

573/573 - 8s - 14ms/step - ia: 0.7198 - loss: 0.3032 - mae: 0.4335 - rmse: 0.5482 - smape: 0.7631 - val_ia: 0.4380 - val_loss: 0.7047 - val_mae: 0.6854 - val_rmse: 0.7866 - val_smape: 1.1195

Epoch 10/128

573/573 - 8s - 13ms/step - ia: 0.7246 - loss: 0.2955 - mae: 0.4272 - rmse: 0.5414 - smape: 0.7564 - val_ia: 0.4495 - val_loss: 0.6638 - val_mae: 0.6642 - val_rmse: 0.7627 - val_smape: 1.1012

Epoch 11/128

573/573 - 8s - 14ms/step - ia: 0.7281 - loss: 0.2884 - mae: 0.4212 - rmse: 0.5345 - smape: 0.7502 - val_ia: 0.4620 - val_loss: 0.6179 - val_mae: 0.6396 - val_rmse: 0.7369 - val_smape: 1.0821

Epoch 12/128

573/573 - 8s - 14ms/step - ia: 0.7326 - loss: 0.2817 - mae: 0.4154 - rmse: 0.5286 - smape: 0.7430 - val_ia: 0.4589 - val_loss: 0.6600 - val_mae: 0.6603 - val_rmse: 0.7584 - val_smape: 1.0906

Epoch 13/128

573/573 - 8s - 14ms/step - ia: 0.7359 - loss: 0.2752 - mae: 0.4101 - rmse: 0.5223 - smape: 0.7374 - val_ia: 0.4679 - val_loss: 0.6294 - val_mae: 0.6445 - val_rmse: 0.7400 - val_smape: 1.0771

Epoch 14/128

573/573 - 7s - 13ms/step - ia: 0.7396 - loss: 0.2690 - mae: 0.4050 - rmse: 0.5163 - smape: 0.7328 - val_ia: 0.4793 - val_loss: 0.5853 - val_mae: 0.6220 - val_rmse: 0.7134 - val_smape: 1.0562

Epoch 15/128

573/573 - 8s - 14ms/step - ia: 0.7433 - loss: 0.2631 - mae: 0.4002 - rmse: 0.5106 - smape: 0.7286 - val_ia: 0.4853 - val_loss: 0.5842 - val_mae: 0.6203 - val_rmse: 0.7099 - val_smape: 1.0455

Epoch 16/128

573/573 - 8s - 14ms/step - ia: 0.7464 - loss: 0.2575 - mae: 0.3955 - rmse: 0.5054 - smape: 0.7250 - val_ia: 0.4951 - val_loss: 0.5492 - val_mae: 0.6012 - val_rmse: 0.6880 - val_smape: 1.0279

Epoch 17/128

573/573 - 8s - 14ms/step - ia: 0.7493 - loss: 0.2526 - mae: 0.3914 - rmse: 0.5004 - smape: 0.7224 - val_ia: 0.4969 - val_loss: 0.5627 - val_mae: 0.6057 - val_rmse: 0.6922 - val_smape: 1.0275

Epoch 18/128

573/573 - 8s - 13ms/step - ia: 0.7522 - loss: 0.2474 - mae: 0.3869 - rmse: 0.4951 - smape: 0.7192 - val_ia: 0.5065 - val_loss: 0.5246 - val_mae: 0.5844 - val_rmse: 0.6694 - val_smape: 1.0101

Epoch 19/128

573/573 - 8s - 14ms/step - ia: 0.7547 - loss: 0.2426 - mae: 0.3826 - rmse: 0.4902 - smape: 0.7159 - val_ia: 0.5093 - val_loss: 0.5271 - val_mae: 0.5828 - val_rmse: 0.6697 - val_smape: 1.0052

Epoch 20/128

573/573 - 9s - 16ms/step - ia: 0.7575 - loss: 0.2379 - mae: 0.3785 - rmse: 0.4854 - smape: 0.7135 - val_ia: 0.5103 - val_loss: 0.5479 - val_mae: 0.5915 - val_rmse: 0.6789 - val_smape: 1.0071

Epoch 21/128

573/573 - 8s - 14ms/step - ia: 0.7603 - loss: 0.2338 - mae: 0.3745 - rmse: 0.4812 - smape: 0.7098 - val_ia: 0.5183 - val_loss: 0.5213 - val_mae: 0.5751 - val_rmse: 0.6628 - val_smape: 0.9930

Epoch 22/128

573/573 - 8s - 14ms/step - ia: 0.7624 - loss: 0.2302 - mae: 0.3710 - rmse: 0.4774 - smape: 0.7081 - val_ia: 0.5256 - val_loss: 0.5123 - val_mae: 0.5687 - val_rmse: 0.6555 - val_smape: 0.9795

Epoch 23/128

573/573 - 8s - 14ms/step - ia: 0.7653 - loss: 0.2258 - mae: 0.3670 - rmse: 0.4729 - smape: 0.7047 - val_ia: 0.5267 - val_loss: 0.5193 - val_mae: 0.5702 - val_rmse: 0.6560 - val_smape: 0.9830

Epoch 24/128

573/573 - 8s - 14ms/step - ia: 0.7669 - loss: 0.2220 - mae: 0.3632 - rmse: 0.4688 - smape: 0.7024 - val_ia: 0.5256 - val_loss: 0.5568 - val_mae: 0.5881 - val_rmse: 0.6719 - val_smape: 0.9879

Epoch 25/128

573/573 - 8s - 14ms/step - ia: 0.7695 - loss: 0.2184 - mae: 0.3598 - rmse: 0.4650 - smape: 0.6994 - val_ia: 0.5397 - val_loss: 0.4845 - val_mae: 0.5498 - val_rmse: 0.6342 - val_smape: 0.9624

Epoch 26/128

573/573 - 8s - 14ms/step - ia: 0.7713 - loss: 0.2145 - mae: 0.3565 - rmse: 0.4610 - smape: 0.6967 - val_ia: 0.5413 - val_loss: 0.4940 - val_mae: 0.5546 - val_rmse: 0.6353 - val_smape: 0.9618

Epoch 27/128

573/573 - 8s - 15ms/step - ia: 0.7739 - loss: 0.2106 - mae: 0.3526 - rmse: 0.4565 - smape: 0.6938 - val_ia: 0.5378 - val_loss: 0.5069 - val_mae: 0.5587 - val_rmse: 0.6439 - val_smape: 0.9731

Epoch 28/128

573/573 - 9s - 16ms/step - ia: 0.7762 - loss: 0.2067 - mae: 0.3487 - rmse: 0.4522 - smape: 0.6891 - val_ia: 0.5496 - val_loss: 0.4755 - val_mae: 0.5415 - val_rmse: 0.6237 - val_smape: 0.9514

Epoch 29/128

573/573 - 9s - 15ms/step - ia: 0.7791 - loss: 0.2028 - mae: 0.3448 - rmse: 0.4480 - smape: 0.6849 - val_ia: 0.5494 - val_loss: 0.4822 - val_mae: 0.5427 - val_rmse: 0.6271 - val_smape: 0.9525

Epoch 30/128

573/573 - 8s - 13ms/step - ia: 0.7811 - loss: 0.1991 - mae: 0.3412 - rmse: 0.4438 - smape: 0.6815 - val_ia: 0.5545 - val_loss: 0.4897 - val_mae: 0.5468 - val_rmse: 0.6282 - val_smape: 0.9366

Epoch 31/128

573/573 - 8s - 14ms/step - ia: 0.7846 - loss: 0.1942 - mae: 0.3362 - rmse: 0.4381 - smape: 0.6746 - val_ia: 0.5633 - val_loss: 0.4584 - val_mae: 0.5300 - val_rmse: 0.6108 - val_smape: 0.9193

Epoch 32/128

573/573 - 8s - 14ms/step - ia: 0.7869 - loss: 0.1903 - mae: 0.3326 - rmse: 0.4338 - smape: 0.6717 - val_ia: 0.5710 - val_loss: 0.4181 - val_mae: 0.5080 - val_rmse: 0.5878 - val_smape: 0.9087

Epoch 33/128

573/573 - 8s - 14ms/step - ia: 0.7900 - loss: 0.1855 - mae: 0.3276 - rmse: 0.4282 - smape: 0.6645 - val_ia: 0.5830 - val_loss: 0.3692 - val_mae: 0.4803 - val_rmse: 0.5615 - val_smape: 0.8955

Epoch 34/128

573/573 - 7s - 13ms/step - ia: 0.7932 - loss: 0.1805 - mae: 0.3226 - rmse: 0.4223 - smape: 0.6590 - val_ia: 0.5934 - val_loss: 0.3705 - val_mae: 0.4802 - val_rmse: 0.5561 - val_smape: 0.8549

Epoch 35/128

573/573 - 8s - 14ms/step - ia: 0.7962 - loss: 0.1760 - mae: 0.3185 - rmse: 0.4171 - smape: 0.6556 - val_ia: 0.6001 - val_loss: 0.3402 - val_mae: 0.4598 - val_rmse: 0.5398 - val_smape: 0.8527

Epoch 36/128

573/573 - 8s - 13ms/step - ia: 0.8000 - loss: 0.1706 - mae: 0.3133 - rmse: 0.4107 - smape: 0.6494 - val_ia: 0.6033 - val_loss: 0.3372 - val_mae: 0.4570 - val_rmse: 0.5394 - val_smape: 0.8536

Epoch 37/128

573/573 - 8s - 14ms/step - ia: 0.8039 - loss: 0.1645 - mae: 0.3071 - rmse: 0.4032 - smape: 0.6426 - val_ia: 0.6215 - val_loss: 0.3034 - val_mae: 0.4336 - val_rmse: 0.5127 - val_smape: 0.8152

Epoch 38/128

573/573 - 8s - 14ms/step - ia: 0.8083 - loss: 0.1587 - mae: 0.3009 - rmse: 0.3961 - smape: 0.6359 - val_ia: 0.6235 - val_loss: 0.2865 - val_mae: 0.4224 - val_rmse: 0.5035 - val_smape: 0.8258

Epoch 39/128

573/573 - 8s - 14ms/step - ia: 0.8124 - loss: 0.1521 - mae: 0.2944 - rmse: 0.3877 - smape: 0.6293 - val_ia: 0.6393 - val_loss: 0.2662 - val_mae: 0.4056 - val_rmse: 0.4850 - val_smape: 0.7922

Epoch 40/128

573/573 - 8s - 15ms/step - ia: 0.8174 - loss: 0.1452 - mae: 0.2869 - rmse: 0.3788 - smape: 0.6218 - val_ia: 0.6575 - val_loss: 0.2276 - val_mae: 0.3747 - val_rmse: 0.4532 - val_smape: 0.7771

Epoch 41/128

573/573 - 8s - 14ms/step - ia: 0.8226 - loss: 0.1381 - mae: 0.2792 - rmse: 0.3695 - smape: 0.6129 - val_ia: 0.6622 - val_loss: 0.2237 - val_mae: 0.3704 - val_rmse: 0.4484 - val_smape: 0.7673

Epoch 42/128

573/573 - 8s - 14ms/step - ia: 0.8269 - loss: 0.1317 - mae: 0.2724 - rmse: 0.3604 - smape: 0.6063 - val_ia: 0.6775 - val_loss: 0.1997 - val_mae: 0.3476 - val_rmse: 0.4253 - val_smape: 0.7482

Epoch 43/128

573/573 - 8s - 13ms/step - ia: 0.8307 - loss: 0.1268 - mae: 0.2669 - rmse: 0.3535 - smape: 0.6000 - val_ia: 0.6825 - val_loss: 0.1942 - val_mae: 0.3416 - val_rmse: 0.4200 - val_smape: 0.7421

Epoch 44/128

573/573 - 8s - 14ms/step - ia: 0.8338 - loss: 0.1224 - mae: 0.2621 - rmse: 0.3477 - smape: 0.5965 - val_ia: 0.6786 - val_loss: 0.1943 - val_mae: 0.3423 - val_rmse: 0.4214 - val_smape: 0.7583

Epoch 45/128

573/573 - 8s - 14ms/step - ia: 0.8364 - loss: 0.1190 - mae: 0.2582 - rmse: 0.3427 - smape: 0.5932 - val_ia: 0.6890 - val_loss: 0.1802 - val_mae: 0.3276 - val_rmse: 0.4061 - val_smape: 0.7426

Epoch 46/128

573/573 - 8s - 14ms/step - ia: 0.8393 - loss: 0.1153 - mae: 0.2539 - rmse: 0.3372 - smape: 0.5865 - val_ia: 0.6890 - val_loss: 0.1850 - val_mae: 0.3321 - val_rmse: 0.4109 - val_smape: 0.7351

Epoch 47/128

573/573 - 7s - 13ms/step - ia: 0.8414 - loss: 0.1123 - mae: 0.2505 - rmse: 0.3329 - smape: 0.5817 - val_ia: 0.6901 - val_loss: 0.1861 - val_mae: 0.3336 - val_rmse: 0.4119 - val_smape: 0.7318

Epoch 48/128

573/573 - 8s - 14ms/step - ia: 0.8437 - loss: 0.1095 - mae: 0.2470 - rmse: 0.3285 - smape: 0.5769 - val_ia: 0.7010 - val_loss: 0.1712 - val_mae: 0.3179 - val_rmse: 0.3955 - val_smape: 0.7104

Epoch 49/128

573/573 - 9s - 15ms/step - ia: 0.8452 - loss: 0.1077 - mae: 0.2449 - rmse: 0.3258 - smape: 0.5748 - val_ia: 0.7039 - val_loss: 0.1663 - val_mae: 0.3126 - val_rmse: 0.3898 - val_smape: 0.7047

Epoch 50/128

573/573 - 8s - 13ms/step - ia: 0.8474 - loss: 0.1050 - mae: 0.2414 - rmse: 0.3219 - smape: 0.5697 - val_ia: 0.6925 - val_loss: 0.1850 - val_mae: 0.3331 - val_rmse: 0.4097 - val_smape: 0.7170

Epoch 51/128

573/573 - 7s - 13ms/step - ia: 0.8488 - loss: 0.1032 - mae: 0.2392 - rmse: 0.3190 - smape: 0.5659 - val_ia: 0.7075 - val_loss: 0.1657 - val_mae: 0.3125 - val_rmse: 0.3890 - val_smape: 0.6981

Epoch 52/128

573/573 - 8s - 13ms/step - ia: 0.8503 - loss: 0.1014 - mae: 0.2372 - rmse: 0.3160 - smape: 0.5622 - val_ia: 0.7168 - val_loss: 0.1537 - val_mae: 0.2997 - val_rmse: 0.3750 - val_smape: 0.6687

Epoch 53/128

573/573 - 8s - 14ms/step - ia: 0.8518 - loss: 0.0995 - mae: 0.2347 - rmse: 0.3132 - smape: 0.5598 - val_ia: 0.7181 - val_loss: 0.1507 - val_mae: 0.2971 - val_rmse: 0.3725 - val_smape: 0.6783

Epoch 54/128

573/573 - 8s - 13ms/step - ia: 0.8532 - loss: 0.0979 - mae: 0.2325 - rmse: 0.3106 - smape: 0.5562 - val_ia: 0.7135 - val_loss: 0.1569 - val_mae: 0.3045 - val_rmse: 0.3784 - val_smape: 0.6794

Epoch 55/128

573/573 - 8s - 14ms/step - ia: 0.8549 - loss: 0.0959 - mae: 0.2301 - rmse: 0.3074 - smape: 0.5528 - val_ia: 0.7151 - val_loss: 0.1559 - val_mae: 0.3030 - val_rmse: 0.3781 - val_smape: 0.6802

Epoch 56/128

573/573 - 8s - 13ms/step - ia: 0.8555 - loss: 0.0949 - mae: 0.2290 - rmse: 0.3057 - smape: 0.5516 - val_ia: 0.7126 - val_loss: 0.1631 - val_mae: 0.3107 - val_rmse: 0.3854 - val_smape: 0.6726

Epoch 57/128

573/573 - 8s - 14ms/step - ia: 0.8566 - loss: 0.0937 - mae: 0.2275 - rmse: 0.3039 - smape: 0.5497 - val_ia: 0.7165 - val_loss: 0.1597 - val_mae: 0.3092 - val_rmse: 0.3800 - val_smape: 0.6645

Epoch 58/128

573/573 - 8s - 13ms/step - ia: 0.8576 - loss: 0.0924 - mae: 0.2258 - rmse: 0.3019 - smape: 0.5460 - val_ia: 0.7234 - val_loss: 0.1478 - val_mae: 0.2949 - val_rmse: 0.3683 - val_smape: 0.6598

Epoch 59/128

573/573 - 7s - 13ms/step - ia: 0.8586 - loss: 0.0912 - mae: 0.2242 - rmse: 0.2997 - smape: 0.5453 - val_ia: 0.7275 - val_loss: 0.1408 - val_mae: 0.2861 - val_rmse: 0.3607 - val_smape: 0.6628

Epoch 60/128

573/573 - 8s - 14ms/step - ia: 0.8590 - loss: 0.0905 - mae: 0.2236 - rmse: 0.2986 - smape: 0.5454 - val_ia: 0.7147 - val_loss: 0.1613 - val_mae: 0.3122 - val_rmse: 0.3821 - val_smape: 0.6682

Epoch 61/128

573/573 - 8s - 13ms/step - ia: 0.8600 - loss: 0.0896 - mae: 0.2221 - rmse: 0.2969 - smape: 0.5432 - val_ia: 0.7222 - val_loss: 0.1490 - val_mae: 0.2962 - val_rmse: 0.3699 - val_smape: 0.6636

Epoch 62/128

573/573 - 8s - 14ms/step - ia: 0.8611 - loss: 0.0883 - mae: 0.2205 - rmse: 0.2949 - smape: 0.5390 - val_ia: 0.7205 - val_loss: 0.1525 - val_mae: 0.3018 - val_rmse: 0.3735 - val_smape: 0.6620

Epoch 63/128

573/573 - 7s - 13ms/step - ia: 0.8614 - loss: 0.0881 - mae: 0.2202 - rmse: 0.2948 - smape: 0.5393 - val_ia: 0.7286 - val_loss: 0.1421 - val_mae: 0.2889 - val_rmse: 0.3615 - val_smape: 0.6477

Epoch 64/128

573/573 - 8s - 13ms/step - ia: 0.8623 - loss: 0.0868 - mae: 0.2184 - rmse: 0.2925 - smape: 0.5363 - val_ia: 0.7282 - val_loss: 0.1419 - val_mae: 0.2908 - val_rmse: 0.3599 - val_smape: 0.6456

Epoch 65/128

573/573 - 8s - 13ms/step - ia: 0.8628 - loss: 0.0863 - mae: 0.2179 - rmse: 0.2916 - smape: 0.5351 - val_ia: 0.7272 - val_loss: 0.1404 - val_mae: 0.2867 - val_rmse: 0.3591 - val_smape: 0.6536

Epoch 66/128

573/573 - 8s - 14ms/step - ia: 0.8635 - loss: 0.0854 - mae: 0.2167 - rmse: 0.2900 - smape: 0.5348 - val_ia: 0.7362 - val_loss: 0.1347 - val_mae: 0.2808 - val_rmse: 0.3515 - val_smape: 0.6305

Epoch 67/128

573/573 - 8s - 13ms/step - ia: 0.8643 - loss: 0.0847 - mae: 0.2156 - rmse: 0.2889 - smape: 0.5318 - val_ia: 0.7201 - val_loss: 0.1539 - val_mae: 0.3056 - val_rmse: 0.3734 - val_smape: 0.6587

Epoch 68/128

573/573 - 7s - 13ms/step - ia: 0.8645 - loss: 0.0845 - mae: 0.2152 - rmse: 0.2883 - smape: 0.5310 - val_ia: 0.7276 - val_loss: 0.1415 - val_mae: 0.2907 - val_rmse: 0.3595 - val_smape: 0.6486

Epoch 69/128

573/573 - 8s - 14ms/step - ia: 0.8648 - loss: 0.0840 - mae: 0.2145 - rmse: 0.2876 - smape: 0.5308 - val_ia: 0.7341 - val_loss: 0.1362 - val_mae: 0.2837 - val_rmse: 0.3534 - val_smape: 0.6383

Epoch 70/128

573/573 - 8s - 13ms/step - ia: 0.8655 - loss: 0.0833 - mae: 0.2138 - rmse: 0.2864 - smape: 0.5279 - val_ia: 0.7250 - val_loss: 0.1506 - val_mae: 0.3022 - val_rmse: 0.3685 - val_smape: 0.6537

Epoch 71/128

573/573 - 8s - 15ms/step - ia: 0.8655 - loss: 0.0830 - mae: 0.2134 - rmse: 0.2859 - smape: 0.5285 - val_ia: 0.7449 - val_loss: 0.1244 - val_mae: 0.2692 - val_rmse: 0.3395 - val_smape: 0.6218

Epoch 72/128

573/573 - 8s - 14ms/step - ia: 0.8665 - loss: 0.0821 - mae: 0.2120 - rmse: 0.2842 - smape: 0.5264 - val_ia: 0.7320 - val_loss: 0.1379 - val_mae: 0.2873 - val_rmse: 0.3538 - val_smape: 0.6400

Epoch 73/128

573/573 - 8s - 14ms/step - ia: 0.8669 - loss: 0.0817 - mae: 0.2116 - rmse: 0.2836 - smape: 0.5256 - val_ia: 0.7105 - val_loss: 0.1629 - val_mae: 0.3183 - val_rmse: 0.3825 - val_smape: 0.6827

Epoch 74/128

573/573 - 8s - 14ms/step - ia: 0.8668 - loss: 0.0817 - mae: 0.2116 - rmse: 0.2834 - smape: 0.5269 - val_ia: 0.7324 - val_loss: 0.1378 - val_mae: 0.2868 - val_rmse: 0.3546 - val_smape: 0.6372

Epoch 75/128

573/573 - 8s - 14ms/step - ia: 0.8677 - loss: 0.0809 - mae: 0.2106 - rmse: 0.2822 - smape: 0.5244 - val_ia: 0.7290 - val_loss: 0.1388 - val_mae: 0.2883 - val_rmse: 0.3548 - val_smape: 0.6472

Epoch 76/128

573/573 - 7s - 13ms/step - ia: 0.8680 - loss: 0.0806 - mae: 0.2098 - rmse: 0.2816 - smape: 0.5243 - val_ia: 0.7455 - val_loss: 0.1229 - val_mae: 0.2679 - val_rmse: 0.3377 - val_smape: 0.6155

Epoch 77/128

573/573 - 8s - 14ms/step - ia: 0.8682 - loss: 0.0801 - mae: 0.2092 - rmse: 0.2808 - smape: 0.5227 - val_ia: 0.7391 - val_loss: 0.1310 - val_mae: 0.2782 - val_rmse: 0.3461 - val_smape: 0.6263

Epoch 78/128

573/573 - 8s - 14ms/step - ia: 0.8684 - loss: 0.0797 - mae: 0.2090 - rmse: 0.2801 - smape: 0.5228 - val_ia: 0.7382 - val_loss: 0.1303 - val_mae: 0.2778 - val_rmse: 0.3451 - val_smape: 0.6271

Epoch 79/128

573/573 - 8s - 14ms/step - ia: 0.8687 - loss: 0.0797 - mae: 0.2087 - rmse: 0.2801 - smape: 0.5216 - val_ia: 0.7398 - val_loss: 0.1294 - val_mae: 0.2767 - val_rmse: 0.3420 - val_smape: 0.6213

Epoch 80/128

573/573 - 8s - 13ms/step - ia: 0.8691 - loss: 0.0792 - mae: 0.2081 - rmse: 0.2790 - smape: 0.5218 - val_ia: 0.7361 - val_loss: 0.1338 - val_mae: 0.2820 - val_rmse: 0.3490 - val_smape: 0.6329

Epoch 81/128

573/573 - 8s - 14ms/step - ia: 0.8694 - loss: 0.0788 - mae: 0.2078 - rmse: 0.2785 - smape: 0.5192 - val_ia: 0.7307 - val_loss: 0.1409 - val_mae: 0.2908 - val_rmse: 0.3555 - val_smape: 0.6421

Epoch 82/128

573/573 - 8s - 14ms/step - ia: 0.8700 - loss: 0.0782 - mae: 0.2066 - rmse: 0.2773 - smape: 0.5175 - val_ia: 0.7327 - val_loss: 0.1368 - val_mae: 0.2861 - val_rmse: 0.3509 - val_smape: 0.6387

Epoch 83/128

573/573 - 8s - 14ms/step - ia: 0.8697 - loss: 0.0784 - mae: 0.2072 - rmse: 0.2776 - smape: 0.5200 - val_ia: 0.7366 - val_loss: 0.1339 - val_mae: 0.2820 - val_rmse: 0.3477 - val_smape: 0.6279

Epoch 84/128

573/573 - 8s - 13ms/step - ia: 0.8700 - loss: 0.0780 - mae: 0.2066 - rmse: 0.2772 - smape: 0.5169 - val_ia: 0.7471 - val_loss: 0.1197 - val_mae: 0.2656 - val_rmse: 0.3322 - val_smape: 0.6046

Epoch 85/128

573/573 - 8s - 14ms/step - ia: 0.8708 - loss: 0.0775 - mae: 0.2057 - rmse: 0.2762 - smape: 0.5160 - val_ia: 0.7411 - val_loss: 0.1295 - val_mae: 0.2767 - val_rmse: 0.3420 - val_smape: 0.6214

Epoch 86/128

573/573 - 9s - 15ms/step - ia: 0.8710 - loss: 0.0771 - mae: 0.2052 - rmse: 0.2757 - smape: 0.5158 - val_ia: 0.7408 - val_loss: 0.1292 - val_mae: 0.2763 - val_rmse: 0.3413 - val_smape: 0.6191

Epoch 87/128

573/573 - 8s - 14ms/step - ia: 0.8713 - loss: 0.0768 - mae: 0.2049 - rmse: 0.2750 - smape: 0.5147 - val_ia: 0.7342 - val_loss: 0.1359 - val_mae: 0.2845 - val_rmse: 0.3483 - val_smape: 0.6346

Epoch 88/128

573/573 - 8s - 14ms/step - ia: 0.8715 - loss: 0.0765 - mae: 0.2044 - rmse: 0.2747 - smape: 0.5153 - val_ia: 0.7397 - val_loss: 0.1318 - val_mae: 0.2793 - val_rmse: 0.3449 - val_smape: 0.6264

Epoch 89/128

573/573 - 8s - 14ms/step - ia: 0.8715 - loss: 0.0765 - mae: 0.2046 - rmse: 0.2745 - smape: 0.5141 - val_ia: 0.7477 - val_loss: 0.1229 - val_mae: 0.2692 - val_rmse: 0.3335 - val_smape: 0.6031

Epoch 90/128

573/573 - 8s - 14ms/step - ia: 0.8716 - loss: 0.0763 - mae: 0.2044 - rmse: 0.2742 - smape: 0.5152 - val_ia: 0.7301 - val_loss: 0.1451 - val_mae: 0.2944 - val_rmse: 0.3583 - val_smape: 0.6452

Epoch 91/128

573/573 - 8s - 14ms/step - ia: 0.8718 - loss: 0.0759 - mae: 0.2038 - rmse: 0.2732 - smape: 0.5134 - val_ia: 0.7341 - val_loss: 0.1364 - val_mae: 0.2845 - val_rmse: 0.3504 - val_smape: 0.6340

Epoch 92/128

573/573 - 8s - 13ms/step - ia: 0.8726 - loss: 0.0755 - mae: 0.2029 - rmse: 0.2726 - smape: 0.5122 - val_ia: 0.7357 - val_loss: 0.1362 - val_mae: 0.2840 - val_rmse: 0.3479 - val_smape: 0.6256

Epoch 93/128

573/573 - 8s - 14ms/step - ia: 0.8720 - loss: 0.0757 - mae: 0.2035 - rmse: 0.2729 - smape: 0.5140 - val_ia: 0.7381 - val_loss: 0.1354 - val_mae: 0.2831 - val_rmse: 0.3472 - val_smape: 0.6221

Epoch 94/128

573/573 - 8s - 14ms/step - ia: 0.8730 - loss: 0.0748 - mae: 0.2021 - rmse: 0.2714 - smape: 0.5092 - val_ia: 0.7407 - val_loss: 0.1314 - val_mae: 0.2783 - val_rmse: 0.3430 - val_smape: 0.6165

Epoch 95/128

573/573 - 8s - 14ms/step - ia: 0.8727 - loss: 0.0750 - mae: 0.2025 - rmse: 0.2715 - smape: 0.5113 - val_ia: 0.7415 - val_loss: 0.1304 - val_mae: 0.2766 - val_rmse: 0.3428 - val_smape: 0.6167

Epoch 96/128

573/573 - 8s - 13ms/step - ia: 0.8733 - loss: 0.0744 - mae: 0.2017 - rmse: 0.2705 - smape: 0.5092 - val_ia: 0.7326 - val_loss: 0.1394 - val_mae: 0.2872 - val_rmse: 0.3527 - val_smape: 0.6332

Epoch 97/128

573/573 - 8s - 13ms/step - ia: 0.8737 - loss: 0.0740 - mae: 0.2012 - rmse: 0.2697 - smape: 0.5084 - val_ia: 0.7305 - val_loss: 0.1410 - val_mae: 0.2900 - val_rmse: 0.3531 - val_smape: 0.6396

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1146/1146 - 24s - 21ms/step - ia: 0.7456 - loss: 0.2387 - mae: 0.3711 - rmse: 0.4712 - smape: 0.7481 - val_ia: 0.4139 - val_loss: 0.3438 - val_mae: 0.4688 - val_rmse: 0.5269 - val_smape: 0.9506

Epoch 2/32

1146/1146 - 17s - 15ms/step - ia: 0.8402 - loss: 0.1103 - mae: 0.2480 - rmse: 0.3267 - smape: 0.5895 - val_ia: 0.5267 - val_loss: 0.1528 - val_mae: 0.3124 - val_rmse: 0.3542 - val_smape: 0.7195

Epoch 3/32

1146/1146 - 17s - 15ms/step - ia: 0.8595 - loss: 0.0883 - mae: 0.2191 - rmse: 0.2920 - smape: 0.5403 - val_ia: 0.5190 - val_loss: 0.2043 - val_mae: 0.3413 - val_rmse: 0.3859 - val_smape: 0.7269

Epoch 4/32

1146/1146 - 17s - 15ms/step - ia: 0.8709 - loss: 0.0755 - mae: 0.2022 - rmse: 0.2698 - smape: 0.5042 - val_ia: 0.5024 - val_loss: 0.2135 - val_mae: 0.3577 - val_rmse: 0.4058 - val_smape: 0.7500

Epoch 5/32

1146/1146 - 18s - 15ms/step - ia: 0.8774 - loss: 0.0685 - mae: 0.1926 - rmse: 0.2571 - smape: 0.4844 - val_ia: 0.5089 - val_loss: 0.2131 - val_mae: 0.3522 - val_rmse: 0.4034 - val_smape: 0.7307

Epoch 6/32

1146/1146 - 17s - 15ms/step - ia: 0.8833 - loss: 0.0627 - mae: 0.1843 - rmse: 0.2461 - smape: 0.4682 - val_ia: 0.4955 - val_loss: 0.2637 - val_mae: 0.3830 - val_rmse: 0.4413 - val_smape: 0.7696

Epoch 7/32

1146/1146 - 17s - 15ms/step - ia: 0.8862 - loss: 0.0594 - mae: 0.1796 - rmse: 0.2393 - smape: 0.4574 - val_ia: 0.4717 - val_loss: 0.3402 - val_mae: 0.4349 - val_rmse: 0.4977 - val_smape: 0.8079

Epoch 8/32

1146/1146 - 15s - 13ms/step - ia: 0.8890 - loss: 0.0571 - mae: 0.1757 - rmse: 0.2343 - smape: 0.4499 - val_ia: 0.4961 - val_loss: 0.2149 - val_mae: 0.3580 - val_rmse: 0.4090 - val_smape: 0.7596

Epoch 9/32

1146/1146 - 16s - 14ms/step - ia: 0.8922 - loss: 0.0541 - mae: 0.1704 - rmse: 0.2283 - smape: 0.4409 - val_ia: 0.4867 - val_loss: 0.2783 - val_mae: 0.4034 - val_rmse: 0.4573 - val_smape: 0.7952

Epoch 10/32

1146/1146 - 16s - 14ms/step - ia: 0.8941 - loss: 0.0521 - mae: 0.1675 - rmse: 0.2239 - smape: 0.4349 - val_ia: 0.4940 - val_loss: 0.2558 - val_mae: 0.3831 - val_rmse: 0.4354 - val_smape: 0.7769

Epoch 11/32

1146/1146 - 16s - 14ms/step - ia: 0.8960 - loss: 0.0503 - mae: 0.1651 - rmse: 0.2202 - smape: 0.4298 - val_ia: 0.5086 - val_loss: 0.2498 - val_mae: 0.3780 - val_rmse: 0.4232 - val_smape: 0.7560

Epoch 12/32

1146/1146 - 17s - 15ms/step - ia: 0.8973 - loss: 0.0490 - mae: 0.1628 - rmse: 0.2172 - smape: 0.4250 - val_ia: 0.4875 - val_loss: 0.2427 - val_mae: 0.3783 - val_rmse: 0.4298 - val_smape: 0.7823

Epoch 13/32

1146/1146 - 17s - 14ms/step - ia: 0.9000 - loss: 0.0470 - mae: 0.1585 - rmse: 0.2122 - smape: 0.4169 - val_ia: 0.5035 - val_loss: 0.2136 - val_mae: 0.3513 - val_rmse: 0.4031 - val_smape: 0.7458

Epoch 14/32

1146/1146 - 17s - 14ms/step - ia: 0.9015 - loss: 0.0455 - mae: 0.1565 - rmse: 0.2091 - smape: 0.4118 - val_ia: 0.4782 - val_loss: 0.2706 - val_mae: 0.3995 - val_rmse: 0.4510 - val_smape: 0.8008

Epoch 15/32

1146/1146 - 17s - 15ms/step - ia: 0.9022 - loss: 0.0448 - mae: 0.1551 - rmse: 0.2073 - smape: 0.4106 - val_ia: 0.4836 - val_loss: 0.2243 - val_mae: 0.3712 - val_rmse: 0.4215 - val_smape: 0.7733

Epoch 16/32

1146/1146 - 17s - 15ms/step - ia: 0.9036 - loss: 0.0438 - mae: 0.1528 - rmse: 0.2051 - smape: 0.4048 - val_ia: 0.4732 - val_loss: 0.2721 - val_mae: 0.3973 - val_rmse: 0.4563 - val_smape: 0.8054

Epoch 17/32

1146/1146 - 15s - 13ms/step - ia: 0.9043 - loss: 0.0433 - mae: 0.1516 - rmse: 0.2038 - smape: 0.4022 - val_ia: 0.5024 - val_loss: 0.2223 - val_mae: 0.3560 - val_rmse: 0.4097 - val_smape: 0.7460

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:17 481ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/64

 80%|████████  | 40/50 [10:55:35<1:39:13, 595.35s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 14s - 99ms/step - ia: 0.4260 - loss: 0.7349 - mae: 0.6874 - rmse: 0.8388 - smape: 1.2253 - val_ia: 0.5008 - val_loss: 0.7700 - val_mae: 0.7314 - val_rmse: 0.8404 - val_smape: 1.2153

Epoch 2/64

144/144 - 2s - 16ms/step - ia: 0.6910 - loss: 0.3474 - mae: 0.4667 - rmse: 0.5879 - smape: 0.8309 - val_ia: 0.6090 - val_loss: 0.4969 - val_mae: 0.5634 - val_rmse: 0.6787 - val_smape: 1.0193

Epoch 3/64

144/144 - 2s - 15ms/step - ia: 0.7418 - loss: 0.2542 - mae: 0.3930 - rmse: 0.5031 - smape: 0.7769 - val_ia: 0.6945 - val_loss: 0.3220 - val_mae: 0.4477 - val_rmse: 0.5445 - val_smape: 0.8884

Epoch 4/64

144/144 - 2s - 14ms/step - ia: 0.7659 - loss: 0.2107 - mae: 0.3572 - rmse: 0.4584 - smape: 0.7443 - val_ia: 0.7120 - val_loss: 0.2482 - val_mae: 0.4048 - val_rmse: 0.4871 - val_smape: 0.8486

Epoch 5/64

144/144 - 2s - 14ms/step - ia: 0.7711 - loss: 0.2029 - mae: 0.3500 - rmse: 0.4497 - smape: 0.7315 - val_ia: 0.7317 - val_loss: 0.1966 - val_mae: 0.3689 - val_rmse: 0.4336 - val_smape: 0.8213

Epoch 6/64

144/144 - 2s - 16ms/step - ia: 0.7747 - loss: 0.1968 - mae: 0.3445 - rmse: 0.4429 - smape: 0.7235 - val_ia: 0.7348 - val_loss: 0.1862 - val_mae: 0.3600 - val_rmse: 0.4205 - val_smape: 0.8057

Epoch 7/64

144/144 - 2s - 16ms/step - ia: 0.7799 - loss: 0.1895 - mae: 0.3373 - rmse: 0.4345 - smape: 0.7162 - val_ia: 0.7182 - val_loss: 0.2272 - val_mae: 0.3910 - val_rmse: 0.4618 - val_smape: 0.8320

Epoch 8/64

144/144 - 2s - 16ms/step - ia: 0.7828 - loss: 0.1849 - mae: 0.3336 - rmse: 0.4291 - smape: 0.7115 - val_ia: 0.7169 - val_loss: 0.2186 - val_mae: 0.3897 - val_rmse: 0.4559 - val_smape: 0.8384

Epoch 9/64

144/144 - 2s - 16ms/step - ia: 0.7907 - loss: 0.1734 - mae: 0.3225 - rmse: 0.4156 - smape: 0.7017 - val_ia: 0.7218 - val_loss: 0.2177 - val_mae: 0.3862 - val_rmse: 0.4522 - val_smape: 0.8107

Epoch 10/64

144/144 - 2s - 15ms/step - ia: 0.7949 - loss: 0.1678 - mae: 0.3160 - rmse: 0.4088 - smape: 0.6942 - val_ia: 0.7134 - val_loss: 0.2534 - val_mae: 0.4076 - val_rmse: 0.4936 - val_smape: 0.8228

Epoch 11/64

144/144 - 2s - 15ms/step - ia: 0.7990 - loss: 0.1630 - mae: 0.3106 - rmse: 0.4033 - smape: 0.6850 - val_ia: 0.7355 - val_loss: 0.2130 - val_mae: 0.3765 - val_rmse: 0.4479 - val_smape: 0.7691

Epoch 12/64

144/144 - 2s - 16ms/step - ia: 0.8013 - loss: 0.1596 - mae: 0.3070 - rmse: 0.3987 - smape: 0.6780 - val_ia: 0.7554 - val_loss: 0.1769 - val_mae: 0.3441 - val_rmse: 0.4034 - val_smape: 0.7351

Epoch 13/64

144/144 - 2s - 15ms/step - ia: 0.8058 - loss: 0.1539 - mae: 0.3008 - rmse: 0.3915 - smape: 0.6649 - val_ia: 0.7494 - val_loss: 0.1850 - val_mae: 0.3518 - val_rmse: 0.4181 - val_smape: 0.7475

Epoch 14/64

144/144 - 2s - 15ms/step - ia: 0.8076 - loss: 0.1507 - mae: 0.2988 - rmse: 0.3872 - smape: 0.6585 - val_ia: 0.7358 - val_loss: 0.2265 - val_mae: 0.3776 - val_rmse: 0.4679 - val_smape: 0.7597

Epoch 15/64

144/144 - 2s - 16ms/step - ia: 0.8091 - loss: 0.1488 - mae: 0.2965 - rmse: 0.3848 - smape: 0.6522 - val_ia: 0.7296 - val_loss: 0.2282 - val_mae: 0.3809 - val_rmse: 0.4673 - val_smape: 0.7770

Epoch 16/64

144/144 - 2s - 14ms/step - ia: 0.8110 - loss: 0.1455 - mae: 0.2940 - rmse: 0.3804 - smape: 0.6468 - val_ia: 0.7379 - val_loss: 0.2256 - val_mae: 0.3765 - val_rmse: 0.4545 - val_smape: 0.7450

Epoch 17/64

144/144 - 2s - 15ms/step - ia: 0.8126 - loss: 0.1436 - mae: 0.2914 - rmse: 0.3785 - smape: 0.6386 - val_ia: 0.7342 - val_loss: 0.2048 - val_mae: 0.3650 - val_rmse: 0.4418 - val_smape: 0.7718

Epoch 18/64

144/144 - 2s - 16ms/step - ia: 0.8136 - loss: 0.1426 - mae: 0.2902 - rmse: 0.3770 - smape: 0.6364 - val_ia: 0.7474 - val_loss: 0.2026 - val_mae: 0.3577 - val_rmse: 0.4373 - val_smape: 0.7418

Epoch 19/64

144/144 - 2s - 14ms/step - ia: 0.8156 - loss: 0.1405 - mae: 0.2879 - rmse: 0.3742 - smape: 0.6314 - val_ia: 0.7375 - val_loss: 0.2148 - val_mae: 0.3680 - val_rmse: 0.4527 - val_smape: 0.7545

Epoch 20/64

144/144 - 2s - 16ms/step - ia: 0.8157 - loss: 0.1404 - mae: 0.2878 - rmse: 0.3739 - smape: 0.6309 - val_ia: 0.7345 - val_loss: 0.2538 - val_mae: 0.3855 - val_rmse: 0.4906 - val_smape: 0.7491

Epoch 21/64

144/144 - 2s - 16ms/step - ia: 0.8164 - loss: 0.1384 - mae: 0.2867 - rmse: 0.3713 - smape: 0.6274 - val_ia: 0.7180 - val_loss: 0.2816 - val_mae: 0.4059 - val_rmse: 0.5170 - val_smape: 0.7774

Epoch 22/64

144/144 - 2s - 16ms/step - ia: 0.8177 - loss: 0.1375 - mae: 0.2849 - rmse: 0.3700 - smape: 0.6230 - val_ia: 0.7448 - val_loss: 0.2203 - val_mae: 0.3683 - val_rmse: 0.4533 - val_smape: 0.7345

Epoch 23/64

144/144 - 2s - 16ms/step - ia: 0.8187 - loss: 0.1368 - mae: 0.2834 - rmse: 0.3693 - smape: 0.6197 - val_ia: 0.7347 - val_loss: 0.2402 - val_mae: 0.3789 - val_rmse: 0.4783 - val_smape: 0.7535

Epoch 24/64

144/144 - 2s - 15ms/step - ia: 0.8196 - loss: 0.1353 - mae: 0.2822 - rmse: 0.3672 - smape: 0.6175 - val_ia: 0.7369 - val_loss: 0.2244 - val_mae: 0.3719 - val_rmse: 0.4588 - val_smape: 0.7594

Epoch 25/64

144/144 - 2s - 16ms/step - ia: 0.8196 - loss: 0.1357 - mae: 0.2819 - rmse: 0.3678 - smape: 0.6178 - val_ia: 0.7294 - val_loss: 0.2474 - val_mae: 0.3848 - val_rmse: 0.4861 - val_smape: 0.7707

Epoch 26/64

144/144 - 2s - 16ms/step - ia: 0.8205 - loss: 0.1349 - mae: 0.2814 - rmse: 0.3663 - smape: 0.6152 - val_ia: 0.7267 - val_loss: 0.2404 - val_mae: 0.3821 - val_rmse: 0.4721 - val_smape: 0.7661

Epoch 27/64

144/144 - 2s - 13ms/step - ia: 0.8214 - loss: 0.1329 - mae: 0.2791 - rmse: 0.3641 - smape: 0.6104 - val_ia: 0.7324 - val_loss: 0.2466 - val_mae: 0.3816 - val_rmse: 0.4808 - val_smape: 0.7544

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:33 577ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 82%|████████▏ | 41/50 [10:56:49<1:05:50, 438.97s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 56s - 24ms/step - ia: 0.7585 - loss: 0.2196 - mae: 0.3533 - rmse: 0.4457 - smape: 0.7154 - val_ia: 0.3216 - val_loss: 0.2340 - val_mae: 0.3798 - val_rmse: 0.4151 - val_smape: 0.7834

Epoch 2/128

2292/2292 - 43s - 19ms/step - ia: 0.8270 - loss: 0.1211 - mae: 0.2607 - rmse: 0.3376 - smape: 0.5942 - val_ia: 0.3330 - val_loss: 0.1705 - val_mae: 0.3393 - val_rmse: 0.3634 - val_smape: 0.7443

Epoch 3/128

2292/2292 - 42s - 19ms/step - ia: 0.8408 - loss: 0.1030 - mae: 0.2410 - rmse: 0.3120 - smape: 0.5646 - val_ia: 0.3282 - val_loss: 0.1892 - val_mae: 0.3453 - val_rmse: 0.3819 - val_smape: 0.7516

Epoch 4/128

2292/2292 - 44s - 19ms/step - ia: 0.8489 - loss: 0.0930 - mae: 0.2289 - rmse: 0.2962 - smape: 0.5402 - val_ia: 0.3523 - val_loss: 0.1654 - val_mae: 0.3163 - val_rmse: 0.3511 - val_smape: 0.6882

Epoch 5/128

2292/2292 - 43s - 19ms/step - ia: 0.8568 - loss: 0.0852 - mae: 0.2186 - rmse: 0.2832 - smape: 0.5173 - val_ia: 0.3490 - val_loss: 0.2045 - val_mae: 0.3399 - val_rmse: 0.3852 - val_smape: 0.7310

Epoch 6/128

2292/2292 - 43s - 19ms/step - ia: 0.8629 - loss: 0.0780 - mae: 0.2099 - rmse: 0.2713 - smape: 0.4981 - val_ia: 0.3607 - val_loss: 0.1657 - val_mae: 0.3162 - val_rmse: 0.3494 - val_smape: 0.7007

Epoch 7/128

2292/2292 - 41s - 18ms/step - ia: 0.8662 - loss: 0.0741 - mae: 0.2043 - rmse: 0.2642 - smape: 0.4887 - val_ia: 0.3790 - val_loss: 0.1697 - val_mae: 0.3062 - val_rmse: 0.3480 - val_smape: 0.7294

Epoch 8/128

2292/2292 - 44s - 19ms/step - ia: 0.8707 - loss: 0.0701 - mae: 0.1983 - rmse: 0.2567 - smape: 0.4748 - val_ia: 0.3287 - val_loss: 0.2228 - val_mae: 0.3654 - val_rmse: 0.4041 - val_smape: 0.8207

Epoch 9/128

2292/2292 - 42s - 18ms/step - ia: 0.8741 - loss: 0.0663 - mae: 0.1929 - rmse: 0.2496 - smape: 0.4628 - val_ia: 0.3543 - val_loss: 0.2160 - val_mae: 0.3489 - val_rmse: 0.3867 - val_smape: 0.7738

Epoch 10/128

2292/2292 - 42s - 18ms/step - ia: 0.8748 - loss: 0.0659 - mae: 0.1922 - rmse: 0.2487 - smape: 0.4659 - val_ia: 0.3394 - val_loss: 0.2292 - val_mae: 0.3617 - val_rmse: 0.4054 - val_smape: 0.7869

Epoch 11/128

2292/2292 - 42s - 18ms/step - ia: 0.8780 - loss: 0.0629 - mae: 0.1873 - rmse: 0.2432 - smape: 0.4564 - val_ia: 0.3609 - val_loss: 0.1905 - val_mae: 0.3346 - val_rmse: 0.3696 - val_smape: 0.7343

Epoch 12/128

2292/2292 - 44s - 19ms/step - ia: 0.8806 - loss: 0.0596 - mae: 0.1830 - rmse: 0.2368 - smape: 0.4459 - val_ia: 0.3772 - val_loss: 0.1891 - val_mae: 0.3183 - val_rmse: 0.3573 - val_smape: 0.7040

Epoch 13/128

2292/2292 - 41s - 18ms/step - ia: 0.8812 - loss: 0.0602 - mae: 0.1828 - rmse: 0.2376 - smape: 0.4466 - val_ia: 0.3430 - val_loss: 0.2354 - val_mae: 0.3613 - val_rmse: 0.4050 - val_smape: 0.7631

Epoch 14/128

2292/2292 - 44s - 19ms/step - ia: 0.8833 - loss: 0.0578 - mae: 0.1795 - rmse: 0.2330 - smape: 0.4398 - val_ia: 0.3301 - val_loss: 0.2477 - val_mae: 0.3881 - val_rmse: 0.4238 - val_smape: 0.8230

Epoch 15/128

2292/2292 - 83s - 36ms/step - ia: 0.8851 - loss: 0.0562 - mae: 0.1768 - rmse: 0.2296 - smape: 0.4331 - val_ia: 0.3504 - val_loss: 0.2248 - val_mae: 0.3522 - val_rmse: 0.3945 - val_smape: 0.7719

Epoch 16/128

2292/2292 - 45s - 19ms/step - ia: 0.8856 - loss: 0.0556 - mae: 0.1761 - rmse: 0.2285 - smape: 0.4322 - val_ia: 0.3288 - val_loss: 0.2296 - val_mae: 0.3711 - val_rmse: 0.4121 - val_smape: 0.7619

Epoch 17/128

2292/2292 - 48s - 21ms/step - ia: 0.8861 - loss: 0.0555 - mae: 0.1751 - rmse: 0.2281 - smape: 0.4299 - val_ia: 0.3573 - val_loss: 0.2138 - val_mae: 0.3384 - val_rmse: 0.3821 - val_smape: 0.7178

Epoch 18/128

2292/2292 - 40s - 17ms/step - ia: 0.8868 - loss: 0.0551 - mae: 0.1744 - rmse: 0.2271 - smape: 0.4294 - val_ia: 0.3389 - val_loss: 0.2384 - val_mae: 0.3657 - val_rmse: 0.4093 - val_smape: 0.7836

Epoch 19/128

2292/2292 - 43s - 19ms/step - ia: 0.8881 - loss: 0.0533 - mae: 0.1722 - rmse: 0.2237 - smape: 0.4263 - val_ia: 0.3396 - val_loss: 0.2881 - val_mae: 0.3869 - val_rmse: 0.4330 - val_smape: 0.7822

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:34 1s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 84%|████████▍ | 42/50 [11:11:22<1:15:54, 569.36s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

4584/4584 - 60s - 13ms/step - ia: 0.7680 - loss: 0.1856 - mae: 0.3212 - rmse: 0.4014 - smape: 0.6833 - val_ia: 0.2424 - val_loss: 0.2428 - val_mae: 0.3779 - val_rmse: 0.3988 - val_smape: 0.7876

Epoch 2/8

4584/4584 - 48s - 10ms/step - ia: 0.8429 - loss: 0.0904 - mae: 0.2210 - rmse: 0.2836 - smape: 0.5484 - val_ia: 0.2468 - val_loss: 0.2703 - val_mae: 0.3943 - val_rmse: 0.4148 - val_smape: 0.7602

Epoch 3/8

4584/4584 - 48s - 10ms/step - ia: 0.8558 - loss: 0.0771 - mae: 0.2033 - rmse: 0.2611 - smape: 0.5107 - val_ia: 0.2537 - val_loss: 0.2714 - val_mae: 0.3779 - val_rmse: 0.3974 - val_smape: 0.7467

Epoch 4/8

4584/4584 - 48s - 10ms/step - ia: 0.8631 - loss: 0.0705 - mae: 0.1937 - rmse: 0.2489 - smape: 0.4887 - val_ia: 0.2333 - val_loss: 0.3714 - val_mae: 0.4506 - val_rmse: 0.4709 - val_smape: 0.8151

Epoch 5/8

4584/4584 - 82s - 18ms/step - ia: 0.8682 - loss: 0.0660 - mae: 0.1872 - rmse: 0.2410 - smape: 0.4742 - val_ia: 0.2441 - val_loss: 0.3469 - val_mae: 0.4378 - val_rmse: 0.4575 - val_smape: 0.8056

Epoch 6/8

4584/4584 - 48s - 10ms/step - ia: 0.8704 - loss: 0.0638 - mae: 0.1837 - rmse: 0.2367 - smape: 0.4682 - val_ia: 0.2485 - val_loss: 0.3276 - val_mae: 0.4149 - val_rmse: 0.4350 - val_smape: 0.7703

Epoch 7/8

4584/4584 - 48s - 10ms/step - ia: 0.8727 - loss: 0.0617 - mae: 0.1807 - rmse: 0.2331 - smape: 0.4598 - val_ia: 0.2521 - val_loss: 0.2815 - val_mae: 0.3961 - val_rmse: 0.4160 - val_smape: 0.7682

Epoch 8/8

4584/4584 - 48s - 11ms/step - ia: 0.8750 - loss: 0.0596 - mae: 0.1773 - rmse: 0.2290 - smape: 0.4529 - val_ia: 0.2435 - val_loss: 0.3232 - val_mae: 0.4071 - val_rmse: 0.4302 - val_smape: 0.7685

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:42 636ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/32

 86%|████████▌ | 43/50 [11:18:34<1:01:36, 528.12s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 10s - 34ms/step - ia: 0.1660 - loss: 1.0627 - mae: 0.8539 - rmse: 1.0295 - smape: 1.6256 - val_ia: 0.2205 - val_loss: 0.8493 - val_mae: 0.7657 - val_rmse: 0.9153 - val_smape: 1.8094

Epoch 2/32

287/287 - 3s - 10ms/step - ia: 0.1633 - loss: 1.0526 - mae: 0.8502 - rmse: 1.0249 - smape: 1.6470 - val_ia: 0.2150 - val_loss: 0.8545 - val_mae: 0.7690 - val_rmse: 0.9177 - val_smape: 1.9384

Epoch 3/32

287/287 - 3s - 11ms/step - ia: 0.1600 - loss: 1.0457 - mae: 0.8486 - rmse: 1.0213 - smape: 1.6574 - val_ia: 0.2143 - val_loss: 0.8549 - val_mae: 0.7694 - val_rmse: 0.9178 - val_smape: 1.9550

Epoch 4/32

287/287 - 3s - 11ms/step - ia: 0.1621 - loss: 1.0421 - mae: 0.8461 - rmse: 1.0195 - smape: 1.6513 - val_ia: 0.2142 - val_loss: 0.8543 - val_mae: 0.7693 - val_rmse: 0.9174 - val_smape: 1.9285

Epoch 5/32

287/287 - 3s - 10ms/step - ia: 0.1625 - loss: 1.0380 - mae: 0.8450 - rmse: 1.0176 - smape: 1.6512 - val_ia: 0.2150 - val_loss: 0.8515 - val_mae: 0.7680 - val_rmse: 0.9159 - val_smape: 1.9109

Epoch 6/32

287/287 - 3s - 10ms/step - ia: 0.1637 - loss: 1.0331 - mae: 0.8422 - rmse: 1.0151 - smape: 1.6427 - val_ia: 0.2155 - val_loss: 0.8501 - val_mae: 0.7675 - val_rmse: 0.9151 - val_smape: 1.8878

Epoch 7/32

287/287 - 3s - 11ms/step - ia: 0.1684 - loss: 1.0202 - mae: 0.8377 - rmse: 1.0088 - smape: 1.6365 - val_ia: 0.2164 - val_loss: 0.8482 - val_mae: 0.7667 - val_rmse: 0.9140 - val_smape: 1.8659

Epoch 8/32

287/287 - 3s - 10ms/step - ia: 0.1666 - loss: 1.0176 - mae: 0.8369 - rmse: 1.0076 - smape: 1.6357 - val_ia: 0.2178 - val_loss: 0.8453 - val_mae: 0.7653 - val_rmse: 0.9124 - val_smape: 1.8447

Epoch 9/32

287/287 - 3s - 11ms/step - ia: 0.1692 - loss: 1.0115 - mae: 0.8341 - rmse: 1.0045 - smape: 1.6278 - val_ia: 0.2194 - val_loss: 0.8423 - val_mae: 0.7639 - val_rmse: 0.9108 - val_smape: 1.8227

Epoch 10/32

287/287 - 3s - 11ms/step - ia: 0.1709 - loss: 1.0044 - mae: 0.8324 - rmse: 1.0007 - smape: 1.6300 - val_ia: 0.2213 - val_loss: 0.8391 - val_mae: 0.7624 - val_rmse: 0.9091 - val_smape: 1.8009

Epoch 11/32

287/287 - 3s - 10ms/step - ia: 0.1740 - loss: 0.9978 - mae: 0.8292 - rmse: 0.9979 - smape: 1.6186 - val_ia: 0.2233 - val_loss: 0.8365 - val_mae: 0.7612 - val_rmse: 0.9076 - val_smape: 1.7783

Epoch 12/32

287/287 - 3s - 10ms/step - ia: 0.1774 - loss: 0.9893 - mae: 0.8260 - rmse: 0.9936 - smape: 1.6137 - val_ia: 0.2256 - val_loss: 0.8328 - val_mae: 0.7594 - val_rmse: 0.9056 - val_smape: 1.7559

Epoch 13/32

287/287 - 3s - 11ms/step - ia: 0.1779 - loss: 0.9854 - mae: 0.8249 - rmse: 0.9916 - smape: 1.6132 - val_ia: 0.2282 - val_loss: 0.8285 - val_mae: 0.7573 - val_rmse: 0.9033 - val_smape: 1.7329

Epoch 14/32

287/287 - 3s - 10ms/step - ia: 0.1824 - loss: 0.9800 - mae: 0.8230 - rmse: 0.9887 - smape: 1.6055 - val_ia: 0.2307 - val_loss: 0.8253 - val_mae: 0.7558 - val_rmse: 0.9015 - val_smape: 1.7098

Epoch 15/32

287/287 - 3s - 10ms/step - ia: 0.1876 - loss: 0.9710 - mae: 0.8189 - rmse: 0.9843 - smape: 1.5951 - val_ia: 0.2336 - val_loss: 0.8216 - val_mae: 0.7539 - val_rmse: 0.8994 - val_smape: 1.6867

Epoch 16/32

287/287 - 3s - 11ms/step - ia: 0.1913 - loss: 0.9587 - mae: 0.8144 - rmse: 0.9781 - smape: 1.5899 - val_ia: 0.2368 - val_loss: 0.8182 - val_mae: 0.7522 - val_rmse: 0.8975 - val_smape: 1.6631

Epoch 17/32

287/287 - 3s - 11ms/step - ia: 0.1964 - loss: 0.9531 - mae: 0.8127 - rmse: 0.9751 - smape: 1.5840 - val_ia: 0.2407 - val_loss: 0.8116 - val_mae: 0.7489 - val_rmse: 0.8939 - val_smape: 1.6393

Epoch 18/32

287/287 - 3s - 11ms/step - ia: 0.2068 - loss: 0.9402 - mae: 0.8063 - rmse: 0.9685 - smape: 1.5662 - val_ia: 0.2447 - val_loss: 0.8077 - val_mae: 0.7469 - val_rmse: 0.8917 - val_smape: 1.6160

Epoch 19/32

287/287 - 3s - 11ms/step - ia: 0.2103 - loss: 0.9353 - mae: 0.8051 - rmse: 0.9659 - smape: 1.5636 - val_ia: 0.2494 - val_loss: 0.8032 - val_mae: 0.7445 - val_rmse: 0.8891 - val_smape: 1.5926

Epoch 20/32

287/287 - 3s - 11ms/step - ia: 0.2198 - loss: 0.9207 - mae: 0.7998 - rmse: 0.9585 - smape: 1.5476 - val_ia: 0.2545 - val_loss: 0.7984 - val_mae: 0.7419 - val_rmse: 0.8864 - val_smape: 1.5696

Epoch 21/32

287/287 - 3s - 11ms/step - ia: 0.2243 - loss: 0.9161 - mae: 0.7977 - rmse: 0.9558 - smape: 1.5397 - val_ia: 0.2601 - val_loss: 0.7937 - val_mae: 0.7393 - val_rmse: 0.8837 - val_smape: 1.5471

Epoch 22/32

287/287 - 3s - 11ms/step - ia: 0.2334 - loss: 0.9020 - mae: 0.7918 - rmse: 0.9489 - smape: 1.5260 - val_ia: 0.2661 - val_loss: 0.7884 - val_mae: 0.7365 - val_rmse: 0.8806 - val_smape: 1.5251

Epoch 23/32

287/287 - 3s - 9ms/step - ia: 0.2409 - loss: 0.8946 - mae: 0.7886 - rmse: 0.9446 - smape: 1.5150 - val_ia: 0.2725 - val_loss: 0.7842 - val_mae: 0.7342 - val_rmse: 0.8781 - val_smape: 1.5039

Epoch 24/32

287/287 - 3s - 11ms/step - ia: 0.2518 - loss: 0.8788 - mae: 0.7820 - rmse: 0.9365 - smape: 1.5010 - val_ia: 0.2794 - val_loss: 0.7794 - val_mae: 0.7315 - val_rmse: 0.8753 - val_smape: 1.4828

Epoch 25/32

287/287 - 3s - 10ms/step - ia: 0.2592 - loss: 0.8722 - mae: 0.7792 - rmse: 0.9328 - smape: 1.4872 - val_ia: 0.2866 - val_loss: 0.7741 - val_mae: 0.7287 - val_rmse: 0.8722 - val_smape: 1.4625

Epoch 26/32

287/287 - 3s - 10ms/step - ia: 0.2695 - loss: 0.8599 - mae: 0.7738 - rmse: 0.9263 - smape: 1.4723 - val_ia: 0.2940 - val_loss: 0.7689 - val_mae: 0.7259 - val_rmse: 0.8691 - val_smape: 1.4430

Epoch 27/32

287/287 - 3s - 9ms/step - ia: 0.2788 - loss: 0.8507 - mae: 0.7697 - rmse: 0.9210 - smape: 1.4583 - val_ia: 0.3019 - val_loss: 0.7657 - val_mae: 0.7242 - val_rmse: 0.8670 - val_smape: 1.4252

Epoch 28/32

287/287 - 2s - 8ms/step - ia: 0.2889 - loss: 0.8356 - mae: 0.7639 - rmse: 0.9131 - smape: 1.4472 - val_ia: 0.3097 - val_loss: 0.7620 - val_mae: 0.7222 - val_rmse: 0.8646 - val_smape: 1.4084

Epoch 29/32

287/287 - 2s - 8ms/step - ia: 0.3003 - loss: 0.8234 - mae: 0.7583 - rmse: 0.9063 - smape: 1.4295 - val_ia: 0.3176 - val_loss: 0.7594 - val_mae: 0.7209 - val_rmse: 0.8629 - val_smape: 1.3929

Epoch 30/32

287/287 - 2s - 8ms/step - ia: 0.3108 - loss: 0.8113 - mae: 0.7527 - rmse: 0.8999 - smape: 1.4145 - val_ia: 0.3253 - val_loss: 0.7548 - val_mae: 0.7186 - val_rmse: 0.8600 - val_smape: 1.3777

Epoch 31/32

287/287 - 3s - 10ms/step - ia: 0.3209 - loss: 0.7989 - mae: 0.7464 - rmse: 0.8930 - smape: 1.4000 - val_ia: 0.3332 - val_loss: 0.7517 - val_mae: 0.7171 - val_rmse: 0.8579 - val_smape: 1.3641

Epoch 32/32

287/287 - 3s - 9ms/step - ia: 0.3339 - loss: 0.7838 - mae: 0.7402 - rmse: 0.8843 - smape: 1.3837 - val_ia: 0.3410 - val_loss: 0.7491 - val_mae: 0.7159 - val_rmse: 0.8560 - val_smape: 1.3516

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:37 602ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 88%|████████▊ | 44/50 [11:20:16<40:01, 400.25s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 31s - 27ms/step - ia: 0.7069 - loss: 0.3034 - mae: 0.4271 - rmse: 0.5384 - smape: 0.8077 - val_ia: 0.3664 - val_loss: 0.3882 - val_mae: 0.5232 - val_rmse: 0.5804 - val_smape: 0.9460

Epoch 2/32

1146/1146 - 18s - 16ms/step - ia: 0.8120 - loss: 0.1488 - mae: 0.2885 - rmse: 0.3776 - smape: 0.6469 - val_ia: 0.5572 - val_loss: 0.1416 - val_mae: 0.3009 - val_rmse: 0.3471 - val_smape: 0.6499

Epoch 3/32

1146/1146 - 18s - 16ms/step - ia: 0.8487 - loss: 0.1013 - mae: 0.2343 - rmse: 0.3128 - smape: 0.5729 - val_ia: 0.5696 - val_loss: 0.1234 - val_mae: 0.2767 - val_rmse: 0.3224 - val_smape: 0.6462

Epoch 4/32

1146/1146 - 18s - 16ms/step - ia: 0.8587 - loss: 0.0904 - mae: 0.2202 - rmse: 0.2952 - smape: 0.5495 - val_ia: 0.5014 - val_loss: 0.2096 - val_mae: 0.3540 - val_rmse: 0.4169 - val_smape: 0.7263

Epoch 5/32

1146/1146 - 18s - 16ms/step - ia: 0.8644 - loss: 0.0838 - mae: 0.2120 - rmse: 0.2844 - smape: 0.5325 - val_ia: 0.5538 - val_loss: 0.1311 - val_mae: 0.2904 - val_rmse: 0.3372 - val_smape: 0.6500

Epoch 6/32

1146/1146 - 19s - 16ms/step - ia: 0.8697 - loss: 0.0778 - mae: 0.2046 - rmse: 0.2742 - smape: 0.5190 - val_ia: 0.5135 - val_loss: 0.1936 - val_mae: 0.3447 - val_rmse: 0.4024 - val_smape: 0.7111

Epoch 7/32

1146/1146 - 16s - 14ms/step - ia: 0.8733 - loss: 0.0740 - mae: 0.1990 - rmse: 0.2674 - smape: 0.5077 - val_ia: 0.5218 - val_loss: 0.1733 - val_mae: 0.3203 - val_rmse: 0.3788 - val_smape: 0.6888

Epoch 8/32

1146/1146 - 18s - 16ms/step - ia: 0.8771 - loss: 0.0695 - mae: 0.1930 - rmse: 0.2589 - smape: 0.4923 - val_ia: 0.5315 - val_loss: 0.1809 - val_mae: 0.3210 - val_rmse: 0.3802 - val_smape: 0.6868

Epoch 9/32

1146/1146 - 18s - 16ms/step - ia: 0.8795 - loss: 0.0672 - mae: 0.1893 - rmse: 0.2541 - smape: 0.4853 - val_ia: 0.5231 - val_loss: 0.1839 - val_mae: 0.3254 - val_rmse: 0.3869 - val_smape: 0.7021

Epoch 10/32

1146/1146 - 18s - 16ms/step - ia: 0.8822 - loss: 0.0648 - mae: 0.1858 - rmse: 0.2497 - smape: 0.4783 - val_ia: 0.5194 - val_loss: 0.2094 - val_mae: 0.3407 - val_rmse: 0.4083 - val_smape: 0.7150

Epoch 11/32

1146/1146 - 18s - 16ms/step - ia: 0.8845 - loss: 0.0626 - mae: 0.1820 - rmse: 0.2455 - smape: 0.4716 - val_ia: 0.4919 - val_loss: 0.2570 - val_mae: 0.3721 - val_rmse: 0.4433 - val_smape: 0.7278

Epoch 12/32

1146/1146 - 18s - 16ms/step - ia: 0.8863 - loss: 0.0606 - mae: 0.1796 - rmse: 0.2416 - smape: 0.4660 - val_ia: 0.5080 - val_loss: 0.2177 - val_mae: 0.3509 - val_rmse: 0.4172 - val_smape: 0.7118

Epoch 13/32

1146/1146 - 21s - 18ms/step - ia: 0.8876 - loss: 0.0587 - mae: 0.1775 - rmse: 0.2380 - smape: 0.4613 - val_ia: 0.5207 - val_loss: 0.1944 - val_mae: 0.3308 - val_rmse: 0.3951 - val_smape: 0.6962

Epoch 14/32

1146/1146 - 19s - 16ms/step - ia: 0.8903 - loss: 0.0570 - mae: 0.1739 - rmse: 0.2342 - smape: 0.4520 - val_ia: 0.5011 - val_loss: 0.2252 - val_mae: 0.3588 - val_rmse: 0.4270 - val_smape: 0.7408

Epoch 15/32

1146/1146 - 18s - 16ms/step - ia: 0.8915 - loss: 0.0557 - mae: 0.1717 - rmse: 0.2311 - smape: 0.4493 - val_ia: 0.5227 - val_loss: 0.1941 - val_mae: 0.3343 - val_rmse: 0.3920 - val_smape: 0.7147

Epoch 16/32

1146/1146 - 19s - 16ms/step - ia: 0.8937 - loss: 0.0536 - mae: 0.1684 - rmse: 0.2269 - smape: 0.4422 - val_ia: 0.4997 - val_loss: 0.2320 - val_mae: 0.3641 - val_rmse: 0.4340 - val_smape: 0.7413

Epoch 17/32

1146/1146 - 21s - 18ms/step - ia: 0.8941 - loss: 0.0532 - mae: 0.1673 - rmse: 0.2260 - smape: 0.4405 - val_ia: 0.5182 - val_loss: 0.2009 - val_mae: 0.3419 - val_rmse: 0.4003 - val_smape: 0.7287

Epoch 18/32

1146/1146 - 19s - 17ms/step - ia: 0.8958 - loss: 0.0514 - mae: 0.1649 - rmse: 0.2224 - smape: 0.4367 - val_ia: 0.5411 - val_loss: 0.1647 - val_mae: 0.3109 - val_rmse: 0.3648 - val_smape: 0.6733

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:11 810ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2292/2292 - 51s - 22ms/step - ia: 0.3237 - loss: 0.7722 - mae: 0.7285 - rmse: 0.8651 - smape: 1.4690 - val_ia: 0.2119 - val_loss: 0.8837 - val_mae: 0.7492 - val_rmse: 0.7799 - val_smape: 1.1698

Epoch 2/256

2292/2292 - 45s - 20ms/step - ia: 0.6417 - loss: 0.3972 - mae: 0.5034 - rmse: 0.6203 - smape: 0.8954 - val_ia: 0.2150 - val_loss: 1.1096 - val_mae: 0.8433 - val_rmse: 0.8746 - val_smape: 1.1934

Epoch 3/256

2292/2292 - 42s - 18ms/step - ia: 0.6808 - loss: 0.3362 - mae: 0.4609 - rmse: 0.5703 - smape: 0.8173 - val_ia: 0.2188 - val_loss: 1.0692 - val_mae: 0.8107 - val_rmse: 0.8437 - val_smape: 1.1560

Epoch 4/256

2292/2292 - 43s - 19ms/step - ia: 0.7014 - loss: 0.3047 - mae: 0.4358 - rmse: 0.5426 - smape: 0.7875 - val_ia: 0.2177 - val_loss: 1.1176 - val_mae: 0.8177 - val_rmse: 0.8514 - val_smape: 1.1563

Epoch 5/256

2292/2292 - 32s - 14ms/step - ia: 0.7159 - loss: 0.2809 - mae: 0.4168 - rmse: 0.5208 - smape: 0.7721 - val_ia: 0.2258 - val_loss: 1.0435 - val_mae: 0.7830 - val_rmse: 0.8173 - val_smape: 1.1625

Epoch 6/256

2292/2292 - 31s - 14ms/step - ia: 0.7283 - loss: 0.2637 - mae: 0.4013 - rmse: 0.5042 - smape: 0.7580 - val_ia: 0.2289 - val_loss: 0.9270 - val_mae: 0.7431 - val_rmse: 0.7763 - val_smape: 1.1855

Epoch 7/256

2292/2292 - 31s - 14ms/step - ia: 0.7359 - loss: 0.2498 - mae: 0.3901 - rmse: 0.4905 - smape: 0.7500 - val_ia: 0.2305 - val_loss: 0.9167 - val_mae: 0.7390 - val_rmse: 0.7724 - val_smape: 1.1915

Epoch 8/256

2292/2292 - 30s - 13ms/step - ia: 0.7423 - loss: 0.2393 - mae: 0.3814 - rmse: 0.4799 - smape: 0.7428 - val_ia: 0.2339 - val_loss: 0.7916 - val_mae: 0.6947 - val_rmse: 0.7272 - val_smape: 1.1706

Epoch 9/256

2292/2292 - 30s - 13ms/step - ia: 0.7503 - loss: 0.2268 - mae: 0.3696 - rmse: 0.4673 - smape: 0.7296 - val_ia: 0.2354 - val_loss: 0.7438 - val_mae: 0.6762 - val_rmse: 0.7086 - val_smape: 1.1508

Epoch 10/256

2292/2292 - 30s - 13ms/step - ia: 0.7550 - loss: 0.2192 - mae: 0.3633 - rmse: 0.4594 - smape: 0.7243 - val_ia: 0.2418 - val_loss: 0.5815 - val_mae: 0.6059 - val_rmse: 0.6372 - val_smape: 1.1004

Epoch 11/256

2292/2292 - 30s - 13ms/step - ia: 0.7600 - loss: 0.2110 - mae: 0.3558 - rmse: 0.4505 - smape: 0.7180 - val_ia: 0.2404 - val_loss: 0.5828 - val_mae: 0.6048 - val_rmse: 0.6377 - val_smape: 1.0905

Epoch 12/256

2292/2292 - 30s - 13ms/step - ia: 0.7641 - loss: 0.2040 - mae: 0.3489 - rmse: 0.4424 - smape: 0.7109 - val_ia: 0.2439 - val_loss: 0.5308 - val_mae: 0.5779 - val_rmse: 0.6115 - val_smape: 1.0584

Epoch 13/256

2292/2292 - 30s - 13ms/step - ia: 0.7685 - loss: 0.1971 - mae: 0.3426 - rmse: 0.4350 - smape: 0.7052 - val_ia: 0.2447 - val_loss: 0.4877 - val_mae: 0.5550 - val_rmse: 0.5897 - val_smape: 1.0491

Epoch 14/256

2292/2292 - 30s - 13ms/step - ia: 0.7743 - loss: 0.1896 - mae: 0.3352 - rmse: 0.4269 - smape: 0.6950 - val_ia: 0.2472 - val_loss: 0.4882 - val_mae: 0.5489 - val_rmse: 0.5858 - val_smape: 1.0351

Epoch 15/256

2292/2292 - 31s - 13ms/step - ia: 0.7784 - loss: 0.1831 - mae: 0.3295 - rmse: 0.4184 - smape: 0.6894 - val_ia: 0.2433 - val_loss: 0.4817 - val_mae: 0.5469 - val_rmse: 0.5857 - val_smape: 1.0388

Epoch 16/256

2292/2292 - 30s - 13ms/step - ia: 0.7824 - loss: 0.1762 - mae: 0.3227 - rmse: 0.4113 - smape: 0.6803 - val_ia: 0.2456 - val_loss: 0.4696 - val_mae: 0.5373 - val_rmse: 0.5770 - val_smape: 1.0249

Epoch 17/256

2292/2292 - 31s - 13ms/step - ia: 0.7857 - loss: 0.1723 - mae: 0.3180 - rmse: 0.4061 - smape: 0.6745 - val_ia: 0.2434 - val_loss: 0.4773 - val_mae: 0.5387 - val_rmse: 0.5804 - val_smape: 1.0291

Epoch 18/256

2292/2292 - 30s - 13ms/step - ia: 0.7899 - loss: 0.1656 - mae: 0.3126 - rmse: 0.3984 - smape: 0.6666 - val_ia: 0.2419 - val_loss: 0.4862 - val_mae: 0.5418 - val_rmse: 0.5845 - val_smape: 1.0261

Epoch 19/256

2292/2292 - 30s - 13ms/step - ia: 0.7937 - loss: 0.1598 - mae: 0.3065 - rmse: 0.3911 - smape: 0.6622 - val_ia: 0.2424 - val_loss: 0.4792 - val_mae: 0.5382 - val_rmse: 0.5804 - val_smape: 1.0267

Epoch 20/256

2292/2292 - 30s - 13ms/step - ia: 0.7966 - loss: 0.1551 - mae: 0.3026 - rmse: 0.3853 - smape: 0.6589 - val_ia: 0.2520 - val_loss: 0.4338 - val_mae: 0.5115 - val_rmse: 0.5533 - val_smape: 0.9964

Epoch 21/256

2292/2292 - 30s - 13ms/step - ia: 0.7997 - loss: 0.1508 - mae: 0.2981 - rmse: 0.3800 - smape: 0.6541 - val_ia: 0.2531 - val_loss: 0.4306 - val_mae: 0.5103 - val_rmse: 0.5505 - val_smape: 0.9872

Epoch 22/256

2292/2292 - 30s - 13ms/step - ia: 0.8033 - loss: 0.1464 - mae: 0.2932 - rmse: 0.3742 - smape: 0.6472 - val_ia: 0.2479 - val_loss: 0.4485 - val_mae: 0.5189 - val_rmse: 0.5606 - val_smape: 0.9991

Epoch 23/256

2292/2292 - 30s - 13ms/step - ia: 0.8059 - loss: 0.1423 - mae: 0.2892 - rmse: 0.3689 - smape: 0.6430 - val_ia: 0.2499 - val_loss: 0.4295 - val_mae: 0.5097 - val_rmse: 0.5508 - val_smape: 0.9866

Epoch 24/256

2292/2292 - 31s - 13ms/step - ia: 0.8104 - loss: 0.1364 - mae: 0.2830 - rmse: 0.3608 - smape: 0.6360 - val_ia: 0.2558 - val_loss: 0.4267 - val_mae: 0.5044 - val_rmse: 0.5461 - val_smape: 0.9645

Epoch 25/256

2292/2292 - 30s - 13ms/step - ia: 0.8133 - loss: 0.1337 - mae: 0.2792 - rmse: 0.3575 - smape: 0.6300 - val_ia: 0.2491 - val_loss: 0.4575 - val_mae: 0.5237 - val_rmse: 0.5645 - val_smape: 0.9794

Epoch 26/256

2292/2292 - 31s - 14ms/step - ia: 0.8157 - loss: 0.1304 - mae: 0.2761 - rmse: 0.3528 - smape: 0.6299 - val_ia: 0.2592 - val_loss: 0.4369 - val_mae: 0.5089 - val_rmse: 0.5486 - val_smape: 0.9496

Epoch 27/256

2292/2292 - 30s - 13ms/step - ia: 0.8193 - loss: 0.1267 - mae: 0.2712 - rmse: 0.3474 - smape: 0.6242 - val_ia: 0.2507 - val_loss: 0.4688 - val_mae: 0.5278 - val_rmse: 0.5686 - val_smape: 0.9577

Epoch 28/256

2292/2292 - 31s - 13ms/step - ia: 0.8203 - loss: 0.1248 - mae: 0.2694 - rmse: 0.3450 - smape: 0.6239 - val_ia: 0.2735 - val_loss: 0.3950 - val_mae: 0.4803 - val_rmse: 0.5188 - val_smape: 0.9090

Epoch 29/256

2292/2292 - 30s - 13ms/step - ia: 0.8230 - loss: 0.1220 - mae: 0.2658 - rmse: 0.3407 - smape: 0.6209 - val_ia: 0.2795 - val_loss: 0.3808 - val_mae: 0.4713 - val_rmse: 0.5101 - val_smape: 0.8870

Epoch 30/256

2292/2292 - 31s - 13ms/step - ia: 0.8244 - loss: 0.1200 - mae: 0.2636 - rmse: 0.3380 - smape: 0.6154 - val_ia: 0.2702 - val_loss: 0.4124 - val_mae: 0.4883 - val_rmse: 0.5295 - val_smape: 0.9049

Epoch 31/256

2292/2292 - 30s - 13ms/step - ia: 0.8261 - loss: 0.1178 - mae: 0.2609 - rmse: 0.3350 - smape: 0.6129 - val_ia: 0.2752 - val_loss: 0.4174 - val_mae: 0.4913 - val_rmse: 0.5313 - val_smape: 0.8829

Epoch 32/256

2292/2292 - 31s - 13ms/step - ia: 0.8281 - loss: 0.1154 - mae: 0.2579 - rmse: 0.3316 - smape: 0.6099 - val_ia: 0.2767 - val_loss: 0.4081 - val_mae: 0.4847 - val_rmse: 0.5256 - val_smape: 0.8768

Epoch 33/256

2292/2292 - 30s - 13ms/step - ia: 0.8296 - loss: 0.1143 - mae: 0.2561 - rmse: 0.3297 - smape: 0.6061 - val_ia: 0.2843 - val_loss: 0.3797 - val_mae: 0.4654 - val_rmse: 0.5055 - val_smape: 0.8620

Epoch 34/256

2292/2292 - 30s - 13ms/step - ia: 0.8305 - loss: 0.1132 - mae: 0.2547 - rmse: 0.3278 - smape: 0.6037 - val_ia: 0.2742 - val_loss: 0.4143 - val_mae: 0.4883 - val_rmse: 0.5305 - val_smape: 0.8822

Epoch 35/256

2292/2292 - 30s - 13ms/step - ia: 0.8326 - loss: 0.1101 - mae: 0.2509 - rmse: 0.3236 - smape: 0.5981 - val_ia: 0.2800 - val_loss: 0.3975 - val_mae: 0.4766 - val_rmse: 0.5182 - val_smape: 0.8683

Epoch 36/256

2292/2292 - 30s - 13ms/step - ia: 0.8338 - loss: 0.1093 - mae: 0.2500 - rmse: 0.3218 - smape: 0.5970 - val_ia: 0.2869 - val_loss: 0.3830 - val_mae: 0.4665 - val_rmse: 0.5081 - val_smape: 0.8542

Epoch 37/256

2292/2292 - 30s - 13ms/step - ia: 0.8348 - loss: 0.1083 - mae: 0.2483 - rmse: 0.3206 - smape: 0.5933 - val_ia: 0.2803 - val_loss: 0.4030 - val_mae: 0.4807 - val_rmse: 0.5224 - val_smape: 0.8675

Epoch 38/256

2292/2292 - 30s - 13ms/step - ia: 0.8365 - loss: 0.1069 - mae: 0.2463 - rmse: 0.3184 - smape: 0.5900 - val_ia: 0.2949 - val_loss: 0.3436 - val_mae: 0.4413 - val_rmse: 0.4846 - val_smape: 0.8362

Epoch 39/256

2292/2292 - 30s - 13ms/step - ia: 0.8363 - loss: 0.1065 - mae: 0.2462 - rmse: 0.3178 - smape: 0.5887 - val_ia: 0.2960 - val_loss: 0.3478 - val_mae: 0.4430 - val_rmse: 0.4859 - val_smape: 0.8360

Epoch 40/256

2292/2292 - 31s - 14ms/step - ia: 0.8375 - loss: 0.1051 - mae: 0.2444 - rmse: 0.3156 - smape: 0.5879 - val_ia: 0.2932 - val_loss: 0.3545 - val_mae: 0.4483 - val_rmse: 0.4916 - val_smape: 0.8380

Epoch 41/256

2292/2292 - 30s - 13ms/step - ia: 0.8380 - loss: 0.1040 - mae: 0.2429 - rmse: 0.3139 - smape: 0.5826 - val_ia: 0.2994 - val_loss: 0.3303 - val_mae: 0.4319 - val_rmse: 0.4734 - val_smape: 0.8192

Epoch 42/256

2292/2292 - 30s - 13ms/step - ia: 0.8402 - loss: 0.1029 - mae: 0.2412 - rmse: 0.3120 - smape: 0.5784 - val_ia: 0.2885 - val_loss: 0.3792 - val_mae: 0.4656 - val_rmse: 0.5075 - val_smape: 0.8469

Epoch 43/256

2292/2292 - 30s - 13ms/step - ia: 0.8407 - loss: 0.1020 - mae: 0.2398 - rmse: 0.3107 - smape: 0.5787 - val_ia: 0.2936 - val_loss: 0.3659 - val_mae: 0.4555 - val_rmse: 0.4976 - val_smape: 0.8386

Epoch 44/256

2292/2292 - 30s - 13ms/step - ia: 0.8406 - loss: 0.1016 - mae: 0.2398 - rmse: 0.3101 - smape: 0.5761 - val_ia: 0.2908 - val_loss: 0.3539 - val_mae: 0.4487 - val_rmse: 0.4942 - val_smape: 0.8395

Epoch 45/256

2292/2292 - 34s - 15ms/step - ia: 0.8413 - loss: 0.1002 - mae: 0.2386 - rmse: 0.3083 - smape: 0.5747 - val_ia: 0.2854 - val_loss: 0.3817 - val_mae: 0.4690 - val_rmse: 0.5141 - val_smape: 0.8504

Epoch 46/256

2292/2292 - 31s - 13ms/step - ia: 0.8428 - loss: 0.0990 - mae: 0.2367 - rmse: 0.3059 - smape: 0.5709 - val_ia: 0.2921 - val_loss: 0.3513 - val_mae: 0.4482 - val_rmse: 0.4922 - val_smape: 0.8307

Epoch 47/256

2292/2292 - 31s - 14ms/step - ia: 0.8432 - loss: 0.0985 - mae: 0.2365 - rmse: 0.3058 - smape: 0.5714 - val_ia: 0.2897 - val_loss: 0.3660 - val_mae: 0.4564 - val_rmse: 0.5014 - val_smape: 0.8387

Epoch 48/256

2292/2292 - 32s - 14ms/step - ia: 0.8443 - loss: 0.0980 - mae: 0.2352 - rmse: 0.3044 - smape: 0.5659 - val_ia: 0.2863 - val_loss: 0.3557 - val_mae: 0.4521 - val_rmse: 0.4979 - val_smape: 0.8387

Epoch 49/256

2292/2292 - 31s - 13ms/step - ia: 0.8436 - loss: 0.0975 - mae: 0.2346 - rmse: 0.3033 - smape: 0.5666 - val_ia: 0.2927 - val_loss: 0.3467 - val_mae: 0.4469 - val_rmse: 0.4929 - val_smape: 0.8275

Epoch 50/256

2292/2292 - 31s - 13ms/step - ia: 0.8450 - loss: 0.0963 - mae: 0.2334 - rmse: 0.3018 - smape: 0.5636 - val_ia: 0.2847 - val_loss: 0.3844 - val_mae: 0.4688 - val_rmse: 0.5152 - val_smape: 0.8503

Epoch 51/256

2292/2292 - 31s - 14ms/step - ia: 0.8461 - loss: 0.0950 - mae: 0.2320 - rmse: 0.3000 - smape: 0.5611 - val_ia: 0.2879 - val_loss: 0.3588 - val_mae: 0.4519 - val_rmse: 0.4976 - val_smape: 0.8379

Epoch 52/256

2292/2292 - 30s - 13ms/step - ia: 0.8468 - loss: 0.0949 - mae: 0.2318 - rmse: 0.2997 - smape: 0.5607 - val_ia: 0.2855 - val_loss: 0.3821 - val_mae: 0.4697 - val_rmse: 0.5151 - val_smape: 0.8522

Epoch 53/256

2292/2292 - 31s - 13ms/step - ia: 0.8483 - loss: 0.0929 - mae: 0.2294 - rmse: 0.2968 - smape: 0.5534 - val_ia: 0.2897 - val_loss: 0.3560 - val_mae: 0.4530 - val_rmse: 0.4976 - val_smape: 0.8368

Epoch 54/256

2292/2292 - 30s - 13ms/step - ia: 0.8485 - loss: 0.0928 - mae: 0.2286 - rmse: 0.2960 - smape: 0.5530 - val_ia: 0.2852 - val_loss: 0.3782 - val_mae: 0.4654 - val_rmse: 0.5118 - val_smape: 0.8456

Epoch 55/256

2292/2292 - 31s - 13ms/step - ia: 0.8485 - loss: 0.0933 - mae: 0.2290 - rmse: 0.2973 - smape: 0.5499 - val_ia: 0.2874 - val_loss: 0.3684 - val_mae: 0.4607 - val_rmse: 0.5066 - val_smape: 0.8390

Epoch 56/256

2292/2292 - 30s - 13ms/step - ia: 0.8489 - loss: 0.0923 - mae: 0.2277 - rmse: 0.2953 - smape: 0.5479 - val_ia: 0.2888 - val_loss: 0.3477 - val_mae: 0.4491 - val_rmse: 0.4945 - val_smape: 0.8308

Epoch 56: early stopping

Restoring model weights from the end of the best epoch: 41.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:15 468ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 92%|█████████▏| 46/50 [11:55:37<53:23, 800.92s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 5s - 38ms/step - ia: 0.2682 - loss: 1.2446 - mae: 0.9181 - rmse: 1.1159 - smape: 1.4515 - val_ia: 0.2501 - val_loss: 1.0373 - val_mae: 0.8472 - val_rmse: 0.9982 - val_smape: 1.4972

Epoch 2/128

144/144 - 1s - 8ms/step - ia: 0.2487 - loss: 1.1708 - mae: 0.8930 - rmse: 1.0807 - smape: 1.4790 - val_ia: 0.2283 - val_loss: 0.9662 - val_mae: 0.8175 - val_rmse: 0.9663 - val_smape: 1.5476

Epoch 3/128

144/144 - 1s - 8ms/step - ia: 0.2301 - loss: 1.1322 - mae: 0.8789 - rmse: 1.0630 - smape: 1.5139 - val_ia: 0.2168 - val_loss: 0.9185 - val_mae: 0.7976 - val_rmse: 0.9445 - val_smape: 1.6105

Epoch 4/128

144/144 - 1s - 8ms/step - ia: 0.2187 - loss: 1.1066 - mae: 0.8706 - rmse: 1.0511 - smape: 1.5406 - val_ia: 0.2128 - val_loss: 0.8874 - val_mae: 0.7844 - val_rmse: 0.9301 - val_smape: 1.6777

Epoch 5/128

144/144 - 1s - 8ms/step - ia: 0.2121 - loss: 1.0891 - mae: 0.8629 - rmse: 1.0428 - smape: 1.5585 - val_ia: 0.2132 - val_loss: 0.8674 - val_mae: 0.7758 - val_rmse: 0.9207 - val_smape: 1.7416

Epoch 6/128

144/144 - 1s - 8ms/step - ia: 0.2066 - loss: 1.0795 - mae: 0.8609 - rmse: 1.0384 - smape: 1.5701 - val_ia: 0.2142 - val_loss: 0.8538 - val_mae: 0.7696 - val_rmse: 0.9142 - val_smape: 1.7905

Epoch 7/128

144/144 - 1s - 8ms/step - ia: 0.2077 - loss: 1.0698 - mae: 0.8565 - rmse: 1.0338 - smape: 1.5686 - val_ia: 0.2158 - val_loss: 0.8453 - val_mae: 0.7657 - val_rmse: 0.9101 - val_smape: 1.8021

Epoch 8/128

144/144 - 1s - 8ms/step - ia: 0.2092 - loss: 1.0585 - mae: 0.8522 - rmse: 1.0287 - smape: 1.5693 - val_ia: 0.2176 - val_loss: 0.8385 - val_mae: 0.7625 - val_rmse: 0.9067 - val_smape: 1.7919

Epoch 9/128

144/144 - 1s - 8ms/step - ia: 0.2081 - loss: 1.0497 - mae: 0.8498 - rmse: 1.0238 - smape: 1.5716 - val_ia: 0.2193 - val_loss: 0.8328 - val_mae: 0.7599 - val_rmse: 0.9039 - val_smape: 1.7749

Epoch 10/128

144/144 - 1s - 8ms/step - ia: 0.2090 - loss: 1.0381 - mae: 0.8454 - rmse: 1.0181 - smape: 1.5685 - val_ia: 0.2211 - val_loss: 0.8277 - val_mae: 0.7574 - val_rmse: 0.9012 - val_smape: 1.7569

Epoch 11/128

144/144 - 1s - 8ms/step - ia: 0.2064 - loss: 1.0349 - mae: 0.8463 - rmse: 1.0166 - smape: 1.5719 - val_ia: 0.2229 - val_loss: 0.8239 - val_mae: 0.7557 - val_rmse: 0.8992 - val_smape: 1.7399

Epoch 12/128

144/144 - 1s - 8ms/step - ia: 0.2104 - loss: 1.0202 - mae: 0.8402 - rmse: 1.0094 - smape: 1.5678 - val_ia: 0.2250 - val_loss: 0.8192 - val_mae: 0.7534 - val_rmse: 0.8967 - val_smape: 1.7221

Epoch 13/128

144/144 - 1s - 8ms/step - ia: 0.2157 - loss: 1.0058 - mae: 0.8338 - rmse: 1.0024 - smape: 1.5555 - val_ia: 0.2269 - val_loss: 0.8161 - val_mae: 0.7520 - val_rmse: 0.8950 - val_smape: 1.7052

Epoch 14/128

144/144 - 1s - 8ms/step - ia: 0.2165 - loss: 1.0037 - mae: 0.8324 - rmse: 1.0004 - smape: 1.5553 - val_ia: 0.2290 - val_loss: 0.8128 - val_mae: 0.7505 - val_rmse: 0.8932 - val_smape: 1.6884

Epoch 15/128

144/144 - 1s - 8ms/step - ia: 0.2149 - loss: 0.9993 - mae: 0.8324 - rmse: 0.9992 - smape: 1.5572 - val_ia: 0.2314 - val_loss: 0.8091 - val_mae: 0.7487 - val_rmse: 0.8911 - val_smape: 1.6714

Epoch 16/128

144/144 - 1s - 8ms/step - ia: 0.2214 - loss: 0.9848 - mae: 0.8265 - rmse: 0.9917 - smape: 1.5481 - val_ia: 0.2337 - val_loss: 0.8074 - val_mae: 0.7479 - val_rmse: 0.8900 - val_smape: 1.6547

Epoch 17/128

144/144 - 1s - 8ms/step - ia: 0.2224 - loss: 0.9750 - mae: 0.8226 - rmse: 0.9879 - smape: 1.5433 - val_ia: 0.2368 - val_loss: 0.8031 - val_mae: 0.7458 - val_rmse: 0.8876 - val_smape: 1.6371

Epoch 18/128

144/144 - 1s - 8ms/step - ia: 0.2229 - loss: 0.9739 - mae: 0.8222 - rmse: 0.9857 - smape: 1.5424 - val_ia: 0.2399 - val_loss: 0.7997 - val_mae: 0.7441 - val_rmse: 0.8856 - val_smape: 1.6191

Epoch 19/128

144/144 - 1s - 8ms/step - ia: 0.2296 - loss: 0.9592 - mae: 0.8163 - rmse: 0.9787 - smape: 1.5323 - val_ia: 0.2436 - val_loss: 0.7956 - val_mae: 0.7421 - val_rmse: 0.8833 - val_smape: 1.6003

Epoch 20/128

144/144 - 1s - 8ms/step - ia: 0.2339 - loss: 0.9496 - mae: 0.8122 - rmse: 0.9735 - smape: 1.5246 - val_ia: 0.2477 - val_loss: 0.7908 - val_mae: 0.7396 - val_rmse: 0.8805 - val_smape: 1.5819

Epoch 21/128

144/144 - 1s - 8ms/step - ia: 0.2396 - loss: 0.9386 - mae: 0.8083 - rmse: 0.9687 - smape: 1.5163 - val_ia: 0.2522 - val_loss: 0.7879 - val_mae: 0.7380 - val_rmse: 0.8787 - val_smape: 1.5630

Epoch 22/128

144/144 - 1s - 8ms/step - ia: 0.2474 - loss: 0.9227 - mae: 0.8012 - rmse: 0.9609 - smape: 1.5052 - val_ia: 0.2574 - val_loss: 0.7837 - val_mae: 0.7357 - val_rmse: 0.8761 - val_smape: 1.5432

Epoch 23/128

144/144 - 1s - 8ms/step - ia: 0.2526 - loss: 0.9205 - mae: 0.7999 - rmse: 0.9587 - smape: 1.4948 - val_ia: 0.2631 - val_loss: 0.7793 - val_mae: 0.7334 - val_rmse: 0.8735 - val_smape: 1.5242

Epoch 24/128

144/144 - 1s - 8ms/step - ia: 0.2586 - loss: 0.9052 - mae: 0.7938 - rmse: 0.9506 - smape: 1.4882 - val_ia: 0.2696 - val_loss: 0.7755 - val_mae: 0.7312 - val_rmse: 0.8711 - val_smape: 1.5046

Epoch 25/128

144/144 - 1s - 8ms/step - ia: 0.2671 - loss: 0.8896 - mae: 0.7876 - rmse: 0.9421 - smape: 1.4773 - val_ia: 0.2767 - val_loss: 0.7715 - val_mae: 0.7290 - val_rmse: 0.8685 - val_smape: 1.4851

Epoch 26/128

144/144 - 1s - 8ms/step - ia: 0.2726 - loss: 0.8848 - mae: 0.7857 - rmse: 0.9399 - smape: 1.4709 - val_ia: 0.2842 - val_loss: 0.7690 - val_mae: 0.7275 - val_rmse: 0.8667 - val_smape: 1.4671

Epoch 27/128

144/144 - 1s - 7ms/step - ia: 0.2836 - loss: 0.8671 - mae: 0.7780 - rmse: 0.9306 - smape: 1.4567 - val_ia: 0.2919 - val_loss: 0.7627 - val_mae: 0.7242 - val_rmse: 0.8629 - val_smape: 1.4477

Epoch 28/128

144/144 - 1s - 7ms/step - ia: 0.2910 - loss: 0.8594 - mae: 0.7745 - rmse: 0.9260 - smape: 1.4467 - val_ia: 0.3003 - val_loss: 0.7604 - val_mae: 0.7229 - val_rmse: 0.8611 - val_smape: 1.4306

Epoch 29/128

144/144 - 1s - 7ms/step - ia: 0.3000 - loss: 0.8467 - mae: 0.7690 - rmse: 0.9202 - smape: 1.4325 - val_ia: 0.3090 - val_loss: 0.7587 - val_mae: 0.7218 - val_rmse: 0.8596 - val_smape: 1.4141

Epoch 30/128

144/144 - 1s - 7ms/step - ia: 0.3106 - loss: 0.8343 - mae: 0.7633 - rmse: 0.9126 - smape: 1.4193 - val_ia: 0.3176 - val_loss: 0.7557 - val_mae: 0.7201 - val_rmse: 0.8575 - val_smape: 1.3981

Epoch 31/128

144/144 - 1s - 8ms/step - ia: 0.3216 - loss: 0.8186 - mae: 0.7561 - rmse: 0.9042 - smape: 1.4050 - val_ia: 0.3262 - val_loss: 0.7524 - val_mae: 0.7183 - val_rmse: 0.8551 - val_smape: 1.3823

Epoch 32/128

144/144 - 1s - 8ms/step - ia: 0.3331 - loss: 0.8059 - mae: 0.7494 - rmse: 0.8970 - smape: 1.3877 - val_ia: 0.3347 - val_loss: 0.7518 - val_mae: 0.7177 - val_rmse: 0.8542 - val_smape: 1.3687

Epoch 33/128

144/144 - 1s - 8ms/step - ia: 0.3426 - loss: 0.7925 - mae: 0.7450 - rmse: 0.8895 - smape: 1.3750 - val_ia: 0.3431 - val_loss: 0.7536 - val_mae: 0.7181 - val_rmse: 0.8545 - val_smape: 1.3561

Epoch 34/128

144/144 - 1s - 8ms/step - ia: 0.3532 - loss: 0.7841 - mae: 0.7388 - rmse: 0.8844 - smape: 1.3575 - val_ia: 0.3509 - val_loss: 0.7553 - val_mae: 0.7185 - val_rmse: 0.8548 - val_smape: 1.3446

Epoch 35/128

144/144 - 1s - 8ms/step - ia: 0.3686 - loss: 0.7605 - mae: 0.7286 - rmse: 0.8722 - smape: 1.3377 - val_ia: 0.3586 - val_loss: 0.7563 - val_mae: 0.7184 - val_rmse: 0.8546 - val_smape: 1.3322

Epoch 36/128

144/144 - 1s - 8ms/step - ia: 0.3807 - loss: 0.7480 - mae: 0.7226 - rmse: 0.8639 - smape: 1.3221 - val_ia: 0.3660 - val_loss: 0.7618 - val_mae: 0.7204 - val_rmse: 0.8569 - val_smape: 1.3222

Epoch 37/128

144/144 - 1s - 8ms/step - ia: 0.3928 - loss: 0.7365 - mae: 0.7155 - rmse: 0.8580 - smape: 1.3041 - val_ia: 0.3734 - val_loss: 0.7621 - val_mae: 0.7199 - val_rmse: 0.8565 - val_smape: 1.3107

Epoch 38/128

144/144 - 1s - 8ms/step - ia: 0.4049 - loss: 0.7228 - mae: 0.7080 - rmse: 0.8492 - smape: 1.2862 - val_ia: 0.3812 - val_loss: 0.7719 - val_mae: 0.7236 - val_rmse: 0.8612 - val_smape: 1.3026

Epoch 39/128

144/144 - 1s - 8ms/step - ia: 0.4176 - loss: 0.7090 - mae: 0.7013 - rmse: 0.8409 - smape: 1.2663 - val_ia: 0.3892 - val_loss: 0.7767 - val_mae: 0.7252 - val_rmse: 0.8632 - val_smape: 1.2937

Epoch 40/128

144/144 - 1s - 8ms/step - ia: 0.4284 - loss: 0.6954 - mae: 0.6942 - rmse: 0.8330 - smape: 1.2520 - val_ia: 0.3970 - val_loss: 0.7893 - val_mae: 0.7302 - val_rmse: 0.8694 - val_smape: 1.2883

Epoch 41/128

144/144 - 1s - 8ms/step - ia: 0.4417 - loss: 0.6795 - mae: 0.6857 - rmse: 0.8239 - smape: 1.2338 - val_ia: 0.4039 - val_loss: 0.8013 - val_mae: 0.7350 - val_rmse: 0.8753 - val_smape: 1.2836

Epoch 42/128

144/144 - 1s - 8ms/step - ia: 0.4524 - loss: 0.6695 - mae: 0.6787 - rmse: 0.8176 - smape: 1.2153 - val_ia: 0.4102 - val_loss: 0.8129 - val_mae: 0.7396 - val_rmse: 0.8810 - val_smape: 1.2789

Epoch 43/128

144/144 - 1s - 8ms/step - ia: 0.4638 - loss: 0.6566 - mae: 0.6713 - rmse: 0.8098 - smape: 1.1992 - val_ia: 0.4155 - val_loss: 0.8307 - val_mae: 0.7470 - val_rmse: 0.8900 - val_smape: 1.2769

Epoch 44/128

144/144 - 1s - 8ms/step - ia: 0.4767 - loss: 0.6432 - mae: 0.6626 - rmse: 0.8015 - smape: 1.1793 - val_ia: 0.4202 - val_loss: 0.8434 - val_mae: 0.7522 - val_rmse: 0.8962 - val_smape: 1.2738

Epoch 45/128

144/144 - 1s - 8ms/step - ia: 0.4864 - loss: 0.6285 - mae: 0.6550 - rmse: 0.7917 - smape: 1.1657 - val_ia: 0.4241 - val_loss: 0.8599 - val_mae: 0.7590 - val_rmse: 0.9045 - val_smape: 1.2716

Epoch 46/128

144/144 - 1s - 8ms/step - ia: 0.4969 - loss: 0.6198 - mae: 0.6488 - rmse: 0.7869 - smape: 1.1495 - val_ia: 0.4266 - val_loss: 0.8795 - val_mae: 0.7675 - val_rmse: 0.9144 - val_smape: 1.2721

Epoch 47/128

144/144 - 1s - 8ms/step - ia: 0.5091 - loss: 0.6049 - mae: 0.6401 - rmse: 0.7771 - smape: 1.1317 - val_ia: 0.4288 - val_loss: 0.8954 - val_mae: 0.7744 - val_rmse: 0.9222 - val_smape: 1.2725

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 51s 318ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/8

 94%|█████████▍| 47/50 [11:56:36<28:55, 578.52s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4584/4584 - 74s - 16ms/step - ia: 0.7781 - loss: 0.1734 - mae: 0.3101 - rmse: 0.3869 - smape: 0.6692 - val_ia: 0.2767 - val_loss: 0.1899 - val_mae: 0.3355 - val_rmse: 0.3501 - val_smape: 0.6809

Epoch 2/8

4584/4584 - 63s - 14ms/step - ia: 0.8372 - loss: 0.0964 - mae: 0.2296 - rmse: 0.2925 - smape: 0.5445 - val_ia: 0.2802 - val_loss: 0.1460 - val_mae: 0.2977 - val_rmse: 0.3157 - val_smape: 0.6386

Epoch 3/8

4584/4584 - 61s - 13ms/step - ia: 0.8548 - loss: 0.0787 - mae: 0.2067 - rmse: 0.2639 - smape: 0.4954 - val_ia: 0.2333 - val_loss: 0.2309 - val_mae: 0.3770 - val_rmse: 0.3972 - val_smape: 0.7411

Epoch 4/8

4584/4584 - 60s - 13ms/step - ia: 0.8636 - loss: 0.0690 - mae: 0.1933 - rmse: 0.2471 - smape: 0.4741 - val_ia: 0.2477 - val_loss: 0.2055 - val_mae: 0.3490 - val_rmse: 0.3720 - val_smape: 0.7078

Epoch 5/8

4584/4584 - 60s - 13ms/step - ia: 0.8724 - loss: 0.0613 - mae: 0.1815 - rmse: 0.2326 - smape: 0.4488 - val_ia: 0.2359 - val_loss: 0.2197 - val_mae: 0.3753 - val_rmse: 0.3932 - val_smape: 0.7594

Epoch 6/8

4584/4584 - 60s - 13ms/step - ia: 0.8777 - loss: 0.0563 - mae: 0.1736 - rmse: 0.2222 - smape: 0.4367 - val_ia: 0.2852 - val_loss: 0.1519 - val_mae: 0.2960 - val_rmse: 0.3178 - val_smape: 0.6452

Epoch 7/8

4584/4584 - 60s - 13ms/step - ia: 0.8815 - loss: 0.0532 - mae: 0.1686 - rmse: 0.2160 - smape: 0.4262 - val_ia: 0.2863 - val_loss: 0.1611 - val_mae: 0.3078 - val_rmse: 0.3304 - val_smape: 0.6846

Epoch 8/8

4584/4584 - 60s - 13ms/step - ia: 0.8861 - loss: 0.0505 - mae: 0.1638 - rmse: 0.2100 - smape: 0.4155 - val_ia: 0.2801 - val_loss: 0.1526 - val_mae: 0.2994 - val_rmse: 0.3206 - val_smape: 0.6677

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:44 646ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

Epoch 1/16

 96%|█████████▌| 48/50 [12:04:57<18:30, 555.00s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

573/573 - 11s - 20ms/step - ia: 0.3611 - loss: 0.9885 - mae: 0.8382 - rmse: 0.9921 - smape: 1.3854 - val_ia: 0.2812 - val_loss: 0.8013 - val_mae: 0.7500 - val_rmse: 0.8600 - val_smape: 1.3459

Epoch 2/16

573/573 - 5s - 9ms/step - ia: 0.3499 - loss: 0.9321 - mae: 0.8151 - rmse: 0.9634 - smape: 1.3968 - val_ia: 0.2872 - val_loss: 0.7806 - val_mae: 0.7384 - val_rmse: 0.8468 - val_smape: 1.3560

Epoch 3/16

573/573 - 5s - 9ms/step - ia: 0.3455 - loss: 0.8876 - mae: 0.7936 - rmse: 0.9402 - smape: 1.4023 - val_ia: 0.2934 - val_loss: 0.7678 - val_mae: 0.7304 - val_rmse: 0.8384 - val_smape: 1.3640

Epoch 4/16

573/573 - 5s - 9ms/step - ia: 0.3366 - loss: 0.8622 - mae: 0.7821 - rmse: 0.9268 - smape: 1.4097 - val_ia: 0.2990 - val_loss: 0.7594 - val_mae: 0.7247 - val_rmse: 0.8328 - val_smape: 1.3684

Epoch 5/16

573/573 - 5s - 9ms/step - ia: 0.3315 - loss: 0.8442 - mae: 0.7729 - rmse: 0.9165 - smape: 1.4158 - val_ia: 0.3041 - val_loss: 0.7533 - val_mae: 0.7203 - val_rmse: 0.8285 - val_smape: 1.3716

Epoch 6/16

573/573 - 5s - 9ms/step - ia: 0.3315 - loss: 0.8261 - mae: 0.7624 - rmse: 0.9071 - smape: 1.4134 - val_ia: 0.3089 - val_loss: 0.7485 - val_mae: 0.7169 - val_rmse: 0.8251 - val_smape: 1.3711

Epoch 7/16

573/573 - 5s - 9ms/step - ia: 0.3348 - loss: 0.8088 - mae: 0.7540 - rmse: 0.8972 - smape: 1.4078 - val_ia: 0.3137 - val_loss: 0.7451 - val_mae: 0.7142 - val_rmse: 0.8223 - val_smape: 1.3684

Epoch 8/16

573/573 - 5s - 9ms/step - ia: 0.3383 - loss: 0.7926 - mae: 0.7452 - rmse: 0.8882 - smape: 1.3991 - val_ia: 0.3184 - val_loss: 0.7420 - val_mae: 0.7119 - val_rmse: 0.8196 - val_smape: 1.3633

Epoch 9/16

573/573 - 5s - 9ms/step - ia: 0.3430 - loss: 0.7782 - mae: 0.7380 - rmse: 0.8801 - smape: 1.3903 - val_ia: 0.3231 - val_loss: 0.7402 - val_mae: 0.7101 - val_rmse: 0.8175 - val_smape: 1.3569

Epoch 10/16

573/573 - 5s - 9ms/step - ia: 0.3523 - loss: 0.7615 - mae: 0.7286 - rmse: 0.8707 - smape: 1.3744 - val_ia: 0.3280 - val_loss: 0.7397 - val_mae: 0.7091 - val_rmse: 0.8160 - val_smape: 1.3491

Epoch 11/16

573/573 - 5s - 9ms/step - ia: 0.3650 - loss: 0.7452 - mae: 0.7188 - rmse: 0.8610 - smape: 1.3551 - val_ia: 0.3331 - val_loss: 0.7406 - val_mae: 0.7086 - val_rmse: 0.8151 - val_smape: 1.3402

Epoch 12/16

573/573 - 5s - 9ms/step - ia: 0.3788 - loss: 0.7233 - mae: 0.7064 - rmse: 0.8483 - smape: 1.3313 - val_ia: 0.3385 - val_loss: 0.7424 - val_mae: 0.7087 - val_rmse: 0.8146 - val_smape: 1.3307

Epoch 13/16

573/573 - 5s - 9ms/step - ia: 0.3905 - loss: 0.7117 - mae: 0.6996 - rmse: 0.8415 - smape: 1.3160 - val_ia: 0.3440 - val_loss: 0.7465 - val_mae: 0.7097 - val_rmse: 0.8153 - val_smape: 1.3206

Epoch 14/16

573/573 - 5s - 9ms/step - ia: 0.4080 - loss: 0.6884 - mae: 0.6855 - rmse: 0.8275 - smape: 1.2856 - val_ia: 0.3498 - val_loss: 0.7524 - val_mae: 0.7116 - val_rmse: 0.8168 - val_smape: 1.3108

Epoch 15/16

573/573 - 5s - 8ms/step - ia: 0.4210 - loss: 0.6741 - mae: 0.6774 - rmse: 0.8187 - smape: 1.2669 - val_ia: 0.3556 - val_loss: 0.7602 - val_mae: 0.7145 - val_rmse: 0.8194 - val_smape: 1.3020

Epoch 16/16

573/573 - 5s - 9ms/step - ia: 0.4363 - loss: 0.6580 - mae: 0.6677 - rmse: 0.8091 - smape: 1.2449 - val_ia: 0.3612 - val_loss: 0.7707 - val_mae: 0.7187 - val_rmse: 0.8234 - val_smape: 1.2940

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:14 458ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/32

 98%|█████████▊| 49/50 [12:06:30<06:56, 416.46s/trial, best loss: 0.1011223877819723]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 12s - 42ms/step - ia: 0.3033 - loss: 1.5565 - mae: 1.0118 - rmse: 1.2440 - smape: 1.4331 - val_ia: 0.2534 - val_loss: 0.8918 - val_mae: 0.7638 - val_rmse: 0.9344 - val_smape: 1.2844

Epoch 2/32

287/287 - 4s - 15ms/step - ia: 0.2635 - loss: 1.2923 - mae: 0.9303 - rmse: 1.1351 - smape: 1.4921 - val_ia: 0.2463 - val_loss: 0.8350 - val_mae: 0.7529 - val_rmse: 0.9079 - val_smape: 1.4954

Epoch 3/32

287/287 - 4s - 15ms/step - ia: 0.2463 - loss: 1.2199 - mae: 0.9073 - rmse: 1.1026 - smape: 1.5094 - val_ia: 0.2283 - val_loss: 0.8426 - val_mae: 0.7619 - val_rmse: 0.9119 - val_smape: 1.7225

Epoch 4/32

287/287 - 4s - 15ms/step - ia: 0.2434 - loss: 1.1860 - mae: 0.8948 - rmse: 1.0875 - smape: 1.5107 - val_ia: 0.2199 - val_loss: 0.8507 - val_mae: 0.7669 - val_rmse: 0.9159 - val_smape: 1.8478

Epoch 5/32

287/287 - 4s - 15ms/step - ia: 0.2356 - loss: 1.1643 - mae: 0.8897 - rmse: 1.0774 - smape: 1.5215 - val_ia: 0.2173 - val_loss: 0.8540 - val_mae: 0.7687 - val_rmse: 0.9174 - val_smape: 1.9033

Epoch 6/32

287/287 - 4s - 15ms/step - ia: 0.2295 - loss: 1.1443 - mae: 0.8835 - rmse: 1.0682 - smape: 1.5313 - val_ia: 0.2168 - val_loss: 0.8544 - val_mae: 0.7690 - val_rmse: 0.9177 - val_smape: 1.9157

Epoch 7/32

287/287 - 4s - 15ms/step - ia: 0.2207 - loss: 1.1296 - mae: 0.8783 - rmse: 1.0614 - smape: 1.5422 - val_ia: 0.2167 - val_loss: 0.8544 - val_mae: 0.7690 - val_rmse: 0.9176 - val_smape: 1.9195

Epoch 8/32

287/287 - 4s - 15ms/step - ia: 0.2172 - loss: 1.1166 - mae: 0.8725 - rmse: 1.0554 - smape: 1.5468 - val_ia: 0.2164 - val_loss: 0.8546 - val_mae: 0.7691 - val_rmse: 0.9177 - val_smape: 1.9286

Epoch 9/32

287/287 - 4s - 14ms/step - ia: 0.2079 - loss: 1.1049 - mae: 0.8694 - rmse: 1.0498 - smape: 1.5584 - val_ia: 0.2159 - val_loss: 0.8555 - val_mae: 0.7696 - val_rmse: 0.9182 - val_smape: 1.9496

Epoch 10/32

287/287 - 4s - 14ms/step - ia: 0.1993 - loss: 1.0854 - mae: 0.8635 - rmse: 1.0403 - smape: 1.5746 - val_ia: 0.2152 - val_loss: 0.8570 - val_mae: 0.7704 - val_rmse: 0.9188 - val_smape: 1.9707

Epoch 11/32

287/287 - 4s - 15ms/step - ia: 0.1939 - loss: 1.0749 - mae: 0.8585 - rmse: 1.0352 - smape: 1.5789 - val_ia: 0.2154 - val_loss: 0.8563 - val_mae: 0.7701 - val_rmse: 0.9185 - val_smape: 1.9667

Epoch 12/32

287/287 - 4s - 15ms/step - ia: 0.1861 - loss: 1.0654 - mae: 0.8548 - rmse: 1.0312 - smape: 1.5894 - val_ia: 0.2151 - val_loss: 0.8571 - val_mae: 0.7705 - val_rmse: 0.9189 - val_smape: 1.9658

Epoch 13/32

287/287 - 4s - 15ms/step - ia: 0.1812 - loss: 1.0558 - mae: 0.8515 - rmse: 1.0260 - smape: 1.5988 - val_ia: 0.2163 - val_loss: 0.8543 - val_mae: 0.7691 - val_rmse: 0.9175 - val_smape: 1.9502

Epoch 14/32

287/287 - 4s - 15ms/step - ia: 0.1725 - loss: 1.0501 - mae: 0.8497 - rmse: 1.0237 - smape: 1.6141 - val_ia: 0.2159 - val_loss: 0.8549 - val_mae: 0.7694 - val_rmse: 0.9177 - val_smape: 1.9565

Epoch 15/32

287/287 - 4s - 15ms/step - ia: 0.1678 - loss: 1.0434 - mae: 0.8468 - rmse: 1.0203 - smape: 1.6200 - val_ia: 0.2162 - val_loss: 0.8541 - val_mae: 0.7690 - val_rmse: 0.9173 - val_smape: 1.9509

Epoch 16/32

287/287 - 4s - 15ms/step - ia: 0.1614 - loss: 1.0343 - mae: 0.8444 - rmse: 1.0158 - smape: 1.6312 - val_ia: 0.2158 - val_loss: 0.8547 - val_mae: 0.7694 - val_rmse: 0.9176 - val_smape: 1.9444

Epoch 17/32

287/287 - 4s - 15ms/step - ia: 0.1563 - loss: 1.0358 - mae: 0.8441 - rmse: 1.0163 - smape: 1.6410 - val_ia: 0.2170 - val_loss: 0.8518 - val_mae: 0.7679 - val_rmse: 0.9161 - val_smape: 1.9352

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:42 630ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

100%|██████████| 50/50 [12:07:52<00:00, 873.44s/trial, best loss: 0.1011223877819723]

In [22]:
print(best)

{'activation': 1, 'batch': 1, 'dropout': 0.0, 'epochs': 2, 'layers': 4.0, 'learning_rate': 0.0007611975499647884, 'units': 0}