Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv('C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNconsumptionFinal.csv')

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(14)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823
2017-01-01 02:10:00 -2.308740 -1.464790 -1.131650 -0.649995 -1.371823

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [15]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 12, 5)
Las dimensiones de testX son:  (10529, 12, 5)
Las dimensiones de valX son:  (5186, 12, 5)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 41s - 36ms/step - ia: 0.5137 - loss: 0.5678 - mae: 0.6075 - rmse: 0.7410 - smape: 1.1347 - val_ia: 0.2906 - val_loss: 0.8048 - val_mae: 0.7546 - val_rmse: 0.8206 - val_smape: 1.1816

Epoch 2/128

1146/1146 - 35s - 31ms/step - ia: 0.6716 - loss: 0.3614 - mae: 0.4801 - rmse: 0.5958 - smape: 0.8450 - val_ia: 0.3615 - val_loss: 0.4392 - val_mae: 0.5360 - val_rmse: 0.5984 - val_smape: 0.9135

Epoch 3/128

1146/1146 - 21s - 18ms/step - ia: 0.7109 - loss: 0.2917 - mae: 0.4274 - rmse: 0.5351 - smape: 0.8021 - val_ia: 0.4030 - val_loss: 0.3451 - val_mae: 0.4800 - val_rmse: 0.5379 - val_smape: 0.9407

Epoch 4/128

1146/1146 - 16s - 14ms/step - ia: 0.7325 - loss: 0.2541 - mae: 0.3975 - rmse: 0.4995 - smape: 0.7790 - val_ia: 0.4215 - val_loss: 0.2986 - val_mae: 0.4526 - val_rmse: 0.5083 - val_smape: 0.9837

Epoch 5/128

1146/1146 - 22s - 19ms/step - ia: 0.7502 - loss: 0.2256 - mae: 0.3718 - rmse: 0.4703 - smape: 0.7561 - val_ia: 0.4501 - val_loss: 0.2456 - val_mae: 0.4024 - val_rmse: 0.4616 - val_smape: 0.9359

Epoch 6/128

1146/1146 - 17s - 15ms/step - ia: 0.7611 - loss: 0.2092 - mae: 0.3571 - rmse: 0.4530 - smape: 0.7403 - val_ia: 0.4661 - val_loss: 0.2253 - val_mae: 0.3820 - val_rmse: 0.4379 - val_smape: 0.8570

Epoch 7/128

1146/1146 - 18s - 16ms/step - ia: 0.7695 - loss: 0.1957 - mae: 0.3455 - rmse: 0.4382 - smape: 0.7269 - val_ia: 0.4629 - val_loss: 0.2159 - val_mae: 0.3777 - val_rmse: 0.4305 - val_smape: 0.8386

Epoch 8/128

1146/1146 - 18s - 15ms/step - ia: 0.7762 - loss: 0.1876 - mae: 0.3363 - rmse: 0.4288 - smape: 0.7173 - val_ia: 0.4810 - val_loss: 0.2073 - val_mae: 0.3626 - val_rmse: 0.4174 - val_smape: 0.8062

Epoch 9/128

1146/1146 - 21s - 18ms/step - ia: 0.7798 - loss: 0.1823 - mae: 0.3312 - rmse: 0.4225 - smape: 0.7129 - val_ia: 0.4755 - val_loss: 0.2051 - val_mae: 0.3648 - val_rmse: 0.4183 - val_smape: 0.8135

Epoch 10/128

1146/1146 - 15s - 13ms/step - ia: 0.7831 - loss: 0.1774 - mae: 0.3258 - rmse: 0.4167 - smape: 0.7038 - val_ia: 0.4772 - val_loss: 0.2087 - val_mae: 0.3661 - val_rmse: 0.4203 - val_smape: 0.7959

Epoch 11/128

1146/1146 - 15s - 13ms/step - ia: 0.7871 - loss: 0.1723 - mae: 0.3209 - rmse: 0.4107 - smape: 0.7018 - val_ia: 0.5004 - val_loss: 0.1898 - val_mae: 0.3417 - val_rmse: 0.3939 - val_smape: 0.7606

Epoch 12/128

1146/1146 - 21s - 18ms/step - ia: 0.7899 - loss: 0.1676 - mae: 0.3170 - rmse: 0.4051 - smape: 0.6940 - val_ia: 0.4659 - val_loss: 0.2269 - val_mae: 0.3802 - val_rmse: 0.4361 - val_smape: 0.8072

Epoch 13/128

1146/1146 - 22s - 19ms/step - ia: 0.7918 - loss: 0.1647 - mae: 0.3146 - rmse: 0.4015 - smape: 0.6919 - val_ia: 0.4722 - val_loss: 0.2137 - val_mae: 0.3717 - val_rmse: 0.4261 - val_smape: 0.7961

Epoch 14/128

1146/1146 - 20s - 17ms/step - ia: 0.7936 - loss: 0.1624 - mae: 0.3116 - rmse: 0.3989 - smape: 0.6851 - val_ia: 0.4842 - val_loss: 0.1989 - val_mae: 0.3586 - val_rmse: 0.4101 - val_smape: 0.7804

Epoch 15/128

1146/1146 - 15s - 13ms/step - ia: 0.7950 - loss: 0.1608 - mae: 0.3105 - rmse: 0.3969 - smape: 0.6812 - val_ia: 0.4864 - val_loss: 0.2025 - val_mae: 0.3630 - val_rmse: 0.4161 - val_smape: 0.7785

Epoch 16/128

1146/1146 - 20s - 18ms/step - ia: 0.7962 - loss: 0.1603 - mae: 0.3091 - rmse: 0.3963 - smape: 0.6762 - val_ia: 0.4638 - val_loss: 0.2161 - val_mae: 0.3764 - val_rmse: 0.4306 - val_smape: 0.8163

Epoch 17/128

1146/1146 - 16s - 14ms/step - ia: 0.7986 - loss: 0.1561 - mae: 0.3058 - rmse: 0.3910 - smape: 0.6720 - val_ia: 0.4638 - val_loss: 0.2226 - val_mae: 0.3806 - val_rmse: 0.4354 - val_smape: 0.8154

Epoch 18/128

1146/1146 - 14s - 12ms/step - ia: 0.7997 - loss: 0.1541 - mae: 0.3043 - rmse: 0.3883 - smape: 0.6682 - val_ia: 0.4825 - val_loss: 0.2002 - val_mae: 0.3624 - val_rmse: 0.4120 - val_smape: 0.7788

Epoch 19/128

1146/1146 - 12s - 10ms/step - ia: 0.8008 - loss: 0.1529 - mae: 0.3024 - rmse: 0.3867 - smape: 0.6643 - val_ia: 0.4957 - val_loss: 0.1821 - val_mae: 0.3456 - val_rmse: 0.3913 - val_smape: 0.7601

Epoch 20/128

1146/1146 - 14s - 12ms/step - ia: 0.8018 - loss: 0.1525 - mae: 0.3016 - rmse: 0.3863 - smape: 0.6606 - val_ia: 0.4701 - val_loss: 0.2240 - val_mae: 0.3796 - val_rmse: 0.4353 - val_smape: 0.7956

Epoch 21/128

1146/1146 - 16s - 14ms/step - ia: 0.8025 - loss: 0.1516 - mae: 0.3007 - rmse: 0.3853 - smape: 0.6574 - val_ia: 0.4781 - val_loss: 0.2041 - val_mae: 0.3676 - val_rmse: 0.4183 - val_smape: 0.7919

Epoch 22/128

1146/1146 - 17s - 15ms/step - ia: 0.8028 - loss: 0.1509 - mae: 0.2998 - rmse: 0.3840 - smape: 0.6582 - val_ia: 0.4820 - val_loss: 0.2017 - val_mae: 0.3635 - val_rmse: 0.4125 - val_smape: 0.7661

Epoch 23/128

1146/1146 - 17s - 15ms/step - ia: 0.8045 - loss: 0.1479 - mae: 0.2977 - rmse: 0.3803 - smape: 0.6519 - val_ia: 0.4780 - val_loss: 0.2111 - val_mae: 0.3705 - val_rmse: 0.4236 - val_smape: 0.7879

Epoch 24/128

1146/1146 - 18s - 16ms/step - ia: 0.8058 - loss: 0.1477 - mae: 0.2959 - rmse: 0.3800 - smape: 0.6495 - val_ia: 0.4844 - val_loss: 0.2057 - val_mae: 0.3651 - val_rmse: 0.4170 - val_smape: 0.7691

Epoch 25/128

1146/1146 - 23s - 20ms/step - ia: 0.8060 - loss: 0.1468 - mae: 0.2961 - rmse: 0.3790 - smape: 0.6500 - val_ia: 0.4861 - val_loss: 0.2063 - val_mae: 0.3662 - val_rmse: 0.4191 - val_smape: 0.7674

Epoch 26/128

1146/1146 - 20s - 17ms/step - ia: 0.8061 - loss: 0.1460 - mae: 0.2949 - rmse: 0.3779 - smape: 0.6485 - val_ia: 0.4724 - val_loss: 0.2237 - val_mae: 0.3801 - val_rmse: 0.4365 - val_smape: 0.7893

Epoch 27/128

1146/1146 - 12s - 11ms/step - ia: 0.8073 - loss: 0.1451 - mae: 0.2940 - rmse: 0.3767 - smape: 0.6467 - val_ia: 0.4842 - val_loss: 0.2128 - val_mae: 0.3696 - val_rmse: 0.4222 - val_smape: 0.7627

Epoch 28/128

1146/1146 - 16s - 14ms/step - ia: 0.8085 - loss: 0.1438 - mae: 0.2925 - rmse: 0.3754 - smape: 0.6414 - val_ia: 0.4801 - val_loss: 0.2087 - val_mae: 0.3676 - val_rmse: 0.4189 - val_smape: 0.7716

Epoch 29/128

1146/1146 - 14s - 13ms/step - ia: 0.8083 - loss: 0.1437 - mae: 0.2920 - rmse: 0.3749 - smape: 0.6432 - val_ia: 0.4780 - val_loss: 0.2112 - val_mae: 0.3688 - val_rmse: 0.4222 - val_smape: 0.7778

Epoch 30/128

1146/1146 - 15s - 13ms/step - ia: 0.8097 - loss: 0.1424 - mae: 0.2908 - rmse: 0.3730 - smape: 0.6388 - val_ia: 0.4774 - val_loss: 0.2213 - val_mae: 0.3765 - val_rmse: 0.4284 - val_smape: 0.7689

Epoch 31/128

1146/1146 - 13s - 11ms/step - ia: 0.8087 - loss: 0.1420 - mae: 0.2914 - rmse: 0.3728 - smape: 0.6418 - val_ia: 0.4661 - val_loss: 0.2334 - val_mae: 0.3858 - val_rmse: 0.4434 - val_smape: 0.7872

Epoch 32/128

1146/1146 - 16s - 14ms/step - ia: 0.8111 - loss: 0.1397 - mae: 0.2886 - rmse: 0.3698 - smape: 0.6370 - val_ia: 0.4654 - val_loss: 0.2441 - val_mae: 0.3923 - val_rmse: 0.4497 - val_smape: 0.7837

Epoch 33/128

1146/1146 - 20s - 17ms/step - ia: 0.8117 - loss: 0.1394 - mae: 0.2874 - rmse: 0.3691 - smape: 0.6303 - val_ia: 0.4718 - val_loss: 0.2256 - val_mae: 0.3777 - val_rmse: 0.4342 - val_smape: 0.7721

Epoch 34/128

1146/1146 - 22s - 19ms/step - ia: 0.8116 - loss: 0.1388 - mae: 0.2879 - rmse: 0.3687 - smape: 0.6334 - val_ia: 0.4909 - val_loss: 0.2048 - val_mae: 0.3603 - val_rmse: 0.4137 - val_smape: 0.7479

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:27 1s/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

  2%|▏         | 1/50 [10:39<8:41:57, 639.14s/trial, best loss: 0.2300784981030546]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 48s - 335ms/step - ia: 0.6059 - loss: 0.4197 - mae: 0.5009 - rmse: 0.6223 - smape: 0.9672 - val_ia: 0.6604 - val_loss: 0.3152 - val_mae: 0.4667 - val_rmse: 0.5514 - val_smape: 0.9441

Epoch 2/16

144/144 - 26s - 182ms/step - ia: 0.8098 - loss: 0.1571 - mae: 0.3011 - rmse: 0.3948 - smape: 0.6509 - val_ia: 0.7015 - val_loss: 0.2749 - val_mae: 0.4092 - val_rmse: 0.5115 - val_smape: 0.9088

Epoch 3/16

144/144 - 40s - 280ms/step - ia: 0.8478 - loss: 0.1054 - mae: 0.2422 - rmse: 0.3233 - smape: 0.5865 - val_ia: 0.7330 - val_loss: 0.2322 - val_mae: 0.3719 - val_rmse: 0.4451 - val_smape: 0.8109

Epoch 4/16

144/144 - 36s - 248ms/step - ia: 0.8640 - loss: 0.0875 - mae: 0.2172 - rmse: 0.2955 - smape: 0.5446 - val_ia: 0.7500 - val_loss: 0.1691 - val_mae: 0.3302 - val_rmse: 0.4030 - val_smape: 0.7543

Epoch 5/16

144/144 - 33s - 229ms/step - ia: 0.8728 - loss: 0.0790 - mae: 0.2042 - rmse: 0.2801 - smape: 0.5212 - val_ia: 0.7822 - val_loss: 0.1516 - val_mae: 0.3070 - val_rmse: 0.3671 - val_smape: 0.6795

Epoch 6/16

144/144 - 30s - 211ms/step - ia: 0.8778 - loss: 0.0727 - mae: 0.1967 - rmse: 0.2685 - smape: 0.5045 - val_ia: 0.7839 - val_loss: 0.1402 - val_mae: 0.2957 - val_rmse: 0.3637 - val_smape: 0.6742

Epoch 7/16

144/144 - 41s - 284ms/step - ia: 0.8843 - loss: 0.0659 - mae: 0.1865 - rmse: 0.2561 - smape: 0.4879 - val_ia: 0.7751 - val_loss: 0.1759 - val_mae: 0.3245 - val_rmse: 0.3891 - val_smape: 0.6998

Epoch 8/16

144/144 - 33s - 230ms/step - ia: 0.8884 - loss: 0.0621 - mae: 0.1801 - rmse: 0.2485 - smape: 0.4725 - val_ia: 0.7833 - val_loss: 0.1647 - val_mae: 0.3118 - val_rmse: 0.3825 - val_smape: 0.6834

Epoch 9/16

144/144 - 35s - 245ms/step - ia: 0.8893 - loss: 0.0609 - mae: 0.1790 - rmse: 0.2463 - smape: 0.4699 - val_ia: 0.7864 - val_loss: 0.1574 - val_mae: 0.3043 - val_rmse: 0.3709 - val_smape: 0.6776

Epoch 10/16

144/144 - 28s - 193ms/step - ia: 0.8920 - loss: 0.0582 - mae: 0.1745 - rmse: 0.2408 - smape: 0.4606 - val_ia: 0.7742 - val_loss: 0.1872 - val_mae: 0.3281 - val_rmse: 0.4048 - val_smape: 0.6994

Epoch 11/16

144/144 - 39s - 271ms/step - ia: 0.8926 - loss: 0.0577 - mae: 0.1739 - rmse: 0.2395 - smape: 0.4591 - val_ia: 0.7948 - val_loss: 0.1523 - val_mae: 0.2993 - val_rmse: 0.3654 - val_smape: 0.6692

Epoch 12/16

144/144 - 29s - 203ms/step - ia: 0.8943 - loss: 0.0559 - mae: 0.1712 - rmse: 0.2357 - smape: 0.4556 - val_ia: 0.7913 - val_loss: 0.1645 - val_mae: 0.3036 - val_rmse: 0.3725 - val_smape: 0.6637

Epoch 13/16

144/144 - 28s - 193ms/step - ia: 0.8943 - loss: 0.0559 - mae: 0.1715 - rmse: 0.2353 - smape: 0.4557 - val_ia: 0.7778 - val_loss: 0.1795 - val_mae: 0.3178 - val_rmse: 0.3890 - val_smape: 0.6818

Epoch 14/16

144/144 - 48s - 334ms/step - ia: 0.8972 - loss: 0.0530 - mae: 0.1667 - rmse: 0.2292 - smape: 0.4462 - val_ia: 0.7773 - val_loss: 0.1872 - val_mae: 0.3229 - val_rmse: 0.4045 - val_smape: 0.6885

Epoch 15/16

144/144 - 27s - 190ms/step - ia: 0.8997 - loss: 0.0510 - mae: 0.1630 - rmse: 0.2250 - smape: 0.4379 - val_ia: 0.7791 - val_loss: 0.1633 - val_mae: 0.2966 - val_rmse: 0.3834 - val_smape: 0.6585

Epoch 16/16

144/144 - 33s - 232ms/step - ia: 0.8990 - loss: 0.0518 - mae: 0.1639 - rmse: 0.2268 - smape: 0.4394 - val_ia: 0.7625 - val_loss: 0.2211 - val_mae: 0.3473 - val_rmse: 0.4277 - val_smape: 0.7140

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:03 761ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

  4%|▍         | 2/50 [19:59<7:54:10, 592.71s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

573/573 - 42s - 74ms/step - ia: 0.0917 - loss: 1.0237 - mae: 0.8383 - rmse: 1.0096 - smape: 1.8857 - val_ia: 0.2782 - val_loss: 0.8794 - val_mae: 0.7818 - val_rmse: 0.8992 - val_smape: 1.9308

Epoch 2/8

573/573 - 14s - 24ms/step - ia: 0.0953 - loss: 1.0199 - mae: 0.8368 - rmse: 1.0076 - smape: 1.8866 - val_ia: 0.2789 - val_loss: 0.8762 - val_mae: 0.7802 - val_rmse: 0.8977 - val_smape: 1.9301

Epoch 3/8

573/573 - 10s - 17ms/step - ia: 0.0967 - loss: 1.0180 - mae: 0.8363 - rmse: 1.0065 - smape: 1.8877 - val_ia: 0.2795 - val_loss: 0.8731 - val_mae: 0.7787 - val_rmse: 0.8961 - val_smape: 1.9264

Epoch 4/8

573/573 - 11s - 18ms/step - ia: 0.0990 - loss: 1.0145 - mae: 0.8349 - rmse: 1.0049 - smape: 1.8883 - val_ia: 0.2801 - val_loss: 0.8701 - val_mae: 0.7771 - val_rmse: 0.8946 - val_smape: 1.9205

Epoch 5/8

573/573 - 8s - 15ms/step - ia: 0.0967 - loss: 1.0120 - mae: 0.8340 - rmse: 1.0036 - smape: 1.8860 - val_ia: 0.2807 - val_loss: 0.8671 - val_mae: 0.7756 - val_rmse: 0.8932 - val_smape: 1.9125

Epoch 6/8

573/573 - 6s - 10ms/step - ia: 0.0989 - loss: 1.0100 - mae: 0.8333 - rmse: 1.0026 - smape: 1.8837 - val_ia: 0.2813 - val_loss: 0.8642 - val_mae: 0.7741 - val_rmse: 0.8917 - val_smape: 1.9036

Epoch 7/8

573/573 - 10s - 18ms/step - ia: 0.1017 - loss: 1.0072 - mae: 0.8323 - rmse: 1.0013 - smape: 1.8807 - val_ia: 0.2818 - val_loss: 0.8613 - val_mae: 0.7726 - val_rmse: 0.8903 - val_smape: 1.8948

Epoch 8/8

573/573 - 5s - 9ms/step - ia: 0.0994 - loss: 1.0051 - mae: 0.8315 - rmse: 1.0003 - smape: 1.8778 - val_ia: 0.2823 - val_loss: 0.8585 - val_mae: 0.7712 - val_rmse: 0.8889 - val_smape: 1.8860

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:50 683ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

  6%|▌         | 3/50 [21:49<4:51:34, 372.22s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 42s - 147ms/step - ia: 0.1183 - loss: 0.9541 - mae: 0.8135 - rmse: 0.9755 - smape: 1.7521 - val_ia: 0.2451 - val_loss: 0.8052 - val_mae: 0.7461 - val_rmse: 0.8897 - val_smape: 1.6912

Epoch 2/32

287/287 - 18s - 63ms/step - ia: 0.2153 - loss: 0.8481 - mae: 0.7691 - rmse: 0.9198 - smape: 1.5655 - val_ia: 0.3024 - val_loss: 0.7513 - val_mae: 0.7194 - val_rmse: 0.8570 - val_smape: 1.5189

Epoch 3/32

287/287 - 8s - 27ms/step - ia: 0.3436 - loss: 0.7218 - mae: 0.7066 - rmse: 0.8482 - smape: 1.3666 - val_ia: 0.3808 - val_loss: 0.7510 - val_mae: 0.7196 - val_rmse: 0.8506 - val_smape: 1.4022

Epoch 4/32

287/287 - 8s - 27ms/step - ia: 0.4690 - loss: 0.5954 - mae: 0.6368 - rmse: 0.7705 - smape: 1.1866 - val_ia: 0.4265 - val_loss: 0.8923 - val_mae: 0.7837 - val_rmse: 0.9204 - val_smape: 1.3631

Epoch 5/32

287/287 - 10s - 36ms/step - ia: 0.5576 - loss: 0.5054 - mae: 0.5795 - rmse: 0.7097 - smape: 1.0505 - val_ia: 0.4320 - val_loss: 1.1170 - val_mae: 0.8770 - val_rmse: 1.0274 - val_smape: 1.3506

Epoch 6/32

287/287 - 12s - 42ms/step - ia: 0.6078 - loss: 0.4586 - mae: 0.5457 - rmse: 0.6759 - smape: 0.9674 - val_ia: 0.4289 - val_loss: 1.2769 - val_mae: 0.9400 - val_rmse: 1.0972 - val_smape: 1.3474

Epoch 7/32

287/287 - 18s - 63ms/step - ia: 0.6332 - loss: 0.4357 - mae: 0.5276 - rmse: 0.6585 - smape: 0.9218 - val_ia: 0.4300 - val_loss: 1.3136 - val_mae: 0.9542 - val_rmse: 1.1114 - val_smape: 1.3394

Epoch 8/32

287/287 - 10s - 35ms/step - ia: 0.6450 - loss: 0.4211 - mae: 0.5177 - rmse: 0.6476 - smape: 0.9043 - val_ia: 0.4330 - val_loss: 1.3054 - val_mae: 0.9506 - val_rmse: 1.1067 - val_smape: 1.3284

Epoch 9/32

287/287 - 11s - 38ms/step - ia: 0.6520 - loss: 0.4115 - mae: 0.5116 - rmse: 0.6404 - smape: 0.8933 - val_ia: 0.4357 - val_loss: 1.2834 - val_mae: 0.9424 - val_rmse: 1.0963 - val_smape: 1.3209

Epoch 10/32

287/287 - 10s - 35ms/step - ia: 0.6610 - loss: 0.3978 - mae: 0.5023 - rmse: 0.6293 - smape: 0.8764 - val_ia: 0.4410 - val_loss: 1.2500 - val_mae: 0.9271 - val_rmse: 1.0812 - val_smape: 1.3054

Epoch 11/32

287/287 - 10s - 33ms/step - ia: 0.6652 - loss: 0.3903 - mae: 0.4970 - rmse: 0.6232 - smape: 0.8686 - val_ia: 0.4474 - val_loss: 1.2144 - val_mae: 0.9092 - val_rmse: 1.0656 - val_smape: 1.2863

Epoch 12/32

287/287 - 12s - 41ms/step - ia: 0.6703 - loss: 0.3803 - mae: 0.4914 - rmse: 0.6154 - smape: 0.8626 - val_ia: 0.4510 - val_loss: 1.1835 - val_mae: 0.8961 - val_rmse: 1.0513 - val_smape: 1.2777

Epoch 13/32

287/287 - 19s - 65ms/step - ia: 0.6754 - loss: 0.3725 - mae: 0.4863 - rmse: 0.6091 - smape: 0.8543 - val_ia: 0.4568 - val_loss: 1.1549 - val_mae: 0.8797 - val_rmse: 1.0391 - val_smape: 1.2612

Epoch 14/32

287/287 - 11s - 39ms/step - ia: 0.6789 - loss: 0.3645 - mae: 0.4815 - rmse: 0.6023 - smape: 0.8475 - val_ia: 0.4627 - val_loss: 1.1274 - val_mae: 0.8643 - val_rmse: 1.0272 - val_smape: 1.2478

Epoch 15/32

287/287 - 11s - 37ms/step - ia: 0.6833 - loss: 0.3579 - mae: 0.4765 - rmse: 0.5969 - smape: 0.8410 - val_ia: 0.4680 - val_loss: 1.1030 - val_mae: 0.8510 - val_rmse: 1.0165 - val_smape: 1.2365

Epoch 16/32

287/287 - 10s - 36ms/step - ia: 0.6862 - loss: 0.3527 - mae: 0.4733 - rmse: 0.5929 - smape: 0.8361 - val_ia: 0.4720 - val_loss: 1.0670 - val_mae: 0.8350 - val_rmse: 0.9998 - val_smape: 1.2291

Epoch 17/32

287/287 - 10s - 36ms/step - ia: 0.6898 - loss: 0.3456 - mae: 0.4690 - rmse: 0.5867 - smape: 0.8315 - val_ia: 0.4756 - val_loss: 1.0458 - val_mae: 0.8238 - val_rmse: 0.9901 - val_smape: 1.2213

Epoch 18/32

287/287 - 11s - 37ms/step - ia: 0.6943 - loss: 0.3396 - mae: 0.4631 - rmse: 0.5815 - smape: 0.8251 - val_ia: 0.4778 - val_loss: 1.0360 - val_mae: 0.8175 - val_rmse: 0.9860 - val_smape: 1.2158

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:36 2s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step

  8%|▊         | 4/50 [25:55<4:07:17, 322.55s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4584/4584 - 58s - 13ms/step - ia: 0.2324 - loss: 1.0707 - mae: 0.8565 - rmse: 1.0135 - smape: 1.6075 - val_ia: 0.1370 - val_loss: 0.8634 - val_mae: 0.7735 - val_rmse: 0.7903 - val_smape: 1.9618

Epoch 2/64

4584/4584 - 43s - 9ms/step - ia: 0.2323 - loss: 1.0629 - mae: 0.8556 - rmse: 1.0098 - smape: 1.6134 - val_ia: 0.1372 - val_loss: 0.8602 - val_mae: 0.7721 - val_rmse: 0.7889 - val_smape: 1.9698

Epoch 3/64

4584/4584 - 37s - 8ms/step - ia: 0.2333 - loss: 1.0573 - mae: 0.8525 - rmse: 1.0076 - smape: 1.6088 - val_ia: 0.1375 - val_loss: 0.8575 - val_mae: 0.7709 - val_rmse: 0.7878 - val_smape: 1.9656

Epoch 4/64

4584/4584 - 38s - 8ms/step - ia: 0.2329 - loss: 1.0546 - mae: 0.8524 - rmse: 1.0068 - smape: 1.6128 - val_ia: 0.1377 - val_loss: 0.8550 - val_mae: 0.7698 - val_rmse: 0.7868 - val_smape: 1.9527

Epoch 5/64

4584/4584 - 32s - 7ms/step - ia: 0.2369 - loss: 1.0446 - mae: 0.8476 - rmse: 1.0016 - smape: 1.6083 - val_ia: 0.1381 - val_loss: 0.8519 - val_mae: 0.7684 - val_rmse: 0.7854 - val_smape: 1.9319

Epoch 6/64

4584/4584 - 43s - 9ms/step - ia: 0.2362 - loss: 1.0410 - mae: 0.8470 - rmse: 0.9994 - smape: 1.6140 - val_ia: 0.1385 - val_loss: 0.8486 - val_mae: 0.7669 - val_rmse: 0.7840 - val_smape: 1.9098

Epoch 7/64

4584/4584 - 30s - 7ms/step - ia: 0.2351 - loss: 1.0340 - mae: 0.8455 - rmse: 0.9959 - smape: 1.6162 - val_ia: 0.1388 - val_loss: 0.8451 - val_mae: 0.7652 - val_rmse: 0.7824 - val_smape: 1.8878

Epoch 8/64

4584/4584 - 44s - 10ms/step - ia: 0.2382 - loss: 1.0285 - mae: 0.8433 - rmse: 0.9936 - smape: 1.6109 - val_ia: 0.1392 - val_loss: 0.8425 - val_mae: 0.7641 - val_rmse: 0.7814 - val_smape: 1.8709

Epoch 9/64

4584/4584 - 30s - 6ms/step - ia: 0.2359 - loss: 1.0262 - mae: 0.8415 - rmse: 0.9931 - smape: 1.6105 - val_ia: 0.1396 - val_loss: 0.8389 - val_mae: 0.7624 - val_rmse: 0.7798 - val_smape: 1.8502

Epoch 10/64

4584/4584 - 33s - 7ms/step - ia: 0.2373 - loss: 1.0201 - mae: 0.8390 - rmse: 0.9900 - smape: 1.6057 - val_ia: 0.1401 - val_loss: 0.8359 - val_mae: 0.7611 - val_rmse: 0.7786 - val_smape: 1.8317

Epoch 11/64

4584/4584 - 30s - 6ms/step - ia: 0.2384 - loss: 1.0138 - mae: 0.8379 - rmse: 0.9869 - smape: 1.6069 - val_ia: 0.1406 - val_loss: 0.8326 - val_mae: 0.7596 - val_rmse: 0.7772 - val_smape: 1.8120

Epoch 12/64

4584/4584 - 33s - 7ms/step - ia: 0.2393 - loss: 1.0064 - mae: 0.8345 - rmse: 0.9832 - smape: 1.6028 - val_ia: 0.1414 - val_loss: 0.8287 - val_mae: 0.7577 - val_rmse: 0.7754 - val_smape: 1.7911

Epoch 13/64

4584/4584 - 38s - 8ms/step - ia: 0.2407 - loss: 1.0039 - mae: 0.8344 - rmse: 0.9828 - smape: 1.6030 - val_ia: 0.1420 - val_loss: 0.8249 - val_mae: 0.7560 - val_rmse: 0.7738 - val_smape: 1.7704

Epoch 14/64

4584/4584 - 41s - 9ms/step - ia: 0.2441 - loss: 0.9954 - mae: 0.8305 - rmse: 0.9779 - smape: 1.5938 - val_ia: 0.1422 - val_loss: 0.8210 - val_mae: 0.7542 - val_rmse: 0.7721 - val_smape: 1.7495

Epoch 15/64

4584/4584 - 40s - 9ms/step - ia: 0.2471 - loss: 0.9860 - mae: 0.8281 - rmse: 0.9729 - smape: 1.5923 - val_ia: 0.1426 - val_loss: 0.8173 - val_mae: 0.7524 - val_rmse: 0.7705 - val_smape: 1.7286

Epoch 16/64

4584/4584 - 33s - 7ms/step - ia: 0.2475 - loss: 0.9784 - mae: 0.8252 - rmse: 0.9697 - smape: 1.5866 - val_ia: 0.1430 - val_loss: 0.8129 - val_mae: 0.7504 - val_rmse: 0.7685 - val_smape: 1.7073

Epoch 17/64

4584/4584 - 42s - 9ms/step - ia: 0.2503 - loss: 0.9732 - mae: 0.8227 - rmse: 0.9675 - smape: 1.5798 - val_ia: 0.1434 - val_loss: 0.8087 - val_mae: 0.7484 - val_rmse: 0.7667 - val_smape: 1.6859

Epoch 18/64

4584/4584 - 33s - 7ms/step - ia: 0.2535 - loss: 0.9692 - mae: 0.8218 - rmse: 0.9657 - smape: 1.5767 - val_ia: 0.1440 - val_loss: 0.8041 - val_mae: 0.7461 - val_rmse: 0.7645 - val_smape: 1.6647

Epoch 19/64

4584/4584 - 40s - 9ms/step - ia: 0.2556 - loss: 0.9665 - mae: 0.8200 - rmse: 0.9635 - smape: 1.5725 - val_ia: 0.1446 - val_loss: 0.8000 - val_mae: 0.7441 - val_rmse: 0.7627 - val_smape: 1.6438

Epoch 20/64

4584/4584 - 30s - 6ms/step - ia: 0.2590 - loss: 0.9526 - mae: 0.8150 - rmse: 0.9572 - smape: 1.5578 - val_ia: 0.1454 - val_loss: 0.7952 - val_mae: 0.7417 - val_rmse: 0.7605 - val_smape: 1.6230

Epoch 21/64

4584/4584 - 33s - 7ms/step - ia: 0.2624 - loss: 0.9490 - mae: 0.8144 - rmse: 0.9555 - smape: 1.5535 - val_ia: 0.1457 - val_loss: 0.7911 - val_mae: 0.7397 - val_rmse: 0.7585 - val_smape: 1.6025

Epoch 22/64

4584/4584 - 37s - 8ms/step - ia: 0.2676 - loss: 0.9374 - mae: 0.8101 - rmse: 0.9501 - smape: 1.5422 - val_ia: 0.1462 - val_loss: 0.7869 - val_mae: 0.7376 - val_rmse: 0.7565 - val_smape: 1.5824

Epoch 23/64

4584/4584 - 31s - 7ms/step - ia: 0.2710 - loss: 0.9300 - mae: 0.8063 - rmse: 0.9461 - smape: 1.5316 - val_ia: 0.1468 - val_loss: 0.7830 - val_mae: 0.7356 - val_rmse: 0.7546 - val_smape: 1.5624

Epoch 24/64

4584/4584 - 38s - 8ms/step - ia: 0.2741 - loss: 0.9214 - mae: 0.8038 - rmse: 0.9408 - smape: 1.5265 - val_ia: 0.1469 - val_loss: 0.7784 - val_mae: 0.7332 - val_rmse: 0.7524 - val_smape: 1.5432

Epoch 25/64

4584/4584 - 37s - 8ms/step - ia: 0.2776 - loss: 0.9168 - mae: 0.8021 - rmse: 0.9396 - smape: 1.5178 - val_ia: 0.1475 - val_loss: 0.7744 - val_mae: 0.7311 - val_rmse: 0.7504 - val_smape: 1.5246

Epoch 26/64

4584/4584 - 29s - 6ms/step - ia: 0.2840 - loss: 0.9101 - mae: 0.7991 - rmse: 0.9362 - smape: 1.5074 - val_ia: 0.1478 - val_loss: 0.7704 - val_mae: 0.7290 - val_rmse: 0.7483 - val_smape: 1.5069

Epoch 27/64

4584/4584 - 33s - 7ms/step - ia: 0.2855 - loss: 0.9058 - mae: 0.7981 - rmse: 0.9342 - smape: 1.5000 - val_ia: 0.1479 - val_loss: 0.7671 - val_mae: 0.7271 - val_rmse: 0.7465 - val_smape: 1.4897

Epoch 28/64

4584/4584 - 33s - 7ms/step - ia: 0.2878 - loss: 0.9029 - mae: 0.7973 - rmse: 0.9322 - smape: 1.4922 - val_ia: 0.1477 - val_loss: 0.7632 - val_mae: 0.7250 - val_rmse: 0.7444 - val_smape: 1.4737

Epoch 29/64

4584/4584 - 40s - 9ms/step - ia: 0.2967 - loss: 0.8923 - mae: 0.7914 - rmse: 0.9263 - smape: 1.4760 - val_ia: 0.1477 - val_loss: 0.7603 - val_mae: 0.7232 - val_rmse: 0.7427 - val_smape: 1.4578

Epoch 30/64

4584/4584 - 39s - 9ms/step - ia: 0.2997 - loss: 0.8838 - mae: 0.7884 - rmse: 0.9228 - smape: 1.4672 - val_ia: 0.1476 - val_loss: 0.7572 - val_mae: 0.7214 - val_rmse: 0.7409 - val_smape: 1.4427

Epoch 31/64

4584/4584 - 34s - 7ms/step - ia: 0.3043 - loss: 0.8760 - mae: 0.7868 - rmse: 0.9183 - smape: 1.4631 - val_ia: 0.1474 - val_loss: 0.7550 - val_mae: 0.7200 - val_rmse: 0.7394 - val_smape: 1.4286

Epoch 32/64

4584/4584 - 32s - 7ms/step - ia: 0.3077 - loss: 0.8711 - mae: 0.7843 - rmse: 0.9160 - smape: 1.4514 - val_ia: 0.1470 - val_loss: 0.7520 - val_mae: 0.7182 - val_rmse: 0.7376 - val_smape: 1.4155

Epoch 33/64

4584/4584 - 34s - 7ms/step - ia: 0.3135 - loss: 0.8643 - mae: 0.7806 - rmse: 0.9118 - smape: 1.4398 - val_ia: 0.1466 - val_loss: 0.7499 - val_mae: 0.7168 - val_rmse: 0.7361 - val_smape: 1.4029

Epoch 34/64

4584/4584 - 27s - 6ms/step - ia: 0.3184 - loss: 0.8549 - mae: 0.7767 - rmse: 0.9071 - smape: 1.4339 - val_ia: 0.1460 - val_loss: 0.7477 - val_mae: 0.7153 - val_rmse: 0.7346 - val_smape: 1.3907

Epoch 35/64

4584/4584 - 35s - 8ms/step - ia: 0.3231 - loss: 0.8510 - mae: 0.7741 - rmse: 0.9046 - smape: 1.4210 - val_ia: 0.1451 - val_loss: 0.7465 - val_mae: 0.7143 - val_rmse: 0.7334 - val_smape: 1.3796

Epoch 36/64

4584/4584 - 32s - 7ms/step - ia: 0.3275 - loss: 0.8413 - mae: 0.7699 - rmse: 0.8996 - smape: 1.4109 - val_ia: 0.1444 - val_loss: 0.7449 - val_mae: 0.7131 - val_rmse: 0.7321 - val_smape: 1.3688

Epoch 37/64

4584/4584 - 31s - 7ms/step - ia: 0.3324 - loss: 0.8398 - mae: 0.7691 - rmse: 0.8994 - smape: 1.4067 - val_ia: 0.1439 - val_loss: 0.7440 - val_mae: 0.7123 - val_rmse: 0.7311 - val_smape: 1.3593

Epoch 38/64

4584/4584 - 30s - 7ms/step - ia: 0.3377 - loss: 0.8298 - mae: 0.7643 - rmse: 0.8937 - smape: 1.3943 - val_ia: 0.1437 - val_loss: 0.7428 - val_mae: 0.7113 - val_rmse: 0.7300 - val_smape: 1.3501

Epoch 39/64

4584/4584 - 32s - 7ms/step - ia: 0.3422 - loss: 0.8212 - mae: 0.7608 - rmse: 0.8886 - smape: 1.3867 - val_ia: 0.1433 - val_loss: 0.7424 - val_mae: 0.7106 - val_rmse: 0.7293 - val_smape: 1.3414

Epoch 40/64

4584/4584 - 41s - 9ms/step - ia: 0.3484 - loss: 0.8151 - mae: 0.7574 - rmse: 0.8850 - smape: 1.3767 - val_ia: 0.1430 - val_loss: 0.7421 - val_mae: 0.7100 - val_rmse: 0.7286 - val_smape: 1.3337

Epoch 41/64

4584/4584 - 31s - 7ms/step - ia: 0.3521 - loss: 0.8075 - mae: 0.7536 - rmse: 0.8815 - smape: 1.3659 - val_ia: 0.1427 - val_loss: 0.7416 - val_mae: 0.7094 - val_rmse: 0.7278 - val_smape: 1.3268

Epoch 42/64

4584/4584 - 31s - 7ms/step - ia: 0.3552 - loss: 0.8069 - mae: 0.7530 - rmse: 0.8815 - smape: 1.3609 - val_ia: 0.1425 - val_loss: 0.7431 - val_mae: 0.7096 - val_rmse: 0.7279 - val_smape: 1.3209

Epoch 43/64

4584/4584 - 40s - 9ms/step - ia: 0.3607 - loss: 0.7967 - mae: 0.7491 - rmse: 0.8754 - smape: 1.3541 - val_ia: 0.1426 - val_loss: 0.7439 - val_mae: 0.7095 - val_rmse: 0.7276 - val_smape: 1.3151

Epoch 44/64

4584/4584 - 31s - 7ms/step - ia: 0.3641 - loss: 0.7927 - mae: 0.7461 - rmse: 0.8733 - smape: 1.3476 - val_ia: 0.1426 - val_loss: 0.7448 - val_mae: 0.7094 - val_rmse: 0.7274 - val_smape: 1.3097

Epoch 45/64

4584/4584 - 28s - 6ms/step - ia: 0.3707 - loss: 0.7812 - mae: 0.7405 - rmse: 0.8666 - smape: 1.3361 - val_ia: 0.1422 - val_loss: 0.7462 - val_mae: 0.7095 - val_rmse: 0.7275 - val_smape: 1.3049

Epoch 46/64

4584/4584 - 31s - 7ms/step - ia: 0.3753 - loss: 0.7742 - mae: 0.7362 - rmse: 0.8626 - smape: 1.3266 - val_ia: 0.1412 - val_loss: 0.7476 - val_mae: 0.7097 - val_rmse: 0.7275 - val_smape: 1.3002

Epoch 47/64

4584/4584 - 34s - 7ms/step - ia: 0.3801 - loss: 0.7682 - mae: 0.7331 - rmse: 0.8592 - smape: 1.3186 - val_ia: 0.1405 - val_loss: 0.7496 - val_mae: 0.7101 - val_rmse: 0.7278 - val_smape: 1.2959

Epoch 48/64

4584/4584 - 30s - 7ms/step - ia: 0.3844 - loss: 0.7625 - mae: 0.7293 - rmse: 0.8557 - smape: 1.3113 - val_ia: 0.1400 - val_loss: 0.7521 - val_mae: 0.7107 - val_rmse: 0.7283 - val_smape: 1.2924

Epoch 49/64

4584/4584 - 41s - 9ms/step - ia: 0.3885 - loss: 0.7555 - mae: 0.7267 - rmse: 0.8521 - smape: 1.3044 - val_ia: 0.1400 - val_loss: 0.7572 - val_mae: 0.7124 - val_rmse: 0.7299 - val_smape: 1.2894

Epoch 50/64

4584/4584 - 43s - 9ms/step - ia: 0.3966 - loss: 0.7488 - mae: 0.7227 - rmse: 0.8479 - smape: 1.2927 - val_ia: 0.1403 - val_loss: 0.7617 - val_mae: 0.7139 - val_rmse: 0.7314 - val_smape: 1.2864

Epoch 51/64

4584/4584 - 28s - 6ms/step - ia: 0.3987 - loss: 0.7414 - mae: 0.7191 - rmse: 0.8437 - smape: 1.2888 - val_ia: 0.1409 - val_loss: 0.7670 - val_mae: 0.7157 - val_rmse: 0.7331 - val_smape: 1.2829

Epoch 52/64

4584/4584 - 30s - 7ms/step - ia: 0.4047 - loss: 0.7332 - mae: 0.7138 - rmse: 0.8389 - smape: 1.2749 - val_ia: 0.1421 - val_loss: 0.7737 - val_mae: 0.7181 - val_rmse: 0.7355 - val_smape: 1.2799

Epoch 53/64

4584/4584 - 27s - 6ms/step - ia: 0.4094 - loss: 0.7277 - mae: 0.7101 - rmse: 0.8350 - smape: 1.2651 - val_ia: 0.1432 - val_loss: 0.7778 - val_mae: 0.7194 - val_rmse: 0.7367 - val_smape: 1.2762

Epoch 54/64

4584/4584 - 31s - 7ms/step - ia: 0.4134 - loss: 0.7203 - mae: 0.7059 - rmse: 0.8310 - smape: 1.2568 - val_ia: 0.1444 - val_loss: 0.7830 - val_mae: 0.7211 - val_rmse: 0.7385 - val_smape: 1.2732

Epoch 55/64

4584/4584 - 33s - 7ms/step - ia: 0.4175 - loss: 0.7146 - mae: 0.7029 - rmse: 0.8270 - smape: 1.2507 - val_ia: 0.1454 - val_loss: 0.7921 - val_mae: 0.7247 - val_rmse: 0.7421 - val_smape: 1.2712

Epoch 56/64

4584/4584 - 40s - 9ms/step - ia: 0.4240 - loss: 0.7065 - mae: 0.6979 - rmse: 0.8228 - smape: 1.2411 - val_ia: 0.1464 - val_loss: 0.7983 - val_mae: 0.7271 - val_rmse: 0.7444 - val_smape: 1.2684

Epoch 56: early stopping

Restoring model weights from the end of the best epoch: 41.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:56 721ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 10%|█         | 5/50 [58:33<11:24:18, 912.41s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 21s - 18ms/step - ia: 0.2502 - loss: 0.8767 - mae: 0.7788 - rmse: 0.9308 - smape: 1.5386 - val_ia: 0.2540 - val_loss: 0.7526 - val_mae: 0.7125 - val_rmse: 0.7829 - val_smape: 1.3984

Epoch 2/128

1146/1146 - 20s - 17ms/step - ia: 0.4279 - loss: 0.6533 - mae: 0.6690 - rmse: 0.8031 - smape: 1.2532 - val_ia: 0.2731 - val_loss: 0.8049 - val_mae: 0.7292 - val_rmse: 0.7953 - val_smape: 1.2975

Epoch 3/128

1146/1146 - 20s - 18ms/step - ia: 0.5344 - loss: 0.5432 - mae: 0.6013 - rmse: 0.7324 - smape: 1.0892 - val_ia: 0.2766 - val_loss: 0.9966 - val_mae: 0.8137 - val_rmse: 0.8822 - val_smape: 1.2928

Epoch 4/128

1146/1146 - 21s - 18ms/step - ia: 0.5842 - loss: 0.4919 - mae: 0.5644 - rmse: 0.6966 - smape: 1.0072 - val_ia: 0.2702 - val_loss: 1.1373 - val_mae: 0.8806 - val_rmse: 0.9491 - val_smape: 1.3121

Epoch 5/128

1146/1146 - 21s - 18ms/step - ia: 0.6079 - loss: 0.4623 - mae: 0.5446 - rmse: 0.6753 - smape: 0.9642 - val_ia: 0.2661 - val_loss: 1.2043 - val_mae: 0.9131 - val_rmse: 0.9810 - val_smape: 1.3151

Epoch 6/128

1146/1146 - 13s - 11ms/step - ia: 0.6239 - loss: 0.4403 - mae: 0.5321 - rmse: 0.6588 - smape: 0.9352 - val_ia: 0.2646 - val_loss: 1.2090 - val_mae: 0.9207 - val_rmse: 0.9868 - val_smape: 1.3164

Epoch 7/128

1146/1146 - 12s - 10ms/step - ia: 0.6349 - loss: 0.4207 - mae: 0.5194 - rmse: 0.6438 - smape: 0.9113 - val_ia: 0.2653 - val_loss: 1.1996 - val_mae: 0.9179 - val_rmse: 0.9841 - val_smape: 1.3044

Epoch 8/128

1146/1146 - 11s - 10ms/step - ia: 0.6438 - loss: 0.4079 - mae: 0.5117 - rmse: 0.6340 - smape: 0.8953 - val_ia: 0.2686 - val_loss: 1.1696 - val_mae: 0.9047 - val_rmse: 0.9715 - val_smape: 1.2853

Epoch 9/128

1146/1146 - 22s - 19ms/step - ia: 0.6529 - loss: 0.3944 - mae: 0.5030 - rmse: 0.6238 - smape: 0.8806 - val_ia: 0.2724 - val_loss: 1.1102 - val_mae: 0.8799 - val_rmse: 0.9464 - val_smape: 1.2667

Epoch 10/128

1146/1146 - 12s - 10ms/step - ia: 0.6590 - loss: 0.3806 - mae: 0.4948 - rmse: 0.6124 - smape: 0.8692 - val_ia: 0.2768 - val_loss: 1.0600 - val_mae: 0.8571 - val_rmse: 0.9241 - val_smape: 1.2460

Epoch 11/128

1146/1146 - 21s - 18ms/step - ia: 0.6673 - loss: 0.3695 - mae: 0.4864 - rmse: 0.6034 - smape: 0.8554 - val_ia: 0.2818 - val_loss: 0.9945 - val_mae: 0.8286 - val_rmse: 0.8950 - val_smape: 1.2287

Epoch 12/128

1146/1146 - 21s - 18ms/step - ia: 0.6710 - loss: 0.3604 - mae: 0.4813 - rmse: 0.5957 - smape: 0.8501 - val_ia: 0.2865 - val_loss: 0.9498 - val_mae: 0.8077 - val_rmse: 0.8744 - val_smape: 1.2127

Epoch 13/128

1146/1146 - 19s - 17ms/step - ia: 0.6763 - loss: 0.3519 - mae: 0.4753 - rmse: 0.5891 - smape: 0.8391 - val_ia: 0.2914 - val_loss: 0.9001 - val_mae: 0.7846 - val_rmse: 0.8513 - val_smape: 1.1969

Epoch 14/128

1146/1146 - 12s - 11ms/step - ia: 0.6807 - loss: 0.3473 - mae: 0.4720 - rmse: 0.5851 - smape: 0.8343 - val_ia: 0.2956 - val_loss: 0.8562 - val_mae: 0.7634 - val_rmse: 0.8303 - val_smape: 1.1816

Epoch 15/128

1146/1146 - 20s - 17ms/step - ia: 0.6848 - loss: 0.3394 - mae: 0.4665 - rmse: 0.5783 - smape: 0.8281 - val_ia: 0.2986 - val_loss: 0.8325 - val_mae: 0.7510 - val_rmse: 0.8185 - val_smape: 1.1712

Epoch 16/128

1146/1146 - 12s - 10ms/step - ia: 0.6878 - loss: 0.3349 - mae: 0.4636 - rmse: 0.5744 - smape: 0.8226 - val_ia: 0.3022 - val_loss: 0.7880 - val_mae: 0.7308 - val_rmse: 0.7973 - val_smape: 1.1614

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:22 511ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 12%|█▏        | 6/50 [1:03:11<8:30:50, 696.61s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 5s - 35ms/step - ia: 0.7413 - loss: 0.2527 - mae: 0.3865 - rmse: 0.4896 - smape: 0.7660 - val_ia: 0.6846 - val_loss: 0.3557 - val_mae: 0.4619 - val_rmse: 0.5716 - val_smape: 0.8564

Epoch 2/128

144/144 - 2s - 17ms/step - ia: 0.8226 - loss: 0.1343 - mae: 0.2780 - rmse: 0.3660 - smape: 0.6131 - val_ia: 0.7608 - val_loss: 0.2007 - val_mae: 0.3364 - val_rmse: 0.4170 - val_smape: 0.7078

Epoch 3/128

144/144 - 2s - 16ms/step - ia: 0.8352 - loss: 0.1171 - mae: 0.2603 - rmse: 0.3413 - smape: 0.5782 - val_ia: 0.7856 - val_loss: 0.1558 - val_mae: 0.3039 - val_rmse: 0.3705 - val_smape: 0.6731

Epoch 4/128

144/144 - 2s - 16ms/step - ia: 0.8391 - loss: 0.1133 - mae: 0.2544 - rmse: 0.3355 - smape: 0.5624 - val_ia: 0.7762 - val_loss: 0.1844 - val_mae: 0.3236 - val_rmse: 0.4048 - val_smape: 0.6862

Epoch 5/128

144/144 - 3s - 21ms/step - ia: 0.8488 - loss: 0.1002 - mae: 0.2407 - rmse: 0.3160 - smape: 0.5371 - val_ia: 0.7946 - val_loss: 0.1381 - val_mae: 0.2907 - val_rmse: 0.3560 - val_smape: 0.6484

Epoch 6/128

144/144 - 2s - 16ms/step - ia: 0.8513 - loss: 0.0969 - mae: 0.2368 - rmse: 0.3105 - smape: 0.5268 - val_ia: 0.8055 - val_loss: 0.1332 - val_mae: 0.2799 - val_rmse: 0.3458 - val_smape: 0.6473

Epoch 7/128

144/144 - 2s - 13ms/step - ia: 0.8537 - loss: 0.0942 - mae: 0.2333 - rmse: 0.3064 - smape: 0.5192 - val_ia: 0.7911 - val_loss: 0.1471 - val_mae: 0.2957 - val_rmse: 0.3535 - val_smape: 0.6606

Epoch 8/128

144/144 - 2s - 13ms/step - ia: 0.8540 - loss: 0.0948 - mae: 0.2331 - rmse: 0.3071 - smape: 0.5212 - val_ia: 0.7827 - val_loss: 0.1610 - val_mae: 0.3069 - val_rmse: 0.3874 - val_smape: 0.6704

Epoch 9/128

144/144 - 2s - 13ms/step - ia: 0.8577 - loss: 0.0898 - mae: 0.2272 - rmse: 0.2992 - smape: 0.5089 - val_ia: 0.7763 - val_loss: 0.1855 - val_mae: 0.3165 - val_rmse: 0.4014 - val_smape: 0.7086

Epoch 10/128

144/144 - 2s - 12ms/step - ia: 0.8607 - loss: 0.0867 - mae: 0.2227 - rmse: 0.2937 - smape: 0.5001 - val_ia: 0.7830 - val_loss: 0.1774 - val_mae: 0.3079 - val_rmse: 0.3873 - val_smape: 0.6747

Epoch 11/128

144/144 - 2s - 12ms/step - ia: 0.8608 - loss: 0.0863 - mae: 0.2230 - rmse: 0.2930 - smape: 0.5019 - val_ia: 0.7624 - val_loss: 0.1883 - val_mae: 0.3324 - val_rmse: 0.4127 - val_smape: 0.7165

Epoch 12/128

144/144 - 2s - 14ms/step - ia: 0.8644 - loss: 0.0818 - mae: 0.2174 - rmse: 0.2853 - smape: 0.4884 - val_ia: 0.7691 - val_loss: 0.1827 - val_mae: 0.3199 - val_rmse: 0.3998 - val_smape: 0.7096

Epoch 13/128

144/144 - 2s - 16ms/step - ia: 0.8645 - loss: 0.0828 - mae: 0.2173 - rmse: 0.2870 - smape: 0.4912 - val_ia: 0.7556 - val_loss: 0.2057 - val_mae: 0.3397 - val_rmse: 0.4267 - val_smape: 0.7436

Epoch 14/128

144/144 - 2s - 17ms/step - ia: 0.8662 - loss: 0.0808 - mae: 0.2144 - rmse: 0.2837 - smape: 0.4841 - val_ia: 0.7523 - val_loss: 0.2252 - val_mae: 0.3476 - val_rmse: 0.4333 - val_smape: 0.7475

Epoch 15/128

144/144 - 3s - 19ms/step - ia: 0.8674 - loss: 0.0795 - mae: 0.2127 - rmse: 0.2811 - smape: 0.4821 - val_ia: 0.7531 - val_loss: 0.2305 - val_mae: 0.3482 - val_rmse: 0.4405 - val_smape: 0.7407

Epoch 16/128

144/144 - 2s - 17ms/step - ia: 0.8685 - loss: 0.0785 - mae: 0.2114 - rmse: 0.2794 - smape: 0.4778 - val_ia: 0.7770 - val_loss: 0.1737 - val_mae: 0.3154 - val_rmse: 0.3843 - val_smape: 0.7123

Epoch 17/128

144/144 - 2s - 13ms/step - ia: 0.8693 - loss: 0.0778 - mae: 0.2098 - rmse: 0.2787 - smape: 0.4728 - val_ia: 0.7785 - val_loss: 0.1730 - val_mae: 0.3088 - val_rmse: 0.3814 - val_smape: 0.6889

Epoch 18/128

144/144 - 2s - 13ms/step - ia: 0.8693 - loss: 0.0769 - mae: 0.2095 - rmse: 0.2768 - smape: 0.4760 - val_ia: 0.7542 - val_loss: 0.2044 - val_mae: 0.3385 - val_rmse: 0.4239 - val_smape: 0.7471

Epoch 19/128

144/144 - 2s - 14ms/step - ia: 0.8683 - loss: 0.0786 - mae: 0.2113 - rmse: 0.2795 - smape: 0.4776 - val_ia: 0.7839 - val_loss: 0.1551 - val_mae: 0.2954 - val_rmse: 0.3652 - val_smape: 0.6719

Epoch 20/128

144/144 - 2s - 12ms/step - ia: 0.8702 - loss: 0.0761 - mae: 0.2084 - rmse: 0.2750 - smape: 0.4726 - val_ia: 0.7689 - val_loss: 0.1986 - val_mae: 0.3306 - val_rmse: 0.4022 - val_smape: 0.7137

Epoch 21/128

144/144 - 2s - 15ms/step - ia: 0.8714 - loss: 0.0749 - mae: 0.2066 - rmse: 0.2729 - smape: 0.4705 - val_ia: 0.7541 - val_loss: 0.2105 - val_mae: 0.3391 - val_rmse: 0.4207 - val_smape: 0.7287

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:27 539ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 14%|█▍        | 7/50 [1:04:13<5:50:29, 489.06s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2292/2292 - 47s - 21ms/step - ia: 0.7907 - loss: 0.1709 - mae: 0.3090 - rmse: 0.3946 - smape: 0.6774 - val_ia: 0.3788 - val_loss: 0.1413 - val_mae: 0.2991 - val_rmse: 0.3206 - val_smape: 0.6920

Epoch 2/8

2292/2292 - 43s - 19ms/step - ia: 0.8421 - loss: 0.1021 - mae: 0.2383 - rmse: 0.3099 - smape: 0.5584 - val_ia: 0.3511 - val_loss: 0.2177 - val_mae: 0.3575 - val_rmse: 0.3976 - val_smape: 0.7344

Epoch 3/8

2292/2292 - 29s - 12ms/step - ia: 0.8542 - loss: 0.0888 - mae: 0.2216 - rmse: 0.2887 - smape: 0.5279 - val_ia: 0.3585 - val_loss: 0.1953 - val_mae: 0.3526 - val_rmse: 0.3842 - val_smape: 0.7328

Epoch 4/8

2292/2292 - 28s - 12ms/step - ia: 0.8628 - loss: 0.0790 - mae: 0.2089 - rmse: 0.2725 - smape: 0.5011 - val_ia: 0.3516 - val_loss: 0.1859 - val_mae: 0.3364 - val_rmse: 0.3770 - val_smape: 0.7276

Epoch 5/8

2292/2292 - 42s - 18ms/step - ia: 0.8680 - loss: 0.0731 - mae: 0.2014 - rmse: 0.2621 - smape: 0.4862 - val_ia: 0.3510 - val_loss: 0.1950 - val_mae: 0.3441 - val_rmse: 0.3770 - val_smape: 0.7298

Epoch 6/8

2292/2292 - 29s - 13ms/step - ia: 0.8723 - loss: 0.0689 - mae: 0.1952 - rmse: 0.2542 - smape: 0.4730 - val_ia: 0.3802 - val_loss: 0.1582 - val_mae: 0.3123 - val_rmse: 0.3427 - val_smape: 0.6716

Epoch 7/8

2292/2292 - 28s - 12ms/step - ia: 0.8759 - loss: 0.0652 - mae: 0.1900 - rmse: 0.2470 - smape: 0.4639 - val_ia: 0.3498 - val_loss: 0.2017 - val_mae: 0.3495 - val_rmse: 0.3844 - val_smape: 0.7385

Epoch 8/8

2292/2292 - 28s - 12ms/step - ia: 0.8776 - loss: 0.0631 - mae: 0.1870 - rmse: 0.2435 - smape: 0.4558 - val_ia: 0.3676 - val_loss: 0.1888 - val_mae: 0.3345 - val_rmse: 0.3696 - val_smape: 0.7050

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:27 537ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

 16%|█▌        | 8/50 [1:09:07<4:58:57, 427.09s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 7s - 51ms/step - ia: 0.4352 - loss: 0.7621 - mae: 0.7055 - rmse: 0.8638 - smape: 1.2517 - val_ia: 0.4087 - val_loss: 1.5189 - val_mae: 0.9873 - val_rmse: 1.1778 - val_smape: 1.3355

Epoch 2/128

144/144 - 1s - 10ms/step - ia: 0.6218 - loss: 0.4550 - mae: 0.5431 - rmse: 0.6734 - smape: 0.9687 - val_ia: 0.4388 - val_loss: 1.7523 - val_mae: 1.0179 - val_rmse: 1.2478 - val_smape: 1.2652

Epoch 3/128

144/144 - 1s - 10ms/step - ia: 0.6683 - loss: 0.3751 - mae: 0.4920 - rmse: 0.6117 - smape: 0.8931 - val_ia: 0.4811 - val_loss: 1.7081 - val_mae: 0.9582 - val_rmse: 1.1745 - val_smape: 1.2201

Epoch 4/128

144/144 - 1s - 10ms/step - ia: 0.6963 - loss: 0.3276 - mae: 0.4571 - rmse: 0.5715 - smape: 0.8494 - val_ia: 0.5039 - val_loss: 1.6626 - val_mae: 0.9102 - val_rmse: 1.1372 - val_smape: 1.1701

Epoch 5/128

144/144 - 1s - 10ms/step - ia: 0.7125 - loss: 0.2994 - mae: 0.4352 - rmse: 0.5466 - smape: 0.8275 - val_ia: 0.5490 - val_loss: 1.3577 - val_mae: 0.8006 - val_rmse: 1.0185 - val_smape: 1.0728

Epoch 6/128

144/144 - 1s - 9ms/step - ia: 0.7242 - loss: 0.2803 - mae: 0.4176 - rmse: 0.5289 - smape: 0.8089 - val_ia: 0.6113 - val_loss: 0.6764 - val_mae: 0.6043 - val_rmse: 0.7647 - val_smape: 0.9624

Epoch 7/128

144/144 - 1s - 6ms/step - ia: 0.7311 - loss: 0.2677 - mae: 0.4077 - rmse: 0.5173 - smape: 0.8020 - val_ia: 0.6351 - val_loss: 0.5532 - val_mae: 0.5514 - val_rmse: 0.7088 - val_smape: 0.9240

Epoch 8/128

144/144 - 1s - 10ms/step - ia: 0.7381 - loss: 0.2579 - mae: 0.3983 - rmse: 0.5071 - smape: 0.7883 - val_ia: 0.6454 - val_loss: 0.5137 - val_mae: 0.5314 - val_rmse: 0.6884 - val_smape: 0.9054

Epoch 9/128

144/144 - 1s - 9ms/step - ia: 0.7432 - loss: 0.2478 - mae: 0.3906 - rmse: 0.4970 - smape: 0.7797 - val_ia: 0.6672 - val_loss: 0.3888 - val_mae: 0.4832 - val_rmse: 0.5957 - val_smape: 0.8813

Epoch 10/128

144/144 - 1s - 9ms/step - ia: 0.7481 - loss: 0.2394 - mae: 0.3835 - rmse: 0.4889 - smape: 0.7721 - val_ia: 0.6697 - val_loss: 0.3534 - val_mae: 0.4735 - val_rmse: 0.5698 - val_smape: 0.8892

Epoch 11/128

144/144 - 1s - 8ms/step - ia: 0.7508 - loss: 0.2341 - mae: 0.3798 - rmse: 0.4836 - smape: 0.7639 - val_ia: 0.6901 - val_loss: 0.2997 - val_mae: 0.4421 - val_rmse: 0.5177 - val_smape: 0.8618

Epoch 12/128

144/144 - 1s - 8ms/step - ia: 0.7548 - loss: 0.2278 - mae: 0.3742 - rmse: 0.4769 - smape: 0.7581 - val_ia: 0.7003 - val_loss: 0.2737 - val_mae: 0.4176 - val_rmse: 0.4876 - val_smape: 0.8454

Epoch 13/128

144/144 - 2s - 11ms/step - ia: 0.7597 - loss: 0.2199 - mae: 0.3676 - rmse: 0.4683 - smape: 0.7478 - val_ia: 0.6919 - val_loss: 0.2905 - val_mae: 0.4353 - val_rmse: 0.5011 - val_smape: 0.8644

Epoch 14/128

144/144 - 1s - 8ms/step - ia: 0.7626 - loss: 0.2146 - mae: 0.3637 - rmse: 0.4625 - smape: 0.7418 - val_ia: 0.7077 - val_loss: 0.2706 - val_mae: 0.4206 - val_rmse: 0.4818 - val_smape: 0.8398

Epoch 15/128

144/144 - 1s - 8ms/step - ia: 0.7674 - loss: 0.2080 - mae: 0.3577 - rmse: 0.4555 - smape: 0.7321 - val_ia: 0.7134 - val_loss: 0.2616 - val_mae: 0.4041 - val_rmse: 0.4705 - val_smape: 0.8197

Epoch 16/128

144/144 - 1s - 10ms/step - ia: 0.7703 - loss: 0.2033 - mae: 0.3533 - rmse: 0.4499 - smape: 0.7256 - val_ia: 0.7208 - val_loss: 0.2370 - val_mae: 0.3835 - val_rmse: 0.4503 - val_smape: 0.8134

Epoch 17/128

144/144 - 1s - 10ms/step - ia: 0.7725 - loss: 0.1998 - mae: 0.3491 - rmse: 0.4464 - smape: 0.7218 - val_ia: 0.7255 - val_loss: 0.2430 - val_mae: 0.3865 - val_rmse: 0.4515 - val_smape: 0.7946

Epoch 18/128

144/144 - 1s - 6ms/step - ia: 0.7765 - loss: 0.1938 - mae: 0.3436 - rmse: 0.4393 - smape: 0.7155 - val_ia: 0.7330 - val_loss: 0.2212 - val_mae: 0.3732 - val_rmse: 0.4339 - val_smape: 0.7865

Epoch 19/128

144/144 - 2s - 11ms/step - ia: 0.7791 - loss: 0.1908 - mae: 0.3400 - rmse: 0.4360 - smape: 0.7093 - val_ia: 0.7491 - val_loss: 0.1936 - val_mae: 0.3474 - val_rmse: 0.4095 - val_smape: 0.7510

Epoch 20/128

144/144 - 1s - 7ms/step - ia: 0.7823 - loss: 0.1849 - mae: 0.3355 - rmse: 0.4293 - smape: 0.7034 - val_ia: 0.7567 - val_loss: 0.1821 - val_mae: 0.3359 - val_rmse: 0.3979 - val_smape: 0.7317

Epoch 21/128

144/144 - 1s - 10ms/step - ia: 0.7850 - loss: 0.1820 - mae: 0.3311 - rmse: 0.4259 - smape: 0.7006 - val_ia: 0.7580 - val_loss: 0.1846 - val_mae: 0.3379 - val_rmse: 0.3983 - val_smape: 0.7327

Epoch 22/128

144/144 - 1s - 10ms/step - ia: 0.7881 - loss: 0.1768 - mae: 0.3267 - rmse: 0.4197 - smape: 0.6973 - val_ia: 0.7519 - val_loss: 0.1924 - val_mae: 0.3490 - val_rmse: 0.4088 - val_smape: 0.7485

Epoch 23/128

144/144 - 1s - 9ms/step - ia: 0.7901 - loss: 0.1751 - mae: 0.3235 - rmse: 0.4180 - smape: 0.6900 - val_ia: 0.7467 - val_loss: 0.2001 - val_mae: 0.3577 - val_rmse: 0.4213 - val_smape: 0.7619

Epoch 24/128

144/144 - 1s - 7ms/step - ia: 0.7917 - loss: 0.1718 - mae: 0.3213 - rmse: 0.4138 - smape: 0.6897 - val_ia: 0.7590 - val_loss: 0.1727 - val_mae: 0.3358 - val_rmse: 0.3890 - val_smape: 0.7388

Epoch 25/128

144/144 - 1s - 7ms/step - ia: 0.7949 - loss: 0.1683 - mae: 0.3167 - rmse: 0.4097 - smape: 0.6836 - val_ia: 0.7611 - val_loss: 0.1674 - val_mae: 0.3296 - val_rmse: 0.3845 - val_smape: 0.7284

Epoch 26/128

144/144 - 1s - 10ms/step - ia: 0.7961 - loss: 0.1657 - mae: 0.3143 - rmse: 0.4068 - smape: 0.6818 - val_ia: 0.7576 - val_loss: 0.1761 - val_mae: 0.3373 - val_rmse: 0.3978 - val_smape: 0.7428

Epoch 27/128

144/144 - 1s - 9ms/step - ia: 0.7976 - loss: 0.1641 - mae: 0.3122 - rmse: 0.4045 - smape: 0.6793 - val_ia: 0.7504 - val_loss: 0.1849 - val_mae: 0.3481 - val_rmse: 0.4107 - val_smape: 0.7612

Epoch 28/128

144/144 - 1s - 7ms/step - ia: 0.8003 - loss: 0.1606 - mae: 0.3088 - rmse: 0.4001 - smape: 0.6737 - val_ia: 0.7626 - val_loss: 0.1620 - val_mae: 0.3272 - val_rmse: 0.3831 - val_smape: 0.7362

Epoch 29/128

144/144 - 1s - 10ms/step - ia: 0.7996 - loss: 0.1615 - mae: 0.3090 - rmse: 0.4017 - smape: 0.6727 - val_ia: 0.7660 - val_loss: 0.1622 - val_mae: 0.3251 - val_rmse: 0.3784 - val_smape: 0.7293

Epoch 30/128

144/144 - 1s - 10ms/step - ia: 0.8016 - loss: 0.1594 - mae: 0.3064 - rmse: 0.3989 - smape: 0.6723 - val_ia: 0.7552 - val_loss: 0.1742 - val_mae: 0.3378 - val_rmse: 0.4026 - val_smape: 0.7480

Epoch 31/128

144/144 - 1s - 9ms/step - ia: 0.8017 - loss: 0.1586 - mae: 0.3060 - rmse: 0.3978 - smape: 0.6708 - val_ia: 0.7736 - val_loss: 0.1496 - val_mae: 0.3131 - val_rmse: 0.3681 - val_smape: 0.7182

Epoch 32/128

144/144 - 1s - 9ms/step - ia: 0.8025 - loss: 0.1572 - mae: 0.3045 - rmse: 0.3963 - smape: 0.6681 - val_ia: 0.7627 - val_loss: 0.1800 - val_mae: 0.3378 - val_rmse: 0.4098 - val_smape: 0.7337

Epoch 33/128

144/144 - 1s - 8ms/step - ia: 0.8049 - loss: 0.1550 - mae: 0.3018 - rmse: 0.3932 - smape: 0.6611 - val_ia: 0.7583 - val_loss: 0.1710 - val_mae: 0.3330 - val_rmse: 0.3990 - val_smape: 0.7511

Epoch 34/128

144/144 - 1s - 8ms/step - ia: 0.8052 - loss: 0.1543 - mae: 0.3010 - rmse: 0.3920 - smape: 0.6600 - val_ia: 0.7668 - val_loss: 0.1738 - val_mae: 0.3296 - val_rmse: 0.3964 - val_smape: 0.7254

Epoch 35/128

144/144 - 1s - 6ms/step - ia: 0.8063 - loss: 0.1533 - mae: 0.2997 - rmse: 0.3907 - smape: 0.6596 - val_ia: 0.7619 - val_loss: 0.1743 - val_mae: 0.3327 - val_rmse: 0.4035 - val_smape: 0.7344

Epoch 36/128

144/144 - 1s - 10ms/step - ia: 0.8068 - loss: 0.1525 - mae: 0.2988 - rmse: 0.3902 - smape: 0.6567 - val_ia: 0.7665 - val_loss: 0.1661 - val_mae: 0.3224 - val_rmse: 0.3851 - val_smape: 0.7233

Epoch 37/128

144/144 - 1s - 8ms/step - ia: 0.8068 - loss: 0.1522 - mae: 0.2989 - rmse: 0.3893 - smape: 0.6567 - val_ia: 0.7607 - val_loss: 0.1903 - val_mae: 0.3418 - val_rmse: 0.4203 - val_smape: 0.7399

Epoch 38/128

144/144 - 1s - 9ms/step - ia: 0.8070 - loss: 0.1523 - mae: 0.2985 - rmse: 0.3893 - smape: 0.6569 - val_ia: 0.7767 - val_loss: 0.1564 - val_mae: 0.3131 - val_rmse: 0.3741 - val_smape: 0.7117

Epoch 39/128

144/144 - 1s - 7ms/step - ia: 0.8087 - loss: 0.1496 - mae: 0.2964 - rmse: 0.3859 - smape: 0.6513 - val_ia: 0.7767 - val_loss: 0.1599 - val_mae: 0.3141 - val_rmse: 0.3775 - val_smape: 0.7099

Epoch 40/128

144/144 - 1s - 10ms/step - ia: 0.8096 - loss: 0.1492 - mae: 0.2953 - rmse: 0.3855 - smape: 0.6490 - val_ia: 0.7767 - val_loss: 0.1550 - val_mae: 0.3107 - val_rmse: 0.3722 - val_smape: 0.7057

Epoch 41/128

144/144 - 1s - 10ms/step - ia: 0.8108 - loss: 0.1467 - mae: 0.2935 - rmse: 0.3823 - smape: 0.6455 - val_ia: 0.7685 - val_loss: 0.1688 - val_mae: 0.3246 - val_rmse: 0.3938 - val_smape: 0.7302

Epoch 42/128

144/144 - 1s - 8ms/step - ia: 0.8103 - loss: 0.1471 - mae: 0.2939 - rmse: 0.3828 - smape: 0.6454 - val_ia: 0.7735 - val_loss: 0.1693 - val_mae: 0.3201 - val_rmse: 0.3898 - val_smape: 0.7128

Epoch 43/128

144/144 - 1s - 10ms/step - ia: 0.8104 - loss: 0.1478 - mae: 0.2945 - rmse: 0.3836 - smape: 0.6428 - val_ia: 0.7691 - val_loss: 0.1720 - val_mae: 0.3253 - val_rmse: 0.3980 - val_smape: 0.7260

Epoch 44/128

144/144 - 1s - 10ms/step - ia: 0.8114 - loss: 0.1458 - mae: 0.2921 - rmse: 0.3816 - smape: 0.6404 - val_ia: 0.7753 - val_loss: 0.1648 - val_mae: 0.3177 - val_rmse: 0.3889 - val_smape: 0.7138

Epoch 45/128

144/144 - 1s - 8ms/step - ia: 0.8116 - loss: 0.1457 - mae: 0.2917 - rmse: 0.3816 - smape: 0.6390 - val_ia: 0.7725 - val_loss: 0.1788 - val_mae: 0.3261 - val_rmse: 0.3995 - val_smape: 0.7182

Epoch 46/128

144/144 - 1s - 8ms/step - ia: 0.8124 - loss: 0.1444 - mae: 0.2908 - rmse: 0.3797 - smape: 0.6405 - val_ia: 0.7754 - val_loss: 0.1757 - val_mae: 0.3227 - val_rmse: 0.3983 - val_smape: 0.7064

Epoch 46: early stopping

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:33 577ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 18%|█▊        | 9/50 [1:10:16<3:35:13, 314.96s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

1146/1146 - 34s - 29ms/step - ia: 0.6655 - loss: 0.3483 - mae: 0.4583 - rmse: 0.5704 - smape: 0.8730 - val_ia: 0.4333 - val_loss: 0.2868 - val_mae: 0.4258 - val_rmse: 0.4827 - val_smape: 0.8815

Epoch 2/16

1146/1146 - 38s - 33ms/step - ia: 0.7752 - loss: 0.1954 - mae: 0.3425 - rmse: 0.4375 - smape: 0.7005 - val_ia: 0.4202 - val_loss: 0.2989 - val_mae: 0.4416 - val_rmse: 0.4982 - val_smape: 0.9013

Epoch 3/16

1146/1146 - 20s - 18ms/step - ia: 0.8007 - loss: 0.1584 - mae: 0.3055 - rmse: 0.3935 - smape: 0.6568 - val_ia: 0.4588 - val_loss: 0.2472 - val_mae: 0.3920 - val_rmse: 0.4466 - val_smape: 0.8152

Epoch 4/16

1146/1146 - 19s - 17ms/step - ia: 0.8170 - loss: 0.1347 - mae: 0.2816 - rmse: 0.3625 - smape: 0.6265 - val_ia: 0.4738 - val_loss: 0.2226 - val_mae: 0.3717 - val_rmse: 0.4260 - val_smape: 0.7731

Epoch 5/16

1146/1146 - 20s - 17ms/step - ia: 0.8305 - loss: 0.1184 - mae: 0.2623 - rmse: 0.3401 - smape: 0.6056 - val_ia: 0.4737 - val_loss: 0.2281 - val_mae: 0.3735 - val_rmse: 0.4288 - val_smape: 0.7844

Epoch 6/16

1146/1146 - 20s - 18ms/step - ia: 0.8405 - loss: 0.1067 - mae: 0.2469 - rmse: 0.3222 - smape: 0.5879 - val_ia: 0.4973 - val_loss: 0.1846 - val_mae: 0.3412 - val_rmse: 0.3904 - val_smape: 0.7316

Epoch 7/16

1146/1146 - 24s - 21ms/step - ia: 0.8470 - loss: 0.0989 - mae: 0.2375 - rmse: 0.3100 - smape: 0.5742 - val_ia: 0.5148 - val_loss: 0.1636 - val_mae: 0.3189 - val_rmse: 0.3655 - val_smape: 0.7151

Epoch 8/16

1146/1146 - 25s - 22ms/step - ia: 0.8513 - loss: 0.0945 - mae: 0.2311 - rmse: 0.3030 - smape: 0.5621 - val_ia: 0.5050 - val_loss: 0.1780 - val_mae: 0.3311 - val_rmse: 0.3790 - val_smape: 0.7267

Epoch 9/16

1146/1146 - 20s - 18ms/step - ia: 0.8552 - loss: 0.0901 - mae: 0.2257 - rmse: 0.2956 - smape: 0.5511 - val_ia: 0.4896 - val_loss: 0.1980 - val_mae: 0.3500 - val_rmse: 0.4012 - val_smape: 0.7483

Epoch 10/16

1146/1146 - 21s - 18ms/step - ia: 0.8573 - loss: 0.0874 - mae: 0.2220 - rmse: 0.2913 - smape: 0.5405 - val_ia: 0.4930 - val_loss: 0.2010 - val_mae: 0.3506 - val_rmse: 0.3982 - val_smape: 0.7379

Epoch 11/16

1146/1146 - 17s - 15ms/step - ia: 0.8606 - loss: 0.0841 - mae: 0.2180 - rmse: 0.2859 - smape: 0.5305 - val_ia: 0.4975 - val_loss: 0.2107 - val_mae: 0.3542 - val_rmse: 0.4053 - val_smape: 0.7412

Epoch 12/16

1146/1146 - 21s - 18ms/step - ia: 0.8635 - loss: 0.0807 - mae: 0.2135 - rmse: 0.2795 - smape: 0.5210 - val_ia: 0.4874 - val_loss: 0.2058 - val_mae: 0.3541 - val_rmse: 0.4062 - val_smape: 0.7541

Epoch 13/16

1146/1146 - 41s - 36ms/step - ia: 0.8647 - loss: 0.0792 - mae: 0.2115 - rmse: 0.2775 - smape: 0.5152 - val_ia: 0.4680 - val_loss: 0.2510 - val_mae: 0.3832 - val_rmse: 0.4462 - val_smape: 0.7932

Epoch 14/16

1146/1146 - 21s - 18ms/step - ia: 0.8669 - loss: 0.0768 - mae: 0.2087 - rmse: 0.2731 - smape: 0.5076 - val_ia: 0.4838 - val_loss: 0.2114 - val_mae: 0.3588 - val_rmse: 0.4115 - val_smape: 0.7570

Epoch 15/16

1146/1146 - 18s - 16ms/step - ia: 0.8691 - loss: 0.0744 - mae: 0.2054 - rmse: 0.2688 - smape: 0.4988 - val_ia: 0.4940 - val_loss: 0.1992 - val_mae: 0.3429 - val_rmse: 0.3997 - val_smape: 0.7451

Epoch 16/16

1146/1146 - 19s - 17ms/step - ia: 0.8702 - loss: 0.0731 - mae: 0.2034 - rmse: 0.2662 - smape: 0.4952 - val_ia: 0.5072 - val_loss: 0.1711 - val_mae: 0.3259 - val_rmse: 0.3727 - val_smape: 0.7239

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:25 896ms/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 20%|██        | 10/50 [1:16:40<3:44:12, 336.31s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 14s - 48ms/step - ia: 0.2628 - loss: 1.3698 - mae: 0.9505 - rmse: 1.1682 - smape: 1.4800 - val_ia: 0.3197 - val_loss: 1.4696 - val_mae: 0.9988 - val_rmse: 1.1894 - val_smape: 1.3829

Epoch 2/8

287/287 - 3s - 9ms/step - ia: 0.2627 - loss: 1.3586 - mae: 0.9475 - rmse: 1.1637 - smape: 1.4841 - val_ia: 0.3204 - val_loss: 1.4422 - val_mae: 0.9904 - val_rmse: 1.1784 - val_smape: 1.3839

Epoch 3/8

287/287 - 3s - 11ms/step - ia: 0.2627 - loss: 1.3369 - mae: 0.9394 - rmse: 1.1544 - smape: 1.4806 - val_ia: 0.3211 - val_loss: 1.4163 - val_mae: 0.9824 - val_rmse: 1.1679 - val_smape: 1.3848

Epoch 4/8

287/287 - 3s - 10ms/step - ia: 0.2633 - loss: 1.3192 - mae: 0.9345 - rmse: 1.1467 - smape: 1.4804 - val_ia: 0.3218 - val_loss: 1.3923 - val_mae: 0.9748 - val_rmse: 1.1581 - val_smape: 1.3857

Epoch 5/8

287/287 - 3s - 11ms/step - ia: 0.2634 - loss: 1.2932 - mae: 0.9265 - rmse: 1.1353 - smape: 1.4835 - val_ia: 0.3225 - val_loss: 1.3698 - val_mae: 0.9677 - val_rmse: 1.1488 - val_smape: 1.3866

Epoch 6/8

287/287 - 3s - 12ms/step - ia: 0.2666 - loss: 1.2810 - mae: 0.9217 - rmse: 1.1296 - smape: 1.4798 - val_ia: 0.3232 - val_loss: 1.3480 - val_mae: 0.9606 - val_rmse: 1.1398 - val_smape: 1.3874

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.2671 - loss: 1.2693 - mae: 0.9163 - rmse: 1.1248 - smape: 1.4771 - val_ia: 0.3239 - val_loss: 1.3269 - val_mae: 0.9538 - val_rmse: 1.1309 - val_smape: 1.3886

Epoch 8/8

287/287 - 3s - 11ms/step - ia: 0.2683 - loss: 1.2535 - mae: 0.9112 - rmse: 1.1173 - smape: 1.4749 - val_ia: 0.3246 - val_loss: 1.3069 - val_mae: 0.9472 - val_rmse: 1.1225 - val_smape: 1.3897

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:07 1s/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step

 22%|██▏       | 11/50 [1:17:18<2:39:22, 245.20s/trial, best loss: 0.19410861421770395]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 18s - 15ms/step - ia: 0.4913 - loss: 0.6463 - mae: 0.6548 - rmse: 0.7950 - smape: 1.1585 - val_ia: 0.2367 - val_loss: 1.6360 - val_mae: 1.0672 - val_rmse: 1.1561 - val_smape: 1.3879

Epoch 2/128

1146/1146 - 10s - 8ms/step - ia: 0.6375 - loss: 0.4328 - mae: 0.5249 - rmse: 0.6527 - smape: 0.9167 - val_ia: 0.2509 - val_loss: 1.2639 - val_mae: 0.9289 - val_rmse: 1.0083 - val_smape: 1.2812

Epoch 3/128

1146/1146 - 10s - 8ms/step - ia: 0.6833 - loss: 0.3573 - mae: 0.4756 - rmse: 0.5930 - smape: 0.8320 - val_ia: 0.2866 - val_loss: 0.9142 - val_mae: 0.7781 - val_rmse: 0.8499 - val_smape: 1.1917

Epoch 4/128

1146/1146 - 12s - 10ms/step - ia: 0.7050 - loss: 0.3184 - mae: 0.4478 - rmse: 0.5595 - smape: 0.7975 - val_ia: 0.3063 - val_loss: 0.7908 - val_mae: 0.7087 - val_rmse: 0.7847 - val_smape: 1.1261

Epoch 5/128

1146/1146 - 10s - 9ms/step - ia: 0.7178 - loss: 0.2954 - mae: 0.4305 - rmse: 0.5389 - smape: 0.7777 - val_ia: 0.3255 - val_loss: 0.6704 - val_mae: 0.6524 - val_rmse: 0.7219 - val_smape: 1.0849

Epoch 6/128

1146/1146 - 9s - 8ms/step - ia: 0.7275 - loss: 0.2782 - mae: 0.4166 - rmse: 0.5228 - smape: 0.7624 - val_ia: 0.3358 - val_loss: 0.5857 - val_mae: 0.6105 - val_rmse: 0.6761 - val_smape: 1.0281

Epoch 7/128

1146/1146 - 10s - 9ms/step - ia: 0.7362 - loss: 0.2636 - mae: 0.4045 - rmse: 0.5086 - smape: 0.7517 - val_ia: 0.3291 - val_loss: 0.6453 - val_mae: 0.6379 - val_rmse: 0.7016 - val_smape: 1.0581

Epoch 8/128

1146/1146 - 10s - 9ms/step - ia: 0.7461 - loss: 0.2473 - mae: 0.3900 - rmse: 0.4929 - smape: 0.7407 - val_ia: 0.3599 - val_loss: 0.4653 - val_mae: 0.5475 - val_rmse: 0.6058 - val_smape: 0.9554

Epoch 9/128

1146/1146 - 10s - 9ms/step - ia: 0.7585 - loss: 0.2263 - mae: 0.3705 - rmse: 0.4712 - smape: 0.7305 - val_ia: 0.3778 - val_loss: 0.4230 - val_mae: 0.5214 - val_rmse: 0.5782 - val_smape: 0.9121

Epoch 10/128

1146/1146 - 10s - 9ms/step - ia: 0.7787 - loss: 0.1954 - mae: 0.3395 - rmse: 0.4371 - smape: 0.7106 - val_ia: 0.4183 - val_loss: 0.3517 - val_mae: 0.4755 - val_rmse: 0.5275 - val_smape: 0.8616

Epoch 11/128

1146/1146 - 10s - 8ms/step - ia: 0.7941 - loss: 0.1700 - mae: 0.3142 - rmse: 0.4075 - smape: 0.6909 - val_ia: 0.4468 - val_loss: 0.2322 - val_mae: 0.3991 - val_rmse: 0.4472 - val_smape: 0.8250

Epoch 12/128

1146/1146 - 8s - 7ms/step - ia: 0.8086 - loss: 0.1492 - mae: 0.2930 - rmse: 0.3812 - smape: 0.6667 - val_ia: 0.4642 - val_loss: 0.2491 - val_mae: 0.4009 - val_rmse: 0.4471 - val_smape: 0.7988

Epoch 13/128

1146/1146 - 12s - 10ms/step - ia: 0.8210 - loss: 0.1325 - mae: 0.2748 - rmse: 0.3590 - smape: 0.6389 - val_ia: 0.5054 - val_loss: 0.1761 - val_mae: 0.3421 - val_rmse: 0.3845 - val_smape: 0.7531

Epoch 14/128

1146/1146 - 10s - 8ms/step - ia: 0.8308 - loss: 0.1204 - mae: 0.2611 - rmse: 0.3424 - smape: 0.6164 - val_ia: 0.4924 - val_loss: 0.2242 - val_mae: 0.3732 - val_rmse: 0.4240 - val_smape: 0.7646

Epoch 15/128

1146/1146 - 11s - 9ms/step - ia: 0.8360 - loss: 0.1147 - mae: 0.2538 - rmse: 0.3336 - smape: 0.6024 - val_ia: 0.5341 - val_loss: 0.1642 - val_mae: 0.3222 - val_rmse: 0.3634 - val_smape: 0.7132

Epoch 16/128

1146/1146 - 10s - 9ms/step - ia: 0.8406 - loss: 0.1102 - mae: 0.2477 - rmse: 0.3268 - smape: 0.5926 - val_ia: 0.5178 - val_loss: 0.1901 - val_mae: 0.3453 - val_rmse: 0.3938 - val_smape: 0.7269

Epoch 17/128

1146/1146 - 11s - 9ms/step - ia: 0.8417 - loss: 0.1081 - mae: 0.2453 - rmse: 0.3240 - smape: 0.5874 - val_ia: 0.5244 - val_loss: 0.1830 - val_mae: 0.3399 - val_rmse: 0.3877 - val_smape: 0.7168

Epoch 18/128

1146/1146 - 9s - 7ms/step - ia: 0.8428 - loss: 0.1071 - mae: 0.2438 - rmse: 0.3219 - smape: 0.5845 - val_ia: 0.5477 - val_loss: 0.1318 - val_mae: 0.2925 - val_rmse: 0.3357 - val_smape: 0.6732

Epoch 19/128

1146/1146 - 8s - 7ms/step - ia: 0.8452 - loss: 0.1039 - mae: 0.2401 - rmse: 0.3174 - smape: 0.5815 - val_ia: 0.5400 - val_loss: 0.1616 - val_mae: 0.3169 - val_rmse: 0.3638 - val_smape: 0.6961

Epoch 20/128

1146/1146 - 10s - 8ms/step - ia: 0.8461 - loss: 0.1036 - mae: 0.2392 - rmse: 0.3168 - smape: 0.5794 - val_ia: 0.5499 - val_loss: 0.1406 - val_mae: 0.2979 - val_rmse: 0.3448 - val_smape: 0.6706

Epoch 21/128

1146/1146 - 11s - 9ms/step - ia: 0.8485 - loss: 0.1003 - mae: 0.2352 - rmse: 0.3116 - smape: 0.5711 - val_ia: 0.5427 - val_loss: 0.1487 - val_mae: 0.3066 - val_rmse: 0.3542 - val_smape: 0.6820

Epoch 22/128

1146/1146 - 9s - 8ms/step - ia: 0.8478 - loss: 0.1008 - mae: 0.2363 - rmse: 0.3124 - smape: 0.5742 - val_ia: 0.5551 - val_loss: 0.1322 - val_mae: 0.2921 - val_rmse: 0.3345 - val_smape: 0.6685

Epoch 23/128

1146/1146 - 10s - 9ms/step - ia: 0.8495 - loss: 0.0991 - mae: 0.2339 - rmse: 0.3095 - smape: 0.5703 - val_ia: 0.5573 - val_loss: 0.1297 - val_mae: 0.2867 - val_rmse: 0.3318 - val_smape: 0.6569

Epoch 24/128

1146/1146 - 12s - 11ms/step - ia: 0.8504 - loss: 0.0977 - mae: 0.2324 - rmse: 0.3079 - smape: 0.5661 - val_ia: 0.5294 - val_loss: 0.1831 - val_mae: 0.3386 - val_rmse: 0.3837 - val_smape: 0.7225

Epoch 25/128

1146/1146 - 10s - 8ms/step - ia: 0.8524 - loss: 0.0956 - mae: 0.2293 - rmse: 0.3040 - smape: 0.5593 - val_ia: 0.5136 - val_loss: 0.1995 - val_mae: 0.3534 - val_rmse: 0.4046 - val_smape: 0.7266

Epoch 26/128

1146/1146 - 10s - 8ms/step - ia: 0.8533 - loss: 0.0944 - mae: 0.2284 - rmse: 0.3024 - smape: 0.5588 - val_ia: 0.5362 - val_loss: 0.1604 - val_mae: 0.3178 - val_rmse: 0.3654 - val_smape: 0.6898

Epoch 27/128

1146/1146 - 10s - 9ms/step - ia: 0.8542 - loss: 0.0937 - mae: 0.2272 - rmse: 0.3012 - smape: 0.5537 - val_ia: 0.5306 - val_loss: 0.1618 - val_mae: 0.3176 - val_rmse: 0.3665 - val_smape: 0.6925

Epoch 28/128

1146/1146 - 10s - 9ms/step - ia: 0.8544 - loss: 0.0932 - mae: 0.2270 - rmse: 0.3005 - smape: 0.5546 - val_ia: 0.5480 - val_loss: 0.1558 - val_mae: 0.3131 - val_rmse: 0.3571 - val_smape: 0.6814

Epoch 29/128

1146/1146 - 9s - 8ms/step - ia: 0.8548 - loss: 0.0930 - mae: 0.2263 - rmse: 0.3003 - smape: 0.5505 - val_ia: 0.5583 - val_loss: 0.1361 - val_mae: 0.2943 - val_rmse: 0.3344 - val_smape: 0.6635

Epoch 30/128

1146/1146 - 11s - 9ms/step - ia: 0.8555 - loss: 0.0914 - mae: 0.2251 - rmse: 0.2973 - smape: 0.5495 - val_ia: 0.5605 - val_loss: 0.1334 - val_mae: 0.2902 - val_rmse: 0.3357 - val_smape: 0.6547

Epoch 31/128

1146/1146 - 10s - 9ms/step - ia: 0.8570 - loss: 0.0897 - mae: 0.2232 - rmse: 0.2949 - smape: 0.5483 - val_ia: 0.5380 - val_loss: 0.1661 - val_mae: 0.3235 - val_rmse: 0.3688 - val_smape: 0.6841

Epoch 32/128

1146/1146 - 9s - 8ms/step - ia: 0.8573 - loss: 0.0890 - mae: 0.2228 - rmse: 0.2936 - smape: 0.5456 - val_ia: 0.5319 - val_loss: 0.1589 - val_mae: 0.3162 - val_rmse: 0.3652 - val_smape: 0.6827

Epoch 33/128

1146/1146 - 10s - 9ms/step - ia: 0.8575 - loss: 0.0890 - mae: 0.2224 - rmse: 0.2939 - smape: 0.5469 - val_ia: 0.5317 - val_loss: 0.1584 - val_mae: 0.3173 - val_rmse: 0.3660 - val_smape: 0.6838

Epoch 34/128

1146/1146 - 8s - 7ms/step - ia: 0.8592 - loss: 0.0871 - mae: 0.2203 - rmse: 0.2904 - smape: 0.5406 - val_ia: 0.5476 - val_loss: 0.1463 - val_mae: 0.3038 - val_rmse: 0.3504 - val_smape: 0.6647

Epoch 35/128

1146/1146 - 11s - 10ms/step - ia: 0.8591 - loss: 0.0870 - mae: 0.2196 - rmse: 0.2904 - smape: 0.5389 - val_ia: 0.5351 - val_loss: 0.1528 - val_mae: 0.3137 - val_rmse: 0.3593 - val_smape: 0.6785

Epoch 36/128

1146/1146 - 10s - 9ms/step - ia: 0.8603 - loss: 0.0858 - mae: 0.2185 - rmse: 0.2885 - smape: 0.5355 - val_ia: 0.5464 - val_loss: 0.1429 - val_mae: 0.3037 - val_rmse: 0.3465 - val_smape: 0.6646

Epoch 37/128

1146/1146 - 11s - 10ms/step - ia: 0.8597 - loss: 0.0860 - mae: 0.2195 - rmse: 0.2890 - smape: 0.5381 - val_ia: 0.5633 - val_loss: 0.1262 - val_mae: 0.2855 - val_rmse: 0.3279 - val_smape: 0.6401

Epoch 38/128

1146/1146 - 10s - 9ms/step - ia: 0.8604 - loss: 0.0856 - mae: 0.2184 - rmse: 0.2880 - smape: 0.5359 - val_ia: 0.5385 - val_loss: 0.1679 - val_mae: 0.3240 - val_rmse: 0.3676 - val_smape: 0.6878

Epoch 39/128

1146/1146 - 12s - 10ms/step - ia: 0.8618 - loss: 0.0836 - mae: 0.2158 - rmse: 0.2846 - smape: 0.5320 - val_ia: 0.5481 - val_loss: 0.1413 - val_mae: 0.3035 - val_rmse: 0.3443 - val_smape: 0.6630

Epoch 40/128

1146/1146 - 10s - 9ms/step - ia: 0.8631 - loss: 0.0827 - mae: 0.2144 - rmse: 0.2832 - smape: 0.5283 - val_ia: 0.5270 - val_loss: 0.1625 - val_mae: 0.3235 - val_rmse: 0.3699 - val_smape: 0.6906

Epoch 41/128

1146/1146 - 12s - 10ms/step - ia: 0.8626 - loss: 0.0824 - mae: 0.2149 - rmse: 0.2826 - smape: 0.5292 - val_ia: 0.5416 - val_loss: 0.1559 - val_mae: 0.3147 - val_rmse: 0.3570 - val_smape: 0.6757

Epoch 42/128

1146/1146 - 9s - 8ms/step - ia: 0.8630 - loss: 0.0822 - mae: 0.2145 - rmse: 0.2821 - smape: 0.5256 - val_ia: 0.5330 - val_loss: 0.1610 - val_mae: 0.3200 - val_rmse: 0.3657 - val_smape: 0.6833

Epoch 43/128

1146/1146 - 12s - 10ms/step - ia: 0.8635 - loss: 0.0815 - mae: 0.2137 - rmse: 0.2810 - smape: 0.5268 - val_ia: 0.5368 - val_loss: 0.1672 - val_mae: 0.3235 - val_rmse: 0.3641 - val_smape: 0.6945

Epoch 44/128

1146/1146 - 19s - 17ms/step - ia: 0.8639 - loss: 0.0807 - mae: 0.2128 - rmse: 0.2798 - smape: 0.5246 - val_ia: 0.5241 - val_loss: 0.1714 - val_mae: 0.3305 - val_rmse: 0.3761 - val_smape: 0.7032

Epoch 45/128

1146/1146 - 10s - 9ms/step - ia: 0.8646 - loss: 0.0803 - mae: 0.2121 - rmse: 0.2789 - smape: 0.5220 - val_ia: 0.5391 - val_loss: 0.1497 - val_mae: 0.3089 - val_rmse: 0.3557 - val_smape: 0.6729

Epoch 46/128

1146/1146 - 11s - 10ms/step - ia: 0.8656 - loss: 0.0795 - mae: 0.2110 - rmse: 0.2778 - smape: 0.5200 - val_ia: 0.5365 - val_loss: 0.1551 - val_mae: 0.3144 - val_rmse: 0.3589 - val_smape: 0.6799

Epoch 47/128

1146/1146 - 10s - 9ms/step - ia: 0.8653 - loss: 0.0794 - mae: 0.2110 - rmse: 0.2772 - smape: 0.5221 - val_ia: 0.5286 - val_loss: 0.1712 - val_mae: 0.3291 - val_rmse: 0.3734 - val_smape: 0.6939

Epoch 48/128

1146/1146 - 11s - 10ms/step - ia: 0.8670 - loss: 0.0776 - mae: 0.2085 - rmse: 0.2744 - smape: 0.5156 - val_ia: 0.5284 - val_loss: 0.1595 - val_mae: 0.3180 - val_rmse: 0.3657 - val_smape: 0.6843

Epoch 49/128

1146/1146 - 10s - 9ms/step - ia: 0.8671 - loss: 0.0771 - mae: 0.2079 - rmse: 0.2735 - smape: 0.5151 - val_ia: 0.5478 - val_loss: 0.1409 - val_mae: 0.3017 - val_rmse: 0.3417 - val_smape: 0.6647

Epoch 50/128

1146/1146 - 12s - 10ms/step - ia: 0.8689 - loss: 0.0755 - mae: 0.2057 - rmse: 0.2708 - smape: 0.5095 - val_ia: 0.5178 - val_loss: 0.1777 - val_mae: 0.3350 - val_rmse: 0.3846 - val_smape: 0.7003

Epoch 51/128

1146/1146 - 12s - 10ms/step - ia: 0.8680 - loss: 0.0768 - mae: 0.2072 - rmse: 0.2723 - smape: 0.5137 - val_ia: 0.5338 - val_loss: 0.1381 - val_mae: 0.3006 - val_rmse: 0.3442 - val_smape: 0.6711

Epoch 52/128

1146/1146 - 8s - 7ms/step - ia: 0.8688 - loss: 0.0757 - mae: 0.2061 - rmse: 0.2707 - smape: 0.5108 - val_ia: 0.5074 - val_loss: 0.1984 - val_mae: 0.3532 - val_rmse: 0.4032 - val_smape: 0.7240

Epoch 52: early stopping

Restoring model weights from the end of the best epoch: 37.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:47 662ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 24%|██▍       | 12/50 [1:26:25<3:33:18, 336.81s/trial, best loss: 0.17585821508012853]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 40s - 139ms/step - ia: 0.6311 - loss: 0.4067 - mae: 0.5008 - rmse: 0.6201 - smape: 0.9382 - val_ia: 0.6692 - val_loss: 0.5357 - val_mae: 0.5304 - val_rmse: 0.6731 - val_smape: 0.8628

Epoch 2/16

287/287 - 6s - 20ms/step - ia: 0.7824 - loss: 0.1907 - mae: 0.3386 - rmse: 0.4350 - smape: 0.7159 - val_ia: 0.7372 - val_loss: 0.2193 - val_mae: 0.3749 - val_rmse: 0.4386 - val_smape: 0.8071

Epoch 3/16

287/287 - 10s - 34ms/step - ia: 0.8193 - loss: 0.1376 - mae: 0.2832 - rmse: 0.3697 - smape: 0.6540 - val_ia: 0.7385 - val_loss: 0.2366 - val_mae: 0.3826 - val_rmse: 0.4580 - val_smape: 0.7968

Epoch 4/16

287/287 - 6s - 19ms/step - ia: 0.8342 - loss: 0.1185 - mae: 0.2614 - rmse: 0.3431 - smape: 0.6183 - val_ia: 0.7649 - val_loss: 0.1891 - val_mae: 0.3417 - val_rmse: 0.4082 - val_smape: 0.7183

Epoch 5/16

287/287 - 6s - 20ms/step - ia: 0.8416 - loss: 0.1098 - mae: 0.2509 - rmse: 0.3300 - smape: 0.5970 - val_ia: 0.7523 - val_loss: 0.2164 - val_mae: 0.3611 - val_rmse: 0.4334 - val_smape: 0.7402

Epoch 6/16

287/287 - 4s - 15ms/step - ia: 0.8470 - loss: 0.1032 - mae: 0.2428 - rmse: 0.3201 - smape: 0.5809 - val_ia: 0.7504 - val_loss: 0.2215 - val_mae: 0.3679 - val_rmse: 0.4403 - val_smape: 0.7538

Epoch 7/16

287/287 - 5s - 18ms/step - ia: 0.8508 - loss: 0.0989 - mae: 0.2374 - rmse: 0.3132 - smape: 0.5685 - val_ia: 0.7464 - val_loss: 0.2288 - val_mae: 0.3745 - val_rmse: 0.4529 - val_smape: 0.7538

Epoch 8/16

287/287 - 10s - 34ms/step - ia: 0.8526 - loss: 0.0963 - mae: 0.2348 - rmse: 0.3094 - smape: 0.5645 - val_ia: 0.7417 - val_loss: 0.2271 - val_mae: 0.3705 - val_rmse: 0.4559 - val_smape: 0.7635

Epoch 9/16

287/287 - 4s - 15ms/step - ia: 0.8557 - loss: 0.0926 - mae: 0.2301 - rmse: 0.3031 - smape: 0.5571 - val_ia: 0.7299 - val_loss: 0.2686 - val_mae: 0.3926 - val_rmse: 0.4998 - val_smape: 0.7808

Epoch 10/16

287/287 - 4s - 13ms/step - ia: 0.8575 - loss: 0.0900 - mae: 0.2275 - rmse: 0.2989 - smape: 0.5492 - val_ia: 0.7464 - val_loss: 0.2172 - val_mae: 0.3612 - val_rmse: 0.4352 - val_smape: 0.7532

Epoch 11/16

287/287 - 4s - 12ms/step - ia: 0.8599 - loss: 0.0876 - mae: 0.2238 - rmse: 0.2950 - smape: 0.5437 - val_ia: 0.7571 - val_loss: 0.1929 - val_mae: 0.3479 - val_rmse: 0.4207 - val_smape: 0.7413

Epoch 12/16

287/287 - 4s - 13ms/step - ia: 0.8608 - loss: 0.0860 - mae: 0.2223 - rmse: 0.2919 - smape: 0.5441 - val_ia: 0.7511 - val_loss: 0.2107 - val_mae: 0.3585 - val_rmse: 0.4324 - val_smape: 0.7462

Epoch 13/16

287/287 - 5s - 18ms/step - ia: 0.8632 - loss: 0.0835 - mae: 0.2186 - rmse: 0.2879 - smape: 0.5335 - val_ia: 0.7360 - val_loss: 0.2423 - val_mae: 0.3797 - val_rmse: 0.4626 - val_smape: 0.7689

Epoch 14/16

287/287 - 4s - 14ms/step - ia: 0.8643 - loss: 0.0826 - mae: 0.2173 - rmse: 0.2862 - smape: 0.5282 - val_ia: 0.7580 - val_loss: 0.2018 - val_mae: 0.3498 - val_rmse: 0.4215 - val_smape: 0.7331

Epoch 15/16

287/287 - 5s - 18ms/step - ia: 0.8654 - loss: 0.0811 - mae: 0.2157 - rmse: 0.2835 - smape: 0.5278 - val_ia: 0.7428 - val_loss: 0.2219 - val_mae: 0.3670 - val_rmse: 0.4470 - val_smape: 0.7610

Epoch 16/16

287/287 - 4s - 15ms/step - ia: 0.8659 - loss: 0.0805 - mae: 0.2146 - rmse: 0.2827 - smape: 0.5239 - val_ia: 0.7277 - val_loss: 0.2543 - val_mae: 0.3874 - val_rmse: 0.4817 - val_smape: 0.7804

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:55 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step

 26%|██▌       | 13/50 [1:28:30<2:48:06, 272.61s/trial, best loss: 0.17585821508012853]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 7s - 25ms/step - ia: 0.4682 - loss: 0.6519 - mae: 0.6662 - rmse: 0.8032 - smape: 1.2062 - val_ia: 0.4707 - val_loss: 0.8160 - val_mae: 0.7564 - val_rmse: 0.8809 - val_smape: 1.2434

Epoch 2/8

287/287 - 3s - 11ms/step - ia: 0.6438 - loss: 0.4207 - mae: 0.5189 - rmse: 0.6469 - smape: 0.9140 - val_ia: 0.5021 - val_loss: 0.8067 - val_mae: 0.7576 - val_rmse: 0.8722 - val_smape: 1.1901

Epoch 3/8

287/287 - 5s - 17ms/step - ia: 0.6853 - loss: 0.3539 - mae: 0.4761 - rmse: 0.5937 - smape: 0.8377 - val_ia: 0.5421 - val_loss: 0.6879 - val_mae: 0.6939 - val_rmse: 0.8008 - val_smape: 1.1218

Epoch 4/8

287/287 - 2s - 8ms/step - ia: 0.7030 - loss: 0.3239 - mae: 0.4545 - rmse: 0.5680 - smape: 0.8093 - val_ia: 0.5817 - val_loss: 0.5553 - val_mae: 0.6237 - val_rmse: 0.7178 - val_smape: 1.0585

Epoch 5/8

287/287 - 2s - 8ms/step - ia: 0.7151 - loss: 0.3052 - mae: 0.4395 - rmse: 0.5513 - smape: 0.7942 - val_ia: 0.5881 - val_loss: 0.5395 - val_mae: 0.6134 - val_rmse: 0.7101 - val_smape: 1.0503

Epoch 6/8

287/287 - 3s - 10ms/step - ia: 0.7228 - loss: 0.2910 - mae: 0.4277 - rmse: 0.5384 - smape: 0.7854 - val_ia: 0.6007 - val_loss: 0.4885 - val_mae: 0.5880 - val_rmse: 0.6764 - val_smape: 1.0330

Epoch 7/8

287/287 - 2s - 8ms/step - ia: 0.7306 - loss: 0.2789 - mae: 0.4175 - rmse: 0.5269 - smape: 0.7782 - val_ia: 0.6299 - val_loss: 0.4164 - val_mae: 0.5425 - val_rmse: 0.6260 - val_smape: 0.9953

Epoch 8/8

287/287 - 3s - 11ms/step - ia: 0.7371 - loss: 0.2674 - mae: 0.4082 - rmse: 0.5165 - smape: 0.7708 - val_ia: 0.6225 - val_loss: 0.4182 - val_mae: 0.5406 - val_rmse: 0.6317 - val_smape: 1.0328

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:29 550ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 28%|██▊       | 14/50 [1:29:01<1:59:54, 199.84s/trial, best loss: 0.17585821508012853]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 10s - 17ms/step - ia: 0.7600 - loss: 0.2279 - mae: 0.3643 - rmse: 0.4647 - smape: 0.7359 - val_ia: 0.6846 - val_loss: 0.1817 - val_mae: 0.3321 - val_rmse: 0.3934 - val_smape: 0.7415

Epoch 2/16

573/573 - 5s - 8ms/step - ia: 0.8184 - loss: 0.1369 - mae: 0.2818 - rmse: 0.3674 - smape: 0.6253 - val_ia: 0.7028 - val_loss: 0.1625 - val_mae: 0.3186 - val_rmse: 0.3756 - val_smape: 0.7030

Epoch 3/16

573/573 - 4s - 7ms/step - ia: 0.8246 - loss: 0.1281 - mae: 0.2732 - rmse: 0.3552 - smape: 0.6062 - val_ia: 0.7296 - val_loss: 0.1264 - val_mae: 0.2806 - val_rmse: 0.3293 - val_smape: 0.6372

Epoch 4/16

573/573 - 4s - 7ms/step - ia: 0.8311 - loss: 0.1196 - mae: 0.2634 - rmse: 0.3437 - smape: 0.5880 - val_ia: 0.6971 - val_loss: 0.1771 - val_mae: 0.3244 - val_rmse: 0.3757 - val_smape: 0.6853

Epoch 5/16

573/573 - 6s - 10ms/step - ia: 0.8368 - loss: 0.1124 - mae: 0.2561 - rmse: 0.3329 - smape: 0.5671 - val_ia: 0.6934 - val_loss: 0.1656 - val_mae: 0.3191 - val_rmse: 0.3699 - val_smape: 0.6898

Epoch 6/16

573/573 - 5s - 8ms/step - ia: 0.8394 - loss: 0.1092 - mae: 0.2521 - rmse: 0.3283 - smape: 0.5574 - val_ia: 0.6652 - val_loss: 0.2447 - val_mae: 0.3754 - val_rmse: 0.4411 - val_smape: 0.7476

Epoch 7/16

573/573 - 4s - 7ms/step - ia: 0.8413 - loss: 0.1066 - mae: 0.2492 - rmse: 0.3245 - smape: 0.5507 - val_ia: 0.6694 - val_loss: 0.2319 - val_mae: 0.3681 - val_rmse: 0.4296 - val_smape: 0.7310

Epoch 8/16

573/573 - 5s - 9ms/step - ia: 0.8449 - loss: 0.1027 - mae: 0.2442 - rmse: 0.3181 - smape: 0.5410 - val_ia: 0.7062 - val_loss: 0.1532 - val_mae: 0.3074 - val_rmse: 0.3627 - val_smape: 0.6625

Epoch 9/16

573/573 - 3s - 6ms/step - ia: 0.8462 - loss: 0.1008 - mae: 0.2423 - rmse: 0.3155 - smape: 0.5368 - val_ia: 0.7033 - val_loss: 0.1476 - val_mae: 0.3034 - val_rmse: 0.3531 - val_smape: 0.6704

Epoch 10/16

573/573 - 5s - 9ms/step - ia: 0.8483 - loss: 0.0991 - mae: 0.2391 - rmse: 0.3127 - smape: 0.5280 - val_ia: 0.7029 - val_loss: 0.1477 - val_mae: 0.3052 - val_rmse: 0.3542 - val_smape: 0.6745

Epoch 11/16

573/573 - 6s - 10ms/step - ia: 0.8482 - loss: 0.0993 - mae: 0.2396 - rmse: 0.3129 - smape: 0.5278 - val_ia: 0.6725 - val_loss: 0.2057 - val_mae: 0.3543 - val_rmse: 0.4115 - val_smape: 0.7262

Epoch 12/16

573/573 - 3s - 5ms/step - ia: 0.8506 - loss: 0.0963 - mae: 0.2358 - rmse: 0.3082 - smape: 0.5221 - val_ia: 0.6856 - val_loss: 0.1870 - val_mae: 0.3335 - val_rmse: 0.3997 - val_smape: 0.6917

Epoch 13/16

573/573 - 4s - 7ms/step - ia: 0.8506 - loss: 0.0962 - mae: 0.2359 - rmse: 0.3081 - smape: 0.5215 - val_ia: 0.7082 - val_loss: 0.1541 - val_mae: 0.3042 - val_rmse: 0.3584 - val_smape: 0.6534

Epoch 14/16

573/573 - 5s - 8ms/step - ia: 0.8531 - loss: 0.0932 - mae: 0.2323 - rmse: 0.3032 - smape: 0.5160 - val_ia: 0.6797 - val_loss: 0.2040 - val_mae: 0.3432 - val_rmse: 0.4160 - val_smape: 0.7074

Epoch 15/16

573/573 - 4s - 7ms/step - ia: 0.8542 - loss: 0.0919 - mae: 0.2306 - rmse: 0.3014 - smape: 0.5134 - val_ia: 0.6932 - val_loss: 0.1744 - val_mae: 0.3234 - val_rmse: 0.3793 - val_smape: 0.6962

Epoch 16/16

573/573 - 5s - 9ms/step - ia: 0.8541 - loss: 0.0921 - mae: 0.2307 - rmse: 0.3014 - smape: 0.5140 - val_ia: 0.6855 - val_loss: 0.1851 - val_mae: 0.3324 - val_rmse: 0.3938 - val_smape: 0.6973

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:21 502ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 30%|███       | 15/50 [1:30:20<1:35:21, 163.47s/trial, best loss: 0.17585821508012853]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 47s - 10ms/step - ia: 0.7343 - loss: 0.2272 - mae: 0.3651 - rmse: 0.4514 - smape: 0.7356 - val_ia: 0.2339 - val_loss: 0.2033 - val_mae: 0.3571 - val_rmse: 0.3765 - val_smape: 0.7340

Epoch 2/256

4584/4584 - 33s - 7ms/step - ia: 0.7847 - loss: 0.1539 - mae: 0.2990 - rmse: 0.3745 - smape: 0.6480 - val_ia: 0.2302 - val_loss: 0.2226 - val_mae: 0.3622 - val_rmse: 0.3852 - val_smape: 0.7756

Epoch 3/256

4584/4584 - 41s - 9ms/step - ia: 0.7919 - loss: 0.1489 - mae: 0.2912 - rmse: 0.3659 - smape: 0.6341 - val_ia: 0.2353 - val_loss: 0.2127 - val_mae: 0.3580 - val_rmse: 0.3772 - val_smape: 0.7559

Epoch 4/256

4584/4584 - 32s - 7ms/step - ia: 0.8004 - loss: 0.1370 - mae: 0.2794 - rmse: 0.3521 - smape: 0.6170 - val_ia: 0.2619 - val_loss: 0.1438 - val_mae: 0.3092 - val_rmse: 0.3253 - val_smape: 0.6807

Epoch 5/256

4584/4584 - 32s - 7ms/step - ia: 0.8072 - loss: 0.1275 - mae: 0.2703 - rmse: 0.3398 - smape: 0.6026 - val_ia: 0.2564 - val_loss: 0.1965 - val_mae: 0.3295 - val_rmse: 0.3534 - val_smape: 0.6783

Epoch 6/256

4584/4584 - 32s - 7ms/step - ia: 0.7712 - loss: 840.4384 - mae: 0.5073 - rmse: 0.9331 - smape: 0.6589 - val_ia: 0.1316 - val_loss: 166.5529 - val_mae: 2.4425 - val_rmse: 3.4026 - val_smape: 1.4046

Epoch 7/256

4584/4584 - 31s - 7ms/step - ia: 0.2236 - loss: 17.3989 - mae: 1.0601 - rmse: 1.5104 - smape: 1.5947 - val_ia: 0.1441 - val_loss: 6.7028 - val_mae: 0.8518 - val_rmse: 0.9478 - val_smape: 1.6617

Epoch 8/256

4584/4584 - 31s - 7ms/step - ia: 0.2416 - loss: 1.2446 - mae: 0.8484 - rmse: 1.0371 - smape: 1.6565 - val_ia: 0.1503 - val_loss: 3.5565 - val_mae: 0.7707 - val_rmse: 0.8518 - val_smape: 1.4497

Epoch 9/256

4584/4584 - 39s - 8ms/step - ia: 0.2830 - loss: 2.1068 - mae: 0.8166 - rmse: 1.0071 - smape: 1.5340 - val_ia: 0.1515 - val_loss: 0.8199 - val_mae: 0.7244 - val_rmse: 0.7503 - val_smape: 1.5558

Epoch 10/256

4584/4584 - 41s - 9ms/step - ia: 0.2486 - loss: 0.9833 - mae: 0.8065 - rmse: 0.9628 - smape: 1.6936 - val_ia: 0.1582 - val_loss: 0.7156 - val_mae: 0.6825 - val_rmse: 0.7027 - val_smape: 1.4617

Epoch 11/256

4584/4584 - 29s - 6ms/step - ia: 0.3497 - loss: 0.9148 - mae: 0.7384 - rmse: 0.8948 - smape: 1.3800 - val_ia: 0.1460 - val_loss: 0.7997 - val_mae: 0.7327 - val_rmse: 0.7526 - val_smape: 1.4842

Epoch 12/256

4584/4584 - 40s - 9ms/step - ia: 0.2941 - loss: 1.5651 - mae: 0.8006 - rmse: 0.9833 - smape: 1.5289 - val_ia: 0.1457 - val_loss: 0.7581 - val_mae: 0.7131 - val_rmse: 0.7395 - val_smape: 1.5161

Epoch 13/256

4584/4584 - 28s - 6ms/step - ia: 0.2302 - loss: 118.5582 - mae: 1.6775 - rmse: 2.7982 - smape: 1.5962 - val_ia: 0.1088 - val_loss: 22.2939 - val_mae: 1.7385 - val_rmse: 2.2543 - val_smape: 1.6867

Epoch 14/256

4584/4584 - 42s - 9ms/step - ia: 0.2105 - loss: 1339.9966 - mae: 2.6039 - rmse: 5.1854 - smape: 1.7773 - val_ia: 0.0977 - val_loss: 41.4660 - val_mae: 2.1054 - val_rmse: 3.0413 - val_smape: 1.2914

Epoch 15/256

4584/4584 - 28s - 6ms/step - ia: 0.2146 - loss: 251.7570 - mae: 2.4392 - rmse: 4.6179 - smape: 1.5357 - val_ia: 0.1370 - val_loss: 0.8694 - val_mae: 0.7725 - val_rmse: 0.7942 - val_smape: 1.8123

Epoch 16/256

4584/4584 - 41s - 9ms/step - ia: 0.2020 - loss: 190.5861 - mae: 2.1966 - rmse: 3.9703 - smape: 1.7110 - val_ia: 0.1086 - val_loss: 3.9106 - val_mae: 1.1938 - val_rmse: 1.3943 - val_smape: 1.6378

Epoch 17/256

4584/4584 - 29s - 6ms/step - ia: 0.2180 - loss: 96.7647 - mae: 1.5078 - rmse: 2.4932 - smape: 1.7253 - val_ia: 0.0759 - val_loss: 51.1789 - val_mae: 2.7617 - val_rmse: 3.6420 - val_smape: 1.4961

Epoch 18/256

4584/4584 - 25s - 5ms/step - ia: 0.2120 - loss: 111.8217 - mae: 1.8942 - rmse: 3.2928 - smape: 1.6246 - val_ia: 0.1272 - val_loss: 2.6291 - val_mae: 0.8352 - val_rmse: 0.9094 - val_smape: 1.7454

Epoch 19/256

4584/4584 - 43s - 9ms/step - ia: 0.2188 - loss: 14.2515 - mae: 1.0713 - rmse: 1.5194 - smape: 1.6836 - val_ia: 0.1372 - val_loss: 5.2548 - val_mae: 0.8543 - val_rmse: 1.0300 - val_smape: 1.7310

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:31 563ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 32%|███▏      | 16/50 [1:41:28<2:58:33, 315.10s/trial, best loss: 0.1744616495888466]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 63s - 14ms/step - ia: 0.6811 - loss: 0.3161 - mae: 0.4320 - rmse: 0.5281 - smape: 0.8154 - val_ia: 0.1938 - val_loss: 0.3398 - val_mae: 0.4667 - val_rmse: 0.4832 - val_smape: 0.8965

Epoch 2/256

4584/4584 - 82s - 18ms/step - ia: 0.7952 - loss: 0.1427 - mae: 0.2855 - rmse: 0.3588 - smape: 0.6677 - val_ia: 0.2682 - val_loss: 0.1670 - val_mae: 0.3266 - val_rmse: 0.3419 - val_smape: 0.7161

Epoch 3/256

4584/4584 - 51s - 11ms/step - ia: 0.8149 - loss: 0.1182 - mae: 0.2583 - rmse: 0.3257 - smape: 0.6264 - val_ia: 0.2345 - val_loss: 0.2070 - val_mae: 0.3687 - val_rmse: 0.3839 - val_smape: 0.7683

Epoch 4/256

4584/4584 - 51s - 11ms/step - ia: 0.8253 - loss: 0.1074 - mae: 0.2446 - rmse: 0.3107 - smape: 0.5920 - val_ia: 0.2600 - val_loss: 0.1383 - val_mae: 0.3065 - val_rmse: 0.3213 - val_smape: 0.6986

Epoch 5/256

4584/4584 - 86s - 19ms/step - ia: 0.8337 - loss: 0.0984 - mae: 0.2339 - rmse: 0.2964 - smape: 0.5648 - val_ia: 0.2474 - val_loss: 0.2011 - val_mae: 0.3531 - val_rmse: 0.3728 - val_smape: 0.7532

Epoch 6/256

4584/4584 - 52s - 11ms/step - ia: 0.8411 - loss: 0.0907 - mae: 0.2250 - rmse: 0.2848 - smape: 0.5407 - val_ia: 0.2541 - val_loss: 0.2060 - val_mae: 0.3601 - val_rmse: 0.3764 - val_smape: 0.7466

Epoch 7/256

4584/4584 - 82s - 18ms/step - ia: 0.8465 - loss: 0.0844 - mae: 0.2171 - rmse: 0.2743 - smape: 0.5230 - val_ia: 0.2673 - val_loss: 0.1912 - val_mae: 0.3359 - val_rmse: 0.3552 - val_smape: 0.7104

Epoch 8/256

4584/4584 - 54s - 12ms/step - ia: 0.8513 - loss: 0.0801 - mae: 0.2115 - rmse: 0.2679 - smape: 0.5109 - val_ia: 0.2855 - val_loss: 0.1609 - val_mae: 0.3070 - val_rmse: 0.3252 - val_smape: 0.6900

Epoch 9/256

4584/4584 - 59s - 13ms/step - ia: 0.8539 - loss: 0.0766 - mae: 0.2069 - rmse: 0.2618 - smape: 0.4995 - val_ia: 0.2624 - val_loss: 0.2101 - val_mae: 0.3491 - val_rmse: 0.3695 - val_smape: 0.7442

Epoch 10/256

4584/4584 - 55s - 12ms/step - ia: 0.8557 - loss: 0.0746 - mae: 0.2042 - rmse: 0.2582 - smape: 0.4964 - val_ia: 0.2907 - val_loss: 0.1406 - val_mae: 0.2905 - val_rmse: 0.3097 - val_smape: 0.6664

Epoch 11/256

4584/4584 - 85s - 19ms/step - ia: 0.8585 - loss: 0.0721 - mae: 0.2011 - rmse: 0.2540 - smape: 0.4896 - val_ia: 0.2871 - val_loss: 0.1241 - val_mae: 0.2794 - val_rmse: 0.2968 - val_smape: 0.6510

Epoch 12/256

4584/4584 - 82s - 18ms/step - ia: 0.8610 - loss: 0.0704 - mae: 0.1978 - rmse: 0.2506 - smape: 0.4846 - val_ia: 0.2728 - val_loss: 0.1654 - val_mae: 0.3141 - val_rmse: 0.3340 - val_smape: 0.7071

Epoch 13/256

4584/4584 - 49s - 11ms/step - ia: 0.8636 - loss: 0.0677 - mae: 0.1945 - rmse: 0.2460 - smape: 0.4788 - val_ia: 0.2851 - val_loss: 0.1517 - val_mae: 0.3012 - val_rmse: 0.3206 - val_smape: 0.6760

Epoch 14/256

4584/4584 - 60s - 13ms/step - ia: 0.8651 - loss: 0.0667 - mae: 0.1923 - rmse: 0.2439 - smape: 0.4735 - val_ia: 0.2800 - val_loss: 0.1485 - val_mae: 0.3008 - val_rmse: 0.3207 - val_smape: 0.6851

Epoch 15/256

4584/4584 - 61s - 13ms/step - ia: 0.8667 - loss: 0.0647 - mae: 0.1894 - rmse: 0.2403 - smape: 0.4669 - val_ia: 0.2830 - val_loss: 0.1465 - val_mae: 0.2971 - val_rmse: 0.3158 - val_smape: 0.6715

Epoch 16/256

4584/4584 - 82s - 18ms/step - ia: 0.8688 - loss: 0.0639 - mae: 0.1873 - rmse: 0.2380 - smape: 0.4625 - val_ia: 0.2767 - val_loss: 0.1663 - val_mae: 0.3190 - val_rmse: 0.3342 - val_smape: 0.6975

Epoch 17/256

4584/4584 - 61s - 13ms/step - ia: 0.8701 - loss: 0.0624 - mae: 0.1855 - rmse: 0.2363 - smape: 0.4603 - val_ia: 0.2833 - val_loss: 0.1779 - val_mae: 0.3206 - val_rmse: 0.3404 - val_smape: 0.6996

Epoch 18/256

4584/4584 - 62s - 13ms/step - ia: 0.8709 - loss: 0.0611 - mae: 0.1839 - rmse: 0.2334 - smape: 0.4566 - val_ia: 0.2873 - val_loss: 0.1398 - val_mae: 0.2904 - val_rmse: 0.3092 - val_smape: 0.6756

Epoch 19/256

4584/4584 - 57s - 13ms/step - ia: 0.8721 - loss: 0.0599 - mae: 0.1824 - rmse: 0.2311 - smape: 0.4538 - val_ia: 0.2619 - val_loss: 0.1769 - val_mae: 0.3262 - val_rmse: 0.3463 - val_smape: 0.7340

Epoch 20/256

4584/4584 - 57s - 12ms/step - ia: 0.8736 - loss: 0.0586 - mae: 0.1803 - rmse: 0.2283 - smape: 0.4510 - val_ia: 0.2559 - val_loss: 0.1988 - val_mae: 0.3433 - val_rmse: 0.3641 - val_smape: 0.7455

Epoch 21/256

4584/4584 - 57s - 12ms/step - ia: 0.8750 - loss: 0.0576 - mae: 0.1787 - rmse: 0.2264 - smape: 0.4455 - val_ia: 0.2729 - val_loss: 0.1770 - val_mae: 0.3229 - val_rmse: 0.3428 - val_smape: 0.7055

Epoch 22/256

4584/4584 - 59s - 13ms/step - ia: 0.8760 - loss: 0.0567 - mae: 0.1768 - rmse: 0.2246 - smape: 0.4437 - val_ia: 0.2718 - val_loss: 0.1826 - val_mae: 0.3277 - val_rmse: 0.3478 - val_smape: 0.7121

Epoch 23/256

4584/4584 - 59s - 13ms/step - ia: 0.8768 - loss: 0.0564 - mae: 0.1761 - rmse: 0.2236 - smape: 0.4418 - val_ia: 0.2677 - val_loss: 0.1912 - val_mae: 0.3356 - val_rmse: 0.3543 - val_smape: 0.7225

Epoch 24/256

4584/4584 - 51s - 11ms/step - ia: 0.8783 - loss: 0.0549 - mae: 0.1742 - rmse: 0.2207 - smape: 0.4384 - val_ia: 0.2483 - val_loss: 0.2092 - val_mae: 0.3541 - val_rmse: 0.3731 - val_smape: 0.7469

Epoch 25/256

4584/4584 - 56s - 12ms/step - ia: 0.8777 - loss: 0.0557 - mae: 0.1747 - rmse: 0.2222 - smape: 0.4402 - val_ia: 0.2550 - val_loss: 0.2133 - val_mae: 0.3544 - val_rmse: 0.3745 - val_smape: 0.7397

Epoch 26/256

4584/4584 - 50s - 11ms/step - ia: 0.8790 - loss: 0.0544 - mae: 0.1731 - rmse: 0.2197 - smape: 0.4334 - val_ia: 0.2651 - val_loss: 0.1847 - val_mae: 0.3310 - val_rmse: 0.3506 - val_smape: 0.7045

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:12 1s/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 34%|███▍      | 17/50 [2:08:37<6:30:40, 710.33s/trial, best loss: 0.1659520630211836]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 11s - 38ms/step - ia: 0.1327 - loss: 1.1412 - mae: 0.8792 - rmse: 1.0669 - smape: 1.6693 - val_ia: 0.2125 - val_loss: 0.9473 - val_mae: 0.8021 - val_rmse: 0.9675 - val_smape: 1.6740

Epoch 2/16

287/287 - 4s - 14ms/step - ia: 0.1365 - loss: 1.1132 - mae: 0.8699 - rmse: 1.0538 - smape: 1.6703 - val_ia: 0.2119 - val_loss: 0.9258 - val_mae: 0.7939 - val_rmse: 0.9564 - val_smape: 1.6994

Epoch 3/16

287/287 - 4s - 13ms/step - ia: 0.1403 - loss: 1.0882 - mae: 0.8611 - rmse: 1.0420 - smape: 1.6683 - val_ia: 0.2115 - val_loss: 0.9060 - val_mae: 0.7863 - val_rmse: 0.9461 - val_smape: 1.7250

Epoch 4/16

287/287 - 4s - 12ms/step - ia: 0.1466 - loss: 1.0621 - mae: 0.8516 - rmse: 1.0294 - smape: 1.6579 - val_ia: 0.2118 - val_loss: 0.8880 - val_mae: 0.7791 - val_rmse: 0.9367 - val_smape: 1.7482

Epoch 5/16

287/287 - 3s - 12ms/step - ia: 0.1543 - loss: 1.0419 - mae: 0.8435 - rmse: 1.0192 - smape: 1.6482 - val_ia: 0.2130 - val_loss: 0.8715 - val_mae: 0.7724 - val_rmse: 0.9278 - val_smape: 1.7635

Epoch 6/16

287/287 - 4s - 12ms/step - ia: 0.1596 - loss: 1.0276 - mae: 0.8393 - rmse: 1.0125 - smape: 1.6461 - val_ia: 0.2153 - val_loss: 0.8561 - val_mae: 0.7659 - val_rmse: 0.9195 - val_smape: 1.7692

Epoch 7/16

287/287 - 5s - 18ms/step - ia: 0.1675 - loss: 1.0076 - mae: 0.8325 - rmse: 1.0025 - smape: 1.6330 - val_ia: 0.2186 - val_loss: 0.8416 - val_mae: 0.7597 - val_rmse: 0.9116 - val_smape: 1.7675

Epoch 8/16

287/287 - 3s - 12ms/step - ia: 0.1781 - loss: 0.9902 - mae: 0.8256 - rmse: 0.9939 - smape: 1.6162 - val_ia: 0.2228 - val_loss: 0.8282 - val_mae: 0.7538 - val_rmse: 0.9042 - val_smape: 1.7550

Epoch 9/16

287/287 - 3s - 12ms/step - ia: 0.1843 - loss: 0.9750 - mae: 0.8207 - rmse: 0.9863 - smape: 1.6062 - val_ia: 0.2276 - val_loss: 0.8156 - val_mae: 0.7481 - val_rmse: 0.8971 - val_smape: 1.7355

Epoch 10/16

287/287 - 5s - 18ms/step - ia: 0.1950 - loss: 0.9582 - mae: 0.8141 - rmse: 0.9777 - smape: 1.5914 - val_ia: 0.2331 - val_loss: 0.8037 - val_mae: 0.7427 - val_rmse: 0.8904 - val_smape: 1.7093

Epoch 11/16

287/287 - 3s - 12ms/step - ia: 0.2033 - loss: 0.9424 - mae: 0.8087 - rmse: 0.9695 - smape: 1.5804 - val_ia: 0.2390 - val_loss: 0.7925 - val_mae: 0.7374 - val_rmse: 0.8840 - val_smape: 1.6792

Epoch 12/16

287/287 - 5s - 18ms/step - ia: 0.2159 - loss: 0.9286 - mae: 0.8026 - rmse: 0.9622 - smape: 1.5639 - val_ia: 0.2457 - val_loss: 0.7821 - val_mae: 0.7324 - val_rmse: 0.8779 - val_smape: 1.6499

Epoch 13/16

287/287 - 3s - 12ms/step - ia: 0.2249 - loss: 0.9137 - mae: 0.7966 - rmse: 0.9547 - smape: 1.5490 - val_ia: 0.2533 - val_loss: 0.7723 - val_mae: 0.7276 - val_rmse: 0.8721 - val_smape: 1.6224

Epoch 14/16

287/287 - 3s - 12ms/step - ia: 0.2379 - loss: 0.8983 - mae: 0.7901 - rmse: 0.9468 - smape: 1.5279 - val_ia: 0.2611 - val_loss: 0.7632 - val_mae: 0.7232 - val_rmse: 0.8667 - val_smape: 1.5958

Epoch 15/16

287/287 - 3s - 11ms/step - ia: 0.2488 - loss: 0.8816 - mae: 0.7834 - rmse: 0.9378 - smape: 1.5129 - val_ia: 0.2695 - val_loss: 0.7546 - val_mae: 0.7189 - val_rmse: 0.8615 - val_smape: 1.5713

Epoch 16/16

287/287 - 4s - 12ms/step - ia: 0.2603 - loss: 0.8677 - mae: 0.7772 - rmse: 0.9304 - smape: 1.4953 - val_ia: 0.2782 - val_loss: 0.7469 - val_mae: 0.7151 - val_rmse: 0.8567 - val_smape: 1.5480

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:47 666ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 36%|███▌      | 18/50 [2:09:49<4:36:30, 518.44s/trial, best loss: 0.1659520630211836]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 12s - 21ms/step - ia: 0.6352 - loss: 0.4351 - mae: 0.5223 - rmse: 0.6460 - smape: 0.9223 - val_ia: 0.4792 - val_loss: 0.6741 - val_mae: 0.6570 - val_rmse: 0.7450 - val_smape: 1.0674

Epoch 2/16

573/573 - 10s - 17ms/step - ia: 0.7666 - loss: 0.2200 - mae: 0.3627 - rmse: 0.4644 - smape: 0.7254 - val_ia: 0.6060 - val_loss: 0.3569 - val_mae: 0.4767 - val_rmse: 0.5422 - val_smape: 0.8766

Epoch 3/16

573/573 - 6s - 11ms/step - ia: 0.8171 - loss: 0.1428 - mae: 0.2847 - rmse: 0.3748 - smape: 0.6520 - val_ia: 0.6665 - val_loss: 0.1929 - val_mae: 0.3614 - val_rmse: 0.4186 - val_smape: 0.7765

Epoch 4/16

573/573 - 7s - 12ms/step - ia: 0.8385 - loss: 0.1146 - mae: 0.2532 - rmse: 0.3356 - smape: 0.6033 - val_ia: 0.7117 - val_loss: 0.1482 - val_mae: 0.3026 - val_rmse: 0.3522 - val_smape: 0.6757

Epoch 5/16

573/573 - 9s - 16ms/step - ia: 0.8511 - loss: 0.1002 - mae: 0.2346 - rmse: 0.3138 - smape: 0.5693 - val_ia: 0.7022 - val_loss: 0.1651 - val_mae: 0.3205 - val_rmse: 0.3819 - val_smape: 0.7071

Epoch 6/16

573/573 - 6s - 10ms/step - ia: 0.8567 - loss: 0.0933 - mae: 0.2263 - rmse: 0.3029 - smape: 0.5534 - val_ia: 0.6768 - val_loss: 0.2035 - val_mae: 0.3557 - val_rmse: 0.4262 - val_smape: 0.7384

Epoch 7/16

573/573 - 10s - 18ms/step - ia: 0.8603 - loss: 0.0887 - mae: 0.2211 - rmse: 0.2951 - smape: 0.5432 - val_ia: 0.7110 - val_loss: 0.1578 - val_mae: 0.3128 - val_rmse: 0.3657 - val_smape: 0.6830

Epoch 8/16

573/573 - 6s - 10ms/step - ia: 0.8631 - loss: 0.0850 - mae: 0.2169 - rmse: 0.2891 - smape: 0.5349 - val_ia: 0.7241 - val_loss: 0.1436 - val_mae: 0.2941 - val_rmse: 0.3523 - val_smape: 0.6593

Epoch 9/16

573/573 - 5s - 9ms/step - ia: 0.8649 - loss: 0.0825 - mae: 0.2144 - rmse: 0.2850 - smape: 0.5289 - val_ia: 0.7152 - val_loss: 0.1673 - val_mae: 0.3143 - val_rmse: 0.3804 - val_smape: 0.6723

Epoch 10/16

573/573 - 11s - 20ms/step - ia: 0.8708 - loss: 0.0763 - mae: 0.2055 - rmse: 0.2740 - smape: 0.5104 - val_ia: 0.6923 - val_loss: 0.1878 - val_mae: 0.3301 - val_rmse: 0.4006 - val_smape: 0.7059

Epoch 11/16

573/573 - 6s - 11ms/step - ia: 0.8723 - loss: 0.0741 - mae: 0.2034 - rmse: 0.2699 - smape: 0.5070 - val_ia: 0.6992 - val_loss: 0.1786 - val_mae: 0.3236 - val_rmse: 0.3792 - val_smape: 0.6936

Epoch 12/16

573/573 - 11s - 19ms/step - ia: 0.8744 - loss: 0.0719 - mae: 0.2002 - rmse: 0.2658 - smape: 0.5013 - val_ia: 0.6859 - val_loss: 0.1928 - val_mae: 0.3336 - val_rmse: 0.4099 - val_smape: 0.7138

Epoch 13/16

573/573 - 6s - 11ms/step - ia: 0.8766 - loss: 0.0699 - mae: 0.1968 - rmse: 0.2622 - smape: 0.4940 - val_ia: 0.6877 - val_loss: 0.1883 - val_mae: 0.3404 - val_rmse: 0.4007 - val_smape: 0.7114

Epoch 14/16

573/573 - 11s - 19ms/step - ia: 0.8787 - loss: 0.0677 - mae: 0.1938 - rmse: 0.2578 - smape: 0.4899 - val_ia: 0.6931 - val_loss: 0.1988 - val_mae: 0.3386 - val_rmse: 0.4094 - val_smape: 0.7022

Epoch 15/16

573/573 - 6s - 10ms/step - ia: 0.8793 - loss: 0.0676 - mae: 0.1929 - rmse: 0.2575 - smape: 0.4874 - val_ia: 0.6937 - val_loss: 0.1974 - val_mae: 0.3385 - val_rmse: 0.4006 - val_smape: 0.7110

Epoch 16/16

573/573 - 6s - 10ms/step - ia: 0.8819 - loss: 0.0647 - mae: 0.1889 - rmse: 0.2522 - smape: 0.4790 - val_ia: 0.6703 - val_loss: 0.2347 - val_mae: 0.3728 - val_rmse: 0.4363 - val_smape: 0.7493

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 46s 288ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step

 38%|███▊      | 19/50 [2:12:07<3:28:51, 404.23s/trial, best loss: 0.1659520630211836]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 59s - 13ms/step - ia: 0.5080 - loss: 0.5895 - mae: 0.6095 - rmse: 0.7325 - smape: 1.0832 - val_ia: 0.1566 - val_loss: 0.8978 - val_mae: 0.7705 - val_rmse: 0.7882 - val_smape: 1.2111

Epoch 2/32

4584/4584 - 47s - 10ms/step - ia: 0.6506 - loss: 0.3596 - mae: 0.4779 - rmse: 0.5808 - smape: 0.8326 - val_ia: 0.1658 - val_loss: 0.7144 - val_mae: 0.6753 - val_rmse: 0.6956 - val_smape: 1.1152

Epoch 3/32

4584/4584 - 54s - 12ms/step - ia: 0.6735 - loss: 0.3234 - mae: 0.4515 - rmse: 0.5506 - smape: 0.8050 - val_ia: 0.1615 - val_loss: 0.6663 - val_mae: 0.6534 - val_rmse: 0.6735 - val_smape: 1.0663

Epoch 4/32

4584/4584 - 51s - 11ms/step - ia: 0.6844 - loss: 0.3042 - mae: 0.4380 - rmse: 0.5336 - smape: 0.7932 - val_ia: 0.1689 - val_loss: 0.5852 - val_mae: 0.6105 - val_rmse: 0.6294 - val_smape: 1.0375

Epoch 5/32

4584/4584 - 57s - 12ms/step - ia: 0.6959 - loss: 0.2856 - mae: 0.4222 - rmse: 0.5178 - smape: 0.7851 - val_ia: 0.1698 - val_loss: 0.4734 - val_mae: 0.5522 - val_rmse: 0.5700 - val_smape: 1.0034

Epoch 6/32

4584/4584 - 88s - 19ms/step - ia: 0.7088 - loss: 0.2649 - mae: 0.4027 - rmse: 0.4968 - smape: 0.7686 - val_ia: 0.1783 - val_loss: 0.4801 - val_mae: 0.5626 - val_rmse: 0.5792 - val_smape: 1.0017

Epoch 7/32

4584/4584 - 53s - 12ms/step - ia: 0.7228 - loss: 0.2427 - mae: 0.3832 - rmse: 0.4746 - smape: 0.7574 - val_ia: 0.1980 - val_loss: 0.3006 - val_mae: 0.4472 - val_rmse: 0.4627 - val_smape: 0.8772

Epoch 8/32

4584/4584 - 55s - 12ms/step - ia: 0.7339 - loss: 0.2213 - mae: 0.3649 - rmse: 0.4525 - smape: 0.7406 - val_ia: 0.2239 - val_loss: 0.2227 - val_mae: 0.3824 - val_rmse: 0.3976 - val_smape: 0.8076

Epoch 9/32

4584/4584 - 53s - 12ms/step - ia: 0.7443 - loss: 0.2060 - mae: 0.3522 - rmse: 0.4366 - smape: 0.7257 - val_ia: 0.2294 - val_loss: 0.2295 - val_mae: 0.3846 - val_rmse: 0.4001 - val_smape: 0.7823

Epoch 10/32

4584/4584 - 54s - 12ms/step - ia: 0.7527 - loss: 0.1935 - mae: 0.3402 - rmse: 0.4228 - smape: 0.7125 - val_ia: 0.2539 - val_loss: 0.1755 - val_mae: 0.3389 - val_rmse: 0.3534 - val_smape: 0.7294

Epoch 11/32

4584/4584 - 82s - 18ms/step - ia: 0.7560 - loss: 0.1880 - mae: 0.3347 - rmse: 0.4169 - smape: 0.7047 - val_ia: 0.2459 - val_loss: 0.1782 - val_mae: 0.3398 - val_rmse: 0.3533 - val_smape: 0.7336

Epoch 12/32

4584/4584 - 54s - 12ms/step - ia: 0.7593 - loss: 0.1829 - mae: 0.3304 - rmse: 0.4112 - smape: 0.7025 - val_ia: 0.2379 - val_loss: 0.1988 - val_mae: 0.3580 - val_rmse: 0.3719 - val_smape: 0.7519

Epoch 13/32

4584/4584 - 80s - 18ms/step - ia: 0.7639 - loss: 0.1786 - mae: 0.3257 - rmse: 0.4060 - smape: 0.6919 - val_ia: 0.2368 - val_loss: 0.2047 - val_mae: 0.3616 - val_rmse: 0.3758 - val_smape: 0.7599

Epoch 14/32

4584/4584 - 50s - 11ms/step - ia: 0.7659 - loss: 0.1754 - mae: 0.3226 - rmse: 0.4022 - smape: 0.6913 - val_ia: 0.2585 - val_loss: 0.1642 - val_mae: 0.3275 - val_rmse: 0.3412 - val_smape: 0.7232

Epoch 15/32

4584/4584 - 49s - 11ms/step - ia: 0.7667 - loss: 0.1734 - mae: 0.3207 - rmse: 0.4001 - smape: 0.6900 - val_ia: 0.2478 - val_loss: 0.1789 - val_mae: 0.3387 - val_rmse: 0.3527 - val_smape: 0.7355

Epoch 16/32

4584/4584 - 58s - 13ms/step - ia: 0.7710 - loss: 0.1695 - mae: 0.3164 - rmse: 0.3947 - smape: 0.6855 - val_ia: 0.2554 - val_loss: 0.1689 - val_mae: 0.3318 - val_rmse: 0.3461 - val_smape: 0.7265

Epoch 17/32

4584/4584 - 54s - 12ms/step - ia: 0.7728 - loss: 0.1661 - mae: 0.3131 - rmse: 0.3909 - smape: 0.6832 - val_ia: 0.2423 - val_loss: 0.1816 - val_mae: 0.3429 - val_rmse: 0.3578 - val_smape: 0.7456

Epoch 18/32

4584/4584 - 52s - 11ms/step - ia: 0.7734 - loss: 0.1645 - mae: 0.3114 - rmse: 0.3885 - smape: 0.6823 - val_ia: 0.2604 - val_loss: 0.1587 - val_mae: 0.3223 - val_rmse: 0.3364 - val_smape: 0.7233

Epoch 19/32

4584/4584 - 81s - 18ms/step - ia: 0.7778 - loss: 0.1613 - mae: 0.3073 - rmse: 0.3853 - smape: 0.6763 - val_ia: 0.2524 - val_loss: 0.1645 - val_mae: 0.3272 - val_rmse: 0.3417 - val_smape: 0.7324

Epoch 20/32

4584/4584 - 51s - 11ms/step - ia: 0.7771 - loss: 0.1602 - mae: 0.3075 - rmse: 0.3841 - smape: 0.6794 - val_ia: 0.2670 - val_loss: 0.1500 - val_mae: 0.3133 - val_rmse: 0.3267 - val_smape: 0.7224

Epoch 21/32

4584/4584 - 51s - 11ms/step - ia: 0.7796 - loss: 0.1581 - mae: 0.3045 - rmse: 0.3810 - smape: 0.6774 - val_ia: 0.2639 - val_loss: 0.1474 - val_mae: 0.3116 - val_rmse: 0.3254 - val_smape: 0.7234

Epoch 22/32

4584/4584 - 50s - 11ms/step - ia: 0.7809 - loss: 0.1564 - mae: 0.3026 - rmse: 0.3782 - smape: 0.6762 - val_ia: 0.2505 - val_loss: 0.1583 - val_mae: 0.3242 - val_rmse: 0.3396 - val_smape: 0.7597

Epoch 23/32

4584/4584 - 51s - 11ms/step - ia: 0.7841 - loss: 0.1523 - mae: 0.2989 - rmse: 0.3735 - smape: 0.6717 - val_ia: 0.2560 - val_loss: 0.1506 - val_mae: 0.3169 - val_rmse: 0.3321 - val_smape: 0.7587

Epoch 24/32

4584/4584 - 98s - 21ms/step - ia: 0.7862 - loss: 0.1502 - mae: 0.2965 - rmse: 0.3708 - smape: 0.6708 - val_ia: 0.2569 - val_loss: 0.1563 - val_mae: 0.3206 - val_rmse: 0.3356 - val_smape: 0.7161

Epoch 25/32

4584/4584 - 68s - 15ms/step - ia: 0.7877 - loss: 0.1489 - mae: 0.2951 - rmse: 0.3694 - smape: 0.6686 - val_ia: 0.2673 - val_loss: 0.1413 - val_mae: 0.3063 - val_rmse: 0.3197 - val_smape: 0.7276

Epoch 26/32

4584/4584 - 69s - 15ms/step - ia: 0.7893 - loss: 0.1469 - mae: 0.2936 - rmse: 0.3669 - smape: 0.6643 - val_ia: 0.2519 - val_loss: 0.1617 - val_mae: 0.3260 - val_rmse: 0.3417 - val_smape: 0.7771

Epoch 27/32

4584/4584 - 67s - 15ms/step - ia: 0.7906 - loss: 0.1458 - mae: 0.2920 - rmse: 0.3656 - smape: 0.6626 - val_ia: 0.2577 - val_loss: 0.1490 - val_mae: 0.3156 - val_rmse: 0.3304 - val_smape: 0.7596

Epoch 28/32

4584/4584 - 84s - 18ms/step - ia: 0.7913 - loss: 0.1443 - mae: 0.2897 - rmse: 0.3635 - smape: 0.6542 - val_ia: 0.2568 - val_loss: 0.1552 - val_mae: 0.3195 - val_rmse: 0.3348 - val_smape: 0.7637

Epoch 29/32

4584/4584 - 64s - 14ms/step - ia: 0.7939 - loss: 0.1414 - mae: 0.2868 - rmse: 0.3591 - smape: 0.6521 - val_ia: 0.2678 - val_loss: 0.1355 - val_mae: 0.3012 - val_rmse: 0.3149 - val_smape: 0.7298

Epoch 30/32

4584/4584 - 66s - 14ms/step - ia: 0.7946 - loss: 0.1395 - mae: 0.2846 - rmse: 0.3567 - smape: 0.6496 - val_ia: 0.2610 - val_loss: 0.1621 - val_mae: 0.3226 - val_rmse: 0.3366 - val_smape: 0.7165

Epoch 31/32

4584/4584 - 67s - 15ms/step - ia: 0.7970 - loss: 0.1375 - mae: 0.2833 - rmse: 0.3545 - smape: 0.6469 - val_ia: 0.2562 - val_loss: 0.1614 - val_mae: 0.3240 - val_rmse: 0.3400 - val_smape: 0.7752

Epoch 32/32

4584/4584 - 65s - 14ms/step - ia: 0.7960 - loss: 0.1379 - mae: 0.2834 - rmse: 0.3549 - smape: 0.6436 - val_ia: 0.2582 - val_loss: 0.1702 - val_mae: 0.3296 - val_rmse: 0.3446 - val_smape: 0.7559

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 7:52 3s/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step

 40%|████      | 20/50 [2:45:17<7:20:10, 880.35s/trial, best loss: 0.1659520630211836]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 107s - 23ms/step - ia: 0.2118 - loss: 1.0052 - mae: 0.8317 - rmse: 0.9821 - smape: 1.8292 - val_ia: 0.1419 - val_loss: 0.8269 - val_mae: 0.7567 - val_rmse: 0.7747 - val_smape: 1.7057

Epoch 2/256

4584/4584 - 83s - 18ms/step - ia: 0.3884 - loss: 0.7159 - mae: 0.7070 - rmse: 0.8258 - smape: 1.2999 - val_ia: 0.1298 - val_loss: 1.2769 - val_mae: 0.9411 - val_rmse: 0.9564 - val_smape: 1.3513

Epoch 3/256

4584/4584 - 144s - 31ms/step - ia: 0.5578 - loss: 0.5164 - mae: 0.5817 - rmse: 0.6989 - smape: 0.9961 - val_ia: 0.1202 - val_loss: 1.4669 - val_mae: 1.0221 - val_rmse: 1.0368 - val_smape: 1.3947

Epoch 4/256

4584/4584 - 83s - 18ms/step - ia: 0.5841 - loss: 0.4761 - mae: 0.5542 - rmse: 0.6698 - smape: 0.9557 - val_ia: 0.1300 - val_loss: 1.2639 - val_mae: 0.9336 - val_rmse: 0.9497 - val_smape: 1.3492

Epoch 5/256

4584/4584 - 81s - 18ms/step - ia: 0.6063 - loss: 0.4381 - mae: 0.5292 - rmse: 0.6421 - smape: 0.9196 - val_ia: 0.1230 - val_loss: 1.3559 - val_mae: 0.9755 - val_rmse: 0.9912 - val_smape: 1.3720

Epoch 6/256

4584/4584 - 80s - 17ms/step - ia: 0.6273 - loss: 0.4037 - mae: 0.5063 - rmse: 0.6162 - smape: 0.8830 - val_ia: 0.1243 - val_loss: 1.3057 - val_mae: 0.9578 - val_rmse: 0.9739 - val_smape: 1.3598

Epoch 7/256

4584/4584 - 79s - 17ms/step - ia: 0.6437 - loss: 0.3773 - mae: 0.4887 - rmse: 0.5953 - smape: 0.8532 - val_ia: 0.1202 - val_loss: 1.3363 - val_mae: 0.9770 - val_rmse: 0.9928 - val_smape: 1.3763

Epoch 8/256

4584/4584 - 84s - 18ms/step - ia: 0.6518 - loss: 0.3591 - mae: 0.4774 - rmse: 0.5813 - smape: 0.8363 - val_ia: 0.1301 - val_loss: 1.1812 - val_mae: 0.9046 - val_rmse: 0.9218 - val_smape: 1.2881

Epoch 9/256

4584/4584 - 72s - 16ms/step - ia: 0.6615 - loss: 0.3465 - mae: 0.4686 - rmse: 0.5704 - smape: 0.8201 - val_ia: 0.1430 - val_loss: 0.9957 - val_mae: 0.8179 - val_rmse: 0.8368 - val_smape: 1.2150

Epoch 10/256

4584/4584 - 78s - 17ms/step - ia: 0.6659 - loss: 0.3369 - mae: 0.4616 - rmse: 0.5628 - smape: 0.8104 - val_ia: 0.1428 - val_loss: 1.0352 - val_mae: 0.8342 - val_rmse: 0.8531 - val_smape: 1.2121

Epoch 11/256

4584/4584 - 80s - 17ms/step - ia: 0.6714 - loss: 0.3289 - mae: 0.4556 - rmse: 0.5557 - smape: 0.8013 - val_ia: 0.1456 - val_loss: 0.9572 - val_mae: 0.8044 - val_rmse: 0.8234 - val_smape: 1.2076

Epoch 12/256

4584/4584 - 76s - 17ms/step - ia: 0.6750 - loss: 0.3224 - mae: 0.4507 - rmse: 0.5500 - smape: 0.7950 - val_ia: 0.1515 - val_loss: 0.8837 - val_mae: 0.7656 - val_rmse: 0.7855 - val_smape: 1.1764

Epoch 13/256

4584/4584 - 80s - 17ms/step - ia: 0.6797 - loss: 0.3158 - mae: 0.4457 - rmse: 0.5442 - smape: 0.7899 - val_ia: 0.1465 - val_loss: 0.9346 - val_mae: 0.7971 - val_rmse: 0.8160 - val_smape: 1.2013

Epoch 14/256

4584/4584 - 78s - 17ms/step - ia: 0.6832 - loss: 0.3096 - mae: 0.4406 - rmse: 0.5381 - smape: 0.7831 - val_ia: 0.1565 - val_loss: 0.7827 - val_mae: 0.7182 - val_rmse: 0.7386 - val_smape: 1.1524

Epoch 15/256

4584/4584 - 84s - 18ms/step - ia: 0.6874 - loss: 0.3042 - mae: 0.4362 - rmse: 0.5338 - smape: 0.7776 - val_ia: 0.1558 - val_loss: 0.8038 - val_mae: 0.7282 - val_rmse: 0.7485 - val_smape: 1.1506

Epoch 16/256

4584/4584 - 78s - 17ms/step - ia: 0.6896 - loss: 0.2988 - mae: 0.4324 - rmse: 0.5289 - smape: 0.7744 - val_ia: 0.1551 - val_loss: 0.8427 - val_mae: 0.7449 - val_rmse: 0.7652 - val_smape: 1.1542

Epoch 17/256

4584/4584 - 85s - 19ms/step - ia: 0.6931 - loss: 0.2944 - mae: 0.4286 - rmse: 0.5250 - smape: 0.7703 - val_ia: 0.1577 - val_loss: 0.7599 - val_mae: 0.7082 - val_rmse: 0.7286 - val_smape: 1.1405

Epoch 18/256

4584/4584 - 80s - 18ms/step - ia: 0.6961 - loss: 0.2896 - mae: 0.4247 - rmse: 0.5208 - smape: 0.7657 - val_ia: 0.1611 - val_loss: 0.6395 - val_mae: 0.6497 - val_rmse: 0.6711 - val_smape: 1.0963

Epoch 19/256

4584/4584 - 80s - 17ms/step - ia: 0.6992 - loss: 0.2854 - mae: 0.4212 - rmse: 0.5166 - smape: 0.7618 - val_ia: 0.1618 - val_loss: 0.6364 - val_mae: 0.6486 - val_rmse: 0.6694 - val_smape: 1.1017

Epoch 20/256

4584/4584 - 82s - 18ms/step - ia: 0.7019 - loss: 0.2811 - mae: 0.4176 - rmse: 0.5126 - smape: 0.7583 - val_ia: 0.1619 - val_loss: 0.6314 - val_mae: 0.6462 - val_rmse: 0.6668 - val_smape: 1.0998

Epoch 21/256

4584/4584 - 83s - 18ms/step - ia: 0.7047 - loss: 0.2772 - mae: 0.4142 - rmse: 0.5086 - smape: 0.7537 - val_ia: 0.1584 - val_loss: 0.6630 - val_mae: 0.6625 - val_rmse: 0.6831 - val_smape: 1.1054

Epoch 22/256

4584/4584 - 80s - 17ms/step - ia: 0.7065 - loss: 0.2736 - mae: 0.4109 - rmse: 0.5058 - smape: 0.7508 - val_ia: 0.1597 - val_loss: 0.6491 - val_mae: 0.6556 - val_rmse: 0.6760 - val_smape: 1.1031

Epoch 23/256

4584/4584 - 70s - 15ms/step - ia: 0.7094 - loss: 0.2700 - mae: 0.4078 - rmse: 0.5018 - smape: 0.7477 - val_ia: 0.1587 - val_loss: 0.6737 - val_mae: 0.6680 - val_rmse: 0.6878 - val_smape: 1.1093

Epoch 24/256

4584/4584 - 91s - 20ms/step - ia: 0.7101 - loss: 0.2663 - mae: 0.4046 - rmse: 0.4981 - smape: 0.7456 - val_ia: 0.1628 - val_loss: 0.5872 - val_mae: 0.6256 - val_rmse: 0.6454 - val_smape: 1.0788

Epoch 25/256

4584/4584 - 82s - 18ms/step - ia: 0.7134 - loss: 0.2625 - mae: 0.4009 - rmse: 0.4942 - smape: 0.7417 - val_ia: 0.1599 - val_loss: 0.6430 - val_mae: 0.6537 - val_rmse: 0.6730 - val_smape: 1.0986

Epoch 26/256

4584/4584 - 82s - 18ms/step - ia: 0.7171 - loss: 0.2588 - mae: 0.3979 - rmse: 0.4910 - smape: 0.7395 - val_ia: 0.1620 - val_loss: 0.5797 - val_mae: 0.6236 - val_rmse: 0.6424 - val_smape: 1.0691

Epoch 27/256

4584/4584 - 82s - 18ms/step - ia: 0.7193 - loss: 0.2547 - mae: 0.3939 - rmse: 0.4865 - smape: 0.7348 - val_ia: 0.1621 - val_loss: 0.5403 - val_mae: 0.6023 - val_rmse: 0.6217 - val_smape: 1.0597

Epoch 28/256

4584/4584 - 82s - 18ms/step - ia: 0.7212 - loss: 0.2510 - mae: 0.3908 - rmse: 0.4829 - smape: 0.7340 - val_ia: 0.1628 - val_loss: 0.5243 - val_mae: 0.5950 - val_rmse: 0.6137 - val_smape: 1.0441

Epoch 29/256

4584/4584 - 81s - 18ms/step - ia: 0.7248 - loss: 0.2465 - mae: 0.3864 - rmse: 0.4785 - smape: 0.7291 - val_ia: 0.1633 - val_loss: 0.5877 - val_mae: 0.6283 - val_rmse: 0.6456 - val_smape: 1.0617

Epoch 30/256

4584/4584 - 82s - 18ms/step - ia: 0.7278 - loss: 0.2421 - mae: 0.3826 - rmse: 0.4739 - smape: 0.7264 - val_ia: 0.1653 - val_loss: 0.5282 - val_mae: 0.5968 - val_rmse: 0.6141 - val_smape: 1.0373

Epoch 31/256

4584/4584 - 81s - 18ms/step - ia: 0.7302 - loss: 0.2369 - mae: 0.3779 - rmse: 0.4683 - smape: 0.7227 - val_ia: 0.1615 - val_loss: 0.5466 - val_mae: 0.6067 - val_rmse: 0.6242 - val_smape: 1.0381

Epoch 32/256

4584/4584 - 77s - 17ms/step - ia: 0.7344 - loss: 0.2308 - mae: 0.3726 - rmse: 0.4619 - smape: 0.7178 - val_ia: 0.1673 - val_loss: 0.4838 - val_mae: 0.5720 - val_rmse: 0.5889 - val_smape: 1.0049

Epoch 33/256

4584/4584 - 66s - 14ms/step - ia: 0.7386 - loss: 0.2236 - mae: 0.3658 - rmse: 0.4548 - smape: 0.7131 - val_ia: 0.1672 - val_loss: 0.4839 - val_mae: 0.5709 - val_rmse: 0.5876 - val_smape: 0.9967

Epoch 34/256

4584/4584 - 71s - 16ms/step - ia: 0.7440 - loss: 0.2158 - mae: 0.3586 - rmse: 0.4461 - smape: 0.7085 - val_ia: 0.1698 - val_loss: 0.4998 - val_mae: 0.5784 - val_rmse: 0.5944 - val_smape: 0.9864

Epoch 35/256

4584/4584 - 72s - 16ms/step - ia: 0.7483 - loss: 0.2082 - mae: 0.3515 - rmse: 0.4373 - smape: 0.7039 - val_ia: 0.1682 - val_loss: 0.4891 - val_mae: 0.5704 - val_rmse: 0.5874 - val_smape: 0.9820

Epoch 36/256

4584/4584 - 69s - 15ms/step - ia: 0.7549 - loss: 0.2000 - mae: 0.3434 - rmse: 0.4288 - smape: 0.6972 - val_ia: 0.1766 - val_loss: 0.4586 - val_mae: 0.5513 - val_rmse: 0.5680 - val_smape: 0.9564

Epoch 37/256

4584/4584 - 71s - 15ms/step - ia: 0.7596 - loss: 0.1915 - mae: 0.3349 - rmse: 0.4188 - smape: 0.6896 - val_ia: 0.1815 - val_loss: 0.4812 - val_mae: 0.5601 - val_rmse: 0.5770 - val_smape: 0.9471

Epoch 38/256

4584/4584 - 61s - 13ms/step - ia: 0.7682 - loss: 0.1824 - mae: 0.3254 - rmse: 0.4075 - smape: 0.6797 - val_ia: 0.1864 - val_loss: 0.4818 - val_mae: 0.5573 - val_rmse: 0.5744 - val_smape: 0.9343

Epoch 39/256

4584/4584 - 94s - 21ms/step - ia: 0.7734 - loss: 0.1734 - mae: 0.3165 - rmse: 0.3972 - smape: 0.6721 - val_ia: 0.1901 - val_loss: 0.4809 - val_mae: 0.5542 - val_rmse: 0.5713 - val_smape: 0.9248

Epoch 40/256

4584/4584 - 74s - 16ms/step - ia: 0.7816 - loss: 0.1642 - mae: 0.3067 - rmse: 0.3860 - smape: 0.6612 - val_ia: 0.1927 - val_loss: 0.4205 - val_mae: 0.5187 - val_rmse: 0.5359 - val_smape: 0.9098

Epoch 41/256

4584/4584 - 69s - 15ms/step - ia: 0.7856 - loss: 0.1555 - mae: 0.2973 - rmse: 0.3754 - smape: 0.6528 - val_ia: 0.1970 - val_loss: 0.4525 - val_mae: 0.5339 - val_rmse: 0.5505 - val_smape: 0.8991

Epoch 42/256

4584/4584 - 86s - 19ms/step - ia: 0.7921 - loss: 0.1475 - mae: 0.2890 - rmse: 0.3646 - smape: 0.6452 - val_ia: 0.2046 - val_loss: 0.3039 - val_mae: 0.4483 - val_rmse: 0.4653 - val_smape: 0.8836

Epoch 43/256

4584/4584 - 71s - 15ms/step - ia: 0.7974 - loss: 0.1401 - mae: 0.2807 - rmse: 0.3552 - smape: 0.6343 - val_ia: 0.2073 - val_loss: 0.3405 - val_mae: 0.4651 - val_rmse: 0.4821 - val_smape: 0.8628

Epoch 44/256

4584/4584 - 71s - 15ms/step - ia: 0.8044 - loss: 0.1335 - mae: 0.2739 - rmse: 0.3465 - smape: 0.6270 - val_ia: 0.2189 - val_loss: 0.3112 - val_mae: 0.4433 - val_rmse: 0.4603 - val_smape: 0.8404

Epoch 45/256

4584/4584 - 70s - 15ms/step - ia: 0.8079 - loss: 0.1278 - mae: 0.2669 - rmse: 0.3385 - smape: 0.6171 - val_ia: 0.2226 - val_loss: 0.2695 - val_mae: 0.4170 - val_rmse: 0.4341 - val_smape: 0.8326

Epoch 46/256

4584/4584 - 78s - 17ms/step - ia: 0.8132 - loss: 0.1230 - mae: 0.2615 - rmse: 0.3317 - smape: 0.6098 - val_ia: 0.2219 - val_loss: 0.3028 - val_mae: 0.4348 - val_rmse: 0.4512 - val_smape: 0.8248

Epoch 47/256

4584/4584 - 70s - 15ms/step - ia: 0.8162 - loss: 0.1191 - mae: 0.2566 - rmse: 0.3261 - smape: 0.6037 - val_ia: 0.2250 - val_loss: 0.3012 - val_mae: 0.4336 - val_rmse: 0.4500 - val_smape: 0.8223

Epoch 48/256

4584/4584 - 72s - 16ms/step - ia: 0.8194 - loss: 0.1155 - mae: 0.2519 - rmse: 0.3205 - smape: 0.5968 - val_ia: 0.2370 - val_loss: 0.2140 - val_mae: 0.3743 - val_rmse: 0.3916 - val_smape: 0.8014

Epoch 49/256

4584/4584 - 67s - 15ms/step - ia: 0.8226 - loss: 0.1125 - mae: 0.2479 - rmse: 0.3160 - smape: 0.5911 - val_ia: 0.2398 - val_loss: 0.2091 - val_mae: 0.3689 - val_rmse: 0.3860 - val_smape: 0.7923

Epoch 50/256

4584/4584 - 75s - 16ms/step - ia: 0.8248 - loss: 0.1100 - mae: 0.2449 - rmse: 0.3122 - smape: 0.5854 - val_ia: 0.2447 - val_loss: 0.2301 - val_mae: 0.3788 - val_rmse: 0.3958 - val_smape: 0.7654

Epoch 51/256

4584/4584 - 65s - 14ms/step - ia: 0.8277 - loss: 0.1080 - mae: 0.2418 - rmse: 0.3092 - smape: 0.5814 - val_ia: 0.2446 - val_loss: 0.2014 - val_mae: 0.3591 - val_rmse: 0.3759 - val_smape: 0.7576

Epoch 52/256

4584/4584 - 69s - 15ms/step - ia: 0.8285 - loss: 0.1064 - mae: 0.2398 - rmse: 0.3065 - smape: 0.5770 - val_ia: 0.2502 - val_loss: 0.2133 - val_mae: 0.3655 - val_rmse: 0.3822 - val_smape: 0.7478

Epoch 53/256

4584/4584 - 61s - 13ms/step - ia: 0.8300 - loss: 0.1051 - mae: 0.2376 - rmse: 0.3045 - smape: 0.5735 - val_ia: 0.2399 - val_loss: 0.2467 - val_mae: 0.3929 - val_rmse: 0.4084 - val_smape: 0.7800

Epoch 54/256

4584/4584 - 59s - 13ms/step - ia: 0.8315 - loss: 0.1040 - mae: 0.2361 - rmse: 0.3031 - smape: 0.5699 - val_ia: 0.2497 - val_loss: 0.2085 - val_mae: 0.3611 - val_rmse: 0.3777 - val_smape: 0.7393

Epoch 55/256

4584/4584 - 73s - 16ms/step - ia: 0.8325 - loss: 0.1028 - mae: 0.2348 - rmse: 0.3012 - smape: 0.5700 - val_ia: 0.2534 - val_loss: 0.1963 - val_mae: 0.3499 - val_rmse: 0.3666 - val_smape: 0.7285

Epoch 56/256

4584/4584 - 72s - 16ms/step - ia: 0.8327 - loss: 0.1019 - mae: 0.2334 - rmse: 0.2999 - smape: 0.5675 - val_ia: 0.2515 - val_loss: 0.2004 - val_mae: 0.3536 - val_rmse: 0.3691 - val_smape: 0.7278

Epoch 57/256

4584/4584 - 69s - 15ms/step - ia: 0.8342 - loss: 0.1009 - mae: 0.2322 - rmse: 0.2985 - smape: 0.5652 - val_ia: 0.2498 - val_loss: 0.2090 - val_mae: 0.3622 - val_rmse: 0.3776 - val_smape: 0.7395

Epoch 58/256

4584/4584 - 69s - 15ms/step - ia: 0.8347 - loss: 0.1001 - mae: 0.2313 - rmse: 0.2972 - smape: 0.5649 - val_ia: 0.2571 - val_loss: 0.1911 - val_mae: 0.3460 - val_rmse: 0.3609 - val_smape: 0.7211

Epoch 59/256

4584/4584 - 71s - 16ms/step - ia: 0.8357 - loss: 0.0992 - mae: 0.2301 - rmse: 0.2956 - smape: 0.5629 - val_ia: 0.2546 - val_loss: 0.1744 - val_mae: 0.3326 - val_rmse: 0.3485 - val_smape: 0.7048

Epoch 60/256

4584/4584 - 83s - 18ms/step - ia: 0.8366 - loss: 0.0986 - mae: 0.2295 - rmse: 0.2953 - smape: 0.5609 - val_ia: 0.2594 - val_loss: 0.1623 - val_mae: 0.3221 - val_rmse: 0.3375 - val_smape: 0.6917

Epoch 61/256

4584/4584 - 68s - 15ms/step - ia: 0.8369 - loss: 0.0979 - mae: 0.2283 - rmse: 0.2938 - smape: 0.5590 - val_ia: 0.2636 - val_loss: 0.1795 - val_mae: 0.3362 - val_rmse: 0.3516 - val_smape: 0.7037

Epoch 62/256

4584/4584 - 61s - 13ms/step - ia: 0.8376 - loss: 0.0970 - mae: 0.2273 - rmse: 0.2919 - smape: 0.5572 - val_ia: 0.2616 - val_loss: 0.1655 - val_mae: 0.3237 - val_rmse: 0.3381 - val_smape: 0.6946

Epoch 63/256

4584/4584 - 57s - 12ms/step - ia: 0.8385 - loss: 0.0963 - mae: 0.2267 - rmse: 0.2914 - smape: 0.5588 - val_ia: 0.2534 - val_loss: 0.1927 - val_mae: 0.3500 - val_rmse: 0.3645 - val_smape: 0.7279

Epoch 64/256

4584/4584 - 94s - 20ms/step - ia: 0.8386 - loss: 0.0961 - mae: 0.2265 - rmse: 0.2910 - smape: 0.5558 - val_ia: 0.2534 - val_loss: 0.1902 - val_mae: 0.3472 - val_rmse: 0.3617 - val_smape: 0.7208

Epoch 65/256

4584/4584 - 82s - 18ms/step - ia: 0.8395 - loss: 0.0947 - mae: 0.2246 - rmse: 0.2893 - smape: 0.5543 - val_ia: 0.2651 - val_loss: 0.1666 - val_mae: 0.3237 - val_rmse: 0.3387 - val_smape: 0.6877

Epoch 66/256

4584/4584 - 48s - 11ms/step - ia: 0.8408 - loss: 0.0938 - mae: 0.2236 - rmse: 0.2876 - smape: 0.5526 - val_ia: 0.2643 - val_loss: 0.1728 - val_mae: 0.3291 - val_rmse: 0.3438 - val_smape: 0.6957

Epoch 67/256

4584/4584 - 104s - 23ms/step - ia: 0.8406 - loss: 0.0934 - mae: 0.2232 - rmse: 0.2873 - smape: 0.5531 - val_ia: 0.2742 - val_loss: 0.1554 - val_mae: 0.3119 - val_rmse: 0.3263 - val_smape: 0.6758

Epoch 68/256

4584/4584 - 68s - 15ms/step - ia: 0.8408 - loss: 0.0929 - mae: 0.2227 - rmse: 0.2865 - smape: 0.5514 - val_ia: 0.2759 - val_loss: 0.1579 - val_mae: 0.3134 - val_rmse: 0.3285 - val_smape: 0.6738

Epoch 69/256

4584/4584 - 70s - 15ms/step - ia: 0.8414 - loss: 0.0921 - mae: 0.2216 - rmse: 0.2851 - smape: 0.5498 - val_ia: 0.2686 - val_loss: 0.1656 - val_mae: 0.3222 - val_rmse: 0.3374 - val_smape: 0.6866

Epoch 70/256

4584/4584 - 82s - 18ms/step - ia: 0.8433 - loss: 0.0913 - mae: 0.2207 - rmse: 0.2842 - smape: 0.5475 - val_ia: 0.2651 - val_loss: 0.1696 - val_mae: 0.3270 - val_rmse: 0.3416 - val_smape: 0.6963

Epoch 71/256

4584/4584 - 69s - 15ms/step - ia: 0.8426 - loss: 0.0910 - mae: 0.2207 - rmse: 0.2837 - smape: 0.5486 - val_ia: 0.2713 - val_loss: 0.1599 - val_mae: 0.3156 - val_rmse: 0.3307 - val_smape: 0.6768

Epoch 72/256

4584/4584 - 82s - 18ms/step - ia: 0.8439 - loss: 0.0901 - mae: 0.2197 - rmse: 0.2822 - smape: 0.5466 - val_ia: 0.2788 - val_loss: 0.1524 - val_mae: 0.3088 - val_rmse: 0.3232 - val_smape: 0.6732

Epoch 73/256

4584/4584 - 82s - 18ms/step - ia: 0.8439 - loss: 0.0896 - mae: 0.2188 - rmse: 0.2810 - smape: 0.5446 - val_ia: 0.2472 - val_loss: 0.2012 - val_mae: 0.3583 - val_rmse: 0.3730 - val_smape: 0.7339

Epoch 74/256

4584/4584 - 83s - 18ms/step - ia: 0.8440 - loss: 0.0894 - mae: 0.2187 - rmse: 0.2812 - smape: 0.5444 - val_ia: 0.2677 - val_loss: 0.1717 - val_mae: 0.3268 - val_rmse: 0.3418 - val_smape: 0.6943

Epoch 75/256

4584/4584 - 81s - 18ms/step - ia: 0.8442 - loss: 0.0889 - mae: 0.2182 - rmse: 0.2803 - smape: 0.5436 - val_ia: 0.2724 - val_loss: 0.1620 - val_mae: 0.3181 - val_rmse: 0.3333 - val_smape: 0.6829

Epoch 76/256

4584/4584 - 68s - 15ms/step - ia: 0.8436 - loss: 0.0890 - mae: 0.2183 - rmse: 0.2806 - smape: 0.5443 - val_ia: 0.2868 - val_loss: 0.1413 - val_mae: 0.2954 - val_rmse: 0.3104 - val_smape: 0.6442

Epoch 77/256

4584/4584 - 71s - 15ms/step - ia: 0.8458 - loss: 0.0878 - mae: 0.2169 - rmse: 0.2789 - smape: 0.5392 - val_ia: 0.2920 - val_loss: 0.1257 - val_mae: 0.2791 - val_rmse: 0.2943 - val_smape: 0.6145

Epoch 78/256

4584/4584 - 70s - 15ms/step - ia: 0.8463 - loss: 0.0876 - mae: 0.2162 - rmse: 0.2785 - smape: 0.5382 - val_ia: 0.2676 - val_loss: 0.1680 - val_mae: 0.3230 - val_rmse: 0.3379 - val_smape: 0.6880

Epoch 79/256

4584/4584 - 80s - 18ms/step - ia: 0.8451 - loss: 0.0873 - mae: 0.2164 - rmse: 0.2779 - smape: 0.5390 - val_ia: 0.2853 - val_loss: 0.1378 - val_mae: 0.2906 - val_rmse: 0.3058 - val_smape: 0.6296

Epoch 80/256

4584/4584 - 70s - 15ms/step - ia: 0.8459 - loss: 0.0865 - mae: 0.2148 - rmse: 0.2768 - smape: 0.5370 - val_ia: 0.2549 - val_loss: 0.1835 - val_mae: 0.3439 - val_rmse: 0.3585 - val_smape: 0.7217

Epoch 81/256

4584/4584 - 70s - 15ms/step - ia: 0.8473 - loss: 0.0861 - mae: 0.2150 - rmse: 0.2761 - smape: 0.5361 - val_ia: 0.2830 - val_loss: 0.1450 - val_mae: 0.2994 - val_rmse: 0.3149 - val_smape: 0.6536

Epoch 82/256

4584/4584 - 81s - 18ms/step - ia: 0.8471 - loss: 0.0857 - mae: 0.2144 - rmse: 0.2755 - smape: 0.5348 - val_ia: 0.2800 - val_loss: 0.1513 - val_mae: 0.3080 - val_rmse: 0.3229 - val_smape: 0.6740

Epoch 83/256

4584/4584 - 69s - 15ms/step - ia: 0.8480 - loss: 0.0854 - mae: 0.2138 - rmse: 0.2750 - smape: 0.5340 - val_ia: 0.2711 - val_loss: 0.1655 - val_mae: 0.3224 - val_rmse: 0.3371 - val_smape: 0.6874

Epoch 84/256

4584/4584 - 71s - 15ms/step - ia: 0.8483 - loss: 0.0851 - mae: 0.2137 - rmse: 0.2747 - smape: 0.5339 - val_ia: 0.2726 - val_loss: 0.1650 - val_mae: 0.3191 - val_rmse: 0.3345 - val_smape: 0.6839

Epoch 85/256

4584/4584 - 92s - 20ms/step - ia: 0.8472 - loss: 0.0849 - mae: 0.2136 - rmse: 0.2745 - smape: 0.5351 - val_ia: 0.2981 - val_loss: 0.1273 - val_mae: 0.2789 - val_rmse: 0.2946 - val_smape: 0.6135

Epoch 86/256

4584/4584 - 65s - 14ms/step - ia: 0.8488 - loss: 0.0842 - mae: 0.2125 - rmse: 0.2732 - smape: 0.5321 - val_ia: 0.2802 - val_loss: 0.1542 - val_mae: 0.3068 - val_rmse: 0.3226 - val_smape: 0.6614

Epoch 87/256

4584/4584 - 59s - 13ms/step - ia: 0.8486 - loss: 0.0840 - mae: 0.2123 - rmse: 0.2726 - smape: 0.5322 - val_ia: 0.2778 - val_loss: 0.1550 - val_mae: 0.3110 - val_rmse: 0.3264 - val_smape: 0.6744

Epoch 88/256

4584/4584 - 111s - 24ms/step - ia: 0.8493 - loss: 0.0834 - mae: 0.2114 - rmse: 0.2719 - smape: 0.5291 - val_ia: 0.2881 - val_loss: 0.1410 - val_mae: 0.2948 - val_rmse: 0.3098 - val_smape: 0.6502

Epoch 89/256

4584/4584 - 117s - 26ms/step - ia: 0.8496 - loss: 0.0830 - mae: 0.2110 - rmse: 0.2714 - smape: 0.5289 - val_ia: 0.2908 - val_loss: 0.1378 - val_mae: 0.2899 - val_rmse: 0.3055 - val_smape: 0.6367

Epoch 90/256

4584/4584 - 84s - 18ms/step - ia: 0.8496 - loss: 0.0832 - mae: 0.2117 - rmse: 0.2718 - smape: 0.5303 - val_ia: 0.2807 - val_loss: 0.1532 - val_mae: 0.3076 - val_rmse: 0.3232 - val_smape: 0.6687

Epoch 91/256

4584/4584 - 83s - 18ms/step - ia: 0.8504 - loss: 0.0824 - mae: 0.2103 - rmse: 0.2707 - smape: 0.5275 - val_ia: 0.2816 - val_loss: 0.1516 - val_mae: 0.3053 - val_rmse: 0.3208 - val_smape: 0.6641

Epoch 92/256

4584/4584 - 71s - 15ms/step - ia: 0.8510 - loss: 0.0820 - mae: 0.2101 - rmse: 0.2698 - smape: 0.5278 - val_ia: 0.2753 - val_loss: 0.1583 - val_mae: 0.3157 - val_rmse: 0.3309 - val_smape: 0.6825

Epoch 92: early stopping

Restoring model weights from the end of the best epoch: 77.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:35 2s/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 12s 77ms/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 111s - 24ms/step - ia: 0.2084 - loss: 0.9890 - mae: 0.8265 - rmse: 0.9756 - smape: 1.8509 - val_ia: 0.1410 - val_loss: 0.8358 - val_mae: 0.7589 - val_rmse: 0.7769 - val_smape: 1.6069

Epoch 2/256

4584/4584 - 80s - 17ms/step - ia: 0.3910 - loss: 0.7166 - mae: 0.7092 - rmse: 0.8273 - smape: 1.2879 - val_ia: 0.1362 - val_loss: 1.1759 - val_mae: 0.8940 - val_rmse: 0.9098 - val_smape: 1.3208

Epoch 3/256

4584/4584 - 75s - 16ms/step - ia: 0.5512 - loss: 0.5247 - mae: 0.5868 - rmse: 0.7044 - smape: 1.0096 - val_ia: 0.1278 - val_loss: 1.3334 - val_mae: 0.9651 - val_rmse: 0.9804 - val_smape: 1.3621

Epoch 4/256

4584/4584 - 79s - 17ms/step - ia: 0.5778 - loss: 0.4847 - mae: 0.5595 - rmse: 0.6767 - smape: 0.9664 - val_ia: 0.1282 - val_loss: 1.3012 - val_mae: 0.9482 - val_rmse: 0.9639 - val_smape: 1.3446

Epoch 5/256

4584/4584 - 64s - 14ms/step - ia: 0.5998 - loss: 0.4464 - mae: 0.5347 - rmse: 0.6482 - smape: 0.9293 - val_ia: 0.1119 - val_loss: 1.5617 - val_mae: 1.0661 - val_rmse: 1.0802 - val_smape: 1.4220

Epoch 6/256

4584/4584 - 70s - 15ms/step - ia: 0.6232 - loss: 0.4095 - mae: 0.5102 - rmse: 0.6204 - smape: 0.8895 - val_ia: 0.1294 - val_loss: 1.2483 - val_mae: 0.9302 - val_rmse: 0.9465 - val_smape: 1.3211

Epoch 7/256

4584/4584 - 72s - 16ms/step - ia: 0.6410 - loss: 0.3789 - mae: 0.4894 - rmse: 0.5963 - smape: 0.8557 - val_ia: 0.1289 - val_loss: 1.2492 - val_mae: 0.9291 - val_rmse: 0.9459 - val_smape: 1.2935

Epoch 8/256

4584/4584 - 72s - 16ms/step - ia: 0.6538 - loss: 0.3601 - mae: 0.4768 - rmse: 0.5810 - smape: 0.8344 - val_ia: 0.1250 - val_loss: 1.2934 - val_mae: 0.9538 - val_rmse: 0.9702 - val_smape: 1.3174

Epoch 9/256

4584/4584 - 61s - 13ms/step - ia: 0.6605 - loss: 0.3472 - mae: 0.4683 - rmse: 0.5702 - smape: 0.8202 - val_ia: 0.1398 - val_loss: 1.1100 - val_mae: 0.8663 - val_rmse: 0.8847 - val_smape: 1.2321

Epoch 10/256

4584/4584 - 71s - 15ms/step - ia: 0.6655 - loss: 0.3390 - mae: 0.4626 - rmse: 0.5644 - smape: 0.8125 - val_ia: 0.1425 - val_loss: 1.0400 - val_mae: 0.8410 - val_rmse: 0.8595 - val_smape: 1.2257

Epoch 11/256

4584/4584 - 71s - 16ms/step - ia: 0.6700 - loss: 0.3318 - mae: 0.4576 - rmse: 0.5581 - smape: 0.8036 - val_ia: 0.1524 - val_loss: 0.9359 - val_mae: 0.7859 - val_rmse: 0.8058 - val_smape: 1.1786

Epoch 12/256

4584/4584 - 65s - 14ms/step - ia: 0.6736 - loss: 0.3255 - mae: 0.4528 - rmse: 0.5532 - smape: 0.7978 - val_ia: 0.1501 - val_loss: 0.9628 - val_mae: 0.8024 - val_rmse: 0.8217 - val_smape: 1.1892

Epoch 13/256

4584/4584 - 70s - 15ms/step - ia: 0.6765 - loss: 0.3199 - mae: 0.4486 - rmse: 0.5483 - smape: 0.7920 - val_ia: 0.1553 - val_loss: 0.8627 - val_mae: 0.7522 - val_rmse: 0.7726 - val_smape: 1.1584

Epoch 14/256

4584/4584 - 83s - 18ms/step - ia: 0.6820 - loss: 0.3141 - mae: 0.4441 - rmse: 0.5424 - smape: 0.7869 - val_ia: 0.1538 - val_loss: 0.9075 - val_mae: 0.7746 - val_rmse: 0.7944 - val_smape: 1.1660

Epoch 15/256

4584/4584 - 94s - 20ms/step - ia: 0.6841 - loss: 0.3088 - mae: 0.4400 - rmse: 0.5379 - smape: 0.7815 - val_ia: 0.1587 - val_loss: 0.7481 - val_mae: 0.6977 - val_rmse: 0.7195 - val_smape: 1.1301

Epoch 16/256

4584/4584 - 85s - 19ms/step - ia: 0.6875 - loss: 0.3039 - mae: 0.4362 - rmse: 0.5340 - smape: 0.7780 - val_ia: 0.1583 - val_loss: 0.7668 - val_mae: 0.7079 - val_rmse: 0.7291 - val_smape: 1.1377

Epoch 17/256

4584/4584 - 135s - 30ms/step - ia: 0.6896 - loss: 0.2991 - mae: 0.4323 - rmse: 0.5294 - smape: 0.7731 - val_ia: 0.1587 - val_loss: 0.7633 - val_mae: 0.7081 - val_rmse: 0.7289 - val_smape: 1.1380

Epoch 18/256

4584/4584 - 72s - 16ms/step - ia: 0.6934 - loss: 0.2946 - mae: 0.4287 - rmse: 0.5254 - smape: 0.7696 - val_ia: 0.1566 - val_loss: 0.6803 - val_mae: 0.6688 - val_rmse: 0.6909 - val_smape: 1.1074

Epoch 19/256

4584/4584 - 75s - 16ms/step - ia: 0.6967 - loss: 0.2903 - mae: 0.4251 - rmse: 0.5218 - smape: 0.7648 - val_ia: 0.1566 - val_loss: 0.7548 - val_mae: 0.7036 - val_rmse: 0.7249 - val_smape: 1.1299

Epoch 20/256

4584/4584 - 78s - 17ms/step - ia: 0.6980 - loss: 0.2860 - mae: 0.4215 - rmse: 0.5175 - smape: 0.7609 - val_ia: 0.1580 - val_loss: 0.6659 - val_mae: 0.6623 - val_rmse: 0.6840 - val_smape: 1.1054

Epoch 21/256

4584/4584 - 75s - 16ms/step - ia: 0.7007 - loss: 0.2825 - mae: 0.4182 - rmse: 0.5144 - smape: 0.7584 - val_ia: 0.1540 - val_loss: 0.7141 - val_mae: 0.6842 - val_rmse: 0.7061 - val_smape: 1.1141

Epoch 22/256

4584/4584 - 72s - 16ms/step - ia: 0.7035 - loss: 0.2788 - mae: 0.4150 - rmse: 0.5106 - smape: 0.7542 - val_ia: 0.1569 - val_loss: 0.7311 - val_mae: 0.6908 - val_rmse: 0.7121 - val_smape: 1.1218

Epoch 23/256

4584/4584 - 69s - 15ms/step - ia: 0.7063 - loss: 0.2753 - mae: 0.4120 - rmse: 0.5069 - smape: 0.7514 - val_ia: 0.1592 - val_loss: 0.6759 - val_mae: 0.6648 - val_rmse: 0.6863 - val_smape: 1.1081

Epoch 24/256

4584/4584 - 59s - 13ms/step - ia: 0.7085 - loss: 0.2713 - mae: 0.4087 - rmse: 0.5033 - smape: 0.7495 - val_ia: 0.1594 - val_loss: 0.7237 - val_mae: 0.6891 - val_rmse: 0.7093 - val_smape: 1.1238

Epoch 25/256

4584/4584 - 70s - 15ms/step - ia: 0.7098 - loss: 0.2679 - mae: 0.4056 - rmse: 0.5004 - smape: 0.7468 - val_ia: 0.1593 - val_loss: 0.6640 - val_mae: 0.6602 - val_rmse: 0.6813 - val_smape: 1.1020

Epoch 26/256

4584/4584 - 84s - 18ms/step - ia: 0.7131 - loss: 0.2640 - mae: 0.4021 - rmse: 0.4964 - smape: 0.7451 - val_ia: 0.1578 - val_loss: 0.6875 - val_mae: 0.6716 - val_rmse: 0.6923 - val_smape: 1.1063

Epoch 27/256

4584/4584 - 70s - 15ms/step - ia: 0.7160 - loss: 0.2600 - mae: 0.3984 - rmse: 0.4929 - smape: 0.7412 - val_ia: 0.1615 - val_loss: 0.6241 - val_mae: 0.6416 - val_rmse: 0.6620 - val_smape: 1.0902

Epoch 28/256

4584/4584 - 69s - 15ms/step - ia: 0.7164 - loss: 0.2562 - mae: 0.3948 - rmse: 0.4886 - smape: 0.7370 - val_ia: 0.1587 - val_loss: 0.6692 - val_mae: 0.6658 - val_rmse: 0.6853 - val_smape: 1.0960

Epoch 29/256

4584/4584 - 56s - 12ms/step - ia: 0.7210 - loss: 0.2522 - mae: 0.3915 - rmse: 0.4843 - smape: 0.7372 - val_ia: 0.1582 - val_loss: 0.5804 - val_mae: 0.6219 - val_rmse: 0.6421 - val_smape: 1.0694

Epoch 30/256

4584/4584 - 97s - 21ms/step - ia: 0.7247 - loss: 0.2481 - mae: 0.3873 - rmse: 0.4801 - smape: 0.7318 - val_ia: 0.1594 - val_loss: 0.6477 - val_mae: 0.6558 - val_rmse: 0.6747 - val_smape: 1.0881

Epoch 31/256

4584/4584 - 70s - 15ms/step - ia: 0.7271 - loss: 0.2440 - mae: 0.3838 - rmse: 0.4765 - smape: 0.7306 - val_ia: 0.1596 - val_loss: 0.6703 - val_mae: 0.6673 - val_rmse: 0.6856 - val_smape: 1.0952

Epoch 32/256

4584/4584 - 72s - 16ms/step - ia: 0.7300 - loss: 0.2392 - mae: 0.3791 - rmse: 0.4710 - smape: 0.7274 - val_ia: 0.1617 - val_loss: 0.5770 - val_mae: 0.6211 - val_rmse: 0.6395 - val_smape: 1.0603

Epoch 33/256

4584/4584 - 71s - 16ms/step - ia: 0.7334 - loss: 0.2345 - mae: 0.3747 - rmse: 0.4663 - smape: 0.7225 - val_ia: 0.1622 - val_loss: 0.5550 - val_mae: 0.6104 - val_rmse: 0.6284 - val_smape: 1.0488

Epoch 34/256

4584/4584 - 71s - 16ms/step - ia: 0.7369 - loss: 0.2297 - mae: 0.3703 - rmse: 0.4603 - smape: 0.7198 - val_ia: 0.1610 - val_loss: 0.5907 - val_mae: 0.6280 - val_rmse: 0.6455 - val_smape: 1.0572

Epoch 35/256

4584/4584 - 83s - 18ms/step - ia: 0.7409 - loss: 0.2243 - mae: 0.3654 - rmse: 0.4546 - smape: 0.7157 - val_ia: 0.1624 - val_loss: 0.5684 - val_mae: 0.6164 - val_rmse: 0.6336 - val_smape: 1.0434

Epoch 36/256

4584/4584 - 58s - 13ms/step - ia: 0.7421 - loss: 0.2191 - mae: 0.3604 - rmse: 0.4493 - smape: 0.7111 - val_ia: 0.1629 - val_loss: 0.5523 - val_mae: 0.6075 - val_rmse: 0.6244 - val_smape: 1.0201

Epoch 37/256

4584/4584 - 57s - 12ms/step - ia: 0.7471 - loss: 0.2133 - mae: 0.3547 - rmse: 0.4430 - smape: 0.7052 - val_ia: 0.1644 - val_loss: 0.5209 - val_mae: 0.5899 - val_rmse: 0.6068 - val_smape: 1.0143

Epoch 38/256

4584/4584 - 60s - 13ms/step - ia: 0.7508 - loss: 0.2074 - mae: 0.3491 - rmse: 0.4360 - smape: 0.7013 - val_ia: 0.1681 - val_loss: 0.5693 - val_mae: 0.6141 - val_rmse: 0.6303 - val_smape: 1.0004

Epoch 39/256

4584/4584 - 90s - 20ms/step - ia: 0.7551 - loss: 0.2013 - mae: 0.3430 - rmse: 0.4294 - smape: 0.6943 - val_ia: 0.1691 - val_loss: 0.4778 - val_mae: 0.5635 - val_rmse: 0.5804 - val_smape: 0.9838

Epoch 40/256

4584/4584 - 70s - 15ms/step - ia: 0.7596 - loss: 0.1952 - mae: 0.3372 - rmse: 0.4225 - smape: 0.6898 - val_ia: 0.1718 - val_loss: 0.5250 - val_mae: 0.5853 - val_rmse: 0.6021 - val_smape: 0.9729

Epoch 41/256

4584/4584 - 70s - 15ms/step - ia: 0.7627 - loss: 0.1886 - mae: 0.3308 - rmse: 0.4151 - smape: 0.6839 - val_ia: 0.1777 - val_loss: 0.5059 - val_mae: 0.5734 - val_rmse: 0.5899 - val_smape: 0.9548

Epoch 42/256

4584/4584 - 81s - 18ms/step - ia: 0.7693 - loss: 0.1816 - mae: 0.3235 - rmse: 0.4064 - smape: 0.6752 - val_ia: 0.1815 - val_loss: 0.4964 - val_mae: 0.5651 - val_rmse: 0.5821 - val_smape: 0.9429

Epoch 43/256

4584/4584 - 69s - 15ms/step - ia: 0.7734 - loss: 0.1749 - mae: 0.3166 - rmse: 0.3988 - smape: 0.6694 - val_ia: 0.1833 - val_loss: 0.5034 - val_mae: 0.5663 - val_rmse: 0.5836 - val_smape: 0.9385

Epoch 44/256

4584/4584 - 70s - 15ms/step - ia: 0.7787 - loss: 0.1676 - mae: 0.3092 - rmse: 0.3905 - smape: 0.6609 - val_ia: 0.1916 - val_loss: 0.3731 - val_mae: 0.4948 - val_rmse: 0.5120 - val_smape: 0.9169

Epoch 45/256

4584/4584 - 81s - 18ms/step - ia: 0.7845 - loss: 0.1606 - mae: 0.3016 - rmse: 0.3811 - smape: 0.6528 - val_ia: 0.1960 - val_loss: 0.3968 - val_mae: 0.5045 - val_rmse: 0.5216 - val_smape: 0.8976

Epoch 46/256

4584/4584 - 69s - 15ms/step - ia: 0.7887 - loss: 0.1535 - mae: 0.2945 - rmse: 0.3724 - smape: 0.6449 - val_ia: 0.1983 - val_loss: 0.3759 - val_mae: 0.4918 - val_rmse: 0.5091 - val_smape: 0.9021

Epoch 47/256

4584/4584 - 82s - 18ms/step - ia: 0.7942 - loss: 0.1467 - mae: 0.2873 - rmse: 0.3636 - smape: 0.6374 - val_ia: 0.1965 - val_loss: 0.3310 - val_mae: 0.4646 - val_rmse: 0.4821 - val_smape: 0.8886

Epoch 48/256

4584/4584 - 83s - 18ms/step - ia: 0.7995 - loss: 0.1408 - mae: 0.2811 - rmse: 0.3561 - smape: 0.6312 - val_ia: 0.2114 - val_loss: 0.3120 - val_mae: 0.4477 - val_rmse: 0.4655 - val_smape: 0.8541

Epoch 49/256

4584/4584 - 75s - 16ms/step - ia: 0.8030 - loss: 0.1353 - mae: 0.2747 - rmse: 0.3485 - smape: 0.6216 - val_ia: 0.2108 - val_loss: 0.3207 - val_mae: 0.4520 - val_rmse: 0.4700 - val_smape: 0.8539

Epoch 50/256

4584/4584 - 58s - 13ms/step - ia: 0.8079 - loss: 0.1299 - mae: 0.2686 - rmse: 0.3413 - smape: 0.6136 - val_ia: 0.2166 - val_loss: 0.2823 - val_mae: 0.4276 - val_rmse: 0.4464 - val_smape: 0.8534

Epoch 51/256

4584/4584 - 48s - 11ms/step - ia: 0.8109 - loss: 0.1258 - mae: 0.2641 - rmse: 0.3354 - smape: 0.6094 - val_ia: 0.2113 - val_loss: 0.3322 - val_mae: 0.4577 - val_rmse: 0.4749 - val_smape: 0.8367

Epoch 52/256

4584/4584 - 96s - 21ms/step - ia: 0.8136 - loss: 0.1227 - mae: 0.2605 - rmse: 0.3314 - smape: 0.6041 - val_ia: 0.2212 - val_loss: 0.2982 - val_mae: 0.4337 - val_rmse: 0.4515 - val_smape: 0.8179

Epoch 53/256

4584/4584 - 58s - 13ms/step - ia: 0.8162 - loss: 0.1200 - mae: 0.2569 - rmse: 0.3267 - smape: 0.5986 - val_ia: 0.2271 - val_loss: 0.2514 - val_mae: 0.4007 - val_rmse: 0.4185 - val_smape: 0.7960

Epoch 54/256

4584/4584 - 63s - 14ms/step - ia: 0.8186 - loss: 0.1176 - mae: 0.2539 - rmse: 0.3237 - smape: 0.5950 - val_ia: 0.2322 - val_loss: 0.2456 - val_mae: 0.3966 - val_rmse: 0.4157 - val_smape: 0.8035

Epoch 55/256

4584/4584 - 53s - 12ms/step - ia: 0.8205 - loss: 0.1158 - mae: 0.2515 - rmse: 0.3203 - smape: 0.5900 - val_ia: 0.2318 - val_loss: 0.2677 - val_mae: 0.4101 - val_rmse: 0.4290 - val_smape: 0.7969

Epoch 56/256

4584/4584 - 69s - 15ms/step - ia: 0.8222 - loss: 0.1137 - mae: 0.2486 - rmse: 0.3177 - smape: 0.5859 - val_ia: 0.2391 - val_loss: 0.2286 - val_mae: 0.3814 - val_rmse: 0.3990 - val_smape: 0.7682

Epoch 57/256

4584/4584 - 60s - 13ms/step - ia: 0.8227 - loss: 0.1128 - mae: 0.2473 - rmse: 0.3158 - smape: 0.5842 - val_ia: 0.2454 - val_loss: 0.2170 - val_mae: 0.3715 - val_rmse: 0.3901 - val_smape: 0.7590

Epoch 58/256

4584/4584 - 59s - 13ms/step - ia: 0.8254 - loss: 0.1115 - mae: 0.2452 - rmse: 0.3142 - smape: 0.5808 - val_ia: 0.2300 - val_loss: 0.2696 - val_mae: 0.4130 - val_rmse: 0.4299 - val_smape: 0.7937

Epoch 59/256

4584/4584 - 91s - 20ms/step - ia: 0.8260 - loss: 0.1102 - mae: 0.2436 - rmse: 0.3119 - smape: 0.5783 - val_ia: 0.2372 - val_loss: 0.2528 - val_mae: 0.3988 - val_rmse: 0.4162 - val_smape: 0.7747

Epoch 60/256

4584/4584 - 89s - 19ms/step - ia: 0.8274 - loss: 0.1092 - mae: 0.2424 - rmse: 0.3104 - smape: 0.5753 - val_ia: 0.2441 - val_loss: 0.2376 - val_mae: 0.3858 - val_rmse: 0.4039 - val_smape: 0.7626

Epoch 61/256

4584/4584 - 77s - 17ms/step - ia: 0.8267 - loss: 0.1087 - mae: 0.2417 - rmse: 0.3103 - smape: 0.5728 - val_ia: 0.2438 - val_loss: 0.2360 - val_mae: 0.3849 - val_rmse: 0.4024 - val_smape: 0.7616

Epoch 62/256

4584/4584 - 83s - 18ms/step - ia: 0.8290 - loss: 0.1074 - mae: 0.2400 - rmse: 0.3077 - smape: 0.5694 - val_ia: 0.2454 - val_loss: 0.2219 - val_mae: 0.3736 - val_rmse: 0.3912 - val_smape: 0.7493

Epoch 63/256

4584/4584 - 72s - 16ms/step - ia: 0.8293 - loss: 0.1066 - mae: 0.2389 - rmse: 0.3068 - smape: 0.5686 - val_ia: 0.2475 - val_loss: 0.2054 - val_mae: 0.3618 - val_rmse: 0.3793 - val_smape: 0.7387

Epoch 64/256

4584/4584 - 60s - 13ms/step - ia: 0.8303 - loss: 0.1062 - mae: 0.2381 - rmse: 0.3064 - smape: 0.5671 - val_ia: 0.2445 - val_loss: 0.2185 - val_mae: 0.3714 - val_rmse: 0.3886 - val_smape: 0.7470

Epoch 65/256

4584/4584 - 60s - 13ms/step - ia: 0.8306 - loss: 0.1054 - mae: 0.2375 - rmse: 0.3051 - smape: 0.5673 - val_ia: 0.2471 - val_loss: 0.2173 - val_mae: 0.3709 - val_rmse: 0.3872 - val_smape: 0.7450

Epoch 66/256

4584/4584 - 52s - 11ms/step - ia: 0.8309 - loss: 0.1047 - mae: 0.2367 - rmse: 0.3038 - smape: 0.5664 - val_ia: 0.2518 - val_loss: 0.1932 - val_mae: 0.3517 - val_rmse: 0.3689 - val_smape: 0.7276

Epoch 67/256

4584/4584 - 51s - 11ms/step - ia: 0.8316 - loss: 0.1041 - mae: 0.2355 - rmse: 0.3027 - smape: 0.5635 - val_ia: 0.2480 - val_loss: 0.2054 - val_mae: 0.3613 - val_rmse: 0.3781 - val_smape: 0.7334

Epoch 68/256

4584/4584 - 66s - 14ms/step - ia: 0.8321 - loss: 0.1031 - mae: 0.2346 - rmse: 0.3017 - smape: 0.5605 - val_ia: 0.2449 - val_loss: 0.2158 - val_mae: 0.3693 - val_rmse: 0.3859 - val_smape: 0.7417

Epoch 69/256

4584/4584 - 82s - 18ms/step - ia: 0.8319 - loss: 0.1028 - mae: 0.2343 - rmse: 0.3009 - smape: 0.5611 - val_ia: 0.2528 - val_loss: 0.1942 - val_mae: 0.3512 - val_rmse: 0.3682 - val_smape: 0.7195

Epoch 70/256

4584/4584 - 67s - 15ms/step - ia: 0.8333 - loss: 0.1021 - mae: 0.2331 - rmse: 0.3000 - smape: 0.5593 - val_ia: 0.2460 - val_loss: 0.2148 - val_mae: 0.3678 - val_rmse: 0.3839 - val_smape: 0.7399

Epoch 71/256

4584/4584 - 79s - 17ms/step - ia: 0.8333 - loss: 0.1016 - mae: 0.2327 - rmse: 0.2992 - smape: 0.5597 - val_ia: 0.2468 - val_loss: 0.2130 - val_mae: 0.3672 - val_rmse: 0.3834 - val_smape: 0.7391

Epoch 72/256

4584/4584 - 90s - 20ms/step - ia: 0.8344 - loss: 0.1014 - mae: 0.2325 - rmse: 0.2995 - smape: 0.5579 - val_ia: 0.2495 - val_loss: 0.2108 - val_mae: 0.3666 - val_rmse: 0.3825 - val_smape: 0.7425

Epoch 73/256

4584/4584 - 81s - 18ms/step - ia: 0.8342 - loss: 0.1010 - mae: 0.2322 - rmse: 0.2988 - smape: 0.5586 - val_ia: 0.2533 - val_loss: 0.1804 - val_mae: 0.3407 - val_rmse: 0.3568 - val_smape: 0.7091

Epoch 74/256

4584/4584 - 70s - 15ms/step - ia: 0.8341 - loss: 0.1004 - mae: 0.2316 - rmse: 0.2976 - smape: 0.5580 - val_ia: 0.2570 - val_loss: 0.1806 - val_mae: 0.3394 - val_rmse: 0.3557 - val_smape: 0.7036

Epoch 75/256

4584/4584 - 71s - 15ms/step - ia: 0.8364 - loss: 0.0996 - mae: 0.2304 - rmse: 0.2964 - smape: 0.5564 - val_ia: 0.2428 - val_loss: 0.2140 - val_mae: 0.3706 - val_rmse: 0.3858 - val_smape: 0.7444

Epoch 76/256

4584/4584 - 72s - 16ms/step - ia: 0.8362 - loss: 0.0992 - mae: 0.2300 - rmse: 0.2962 - smape: 0.5559 - val_ia: 0.2611 - val_loss: 0.1782 - val_mae: 0.3364 - val_rmse: 0.3525 - val_smape: 0.7009

Epoch 77/256

4584/4584 - 73s - 16ms/step - ia: 0.8363 - loss: 0.0987 - mae: 0.2295 - rmse: 0.2949 - smape: 0.5544 - val_ia: 0.2610 - val_loss: 0.1797 - val_mae: 0.3375 - val_rmse: 0.3536 - val_smape: 0.7002

Epoch 78/256

4584/4584 - 67s - 15ms/step - ia: 0.8373 - loss: 0.0982 - mae: 0.2288 - rmse: 0.2941 - smape: 0.5550 - val_ia: 0.2507 - val_loss: 0.1971 - val_mae: 0.3543 - val_rmse: 0.3695 - val_smape: 0.7249

Epoch 79/256

4584/4584 - 71s - 16ms/step - ia: 0.8368 - loss: 0.0979 - mae: 0.2285 - rmse: 0.2940 - smape: 0.5534 - val_ia: 0.2343 - val_loss: 0.2304 - val_mae: 0.3877 - val_rmse: 0.4027 - val_smape: 0.7685

Epoch 80/256

4584/4584 - 70s - 15ms/step - ia: 0.8363 - loss: 0.0976 - mae: 0.2282 - rmse: 0.2933 - smape: 0.5527 - val_ia: 0.2492 - val_loss: 0.2060 - val_mae: 0.3623 - val_rmse: 0.3780 - val_smape: 0.7371

Epoch 81/256

4584/4584 - 66s - 14ms/step - ia: 0.8385 - loss: 0.0970 - mae: 0.2273 - rmse: 0.2929 - smape: 0.5510 - val_ia: 0.2423 - val_loss: 0.2176 - val_mae: 0.3731 - val_rmse: 0.3884 - val_smape: 0.7471

Epoch 82/256

4584/4584 - 70s - 15ms/step - ia: 0.8385 - loss: 0.0967 - mae: 0.2269 - rmse: 0.2920 - smape: 0.5521 - val_ia: 0.2422 - val_loss: 0.2190 - val_mae: 0.3753 - val_rmse: 0.3908 - val_smape: 0.7543

Epoch 83/256

4584/4584 - 83s - 18ms/step - ia: 0.8382 - loss: 0.0962 - mae: 0.2263 - rmse: 0.2915 - smape: 0.5503 - val_ia: 0.2581 - val_loss: 0.1691 - val_mae: 0.3290 - val_rmse: 0.3445 - val_smape: 0.6883

Epoch 84/256

4584/4584 - 70s - 15ms/step - ia: 0.8388 - loss: 0.0958 - mae: 0.2264 - rmse: 0.2909 - smape: 0.5508 - val_ia: 0.2540 - val_loss: 0.1848 - val_mae: 0.3423 - val_rmse: 0.3579 - val_smape: 0.7084

Epoch 85/256

4584/4584 - 65s - 14ms/step - ia: 0.8386 - loss: 0.0956 - mae: 0.2258 - rmse: 0.2905 - smape: 0.5496 - val_ia: 0.2566 - val_loss: 0.1883 - val_mae: 0.3461 - val_rmse: 0.3618 - val_smape: 0.7189

Epoch 86/256

4584/4584 - 71s - 15ms/step - ia: 0.8393 - loss: 0.0951 - mae: 0.2251 - rmse: 0.2898 - smape: 0.5484 - val_ia: 0.2571 - val_loss: 0.1753 - val_mae: 0.3349 - val_rmse: 0.3503 - val_smape: 0.7017

Epoch 87/256

4584/4584 - 68s - 15ms/step - ia: 0.8398 - loss: 0.0946 - mae: 0.2247 - rmse: 0.2892 - smape: 0.5472 - val_ia: 0.2614 - val_loss: 0.1657 - val_mae: 0.3254 - val_rmse: 0.3409 - val_smape: 0.6871

Epoch 88/256

4584/4584 - 67s - 15ms/step - ia: 0.8408 - loss: 0.0943 - mae: 0.2242 - rmse: 0.2884 - smape: 0.5465 - val_ia: 0.2574 - val_loss: 0.1560 - val_mae: 0.3178 - val_rmse: 0.3337 - val_smape: 0.6791

Epoch 89/256

4584/4584 - 69s - 15ms/step - ia: 0.8405 - loss: 0.0942 - mae: 0.2242 - rmse: 0.2880 - smape: 0.5476 - val_ia: 0.2352 - val_loss: 0.2194 - val_mae: 0.3802 - val_rmse: 0.3949 - val_smape: 0.7603

Epoch 90/256

4584/4584 - 70s - 15ms/step - ia: 0.8414 - loss: 0.0938 - mae: 0.2235 - rmse: 0.2878 - smape: 0.5451 - val_ia: 0.2591 - val_loss: 0.1798 - val_mae: 0.3399 - val_rmse: 0.3552 - val_smape: 0.7138

Epoch 91/256

4584/4584 - 71s - 15ms/step - ia: 0.8411 - loss: 0.0932 - mae: 0.2232 - rmse: 0.2872 - smape: 0.5470 - val_ia: 0.2675 - val_loss: 0.1555 - val_mae: 0.3152 - val_rmse: 0.3304 - val_smape: 0.6727

Epoch 92/256

4584/4584 - 65s - 14ms/step - ia: 0.8415 - loss: 0.0929 - mae: 0.2226 - rmse: 0.2870 - smape: 0.5430 - val_ia: 0.2628 - val_loss: 0.1605 - val_mae: 0.3203 - val_rmse: 0.3356 - val_smape: 0.6774

Epoch 93/256

4584/4584 - 89s - 19ms/step - ia: 0.8408 - loss: 0.0926 - mae: 0.2226 - rmse: 0.2861 - smape: 0.5448 - val_ia: 0.2487 - val_loss: 0.1996 - val_mae: 0.3575 - val_rmse: 0.3726 - val_smape: 0.7301

Epoch 94/256

4584/4584 - 71s - 15ms/step - ia: 0.8408 - loss: 0.0919 - mae: 0.2216 - rmse: 0.2849 - smape: 0.5420 - val_ia: 0.2599 - val_loss: 0.1821 - val_mae: 0.3399 - val_rmse: 0.3553 - val_smape: 0.7091

Epoch 95/256

4584/4584 - 70s - 15ms/step - ia: 0.8417 - loss: 0.0920 - mae: 0.2215 - rmse: 0.2848 - smape: 0.5416 - val_ia: 0.2618 - val_loss: 0.1677 - val_mae: 0.3259 - val_rmse: 0.3417 - val_smape: 0.6842

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 87s - 19ms/step - ia: 0.2070 - loss: 0.9989 - mae: 0.8294 - rmse: 0.9808 - smape: 1.8948 - val_ia: 0.1384 - val_loss: 0.8460 - val_mae: 0.7648 - val_rmse: 0.7818 - val_smape: 1.8373

Epoch 2/256

4584/4584 - 66s - 14ms/step - ia: 0.2597 - loss: 0.8950 - mae: 0.7940 - rmse: 0.9287 - smape: 1.6276 - val_ia: 0.1363 - val_loss: 0.8173 - val_mae: 0.7381 - val_rmse: 0.7555 - val_smape: 1.2858

Epoch 3/256

4584/4584 - 66s - 14ms/step - ia: 0.4606 - loss: 0.6291 - mae: 0.6644 - rmse: 0.7762 - smape: 1.1546 - val_ia: 0.1383 - val_loss: 1.1247 - val_mae: 0.8723 - val_rmse: 0.8885 - val_smape: 1.3090

Epoch 4/256

4584/4584 - 69s - 15ms/step - ia: 0.5432 - loss: 0.5366 - mae: 0.5961 - rmse: 0.7128 - smape: 1.0163 - val_ia: 0.1274 - val_loss: 1.3383 - val_mae: 0.9666 - val_rmse: 0.9820 - val_smape: 1.3629

Epoch 5/256

4584/4584 - 71s - 15ms/step - ia: 0.5633 - loss: 0.5095 - mae: 0.5761 - rmse: 0.6944 - smape: 0.9879 - val_ia: 0.1248 - val_loss: 1.3946 - val_mae: 0.9909 - val_rmse: 1.0061 - val_smape: 1.3782

Epoch 6/256

4584/4584 - 72s - 16ms/step - ia: 0.5771 - loss: 0.4840 - mae: 0.5596 - rmse: 0.6759 - smape: 0.9635 - val_ia: 0.1213 - val_loss: 1.4540 - val_mae: 1.0150 - val_rmse: 1.0301 - val_smape: 1.3905

Epoch 7/256

4584/4584 - 68s - 15ms/step - ia: 0.5946 - loss: 0.4571 - mae: 0.5419 - rmse: 0.6564 - smape: 0.9373 - val_ia: 0.1184 - val_loss: 1.4809 - val_mae: 1.0286 - val_rmse: 1.0436 - val_smape: 1.4013

Epoch 8/256

4584/4584 - 67s - 15ms/step - ia: 0.6102 - loss: 0.4298 - mae: 0.5237 - rmse: 0.6357 - smape: 0.9102 - val_ia: 0.1198 - val_loss: 1.4097 - val_mae: 0.9994 - val_rmse: 1.0149 - val_smape: 1.3831

Epoch 9/256

4584/4584 - 81s - 18ms/step - ia: 0.6257 - loss: 0.4043 - mae: 0.5071 - rmse: 0.6164 - smape: 0.8829 - val_ia: 0.1209 - val_loss: 1.3663 - val_mae: 0.9808 - val_rmse: 0.9969 - val_smape: 1.3625

Epoch 10/256

4584/4584 - 66s - 14ms/step - ia: 0.6393 - loss: 0.3828 - mae: 0.4922 - rmse: 0.5995 - smape: 0.8575 - val_ia: 0.1298 - val_loss: 1.2163 - val_mae: 0.9182 - val_rmse: 0.9354 - val_smape: 1.3131

Epoch 11/256

4584/4584 - 66s - 14ms/step - ia: 0.6476 - loss: 0.3666 - mae: 0.4818 - rmse: 0.5868 - smape: 0.8424 - val_ia: 0.1263 - val_loss: 1.2472 - val_mae: 0.9339 - val_rmse: 0.9510 - val_smape: 1.3163

Epoch 12/256

4584/4584 - 82s - 18ms/step - ia: 0.6555 - loss: 0.3546 - mae: 0.4740 - rmse: 0.5767 - smape: 0.8293 - val_ia: 0.1284 - val_loss: 1.2160 - val_mae: 0.9204 - val_rmse: 0.9379 - val_smape: 1.2970

Epoch 13/256

4584/4584 - 66s - 14ms/step - ia: 0.6620 - loss: 0.3460 - mae: 0.4679 - rmse: 0.5700 - smape: 0.8179 - val_ia: 0.1382 - val_loss: 1.0708 - val_mae: 0.8519 - val_rmse: 0.8709 - val_smape: 1.2349

Epoch 14/256

4584/4584 - 67s - 15ms/step - ia: 0.6653 - loss: 0.3392 - mae: 0.4634 - rmse: 0.5647 - smape: 0.8113 - val_ia: 0.1457 - val_loss: 0.9784 - val_mae: 0.8066 - val_rmse: 0.8267 - val_smape: 1.1931

Epoch 15/256

4584/4584 - 67s - 15ms/step - ia: 0.6685 - loss: 0.3335 - mae: 0.4593 - rmse: 0.5594 - smape: 0.8055 - val_ia: 0.1419 - val_loss: 1.0347 - val_mae: 0.8353 - val_rmse: 0.8549 - val_smape: 1.2141

Epoch 16/256

4584/4584 - 66s - 14ms/step - ia: 0.6716 - loss: 0.3288 - mae: 0.4558 - rmse: 0.5557 - smape: 0.8002 - val_ia: 0.1461 - val_loss: 0.9670 - val_mae: 0.8036 - val_rmse: 0.8237 - val_smape: 1.1905

Epoch 17/256

4584/4584 - 67s - 15ms/step - ia: 0.6723 - loss: 0.3245 - mae: 0.4525 - rmse: 0.5514 - smape: 0.7962 - val_ia: 0.1511 - val_loss: 0.8688 - val_mae: 0.7560 - val_rmse: 0.7768 - val_smape: 1.1616

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:14 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 46%|████▌     | 23/50 [7:32:22<26:49:59, 3577.74s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2292/2292 - 64s - 28ms/step - ia: 0.1644 - loss: 0.9991 - mae: 0.8296 - rmse: 0.9895 - smape: 1.8975 - val_ia: 0.1815 - val_loss: 0.8487 - val_mae: 0.7665 - val_rmse: 0.8034 - val_smape: 1.8986

Epoch 2/256

2292/2292 - 40s - 17ms/step - ia: 0.2639 - loss: 0.8648 - mae: 0.7814 - rmse: 0.9205 - smape: 1.5660 - val_ia: 0.1858 - val_loss: 0.8586 - val_mae: 0.7518 - val_rmse: 0.7851 - val_smape: 1.2569

Epoch 3/256

2292/2292 - 37s - 16ms/step - ia: 0.5189 - loss: 0.5797 - mae: 0.6310 - rmse: 0.7521 - smape: 1.0824 - val_ia: 0.1813 - val_loss: 1.1804 - val_mae: 0.8988 - val_rmse: 0.9280 - val_smape: 1.3239

Epoch 4/256

2292/2292 - 41s - 18ms/step - ia: 0.5748 - loss: 0.5155 - mae: 0.5816 - rmse: 0.7082 - smape: 0.9934 - val_ia: 0.1792 - val_loss: 1.2427 - val_mae: 0.9254 - val_rmse: 0.9550 - val_smape: 1.3392

Epoch 5/256

2292/2292 - 37s - 16ms/step - ia: 0.5960 - loss: 0.4844 - mae: 0.5605 - rmse: 0.6861 - smape: 0.9626 - val_ia: 0.1757 - val_loss: 1.3940 - val_mae: 0.9919 - val_rmse: 1.0217 - val_smape: 1.3754

Epoch 6/256

2292/2292 - 37s - 16ms/step - ia: 0.6148 - loss: 0.4541 - mae: 0.5403 - rmse: 0.6641 - smape: 0.9319 - val_ia: 0.1811 - val_loss: 1.3325 - val_mae: 0.9612 - val_rmse: 0.9925 - val_smape: 1.3426

Epoch 7/256

2292/2292 - 36s - 16ms/step - ia: 0.6330 - loss: 0.4234 - mae: 0.5199 - rmse: 0.6405 - smape: 0.9023 - val_ia: 0.1818 - val_loss: 1.3127 - val_mae: 0.9548 - val_rmse: 0.9865 - val_smape: 1.3370

Epoch 8/256

2292/2292 - 37s - 16ms/step - ia: 0.6497 - loss: 0.3953 - mae: 0.5008 - rmse: 0.6190 - smape: 0.8727 - val_ia: 0.1840 - val_loss: 1.3002 - val_mae: 0.9487 - val_rmse: 0.9811 - val_smape: 1.3181

Epoch 9/256

2292/2292 - 35s - 15ms/step - ia: 0.6629 - loss: 0.3733 - mae: 0.4857 - rmse: 0.6018 - smape: 0.8485 - val_ia: 0.1769 - val_loss: 1.3715 - val_mae: 0.9887 - val_rmse: 1.0203 - val_smape: 1.3583

Epoch 10/256

2292/2292 - 36s - 16ms/step - ia: 0.6722 - loss: 0.3577 - mae: 0.4749 - rmse: 0.5887 - smape: 0.8315 - val_ia: 0.1967 - val_loss: 1.0660 - val_mae: 0.8472 - val_rmse: 0.8808 - val_smape: 1.2325

Epoch 11/256

2292/2292 - 37s - 16ms/step - ia: 0.6791 - loss: 0.3475 - mae: 0.4682 - rmse: 0.5800 - smape: 0.8197 - val_ia: 0.1987 - val_loss: 1.0570 - val_mae: 0.8428 - val_rmse: 0.8770 - val_smape: 1.2209

Epoch 12/256

2292/2292 - 37s - 16ms/step - ia: 0.6838 - loss: 0.3402 - mae: 0.4636 - rmse: 0.5739 - smape: 0.8119 - val_ia: 0.2001 - val_loss: 1.0493 - val_mae: 0.8400 - val_rmse: 0.8745 - val_smape: 1.2143

Epoch 13/256

2292/2292 - 35s - 15ms/step - ia: 0.6871 - loss: 0.3344 - mae: 0.4593 - rmse: 0.5696 - smape: 0.8055 - val_ia: 0.2031 - val_loss: 0.9580 - val_mae: 0.7977 - val_rmse: 0.8324 - val_smape: 1.1868

Epoch 14/256

2292/2292 - 35s - 15ms/step - ia: 0.6890 - loss: 0.3292 - mae: 0.4557 - rmse: 0.5648 - smape: 0.8005 - val_ia: 0.2038 - val_loss: 0.8822 - val_mae: 0.7621 - val_rmse: 0.7967 - val_smape: 1.1664

Epoch 15/256

2292/2292 - 35s - 15ms/step - ia: 0.6930 - loss: 0.3248 - mae: 0.4523 - rmse: 0.5615 - smape: 0.7962 - val_ia: 0.2035 - val_loss: 0.9641 - val_mae: 0.8039 - val_rmse: 0.8380 - val_smape: 1.1928

Epoch 16/256

2292/2292 - 42s - 18ms/step - ia: 0.6948 - loss: 0.3204 - mae: 0.4492 - rmse: 0.5573 - smape: 0.7909 - val_ia: 0.2048 - val_loss: 0.8962 - val_mae: 0.7719 - val_rmse: 0.8061 - val_smape: 1.1716

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step

 48%|████▊     | 24/50 [7:42:48<19:26:32, 2692.01s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 90s - 20ms/step - ia: 0.2173 - loss: 1.0185 - mae: 0.8377 - rmse: 0.9896 - smape: 1.6893 - val_ia: 0.1386 - val_loss: 0.8513 - val_mae: 0.7679 - val_rmse: 0.7851 - val_smape: 1.9158

Epoch 2/256

4584/4584 - 75s - 16ms/step - ia: 0.2899 - loss: 0.8778 - mae: 0.7848 - rmse: 0.9181 - smape: 1.5064 - val_ia: 0.1429 - val_loss: 0.8820 - val_mae: 0.7609 - val_rmse: 0.7781 - val_smape: 1.2589

Epoch 3/256

4584/4584 - 80s - 17ms/step - ia: 0.5096 - loss: 0.5909 - mae: 0.6307 - rmse: 0.7494 - smape: 1.0725 - val_ia: 0.1278 - val_loss: 1.3264 - val_mae: 0.9649 - val_rmse: 0.9803 - val_smape: 1.3646

Epoch 4/256

4584/4584 - 85s - 19ms/step - ia: 0.5521 - loss: 0.5380 - mae: 0.5923 - rmse: 0.7123 - smape: 1.0003 - val_ia: 0.1295 - val_loss: 1.3080 - val_mae: 0.9554 - val_rmse: 0.9711 - val_smape: 1.3590

Epoch 5/256

4584/4584 - 76s - 16ms/step - ia: 0.5700 - loss: 0.5089 - mae: 0.5743 - rmse: 0.6929 - smape: 0.9703 - val_ia: 0.1157 - val_loss: 1.5005 - val_mae: 1.0423 - val_rmse: 1.0569 - val_smape: 1.4106

Epoch 6/256

4584/4584 - 75s - 16ms/step - ia: 0.5851 - loss: 0.4801 - mae: 0.5562 - rmse: 0.6730 - smape: 0.9450 - val_ia: 0.1226 - val_loss: 1.3964 - val_mae: 0.9980 - val_rmse: 1.0131 - val_smape: 1.3887

Epoch 7/256

4584/4584 - 73s - 16ms/step - ia: 0.6038 - loss: 0.4491 - mae: 0.5353 - rmse: 0.6501 - smape: 0.9137 - val_ia: 0.1194 - val_loss: 1.4219 - val_mae: 1.0123 - val_rmse: 1.0272 - val_smape: 1.4002

Epoch 8/256

4584/4584 - 84s - 18ms/step - ia: 0.6177 - loss: 0.4228 - mae: 0.5186 - rmse: 0.6304 - smape: 0.8877 - val_ia: 0.1231 - val_loss: 1.3248 - val_mae: 0.9738 - val_rmse: 0.9892 - val_smape: 1.3833

Epoch 9/256

4584/4584 - 79s - 17ms/step - ia: 0.6295 - loss: 0.4031 - mae: 0.5059 - rmse: 0.6157 - smape: 0.8670 - val_ia: 0.1275 - val_loss: 1.2406 - val_mae: 0.9370 - val_rmse: 0.9530 - val_smape: 1.3520

Epoch 10/256

4584/4584 - 76s - 17ms/step - ia: 0.6409 - loss: 0.3864 - mae: 0.4950 - rmse: 0.6027 - smape: 0.8496 - val_ia: 0.1216 - val_loss: 1.3313 - val_mae: 0.9794 - val_rmse: 0.9948 - val_smape: 1.3798

Epoch 11/256

4584/4584 - 83s - 18ms/step - ia: 0.6459 - loss: 0.3753 - mae: 0.4871 - rmse: 0.5941 - smape: 0.8368 - val_ia: 0.1350 - val_loss: 1.1329 - val_mae: 0.8883 - val_rmse: 0.9052 - val_smape: 1.2942

Epoch 12/256

4584/4584 - 82s - 18ms/step - ia: 0.6521 - loss: 0.3659 - mae: 0.4806 - rmse: 0.5863 - smape: 0.8267 - val_ia: 0.1375 - val_loss: 1.1168 - val_mae: 0.8784 - val_rmse: 0.8957 - val_smape: 1.2691

Epoch 13/256

4584/4584 - 73s - 16ms/step - ia: 0.6562 - loss: 0.3595 - mae: 0.4765 - rmse: 0.5812 - smape: 0.8206 - val_ia: 0.1429 - val_loss: 1.0340 - val_mae: 0.8432 - val_rmse: 0.8609 - val_smape: 1.2556

Epoch 14/256

4584/4584 - 74s - 16ms/step - ia: 0.6569 - loss: 0.3550 - mae: 0.4727 - rmse: 0.5773 - smape: 0.8165 - val_ia: 0.1482 - val_loss: 0.9747 - val_mae: 0.8122 - val_rmse: 0.8306 - val_smape: 1.2162

Epoch 15/256

4584/4584 - 75s - 16ms/step - ia: 0.6634 - loss: 0.3472 - mae: 0.4673 - rmse: 0.5705 - smape: 0.8099 - val_ia: 0.1563 - val_loss: 0.8820 - val_mae: 0.7645 - val_rmse: 0.7836 - val_smape: 1.1799

Epoch 16/256

4584/4584 - 72s - 16ms/step - ia: 0.6649 - loss: 0.3412 - mae: 0.4630 - rmse: 0.5654 - smape: 0.8049 - val_ia: 0.1508 - val_loss: 0.9396 - val_mae: 0.7963 - val_rmse: 0.8149 - val_smape: 1.1986

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:58 2s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 50%|█████     | 25/50 [8:03:48<15:42:42, 2262.50s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 71s - 15ms/step - ia: 0.2098 - loss: 1.0181 - mae: 0.8359 - rmse: 0.9899 - smape: 1.7200 - val_ia: 0.1377 - val_loss: 0.8603 - val_mae: 0.7720 - val_rmse: 0.7889 - val_smape: 1.9801

Epoch 2/256

4584/4584 - 57s - 12ms/step - ia: 0.2039 - loss: 0.9993 - mae: 0.8296 - rmse: 0.9798 - smape: 1.9692 - val_ia: 0.1378 - val_loss: 0.8605 - val_mae: 0.7721 - val_rmse: 0.7890 - val_smape: 1.9695

Epoch 3/256

4584/4584 - 57s - 12ms/step - ia: 0.2042 - loss: 0.9983 - mae: 0.8292 - rmse: 0.9801 - smape: 1.9671 - val_ia: 0.1379 - val_loss: 0.8621 - val_mae: 0.7729 - val_rmse: 0.7899 - val_smape: 1.9320

Epoch 4/256

4584/4584 - 58s - 13ms/step - ia: 0.2033 - loss: 0.9959 - mae: 0.8284 - rmse: 0.9788 - smape: 1.9593 - val_ia: 0.1381 - val_loss: 0.8584 - val_mae: 0.7712 - val_rmse: 0.7883 - val_smape: 1.9501

Epoch 5/256

4584/4584 - 75s - 16ms/step - ia: 0.2050 - loss: 0.9903 - mae: 0.8266 - rmse: 0.9755 - smape: 1.9261 - val_ia: 0.1384 - val_loss: 0.8541 - val_mae: 0.7694 - val_rmse: 0.7866 - val_smape: 1.9093

Epoch 6/256

4584/4584 - 53s - 12ms/step - ia: 0.2086 - loss: 0.9779 - mae: 0.8224 - rmse: 0.9702 - smape: 1.8719 - val_ia: 0.1402 - val_loss: 0.8411 - val_mae: 0.7634 - val_rmse: 0.7809 - val_smape: 1.8200

Epoch 7/256

4584/4584 - 53s - 12ms/step - ia: 0.2164 - loss: 0.9520 - mae: 0.8135 - rmse: 0.9572 - smape: 1.7766 - val_ia: 0.1426 - val_loss: 0.8173 - val_mae: 0.7518 - val_rmse: 0.7698 - val_smape: 1.6830

Epoch 8/256

4584/4584 - 55s - 12ms/step - ia: 0.2351 - loss: 0.9073 - mae: 0.7978 - rmse: 0.9349 - smape: 1.6507 - val_ia: 0.1472 - val_loss: 0.7861 - val_mae: 0.7350 - val_rmse: 0.7535 - val_smape: 1.5229

Epoch 9/256

4584/4584 - 84s - 18ms/step - ia: 0.2776 - loss: 0.8394 - mae: 0.7718 - rmse: 0.8999 - smape: 1.5093 - val_ia: 0.1458 - val_loss: 0.7733 - val_mae: 0.7241 - val_rmse: 0.7419 - val_smape: 1.3807

Epoch 10/256

4584/4584 - 57s - 13ms/step - ia: 0.3370 - loss: 0.7564 - mae: 0.7357 - rmse: 0.8542 - smape: 1.3633 - val_ia: 0.1389 - val_loss: 0.7929 - val_mae: 0.7284 - val_rmse: 0.7447 - val_smape: 1.2985

Epoch 11/256

4584/4584 - 81s - 18ms/step - ia: 0.4034 - loss: 0.6734 - mae: 0.6933 - rmse: 0.8051 - smape: 1.2279 - val_ia: 0.1453 - val_loss: 0.8914 - val_mae: 0.7704 - val_rmse: 0.7868 - val_smape: 1.2729

Epoch 12/256

4584/4584 - 88s - 19ms/step - ia: 0.4596 - loss: 0.6101 - mae: 0.6559 - rmse: 0.7646 - smape: 1.1323 - val_ia: 0.1409 - val_loss: 1.0182 - val_mae: 0.8286 - val_rmse: 0.8450 - val_smape: 1.2900

Epoch 13/256

4584/4584 - 77s - 17ms/step - ia: 0.4969 - loss: 0.5718 - mae: 0.6302 - rmse: 0.7395 - smape: 1.0677 - val_ia: 0.1386 - val_loss: 1.1100 - val_mae: 0.8711 - val_rmse: 0.8874 - val_smape: 1.3089

Epoch 14/256

4584/4584 - 53s - 11ms/step - ia: 0.5218 - loss: 0.5478 - mae: 0.6117 - rmse: 0.7220 - smape: 1.0274 - val_ia: 0.1351 - val_loss: 1.1756 - val_mae: 0.9013 - val_rmse: 0.9173 - val_smape: 1.3260

Epoch 15/256

4584/4584 - 57s - 12ms/step - ia: 0.5387 - loss: 0.5304 - mae: 0.5976 - rmse: 0.7096 - smape: 1.0036 - val_ia: 0.1317 - val_loss: 1.2484 - val_mae: 0.9346 - val_rmse: 0.9503 - val_smape: 1.3470

Epoch 16/256

4584/4584 - 56s - 12ms/step - ia: 0.5517 - loss: 0.5162 - mae: 0.5864 - rmse: 0.6993 - smape: 0.9872 - val_ia: 0.1320 - val_loss: 1.2505 - val_mae: 0.9354 - val_rmse: 0.9512 - val_smape: 1.3486

Epoch 17/256

4584/4584 - 54s - 12ms/step - ia: 0.5625 - loss: 0.5039 - mae: 0.5766 - rmse: 0.6901 - smape: 0.9730 - val_ia: 0.1295 - val_loss: 1.2910 - val_mae: 0.9542 - val_rmse: 0.9698 - val_smape: 1.3611

Epoch 18/256

4584/4584 - 56s - 12ms/step - ia: 0.5692 - loss: 0.4928 - mae: 0.5684 - rmse: 0.6820 - smape: 0.9609 - val_ia: 0.1297 - val_loss: 1.2841 - val_mae: 0.9508 - val_rmse: 0.9665 - val_smape: 1.3600

Epoch 19/256

4584/4584 - 55s - 12ms/step - ia: 0.5776 - loss: 0.4822 - mae: 0.5607 - rmse: 0.6743 - smape: 0.9500 - val_ia: 0.1281 - val_loss: 1.3068 - val_mae: 0.9618 - val_rmse: 0.9774 - val_smape: 1.3697

Epoch 20/256

4584/4584 - 54s - 12ms/step - ia: 0.5835 - loss: 0.4720 - mae: 0.5537 - rmse: 0.6672 - smape: 0.9404 - val_ia: 0.1291 - val_loss: 1.2914 - val_mae: 0.9547 - val_rmse: 0.9703 - val_smape: 1.3662

Epoch 21/256

4584/4584 - 56s - 12ms/step - ia: 0.5906 - loss: 0.4618 - mae: 0.5466 - rmse: 0.6595 - smape: 0.9306 - val_ia: 0.1300 - val_loss: 1.2810 - val_mae: 0.9499 - val_rmse: 0.9656 - val_smape: 1.3639

Epoch 22/256

4584/4584 - 54s - 12ms/step - ia: 0.5963 - loss: 0.4520 - mae: 0.5399 - rmse: 0.6524 - smape: 0.9214 - val_ia: 0.1291 - val_loss: 1.2931 - val_mae: 0.9553 - val_rmse: 0.9710 - val_smape: 1.3668

Epoch 23/256

4584/4584 - 52s - 11ms/step - ia: 0.6019 - loss: 0.4422 - mae: 0.5333 - rmse: 0.6453 - smape: 0.9113 - val_ia: 0.1295 - val_loss: 1.2813 - val_mae: 0.9501 - val_rmse: 0.9659 - val_smape: 1.3640

Epoch 24/256

4584/4584 - 52s - 11ms/step - ia: 0.6083 - loss: 0.4327 - mae: 0.5269 - rmse: 0.6382 - smape: 0.9032 - val_ia: 0.1293 - val_loss: 1.2779 - val_mae: 0.9489 - val_rmse: 0.9646 - val_smape: 1.3628

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:06 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 52%|█████▏    | 26/50 [8:28:18<13:29:53, 2024.72s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 82s - 18ms/step - ia: 0.2727 - loss: 0.8910 - mae: 0.7871 - rmse: 0.9223 - smape: 1.6170 - val_ia: 0.1376 - val_loss: 1.1202 - val_mae: 0.8718 - val_rmse: 0.8881 - val_smape: 1.3157

Epoch 2/256

4584/4584 - 82s - 18ms/step - ia: 0.5729 - loss: 0.4894 - mae: 0.5642 - rmse: 0.6791 - smape: 0.9719 - val_ia: 0.1338 - val_loss: 1.2151 - val_mae: 0.9074 - val_rmse: 0.9244 - val_smape: 1.3093

Epoch 3/256

4584/4584 - 70s - 15ms/step - ia: 0.6221 - loss: 0.4116 - mae: 0.5121 - rmse: 0.6226 - smape: 0.8911 - val_ia: 0.1228 - val_loss: 1.3119 - val_mae: 0.9603 - val_rmse: 0.9768 - val_smape: 1.3561

Epoch 4/256

4584/4584 - 76s - 17ms/step - ia: 0.6482 - loss: 0.3661 - mae: 0.4821 - rmse: 0.5864 - smape: 0.8418 - val_ia: 0.1370 - val_loss: 1.0658 - val_mae: 0.8511 - val_rmse: 0.8696 - val_smape: 1.2515

Epoch 5/256

4584/4584 - 66s - 14ms/step - ia: 0.6640 - loss: 0.3424 - mae: 0.4657 - rmse: 0.5674 - smape: 0.8164 - val_ia: 0.1483 - val_loss: 0.9412 - val_mae: 0.7870 - val_rmse: 0.8073 - val_smape: 1.1835

Epoch 6/256

4584/4584 - 79s - 17ms/step - ia: 0.6723 - loss: 0.3273 - mae: 0.4547 - rmse: 0.5547 - smape: 0.7996 - val_ia: 0.1516 - val_loss: 0.8421 - val_mae: 0.7466 - val_rmse: 0.7670 - val_smape: 1.1726

Epoch 7/256

4584/4584 - 73s - 16ms/step - ia: 0.6795 - loss: 0.3155 - mae: 0.4459 - rmse: 0.5444 - smape: 0.7884 - val_ia: 0.1504 - val_loss: 0.8691 - val_mae: 0.7613 - val_rmse: 0.7814 - val_smape: 1.1795

Epoch 8/256

4584/4584 - 66s - 14ms/step - ia: 0.6859 - loss: 0.3042 - mae: 0.4372 - rmse: 0.5344 - smape: 0.7798 - val_ia: 0.1569 - val_loss: 0.7639 - val_mae: 0.7057 - val_rmse: 0.7272 - val_smape: 1.1357

Epoch 9/256

4584/4584 - 71s - 16ms/step - ia: 0.6928 - loss: 0.2939 - mae: 0.4295 - rmse: 0.5244 - smape: 0.7717 - val_ia: 0.1584 - val_loss: 0.7051 - val_mae: 0.6779 - val_rmse: 0.6996 - val_smape: 1.1180

Epoch 10/256

4584/4584 - 81s - 18ms/step - ia: 0.6973 - loss: 0.2840 - mae: 0.4217 - rmse: 0.5155 - smape: 0.7645 - val_ia: 0.1578 - val_loss: 0.6952 - val_mae: 0.6767 - val_rmse: 0.6977 - val_smape: 1.1141

Epoch 11/256

4584/4584 - 62s - 13ms/step - ia: 0.7044 - loss: 0.2743 - mae: 0.4136 - rmse: 0.5066 - smape: 0.7559 - val_ia: 0.1579 - val_loss: 0.6987 - val_mae: 0.6801 - val_rmse: 0.7002 - val_smape: 1.1163

Epoch 12/256

4584/4584 - 66s - 14ms/step - ia: 0.7111 - loss: 0.2636 - mae: 0.4044 - rmse: 0.4954 - smape: 0.7477 - val_ia: 0.1623 - val_loss: 0.5844 - val_mae: 0.6225 - val_rmse: 0.6427 - val_smape: 1.0751

Epoch 13/256

4584/4584 - 71s - 16ms/step - ia: 0.7181 - loss: 0.2526 - mae: 0.3948 - rmse: 0.4848 - smape: 0.7397 - val_ia: 0.1595 - val_loss: 0.6075 - val_mae: 0.6366 - val_rmse: 0.6556 - val_smape: 1.0754

Epoch 14/256

4584/4584 - 79s - 17ms/step - ia: 0.7270 - loss: 0.2401 - mae: 0.3833 - rmse: 0.4721 - smape: 0.7299 - val_ia: 0.1604 - val_loss: 0.5851 - val_mae: 0.6239 - val_rmse: 0.6422 - val_smape: 1.0614

Epoch 15/256

4584/4584 - 68s - 15ms/step - ia: 0.7383 - loss: 0.2244 - mae: 0.3682 - rmse: 0.4552 - smape: 0.7168 - val_ia: 0.1599 - val_loss: 0.6396 - val_mae: 0.6554 - val_rmse: 0.6720 - val_smape: 1.0625

Epoch 16/256

4584/4584 - 67s - 15ms/step - ia: 0.7489 - loss: 0.2080 - mae: 0.3523 - rmse: 0.4371 - smape: 0.7044 - val_ia: 0.1758 - val_loss: 0.4774 - val_mae: 0.5605 - val_rmse: 0.5774 - val_smape: 0.9636

Epoch 17/256

4584/4584 - 71s - 15ms/step - ia: 0.7612 - loss: 0.1916 - mae: 0.3352 - rmse: 0.4180 - smape: 0.6889 - val_ia: 0.1830 - val_loss: 0.4561 - val_mae: 0.5436 - val_rmse: 0.5604 - val_smape: 0.9430

Epoch 18/256

4584/4584 - 67s - 15ms/step - ia: 0.7730 - loss: 0.1754 - mae: 0.3175 - rmse: 0.3985 - smape: 0.6711 - val_ia: 0.1846 - val_loss: 0.4670 - val_mae: 0.5450 - val_rmse: 0.5617 - val_smape: 0.9459

Epoch 19/256

4584/4584 - 72s - 16ms/step - ia: 0.7824 - loss: 0.1611 - mae: 0.3018 - rmse: 0.3808 - smape: 0.6551 - val_ia: 0.1947 - val_loss: 0.3787 - val_mae: 0.4928 - val_rmse: 0.5092 - val_smape: 0.9037

Epoch 20/256

4584/4584 - 82s - 18ms/step - ia: 0.7936 - loss: 0.1483 - mae: 0.2880 - rmse: 0.3648 - smape: 0.6401 - val_ia: 0.2105 - val_loss: 0.3966 - val_mae: 0.4946 - val_rmse: 0.5108 - val_smape: 0.8772

Epoch 21/256

4584/4584 - 71s - 15ms/step - ia: 0.8022 - loss: 0.1374 - mae: 0.2755 - rmse: 0.3502 - smape: 0.6234 - val_ia: 0.2149 - val_loss: 0.3393 - val_mae: 0.4598 - val_rmse: 0.4764 - val_smape: 0.8504

Epoch 22/256

4584/4584 - 66s - 14ms/step - ia: 0.8110 - loss: 0.1287 - mae: 0.2658 - rmse: 0.3385 - smape: 0.6121 - val_ia: 0.2261 - val_loss: 0.3208 - val_mae: 0.4451 - val_rmse: 0.4615 - val_smape: 0.8372

Epoch 23/256

4584/4584 - 68s - 15ms/step - ia: 0.8160 - loss: 0.1215 - mae: 0.2570 - rmse: 0.3279 - smape: 0.6000 - val_ia: 0.2308 - val_loss: 0.2721 - val_mae: 0.4127 - val_rmse: 0.4294 - val_smape: 0.8116

Epoch 24/256

4584/4584 - 97s - 21ms/step - ia: 0.8201 - loss: 0.1161 - mae: 0.2505 - rmse: 0.3201 - smape: 0.5904 - val_ia: 0.2288 - val_loss: 0.2049 - val_mae: 0.3688 - val_rmse: 0.3855 - val_smape: 0.8010

Epoch 25/256

4584/4584 - 86s - 19ms/step - ia: 0.8253 - loss: 0.1117 - mae: 0.2444 - rmse: 0.3131 - smape: 0.5821 - val_ia: 0.2352 - val_loss: 0.2817 - val_mae: 0.4151 - val_rmse: 0.4314 - val_smape: 0.8062

Epoch 26/256

4584/4584 - 82s - 18ms/step - ia: 0.8277 - loss: 0.1093 - mae: 0.2411 - rmse: 0.3095 - smape: 0.5770 - val_ia: 0.2382 - val_loss: 0.2150 - val_mae: 0.3681 - val_rmse: 0.3846 - val_smape: 0.7618

Epoch 27/256

4584/4584 - 90s - 20ms/step - ia: 0.8301 - loss: 0.1069 - mae: 0.2381 - rmse: 0.3057 - smape: 0.5734 - val_ia: 0.2416 - val_loss: 0.2303 - val_mae: 0.3769 - val_rmse: 0.3929 - val_smape: 0.7588

Epoch 28/256

4584/4584 - 77s - 17ms/step - ia: 0.8319 - loss: 0.1046 - mae: 0.2354 - rmse: 0.3024 - smape: 0.5689 - val_ia: 0.2476 - val_loss: 0.1827 - val_mae: 0.3401 - val_rmse: 0.3562 - val_smape: 0.7189

Epoch 29/256

4584/4584 - 72s - 16ms/step - ia: 0.8335 - loss: 0.1030 - mae: 0.2330 - rmse: 0.2996 - smape: 0.5642 - val_ia: 0.2505 - val_loss: 0.1984 - val_mae: 0.3509 - val_rmse: 0.3670 - val_smape: 0.7252

Epoch 30/256

4584/4584 - 75s - 16ms/step - ia: 0.8347 - loss: 0.1018 - mae: 0.2316 - rmse: 0.2982 - smape: 0.5638 - val_ia: 0.2473 - val_loss: 0.1744 - val_mae: 0.3327 - val_rmse: 0.3485 - val_smape: 0.7080

Epoch 31/256

4584/4584 - 67s - 15ms/step - ia: 0.8368 - loss: 0.1003 - mae: 0.2298 - rmse: 0.2958 - smape: 0.5605 - val_ia: 0.2532 - val_loss: 0.1960 - val_mae: 0.3487 - val_rmse: 0.3644 - val_smape: 0.7167

Epoch 32/256

4584/4584 - 70s - 15ms/step - ia: 0.8376 - loss: 0.0994 - mae: 0.2291 - rmse: 0.2954 - smape: 0.5610 - val_ia: 0.2569 - val_loss: 0.1820 - val_mae: 0.3364 - val_rmse: 0.3516 - val_smape: 0.7033

Epoch 33/256

4584/4584 - 75s - 16ms/step - ia: 0.8383 - loss: 0.0981 - mae: 0.2272 - rmse: 0.2934 - smape: 0.5563 - val_ia: 0.2590 - val_loss: 0.1680 - val_mae: 0.3239 - val_rmse: 0.3392 - val_smape: 0.6856

Epoch 34/256

4584/4584 - 97s - 21ms/step - ia: 0.8380 - loss: 0.0975 - mae: 0.2268 - rmse: 0.2919 - smape: 0.5570 - val_ia: 0.2523 - val_loss: 0.1996 - val_mae: 0.3537 - val_rmse: 0.3686 - val_smape: 0.7317

Epoch 35/256

4584/4584 - 69s - 15ms/step - ia: 0.8390 - loss: 0.0964 - mae: 0.2254 - rmse: 0.2906 - smape: 0.5572 - val_ia: 0.2514 - val_loss: 0.1899 - val_mae: 0.3491 - val_rmse: 0.3641 - val_smape: 0.7294

Epoch 36/256

4584/4584 - 86s - 19ms/step - ia: 0.8403 - loss: 0.0955 - mae: 0.2241 - rmse: 0.2891 - smape: 0.5549 - val_ia: 0.2478 - val_loss: 0.2003 - val_mae: 0.3573 - val_rmse: 0.3725 - val_smape: 0.7416

Epoch 37/256

4584/4584 - 78s - 17ms/step - ia: 0.8414 - loss: 0.0945 - mae: 0.2230 - rmse: 0.2876 - smape: 0.5537 - val_ia: 0.2684 - val_loss: 0.1654 - val_mae: 0.3220 - val_rmse: 0.3372 - val_smape: 0.6853

Epoch 38/256

4584/4584 - 76s - 17ms/step - ia: 0.8412 - loss: 0.0937 - mae: 0.2222 - rmse: 0.2869 - smape: 0.5524 - val_ia: 0.2582 - val_loss: 0.1829 - val_mae: 0.3352 - val_rmse: 0.3509 - val_smape: 0.6943

Epoch 39/256

4584/4584 - 90s - 20ms/step - ia: 0.8413 - loss: 0.0933 - mae: 0.2217 - rmse: 0.2859 - smape: 0.5519 - val_ia: 0.2565 - val_loss: 0.1879 - val_mae: 0.3440 - val_rmse: 0.3596 - val_smape: 0.7153

Epoch 40/256

4584/4584 - 136s - 30ms/step - ia: 0.8434 - loss: 0.0923 - mae: 0.2201 - rmse: 0.2847 - smape: 0.5470 - val_ia: 0.2430 - val_loss: 0.2045 - val_mae: 0.3631 - val_rmse: 0.3781 - val_smape: 0.7523

Epoch 41/256

4584/4584 - 83s - 18ms/step - ia: 0.8433 - loss: 0.0920 - mae: 0.2201 - rmse: 0.2839 - smape: 0.5480 - val_ia: 0.2672 - val_loss: 0.1643 - val_mae: 0.3200 - val_rmse: 0.3354 - val_smape: 0.6809

Epoch 42/256

4584/4584 - 93s - 20ms/step - ia: 0.8436 - loss: 0.0913 - mae: 0.2191 - rmse: 0.2829 - smape: 0.5492 - val_ia: 0.2704 - val_loss: 0.1575 - val_mae: 0.3174 - val_rmse: 0.3324 - val_smape: 0.6880

Epoch 43/256

4584/4584 - 86s - 19ms/step - ia: 0.8456 - loss: 0.0902 - mae: 0.2176 - rmse: 0.2815 - smape: 0.5421 - val_ia: 0.2720 - val_loss: 0.1611 - val_mae: 0.3191 - val_rmse: 0.3344 - val_smape: 0.6849

Epoch 44/256

4584/4584 - 96s - 21ms/step - ia: 0.8458 - loss: 0.0898 - mae: 0.2175 - rmse: 0.2809 - smape: 0.5437 - val_ia: 0.2680 - val_loss: 0.1515 - val_mae: 0.3077 - val_rmse: 0.3233 - val_smape: 0.6625

Epoch 45/256

4584/4584 - 101s - 22ms/step - ia: 0.8460 - loss: 0.0892 - mae: 0.2162 - rmse: 0.2799 - smape: 0.5413 - val_ia: 0.2641 - val_loss: 0.1733 - val_mae: 0.3332 - val_rmse: 0.3487 - val_smape: 0.7112

Epoch 46/256

4584/4584 - 107s - 23ms/step - ia: 0.8460 - loss: 0.0890 - mae: 0.2163 - rmse: 0.2796 - smape: 0.5410 - val_ia: 0.2648 - val_loss: 0.1703 - val_mae: 0.3280 - val_rmse: 0.3434 - val_smape: 0.6976

Epoch 47/256

4584/4584 - 95s - 21ms/step - ia: 0.8471 - loss: 0.0878 - mae: 0.2149 - rmse: 0.2781 - smape: 0.5406 - val_ia: 0.2542 - val_loss: 0.1845 - val_mae: 0.3454 - val_rmse: 0.3607 - val_smape: 0.7331

Epoch 48/256

4584/4584 - 80s - 17ms/step - ia: 0.8469 - loss: 0.0875 - mae: 0.2148 - rmse: 0.2777 - smape: 0.5393 - val_ia: 0.2541 - val_loss: 0.1864 - val_mae: 0.3460 - val_rmse: 0.3614 - val_smape: 0.7342

Epoch 49/256

4584/4584 - 73s - 16ms/step - ia: 0.8475 - loss: 0.0870 - mae: 0.2138 - rmse: 0.2764 - smape: 0.5370 - val_ia: 0.2402 - val_loss: 0.2082 - val_mae: 0.3707 - val_rmse: 0.3860 - val_smape: 0.7652

Epoch 50/256

4584/4584 - 71s - 15ms/step - ia: 0.8484 - loss: 0.0865 - mae: 0.2135 - rmse: 0.2758 - smape: 0.5374 - val_ia: 0.2628 - val_loss: 0.1766 - val_mae: 0.3341 - val_rmse: 0.3493 - val_smape: 0.7057

Epoch 51/256

4584/4584 - 74s - 16ms/step - ia: 0.8495 - loss: 0.0856 - mae: 0.2118 - rmse: 0.2744 - smape: 0.5338 - val_ia: 0.2654 - val_loss: 0.1664 - val_mae: 0.3245 - val_rmse: 0.3403 - val_smape: 0.6979

Epoch 52/256

4584/4584 - 62s - 13ms/step - ia: 0.8491 - loss: 0.0852 - mae: 0.2118 - rmse: 0.2741 - smape: 0.5347 - val_ia: 0.2471 - val_loss: 0.1935 - val_mae: 0.3548 - val_rmse: 0.3705 - val_smape: 0.7455

Epoch 53/256

4584/4584 - 62s - 13ms/step - ia: 0.8506 - loss: 0.0845 - mae: 0.2112 - rmse: 0.2733 - smape: 0.5311 - val_ia: 0.2800 - val_loss: 0.1455 - val_mae: 0.3011 - val_rmse: 0.3171 - val_smape: 0.6551

Epoch 54/256

4584/4584 - 58s - 13ms/step - ia: 0.8498 - loss: 0.0843 - mae: 0.2109 - rmse: 0.2724 - smape: 0.5327 - val_ia: 0.2415 - val_loss: 0.2074 - val_mae: 0.3675 - val_rmse: 0.3835 - val_smape: 0.7568

Epoch 55/256

4584/4584 - 56s - 12ms/step - ia: 0.8511 - loss: 0.0833 - mae: 0.2093 - rmse: 0.2708 - smape: 0.5281 - val_ia: 0.2637 - val_loss: 0.1664 - val_mae: 0.3268 - val_rmse: 0.3426 - val_smape: 0.7087

Epoch 56/256

4584/4584 - 60s - 13ms/step - ia: 0.8504 - loss: 0.0834 - mae: 0.2097 - rmse: 0.2715 - smape: 0.5290 - val_ia: 0.2539 - val_loss: 0.1784 - val_mae: 0.3399 - val_rmse: 0.3560 - val_smape: 0.7240

Epoch 57/256

4584/4584 - 56s - 12ms/step - ia: 0.8518 - loss: 0.0826 - mae: 0.2090 - rmse: 0.2700 - smape: 0.5282 - val_ia: 0.2825 - val_loss: 0.1436 - val_mae: 0.2995 - val_rmse: 0.3156 - val_smape: 0.6591

Epoch 58/256

4584/4584 - 59s - 13ms/step - ia: 0.8515 - loss: 0.0821 - mae: 0.2080 - rmse: 0.2689 - smape: 0.5249 - val_ia: 0.2571 - val_loss: 0.1773 - val_mae: 0.3378 - val_rmse: 0.3542 - val_smape: 0.7223

Epoch 59/256

4584/4584 - 58s - 13ms/step - ia: 0.8528 - loss: 0.0816 - mae: 0.2072 - rmse: 0.2681 - smape: 0.5241 - val_ia: 0.2758 - val_loss: 0.1532 - val_mae: 0.3109 - val_rmse: 0.3270 - val_smape: 0.6853

Epoch 60/256

4584/4584 - 58s - 13ms/step - ia: 0.8523 - loss: 0.0809 - mae: 0.2067 - rmse: 0.2671 - smape: 0.5217 - val_ia: 0.2646 - val_loss: 0.1691 - val_mae: 0.3270 - val_rmse: 0.3434 - val_smape: 0.7064

Epoch 61/256

4584/4584 - 57s - 12ms/step - ia: 0.8532 - loss: 0.0806 - mae: 0.2066 - rmse: 0.2667 - smape: 0.5239 - val_ia: 0.2344 - val_loss: 0.2120 - val_mae: 0.3754 - val_rmse: 0.3915 - val_smape: 0.7651

Epoch 62/256

4584/4584 - 56s - 12ms/step - ia: 0.8538 - loss: 0.0802 - mae: 0.2065 - rmse: 0.2665 - smape: 0.5244 - val_ia: 0.2826 - val_loss: 0.1399 - val_mae: 0.2960 - val_rmse: 0.3121 - val_smape: 0.6570

Epoch 63/256

4584/4584 - 59s - 13ms/step - ia: 0.8536 - loss: 0.0798 - mae: 0.2058 - rmse: 0.2658 - smape: 0.5207 - val_ia: 0.2307 - val_loss: 0.2200 - val_mae: 0.3808 - val_rmse: 0.3970 - val_smape: 0.7722

Epoch 64/256

4584/4584 - 58s - 13ms/step - ia: 0.8537 - loss: 0.0795 - mae: 0.2054 - rmse: 0.2652 - smape: 0.5205 - val_ia: 0.2688 - val_loss: 0.1628 - val_mae: 0.3186 - val_rmse: 0.3355 - val_smape: 0.6899

Epoch 65/256

4584/4584 - 83s - 18ms/step - ia: 0.8540 - loss: 0.0790 - mae: 0.2050 - rmse: 0.2645 - smape: 0.5194 - val_ia: 0.2687 - val_loss: 0.1583 - val_mae: 0.3169 - val_rmse: 0.3332 - val_smape: 0.6989

Epoch 66/256

4584/4584 - 59s - 13ms/step - ia: 0.8547 - loss: 0.0789 - mae: 0.2049 - rmse: 0.2641 - smape: 0.5182 - val_ia: 0.2393 - val_loss: 0.2093 - val_mae: 0.3686 - val_rmse: 0.3847 - val_smape: 0.7595

Epoch 67/256

4584/4584 - 60s - 13ms/step - ia: 0.8556 - loss: 0.0781 - mae: 0.2036 - rmse: 0.2629 - smape: 0.5163 - val_ia: 0.2807 - val_loss: 0.1326 - val_mae: 0.2870 - val_rmse: 0.3039 - val_smape: 0.6405

Epoch 68/256

4584/4584 - 59s - 13ms/step - ia: 0.8551 - loss: 0.0779 - mae: 0.2033 - rmse: 0.2624 - smape: 0.5143 - val_ia: 0.2517 - val_loss: 0.1866 - val_mae: 0.3452 - val_rmse: 0.3622 - val_smape: 0.7305

Epoch 69/256

4584/4584 - 74s - 16ms/step - ia: 0.8557 - loss: 0.0779 - mae: 0.2035 - rmse: 0.2623 - smape: 0.5137 - val_ia: 0.2596 - val_loss: 0.1712 - val_mae: 0.3312 - val_rmse: 0.3476 - val_smape: 0.7118

Epoch 70/256

4584/4584 - 76s - 17ms/step - ia: 0.8556 - loss: 0.0774 - mae: 0.2025 - rmse: 0.2612 - smape: 0.5138 - val_ia: 0.2821 - val_loss: 0.1523 - val_mae: 0.3064 - val_rmse: 0.3237 - val_smape: 0.6796

Epoch 71/256

4584/4584 - 69s - 15ms/step - ia: 0.8562 - loss: 0.0768 - mae: 0.2022 - rmse: 0.2608 - smape: 0.5130 - val_ia: 0.2730 - val_loss: 0.1632 - val_mae: 0.3182 - val_rmse: 0.3354 - val_smape: 0.6918

Epoch 72/256

4584/4584 - 74s - 16ms/step - ia: 0.8566 - loss: 0.0765 - mae: 0.2021 - rmse: 0.2602 - smape: 0.5123 - val_ia: 0.2663 - val_loss: 0.1746 - val_mae: 0.3311 - val_rmse: 0.3488 - val_smape: 0.7112

Epoch 73/256

4584/4584 - 73s - 16ms/step - ia: 0.8571 - loss: 0.0764 - mae: 0.2014 - rmse: 0.2593 - smape: 0.5102 - val_ia: 0.2781 - val_loss: 0.1647 - val_mae: 0.3175 - val_rmse: 0.3348 - val_smape: 0.6952

Epoch 74/256

4584/4584 - 74s - 16ms/step - ia: 0.8568 - loss: 0.0761 - mae: 0.2014 - rmse: 0.2597 - smape: 0.5122 - val_ia: 0.2854 - val_loss: 0.1454 - val_mae: 0.2989 - val_rmse: 0.3165 - val_smape: 0.6616

Epoch 75/256

4584/4584 - 69s - 15ms/step - ia: 0.8573 - loss: 0.0758 - mae: 0.2010 - rmse: 0.2588 - smape: 0.5098 - val_ia: 0.2809 - val_loss: 0.1530 - val_mae: 0.3060 - val_rmse: 0.3236 - val_smape: 0.6711

Epoch 76/256

4584/4584 - 68s - 15ms/step - ia: 0.8574 - loss: 0.0753 - mae: 0.2004 - rmse: 0.2587 - smape: 0.5094 - val_ia: 0.2655 - val_loss: 0.1749 - val_mae: 0.3300 - val_rmse: 0.3479 - val_smape: 0.7026

Epoch 77/256

4584/4584 - 63s - 14ms/step - ia: 0.8585 - loss: 0.0751 - mae: 0.2003 - rmse: 0.2582 - smape: 0.5075 - val_ia: 0.2540 - val_loss: 0.1894 - val_mae: 0.3464 - val_rmse: 0.3631 - val_smape: 0.7320

Epoch 78/256

4584/4584 - 73s - 16ms/step - ia: 0.8579 - loss: 0.0748 - mae: 0.1998 - rmse: 0.2576 - smape: 0.5076 - val_ia: 0.2633 - val_loss: 0.1806 - val_mae: 0.3366 - val_rmse: 0.3542 - val_smape: 0.7134

Epoch 79/256

4584/4584 - 70s - 15ms/step - ia: 0.8580 - loss: 0.0742 - mae: 0.1990 - rmse: 0.2565 - smape: 0.5045 - val_ia: 0.2898 - val_loss: 0.1365 - val_mae: 0.2866 - val_rmse: 0.3046 - val_smape: 0.6366

Epoch 80/256

4584/4584 - 73s - 16ms/step - ia: 0.8589 - loss: 0.0741 - mae: 0.1988 - rmse: 0.2565 - smape: 0.5060 - val_ia: 0.2856 - val_loss: 0.1463 - val_mae: 0.2984 - val_rmse: 0.3164 - val_smape: 0.6632

Epoch 81/256

4584/4584 - 70s - 15ms/step - ia: 0.8599 - loss: 0.0736 - mae: 0.1983 - rmse: 0.2556 - smape: 0.5053 - val_ia: 0.2817 - val_loss: 0.1521 - val_mae: 0.3042 - val_rmse: 0.3224 - val_smape: 0.6685

Epoch 82/256

4584/4584 - 85s - 19ms/step - ia: 0.8595 - loss: 0.0733 - mae: 0.1975 - rmse: 0.2547 - smape: 0.5015 - val_ia: 0.2888 - val_loss: 0.1393 - val_mae: 0.2899 - val_rmse: 0.3081 - val_smape: 0.6448

Epoch 82: early stopping

Restoring model weights from the end of the best epoch: 67.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:53 2s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step

 54%|█████▍    | 27/50 [10:09:34<20:42:01, 3240.04s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 51s - 22ms/step - ia: 0.4553 - loss: 0.6710 - mae: 0.6630 - rmse: 0.7994 - smape: 1.2038 - val_ia: 0.1772 - val_loss: 1.3289 - val_mae: 0.9652 - val_rmse: 0.9965 - val_smape: 1.3624

Epoch 2/64

2292/2292 - 28s - 12ms/step - ia: 0.6524 - loss: 0.3957 - mae: 0.5027 - rmse: 0.6188 - smape: 0.8698 - val_ia: 0.1932 - val_loss: 1.0532 - val_mae: 0.8483 - val_rmse: 0.8801 - val_smape: 1.2582

Epoch 3/64

2292/2292 - 47s - 20ms/step - ia: 0.6826 - loss: 0.3428 - mae: 0.4669 - rmse: 0.5768 - smape: 0.8154 - val_ia: 0.2059 - val_loss: 0.8209 - val_mae: 0.7430 - val_rmse: 0.7741 - val_smape: 1.1964

Epoch 4/64

2292/2292 - 34s - 15ms/step - ia: 0.6980 - loss: 0.3164 - mae: 0.4465 - rmse: 0.5535 - smape: 0.7922 - val_ia: 0.2174 - val_loss: 0.7545 - val_mae: 0.6995 - val_rmse: 0.7311 - val_smape: 1.1344

Epoch 5/64

2292/2292 - 42s - 18ms/step - ia: 0.7105 - loss: 0.2942 - mae: 0.4293 - rmse: 0.5336 - smape: 0.7734 - val_ia: 0.2148 - val_loss: 0.6621 - val_mae: 0.6507 - val_rmse: 0.6830 - val_smape: 1.0983

Epoch 6/64

2292/2292 - 34s - 15ms/step - ia: 0.7230 - loss: 0.2739 - mae: 0.4120 - rmse: 0.5143 - smape: 0.7577 - val_ia: 0.2262 - val_loss: 0.5304 - val_mae: 0.5856 - val_rmse: 0.6155 - val_smape: 1.0454

Epoch 7/64

2292/2292 - 35s - 15ms/step - ia: 0.7352 - loss: 0.2518 - mae: 0.3928 - rmse: 0.4930 - smape: 0.7472 - val_ia: 0.2328 - val_loss: 0.5341 - val_mae: 0.5881 - val_rmse: 0.6200 - val_smape: 1.0212

Epoch 8/64

2292/2292 - 29s - 13ms/step - ia: 0.7519 - loss: 0.2254 - mae: 0.3684 - rmse: 0.4655 - smape: 0.7336 - val_ia: 0.2500 - val_loss: 0.4672 - val_mae: 0.5473 - val_rmse: 0.5789 - val_smape: 1.0030

Epoch 9/64

2292/2292 - 34s - 15ms/step - ia: 0.7691 - loss: 0.1984 - mae: 0.3420 - rmse: 0.4355 - smape: 0.7187 - val_ia: 0.2655 - val_loss: 0.3767 - val_mae: 0.4907 - val_rmse: 0.5224 - val_smape: 0.9380

Epoch 10/64

2292/2292 - 34s - 15ms/step - ia: 0.7803 - loss: 0.1806 - mae: 0.3235 - rmse: 0.4152 - smape: 0.7031 - val_ia: 0.2655 - val_loss: 0.4001 - val_mae: 0.5019 - val_rmse: 0.5349 - val_smape: 0.9300

Epoch 11/64

2292/2292 - 41s - 18ms/step - ia: 0.7876 - loss: 0.1699 - mae: 0.3124 - rmse: 0.4024 - smape: 0.6895 - val_ia: 0.2814 - val_loss: 0.2967 - val_mae: 0.4415 - val_rmse: 0.4732 - val_smape: 0.8770

Epoch 12/64

2292/2292 - 29s - 13ms/step - ia: 0.7924 - loss: 0.1633 - mae: 0.3065 - rmse: 0.3945 - smape: 0.6819 - val_ia: 0.2885 - val_loss: 0.2818 - val_mae: 0.4310 - val_rmse: 0.4608 - val_smape: 0.8502

Epoch 13/64

2292/2292 - 47s - 20ms/step - ia: 0.7964 - loss: 0.1577 - mae: 0.3000 - rmse: 0.3875 - smape: 0.6707 - val_ia: 0.2934 - val_loss: 0.2425 - val_mae: 0.4032 - val_rmse: 0.4356 - val_smape: 0.8335

Epoch 14/64

2292/2292 - 41s - 18ms/step - ia: 0.8003 - loss: 0.1533 - mae: 0.2948 - rmse: 0.3817 - smape: 0.6606 - val_ia: 0.3046 - val_loss: 0.2152 - val_mae: 0.3822 - val_rmse: 0.4137 - val_smape: 0.7975

Epoch 15/64

2292/2292 - 42s - 18ms/step - ia: 0.8018 - loss: 0.1502 - mae: 0.2917 - rmse: 0.3781 - smape: 0.6563 - val_ia: 0.2955 - val_loss: 0.2504 - val_mae: 0.4069 - val_rmse: 0.4387 - val_smape: 0.8194

Epoch 16/64

2292/2292 - 41s - 18ms/step - ia: 0.8043 - loss: 0.1476 - mae: 0.2886 - rmse: 0.3744 - smape: 0.6502 - val_ia: 0.3184 - val_loss: 0.1834 - val_mae: 0.3552 - val_rmse: 0.3843 - val_smape: 0.7745

Epoch 17/64

2292/2292 - 41s - 18ms/step - ia: 0.8066 - loss: 0.1447 - mae: 0.2855 - rmse: 0.3706 - smape: 0.6461 - val_ia: 0.3009 - val_loss: 0.2435 - val_mae: 0.4003 - val_rmse: 0.4333 - val_smape: 0.7982

Epoch 18/64

2292/2292 - 34s - 15ms/step - ia: 0.8093 - loss: 0.1423 - mae: 0.2828 - rmse: 0.3673 - smape: 0.6408 - val_ia: 0.3156 - val_loss: 0.2119 - val_mae: 0.3740 - val_rmse: 0.4063 - val_smape: 0.7759

Epoch 19/64

2292/2292 - 35s - 15ms/step - ia: 0.8115 - loss: 0.1395 - mae: 0.2799 - rmse: 0.3635 - smape: 0.6370 - val_ia: 0.3194 - val_loss: 0.1922 - val_mae: 0.3600 - val_rmse: 0.3912 - val_smape: 0.7681

Epoch 20/64

2292/2292 - 34s - 15ms/step - ia: 0.8133 - loss: 0.1366 - mae: 0.2765 - rmse: 0.3602 - smape: 0.6309 - val_ia: 0.3149 - val_loss: 0.1951 - val_mae: 0.3644 - val_rmse: 0.3961 - val_smape: 0.7747

Epoch 21/64

2292/2292 - 41s - 18ms/step - ia: 0.8174 - loss: 0.1316 - mae: 0.2715 - rmse: 0.3534 - smape: 0.6252 - val_ia: 0.3078 - val_loss: 0.2134 - val_mae: 0.3777 - val_rmse: 0.4112 - val_smape: 0.7949

Epoch 22/64

2292/2292 - 30s - 13ms/step - ia: 0.8199 - loss: 0.1277 - mae: 0.2679 - rmse: 0.3479 - smape: 0.6208 - val_ia: 0.3177 - val_loss: 0.2118 - val_mae: 0.3725 - val_rmse: 0.4040 - val_smape: 0.7851

Epoch 23/64

2292/2292 - 38s - 16ms/step - ia: 0.8243 - loss: 0.1228 - mae: 0.2618 - rmse: 0.3408 - smape: 0.6180 - val_ia: 0.3076 - val_loss: 0.2329 - val_mae: 0.3888 - val_rmse: 0.4219 - val_smape: 0.7952

Epoch 24/64

2292/2292 - 48s - 21ms/step - ia: 0.8287 - loss: 0.1168 - mae: 0.2557 - rmse: 0.3322 - smape: 0.6155 - val_ia: 0.3157 - val_loss: 0.2050 - val_mae: 0.3671 - val_rmse: 0.3998 - val_smape: 0.7943

Epoch 25/64

2292/2292 - 34s - 15ms/step - ia: 0.8324 - loss: 0.1134 - mae: 0.2508 - rmse: 0.3272 - smape: 0.6134 - val_ia: 0.3068 - val_loss: 0.1998 - val_mae: 0.3661 - val_rmse: 0.3992 - val_smape: 0.8051

Epoch 26/64

2292/2292 - 30s - 13ms/step - ia: 0.8346 - loss: 0.1108 - mae: 0.2476 - rmse: 0.3233 - smape: 0.6100 - val_ia: 0.3232 - val_loss: 0.1923 - val_mae: 0.3539 - val_rmse: 0.3874 - val_smape: 0.7688

Epoch 27/64

2292/2292 - 35s - 15ms/step - ia: 0.8373 - loss: 0.1084 - mae: 0.2444 - rmse: 0.3197 - smape: 0.6064 - val_ia: 0.3462 - val_loss: 0.1549 - val_mae: 0.3230 - val_rmse: 0.3517 - val_smape: 0.7352

Epoch 28/64

2292/2292 - 39s - 17ms/step - ia: 0.8384 - loss: 0.1072 - mae: 0.2428 - rmse: 0.3176 - smape: 0.6034 - val_ia: 0.3109 - val_loss: 0.2071 - val_mae: 0.3660 - val_rmse: 0.4021 - val_smape: 0.7953

Epoch 29/64

2292/2292 - 30s - 13ms/step - ia: 0.8392 - loss: 0.1057 - mae: 0.2413 - rmse: 0.3156 - smape: 0.6039 - val_ia: 0.3178 - val_loss: 0.2046 - val_mae: 0.3614 - val_rmse: 0.3973 - val_smape: 0.7796

Epoch 30/64

2292/2292 - 45s - 20ms/step - ia: 0.8401 - loss: 0.1053 - mae: 0.2402 - rmse: 0.3140 - smape: 0.5998 - val_ia: 0.3182 - val_loss: 0.1986 - val_mae: 0.3570 - val_rmse: 0.3930 - val_smape: 0.7704

Epoch 31/64

2292/2292 - 33s - 15ms/step - ia: 0.8412 - loss: 0.1037 - mae: 0.2384 - rmse: 0.3115 - smape: 0.5947 - val_ia: 0.3221 - val_loss: 0.2318 - val_mae: 0.3779 - val_rmse: 0.4138 - val_smape: 0.7690

Epoch 32/64

2292/2292 - 33s - 14ms/step - ia: 0.8421 - loss: 0.1027 - mae: 0.2368 - rmse: 0.3107 - smape: 0.5923 - val_ia: 0.3580 - val_loss: 0.1398 - val_mae: 0.3059 - val_rmse: 0.3334 - val_smape: 0.7140

Epoch 33/64

2292/2292 - 29s - 13ms/step - ia: 0.8428 - loss: 0.1025 - mae: 0.2362 - rmse: 0.3099 - smape: 0.5903 - val_ia: 0.3446 - val_loss: 0.1589 - val_mae: 0.3226 - val_rmse: 0.3544 - val_smape: 0.7288

Epoch 34/64

2292/2292 - 29s - 12ms/step - ia: 0.8450 - loss: 0.1002 - mae: 0.2333 - rmse: 0.3064 - smape: 0.5843 - val_ia: 0.3411 - val_loss: 0.1682 - val_mae: 0.3310 - val_rmse: 0.3625 - val_smape: 0.7416

Epoch 35/64

2292/2292 - 35s - 15ms/step - ia: 0.8449 - loss: 0.1002 - mae: 0.2337 - rmse: 0.3071 - smape: 0.5849 - val_ia: 0.3391 - val_loss: 0.1983 - val_mae: 0.3525 - val_rmse: 0.3852 - val_smape: 0.7398

Epoch 36/64

2292/2292 - 35s - 15ms/step - ia: 0.8445 - loss: 0.0998 - mae: 0.2335 - rmse: 0.3060 - smape: 0.5852 - val_ia: 0.3282 - val_loss: 0.2029 - val_mae: 0.3571 - val_rmse: 0.3920 - val_smape: 0.7493

Epoch 37/64

2292/2292 - 40s - 18ms/step - ia: 0.8458 - loss: 0.0985 - mae: 0.2314 - rmse: 0.3038 - smape: 0.5818 - val_ia: 0.3561 - val_loss: 0.1648 - val_mae: 0.3253 - val_rmse: 0.3544 - val_smape: 0.7154

Epoch 38/64

2292/2292 - 35s - 15ms/step - ia: 0.8468 - loss: 0.0979 - mae: 0.2304 - rmse: 0.3030 - smape: 0.5782 - val_ia: 0.3489 - val_loss: 0.1733 - val_mae: 0.3308 - val_rmse: 0.3633 - val_smape: 0.7235

Epoch 39/64

2292/2292 - 29s - 13ms/step - ia: 0.8472 - loss: 0.0973 - mae: 0.2299 - rmse: 0.3021 - smape: 0.5785 - val_ia: 0.3442 - val_loss: 0.1917 - val_mae: 0.3483 - val_rmse: 0.3811 - val_smape: 0.7380

Epoch 40/64

2292/2292 - 34s - 15ms/step - ia: 0.8485 - loss: 0.0961 - mae: 0.2280 - rmse: 0.3000 - smape: 0.5732 - val_ia: 0.3481 - val_loss: 0.1676 - val_mae: 0.3246 - val_rmse: 0.3573 - val_smape: 0.7189

Epoch 41/64

2292/2292 - 34s - 15ms/step - ia: 0.8488 - loss: 0.0957 - mae: 0.2278 - rmse: 0.2996 - smape: 0.5738 - val_ia: 0.3653 - val_loss: 0.1530 - val_mae: 0.3123 - val_rmse: 0.3429 - val_smape: 0.6969

Epoch 42/64

2292/2292 - 35s - 15ms/step - ia: 0.8498 - loss: 0.0946 - mae: 0.2261 - rmse: 0.2977 - smape: 0.5680 - val_ia: 0.3551 - val_loss: 0.1721 - val_mae: 0.3316 - val_rmse: 0.3622 - val_smape: 0.7184

Epoch 43/64

2292/2292 - 33s - 14ms/step - ia: 0.8498 - loss: 0.0944 - mae: 0.2263 - rmse: 0.2976 - smape: 0.5681 - val_ia: 0.3523 - val_loss: 0.1633 - val_mae: 0.3212 - val_rmse: 0.3557 - val_smape: 0.7114

Epoch 44/64

2292/2292 - 34s - 15ms/step - ia: 0.8502 - loss: 0.0930 - mae: 0.2243 - rmse: 0.2949 - smape: 0.5655 - val_ia: 0.3424 - val_loss: 0.1962 - val_mae: 0.3500 - val_rmse: 0.3824 - val_smape: 0.7367

Epoch 45/64

2292/2292 - 43s - 19ms/step - ia: 0.8513 - loss: 0.0924 - mae: 0.2235 - rmse: 0.2946 - smape: 0.5622 - val_ia: 0.3470 - val_loss: 0.1641 - val_mae: 0.3215 - val_rmse: 0.3550 - val_smape: 0.7152

Epoch 46/64

2292/2292 - 35s - 15ms/step - ia: 0.8517 - loss: 0.0922 - mae: 0.2234 - rmse: 0.2942 - smape: 0.5620 - val_ia: 0.3664 - val_loss: 0.1448 - val_mae: 0.3034 - val_rmse: 0.3346 - val_smape: 0.6862

Epoch 47/64

2292/2292 - 29s - 13ms/step - ia: 0.8521 - loss: 0.0914 - mae: 0.2226 - rmse: 0.2925 - smape: 0.5586 - val_ia: 0.3642 - val_loss: 0.1485 - val_mae: 0.3073 - val_rmse: 0.3374 - val_smape: 0.6967

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 5:18 2s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step

 56%|█████▌    | 28/50 [10:38:01<16:59:22, 2780.11s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 72s - 32ms/step - ia: 0.4464 - loss: 0.6829 - mae: 0.6680 - rmse: 0.8056 - smape: 1.2160 - val_ia: 0.1701 - val_loss: 1.4196 - val_mae: 1.0082 - val_rmse: 1.0381 - val_smape: 1.4020

Epoch 2/64

2292/2292 - 39s - 17ms/step - ia: 0.6523 - loss: 0.3976 - mae: 0.5021 - rmse: 0.6212 - smape: 0.8659 - val_ia: 0.1778 - val_loss: 1.2718 - val_mae: 0.9542 - val_rmse: 0.9840 - val_smape: 1.3587

Epoch 3/64

2292/2292 - 41s - 18ms/step - ia: 0.6819 - loss: 0.3468 - mae: 0.4671 - rmse: 0.5794 - smape: 0.8144 - val_ia: 0.2132 - val_loss: 0.7479 - val_mae: 0.6996 - val_rmse: 0.7318 - val_smape: 1.1408

Epoch 4/64

2292/2292 - 30s - 13ms/step - ia: 0.6959 - loss: 0.3229 - mae: 0.4507 - rmse: 0.5589 - smape: 0.7950 - val_ia: 0.2134 - val_loss: 0.7200 - val_mae: 0.6815 - val_rmse: 0.7134 - val_smape: 1.1348

Epoch 5/64

2292/2292 - 36s - 16ms/step - ia: 0.7071 - loss: 0.3019 - mae: 0.4339 - rmse: 0.5404 - smape: 0.7775 - val_ia: 0.2202 - val_loss: 0.5898 - val_mae: 0.6200 - val_rmse: 0.6513 - val_smape: 1.0741

Epoch 6/64

2292/2292 - 31s - 14ms/step - ia: 0.7177 - loss: 0.2830 - mae: 0.4187 - rmse: 0.5232 - smape: 0.7660 - val_ia: 0.2221 - val_loss: 0.5796 - val_mae: 0.6166 - val_rmse: 0.6464 - val_smape: 1.0858

Epoch 7/64

2292/2292 - 36s - 16ms/step - ia: 0.7292 - loss: 0.2615 - mae: 0.4014 - rmse: 0.5023 - smape: 0.7559 - val_ia: 0.2300 - val_loss: 0.5317 - val_mae: 0.5933 - val_rmse: 0.6235 - val_smape: 1.0598

Epoch 8/64

2292/2292 - 36s - 16ms/step - ia: 0.7470 - loss: 0.2330 - mae: 0.3756 - rmse: 0.4730 - smape: 0.7436 - val_ia: 0.2418 - val_loss: 0.4743 - val_mae: 0.5607 - val_rmse: 0.5919 - val_smape: 1.0211

Epoch 9/64

2292/2292 - 36s - 16ms/step - ia: 0.7674 - loss: 0.2003 - mae: 0.3445 - rmse: 0.4380 - smape: 0.7259 - val_ia: 0.2462 - val_loss: 0.5039 - val_mae: 0.5617 - val_rmse: 0.5955 - val_smape: 0.9913

Epoch 10/64

2292/2292 - 41s - 18ms/step - ia: 0.7811 - loss: 0.1789 - mae: 0.3225 - rmse: 0.4132 - smape: 0.7089 - val_ia: 0.2637 - val_loss: 0.4363 - val_mae: 0.5227 - val_rmse: 0.5547 - val_smape: 0.9495

Epoch 11/64

2292/2292 - 35s - 15ms/step - ia: 0.7895 - loss: 0.1668 - mae: 0.3098 - rmse: 0.3990 - smape: 0.6913 - val_ia: 0.2720 - val_loss: 0.3415 - val_mae: 0.4699 - val_rmse: 0.5026 - val_smape: 0.9086

Epoch 12/64

2292/2292 - 30s - 13ms/step - ia: 0.7946 - loss: 0.1594 - mae: 0.3019 - rmse: 0.3896 - smape: 0.6787 - val_ia: 0.2935 - val_loss: 0.2442 - val_mae: 0.4038 - val_rmse: 0.4353 - val_smape: 0.8301

Epoch 13/64

2292/2292 - 39s - 17ms/step - ia: 0.7981 - loss: 0.1557 - mae: 0.2976 - rmse: 0.3850 - smape: 0.6720 - val_ia: 0.2890 - val_loss: 0.2458 - val_mae: 0.4065 - val_rmse: 0.4389 - val_smape: 0.8321

Epoch 14/64

2292/2292 - 30s - 13ms/step - ia: 0.8006 - loss: 0.1518 - mae: 0.2932 - rmse: 0.3801 - smape: 0.6622 - val_ia: 0.3002 - val_loss: 0.2464 - val_mae: 0.3998 - val_rmse: 0.4318 - val_smape: 0.8243

Epoch 15/64

2292/2292 - 35s - 15ms/step - ia: 0.8044 - loss: 0.1486 - mae: 0.2894 - rmse: 0.3758 - smape: 0.6571 - val_ia: 0.3052 - val_loss: 0.2321 - val_mae: 0.3914 - val_rmse: 0.4230 - val_smape: 0.8116

Epoch 16/64

2292/2292 - 31s - 14ms/step - ia: 0.8051 - loss: 0.1465 - mae: 0.2876 - rmse: 0.3728 - smape: 0.6526 - val_ia: 0.3006 - val_loss: 0.2423 - val_mae: 0.3958 - val_rmse: 0.4307 - val_smape: 0.8175

Epoch 17/64

2292/2292 - 39s - 17ms/step - ia: 0.8079 - loss: 0.1441 - mae: 0.2849 - rmse: 0.3696 - smape: 0.6501 - val_ia: 0.3151 - val_loss: 0.2013 - val_mae: 0.3672 - val_rmse: 0.4000 - val_smape: 0.7849

Epoch 18/64

2292/2292 - 33s - 14ms/step - ia: 0.8099 - loss: 0.1420 - mae: 0.2822 - rmse: 0.3672 - smape: 0.6431 - val_ia: 0.3015 - val_loss: 0.2185 - val_mae: 0.3826 - val_rmse: 0.4156 - val_smape: 0.8089

Epoch 19/64

2292/2292 - 34s - 15ms/step - ia: 0.8112 - loss: 0.1388 - mae: 0.2791 - rmse: 0.3630 - smape: 0.6396 - val_ia: 0.3275 - val_loss: 0.1694 - val_mae: 0.3418 - val_rmse: 0.3712 - val_smape: 0.7644

Epoch 20/64

2292/2292 - 29s - 13ms/step - ia: 0.8145 - loss: 0.1350 - mae: 0.2746 - rmse: 0.3577 - smape: 0.6298 - val_ia: 0.3148 - val_loss: 0.2179 - val_mae: 0.3774 - val_rmse: 0.4093 - val_smape: 0.7830

Epoch 21/64

2292/2292 - 34s - 15ms/step - ia: 0.8178 - loss: 0.1310 - mae: 0.2706 - rmse: 0.3521 - smape: 0.6249 - val_ia: 0.2983 - val_loss: 0.2599 - val_mae: 0.4034 - val_rmse: 0.4407 - val_smape: 0.7997

Epoch 22/64

2292/2292 - 32s - 14ms/step - ia: 0.8238 - loss: 0.1235 - mae: 0.2627 - rmse: 0.3415 - smape: 0.6147 - val_ia: 0.3238 - val_loss: 0.2132 - val_mae: 0.3696 - val_rmse: 0.4033 - val_smape: 0.7760

Epoch 23/64

2292/2292 - 34s - 15ms/step - ia: 0.8297 - loss: 0.1168 - mae: 0.2552 - rmse: 0.3319 - smape: 0.6155 - val_ia: 0.3004 - val_loss: 0.2212 - val_mae: 0.3811 - val_rmse: 0.4182 - val_smape: 0.8272

Epoch 24/64

2292/2292 - 35s - 15ms/step - ia: 0.8326 - loss: 0.1135 - mae: 0.2508 - rmse: 0.3265 - smape: 0.6129 - val_ia: 0.3175 - val_loss: 0.2351 - val_mae: 0.3839 - val_rmse: 0.4168 - val_smape: 0.8010

Epoch 25/64

2292/2292 - 38s - 17ms/step - ia: 0.8354 - loss: 0.1100 - mae: 0.2462 - rmse: 0.3214 - smape: 0.6080 - val_ia: 0.3199 - val_loss: 0.1999 - val_mae: 0.3597 - val_rmse: 0.3934 - val_smape: 0.7914

Epoch 26/64

2292/2292 - 41s - 18ms/step - ia: 0.8372 - loss: 0.1084 - mae: 0.2440 - rmse: 0.3192 - smape: 0.6055 - val_ia: 0.3236 - val_loss: 0.2158 - val_mae: 0.3676 - val_rmse: 0.4015 - val_smape: 0.7672

Epoch 27/64

2292/2292 - 39s - 17ms/step - ia: 0.8389 - loss: 0.1064 - mae: 0.2412 - rmse: 0.3161 - smape: 0.5986 - val_ia: 0.3354 - val_loss: 0.1743 - val_mae: 0.3381 - val_rmse: 0.3691 - val_smape: 0.7484

Epoch 28/64

2292/2292 - 32s - 14ms/step - ia: 0.8406 - loss: 0.1045 - mae: 0.2389 - rmse: 0.3130 - smape: 0.5947 - val_ia: 0.3027 - val_loss: 0.2464 - val_mae: 0.3885 - val_rmse: 0.4270 - val_smape: 0.8045

Epoch 29/64

2292/2292 - 34s - 15ms/step - ia: 0.8411 - loss: 0.1040 - mae: 0.2383 - rmse: 0.3125 - smape: 0.5956 - val_ia: 0.3435 - val_loss: 0.1746 - val_mae: 0.3350 - val_rmse: 0.3638 - val_smape: 0.7371

Epoch 30/64

2292/2292 - 31s - 14ms/step - ia: 0.8429 - loss: 0.1023 - mae: 0.2361 - rmse: 0.3100 - smape: 0.5894 - val_ia: 0.3333 - val_loss: 0.1919 - val_mae: 0.3477 - val_rmse: 0.3828 - val_smape: 0.7404

Epoch 31/64

2292/2292 - 39s - 17ms/step - ia: 0.8437 - loss: 0.1015 - mae: 0.2350 - rmse: 0.3083 - smape: 0.5879 - val_ia: 0.3425 - val_loss: 0.1736 - val_mae: 0.3312 - val_rmse: 0.3654 - val_smape: 0.7271

Epoch 32/64

2292/2292 - 45s - 20ms/step - ia: 0.8440 - loss: 0.1005 - mae: 0.2343 - rmse: 0.3071 - smape: 0.5866 - val_ia: 0.3423 - val_loss: 0.1662 - val_mae: 0.3269 - val_rmse: 0.3594 - val_smape: 0.7220

Epoch 33/64

2292/2292 - 36s - 16ms/step - ia: 0.8452 - loss: 0.0994 - mae: 0.2321 - rmse: 0.3053 - smape: 0.5812 - val_ia: 0.3284 - val_loss: 0.2172 - val_mae: 0.3648 - val_rmse: 0.4002 - val_smape: 0.7493

Epoch 34/64

2292/2292 - 35s - 15ms/step - ia: 0.8457 - loss: 0.0989 - mae: 0.2322 - rmse: 0.3046 - smape: 0.5811 - val_ia: 0.3424 - val_loss: 0.1835 - val_mae: 0.3419 - val_rmse: 0.3729 - val_smape: 0.7326

Epoch 35/64

2292/2292 - 36s - 15ms/step - ia: 0.8473 - loss: 0.0974 - mae: 0.2299 - rmse: 0.3022 - smape: 0.5759 - val_ia: 0.3316 - val_loss: 0.1930 - val_mae: 0.3483 - val_rmse: 0.3849 - val_smape: 0.7437

Epoch 36/64

2292/2292 - 36s - 16ms/step - ia: 0.8474 - loss: 0.0971 - mae: 0.2296 - rmse: 0.3020 - smape: 0.5760 - val_ia: 0.3497 - val_loss: 0.1913 - val_mae: 0.3468 - val_rmse: 0.3777 - val_smape: 0.7303

Epoch 37/64

2292/2292 - 30s - 13ms/step - ia: 0.8482 - loss: 0.0968 - mae: 0.2289 - rmse: 0.3012 - smape: 0.5741 - val_ia: 0.3192 - val_loss: 0.2251 - val_mae: 0.3724 - val_rmse: 0.4099 - val_smape: 0.7565

Epoch 38/64

2292/2292 - 35s - 15ms/step - ia: 0.8484 - loss: 0.0963 - mae: 0.2283 - rmse: 0.3001 - smape: 0.5703 - val_ia: 0.3489 - val_loss: 0.1772 - val_mae: 0.3321 - val_rmse: 0.3655 - val_smape: 0.7188

Epoch 39/64

2292/2292 - 36s - 16ms/step - ia: 0.8491 - loss: 0.0953 - mae: 0.2268 - rmse: 0.2985 - smape: 0.5682 - val_ia: 0.3611 - val_loss: 0.1478 - val_mae: 0.3077 - val_rmse: 0.3395 - val_smape: 0.6996

Epoch 40/64

2292/2292 - 41s - 18ms/step - ia: 0.8508 - loss: 0.0936 - mae: 0.2247 - rmse: 0.2963 - smape: 0.5652 - val_ia: 0.3281 - val_loss: 0.2027 - val_mae: 0.3529 - val_rmse: 0.3895 - val_smape: 0.7408

Epoch 41/64

2292/2292 - 30s - 13ms/step - ia: 0.8499 - loss: 0.0938 - mae: 0.2254 - rmse: 0.2965 - smape: 0.5658 - val_ia: 0.3271 - val_loss: 0.2061 - val_mae: 0.3575 - val_rmse: 0.3953 - val_smape: 0.7479

Epoch 42/64

2292/2292 - 35s - 15ms/step - ia: 0.8518 - loss: 0.0922 - mae: 0.2229 - rmse: 0.2938 - smape: 0.5604 - val_ia: 0.3286 - val_loss: 0.2047 - val_mae: 0.3622 - val_rmse: 0.3958 - val_smape: 0.7479

Epoch 43/64

2292/2292 - 34s - 15ms/step - ia: 0.8522 - loss: 0.0921 - mae: 0.2232 - rmse: 0.2933 - smape: 0.5615 - val_ia: 0.3571 - val_loss: 0.1624 - val_mae: 0.3224 - val_rmse: 0.3535 - val_smape: 0.7085

Epoch 44/64

2292/2292 - 49s - 21ms/step - ia: 0.8528 - loss: 0.0915 - mae: 0.2221 - rmse: 0.2926 - smape: 0.5584 - val_ia: 0.3648 - val_loss: 0.1599 - val_mae: 0.3196 - val_rmse: 0.3496 - val_smape: 0.7019

Epoch 45/64

2292/2292 - 32s - 14ms/step - ia: 0.8531 - loss: 0.0908 - mae: 0.2212 - rmse: 0.2920 - smape: 0.5529 - val_ia: 0.3541 - val_loss: 0.1751 - val_mae: 0.3328 - val_rmse: 0.3637 - val_smape: 0.7168

Epoch 46/64

2292/2292 - 44s - 19ms/step - ia: 0.8530 - loss: 0.0909 - mae: 0.2219 - rmse: 0.2919 - smape: 0.5550 - val_ia: 0.3545 - val_loss: 0.1683 - val_mae: 0.3254 - val_rmse: 0.3577 - val_smape: 0.7133

Epoch 47/64

2292/2292 - 35s - 15ms/step - ia: 0.8538 - loss: 0.0893 - mae: 0.2197 - rmse: 0.2888 - smape: 0.5525 - val_ia: 0.3622 - val_loss: 0.1548 - val_mae: 0.3120 - val_rmse: 0.3452 - val_smape: 0.6936

Epoch 48/64

2292/2292 - 42s - 19ms/step - ia: 0.8539 - loss: 0.0895 - mae: 0.2199 - rmse: 0.2895 - smape: 0.5503 - val_ia: 0.3544 - val_loss: 0.1638 - val_mae: 0.3193 - val_rmse: 0.3543 - val_smape: 0.6979

Epoch 49/64

2292/2292 - 28s - 12ms/step - ia: 0.8551 - loss: 0.0885 - mae: 0.2186 - rmse: 0.2881 - smape: 0.5485 - val_ia: 0.3410 - val_loss: 0.1852 - val_mae: 0.3412 - val_rmse: 0.3742 - val_smape: 0.7289

Epoch 50/64

2292/2292 - 40s - 18ms/step - ia: 0.8557 - loss: 0.0878 - mae: 0.2179 - rmse: 0.2869 - smape: 0.5453 - val_ia: 0.3472 - val_loss: 0.1722 - val_mae: 0.3275 - val_rmse: 0.3613 - val_smape: 0.7126

Epoch 51/64

2292/2292 - 28s - 12ms/step - ia: 0.8561 - loss: 0.0871 - mae: 0.2171 - rmse: 0.2860 - smape: 0.5448 - val_ia: 0.3839 - val_loss: 0.1451 - val_mae: 0.2977 - val_rmse: 0.3298 - val_smape: 0.6674

Epoch 52/64

2292/2292 - 28s - 12ms/step - ia: 0.8575 - loss: 0.0861 - mae: 0.2159 - rmse: 0.2839 - smape: 0.5407 - val_ia: 0.3723 - val_loss: 0.1422 - val_mae: 0.2990 - val_rmse: 0.3305 - val_smape: 0.6743

Epoch 53/64

2292/2292 - 28s - 12ms/step - ia: 0.8575 - loss: 0.0851 - mae: 0.2149 - rmse: 0.2830 - smape: 0.5382 - val_ia: 0.3538 - val_loss: 0.1757 - val_mae: 0.3303 - val_rmse: 0.3645 - val_smape: 0.7074

Epoch 54/64

2292/2292 - 28s - 12ms/step - ia: 0.8585 - loss: 0.0843 - mae: 0.2136 - rmse: 0.2814 - smape: 0.5377 - val_ia: 0.3509 - val_loss: 0.1714 - val_mae: 0.3276 - val_rmse: 0.3608 - val_smape: 0.7071

Epoch 55/64

2292/2292 - 41s - 18ms/step - ia: 0.8586 - loss: 0.0834 - mae: 0.2130 - rmse: 0.2795 - smape: 0.5334 - val_ia: 0.3837 - val_loss: 0.1378 - val_mae: 0.2930 - val_rmse: 0.3238 - val_smape: 0.6594

Epoch 56/64

2292/2292 - 29s - 13ms/step - ia: 0.8602 - loss: 0.0826 - mae: 0.2120 - rmse: 0.2785 - smape: 0.5340 - val_ia: 0.3499 - val_loss: 0.1888 - val_mae: 0.3423 - val_rmse: 0.3754 - val_smape: 0.7147

Epoch 57/64

2292/2292 - 28s - 12ms/step - ia: 0.8604 - loss: 0.0818 - mae: 0.2113 - rmse: 0.2773 - smape: 0.5292 - val_ia: 0.3662 - val_loss: 0.1477 - val_mae: 0.3039 - val_rmse: 0.3377 - val_smape: 0.6691

Epoch 58/64

2292/2292 - 28s - 12ms/step - ia: 0.8600 - loss: 0.0819 - mae: 0.2115 - rmse: 0.2772 - smape: 0.5270 - val_ia: 0.3781 - val_loss: 0.1424 - val_mae: 0.2985 - val_rmse: 0.3285 - val_smape: 0.6663

Epoch 59/64

2292/2292 - 29s - 12ms/step - ia: 0.8614 - loss: 0.0806 - mae: 0.2100 - rmse: 0.2749 - smape: 0.5252 - val_ia: 0.3798 - val_loss: 0.1389 - val_mae: 0.2957 - val_rmse: 0.3262 - val_smape: 0.6585

Epoch 60/64

2292/2292 - 30s - 13ms/step - ia: 0.8619 - loss: 0.0798 - mae: 0.2092 - rmse: 0.2740 - smape: 0.5237 - val_ia: 0.3784 - val_loss: 0.1571 - val_mae: 0.3086 - val_rmse: 0.3395 - val_smape: 0.6693

Epoch 61/64

2292/2292 - 39s - 17ms/step - ia: 0.8629 - loss: 0.0789 - mae: 0.2080 - rmse: 0.2722 - smape: 0.5204 - val_ia: 0.3763 - val_loss: 0.1540 - val_mae: 0.3071 - val_rmse: 0.3377 - val_smape: 0.6709

Epoch 62/64

2292/2292 - 28s - 12ms/step - ia: 0.8636 - loss: 0.0780 - mae: 0.2068 - rmse: 0.2704 - smape: 0.5195 - val_ia: 0.3542 - val_loss: 0.1801 - val_mae: 0.3319 - val_rmse: 0.3689 - val_smape: 0.6981

Epoch 63/64

2292/2292 - 31s - 13ms/step - ia: 0.8644 - loss: 0.0777 - mae: 0.2063 - rmse: 0.2704 - smape: 0.5165 - val_ia: 0.3625 - val_loss: 0.1624 - val_mae: 0.3167 - val_rmse: 0.3524 - val_smape: 0.6791

Epoch 64/64

2292/2292 - 40s - 18ms/step - ia: 0.8644 - loss: 0.0763 - mae: 0.2053 - rmse: 0.2678 - smape: 0.5143 - val_ia: 0.3563 - val_loss: 0.1732 - val_mae: 0.3253 - val_rmse: 0.3626 - val_smape: 0.6895

Restoring model weights from the end of the best epoch: 55.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:04 2s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step

 58%|█████▊    | 29/50 [11:15:42<15:18:31, 2624.36s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 42s - 19ms/step - ia: 0.3247 - loss: 0.8841 - mae: 0.7752 - rmse: 0.9246 - smape: 1.4173 - val_ia: 0.1734 - val_loss: 1.3616 - val_mae: 0.9805 - val_rmse: 1.0101 - val_smape: 1.3744

Epoch 2/64

2292/2292 - 28s - 12ms/step - ia: 0.5972 - loss: 0.4943 - mae: 0.5644 - rmse: 0.6927 - smape: 0.9589 - val_ia: 0.1721 - val_loss: 1.3635 - val_mae: 0.9856 - val_rmse: 1.0154 - val_smape: 1.3910

Epoch 3/64

2292/2292 - 33s - 15ms/step - ia: 0.6454 - loss: 0.4116 - mae: 0.5113 - rmse: 0.6316 - smape: 0.8738 - val_ia: 0.1916 - val_loss: 1.0083 - val_mae: 0.8263 - val_rmse: 0.8568 - val_smape: 1.2664

Epoch 4/64

2292/2292 - 30s - 13ms/step - ia: 0.6655 - loss: 0.3737 - mae: 0.4874 - rmse: 0.6018 - smape: 0.8392 - val_ia: 0.1931 - val_loss: 0.9778 - val_mae: 0.8155 - val_rmse: 0.8454 - val_smape: 1.2697

Epoch 5/64

2292/2292 - 29s - 12ms/step - ia: 0.6822 - loss: 0.3423 - mae: 0.4652 - rmse: 0.5760 - smape: 0.8143 - val_ia: 0.2079 - val_loss: 0.8133 - val_mae: 0.7331 - val_rmse: 0.7641 - val_smape: 1.1899

Epoch 6/64

2292/2292 - 28s - 12ms/step - ia: 0.6958 - loss: 0.3185 - mae: 0.4474 - rmse: 0.5549 - smape: 0.7953 - val_ia: 0.2106 - val_loss: 0.7923 - val_mae: 0.7186 - val_rmse: 0.7501 - val_smape: 1.1786

Epoch 7/64

2292/2292 - 31s - 13ms/step - ia: 0.7060 - loss: 0.2985 - mae: 0.4328 - rmse: 0.5378 - smape: 0.7819 - val_ia: 0.2283 - val_loss: 0.6391 - val_mae: 0.6363 - val_rmse: 0.6679 - val_smape: 1.0893

Epoch 8/64

2292/2292 - 33s - 14ms/step - ia: 0.7161 - loss: 0.2818 - mae: 0.4187 - rmse: 0.5214 - smape: 0.7709 - val_ia: 0.2298 - val_loss: 0.5682 - val_mae: 0.6025 - val_rmse: 0.6338 - val_smape: 1.0598

Epoch 9/64

2292/2292 - 41s - 18ms/step - ia: 0.7268 - loss: 0.2624 - mae: 0.4032 - rmse: 0.5030 - smape: 0.7625 - val_ia: 0.2401 - val_loss: 0.5193 - val_mae: 0.5772 - val_rmse: 0.6075 - val_smape: 1.0458

Epoch 10/64

2292/2292 - 32s - 14ms/step - ia: 0.7396 - loss: 0.2420 - mae: 0.3844 - rmse: 0.4825 - smape: 0.7516 - val_ia: 0.2472 - val_loss: 0.4910 - val_mae: 0.5622 - val_rmse: 0.5942 - val_smape: 1.0338

Epoch 11/64

2292/2292 - 31s - 13ms/step - ia: 0.7519 - loss: 0.2215 - mae: 0.3659 - rmse: 0.4613 - smape: 0.7423 - val_ia: 0.2593 - val_loss: 0.4153 - val_mae: 0.5158 - val_rmse: 0.5475 - val_smape: 0.9722

Epoch 12/64

2292/2292 - 31s - 13ms/step - ia: 0.7612 - loss: 0.2069 - mae: 0.3514 - rmse: 0.4455 - smape: 0.7293 - val_ia: 0.2576 - val_loss: 0.4447 - val_mae: 0.5243 - val_rmse: 0.5590 - val_smape: 0.9609

Epoch 13/64

2292/2292 - 32s - 14ms/step - ia: 0.7690 - loss: 0.1951 - mae: 0.3402 - rmse: 0.4323 - smape: 0.7194 - val_ia: 0.2684 - val_loss: 0.3731 - val_mae: 0.4824 - val_rmse: 0.5177 - val_smape: 0.9152

Epoch 14/64

2292/2292 - 31s - 14ms/step - ia: 0.7744 - loss: 0.1864 - mae: 0.3312 - rmse: 0.4222 - smape: 0.7092 - val_ia: 0.2680 - val_loss: 0.3791 - val_mae: 0.4856 - val_rmse: 0.5220 - val_smape: 0.9142

Epoch 15/64

2292/2292 - 43s - 19ms/step - ia: 0.7771 - loss: 0.1818 - mae: 0.3271 - rmse: 0.4168 - smape: 0.7016 - val_ia: 0.2760 - val_loss: 0.3454 - val_mae: 0.4622 - val_rmse: 0.4979 - val_smape: 0.8742

Epoch 16/64

2292/2292 - 35s - 15ms/step - ia: 0.7818 - loss: 0.1757 - mae: 0.3207 - rmse: 0.4099 - smape: 0.6940 - val_ia: 0.2824 - val_loss: 0.3068 - val_mae: 0.4395 - val_rmse: 0.4749 - val_smape: 0.8506

Epoch 17/64

2292/2292 - 35s - 15ms/step - ia: 0.7837 - loss: 0.1724 - mae: 0.3180 - rmse: 0.4060 - smape: 0.6882 - val_ia: 0.2846 - val_loss: 0.2884 - val_mae: 0.4313 - val_rmse: 0.4652 - val_smape: 0.8470

Epoch 18/64

2292/2292 - 40s - 17ms/step - ia: 0.7871 - loss: 0.1682 - mae: 0.3129 - rmse: 0.4008 - smape: 0.6797 - val_ia: 0.2907 - val_loss: 0.2658 - val_mae: 0.4169 - val_rmse: 0.4506 - val_smape: 0.8390

Epoch 19/64

2292/2292 - 30s - 13ms/step - ia: 0.7885 - loss: 0.1664 - mae: 0.3117 - rmse: 0.3990 - smape: 0.6795 - val_ia: 0.2896 - val_loss: 0.2539 - val_mae: 0.4078 - val_rmse: 0.4432 - val_smape: 0.8191

Epoch 20/64

2292/2292 - 31s - 14ms/step - ia: 0.7890 - loss: 0.1655 - mae: 0.3107 - rmse: 0.3974 - smape: 0.6770 - val_ia: 0.2825 - val_loss: 0.2899 - val_mae: 0.4290 - val_rmse: 0.4677 - val_smape: 0.8304

Epoch 21/64

2292/2292 - 33s - 14ms/step - ia: 0.7912 - loss: 0.1631 - mae: 0.3076 - rmse: 0.3942 - smape: 0.6718 - val_ia: 0.2988 - val_loss: 0.2499 - val_mae: 0.4019 - val_rmse: 0.4370 - val_smape: 0.8056

Epoch 22/64

2292/2292 - 29s - 13ms/step - ia: 0.7920 - loss: 0.1614 - mae: 0.3064 - rmse: 0.3923 - smape: 0.6690 - val_ia: 0.2966 - val_loss: 0.2418 - val_mae: 0.3977 - val_rmse: 0.4325 - val_smape: 0.8033

Epoch 23/64

2292/2292 - 28s - 12ms/step - ia: 0.7930 - loss: 0.1599 - mae: 0.3046 - rmse: 0.3907 - smape: 0.6659 - val_ia: 0.2952 - val_loss: 0.2433 - val_mae: 0.3989 - val_rmse: 0.4343 - val_smape: 0.8022

Epoch 24/64

2292/2292 - 27s - 12ms/step - ia: 0.7944 - loss: 0.1593 - mae: 0.3037 - rmse: 0.3897 - smape: 0.6643 - val_ia: 0.3042 - val_loss: 0.2284 - val_mae: 0.3883 - val_rmse: 0.4209 - val_smape: 0.7940

Epoch 25/64

2292/2292 - 27s - 12ms/step - ia: 0.7942 - loss: 0.1581 - mae: 0.3027 - rmse: 0.3884 - smape: 0.6629 - val_ia: 0.3021 - val_loss: 0.2242 - val_mae: 0.3851 - val_rmse: 0.4201 - val_smape: 0.7941

Epoch 26/64

2292/2292 - 28s - 12ms/step - ia: 0.7946 - loss: 0.1573 - mae: 0.3020 - rmse: 0.3874 - smape: 0.6628 - val_ia: 0.3068 - val_loss: 0.2135 - val_mae: 0.3782 - val_rmse: 0.4113 - val_smape: 0.7912

Epoch 27/64

2292/2292 - 28s - 12ms/step - ia: 0.7952 - loss: 0.1567 - mae: 0.3014 - rmse: 0.3867 - smape: 0.6618 - val_ia: 0.3077 - val_loss: 0.2359 - val_mae: 0.3908 - val_rmse: 0.4255 - val_smape: 0.7885

Epoch 28/64

2292/2292 - 26s - 11ms/step - ia: 0.7960 - loss: 0.1559 - mae: 0.3005 - rmse: 0.3859 - smape: 0.6585 - val_ia: 0.3022 - val_loss: 0.2363 - val_mae: 0.3922 - val_rmse: 0.4263 - val_smape: 0.7963

Epoch 29/64

2292/2292 - 28s - 12ms/step - ia: 0.7972 - loss: 0.1542 - mae: 0.2986 - rmse: 0.3833 - smape: 0.6557 - val_ia: 0.3003 - val_loss: 0.2298 - val_mae: 0.3887 - val_rmse: 0.4241 - val_smape: 0.7984

Epoch 30/64

2292/2292 - 29s - 13ms/step - ia: 0.7988 - loss: 0.1528 - mae: 0.2972 - rmse: 0.3821 - smape: 0.6537 - val_ia: 0.3199 - val_loss: 0.1948 - val_mae: 0.3605 - val_rmse: 0.3929 - val_smape: 0.7638

Epoch 31/64

2292/2292 - 27s - 12ms/step - ia: 0.7979 - loss: 0.1533 - mae: 0.2980 - rmse: 0.3825 - smape: 0.6544 - val_ia: 0.3029 - val_loss: 0.2349 - val_mae: 0.3891 - val_rmse: 0.4256 - val_smape: 0.7896

Epoch 32/64

2292/2292 - 27s - 12ms/step - ia: 0.7998 - loss: 0.1517 - mae: 0.2958 - rmse: 0.3806 - smape: 0.6521 - val_ia: 0.2921 - val_loss: 0.2521 - val_mae: 0.4026 - val_rmse: 0.4399 - val_smape: 0.8060

Epoch 33/64

2292/2292 - 27s - 12ms/step - ia: 0.8003 - loss: 0.1506 - mae: 0.2946 - rmse: 0.3787 - smape: 0.6510 - val_ia: 0.3039 - val_loss: 0.2254 - val_mae: 0.3838 - val_rmse: 0.4185 - val_smape: 0.7966

Epoch 34/64

2292/2292 - 27s - 12ms/step - ia: 0.7994 - loss: 0.1508 - mae: 0.2949 - rmse: 0.3789 - smape: 0.6514 - val_ia: 0.2970 - val_loss: 0.2328 - val_mae: 0.3900 - val_rmse: 0.4265 - val_smape: 0.7947

Epoch 35/64

2292/2292 - 29s - 13ms/step - ia: 0.8013 - loss: 0.1491 - mae: 0.2934 - rmse: 0.3768 - smape: 0.6485 - val_ia: 0.2938 - val_loss: 0.2357 - val_mae: 0.3929 - val_rmse: 0.4295 - val_smape: 0.8024

Epoch 36/64

2292/2292 - 32s - 14ms/step - ia: 0.8013 - loss: 0.1489 - mae: 0.2932 - rmse: 0.3766 - smape: 0.6470 - val_ia: 0.3127 - val_loss: 0.2024 - val_mae: 0.3668 - val_rmse: 0.4006 - val_smape: 0.7713

Epoch 37/64

2292/2292 - 36s - 16ms/step - ia: 0.8023 - loss: 0.1480 - mae: 0.2920 - rmse: 0.3756 - smape: 0.6462 - val_ia: 0.3116 - val_loss: 0.2145 - val_mae: 0.3754 - val_rmse: 0.4094 - val_smape: 0.7823

Epoch 38/64

2292/2292 - 35s - 15ms/step - ia: 0.8037 - loss: 0.1459 - mae: 0.2903 - rmse: 0.3728 - smape: 0.6453 - val_ia: 0.3017 - val_loss: 0.2170 - val_mae: 0.3800 - val_rmse: 0.4139 - val_smape: 0.7918

Epoch 39/64

2292/2292 - 38s - 17ms/step - ia: 0.8037 - loss: 0.1456 - mae: 0.2899 - rmse: 0.3727 - smape: 0.6446 - val_ia: 0.3032 - val_loss: 0.2330 - val_mae: 0.3873 - val_rmse: 0.4242 - val_smape: 0.7933

Epoch 40/64

2292/2292 - 32s - 14ms/step - ia: 0.8048 - loss: 0.1438 - mae: 0.2883 - rmse: 0.3703 - smape: 0.6425 - val_ia: 0.3116 - val_loss: 0.2099 - val_mae: 0.3722 - val_rmse: 0.4070 - val_smape: 0.7741

Epoch 41/64

2292/2292 - 31s - 14ms/step - ia: 0.8050 - loss: 0.1437 - mae: 0.2886 - rmse: 0.3700 - smape: 0.6413 - val_ia: 0.3007 - val_loss: 0.2371 - val_mae: 0.3890 - val_rmse: 0.4273 - val_smape: 0.7992

Epoch 42/64

2292/2292 - 30s - 13ms/step - ia: 0.8066 - loss: 0.1423 - mae: 0.2866 - rmse: 0.3681 - smape: 0.6391 - val_ia: 0.3044 - val_loss: 0.2299 - val_mae: 0.3859 - val_rmse: 0.4204 - val_smape: 0.7923

Epoch 43/64

2292/2292 - 29s - 13ms/step - ia: 0.8077 - loss: 0.1409 - mae: 0.2851 - rmse: 0.3664 - smape: 0.6373 - val_ia: 0.2981 - val_loss: 0.2420 - val_mae: 0.3932 - val_rmse: 0.4301 - val_smape: 0.8015

Epoch 44/64

2292/2292 - 28s - 12ms/step - ia: 0.8083 - loss: 0.1395 - mae: 0.2835 - rmse: 0.3644 - smape: 0.6340 - val_ia: 0.2993 - val_loss: 0.2345 - val_mae: 0.3895 - val_rmse: 0.4249 - val_smape: 0.7977

Epoch 45/64

2292/2292 - 29s - 12ms/step - ia: 0.8094 - loss: 0.1381 - mae: 0.2823 - rmse: 0.3626 - smape: 0.6342 - val_ia: 0.2963 - val_loss: 0.2507 - val_mae: 0.3979 - val_rmse: 0.4358 - val_smape: 0.8014

Epoch 45: early stopping

Restoring model weights from the end of the best epoch: 30.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:33 950ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 60%|██████    | 30/50 [11:39:13<12:33:29, 2260.46s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 36s - 16ms/step - ia: 0.6990 - loss: 0.2994 - mae: 0.4183 - rmse: 0.5229 - smape: 0.8156 - val_ia: 0.3023 - val_loss: 0.2373 - val_mae: 0.3990 - val_rmse: 0.4302 - val_smape: 0.9347

Epoch 2/64

2292/2292 - 22s - 10ms/step - ia: 0.7989 - loss: 0.1549 - mae: 0.2990 - rmse: 0.3841 - smape: 0.6505 - val_ia: 0.3035 - val_loss: 0.2332 - val_mae: 0.3874 - val_rmse: 0.4255 - val_smape: 0.7979

Epoch 3/64

2292/2292 - 23s - 10ms/step - ia: 0.8207 - loss: 0.1265 - mae: 0.2678 - rmse: 0.3462 - smape: 0.6110 - val_ia: 0.3582 - val_loss: 0.1587 - val_mae: 0.3117 - val_rmse: 0.3481 - val_smape: 0.6953

Epoch 4/64

2292/2292 - 22s - 10ms/step - ia: 0.8299 - loss: 0.1148 - mae: 0.2551 - rmse: 0.3303 - smape: 0.5872 - val_ia: 0.3669 - val_loss: 0.1632 - val_mae: 0.3161 - val_rmse: 0.3484 - val_smape: 0.6700

Epoch 5/64

2292/2292 - 25s - 11ms/step - ia: 0.8378 - loss: 0.1050 - mae: 0.2438 - rmse: 0.3154 - smape: 0.5627 - val_ia: 0.3386 - val_loss: 0.1997 - val_mae: 0.3480 - val_rmse: 0.3844 - val_smape: 0.7243

Epoch 6/64

2292/2292 - 23s - 10ms/step - ia: 0.8428 - loss: 0.0993 - mae: 0.2377 - rmse: 0.3071 - smape: 0.5520 - val_ia: 0.3540 - val_loss: 0.1854 - val_mae: 0.3342 - val_rmse: 0.3697 - val_smape: 0.7058

Epoch 7/64

2292/2292 - 22s - 9ms/step - ia: 0.8458 - loss: 0.0963 - mae: 0.2337 - rmse: 0.3017 - smape: 0.5429 - val_ia: 0.3324 - val_loss: 0.2098 - val_mae: 0.3569 - val_rmse: 0.3950 - val_smape: 0.7447

Epoch 8/64

2292/2292 - 22s - 10ms/step - ia: 0.8493 - loss: 0.0919 - mae: 0.2284 - rmse: 0.2949 - smape: 0.5334 - val_ia: 0.3673 - val_loss: 0.1742 - val_mae: 0.3207 - val_rmse: 0.3525 - val_smape: 0.6823

Epoch 9/64

2292/2292 - 21s - 9ms/step - ia: 0.8517 - loss: 0.0892 - mae: 0.2248 - rmse: 0.2904 - smape: 0.5296 - val_ia: 0.3663 - val_loss: 0.1677 - val_mae: 0.3172 - val_rmse: 0.3485 - val_smape: 0.6877

Epoch 10/64

2292/2292 - 21s - 9ms/step - ia: 0.8531 - loss: 0.0871 - mae: 0.2228 - rmse: 0.2873 - smape: 0.5257 - val_ia: 0.3466 - val_loss: 0.1967 - val_mae: 0.3463 - val_rmse: 0.3798 - val_smape: 0.7364

Epoch 11/64

2292/2292 - 43s - 19ms/step - ia: 0.8560 - loss: 0.0836 - mae: 0.2184 - rmse: 0.2815 - smape: 0.5170 - val_ia: 0.3424 - val_loss: 0.1877 - val_mae: 0.3429 - val_rmse: 0.3759 - val_smape: 0.7342

Epoch 12/64

2292/2292 - 20s - 9ms/step - ia: 0.8564 - loss: 0.0836 - mae: 0.2181 - rmse: 0.2813 - smape: 0.5168 - val_ia: 0.3364 - val_loss: 0.1875 - val_mae: 0.3393 - val_rmse: 0.3737 - val_smape: 0.7425

Epoch 13/64

2292/2292 - 24s - 11ms/step - ia: 0.8568 - loss: 0.0834 - mae: 0.2175 - rmse: 0.2809 - smape: 0.5150 - val_ia: 0.3352 - val_loss: 0.2031 - val_mae: 0.3535 - val_rmse: 0.3882 - val_smape: 0.7501

Epoch 14/64

2292/2292 - 23s - 10ms/step - ia: 0.8593 - loss: 0.0805 - mae: 0.2141 - rmse: 0.2761 - smape: 0.5066 - val_ia: 0.3359 - val_loss: 0.1988 - val_mae: 0.3516 - val_rmse: 0.3867 - val_smape: 0.7454

Epoch 15/64

2292/2292 - 20s - 9ms/step - ia: 0.8598 - loss: 0.0806 - mae: 0.2140 - rmse: 0.2763 - smape: 0.5079 - val_ia: 0.3278 - val_loss: 0.2159 - val_mae: 0.3634 - val_rmse: 0.4014 - val_smape: 0.7471

Epoch 16/64

2292/2292 - 21s - 9ms/step - ia: 0.8613 - loss: 0.0788 - mae: 0.2117 - rmse: 0.2731 - smape: 0.5064 - val_ia: 0.3159 - val_loss: 0.2317 - val_mae: 0.3786 - val_rmse: 0.4169 - val_smape: 0.7622

Epoch 17/64

2292/2292 - 23s - 10ms/step - ia: 0.8620 - loss: 0.0777 - mae: 0.2104 - rmse: 0.2709 - smape: 0.5010 - val_ia: 0.3377 - val_loss: 0.2081 - val_mae: 0.3570 - val_rmse: 0.3940 - val_smape: 0.7461

Epoch 18/64

2292/2292 - 23s - 10ms/step - ia: 0.8628 - loss: 0.0771 - mae: 0.2090 - rmse: 0.2701 - smape: 0.4978 - val_ia: 0.3316 - val_loss: 0.2149 - val_mae: 0.3608 - val_rmse: 0.3974 - val_smape: 0.7556

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 62%|██████▏   | 31/50 [11:46:32<9:02:43, 1713.87s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 44s - 19ms/step - ia: 0.1781 - loss: 1.0265 - mae: 0.8390 - rmse: 1.0021 - smape: 1.8160 - val_ia: 0.1778 - val_loss: 0.8653 - val_mae: 0.7746 - val_rmse: 0.8112 - val_smape: 1.8415

Epoch 2/64

2292/2292 - 30s - 13ms/step - ia: 0.2067 - loss: 0.9255 - mae: 0.8038 - rmse: 0.9532 - smape: 1.7005 - val_ia: 0.1915 - val_loss: 0.7612 - val_mae: 0.7152 - val_rmse: 0.7525 - val_smape: 1.3462

Epoch 3/64

2292/2292 - 32s - 14ms/step - ia: 0.4700 - loss: 0.6134 - mae: 0.6496 - rmse: 0.7728 - smape: 1.1520 - val_ia: 0.1764 - val_loss: 1.1865 - val_mae: 0.9107 - val_rmse: 0.9391 - val_smape: 1.3454

Epoch 4/64

2292/2292 - 33s - 14ms/step - ia: 0.5971 - loss: 0.4789 - mae: 0.5578 - rmse: 0.6823 - smape: 0.9523 - val_ia: 0.1725 - val_loss: 1.2856 - val_mae: 0.9570 - val_rmse: 0.9852 - val_smape: 1.3722

Epoch 5/64

2292/2292 - 29s - 12ms/step - ia: 0.6259 - loss: 0.4347 - mae: 0.5281 - rmse: 0.6488 - smape: 0.9069 - val_ia: 0.1724 - val_loss: 1.3143 - val_mae: 0.9724 - val_rmse: 1.0006 - val_smape: 1.3844

Epoch 6/64

2292/2292 - 21s - 9ms/step - ia: 0.6485 - loss: 0.3977 - mae: 0.5027 - rmse: 0.6211 - smape: 0.8686 - val_ia: 0.1806 - val_loss: 1.2053 - val_mae: 0.9232 - val_rmse: 0.9526 - val_smape: 1.3382

Epoch 7/64

2292/2292 - 23s - 10ms/step - ia: 0.6661 - loss: 0.3703 - mae: 0.4836 - rmse: 0.5986 - smape: 0.8393 - val_ia: 0.1831 - val_loss: 1.1889 - val_mae: 0.9161 - val_rmse: 0.9459 - val_smape: 1.3204

Epoch 8/64

2292/2292 - 22s - 10ms/step - ia: 0.6757 - loss: 0.3526 - mae: 0.4715 - rmse: 0.5844 - smape: 0.8224 - val_ia: 0.1929 - val_loss: 1.0662 - val_mae: 0.8595 - val_rmse: 0.8902 - val_smape: 1.2661

Epoch 9/64

2292/2292 - 21s - 9ms/step - ia: 0.6838 - loss: 0.3406 - mae: 0.4631 - rmse: 0.5746 - smape: 0.8097 - val_ia: 0.1976 - val_loss: 1.0220 - val_mae: 0.8375 - val_rmse: 0.8689 - val_smape: 1.2397

Epoch 10/64

2292/2292 - 21s - 9ms/step - ia: 0.6878 - loss: 0.3322 - mae: 0.4573 - rmse: 0.5677 - smape: 0.8028 - val_ia: 0.2070 - val_loss: 0.9030 - val_mae: 0.7778 - val_rmse: 0.8105 - val_smape: 1.1871

Epoch 11/64

2292/2292 - 21s - 9ms/step - ia: 0.6923 - loss: 0.3255 - mae: 0.4524 - rmse: 0.5613 - smape: 0.7943 - val_ia: 0.2066 - val_loss: 0.8940 - val_mae: 0.7752 - val_rmse: 0.8081 - val_smape: 1.1853

Epoch 12/64

2292/2292 - 21s - 9ms/step - ia: 0.6952 - loss: 0.3196 - mae: 0.4483 - rmse: 0.5563 - smape: 0.7911 - val_ia: 0.2060 - val_loss: 0.9155 - val_mae: 0.7857 - val_rmse: 0.8186 - val_smape: 1.1881

Epoch 13/64

2292/2292 - 21s - 9ms/step - ia: 0.6993 - loss: 0.3141 - mae: 0.4440 - rmse: 0.5515 - smape: 0.7850 - val_ia: 0.2074 - val_loss: 0.8632 - val_mae: 0.7561 - val_rmse: 0.7898 - val_smape: 1.1611

Epoch 14/64

2292/2292 - 21s - 9ms/step - ia: 0.7012 - loss: 0.3092 - mae: 0.4404 - rmse: 0.5470 - smape: 0.7819 - val_ia: 0.2070 - val_loss: 0.8231 - val_mae: 0.7380 - val_rmse: 0.7716 - val_smape: 1.1535

Epoch 15/64

2292/2292 - 21s - 9ms/step - ia: 0.7044 - loss: 0.3042 - mae: 0.4364 - rmse: 0.5430 - smape: 0.7776 - val_ia: 0.2045 - val_loss: 0.7235 - val_mae: 0.6871 - val_rmse: 0.7217 - val_smape: 1.1252

Epoch 16/64

2292/2292 - 21s - 9ms/step - ia: 0.7086 - loss: 0.2996 - mae: 0.4330 - rmse: 0.5387 - smape: 0.7741 - val_ia: 0.2062 - val_loss: 0.8342 - val_mae: 0.7396 - val_rmse: 0.7740 - val_smape: 1.1457

Epoch 17/64

2292/2292 - 21s - 9ms/step - ia: 0.7097 - loss: 0.2955 - mae: 0.4298 - rmse: 0.5350 - smape: 0.7709 - val_ia: 0.2051 - val_loss: 0.7422 - val_mae: 0.6958 - val_rmse: 0.7304 - val_smape: 1.1286

Epoch 18/64

2292/2292 - 21s - 9ms/step - ia: 0.7126 - loss: 0.2915 - mae: 0.4266 - rmse: 0.5311 - smape: 0.7678 - val_ia: 0.2047 - val_loss: 0.7196 - val_mae: 0.6840 - val_rmse: 0.7189 - val_smape: 1.1217

Epoch 19/64

2292/2292 - 21s - 9ms/step - ia: 0.7144 - loss: 0.2874 - mae: 0.4229 - rmse: 0.5277 - smape: 0.7635 - val_ia: 0.2048 - val_loss: 0.7298 - val_mae: 0.6883 - val_rmse: 0.7230 - val_smape: 1.1228

Epoch 20/64

2292/2292 - 26s - 11ms/step - ia: 0.7168 - loss: 0.2834 - mae: 0.4196 - rmse: 0.5235 - smape: 0.7600 - val_ia: 0.2050 - val_loss: 0.7633 - val_mae: 0.7066 - val_rmse: 0.7404 - val_smape: 1.1328

Epoch 21/64

2292/2292 - 22s - 9ms/step - ia: 0.7191 - loss: 0.2794 - mae: 0.4165 - rmse: 0.5202 - smape: 0.7578 - val_ia: 0.2049 - val_loss: 0.7057 - val_mae: 0.6754 - val_rmse: 0.7105 - val_smape: 1.1127

Epoch 22/64

2292/2292 - 23s - 10ms/step - ia: 0.7222 - loss: 0.2758 - mae: 0.4134 - rmse: 0.5168 - smape: 0.7535 - val_ia: 0.2034 - val_loss: 0.7021 - val_mae: 0.6725 - val_rmse: 0.7075 - val_smape: 1.1115

Epoch 23/64

2292/2292 - 27s - 12ms/step - ia: 0.7242 - loss: 0.2721 - mae: 0.4102 - rmse: 0.5128 - smape: 0.7516 - val_ia: 0.2038 - val_loss: 0.6921 - val_mae: 0.6669 - val_rmse: 0.7019 - val_smape: 1.1068

Epoch 24/64

2292/2292 - 24s - 10ms/step - ia: 0.7267 - loss: 0.2683 - mae: 0.4070 - rmse: 0.5090 - smape: 0.7474 - val_ia: 0.2041 - val_loss: 0.6953 - val_mae: 0.6681 - val_rmse: 0.7027 - val_smape: 1.1078

Epoch 25/64

2292/2292 - 23s - 10ms/step - ia: 0.7294 - loss: 0.2642 - mae: 0.4035 - rmse: 0.5048 - smape: 0.7446 - val_ia: 0.2062 - val_loss: 0.7025 - val_mae: 0.6717 - val_rmse: 0.7057 - val_smape: 1.1074

Epoch 26/64

2292/2292 - 23s - 10ms/step - ia: 0.7310 - loss: 0.2602 - mae: 0.3997 - rmse: 0.5015 - smape: 0.7390 - val_ia: 0.2061 - val_loss: 0.6789 - val_mae: 0.6585 - val_rmse: 0.6933 - val_smape: 1.0972

Epoch 27/64

2292/2292 - 26s - 12ms/step - ia: 0.7346 - loss: 0.2563 - mae: 0.3961 - rmse: 0.4975 - smape: 0.7361 - val_ia: 0.2070 - val_loss: 0.6483 - val_mae: 0.6432 - val_rmse: 0.6776 - val_smape: 1.0891

Epoch 28/64

2292/2292 - 22s - 9ms/step - ia: 0.7366 - loss: 0.2520 - mae: 0.3921 - rmse: 0.4927 - smape: 0.7316 - val_ia: 0.2083 - val_loss: 0.6622 - val_mae: 0.6494 - val_rmse: 0.6835 - val_smape: 1.0922

Epoch 29/64

2292/2292 - 21s - 9ms/step - ia: 0.7389 - loss: 0.2479 - mae: 0.3885 - rmse: 0.4882 - smape: 0.7285 - val_ia: 0.2103 - val_loss: 0.6372 - val_mae: 0.6373 - val_rmse: 0.6711 - val_smape: 1.0836

Epoch 30/64

2292/2292 - 24s - 10ms/step - ia: 0.7432 - loss: 0.2433 - mae: 0.3840 - rmse: 0.4849 - smape: 0.7234 - val_ia: 0.2129 - val_loss: 0.6486 - val_mae: 0.6433 - val_rmse: 0.6766 - val_smape: 1.0840

Epoch 31/64

2292/2292 - 22s - 10ms/step - ia: 0.7451 - loss: 0.2388 - mae: 0.3800 - rmse: 0.4799 - smape: 0.7198 - val_ia: 0.2158 - val_loss: 0.6457 - val_mae: 0.6418 - val_rmse: 0.6748 - val_smape: 1.0789

Epoch 32/64

2292/2292 - 22s - 10ms/step - ia: 0.7477 - loss: 0.2338 - mae: 0.3752 - rmse: 0.4745 - smape: 0.7139 - val_ia: 0.2187 - val_loss: 0.6309 - val_mae: 0.6351 - val_rmse: 0.6673 - val_smape: 1.0711

Epoch 33/64

2292/2292 - 23s - 10ms/step - ia: 0.7512 - loss: 0.2288 - mae: 0.3712 - rmse: 0.4696 - smape: 0.7111 - val_ia: 0.2208 - val_loss: 0.6097 - val_mae: 0.6237 - val_rmse: 0.6563 - val_smape: 1.0628

Epoch 34/64

2292/2292 - 41s - 18ms/step - ia: 0.7550 - loss: 0.2235 - mae: 0.3658 - rmse: 0.4636 - smape: 0.7045 - val_ia: 0.2238 - val_loss: 0.5715 - val_mae: 0.6055 - val_rmse: 0.6377 - val_smape: 1.0482

Epoch 35/64

2292/2292 - 22s - 10ms/step - ia: 0.7580 - loss: 0.2181 - mae: 0.3606 - rmse: 0.4579 - smape: 0.6986 - val_ia: 0.2278 - val_loss: 0.5955 - val_mae: 0.6167 - val_rmse: 0.6488 - val_smape: 1.0482

Epoch 36/64

2292/2292 - 22s - 10ms/step - ia: 0.7618 - loss: 0.2123 - mae: 0.3553 - rmse: 0.4514 - smape: 0.6945 - val_ia: 0.2322 - val_loss: 0.5787 - val_mae: 0.6078 - val_rmse: 0.6397 - val_smape: 1.0345

Epoch 37/64

2292/2292 - 22s - 10ms/step - ia: 0.7657 - loss: 0.2066 - mae: 0.3501 - rmse: 0.4453 - smape: 0.6896 - val_ia: 0.2360 - val_loss: 0.5176 - val_mae: 0.5768 - val_rmse: 0.6085 - val_smape: 1.0145

Epoch 38/64

2292/2292 - 40s - 18ms/step - ia: 0.7704 - loss: 0.2005 - mae: 0.3442 - rmse: 0.4386 - smape: 0.6842 - val_ia: 0.2384 - val_loss: 0.5405 - val_mae: 0.5876 - val_rmse: 0.6197 - val_smape: 1.0092

Epoch 39/64

2292/2292 - 22s - 10ms/step - ia: 0.7738 - loss: 0.1943 - mae: 0.3384 - rmse: 0.4307 - smape: 0.6798 - val_ia: 0.2405 - val_loss: 0.5155 - val_mae: 0.5751 - val_rmse: 0.6074 - val_smape: 0.9997

Epoch 40/64

2292/2292 - 22s - 10ms/step - ia: 0.7769 - loss: 0.1882 - mae: 0.3326 - rmse: 0.4240 - smape: 0.6744 - val_ia: 0.2446 - val_loss: 0.5469 - val_mae: 0.5882 - val_rmse: 0.6212 - val_smape: 0.9859

Epoch 41/64

2292/2292 - 22s - 10ms/step - ia: 0.7807 - loss: 0.1819 - mae: 0.3266 - rmse: 0.4170 - smape: 0.6700 - val_ia: 0.2533 - val_loss: 0.5257 - val_mae: 0.5745 - val_rmse: 0.6071 - val_smape: 0.9605

Epoch 42/64

2292/2292 - 22s - 10ms/step - ia: 0.7857 - loss: 0.1758 - mae: 0.3204 - rmse: 0.4094 - smape: 0.6631 - val_ia: 0.2530 - val_loss: 0.5451 - val_mae: 0.5816 - val_rmse: 0.6156 - val_smape: 0.9590

Epoch 43/64

2292/2292 - 22s - 10ms/step - ia: 0.7898 - loss: 0.1695 - mae: 0.3138 - rmse: 0.4019 - smape: 0.6575 - val_ia: 0.2579 - val_loss: 0.4377 - val_mae: 0.5267 - val_rmse: 0.5601 - val_smape: 0.9321

Epoch 44/64

2292/2292 - 22s - 10ms/step - ia: 0.7943 - loss: 0.1632 - mae: 0.3073 - rmse: 0.3942 - smape: 0.6510 - val_ia: 0.2547 - val_loss: 0.4923 - val_mae: 0.5505 - val_rmse: 0.5857 - val_smape: 0.9397

Epoch 45/64

2292/2292 - 22s - 10ms/step - ia: 0.7989 - loss: 0.1572 - mae: 0.3011 - rmse: 0.3866 - smape: 0.6465 - val_ia: 0.2673 - val_loss: 0.4412 - val_mae: 0.5210 - val_rmse: 0.5553 - val_smape: 0.9058

Epoch 46/64

2292/2292 - 22s - 10ms/step - ia: 0.8027 - loss: 0.1512 - mae: 0.2945 - rmse: 0.3787 - smape: 0.6407 - val_ia: 0.2649 - val_loss: 0.4653 - val_mae: 0.5308 - val_rmse: 0.5664 - val_smape: 0.9038

Epoch 47/64

2292/2292 - 22s - 10ms/step - ia: 0.8078 - loss: 0.1450 - mae: 0.2879 - rmse: 0.3710 - smape: 0.6335 - val_ia: 0.2717 - val_loss: 0.4054 - val_mae: 0.4982 - val_rmse: 0.5332 - val_smape: 0.8890

Epoch 48/64

2292/2292 - 23s - 10ms/step - ia: 0.8120 - loss: 0.1393 - mae: 0.2811 - rmse: 0.3635 - smape: 0.6281 - val_ia: 0.2739 - val_loss: 0.4307 - val_mae: 0.5091 - val_rmse: 0.5442 - val_smape: 0.8697

Epoch 49/64

2292/2292 - 40s - 17ms/step - ia: 0.8152 - loss: 0.1339 - mae: 0.2754 - rmse: 0.3555 - smape: 0.6224 - val_ia: 0.2830 - val_loss: 0.3542 - val_mae: 0.4663 - val_rmse: 0.5007 - val_smape: 0.8541

Epoch 50/64

2292/2292 - 41s - 18ms/step - ia: 0.8193 - loss: 0.1293 - mae: 0.2700 - rmse: 0.3495 - smape: 0.6160 - val_ia: 0.2884 - val_loss: 0.3160 - val_mae: 0.4433 - val_rmse: 0.4775 - val_smape: 0.8393

Epoch 51/64

2292/2292 - 22s - 9ms/step - ia: 0.8237 - loss: 0.1245 - mae: 0.2643 - rmse: 0.3427 - smape: 0.6093 - val_ia: 0.2881 - val_loss: 0.3249 - val_mae: 0.4458 - val_rmse: 0.4809 - val_smape: 0.8363

Epoch 52/64

2292/2292 - 22s - 10ms/step - ia: 0.8265 - loss: 0.1210 - mae: 0.2595 - rmse: 0.3377 - smape: 0.6036 - val_ia: 0.2938 - val_loss: 0.3055 - val_mae: 0.4330 - val_rmse: 0.4675 - val_smape: 0.8193

Epoch 53/64

2292/2292 - 22s - 10ms/step - ia: 0.8301 - loss: 0.1176 - mae: 0.2552 - rmse: 0.3328 - smape: 0.5967 - val_ia: 0.2929 - val_loss: 0.3027 - val_mae: 0.4305 - val_rmse: 0.4657 - val_smape: 0.8191

Epoch 54/64

2292/2292 - 41s - 18ms/step - ia: 0.8321 - loss: 0.1152 - mae: 0.2521 - rmse: 0.3288 - smape: 0.5923 - val_ia: 0.2990 - val_loss: 0.2866 - val_mae: 0.4192 - val_rmse: 0.4538 - val_smape: 0.8035

Epoch 55/64

2292/2292 - 22s - 10ms/step - ia: 0.8347 - loss: 0.1129 - mae: 0.2488 - rmse: 0.3254 - smape: 0.5876 - val_ia: 0.3034 - val_loss: 0.2523 - val_mae: 0.3971 - val_rmse: 0.4331 - val_smape: 0.7935

Epoch 56/64

2292/2292 - 22s - 9ms/step - ia: 0.8357 - loss: 0.1112 - mae: 0.2466 - rmse: 0.3233 - smape: 0.5844 - val_ia: 0.3088 - val_loss: 0.2356 - val_mae: 0.3854 - val_rmse: 0.4223 - val_smape: 0.7854

Epoch 57/64

2292/2292 - 22s - 10ms/step - ia: 0.8368 - loss: 0.1098 - mae: 0.2444 - rmse: 0.3207 - smape: 0.5808 - val_ia: 0.3135 - val_loss: 0.2355 - val_mae: 0.3826 - val_rmse: 0.4181 - val_smape: 0.7724

Epoch 58/64

2292/2292 - 23s - 10ms/step - ia: 0.8389 - loss: 0.1082 - mae: 0.2424 - rmse: 0.3185 - smape: 0.5758 - val_ia: 0.3072 - val_loss: 0.2541 - val_mae: 0.3962 - val_rmse: 0.4307 - val_smape: 0.7824

Epoch 59/64

2292/2292 - 22s - 10ms/step - ia: 0.8394 - loss: 0.1072 - mae: 0.2411 - rmse: 0.3169 - smape: 0.5733 - val_ia: 0.3136 - val_loss: 0.2350 - val_mae: 0.3818 - val_rmse: 0.4177 - val_smape: 0.7672

Epoch 60/64

2292/2292 - 22s - 10ms/step - ia: 0.8403 - loss: 0.1061 - mae: 0.2395 - rmse: 0.3151 - smape: 0.5712 - val_ia: 0.3064 - val_loss: 0.2646 - val_mae: 0.4037 - val_rmse: 0.4376 - val_smape: 0.7858

Epoch 61/64

2292/2292 - 22s - 10ms/step - ia: 0.8416 - loss: 0.1053 - mae: 0.2383 - rmse: 0.3141 - smape: 0.5702 - val_ia: 0.3083 - val_loss: 0.2681 - val_mae: 0.4077 - val_rmse: 0.4401 - val_smape: 0.7895

Epoch 62/64

2292/2292 - 22s - 10ms/step - ia: 0.8422 - loss: 0.1043 - mae: 0.2372 - rmse: 0.3127 - smape: 0.5683 - val_ia: 0.3119 - val_loss: 0.2244 - val_mae: 0.3755 - val_rmse: 0.4121 - val_smape: 0.7655

Epoch 63/64

2292/2292 - 22s - 10ms/step - ia: 0.8427 - loss: 0.1038 - mae: 0.2364 - rmse: 0.3115 - smape: 0.5664 - val_ia: 0.3260 - val_loss: 0.2072 - val_mae: 0.3605 - val_rmse: 0.3958 - val_smape: 0.7421

Epoch 64/64

2292/2292 - 42s - 18ms/step - ia: 0.8438 - loss: 0.1030 - mae: 0.2352 - rmse: 0.3106 - smape: 0.5639 - val_ia: 0.3131 - val_loss: 0.2504 - val_mae: 0.3955 - val_rmse: 0.4285 - val_smape: 0.7787

Restoring model weights from the end of the best epoch: 63.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 64%|██████▍   | 32/50 [12:13:04<8:23:12, 1677.37s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

144/144 - 13s - 94ms/step - ia: 0.1062 - loss: 0.9454 - mae: 0.8088 - rmse: 0.9712 - smape: 1.7532 - val_ia: 0.2491 - val_loss: 0.7981 - val_mae: 0.7420 - val_rmse: 0.8823 - val_smape: 1.6293

Epoch 2/32

144/144 - 6s - 40ms/step - ia: 0.2252 - loss: 0.8263 - mae: 0.7589 - rmse: 0.9078 - smape: 1.5417 - val_ia: 0.3260 - val_loss: 0.7530 - val_mae: 0.7202 - val_rmse: 0.8533 - val_smape: 1.4424

Epoch 3/32

144/144 - 6s - 39ms/step - ia: 0.3785 - loss: 0.6775 - mae: 0.6868 - rmse: 0.8218 - smape: 1.3163 - val_ia: 0.4109 - val_loss: 0.7964 - val_mae: 0.7392 - val_rmse: 0.8713 - val_smape: 1.3309

Epoch 4/32

144/144 - 6s - 40ms/step - ia: 0.5182 - loss: 0.5462 - mae: 0.6092 - rmse: 0.7382 - smape: 1.1088 - val_ia: 0.4376 - val_loss: 0.9787 - val_mae: 0.8180 - val_rmse: 0.9648 - val_smape: 1.3155

Epoch 5/32

144/144 - 6s - 40ms/step - ia: 0.5940 - loss: 0.4762 - mae: 0.5585 - rmse: 0.6897 - smape: 0.9963 - val_ia: 0.4345 - val_loss: 1.1232 - val_mae: 0.8806 - val_rmse: 1.0339 - val_smape: 1.3234

Epoch 6/32

144/144 - 6s - 41ms/step - ia: 0.6284 - loss: 0.4402 - mae: 0.5312 - rmse: 0.6624 - smape: 0.9414 - val_ia: 0.4329 - val_loss: 1.1630 - val_mae: 0.9024 - val_rmse: 1.0503 - val_smape: 1.3325

Epoch 7/32

144/144 - 6s - 40ms/step - ia: 0.6472 - loss: 0.4157 - mae: 0.5145 - rmse: 0.6443 - smape: 0.9051 - val_ia: 0.4346 - val_loss: 1.1628 - val_mae: 0.9055 - val_rmse: 1.0478 - val_smape: 1.3316

Epoch 8/32

144/144 - 6s - 39ms/step - ia: 0.6598 - loss: 0.3967 - mae: 0.5022 - rmse: 0.6287 - smape: 0.8820 - val_ia: 0.4390 - val_loss: 1.1534 - val_mae: 0.8999 - val_rmse: 1.0420 - val_smape: 1.3166

Epoch 9/32

144/144 - 6s - 40ms/step - ia: 0.6691 - loss: 0.3812 - mae: 0.4924 - rmse: 0.6167 - smape: 0.8660 - val_ia: 0.4449 - val_loss: 1.1320 - val_mae: 0.8885 - val_rmse: 1.0307 - val_smape: 1.2991

Epoch 10/32

144/144 - 6s - 39ms/step - ia: 0.6775 - loss: 0.3659 - mae: 0.4832 - rmse: 0.6047 - smape: 0.8518 - val_ia: 0.4506 - val_loss: 1.1017 - val_mae: 0.8738 - val_rmse: 1.0154 - val_smape: 1.2850

Epoch 11/32

144/144 - 10s - 71ms/step - ia: 0.6862 - loss: 0.3510 - mae: 0.4730 - rmse: 0.5921 - smape: 0.8381 - val_ia: 0.4601 - val_loss: 1.0711 - val_mae: 0.8544 - val_rmse: 1.0007 - val_smape: 1.2579

Epoch 12/32

144/144 - 11s - 73ms/step - ia: 0.6942 - loss: 0.3377 - mae: 0.4636 - rmse: 0.5808 - smape: 0.8241 - val_ia: 0.4674 - val_loss: 1.0350 - val_mae: 0.8345 - val_rmse: 0.9829 - val_smape: 1.2431

Epoch 13/32

144/144 - 10s - 70ms/step - ia: 0.7018 - loss: 0.3253 - mae: 0.4549 - rmse: 0.5694 - smape: 0.8130 - val_ia: 0.4752 - val_loss: 0.9970 - val_mae: 0.8155 - val_rmse: 0.9640 - val_smape: 1.2307

Epoch 14/32

144/144 - 6s - 40ms/step - ia: 0.7081 - loss: 0.3145 - mae: 0.4470 - rmse: 0.5604 - smape: 0.8039 - val_ia: 0.4821 - val_loss: 0.9606 - val_mae: 0.7966 - val_rmse: 0.9458 - val_smape: 1.2182

Epoch 15/32

144/144 - 10s - 70ms/step - ia: 0.7145 - loss: 0.3046 - mae: 0.4388 - rmse: 0.5514 - smape: 0.7924 - val_ia: 0.4888 - val_loss: 0.9313 - val_mae: 0.7804 - val_rmse: 0.9314 - val_smape: 1.2057

Epoch 16/32

144/144 - 6s - 40ms/step - ia: 0.7193 - loss: 0.2971 - mae: 0.4325 - rmse: 0.5450 - smape: 0.7846 - val_ia: 0.4945 - val_loss: 0.8971 - val_mae: 0.7637 - val_rmse: 0.9142 - val_smape: 1.1975

Epoch 17/32

144/144 - 6s - 45ms/step - ia: 0.7248 - loss: 0.2878 - mae: 0.4255 - rmse: 0.5358 - smape: 0.7773 - val_ia: 0.5025 - val_loss: 0.8497 - val_mae: 0.7432 - val_rmse: 0.8889 - val_smape: 1.1881

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:53 700ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 66%|██████▌   | 33/50 [12:15:12<5:43:33, 1212.54s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

573/573 - 32s - 56ms/step - ia: 0.1118 - loss: 0.9718 - mae: 0.8184 - rmse: 0.9835 - smape: 1.8829 - val_ia: 0.2960 - val_loss: 0.8025 - val_mae: 0.7436 - val_rmse: 0.8595 - val_smape: 1.7304

Epoch 2/64

573/573 - 22s - 38ms/step - ia: 0.3957 - loss: 0.6551 - mae: 0.6618 - rmse: 0.8007 - smape: 1.2915 - val_ia: 0.3618 - val_loss: 0.9014 - val_mae: 0.7900 - val_rmse: 0.8901 - val_smape: 1.3088

Epoch 3/64

573/573 - 23s - 39ms/step - ia: 0.6520 - loss: 0.3847 - mae: 0.4973 - rmse: 0.6181 - smape: 0.8805 - val_ia: 0.3956 - val_loss: 0.9413 - val_mae: 0.8060 - val_rmse: 0.9101 - val_smape: 1.2484

Epoch 4/64

573/573 - 22s - 39ms/step - ia: 0.6917 - loss: 0.3271 - mae: 0.4584 - rmse: 0.5699 - smape: 0.8182 - val_ia: 0.4320 - val_loss: 0.8297 - val_mae: 0.7464 - val_rmse: 0.8516 - val_smape: 1.1970

Epoch 5/64

573/573 - 41s - 71ms/step - ia: 0.7195 - loss: 0.2854 - mae: 0.4247 - rmse: 0.5320 - smape: 0.7757 - val_ia: 0.4503 - val_loss: 0.7566 - val_mae: 0.7112 - val_rmse: 0.8097 - val_smape: 1.1801

Epoch 6/64

573/573 - 41s - 71ms/step - ia: 0.7430 - loss: 0.2521 - mae: 0.3950 - rmse: 0.4998 - smape: 0.7407 - val_ia: 0.4661 - val_loss: 0.6807 - val_mae: 0.6756 - val_rmse: 0.7681 - val_smape: 1.1643

Epoch 7/64

573/573 - 41s - 72ms/step - ia: 0.7592 - loss: 0.2279 - mae: 0.3731 - rmse: 0.4752 - smape: 0.7162 - val_ia: 0.4868 - val_loss: 0.5850 - val_mae: 0.6283 - val_rmse: 0.7157 - val_smape: 1.1405

Epoch 8/64

573/573 - 22s - 39ms/step - ia: 0.7710 - loss: 0.2112 - mae: 0.3573 - rmse: 0.4574 - smape: 0.7011 - val_ia: 0.5143 - val_loss: 0.4709 - val_mae: 0.5686 - val_rmse: 0.6498 - val_smape: 1.0914

Epoch 9/64

573/573 - 22s - 38ms/step - ia: 0.7783 - loss: 0.1997 - mae: 0.3458 - rmse: 0.4448 - smape: 0.6894 - val_ia: 0.5331 - val_loss: 0.4195 - val_mae: 0.5374 - val_rmse: 0.6154 - val_smape: 1.0518

Epoch 10/64

573/573 - 22s - 38ms/step - ia: 0.7844 - loss: 0.1907 - mae: 0.3367 - rmse: 0.4345 - smape: 0.6796 - val_ia: 0.5378 - val_loss: 0.4218 - val_mae: 0.5368 - val_rmse: 0.6145 - val_smape: 1.0571

Epoch 11/64

573/573 - 21s - 37ms/step - ia: 0.7890 - loss: 0.1834 - mae: 0.3291 - rmse: 0.4262 - smape: 0.6727 - val_ia: 0.5582 - val_loss: 0.3756 - val_mae: 0.5060 - val_rmse: 0.5809 - val_smape: 1.0050

Epoch 12/64

573/573 - 21s - 37ms/step - ia: 0.7939 - loss: 0.1770 - mae: 0.3222 - rmse: 0.4182 - smape: 0.6645 - val_ia: 0.5610 - val_loss: 0.3758 - val_mae: 0.5054 - val_rmse: 0.5805 - val_smape: 1.0031

Epoch 13/64

573/573 - 22s - 38ms/step - ia: 0.7980 - loss: 0.1713 - mae: 0.3162 - rmse: 0.4117 - smape: 0.6578 - val_ia: 0.5784 - val_loss: 0.3394 - val_mae: 0.4783 - val_rmse: 0.5513 - val_smape: 0.9605

Epoch 14/64

573/573 - 22s - 39ms/step - ia: 0.8013 - loss: 0.1662 - mae: 0.3108 - rmse: 0.4057 - smape: 0.6513 - val_ia: 0.5834 - val_loss: 0.3292 - val_mae: 0.4709 - val_rmse: 0.5432 - val_smape: 0.9555

Epoch 15/64

573/573 - 22s - 38ms/step - ia: 0.8047 - loss: 0.1612 - mae: 0.3056 - rmse: 0.3994 - smape: 0.6479 - val_ia: 0.5929 - val_loss: 0.3165 - val_mae: 0.4597 - val_rmse: 0.5319 - val_smape: 0.9379

Epoch 16/64

573/573 - 22s - 38ms/step - ia: 0.8080 - loss: 0.1565 - mae: 0.3006 - rmse: 0.3935 - smape: 0.6419 - val_ia: 0.5895 - val_loss: 0.3256 - val_mae: 0.4654 - val_rmse: 0.5392 - val_smape: 0.9482

Epoch 17/64

573/573 - 22s - 38ms/step - ia: 0.8107 - loss: 0.1523 - mae: 0.2963 - rmse: 0.3879 - smape: 0.6409 - val_ia: 0.5859 - val_loss: 0.3439 - val_mae: 0.4769 - val_rmse: 0.5532 - val_smape: 0.9581

Epoch 18/64

573/573 - 41s - 71ms/step - ia: 0.8140 - loss: 0.1479 - mae: 0.2915 - rmse: 0.3826 - smape: 0.6352 - val_ia: 0.5963 - val_loss: 0.3282 - val_mae: 0.4629 - val_rmse: 0.5394 - val_smape: 0.9357

Epoch 19/64

573/573 - 22s - 38ms/step - ia: 0.8171 - loss: 0.1438 - mae: 0.2870 - rmse: 0.3771 - smape: 0.6314 - val_ia: 0.5922 - val_loss: 0.3418 - val_mae: 0.4698 - val_rmse: 0.5489 - val_smape: 0.9431

Epoch 20/64

573/573 - 22s - 38ms/step - ia: 0.8196 - loss: 0.1399 - mae: 0.2829 - rmse: 0.3720 - smape: 0.6273 - val_ia: 0.5913 - val_loss: 0.3507 - val_mae: 0.4735 - val_rmse: 0.5548 - val_smape: 0.9472

Epoch 21/64

573/573 - 41s - 71ms/step - ia: 0.8223 - loss: 0.1358 - mae: 0.2785 - rmse: 0.3663 - smape: 0.6236 - val_ia: 0.6013 - val_loss: 0.3273 - val_mae: 0.4589 - val_rmse: 0.5386 - val_smape: 0.9332

Epoch 22/64

573/573 - 21s - 37ms/step - ia: 0.8251 - loss: 0.1319 - mae: 0.2739 - rmse: 0.3612 - smape: 0.6175 - val_ia: 0.5949 - val_loss: 0.3559 - val_mae: 0.4715 - val_rmse: 0.5556 - val_smape: 0.9420

Epoch 23/64

573/573 - 21s - 37ms/step - ia: 0.8281 - loss: 0.1282 - mae: 0.2698 - rmse: 0.3563 - smape: 0.6156 - val_ia: 0.6026 - val_loss: 0.3389 - val_mae: 0.4605 - val_rmse: 0.5444 - val_smape: 0.9291

Epoch 24/64

573/573 - 22s - 38ms/step - ia: 0.8308 - loss: 0.1245 - mae: 0.2653 - rmse: 0.3507 - smape: 0.6084 - val_ia: 0.5969 - val_loss: 0.3693 - val_mae: 0.4736 - val_rmse: 0.5615 - val_smape: 0.9371

Epoch 25/64

573/573 - 22s - 38ms/step - ia: 0.8335 - loss: 0.1211 - mae: 0.2615 - rmse: 0.3458 - smape: 0.6043 - val_ia: 0.5962 - val_loss: 0.3841 - val_mae: 0.4780 - val_rmse: 0.5687 - val_smape: 0.9384

Epoch 26/64

573/573 - 22s - 39ms/step - ia: 0.8360 - loss: 0.1177 - mae: 0.2575 - rmse: 0.3408 - smape: 0.6002 - val_ia: 0.5947 - val_loss: 0.4169 - val_mae: 0.4904 - val_rmse: 0.5836 - val_smape: 0.9391

Epoch 27/64

573/573 - 22s - 39ms/step - ia: 0.8387 - loss: 0.1148 - mae: 0.2540 - rmse: 0.3369 - smape: 0.5950 - val_ia: 0.6018 - val_loss: 0.3952 - val_mae: 0.4758 - val_rmse: 0.5689 - val_smape: 0.9261

Epoch 28/64

573/573 - 22s - 38ms/step - ia: 0.8410 - loss: 0.1116 - mae: 0.2499 - rmse: 0.3319 - smape: 0.5903 - val_ia: 0.6005 - val_loss: 0.4051 - val_mae: 0.4807 - val_rmse: 0.5748 - val_smape: 0.9262

Epoch 29/64

573/573 - 22s - 38ms/step - ia: 0.8433 - loss: 0.1089 - mae: 0.2466 - rmse: 0.3280 - smape: 0.5837 - val_ia: 0.5992 - val_loss: 0.4202 - val_mae: 0.4838 - val_rmse: 0.5807 - val_smape: 0.9273

Epoch 30/64

573/573 - 22s - 38ms/step - ia: 0.8453 - loss: 0.1062 - mae: 0.2432 - rmse: 0.3239 - smape: 0.5793 - val_ia: 0.6007 - val_loss: 0.4380 - val_mae: 0.4884 - val_rmse: 0.5865 - val_smape: 0.9191

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:33 950ms/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

 68%|██████▊   | 34/50 [12:27:57<4:47:33, 1078.37s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 44s - 19ms/step - ia: 0.5829 - loss: 0.4943 - mae: 0.5580 - rmse: 0.6828 - smape: 0.9848 - val_ia: 0.2047 - val_loss: 0.9489 - val_mae: 0.7976 - val_rmse: 0.8297 - val_smape: 1.2112

Epoch 2/64

2292/2292 - 23s - 10ms/step - ia: 0.7014 - loss: 0.3112 - mae: 0.4424 - rmse: 0.5490 - smape: 0.7893 - val_ia: 0.2196 - val_loss: 0.8391 - val_mae: 0.7372 - val_rmse: 0.7713 - val_smape: 1.1386

Epoch 3/64

2292/2292 - 24s - 10ms/step - ia: 0.7390 - loss: 0.2477 - mae: 0.3881 - rmse: 0.4885 - smape: 0.7502 - val_ia: 0.2531 - val_loss: 0.4212 - val_mae: 0.5167 - val_rmse: 0.5465 - val_smape: 0.9708

Epoch 4/64

2292/2292 - 24s - 10ms/step - ia: 0.7806 - loss: 0.1800 - mae: 0.3231 - rmse: 0.4145 - smape: 0.7002 - val_ia: 0.2871 - val_loss: 0.2801 - val_mae: 0.4281 - val_rmse: 0.4586 - val_smape: 0.8582

Epoch 5/64

2292/2292 - 24s - 10ms/step - ia: 0.7972 - loss: 0.1558 - mae: 0.2991 - rmse: 0.3855 - smape: 0.6687 - val_ia: 0.2835 - val_loss: 0.2651 - val_mae: 0.4199 - val_rmse: 0.4514 - val_smape: 0.8269

Epoch 6/64

2292/2292 - 40s - 18ms/step - ia: 0.8069 - loss: 0.1443 - mae: 0.2862 - rmse: 0.3700 - smape: 0.6453 - val_ia: 0.2840 - val_loss: 0.2959 - val_mae: 0.4263 - val_rmse: 0.4659 - val_smape: 0.8123

Epoch 7/64

2292/2292 - 24s - 10ms/step - ia: 0.8205 - loss: 0.1267 - mae: 0.2674 - rmse: 0.3465 - smape: 0.6276 - val_ia: 0.3349 - val_loss: 0.1740 - val_mae: 0.3401 - val_rmse: 0.3708 - val_smape: 0.7595

Epoch 8/64

2292/2292 - 24s - 10ms/step - ia: 0.8303 - loss: 0.1166 - mae: 0.2546 - rmse: 0.3314 - smape: 0.6259 - val_ia: 0.3229 - val_loss: 0.1917 - val_mae: 0.3520 - val_rmse: 0.3858 - val_smape: 0.7674

Epoch 9/64

2292/2292 - 24s - 10ms/step - ia: 0.8351 - loss: 0.1107 - mae: 0.2478 - rmse: 0.3228 - smape: 0.6158 - val_ia: 0.3221 - val_loss: 0.2253 - val_mae: 0.3770 - val_rmse: 0.4116 - val_smape: 0.7507

Epoch 10/64

2292/2292 - 23s - 10ms/step - ia: 0.8371 - loss: 0.1081 - mae: 0.2441 - rmse: 0.3186 - smape: 0.6067 - val_ia: 0.3289 - val_loss: 0.2194 - val_mae: 0.3677 - val_rmse: 0.4035 - val_smape: 0.7398

Epoch 11/64

2292/2292 - 24s - 10ms/step - ia: 0.8394 - loss: 0.1056 - mae: 0.2403 - rmse: 0.3150 - smape: 0.5997 - val_ia: 0.3387 - val_loss: 0.1958 - val_mae: 0.3499 - val_rmse: 0.3830 - val_smape: 0.7352

Epoch 12/64

2292/2292 - 23s - 10ms/step - ia: 0.8438 - loss: 0.1017 - mae: 0.2353 - rmse: 0.3088 - smape: 0.5841 - val_ia: 0.3358 - val_loss: 0.1624 - val_mae: 0.3248 - val_rmse: 0.3600 - val_smape: 0.7362

Epoch 13/64

2292/2292 - 23s - 10ms/step - ia: 0.8454 - loss: 0.0998 - mae: 0.2332 - rmse: 0.3056 - smape: 0.5804 - val_ia: 0.3353 - val_loss: 0.2084 - val_mae: 0.3562 - val_rmse: 0.3921 - val_smape: 0.7351

Epoch 14/64

2292/2292 - 23s - 10ms/step - ia: 0.8477 - loss: 0.0970 - mae: 0.2292 - rmse: 0.3012 - smape: 0.5728 - val_ia: 0.3142 - val_loss: 0.2141 - val_mae: 0.3624 - val_rmse: 0.4021 - val_smape: 0.7571

Epoch 15/64

2292/2292 - 23s - 10ms/step - ia: 0.8496 - loss: 0.0945 - mae: 0.2262 - rmse: 0.2970 - smape: 0.5653 - val_ia: 0.3680 - val_loss: 0.1471 - val_mae: 0.3098 - val_rmse: 0.3367 - val_smape: 0.6870

Epoch 16/64

2292/2292 - 25s - 11ms/step - ia: 0.8520 - loss: 0.0920 - mae: 0.2235 - rmse: 0.2937 - smape: 0.5605 - val_ia: 0.3613 - val_loss: 0.1356 - val_mae: 0.2951 - val_rmse: 0.3262 - val_smape: 0.6748

Epoch 17/64

2292/2292 - 23s - 10ms/step - ia: 0.8539 - loss: 0.0898 - mae: 0.2207 - rmse: 0.2897 - smape: 0.5518 - val_ia: 0.3361 - val_loss: 0.1979 - val_mae: 0.3538 - val_rmse: 0.3850 - val_smape: 0.7316

Epoch 18/64

2292/2292 - 23s - 10ms/step - ia: 0.8552 - loss: 0.0884 - mae: 0.2185 - rmse: 0.2881 - smape: 0.5455 - val_ia: 0.3830 - val_loss: 0.1258 - val_mae: 0.2831 - val_rmse: 0.3117 - val_smape: 0.6427

Epoch 19/64

2292/2292 - 23s - 10ms/step - ia: 0.8574 - loss: 0.0859 - mae: 0.2156 - rmse: 0.2833 - smape: 0.5386 - val_ia: 0.3970 - val_loss: 0.1296 - val_mae: 0.2841 - val_rmse: 0.3113 - val_smape: 0.6342

Epoch 20/64

2292/2292 - 24s - 11ms/step - ia: 0.8591 - loss: 0.0835 - mae: 0.2134 - rmse: 0.2798 - smape: 0.5358 - val_ia: 0.3899 - val_loss: 0.1364 - val_mae: 0.2919 - val_rmse: 0.3184 - val_smape: 0.6416

Epoch 21/64

2292/2292 - 23s - 10ms/step - ia: 0.8609 - loss: 0.0813 - mae: 0.2104 - rmse: 0.2757 - smape: 0.5291 - val_ia: 0.3656 - val_loss: 0.1654 - val_mae: 0.3244 - val_rmse: 0.3523 - val_smape: 0.6787

Epoch 22/64

2292/2292 - 40s - 18ms/step - ia: 0.8630 - loss: 0.0787 - mae: 0.2076 - rmse: 0.2717 - smape: 0.5220 - val_ia: 0.3662 - val_loss: 0.1452 - val_mae: 0.3036 - val_rmse: 0.3341 - val_smape: 0.6607

Epoch 23/64

2292/2292 - 23s - 10ms/step - ia: 0.8646 - loss: 0.0766 - mae: 0.2052 - rmse: 0.2682 - smape: 0.5180 - val_ia: 0.3725 - val_loss: 0.1450 - val_mae: 0.3034 - val_rmse: 0.3337 - val_smape: 0.6567

Epoch 24/64

2292/2292 - 23s - 10ms/step - ia: 0.8667 - loss: 0.0747 - mae: 0.2026 - rmse: 0.2651 - smape: 0.5098 - val_ia: 0.3832 - val_loss: 0.1367 - val_mae: 0.2941 - val_rmse: 0.3218 - val_smape: 0.6501

Epoch 25/64

2292/2292 - 23s - 10ms/step - ia: 0.8681 - loss: 0.0734 - mae: 0.2010 - rmse: 0.2625 - smape: 0.5062 - val_ia: 0.3698 - val_loss: 0.1514 - val_mae: 0.3087 - val_rmse: 0.3374 - val_smape: 0.6663

Epoch 26/64

2292/2292 - 23s - 10ms/step - ia: 0.8698 - loss: 0.0714 - mae: 0.1985 - rmse: 0.2593 - smape: 0.4997 - val_ia: 0.3745 - val_loss: 0.1504 - val_mae: 0.3100 - val_rmse: 0.3386 - val_smape: 0.6721

Epoch 27/64

2292/2292 - 41s - 18ms/step - ia: 0.8703 - loss: 0.0712 - mae: 0.1976 - rmse: 0.2583 - smape: 0.4968 - val_ia: 0.3540 - val_loss: 0.1752 - val_mae: 0.3306 - val_rmse: 0.3668 - val_smape: 0.6953

Epoch 28/64

2292/2292 - 23s - 10ms/step - ia: 0.8711 - loss: 0.0701 - mae: 0.1961 - rmse: 0.2561 - smape: 0.4949 - val_ia: 0.3262 - val_loss: 0.2190 - val_mae: 0.3688 - val_rmse: 0.4060 - val_smape: 0.7421

Epoch 29/64

2292/2292 - 23s - 10ms/step - ia: 0.8721 - loss: 0.0690 - mae: 0.1947 - rmse: 0.2545 - smape: 0.4931 - val_ia: 0.3628 - val_loss: 0.1582 - val_mae: 0.3153 - val_rmse: 0.3469 - val_smape: 0.6820

Epoch 30/64

2292/2292 - 23s - 10ms/step - ia: 0.8735 - loss: 0.0678 - mae: 0.1930 - rmse: 0.2521 - smape: 0.4893 - val_ia: 0.3422 - val_loss: 0.1840 - val_mae: 0.3415 - val_rmse: 0.3764 - val_smape: 0.7104

Epoch 31/64

2292/2292 - 23s - 10ms/step - ia: 0.8743 - loss: 0.0672 - mae: 0.1921 - rmse: 0.2509 - smape: 0.4878 - val_ia: 0.3651 - val_loss: 0.1614 - val_mae: 0.3171 - val_rmse: 0.3477 - val_smape: 0.6872

Epoch 32/64

2292/2292 - 23s - 10ms/step - ia: 0.8751 - loss: 0.0664 - mae: 0.1909 - rmse: 0.2494 - smape: 0.4841 - val_ia: 0.3663 - val_loss: 0.1609 - val_mae: 0.3170 - val_rmse: 0.3496 - val_smape: 0.6795

Epoch 33/64

2292/2292 - 22s - 10ms/step - ia: 0.8750 - loss: 0.0660 - mae: 0.1904 - rmse: 0.2485 - smape: 0.4822 - val_ia: 0.3408 - val_loss: 0.1899 - val_mae: 0.3438 - val_rmse: 0.3814 - val_smape: 0.7134

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:36 967ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 70%|███████   | 35/50 [12:42:04<4:12:13, 1008.90s/trial, best loss: 0.11133362884407784]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 29s - 25ms/step - ia: 0.3561 - loss: 0.7995 - mae: 0.7320 - rmse: 0.8810 - smape: 1.3573 - val_ia: 0.2521 - val_loss: 1.2380 - val_mae: 0.9250 - val_rmse: 0.9981 - val_smape: 1.3337

Epoch 2/32

1146/1146 - 19s - 17ms/step - ia: 0.6365 - loss: 0.4432 - mae: 0.5308 - rmse: 0.6600 - smape: 0.9011 - val_ia: 0.2509 - val_loss: 1.1797 - val_mae: 0.9111 - val_rmse: 0.9827 - val_smape: 1.3403

Epoch 3/32

1146/1146 - 19s - 16ms/step - ia: 0.6746 - loss: 0.3775 - mae: 0.4879 - rmse: 0.6094 - smape: 0.8349 - val_ia: 0.2689 - val_loss: 1.0441 - val_mae: 0.8459 - val_rmse: 0.9197 - val_smape: 1.2438

Epoch 4/32

1146/1146 - 19s - 16ms/step - ia: 0.6882 - loss: 0.3532 - mae: 0.4714 - rmse: 0.5894 - smape: 0.8126 - val_ia: 0.3056 - val_loss: 0.7646 - val_mae: 0.7006 - val_rmse: 0.7789 - val_smape: 1.1312

Epoch 5/32

1146/1146 - 19s - 17ms/step - ia: 0.6979 - loss: 0.3360 - mae: 0.4584 - rmse: 0.5750 - smape: 0.8011 - val_ia: 0.3027 - val_loss: 0.8150 - val_mae: 0.7294 - val_rmse: 0.8035 - val_smape: 1.1495

Epoch 6/32

1146/1146 - 19s - 17ms/step - ia: 0.7078 - loss: 0.3162 - mae: 0.4444 - rmse: 0.5574 - smape: 0.7881 - val_ia: 0.3106 - val_loss: 0.7411 - val_mae: 0.6958 - val_rmse: 0.7666 - val_smape: 1.1373

Epoch 7/32

1146/1146 - 19s - 17ms/step - ia: 0.7148 - loss: 0.3014 - mae: 0.4328 - rmse: 0.5445 - smape: 0.7797 - val_ia: 0.3108 - val_loss: 0.6784 - val_mae: 0.6671 - val_rmse: 0.7359 - val_smape: 1.1228

Epoch 8/32

1146/1146 - 19s - 16ms/step - ia: 0.7227 - loss: 0.2871 - mae: 0.4224 - rmse: 0.5314 - smape: 0.7743 - val_ia: 0.3279 - val_loss: 0.5595 - val_mae: 0.6085 - val_rmse: 0.6721 - val_smape: 1.0894

Epoch 9/32

1146/1146 - 19s - 17ms/step - ia: 0.7290 - loss: 0.2741 - mae: 0.4123 - rmse: 0.5191 - smape: 0.7681 - val_ia: 0.3286 - val_loss: 0.5596 - val_mae: 0.6071 - val_rmse: 0.6696 - val_smape: 1.0940

Epoch 10/32

1146/1146 - 19s - 16ms/step - ia: 0.7374 - loss: 0.2580 - mae: 0.3995 - rmse: 0.5033 - smape: 0.7652 - val_ia: 0.3280 - val_loss: 0.5940 - val_mae: 0.6217 - val_rmse: 0.6827 - val_smape: 1.0904

Epoch 11/32

1146/1146 - 18s - 16ms/step - ia: 0.7480 - loss: 0.2397 - mae: 0.3827 - rmse: 0.4851 - smape: 0.7556 - val_ia: 0.3447 - val_loss: 0.5417 - val_mae: 0.5902 - val_rmse: 0.6500 - val_smape: 1.0615

Epoch 12/32

1146/1146 - 18s - 16ms/step - ia: 0.7600 - loss: 0.2195 - mae: 0.3636 - rmse: 0.4642 - smape: 0.7428 - val_ia: 0.3591 - val_loss: 0.5814 - val_mae: 0.6001 - val_rmse: 0.6624 - val_smape: 1.0477

Epoch 13/32

1146/1146 - 21s - 18ms/step - ia: 0.7725 - loss: 0.1997 - mae: 0.3443 - rmse: 0.4426 - smape: 0.7285 - val_ia: 0.3826 - val_loss: 0.4801 - val_mae: 0.5448 - val_rmse: 0.6040 - val_smape: 0.9726

Epoch 14/32

1146/1146 - 19s - 17ms/step - ia: 0.7840 - loss: 0.1826 - mae: 0.3270 - rmse: 0.4226 - smape: 0.7080 - val_ia: 0.4072 - val_loss: 0.3787 - val_mae: 0.4889 - val_rmse: 0.5425 - val_smape: 0.9156

Epoch 15/32

1146/1146 - 19s - 16ms/step - ia: 0.7907 - loss: 0.1732 - mae: 0.3175 - rmse: 0.4116 - smape: 0.6965 - val_ia: 0.4204 - val_loss: 0.3296 - val_mae: 0.4587 - val_rmse: 0.5095 - val_smape: 0.8820

Epoch 16/32

1146/1146 - 18s - 16ms/step - ia: 0.7957 - loss: 0.1657 - mae: 0.3092 - rmse: 0.4025 - smape: 0.6847 - val_ia: 0.4253 - val_loss: 0.3027 - val_mae: 0.4432 - val_rmse: 0.4932 - val_smape: 0.8630

Epoch 17/32

1146/1146 - 20s - 18ms/step - ia: 0.8003 - loss: 0.1604 - mae: 0.3032 - rmse: 0.3955 - smape: 0.6754 - val_ia: 0.4536 - val_loss: 0.2402 - val_mae: 0.4001 - val_rmse: 0.4468 - val_smape: 0.8228

Epoch 18/32

1146/1146 - 18s - 16ms/step - ia: 0.8033 - loss: 0.1573 - mae: 0.2994 - rmse: 0.3918 - smape: 0.6667 - val_ia: 0.4507 - val_loss: 0.2567 - val_mae: 0.4103 - val_rmse: 0.4569 - val_smape: 0.8194

Epoch 19/32

1146/1146 - 24s - 21ms/step - ia: 0.8058 - loss: 0.1539 - mae: 0.2959 - rmse: 0.3873 - smape: 0.6608 - val_ia: 0.4487 - val_loss: 0.2577 - val_mae: 0.4093 - val_rmse: 0.4603 - val_smape: 0.8177

Epoch 20/32

1146/1146 - 19s - 17ms/step - ia: 0.8091 - loss: 0.1500 - mae: 0.2913 - rmse: 0.3824 - smape: 0.6544 - val_ia: 0.4575 - val_loss: 0.2513 - val_mae: 0.4027 - val_rmse: 0.4535 - val_smape: 0.8015

Epoch 21/32

1146/1146 - 19s - 17ms/step - ia: 0.8105 - loss: 0.1484 - mae: 0.2893 - rmse: 0.3803 - smape: 0.6531 - val_ia: 0.4697 - val_loss: 0.2106 - val_mae: 0.3763 - val_rmse: 0.4219 - val_smape: 0.7906

Epoch 22/32

1146/1146 - 20s - 18ms/step - ia: 0.8116 - loss: 0.1463 - mae: 0.2873 - rmse: 0.3775 - smape: 0.6498 - val_ia: 0.4673 - val_loss: 0.2222 - val_mae: 0.3828 - val_rmse: 0.4301 - val_smape: 0.7857

Epoch 23/32

1146/1146 - 19s - 16ms/step - ia: 0.8132 - loss: 0.1441 - mae: 0.2849 - rmse: 0.3745 - smape: 0.6461 - val_ia: 0.4488 - val_loss: 0.2781 - val_mae: 0.4167 - val_rmse: 0.4742 - val_smape: 0.8052

Epoch 24/32

1146/1146 - 20s - 18ms/step - ia: 0.8148 - loss: 0.1419 - mae: 0.2830 - rmse: 0.3717 - smape: 0.6428 - val_ia: 0.4578 - val_loss: 0.2353 - val_mae: 0.3909 - val_rmse: 0.4445 - val_smape: 0.8019

Epoch 25/32

1146/1146 - 18s - 16ms/step - ia: 0.8173 - loss: 0.1391 - mae: 0.2796 - rmse: 0.3679 - smape: 0.6399 - val_ia: 0.4689 - val_loss: 0.2333 - val_mae: 0.3850 - val_rmse: 0.4390 - val_smape: 0.7811

Epoch 26/32

1146/1146 - 18s - 16ms/step - ia: 0.8180 - loss: 0.1373 - mae: 0.2781 - rmse: 0.3654 - smape: 0.6358 - val_ia: 0.4789 - val_loss: 0.2142 - val_mae: 0.3724 - val_rmse: 0.4196 - val_smape: 0.7627

Epoch 27/32

1146/1146 - 18s - 16ms/step - ia: 0.8221 - loss: 0.1326 - mae: 0.2725 - rmse: 0.3595 - smape: 0.6259 - val_ia: 0.4814 - val_loss: 0.2144 - val_mae: 0.3702 - val_rmse: 0.4226 - val_smape: 0.7825

Epoch 28/32

1146/1146 - 21s - 18ms/step - ia: 0.8252 - loss: 0.1282 - mae: 0.2684 - rmse: 0.3530 - smape: 0.6232 - val_ia: 0.4824 - val_loss: 0.2033 - val_mae: 0.3625 - val_rmse: 0.4119 - val_smape: 0.7679

Epoch 29/32

1146/1146 - 20s - 18ms/step - ia: 0.8301 - loss: 0.1226 - mae: 0.2619 - rmse: 0.3449 - smape: 0.6166 - val_ia: 0.4904 - val_loss: 0.2053 - val_mae: 0.3623 - val_rmse: 0.4100 - val_smape: 0.7688

Epoch 30/32

1146/1146 - 19s - 17ms/step - ia: 0.8334 - loss: 0.1185 - mae: 0.2574 - rmse: 0.3389 - smape: 0.6178 - val_ia: 0.4895 - val_loss: 0.1933 - val_mae: 0.3541 - val_rmse: 0.4036 - val_smape: 0.7893

Epoch 31/32

1146/1146 - 19s - 16ms/step - ia: 0.8344 - loss: 0.1161 - mae: 0.2551 - rmse: 0.3355 - smape: 0.6206 - val_ia: 0.5139 - val_loss: 0.1715 - val_mae: 0.3341 - val_rmse: 0.3776 - val_smape: 0.7479

Epoch 32/32

1146/1146 - 19s - 16ms/step - ia: 0.8361 - loss: 0.1143 - mae: 0.2527 - rmse: 0.3330 - smape: 0.6163 - val_ia: 0.5103 - val_loss: 0.1533 - val_mae: 0.3240 - val_rmse: 0.3645 - val_smape: 0.7758

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:09 1s/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 72%|███████▏  | 36/50 [12:52:34<3:28:52, 895.19s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 19s - 17ms/step - ia: 0.1307 - loss: 0.9951 - mae: 0.8298 - rmse: 0.9931 - smape: 1.8777 - val_ia: 0.2430 - val_loss: 0.8335 - val_mae: 0.7581 - val_rmse: 0.8340 - val_smape: 1.7675

Epoch 2/32

1146/1146 - 11s - 9ms/step - ia: 0.1329 - loss: 0.9832 - mae: 0.8260 - rmse: 0.9867 - smape: 1.8590 - val_ia: 0.2457 - val_loss: 0.8212 - val_mae: 0.7520 - val_rmse: 0.8283 - val_smape: 1.7361

Epoch 3/32

1146/1146 - 11s - 9ms/step - ia: 0.1417 - loss: 0.9689 - mae: 0.8213 - rmse: 0.9798 - smape: 1.8206 - val_ia: 0.2479 - val_loss: 0.8036 - val_mae: 0.7434 - val_rmse: 0.8200 - val_smape: 1.6955

Epoch 4/32

1146/1146 - 11s - 9ms/step - ia: 0.1500 - loss: 0.9488 - mae: 0.8144 - rmse: 0.9695 - smape: 1.7705 - val_ia: 0.2510 - val_loss: 0.7777 - val_mae: 0.7306 - val_rmse: 0.8076 - val_smape: 1.6441

Epoch 5/32

1146/1146 - 11s - 9ms/step - ia: 0.1680 - loss: 0.9220 - mae: 0.8047 - rmse: 0.9555 - smape: 1.7100 - val_ia: 0.2568 - val_loss: 0.7458 - val_mae: 0.7146 - val_rmse: 0.7921 - val_smape: 1.5791

Epoch 6/32

1146/1146 - 11s - 9ms/step - ia: 0.1954 - loss: 0.8876 - mae: 0.7916 - rmse: 0.9376 - smape: 1.6413 - val_ia: 0.2615 - val_loss: 0.7083 - val_mae: 0.6953 - val_rmse: 0.7729 - val_smape: 1.5056

Epoch 7/32

1146/1146 - 11s - 10ms/step - ia: 0.2346 - loss: 0.8434 - mae: 0.7729 - rmse: 0.9141 - smape: 1.5640 - val_ia: 0.2699 - val_loss: 0.6632 - val_mae: 0.6688 - val_rmse: 0.7473 - val_smape: 1.4203

Epoch 8/32

1146/1146 - 11s - 9ms/step - ia: 0.2835 - loss: 0.7862 - mae: 0.7452 - rmse: 0.8823 - smape: 1.4747 - val_ia: 0.2867 - val_loss: 0.6140 - val_mae: 0.6334 - val_rmse: 0.7153 - val_smape: 1.3261

Epoch 9/32

1146/1146 - 11s - 9ms/step - ia: 0.3476 - loss: 0.7145 - mae: 0.7048 - rmse: 0.8411 - smape: 1.3724 - val_ia: 0.3136 - val_loss: 0.5684 - val_mae: 0.5946 - val_rmse: 0.6809 - val_smape: 1.2266

Epoch 10/32

1146/1146 - 11s - 9ms/step - ia: 0.4237 - loss: 0.6287 - mae: 0.6496 - rmse: 0.7885 - smape: 1.2545 - val_ia: 0.3406 - val_loss: 0.5484 - val_mae: 0.5734 - val_rmse: 0.6590 - val_smape: 1.1434

Epoch 11/32

1146/1146 - 11s - 9ms/step - ia: 0.5059 - loss: 0.5413 - mae: 0.5888 - rmse: 0.7305 - smape: 1.1109 - val_ia: 0.3504 - val_loss: 0.5765 - val_mae: 0.5839 - val_rmse: 0.6687 - val_smape: 1.0949

Epoch 12/32

1146/1146 - 11s - 9ms/step - ia: 0.5647 - loss: 0.4792 - mae: 0.5493 - rmse: 0.6875 - smape: 1.0031 - val_ia: 0.3440 - val_loss: 0.6178 - val_mae: 0.6063 - val_rmse: 0.6894 - val_smape: 1.0850

Epoch 13/32

1146/1146 - 11s - 9ms/step - ia: 0.5992 - loss: 0.4405 - mae: 0.5278 - rmse: 0.6594 - smape: 0.9465 - val_ia: 0.3379 - val_loss: 0.6446 - val_mae: 0.6225 - val_rmse: 0.7030 - val_smape: 1.0833

Epoch 14/32

1146/1146 - 11s - 9ms/step - ia: 0.6233 - loss: 0.4138 - mae: 0.5137 - rmse: 0.6390 - smape: 0.9126 - val_ia: 0.3339 - val_loss: 0.6588 - val_mae: 0.6337 - val_rmse: 0.7116 - val_smape: 1.0887

Epoch 15/32

1146/1146 - 20s - 18ms/step - ia: 0.6383 - loss: 0.3930 - mae: 0.5021 - rmse: 0.6226 - smape: 0.8897 - val_ia: 0.3341 - val_loss: 0.6680 - val_mae: 0.6419 - val_rmse: 0.7178 - val_smape: 1.0942

Epoch 16/32

1146/1146 - 10s - 9ms/step - ia: 0.6514 - loss: 0.3756 - mae: 0.4917 - rmse: 0.6087 - smape: 0.8699 - val_ia: 0.3350 - val_loss: 0.6762 - val_mae: 0.6490 - val_rmse: 0.7235 - val_smape: 1.1002

Epoch 17/32

1146/1146 - 20s - 18ms/step - ia: 0.6623 - loss: 0.3608 - mae: 0.4823 - rmse: 0.5966 - smape: 0.8537 - val_ia: 0.3361 - val_loss: 0.6805 - val_mae: 0.6527 - val_rmse: 0.7266 - val_smape: 1.1008

Epoch 18/32

1146/1146 - 10s - 9ms/step - ia: 0.6706 - loss: 0.3479 - mae: 0.4737 - rmse: 0.5857 - smape: 0.8400 - val_ia: 0.3378 - val_loss: 0.6776 - val_mae: 0.6527 - val_rmse: 0.7260 - val_smape: 1.0997

Epoch 19/32

1146/1146 - 11s - 9ms/step - ia: 0.6794 - loss: 0.3363 - mae: 0.4654 - rmse: 0.5760 - smape: 0.8270 - val_ia: 0.3381 - val_loss: 0.6816 - val_mae: 0.6549 - val_rmse: 0.7282 - val_smape: 1.0981

Epoch 20/32

1146/1146 - 11s - 9ms/step - ia: 0.6870 - loss: 0.3259 - mae: 0.4577 - rmse: 0.5669 - smape: 0.8158 - val_ia: 0.3372 - val_loss: 0.6883 - val_mae: 0.6593 - val_rmse: 0.7325 - val_smape: 1.1010

Epoch 21/32

1146/1146 - 11s - 9ms/step - ia: 0.6936 - loss: 0.3166 - mae: 0.4502 - rmse: 0.5584 - smape: 0.8043 - val_ia: 0.3367 - val_loss: 0.6915 - val_mae: 0.6601 - val_rmse: 0.7335 - val_smape: 1.0993

Epoch 22/32

1146/1146 - 22s - 19ms/step - ia: 0.7008 - loss: 0.3081 - mae: 0.4431 - rmse: 0.5512 - smape: 0.7949 - val_ia: 0.3347 - val_loss: 0.7059 - val_mae: 0.6665 - val_rmse: 0.7404 - val_smape: 1.1022

Epoch 23/32

1146/1146 - 13s - 11ms/step - ia: 0.7067 - loss: 0.3003 - mae: 0.4363 - rmse: 0.5441 - smape: 0.7851 - val_ia: 0.3324 - val_loss: 0.7243 - val_mae: 0.6738 - val_rmse: 0.7487 - val_smape: 1.1060

Epoch 24/32

1146/1146 - 12s - 10ms/step - ia: 0.7118 - loss: 0.2934 - mae: 0.4301 - rmse: 0.5376 - smape: 0.7777 - val_ia: 0.3326 - val_loss: 0.7266 - val_mae: 0.6727 - val_rmse: 0.7481 - val_smape: 1.1015

Epoch 25/32

1146/1146 - 11s - 10ms/step - ia: 0.7173 - loss: 0.2870 - mae: 0.4241 - rmse: 0.5318 - smape: 0.7695 - val_ia: 0.3312 - val_loss: 0.7393 - val_mae: 0.6763 - val_rmse: 0.7526 - val_smape: 1.1019

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:37 974ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 74%|███████▍  | 37/50 [12:57:47<2:36:09, 720.74s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 24s - 21ms/step - ia: 0.5193 - loss: 0.5490 - mae: 0.5926 - rmse: 0.7260 - smape: 1.1065 - val_ia: 0.2636 - val_loss: 1.1513 - val_mae: 0.8940 - val_rmse: 0.9689 - val_smape: 1.2936

Epoch 2/32

1146/1146 - 14s - 12ms/step - ia: 0.6801 - loss: 0.3501 - mae: 0.4746 - rmse: 0.5874 - smape: 0.8330 - val_ia: 0.2915 - val_loss: 0.8661 - val_mae: 0.7622 - val_rmse: 0.8364 - val_smape: 1.2015

Epoch 3/32

1146/1146 - 13s - 12ms/step - ia: 0.7093 - loss: 0.3009 - mae: 0.4369 - rmse: 0.5438 - smape: 0.7909 - val_ia: 0.3120 - val_loss: 0.6525 - val_mae: 0.6502 - val_rmse: 0.7206 - val_smape: 1.0652

Epoch 4/32

1146/1146 - 21s - 18ms/step - ia: 0.7405 - loss: 0.2514 - mae: 0.3931 - rmse: 0.4964 - smape: 0.7653 - val_ia: 0.3701 - val_loss: 0.4696 - val_mae: 0.5382 - val_rmse: 0.6065 - val_smape: 0.9564

Epoch 5/32

1146/1146 - 14s - 12ms/step - ia: 0.7614 - loss: 0.2150 - mae: 0.3606 - rmse: 0.4591 - smape: 0.7449 - val_ia: 0.4056 - val_loss: 0.4017 - val_mae: 0.4949 - val_rmse: 0.5609 - val_smape: 0.9361

Epoch 6/32

1146/1146 - 14s - 12ms/step - ia: 0.7752 - loss: 0.1942 - mae: 0.3417 - rmse: 0.4361 - smape: 0.7201 - val_ia: 0.4386 - val_loss: 0.3249 - val_mae: 0.4490 - val_rmse: 0.5057 - val_smape: 0.9124

Epoch 7/32

1146/1146 - 14s - 12ms/step - ia: 0.7889 - loss: 0.1736 - mae: 0.3225 - rmse: 0.4120 - smape: 0.6995 - val_ia: 0.4566 - val_loss: 0.3025 - val_mae: 0.4322 - val_rmse: 0.4848 - val_smape: 0.8841

Epoch 8/32

1146/1146 - 14s - 12ms/step - ia: 0.7970 - loss: 0.1629 - mae: 0.3112 - rmse: 0.3994 - smape: 0.6818 - val_ia: 0.4575 - val_loss: 0.3128 - val_mae: 0.4368 - val_rmse: 0.4911 - val_smape: 0.8716

Epoch 9/32

1146/1146 - 14s - 12ms/step - ia: 0.8038 - loss: 0.1544 - mae: 0.3015 - rmse: 0.3881 - smape: 0.6695 - val_ia: 0.4746 - val_loss: 0.2876 - val_mae: 0.4150 - val_rmse: 0.4674 - val_smape: 0.8305

Epoch 10/32

1146/1146 - 14s - 12ms/step - ia: 0.8081 - loss: 0.1478 - mae: 0.2951 - rmse: 0.3799 - smape: 0.6601 - val_ia: 0.4732 - val_loss: 0.3008 - val_mae: 0.4215 - val_rmse: 0.4769 - val_smape: 0.8182

Epoch 11/32

1146/1146 - 15s - 13ms/step - ia: 0.8125 - loss: 0.1433 - mae: 0.2889 - rmse: 0.3737 - smape: 0.6507 - val_ia: 0.4815 - val_loss: 0.2992 - val_mae: 0.4180 - val_rmse: 0.4722 - val_smape: 0.8023

Epoch 12/32

1146/1146 - 20s - 17ms/step - ia: 0.8158 - loss: 0.1383 - mae: 0.2841 - rmse: 0.3673 - smape: 0.6445 - val_ia: 0.4910 - val_loss: 0.2707 - val_mae: 0.4009 - val_rmse: 0.4539 - val_smape: 0.7829

Epoch 13/32

1146/1146 - 14s - 12ms/step - ia: 0.8182 - loss: 0.1351 - mae: 0.2802 - rmse: 0.3628 - smape: 0.6375 - val_ia: 0.4865 - val_loss: 0.2835 - val_mae: 0.4065 - val_rmse: 0.4637 - val_smape: 0.7862

Epoch 14/32

1146/1146 - 14s - 12ms/step - ia: 0.8196 - loss: 0.1334 - mae: 0.2786 - rmse: 0.3605 - smape: 0.6344 - val_ia: 0.4978 - val_loss: 0.2632 - val_mae: 0.3940 - val_rmse: 0.4466 - val_smape: 0.7642

Epoch 15/32

1146/1146 - 14s - 12ms/step - ia: 0.8223 - loss: 0.1301 - mae: 0.2742 - rmse: 0.3563 - smape: 0.6267 - val_ia: 0.5010 - val_loss: 0.2653 - val_mae: 0.3928 - val_rmse: 0.4459 - val_smape: 0.7603

Epoch 16/32

1146/1146 - 14s - 12ms/step - ia: 0.8238 - loss: 0.1280 - mae: 0.2721 - rmse: 0.3531 - smape: 0.6226 - val_ia: 0.4982 - val_loss: 0.2623 - val_mae: 0.3907 - val_rmse: 0.4445 - val_smape: 0.7619

Epoch 17/32

1146/1146 - 13s - 12ms/step - ia: 0.8269 - loss: 0.1244 - mae: 0.2674 - rmse: 0.3484 - smape: 0.6188 - val_ia: 0.5026 - val_loss: 0.2500 - val_mae: 0.3829 - val_rmse: 0.4357 - val_smape: 0.7540

Epoch 18/32

1146/1146 - 13s - 12ms/step - ia: 0.8268 - loss: 0.1240 - mae: 0.2671 - rmse: 0.3478 - smape: 0.6152 - val_ia: 0.5008 - val_loss: 0.2675 - val_mae: 0.3922 - val_rmse: 0.4462 - val_smape: 0.7548

Epoch 19/32

1146/1146 - 13s - 12ms/step - ia: 0.8291 - loss: 0.1219 - mae: 0.2645 - rmse: 0.3444 - smape: 0.6091 - val_ia: 0.4979 - val_loss: 0.2567 - val_mae: 0.3875 - val_rmse: 0.4422 - val_smape: 0.7604

Epoch 20/32

1146/1146 - 13s - 12ms/step - ia: 0.8298 - loss: 0.1211 - mae: 0.2636 - rmse: 0.3434 - smape: 0.6091 - val_ia: 0.5034 - val_loss: 0.2489 - val_mae: 0.3791 - val_rmse: 0.4332 - val_smape: 0.7461

Epoch 21/32

1146/1146 - 13s - 12ms/step - ia: 0.8307 - loss: 0.1194 - mae: 0.2624 - rmse: 0.3408 - smape: 0.6092 - val_ia: 0.4993 - val_loss: 0.2525 - val_mae: 0.3833 - val_rmse: 0.4378 - val_smape: 0.7522

Epoch 22/32

1146/1146 - 13s - 12ms/step - ia: 0.8324 - loss: 0.1179 - mae: 0.2600 - rmse: 0.3385 - smape: 0.6047 - val_ia: 0.5099 - val_loss: 0.2454 - val_mae: 0.3770 - val_rmse: 0.4292 - val_smape: 0.7335

Epoch 23/32

1146/1146 - 13s - 12ms/step - ia: 0.8330 - loss: 0.1172 - mae: 0.2592 - rmse: 0.3377 - smape: 0.6012 - val_ia: 0.5048 - val_loss: 0.2454 - val_mae: 0.3772 - val_rmse: 0.4290 - val_smape: 0.7436

Epoch 24/32

1146/1146 - 13s - 12ms/step - ia: 0.8341 - loss: 0.1154 - mae: 0.2574 - rmse: 0.3353 - smape: 0.5980 - val_ia: 0.5111 - val_loss: 0.2238 - val_mae: 0.3617 - val_rmse: 0.4134 - val_smape: 0.7279

Epoch 25/32

1146/1146 - 17s - 14ms/step - ia: 0.8348 - loss: 0.1143 - mae: 0.2558 - rmse: 0.3336 - smape: 0.5972 - val_ia: 0.5046 - val_loss: 0.2479 - val_mae: 0.3769 - val_rmse: 0.4319 - val_smape: 0.7343

Epoch 26/32

1146/1146 - 15s - 13ms/step - ia: 0.8355 - loss: 0.1133 - mae: 0.2551 - rmse: 0.3317 - smape: 0.5978 - val_ia: 0.5049 - val_loss: 0.2477 - val_mae: 0.3777 - val_rmse: 0.4317 - val_smape: 0.7395

Epoch 27/32

1146/1146 - 14s - 12ms/step - ia: 0.8368 - loss: 0.1117 - mae: 0.2528 - rmse: 0.3299 - smape: 0.5936 - val_ia: 0.5207 - val_loss: 0.2128 - val_mae: 0.3550 - val_rmse: 0.4021 - val_smape: 0.7071

Epoch 28/32

1146/1146 - 14s - 12ms/step - ia: 0.8368 - loss: 0.1116 - mae: 0.2529 - rmse: 0.3294 - smape: 0.5919 - val_ia: 0.5062 - val_loss: 0.2509 - val_mae: 0.3794 - val_rmse: 0.4314 - val_smape: 0.7339

Epoch 29/32

1146/1146 - 14s - 12ms/step - ia: 0.8374 - loss: 0.1108 - mae: 0.2521 - rmse: 0.3281 - smape: 0.5926 - val_ia: 0.5095 - val_loss: 0.2348 - val_mae: 0.3682 - val_rmse: 0.4192 - val_smape: 0.7310

Epoch 30/32

1146/1146 - 14s - 13ms/step - ia: 0.8393 - loss: 0.1090 - mae: 0.2495 - rmse: 0.3256 - smape: 0.5875 - val_ia: 0.5074 - val_loss: 0.2413 - val_mae: 0.3726 - val_rmse: 0.4273 - val_smape: 0.7289

Epoch 31/32

1146/1146 - 13s - 12ms/step - ia: 0.8402 - loss: 0.1077 - mae: 0.2476 - rmse: 0.3234 - smape: 0.5813 - val_ia: 0.5081 - val_loss: 0.2321 - val_mae: 0.3677 - val_rmse: 0.4200 - val_smape: 0.7266

Epoch 32/32

1146/1146 - 13s - 12ms/step - ia: 0.8406 - loss: 0.1073 - mae: 0.2475 - rmse: 0.3227 - smape: 0.5838 - val_ia: 0.5085 - val_loss: 0.2365 - val_mae: 0.3698 - val_rmse: 0.4229 - val_smape: 0.7252

Restoring model weights from the end of the best epoch: 27.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:00 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step

 76%|███████▌  | 38/50 [13:05:37<2:09:06, 645.55s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 25s - 22ms/step - ia: 0.1363 - loss: 1.0056 - mae: 0.8327 - rmse: 0.9980 - smape: 1.8549 - val_ia: 0.2362 - val_loss: 0.8625 - val_mae: 0.7730 - val_rmse: 0.8468 - val_smape: 1.9474

Epoch 2/32

1146/1146 - 17s - 14ms/step - ia: 0.1254 - loss: 0.9994 - mae: 0.8296 - rmse: 0.9950 - smape: 1.9384 - val_ia: 0.2374 - val_loss: 0.8587 - val_mae: 0.7711 - val_rmse: 0.8451 - val_smape: 1.9832

Epoch 3/32

1146/1146 - 16s - 14ms/step - ia: 0.1282 - loss: 0.9990 - mae: 0.8295 - rmse: 0.9949 - smape: 1.9453 - val_ia: 0.2370 - val_loss: 0.8596 - val_mae: 0.7716 - val_rmse: 0.8455 - val_smape: 1.9844

Epoch 4/32

1146/1146 - 17s - 14ms/step - ia: 0.1281 - loss: 0.9981 - mae: 0.8292 - rmse: 0.9945 - smape: 1.9459 - val_ia: 0.2382 - val_loss: 0.8544 - val_mae: 0.7690 - val_rmse: 0.8433 - val_smape: 1.9221

Epoch 5/32

1146/1146 - 17s - 15ms/step - ia: 0.1320 - loss: 0.9962 - mae: 0.8285 - rmse: 0.9935 - smape: 1.9480 - val_ia: 0.2379 - val_loss: 0.8539 - val_mae: 0.7689 - val_rmse: 0.8431 - val_smape: 1.9406

Epoch 6/32

1146/1146 - 17s - 15ms/step - ia: 0.1306 - loss: 0.9921 - mae: 0.8272 - rmse: 0.9913 - smape: 1.9299 - val_ia: 0.2363 - val_loss: 0.8557 - val_mae: 0.7701 - val_rmse: 0.8438 - val_smape: 1.9219

Epoch 7/32

1146/1146 - 17s - 15ms/step - ia: 0.1355 - loss: 0.9821 - mae: 0.8238 - rmse: 0.9862 - smape: 1.8818 - val_ia: 0.2378 - val_loss: 0.8413 - val_mae: 0.7634 - val_rmse: 0.8374 - val_smape: 1.8386

Epoch 8/32

1146/1146 - 17s - 15ms/step - ia: 0.1481 - loss: 0.9570 - mae: 0.8157 - rmse: 0.9736 - smape: 1.7817 - val_ia: 0.2408 - val_loss: 0.8139 - val_mae: 0.7501 - val_rmse: 0.8248 - val_smape: 1.6767

Epoch 9/32

1146/1146 - 17s - 14ms/step - ia: 0.1957 - loss: 0.9094 - mae: 0.8002 - rmse: 0.9493 - smape: 1.6270 - val_ia: 0.2397 - val_loss: 0.7903 - val_mae: 0.7359 - val_rmse: 0.8113 - val_smape: 1.4786

Epoch 10/32

1146/1146 - 21s - 18ms/step - ia: 0.2623 - loss: 0.8586 - mae: 0.7824 - rmse: 0.9226 - smape: 1.4860 - val_ia: 0.2408 - val_loss: 0.7758 - val_mae: 0.7244 - val_rmse: 0.8013 - val_smape: 1.3591

Epoch 11/32

1146/1146 - 20s - 17ms/step - ia: 0.3160 - loss: 0.8179 - mae: 0.7659 - rmse: 0.9007 - smape: 1.4029 - val_ia: 0.2388 - val_loss: 0.7830 - val_mae: 0.7236 - val_rmse: 0.7998 - val_smape: 1.3011

Epoch 12/32

1146/1146 - 16s - 14ms/step - ia: 0.3555 - loss: 0.7768 - mae: 0.7467 - rmse: 0.8776 - smape: 1.3473 - val_ia: 0.2381 - val_loss: 0.7952 - val_mae: 0.7258 - val_rmse: 0.8006 - val_smape: 1.2688

Epoch 13/32

1146/1146 - 16s - 14ms/step - ia: 0.3965 - loss: 0.7275 - mae: 0.7218 - rmse: 0.8493 - smape: 1.2939 - val_ia: 0.2448 - val_loss: 0.8232 - val_mae: 0.7349 - val_rmse: 0.8082 - val_smape: 1.2511

Epoch 14/32

1146/1146 - 20s - 18ms/step - ia: 0.4389 - loss: 0.6706 - mae: 0.6901 - rmse: 0.8151 - smape: 1.2260 - val_ia: 0.2573 - val_loss: 0.9194 - val_mae: 0.7752 - val_rmse: 0.8476 - val_smape: 1.2600

Epoch 15/32

1146/1146 - 17s - 14ms/step - ia: 0.4847 - loss: 0.6151 - mae: 0.6557 - rmse: 0.7806 - smape: 1.1523 - val_ia: 0.2637 - val_loss: 1.0268 - val_mae: 0.8244 - val_rmse: 0.8967 - val_smape: 1.2827

Epoch 16/32

1146/1146 - 16s - 14ms/step - ia: 0.5226 - loss: 0.5748 - mae: 0.6279 - rmse: 0.7543 - smape: 1.0927 - val_ia: 0.2617 - val_loss: 1.1179 - val_mae: 0.8681 - val_rmse: 0.9399 - val_smape: 1.3038

Epoch 17/32

1146/1146 - 16s - 14ms/step - ia: 0.5481 - loss: 0.5530 - mae: 0.6102 - rmse: 0.7390 - smape: 1.0516 - val_ia: 0.2523 - val_loss: 1.2452 - val_mae: 0.9269 - val_rmse: 0.9985 - val_smape: 1.3363

Epoch 18/32

1146/1146 - 16s - 14ms/step - ia: 0.5623 - loss: 0.5412 - mae: 0.6000 - rmse: 0.7312 - smape: 1.0296 - val_ia: 0.2502 - val_loss: 1.2709 - val_mae: 0.9395 - val_rmse: 1.0106 - val_smape: 1.3453

Epoch 19/32

1146/1146 - 16s - 14ms/step - ia: 0.5711 - loss: 0.5329 - mae: 0.5932 - rmse: 0.7252 - smape: 1.0185 - val_ia: 0.2503 - val_loss: 1.2685 - val_mae: 0.9383 - val_rmse: 1.0096 - val_smape: 1.3447

Epoch 20/32

1146/1146 - 16s - 14ms/step - ia: 0.5767 - loss: 0.5259 - mae: 0.5877 - rmse: 0.7203 - smape: 1.0083 - val_ia: 0.2448 - val_loss: 1.3288 - val_mae: 0.9655 - val_rmse: 1.0366 - val_smape: 1.3614

Epoch 21/32

1146/1146 - 16s - 14ms/step - ia: 0.5803 - loss: 0.5195 - mae: 0.5834 - rmse: 0.7161 - smape: 1.0025 - val_ia: 0.2455 - val_loss: 1.3200 - val_mae: 0.9613 - val_rmse: 1.0328 - val_smape: 1.3592

Epoch 22/32

1146/1146 - 16s - 14ms/step - ia: 0.5843 - loss: 0.5135 - mae: 0.5794 - rmse: 0.7116 - smape: 0.9964 - val_ia: 0.2389 - val_loss: 1.3921 - val_mae: 0.9926 - val_rmse: 1.0639 - val_smape: 1.3748

Epoch 23/32

1146/1146 - 17s - 14ms/step - ia: 0.5879 - loss: 0.5074 - mae: 0.5754 - rmse: 0.7077 - smape: 0.9905 - val_ia: 0.2438 - val_loss: 1.3355 - val_mae: 0.9668 - val_rmse: 1.0390 - val_smape: 1.3599

Epoch 24/32

1146/1146 - 17s - 14ms/step - ia: 0.5923 - loss: 0.5014 - mae: 0.5716 - rmse: 0.7034 - smape: 0.9837 - val_ia: 0.2424 - val_loss: 1.3487 - val_mae: 0.9727 - val_rmse: 1.0450 - val_smape: 1.3632

Epoch 25/32

1146/1146 - 17s - 14ms/step - ia: 0.5960 - loss: 0.4957 - mae: 0.5679 - rmse: 0.6990 - smape: 0.9784 - val_ia: 0.2399 - val_loss: 1.3727 - val_mae: 0.9834 - val_rmse: 1.0556 - val_smape: 1.3701

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 10.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:55 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 78%|███████▊  | 39/50 [13:12:54<1:46:51, 582.91s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 20s - 17ms/step - ia: 0.4760 - loss: 0.6150 - mae: 0.6211 - rmse: 0.7690 - smape: 1.2167 - val_ia: 0.3215 - val_loss: 0.7856 - val_mae: 0.6917 - val_rmse: 0.7764 - val_smape: 1.0977

Epoch 2/32

1146/1146 - 19s - 17ms/step - ia: 0.6465 - loss: 0.4008 - mae: 0.5020 - rmse: 0.6279 - smape: 0.8893 - val_ia: 0.3308 - val_loss: 0.6785 - val_mae: 0.6557 - val_rmse: 0.7280 - val_smape: 1.1502

Epoch 3/32

1146/1146 - 10s - 9ms/step - ia: 0.6837 - loss: 0.3455 - mae: 0.4614 - rmse: 0.5829 - smape: 0.8418 - val_ia: 0.3606 - val_loss: 0.4130 - val_mae: 0.5338 - val_rmse: 0.5895 - val_smape: 1.0769

Epoch 4/32

1146/1146 - 11s - 9ms/step - ia: 0.7003 - loss: 0.3188 - mae: 0.4398 - rmse: 0.5597 - smape: 0.8133 - val_ia: 0.3751 - val_loss: 0.3834 - val_mae: 0.5094 - val_rmse: 0.5664 - val_smape: 1.0442

Epoch 5/32

1146/1146 - 11s - 9ms/step - ia: 0.7129 - loss: 0.2979 - mae: 0.4225 - rmse: 0.5403 - smape: 0.7949 - val_ia: 0.3819 - val_loss: 0.3853 - val_mae: 0.5097 - val_rmse: 0.5656 - val_smape: 1.0327

Epoch 6/32

1146/1146 - 11s - 10ms/step - ia: 0.7255 - loss: 0.2758 - mae: 0.4064 - rmse: 0.5200 - smape: 0.7778 - val_ia: 0.3911 - val_loss: 0.3758 - val_mae: 0.5024 - val_rmse: 0.5570 - val_smape: 1.0177

Epoch 7/32

1146/1146 - 11s - 9ms/step - ia: 0.7374 - loss: 0.2559 - mae: 0.3902 - rmse: 0.5007 - smape: 0.7605 - val_ia: 0.4008 - val_loss: 0.3502 - val_mae: 0.4886 - val_rmse: 0.5384 - val_smape: 1.0067

Epoch 8/32

1146/1146 - 21s - 18ms/step - ia: 0.7470 - loss: 0.2416 - mae: 0.3773 - rmse: 0.4864 - smape: 0.7503 - val_ia: 0.4049 - val_loss: 0.3281 - val_mae: 0.4768 - val_rmse: 0.5226 - val_smape: 1.0136

Epoch 9/32

1146/1146 - 21s - 18ms/step - ia: 0.7521 - loss: 0.2311 - mae: 0.3701 - rmse: 0.4755 - smape: 0.7454 - val_ia: 0.4074 - val_loss: 0.3367 - val_mae: 0.4795 - val_rmse: 0.5249 - val_smape: 1.0108

Epoch 10/32

1146/1146 - 11s - 9ms/step - ia: 0.7580 - loss: 0.2212 - mae: 0.3616 - rmse: 0.4653 - smape: 0.7403 - val_ia: 0.3941 - val_loss: 0.3488 - val_mae: 0.4902 - val_rmse: 0.5384 - val_smape: 1.0449

Epoch 11/32

1146/1146 - 10s - 9ms/step - ia: 0.7627 - loss: 0.2147 - mae: 0.3556 - rmse: 0.4586 - smape: 0.7329 - val_ia: 0.4017 - val_loss: 0.3320 - val_mae: 0.4795 - val_rmse: 0.5222 - val_smape: 1.0428

Epoch 12/32

1146/1146 - 11s - 9ms/step - ia: 0.7647 - loss: 0.2114 - mae: 0.3524 - rmse: 0.4548 - smape: 0.7324 - val_ia: 0.4146 - val_loss: 0.2941 - val_mae: 0.4556 - val_rmse: 0.4952 - val_smape: 1.0300

Epoch 13/32

1146/1146 - 11s - 9ms/step - ia: 0.7697 - loss: 0.2038 - mae: 0.3456 - rmse: 0.4462 - smape: 0.7236 - val_ia: 0.4110 - val_loss: 0.3050 - val_mae: 0.4607 - val_rmse: 0.5028 - val_smape: 1.0318

Epoch 14/32

1146/1146 - 10s - 9ms/step - ia: 0.7707 - loss: 0.2009 - mae: 0.3448 - rmse: 0.4435 - smape: 0.7230 - val_ia: 0.3959 - val_loss: 0.3495 - val_mae: 0.4867 - val_rmse: 0.5343 - val_smape: 1.0641

Epoch 15/32

1146/1146 - 10s - 9ms/step - ia: 0.7732 - loss: 0.1975 - mae: 0.3403 - rmse: 0.4395 - smape: 0.7203 - val_ia: 0.4097 - val_loss: 0.3123 - val_mae: 0.4655 - val_rmse: 0.5088 - val_smape: 1.0459

Epoch 16/32

1146/1146 - 11s - 9ms/step - ia: 0.7747 - loss: 0.1949 - mae: 0.3387 - rmse: 0.4364 - smape: 0.7184 - val_ia: 0.4082 - val_loss: 0.3309 - val_mae: 0.4727 - val_rmse: 0.5229 - val_smape: 1.0297

Epoch 17/32

1146/1146 - 11s - 9ms/step - ia: 0.7786 - loss: 0.1890 - mae: 0.3332 - rmse: 0.4296 - smape: 0.7097 - val_ia: 0.4140 - val_loss: 0.3211 - val_mae: 0.4671 - val_rmse: 0.5143 - val_smape: 1.0242

Epoch 18/32

1146/1146 - 11s - 9ms/step - ia: 0.7802 - loss: 0.1866 - mae: 0.3310 - rmse: 0.4274 - smape: 0.7093 - val_ia: 0.4053 - val_loss: 0.3459 - val_mae: 0.4800 - val_rmse: 0.5314 - val_smape: 1.0486

Epoch 19/32

1146/1146 - 11s - 9ms/step - ia: 0.7825 - loss: 0.1830 - mae: 0.3278 - rmse: 0.4227 - smape: 0.7077 - val_ia: 0.4219 - val_loss: 0.3226 - val_mae: 0.4625 - val_rmse: 0.5128 - val_smape: 0.9987

Epoch 20/32

1146/1146 - 10s - 9ms/step - ia: 0.7832 - loss: 0.1827 - mae: 0.3267 - rmse: 0.4226 - smape: 0.7073 - val_ia: 0.4153 - val_loss: 0.3106 - val_mae: 0.4572 - val_rmse: 0.5074 - val_smape: 1.0245

Epoch 21/32

1146/1146 - 11s - 9ms/step - ia: 0.7844 - loss: 0.1790 - mae: 0.3247 - rmse: 0.4184 - smape: 0.7038 - val_ia: 0.4253 - val_loss: 0.3003 - val_mae: 0.4490 - val_rmse: 0.4976 - val_smape: 0.9772

Epoch 22/32

1146/1146 - 11s - 9ms/step - ia: 0.7852 - loss: 0.1786 - mae: 0.3234 - rmse: 0.4178 - smape: 0.7014 - val_ia: 0.4393 - val_loss: 0.2963 - val_mae: 0.4405 - val_rmse: 0.4924 - val_smape: 0.9266

Epoch 23/32

1146/1146 - 11s - 9ms/step - ia: 0.7882 - loss: 0.1741 - mae: 0.3201 - rmse: 0.4125 - smape: 0.6972 - val_ia: 0.4364 - val_loss: 0.2720 - val_mae: 0.4259 - val_rmse: 0.4776 - val_smape: 0.9354

Epoch 24/32

1146/1146 - 11s - 9ms/step - ia: 0.7878 - loss: 0.1743 - mae: 0.3205 - rmse: 0.4130 - smape: 0.6961 - val_ia: 0.4474 - val_loss: 0.2634 - val_mae: 0.4154 - val_rmse: 0.4677 - val_smape: 0.9052

Epoch 25/32

1146/1146 - 11s - 9ms/step - ia: 0.7905 - loss: 0.1705 - mae: 0.3165 - rmse: 0.4081 - smape: 0.6935 - val_ia: 0.4565 - val_loss: 0.2601 - val_mae: 0.4129 - val_rmse: 0.4625 - val_smape: 0.8776

Epoch 26/32

1146/1146 - 11s - 9ms/step - ia: 0.7900 - loss: 0.1719 - mae: 0.3172 - rmse: 0.4099 - smape: 0.6893 - val_ia: 0.4500 - val_loss: 0.2636 - val_mae: 0.4137 - val_rmse: 0.4675 - val_smape: 0.9181

Epoch 27/32

1146/1146 - 10s - 9ms/step - ia: 0.7918 - loss: 0.1699 - mae: 0.3146 - rmse: 0.4072 - smape: 0.6897 - val_ia: 0.4465 - val_loss: 0.2730 - val_mae: 0.4215 - val_rmse: 0.4746 - val_smape: 0.9068

Epoch 28/32

1146/1146 - 10s - 9ms/step - ia: 0.7929 - loss: 0.1670 - mae: 0.3128 - rmse: 0.4039 - smape: 0.6850 - val_ia: 0.4536 - val_loss: 0.2838 - val_mae: 0.4247 - val_rmse: 0.4791 - val_smape: 0.8867

Epoch 29/32

1146/1146 - 11s - 9ms/step - ia: 0.7928 - loss: 0.1663 - mae: 0.3131 - rmse: 0.4033 - smape: 0.6839 - val_ia: 0.4683 - val_loss: 0.2403 - val_mae: 0.3944 - val_rmse: 0.4449 - val_smape: 0.8594

Epoch 30/32

1146/1146 - 11s - 9ms/step - ia: 0.7930 - loss: 0.1682 - mae: 0.3133 - rmse: 0.4052 - smape: 0.6843 - val_ia: 0.4653 - val_loss: 0.2667 - val_mae: 0.4115 - val_rmse: 0.4638 - val_smape: 0.8419

Epoch 31/32

1146/1146 - 11s - 9ms/step - ia: 0.7959 - loss: 0.1638 - mae: 0.3092 - rmse: 0.3999 - smape: 0.6798 - val_ia: 0.4596 - val_loss: 0.2505 - val_mae: 0.4016 - val_rmse: 0.4541 - val_smape: 0.8603

Epoch 32/32

1146/1146 - 11s - 9ms/step - ia: 0.7964 - loss: 0.1636 - mae: 0.3082 - rmse: 0.3998 - smape: 0.6777 - val_ia: 0.4644 - val_loss: 0.2447 - val_mae: 0.3993 - val_rmse: 0.4486 - val_smape: 0.8433

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:06 783ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 80%|████████  | 40/50 [13:19:15<1:27:01, 522.18s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 29s - 201ms/step - ia: 0.1958 - loss: 0.9720 - mae: 0.8187 - rmse: 0.9833 - smape: 1.5849 - val_ia: 0.3829 - val_loss: 0.7831 - val_mae: 0.7139 - val_rmse: 0.8690 - val_smape: 1.2476

Epoch 2/128

144/144 - 18s - 127ms/step - ia: 0.5961 - loss: 0.5147 - mae: 0.5769 - rmse: 0.7147 - smape: 0.9906 - val_ia: 0.4286 - val_loss: 1.2116 - val_mae: 0.9249 - val_rmse: 1.0680 - val_smape: 1.3166

Epoch 3/128

144/144 - 20s - 141ms/step - ia: 0.6738 - loss: 0.3882 - mae: 0.4992 - rmse: 0.6224 - smape: 0.8484 - val_ia: 0.4915 - val_loss: 0.9199 - val_mae: 0.7900 - val_rmse: 0.9237 - val_smape: 1.1901

Epoch 4/128

144/144 - 18s - 123ms/step - ia: 0.6963 - loss: 0.3516 - mae: 0.4713 - rmse: 0.5925 - smape: 0.8093 - val_ia: 0.5550 - val_loss: 0.6672 - val_mae: 0.6640 - val_rmse: 0.7874 - val_smape: 1.0910

Epoch 5/128

144/144 - 18s - 124ms/step - ia: 0.7104 - loss: 0.3248 - mae: 0.4527 - rmse: 0.5689 - smape: 0.7906 - val_ia: 0.5535 - val_loss: 0.6181 - val_mae: 0.6434 - val_rmse: 0.7530 - val_smape: 1.0991

Epoch 6/128

144/144 - 19s - 129ms/step - ia: 0.7244 - loss: 0.2976 - mae: 0.4321 - rmse: 0.5446 - smape: 0.7737 - val_ia: 0.5757 - val_loss: 0.5418 - val_mae: 0.6029 - val_rmse: 0.7071 - val_smape: 1.0745

Epoch 7/128

144/144 - 20s - 136ms/step - ia: 0.7465 - loss: 0.2572 - mae: 0.3983 - rmse: 0.5062 - smape: 0.7476 - val_ia: 0.6027 - val_loss: 0.5071 - val_mae: 0.5812 - val_rmse: 0.6809 - val_smape: 1.0393

Epoch 8/128

144/144 - 19s - 129ms/step - ia: 0.7790 - loss: 0.2042 - mae: 0.3471 - rmse: 0.4513 - smape: 0.7092 - val_ia: 0.6355 - val_loss: 0.4672 - val_mae: 0.5522 - val_rmse: 0.6360 - val_smape: 0.9984

Epoch 9/128

144/144 - 18s - 127ms/step - ia: 0.7926 - loss: 0.1828 - mae: 0.3243 - rmse: 0.4265 - smape: 0.6918 - val_ia: 0.6861 - val_loss: 0.3190 - val_mae: 0.4576 - val_rmse: 0.5326 - val_smape: 0.9040

Epoch 10/128

144/144 - 21s - 144ms/step - ia: 0.7994 - loss: 0.1724 - mae: 0.3144 - rmse: 0.4144 - smape: 0.6830 - val_ia: 0.6934 - val_loss: 0.3115 - val_mae: 0.4509 - val_rmse: 0.5283 - val_smape: 0.8869

Epoch 11/128

144/144 - 18s - 123ms/step - ia: 0.8037 - loss: 0.1664 - mae: 0.3079 - rmse: 0.4069 - smape: 0.6754 - val_ia: 0.7143 - val_loss: 0.2576 - val_mae: 0.4162 - val_rmse: 0.4889 - val_smape: 0.8521

Epoch 12/128

144/144 - 19s - 132ms/step - ia: 0.8059 - loss: 0.1624 - mae: 0.3040 - rmse: 0.4019 - smape: 0.6718 - val_ia: 0.7078 - val_loss: 0.2715 - val_mae: 0.4252 - val_rmse: 0.4984 - val_smape: 0.8577

Epoch 13/128

144/144 - 18s - 125ms/step - ia: 0.8068 - loss: 0.1606 - mae: 0.3023 - rmse: 0.4005 - smape: 0.6698 - val_ia: 0.6975 - val_loss: 0.3003 - val_mae: 0.4476 - val_rmse: 0.5405 - val_smape: 0.8681

Epoch 14/128

144/144 - 18s - 126ms/step - ia: 0.8105 - loss: 0.1564 - mae: 0.2970 - rmse: 0.3948 - smape: 0.6615 - val_ia: 0.7134 - val_loss: 0.2892 - val_mae: 0.4374 - val_rmse: 0.5221 - val_smape: 0.8409

Epoch 15/128

144/144 - 20s - 136ms/step - ia: 0.8134 - loss: 0.1522 - mae: 0.2929 - rmse: 0.3893 - smape: 0.6577 - val_ia: 0.7160 - val_loss: 0.2663 - val_mae: 0.4216 - val_rmse: 0.5021 - val_smape: 0.8388

Epoch 16/128

144/144 - 18s - 126ms/step - ia: 0.8171 - loss: 0.1478 - mae: 0.2880 - rmse: 0.3833 - smape: 0.6475 - val_ia: 0.7081 - val_loss: 0.2696 - val_mae: 0.4234 - val_rmse: 0.5038 - val_smape: 0.8521

Epoch 17/128

144/144 - 18s - 123ms/step - ia: 0.8184 - loss: 0.1451 - mae: 0.2853 - rmse: 0.3803 - smape: 0.6441 - val_ia: 0.7313 - val_loss: 0.2244 - val_mae: 0.3909 - val_rmse: 0.4633 - val_smape: 0.8130

Epoch 18/128

144/144 - 18s - 127ms/step - ia: 0.8216 - loss: 0.1403 - mae: 0.2805 - rmse: 0.3744 - smape: 0.6382 - val_ia: 0.7091 - val_loss: 0.2617 - val_mae: 0.4188 - val_rmse: 0.5059 - val_smape: 0.8520

Epoch 19/128

144/144 - 18s - 127ms/step - ia: 0.8279 - loss: 0.1316 - mae: 0.2717 - rmse: 0.3621 - smape: 0.6254 - val_ia: 0.7286 - val_loss: 0.2356 - val_mae: 0.3944 - val_rmse: 0.4793 - val_smape: 0.8133

Epoch 20/128

144/144 - 18s - 127ms/step - ia: 0.8344 - loss: 0.1234 - mae: 0.2615 - rmse: 0.3512 - smape: 0.6240 - val_ia: 0.7254 - val_loss: 0.2543 - val_mae: 0.4025 - val_rmse: 0.4975 - val_smape: 0.8129

Epoch 21/128

144/144 - 18s - 128ms/step - ia: 0.8385 - loss: 0.1185 - mae: 0.2554 - rmse: 0.3441 - smape: 0.6241 - val_ia: 0.7486 - val_loss: 0.1849 - val_mae: 0.3570 - val_rmse: 0.4252 - val_smape: 0.8281

Epoch 22/128

144/144 - 18s - 127ms/step - ia: 0.8383 - loss: 0.1181 - mae: 0.2552 - rmse: 0.3429 - smape: 0.6283 - val_ia: 0.7440 - val_loss: 0.2041 - val_mae: 0.3679 - val_rmse: 0.4448 - val_smape: 0.8041

Epoch 23/128

144/144 - 18s - 128ms/step - ia: 0.8422 - loss: 0.1134 - mae: 0.2494 - rmse: 0.3359 - smape: 0.6192 - val_ia: 0.7522 - val_loss: 0.2051 - val_mae: 0.3640 - val_rmse: 0.4468 - val_smape: 0.7673

Epoch 24/128

144/144 - 18s - 125ms/step - ia: 0.8441 - loss: 0.1113 - mae: 0.2469 - rmse: 0.3327 - smape: 0.6161 - val_ia: 0.7316 - val_loss: 0.2427 - val_mae: 0.3925 - val_rmse: 0.4852 - val_smape: 0.7982

Epoch 25/128

144/144 - 18s - 125ms/step - ia: 0.8450 - loss: 0.1101 - mae: 0.2457 - rmse: 0.3308 - smape: 0.6125 - val_ia: 0.7206 - val_loss: 0.2613 - val_mae: 0.4043 - val_rmse: 0.5069 - val_smape: 0.8306

Epoch 26/128

144/144 - 20s - 141ms/step - ia: 0.8467 - loss: 0.1081 - mae: 0.2428 - rmse: 0.3279 - smape: 0.6109 - val_ia: 0.7633 - val_loss: 0.2004 - val_mae: 0.3573 - val_rmse: 0.4441 - val_smape: 0.7448

Epoch 27/128

144/144 - 21s - 142ms/step - ia: 0.8488 - loss: 0.1064 - mae: 0.2402 - rmse: 0.3253 - smape: 0.6021 - val_ia: 0.7405 - val_loss: 0.2217 - val_mae: 0.3744 - val_rmse: 0.4675 - val_smape: 0.7944

Epoch 28/128

144/144 - 18s - 127ms/step - ia: 0.8477 - loss: 0.1068 - mae: 0.2411 - rmse: 0.3261 - smape: 0.6036 - val_ia: 0.7444 - val_loss: 0.2294 - val_mae: 0.3734 - val_rmse: 0.4737 - val_smape: 0.7756

Epoch 29/128

144/144 - 19s - 129ms/step - ia: 0.8495 - loss: 0.1050 - mae: 0.2390 - rmse: 0.3229 - smape: 0.6012 - val_ia: 0.7420 - val_loss: 0.2517 - val_mae: 0.3840 - val_rmse: 0.4976 - val_smape: 0.7688

Epoch 30/128

144/144 - 18s - 125ms/step - ia: 0.8496 - loss: 0.1041 - mae: 0.2380 - rmse: 0.3218 - smape: 0.6024 - val_ia: 0.7363 - val_loss: 0.2574 - val_mae: 0.3904 - val_rmse: 0.5014 - val_smape: 0.7725

Epoch 31/128

144/144 - 18s - 126ms/step - ia: 0.8526 - loss: 0.1009 - mae: 0.2338 - rmse: 0.3177 - smape: 0.5894 - val_ia: 0.7486 - val_loss: 0.2374 - val_mae: 0.3706 - val_rmse: 0.4816 - val_smape: 0.7567

Epoch 32/128

144/144 - 18s - 125ms/step - ia: 0.8526 - loss: 0.1010 - mae: 0.2342 - rmse: 0.3166 - smape: 0.5917 - val_ia: 0.7681 - val_loss: 0.2018 - val_mae: 0.3461 - val_rmse: 0.4445 - val_smape: 0.7281

Epoch 33/128

144/144 - 18s - 124ms/step - ia: 0.8532 - loss: 0.1000 - mae: 0.2332 - rmse: 0.3154 - smape: 0.5882 - val_ia: 0.7519 - val_loss: 0.2285 - val_mae: 0.3666 - val_rmse: 0.4713 - val_smape: 0.7547

Epoch 34/128

144/144 - 18s - 126ms/step - ia: 0.8536 - loss: 0.1000 - mae: 0.2327 - rmse: 0.3154 - smape: 0.5890 - val_ia: 0.7621 - val_loss: 0.1960 - val_mae: 0.3433 - val_rmse: 0.4371 - val_smape: 0.7473

Epoch 35/128

144/144 - 18s - 127ms/step - ia: 0.8550 - loss: 0.0981 - mae: 0.2303 - rmse: 0.3124 - smape: 0.5827 - val_ia: 0.7614 - val_loss: 0.2213 - val_mae: 0.3581 - val_rmse: 0.4651 - val_smape: 0.7319

Epoch 36/128

144/144 - 18s - 124ms/step - ia: 0.8575 - loss: 0.0955 - mae: 0.2269 - rmse: 0.3080 - smape: 0.5739 - val_ia: 0.7753 - val_loss: 0.1905 - val_mae: 0.3326 - val_rmse: 0.4315 - val_smape: 0.7116

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step

 82%|████████▏ | 41/50 [13:30:37<1:25:31, 570.18s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1146/1146 - 43s - 38ms/step - ia: 0.6712 - loss: 0.3506 - mae: 0.4643 - rmse: 0.5798 - smape: 0.8564 - val_ia: 0.3315 - val_loss: 0.6558 - val_mae: 0.6413 - val_rmse: 0.7138 - val_smape: 1.0690

Epoch 2/8

1146/1146 - 14s - 12ms/step - ia: 0.7941 - loss: 0.1720 - mae: 0.3160 - rmse: 0.4083 - smape: 0.6773 - val_ia: 0.4595 - val_loss: 0.2774 - val_mae: 0.4257 - val_rmse: 0.4921 - val_smape: 0.8675

Epoch 3/8

1146/1146 - 13s - 12ms/step - ia: 0.8316 - loss: 0.1172 - mae: 0.2590 - rmse: 0.3377 - smape: 0.6202 - val_ia: 0.5275 - val_loss: 0.1901 - val_mae: 0.3562 - val_rmse: 0.4079 - val_smape: 0.7463

Epoch 4/8

1146/1146 - 13s - 12ms/step - ia: 0.8535 - loss: 0.0933 - mae: 0.2283 - rmse: 0.3011 - smape: 0.5704 - val_ia: 0.5172 - val_loss: 0.1982 - val_mae: 0.3600 - val_rmse: 0.4172 - val_smape: 0.7416

Epoch 5/8

1146/1146 - 14s - 12ms/step - ia: 0.8623 - loss: 0.0838 - mae: 0.2149 - rmse: 0.2851 - smape: 0.5419 - val_ia: 0.5429 - val_loss: 0.1589 - val_mae: 0.3227 - val_rmse: 0.3746 - val_smape: 0.6928

Epoch 6/8

1146/1146 - 14s - 12ms/step - ia: 0.8684 - loss: 0.0778 - mae: 0.2062 - rmse: 0.2749 - smape: 0.5232 - val_ia: 0.5603 - val_loss: 0.1325 - val_mae: 0.2900 - val_rmse: 0.3394 - val_smape: 0.6610

Epoch 7/8

1146/1146 - 13s - 12ms/step - ia: 0.8714 - loss: 0.0744 - mae: 0.2019 - rmse: 0.2685 - smape: 0.5133 - val_ia: 0.5647 - val_loss: 0.1349 - val_mae: 0.2857 - val_rmse: 0.3329 - val_smape: 0.6482

Epoch 8/8

1146/1146 - 14s - 12ms/step - ia: 0.8751 - loss: 0.0706 - mae: 0.1963 - rmse: 0.2614 - smape: 0.5007 - val_ia: 0.5356 - val_loss: 0.1722 - val_mae: 0.3224 - val_rmse: 0.3737 - val_smape: 0.7023

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:18 482ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 84%|████████▍ | 42/50 [13:32:58<58:50, 441.34s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

1146/1146 - 20s - 18ms/step - ia: 0.6015 - loss: 0.4556 - mae: 0.5377 - rmse: 0.6614 - smape: 0.9656 - val_ia: 0.3169 - val_loss: 0.5871 - val_mae: 0.6298 - val_rmse: 0.6929 - val_smape: 1.0880

Epoch 2/32

1146/1146 - 19s - 17ms/step - ia: 0.7348 - loss: 0.2601 - mae: 0.3996 - rmse: 0.5045 - smape: 0.7760 - val_ia: 0.4282 - val_loss: 0.3361 - val_mae: 0.4668 - val_rmse: 0.5203 - val_smape: 0.9390

Epoch 3/32

1146/1146 - 12s - 10ms/step - ia: 0.7702 - loss: 0.2006 - mae: 0.3483 - rmse: 0.4430 - smape: 0.7316 - val_ia: 0.4743 - val_loss: 0.2283 - val_mae: 0.3873 - val_rmse: 0.4283 - val_smape: 0.8114

Epoch 4/32

1146/1146 - 12s - 10ms/step - ia: 0.7882 - loss: 0.1744 - mae: 0.3228 - rmse: 0.4132 - smape: 0.7009 - val_ia: 0.4817 - val_loss: 0.2059 - val_mae: 0.3719 - val_rmse: 0.4125 - val_smape: 0.7740

Epoch 5/32

1146/1146 - 12s - 10ms/step - ia: 0.7988 - loss: 0.1602 - mae: 0.3074 - rmse: 0.3958 - smape: 0.6760 - val_ia: 0.4915 - val_loss: 0.1939 - val_mae: 0.3580 - val_rmse: 0.4023 - val_smape: 0.7409

Epoch 6/32

1146/1146 - 12s - 10ms/step - ia: 0.8031 - loss: 0.1545 - mae: 0.3011 - rmse: 0.3885 - smape: 0.6654 - val_ia: 0.4665 - val_loss: 0.2237 - val_mae: 0.3833 - val_rmse: 0.4307 - val_smape: 0.7880

Epoch 7/32

1146/1146 - 12s - 10ms/step - ia: 0.8088 - loss: 0.1470 - mae: 0.2929 - rmse: 0.3792 - smape: 0.6508 - val_ia: 0.4965 - val_loss: 0.1872 - val_mae: 0.3506 - val_rmse: 0.3966 - val_smape: 0.7296

Epoch 8/32

1146/1146 - 12s - 10ms/step - ia: 0.8130 - loss: 0.1411 - mae: 0.2871 - rmse: 0.3710 - smape: 0.6451 - val_ia: 0.4986 - val_loss: 0.1901 - val_mae: 0.3496 - val_rmse: 0.3980 - val_smape: 0.7223

Epoch 9/32

1146/1146 - 12s - 10ms/step - ia: 0.8157 - loss: 0.1372 - mae: 0.2835 - rmse: 0.3660 - smape: 0.6341 - val_ia: 0.5164 - val_loss: 0.1543 - val_mae: 0.3217 - val_rmse: 0.3627 - val_smape: 0.6885

Epoch 10/32

1146/1146 - 11s - 10ms/step - ia: 0.8181 - loss: 0.1349 - mae: 0.2800 - rmse: 0.3628 - smape: 0.6273 - val_ia: 0.5056 - val_loss: 0.1730 - val_mae: 0.3365 - val_rmse: 0.3830 - val_smape: 0.7027

Epoch 11/32

1146/1146 - 12s - 10ms/step - ia: 0.8203 - loss: 0.1324 - mae: 0.2769 - rmse: 0.3592 - smape: 0.6205 - val_ia: 0.4999 - val_loss: 0.1906 - val_mae: 0.3515 - val_rmse: 0.4001 - val_smape: 0.7187

Epoch 12/32

1146/1146 - 12s - 10ms/step - ia: 0.8227 - loss: 0.1288 - mae: 0.2727 - rmse: 0.3543 - smape: 0.6145 - val_ia: 0.5034 - val_loss: 0.1822 - val_mae: 0.3448 - val_rmse: 0.3941 - val_smape: 0.7113

Epoch 13/32

1146/1146 - 12s - 10ms/step - ia: 0.8237 - loss: 0.1272 - mae: 0.2715 - rmse: 0.3524 - smape: 0.6105 - val_ia: 0.5040 - val_loss: 0.1787 - val_mae: 0.3418 - val_rmse: 0.3904 - val_smape: 0.7113

Epoch 14/32

1146/1146 - 12s - 10ms/step - ia: 0.8256 - loss: 0.1243 - mae: 0.2690 - rmse: 0.3482 - smape: 0.6025 - val_ia: 0.5043 - val_loss: 0.1702 - val_mae: 0.3342 - val_rmse: 0.3793 - val_smape: 0.7083

Epoch 15/32

1146/1146 - 12s - 10ms/step - ia: 0.8282 - loss: 0.1208 - mae: 0.2652 - rmse: 0.3434 - smape: 0.5968 - val_ia: 0.4872 - val_loss: 0.2056 - val_mae: 0.3659 - val_rmse: 0.4182 - val_smape: 0.7370

Epoch 16/32

1146/1146 - 12s - 10ms/step - ia: 0.8305 - loss: 0.1177 - mae: 0.2623 - rmse: 0.3389 - smape: 0.5909 - val_ia: 0.5036 - val_loss: 0.1797 - val_mae: 0.3442 - val_rmse: 0.3927 - val_smape: 0.7156

Epoch 17/32

1146/1146 - 20s - 18ms/step - ia: 0.8319 - loss: 0.1155 - mae: 0.2603 - rmse: 0.3358 - smape: 0.5894 - val_ia: 0.5047 - val_loss: 0.1899 - val_mae: 0.3516 - val_rmse: 0.4003 - val_smape: 0.7139

Epoch 18/32

1146/1146 - 12s - 10ms/step - ia: 0.8326 - loss: 0.1157 - mae: 0.2595 - rmse: 0.3358 - smape: 0.5848 - val_ia: 0.4866 - val_loss: 0.1886 - val_mae: 0.3527 - val_rmse: 0.4051 - val_smape: 0.7300

Epoch 19/32

1146/1146 - 12s - 10ms/step - ia: 0.8339 - loss: 0.1132 - mae: 0.2574 - rmse: 0.3324 - smape: 0.5799 - val_ia: 0.4901 - val_loss: 0.2070 - val_mae: 0.3675 - val_rmse: 0.4185 - val_smape: 0.7417

Epoch 20/32

1146/1146 - 12s - 10ms/step - ia: 0.8350 - loss: 0.1126 - mae: 0.2557 - rmse: 0.3313 - smape: 0.5767 - val_ia: 0.4916 - val_loss: 0.1911 - val_mae: 0.3552 - val_rmse: 0.4060 - val_smape: 0.7255

Epoch 21/32

1146/1146 - 12s - 10ms/step - ia: 0.8360 - loss: 0.1105 - mae: 0.2541 - rmse: 0.3285 - smape: 0.5749 - val_ia: 0.4873 - val_loss: 0.1997 - val_mae: 0.3599 - val_rmse: 0.4142 - val_smape: 0.7298

Epoch 22/32

1146/1146 - 12s - 10ms/step - ia: 0.8359 - loss: 0.1106 - mae: 0.2547 - rmse: 0.3284 - smape: 0.5750 - val_ia: 0.4838 - val_loss: 0.2031 - val_mae: 0.3628 - val_rmse: 0.4176 - val_smape: 0.7393

Epoch 23/32

1146/1146 - 12s - 10ms/step - ia: 0.8379 - loss: 0.1089 - mae: 0.2520 - rmse: 0.3259 - smape: 0.5725 - val_ia: 0.4928 - val_loss: 0.1852 - val_mae: 0.3491 - val_rmse: 0.3982 - val_smape: 0.7282

Epoch 24/32

1146/1146 - 20s - 17ms/step - ia: 0.8373 - loss: 0.1097 - mae: 0.2528 - rmse: 0.3269 - smape: 0.5684 - val_ia: 0.5021 - val_loss: 0.1805 - val_mae: 0.3453 - val_rmse: 0.3930 - val_smape: 0.7171

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 9.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:11 1s/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 39/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 86%|████████▌ | 43/50 [13:38:14<47:07, 403.87s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 12s - 80ms/step - ia: 0.1386 - loss: 1.0303 - mae: 0.8421 - rmse: 1.0152 - smape: 1.6669 - val_ia: 0.2224 - val_loss: 0.8456 - val_mae: 0.7637 - val_rmse: 0.9116 - val_smape: 1.7647

Epoch 2/128

144/144 - 4s - 28ms/step - ia: 0.1360 - loss: 1.0315 - mae: 0.8427 - rmse: 1.0147 - smape: 1.6720 - val_ia: 0.2196 - val_loss: 0.8484 - val_mae: 0.7654 - val_rmse: 0.9128 - val_smape: 1.8079

Epoch 3/128

144/144 - 4s - 30ms/step - ia: 0.1335 - loss: 1.0229 - mae: 0.8398 - rmse: 1.0110 - smape: 1.6749 - val_ia: 0.2187 - val_loss: 0.8508 - val_mae: 0.7668 - val_rmse: 0.9138 - val_smape: 1.8473

Epoch 4/128

144/144 - 5s - 33ms/step - ia: 0.1350 - loss: 1.0252 - mae: 0.8411 - rmse: 1.0115 - smape: 1.6778 - val_ia: 0.2180 - val_loss: 0.8527 - val_mae: 0.7679 - val_rmse: 0.9147 - val_smape: 1.8802

Epoch 5/128

144/144 - 5s - 33ms/step - ia: 0.1329 - loss: 1.0238 - mae: 0.8388 - rmse: 1.0113 - smape: 1.6728 - val_ia: 0.2175 - val_loss: 0.8541 - val_mae: 0.7687 - val_rmse: 0.9153 - val_smape: 1.9060

Epoch 6/128

144/144 - 4s - 29ms/step - ia: 0.1348 - loss: 1.0247 - mae: 0.8394 - rmse: 1.0111 - smape: 1.6725 - val_ia: 0.2170 - val_loss: 0.8553 - val_mae: 0.7694 - val_rmse: 0.9158 - val_smape: 1.9294

Epoch 7/128

144/144 - 5s - 34ms/step - ia: 0.1300 - loss: 1.0243 - mae: 0.8403 - rmse: 1.0123 - smape: 1.6769 - val_ia: 0.2165 - val_loss: 0.8564 - val_mae: 0.7699 - val_rmse: 0.9163 - val_smape: 1.9480

Epoch 8/128

144/144 - 4s - 28ms/step - ia: 0.1342 - loss: 1.0203 - mae: 0.8392 - rmse: 1.0096 - smape: 1.6754 - val_ia: 0.2163 - val_loss: 0.8568 - val_mae: 0.7701 - val_rmse: 0.9164 - val_smape: 1.9555

Epoch 9/128

144/144 - 4s - 27ms/step - ia: 0.1371 - loss: 1.0208 - mae: 0.8377 - rmse: 1.0089 - smape: 1.6708 - val_ia: 0.2161 - val_loss: 0.8573 - val_mae: 0.7705 - val_rmse: 0.9166 - val_smape: 1.9636

Epoch 10/128

144/144 - 4s - 28ms/step - ia: 0.1342 - loss: 1.0213 - mae: 0.8384 - rmse: 1.0105 - smape: 1.6717 - val_ia: 0.2160 - val_loss: 0.8577 - val_mae: 0.7707 - val_rmse: 0.9168 - val_smape: 1.9656

Epoch 11/128

144/144 - 4s - 27ms/step - ia: 0.1325 - loss: 1.0229 - mae: 0.8394 - rmse: 1.0096 - smape: 1.6742 - val_ia: 0.2159 - val_loss: 0.8579 - val_mae: 0.7708 - val_rmse: 0.9168 - val_smape: 1.9641

Epoch 12/128

144/144 - 4s - 27ms/step - ia: 0.1327 - loss: 1.0210 - mae: 0.8389 - rmse: 1.0090 - smape: 1.6773 - val_ia: 0.2159 - val_loss: 0.8579 - val_mae: 0.7708 - val_rmse: 0.9169 - val_smape: 1.9619

Epoch 13/128

144/144 - 5s - 36ms/step - ia: 0.1327 - loss: 1.0191 - mae: 0.8380 - rmse: 1.0092 - smape: 1.6747 - val_ia: 0.2159 - val_loss: 0.8578 - val_mae: 0.7708 - val_rmse: 0.9168 - val_smape: 1.9600

Epoch 14/128

144/144 - 4s - 27ms/step - ia: 0.1356 - loss: 1.0184 - mae: 0.8370 - rmse: 1.0087 - smape: 1.6697 - val_ia: 0.2159 - val_loss: 0.8577 - val_mae: 0.7707 - val_rmse: 0.9167 - val_smape: 1.9581

Epoch 15/128

144/144 - 4s - 26ms/step - ia: 0.1349 - loss: 1.0202 - mae: 0.8381 - rmse: 1.0097 - smape: 1.6708 - val_ia: 0.2159 - val_loss: 0.8578 - val_mae: 0.7708 - val_rmse: 0.9167 - val_smape: 1.9561

Epoch 16/128

144/144 - 4s - 26ms/step - ia: 0.1337 - loss: 1.0195 - mae: 0.8373 - rmse: 1.0091 - smape: 1.6707 - val_ia: 0.2160 - val_loss: 0.8574 - val_mae: 0.7706 - val_rmse: 0.9166 - val_smape: 1.9542

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:08 423ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 88%|████████▊ | 44/50 [13:39:32<30:36, 306.00s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

573/573 - 12s - 20ms/step - ia: 0.2790 - loss: 0.8702 - mae: 0.7734 - rmse: 0.9278 - smape: 1.5249 - val_ia: 0.4167 - val_loss: 0.5698 - val_mae: 0.6068 - val_rmse: 0.7176 - val_smape: 1.2802

Epoch 2/8

573/573 - 4s - 8ms/step - ia: 0.5590 - loss: 0.5065 - mae: 0.5708 - rmse: 0.7077 - smape: 1.0721 - val_ia: 0.4624 - val_loss: 0.5144 - val_mae: 0.5903 - val_rmse: 0.6856 - val_smape: 1.1411

Epoch 3/8

573/573 - 5s - 9ms/step - ia: 0.6569 - loss: 0.3855 - mae: 0.4961 - rmse: 0.6183 - smape: 0.8930 - val_ia: 0.4956 - val_loss: 0.4948 - val_mae: 0.5846 - val_rmse: 0.6697 - val_smape: 1.0596

Epoch 4/8

573/573 - 4s - 7ms/step - ia: 0.6789 - loss: 0.3525 - mae: 0.4747 - rmse: 0.5915 - smape: 0.8650 - val_ia: 0.5170 - val_loss: 0.4732 - val_mae: 0.5714 - val_rmse: 0.6528 - val_smape: 1.0112

Epoch 5/8

573/573 - 4s - 7ms/step - ia: 0.6898 - loss: 0.3363 - mae: 0.4627 - rmse: 0.5773 - smape: 0.8482 - val_ia: 0.5255 - val_loss: 0.4644 - val_mae: 0.5624 - val_rmse: 0.6451 - val_smape: 0.9908

Epoch 6/8

573/573 - 4s - 7ms/step - ia: 0.6984 - loss: 0.3212 - mae: 0.4523 - rmse: 0.5644 - smape: 0.8385 - val_ia: 0.5362 - val_loss: 0.4431 - val_mae: 0.5464 - val_rmse: 0.6296 - val_smape: 0.9689

Epoch 7/8

573/573 - 4s - 7ms/step - ia: 0.7062 - loss: 0.3082 - mae: 0.4414 - rmse: 0.5529 - smape: 0.8285 - val_ia: 0.5515 - val_loss: 0.4097 - val_mae: 0.5237 - val_rmse: 0.6053 - val_smape: 0.9381

Epoch 8/8

573/573 - 4s - 7ms/step - ia: 0.7121 - loss: 0.2987 - mae: 0.4330 - rmse: 0.5443 - smape: 0.8215 - val_ia: 0.5630 - val_loss: 0.3821 - val_mae: 0.5052 - val_rmse: 0.5856 - val_smape: 0.9160

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:23 516ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

Epoch 1/32

 90%|█████████ | 45/50 [13:40:16<18:57, 227.43s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1146/1146 - 12s - 11ms/step - ia: 0.7877 - loss: 0.1768 - mae: 0.3188 - rmse: 0.4088 - smape: 0.6921 - val_ia: 0.5393 - val_loss: 0.1774 - val_mae: 0.3157 - val_rmse: 0.3681 - val_smape: 0.7067

Epoch 2/32

1146/1146 - 7s - 6ms/step - ia: 0.8338 - loss: 0.1158 - mae: 0.2570 - rmse: 0.3355 - smape: 0.5946 - val_ia: 0.5113 - val_loss: 0.1862 - val_mae: 0.3399 - val_rmse: 0.3897 - val_smape: 0.7220

Epoch 3/32

1146/1146 - 7s - 6ms/step - ia: 0.8473 - loss: 0.0998 - mae: 0.2378 - rmse: 0.3113 - smape: 0.5465 - val_ia: 0.5218 - val_loss: 0.1853 - val_mae: 0.3261 - val_rmse: 0.3788 - val_smape: 0.7314

Epoch 4/32

1146/1146 - 7s - 6ms/step - ia: 0.8532 - loss: 0.0933 - mae: 0.2294 - rmse: 0.3006 - smape: 0.5262 - val_ia: 0.5203 - val_loss: 0.2213 - val_mae: 0.3410 - val_rmse: 0.3975 - val_smape: 0.7248

Epoch 5/32

1146/1146 - 7s - 6ms/step - ia: 0.8568 - loss: 0.0907 - mae: 0.2239 - rmse: 0.2943 - smape: 0.5166 - val_ia: 0.5283 - val_loss: 0.2119 - val_mae: 0.3426 - val_rmse: 0.3849 - val_smape: 0.7388

Epoch 6/32

1146/1146 - 7s - 6ms/step - ia: 0.8489 - loss: 0.0979 - mae: 0.2350 - rmse: 0.3078 - smape: 0.5394 - val_ia: 0.5279 - val_loss: 0.2114 - val_mae: 0.3395 - val_rmse: 0.4012 - val_smape: 0.6867

Epoch 7/32

1146/1146 - 7s - 6ms/step - ia: 0.8552 - loss: 0.0922 - mae: 0.2260 - rmse: 0.2961 - smape: 0.5180 - val_ia: 0.5245 - val_loss: 0.2016 - val_mae: 0.3249 - val_rmse: 0.3810 - val_smape: 0.7154

Epoch 8/32

1146/1146 - 8s - 7ms/step - ia: 0.8600 - loss: 0.0842 - mae: 0.2192 - rmse: 0.2861 - smape: 0.5071 - val_ia: 0.5260 - val_loss: 0.2203 - val_mae: 0.3369 - val_rmse: 0.3925 - val_smape: 0.7048

Epoch 9/32

1146/1146 - 7s - 6ms/step - ia: 0.8651 - loss: 0.0795 - mae: 0.2115 - rmse: 0.2774 - smape: 0.4889 - val_ia: 0.5317 - val_loss: 0.1740 - val_mae: 0.3166 - val_rmse: 0.3598 - val_smape: 0.6842

Epoch 10/32

1146/1146 - 7s - 6ms/step - ia: 0.8682 - loss: 0.0770 - mae: 0.2074 - rmse: 0.2732 - smape: 0.4803 - val_ia: 0.5099 - val_loss: 0.2090 - val_mae: 0.3448 - val_rmse: 0.3957 - val_smape: 0.7175

Epoch 11/32

1146/1146 - 10s - 9ms/step - ia: 0.8699 - loss: 0.0744 - mae: 0.2042 - rmse: 0.2683 - smape: 0.4759 - val_ia: 0.5294 - val_loss: 0.1523 - val_mae: 0.3059 - val_rmse: 0.3498 - val_smape: 0.6743

Epoch 12/32

1146/1146 - 7s - 6ms/step - ia: 0.8712 - loss: 0.0732 - mae: 0.2029 - rmse: 0.2661 - smape: 0.4713 - val_ia: 0.5068 - val_loss: 0.2084 - val_mae: 0.3423 - val_rmse: 0.4056 - val_smape: 0.7277

Epoch 13/32

1146/1146 - 8s - 7ms/step - ia: 0.8680 - loss: 0.0780 - mae: 0.2070 - rmse: 0.2745 - smape: 0.4812 - val_ia: 0.5296 - val_loss: 0.1636 - val_mae: 0.3145 - val_rmse: 0.3569 - val_smape: 0.6922

Epoch 14/32

1146/1146 - 8s - 7ms/step - ia: 0.8742 - loss: 0.0703 - mae: 0.1983 - rmse: 0.2608 - smape: 0.4635 - val_ia: 0.5233 - val_loss: 0.1760 - val_mae: 0.3222 - val_rmse: 0.3667 - val_smape: 0.7149

Epoch 15/32

1146/1146 - 7s - 6ms/step - ia: 0.8748 - loss: 0.0701 - mae: 0.1970 - rmse: 0.2607 - smape: 0.4606 - val_ia: 0.5001 - val_loss: 0.2226 - val_mae: 0.3608 - val_rmse: 0.4100 - val_smape: 0.7273

Epoch 16/32

1146/1146 - 7s - 6ms/step - ia: 0.8758 - loss: 0.0685 - mae: 0.1960 - rmse: 0.2575 - smape: 0.4573 - val_ia: 0.5003 - val_loss: 0.2062 - val_mae: 0.3493 - val_rmse: 0.4009 - val_smape: 0.7268

Epoch 17/32

1146/1146 - 7s - 6ms/step - ia: 0.8768 - loss: 0.0675 - mae: 0.1945 - rmse: 0.2557 - smape: 0.4572 - val_ia: 0.5008 - val_loss: 0.2204 - val_mae: 0.3533 - val_rmse: 0.4091 - val_smape: 0.7303

Epoch 18/32

1146/1146 - 7s - 6ms/step - ia: 0.8627 - loss: 0.0955 - mae: 0.2154 - rmse: 0.2885 - smape: 0.4941 - val_ia: 0.4621 - val_loss: 0.3757 - val_mae: 0.4340 - val_rmse: 0.5293 - val_smape: 0.8072

Epoch 19/32

1146/1146 - 7s - 6ms/step - ia: 0.8752 - loss: 0.0693 - mae: 0.1966 - rmse: 0.2589 - smape: 0.4595 - val_ia: 0.4834 - val_loss: 0.2720 - val_mae: 0.3808 - val_rmse: 0.4584 - val_smape: 0.7572

Epoch 20/32

1146/1146 - 7s - 6ms/step - ia: 0.8806 - loss: 0.0631 - mae: 0.1886 - rmse: 0.2478 - smape: 0.4450 - val_ia: 0.5206 - val_loss: 0.1846 - val_mae: 0.3234 - val_rmse: 0.3832 - val_smape: 0.6920

Epoch 21/32

1146/1146 - 10s - 9ms/step - ia: 0.5451 - loss: 7.6334 - mae: 0.6785 - rmse: 1.1029 - smape: 1.0550 - val_ia: 0.3159 - val_loss: 0.5453 - val_mae: 0.6108 - val_rmse: 0.6817 - val_smape: 1.1950

Epoch 22/32

1146/1146 - 7s - 6ms/step - ia: 0.5963 - loss: 0.5728 - mae: 0.5700 - rmse: 0.7142 - smape: 0.9964 - val_ia: 0.3009 - val_loss: 0.6047 - val_mae: 0.6267 - val_rmse: 0.7123 - val_smape: 1.2136

Epoch 23/32

1146/1146 - 7s - 6ms/step - ia: 0.6380 - loss: 0.4375 - mae: 0.5206 - rmse: 0.6463 - smape: 0.9409 - val_ia: 0.3188 - val_loss: 0.6621 - val_mae: 0.6303 - val_rmse: 0.7230 - val_smape: 1.1636

Epoch 24/32

1146/1146 - 7s - 6ms/step - ia: 0.7009 - loss: 0.3307 - mae: 0.4423 - rmse: 0.5582 - smape: 0.8350 - val_ia: 0.3373 - val_loss: 0.5043 - val_mae: 0.5671 - val_rmse: 0.6481 - val_smape: 1.1485

Epoch 25/32

1146/1146 - 7s - 6ms/step - ia: 0.6889 - loss: 0.5152 - mae: 0.4512 - rmse: 0.5983 - smape: 0.8511 - val_ia: 0.3119 - val_loss: 0.5984 - val_mae: 0.6221 - val_rmse: 0.7134 - val_smape: 1.2290

Epoch 26/32

1146/1146 - 7s - 6ms/step - ia: 0.3693 - loss: 40.2188 - mae: 1.0707 - rmse: 2.3354 - smape: 1.3222 - val_ia: 0.2796 - val_loss: 0.7695 - val_mae: 0.7000 - val_rmse: 0.7958 - val_smape: 1.5120

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:19 490ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 92%|█████████▏| 46/50 [13:43:41<14:43, 220.76s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 86s - 19ms/step - ia: 0.2206 - loss: 1.0322 - mae: 0.8424 - rmse: 0.9958 - smape: 1.6698 - val_ia: 0.1379 - val_loss: 0.8524 - val_mae: 0.7682 - val_rmse: 0.7852 - val_smape: 1.9163

Epoch 2/256

4584/4584 - 81s - 18ms/step - ia: 0.2480 - loss: 0.9546 - mae: 0.8169 - rmse: 0.9583 - smape: 1.6075 - val_ia: 0.1444 - val_loss: 0.7541 - val_mae: 0.7186 - val_rmse: 0.7380 - val_smape: 1.3495

Epoch 3/256

4584/4584 - 76s - 17ms/step - ia: 0.4148 - loss: 0.7147 - mae: 0.7106 - rmse: 0.8285 - smape: 1.2473 - val_ia: 0.1354 - val_loss: 1.1636 - val_mae: 0.8893 - val_rmse: 0.9050 - val_smape: 1.3229

Epoch 4/256

4584/4584 - 76s - 17ms/step - ia: 0.5267 - loss: 0.5745 - mae: 0.6181 - rmse: 0.7385 - smape: 1.0548 - val_ia: 0.1299 - val_loss: 1.2626 - val_mae: 0.9346 - val_rmse: 0.9499 - val_smape: 1.3478

Epoch 5/256

4584/4584 - 76s - 17ms/step - ia: 0.5490 - loss: 0.5383 - mae: 0.5935 - rmse: 0.7137 - smape: 1.0145 - val_ia: 0.1301 - val_loss: 1.2520 - val_mae: 0.9280 - val_rmse: 0.9437 - val_smape: 1.3410

Epoch 6/256

4584/4584 - 81s - 18ms/step - ia: 0.5662 - loss: 0.5120 - mae: 0.5765 - rmse: 0.6951 - smape: 0.9872 - val_ia: 0.1274 - val_loss: 1.2937 - val_mae: 0.9492 - val_rmse: 0.9648 - val_smape: 1.3596

Epoch 7/256

4584/4584 - 77s - 17ms/step - ia: 0.5817 - loss: 0.4861 - mae: 0.5603 - rmse: 0.6772 - smape: 0.9615 - val_ia: 0.1249 - val_loss: 1.3244 - val_mae: 0.9627 - val_rmse: 0.9784 - val_smape: 1.3649

Epoch 8/256

4584/4584 - 76s - 17ms/step - ia: 0.5963 - loss: 0.4611 - mae: 0.5439 - rmse: 0.6589 - smape: 0.9332 - val_ia: 0.1240 - val_loss: 1.3401 - val_mae: 0.9688 - val_rmse: 0.9848 - val_smape: 1.3575

Epoch 9/256

4584/4584 - 80s - 17ms/step - ia: 0.6117 - loss: 0.4360 - mae: 0.5268 - rmse: 0.6397 - smape: 0.9064 - val_ia: 0.1227 - val_loss: 1.3235 - val_mae: 0.9672 - val_rmse: 0.9833 - val_smape: 1.3687

Epoch 10/256

4584/4584 - 77s - 17ms/step - ia: 0.6245 - loss: 0.4139 - mae: 0.5127 - rmse: 0.6239 - smape: 0.8818 - val_ia: 0.1240 - val_loss: 1.2952 - val_mae: 0.9560 - val_rmse: 0.9725 - val_smape: 1.3551

Epoch 11/256

4584/4584 - 80s - 17ms/step - ia: 0.6345 - loss: 0.3950 - mae: 0.5002 - rmse: 0.6088 - smape: 0.8618 - val_ia: 0.1315 - val_loss: 1.1721 - val_mae: 0.9017 - val_rmse: 0.9192 - val_smape: 1.3019

Epoch 12/256

4584/4584 - 77s - 17ms/step - ia: 0.6410 - loss: 0.3820 - mae: 0.4918 - rmse: 0.5993 - smape: 0.8463 - val_ia: 0.1391 - val_loss: 1.0816 - val_mae: 0.8554 - val_rmse: 0.8741 - val_smape: 1.2454

Epoch 13/256

4584/4584 - 88s - 19ms/step - ia: 0.6490 - loss: 0.3715 - mae: 0.4854 - rmse: 0.5911 - smape: 0.8361 - val_ia: 0.1323 - val_loss: 1.1441 - val_mae: 0.8946 - val_rmse: 0.9121 - val_smape: 1.3000

Epoch 14/256

4584/4584 - 77s - 17ms/step - ia: 0.6539 - loss: 0.3654 - mae: 0.4800 - rmse: 0.5858 - smape: 0.8255 - val_ia: 0.1389 - val_loss: 1.0782 - val_mae: 0.8582 - val_rmse: 0.8766 - val_smape: 1.2501

Epoch 15/256

4584/4584 - 76s - 17ms/step - ia: 0.6558 - loss: 0.3575 - mae: 0.4747 - rmse: 0.5791 - smape: 0.8183 - val_ia: 0.1368 - val_loss: 1.0832 - val_mae: 0.8679 - val_rmse: 0.8858 - val_smape: 1.2736

Epoch 16/256

4584/4584 - 76s - 17ms/step - ia: 0.6617 - loss: 0.3501 - mae: 0.4690 - rmse: 0.5733 - smape: 0.8098 - val_ia: 0.1441 - val_loss: 1.0049 - val_mae: 0.8242 - val_rmse: 0.8431 - val_smape: 1.2187

Epoch 17/256

4584/4584 - 76s - 17ms/step - ia: 0.6635 - loss: 0.3461 - mae: 0.4667 - rmse: 0.5702 - smape: 0.8065 - val_ia: 0.1504 - val_loss: 0.9037 - val_mae: 0.7775 - val_rmse: 0.7969 - val_smape: 1.1915

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:30 1s/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step

 94%|█████████▍| 47/50 [14:06:05<27:53, 557.78s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 15s - 53ms/step - ia: 0.7776 - loss: 0.2056 - mae: 0.3320 - rmse: 0.4308 - smape: 0.7080 - val_ia: 0.7570 - val_loss: 0.1913 - val_mae: 0.3484 - val_rmse: 0.4183 - val_smape: 0.7540

Epoch 2/32

287/287 - 8s - 29ms/step - ia: 0.8583 - loss: 0.0958 - mae: 0.2254 - rmse: 0.3081 - smape: 0.5597 - val_ia: 0.7349 - val_loss: 0.2566 - val_mae: 0.3933 - val_rmse: 0.4752 - val_smape: 0.7745

Epoch 3/32

287/287 - 7s - 25ms/step - ia: 0.8727 - loss: 0.0786 - mae: 0.2040 - rmse: 0.2789 - smape: 0.5184 - val_ia: 0.7595 - val_loss: 0.1896 - val_mae: 0.3446 - val_rmse: 0.4025 - val_smape: 0.7275

Epoch 4/32

287/287 - 10s - 35ms/step - ia: 0.8763 - loss: 0.0739 - mae: 0.1987 - rmse: 0.2704 - smape: 0.5064 - val_ia: 0.7426 - val_loss: 0.2287 - val_mae: 0.3713 - val_rmse: 0.4527 - val_smape: 0.7620

Epoch 5/32

287/287 - 7s - 25ms/step - ia: 0.8827 - loss: 0.0672 - mae: 0.1889 - rmse: 0.2576 - smape: 0.4859 - val_ia: 0.7512 - val_loss: 0.1989 - val_mae: 0.3471 - val_rmse: 0.4128 - val_smape: 0.7383

Epoch 6/32

287/287 - 10s - 36ms/step - ia: 0.8861 - loss: 0.0639 - mae: 0.1836 - rmse: 0.2514 - smape: 0.4769 - val_ia: 0.7222 - val_loss: 0.2451 - val_mae: 0.3857 - val_rmse: 0.4531 - val_smape: 0.7935

Epoch 7/32

287/287 - 8s - 26ms/step - ia: 0.8897 - loss: 0.0608 - mae: 0.1780 - rmse: 0.2447 - smape: 0.4659 - val_ia: 0.7355 - val_loss: 0.2570 - val_mae: 0.3836 - val_rmse: 0.4617 - val_smape: 0.7716

Epoch 8/32

287/287 - 7s - 25ms/step - ia: 0.8932 - loss: 0.0572 - mae: 0.1727 - rmse: 0.2377 - smape: 0.4557 - val_ia: 0.7247 - val_loss: 0.2440 - val_mae: 0.3864 - val_rmse: 0.4592 - val_smape: 0.7824

Epoch 9/32

287/287 - 12s - 40ms/step - ia: 0.8967 - loss: 0.0539 - mae: 0.1670 - rmse: 0.2307 - smape: 0.4462 - val_ia: 0.7041 - val_loss: 0.2753 - val_mae: 0.4102 - val_rmse: 0.4907 - val_smape: 0.8225

Epoch 10/32

287/287 - 9s - 31ms/step - ia: 0.9006 - loss: 0.0503 - mae: 0.1610 - rmse: 0.2227 - smape: 0.4317 - val_ia: 0.7205 - val_loss: 0.2388 - val_mae: 0.3753 - val_rmse: 0.4412 - val_smape: 0.7873

Epoch 11/32

287/287 - 10s - 36ms/step - ia: 0.9032 - loss: 0.0478 - mae: 0.1568 - rmse: 0.2173 - smape: 0.4263 - val_ia: 0.7153 - val_loss: 0.2789 - val_mae: 0.3995 - val_rmse: 0.4671 - val_smape: 0.7909

Epoch 12/32

287/287 - 10s - 35ms/step - ia: 0.9037 - loss: 0.0471 - mae: 0.1562 - rmse: 0.2154 - smape: 0.4227 - val_ia: 0.6803 - val_loss: 0.3033 - val_mae: 0.4299 - val_rmse: 0.5041 - val_smape: 0.8532

Epoch 13/32

287/287 - 7s - 25ms/step - ia: 0.9069 - loss: 0.0446 - mae: 0.1511 - rmse: 0.2099 - smape: 0.4127 - val_ia: 0.7226 - val_loss: 0.2431 - val_mae: 0.3729 - val_rmse: 0.4485 - val_smape: 0.7699

Epoch 14/32

287/287 - 7s - 24ms/step - ia: 0.9093 - loss: 0.0426 - mae: 0.1476 - rmse: 0.2050 - smape: 0.4065 - val_ia: 0.7297 - val_loss: 0.2190 - val_mae: 0.3631 - val_rmse: 0.4404 - val_smape: 0.7473

Epoch 15/32

287/287 - 10s - 36ms/step - ia: 0.9115 - loss: 0.0401 - mae: 0.1438 - rmse: 0.1989 - smape: 0.3979 - val_ia: 0.7104 - val_loss: 0.2576 - val_mae: 0.3959 - val_rmse: 0.4671 - val_smape: 0.7897

Epoch 16/32

287/287 - 7s - 24ms/step - ia: 0.9135 - loss: 0.0387 - mae: 0.1407 - rmse: 0.1952 - smape: 0.3927 - val_ia: 0.7122 - val_loss: 0.2495 - val_mae: 0.3866 - val_rmse: 0.4665 - val_smape: 0.7914

Epoch 17/32

287/287 - 7s - 25ms/step - ia: 0.9132 - loss: 0.0387 - mae: 0.1409 - rmse: 0.1954 - smape: 0.3923 - val_ia: 0.7126 - val_loss: 0.2604 - val_mae: 0.3884 - val_rmse: 0.4650 - val_smape: 0.7807

Epoch 18/32

287/287 - 7s - 24ms/step - ia: 0.9146 - loss: 0.0382 - mae: 0.1388 - rmse: 0.1937 - smape: 0.3873 - val_ia: 0.7256 - val_loss: 0.2216 - val_mae: 0.3584 - val_rmse: 0.4375 - val_smape: 0.7666

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:38 607ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 96%|█████████▌| 48/50 [14:08:48<14:38, 439.19s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 29s - 25ms/step - ia: 0.1478 - loss: 0.9640 - mae: 0.8187 - rmse: 0.9776 - smape: 1.8032 - val_ia: 0.2368 - val_loss: 0.8244 - val_mae: 0.7557 - val_rmse: 0.8290 - val_smape: 1.7702

Epoch 2/128

1146/1146 - 19s - 17ms/step - ia: 0.1896 - loss: 0.9030 - mae: 0.7953 - rmse: 0.9459 - smape: 1.6629 - val_ia: 0.2412 - val_loss: 0.7886 - val_mae: 0.7378 - val_rmse: 0.8097 - val_smape: 1.6093

Epoch 3/128

1146/1146 - 19s - 17ms/step - ia: 0.2644 - loss: 0.8150 - mae: 0.7579 - rmse: 0.8986 - smape: 1.5090 - val_ia: 0.2484 - val_loss: 0.7560 - val_mae: 0.7207 - val_rmse: 0.7884 - val_smape: 1.4546

Epoch 4/128

1146/1146 - 21s - 18ms/step - ia: 0.3713 - loss: 0.7002 - mae: 0.6995 - rmse: 0.8326 - smape: 1.3340 - val_ia: 0.2571 - val_loss: 0.7780 - val_mae: 0.7294 - val_rmse: 0.7924 - val_smape: 1.3534

Epoch 5/128

1146/1146 - 19s - 17ms/step - ia: 0.4826 - loss: 0.5861 - mae: 0.6308 - rmse: 0.7613 - smape: 1.1625 - val_ia: 0.2710 - val_loss: 0.9263 - val_mae: 0.7967 - val_rmse: 0.8617 - val_smape: 1.3283

Epoch 6/128

1146/1146 - 19s - 16ms/step - ia: 0.5570 - loss: 0.5126 - mae: 0.5808 - rmse: 0.7114 - smape: 1.0515 - val_ia: 0.2666 - val_loss: 1.1296 - val_mae: 0.8836 - val_rmse: 0.9540 - val_smape: 1.3330

Epoch 7/128

1146/1146 - 19s - 17ms/step - ia: 0.5963 - loss: 0.4751 - mae: 0.5520 - rmse: 0.6847 - smape: 0.9916 - val_ia: 0.2628 - val_loss: 1.2470 - val_mae: 0.9333 - val_rmse: 1.0058 - val_smape: 1.3400

Epoch 8/128

1146/1146 - 21s - 18ms/step - ia: 0.6132 - loss: 0.4553 - mae: 0.5379 - rmse: 0.6699 - smape: 0.9598 - val_ia: 0.2624 - val_loss: 1.2923 - val_mae: 0.9512 - val_rmse: 1.0252 - val_smape: 1.3333

Epoch 9/128

1146/1146 - 19s - 17ms/step - ia: 0.6231 - loss: 0.4414 - mae: 0.5294 - rmse: 0.6595 - smape: 0.9439 - val_ia: 0.2633 - val_loss: 1.3009 - val_mae: 0.9547 - val_rmse: 1.0293 - val_smape: 1.3244

Epoch 10/128

1146/1146 - 19s - 17ms/step - ia: 0.6299 - loss: 0.4314 - mae: 0.5225 - rmse: 0.6523 - smape: 0.9265 - val_ia: 0.2653 - val_loss: 1.2914 - val_mae: 0.9508 - val_rmse: 1.0261 - val_smape: 1.3144

Epoch 11/128

1146/1146 - 19s - 17ms/step - ia: 0.6341 - loss: 0.4232 - mae: 0.5184 - rmse: 0.6461 - smape: 0.9194 - val_ia: 0.2692 - val_loss: 1.2777 - val_mae: 0.9419 - val_rmse: 1.0194 - val_smape: 1.2974

Epoch 12/128

1146/1146 - 19s - 17ms/step - ia: 0.6389 - loss: 0.4173 - mae: 0.5145 - rmse: 0.6413 - smape: 0.9104 - val_ia: 0.2723 - val_loss: 1.2564 - val_mae: 0.9322 - val_rmse: 1.0105 - val_smape: 1.2865

Epoch 13/128

1146/1146 - 19s - 17ms/step - ia: 0.6416 - loss: 0.4102 - mae: 0.5104 - rmse: 0.6359 - smape: 0.9053 - val_ia: 0.2751 - val_loss: 1.2439 - val_mae: 0.9266 - val_rmse: 1.0057 - val_smape: 1.2784

Epoch 14/128

1146/1146 - 19s - 17ms/step - ia: 0.6454 - loss: 0.4050 - mae: 0.5079 - rmse: 0.6319 - smape: 0.9001 - val_ia: 0.2787 - val_loss: 1.2264 - val_mae: 0.9173 - val_rmse: 0.9977 - val_smape: 1.2673

Epoch 15/128

1146/1146 - 19s - 17ms/step - ia: 0.6483 - loss: 0.3996 - mae: 0.5039 - rmse: 0.6275 - smape: 0.8931 - val_ia: 0.2813 - val_loss: 1.2051 - val_mae: 0.9077 - val_rmse: 0.9885 - val_smape: 1.2594

Epoch 16/128

1146/1146 - 19s - 17ms/step - ia: 0.6511 - loss: 0.3932 - mae: 0.5005 - rmse: 0.6227 - smape: 0.8888 - val_ia: 0.2830 - val_loss: 1.1896 - val_mae: 0.9020 - val_rmse: 0.9825 - val_smape: 1.2555

Epoch 17/128

1146/1146 - 19s - 17ms/step - ia: 0.6529 - loss: 0.3917 - mae: 0.4997 - rmse: 0.6215 - smape: 0.8851 - val_ia: 0.2849 - val_loss: 1.1624 - val_mae: 0.8901 - val_rmse: 0.9705 - val_smape: 1.2492

Epoch 18/128

1146/1146 - 19s - 16ms/step - ia: 0.6552 - loss: 0.3863 - mae: 0.4957 - rmse: 0.6171 - smape: 0.8782 - val_ia: 0.2861 - val_loss: 1.1501 - val_mae: 0.8842 - val_rmse: 0.9648 - val_smape: 1.2448

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 98%|█████████▊| 49/50 [14:14:48<06:55, 415.60s/trial, best loss: 0.10860423576847295]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 9s - 16ms/step - ia: 0.3628 - loss: 1.8972 - mae: 1.1182 - rmse: 1.3724 - smape: 1.3296 - val_ia: 0.3182 - val_loss: 1.2532 - val_mae: 0.8733 - val_rmse: 1.0330 - val_smape: 1.1617

Epoch 2/16

573/573 - 3s - 6ms/step - ia: 0.3457 - loss: 1.5285 - mae: 1.0087 - rmse: 1.2321 - smape: 1.3487 - val_ia: 0.3028 - val_loss: 1.0414 - val_mae: 0.8081 - val_rmse: 0.9513 - val_smape: 1.1898

Epoch 3/16

573/573 - 4s - 6ms/step - ia: 0.3149 - loss: 1.3074 - mae: 0.9404 - rmse: 1.1397 - smape: 1.3871 - val_ia: 0.2884 - val_loss: 0.9161 - val_mae: 0.7703 - val_rmse: 0.9029 - val_smape: 1.2403

Epoch 4/16

573/573 - 3s - 6ms/step - ia: 0.2778 - loss: 1.1615 - mae: 0.8925 - rmse: 1.0743 - smape: 1.4433 - val_ia: 0.2823 - val_loss: 0.8454 - val_mae: 0.7488 - val_rmse: 0.8757 - val_smape: 1.3100

Epoch 5/16

573/573 - 3s - 6ms/step - ia: 0.2357 - loss: 1.0707 - mae: 0.8615 - rmse: 1.0316 - smape: 1.5138 - val_ia: 0.2868 - val_loss: 0.8096 - val_mae: 0.7392 - val_rmse: 0.8620 - val_smape: 1.4027

Epoch 6/16

573/573 - 4s - 6ms/step - ia: 0.2051 - loss: 1.0153 - mae: 0.8399 - rmse: 1.0049 - smape: 1.5806 - val_ia: 0.2902 - val_loss: 0.7956 - val_mae: 0.7373 - val_rmse: 0.8566 - val_smape: 1.5217

Epoch 7/16

573/573 - 3s - 6ms/step - ia: 0.1895 - loss: 0.9842 - mae: 0.8262 - rmse: 0.9895 - smape: 1.6279 - val_ia: 0.2920 - val_loss: 0.7930 - val_mae: 0.7386 - val_rmse: 0.8554 - val_smape: 1.6649

Epoch 8/16

573/573 - 3s - 6ms/step - ia: 0.1839 - loss: 0.9662 - mae: 0.8198 - rmse: 0.9803 - smape: 1.6406 - val_ia: 0.2938 - val_loss: 0.7927 - val_mae: 0.7394 - val_rmse: 0.8546 - val_smape: 1.6810

Epoch 9/16

573/573 - 3s - 6ms/step - ia: 0.1926 - loss: 0.9461 - mae: 0.8104 - rmse: 0.9702 - smape: 1.6158 - val_ia: 0.2959 - val_loss: 0.7908 - val_mae: 0.7385 - val_rmse: 0.8527 - val_smape: 1.6365

Epoch 10/16

573/573 - 4s - 6ms/step - ia: 0.2062 - loss: 0.9301 - mae: 0.8032 - rmse: 0.9621 - smape: 1.5819 - val_ia: 0.2985 - val_loss: 0.7847 - val_mae: 0.7350 - val_rmse: 0.8485 - val_smape: 1.5875

Epoch 11/16

573/573 - 4s - 6ms/step - ia: 0.2231 - loss: 0.9103 - mae: 0.7967 - rmse: 0.9518 - smape: 1.5521 - val_ia: 0.3016 - val_loss: 0.7775 - val_mae: 0.7308 - val_rmse: 0.8436 - val_smape: 1.5391

Epoch 12/16

573/573 - 3s - 6ms/step - ia: 0.2409 - loss: 0.8897 - mae: 0.7876 - rmse: 0.9408 - smape: 1.5186 - val_ia: 0.3057 - val_loss: 0.7682 - val_mae: 0.7251 - val_rmse: 0.8375 - val_smape: 1.4917

Epoch 13/16

573/573 - 3s - 6ms/step - ia: 0.2568 - loss: 0.8769 - mae: 0.7820 - rmse: 0.9341 - smape: 1.4905 - val_ia: 0.3103 - val_loss: 0.7598 - val_mae: 0.7197 - val_rmse: 0.8317 - val_smape: 1.4477

Epoch 14/16

573/573 - 3s - 6ms/step - ia: 0.2788 - loss: 0.8521 - mae: 0.7713 - rmse: 0.9209 - smape: 1.4567 - val_ia: 0.3149 - val_loss: 0.7518 - val_mae: 0.7142 - val_rmse: 0.8260 - val_smape: 1.4063

Epoch 15/16

573/573 - 5s - 9ms/step - ia: 0.3022 - loss: 0.8293 - mae: 0.7599 - rmse: 0.9086 - smape: 1.4197 - val_ia: 0.3199 - val_loss: 0.7449 - val_mae: 0.7092 - val_rmse: 0.8209 - val_smape: 1.3697

Epoch 16/16

573/573 - 3s - 6ms/step - ia: 0.3226 - loss: 0.8077 - mae: 0.7505 - rmse: 0.8966 - smape: 1.3883 - val_ia: 0.3249 - val_loss: 0.7412 - val_mae: 0.7057 - val_rmse: 0.8173 - val_smape: 1.3394

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 54s 337ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

100%|██████████| 50/50 [14:15:51<00:00, 1027.03s/trial, best loss: 0.10860423576847295]

In [22]:
print(best)

{'activation': 1, 'batch': 2, 'dropout': 0.1, 'epochs': 2, 'layers': 4.0, 'learning_rate': 0.0001704833214115943, 'units': 3}