Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv('C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNpollutionFinal.csv')

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 24
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [16]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 12, 6)
Las dimensiones de testX son:  (8797, 12, 6)
Las dimensiones de valX son:  (4333, 12, 6)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 43s - 45ms/step - ia: 0.2399 - loss: 0.9354 - mae: 0.7228 - rmse: 0.9470 - smape: 1.5648 - val_ia: 0.2466 - val_loss: 0.8686 - val_mae: 0.6920 - val_rmse: 0.7803 - val_smape: 1.4890

Epoch 2/128

958/958 - 16s - 16ms/step - ia: 0.2814 - loss: 0.9056 - mae: 0.7088 - rmse: 0.9310 - smape: 1.4769 - val_ia: 0.2497 - val_loss: 0.8459 - val_mae: 0.6823 - val_rmse: 0.7728 - val_smape: 1.4285

Epoch 3/128

958/958 - 14s - 15ms/step - ia: 0.2964 - loss: 0.8922 - mae: 0.7020 - rmse: 0.9255 - smape: 1.4487 - val_ia: 0.2493 - val_loss: 0.8401 - val_mae: 0.6844 - val_rmse: 0.7756 - val_smape: 1.4308

Epoch 4/128

958/958 - 15s - 15ms/step - ia: 0.3142 - loss: 0.8765 - mae: 0.6958 - rmse: 0.9178 - smape: 1.4226 - val_ia: 0.2466 - val_loss: 0.8345 - val_mae: 0.6871 - val_rmse: 0.7800 - val_smape: 1.4130

Epoch 5/128

958/958 - 19s - 19ms/step - ia: 0.3209 - loss: 0.8697 - mae: 0.6930 - rmse: 0.9133 - smape: 1.4067 - val_ia: 0.2481 - val_loss: 0.8187 - val_mae: 0.6780 - val_rmse: 0.7689 - val_smape: 1.4078

Epoch 6/128

958/958 - 13s - 14ms/step - ia: 0.3336 - loss: 0.8580 - mae: 0.6868 - rmse: 0.9085 - smape: 1.3835 - val_ia: 0.2490 - val_loss: 0.8178 - val_mae: 0.6792 - val_rmse: 0.7722 - val_smape: 1.3822

Epoch 7/128

958/958 - 14s - 15ms/step - ia: 0.3447 - loss: 0.8458 - mae: 0.6811 - rmse: 0.9006 - smape: 1.3672 - val_ia: 0.2504 - val_loss: 0.8001 - val_mae: 0.6680 - val_rmse: 0.7589 - val_smape: 1.3693

Epoch 8/128

958/958 - 15s - 16ms/step - ia: 0.3501 - loss: 0.8430 - mae: 0.6787 - rmse: 0.8991 - smape: 1.3563 - val_ia: 0.2508 - val_loss: 0.8055 - val_mae: 0.6744 - val_rmse: 0.7664 - val_smape: 1.3612

Epoch 9/128

958/958 - 14s - 15ms/step - ia: 0.3524 - loss: 0.8378 - mae: 0.6778 - rmse: 0.8969 - smape: 1.3530 - val_ia: 0.2515 - val_loss: 0.7950 - val_mae: 0.6680 - val_rmse: 0.7596 - val_smape: 1.3647

Epoch 10/128

958/958 - 14s - 15ms/step - ia: 0.3548 - loss: 0.8370 - mae: 0.6751 - rmse: 0.8952 - smape: 1.3462 - val_ia: 0.2529 - val_loss: 0.7851 - val_mae: 0.6644 - val_rmse: 0.7557 - val_smape: 1.3630

Epoch 11/128

958/958 - 15s - 16ms/step - ia: 0.3611 - loss: 0.8286 - mae: 0.6728 - rmse: 0.8919 - smape: 1.3354 - val_ia: 0.2527 - val_loss: 0.7900 - val_mae: 0.6673 - val_rmse: 0.7602 - val_smape: 1.3443

Epoch 12/128

958/958 - 18s - 19ms/step - ia: 0.3626 - loss: 0.8272 - mae: 0.6722 - rmse: 0.8903 - smape: 1.3338 - val_ia: 0.2543 - val_loss: 0.7848 - val_mae: 0.6645 - val_rmse: 0.7572 - val_smape: 1.3450

Epoch 13/128

958/958 - 14s - 14ms/step - ia: 0.3670 - loss: 0.8224 - mae: 0.6705 - rmse: 0.8886 - smape: 1.3271 - val_ia: 0.2531 - val_loss: 0.7913 - val_mae: 0.6646 - val_rmse: 0.7574 - val_smape: 1.3371

Epoch 14/128

958/958 - 20s - 20ms/step - ia: 0.3685 - loss: 0.8216 - mae: 0.6679 - rmse: 0.8876 - smape: 1.3269 - val_ia: 0.2545 - val_loss: 0.7818 - val_mae: 0.6602 - val_rmse: 0.7529 - val_smape: 1.3250

Epoch 15/128

958/958 - 20s - 21ms/step - ia: 0.3724 - loss: 0.8193 - mae: 0.6673 - rmse: 0.8870 - smape: 1.3172 - val_ia: 0.2544 - val_loss: 0.7889 - val_mae: 0.6636 - val_rmse: 0.7565 - val_smape: 1.3303

Epoch 16/128

958/958 - 13s - 13ms/step - ia: 0.3694 - loss: 0.8222 - mae: 0.6678 - rmse: 0.8881 - smape: 1.3215 - val_ia: 0.2539 - val_loss: 0.7997 - val_mae: 0.6704 - val_rmse: 0.7653 - val_smape: 1.3162

Epoch 17/128

958/958 - 22s - 23ms/step - ia: 0.3764 - loss: 0.8105 - mae: 0.6637 - rmse: 0.8831 - smape: 1.3133 - val_ia: 0.2548 - val_loss: 0.7829 - val_mae: 0.6599 - val_rmse: 0.7518 - val_smape: 1.3244

Epoch 18/128

958/958 - 12s - 13ms/step - ia: 0.3759 - loss: 0.8100 - mae: 0.6639 - rmse: 0.8819 - smape: 1.3131 - val_ia: 0.2554 - val_loss: 0.7759 - val_mae: 0.6587 - val_rmse: 0.7516 - val_smape: 1.3132

Epoch 19/128

958/958 - 13s - 13ms/step - ia: 0.3793 - loss: 0.8070 - mae: 0.6616 - rmse: 0.8804 - smape: 1.3053 - val_ia: 0.2564 - val_loss: 0.7890 - val_mae: 0.6641 - val_rmse: 0.7592 - val_smape: 1.3026

Epoch 20/128

958/958 - 13s - 13ms/step - ia: 0.3842 - loss: 0.8060 - mae: 0.6605 - rmse: 0.8769 - smape: 1.3003 - val_ia: 0.2563 - val_loss: 0.7771 - val_mae: 0.6543 - val_rmse: 0.7468 - val_smape: 1.3021

Epoch 21/128

958/958 - 10s - 10ms/step - ia: 0.3810 - loss: 0.8061 - mae: 0.6605 - rmse: 0.8783 - smape: 1.3039 - val_ia: 0.2568 - val_loss: 0.7819 - val_mae: 0.6587 - val_rmse: 0.7532 - val_smape: 1.2916

Epoch 22/128

958/958 - 13s - 14ms/step - ia: 0.3815 - loss: 0.8097 - mae: 0.6609 - rmse: 0.8809 - smape: 1.2990 - val_ia: 0.2564 - val_loss: 0.7820 - val_mae: 0.6576 - val_rmse: 0.7523 - val_smape: 1.2903

Epoch 23/128

958/958 - 13s - 14ms/step - ia: 0.3860 - loss: 0.8014 - mae: 0.6585 - rmse: 0.8782 - smape: 1.2953 - val_ia: 0.2582 - val_loss: 0.7851 - val_mae: 0.6586 - val_rmse: 0.7540 - val_smape: 1.2841

Epoch 24/128

958/958 - 12s - 13ms/step - ia: 0.3877 - loss: 0.7984 - mae: 0.6570 - rmse: 0.8759 - smape: 1.2937 - val_ia: 0.2575 - val_loss: 0.7873 - val_mae: 0.6585 - val_rmse: 0.7526 - val_smape: 1.3005

Epoch 25/128

958/958 - 21s - 22ms/step - ia: 0.3862 - loss: 0.8009 - mae: 0.6578 - rmse: 0.8769 - smape: 1.2962 - val_ia: 0.2587 - val_loss: 0.7729 - val_mae: 0.6523 - val_rmse: 0.7462 - val_smape: 1.2890

Epoch 26/128

958/958 - 22s - 23ms/step - ia: 0.3878 - loss: 0.8019 - mae: 0.6571 - rmse: 0.8783 - smape: 1.2899 - val_ia: 0.2593 - val_loss: 0.7771 - val_mae: 0.6558 - val_rmse: 0.7489 - val_smape: 1.3069

Epoch 27/128

958/958 - 15s - 15ms/step - ia: 0.3931 - loss: 0.7917 - mae: 0.6538 - rmse: 0.8712 - smape: 1.2855 - val_ia: 0.2597 - val_loss: 0.7794 - val_mae: 0.6525 - val_rmse: 0.7475 - val_smape: 1.2777

Epoch 28/128

958/958 - 14s - 15ms/step - ia: 0.3940 - loss: 0.7876 - mae: 0.6533 - rmse: 0.8690 - smape: 1.2851 - val_ia: 0.2606 - val_loss: 0.7722 - val_mae: 0.6507 - val_rmse: 0.7441 - val_smape: 1.2896

Epoch 29/128

958/958 - 13s - 14ms/step - ia: 0.3937 - loss: 0.7877 - mae: 0.6523 - rmse: 0.8706 - smape: 1.2837 - val_ia: 0.2605 - val_loss: 0.7861 - val_mae: 0.6594 - val_rmse: 0.7546 - val_smape: 1.2934

Epoch 30/128

958/958 - 11s - 12ms/step - ia: 0.3967 - loss: 0.7852 - mae: 0.6526 - rmse: 0.8675 - smape: 1.2814 - val_ia: 0.2597 - val_loss: 0.8029 - val_mae: 0.6602 - val_rmse: 0.7564 - val_smape: 1.2818

Epoch 31/128

958/958 - 11s - 12ms/step - ia: 0.3929 - loss: 0.7846 - mae: 0.6516 - rmse: 0.8674 - smape: 1.2881 - val_ia: 0.2609 - val_loss: 0.7942 - val_mae: 0.6592 - val_rmse: 0.7551 - val_smape: 1.2800

Epoch 32/128

958/958 - 13s - 13ms/step - ia: 0.3971 - loss: 0.7821 - mae: 0.6512 - rmse: 0.8655 - smape: 1.2810 - val_ia: 0.2609 - val_loss: 0.7905 - val_mae: 0.6536 - val_rmse: 0.7496 - val_smape: 1.2673

Epoch 33/128

958/958 - 12s - 12ms/step - ia: 0.3978 - loss: 0.7810 - mae: 0.6501 - rmse: 0.8664 - smape: 1.2793 - val_ia: 0.2624 - val_loss: 0.7714 - val_mae: 0.6498 - val_rmse: 0.7440 - val_smape: 1.2830

Epoch 34/128

958/958 - 12s - 13ms/step - ia: 0.3985 - loss: 0.7782 - mae: 0.6482 - rmse: 0.8650 - smape: 1.2751 - val_ia: 0.2612 - val_loss: 0.8047 - val_mae: 0.6584 - val_rmse: 0.7557 - val_smape: 1.2753

Epoch 35/128

958/958 - 22s - 23ms/step - ia: 0.3991 - loss: 0.7775 - mae: 0.6483 - rmse: 0.8641 - smape: 1.2770 - val_ia: 0.2621 - val_loss: 0.8028 - val_mae: 0.6628 - val_rmse: 0.7595 - val_smape: 1.2947

Epoch 36/128

958/958 - 21s - 22ms/step - ia: 0.4001 - loss: 0.7781 - mae: 0.6485 - rmse: 0.8645 - smape: 1.2747 - val_ia: 0.2604 - val_loss: 0.7916 - val_mae: 0.6561 - val_rmse: 0.7509 - val_smape: 1.2985

Epoch 37/128

958/958 - 12s - 12ms/step - ia: 0.3997 - loss: 0.7778 - mae: 0.6480 - rmse: 0.8648 - smape: 1.2754 - val_ia: 0.2616 - val_loss: 0.8106 - val_mae: 0.6607 - val_rmse: 0.7575 - val_smape: 1.2895

Epoch 38/128

958/958 - 22s - 23ms/step - ia: 0.4010 - loss: 0.7709 - mae: 0.6469 - rmse: 0.8624 - smape: 1.2776 - val_ia: 0.2635 - val_loss: 0.8209 - val_mae: 0.6589 - val_rmse: 0.7571 - val_smape: 1.2782

Epoch 39/128

958/958 - 12s - 13ms/step - ia: 0.3998 - loss: 0.7755 - mae: 0.6482 - rmse: 0.8631 - smape: 1.2768 - val_ia: 0.2617 - val_loss: 0.7962 - val_mae: 0.6564 - val_rmse: 0.7534 - val_smape: 1.2826

Epoch 40/128

958/958 - 21s - 22ms/step - ia: 0.4052 - loss: 0.7678 - mae: 0.6454 - rmse: 0.8600 - smape: 1.2730 - val_ia: 0.2617 - val_loss: 0.8250 - val_mae: 0.6621 - val_rmse: 0.7596 - val_smape: 1.2931

Epoch 41/128

958/958 - 14s - 14ms/step - ia: 0.4037 - loss: 0.7683 - mae: 0.6456 - rmse: 0.8602 - smape: 1.2725 - val_ia: 0.2615 - val_loss: 0.8361 - val_mae: 0.6650 - val_rmse: 0.7645 - val_smape: 1.2873

Epoch 42/128

958/958 - 12s - 13ms/step - ia: 0.4038 - loss: 0.7698 - mae: 0.6467 - rmse: 0.8605 - smape: 1.2737 - val_ia: 0.2619 - val_loss: 0.8303 - val_mae: 0.6629 - val_rmse: 0.7615 - val_smape: 1.2774

Epoch 43/128

958/958 - 12s - 12ms/step - ia: 0.4062 - loss: 0.7679 - mae: 0.6442 - rmse: 0.8587 - smape: 1.2678 - val_ia: 0.2615 - val_loss: 0.8134 - val_mae: 0.6648 - val_rmse: 0.7609 - val_smape: 1.3152

Epoch 44/128

958/958 - 28s - 30ms/step - ia: 0.4063 - loss: 0.7609 - mae: 0.6431 - rmse: 0.8562 - smape: 1.2700 - val_ia: 0.2613 - val_loss: 0.8036 - val_mae: 0.6580 - val_rmse: 0.7556 - val_smape: 1.2873

Epoch 45/128

958/958 - 21s - 22ms/step - ia: 0.4075 - loss: 0.7633 - mae: 0.6437 - rmse: 0.8570 - smape: 1.2694 - val_ia: 0.2626 - val_loss: 0.8191 - val_mae: 0.6615 - val_rmse: 0.7608 - val_smape: 1.2828

Epoch 46/128

958/958 - 12s - 13ms/step - ia: 0.4090 - loss: 0.7630 - mae: 0.6421 - rmse: 0.8561 - smape: 1.2659 - val_ia: 0.2614 - val_loss: 0.8172 - val_mae: 0.6606 - val_rmse: 0.7592 - val_smape: 1.2845

Epoch 47/128

958/958 - 29s - 30ms/step - ia: 0.4122 - loss: 0.7573 - mae: 0.6409 - rmse: 0.8537 - smape: 1.2599 - val_ia: 0.2624 - val_loss: 0.8714 - val_mae: 0.6713 - val_rmse: 0.7767 - val_smape: 1.2518

Epoch 48/128

958/958 - 12s - 12ms/step - ia: 0.4104 - loss: 0.7616 - mae: 0.6415 - rmse: 0.8565 - smape: 1.2642 - val_ia: 0.2621 - val_loss: 0.8151 - val_mae: 0.6636 - val_rmse: 0.7613 - val_smape: 1.3001

Epoch 48: early stopping

Restoring model weights from the end of the best epoch: 33.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:54 851ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

  2%|▏         | 1/50 [13:10<10:45:39, 790.61s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

120/120 - 59s - 495ms/step - ia: 0.2712 - loss: 0.8907 - mae: 0.6986 - rmse: 0.9406 - smape: 1.4669 - val_ia: 0.2969 - val_loss: 0.8057 - val_mae: 0.6710 - val_rmse: 0.8255 - val_smape: 1.3478

Epoch 2/16

120/120 - 34s - 282ms/step - ia: 0.3737 - loss: 0.8205 - mae: 0.6677 - rmse: 0.9037 - smape: 1.2972 - val_ia: 0.3185 - val_loss: 0.8048 - val_mae: 0.6785 - val_rmse: 0.8336 - val_smape: 1.3497

Epoch 3/16

120/120 - 27s - 223ms/step - ia: 0.4050 - loss: 0.7900 - mae: 0.6513 - rmse: 0.8867 - smape: 1.2530 - val_ia: 0.3452 - val_loss: 0.7981 - val_mae: 0.6725 - val_rmse: 0.8340 - val_smape: 1.3086

Epoch 4/16

120/120 - 43s - 356ms/step - ia: 0.4171 - loss: 0.7751 - mae: 0.6445 - rmse: 0.8775 - smape: 1.2341 - val_ia: 0.3625 - val_loss: 0.7880 - val_mae: 0.6559 - val_rmse: 0.8236 - val_smape: 1.2650

Epoch 5/16

120/120 - 24s - 203ms/step - ia: 0.4322 - loss: 0.7577 - mae: 0.6356 - rmse: 0.8684 - smape: 1.2130 - val_ia: 0.3627 - val_loss: 0.8162 - val_mae: 0.6642 - val_rmse: 0.8355 - val_smape: 1.2628

Epoch 6/16

120/120 - 42s - 350ms/step - ia: 0.4364 - loss: 0.7487 - mae: 0.6325 - rmse: 0.8628 - smape: 1.2096 - val_ia: 0.3745 - val_loss: 0.7937 - val_mae: 0.6459 - val_rmse: 0.8219 - val_smape: 1.2167

Epoch 7/16

120/120 - 23s - 191ms/step - ia: 0.4502 - loss: 0.7312 - mae: 0.6241 - rmse: 0.8528 - smape: 1.1918 - val_ia: 0.3772 - val_loss: 0.8118 - val_mae: 0.6579 - val_rmse: 0.8357 - val_smape: 1.2664

Epoch 8/16

120/120 - 47s - 389ms/step - ia: 0.4570 - loss: 0.7189 - mae: 0.6193 - rmse: 0.8453 - smape: 1.1864 - val_ia: 0.3779 - val_loss: 0.8856 - val_mae: 0.6714 - val_rmse: 0.8658 - val_smape: 1.2663

Epoch 9/16

120/120 - 32s - 268ms/step - ia: 0.4558 - loss: 0.7183 - mae: 0.6192 - rmse: 0.8454 - smape: 1.1872 - val_ia: 0.3629 - val_loss: 0.7963 - val_mae: 0.6499 - val_rmse: 0.8232 - val_smape: 1.2344

Epoch 10/16

120/120 - 25s - 206ms/step - ia: 0.4704 - loss: 0.6955 - mae: 0.6096 - rmse: 0.8317 - smape: 1.1695 - val_ia: 0.3561 - val_loss: 0.8247 - val_mae: 0.6594 - val_rmse: 0.8316 - val_smape: 1.2720

Epoch 11/16

120/120 - 30s - 246ms/step - ia: 0.4772 - loss: 0.6839 - mae: 0.6043 - rmse: 0.8244 - smape: 1.1611 - val_ia: 0.3583 - val_loss: 0.8304 - val_mae: 0.6685 - val_rmse: 0.8386 - val_smape: 1.2951

Epoch 12/16

120/120 - 42s - 349ms/step - ia: 0.4827 - loss: 0.6707 - mae: 0.5993 - rmse: 0.8166 - smape: 1.1600 - val_ia: 0.3538 - val_loss: 0.8341 - val_mae: 0.6674 - val_rmse: 0.8378 - val_smape: 1.3042

Epoch 13/16

120/120 - 30s - 252ms/step - ia: 0.4839 - loss: 0.6631 - mae: 0.5980 - rmse: 0.8123 - smape: 1.1626 - val_ia: 0.3579 - val_loss: 0.8824 - val_mae: 0.6662 - val_rmse: 0.8499 - val_smape: 1.2278

Epoch 14/16

120/120 - 21s - 175ms/step - ia: 0.4960 - loss: 0.6428 - mae: 0.5870 - rmse: 0.8000 - smape: 1.1447 - val_ia: 0.3533 - val_loss: 0.8971 - val_mae: 0.6883 - val_rmse: 0.8671 - val_smape: 1.3061

Epoch 15/16

120/120 - 21s - 173ms/step - ia: 0.5029 - loss: 0.6295 - mae: 0.5813 - rmse: 0.7911 - smape: 1.1393 - val_ia: 0.3572 - val_loss: 0.9311 - val_mae: 0.6767 - val_rmse: 0.8668 - val_smape: 1.2427

Epoch 16/16

120/120 - 19s - 158ms/step - ia: 0.5077 - loss: 0.6234 - mae: 0.5783 - rmse: 0.7878 - smape: 1.1313 - val_ia: 0.3425 - val_loss: 0.9421 - val_mae: 0.7148 - val_rmse: 0.8920 - val_smape: 1.3671

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:10 968ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step

  4%|▍         | 2/50 [21:53<8:26:29, 633.11s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 32s - 66ms/step - ia: 0.1412 - loss: 0.9889 - mae: 0.7327 - rmse: 0.9829 - smape: 1.7388 - val_ia: 0.2383 - val_loss: 0.9362 - val_mae: 0.7065 - val_rmse: 0.8237 - val_smape: 1.6973

Epoch 2/8

479/479 - 10s - 20ms/step - ia: 0.1441 - loss: 0.9876 - mae: 0.7317 - rmse: 0.9805 - smape: 1.7352 - val_ia: 0.2384 - val_loss: 0.9353 - val_mae: 0.7057 - val_rmse: 0.8230 - val_smape: 1.6937

Epoch 3/8

479/479 - 8s - 16ms/step - ia: 0.1463 - loss: 0.9865 - mae: 0.7309 - rmse: 0.9800 - smape: 1.7324 - val_ia: 0.2386 - val_loss: 0.9343 - val_mae: 0.7050 - val_rmse: 0.8224 - val_smape: 1.6907

Epoch 4/8

479/479 - 7s - 15ms/step - ia: 0.1443 - loss: 0.9860 - mae: 0.7304 - rmse: 0.9802 - smape: 1.7290 - val_ia: 0.2387 - val_loss: 0.9334 - val_mae: 0.7043 - val_rmse: 0.8217 - val_smape: 1.6879

Epoch 5/8

479/479 - 7s - 14ms/step - ia: 0.1479 - loss: 0.9855 - mae: 0.7302 - rmse: 0.9794 - smape: 1.7281 - val_ia: 0.2389 - val_loss: 0.9325 - val_mae: 0.7036 - val_rmse: 0.8211 - val_smape: 1.6851

Epoch 6/8

479/479 - 5s - 10ms/step - ia: 0.1478 - loss: 0.9849 - mae: 0.7292 - rmse: 0.9795 - smape: 1.7230 - val_ia: 0.2391 - val_loss: 0.9316 - val_mae: 0.7028 - val_rmse: 0.8205 - val_smape: 1.6818

Epoch 7/8

479/479 - 5s - 11ms/step - ia: 0.1491 - loss: 0.9841 - mae: 0.7286 - rmse: 0.9788 - smape: 1.7187 - val_ia: 0.2393 - val_loss: 0.9307 - val_mae: 0.7022 - val_rmse: 0.8199 - val_smape: 1.6792

Epoch 8/8

479/479 - 7s - 15ms/step - ia: 0.1484 - loss: 0.9836 - mae: 0.7283 - rmse: 0.9776 - smape: 1.7168 - val_ia: 0.2395 - val_loss: 0.9298 - val_mae: 0.7015 - val_rmse: 0.8193 - val_smape: 1.6761

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 5:03 2s/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step

  6%|▌         | 3/50 [23:19<5:00:06, 383.12s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

240/240 - 34s - 142ms/step - ia: 0.1178 - loss: 0.9810 - mae: 0.7444 - rmse: 0.9842 - smape: 1.7476 - val_ia: 0.2568 - val_loss: 0.9186 - val_mae: 0.7220 - val_rmse: 0.8592 - val_smape: 1.7450

Epoch 2/32

240/240 - 6s - 24ms/step - ia: 0.1581 - loss: 0.9465 - mae: 0.7315 - rmse: 0.9662 - smape: 1.6618 - val_ia: 0.2581 - val_loss: 0.8814 - val_mae: 0.7076 - val_rmse: 0.8428 - val_smape: 1.6177

Epoch 3/32

240/240 - 13s - 54ms/step - ia: 0.2043 - loss: 0.9185 - mae: 0.7206 - rmse: 0.9522 - smape: 1.5745 - val_ia: 0.2624 - val_loss: 0.8559 - val_mae: 0.6968 - val_rmse: 0.8321 - val_smape: 1.5253

Epoch 4/32

240/240 - 11s - 45ms/step - ia: 0.2431 - loss: 0.9004 - mae: 0.7117 - rmse: 0.9427 - smape: 1.5050 - val_ia: 0.2690 - val_loss: 0.8412 - val_mae: 0.6896 - val_rmse: 0.8265 - val_smape: 1.4632

Epoch 5/32

240/240 - 9s - 36ms/step - ia: 0.2722 - loss: 0.8876 - mae: 0.7054 - rmse: 0.9380 - smape: 1.4550 - val_ia: 0.2739 - val_loss: 0.8307 - val_mae: 0.6835 - val_rmse: 0.8220 - val_smape: 1.4140

Epoch 6/32

240/240 - 8s - 33ms/step - ia: 0.2918 - loss: 0.8828 - mae: 0.7024 - rmse: 0.9345 - smape: 1.4256 - val_ia: 0.2774 - val_loss: 0.8260 - val_mae: 0.6803 - val_rmse: 0.8199 - val_smape: 1.3923

Epoch 7/32

240/240 - 8s - 33ms/step - ia: 0.3022 - loss: 0.8813 - mae: 0.7005 - rmse: 0.9332 - smape: 1.4131 - val_ia: 0.2796 - val_loss: 0.8223 - val_mae: 0.6779 - val_rmse: 0.8183 - val_smape: 1.3785

Epoch 8/32

240/240 - 11s - 45ms/step - ia: 0.3082 - loss: 0.8759 - mae: 0.6981 - rmse: 0.9301 - smape: 1.4033 - val_ia: 0.2811 - val_loss: 0.8196 - val_mae: 0.6766 - val_rmse: 0.8171 - val_smape: 1.3719

Epoch 9/32

240/240 - 8s - 31ms/step - ia: 0.3117 - loss: 0.8745 - mae: 0.6968 - rmse: 0.9296 - smape: 1.3952 - val_ia: 0.2823 - val_loss: 0.8169 - val_mae: 0.6755 - val_rmse: 0.8161 - val_smape: 1.3669

Epoch 10/32

240/240 - 9s - 39ms/step - ia: 0.3175 - loss: 0.8693 - mae: 0.6942 - rmse: 0.9273 - smape: 1.3873 - val_ia: 0.2830 - val_loss: 0.8141 - val_mae: 0.6743 - val_rmse: 0.8148 - val_smape: 1.3617

Epoch 11/32

240/240 - 12s - 50ms/step - ia: 0.3194 - loss: 0.8690 - mae: 0.6937 - rmse: 0.9273 - smape: 1.3851 - val_ia: 0.2834 - val_loss: 0.8120 - val_mae: 0.6735 - val_rmse: 0.8139 - val_smape: 1.3606

Epoch 12/32

240/240 - 11s - 45ms/step - ia: 0.3211 - loss: 0.8662 - mae: 0.6925 - rmse: 0.9269 - smape: 1.3814 - val_ia: 0.2849 - val_loss: 0.8113 - val_mae: 0.6738 - val_rmse: 0.8143 - val_smape: 1.3620

Epoch 13/32

240/240 - 11s - 46ms/step - ia: 0.3232 - loss: 0.8648 - mae: 0.6920 - rmse: 0.9254 - smape: 1.3797 - val_ia: 0.2850 - val_loss: 0.8084 - val_mae: 0.6728 - val_rmse: 0.8129 - val_smape: 1.3594

Epoch 14/32

240/240 - 11s - 44ms/step - ia: 0.3253 - loss: 0.8612 - mae: 0.6911 - rmse: 0.9231 - smape: 1.3770 - val_ia: 0.2855 - val_loss: 0.8062 - val_mae: 0.6719 - val_rmse: 0.8120 - val_smape: 1.3558

Epoch 15/32

240/240 - 10s - 42ms/step - ia: 0.3264 - loss: 0.8617 - mae: 0.6903 - rmse: 0.9236 - smape: 1.3763 - val_ia: 0.2858 - val_loss: 0.8043 - val_mae: 0.6716 - val_rmse: 0.8114 - val_smape: 1.3566

Epoch 16/32

240/240 - 8s - 32ms/step - ia: 0.3291 - loss: 0.8594 - mae: 0.6895 - rmse: 0.9218 - smape: 1.3740 - val_ia: 0.2863 - val_loss: 0.8030 - val_mae: 0.6716 - val_rmse: 0.8111 - val_smape: 1.3576

Epoch 17/32

240/240 - 6s - 27ms/step - ia: 0.3277 - loss: 0.8581 - mae: 0.6896 - rmse: 0.9218 - smape: 1.3757 - val_ia: 0.2875 - val_loss: 0.8027 - val_mae: 0.6715 - val_rmse: 0.8114 - val_smape: 1.3563

Epoch 18/32

240/240 - 6s - 26ms/step - ia: 0.3316 - loss: 0.8565 - mae: 0.6882 - rmse: 0.9193 - smape: 1.3714 - val_ia: 0.2881 - val_loss: 0.8010 - val_mae: 0.6707 - val_rmse: 0.8105 - val_smape: 1.3535

Epoch 19/32

240/240 - 6s - 25ms/step - ia: 0.3322 - loss: 0.8553 - mae: 0.6867 - rmse: 0.9202 - smape: 1.3672 - val_ia: 0.2884 - val_loss: 0.7994 - val_mae: 0.6702 - val_rmse: 0.8098 - val_smape: 1.3537

Epoch 20/32

240/240 - 6s - 25ms/step - ia: 0.3322 - loss: 0.8515 - mae: 0.6863 - rmse: 0.9177 - smape: 1.3707 - val_ia: 0.2897 - val_loss: 0.7990 - val_mae: 0.6701 - val_rmse: 0.8100 - val_smape: 1.3515

Epoch 21/32

240/240 - 12s - 48ms/step - ia: 0.3351 - loss: 0.8542 - mae: 0.6861 - rmse: 0.9189 - smape: 1.3656 - val_ia: 0.2899 - val_loss: 0.7979 - val_mae: 0.6697 - val_rmse: 0.8096 - val_smape: 1.3510

Epoch 22/32

240/240 - 7s - 30ms/step - ia: 0.3388 - loss: 0.8506 - mae: 0.6854 - rmse: 0.9176 - smape: 1.3623 - val_ia: 0.2897 - val_loss: 0.7968 - val_mae: 0.6697 - val_rmse: 0.8092 - val_smape: 1.3542

Epoch 23/32

240/240 - 10s - 42ms/step - ia: 0.3379 - loss: 0.8486 - mae: 0.6844 - rmse: 0.9165 - smape: 1.3619 - val_ia: 0.2904 - val_loss: 0.7960 - val_mae: 0.6692 - val_rmse: 0.8088 - val_smape: 1.3516

Epoch 24/32

240/240 - 10s - 42ms/step - ia: 0.3366 - loss: 0.8507 - mae: 0.6852 - rmse: 0.9170 - smape: 1.3630 - val_ia: 0.2911 - val_loss: 0.7951 - val_mae: 0.6688 - val_rmse: 0.8085 - val_smape: 1.3500

Epoch 25/32

240/240 - 7s - 30ms/step - ia: 0.3383 - loss: 0.8494 - mae: 0.6850 - rmse: 0.9163 - smape: 1.3642 - val_ia: 0.2917 - val_loss: 0.7947 - val_mae: 0.6691 - val_rmse: 0.8087 - val_smape: 1.3537

Epoch 26/32

240/240 - 7s - 29ms/step - ia: 0.3399 - loss: 0.8464 - mae: 0.6826 - rmse: 0.9154 - smape: 1.3578 - val_ia: 0.2923 - val_loss: 0.7938 - val_mae: 0.6687 - val_rmse: 0.8083 - val_smape: 1.3522

Epoch 27/32

240/240 - 7s - 29ms/step - ia: 0.3388 - loss: 0.8466 - mae: 0.6826 - rmse: 0.9164 - smape: 1.3593 - val_ia: 0.2926 - val_loss: 0.7928 - val_mae: 0.6683 - val_rmse: 0.8079 - val_smape: 1.3506

Epoch 28/32

240/240 - 10s - 44ms/step - ia: 0.3403 - loss: 0.8443 - mae: 0.6834 - rmse: 0.9132 - smape: 1.3622 - val_ia: 0.2936 - val_loss: 0.7930 - val_mae: 0.6683 - val_rmse: 0.8083 - val_smape: 1.3501

Epoch 29/32

240/240 - 10s - 42ms/step - ia: 0.3424 - loss: 0.8441 - mae: 0.6818 - rmse: 0.9142 - smape: 1.3562 - val_ia: 0.2943 - val_loss: 0.7923 - val_mae: 0.6680 - val_rmse: 0.8080 - val_smape: 1.3486

Epoch 30/32

240/240 - 7s - 29ms/step - ia: 0.3447 - loss: 0.8424 - mae: 0.6813 - rmse: 0.9122 - smape: 1.3540 - val_ia: 0.2946 - val_loss: 0.7917 - val_mae: 0.6678 - val_rmse: 0.8078 - val_smape: 1.3494

Epoch 31/32

240/240 - 10s - 43ms/step - ia: 0.3459 - loss: 0.8430 - mae: 0.6810 - rmse: 0.9130 - smape: 1.3541 - val_ia: 0.2951 - val_loss: 0.7914 - val_mae: 0.6681 - val_rmse: 0.8080 - val_smape: 1.3518

Epoch 32/32

240/240 - 11s - 44ms/step - ia: 0.3460 - loss: 0.8396 - mae: 0.6797 - rmse: 0.9111 - smape: 1.3518 - val_ia: 0.2955 - val_loss: 0.7902 - val_mae: 0.6672 - val_rmse: 0.8072 - val_smape: 1.3478

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:38 2s/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

  8%|▊         | 4/50 [28:34<4:33:19, 356.52s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

3830/3830 - 36s - 9ms/step - ia: 0.2336 - loss: 1.0639 - mae: 0.8032 - rmse: 0.9765 - smape: 1.6337 - val_ia: 0.1794 - val_loss: 0.9842 - val_mae: 0.7700 - val_rmse: 0.8053 - val_smape: 1.7567

Epoch 2/64

3830/3830 - 28s - 7ms/step - ia: 0.2372 - loss: 1.0492 - mae: 0.7851 - rmse: 0.9642 - smape: 1.6281 - val_ia: 0.1815 - val_loss: 0.9707 - val_mae: 0.7531 - val_rmse: 0.7887 - val_smape: 1.8229

Epoch 3/64

3830/3830 - 39s - 10ms/step - ia: 0.2379 - loss: 1.0439 - mae: 0.7765 - rmse: 0.9601 - smape: 1.6215 - val_ia: 0.1838 - val_loss: 0.9643 - val_mae: 0.7435 - val_rmse: 0.7793 - val_smape: 1.8814

Epoch 4/64

3830/3830 - 28s - 7ms/step - ia: 0.2419 - loss: 1.0395 - mae: 0.7696 - rmse: 0.9542 - smape: 1.6097 - val_ia: 0.1850 - val_loss: 0.9608 - val_mae: 0.7382 - val_rmse: 0.7741 - val_smape: 1.9220

Epoch 5/64

3830/3830 - 38s - 10ms/step - ia: 0.2425 - loss: 1.0389 - mae: 0.7668 - rmse: 0.9543 - smape: 1.6071 - val_ia: 0.1858 - val_loss: 0.9584 - val_mae: 0.7348 - val_rmse: 0.7708 - val_smape: 1.9346

Epoch 6/64

3830/3830 - 28s - 7ms/step - ia: 0.2425 - loss: 1.0325 - mae: 0.7628 - rmse: 0.9513 - smape: 1.6017 - val_ia: 0.1862 - val_loss: 0.9567 - val_mae: 0.7330 - val_rmse: 0.7690 - val_smape: 1.9258

Epoch 7/64

3830/3830 - 41s - 11ms/step - ia: 0.2427 - loss: 1.0307 - mae: 0.7629 - rmse: 0.9484 - smape: 1.6055 - val_ia: 0.1865 - val_loss: 0.9551 - val_mae: 0.7316 - val_rmse: 0.7676 - val_smape: 1.9132

Epoch 8/64

3830/3830 - 27s - 7ms/step - ia: 0.2451 - loss: 1.0288 - mae: 0.7608 - rmse: 0.9471 - smape: 1.6034 - val_ia: 0.1866 - val_loss: 0.9537 - val_mae: 0.7307 - val_rmse: 0.7668 - val_smape: 1.9036

Epoch 9/64

3830/3830 - 42s - 11ms/step - ia: 0.2447 - loss: 1.0273 - mae: 0.7592 - rmse: 0.9454 - smape: 1.6000 - val_ia: 0.1867 - val_loss: 0.9521 - val_mae: 0.7298 - val_rmse: 0.7659 - val_smape: 1.8936

Epoch 10/64

3830/3830 - 25s - 7ms/step - ia: 0.2447 - loss: 1.0234 - mae: 0.7558 - rmse: 0.9444 - smape: 1.5913 - val_ia: 0.1868 - val_loss: 0.9506 - val_mae: 0.7292 - val_rmse: 0.7652 - val_smape: 1.8859

Epoch 11/64

3830/3830 - 40s - 10ms/step - ia: 0.2437 - loss: 1.0257 - mae: 0.7578 - rmse: 0.9457 - smape: 1.5973 - val_ia: 0.1868 - val_loss: 0.9491 - val_mae: 0.7286 - val_rmse: 0.7646 - val_smape: 1.8792

Epoch 12/64

3830/3830 - 41s - 11ms/step - ia: 0.2462 - loss: 1.0215 - mae: 0.7560 - rmse: 0.9435 - smape: 1.5949 - val_ia: 0.1868 - val_loss: 0.9474 - val_mae: 0.7280 - val_rmse: 0.7640 - val_smape: 1.8721

Epoch 13/64

3830/3830 - 44s - 12ms/step - ia: 0.2460 - loss: 1.0153 - mae: 0.7543 - rmse: 0.9414 - smape: 1.5954 - val_ia: 0.1868 - val_loss: 0.9456 - val_mae: 0.7274 - val_rmse: 0.7634 - val_smape: 1.8650

Epoch 14/64

3830/3830 - 26s - 7ms/step - ia: 0.2484 - loss: 1.0130 - mae: 0.7521 - rmse: 0.9384 - smape: 1.5901 - val_ia: 0.1868 - val_loss: 0.9438 - val_mae: 0.7267 - val_rmse: 0.7628 - val_smape: 1.8577

Epoch 15/64

3830/3830 - 29s - 7ms/step - ia: 0.2467 - loss: 1.0155 - mae: 0.7540 - rmse: 0.9415 - smape: 1.5951 - val_ia: 0.1869 - val_loss: 0.9417 - val_mae: 0.7258 - val_rmse: 0.7618 - val_smape: 1.8484

Epoch 16/64

3830/3830 - 28s - 7ms/step - ia: 0.2469 - loss: 1.0129 - mae: 0.7528 - rmse: 0.9394 - smape: 1.5910 - val_ia: 0.1869 - val_loss: 0.9396 - val_mae: 0.7250 - val_rmse: 0.7610 - val_smape: 1.8396

Epoch 17/64

3830/3830 - 25s - 7ms/step - ia: 0.2480 - loss: 1.0089 - mae: 0.7514 - rmse: 0.9386 - smape: 1.5923 - val_ia: 0.1870 - val_loss: 0.9374 - val_mae: 0.7241 - val_rmse: 0.7601 - val_smape: 1.8303

Epoch 18/64

3830/3830 - 28s - 7ms/step - ia: 0.2465 - loss: 1.0058 - mae: 0.7503 - rmse: 0.9363 - smape: 1.5894 - val_ia: 0.1871 - val_loss: 0.9349 - val_mae: 0.7232 - val_rmse: 0.7591 - val_smape: 1.8203

Epoch 19/64

3830/3830 - 41s - 11ms/step - ia: 0.2533 - loss: 0.9988 - mae: 0.7472 - rmse: 0.9335 - smape: 1.5825 - val_ia: 0.1872 - val_loss: 0.9324 - val_mae: 0.7220 - val_rmse: 0.7580 - val_smape: 1.8091

Epoch 20/64

3830/3830 - 28s - 7ms/step - ia: 0.2524 - loss: 1.0014 - mae: 0.7468 - rmse: 0.9328 - smape: 1.5812 - val_ia: 0.1873 - val_loss: 0.9298 - val_mae: 0.7211 - val_rmse: 0.7571 - val_smape: 1.8000

Epoch 21/64

3830/3830 - 41s - 11ms/step - ia: 0.2515 - loss: 0.9956 - mae: 0.7458 - rmse: 0.9314 - smape: 1.5816 - val_ia: 0.1873 - val_loss: 0.9272 - val_mae: 0.7204 - val_rmse: 0.7563 - val_smape: 1.7912

Epoch 22/64

3830/3830 - 44s - 11ms/step - ia: 0.2491 - loss: 0.9953 - mae: 0.7464 - rmse: 0.9323 - smape: 1.5815 - val_ia: 0.1875 - val_loss: 0.9243 - val_mae: 0.7192 - val_rmse: 0.7551 - val_smape: 1.7799

Epoch 23/64

3830/3830 - 33s - 9ms/step - ia: 0.2558 - loss: 0.9915 - mae: 0.7437 - rmse: 0.9292 - smape: 1.5767 - val_ia: 0.1877 - val_loss: 0.9213 - val_mae: 0.7180 - val_rmse: 0.7539 - val_smape: 1.7685

Epoch 24/64

3830/3830 - 26s - 7ms/step - ia: 0.2569 - loss: 0.9844 - mae: 0.7405 - rmse: 0.9246 - smape: 1.5698 - val_ia: 0.1878 - val_loss: 0.9183 - val_mae: 0.7170 - val_rmse: 0.7529 - val_smape: 1.7583

Epoch 25/64

3830/3830 - 43s - 11ms/step - ia: 0.2579 - loss: 0.9837 - mae: 0.7406 - rmse: 0.9264 - smape: 1.5678 - val_ia: 0.1880 - val_loss: 0.9149 - val_mae: 0.7154 - val_rmse: 0.7514 - val_smape: 1.7453

Epoch 26/64

3830/3830 - 28s - 7ms/step - ia: 0.2590 - loss: 0.9767 - mae: 0.7389 - rmse: 0.9224 - smape: 1.5668 - val_ia: 0.1881 - val_loss: 0.9116 - val_mae: 0.7142 - val_rmse: 0.7502 - val_smape: 1.7341

Epoch 27/64

3830/3830 - 27s - 7ms/step - ia: 0.2620 - loss: 0.9745 - mae: 0.7364 - rmse: 0.9209 - smape: 1.5571 - val_ia: 0.1882 - val_loss: 0.9082 - val_mae: 0.7130 - val_rmse: 0.7490 - val_smape: 1.7230

Epoch 28/64

3830/3830 - 26s - 7ms/step - ia: 0.2656 - loss: 0.9688 - mae: 0.7346 - rmse: 0.9184 - smape: 1.5527 - val_ia: 0.1884 - val_loss: 0.9047 - val_mae: 0.7118 - val_rmse: 0.7478 - val_smape: 1.7117

Epoch 29/64

3830/3830 - 27s - 7ms/step - ia: 0.2638 - loss: 0.9693 - mae: 0.7347 - rmse: 0.9197 - smape: 1.5509 - val_ia: 0.1886 - val_loss: 0.9010 - val_mae: 0.7103 - val_rmse: 0.7463 - val_smape: 1.6990

Epoch 30/64

3830/3830 - 42s - 11ms/step - ia: 0.2670 - loss: 0.9663 - mae: 0.7326 - rmse: 0.9172 - smape: 1.5440 - val_ia: 0.1887 - val_loss: 0.8974 - val_mae: 0.7091 - val_rmse: 0.7451 - val_smape: 1.6877

Epoch 31/64

3830/3830 - 26s - 7ms/step - ia: 0.2667 - loss: 0.9620 - mae: 0.7335 - rmse: 0.9162 - smape: 1.5478 - val_ia: 0.1889 - val_loss: 0.8935 - val_mae: 0.7076 - val_rmse: 0.7436 - val_smape: 1.6749

Epoch 32/64

3830/3830 - 28s - 7ms/step - ia: 0.2710 - loss: 0.9595 - mae: 0.7307 - rmse: 0.9154 - smape: 1.5363 - val_ia: 0.1892 - val_loss: 0.8895 - val_mae: 0.7058 - val_rmse: 0.7418 - val_smape: 1.6609

Epoch 33/64

3830/3830 - 26s - 7ms/step - ia: 0.2703 - loss: 0.9537 - mae: 0.7293 - rmse: 0.9120 - smape: 1.5309 - val_ia: 0.1894 - val_loss: 0.8855 - val_mae: 0.7039 - val_rmse: 0.7400 - val_smape: 1.6466

Epoch 34/64

3830/3830 - 44s - 11ms/step - ia: 0.2739 - loss: 0.9497 - mae: 0.7271 - rmse: 0.9101 - smape: 1.5223 - val_ia: 0.1896 - val_loss: 0.8816 - val_mae: 0.7027 - val_rmse: 0.7388 - val_smape: 1.6353

Epoch 35/64

3830/3830 - 30s - 8ms/step - ia: 0.2775 - loss: 0.9446 - mae: 0.7252 - rmse: 0.9087 - smape: 1.5188 - val_ia: 0.1898 - val_loss: 0.8775 - val_mae: 0.7009 - val_rmse: 0.7370 - val_smape: 1.6216

Epoch 36/64

3830/3830 - 38s - 10ms/step - ia: 0.2799 - loss: 0.9405 - mae: 0.7237 - rmse: 0.9057 - smape: 1.5119 - val_ia: 0.1900 - val_loss: 0.8735 - val_mae: 0.6991 - val_rmse: 0.7354 - val_smape: 1.6084

Epoch 37/64

3830/3830 - 41s - 11ms/step - ia: 0.2789 - loss: 0.9430 - mae: 0.7244 - rmse: 0.9079 - smape: 1.5098 - val_ia: 0.1902 - val_loss: 0.8696 - val_mae: 0.6976 - val_rmse: 0.7338 - val_smape: 1.5960

Epoch 38/64

3830/3830 - 26s - 7ms/step - ia: 0.2832 - loss: 0.9375 - mae: 0.7220 - rmse: 0.9050 - smape: 1.4979 - val_ia: 0.1904 - val_loss: 0.8654 - val_mae: 0.6955 - val_rmse: 0.7319 - val_smape: 1.5818

Epoch 39/64

3830/3830 - 26s - 7ms/step - ia: 0.2876 - loss: 0.9328 - mae: 0.7198 - rmse: 0.9019 - smape: 1.4913 - val_ia: 0.1906 - val_loss: 0.8616 - val_mae: 0.6942 - val_rmse: 0.7306 - val_smape: 1.5707

Epoch 40/64

3830/3830 - 25s - 7ms/step - ia: 0.2894 - loss: 0.9311 - mae: 0.7192 - rmse: 0.9012 - smape: 1.4886 - val_ia: 0.1909 - val_loss: 0.8577 - val_mae: 0.6923 - val_rmse: 0.7288 - val_smape: 1.5572

Epoch 41/64

3830/3830 - 26s - 7ms/step - ia: 0.2930 - loss: 0.9239 - mae: 0.7161 - rmse: 0.8981 - smape: 1.4783 - val_ia: 0.1912 - val_loss: 0.8539 - val_mae: 0.6908 - val_rmse: 0.7274 - val_smape: 1.5457

Epoch 42/64

3830/3830 - 24s - 6ms/step - ia: 0.2958 - loss: 0.9192 - mae: 0.7145 - rmse: 0.8972 - smape: 1.4691 - val_ia: 0.1916 - val_loss: 0.8501 - val_mae: 0.6890 - val_rmse: 0.7256 - val_smape: 1.5331

Epoch 43/64

3830/3830 - 25s - 7ms/step - ia: 0.2996 - loss: 0.9183 - mae: 0.7127 - rmse: 0.8947 - smape: 1.4624 - val_ia: 0.1920 - val_loss: 0.8463 - val_mae: 0.6873 - val_rmse: 0.7240 - val_smape: 1.5207

Epoch 44/64

3830/3830 - 42s - 11ms/step - ia: 0.3003 - loss: 0.9159 - mae: 0.7123 - rmse: 0.8945 - smape: 1.4565 - val_ia: 0.1923 - val_loss: 0.8428 - val_mae: 0.6860 - val_rmse: 0.7227 - val_smape: 1.5102

Epoch 45/64

3830/3830 - 41s - 11ms/step - ia: 0.3038 - loss: 0.9131 - mae: 0.7118 - rmse: 0.8934 - smape: 1.4514 - val_ia: 0.1927 - val_loss: 0.8394 - val_mae: 0.6843 - val_rmse: 0.7212 - val_smape: 1.4989

Epoch 46/64

3830/3830 - 26s - 7ms/step - ia: 0.3055 - loss: 0.9146 - mae: 0.7117 - rmse: 0.8944 - smape: 1.4460 - val_ia: 0.1931 - val_loss: 0.8361 - val_mae: 0.6828 - val_rmse: 0.7198 - val_smape: 1.4882

Epoch 47/64

3830/3830 - 28s - 7ms/step - ia: 0.3080 - loss: 0.9080 - mae: 0.7091 - rmse: 0.8926 - smape: 1.4389 - val_ia: 0.1934 - val_loss: 0.8328 - val_mae: 0.6812 - val_rmse: 0.7182 - val_smape: 1.4772

Epoch 48/64

3830/3830 - 38s - 10ms/step - ia: 0.3127 - loss: 0.9064 - mae: 0.7079 - rmse: 0.8907 - smape: 1.4295 - val_ia: 0.1938 - val_loss: 0.8298 - val_mae: 0.6796 - val_rmse: 0.7168 - val_smape: 1.4668

Epoch 49/64

3830/3830 - 41s - 11ms/step - ia: 0.3138 - loss: 0.9039 - mae: 0.7076 - rmse: 0.8892 - smape: 1.4277 - val_ia: 0.1942 - val_loss: 0.8269 - val_mae: 0.6782 - val_rmse: 0.7155 - val_smape: 1.4570

Epoch 50/64

3830/3830 - 26s - 7ms/step - ia: 0.3138 - loss: 0.9016 - mae: 0.7071 - rmse: 0.8900 - smape: 1.4245 - val_ia: 0.1945 - val_loss: 0.8243 - val_mae: 0.6771 - val_rmse: 0.7145 - val_smape: 1.4487

Epoch 51/64

3830/3830 - 26s - 7ms/step - ia: 0.3177 - loss: 0.9017 - mae: 0.7060 - rmse: 0.8887 - smape: 1.4181 - val_ia: 0.1950 - val_loss: 0.8216 - val_mae: 0.6755 - val_rmse: 0.7131 - val_smape: 1.4390

Epoch 52/64

3830/3830 - 41s - 11ms/step - ia: 0.3220 - loss: 0.8964 - mae: 0.7028 - rmse: 0.8858 - smape: 1.4066 - val_ia: 0.1952 - val_loss: 0.8191 - val_mae: 0.6745 - val_rmse: 0.7121 - val_smape: 1.4310

Epoch 53/64

3830/3830 - 40s - 11ms/step - ia: 0.3195 - loss: 0.8975 - mae: 0.7058 - rmse: 0.8874 - smape: 1.4099 - val_ia: 0.1954 - val_loss: 0.8168 - val_mae: 0.6734 - val_rmse: 0.7111 - val_smape: 1.4232

Epoch 54/64

3830/3830 - 43s - 11ms/step - ia: 0.3251 - loss: 0.8922 - mae: 0.7025 - rmse: 0.8839 - smape: 1.4006 - val_ia: 0.1955 - val_loss: 0.8146 - val_mae: 0.6724 - val_rmse: 0.7102 - val_smape: 1.4158

Epoch 55/64

3830/3830 - 25s - 7ms/step - ia: 0.3257 - loss: 0.8921 - mae: 0.7033 - rmse: 0.8846 - smape: 1.4018 - val_ia: 0.1959 - val_loss: 0.8125 - val_mae: 0.6710 - val_rmse: 0.7089 - val_smape: 1.4074

Epoch 56/64

3830/3830 - 26s - 7ms/step - ia: 0.3297 - loss: 0.8896 - mae: 0.7004 - rmse: 0.8836 - smape: 1.3913 - val_ia: 0.1961 - val_loss: 0.8106 - val_mae: 0.6701 - val_rmse: 0.7082 - val_smape: 1.4010

Epoch 57/64

3830/3830 - 27s - 7ms/step - ia: 0.3289 - loss: 0.8895 - mae: 0.7024 - rmse: 0.8831 - smape: 1.3945 - val_ia: 0.1964 - val_loss: 0.8088 - val_mae: 0.6692 - val_rmse: 0.7074 - val_smape: 1.3945

Epoch 58/64

3830/3830 - 29s - 8ms/step - ia: 0.3322 - loss: 0.8865 - mae: 0.6993 - rmse: 0.8813 - smape: 1.3821 - val_ia: 0.1967 - val_loss: 0.8072 - val_mae: 0.6683 - val_rmse: 0.7066 - val_smape: 1.3885

Epoch 59/64

3830/3830 - 26s - 7ms/step - ia: 0.3320 - loss: 0.8882 - mae: 0.7001 - rmse: 0.8840 - smape: 1.3823 - val_ia: 0.1968 - val_loss: 0.8057 - val_mae: 0.6679 - val_rmse: 0.7063 - val_smape: 1.3839

Epoch 60/64

3830/3830 - 30s - 8ms/step - ia: 0.3360 - loss: 0.8886 - mae: 0.7012 - rmse: 0.8837 - smape: 1.3797 - val_ia: 0.1971 - val_loss: 0.8041 - val_mae: 0.6666 - val_rmse: 0.7051 - val_smape: 1.3768

Epoch 61/64

3830/3830 - 28s - 7ms/step - ia: 0.3370 - loss: 0.8837 - mae: 0.6985 - rmse: 0.8807 - smape: 1.3744 - val_ia: 0.1974 - val_loss: 0.8027 - val_mae: 0.6657 - val_rmse: 0.7043 - val_smape: 1.3711

Epoch 62/64

3830/3830 - 30s - 8ms/step - ia: 0.3388 - loss: 0.8821 - mae: 0.6980 - rmse: 0.8815 - smape: 1.3703 - val_ia: 0.1978 - val_loss: 0.8014 - val_mae: 0.6649 - val_rmse: 0.7036 - val_smape: 1.3661

Epoch 63/64

3830/3830 - 25s - 7ms/step - ia: 0.3395 - loss: 0.8820 - mae: 0.6984 - rmse: 0.8807 - smape: 1.3709 - val_ia: 0.1980 - val_loss: 0.8004 - val_mae: 0.6645 - val_rmse: 0.7033 - val_smape: 1.3623

Epoch 64/64

3830/3830 - 25s - 7ms/step - ia: 0.3397 - loss: 0.8858 - mae: 0.6992 - rmse: 0.8822 - smape: 1.3662 - val_ia: 0.1983 - val_loss: 0.7993 - val_mae: 0.6638 - val_rmse: 0.7027 - val_smape: 1.3579

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:50 1s/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 10%|█         | 5/50 [1:02:45<12:05:27, 967.27s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 19s - 19ms/step - ia: 0.1959 - loss: 0.9881 - mae: 0.7520 - rmse: 0.9733 - smape: 1.6241 - val_ia: 0.2403 - val_loss: 0.8683 - val_mae: 0.6981 - val_rmse: 0.7809 - val_smape: 1.5345

Epoch 2/128

958/958 - 18s - 19ms/step - ia: 0.2623 - loss: 0.9093 - mae: 0.7150 - rmse: 0.9355 - smape: 1.4963 - val_ia: 0.2447 - val_loss: 0.8303 - val_mae: 0.6789 - val_rmse: 0.7638 - val_smape: 1.4154

Epoch 3/128

958/958 - 10s - 11ms/step - ia: 0.3051 - loss: 0.8829 - mae: 0.7016 - rmse: 0.9209 - smape: 1.4237 - val_ia: 0.2468 - val_loss: 0.8159 - val_mae: 0.6705 - val_rmse: 0.7575 - val_smape: 1.3666

Epoch 4/128

958/958 - 21s - 22ms/step - ia: 0.3220 - loss: 0.8754 - mae: 0.6977 - rmse: 0.9185 - smape: 1.3970 - val_ia: 0.2478 - val_loss: 0.8089 - val_mae: 0.6670 - val_rmse: 0.7549 - val_smape: 1.3495

Epoch 5/128

958/958 - 21s - 22ms/step - ia: 0.3283 - loss: 0.8710 - mae: 0.6945 - rmse: 0.9153 - smape: 1.3854 - val_ia: 0.2491 - val_loss: 0.8026 - val_mae: 0.6639 - val_rmse: 0.7527 - val_smape: 1.3352

Epoch 6/128

958/958 - 19s - 20ms/step - ia: 0.3342 - loss: 0.8649 - mae: 0.6924 - rmse: 0.9127 - smape: 1.3742 - val_ia: 0.2499 - val_loss: 0.7982 - val_mae: 0.6621 - val_rmse: 0.7513 - val_smape: 1.3283

Epoch 7/128

958/958 - 9s - 10ms/step - ia: 0.3382 - loss: 0.8633 - mae: 0.6919 - rmse: 0.9109 - smape: 1.3697 - val_ia: 0.2500 - val_loss: 0.7960 - val_mae: 0.6617 - val_rmse: 0.7511 - val_smape: 1.3296

Epoch 8/128

958/958 - 9s - 10ms/step - ia: 0.3394 - loss: 0.8620 - mae: 0.6901 - rmse: 0.9105 - smape: 1.3665 - val_ia: 0.2500 - val_loss: 0.7941 - val_mae: 0.6613 - val_rmse: 0.7507 - val_smape: 1.3320

Epoch 9/128

958/958 - 8s - 9ms/step - ia: 0.3429 - loss: 0.8561 - mae: 0.6878 - rmse: 0.9077 - smape: 1.3626 - val_ia: 0.2505 - val_loss: 0.7909 - val_mae: 0.6600 - val_rmse: 0.7496 - val_smape: 1.3279

Epoch 10/128

958/958 - 11s - 11ms/step - ia: 0.3457 - loss: 0.8537 - mae: 0.6872 - rmse: 0.9061 - smape: 1.3574 - val_ia: 0.2505 - val_loss: 0.7897 - val_mae: 0.6598 - val_rmse: 0.7495 - val_smape: 1.3280

Epoch 11/128

958/958 - 19s - 19ms/step - ia: 0.3491 - loss: 0.8518 - mae: 0.6854 - rmse: 0.9051 - smape: 1.3522 - val_ia: 0.2505 - val_loss: 0.7882 - val_mae: 0.6594 - val_rmse: 0.7492 - val_smape: 1.3284

Epoch 12/128

958/958 - 8s - 8ms/step - ia: 0.3505 - loss: 0.8469 - mae: 0.6832 - rmse: 0.9019 - smape: 1.3539 - val_ia: 0.2508 - val_loss: 0.7862 - val_mae: 0.6586 - val_rmse: 0.7485 - val_smape: 1.3251

Epoch 13/128

958/958 - 9s - 10ms/step - ia: 0.3521 - loss: 0.8457 - mae: 0.6827 - rmse: 0.9019 - smape: 1.3498 - val_ia: 0.2509 - val_loss: 0.7850 - val_mae: 0.6579 - val_rmse: 0.7480 - val_smape: 1.3221

Epoch 14/128

958/958 - 10s - 11ms/step - ia: 0.3532 - loss: 0.8493 - mae: 0.6833 - rmse: 0.9039 - smape: 1.3464 - val_ia: 0.2508 - val_loss: 0.7838 - val_mae: 0.6580 - val_rmse: 0.7480 - val_smape: 1.3256

Epoch 15/128

958/958 - 10s - 11ms/step - ia: 0.3526 - loss: 0.8455 - mae: 0.6822 - rmse: 0.9018 - smape: 1.3477 - val_ia: 0.2510 - val_loss: 0.7823 - val_mae: 0.6574 - val_rmse: 0.7475 - val_smape: 1.3235

Epoch 16/128

958/958 - 10s - 10ms/step - ia: 0.3530 - loss: 0.8451 - mae: 0.6819 - rmse: 0.9020 - smape: 1.3467 - val_ia: 0.2511 - val_loss: 0.7810 - val_mae: 0.6570 - val_rmse: 0.7471 - val_smape: 1.3223

Epoch 17/128

958/958 - 11s - 11ms/step - ia: 0.3545 - loss: 0.8419 - mae: 0.6802 - rmse: 0.8985 - smape: 1.3435 - val_ia: 0.2512 - val_loss: 0.7801 - val_mae: 0.6562 - val_rmse: 0.7466 - val_smape: 1.3184

Epoch 18/128

958/958 - 10s - 10ms/step - ia: 0.3562 - loss: 0.8381 - mae: 0.6792 - rmse: 0.8986 - smape: 1.3410 - val_ia: 0.2513 - val_loss: 0.7788 - val_mae: 0.6557 - val_rmse: 0.7462 - val_smape: 1.3176

Epoch 19/128

958/958 - 11s - 11ms/step - ia: 0.3584 - loss: 0.8396 - mae: 0.6787 - rmse: 0.8984 - smape: 1.3371 - val_ia: 0.2513 - val_loss: 0.7778 - val_mae: 0.6555 - val_rmse: 0.7460 - val_smape: 1.3185

Epoch 20/128

958/958 - 10s - 11ms/step - ia: 0.3595 - loss: 0.8361 - mae: 0.6781 - rmse: 0.8961 - smape: 1.3381 - val_ia: 0.2513 - val_loss: 0.7769 - val_mae: 0.6553 - val_rmse: 0.7458 - val_smape: 1.3188

Epoch 21/128

958/958 - 9s - 10ms/step - ia: 0.3590 - loss: 0.8343 - mae: 0.6771 - rmse: 0.8950 - smape: 1.3375 - val_ia: 0.2514 - val_loss: 0.7764 - val_mae: 0.6550 - val_rmse: 0.7456 - val_smape: 1.3171

Epoch 22/128

958/958 - 8s - 8ms/step - ia: 0.3582 - loss: 0.8359 - mae: 0.6780 - rmse: 0.8963 - smape: 1.3366 - val_ia: 0.2514 - val_loss: 0.7753 - val_mae: 0.6546 - val_rmse: 0.7452 - val_smape: 1.3180

Epoch 23/128

958/958 - 13s - 13ms/step - ia: 0.3594 - loss: 0.8361 - mae: 0.6779 - rmse: 0.8968 - smape: 1.3374 - val_ia: 0.2515 - val_loss: 0.7739 - val_mae: 0.6541 - val_rmse: 0.7446 - val_smape: 1.3180

Epoch 24/128

958/958 - 10s - 11ms/step - ia: 0.3617 - loss: 0.8343 - mae: 0.6760 - rmse: 0.8948 - smape: 1.3349 - val_ia: 0.2517 - val_loss: 0.7733 - val_mae: 0.6538 - val_rmse: 0.7445 - val_smape: 1.3159

Epoch 25/128

958/958 - 10s - 10ms/step - ia: 0.3617 - loss: 0.8327 - mae: 0.6753 - rmse: 0.8946 - smape: 1.3335 - val_ia: 0.2517 - val_loss: 0.7732 - val_mae: 0.6536 - val_rmse: 0.7446 - val_smape: 1.3150

Epoch 26/128

958/958 - 11s - 11ms/step - ia: 0.3628 - loss: 0.8331 - mae: 0.6761 - rmse: 0.8945 - smape: 1.3313 - val_ia: 0.2517 - val_loss: 0.7726 - val_mae: 0.6536 - val_rmse: 0.7445 - val_smape: 1.3163

Epoch 27/128

958/958 - 10s - 11ms/step - ia: 0.3642 - loss: 0.8299 - mae: 0.6738 - rmse: 0.8936 - smape: 1.3272 - val_ia: 0.2519 - val_loss: 0.7713 - val_mae: 0.6530 - val_rmse: 0.7439 - val_smape: 1.3140

Epoch 28/128

958/958 - 10s - 11ms/step - ia: 0.3658 - loss: 0.8301 - mae: 0.6733 - rmse: 0.8930 - smape: 1.3258 - val_ia: 0.2521 - val_loss: 0.7704 - val_mae: 0.6526 - val_rmse: 0.7436 - val_smape: 1.3135

Epoch 29/128

958/958 - 10s - 11ms/step - ia: 0.3670 - loss: 0.8281 - mae: 0.6730 - rmse: 0.8914 - smape: 1.3255 - val_ia: 0.2522 - val_loss: 0.7702 - val_mae: 0.6523 - val_rmse: 0.7436 - val_smape: 1.3100

Epoch 30/128

958/958 - 11s - 11ms/step - ia: 0.3648 - loss: 0.8275 - mae: 0.6728 - rmse: 0.8921 - smape: 1.3262 - val_ia: 0.2523 - val_loss: 0.7692 - val_mae: 0.6519 - val_rmse: 0.7433 - val_smape: 1.3103

Epoch 31/128

958/958 - 10s - 10ms/step - ia: 0.3655 - loss: 0.8297 - mae: 0.6735 - rmse: 0.8928 - smape: 1.3280 - val_ia: 0.2524 - val_loss: 0.7682 - val_mae: 0.6516 - val_rmse: 0.7430 - val_smape: 1.3093

Epoch 32/128

958/958 - 10s - 11ms/step - ia: 0.3668 - loss: 0.8292 - mae: 0.6730 - rmse: 0.8922 - smape: 1.3249 - val_ia: 0.2524 - val_loss: 0.7676 - val_mae: 0.6513 - val_rmse: 0.7427 - val_smape: 1.3094

Epoch 33/128

958/958 - 10s - 10ms/step - ia: 0.3685 - loss: 0.8250 - mae: 0.6714 - rmse: 0.8910 - smape: 1.3225 - val_ia: 0.2526 - val_loss: 0.7663 - val_mae: 0.6507 - val_rmse: 0.7422 - val_smape: 1.3073

Epoch 34/128

958/958 - 9s - 9ms/step - ia: 0.3692 - loss: 0.8250 - mae: 0.6715 - rmse: 0.8912 - smape: 1.3221 - val_ia: 0.2526 - val_loss: 0.7664 - val_mae: 0.6505 - val_rmse: 0.7422 - val_smape: 1.3062

Epoch 35/128

958/958 - 9s - 9ms/step - ia: 0.3690 - loss: 0.8251 - mae: 0.6711 - rmse: 0.8893 - smape: 1.3231 - val_ia: 0.2528 - val_loss: 0.7656 - val_mae: 0.6505 - val_rmse: 0.7422 - val_smape: 1.3063

Epoch 36/128

958/958 - 8s - 8ms/step - ia: 0.3694 - loss: 0.8229 - mae: 0.6707 - rmse: 0.8905 - smape: 1.3190 - val_ia: 0.2529 - val_loss: 0.7657 - val_mae: 0.6505 - val_rmse: 0.7422 - val_smape: 1.3060

Epoch 37/128

958/958 - 12s - 12ms/step - ia: 0.3724 - loss: 0.8209 - mae: 0.6692 - rmse: 0.8874 - smape: 1.3176 - val_ia: 0.2529 - val_loss: 0.7656 - val_mae: 0.6507 - val_rmse: 0.7425 - val_smape: 1.3085

Epoch 38/128

958/958 - 11s - 12ms/step - ia: 0.3709 - loss: 0.8212 - mae: 0.6691 - rmse: 0.8894 - smape: 1.3174 - val_ia: 0.2531 - val_loss: 0.7656 - val_mae: 0.6504 - val_rmse: 0.7424 - val_smape: 1.3045

Epoch 39/128

958/958 - 10s - 10ms/step - ia: 0.3730 - loss: 0.8206 - mae: 0.6691 - rmse: 0.8889 - smape: 1.3155 - val_ia: 0.2532 - val_loss: 0.7648 - val_mae: 0.6500 - val_rmse: 0.7421 - val_smape: 1.3040

Epoch 40/128

958/958 - 9s - 10ms/step - ia: 0.3735 - loss: 0.8207 - mae: 0.6691 - rmse: 0.8878 - smape: 1.3143 - val_ia: 0.2533 - val_loss: 0.7640 - val_mae: 0.6497 - val_rmse: 0.7418 - val_smape: 1.3036

Epoch 41/128

958/958 - 10s - 10ms/step - ia: 0.3712 - loss: 0.8225 - mae: 0.6701 - rmse: 0.8895 - smape: 1.3175 - val_ia: 0.2534 - val_loss: 0.7636 - val_mae: 0.6495 - val_rmse: 0.7417 - val_smape: 1.3033

Epoch 42/128

958/958 - 9s - 10ms/step - ia: 0.3761 - loss: 0.8208 - mae: 0.6681 - rmse: 0.8879 - smape: 1.3116 - val_ia: 0.2536 - val_loss: 0.7630 - val_mae: 0.6496 - val_rmse: 0.7416 - val_smape: 1.3057

Epoch 43/128

958/958 - 9s - 9ms/step - ia: 0.3755 - loss: 0.8165 - mae: 0.6661 - rmse: 0.8852 - smape: 1.3116 - val_ia: 0.2537 - val_loss: 0.7630 - val_mae: 0.6493 - val_rmse: 0.7415 - val_smape: 1.3025

Epoch 44/128

958/958 - 9s - 9ms/step - ia: 0.3740 - loss: 0.8188 - mae: 0.6672 - rmse: 0.8876 - smape: 1.3120 - val_ia: 0.2538 - val_loss: 0.7631 - val_mae: 0.6489 - val_rmse: 0.7413 - val_smape: 1.3001

Epoch 45/128

958/958 - 12s - 13ms/step - ia: 0.3743 - loss: 0.8172 - mae: 0.6668 - rmse: 0.8863 - smape: 1.3120 - val_ia: 0.2539 - val_loss: 0.7638 - val_mae: 0.6490 - val_rmse: 0.7416 - val_smape: 1.2986

Epoch 46/128

958/958 - 10s - 10ms/step - ia: 0.3763 - loss: 0.8165 - mae: 0.6667 - rmse: 0.8851 - smape: 1.3111 - val_ia: 0.2540 - val_loss: 0.7627 - val_mae: 0.6485 - val_rmse: 0.7412 - val_smape: 1.2977

Epoch 47/128

958/958 - 8s - 8ms/step - ia: 0.3772 - loss: 0.8164 - mae: 0.6666 - rmse: 0.8868 - smape: 1.3087 - val_ia: 0.2542 - val_loss: 0.7627 - val_mae: 0.6485 - val_rmse: 0.7413 - val_smape: 1.2973

Epoch 48/128

958/958 - 8s - 8ms/step - ia: 0.3777 - loss: 0.8160 - mae: 0.6659 - rmse: 0.8855 - smape: 1.3085 - val_ia: 0.2542 - val_loss: 0.7627 - val_mae: 0.6485 - val_rmse: 0.7413 - val_smape: 1.2966

Epoch 49/128

958/958 - 12s - 12ms/step - ia: 0.3796 - loss: 0.8125 - mae: 0.6650 - rmse: 0.8837 - smape: 1.3057 - val_ia: 0.2544 - val_loss: 0.7623 - val_mae: 0.6482 - val_rmse: 0.7411 - val_smape: 1.2961

Epoch 50/128

958/958 - 11s - 12ms/step - ia: 0.3795 - loss: 0.8140 - mae: 0.6647 - rmse: 0.8849 - smape: 1.3046 - val_ia: 0.2545 - val_loss: 0.7610 - val_mae: 0.6481 - val_rmse: 0.7408 - val_smape: 1.2984

Epoch 51/128

958/958 - 13s - 13ms/step - ia: 0.3774 - loss: 0.8155 - mae: 0.6656 - rmse: 0.8846 - smape: 1.3067 - val_ia: 0.2547 - val_loss: 0.7613 - val_mae: 0.6477 - val_rmse: 0.7407 - val_smape: 1.2941

Epoch 52/128

958/958 - 21s - 22ms/step - ia: 0.3802 - loss: 0.8137 - mae: 0.6647 - rmse: 0.8841 - smape: 1.3043 - val_ia: 0.2548 - val_loss: 0.7604 - val_mae: 0.6476 - val_rmse: 0.7406 - val_smape: 1.2951

Epoch 53/128

958/958 - 20s - 21ms/step - ia: 0.3797 - loss: 0.8161 - mae: 0.6649 - rmse: 0.8857 - smape: 1.3048 - val_ia: 0.2549 - val_loss: 0.7613 - val_mae: 0.6480 - val_rmse: 0.7413 - val_smape: 1.2947

Epoch 54/128

958/958 - 12s - 13ms/step - ia: 0.3817 - loss: 0.8114 - mae: 0.6642 - rmse: 0.8845 - smape: 1.3011 - val_ia: 0.2551 - val_loss: 0.7602 - val_mae: 0.6474 - val_rmse: 0.7406 - val_smape: 1.2922

Epoch 55/128

958/958 - 23s - 24ms/step - ia: 0.3809 - loss: 0.8110 - mae: 0.6644 - rmse: 0.8835 - smape: 1.3021 - val_ia: 0.2551 - val_loss: 0.7595 - val_mae: 0.6471 - val_rmse: 0.7403 - val_smape: 1.2928

Epoch 56/128

958/958 - 24s - 25ms/step - ia: 0.3830 - loss: 0.8111 - mae: 0.6632 - rmse: 0.8819 - smape: 1.3001 - val_ia: 0.2553 - val_loss: 0.7606 - val_mae: 0.6473 - val_rmse: 0.7407 - val_smape: 1.2911

Epoch 57/128

958/958 - 13s - 14ms/step - ia: 0.3843 - loss: 0.8151 - mae: 0.6642 - rmse: 0.8853 - smape: 1.2993 - val_ia: 0.2553 - val_loss: 0.7611 - val_mae: 0.6477 - val_rmse: 0.7410 - val_smape: 1.2930

Epoch 58/128

958/958 - 13s - 13ms/step - ia: 0.3833 - loss: 0.8099 - mae: 0.6630 - rmse: 0.8825 - smape: 1.2984 - val_ia: 0.2555 - val_loss: 0.7609 - val_mae: 0.6473 - val_rmse: 0.7407 - val_smape: 1.2909

Epoch 59/128

958/958 - 20s - 21ms/step - ia: 0.3834 - loss: 0.8133 - mae: 0.6627 - rmse: 0.8843 - smape: 1.2974 - val_ia: 0.2555 - val_loss: 0.7607 - val_mae: 0.6471 - val_rmse: 0.7406 - val_smape: 1.2898

Epoch 60/128

958/958 - 12s - 12ms/step - ia: 0.3844 - loss: 0.8092 - mae: 0.6628 - rmse: 0.8808 - smape: 1.2989 - val_ia: 0.2556 - val_loss: 0.7616 - val_mae: 0.6474 - val_rmse: 0.7409 - val_smape: 1.2902

Epoch 61/128

958/958 - 20s - 21ms/step - ia: 0.3831 - loss: 0.8121 - mae: 0.6631 - rmse: 0.8835 - smape: 1.2982 - val_ia: 0.2556 - val_loss: 0.7627 - val_mae: 0.6475 - val_rmse: 0.7412 - val_smape: 1.2878

Epoch 62/128

958/958 - 12s - 13ms/step - ia: 0.3855 - loss: 0.8067 - mae: 0.6618 - rmse: 0.8805 - smape: 1.2936 - val_ia: 0.2559 - val_loss: 0.7605 - val_mae: 0.6466 - val_rmse: 0.7402 - val_smape: 1.2863

Epoch 63/128

958/958 - 9s - 9ms/step - ia: 0.3853 - loss: 0.8072 - mae: 0.6617 - rmse: 0.8802 - smape: 1.2974 - val_ia: 0.2558 - val_loss: 0.7626 - val_mae: 0.6473 - val_rmse: 0.7411 - val_smape: 1.2860

Epoch 64/128

958/958 - 8s - 9ms/step - ia: 0.3869 - loss: 0.8072 - mae: 0.6622 - rmse: 0.8813 - smape: 1.2950 - val_ia: 0.2561 - val_loss: 0.7609 - val_mae: 0.6468 - val_rmse: 0.7405 - val_smape: 1.2861

Epoch 65/128

958/958 - 10s - 10ms/step - ia: 0.3865 - loss: 0.8072 - mae: 0.6606 - rmse: 0.8801 - smape: 1.2937 - val_ia: 0.2559 - val_loss: 0.7620 - val_mae: 0.6470 - val_rmse: 0.7409 - val_smape: 1.2852

Epoch 66/128

958/958 - 13s - 13ms/step - ia: 0.3857 - loss: 0.8071 - mae: 0.6616 - rmse: 0.8807 - smape: 1.2927 - val_ia: 0.2561 - val_loss: 0.7625 - val_mae: 0.6470 - val_rmse: 0.7411 - val_smape: 1.2835

Epoch 67/128

958/958 - 12s - 13ms/step - ia: 0.3884 - loss: 0.8033 - mae: 0.6601 - rmse: 0.8786 - smape: 1.2916 - val_ia: 0.2564 - val_loss: 0.7624 - val_mae: 0.6471 - val_rmse: 0.7412 - val_smape: 1.2841

Epoch 68/128

958/958 - 12s - 13ms/step - ia: 0.3874 - loss: 0.8078 - mae: 0.6611 - rmse: 0.8801 - smape: 1.2914 - val_ia: 0.2565 - val_loss: 0.7604 - val_mae: 0.6463 - val_rmse: 0.7403 - val_smape: 1.2825

Epoch 69/128

958/958 - 12s - 13ms/step - ia: 0.3880 - loss: 0.8071 - mae: 0.6604 - rmse: 0.8789 - smape: 1.2895 - val_ia: 0.2566 - val_loss: 0.7610 - val_mae: 0.6462 - val_rmse: 0.7403 - val_smape: 1.2813

Epoch 70/128

958/958 - 21s - 22ms/step - ia: 0.3886 - loss: 0.8056 - mae: 0.6606 - rmse: 0.8805 - smape: 1.2909 - val_ia: 0.2566 - val_loss: 0.7610 - val_mae: 0.6461 - val_rmse: 0.7401 - val_smape: 1.2815

Epoch 70: early stopping

Restoring model weights from the end of the best epoch: 55.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:39 1s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 12%|█▏        | 6/50 [1:16:59<11:21:16, 929.01s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 16s - 133ms/step - ia: 0.3752 - loss: 0.8234 - mae: 0.6649 - rmse: 0.9050 - smape: 1.3020 - val_ia: 0.3638 - val_loss: 0.7611 - val_mae: 0.6406 - val_rmse: 0.8078 - val_smape: 1.2453

Epoch 2/128

120/120 - 2s - 16ms/step - ia: 0.4065 - loss: 0.7961 - mae: 0.6508 - rmse: 0.8899 - smape: 1.2518 - val_ia: 0.3487 - val_loss: 0.7539 - val_mae: 0.6423 - val_rmse: 0.8039 - val_smape: 1.2670

Epoch 3/128

120/120 - 2s - 16ms/step - ia: 0.4154 - loss: 0.7803 - mae: 0.6444 - rmse: 0.8804 - smape: 1.2429 - val_ia: 0.3370 - val_loss: 0.7488 - val_mae: 0.6378 - val_rmse: 0.7981 - val_smape: 1.2673

Epoch 4/128

120/120 - 3s - 22ms/step - ia: 0.4288 - loss: 0.7603 - mae: 0.6371 - rmse: 0.8693 - smape: 1.2311 - val_ia: 0.3501 - val_loss: 0.7285 - val_mae: 0.6322 - val_rmse: 0.7926 - val_smape: 1.2779

Epoch 5/128

120/120 - 2s - 18ms/step - ia: 0.4419 - loss: 0.7381 - mae: 0.6272 - rmse: 0.8569 - smape: 1.2136 - val_ia: 0.3686 - val_loss: 0.7884 - val_mae: 0.6534 - val_rmse: 0.8246 - val_smape: 1.2904

Epoch 6/128

120/120 - 3s - 24ms/step - ia: 0.4477 - loss: 0.7271 - mae: 0.6231 - rmse: 0.8504 - smape: 1.2117 - val_ia: 0.3623 - val_loss: 0.7829 - val_mae: 0.6605 - val_rmse: 0.8277 - val_smape: 1.3157

Epoch 7/128

120/120 - 2s - 19ms/step - ia: 0.4552 - loss: 0.7148 - mae: 0.6176 - rmse: 0.8430 - smape: 1.1990 - val_ia: 0.3651 - val_loss: 0.7793 - val_mae: 0.6494 - val_rmse: 0.8179 - val_smape: 1.2873

Epoch 8/128

120/120 - 2s - 20ms/step - ia: 0.4749 - loss: 0.6757 - mae: 0.6012 - rmse: 0.8194 - smape: 1.1821 - val_ia: 0.3614 - val_loss: 0.8497 - val_mae: 0.6732 - val_rmse: 0.8557 - val_smape: 1.2898

Epoch 9/128

120/120 - 2s - 17ms/step - ia: 0.4784 - loss: 0.6641 - mae: 0.5961 - rmse: 0.8129 - smape: 1.1813 - val_ia: 0.3586 - val_loss: 0.8245 - val_mae: 0.6526 - val_rmse: 0.8308 - val_smape: 1.2724

Epoch 10/128

120/120 - 3s - 24ms/step - ia: 0.4865 - loss: 0.6519 - mae: 0.5919 - rmse: 0.8046 - smape: 1.1688 - val_ia: 0.3664 - val_loss: 0.8689 - val_mae: 0.6590 - val_rmse: 0.8472 - val_smape: 1.2476

Epoch 11/128

120/120 - 2s - 18ms/step - ia: 0.4988 - loss: 0.6303 - mae: 0.5825 - rmse: 0.7914 - smape: 1.1543 - val_ia: 0.3922 - val_loss: 0.9323 - val_mae: 0.6756 - val_rmse: 0.8811 - val_smape: 1.2225

Epoch 12/128

120/120 - 2s - 17ms/step - ia: 0.5077 - loss: 0.6086 - mae: 0.5748 - rmse: 0.7777 - smape: 1.1420 - val_ia: 0.3690 - val_loss: 0.8867 - val_mae: 0.6695 - val_rmse: 0.8629 - val_smape: 1.2550

Epoch 13/128

120/120 - 3s - 23ms/step - ia: 0.5162 - loss: 0.5970 - mae: 0.5674 - rmse: 0.7699 - smape: 1.1322 - val_ia: 0.3778 - val_loss: 0.8323 - val_mae: 0.6538 - val_rmse: 0.8367 - val_smape: 1.2416

Epoch 14/128

120/120 - 3s - 22ms/step - ia: 0.5238 - loss: 0.5786 - mae: 0.5609 - rmse: 0.7583 - smape: 1.1265 - val_ia: 0.3630 - val_loss: 0.8499 - val_mae: 0.6644 - val_rmse: 0.8460 - val_smape: 1.2763

Epoch 15/128

120/120 - 2s - 14ms/step - ia: 0.5338 - loss: 0.5558 - mae: 0.5521 - rmse: 0.7437 - smape: 1.1137 - val_ia: 0.3502 - val_loss: 0.8846 - val_mae: 0.6827 - val_rmse: 0.8654 - val_smape: 1.3195

Epoch 16/128

120/120 - 3s - 29ms/step - ia: 0.5349 - loss: 0.5627 - mae: 0.5534 - rmse: 0.7480 - smape: 1.1129 - val_ia: 0.3783 - val_loss: 0.9157 - val_mae: 0.6809 - val_rmse: 0.8801 - val_smape: 1.2489

Epoch 17/128

120/120 - 3s - 24ms/step - ia: 0.5469 - loss: 0.5347 - mae: 0.5418 - rmse: 0.7292 - smape: 1.0957 - val_ia: 0.3690 - val_loss: 0.9169 - val_mae: 0.6848 - val_rmse: 0.8770 - val_smape: 1.2567

Epoch 18/128

120/120 - 3s - 22ms/step - ia: 0.5546 - loss: 0.5244 - mae: 0.5353 - rmse: 0.7222 - smape: 1.0834 - val_ia: 0.3603 - val_loss: 0.9090 - val_mae: 0.6857 - val_rmse: 0.8752 - val_smape: 1.2898

Epoch 19/128

120/120 - 2s - 20ms/step - ia: 0.5620 - loss: 0.5071 - mae: 0.5286 - rmse: 0.7100 - smape: 1.0745 - val_ia: 0.3712 - val_loss: 0.9151 - val_mae: 0.6767 - val_rmse: 0.8740 - val_smape: 1.2376

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 47s 349ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 14%|█▍        | 7/50 [1:18:01<7:42:36, 645.50s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 47s - 24ms/step - ia: 0.3844 - loss: 0.8172 - mae: 0.6625 - rmse: 0.8708 - smape: 1.2870 - val_ia: 0.2498 - val_loss: 0.8752 - val_mae: 0.6721 - val_rmse: 0.7477 - val_smape: 1.2242

Epoch 2/8

1915/1915 - 25s - 13ms/step - ia: 0.4159 - loss: 0.7773 - mae: 0.6428 - rmse: 0.8481 - smape: 1.2321 - val_ia: 0.2545 - val_loss: 0.7858 - val_mae: 0.6422 - val_rmse: 0.7178 - val_smape: 1.2332

Epoch 3/8

1915/1915 - 25s - 13ms/step - ia: 0.4302 - loss: 0.7524 - mae: 0.6325 - rmse: 0.8356 - smape: 1.2056 - val_ia: 0.2507 - val_loss: 0.7838 - val_mae: 0.6409 - val_rmse: 0.7150 - val_smape: 1.2153

Epoch 4/8

1915/1915 - 42s - 22ms/step - ia: 0.4438 - loss: 0.7360 - mae: 0.6231 - rmse: 0.8257 - smape: 1.1903 - val_ia: 0.2517 - val_loss: 0.7890 - val_mae: 0.6430 - val_rmse: 0.7177 - val_smape: 1.2288

Epoch 5/8

1915/1915 - 25s - 13ms/step - ia: 0.4545 - loss: 0.7109 - mae: 0.6133 - rmse: 0.8106 - smape: 1.1769 - val_ia: 0.2445 - val_loss: 0.8222 - val_mae: 0.6655 - val_rmse: 0.7404 - val_smape: 1.2700

Epoch 6/8

1915/1915 - 40s - 21ms/step - ia: 0.4635 - loss: 0.6951 - mae: 0.6055 - rmse: 0.8028 - smape: 1.1681 - val_ia: 0.2458 - val_loss: 0.8220 - val_mae: 0.6580 - val_rmse: 0.7316 - val_smape: 1.2734

Epoch 7/8

1915/1915 - 42s - 22ms/step - ia: 0.4746 - loss: 0.6712 - mae: 0.5959 - rmse: 0.7884 - smape: 1.1595 - val_ia: 0.2454 - val_loss: 0.8537 - val_mae: 0.6677 - val_rmse: 0.7501 - val_smape: 1.2425

Epoch 8/8

1915/1915 - 24s - 13ms/step - ia: 0.4834 - loss: 0.6482 - mae: 0.5865 - rmse: 0.7761 - smape: 1.1449 - val_ia: 0.2442 - val_loss: 0.8564 - val_mae: 0.6688 - val_rmse: 0.7490 - val_smape: 1.2820

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:27 2s/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step

 16%|█▌        | 8/50 [1:22:36<6:09:16, 527.54s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 6s - 48ms/step - ia: 0.2874 - loss: 1.0330 - mae: 0.7589 - rmse: 1.0101 - smape: 1.4454 - val_ia: 0.3092 - val_loss: 0.8111 - val_mae: 0.6692 - val_rmse: 0.8292 - val_smape: 1.3951

Epoch 2/128

120/120 - 1s - 8ms/step - ia: 0.3271 - loss: 0.8772 - mae: 0.6982 - rmse: 0.9335 - smape: 1.3927 - val_ia: 0.3208 - val_loss: 0.7882 - val_mae: 0.6594 - val_rmse: 0.8194 - val_smape: 1.3668

Epoch 3/128

120/120 - 1s - 12ms/step - ia: 0.3417 - loss: 0.8533 - mae: 0.6841 - rmse: 0.9214 - smape: 1.3726 - val_ia: 0.3201 - val_loss: 0.7810 - val_mae: 0.6559 - val_rmse: 0.8155 - val_smape: 1.3668

Epoch 4/128

120/120 - 1s - 12ms/step - ia: 0.3501 - loss: 0.8392 - mae: 0.6785 - rmse: 0.9126 - smape: 1.3608 - val_ia: 0.3241 - val_loss: 0.7741 - val_mae: 0.6524 - val_rmse: 0.8126 - val_smape: 1.3501

Epoch 5/128

120/120 - 1s - 7ms/step - ia: 0.3523 - loss: 0.8376 - mae: 0.6754 - rmse: 0.9122 - smape: 1.3547 - val_ia: 0.3277 - val_loss: 0.7728 - val_mae: 0.6538 - val_rmse: 0.8140 - val_smape: 1.3468

Epoch 6/128

120/120 - 1s - 11ms/step - ia: 0.3605 - loss: 0.8276 - mae: 0.6711 - rmse: 0.9067 - smape: 1.3436 - val_ia: 0.3313 - val_loss: 0.7672 - val_mae: 0.6487 - val_rmse: 0.8104 - val_smape: 1.3218

Epoch 7/128

120/120 - 1s - 6ms/step - ia: 0.3656 - loss: 0.8217 - mae: 0.6686 - rmse: 0.9042 - smape: 1.3322 - val_ia: 0.3337 - val_loss: 0.7621 - val_mae: 0.6440 - val_rmse: 0.8064 - val_smape: 1.3043

Epoch 8/128

120/120 - 1s - 10ms/step - ia: 0.3735 - loss: 0.8185 - mae: 0.6643 - rmse: 0.9022 - smape: 1.3181 - val_ia: 0.3328 - val_loss: 0.7605 - val_mae: 0.6452 - val_rmse: 0.8067 - val_smape: 1.3067

Epoch 9/128

120/120 - 1s - 7ms/step - ia: 0.3779 - loss: 0.8112 - mae: 0.6622 - rmse: 0.8979 - smape: 1.3146 - val_ia: 0.3305 - val_loss: 0.7625 - val_mae: 0.6491 - val_rmse: 0.8099 - val_smape: 1.3210

Epoch 10/128

120/120 - 1s - 12ms/step - ia: 0.3795 - loss: 0.8116 - mae: 0.6622 - rmse: 0.8985 - smape: 1.3105 - val_ia: 0.3343 - val_loss: 0.7632 - val_mae: 0.6449 - val_rmse: 0.8086 - val_smape: 1.3008

Epoch 11/128

120/120 - 1s - 11ms/step - ia: 0.3798 - loss: 0.8086 - mae: 0.6597 - rmse: 0.8964 - smape: 1.3095 - val_ia: 0.3326 - val_loss: 0.7654 - val_mae: 0.6501 - val_rmse: 0.8120 - val_smape: 1.3150

Epoch 12/128

120/120 - 1s - 8ms/step - ia: 0.3835 - loss: 0.8048 - mae: 0.6584 - rmse: 0.8943 - smape: 1.3035 - val_ia: 0.3382 - val_loss: 0.7587 - val_mae: 0.6443 - val_rmse: 0.8076 - val_smape: 1.2958

Epoch 13/128

120/120 - 1s - 12ms/step - ia: 0.3882 - loss: 0.8021 - mae: 0.6561 - rmse: 0.8920 - smape: 1.2965 - val_ia: 0.3441 - val_loss: 0.7623 - val_mae: 0.6464 - val_rmse: 0.8110 - val_smape: 1.2869

Epoch 14/128

120/120 - 1s - 12ms/step - ia: 0.3900 - loss: 0.8016 - mae: 0.6568 - rmse: 0.8925 - smape: 1.2922 - val_ia: 0.3378 - val_loss: 0.7629 - val_mae: 0.6468 - val_rmse: 0.8104 - val_smape: 1.2990

Epoch 15/128

120/120 - 1s - 10ms/step - ia: 0.3899 - loss: 0.8005 - mae: 0.6563 - rmse: 0.8924 - smape: 1.2965 - val_ia: 0.3356 - val_loss: 0.7571 - val_mae: 0.6461 - val_rmse: 0.8077 - val_smape: 1.3014

Epoch 16/128

120/120 - 1s - 5ms/step - ia: 0.3906 - loss: 0.7945 - mae: 0.6551 - rmse: 0.8887 - smape: 1.2938 - val_ia: 0.3449 - val_loss: 0.7612 - val_mae: 0.6446 - val_rmse: 0.8098 - val_smape: 1.2809

Epoch 17/128

120/120 - 2s - 14ms/step - ia: 0.3949 - loss: 0.7959 - mae: 0.6535 - rmse: 0.8898 - smape: 1.2869 - val_ia: 0.3467 - val_loss: 0.7550 - val_mae: 0.6412 - val_rmse: 0.8056 - val_smape: 1.2710

Epoch 18/128

120/120 - 1s - 10ms/step - ia: 0.3942 - loss: 0.7996 - mae: 0.6541 - rmse: 0.8911 - smape: 1.2856 - val_ia: 0.3389 - val_loss: 0.7631 - val_mae: 0.6463 - val_rmse: 0.8096 - val_smape: 1.2935

Epoch 19/128

120/120 - 1s - 11ms/step - ia: 0.3956 - loss: 0.7931 - mae: 0.6526 - rmse: 0.8881 - smape: 1.2824 - val_ia: 0.3426 - val_loss: 0.7612 - val_mae: 0.6442 - val_rmse: 0.8086 - val_smape: 1.2812

Epoch 20/128

120/120 - 1s - 12ms/step - ia: 0.3980 - loss: 0.7918 - mae: 0.6511 - rmse: 0.8872 - smape: 1.2816 - val_ia: 0.3415 - val_loss: 0.7625 - val_mae: 0.6487 - val_rmse: 0.8108 - val_smape: 1.2923

Epoch 21/128

120/120 - 1s - 12ms/step - ia: 0.3994 - loss: 0.7911 - mae: 0.6517 - rmse: 0.8868 - smape: 1.2810 - val_ia: 0.3475 - val_loss: 0.7595 - val_mae: 0.6440 - val_rmse: 0.8088 - val_smape: 1.2751

Epoch 22/128

120/120 - 1s - 7ms/step - ia: 0.4008 - loss: 0.7863 - mae: 0.6492 - rmse: 0.8841 - smape: 1.2794 - val_ia: 0.3491 - val_loss: 0.7585 - val_mae: 0.6431 - val_rmse: 0.8078 - val_smape: 1.2668

Epoch 23/128

120/120 - 1s - 6ms/step - ia: 0.4016 - loss: 0.7868 - mae: 0.6503 - rmse: 0.8848 - smape: 1.2813 - val_ia: 0.3508 - val_loss: 0.7613 - val_mae: 0.6454 - val_rmse: 0.8099 - val_smape: 1.2723

Epoch 24/128

120/120 - 1s - 4ms/step - ia: 0.4023 - loss: 0.7845 - mae: 0.6490 - rmse: 0.8835 - smape: 1.2771 - val_ia: 0.3494 - val_loss: 0.7627 - val_mae: 0.6452 - val_rmse: 0.8103 - val_smape: 1.2701

Epoch 25/128

120/120 - 1s - 4ms/step - ia: 0.4029 - loss: 0.7833 - mae: 0.6482 - rmse: 0.8827 - smape: 1.2775 - val_ia: 0.3506 - val_loss: 0.7649 - val_mae: 0.6453 - val_rmse: 0.8107 - val_smape: 1.2650

Epoch 26/128

120/120 - 1s - 6ms/step - ia: 0.4063 - loss: 0.7824 - mae: 0.6475 - rmse: 0.8821 - smape: 1.2690 - val_ia: 0.3458 - val_loss: 0.7619 - val_mae: 0.6460 - val_rmse: 0.8091 - val_smape: 1.2758

Epoch 27/128

120/120 - 1s - 6ms/step - ia: 0.4054 - loss: 0.7827 - mae: 0.6478 - rmse: 0.8820 - smape: 1.2726 - val_ia: 0.3487 - val_loss: 0.7565 - val_mae: 0.6427 - val_rmse: 0.8062 - val_smape: 1.2717

Epoch 28/128

120/120 - 1s - 7ms/step - ia: 0.4026 - loss: 0.7867 - mae: 0.6492 - rmse: 0.8852 - smape: 1.2731 - val_ia: 0.3488 - val_loss: 0.7582 - val_mae: 0.6444 - val_rmse: 0.8079 - val_smape: 1.2690

Epoch 29/128

120/120 - 2s - 13ms/step - ia: 0.4087 - loss: 0.7793 - mae: 0.6456 - rmse: 0.8808 - smape: 1.2668 - val_ia: 0.3438 - val_loss: 0.7592 - val_mae: 0.6457 - val_rmse: 0.8080 - val_smape: 1.2840

Epoch 30/128

120/120 - 1s - 10ms/step - ia: 0.4079 - loss: 0.7785 - mae: 0.6453 - rmse: 0.8797 - smape: 1.2676 - val_ia: 0.3498 - val_loss: 0.7635 - val_mae: 0.6444 - val_rmse: 0.8093 - val_smape: 1.2661

Epoch 31/128

120/120 - 1s - 12ms/step - ia: 0.4105 - loss: 0.7743 - mae: 0.6442 - rmse: 0.8769 - smape: 1.2659 - val_ia: 0.3507 - val_loss: 0.7554 - val_mae: 0.6403 - val_rmse: 0.8041 - val_smape: 1.2612

Epoch 32/128

120/120 - 1s - 12ms/step - ia: 0.4100 - loss: 0.7718 - mae: 0.6441 - rmse: 0.8763 - smape: 1.2657 - val_ia: 0.3556 - val_loss: 0.7666 - val_mae: 0.6444 - val_rmse: 0.8109 - val_smape: 1.2587

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 17.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 56s 416ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 18%|█▊        | 9/50 [1:23:18<4:16:49, 375.85s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 29s - 30ms/step - ia: 0.3211 - loss: 0.8632 - mae: 0.6857 - rmse: 0.9099 - smape: 1.4025 - val_ia: 0.2524 - val_loss: 0.7964 - val_mae: 0.6615 - val_rmse: 0.7539 - val_smape: 1.3137

Epoch 2/16

958/958 - 19s - 20ms/step - ia: 0.3805 - loss: 0.8164 - mae: 0.6627 - rmse: 0.8852 - smape: 1.2961 - val_ia: 0.2562 - val_loss: 0.7797 - val_mae: 0.6479 - val_rmse: 0.7421 - val_smape: 1.2649

Epoch 3/16

958/958 - 20s - 21ms/step - ia: 0.3955 - loss: 0.7991 - mae: 0.6545 - rmse: 0.8755 - smape: 1.2723 - val_ia: 0.2606 - val_loss: 0.8250 - val_mae: 0.6754 - val_rmse: 0.7743 - val_smape: 1.2938

Epoch 4/16

958/958 - 21s - 22ms/step - ia: 0.4047 - loss: 0.7922 - mae: 0.6515 - rmse: 0.8716 - smape: 1.2578 - val_ia: 0.2595 - val_loss: 0.7764 - val_mae: 0.6559 - val_rmse: 0.7490 - val_smape: 1.3005

Epoch 5/16

958/958 - 18s - 19ms/step - ia: 0.4102 - loss: 0.7831 - mae: 0.6471 - rmse: 0.8661 - smape: 1.2488 - val_ia: 0.2648 - val_loss: 0.8386 - val_mae: 0.6814 - val_rmse: 0.7811 - val_smape: 1.2959

Epoch 6/16

958/958 - 15s - 16ms/step - ia: 0.4155 - loss: 0.7740 - mae: 0.6434 - rmse: 0.8625 - smape: 1.2391 - val_ia: 0.2667 - val_loss: 0.7705 - val_mae: 0.6465 - val_rmse: 0.7427 - val_smape: 1.2498

Epoch 7/16

958/958 - 23s - 24ms/step - ia: 0.4206 - loss: 0.7700 - mae: 0.6404 - rmse: 0.8592 - smape: 1.2309 - val_ia: 0.2658 - val_loss: 0.7576 - val_mae: 0.6442 - val_rmse: 0.7383 - val_smape: 1.2706

Epoch 8/16

958/958 - 21s - 22ms/step - ia: 0.4237 - loss: 0.7634 - mae: 0.6375 - rmse: 0.8550 - smape: 1.2278 - val_ia: 0.2656 - val_loss: 0.7730 - val_mae: 0.6503 - val_rmse: 0.7465 - val_smape: 1.2636

Epoch 9/16

958/958 - 21s - 22ms/step - ia: 0.4277 - loss: 0.7592 - mae: 0.6360 - rmse: 0.8531 - smape: 1.2218 - val_ia: 0.2635 - val_loss: 0.7838 - val_mae: 0.6528 - val_rmse: 0.7481 - val_smape: 1.2814

Epoch 10/16

958/958 - 17s - 17ms/step - ia: 0.4299 - loss: 0.7536 - mae: 0.6331 - rmse: 0.8502 - smape: 1.2188 - val_ia: 0.2689 - val_loss: 0.7945 - val_mae: 0.6555 - val_rmse: 0.7550 - val_smape: 1.2534

Epoch 11/16

958/958 - 19s - 20ms/step - ia: 0.4344 - loss: 0.7480 - mae: 0.6308 - rmse: 0.8480 - smape: 1.2106 - val_ia: 0.2661 - val_loss: 0.7762 - val_mae: 0.6492 - val_rmse: 0.7451 - val_smape: 1.2676

Epoch 12/16

958/958 - 14s - 15ms/step - ia: 0.4367 - loss: 0.7423 - mae: 0.6284 - rmse: 0.8444 - smape: 1.2105 - val_ia: 0.2660 - val_loss: 0.7852 - val_mae: 0.6542 - val_rmse: 0.7510 - val_smape: 1.2851

Epoch 13/16

958/958 - 14s - 15ms/step - ia: 0.4416 - loss: 0.7347 - mae: 0.6252 - rmse: 0.8398 - smape: 1.2021 - val_ia: 0.2642 - val_loss: 0.8059 - val_mae: 0.6672 - val_rmse: 0.7651 - val_smape: 1.3168

Epoch 14/16

958/958 - 16s - 17ms/step - ia: 0.4458 - loss: 0.7269 - mae: 0.6222 - rmse: 0.8346 - smape: 1.2003 - val_ia: 0.2671 - val_loss: 0.8123 - val_mae: 0.6678 - val_rmse: 0.7690 - val_smape: 1.2962

Epoch 15/16

958/958 - 17s - 18ms/step - ia: 0.4501 - loss: 0.7204 - mae: 0.6188 - rmse: 0.8319 - smape: 1.1930 - val_ia: 0.2646 - val_loss: 0.7799 - val_mae: 0.6479 - val_rmse: 0.7420 - val_smape: 1.2999

Epoch 16/16

958/958 - 15s - 15ms/step - ia: 0.4501 - loss: 0.7157 - mae: 0.6175 - rmse: 0.8278 - smape: 1.1940 - val_ia: 0.2659 - val_loss: 0.8058 - val_mae: 0.6638 - val_rmse: 0.7631 - val_smape: 1.3058

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:03 917ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 20%|██        | 10/50 [1:28:20<3:55:16, 352.91s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 17s - 69ms/step - ia: 0.2811 - loss: 2.3599 - mae: 1.0234 - rmse: 1.5040 - smape: 1.4454 - val_ia: 0.2798 - val_loss: 0.9441 - val_mae: 0.7005 - val_rmse: 0.8560 - val_smape: 1.4155

Epoch 2/8

240/240 - 4s - 15ms/step - ia: 0.2793 - loss: 2.2141 - mae: 1.0175 - rmse: 1.4711 - smape: 1.4513 - val_ia: 0.2800 - val_loss: 0.9436 - val_mae: 0.7005 - val_rmse: 0.8559 - val_smape: 1.4168

Epoch 3/8

240/240 - 2s - 9ms/step - ia: 0.2809 - loss: 2.1512 - mae: 1.0077 - rmse: 1.4491 - smape: 1.4426 - val_ia: 0.2803 - val_loss: 0.9429 - val_mae: 0.7004 - val_rmse: 0.8558 - val_smape: 1.4181

Epoch 4/8

240/240 - 3s - 13ms/step - ia: 0.2816 - loss: 2.2254 - mae: 1.0080 - rmse: 1.4648 - smape: 1.4462 - val_ia: 0.2807 - val_loss: 0.9423 - val_mae: 0.7003 - val_rmse: 0.8557 - val_smape: 1.4193

Epoch 5/8

240/240 - 3s - 12ms/step - ia: 0.2832 - loss: 2.1329 - mae: 1.0004 - rmse: 1.4408 - smape: 1.4442 - val_ia: 0.2810 - val_loss: 0.9418 - val_mae: 0.7002 - val_rmse: 0.8556 - val_smape: 1.4203

Epoch 6/8

240/240 - 2s - 9ms/step - ia: 0.2828 - loss: 2.1649 - mae: 1.0024 - rmse: 1.4520 - smape: 1.4496 - val_ia: 0.2813 - val_loss: 0.9410 - val_mae: 0.7000 - val_rmse: 0.8554 - val_smape: 1.4209

Epoch 7/8

240/240 - 3s - 11ms/step - ia: 0.2778 - loss: 2.1495 - mae: 1.0023 - rmse: 1.4451 - smape: 1.4504 - val_ia: 0.2817 - val_loss: 0.9406 - val_mae: 0.7000 - val_rmse: 0.8554 - val_smape: 1.4216

Epoch 8/8

240/240 - 3s - 11ms/step - ia: 0.2838 - loss: 2.1831 - mae: 1.0008 - rmse: 1.4546 - smape: 1.4410 - val_ia: 0.2820 - val_loss: 0.9398 - val_mae: 0.6999 - val_rmse: 0.8552 - val_smape: 1.4228

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:08 505ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 22%|██▏       | 11/50 [1:28:58<2:46:46, 256.56s/trial, best loss: 0.7737179259751158]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

958/958 - 24s - 25ms/step - ia: 0.3439 - loss: 0.8871 - mae: 0.7004 - rmse: 0.9240 - smape: 1.3552 - val_ia: 0.2605 - val_loss: 0.7674 - val_mae: 0.6474 - val_rmse: 0.7406 - val_smape: 1.2848

Epoch 2/128

958/958 - 8s - 9ms/step - ia: 0.3796 - loss: 0.8426 - mae: 0.6768 - rmse: 0.9002 - smape: 1.2921 - val_ia: 0.2609 - val_loss: 0.7616 - val_mae: 0.6365 - val_rmse: 0.7286 - val_smape: 1.2499

Epoch 3/128

958/958 - 10s - 11ms/step - ia: 0.3806 - loss: 0.8336 - mae: 0.6729 - rmse: 0.8962 - smape: 1.2926 - val_ia: 0.2567 - val_loss: 0.7738 - val_mae: 0.6620 - val_rmse: 0.7545 - val_smape: 1.3265

Epoch 4/128

958/958 - 9s - 9ms/step - ia: 0.3828 - loss: 0.8287 - mae: 0.6712 - rmse: 0.8929 - smape: 1.2907 - val_ia: 0.2578 - val_loss: 0.7614 - val_mae: 0.6350 - val_rmse: 0.7272 - val_smape: 1.2475

Epoch 5/128

958/958 - 8s - 8ms/step - ia: 0.3871 - loss: 0.8204 - mae: 0.6659 - rmse: 0.8878 - smape: 1.2813 - val_ia: 0.2583 - val_loss: 0.7564 - val_mae: 0.6373 - val_rmse: 0.7303 - val_smape: 1.2551

Epoch 6/128

958/958 - 11s - 11ms/step - ia: 0.3862 - loss: 0.8192 - mae: 0.6665 - rmse: 0.8867 - smape: 1.2831 - val_ia: 0.2566 - val_loss: 0.7581 - val_mae: 0.6406 - val_rmse: 0.7329 - val_smape: 1.2703

Epoch 7/128

958/958 - 9s - 10ms/step - ia: 0.3899 - loss: 0.8155 - mae: 0.6640 - rmse: 0.8853 - smape: 1.2798 - val_ia: 0.2576 - val_loss: 0.7580 - val_mae: 0.6477 - val_rmse: 0.7410 - val_smape: 1.2867

Epoch 8/128

958/958 - 8s - 8ms/step - ia: 0.3897 - loss: 0.8159 - mae: 0.6633 - rmse: 0.8854 - smape: 1.2776 - val_ia: 0.2572 - val_loss: 0.7566 - val_mae: 0.6453 - val_rmse: 0.7385 - val_smape: 1.2792

Epoch 9/128

958/958 - 8s - 9ms/step - ia: 0.3903 - loss: 0.8131 - mae: 0.6628 - rmse: 0.8838 - smape: 1.2764 - val_ia: 0.2590 - val_loss: 0.7515 - val_mae: 0.6370 - val_rmse: 0.7323 - val_smape: 1.2388

Epoch 10/128

958/958 - 8s - 8ms/step - ia: 0.3950 - loss: 0.8097 - mae: 0.6601 - rmse: 0.8827 - smape: 1.2683 - val_ia: 0.2570 - val_loss: 0.7525 - val_mae: 0.6403 - val_rmse: 0.7341 - val_smape: 1.2615

Epoch 11/128

958/958 - 8s - 8ms/step - ia: 0.3935 - loss: 0.8079 - mae: 0.6596 - rmse: 0.8812 - smape: 1.2725 - val_ia: 0.2582 - val_loss: 0.7559 - val_mae: 0.6439 - val_rmse: 0.7399 - val_smape: 1.2576

Epoch 12/128

958/958 - 7s - 8ms/step - ia: 0.3976 - loss: 0.8034 - mae: 0.6576 - rmse: 0.8788 - smape: 1.2656 - val_ia: 0.2580 - val_loss: 0.7499 - val_mae: 0.6239 - val_rmse: 0.7194 - val_smape: 1.1948

Epoch 13/128

958/958 - 9s - 9ms/step - ia: 0.3986 - loss: 0.8033 - mae: 0.6573 - rmse: 0.8789 - smape: 1.2638 - val_ia: 0.2573 - val_loss: 0.7458 - val_mae: 0.6357 - val_rmse: 0.7293 - val_smape: 1.2522

Epoch 14/128

958/958 - 8s - 8ms/step - ia: 0.3984 - loss: 0.8015 - mae: 0.6562 - rmse: 0.8781 - smape: 1.2633 - val_ia: 0.2565 - val_loss: 0.7549 - val_mae: 0.6458 - val_rmse: 0.7406 - val_smape: 1.2763

Epoch 15/128

958/958 - 9s - 9ms/step - ia: 0.4032 - loss: 0.7971 - mae: 0.6545 - rmse: 0.8761 - smape: 1.2585 - val_ia: 0.2577 - val_loss: 0.7452 - val_mae: 0.6277 - val_rmse: 0.7239 - val_smape: 1.2143

Epoch 16/128

958/958 - 8s - 8ms/step - ia: 0.4028 - loss: 0.7953 - mae: 0.6529 - rmse: 0.8729 - smape: 1.2581 - val_ia: 0.2561 - val_loss: 0.7445 - val_mae: 0.6331 - val_rmse: 0.7261 - val_smape: 1.2609

Epoch 17/128

958/958 - 8s - 8ms/step - ia: 0.4064 - loss: 0.7922 - mae: 0.6518 - rmse: 0.8735 - smape: 1.2560 - val_ia: 0.2588 - val_loss: 0.7544 - val_mae: 0.6465 - val_rmse: 0.7413 - val_smape: 1.2826

Epoch 18/128

958/958 - 9s - 9ms/step - ia: 0.4089 - loss: 0.7900 - mae: 0.6498 - rmse: 0.8714 - smape: 1.2534 - val_ia: 0.2584 - val_loss: 0.7469 - val_mae: 0.6383 - val_rmse: 0.7327 - val_smape: 1.2682

Epoch 19/128

958/958 - 10s - 10ms/step - ia: 0.4098 - loss: 0.7876 - mae: 0.6486 - rmse: 0.8692 - smape: 1.2509 - val_ia: 0.2593 - val_loss: 0.7418 - val_mae: 0.6268 - val_rmse: 0.7219 - val_smape: 1.2260

Epoch 20/128

958/958 - 8s - 8ms/step - ia: 0.4123 - loss: 0.7844 - mae: 0.6464 - rmse: 0.8666 - smape: 1.2494 - val_ia: 0.2613 - val_loss: 0.7610 - val_mae: 0.6446 - val_rmse: 0.7425 - val_smape: 1.2529

Epoch 21/128

958/958 - 7s - 7ms/step - ia: 0.4160 - loss: 0.7815 - mae: 0.6454 - rmse: 0.8650 - smape: 1.2428 - val_ia: 0.2617 - val_loss: 0.7402 - val_mae: 0.6302 - val_rmse: 0.7246 - val_smape: 1.2523

Epoch 22/128

958/958 - 8s - 8ms/step - ia: 0.4160 - loss: 0.7789 - mae: 0.6441 - rmse: 0.8640 - smape: 1.2422 - val_ia: 0.2611 - val_loss: 0.7602 - val_mae: 0.6499 - val_rmse: 0.7454 - val_smape: 1.2886

Epoch 23/128

958/958 - 8s - 9ms/step - ia: 0.4166 - loss: 0.7786 - mae: 0.6442 - rmse: 0.8649 - smape: 1.2436 - val_ia: 0.2625 - val_loss: 0.7584 - val_mae: 0.6355 - val_rmse: 0.7336 - val_smape: 1.2290

Epoch 24/128

958/958 - 10s - 11ms/step - ia: 0.4189 - loss: 0.7761 - mae: 0.6425 - rmse: 0.8624 - smape: 1.2390 - val_ia: 0.2634 - val_loss: 0.7553 - val_mae: 0.6346 - val_rmse: 0.7326 - val_smape: 1.2348

Epoch 25/128

958/958 - 10s - 10ms/step - ia: 0.4208 - loss: 0.7724 - mae: 0.6414 - rmse: 0.8602 - smape: 1.2363 - val_ia: 0.2636 - val_loss: 0.7478 - val_mae: 0.6330 - val_rmse: 0.7298 - val_smape: 1.2430

Epoch 26/128

958/958 - 8s - 9ms/step - ia: 0.4244 - loss: 0.7702 - mae: 0.6392 - rmse: 0.8586 - smape: 1.2312 - val_ia: 0.2656 - val_loss: 0.7535 - val_mae: 0.6379 - val_rmse: 0.7346 - val_smape: 1.2519

Epoch 27/128

958/958 - 8s - 8ms/step - ia: 0.4242 - loss: 0.7696 - mae: 0.6390 - rmse: 0.8600 - smape: 1.2309 - val_ia: 0.2651 - val_loss: 0.7769 - val_mae: 0.6579 - val_rmse: 0.7566 - val_smape: 1.2816

Epoch 28/128

958/958 - 10s - 11ms/step - ia: 0.4252 - loss: 0.7670 - mae: 0.6382 - rmse: 0.8582 - smape: 1.2300 - val_ia: 0.2660 - val_loss: 0.7498 - val_mae: 0.6273 - val_rmse: 0.7256 - val_smape: 1.2138

Epoch 29/128

958/958 - 8s - 9ms/step - ia: 0.4267 - loss: 0.7645 - mae: 0.6377 - rmse: 0.8557 - smape: 1.2289 - val_ia: 0.2661 - val_loss: 0.7344 - val_mae: 0.6251 - val_rmse: 0.7199 - val_smape: 1.2456

Epoch 30/128

958/958 - 8s - 8ms/step - ia: 0.4276 - loss: 0.7648 - mae: 0.6369 - rmse: 0.8572 - smape: 1.2266 - val_ia: 0.2651 - val_loss: 0.7666 - val_mae: 0.6460 - val_rmse: 0.7448 - val_smape: 1.2488

Epoch 31/128

958/958 - 10s - 11ms/step - ia: 0.4301 - loss: 0.7626 - mae: 0.6359 - rmse: 0.8544 - smape: 1.2221 - val_ia: 0.2657 - val_loss: 0.7452 - val_mae: 0.6328 - val_rmse: 0.7287 - val_smape: 1.2503

Epoch 32/128

958/958 - 8s - 8ms/step - ia: 0.4288 - loss: 0.7614 - mae: 0.6359 - rmse: 0.8542 - smape: 1.2253 - val_ia: 0.2647 - val_loss: 0.7590 - val_mae: 0.6363 - val_rmse: 0.7356 - val_smape: 1.2227

Epoch 33/128

958/958 - 8s - 8ms/step - ia: 0.4316 - loss: 0.7599 - mae: 0.6350 - rmse: 0.8529 - smape: 1.2222 - val_ia: 0.2672 - val_loss: 0.7702 - val_mae: 0.6404 - val_rmse: 0.7408 - val_smape: 1.2297

Epoch 34/128

958/958 - 9s - 9ms/step - ia: 0.4311 - loss: 0.7590 - mae: 0.6340 - rmse: 0.8536 - smape: 1.2167 - val_ia: 0.2667 - val_loss: 0.7534 - val_mae: 0.6313 - val_rmse: 0.7305 - val_smape: 1.2189

Epoch 35/128

958/958 - 8s - 8ms/step - ia: 0.4341 - loss: 0.7577 - mae: 0.6331 - rmse: 0.8526 - smape: 1.2152 - val_ia: 0.2654 - val_loss: 0.7525 - val_mae: 0.6397 - val_rmse: 0.7363 - val_smape: 1.2583

Epoch 36/128

958/958 - 10s - 11ms/step - ia: 0.4324 - loss: 0.7571 - mae: 0.6341 - rmse: 0.8519 - smape: 1.2198 - val_ia: 0.2670 - val_loss: 0.7664 - val_mae: 0.6402 - val_rmse: 0.7402 - val_smape: 1.2279

Epoch 37/128

958/958 - 11s - 11ms/step - ia: 0.4353 - loss: 0.7561 - mae: 0.6325 - rmse: 0.8519 - smape: 1.2114 - val_ia: 0.2653 - val_loss: 0.7584 - val_mae: 0.6397 - val_rmse: 0.7367 - val_smape: 1.2554

Epoch 38/128

958/958 - 8s - 9ms/step - ia: 0.4335 - loss: 0.7525 - mae: 0.6318 - rmse: 0.8500 - smape: 1.2162 - val_ia: 0.2699 - val_loss: 0.7571 - val_mae: 0.6227 - val_rmse: 0.7231 - val_smape: 1.1859

Epoch 39/128

958/958 - 10s - 11ms/step - ia: 0.4350 - loss: 0.7512 - mae: 0.6314 - rmse: 0.8486 - smape: 1.2140 - val_ia: 0.2682 - val_loss: 0.7868 - val_mae: 0.6492 - val_rmse: 0.7527 - val_smape: 1.2265

Epoch 40/128

958/958 - 11s - 11ms/step - ia: 0.4361 - loss: 0.7512 - mae: 0.6305 - rmse: 0.8473 - smape: 1.2112 - val_ia: 0.2658 - val_loss: 0.7566 - val_mae: 0.6403 - val_rmse: 0.7380 - val_smape: 1.2478

Epoch 41/128

958/958 - 10s - 11ms/step - ia: 0.4370 - loss: 0.7489 - mae: 0.6293 - rmse: 0.8481 - smape: 1.2061 - val_ia: 0.2668 - val_loss: 0.7976 - val_mae: 0.6618 - val_rmse: 0.7631 - val_smape: 1.2701

Epoch 42/128

958/958 - 10s - 10ms/step - ia: 0.4371 - loss: 0.7482 - mae: 0.6297 - rmse: 0.8472 - smape: 1.2100 - val_ia: 0.2678 - val_loss: 0.7991 - val_mae: 0.6505 - val_rmse: 0.7543 - val_smape: 1.2226

Epoch 43/128

958/958 - 6s - 7ms/step - ia: 0.4382 - loss: 0.7488 - mae: 0.6297 - rmse: 0.8478 - smape: 1.2090 - val_ia: 0.2665 - val_loss: 0.7801 - val_mae: 0.6459 - val_rmse: 0.7465 - val_smape: 1.2370

Epoch 44/128

958/958 - 7s - 7ms/step - ia: 0.4406 - loss: 0.7474 - mae: 0.6287 - rmse: 0.8469 - smape: 1.2042 - val_ia: 0.2670 - val_loss: 0.7891 - val_mae: 0.6476 - val_rmse: 0.7490 - val_smape: 1.2310

Epoch 44: early stopping

Restoring model weights from the end of the best epoch: 29.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 46s 347ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 24%|██▍       | 12/50 [1:35:40<3:10:30, 300.80s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 18s - 75ms/step - ia: 0.3047 - loss: 0.8688 - mae: 0.6936 - rmse: 0.9270 - smape: 1.4290 - val_ia: 0.3024 - val_loss: 0.7980 - val_mae: 0.6600 - val_rmse: 0.8079 - val_smape: 1.3229

Epoch 2/16

240/240 - 3s - 13ms/step - ia: 0.3632 - loss: 0.8260 - mae: 0.6714 - rmse: 0.9033 - smape: 1.3261 - val_ia: 0.3062 - val_loss: 0.7831 - val_mae: 0.6501 - val_rmse: 0.7985 - val_smape: 1.3023

Epoch 3/16

240/240 - 3s - 12ms/step - ia: 0.3836 - loss: 0.8063 - mae: 0.6608 - rmse: 0.8930 - smape: 1.2974 - val_ia: 0.3247 - val_loss: 0.7654 - val_mae: 0.6449 - val_rmse: 0.7943 - val_smape: 1.2822

Epoch 4/16

240/240 - 3s - 12ms/step - ia: 0.3953 - loss: 0.7946 - mae: 0.6553 - rmse: 0.8871 - smape: 1.2804 - val_ia: 0.3324 - val_loss: 0.7650 - val_mae: 0.6472 - val_rmse: 0.7978 - val_smape: 1.2629

Epoch 5/16

240/240 - 3s - 12ms/step - ia: 0.4046 - loss: 0.7827 - mae: 0.6509 - rmse: 0.8793 - smape: 1.2660 - val_ia: 0.3400 - val_loss: 0.7848 - val_mae: 0.6573 - val_rmse: 0.8095 - val_smape: 1.2720

Epoch 6/16

240/240 - 3s - 12ms/step - ia: 0.4125 - loss: 0.7784 - mae: 0.6463 - rmse: 0.8769 - smape: 1.2501 - val_ia: 0.3378 - val_loss: 0.7750 - val_mae: 0.6523 - val_rmse: 0.7998 - val_smape: 1.2596

Epoch 7/16

240/240 - 3s - 12ms/step - ia: 0.4186 - loss: 0.7732 - mae: 0.6440 - rmse: 0.8733 - smape: 1.2384 - val_ia: 0.3429 - val_loss: 0.7936 - val_mae: 0.6476 - val_rmse: 0.8017 - val_smape: 1.2424

Epoch 8/16

240/240 - 6s - 25ms/step - ia: 0.4212 - loss: 0.7689 - mae: 0.6425 - rmse: 0.8727 - smape: 1.2319 - val_ia: 0.3382 - val_loss: 0.7852 - val_mae: 0.6446 - val_rmse: 0.7952 - val_smape: 1.2394

Epoch 9/16

240/240 - 3s - 14ms/step - ia: 0.4247 - loss: 0.7627 - mae: 0.6398 - rmse: 0.8685 - smape: 1.2297 - val_ia: 0.3445 - val_loss: 0.7867 - val_mae: 0.6491 - val_rmse: 0.7999 - val_smape: 1.2386

Epoch 10/16

240/240 - 3s - 13ms/step - ia: 0.4275 - loss: 0.7582 - mae: 0.6390 - rmse: 0.8656 - smape: 1.2256 - val_ia: 0.3406 - val_loss: 0.8139 - val_mae: 0.6473 - val_rmse: 0.8024 - val_smape: 1.2208

Epoch 11/16

240/240 - 4s - 15ms/step - ia: 0.4309 - loss: 0.7518 - mae: 0.6352 - rmse: 0.8623 - smape: 1.2208 - val_ia: 0.3437 - val_loss: 0.8154 - val_mae: 0.6550 - val_rmse: 0.8102 - val_smape: 1.2470

Epoch 12/16

240/240 - 5s - 22ms/step - ia: 0.4346 - loss: 0.7448 - mae: 0.6331 - rmse: 0.8572 - smape: 1.2160 - val_ia: 0.3426 - val_loss: 0.8516 - val_mae: 0.6625 - val_rmse: 0.8200 - val_smape: 1.2534

Epoch 13/16

240/240 - 5s - 20ms/step - ia: 0.4411 - loss: 0.7330 - mae: 0.6286 - rmse: 0.8507 - smape: 1.2082 - val_ia: 0.3418 - val_loss: 0.8662 - val_mae: 0.6685 - val_rmse: 0.8305 - val_smape: 1.2599

Epoch 14/16

240/240 - 6s - 24ms/step - ia: 0.4406 - loss: 0.7352 - mae: 0.6290 - rmse: 0.8528 - smape: 1.2106 - val_ia: 0.3446 - val_loss: 0.8993 - val_mae: 0.6743 - val_rmse: 0.8393 - val_smape: 1.2463

Epoch 15/16

240/240 - 4s - 15ms/step - ia: 0.4451 - loss: 0.7270 - mae: 0.6262 - rmse: 0.8486 - smape: 1.2005 - val_ia: 0.3442 - val_loss: 0.8775 - val_mae: 0.6656 - val_rmse: 0.8255 - val_smape: 1.2555

Epoch 16/16

240/240 - 3s - 13ms/step - ia: 0.4499 - loss: 0.7194 - mae: 0.6221 - rmse: 0.8438 - smape: 1.1954 - val_ia: 0.3406 - val_loss: 0.8249 - val_mae: 0.6535 - val_rmse: 0.8130 - val_smape: 1.2388

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:24 1s/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

Epoch 1/8

 26%|██▌       | 13/50 [1:37:00<2:24:12, 233.84s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 9s - 38ms/step - ia: 0.2892 - loss: 0.9366 - mae: 0.7222 - rmse: 0.9619 - smape: 1.4406 - val_ia: 0.2872 - val_loss: 0.7957 - val_mae: 0.6649 - val_rmse: 0.8042 - val_smape: 1.3629

Epoch 2/8

240/240 - 2s - 9ms/step - ia: 0.3517 - loss: 0.8639 - mae: 0.6907 - rmse: 0.9238 - smape: 1.3457 - val_ia: 0.2996 - val_loss: 0.7799 - val_mae: 0.6565 - val_rmse: 0.7983 - val_smape: 1.3255

Epoch 3/8

240/240 - 2s - 9ms/step - ia: 0.3668 - loss: 0.8470 - mae: 0.6805 - rmse: 0.9160 - smape: 1.3229 - val_ia: 0.3022 - val_loss: 0.7736 - val_mae: 0.6540 - val_rmse: 0.7964 - val_smape: 1.3194

Epoch 4/8

240/240 - 2s - 10ms/step - ia: 0.3705 - loss: 0.8366 - mae: 0.6768 - rmse: 0.9092 - smape: 1.3188 - val_ia: 0.3082 - val_loss: 0.7684 - val_mae: 0.6500 - val_rmse: 0.7942 - val_smape: 1.3023

Epoch 5/8

240/240 - 2s - 8ms/step - ia: 0.3748 - loss: 0.8312 - mae: 0.6732 - rmse: 0.9077 - smape: 1.3121 - val_ia: 0.3097 - val_loss: 0.7673 - val_mae: 0.6481 - val_rmse: 0.7933 - val_smape: 1.2947

Epoch 6/8

240/240 - 3s - 10ms/step - ia: 0.3783 - loss: 0.8269 - mae: 0.6704 - rmse: 0.9045 - smape: 1.3029 - val_ia: 0.3137 - val_loss: 0.7638 - val_mae: 0.6487 - val_rmse: 0.7935 - val_smape: 1.3022

Epoch 7/8

240/240 - 2s - 8ms/step - ia: 0.3825 - loss: 0.8183 - mae: 0.6657 - rmse: 0.8996 - smape: 1.2984 - val_ia: 0.3121 - val_loss: 0.7558 - val_mae: 0.6432 - val_rmse: 0.7871 - val_smape: 1.2855

Epoch 8/8

240/240 - 2s - 8ms/step - ia: 0.3834 - loss: 0.8153 - mae: 0.6650 - rmse: 0.8980 - smape: 1.2956 - val_ia: 0.3175 - val_loss: 0.7638 - val_mae: 0.6457 - val_rmse: 0.7923 - val_smape: 1.2837

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 27s 202ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 28%|██▊       | 14/50 [1:37:25<1:42:33, 170.94s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 10s - 21ms/step - ia: 0.3832 - loss: 0.8315 - mae: 0.6693 - rmse: 0.9013 - smape: 1.2933 - val_ia: 0.2866 - val_loss: 0.7433 - val_mae: 0.6340 - val_rmse: 0.7607 - val_smape: 1.2298

Epoch 2/16

479/479 - 3s - 6ms/step - ia: 0.4072 - loss: 0.7928 - mae: 0.6512 - rmse: 0.8808 - smape: 1.2534 - val_ia: 0.2919 - val_loss: 0.7490 - val_mae: 0.6392 - val_rmse: 0.7657 - val_smape: 1.2547

Epoch 3/16

479/479 - 5s - 10ms/step - ia: 0.4201 - loss: 0.7774 - mae: 0.6434 - rmse: 0.8720 - smape: 1.2318 - val_ia: 0.2929 - val_loss: 0.7525 - val_mae: 0.6468 - val_rmse: 0.7736 - val_smape: 1.2944

Epoch 4/16

479/479 - 2s - 5ms/step - ia: 0.4279 - loss: 0.7634 - mae: 0.6370 - rmse: 0.8643 - smape: 1.2211 - val_ia: 0.2882 - val_loss: 0.7525 - val_mae: 0.6469 - val_rmse: 0.7727 - val_smape: 1.3116

Epoch 5/16

479/479 - 3s - 6ms/step - ia: 0.4350 - loss: 0.7507 - mae: 0.6324 - rmse: 0.8574 - smape: 1.2150 - val_ia: 0.2899 - val_loss: 0.7888 - val_mae: 0.6636 - val_rmse: 0.7942 - val_smape: 1.2923

Epoch 6/16

479/479 - 3s - 6ms/step - ia: 0.4378 - loss: 0.7450 - mae: 0.6293 - rmse: 0.8528 - smape: 1.2100 - val_ia: 0.2958 - val_loss: 0.8021 - val_mae: 0.6391 - val_rmse: 0.7792 - val_smape: 1.1945

Epoch 7/16

479/479 - 3s - 6ms/step - ia: 0.4460 - loss: 0.7362 - mae: 0.6238 - rmse: 0.8485 - smape: 1.1988 - val_ia: 0.2975 - val_loss: 0.7831 - val_mae: 0.6492 - val_rmse: 0.7866 - val_smape: 1.2421

Epoch 8/16

479/479 - 3s - 5ms/step - ia: 0.4529 - loss: 0.7202 - mae: 0.6192 - rmse: 0.8393 - smape: 1.1959 - val_ia: 0.2887 - val_loss: 0.8181 - val_mae: 0.6561 - val_rmse: 0.7957 - val_smape: 1.2769

Epoch 9/16

479/479 - 3s - 6ms/step - ia: 0.4561 - loss: 0.7059 - mae: 0.6145 - rmse: 0.8308 - smape: 1.1927 - val_ia: 0.2886 - val_loss: 0.8173 - val_mae: 0.6482 - val_rmse: 0.7910 - val_smape: 1.2268

Epoch 10/16

479/479 - 3s - 7ms/step - ia: 0.4624 - loss: 0.6997 - mae: 0.6099 - rmse: 0.8278 - smape: 1.1817 - val_ia: 0.2942 - val_loss: 0.7794 - val_mae: 0.6382 - val_rmse: 0.7739 - val_smape: 1.2381

Epoch 11/16

479/479 - 3s - 6ms/step - ia: 0.4663 - loss: 0.6903 - mae: 0.6067 - rmse: 0.8225 - smape: 1.1800 - val_ia: 0.2939 - val_loss: 0.9277 - val_mae: 0.6923 - val_rmse: 0.8492 - val_smape: 1.2567

Epoch 12/16

479/479 - 2s - 5ms/step - ia: 0.4709 - loss: 0.6765 - mae: 0.6025 - rmse: 0.8139 - smape: 1.1791 - val_ia: 0.2939 - val_loss: 0.8444 - val_mae: 0.6480 - val_rmse: 0.7936 - val_smape: 1.2077

Epoch 13/16

479/479 - 3s - 6ms/step - ia: 0.4793 - loss: 0.6631 - mae: 0.5952 - rmse: 0.8057 - smape: 1.1717 - val_ia: 0.2899 - val_loss: 0.9118 - val_mae: 0.6856 - val_rmse: 0.8337 - val_smape: 1.2840

Epoch 14/16

479/479 - 5s - 11ms/step - ia: 0.4852 - loss: 0.6485 - mae: 0.5902 - rmse: 0.7965 - smape: 1.1633 - val_ia: 0.2838 - val_loss: 0.8792 - val_mae: 0.6704 - val_rmse: 0.8095 - val_smape: 1.2935

Epoch 15/16

479/479 - 5s - 11ms/step - ia: 0.4883 - loss: 0.6411 - mae: 0.5867 - rmse: 0.7925 - smape: 1.1606 - val_ia: 0.2961 - val_loss: 0.8624 - val_mae: 0.6622 - val_rmse: 0.8002 - val_smape: 1.2686

Epoch 16/16

479/479 - 2s - 5ms/step - ia: 0.4925 - loss: 0.6317 - mae: 0.5839 - rmse: 0.7865 - smape: 1.1585 - val_ia: 0.2991 - val_loss: 0.9228 - val_mae: 0.6788 - val_rmse: 0.8361 - val_smape: 1.2464

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 26s 200ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/256

 30%|███       | 15/50 [1:38:24<1:19:57, 137.07s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

3830/3830 - 27s - 7ms/step - ia: 0.3651 - loss: 0.8438 - mae: 0.6757 - rmse: 0.8600 - smape: 1.3259 - val_ia: 0.2040 - val_loss: 0.7691 - val_mae: 0.6451 - val_rmse: 0.6858 - val_smape: 1.2576

Epoch 2/256

3830/3830 - 24s - 6ms/step - ia: 0.3900 - loss: 0.8127 - mae: 0.6586 - rmse: 0.8415 - smape: 1.2663 - val_ia: 0.2067 - val_loss: 0.7512 - val_mae: 0.6378 - val_rmse: 0.6791 - val_smape: 1.2376

Epoch 3/256

3830/3830 - 23s - 6ms/step - ia: 0.3017 - loss: 59.8488 - mae: 1.3676 - rmse: 2.3328 - smape: 1.4633 - val_ia: 0.1351 - val_loss: 12.9719 - val_mae: 2.2006 - val_rmse: 2.3506 - val_smape: 1.7685

Epoch 4/256

3830/3830 - 22s - 6ms/step - ia: 0.2399 - loss: 13.8820 - mae: 1.1050 - rmse: 1.6164 - smape: 1.6793 - val_ia: 0.1863 - val_loss: 1.0038 - val_mae: 0.7372 - val_rmse: 0.7783 - val_smape: 1.7793

Epoch 5/256

3830/3830 - 23s - 6ms/step - ia: 0.2342 - loss: 3.0600 - mae: 0.9074 - rmse: 1.2126 - smape: 1.7211 - val_ia: 0.1838 - val_loss: 0.9897 - val_mae: 0.7528 - val_rmse: 0.7964 - val_smape: 1.8126

Epoch 6/256

3830/3830 - 24s - 6ms/step - ia: 0.2342 - loss: 2.1648 - mae: 0.8300 - rmse: 1.0850 - smape: 1.7212 - val_ia: 0.1860 - val_loss: 0.9969 - val_mae: 0.7513 - val_rmse: 0.7926 - val_smape: 1.8745

Epoch 7/256

3830/3830 - 38s - 10ms/step - ia: 0.2361 - loss: 4.8647 - mae: 0.8876 - rmse: 1.2167 - smape: 1.6805 - val_ia: 0.1804 - val_loss: 0.9878 - val_mae: 0.7624 - val_rmse: 0.7995 - val_smape: 1.7845

Epoch 8/256

3830/3830 - 24s - 6ms/step - ia: 0.2219 - loss: 324.6812 - mae: 1.4252 - rmse: 2.5148 - smape: 1.6809 - val_ia: 0.1691 - val_loss: 15.7583 - val_mae: 1.3221 - val_rmse: 1.8976 - val_smape: 1.2469

Epoch 9/256

3830/3830 - 45s - 12ms/step - ia: 0.2564 - loss: 6.7186 - mae: 0.9434 - rmse: 1.4110 - smape: 1.5394 - val_ia: 0.1888 - val_loss: 0.9951 - val_mae: 0.7345 - val_rmse: 0.7772 - val_smape: 1.7898

Epoch 10/256

3830/3830 - 25s - 7ms/step - ia: 0.2330 - loss: 4.7614 - mae: 0.9008 - rmse: 1.2765 - smape: 1.7336 - val_ia: 0.1876 - val_loss: 0.9675 - val_mae: 0.7310 - val_rmse: 0.7700 - val_smape: 1.8421

Epoch 11/256

3830/3830 - 20s - 5ms/step - ia: 0.2217 - loss: 6.9332 - mae: 0.9650 - rmse: 1.3820 - smape: 1.7659 - val_ia: 0.1323 - val_loss: 34.7896 - val_mae: 1.6274 - val_rmse: 2.4656 - val_smape: 1.6606

Epoch 12/256

3830/3830 - 25s - 7ms/step - ia: 0.2219 - loss: 1.9673 - mae: 0.8363 - rmse: 1.0902 - smape: 1.7793 - val_ia: 0.1353 - val_loss: 10.7305 - val_mae: 1.4230 - val_rmse: 1.9692 - val_smape: 1.4677

Epoch 13/256

3830/3830 - 27s - 7ms/step - ia: 0.2137 - loss: 215.5380 - mae: 1.9731 - rmse: 3.6170 - smape: 1.6914 - val_ia: 0.1473 - val_loss: 37.5120 - val_mae: 1.6757 - val_rmse: 2.3199 - val_smape: 1.6841

Epoch 14/256

3830/3830 - 25s - 7ms/step - ia: 0.1932 - loss: 411.0981 - mae: 2.7071 - rmse: 5.3121 - smape: 1.6767 - val_ia: 0.1552 - val_loss: 9.2988 - val_mae: 1.1419 - val_rmse: 1.5291 - val_smape: 1.6620

Epoch 15/256

3830/3830 - 26s - 7ms/step - ia: 0.2351 - loss: 3.9004 - mae: 0.8973 - rmse: 1.2215 - smape: 1.6868 - val_ia: 0.1893 - val_loss: 0.9785 - val_mae: 0.7268 - val_rmse: 0.7648 - val_smape: 1.7383

Epoch 16/256

3830/3830 - 43s - 11ms/step - ia: 0.2073 - loss: 163.0799 - mae: 1.6355 - rmse: 2.7974 - smape: 1.7271 - val_ia: 0.1255 - val_loss: 44.4108 - val_mae: 1.6785 - val_rmse: 2.5173 - val_smape: 1.4333

Epoch 17/256

3830/3830 - 34s - 9ms/step - ia: 0.2177 - loss: 97.7352 - mae: 1.7616 - rmse: 3.0287 - smape: 1.6162 - val_ia: 0.1280 - val_loss: 26.0144 - val_mae: 1.6307 - val_rmse: 2.4240 - val_smape: 1.5580

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 52s 391ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 32%|███▏      | 16/50 [1:46:19<2:15:24, 238.95s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 58s - 15ms/step - ia: 0.3646 - loss: 0.8502 - mae: 0.6792 - rmse: 0.8627 - smape: 1.2968 - val_ia: 0.2040 - val_loss: 0.7684 - val_mae: 0.6383 - val_rmse: 0.6797 - val_smape: 1.2468

Epoch 2/256

3830/3830 - 75s - 20ms/step - ia: 0.3886 - loss: 0.8113 - mae: 0.6608 - rmse: 0.8430 - smape: 1.2663 - val_ia: 0.2049 - val_loss: 0.7662 - val_mae: 0.6399 - val_rmse: 0.6823 - val_smape: 1.2505

Epoch 3/256

3830/3830 - 44s - 12ms/step - ia: 0.3986 - loss: 0.7947 - mae: 0.6516 - rmse: 0.8340 - smape: 1.2457 - val_ia: 0.2031 - val_loss: 0.7790 - val_mae: 0.6455 - val_rmse: 0.6870 - val_smape: 1.2789

Epoch 4/256

3830/3830 - 87s - 23ms/step - ia: 0.4062 - loss: 0.7805 - mae: 0.6450 - rmse: 0.8262 - smape: 1.2322 - val_ia: 0.2013 - val_loss: 0.7764 - val_mae: 0.6523 - val_rmse: 0.6950 - val_smape: 1.2612

Epoch 5/256

3830/3830 - 50s - 13ms/step - ia: 0.4133 - loss: 0.7724 - mae: 0.6402 - rmse: 0.8204 - smape: 1.2218 - val_ia: 0.2038 - val_loss: 0.7812 - val_mae: 0.6439 - val_rmse: 0.6858 - val_smape: 1.2390

Epoch 6/256

3830/3830 - 48s - 13ms/step - ia: 0.4182 - loss: 0.7644 - mae: 0.6355 - rmse: 0.8168 - smape: 1.2171 - val_ia: 0.1965 - val_loss: 0.8025 - val_mae: 0.6793 - val_rmse: 0.7201 - val_smape: 1.3259

Epoch 7/256

3830/3830 - 82s - 21ms/step - ia: 0.4223 - loss: 0.7565 - mae: 0.6328 - rmse: 0.8138 - smape: 1.2169 - val_ia: 0.2082 - val_loss: 0.7716 - val_mae: 0.6324 - val_rmse: 0.6744 - val_smape: 1.2258

Epoch 8/256

3830/3830 - 41s - 11ms/step - ia: 0.4264 - loss: 0.7479 - mae: 0.6287 - rmse: 0.8081 - smape: 1.2091 - val_ia: 0.2036 - val_loss: 0.7996 - val_mae: 0.6499 - val_rmse: 0.6923 - val_smape: 1.2470

Epoch 9/256

3830/3830 - 50s - 13ms/step - ia: 0.4285 - loss: 0.7389 - mae: 0.6242 - rmse: 0.8022 - smape: 1.2103 - val_ia: 0.2040 - val_loss: 0.8171 - val_mae: 0.6571 - val_rmse: 0.7009 - val_smape: 1.2381

Epoch 10/256

3830/3830 - 82s - 21ms/step - ia: 0.4342 - loss: 0.7291 - mae: 0.6199 - rmse: 0.7981 - smape: 1.1969 - val_ia: 0.2012 - val_loss: 0.8016 - val_mae: 0.6660 - val_rmse: 0.7078 - val_smape: 1.3082

Epoch 11/256

3830/3830 - 51s - 13ms/step - ia: 0.4391 - loss: 0.7238 - mae: 0.6185 - rmse: 0.7929 - smape: 1.1936 - val_ia: 0.2069 - val_loss: 0.7917 - val_mae: 0.6450 - val_rmse: 0.6873 - val_smape: 1.2481

Epoch 12/256

3830/3830 - 50s - 13ms/step - ia: 0.4414 - loss: 0.7125 - mae: 0.6142 - rmse: 0.7893 - smape: 1.1925 - val_ia: 0.2020 - val_loss: 0.8169 - val_mae: 0.6586 - val_rmse: 0.7016 - val_smape: 1.2695

Epoch 13/256

3830/3830 - 49s - 13ms/step - ia: 0.4474 - loss: 0.7020 - mae: 0.6085 - rmse: 0.7816 - smape: 1.1801 - val_ia: 0.2050 - val_loss: 0.8931 - val_mae: 0.6750 - val_rmse: 0.7214 - val_smape: 1.2464

Epoch 14/256

3830/3830 - 51s - 13ms/step - ia: 0.4513 - loss: 0.6925 - mae: 0.6049 - rmse: 0.7759 - smape: 1.1811 - val_ia: 0.2026 - val_loss: 0.8526 - val_mae: 0.6685 - val_rmse: 0.7118 - val_smape: 1.3256

Epoch 15/256

3830/3830 - 51s - 13ms/step - ia: 0.4528 - loss: 0.6873 - mae: 0.6029 - rmse: 0.7730 - smape: 1.1777 - val_ia: 0.2004 - val_loss: 0.8683 - val_mae: 0.6860 - val_rmse: 0.7304 - val_smape: 1.3063

Epoch 16/256

3830/3830 - 51s - 13ms/step - ia: 0.4566 - loss: 0.6750 - mae: 0.5972 - rmse: 0.7674 - smape: 1.1652 - val_ia: 0.2055 - val_loss: 0.8992 - val_mae: 0.6812 - val_rmse: 0.7280 - val_smape: 1.2603

Epoch 17/256

3830/3830 - 49s - 13ms/step - ia: 0.4640 - loss: 0.6600 - mae: 0.5911 - rmse: 0.7589 - smape: 1.1541 - val_ia: 0.2035 - val_loss: 0.8414 - val_mae: 0.6690 - val_rmse: 0.7133 - val_smape: 1.3216

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:13 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 34%|███▍      | 17/50 [2:02:33<4:12:59, 459.99s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 30s - 124ms/step - ia: 0.1314 - loss: 1.0835 - mae: 0.7746 - rmse: 1.0334 - smape: 1.6975 - val_ia: 0.2616 - val_loss: 1.0775 - val_mae: 0.7777 - val_rmse: 0.9301 - val_smape: 1.7583

Epoch 2/16

240/240 - 3s - 13ms/step - ia: 0.1295 - loss: 1.0732 - mae: 0.7712 - rmse: 1.0282 - smape: 1.6998 - val_ia: 0.2615 - val_loss: 1.0629 - val_mae: 0.7724 - val_rmse: 0.9235 - val_smape: 1.7669

Epoch 3/16

240/240 - 5s - 22ms/step - ia: 0.1305 - loss: 1.0612 - mae: 0.7669 - rmse: 1.0220 - smape: 1.6995 - val_ia: 0.2614 - val_loss: 1.0491 - val_mae: 0.7675 - val_rmse: 0.9175 - val_smape: 1.7763

Epoch 4/16

240/240 - 3s - 13ms/step - ia: 0.1297 - loss: 1.0527 - mae: 0.7637 - rmse: 1.0190 - smape: 1.7000 - val_ia: 0.2612 - val_loss: 1.0360 - val_mae: 0.7628 - val_rmse: 0.9117 - val_smape: 1.7859

Epoch 5/16

240/240 - 4s - 18ms/step - ia: 0.1310 - loss: 1.0412 - mae: 0.7601 - rmse: 1.0149 - smape: 1.7008 - val_ia: 0.2610 - val_loss: 1.0238 - val_mae: 0.7585 - val_rmse: 0.9063 - val_smape: 1.7944

Epoch 6/16

240/240 - 4s - 18ms/step - ia: 0.1297 - loss: 1.0322 - mae: 0.7577 - rmse: 1.0090 - smape: 1.7008 - val_ia: 0.2608 - val_loss: 1.0124 - val_mae: 0.7545 - val_rmse: 0.9013 - val_smape: 1.8021

Epoch 7/16

240/240 - 3s - 14ms/step - ia: 0.1323 - loss: 1.0233 - mae: 0.7541 - rmse: 1.0051 - smape: 1.6976 - val_ia: 0.2605 - val_loss: 1.0014 - val_mae: 0.7505 - val_rmse: 0.8964 - val_smape: 1.8085

Epoch 8/16

240/240 - 5s - 22ms/step - ia: 0.1330 - loss: 1.0147 - mae: 0.7509 - rmse: 1.0015 - smape: 1.6897 - val_ia: 0.2602 - val_loss: 0.9910 - val_mae: 0.7468 - val_rmse: 0.8918 - val_smape: 1.8121

Epoch 9/16

240/240 - 5s - 22ms/step - ia: 0.1358 - loss: 1.0078 - mae: 0.7491 - rmse: 0.9969 - smape: 1.6889 - val_ia: 0.2600 - val_loss: 0.9810 - val_mae: 0.7431 - val_rmse: 0.8873 - val_smape: 1.8117

Epoch 10/16

240/240 - 4s - 15ms/step - ia: 0.1408 - loss: 0.9996 - mae: 0.7462 - rmse: 0.9936 - smape: 1.6838 - val_ia: 0.2598 - val_loss: 0.9715 - val_mae: 0.7397 - val_rmse: 0.8832 - val_smape: 1.8052

Epoch 11/16

240/240 - 5s - 22ms/step - ia: 0.1443 - loss: 0.9910 - mae: 0.7430 - rmse: 0.9895 - smape: 1.6750 - val_ia: 0.2597 - val_loss: 0.9624 - val_mae: 0.7364 - val_rmse: 0.8791 - val_smape: 1.7954

Epoch 12/16

240/240 - 5s - 20ms/step - ia: 0.1483 - loss: 0.9861 - mae: 0.7419 - rmse: 0.9865 - smape: 1.6685 - val_ia: 0.2595 - val_loss: 0.9537 - val_mae: 0.7332 - val_rmse: 0.8753 - val_smape: 1.7829

Epoch 13/16

240/240 - 3s - 14ms/step - ia: 0.1537 - loss: 0.9756 - mae: 0.7372 - rmse: 0.9804 - smape: 1.6572 - val_ia: 0.2595 - val_loss: 0.9453 - val_mae: 0.7302 - val_rmse: 0.8716 - val_smape: 1.7683

Epoch 14/16

240/240 - 3s - 14ms/step - ia: 0.1580 - loss: 0.9709 - mae: 0.7355 - rmse: 0.9801 - smape: 1.6470 - val_ia: 0.2597 - val_loss: 0.9372 - val_mae: 0.7272 - val_rmse: 0.8680 - val_smape: 1.7519

Epoch 15/16

240/240 - 5s - 22ms/step - ia: 0.1651 - loss: 0.9618 - mae: 0.7324 - rmse: 0.9746 - smape: 1.6374 - val_ia: 0.2599 - val_loss: 0.9293 - val_mae: 0.7242 - val_rmse: 0.8645 - val_smape: 1.7343

Epoch 16/16

240/240 - 5s - 21ms/step - ia: 0.1711 - loss: 0.9587 - mae: 0.7308 - rmse: 0.9731 - smape: 1.6237 - val_ia: 0.2602 - val_loss: 0.9218 - val_mae: 0.7214 - val_rmse: 0.8612 - val_smape: 1.7146

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:17 1s/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 36%|███▌      | 18/50 [2:04:12<3:07:19, 351.25s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 14s - 30ms/step - ia: 0.3741 - loss: 0.8510 - mae: 0.6817 - rmse: 0.9125 - smape: 1.3049 - val_ia: 0.2728 - val_loss: 0.7610 - val_mae: 0.6406 - val_rmse: 0.7617 - val_smape: 1.2748

Epoch 2/16

479/479 - 7s - 14ms/step - ia: 0.3839 - loss: 0.8220 - mae: 0.6673 - rmse: 0.8970 - smape: 1.2829 - val_ia: 0.2851 - val_loss: 0.7559 - val_mae: 0.6439 - val_rmse: 0.7714 - val_smape: 1.2510

Epoch 3/16

479/479 - 10s - 21ms/step - ia: 0.3947 - loss: 0.8074 - mae: 0.6592 - rmse: 0.8895 - smape: 1.2702 - val_ia: 0.2832 - val_loss: 0.7619 - val_mae: 0.6438 - val_rmse: 0.7725 - val_smape: 1.2565

Epoch 4/16

479/479 - 10s - 22ms/step - ia: 0.4044 - loss: 0.7957 - mae: 0.6530 - rmse: 0.8827 - smape: 1.2566 - val_ia: 0.2860 - val_loss: 0.7611 - val_mae: 0.6409 - val_rmse: 0.7709 - val_smape: 1.2374

Epoch 5/16

479/479 - 10s - 22ms/step - ia: 0.4123 - loss: 0.7856 - mae: 0.6469 - rmse: 0.8759 - smape: 1.2486 - val_ia: 0.2813 - val_loss: 0.7639 - val_mae: 0.6289 - val_rmse: 0.7571 - val_smape: 1.2396

Epoch 6/16

479/479 - 10s - 21ms/step - ia: 0.4188 - loss: 0.7784 - mae: 0.6437 - rmse: 0.8734 - smape: 1.2406 - val_ia: 0.2857 - val_loss: 0.7744 - val_mae: 0.6409 - val_rmse: 0.7726 - val_smape: 1.2613

Epoch 7/16

479/479 - 6s - 12ms/step - ia: 0.4233 - loss: 0.7736 - mae: 0.6400 - rmse: 0.8697 - smape: 1.2307 - val_ia: 0.2840 - val_loss: 0.7785 - val_mae: 0.6439 - val_rmse: 0.7755 - val_smape: 1.2700

Epoch 8/16

479/479 - 6s - 13ms/step - ia: 0.4285 - loss: 0.7655 - mae: 0.6367 - rmse: 0.8644 - smape: 1.2235 - val_ia: 0.2845 - val_loss: 0.7616 - val_mae: 0.6348 - val_rmse: 0.7651 - val_smape: 1.2481

Epoch 9/16

479/479 - 10s - 22ms/step - ia: 0.4324 - loss: 0.7612 - mae: 0.6345 - rmse: 0.8628 - smape: 1.2196 - val_ia: 0.2836 - val_loss: 0.7799 - val_mae: 0.6404 - val_rmse: 0.7720 - val_smape: 1.2275

Epoch 10/16

479/479 - 6s - 13ms/step - ia: 0.4351 - loss: 0.7586 - mae: 0.6329 - rmse: 0.8618 - smape: 1.2105 - val_ia: 0.2853 - val_loss: 0.7882 - val_mae: 0.6719 - val_rmse: 0.7996 - val_smape: 1.3365

Epoch 11/16

479/479 - 10s - 22ms/step - ia: 0.4384 - loss: 0.7520 - mae: 0.6304 - rmse: 0.8580 - smape: 1.2070 - val_ia: 0.2882 - val_loss: 0.8023 - val_mae: 0.6493 - val_rmse: 0.7854 - val_smape: 1.2216

Epoch 12/16

479/479 - 7s - 14ms/step - ia: 0.4404 - loss: 0.7484 - mae: 0.6289 - rmse: 0.8550 - smape: 1.2046 - val_ia: 0.2904 - val_loss: 0.8336 - val_mae: 0.6571 - val_rmse: 0.7979 - val_smape: 1.2112

Epoch 13/16

479/479 - 10s - 21ms/step - ia: 0.4460 - loss: 0.7413 - mae: 0.6253 - rmse: 0.8507 - smape: 1.1938 - val_ia: 0.2896 - val_loss: 0.8148 - val_mae: 0.6636 - val_rmse: 0.7988 - val_smape: 1.2738

Epoch 14/16

479/479 - 10s - 21ms/step - ia: 0.4511 - loss: 0.7343 - mae: 0.6230 - rmse: 0.8476 - smape: 1.1915 - val_ia: 0.2945 - val_loss: 0.8552 - val_mae: 0.6777 - val_rmse: 0.8171 - val_smape: 1.2701

Epoch 15/16

479/479 - 10s - 22ms/step - ia: 0.4518 - loss: 0.7274 - mae: 0.6201 - rmse: 0.8436 - smape: 1.1892 - val_ia: 0.2920 - val_loss: 0.8235 - val_mae: 0.6581 - val_rmse: 0.7982 - val_smape: 1.2225

Epoch 16/16

479/479 - 11s - 23ms/step - ia: 0.4540 - loss: 0.7200 - mae: 0.6181 - rmse: 0.8393 - smape: 1.1932 - val_ia: 0.2987 - val_loss: 0.8630 - val_mae: 0.6668 - val_rmse: 0.8092 - val_smape: 1.2175

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:34 699ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 38%|███▊      | 19/50 [2:06:43<2:30:31, 291.34s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 78s - 20ms/step - ia: 0.3090 - loss: 0.9498 - mae: 0.7148 - rmse: 0.9064 - smape: 1.4283 - val_ia: 0.1964 - val_loss: 0.8319 - val_mae: 0.6823 - val_rmse: 0.7227 - val_smape: 1.3121

Epoch 2/32

3830/3830 - 73s - 19ms/step - ia: 0.3628 - loss: 0.8597 - mae: 0.6820 - rmse: 0.8671 - smape: 1.2835 - val_ia: 0.2021 - val_loss: 0.7936 - val_mae: 0.6554 - val_rmse: 0.6972 - val_smape: 1.2453

Epoch 3/32

3830/3830 - 50s - 13ms/step - ia: 0.3722 - loss: 0.8432 - mae: 0.6752 - rmse: 0.8593 - smape: 1.2705 - val_ia: 0.2037 - val_loss: 0.7764 - val_mae: 0.6403 - val_rmse: 0.6820 - val_smape: 1.2125

Epoch 4/32

3830/3830 - 48s - 13ms/step - ia: 0.3758 - loss: 0.8347 - mae: 0.6727 - rmse: 0.8554 - smape: 1.2700 - val_ia: 0.2011 - val_loss: 0.7827 - val_mae: 0.6560 - val_rmse: 0.6975 - val_smape: 1.2595

Epoch 5/32

3830/3830 - 82s - 21ms/step - ia: 0.3795 - loss: 0.8296 - mae: 0.6699 - rmse: 0.8535 - smape: 1.2686 - val_ia: 0.2013 - val_loss: 0.7855 - val_mae: 0.6626 - val_rmse: 0.7037 - val_smape: 1.2739

Epoch 6/32

3830/3830 - 78s - 20ms/step - ia: 0.3833 - loss: 0.8230 - mae: 0.6667 - rmse: 0.8502 - smape: 1.2630 - val_ia: 0.2045 - val_loss: 0.7619 - val_mae: 0.6410 - val_rmse: 0.6818 - val_smape: 1.2458

Epoch 7/32

3830/3830 - 84s - 22ms/step - ia: 0.3819 - loss: 0.8176 - mae: 0.6649 - rmse: 0.8482 - smape: 1.2653 - val_ia: 0.2041 - val_loss: 0.7622 - val_mae: 0.6429 - val_rmse: 0.6839 - val_smape: 1.2374

Epoch 8/32

3830/3830 - 46s - 12ms/step - ia: 0.3860 - loss: 0.8132 - mae: 0.6636 - rmse: 0.8449 - smape: 1.2676 - val_ia: 0.2022 - val_loss: 0.7840 - val_mae: 0.6569 - val_rmse: 0.6982 - val_smape: 1.2389

Epoch 9/32

3830/3830 - 88s - 23ms/step - ia: 0.3914 - loss: 0.8057 - mae: 0.6594 - rmse: 0.8410 - smape: 1.2554 - val_ia: 0.2044 - val_loss: 0.7596 - val_mae: 0.6449 - val_rmse: 0.6854 - val_smape: 1.2656

Epoch 10/32

3830/3830 - 53s - 14ms/step - ia: 0.3935 - loss: 0.7999 - mae: 0.6576 - rmse: 0.8387 - smape: 1.2586 - val_ia: 0.2045 - val_loss: 0.7623 - val_mae: 0.6436 - val_rmse: 0.6847 - val_smape: 1.2461

Epoch 11/32

3830/3830 - 46s - 12ms/step - ia: 0.3956 - loss: 0.7990 - mae: 0.6571 - rmse: 0.8374 - smape: 1.2580 - val_ia: 0.2039 - val_loss: 0.7791 - val_mae: 0.6484 - val_rmse: 0.6900 - val_smape: 1.2322

Epoch 12/32

3830/3830 - 47s - 12ms/step - ia: 0.3969 - loss: 0.7961 - mae: 0.6540 - rmse: 0.8363 - smape: 1.2574 - val_ia: 0.2045 - val_loss: 0.7726 - val_mae: 0.6413 - val_rmse: 0.6825 - val_smape: 1.2275

Epoch 13/32

3830/3830 - 45s - 12ms/step - ia: 0.3953 - loss: 0.7955 - mae: 0.6546 - rmse: 0.8355 - smape: 1.2605 - val_ia: 0.2028 - val_loss: 0.7966 - val_mae: 0.6588 - val_rmse: 0.7008 - val_smape: 1.2288

Epoch 14/32

3830/3830 - 46s - 12ms/step - ia: 0.3972 - loss: 0.7896 - mae: 0.6529 - rmse: 0.8309 - smape: 1.2568 - val_ia: 0.2094 - val_loss: 0.7463 - val_mae: 0.6252 - val_rmse: 0.6666 - val_smape: 1.2080

Epoch 15/32

3830/3830 - 45s - 12ms/step - ia: 0.3995 - loss: 0.7873 - mae: 0.6512 - rmse: 0.8298 - smape: 1.2561 - val_ia: 0.2066 - val_loss: 0.7571 - val_mae: 0.6374 - val_rmse: 0.6785 - val_smape: 1.2513

Epoch 16/32

3830/3830 - 40s - 11ms/step - ia: 0.3994 - loss: 0.7842 - mae: 0.6509 - rmse: 0.8289 - smape: 1.2574 - val_ia: 0.2066 - val_loss: 0.7656 - val_mae: 0.6404 - val_rmse: 0.6822 - val_smape: 1.2352

Epoch 17/32

3830/3830 - 46s - 12ms/step - ia: 0.4002 - loss: 0.7824 - mae: 0.6500 - rmse: 0.8300 - smape: 1.2557 - val_ia: 0.2071 - val_loss: 0.7562 - val_mae: 0.6378 - val_rmse: 0.6791 - val_smape: 1.2498

Epoch 18/32

3830/3830 - 45s - 12ms/step - ia: 0.4020 - loss: 0.7805 - mae: 0.6487 - rmse: 0.8274 - smape: 1.2522 - val_ia: 0.2064 - val_loss: 0.7722 - val_mae: 0.6421 - val_rmse: 0.6846 - val_smape: 1.2323

Epoch 19/32

3830/3830 - 40s - 10ms/step - ia: 0.4001 - loss: 0.7809 - mae: 0.6485 - rmse: 0.8273 - smape: 1.2571 - val_ia: 0.2093 - val_loss: 0.7587 - val_mae: 0.6302 - val_rmse: 0.6731 - val_smape: 1.2034

Epoch 20/32

3830/3830 - 47s - 12ms/step - ia: 0.4014 - loss: 0.7789 - mae: 0.6478 - rmse: 0.8251 - smape: 1.2552 - val_ia: 0.2099 - val_loss: 0.7466 - val_mae: 0.6266 - val_rmse: 0.6684 - val_smape: 1.2217

Epoch 21/32

3830/3830 - 43s - 11ms/step - ia: 0.4005 - loss: 0.7772 - mae: 0.6469 - rmse: 0.8259 - smape: 1.2562 - val_ia: 0.2083 - val_loss: 0.7443 - val_mae: 0.6315 - val_rmse: 0.6728 - val_smape: 1.2487

Epoch 22/32

3830/3830 - 85s - 22ms/step - ia: 0.4054 - loss: 0.7719 - mae: 0.6442 - rmse: 0.8219 - smape: 1.2450 - val_ia: 0.2060 - val_loss: 0.7633 - val_mae: 0.6416 - val_rmse: 0.6838 - val_smape: 1.2486

Epoch 23/32

3830/3830 - 50s - 13ms/step - ia: 0.4023 - loss: 0.7735 - mae: 0.6462 - rmse: 0.8253 - smape: 1.2535 - val_ia: 0.2064 - val_loss: 0.7853 - val_mae: 0.6463 - val_rmse: 0.6898 - val_smape: 1.2332

Epoch 24/32

3830/3830 - 45s - 12ms/step - ia: 0.4043 - loss: 0.7692 - mae: 0.6447 - rmse: 0.8211 - smape: 1.2530 - val_ia: 0.2073 - val_loss: 0.7834 - val_mae: 0.6427 - val_rmse: 0.6864 - val_smape: 1.2174

Epoch 25/32

3830/3830 - 45s - 12ms/step - ia: 0.4056 - loss: 0.7695 - mae: 0.6434 - rmse: 0.8192 - smape: 1.2492 - val_ia: 0.2089 - val_loss: 0.7589 - val_mae: 0.6299 - val_rmse: 0.6723 - val_smape: 1.2224

Epoch 26/32

3830/3830 - 38s - 10ms/step - ia: 0.4054 - loss: 0.7718 - mae: 0.6439 - rmse: 0.8226 - smape: 1.2483 - val_ia: 0.2041 - val_loss: 0.7740 - val_mae: 0.6510 - val_rmse: 0.6935 - val_smape: 1.2624

Epoch 27/32

3830/3830 - 44s - 11ms/step - ia: 0.4083 - loss: 0.7681 - mae: 0.6444 - rmse: 0.8206 - smape: 1.2475 - val_ia: 0.2058 - val_loss: 0.7662 - val_mae: 0.6427 - val_rmse: 0.6852 - val_smape: 1.2565

Epoch 28/32

3830/3830 - 43s - 11ms/step - ia: 0.4079 - loss: 0.7654 - mae: 0.6427 - rmse: 0.8189 - smape: 1.2482 - val_ia: 0.2090 - val_loss: 0.7578 - val_mae: 0.6335 - val_rmse: 0.6765 - val_smape: 1.2318

Epoch 29/32

3830/3830 - 43s - 11ms/step - ia: 0.4055 - loss: 0.7638 - mae: 0.6427 - rmse: 0.8193 - smape: 1.2501 - val_ia: 0.2065 - val_loss: 0.7595 - val_mae: 0.6401 - val_rmse: 0.6824 - val_smape: 1.2506

Epoch 30/32

3830/3830 - 43s - 11ms/step - ia: 0.4065 - loss: 0.7684 - mae: 0.6445 - rmse: 0.8210 - smape: 1.2496 - val_ia: 0.2080 - val_loss: 0.7637 - val_mae: 0.6349 - val_rmse: 0.6782 - val_smape: 1.2333

Epoch 31/32

3830/3830 - 43s - 11ms/step - ia: 0.4069 - loss: 0.7649 - mae: 0.6421 - rmse: 0.8189 - smape: 1.2472 - val_ia: 0.2089 - val_loss: 0.7504 - val_mae: 0.6275 - val_rmse: 0.6699 - val_smape: 1.2386

Epoch 32/32

3830/3830 - 42s - 11ms/step - ia: 0.4082 - loss: 0.7613 - mae: 0.6411 - rmse: 0.8177 - smape: 1.2506 - val_ia: 0.2083 - val_loss: 0.7573 - val_mae: 0.6346 - val_rmse: 0.6777 - val_smape: 1.2390

Restoring model weights from the end of the best epoch: 21.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:33 2s/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 40%|████      | 20/50 [2:34:58<5:56:19, 712.63s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1915/1915 - 43s - 23ms/step - ia: 0.1778 - loss: 1.0064 - mae: 0.7557 - rmse: 0.9634 - smape: 1.8584 - val_ia: 0.2157 - val_loss: 0.9740 - val_mae: 0.7588 - val_rmse: 0.8172 - val_smape: 1.7928

Epoch 2/256

1915/1915 - 38s - 20ms/step - ia: 0.1865 - loss: 0.9726 - mae: 0.7386 - rmse: 0.9471 - smape: 1.7864 - val_ia: 0.2228 - val_loss: 0.8979 - val_mae: 0.7087 - val_rmse: 0.7675 - val_smape: 1.6848

Epoch 3/256

1915/1915 - 38s - 20ms/step - ia: 0.2969 - loss: 0.8749 - mae: 0.6945 - rmse: 0.8999 - smape: 1.4539 - val_ia: 0.2297 - val_loss: 0.8158 - val_mae: 0.6871 - val_rmse: 0.7510 - val_smape: 1.3946

Epoch 4/256

1915/1915 - 38s - 20ms/step - ia: 0.3602 - loss: 0.8444 - mae: 0.6789 - rmse: 0.8855 - smape: 1.3247 - val_ia: 0.2453 - val_loss: 0.7883 - val_mae: 0.6463 - val_rmse: 0.7135 - val_smape: 1.2621

Epoch 5/256

1915/1915 - 38s - 20ms/step - ia: 0.3616 - loss: 0.8399 - mae: 0.6770 - rmse: 0.8840 - smape: 1.3156 - val_ia: 0.2452 - val_loss: 0.7840 - val_mae: 0.6491 - val_rmse: 0.7167 - val_smape: 1.2692

Epoch 6/256

1915/1915 - 39s - 20ms/step - ia: 0.3664 - loss: 0.8372 - mae: 0.6752 - rmse: 0.8821 - smape: 1.3072 - val_ia: 0.2459 - val_loss: 0.7810 - val_mae: 0.6435 - val_rmse: 0.7107 - val_smape: 1.2534

Epoch 7/256

1915/1915 - 37s - 19ms/step - ia: 0.3685 - loss: 0.8344 - mae: 0.6741 - rmse: 0.8816 - smape: 1.3047 - val_ia: 0.2454 - val_loss: 0.7788 - val_mae: 0.6472 - val_rmse: 0.7148 - val_smape: 1.2683

Epoch 8/256

1915/1915 - 35s - 18ms/step - ia: 0.3708 - loss: 0.8322 - mae: 0.6729 - rmse: 0.8795 - smape: 1.3001 - val_ia: 0.2439 - val_loss: 0.7790 - val_mae: 0.6522 - val_rmse: 0.7193 - val_smape: 1.2891

Epoch 9/256

1915/1915 - 37s - 20ms/step - ia: 0.3706 - loss: 0.8303 - mae: 0.6724 - rmse: 0.8783 - smape: 1.3030 - val_ia: 0.2431 - val_loss: 0.7792 - val_mae: 0.6549 - val_rmse: 0.7223 - val_smape: 1.2932

Epoch 10/256

1915/1915 - 38s - 20ms/step - ia: 0.3751 - loss: 0.8286 - mae: 0.6708 - rmse: 0.8778 - smape: 1.2943 - val_ia: 0.2442 - val_loss: 0.7760 - val_mae: 0.6514 - val_rmse: 0.7189 - val_smape: 1.2852

Epoch 11/256

1915/1915 - 38s - 20ms/step - ia: 0.3710 - loss: 0.8272 - mae: 0.6707 - rmse: 0.8781 - smape: 1.2985 - val_ia: 0.2465 - val_loss: 0.7724 - val_mae: 0.6453 - val_rmse: 0.7141 - val_smape: 1.2565

Epoch 12/256

1915/1915 - 38s - 20ms/step - ia: 0.3744 - loss: 0.8254 - mae: 0.6698 - rmse: 0.8766 - smape: 1.2941 - val_ia: 0.2479 - val_loss: 0.7704 - val_mae: 0.6408 - val_rmse: 0.7102 - val_smape: 1.2402

Epoch 13/256

1915/1915 - 37s - 19ms/step - ia: 0.3786 - loss: 0.8246 - mae: 0.6689 - rmse: 0.8764 - smape: 1.2868 - val_ia: 0.2476 - val_loss: 0.7692 - val_mae: 0.6398 - val_rmse: 0.7086 - val_smape: 1.2421

Epoch 14/256

1915/1915 - 37s - 19ms/step - ia: 0.3770 - loss: 0.8234 - mae: 0.6683 - rmse: 0.8749 - smape: 1.2881 - val_ia: 0.2473 - val_loss: 0.7684 - val_mae: 0.6409 - val_rmse: 0.7096 - val_smape: 1.2483

Epoch 15/256

1915/1915 - 37s - 19ms/step - ia: 0.3786 - loss: 0.8224 - mae: 0.6681 - rmse: 0.8748 - smape: 1.2887 - val_ia: 0.2440 - val_loss: 0.7738 - val_mae: 0.6537 - val_rmse: 0.7218 - val_smape: 1.2882

Epoch 16/256

1915/1915 - 37s - 20ms/step - ia: 0.3801 - loss: 0.8215 - mae: 0.6675 - rmse: 0.8738 - smape: 1.2854 - val_ia: 0.2437 - val_loss: 0.7737 - val_mae: 0.6546 - val_rmse: 0.7224 - val_smape: 1.2947

Epoch 17/256

1915/1915 - 40s - 21ms/step - ia: 0.3795 - loss: 0.8215 - mae: 0.6672 - rmse: 0.8745 - smape: 1.2860 - val_ia: 0.2465 - val_loss: 0.7676 - val_mae: 0.6437 - val_rmse: 0.7122 - val_smape: 1.2600

Epoch 18/256

1915/1915 - 37s - 19ms/step - ia: 0.3808 - loss: 0.8198 - mae: 0.6663 - rmse: 0.8736 - smape: 1.2826 - val_ia: 0.2436 - val_loss: 0.7735 - val_mae: 0.6557 - val_rmse: 0.7235 - val_smape: 1.2966

Epoch 19/256

1915/1915 - 45s - 24ms/step - ia: 0.3818 - loss: 0.8198 - mae: 0.6663 - rmse: 0.8738 - smape: 1.2820 - val_ia: 0.2466 - val_loss: 0.7661 - val_mae: 0.6434 - val_rmse: 0.7117 - val_smape: 1.2610

Epoch 20/256

1915/1915 - 38s - 20ms/step - ia: 0.3795 - loss: 0.8192 - mae: 0.6662 - rmse: 0.8726 - smape: 1.2851 - val_ia: 0.2505 - val_loss: 0.7677 - val_mae: 0.6293 - val_rmse: 0.6990 - val_smape: 1.1950

Epoch 21/256

1915/1915 - 40s - 21ms/step - ia: 0.3840 - loss: 0.8179 - mae: 0.6651 - rmse: 0.8722 - smape: 1.2799 - val_ia: 0.2454 - val_loss: 0.7690 - val_mae: 0.6501 - val_rmse: 0.7187 - val_smape: 1.2777

Epoch 22/256

1915/1915 - 37s - 19ms/step - ia: 0.3829 - loss: 0.8171 - mae: 0.6649 - rmse: 0.8728 - smape: 1.2789 - val_ia: 0.2492 - val_loss: 0.7641 - val_mae: 0.6324 - val_rmse: 0.7018 - val_smape: 1.2164

Epoch 23/256

1915/1915 - 30s - 16ms/step - ia: 0.3825 - loss: 0.8164 - mae: 0.6644 - rmse: 0.8709 - smape: 1.2798 - val_ia: 0.2477 - val_loss: 0.7647 - val_mae: 0.6429 - val_rmse: 0.7127 - val_smape: 1.2482

Epoch 24/256

1915/1915 - 34s - 18ms/step - ia: 0.3846 - loss: 0.8167 - mae: 0.6644 - rmse: 0.8736 - smape: 1.2763 - val_ia: 0.2469 - val_loss: 0.7652 - val_mae: 0.6455 - val_rmse: 0.7148 - val_smape: 1.2601

Epoch 25/256

1915/1915 - 41s - 22ms/step - ia: 0.3837 - loss: 0.8159 - mae: 0.6642 - rmse: 0.8718 - smape: 1.2766 - val_ia: 0.2463 - val_loss: 0.7674 - val_mae: 0.6487 - val_rmse: 0.7182 - val_smape: 1.2670

Epoch 26/256

1915/1915 - 40s - 21ms/step - ia: 0.3883 - loss: 0.8155 - mae: 0.6638 - rmse: 0.8715 - smape: 1.2720 - val_ia: 0.2472 - val_loss: 0.7619 - val_mae: 0.6411 - val_rmse: 0.7098 - val_smape: 1.2542

Epoch 27/256

1915/1915 - 40s - 21ms/step - ia: 0.3834 - loss: 0.8147 - mae: 0.6637 - rmse: 0.8710 - smape: 1.2781 - val_ia: 0.2485 - val_loss: 0.7604 - val_mae: 0.6363 - val_rmse: 0.7058 - val_smape: 1.2329

Epoch 28/256

1915/1915 - 39s - 20ms/step - ia: 0.3880 - loss: 0.8146 - mae: 0.6630 - rmse: 0.8712 - smape: 1.2711 - val_ia: 0.2469 - val_loss: 0.7632 - val_mae: 0.6445 - val_rmse: 0.7133 - val_smape: 1.2639

Epoch 29/256

1915/1915 - 39s - 20ms/step - ia: 0.3862 - loss: 0.8138 - mae: 0.6632 - rmse: 0.8692 - smape: 1.2749 - val_ia: 0.2477 - val_loss: 0.7613 - val_mae: 0.6410 - val_rmse: 0.7104 - val_smape: 1.2491

Epoch 30/256

1915/1915 - 39s - 20ms/step - ia: 0.3876 - loss: 0.8136 - mae: 0.6628 - rmse: 0.8699 - smape: 1.2723 - val_ia: 0.2490 - val_loss: 0.7581 - val_mae: 0.6332 - val_rmse: 0.7025 - val_smape: 1.2245

Epoch 31/256

1915/1915 - 39s - 20ms/step - ia: 0.3875 - loss: 0.8133 - mae: 0.6630 - rmse: 0.8701 - smape: 1.2752 - val_ia: 0.2456 - val_loss: 0.7669 - val_mae: 0.6511 - val_rmse: 0.7200 - val_smape: 1.2788

Epoch 32/256

1915/1915 - 41s - 21ms/step - ia: 0.3890 - loss: 0.8128 - mae: 0.6622 - rmse: 0.8687 - smape: 1.2712 - val_ia: 0.2494 - val_loss: 0.7582 - val_mae: 0.6316 - val_rmse: 0.7011 - val_smape: 1.2177

Epoch 33/256

1915/1915 - 40s - 21ms/step - ia: 0.3885 - loss: 0.8125 - mae: 0.6617 - rmse: 0.8677 - smape: 1.2704 - val_ia: 0.2458 - val_loss: 0.7653 - val_mae: 0.6509 - val_rmse: 0.7195 - val_smape: 1.2817

Epoch 34/256

1915/1915 - 38s - 20ms/step - ia: 0.3876 - loss: 0.8117 - mae: 0.6621 - rmse: 0.8699 - smape: 1.2721 - val_ia: 0.2502 - val_loss: 0.7571 - val_mae: 0.6297 - val_rmse: 0.6995 - val_smape: 1.2084

Epoch 35/256

1915/1915 - 39s - 20ms/step - ia: 0.3892 - loss: 0.8115 - mae: 0.6618 - rmse: 0.8685 - smape: 1.2714 - val_ia: 0.2501 - val_loss: 0.7567 - val_mae: 0.6307 - val_rmse: 0.7007 - val_smape: 1.2122

Epoch 36/256

1915/1915 - 42s - 22ms/step - ia: 0.3889 - loss: 0.8113 - mae: 0.6613 - rmse: 0.8683 - smape: 1.2676 - val_ia: 0.2479 - val_loss: 0.7606 - val_mae: 0.6446 - val_rmse: 0.7141 - val_smape: 1.2566

Epoch 37/256

1915/1915 - 44s - 23ms/step - ia: 0.3905 - loss: 0.8109 - mae: 0.6617 - rmse: 0.8693 - smape: 1.2680 - val_ia: 0.2485 - val_loss: 0.7559 - val_mae: 0.6348 - val_rmse: 0.7041 - val_smape: 1.2327

Epoch 38/256

1915/1915 - 79s - 41ms/step - ia: 0.3882 - loss: 0.8104 - mae: 0.6612 - rmse: 0.8674 - smape: 1.2689 - val_ia: 0.2499 - val_loss: 0.7550 - val_mae: 0.6306 - val_rmse: 0.7004 - val_smape: 1.2143

Epoch 39/256

1915/1915 - 41s - 21ms/step - ia: 0.3898 - loss: 0.8097 - mae: 0.6608 - rmse: 0.8675 - smape: 1.2671 - val_ia: 0.2493 - val_loss: 0.7546 - val_mae: 0.6330 - val_rmse: 0.7028 - val_smape: 1.2235

Epoch 40/256

1915/1915 - 39s - 20ms/step - ia: 0.3906 - loss: 0.8100 - mae: 0.6606 - rmse: 0.8671 - smape: 1.2666 - val_ia: 0.2468 - val_loss: 0.7611 - val_mae: 0.6469 - val_rmse: 0.7160 - val_smape: 1.2690

Epoch 41/256

1915/1915 - 39s - 21ms/step - ia: 0.3917 - loss: 0.8094 - mae: 0.6607 - rmse: 0.8670 - smape: 1.2669 - val_ia: 0.2512 - val_loss: 0.7551 - val_mae: 0.6267 - val_rmse: 0.6967 - val_smape: 1.1963

Epoch 42/256

1915/1915 - 41s - 22ms/step - ia: 0.3897 - loss: 0.8093 - mae: 0.6607 - rmse: 0.8683 - smape: 1.2674 - val_ia: 0.2482 - val_loss: 0.7571 - val_mae: 0.6414 - val_rmse: 0.7108 - val_smape: 1.2515

Epoch 43/256

1915/1915 - 42s - 22ms/step - ia: 0.3928 - loss: 0.8083 - mae: 0.6602 - rmse: 0.8657 - smape: 1.2646 - val_ia: 0.2483 - val_loss: 0.7550 - val_mae: 0.6379 - val_rmse: 0.7070 - val_smape: 1.2455

Epoch 44/256

1915/1915 - 40s - 21ms/step - ia: 0.3913 - loss: 0.8081 - mae: 0.6604 - rmse: 0.8665 - smape: 1.2707 - val_ia: 0.2490 - val_loss: 0.7542 - val_mae: 0.6369 - val_rmse: 0.7069 - val_smape: 1.2342

Epoch 45/256

1915/1915 - 36s - 19ms/step - ia: 0.3938 - loss: 0.8080 - mae: 0.6598 - rmse: 0.8671 - smape: 1.2625 - val_ia: 0.2487 - val_loss: 0.7526 - val_mae: 0.6361 - val_rmse: 0.7053 - val_smape: 1.2386

Epoch 46/256

1915/1915 - 44s - 23ms/step - ia: 0.3901 - loss: 0.8075 - mae: 0.6599 - rmse: 0.8675 - smape: 1.2672 - val_ia: 0.2485 - val_loss: 0.7566 - val_mae: 0.6415 - val_rmse: 0.7114 - val_smape: 1.2491

Epoch 47/256

1915/1915 - 37s - 19ms/step - ia: 0.3954 - loss: 0.8074 - mae: 0.6595 - rmse: 0.8667 - smape: 1.2633 - val_ia: 0.2486 - val_loss: 0.7535 - val_mae: 0.6377 - val_rmse: 0.7071 - val_smape: 1.2432

Epoch 48/256

1915/1915 - 38s - 20ms/step - ia: 0.3907 - loss: 0.8068 - mae: 0.6594 - rmse: 0.8657 - smape: 1.2659 - val_ia: 0.2472 - val_loss: 0.7590 - val_mae: 0.6457 - val_rmse: 0.7152 - val_smape: 1.2640

Epoch 49/256

1915/1915 - 36s - 19ms/step - ia: 0.3939 - loss: 0.8064 - mae: 0.6590 - rmse: 0.8671 - smape: 1.2635 - val_ia: 0.2489 - val_loss: 0.7524 - val_mae: 0.6363 - val_rmse: 0.7059 - val_smape: 1.2369

Epoch 50/256

1915/1915 - 46s - 24ms/step - ia: 0.3964 - loss: 0.8066 - mae: 0.6589 - rmse: 0.8664 - smape: 1.2607 - val_ia: 0.2467 - val_loss: 0.7587 - val_mae: 0.6467 - val_rmse: 0.7158 - val_smape: 1.2706

Epoch 51/256

1915/1915 - 36s - 19ms/step - ia: 0.3949 - loss: 0.8060 - mae: 0.6588 - rmse: 0.8663 - smape: 1.2618 - val_ia: 0.2449 - val_loss: 0.7657 - val_mae: 0.6553 - val_rmse: 0.7242 - val_smape: 1.2912

Epoch 52/256

1915/1915 - 45s - 23ms/step - ia: 0.3934 - loss: 0.8055 - mae: 0.6586 - rmse: 0.8659 - smape: 1.2626 - val_ia: 0.2484 - val_loss: 0.7554 - val_mae: 0.6427 - val_rmse: 0.7124 - val_smape: 1.2546

Epoch 53/256

1915/1915 - 40s - 21ms/step - ia: 0.3953 - loss: 0.8053 - mae: 0.6583 - rmse: 0.8655 - smape: 1.2599 - val_ia: 0.2493 - val_loss: 0.7506 - val_mae: 0.6335 - val_rmse: 0.7031 - val_smape: 1.2301

Epoch 54/256

1915/1915 - 41s - 21ms/step - ia: 0.3959 - loss: 0.8047 - mae: 0.6579 - rmse: 0.8655 - smape: 1.2609 - val_ia: 0.2492 - val_loss: 0.7493 - val_mae: 0.6325 - val_rmse: 0.7018 - val_smape: 1.2295

Epoch 55/256

1915/1915 - 39s - 20ms/step - ia: 0.3950 - loss: 0.8044 - mae: 0.6578 - rmse: 0.8652 - smape: 1.2626 - val_ia: 0.2488 - val_loss: 0.7527 - val_mae: 0.6401 - val_rmse: 0.7098 - val_smape: 1.2486

Epoch 56/256

1915/1915 - 41s - 22ms/step - ia: 0.3962 - loss: 0.8037 - mae: 0.6577 - rmse: 0.8651 - smape: 1.2595 - val_ia: 0.2482 - val_loss: 0.7529 - val_mae: 0.6408 - val_rmse: 0.7102 - val_smape: 1.2543

Epoch 57/256

1915/1915 - 41s - 21ms/step - ia: 0.3946 - loss: 0.8042 - mae: 0.6581 - rmse: 0.8642 - smape: 1.2620 - val_ia: 0.2496 - val_loss: 0.7507 - val_mae: 0.6359 - val_rmse: 0.7061 - val_smape: 1.2338

Epoch 58/256

1915/1915 - 39s - 20ms/step - ia: 0.3956 - loss: 0.8037 - mae: 0.6575 - rmse: 0.8645 - smape: 1.2591 - val_ia: 0.2499 - val_loss: 0.7494 - val_mae: 0.6341 - val_rmse: 0.7042 - val_smape: 1.2285

Epoch 59/256

1915/1915 - 40s - 21ms/step - ia: 0.3970 - loss: 0.8033 - mae: 0.6572 - rmse: 0.8646 - smape: 1.2587 - val_ia: 0.2464 - val_loss: 0.7590 - val_mae: 0.6490 - val_rmse: 0.7183 - val_smape: 1.2744

Epoch 60/256

1915/1915 - 39s - 20ms/step - ia: 0.3970 - loss: 0.8027 - mae: 0.6571 - rmse: 0.8628 - smape: 1.2588 - val_ia: 0.2519 - val_loss: 0.7482 - val_mae: 0.6247 - val_rmse: 0.6947 - val_smape: 1.1964

Epoch 61/256

1915/1915 - 39s - 20ms/step - ia: 0.3961 - loss: 0.8026 - mae: 0.6568 - rmse: 0.8641 - smape: 1.2585 - val_ia: 0.2491 - val_loss: 0.7490 - val_mae: 0.6360 - val_rmse: 0.7054 - val_smape: 1.2407

Epoch 62/256

1915/1915 - 41s - 21ms/step - ia: 0.3963 - loss: 0.8023 - mae: 0.6568 - rmse: 0.8632 - smape: 1.2578 - val_ia: 0.2450 - val_loss: 0.7607 - val_mae: 0.6526 - val_rmse: 0.7213 - val_smape: 1.2891

Epoch 63/256

1915/1915 - 39s - 20ms/step - ia: 0.3955 - loss: 0.8029 - mae: 0.6576 - rmse: 0.8650 - smape: 1.2617 - val_ia: 0.2452 - val_loss: 0.7647 - val_mae: 0.6552 - val_rmse: 0.7246 - val_smape: 1.2855

Epoch 64/256

1915/1915 - 46s - 24ms/step - ia: 0.3987 - loss: 0.8018 - mae: 0.6564 - rmse: 0.8638 - smape: 1.2560 - val_ia: 0.2475 - val_loss: 0.7533 - val_mae: 0.6439 - val_rmse: 0.7133 - val_smape: 1.2638

Epoch 65/256

1915/1915 - 78s - 41ms/step - ia: 0.3989 - loss: 0.8014 - mae: 0.6565 - rmse: 0.8637 - smape: 1.2559 - val_ia: 0.2540 - val_loss: 0.7528 - val_mae: 0.6196 - val_rmse: 0.6903 - val_smape: 1.1669

Epoch 66/256

1915/1915 - 38s - 20ms/step - ia: 0.3981 - loss: 0.8016 - mae: 0.6564 - rmse: 0.8646 - smape: 1.2576 - val_ia: 0.2499 - val_loss: 0.7464 - val_mae: 0.6325 - val_rmse: 0.7022 - val_smape: 1.2304

Epoch 67/256

1915/1915 - 40s - 21ms/step - ia: 0.3981 - loss: 0.8005 - mae: 0.6564 - rmse: 0.8633 - smape: 1.2593 - val_ia: 0.2506 - val_loss: 0.7473 - val_mae: 0.6327 - val_rmse: 0.7032 - val_smape: 1.2239

Epoch 68/256

1915/1915 - 40s - 21ms/step - ia: 0.4005 - loss: 0.8003 - mae: 0.6558 - rmse: 0.8622 - smape: 1.2542 - val_ia: 0.2499 - val_loss: 0.7462 - val_mae: 0.6339 - val_rmse: 0.7036 - val_smape: 1.2336

Epoch 69/256

1915/1915 - 41s - 21ms/step - ia: 0.3981 - loss: 0.8005 - mae: 0.6557 - rmse: 0.8639 - smape: 1.2557 - val_ia: 0.2512 - val_loss: 0.7453 - val_mae: 0.6288 - val_rmse: 0.6992 - val_smape: 1.2153

Epoch 70/256

1915/1915 - 40s - 21ms/step - ia: 0.3975 - loss: 0.7993 - mae: 0.6555 - rmse: 0.8616 - smape: 1.2586 - val_ia: 0.2503 - val_loss: 0.7475 - val_mae: 0.6352 - val_rmse: 0.7058 - val_smape: 1.2317

Epoch 71/256

1915/1915 - 40s - 21ms/step - ia: 0.3993 - loss: 0.7997 - mae: 0.6555 - rmse: 0.8626 - smape: 1.2554 - val_ia: 0.2510 - val_loss: 0.7456 - val_mae: 0.6311 - val_rmse: 0.7017 - val_smape: 1.2210

Epoch 72/256

1915/1915 - 39s - 21ms/step - ia: 0.3991 - loss: 0.7994 - mae: 0.6554 - rmse: 0.8630 - smape: 1.2571 - val_ia: 0.2502 - val_loss: 0.7475 - val_mae: 0.6349 - val_rmse: 0.7055 - val_smape: 1.2310

Epoch 73/256

1915/1915 - 40s - 21ms/step - ia: 0.4003 - loss: 0.7991 - mae: 0.6550 - rmse: 0.8621 - smape: 1.2539 - val_ia: 0.2492 - val_loss: 0.7478 - val_mae: 0.6354 - val_rmse: 0.7054 - val_smape: 1.2385

Epoch 74/256

1915/1915 - 40s - 21ms/step - ia: 0.3999 - loss: 0.7986 - mae: 0.6550 - rmse: 0.8614 - smape: 1.2562 - val_ia: 0.2430 - val_loss: 0.7698 - val_mae: 0.6613 - val_rmse: 0.7306 - val_smape: 1.3027

Epoch 75/256

1915/1915 - 40s - 21ms/step - ia: 0.3986 - loss: 0.7978 - mae: 0.6547 - rmse: 0.8619 - smape: 1.2560 - val_ia: 0.2478 - val_loss: 0.7530 - val_mae: 0.6428 - val_rmse: 0.7131 - val_smape: 1.2551

Epoch 76/256

1915/1915 - 40s - 21ms/step - ia: 0.4027 - loss: 0.7982 - mae: 0.6545 - rmse: 0.8612 - smape: 1.2521 - val_ia: 0.2505 - val_loss: 0.7441 - val_mae: 0.6308 - val_rmse: 0.7008 - val_smape: 1.2263

Epoch 77/256

1915/1915 - 39s - 21ms/step - ia: 0.3992 - loss: 0.7979 - mae: 0.6546 - rmse: 0.8619 - smape: 1.2552 - val_ia: 0.2506 - val_loss: 0.7445 - val_mae: 0.6308 - val_rmse: 0.7011 - val_smape: 1.2250

Epoch 78/256

1915/1915 - 39s - 21ms/step - ia: 0.4020 - loss: 0.7973 - mae: 0.6542 - rmse: 0.8602 - smape: 1.2528 - val_ia: 0.2497 - val_loss: 0.7434 - val_mae: 0.6323 - val_rmse: 0.7016 - val_smape: 1.2361

Epoch 79/256

1915/1915 - 40s - 21ms/step - ia: 0.4004 - loss: 0.7966 - mae: 0.6541 - rmse: 0.8612 - smape: 1.2547 - val_ia: 0.2488 - val_loss: 0.7474 - val_mae: 0.6375 - val_rmse: 0.7075 - val_smape: 1.2458

Epoch 80/256

1915/1915 - 40s - 21ms/step - ia: 0.4021 - loss: 0.7966 - mae: 0.6538 - rmse: 0.8613 - smape: 1.2506 - val_ia: 0.2501 - val_loss: 0.7436 - val_mae: 0.6330 - val_rmse: 0.7029 - val_smape: 1.2344

Epoch 81/256

1915/1915 - 39s - 20ms/step - ia: 0.4022 - loss: 0.7963 - mae: 0.6537 - rmse: 0.8608 - smape: 1.2532 - val_ia: 0.2507 - val_loss: 0.7419 - val_mae: 0.6308 - val_rmse: 0.7007 - val_smape: 1.2289

Epoch 82/256

1915/1915 - 38s - 20ms/step - ia: 0.4009 - loss: 0.7959 - mae: 0.6537 - rmse: 0.8607 - smape: 1.2542 - val_ia: 0.2507 - val_loss: 0.7434 - val_mae: 0.6320 - val_rmse: 0.7024 - val_smape: 1.2288

Epoch 83/256

1915/1915 - 33s - 17ms/step - ia: 0.4029 - loss: 0.7959 - mae: 0.6536 - rmse: 0.8613 - smape: 1.2535 - val_ia: 0.2526 - val_loss: 0.7411 - val_mae: 0.6263 - val_rmse: 0.6971 - val_smape: 1.2092

Epoch 84/256

1915/1915 - 41s - 21ms/step - ia: 0.4031 - loss: 0.7953 - mae: 0.6533 - rmse: 0.8598 - smape: 1.2526 - val_ia: 0.2508 - val_loss: 0.7430 - val_mae: 0.6323 - val_rmse: 0.7028 - val_smape: 1.2291

Epoch 85/256

1915/1915 - 34s - 18ms/step - ia: 0.4029 - loss: 0.7951 - mae: 0.6533 - rmse: 0.8602 - smape: 1.2527 - val_ia: 0.2489 - val_loss: 0.7465 - val_mae: 0.6373 - val_rmse: 0.7074 - val_smape: 1.2458

Epoch 86/256

1915/1915 - 33s - 17ms/step - ia: 0.4021 - loss: 0.7950 - mae: 0.6533 - rmse: 0.8599 - smape: 1.2536 - val_ia: 0.2499 - val_loss: 0.7465 - val_mae: 0.6351 - val_rmse: 0.7060 - val_smape: 1.2346

Epoch 87/256

1915/1915 - 33s - 17ms/step - ia: 0.4049 - loss: 0.7944 - mae: 0.6526 - rmse: 0.8589 - smape: 1.2500 - val_ia: 0.2471 - val_loss: 0.7512 - val_mae: 0.6434 - val_rmse: 0.7133 - val_smape: 1.2628

Epoch 88/256

1915/1915 - 35s - 18ms/step - ia: 0.4035 - loss: 0.7943 - mae: 0.6529 - rmse: 0.8590 - smape: 1.2520 - val_ia: 0.2505 - val_loss: 0.7435 - val_mae: 0.6325 - val_rmse: 0.7030 - val_smape: 1.2308

Epoch 89/256

1915/1915 - 34s - 18ms/step - ia: 0.4040 - loss: 0.7936 - mae: 0.6525 - rmse: 0.8607 - smape: 1.2495 - val_ia: 0.2539 - val_loss: 0.7389 - val_mae: 0.6233 - val_rmse: 0.6943 - val_smape: 1.1992

Epoch 90/256

1915/1915 - 42s - 22ms/step - ia: 0.4027 - loss: 0.7936 - mae: 0.6523 - rmse: 0.8599 - smape: 1.2505 - val_ia: 0.2508 - val_loss: 0.7424 - val_mae: 0.6318 - val_rmse: 0.7024 - val_smape: 1.2295

Epoch 91/256

1915/1915 - 40s - 21ms/step - ia: 0.4045 - loss: 0.7935 - mae: 0.6522 - rmse: 0.8586 - smape: 1.2513 - val_ia: 0.2520 - val_loss: 0.7408 - val_mae: 0.6291 - val_rmse: 0.6999 - val_smape: 1.2195

Epoch 92/256

1915/1915 - 34s - 18ms/step - ia: 0.4052 - loss: 0.7924 - mae: 0.6517 - rmse: 0.8575 - smape: 1.2506 - val_ia: 0.2534 - val_loss: 0.7402 - val_mae: 0.6258 - val_rmse: 0.6971 - val_smape: 1.2060

Epoch 93/256

1915/1915 - 41s - 21ms/step - ia: 0.4051 - loss: 0.7928 - mae: 0.6518 - rmse: 0.8574 - smape: 1.2499 - val_ia: 0.2507 - val_loss: 0.7425 - val_mae: 0.6332 - val_rmse: 0.7038 - val_smape: 1.2335

Epoch 94/256

1915/1915 - 35s - 18ms/step - ia: 0.4059 - loss: 0.7920 - mae: 0.6513 - rmse: 0.8582 - smape: 1.2484 - val_ia: 0.2528 - val_loss: 0.7398 - val_mae: 0.6260 - val_rmse: 0.6967 - val_smape: 1.2115

Epoch 95/256

1915/1915 - 34s - 17ms/step - ia: 0.4058 - loss: 0.7923 - mae: 0.6512 - rmse: 0.8582 - smape: 1.2486 - val_ia: 0.2486 - val_loss: 0.7451 - val_mae: 0.6382 - val_rmse: 0.7081 - val_smape: 1.2519

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1915/1915 - 60s - 32ms/step - ia: 0.1747 - loss: 1.0193 - mae: 0.7642 - rmse: 0.9702 - smape: 1.8632 - val_ia: 0.2211 - val_loss: 0.9653 - val_mae: 0.7291 - val_rmse: 0.7892 - val_smape: 1.8286

Epoch 2/256

1915/1915 - 46s - 24ms/step - ia: 0.1738 - loss: 0.9986 - mae: 0.7490 - rmse: 0.9596 - smape: 1.8697 - val_ia: 0.2206 - val_loss: 0.9592 - val_mae: 0.7311 - val_rmse: 0.7908 - val_smape: 1.9042

Epoch 3/256

1915/1915 - 46s - 24ms/step - ia: 0.1967 - loss: 0.9646 - mae: 0.7352 - rmse: 0.9418 - smape: 1.7526 - val_ia: 0.2269 - val_loss: 0.8621 - val_mae: 0.6864 - val_rmse: 0.7463 - val_smape: 1.5066

Epoch 4/256

1915/1915 - 81s - 42ms/step - ia: 0.3207 - loss: 0.8684 - mae: 0.6907 - rmse: 0.8973 - smape: 1.3781 - val_ia: 0.2402 - val_loss: 0.8052 - val_mae: 0.6555 - val_rmse: 0.7221 - val_smape: 1.2733

Epoch 5/256

1915/1915 - 50s - 26ms/step - ia: 0.3561 - loss: 0.8547 - mae: 0.6830 - rmse: 0.8912 - smape: 1.3143 - val_ia: 0.2394 - val_loss: 0.7993 - val_mae: 0.6604 - val_rmse: 0.7266 - val_smape: 1.2916

Epoch 6/256

1915/1915 - 47s - 24ms/step - ia: 0.3581 - loss: 0.8497 - mae: 0.6808 - rmse: 0.8902 - smape: 1.3102 - val_ia: 0.2416 - val_loss: 0.7926 - val_mae: 0.6552 - val_rmse: 0.7216 - val_smape: 1.2797

Epoch 7/256

1915/1915 - 46s - 24ms/step - ia: 0.3602 - loss: 0.8452 - mae: 0.6791 - rmse: 0.8871 - smape: 1.3081 - val_ia: 0.2395 - val_loss: 0.7917 - val_mae: 0.6616 - val_rmse: 0.7280 - val_smape: 1.3005

Epoch 8/256

1915/1915 - 45s - 24ms/step - ia: 0.3646 - loss: 0.8409 - mae: 0.6766 - rmse: 0.8846 - smape: 1.3008 - val_ia: 0.2361 - val_loss: 0.7953 - val_mae: 0.6703 - val_rmse: 0.7362 - val_smape: 1.3271

Epoch 9/256

1915/1915 - 45s - 23ms/step - ia: 0.3667 - loss: 0.8370 - mae: 0.6754 - rmse: 0.8825 - smape: 1.3003 - val_ia: 0.2443 - val_loss: 0.7801 - val_mae: 0.6489 - val_rmse: 0.7165 - val_smape: 1.2620

Epoch 10/256

1915/1915 - 46s - 24ms/step - ia: 0.3703 - loss: 0.8348 - mae: 0.6739 - rmse: 0.8808 - smape: 1.2957 - val_ia: 0.2449 - val_loss: 0.7767 - val_mae: 0.6464 - val_rmse: 0.7141 - val_smape: 1.2571

Epoch 11/256

1915/1915 - 48s - 25ms/step - ia: 0.3708 - loss: 0.8321 - mae: 0.6727 - rmse: 0.8812 - smape: 1.2943 - val_ia: 0.2405 - val_loss: 0.7833 - val_mae: 0.6612 - val_rmse: 0.7285 - val_smape: 1.3005

Epoch 12/256

1915/1915 - 41s - 22ms/step - ia: 0.3747 - loss: 0.8299 - mae: 0.6716 - rmse: 0.8784 - smape: 1.2898 - val_ia: 0.2433 - val_loss: 0.7769 - val_mae: 0.6536 - val_rmse: 0.7214 - val_smape: 1.2818

Epoch 13/256

1915/1915 - 46s - 24ms/step - ia: 0.3746 - loss: 0.8278 - mae: 0.6703 - rmse: 0.8786 - smape: 1.2877 - val_ia: 0.2459 - val_loss: 0.7711 - val_mae: 0.6442 - val_rmse: 0.7128 - val_smape: 1.2502

Epoch 14/256

1915/1915 - 43s - 23ms/step - ia: 0.3760 - loss: 0.8266 - mae: 0.6697 - rmse: 0.8782 - smape: 1.2838 - val_ia: 0.2465 - val_loss: 0.7696 - val_mae: 0.6410 - val_rmse: 0.7097 - val_smape: 1.2412

Epoch 15/256

1915/1915 - 45s - 23ms/step - ia: 0.3767 - loss: 0.8255 - mae: 0.6689 - rmse: 0.8770 - smape: 1.2816 - val_ia: 0.2438 - val_loss: 0.7735 - val_mae: 0.6525 - val_rmse: 0.7205 - val_smape: 1.2803

Epoch 16/256

1915/1915 - 46s - 24ms/step - ia: 0.3778 - loss: 0.8242 - mae: 0.6684 - rmse: 0.8747 - smape: 1.2827 - val_ia: 0.2471 - val_loss: 0.7675 - val_mae: 0.6391 - val_rmse: 0.7082 - val_smape: 1.2347

Epoch 17/256

1915/1915 - 78s - 41ms/step - ia: 0.3806 - loss: 0.8234 - mae: 0.6680 - rmse: 0.8761 - smape: 1.2810 - val_ia: 0.2463 - val_loss: 0.7676 - val_mae: 0.6435 - val_rmse: 0.7123 - val_smape: 1.2520

Epoch 18/256

1915/1915 - 40s - 21ms/step - ia: 0.3813 - loss: 0.8217 - mae: 0.6671 - rmse: 0.8746 - smape: 1.2770 - val_ia: 0.2470 - val_loss: 0.7664 - val_mae: 0.6379 - val_rmse: 0.7065 - val_smape: 1.2365

Epoch 19/256

1915/1915 - 46s - 24ms/step - ia: 0.3805 - loss: 0.8205 - mae: 0.6668 - rmse: 0.8748 - smape: 1.2784 - val_ia: 0.2450 - val_loss: 0.7695 - val_mae: 0.6494 - val_rmse: 0.7181 - val_smape: 1.2709

Epoch 20/256

1915/1915 - 40s - 21ms/step - ia: 0.3811 - loss: 0.8196 - mae: 0.6661 - rmse: 0.8736 - smape: 1.2768 - val_ia: 0.2427 - val_loss: 0.7768 - val_mae: 0.6592 - val_rmse: 0.7280 - val_smape: 1.2908

Epoch 21/256

1915/1915 - 45s - 23ms/step - ia: 0.3841 - loss: 0.8193 - mae: 0.6660 - rmse: 0.8727 - smape: 1.2744 - val_ia: 0.2469 - val_loss: 0.7653 - val_mae: 0.6428 - val_rmse: 0.7122 - val_smape: 1.2467

Epoch 22/256

1915/1915 - 72s - 38ms/step - ia: 0.3856 - loss: 0.8185 - mae: 0.6653 - rmse: 0.8730 - smape: 1.2719 - val_ia: 0.2467 - val_loss: 0.7642 - val_mae: 0.6421 - val_rmse: 0.7109 - val_smape: 1.2506

Epoch 23/256

1915/1915 - 44s - 23ms/step - ia: 0.3826 - loss: 0.8177 - mae: 0.6653 - rmse: 0.8729 - smape: 1.2752 - val_ia: 0.2497 - val_loss: 0.7661 - val_mae: 0.6293 - val_rmse: 0.6997 - val_smape: 1.1882

Epoch 24/256

1915/1915 - 46s - 24ms/step - ia: 0.3882 - loss: 0.8173 - mae: 0.6641 - rmse: 0.8725 - smape: 1.2685 - val_ia: 0.2465 - val_loss: 0.7641 - val_mae: 0.6441 - val_rmse: 0.7129 - val_smape: 1.2570

Epoch 25/256

1915/1915 - 46s - 24ms/step - ia: 0.3845 - loss: 0.8165 - mae: 0.6651 - rmse: 0.8735 - smape: 1.2743 - val_ia: 0.2460 - val_loss: 0.7669 - val_mae: 0.6480 - val_rmse: 0.7173 - val_smape: 1.2633

Epoch 26/256

1915/1915 - 45s - 24ms/step - ia: 0.3866 - loss: 0.8158 - mae: 0.6644 - rmse: 0.8718 - smape: 1.2710 - val_ia: 0.2460 - val_loss: 0.7671 - val_mae: 0.6482 - val_rmse: 0.7176 - val_smape: 1.2634

Epoch 27/256

1915/1915 - 43s - 22ms/step - ia: 0.3872 - loss: 0.8159 - mae: 0.6640 - rmse: 0.8715 - smape: 1.2703 - val_ia: 0.2474 - val_loss: 0.7623 - val_mae: 0.6411 - val_rmse: 0.7107 - val_smape: 1.2426

Epoch 28/256

1915/1915 - 44s - 23ms/step - ia: 0.3875 - loss: 0.8150 - mae: 0.6635 - rmse: 0.8701 - smape: 1.2694 - val_ia: 0.2455 - val_loss: 0.7682 - val_mae: 0.6518 - val_rmse: 0.7209 - val_smape: 1.2746

Epoch 29/256

1915/1915 - 46s - 24ms/step - ia: 0.3876 - loss: 0.8140 - mae: 0.6630 - rmse: 0.8705 - smape: 1.2661 - val_ia: 0.2462 - val_loss: 0.7649 - val_mae: 0.6475 - val_rmse: 0.7164 - val_smape: 1.2676

Epoch 30/256

1915/1915 - 46s - 24ms/step - ia: 0.3885 - loss: 0.8139 - mae: 0.6633 - rmse: 0.8709 - smape: 1.2690 - val_ia: 0.2481 - val_loss: 0.7598 - val_mae: 0.6334 - val_rmse: 0.7026 - val_smape: 1.2209

Epoch 31/256

1915/1915 - 41s - 22ms/step - ia: 0.3874 - loss: 0.8137 - mae: 0.6629 - rmse: 0.8697 - smape: 1.2698 - val_ia: 0.2479 - val_loss: 0.7598 - val_mae: 0.6371 - val_rmse: 0.7067 - val_smape: 1.2320

Epoch 32/256

1915/1915 - 45s - 24ms/step - ia: 0.3889 - loss: 0.8127 - mae: 0.6621 - rmse: 0.8693 - smape: 1.2665 - val_ia: 0.2491 - val_loss: 0.7589 - val_mae: 0.6306 - val_rmse: 0.7002 - val_smape: 1.2075

Epoch 33/256

1915/1915 - 40s - 21ms/step - ia: 0.3870 - loss: 0.8127 - mae: 0.6627 - rmse: 0.8708 - smape: 1.2696 - val_ia: 0.2444 - val_loss: 0.7739 - val_mae: 0.6588 - val_rmse: 0.7280 - val_smape: 1.2886

Epoch 34/256

1915/1915 - 46s - 24ms/step - ia: 0.3911 - loss: 0.8117 - mae: 0.6616 - rmse: 0.8696 - smape: 1.2641 - val_ia: 0.2460 - val_loss: 0.7663 - val_mae: 0.6511 - val_rmse: 0.7202 - val_smape: 1.2743

Epoch 35/256

1915/1915 - 41s - 22ms/step - ia: 0.3900 - loss: 0.8116 - mae: 0.6620 - rmse: 0.8688 - smape: 1.2670 - val_ia: 0.2490 - val_loss: 0.7570 - val_mae: 0.6334 - val_rmse: 0.7034 - val_smape: 1.2184

Epoch 36/256

1915/1915 - 44s - 23ms/step - ia: 0.3903 - loss: 0.8115 - mae: 0.6615 - rmse: 0.8684 - smape: 1.2654 - val_ia: 0.2484 - val_loss: 0.7578 - val_mae: 0.6369 - val_rmse: 0.7068 - val_smape: 1.2308

Epoch 37/256

1915/1915 - 41s - 22ms/step - ia: 0.3920 - loss: 0.8102 - mae: 0.6611 - rmse: 0.8685 - smape: 1.2641 - val_ia: 0.2466 - val_loss: 0.7636 - val_mae: 0.6478 - val_rmse: 0.7171 - val_smape: 1.2667

Epoch 38/256

1915/1915 - 45s - 23ms/step - ia: 0.3910 - loss: 0.8100 - mae: 0.6609 - rmse: 0.8678 - smape: 1.2648 - val_ia: 0.2421 - val_loss: 0.7810 - val_mae: 0.6684 - val_rmse: 0.7367 - val_smape: 1.3157

Epoch 39/256

1915/1915 - 46s - 24ms/step - ia: 0.3898 - loss: 0.8095 - mae: 0.6607 - rmse: 0.8679 - smape: 1.2636 - val_ia: 0.2482 - val_loss: 0.7568 - val_mae: 0.6391 - val_rmse: 0.7083 - val_smape: 1.2442

Epoch 40/256

1915/1915 - 45s - 24ms/step - ia: 0.3908 - loss: 0.8094 - mae: 0.6609 - rmse: 0.8679 - smape: 1.2668 - val_ia: 0.2478 - val_loss: 0.7597 - val_mae: 0.6433 - val_rmse: 0.7129 - val_smape: 1.2529

Epoch 41/256

1915/1915 - 46s - 24ms/step - ia: 0.3927 - loss: 0.8089 - mae: 0.6605 - rmse: 0.8671 - smape: 1.2626 - val_ia: 0.2484 - val_loss: 0.7557 - val_mae: 0.6364 - val_rmse: 0.7060 - val_smape: 1.2337

Epoch 42/256

1915/1915 - 47s - 24ms/step - ia: 0.3920 - loss: 0.8081 - mae: 0.6603 - rmse: 0.8669 - smape: 1.2654 - val_ia: 0.2493 - val_loss: 0.7547 - val_mae: 0.6338 - val_rmse: 0.7041 - val_smape: 1.2200

Epoch 43/256

1915/1915 - 40s - 21ms/step - ia: 0.3940 - loss: 0.8078 - mae: 0.6598 - rmse: 0.8672 - smape: 1.2607 - val_ia: 0.2504 - val_loss: 0.7542 - val_mae: 0.6276 - val_rmse: 0.6974 - val_smape: 1.2000

Epoch 44/256

1915/1915 - 46s - 24ms/step - ia: 0.3924 - loss: 0.8072 - mae: 0.6599 - rmse: 0.8674 - smape: 1.2640 - val_ia: 0.2485 - val_loss: 0.7560 - val_mae: 0.6377 - val_rmse: 0.7076 - val_smape: 1.2368

Epoch 45/256

1915/1915 - 45s - 24ms/step - ia: 0.3936 - loss: 0.8076 - mae: 0.6598 - rmse: 0.8666 - smape: 1.2620 - val_ia: 0.2491 - val_loss: 0.7540 - val_mae: 0.6334 - val_rmse: 0.7034 - val_smape: 1.2226

Epoch 46/256

1915/1915 - 46s - 24ms/step - ia: 0.3942 - loss: 0.8065 - mae: 0.6593 - rmse: 0.8670 - smape: 1.2608 - val_ia: 0.2499 - val_loss: 0.7528 - val_mae: 0.6287 - val_rmse: 0.6984 - val_smape: 1.2075

Epoch 47/256

1915/1915 - 46s - 24ms/step - ia: 0.3953 - loss: 0.8056 - mae: 0.6590 - rmse: 0.8649 - smape: 1.2617 - val_ia: 0.2486 - val_loss: 0.7528 - val_mae: 0.6365 - val_rmse: 0.7054 - val_smape: 1.2418

Epoch 48/256

1915/1915 - 41s - 21ms/step - ia: 0.3944 - loss: 0.8052 - mae: 0.6588 - rmse: 0.8644 - smape: 1.2620 - val_ia: 0.2490 - val_loss: 0.7520 - val_mae: 0.6312 - val_rmse: 0.7004 - val_smape: 1.2221

Epoch 49/256

1915/1915 - 46s - 24ms/step - ia: 0.3926 - loss: 0.8052 - mae: 0.6590 - rmse: 0.8651 - smape: 1.2643 - val_ia: 0.2497 - val_loss: 0.7515 - val_mae: 0.6308 - val_rmse: 0.7007 - val_smape: 1.2163

Epoch 50/256

1915/1915 - 45s - 23ms/step - ia: 0.3941 - loss: 0.8051 - mae: 0.6585 - rmse: 0.8651 - smape: 1.2608 - val_ia: 0.2490 - val_loss: 0.7546 - val_mae: 0.6375 - val_rmse: 0.7078 - val_smape: 1.2346

Epoch 51/256

1915/1915 - 42s - 22ms/step - ia: 0.3951 - loss: 0.8046 - mae: 0.6581 - rmse: 0.8651 - smape: 1.2594 - val_ia: 0.2482 - val_loss: 0.7564 - val_mae: 0.6423 - val_rmse: 0.7121 - val_smape: 1.2514

Epoch 52/256

1915/1915 - 44s - 23ms/step - ia: 0.3971 - loss: 0.8039 - mae: 0.6578 - rmse: 0.8650 - smape: 1.2580 - val_ia: 0.2482 - val_loss: 0.7538 - val_mae: 0.6401 - val_rmse: 0.7092 - val_smape: 1.2525

Epoch 53/256

1915/1915 - 81s - 42ms/step - ia: 0.3959 - loss: 0.8039 - mae: 0.6582 - rmse: 0.8636 - smape: 1.2613 - val_ia: 0.2501 - val_loss: 0.7493 - val_mae: 0.6309 - val_rmse: 0.7010 - val_smape: 1.2178

Epoch 54/256

1915/1915 - 45s - 24ms/step - ia: 0.3953 - loss: 0.8034 - mae: 0.6581 - rmse: 0.8650 - smape: 1.2623 - val_ia: 0.2470 - val_loss: 0.7613 - val_mae: 0.6487 - val_rmse: 0.7186 - val_smape: 1.2659

Epoch 55/256

1915/1915 - 45s - 24ms/step - ia: 0.3972 - loss: 0.8025 - mae: 0.6573 - rmse: 0.8640 - smape: 1.2581 - val_ia: 0.2471 - val_loss: 0.7593 - val_mae: 0.6477 - val_rmse: 0.7172 - val_smape: 1.2668

Epoch 56/256

1915/1915 - 88s - 46ms/step - ia: 0.3975 - loss: 0.8019 - mae: 0.6571 - rmse: 0.8635 - smape: 1.2575 - val_ia: 0.2487 - val_loss: 0.7512 - val_mae: 0.6370 - val_rmse: 0.7065 - val_smape: 1.2427

Epoch 57/256

1915/1915 - 60s - 31ms/step - ia: 0.3970 - loss: 0.8018 - mae: 0.6568 - rmse: 0.8633 - smape: 1.2585 - val_ia: 0.2511 - val_loss: 0.7474 - val_mae: 0.6277 - val_rmse: 0.6978 - val_smape: 1.2081

Epoch 58/256

1915/1915 - 52s - 27ms/step - ia: 0.3977 - loss: 0.8015 - mae: 0.6568 - rmse: 0.8627 - smape: 1.2591 - val_ia: 0.2480 - val_loss: 0.7557 - val_mae: 0.6438 - val_rmse: 0.7137 - val_smape: 1.2567

Epoch 59/256

1915/1915 - 44s - 23ms/step - ia: 0.3979 - loss: 0.8012 - mae: 0.6565 - rmse: 0.8627 - smape: 1.2589 - val_ia: 0.2476 - val_loss: 0.7596 - val_mae: 0.6473 - val_rmse: 0.7175 - val_smape: 1.2597

Epoch 60/256

1915/1915 - 93s - 48ms/step - ia: 0.3995 - loss: 0.8010 - mae: 0.6564 - rmse: 0.8624 - smape: 1.2561 - val_ia: 0.2510 - val_loss: 0.7477 - val_mae: 0.6292 - val_rmse: 0.6997 - val_smape: 1.2114

Epoch 61/256

1915/1915 - 57s - 30ms/step - ia: 0.3989 - loss: 0.8007 - mae: 0.6561 - rmse: 0.8625 - smape: 1.2582 - val_ia: 0.2501 - val_loss: 0.7477 - val_mae: 0.6330 - val_rmse: 0.7032 - val_smape: 1.2266

Epoch 62/256

1915/1915 - 58s - 30ms/step - ia: 0.4011 - loss: 0.8002 - mae: 0.6559 - rmse: 0.8630 - smape: 1.2549 - val_ia: 0.2500 - val_loss: 0.7469 - val_mae: 0.6325 - val_rmse: 0.7023 - val_smape: 1.2282

Epoch 63/256

1915/1915 - 56s - 29ms/step - ia: 0.3992 - loss: 0.7996 - mae: 0.6559 - rmse: 0.8618 - smape: 1.2570 - val_ia: 0.2490 - val_loss: 0.7502 - val_mae: 0.6382 - val_rmse: 0.7081 - val_smape: 1.2441

Epoch 64/256

1915/1915 - 73s - 38ms/step - ia: 0.3989 - loss: 0.7996 - mae: 0.6559 - rmse: 0.8619 - smape: 1.2565 - val_ia: 0.2495 - val_loss: 0.7490 - val_mae: 0.6349 - val_rmse: 0.7052 - val_smape: 1.2328

Epoch 65/256

1915/1915 - 54s - 28ms/step - ia: 0.3997 - loss: 0.7988 - mae: 0.6550 - rmse: 0.8618 - smape: 1.2548 - val_ia: 0.2480 - val_loss: 0.7538 - val_mae: 0.6431 - val_rmse: 0.7130 - val_smape: 1.2559

Epoch 66/256

1915/1915 - 51s - 27ms/step - ia: 0.4011 - loss: 0.7988 - mae: 0.6549 - rmse: 0.8615 - smape: 1.2536 - val_ia: 0.2498 - val_loss: 0.7462 - val_mae: 0.6318 - val_rmse: 0.7015 - val_smape: 1.2295

Epoch 67/256

1915/1915 - 50s - 26ms/step - ia: 0.3991 - loss: 0.7980 - mae: 0.6551 - rmse: 0.8604 - smape: 1.2555 - val_ia: 0.2496 - val_loss: 0.7491 - val_mae: 0.6361 - val_rmse: 0.7066 - val_smape: 1.2347

Epoch 68/256

1915/1915 - 47s - 24ms/step - ia: 0.4008 - loss: 0.7972 - mae: 0.6545 - rmse: 0.8618 - smape: 1.2536 - val_ia: 0.2520 - val_loss: 0.7450 - val_mae: 0.6269 - val_rmse: 0.6976 - val_smape: 1.2066

Epoch 69/256

1915/1915 - 45s - 24ms/step - ia: 0.4006 - loss: 0.7977 - mae: 0.6548 - rmse: 0.8620 - smape: 1.2556 - val_ia: 0.2460 - val_loss: 0.7595 - val_mae: 0.6506 - val_rmse: 0.7202 - val_smape: 1.2745

Epoch 70/256

1915/1915 - 47s - 25ms/step - ia: 0.4029 - loss: 0.7973 - mae: 0.6545 - rmse: 0.8612 - smape: 1.2543 - val_ia: 0.2501 - val_loss: 0.7459 - val_mae: 0.6322 - val_rmse: 0.7024 - val_smape: 1.2276

Epoch 71/256

1915/1915 - 80s - 42ms/step - ia: 0.4004 - loss: 0.7967 - mae: 0.6541 - rmse: 0.8606 - smape: 1.2536 - val_ia: 0.2526 - val_loss: 0.7449 - val_mae: 0.6256 - val_rmse: 0.6965 - val_smape: 1.2020

Epoch 72/256

1915/1915 - 46s - 24ms/step - ia: 0.4039 - loss: 0.7961 - mae: 0.6535 - rmse: 0.8600 - smape: 1.2498 - val_ia: 0.2464 - val_loss: 0.7547 - val_mae: 0.6467 - val_rmse: 0.7159 - val_smape: 1.2715

Epoch 73/256

1915/1915 - 46s - 24ms/step - ia: 0.4038 - loss: 0.7956 - mae: 0.6537 - rmse: 0.8593 - smape: 1.2530 - val_ia: 0.2473 - val_loss: 0.7503 - val_mae: 0.6414 - val_rmse: 0.7107 - val_smape: 1.2602

Epoch 74/256

1915/1915 - 46s - 24ms/step - ia: 0.4016 - loss: 0.7953 - mae: 0.6535 - rmse: 0.8602 - smape: 1.2524 - val_ia: 0.2486 - val_loss: 0.7492 - val_mae: 0.6396 - val_rmse: 0.7096 - val_smape: 1.2489

Epoch 75/256

1915/1915 - 47s - 25ms/step - ia: 0.4016 - loss: 0.7952 - mae: 0.6534 - rmse: 0.8601 - smape: 1.2537 - val_ia: 0.2484 - val_loss: 0.7557 - val_mae: 0.6437 - val_rmse: 0.7145 - val_smape: 1.2486

Epoch 76/256

1915/1915 - 48s - 25ms/step - ia: 0.4044 - loss: 0.7947 - mae: 0.6530 - rmse: 0.8598 - smape: 1.2501 - val_ia: 0.2520 - val_loss: 0.7452 - val_mae: 0.6291 - val_rmse: 0.7005 - val_smape: 1.2104

Epoch 77/256

1915/1915 - 81s - 42ms/step - ia: 0.4055 - loss: 0.7944 - mae: 0.6526 - rmse: 0.8594 - smape: 1.2488 - val_ia: 0.2485 - val_loss: 0.7497 - val_mae: 0.6398 - val_rmse: 0.7100 - val_smape: 1.2490

Epoch 78/256

1915/1915 - 46s - 24ms/step - ia: 0.4038 - loss: 0.7943 - mae: 0.6525 - rmse: 0.8583 - smape: 1.2492 - val_ia: 0.2486 - val_loss: 0.7472 - val_mae: 0.6371 - val_rmse: 0.7069 - val_smape: 1.2455

Epoch 79/256

1915/1915 - 48s - 25ms/step - ia: 0.4042 - loss: 0.7937 - mae: 0.6527 - rmse: 0.8592 - smape: 1.2511 - val_ia: 0.2474 - val_loss: 0.7526 - val_mae: 0.6436 - val_rmse: 0.7137 - val_smape: 1.2578

Epoch 80/256

1915/1915 - 81s - 42ms/step - ia: 0.4058 - loss: 0.7932 - mae: 0.6520 - rmse: 0.8596 - smape: 1.2495 - val_ia: 0.2499 - val_loss: 0.7422 - val_mae: 0.6318 - val_rmse: 0.7014 - val_smape: 1.2339

Epoch 81/256

1915/1915 - 46s - 24ms/step - ia: 0.4047 - loss: 0.7923 - mae: 0.6516 - rmse: 0.8583 - smape: 1.2484 - val_ia: 0.2493 - val_loss: 0.7440 - val_mae: 0.6327 - val_rmse: 0.7024 - val_smape: 1.2368

Epoch 82/256

1915/1915 - 43s - 22ms/step - ia: 0.4028 - loss: 0.7928 - mae: 0.6518 - rmse: 0.8589 - smape: 1.2513 - val_ia: 0.2461 - val_loss: 0.7630 - val_mae: 0.6514 - val_rmse: 0.7220 - val_smape: 1.2651

Epoch 83/256

1915/1915 - 47s - 25ms/step - ia: 0.4061 - loss: 0.7923 - mae: 0.6517 - rmse: 0.8586 - smape: 1.2475 - val_ia: 0.2502 - val_loss: 0.7445 - val_mae: 0.6320 - val_rmse: 0.7026 - val_smape: 1.2274

Epoch 84/256

1915/1915 - 50s - 26ms/step - ia: 0.4065 - loss: 0.7918 - mae: 0.6513 - rmse: 0.8581 - smape: 1.2459 - val_ia: 0.2498 - val_loss: 0.7422 - val_mae: 0.6332 - val_rmse: 0.7030 - val_smape: 1.2379

Epoch 85/256

1915/1915 - 54s - 28ms/step - ia: 0.4059 - loss: 0.7911 - mae: 0.6513 - rmse: 0.8575 - smape: 1.2487 - val_ia: 0.2556 - val_loss: 0.7414 - val_mae: 0.6211 - val_rmse: 0.6929 - val_smape: 1.1884

Epoch 86/256

1915/1915 - 59s - 31ms/step - ia: 0.4078 - loss: 0.7916 - mae: 0.6508 - rmse: 0.8573 - smape: 1.2443 - val_ia: 0.2450 - val_loss: 0.7605 - val_mae: 0.6533 - val_rmse: 0.7229 - val_smape: 1.2834

Epoch 87/256

1915/1915 - 46s - 24ms/step - ia: 0.4075 - loss: 0.7911 - mae: 0.6508 - rmse: 0.8574 - smape: 1.2467 - val_ia: 0.2523 - val_loss: 0.7402 - val_mae: 0.6259 - val_rmse: 0.6966 - val_smape: 1.2122

Epoch 88/256

1915/1915 - 45s - 23ms/step - ia: 0.4078 - loss: 0.7904 - mae: 0.6504 - rmse: 0.8584 - smape: 1.2448 - val_ia: 0.2524 - val_loss: 0.7399 - val_mae: 0.6255 - val_rmse: 0.6961 - val_smape: 1.2117

Epoch 89/256

1915/1915 - 57s - 30ms/step - ia: 0.4075 - loss: 0.7906 - mae: 0.6506 - rmse: 0.8571 - smape: 1.2469 - val_ia: 0.2462 - val_loss: 0.7563 - val_mae: 0.6479 - val_rmse: 0.7180 - val_smape: 1.2655

Epoch 90/256

1915/1915 - 80s - 42ms/step - ia: 0.4095 - loss: 0.7898 - mae: 0.6503 - rmse: 0.8565 - smape: 1.2450 - val_ia: 0.2534 - val_loss: 0.7394 - val_mae: 0.6244 - val_rmse: 0.6953 - val_smape: 1.2064

Epoch 91/256

1915/1915 - 77s - 40ms/step - ia: 0.4085 - loss: 0.7901 - mae: 0.6497 - rmse: 0.8558 - smape: 1.2434 - val_ia: 0.2504 - val_loss: 0.7421 - val_mae: 0.6309 - val_rmse: 0.7014 - val_smape: 1.2277

Epoch 92/256

1915/1915 - 50s - 26ms/step - ia: 0.4086 - loss: 0.7896 - mae: 0.6498 - rmse: 0.8568 - smape: 1.2445 - val_ia: 0.2425 - val_loss: 0.7765 - val_mae: 0.6686 - val_rmse: 0.7378 - val_smape: 1.3149

Epoch 93/256

1915/1915 - 50s - 26ms/step - ia: 0.4076 - loss: 0.7894 - mae: 0.6500 - rmse: 0.8556 - smape: 1.2463 - val_ia: 0.2518 - val_loss: 0.7422 - val_mae: 0.6286 - val_rmse: 0.6998 - val_smape: 1.2158

Epoch 94/256

1915/1915 - 49s - 26ms/step - ia: 0.4096 - loss: 0.7887 - mae: 0.6493 - rmse: 0.8558 - smape: 1.2418 - val_ia: 0.2522 - val_loss: 0.7399 - val_mae: 0.6262 - val_rmse: 0.6969 - val_smape: 1.2144

Epoch 95/256

1915/1915 - 47s - 25ms/step - ia: 0.4068 - loss: 0.7884 - mae: 0.6494 - rmse: 0.8558 - smape: 1.2443 - val_ia: 0.2467 - val_loss: 0.7596 - val_mae: 0.6483 - val_rmse: 0.7190 - val_smape: 1.2573

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1915/1915 - 44s - 23ms/step - ia: 0.1813 - loss: 1.0111 - mae: 0.7588 - rmse: 0.9649 - smape: 1.8053 - val_ia: 0.2212 - val_loss: 0.9343 - val_mae: 0.7256 - val_rmse: 0.7846 - val_smape: 1.8291

Epoch 2/64

1915/1915 - 30s - 16ms/step - ia: 0.2907 - loss: 0.8832 - mae: 0.6980 - rmse: 0.9053 - smape: 1.4780 - val_ia: 0.2413 - val_loss: 0.7920 - val_mae: 0.6588 - val_rmse: 0.7253 - val_smape: 1.3011

Epoch 3/64

1915/1915 - 30s - 16ms/step - ia: 0.3631 - loss: 0.8415 - mae: 0.6777 - rmse: 0.8846 - smape: 1.3135 - val_ia: 0.2410 - val_loss: 0.7874 - val_mae: 0.6599 - val_rmse: 0.7265 - val_smape: 1.3056

Epoch 4/64

1915/1915 - 43s - 23ms/step - ia: 0.3680 - loss: 0.8373 - mae: 0.6752 - rmse: 0.8830 - smape: 1.3046 - val_ia: 0.2379 - val_loss: 0.7912 - val_mae: 0.6687 - val_rmse: 0.7348 - val_smape: 1.3307

Epoch 5/64

1915/1915 - 27s - 14ms/step - ia: 0.3714 - loss: 0.8322 - mae: 0.6727 - rmse: 0.8805 - smape: 1.2965 - val_ia: 0.2417 - val_loss: 0.7813 - val_mae: 0.6581 - val_rmse: 0.7249 - val_smape: 1.3051

Epoch 6/64

1915/1915 - 34s - 18ms/step - ia: 0.3733 - loss: 0.8293 - mae: 0.6715 - rmse: 0.8779 - smape: 1.2979 - val_ia: 0.2481 - val_loss: 0.7703 - val_mae: 0.6387 - val_rmse: 0.7077 - val_smape: 1.2310

Epoch 7/64

1915/1915 - 31s - 16ms/step - ia: 0.3750 - loss: 0.8266 - mae: 0.6698 - rmse: 0.8779 - smape: 1.2884 - val_ia: 0.2453 - val_loss: 0.7717 - val_mae: 0.6483 - val_rmse: 0.7167 - val_smape: 1.2693

Epoch 8/64

1915/1915 - 30s - 16ms/step - ia: 0.3810 - loss: 0.8244 - mae: 0.6683 - rmse: 0.8758 - smape: 1.2834 - val_ia: 0.2480 - val_loss: 0.7667 - val_mae: 0.6370 - val_rmse: 0.7056 - val_smape: 1.2332

Epoch 9/64

1915/1915 - 33s - 17ms/step - ia: 0.3785 - loss: 0.8224 - mae: 0.6679 - rmse: 0.8746 - smape: 1.2841 - val_ia: 0.2481 - val_loss: 0.7666 - val_mae: 0.6357 - val_rmse: 0.7045 - val_smape: 1.2290

Epoch 10/64

1915/1915 - 33s - 17ms/step - ia: 0.3818 - loss: 0.8205 - mae: 0.6663 - rmse: 0.8732 - smape: 1.2807 - val_ia: 0.2469 - val_loss: 0.7655 - val_mae: 0.6424 - val_rmse: 0.7110 - val_smape: 1.2549

Epoch 11/64

1915/1915 - 33s - 17ms/step - ia: 0.3818 - loss: 0.8188 - mae: 0.6665 - rmse: 0.8727 - smape: 1.2816 - val_ia: 0.2478 - val_loss: 0.7636 - val_mae: 0.6406 - val_rmse: 0.7099 - val_smape: 1.2446

Epoch 12/64

1915/1915 - 32s - 17ms/step - ia: 0.3842 - loss: 0.8178 - mae: 0.6653 - rmse: 0.8729 - smape: 1.2782 - val_ia: 0.2477 - val_loss: 0.7630 - val_mae: 0.6415 - val_rmse: 0.7108 - val_smape: 1.2477

Epoch 13/64

1915/1915 - 33s - 17ms/step - ia: 0.3853 - loss: 0.8169 - mae: 0.6648 - rmse: 0.8704 - smape: 1.2758 - val_ia: 0.2442 - val_loss: 0.7709 - val_mae: 0.6534 - val_rmse: 0.7219 - val_smape: 1.2871

Epoch 14/64

1915/1915 - 33s - 17ms/step - ia: 0.3848 - loss: 0.8161 - mae: 0.6647 - rmse: 0.8718 - smape: 1.2760 - val_ia: 0.2520 - val_loss: 0.7704 - val_mae: 0.6258 - val_rmse: 0.6960 - val_smape: 1.1730

Epoch 15/64

1915/1915 - 34s - 18ms/step - ia: 0.3849 - loss: 0.8144 - mae: 0.6634 - rmse: 0.8710 - smape: 1.2745 - val_ia: 0.2486 - val_loss: 0.7608 - val_mae: 0.6381 - val_rmse: 0.7082 - val_smape: 1.2321

Epoch 16/64

1915/1915 - 35s - 18ms/step - ia: 0.3882 - loss: 0.8142 - mae: 0.6631 - rmse: 0.8702 - smape: 1.2708 - val_ia: 0.2474 - val_loss: 0.7626 - val_mae: 0.6459 - val_rmse: 0.7151 - val_smape: 1.2612

Epoch 17/64

1915/1915 - 37s - 19ms/step - ia: 0.3876 - loss: 0.8129 - mae: 0.6626 - rmse: 0.8686 - smape: 1.2721 - val_ia: 0.2490 - val_loss: 0.7574 - val_mae: 0.6341 - val_rmse: 0.7038 - val_smape: 1.2248

Epoch 18/64

1915/1915 - 38s - 20ms/step - ia: 0.3883 - loss: 0.8125 - mae: 0.6620 - rmse: 0.8699 - smape: 1.2686 - val_ia: 0.2497 - val_loss: 0.7573 - val_mae: 0.6311 - val_rmse: 0.7009 - val_smape: 1.2143

Epoch 19/64

1915/1915 - 41s - 21ms/step - ia: 0.3885 - loss: 0.8113 - mae: 0.6620 - rmse: 0.8685 - smape: 1.2703 - val_ia: 0.2501 - val_loss: 0.7553 - val_mae: 0.6303 - val_rmse: 0.7001 - val_smape: 1.2116

Epoch 20/64

1915/1915 - 32s - 17ms/step - ia: 0.3884 - loss: 0.8112 - mae: 0.6614 - rmse: 0.8698 - smape: 1.2698 - val_ia: 0.2475 - val_loss: 0.7624 - val_mae: 0.6458 - val_rmse: 0.7159 - val_smape: 1.2564

Epoch 21/64

1915/1915 - 34s - 18ms/step - ia: 0.3918 - loss: 0.8101 - mae: 0.6611 - rmse: 0.8683 - smape: 1.2672 - val_ia: 0.2519 - val_loss: 0.7554 - val_mae: 0.6273 - val_rmse: 0.6981 - val_smape: 1.1936

Epoch 22/64

1915/1915 - 33s - 17ms/step - ia: 0.3936 - loss: 0.8089 - mae: 0.6597 - rmse: 0.8673 - smape: 1.2604 - val_ia: 0.2494 - val_loss: 0.7534 - val_mae: 0.6280 - val_rmse: 0.6967 - val_smape: 1.2097

Epoch 23/64

1915/1915 - 34s - 18ms/step - ia: 0.3885 - loss: 0.8081 - mae: 0.6605 - rmse: 0.8668 - smape: 1.2699 - val_ia: 0.2481 - val_loss: 0.7596 - val_mae: 0.6453 - val_rmse: 0.7154 - val_smape: 1.2564

Epoch 24/64

1915/1915 - 32s - 17ms/step - ia: 0.3940 - loss: 0.8073 - mae: 0.6596 - rmse: 0.8679 - smape: 1.2609 - val_ia: 0.2494 - val_loss: 0.7512 - val_mae: 0.6305 - val_rmse: 0.6999 - val_smape: 1.2199

Epoch 25/64

1915/1915 - 42s - 22ms/step - ia: 0.3913 - loss: 0.8072 - mae: 0.6598 - rmse: 0.8660 - smape: 1.2663 - val_ia: 0.2459 - val_loss: 0.7616 - val_mae: 0.6502 - val_rmse: 0.7192 - val_smape: 1.2796

Epoch 26/64

1915/1915 - 32s - 17ms/step - ia: 0.3947 - loss: 0.8068 - mae: 0.6594 - rmse: 0.8669 - smape: 1.2638 - val_ia: 0.2479 - val_loss: 0.7539 - val_mae: 0.6416 - val_rmse: 0.7104 - val_smape: 1.2601

Epoch 27/64

1915/1915 - 33s - 17ms/step - ia: 0.3931 - loss: 0.8053 - mae: 0.6593 - rmse: 0.8657 - smape: 1.2659 - val_ia: 0.2466 - val_loss: 0.7618 - val_mae: 0.6497 - val_rmse: 0.7194 - val_smape: 1.2707

Epoch 28/64

1915/1915 - 29s - 15ms/step - ia: 0.3936 - loss: 0.8054 - mae: 0.6587 - rmse: 0.8651 - smape: 1.2628 - val_ia: 0.2478 - val_loss: 0.7578 - val_mae: 0.6432 - val_rmse: 0.7136 - val_smape: 1.2519

Epoch 29/64

1915/1915 - 32s - 17ms/step - ia: 0.3963 - loss: 0.8042 - mae: 0.6578 - rmse: 0.8628 - smape: 1.2603 - val_ia: 0.2489 - val_loss: 0.7533 - val_mae: 0.6387 - val_rmse: 0.7090 - val_smape: 1.2413

Epoch 30/64

1915/1915 - 34s - 18ms/step - ia: 0.3974 - loss: 0.8035 - mae: 0.6575 - rmse: 0.8633 - smape: 1.2593 - val_ia: 0.2489 - val_loss: 0.7507 - val_mae: 0.6388 - val_rmse: 0.7084 - val_smape: 1.2476

Epoch 31/64

1915/1915 - 33s - 17ms/step - ia: 0.3968 - loss: 0.8028 - mae: 0.6576 - rmse: 0.8633 - smape: 1.2616 - val_ia: 0.2401 - val_loss: 0.7892 - val_mae: 0.6782 - val_rmse: 0.7469 - val_smape: 1.3373

Epoch 32/64

1915/1915 - 33s - 17ms/step - ia: 0.3988 - loss: 0.8028 - mae: 0.6573 - rmse: 0.8642 - smape: 1.2595 - val_ia: 0.2466 - val_loss: 0.7572 - val_mae: 0.6477 - val_rmse: 0.7170 - val_smape: 1.2732

Epoch 33/64

1915/1915 - 32s - 17ms/step - ia: 0.3978 - loss: 0.8020 - mae: 0.6566 - rmse: 0.8638 - smape: 1.2581 - val_ia: 0.2494 - val_loss: 0.7470 - val_mae: 0.6321 - val_rmse: 0.7014 - val_smape: 1.2323

Epoch 34/64

1915/1915 - 35s - 18ms/step - ia: 0.3978 - loss: 0.8011 - mae: 0.6563 - rmse: 0.8628 - smape: 1.2579 - val_ia: 0.2525 - val_loss: 0.7456 - val_mae: 0.6255 - val_rmse: 0.6962 - val_smape: 1.2007

Epoch 35/64

1915/1915 - 39s - 20ms/step - ia: 0.4001 - loss: 0.8009 - mae: 0.6561 - rmse: 0.8627 - smape: 1.2573 - val_ia: 0.2513 - val_loss: 0.7456 - val_mae: 0.6284 - val_rmse: 0.6988 - val_smape: 1.2142

Epoch 36/64

1915/1915 - 33s - 17ms/step - ia: 0.3993 - loss: 0.7996 - mae: 0.6555 - rmse: 0.8618 - smape: 1.2583 - val_ia: 0.2486 - val_loss: 0.7505 - val_mae: 0.6397 - val_rmse: 0.7099 - val_smape: 1.2483

Epoch 37/64

1915/1915 - 34s - 18ms/step - ia: 0.3998 - loss: 0.7993 - mae: 0.6556 - rmse: 0.8635 - smape: 1.2555 - val_ia: 0.2540 - val_loss: 0.7432 - val_mae: 0.6236 - val_rmse: 0.6950 - val_smape: 1.1913

Epoch 38/64

1915/1915 - 42s - 22ms/step - ia: 0.3984 - loss: 0.7981 - mae: 0.6548 - rmse: 0.8622 - smape: 1.2564 - val_ia: 0.2485 - val_loss: 0.7520 - val_mae: 0.6420 - val_rmse: 0.7124 - val_smape: 1.2513

Epoch 39/64

1915/1915 - 33s - 17ms/step - ia: 0.4017 - loss: 0.7975 - mae: 0.6543 - rmse: 0.8611 - smape: 1.2546 - val_ia: 0.2444 - val_loss: 0.7672 - val_mae: 0.6600 - val_rmse: 0.7293 - val_smape: 1.2980

Epoch 40/64

1915/1915 - 40s - 21ms/step - ia: 0.4006 - loss: 0.7973 - mae: 0.6545 - rmse: 0.8602 - smape: 1.2559 - val_ia: 0.2448 - val_loss: 0.7713 - val_mae: 0.6598 - val_rmse: 0.7302 - val_smape: 1.2852

Epoch 41/64

1915/1915 - 33s - 17ms/step - ia: 0.4030 - loss: 0.7968 - mae: 0.6540 - rmse: 0.8606 - smape: 1.2523 - val_ia: 0.2524 - val_loss: 0.7447 - val_mae: 0.6279 - val_rmse: 0.6991 - val_smape: 1.2103

Epoch 42/64

1915/1915 - 32s - 17ms/step - ia: 0.4034 - loss: 0.7956 - mae: 0.6536 - rmse: 0.8593 - smape: 1.2518 - val_ia: 0.2549 - val_loss: 0.7407 - val_mae: 0.6219 - val_rmse: 0.6934 - val_smape: 1.1898

Epoch 43/64

1915/1915 - 33s - 17ms/step - ia: 0.4059 - loss: 0.7950 - mae: 0.6529 - rmse: 0.8607 - smape: 1.2502 - val_ia: 0.2514 - val_loss: 0.7426 - val_mae: 0.6315 - val_rmse: 0.7022 - val_smape: 1.2258

Epoch 44/64

1915/1915 - 33s - 17ms/step - ia: 0.4051 - loss: 0.7945 - mae: 0.6525 - rmse: 0.8600 - smape: 1.2499 - val_ia: 0.2486 - val_loss: 0.7445 - val_mae: 0.6380 - val_rmse: 0.7073 - val_smape: 1.2534

Epoch 45/64

1915/1915 - 33s - 17ms/step - ia: 0.4050 - loss: 0.7937 - mae: 0.6527 - rmse: 0.8592 - smape: 1.2505 - val_ia: 0.2546 - val_loss: 0.7399 - val_mae: 0.6222 - val_rmse: 0.6933 - val_smape: 1.1954

Epoch 46/64

1915/1915 - 34s - 18ms/step - ia: 0.4040 - loss: 0.7922 - mae: 0.6520 - rmse: 0.8583 - smape: 1.2520 - val_ia: 0.2477 - val_loss: 0.7560 - val_mae: 0.6450 - val_rmse: 0.7160 - val_smape: 1.2543

Epoch 47/64

1915/1915 - 33s - 17ms/step - ia: 0.4070 - loss: 0.7921 - mae: 0.6513 - rmse: 0.8589 - smape: 1.2456 - val_ia: 0.2496 - val_loss: 0.7450 - val_mae: 0.6353 - val_rmse: 0.7056 - val_smape: 1.2395

Epoch 48/64

1915/1915 - 40s - 21ms/step - ia: 0.4066 - loss: 0.7915 - mae: 0.6515 - rmse: 0.8569 - smape: 1.2486 - val_ia: 0.2500 - val_loss: 0.7477 - val_mae: 0.6383 - val_rmse: 0.7092 - val_smape: 1.2403

Epoch 49/64

1915/1915 - 27s - 14ms/step - ia: 0.4064 - loss: 0.7915 - mae: 0.6511 - rmse: 0.8586 - smape: 1.2461 - val_ia: 0.2495 - val_loss: 0.7446 - val_mae: 0.6358 - val_rmse: 0.7060 - val_smape: 1.2430

Epoch 50/64

1915/1915 - 36s - 19ms/step - ia: 0.4067 - loss: 0.7903 - mae: 0.6504 - rmse: 0.8573 - smape: 1.2458 - val_ia: 0.2516 - val_loss: 0.7420 - val_mae: 0.6314 - val_rmse: 0.7023 - val_smape: 1.2267

Epoch 51/64

1915/1915 - 32s - 17ms/step - ia: 0.4082 - loss: 0.7896 - mae: 0.6499 - rmse: 0.8568 - smape: 1.2463 - val_ia: 0.2472 - val_loss: 0.7512 - val_mae: 0.6443 - val_rmse: 0.7143 - val_smape: 1.2643

Epoch 52/64

1915/1915 - 34s - 18ms/step - ia: 0.4077 - loss: 0.7896 - mae: 0.6502 - rmse: 0.8553 - smape: 1.2463 - val_ia: 0.2548 - val_loss: 0.7394 - val_mae: 0.6242 - val_rmse: 0.6958 - val_smape: 1.2038

Epoch 53/64

1915/1915 - 33s - 17ms/step - ia: 0.4085 - loss: 0.7891 - mae: 0.6498 - rmse: 0.8563 - smape: 1.2439 - val_ia: 0.2500 - val_loss: 0.7418 - val_mae: 0.6336 - val_rmse: 0.7036 - val_smape: 1.2401

Epoch 54/64

1915/1915 - 34s - 18ms/step - ia: 0.4094 - loss: 0.7876 - mae: 0.6490 - rmse: 0.8561 - smape: 1.2431 - val_ia: 0.2478 - val_loss: 0.7445 - val_mae: 0.6370 - val_rmse: 0.7063 - val_smape: 1.2551

Epoch 55/64

1915/1915 - 33s - 17ms/step - ia: 0.4094 - loss: 0.7873 - mae: 0.6489 - rmse: 0.8549 - smape: 1.2435 - val_ia: 0.2467 - val_loss: 0.7520 - val_mae: 0.6467 - val_rmse: 0.7162 - val_smape: 1.2724

Epoch 56/64

1915/1915 - 29s - 15ms/step - ia: 0.4097 - loss: 0.7867 - mae: 0.6487 - rmse: 0.8545 - smape: 1.2436 - val_ia: 0.2472 - val_loss: 0.7607 - val_mae: 0.6488 - val_rmse: 0.7199 - val_smape: 1.2586

Epoch 57/64

1915/1915 - 33s - 17ms/step - ia: 0.4118 - loss: 0.7859 - mae: 0.6480 - rmse: 0.8545 - smape: 1.2401 - val_ia: 0.2555 - val_loss: 0.7377 - val_mae: 0.6230 - val_rmse: 0.6943 - val_smape: 1.2038

Epoch 58/64

1915/1915 - 32s - 17ms/step - ia: 0.4139 - loss: 0.7851 - mae: 0.6474 - rmse: 0.8533 - smape: 1.2382 - val_ia: 0.2522 - val_loss: 0.7369 - val_mae: 0.6290 - val_rmse: 0.6989 - val_smape: 1.2306

Epoch 59/64

1915/1915 - 33s - 17ms/step - ia: 0.4115 - loss: 0.7858 - mae: 0.6476 - rmse: 0.8554 - smape: 1.2389 - val_ia: 0.2528 - val_loss: 0.7374 - val_mae: 0.6279 - val_rmse: 0.6981 - val_smape: 1.2266

Epoch 60/64

1915/1915 - 30s - 16ms/step - ia: 0.4123 - loss: 0.7838 - mae: 0.6470 - rmse: 0.8541 - smape: 1.2398 - val_ia: 0.2543 - val_loss: 0.7374 - val_mae: 0.6259 - val_rmse: 0.6968 - val_smape: 1.2151

Epoch 61/64

1915/1915 - 44s - 23ms/step - ia: 0.4140 - loss: 0.7832 - mae: 0.6465 - rmse: 0.8534 - smape: 1.2384 - val_ia: 0.2587 - val_loss: 0.7392 - val_mae: 0.6170 - val_rmse: 0.6887 - val_smape: 1.1818

Epoch 62/64

1915/1915 - 32s - 17ms/step - ia: 0.4122 - loss: 0.7840 - mae: 0.6469 - rmse: 0.8536 - smape: 1.2401 - val_ia: 0.2484 - val_loss: 0.7470 - val_mae: 0.6398 - val_rmse: 0.7097 - val_smape: 1.2542

Epoch 63/64

1915/1915 - 29s - 15ms/step - ia: 0.4132 - loss: 0.7826 - mae: 0.6467 - rmse: 0.8528 - smape: 1.2385 - val_ia: 0.2571 - val_loss: 0.7412 - val_mae: 0.6235 - val_rmse: 0.6957 - val_smape: 1.1955

Epoch 64/64

1915/1915 - 33s - 17ms/step - ia: 0.4141 - loss: 0.7829 - mae: 0.6459 - rmse: 0.8531 - smape: 1.2374 - val_ia: 0.2484 - val_loss: 0.7538 - val_mae: 0.6436 - val_rmse: 0.7139 - val_smape: 1.2542

Restoring model weights from the end of the best epoch: 58.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 27:56 12s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step

 46%|████▌     | 23/50 [6:45:08<24:45:36, 3301.34s/trial, best loss: 0.7652717272425783]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

1915/1915 - 48s - 25ms/step - ia: 0.2191 - loss: 1.0547 - mae: 0.7622 - rmse: 0.9864 - smape: 1.5953 - val_ia: 0.2191 - val_loss: 0.9668 - val_mae: 0.7444 - val_rmse: 0.8035 - val_smape: 1.8805

Epoch 2/256

1915/1915 - 37s - 19ms/step - ia: 0.2088 - loss: 1.0161 - mae: 0.7567 - rmse: 0.9699 - smape: 1.6399 - val_ia: 0.2237 - val_loss: 0.9465 - val_mae: 0.7162 - val_rmse: 0.7763 - val_smape: 1.7049

Epoch 3/256

1915/1915 - 38s - 20ms/step - ia: 0.2197 - loss: 0.9847 - mae: 0.7432 - rmse: 0.9539 - smape: 1.6075 - val_ia: 0.2214 - val_loss: 0.9001 - val_mae: 0.7146 - val_rmse: 0.7731 - val_smape: 1.7121

Epoch 4/256

1915/1915 - 43s - 22ms/step - ia: 0.2780 - loss: 0.9208 - mae: 0.7155 - rmse: 0.9252 - smape: 1.4807 - val_ia: 0.2289 - val_loss: 0.8197 - val_mae: 0.6756 - val_rmse: 0.7377 - val_smape: 1.4202

Epoch 5/256

1915/1915 - 36s - 19ms/step - ia: 0.3430 - loss: 0.8770 - mae: 0.6952 - rmse: 0.9034 - smape: 1.3561 - val_ia: 0.2424 - val_loss: 0.7961 - val_mae: 0.6528 - val_rmse: 0.7189 - val_smape: 1.2994

Epoch 6/256

1915/1915 - 36s - 19ms/step - ia: 0.3564 - loss: 0.8686 - mae: 0.6916 - rmse: 0.8995 - smape: 1.3326 - val_ia: 0.2429 - val_loss: 0.7902 - val_mae: 0.6527 - val_rmse: 0.7190 - val_smape: 1.2925

Epoch 7/256

1915/1915 - 37s - 20ms/step - ia: 0.3591 - loss: 0.8651 - mae: 0.6891 - rmse: 0.8972 - smape: 1.3230 - val_ia: 0.2420 - val_loss: 0.7885 - val_mae: 0.6567 - val_rmse: 0.7230 - val_smape: 1.3040

Epoch 8/256

1915/1915 - 39s - 20ms/step - ia: 0.3629 - loss: 0.8601 - mae: 0.6862 - rmse: 0.8955 - smape: 1.3180 - val_ia: 0.2436 - val_loss: 0.7847 - val_mae: 0.6516 - val_rmse: 0.7181 - val_smape: 1.2875

Epoch 9/256

1915/1915 - 37s - 19ms/step - ia: 0.3627 - loss: 0.8603 - mae: 0.6867 - rmse: 0.8956 - smape: 1.3180 - val_ia: 0.2456 - val_loss: 0.7829 - val_mae: 0.6426 - val_rmse: 0.7092 - val_smape: 1.2515

Epoch 10/256

1915/1915 - 42s - 22ms/step - ia: 0.3656 - loss: 0.8539 - mae: 0.6835 - rmse: 0.8927 - smape: 1.3125 - val_ia: 0.2431 - val_loss: 0.7822 - val_mae: 0.6532 - val_rmse: 0.7195 - val_smape: 1.2954

Epoch 11/256

1915/1915 - 30s - 16ms/step - ia: 0.3603 - loss: 0.8563 - mae: 0.6845 - rmse: 0.8941 - smape: 1.3145 - val_ia: 0.2349 - val_loss: 0.7983 - val_mae: 0.6768 - val_rmse: 0.7425 - val_smape: 1.3529

Epoch 12/256

1915/1915 - 39s - 20ms/step - ia: 0.3655 - loss: 0.8519 - mae: 0.6834 - rmse: 0.8905 - smape: 1.3141 - val_ia: 0.2421 - val_loss: 0.7824 - val_mae: 0.6573 - val_rmse: 0.7240 - val_smape: 1.3026

Epoch 13/256

1915/1915 - 36s - 19ms/step - ia: 0.3680 - loss: 0.8471 - mae: 0.6812 - rmse: 0.8885 - smape: 1.3079 - val_ia: 0.2449 - val_loss: 0.7771 - val_mae: 0.6466 - val_rmse: 0.7138 - val_smape: 1.2705

Epoch 14/256

1915/1915 - 35s - 18ms/step - ia: 0.3691 - loss: 0.8472 - mae: 0.6808 - rmse: 0.8887 - smape: 1.3082 - val_ia: 0.2447 - val_loss: 0.7764 - val_mae: 0.6476 - val_rmse: 0.7148 - val_smape: 1.2746

Epoch 15/256

1915/1915 - 37s - 19ms/step - ia: 0.3684 - loss: 0.8435 - mae: 0.6787 - rmse: 0.8864 - smape: 1.3038 - val_ia: 0.2445 - val_loss: 0.7759 - val_mae: 0.6498 - val_rmse: 0.7174 - val_smape: 1.2774

Epoch 16/256

1915/1915 - 31s - 16ms/step - ia: 0.3714 - loss: 0.8421 - mae: 0.6779 - rmse: 0.8862 - smape: 1.3014 - val_ia: 0.2444 - val_loss: 0.7754 - val_mae: 0.6502 - val_rmse: 0.7177 - val_smape: 1.2790

Epoch 17/256

1915/1915 - 38s - 20ms/step - ia: 0.3723 - loss: 0.8402 - mae: 0.6766 - rmse: 0.8840 - smape: 1.2987 - val_ia: 0.2458 - val_loss: 0.7728 - val_mae: 0.6433 - val_rmse: 0.7111 - val_smape: 1.2572

Epoch 18/256

1915/1915 - 30s - 16ms/step - ia: 0.3732 - loss: 0.8397 - mae: 0.6764 - rmse: 0.8847 - smape: 1.2948 - val_ia: 0.2462 - val_loss: 0.7719 - val_mae: 0.6405 - val_rmse: 0.7081 - val_smape: 1.2480

Epoch 19/256

1915/1915 - 38s - 20ms/step - ia: 0.3710 - loss: 0.8405 - mae: 0.6775 - rmse: 0.8856 - smape: 1.3006 - val_ia: 0.2463 - val_loss: 0.7712 - val_mae: 0.6417 - val_rmse: 0.7097 - val_smape: 1.2507

Epoch 20/256

1915/1915 - 36s - 19ms/step - ia: 0.3746 - loss: 0.8401 - mae: 0.6767 - rmse: 0.8853 - smape: 1.2983 - val_ia: 0.2443 - val_loss: 0.7735 - val_mae: 0.6499 - val_rmse: 0.7173 - val_smape: 1.2810

Epoch 21/256

1915/1915 - 37s - 19ms/step - ia: 0.3745 - loss: 0.8364 - mae: 0.6752 - rmse: 0.8825 - smape: 1.2966 - val_ia: 0.2440 - val_loss: 0.7735 - val_mae: 0.6512 - val_rmse: 0.7185 - val_smape: 1.2856

Epoch 22/256

1915/1915 - 38s - 20ms/step - ia: 0.3746 - loss: 0.8353 - mae: 0.6749 - rmse: 0.8826 - smape: 1.2946 - val_ia: 0.2465 - val_loss: 0.7693 - val_mae: 0.6393 - val_rmse: 0.7072 - val_smape: 1.2444

Epoch 23/256

1915/1915 - 38s - 20ms/step - ia: 0.3749 - loss: 0.8347 - mae: 0.6741 - rmse: 0.8825 - smape: 1.2954 - val_ia: 0.2460 - val_loss: 0.7689 - val_mae: 0.6423 - val_rmse: 0.7102 - val_smape: 1.2556

Epoch 24/256

1915/1915 - 37s - 19ms/step - ia: 0.3768 - loss: 0.8329 - mae: 0.6734 - rmse: 0.8802 - smape: 1.2926 - val_ia: 0.2466 - val_loss: 0.7681 - val_mae: 0.6408 - val_rmse: 0.7091 - val_smape: 1.2472

Epoch 25/256

1915/1915 - 38s - 20ms/step - ia: 0.3786 - loss: 0.8345 - mae: 0.6736 - rmse: 0.8817 - smape: 1.2893 - val_ia: 0.2437 - val_loss: 0.7729 - val_mae: 0.6530 - val_rmse: 0.7205 - val_smape: 1.2891

Epoch 26/256

1915/1915 - 40s - 21ms/step - ia: 0.3763 - loss: 0.8319 - mae: 0.6728 - rmse: 0.8809 - smape: 1.2927 - val_ia: 0.2477 - val_loss: 0.7682 - val_mae: 0.6342 - val_rmse: 0.7026 - val_smape: 1.2195

Epoch 27/256

1915/1915 - 40s - 21ms/step - ia: 0.3762 - loss: 0.8325 - mae: 0.6726 - rmse: 0.8801 - smape: 1.2910 - val_ia: 0.2460 - val_loss: 0.7678 - val_mae: 0.6444 - val_rmse: 0.7127 - val_smape: 1.2600

Epoch 28/256

1915/1915 - 38s - 20ms/step - ia: 0.3794 - loss: 0.8307 - mae: 0.6717 - rmse: 0.8792 - smape: 1.2860 - val_ia: 0.2446 - val_loss: 0.7702 - val_mae: 0.6497 - val_rmse: 0.7174 - val_smape: 1.2809

Epoch 29/256

1915/1915 - 37s - 19ms/step - ia: 0.3793 - loss: 0.8291 - mae: 0.6716 - rmse: 0.8791 - smape: 1.2880 - val_ia: 0.2468 - val_loss: 0.7659 - val_mae: 0.6387 - val_rmse: 0.7069 - val_smape: 1.2431

Epoch 30/256

1915/1915 - 37s - 20ms/step - ia: 0.3782 - loss: 0.8306 - mae: 0.6716 - rmse: 0.8785 - smape: 1.2878 - val_ia: 0.2446 - val_loss: 0.7702 - val_mae: 0.6507 - val_rmse: 0.7190 - val_smape: 1.2779

Epoch 31/256

1915/1915 - 37s - 19ms/step - ia: 0.3784 - loss: 0.8299 - mae: 0.6719 - rmse: 0.8799 - smape: 1.2906 - val_ia: 0.2464 - val_loss: 0.7656 - val_mae: 0.6422 - val_rmse: 0.7108 - val_smape: 1.2531

Epoch 32/256

1915/1915 - 38s - 20ms/step - ia: 0.3779 - loss: 0.8290 - mae: 0.6719 - rmse: 0.8785 - smape: 1.2910 - val_ia: 0.2458 - val_loss: 0.7671 - val_mae: 0.6462 - val_rmse: 0.7147 - val_smape: 1.2647

Epoch 33/256

1915/1915 - 40s - 21ms/step - ia: 0.3792 - loss: 0.8297 - mae: 0.6713 - rmse: 0.8792 - smape: 1.2865 - val_ia: 0.2458 - val_loss: 0.7665 - val_mae: 0.6459 - val_rmse: 0.7140 - val_smape: 1.2678

Epoch 34/256

1915/1915 - 38s - 20ms/step - ia: 0.3795 - loss: 0.8263 - mae: 0.6698 - rmse: 0.8782 - smape: 1.2831 - val_ia: 0.2450 - val_loss: 0.7684 - val_mae: 0.6496 - val_rmse: 0.7178 - val_smape: 1.2770

Epoch 35/256

1915/1915 - 42s - 22ms/step - ia: 0.3809 - loss: 0.8272 - mae: 0.6704 - rmse: 0.8784 - smape: 1.2824 - val_ia: 0.2465 - val_loss: 0.7642 - val_mae: 0.6416 - val_rmse: 0.7098 - val_smape: 1.2539

Epoch 36/256

1915/1915 - 38s - 20ms/step - ia: 0.3789 - loss: 0.8268 - mae: 0.6704 - rmse: 0.8768 - smape: 1.2858 - val_ia: 0.2440 - val_loss: 0.7714 - val_mae: 0.6537 - val_rmse: 0.7222 - val_smape: 1.2831

Epoch 37/256

1915/1915 - 38s - 20ms/step - ia: 0.3822 - loss: 0.8260 - mae: 0.6690 - rmse: 0.8778 - smape: 1.2792 - val_ia: 0.2440 - val_loss: 0.7706 - val_mae: 0.6536 - val_rmse: 0.7218 - val_smape: 1.2861

Epoch 38/256

1915/1915 - 33s - 17ms/step - ia: 0.3807 - loss: 0.8264 - mae: 0.6696 - rmse: 0.8770 - smape: 1.2836 - val_ia: 0.2454 - val_loss: 0.7671 - val_mae: 0.6487 - val_rmse: 0.7174 - val_smape: 1.2691

Epoch 39/256

1915/1915 - 46s - 24ms/step - ia: 0.3821 - loss: 0.8238 - mae: 0.6685 - rmse: 0.8754 - smape: 1.2816 - val_ia: 0.2469 - val_loss: 0.7622 - val_mae: 0.6399 - val_rmse: 0.7086 - val_smape: 1.2459

Epoch 40/256

1915/1915 - 31s - 16ms/step - ia: 0.3837 - loss: 0.8241 - mae: 0.6685 - rmse: 0.8771 - smape: 1.2809 - val_ia: 0.2460 - val_loss: 0.7642 - val_mae: 0.6451 - val_rmse: 0.7131 - val_smape: 1.2676

Epoch 41/256

1915/1915 - 39s - 20ms/step - ia: 0.3796 - loss: 0.8259 - mae: 0.6695 - rmse: 0.8765 - smape: 1.2873 - val_ia: 0.2462 - val_loss: 0.7646 - val_mae: 0.6456 - val_rmse: 0.7147 - val_smape: 1.2586

Epoch 42/256

1915/1915 - 40s - 21ms/step - ia: 0.3847 - loss: 0.8239 - mae: 0.6679 - rmse: 0.8754 - smape: 1.2767 - val_ia: 0.2453 - val_loss: 0.7655 - val_mae: 0.6483 - val_rmse: 0.7165 - val_smape: 1.2752

Epoch 43/256

1915/1915 - 37s - 19ms/step - ia: 0.3807 - loss: 0.8227 - mae: 0.6685 - rmse: 0.8747 - smape: 1.2847 - val_ia: 0.2441 - val_loss: 0.7713 - val_mae: 0.6546 - val_rmse: 0.7235 - val_smape: 1.2810

Epoch 44/256

1915/1915 - 37s - 19ms/step - ia: 0.3858 - loss: 0.8223 - mae: 0.6673 - rmse: 0.8755 - smape: 1.2779 - val_ia: 0.2486 - val_loss: 0.7610 - val_mae: 0.6311 - val_rmse: 0.7003 - val_smape: 1.2108

Epoch 45/256

1915/1915 - 36s - 19ms/step - ia: 0.3841 - loss: 0.8219 - mae: 0.6675 - rmse: 0.8769 - smape: 1.2780 - val_ia: 0.2457 - val_loss: 0.7642 - val_mae: 0.6475 - val_rmse: 0.7159 - val_smape: 1.2706

Epoch 46/256

1915/1915 - 39s - 21ms/step - ia: 0.3836 - loss: 0.8229 - mae: 0.6681 - rmse: 0.8744 - smape: 1.2786 - val_ia: 0.2461 - val_loss: 0.7622 - val_mae: 0.6443 - val_rmse: 0.7124 - val_smape: 1.2657

Epoch 47/256

1915/1915 - 40s - 21ms/step - ia: 0.3815 - loss: 0.8235 - mae: 0.6680 - rmse: 0.8752 - smape: 1.2806 - val_ia: 0.2468 - val_loss: 0.7607 - val_mae: 0.6414 - val_rmse: 0.7102 - val_smape: 1.2511

Epoch 48/256

1915/1915 - 39s - 21ms/step - ia: 0.3868 - loss: 0.8180 - mae: 0.6656 - rmse: 0.8717 - smape: 1.2767 - val_ia: 0.2477 - val_loss: 0.7587 - val_mae: 0.6366 - val_rmse: 0.7058 - val_smape: 1.2340

Epoch 49/256

1915/1915 - 39s - 20ms/step - ia: 0.3852 - loss: 0.8202 - mae: 0.6656 - rmse: 0.8732 - smape: 1.2757 - val_ia: 0.2465 - val_loss: 0.7615 - val_mae: 0.6436 - val_rmse: 0.7126 - val_smape: 1.2567

Epoch 50/256

1915/1915 - 41s - 22ms/step - ia: 0.3832 - loss: 0.8233 - mae: 0.6677 - rmse: 0.8762 - smape: 1.2793 - val_ia: 0.2471 - val_loss: 0.7585 - val_mae: 0.6380 - val_rmse: 0.7066 - val_smape: 1.2430

Epoch 51/256

1915/1915 - 39s - 20ms/step - ia: 0.3840 - loss: 0.8201 - mae: 0.6664 - rmse: 0.8736 - smape: 1.2813 - val_ia: 0.2463 - val_loss: 0.7628 - val_mae: 0.6450 - val_rmse: 0.7145 - val_smape: 1.2553

Epoch 52/256

1915/1915 - 43s - 22ms/step - ia: 0.3857 - loss: 0.8190 - mae: 0.6664 - rmse: 0.8736 - smape: 1.2767 - val_ia: 0.2462 - val_loss: 0.7622 - val_mae: 0.6454 - val_rmse: 0.7146 - val_smape: 1.2584

Epoch 53/256

1915/1915 - 39s - 20ms/step - ia: 0.3856 - loss: 0.8199 - mae: 0.6657 - rmse: 0.8727 - smape: 1.2765 - val_ia: 0.2456 - val_loss: 0.7629 - val_mae: 0.6472 - val_rmse: 0.7161 - val_smape: 1.2671

Epoch 54/256

1915/1915 - 38s - 20ms/step - ia: 0.3867 - loss: 0.8184 - mae: 0.6654 - rmse: 0.8720 - smape: 1.2730 - val_ia: 0.2451 - val_loss: 0.7624 - val_mae: 0.6482 - val_rmse: 0.7161 - val_smape: 1.2789

Epoch 55/256

1915/1915 - 38s - 20ms/step - ia: 0.3844 - loss: 0.8184 - mae: 0.6660 - rmse: 0.8715 - smape: 1.2792 - val_ia: 0.2466 - val_loss: 0.7594 - val_mae: 0.6424 - val_rmse: 0.7115 - val_smape: 1.2535

Epoch 56/256

1915/1915 - 38s - 20ms/step - ia: 0.3867 - loss: 0.8167 - mae: 0.6644 - rmse: 0.8717 - smape: 1.2726 - val_ia: 0.2445 - val_loss: 0.7665 - val_mae: 0.6527 - val_rmse: 0.7214 - val_smape: 1.2813

Epoch 57/256

1915/1915 - 38s - 20ms/step - ia: 0.3868 - loss: 0.8190 - mae: 0.6653 - rmse: 0.8726 - smape: 1.2735 - val_ia: 0.2464 - val_loss: 0.7586 - val_mae: 0.6432 - val_rmse: 0.7117 - val_smape: 1.2605

Epoch 58/256

1915/1915 - 38s - 20ms/step - ia: 0.3869 - loss: 0.8170 - mae: 0.6652 - rmse: 0.8711 - smape: 1.2761 - val_ia: 0.2467 - val_loss: 0.7574 - val_mae: 0.6412 - val_rmse: 0.7098 - val_smape: 1.2538

Epoch 59/256

1915/1915 - 33s - 17ms/step - ia: 0.3852 - loss: 0.8180 - mae: 0.6654 - rmse: 0.8734 - smape: 1.2779 - val_ia: 0.2460 - val_loss: 0.7597 - val_mae: 0.6453 - val_rmse: 0.7141 - val_smape: 1.2641

Epoch 60/256

1915/1915 - 36s - 19ms/step - ia: 0.3867 - loss: 0.8164 - mae: 0.6646 - rmse: 0.8716 - smape: 1.2739 - val_ia: 0.2466 - val_loss: 0.7576 - val_mae: 0.6419 - val_rmse: 0.7108 - val_smape: 1.2537

Epoch 61/256

1915/1915 - 43s - 22ms/step - ia: 0.3873 - loss: 0.8162 - mae: 0.6652 - rmse: 0.8713 - smape: 1.2751 - val_ia: 0.2458 - val_loss: 0.7593 - val_mae: 0.6453 - val_rmse: 0.7139 - val_smape: 1.2661

Epoch 62/256

1915/1915 - 41s - 22ms/step - ia: 0.3869 - loss: 0.8166 - mae: 0.6646 - rmse: 0.8717 - smape: 1.2736 - val_ia: 0.2474 - val_loss: 0.7547 - val_mae: 0.6357 - val_rmse: 0.7045 - val_smape: 1.2385

Epoch 63/256

1915/1915 - 38s - 20ms/step - ia: 0.3866 - loss: 0.8166 - mae: 0.6652 - rmse: 0.8720 - smape: 1.2760 - val_ia: 0.2489 - val_loss: 0.7541 - val_mae: 0.6294 - val_rmse: 0.6983 - val_smape: 1.2136

Epoch 64/256

1915/1915 - 38s - 20ms/step - ia: 0.3889 - loss: 0.8145 - mae: 0.6637 - rmse: 0.8716 - smape: 1.2724 - val_ia: 0.2471 - val_loss: 0.7544 - val_mae: 0.6367 - val_rmse: 0.7053 - val_smape: 1.2441

Epoch 65/256

1915/1915 - 31s - 16ms/step - ia: 0.3846 - loss: 0.8147 - mae: 0.6644 - rmse: 0.8712 - smape: 1.2752 - val_ia: 0.2476 - val_loss: 0.7543 - val_mae: 0.6369 - val_rmse: 0.7062 - val_smape: 1.2389

Epoch 66/256

1915/1915 - 38s - 20ms/step - ia: 0.3898 - loss: 0.8133 - mae: 0.6633 - rmse: 0.8699 - smape: 1.2722 - val_ia: 0.2479 - val_loss: 0.7530 - val_mae: 0.6334 - val_rmse: 0.7024 - val_smape: 1.2307

Epoch 67/256

1915/1915 - 39s - 21ms/step - ia: 0.3882 - loss: 0.8149 - mae: 0.6638 - rmse: 0.8701 - smape: 1.2738 - val_ia: 0.2472 - val_loss: 0.7540 - val_mae: 0.6386 - val_rmse: 0.7075 - val_smape: 1.2462

Epoch 68/256

1915/1915 - 39s - 20ms/step - ia: 0.3882 - loss: 0.8124 - mae: 0.6635 - rmse: 0.8699 - smape: 1.2734 - val_ia: 0.2470 - val_loss: 0.7545 - val_mae: 0.6390 - val_rmse: 0.7082 - val_smape: 1.2468

Epoch 69/256

1915/1915 - 38s - 20ms/step - ia: 0.3900 - loss: 0.8128 - mae: 0.6622 - rmse: 0.8694 - smape: 1.2700 - val_ia: 0.2474 - val_loss: 0.7528 - val_mae: 0.6368 - val_rmse: 0.7057 - val_smape: 1.2427

Epoch 70/256

1915/1915 - 38s - 20ms/step - ia: 0.3899 - loss: 0.8135 - mae: 0.6633 - rmse: 0.8707 - smape: 1.2718 - val_ia: 0.2472 - val_loss: 0.7522 - val_mae: 0.6353 - val_rmse: 0.7036 - val_smape: 1.2434

Epoch 71/256

1915/1915 - 39s - 20ms/step - ia: 0.3888 - loss: 0.8132 - mae: 0.6627 - rmse: 0.8692 - smape: 1.2731 - val_ia: 0.2472 - val_loss: 0.7522 - val_mae: 0.6364 - val_rmse: 0.7050 - val_smape: 1.2440

Epoch 72/256

1915/1915 - 38s - 20ms/step - ia: 0.3907 - loss: 0.8112 - mae: 0.6619 - rmse: 0.8693 - smape: 1.2692 - val_ia: 0.2476 - val_loss: 0.7519 - val_mae: 0.6354 - val_rmse: 0.7044 - val_smape: 1.2392

Epoch 73/256

1915/1915 - 38s - 20ms/step - ia: 0.3896 - loss: 0.8114 - mae: 0.6620 - rmse: 0.8688 - smape: 1.2733 - val_ia: 0.2450 - val_loss: 0.7624 - val_mae: 0.6506 - val_rmse: 0.7197 - val_smape: 1.2758

Epoch 74/256

1915/1915 - 41s - 21ms/step - ia: 0.3905 - loss: 0.8125 - mae: 0.6623 - rmse: 0.8690 - smape: 1.2701 - val_ia: 0.2477 - val_loss: 0.7520 - val_mae: 0.6368 - val_rmse: 0.7062 - val_smape: 1.2400

Epoch 75/256

1915/1915 - 38s - 20ms/step - ia: 0.3909 - loss: 0.8103 - mae: 0.6611 - rmse: 0.8692 - smape: 1.2689 - val_ia: 0.2477 - val_loss: 0.7519 - val_mae: 0.6372 - val_rmse: 0.7066 - val_smape: 1.2405

Epoch 76/256

1915/1915 - 33s - 17ms/step - ia: 0.3926 - loss: 0.8106 - mae: 0.6613 - rmse: 0.8692 - smape: 1.2653 - val_ia: 0.2483 - val_loss: 0.7502 - val_mae: 0.6317 - val_rmse: 0.7008 - val_smape: 1.2264

Epoch 77/256

1915/1915 - 38s - 20ms/step - ia: 0.3925 - loss: 0.8115 - mae: 0.6617 - rmse: 0.8681 - smape: 1.2693 - val_ia: 0.2462 - val_loss: 0.7538 - val_mae: 0.6417 - val_rmse: 0.7104 - val_smape: 1.2603

Epoch 78/256

1915/1915 - 38s - 20ms/step - ia: 0.3916 - loss: 0.8090 - mae: 0.6609 - rmse: 0.8672 - smape: 1.2710 - val_ia: 0.2502 - val_loss: 0.7506 - val_mae: 0.6273 - val_rmse: 0.6969 - val_smape: 1.2059

Epoch 79/256

1915/1915 - 39s - 20ms/step - ia: 0.3908 - loss: 0.8107 - mae: 0.6616 - rmse: 0.8680 - smape: 1.2673 - val_ia: 0.2476 - val_loss: 0.7512 - val_mae: 0.6365 - val_rmse: 0.7060 - val_smape: 1.2399

Epoch 80/256

1915/1915 - 39s - 21ms/step - ia: 0.3930 - loss: 0.8091 - mae: 0.6608 - rmse: 0.8681 - smape: 1.2695 - val_ia: 0.2470 - val_loss: 0.7524 - val_mae: 0.6388 - val_rmse: 0.7081 - val_smape: 1.2478

Epoch 81/256

1915/1915 - 38s - 20ms/step - ia: 0.3929 - loss: 0.8105 - mae: 0.6610 - rmse: 0.8678 - smape: 1.2672 - val_ia: 0.2475 - val_loss: 0.7503 - val_mae: 0.6366 - val_rmse: 0.7058 - val_smape: 1.2422

Epoch 82/256

1915/1915 - 38s - 20ms/step - ia: 0.3926 - loss: 0.8094 - mae: 0.6609 - rmse: 0.8678 - smape: 1.2683 - val_ia: 0.2472 - val_loss: 0.7513 - val_mae: 0.6387 - val_rmse: 0.7080 - val_smape: 1.2476

Epoch 83/256

1915/1915 - 38s - 20ms/step - ia: 0.3933 - loss: 0.8073 - mae: 0.6595 - rmse: 0.8658 - smape: 1.2671 - val_ia: 0.2471 - val_loss: 0.7515 - val_mae: 0.6388 - val_rmse: 0.7081 - val_smape: 1.2478

Epoch 84/256

1915/1915 - 40s - 21ms/step - ia: 0.3944 - loss: 0.8084 - mae: 0.6603 - rmse: 0.8683 - smape: 1.2668 - val_ia: 0.2481 - val_loss: 0.7491 - val_mae: 0.6340 - val_rmse: 0.7034 - val_smape: 1.2335

Epoch 85/256

1915/1915 - 39s - 20ms/step - ia: 0.3940 - loss: 0.8088 - mae: 0.6605 - rmse: 0.8675 - smape: 1.2674 - val_ia: 0.2494 - val_loss: 0.7475 - val_mae: 0.6285 - val_rmse: 0.6977 - val_smape: 1.2156

Epoch 86/256

1915/1915 - 39s - 20ms/step - ia: 0.3970 - loss: 0.8067 - mae: 0.6592 - rmse: 0.8666 - smape: 1.2651 - val_ia: 0.2461 - val_loss: 0.7545 - val_mae: 0.6442 - val_rmse: 0.7132 - val_smape: 1.2637

Epoch 87/256

1915/1915 - 39s - 20ms/step - ia: 0.3943 - loss: 0.8065 - mae: 0.6598 - rmse: 0.8667 - smape: 1.2664 - val_ia: 0.2460 - val_loss: 0.7530 - val_mae: 0.6433 - val_rmse: 0.7119 - val_smape: 1.2678

Epoch 88/256

1915/1915 - 38s - 20ms/step - ia: 0.3923 - loss: 0.8062 - mae: 0.6595 - rmse: 0.8655 - smape: 1.2688 - val_ia: 0.2480 - val_loss: 0.7498 - val_mae: 0.6360 - val_rmse: 0.7059 - val_smape: 1.2360

Epoch 89/256

1915/1915 - 41s - 21ms/step - ia: 0.3964 - loss: 0.8062 - mae: 0.6589 - rmse: 0.8665 - smape: 1.2620 - val_ia: 0.2487 - val_loss: 0.7464 - val_mae: 0.6303 - val_rmse: 0.6995 - val_smape: 1.2254

Epoch 90/256

1915/1915 - 41s - 21ms/step - ia: 0.3941 - loss: 0.8060 - mae: 0.6588 - rmse: 0.8649 - smape: 1.2656 - val_ia: 0.2468 - val_loss: 0.7515 - val_mae: 0.6403 - val_rmse: 0.7096 - val_smape: 1.2533

Epoch 91/256

1915/1915 - 38s - 20ms/step - ia: 0.3947 - loss: 0.8057 - mae: 0.6594 - rmse: 0.8646 - smape: 1.2654 - val_ia: 0.2468 - val_loss: 0.7513 - val_mae: 0.6405 - val_rmse: 0.7098 - val_smape: 1.2538

Epoch 92/256

1915/1915 - 34s - 18ms/step - ia: 0.3962 - loss: 0.8049 - mae: 0.6589 - rmse: 0.8641 - smape: 1.2655 - val_ia: 0.2493 - val_loss: 0.7462 - val_mae: 0.6303 - val_rmse: 0.7001 - val_smape: 1.2217

Epoch 93/256

1915/1915 - 37s - 19ms/step - ia: 0.3926 - loss: 0.8057 - mae: 0.6590 - rmse: 0.8655 - smape: 1.2666 - val_ia: 0.2481 - val_loss: 0.7490 - val_mae: 0.6364 - val_rmse: 0.7063 - val_smape: 1.2371

Epoch 94/256

1915/1915 - 40s - 21ms/step - ia: 0.3961 - loss: 0.8055 - mae: 0.6587 - rmse: 0.8668 - smape: 1.2634 - val_ia: 0.2471 - val_loss: 0.7490 - val_mae: 0.6376 - val_rmse: 0.7066 - val_smape: 1.2498

Epoch 95/256

1915/1915 - 37s - 19ms/step - ia: 0.3955 - loss: 0.8045 - mae: 0.6588 - rmse: 0.8643 - smape: 1.2662 - val_ia: 0.2467 - val_loss: 0.7524 - val_mae: 0.6417 - val_rmse: 0.7112 - val_smape: 1.2540

Epoch 96/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 45s - 47ms/step - ia: 0.2470 - loss: 1.0006 - mae: 0.7463 - rmse: 0.9787 - smape: 1.5056 - val_ia: 0.2505 - val_loss: 0.8213 - val_mae: 0.6849 - val_rmse: 0.7764 - val_smape: 1.3335

Epoch 2/256

958/958 - 32s - 33ms/step - ia: 0.3601 - loss: 0.8662 - mae: 0.6881 - rmse: 0.9120 - smape: 1.3020 - val_ia: 0.2555 - val_loss: 0.7843 - val_mae: 0.6458 - val_rmse: 0.7352 - val_smape: 1.2626

Epoch 3/256

958/958 - 28s - 30ms/step - ia: 0.3685 - loss: 0.8469 - mae: 0.6787 - rmse: 0.9030 - smape: 1.2896 - val_ia: 0.2554 - val_loss: 0.7746 - val_mae: 0.6565 - val_rmse: 0.7475 - val_smape: 1.2983

Epoch 4/256

958/958 - 32s - 33ms/step - ia: 0.3733 - loss: 0.8363 - mae: 0.6739 - rmse: 0.8957 - smape: 1.2828 - val_ia: 0.2555 - val_loss: 0.7799 - val_mae: 0.6679 - val_rmse: 0.7612 - val_smape: 1.3175

Epoch 5/256

958/958 - 31s - 32ms/step - ia: 0.3784 - loss: 0.8275 - mae: 0.6704 - rmse: 0.8924 - smape: 1.2828 - val_ia: 0.2597 - val_loss: 0.7661 - val_mae: 0.6401 - val_rmse: 0.7389 - val_smape: 1.1991

Epoch 6/256

958/958 - 33s - 34ms/step - ia: 0.3802 - loss: 0.8273 - mae: 0.6694 - rmse: 0.8919 - smape: 1.2780 - val_ia: 0.2574 - val_loss: 0.7577 - val_mae: 0.6418 - val_rmse: 0.7361 - val_smape: 1.2509

Epoch 7/256

958/958 - 31s - 33ms/step - ia: 0.3864 - loss: 0.8210 - mae: 0.6657 - rmse: 0.8883 - smape: 1.2700 - val_ia: 0.2555 - val_loss: 0.7598 - val_mae: 0.6392 - val_rmse: 0.7291 - val_smape: 1.2674

Epoch 8/256

958/958 - 39s - 41ms/step - ia: 0.3872 - loss: 0.8148 - mae: 0.6643 - rmse: 0.8852 - smape: 1.2722 - val_ia: 0.2573 - val_loss: 0.7562 - val_mae: 0.6367 - val_rmse: 0.7318 - val_smape: 1.2172

Epoch 9/256

958/958 - 42s - 44ms/step - ia: 0.3911 - loss: 0.8124 - mae: 0.6623 - rmse: 0.8843 - smape: 1.2629 - val_ia: 0.2586 - val_loss: 0.7536 - val_mae: 0.6425 - val_rmse: 0.7381 - val_smape: 1.2576

Epoch 10/256

958/958 - 32s - 33ms/step - ia: 0.3928 - loss: 0.8113 - mae: 0.6615 - rmse: 0.8822 - smape: 1.2619 - val_ia: 0.2589 - val_loss: 0.7543 - val_mae: 0.6382 - val_rmse: 0.7345 - val_smape: 1.2343

Epoch 11/256

958/958 - 38s - 39ms/step - ia: 0.3956 - loss: 0.8088 - mae: 0.6600 - rmse: 0.8816 - smape: 1.2571 - val_ia: 0.2570 - val_loss: 0.7474 - val_mae: 0.6281 - val_rmse: 0.7217 - val_smape: 1.2233

Epoch 12/256

958/958 - 28s - 29ms/step - ia: 0.3965 - loss: 0.8055 - mae: 0.6599 - rmse: 0.8801 - smape: 1.2623 - val_ia: 0.2588 - val_loss: 0.7536 - val_mae: 0.6453 - val_rmse: 0.7397 - val_smape: 1.2664

Epoch 13/256

958/958 - 44s - 46ms/step - ia: 0.3964 - loss: 0.8062 - mae: 0.6599 - rmse: 0.8805 - smape: 1.2566 - val_ia: 0.2615 - val_loss: 0.7633 - val_mae: 0.6358 - val_rmse: 0.7347 - val_smape: 1.2146

Epoch 14/256

958/958 - 33s - 34ms/step - ia: 0.3962 - loss: 0.8022 - mae: 0.6581 - rmse: 0.8781 - smape: 1.2602 - val_ia: 0.2558 - val_loss: 0.7512 - val_mae: 0.6311 - val_rmse: 0.7216 - val_smape: 1.2451

Epoch 15/256

958/958 - 33s - 34ms/step - ia: 0.4026 - loss: 0.7994 - mae: 0.6552 - rmse: 0.8763 - smape: 1.2507 - val_ia: 0.2611 - val_loss: 0.7839 - val_mae: 0.6583 - val_rmse: 0.7579 - val_smape: 1.2501

Epoch 16/256

958/958 - 31s - 32ms/step - ia: 0.4036 - loss: 0.7972 - mae: 0.6553 - rmse: 0.8739 - smape: 1.2495 - val_ia: 0.2593 - val_loss: 0.7469 - val_mae: 0.6256 - val_rmse: 0.7216 - val_smape: 1.1979

Epoch 17/256

958/958 - 41s - 43ms/step - ia: 0.4017 - loss: 0.7986 - mae: 0.6553 - rmse: 0.8747 - smape: 1.2540 - val_ia: 0.2587 - val_loss: 0.7476 - val_mae: 0.6403 - val_rmse: 0.7330 - val_smape: 1.2823

Epoch 18/256

958/958 - 32s - 33ms/step - ia: 0.4034 - loss: 0.7980 - mae: 0.6545 - rmse: 0.8760 - smape: 1.2525 - val_ia: 0.2585 - val_loss: 0.7490 - val_mae: 0.6306 - val_rmse: 0.7252 - val_smape: 1.2185

Epoch 19/256

958/958 - 32s - 33ms/step - ia: 0.4056 - loss: 0.7934 - mae: 0.6533 - rmse: 0.8716 - smape: 1.2503 - val_ia: 0.2606 - val_loss: 0.7604 - val_mae: 0.6362 - val_rmse: 0.7346 - val_smape: 1.2197

Epoch 20/256

958/958 - 27s - 28ms/step - ia: 0.4066 - loss: 0.7913 - mae: 0.6516 - rmse: 0.8713 - smape: 1.2470 - val_ia: 0.2612 - val_loss: 0.7490 - val_mae: 0.6353 - val_rmse: 0.7304 - val_smape: 1.2585

Epoch 21/256

958/958 - 31s - 33ms/step - ia: 0.4079 - loss: 0.7911 - mae: 0.6513 - rmse: 0.8719 - smape: 1.2459 - val_ia: 0.2621 - val_loss: 0.7639 - val_mae: 0.6485 - val_rmse: 0.7471 - val_smape: 1.2528

Epoch 22/256

958/958 - 32s - 33ms/step - ia: 0.4089 - loss: 0.7880 - mae: 0.6510 - rmse: 0.8700 - smape: 1.2461 - val_ia: 0.2638 - val_loss: 0.7610 - val_mae: 0.6385 - val_rmse: 0.7391 - val_smape: 1.2203

Epoch 23/256

958/958 - 41s - 43ms/step - ia: 0.4123 - loss: 0.7868 - mae: 0.6490 - rmse: 0.8684 - smape: 1.2437 - val_ia: 0.2619 - val_loss: 0.7463 - val_mae: 0.6369 - val_rmse: 0.7323 - val_smape: 1.2408

Epoch 24/256

958/958 - 41s - 42ms/step - ia: 0.4101 - loss: 0.7852 - mae: 0.6499 - rmse: 0.8685 - smape: 1.2472 - val_ia: 0.2634 - val_loss: 0.7621 - val_mae: 0.6434 - val_rmse: 0.7429 - val_smape: 1.2398

Epoch 25/256

958/958 - 42s - 43ms/step - ia: 0.4130 - loss: 0.7836 - mae: 0.6477 - rmse: 0.8672 - smape: 1.2426 - val_ia: 0.2635 - val_loss: 0.7448 - val_mae: 0.6325 - val_rmse: 0.7293 - val_smape: 1.2396

Epoch 26/256

958/958 - 31s - 33ms/step - ia: 0.4136 - loss: 0.7825 - mae: 0.6473 - rmse: 0.8661 - smape: 1.2393 - val_ia: 0.2642 - val_loss: 0.7531 - val_mae: 0.6243 - val_rmse: 0.7228 - val_smape: 1.1792

Epoch 27/256

958/958 - 31s - 33ms/step - ia: 0.4170 - loss: 0.7774 - mae: 0.6449 - rmse: 0.8629 - smape: 1.2353 - val_ia: 0.2619 - val_loss: 0.7463 - val_mae: 0.6316 - val_rmse: 0.7267 - val_smape: 1.2348

Epoch 28/256

958/958 - 26s - 27ms/step - ia: 0.4167 - loss: 0.7790 - mae: 0.6455 - rmse: 0.8646 - smape: 1.2349 - val_ia: 0.2629 - val_loss: 0.7451 - val_mae: 0.6359 - val_rmse: 0.7311 - val_smape: 1.2533

Epoch 29/256

958/958 - 31s - 33ms/step - ia: 0.4145 - loss: 0.7790 - mae: 0.6457 - rmse: 0.8640 - smape: 1.2400 - val_ia: 0.2659 - val_loss: 0.7563 - val_mae: 0.6360 - val_rmse: 0.7352 - val_smape: 1.2388

Epoch 30/256

958/958 - 31s - 33ms/step - ia: 0.4171 - loss: 0.7759 - mae: 0.6450 - rmse: 0.8617 - smape: 1.2378 - val_ia: 0.2664 - val_loss: 0.7501 - val_mae: 0.6274 - val_rmse: 0.7271 - val_smape: 1.2026

Epoch 31/256

958/958 - 41s - 43ms/step - ia: 0.4175 - loss: 0.7745 - mae: 0.6439 - rmse: 0.8621 - smape: 1.2346 - val_ia: 0.2686 - val_loss: 0.7724 - val_mae: 0.6379 - val_rmse: 0.7412 - val_smape: 1.2063

Epoch 32/256

958/958 - 31s - 32ms/step - ia: 0.4198 - loss: 0.7732 - mae: 0.6425 - rmse: 0.8617 - smape: 1.2305 - val_ia: 0.2665 - val_loss: 0.7445 - val_mae: 0.6316 - val_rmse: 0.7295 - val_smape: 1.2203

Epoch 33/256

958/958 - 42s - 44ms/step - ia: 0.4206 - loss: 0.7730 - mae: 0.6426 - rmse: 0.8601 - smape: 1.2305 - val_ia: 0.2671 - val_loss: 0.7754 - val_mae: 0.6489 - val_rmse: 0.7488 - val_smape: 1.2533

Epoch 34/256

958/958 - 31s - 32ms/step - ia: 0.4227 - loss: 0.7708 - mae: 0.6421 - rmse: 0.8604 - smape: 1.2262 - val_ia: 0.2646 - val_loss: 0.7379 - val_mae: 0.6218 - val_rmse: 0.7162 - val_smape: 1.2080

Epoch 35/256

958/958 - 32s - 33ms/step - ia: 0.4219 - loss: 0.7707 - mae: 0.6414 - rmse: 0.8590 - smape: 1.2286 - val_ia: 0.2697 - val_loss: 0.7513 - val_mae: 0.6195 - val_rmse: 0.7194 - val_smape: 1.1785

Epoch 36/256

958/958 - 31s - 33ms/step - ia: 0.4207 - loss: 0.7695 - mae: 0.6410 - rmse: 0.8599 - smape: 1.2303 - val_ia: 0.2686 - val_loss: 0.7963 - val_mae: 0.6550 - val_rmse: 0.7590 - val_smape: 1.2340

Epoch 37/256

958/958 - 31s - 33ms/step - ia: 0.4250 - loss: 0.7663 - mae: 0.6394 - rmse: 0.8571 - smape: 1.2279 - val_ia: 0.2661 - val_loss: 0.7368 - val_mae: 0.6230 - val_rmse: 0.7191 - val_smape: 1.2154

Epoch 38/256

958/958 - 41s - 42ms/step - ia: 0.4256 - loss: 0.7649 - mae: 0.6388 - rmse: 0.8568 - smape: 1.2277 - val_ia: 0.2664 - val_loss: 0.7383 - val_mae: 0.6291 - val_rmse: 0.7257 - val_smape: 1.2274

Epoch 39/256

958/958 - 32s - 33ms/step - ia: 0.4241 - loss: 0.7646 - mae: 0.6394 - rmse: 0.8576 - smape: 1.2309 - val_ia: 0.2678 - val_loss: 0.7354 - val_mae: 0.6178 - val_rmse: 0.7144 - val_smape: 1.1958

Epoch 40/256

958/958 - 32s - 33ms/step - ia: 0.4257 - loss: 0.7647 - mae: 0.6385 - rmse: 0.8557 - smape: 1.2274 - val_ia: 0.2696 - val_loss: 0.7480 - val_mae: 0.6386 - val_rmse: 0.7375 - val_smape: 1.2401

Epoch 41/256

958/958 - 28s - 29ms/step - ia: 0.4273 - loss: 0.7624 - mae: 0.6373 - rmse: 0.8545 - smape: 1.2206 - val_ia: 0.2673 - val_loss: 0.7369 - val_mae: 0.6291 - val_rmse: 0.7254 - val_smape: 1.2492

Epoch 42/256

958/958 - 32s - 33ms/step - ia: 0.4269 - loss: 0.7622 - mae: 0.6371 - rmse: 0.8543 - smape: 1.2218 - val_ia: 0.2683 - val_loss: 0.7629 - val_mae: 0.6398 - val_rmse: 0.7410 - val_smape: 1.2378

Epoch 43/256

958/958 - 31s - 32ms/step - ia: 0.4286 - loss: 0.7585 - mae: 0.6357 - rmse: 0.8534 - smape: 1.2207 - val_ia: 0.2688 - val_loss: 0.7695 - val_mae: 0.6469 - val_rmse: 0.7471 - val_smape: 1.2647

Epoch 44/256

958/958 - 32s - 33ms/step - ia: 0.4273 - loss: 0.7608 - mae: 0.6366 - rmse: 0.8558 - smape: 1.2214 - val_ia: 0.2683 - val_loss: 0.7664 - val_mae: 0.6436 - val_rmse: 0.7437 - val_smape: 1.2508

Epoch 45/256

958/958 - 31s - 33ms/step - ia: 0.4323 - loss: 0.7564 - mae: 0.6347 - rmse: 0.8518 - smape: 1.2163 - val_ia: 0.2645 - val_loss: 0.7316 - val_mae: 0.6238 - val_rmse: 0.7169 - val_smape: 1.2414

Epoch 46/256

958/958 - 31s - 32ms/step - ia: 0.4332 - loss: 0.7527 - mae: 0.6330 - rmse: 0.8490 - smape: 1.2160 - val_ia: 0.2682 - val_loss: 0.7729 - val_mae: 0.6566 - val_rmse: 0.7566 - val_smape: 1.2823

Epoch 47/256

958/958 - 41s - 43ms/step - ia: 0.4339 - loss: 0.7532 - mae: 0.6335 - rmse: 0.8508 - smape: 1.2181 - val_ia: 0.2672 - val_loss: 0.7412 - val_mae: 0.6268 - val_rmse: 0.7235 - val_smape: 1.2264

Epoch 48/256

958/958 - 32s - 33ms/step - ia: 0.4332 - loss: 0.7521 - mae: 0.6337 - rmse: 0.8498 - smape: 1.2200 - val_ia: 0.2705 - val_loss: 0.7611 - val_mae: 0.6379 - val_rmse: 0.7401 - val_smape: 1.2206

Epoch 49/256

958/958 - 39s - 40ms/step - ia: 0.4337 - loss: 0.7527 - mae: 0.6322 - rmse: 0.8506 - smape: 1.2170 - val_ia: 0.2671 - val_loss: 0.7622 - val_mae: 0.6426 - val_rmse: 0.7419 - val_smape: 1.2617

Epoch 50/256

958/958 - 27s - 29ms/step - ia: 0.4341 - loss: 0.7490 - mae: 0.6319 - rmse: 0.8473 - smape: 1.2198 - val_ia: 0.2661 - val_loss: 0.7375 - val_mae: 0.6292 - val_rmse: 0.7257 - val_smape: 1.2523

Epoch 51/256

958/958 - 59s - 62ms/step - ia: 0.4358 - loss: 0.7493 - mae: 0.6315 - rmse: 0.8469 - smape: 1.2183 - val_ia: 0.2647 - val_loss: 0.7426 - val_mae: 0.6361 - val_rmse: 0.7313 - val_smape: 1.2720

Epoch 52/256

958/958 - 41s - 43ms/step - ia: 0.4364 - loss: 0.7489 - mae: 0.6310 - rmse: 0.8474 - smape: 1.2134 - val_ia: 0.2723 - val_loss: 0.7268 - val_mae: 0.6163 - val_rmse: 0.7141 - val_smape: 1.1957

Epoch 53/256

958/958 - 38s - 39ms/step - ia: 0.4371 - loss: 0.7441 - mae: 0.6296 - rmse: 0.8445 - smape: 1.2137 - val_ia: 0.2696 - val_loss: 0.7472 - val_mae: 0.6242 - val_rmse: 0.7243 - val_smape: 1.1974

Epoch 54/256

958/958 - 38s - 40ms/step - ia: 0.4375 - loss: 0.7451 - mae: 0.6297 - rmse: 0.8447 - smape: 1.2155 - val_ia: 0.2701 - val_loss: 0.7479 - val_mae: 0.6298 - val_rmse: 0.7296 - val_smape: 1.2283

Epoch 55/256

958/958 - 34s - 36ms/step - ia: 0.4377 - loss: 0.7455 - mae: 0.6301 - rmse: 0.8464 - smape: 1.2167 - val_ia: 0.2739 - val_loss: 0.7615 - val_mae: 0.6380 - val_rmse: 0.7426 - val_smape: 1.2262

Epoch 56/256

958/958 - 34s - 36ms/step - ia: 0.4392 - loss: 0.7453 - mae: 0.6288 - rmse: 0.8448 - smape: 1.2091 - val_ia: 0.2742 - val_loss: 0.7586 - val_mae: 0.6285 - val_rmse: 0.7327 - val_smape: 1.1919

Epoch 57/256

958/958 - 42s - 44ms/step - ia: 0.4380 - loss: 0.7438 - mae: 0.6287 - rmse: 0.8459 - smape: 1.2113 - val_ia: 0.2741 - val_loss: 0.7829 - val_mae: 0.6462 - val_rmse: 0.7511 - val_smape: 1.2331

Epoch 58/256

958/958 - 38s - 39ms/step - ia: 0.4389 - loss: 0.7412 - mae: 0.6283 - rmse: 0.8433 - smape: 1.2123 - val_ia: 0.2667 - val_loss: 0.7576 - val_mae: 0.6430 - val_rmse: 0.7408 - val_smape: 1.2656

Epoch 59/256

958/958 - 34s - 35ms/step - ia: 0.4408 - loss: 0.7389 - mae: 0.6267 - rmse: 0.8419 - smape: 1.2107 - val_ia: 0.2733 - val_loss: 0.7884 - val_mae: 0.6454 - val_rmse: 0.7502 - val_smape: 1.2359

Epoch 60/256

958/958 - 34s - 35ms/step - ia: 0.4404 - loss: 0.7398 - mae: 0.6268 - rmse: 0.8417 - smape: 1.2126 - val_ia: 0.2698 - val_loss: 0.7728 - val_mae: 0.6501 - val_rmse: 0.7514 - val_smape: 1.2727

Epoch 61/256

958/958 - 33s - 35ms/step - ia: 0.4424 - loss: 0.7389 - mae: 0.6265 - rmse: 0.8425 - smape: 1.2063 - val_ia: 0.2714 - val_loss: 0.7432 - val_mae: 0.6249 - val_rmse: 0.7251 - val_smape: 1.2006

Epoch 62/256

958/958 - 33s - 35ms/step - ia: 0.4419 - loss: 0.7362 - mae: 0.6259 - rmse: 0.8411 - smape: 1.2025 - val_ia: 0.2687 - val_loss: 0.7578 - val_mae: 0.6375 - val_rmse: 0.7367 - val_smape: 1.2412

Epoch 63/256

958/958 - 40s - 42ms/step - ia: 0.4405 - loss: 0.7387 - mae: 0.6265 - rmse: 0.8419 - smape: 1.2063 - val_ia: 0.2689 - val_loss: 0.7727 - val_mae: 0.6511 - val_rmse: 0.7516 - val_smape: 1.2705

Epoch 64/256

958/958 - 33s - 35ms/step - ia: 0.4440 - loss: 0.7344 - mae: 0.6249 - rmse: 0.8398 - smape: 1.2066 - val_ia: 0.2716 - val_loss: 0.7519 - val_mae: 0.6323 - val_rmse: 0.7322 - val_smape: 1.2367

Epoch 65/256

958/958 - 32s - 34ms/step - ia: 0.4462 - loss: 0.7320 - mae: 0.6235 - rmse: 0.8388 - smape: 1.2067 - val_ia: 0.2694 - val_loss: 0.7641 - val_mae: 0.6371 - val_rmse: 0.7368 - val_smape: 1.2428

Epoch 66/256

958/958 - 42s - 44ms/step - ia: 0.4443 - loss: 0.7312 - mae: 0.6238 - rmse: 0.8378 - smape: 1.2073 - val_ia: 0.2724 - val_loss: 0.7559 - val_mae: 0.6339 - val_rmse: 0.7353 - val_smape: 1.2428

Epoch 67/256

958/958 - 42s - 43ms/step - ia: 0.4460 - loss: 0.7324 - mae: 0.6222 - rmse: 0.8383 - smape: 1.2036 - val_ia: 0.2694 - val_loss: 0.7518 - val_mae: 0.6339 - val_rmse: 0.7320 - val_smape: 1.2394

Epoch 67: early stopping

Restoring model weights from the end of the best epoch: 52.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:05 2s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step

 50%|█████     | 25/50 [9:07:45<25:10:34, 3625.36s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 42s - 44ms/step - ia: 0.2458 - loss: 0.9933 - mae: 0.7446 - rmse: 0.9755 - smape: 1.5087 - val_ia: 0.2550 - val_loss: 0.7975 - val_mae: 0.6618 - val_rmse: 0.7547 - val_smape: 1.2659

Epoch 2/128

958/958 - 45s - 47ms/step - ia: 0.3614 - loss: 0.8622 - mae: 0.6864 - rmse: 0.9112 - smape: 1.2997 - val_ia: 0.2573 - val_loss: 0.7753 - val_mae: 0.6359 - val_rmse: 0.7271 - val_smape: 1.2065

Epoch 3/128

958/958 - 34s - 35ms/step - ia: 0.3687 - loss: 0.8449 - mae: 0.6791 - rmse: 0.9019 - smape: 1.2866 - val_ia: 0.2556 - val_loss: 0.7731 - val_mae: 0.6452 - val_rmse: 0.7350 - val_smape: 1.2672

Epoch 4/128

958/958 - 33s - 34ms/step - ia: 0.3741 - loss: 0.8346 - mae: 0.6748 - rmse: 0.8964 - smape: 1.2855 - val_ia: 0.2577 - val_loss: 0.7609 - val_mae: 0.6364 - val_rmse: 0.7308 - val_smape: 1.2130

Epoch 5/128

958/958 - 34s - 35ms/step - ia: 0.3815 - loss: 0.8272 - mae: 0.6696 - rmse: 0.8927 - smape: 1.2773 - val_ia: 0.2546 - val_loss: 0.7699 - val_mae: 0.6602 - val_rmse: 0.7506 - val_smape: 1.3253

Epoch 6/128

958/958 - 33s - 35ms/step - ia: 0.3818 - loss: 0.8228 - mae: 0.6681 - rmse: 0.8892 - smape: 1.2792 - val_ia: 0.2582 - val_loss: 0.7618 - val_mae: 0.6470 - val_rmse: 0.7420 - val_smape: 1.2487

Epoch 7/128

958/958 - 32s - 34ms/step - ia: 0.3877 - loss: 0.8187 - mae: 0.6654 - rmse: 0.8867 - smape: 1.2707 - val_ia: 0.2570 - val_loss: 0.7530 - val_mae: 0.6295 - val_rmse: 0.7224 - val_smape: 1.2105

Epoch 8/128

958/958 - 41s - 42ms/step - ia: 0.3905 - loss: 0.8161 - mae: 0.6645 - rmse: 0.8858 - smape: 1.2656 - val_ia: 0.2575 - val_loss: 0.7516 - val_mae: 0.6365 - val_rmse: 0.7285 - val_smape: 1.2466

Epoch 9/128

958/958 - 40s - 41ms/step - ia: 0.3895 - loss: 0.8135 - mae: 0.6643 - rmse: 0.8841 - smape: 1.2671 - val_ia: 0.2613 - val_loss: 0.7754 - val_mae: 0.6487 - val_rmse: 0.7478 - val_smape: 1.2357

Epoch 10/128

958/958 - 36s - 37ms/step - ia: 0.3910 - loss: 0.8096 - mae: 0.6608 - rmse: 0.8830 - smape: 1.2649 - val_ia: 0.2597 - val_loss: 0.7748 - val_mae: 0.6511 - val_rmse: 0.7511 - val_smape: 1.1990

Epoch 11/128

958/958 - 34s - 36ms/step - ia: 0.3976 - loss: 0.8062 - mae: 0.6595 - rmse: 0.8791 - smape: 1.2552 - val_ia: 0.2590 - val_loss: 0.7484 - val_mae: 0.6336 - val_rmse: 0.7274 - val_smape: 1.2384

Epoch 12/128

958/958 - 35s - 37ms/step - ia: 0.3961 - loss: 0.8080 - mae: 0.6599 - rmse: 0.8808 - smape: 1.2615 - val_ia: 0.2632 - val_loss: 0.7461 - val_mae: 0.6214 - val_rmse: 0.7190 - val_smape: 1.1694

Epoch 13/128

958/958 - 33s - 35ms/step - ia: 0.3974 - loss: 0.8031 - mae: 0.6580 - rmse: 0.8780 - smape: 1.2597 - val_ia: 0.2612 - val_loss: 0.7637 - val_mae: 0.6541 - val_rmse: 0.7515 - val_smape: 1.2623

Epoch 14/128

958/958 - 35s - 36ms/step - ia: 0.4016 - loss: 0.8009 - mae: 0.6568 - rmse: 0.8772 - smape: 1.2563 - val_ia: 0.2585 - val_loss: 0.7540 - val_mae: 0.6316 - val_rmse: 0.7270 - val_smape: 1.2117

Epoch 15/128

958/958 - 39s - 41ms/step - ia: 0.4004 - loss: 0.7978 - mae: 0.6551 - rmse: 0.8759 - smape: 1.2596 - val_ia: 0.2608 - val_loss: 0.7445 - val_mae: 0.6365 - val_rmse: 0.7307 - val_smape: 1.2527

Epoch 16/128

958/958 - 40s - 41ms/step - ia: 0.4021 - loss: 0.7971 - mae: 0.6552 - rmse: 0.8751 - smape: 1.2557 - val_ia: 0.2651 - val_loss: 0.7718 - val_mae: 0.6453 - val_rmse: 0.7459 - val_smape: 1.2166

Epoch 17/128

958/958 - 30s - 31ms/step - ia: 0.4037 - loss: 0.7949 - mae: 0.6533 - rmse: 0.8744 - smape: 1.2498 - val_ia: 0.2628 - val_loss: 0.7521 - val_mae: 0.6375 - val_rmse: 0.7351 - val_smape: 1.2341

Epoch 18/128

958/958 - 26s - 27ms/step - ia: 0.4037 - loss: 0.7945 - mae: 0.6528 - rmse: 0.8737 - smape: 1.2514 - val_ia: 0.2627 - val_loss: 0.7724 - val_mae: 0.6511 - val_rmse: 0.7492 - val_smape: 1.2615

Epoch 19/128

958/958 - 33s - 35ms/step - ia: 0.4061 - loss: 0.7921 - mae: 0.6524 - rmse: 0.8713 - smape: 1.2493 - val_ia: 0.2628 - val_loss: 0.7507 - val_mae: 0.6326 - val_rmse: 0.7308 - val_smape: 1.2090

Epoch 20/128

958/958 - 33s - 35ms/step - ia: 0.4091 - loss: 0.7882 - mae: 0.6504 - rmse: 0.8694 - smape: 1.2450 - val_ia: 0.2631 - val_loss: 0.7480 - val_mae: 0.6352 - val_rmse: 0.7322 - val_smape: 1.2421

Epoch 21/128

958/958 - 39s - 41ms/step - ia: 0.4083 - loss: 0.7861 - mae: 0.6501 - rmse: 0.8682 - smape: 1.2478 - val_ia: 0.2664 - val_loss: 0.7630 - val_mae: 0.6330 - val_rmse: 0.7352 - val_smape: 1.1814

Epoch 22/128

958/958 - 37s - 38ms/step - ia: 0.4121 - loss: 0.7864 - mae: 0.6491 - rmse: 0.8687 - smape: 1.2411 - val_ia: 0.2648 - val_loss: 0.7714 - val_mae: 0.6497 - val_rmse: 0.7507 - val_smape: 1.2349

Epoch 23/128

958/958 - 38s - 40ms/step - ia: 0.4128 - loss: 0.7825 - mae: 0.6473 - rmse: 0.8662 - smape: 1.2343 - val_ia: 0.2635 - val_loss: 0.7358 - val_mae: 0.6264 - val_rmse: 0.7210 - val_smape: 1.2348

Epoch 24/128

958/958 - 46s - 48ms/step - ia: 0.4112 - loss: 0.7823 - mae: 0.6474 - rmse: 0.8682 - smape: 1.2393 - val_ia: 0.2638 - val_loss: 0.7510 - val_mae: 0.6350 - val_rmse: 0.7333 - val_smape: 1.2259

Epoch 25/128

958/958 - 38s - 39ms/step - ia: 0.4144 - loss: 0.7815 - mae: 0.6464 - rmse: 0.8663 - smape: 1.2358 - val_ia: 0.2632 - val_loss: 0.7435 - val_mae: 0.6393 - val_rmse: 0.7340 - val_smape: 1.2797

Epoch 26/128

958/958 - 33s - 35ms/step - ia: 0.4162 - loss: 0.7795 - mae: 0.6462 - rmse: 0.8655 - smape: 1.2351 - val_ia: 0.2645 - val_loss: 0.7641 - val_mae: 0.6322 - val_rmse: 0.7312 - val_smape: 1.2180

Epoch 27/128

958/958 - 42s - 44ms/step - ia: 0.4152 - loss: 0.7780 - mae: 0.6458 - rmse: 0.8638 - smape: 1.2394 - val_ia: 0.2658 - val_loss: 0.7399 - val_mae: 0.6234 - val_rmse: 0.7208 - val_smape: 1.1992

Epoch 28/128

958/958 - 39s - 41ms/step - ia: 0.4159 - loss: 0.7793 - mae: 0.6457 - rmse: 0.8654 - smape: 1.2384 - val_ia: 0.2651 - val_loss: 0.7446 - val_mae: 0.6349 - val_rmse: 0.7314 - val_smape: 1.2403

Epoch 29/128

958/958 - 45s - 47ms/step - ia: 0.4192 - loss: 0.7758 - mae: 0.6435 - rmse: 0.8626 - smape: 1.2305 - val_ia: 0.2648 - val_loss: 0.7730 - val_mae: 0.6534 - val_rmse: 0.7525 - val_smape: 1.2649

Epoch 30/128

958/958 - 38s - 40ms/step - ia: 0.4196 - loss: 0.7750 - mae: 0.6438 - rmse: 0.8619 - smape: 1.2302 - val_ia: 0.2665 - val_loss: 0.7498 - val_mae: 0.6302 - val_rmse: 0.7285 - val_smape: 1.2134

Epoch 31/128

958/958 - 44s - 46ms/step - ia: 0.4201 - loss: 0.7741 - mae: 0.6431 - rmse: 0.8610 - smape: 1.2338 - val_ia: 0.2650 - val_loss: 0.7457 - val_mae: 0.6337 - val_rmse: 0.7290 - val_smape: 1.2522

Epoch 32/128

958/958 - 41s - 42ms/step - ia: 0.4215 - loss: 0.7725 - mae: 0.6423 - rmse: 0.8603 - smape: 1.2266 - val_ia: 0.2649 - val_loss: 0.7499 - val_mae: 0.6391 - val_rmse: 0.7350 - val_smape: 1.2605

Epoch 33/128

958/958 - 44s - 46ms/step - ia: 0.4225 - loss: 0.7700 - mae: 0.6421 - rmse: 0.8598 - smape: 1.2274 - val_ia: 0.2662 - val_loss: 0.7463 - val_mae: 0.6267 - val_rmse: 0.7252 - val_smape: 1.2002

Epoch 34/128

958/958 - 51s - 53ms/step - ia: 0.4220 - loss: 0.7687 - mae: 0.6411 - rmse: 0.8592 - smape: 1.2252 - val_ia: 0.2697 - val_loss: 0.7402 - val_mae: 0.6194 - val_rmse: 0.7182 - val_smape: 1.1924

Epoch 35/128

958/958 - 49s - 52ms/step - ia: 0.4227 - loss: 0.7673 - mae: 0.6403 - rmse: 0.8575 - smape: 1.2272 - val_ia: 0.2687 - val_loss: 0.7704 - val_mae: 0.6313 - val_rmse: 0.7338 - val_smape: 1.1852

Epoch 36/128

958/958 - 41s - 43ms/step - ia: 0.4248 - loss: 0.7668 - mae: 0.6399 - rmse: 0.8578 - smape: 1.2238 - val_ia: 0.2620 - val_loss: 0.7445 - val_mae: 0.6422 - val_rmse: 0.7340 - val_smape: 1.3076

Epoch 37/128

958/958 - 38s - 39ms/step - ia: 0.4255 - loss: 0.7665 - mae: 0.6397 - rmse: 0.8577 - smape: 1.2246 - val_ia: 0.2675 - val_loss: 0.7692 - val_mae: 0.6447 - val_rmse: 0.7444 - val_smape: 1.2693

Epoch 38/128

958/958 - 37s - 39ms/step - ia: 0.4269 - loss: 0.7647 - mae: 0.6380 - rmse: 0.8558 - smape: 1.2212 - val_ia: 0.2692 - val_loss: 0.8232 - val_mae: 0.6677 - val_rmse: 0.7749 - val_smape: 1.2559

Epoch 38: early stopping

Restoring model weights from the end of the best epoch: 23.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 4:48 2s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step

 52%|█████▏    | 26/50 [9:32:01<19:49:45, 2974.41s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 18s - 18ms/step - ia: 0.3557 - loss: 0.8872 - mae: 0.7013 - rmse: 0.9236 - smape: 1.3377 - val_ia: 0.2594 - val_loss: 0.7691 - val_mae: 0.6529 - val_rmse: 0.7463 - val_smape: 1.2989

Epoch 2/128

958/958 - 9s - 9ms/step - ia: 0.3791 - loss: 0.8366 - mae: 0.6754 - rmse: 0.8973 - smape: 1.2961 - val_ia: 0.2572 - val_loss: 0.7668 - val_mae: 0.6473 - val_rmse: 0.7399 - val_smape: 1.2844

Epoch 3/128

958/958 - 9s - 10ms/step - ia: 0.3833 - loss: 0.8265 - mae: 0.6696 - rmse: 0.8921 - smape: 1.2917 - val_ia: 0.2574 - val_loss: 0.7599 - val_mae: 0.6472 - val_rmse: 0.7397 - val_smape: 1.2886

Epoch 4/128

958/958 - 11s - 11ms/step - ia: 0.3855 - loss: 0.8201 - mae: 0.6658 - rmse: 0.8889 - smape: 1.2848 - val_ia: 0.2558 - val_loss: 0.7661 - val_mae: 0.6546 - val_rmse: 0.7485 - val_smape: 1.3009

Epoch 5/128

958/958 - 10s - 10ms/step - ia: 0.3885 - loss: 0.8147 - mae: 0.6632 - rmse: 0.8855 - smape: 1.2801 - val_ia: 0.2582 - val_loss: 0.7550 - val_mae: 0.6445 - val_rmse: 0.7382 - val_smape: 1.2702

Epoch 6/128

958/958 - 10s - 10ms/step - ia: 0.3907 - loss: 0.8111 - mae: 0.6619 - rmse: 0.8828 - smape: 1.2748 - val_ia: 0.2565 - val_loss: 0.7515 - val_mae: 0.6388 - val_rmse: 0.7323 - val_smape: 1.2620

Epoch 7/128

958/958 - 9s - 9ms/step - ia: 0.3955 - loss: 0.8058 - mae: 0.6582 - rmse: 0.8802 - smape: 1.2696 - val_ia: 0.2562 - val_loss: 0.7509 - val_mae: 0.6340 - val_rmse: 0.7274 - val_smape: 1.2453

Epoch 8/128

958/958 - 9s - 9ms/step - ia: 0.3996 - loss: 0.8006 - mae: 0.6567 - rmse: 0.8773 - smape: 1.2654 - val_ia: 0.2566 - val_loss: 0.7530 - val_mae: 0.6420 - val_rmse: 0.7353 - val_smape: 1.2775

Epoch 9/128

958/958 - 11s - 11ms/step - ia: 0.4037 - loss: 0.7960 - mae: 0.6535 - rmse: 0.8742 - smape: 1.2570 - val_ia: 0.2596 - val_loss: 0.7481 - val_mae: 0.6278 - val_rmse: 0.7240 - val_smape: 1.2077

Epoch 10/128

958/958 - 10s - 11ms/step - ia: 0.4048 - loss: 0.7945 - mae: 0.6522 - rmse: 0.8729 - smape: 1.2573 - val_ia: 0.2594 - val_loss: 0.7565 - val_mae: 0.6433 - val_rmse: 0.7380 - val_smape: 1.2694

Epoch 11/128

958/958 - 9s - 9ms/step - ia: 0.4100 - loss: 0.7881 - mae: 0.6495 - rmse: 0.8697 - smape: 1.2521 - val_ia: 0.2609 - val_loss: 0.7447 - val_mae: 0.6294 - val_rmse: 0.7245 - val_smape: 1.2352

Epoch 12/128

958/958 - 8s - 9ms/step - ia: 0.4123 - loss: 0.7851 - mae: 0.6467 - rmse: 0.8672 - smape: 1.2475 - val_ia: 0.2605 - val_loss: 0.7622 - val_mae: 0.6433 - val_rmse: 0.7396 - val_smape: 1.2589

Epoch 13/128

958/958 - 11s - 11ms/step - ia: 0.4177 - loss: 0.7773 - mae: 0.6428 - rmse: 0.8632 - smape: 1.2382 - val_ia: 0.2639 - val_loss: 0.7679 - val_mae: 0.6428 - val_rmse: 0.7409 - val_smape: 1.2460

Epoch 14/128

958/958 - 10s - 11ms/step - ia: 0.4197 - loss: 0.7731 - mae: 0.6417 - rmse: 0.8629 - smape: 1.2384 - val_ia: 0.2653 - val_loss: 0.7625 - val_mae: 0.6294 - val_rmse: 0.7284 - val_smape: 1.1985

Epoch 15/128

958/958 - 20s - 21ms/step - ia: 0.4203 - loss: 0.7725 - mae: 0.6411 - rmse: 0.8607 - smape: 1.2337 - val_ia: 0.2633 - val_loss: 0.7501 - val_mae: 0.6311 - val_rmse: 0.7275 - val_smape: 1.2383

Epoch 16/128

958/958 - 9s - 9ms/step - ia: 0.4245 - loss: 0.7672 - mae: 0.6383 - rmse: 0.8579 - smape: 1.2295 - val_ia: 0.2643 - val_loss: 0.7491 - val_mae: 0.6289 - val_rmse: 0.7260 - val_smape: 1.2220

Epoch 17/128

958/958 - 9s - 10ms/step - ia: 0.4283 - loss: 0.7639 - mae: 0.6366 - rmse: 0.8551 - smape: 1.2234 - val_ia: 0.2646 - val_loss: 0.7805 - val_mae: 0.6462 - val_rmse: 0.7468 - val_smape: 1.2326

Epoch 18/128

958/958 - 10s - 11ms/step - ia: 0.4294 - loss: 0.7607 - mae: 0.6344 - rmse: 0.8543 - smape: 1.2188 - val_ia: 0.2691 - val_loss: 0.7522 - val_mae: 0.6284 - val_rmse: 0.7280 - val_smape: 1.2076

Epoch 19/128

958/958 - 10s - 10ms/step - ia: 0.4292 - loss: 0.7610 - mae: 0.6351 - rmse: 0.8542 - smape: 1.2212 - val_ia: 0.2671 - val_loss: 0.7741 - val_mae: 0.6419 - val_rmse: 0.7437 - val_smape: 1.2148

Epoch 20/128

958/958 - 9s - 9ms/step - ia: 0.4330 - loss: 0.7560 - mae: 0.6326 - rmse: 0.8520 - smape: 1.2117 - val_ia: 0.2670 - val_loss: 0.7595 - val_mae: 0.6302 - val_rmse: 0.7294 - val_smape: 1.1994

Epoch 21/128

958/958 - 8s - 8ms/step - ia: 0.4352 - loss: 0.7562 - mae: 0.6326 - rmse: 0.8514 - smape: 1.2128 - val_ia: 0.2643 - val_loss: 0.7596 - val_mae: 0.6451 - val_rmse: 0.7413 - val_smape: 1.2799

Epoch 22/128

958/958 - 10s - 11ms/step - ia: 0.4353 - loss: 0.7524 - mae: 0.6309 - rmse: 0.8486 - smape: 1.2126 - val_ia: 0.2662 - val_loss: 0.7687 - val_mae: 0.6465 - val_rmse: 0.7452 - val_smape: 1.2555

Epoch 23/128

958/958 - 7s - 7ms/step - ia: 0.4376 - loss: 0.7494 - mae: 0.6298 - rmse: 0.8484 - smape: 1.2099 - val_ia: 0.2678 - val_loss: 0.8065 - val_mae: 0.6509 - val_rmse: 0.7561 - val_smape: 1.2072

Epoch 24/128

958/958 - 7s - 7ms/step - ia: 0.4372 - loss: 0.7501 - mae: 0.6301 - rmse: 0.8483 - smape: 1.2081 - val_ia: 0.2659 - val_loss: 0.7775 - val_mae: 0.6511 - val_rmse: 0.7499 - val_smape: 1.2565

Epoch 25/128

958/958 - 9s - 9ms/step - ia: 0.4393 - loss: 0.7471 - mae: 0.6284 - rmse: 0.8464 - smape: 1.2038 - val_ia: 0.2708 - val_loss: 0.7582 - val_mae: 0.6327 - val_rmse: 0.7332 - val_smape: 1.2119

Epoch 26/128

958/958 - 10s - 10ms/step - ia: 0.4393 - loss: 0.7446 - mae: 0.6281 - rmse: 0.8462 - smape: 1.2062 - val_ia: 0.2670 - val_loss: 0.7838 - val_mae: 0.6456 - val_rmse: 0.7465 - val_smape: 1.2313

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:35 706ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 54%|█████▍    | 27/50 [9:36:25<13:48:30, 2161.34s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

958/958 - 30s - 31ms/step - ia: 0.1958 - loss: 1.0469 - mae: 0.7685 - rmse: 1.0007 - smape: 1.6027 - val_ia: 0.2323 - val_loss: 0.9678 - val_mae: 0.7355 - val_rmse: 0.8200 - val_smape: 1.9604

Epoch 2/64

958/958 - 13s - 14ms/step - ia: 0.1758 - loss: 1.0239 - mae: 0.7577 - rmse: 0.9893 - smape: 1.6596 - val_ia: 0.2314 - val_loss: 0.9692 - val_mae: 0.7405 - val_rmse: 0.8246 - val_smape: 1.9367

Epoch 3/64

958/958 - 14s - 15ms/step - ia: 0.1609 - loss: 1.0143 - mae: 0.7553 - rmse: 0.9850 - smape: 1.6989 - val_ia: 0.2324 - val_loss: 0.9657 - val_mae: 0.7348 - val_rmse: 0.8192 - val_smape: 1.9575

Epoch 4/64

958/958 - 14s - 14ms/step - ia: 0.1612 - loss: 1.0036 - mae: 0.7492 - rmse: 0.9794 - smape: 1.7124 - val_ia: 0.2342 - val_loss: 0.9408 - val_mae: 0.7236 - val_rmse: 0.8079 - val_smape: 1.7875

Epoch 5/64

958/958 - 15s - 15ms/step - ia: 0.2482 - loss: 0.9397 - mae: 0.7162 - rmse: 0.9468 - smape: 1.5048 - val_ia: 0.2485 - val_loss: 0.8618 - val_mae: 0.6819 - val_rmse: 0.7737 - val_smape: 1.3352

Epoch 6/64

958/958 - 14s - 14ms/step - ia: 0.3132 - loss: 0.9057 - mae: 0.7036 - rmse: 0.9310 - smape: 1.3692 - val_ia: 0.2497 - val_loss: 0.8466 - val_mae: 0.6786 - val_rmse: 0.7719 - val_smape: 1.3011

Epoch 7/64

958/958 - 14s - 14ms/step - ia: 0.3306 - loss: 0.8924 - mae: 0.6970 - rmse: 0.9257 - smape: 1.3335 - val_ia: 0.2509 - val_loss: 0.8336 - val_mae: 0.6730 - val_rmse: 0.7658 - val_smape: 1.2896

Epoch 8/64

958/958 - 14s - 15ms/step - ia: 0.3366 - loss: 0.8880 - mae: 0.6948 - rmse: 0.9210 - smape: 1.3273 - val_ia: 0.2519 - val_loss: 0.8219 - val_mae: 0.6682 - val_rmse: 0.7606 - val_smape: 1.2791

Epoch 9/64

958/958 - 20s - 21ms/step - ia: 0.3404 - loss: 0.8822 - mae: 0.6928 - rmse: 0.9192 - smape: 1.3198 - val_ia: 0.2529 - val_loss: 0.8176 - val_mae: 0.6684 - val_rmse: 0.7609 - val_smape: 1.2784

Epoch 10/64

958/958 - 20s - 21ms/step - ia: 0.3446 - loss: 0.8772 - mae: 0.6905 - rmse: 0.9179 - smape: 1.3135 - val_ia: 0.2537 - val_loss: 0.8111 - val_mae: 0.6631 - val_rmse: 0.7555 - val_smape: 1.2659

Epoch 11/64

958/958 - 21s - 22ms/step - ia: 0.3503 - loss: 0.8692 - mae: 0.6875 - rmse: 0.9125 - smape: 1.3043 - val_ia: 0.2545 - val_loss: 0.8037 - val_mae: 0.6577 - val_rmse: 0.7501 - val_smape: 1.2510

Epoch 12/64

958/958 - 13s - 14ms/step - ia: 0.3502 - loss: 0.8708 - mae: 0.6879 - rmse: 0.9132 - smape: 1.3065 - val_ia: 0.2549 - val_loss: 0.8021 - val_mae: 0.6599 - val_rmse: 0.7519 - val_smape: 1.2663

Epoch 13/64

958/958 - 20s - 21ms/step - ia: 0.3505 - loss: 0.8664 - mae: 0.6858 - rmse: 0.9119 - smape: 1.3045 - val_ia: 0.2557 - val_loss: 0.7992 - val_mae: 0.6628 - val_rmse: 0.7555 - val_smape: 1.2657

Epoch 14/64

958/958 - 14s - 14ms/step - ia: 0.3544 - loss: 0.8647 - mae: 0.6851 - rmse: 0.9098 - smape: 1.3001 - val_ia: 0.2559 - val_loss: 0.7945 - val_mae: 0.6569 - val_rmse: 0.7493 - val_smape: 1.2552

Epoch 15/64

958/958 - 14s - 14ms/step - ia: 0.3546 - loss: 0.8635 - mae: 0.6844 - rmse: 0.9099 - smape: 1.3027 - val_ia: 0.2558 - val_loss: 0.7934 - val_mae: 0.6599 - val_rmse: 0.7520 - val_smape: 1.2694

Epoch 16/64

958/958 - 14s - 14ms/step - ia: 0.3576 - loss: 0.8590 - mae: 0.6833 - rmse: 0.9069 - smape: 1.2985 - val_ia: 0.2561 - val_loss: 0.7891 - val_mae: 0.6547 - val_rmse: 0.7466 - val_smape: 1.2578

Epoch 17/64

958/958 - 13s - 13ms/step - ia: 0.3583 - loss: 0.8550 - mae: 0.6821 - rmse: 0.9059 - smape: 1.3002 - val_ia: 0.2565 - val_loss: 0.7891 - val_mae: 0.6588 - val_rmse: 0.7518 - val_smape: 1.2593

Epoch 18/64

958/958 - 21s - 22ms/step - ia: 0.3606 - loss: 0.8546 - mae: 0.6814 - rmse: 0.9054 - smape: 1.2941 - val_ia: 0.2565 - val_loss: 0.7836 - val_mae: 0.6507 - val_rmse: 0.7432 - val_smape: 1.2405

Epoch 19/64

958/958 - 13s - 14ms/step - ia: 0.3598 - loss: 0.8538 - mae: 0.6814 - rmse: 0.9048 - smape: 1.3007 - val_ia: 0.2568 - val_loss: 0.7831 - val_mae: 0.6528 - val_rmse: 0.7458 - val_smape: 1.2447

Epoch 20/64

958/958 - 13s - 14ms/step - ia: 0.3594 - loss: 0.8551 - mae: 0.6826 - rmse: 0.9054 - smape: 1.3051 - val_ia: 0.2564 - val_loss: 0.7822 - val_mae: 0.6534 - val_rmse: 0.7453 - val_smape: 1.2614

Epoch 21/64

958/958 - 21s - 21ms/step - ia: 0.3586 - loss: 0.8516 - mae: 0.6808 - rmse: 0.9037 - smape: 1.3042 - val_ia: 0.2565 - val_loss: 0.7787 - val_mae: 0.6487 - val_rmse: 0.7406 - val_smape: 1.2450

Epoch 22/64

958/958 - 14s - 14ms/step - ia: 0.3576 - loss: 0.8554 - mae: 0.6816 - rmse: 0.9058 - smape: 1.3061 - val_ia: 0.2567 - val_loss: 0.7785 - val_mae: 0.6481 - val_rmse: 0.7410 - val_smape: 1.2363

Epoch 23/64

958/958 - 14s - 15ms/step - ia: 0.3662 - loss: 0.8456 - mae: 0.6778 - rmse: 0.9001 - smape: 1.2959 - val_ia: 0.2563 - val_loss: 0.7769 - val_mae: 0.6480 - val_rmse: 0.7398 - val_smape: 1.2518

Epoch 24/64

958/958 - 13s - 14ms/step - ia: 0.3622 - loss: 0.8485 - mae: 0.6787 - rmse: 0.9034 - smape: 1.3038 - val_ia: 0.2564 - val_loss: 0.7779 - val_mae: 0.6518 - val_rmse: 0.7447 - val_smape: 1.2555

Epoch 25/64

958/958 - 13s - 14ms/step - ia: 0.3677 - loss: 0.8408 - mae: 0.6763 - rmse: 0.8986 - smape: 1.2946 - val_ia: 0.2564 - val_loss: 0.7744 - val_mae: 0.6478 - val_rmse: 0.7401 - val_smape: 1.2508

Epoch 26/64

958/958 - 13s - 14ms/step - ia: 0.3651 - loss: 0.8406 - mae: 0.6766 - rmse: 0.8978 - smape: 1.3030 - val_ia: 0.2567 - val_loss: 0.7751 - val_mae: 0.6501 - val_rmse: 0.7436 - val_smape: 1.2487

Epoch 27/64

958/958 - 13s - 14ms/step - ia: 0.3685 - loss: 0.8410 - mae: 0.6763 - rmse: 0.8985 - smape: 1.2977 - val_ia: 0.2561 - val_loss: 0.7706 - val_mae: 0.6416 - val_rmse: 0.7341 - val_smape: 1.2297

Epoch 28/64

958/958 - 20s - 21ms/step - ia: 0.3660 - loss: 0.8419 - mae: 0.6765 - rmse: 0.8995 - smape: 1.3037 - val_ia: 0.2563 - val_loss: 0.7710 - val_mae: 0.6466 - val_rmse: 0.7391 - val_smape: 1.2535

Epoch 29/64

958/958 - 14s - 14ms/step - ia: 0.3642 - loss: 0.8424 - mae: 0.6768 - rmse: 0.8991 - smape: 1.3049 - val_ia: 0.2562 - val_loss: 0.7717 - val_mae: 0.6478 - val_rmse: 0.7406 - val_smape: 1.2565

Epoch 30/64

958/958 - 14s - 14ms/step - ia: 0.3667 - loss: 0.8405 - mae: 0.6760 - rmse: 0.8978 - smape: 1.3053 - val_ia: 0.2563 - val_loss: 0.7712 - val_mae: 0.6480 - val_rmse: 0.7410 - val_smape: 1.2557

Epoch 31/64

958/958 - 13s - 14ms/step - ia: 0.3671 - loss: 0.8384 - mae: 0.6746 - rmse: 0.8981 - smape: 1.3030 - val_ia: 0.2566 - val_loss: 0.7711 - val_mae: 0.6490 - val_rmse: 0.7428 - val_smape: 1.2547

Epoch 32/64

958/958 - 13s - 14ms/step - ia: 0.3715 - loss: 0.8365 - mae: 0.6742 - rmse: 0.8961 - smape: 1.2975 - val_ia: 0.2563 - val_loss: 0.7659 - val_mae: 0.6412 - val_rmse: 0.7341 - val_smape: 1.2418

Epoch 33/64

958/958 - 20s - 21ms/step - ia: 0.3709 - loss: 0.8332 - mae: 0.6730 - rmse: 0.8934 - smape: 1.3000 - val_ia: 0.2565 - val_loss: 0.7686 - val_mae: 0.6470 - val_rmse: 0.7405 - val_smape: 1.2576

Epoch 34/64

958/958 - 14s - 14ms/step - ia: 0.3689 - loss: 0.8359 - mae: 0.6742 - rmse: 0.8981 - smape: 1.3026 - val_ia: 0.2563 - val_loss: 0.7699 - val_mae: 0.6501 - val_rmse: 0.7432 - val_smape: 1.2720

Epoch 35/64

958/958 - 21s - 22ms/step - ia: 0.3714 - loss: 0.8339 - mae: 0.6734 - rmse: 0.8947 - smape: 1.2986 - val_ia: 0.2565 - val_loss: 0.7676 - val_mae: 0.6446 - val_rmse: 0.7381 - val_smape: 1.2473

Epoch 36/64

958/958 - 13s - 13ms/step - ia: 0.3696 - loss: 0.8358 - mae: 0.6733 - rmse: 0.8966 - smape: 1.3020 - val_ia: 0.2564 - val_loss: 0.7705 - val_mae: 0.6488 - val_rmse: 0.7427 - val_smape: 1.2597

Epoch 37/64

958/958 - 21s - 22ms/step - ia: 0.3742 - loss: 0.8315 - mae: 0.6718 - rmse: 0.8936 - smape: 1.2950 - val_ia: 0.2567 - val_loss: 0.7684 - val_mae: 0.6463 - val_rmse: 0.7405 - val_smape: 1.2509

Epoch 38/64

958/958 - 13s - 14ms/step - ia: 0.3708 - loss: 0.8353 - mae: 0.6739 - rmse: 0.8961 - smape: 1.3026 - val_ia: 0.2564 - val_loss: 0.7663 - val_mae: 0.6449 - val_rmse: 0.7381 - val_smape: 1.2568

Epoch 39/64

958/958 - 13s - 14ms/step - ia: 0.3724 - loss: 0.8295 - mae: 0.6716 - rmse: 0.8943 - smape: 1.2973 - val_ia: 0.2567 - val_loss: 0.7675 - val_mae: 0.6461 - val_rmse: 0.7402 - val_smape: 1.2541

Epoch 40/64

958/958 - 21s - 22ms/step - ia: 0.3753 - loss: 0.8277 - mae: 0.6698 - rmse: 0.8908 - smape: 1.2948 - val_ia: 0.2569 - val_loss: 0.7663 - val_mae: 0.6450 - val_rmse: 0.7393 - val_smape: 1.2506

Epoch 41/64

958/958 - 14s - 14ms/step - ia: 0.3729 - loss: 0.8329 - mae: 0.6722 - rmse: 0.8951 - smape: 1.2993 - val_ia: 0.2564 - val_loss: 0.7643 - val_mae: 0.6445 - val_rmse: 0.7374 - val_smape: 1.2653

Epoch 42/64

958/958 - 14s - 14ms/step - ia: 0.3755 - loss: 0.8298 - mae: 0.6712 - rmse: 0.8916 - smape: 1.2997 - val_ia: 0.2569 - val_loss: 0.7655 - val_mae: 0.6446 - val_rmse: 0.7387 - val_smape: 1.2527

Epoch 43/64

958/958 - 13s - 14ms/step - ia: 0.3745 - loss: 0.8316 - mae: 0.6717 - rmse: 0.8935 - smape: 1.2990 - val_ia: 0.2565 - val_loss: 0.7620 - val_mae: 0.6400 - val_rmse: 0.7330 - val_smape: 1.2496

Epoch 44/64

958/958 - 21s - 22ms/step - ia: 0.3765 - loss: 0.8275 - mae: 0.6699 - rmse: 0.8918 - smape: 1.2940 - val_ia: 0.2570 - val_loss: 0.7650 - val_mae: 0.6456 - val_rmse: 0.7397 - val_smape: 1.2594

Epoch 45/64

958/958 - 13s - 14ms/step - ia: 0.3756 - loss: 0.8256 - mae: 0.6709 - rmse: 0.8905 - smape: 1.2959 - val_ia: 0.2569 - val_loss: 0.7644 - val_mae: 0.6443 - val_rmse: 0.7383 - val_smape: 1.2553

Epoch 46/64

958/958 - 14s - 14ms/step - ia: 0.3744 - loss: 0.8271 - mae: 0.6698 - rmse: 0.8916 - smape: 1.2978 - val_ia: 0.2572 - val_loss: 0.7631 - val_mae: 0.6406 - val_rmse: 0.7353 - val_smape: 1.2384

Epoch 47/64

958/958 - 12s - 13ms/step - ia: 0.3765 - loss: 0.8292 - mae: 0.6708 - rmse: 0.8929 - smape: 1.2940 - val_ia: 0.2571 - val_loss: 0.7659 - val_mae: 0.6484 - val_rmse: 0.7424 - val_smape: 1.2712

Epoch 48/64

958/958 - 10s - 10ms/step - ia: 0.3743 - loss: 0.8285 - mae: 0.6702 - rmse: 0.8917 - smape: 1.2990 - val_ia: 0.2574 - val_loss: 0.7662 - val_mae: 0.6459 - val_rmse: 0.7411 - val_smape: 1.2509

Epoch 49/64

958/958 - 9s - 10ms/step - ia: 0.3749 - loss: 0.8281 - mae: 0.6702 - rmse: 0.8920 - smape: 1.2975 - val_ia: 0.2574 - val_loss: 0.7666 - val_mae: 0.6476 - val_rmse: 0.7427 - val_smape: 1.2597

Epoch 50/64

958/958 - 12s - 13ms/step - ia: 0.3763 - loss: 0.8261 - mae: 0.6690 - rmse: 0.8907 - smape: 1.2942 - val_ia: 0.2574 - val_loss: 0.7722 - val_mae: 0.6499 - val_rmse: 0.7462 - val_smape: 1.2520

Epoch 51/64

958/958 - 13s - 14ms/step - ia: 0.3792 - loss: 0.8227 - mae: 0.6685 - rmse: 0.8889 - smape: 1.2917 - val_ia: 0.2576 - val_loss: 0.7622 - val_mae: 0.6416 - val_rmse: 0.7366 - val_smape: 1.2415

Epoch 52/64

958/958 - 13s - 14ms/step - ia: 0.3782 - loss: 0.8251 - mae: 0.6674 - rmse: 0.8904 - smape: 1.2926 - val_ia: 0.2574 - val_loss: 0.7694 - val_mae: 0.6463 - val_rmse: 0.7426 - val_smape: 1.2408

Epoch 53/64

958/958 - 14s - 14ms/step - ia: 0.3792 - loss: 0.8256 - mae: 0.6689 - rmse: 0.8898 - smape: 1.2909 - val_ia: 0.2575 - val_loss: 0.7675 - val_mae: 0.6462 - val_rmse: 0.7419 - val_smape: 1.2483

Epoch 54/64

958/958 - 13s - 13ms/step - ia: 0.3784 - loss: 0.8250 - mae: 0.6692 - rmse: 0.8905 - smape: 1.2914 - val_ia: 0.2574 - val_loss: 0.7652 - val_mae: 0.6453 - val_rmse: 0.7402 - val_smape: 1.2557

Epoch 55/64

958/958 - 14s - 14ms/step - ia: 0.3777 - loss: 0.8264 - mae: 0.6683 - rmse: 0.8901 - smape: 1.2938 - val_ia: 0.2578 - val_loss: 0.7650 - val_mae: 0.6393 - val_rmse: 0.7357 - val_smape: 1.2210

Epoch 56/64

958/958 - 13s - 14ms/step - ia: 0.3810 - loss: 0.8200 - mae: 0.6664 - rmse: 0.8868 - smape: 1.2887 - val_ia: 0.2577 - val_loss: 0.7616 - val_mae: 0.6410 - val_rmse: 0.7361 - val_smape: 1.2431

Epoch 57/64

958/958 - 13s - 14ms/step - ia: 0.3804 - loss: 0.8242 - mae: 0.6673 - rmse: 0.8902 - smape: 1.2861 - val_ia: 0.2578 - val_loss: 0.7622 - val_mae: 0.6440 - val_rmse: 0.7389 - val_smape: 1.2554

Epoch 58/64

958/958 - 13s - 13ms/step - ia: 0.3789 - loss: 0.8226 - mae: 0.6675 - rmse: 0.8890 - smape: 1.2913 - val_ia: 0.2578 - val_loss: 0.7641 - val_mae: 0.6437 - val_rmse: 0.7395 - val_smape: 1.2464

Epoch 59/64

958/958 - 13s - 14ms/step - ia: 0.3821 - loss: 0.8203 - mae: 0.6663 - rmse: 0.8880 - smape: 1.2878 - val_ia: 0.2580 - val_loss: 0.7621 - val_mae: 0.6402 - val_rmse: 0.7362 - val_smape: 1.2331

Epoch 60/64

958/958 - 14s - 14ms/step - ia: 0.3831 - loss: 0.8201 - mae: 0.6659 - rmse: 0.8880 - smape: 1.2856 - val_ia: 0.2579 - val_loss: 0.7614 - val_mae: 0.6418 - val_rmse: 0.7370 - val_smape: 1.2472

Epoch 61/64

958/958 - 14s - 14ms/step - ia: 0.3849 - loss: 0.8164 - mae: 0.6652 - rmse: 0.8854 - smape: 1.2844 - val_ia: 0.2579 - val_loss: 0.7631 - val_mae: 0.6426 - val_rmse: 0.7381 - val_smape: 1.2460

Epoch 62/64

958/958 - 14s - 14ms/step - ia: 0.3812 - loss: 0.8184 - mae: 0.6661 - rmse: 0.8874 - smape: 1.2886 - val_ia: 0.2580 - val_loss: 0.7612 - val_mae: 0.6395 - val_rmse: 0.7355 - val_smape: 1.2360

Epoch 63/64

958/958 - 13s - 13ms/step - ia: 0.3836 - loss: 0.8204 - mae: 0.6659 - rmse: 0.8876 - smape: 1.2856 - val_ia: 0.2580 - val_loss: 0.7623 - val_mae: 0.6415 - val_rmse: 0.7375 - val_smape: 1.2419

Epoch 64/64

958/958 - 14s - 14ms/step - ia: 0.3794 - loss: 0.8210 - mae: 0.6670 - rmse: 0.8871 - smape: 1.2936 - val_ia: 0.2581 - val_loss: 0.7697 - val_mae: 0.6461 - val_rmse: 0.7432 - val_smape: 1.2456

Restoring model weights from the end of the best epoch: 62.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:15 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step

 56%|█████▌    | 28/50 [9:52:25<11:00:15, 1800.72s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 62s - 64ms/step - ia: 0.2181 - loss: 1.0793 - mae: 0.7785 - rmse: 1.0161 - smape: 1.5538 - val_ia: 0.2317 - val_loss: 0.9687 - val_mae: 0.7390 - val_rmse: 0.8233 - val_smape: 1.9581

Epoch 2/256

958/958 - 34s - 35ms/step - ia: 0.1974 - loss: 1.0470 - mae: 0.7671 - rmse: 1.0002 - smape: 1.6065 - val_ia: 0.2341 - val_loss: 0.9636 - val_mae: 0.7271 - val_rmse: 0.8121 - val_smape: 1.7993

Epoch 3/256

958/958 - 35s - 37ms/step - ia: 0.1946 - loss: 1.0088 - mae: 0.7526 - rmse: 0.9823 - smape: 1.6127 - val_ia: 0.2423 - val_loss: 0.8810 - val_mae: 0.6907 - val_rmse: 0.7771 - val_smape: 1.4713

Epoch 4/256

958/958 - 33s - 35ms/step - ia: 0.3151 - loss: 0.9130 - mae: 0.7082 - rmse: 0.9351 - smape: 1.3722 - val_ia: 0.2513 - val_loss: 0.8230 - val_mae: 0.6691 - val_rmse: 0.7618 - val_smape: 1.2833

Epoch 5/256

958/958 - 32s - 34ms/step - ia: 0.3434 - loss: 0.8881 - mae: 0.6978 - rmse: 0.9236 - smape: 1.3249 - val_ia: 0.2535 - val_loss: 0.8042 - val_mae: 0.6579 - val_rmse: 0.7497 - val_smape: 1.2687

Epoch 6/256

958/958 - 33s - 35ms/step - ia: 0.3534 - loss: 0.8735 - mae: 0.6921 - rmse: 0.9155 - smape: 1.3149 - val_ia: 0.2546 - val_loss: 0.7946 - val_mae: 0.6590 - val_rmse: 0.7510 - val_smape: 1.2742

Epoch 7/256

958/958 - 40s - 42ms/step - ia: 0.3571 - loss: 0.8676 - mae: 0.6894 - rmse: 0.9129 - smape: 1.3081 - val_ia: 0.2554 - val_loss: 0.7879 - val_mae: 0.6565 - val_rmse: 0.7483 - val_smape: 1.2757

Epoch 8/256

958/958 - 34s - 35ms/step - ia: 0.3618 - loss: 0.8576 - mae: 0.6837 - rmse: 0.9091 - smape: 1.2985 - val_ia: 0.2550 - val_loss: 0.7886 - val_mae: 0.6621 - val_rmse: 0.7549 - val_smape: 1.2887

Epoch 9/256

958/958 - 34s - 36ms/step - ia: 0.3653 - loss: 0.8536 - mae: 0.6820 - rmse: 0.9058 - smape: 1.2955 - val_ia: 0.2566 - val_loss: 0.7796 - val_mae: 0.6516 - val_rmse: 0.7443 - val_smape: 1.2581

Epoch 10/256

958/958 - 41s - 43ms/step - ia: 0.3677 - loss: 0.8492 - mae: 0.6807 - rmse: 0.9033 - smape: 1.2941 - val_ia: 0.2553 - val_loss: 0.7842 - val_mae: 0.6618 - val_rmse: 0.7551 - val_smape: 1.2873

Epoch 11/256

958/958 - 33s - 35ms/step - ia: 0.3659 - loss: 0.8488 - mae: 0.6810 - rmse: 0.9034 - smape: 1.2962 - val_ia: 0.2567 - val_loss: 0.7738 - val_mae: 0.6461 - val_rmse: 0.7378 - val_smape: 1.2513

Epoch 12/256

958/958 - 33s - 35ms/step - ia: 0.3696 - loss: 0.8453 - mae: 0.6782 - rmse: 0.9012 - smape: 1.2918 - val_ia: 0.2564 - val_loss: 0.7767 - val_mae: 0.6542 - val_rmse: 0.7476 - val_smape: 1.2695

Epoch 13/256

958/958 - 32s - 34ms/step - ia: 0.3721 - loss: 0.8409 - mae: 0.6757 - rmse: 0.8998 - smape: 1.2845 - val_ia: 0.2565 - val_loss: 0.7743 - val_mae: 0.6526 - val_rmse: 0.7455 - val_smape: 1.2697

Epoch 14/256

958/958 - 42s - 44ms/step - ia: 0.3703 - loss: 0.8413 - mae: 0.6766 - rmse: 0.8998 - smape: 1.2888 - val_ia: 0.2566 - val_loss: 0.7704 - val_mae: 0.6403 - val_rmse: 0.7317 - val_smape: 1.2370

Epoch 15/256

958/958 - 33s - 34ms/step - ia: 0.3719 - loss: 0.8382 - mae: 0.6757 - rmse: 0.8981 - smape: 1.2888 - val_ia: 0.2562 - val_loss: 0.7722 - val_mae: 0.6513 - val_rmse: 0.7433 - val_smape: 1.2776

Epoch 16/256

958/958 - 41s - 43ms/step - ia: 0.3732 - loss: 0.8349 - mae: 0.6740 - rmse: 0.8954 - smape: 1.2874 - val_ia: 0.2571 - val_loss: 0.7679 - val_mae: 0.6439 - val_rmse: 0.7366 - val_smape: 1.2486

Epoch 17/256

958/958 - 32s - 33ms/step - ia: 0.3743 - loss: 0.8360 - mae: 0.6738 - rmse: 0.8958 - smape: 1.2876 - val_ia: 0.2570 - val_loss: 0.7706 - val_mae: 0.6497 - val_rmse: 0.7439 - val_smape: 1.2560

Epoch 18/256

958/958 - 42s - 44ms/step - ia: 0.3750 - loss: 0.8335 - mae: 0.6730 - rmse: 0.8962 - smape: 1.2841 - val_ia: 0.2573 - val_loss: 0.7658 - val_mae: 0.6405 - val_rmse: 0.7331 - val_smape: 1.2393

Epoch 19/256

958/958 - 41s - 43ms/step - ia: 0.3773 - loss: 0.8314 - mae: 0.6727 - rmse: 0.8946 - smape: 1.2867 - val_ia: 0.2567 - val_loss: 0.7676 - val_mae: 0.6477 - val_rmse: 0.7407 - val_smape: 1.2622

Epoch 20/256

958/958 - 33s - 35ms/step - ia: 0.3769 - loss: 0.8310 - mae: 0.6718 - rmse: 0.8931 - smape: 1.2847 - val_ia: 0.2567 - val_loss: 0.7671 - val_mae: 0.6473 - val_rmse: 0.7402 - val_smape: 1.2638

Epoch 21/256

958/958 - 33s - 35ms/step - ia: 0.3796 - loss: 0.8266 - mae: 0.6697 - rmse: 0.8907 - smape: 1.2803 - val_ia: 0.2571 - val_loss: 0.7638 - val_mae: 0.6414 - val_rmse: 0.7344 - val_smape: 1.2434

Epoch 22/256

958/958 - 41s - 43ms/step - ia: 0.3779 - loss: 0.8275 - mae: 0.6705 - rmse: 0.8920 - smape: 1.2834 - val_ia: 0.2562 - val_loss: 0.7670 - val_mae: 0.6477 - val_rmse: 0.7393 - val_smape: 1.2773

Epoch 23/256

958/958 - 33s - 35ms/step - ia: 0.3764 - loss: 0.8275 - mae: 0.6709 - rmse: 0.8917 - smape: 1.2872 - val_ia: 0.2570 - val_loss: 0.7700 - val_mae: 0.6510 - val_rmse: 0.7460 - val_smape: 1.2597

Epoch 24/256

958/958 - 33s - 35ms/step - ia: 0.3827 - loss: 0.8259 - mae: 0.6691 - rmse: 0.8915 - smape: 1.2774 - val_ia: 0.2570 - val_loss: 0.7621 - val_mae: 0.6411 - val_rmse: 0.7342 - val_smape: 1.2432

Epoch 25/256

958/958 - 32s - 34ms/step - ia: 0.3806 - loss: 0.8263 - mae: 0.6696 - rmse: 0.8912 - smape: 1.2829 - val_ia: 0.2572 - val_loss: 0.7607 - val_mae: 0.6398 - val_rmse: 0.7322 - val_smape: 1.2466

Epoch 26/256

958/958 - 36s - 38ms/step - ia: 0.3789 - loss: 0.8238 - mae: 0.6692 - rmse: 0.8906 - smape: 1.2821 - val_ia: 0.2573 - val_loss: 0.7686 - val_mae: 0.6476 - val_rmse: 0.7436 - val_smape: 1.2461

Epoch 27/256

958/958 - 32s - 34ms/step - ia: 0.3837 - loss: 0.8205 - mae: 0.6671 - rmse: 0.8885 - smape: 1.2786 - val_ia: 0.2570 - val_loss: 0.7621 - val_mae: 0.6438 - val_rmse: 0.7376 - val_smape: 1.2511

Epoch 28/256

958/958 - 33s - 35ms/step - ia: 0.3822 - loss: 0.8242 - mae: 0.6686 - rmse: 0.8893 - smape: 1.2792 - val_ia: 0.2564 - val_loss: 0.7628 - val_mae: 0.6467 - val_rmse: 0.7392 - val_smape: 1.2718

Epoch 29/256

958/958 - 32s - 33ms/step - ia: 0.3829 - loss: 0.8220 - mae: 0.6677 - rmse: 0.8898 - smape: 1.2782 - val_ia: 0.2559 - val_loss: 0.7669 - val_mae: 0.6536 - val_rmse: 0.7463 - val_smape: 1.2897

Epoch 30/256

958/958 - 30s - 31ms/step - ia: 0.3844 - loss: 0.8197 - mae: 0.6668 - rmse: 0.8873 - smape: 1.2782 - val_ia: 0.2570 - val_loss: 0.7594 - val_mae: 0.6387 - val_rmse: 0.7326 - val_smape: 1.2336

Epoch 31/256

958/958 - 32s - 34ms/step - ia: 0.3822 - loss: 0.8205 - mae: 0.6670 - rmse: 0.8886 - smape: 1.2794 - val_ia: 0.2566 - val_loss: 0.7634 - val_mae: 0.6469 - val_rmse: 0.7405 - val_smape: 1.2621

Epoch 32/256

958/958 - 36s - 38ms/step - ia: 0.3851 - loss: 0.8187 - mae: 0.6660 - rmse: 0.8869 - smape: 1.2740 - val_ia: 0.2574 - val_loss: 0.7572 - val_mae: 0.6360 - val_rmse: 0.7299 - val_smape: 1.2291

Epoch 33/256

958/958 - 32s - 34ms/step - ia: 0.3861 - loss: 0.8160 - mae: 0.6651 - rmse: 0.8858 - smape: 1.2732 - val_ia: 0.2572 - val_loss: 0.7614 - val_mae: 0.6439 - val_rmse: 0.7386 - val_smape: 1.2514

Epoch 34/256

958/958 - 33s - 34ms/step - ia: 0.3878 - loss: 0.8168 - mae: 0.6648 - rmse: 0.8852 - smape: 1.2736 - val_ia: 0.2559 - val_loss: 0.7588 - val_mae: 0.6329 - val_rmse: 0.7246 - val_smape: 1.2278

Epoch 35/256

958/958 - 30s - 32ms/step - ia: 0.3859 - loss: 0.8136 - mae: 0.6646 - rmse: 0.8844 - smape: 1.2759 - val_ia: 0.2585 - val_loss: 0.7602 - val_mae: 0.6390 - val_rmse: 0.7355 - val_smape: 1.2262

Epoch 36/256

958/958 - 32s - 33ms/step - ia: 0.3888 - loss: 0.8133 - mae: 0.6632 - rmse: 0.8842 - smape: 1.2693 - val_ia: 0.2586 - val_loss: 0.7820 - val_mae: 0.6573 - val_rmse: 0.7550 - val_smape: 1.2609

Epoch 37/256

958/958 - 32s - 34ms/step - ia: 0.3889 - loss: 0.8157 - mae: 0.6643 - rmse: 0.8850 - smape: 1.2690 - val_ia: 0.2565 - val_loss: 0.7559 - val_mae: 0.6358 - val_rmse: 0.7288 - val_smape: 1.2349

Epoch 38/256

958/958 - 33s - 34ms/step - ia: 0.3886 - loss: 0.8160 - mae: 0.6648 - rmse: 0.8852 - smape: 1.2718 - val_ia: 0.2570 - val_loss: 0.7550 - val_mae: 0.6392 - val_rmse: 0.7319 - val_smape: 1.2497

Epoch 39/256

958/958 - 41s - 43ms/step - ia: 0.3879 - loss: 0.8157 - mae: 0.6652 - rmse: 0.8856 - smape: 1.2729 - val_ia: 0.2570 - val_loss: 0.7544 - val_mae: 0.6352 - val_rmse: 0.7286 - val_smape: 1.2337

Epoch 40/256

958/958 - 32s - 34ms/step - ia: 0.3889 - loss: 0.8125 - mae: 0.6633 - rmse: 0.8833 - smape: 1.2715 - val_ia: 0.2585 - val_loss: 0.7571 - val_mae: 0.6374 - val_rmse: 0.7335 - val_smape: 1.2243

Epoch 41/256

958/958 - 29s - 31ms/step - ia: 0.3911 - loss: 0.8156 - mae: 0.6637 - rmse: 0.8853 - smape: 1.2652 - val_ia: 0.2578 - val_loss: 0.7536 - val_mae: 0.6370 - val_rmse: 0.7313 - val_smape: 1.2384

Epoch 42/256

958/958 - 32s - 34ms/step - ia: 0.3883 - loss: 0.8128 - mae: 0.6632 - rmse: 0.8845 - smape: 1.2712 - val_ia: 0.2582 - val_loss: 0.7570 - val_mae: 0.6409 - val_rmse: 0.7362 - val_smape: 1.2446

Epoch 43/256

958/958 - 37s - 38ms/step - ia: 0.3904 - loss: 0.8107 - mae: 0.6626 - rmse: 0.8832 - smape: 1.2703 - val_ia: 0.2589 - val_loss: 0.7589 - val_mae: 0.6386 - val_rmse: 0.7353 - val_smape: 1.2262

Epoch 44/256

958/958 - 31s - 33ms/step - ia: 0.3921 - loss: 0.8119 - mae: 0.6621 - rmse: 0.8840 - smape: 1.2672 - val_ia: 0.2585 - val_loss: 0.7588 - val_mae: 0.6419 - val_rmse: 0.7376 - val_smape: 1.2451

Epoch 45/256

958/958 - 31s - 32ms/step - ia: 0.3900 - loss: 0.8117 - mae: 0.6630 - rmse: 0.8840 - smape: 1.2702 - val_ia: 0.2591 - val_loss: 0.7589 - val_mae: 0.6364 - val_rmse: 0.7334 - val_smape: 1.2175

Epoch 46/256

958/958 - 30s - 31ms/step - ia: 0.3913 - loss: 0.8123 - mae: 0.6625 - rmse: 0.8830 - smape: 1.2689 - val_ia: 0.2577 - val_loss: 0.7515 - val_mae: 0.6333 - val_rmse: 0.7274 - val_smape: 1.2270

Epoch 47/256

958/958 - 30s - 32ms/step - ia: 0.3921 - loss: 0.8089 - mae: 0.6612 - rmse: 0.8816 - smape: 1.2653 - val_ia: 0.2596 - val_loss: 0.7512 - val_mae: 0.6300 - val_rmse: 0.7263 - val_smape: 1.2065

Epoch 48/256

958/958 - 31s - 33ms/step - ia: 0.3934 - loss: 0.8094 - mae: 0.6609 - rmse: 0.8814 - smape: 1.2659 - val_ia: 0.2583 - val_loss: 0.7537 - val_mae: 0.6412 - val_rmse: 0.7358 - val_smape: 1.2566

Epoch 49/256

958/958 - 30s - 32ms/step - ia: 0.3929 - loss: 0.8085 - mae: 0.6606 - rmse: 0.8823 - smape: 1.2644 - val_ia: 0.2583 - val_loss: 0.7495 - val_mae: 0.6333 - val_rmse: 0.7276 - val_smape: 1.2352

Epoch 50/256

958/958 - 32s - 33ms/step - ia: 0.3924 - loss: 0.8077 - mae: 0.6607 - rmse: 0.8815 - smape: 1.2693 - val_ia: 0.2593 - val_loss: 0.7563 - val_mae: 0.6364 - val_rmse: 0.7333 - val_smape: 1.2223

Epoch 51/256

958/958 - 33s - 34ms/step - ia: 0.3955 - loss: 0.8077 - mae: 0.6601 - rmse: 0.8812 - smape: 1.2619 - val_ia: 0.2594 - val_loss: 0.7529 - val_mae: 0.6356 - val_rmse: 0.7319 - val_smape: 1.2286

Epoch 52/256

958/958 - 32s - 34ms/step - ia: 0.3957 - loss: 0.8070 - mae: 0.6601 - rmse: 0.8802 - smape: 1.2635 - val_ia: 0.2570 - val_loss: 0.7498 - val_mae: 0.6280 - val_rmse: 0.7213 - val_smape: 1.2129

Epoch 53/256

958/958 - 30s - 31ms/step - ia: 0.3943 - loss: 0.8068 - mae: 0.6600 - rmse: 0.8793 - smape: 1.2652 - val_ia: 0.2592 - val_loss: 0.7515 - val_mae: 0.6341 - val_rmse: 0.7299 - val_smape: 1.2254

Epoch 54/256

958/958 - 32s - 34ms/step - ia: 0.3966 - loss: 0.8055 - mae: 0.6596 - rmse: 0.8806 - smape: 1.2627 - val_ia: 0.2597 - val_loss: 0.7607 - val_mae: 0.6423 - val_rmse: 0.7395 - val_smape: 1.2374

Epoch 55/256

958/958 - 37s - 39ms/step - ia: 0.3954 - loss: 0.8052 - mae: 0.6602 - rmse: 0.8797 - smape: 1.2659 - val_ia: 0.2599 - val_loss: 0.7575 - val_mae: 0.6399 - val_rmse: 0.7371 - val_smape: 1.2330

Epoch 56/256

958/958 - 40s - 42ms/step - ia: 0.3954 - loss: 0.8055 - mae: 0.6592 - rmse: 0.8804 - smape: 1.2658 - val_ia: 0.2598 - val_loss: 0.7523 - val_mae: 0.6316 - val_rmse: 0.7285 - val_smape: 1.2106

Epoch 57/256

958/958 - 32s - 34ms/step - ia: 0.3966 - loss: 0.8050 - mae: 0.6595 - rmse: 0.8807 - smape: 1.2655 - val_ia: 0.2592 - val_loss: 0.7481 - val_mae: 0.6294 - val_rmse: 0.7248 - val_smape: 1.2129

Epoch 58/256

958/958 - 32s - 34ms/step - ia: 0.3957 - loss: 0.8045 - mae: 0.6594 - rmse: 0.8786 - smape: 1.2653 - val_ia: 0.2590 - val_loss: 0.7475 - val_mae: 0.6319 - val_rmse: 0.7268 - val_smape: 1.2304

Epoch 59/256

958/958 - 41s - 43ms/step - ia: 0.3983 - loss: 0.8029 - mae: 0.6583 - rmse: 0.8782 - smape: 1.2611 - val_ia: 0.2592 - val_loss: 0.7479 - val_mae: 0.6279 - val_rmse: 0.7231 - val_smape: 1.2131

Epoch 60/256

958/958 - 31s - 32ms/step - ia: 0.3951 - loss: 0.8042 - mae: 0.6585 - rmse: 0.8790 - smape: 1.2623 - val_ia: 0.2600 - val_loss: 0.7496 - val_mae: 0.6314 - val_rmse: 0.7278 - val_smape: 1.2202

Epoch 61/256

958/958 - 32s - 33ms/step - ia: 0.3967 - loss: 0.8022 - mae: 0.6576 - rmse: 0.8774 - smape: 1.2612 - val_ia: 0.2609 - val_loss: 0.7587 - val_mae: 0.6409 - val_rmse: 0.7388 - val_smape: 1.2373

Epoch 62/256

958/958 - 39s - 41ms/step - ia: 0.3988 - loss: 0.8032 - mae: 0.6583 - rmse: 0.8783 - smape: 1.2596 - val_ia: 0.2599 - val_loss: 0.7477 - val_mae: 0.6315 - val_rmse: 0.7273 - val_smape: 1.2250

Epoch 63/256

958/958 - 32s - 33ms/step - ia: 0.3992 - loss: 0.8006 - mae: 0.6566 - rmse: 0.8769 - smape: 1.2594 - val_ia: 0.2602 - val_loss: 0.7537 - val_mae: 0.6399 - val_rmse: 0.7364 - val_smape: 1.2479

Epoch 64/256

958/958 - 30s - 31ms/step - ia: 0.3980 - loss: 0.8017 - mae: 0.6573 - rmse: 0.8779 - smape: 1.2634 - val_ia: 0.2609 - val_loss: 0.7544 - val_mae: 0.6330 - val_rmse: 0.7310 - val_smape: 1.2144

Epoch 65/256

958/958 - 43s - 45ms/step - ia: 0.3984 - loss: 0.8020 - mae: 0.6573 - rmse: 0.8780 - smape: 1.2609 - val_ia: 0.2601 - val_loss: 0.7468 - val_mae: 0.6306 - val_rmse: 0.7266 - val_smape: 1.2211

Epoch 66/256

958/958 - 41s - 43ms/step - ia: 0.4003 - loss: 0.7995 - mae: 0.6561 - rmse: 0.8765 - smape: 1.2593 - val_ia: 0.2605 - val_loss: 0.7482 - val_mae: 0.6297 - val_rmse: 0.7267 - val_smape: 1.2116

Epoch 67/256

958/958 - 41s - 43ms/step - ia: 0.3989 - loss: 0.8022 - mae: 0.6575 - rmse: 0.8776 - smape: 1.2608 - val_ia: 0.2606 - val_loss: 0.7463 - val_mae: 0.6280 - val_rmse: 0.7248 - val_smape: 1.2077

Epoch 68/256

958/958 - 34s - 35ms/step - ia: 0.3994 - loss: 0.8005 - mae: 0.6569 - rmse: 0.8779 - smape: 1.2591 - val_ia: 0.2620 - val_loss: 0.7667 - val_mae: 0.6411 - val_rmse: 0.7409 - val_smape: 1.2203

Epoch 69/256

958/958 - 30s - 31ms/step - ia: 0.4005 - loss: 0.8014 - mae: 0.6571 - rmse: 0.8772 - smape: 1.2577 - val_ia: 0.2603 - val_loss: 0.7488 - val_mae: 0.6374 - val_rmse: 0.7332 - val_smape: 1.2477

Epoch 70/256

958/958 - 33s - 34ms/step - ia: 0.3997 - loss: 0.8007 - mae: 0.6565 - rmse: 0.8757 - smape: 1.2601 - val_ia: 0.2613 - val_loss: 0.7487 - val_mae: 0.6348 - val_rmse: 0.7319 - val_smape: 1.2326

Epoch 71/256

958/958 - 33s - 34ms/step - ia: 0.4003 - loss: 0.7985 - mae: 0.6560 - rmse: 0.8755 - smape: 1.2582 - val_ia: 0.2612 - val_loss: 0.7550 - val_mae: 0.6427 - val_rmse: 0.7401 - val_smape: 1.2523

Epoch 72/256

958/958 - 40s - 42ms/step - ia: 0.4012 - loss: 0.8001 - mae: 0.6558 - rmse: 0.8763 - smape: 1.2578 - val_ia: 0.2610 - val_loss: 0.7540 - val_mae: 0.6427 - val_rmse: 0.7398 - val_smape: 1.2553

Epoch 73/256

958/958 - 32s - 33ms/step - ia: 0.4028 - loss: 0.7948 - mae: 0.6550 - rmse: 0.8733 - smape: 1.2557 - val_ia: 0.2617 - val_loss: 0.7593 - val_mae: 0.6380 - val_rmse: 0.7367 - val_smape: 1.2272

Epoch 74/256

958/958 - 32s - 33ms/step - ia: 0.4014 - loss: 0.7992 - mae: 0.6553 - rmse: 0.8751 - smape: 1.2568 - val_ia: 0.2598 - val_loss: 0.7430 - val_mae: 0.6332 - val_rmse: 0.7275 - val_smape: 1.2503

Epoch 75/256

958/958 - 35s - 37ms/step - ia: 0.4013 - loss: 0.7967 - mae: 0.6556 - rmse: 0.8752 - smape: 1.2573 - val_ia: 0.2612 - val_loss: 0.7526 - val_mae: 0.6396 - val_rmse: 0.7366 - val_smape: 1.2506

Epoch 76/256

958/958 - 38s - 40ms/step - ia: 0.4009 - loss: 0.7986 - mae: 0.6553 - rmse: 0.8754 - smape: 1.2584 - val_ia: 0.2607 - val_loss: 0.7479 - val_mae: 0.6382 - val_rmse: 0.7339 - val_smape: 1.2551

Epoch 77/256

958/958 - 30s - 31ms/step - ia: 0.4015 - loss: 0.7976 - mae: 0.6558 - rmse: 0.8757 - smape: 1.2615 - val_ia: 0.2619 - val_loss: 0.7519 - val_mae: 0.6382 - val_rmse: 0.7359 - val_smape: 1.2399

Epoch 78/256

958/958 - 34s - 36ms/step - ia: 0.4027 - loss: 0.7953 - mae: 0.6545 - rmse: 0.8749 - smape: 1.2564 - val_ia: 0.2603 - val_loss: 0.7465 - val_mae: 0.6315 - val_rmse: 0.7275 - val_smape: 1.2294

Epoch 79/256

958/958 - 33s - 34ms/step - ia: 0.4019 - loss: 0.7972 - mae: 0.6545 - rmse: 0.8743 - smape: 1.2592 - val_ia: 0.2614 - val_loss: 0.7444 - val_mae: 0.6325 - val_rmse: 0.7290 - val_smape: 1.2354

Epoch 80/256

958/958 - 39s - 41ms/step - ia: 0.4041 - loss: 0.7961 - mae: 0.6545 - rmse: 0.8741 - smape: 1.2555 - val_ia: 0.2607 - val_loss: 0.7475 - val_mae: 0.6309 - val_rmse: 0.7276 - val_smape: 1.2224

Epoch 81/256

958/958 - 29s - 30ms/step - ia: 0.4035 - loss: 0.7939 - mae: 0.6532 - rmse: 0.8722 - smape: 1.2575 - val_ia: 0.2606 - val_loss: 0.7413 - val_mae: 0.6313 - val_rmse: 0.7262 - val_smape: 1.2437

Epoch 82/256

958/958 - 33s - 35ms/step - ia: 0.4040 - loss: 0.7938 - mae: 0.6535 - rmse: 0.8729 - smape: 1.2591 - val_ia: 0.2617 - val_loss: 0.7565 - val_mae: 0.6393 - val_rmse: 0.7376 - val_smape: 1.2336

Epoch 83/256

958/958 - 32s - 33ms/step - ia: 0.4059 - loss: 0.7956 - mae: 0.6537 - rmse: 0.8722 - smape: 1.2531 - val_ia: 0.2614 - val_loss: 0.7458 - val_mae: 0.6335 - val_rmse: 0.7299 - val_smape: 1.2395

Epoch 84/256

958/958 - 30s - 32ms/step - ia: 0.4037 - loss: 0.7936 - mae: 0.6536 - rmse: 0.8736 - smape: 1.2566 - val_ia: 0.2603 - val_loss: 0.7431 - val_mae: 0.6342 - val_rmse: 0.7287 - val_smape: 1.2560

Epoch 85/256

958/958 - 32s - 34ms/step - ia: 0.4046 - loss: 0.7938 - mae: 0.6533 - rmse: 0.8738 - smape: 1.2555 - val_ia: 0.2625 - val_loss: 0.7595 - val_mae: 0.6401 - val_rmse: 0.7388 - val_smape: 1.2298

Epoch 86/256

958/958 - 42s - 43ms/step - ia: 0.4044 - loss: 0.7933 - mae: 0.6533 - rmse: 0.8731 - smape: 1.2556 - val_ia: 0.2623 - val_loss: 0.7528 - val_mae: 0.6371 - val_rmse: 0.7354 - val_smape: 1.2311

Epoch 87/256

958/958 - 33s - 34ms/step - ia: 0.4035 - loss: 0.7950 - mae: 0.6542 - rmse: 0.8737 - smape: 1.2551 - val_ia: 0.2623 - val_loss: 0.7534 - val_mae: 0.6357 - val_rmse: 0.7340 - val_smape: 1.2276

Epoch 88/256

958/958 - 41s - 42ms/step - ia: 0.4064 - loss: 0.7920 - mae: 0.6525 - rmse: 0.8707 - smape: 1.2518 - val_ia: 0.2632 - val_loss: 0.7682 - val_mae: 0.6436 - val_rmse: 0.7438 - val_smape: 1.2277

Epoch 89/256

958/958 - 32s - 34ms/step - ia: 0.4086 - loss: 0.7898 - mae: 0.6520 - rmse: 0.8711 - smape: 1.2486 - val_ia: 0.2611 - val_loss: 0.7560 - val_mae: 0.6338 - val_rmse: 0.7315 - val_smape: 1.2189

Epoch 90/256

958/958 - 32s - 34ms/step - ia: 0.4047 - loss: 0.7929 - mae: 0.6525 - rmse: 0.8729 - smape: 1.2531 - val_ia: 0.2625 - val_loss: 0.7607 - val_mae: 0.6441 - val_rmse: 0.7423 - val_smape: 1.2487

Epoch 91/256

958/958 - 30s - 32ms/step - ia: 0.4053 - loss: 0.7913 - mae: 0.6525 - rmse: 0.8709 - smape: 1.2539 - val_ia: 0.2626 - val_loss: 0.7544 - val_mae: 0.6346 - val_rmse: 0.7330 - val_smape: 1.2251

Epoch 92/256

958/958 - 32s - 34ms/step - ia: 0.4068 - loss: 0.7899 - mae: 0.6517 - rmse: 0.8719 - smape: 1.2514 - val_ia: 0.2619 - val_loss: 0.7513 - val_mae: 0.6367 - val_rmse: 0.7339 - val_smape: 1.2421

Epoch 93/256

958/958 - 32s - 34ms/step - ia: 0.4054 - loss: 0.7915 - mae: 0.6528 - rmse: 0.8715 - smape: 1.2563 - val_ia: 0.2601 - val_loss: 0.7418 - val_mae: 0.6282 - val_rmse: 0.7230 - val_smape: 1.2343

Epoch 94/256

958/958 - 37s - 39ms/step - ia: 0.4062 - loss: 0.7887 - mae: 0.6516 - rmse: 0.8699 - smape: 1.2531 - val_ia: 0.2620 - val_loss: 0.7529 - val_mae: 0.6299 - val_rmse: 0.7282 - val_smape: 1.2054

Epoch 95/256

958/958 - 45s - 47ms/step - ia: 0.4084 - loss: 0.7879 - mae: 0.6501 - rmse: 0.8706 - smape: 1.2512 - val_ia: 0.2625 - val_loss: 0.7485 - val_mae: 0.6289 - val_rmse: 0.7273 - val_smape: 1.2101

Epoch 96/256

958/958 - 41s - 43ms/step - ia: 0.4062 - loss: 0.7905 - mae: 0.6519 - rmse: 0.8701 - smape: 1.2547 - val_ia: 0.2625 - val_loss: 0.7456 - val_mae: 0.6332 - val_rmse: 0.7302 - val_smape: 1.2369

Epoch 96: early stopping

Restoring model weights from the end of the best epoch: 81.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:42 2s/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 27s - 28ms/step - ia: 0.3331 - loss: 0.8988 - mae: 0.7045 - rmse: 0.9289 - smape: 1.3705 - val_ia: 0.2602 - val_loss: 0.7801 - val_mae: 0.6305 - val_rmse: 0.7245 - val_smape: 1.1837

Epoch 2/32

958/958 - 13s - 14ms/step - ia: 0.3791 - loss: 0.8330 - mae: 0.6732 - rmse: 0.8954 - smape: 1.2869 - val_ia: 0.2545 - val_loss: 0.7740 - val_mae: 0.6611 - val_rmse: 0.7520 - val_smape: 1.3320

Epoch 3/32

958/958 - 25s - 26ms/step - ia: 0.3799 - loss: 0.8249 - mae: 0.6692 - rmse: 0.8894 - smape: 1.2865 - val_ia: 0.2563 - val_loss: 0.7631 - val_mae: 0.6456 - val_rmse: 0.7393 - val_smape: 1.2688

Epoch 4/32

958/958 - 19s - 20ms/step - ia: 0.3847 - loss: 0.8193 - mae: 0.6662 - rmse: 0.8881 - smape: 1.2804 - val_ia: 0.2603 - val_loss: 0.7487 - val_mae: 0.6283 - val_rmse: 0.7231 - val_smape: 1.2004

Epoch 5/32

958/958 - 16s - 17ms/step - ia: 0.3894 - loss: 0.8151 - mae: 0.6634 - rmse: 0.8856 - smape: 1.2716 - val_ia: 0.2576 - val_loss: 0.7636 - val_mae: 0.6287 - val_rmse: 0.7263 - val_smape: 1.1860

Epoch 6/32

958/958 - 16s - 17ms/step - ia: 0.3905 - loss: 0.8106 - mae: 0.6618 - rmse: 0.8831 - smape: 1.2736 - val_ia: 0.2587 - val_loss: 0.7514 - val_mae: 0.6424 - val_rmse: 0.7369 - val_smape: 1.2644

Epoch 7/32

958/958 - 16s - 17ms/step - ia: 0.3944 - loss: 0.8074 - mae: 0.6598 - rmse: 0.8807 - smape: 1.2694 - val_ia: 0.2610 - val_loss: 0.7610 - val_mae: 0.6379 - val_rmse: 0.7368 - val_smape: 1.2134

Epoch 8/32

958/958 - 21s - 22ms/step - ia: 0.3986 - loss: 0.8030 - mae: 0.6565 - rmse: 0.8779 - smape: 1.2609 - val_ia: 0.2606 - val_loss: 0.7528 - val_mae: 0.6301 - val_rmse: 0.7280 - val_smape: 1.2050

Epoch 9/32

958/958 - 21s - 21ms/step - ia: 0.4011 - loss: 0.7974 - mae: 0.6550 - rmse: 0.8750 - smape: 1.2625 - val_ia: 0.2618 - val_loss: 0.7710 - val_mae: 0.6434 - val_rmse: 0.7440 - val_smape: 1.2280

Epoch 10/32

958/958 - 17s - 17ms/step - ia: 0.4053 - loss: 0.7937 - mae: 0.6521 - rmse: 0.8717 - smape: 1.2539 - val_ia: 0.2601 - val_loss: 0.7518 - val_mae: 0.6458 - val_rmse: 0.7393 - val_smape: 1.3031

Epoch 11/32

958/958 - 16s - 17ms/step - ia: 0.4048 - loss: 0.7917 - mae: 0.6510 - rmse: 0.8720 - smape: 1.2559 - val_ia: 0.2617 - val_loss: 0.7615 - val_mae: 0.6508 - val_rmse: 0.7464 - val_smape: 1.2910

Epoch 12/32

958/958 - 16s - 17ms/step - ia: 0.4103 - loss: 0.7847 - mae: 0.6479 - rmse: 0.8683 - smape: 1.2479 - val_ia: 0.2632 - val_loss: 0.7539 - val_mae: 0.6219 - val_rmse: 0.7197 - val_smape: 1.1796

Epoch 13/32

958/958 - 20s - 21ms/step - ia: 0.4116 - loss: 0.7838 - mae: 0.6470 - rmse: 0.8676 - smape: 1.2470 - val_ia: 0.2668 - val_loss: 0.7718 - val_mae: 0.6292 - val_rmse: 0.7313 - val_smape: 1.1729

Epoch 14/32

958/958 - 17s - 17ms/step - ia: 0.4152 - loss: 0.7774 - mae: 0.6437 - rmse: 0.8643 - smape: 1.2428 - val_ia: 0.2634 - val_loss: 0.7585 - val_mae: 0.6374 - val_rmse: 0.7364 - val_smape: 1.2310

Epoch 15/32

958/958 - 16s - 17ms/step - ia: 0.4191 - loss: 0.7734 - mae: 0.6420 - rmse: 0.8610 - smape: 1.2381 - val_ia: 0.2612 - val_loss: 0.7425 - val_mae: 0.6330 - val_rmse: 0.7255 - val_smape: 1.2752

Epoch 16/32

958/958 - 17s - 18ms/step - ia: 0.4216 - loss: 0.7719 - mae: 0.6408 - rmse: 0.8602 - smape: 1.2336 - val_ia: 0.2639 - val_loss: 0.7641 - val_mae: 0.6361 - val_rmse: 0.7347 - val_smape: 1.2256

Epoch 17/32

958/958 - 14s - 15ms/step - ia: 0.4235 - loss: 0.7666 - mae: 0.6382 - rmse: 0.8572 - smape: 1.2296 - val_ia: 0.2663 - val_loss: 0.7569 - val_mae: 0.6237 - val_rmse: 0.7226 - val_smape: 1.1887

Epoch 18/32

958/958 - 17s - 17ms/step - ia: 0.4235 - loss: 0.7660 - mae: 0.6377 - rmse: 0.8580 - smape: 1.2277 - val_ia: 0.2660 - val_loss: 0.7673 - val_mae: 0.6421 - val_rmse: 0.7411 - val_smape: 1.2351

Epoch 19/32

958/958 - 17s - 18ms/step - ia: 0.4283 - loss: 0.7614 - mae: 0.6364 - rmse: 0.8542 - smape: 1.2221 - val_ia: 0.2629 - val_loss: 0.7499 - val_mae: 0.6410 - val_rmse: 0.7339 - val_smape: 1.2935

Epoch 20/32

958/958 - 16s - 17ms/step - ia: 0.4285 - loss: 0.7569 - mae: 0.6342 - rmse: 0.8522 - smape: 1.2230 - val_ia: 0.2641 - val_loss: 0.7844 - val_mae: 0.6440 - val_rmse: 0.7462 - val_smape: 1.2099

Epoch 21/32

958/958 - 19s - 20ms/step - ia: 0.4338 - loss: 0.7562 - mae: 0.6330 - rmse: 0.8510 - smape: 1.2137 - val_ia: 0.2664 - val_loss: 0.7595 - val_mae: 0.6301 - val_rmse: 0.7265 - val_smape: 1.2209

Epoch 22/32

958/958 - 15s - 15ms/step - ia: 0.4326 - loss: 0.7563 - mae: 0.6323 - rmse: 0.8511 - smape: 1.2150 - val_ia: 0.2665 - val_loss: 0.7600 - val_mae: 0.6414 - val_rmse: 0.7396 - val_smape: 1.2440

Epoch 23/32

958/958 - 22s - 23ms/step - ia: 0.4340 - loss: 0.7526 - mae: 0.6313 - rmse: 0.8499 - smape: 1.2136 - val_ia: 0.2664 - val_loss: 0.7645 - val_mae: 0.6380 - val_rmse: 0.7367 - val_smape: 1.2270

Epoch 24/32

958/958 - 21s - 22ms/step - ia: 0.4368 - loss: 0.7474 - mae: 0.6291 - rmse: 0.8455 - smape: 1.2094 - val_ia: 0.2670 - val_loss: 0.7840 - val_mae: 0.6435 - val_rmse: 0.7445 - val_smape: 1.2104

Epoch 25/32

958/958 - 16s - 17ms/step - ia: 0.4376 - loss: 0.7476 - mae: 0.6295 - rmse: 0.8462 - smape: 1.2116 - val_ia: 0.2658 - val_loss: 0.7849 - val_mae: 0.6452 - val_rmse: 0.7441 - val_smape: 1.2385

Epoch 26/32

958/958 - 16s - 17ms/step - ia: 0.4377 - loss: 0.7458 - mae: 0.6286 - rmse: 0.8452 - smape: 1.2063 - val_ia: 0.2675 - val_loss: 0.7726 - val_mae: 0.6380 - val_rmse: 0.7369 - val_smape: 1.2264

Epoch 27/32

958/958 - 16s - 17ms/step - ia: 0.4410 - loss: 0.7435 - mae: 0.6272 - rmse: 0.8448 - smape: 1.2057 - val_ia: 0.2658 - val_loss: 0.7796 - val_mae: 0.6447 - val_rmse: 0.7431 - val_smape: 1.2358

Epoch 28/32

958/958 - 21s - 22ms/step - ia: 0.4429 - loss: 0.7377 - mae: 0.6255 - rmse: 0.8408 - smape: 1.2043 - val_ia: 0.2665 - val_loss: 0.7931 - val_mae: 0.6585 - val_rmse: 0.7584 - val_smape: 1.2762

Epoch 29/32

958/958 - 13s - 14ms/step - ia: 0.4441 - loss: 0.7379 - mae: 0.6254 - rmse: 0.8413 - smape: 1.2021 - val_ia: 0.2642 - val_loss: 0.7854 - val_mae: 0.6491 - val_rmse: 0.7464 - val_smape: 1.2589

Epoch 30/32

958/958 - 16s - 16ms/step - ia: 0.4433 - loss: 0.7355 - mae: 0.6242 - rmse: 0.8398 - smape: 1.2003 - val_ia: 0.2665 - val_loss: 0.7854 - val_mae: 0.6434 - val_rmse: 0.7410 - val_smape: 1.2276

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:08 510ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 60%|██████    | 30/50 [10:56:55<9:41:11, 1743.56s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 44s - 46ms/step - ia: 0.3287 - loss: 0.8651 - mae: 0.6861 - rmse: 0.9101 - smape: 1.3843 - val_ia: 0.2566 - val_loss: 0.8178 - val_mae: 0.6810 - val_rmse: 0.7725 - val_smape: 1.3366

Epoch 2/128

958/958 - 41s - 43ms/step - ia: 0.3819 - loss: 0.8142 - mae: 0.6637 - rmse: 0.8835 - smape: 1.2848 - val_ia: 0.2647 - val_loss: 0.8163 - val_mae: 0.6690 - val_rmse: 0.7702 - val_smape: 1.2375

Epoch 3/128

958/958 - 32s - 34ms/step - ia: 0.3965 - loss: 0.7993 - mae: 0.6559 - rmse: 0.8766 - smape: 1.2593 - val_ia: 0.2622 - val_loss: 0.7757 - val_mae: 0.6474 - val_rmse: 0.7429 - val_smape: 1.2419

Epoch 4/128

958/958 - 32s - 34ms/step - ia: 0.4071 - loss: 0.7873 - mae: 0.6495 - rmse: 0.8695 - smape: 1.2405 - val_ia: 0.2659 - val_loss: 0.7995 - val_mae: 0.6711 - val_rmse: 0.7707 - val_smape: 1.2764

Epoch 5/128

958/958 - 33s - 34ms/step - ia: 0.4182 - loss: 0.7732 - mae: 0.6430 - rmse: 0.8602 - smape: 1.2235 - val_ia: 0.2645 - val_loss: 0.8217 - val_mae: 0.6804 - val_rmse: 0.7796 - val_smape: 1.2960

Epoch 6/128

958/958 - 33s - 34ms/step - ia: 0.4230 - loss: 0.7618 - mae: 0.6383 - rmse: 0.8548 - smape: 1.2200 - val_ia: 0.2658 - val_loss: 0.8165 - val_mae: 0.6511 - val_rmse: 0.7543 - val_smape: 1.2175

Epoch 7/128

958/958 - 41s - 43ms/step - ia: 0.4326 - loss: 0.7483 - mae: 0.6323 - rmse: 0.8483 - smape: 1.2086 - val_ia: 0.2651 - val_loss: 0.8269 - val_mae: 0.6647 - val_rmse: 0.7674 - val_smape: 1.2571

Epoch 8/128

958/958 - 33s - 35ms/step - ia: 0.4392 - loss: 0.7408 - mae: 0.6277 - rmse: 0.8430 - smape: 1.1993 - val_ia: 0.2674 - val_loss: 0.8369 - val_mae: 0.6540 - val_rmse: 0.7570 - val_smape: 1.2571

Epoch 9/128

958/958 - 30s - 32ms/step - ia: 0.4438 - loss: 0.7280 - mae: 0.6225 - rmse: 0.8362 - smape: 1.1943 - val_ia: 0.2689 - val_loss: 0.8206 - val_mae: 0.6648 - val_rmse: 0.7680 - val_smape: 1.2797

Epoch 10/128

958/958 - 32s - 34ms/step - ia: 0.4470 - loss: 0.7179 - mae: 0.6200 - rmse: 0.8315 - smape: 1.2002 - val_ia: 0.2732 - val_loss: 0.8503 - val_mae: 0.6671 - val_rmse: 0.7741 - val_smape: 1.2652

Epoch 11/128

958/958 - 41s - 43ms/step - ia: 0.4528 - loss: 0.7078 - mae: 0.6164 - rmse: 0.8248 - smape: 1.1921 - val_ia: 0.2706 - val_loss: 0.8458 - val_mae: 0.6619 - val_rmse: 0.7702 - val_smape: 1.2717

Epoch 12/128

958/958 - 30s - 31ms/step - ia: 0.4596 - loss: 0.6950 - mae: 0.6100 - rmse: 0.8172 - smape: 1.1844 - val_ia: 0.2656 - val_loss: 0.8571 - val_mae: 0.6791 - val_rmse: 0.7845 - val_smape: 1.3195

Epoch 13/128

958/958 - 40s - 41ms/step - ia: 0.4624 - loss: 0.6885 - mae: 0.6068 - rmse: 0.8137 - smape: 1.1882 - val_ia: 0.2635 - val_loss: 0.8597 - val_mae: 0.6684 - val_rmse: 0.7674 - val_smape: 1.3142

Epoch 14/128

958/958 - 33s - 34ms/step - ia: 0.4691 - loss: 0.6747 - mae: 0.6019 - rmse: 0.8062 - smape: 1.1800 - val_ia: 0.2639 - val_loss: 0.9388 - val_mae: 0.6891 - val_rmse: 0.7983 - val_smape: 1.2945

Epoch 15/128

958/958 - 36s - 38ms/step - ia: 0.4750 - loss: 0.6621 - mae: 0.5970 - rmse: 0.7975 - smape: 1.1747 - val_ia: 0.2648 - val_loss: 0.9176 - val_mae: 0.6859 - val_rmse: 0.7936 - val_smape: 1.3111

Epoch 16/128

958/958 - 33s - 35ms/step - ia: 0.4795 - loss: 0.6524 - mae: 0.5938 - rmse: 0.7933 - smape: 1.1696 - val_ia: 0.2644 - val_loss: 0.9434 - val_mae: 0.6945 - val_rmse: 0.8059 - val_smape: 1.3090

Epoch 17/128

958/958 - 42s - 44ms/step - ia: 0.4820 - loss: 0.6431 - mae: 0.5900 - rmse: 0.7860 - smape: 1.1701 - val_ia: 0.2609 - val_loss: 1.0261 - val_mae: 0.7026 - val_rmse: 0.8176 - val_smape: 1.2865

Epoch 18/128

958/958 - 34s - 36ms/step - ia: 0.4886 - loss: 0.6324 - mae: 0.5847 - rmse: 0.7797 - smape: 1.1594 - val_ia: 0.2609 - val_loss: 0.9972 - val_mae: 0.6989 - val_rmse: 0.8080 - val_smape: 1.3381

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:10 1s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step

 62%|██████▏   | 31/50 [11:07:41<7:27:53, 1414.41s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 11s - 11ms/step - ia: 0.3083 - loss: 0.9021 - mae: 0.7062 - rmse: 0.9296 - smape: 1.4094 - val_ia: 0.2561 - val_loss: 0.7795 - val_mae: 0.6475 - val_rmse: 0.7403 - val_smape: 1.2882

Epoch 2/256

958/958 - 5s - 5ms/step - ia: 0.3772 - loss: 0.8451 - mae: 0.6792 - rmse: 0.9018 - smape: 1.2988 - val_ia: 0.2604 - val_loss: 0.7612 - val_mae: 0.6417 - val_rmse: 0.7344 - val_smape: 1.2609

Epoch 3/256

958/958 - 5s - 5ms/step - ia: 0.3822 - loss: 0.8334 - mae: 0.6728 - rmse: 0.8960 - smape: 1.2881 - val_ia: 0.2570 - val_loss: 0.7699 - val_mae: 0.6539 - val_rmse: 0.7470 - val_smape: 1.2959

Epoch 4/256

958/958 - 5s - 5ms/step - ia: 0.3841 - loss: 0.8297 - mae: 0.6715 - rmse: 0.8932 - smape: 1.2867 - val_ia: 0.2587 - val_loss: 0.7586 - val_mae: 0.6360 - val_rmse: 0.7301 - val_smape: 1.2368

Epoch 5/256

958/958 - 3s - 4ms/step - ia: 0.3893 - loss: 0.8223 - mae: 0.6675 - rmse: 0.8890 - smape: 1.2753 - val_ia: 0.2573 - val_loss: 0.7580 - val_mae: 0.6320 - val_rmse: 0.7247 - val_smape: 1.2301

Epoch 6/256

958/958 - 5s - 5ms/step - ia: 0.3857 - loss: 0.8206 - mae: 0.6663 - rmse: 0.8883 - smape: 1.2816 - val_ia: 0.2581 - val_loss: 0.7554 - val_mae: 0.6392 - val_rmse: 0.7330 - val_smape: 1.2519

Epoch 7/256

958/958 - 3s - 3ms/step - ia: 0.3915 - loss: 0.8159 - mae: 0.6645 - rmse: 0.8863 - smape: 1.2750 - val_ia: 0.2567 - val_loss: 0.7588 - val_mae: 0.6459 - val_rmse: 0.7389 - val_smape: 1.2798

Epoch 8/256

958/958 - 4s - 4ms/step - ia: 0.3922 - loss: 0.8139 - mae: 0.6628 - rmse: 0.8847 - smape: 1.2718 - val_ia: 0.2573 - val_loss: 0.7523 - val_mae: 0.6359 - val_rmse: 0.7291 - val_smape: 1.2470

Epoch 9/256

958/958 - 6s - 6ms/step - ia: 0.3933 - loss: 0.8138 - mae: 0.6625 - rmse: 0.8844 - smape: 1.2717 - val_ia: 0.2572 - val_loss: 0.7542 - val_mae: 0.6399 - val_rmse: 0.7336 - val_smape: 1.2563

Epoch 10/256

958/958 - 5s - 5ms/step - ia: 0.3950 - loss: 0.8116 - mae: 0.6618 - rmse: 0.8842 - smape: 1.2695 - val_ia: 0.2588 - val_loss: 0.7479 - val_mae: 0.6346 - val_rmse: 0.7284 - val_smape: 1.2387

Epoch 11/256

958/958 - 5s - 5ms/step - ia: 0.3979 - loss: 0.8069 - mae: 0.6590 - rmse: 0.8798 - smape: 1.2625 - val_ia: 0.2582 - val_loss: 0.7495 - val_mae: 0.6363 - val_rmse: 0.7307 - val_smape: 1.2452

Epoch 12/256

958/958 - 5s - 5ms/step - ia: 0.3989 - loss: 0.8065 - mae: 0.6588 - rmse: 0.8794 - smape: 1.2638 - val_ia: 0.2585 - val_loss: 0.7474 - val_mae: 0.6329 - val_rmse: 0.7277 - val_smape: 1.2301

Epoch 13/256

958/958 - 5s - 5ms/step - ia: 0.3994 - loss: 0.8032 - mae: 0.6576 - rmse: 0.8787 - smape: 1.2613 - val_ia: 0.2584 - val_loss: 0.7502 - val_mae: 0.6384 - val_rmse: 0.7336 - val_smape: 1.2479

Epoch 14/256

958/958 - 5s - 5ms/step - ia: 0.4019 - loss: 0.8031 - mae: 0.6570 - rmse: 0.8795 - smape: 1.2573 - val_ia: 0.2575 - val_loss: 0.7498 - val_mae: 0.6402 - val_rmse: 0.7338 - val_smape: 1.2655

Epoch 15/256

958/958 - 5s - 5ms/step - ia: 0.3992 - loss: 0.8018 - mae: 0.6562 - rmse: 0.8780 - smape: 1.2610 - val_ia: 0.2583 - val_loss: 0.7482 - val_mae: 0.6366 - val_rmse: 0.7314 - val_smape: 1.2443

Epoch 16/256

958/958 - 5s - 5ms/step - ia: 0.4023 - loss: 0.8004 - mae: 0.6551 - rmse: 0.8768 - smape: 1.2570 - val_ia: 0.2584 - val_loss: 0.7520 - val_mae: 0.6391 - val_rmse: 0.7356 - val_smape: 1.2429

Epoch 17/256

958/958 - 5s - 5ms/step - ia: 0.4055 - loss: 0.7991 - mae: 0.6543 - rmse: 0.8769 - smape: 1.2513 - val_ia: 0.2586 - val_loss: 0.7437 - val_mae: 0.6310 - val_rmse: 0.7259 - val_smape: 1.2283

Epoch 18/256

958/958 - 5s - 5ms/step - ia: 0.4054 - loss: 0.7975 - mae: 0.6532 - rmse: 0.8757 - smape: 1.2536 - val_ia: 0.2583 - val_loss: 0.7490 - val_mae: 0.6384 - val_rmse: 0.7335 - val_smape: 1.2496

Epoch 19/256

958/958 - 5s - 5ms/step - ia: 0.4056 - loss: 0.7961 - mae: 0.6535 - rmse: 0.8752 - smape: 1.2523 - val_ia: 0.2579 - val_loss: 0.7467 - val_mae: 0.6351 - val_rmse: 0.7301 - val_smape: 1.2437

Epoch 20/256

958/958 - 5s - 5ms/step - ia: 0.4084 - loss: 0.7943 - mae: 0.6514 - rmse: 0.8739 - smape: 1.2479 - val_ia: 0.2594 - val_loss: 0.7417 - val_mae: 0.6318 - val_rmse: 0.7265 - val_smape: 1.2355

Epoch 21/256

958/958 - 5s - 5ms/step - ia: 0.4081 - loss: 0.7929 - mae: 0.6507 - rmse: 0.8727 - smape: 1.2483 - val_ia: 0.2583 - val_loss: 0.7485 - val_mae: 0.6371 - val_rmse: 0.7329 - val_smape: 1.2470

Epoch 22/256

958/958 - 5s - 5ms/step - ia: 0.4105 - loss: 0.7903 - mae: 0.6498 - rmse: 0.8707 - smape: 1.2459 - val_ia: 0.2588 - val_loss: 0.7500 - val_mae: 0.6401 - val_rmse: 0.7359 - val_smape: 1.2560

Epoch 23/256

958/958 - 5s - 5ms/step - ia: 0.4121 - loss: 0.7905 - mae: 0.6487 - rmse: 0.8717 - smape: 1.2432 - val_ia: 0.2581 - val_loss: 0.7502 - val_mae: 0.6391 - val_rmse: 0.7348 - val_smape: 1.2564

Epoch 24/256

958/958 - 5s - 5ms/step - ia: 0.4104 - loss: 0.7891 - mae: 0.6491 - rmse: 0.8693 - smape: 1.2471 - val_ia: 0.2600 - val_loss: 0.7487 - val_mae: 0.6340 - val_rmse: 0.7311 - val_smape: 1.2279

Epoch 25/256

958/958 - 5s - 5ms/step - ia: 0.4139 - loss: 0.7871 - mae: 0.6478 - rmse: 0.8689 - smape: 1.2440 - val_ia: 0.2596 - val_loss: 0.7493 - val_mae: 0.6373 - val_rmse: 0.7339 - val_smape: 1.2462

Epoch 26/256

958/958 - 5s - 6ms/step - ia: 0.4139 - loss: 0.7861 - mae: 0.6479 - rmse: 0.8691 - smape: 1.2413 - val_ia: 0.2597 - val_loss: 0.7427 - val_mae: 0.6280 - val_rmse: 0.7237 - val_smape: 1.2244

Epoch 27/256

958/958 - 5s - 5ms/step - ia: 0.4133 - loss: 0.7863 - mae: 0.6471 - rmse: 0.8690 - smape: 1.2437 - val_ia: 0.2608 - val_loss: 0.7538 - val_mae: 0.6401 - val_rmse: 0.7374 - val_smape: 1.2475

Epoch 28/256

958/958 - 5s - 5ms/step - ia: 0.4147 - loss: 0.7844 - mae: 0.6465 - rmse: 0.8682 - smape: 1.2414 - val_ia: 0.2612 - val_loss: 0.7532 - val_mae: 0.6431 - val_rmse: 0.7394 - val_smape: 1.2622

Epoch 29/256

958/958 - 5s - 5ms/step - ia: 0.4144 - loss: 0.7835 - mae: 0.6461 - rmse: 0.8681 - smape: 1.2410 - val_ia: 0.2619 - val_loss: 0.7553 - val_mae: 0.6422 - val_rmse: 0.7397 - val_smape: 1.2518

Epoch 30/256

958/958 - 4s - 5ms/step - ia: 0.4178 - loss: 0.7827 - mae: 0.6454 - rmse: 0.8671 - smape: 1.2372 - val_ia: 0.2611 - val_loss: 0.7432 - val_mae: 0.6321 - val_rmse: 0.7275 - val_smape: 1.2423

Epoch 31/256

958/958 - 6s - 6ms/step - ia: 0.4167 - loss: 0.7807 - mae: 0.6446 - rmse: 0.8656 - smape: 1.2397 - val_ia: 0.2610 - val_loss: 0.7477 - val_mae: 0.6343 - val_rmse: 0.7305 - val_smape: 1.2418

Epoch 32/256

958/958 - 5s - 5ms/step - ia: 0.4192 - loss: 0.7809 - mae: 0.6446 - rmse: 0.8668 - smape: 1.2344 - val_ia: 0.2614 - val_loss: 0.7445 - val_mae: 0.6314 - val_rmse: 0.7271 - val_smape: 1.2397

Epoch 33/256

958/958 - 5s - 5ms/step - ia: 0.4195 - loss: 0.7791 - mae: 0.6431 - rmse: 0.8649 - smape: 1.2356 - val_ia: 0.2626 - val_loss: 0.7437 - val_mae: 0.6306 - val_rmse: 0.7267 - val_smape: 1.2319

Epoch 34/256

958/958 - 5s - 5ms/step - ia: 0.4180 - loss: 0.7801 - mae: 0.6443 - rmse: 0.8656 - smape: 1.2366 - val_ia: 0.2624 - val_loss: 0.7491 - val_mae: 0.6344 - val_rmse: 0.7313 - val_smape: 1.2385

Epoch 35/256

958/958 - 5s - 5ms/step - ia: 0.4192 - loss: 0.7801 - mae: 0.6434 - rmse: 0.8648 - smape: 1.2345 - val_ia: 0.2625 - val_loss: 0.7544 - val_mae: 0.6373 - val_rmse: 0.7350 - val_smape: 1.2395

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 39s 295ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

Epoch 1/128

 64%|██████▍   | 32/50 [11:10:37<5:12:49, 1042.75s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 7s - 55ms/step - ia: 0.3784 - loss: 0.8240 - mae: 0.6672 - rmse: 0.9049 - smape: 1.2974 - val_ia: 0.3449 - val_loss: 0.7652 - val_mae: 0.6459 - val_rmse: 0.8093 - val_smape: 1.2569

Epoch 2/128

120/120 - 1s - 11ms/step - ia: 0.4113 - loss: 0.7799 - mae: 0.6463 - rmse: 0.8804 - smape: 1.2536 - val_ia: 0.3692 - val_loss: 0.7859 - val_mae: 0.6443 - val_rmse: 0.8185 - val_smape: 1.2234

Epoch 3/128

120/120 - 1s - 10ms/step - ia: 0.4228 - loss: 0.7688 - mae: 0.6406 - rmse: 0.8743 - smape: 1.2350 - val_ia: 0.3626 - val_loss: 0.8998 - val_mae: 0.6790 - val_rmse: 0.8711 - val_smape: 1.2913

Epoch 4/128

120/120 - 1s - 10ms/step - ia: 0.4281 - loss: 0.7612 - mae: 0.6366 - rmse: 0.8693 - smape: 1.2293 - val_ia: 0.3533 - val_loss: 0.7970 - val_mae: 0.6556 - val_rmse: 0.8255 - val_smape: 1.2603

Epoch 5/128

120/120 - 1s - 10ms/step - ia: 0.4382 - loss: 0.7464 - mae: 0.6314 - rmse: 0.8608 - smape: 1.2155 - val_ia: 0.3527 - val_loss: 0.7641 - val_mae: 0.6399 - val_rmse: 0.8053 - val_smape: 1.2620

Epoch 6/128

120/120 - 1s - 10ms/step - ia: 0.4430 - loss: 0.7382 - mae: 0.6268 - rmse: 0.8563 - smape: 1.2069 - val_ia: 0.3748 - val_loss: 0.7973 - val_mae: 0.6522 - val_rmse: 0.8290 - val_smape: 1.2159

Epoch 7/128

120/120 - 1s - 10ms/step - ia: 0.4474 - loss: 0.7310 - mae: 0.6244 - rmse: 0.8524 - smape: 1.2002 - val_ia: 0.3637 - val_loss: 0.7913 - val_mae: 0.6557 - val_rmse: 0.8263 - val_smape: 1.2704

Epoch 8/128

120/120 - 1s - 10ms/step - ia: 0.4525 - loss: 0.7185 - mae: 0.6202 - rmse: 0.8451 - smape: 1.1982 - val_ia: 0.3630 - val_loss: 0.8062 - val_mae: 0.6464 - val_rmse: 0.8215 - val_smape: 1.2375

Epoch 9/128

120/120 - 1s - 12ms/step - ia: 0.4602 - loss: 0.7086 - mae: 0.6156 - rmse: 0.8391 - smape: 1.1879 - val_ia: 0.3548 - val_loss: 0.8204 - val_mae: 0.6526 - val_rmse: 0.8278 - val_smape: 1.2493

Epoch 10/128

120/120 - 2s - 13ms/step - ia: 0.4658 - loss: 0.6965 - mae: 0.6103 - rmse: 0.8322 - smape: 1.1821 - val_ia: 0.3651 - val_loss: 0.8131 - val_mae: 0.6539 - val_rmse: 0.8295 - val_smape: 1.2750

Epoch 11/128

120/120 - 3s - 22ms/step - ia: 0.4715 - loss: 0.6891 - mae: 0.6066 - rmse: 0.8276 - smape: 1.1754 - val_ia: 0.3665 - val_loss: 0.8420 - val_mae: 0.6648 - val_rmse: 0.8438 - val_smape: 1.2504

Epoch 12/128

120/120 - 2s - 13ms/step - ia: 0.4702 - loss: 0.6854 - mae: 0.6059 - rmse: 0.8252 - smape: 1.1816 - val_ia: 0.3584 - val_loss: 0.8720 - val_mae: 0.6749 - val_rmse: 0.8577 - val_smape: 1.2749

Epoch 13/128

120/120 - 3s - 22ms/step - ia: 0.4760 - loss: 0.6780 - mae: 0.6012 - rmse: 0.8212 - smape: 1.1733 - val_ia: 0.3669 - val_loss: 0.8251 - val_mae: 0.6611 - val_rmse: 0.8391 - val_smape: 1.2552

Epoch 14/128

120/120 - 2s - 13ms/step - ia: 0.4832 - loss: 0.6703 - mae: 0.5982 - rmse: 0.8164 - smape: 1.1624 - val_ia: 0.3833 - val_loss: 0.8355 - val_mae: 0.6534 - val_rmse: 0.8364 - val_smape: 1.2084

Epoch 15/128

120/120 - 2s - 13ms/step - ia: 0.4845 - loss: 0.6623 - mae: 0.5959 - rmse: 0.8123 - smape: 1.1637 - val_ia: 0.3656 - val_loss: 0.9386 - val_mae: 0.6836 - val_rmse: 0.8826 - val_smape: 1.2602

Epoch 16/128

120/120 - 3s - 21ms/step - ia: 0.4851 - loss: 0.6619 - mae: 0.5956 - rmse: 0.8117 - smape: 1.1589 - val_ia: 0.3769 - val_loss: 0.8361 - val_mae: 0.6623 - val_rmse: 0.8434 - val_smape: 1.2346

Epoch 17/128

120/120 - 2s - 13ms/step - ia: 0.4857 - loss: 0.6561 - mae: 0.5941 - rmse: 0.8080 - smape: 1.1628 - val_ia: 0.3755 - val_loss: 0.8787 - val_mae: 0.6681 - val_rmse: 0.8564 - val_smape: 1.2367

Epoch 18/128

120/120 - 2s - 13ms/step - ia: 0.4955 - loss: 0.6450 - mae: 0.5884 - rmse: 0.8010 - smape: 1.1505 - val_ia: 0.3732 - val_loss: 0.9246 - val_mae: 0.6788 - val_rmse: 0.8790 - val_smape: 1.2648

Epoch 19/128

120/120 - 2s - 13ms/step - ia: 0.4979 - loss: 0.6365 - mae: 0.5853 - rmse: 0.7957 - smape: 1.1485 - val_ia: 0.3821 - val_loss: 0.8940 - val_mae: 0.6618 - val_rmse: 0.8587 - val_smape: 1.2365

Epoch 20/128

120/120 - 3s - 22ms/step - ia: 0.4988 - loss: 0.6353 - mae: 0.5847 - rmse: 0.7945 - smape: 1.1493 - val_ia: 0.3559 - val_loss: 0.9231 - val_mae: 0.6715 - val_rmse: 0.8699 - val_smape: 1.2566

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:02 464ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
121/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

Epoch 1/32

 66%|██████▌   | 33/50 [11:11:18<3:30:14, 742.04s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 8s - 69ms/step - ia: 0.3706 - loss: 0.8294 - mae: 0.6694 - rmse: 0.9083 - smape: 1.3045 - val_ia: 0.3479 - val_loss: 0.7449 - val_mae: 0.6379 - val_rmse: 0.7977 - val_smape: 1.2724

Epoch 2/32

120/120 - 2s - 14ms/step - ia: 0.4169 - loss: 0.7792 - mae: 0.6457 - rmse: 0.8796 - smape: 1.2393 - val_ia: 0.3744 - val_loss: 0.7631 - val_mae: 0.6360 - val_rmse: 0.8084 - val_smape: 1.2423

Epoch 3/32

120/120 - 3s - 22ms/step - ia: 0.4317 - loss: 0.7581 - mae: 0.6347 - rmse: 0.8681 - smape: 1.2214 - val_ia: 0.3470 - val_loss: 0.8005 - val_mae: 0.6637 - val_rmse: 0.8285 - val_smape: 1.2967

Epoch 4/32

120/120 - 2s - 13ms/step - ia: 0.4397 - loss: 0.7482 - mae: 0.6303 - rmse: 0.8627 - smape: 1.2061 - val_ia: 0.3854 - val_loss: 0.8201 - val_mae: 0.6496 - val_rmse: 0.8341 - val_smape: 1.1847

Epoch 5/32

120/120 - 2s - 14ms/step - ia: 0.4510 - loss: 0.7296 - mae: 0.6215 - rmse: 0.8513 - smape: 1.1929 - val_ia: 0.3588 - val_loss: 0.7731 - val_mae: 0.6392 - val_rmse: 0.8061 - val_smape: 1.2291

Epoch 6/32

120/120 - 2s - 20ms/step - ia: 0.4573 - loss: 0.7204 - mae: 0.6179 - rmse: 0.8462 - smape: 1.1825 - val_ia: 0.3807 - val_loss: 0.8239 - val_mae: 0.6561 - val_rmse: 0.8403 - val_smape: 1.1985

Epoch 7/32

120/120 - 3s - 22ms/step - ia: 0.4696 - loss: 0.7018 - mae: 0.6096 - rmse: 0.8348 - smape: 1.1682 - val_ia: 0.3713 - val_loss: 0.8046 - val_mae: 0.6445 - val_rmse: 0.8252 - val_smape: 1.2173

Epoch 8/32

120/120 - 2s - 13ms/step - ia: 0.4713 - loss: 0.6902 - mae: 0.6072 - rmse: 0.8283 - smape: 1.1706 - val_ia: 0.3477 - val_loss: 0.8651 - val_mae: 0.6685 - val_rmse: 0.8461 - val_smape: 1.2608

Epoch 9/32

120/120 - 2s - 13ms/step - ia: 0.4765 - loss: 0.6808 - mae: 0.6026 - rmse: 0.8229 - smape: 1.1679 - val_ia: 0.3596 - val_loss: 0.8471 - val_mae: 0.6551 - val_rmse: 0.8351 - val_smape: 1.2322

Epoch 10/32

120/120 - 2s - 13ms/step - ia: 0.4878 - loss: 0.6666 - mae: 0.5947 - rmse: 0.8141 - smape: 1.1502 - val_ia: 0.3548 - val_loss: 0.8851 - val_mae: 0.6724 - val_rmse: 0.8574 - val_smape: 1.2669

Epoch 11/32

120/120 - 3s - 22ms/step - ia: 0.4897 - loss: 0.6548 - mae: 0.5911 - rmse: 0.8073 - smape: 1.1491 - val_ia: 0.3504 - val_loss: 0.8641 - val_mae: 0.6662 - val_rmse: 0.8471 - val_smape: 1.2856

Epoch 12/32

120/120 - 2s - 21ms/step - ia: 0.4982 - loss: 0.6417 - mae: 0.5854 - rmse: 0.7990 - smape: 1.1430 - val_ia: 0.3456 - val_loss: 0.8725 - val_mae: 0.6647 - val_rmse: 0.8461 - val_smape: 1.2744

Epoch 13/32

120/120 - 2s - 13ms/step - ia: 0.5013 - loss: 0.6290 - mae: 0.5816 - rmse: 0.7910 - smape: 1.1425 - val_ia: 0.3678 - val_loss: 0.9674 - val_mae: 0.6796 - val_rmse: 0.8854 - val_smape: 1.2148

Epoch 14/32

120/120 - 3s - 22ms/step - ia: 0.5099 - loss: 0.6173 - mae: 0.5761 - rmse: 0.7837 - smape: 1.1303 - val_ia: 0.3584 - val_loss: 0.8753 - val_mae: 0.6832 - val_rmse: 0.8674 - val_smape: 1.2883

Epoch 15/32

120/120 - 2s - 13ms/step - ia: 0.5155 - loss: 0.6031 - mae: 0.5711 - rmse: 0.7748 - smape: 1.1261 - val_ia: 0.3681 - val_loss: 0.9416 - val_mae: 0.6837 - val_rmse: 0.8805 - val_smape: 1.2430

Epoch 16/32

120/120 - 2s - 13ms/step - ia: 0.5191 - loss: 0.5939 - mae: 0.5656 - rmse: 0.7689 - smape: 1.1228 - val_ia: 0.3591 - val_loss: 0.9371 - val_mae: 0.6834 - val_rmse: 0.8776 - val_smape: 1.2668

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:06 491ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

Epoch 1/64

 68%|██████▊   | 34/50 [11:11:58<2:21:43, 531.47s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 9s - 76ms/step - ia: 0.3485 - loss: 0.8527 - mae: 0.6809 - rmse: 0.9201 - smape: 1.3451 - val_ia: 0.3361 - val_loss: 0.7657 - val_mae: 0.6475 - val_rmse: 0.8093 - val_smape: 1.3052

Epoch 2/64

120/120 - 2s - 14ms/step - ia: 0.3868 - loss: 0.8083 - mae: 0.6591 - rmse: 0.8958 - smape: 1.2901 - val_ia: 0.3501 - val_loss: 0.7606 - val_mae: 0.6499 - val_rmse: 0.8117 - val_smape: 1.2603

Epoch 3/64

120/120 - 2s - 14ms/step - ia: 0.4035 - loss: 0.7912 - mae: 0.6524 - rmse: 0.8867 - smape: 1.2640 - val_ia: 0.3678 - val_loss: 0.7655 - val_mae: 0.6511 - val_rmse: 0.8195 - val_smape: 1.2799

Epoch 4/64

120/120 - 2s - 13ms/step - ia: 0.4106 - loss: 0.7842 - mae: 0.6476 - rmse: 0.8828 - smape: 1.2525 - val_ia: 0.3390 - val_loss: 0.7559 - val_mae: 0.6471 - val_rmse: 0.8055 - val_smape: 1.3062

Epoch 5/64

120/120 - 2s - 13ms/step - ia: 0.4148 - loss: 0.7692 - mae: 0.6416 - rmse: 0.8751 - smape: 1.2494 - val_ia: 0.3665 - val_loss: 0.7520 - val_mae: 0.6386 - val_rmse: 0.8046 - val_smape: 1.2582

Epoch 6/64

120/120 - 2s - 13ms/step - ia: 0.4221 - loss: 0.7618 - mae: 0.6397 - rmse: 0.8695 - smape: 1.2397 - val_ia: 0.3538 - val_loss: 0.7582 - val_mae: 0.6432 - val_rmse: 0.8079 - val_smape: 1.2766

Epoch 7/64

120/120 - 2s - 20ms/step - ia: 0.4291 - loss: 0.7501 - mae: 0.6336 - rmse: 0.8636 - smape: 1.2293 - val_ia: 0.3829 - val_loss: 0.7999 - val_mae: 0.6530 - val_rmse: 0.8309 - val_smape: 1.2436

Epoch 8/64

120/120 - 3s - 23ms/step - ia: 0.4343 - loss: 0.7478 - mae: 0.6313 - rmse: 0.8624 - smape: 1.2209 - val_ia: 0.3501 - val_loss: 0.7613 - val_mae: 0.6344 - val_rmse: 0.8023 - val_smape: 1.2175

Epoch 9/64

120/120 - 2s - 13ms/step - ia: 0.4347 - loss: 0.7425 - mae: 0.6297 - rmse: 0.8585 - smape: 1.2216 - val_ia: 0.3589 - val_loss: 0.7906 - val_mae: 0.6557 - val_rmse: 0.8253 - val_smape: 1.2823

Epoch 10/64

120/120 - 3s - 21ms/step - ia: 0.4438 - loss: 0.7258 - mae: 0.6242 - rmse: 0.8495 - smape: 1.2161 - val_ia: 0.3632 - val_loss: 0.7936 - val_mae: 0.6494 - val_rmse: 0.8229 - val_smape: 1.2632

Epoch 11/64

120/120 - 2s - 13ms/step - ia: 0.4485 - loss: 0.7174 - mae: 0.6204 - rmse: 0.8443 - smape: 1.2067 - val_ia: 0.3589 - val_loss: 0.8340 - val_mae: 0.6642 - val_rmse: 0.8389 - val_smape: 1.2899

Epoch 12/64

120/120 - 2s - 13ms/step - ia: 0.4497 - loss: 0.7154 - mae: 0.6188 - rmse: 0.8432 - smape: 1.2100 - val_ia: 0.3654 - val_loss: 0.8076 - val_mae: 0.6574 - val_rmse: 0.8336 - val_smape: 1.2647

Epoch 13/64

120/120 - 3s - 21ms/step - ia: 0.4570 - loss: 0.7032 - mae: 0.6142 - rmse: 0.8367 - smape: 1.2004 - val_ia: 0.3541 - val_loss: 0.8489 - val_mae: 0.6710 - val_rmse: 0.8523 - val_smape: 1.2949

Epoch 14/64

120/120 - 3s - 22ms/step - ia: 0.4606 - loss: 0.6978 - mae: 0.6113 - rmse: 0.8329 - smape: 1.1972 - val_ia: 0.3621 - val_loss: 0.8207 - val_mae: 0.6560 - val_rmse: 0.8349 - val_smape: 1.2663

Epoch 15/64

120/120 - 3s - 22ms/step - ia: 0.4649 - loss: 0.6893 - mae: 0.6074 - rmse: 0.8281 - smape: 1.1878 - val_ia: 0.3644 - val_loss: 0.8257 - val_mae: 0.6604 - val_rmse: 0.8381 - val_smape: 1.2648

Epoch 16/64

120/120 - 2s - 13ms/step - ia: 0.4679 - loss: 0.6803 - mae: 0.6052 - rmse: 0.8227 - smape: 1.1906 - val_ia: 0.3564 - val_loss: 0.8707 - val_mae: 0.6728 - val_rmse: 0.8569 - val_smape: 1.2796

Epoch 17/64

120/120 - 3s - 21ms/step - ia: 0.4635 - loss: 0.6851 - mae: 0.6071 - rmse: 0.8254 - smape: 1.1947 - val_ia: 0.3620 - val_loss: 0.8591 - val_mae: 0.6657 - val_rmse: 0.8533 - val_smape: 1.2463

Epoch 18/64

120/120 - 2s - 13ms/step - ia: 0.4728 - loss: 0.6754 - mae: 0.6022 - rmse: 0.8189 - smape: 1.1834 - val_ia: 0.3534 - val_loss: 0.8818 - val_mae: 0.6761 - val_rmse: 0.8620 - val_smape: 1.2646

Epoch 19/64

120/120 - 2s - 13ms/step - ia: 0.4722 - loss: 0.6700 - mae: 0.6006 - rmse: 0.8166 - smape: 1.1898 - val_ia: 0.3531 - val_loss: 0.8680 - val_mae: 0.6678 - val_rmse: 0.8508 - val_smape: 1.2742

Epoch 20/64

120/120 - 2s - 13ms/step - ia: 0.4764 - loss: 0.6621 - mae: 0.5986 - rmse: 0.8113 - smape: 1.1826 - val_ia: 0.3614 - val_loss: 0.8605 - val_mae: 0.6678 - val_rmse: 0.8498 - val_smape: 1.2663

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 45s 339ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 70%|███████   | 35/50 [11:12:46<1:36:35, 386.38s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

120/120 - 9s - 71ms/step - ia: 0.1124 - loss: 1.0571 - mae: 0.7826 - rmse: 1.0252 - smape: 1.7189 - val_ia: 0.2502 - val_loss: 1.0253 - val_mae: 0.7761 - val_rmse: 0.9369 - val_smape: 1.8083

Epoch 2/128

120/120 - 2s - 14ms/step - ia: 0.1151 - loss: 1.0442 - mae: 0.7756 - rmse: 1.0196 - smape: 1.7142 - val_ia: 0.2505 - val_loss: 1.0124 - val_mae: 0.7699 - val_rmse: 0.9300 - val_smape: 1.8135

Epoch 3/128

120/120 - 2s - 14ms/step - ia: 0.1169 - loss: 1.0365 - mae: 0.7727 - rmse: 1.0142 - smape: 1.7154 - val_ia: 0.2507 - val_loss: 1.0004 - val_mae: 0.7643 - val_rmse: 0.9238 - val_smape: 1.8167

Epoch 4/128

120/120 - 2s - 13ms/step - ia: 0.1201 - loss: 1.0285 - mae: 0.7685 - rmse: 1.0106 - smape: 1.7095 - val_ia: 0.2508 - val_loss: 0.9896 - val_mae: 0.7594 - val_rmse: 0.9182 - val_smape: 1.8158

Epoch 5/128

120/120 - 2s - 13ms/step - ia: 0.1197 - loss: 1.0210 - mae: 0.7665 - rmse: 1.0080 - smape: 1.7146 - val_ia: 0.2511 - val_loss: 0.9795 - val_mae: 0.7548 - val_rmse: 0.9129 - val_smape: 1.8125

Epoch 6/128

120/120 - 2s - 13ms/step - ia: 0.1239 - loss: 1.0111 - mae: 0.7616 - rmse: 1.0030 - smape: 1.7030 - val_ia: 0.2514 - val_loss: 0.9701 - val_mae: 0.7507 - val_rmse: 0.9082 - val_smape: 1.8074

Epoch 7/128

120/120 - 3s - 21ms/step - ia: 0.1280 - loss: 1.0042 - mae: 0.7585 - rmse: 0.9993 - smape: 1.6956 - val_ia: 0.2520 - val_loss: 0.9610 - val_mae: 0.7468 - val_rmse: 0.9036 - val_smape: 1.8010

Epoch 8/128

120/120 - 2s - 14ms/step - ia: 0.1325 - loss: 0.9947 - mae: 0.7544 - rmse: 0.9945 - smape: 1.6865 - val_ia: 0.2527 - val_loss: 0.9525 - val_mae: 0.7431 - val_rmse: 0.8994 - val_smape: 1.7949

Epoch 9/128

120/120 - 1s - 12ms/step - ia: 0.1359 - loss: 0.9924 - mae: 0.7524 - rmse: 0.9934 - smape: 1.6787 - val_ia: 0.2536 - val_loss: 0.9444 - val_mae: 0.7396 - val_rmse: 0.8954 - val_smape: 1.7875

Epoch 10/128

120/120 - 3s - 22ms/step - ia: 0.1423 - loss: 0.9845 - mae: 0.7496 - rmse: 0.9894 - smape: 1.6698 - val_ia: 0.2544 - val_loss: 0.9364 - val_mae: 0.7362 - val_rmse: 0.8915 - val_smape: 1.7784

Epoch 11/128

120/120 - 2s - 13ms/step - ia: 0.1478 - loss: 0.9765 - mae: 0.7463 - rmse: 0.9848 - smape: 1.6600 - val_ia: 0.2555 - val_loss: 0.9289 - val_mae: 0.7331 - val_rmse: 0.8878 - val_smape: 1.7673

Epoch 12/128

120/120 - 1s - 11ms/step - ia: 0.1555 - loss: 0.9699 - mae: 0.7426 - rmse: 0.9819 - smape: 1.6461 - val_ia: 0.2566 - val_loss: 0.9215 - val_mae: 0.7300 - val_rmse: 0.8843 - val_smape: 1.7542

Epoch 13/128

120/120 - 3s - 25ms/step - ia: 0.1617 - loss: 0.9633 - mae: 0.7410 - rmse: 0.9787 - smape: 1.6391 - val_ia: 0.2579 - val_loss: 0.9146 - val_mae: 0.7271 - val_rmse: 0.8809 - val_smape: 1.7403

Epoch 14/128

120/120 - 3s - 21ms/step - ia: 0.1692 - loss: 0.9577 - mae: 0.7373 - rmse: 0.9756 - smape: 1.6255 - val_ia: 0.2593 - val_loss: 0.9078 - val_mae: 0.7242 - val_rmse: 0.8777 - val_smape: 1.7255

Epoch 15/128

120/120 - 3s - 22ms/step - ia: 0.1765 - loss: 0.9497 - mae: 0.7348 - rmse: 0.9719 - smape: 1.6112 - val_ia: 0.2608 - val_loss: 0.9011 - val_mae: 0.7213 - val_rmse: 0.8745 - val_smape: 1.7085

Epoch 16/128

120/120 - 2s - 14ms/step - ia: 0.1849 - loss: 0.9434 - mae: 0.7307 - rmse: 0.9685 - smape: 1.5959 - val_ia: 0.2624 - val_loss: 0.8950 - val_mae: 0.7188 - val_rmse: 0.8716 - val_smape: 1.6906

Epoch 17/128

120/120 - 1s - 12ms/step - ia: 0.1882 - loss: 0.9413 - mae: 0.7307 - rmse: 0.9676 - smape: 1.5892 - val_ia: 0.2640 - val_loss: 0.8891 - val_mae: 0.7163 - val_rmse: 0.8689 - val_smape: 1.6724

Epoch 18/128

120/120 - 3s - 22ms/step - ia: 0.1951 - loss: 0.9373 - mae: 0.7286 - rmse: 0.9655 - smape: 1.5775 - val_ia: 0.2658 - val_loss: 0.8836 - val_mae: 0.7140 - val_rmse: 0.8664 - val_smape: 1.6550

Epoch 19/128

120/120 - 2s - 13ms/step - ia: 0.2045 - loss: 0.9292 - mae: 0.7252 - rmse: 0.9608 - smape: 1.5636 - val_ia: 0.2673 - val_loss: 0.8778 - val_mae: 0.7114 - val_rmse: 0.8636 - val_smape: 1.6347

Epoch 20/128

120/120 - 2s - 13ms/step - ia: 0.2119 - loss: 0.9264 - mae: 0.7232 - rmse: 0.9596 - smape: 1.5500 - val_ia: 0.2691 - val_loss: 0.8727 - val_mae: 0.7092 - val_rmse: 0.8613 - val_smape: 1.6166

Epoch 21/128

120/120 - 2s - 13ms/step - ia: 0.2204 - loss: 0.9194 - mae: 0.7208 - rmse: 0.9570 - smape: 1.5403 - val_ia: 0.2709 - val_loss: 0.8678 - val_mae: 0.7068 - val_rmse: 0.8589 - val_smape: 1.5988

Epoch 22/128

120/120 - 2s - 13ms/step - ia: 0.2265 - loss: 0.9165 - mae: 0.7186 - rmse: 0.9544 - smape: 1.5268 - val_ia: 0.2728 - val_loss: 0.8634 - val_mae: 0.7048 - val_rmse: 0.8569 - val_smape: 1.5830

Epoch 23/128

120/120 - 2s - 13ms/step - ia: 0.2339 - loss: 0.9100 - mae: 0.7162 - rmse: 0.9516 - smape: 1.5151 - val_ia: 0.2745 - val_loss: 0.8587 - val_mae: 0.7026 - val_rmse: 0.8546 - val_smape: 1.5657

Epoch 24/128

120/120 - 2s - 13ms/step - ia: 0.2391 - loss: 0.9099 - mae: 0.7160 - rmse: 0.9513 - smape: 1.5087 - val_ia: 0.2763 - val_loss: 0.8546 - val_mae: 0.7007 - val_rmse: 0.8528 - val_smape: 1.5507

Epoch 25/128

120/120 - 2s - 13ms/step - ia: 0.2455 - loss: 0.9047 - mae: 0.7145 - rmse: 0.9483 - smape: 1.5009 - val_ia: 0.2781 - val_loss: 0.8511 - val_mae: 0.6989 - val_rmse: 0.8512 - val_smape: 1.5368

Epoch 26/128

120/120 - 3s - 22ms/step - ia: 0.2540 - loss: 0.8988 - mae: 0.7110 - rmse: 0.9458 - smape: 1.4861 - val_ia: 0.2800 - val_loss: 0.8475 - val_mae: 0.6971 - val_rmse: 0.8495 - val_smape: 1.5224

Epoch 27/128

120/120 - 2s - 20ms/step - ia: 0.2585 - loss: 0.9002 - mae: 0.7111 - rmse: 0.9453 - smape: 1.4784 - val_ia: 0.2816 - val_loss: 0.8441 - val_mae: 0.6954 - val_rmse: 0.8479 - val_smape: 1.5092

Epoch 28/128

120/120 - 2s - 20ms/step - ia: 0.2647 - loss: 0.8957 - mae: 0.7095 - rmse: 0.9433 - smape: 1.4710 - val_ia: 0.2833 - val_loss: 0.8412 - val_mae: 0.6938 - val_rmse: 0.8466 - val_smape: 1.4973

Epoch 29/128

120/120 - 1s - 9ms/step - ia: 0.2693 - loss: 0.8948 - mae: 0.7082 - rmse: 0.9436 - smape: 1.4622 - val_ia: 0.2848 - val_loss: 0.8383 - val_mae: 0.6920 - val_rmse: 0.8451 - val_smape: 1.4850

Epoch 30/128

120/120 - 1s - 9ms/step - ia: 0.2743 - loss: 0.8916 - mae: 0.7068 - rmse: 0.9415 - smape: 1.4527 - val_ia: 0.2864 - val_loss: 0.8358 - val_mae: 0.6907 - val_rmse: 0.8440 - val_smape: 1.4750

Epoch 31/128

120/120 - 1s - 9ms/step - ia: 0.2791 - loss: 0.8892 - mae: 0.7062 - rmse: 0.9412 - smape: 1.4480 - val_ia: 0.2879 - val_loss: 0.8336 - val_mae: 0.6893 - val_rmse: 0.8429 - val_smape: 1.4652

Epoch 32/128

120/120 - 1s - 9ms/step - ia: 0.2840 - loss: 0.8909 - mae: 0.7053 - rmse: 0.9412 - smape: 1.4410 - val_ia: 0.2892 - val_loss: 0.8315 - val_mae: 0.6881 - val_rmse: 0.8419 - val_smape: 1.4561

Epoch 33/128

120/120 - 1s - 10ms/step - ia: 0.2875 - loss: 0.8870 - mae: 0.7037 - rmse: 0.9395 - smape: 1.4320 - val_ia: 0.2904 - val_loss: 0.8296 - val_mae: 0.6868 - val_rmse: 0.8409 - val_smape: 1.4476

Epoch 34/128

120/120 - 1s - 10ms/step - ia: 0.2914 - loss: 0.8853 - mae: 0.7028 - rmse: 0.9390 - smape: 1.4262 - val_ia: 0.2914 - val_loss: 0.8275 - val_mae: 0.6855 - val_rmse: 0.8398 - val_smape: 1.4385

Epoch 35/128

120/120 - 1s - 9ms/step - ia: 0.2953 - loss: 0.8835 - mae: 0.7018 - rmse: 0.9376 - smape: 1.4208 - val_ia: 0.2926 - val_loss: 0.8257 - val_mae: 0.6843 - val_rmse: 0.8389 - val_smape: 1.4307

Epoch 36/128

120/120 - 1s - 11ms/step - ia: 0.3005 - loss: 0.8802 - mae: 0.6995 - rmse: 0.9354 - smape: 1.4116 - val_ia: 0.2938 - val_loss: 0.8244 - val_mae: 0.6834 - val_rmse: 0.8383 - val_smape: 1.4247

Epoch 37/128

120/120 - 1s - 12ms/step - ia: 0.3015 - loss: 0.8829 - mae: 0.7008 - rmse: 0.9372 - smape: 1.4124 - val_ia: 0.2946 - val_loss: 0.8227 - val_mae: 0.6823 - val_rmse: 0.8373 - val_smape: 1.4176

Epoch 38/128

120/120 - 2s - 13ms/step - ia: 0.3062 - loss: 0.8776 - mae: 0.6985 - rmse: 0.9336 - smape: 1.4056 - val_ia: 0.2955 - val_loss: 0.8213 - val_mae: 0.6814 - val_rmse: 0.8366 - val_smape: 1.4116

Epoch 39/128

120/120 - 3s - 22ms/step - ia: 0.3095 - loss: 0.8772 - mae: 0.6979 - rmse: 0.9346 - smape: 1.3994 - val_ia: 0.2965 - val_loss: 0.8202 - val_mae: 0.6807 - val_rmse: 0.8362 - val_smape: 1.4070

Epoch 40/128

120/120 - 2s - 13ms/step - ia: 0.3107 - loss: 0.8758 - mae: 0.6972 - rmse: 0.9340 - smape: 1.3958 - val_ia: 0.2972 - val_loss: 0.8189 - val_mae: 0.6798 - val_rmse: 0.8354 - val_smape: 1.4015

Epoch 41/128

120/120 - 3s - 22ms/step - ia: 0.3146 - loss: 0.8721 - mae: 0.6955 - rmse: 0.9309 - smape: 1.3943 - val_ia: 0.2979 - val_loss: 0.8177 - val_mae: 0.6791 - val_rmse: 0.8349 - val_smape: 1.3967

Epoch 42/128

120/120 - 2s - 20ms/step - ia: 0.3162 - loss: 0.8743 - mae: 0.6952 - rmse: 0.9326 - smape: 1.3884 - val_ia: 0.2986 - val_loss: 0.8167 - val_mae: 0.6784 - val_rmse: 0.8343 - val_smape: 1.3925

Epoch 43/128

120/120 - 2s - 14ms/step - ia: 0.3172 - loss: 0.8728 - mae: 0.6952 - rmse: 0.9315 - smape: 1.3866 - val_ia: 0.2992 - val_loss: 0.8156 - val_mae: 0.6776 - val_rmse: 0.8337 - val_smape: 1.3885

Epoch 44/128

120/120 - 2s - 13ms/step - ia: 0.3207 - loss: 0.8718 - mae: 0.6941 - rmse: 0.9304 - smape: 1.3848 - val_ia: 0.2998 - val_loss: 0.8145 - val_mae: 0.6771 - val_rmse: 0.8332 - val_smape: 1.3851

Epoch 45/128

120/120 - 3s - 23ms/step - ia: 0.3227 - loss: 0.8680 - mae: 0.6929 - rmse: 0.9287 - smape: 1.3785 - val_ia: 0.3004 - val_loss: 0.8138 - val_mae: 0.6767 - val_rmse: 0.8329 - val_smape: 1.3827

Epoch 46/128

120/120 - 2s - 21ms/step - ia: 0.3212 - loss: 0.8717 - mae: 0.6950 - rmse: 0.9319 - smape: 1.3822 - val_ia: 0.3008 - val_loss: 0.8129 - val_mae: 0.6761 - val_rmse: 0.8324 - val_smape: 1.3798

Epoch 47/128

120/120 - 3s - 22ms/step - ia: 0.3262 - loss: 0.8665 - mae: 0.6914 - rmse: 0.9287 - smape: 1.3709 - val_ia: 0.3013 - val_loss: 0.8121 - val_mae: 0.6757 - val_rmse: 0.8321 - val_smape: 1.3777

Epoch 48/128

120/120 - 3s - 21ms/step - ia: 0.3249 - loss: 0.8682 - mae: 0.6928 - rmse: 0.9291 - smape: 1.3755 - val_ia: 0.3017 - val_loss: 0.8112 - val_mae: 0.6752 - val_rmse: 0.8316 - val_smape: 1.3754

Epoch 49/128

120/120 - 3s - 21ms/step - ia: 0.3277 - loss: 0.8667 - mae: 0.6915 - rmse: 0.9278 - smape: 1.3705 - val_ia: 0.3023 - val_loss: 0.8104 - val_mae: 0.6747 - val_rmse: 0.8312 - val_smape: 1.3724

Epoch 50/128

120/120 - 2s - 13ms/step - ia: 0.3293 - loss: 0.8663 - mae: 0.6915 - rmse: 0.9282 - smape: 1.3687 - val_ia: 0.3028 - val_loss: 0.8100 - val_mae: 0.6745 - val_rmse: 0.8311 - val_smape: 1.3721

Epoch 51/128

120/120 - 3s - 21ms/step - ia: 0.3297 - loss: 0.8674 - mae: 0.6911 - rmse: 0.9291 - smape: 1.3677 - val_ia: 0.3032 - val_loss: 0.8091 - val_mae: 0.6739 - val_rmse: 0.8306 - val_smape: 1.3698

Epoch 52/128

120/120 - 3s - 22ms/step - ia: 0.3298 - loss: 0.8645 - mae: 0.6910 - rmse: 0.9272 - smape: 1.3697 - val_ia: 0.3035 - val_loss: 0.8083 - val_mae: 0.6735 - val_rmse: 0.8302 - val_smape: 1.3678

Epoch 53/128

120/120 - 2s - 13ms/step - ia: 0.3335 - loss: 0.8633 - mae: 0.6900 - rmse: 0.9258 - smape: 1.3620 - val_ia: 0.3039 - val_loss: 0.8076 - val_mae: 0.6732 - val_rmse: 0.8299 - val_smape: 1.3666

Epoch 54/128

120/120 - 3s - 22ms/step - ia: 0.3329 - loss: 0.8631 - mae: 0.6896 - rmse: 0.9266 - smape: 1.3647 - val_ia: 0.3042 - val_loss: 0.8070 - val_mae: 0.6728 - val_rmse: 0.8295 - val_smape: 1.3652

Epoch 55/128

120/120 - 2s - 13ms/step - ia: 0.3324 - loss: 0.8649 - mae: 0.6896 - rmse: 0.9274 - smape: 1.3639 - val_ia: 0.3044 - val_loss: 0.8065 - val_mae: 0.6726 - val_rmse: 0.8293 - val_smape: 1.3649

Epoch 56/128

120/120 - 2s - 13ms/step - ia: 0.3328 - loss: 0.8630 - mae: 0.6902 - rmse: 0.9266 - smape: 1.3660 - val_ia: 0.3048 - val_loss: 0.8059 - val_mae: 0.6724 - val_rmse: 0.8291 - val_smape: 1.3641

Epoch 57/128

120/120 - 2s - 13ms/step - ia: 0.3342 - loss: 0.8612 - mae: 0.6895 - rmse: 0.9252 - smape: 1.3636 - val_ia: 0.3050 - val_loss: 0.8052 - val_mae: 0.6720 - val_rmse: 0.8288 - val_smape: 1.3630

Epoch 58/128

120/120 - 2s - 13ms/step - ia: 0.3359 - loss: 0.8602 - mae: 0.6884 - rmse: 0.9257 - smape: 1.3582 - val_ia: 0.3055 - val_loss: 0.8049 - val_mae: 0.6719 - val_rmse: 0.8287 - val_smape: 1.3626

Epoch 59/128

120/120 - 3s - 21ms/step - ia: 0.3385 - loss: 0.8575 - mae: 0.6861 - rmse: 0.9236 - smape: 1.3546 - val_ia: 0.3060 - val_loss: 0.8044 - val_mae: 0.6717 - val_rmse: 0.8286 - val_smape: 1.3613

Epoch 60/128

120/120 - 3s - 22ms/step - ia: 0.3379 - loss: 0.8611 - mae: 0.6880 - rmse: 0.9250 - smape: 1.3583 - val_ia: 0.3060 - val_loss: 0.8035 - val_mae: 0.6712 - val_rmse: 0.8280 - val_smape: 1.3600

Epoch 61/128

120/120 - 3s - 23ms/step - ia: 0.3369 - loss: 0.8588 - mae: 0.6871 - rmse: 0.9237 - smape: 1.3584 - val_ia: 0.3063 - val_loss: 0.8029 - val_mae: 0.6709 - val_rmse: 0.8277 - val_smape: 1.3589

Epoch 62/128

120/120 - 2s - 20ms/step - ia: 0.3395 - loss: 0.8584 - mae: 0.6863 - rmse: 0.9242 - smape: 1.3523 - val_ia: 0.3064 - val_loss: 0.8022 - val_mae: 0.6705 - val_rmse: 0.8273 - val_smape: 1.3582

Epoch 63/128

120/120 - 3s - 23ms/step - ia: 0.3389 - loss: 0.8585 - mae: 0.6869 - rmse: 0.9240 - smape: 1.3563 - val_ia: 0.3065 - val_loss: 0.8016 - val_mae: 0.6702 - val_rmse: 0.8270 - val_smape: 1.3571

Epoch 64/128

120/120 - 3s - 23ms/step - ia: 0.3387 - loss: 0.8568 - mae: 0.6865 - rmse: 0.9234 - smape: 1.3561 - val_ia: 0.3068 - val_loss: 0.8011 - val_mae: 0.6701 - val_rmse: 0.8268 - val_smape: 1.3567

Epoch 65/128

120/120 - 3s - 22ms/step - ia: 0.3397 - loss: 0.8577 - mae: 0.6856 - rmse: 0.9236 - smape: 1.3525 - val_ia: 0.3070 - val_loss: 0.8007 - val_mae: 0.6699 - val_rmse: 0.8266 - val_smape: 1.3563

Epoch 66/128

120/120 - 2s - 13ms/step - ia: 0.3412 - loss: 0.8549 - mae: 0.6856 - rmse: 0.9217 - smape: 1.3508 - val_ia: 0.3071 - val_loss: 0.8000 - val_mae: 0.6697 - val_rmse: 0.8263 - val_smape: 1.3556

Epoch 67/128

120/120 - 3s - 21ms/step - ia: 0.3403 - loss: 0.8564 - mae: 0.6865 - rmse: 0.9231 - smape: 1.3533 - val_ia: 0.3075 - val_loss: 0.7995 - val_mae: 0.6694 - val_rmse: 0.8261 - val_smape: 1.3549

Epoch 68/128

120/120 - 2s - 13ms/step - ia: 0.3414 - loss: 0.8581 - mae: 0.6857 - rmse: 0.9240 - smape: 1.3510 - val_ia: 0.3078 - val_loss: 0.7994 - val_mae: 0.6695 - val_rmse: 0.8261 - val_smape: 1.3555

Epoch 69/128

120/120 - 3s - 22ms/step - ia: 0.3421 - loss: 0.8561 - mae: 0.6843 - rmse: 0.9229 - smape: 1.3475 - val_ia: 0.3078 - val_loss: 0.7989 - val_mae: 0.6693 - val_rmse: 0.8259 - val_smape: 1.3557

Epoch 70/128

120/120 - 2s - 13ms/step - ia: 0.3426 - loss: 0.8545 - mae: 0.6844 - rmse: 0.9214 - smape: 1.3472 - val_ia: 0.3081 - val_loss: 0.7984 - val_mae: 0.6692 - val_rmse: 0.8257 - val_smape: 1.3551

Epoch 71/128

120/120 - 3s - 21ms/step - ia: 0.3434 - loss: 0.8542 - mae: 0.6839 - rmse: 0.9216 - smape: 1.3483 - val_ia: 0.3083 - val_loss: 0.7980 - val_mae: 0.6689 - val_rmse: 0.8255 - val_smape: 1.3544

Epoch 72/128

120/120 - 2s - 13ms/step - ia: 0.3429 - loss: 0.8539 - mae: 0.6836 - rmse: 0.9220 - smape: 1.3476 - val_ia: 0.3085 - val_loss: 0.7976 - val_mae: 0.6689 - val_rmse: 0.8255 - val_smape: 1.3545

Epoch 73/128

120/120 - 2s - 13ms/step - ia: 0.3442 - loss: 0.8513 - mae: 0.6837 - rmse: 0.9195 - smape: 1.3472 - val_ia: 0.3089 - val_loss: 0.7972 - val_mae: 0.6686 - val_rmse: 0.8252 - val_smape: 1.3535

Epoch 74/128

120/120 - 2s - 13ms/step - ia: 0.3435 - loss: 0.8548 - mae: 0.6842 - rmse: 0.9223 - smape: 1.3478 - val_ia: 0.3090 - val_loss: 0.7967 - val_mae: 0.6685 - val_rmse: 0.8251 - val_smape: 1.3537

Epoch 75/128

120/120 - 1s - 11ms/step - ia: 0.3444 - loss: 0.8505 - mae: 0.6836 - rmse: 0.9191 - smape: 1.3474 - val_ia: 0.3093 - val_loss: 0.7963 - val_mae: 0.6684 - val_rmse: 0.8249 - val_smape: 1.3528

Epoch 76/128

120/120 - 1s - 12ms/step - ia: 0.3442 - loss: 0.8521 - mae: 0.6839 - rmse: 0.9205 - smape: 1.3449 - val_ia: 0.3094 - val_loss: 0.7958 - val_mae: 0.6682 - val_rmse: 0.8246 - val_smape: 1.3522

Epoch 77/128

120/120 - 1s - 10ms/step - ia: 0.3463 - loss: 0.8475 - mae: 0.6822 - rmse: 0.9181 - smape: 1.3443 - val_ia: 0.3097 - val_loss: 0.7954 - val_mae: 0.6680 - val_rmse: 0.8245 - val_smape: 1.3514

Epoch 78/128

120/120 - 1s - 9ms/step - ia: 0.3459 - loss: 0.8503 - mae: 0.6833 - rmse: 0.9190 - smape: 1.3448 - val_ia: 0.3100 - val_loss: 0.7952 - val_mae: 0.6679 - val_rmse: 0.8245 - val_smape: 1.3516

Epoch 79/128

120/120 - 1s - 11ms/step - ia: 0.3470 - loss: 0.8500 - mae: 0.6824 - rmse: 0.9190 - smape: 1.3429 - val_ia: 0.3101 - val_loss: 0.7947 - val_mae: 0.6678 - val_rmse: 0.8242 - val_smape: 1.3514

Epoch 80/128

120/120 - 1s - 9ms/step - ia: 0.3464 - loss: 0.8520 - mae: 0.6831 - rmse: 0.9194 - smape: 1.3442 - val_ia: 0.3101 - val_loss: 0.7941 - val_mae: 0.6674 - val_rmse: 0.8239 - val_smape: 1.3505

Epoch 81/128

120/120 - 1s - 9ms/step - ia: 0.3457 - loss: 0.8509 - mae: 0.6832 - rmse: 0.9202 - smape: 1.3459 - val_ia: 0.3103 - val_loss: 0.7937 - val_mae: 0.6672 - val_rmse: 0.8236 - val_smape: 1.3500

Epoch 82/128

120/120 - 1s - 9ms/step - ia: 0.3480 - loss: 0.8469 - mae: 0.6809 - rmse: 0.9181 - smape: 1.3426 - val_ia: 0.3105 - val_loss: 0.7934 - val_mae: 0.6671 - val_rmse: 0.8235 - val_smape: 1.3497

Epoch 83/128

120/120 - 1s - 9ms/step - ia: 0.3496 - loss: 0.8470 - mae: 0.6798 - rmse: 0.9186 - smape: 1.3362 - val_ia: 0.3107 - val_loss: 0.7930 - val_mae: 0.6670 - val_rmse: 0.8234 - val_smape: 1.3496

Epoch 84/128

120/120 - 1s - 9ms/step - ia: 0.3495 - loss: 0.8485 - mae: 0.6806 - rmse: 0.9187 - smape: 1.3386 - val_ia: 0.3107 - val_loss: 0.7924 - val_mae: 0.6667 - val_rmse: 0.8231 - val_smape: 1.3490

Epoch 85/128

120/120 - 1s - 9ms/step - ia: 0.3494 - loss: 0.8478 - mae: 0.6810 - rmse: 0.9182 - smape: 1.3393 - val_ia: 0.3109 - val_loss: 0.7922 - val_mae: 0.6667 - val_rmse: 0.8231 - val_smape: 1.3487

Epoch 86/128

120/120 - 1s - 10ms/step - ia: 0.3497 - loss: 0.8483 - mae: 0.6815 - rmse: 0.9182 - smape: 1.3394 - val_ia: 0.3111 - val_loss: 0.7920 - val_mae: 0.6667 - val_rmse: 0.8230 - val_smape: 1.3493

Epoch 87/128

120/120 - 1s - 10ms/step - ia: 0.3486 - loss: 0.8482 - mae: 0.6809 - rmse: 0.9187 - smape: 1.3408 - val_ia: 0.3111 - val_loss: 0.7914 - val_mae: 0.6664 - val_rmse: 0.8227 - val_smape: 1.3482

Epoch 88/128

120/120 - 2s - 13ms/step - ia: 0.3483 - loss: 0.8479 - mae: 0.6817 - rmse: 0.9183 - smape: 1.3439 - val_ia: 0.3115 - val_loss: 0.7910 - val_mae: 0.6661 - val_rmse: 0.8225 - val_smape: 1.3469

Epoch 89/128

120/120 - 2s - 13ms/step - ia: 0.3514 - loss: 0.8429 - mae: 0.6797 - rmse: 0.9155 - smape: 1.3392 - val_ia: 0.3117 - val_loss: 0.7908 - val_mae: 0.6661 - val_rmse: 0.8225 - val_smape: 1.3475

Epoch 90/128

120/120 - 2s - 13ms/step - ia: 0.3507 - loss: 0.8473 - mae: 0.6797 - rmse: 0.9181 - smape: 1.3366 - val_ia: 0.3119 - val_loss: 0.7904 - val_mae: 0.6659 - val_rmse: 0.8222 - val_smape: 1.3466

Epoch 91/128

120/120 - 3s - 22ms/step - ia: 0.3503 - loss: 0.8455 - mae: 0.6803 - rmse: 0.9167 - smape: 1.3405 - val_ia: 0.3122 - val_loss: 0.7902 - val_mae: 0.6660 - val_rmse: 0.8223 - val_smape: 1.3468

Epoch 92/128

120/120 - 2s - 14ms/step - ia: 0.3510 - loss: 0.8486 - mae: 0.6806 - rmse: 0.9190 - smape: 1.3371 - val_ia: 0.3123 - val_loss: 0.7899 - val_mae: 0.6658 - val_rmse: 0.8221 - val_smape: 1.3466

Epoch 93/128

120/120 - 2s - 13ms/step - ia: 0.3526 - loss: 0.8443 - mae: 0.6796 - rmse: 0.9158 - smape: 1.3390 - val_ia: 0.3125 - val_loss: 0.7896 - val_mae: 0.6657 - val_rmse: 0.8220 - val_smape: 1.3463

Epoch 94/128

120/120 - 3s - 22ms/step - ia: 0.3523 - loss: 0.8447 - mae: 0.6793 - rmse: 0.9166 - smape: 1.3364 - val_ia: 0.3126 - val_loss: 0.7894 - val_mae: 0.6657 - val_rmse: 0.8220 - val_smape: 1.3466

Epoch 95/128

120/120 - 3s - 21ms/step - ia: 0.3527 - loss: 0.8439 - mae: 0.6789 - rmse: 0.9161 - smape: 1.3359 - val_ia: 0.3128 - val_loss: 0.7891 - val_mae: 0.6655 - val_rmse: 0.8218 - val_smape: 1.3460

Epoch 96/128

120/120 - 2s - 13ms/step - ia: 0.3543 - loss: 0.8418 - mae: 0.6781 - rmse: 0.9144 - smape: 1.3332 - val_ia: 0.3129 - val_loss: 0.7888 - val_mae: 0.6655 - val_rmse: 0.8218 - val_smape: 1.3457

Epoch 97/128

120/120 - 1s - 12ms/step - ia: 0.3536 - loss: 0.8421 - mae: 0.6783 - rmse: 0.9149 - smape: 1.3372 - val_ia: 0.3132 - val_loss: 0.7888 - val_mae: 0.6656 - val_rmse: 0.8218 - val_smape: 1.3458

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

120/120 - 33s - 271ms/step - ia: 0.3428 - loss: 0.8445 - mae: 0.6793 - rmse: 0.9164 - smape: 1.3537 - val_ia: 0.3433 - val_loss: 0.7771 - val_mae: 0.6497 - val_rmse: 0.8164 - val_smape: 1.2605

Epoch 2/256

120/120 - 3s - 24ms/step - ia: 0.4001 - loss: 0.7937 - mae: 0.6536 - rmse: 0.8884 - smape: 1.2673 - val_ia: 0.3608 - val_loss: 0.7765 - val_mae: 0.6426 - val_rmse: 0.8139 - val_smape: 1.2222

Epoch 3/256

120/120 - 3s - 22ms/step - ia: 0.4147 - loss: 0.7748 - mae: 0.6438 - rmse: 0.8775 - smape: 1.2461 - val_ia: 0.3470 - val_loss: 0.7643 - val_mae: 0.6422 - val_rmse: 0.8091 - val_smape: 1.2607

Epoch 4/256

120/120 - 3s - 26ms/step - ia: 0.4171 - loss: 0.7654 - mae: 0.6414 - rmse: 0.8722 - smape: 1.2474 - val_ia: 0.3568 - val_loss: 0.7604 - val_mae: 0.6351 - val_rmse: 0.8033 - val_smape: 1.2405

Epoch 5/256

120/120 - 2s - 20ms/step - ia: 0.4256 - loss: 0.7596 - mae: 0.6371 - rmse: 0.8690 - smape: 1.2299 - val_ia: 0.3654 - val_loss: 0.7656 - val_mae: 0.6343 - val_rmse: 0.8046 - val_smape: 1.2347

Epoch 6/256

120/120 - 3s - 23ms/step - ia: 0.4362 - loss: 0.7417 - mae: 0.6299 - rmse: 0.8588 - smape: 1.2192 - val_ia: 0.3622 - val_loss: 0.8611 - val_mae: 0.6687 - val_rmse: 0.8554 - val_smape: 1.2598

Epoch 7/256

120/120 - 3s - 25ms/step - ia: 0.4381 - loss: 0.7375 - mae: 0.6288 - rmse: 0.8558 - smape: 1.2199 - val_ia: 0.3611 - val_loss: 0.7887 - val_mae: 0.6388 - val_rmse: 0.8121 - val_smape: 1.2364

Epoch 8/256

120/120 - 2s - 20ms/step - ia: 0.4439 - loss: 0.7296 - mae: 0.6254 - rmse: 0.8520 - smape: 1.2116 - val_ia: 0.3620 - val_loss: 0.7967 - val_mae: 0.6482 - val_rmse: 0.8246 - val_smape: 1.2423

Epoch 9/256

120/120 - 2s - 20ms/step - ia: 0.4445 - loss: 0.7219 - mae: 0.6231 - rmse: 0.8472 - smape: 1.2110 - val_ia: 0.3714 - val_loss: 0.8292 - val_mae: 0.6521 - val_rmse: 0.8336 - val_smape: 1.2374

Epoch 10/256

120/120 - 3s - 22ms/step - ia: 0.4508 - loss: 0.7166 - mae: 0.6191 - rmse: 0.8442 - smape: 1.2019 - val_ia: 0.3581 - val_loss: 0.8425 - val_mae: 0.6551 - val_rmse: 0.8355 - val_smape: 1.2642

Epoch 11/256

120/120 - 2s - 19ms/step - ia: 0.4533 - loss: 0.7037 - mae: 0.6147 - rmse: 0.8361 - smape: 1.2079 - val_ia: 0.3568 - val_loss: 0.8789 - val_mae: 0.6757 - val_rmse: 0.8613 - val_smape: 1.2893

Epoch 12/256

120/120 - 2s - 18ms/step - ia: 0.4583 - loss: 0.6957 - mae: 0.6126 - rmse: 0.8314 - smape: 1.2027 - val_ia: 0.3550 - val_loss: 0.9419 - val_mae: 0.6821 - val_rmse: 0.8777 - val_smape: 1.2828

Epoch 13/256

120/120 - 2s - 19ms/step - ia: 0.4515 - loss: 0.7059 - mae: 0.6153 - rmse: 0.8374 - smape: 1.2073 - val_ia: 0.3637 - val_loss: 0.8623 - val_mae: 0.6670 - val_rmse: 0.8461 - val_smape: 1.2720

Epoch 14/256

120/120 - 3s - 23ms/step - ia: 0.4596 - loss: 0.6963 - mae: 0.6121 - rmse: 0.8324 - smape: 1.1964 - val_ia: 0.3543 - val_loss: 0.8966 - val_mae: 0.6633 - val_rmse: 0.8534 - val_smape: 1.2726

Epoch 15/256

120/120 - 3s - 23ms/step - ia: 0.4660 - loss: 0.6746 - mae: 0.6047 - rmse: 0.8192 - smape: 1.1963 - val_ia: 0.3652 - val_loss: 0.9016 - val_mae: 0.6741 - val_rmse: 0.8634 - val_smape: 1.2837

Epoch 16/256

120/120 - 3s - 22ms/step - ia: 0.4712 - loss: 0.6671 - mae: 0.6009 - rmse: 0.8137 - smape: 1.1907 - val_ia: 0.3629 - val_loss: 0.9779 - val_mae: 0.6870 - val_rmse: 0.8894 - val_smape: 1.2611

Epoch 17/256

120/120 - 3s - 21ms/step - ia: 0.4718 - loss: 0.6654 - mae: 0.6011 - rmse: 0.8134 - smape: 1.1902 - val_ia: 0.3612 - val_loss: 0.9434 - val_mae: 0.6847 - val_rmse: 0.8795 - val_smape: 1.2895

Epoch 18/256

120/120 - 3s - 21ms/step - ia: 0.4780 - loss: 0.6521 - mae: 0.5955 - rmse: 0.8054 - smape: 1.1863 - val_ia: 0.3661 - val_loss: 0.9268 - val_mae: 0.6805 - val_rmse: 0.8741 - val_smape: 1.2711

Epoch 19/256

120/120 - 2s - 20ms/step - ia: 0.4803 - loss: 0.6508 - mae: 0.5949 - rmse: 0.8047 - smape: 1.1811 - val_ia: 0.3584 - val_loss: 0.9008 - val_mae: 0.6704 - val_rmse: 0.8543 - val_smape: 1.2821

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:49 812ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 74%|███████▍  | 37/50 [11:18:11<57:25, 265.04s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 14s - 28ms/step - ia: 0.3055 - loss: 0.8743 - mae: 0.6951 - rmse: 0.9244 - smape: 1.4368 - val_ia: 0.2685 - val_loss: 0.7801 - val_mae: 0.6593 - val_rmse: 0.7818 - val_smape: 1.3293

Epoch 2/8

479/479 - 4s - 9ms/step - ia: 0.3597 - loss: 0.8293 - mae: 0.6735 - rmse: 0.9008 - smape: 1.3392 - val_ia: 0.2619 - val_loss: 0.7566 - val_mae: 0.6459 - val_rmse: 0.7631 - val_smape: 1.3049

Epoch 3/8

479/479 - 4s - 9ms/step - ia: 0.3754 - loss: 0.8158 - mae: 0.6648 - rmse: 0.8930 - smape: 1.3101 - val_ia: 0.2761 - val_loss: 0.7540 - val_mae: 0.6448 - val_rmse: 0.7657 - val_smape: 1.2957

Epoch 4/8

479/479 - 4s - 9ms/step - ia: 0.3908 - loss: 0.8010 - mae: 0.6573 - rmse: 0.8850 - smape: 1.2817 - val_ia: 0.2772 - val_loss: 0.7619 - val_mae: 0.6440 - val_rmse: 0.7676 - val_smape: 1.2881

Epoch 5/8

479/479 - 4s - 9ms/step - ia: 0.3951 - loss: 0.7924 - mae: 0.6527 - rmse: 0.8803 - smape: 1.2730 - val_ia: 0.2912 - val_loss: 0.7869 - val_mae: 0.6625 - val_rmse: 0.7919 - val_smape: 1.2977

Epoch 6/8

479/479 - 5s - 11ms/step - ia: 0.3996 - loss: 0.7877 - mae: 0.6511 - rmse: 0.8782 - smape: 1.2657 - val_ia: 0.2931 - val_loss: 0.7824 - val_mae: 0.6530 - val_rmse: 0.7850 - val_smape: 1.2733

Epoch 7/8

479/479 - 4s - 9ms/step - ia: 0.4050 - loss: 0.7806 - mae: 0.6479 - rmse: 0.8746 - smape: 1.2627 - val_ia: 0.2812 - val_loss: 0.7527 - val_mae: 0.6388 - val_rmse: 0.7629 - val_smape: 1.2822

Epoch 8/8

479/479 - 4s - 9ms/step - ia: 0.4098 - loss: 0.7716 - mae: 0.6442 - rmse: 0.8689 - smape: 1.2528 - val_ia: 0.2865 - val_loss: 0.8061 - val_mae: 0.6472 - val_rmse: 0.7819 - val_smape: 1.2604

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:11 533ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 76%|███████▌  | 38/50 [11:18:58<39:56, 199.70s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 15s - 124ms/step - ia: 0.1097 - loss: 0.9929 - mae: 0.7459 - rmse: 0.9939 - smape: 1.7391 - val_ia: 0.2565 - val_loss: 0.9393 - val_mae: 0.7305 - val_rmse: 0.8899 - val_smape: 1.7933

Epoch 2/128

120/120 - 4s - 30ms/step - ia: 0.1426 - loss: 0.9591 - mae: 0.7329 - rmse: 0.9763 - smape: 1.6766 - val_ia: 0.2595 - val_loss: 0.9001 - val_mae: 0.7146 - val_rmse: 0.8711 - val_smape: 1.6812

Epoch 3/128

120/120 - 3s - 23ms/step - ia: 0.1897 - loss: 0.9297 - mae: 0.7215 - rmse: 0.9612 - smape: 1.5978 - val_ia: 0.2661 - val_loss: 0.8708 - val_mae: 0.7030 - val_rmse: 0.8579 - val_smape: 1.5658

Epoch 4/128

120/120 - 5s - 40ms/step - ia: 0.2308 - loss: 0.9120 - mae: 0.7139 - rmse: 0.9514 - smape: 1.5242 - val_ia: 0.2746 - val_loss: 0.8534 - val_mae: 0.6954 - val_rmse: 0.8504 - val_smape: 1.4907

Epoch 5/128

120/120 - 3s - 22ms/step - ia: 0.2634 - loss: 0.8971 - mae: 0.7069 - rmse: 0.9448 - smape: 1.4666 - val_ia: 0.2815 - val_loss: 0.8423 - val_mae: 0.6899 - val_rmse: 0.8456 - val_smape: 1.4399

Epoch 6/128

120/120 - 2s - 20ms/step - ia: 0.2830 - loss: 0.8922 - mae: 0.7039 - rmse: 0.9414 - smape: 1.4408 - val_ia: 0.2855 - val_loss: 0.8349 - val_mae: 0.6857 - val_rmse: 0.8421 - val_smape: 1.4082

Epoch 7/128

120/120 - 2s - 19ms/step - ia: 0.2975 - loss: 0.8851 - mae: 0.7008 - rmse: 0.9377 - smape: 1.4163 - val_ia: 0.2886 - val_loss: 0.8306 - val_mae: 0.6841 - val_rmse: 0.8407 - val_smape: 1.3928

Epoch 8/128

120/120 - 2s - 20ms/step - ia: 0.3057 - loss: 0.8808 - mae: 0.6985 - rmse: 0.9358 - smape: 1.4025 - val_ia: 0.2906 - val_loss: 0.8267 - val_mae: 0.6818 - val_rmse: 0.8389 - val_smape: 1.3796

Epoch 9/128

120/120 - 3s - 22ms/step - ia: 0.3081 - loss: 0.8820 - mae: 0.6984 - rmse: 0.9362 - smape: 1.3984 - val_ia: 0.2914 - val_loss: 0.8238 - val_mae: 0.6802 - val_rmse: 0.8374 - val_smape: 1.3742

Epoch 10/128

120/120 - 3s - 21ms/step - ia: 0.3133 - loss: 0.8763 - mae: 0.6961 - rmse: 0.9333 - smape: 1.3900 - val_ia: 0.2928 - val_loss: 0.8220 - val_mae: 0.6794 - val_rmse: 0.8368 - val_smape: 1.3718

Epoch 11/128

120/120 - 2s - 19ms/step - ia: 0.3151 - loss: 0.8726 - mae: 0.6950 - rmse: 0.9311 - smape: 1.3876 - val_ia: 0.2939 - val_loss: 0.8191 - val_mae: 0.6781 - val_rmse: 0.8355 - val_smape: 1.3655

Epoch 12/128

120/120 - 2s - 19ms/step - ia: 0.3197 - loss: 0.8720 - mae: 0.6925 - rmse: 0.9314 - smape: 1.3806 - val_ia: 0.2951 - val_loss: 0.8172 - val_mae: 0.6771 - val_rmse: 0.8348 - val_smape: 1.3599

Epoch 13/128

120/120 - 3s - 21ms/step - ia: 0.3217 - loss: 0.8692 - mae: 0.6914 - rmse: 0.9295 - smape: 1.3772 - val_ia: 0.2957 - val_loss: 0.8153 - val_mae: 0.6765 - val_rmse: 0.8340 - val_smape: 1.3575

Epoch 14/128

120/120 - 2s - 18ms/step - ia: 0.3265 - loss: 0.8657 - mae: 0.6903 - rmse: 0.9284 - smape: 1.3720 - val_ia: 0.2975 - val_loss: 0.8145 - val_mae: 0.6759 - val_rmse: 0.8339 - val_smape: 1.3580

Epoch 15/128

120/120 - 3s - 23ms/step - ia: 0.3270 - loss: 0.8629 - mae: 0.6902 - rmse: 0.9264 - smape: 1.3723 - val_ia: 0.2983 - val_loss: 0.8130 - val_mae: 0.6756 - val_rmse: 0.8335 - val_smape: 1.3578

Epoch 16/128

120/120 - 3s - 22ms/step - ia: 0.3293 - loss: 0.8640 - mae: 0.6893 - rmse: 0.9264 - smape: 1.3684 - val_ia: 0.2978 - val_loss: 0.8104 - val_mae: 0.6744 - val_rmse: 0.8320 - val_smape: 1.3591

Epoch 17/128

120/120 - 3s - 22ms/step - ia: 0.3296 - loss: 0.8589 - mae: 0.6875 - rmse: 0.9236 - smape: 1.3702 - val_ia: 0.3002 - val_loss: 0.8101 - val_mae: 0.6744 - val_rmse: 0.8325 - val_smape: 1.3554

Epoch 18/128

120/120 - 3s - 22ms/step - ia: 0.3338 - loss: 0.8589 - mae: 0.6864 - rmse: 0.9234 - smape: 1.3619 - val_ia: 0.3008 - val_loss: 0.8083 - val_mae: 0.6734 - val_rmse: 0.8316 - val_smape: 1.3514

Epoch 19/128

120/120 - 2s - 20ms/step - ia: 0.3330 - loss: 0.8565 - mae: 0.6865 - rmse: 0.9232 - smape: 1.3631 - val_ia: 0.3018 - val_loss: 0.8066 - val_mae: 0.6727 - val_rmse: 0.8310 - val_smape: 1.3491

Epoch 20/128

120/120 - 2s - 19ms/step - ia: 0.3371 - loss: 0.8555 - mae: 0.6854 - rmse: 0.9216 - smape: 1.3590 - val_ia: 0.3016 - val_loss: 0.8047 - val_mae: 0.6718 - val_rmse: 0.8299 - val_smape: 1.3501

Epoch 21/128

120/120 - 2s - 19ms/step - ia: 0.3376 - loss: 0.8537 - mae: 0.6837 - rmse: 0.9221 - smape: 1.3560 - val_ia: 0.3036 - val_loss: 0.8046 - val_mae: 0.6715 - val_rmse: 0.8303 - val_smape: 1.3477

Epoch 22/128

120/120 - 2s - 20ms/step - ia: 0.3379 - loss: 0.8521 - mae: 0.6841 - rmse: 0.9207 - smape: 1.3576 - val_ia: 0.3045 - val_loss: 0.8036 - val_mae: 0.6712 - val_rmse: 0.8301 - val_smape: 1.3474

Epoch 23/128

120/120 - 2s - 20ms/step - ia: 0.3401 - loss: 0.8517 - mae: 0.6836 - rmse: 0.9201 - smape: 1.3525 - val_ia: 0.3052 - val_loss: 0.8020 - val_mae: 0.6704 - val_rmse: 0.8292 - val_smape: 1.3457

Epoch 24/128

120/120 - 3s - 27ms/step - ia: 0.3420 - loss: 0.8473 - mae: 0.6812 - rmse: 0.9189 - smape: 1.3490 - val_ia: 0.3060 - val_loss: 0.8000 - val_mae: 0.6693 - val_rmse: 0.8281 - val_smape: 1.3438

Epoch 25/128

120/120 - 5s - 42ms/step - ia: 0.3424 - loss: 0.8476 - mae: 0.6809 - rmse: 0.9188 - smape: 1.3491 - val_ia: 0.3080 - val_loss: 0.7994 - val_mae: 0.6688 - val_rmse: 0.8281 - val_smape: 1.3411

Epoch 26/128

120/120 - 6s - 52ms/step - ia: 0.3461 - loss: 0.8463 - mae: 0.6802 - rmse: 0.9173 - smape: 1.3457 - val_ia: 0.3085 - val_loss: 0.7986 - val_mae: 0.6689 - val_rmse: 0.8280 - val_smape: 1.3408

Epoch 27/128

120/120 - 6s - 50ms/step - ia: 0.3452 - loss: 0.8457 - mae: 0.6795 - rmse: 0.9169 - smape: 1.3459 - val_ia: 0.3094 - val_loss: 0.7979 - val_mae: 0.6685 - val_rmse: 0.8277 - val_smape: 1.3386

Epoch 28/128

120/120 - 4s - 37ms/step - ia: 0.3482 - loss: 0.8448 - mae: 0.6793 - rmse: 0.9168 - smape: 1.3431 - val_ia: 0.3107 - val_loss: 0.7966 - val_mae: 0.6677 - val_rmse: 0.8272 - val_smape: 1.3381

Epoch 29/128

120/120 - 4s - 29ms/step - ia: 0.3513 - loss: 0.8413 - mae: 0.6775 - rmse: 0.9147 - smape: 1.3368 - val_ia: 0.3122 - val_loss: 0.7972 - val_mae: 0.6678 - val_rmse: 0.8277 - val_smape: 1.3360

Epoch 30/128

120/120 - 5s - 38ms/step - ia: 0.3506 - loss: 0.8404 - mae: 0.6774 - rmse: 0.9145 - smape: 1.3390 - val_ia: 0.3126 - val_loss: 0.7961 - val_mae: 0.6672 - val_rmse: 0.8272 - val_smape: 1.3349

Epoch 31/128

120/120 - 5s - 42ms/step - ia: 0.3509 - loss: 0.8405 - mae: 0.6781 - rmse: 0.9138 - smape: 1.3398 - val_ia: 0.3142 - val_loss: 0.7967 - val_mae: 0.6677 - val_rmse: 0.8280 - val_smape: 1.3341

Epoch 32/128

120/120 - 3s - 22ms/step - ia: 0.3521 - loss: 0.8380 - mae: 0.6759 - rmse: 0.9127 - smape: 1.3371 - val_ia: 0.3150 - val_loss: 0.7956 - val_mae: 0.6666 - val_rmse: 0.8271 - val_smape: 1.3300

Epoch 33/128

120/120 - 3s - 24ms/step - ia: 0.3561 - loss: 0.8355 - mae: 0.6756 - rmse: 0.9121 - smape: 1.3319 - val_ia: 0.3151 - val_loss: 0.7937 - val_mae: 0.6656 - val_rmse: 0.8260 - val_smape: 1.3291

Epoch 34/128

120/120 - 3s - 25ms/step - ia: 0.3550 - loss: 0.8348 - mae: 0.6749 - rmse: 0.9113 - smape: 1.3331 - val_ia: 0.3169 - val_loss: 0.7944 - val_mae: 0.6656 - val_rmse: 0.8265 - val_smape: 1.3258

Epoch 35/128

120/120 - 5s - 38ms/step - ia: 0.3593 - loss: 0.8319 - mae: 0.6734 - rmse: 0.9095 - smape: 1.3270 - val_ia: 0.3187 - val_loss: 0.7947 - val_mae: 0.6655 - val_rmse: 0.8268 - val_smape: 1.3243

Epoch 36/128

120/120 - 3s - 23ms/step - ia: 0.3616 - loss: 0.8292 - mae: 0.6725 - rmse: 0.9085 - smape: 1.3241 - val_ia: 0.3191 - val_loss: 0.7930 - val_mae: 0.6647 - val_rmse: 0.8259 - val_smape: 1.3241

Epoch 37/128

120/120 - 2s - 19ms/step - ia: 0.3603 - loss: 0.8306 - mae: 0.6724 - rmse: 0.9086 - smape: 1.3268 - val_ia: 0.3203 - val_loss: 0.7939 - val_mae: 0.6651 - val_rmse: 0.8267 - val_smape: 1.3215

Epoch 38/128

120/120 - 3s - 22ms/step - ia: 0.3623 - loss: 0.8299 - mae: 0.6726 - rmse: 0.9081 - smape: 1.3212 - val_ia: 0.3203 - val_loss: 0.7928 - val_mae: 0.6640 - val_rmse: 0.8256 - val_smape: 1.3201

Epoch 39/128

120/120 - 2s - 19ms/step - ia: 0.3619 - loss: 0.8313 - mae: 0.6723 - rmse: 0.9089 - smape: 1.3238 - val_ia: 0.3208 - val_loss: 0.7922 - val_mae: 0.6643 - val_rmse: 0.8258 - val_smape: 1.3229

Epoch 40/128

120/120 - 2s - 20ms/step - ia: 0.3605 - loss: 0.8288 - mae: 0.6713 - rmse: 0.9077 - smape: 1.3256 - val_ia: 0.3231 - val_loss: 0.7950 - val_mae: 0.6653 - val_rmse: 0.8276 - val_smape: 1.3195

Epoch 41/128

120/120 - 3s - 22ms/step - ia: 0.3642 - loss: 0.8285 - mae: 0.6720 - rmse: 0.9080 - smape: 1.3191 - val_ia: 0.3236 - val_loss: 0.7928 - val_mae: 0.6633 - val_rmse: 0.8258 - val_smape: 1.3163

Epoch 42/128

120/120 - 2s - 20ms/step - ia: 0.3652 - loss: 0.8285 - mae: 0.6709 - rmse: 0.9076 - smape: 1.3198 - val_ia: 0.3234 - val_loss: 0.7919 - val_mae: 0.6636 - val_rmse: 0.8257 - val_smape: 1.3190

Epoch 43/128

120/120 - 2s - 20ms/step - ia: 0.3631 - loss: 0.8275 - mae: 0.6715 - rmse: 0.9070 - smape: 1.3240 - val_ia: 0.3241 - val_loss: 0.7916 - val_mae: 0.6629 - val_rmse: 0.8253 - val_smape: 1.3172

Epoch 44/128

120/120 - 3s - 23ms/step - ia: 0.3668 - loss: 0.8241 - mae: 0.6690 - rmse: 0.9055 - smape: 1.3181 - val_ia: 0.3257 - val_loss: 0.7924 - val_mae: 0.6629 - val_rmse: 0.8258 - val_smape: 1.3137

Epoch 45/128

120/120 - 2s - 21ms/step - ia: 0.3673 - loss: 0.8247 - mae: 0.6706 - rmse: 0.9050 - smape: 1.3178 - val_ia: 0.3255 - val_loss: 0.7914 - val_mae: 0.6625 - val_rmse: 0.8252 - val_smape: 1.3140

Epoch 46/128

120/120 - 2s - 21ms/step - ia: 0.3688 - loss: 0.8225 - mae: 0.6690 - rmse: 0.9043 - smape: 1.3157 - val_ia: 0.3258 - val_loss: 0.7908 - val_mae: 0.6620 - val_rmse: 0.8247 - val_smape: 1.3137

Epoch 47/128

120/120 - 2s - 19ms/step - ia: 0.3673 - loss: 0.8238 - mae: 0.6683 - rmse: 0.9047 - smape: 1.3157 - val_ia: 0.3265 - val_loss: 0.7919 - val_mae: 0.6627 - val_rmse: 0.8255 - val_smape: 1.3127

Epoch 48/128

120/120 - 2s - 19ms/step - ia: 0.3715 - loss: 0.8221 - mae: 0.6686 - rmse: 0.9042 - smape: 1.3119 - val_ia: 0.3274 - val_loss: 0.7907 - val_mae: 0.6619 - val_rmse: 0.8250 - val_smape: 1.3122

Epoch 49/128

120/120 - 3s - 24ms/step - ia: 0.3702 - loss: 0.8223 - mae: 0.6675 - rmse: 0.9041 - smape: 1.3128 - val_ia: 0.3285 - val_loss: 0.7914 - val_mae: 0.6618 - val_rmse: 0.8252 - val_smape: 1.3093

Epoch 50/128

120/120 - 2s - 20ms/step - ia: 0.3709 - loss: 0.8232 - mae: 0.6684 - rmse: 0.9047 - smape: 1.3096 - val_ia: 0.3283 - val_loss: 0.7901 - val_mae: 0.6614 - val_rmse: 0.8246 - val_smape: 1.3107

Epoch 51/128

120/120 - 2s - 19ms/step - ia: 0.3718 - loss: 0.8208 - mae: 0.6665 - rmse: 0.9031 - smape: 1.3083 - val_ia: 0.3283 - val_loss: 0.7898 - val_mae: 0.6610 - val_rmse: 0.8242 - val_smape: 1.3093

Epoch 52/128

120/120 - 2s - 20ms/step - ia: 0.3709 - loss: 0.8170 - mae: 0.6672 - rmse: 0.9014 - smape: 1.3119 - val_ia: 0.3297 - val_loss: 0.7910 - val_mae: 0.6614 - val_rmse: 0.8250 - val_smape: 1.3060

Epoch 53/128

120/120 - 2s - 19ms/step - ia: 0.3772 - loss: 0.8160 - mae: 0.6653 - rmse: 0.9005 - smape: 1.3026 - val_ia: 0.3302 - val_loss: 0.7902 - val_mae: 0.6607 - val_rmse: 0.8244 - val_smape: 1.3047

Epoch 54/128

120/120 - 3s - 22ms/step - ia: 0.3748 - loss: 0.8184 - mae: 0.6659 - rmse: 0.9019 - smape: 1.3057 - val_ia: 0.3298 - val_loss: 0.7896 - val_mae: 0.6612 - val_rmse: 0.8245 - val_smape: 1.3081

Epoch 55/128

120/120 - 3s - 22ms/step - ia: 0.3760 - loss: 0.8162 - mae: 0.6653 - rmse: 0.9003 - smape: 1.3007 - val_ia: 0.3316 - val_loss: 0.7920 - val_mae: 0.6618 - val_rmse: 0.8258 - val_smape: 1.3052

Epoch 56/128

120/120 - 2s - 19ms/step - ia: 0.3725 - loss: 0.8204 - mae: 0.6666 - rmse: 0.9037 - smape: 1.3085 - val_ia: 0.3318 - val_loss: 0.7907 - val_mae: 0.6610 - val_rmse: 0.8251 - val_smape: 1.3041

Epoch 57/128

120/120 - 2s - 19ms/step - ia: 0.3764 - loss: 0.8150 - mae: 0.6648 - rmse: 0.9008 - smape: 1.3041 - val_ia: 0.3323 - val_loss: 0.7900 - val_mae: 0.6602 - val_rmse: 0.8244 - val_smape: 1.3022

Epoch 58/128

120/120 - 2s - 20ms/step - ia: 0.3780 - loss: 0.8148 - mae: 0.6649 - rmse: 0.8996 - smape: 1.3022 - val_ia: 0.3333 - val_loss: 0.7921 - val_mae: 0.6613 - val_rmse: 0.8259 - val_smape: 1.3016

Epoch 59/128

120/120 - 2s - 19ms/step - ia: 0.3790 - loss: 0.8133 - mae: 0.6637 - rmse: 0.8995 - smape: 1.3002 - val_ia: 0.3331 - val_loss: 0.7908 - val_mae: 0.6605 - val_rmse: 0.8249 - val_smape: 1.3010

Epoch 60/128

120/120 - 2s - 18ms/step - ia: 0.3779 - loss: 0.8132 - mae: 0.6647 - rmse: 0.8991 - smape: 1.3019 - val_ia: 0.3330 - val_loss: 0.7892 - val_mae: 0.6597 - val_rmse: 0.8239 - val_smape: 1.3009

Epoch 61/128

120/120 - 2s - 17ms/step - ia: 0.3783 - loss: 0.8157 - mae: 0.6644 - rmse: 0.9010 - smape: 1.3008 - val_ia: 0.3335 - val_loss: 0.7893 - val_mae: 0.6601 - val_rmse: 0.8243 - val_smape: 1.3022

Epoch 62/128

120/120 - 3s - 25ms/step - ia: 0.3784 - loss: 0.8124 - mae: 0.6636 - rmse: 0.8982 - smape: 1.2987 - val_ia: 0.3335 - val_loss: 0.7895 - val_mae: 0.6600 - val_rmse: 0.8242 - val_smape: 1.3010

Epoch 63/128

120/120 - 2s - 19ms/step - ia: 0.3801 - loss: 0.8148 - mae: 0.6634 - rmse: 0.9006 - smape: 1.2972 - val_ia: 0.3349 - val_loss: 0.7888 - val_mae: 0.6592 - val_rmse: 0.8238 - val_smape: 1.2990

Epoch 64/128

120/120 - 2s - 20ms/step - ia: 0.3792 - loss: 0.8139 - mae: 0.6633 - rmse: 0.8998 - smape: 1.2975 - val_ia: 0.3344 - val_loss: 0.7891 - val_mae: 0.6601 - val_rmse: 0.8243 - val_smape: 1.3014

Epoch 65/128

120/120 - 3s - 21ms/step - ia: 0.3801 - loss: 0.8141 - mae: 0.6645 - rmse: 0.8998 - smape: 1.2966 - val_ia: 0.3340 - val_loss: 0.7890 - val_mae: 0.6598 - val_rmse: 0.8239 - val_smape: 1.3005

Epoch 66/128

120/120 - 2s - 20ms/step - ia: 0.3794 - loss: 0.8128 - mae: 0.6634 - rmse: 0.8987 - smape: 1.2977 - val_ia: 0.3353 - val_loss: 0.7887 - val_mae: 0.6594 - val_rmse: 0.8238 - val_smape: 1.2998

Epoch 67/128

120/120 - 3s - 22ms/step - ia: 0.3819 - loss: 0.8123 - mae: 0.6625 - rmse: 0.8983 - smape: 1.2944 - val_ia: 0.3354 - val_loss: 0.7875 - val_mae: 0.6589 - val_rmse: 0.8233 - val_smape: 1.3011

Epoch 68/128

120/120 - 2s - 19ms/step - ia: 0.3809 - loss: 0.8106 - mae: 0.6620 - rmse: 0.8974 - smape: 1.2963 - val_ia: 0.3363 - val_loss: 0.7888 - val_mae: 0.6592 - val_rmse: 0.8240 - val_smape: 1.2971

Epoch 69/128

120/120 - 2s - 19ms/step - ia: 0.3842 - loss: 0.8074 - mae: 0.6621 - rmse: 0.8954 - smape: 1.2929 - val_ia: 0.3361 - val_loss: 0.7880 - val_mae: 0.6588 - val_rmse: 0.8234 - val_smape: 1.2972

Epoch 70/128

120/120 - 3s - 22ms/step - ia: 0.3820 - loss: 0.8113 - mae: 0.6617 - rmse: 0.8979 - smape: 1.2942 - val_ia: 0.3372 - val_loss: 0.7893 - val_mae: 0.6594 - val_rmse: 0.8244 - val_smape: 1.2964

Epoch 71/128

120/120 - 2s - 19ms/step - ia: 0.3837 - loss: 0.8086 - mae: 0.6620 - rmse: 0.8968 - smape: 1.2922 - val_ia: 0.3372 - val_loss: 0.7895 - val_mae: 0.6595 - val_rmse: 0.8246 - val_smape: 1.2974

Epoch 72/128

120/120 - 3s - 23ms/step - ia: 0.3833 - loss: 0.8102 - mae: 0.6620 - rmse: 0.8982 - smape: 1.2940 - val_ia: 0.3366 - val_loss: 0.7876 - val_mae: 0.6585 - val_rmse: 0.8232 - val_smape: 1.2973

Epoch 73/128

120/120 - 2s - 17ms/step - ia: 0.3846 - loss: 0.8078 - mae: 0.6608 - rmse: 0.8962 - smape: 1.2888 - val_ia: 0.3374 - val_loss: 0.7875 - val_mae: 0.6581 - val_rmse: 0.8231 - val_smape: 1.2956

Epoch 74/128

120/120 - 2s - 19ms/step - ia: 0.3846 - loss: 0.8094 - mae: 0.6618 - rmse: 0.8971 - smape: 1.2895 - val_ia: 0.3373 - val_loss: 0.7869 - val_mae: 0.6578 - val_rmse: 0.8227 - val_smape: 1.2962

Epoch 75/128

120/120 - 2s - 20ms/step - ia: 0.3844 - loss: 0.8074 - mae: 0.6602 - rmse: 0.8961 - smape: 1.2921 - val_ia: 0.3387 - val_loss: 0.7878 - val_mae: 0.6583 - val_rmse: 0.8235 - val_smape: 1.2948

Epoch 76/128

120/120 - 2s - 19ms/step - ia: 0.3863 - loss: 0.8064 - mae: 0.6599 - rmse: 0.8961 - smape: 1.2872 - val_ia: 0.3395 - val_loss: 0.7888 - val_mae: 0.6582 - val_rmse: 0.8239 - val_smape: 1.2932

Epoch 77/128

120/120 - 2s - 19ms/step - ia: 0.3866 - loss: 0.8070 - mae: 0.6607 - rmse: 0.8954 - smape: 1.2905 - val_ia: 0.3398 - val_loss: 0.7877 - val_mae: 0.6576 - val_rmse: 0.8232 - val_smape: 1.2919

Epoch 78/128

120/120 - 2s - 20ms/step - ia: 0.3853 - loss: 0.8041 - mae: 0.6603 - rmse: 0.8943 - smape: 1.2916 - val_ia: 0.3410 - val_loss: 0.7903 - val_mae: 0.6585 - val_rmse: 0.8247 - val_smape: 1.2903

Epoch 79/128

120/120 - 3s - 22ms/step - ia: 0.3893 - loss: 0.8042 - mae: 0.6594 - rmse: 0.8940 - smape: 1.2843 - val_ia: 0.3406 - val_loss: 0.7882 - val_mae: 0.6574 - val_rmse: 0.8234 - val_smape: 1.2911

Epoch 80/128

120/120 - 2s - 19ms/step - ia: 0.3885 - loss: 0.8038 - mae: 0.6587 - rmse: 0.8941 - smape: 1.2854 - val_ia: 0.3406 - val_loss: 0.7901 - val_mae: 0.6587 - val_rmse: 0.8247 - val_smape: 1.2931

Epoch 81/128

120/120 - 2s - 19ms/step - ia: 0.3906 - loss: 0.8042 - mae: 0.6589 - rmse: 0.8945 - smape: 1.2810 - val_ia: 0.3397 - val_loss: 0.7874 - val_mae: 0.6573 - val_rmse: 0.8229 - val_smape: 1.2931

Epoch 82/128

120/120 - 2s - 20ms/step - ia: 0.3879 - loss: 0.8039 - mae: 0.6585 - rmse: 0.8939 - smape: 1.2856 - val_ia: 0.3411 - val_loss: 0.7890 - val_mae: 0.6580 - val_rmse: 0.8241 - val_smape: 1.2920

Epoch 83/128

120/120 - 3s - 21ms/step - ia: 0.3918 - loss: 0.8023 - mae: 0.6582 - rmse: 0.8928 - smape: 1.2824 - val_ia: 0.3418 - val_loss: 0.7886 - val_mae: 0.6571 - val_rmse: 0.8235 - val_smape: 1.2890

Epoch 84/128

120/120 - 2s - 20ms/step - ia: 0.3890 - loss: 0.8051 - mae: 0.6586 - rmse: 0.8946 - smape: 1.2856 - val_ia: 0.3402 - val_loss: 0.7879 - val_mae: 0.6575 - val_rmse: 0.8231 - val_smape: 1.2915

Epoch 85/128

120/120 - 2s - 19ms/step - ia: 0.3900 - loss: 0.8007 - mae: 0.6576 - rmse: 0.8919 - smape: 1.2833 - val_ia: 0.3415 - val_loss: 0.7892 - val_mae: 0.6577 - val_rmse: 0.8240 - val_smape: 1.2901

Epoch 86/128

120/120 - 2s - 18ms/step - ia: 0.3909 - loss: 0.8022 - mae: 0.6590 - rmse: 0.8931 - smape: 1.2844 - val_ia: 0.3405 - val_loss: 0.7872 - val_mae: 0.6576 - val_rmse: 0.8232 - val_smape: 1.2943

Epoch 87/128

120/120 - 2s - 18ms/step - ia: 0.3895 - loss: 0.8012 - mae: 0.6580 - rmse: 0.8924 - smape: 1.2836 - val_ia: 0.3428 - val_loss: 0.7903 - val_mae: 0.6581 - val_rmse: 0.8248 - val_smape: 1.2883

Epoch 88/128

120/120 - 3s - 24ms/step - ia: 0.3908 - loss: 0.8018 - mae: 0.6583 - rmse: 0.8933 - smape: 1.2808 - val_ia: 0.3418 - val_loss: 0.7860 - val_mae: 0.6561 - val_rmse: 0.8222 - val_smape: 1.2898

Epoch 89/128

120/120 - 2s - 19ms/step - ia: 0.3905 - loss: 0.8033 - mae: 0.6579 - rmse: 0.8940 - smape: 1.2801 - val_ia: 0.3413 - val_loss: 0.7862 - val_mae: 0.6564 - val_rmse: 0.8222 - val_smape: 1.2900

Epoch 90/128

120/120 - 2s - 19ms/step - ia: 0.3894 - loss: 0.8035 - mae: 0.6578 - rmse: 0.8939 - smape: 1.2838 - val_ia: 0.3427 - val_loss: 0.7885 - val_mae: 0.6576 - val_rmse: 0.8239 - val_smape: 1.2897

Epoch 91/128

120/120 - 3s - 23ms/step - ia: 0.3932 - loss: 0.7995 - mae: 0.6568 - rmse: 0.8918 - smape: 1.2781 - val_ia: 0.3430 - val_loss: 0.7874 - val_mae: 0.6567 - val_rmse: 0.8231 - val_smape: 1.2878

Epoch 92/128

120/120 - 2s - 20ms/step - ia: 0.3915 - loss: 0.7999 - mae: 0.6574 - rmse: 0.8918 - smape: 1.2788 - val_ia: 0.3437 - val_loss: 0.7883 - val_mae: 0.6567 - val_rmse: 0.8234 - val_smape: 1.2858

Epoch 93/128

120/120 - 2s - 19ms/step - ia: 0.3932 - loss: 0.7986 - mae: 0.6576 - rmse: 0.8913 - smape: 1.2772 - val_ia: 0.3435 - val_loss: 0.7872 - val_mae: 0.6563 - val_rmse: 0.8229 - val_smape: 1.2874

Epoch 94/128

120/120 - 3s - 21ms/step - ia: 0.3940 - loss: 0.8005 - mae: 0.6564 - rmse: 0.8916 - smape: 1.2761 - val_ia: 0.3445 - val_loss: 0.7874 - val_mae: 0.6560 - val_rmse: 0.8228 - val_smape: 1.2862

Epoch 95/128

120/120 - 3s - 21ms/step - ia: 0.3952 - loss: 0.7951 - mae: 0.6555 - rmse: 0.8893 - smape: 1.2760 - val_ia: 0.3449 - val_loss: 0.7887 - val_mae: 0.6565 - val_rmse: 0.8237 - val_smape: 1.2860

Epoch 96/128

120/120 - 2s - 20ms/step - ia: 0.3963 - loss: 0.7963 - mae: 0.6554 - rmse: 0.8888 - smape: 1.2732 - val_ia: 0.3448 - val_loss: 0.7880 - val_mae: 0.6564 - val_rmse: 0.8233 - val_smape: 1.2854

Epoch 97/128

120/120 - 3s - 21ms/step - ia: 0.3935 - loss: 0.7968 - mae: 0.6557 - rmse: 0.8893 - smape: 1.2792 - val_ia: 0.3449 - val_loss: 0.7900 - val_mae: 0.6577 - val_rmse: 0.8247 - val_smape: 1.2859

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 14s - 118ms/step - ia: 0.0983 - loss: 1.0846 - mae: 0.7881 - rmse: 1.0390 - smape: 1.7278 - val_ia: 0.2353 - val_loss: 1.0127 - val_mae: 0.7510 - val_rmse: 0.9178 - val_smape: 1.7324

Epoch 2/32

120/120 - 5s - 39ms/step - ia: 0.0948 - loss: 1.0507 - mae: 0.7752 - rmse: 1.0222 - smape: 1.7421 - val_ia: 0.2386 - val_loss: 0.9885 - val_mae: 0.7434 - val_rmse: 0.9077 - val_smape: 1.7491

Epoch 3/32

120/120 - 5s - 41ms/step - ia: 0.1009 - loss: 1.0234 - mae: 0.7638 - rmse: 1.0084 - smape: 1.7341 - val_ia: 0.2415 - val_loss: 0.9661 - val_mae: 0.7363 - val_rmse: 0.8982 - val_smape: 1.7394

Epoch 4/32

120/120 - 5s - 39ms/step - ia: 0.1118 - loss: 1.0004 - mae: 0.7550 - rmse: 0.9977 - smape: 1.7186 - val_ia: 0.2442 - val_loss: 0.9454 - val_mae: 0.7294 - val_rmse: 0.8894 - val_smape: 1.7102

Epoch 5/32

120/120 - 5s - 38ms/step - ia: 0.1323 - loss: 0.9775 - mae: 0.7456 - rmse: 0.9859 - smape: 1.6833 - val_ia: 0.2481 - val_loss: 0.9270 - val_mae: 0.7231 - val_rmse: 0.8815 - val_smape: 1.6758

Epoch 6/32

120/120 - 5s - 39ms/step - ia: 0.1543 - loss: 0.9585 - mae: 0.7383 - rmse: 0.9758 - smape: 1.6492 - val_ia: 0.2528 - val_loss: 0.9101 - val_mae: 0.7171 - val_rmse: 0.8743 - val_smape: 1.6367

Epoch 7/32

120/120 - 6s - 46ms/step - ia: 0.1766 - loss: 0.9423 - mae: 0.7313 - rmse: 0.9679 - smape: 1.6101 - val_ia: 0.2578 - val_loss: 0.8964 - val_mae: 0.7118 - val_rmse: 0.8683 - val_smape: 1.6007

Epoch 8/32

120/120 - 5s - 40ms/step - ia: 0.1958 - loss: 0.9278 - mae: 0.7258 - rmse: 0.9605 - smape: 1.5781 - val_ia: 0.2624 - val_loss: 0.8833 - val_mae: 0.7066 - val_rmse: 0.8626 - val_smape: 1.5622

Epoch 9/32

120/120 - 5s - 42ms/step - ia: 0.2155 - loss: 0.9182 - mae: 0.7214 - rmse: 0.9560 - smape: 1.5450 - val_ia: 0.2675 - val_loss: 0.8730 - val_mae: 0.7021 - val_rmse: 0.8581 - val_smape: 1.5282

Epoch 10/32

120/120 - 4s - 37ms/step - ia: 0.2349 - loss: 0.9075 - mae: 0.7161 - rmse: 0.9499 - smape: 1.5157 - val_ia: 0.2721 - val_loss: 0.8643 - val_mae: 0.6983 - val_rmse: 0.8543 - val_smape: 1.4997

Epoch 11/32

120/120 - 5s - 44ms/step - ia: 0.2493 - loss: 0.9028 - mae: 0.7137 - rmse: 0.9477 - smape: 1.4906 - val_ia: 0.2760 - val_loss: 0.8564 - val_mae: 0.6945 - val_rmse: 0.8507 - val_smape: 1.4723

Epoch 12/32

120/120 - 4s - 37ms/step - ia: 0.2639 - loss: 0.8937 - mae: 0.7097 - rmse: 0.9427 - smape: 1.4693 - val_ia: 0.2796 - val_loss: 0.8505 - val_mae: 0.6915 - val_rmse: 0.8480 - val_smape: 1.4512

Epoch 13/32

120/120 - 5s - 46ms/step - ia: 0.2738 - loss: 0.8906 - mae: 0.7076 - rmse: 0.9413 - smape: 1.4517 - val_ia: 0.2829 - val_loss: 0.8452 - val_mae: 0.6887 - val_rmse: 0.8455 - val_smape: 1.4321

Epoch 14/32

120/120 - 5s - 38ms/step - ia: 0.2829 - loss: 0.8855 - mae: 0.7046 - rmse: 0.9384 - smape: 1.4389 - val_ia: 0.2855 - val_loss: 0.8410 - val_mae: 0.6865 - val_rmse: 0.8436 - val_smape: 1.4192

Epoch 15/32

120/120 - 5s - 38ms/step - ia: 0.2910 - loss: 0.8808 - mae: 0.7028 - rmse: 0.9359 - smape: 1.4265 - val_ia: 0.2876 - val_loss: 0.8371 - val_mae: 0.6844 - val_rmse: 0.8417 - val_smape: 1.4080

Epoch 16/32

120/120 - 4s - 37ms/step - ia: 0.2984 - loss: 0.8782 - mae: 0.7009 - rmse: 0.9345 - smape: 1.4157 - val_ia: 0.2896 - val_loss: 0.8333 - val_mae: 0.6823 - val_rmse: 0.8399 - val_smape: 1.3964

Epoch 17/32

120/120 - 4s - 37ms/step - ia: 0.3045 - loss: 0.8743 - mae: 0.6991 - rmse: 0.9326 - smape: 1.4058 - val_ia: 0.2911 - val_loss: 0.8303 - val_mae: 0.6807 - val_rmse: 0.8384 - val_smape: 1.3886

Epoch 18/32

120/120 - 4s - 37ms/step - ia: 0.3092 - loss: 0.8712 - mae: 0.6973 - rmse: 0.9306 - smape: 1.3989 - val_ia: 0.2929 - val_loss: 0.8273 - val_mae: 0.6791 - val_rmse: 0.8370 - val_smape: 1.3810

Epoch 19/32

120/120 - 4s - 37ms/step - ia: 0.3109 - loss: 0.8696 - mae: 0.6966 - rmse: 0.9308 - smape: 1.3961 - val_ia: 0.2941 - val_loss: 0.8245 - val_mae: 0.6776 - val_rmse: 0.8357 - val_smape: 1.3748

Epoch 20/32

120/120 - 4s - 33ms/step - ia: 0.3149 - loss: 0.8658 - mae: 0.6947 - rmse: 0.9281 - smape: 1.3891 - val_ia: 0.2952 - val_loss: 0.8216 - val_mae: 0.6760 - val_rmse: 0.8342 - val_smape: 1.3677

Epoch 21/32

120/120 - 3s - 27ms/step - ia: 0.3192 - loss: 0.8635 - mae: 0.6934 - rmse: 0.9261 - smape: 1.3838 - val_ia: 0.2965 - val_loss: 0.8193 - val_mae: 0.6750 - val_rmse: 0.8332 - val_smape: 1.3638

Epoch 22/32

120/120 - 4s - 31ms/step - ia: 0.3211 - loss: 0.8630 - mae: 0.6927 - rmse: 0.9264 - smape: 1.3811 - val_ia: 0.2973 - val_loss: 0.8169 - val_mae: 0.6737 - val_rmse: 0.8320 - val_smape: 1.3597

Epoch 23/32

120/120 - 6s - 48ms/step - ia: 0.3244 - loss: 0.8604 - mae: 0.6912 - rmse: 0.9248 - smape: 1.3764 - val_ia: 0.2984 - val_loss: 0.8146 - val_mae: 0.6727 - val_rmse: 0.8310 - val_smape: 1.3552

Epoch 24/32

120/120 - 5s - 38ms/step - ia: 0.3259 - loss: 0.8592 - mae: 0.6908 - rmse: 0.9241 - smape: 1.3738 - val_ia: 0.2993 - val_loss: 0.8125 - val_mae: 0.6716 - val_rmse: 0.8300 - val_smape: 1.3526

Epoch 25/32

120/120 - 5s - 43ms/step - ia: 0.3279 - loss: 0.8577 - mae: 0.6903 - rmse: 0.9233 - smape: 1.3724 - val_ia: 0.3003 - val_loss: 0.8106 - val_mae: 0.6707 - val_rmse: 0.8292 - val_smape: 1.3499

Epoch 26/32

120/120 - 5s - 38ms/step - ia: 0.3293 - loss: 0.8547 - mae: 0.6885 - rmse: 0.9215 - smape: 1.3702 - val_ia: 0.3010 - val_loss: 0.8086 - val_mae: 0.6698 - val_rmse: 0.8282 - val_smape: 1.3477

Epoch 27/32

120/120 - 5s - 38ms/step - ia: 0.3319 - loss: 0.8532 - mae: 0.6875 - rmse: 0.9212 - smape: 1.3653 - val_ia: 0.3019 - val_loss: 0.8068 - val_mae: 0.6689 - val_rmse: 0.8274 - val_smape: 1.3448

Epoch 28/32

120/120 - 4s - 37ms/step - ia: 0.3351 - loss: 0.8503 - mae: 0.6862 - rmse: 0.9190 - smape: 1.3607 - val_ia: 0.3025 - val_loss: 0.8048 - val_mae: 0.6682 - val_rmse: 0.8265 - val_smape: 1.3427

Epoch 29/32

120/120 - 4s - 34ms/step - ia: 0.3364 - loss: 0.8493 - mae: 0.6856 - rmse: 0.9188 - smape: 1.3587 - val_ia: 0.3032 - val_loss: 0.8033 - val_mae: 0.6675 - val_rmse: 0.8258 - val_smape: 1.3416

Epoch 30/32

120/120 - 4s - 37ms/step - ia: 0.3369 - loss: 0.8489 - mae: 0.6856 - rmse: 0.9189 - smape: 1.3597 - val_ia: 0.3039 - val_loss: 0.8014 - val_mae: 0.6667 - val_rmse: 0.8250 - val_smape: 1.3391

Epoch 31/32

120/120 - 4s - 37ms/step - ia: 0.3387 - loss: 0.8477 - mae: 0.6845 - rmse: 0.9183 - smape: 1.3554 - val_ia: 0.3049 - val_loss: 0.8003 - val_mae: 0.6664 - val_rmse: 0.8246 - val_smape: 1.3387

Epoch 32/32

120/120 - 5s - 43ms/step - ia: 0.3393 - loss: 0.8464 - mae: 0.6841 - rmse: 0.9173 - smape: 1.3537 - val_ia: 0.3055 - val_loss: 0.7987 - val_mae: 0.6657 - val_rmse: 0.8239 - val_smape: 1.3364

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:52 832ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

 80%|████████  | 40/50 [11:26:31<34:35, 207.59s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 16s - 130ms/step - ia: 0.2806 - loss: 0.8877 - mae: 0.7005 - rmse: 0.9388 - smape: 1.4581 - val_ia: 0.3071 - val_loss: 0.7860 - val_mae: 0.6603 - val_rmse: 0.8179 - val_smape: 1.3176

Epoch 2/128

120/120 - 4s - 32ms/step - ia: 0.3585 - loss: 0.8318 - mae: 0.6729 - rmse: 0.9093 - smape: 1.3279 - val_ia: 0.3430 - val_loss: 0.7797 - val_mae: 0.6529 - val_rmse: 0.8174 - val_smape: 1.2387

Epoch 3/128

120/120 - 6s - 47ms/step - ia: 0.3871 - loss: 0.8093 - mae: 0.6608 - rmse: 0.8975 - smape: 1.2779 - val_ia: 0.3346 - val_loss: 0.7568 - val_mae: 0.6429 - val_rmse: 0.8018 - val_smape: 1.2518

Epoch 4/128

120/120 - 4s - 32ms/step - ia: 0.3933 - loss: 0.7968 - mae: 0.6565 - rmse: 0.8897 - smape: 1.2725 - val_ia: 0.3516 - val_loss: 0.7662 - val_mae: 0.6440 - val_rmse: 0.8094 - val_smape: 1.2345

Epoch 5/128

120/120 - 5s - 42ms/step - ia: 0.4050 - loss: 0.7821 - mae: 0.6489 - rmse: 0.8816 - smape: 1.2577 - val_ia: 0.3702 - val_loss: 0.8013 - val_mae: 0.6574 - val_rmse: 0.8329 - val_smape: 1.2349

Epoch 6/128

120/120 - 5s - 43ms/step - ia: 0.4140 - loss: 0.7753 - mae: 0.6448 - rmse: 0.8786 - smape: 1.2417 - val_ia: 0.3460 - val_loss: 0.8024 - val_mae: 0.6663 - val_rmse: 0.8324 - val_smape: 1.3172

Epoch 7/128

120/120 - 4s - 30ms/step - ia: 0.4184 - loss: 0.7631 - mae: 0.6412 - rmse: 0.8717 - smape: 1.2397 - val_ia: 0.3730 - val_loss: 0.8207 - val_mae: 0.6582 - val_rmse: 0.8357 - val_smape: 1.2599

Epoch 8/128

120/120 - 4s - 32ms/step - ia: 0.4220 - loss: 0.7598 - mae: 0.6387 - rmse: 0.8691 - smape: 1.2373 - val_ia: 0.3449 - val_loss: 0.7782 - val_mae: 0.6509 - val_rmse: 0.8140 - val_smape: 1.2996

Epoch 9/128

120/120 - 4s - 31ms/step - ia: 0.4272 - loss: 0.7496 - mae: 0.6364 - rmse: 0.8637 - smape: 1.2297 - val_ia: 0.3451 - val_loss: 0.7999 - val_mae: 0.6570 - val_rmse: 0.8256 - val_smape: 1.3078

Epoch 10/128

120/120 - 4s - 31ms/step - ia: 0.4317 - loss: 0.7385 - mae: 0.6321 - rmse: 0.8566 - smape: 1.2330 - val_ia: 0.3594 - val_loss: 0.8184 - val_mae: 0.6580 - val_rmse: 0.8353 - val_smape: 1.2853

Epoch 11/128

120/120 - 5s - 45ms/step - ia: 0.4365 - loss: 0.7336 - mae: 0.6292 - rmse: 0.8545 - smape: 1.2232 - val_ia: 0.3512 - val_loss: 0.8248 - val_mae: 0.6647 - val_rmse: 0.8390 - val_smape: 1.3320

Epoch 12/128

120/120 - 4s - 32ms/step - ia: 0.4388 - loss: 0.7233 - mae: 0.6257 - rmse: 0.8476 - smape: 1.2262 - val_ia: 0.3545 - val_loss: 0.8248 - val_mae: 0.6608 - val_rmse: 0.8356 - val_smape: 1.3349

Epoch 13/128

120/120 - 4s - 33ms/step - ia: 0.4444 - loss: 0.7166 - mae: 0.6213 - rmse: 0.8447 - smape: 1.2169 - val_ia: 0.3482 - val_loss: 0.9165 - val_mae: 0.6747 - val_rmse: 0.8656 - val_smape: 1.3199

Epoch 14/128

120/120 - 5s - 42ms/step - ia: 0.4421 - loss: 0.7149 - mae: 0.6219 - rmse: 0.8433 - smape: 1.2267 - val_ia: 0.3542 - val_loss: 0.8605 - val_mae: 0.6768 - val_rmse: 0.8518 - val_smape: 1.3115

Epoch 15/128

120/120 - 4s - 30ms/step - ia: 0.4513 - loss: 0.7050 - mae: 0.6173 - rmse: 0.8372 - smape: 1.2159 - val_ia: 0.3403 - val_loss: 0.8528 - val_mae: 0.6701 - val_rmse: 0.8465 - val_smape: 1.3527

Epoch 16/128

120/120 - 4s - 32ms/step - ia: 0.4535 - loss: 0.6960 - mae: 0.6134 - rmse: 0.8323 - smape: 1.2128 - val_ia: 0.3489 - val_loss: 0.8801 - val_mae: 0.6911 - val_rmse: 0.8675 - val_smape: 1.3560

Epoch 17/128

120/120 - 4s - 32ms/step - ia: 0.4586 - loss: 0.6884 - mae: 0.6115 - rmse: 0.8274 - smape: 1.2079 - val_ia: 0.3611 - val_loss: 0.8553 - val_mae: 0.6650 - val_rmse: 0.8425 - val_smape: 1.2842

Epoch 18/128

120/120 - 4s - 32ms/step - ia: 0.4602 - loss: 0.6839 - mae: 0.6094 - rmse: 0.8253 - smape: 1.2090 - val_ia: 0.3368 - val_loss: 0.8834 - val_mae: 0.6917 - val_rmse: 0.8664 - val_smape: 1.3767

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:41 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 82%|████████▏ | 41/50 [11:28:03<25:56, 172.93s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

479/479 - 13s - 27ms/step - ia: 0.1617 - loss: 1.0270 - mae: 0.7720 - rmse: 1.0024 - smape: 1.6612 - val_ia: 0.2440 - val_loss: 0.9176 - val_mae: 0.7164 - val_rmse: 0.8301 - val_smape: 1.6426

Epoch 2/64

479/479 - 5s - 10ms/step - ia: 0.2072 - loss: 0.9493 - mae: 0.7310 - rmse: 0.9633 - smape: 1.5845 - val_ia: 0.2553 - val_loss: 0.8589 - val_mae: 0.6874 - val_rmse: 0.8038 - val_smape: 1.4705

Epoch 3/64

479/479 - 5s - 11ms/step - ia: 0.2824 - loss: 0.9039 - mae: 0.7048 - rmse: 0.9408 - smape: 1.4411 - val_ia: 0.2625 - val_loss: 0.8191 - val_mae: 0.6663 - val_rmse: 0.7858 - val_smape: 1.3452

Epoch 4/64

479/479 - 6s - 12ms/step - ia: 0.3208 - loss: 0.8816 - mae: 0.6933 - rmse: 0.9287 - smape: 1.3778 - val_ia: 0.2644 - val_loss: 0.8054 - val_mae: 0.6632 - val_rmse: 0.7832 - val_smape: 1.3258

Epoch 5/64

479/479 - 4s - 8ms/step - ia: 0.3352 - loss: 0.8699 - mae: 0.6868 - rmse: 0.9230 - smape: 1.3563 - val_ia: 0.2649 - val_loss: 0.7993 - val_mae: 0.6642 - val_rmse: 0.7842 - val_smape: 1.3284

Epoch 6/64

479/479 - 4s - 8ms/step - ia: 0.3429 - loss: 0.8608 - mae: 0.6838 - rmse: 0.9177 - smape: 1.3464 - val_ia: 0.2643 - val_loss: 0.7921 - val_mae: 0.6605 - val_rmse: 0.7803 - val_smape: 1.3231

Epoch 7/64

479/479 - 4s - 8ms/step - ia: 0.3473 - loss: 0.8561 - mae: 0.6815 - rmse: 0.9150 - smape: 1.3405 - val_ia: 0.2646 - val_loss: 0.7867 - val_mae: 0.6588 - val_rmse: 0.7787 - val_smape: 1.3214

Epoch 8/64

479/479 - 5s - 11ms/step - ia: 0.3511 - loss: 0.8486 - mae: 0.6792 - rmse: 0.9099 - smape: 1.3357 - val_ia: 0.2653 - val_loss: 0.7838 - val_mae: 0.6579 - val_rmse: 0.7781 - val_smape: 1.3171

Epoch 9/64

479/479 - 4s - 8ms/step - ia: 0.3545 - loss: 0.8444 - mae: 0.6763 - rmse: 0.9091 - smape: 1.3285 - val_ia: 0.2670 - val_loss: 0.7799 - val_mae: 0.6569 - val_rmse: 0.7778 - val_smape: 1.3057

Epoch 10/64

479/479 - 4s - 8ms/step - ia: 0.3627 - loss: 0.8396 - mae: 0.6747 - rmse: 0.9063 - smape: 1.3180 - val_ia: 0.2663 - val_loss: 0.7771 - val_mae: 0.6557 - val_rmse: 0.7761 - val_smape: 1.3112

Epoch 11/64

479/479 - 5s - 11ms/step - ia: 0.3612 - loss: 0.8365 - mae: 0.6732 - rmse: 0.9049 - smape: 1.3209 - val_ia: 0.2678 - val_loss: 0.7754 - val_mae: 0.6560 - val_rmse: 0.7769 - val_smape: 1.3090

Epoch 12/64

479/479 - 4s - 8ms/step - ia: 0.3634 - loss: 0.8350 - mae: 0.6731 - rmse: 0.9040 - smape: 1.3157 - val_ia: 0.2699 - val_loss: 0.7731 - val_mae: 0.6547 - val_rmse: 0.7766 - val_smape: 1.2980

Epoch 13/64

479/479 - 4s - 8ms/step - ia: 0.3670 - loss: 0.8332 - mae: 0.6713 - rmse: 0.9022 - smape: 1.3115 - val_ia: 0.2699 - val_loss: 0.7695 - val_mae: 0.6521 - val_rmse: 0.7741 - val_smape: 1.2924

Epoch 14/64

479/479 - 4s - 8ms/step - ia: 0.3722 - loss: 0.8289 - mae: 0.6686 - rmse: 0.9000 - smape: 1.3031 - val_ia: 0.2702 - val_loss: 0.7686 - val_mae: 0.6514 - val_rmse: 0.7734 - val_smape: 1.2958

Epoch 15/64

479/479 - 4s - 8ms/step - ia: 0.3721 - loss: 0.8238 - mae: 0.6668 - rmse: 0.8978 - smape: 1.3031 - val_ia: 0.2724 - val_loss: 0.7698 - val_mae: 0.6531 - val_rmse: 0.7762 - val_smape: 1.2904

Epoch 16/64

479/479 - 4s - 8ms/step - ia: 0.3752 - loss: 0.8261 - mae: 0.6669 - rmse: 0.8986 - smape: 1.2963 - val_ia: 0.2723 - val_loss: 0.7661 - val_mae: 0.6506 - val_rmse: 0.7737 - val_smape: 1.2858

Epoch 17/64

479/479 - 5s - 11ms/step - ia: 0.3764 - loss: 0.8218 - mae: 0.6662 - rmse: 0.8963 - smape: 1.2974 - val_ia: 0.2725 - val_loss: 0.7630 - val_mae: 0.6486 - val_rmse: 0.7716 - val_smape: 1.2857

Epoch 18/64

479/479 - 4s - 8ms/step - ia: 0.3767 - loss: 0.8210 - mae: 0.6652 - rmse: 0.8970 - smape: 1.2964 - val_ia: 0.2749 - val_loss: 0.7664 - val_mae: 0.6519 - val_rmse: 0.7758 - val_smape: 1.2863

Epoch 19/64

479/479 - 4s - 8ms/step - ia: 0.3798 - loss: 0.8198 - mae: 0.6649 - rmse: 0.8950 - smape: 1.2942 - val_ia: 0.2757 - val_loss: 0.7665 - val_mae: 0.6512 - val_rmse: 0.7757 - val_smape: 1.2786

Epoch 20/64

479/479 - 5s - 10ms/step - ia: 0.3827 - loss: 0.8169 - mae: 0.6625 - rmse: 0.8939 - smape: 1.2870 - val_ia: 0.2755 - val_loss: 0.7634 - val_mae: 0.6487 - val_rmse: 0.7732 - val_smape: 1.2755

Epoch 21/64

479/479 - 4s - 8ms/step - ia: 0.3814 - loss: 0.8179 - mae: 0.6637 - rmse: 0.8945 - smape: 1.2892 - val_ia: 0.2760 - val_loss: 0.7616 - val_mae: 0.6483 - val_rmse: 0.7726 - val_smape: 1.2781

Epoch 22/64

479/479 - 4s - 8ms/step - ia: 0.3825 - loss: 0.8168 - mae: 0.6627 - rmse: 0.8930 - smape: 1.2872 - val_ia: 0.2772 - val_loss: 0.7624 - val_mae: 0.6492 - val_rmse: 0.7738 - val_smape: 1.2802

Epoch 23/64

479/479 - 4s - 8ms/step - ia: 0.3850 - loss: 0.8129 - mae: 0.6598 - rmse: 0.8909 - smape: 1.2816 - val_ia: 0.2797 - val_loss: 0.7665 - val_mae: 0.6512 - val_rmse: 0.7773 - val_smape: 1.2726

Epoch 24/64

479/479 - 4s - 8ms/step - ia: 0.3899 - loss: 0.8087 - mae: 0.6599 - rmse: 0.8903 - smape: 1.2802 - val_ia: 0.2785 - val_loss: 0.7619 - val_mae: 0.6491 - val_rmse: 0.7740 - val_smape: 1.2810

Epoch 25/64

479/479 - 5s - 11ms/step - ia: 0.3870 - loss: 0.8107 - mae: 0.6598 - rmse: 0.8907 - smape: 1.2822 - val_ia: 0.2792 - val_loss: 0.7631 - val_mae: 0.6485 - val_rmse: 0.7743 - val_smape: 1.2688

Epoch 26/64

479/479 - 4s - 8ms/step - ia: 0.3891 - loss: 0.8077 - mae: 0.6586 - rmse: 0.8886 - smape: 1.2789 - val_ia: 0.2800 - val_loss: 0.7638 - val_mae: 0.6482 - val_rmse: 0.7747 - val_smape: 1.2642

Epoch 27/64

479/479 - 5s - 11ms/step - ia: 0.3920 - loss: 0.8075 - mae: 0.6590 - rmse: 0.8885 - smape: 1.2745 - val_ia: 0.2788 - val_loss: 0.7591 - val_mae: 0.6462 - val_rmse: 0.7715 - val_smape: 1.2718

Epoch 28/64

479/479 - 4s - 8ms/step - ia: 0.3908 - loss: 0.8057 - mae: 0.6577 - rmse: 0.8879 - smape: 1.2776 - val_ia: 0.2814 - val_loss: 0.7650 - val_mae: 0.6499 - val_rmse: 0.7765 - val_smape: 1.2702

Epoch 29/64

479/479 - 4s - 8ms/step - ia: 0.3959 - loss: 0.8015 - mae: 0.6563 - rmse: 0.8859 - smape: 1.2690 - val_ia: 0.2805 - val_loss: 0.7614 - val_mae: 0.6469 - val_rmse: 0.7732 - val_smape: 1.2645

Epoch 30/64

479/479 - 4s - 8ms/step - ia: 0.3954 - loss: 0.7990 - mae: 0.6559 - rmse: 0.8839 - smape: 1.2689 - val_ia: 0.2820 - val_loss: 0.7640 - val_mae: 0.6486 - val_rmse: 0.7754 - val_smape: 1.2669

Epoch 31/64

479/479 - 5s - 11ms/step - ia: 0.3948 - loss: 0.8039 - mae: 0.6561 - rmse: 0.8867 - smape: 1.2714 - val_ia: 0.2817 - val_loss: 0.7630 - val_mae: 0.6475 - val_rmse: 0.7742 - val_smape: 1.2657

Epoch 32/64

479/479 - 4s - 8ms/step - ia: 0.3958 - loss: 0.8011 - mae: 0.6555 - rmse: 0.8854 - smape: 1.2700 - val_ia: 0.2819 - val_loss: 0.7625 - val_mae: 0.6481 - val_rmse: 0.7744 - val_smape: 1.2728

Epoch 33/64

479/479 - 4s - 8ms/step - ia: 0.3977 - loss: 0.8014 - mae: 0.6550 - rmse: 0.8852 - smape: 1.2669 - val_ia: 0.2819 - val_loss: 0.7604 - val_mae: 0.6462 - val_rmse: 0.7726 - val_smape: 1.2649

Epoch 34/64

479/479 - 6s - 12ms/step - ia: 0.3979 - loss: 0.7955 - mae: 0.6545 - rmse: 0.8825 - smape: 1.2689 - val_ia: 0.2842 - val_loss: 0.7653 - val_mae: 0.6488 - val_rmse: 0.7764 - val_smape: 1.2643

Epoch 35/64

479/479 - 4s - 8ms/step - ia: 0.3996 - loss: 0.7965 - mae: 0.6542 - rmse: 0.8833 - smape: 1.2649 - val_ia: 0.2819 - val_loss: 0.7586 - val_mae: 0.6447 - val_rmse: 0.7709 - val_smape: 1.2643

Epoch 36/64

479/479 - 5s - 11ms/step - ia: 0.3995 - loss: 0.7929 - mae: 0.6531 - rmse: 0.8810 - smape: 1.2651 - val_ia: 0.2837 - val_loss: 0.7627 - val_mae: 0.6467 - val_rmse: 0.7741 - val_smape: 1.2580

Epoch 37/64

479/479 - 5s - 11ms/step - ia: 0.3989 - loss: 0.7990 - mae: 0.6543 - rmse: 0.8835 - smape: 1.2657 - val_ia: 0.2838 - val_loss: 0.7621 - val_mae: 0.6463 - val_rmse: 0.7736 - val_smape: 1.2574

Epoch 38/64

479/479 - 5s - 11ms/step - ia: 0.3996 - loss: 0.7980 - mae: 0.6535 - rmse: 0.8837 - smape: 1.2631 - val_ia: 0.2843 - val_loss: 0.7629 - val_mae: 0.6486 - val_rmse: 0.7754 - val_smape: 1.2678

Epoch 39/64

479/479 - 5s - 11ms/step - ia: 0.3993 - loss: 0.7956 - mae: 0.6539 - rmse: 0.8814 - smape: 1.2658 - val_ia: 0.2838 - val_loss: 0.7611 - val_mae: 0.6468 - val_rmse: 0.7734 - val_smape: 1.2668

Epoch 40/64

479/479 - 4s - 8ms/step - ia: 0.4001 - loss: 0.7953 - mae: 0.6527 - rmse: 0.8819 - smape: 1.2624 - val_ia: 0.2853 - val_loss: 0.7630 - val_mae: 0.6475 - val_rmse: 0.7751 - val_smape: 1.2607

Epoch 41/64

479/479 - 4s - 8ms/step - ia: 0.4027 - loss: 0.7901 - mae: 0.6528 - rmse: 0.8796 - smape: 1.2615 - val_ia: 0.2828 - val_loss: 0.7589 - val_mae: 0.6439 - val_rmse: 0.7705 - val_smape: 1.2571

Epoch 42/64

479/479 - 4s - 8ms/step - ia: 0.4001 - loss: 0.7925 - mae: 0.6515 - rmse: 0.8800 - smape: 1.2612 - val_ia: 0.2857 - val_loss: 0.7663 - val_mae: 0.6480 - val_rmse: 0.7762 - val_smape: 1.2571

Epoch 43/64

479/479 - 5s - 11ms/step - ia: 0.4021 - loss: 0.7937 - mae: 0.6521 - rmse: 0.8809 - smape: 1.2618 - val_ia: 0.2842 - val_loss: 0.7621 - val_mae: 0.6453 - val_rmse: 0.7728 - val_smape: 1.2530

Epoch 44/64

479/479 - 6s - 12ms/step - ia: 0.4015 - loss: 0.7916 - mae: 0.6520 - rmse: 0.8793 - smape: 1.2614 - val_ia: 0.2850 - val_loss: 0.7640 - val_mae: 0.6468 - val_rmse: 0.7746 - val_smape: 1.2566

Epoch 45/64

479/479 - 4s - 8ms/step - ia: 0.4010 - loss: 0.7940 - mae: 0.6520 - rmse: 0.8803 - smape: 1.2618 - val_ia: 0.2854 - val_loss: 0.7644 - val_mae: 0.6464 - val_rmse: 0.7744 - val_smape: 1.2520

Epoch 46/64

479/479 - 4s - 9ms/step - ia: 0.4066 - loss: 0.7881 - mae: 0.6511 - rmse: 0.8784 - smape: 1.2563 - val_ia: 0.2843 - val_loss: 0.7602 - val_mae: 0.6451 - val_rmse: 0.7720 - val_smape: 1.2586

Epoch 47/64

479/479 - 5s - 11ms/step - ia: 0.4035 - loss: 0.7891 - mae: 0.6513 - rmse: 0.8785 - smape: 1.2603 - val_ia: 0.2845 - val_loss: 0.7607 - val_mae: 0.6448 - val_rmse: 0.7720 - val_smape: 1.2567

Epoch 48/64

479/479 - 5s - 11ms/step - ia: 0.4042 - loss: 0.7898 - mae: 0.6507 - rmse: 0.8790 - smape: 1.2606 - val_ia: 0.2854 - val_loss: 0.7668 - val_mae: 0.6484 - val_rmse: 0.7764 - val_smape: 1.2581

Epoch 49/64

479/479 - 5s - 10ms/step - ia: 0.4031 - loss: 0.7928 - mae: 0.6514 - rmse: 0.8803 - smape: 1.2583 - val_ia: 0.2853 - val_loss: 0.7643 - val_mae: 0.6472 - val_rmse: 0.7749 - val_smape: 1.2554

Epoch 50/64

479/479 - 5s - 11ms/step - ia: 0.4041 - loss: 0.7881 - mae: 0.6498 - rmse: 0.8782 - smape: 1.2582 - val_ia: 0.2853 - val_loss: 0.7618 - val_mae: 0.6463 - val_rmse: 0.7736 - val_smape: 1.2607

Epoch 50: early stopping

Restoring model weights from the end of the best epoch: 35.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:54 850ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 84%|████████▍ | 42/50 [11:31:58<25:32, 191.60s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

3830/3830 - 22s - 6ms/step - ia: 0.2667 - loss: 1.1659 - mae: 0.7828 - rmse: 1.0007 - smape: 1.5292 - val_ia: 0.1895 - val_loss: 1.0258 - val_mae: 0.7331 - val_rmse: 0.7718 - val_smape: 1.6529

Epoch 2/8

3830/3830 - 16s - 4ms/step - ia: 0.2690 - loss: 1.1564 - mae: 0.7790 - rmse: 0.9945 - smape: 1.5355 - val_ia: 0.1898 - val_loss: 1.0179 - val_mae: 0.7309 - val_rmse: 0.7696 - val_smape: 1.6560

Epoch 3/8

3830/3830 - 16s - 4ms/step - ia: 0.2622 - loss: 1.1343 - mae: 0.7763 - rmse: 0.9886 - smape: 1.5410 - val_ia: 0.1902 - val_loss: 1.0101 - val_mae: 0.7284 - val_rmse: 0.7671 - val_smape: 1.6568

Epoch 4/8

3830/3830 - 21s - 5ms/step - ia: 0.2638 - loss: 1.1281 - mae: 0.7721 - rmse: 0.9855 - smape: 1.5410 - val_ia: 0.1905 - val_loss: 1.0028 - val_mae: 0.7262 - val_rmse: 0.7648 - val_smape: 1.6575

Epoch 5/8

3830/3830 - 16s - 4ms/step - ia: 0.2665 - loss: 1.1142 - mae: 0.7681 - rmse: 0.9794 - smape: 1.5408 - val_ia: 0.1908 - val_loss: 0.9960 - val_mae: 0.7241 - val_rmse: 0.7627 - val_smape: 1.6582

Epoch 6/8

3830/3830 - 15s - 4ms/step - ia: 0.2687 - loss: 1.1047 - mae: 0.7643 - rmse: 0.9747 - smape: 1.5383 - val_ia: 0.1909 - val_loss: 0.9895 - val_mae: 0.7221 - val_rmse: 0.7607 - val_smape: 1.6582

Epoch 7/8

3830/3830 - 16s - 4ms/step - ia: 0.2671 - loss: 1.0926 - mae: 0.7610 - rmse: 0.9683 - smape: 1.5462 - val_ia: 0.1911 - val_loss: 0.9831 - val_mae: 0.7199 - val_rmse: 0.7585 - val_smape: 1.6569

Epoch 8/8

3830/3830 - 17s - 5ms/step - ia: 0.2672 - loss: 1.0872 - mae: 0.7608 - rmse: 0.9679 - smape: 1.5515 - val_ia: 0.1911 - val_loss: 0.9771 - val_mae: 0.7180 - val_rmse: 0.7566 - val_smape: 1.6560

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:25 633ms/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 86%|████████▌ | 43/50 [11:34:20<20:37, 176.72s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

120/120 - 16s - 132ms/step - ia: 0.3428 - loss: 0.8438 - mae: 0.6811 - rmse: 0.9163 - smape: 1.3594 - val_ia: 0.3253 - val_loss: 0.7748 - val_mae: 0.6555 - val_rmse: 0.8148 - val_smape: 1.3290

Epoch 2/256

120/120 - 5s - 38ms/step - ia: 0.3792 - loss: 0.8098 - mae: 0.6634 - rmse: 0.8974 - smape: 1.3046 - val_ia: 0.3378 - val_loss: 0.7615 - val_mae: 0.6499 - val_rmse: 0.8085 - val_smape: 1.2936

Epoch 3/256

120/120 - 5s - 44ms/step - ia: 0.3970 - loss: 0.7966 - mae: 0.6550 - rmse: 0.8898 - smape: 1.2753 - val_ia: 0.3523 - val_loss: 0.7693 - val_mae: 0.6501 - val_rmse: 0.8128 - val_smape: 1.2808

Epoch 4/256

120/120 - 5s - 45ms/step - ia: 0.4044 - loss: 0.7896 - mae: 0.6518 - rmse: 0.8864 - smape: 1.2657 - val_ia: 0.3520 - val_loss: 0.7588 - val_mae: 0.6478 - val_rmse: 0.8087 - val_smape: 1.2872

Epoch 5/256

120/120 - 4s - 36ms/step - ia: 0.4112 - loss: 0.7824 - mae: 0.6478 - rmse: 0.8817 - smape: 1.2555 - val_ia: 0.3551 - val_loss: 0.7671 - val_mae: 0.6484 - val_rmse: 0.8130 - val_smape: 1.2853

Epoch 6/256

120/120 - 4s - 35ms/step - ia: 0.4135 - loss: 0.7817 - mae: 0.6466 - rmse: 0.8811 - smape: 1.2508 - val_ia: 0.3599 - val_loss: 0.7618 - val_mae: 0.6475 - val_rmse: 0.8115 - val_smape: 1.2742

Epoch 7/256

120/120 - 4s - 37ms/step - ia: 0.4161 - loss: 0.7762 - mae: 0.6445 - rmse: 0.8783 - smape: 1.2484 - val_ia: 0.3739 - val_loss: 0.7547 - val_mae: 0.6378 - val_rmse: 0.8052 - val_smape: 1.2312

Epoch 8/256

120/120 - 4s - 35ms/step - ia: 0.4207 - loss: 0.7719 - mae: 0.6428 - rmse: 0.8760 - smape: 1.2428 - val_ia: 0.3654 - val_loss: 0.7815 - val_mae: 0.6495 - val_rmse: 0.8188 - val_smape: 1.2488

Epoch 9/256

120/120 - 4s - 35ms/step - ia: 0.4233 - loss: 0.7632 - mae: 0.6391 - rmse: 0.8711 - smape: 1.2369 - val_ia: 0.3651 - val_loss: 0.7704 - val_mae: 0.6455 - val_rmse: 0.8128 - val_smape: 1.2499

Epoch 10/256

120/120 - 4s - 35ms/step - ia: 0.4288 - loss: 0.7583 - mae: 0.6369 - rmse: 0.8678 - smape: 1.2330 - val_ia: 0.3641 - val_loss: 0.7743 - val_mae: 0.6501 - val_rmse: 0.8172 - val_smape: 1.2655

Epoch 11/256

120/120 - 5s - 40ms/step - ia: 0.4302 - loss: 0.7547 - mae: 0.6357 - rmse: 0.8668 - smape: 1.2314 - val_ia: 0.3603 - val_loss: 0.7858 - val_mae: 0.6493 - val_rmse: 0.8197 - val_smape: 1.2495

Epoch 12/256

120/120 - 4s - 35ms/step - ia: 0.4300 - loss: 0.7512 - mae: 0.6347 - rmse: 0.8646 - smape: 1.2278 - val_ia: 0.3585 - val_loss: 0.7985 - val_mae: 0.6587 - val_rmse: 0.8298 - val_smape: 1.2686

Epoch 13/256

120/120 - 5s - 43ms/step - ia: 0.4360 - loss: 0.7478 - mae: 0.6327 - rmse: 0.8626 - smape: 1.2223 - val_ia: 0.3689 - val_loss: 0.7681 - val_mae: 0.6497 - val_rmse: 0.8168 - val_smape: 1.2618

Epoch 14/256

120/120 - 4s - 36ms/step - ia: 0.4406 - loss: 0.7399 - mae: 0.6298 - rmse: 0.8577 - smape: 1.2155 - val_ia: 0.3614 - val_loss: 0.8274 - val_mae: 0.6617 - val_rmse: 0.8394 - val_smape: 1.2613

Epoch 15/256

120/120 - 5s - 44ms/step - ia: 0.4431 - loss: 0.7365 - mae: 0.6280 - rmse: 0.8558 - smape: 1.2123 - val_ia: 0.3631 - val_loss: 0.8226 - val_mae: 0.6556 - val_rmse: 0.8335 - val_smape: 1.2433

Epoch 16/256

120/120 - 4s - 35ms/step - ia: 0.4451 - loss: 0.7311 - mae: 0.6257 - rmse: 0.8527 - smape: 1.2105 - val_ia: 0.3573 - val_loss: 0.8507 - val_mae: 0.6649 - val_rmse: 0.8449 - val_smape: 1.2643

Epoch 17/256

120/120 - 4s - 35ms/step - ia: 0.4481 - loss: 0.7232 - mae: 0.6238 - rmse: 0.8486 - smape: 1.2065 - val_ia: 0.3615 - val_loss: 0.8594 - val_mae: 0.6602 - val_rmse: 0.8445 - val_smape: 1.2578

Epoch 18/256

120/120 - 4s - 35ms/step - ia: 0.4495 - loss: 0.7177 - mae: 0.6215 - rmse: 0.8447 - smape: 1.2069 - val_ia: 0.3618 - val_loss: 0.8289 - val_mae: 0.6571 - val_rmse: 0.8329 - val_smape: 1.2538

Epoch 19/256

120/120 - 5s - 43ms/step - ia: 0.4564 - loss: 0.7129 - mae: 0.6192 - rmse: 0.8421 - smape: 1.1958 - val_ia: 0.3572 - val_loss: 0.9056 - val_mae: 0.6703 - val_rmse: 0.8600 - val_smape: 1.2713

Epoch 20/256

120/120 - 5s - 45ms/step - ia: 0.4556 - loss: 0.7100 - mae: 0.6177 - rmse: 0.8402 - smape: 1.1979 - val_ia: 0.3666 - val_loss: 0.8872 - val_mae: 0.6714 - val_rmse: 0.8594 - val_smape: 1.2652

Epoch 21/256

120/120 - 4s - 36ms/step - ia: 0.4573 - loss: 0.7080 - mae: 0.6166 - rmse: 0.8392 - smape: 1.1952 - val_ia: 0.3639 - val_loss: 0.8637 - val_mae: 0.6612 - val_rmse: 0.8451 - val_smape: 1.2499

Epoch 22/256

120/120 - 7s - 54ms/step - ia: 0.4618 - loss: 0.6998 - mae: 0.6140 - rmse: 0.8345 - smape: 1.1912 - val_ia: 0.3661 - val_loss: 0.8781 - val_mae: 0.6627 - val_rmse: 0.8516 - val_smape: 1.2537

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:31 1s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 88%|████████▊ | 44/50 [11:36:20<15:56, 159.48s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 34s - 142ms/step - ia: 0.2945 - loss: 0.8834 - mae: 0.6997 - rmse: 0.9336 - smape: 1.4335 - val_ia: 0.3002 - val_loss: 0.8150 - val_mae: 0.6804 - val_rmse: 0.8239 - val_smape: 1.3611

Epoch 2/128

240/240 - 5s - 21ms/step - ia: 0.3545 - loss: 0.8349 - mae: 0.6772 - rmse: 0.9103 - smape: 1.3391 - val_ia: 0.3173 - val_loss: 0.8323 - val_mae: 0.6784 - val_rmse: 0.8314 - val_smape: 1.3214

Epoch 3/128

240/240 - 5s - 21ms/step - ia: 0.3712 - loss: 0.8157 - mae: 0.6682 - rmse: 0.8980 - smape: 1.3162 - val_ia: 0.3200 - val_loss: 0.8133 - val_mae: 0.6675 - val_rmse: 0.8202 - val_smape: 1.3174

Epoch 4/128

240/240 - 5s - 22ms/step - ia: 0.3846 - loss: 0.8043 - mae: 0.6616 - rmse: 0.8919 - smape: 1.2955 - val_ia: 0.3246 - val_loss: 0.8006 - val_mae: 0.6593 - val_rmse: 0.8089 - val_smape: 1.3016

Epoch 5/128

240/240 - 5s - 21ms/step - ia: 0.3958 - loss: 0.7895 - mae: 0.6543 - rmse: 0.8841 - smape: 1.2761 - val_ia: 0.3360 - val_loss: 0.8329 - val_mae: 0.6524 - val_rmse: 0.8150 - val_smape: 1.2354

Epoch 6/128

240/240 - 5s - 22ms/step - ia: 0.4026 - loss: 0.7819 - mae: 0.6506 - rmse: 0.8786 - smape: 1.2690 - val_ia: 0.3360 - val_loss: 0.8087 - val_mae: 0.6513 - val_rmse: 0.8072 - val_smape: 1.2564

Epoch 7/128

240/240 - 6s - 23ms/step - ia: 0.4082 - loss: 0.7741 - mae: 0.6459 - rmse: 0.8748 - smape: 1.2608 - val_ia: 0.3371 - val_loss: 0.8666 - val_mae: 0.6670 - val_rmse: 0.8327 - val_smape: 1.2598

Epoch 8/128

240/240 - 5s - 21ms/step - ia: 0.4125 - loss: 0.7708 - mae: 0.6448 - rmse: 0.8725 - smape: 1.2525 - val_ia: 0.3306 - val_loss: 0.8280 - val_mae: 0.6552 - val_rmse: 0.8120 - val_smape: 1.2663

Epoch 9/128

240/240 - 5s - 21ms/step - ia: 0.4169 - loss: 0.7609 - mae: 0.6396 - rmse: 0.8664 - smape: 1.2474 - val_ia: 0.3422 - val_loss: 0.8483 - val_mae: 0.6575 - val_rmse: 0.8226 - val_smape: 1.2428

Epoch 10/128

240/240 - 5s - 21ms/step - ia: 0.4215 - loss: 0.7562 - mae: 0.6376 - rmse: 0.8643 - smape: 1.2431 - val_ia: 0.3405 - val_loss: 0.8355 - val_mae: 0.6608 - val_rmse: 0.8219 - val_smape: 1.2687

Epoch 11/128

240/240 - 5s - 23ms/step - ia: 0.4255 - loss: 0.7504 - mae: 0.6359 - rmse: 0.8611 - smape: 1.2387 - val_ia: 0.3341 - val_loss: 0.8389 - val_mae: 0.6607 - val_rmse: 0.8217 - val_smape: 1.2793

Epoch 12/128

240/240 - 5s - 21ms/step - ia: 0.4274 - loss: 0.7446 - mae: 0.6336 - rmse: 0.8566 - smape: 1.2361 - val_ia: 0.3338 - val_loss: 0.8225 - val_mae: 0.6620 - val_rmse: 0.8154 - val_smape: 1.2915

Epoch 13/128

240/240 - 5s - 21ms/step - ia: 0.4308 - loss: 0.7406 - mae: 0.6311 - rmse: 0.8555 - smape: 1.2299 - val_ia: 0.3414 - val_loss: 0.8275 - val_mae: 0.6533 - val_rmse: 0.8170 - val_smape: 1.2460

Epoch 14/128

240/240 - 5s - 21ms/step - ia: 0.4336 - loss: 0.7340 - mae: 0.6290 - rmse: 0.8520 - smape: 1.2270 - val_ia: 0.3469 - val_loss: 0.8703 - val_mae: 0.6587 - val_rmse: 0.8281 - val_smape: 1.2280

Epoch 15/128

240/240 - 5s - 21ms/step - ia: 0.4370 - loss: 0.7317 - mae: 0.6280 - rmse: 0.8499 - smape: 1.2226 - val_ia: 0.3361 - val_loss: 0.8560 - val_mae: 0.6632 - val_rmse: 0.8268 - val_smape: 1.2895

Epoch 16/128

240/240 - 5s - 20ms/step - ia: 0.4381 - loss: 0.7284 - mae: 0.6259 - rmse: 0.8486 - smape: 1.2199 - val_ia: 0.3430 - val_loss: 0.8619 - val_mae: 0.6631 - val_rmse: 0.8309 - val_smape: 1.2529

Epoch 17/128

240/240 - 5s - 22ms/step - ia: 0.4403 - loss: 0.7259 - mae: 0.6254 - rmse: 0.8478 - smape: 1.2161 - val_ia: 0.3384 - val_loss: 0.8502 - val_mae: 0.6578 - val_rmse: 0.8241 - val_smape: 1.2561

Epoch 18/128

240/240 - 5s - 20ms/step - ia: 0.4417 - loss: 0.7206 - mae: 0.6235 - rmse: 0.8438 - smape: 1.2143 - val_ia: 0.3496 - val_loss: 0.8603 - val_mae: 0.6595 - val_rmse: 0.8309 - val_smape: 1.2485

Epoch 19/128

240/240 - 6s - 23ms/step - ia: 0.4454 - loss: 0.7197 - mae: 0.6218 - rmse: 0.8440 - smape: 1.2109 - val_ia: 0.3414 - val_loss: 0.8546 - val_mae: 0.6646 - val_rmse: 0.8281 - val_smape: 1.2726

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:57 2s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 25/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 90%|█████████ | 45/50 [11:38:32<12:37, 151.48s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 24s - 25ms/step - ia: 0.3344 - loss: 0.8609 - mae: 0.6869 - rmse: 0.9095 - smape: 1.3751 - val_ia: 0.2626 - val_loss: 0.8021 - val_mae: 0.6720 - val_rmse: 0.7694 - val_smape: 1.3170

Epoch 2/256

958/958 - 10s - 10ms/step - ia: 0.3701 - loss: 0.8225 - mae: 0.6674 - rmse: 0.8883 - smape: 1.3236 - val_ia: 0.2642 - val_loss: 0.7665 - val_mae: 0.6427 - val_rmse: 0.7386 - val_smape: 1.2655

Epoch 3/256

958/958 - 10s - 11ms/step - ia: 0.3810 - loss: 0.8107 - mae: 0.6621 - rmse: 0.8819 - smape: 1.3003 - val_ia: 0.2551 - val_loss: 0.7678 - val_mae: 0.6441 - val_rmse: 0.7333 - val_smape: 1.3143

Epoch 4/256

958/958 - 11s - 12ms/step - ia: 0.3922 - loss: 0.7917 - mae: 0.6564 - rmse: 0.8721 - smape: 1.2839 - val_ia: 0.2574 - val_loss: 0.7727 - val_mae: 0.6432 - val_rmse: 0.7379 - val_smape: 1.2791

Epoch 5/256

958/958 - 18s - 19ms/step - ia: 0.3979 - loss: 0.7829 - mae: 0.6509 - rmse: 0.8671 - smape: 1.2829 - val_ia: 0.2631 - val_loss: 0.7994 - val_mae: 0.6589 - val_rmse: 0.7612 - val_smape: 1.2568

Epoch 6/256

958/958 - 9s - 10ms/step - ia: 0.3998 - loss: 0.7823 - mae: 0.6501 - rmse: 0.8671 - smape: 1.2695 - val_ia: 0.2691 - val_loss: 0.8612 - val_mae: 0.6783 - val_rmse: 0.7913 - val_smape: 1.2349

Epoch 7/256

958/958 - 10s - 11ms/step - ia: 0.3978 - loss: 0.7801 - mae: 0.6514 - rmse: 0.8660 - smape: 1.2799 - val_ia: 0.2581 - val_loss: 0.7928 - val_mae: 0.6565 - val_rmse: 0.7556 - val_smape: 1.2747

Epoch 8/256

958/958 - 10s - 10ms/step - ia: 0.4028 - loss: 0.7761 - mae: 0.6485 - rmse: 0.8623 - smape: 1.2709 - val_ia: 0.2611 - val_loss: 0.8000 - val_mae: 0.6600 - val_rmse: 0.7632 - val_smape: 1.2349

Epoch 9/256

958/958 - 9s - 10ms/step - ia: 0.4089 - loss: 0.7651 - mae: 0.6438 - rmse: 0.8566 - smape: 1.2624 - val_ia: 0.2602 - val_loss: 0.7988 - val_mae: 0.6583 - val_rmse: 0.7592 - val_smape: 1.3047

Epoch 10/256

958/958 - 9s - 10ms/step - ia: 0.4091 - loss: 0.7629 - mae: 0.6434 - rmse: 0.8551 - smape: 1.2660 - val_ia: 0.2584 - val_loss: 0.8250 - val_mae: 0.6632 - val_rmse: 0.7647 - val_smape: 1.2876

Epoch 11/256

958/958 - 9s - 10ms/step - ia: 0.4094 - loss: 0.7610 - mae: 0.6428 - rmse: 0.8548 - smape: 1.2649 - val_ia: 0.2596 - val_loss: 0.8602 - val_mae: 0.6719 - val_rmse: 0.7823 - val_smape: 1.2429

Epoch 12/256

958/958 - 10s - 10ms/step - ia: 0.4146 - loss: 0.7579 - mae: 0.6411 - rmse: 0.8525 - smape: 1.2576 - val_ia: 0.2551 - val_loss: 0.8311 - val_mae: 0.6593 - val_rmse: 0.7573 - val_smape: 1.2950

Epoch 13/256

958/958 - 10s - 10ms/step - ia: 0.4076 - loss: 0.7635 - mae: 0.6448 - rmse: 0.8564 - smape: 1.2680 - val_ia: 0.2564 - val_loss: 0.8393 - val_mae: 0.6758 - val_rmse: 0.7830 - val_smape: 1.2554

Epoch 14/256

958/958 - 10s - 10ms/step - ia: 0.4164 - loss: 0.7493 - mae: 0.6380 - rmse: 0.8476 - smape: 1.2533 - val_ia: 0.2592 - val_loss: 0.8496 - val_mae: 0.6643 - val_rmse: 0.7690 - val_smape: 1.2893

Epoch 15/256

958/958 - 10s - 10ms/step - ia: 0.4122 - loss: 0.7528 - mae: 0.6401 - rmse: 0.8487 - smape: 1.2658 - val_ia: 0.2621 - val_loss: 0.8909 - val_mae: 0.6710 - val_rmse: 0.7839 - val_smape: 1.2514

Epoch 16/256

958/958 - 11s - 11ms/step - ia: 0.4188 - loss: 0.7455 - mae: 0.6370 - rmse: 0.8464 - smape: 1.2570 - val_ia: 0.2601 - val_loss: 0.8598 - val_mae: 0.6668 - val_rmse: 0.7787 - val_smape: 1.2296

Epoch 17/256

958/958 - 11s - 11ms/step - ia: 0.4208 - loss: 0.7463 - mae: 0.6348 - rmse: 0.8463 - smape: 1.2514 - val_ia: 0.2607 - val_loss: 0.7970 - val_mae: 0.6561 - val_rmse: 0.7569 - val_smape: 1.2721

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:14 1s/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 92%|█████████▏| 46/50 [11:42:18<11:34, 173.68s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 8s - 17ms/step - ia: 0.3920 - loss: 0.8164 - mae: 0.6617 - rmse: 0.8930 - smape: 1.2710 - val_ia: 0.2927 - val_loss: 0.7664 - val_mae: 0.6504 - val_rmse: 0.7804 - val_smape: 1.2600

Epoch 2/128

479/479 - 3s - 6ms/step - ia: 0.4134 - loss: 0.7942 - mae: 0.6500 - rmse: 0.8805 - smape: 1.2414 - val_ia: 0.2836 - val_loss: 0.7694 - val_mae: 0.6532 - val_rmse: 0.7785 - val_smape: 1.2644

Epoch 3/128

479/479 - 5s - 10ms/step - ia: 0.4219 - loss: 0.7814 - mae: 0.6439 - rmse: 0.8742 - smape: 1.2256 - val_ia: 0.3017 - val_loss: 0.7880 - val_mae: 0.6469 - val_rmse: 0.7836 - val_smape: 1.2303

Epoch 4/128

479/479 - 3s - 6ms/step - ia: 0.3756 - loss: 1.5687 - mae: 0.6831 - rmse: 0.9506 - smape: 1.3078 - val_ia: 0.2657 - val_loss: 0.8111 - val_mae: 0.6779 - val_rmse: 0.8021 - val_smape: 1.3726

Epoch 5/128

479/479 - 5s - 11ms/step - ia: 0.3910 - loss: 0.8072 - mae: 0.6607 - rmse: 0.8878 - smape: 1.2750 - val_ia: 0.2706 - val_loss: 0.8266 - val_mae: 0.6622 - val_rmse: 0.7922 - val_smape: 1.2947

Epoch 6/128

479/479 - 3s - 6ms/step - ia: 0.4080 - loss: 0.7861 - mae: 0.6510 - rmse: 0.8771 - smape: 1.2535 - val_ia: 0.2747 - val_loss: 0.8737 - val_mae: 0.6780 - val_rmse: 0.8125 - val_smape: 1.3183

Epoch 7/128

479/479 - 3s - 6ms/step - ia: 0.4172 - loss: 0.7740 - mae: 0.6437 - rmse: 0.8704 - smape: 1.2397 - val_ia: 0.2802 - val_loss: 0.7829 - val_mae: 0.6490 - val_rmse: 0.7789 - val_smape: 1.2706

Epoch 8/128

479/479 - 3s - 6ms/step - ia: 0.4259 - loss: 0.7664 - mae: 0.6394 - rmse: 0.8644 - smape: 1.2263 - val_ia: 0.2775 - val_loss: 0.8084 - val_mae: 0.6561 - val_rmse: 0.7869 - val_smape: 1.2718

Epoch 9/128

479/479 - 2s - 5ms/step - ia: 0.3984 - loss: 1.1661 - mae: 0.6575 - rmse: 0.9086 - smape: 1.2720 - val_ia: 0.2776 - val_loss: 0.8620 - val_mae: 0.6716 - val_rmse: 0.8106 - val_smape: 1.2788

Epoch 10/128

479/479 - 3s - 6ms/step - ia: 0.4118 - loss: 0.7692 - mae: 0.6430 - rmse: 0.8680 - smape: 1.2587 - val_ia: 0.2744 - val_loss: 0.8288 - val_mae: 0.6786 - val_rmse: 0.8095 - val_smape: 1.3484

Epoch 11/128

479/479 - 3s - 6ms/step - ia: 0.4227 - loss: 0.7551 - mae: 0.6377 - rmse: 0.8590 - smape: 1.2431 - val_ia: 0.2817 - val_loss: 0.8292 - val_mae: 0.6580 - val_rmse: 0.7945 - val_smape: 1.2749

Epoch 12/128

479/479 - 5s - 11ms/step - ia: 0.4268 - loss: 0.7499 - mae: 0.6343 - rmse: 0.8564 - smape: 1.2335 - val_ia: 0.2845 - val_loss: 0.8443 - val_mae: 0.6735 - val_rmse: 0.8148 - val_smape: 1.2931

Epoch 13/128

479/479 - 3s - 6ms/step - ia: 0.4364 - loss: 0.7396 - mae: 0.6289 - rmse: 0.8503 - smape: 1.2210 - val_ia: 0.2829 - val_loss: 0.8381 - val_mae: 0.6801 - val_rmse: 0.8155 - val_smape: 1.3360

Epoch 14/128

479/479 - 3s - 6ms/step - ia: 0.2006 - loss: 3142273280.0000 - mae: 12843.0186 - rmse: 26016.7324 - smape: 1.5928 - val_ia: 3.3352e-05 - val_loss: 3296081152.0000 - val_mae: 32373.0977 - val_rmse: 48018.4648 - val_smape: 1.9991

Epoch 15/128

479/479 - 3s - 6ms/step - ia: 0.0265 - loss: 807329536.0000 - mae: 6367.5430 - rmse: 11511.5840 - smape: 1.8636 - val_ia: 0.1376 - val_loss: 28.2222 - val_mae: 3.2723 - val_rmse: 4.9180 - val_smape: 1.4913

Epoch 16/128

479/479 - 5s - 11ms/step - ia: 0.3466 - loss: 4.1780 - mae: 1.3220 - rmse: 1.8393 - smape: 1.2688 - val_ia: 0.2853 - val_loss: 2.3004 - val_mae: 1.1266 - val_rmse: 1.3551 - val_smape: 1.2236

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 44s 333ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 94%|█████████▍| 47/50 [11:43:18<06:59, 139.76s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

3830/3830 - 35s - 9ms/step - ia: 0.3448 - loss: 0.8474 - mae: 0.6813 - rmse: 0.8609 - smape: 1.3771 - val_ia: 0.1991 - val_loss: 0.8047 - val_mae: 0.6648 - val_rmse: 0.7049 - val_smape: 1.3159

Epoch 2/8

3830/3830 - 30s - 8ms/step - ia: 0.3833 - loss: 0.8110 - mae: 0.6610 - rmse: 0.8420 - smape: 1.2946 - val_ia: 0.1996 - val_loss: 0.7741 - val_mae: 0.6534 - val_rmse: 0.6925 - val_smape: 1.2939

Epoch 3/8

3830/3830 - 43s - 11ms/step - ia: 0.3949 - loss: 0.7928 - mae: 0.6523 - rmse: 0.8344 - smape: 1.2661 - val_ia: 0.2014 - val_loss: 0.7847 - val_mae: 0.6571 - val_rmse: 0.6971 - val_smape: 1.2908

Epoch 4/8

3830/3830 - 31s - 8ms/step - ia: 0.4000 - loss: 0.7830 - mae: 0.6481 - rmse: 0.8277 - smape: 1.2534 - val_ia: 0.2014 - val_loss: 0.7799 - val_mae: 0.6621 - val_rmse: 0.7020 - val_smape: 1.3065

Epoch 5/8

3830/3830 - 41s - 11ms/step - ia: 0.4049 - loss: 0.7769 - mae: 0.6459 - rmse: 0.8253 - smape: 1.2458 - val_ia: 0.2042 - val_loss: 0.7862 - val_mae: 0.6528 - val_rmse: 0.6931 - val_smape: 1.2707

Epoch 6/8

3830/3830 - 32s - 8ms/step - ia: 0.4111 - loss: 0.7690 - mae: 0.6412 - rmse: 0.8207 - smape: 1.2359 - val_ia: 0.2070 - val_loss: 0.7681 - val_mae: 0.6442 - val_rmse: 0.6846 - val_smape: 1.2427

Epoch 7/8

3830/3830 - 31s - 8ms/step - ia: 0.4112 - loss: 0.7650 - mae: 0.6394 - rmse: 0.8190 - smape: 1.2277 - val_ia: 0.2012 - val_loss: 0.7882 - val_mae: 0.6604 - val_rmse: 0.7007 - val_smape: 1.2900

Epoch 8/8

3830/3830 - 33s - 9ms/step - ia: 0.4184 - loss: 0.7560 - mae: 0.6356 - rmse: 0.8149 - smape: 1.2222 - val_ia: 0.2052 - val_loss: 0.7727 - val_mae: 0.6495 - val_rmse: 0.6899 - val_smape: 1.2606

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:17 1s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step

 96%|█████████▌| 48/50 [11:48:00<06:04, 182.23s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 10s - 41ms/step - ia: 0.3493 - loss: 0.8910 - mae: 0.6972 - rmse: 0.9360 - smape: 1.3492 - val_ia: 0.3102 - val_loss: 0.7599 - val_mae: 0.6475 - val_rmse: 0.7897 - val_smape: 1.2946

Epoch 2/16

240/240 - 2s - 8ms/step - ia: 0.3844 - loss: 0.8176 - mae: 0.6662 - rmse: 0.8998 - smape: 1.2938 - val_ia: 0.3341 - val_loss: 0.7665 - val_mae: 0.6484 - val_rmse: 0.7997 - val_smape: 1.2794

Epoch 3/16

240/240 - 3s - 11ms/step - ia: 0.3964 - loss: 0.8036 - mae: 0.6565 - rmse: 0.8919 - smape: 1.2763 - val_ia: 0.3302 - val_loss: 0.7602 - val_mae: 0.6395 - val_rmse: 0.7888 - val_smape: 1.2560

Epoch 4/16

240/240 - 3s - 11ms/step - ia: 0.4018 - loss: 0.7909 - mae: 0.6511 - rmse: 0.8842 - smape: 1.2684 - val_ia: 0.3381 - val_loss: 0.7514 - val_mae: 0.6409 - val_rmse: 0.7903 - val_smape: 1.2755

Epoch 5/16

240/240 - 2s - 9ms/step - ia: 0.4045 - loss: 0.7849 - mae: 0.6499 - rmse: 0.8806 - smape: 1.2643 - val_ia: 0.3436 - val_loss: 0.7618 - val_mae: 0.6403 - val_rmse: 0.7941 - val_smape: 1.2474

Epoch 6/16

240/240 - 2s - 8ms/step - ia: 0.4110 - loss: 0.7778 - mae: 0.6462 - rmse: 0.8765 - smape: 1.2552 - val_ia: 0.3380 - val_loss: 0.7680 - val_mae: 0.6488 - val_rmse: 0.7996 - val_smape: 1.2807

Epoch 7/16

240/240 - 2s - 7ms/step - ia: 0.4153 - loss: 0.7713 - mae: 0.6440 - rmse: 0.8728 - smape: 1.2508 - val_ia: 0.3364 - val_loss: 0.7486 - val_mae: 0.6394 - val_rmse: 0.7846 - val_smape: 1.2841

Epoch 8/16

240/240 - 2s - 7ms/step - ia: 0.4173 - loss: 0.7675 - mae: 0.6413 - rmse: 0.8718 - smape: 1.2464 - val_ia: 0.3460 - val_loss: 0.7487 - val_mae: 0.6371 - val_rmse: 0.7886 - val_smape: 1.2452

Epoch 9/16

240/240 - 3s - 12ms/step - ia: 0.4214 - loss: 0.7661 - mae: 0.6402 - rmse: 0.8700 - smape: 1.2414 - val_ia: 0.3435 - val_loss: 0.7583 - val_mae: 0.6450 - val_rmse: 0.7984 - val_smape: 1.2718

Epoch 10/16

240/240 - 3s - 11ms/step - ia: 0.4247 - loss: 0.7585 - mae: 0.6383 - rmse: 0.8663 - smape: 1.2370 - val_ia: 0.3410 - val_loss: 0.7510 - val_mae: 0.6307 - val_rmse: 0.7843 - val_smape: 1.2302

Epoch 11/16

240/240 - 2s - 10ms/step - ia: 0.4246 - loss: 0.7620 - mae: 0.6373 - rmse: 0.8677 - smape: 1.2330 - val_ia: 0.3484 - val_loss: 0.7566 - val_mae: 0.6417 - val_rmse: 0.7961 - val_smape: 1.2440

Epoch 12/16

240/240 - 2s - 7ms/step - ia: 0.4262 - loss: 0.7563 - mae: 0.6357 - rmse: 0.8646 - smape: 1.2343 - val_ia: 0.3414 - val_loss: 0.7563 - val_mae: 0.6381 - val_rmse: 0.7914 - val_smape: 1.2560

Epoch 13/16

240/240 - 3s - 11ms/step - ia: 0.4278 - loss: 0.7512 - mae: 0.6332 - rmse: 0.8625 - smape: 1.2321 - val_ia: 0.3442 - val_loss: 0.7798 - val_mae: 0.6521 - val_rmse: 0.8046 - val_smape: 1.2796

Epoch 14/16

240/240 - 3s - 11ms/step - ia: 0.4311 - loss: 0.7483 - mae: 0.6321 - rmse: 0.8597 - smape: 1.2311 - val_ia: 0.3447 - val_loss: 0.7642 - val_mae: 0.6420 - val_rmse: 0.7942 - val_smape: 1.2553

Epoch 15/16

240/240 - 2s - 7ms/step - ia: 0.4325 - loss: 0.7463 - mae: 0.6303 - rmse: 0.8587 - smape: 1.2275 - val_ia: 0.3444 - val_loss: 0.7846 - val_mae: 0.6481 - val_rmse: 0.8037 - val_smape: 1.2728

Epoch 16/16

240/240 - 1s - 6ms/step - ia: 0.4353 - loss: 0.7371 - mae: 0.6286 - rmse: 0.8537 - smape: 1.2293 - val_ia: 0.3399 - val_loss: 0.7812 - val_mae: 0.6434 - val_rmse: 0.7979 - val_smape: 1.2616

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 53s 397ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 98%|█████████▊| 49/50 [11:48:45<02:21, 141.25s/trial, best loss: 0.7596827935423266]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 12s - 100ms/step - ia: 0.2688 - loss: 0.9107 - mae: 0.7080 - rmse: 0.9506 - smape: 1.4775 - val_ia: 0.2987 - val_loss: 0.7927 - val_mae: 0.6622 - val_rmse: 0.8186 - val_smape: 1.3858

Epoch 2/32

120/120 - 1s - 12ms/step - ia: 0.3237 - loss: 0.8610 - mae: 0.6855 - rmse: 0.9255 - smape: 1.3901 - val_ia: 0.3110 - val_loss: 0.7715 - val_mae: 0.6591 - val_rmse: 0.8135 - val_smape: 1.3452

Epoch 3/32

120/120 - 2s - 14ms/step - ia: 0.3429 - loss: 0.8449 - mae: 0.6776 - rmse: 0.9174 - smape: 1.3586 - val_ia: 0.3237 - val_loss: 0.7650 - val_mae: 0.6494 - val_rmse: 0.8065 - val_smape: 1.3191

Epoch 4/32

120/120 - 2s - 13ms/step - ia: 0.3511 - loss: 0.8430 - mae: 0.6760 - rmse: 0.9156 - smape: 1.3497 - val_ia: 0.3268 - val_loss: 0.7540 - val_mae: 0.6419 - val_rmse: 0.8010 - val_smape: 1.2968

Epoch 5/32

120/120 - 2s - 14ms/step - ia: 0.3627 - loss: 0.8252 - mae: 0.6689 - rmse: 0.9058 - smape: 1.3313 - val_ia: 0.3487 - val_loss: 0.7522 - val_mae: 0.6401 - val_rmse: 0.8033 - val_smape: 1.2646

Epoch 6/32

120/120 - 3s - 24ms/step - ia: 0.3720 - loss: 0.8148 - mae: 0.6645 - rmse: 0.9005 - smape: 1.3171 - val_ia: 0.3415 - val_loss: 0.7512 - val_mae: 0.6412 - val_rmse: 0.8011 - val_smape: 1.2619

Epoch 7/32

120/120 - 2s - 15ms/step - ia: 0.3756 - loss: 0.8159 - mae: 0.6629 - rmse: 0.9004 - smape: 1.3097 - val_ia: 0.3590 - val_loss: 0.7635 - val_mae: 0.6471 - val_rmse: 0.8130 - val_smape: 1.2571

Epoch 8/32

120/120 - 2s - 16ms/step - ia: 0.3776 - loss: 0.8130 - mae: 0.6626 - rmse: 0.8987 - smape: 1.3079 - val_ia: 0.3575 - val_loss: 0.7654 - val_mae: 0.6422 - val_rmse: 0.8099 - val_smape: 1.2558

Epoch 9/32

120/120 - 2s - 13ms/step - ia: 0.3807 - loss: 0.8075 - mae: 0.6613 - rmse: 0.8962 - smape: 1.3029 - val_ia: 0.3426 - val_loss: 0.7665 - val_mae: 0.6474 - val_rmse: 0.8099 - val_smape: 1.2856

Epoch 10/32

120/120 - 1s - 12ms/step - ia: 0.3864 - loss: 0.8026 - mae: 0.6574 - rmse: 0.8932 - smape: 1.2934 - val_ia: 0.3529 - val_loss: 0.7763 - val_mae: 0.6451 - val_rmse: 0.8146 - val_smape: 1.2500

Epoch 11/32

120/120 - 3s - 22ms/step - ia: 0.3828 - loss: 0.8035 - mae: 0.6574 - rmse: 0.8932 - smape: 1.3009 - val_ia: 0.3429 - val_loss: 0.7753 - val_mae: 0.6572 - val_rmse: 0.8179 - val_smape: 1.3044

Epoch 12/32

120/120 - 2s - 14ms/step - ia: 0.3837 - loss: 0.8027 - mae: 0.6592 - rmse: 0.8931 - smape: 1.2987 - val_ia: 0.3431 - val_loss: 0.7567 - val_mae: 0.6385 - val_rmse: 0.8014 - val_smape: 1.2952

Epoch 13/32

120/120 - 2s - 21ms/step - ia: 0.3940 - loss: 0.7908 - mae: 0.6531 - rmse: 0.8861 - smape: 1.2811 - val_ia: 0.3602 - val_loss: 0.7806 - val_mae: 0.6539 - val_rmse: 0.8222 - val_smape: 1.2582

Epoch 14/32

120/120 - 2s - 13ms/step - ia: 0.3912 - loss: 0.7959 - mae: 0.6556 - rmse: 0.8895 - smape: 1.2866 - val_ia: 0.3413 - val_loss: 0.7601 - val_mae: 0.6355 - val_rmse: 0.8005 - val_smape: 1.2595

Epoch 15/32

120/120 - 2s - 13ms/step - ia: 0.3927 - loss: 0.7901 - mae: 0.6531 - rmse: 0.8867 - smape: 1.2877 - val_ia: 0.3448 - val_loss: 0.7692 - val_mae: 0.6426 - val_rmse: 0.8081 - val_smape: 1.2709

Epoch 16/32

120/120 - 1s - 12ms/step - ia: 0.3881 - loss: 0.7937 - mae: 0.6548 - rmse: 0.8883 - smape: 1.2922 - val_ia: 0.3621 - val_loss: 0.7654 - val_mae: 0.6412 - val_rmse: 0.8111 - val_smape: 1.2307

Epoch 17/32

120/120 - 2s - 13ms/step - ia: 0.3976 - loss: 0.7836 - mae: 0.6495 - rmse: 0.8826 - smape: 1.2772 - val_ia: 0.3492 - val_loss: 0.7765 - val_mae: 0.6475 - val_rmse: 0.8157 - val_smape: 1.2438

Epoch 18/32

120/120 - 2s - 14ms/step - ia: 0.3724 - loss: 0.8281 - mae: 0.6641 - rmse: 0.9053 - smape: 1.3077 - val_ia: 0.3342 - val_loss: 0.7646 - val_mae: 0.6464 - val_rmse: 0.8090 - val_smape: 1.2872

Epoch 19/32

120/120 - 2s - 13ms/step - ia: 0.3875 - loss: 0.8025 - mae: 0.6574 - rmse: 0.8931 - smape: 1.2885 - val_ia: 0.3339 - val_loss: 0.7767 - val_mae: 0.6572 - val_rmse: 0.8190 - val_smape: 1.3137

Epoch 20/32

120/120 - 2s - 14ms/step - ia: 0.3903 - loss: 0.7940 - mae: 0.6546 - rmse: 0.8884 - smape: 1.2848 - val_ia: 0.3440 - val_loss: 0.7934 - val_mae: 0.6574 - val_rmse: 0.8250 - val_smape: 1.2717

Epoch 21/32

120/120 - 2s - 14ms/step - ia: 0.3933 - loss: 0.7909 - mae: 0.6535 - rmse: 0.8866 - smape: 1.2848 - val_ia: 0.3459 - val_loss: 0.7757 - val_mae: 0.6508 - val_rmse: 0.8186 - val_smape: 1.2667

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:45 784ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

100%|██████████| 50/50 [11:49:36<00:00, 851.52s/trial, best loss: 0.7596827935423266]

In [23]:
print(best)

{'activation': 1, 'batch': 2, 'dropout': 0.30000000000000004, 'epochs': 5, 'layers': 4.0, 'learning_rate': 0.0002283375510850933, 'units': 4}