Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [15]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [16]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (52381, 60)

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 60)
Las dimensiones de testX son:  (10529, 60)
Las dimensiones de valX son:  (5186, 60)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 25s - 22ms/step - ia: 0.3337 - loss: 1.3041 - mae: 0.8756 - rmse: 1.0993 - smape: 1.4130 - val_ia: 0.2520 - val_loss: 0.9318 - val_mae: 0.7932 - val_rmse: 0.8629 - val_smape: 1.4030

Epoch 2/128

1146/1146 - 9s - 8ms/step - ia: 0.4165 - loss: 0.7816 - mae: 0.7118 - rmse: 0.8778 - smape: 1.3042 - val_ia: 0.2514 - val_loss: 1.1205 - val_mae: 0.8785 - val_rmse: 0.9476 - val_smape: 1.3789

Epoch 3/128

1146/1146 - 5s - 4ms/step - ia: 0.4652 - loss: 0.6911 - mae: 0.6688 - rmse: 0.8258 - smape: 1.2183 - val_ia: 0.2449 - val_loss: 1.2003 - val_mae: 0.9178 - val_rmse: 0.9849 - val_smape: 1.3899

Epoch 4/128

1146/1146 - 7s - 6ms/step - ia: 0.4865 - loss: 0.6516 - mae: 0.6492 - rmse: 0.8018 - smape: 1.1756 - val_ia: 0.2407 - val_loss: 1.2256 - val_mae: 0.9279 - val_rmse: 0.9961 - val_smape: 1.3840

Epoch 5/128

1146/1146 - 4s - 3ms/step - ia: 0.4997 - loss: 0.6289 - mae: 0.6368 - rmse: 0.7877 - smape: 1.1513 - val_ia: 0.2356 - val_loss: 1.3119 - val_mae: 0.9542 - val_rmse: 1.0261 - val_smape: 1.3644

Epoch 6/128

1146/1146 - 5s - 5ms/step - ia: 0.5112 - loss: 0.6099 - mae: 0.6267 - rmse: 0.7757 - smape: 1.1304 - val_ia: 0.2459 - val_loss: 1.1505 - val_mae: 0.8969 - val_rmse: 0.9652 - val_smape: 1.3608

Epoch 7/128

1146/1146 - 4s - 4ms/step - ia: 0.5148 - loss: 0.6011 - mae: 0.6227 - rmse: 0.7695 - smape: 1.1221 - val_ia: 0.2443 - val_loss: 1.1906 - val_mae: 0.9084 - val_rmse: 0.9800 - val_smape: 1.3392

Epoch 8/128

1146/1146 - 5s - 4ms/step - ia: 0.5199 - loss: 0.5947 - mae: 0.6185 - rmse: 0.7658 - smape: 1.1107 - val_ia: 0.2417 - val_loss: 1.1719 - val_mae: 0.9109 - val_rmse: 0.9802 - val_smape: 1.3585

Epoch 9/128

1146/1146 - 5s - 4ms/step - ia: 0.5261 - loss: 0.5847 - mae: 0.6127 - rmse: 0.7592 - smape: 1.1008 - val_ia: 0.2402 - val_loss: 1.2188 - val_mae: 0.9271 - val_rmse: 0.9978 - val_smape: 1.3493

Epoch 10/128

1146/1146 - 9s - 8ms/step - ia: 0.5269 - loss: 0.5852 - mae: 0.6124 - rmse: 0.7595 - smape: 1.0957 - val_ia: 0.2347 - val_loss: 1.2587 - val_mae: 0.9551 - val_rmse: 1.0224 - val_smape: 1.3796

Epoch 11/128

1146/1146 - 9s - 8ms/step - ia: 0.5265 - loss: 0.5831 - mae: 0.6116 - rmse: 0.7583 - smape: 1.0979 - val_ia: 0.2428 - val_loss: 1.2388 - val_mae: 0.9252 - val_rmse: 0.9985 - val_smape: 1.3246

Epoch 12/128

1146/1146 - 12s - 10ms/step - ia: 0.5283 - loss: 0.5818 - mae: 0.6115 - rmse: 0.7573 - smape: 1.0955 - val_ia: 0.2380 - val_loss: 1.2343 - val_mae: 0.9379 - val_rmse: 1.0062 - val_smape: 1.3641

Epoch 13/128

1146/1146 - 10s - 9ms/step - ia: 0.5302 - loss: 0.5776 - mae: 0.6093 - rmse: 0.7547 - smape: 1.0894 - val_ia: 0.2398 - val_loss: 1.2055 - val_mae: 0.9260 - val_rmse: 0.9956 - val_smape: 1.3513

Epoch 14/128

1146/1146 - 6s - 5ms/step - ia: 0.5299 - loss: 0.5773 - mae: 0.6095 - rmse: 0.7545 - smape: 1.0910 - val_ia: 0.2402 - val_loss: 1.2110 - val_mae: 0.9329 - val_rmse: 0.9992 - val_smape: 1.3736

Epoch 15/128

1146/1146 - 4s - 4ms/step - ia: 0.5307 - loss: 0.5770 - mae: 0.6082 - rmse: 0.7547 - smape: 1.0878 - val_ia: 0.2442 - val_loss: 1.1652 - val_mae: 0.9120 - val_rmse: 0.9785 - val_smape: 1.3596

Epoch 16/128

1146/1146 - 4s - 4ms/step - ia: 0.5340 - loss: 0.5707 - mae: 0.6053 - rmse: 0.7496 - smape: 1.0828 - val_ia: 0.2341 - val_loss: 1.2633 - val_mae: 0.9589 - val_rmse: 1.0254 - val_smape: 1.3802

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 46s 289ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

  2%|▏         | 1/50 [02:12<1:47:50, 132.04s/trial, best loss: 1.3617105761680324]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

144/144 - 8s - 57ms/step - ia: 0.6949 - loss: 0.3147 - mae: 0.4293 - rmse: 0.5412 - smape: 0.8346 - val_ia: 0.5672 - val_loss: 0.6156 - val_mae: 0.6257 - val_rmse: 0.7591 - val_smape: 1.1070

Epoch 2/16

144/144 - 2s - 12ms/step - ia: 0.8205 - loss: 0.1401 - mae: 0.2830 - rmse: 0.3731 - smape: 0.6285 - val_ia: 0.6248 - val_loss: 0.4358 - val_mae: 0.5078 - val_rmse: 0.6333 - val_smape: 1.0256

Epoch 3/16

144/144 - 1s - 4ms/step - ia: 0.8458 - loss: 0.1078 - mae: 0.2461 - rmse: 0.3278 - smape: 0.5702 - val_ia: 0.6653 - val_loss: 0.3279 - val_mae: 0.4285 - val_rmse: 0.5511 - val_smape: 0.8946

Epoch 4/16

144/144 - 1s - 5ms/step - ia: 0.8581 - loss: 0.0930 - mae: 0.2277 - rmse: 0.3042 - smape: 0.5413 - val_ia: 0.6620 - val_loss: 0.3606 - val_mae: 0.4437 - val_rmse: 0.5669 - val_smape: 0.8919

Epoch 5/16

144/144 - 2s - 14ms/step - ia: 0.8680 - loss: 0.0820 - mae: 0.2128 - rmse: 0.2857 - smape: 0.5128 - val_ia: 0.6684 - val_loss: 0.3535 - val_mae: 0.4410 - val_rmse: 0.5584 - val_smape: 0.8844

Epoch 6/16

144/144 - 3s - 17ms/step - ia: 0.8751 - loss: 0.0743 - mae: 0.2017 - rmse: 0.2717 - smape: 0.4922 - val_ia: 0.6794 - val_loss: 0.3223 - val_mae: 0.4230 - val_rmse: 0.5321 - val_smape: 0.8417

Epoch 7/16

144/144 - 2s - 14ms/step - ia: 0.8798 - loss: 0.0692 - mae: 0.1946 - rmse: 0.2626 - smape: 0.4808 - val_ia: 0.6839 - val_loss: 0.3259 - val_mae: 0.4279 - val_rmse: 0.5348 - val_smape: 0.8348

Epoch 8/16

144/144 - 3s - 18ms/step - ia: 0.8843 - loss: 0.0644 - mae: 0.1876 - rmse: 0.2528 - smape: 0.4706 - val_ia: 0.6793 - val_loss: 0.3173 - val_mae: 0.4249 - val_rmse: 0.5276 - val_smape: 0.8512

Epoch 9/16

144/144 - 2s - 12ms/step - ia: 0.8910 - loss: 0.0585 - mae: 0.1771 - rmse: 0.2406 - smape: 0.4501 - val_ia: 0.6853 - val_loss: 0.3110 - val_mae: 0.4181 - val_rmse: 0.5231 - val_smape: 0.8281

Epoch 10/16

144/144 - 2s - 17ms/step - ia: 0.8931 - loss: 0.0560 - mae: 0.1738 - rmse: 0.2361 - smape: 0.4458 - val_ia: 0.7126 - val_loss: 0.2617 - val_mae: 0.3889 - val_rmse: 0.4811 - val_smape: 0.7642

Epoch 11/16

144/144 - 1s - 9ms/step - ia: 0.8953 - loss: 0.0540 - mae: 0.1702 - rmse: 0.2314 - smape: 0.4384 - val_ia: 0.7158 - val_loss: 0.2596 - val_mae: 0.3865 - val_rmse: 0.4766 - val_smape: 0.7642

Epoch 12/16

144/144 - 1s - 7ms/step - ia: 0.8977 - loss: 0.0514 - mae: 0.1664 - rmse: 0.2261 - smape: 0.4320 - val_ia: 0.7174 - val_loss: 0.2547 - val_mae: 0.3842 - val_rmse: 0.4716 - val_smape: 0.7643

Epoch 13/16

144/144 - 1s - 6ms/step - ia: 0.8991 - loss: 0.0504 - mae: 0.1643 - rmse: 0.2236 - smape: 0.4278 - val_ia: 0.7373 - val_loss: 0.2079 - val_mae: 0.3455 - val_rmse: 0.4328 - val_smape: 0.7010

Epoch 14/16

144/144 - 2s - 12ms/step - ia: 0.9012 - loss: 0.0485 - mae: 0.1610 - rmse: 0.2194 - smape: 0.4226 - val_ia: 0.7315 - val_loss: 0.2281 - val_mae: 0.3610 - val_rmse: 0.4453 - val_smape: 0.7295

Epoch 15/16

144/144 - 1s - 9ms/step - ia: 0.9040 - loss: 0.0459 - mae: 0.1565 - rmse: 0.2135 - smape: 0.4141 - val_ia: 0.7540 - val_loss: 0.1974 - val_mae: 0.3386 - val_rmse: 0.4119 - val_smape: 0.6850

Epoch 16/16

144/144 - 1s - 10ms/step - ia: 0.9053 - loss: 0.0445 - mae: 0.1542 - rmse: 0.2105 - smape: 0.4128 - val_ia: 0.7444 - val_loss: 0.2023 - val_mae: 0.3381 - val_rmse: 0.4207 - val_smape: 0.6797

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:07 418ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

  4%|▍         | 2/50 [02:48<1:00:28, 75.60s/trial, best loss: 0.42669176630993966]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

573/573 - 14s - 24ms/step - ia: 0.3078 - loss: 1.7181 - mae: 1.0578 - rmse: 1.3057 - smape: 1.4981 - val_ia: 0.3360 - val_loss: 0.7910 - val_mae: 0.7283 - val_rmse: 0.8554 - val_smape: 1.2928

Epoch 2/8

573/573 - 4s - 6ms/step - ia: 0.3115 - loss: 1.6203 - mae: 1.0292 - rmse: 1.2684 - smape: 1.4974 - val_ia: 0.3388 - val_loss: 0.7614 - val_mae: 0.7120 - val_rmse: 0.8400 - val_smape: 1.2995

Epoch 3/8

573/573 - 3s - 5ms/step - ia: 0.3149 - loss: 1.5225 - mae: 1.0000 - rmse: 1.2297 - smape: 1.4944 - val_ia: 0.3413 - val_loss: 0.7376 - val_mae: 0.6982 - val_rmse: 0.8273 - val_smape: 1.3073

Epoch 4/8

573/573 - 2s - 3ms/step - ia: 0.3173 - loss: 1.4330 - mae: 0.9725 - rmse: 1.1930 - smape: 1.4959 - val_ia: 0.3436 - val_loss: 0.7192 - val_mae: 0.6868 - val_rmse: 0.8173 - val_smape: 1.3160

Epoch 5/8

573/573 - 2s - 3ms/step - ia: 0.3201 - loss: 1.3675 - mae: 0.9501 - rmse: 1.1653 - smape: 1.4941 - val_ia: 0.3455 - val_loss: 0.7048 - val_mae: 0.6775 - val_rmse: 0.8092 - val_smape: 1.3258

Epoch 6/8

573/573 - 3s - 5ms/step - ia: 0.3221 - loss: 1.3116 - mae: 0.9302 - rmse: 1.1416 - smape: 1.4918 - val_ia: 0.3466 - val_loss: 0.6941 - val_mae: 0.6710 - val_rmse: 0.8030 - val_smape: 1.3364

Epoch 7/8

573/573 - 2s - 3ms/step - ia: 0.3235 - loss: 1.2512 - mae: 0.9100 - rmse: 1.1149 - smape: 1.4903 - val_ia: 0.3476 - val_loss: 0.6862 - val_mae: 0.6661 - val_rmse: 0.7983 - val_smape: 1.3460

Epoch 8/8

573/573 - 3s - 5ms/step - ia: 0.3267 - loss: 1.1917 - mae: 0.8878 - rmse: 1.0881 - smape: 1.4864 - val_ia: 0.3480 - val_loss: 0.6806 - val_mae: 0.6632 - val_rmse: 0.7948 - val_smape: 1.3564

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 21s 131ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  6%|▌         | 3/50 [03:21<44:08, 56.35s/trial, best loss: 0.42669176630993966]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

287/287 - 13s - 46ms/step - ia: 0.3363 - loss: 1.6857 - mae: 1.0419 - rmse: 1.2946 - smape: 1.3862 - val_ia: 0.2705 - val_loss: 0.8235 - val_mae: 0.7520 - val_rmse: 0.8982 - val_smape: 1.4993

Epoch 2/32

287/287 - 1s - 4ms/step - ia: 0.3824 - loss: 1.4613 - mae: 0.9692 - rmse: 1.2065 - smape: 1.3269 - val_ia: 0.3543 - val_loss: 0.8024 - val_mae: 0.7374 - val_rmse: 0.8833 - val_smape: 1.3521

Epoch 3/32

287/287 - 1s - 5ms/step - ia: 0.4094 - loss: 1.3406 - mae: 0.9293 - rmse: 1.1564 - smape: 1.2947 - val_ia: 0.3953 - val_loss: 0.8618 - val_mae: 0.7612 - val_rmse: 0.9123 - val_smape: 1.2965

Epoch 4/32

287/287 - 2s - 7ms/step - ia: 0.4278 - loss: 1.2741 - mae: 0.9042 - rmse: 1.1267 - smape: 1.2657 - val_ia: 0.4113 - val_loss: 0.9306 - val_mae: 0.7940 - val_rmse: 0.9460 - val_smape: 1.2891

Epoch 5/32

287/287 - 3s - 9ms/step - ia: 0.4404 - loss: 1.2249 - mae: 0.8859 - rmse: 1.1044 - smape: 1.2480 - val_ia: 0.4188 - val_loss: 0.9869 - val_mae: 0.8206 - val_rmse: 0.9736 - val_smape: 1.2889

Epoch 6/32

287/287 - 2s - 7ms/step - ia: 0.4502 - loss: 1.1837 - mae: 0.8713 - rmse: 1.0861 - smape: 1.2336 - val_ia: 0.4211 - val_loss: 1.0306 - val_mae: 0.8418 - val_rmse: 0.9947 - val_smape: 1.2938

Epoch 7/32

287/287 - 2s - 8ms/step - ia: 0.4588 - loss: 1.1358 - mae: 0.8526 - rmse: 1.0638 - smape: 1.2213 - val_ia: 0.4209 - val_loss: 1.0669 - val_mae: 0.8615 - val_rmse: 1.0115 - val_smape: 1.3024

Epoch 8/32

287/287 - 1s - 5ms/step - ia: 0.4631 - loss: 1.1051 - mae: 0.8456 - rmse: 1.0493 - smape: 1.2204 - val_ia: 0.4195 - val_loss: 1.0952 - val_mae: 0.8776 - val_rmse: 1.0242 - val_smape: 1.3119

Epoch 9/32

287/287 - 1s - 5ms/step - ia: 0.4679 - loss: 1.0874 - mae: 0.8352 - rmse: 1.0411 - smape: 1.2079 - val_ia: 0.4206 - val_loss: 1.1204 - val_mae: 0.8878 - val_rmse: 1.0358 - val_smape: 1.3103

Epoch 10/32

287/287 - 1s - 4ms/step - ia: 0.4750 - loss: 1.0537 - mae: 0.8229 - rmse: 1.0246 - smape: 1.1961 - val_ia: 0.4194 - val_loss: 1.1397 - val_mae: 0.8980 - val_rmse: 1.0441 - val_smape: 1.3160

Epoch 11/32

287/287 - 1s - 3ms/step - ia: 0.4827 - loss: 1.0144 - mae: 0.8067 - rmse: 1.0052 - smape: 1.1870 - val_ia: 0.4189 - val_loss: 1.1490 - val_mae: 0.9040 - val_rmse: 1.0478 - val_smape: 1.3191

Epoch 12/32

287/287 - 2s - 6ms/step - ia: 0.4831 - loss: 1.0091 - mae: 0.8062 - rmse: 1.0024 - smape: 1.1850 - val_ia: 0.4187 - val_loss: 1.1663 - val_mae: 0.9112 - val_rmse: 1.0554 - val_smape: 1.3196

Epoch 13/32

287/287 - 1s - 5ms/step - ia: 0.4872 - loss: 0.9853 - mae: 0.7969 - rmse: 0.9908 - smape: 1.1794 - val_ia: 0.4190 - val_loss: 1.1752 - val_mae: 0.9145 - val_rmse: 1.0592 - val_smape: 1.3186

Epoch 14/32

287/287 - 2s - 7ms/step - ia: 0.4926 - loss: 0.9600 - mae: 0.7861 - rmse: 0.9779 - smape: 1.1699 - val_ia: 0.4184 - val_loss: 1.1810 - val_mae: 0.9180 - val_rmse: 1.0611 - val_smape: 1.3212

Epoch 15/32

287/287 - 2s - 8ms/step - ia: 0.4957 - loss: 0.9435 - mae: 0.7778 - rmse: 0.9699 - smape: 1.1658 - val_ia: 0.4185 - val_loss: 1.1976 - val_mae: 0.9246 - val_rmse: 1.0684 - val_smape: 1.3214

Epoch 16/32

287/287 - 1s - 4ms/step - ia: 0.5028 - loss: 0.9224 - mae: 0.7680 - rmse: 0.9586 - smape: 1.1518 - val_ia: 0.4179 - val_loss: 1.1982 - val_mae: 0.9267 - val_rmse: 1.0680 - val_smape: 1.3243

Epoch 17/32

287/287 - 2s - 6ms/step - ia: 0.5039 - loss: 0.9077 - mae: 0.7631 - rmse: 0.9510 - smape: 1.1539 - val_ia: 0.4185 - val_loss: 1.2015 - val_mae: 0.9267 - val_rmse: 1.0690 - val_smape: 1.3225

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 53s 329ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  8%|▊         | 4/50 [04:03<38:42, 50.49s/trial, best loss: 0.42669176630993966]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

4584/4584 - 19s - 4ms/step - ia: 0.2630 - loss: 1.1885 - mae: 0.9005 - rmse: 1.0662 - smape: 1.5013 - val_ia: 0.1346 - val_loss: 0.9870 - val_mae: 0.8263 - val_rmse: 0.8422 - val_smape: 1.5381

Epoch 2/64

4584/4584 - 22s - 5ms/step - ia: 0.2647 - loss: 1.1089 - mae: 0.8696 - rmse: 1.0313 - smape: 1.5136 - val_ia: 0.1366 - val_loss: 0.9172 - val_mae: 0.7966 - val_rmse: 0.8132 - val_smape: 1.5939

Epoch 3/64

4584/4584 - 22s - 5ms/step - ia: 0.2664 - loss: 1.0718 - mae: 0.8568 - rmse: 1.0138 - smape: 1.5235 - val_ia: 0.1397 - val_loss: 0.8724 - val_mae: 0.7769 - val_rmse: 0.7940 - val_smape: 1.6520

Epoch 4/64

4584/4584 - 14s - 3ms/step - ia: 0.2729 - loss: 1.0333 - mae: 0.8411 - rmse: 0.9952 - smape: 1.5111 - val_ia: 0.1395 - val_loss: 0.8427 - val_mae: 0.7634 - val_rmse: 0.7807 - val_smape: 1.6601

Epoch 5/64

4584/4584 - 15s - 3ms/step - ia: 0.2820 - loss: 0.9990 - mae: 0.8294 - rmse: 0.9786 - smape: 1.4969 - val_ia: 0.1403 - val_loss: 0.8218 - val_mae: 0.7536 - val_rmse: 0.7710 - val_smape: 1.6192

Epoch 6/64

4584/4584 - 21s - 5ms/step - ia: 0.2892 - loss: 0.9800 - mae: 0.8214 - rmse: 0.9688 - smape: 1.4839 - val_ia: 0.1413 - val_loss: 0.8065 - val_mae: 0.7461 - val_rmse: 0.7636 - val_smape: 1.5814

Epoch 7/64

4584/4584 - 49s - 11ms/step - ia: 0.2959 - loss: 0.9562 - mae: 0.8110 - rmse: 0.9567 - smape: 1.4653 - val_ia: 0.1411 - val_loss: 0.7944 - val_mae: 0.7401 - val_rmse: 0.7574 - val_smape: 1.5495

Epoch 8/64

4584/4584 - 27s - 6ms/step - ia: 0.3027 - loss: 0.9403 - mae: 0.8039 - rmse: 0.9495 - smape: 1.4505 - val_ia: 0.1405 - val_loss: 0.7849 - val_mae: 0.7353 - val_rmse: 0.7524 - val_smape: 1.5225

Epoch 9/64

4584/4584 - 27s - 6ms/step - ia: 0.3121 - loss: 0.9158 - mae: 0.7928 - rmse: 0.9365 - smape: 1.4312 - val_ia: 0.1401 - val_loss: 0.7781 - val_mae: 0.7318 - val_rmse: 0.7487 - val_smape: 1.4997

Epoch 10/64

4584/4584 - 39s - 9ms/step - ia: 0.3195 - loss: 0.9027 - mae: 0.7877 - rmse: 0.9296 - smape: 1.4236 - val_ia: 0.1398 - val_loss: 0.7738 - val_mae: 0.7296 - val_rmse: 0.7461 - val_smape: 1.4808

Epoch 11/64

4584/4584 - 26s - 6ms/step - ia: 0.3264 - loss: 0.8839 - mae: 0.7793 - rmse: 0.9200 - smape: 1.4070 - val_ia: 0.1388 - val_loss: 0.7707 - val_mae: 0.7280 - val_rmse: 0.7443 - val_smape: 1.4637

Epoch 12/64

4584/4584 - 23s - 5ms/step - ia: 0.3398 - loss: 0.8579 - mae: 0.7668 - rmse: 0.9050 - smape: 1.3869 - val_ia: 0.1370 - val_loss: 0.7695 - val_mae: 0.7274 - val_rmse: 0.7434 - val_smape: 1.4463

Epoch 13/64

4584/4584 - 11s - 3ms/step - ia: 0.3437 - loss: 0.8525 - mae: 0.7643 - rmse: 0.9021 - smape: 1.3751 - val_ia: 0.1356 - val_loss: 0.7701 - val_mae: 0.7278 - val_rmse: 0.7435 - val_smape: 1.4310

Epoch 14/64

4584/4584 - 20s - 4ms/step - ia: 0.3547 - loss: 0.8304 - mae: 0.7531 - rmse: 0.8910 - smape: 1.3539 - val_ia: 0.1335 - val_loss: 0.7739 - val_mae: 0.7297 - val_rmse: 0.7452 - val_smape: 1.4171

Epoch 15/64

4584/4584 - 22s - 5ms/step - ia: 0.3613 - loss: 0.8183 - mae: 0.7463 - rmse: 0.8844 - smape: 1.3400 - val_ia: 0.1322 - val_loss: 0.7779 - val_mae: 0.7318 - val_rmse: 0.7470 - val_smape: 1.4034

Epoch 16/64

4584/4584 - 45s - 10ms/step - ia: 0.3721 - loss: 0.7975 - mae: 0.7368 - rmse: 0.8730 - smape: 1.3194 - val_ia: 0.1326 - val_loss: 0.7835 - val_mae: 0.7345 - val_rmse: 0.7497 - val_smape: 1.3910

Epoch 17/64

4584/4584 - 26s - 6ms/step - ia: 0.3860 - loss: 0.7743 - mae: 0.7241 - rmse: 0.8599 - smape: 1.2925 - val_ia: 0.1335 - val_loss: 0.7896 - val_mae: 0.7376 - val_rmse: 0.7528 - val_smape: 1.3808

Epoch 18/64

4584/4584 - 24s - 5ms/step - ia: 0.3917 - loss: 0.7675 - mae: 0.7202 - rmse: 0.8555 - smape: 1.2819 - val_ia: 0.1338 - val_loss: 0.8000 - val_mae: 0.7428 - val_rmse: 0.7580 - val_smape: 1.3723

Epoch 19/64

4584/4584 - 12s - 3ms/step - ia: 0.3992 - loss: 0.7501 - mae: 0.7120 - rmse: 0.8458 - smape: 1.2661 - val_ia: 0.1340 - val_loss: 0.8103 - val_mae: 0.7480 - val_rmse: 0.7633 - val_smape: 1.3650

Epoch 20/64

4584/4584 - 18s - 4ms/step - ia: 0.4051 - loss: 0.7462 - mae: 0.7086 - rmse: 0.8433 - smape: 1.2569 - val_ia: 0.1350 - val_loss: 0.8212 - val_mae: 0.7536 - val_rmse: 0.7689 - val_smape: 1.3584

Epoch 21/64

4584/4584 - 23s - 5ms/step - ia: 0.4186 - loss: 0.7277 - mae: 0.6982 - rmse: 0.8321 - smape: 1.2316 - val_ia: 0.1361 - val_loss: 0.8328 - val_mae: 0.7594 - val_rmse: 0.7749 - val_smape: 1.3530

Epoch 22/64

4584/4584 - 12s - 3ms/step - ia: 0.4247 - loss: 0.7171 - mae: 0.6928 - rmse: 0.8260 - smape: 1.2191 - val_ia: 0.1359 - val_loss: 0.8455 - val_mae: 0.7657 - val_rmse: 0.7813 - val_smape: 1.3485

Epoch 23/64

4584/4584 - 12s - 3ms/step - ia: 0.4363 - loss: 0.7024 - mae: 0.6862 - rmse: 0.8171 - smape: 1.2078 - val_ia: 0.1361 - val_loss: 0.8591 - val_mae: 0.7724 - val_rmse: 0.7883 - val_smape: 1.3454

Epoch 24/64

4584/4584 - 12s - 3ms/step - ia: 0.4430 - loss: 0.6941 - mae: 0.6796 - rmse: 0.8122 - smape: 1.1904 - val_ia: 0.1361 - val_loss: 0.8738 - val_mae: 0.7796 - val_rmse: 0.7956 - val_smape: 1.3424

Epoch 25/64

4584/4584 - 12s - 3ms/step - ia: 0.4493 - loss: 0.6864 - mae: 0.6751 - rmse: 0.8078 - smape: 1.1790 - val_ia: 0.1362 - val_loss: 0.8882 - val_mae: 0.7866 - val_rmse: 0.8028 - val_smape: 1.3404

Epoch 26/64

4584/4584 - 11s - 2ms/step - ia: 0.4552 - loss: 0.6755 - mae: 0.6687 - rmse: 0.8001 - smape: 1.1650 - val_ia: 0.1362 - val_loss: 0.9032 - val_mae: 0.7938 - val_rmse: 0.8101 - val_smape: 1.3378

Epoch 27/64

4584/4584 - 35s - 8ms/step - ia: 0.4658 - loss: 0.6627 - mae: 0.6626 - rmse: 0.7929 - smape: 1.1519 - val_ia: 0.1360 - val_loss: 0.9164 - val_mae: 0.8001 - val_rmse: 0.8165 - val_smape: 1.3361

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 35s 217ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 10%|█         | 5/50 [14:05<3:07:15, 249.68s/trial, best loss: 0.42669176630993966]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 22s - 19ms/step - ia: 0.2307 - loss: 4.7323 - mae: 1.7024 - rmse: 2.1511 - smape: 1.5255 - val_ia: 0.1804 - val_loss: 1.9126 - val_mae: 1.1475 - val_rmse: 1.2468 - val_smape: 1.4548

Epoch 2/128

1146/1146 - 6s - 5ms/step - ia: 0.2862 - loss: 3.5796 - mae: 1.4788 - rmse: 1.8722 - smape: 1.4492 - val_ia: 0.2095 - val_loss: 1.0709 - val_mae: 0.8615 - val_rmse: 0.9494 - val_smape: 1.3116

Epoch 3/128

1146/1146 - 4s - 4ms/step - ia: 0.3305 - loss: 2.9272 - mae: 1.3332 - rmse: 1.6927 - smape: 1.3843 - val_ia: 0.2366 - val_loss: 0.7721 - val_mae: 0.7281 - val_rmse: 0.8082 - val_smape: 1.1999

Epoch 4/128

1146/1146 - 3s - 3ms/step - ia: 0.3572 - loss: 2.4738 - mae: 1.2339 - rmse: 1.5576 - smape: 1.3503 - val_ia: 0.2460 - val_loss: 0.7177 - val_mae: 0.7060 - val_rmse: 0.7770 - val_smape: 1.2032

Epoch 5/128

1146/1146 - 3s - 3ms/step - ia: 0.3808 - loss: 2.1626 - mae: 1.1527 - rmse: 1.4558 - smape: 1.3159 - val_ia: 0.2355 - val_loss: 0.7747 - val_mae: 0.7409 - val_rmse: 0.8081 - val_smape: 1.2536

Epoch 6/128

1146/1146 - 5s - 4ms/step - ia: 0.4072 - loss: 1.8588 - mae: 1.0692 - rmse: 1.3501 - smape: 1.2791 - val_ia: 0.2347 - val_loss: 0.8609 - val_mae: 0.7885 - val_rmse: 0.8571 - val_smape: 1.2969

Epoch 7/128

1146/1146 - 9s - 8ms/step - ia: 0.4193 - loss: 1.6531 - mae: 1.0169 - rmse: 1.2743 - smape: 1.2682 - val_ia: 0.2332 - val_loss: 0.9633 - val_mae: 0.8341 - val_rmse: 0.9067 - val_smape: 1.3171

Epoch 8/128

1146/1146 - 9s - 8ms/step - ia: 0.4400 - loss: 1.4681 - mae: 0.9568 - rmse: 1.2009 - smape: 1.2374 - val_ia: 0.2340 - val_loss: 1.0559 - val_mae: 0.8724 - val_rmse: 0.9479 - val_smape: 1.3338

Epoch 9/128

1146/1146 - 9s - 7ms/step - ia: 0.4478 - loss: 1.3425 - mae: 0.9185 - rmse: 1.1486 - smape: 1.2278 - val_ia: 0.2346 - val_loss: 1.1360 - val_mae: 0.9051 - val_rmse: 0.9813 - val_smape: 1.3498

Epoch 10/128

1146/1146 - 10s - 9ms/step - ia: 0.4616 - loss: 1.2285 - mae: 0.8800 - rmse: 1.0987 - smape: 1.2115 - val_ia: 0.2339 - val_loss: 1.2026 - val_mae: 0.9298 - val_rmse: 1.0063 - val_smape: 1.3607

Epoch 11/128

1146/1146 - 9s - 8ms/step - ia: 0.4716 - loss: 1.1339 - mae: 0.8453 - rmse: 1.0560 - smape: 1.1921 - val_ia: 0.2331 - val_loss: 1.2556 - val_mae: 0.9507 - val_rmse: 1.0265 - val_smape: 1.3691

Epoch 12/128

1146/1146 - 6s - 5ms/step - ia: 0.4808 - loss: 1.0611 - mae: 0.8175 - rmse: 1.0218 - smape: 1.1774 - val_ia: 0.2313 - val_loss: 1.3073 - val_mae: 0.9679 - val_rmse: 1.0436 - val_smape: 1.3734

Epoch 13/128

1146/1146 - 13s - 12ms/step - ia: 0.4882 - loss: 1.0000 - mae: 0.7940 - rmse: 0.9911 - smape: 1.1692 - val_ia: 0.2299 - val_loss: 1.3552 - val_mae: 0.9850 - val_rmse: 1.0607 - val_smape: 1.3774

Epoch 14/128

1146/1146 - 6s - 5ms/step - ia: 0.4956 - loss: 0.9546 - mae: 0.7756 - rmse: 0.9692 - smape: 1.1579 - val_ia: 0.2299 - val_loss: 1.3661 - val_mae: 0.9873 - val_rmse: 1.0622 - val_smape: 1.3769

Epoch 15/128

1146/1146 - 7s - 6ms/step - ia: 0.5011 - loss: 0.9081 - mae: 0.7562 - rmse: 0.9450 - smape: 1.1456 - val_ia: 0.2299 - val_loss: 1.3949 - val_mae: 0.9964 - val_rmse: 1.0718 - val_smape: 1.3753

Epoch 16/128

1146/1146 - 12s - 10ms/step - ia: 0.5105 - loss: 0.8716 - mae: 0.7390 - rmse: 0.9261 - smape: 1.1330 - val_ia: 0.2290 - val_loss: 1.4088 - val_mae: 1.0016 - val_rmse: 1.0762 - val_smape: 1.3788

Epoch 17/128

1146/1146 - 9s - 8ms/step - ia: 0.5122 - loss: 0.8333 - mae: 0.7250 - rmse: 0.9056 - smape: 1.1289 - val_ia: 0.2286 - val_loss: 1.4246 - val_mae: 1.0066 - val_rmse: 1.0818 - val_smape: 1.3772

Epoch 18/128

1146/1146 - 4s - 4ms/step - ia: 0.5192 - loss: 0.7977 - mae: 0.7103 - rmse: 0.8863 - smape: 1.1194 - val_ia: 0.2289 - val_loss: 1.4421 - val_mae: 1.0131 - val_rmse: 1.0876 - val_smape: 1.3799

Epoch 19/128

1146/1146 - 4s - 4ms/step - ia: 0.5243 - loss: 0.7801 - mae: 0.7019 - rmse: 0.8756 - smape: 1.1102 - val_ia: 0.2290 - val_loss: 1.4389 - val_mae: 1.0119 - val_rmse: 1.0856 - val_smape: 1.3813

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 15s 98ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 12%|█▏        | 6/50 [16:39<2:39:01, 216.86s/trial, best loss: 0.42669176630993966]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 18s - 128ms/step - ia: 0.6542 - loss: 0.4662 - mae: 0.5257 - rmse: 0.6567 - smape: 0.9007 - val_ia: 0.5408 - val_loss: 0.8789 - val_mae: 0.7406 - val_rmse: 0.8926 - val_smape: 1.1112

Epoch 2/128

144/144 - 2s - 14ms/step - ia: 0.7122 - loss: 0.2997 - mae: 0.4374 - rmse: 0.5470 - smape: 0.8061 - val_ia: 0.5833 - val_loss: 0.6044 - val_mae: 0.6356 - val_rmse: 0.7418 - val_smape: 1.0645

Epoch 3/128

144/144 - 3s - 20ms/step - ia: 0.7240 - loss: 0.2823 - mae: 0.4231 - rmse: 0.5308 - smape: 0.7844 - val_ia: 0.6104 - val_loss: 0.5295 - val_mae: 0.5834 - val_rmse: 0.7102 - val_smape: 1.0122

Epoch 4/128

144/144 - 2s - 15ms/step - ia: 0.7300 - loss: 0.2726 - mae: 0.4148 - rmse: 0.5214 - smape: 0.7759 - val_ia: 0.6352 - val_loss: 0.4511 - val_mae: 0.5410 - val_rmse: 0.6519 - val_smape: 0.9903

Epoch 5/128

144/144 - 1s - 8ms/step - ia: 0.7317 - loss: 0.2716 - mae: 0.4130 - rmse: 0.5203 - smape: 0.7737 - val_ia: 0.6723 - val_loss: 0.3335 - val_mae: 0.4706 - val_rmse: 0.5535 - val_smape: 0.8902

Epoch 6/128

144/144 - 1s - 6ms/step - ia: 0.7373 - loss: 0.2620 - mae: 0.4053 - rmse: 0.5112 - smape: 0.7609 - val_ia: 0.6150 - val_loss: 0.5613 - val_mae: 0.6046 - val_rmse: 0.7273 - val_smape: 1.0117

Epoch 7/128

144/144 - 1s - 10ms/step - ia: 0.7379 - loss: 0.2614 - mae: 0.4042 - rmse: 0.5102 - smape: 0.7605 - val_ia: 0.6327 - val_loss: 0.4694 - val_mae: 0.5451 - val_rmse: 0.6654 - val_smape: 0.9718

Epoch 8/128

144/144 - 1s - 8ms/step - ia: 0.7398 - loss: 0.2587 - mae: 0.4018 - rmse: 0.5075 - smape: 0.7571 - val_ia: 0.6862 - val_loss: 0.3166 - val_mae: 0.4504 - val_rmse: 0.5440 - val_smape: 0.8698

Epoch 9/128

144/144 - 1s - 7ms/step - ia: 0.7386 - loss: 0.2621 - mae: 0.4034 - rmse: 0.5112 - smape: 0.7597 - val_ia: 0.6311 - val_loss: 0.4915 - val_mae: 0.5676 - val_rmse: 0.6885 - val_smape: 0.9825

Epoch 10/128

144/144 - 1s - 9ms/step - ia: 0.7400 - loss: 0.2580 - mae: 0.4006 - rmse: 0.5076 - smape: 0.7564 - val_ia: 0.6859 - val_loss: 0.2928 - val_mae: 0.4413 - val_rmse: 0.5329 - val_smape: 0.8755

Epoch 11/128

144/144 - 2s - 16ms/step - ia: 0.7418 - loss: 0.2567 - mae: 0.3990 - rmse: 0.5056 - smape: 0.7511 - val_ia: 0.6282 - val_loss: 0.5460 - val_mae: 0.5804 - val_rmse: 0.7304 - val_smape: 0.9773

Epoch 12/128

144/144 - 2s - 16ms/step - ia: 0.7422 - loss: 0.2561 - mae: 0.3981 - rmse: 0.5057 - smape: 0.7519 - val_ia: 0.6931 - val_loss: 0.2846 - val_mae: 0.4365 - val_rmse: 0.5177 - val_smape: 0.8497

Epoch 13/128

144/144 - 2s - 13ms/step - ia: 0.7429 - loss: 0.2547 - mae: 0.3966 - rmse: 0.5040 - smape: 0.7472 - val_ia: 0.6590 - val_loss: 0.4064 - val_mae: 0.5151 - val_rmse: 0.6254 - val_smape: 0.9249

Epoch 14/128

144/144 - 2s - 17ms/step - ia: 0.7415 - loss: 0.2590 - mae: 0.3997 - rmse: 0.5080 - smape: 0.7521 - val_ia: 0.6580 - val_loss: 0.4094 - val_mae: 0.5113 - val_rmse: 0.6234 - val_smape: 0.9369

Epoch 15/128

144/144 - 3s - 20ms/step - ia: 0.7425 - loss: 0.2553 - mae: 0.3973 - rmse: 0.5047 - smape: 0.7509 - val_ia: 0.6697 - val_loss: 0.3791 - val_mae: 0.4915 - val_rmse: 0.5997 - val_smape: 0.9119

Epoch 16/128

144/144 - 2s - 16ms/step - ia: 0.7420 - loss: 0.2571 - mae: 0.3986 - rmse: 0.5068 - smape: 0.7499 - val_ia: 0.6645 - val_loss: 0.3675 - val_mae: 0.4904 - val_rmse: 0.5876 - val_smape: 0.9235

Epoch 17/128

144/144 - 1s - 10ms/step - ia: 0.7426 - loss: 0.2553 - mae: 0.3970 - rmse: 0.5046 - smape: 0.7475 - val_ia: 0.6119 - val_loss: 0.6185 - val_mae: 0.6227 - val_rmse: 0.7729 - val_smape: 1.0038

Epoch 18/128

144/144 - 1s - 7ms/step - ia: 0.7450 - loss: 0.2518 - mae: 0.3944 - rmse: 0.5010 - smape: 0.7440 - val_ia: 0.6415 - val_loss: 0.4845 - val_mae: 0.5525 - val_rmse: 0.6837 - val_smape: 0.9623

Epoch 19/128

144/144 - 1s - 9ms/step - ia: 0.7440 - loss: 0.2527 - mae: 0.3949 - rmse: 0.5027 - smape: 0.7457 - val_ia: 0.6741 - val_loss: 0.3510 - val_mae: 0.4894 - val_rmse: 0.5750 - val_smape: 0.8917

Epoch 20/128

144/144 - 2s - 11ms/step - ia: 0.7448 - loss: 0.2517 - mae: 0.3945 - rmse: 0.5010 - smape: 0.7441 - val_ia: 0.6787 - val_loss: 0.3377 - val_mae: 0.4792 - val_rmse: 0.5574 - val_smape: 0.8564

Epoch 21/128

144/144 - 1s - 10ms/step - ia: 0.7464 - loss: 0.2507 - mae: 0.3923 - rmse: 0.4992 - smape: 0.7407 - val_ia: 0.7250 - val_loss: 0.2487 - val_mae: 0.4055 - val_rmse: 0.4822 - val_smape: 0.7793

Epoch 22/128

144/144 - 2s - 12ms/step - ia: 0.7464 - loss: 0.2507 - mae: 0.3919 - rmse: 0.5002 - smape: 0.7416 - val_ia: 0.6582 - val_loss: 0.4202 - val_mae: 0.5270 - val_rmse: 0.6340 - val_smape: 0.9456

Epoch 23/128

144/144 - 3s - 20ms/step - ia: 0.7458 - loss: 0.2507 - mae: 0.3930 - rmse: 0.4999 - smape: 0.7416 - val_ia: 0.6870 - val_loss: 0.3053 - val_mae: 0.4484 - val_rmse: 0.5395 - val_smape: 0.8673

Epoch 24/128

144/144 - 4s - 25ms/step - ia: 0.7463 - loss: 0.2496 - mae: 0.3916 - rmse: 0.4993 - smape: 0.7420 - val_ia: 0.6997 - val_loss: 0.2800 - val_mae: 0.4347 - val_rmse: 0.5167 - val_smape: 0.8390

Epoch 25/128

144/144 - 3s - 18ms/step - ia: 0.7448 - loss: 0.2524 - mae: 0.3942 - rmse: 0.5020 - smape: 0.7413 - val_ia: 0.6846 - val_loss: 0.3151 - val_mae: 0.4562 - val_rmse: 0.5454 - val_smape: 0.8739

Epoch 26/128

144/144 - 2s - 17ms/step - ia: 0.7465 - loss: 0.2512 - mae: 0.3923 - rmse: 0.5004 - smape: 0.7400 - val_ia: 0.6688 - val_loss: 0.3363 - val_mae: 0.4738 - val_rmse: 0.5608 - val_smape: 0.8972

Epoch 27/128

144/144 - 1s - 7ms/step - ia: 0.7441 - loss: 0.2533 - mae: 0.3949 - rmse: 0.5028 - smape: 0.7458 - val_ia: 0.6059 - val_loss: 0.6011 - val_mae: 0.6224 - val_rmse: 0.7571 - val_smape: 1.0266

Epoch 28/128

144/144 - 1s - 8ms/step - ia: 0.7463 - loss: 0.2496 - mae: 0.3916 - rmse: 0.4988 - smape: 0.7412 - val_ia: 0.6892 - val_loss: 0.3089 - val_mae: 0.4538 - val_rmse: 0.5367 - val_smape: 0.8673

Epoch 29/128

144/144 - 1s - 6ms/step - ia: 0.7452 - loss: 0.2516 - mae: 0.3944 - rmse: 0.5009 - smape: 0.7440 - val_ia: 0.6846 - val_loss: 0.3398 - val_mae: 0.4716 - val_rmse: 0.5633 - val_smape: 0.8684

Epoch 30/128

144/144 - 2s - 11ms/step - ia: 0.7477 - loss: 0.2461 - mae: 0.3894 - rmse: 0.4961 - smape: 0.7387 - val_ia: 0.6547 - val_loss: 0.4064 - val_mae: 0.5040 - val_rmse: 0.6236 - val_smape: 0.9414

Epoch 31/128

144/144 - 1s - 10ms/step - ia: 0.7454 - loss: 0.2512 - mae: 0.3929 - rmse: 0.5005 - smape: 0.7423 - val_ia: 0.6893 - val_loss: 0.3110 - val_mae: 0.4560 - val_rmse: 0.5353 - val_smape: 0.8627

Epoch 32/128

144/144 - 2s - 11ms/step - ia: 0.7494 - loss: 0.2464 - mae: 0.3874 - rmse: 0.4961 - smape: 0.7336 - val_ia: 0.6945 - val_loss: 0.2930 - val_mae: 0.4382 - val_rmse: 0.5276 - val_smape: 0.8534

Epoch 33/128

144/144 - 2s - 17ms/step - ia: 0.7488 - loss: 0.2449 - mae: 0.3882 - rmse: 0.4942 - smape: 0.7353 - val_ia: 0.6748 - val_loss: 0.3424 - val_mae: 0.4768 - val_rmse: 0.5689 - val_smape: 0.8992

Epoch 34/128

144/144 - 2s - 13ms/step - ia: 0.7469 - loss: 0.2492 - mae: 0.3918 - rmse: 0.4988 - smape: 0.7389 - val_ia: 0.7015 - val_loss: 0.3087 - val_mae: 0.4495 - val_rmse: 0.5439 - val_smape: 0.8539

Epoch 35/128

144/144 - 2s - 15ms/step - ia: 0.7442 - loss: 0.2538 - mae: 0.3946 - rmse: 0.5030 - smape: 0.7435 - val_ia: 0.7121 - val_loss: 0.2591 - val_mae: 0.4203 - val_rmse: 0.5004 - val_smape: 0.8307

Epoch 36/128

144/144 - 3s - 19ms/step - ia: 0.7476 - loss: 0.2472 - mae: 0.3904 - rmse: 0.4965 - smape: 0.7376 - val_ia: 0.6422 - val_loss: 0.4750 - val_mae: 0.5556 - val_rmse: 0.6757 - val_smape: 0.9702

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:09 799ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
147/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 14%|█▍        | 7/50 [18:07<2:05:23, 174.96s/trial, best loss: 0.30989160951024364]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2292/2292 - 36s - 16ms/step - ia: 0.6771 - loss: 0.3637 - mae: 0.4696 - rmse: 0.5864 - smape: 0.8490 - val_ia: 0.2287 - val_loss: 0.7975 - val_mae: 0.6512 - val_rmse: 0.7067 - val_smape: 1.1135

Epoch 2/8

2292/2292 - 19s - 8ms/step - ia: 0.7552 - loss: 0.2216 - mae: 0.3622 - rmse: 0.4603 - smape: 0.7430 - val_ia: 0.2783 - val_loss: 0.3519 - val_mae: 0.4609 - val_rmse: 0.5031 - val_smape: 0.9823

Epoch 3/8

2292/2292 - 13s - 6ms/step - ia: 0.7772 - loss: 0.1872 - mae: 0.3327 - rmse: 0.4232 - smape: 0.7132 - val_ia: 0.3127 - val_loss: 0.2722 - val_mae: 0.4068 - val_rmse: 0.4405 - val_smape: 0.8676

Epoch 4/8

2292/2292 - 15s - 7ms/step - ia: 0.7878 - loss: 0.1715 - mae: 0.3168 - rmse: 0.4044 - smape: 0.6929 - val_ia: 0.3050 - val_loss: 0.2411 - val_mae: 0.3936 - val_rmse: 0.4299 - val_smape: 0.8694

Epoch 5/8

2292/2292 - 15s - 7ms/step - ia: 0.7939 - loss: 0.1631 - mae: 0.3087 - rmse: 0.3942 - smape: 0.6818 - val_ia: 0.3093 - val_loss: 0.2242 - val_mae: 0.3820 - val_rmse: 0.4191 - val_smape: 0.8640

Epoch 6/8

2292/2292 - 7s - 3ms/step - ia: 0.7999 - loss: 0.1554 - mae: 0.3008 - rmse: 0.3848 - smape: 0.6669 - val_ia: 0.3247 - val_loss: 0.1958 - val_mae: 0.3556 - val_rmse: 0.3945 - val_smape: 0.8299

Epoch 7/8

2292/2292 - 18s - 8ms/step - ia: 0.8035 - loss: 0.1496 - mae: 0.2957 - rmse: 0.3779 - smape: 0.6609 - val_ia: 0.3321 - val_loss: 0.1960 - val_mae: 0.3539 - val_rmse: 0.3887 - val_smape: 0.7396

Epoch 8/8

2292/2292 - 23s - 10ms/step - ia: 0.8047 - loss: 0.1475 - mae: 0.2937 - rmse: 0.3754 - smape: 0.6552 - val_ia: 0.3237 - val_loss: 0.1821 - val_mae: 0.3477 - val_rmse: 0.3819 - val_smape: 0.7644

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:57 1s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 16%|█▌        | 8/50 [20:41<1:57:43, 168.18s/trial, best loss: 0.30989160951024364]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 29s - 202ms/step - ia: 0.4523 - loss: 1.1867 - mae: 0.8462 - rmse: 1.0527 - smape: 1.2321 - val_ia: 0.4176 - val_loss: 1.2265 - val_mae: 0.9214 - val_rmse: 1.0831 - val_smape: 1.3462

Epoch 2/128

144/144 - 4s - 25ms/step - ia: 0.5576 - loss: 0.6103 - mae: 0.6256 - rmse: 0.7798 - smape: 1.0554 - val_ia: 0.4052 - val_loss: 1.4443 - val_mae: 1.0044 - val_rmse: 1.1581 - val_smape: 1.3816

Epoch 3/128

144/144 - 3s - 21ms/step - ia: 0.5752 - loss: 0.5607 - mae: 0.5984 - rmse: 0.7479 - smape: 1.0205 - val_ia: 0.3961 - val_loss: 1.5534 - val_mae: 1.0541 - val_rmse: 1.1953 - val_smape: 1.4048

Epoch 4/128

144/144 - 1s - 6ms/step - ia: 0.5805 - loss: 0.5404 - mae: 0.5883 - rmse: 0.7336 - smape: 1.0135 - val_ia: 0.4011 - val_loss: 1.5656 - val_mae: 1.0516 - val_rmse: 1.1991 - val_smape: 1.3889

Epoch 5/128

144/144 - 2s - 11ms/step - ia: 0.5871 - loss: 0.5247 - mae: 0.5793 - rmse: 0.7241 - smape: 1.0057 - val_ia: 0.4093 - val_loss: 1.4760 - val_mae: 1.0143 - val_rmse: 1.1662 - val_smape: 1.3653

Epoch 6/128

144/144 - 3s - 24ms/step - ia: 0.5884 - loss: 0.5197 - mae: 0.5766 - rmse: 0.7204 - smape: 1.0016 - val_ia: 0.4073 - val_loss: 1.4489 - val_mae: 1.0183 - val_rmse: 1.1527 - val_smape: 1.3783

Epoch 7/128

144/144 - 3s - 20ms/step - ia: 0.5922 - loss: 0.5119 - mae: 0.5718 - rmse: 0.7144 - smape: 0.9975 - val_ia: 0.4086 - val_loss: 1.4588 - val_mae: 1.0201 - val_rmse: 1.1571 - val_smape: 1.3733

Epoch 8/128

144/144 - 3s - 22ms/step - ia: 0.5937 - loss: 0.5088 - mae: 0.5692 - rmse: 0.7126 - smape: 0.9916 - val_ia: 0.4160 - val_loss: 1.4626 - val_mae: 1.0095 - val_rmse: 1.1622 - val_smape: 1.3419

Epoch 9/128

144/144 - 2s - 12ms/step - ia: 0.5949 - loss: 0.5063 - mae: 0.5680 - rmse: 0.7113 - smape: 0.9905 - val_ia: 0.4166 - val_loss: 1.4073 - val_mae: 0.9935 - val_rmse: 1.1380 - val_smape: 1.3444

Epoch 10/128

144/144 - 2s - 14ms/step - ia: 0.5957 - loss: 0.5056 - mae: 0.5665 - rmse: 0.7102 - smape: 0.9878 - val_ia: 0.4141 - val_loss: 1.3598 - val_mae: 0.9887 - val_rmse: 1.1132 - val_smape: 1.3639

Epoch 11/128

144/144 - 3s - 20ms/step - ia: 0.5958 - loss: 0.5047 - mae: 0.5660 - rmse: 0.7104 - smape: 0.9885 - val_ia: 0.4094 - val_loss: 1.4573 - val_mae: 1.0221 - val_rmse: 1.1549 - val_smape: 1.3703

Epoch 12/128

144/144 - 4s - 25ms/step - ia: 0.5988 - loss: 0.5000 - mae: 0.5629 - rmse: 0.7064 - smape: 0.9835 - val_ia: 0.4194 - val_loss: 1.3842 - val_mae: 0.9875 - val_rmse: 1.1290 - val_smape: 1.3385

Epoch 13/128

144/144 - 1s - 9ms/step - ia: 0.5977 - loss: 0.4999 - mae: 0.5637 - rmse: 0.7064 - smape: 0.9874 - val_ia: 0.4138 - val_loss: 1.3773 - val_mae: 0.9971 - val_rmse: 1.1245 - val_smape: 1.3618

Epoch 14/128

144/144 - 1s - 5ms/step - ia: 0.5989 - loss: 0.5002 - mae: 0.5633 - rmse: 0.7060 - smape: 0.9834 - val_ia: 0.4169 - val_loss: 1.4052 - val_mae: 0.9971 - val_rmse: 1.1412 - val_smape: 1.3399

Epoch 15/128

144/144 - 1s - 5ms/step - ia: 0.5994 - loss: 0.4985 - mae: 0.5620 - rmse: 0.7056 - smape: 0.9834 - val_ia: 0.4128 - val_loss: 1.3943 - val_mae: 1.0042 - val_rmse: 1.1287 - val_smape: 1.3651

Epoch 16/128

144/144 - 3s - 23ms/step - ia: 0.6002 - loss: 0.4954 - mae: 0.5602 - rmse: 0.7032 - smape: 0.9823 - val_ia: 0.4078 - val_loss: 1.4729 - val_mae: 1.0318 - val_rmse: 1.1632 - val_smape: 1.3725

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 22s 138ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 18%|█▊        | 9/50 [21:49<1:33:30, 136.83s/trial, best loss: 0.30989160951024364]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

1146/1146 - 80s - 70ms/step - ia: 0.5647 - loss: 0.6192 - mae: 0.6262 - rmse: 0.7721 - smape: 1.0423 - val_ia: 0.2738 - val_loss: 1.1087 - val_mae: 0.8379 - val_rmse: 0.9208 - val_smape: 1.1956

Epoch 2/16

1146/1146 - 8s - 7ms/step - ia: 0.6527 - loss: 0.4018 - mae: 0.5048 - rmse: 0.6290 - smape: 0.8960 - val_ia: 0.2994 - val_loss: 1.0034 - val_mae: 0.7742 - val_rmse: 0.8597 - val_smape: 1.1463

Epoch 3/16

1146/1146 - 6s - 5ms/step - ia: 0.6815 - loss: 0.3443 - mae: 0.4666 - rmse: 0.5820 - smape: 0.8544 - val_ia: 0.3136 - val_loss: 1.0180 - val_mae: 0.7657 - val_rmse: 0.8564 - val_smape: 1.1519

Epoch 4/16

1146/1146 - 5s - 5ms/step - ia: 0.7026 - loss: 0.3072 - mae: 0.4382 - rmse: 0.5490 - smape: 0.8209 - val_ia: 0.3247 - val_loss: 0.9703 - val_mae: 0.7419 - val_rmse: 0.8360 - val_smape: 1.1680

Epoch 5/16

1146/1146 - 5s - 4ms/step - ia: 0.7195 - loss: 0.2797 - mae: 0.4162 - rmse: 0.5243 - smape: 0.7983 - val_ia: 0.3410 - val_loss: 0.9097 - val_mae: 0.7128 - val_rmse: 0.8083 - val_smape: 1.1567

Epoch 6/16

1146/1146 - 4s - 3ms/step - ia: 0.7312 - loss: 0.2601 - mae: 0.4007 - rmse: 0.5057 - smape: 0.7745 - val_ia: 0.3506 - val_loss: 0.7561 - val_mae: 0.6567 - val_rmse: 0.7452 - val_smape: 1.1675

Epoch 7/16

1146/1146 - 4s - 4ms/step - ia: 0.7424 - loss: 0.2424 - mae: 0.3861 - rmse: 0.4877 - smape: 0.7605 - val_ia: 0.3602 - val_loss: 0.7067 - val_mae: 0.6331 - val_rmse: 0.7212 - val_smape: 1.1548

Epoch 8/16

1146/1146 - 5s - 4ms/step - ia: 0.7518 - loss: 0.2267 - mae: 0.3728 - rmse: 0.4715 - smape: 0.7472 - val_ia: 0.3652 - val_loss: 0.6396 - val_mae: 0.6031 - val_rmse: 0.6883 - val_smape: 1.1370

Epoch 9/16

1146/1146 - 3s - 2ms/step - ia: 0.7600 - loss: 0.2136 - mae: 0.3613 - rmse: 0.4580 - smape: 0.7310 - val_ia: 0.3639 - val_loss: 0.5941 - val_mae: 0.5898 - val_rmse: 0.6691 - val_smape: 1.1317

Epoch 10/16

1146/1146 - 4s - 3ms/step - ia: 0.7655 - loss: 0.2054 - mae: 0.3543 - rmse: 0.4491 - smape: 0.7259 - val_ia: 0.3729 - val_loss: 0.5588 - val_mae: 0.5713 - val_rmse: 0.6490 - val_smape: 1.1105

Epoch 11/16

1146/1146 - 3s - 3ms/step - ia: 0.7711 - loss: 0.1968 - mae: 0.3465 - rmse: 0.4394 - smape: 0.7130 - val_ia: 0.3840 - val_loss: 0.4828 - val_mae: 0.5354 - val_rmse: 0.6082 - val_smape: 1.0757

Epoch 12/16

1146/1146 - 3s - 3ms/step - ia: 0.7765 - loss: 0.1898 - mae: 0.3387 - rmse: 0.4312 - smape: 0.7047 - val_ia: 0.3902 - val_loss: 0.4244 - val_mae: 0.5056 - val_rmse: 0.5761 - val_smape: 1.0415

Epoch 13/16

1146/1146 - 4s - 3ms/step - ia: 0.7807 - loss: 0.1842 - mae: 0.3328 - rmse: 0.4245 - smape: 0.6956 - val_ia: 0.3966 - val_loss: 0.3983 - val_mae: 0.4923 - val_rmse: 0.5619 - val_smape: 1.0344

Epoch 14/16

1146/1146 - 4s - 4ms/step - ia: 0.7839 - loss: 0.1783 - mae: 0.3282 - rmse: 0.4177 - smape: 0.6916 - val_ia: 0.3949 - val_loss: 0.3831 - val_mae: 0.4839 - val_rmse: 0.5526 - val_smape: 1.0215

Epoch 15/16

1146/1146 - 5s - 4ms/step - ia: 0.7867 - loss: 0.1747 - mae: 0.3245 - rmse: 0.4137 - smape: 0.6824 - val_ia: 0.4031 - val_loss: 0.3691 - val_mae: 0.4747 - val_rmse: 0.5414 - val_smape: 1.0027

Epoch 16/16

1146/1146 - 4s - 4ms/step - ia: 0.7885 - loss: 0.1718 - mae: 0.3218 - rmse: 0.4102 - smape: 0.6829 - val_ia: 0.4056 - val_loss: 0.3569 - val_mae: 0.4672 - val_rmse: 0.5345 - val_smape: 0.9921

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 47s 294ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 20%|██        | 10/50 [24:19<1:34:00, 141.01s/trial, best loss: 0.30989160951024364]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 9s - 30ms/step - ia: 0.2250 - loss: 6.9964 - mae: 1.9878 - rmse: 2.6359 - smape: 1.5229 - val_ia: 0.2378 - val_loss: 2.5287 - val_mae: 1.3618 - val_rmse: 1.5777 - val_smape: 1.5214

Epoch 2/8

287/287 - 1s - 4ms/step - ia: 0.2265 - loss: 6.8091 - mae: 1.9657 - rmse: 2.5991 - smape: 1.5221 - val_ia: 0.2398 - val_loss: 2.4632 - val_mae: 1.3418 - val_rmse: 1.5564 - val_smape: 1.5189

Epoch 3/8

287/287 - 1s - 3ms/step - ia: 0.2284 - loss: 6.6889 - mae: 1.9546 - rmse: 2.5768 - smape: 1.5229 - val_ia: 0.2417 - val_loss: 2.4009 - val_mae: 1.3224 - val_rmse: 1.5359 - val_smape: 1.5169

Epoch 4/8

287/287 - 1s - 3ms/step - ia: 0.2306 - loss: 6.4590 - mae: 1.9233 - rmse: 2.5328 - smape: 1.5209 - val_ia: 0.2436 - val_loss: 2.3429 - val_mae: 1.3040 - val_rmse: 1.5165 - val_smape: 1.5139

Epoch 5/8

287/287 - 2s - 7ms/step - ia: 0.2333 - loss: 6.2130 - mae: 1.8895 - rmse: 2.4856 - smape: 1.5201 - val_ia: 0.2455 - val_loss: 2.2889 - val_mae: 1.2867 - val_rmse: 1.4982 - val_smape: 1.5107

Epoch 6/8

287/287 - 2s - 7ms/step - ia: 0.2354 - loss: 5.9864 - mae: 1.8649 - rmse: 2.4396 - smape: 1.5155 - val_ia: 0.2472 - val_loss: 2.2379 - val_mae: 1.2702 - val_rmse: 1.4807 - val_smape: 1.5083

Epoch 7/8

287/287 - 3s - 10ms/step - ia: 0.2372 - loss: 5.9224 - mae: 1.8474 - rmse: 2.4262 - smape: 1.5158 - val_ia: 0.2491 - val_loss: 2.1879 - val_mae: 1.2538 - val_rmse: 1.4633 - val_smape: 1.5062

Epoch 8/8

287/287 - 2s - 7ms/step - ia: 0.2401 - loss: 5.7433 - mae: 1.8213 - rmse: 2.3882 - smape: 1.5088 - val_ia: 0.2508 - val_loss: 2.1418 - val_mae: 1.2384 - val_rmse: 1.4471 - val_smape: 1.5040

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 43s 271ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 22%|██▏       | 11/50 [24:42<1:08:02, 104.69s/trial, best loss: 0.30989160951024364]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1146/1146 - 12s - 11ms/step - ia: 0.5547 - loss: 0.6211 - mae: 0.6296 - rmse: 0.7794 - smape: 1.0552 - val_ia: 0.2252 - val_loss: 1.5526 - val_mae: 1.0554 - val_rmse: 1.1318 - val_smape: 1.3861

Epoch 2/128

1146/1146 - 5s - 5ms/step - ia: 0.6046 - loss: 0.5097 - mae: 0.5698 - rmse: 0.7081 - smape: 0.9742 - val_ia: 0.2340 - val_loss: 1.3379 - val_mae: 0.9704 - val_rmse: 1.0455 - val_smape: 1.3470

Epoch 3/128

1146/1146 - 3s - 3ms/step - ia: 0.6269 - loss: 0.4532 - mae: 0.5383 - rmse: 0.6681 - smape: 0.9353 - val_ia: 0.2381 - val_loss: 1.3358 - val_mae: 0.9627 - val_rmse: 1.0399 - val_smape: 1.3362

Epoch 4/128

1146/1146 - 3s - 3ms/step - ia: 0.6459 - loss: 0.4169 - mae: 0.5150 - rmse: 0.6407 - smape: 0.9093 - val_ia: 0.2516 - val_loss: 1.1778 - val_mae: 0.8873 - val_rmse: 0.9638 - val_smape: 1.3021

Epoch 5/128

1146/1146 - 5s - 4ms/step - ia: 0.6615 - loss: 0.3853 - mae: 0.4936 - rmse: 0.6156 - smape: 0.8870 - val_ia: 0.2685 - val_loss: 1.0533 - val_mae: 0.8280 - val_rmse: 0.9052 - val_smape: 1.2758

Epoch 6/128

1146/1146 - 5s - 4ms/step - ia: 0.6788 - loss: 0.3558 - mae: 0.4722 - rmse: 0.5909 - smape: 0.8630 - val_ia: 0.2738 - val_loss: 1.0870 - val_mae: 0.8265 - val_rmse: 0.9081 - val_smape: 1.2583

Epoch 7/128

1146/1146 - 4s - 4ms/step - ia: 0.6902 - loss: 0.3365 - mae: 0.4587 - rmse: 0.5751 - smape: 0.8475 - val_ia: 0.2892 - val_loss: 0.9830 - val_mae: 0.7755 - val_rmse: 0.8601 - val_smape: 1.2284

Epoch 8/128

1146/1146 - 4s - 4ms/step - ia: 0.6988 - loss: 0.3203 - mae: 0.4462 - rmse: 0.5608 - smape: 0.8302 - val_ia: 0.2979 - val_loss: 0.9730 - val_mae: 0.7627 - val_rmse: 0.8504 - val_smape: 1.2076

Epoch 9/128

1146/1146 - 3s - 3ms/step - ia: 0.7104 - loss: 0.3043 - mae: 0.4329 - rmse: 0.5469 - smape: 0.8152 - val_ia: 0.3110 - val_loss: 0.8639 - val_mae: 0.7127 - val_rmse: 0.8018 - val_smape: 1.1767

Epoch 10/128

1146/1146 - 6s - 5ms/step - ia: 0.7133 - loss: 0.2952 - mae: 0.4279 - rmse: 0.5385 - smape: 0.8094 - val_ia: 0.3097 - val_loss: 0.9147 - val_mae: 0.7308 - val_rmse: 0.8202 - val_smape: 1.1805

Epoch 11/128

1146/1146 - 4s - 3ms/step - ia: 0.7201 - loss: 0.2862 - mae: 0.4205 - rmse: 0.5298 - smape: 0.8007 - val_ia: 0.3171 - val_loss: 0.8957 - val_mae: 0.7163 - val_rmse: 0.8077 - val_smape: 1.1618

Epoch 12/128

1146/1146 - 4s - 3ms/step - ia: 0.7233 - loss: 0.2819 - mae: 0.4160 - rmse: 0.5253 - smape: 0.7917 - val_ia: 0.3192 - val_loss: 0.8596 - val_mae: 0.7006 - val_rmse: 0.7929 - val_smape: 1.1528

Epoch 13/128

1146/1146 - 5s - 4ms/step - ia: 0.7258 - loss: 0.2759 - mae: 0.4121 - rmse: 0.5206 - smape: 0.7891 - val_ia: 0.3189 - val_loss: 0.8751 - val_mae: 0.7103 - val_rmse: 0.8001 - val_smape: 1.1560

Epoch 14/128

1146/1146 - 3s - 3ms/step - ia: 0.7330 - loss: 0.2659 - mae: 0.4029 - rmse: 0.5108 - smape: 0.7750 - val_ia: 0.3235 - val_loss: 0.8483 - val_mae: 0.6940 - val_rmse: 0.7867 - val_smape: 1.1421

Epoch 15/128

1146/1146 - 5s - 5ms/step - ia: 0.7359 - loss: 0.2606 - mae: 0.3989 - rmse: 0.5052 - smape: 0.7699 - val_ia: 0.3314 - val_loss: 0.7843 - val_mae: 0.6691 - val_rmse: 0.7585 - val_smape: 1.1367

Epoch 16/128

1146/1146 - 8s - 7ms/step - ia: 0.7383 - loss: 0.2563 - mae: 0.3956 - rmse: 0.5018 - smape: 0.7683 - val_ia: 0.3343 - val_loss: 0.7905 - val_mae: 0.6682 - val_rmse: 0.7593 - val_smape: 1.1233

Epoch 17/128

1146/1146 - 5s - 4ms/step - ia: 0.7412 - loss: 0.2517 - mae: 0.3922 - rmse: 0.4968 - smape: 0.7655 - val_ia: 0.3376 - val_loss: 0.7763 - val_mae: 0.6643 - val_rmse: 0.7532 - val_smape: 1.1250

Epoch 18/128

1146/1146 - 3s - 3ms/step - ia: 0.7435 - loss: 0.2480 - mae: 0.3883 - rmse: 0.4933 - smape: 0.7550 - val_ia: 0.3371 - val_loss: 0.7832 - val_mae: 0.6683 - val_rmse: 0.7565 - val_smape: 1.1267

Epoch 19/128

1146/1146 - 9s - 8ms/step - ia: 0.7460 - loss: 0.2426 - mae: 0.3854 - rmse: 0.4881 - smape: 0.7540 - val_ia: 0.3439 - val_loss: 0.7433 - val_mae: 0.6484 - val_rmse: 0.7370 - val_smape: 1.1161

Epoch 20/128

1146/1146 - 10s - 8ms/step - ia: 0.7481 - loss: 0.2399 - mae: 0.3819 - rmse: 0.4849 - smape: 0.7510 - val_ia: 0.3468 - val_loss: 0.7399 - val_mae: 0.6450 - val_rmse: 0.7338 - val_smape: 1.1117

Epoch 21/128

1146/1146 - 11s - 9ms/step - ia: 0.7500 - loss: 0.2373 - mae: 0.3792 - rmse: 0.4823 - smape: 0.7460 - val_ia: 0.3555 - val_loss: 0.6646 - val_mae: 0.6128 - val_rmse: 0.7011 - val_smape: 1.0926

Epoch 22/128

1146/1146 - 5s - 5ms/step - ia: 0.7512 - loss: 0.2333 - mae: 0.3770 - rmse: 0.4783 - smape: 0.7464 - val_ia: 0.3564 - val_loss: 0.6710 - val_mae: 0.6180 - val_rmse: 0.7035 - val_smape: 1.0996

Epoch 23/128

1146/1146 - 5s - 4ms/step - ia: 0.7537 - loss: 0.2305 - mae: 0.3746 - rmse: 0.4756 - smape: 0.7407 - val_ia: 0.3613 - val_loss: 0.6318 - val_mae: 0.6006 - val_rmse: 0.6855 - val_smape: 1.0931

Epoch 24/128

1146/1146 - 6s - 5ms/step - ia: 0.7564 - loss: 0.2278 - mae: 0.3709 - rmse: 0.4725 - smape: 0.7404 - val_ia: 0.3647 - val_loss: 0.6247 - val_mae: 0.5942 - val_rmse: 0.6806 - val_smape: 1.0826

Epoch 25/128

1146/1146 - 6s - 5ms/step - ia: 0.7569 - loss: 0.2251 - mae: 0.3698 - rmse: 0.4696 - smape: 0.7352 - val_ia: 0.3668 - val_loss: 0.6145 - val_mae: 0.5889 - val_rmse: 0.6752 - val_smape: 1.0812

Epoch 26/128

1146/1146 - 11s - 9ms/step - ia: 0.7591 - loss: 0.2218 - mae: 0.3670 - rmse: 0.4668 - smape: 0.7335 - val_ia: 0.3699 - val_loss: 0.5975 - val_mae: 0.5831 - val_rmse: 0.6669 - val_smape: 1.0749

Epoch 27/128

1146/1146 - 6s - 5ms/step - ia: 0.7602 - loss: 0.2204 - mae: 0.3657 - rmse: 0.4646 - smape: 0.7311 - val_ia: 0.3701 - val_loss: 0.5828 - val_mae: 0.5750 - val_rmse: 0.6602 - val_smape: 1.0682

Epoch 28/128

1146/1146 - 10s - 9ms/step - ia: 0.7614 - loss: 0.2178 - mae: 0.3639 - rmse: 0.4621 - smape: 0.7284 - val_ia: 0.3741 - val_loss: 0.5860 - val_mae: 0.5765 - val_rmse: 0.6607 - val_smape: 1.0686

Epoch 29/128

1146/1146 - 12s - 11ms/step - ia: 0.7633 - loss: 0.2160 - mae: 0.3626 - rmse: 0.4602 - smape: 0.7276 - val_ia: 0.3713 - val_loss: 0.6059 - val_mae: 0.5857 - val_rmse: 0.6710 - val_smape: 1.0703

Epoch 30/128

1146/1146 - 8s - 7ms/step - ia: 0.7644 - loss: 0.2122 - mae: 0.3592 - rmse: 0.4561 - smape: 0.7242 - val_ia: 0.3790 - val_loss: 0.5317 - val_mae: 0.5535 - val_rmse: 0.6346 - val_smape: 1.0629

Epoch 31/128

1146/1146 - 6s - 5ms/step - ia: 0.7651 - loss: 0.2110 - mae: 0.3588 - rmse: 0.4550 - smape: 0.7244 - val_ia: 0.3821 - val_loss: 0.5223 - val_mae: 0.5474 - val_rmse: 0.6288 - val_smape: 1.0554

Epoch 32/128

1146/1146 - 11s - 10ms/step - ia: 0.7669 - loss: 0.2097 - mae: 0.3567 - rmse: 0.4535 - smape: 0.7163 - val_ia: 0.3837 - val_loss: 0.5058 - val_mae: 0.5398 - val_rmse: 0.6198 - val_smape: 1.0520

Epoch 33/128

1146/1146 - 11s - 10ms/step - ia: 0.7680 - loss: 0.2087 - mae: 0.3547 - rmse: 0.4522 - smape: 0.7184 - val_ia: 0.3844 - val_loss: 0.5278 - val_mae: 0.5508 - val_rmse: 0.6310 - val_smape: 1.0539

Epoch 34/128

1146/1146 - 7s - 6ms/step - ia: 0.7694 - loss: 0.2058 - mae: 0.3528 - rmse: 0.4487 - smape: 0.7135 - val_ia: 0.3889 - val_loss: 0.5001 - val_mae: 0.5358 - val_rmse: 0.6163 - val_smape: 1.0398

Epoch 35/128

1146/1146 - 5s - 5ms/step - ia: 0.7696 - loss: 0.2043 - mae: 0.3524 - rmse: 0.4477 - smape: 0.7157 - val_ia: 0.3893 - val_loss: 0.5189 - val_mae: 0.5447 - val_rmse: 0.6249 - val_smape: 1.0431

Epoch 36/128

1146/1146 - 11s - 9ms/step - ia: 0.7723 - loss: 0.2002 - mae: 0.3487 - rmse: 0.4430 - smape: 0.7091 - val_ia: 0.3938 - val_loss: 0.4867 - val_mae: 0.5307 - val_rmse: 0.6080 - val_smape: 1.0397

Epoch 37/128

1146/1146 - 11s - 9ms/step - ia: 0.7720 - loss: 0.2021 - mae: 0.3494 - rmse: 0.4451 - smape: 0.7103 - val_ia: 0.3923 - val_loss: 0.4718 - val_mae: 0.5216 - val_rmse: 0.6006 - val_smape: 1.0304

Epoch 38/128

1146/1146 - 6s - 5ms/step - ia: 0.7731 - loss: 0.1982 - mae: 0.3471 - rmse: 0.4409 - smape: 0.7086 - val_ia: 0.3957 - val_loss: 0.4748 - val_mae: 0.5212 - val_rmse: 0.6014 - val_smape: 1.0264

Epoch 39/128

1146/1146 - 11s - 10ms/step - ia: 0.7743 - loss: 0.1967 - mae: 0.3454 - rmse: 0.4393 - smape: 0.7041 - val_ia: 0.3971 - val_loss: 0.4762 - val_mae: 0.5236 - val_rmse: 0.6015 - val_smape: 1.0267

Epoch 40/128

1146/1146 - 8s - 7ms/step - ia: 0.7752 - loss: 0.1949 - mae: 0.3447 - rmse: 0.4373 - smape: 0.7049 - val_ia: 0.4029 - val_loss: 0.4258 - val_mae: 0.5007 - val_rmse: 0.5732 - val_smape: 1.0117

Epoch 41/128

1146/1146 - 6s - 5ms/step - ia: 0.7760 - loss: 0.1948 - mae: 0.3429 - rmse: 0.4369 - smape: 0.7033 - val_ia: 0.4067 - val_loss: 0.4219 - val_mae: 0.4964 - val_rmse: 0.5694 - val_smape: 1.0021

Epoch 42/128

1146/1146 - 4s - 3ms/step - ia: 0.7766 - loss: 0.1932 - mae: 0.3428 - rmse: 0.4354 - smape: 0.7027 - val_ia: 0.4040 - val_loss: 0.4053 - val_mae: 0.4899 - val_rmse: 0.5623 - val_smape: 1.0072

Epoch 43/128

1146/1146 - 3s - 3ms/step - ia: 0.7778 - loss: 0.1919 - mae: 0.3409 - rmse: 0.4336 - smape: 0.7008 - val_ia: 0.4093 - val_loss: 0.4148 - val_mae: 0.4921 - val_rmse: 0.5658 - val_smape: 0.9982

Epoch 44/128

1146/1146 - 3s - 3ms/step - ia: 0.7785 - loss: 0.1906 - mae: 0.3395 - rmse: 0.4322 - smape: 0.6979 - val_ia: 0.4106 - val_loss: 0.4227 - val_mae: 0.4978 - val_rmse: 0.5699 - val_smape: 1.0031

Epoch 45/128

1146/1146 - 6s - 5ms/step - ia: 0.7794 - loss: 0.1896 - mae: 0.3384 - rmse: 0.4308 - smape: 0.6953 - val_ia: 0.4124 - val_loss: 0.4014 - val_mae: 0.4846 - val_rmse: 0.5577 - val_smape: 0.9927

Epoch 46/128

1146/1146 - 6s - 5ms/step - ia: 0.7806 - loss: 0.1870 - mae: 0.3369 - rmse: 0.4282 - smape: 0.6963 - val_ia: 0.4122 - val_loss: 0.3772 - val_mae: 0.4738 - val_rmse: 0.5446 - val_smape: 0.9938

Epoch 47/128

1146/1146 - 5s - 4ms/step - ia: 0.7802 - loss: 0.1876 - mae: 0.3373 - rmse: 0.4286 - smape: 0.6947 - val_ia: 0.4151 - val_loss: 0.3797 - val_mae: 0.4744 - val_rmse: 0.5452 - val_smape: 0.9804

Epoch 48/128

1146/1146 - 5s - 4ms/step - ia: 0.7823 - loss: 0.1857 - mae: 0.3352 - rmse: 0.4264 - smape: 0.6925 - val_ia: 0.4175 - val_loss: 0.3629 - val_mae: 0.4641 - val_rmse: 0.5341 - val_smape: 0.9714

Epoch 49/128

1146/1146 - 4s - 4ms/step - ia: 0.7837 - loss: 0.1828 - mae: 0.3325 - rmse: 0.4228 - smape: 0.6894 - val_ia: 0.4199 - val_loss: 0.3717 - val_mae: 0.4682 - val_rmse: 0.5389 - val_smape: 0.9668

Epoch 50/128

1146/1146 - 5s - 4ms/step - ia: 0.7846 - loss: 0.1810 - mae: 0.3311 - rmse: 0.4214 - smape: 0.6889 - val_ia: 0.4195 - val_loss: 0.3821 - val_mae: 0.4735 - val_rmse: 0.5443 - val_smape: 0.9703

Epoch 51/128

1146/1146 - 5s - 4ms/step - ia: 0.7858 - loss: 0.1798 - mae: 0.3295 - rmse: 0.4198 - smape: 0.6840 - val_ia: 0.4200 - val_loss: 0.3523 - val_mae: 0.4592 - val_rmse: 0.5277 - val_smape: 0.9589

Epoch 52/128

1146/1146 - 3s - 3ms/step - ia: 0.7853 - loss: 0.1803 - mae: 0.3303 - rmse: 0.4204 - smape: 0.6865 - val_ia: 0.4272 - val_loss: 0.3443 - val_mae: 0.4545 - val_rmse: 0.5205 - val_smape: 0.9425

Epoch 53/128

1146/1146 - 6s - 6ms/step - ia: 0.7872 - loss: 0.1779 - mae: 0.3280 - rmse: 0.4175 - smape: 0.6840 - val_ia: 0.4268 - val_loss: 0.3375 - val_mae: 0.4494 - val_rmse: 0.5161 - val_smape: 0.9421

Epoch 54/128

1146/1146 - 5s - 4ms/step - ia: 0.7864 - loss: 0.1781 - mae: 0.3286 - rmse: 0.4179 - smape: 0.6841 - val_ia: 0.4264 - val_loss: 0.3321 - val_mae: 0.4458 - val_rmse: 0.5136 - val_smape: 0.9444

Epoch 55/128

1146/1146 - 5s - 4ms/step - ia: 0.7877 - loss: 0.1772 - mae: 0.3269 - rmse: 0.4169 - smape: 0.6820 - val_ia: 0.4305 - val_loss: 0.3041 - val_mae: 0.4300 - val_rmse: 0.4945 - val_smape: 0.9234

Epoch 56/128

1146/1146 - 5s - 4ms/step - ia: 0.7883 - loss: 0.1758 - mae: 0.3261 - rmse: 0.4152 - smape: 0.6820 - val_ia: 0.4320 - val_loss: 0.3038 - val_mae: 0.4298 - val_rmse: 0.4936 - val_smape: 0.9202

Epoch 57/128

1146/1146 - 3s - 3ms/step - ia: 0.7887 - loss: 0.1752 - mae: 0.3256 - rmse: 0.4144 - smape: 0.6815 - val_ia: 0.4369 - val_loss: 0.3013 - val_mae: 0.4269 - val_rmse: 0.4917 - val_smape: 0.9089

Epoch 58/128

1146/1146 - 4s - 3ms/step - ia: 0.7891 - loss: 0.1738 - mae: 0.3246 - rmse: 0.4128 - smape: 0.6811 - val_ia: 0.4384 - val_loss: 0.2981 - val_mae: 0.4258 - val_rmse: 0.4877 - val_smape: 0.9039

Epoch 59/128

1146/1146 - 6s - 5ms/step - ia: 0.7900 - loss: 0.1726 - mae: 0.3231 - rmse: 0.4110 - smape: 0.6767 - val_ia: 0.4321 - val_loss: 0.3006 - val_mae: 0.4277 - val_rmse: 0.4923 - val_smape: 0.9240

Epoch 60/128

1146/1146 - 5s - 4ms/step - ia: 0.7896 - loss: 0.1727 - mae: 0.3238 - rmse: 0.4115 - smape: 0.6805 - val_ia: 0.4371 - val_loss: 0.2948 - val_mae: 0.4231 - val_rmse: 0.4880 - val_smape: 0.9081

Epoch 61/128

1146/1146 - 5s - 4ms/step - ia: 0.7904 - loss: 0.1722 - mae: 0.3227 - rmse: 0.4105 - smape: 0.6783 - val_ia: 0.4402 - val_loss: 0.3071 - val_mae: 0.4309 - val_rmse: 0.4934 - val_smape: 0.9082

Epoch 62/128

1146/1146 - 4s - 4ms/step - ia: 0.7917 - loss: 0.1707 - mae: 0.3220 - rmse: 0.4091 - smape: 0.6776 - val_ia: 0.4397 - val_loss: 0.2712 - val_mae: 0.4082 - val_rmse: 0.4705 - val_smape: 0.8825

Epoch 63/128

1146/1146 - 3s - 3ms/step - ia: 0.7931 - loss: 0.1679 - mae: 0.3190 - rmse: 0.4057 - smape: 0.6730 - val_ia: 0.4384 - val_loss: 0.2670 - val_mae: 0.4073 - val_rmse: 0.4680 - val_smape: 0.8891

Epoch 64/128

1146/1146 - 5s - 4ms/step - ia: 0.7927 - loss: 0.1690 - mae: 0.3195 - rmse: 0.4069 - smape: 0.6709 - val_ia: 0.4422 - val_loss: 0.2661 - val_mae: 0.4054 - val_rmse: 0.4662 - val_smape: 0.8819

Epoch 65/128

1146/1146 - 6s - 5ms/step - ia: 0.7934 - loss: 0.1672 - mae: 0.3181 - rmse: 0.4048 - smape: 0.6690 - val_ia: 0.4483 - val_loss: 0.2595 - val_mae: 0.3991 - val_rmse: 0.4590 - val_smape: 0.8627

Epoch 66/128

1146/1146 - 3s - 3ms/step - ia: 0.7938 - loss: 0.1680 - mae: 0.3183 - rmse: 0.4057 - smape: 0.6735 - val_ia: 0.4499 - val_loss: 0.2546 - val_mae: 0.3953 - val_rmse: 0.4555 - val_smape: 0.8553

Epoch 67/128

1146/1146 - 3s - 3ms/step - ia: 0.7947 - loss: 0.1662 - mae: 0.3166 - rmse: 0.4035 - smape: 0.6694 - val_ia: 0.4474 - val_loss: 0.2704 - val_mae: 0.4068 - val_rmse: 0.4685 - val_smape: 0.8723

Epoch 68/128

1146/1146 - 6s - 5ms/step - ia: 0.7941 - loss: 0.1670 - mae: 0.3177 - rmse: 0.4044 - smape: 0.6685 - val_ia: 0.4463 - val_loss: 0.2582 - val_mae: 0.3990 - val_rmse: 0.4596 - val_smape: 0.8635

Epoch 69/128

1146/1146 - 5s - 4ms/step - ia: 0.7949 - loss: 0.1653 - mae: 0.3160 - rmse: 0.4026 - smape: 0.6686 - val_ia: 0.4503 - val_loss: 0.2536 - val_mae: 0.3955 - val_rmse: 0.4553 - val_smape: 0.8549

Epoch 70/128

1146/1146 - 5s - 4ms/step - ia: 0.7959 - loss: 0.1648 - mae: 0.3154 - rmse: 0.4019 - smape: 0.6668 - val_ia: 0.4465 - val_loss: 0.2566 - val_mae: 0.3986 - val_rmse: 0.4588 - val_smape: 0.8704

Epoch 71/128

1146/1146 - 2s - 2ms/step - ia: 0.7978 - loss: 0.1628 - mae: 0.3125 - rmse: 0.3990 - smape: 0.6626 - val_ia: 0.4489 - val_loss: 0.2563 - val_mae: 0.3972 - val_rmse: 0.4583 - val_smape: 0.8604

Epoch 72/128

1146/1146 - 3s - 3ms/step - ia: 0.7973 - loss: 0.1624 - mae: 0.3130 - rmse: 0.3990 - smape: 0.6656 - val_ia: 0.4557 - val_loss: 0.2390 - val_mae: 0.3851 - val_rmse: 0.4433 - val_smape: 0.8381

Epoch 73/128

1146/1146 - 5s - 5ms/step - ia: 0.7967 - loss: 0.1634 - mae: 0.3143 - rmse: 0.4001 - smape: 0.6650 - val_ia: 0.4573 - val_loss: 0.2347 - val_mae: 0.3817 - val_rmse: 0.4396 - val_smape: 0.8319

Epoch 74/128

1146/1146 - 6s - 5ms/step - ia: 0.7979 - loss: 0.1613 - mae: 0.3124 - rmse: 0.3976 - smape: 0.6625 - val_ia: 0.4593 - val_loss: 0.2217 - val_mae: 0.3723 - val_rmse: 0.4290 - val_smape: 0.8230

Epoch 75/128

1146/1146 - 4s - 4ms/step - ia: 0.7980 - loss: 0.1613 - mae: 0.3119 - rmse: 0.3974 - smape: 0.6614 - val_ia: 0.4528 - val_loss: 0.2430 - val_mae: 0.3881 - val_rmse: 0.4478 - val_smape: 0.8499

Epoch 76/128

1146/1146 - 4s - 4ms/step - ia: 0.7975 - loss: 0.1616 - mae: 0.3126 - rmse: 0.3977 - smape: 0.6636 - val_ia: 0.4593 - val_loss: 0.2383 - val_mae: 0.3843 - val_rmse: 0.4413 - val_smape: 0.8332

Epoch 77/128

1146/1146 - 5s - 4ms/step - ia: 0.7983 - loss: 0.1599 - mae: 0.3111 - rmse: 0.3957 - smape: 0.6627 - val_ia: 0.4548 - val_loss: 0.2382 - val_mae: 0.3847 - val_rmse: 0.4441 - val_smape: 0.8428

Epoch 78/128

1146/1146 - 4s - 4ms/step - ia: 0.7996 - loss: 0.1591 - mae: 0.3096 - rmse: 0.3947 - smape: 0.6589 - val_ia: 0.4556 - val_loss: 0.2368 - val_mae: 0.3842 - val_rmse: 0.4428 - val_smape: 0.8397

Epoch 79/128

1146/1146 - 5s - 4ms/step - ia: 0.8001 - loss: 0.1583 - mae: 0.3092 - rmse: 0.3936 - smape: 0.6614 - val_ia: 0.4608 - val_loss: 0.2351 - val_mae: 0.3826 - val_rmse: 0.4388 - val_smape: 0.8298

Epoch 80/128

1146/1146 - 3s - 3ms/step - ia: 0.7999 - loss: 0.1575 - mae: 0.3084 - rmse: 0.3927 - smape: 0.6566 - val_ia: 0.4638 - val_loss: 0.2305 - val_mae: 0.3778 - val_rmse: 0.4354 - val_smape: 0.8194

Epoch 81/128

1146/1146 - 3s - 2ms/step - ia: 0.8002 - loss: 0.1580 - mae: 0.3084 - rmse: 0.3935 - smape: 0.6571 - val_ia: 0.4692 - val_loss: 0.2004 - val_mae: 0.3554 - val_rmse: 0.4103 - val_smape: 0.7978

Epoch 82/128

1146/1146 - 4s - 4ms/step - ia: 0.8016 - loss: 0.1565 - mae: 0.3068 - rmse: 0.3914 - smape: 0.6537 - val_ia: 0.4658 - val_loss: 0.2157 - val_mae: 0.3678 - val_rmse: 0.4238 - val_smape: 0.8095

Epoch 83/128

1146/1146 - 4s - 4ms/step - ia: 0.7998 - loss: 0.1581 - mae: 0.3098 - rmse: 0.3937 - smape: 0.6602 - val_ia: 0.4689 - val_loss: 0.2096 - val_mae: 0.3632 - val_rmse: 0.4185 - val_smape: 0.8038

Epoch 84/128

1146/1146 - 5s - 5ms/step - ia: 0.8014 - loss: 0.1552 - mae: 0.3063 - rmse: 0.3900 - smape: 0.6575 - val_ia: 0.4715 - val_loss: 0.2061 - val_mae: 0.3595 - val_rmse: 0.4147 - val_smape: 0.7975

Epoch 85/128

1146/1146 - 5s - 5ms/step - ia: 0.8029 - loss: 0.1541 - mae: 0.3046 - rmse: 0.3883 - smape: 0.6524 - val_ia: 0.4688 - val_loss: 0.2043 - val_mae: 0.3579 - val_rmse: 0.4136 - val_smape: 0.7982

Epoch 86/128

1146/1146 - 6s - 6ms/step - ia: 0.8031 - loss: 0.1541 - mae: 0.3048 - rmse: 0.3886 - smape: 0.6534 - val_ia: 0.4723 - val_loss: 0.1971 - val_mae: 0.3531 - val_rmse: 0.4081 - val_smape: 0.7918

Epoch 87/128

1146/1146 - 4s - 3ms/step - ia: 0.8034 - loss: 0.1530 - mae: 0.3036 - rmse: 0.3870 - smape: 0.6502 - val_ia: 0.4753 - val_loss: 0.1955 - val_mae: 0.3517 - val_rmse: 0.4068 - val_smape: 0.7873

Epoch 88/128

1146/1146 - 4s - 3ms/step - ia: 0.8045 - loss: 0.1527 - mae: 0.3026 - rmse: 0.3869 - smape: 0.6490 - val_ia: 0.4680 - val_loss: 0.2043 - val_mae: 0.3590 - val_rmse: 0.4153 - val_smape: 0.8007

Epoch 89/128

1146/1146 - 5s - 4ms/step - ia: 0.8035 - loss: 0.1531 - mae: 0.3043 - rmse: 0.3869 - smape: 0.6528 - val_ia: 0.4703 - val_loss: 0.2043 - val_mae: 0.3583 - val_rmse: 0.4147 - val_smape: 0.7979

Epoch 90/128

1146/1146 - 4s - 3ms/step - ia: 0.8042 - loss: 0.1528 - mae: 0.3031 - rmse: 0.3867 - smape: 0.6514 - val_ia: 0.4726 - val_loss: 0.1933 - val_mae: 0.3497 - val_rmse: 0.4053 - val_smape: 0.7826

Epoch 91/128

1146/1146 - 4s - 3ms/step - ia: 0.8035 - loss: 0.1525 - mae: 0.3039 - rmse: 0.3867 - smape: 0.6517 - val_ia: 0.4734 - val_loss: 0.1950 - val_mae: 0.3516 - val_rmse: 0.4069 - val_smape: 0.7882

Epoch 92/128

1146/1146 - 4s - 4ms/step - ia: 0.8059 - loss: 0.1500 - mae: 0.3006 - rmse: 0.3834 - smape: 0.6469 - val_ia: 0.4741 - val_loss: 0.1940 - val_mae: 0.3503 - val_rmse: 0.4053 - val_smape: 0.7842

Epoch 93/128

1146/1146 - 4s - 4ms/step - ia: 0.8048 - loss: 0.1505 - mae: 0.3019 - rmse: 0.3840 - smape: 0.6496 - val_ia: 0.4783 - val_loss: 0.1873 - val_mae: 0.3451 - val_rmse: 0.3996 - val_smape: 0.7765

Epoch 94/128

1146/1146 - 5s - 5ms/step - ia: 0.8048 - loss: 0.1510 - mae: 0.3022 - rmse: 0.3847 - smape: 0.6508 - val_ia: 0.4738 - val_loss: 0.1936 - val_mae: 0.3501 - val_rmse: 0.4055 - val_smape: 0.7892

Epoch 95/128

1146/1146 - 5s - 4ms/step - ia: 0.8046 - loss: 0.1515 - mae: 0.3022 - rmse: 0.3849 - smape: 0.6510 - val_ia: 0.4772 - val_loss: 0.1893 - val_mae: 0.3461 - val_rmse: 0.4006 - val_smape: 0.7798

Epoch 96/128

1146/1146 - 4s - 4ms/step - ia: 0.8051 - loss: 0.1497 - mae: 0.3010 - rmse: 0.3828 - smape: 0.6491 - val_ia: 0.4781 - val_loss: 0.1903 - val_mae: 0.3467 - val_rmse: 0.4002 - val_smape: 0.7731

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 11s - 37ms/step - ia: 0.5129 - loss: 1.1154 - mae: 0.7758 - rmse: 0.9791 - smape: 1.1236 - val_ia: 0.4140 - val_loss: 1.3270 - val_mae: 0.9740 - val_rmse: 1.1098 - val_smape: 1.3523

Epoch 2/16

287/287 - 4s - 14ms/step - ia: 0.5772 - loss: 0.5600 - mae: 0.5957 - rmse: 0.7468 - smape: 1.0225 - val_ia: 0.4091 - val_loss: 1.3535 - val_mae: 0.9934 - val_rmse: 1.1138 - val_smape: 1.3749

Epoch 3/16

287/287 - 2s - 8ms/step - ia: 0.5903 - loss: 0.5246 - mae: 0.5766 - rmse: 0.7231 - smape: 1.0004 - val_ia: 0.4126 - val_loss: 1.3878 - val_mae: 1.0012 - val_rmse: 1.1306 - val_smape: 1.3607

Epoch 4/16

287/287 - 1s - 4ms/step - ia: 0.5947 - loss: 0.5140 - mae: 0.5697 - rmse: 0.7155 - smape: 0.9908 - val_ia: 0.4095 - val_loss: 1.4580 - val_mae: 1.0231 - val_rmse: 1.1531 - val_smape: 1.3675

Epoch 5/16

287/287 - 1s - 5ms/step - ia: 0.5997 - loss: 0.5007 - mae: 0.5631 - rmse: 0.7062 - smape: 0.9804 - val_ia: 0.4150 - val_loss: 1.3927 - val_mae: 1.0023 - val_rmse: 1.1265 - val_smape: 1.3592

Epoch 6/16

287/287 - 1s - 5ms/step - ia: 0.6006 - loss: 0.4985 - mae: 0.5617 - rmse: 0.7047 - smape: 0.9797 - val_ia: 0.4167 - val_loss: 1.4170 - val_mae: 1.0068 - val_rmse: 1.1357 - val_smape: 1.3512

Epoch 7/16

287/287 - 2s - 5ms/step - ia: 0.6030 - loss: 0.4942 - mae: 0.5590 - rmse: 0.7015 - smape: 0.9755 - val_ia: 0.4199 - val_loss: 1.4486 - val_mae: 1.0054 - val_rmse: 1.1496 - val_smape: 1.3303

Epoch 8/16

287/287 - 2s - 9ms/step - ia: 0.6043 - loss: 0.4930 - mae: 0.5578 - rmse: 0.7009 - smape: 0.9734 - val_ia: 0.4135 - val_loss: 1.3949 - val_mae: 1.0041 - val_rmse: 1.1307 - val_smape: 1.3593

Epoch 9/16

287/287 - 1s - 4ms/step - ia: 0.6047 - loss: 0.4901 - mae: 0.5567 - rmse: 0.6991 - smape: 0.9717 - val_ia: 0.4062 - val_loss: 1.5184 - val_mae: 1.0498 - val_rmse: 1.1816 - val_smape: 1.3749

Epoch 10/16

287/287 - 1s - 5ms/step - ia: 0.6061 - loss: 0.4896 - mae: 0.5559 - rmse: 0.6981 - smape: 0.9717 - val_ia: 0.4121 - val_loss: 1.3879 - val_mae: 1.0002 - val_rmse: 1.1247 - val_smape: 1.3658

Epoch 11/16

287/287 - 2s - 6ms/step - ia: 0.6063 - loss: 0.4868 - mae: 0.5546 - rmse: 0.6963 - smape: 0.9693 - val_ia: 0.4142 - val_loss: 1.4550 - val_mae: 1.0251 - val_rmse: 1.1516 - val_smape: 1.3589

Epoch 12/16

287/287 - 3s - 9ms/step - ia: 0.6073 - loss: 0.4880 - mae: 0.5544 - rmse: 0.6971 - smape: 0.9677 - val_ia: 0.4171 - val_loss: 1.3512 - val_mae: 0.9855 - val_rmse: 1.1112 - val_smape: 1.3511

Epoch 13/16

287/287 - 2s - 8ms/step - ia: 0.6075 - loss: 0.4853 - mae: 0.5542 - rmse: 0.6950 - smape: 0.9679 - val_ia: 0.4178 - val_loss: 1.4080 - val_mae: 1.0017 - val_rmse: 1.1303 - val_smape: 1.3482

Epoch 14/16

287/287 - 1s - 5ms/step - ia: 0.6082 - loss: 0.4845 - mae: 0.5526 - rmse: 0.6945 - smape: 0.9658 - val_ia: 0.4109 - val_loss: 1.4021 - val_mae: 1.0037 - val_rmse: 1.1350 - val_smape: 1.3640

Epoch 15/16

287/287 - 2s - 6ms/step - ia: 0.6096 - loss: 0.4828 - mae: 0.5521 - rmse: 0.6937 - smape: 0.9643 - val_ia: 0.4210 - val_loss: 1.3064 - val_mae: 0.9665 - val_rmse: 1.0902 - val_smape: 1.3425

Epoch 16/16

287/287 - 3s - 9ms/step - ia: 0.6087 - loss: 0.4835 - mae: 0.5522 - rmse: 0.6939 - smape: 0.9644 - val_ia: 0.4200 - val_loss: 1.3882 - val_mae: 0.9957 - val_rmse: 1.1240 - val_smape: 1.3429

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 18s 116ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 26%|██▌       | 13/50 [36:39<2:07:28, 206.70s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

287/287 - 8s - 27ms/step - ia: 0.3973 - loss: 1.6941 - mae: 1.0242 - rmse: 1.2911 - smape: 1.2987 - val_ia: 0.3827 - val_loss: 1.4352 - val_mae: 1.0457 - val_rmse: 1.1753 - val_smape: 1.4217

Epoch 2/8

287/287 - 1s - 4ms/step - ia: 0.4911 - loss: 1.0639 - mae: 0.8201 - rmse: 1.0282 - smape: 1.1670 - val_ia: 0.3993 - val_loss: 1.4011 - val_mae: 1.0147 - val_rmse: 1.1468 - val_smape: 1.3888

Epoch 3/8

287/287 - 1s - 5ms/step - ia: 0.5216 - loss: 0.8686 - mae: 0.7379 - rmse: 0.9298 - smape: 1.1189 - val_ia: 0.4041 - val_loss: 1.4774 - val_mae: 1.0308 - val_rmse: 1.1698 - val_smape: 1.3752

Epoch 4/8

287/287 - 1s - 5ms/step - ia: 0.5443 - loss: 0.7584 - mae: 0.6888 - rmse: 0.8686 - smape: 1.0834 - val_ia: 0.4007 - val_loss: 1.5373 - val_mae: 1.0539 - val_rmse: 1.1876 - val_smape: 1.3892

Epoch 5/8

287/287 - 2s - 6ms/step - ia: 0.5539 - loss: 0.6920 - mae: 0.6606 - rmse: 0.8301 - smape: 1.0638 - val_ia: 0.4044 - val_loss: 1.5289 - val_mae: 1.0467 - val_rmse: 1.1826 - val_smape: 1.3790

Epoch 6/8

287/287 - 1s - 4ms/step - ia: 0.5657 - loss: 0.6473 - mae: 0.6383 - rmse: 0.8029 - smape: 1.0455 - val_ia: 0.4058 - val_loss: 1.5022 - val_mae: 1.0386 - val_rmse: 1.1702 - val_smape: 1.3783

Epoch 7/8

287/287 - 1s - 4ms/step - ia: 0.5737 - loss: 0.6097 - mae: 0.6198 - rmse: 0.7790 - smape: 1.0301 - val_ia: 0.4027 - val_loss: 1.5710 - val_mae: 1.0640 - val_rmse: 1.1960 - val_smape: 1.3871

Epoch 8/8

287/287 - 1s - 5ms/step - ia: 0.5797 - loss: 0.5840 - mae: 0.6084 - rmse: 0.7627 - smape: 1.0225 - val_ia: 0.4028 - val_loss: 1.5415 - val_mae: 1.0569 - val_rmse: 1.1839 - val_smape: 1.3895

Restoring model weights from the end of the best epoch: 2.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 24s 154ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 28%|██▊       | 14/50 [36:59<1:30:11, 150.33s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 8s - 13ms/step - ia: 0.6249 - loss: 0.4860 - mae: 0.5511 - rmse: 0.6879 - smape: 0.9463 - val_ia: 0.3982 - val_loss: 1.0543 - val_mae: 0.8115 - val_rmse: 0.9338 - val_smape: 1.2535

Epoch 2/16

573/573 - 3s - 5ms/step - ia: 0.6713 - loss: 0.3783 - mae: 0.4863 - rmse: 0.6126 - smape: 0.8747 - val_ia: 0.4090 - val_loss: 1.0054 - val_mae: 0.7850 - val_rmse: 0.9061 - val_smape: 1.2406

Epoch 3/16

573/573 - 5s - 9ms/step - ia: 0.6796 - loss: 0.3621 - mae: 0.4763 - rmse: 0.5993 - smape: 0.8635 - val_ia: 0.4085 - val_loss: 0.8978 - val_mae: 0.7356 - val_rmse: 0.8587 - val_smape: 1.2330

Epoch 4/16

573/573 - 3s - 5ms/step - ia: 0.6856 - loss: 0.3512 - mae: 0.4684 - rmse: 0.5900 - smape: 0.8549 - val_ia: 0.4201 - val_loss: 0.9937 - val_mae: 0.7655 - val_rmse: 0.8931 - val_smape: 1.1945

Epoch 5/16

573/573 - 3s - 5ms/step - ia: 0.6915 - loss: 0.3396 - mae: 0.4607 - rmse: 0.5804 - smape: 0.8466 - val_ia: 0.4275 - val_loss: 0.8353 - val_mae: 0.7017 - val_rmse: 0.8247 - val_smape: 1.2024

Epoch 6/16

573/573 - 2s - 4ms/step - ia: 0.6986 - loss: 0.3284 - mae: 0.4528 - rmse: 0.5705 - smape: 0.8349 - val_ia: 0.4472 - val_loss: 0.8034 - val_mae: 0.6931 - val_rmse: 0.8074 - val_smape: 1.1677

Epoch 7/16

573/573 - 2s - 4ms/step - ia: 0.7045 - loss: 0.3184 - mae: 0.4461 - rmse: 0.5619 - smape: 0.8247 - val_ia: 0.4461 - val_loss: 0.7263 - val_mae: 0.6567 - val_rmse: 0.7744 - val_smape: 1.1567

Epoch 8/16

573/573 - 2s - 4ms/step - ia: 0.7063 - loss: 0.3149 - mae: 0.4432 - rmse: 0.5589 - smape: 0.8212 - val_ia: 0.4652 - val_loss: 0.6506 - val_mae: 0.6315 - val_rmse: 0.7365 - val_smape: 1.1390

Epoch 9/16

573/573 - 3s - 5ms/step - ia: 0.7104 - loss: 0.3070 - mae: 0.4377 - rmse: 0.5516 - smape: 0.8128 - val_ia: 0.4691 - val_loss: 0.6386 - val_mae: 0.6222 - val_rmse: 0.7277 - val_smape: 1.1416

Epoch 10/16

573/573 - 2s - 4ms/step - ia: 0.7120 - loss: 0.3047 - mae: 0.4362 - rmse: 0.5496 - smape: 0.8141 - val_ia: 0.4621 - val_loss: 0.7196 - val_mae: 0.6512 - val_rmse: 0.7638 - val_smape: 1.1372

Epoch 11/16

573/573 - 3s - 5ms/step - ia: 0.7133 - loss: 0.3018 - mae: 0.4343 - rmse: 0.5469 - smape: 0.8138 - val_ia: 0.4711 - val_loss: 0.6911 - val_mae: 0.6373 - val_rmse: 0.7481 - val_smape: 1.1431

Epoch 12/16

573/573 - 3s - 6ms/step - ia: 0.7164 - loss: 0.2973 - mae: 0.4303 - rmse: 0.5431 - smape: 0.8073 - val_ia: 0.4529 - val_loss: 0.7186 - val_mae: 0.6662 - val_rmse: 0.7719 - val_smape: 1.1636

Epoch 13/16

573/573 - 3s - 6ms/step - ia: 0.7175 - loss: 0.2941 - mae: 0.4287 - rmse: 0.5402 - smape: 0.8084 - val_ia: 0.4770 - val_loss: 0.6017 - val_mae: 0.6043 - val_rmse: 0.7068 - val_smape: 1.1226

Epoch 14/16

573/573 - 5s - 8ms/step - ia: 0.7162 - loss: 0.2969 - mae: 0.4309 - rmse: 0.5423 - smape: 0.8066 - val_ia: 0.4684 - val_loss: 0.6926 - val_mae: 0.6502 - val_rmse: 0.7561 - val_smape: 1.1243

Epoch 15/16

573/573 - 3s - 5ms/step - ia: 0.7211 - loss: 0.2897 - mae: 0.4243 - rmse: 0.5360 - smape: 0.7989 - val_ia: 0.4819 - val_loss: 0.6334 - val_mae: 0.6133 - val_rmse: 0.7204 - val_smape: 1.0967

Epoch 16/16

573/573 - 3s - 5ms/step - ia: 0.7200 - loss: 0.2897 - mae: 0.4247 - rmse: 0.5361 - smape: 0.8015 - val_ia: 0.4860 - val_loss: 0.5901 - val_mae: 0.5973 - val_rmse: 0.7000 - val_smape: 1.0950

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 28s 177ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 30%|███       | 15/50 [37:54<1:10:55, 121.58s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 21s - 5ms/step - ia: 0.5348 - loss: 0.5604 - mae: 0.5990 - rmse: 0.7258 - smape: 1.0424 - val_ia: 0.1165 - val_loss: 1.1830 - val_mae: 0.9235 - val_rmse: 0.9415 - val_smape: 1.3704

Epoch 2/256

4584/4584 - 16s - 4ms/step - ia: 0.5414 - loss: 0.5445 - mae: 0.5896 - rmse: 0.7162 - smape: 1.0296 - val_ia: 0.1218 - val_loss: 1.0691 - val_mae: 0.8772 - val_rmse: 0.8964 - val_smape: 1.3602

Epoch 3/256

4584/4584 - 15s - 3ms/step - ia: 0.5409 - loss: 0.5465 - mae: 0.5901 - rmse: 0.7174 - smape: 1.0317 - val_ia: 0.0991 - val_loss: 1.5980 - val_mae: 1.0981 - val_rmse: 1.1227 - val_smape: 1.3994

Epoch 4/256

4584/4584 - 16s - 3ms/step - ia: 0.5440 - loss: 0.5417 - mae: 0.5873 - rmse: 0.7133 - smape: 1.0274 - val_ia: 0.1109 - val_loss: 1.3952 - val_mae: 0.9980 - val_rmse: 1.0207 - val_smape: 1.3456

Epoch 5/256

4584/4584 - 21s - 5ms/step - ia: 0.5423 - loss: 0.5427 - mae: 0.5876 - rmse: 0.7151 - smape: 1.0268 - val_ia: 0.1055 - val_loss: 1.6347 - val_mae: 1.0788 - val_rmse: 1.1043 - val_smape: 1.3520

Epoch 6/256

4584/4584 - 19s - 4ms/step - ia: 0.5385 - loss: 0.5475 - mae: 0.5913 - rmse: 0.7171 - smape: 1.0350 - val_ia: 0.1174 - val_loss: 1.3009 - val_mae: 0.9527 - val_rmse: 0.9742 - val_smape: 1.3222

Epoch 7/256

4584/4584 - 11s - 2ms/step - ia: 0.5411 - loss: 0.5429 - mae: 0.5883 - rmse: 0.7150 - smape: 1.0305 - val_ia: 0.1042 - val_loss: 1.5030 - val_mae: 1.0498 - val_rmse: 1.0710 - val_smape: 1.3890

Epoch 8/256

4584/4584 - 16s - 4ms/step - ia: 0.5444 - loss: 0.5391 - mae: 0.5860 - rmse: 0.7118 - smape: 1.0228 - val_ia: 0.1141 - val_loss: 1.1959 - val_mae: 0.9374 - val_rmse: 0.9554 - val_smape: 1.3974

Epoch 9/256

4584/4584 - 18s - 4ms/step - ia: 0.5439 - loss: 0.5398 - mae: 0.5867 - rmse: 0.7135 - smape: 1.0267 - val_ia: 0.1065 - val_loss: 1.4072 - val_mae: 1.0189 - val_rmse: 1.0393 - val_smape: 1.3938

Epoch 10/256

4584/4584 - 13s - 3ms/step - ia: 0.5435 - loss: 0.5393 - mae: 0.5845 - rmse: 0.7124 - smape: 1.0205 - val_ia: 0.1058 - val_loss: 1.5029 - val_mae: 1.0424 - val_rmse: 1.0650 - val_smape: 1.3715

Epoch 11/256

4584/4584 - 23s - 5ms/step - ia: 0.5434 - loss: 0.5386 - mae: 0.5855 - rmse: 0.7118 - smape: 1.0246 - val_ia: 0.1122 - val_loss: 1.3193 - val_mae: 0.9724 - val_rmse: 0.9925 - val_smape: 1.3630

Epoch 12/256

4584/4584 - 21s - 4ms/step - ia: 0.5421 - loss: 0.5393 - mae: 0.5865 - rmse: 0.7122 - smape: 1.0266 - val_ia: 0.1402 - val_loss: 0.8260 - val_mae: 0.7504 - val_rmse: 0.7687 - val_smape: 1.3480

Epoch 13/256

4584/4584 - 13s - 3ms/step - ia: 0.5429 - loss: 0.5371 - mae: 0.5854 - rmse: 0.7118 - smape: 1.0243 - val_ia: 0.1053 - val_loss: 1.8981 - val_mae: 1.1409 - val_rmse: 1.1707 - val_smape: 1.3194

Epoch 14/256

4584/4584 - 12s - 3ms/step - ia: 0.5392 - loss: 0.5447 - mae: 0.5890 - rmse: 0.7164 - smape: 1.0317 - val_ia: 0.1005 - val_loss: 1.8172 - val_mae: 1.1531 - val_rmse: 1.1762 - val_smape: 1.4003

Epoch 15/256

4584/4584 - 13s - 3ms/step - ia: 0.5446 - loss: 0.5385 - mae: 0.5848 - rmse: 0.7111 - smape: 1.0237 - val_ia: 0.0958 - val_loss: 1.4894 - val_mae: 1.0649 - val_rmse: 1.0902 - val_smape: 1.4031

Epoch 16/256

4584/4584 - 13s - 3ms/step - ia: 0.5423 - loss: 0.5397 - mae: 0.5864 - rmse: 0.7132 - smape: 1.0266 - val_ia: 0.1252 - val_loss: 0.9349 - val_mae: 0.8247 - val_rmse: 0.8424 - val_smape: 1.3724

Epoch 17/256

4584/4584 - 11s - 3ms/step - ia: 0.5425 - loss: 0.5408 - mae: 0.5869 - rmse: 0.7139 - smape: 1.0276 - val_ia: 0.0996 - val_loss: 2.0786 - val_mae: 1.2182 - val_rmse: 1.2453 - val_smape: 1.3737

Epoch 18/256

4584/4584 - 26s - 6ms/step - ia: 0.5436 - loss: 0.5386 - mae: 0.5860 - rmse: 0.7129 - smape: 1.0258 - val_ia: 0.1108 - val_loss: 1.3718 - val_mae: 0.9907 - val_rmse: 1.0144 - val_smape: 1.3422

Epoch 19/256

4584/4584 - 17s - 4ms/step - ia: 0.5432 - loss: 0.5397 - mae: 0.5866 - rmse: 0.7129 - smape: 1.0273 - val_ia: 0.1168 - val_loss: 1.0926 - val_mae: 0.8940 - val_rmse: 0.9130 - val_smape: 1.3695

Epoch 20/256

4584/4584 - 21s - 5ms/step - ia: 0.5466 - loss: 0.5368 - mae: 0.5851 - rmse: 0.7118 - smape: 1.0243 - val_ia: 0.1218 - val_loss: 1.0618 - val_mae: 0.8628 - val_rmse: 0.8864 - val_smape: 1.2706

Epoch 21/256

4584/4584 - 18s - 4ms/step - ia: 0.5417 - loss: 0.5404 - mae: 0.5877 - rmse: 0.7137 - smape: 1.0291 - val_ia: 0.1079 - val_loss: 1.5310 - val_mae: 1.0448 - val_rmse: 1.0687 - val_smape: 1.3626

Epoch 22/256

4584/4584 - 14s - 3ms/step - ia: 0.5436 - loss: 0.5418 - mae: 0.5869 - rmse: 0.7137 - smape: 1.0266 - val_ia: 0.1208 - val_loss: 1.3066 - val_mae: 0.9438 - val_rmse: 0.9678 - val_smape: 1.2735

Epoch 23/256

4584/4584 - 11s - 2ms/step - ia: 0.5448 - loss: 0.5363 - mae: 0.5848 - rmse: 0.7104 - smape: 1.0233 - val_ia: 0.1117 - val_loss: 1.3169 - val_mae: 0.9760 - val_rmse: 0.9961 - val_smape: 1.3726

Epoch 24/256

4584/4584 - 21s - 5ms/step - ia: 0.5416 - loss: 0.5418 - mae: 0.5877 - rmse: 0.7141 - smape: 1.0271 - val_ia: 0.1288 - val_loss: 0.9839 - val_mae: 0.8307 - val_rmse: 0.8494 - val_smape: 1.3413

Epoch 25/256

4584/4584 - 20s - 4ms/step - ia: 0.5405 - loss: 0.5420 - mae: 0.5890 - rmse: 0.7149 - smape: 1.0318 - val_ia: 0.1111 - val_loss: 1.2346 - val_mae: 0.9576 - val_rmse: 0.9789 - val_smape: 1.3732

Epoch 26/256

4584/4584 - 23s - 5ms/step - ia: 0.5419 - loss: 0.5401 - mae: 0.5868 - rmse: 0.7132 - smape: 1.0282 - val_ia: 0.1174 - val_loss: 1.1763 - val_mae: 0.9076 - val_rmse: 0.9336 - val_smape: 1.2849

Epoch 27/256

4584/4584 - 12s - 3ms/step - ia: 0.5424 - loss: 0.5406 - mae: 0.5867 - rmse: 0.7134 - smape: 1.0291 - val_ia: 0.1075 - val_loss: 1.5236 - val_mae: 1.0494 - val_rmse: 1.0709 - val_smape: 1.3807

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 35s 217ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 32%|███▏      | 16/50 [45:32<2:06:17, 222.86s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

4584/4584 - 22s - 5ms/step - ia: 0.6574 - loss: 0.3561 - mae: 0.4623 - rmse: 0.5686 - smape: 0.8539 - val_ia: 0.1564 - val_loss: 0.9430 - val_mae: 0.7213 - val_rmse: 0.7498 - val_smape: 1.2112

Epoch 2/256

4584/4584 - 17s - 4ms/step - ia: 0.7461 - loss: 0.2095 - mae: 0.3520 - rmse: 0.4382 - smape: 0.7364 - val_ia: 0.1735 - val_loss: 0.9335 - val_mae: 0.6948 - val_rmse: 0.7273 - val_smape: 1.1927

Epoch 3/256

4584/4584 - 17s - 4ms/step - ia: 0.7728 - loss: 0.1719 - mae: 0.3162 - rmse: 0.3959 - smape: 0.7008 - val_ia: 0.1928 - val_loss: 0.5880 - val_mae: 0.5471 - val_rmse: 0.5825 - val_smape: 1.0367

Epoch 4/256

4584/4584 - 19s - 4ms/step - ia: 0.7925 - loss: 0.1459 - mae: 0.2910 - rmse: 0.3650 - smape: 0.6667 - val_ia: 0.2061 - val_loss: 0.5777 - val_mae: 0.5232 - val_rmse: 0.5619 - val_smape: 0.9797

Epoch 5/256

4584/4584 - 21s - 5ms/step - ia: 0.8021 - loss: 0.1343 - mae: 0.2780 - rmse: 0.3491 - smape: 0.6476 - val_ia: 0.2180 - val_loss: 0.4754 - val_mae: 0.4824 - val_rmse: 0.5162 - val_smape: 0.9352

Epoch 6/256

4584/4584 - 14s - 3ms/step - ia: 0.8081 - loss: 0.1259 - mae: 0.2691 - rmse: 0.3382 - smape: 0.6277 - val_ia: 0.2340 - val_loss: 0.4306 - val_mae: 0.4472 - val_rmse: 0.4856 - val_smape: 0.8792

Epoch 7/256

4584/4584 - 19s - 4ms/step - ia: 0.8134 - loss: 0.1198 - mae: 0.2621 - rmse: 0.3293 - smape: 0.6163 - val_ia: 0.2439 - val_loss: 0.3195 - val_mae: 0.4032 - val_rmse: 0.4328 - val_smape: 0.8093

Epoch 8/256

4584/4584 - 27s - 6ms/step - ia: 0.8171 - loss: 0.1151 - mae: 0.2570 - rmse: 0.3231 - smape: 0.6070 - val_ia: 0.2436 - val_loss: 0.3272 - val_mae: 0.3977 - val_rmse: 0.4289 - val_smape: 0.7947

Epoch 9/256

4584/4584 - 34s - 7ms/step - ia: 0.8203 - loss: 0.1120 - mae: 0.2526 - rmse: 0.3177 - smape: 0.5931 - val_ia: 0.2363 - val_loss: 0.2866 - val_mae: 0.3924 - val_rmse: 0.4216 - val_smape: 0.8021

Epoch 10/256

4584/4584 - 17s - 4ms/step - ia: 0.8235 - loss: 0.1081 - mae: 0.2491 - rmse: 0.3131 - smape: 0.5837 - val_ia: 0.2369 - val_loss: 0.4202 - val_mae: 0.4366 - val_rmse: 0.4738 - val_smape: 0.8038

Epoch 11/256

4584/4584 - 23s - 5ms/step - ia: 0.8269 - loss: 0.1046 - mae: 0.2444 - rmse: 0.3080 - smape: 0.5751 - val_ia: 0.2541 - val_loss: 0.2823 - val_mae: 0.3807 - val_rmse: 0.4065 - val_smape: 0.7467

Epoch 12/256

4584/4584 - 15s - 3ms/step - ia: 0.8266 - loss: 0.1036 - mae: 0.2437 - rmse: 0.3060 - smape: 0.5722 - val_ia: 0.2388 - val_loss: 0.5179 - val_mae: 0.4740 - val_rmse: 0.5108 - val_smape: 0.8399

Epoch 13/256

4584/4584 - 19s - 4ms/step - ia: 0.8298 - loss: 0.1004 - mae: 0.2398 - rmse: 0.3014 - smape: 0.5668 - val_ia: 0.2456 - val_loss: 0.3582 - val_mae: 0.4124 - val_rmse: 0.4419 - val_smape: 0.7862

Epoch 14/256

4584/4584 - 13s - 3ms/step - ia: 0.8297 - loss: 0.1007 - mae: 0.2399 - rmse: 0.3019 - smape: 0.5655 - val_ia: 0.2377 - val_loss: 0.3397 - val_mae: 0.4178 - val_rmse: 0.4462 - val_smape: 0.8443

Epoch 15/256

4584/4584 - 18s - 4ms/step - ia: 0.8317 - loss: 0.0984 - mae: 0.2370 - rmse: 0.2979 - smape: 0.5631 - val_ia: 0.2468 - val_loss: 0.3637 - val_mae: 0.4091 - val_rmse: 0.4417 - val_smape: 0.8120

Epoch 16/256

4584/4584 - 16s - 4ms/step - ia: 0.8336 - loss: 0.0965 - mae: 0.2348 - rmse: 0.2953 - smape: 0.5529 - val_ia: 0.2453 - val_loss: 0.3379 - val_mae: 0.4077 - val_rmse: 0.4396 - val_smape: 0.7978

Epoch 17/256

4584/4584 - 19s - 4ms/step - ia: 0.8349 - loss: 0.0951 - mae: 0.2328 - rmse: 0.2927 - smape: 0.5532 - val_ia: 0.2531 - val_loss: 0.2609 - val_mae: 0.3686 - val_rmse: 0.3960 - val_smape: 0.7485

Epoch 18/256

4584/4584 - 19s - 4ms/step - ia: 0.8362 - loss: 0.0944 - mae: 0.2321 - rmse: 0.2921 - smape: 0.5473 - val_ia: 0.2560 - val_loss: 0.2428 - val_mae: 0.3604 - val_rmse: 0.3848 - val_smape: 0.7406

Epoch 19/256

4584/4584 - 18s - 4ms/step - ia: 0.8371 - loss: 0.0935 - mae: 0.2299 - rmse: 0.2901 - smape: 0.5463 - val_ia: 0.2455 - val_loss: 0.3151 - val_mae: 0.3975 - val_rmse: 0.4251 - val_smape: 0.7612

Epoch 20/256

4584/4584 - 16s - 3ms/step - ia: 0.8383 - loss: 0.0923 - mae: 0.2294 - rmse: 0.2886 - smape: 0.5423 - val_ia: 0.2414 - val_loss: 0.2885 - val_mae: 0.3889 - val_rmse: 0.4152 - val_smape: 0.7875

Epoch 21/256

4584/4584 - 19s - 4ms/step - ia: 0.8391 - loss: 0.0914 - mae: 0.2276 - rmse: 0.2870 - smape: 0.5393 - val_ia: 0.2588 - val_loss: 0.2602 - val_mae: 0.3646 - val_rmse: 0.3929 - val_smape: 0.7419

Epoch 22/256

4584/4584 - 19s - 4ms/step - ia: 0.8393 - loss: 0.0898 - mae: 0.2269 - rmse: 0.2846 - smape: 0.5411 - val_ia: 0.2571 - val_loss: 0.2978 - val_mae: 0.3798 - val_rmse: 0.4111 - val_smape: 0.7495

Epoch 23/256

4584/4584 - 20s - 4ms/step - ia: 0.8402 - loss: 0.0895 - mae: 0.2260 - rmse: 0.2842 - smape: 0.5360 - val_ia: 0.2583 - val_loss: 0.2302 - val_mae: 0.3551 - val_rmse: 0.3808 - val_smape: 0.7404

Epoch 24/256

4584/4584 - 23s - 5ms/step - ia: 0.8410 - loss: 0.0894 - mae: 0.2254 - rmse: 0.2841 - smape: 0.5355 - val_ia: 0.2581 - val_loss: 0.2613 - val_mae: 0.3662 - val_rmse: 0.3962 - val_smape: 0.7203

Epoch 25/256

4584/4584 - 15s - 3ms/step - ia: 0.8422 - loss: 0.0875 - mae: 0.2235 - rmse: 0.2811 - smape: 0.5333 - val_ia: 0.2562 - val_loss: 0.2915 - val_mae: 0.3749 - val_rmse: 0.4063 - val_smape: 0.7542

Epoch 26/256

4584/4584 - 16s - 4ms/step - ia: 0.8422 - loss: 0.0879 - mae: 0.2234 - rmse: 0.2812 - smape: 0.5329 - val_ia: 0.2627 - val_loss: 0.2557 - val_mae: 0.3584 - val_rmse: 0.3864 - val_smape: 0.7324

Epoch 27/256

4584/4584 - 18s - 4ms/step - ia: 0.8439 - loss: 0.0858 - mae: 0.2212 - rmse: 0.2785 - smape: 0.5260 - val_ia: 0.2594 - val_loss: 0.2084 - val_mae: 0.3460 - val_rmse: 0.3701 - val_smape: 0.7210

Epoch 28/256

4584/4584 - 17s - 4ms/step - ia: 0.8435 - loss: 0.0865 - mae: 0.2221 - rmse: 0.2798 - smape: 0.5247 - val_ia: 0.2703 - val_loss: 0.1646 - val_mae: 0.3121 - val_rmse: 0.3360 - val_smape: 0.6865

Epoch 29/256

4584/4584 - 17s - 4ms/step - ia: 0.8447 - loss: 0.0855 - mae: 0.2201 - rmse: 0.2775 - smape: 0.5258 - val_ia: 0.2607 - val_loss: 0.3023 - val_mae: 0.3800 - val_rmse: 0.4100 - val_smape: 0.7474

Epoch 30/256

4584/4584 - 19s - 4ms/step - ia: 0.8449 - loss: 0.0856 - mae: 0.2203 - rmse: 0.2780 - smape: 0.5229 - val_ia: 0.2605 - val_loss: 0.2947 - val_mae: 0.3737 - val_rmse: 0.4063 - val_smape: 0.7637

Epoch 31/256

4584/4584 - 18s - 4ms/step - ia: 0.8464 - loss: 0.0840 - mae: 0.2181 - rmse: 0.2751 - smape: 0.5226 - val_ia: 0.2645 - val_loss: 0.1741 - val_mae: 0.3249 - val_rmse: 0.3467 - val_smape: 0.7046

Epoch 32/256

4584/4584 - 15s - 3ms/step - ia: 0.8460 - loss: 0.0831 - mae: 0.2178 - rmse: 0.2741 - smape: 0.5193 - val_ia: 0.2681 - val_loss: 0.2233 - val_mae: 0.3442 - val_rmse: 0.3711 - val_smape: 0.7193

Epoch 33/256

4584/4584 - 24s - 5ms/step - ia: 0.8461 - loss: 0.0841 - mae: 0.2189 - rmse: 0.2752 - smape: 0.5198 - val_ia: 0.2524 - val_loss: 0.3811 - val_mae: 0.4131 - val_rmse: 0.4441 - val_smape: 0.7918

Epoch 34/256

4584/4584 - 17s - 4ms/step - ia: 0.8472 - loss: 0.0831 - mae: 0.2168 - rmse: 0.2733 - smape: 0.5167 - val_ia: 0.2737 - val_loss: 0.2000 - val_mae: 0.3297 - val_rmse: 0.3539 - val_smape: 0.7104

Epoch 35/256

4584/4584 - 15s - 3ms/step - ia: 0.8483 - loss: 0.0819 - mae: 0.2161 - rmse: 0.2719 - smape: 0.5173 - val_ia: 0.2557 - val_loss: 0.2485 - val_mae: 0.3634 - val_rmse: 0.3875 - val_smape: 0.7507

Epoch 36/256

4584/4584 - 14s - 3ms/step - ia: 0.8472 - loss: 0.0828 - mae: 0.2168 - rmse: 0.2731 - smape: 0.5171 - val_ia: 0.2731 - val_loss: 0.1711 - val_mae: 0.3159 - val_rmse: 0.3380 - val_smape: 0.6860

Epoch 37/256

4584/4584 - 19s - 4ms/step - ia: 0.8480 - loss: 0.0819 - mae: 0.2153 - rmse: 0.2715 - smape: 0.5147 - val_ia: 0.2779 - val_loss: 0.1731 - val_mae: 0.3161 - val_rmse: 0.3372 - val_smape: 0.6775

Epoch 38/256

4584/4584 - 20s - 4ms/step - ia: 0.8484 - loss: 0.0815 - mae: 0.2156 - rmse: 0.2710 - smape: 0.5145 - val_ia: 0.2817 - val_loss: 0.1707 - val_mae: 0.3135 - val_rmse: 0.3352 - val_smape: 0.6801

Epoch 39/256

4584/4584 - 17s - 4ms/step - ia: 0.8482 - loss: 0.0814 - mae: 0.2154 - rmse: 0.2713 - smape: 0.5177 - val_ia: 0.2722 - val_loss: 0.1757 - val_mae: 0.3157 - val_rmse: 0.3410 - val_smape: 0.6784

Epoch 40/256

4584/4584 - 16s - 3ms/step - ia: 0.8488 - loss: 0.0814 - mae: 0.2146 - rmse: 0.2707 - smape: 0.5139 - val_ia: 0.2859 - val_loss: 0.1586 - val_mae: 0.3042 - val_rmse: 0.3262 - val_smape: 0.6692

Epoch 41/256

4584/4584 - 19s - 4ms/step - ia: 0.8493 - loss: 0.0801 - mae: 0.2138 - rmse: 0.2688 - smape: 0.5140 - val_ia: 0.2714 - val_loss: 0.1907 - val_mae: 0.3266 - val_rmse: 0.3500 - val_smape: 0.6989

Epoch 42/256

4584/4584 - 15s - 3ms/step - ia: 0.8486 - loss: 0.0815 - mae: 0.2145 - rmse: 0.2708 - smape: 0.5123 - val_ia: 0.2757 - val_loss: 0.2154 - val_mae: 0.3353 - val_rmse: 0.3591 - val_smape: 0.7015

Epoch 43/256

4584/4584 - 15s - 3ms/step - ia: 0.8490 - loss: 0.0809 - mae: 0.2141 - rmse: 0.2700 - smape: 0.5117 - val_ia: 0.2876 - val_loss: 0.1599 - val_mae: 0.3053 - val_rmse: 0.3254 - val_smape: 0.6578

Epoch 44/256

4584/4584 - 22s - 5ms/step - ia: 0.8482 - loss: 0.0814 - mae: 0.2153 - rmse: 0.2709 - smape: 0.5123 - val_ia: 0.2670 - val_loss: 0.2948 - val_mae: 0.3712 - val_rmse: 0.3996 - val_smape: 0.7381

Epoch 45/256

4584/4584 - 13s - 3ms/step - ia: 0.8508 - loss: 0.0789 - mae: 0.2121 - rmse: 0.2667 - smape: 0.5135 - val_ia: 0.2709 - val_loss: 0.2590 - val_mae: 0.3584 - val_rmse: 0.3837 - val_smape: 0.7368

Epoch 46/256

4584/4584 - 18s - 4ms/step - ia: 0.8501 - loss: 0.0792 - mae: 0.2125 - rmse: 0.2673 - smape: 0.5112 - val_ia: 0.2699 - val_loss: 0.2198 - val_mae: 0.3442 - val_rmse: 0.3664 - val_smape: 0.7143

Epoch 47/256

4584/4584 - 19s - 4ms/step - ia: 0.8525 - loss: 0.0786 - mae: 0.2109 - rmse: 0.2658 - smape: 0.5084 - val_ia: 0.2740 - val_loss: 0.2259 - val_mae: 0.3391 - val_rmse: 0.3653 - val_smape: 0.6961

Epoch 48/256

4584/4584 - 21s - 5ms/step - ia: 0.8507 - loss: 0.0788 - mae: 0.2116 - rmse: 0.2664 - smape: 0.5067 - val_ia: 0.2715 - val_loss: 0.2827 - val_mae: 0.3605 - val_rmse: 0.3871 - val_smape: 0.7275

Epoch 49/256

4584/4584 - 37s - 8ms/step - ia: 0.8515 - loss: 0.0791 - mae: 0.2115 - rmse: 0.2666 - smape: 0.5078 - val_ia: 0.2775 - val_loss: 0.1710 - val_mae: 0.3157 - val_rmse: 0.3372 - val_smape: 0.6835

Epoch 50/256

4584/4584 - 20s - 4ms/step - ia: 0.8508 - loss: 0.0790 - mae: 0.2116 - rmse: 0.2667 - smape: 0.5071 - val_ia: 0.2806 - val_loss: 0.1885 - val_mae: 0.3271 - val_rmse: 0.3472 - val_smape: 0.6965

Epoch 51/256

4584/4584 - 22s - 5ms/step - ia: 0.8525 - loss: 0.0785 - mae: 0.2099 - rmse: 0.2656 - smape: 0.5046 - val_ia: 0.2775 - val_loss: 0.2156 - val_mae: 0.3309 - val_rmse: 0.3552 - val_smape: 0.6921

Epoch 52/256

4584/4584 - 14s - 3ms/step - ia: 0.8521 - loss: 0.0779 - mae: 0.2103 - rmse: 0.2649 - smape: 0.5057 - val_ia: 0.2666 - val_loss: 0.2438 - val_mae: 0.3558 - val_rmse: 0.3802 - val_smape: 0.7336

Epoch 53/256

4584/4584 - 27s - 6ms/step - ia: 0.8507 - loss: 0.0785 - mae: 0.2114 - rmse: 0.2659 - smape: 0.5075 - val_ia: 0.2747 - val_loss: 0.2449 - val_mae: 0.3424 - val_rmse: 0.3672 - val_smape: 0.7362

Epoch 54/256

4584/4584 - 16s - 3ms/step - ia: 0.8527 - loss: 0.0776 - mae: 0.2100 - rmse: 0.2647 - smape: 0.5040 - val_ia: 0.2866 - val_loss: 0.1953 - val_mae: 0.3224 - val_rmse: 0.3441 - val_smape: 0.7059

Epoch 55/256

4584/4584 - 20s - 4ms/step - ia: 0.8519 - loss: 0.0776 - mae: 0.2101 - rmse: 0.2646 - smape: 0.5048 - val_ia: 0.2794 - val_loss: 0.2160 - val_mae: 0.3306 - val_rmse: 0.3522 - val_smape: 0.6951

Epoch 55: early stopping

Restoring model weights from the end of the best epoch: 40.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:08 795ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 34%|███▍      | 17/50 [1:02:57<4:18:38, 470.25s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

287/287 - 7s - 24ms/step - ia: 0.2627 - loss: 2.7388 - mae: 1.3265 - rmse: 1.6521 - smape: 1.4848 - val_ia: 0.2592 - val_loss: 1.7235 - val_mae: 0.9956 - val_rmse: 1.2962 - val_smape: 1.4228

Epoch 2/16

287/287 - 1s - 4ms/step - ia: 0.2700 - loss: 2.6233 - mae: 1.2995 - rmse: 1.6176 - smape: 1.4732 - val_ia: 0.2629 - val_loss: 1.5721 - val_mae: 0.9414 - val_rmse: 1.2379 - val_smape: 1.4013

Epoch 3/16

287/287 - 1s - 5ms/step - ia: 0.2793 - loss: 2.5119 - mae: 1.2725 - rmse: 1.5819 - smape: 1.4660 - val_ia: 0.2662 - val_loss: 1.4420 - val_mae: 0.8965 - val_rmse: 1.1858 - val_smape: 1.3838

Epoch 4/16

287/287 - 3s - 11ms/step - ia: 0.2905 - loss: 2.4344 - mae: 1.2503 - rmse: 1.5575 - smape: 1.4496 - val_ia: 0.2683 - val_loss: 1.3297 - val_mae: 0.8609 - val_rmse: 1.1392 - val_smape: 1.3714

Epoch 5/16

287/287 - 3s - 10ms/step - ia: 0.2978 - loss: 2.3512 - mae: 1.2281 - rmse: 1.5308 - smape: 1.4393 - val_ia: 0.2699 - val_loss: 1.2316 - val_mae: 0.8326 - val_rmse: 1.0971 - val_smape: 1.3643

Epoch 6/16

287/287 - 3s - 11ms/step - ia: 0.3062 - loss: 2.2746 - mae: 1.2097 - rmse: 1.5057 - smape: 1.4303 - val_ia: 0.2713 - val_loss: 1.1449 - val_mae: 0.8093 - val_rmse: 1.0585 - val_smape: 1.3644

Epoch 7/16

287/287 - 2s - 8ms/step - ia: 0.3097 - loss: 2.2396 - mae: 1.1999 - rmse: 1.4941 - smape: 1.4253 - val_ia: 0.2725 - val_loss: 1.0700 - val_mae: 0.7899 - val_rmse: 1.0241 - val_smape: 1.3658

Epoch 8/16

287/287 - 2s - 6ms/step - ia: 0.3181 - loss: 2.1817 - mae: 1.1818 - rmse: 1.4742 - smape: 1.4161 - val_ia: 0.2739 - val_loss: 1.0048 - val_mae: 0.7734 - val_rmse: 0.9932 - val_smape: 1.3742

Epoch 9/16

287/287 - 2s - 6ms/step - ia: 0.3211 - loss: 2.1440 - mae: 1.1735 - rmse: 1.4612 - smape: 1.4098 - val_ia: 0.2759 - val_loss: 0.9466 - val_mae: 0.7586 - val_rmse: 0.9648 - val_smape: 1.3850

Epoch 10/16

287/287 - 2s - 8ms/step - ia: 0.3296 - loss: 2.0929 - mae: 1.1595 - rmse: 1.4439 - smape: 1.3980 - val_ia: 0.2792 - val_loss: 0.8964 - val_mae: 0.7456 - val_rmse: 0.9395 - val_smape: 1.3960

Epoch 11/16

287/287 - 2s - 7ms/step - ia: 0.3362 - loss: 2.0407 - mae: 1.1436 - rmse: 1.4253 - smape: 1.3891 - val_ia: 0.2839 - val_loss: 0.8540 - val_mae: 0.7343 - val_rmse: 0.9175 - val_smape: 1.4074

Epoch 12/16

287/287 - 2s - 8ms/step - ia: 0.3410 - loss: 1.9939 - mae: 1.1301 - rmse: 1.4098 - smape: 1.3814 - val_ia: 0.2891 - val_loss: 0.8175 - val_mae: 0.7244 - val_rmse: 0.8981 - val_smape: 1.4164

Epoch 13/16

287/287 - 2s - 7ms/step - ia: 0.3462 - loss: 1.9687 - mae: 1.1249 - rmse: 1.4004 - smape: 1.3768 - val_ia: 0.2948 - val_loss: 0.7868 - val_mae: 0.7163 - val_rmse: 0.8814 - val_smape: 1.4239

Epoch 14/16

287/287 - 2s - 8ms/step - ia: 0.3580 - loss: 1.9117 - mae: 1.1042 - rmse: 1.3799 - smape: 1.3594 - val_ia: 0.3018 - val_loss: 0.7618 - val_mae: 0.7095 - val_rmse: 0.8674 - val_smape: 1.4241

Epoch 15/16

287/287 - 2s - 7ms/step - ia: 0.3562 - loss: 1.8874 - mae: 1.1012 - rmse: 1.3710 - smape: 1.3631 - val_ia: 0.3099 - val_loss: 0.7406 - val_mae: 0.7037 - val_rmse: 0.8552 - val_smape: 1.4186

Epoch 16/16

287/287 - 2s - 8ms/step - ia: 0.3655 - loss: 1.8330 - mae: 1.0812 - rmse: 1.3515 - smape: 1.3498 - val_ia: 0.3189 - val_loss: 0.7235 - val_mae: 0.6991 - val_rmse: 0.8451 - val_smape: 1.4055

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:07 418ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

Epoch 1/16

 36%|███▌      | 18/50 [1:03:42<3:02:35, 342.37s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

573/573 - 8s - 14ms/step - ia: 0.6237 - loss: 0.4873 - mae: 0.5550 - rmse: 0.6912 - smape: 0.9550 - val_ia: 0.3878 - val_loss: 1.2693 - val_mae: 0.9077 - val_rmse: 1.0245 - val_smape: 1.2888

Epoch 2/16

573/573 - 2s - 4ms/step - ia: 0.7024 - loss: 0.3219 - mae: 0.4487 - rmse: 0.5647 - smape: 0.8365 - val_ia: 0.4452 - val_loss: 0.8785 - val_mae: 0.7175 - val_rmse: 0.8419 - val_smape: 1.1620

Epoch 3/16

573/573 - 3s - 6ms/step - ia: 0.7314 - loss: 0.2717 - mae: 0.4101 - rmse: 0.5185 - smape: 0.7913 - val_ia: 0.4713 - val_loss: 0.6916 - val_mae: 0.6331 - val_rmse: 0.7518 - val_smape: 1.1262

Epoch 4/16

573/573 - 4s - 6ms/step - ia: 0.7439 - loss: 0.2516 - mae: 0.3934 - rmse: 0.4993 - smape: 0.7681 - val_ia: 0.4827 - val_loss: 0.6574 - val_mae: 0.6099 - val_rmse: 0.7329 - val_smape: 1.0923

Epoch 5/16

573/573 - 4s - 8ms/step - ia: 0.7530 - loss: 0.2368 - mae: 0.3807 - rmse: 0.4841 - smape: 0.7562 - val_ia: 0.4879 - val_loss: 0.6278 - val_mae: 0.6124 - val_rmse: 0.7177 - val_smape: 1.1126

Epoch 6/16

573/573 - 2s - 4ms/step - ia: 0.7603 - loss: 0.2236 - mae: 0.3706 - rmse: 0.4707 - smape: 0.7396 - val_ia: 0.5088 - val_loss: 0.4986 - val_mae: 0.5413 - val_rmse: 0.6470 - val_smape: 1.0614

Epoch 7/16

573/573 - 3s - 5ms/step - ia: 0.7665 - loss: 0.2141 - mae: 0.3618 - rmse: 0.4603 - smape: 0.7291 - val_ia: 0.5297 - val_loss: 0.4708 - val_mae: 0.5334 - val_rmse: 0.6277 - val_smape: 1.0449

Epoch 8/16

573/573 - 3s - 5ms/step - ia: 0.7716 - loss: 0.2063 - mae: 0.3551 - rmse: 0.4518 - smape: 0.7231 - val_ia: 0.5423 - val_loss: 0.4272 - val_mae: 0.5121 - val_rmse: 0.5983 - val_smape: 1.0301

Epoch 9/16

573/573 - 3s - 5ms/step - ia: 0.7756 - loss: 0.1996 - mae: 0.3489 - rmse: 0.4444 - smape: 0.7173 - val_ia: 0.5383 - val_loss: 0.4035 - val_mae: 0.4982 - val_rmse: 0.5880 - val_smape: 1.0204

Epoch 10/16

573/573 - 3s - 5ms/step - ia: 0.7814 - loss: 0.1910 - mae: 0.3402 - rmse: 0.4347 - smape: 0.7037 - val_ia: 0.5551 - val_loss: 0.3436 - val_mae: 0.4639 - val_rmse: 0.5488 - val_smape: 0.9825

Epoch 11/16

573/573 - 3s - 5ms/step - ia: 0.7841 - loss: 0.1860 - mae: 0.3369 - rmse: 0.4292 - smape: 0.7003 - val_ia: 0.5621 - val_loss: 0.3557 - val_mae: 0.4743 - val_rmse: 0.5479 - val_smape: 0.9610

Epoch 12/16

573/573 - 5s - 8ms/step - ia: 0.7872 - loss: 0.1817 - mae: 0.3320 - rmse: 0.4242 - smape: 0.6943 - val_ia: 0.5860 - val_loss: 0.2987 - val_mae: 0.4339 - val_rmse: 0.5106 - val_smape: 0.9105

Epoch 13/16

573/573 - 3s - 5ms/step - ia: 0.7902 - loss: 0.1762 - mae: 0.3277 - rmse: 0.4176 - smape: 0.6885 - val_ia: 0.5775 - val_loss: 0.3047 - val_mae: 0.4394 - val_rmse: 0.5149 - val_smape: 0.9256

Epoch 14/16

573/573 - 6s - 10ms/step - ia: 0.7913 - loss: 0.1747 - mae: 0.3262 - rmse: 0.4158 - smape: 0.6872 - val_ia: 0.5932 - val_loss: 0.2774 - val_mae: 0.4175 - val_rmse: 0.4891 - val_smape: 0.9008

Epoch 15/16

573/573 - 3s - 5ms/step - ia: 0.7952 - loss: 0.1688 - mae: 0.3207 - rmse: 0.4087 - smape: 0.6801 - val_ia: 0.5954 - val_loss: 0.2649 - val_mae: 0.4108 - val_rmse: 0.4858 - val_smape: 0.8996

Epoch 16/16

573/573 - 4s - 7ms/step - ia: 0.7969 - loss: 0.1663 - mae: 0.3187 - rmse: 0.4056 - smape: 0.6797 - val_ia: 0.5998 - val_loss: 0.2558 - val_mae: 0.4045 - val_rmse: 0.4751 - val_smape: 0.8810

Restoring model weights from the end of the best epoch: 16.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 21s 134ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 38%|███▊      | 19/50 [1:04:42<2:13:07, 257.66s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 51s - 11ms/step - ia: 0.4744 - loss: 0.6641 - mae: 0.6553 - rmse: 0.7856 - smape: 1.1111 - val_ia: 0.1275 - val_loss: 1.0851 - val_mae: 0.8599 - val_rmse: 0.8863 - val_smape: 1.3040

Epoch 2/32

4584/4584 - 22s - 5ms/step - ia: 0.5874 - loss: 0.4848 - mae: 0.5542 - rmse: 0.6740 - smape: 0.9200 - val_ia: 0.1346 - val_loss: 1.0373 - val_mae: 0.8185 - val_rmse: 0.8472 - val_smape: 1.2899

Epoch 3/32

4584/4584 - 39s - 9ms/step - ia: 0.6160 - loss: 0.4332 - mae: 0.5172 - rmse: 0.6362 - smape: 0.8856 - val_ia: 0.1321 - val_loss: 1.0741 - val_mae: 0.8238 - val_rmse: 0.8535 - val_smape: 1.2887

Epoch 4/32

4584/4584 - 14s - 3ms/step - ia: 0.6321 - loss: 0.4072 - mae: 0.4982 - rmse: 0.6155 - smape: 0.8662 - val_ia: 0.1345 - val_loss: 1.0017 - val_mae: 0.7974 - val_rmse: 0.8249 - val_smape: 1.2924

Epoch 5/32

4584/4584 - 16s - 3ms/step - ia: 0.6497 - loss: 0.3776 - mae: 0.4786 - rmse: 0.5918 - smape: 0.8460 - val_ia: 0.1364 - val_loss: 0.9449 - val_mae: 0.7718 - val_rmse: 0.7979 - val_smape: 1.2783

Epoch 6/32

4584/4584 - 20s - 4ms/step - ia: 0.6620 - loss: 0.3533 - mae: 0.4636 - rmse: 0.5738 - smape: 0.8359 - val_ia: 0.1398 - val_loss: 0.8993 - val_mae: 0.7508 - val_rmse: 0.7762 - val_smape: 1.2728

Epoch 7/32

4584/4584 - 28s - 6ms/step - ia: 0.6705 - loss: 0.3380 - mae: 0.4536 - rmse: 0.5608 - smape: 0.8305 - val_ia: 0.1466 - val_loss: 0.7670 - val_mae: 0.6977 - val_rmse: 0.7219 - val_smape: 1.2376

Epoch 8/32

4584/4584 - 17s - 4ms/step - ia: 0.6751 - loss: 0.3274 - mae: 0.4454 - rmse: 0.5508 - smape: 0.8261 - val_ia: 0.1518 - val_loss: 0.7024 - val_mae: 0.6740 - val_rmse: 0.6981 - val_smape: 1.2280

Epoch 9/32

4584/4584 - 20s - 4ms/step - ia: 0.6835 - loss: 0.3164 - mae: 0.4348 - rmse: 0.5412 - smape: 0.8161 - val_ia: 0.1480 - val_loss: 0.6838 - val_mae: 0.6705 - val_rmse: 0.6952 - val_smape: 1.2366

Epoch 10/32

4584/4584 - 17s - 4ms/step - ia: 0.6909 - loss: 0.3058 - mae: 0.4260 - rmse: 0.5318 - smape: 0.8153 - val_ia: 0.1532 - val_loss: 0.6325 - val_mae: 0.6492 - val_rmse: 0.6734 - val_smape: 1.2293

Epoch 11/32

4584/4584 - 22s - 5ms/step - ia: 0.6993 - loss: 0.2943 - mae: 0.4151 - rmse: 0.5198 - smape: 0.8007 - val_ia: 0.1572 - val_loss: 0.5792 - val_mae: 0.6225 - val_rmse: 0.6456 - val_smape: 1.2135

Epoch 12/32

4584/4584 - 24s - 5ms/step - ia: 0.7009 - loss: 0.2894 - mae: 0.4113 - rmse: 0.5153 - smape: 0.8036 - val_ia: 0.1636 - val_loss: 0.5338 - val_mae: 0.5990 - val_rmse: 0.6224 - val_smape: 1.1965

Epoch 13/32

4584/4584 - 20s - 4ms/step - ia: 0.7065 - loss: 0.2842 - mae: 0.4065 - rmse: 0.5107 - smape: 0.7939 - val_ia: 0.1611 - val_loss: 0.5479 - val_mae: 0.6098 - val_rmse: 0.6315 - val_smape: 1.2102

Epoch 14/32

4584/4584 - 21s - 5ms/step - ia: 0.7086 - loss: 0.2782 - mae: 0.4014 - rmse: 0.5044 - smape: 0.7886 - val_ia: 0.1636 - val_loss: 0.5276 - val_mae: 0.6000 - val_rmse: 0.6214 - val_smape: 1.2161

Epoch 15/32

4584/4584 - 21s - 4ms/step - ia: 0.7087 - loss: 0.2785 - mae: 0.4015 - rmse: 0.5050 - smape: 0.7919 - val_ia: 0.1627 - val_loss: 0.5115 - val_mae: 0.5908 - val_rmse: 0.6124 - val_smape: 1.1906

Epoch 16/32

4584/4584 - 15s - 3ms/step - ia: 0.7119 - loss: 0.2747 - mae: 0.3987 - rmse: 0.5013 - smape: 0.7875 - val_ia: 0.1619 - val_loss: 0.5215 - val_mae: 0.5956 - val_rmse: 0.6173 - val_smape: 1.2065

Epoch 17/32

4584/4584 - 16s - 3ms/step - ia: 0.7105 - loss: 0.2752 - mae: 0.3989 - rmse: 0.5023 - smape: 0.7943 - val_ia: 0.1605 - val_loss: 0.5106 - val_mae: 0.5907 - val_rmse: 0.6129 - val_smape: 1.1976

Epoch 18/32

4584/4584 - 18s - 4ms/step - ia: 0.7125 - loss: 0.2699 - mae: 0.3955 - rmse: 0.4970 - smape: 0.7873 - val_ia: 0.1632 - val_loss: 0.5060 - val_mae: 0.5870 - val_rmse: 0.6089 - val_smape: 1.2110

Epoch 19/32

4584/4584 - 13s - 3ms/step - ia: 0.7161 - loss: 0.2639 - mae: 0.3915 - rmse: 0.4914 - smape: 0.7907 - val_ia: 0.1640 - val_loss: 0.4965 - val_mae: 0.5820 - val_rmse: 0.6042 - val_smape: 1.2249

Epoch 20/32

4584/4584 - 16s - 4ms/step - ia: 0.7182 - loss: 0.2617 - mae: 0.3890 - rmse: 0.4886 - smape: 0.7861 - val_ia: 0.1581 - val_loss: 0.5096 - val_mae: 0.5917 - val_rmse: 0.6134 - val_smape: 1.2385

Epoch 21/32

4584/4584 - 23s - 5ms/step - ia: 0.7204 - loss: 0.2596 - mae: 0.3874 - rmse: 0.4875 - smape: 0.7823 - val_ia: 0.1614 - val_loss: 0.4805 - val_mae: 0.5737 - val_rmse: 0.5963 - val_smape: 1.2130

Epoch 22/32

4584/4584 - 36s - 8ms/step - ia: 0.7209 - loss: 0.2584 - mae: 0.3852 - rmse: 0.4859 - smape: 0.7831 - val_ia: 0.1706 - val_loss: 0.4622 - val_mae: 0.5582 - val_rmse: 0.5818 - val_smape: 1.2068

Epoch 23/32

4584/4584 - 24s - 5ms/step - ia: 0.7222 - loss: 0.2537 - mae: 0.3831 - rmse: 0.4814 - smape: 0.7829 - val_ia: 0.1656 - val_loss: 0.4603 - val_mae: 0.5580 - val_rmse: 0.5822 - val_smape: 1.1880

Epoch 24/32

4584/4584 - 37s - 8ms/step - ia: 0.7221 - loss: 0.2518 - mae: 0.3823 - rmse: 0.4803 - smape: 0.7857 - val_ia: 0.1706 - val_loss: 0.4310 - val_mae: 0.5400 - val_rmse: 0.5644 - val_smape: 1.1694

Epoch 25/32

4584/4584 - 29s - 6ms/step - ia: 0.7230 - loss: 0.2541 - mae: 0.3824 - rmse: 0.4818 - smape: 0.7805 - val_ia: 0.1638 - val_loss: 0.4439 - val_mae: 0.5499 - val_rmse: 0.5751 - val_smape: 1.1779

Epoch 26/32

4584/4584 - 23s - 5ms/step - ia: 0.7264 - loss: 0.2476 - mae: 0.3779 - rmse: 0.4749 - smape: 0.7774 - val_ia: 0.1703 - val_loss: 0.4178 - val_mae: 0.5337 - val_rmse: 0.5580 - val_smape: 1.1479

Epoch 27/32

4584/4584 - 19s - 4ms/step - ia: 0.7274 - loss: 0.2467 - mae: 0.3769 - rmse: 0.4742 - smape: 0.7762 - val_ia: 0.1759 - val_loss: 0.4019 - val_mae: 0.5201 - val_rmse: 0.5455 - val_smape: 1.1249

Epoch 28/32

4584/4584 - 18s - 4ms/step - ia: 0.7296 - loss: 0.2444 - mae: 0.3746 - rmse: 0.4726 - smape: 0.7701 - val_ia: 0.1824 - val_loss: 0.3692 - val_mae: 0.4991 - val_rmse: 0.5241 - val_smape: 1.0870

Epoch 29/32

4584/4584 - 24s - 5ms/step - ia: 0.7287 - loss: 0.2428 - mae: 0.3745 - rmse: 0.4712 - smape: 0.7720 - val_ia: 0.1880 - val_loss: 0.3626 - val_mae: 0.4919 - val_rmse: 0.5172 - val_smape: 1.0739

Epoch 30/32

4584/4584 - 20s - 4ms/step - ia: 0.7288 - loss: 0.2416 - mae: 0.3738 - rmse: 0.4702 - smape: 0.7713 - val_ia: 0.1841 - val_loss: 0.3699 - val_mae: 0.4967 - val_rmse: 0.5218 - val_smape: 1.0641

Epoch 31/32

4584/4584 - 18s - 4ms/step - ia: 0.7306 - loss: 0.2419 - mae: 0.3733 - rmse: 0.4700 - smape: 0.7679 - val_ia: 0.1852 - val_loss: 0.3725 - val_mae: 0.4950 - val_rmse: 0.5207 - val_smape: 1.0561

Epoch 32/32

4584/4584 - 17s - 4ms/step - ia: 0.7291 - loss: 0.2427 - mae: 0.3735 - rmse: 0.4700 - smape: 0.7671 - val_ia: 0.1905 - val_loss: 0.3549 - val_mae: 0.4805 - val_rmse: 0.5071 - val_smape: 1.0082

Restoring model weights from the end of the best epoch: 32.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:25 527ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 40%|████      | 20/50 [1:16:46<3:18:48, 397.63s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

144/144 - 5s - 36ms/step - ia: 0.3541 - loss: 0.9861 - mae: 0.8060 - rmse: 0.9898 - smape: 1.3582 - val_ia: 0.4074 - val_loss: 0.6531 - val_mae: 0.6663 - val_rmse: 0.7972 - val_smape: 1.2179

Epoch 2/128

144/144 - 1s - 4ms/step - ia: 0.4662 - loss: 0.7618 - mae: 0.7053 - rmse: 0.8721 - smape: 1.2088 - val_ia: 0.4657 - val_loss: 0.6721 - val_mae: 0.6685 - val_rmse: 0.8038 - val_smape: 1.1566

Epoch 3/128

144/144 - 1s - 4ms/step - ia: 0.5320 - loss: 0.6555 - mae: 0.6503 - rmse: 0.8089 - smape: 1.1104 - val_ia: 0.4890 - val_loss: 0.7340 - val_mae: 0.6965 - val_rmse: 0.8383 - val_smape: 1.1487

Epoch 4/128

144/144 - 2s - 11ms/step - ia: 0.5712 - loss: 0.5914 - mae: 0.6161 - rmse: 0.7674 - smape: 1.0487 - val_ia: 0.4907 - val_loss: 0.8092 - val_mae: 0.7320 - val_rmse: 0.8798 - val_smape: 1.1585

Epoch 5/128

144/144 - 1s - 8ms/step - ia: 0.5980 - loss: 0.5471 - mae: 0.5894 - rmse: 0.7389 - smape: 1.0013 - val_ia: 0.4935 - val_loss: 0.8491 - val_mae: 0.7499 - val_rmse: 0.9006 - val_smape: 1.1604

Epoch 6/128

144/144 - 2s - 13ms/step - ia: 0.6153 - loss: 0.5171 - mae: 0.5733 - rmse: 0.7182 - smape: 0.9716 - val_ia: 0.4926 - val_loss: 0.8955 - val_mae: 0.7691 - val_rmse: 0.9240 - val_smape: 1.1659

Epoch 7/128

144/144 - 2s - 14ms/step - ia: 0.6268 - loss: 0.4928 - mae: 0.5594 - rmse: 0.7007 - smape: 0.9496 - val_ia: 0.4970 - val_loss: 0.9117 - val_mae: 0.7730 - val_rmse: 0.9312 - val_smape: 1.1593

Epoch 8/128

144/144 - 2s - 14ms/step - ia: 0.6362 - loss: 0.4759 - mae: 0.5475 - rmse: 0.6897 - smape: 0.9312 - val_ia: 0.4955 - val_loss: 0.9478 - val_mae: 0.7872 - val_rmse: 0.9485 - val_smape: 1.1655

Epoch 9/128

144/144 - 2s - 16ms/step - ia: 0.6433 - loss: 0.4578 - mae: 0.5379 - rmse: 0.6758 - smape: 0.9227 - val_ia: 0.4961 - val_loss: 0.9733 - val_mae: 0.7949 - val_rmse: 0.9602 - val_smape: 1.1640

Epoch 10/128

144/144 - 1s - 10ms/step - ia: 0.6513 - loss: 0.4389 - mae: 0.5270 - rmse: 0.6617 - smape: 0.9085 - val_ia: 0.4978 - val_loss: 0.9987 - val_mae: 0.8013 - val_rmse: 0.9714 - val_smape: 1.1602

Epoch 11/128

144/144 - 2s - 11ms/step - ia: 0.6564 - loss: 0.4291 - mae: 0.5193 - rmse: 0.6554 - smape: 0.8936 - val_ia: 0.4961 - val_loss: 1.0215 - val_mae: 0.8114 - val_rmse: 0.9806 - val_smape: 1.1678

Epoch 12/128

144/144 - 1s - 6ms/step - ia: 0.6592 - loss: 0.4201 - mae: 0.5150 - rmse: 0.6476 - smape: 0.8933 - val_ia: 0.4969 - val_loss: 1.0454 - val_mae: 0.8176 - val_rmse: 0.9913 - val_smape: 1.1651

Epoch 13/128

144/144 - 1s - 4ms/step - ia: 0.6662 - loss: 0.4061 - mae: 0.5058 - rmse: 0.6371 - smape: 0.8831 - val_ia: 0.4973 - val_loss: 1.0634 - val_mae: 0.8230 - val_rmse: 0.9984 - val_smape: 1.1653

Epoch 14/128

144/144 - 1s - 6ms/step - ia: 0.6704 - loss: 0.3980 - mae: 0.4992 - rmse: 0.6304 - smape: 0.8743 - val_ia: 0.4957 - val_loss: 1.0896 - val_mae: 0.8332 - val_rmse: 1.0091 - val_smape: 1.1698

Epoch 15/128

144/144 - 2s - 12ms/step - ia: 0.6712 - loss: 0.3931 - mae: 0.4969 - rmse: 0.6269 - smape: 0.8745 - val_ia: 0.4984 - val_loss: 1.0933 - val_mae: 0.8318 - val_rmse: 1.0101 - val_smape: 1.1645

Epoch 16/128

144/144 - 1s - 10ms/step - ia: 0.6745 - loss: 0.3853 - mae: 0.4923 - rmse: 0.6198 - smape: 0.8681 - val_ia: 0.4978 - val_loss: 1.1161 - val_mae: 0.8399 - val_rmse: 1.0194 - val_smape: 1.1664

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:21 505ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 42%|████▏     | 21/50 [1:17:15<2:18:40, 286.91s/trial, best loss: 0.2169016753577655]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

2292/2292 - 15s - 7ms/step - ia: 0.6732 - loss: 0.3712 - mae: 0.4794 - rmse: 0.5937 - smape: 0.8638 - val_ia: 0.2418 - val_loss: 0.5804 - val_mae: 0.6023 - val_rmse: 0.6421 - val_smape: 1.1108

Epoch 2/128

2292/2292 - 13s - 6ms/step - ia: 0.7324 - loss: 0.2584 - mae: 0.3999 - rmse: 0.4984 - smape: 0.7727 - val_ia: 0.2806 - val_loss: 0.4678 - val_mae: 0.5276 - val_rmse: 0.5620 - val_smape: 1.0534

Epoch 3/128

2292/2292 - 13s - 6ms/step - ia: 0.7498 - loss: 0.2285 - mae: 0.3745 - rmse: 0.4684 - smape: 0.7447 - val_ia: 0.2862 - val_loss: 0.4183 - val_mae: 0.5109 - val_rmse: 0.5396 - val_smape: 0.9968

Epoch 4/128

2292/2292 - 19s - 8ms/step - ia: 0.7613 - loss: 0.2099 - mae: 0.3584 - rmse: 0.4489 - smape: 0.7265 - val_ia: 0.3195 - val_loss: 0.2012 - val_mae: 0.3628 - val_rmse: 0.3946 - val_smape: 0.8520

Epoch 5/128

2292/2292 - 9s - 4ms/step - ia: 0.7674 - loss: 0.1993 - mae: 0.3496 - rmse: 0.4375 - smape: 0.7127 - val_ia: 0.3451 - val_loss: 0.1985 - val_mae: 0.3543 - val_rmse: 0.3831 - val_smape: 0.7616

Epoch 6/128

2292/2292 - 8s - 3ms/step - ia: 0.7737 - loss: 0.1922 - mae: 0.3421 - rmse: 0.4292 - smape: 0.7011 - val_ia: 0.3060 - val_loss: 0.2171 - val_mae: 0.3699 - val_rmse: 0.4071 - val_smape: 0.8287

Epoch 7/128

2292/2292 - 9s - 4ms/step - ia: 0.7759 - loss: 0.1885 - mae: 0.3392 - rmse: 0.4251 - smape: 0.7014 - val_ia: 0.3432 - val_loss: 0.1441 - val_mae: 0.3060 - val_rmse: 0.3374 - val_smape: 0.7025

Epoch 8/128

2292/2292 - 8s - 4ms/step - ia: 0.7788 - loss: 0.1827 - mae: 0.3331 - rmse: 0.4186 - smape: 0.6922 - val_ia: 0.3345 - val_loss: 0.1554 - val_mae: 0.3209 - val_rmse: 0.3557 - val_smape: 0.7243

Epoch 9/128

2292/2292 - 7s - 3ms/step - ia: 0.7826 - loss: 0.1771 - mae: 0.3280 - rmse: 0.4119 - smape: 0.6856 - val_ia: 0.3181 - val_loss: 0.2198 - val_mae: 0.3848 - val_rmse: 0.4128 - val_smape: 0.8199

Epoch 10/128

2292/2292 - 6s - 3ms/step - ia: 0.7855 - loss: 0.1741 - mae: 0.3245 - rmse: 0.4084 - smape: 0.6812 - val_ia: 0.3507 - val_loss: 0.1630 - val_mae: 0.3235 - val_rmse: 0.3522 - val_smape: 0.6886

Epoch 11/128

2292/2292 - 6s - 3ms/step - ia: 0.7869 - loss: 0.1723 - mae: 0.3227 - rmse: 0.4060 - smape: 0.6762 - val_ia: 0.3325 - val_loss: 0.2113 - val_mae: 0.3651 - val_rmse: 0.3941 - val_smape: 0.7583

Epoch 12/128

2292/2292 - 7s - 3ms/step - ia: 0.7879 - loss: 0.1698 - mae: 0.3207 - rmse: 0.4038 - smape: 0.6721 - val_ia: 0.3547 - val_loss: 0.1570 - val_mae: 0.3165 - val_rmse: 0.3522 - val_smape: 0.6978

Epoch 13/128

2292/2292 - 11s - 5ms/step - ia: 0.7883 - loss: 0.1686 - mae: 0.3198 - rmse: 0.4021 - smape: 0.6723 - val_ia: 0.3534 - val_loss: 0.1578 - val_mae: 0.3157 - val_rmse: 0.3429 - val_smape: 0.6864

Epoch 14/128

2292/2292 - 11s - 5ms/step - ia: 0.7906 - loss: 0.1648 - mae: 0.3162 - rmse: 0.3978 - smape: 0.6680 - val_ia: 0.3233 - val_loss: 0.2169 - val_mae: 0.3719 - val_rmse: 0.4039 - val_smape: 0.7900

Epoch 15/128

2292/2292 - 10s - 4ms/step - ia: 0.7903 - loss: 0.1670 - mae: 0.3176 - rmse: 0.4000 - smape: 0.6712 - val_ia: 0.3633 - val_loss: 0.1601 - val_mae: 0.3013 - val_rmse: 0.3322 - val_smape: 0.7010

Epoch 16/128

2292/2292 - 5s - 2ms/step - ia: 0.7904 - loss: 0.1648 - mae: 0.3160 - rmse: 0.3978 - smape: 0.6684 - val_ia: 0.3495 - val_loss: 0.1617 - val_mae: 0.3206 - val_rmse: 0.3508 - val_smape: 0.7063

Epoch 17/128

2292/2292 - 10s - 4ms/step - ia: 0.7915 - loss: 0.1651 - mae: 0.3166 - rmse: 0.3978 - smape: 0.6678 - val_ia: 0.3270 - val_loss: 0.2296 - val_mae: 0.3902 - val_rmse: 0.4172 - val_smape: 0.7707

Epoch 18/128

2292/2292 - 9s - 4ms/step - ia: 0.7931 - loss: 0.1616 - mae: 0.3130 - rmse: 0.3936 - smape: 0.6648 - val_ia: 0.3569 - val_loss: 0.1534 - val_mae: 0.3107 - val_rmse: 0.3410 - val_smape: 0.6892

Epoch 19/128

2292/2292 - 9s - 4ms/step - ia: 0.7955 - loss: 0.1587 - mae: 0.3097 - rmse: 0.3899 - smape: 0.6596 - val_ia: 0.3115 - val_loss: 0.2310 - val_mae: 0.3951 - val_rmse: 0.4226 - val_smape: 0.7848

Epoch 20/128

2292/2292 - 10s - 4ms/step - ia: 0.7936 - loss: 0.1609 - mae: 0.3125 - rmse: 0.3925 - smape: 0.6633 - val_ia: 0.3226 - val_loss: 0.2448 - val_mae: 0.3965 - val_rmse: 0.4254 - val_smape: 0.7790

Epoch 21/128

2292/2292 - 11s - 5ms/step - ia: 0.7940 - loss: 0.1605 - mae: 0.3113 - rmse: 0.3924 - smape: 0.6634 - val_ia: 0.3444 - val_loss: 0.1603 - val_mae: 0.3200 - val_rmse: 0.3491 - val_smape: 0.7234

Epoch 22/128

2292/2292 - 16s - 7ms/step - ia: 0.7954 - loss: 0.1594 - mae: 0.3098 - rmse: 0.3910 - smape: 0.6603 - val_ia: 0.3502 - val_loss: 0.1639 - val_mae: 0.3146 - val_rmse: 0.3476 - val_smape: 0.7043

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 42s 264ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 44%|████▍     | 22/50 [1:21:02<2:05:33, 269.05s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 16s - 7ms/step - ia: 0.4744 - loss: 0.8157 - mae: 0.7272 - rmse: 0.8884 - smape: 1.1771 - val_ia: 0.1730 - val_loss: 1.3493 - val_mae: 0.9867 - val_rmse: 1.0253 - val_smape: 1.3694

Epoch 2/64

2292/2292 - 7s - 3ms/step - ia: 0.5404 - loss: 0.6955 - mae: 0.6676 - rmse: 0.8217 - smape: 1.0734 - val_ia: 0.1695 - val_loss: 1.4112 - val_mae: 1.0095 - val_rmse: 1.0494 - val_smape: 1.3711

Epoch 3/64

2292/2292 - 7s - 3ms/step - ia: 0.5497 - loss: 0.6676 - mae: 0.6535 - rmse: 0.8047 - smape: 1.0566 - val_ia: 0.1659 - val_loss: 1.4273 - val_mae: 1.0182 - val_rmse: 1.0573 - val_smape: 1.3805

Epoch 4/64

2292/2292 - 6s - 3ms/step - ia: 0.5602 - loss: 0.6366 - mae: 0.6363 - rmse: 0.7854 - smape: 1.0375 - val_ia: 0.1650 - val_loss: 1.4583 - val_mae: 1.0280 - val_rmse: 1.0671 - val_smape: 1.3820

Epoch 5/64

2292/2292 - 7s - 3ms/step - ia: 0.5652 - loss: 0.6110 - mae: 0.6237 - rmse: 0.7702 - smape: 1.0277 - val_ia: 0.1662 - val_loss: 1.4366 - val_mae: 1.0165 - val_rmse: 1.0565 - val_smape: 1.3702

Epoch 6/64

2292/2292 - 7s - 3ms/step - ia: 0.5705 - loss: 0.5940 - mae: 0.6161 - rmse: 0.7588 - smape: 1.0220 - val_ia: 0.1675 - val_loss: 1.4237 - val_mae: 1.0087 - val_rmse: 1.0490 - val_smape: 1.3635

Epoch 7/64

2292/2292 - 12s - 5ms/step - ia: 0.5724 - loss: 0.5770 - mae: 0.6074 - rmse: 0.7487 - smape: 1.0164 - val_ia: 0.1669 - val_loss: 1.4163 - val_mae: 1.0099 - val_rmse: 1.0499 - val_smape: 1.3695

Epoch 8/64

2292/2292 - 13s - 6ms/step - ia: 0.5814 - loss: 0.5570 - mae: 0.5962 - rmse: 0.7345 - smape: 1.0027 - val_ia: 0.1681 - val_loss: 1.4022 - val_mae: 1.0026 - val_rmse: 1.0426 - val_smape: 1.3648

Epoch 9/64

2292/2292 - 10s - 5ms/step - ia: 0.5839 - loss: 0.5432 - mae: 0.5875 - rmse: 0.7264 - smape: 0.9915 - val_ia: 0.1694 - val_loss: 1.3502 - val_mae: 0.9842 - val_rmse: 1.0242 - val_smape: 1.3606

Epoch 10/64

2292/2292 - 10s - 4ms/step - ia: 0.5877 - loss: 0.5292 - mae: 0.5808 - rmse: 0.7163 - smape: 0.9841 - val_ia: 0.1692 - val_loss: 1.3860 - val_mae: 0.9956 - val_rmse: 1.0360 - val_smape: 1.3624

Epoch 11/64

2292/2292 - 9s - 4ms/step - ia: 0.5914 - loss: 0.5173 - mae: 0.5755 - rmse: 0.7083 - smape: 0.9813 - val_ia: 0.1704 - val_loss: 1.3432 - val_mae: 0.9794 - val_rmse: 1.0199 - val_smape: 1.3562

Epoch 12/64

2292/2292 - 10s - 4ms/step - ia: 0.5973 - loss: 0.5023 - mae: 0.5670 - rmse: 0.6983 - smape: 0.9710 - val_ia: 0.1698 - val_loss: 1.3549 - val_mae: 0.9859 - val_rmse: 1.0263 - val_smape: 1.3644

Epoch 13/64

2292/2292 - 9s - 4ms/step - ia: 0.6003 - loss: 0.4931 - mae: 0.5614 - rmse: 0.6921 - smape: 0.9647 - val_ia: 0.1719 - val_loss: 1.3264 - val_mae: 0.9717 - val_rmse: 1.0127 - val_smape: 1.3533

Epoch 14/64

2292/2292 - 6s - 3ms/step - ia: 0.6054 - loss: 0.4821 - mae: 0.5546 - rmse: 0.6840 - smape: 0.9571 - val_ia: 0.1730 - val_loss: 1.3316 - val_mae: 0.9692 - val_rmse: 1.0111 - val_smape: 1.3453

Epoch 15/64

2292/2292 - 6s - 3ms/step - ia: 0.6086 - loss: 0.4700 - mae: 0.5485 - rmse: 0.6756 - smape: 0.9501 - val_ia: 0.1743 - val_loss: 1.2939 - val_mae: 0.9538 - val_rmse: 0.9960 - val_smape: 1.3399

Epoch 16/64

2292/2292 - 6s - 3ms/step - ia: 0.6121 - loss: 0.4636 - mae: 0.5445 - rmse: 0.6704 - smape: 0.9448 - val_ia: 0.1748 - val_loss: 1.2680 - val_mae: 0.9453 - val_rmse: 0.9872 - val_smape: 1.3419

Epoch 17/64

2292/2292 - 14s - 6ms/step - ia: 0.6163 - loss: 0.4550 - mae: 0.5396 - rmse: 0.6639 - smape: 0.9399 - val_ia: 0.1763 - val_loss: 1.2530 - val_mae: 0.9342 - val_rmse: 0.9767 - val_smape: 1.3312

Epoch 18/64

2292/2292 - 9s - 4ms/step - ia: 0.6183 - loss: 0.4484 - mae: 0.5350 - rmse: 0.6593 - smape: 0.9341 - val_ia: 0.1761 - val_loss: 1.2737 - val_mae: 0.9434 - val_rmse: 0.9861 - val_smape: 1.3361

Epoch 19/64

2292/2292 - 5s - 2ms/step - ia: 0.6218 - loss: 0.4456 - mae: 0.5331 - rmse: 0.6573 - smape: 0.9326 - val_ia: 0.1778 - val_loss: 1.2306 - val_mae: 0.9236 - val_rmse: 0.9666 - val_smape: 1.3260

Epoch 20/64

2292/2292 - 5s - 2ms/step - ia: 0.6237 - loss: 0.4385 - mae: 0.5300 - rmse: 0.6524 - smape: 0.9287 - val_ia: 0.1781 - val_loss: 1.2274 - val_mae: 0.9189 - val_rmse: 0.9624 - val_smape: 1.3200

Epoch 21/64

2292/2292 - 6s - 3ms/step - ia: 0.6254 - loss: 0.4336 - mae: 0.5273 - rmse: 0.6486 - smape: 0.9260 - val_ia: 0.1778 - val_loss: 1.2432 - val_mae: 0.9272 - val_rmse: 0.9708 - val_smape: 1.3274

Epoch 22/64

2292/2292 - 7s - 3ms/step - ia: 0.6302 - loss: 0.4277 - mae: 0.5214 - rmse: 0.6441 - smape: 0.9169 - val_ia: 0.1785 - val_loss: 1.2315 - val_mae: 0.9200 - val_rmse: 0.9637 - val_smape: 1.3231

Epoch 23/64

2292/2292 - 9s - 4ms/step - ia: 0.6314 - loss: 0.4251 - mae: 0.5198 - rmse: 0.6420 - smape: 0.9146 - val_ia: 0.1798 - val_loss: 1.1999 - val_mae: 0.9041 - val_rmse: 0.9480 - val_smape: 1.3136

Epoch 24/64

2292/2292 - 7s - 3ms/step - ia: 0.6324 - loss: 0.4226 - mae: 0.5194 - rmse: 0.6401 - smape: 0.9158 - val_ia: 0.1800 - val_loss: 1.1978 - val_mae: 0.9010 - val_rmse: 0.9451 - val_smape: 1.3106

Epoch 25/64

2292/2292 - 12s - 5ms/step - ia: 0.6348 - loss: 0.4172 - mae: 0.5161 - rmse: 0.6356 - smape: 0.9143 - val_ia: 0.1798 - val_loss: 1.2208 - val_mae: 0.9114 - val_rmse: 0.9556 - val_smape: 1.3163

Epoch 26/64

2292/2292 - 8s - 4ms/step - ia: 0.6392 - loss: 0.4080 - mae: 0.5094 - rmse: 0.6286 - smape: 0.9046 - val_ia: 0.1806 - val_loss: 1.1897 - val_mae: 0.8969 - val_rmse: 0.9413 - val_smape: 1.3100

Epoch 27/64

2292/2292 - 8s - 3ms/step - ia: 0.6413 - loss: 0.4062 - mae: 0.5085 - rmse: 0.6276 - smape: 0.9016 - val_ia: 0.1811 - val_loss: 1.1765 - val_mae: 0.8882 - val_rmse: 0.9327 - val_smape: 1.3029

Epoch 28/64

2292/2292 - 11s - 5ms/step - ia: 0.6422 - loss: 0.4034 - mae: 0.5058 - rmse: 0.6252 - smape: 0.9020 - val_ia: 0.1808 - val_loss: 1.1888 - val_mae: 0.8915 - val_rmse: 0.9364 - val_smape: 1.3020

Epoch 29/64

2292/2292 - 7s - 3ms/step - ia: 0.6437 - loss: 0.4011 - mae: 0.5048 - rmse: 0.6237 - smape: 0.8988 - val_ia: 0.1812 - val_loss: 1.1813 - val_mae: 0.8866 - val_rmse: 0.9314 - val_smape: 1.2988

Epoch 30/64

2292/2292 - 6s - 3ms/step - ia: 0.6490 - loss: 0.3933 - mae: 0.4983 - rmse: 0.6173 - smape: 0.8924 - val_ia: 0.1820 - val_loss: 1.1623 - val_mae: 0.8778 - val_rmse: 0.9224 - val_smape: 1.2970

Epoch 31/64

2292/2292 - 11s - 5ms/step - ia: 0.6484 - loss: 0.3946 - mae: 0.4986 - rmse: 0.6182 - smape: 0.8911 - val_ia: 0.1820 - val_loss: 1.1658 - val_mae: 0.8752 - val_rmse: 0.9199 - val_smape: 1.2905

Epoch 32/64

2292/2292 - 11s - 5ms/step - ia: 0.6516 - loss: 0.3864 - mae: 0.4940 - rmse: 0.6119 - smape: 0.8865 - val_ia: 0.1827 - val_loss: 1.1420 - val_mae: 0.8655 - val_rmse: 0.9099 - val_smape: 1.2885

Epoch 33/64

2292/2292 - 17s - 7ms/step - ia: 0.6524 - loss: 0.3853 - mae: 0.4927 - rmse: 0.6104 - smape: 0.8880 - val_ia: 0.1827 - val_loss: 1.1367 - val_mae: 0.8611 - val_rmse: 0.9057 - val_smape: 1.2840

Epoch 34/64

2292/2292 - 14s - 6ms/step - ia: 0.6550 - loss: 0.3831 - mae: 0.4912 - rmse: 0.6085 - smape: 0.8840 - val_ia: 0.1830 - val_loss: 1.1401 - val_mae: 0.8617 - val_rmse: 0.9062 - val_smape: 1.2848

Epoch 35/64

2292/2292 - 12s - 5ms/step - ia: 0.6567 - loss: 0.3799 - mae: 0.4883 - rmse: 0.6061 - smape: 0.8809 - val_ia: 0.1830 - val_loss: 1.1301 - val_mae: 0.8545 - val_rmse: 0.8992 - val_smape: 1.2778

Epoch 36/64

2292/2292 - 11s - 5ms/step - ia: 0.6590 - loss: 0.3759 - mae: 0.4854 - rmse: 0.6029 - smape: 0.8761 - val_ia: 0.1838 - val_loss: 1.1131 - val_mae: 0.8459 - val_rmse: 0.8904 - val_smape: 1.2748

Epoch 37/64

2292/2292 - 6s - 3ms/step - ia: 0.6612 - loss: 0.3718 - mae: 0.4828 - rmse: 0.5999 - smape: 0.8741 - val_ia: 0.1842 - val_loss: 1.1033 - val_mae: 0.8408 - val_rmse: 0.8852 - val_smape: 1.2718

Epoch 38/64

2292/2292 - 6s - 2ms/step - ia: 0.6643 - loss: 0.3669 - mae: 0.4787 - rmse: 0.5954 - smape: 0.8679 - val_ia: 0.1843 - val_loss: 1.1371 - val_mae: 0.8546 - val_rmse: 0.8992 - val_smape: 1.2762

Epoch 39/64

2292/2292 - 6s - 3ms/step - ia: 0.6662 - loss: 0.3616 - mae: 0.4770 - rmse: 0.5915 - smape: 0.8703 - val_ia: 0.1850 - val_loss: 1.1212 - val_mae: 0.8465 - val_rmse: 0.8909 - val_smape: 1.2728

Epoch 40/64

2292/2292 - 7s - 3ms/step - ia: 0.6664 - loss: 0.3631 - mae: 0.4770 - rmse: 0.5926 - smape: 0.8677 - val_ia: 0.1859 - val_loss: 1.1139 - val_mae: 0.8423 - val_rmse: 0.8866 - val_smape: 1.2714

Epoch 41/64

2292/2292 - 11s - 5ms/step - ia: 0.6679 - loss: 0.3599 - mae: 0.4758 - rmse: 0.5899 - smape: 0.8668 - val_ia: 0.1856 - val_loss: 1.1095 - val_mae: 0.8372 - val_rmse: 0.8817 - val_smape: 1.2641

Epoch 42/64

2292/2292 - 11s - 5ms/step - ia: 0.6706 - loss: 0.3557 - mae: 0.4717 - rmse: 0.5863 - smape: 0.8608 - val_ia: 0.1867 - val_loss: 1.0803 - val_mae: 0.8240 - val_rmse: 0.8682 - val_smape: 1.2601

Epoch 43/64

2292/2292 - 13s - 5ms/step - ia: 0.6727 - loss: 0.3542 - mae: 0.4699 - rmse: 0.5850 - smape: 0.8591 - val_ia: 0.1871 - val_loss: 1.0802 - val_mae: 0.8226 - val_rmse: 0.8667 - val_smape: 1.2587

Epoch 44/64

2292/2292 - 5s - 2ms/step - ia: 0.6743 - loss: 0.3490 - mae: 0.4665 - rmse: 0.5807 - smape: 0.8534 - val_ia: 0.1874 - val_loss: 1.0789 - val_mae: 0.8190 - val_rmse: 0.8633 - val_smape: 1.2527

Epoch 45/64

2292/2292 - 5s - 2ms/step - ia: 0.6763 - loss: 0.3454 - mae: 0.4648 - rmse: 0.5779 - smape: 0.8511 - val_ia: 0.1884 - val_loss: 1.0600 - val_mae: 0.8100 - val_rmse: 0.8542 - val_smape: 1.2490

Epoch 46/64

2292/2292 - 5s - 2ms/step - ia: 0.6765 - loss: 0.3447 - mae: 0.4645 - rmse: 0.5774 - smape: 0.8545 - val_ia: 0.1890 - val_loss: 1.0646 - val_mae: 0.8114 - val_rmse: 0.8556 - val_smape: 1.2461

Epoch 47/64

2292/2292 - 7s - 3ms/step - ia: 0.6778 - loss: 0.3452 - mae: 0.4643 - rmse: 0.5769 - smape: 0.8534 - val_ia: 0.1909 - val_loss: 1.0327 - val_mae: 0.7982 - val_rmse: 0.8421 - val_smape: 1.2439

Epoch 48/64

2292/2292 - 14s - 6ms/step - ia: 0.6781 - loss: 0.3430 - mae: 0.4632 - rmse: 0.5756 - smape: 0.8514 - val_ia: 0.1904 - val_loss: 1.0465 - val_mae: 0.8012 - val_rmse: 0.8453 - val_smape: 1.2400

Epoch 49/64

2292/2292 - 6s - 3ms/step - ia: 0.6813 - loss: 0.3373 - mae: 0.4586 - rmse: 0.5706 - smape: 0.8445 - val_ia: 0.1915 - val_loss: 1.0514 - val_mae: 0.8045 - val_rmse: 0.8486 - val_smape: 1.2436

Epoch 50/64

2292/2292 - 6s - 3ms/step - ia: 0.6813 - loss: 0.3372 - mae: 0.4579 - rmse: 0.5705 - smape: 0.8436 - val_ia: 0.1926 - val_loss: 1.0276 - val_mae: 0.7929 - val_rmse: 0.8370 - val_smape: 1.2365

Epoch 51/64

2292/2292 - 11s - 5ms/step - ia: 0.6828 - loss: 0.3360 - mae: 0.4576 - rmse: 0.5697 - smape: 0.8430 - val_ia: 0.1931 - val_loss: 1.0224 - val_mae: 0.7895 - val_rmse: 0.8335 - val_smape: 1.2350

Epoch 52/64

2292/2292 - 14s - 6ms/step - ia: 0.6842 - loss: 0.3330 - mae: 0.4559 - rmse: 0.5672 - smape: 0.8426 - val_ia: 0.1932 - val_loss: 1.0333 - val_mae: 0.7944 - val_rmse: 0.8384 - val_smape: 1.2374

Epoch 53/64

2292/2292 - 8s - 3ms/step - ia: 0.6841 - loss: 0.3317 - mae: 0.4546 - rmse: 0.5658 - smape: 0.8399 - val_ia: 0.1939 - val_loss: 1.0242 - val_mae: 0.7884 - val_rmse: 0.8325 - val_smape: 1.2302

Epoch 54/64

2292/2292 - 9s - 4ms/step - ia: 0.6875 - loss: 0.3277 - mae: 0.4520 - rmse: 0.5627 - smape: 0.8361 - val_ia: 0.1939 - val_loss: 1.0136 - val_mae: 0.7817 - val_rmse: 0.8259 - val_smape: 1.2239

Epoch 55/64

2292/2292 - 9s - 4ms/step - ia: 0.6877 - loss: 0.3283 - mae: 0.4513 - rmse: 0.5633 - smape: 0.8338 - val_ia: 0.1963 - val_loss: 0.9969 - val_mae: 0.7769 - val_rmse: 0.8208 - val_smape: 1.2278

Epoch 56/64

2292/2292 - 16s - 7ms/step - ia: 0.6894 - loss: 0.3253 - mae: 0.4491 - rmse: 0.5606 - smape: 0.8306 - val_ia: 0.1963 - val_loss: 1.0097 - val_mae: 0.7803 - val_rmse: 0.8243 - val_smape: 1.2244

Epoch 57/64

2292/2292 - 15s - 6ms/step - ia: 0.6885 - loss: 0.3242 - mae: 0.4489 - rmse: 0.5593 - smape: 0.8347 - val_ia: 0.1969 - val_loss: 0.9937 - val_mae: 0.7722 - val_rmse: 0.8162 - val_smape: 1.2189

Epoch 58/64

2292/2292 - 10s - 4ms/step - ia: 0.6906 - loss: 0.3225 - mae: 0.4469 - rmse: 0.5578 - smape: 0.8283 - val_ia: 0.1971 - val_loss: 0.9837 - val_mae: 0.7656 - val_rmse: 0.8097 - val_smape: 1.2110

Epoch 59/64

2292/2292 - 10s - 4ms/step - ia: 0.6929 - loss: 0.3188 - mae: 0.4450 - rmse: 0.5543 - smape: 0.8304 - val_ia: 0.1974 - val_loss: 1.0278 - val_mae: 0.7866 - val_rmse: 0.8306 - val_smape: 1.2253

Epoch 60/64

2292/2292 - 14s - 6ms/step - ia: 0.6939 - loss: 0.3196 - mae: 0.4445 - rmse: 0.5554 - smape: 0.8256 - val_ia: 0.1979 - val_loss: 0.9911 - val_mae: 0.7672 - val_rmse: 0.8112 - val_smape: 1.2104

Epoch 61/64

2292/2292 - 15s - 7ms/step - ia: 0.6928 - loss: 0.3190 - mae: 0.4442 - rmse: 0.5546 - smape: 0.8264 - val_ia: 0.1992 - val_loss: 0.9966 - val_mae: 0.7715 - val_rmse: 0.8153 - val_smape: 1.2164

Epoch 62/64

2292/2292 - 15s - 7ms/step - ia: 0.6943 - loss: 0.3183 - mae: 0.4434 - rmse: 0.5538 - smape: 0.8242 - val_ia: 0.1997 - val_loss: 0.9997 - val_mae: 0.7729 - val_rmse: 0.8167 - val_smape: 1.2164

Epoch 63/64

2292/2292 - 15s - 6ms/step - ia: 0.6953 - loss: 0.3147 - mae: 0.4409 - rmse: 0.5510 - smape: 0.8189 - val_ia: 0.2000 - val_loss: 1.0071 - val_mae: 0.7755 - val_rmse: 0.8192 - val_smape: 1.2167

Epoch 64/64

2292/2292 - 7s - 3ms/step - ia: 0.6956 - loss: 0.3144 - mae: 0.4417 - rmse: 0.5508 - smape: 0.8259 - val_ia: 0.2009 - val_loss: 0.9805 - val_mae: 0.7624 - val_rmse: 0.8063 - val_smape: 1.2071

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 32s 201ms/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 46%|████▌     | 23/50 [1:31:14<2:47:18, 371.81s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 19s - 8ms/step - ia: 0.6073 - loss: 0.4579 - mae: 0.5393 - rmse: 0.6649 - smape: 0.9472 - val_ia: 0.1653 - val_loss: 1.4468 - val_mae: 1.0165 - val_rmse: 1.0596 - val_smape: 1.3669

Epoch 2/128

2292/2292 - 15s - 7ms/step - ia: 0.6688 - loss: 0.3439 - mae: 0.4670 - rmse: 0.5772 - smape: 0.8572 - val_ia: 0.1823 - val_loss: 1.1359 - val_mae: 0.8657 - val_rmse: 0.9097 - val_smape: 1.2846

Epoch 3/128

2292/2292 - 8s - 3ms/step - ia: 0.7134 - loss: 0.2748 - mae: 0.4130 - rmse: 0.5151 - smape: 0.7995 - val_ia: 0.2076 - val_loss: 0.8675 - val_mae: 0.7379 - val_rmse: 0.7832 - val_smape: 1.1957

Epoch 4/128

2292/2292 - 9s - 4ms/step - ia: 0.7395 - loss: 0.2358 - mae: 0.3795 - rmse: 0.4766 - smape: 0.7540 - val_ia: 0.2283 - val_loss: 0.7380 - val_mae: 0.6666 - val_rmse: 0.7126 - val_smape: 1.1170

Epoch 5/128

2292/2292 - 15s - 7ms/step - ia: 0.7569 - loss: 0.2131 - mae: 0.3590 - rmse: 0.4529 - smape: 0.7236 - val_ia: 0.2408 - val_loss: 0.7065 - val_mae: 0.6436 - val_rmse: 0.6890 - val_smape: 1.0853

Epoch 6/128

2292/2292 - 10s - 4ms/step - ia: 0.7680 - loss: 0.1968 - mae: 0.3443 - rmse: 0.4350 - smape: 0.7056 - val_ia: 0.2575 - val_loss: 0.6070 - val_mae: 0.5903 - val_rmse: 0.6351 - val_smape: 1.0477

Epoch 7/128

2292/2292 - 9s - 4ms/step - ia: 0.7766 - loss: 0.1847 - mae: 0.3321 - rmse: 0.4211 - smape: 0.6904 - val_ia: 0.2661 - val_loss: 0.6185 - val_mae: 0.5805 - val_rmse: 0.6260 - val_smape: 1.0090

Epoch 8/128

2292/2292 - 11s - 5ms/step - ia: 0.7828 - loss: 0.1747 - mae: 0.3224 - rmse: 0.4093 - smape: 0.6777 - val_ia: 0.2693 - val_loss: 0.5850 - val_mae: 0.5679 - val_rmse: 0.6111 - val_smape: 1.0136

Epoch 9/128

2292/2292 - 10s - 4ms/step - ia: 0.7903 - loss: 0.1656 - mae: 0.3128 - rmse: 0.3982 - smape: 0.6650 - val_ia: 0.2732 - val_loss: 0.5540 - val_mae: 0.5541 - val_rmse: 0.5972 - val_smape: 1.0139

Epoch 10/128

2292/2292 - 9s - 4ms/step - ia: 0.7950 - loss: 0.1587 - mae: 0.3056 - rmse: 0.3898 - smape: 0.6567 - val_ia: 0.2760 - val_loss: 0.5535 - val_mae: 0.5505 - val_rmse: 0.5932 - val_smape: 0.9982

Epoch 11/128

2292/2292 - 8s - 3ms/step - ia: 0.8006 - loss: 0.1518 - mae: 0.2982 - rmse: 0.3814 - smape: 0.6476 - val_ia: 0.3017 - val_loss: 0.4394 - val_mae: 0.4848 - val_rmse: 0.5323 - val_smape: 0.9497

Epoch 12/128

2292/2292 - 11s - 5ms/step - ia: 0.8053 - loss: 0.1460 - mae: 0.2917 - rmse: 0.3737 - smape: 0.6409 - val_ia: 0.2803 - val_loss: 0.5269 - val_mae: 0.5389 - val_rmse: 0.5826 - val_smape: 0.9950

Epoch 13/128

2292/2292 - 9s - 4ms/step - ia: 0.8096 - loss: 0.1405 - mae: 0.2855 - rmse: 0.3664 - smape: 0.6324 - val_ia: 0.2975 - val_loss: 0.4560 - val_mae: 0.4959 - val_rmse: 0.5425 - val_smape: 0.9442

Epoch 14/128

2292/2292 - 12s - 5ms/step - ia: 0.8134 - loss: 0.1353 - mae: 0.2798 - rmse: 0.3596 - smape: 0.6238 - val_ia: 0.3082 - val_loss: 0.4231 - val_mae: 0.4739 - val_rmse: 0.5221 - val_smape: 0.9074

Epoch 15/128

2292/2292 - 9s - 4ms/step - ia: 0.8177 - loss: 0.1306 - mae: 0.2744 - rmse: 0.3527 - smape: 0.6183 - val_ia: 0.3083 - val_loss: 0.4476 - val_mae: 0.4815 - val_rmse: 0.5317 - val_smape: 0.9356

Epoch 16/128

2292/2292 - 9s - 4ms/step - ia: 0.8209 - loss: 0.1257 - mae: 0.2685 - rmse: 0.3462 - smape: 0.6094 - val_ia: 0.3171 - val_loss: 0.4206 - val_mae: 0.4640 - val_rmse: 0.5140 - val_smape: 0.8893

Epoch 17/128

2292/2292 - 7s - 3ms/step - ia: 0.8247 - loss: 0.1212 - mae: 0.2629 - rmse: 0.3393 - smape: 0.6013 - val_ia: 0.3098 - val_loss: 0.4052 - val_mae: 0.4651 - val_rmse: 0.5148 - val_smape: 0.8873

Epoch 18/128

2292/2292 - 10s - 4ms/step - ia: 0.8285 - loss: 0.1170 - mae: 0.2577 - rmse: 0.3338 - smape: 0.5933 - val_ia: 0.3178 - val_loss: 0.3832 - val_mae: 0.4502 - val_rmse: 0.5011 - val_smape: 0.8734

Epoch 19/128

2292/2292 - 10s - 4ms/step - ia: 0.8327 - loss: 0.1123 - mae: 0.2519 - rmse: 0.3264 - smape: 0.5854 - val_ia: 0.3125 - val_loss: 0.3872 - val_mae: 0.4577 - val_rmse: 0.5080 - val_smape: 0.8838

Epoch 20/128

2292/2292 - 11s - 5ms/step - ia: 0.8360 - loss: 0.1082 - mae: 0.2468 - rmse: 0.3205 - smape: 0.5765 - val_ia: 0.3177 - val_loss: 0.3870 - val_mae: 0.4527 - val_rmse: 0.5026 - val_smape: 0.8690

Epoch 21/128

2292/2292 - 28s - 12ms/step - ia: 0.8386 - loss: 0.1047 - mae: 0.2420 - rmse: 0.3151 - smape: 0.5678 - val_ia: 0.3120 - val_loss: 0.3897 - val_mae: 0.4600 - val_rmse: 0.5091 - val_smape: 0.8739

Epoch 22/128

2292/2292 - 16s - 7ms/step - ia: 0.8429 - loss: 0.1006 - mae: 0.2371 - rmse: 0.3089 - smape: 0.5600 - val_ia: 0.3129 - val_loss: 0.3899 - val_mae: 0.4608 - val_rmse: 0.5093 - val_smape: 0.8644

Epoch 23/128

2292/2292 - 11s - 5ms/step - ia: 0.8458 - loss: 0.0972 - mae: 0.2322 - rmse: 0.3031 - smape: 0.5517 - val_ia: 0.3130 - val_loss: 0.4026 - val_mae: 0.4644 - val_rmse: 0.5116 - val_smape: 0.8489

Epoch 24/128

2292/2292 - 9s - 4ms/step - ia: 0.8496 - loss: 0.0938 - mae: 0.2275 - rmse: 0.2976 - smape: 0.5416 - val_ia: 0.3145 - val_loss: 0.3714 - val_mae: 0.4540 - val_rmse: 0.5002 - val_smape: 0.8525

Epoch 25/128

2292/2292 - 9s - 4ms/step - ia: 0.8517 - loss: 0.0911 - mae: 0.2238 - rmse: 0.2929 - smape: 0.5345 - val_ia: 0.3110 - val_loss: 0.4135 - val_mae: 0.4727 - val_rmse: 0.5186 - val_smape: 0.8641

Epoch 26/128

2292/2292 - 7s - 3ms/step - ia: 0.8551 - loss: 0.0878 - mae: 0.2191 - rmse: 0.2877 - smape: 0.5262 - val_ia: 0.3166 - val_loss: 0.3630 - val_mae: 0.4421 - val_rmse: 0.4867 - val_smape: 0.8250

Epoch 27/128

2292/2292 - 10s - 4ms/step - ia: 0.8574 - loss: 0.0852 - mae: 0.2153 - rmse: 0.2830 - smape: 0.5206 - val_ia: 0.3186 - val_loss: 0.3699 - val_mae: 0.4480 - val_rmse: 0.4920 - val_smape: 0.8340

Epoch 28/128

2292/2292 - 7s - 3ms/step - ia: 0.8600 - loss: 0.0826 - mae: 0.2117 - rmse: 0.2788 - smape: 0.5134 - val_ia: 0.3221 - val_loss: 0.3745 - val_mae: 0.4460 - val_rmse: 0.4892 - val_smape: 0.8170

Epoch 29/128

2292/2292 - 8s - 3ms/step - ia: 0.8619 - loss: 0.0807 - mae: 0.2089 - rmse: 0.2753 - smape: 0.5090 - val_ia: 0.3205 - val_loss: 0.3625 - val_mae: 0.4404 - val_rmse: 0.4830 - val_smape: 0.8215

Epoch 30/128

2292/2292 - 11s - 5ms/step - ia: 0.8636 - loss: 0.0788 - mae: 0.2064 - rmse: 0.2721 - smape: 0.5046 - val_ia: 0.3217 - val_loss: 0.3484 - val_mae: 0.4369 - val_rmse: 0.4791 - val_smape: 0.8260

Epoch 31/128

2292/2292 - 10s - 4ms/step - ia: 0.8654 - loss: 0.0770 - mae: 0.2039 - rmse: 0.2691 - smape: 0.4998 - val_ia: 0.3268 - val_loss: 0.3292 - val_mae: 0.4221 - val_rmse: 0.4639 - val_smape: 0.7976

Epoch 32/128

2292/2292 - 9s - 4ms/step - ia: 0.8668 - loss: 0.0757 - mae: 0.2022 - rmse: 0.2667 - smape: 0.4981 - val_ia: 0.3222 - val_loss: 0.3402 - val_mae: 0.4316 - val_rmse: 0.4729 - val_smape: 0.8258

Epoch 33/128

2292/2292 - 7s - 3ms/step - ia: 0.8684 - loss: 0.0741 - mae: 0.1999 - rmse: 0.2635 - smape: 0.4927 - val_ia: 0.3190 - val_loss: 0.3320 - val_mae: 0.4272 - val_rmse: 0.4681 - val_smape: 0.8183

Epoch 34/128

2292/2292 - 7s - 3ms/step - ia: 0.8694 - loss: 0.0730 - mae: 0.1983 - rmse: 0.2616 - smape: 0.4913 - val_ia: 0.3238 - val_loss: 0.3458 - val_mae: 0.4294 - val_rmse: 0.4707 - val_smape: 0.7947

Epoch 35/128

2292/2292 - 10s - 5ms/step - ia: 0.8700 - loss: 0.0719 - mae: 0.1970 - rmse: 0.2592 - smape: 0.4885 - val_ia: 0.3204 - val_loss: 0.3154 - val_mae: 0.4200 - val_rmse: 0.4606 - val_smape: 0.8201

Epoch 36/128

2292/2292 - 9s - 4ms/step - ia: 0.8715 - loss: 0.0707 - mae: 0.1954 - rmse: 0.2577 - smape: 0.4856 - val_ia: 0.3237 - val_loss: 0.3059 - val_mae: 0.4141 - val_rmse: 0.4541 - val_smape: 0.8042

Epoch 37/128

2292/2292 - 7s - 3ms/step - ia: 0.8720 - loss: 0.0699 - mae: 0.1940 - rmse: 0.2557 - smape: 0.4828 - val_ia: 0.3321 - val_loss: 0.3244 - val_mae: 0.4142 - val_rmse: 0.4552 - val_smape: 0.7796

Epoch 38/128

2292/2292 - 8s - 4ms/step - ia: 0.8730 - loss: 0.0690 - mae: 0.1930 - rmse: 0.2540 - smape: 0.4836 - val_ia: 0.3343 - val_loss: 0.3238 - val_mae: 0.4154 - val_rmse: 0.4565 - val_smape: 0.7758

Epoch 39/128

2292/2292 - 6s - 3ms/step - ia: 0.8735 - loss: 0.0680 - mae: 0.1916 - rmse: 0.2525 - smape: 0.4794 - val_ia: 0.3324 - val_loss: 0.3006 - val_mae: 0.4044 - val_rmse: 0.4458 - val_smape: 0.7802

Epoch 40/128

2292/2292 - 8s - 4ms/step - ia: 0.8750 - loss: 0.0673 - mae: 0.1905 - rmse: 0.2510 - smape: 0.4781 - val_ia: 0.3277 - val_loss: 0.3123 - val_mae: 0.4133 - val_rmse: 0.4543 - val_smape: 0.7938

Epoch 41/128

2292/2292 - 13s - 6ms/step - ia: 0.8756 - loss: 0.0665 - mae: 0.1894 - rmse: 0.2496 - smape: 0.4748 - val_ia: 0.3316 - val_loss: 0.3029 - val_mae: 0.4077 - val_rmse: 0.4484 - val_smape: 0.7940

Epoch 42/128

2292/2292 - 12s - 5ms/step - ia: 0.8765 - loss: 0.0656 - mae: 0.1882 - rmse: 0.2480 - smape: 0.4743 - val_ia: 0.3329 - val_loss: 0.3019 - val_mae: 0.4028 - val_rmse: 0.4436 - val_smape: 0.7812

Epoch 43/128

2292/2292 - 7s - 3ms/step - ia: 0.8762 - loss: 0.0655 - mae: 0.1879 - rmse: 0.2477 - smape: 0.4729 - val_ia: 0.3308 - val_loss: 0.2848 - val_mae: 0.4008 - val_rmse: 0.4411 - val_smape: 0.7930

Epoch 44/128

2292/2292 - 9s - 4ms/step - ia: 0.8775 - loss: 0.0647 - mae: 0.1867 - rmse: 0.2461 - smape: 0.4700 - val_ia: 0.3349 - val_loss: 0.2804 - val_mae: 0.3921 - val_rmse: 0.4331 - val_smape: 0.7675

Epoch 45/128

2292/2292 - 11s - 5ms/step - ia: 0.8781 - loss: 0.0639 - mae: 0.1858 - rmse: 0.2451 - smape: 0.4713 - val_ia: 0.3370 - val_loss: 0.2991 - val_mae: 0.4026 - val_rmse: 0.4438 - val_smape: 0.7730

Epoch 46/128

2292/2292 - 10s - 4ms/step - ia: 0.8785 - loss: 0.0634 - mae: 0.1850 - rmse: 0.2436 - smape: 0.4675 - val_ia: 0.3369 - val_loss: 0.3043 - val_mae: 0.4061 - val_rmse: 0.4478 - val_smape: 0.7655

Epoch 47/128

2292/2292 - 5s - 2ms/step - ia: 0.8795 - loss: 0.0626 - mae: 0.1840 - rmse: 0.2423 - smape: 0.4658 - val_ia: 0.3383 - val_loss: 0.2698 - val_mae: 0.3848 - val_rmse: 0.4254 - val_smape: 0.7572

Epoch 48/128

2292/2292 - 7s - 3ms/step - ia: 0.8797 - loss: 0.0624 - mae: 0.1838 - rmse: 0.2417 - smape: 0.4650 - val_ia: 0.3383 - val_loss: 0.2635 - val_mae: 0.3793 - val_rmse: 0.4202 - val_smape: 0.7531

Epoch 49/128

2292/2292 - 11s - 5ms/step - ia: 0.8805 - loss: 0.0616 - mae: 0.1823 - rmse: 0.2404 - smape: 0.4630 - val_ia: 0.3368 - val_loss: 0.2703 - val_mae: 0.3847 - val_rmse: 0.4259 - val_smape: 0.7552

Epoch 50/128

2292/2292 - 21s - 9ms/step - ia: 0.8805 - loss: 0.0613 - mae: 0.1819 - rmse: 0.2398 - smape: 0.4610 - val_ia: 0.3316 - val_loss: 0.2770 - val_mae: 0.3966 - val_rmse: 0.4375 - val_smape: 0.7922

Epoch 51/128

2292/2292 - 8s - 3ms/step - ia: 0.8810 - loss: 0.0606 - mae: 0.1808 - rmse: 0.2384 - smape: 0.4617 - val_ia: 0.3380 - val_loss: 0.2746 - val_mae: 0.3891 - val_rmse: 0.4304 - val_smape: 0.7796

Epoch 52/128

2292/2292 - 9s - 4ms/step - ia: 0.8819 - loss: 0.0604 - mae: 0.1807 - rmse: 0.2379 - smape: 0.4592 - val_ia: 0.3357 - val_loss: 0.2594 - val_mae: 0.3835 - val_rmse: 0.4244 - val_smape: 0.7718

Epoch 53/128

2292/2292 - 13s - 6ms/step - ia: 0.8823 - loss: 0.0598 - mae: 0.1795 - rmse: 0.2368 - smape: 0.4590 - val_ia: 0.3389 - val_loss: 0.2771 - val_mae: 0.3901 - val_rmse: 0.4316 - val_smape: 0.7676

Epoch 54/128

2292/2292 - 10s - 4ms/step - ia: 0.8828 - loss: 0.0594 - mae: 0.1791 - rmse: 0.2361 - smape: 0.4582 - val_ia: 0.3371 - val_loss: 0.2875 - val_mae: 0.3943 - val_rmse: 0.4366 - val_smape: 0.7666

Epoch 55/128

2292/2292 - 11s - 5ms/step - ia: 0.8831 - loss: 0.0589 - mae: 0.1785 - rmse: 0.2353 - smape: 0.4567 - val_ia: 0.3408 - val_loss: 0.2565 - val_mae: 0.3749 - val_rmse: 0.4153 - val_smape: 0.7462

Epoch 56/128

2292/2292 - 9s - 4ms/step - ia: 0.8835 - loss: 0.0587 - mae: 0.1782 - rmse: 0.2347 - smape: 0.4578 - val_ia: 0.3412 - val_loss: 0.2713 - val_mae: 0.3871 - val_rmse: 0.4283 - val_smape: 0.7688

Epoch 57/128

2292/2292 - 7s - 3ms/step - ia: 0.8838 - loss: 0.0581 - mae: 0.1771 - rmse: 0.2334 - smape: 0.4546 - val_ia: 0.3420 - val_loss: 0.2584 - val_mae: 0.3756 - val_rmse: 0.4173 - val_smape: 0.7464

Epoch 58/128

2292/2292 - 11s - 5ms/step - ia: 0.8839 - loss: 0.0578 - mae: 0.1767 - rmse: 0.2323 - smape: 0.4529 - val_ia: 0.3422 - val_loss: 0.2504 - val_mae: 0.3738 - val_rmse: 0.4152 - val_smape: 0.7617

Epoch 59/128

2292/2292 - 6s - 3ms/step - ia: 0.8846 - loss: 0.0574 - mae: 0.1761 - rmse: 0.2322 - smape: 0.4509 - val_ia: 0.3464 - val_loss: 0.2380 - val_mae: 0.3624 - val_rmse: 0.4039 - val_smape: 0.7263

Epoch 60/128

2292/2292 - 9s - 4ms/step - ia: 0.8849 - loss: 0.0571 - mae: 0.1753 - rmse: 0.2310 - smape: 0.4495 - val_ia: 0.3476 - val_loss: 0.2456 - val_mae: 0.3666 - val_rmse: 0.4078 - val_smape: 0.7333

Epoch 61/128

2292/2292 - 11s - 5ms/step - ia: 0.8854 - loss: 0.0568 - mae: 0.1750 - rmse: 0.2307 - smape: 0.4504 - val_ia: 0.3443 - val_loss: 0.2679 - val_mae: 0.3833 - val_rmse: 0.4248 - val_smape: 0.7593

Epoch 62/128

2292/2292 - 6s - 2ms/step - ia: 0.8861 - loss: 0.0563 - mae: 0.1744 - rmse: 0.2294 - smape: 0.4485 - val_ia: 0.3456 - val_loss: 0.2548 - val_mae: 0.3737 - val_rmse: 0.4154 - val_smape: 0.7466

Epoch 63/128

2292/2292 - 17s - 7ms/step - ia: 0.8860 - loss: 0.0560 - mae: 0.1739 - rmse: 0.2286 - smape: 0.4485 - val_ia: 0.3468 - val_loss: 0.2531 - val_mae: 0.3707 - val_rmse: 0.4123 - val_smape: 0.7344

Epoch 64/128

2292/2292 - 18s - 8ms/step - ia: 0.8869 - loss: 0.0555 - mae: 0.1729 - rmse: 0.2281 - smape: 0.4441 - val_ia: 0.3488 - val_loss: 0.2374 - val_mae: 0.3635 - val_rmse: 0.4052 - val_smape: 0.7356

Epoch 65/128

2292/2292 - 6s - 3ms/step - ia: 0.8873 - loss: 0.0551 - mae: 0.1724 - rmse: 0.2274 - smape: 0.4447 - val_ia: 0.3480 - val_loss: 0.2344 - val_mae: 0.3621 - val_rmse: 0.4034 - val_smape: 0.7244

Epoch 66/128

2292/2292 - 9s - 4ms/step - ia: 0.8871 - loss: 0.0550 - mae: 0.1721 - rmse: 0.2269 - smape: 0.4448 - val_ia: 0.3515 - val_loss: 0.2381 - val_mae: 0.3615 - val_rmse: 0.4030 - val_smape: 0.7096

Epoch 67/128

2292/2292 - 10s - 4ms/step - ia: 0.8875 - loss: 0.0547 - mae: 0.1719 - rmse: 0.2267 - smape: 0.4456 - val_ia: 0.3494 - val_loss: 0.2450 - val_mae: 0.3648 - val_rmse: 0.4063 - val_smape: 0.7191

Epoch 68/128

2292/2292 - 10s - 4ms/step - ia: 0.8876 - loss: 0.0545 - mae: 0.1717 - rmse: 0.2259 - smape: 0.4448 - val_ia: 0.3454 - val_loss: 0.2400 - val_mae: 0.3665 - val_rmse: 0.4086 - val_smape: 0.7342

Epoch 69/128

2292/2292 - 11s - 5ms/step - ia: 0.8886 - loss: 0.0539 - mae: 0.1704 - rmse: 0.2250 - smape: 0.4412 - val_ia: 0.3406 - val_loss: 0.2372 - val_mae: 0.3722 - val_rmse: 0.4139 - val_smape: 0.7635

Epoch 70/128

2292/2292 - 6s - 3ms/step - ia: 0.8883 - loss: 0.0540 - mae: 0.1707 - rmse: 0.2246 - smape: 0.4429 - val_ia: 0.3498 - val_loss: 0.2177 - val_mae: 0.3544 - val_rmse: 0.3958 - val_smape: 0.7166

Epoch 71/128

2292/2292 - 9s - 4ms/step - ia: 0.8892 - loss: 0.0535 - mae: 0.1700 - rmse: 0.2240 - smape: 0.4404 - val_ia: 0.3479 - val_loss: 0.2269 - val_mae: 0.3604 - val_rmse: 0.4015 - val_smape: 0.7315

Epoch 72/128

2292/2292 - 11s - 5ms/step - ia: 0.8890 - loss: 0.0531 - mae: 0.1691 - rmse: 0.2228 - smape: 0.4403 - val_ia: 0.3528 - val_loss: 0.2319 - val_mae: 0.3593 - val_rmse: 0.4012 - val_smape: 0.7263

Epoch 73/128

2292/2292 - 10s - 4ms/step - ia: 0.8892 - loss: 0.0531 - mae: 0.1692 - rmse: 0.2229 - smape: 0.4400 - val_ia: 0.3531 - val_loss: 0.2402 - val_mae: 0.3630 - val_rmse: 0.4041 - val_smape: 0.7170

Epoch 74/128

2292/2292 - 8s - 4ms/step - ia: 0.8900 - loss: 0.0526 - mae: 0.1682 - rmse: 0.2217 - smape: 0.4375 - val_ia: 0.3557 - val_loss: 0.2207 - val_mae: 0.3493 - val_rmse: 0.3901 - val_smape: 0.6919

Epoch 75/128

2292/2292 - 4s - 2ms/step - ia: 0.8897 - loss: 0.0526 - mae: 0.1683 - rmse: 0.2219 - smape: 0.4385 - val_ia: 0.3519 - val_loss: 0.2212 - val_mae: 0.3536 - val_rmse: 0.3951 - val_smape: 0.7136

Epoch 76/128

2292/2292 - 8s - 3ms/step - ia: 0.8904 - loss: 0.0523 - mae: 0.1677 - rmse: 0.2213 - smape: 0.4374 - val_ia: 0.3464 - val_loss: 0.2392 - val_mae: 0.3696 - val_rmse: 0.4114 - val_smape: 0.7453

Epoch 77/128

2292/2292 - 11s - 5ms/step - ia: 0.8905 - loss: 0.0521 - mae: 0.1675 - rmse: 0.2207 - smape: 0.4370 - val_ia: 0.3502 - val_loss: 0.2180 - val_mae: 0.3543 - val_rmse: 0.3960 - val_smape: 0.7159

Epoch 78/128

2292/2292 - 11s - 5ms/step - ia: 0.8908 - loss: 0.0519 - mae: 0.1669 - rmse: 0.2200 - smape: 0.4342 - val_ia: 0.3544 - val_loss: 0.2253 - val_mae: 0.3565 - val_rmse: 0.3977 - val_smape: 0.7137

Epoch 79/128

2292/2292 - 6s - 3ms/step - ia: 0.8909 - loss: 0.0517 - mae: 0.1665 - rmse: 0.2199 - smape: 0.4340 - val_ia: 0.3546 - val_loss: 0.2380 - val_mae: 0.3637 - val_rmse: 0.4057 - val_smape: 0.7286

Epoch 80/128

2292/2292 - 15s - 6ms/step - ia: 0.8920 - loss: 0.0513 - mae: 0.1660 - rmse: 0.2190 - smape: 0.4343 - val_ia: 0.3535 - val_loss: 0.2132 - val_mae: 0.3487 - val_rmse: 0.3911 - val_smape: 0.7045

Epoch 81/128

2292/2292 - 9s - 4ms/step - ia: 0.8914 - loss: 0.0513 - mae: 0.1660 - rmse: 0.2188 - smape: 0.4334 - val_ia: 0.3538 - val_loss: 0.2221 - val_mae: 0.3524 - val_rmse: 0.3946 - val_smape: 0.6997

Epoch 82/128

2292/2292 - 7s - 3ms/step - ia: 0.8914 - loss: 0.0512 - mae: 0.1659 - rmse: 0.2187 - smape: 0.4341 - val_ia: 0.3410 - val_loss: 0.2530 - val_mae: 0.3817 - val_rmse: 0.4239 - val_smape: 0.7575

Epoch 83/128

2292/2292 - 5s - 2ms/step - ia: 0.8917 - loss: 0.0508 - mae: 0.1656 - rmse: 0.2179 - smape: 0.4339 - val_ia: 0.3498 - val_loss: 0.2305 - val_mae: 0.3619 - val_rmse: 0.4042 - val_smape: 0.7261

Epoch 84/128

2292/2292 - 11s - 5ms/step - ia: 0.8922 - loss: 0.0506 - mae: 0.1648 - rmse: 0.2176 - smape: 0.4326 - val_ia: 0.3495 - val_loss: 0.2428 - val_mae: 0.3696 - val_rmse: 0.4114 - val_smape: 0.7351

Epoch 85/128

2292/2292 - 7s - 3ms/step - ia: 0.8921 - loss: 0.0506 - mae: 0.1648 - rmse: 0.2175 - smape: 0.4318 - val_ia: 0.3519 - val_loss: 0.2146 - val_mae: 0.3495 - val_rmse: 0.3921 - val_smape: 0.6967

Epoch 86/128

2292/2292 - 6s - 3ms/step - ia: 0.8924 - loss: 0.0501 - mae: 0.1646 - rmse: 0.2168 - smape: 0.4319 - val_ia: 0.3560 - val_loss: 0.2320 - val_mae: 0.3612 - val_rmse: 0.4026 - val_smape: 0.7143

Epoch 87/128

2292/2292 - 7s - 3ms/step - ia: 0.8928 - loss: 0.0500 - mae: 0.1637 - rmse: 0.2161 - smape: 0.4284 - val_ia: 0.3489 - val_loss: 0.2365 - val_mae: 0.3688 - val_rmse: 0.4107 - val_smape: 0.7315

Epoch 88/128

2292/2292 - 12s - 5ms/step - ia: 0.8930 - loss: 0.0499 - mae: 0.1635 - rmse: 0.2160 - smape: 0.4297 - val_ia: 0.3527 - val_loss: 0.2044 - val_mae: 0.3449 - val_rmse: 0.3877 - val_smape: 0.6919

Epoch 89/128

2292/2292 - 11s - 5ms/step - ia: 0.8927 - loss: 0.0499 - mae: 0.1637 - rmse: 0.2160 - smape: 0.4301 - val_ia: 0.3548 - val_loss: 0.2328 - val_mae: 0.3596 - val_rmse: 0.4018 - val_smape: 0.7076

Epoch 90/128

2292/2292 - 19s - 8ms/step - ia: 0.8937 - loss: 0.0495 - mae: 0.1631 - rmse: 0.2152 - smape: 0.4291 - val_ia: 0.3525 - val_loss: 0.2098 - val_mae: 0.3501 - val_rmse: 0.3924 - val_smape: 0.7032

Epoch 91/128

2292/2292 - 11s - 5ms/step - ia: 0.8936 - loss: 0.0495 - mae: 0.1629 - rmse: 0.2148 - smape: 0.4279 - val_ia: 0.3576 - val_loss: 0.2269 - val_mae: 0.3563 - val_rmse: 0.3981 - val_smape: 0.6953

Epoch 92/128

2292/2292 - 9s - 4ms/step - ia: 0.8939 - loss: 0.0491 - mae: 0.1624 - rmse: 0.2142 - smape: 0.4282 - val_ia: 0.3485 - val_loss: 0.2321 - val_mae: 0.3651 - val_rmse: 0.4078 - val_smape: 0.7327

Epoch 93/128

2292/2292 - 6s - 3ms/step - ia: 0.8940 - loss: 0.0491 - mae: 0.1623 - rmse: 0.2144 - smape: 0.4269 - val_ia: 0.3522 - val_loss: 0.2394 - val_mae: 0.3644 - val_rmse: 0.4079 - val_smape: 0.7179

Epoch 94/128

2292/2292 - 12s - 5ms/step - ia: 0.8940 - loss: 0.0489 - mae: 0.1619 - rmse: 0.2138 - smape: 0.4259 - val_ia: 0.3583 - val_loss: 0.2340 - val_mae: 0.3575 - val_rmse: 0.4001 - val_smape: 0.6977

Epoch 95/128

2292/2292 - 10s - 5ms/step - ia: 0.8940 - loss: 0.0491 - mae: 0.1622 - rmse: 0.2142 - smape: 0.4260 - val_ia: 0.3494 - val_loss: 0.2314 - val_mae: 0.3625 - val_rmse: 0.4056 - val_smape: 0.7251

Epoch 96/128

2292/2292 - 7s - 3ms/step - ia: 0.8943 - loss: 0.0489 - mae: 0.1619 - rmse: 0.2135 - smape: 0.4268 - val_ia: 0.3550 - val_loss: 0.2281 - val_mae: 0.3570 - val_rmse: 0.3999 - val_smape: 0.7028

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 12s - 5ms/step - ia: 0.7384 - loss: 0.2503 - mae: 0.3839 - rmse: 0.4829 - smape: 0.7525 - val_ia: 0.2928 - val_loss: 0.4138 - val_mae: 0.4810 - val_rmse: 0.5346 - val_smape: 0.9702

Epoch 2/128

2292/2292 - 6s - 3ms/step - ia: 0.8181 - loss: 0.1314 - mae: 0.2740 - rmse: 0.3519 - smape: 0.6102 - val_ia: 0.3393 - val_loss: 0.3253 - val_mae: 0.4067 - val_rmse: 0.4481 - val_smape: 0.8224

Epoch 3/128

2292/2292 - 5s - 2ms/step - ia: 0.8422 - loss: 0.1014 - mae: 0.2396 - rmse: 0.3097 - smape: 0.5581 - val_ia: 0.3272 - val_loss: 0.3487 - val_mae: 0.4339 - val_rmse: 0.4751 - val_smape: 0.8579

Epoch 4/128

2292/2292 - 9s - 4ms/step - ia: 0.8531 - loss: 0.0887 - mae: 0.2229 - rmse: 0.2887 - smape: 0.5305 - val_ia: 0.3320 - val_loss: 0.3113 - val_mae: 0.3945 - val_rmse: 0.4378 - val_smape: 0.7841

Epoch 5/128

2292/2292 - 10s - 4ms/step - ia: 0.8605 - loss: 0.0808 - mae: 0.2125 - rmse: 0.2758 - smape: 0.5106 - val_ia: 0.3221 - val_loss: 0.2897 - val_mae: 0.4063 - val_rmse: 0.4465 - val_smape: 0.8104

Epoch 6/128

2292/2292 - 12s - 5ms/step - ia: 0.8654 - loss: 0.0761 - mae: 0.2059 - rmse: 0.2671 - smape: 0.4985 - val_ia: 0.3257 - val_loss: 0.2470 - val_mae: 0.3919 - val_rmse: 0.4302 - val_smape: 0.8238

Epoch 7/128

2292/2292 - 10s - 4ms/step - ia: 0.8686 - loss: 0.0727 - mae: 0.2012 - rmse: 0.2610 - smape: 0.4950 - val_ia: 0.3633 - val_loss: 0.1810 - val_mae: 0.3237 - val_rmse: 0.3635 - val_smape: 0.6632

Epoch 8/128

2292/2292 - 8s - 4ms/step - ia: 0.8723 - loss: 0.0689 - mae: 0.1958 - rmse: 0.2542 - smape: 0.4847 - val_ia: 0.3732 - val_loss: 0.2036 - val_mae: 0.3370 - val_rmse: 0.3759 - val_smape: 0.6782

Epoch 9/128

2292/2292 - 9s - 4ms/step - ia: 0.8737 - loss: 0.0674 - mae: 0.1930 - rmse: 0.2513 - smape: 0.4786 - val_ia: 0.3617 - val_loss: 0.2377 - val_mae: 0.3587 - val_rmse: 0.3970 - val_smape: 0.7083

Epoch 10/128

2292/2292 - 6s - 2ms/step - ia: 0.8762 - loss: 0.0649 - mae: 0.1899 - rmse: 0.2469 - smape: 0.4739 - val_ia: 0.3664 - val_loss: 0.1994 - val_mae: 0.3390 - val_rmse: 0.3772 - val_smape: 0.7080

Epoch 11/128

2292/2292 - 9s - 4ms/step - ia: 0.8785 - loss: 0.0626 - mae: 0.1859 - rmse: 0.2420 - smape: 0.4699 - val_ia: 0.3685 - val_loss: 0.1789 - val_mae: 0.3224 - val_rmse: 0.3627 - val_smape: 0.6480

Epoch 12/128

2292/2292 - 10s - 4ms/step - ia: 0.8796 - loss: 0.0611 - mae: 0.1842 - rmse: 0.2393 - smape: 0.4647 - val_ia: 0.3388 - val_loss: 0.2198 - val_mae: 0.3663 - val_rmse: 0.4038 - val_smape: 0.7593

Epoch 13/128

2292/2292 - 9s - 4ms/step - ia: 0.8795 - loss: 0.0613 - mae: 0.1848 - rmse: 0.2399 - smape: 0.4671 - val_ia: 0.3571 - val_loss: 0.1800 - val_mae: 0.3295 - val_rmse: 0.3688 - val_smape: 0.7043

Epoch 14/128

2292/2292 - 7s - 3ms/step - ia: 0.8802 - loss: 0.0601 - mae: 0.1834 - rmse: 0.2376 - smape: 0.4667 - val_ia: 0.3521 - val_loss: 0.1757 - val_mae: 0.3272 - val_rmse: 0.3658 - val_smape: 0.6953

Epoch 15/128

2292/2292 - 5s - 2ms/step - ia: 0.8825 - loss: 0.0585 - mae: 0.1799 - rmse: 0.2340 - smape: 0.4575 - val_ia: 0.3348 - val_loss: 0.1994 - val_mae: 0.3482 - val_rmse: 0.3927 - val_smape: 0.7153

Epoch 16/128

2292/2292 - 9s - 4ms/step - ia: 0.8840 - loss: 0.0574 - mae: 0.1783 - rmse: 0.2318 - smape: 0.4562 - val_ia: 0.3519 - val_loss: 0.1999 - val_mae: 0.3426 - val_rmse: 0.3851 - val_smape: 0.7242

Epoch 17/128

2292/2292 - 8s - 3ms/step - ia: 0.8831 - loss: 0.0579 - mae: 0.1795 - rmse: 0.2333 - smape: 0.4579 - val_ia: 0.3388 - val_loss: 0.2114 - val_mae: 0.3617 - val_rmse: 0.4027 - val_smape: 0.7595

Epoch 18/128

2292/2292 - 11s - 5ms/step - ia: 0.8838 - loss: 0.0573 - mae: 0.1783 - rmse: 0.2315 - smape: 0.4544 - val_ia: 0.3474 - val_loss: 0.1732 - val_mae: 0.3212 - val_rmse: 0.3631 - val_smape: 0.6596

Epoch 19/128

2292/2292 - 6s - 2ms/step - ia: 0.8841 - loss: 0.0570 - mae: 0.1774 - rmse: 0.2309 - smape: 0.4531 - val_ia: 0.3572 - val_loss: 0.2022 - val_mae: 0.3442 - val_rmse: 0.3834 - val_smape: 0.7417

Epoch 20/128

2292/2292 - 11s - 5ms/step - ia: 0.8858 - loss: 0.0556 - mae: 0.1759 - rmse: 0.2283 - smape: 0.4509 - val_ia: 0.3556 - val_loss: 0.2003 - val_mae: 0.3477 - val_rmse: 0.3881 - val_smape: 0.7194

Epoch 21/128

2292/2292 - 9s - 4ms/step - ia: 0.8852 - loss: 0.0560 - mae: 0.1766 - rmse: 0.2290 - smape: 0.4506 - val_ia: 0.3452 - val_loss: 0.2120 - val_mae: 0.3518 - val_rmse: 0.3957 - val_smape: 0.7276

Epoch 22/128

2292/2292 - 9s - 4ms/step - ia: 0.8859 - loss: 0.0553 - mae: 0.1756 - rmse: 0.2277 - smape: 0.4508 - val_ia: 0.3632 - val_loss: 0.1870 - val_mae: 0.3252 - val_rmse: 0.3659 - val_smape: 0.6783

Epoch 23/128

2292/2292 - 9s - 4ms/step - ia: 0.8856 - loss: 0.0550 - mae: 0.1750 - rmse: 0.2272 - smape: 0.4486 - val_ia: 0.3727 - val_loss: 0.1725 - val_mae: 0.3144 - val_rmse: 0.3528 - val_smape: 0.6633

Epoch 24/128

2292/2292 - 5s - 2ms/step - ia: 0.8873 - loss: 0.0541 - mae: 0.1730 - rmse: 0.2252 - smape: 0.4438 - val_ia: 0.3487 - val_loss: 0.2192 - val_mae: 0.3544 - val_rmse: 0.3959 - val_smape: 0.7395

Epoch 25/128

2292/2292 - 5s - 2ms/step - ia: 0.8878 - loss: 0.0533 - mae: 0.1723 - rmse: 0.2235 - smape: 0.4432 - val_ia: 0.3565 - val_loss: 0.2015 - val_mae: 0.3382 - val_rmse: 0.3811 - val_smape: 0.7226

Epoch 26/128

2292/2292 - 8s - 3ms/step - ia: 0.8872 - loss: 0.0539 - mae: 0.1732 - rmse: 0.2247 - smape: 0.4451 - val_ia: 0.3371 - val_loss: 0.2454 - val_mae: 0.3742 - val_rmse: 0.4179 - val_smape: 0.7634

Epoch 27/128

2292/2292 - 7s - 3ms/step - ia: 0.8878 - loss: 0.0535 - mae: 0.1723 - rmse: 0.2237 - smape: 0.4438 - val_ia: 0.3522 - val_loss: 0.1897 - val_mae: 0.3337 - val_rmse: 0.3755 - val_smape: 0.7167

Epoch 28/128

2292/2292 - 8s - 3ms/step - ia: 0.8877 - loss: 0.0537 - mae: 0.1726 - rmse: 0.2244 - smape: 0.4433 - val_ia: 0.3539 - val_loss: 0.2092 - val_mae: 0.3416 - val_rmse: 0.3851 - val_smape: 0.7218

Epoch 29/128

2292/2292 - 9s - 4ms/step - ia: 0.8880 - loss: 0.0528 - mae: 0.1717 - rmse: 0.2226 - smape: 0.4424 - val_ia: 0.3421 - val_loss: 0.2348 - val_mae: 0.3742 - val_rmse: 0.4176 - val_smape: 0.7588

Epoch 30/128

2292/2292 - 5s - 2ms/step - ia: 0.8891 - loss: 0.0526 - mae: 0.1705 - rmse: 0.2219 - smape: 0.4403 - val_ia: 0.3506 - val_loss: 0.2093 - val_mae: 0.3444 - val_rmse: 0.3894 - val_smape: 0.7318

Epoch 31/128

2292/2292 - 6s - 3ms/step - ia: 0.8884 - loss: 0.0527 - mae: 0.1712 - rmse: 0.2219 - smape: 0.4417 - val_ia: 0.3507 - val_loss: 0.1928 - val_mae: 0.3346 - val_rmse: 0.3757 - val_smape: 0.7242

Epoch 32/128

2292/2292 - 6s - 3ms/step - ia: 0.8900 - loss: 0.0517 - mae: 0.1692 - rmse: 0.2200 - smape: 0.4387 - val_ia: 0.3573 - val_loss: 0.2031 - val_mae: 0.3355 - val_rmse: 0.3792 - val_smape: 0.6974

Epoch 33/128

2292/2292 - 13s - 6ms/step - ia: 0.8888 - loss: 0.0527 - mae: 0.1712 - rmse: 0.2221 - smape: 0.4407 - val_ia: 0.3527 - val_loss: 0.2179 - val_mae: 0.3474 - val_rmse: 0.3906 - val_smape: 0.7266

Epoch 34/128

2292/2292 - 10s - 4ms/step - ia: 0.8896 - loss: 0.0515 - mae: 0.1698 - rmse: 0.2196 - smape: 0.4395 - val_ia: 0.3550 - val_loss: 0.2202 - val_mae: 0.3489 - val_rmse: 0.3947 - val_smape: 0.7382

Epoch 35/128

2292/2292 - 7s - 3ms/step - ia: 0.8897 - loss: 0.0514 - mae: 0.1691 - rmse: 0.2197 - smape: 0.4362 - val_ia: 0.3361 - val_loss: 0.2584 - val_mae: 0.3755 - val_rmse: 0.4206 - val_smape: 0.7766

Epoch 36/128

2292/2292 - 5s - 2ms/step - ia: 0.8899 - loss: 0.0516 - mae: 0.1689 - rmse: 0.2199 - smape: 0.4375 - val_ia: 0.3646 - val_loss: 0.1880 - val_mae: 0.3280 - val_rmse: 0.3717 - val_smape: 0.6939

Epoch 37/128

2292/2292 - 8s - 3ms/step - ia: 0.8907 - loss: 0.0511 - mae: 0.1683 - rmse: 0.2188 - smape: 0.4365 - val_ia: 0.3447 - val_loss: 0.2080 - val_mae: 0.3514 - val_rmse: 0.3950 - val_smape: 0.7400

Epoch 38/128

2292/2292 - 7s - 3ms/step - ia: 0.8909 - loss: 0.0509 - mae: 0.1678 - rmse: 0.2181 - smape: 0.4346 - val_ia: 0.3392 - val_loss: 0.2392 - val_mae: 0.3655 - val_rmse: 0.4107 - val_smape: 0.7511

Epoch 38: early stopping

Restoring model weights from the end of the best epoch: 23.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 43s 266ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 50%|█████     | 25/50 [1:53:23<3:23:52, 489.32s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 16s - 7ms/step - ia: 0.3070 - loss: 0.9632 - mae: 0.8105 - rmse: 0.9645 - smape: 1.4325 - val_ia: 0.1917 - val_loss: 0.7758 - val_mae: 0.7276 - val_rmse: 0.7606 - val_smape: 1.3526

Epoch 2/128

2292/2292 - 7s - 3ms/step - ia: 0.4778 - loss: 0.6385 - mae: 0.6524 - rmse: 0.7886 - smape: 1.1547 - val_ia: 0.1797 - val_loss: 1.0787 - val_mae: 0.8771 - val_rmse: 0.9111 - val_smape: 1.3379

Epoch 3/128

2292/2292 - 10s - 4ms/step - ia: 0.5607 - loss: 0.5584 - mae: 0.5982 - rmse: 0.7363 - smape: 1.0260 - val_ia: 0.1735 - val_loss: 1.3176 - val_mae: 0.9775 - val_rmse: 1.0155 - val_smape: 1.3630

Epoch 4/128

2292/2292 - 9s - 4ms/step - ia: 0.5770 - loss: 0.5422 - mae: 0.5877 - rmse: 0.7253 - smape: 0.9998 - val_ia: 0.1713 - val_loss: 1.3420 - val_mae: 0.9852 - val_rmse: 1.0251 - val_smape: 1.3584

Epoch 5/128

2292/2292 - 9s - 4ms/step - ia: 0.5832 - loss: 0.5330 - mae: 0.5818 - rmse: 0.7194 - smape: 0.9901 - val_ia: 0.1703 - val_loss: 1.3614 - val_mae: 0.9899 - val_rmse: 1.0306 - val_smape: 1.3563

Epoch 6/128

2292/2292 - 11s - 5ms/step - ia: 0.5848 - loss: 0.5262 - mae: 0.5778 - rmse: 0.7148 - smape: 0.9862 - val_ia: 0.1683 - val_loss: 1.4260 - val_mae: 1.0127 - val_rmse: 1.0542 - val_smape: 1.3617

Epoch 7/128

2292/2292 - 11s - 5ms/step - ia: 0.5914 - loss: 0.5161 - mae: 0.5715 - rmse: 0.7073 - smape: 0.9734 - val_ia: 0.1699 - val_loss: 1.3655 - val_mae: 0.9876 - val_rmse: 1.0293 - val_smape: 1.3490

Epoch 8/128

2292/2292 - 10s - 4ms/step - ia: 0.5934 - loss: 0.5068 - mae: 0.5669 - rmse: 0.7017 - smape: 0.9728 - val_ia: 0.1686 - val_loss: 1.4003 - val_mae: 1.0006 - val_rmse: 1.0424 - val_smape: 1.3553

Epoch 9/128

2292/2292 - 9s - 4ms/step - ia: 0.5984 - loss: 0.4966 - mae: 0.5604 - rmse: 0.6938 - smape: 0.9609 - val_ia: 0.1683 - val_loss: 1.4083 - val_mae: 1.0032 - val_rmse: 1.0449 - val_smape: 1.3582

Epoch 10/128

2292/2292 - 8s - 4ms/step - ia: 0.6004 - loss: 0.4903 - mae: 0.5573 - rmse: 0.6894 - smape: 0.9596 - val_ia: 0.1661 - val_loss: 1.4633 - val_mae: 1.0257 - val_rmse: 1.0675 - val_smape: 1.3713

Epoch 11/128

2292/2292 - 9s - 4ms/step - ia: 0.6034 - loss: 0.4841 - mae: 0.5538 - rmse: 0.6849 - smape: 0.9569 - val_ia: 0.1671 - val_loss: 1.4783 - val_mae: 1.0270 - val_rmse: 1.0694 - val_smape: 1.3663

Epoch 12/128

2292/2292 - 10s - 4ms/step - ia: 0.6065 - loss: 0.4742 - mae: 0.5487 - rmse: 0.6777 - smape: 0.9494 - val_ia: 0.1686 - val_loss: 1.4311 - val_mae: 1.0082 - val_rmse: 1.0504 - val_smape: 1.3605

Epoch 13/128

2292/2292 - 6s - 3ms/step - ia: 0.6112 - loss: 0.4635 - mae: 0.5424 - rmse: 0.6710 - smape: 0.9422 - val_ia: 0.1695 - val_loss: 1.3926 - val_mae: 0.9942 - val_rmse: 1.0362 - val_smape: 1.3590

Epoch 14/128

2292/2292 - 6s - 3ms/step - ia: 0.6161 - loss: 0.4566 - mae: 0.5374 - rmse: 0.6657 - smape: 0.9370 - val_ia: 0.1702 - val_loss: 1.3978 - val_mae: 0.9929 - val_rmse: 1.0354 - val_smape: 1.3550

Epoch 15/128

2292/2292 - 9s - 4ms/step - ia: 0.6188 - loss: 0.4483 - mae: 0.5328 - rmse: 0.6597 - smape: 0.9295 - val_ia: 0.1700 - val_loss: 1.4224 - val_mae: 1.0013 - val_rmse: 1.0438 - val_smape: 1.3610

Epoch 16/128

2292/2292 - 10s - 4ms/step - ia: 0.6238 - loss: 0.4386 - mae: 0.5268 - rmse: 0.6519 - smape: 0.9246 - val_ia: 0.1721 - val_loss: 1.4010 - val_mae: 0.9885 - val_rmse: 1.0316 - val_smape: 1.3502

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 28s 178ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 52%|█████▏    | 26/50 [1:55:57<2:35:29, 388.74s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 14s - 6ms/step - ia: 0.6285 - loss: 0.4139 - mae: 0.5118 - rmse: 0.6306 - smape: 0.9127 - val_ia: 0.1763 - val_loss: 1.1621 - val_mae: 0.8878 - val_rmse: 0.9342 - val_smape: 1.3013

Epoch 2/128

2292/2292 - 9s - 4ms/step - ia: 0.7177 - loss: 0.2692 - mae: 0.4077 - rmse: 0.5092 - smape: 0.7913 - val_ia: 0.2117 - val_loss: 0.8764 - val_mae: 0.7323 - val_rmse: 0.7761 - val_smape: 1.1760

Epoch 3/128

2292/2292 - 11s - 5ms/step - ia: 0.7530 - loss: 0.2186 - mae: 0.3635 - rmse: 0.4584 - smape: 0.7320 - val_ia: 0.2477 - val_loss: 0.6339 - val_mae: 0.6075 - val_rmse: 0.6538 - val_smape: 1.0839

Epoch 4/128

2292/2292 - 8s - 4ms/step - ia: 0.7717 - loss: 0.1922 - mae: 0.3392 - rmse: 0.4295 - smape: 0.6999 - val_ia: 0.2625 - val_loss: 0.5618 - val_mae: 0.5651 - val_rmse: 0.6097 - val_smape: 1.0297

Epoch 5/128

2292/2292 - 10s - 4ms/step - ia: 0.7849 - loss: 0.1735 - mae: 0.3202 - rmse: 0.4075 - smape: 0.6738 - val_ia: 0.2716 - val_loss: 0.5227 - val_mae: 0.5377 - val_rmse: 0.5834 - val_smape: 1.0093

Epoch 6/128

2292/2292 - 10s - 4ms/step - ia: 0.7951 - loss: 0.1595 - mae: 0.3056 - rmse: 0.3908 - smape: 0.6591 - val_ia: 0.2799 - val_loss: 0.4867 - val_mae: 0.5199 - val_rmse: 0.5652 - val_smape: 1.0000

Epoch 7/128

2292/2292 - 6s - 3ms/step - ia: 0.8048 - loss: 0.1474 - mae: 0.2918 - rmse: 0.3749 - smape: 0.6410 - val_ia: 0.2816 - val_loss: 0.4884 - val_mae: 0.5114 - val_rmse: 0.5579 - val_smape: 0.9559

Epoch 8/128

2292/2292 - 13s - 6ms/step - ia: 0.8130 - loss: 0.1366 - mae: 0.2796 - rmse: 0.3605 - smape: 0.6227 - val_ia: 0.2988 - val_loss: 0.4180 - val_mae: 0.4707 - val_rmse: 0.5169 - val_smape: 0.9107

Epoch 9/128

2292/2292 - 8s - 4ms/step - ia: 0.8215 - loss: 0.1269 - mae: 0.2680 - rmse: 0.3471 - smape: 0.6049 - val_ia: 0.3148 - val_loss: 0.3834 - val_mae: 0.4445 - val_rmse: 0.4918 - val_smape: 0.8641

Epoch 10/128

2292/2292 - 6s - 3ms/step - ia: 0.8287 - loss: 0.1173 - mae: 0.2573 - rmse: 0.3336 - smape: 0.5882 - val_ia: 0.3268 - val_loss: 0.3569 - val_mae: 0.4230 - val_rmse: 0.4708 - val_smape: 0.8115

Epoch 11/128

2292/2292 - 10s - 4ms/step - ia: 0.8352 - loss: 0.1099 - mae: 0.2475 - rmse: 0.3227 - smape: 0.5738 - val_ia: 0.3376 - val_loss: 0.3109 - val_mae: 0.3960 - val_rmse: 0.4417 - val_smape: 0.7670

Epoch 12/128

2292/2292 - 8s - 3ms/step - ia: 0.8406 - loss: 0.1033 - mae: 0.2398 - rmse: 0.3125 - smape: 0.5614 - val_ia: 0.3279 - val_loss: 0.3693 - val_mae: 0.4294 - val_rmse: 0.4742 - val_smape: 0.8224

Epoch 13/128

2292/2292 - 10s - 4ms/step - ia: 0.8461 - loss: 0.0976 - mae: 0.2322 - rmse: 0.3038 - smape: 0.5493 - val_ia: 0.3250 - val_loss: 0.3878 - val_mae: 0.4471 - val_rmse: 0.4911 - val_smape: 0.8481

Epoch 14/128

2292/2292 - 10s - 5ms/step - ia: 0.8505 - loss: 0.0930 - mae: 0.2262 - rmse: 0.2961 - smape: 0.5400 - val_ia: 0.3347 - val_loss: 0.3313 - val_mae: 0.4071 - val_rmse: 0.4506 - val_smape: 0.7777

Epoch 15/128

2292/2292 - 9s - 4ms/step - ia: 0.8535 - loss: 0.0892 - mae: 0.2214 - rmse: 0.2898 - smape: 0.5306 - val_ia: 0.3304 - val_loss: 0.3273 - val_mae: 0.4135 - val_rmse: 0.4565 - val_smape: 0.8098

Epoch 16/128

2292/2292 - 10s - 4ms/step - ia: 0.8571 - loss: 0.0851 - mae: 0.2161 - rmse: 0.2831 - smape: 0.5234 - val_ia: 0.3252 - val_loss: 0.3493 - val_mae: 0.4332 - val_rmse: 0.4764 - val_smape: 0.8404

Epoch 17/128

2292/2292 - 9s - 4ms/step - ia: 0.8599 - loss: 0.0822 - mae: 0.2123 - rmse: 0.2784 - smape: 0.5161 - val_ia: 0.3335 - val_loss: 0.3157 - val_mae: 0.4014 - val_rmse: 0.4436 - val_smape: 0.7837

Epoch 18/128

2292/2292 - 6s - 3ms/step - ia: 0.8628 - loss: 0.0793 - mae: 0.2082 - rmse: 0.2732 - smape: 0.5091 - val_ia: 0.3317 - val_loss: 0.3143 - val_mae: 0.4044 - val_rmse: 0.4462 - val_smape: 0.7788

Epoch 19/128

2292/2292 - 9s - 4ms/step - ia: 0.8649 - loss: 0.0769 - mae: 0.2049 - rmse: 0.2687 - smape: 0.5035 - val_ia: 0.3346 - val_loss: 0.3538 - val_mae: 0.4193 - val_rmse: 0.4617 - val_smape: 0.7964

Epoch 20/128

2292/2292 - 6s - 3ms/step - ia: 0.8674 - loss: 0.0747 - mae: 0.2016 - rmse: 0.2648 - smape: 0.4974 - val_ia: 0.3256 - val_loss: 0.3242 - val_mae: 0.4182 - val_rmse: 0.4599 - val_smape: 0.8313

Epoch 21/128

2292/2292 - 6s - 3ms/step - ia: 0.8685 - loss: 0.0730 - mae: 0.1993 - rmse: 0.2618 - smape: 0.4940 - val_ia: 0.3279 - val_loss: 0.3664 - val_mae: 0.4357 - val_rmse: 0.4780 - val_smape: 0.8181

Epoch 22/128

2292/2292 - 11s - 5ms/step - ia: 0.8707 - loss: 0.0707 - mae: 0.1960 - rmse: 0.2576 - smape: 0.4878 - val_ia: 0.3316 - val_loss: 0.3594 - val_mae: 0.4280 - val_rmse: 0.4692 - val_smape: 0.7973

Epoch 23/128

2292/2292 - 25s - 11ms/step - ia: 0.8721 - loss: 0.0692 - mae: 0.1941 - rmse: 0.2546 - smape: 0.4856 - val_ia: 0.3322 - val_loss: 0.3241 - val_mae: 0.4137 - val_rmse: 0.4548 - val_smape: 0.8069

Epoch 24/128

2292/2292 - 17s - 7ms/step - ia: 0.8734 - loss: 0.0682 - mae: 0.1927 - rmse: 0.2533 - smape: 0.4821 - val_ia: 0.3354 - val_loss: 0.3279 - val_mae: 0.4098 - val_rmse: 0.4523 - val_smape: 0.7866

Epoch 25/128

2292/2292 - 9s - 4ms/step - ia: 0.8744 - loss: 0.0670 - mae: 0.1909 - rmse: 0.2507 - smape: 0.4796 - val_ia: 0.3250 - val_loss: 0.3172 - val_mae: 0.4125 - val_rmse: 0.4537 - val_smape: 0.8052

Epoch 26/128

2292/2292 - 11s - 5ms/step - ia: 0.8753 - loss: 0.0657 - mae: 0.1891 - rmse: 0.2484 - smape: 0.4774 - val_ia: 0.3304 - val_loss: 0.3573 - val_mae: 0.4316 - val_rmse: 0.4728 - val_smape: 0.8071

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:00 746ms/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
113/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 54%|█████▍    | 27/50 [2:00:25<2:15:10, 352.65s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

2292/2292 - 17s - 7ms/step - ia: 0.4587 - loss: 1.2367 - mae: 0.8643 - rmse: 1.0635 - smape: 1.2134 - val_ia: 0.1820 - val_loss: 1.0304 - val_mae: 0.8464 - val_rmse: 0.8855 - val_smape: 1.2938

Epoch 2/64

2292/2292 - 12s - 5ms/step - ia: 0.5473 - loss: 0.6466 - mae: 0.6415 - rmse: 0.7920 - smape: 1.0589 - val_ia: 0.1728 - val_loss: 1.2176 - val_mae: 0.9289 - val_rmse: 0.9688 - val_smape: 1.3331

Epoch 3/64

2292/2292 - 20s - 9ms/step - ia: 0.5646 - loss: 0.5827 - mae: 0.6088 - rmse: 0.7521 - smape: 1.0230 - val_ia: 0.1711 - val_loss: 1.2389 - val_mae: 0.9367 - val_rmse: 0.9756 - val_smape: 1.3391

Epoch 4/64

2292/2292 - 11s - 5ms/step - ia: 0.5733 - loss: 0.5504 - mae: 0.5908 - rmse: 0.7303 - smape: 1.0021 - val_ia: 0.1723 - val_loss: 1.1977 - val_mae: 0.9183 - val_rmse: 0.9570 - val_smape: 1.3312

Epoch 5/64

2292/2292 - 11s - 5ms/step - ia: 0.5821 - loss: 0.5278 - mae: 0.5776 - rmse: 0.7155 - smape: 0.9824 - val_ia: 0.1728 - val_loss: 1.1844 - val_mae: 0.9099 - val_rmse: 0.9488 - val_smape: 1.3259

Epoch 6/64

2292/2292 - 10s - 5ms/step - ia: 0.5882 - loss: 0.5116 - mae: 0.5676 - rmse: 0.7044 - smape: 0.9678 - val_ia: 0.1722 - val_loss: 1.1836 - val_mae: 0.9077 - val_rmse: 0.9469 - val_smape: 1.3250

Epoch 7/64

2292/2292 - 11s - 5ms/step - ia: 0.5960 - loss: 0.4963 - mae: 0.5583 - rmse: 0.6929 - smape: 0.9530 - val_ia: 0.1728 - val_loss: 1.1715 - val_mae: 0.9013 - val_rmse: 0.9409 - val_smape: 1.3257

Epoch 8/64

2292/2292 - 10s - 5ms/step - ia: 0.5999 - loss: 0.4856 - mae: 0.5527 - rmse: 0.6859 - smape: 0.9459 - val_ia: 0.1742 - val_loss: 1.1736 - val_mae: 0.8967 - val_rmse: 0.9377 - val_smape: 1.3180

Epoch 9/64

2292/2292 - 11s - 5ms/step - ia: 0.6055 - loss: 0.4751 - mae: 0.5459 - rmse: 0.6785 - smape: 0.9356 - val_ia: 0.1755 - val_loss: 1.1626 - val_mae: 0.8875 - val_rmse: 0.9295 - val_smape: 1.3097

Epoch 10/64

2292/2292 - 21s - 9ms/step - ia: 0.6120 - loss: 0.4640 - mae: 0.5385 - rmse: 0.6701 - smape: 0.9251 - val_ia: 0.1758 - val_loss: 1.1447 - val_mae: 0.8774 - val_rmse: 0.9197 - val_smape: 1.3097

Epoch 11/64

2292/2292 - 10s - 4ms/step - ia: 0.6158 - loss: 0.4552 - mae: 0.5340 - rmse: 0.6636 - smape: 0.9202 - val_ia: 0.1770 - val_loss: 1.1436 - val_mae: 0.8718 - val_rmse: 0.9146 - val_smape: 1.3015

Epoch 12/64

2292/2292 - 10s - 4ms/step - ia: 0.6190 - loss: 0.4500 - mae: 0.5311 - rmse: 0.6604 - smape: 0.9184 - val_ia: 0.1764 - val_loss: 1.1530 - val_mae: 0.8747 - val_rmse: 0.9177 - val_smape: 1.3057

Epoch 13/64

2292/2292 - 10s - 4ms/step - ia: 0.6211 - loss: 0.4436 - mae: 0.5271 - rmse: 0.6556 - smape: 0.9121 - val_ia: 0.1770 - val_loss: 1.1461 - val_mae: 0.8700 - val_rmse: 0.9133 - val_smape: 1.3029

Epoch 14/64

2292/2292 - 12s - 5ms/step - ia: 0.6228 - loss: 0.4410 - mae: 0.5251 - rmse: 0.6538 - smape: 0.9096 - val_ia: 0.1786 - val_loss: 1.1226 - val_mae: 0.8573 - val_rmse: 0.9009 - val_smape: 1.2948

Epoch 15/64

2292/2292 - 22s - 9ms/step - ia: 0.6280 - loss: 0.4338 - mae: 0.5202 - rmse: 0.6478 - smape: 0.9014 - val_ia: 0.1785 - val_loss: 1.1270 - val_mae: 0.8607 - val_rmse: 0.9041 - val_smape: 1.3003

Epoch 16/64

2292/2292 - 18s - 8ms/step - ia: 0.6277 - loss: 0.4311 - mae: 0.5200 - rmse: 0.6459 - smape: 0.9009 - val_ia: 0.1786 - val_loss: 1.1209 - val_mae: 0.8578 - val_rmse: 0.9015 - val_smape: 1.2995

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:23 515ms/step
  5/163 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 32/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 56%|█████▌    | 28/50 [2:04:06<1:54:46, 313.02s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 23s - 10ms/step - ia: 0.7193 - loss: 0.2806 - mae: 0.4065 - rmse: 0.5103 - smape: 0.7979 - val_ia: 0.2815 - val_loss: 0.4133 - val_mae: 0.4835 - val_rmse: 0.5218 - val_smape: 1.0121

Epoch 2/32

2292/2292 - 12s - 5ms/step - ia: 0.7779 - loss: 0.1809 - mae: 0.3273 - rmse: 0.4159 - smape: 0.7115 - val_ia: 0.2721 - val_loss: 0.4823 - val_mae: 0.5167 - val_rmse: 0.5590 - val_smape: 1.0333

Epoch 3/32

2292/2292 - 11s - 5ms/step - ia: 0.7939 - loss: 0.1589 - mae: 0.3059 - rmse: 0.3897 - smape: 0.6838 - val_ia: 0.3184 - val_loss: 0.3342 - val_mae: 0.4286 - val_rmse: 0.4649 - val_smape: 0.8739

Epoch 4/32

2292/2292 - 20s - 9ms/step - ia: 0.8012 - loss: 0.1487 - mae: 0.2962 - rmse: 0.3766 - smape: 0.6627 - val_ia: 0.3246 - val_loss: 0.2914 - val_mae: 0.3972 - val_rmse: 0.4414 - val_smape: 0.8513

Epoch 5/32

2292/2292 - 12s - 5ms/step - ia: 0.8082 - loss: 0.1384 - mae: 0.2863 - rmse: 0.3633 - smape: 0.6507 - val_ia: 0.3087 - val_loss: 0.3278 - val_mae: 0.4183 - val_rmse: 0.4636 - val_smape: 0.8695

Epoch 6/32

2292/2292 - 21s - 9ms/step - ia: 0.8128 - loss: 0.1334 - mae: 0.2804 - rmse: 0.3568 - smape: 0.6379 - val_ia: 0.3077 - val_loss: 0.3231 - val_mae: 0.4174 - val_rmse: 0.4658 - val_smape: 0.8878

Epoch 7/32

2292/2292 - 12s - 5ms/step - ia: 0.8148 - loss: 0.1300 - mae: 0.2773 - rmse: 0.3522 - smape: 0.6339 - val_ia: 0.3176 - val_loss: 0.2946 - val_mae: 0.3964 - val_rmse: 0.4394 - val_smape: 0.8268

Epoch 8/32

2292/2292 - 13s - 6ms/step - ia: 0.8177 - loss: 0.1269 - mae: 0.2732 - rmse: 0.3483 - smape: 0.6212 - val_ia: 0.3171 - val_loss: 0.3156 - val_mae: 0.3995 - val_rmse: 0.4482 - val_smape: 0.8814

Epoch 9/32

2292/2292 - 11s - 5ms/step - ia: 0.8210 - loss: 0.1223 - mae: 0.2686 - rmse: 0.3417 - smape: 0.6130 - val_ia: 0.3358 - val_loss: 0.3767 - val_mae: 0.4261 - val_rmse: 0.4681 - val_smape: 0.8622

Epoch 10/32

2292/2292 - 22s - 10ms/step - ia: 0.8221 - loss: 0.1221 - mae: 0.2671 - rmse: 0.3412 - smape: 0.6061 - val_ia: 0.3334 - val_loss: 0.3678 - val_mae: 0.4246 - val_rmse: 0.4664 - val_smape: 0.8303

Epoch 11/32

2292/2292 - 10s - 4ms/step - ia: 0.8225 - loss: 0.1200 - mae: 0.2667 - rmse: 0.3386 - smape: 0.6113 - val_ia: 0.3141 - val_loss: 0.3560 - val_mae: 0.4297 - val_rmse: 0.4740 - val_smape: 0.8897

Epoch 12/32

2292/2292 - 8s - 3ms/step - ia: 0.8233 - loss: 0.1201 - mae: 0.2661 - rmse: 0.3383 - smape: 0.6077 - val_ia: 0.3130 - val_loss: 0.3412 - val_mae: 0.4262 - val_rmse: 0.4665 - val_smape: 0.9080

Epoch 13/32

2292/2292 - 7s - 3ms/step - ia: 0.8240 - loss: 0.1179 - mae: 0.2643 - rmse: 0.3354 - smape: 0.6093 - val_ia: 0.3284 - val_loss: 0.3133 - val_mae: 0.4082 - val_rmse: 0.4509 - val_smape: 0.8664

Epoch 14/32

2292/2292 - 7s - 3ms/step - ia: 0.8275 - loss: 0.1152 - mae: 0.2600 - rmse: 0.3317 - smape: 0.5952 - val_ia: 0.3259 - val_loss: 0.2743 - val_mae: 0.3948 - val_rmse: 0.4289 - val_smape: 0.8649

Epoch 15/32

2292/2292 - 16s - 7ms/step - ia: 0.8285 - loss: 0.1137 - mae: 0.2588 - rmse: 0.3295 - smape: 0.5944 - val_ia: 0.3204 - val_loss: 0.2532 - val_mae: 0.3858 - val_rmse: 0.4274 - val_smape: 0.8803

Epoch 16/32

2292/2292 - 21s - 9ms/step - ia: 0.8287 - loss: 0.1137 - mae: 0.2583 - rmse: 0.3293 - smape: 0.5931 - val_ia: 0.3109 - val_loss: 0.3053 - val_mae: 0.4177 - val_rmse: 0.4519 - val_smape: 0.9045

Epoch 17/32

2292/2292 - 13s - 6ms/step - ia: 0.8288 - loss: 0.1127 - mae: 0.2577 - rmse: 0.3277 - smape: 0.5920 - val_ia: 0.3477 - val_loss: 0.2230 - val_mae: 0.3537 - val_rmse: 0.3923 - val_smape: 0.7690

Epoch 18/32

2292/2292 - 12s - 5ms/step - ia: 0.8292 - loss: 0.1125 - mae: 0.2574 - rmse: 0.3276 - smape: 0.5901 - val_ia: 0.3298 - val_loss: 0.2548 - val_mae: 0.3831 - val_rmse: 0.4176 - val_smape: 0.8131

Epoch 19/32

2292/2292 - 11s - 5ms/step - ia: 0.8293 - loss: 0.1118 - mae: 0.2570 - rmse: 0.3267 - smape: 0.5928 - val_ia: 0.3397 - val_loss: 0.2384 - val_mae: 0.3689 - val_rmse: 0.4052 - val_smape: 0.7991

Epoch 20/32

2292/2292 - 8s - 3ms/step - ia: 0.8312 - loss: 0.1110 - mae: 0.2550 - rmse: 0.3250 - smape: 0.5907 - val_ia: 0.3273 - val_loss: 0.2361 - val_mae: 0.3776 - val_rmse: 0.4118 - val_smape: 0.8275

Epoch 21/32

2292/2292 - 10s - 4ms/step - ia: 0.8313 - loss: 0.1101 - mae: 0.2548 - rmse: 0.3241 - smape: 0.5864 - val_ia: 0.3197 - val_loss: 0.2445 - val_mae: 0.3812 - val_rmse: 0.4151 - val_smape: 0.8685

Epoch 22/32

2292/2292 - 12s - 5ms/step - ia: 0.8321 - loss: 0.1094 - mae: 0.2538 - rmse: 0.3232 - smape: 0.5838 - val_ia: 0.3302 - val_loss: 0.2496 - val_mae: 0.3842 - val_rmse: 0.4212 - val_smape: 0.8641

Epoch 23/32

2292/2292 - 20s - 9ms/step - ia: 0.8336 - loss: 0.1085 - mae: 0.2519 - rmse: 0.3215 - smape: 0.5821 - val_ia: 0.3408 - val_loss: 0.2253 - val_mae: 0.3610 - val_rmse: 0.3952 - val_smape: 0.8039

Epoch 24/32

2292/2292 - 22s - 10ms/step - ia: 0.8317 - loss: 0.1090 - mae: 0.2538 - rmse: 0.3226 - smape: 0.5815 - val_ia: 0.3276 - val_loss: 0.2313 - val_mae: 0.3733 - val_rmse: 0.4071 - val_smape: 0.8431

Epoch 25/32

2292/2292 - 9s - 4ms/step - ia: 0.8327 - loss: 0.1085 - mae: 0.2529 - rmse: 0.3214 - smape: 0.5825 - val_ia: 0.3453 - val_loss: 0.2411 - val_mae: 0.3721 - val_rmse: 0.4018 - val_smape: 0.8090

Epoch 26/32

2292/2292 - 12s - 5ms/step - ia: 0.8332 - loss: 0.1076 - mae: 0.2510 - rmse: 0.3204 - smape: 0.5782 - val_ia: 0.3610 - val_loss: 0.2120 - val_mae: 0.3520 - val_rmse: 0.3803 - val_smape: 0.7941

Epoch 27/32

2292/2292 - 11s - 5ms/step - ia: 0.8345 - loss: 0.1068 - mae: 0.2501 - rmse: 0.3191 - smape: 0.5771 - val_ia: 0.3314 - val_loss: 0.2468 - val_mae: 0.3867 - val_rmse: 0.4154 - val_smape: 0.8272

Epoch 28/32

2292/2292 - 12s - 5ms/step - ia: 0.8337 - loss: 0.1064 - mae: 0.2508 - rmse: 0.3188 - smape: 0.5852 - val_ia: 0.3331 - val_loss: 0.2450 - val_mae: 0.3782 - val_rmse: 0.4084 - val_smape: 0.8187

Epoch 29/32

2292/2292 - 12s - 5ms/step - ia: 0.8346 - loss: 0.1061 - mae: 0.2496 - rmse: 0.3181 - smape: 0.5791 - val_ia: 0.3451 - val_loss: 0.2157 - val_mae: 0.3559 - val_rmse: 0.3874 - val_smape: 0.7940

Epoch 30/32

2292/2292 - 13s - 5ms/step - ia: 0.8363 - loss: 0.1042 - mae: 0.2475 - rmse: 0.3153 - smape: 0.5711 - val_ia: 0.3321 - val_loss: 0.2437 - val_mae: 0.3789 - val_rmse: 0.4097 - val_smape: 0.8201

Epoch 31/32

2292/2292 - 11s - 5ms/step - ia: 0.8353 - loss: 0.1061 - mae: 0.2492 - rmse: 0.3176 - smape: 0.5740 - val_ia: 0.3410 - val_loss: 0.1687 - val_mae: 0.3292 - val_rmse: 0.3625 - val_smape: 0.7538

Epoch 32/32

2292/2292 - 20s - 9ms/step - ia: 0.8372 - loss: 0.1031 - mae: 0.2465 - rmse: 0.3139 - smape: 0.5726 - val_ia: 0.3468 - val_loss: 0.2352 - val_mae: 0.3694 - val_rmse: 0.3989 - val_smape: 0.8119

Restoring model weights from the end of the best epoch: 31.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:31 563ms/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 13s 83ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 58%|█████▊    | 29/50 [2:11:25<2:02:48, 350.88s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 19s - 8ms/step - ia: 0.5708 - loss: 0.5641 - mae: 0.5971 - rmse: 0.7348 - smape: 1.0089 - val_ia: 0.1661 - val_loss: 1.5147 - val_mae: 1.0376 - val_rmse: 1.0777 - val_smape: 1.3714

Epoch 2/128

2292/2292 - 18s - 8ms/step - ia: 0.6141 - loss: 0.4662 - mae: 0.5451 - rmse: 0.6726 - smape: 0.9436 - val_ia: 0.1701 - val_loss: 1.3482 - val_mae: 0.9794 - val_rmse: 1.0214 - val_smape: 1.3597

Epoch 3/128

2292/2292 - 12s - 5ms/step - ia: 0.6430 - loss: 0.4077 - mae: 0.5082 - rmse: 0.6285 - smape: 0.9003 - val_ia: 0.1761 - val_loss: 1.2662 - val_mae: 0.9284 - val_rmse: 0.9717 - val_smape: 1.3175

Epoch 4/128

2292/2292 - 21s - 9ms/step - ia: 0.6635 - loss: 0.3672 - mae: 0.4821 - rmse: 0.5963 - smape: 0.8759 - val_ia: 0.1855 - val_loss: 1.0493 - val_mae: 0.8271 - val_rmse: 0.8702 - val_smape: 1.2691

Epoch 5/128

2292/2292 - 19s - 8ms/step - ia: 0.6803 - loss: 0.3401 - mae: 0.4622 - rmse: 0.5737 - smape: 0.8538 - val_ia: 0.1955 - val_loss: 0.9329 - val_mae: 0.7706 - val_rmse: 0.8130 - val_smape: 1.2403

Epoch 6/128

2292/2292 - 11s - 5ms/step - ia: 0.6929 - loss: 0.3169 - mae: 0.4455 - rmse: 0.5532 - smape: 0.8345 - val_ia: 0.2014 - val_loss: 0.9289 - val_mae: 0.7591 - val_rmse: 0.8008 - val_smape: 1.2166

Epoch 7/128

2292/2292 - 11s - 5ms/step - ia: 0.7034 - loss: 0.3013 - mae: 0.4329 - rmse: 0.5394 - smape: 0.8194 - val_ia: 0.2018 - val_loss: 0.9561 - val_mae: 0.7675 - val_rmse: 0.8094 - val_smape: 1.2114

Epoch 8/128

2292/2292 - 10s - 5ms/step - ia: 0.7103 - loss: 0.2883 - mae: 0.4227 - rmse: 0.5269 - smape: 0.8072 - val_ia: 0.2116 - val_loss: 0.9032 - val_mae: 0.7390 - val_rmse: 0.7809 - val_smape: 1.1929

Epoch 9/128

2292/2292 - 11s - 5ms/step - ia: 0.7192 - loss: 0.2747 - mae: 0.4123 - rmse: 0.5147 - smape: 0.7929 - val_ia: 0.2191 - val_loss: 0.8422 - val_mae: 0.7091 - val_rmse: 0.7511 - val_smape: 1.1654

Epoch 10/128

2292/2292 - 20s - 9ms/step - ia: 0.7236 - loss: 0.2674 - mae: 0.4068 - rmse: 0.5083 - smape: 0.7843 - val_ia: 0.2270 - val_loss: 0.7931 - val_mae: 0.6812 - val_rmse: 0.7237 - val_smape: 1.1416

Epoch 11/128

2292/2292 - 11s - 5ms/step - ia: 0.7297 - loss: 0.2576 - mae: 0.3989 - rmse: 0.4983 - smape: 0.7764 - val_ia: 0.2312 - val_loss: 0.7574 - val_mae: 0.6600 - val_rmse: 0.7043 - val_smape: 1.1178

Epoch 12/128

2292/2292 - 20s - 9ms/step - ia: 0.7321 - loss: 0.2545 - mae: 0.3952 - rmse: 0.4955 - smape: 0.7710 - val_ia: 0.2325 - val_loss: 0.7750 - val_mae: 0.6712 - val_rmse: 0.7141 - val_smape: 1.1304

Epoch 13/128

2292/2292 - 8s - 3ms/step - ia: 0.7366 - loss: 0.2451 - mae: 0.3889 - rmse: 0.4861 - smape: 0.7616 - val_ia: 0.2353 - val_loss: 0.7598 - val_mae: 0.6588 - val_rmse: 0.7023 - val_smape: 1.1145

Epoch 14/128

2292/2292 - 6s - 3ms/step - ia: 0.7400 - loss: 0.2408 - mae: 0.3844 - rmse: 0.4819 - smape: 0.7557 - val_ia: 0.2424 - val_loss: 0.7145 - val_mae: 0.6380 - val_rmse: 0.6813 - val_smape: 1.0998

Epoch 15/128

2292/2292 - 6s - 3ms/step - ia: 0.7445 - loss: 0.2342 - mae: 0.3776 - rmse: 0.4747 - smape: 0.7468 - val_ia: 0.2395 - val_loss: 0.7605 - val_mae: 0.6539 - val_rmse: 0.6979 - val_smape: 1.1003

Epoch 16/128

2292/2292 - 10s - 4ms/step - ia: 0.7467 - loss: 0.2305 - mae: 0.3750 - rmse: 0.4713 - smape: 0.7415 - val_ia: 0.2496 - val_loss: 0.6867 - val_mae: 0.6254 - val_rmse: 0.6679 - val_smape: 1.1000

Epoch 17/128

2292/2292 - 12s - 5ms/step - ia: 0.7483 - loss: 0.2291 - mae: 0.3727 - rmse: 0.4698 - smape: 0.7388 - val_ia: 0.2493 - val_loss: 0.7143 - val_mae: 0.6317 - val_rmse: 0.6756 - val_smape: 1.0937

Epoch 18/128

2292/2292 - 11s - 5ms/step - ia: 0.7525 - loss: 0.2219 - mae: 0.3675 - rmse: 0.4621 - smape: 0.7323 - val_ia: 0.2500 - val_loss: 0.7140 - val_mae: 0.6328 - val_rmse: 0.6762 - val_smape: 1.0949

Epoch 19/128

2292/2292 - 12s - 5ms/step - ia: 0.7542 - loss: 0.2184 - mae: 0.3638 - rmse: 0.4582 - smape: 0.7295 - val_ia: 0.2556 - val_loss: 0.6641 - val_mae: 0.6103 - val_rmse: 0.6546 - val_smape: 1.0826

Epoch 20/128

2292/2292 - 19s - 8ms/step - ia: 0.7563 - loss: 0.2159 - mae: 0.3620 - rmse: 0.4559 - smape: 0.7273 - val_ia: 0.2592 - val_loss: 0.6559 - val_mae: 0.6014 - val_rmse: 0.6473 - val_smape: 1.0727

Epoch 21/128

2292/2292 - 10s - 4ms/step - ia: 0.7586 - loss: 0.2123 - mae: 0.3585 - rmse: 0.4520 - smape: 0.7238 - val_ia: 0.2604 - val_loss: 0.6230 - val_mae: 0.5919 - val_rmse: 0.6363 - val_smape: 1.0722

Epoch 22/128

2292/2292 - 11s - 5ms/step - ia: 0.7593 - loss: 0.2100 - mae: 0.3567 - rmse: 0.4494 - smape: 0.7211 - val_ia: 0.2649 - val_loss: 0.6117 - val_mae: 0.5822 - val_rmse: 0.6281 - val_smape: 1.0652

Epoch 23/128

2292/2292 - 11s - 5ms/step - ia: 0.7620 - loss: 0.2065 - mae: 0.3535 - rmse: 0.4460 - smape: 0.7165 - val_ia: 0.2650 - val_loss: 0.6152 - val_mae: 0.5858 - val_rmse: 0.6313 - val_smape: 1.0721

Epoch 24/128

2292/2292 - 11s - 5ms/step - ia: 0.7646 - loss: 0.2028 - mae: 0.3500 - rmse: 0.4410 - smape: 0.7128 - val_ia: 0.2633 - val_loss: 0.6220 - val_mae: 0.5904 - val_rmse: 0.6353 - val_smape: 1.0723

Epoch 25/128

2292/2292 - 10s - 4ms/step - ia: 0.7664 - loss: 0.2000 - mae: 0.3474 - rmse: 0.4380 - smape: 0.7121 - val_ia: 0.2660 - val_loss: 0.6067 - val_mae: 0.5829 - val_rmse: 0.6275 - val_smape: 1.0711

Epoch 26/128

2292/2292 - 11s - 5ms/step - ia: 0.7690 - loss: 0.1972 - mae: 0.3446 - rmse: 0.4352 - smape: 0.7090 - val_ia: 0.2678 - val_loss: 0.5676 - val_mae: 0.5668 - val_rmse: 0.6110 - val_smape: 1.0695

Epoch 27/128

2292/2292 - 10s - 4ms/step - ia: 0.7679 - loss: 0.1981 - mae: 0.3450 - rmse: 0.4363 - smape: 0.7060 - val_ia: 0.2712 - val_loss: 0.5312 - val_mae: 0.5490 - val_rmse: 0.5926 - val_smape: 1.0564

Epoch 28/128

2292/2292 - 7s - 3ms/step - ia: 0.7699 - loss: 0.1947 - mae: 0.3426 - rmse: 0.4320 - smape: 0.7044 - val_ia: 0.2737 - val_loss: 0.5378 - val_mae: 0.5508 - val_rmse: 0.5935 - val_smape: 1.0572

Epoch 29/128

2292/2292 - 7s - 3ms/step - ia: 0.7727 - loss: 0.1917 - mae: 0.3390 - rmse: 0.4288 - smape: 0.6986 - val_ia: 0.2719 - val_loss: 0.5425 - val_mae: 0.5542 - val_rmse: 0.5969 - val_smape: 1.0613

Epoch 30/128

2292/2292 - 14s - 6ms/step - ia: 0.7725 - loss: 0.1908 - mae: 0.3387 - rmse: 0.4280 - smape: 0.6998 - val_ia: 0.2750 - val_loss: 0.5382 - val_mae: 0.5490 - val_rmse: 0.5933 - val_smape: 1.0521

Epoch 31/128

2292/2292 - 9s - 4ms/step - ia: 0.7753 - loss: 0.1872 - mae: 0.3348 - rmse: 0.4242 - smape: 0.6930 - val_ia: 0.2747 - val_loss: 0.4953 - val_mae: 0.5323 - val_rmse: 0.5755 - val_smape: 1.0470

Epoch 32/128

2292/2292 - 10s - 4ms/step - ia: 0.7753 - loss: 0.1874 - mae: 0.3357 - rmse: 0.4240 - smape: 0.6970 - val_ia: 0.2773 - val_loss: 0.5084 - val_mae: 0.5383 - val_rmse: 0.5801 - val_smape: 1.0452

Epoch 33/128

2292/2292 - 8s - 3ms/step - ia: 0.7761 - loss: 0.1859 - mae: 0.3339 - rmse: 0.4223 - smape: 0.6910 - val_ia: 0.2788 - val_loss: 0.4823 - val_mae: 0.5250 - val_rmse: 0.5670 - val_smape: 1.0398

Epoch 34/128

2292/2292 - 11s - 5ms/step - ia: 0.7766 - loss: 0.1839 - mae: 0.3325 - rmse: 0.4200 - smape: 0.6947 - val_ia: 0.2807 - val_loss: 0.4536 - val_mae: 0.5135 - val_rmse: 0.5556 - val_smape: 1.0446

Epoch 35/128

2292/2292 - 10s - 4ms/step - ia: 0.7781 - loss: 0.1825 - mae: 0.3312 - rmse: 0.4184 - smape: 0.6927 - val_ia: 0.2843 - val_loss: 0.4584 - val_mae: 0.5126 - val_rmse: 0.5538 - val_smape: 1.0288

Epoch 36/128

2292/2292 - 13s - 6ms/step - ia: 0.7796 - loss: 0.1807 - mae: 0.3288 - rmse: 0.4161 - smape: 0.6874 - val_ia: 0.2845 - val_loss: 0.4487 - val_mae: 0.5083 - val_rmse: 0.5493 - val_smape: 1.0317

Epoch 37/128

2292/2292 - 10s - 5ms/step - ia: 0.7795 - loss: 0.1786 - mae: 0.3279 - rmse: 0.4141 - smape: 0.6861 - val_ia: 0.2815 - val_loss: 0.4781 - val_mae: 0.5245 - val_rmse: 0.5646 - val_smape: 1.0373

Epoch 38/128

2292/2292 - 11s - 5ms/step - ia: 0.7823 - loss: 0.1772 - mae: 0.3254 - rmse: 0.4124 - smape: 0.6830 - val_ia: 0.2831 - val_loss: 0.4562 - val_mae: 0.5148 - val_rmse: 0.5542 - val_smape: 1.0330

Epoch 39/128

2292/2292 - 10s - 4ms/step - ia: 0.7817 - loss: 0.1760 - mae: 0.3249 - rmse: 0.4108 - smape: 0.6848 - val_ia: 0.2864 - val_loss: 0.4240 - val_mae: 0.4980 - val_rmse: 0.5381 - val_smape: 1.0212

Epoch 40/128

2292/2292 - 12s - 5ms/step - ia: 0.7829 - loss: 0.1755 - mae: 0.3235 - rmse: 0.4101 - smape: 0.6825 - val_ia: 0.2887 - val_loss: 0.4254 - val_mae: 0.4968 - val_rmse: 0.5368 - val_smape: 1.0162

Epoch 41/128

2292/2292 - 10s - 4ms/step - ia: 0.7834 - loss: 0.1737 - mae: 0.3222 - rmse: 0.4082 - smape: 0.6808 - val_ia: 0.2884 - val_loss: 0.4330 - val_mae: 0.5014 - val_rmse: 0.5411 - val_smape: 1.0190

Epoch 42/128

2292/2292 - 10s - 4ms/step - ia: 0.7860 - loss: 0.1708 - mae: 0.3197 - rmse: 0.4049 - smape: 0.6748 - val_ia: 0.2919 - val_loss: 0.4156 - val_mae: 0.4908 - val_rmse: 0.5310 - val_smape: 1.0089

Epoch 43/128

2292/2292 - 10s - 4ms/step - ia: 0.7853 - loss: 0.1717 - mae: 0.3200 - rmse: 0.4058 - smape: 0.6772 - val_ia: 0.2886 - val_loss: 0.4353 - val_mae: 0.5030 - val_rmse: 0.5420 - val_smape: 1.0155

Epoch 44/128

2292/2292 - 10s - 4ms/step - ia: 0.7868 - loss: 0.1697 - mae: 0.3184 - rmse: 0.4031 - smape: 0.6766 - val_ia: 0.2930 - val_loss: 0.4031 - val_mae: 0.4850 - val_rmse: 0.5244 - val_smape: 0.9996

Epoch 45/128

2292/2292 - 8s - 4ms/step - ia: 0.7877 - loss: 0.1683 - mae: 0.3174 - rmse: 0.4017 - smape: 0.6717 - val_ia: 0.2963 - val_loss: 0.3774 - val_mae: 0.4717 - val_rmse: 0.5117 - val_smape: 0.9877

Epoch 46/128

2292/2292 - 11s - 5ms/step - ia: 0.7883 - loss: 0.1688 - mae: 0.3171 - rmse: 0.4025 - smape: 0.6735 - val_ia: 0.2957 - val_loss: 0.3950 - val_mae: 0.4802 - val_rmse: 0.5192 - val_smape: 0.9935

Epoch 47/128

2292/2292 - 11s - 5ms/step - ia: 0.7887 - loss: 0.1667 - mae: 0.3152 - rmse: 0.4000 - smape: 0.6729 - val_ia: 0.2973 - val_loss: 0.3718 - val_mae: 0.4682 - val_rmse: 0.5080 - val_smape: 0.9862

Epoch 48/128

2292/2292 - 11s - 5ms/step - ia: 0.7912 - loss: 0.1633 - mae: 0.3123 - rmse: 0.3954 - smape: 0.6649 - val_ia: 0.2997 - val_loss: 0.3649 - val_mae: 0.4646 - val_rmse: 0.5039 - val_smape: 0.9751

Epoch 49/128

2292/2292 - 22s - 10ms/step - ia: 0.7914 - loss: 0.1636 - mae: 0.3119 - rmse: 0.3961 - smape: 0.6679 - val_ia: 0.2993 - val_loss: 0.3602 - val_mae: 0.4612 - val_rmse: 0.5007 - val_smape: 0.9698

Epoch 50/128

2292/2292 - 17s - 8ms/step - ia: 0.7917 - loss: 0.1632 - mae: 0.3118 - rmse: 0.3952 - smape: 0.6651 - val_ia: 0.3034 - val_loss: 0.3496 - val_mae: 0.4548 - val_rmse: 0.4933 - val_smape: 0.9590

Epoch 51/128

2292/2292 - 13s - 6ms/step - ia: 0.7918 - loss: 0.1625 - mae: 0.3115 - rmse: 0.3951 - smape: 0.6674 - val_ia: 0.3007 - val_loss: 0.3598 - val_mae: 0.4604 - val_rmse: 0.4988 - val_smape: 0.9673

Epoch 52/128

2292/2292 - 11s - 5ms/step - ia: 0.7930 - loss: 0.1619 - mae: 0.3107 - rmse: 0.3939 - smape: 0.6646 - val_ia: 0.2993 - val_loss: 0.3595 - val_mae: 0.4620 - val_rmse: 0.5001 - val_smape: 0.9765

Epoch 53/128

2292/2292 - 22s - 10ms/step - ia: 0.7928 - loss: 0.1607 - mae: 0.3093 - rmse: 0.3928 - smape: 0.6613 - val_ia: 0.3043 - val_loss: 0.3527 - val_mae: 0.4560 - val_rmse: 0.4944 - val_smape: 0.9611

Epoch 54/128

2292/2292 - 10s - 4ms/step - ia: 0.7945 - loss: 0.1586 - mae: 0.3072 - rmse: 0.3901 - smape: 0.6603 - val_ia: 0.3065 - val_loss: 0.3353 - val_mae: 0.4463 - val_rmse: 0.4850 - val_smape: 0.9544

Epoch 55/128

2292/2292 - 8s - 3ms/step - ia: 0.7954 - loss: 0.1576 - mae: 0.3065 - rmse: 0.3886 - smape: 0.6608 - val_ia: 0.3066 - val_loss: 0.3363 - val_mae: 0.4456 - val_rmse: 0.4834 - val_smape: 0.9398

Epoch 56/128

2292/2292 - 10s - 4ms/step - ia: 0.7968 - loss: 0.1570 - mae: 0.3054 - rmse: 0.3877 - smape: 0.6582 - val_ia: 0.3073 - val_loss: 0.3248 - val_mae: 0.4397 - val_rmse: 0.4780 - val_smape: 0.9395

Epoch 57/128

2292/2292 - 11s - 5ms/step - ia: 0.7972 - loss: 0.1565 - mae: 0.3049 - rmse: 0.3872 - smape: 0.6556 - val_ia: 0.3079 - val_loss: 0.3250 - val_mae: 0.4396 - val_rmse: 0.4769 - val_smape: 0.9364

Epoch 58/128

2292/2292 - 11s - 5ms/step - ia: 0.7963 - loss: 0.1568 - mae: 0.3050 - rmse: 0.3877 - smape: 0.6546 - val_ia: 0.3113 - val_loss: 0.3266 - val_mae: 0.4383 - val_rmse: 0.4759 - val_smape: 0.9240

Epoch 59/128

2292/2292 - 8s - 4ms/step - ia: 0.7987 - loss: 0.1544 - mae: 0.3028 - rmse: 0.3848 - smape: 0.6537 - val_ia: 0.3106 - val_loss: 0.3220 - val_mae: 0.4376 - val_rmse: 0.4746 - val_smape: 0.9268

Epoch 60/128

2292/2292 - 7s - 3ms/step - ia: 0.7991 - loss: 0.1535 - mae: 0.3017 - rmse: 0.3836 - smape: 0.6525 - val_ia: 0.3123 - val_loss: 0.3122 - val_mae: 0.4309 - val_rmse: 0.4691 - val_smape: 0.9256

Epoch 61/128

2292/2292 - 7s - 3ms/step - ia: 0.7990 - loss: 0.1538 - mae: 0.3022 - rmse: 0.3840 - smape: 0.6529 - val_ia: 0.3115 - val_loss: 0.3122 - val_mae: 0.4317 - val_rmse: 0.4696 - val_smape: 0.9258

Epoch 62/128

2292/2292 - 10s - 4ms/step - ia: 0.7994 - loss: 0.1525 - mae: 0.3003 - rmse: 0.3816 - smape: 0.6508 - val_ia: 0.3145 - val_loss: 0.3088 - val_mae: 0.4298 - val_rmse: 0.4658 - val_smape: 0.9186

Epoch 63/128

2292/2292 - 8s - 4ms/step - ia: 0.8009 - loss: 0.1505 - mae: 0.2991 - rmse: 0.3800 - smape: 0.6494 - val_ia: 0.3158 - val_loss: 0.2878 - val_mae: 0.4163 - val_rmse: 0.4541 - val_smape: 0.9054

Epoch 64/128

2292/2292 - 9s - 4ms/step - ia: 0.8000 - loss: 0.1503 - mae: 0.2988 - rmse: 0.3791 - smape: 0.6491 - val_ia: 0.3171 - val_loss: 0.2896 - val_mae: 0.4165 - val_rmse: 0.4542 - val_smape: 0.8994

Epoch 65/128

2292/2292 - 12s - 5ms/step - ia: 0.8017 - loss: 0.1488 - mae: 0.2975 - rmse: 0.3779 - smape: 0.6440 - val_ia: 0.3153 - val_loss: 0.3040 - val_mae: 0.4245 - val_rmse: 0.4616 - val_smape: 0.9050

Epoch 66/128

2292/2292 - 19s - 8ms/step - ia: 0.8013 - loss: 0.1492 - mae: 0.2973 - rmse: 0.3781 - smape: 0.6466 - val_ia: 0.3206 - val_loss: 0.2793 - val_mae: 0.4092 - val_rmse: 0.4457 - val_smape: 0.8915

Epoch 67/128

2292/2292 - 9s - 4ms/step - ia: 0.8024 - loss: 0.1484 - mae: 0.2966 - rmse: 0.3768 - smape: 0.6444 - val_ia: 0.3211 - val_loss: 0.2763 - val_mae: 0.4070 - val_rmse: 0.4441 - val_smape: 0.8806

Epoch 68/128

2292/2292 - 9s - 4ms/step - ia: 0.8015 - loss: 0.1481 - mae: 0.2970 - rmse: 0.3769 - smape: 0.6448 - val_ia: 0.3244 - val_loss: 0.2614 - val_mae: 0.3977 - val_rmse: 0.4347 - val_smape: 0.8728

Epoch 69/128

2292/2292 - 7s - 3ms/step - ia: 0.8036 - loss: 0.1468 - mae: 0.2951 - rmse: 0.3749 - smape: 0.6446 - val_ia: 0.3229 - val_loss: 0.2638 - val_mae: 0.3998 - val_rmse: 0.4359 - val_smape: 0.8765

Epoch 70/128

2292/2292 - 7s - 3ms/step - ia: 0.8028 - loss: 0.1468 - mae: 0.2952 - rmse: 0.3751 - smape: 0.6422 - val_ia: 0.3229 - val_loss: 0.2788 - val_mae: 0.4082 - val_rmse: 0.4442 - val_smape: 0.8808

Epoch 71/128

2292/2292 - 9s - 4ms/step - ia: 0.8050 - loss: 0.1453 - mae: 0.2930 - rmse: 0.3725 - smape: 0.6379 - val_ia: 0.3299 - val_loss: 0.2525 - val_mae: 0.3897 - val_rmse: 0.4259 - val_smape: 0.8480

Epoch 72/128

2292/2292 - 11s - 5ms/step - ia: 0.8050 - loss: 0.1448 - mae: 0.2926 - rmse: 0.3721 - smape: 0.6400 - val_ia: 0.3233 - val_loss: 0.2710 - val_mae: 0.4033 - val_rmse: 0.4394 - val_smape: 0.8696

Epoch 73/128

2292/2292 - 10s - 5ms/step - ia: 0.8054 - loss: 0.1439 - mae: 0.2924 - rmse: 0.3713 - smape: 0.6395 - val_ia: 0.3230 - val_loss: 0.2669 - val_mae: 0.4010 - val_rmse: 0.4372 - val_smape: 0.8702

Epoch 74/128

2292/2292 - 10s - 4ms/step - ia: 0.8049 - loss: 0.1443 - mae: 0.2932 - rmse: 0.3716 - smape: 0.6396 - val_ia: 0.3294 - val_loss: 0.2555 - val_mae: 0.3916 - val_rmse: 0.4273 - val_smape: 0.8508

Epoch 75/128

2292/2292 - 11s - 5ms/step - ia: 0.8055 - loss: 0.1426 - mae: 0.2918 - rmse: 0.3700 - smape: 0.6384 - val_ia: 0.3265 - val_loss: 0.2747 - val_mae: 0.4032 - val_rmse: 0.4395 - val_smape: 0.8642

Epoch 76/128

2292/2292 - 11s - 5ms/step - ia: 0.8071 - loss: 0.1416 - mae: 0.2896 - rmse: 0.3679 - smape: 0.6345 - val_ia: 0.3271 - val_loss: 0.2731 - val_mae: 0.4039 - val_rmse: 0.4397 - val_smape: 0.8667

Epoch 77/128

2292/2292 - 12s - 5ms/step - ia: 0.8072 - loss: 0.1417 - mae: 0.2894 - rmse: 0.3683 - smape: 0.6349 - val_ia: 0.3301 - val_loss: 0.2601 - val_mae: 0.3955 - val_rmse: 0.4305 - val_smape: 0.8530

Epoch 78/128

2292/2292 - 17s - 7ms/step - ia: 0.8069 - loss: 0.1411 - mae: 0.2892 - rmse: 0.3675 - smape: 0.6327 - val_ia: 0.3299 - val_loss: 0.2444 - val_mae: 0.3850 - val_rmse: 0.4198 - val_smape: 0.8399

Epoch 79/128

2292/2292 - 9s - 4ms/step - ia: 0.8069 - loss: 0.1415 - mae: 0.2901 - rmse: 0.3679 - smape: 0.6359 - val_ia: 0.3294 - val_loss: 0.2632 - val_mae: 0.3967 - val_rmse: 0.4327 - val_smape: 0.8548

Epoch 80/128

2292/2292 - 8s - 4ms/step - ia: 0.8090 - loss: 0.1401 - mae: 0.2877 - rmse: 0.3662 - smape: 0.6332 - val_ia: 0.3330 - val_loss: 0.2406 - val_mae: 0.3823 - val_rmse: 0.4178 - val_smape: 0.8286

Epoch 81/128

2292/2292 - 12s - 5ms/step - ia: 0.8092 - loss: 0.1399 - mae: 0.2873 - rmse: 0.3656 - smape: 0.6297 - val_ia: 0.3343 - val_loss: 0.2365 - val_mae: 0.3786 - val_rmse: 0.4135 - val_smape: 0.8201

Epoch 82/128

2292/2292 - 11s - 5ms/step - ia: 0.8093 - loss: 0.1388 - mae: 0.2872 - rmse: 0.3645 - smape: 0.6314 - val_ia: 0.3344 - val_loss: 0.2274 - val_mae: 0.3744 - val_rmse: 0.4093 - val_smape: 0.8261

Epoch 83/128

2292/2292 - 8s - 4ms/step - ia: 0.8101 - loss: 0.1380 - mae: 0.2855 - rmse: 0.3632 - smape: 0.6278 - val_ia: 0.3399 - val_loss: 0.2157 - val_mae: 0.3632 - val_rmse: 0.3981 - val_smape: 0.7981

Epoch 84/128

2292/2292 - 8s - 4ms/step - ia: 0.8098 - loss: 0.1373 - mae: 0.2854 - rmse: 0.3627 - smape: 0.6308 - val_ia: 0.3348 - val_loss: 0.2395 - val_mae: 0.3798 - val_rmse: 0.4153 - val_smape: 0.8248

Epoch 85/128

2292/2292 - 7s - 3ms/step - ia: 0.8094 - loss: 0.1390 - mae: 0.2871 - rmse: 0.3650 - smape: 0.6332 - val_ia: 0.3373 - val_loss: 0.2250 - val_mae: 0.3698 - val_rmse: 0.4045 - val_smape: 0.8061

Epoch 86/128

2292/2292 - 8s - 3ms/step - ia: 0.8095 - loss: 0.1365 - mae: 0.2855 - rmse: 0.3616 - smape: 0.6315 - val_ia: 0.3396 - val_loss: 0.2258 - val_mae: 0.3694 - val_rmse: 0.4044 - val_smape: 0.7992

Epoch 87/128

2292/2292 - 5s - 2ms/step - ia: 0.8115 - loss: 0.1358 - mae: 0.2836 - rmse: 0.3604 - smape: 0.6273 - val_ia: 0.3394 - val_loss: 0.2178 - val_mae: 0.3648 - val_rmse: 0.3995 - val_smape: 0.7990

Epoch 88/128

2292/2292 - 7s - 3ms/step - ia: 0.8114 - loss: 0.1355 - mae: 0.2833 - rmse: 0.3602 - smape: 0.6261 - val_ia: 0.3399 - val_loss: 0.2235 - val_mae: 0.3688 - val_rmse: 0.4039 - val_smape: 0.8044

Epoch 89/128

2292/2292 - 6s - 3ms/step - ia: 0.8120 - loss: 0.1352 - mae: 0.2831 - rmse: 0.3598 - smape: 0.6250 - val_ia: 0.3401 - val_loss: 0.2180 - val_mae: 0.3655 - val_rmse: 0.3999 - val_smape: 0.7969

Epoch 90/128

2292/2292 - 5s - 2ms/step - ia: 0.8115 - loss: 0.1345 - mae: 0.2829 - rmse: 0.3590 - smape: 0.6257 - val_ia: 0.3398 - val_loss: 0.2213 - val_mae: 0.3674 - val_rmse: 0.4016 - val_smape: 0.7995

Epoch 91/128

2292/2292 - 8s - 3ms/step - ia: 0.8127 - loss: 0.1343 - mae: 0.2813 - rmse: 0.3583 - smape: 0.6210 - val_ia: 0.3439 - val_loss: 0.2112 - val_mae: 0.3581 - val_rmse: 0.3930 - val_smape: 0.7787

Epoch 92/128

2292/2292 - 9s - 4ms/step - ia: 0.8128 - loss: 0.1342 - mae: 0.2816 - rmse: 0.3581 - smape: 0.6223 - val_ia: 0.3431 - val_loss: 0.2026 - val_mae: 0.3540 - val_rmse: 0.3884 - val_smape: 0.7802

Epoch 93/128

2292/2292 - 10s - 4ms/step - ia: 0.8131 - loss: 0.1334 - mae: 0.2817 - rmse: 0.3574 - smape: 0.6228 - val_ia: 0.3421 - val_loss: 0.2165 - val_mae: 0.3630 - val_rmse: 0.3971 - val_smape: 0.7887

Epoch 94/128

2292/2292 - 10s - 4ms/step - ia: 0.8136 - loss: 0.1336 - mae: 0.2810 - rmse: 0.3576 - smape: 0.6216 - val_ia: 0.3461 - val_loss: 0.1976 - val_mae: 0.3494 - val_rmse: 0.3832 - val_smape: 0.7710

Epoch 95/128

2292/2292 - 9s - 4ms/step - ia: 0.8134 - loss: 0.1332 - mae: 0.2807 - rmse: 0.3575 - smape: 0.6217 - val_ia: 0.3484 - val_loss: 0.1954 - val_mae: 0.3468 - val_rmse: 0.3804 - val_smape: 0.7618

Epoch 96/128

2292/2292 - 10s - 4ms/step - ia: 0.8127 - loss: 0.1340 - mae: 0.2813 - rmse: 0.3581 - smape: 0.6237 - val_ia: 0.3438 - val_loss: 0.2052 - val_mae: 0.3549 - val_rmse: 0.3891 - val_smape: 0.7766

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2292/2292 - 20s - 9ms/step - ia: 0.3969 - loss: 0.7109 - mae: 0.6854 - rmse: 0.8238 - smape: 1.3242 - val_ia: 0.1688 - val_loss: 1.2310 - val_mae: 0.9446 - val_rmse: 0.9786 - val_smape: 1.3548

Epoch 2/256

2292/2292 - 11s - 5ms/step - ia: 0.6201 - loss: 0.4537 - mae: 0.5342 - rmse: 0.6634 - smape: 0.9039 - val_ia: 0.1649 - val_loss: 1.2850 - val_mae: 0.9656 - val_rmse: 1.0006 - val_smape: 1.3773

Epoch 3/256

2292/2292 - 11s - 5ms/step - ia: 0.6308 - loss: 0.4356 - mae: 0.5217 - rmse: 0.6498 - smape: 0.8908 - val_ia: 0.1695 - val_loss: 1.2813 - val_mae: 0.9527 - val_rmse: 0.9898 - val_smape: 1.3600

Epoch 4/256

2292/2292 - 16s - 7ms/step - ia: 0.6436 - loss: 0.4123 - mae: 0.5061 - rmse: 0.6317 - smape: 0.8726 - val_ia: 0.1712 - val_loss: 1.3860 - val_mae: 0.9859 - val_rmse: 1.0232 - val_smape: 1.3790

Epoch 5/256

2292/2292 - 18s - 8ms/step - ia: 0.6593 - loss: 0.3803 - mae: 0.4864 - rmse: 0.6064 - smape: 0.8519 - val_ia: 0.1759 - val_loss: 1.2594 - val_mae: 0.9128 - val_rmse: 0.9522 - val_smape: 1.3343

Epoch 6/256

2292/2292 - 12s - 5ms/step - ia: 0.6771 - loss: 0.3480 - mae: 0.4666 - rmse: 0.5801 - smape: 0.8373 - val_ia: 0.1756 - val_loss: 1.2193 - val_mae: 0.8810 - val_rmse: 0.9207 - val_smape: 1.3169

Epoch 7/256

2292/2292 - 11s - 5ms/step - ia: 0.6924 - loss: 0.3199 - mae: 0.4466 - rmse: 0.5561 - smape: 0.8229 - val_ia: 0.1764 - val_loss: 1.2319 - val_mae: 0.8757 - val_rmse: 0.9159 - val_smape: 1.3064

Epoch 8/256

2292/2292 - 11s - 5ms/step - ia: 0.7090 - loss: 0.2910 - mae: 0.4247 - rmse: 0.5300 - smape: 0.8062 - val_ia: 0.1806 - val_loss: 1.0653 - val_mae: 0.8011 - val_rmse: 0.8407 - val_smape: 1.2386

Epoch 9/256

2292/2292 - 10s - 4ms/step - ia: 0.7258 - loss: 0.2633 - mae: 0.4027 - rmse: 0.5042 - smape: 0.7830 - val_ia: 0.1937 - val_loss: 0.8752 - val_mae: 0.7187 - val_rmse: 0.7575 - val_smape: 1.1709

Epoch 10/256

2292/2292 - 10s - 5ms/step - ia: 0.7403 - loss: 0.2420 - mae: 0.3846 - rmse: 0.4832 - smape: 0.7597 - val_ia: 0.1996 - val_loss: 0.8690 - val_mae: 0.7179 - val_rmse: 0.7567 - val_smape: 1.1642

Epoch 11/256

2292/2292 - 10s - 4ms/step - ia: 0.7493 - loss: 0.2278 - mae: 0.3718 - rmse: 0.4682 - smape: 0.7405 - val_ia: 0.2102 - val_loss: 0.8189 - val_mae: 0.6940 - val_rmse: 0.7349 - val_smape: 1.1351

Epoch 12/256

2292/2292 - 11s - 5ms/step - ia: 0.7558 - loss: 0.2172 - mae: 0.3624 - rmse: 0.4570 - smape: 0.7278 - val_ia: 0.2206 - val_loss: 0.7395 - val_mae: 0.6592 - val_rmse: 0.7016 - val_smape: 1.1023

Epoch 13/256

2292/2292 - 10s - 4ms/step - ia: 0.7621 - loss: 0.2089 - mae: 0.3541 - rmse: 0.4482 - smape: 0.7178 - val_ia: 0.2272 - val_loss: 0.7349 - val_mae: 0.6580 - val_rmse: 0.7003 - val_smape: 1.0962

Epoch 14/256

2292/2292 - 9s - 4ms/step - ia: 0.7678 - loss: 0.2019 - mae: 0.3470 - rmse: 0.4404 - smape: 0.7093 - val_ia: 0.2370 - val_loss: 0.6510 - val_mae: 0.6158 - val_rmse: 0.6618 - val_smape: 1.0524

Epoch 15/256

2292/2292 - 11s - 5ms/step - ia: 0.7725 - loss: 0.1959 - mae: 0.3410 - rmse: 0.4334 - smape: 0.7016 - val_ia: 0.2356 - val_loss: 0.7102 - val_mae: 0.6424 - val_rmse: 0.6872 - val_smape: 1.0641

Epoch 16/256

2292/2292 - 10s - 4ms/step - ia: 0.7756 - loss: 0.1906 - mae: 0.3359 - rmse: 0.4272 - smape: 0.6948 - val_ia: 0.2421 - val_loss: 0.6563 - val_mae: 0.6160 - val_rmse: 0.6632 - val_smape: 1.0420

Epoch 17/256

2292/2292 - 11s - 5ms/step - ia: 0.7793 - loss: 0.1858 - mae: 0.3310 - rmse: 0.4219 - smape: 0.6880 - val_ia: 0.2425 - val_loss: 0.6772 - val_mae: 0.6263 - val_rmse: 0.6724 - val_smape: 1.0420

Epoch 18/256

2292/2292 - 19s - 8ms/step - ia: 0.7829 - loss: 0.1812 - mae: 0.3259 - rmse: 0.4170 - smape: 0.6831 - val_ia: 0.2516 - val_loss: 0.5936 - val_mae: 0.5885 - val_rmse: 0.6362 - val_smape: 1.0197

Epoch 19/256

2292/2292 - 10s - 4ms/step - ia: 0.7853 - loss: 0.1768 - mae: 0.3217 - rmse: 0.4120 - smape: 0.6771 - val_ia: 0.2571 - val_loss: 0.5411 - val_mae: 0.5611 - val_rmse: 0.6102 - val_smape: 0.9922

Epoch 20/256

2292/2292 - 11s - 5ms/step - ia: 0.7883 - loss: 0.1727 - mae: 0.3174 - rmse: 0.4063 - smape: 0.6718 - val_ia: 0.2581 - val_loss: 0.5190 - val_mae: 0.5507 - val_rmse: 0.6002 - val_smape: 0.9949

Epoch 21/256

2292/2292 - 20s - 9ms/step - ia: 0.7913 - loss: 0.1688 - mae: 0.3133 - rmse: 0.4019 - smape: 0.6667 - val_ia: 0.2650 - val_loss: 0.4873 - val_mae: 0.5343 - val_rmse: 0.5831 - val_smape: 0.9728

Epoch 22/256

2292/2292 - 11s - 5ms/step - ia: 0.7940 - loss: 0.1652 - mae: 0.3102 - rmse: 0.3978 - smape: 0.6641 - val_ia: 0.2588 - val_loss: 0.5452 - val_mae: 0.5674 - val_rmse: 0.6128 - val_smape: 0.9933

Epoch 23/256

2292/2292 - 21s - 9ms/step - ia: 0.7958 - loss: 0.1614 - mae: 0.3066 - rmse: 0.3930 - smape: 0.6605 - val_ia: 0.2696 - val_loss: 0.4772 - val_mae: 0.5299 - val_rmse: 0.5766 - val_smape: 0.9576

Epoch 24/256

2292/2292 - 20s - 9ms/step - ia: 0.7981 - loss: 0.1585 - mae: 0.3031 - rmse: 0.3890 - smape: 0.6547 - val_ia: 0.2704 - val_loss: 0.4887 - val_mae: 0.5326 - val_rmse: 0.5804 - val_smape: 0.9571

Epoch 25/256

2292/2292 - 10s - 4ms/step - ia: 0.8011 - loss: 0.1550 - mae: 0.2994 - rmse: 0.3849 - smape: 0.6504 - val_ia: 0.2657 - val_loss: 0.5097 - val_mae: 0.5497 - val_rmse: 0.5937 - val_smape: 0.9763

Epoch 26/256

2292/2292 - 7s - 3ms/step - ia: 0.8025 - loss: 0.1518 - mae: 0.2963 - rmse: 0.3812 - smape: 0.6467 - val_ia: 0.2684 - val_loss: 0.4958 - val_mae: 0.5418 - val_rmse: 0.5868 - val_smape: 0.9684

Epoch 27/256

2292/2292 - 7s - 3ms/step - ia: 0.8042 - loss: 0.1490 - mae: 0.2934 - rmse: 0.3774 - smape: 0.6453 - val_ia: 0.2840 - val_loss: 0.4182 - val_mae: 0.4938 - val_rmse: 0.5412 - val_smape: 0.9188

Epoch 28/256

2292/2292 - 7s - 3ms/step - ia: 0.8069 - loss: 0.1458 - mae: 0.2898 - rmse: 0.3729 - smape: 0.6392 - val_ia: 0.2925 - val_loss: 0.3828 - val_mae: 0.4689 - val_rmse: 0.5174 - val_smape: 0.8999

Epoch 29/256

2292/2292 - 7s - 3ms/step - ia: 0.8098 - loss: 0.1424 - mae: 0.2864 - rmse: 0.3685 - smape: 0.6368 - val_ia: 0.2958 - val_loss: 0.3616 - val_mae: 0.4563 - val_rmse: 0.5045 - val_smape: 0.8962

Epoch 30/256

2292/2292 - 8s - 3ms/step - ia: 0.8115 - loss: 0.1392 - mae: 0.2828 - rmse: 0.3645 - smape: 0.6322 - val_ia: 0.2858 - val_loss: 0.4129 - val_mae: 0.4895 - val_rmse: 0.5351 - val_smape: 0.9106

Epoch 31/256

2292/2292 - 13s - 6ms/step - ia: 0.8141 - loss: 0.1360 - mae: 0.2791 - rmse: 0.3606 - smape: 0.6272 - val_ia: 0.2905 - val_loss: 0.3845 - val_mae: 0.4738 - val_rmse: 0.5192 - val_smape: 0.8929

Epoch 32/256

2292/2292 - 10s - 4ms/step - ia: 0.8176 - loss: 0.1329 - mae: 0.2753 - rmse: 0.3560 - smape: 0.6218 - val_ia: 0.2870 - val_loss: 0.4029 - val_mae: 0.4871 - val_rmse: 0.5311 - val_smape: 0.9113

Epoch 33/256

2292/2292 - 10s - 5ms/step - ia: 0.8191 - loss: 0.1302 - mae: 0.2725 - rmse: 0.3524 - smape: 0.6180 - val_ia: 0.3046 - val_loss: 0.3396 - val_mae: 0.4411 - val_rmse: 0.4866 - val_smape: 0.8622

Epoch 34/256

2292/2292 - 11s - 5ms/step - ia: 0.8210 - loss: 0.1274 - mae: 0.2693 - rmse: 0.3488 - smape: 0.6130 - val_ia: 0.2842 - val_loss: 0.3876 - val_mae: 0.4807 - val_rmse: 0.5245 - val_smape: 0.9090

Epoch 35/256

2292/2292 - 10s - 4ms/step - ia: 0.8233 - loss: 0.1246 - mae: 0.2656 - rmse: 0.3443 - smape: 0.6086 - val_ia: 0.2940 - val_loss: 0.3559 - val_mae: 0.4578 - val_rmse: 0.5017 - val_smape: 0.8775

Epoch 36/256

2292/2292 - 12s - 5ms/step - ia: 0.8250 - loss: 0.1221 - mae: 0.2635 - rmse: 0.3406 - smape: 0.6040 - val_ia: 0.2959 - val_loss: 0.3430 - val_mae: 0.4501 - val_rmse: 0.4935 - val_smape: 0.8704

Epoch 37/256

2292/2292 - 11s - 5ms/step - ia: 0.8271 - loss: 0.1196 - mae: 0.2603 - rmse: 0.3376 - smape: 0.6000 - val_ia: 0.3012 - val_loss: 0.3420 - val_mae: 0.4409 - val_rmse: 0.4868 - val_smape: 0.8556

Epoch 38/256

2292/2292 - 11s - 5ms/step - ia: 0.8299 - loss: 0.1171 - mae: 0.2575 - rmse: 0.3338 - smape: 0.5956 - val_ia: 0.3123 - val_loss: 0.2964 - val_mae: 0.4144 - val_rmse: 0.4584 - val_smape: 0.8235

Epoch 39/256

2292/2292 - 19s - 8ms/step - ia: 0.8309 - loss: 0.1149 - mae: 0.2549 - rmse: 0.3305 - smape: 0.5895 - val_ia: 0.3143 - val_loss: 0.2922 - val_mae: 0.4086 - val_rmse: 0.4527 - val_smape: 0.8184

Epoch 40/256

2292/2292 - 7s - 3ms/step - ia: 0.8329 - loss: 0.1125 - mae: 0.2517 - rmse: 0.3268 - smape: 0.5856 - val_ia: 0.3062 - val_loss: 0.3042 - val_mae: 0.4219 - val_rmse: 0.4640 - val_smape: 0.8383

Epoch 41/256

2292/2292 - 7s - 3ms/step - ia: 0.8349 - loss: 0.1103 - mae: 0.2494 - rmse: 0.3240 - smape: 0.5818 - val_ia: 0.3116 - val_loss: 0.2915 - val_mae: 0.4108 - val_rmse: 0.4535 - val_smape: 0.8164

Epoch 42/256

2292/2292 - 10s - 5ms/step - ia: 0.8362 - loss: 0.1082 - mae: 0.2471 - rmse: 0.3209 - smape: 0.5770 - val_ia: 0.3359 - val_loss: 0.2517 - val_mae: 0.3729 - val_rmse: 0.4173 - val_smape: 0.7593

Epoch 43/256

2292/2292 - 10s - 4ms/step - ia: 0.8372 - loss: 0.1065 - mae: 0.2447 - rmse: 0.3181 - smape: 0.5733 - val_ia: 0.3389 - val_loss: 0.2401 - val_mae: 0.3654 - val_rmse: 0.4103 - val_smape: 0.7462

Epoch 44/256

2292/2292 - 11s - 5ms/step - ia: 0.8391 - loss: 0.1046 - mae: 0.2425 - rmse: 0.3149 - smape: 0.5692 - val_ia: 0.3208 - val_loss: 0.2660 - val_mae: 0.3916 - val_rmse: 0.4345 - val_smape: 0.7881

Epoch 45/256

2292/2292 - 11s - 5ms/step - ia: 0.8412 - loss: 0.1026 - mae: 0.2398 - rmse: 0.3122 - smape: 0.5639 - val_ia: 0.3327 - val_loss: 0.2423 - val_mae: 0.3719 - val_rmse: 0.4150 - val_smape: 0.7604

Epoch 46/256

2292/2292 - 20s - 9ms/step - ia: 0.8429 - loss: 0.1011 - mae: 0.2377 - rmse: 0.3096 - smape: 0.5612 - val_ia: 0.3279 - val_loss: 0.2575 - val_mae: 0.3833 - val_rmse: 0.4256 - val_smape: 0.7799

Epoch 47/256

2292/2292 - 11s - 5ms/step - ia: 0.8437 - loss: 0.0996 - mae: 0.2360 - rmse: 0.3070 - smape: 0.5574 - val_ia: 0.3211 - val_loss: 0.2518 - val_mae: 0.3873 - val_rmse: 0.4280 - val_smape: 0.7875

Epoch 48/256

2292/2292 - 20s - 9ms/step - ia: 0.8452 - loss: 0.0980 - mae: 0.2339 - rmse: 0.3045 - smape: 0.5530 - val_ia: 0.3400 - val_loss: 0.2373 - val_mae: 0.3647 - val_rmse: 0.4070 - val_smape: 0.7440

Epoch 49/256

2292/2292 - 11s - 5ms/step - ia: 0.8461 - loss: 0.0966 - mae: 0.2320 - rmse: 0.3026 - smape: 0.5502 - val_ia: 0.3450 - val_loss: 0.2124 - val_mae: 0.3484 - val_rmse: 0.3914 - val_smape: 0.7204

Epoch 50/256

2292/2292 - 10s - 4ms/step - ia: 0.8479 - loss: 0.0951 - mae: 0.2298 - rmse: 0.3002 - smape: 0.5461 - val_ia: 0.3300 - val_loss: 0.2317 - val_mae: 0.3712 - val_rmse: 0.4120 - val_smape: 0.7659

Epoch 51/256

2292/2292 - 9s - 4ms/step - ia: 0.8489 - loss: 0.0937 - mae: 0.2282 - rmse: 0.2978 - smape: 0.5440 - val_ia: 0.3488 - val_loss: 0.2232 - val_mae: 0.3551 - val_rmse: 0.3965 - val_smape: 0.7210

Epoch 52/256

2292/2292 - 11s - 5ms/step - ia: 0.8503 - loss: 0.0925 - mae: 0.2267 - rmse: 0.2961 - smape: 0.5410 - val_ia: 0.3391 - val_loss: 0.2281 - val_mae: 0.3644 - val_rmse: 0.4050 - val_smape: 0.7438

Epoch 53/256

2292/2292 - 11s - 5ms/step - ia: 0.8517 - loss: 0.0909 - mae: 0.2246 - rmse: 0.2931 - smape: 0.5359 - val_ia: 0.3407 - val_loss: 0.2257 - val_mae: 0.3637 - val_rmse: 0.4037 - val_smape: 0.7414

Epoch 54/256

2292/2292 - 21s - 9ms/step - ia: 0.8529 - loss: 0.0901 - mae: 0.2231 - rmse: 0.2919 - smape: 0.5364 - val_ia: 0.3510 - val_loss: 0.2106 - val_mae: 0.3488 - val_rmse: 0.3902 - val_smape: 0.7191

Epoch 55/256

2292/2292 - 19s - 8ms/step - ia: 0.8536 - loss: 0.0886 - mae: 0.2214 - rmse: 0.2893 - smape: 0.5316 - val_ia: 0.3489 - val_loss: 0.2135 - val_mae: 0.3533 - val_rmse: 0.3943 - val_smape: 0.7228

Epoch 56/256

2292/2292 - 8s - 3ms/step - ia: 0.8554 - loss: 0.0875 - mae: 0.2197 - rmse: 0.2877 - smape: 0.5282 - val_ia: 0.3598 - val_loss: 0.2050 - val_mae: 0.3427 - val_rmse: 0.3836 - val_smape: 0.6979

Epoch 57/256

2292/2292 - 11s - 5ms/step - ia: 0.8556 - loss: 0.0864 - mae: 0.2187 - rmse: 0.2859 - smape: 0.5266 - val_ia: 0.3648 - val_loss: 0.1950 - val_mae: 0.3337 - val_rmse: 0.3752 - val_smape: 0.6810

Epoch 58/256

2292/2292 - 10s - 4ms/step - ia: 0.8568 - loss: 0.0852 - mae: 0.2171 - rmse: 0.2839 - smape: 0.5243 - val_ia: 0.3520 - val_loss: 0.2203 - val_mae: 0.3579 - val_rmse: 0.3981 - val_smape: 0.7267

Epoch 59/256

2292/2292 - 11s - 5ms/step - ia: 0.8572 - loss: 0.0843 - mae: 0.2156 - rmse: 0.2820 - smape: 0.5205 - val_ia: 0.3719 - val_loss: 0.1825 - val_mae: 0.3201 - val_rmse: 0.3623 - val_smape: 0.6438

Epoch 60/256

2292/2292 - 21s - 9ms/step - ia: 0.8586 - loss: 0.0832 - mae: 0.2145 - rmse: 0.2805 - smape: 0.5198 - val_ia: 0.3589 - val_loss: 0.2160 - val_mae: 0.3529 - val_rmse: 0.3938 - val_smape: 0.7146

Epoch 61/256

2292/2292 - 20s - 9ms/step - ia: 0.8596 - loss: 0.0824 - mae: 0.2130 - rmse: 0.2793 - smape: 0.5151 - val_ia: 0.3607 - val_loss: 0.2045 - val_mae: 0.3453 - val_rmse: 0.3863 - val_smape: 0.7068

Epoch 62/256

2292/2292 - 8s - 3ms/step - ia: 0.8606 - loss: 0.0815 - mae: 0.2118 - rmse: 0.2774 - smape: 0.5129 - val_ia: 0.3423 - val_loss: 0.2405 - val_mae: 0.3793 - val_rmse: 0.4190 - val_smape: 0.7647

Epoch 63/256

2292/2292 - 10s - 4ms/step - ia: 0.8615 - loss: 0.0803 - mae: 0.2105 - rmse: 0.2754 - smape: 0.5111 - val_ia: 0.3589 - val_loss: 0.2160 - val_mae: 0.3535 - val_rmse: 0.3947 - val_smape: 0.7150

Epoch 64/256

2292/2292 - 8s - 4ms/step - ia: 0.8625 - loss: 0.0795 - mae: 0.2091 - rmse: 0.2739 - smape: 0.5084 - val_ia: 0.3669 - val_loss: 0.2030 - val_mae: 0.3401 - val_rmse: 0.3809 - val_smape: 0.6830

Epoch 65/256

2292/2292 - 12s - 5ms/step - ia: 0.8633 - loss: 0.0785 - mae: 0.2077 - rmse: 0.2726 - smape: 0.5061 - val_ia: 0.3519 - val_loss: 0.2221 - val_mae: 0.3629 - val_rmse: 0.4039 - val_smape: 0.7337

Epoch 66/256

2292/2292 - 11s - 5ms/step - ia: 0.8642 - loss: 0.0778 - mae: 0.2068 - rmse: 0.2712 - smape: 0.5042 - val_ia: 0.3557 - val_loss: 0.2289 - val_mae: 0.3651 - val_rmse: 0.4061 - val_smape: 0.7324

Epoch 67/256

2292/2292 - 8s - 4ms/step - ia: 0.8646 - loss: 0.0769 - mae: 0.2056 - rmse: 0.2692 - smape: 0.5024 - val_ia: 0.3594 - val_loss: 0.2214 - val_mae: 0.3585 - val_rmse: 0.3993 - val_smape: 0.7232

Epoch 68/256

2292/2292 - 7s - 3ms/step - ia: 0.8658 - loss: 0.0758 - mae: 0.2042 - rmse: 0.2678 - smape: 0.5001 - val_ia: 0.3681 - val_loss: 0.1885 - val_mae: 0.3284 - val_rmse: 0.3695 - val_smape: 0.6624

Epoch 69/256

2292/2292 - 10s - 4ms/step - ia: 0.8663 - loss: 0.0753 - mae: 0.2035 - rmse: 0.2666 - smape: 0.4978 - val_ia: 0.3617 - val_loss: 0.2139 - val_mae: 0.3530 - val_rmse: 0.3933 - val_smape: 0.7096

Epoch 70/256

2292/2292 - 6s - 3ms/step - ia: 0.8667 - loss: 0.0750 - mae: 0.2029 - rmse: 0.2660 - smape: 0.4971 - val_ia: 0.3640 - val_loss: 0.2031 - val_mae: 0.3436 - val_rmse: 0.3851 - val_smape: 0.7008

Epoch 71/256

2292/2292 - 7s - 3ms/step - ia: 0.8673 - loss: 0.0743 - mae: 0.2021 - rmse: 0.2649 - smape: 0.4955 - val_ia: 0.3545 - val_loss: 0.2534 - val_mae: 0.3827 - val_rmse: 0.4234 - val_smape: 0.7563

Epoch 72/256

2292/2292 - 14s - 6ms/step - ia: 0.8678 - loss: 0.0736 - mae: 0.2011 - rmse: 0.2634 - smape: 0.4940 - val_ia: 0.3585 - val_loss: 0.1983 - val_mae: 0.3417 - val_rmse: 0.3830 - val_smape: 0.6979

Epoch 73/256

2292/2292 - 20s - 9ms/step - ia: 0.8687 - loss: 0.0727 - mae: 0.1996 - rmse: 0.2620 - smape: 0.4918 - val_ia: 0.3614 - val_loss: 0.1959 - val_mae: 0.3373 - val_rmse: 0.3781 - val_smape: 0.6895

Epoch 74/256

2292/2292 - 10s - 4ms/step - ia: 0.8689 - loss: 0.0722 - mae: 0.1989 - rmse: 0.2609 - smape: 0.4898 - val_ia: 0.3635 - val_loss: 0.1976 - val_mae: 0.3367 - val_rmse: 0.3782 - val_smape: 0.6828

Epoch 74: early stopping

Restoring model weights from the end of the best epoch: 59.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:40 988ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 62%|██████▏   | 31/50 [2:48:32<3:47:41, 719.03s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 13s - 6ms/step - ia: 0.5212 - loss: 0.6594 - mae: 0.6476 - rmse: 0.7929 - smape: 1.0866 - val_ia: 0.1769 - val_loss: 1.1408 - val_mae: 0.8830 - val_rmse: 0.9221 - val_smape: 1.3205

Epoch 2/128

2292/2292 - 6s - 3ms/step - ia: 0.6124 - loss: 0.4632 - mae: 0.5387 - rmse: 0.6699 - smape: 0.9342 - val_ia: 0.1777 - val_loss: 1.1761 - val_mae: 0.8846 - val_rmse: 0.9237 - val_smape: 1.3398

Epoch 3/128

2292/2292 - 8s - 3ms/step - ia: 0.6407 - loss: 0.4118 - mae: 0.5043 - rmse: 0.6308 - smape: 0.8970 - val_ia: 0.1813 - val_loss: 1.1628 - val_mae: 0.8661 - val_rmse: 0.9053 - val_smape: 1.3299

Epoch 4/128

2292/2292 - 12s - 5ms/step - ia: 0.6594 - loss: 0.3764 - mae: 0.4806 - rmse: 0.6030 - smape: 0.8759 - val_ia: 0.1887 - val_loss: 1.1892 - val_mae: 0.8650 - val_rmse: 0.9031 - val_smape: 1.3396

Epoch 5/128

2292/2292 - 16s - 7ms/step - ia: 0.6739 - loss: 0.3458 - mae: 0.4602 - rmse: 0.5778 - smape: 0.8578 - val_ia: 0.2072 - val_loss: 1.1495 - val_mae: 0.8342 - val_rmse: 0.8731 - val_smape: 1.3263

Epoch 6/128

2292/2292 - 10s - 4ms/step - ia: 0.6851 - loss: 0.3259 - mae: 0.4459 - rmse: 0.5604 - smape: 0.8484 - val_ia: 0.2120 - val_loss: 1.1750 - val_mae: 0.8373 - val_rmse: 0.8767 - val_smape: 1.3410

Epoch 7/128

2292/2292 - 6s - 3ms/step - ia: 0.6956 - loss: 0.3098 - mae: 0.4342 - rmse: 0.5453 - smape: 0.8375 - val_ia: 0.2170 - val_loss: 1.1286 - val_mae: 0.8144 - val_rmse: 0.8556 - val_smape: 1.3522

Epoch 8/128

2292/2292 - 6s - 3ms/step - ia: 0.7065 - loss: 0.2924 - mae: 0.4200 - rmse: 0.5303 - smape: 0.8312 - val_ia: 0.2168 - val_loss: 1.1345 - val_mae: 0.8123 - val_rmse: 0.8549 - val_smape: 1.3648

Epoch 9/128

2292/2292 - 12s - 5ms/step - ia: 0.7141 - loss: 0.2802 - mae: 0.4109 - rmse: 0.5190 - smape: 0.8245 - val_ia: 0.2197 - val_loss: 1.0665 - val_mae: 0.7864 - val_rmse: 0.8296 - val_smape: 1.3543

Epoch 10/128

2292/2292 - 12s - 5ms/step - ia: 0.7187 - loss: 0.2722 - mae: 0.4049 - rmse: 0.5112 - smape: 0.8249 - val_ia: 0.2197 - val_loss: 1.1130 - val_mae: 0.7999 - val_rmse: 0.8443 - val_smape: 1.3611

Epoch 11/128

2292/2292 - 10s - 4ms/step - ia: 0.7234 - loss: 0.2650 - mae: 0.3990 - rmse: 0.5043 - smape: 0.8209 - val_ia: 0.2232 - val_loss: 1.0013 - val_mae: 0.7635 - val_rmse: 0.8080 - val_smape: 1.3573

Epoch 12/128

2292/2292 - 9s - 4ms/step - ia: 0.7286 - loss: 0.2571 - mae: 0.3913 - rmse: 0.4963 - smape: 0.8097 - val_ia: 0.2250 - val_loss: 0.9913 - val_mae: 0.7581 - val_rmse: 0.8039 - val_smape: 1.3611

Epoch 13/128

2292/2292 - 9s - 4ms/step - ia: 0.7329 - loss: 0.2494 - mae: 0.3859 - rmse: 0.4891 - smape: 0.8076 - val_ia: 0.2278 - val_loss: 0.9219 - val_mae: 0.7348 - val_rmse: 0.7791 - val_smape: 1.3419

Epoch 14/128

2292/2292 - 9s - 4ms/step - ia: 0.7364 - loss: 0.2439 - mae: 0.3809 - rmse: 0.4835 - smape: 0.8045 - val_ia: 0.2288 - val_loss: 0.8795 - val_mae: 0.7204 - val_rmse: 0.7653 - val_smape: 1.3515

Epoch 15/128

2292/2292 - 8s - 4ms/step - ia: 0.7420 - loss: 0.2357 - mae: 0.3742 - rmse: 0.4751 - smape: 0.7974 - val_ia: 0.2294 - val_loss: 0.8505 - val_mae: 0.7120 - val_rmse: 0.7565 - val_smape: 1.3417

Epoch 16/128

2292/2292 - 9s - 4ms/step - ia: 0.7433 - loss: 0.2324 - mae: 0.3716 - rmse: 0.4719 - smape: 0.7946 - val_ia: 0.2328 - val_loss: 0.7853 - val_mae: 0.6882 - val_rmse: 0.7320 - val_smape: 1.3310

Epoch 17/128

2292/2292 - 10s - 4ms/step - ia: 0.7462 - loss: 0.2290 - mae: 0.3682 - rmse: 0.4682 - smape: 0.7905 - val_ia: 0.2323 - val_loss: 0.7490 - val_mae: 0.6783 - val_rmse: 0.7221 - val_smape: 1.3362

Epoch 18/128

2292/2292 - 10s - 4ms/step - ia: 0.7507 - loss: 0.2227 - mae: 0.3631 - rmse: 0.4616 - smape: 0.7858 - val_ia: 0.2346 - val_loss: 0.6920 - val_mae: 0.6578 - val_rmse: 0.6994 - val_smape: 1.3453

Epoch 19/128

2292/2292 - 9s - 4ms/step - ia: 0.7522 - loss: 0.2178 - mae: 0.3603 - rmse: 0.4571 - smape: 0.7824 - val_ia: 0.2382 - val_loss: 0.6577 - val_mae: 0.6437 - val_rmse: 0.6837 - val_smape: 1.3387

Epoch 20/128

2292/2292 - 10s - 4ms/step - ia: 0.7539 - loss: 0.2149 - mae: 0.3570 - rmse: 0.4534 - smape: 0.7790 - val_ia: 0.2393 - val_loss: 0.6447 - val_mae: 0.6383 - val_rmse: 0.6780 - val_smape: 1.3201

Epoch 21/128

2292/2292 - 9s - 4ms/step - ia: 0.7564 - loss: 0.2117 - mae: 0.3543 - rmse: 0.4505 - smape: 0.7742 - val_ia: 0.2394 - val_loss: 0.6203 - val_mae: 0.6284 - val_rmse: 0.6689 - val_smape: 1.3333

Epoch 22/128

2292/2292 - 9s - 4ms/step - ia: 0.7584 - loss: 0.2096 - mae: 0.3521 - rmse: 0.4478 - smape: 0.7701 - val_ia: 0.2410 - val_loss: 0.6187 - val_mae: 0.6269 - val_rmse: 0.6668 - val_smape: 1.3045

Epoch 23/128

2292/2292 - 9s - 4ms/step - ia: 0.7596 - loss: 0.2086 - mae: 0.3515 - rmse: 0.4467 - smape: 0.7680 - val_ia: 0.2434 - val_loss: 0.5940 - val_mae: 0.6161 - val_rmse: 0.6548 - val_smape: 1.3093

Epoch 24/128

2292/2292 - 10s - 4ms/step - ia: 0.7626 - loss: 0.2036 - mae: 0.3463 - rmse: 0.4408 - smape: 0.7627 - val_ia: 0.2423 - val_loss: 0.5994 - val_mae: 0.6192 - val_rmse: 0.6585 - val_smape: 1.3167

Epoch 25/128

2292/2292 - 10s - 5ms/step - ia: 0.7633 - loss: 0.2020 - mae: 0.3452 - rmse: 0.4395 - smape: 0.7612 - val_ia: 0.2455 - val_loss: 0.5719 - val_mae: 0.6059 - val_rmse: 0.6450 - val_smape: 1.3075

Epoch 26/128

2292/2292 - 6s - 3ms/step - ia: 0.7644 - loss: 0.2003 - mae: 0.3437 - rmse: 0.4378 - smape: 0.7606 - val_ia: 0.2421 - val_loss: 0.5949 - val_mae: 0.6189 - val_rmse: 0.6575 - val_smape: 1.3131

Epoch 27/128

2292/2292 - 5s - 2ms/step - ia: 0.7661 - loss: 0.1976 - mae: 0.3412 - rmse: 0.4350 - smape: 0.7552 - val_ia: 0.2469 - val_loss: 0.5532 - val_mae: 0.5981 - val_rmse: 0.6363 - val_smape: 1.2982

Epoch 28/128

2292/2292 - 6s - 3ms/step - ia: 0.7673 - loss: 0.1964 - mae: 0.3402 - rmse: 0.4334 - smape: 0.7550 - val_ia: 0.2489 - val_loss: 0.5457 - val_mae: 0.5934 - val_rmse: 0.6314 - val_smape: 1.3004

Epoch 29/128

2292/2292 - 6s - 2ms/step - ia: 0.7681 - loss: 0.1970 - mae: 0.3401 - rmse: 0.4337 - smape: 0.7535 - val_ia: 0.2478 - val_loss: 0.5576 - val_mae: 0.5993 - val_rmse: 0.6369 - val_smape: 1.2893

Epoch 30/128

2292/2292 - 11s - 5ms/step - ia: 0.7680 - loss: 0.1960 - mae: 0.3392 - rmse: 0.4325 - smape: 0.7504 - val_ia: 0.2509 - val_loss: 0.5411 - val_mae: 0.5908 - val_rmse: 0.6290 - val_smape: 1.2851

Epoch 31/128

2292/2292 - 7s - 3ms/step - ia: 0.7693 - loss: 0.1931 - mae: 0.3371 - rmse: 0.4295 - smape: 0.7515 - val_ia: 0.2530 - val_loss: 0.5268 - val_mae: 0.5826 - val_rmse: 0.6206 - val_smape: 1.2807

Epoch 32/128

2292/2292 - 13s - 6ms/step - ia: 0.7711 - loss: 0.1896 - mae: 0.3350 - rmse: 0.4263 - smape: 0.7478 - val_ia: 0.2531 - val_loss: 0.5220 - val_mae: 0.5810 - val_rmse: 0.6184 - val_smape: 1.2762

Epoch 33/128

2292/2292 - 9s - 4ms/step - ia: 0.7703 - loss: 0.1903 - mae: 0.3355 - rmse: 0.4264 - smape: 0.7473 - val_ia: 0.2541 - val_loss: 0.5178 - val_mae: 0.5780 - val_rmse: 0.6155 - val_smape: 1.2700

Epoch 34/128

2292/2292 - 11s - 5ms/step - ia: 0.7731 - loss: 0.1874 - mae: 0.3322 - rmse: 0.4236 - smape: 0.7429 - val_ia: 0.2582 - val_loss: 0.5113 - val_mae: 0.5735 - val_rmse: 0.6111 - val_smape: 1.2536

Epoch 35/128

2292/2292 - 9s - 4ms/step - ia: 0.7730 - loss: 0.1878 - mae: 0.3321 - rmse: 0.4240 - smape: 0.7419 - val_ia: 0.2540 - val_loss: 0.5041 - val_mae: 0.5719 - val_rmse: 0.6092 - val_smape: 1.2601

Epoch 36/128

2292/2292 - 10s - 4ms/step - ia: 0.7745 - loss: 0.1859 - mae: 0.3303 - rmse: 0.4215 - smape: 0.7401 - val_ia: 0.2535 - val_loss: 0.5243 - val_mae: 0.5813 - val_rmse: 0.6211 - val_smape: 1.2542

Epoch 37/128

2292/2292 - 11s - 5ms/step - ia: 0.7747 - loss: 0.1866 - mae: 0.3308 - rmse: 0.4221 - smape: 0.7405 - val_ia: 0.2590 - val_loss: 0.4992 - val_mae: 0.5662 - val_rmse: 0.6040 - val_smape: 1.2515

Epoch 38/128

2292/2292 - 12s - 5ms/step - ia: 0.7748 - loss: 0.1853 - mae: 0.3302 - rmse: 0.4206 - smape: 0.7398 - val_ia: 0.2583 - val_loss: 0.4909 - val_mae: 0.5633 - val_rmse: 0.6012 - val_smape: 1.2465

Epoch 39/128

2292/2292 - 18s - 8ms/step - ia: 0.7747 - loss: 0.1858 - mae: 0.3305 - rmse: 0.4216 - smape: 0.7373 - val_ia: 0.2591 - val_loss: 0.4886 - val_mae: 0.5618 - val_rmse: 0.6001 - val_smape: 1.2398

Epoch 40/128

2292/2292 - 9s - 4ms/step - ia: 0.7768 - loss: 0.1807 - mae: 0.3269 - rmse: 0.4159 - smape: 0.7368 - val_ia: 0.2612 - val_loss: 0.4758 - val_mae: 0.5539 - val_rmse: 0.5921 - val_smape: 1.2222

Epoch 41/128

2292/2292 - 10s - 4ms/step - ia: 0.7768 - loss: 0.1819 - mae: 0.3279 - rmse: 0.4166 - smape: 0.7364 - val_ia: 0.2583 - val_loss: 0.4900 - val_mae: 0.5631 - val_rmse: 0.6008 - val_smape: 1.2393

Epoch 42/128

2292/2292 - 12s - 5ms/step - ia: 0.7774 - loss: 0.1797 - mae: 0.3257 - rmse: 0.4149 - smape: 0.7333 - val_ia: 0.2610 - val_loss: 0.4816 - val_mae: 0.5580 - val_rmse: 0.5961 - val_smape: 1.2262

Epoch 43/128

2292/2292 - 10s - 4ms/step - ia: 0.7796 - loss: 0.1777 - mae: 0.3228 - rmse: 0.4121 - smape: 0.7286 - val_ia: 0.2624 - val_loss: 0.4675 - val_mae: 0.5498 - val_rmse: 0.5873 - val_smape: 1.2139

Epoch 44/128

2292/2292 - 10s - 4ms/step - ia: 0.7780 - loss: 0.1797 - mae: 0.3251 - rmse: 0.4143 - smape: 0.7312 - val_ia: 0.2590 - val_loss: 0.4783 - val_mae: 0.5565 - val_rmse: 0.5950 - val_smape: 1.2149

Epoch 45/128

2292/2292 - 10s - 5ms/step - ia: 0.7796 - loss: 0.1774 - mae: 0.3229 - rmse: 0.4117 - smape: 0.7280 - val_ia: 0.2645 - val_loss: 0.4686 - val_mae: 0.5492 - val_rmse: 0.5871 - val_smape: 1.1983

Epoch 46/128

2292/2292 - 9s - 4ms/step - ia: 0.7821 - loss: 0.1737 - mae: 0.3199 - rmse: 0.4076 - smape: 0.7241 - val_ia: 0.2654 - val_loss: 0.4451 - val_mae: 0.5365 - val_rmse: 0.5747 - val_smape: 1.1949

Epoch 47/128

2292/2292 - 11s - 5ms/step - ia: 0.7802 - loss: 0.1769 - mae: 0.3229 - rmse: 0.4107 - smape: 0.7277 - val_ia: 0.2637 - val_loss: 0.4606 - val_mae: 0.5455 - val_rmse: 0.5831 - val_smape: 1.1983

Epoch 48/128

2292/2292 - 22s - 10ms/step - ia: 0.7801 - loss: 0.1765 - mae: 0.3229 - rmse: 0.4109 - smape: 0.7263 - val_ia: 0.2617 - val_loss: 0.4585 - val_mae: 0.5438 - val_rmse: 0.5825 - val_smape: 1.1864

Epoch 49/128

2292/2292 - 10s - 5ms/step - ia: 0.7826 - loss: 0.1730 - mae: 0.3192 - rmse: 0.4068 - smape: 0.7194 - val_ia: 0.2595 - val_loss: 0.4518 - val_mae: 0.5406 - val_rmse: 0.5798 - val_smape: 1.1872

Epoch 50/128

2292/2292 - 9s - 4ms/step - ia: 0.7826 - loss: 0.1733 - mae: 0.3195 - rmse: 0.4070 - smape: 0.7232 - val_ia: 0.2635 - val_loss: 0.4371 - val_mae: 0.5321 - val_rmse: 0.5702 - val_smape: 1.1763

Epoch 51/128

2292/2292 - 13s - 6ms/step - ia: 0.7818 - loss: 0.1735 - mae: 0.3205 - rmse: 0.4076 - smape: 0.7224 - val_ia: 0.2627 - val_loss: 0.4439 - val_mae: 0.5352 - val_rmse: 0.5746 - val_smape: 1.1765

Epoch 52/128

2292/2292 - 8s - 4ms/step - ia: 0.7821 - loss: 0.1749 - mae: 0.3204 - rmse: 0.4089 - smape: 0.7220 - val_ia: 0.2664 - val_loss: 0.4251 - val_mae: 0.5226 - val_rmse: 0.5618 - val_smape: 1.1627

Epoch 53/128

2292/2292 - 11s - 5ms/step - ia: 0.7819 - loss: 0.1737 - mae: 0.3200 - rmse: 0.4077 - smape: 0.7216 - val_ia: 0.2676 - val_loss: 0.4215 - val_mae: 0.5212 - val_rmse: 0.5601 - val_smape: 1.1549

Epoch 54/128

2292/2292 - 19s - 8ms/step - ia: 0.7842 - loss: 0.1724 - mae: 0.3176 - rmse: 0.4051 - smape: 0.7198 - val_ia: 0.2644 - val_loss: 0.4295 - val_mae: 0.5271 - val_rmse: 0.5649 - val_smape: 1.1715

Epoch 55/128

2292/2292 - 9s - 4ms/step - ia: 0.7838 - loss: 0.1711 - mae: 0.3177 - rmse: 0.4042 - smape: 0.7220 - val_ia: 0.2619 - val_loss: 0.4335 - val_mae: 0.5304 - val_rmse: 0.5688 - val_smape: 1.1773

Epoch 56/128

2292/2292 - 11s - 5ms/step - ia: 0.7849 - loss: 0.1705 - mae: 0.3168 - rmse: 0.4033 - smape: 0.7193 - val_ia: 0.2642 - val_loss: 0.4276 - val_mae: 0.5268 - val_rmse: 0.5648 - val_smape: 1.1721

Epoch 57/128

2292/2292 - 8s - 4ms/step - ia: 0.7851 - loss: 0.1701 - mae: 0.3163 - rmse: 0.4031 - smape: 0.7174 - val_ia: 0.2662 - val_loss: 0.4241 - val_mae: 0.5243 - val_rmse: 0.5616 - val_smape: 1.1442

Epoch 58/128

2292/2292 - 9s - 4ms/step - ia: 0.7864 - loss: 0.1678 - mae: 0.3154 - rmse: 0.4009 - smape: 0.7158 - val_ia: 0.2631 - val_loss: 0.4232 - val_mae: 0.5243 - val_rmse: 0.5629 - val_smape: 1.1479

Epoch 59/128

2292/2292 - 9s - 4ms/step - ia: 0.7856 - loss: 0.1690 - mae: 0.3155 - rmse: 0.4019 - smape: 0.7132 - val_ia: 0.2654 - val_loss: 0.4076 - val_mae: 0.5145 - val_rmse: 0.5518 - val_smape: 1.1476

Epoch 60/128

2292/2292 - 6s - 3ms/step - ia: 0.7861 - loss: 0.1679 - mae: 0.3152 - rmse: 0.4008 - smape: 0.7155 - val_ia: 0.2698 - val_loss: 0.4021 - val_mae: 0.5100 - val_rmse: 0.5483 - val_smape: 1.1344

Epoch 61/128

2292/2292 - 9s - 4ms/step - ia: 0.7863 - loss: 0.1678 - mae: 0.3145 - rmse: 0.4003 - smape: 0.7147 - val_ia: 0.2672 - val_loss: 0.4122 - val_mae: 0.5171 - val_rmse: 0.5547 - val_smape: 1.1470

Epoch 62/128

2292/2292 - 11s - 5ms/step - ia: 0.7863 - loss: 0.1679 - mae: 0.3141 - rmse: 0.4004 - smape: 0.7142 - val_ia: 0.2720 - val_loss: 0.4005 - val_mae: 0.5082 - val_rmse: 0.5454 - val_smape: 1.1294

Epoch 63/128

2292/2292 - 12s - 5ms/step - ia: 0.7865 - loss: 0.1674 - mae: 0.3138 - rmse: 0.4004 - smape: 0.7127 - val_ia: 0.2737 - val_loss: 0.3838 - val_mae: 0.4981 - val_rmse: 0.5353 - val_smape: 1.1146

Epoch 64/128

2292/2292 - 8s - 4ms/step - ia: 0.7866 - loss: 0.1672 - mae: 0.3131 - rmse: 0.3997 - smape: 0.7114 - val_ia: 0.2734 - val_loss: 0.4047 - val_mae: 0.5114 - val_rmse: 0.5478 - val_smape: 1.1250

Epoch 65/128

2292/2292 - 9s - 4ms/step - ia: 0.7882 - loss: 0.1651 - mae: 0.3121 - rmse: 0.3970 - smape: 0.7097 - val_ia: 0.2699 - val_loss: 0.3960 - val_mae: 0.5076 - val_rmse: 0.5453 - val_smape: 1.1160

Epoch 66/128

2292/2292 - 9s - 4ms/step - ia: 0.7885 - loss: 0.1650 - mae: 0.3112 - rmse: 0.3967 - smape: 0.7085 - val_ia: 0.2735 - val_loss: 0.3921 - val_mae: 0.5042 - val_rmse: 0.5405 - val_smape: 1.1197

Epoch 67/128

2292/2292 - 10s - 4ms/step - ia: 0.7885 - loss: 0.1638 - mae: 0.3113 - rmse: 0.3954 - smape: 0.7059 - val_ia: 0.2763 - val_loss: 0.3807 - val_mae: 0.4960 - val_rmse: 0.5321 - val_smape: 1.1035

Epoch 68/128

2292/2292 - 8s - 4ms/step - ia: 0.7871 - loss: 0.1690 - mae: 0.3135 - rmse: 0.4016 - smape: 0.7081 - val_ia: 0.2705 - val_loss: 0.4065 - val_mae: 0.5149 - val_rmse: 0.5501 - val_smape: 1.1197

Epoch 69/128

2292/2292 - 7s - 3ms/step - ia: 0.7892 - loss: 0.1639 - mae: 0.3101 - rmse: 0.3954 - smape: 0.7016 - val_ia: 0.2685 - val_loss: 0.4026 - val_mae: 0.5121 - val_rmse: 0.5476 - val_smape: 1.1194

Epoch 70/128

2292/2292 - 17s - 7ms/step - ia: 0.7902 - loss: 0.1637 - mae: 0.3102 - rmse: 0.3953 - smape: 0.7007 - val_ia: 0.2719 - val_loss: 0.3883 - val_mae: 0.5028 - val_rmse: 0.5389 - val_smape: 1.1077

Epoch 71/128

2292/2292 - 19s - 8ms/step - ia: 0.7887 - loss: 0.1649 - mae: 0.3116 - rmse: 0.3969 - smape: 0.7055 - val_ia: 0.2702 - val_loss: 0.3857 - val_mae: 0.5019 - val_rmse: 0.5380 - val_smape: 1.0959

Epoch 72/128

2292/2292 - 16s - 7ms/step - ia: 0.7899 - loss: 0.1641 - mae: 0.3101 - rmse: 0.3958 - smape: 0.7041 - val_ia: 0.2686 - val_loss: 0.3943 - val_mae: 0.5077 - val_rmse: 0.5440 - val_smape: 1.1071

Epoch 73/128

2292/2292 - 9s - 4ms/step - ia: 0.7900 - loss: 0.1627 - mae: 0.3092 - rmse: 0.3943 - smape: 0.6987 - val_ia: 0.2693 - val_loss: 0.3833 - val_mae: 0.5008 - val_rmse: 0.5367 - val_smape: 1.0941

Epoch 74/128

2292/2292 - 13s - 6ms/step - ia: 0.7890 - loss: 0.1636 - mae: 0.3105 - rmse: 0.3952 - smape: 0.7013 - val_ia: 0.2719 - val_loss: 0.3783 - val_mae: 0.4971 - val_rmse: 0.5328 - val_smape: 1.0948

Epoch 75/128

2292/2292 - 11s - 5ms/step - ia: 0.7915 - loss: 0.1619 - mae: 0.3080 - rmse: 0.3933 - smape: 0.6988 - val_ia: 0.2745 - val_loss: 0.3722 - val_mae: 0.4941 - val_rmse: 0.5292 - val_smape: 1.0800

Epoch 76/128

2292/2292 - 10s - 4ms/step - ia: 0.7911 - loss: 0.1606 - mae: 0.3074 - rmse: 0.3919 - smape: 0.6953 - val_ia: 0.2694 - val_loss: 0.3744 - val_mae: 0.4973 - val_rmse: 0.5325 - val_smape: 1.0895

Epoch 77/128

2292/2292 - 12s - 5ms/step - ia: 0.7908 - loss: 0.1626 - mae: 0.3086 - rmse: 0.3943 - smape: 0.7008 - val_ia: 0.2728 - val_loss: 0.3638 - val_mae: 0.4897 - val_rmse: 0.5249 - val_smape: 1.0770

Epoch 78/128

2292/2292 - 21s - 9ms/step - ia: 0.7908 - loss: 0.1634 - mae: 0.3091 - rmse: 0.3943 - smape: 0.6990 - val_ia: 0.2701 - val_loss: 0.3784 - val_mae: 0.4991 - val_rmse: 0.5344 - val_smape: 1.0930

Epoch 79/128

2292/2292 - 13s - 5ms/step - ia: 0.7906 - loss: 0.1621 - mae: 0.3091 - rmse: 0.3932 - smape: 0.7019 - val_ia: 0.2703 - val_loss: 0.3712 - val_mae: 0.4946 - val_rmse: 0.5295 - val_smape: 1.0858

Epoch 80/128

2292/2292 - 9s - 4ms/step - ia: 0.7921 - loss: 0.1599 - mae: 0.3064 - rmse: 0.3906 - smape: 0.6970 - val_ia: 0.2713 - val_loss: 0.3668 - val_mae: 0.4906 - val_rmse: 0.5266 - val_smape: 1.0802

Epoch 81/128

2292/2292 - 9s - 4ms/step - ia: 0.7932 - loss: 0.1591 - mae: 0.3060 - rmse: 0.3899 - smape: 0.6945 - val_ia: 0.2743 - val_loss: 0.3564 - val_mae: 0.4846 - val_rmse: 0.5194 - val_smape: 1.0612

Epoch 82/128

2292/2292 - 10s - 4ms/step - ia: 0.7920 - loss: 0.1597 - mae: 0.3064 - rmse: 0.3910 - smape: 0.6961 - val_ia: 0.2753 - val_loss: 0.3497 - val_mae: 0.4802 - val_rmse: 0.5152 - val_smape: 1.0634

Epoch 83/128

2292/2292 - 9s - 4ms/step - ia: 0.7922 - loss: 0.1597 - mae: 0.3060 - rmse: 0.3906 - smape: 0.6948 - val_ia: 0.2681 - val_loss: 0.3654 - val_mae: 0.4924 - val_rmse: 0.5275 - val_smape: 1.0733

Epoch 84/128

2292/2292 - 9s - 4ms/step - ia: 0.7926 - loss: 0.1590 - mae: 0.3062 - rmse: 0.3894 - smape: 0.6969 - val_ia: 0.2731 - val_loss: 0.3493 - val_mae: 0.4806 - val_rmse: 0.5155 - val_smape: 1.0625

Epoch 85/128

2292/2292 - 13s - 6ms/step - ia: 0.7912 - loss: 0.1618 - mae: 0.3080 - rmse: 0.3926 - smape: 0.6966 - val_ia: 0.2749 - val_loss: 0.3589 - val_mae: 0.4874 - val_rmse: 0.5208 - val_smape: 1.0677

Epoch 86/128

2292/2292 - 15s - 7ms/step - ia: 0.7936 - loss: 0.1583 - mae: 0.3050 - rmse: 0.3885 - smape: 0.6930 - val_ia: 0.2704 - val_loss: 0.3709 - val_mae: 0.4959 - val_rmse: 0.5297 - val_smape: 1.0869

Epoch 87/128

2292/2292 - 11s - 5ms/step - ia: 0.7938 - loss: 0.1579 - mae: 0.3050 - rmse: 0.3886 - smape: 0.6924 - val_ia: 0.2760 - val_loss: 0.3540 - val_mae: 0.4836 - val_rmse: 0.5180 - val_smape: 1.0517

Epoch 88/128

2292/2292 - 12s - 5ms/step - ia: 0.7935 - loss: 0.1584 - mae: 0.3049 - rmse: 0.3892 - smape: 0.6950 - val_ia: 0.2726 - val_loss: 0.3505 - val_mae: 0.4810 - val_rmse: 0.5165 - val_smape: 1.0440

Epoch 89/128

2292/2292 - 18s - 8ms/step - ia: 0.7923 - loss: 0.1607 - mae: 0.3065 - rmse: 0.3915 - smape: 0.6939 - val_ia: 0.2778 - val_loss: 0.3382 - val_mae: 0.4712 - val_rmse: 0.5066 - val_smape: 1.0275

Epoch 90/128

2292/2292 - 10s - 4ms/step - ia: 0.7949 - loss: 0.1572 - mae: 0.3034 - rmse: 0.3868 - smape: 0.6911 - val_ia: 0.2770 - val_loss: 0.3427 - val_mae: 0.4750 - val_rmse: 0.5098 - val_smape: 1.0457

Epoch 91/128

2292/2292 - 13s - 6ms/step - ia: 0.7946 - loss: 0.1563 - mae: 0.3029 - rmse: 0.3863 - smape: 0.6897 - val_ia: 0.2798 - val_loss: 0.3379 - val_mae: 0.4718 - val_rmse: 0.5059 - val_smape: 1.0373

Epoch 92/128

2292/2292 - 15s - 7ms/step - ia: 0.7935 - loss: 0.1592 - mae: 0.3044 - rmse: 0.3897 - smape: 0.6906 - val_ia: 0.2786 - val_loss: 0.3320 - val_mae: 0.4688 - val_rmse: 0.5027 - val_smape: 1.0306

Epoch 93/128

2292/2292 - 12s - 5ms/step - ia: 0.7953 - loss: 0.1555 - mae: 0.3023 - rmse: 0.3854 - smape: 0.6874 - val_ia: 0.2796 - val_loss: 0.3291 - val_mae: 0.4660 - val_rmse: 0.5004 - val_smape: 1.0284

Epoch 94/128

2292/2292 - 13s - 6ms/step - ia: 0.7941 - loss: 0.1579 - mae: 0.3043 - rmse: 0.3882 - smape: 0.6917 - val_ia: 0.2760 - val_loss: 0.3406 - val_mae: 0.4749 - val_rmse: 0.5099 - val_smape: 1.0358

Epoch 95/128

2292/2292 - 17s - 7ms/step - ia: 0.7953 - loss: 0.1562 - mae: 0.3022 - rmse: 0.3857 - smape: 0.6859 - val_ia: 0.2760 - val_loss: 0.3363 - val_mae: 0.4727 - val_rmse: 0.5076 - val_smape: 1.0296

Epoch 96/128

2292/2292 - 16s - 7ms/step - ia: 0.7939 - loss: 0.1574 - mae: 0.3039 - rmse: 0.3877 - smape: 0.6910 - val_ia: 0.2752 - val_loss: 0.3364 - val_mae: 0.4737 - val_rmse: 0.5078 - val_smape: 1.0380

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

573/573 - 9s - 16ms/step - ia: 0.3895 - loss: 1.0374 - mae: 0.8275 - rmse: 1.0125 - smape: 1.2971 - val_ia: 0.3415 - val_loss: 0.8430 - val_mae: 0.7346 - val_rmse: 0.8765 - val_smape: 1.2724

Epoch 2/128

573/573 - 2s - 4ms/step - ia: 0.4598 - loss: 0.7981 - mae: 0.7253 - rmse: 0.8902 - smape: 1.1952 - val_ia: 0.3625 - val_loss: 0.8072 - val_mae: 0.7071 - val_rmse: 0.8486 - val_smape: 1.1937

Epoch 3/128

573/573 - 3s - 5ms/step - ia: 0.4967 - loss: 0.7040 - mae: 0.6831 - rmse: 0.8363 - smape: 1.1446 - val_ia: 0.3727 - val_loss: 0.7974 - val_mae: 0.7035 - val_rmse: 0.8387 - val_smape: 1.1701

Epoch 4/128

573/573 - 3s - 5ms/step - ia: 0.5219 - loss: 0.6355 - mae: 0.6509 - rmse: 0.7943 - smape: 1.1063 - val_ia: 0.3775 - val_loss: 0.8066 - val_mae: 0.7108 - val_rmse: 0.8411 - val_smape: 1.1694

Epoch 5/128

573/573 - 6s - 11ms/step - ia: 0.5454 - loss: 0.5797 - mae: 0.6216 - rmse: 0.7587 - smape: 1.0699 - val_ia: 0.3781 - val_loss: 0.8278 - val_mae: 0.7245 - val_rmse: 0.8522 - val_smape: 1.1779

Epoch 6/128

573/573 - 4s - 7ms/step - ia: 0.5670 - loss: 0.5343 - mae: 0.5963 - rmse: 0.7282 - smape: 1.0376 - val_ia: 0.3751 - val_loss: 0.8575 - val_mae: 0.7439 - val_rmse: 0.8692 - val_smape: 1.1899

Epoch 7/128

573/573 - 5s - 8ms/step - ia: 0.5847 - loss: 0.4985 - mae: 0.5757 - rmse: 0.7037 - smape: 1.0103 - val_ia: 0.3729 - val_loss: 0.8944 - val_mae: 0.7641 - val_rmse: 0.8892 - val_smape: 1.2006

Epoch 8/128

573/573 - 6s - 10ms/step - ia: 0.6017 - loss: 0.4703 - mae: 0.5587 - rmse: 0.6835 - smape: 0.9854 - val_ia: 0.3701 - val_loss: 0.9266 - val_mae: 0.7833 - val_rmse: 0.9067 - val_smape: 1.2171

Epoch 9/128

573/573 - 4s - 7ms/step - ia: 0.6145 - loss: 0.4478 - mae: 0.5448 - rmse: 0.6666 - smape: 0.9674 - val_ia: 0.3683 - val_loss: 0.9590 - val_mae: 0.8011 - val_rmse: 0.9234 - val_smape: 1.2289

Epoch 10/128

573/573 - 5s - 9ms/step - ia: 0.6254 - loss: 0.4293 - mae: 0.5329 - rmse: 0.6526 - smape: 0.9504 - val_ia: 0.3676 - val_loss: 0.9871 - val_mae: 0.8147 - val_rmse: 0.9365 - val_smape: 1.2359

Epoch 11/128

573/573 - 4s - 8ms/step - ia: 0.6356 - loss: 0.4139 - mae: 0.5225 - rmse: 0.6408 - smape: 0.9357 - val_ia: 0.3676 - val_loss: 1.0120 - val_mae: 0.8252 - val_rmse: 0.9470 - val_smape: 1.2405

Epoch 12/128

573/573 - 6s - 10ms/step - ia: 0.6443 - loss: 0.4009 - mae: 0.5132 - rmse: 0.6309 - smape: 0.9223 - val_ia: 0.3675 - val_loss: 1.0318 - val_mae: 0.8341 - val_rmse: 0.9551 - val_smape: 1.2466

Epoch 13/128

573/573 - 5s - 8ms/step - ia: 0.6514 - loss: 0.3897 - mae: 0.5049 - rmse: 0.6219 - smape: 0.9102 - val_ia: 0.3682 - val_loss: 1.0497 - val_mae: 0.8401 - val_rmse: 0.9613 - val_smape: 1.2490

Epoch 14/128

573/573 - 5s - 8ms/step - ia: 0.6592 - loss: 0.3799 - mae: 0.4974 - rmse: 0.6138 - smape: 0.8986 - val_ia: 0.3690 - val_loss: 1.0613 - val_mae: 0.8438 - val_rmse: 0.9650 - val_smape: 1.2538

Epoch 15/128

573/573 - 5s - 8ms/step - ia: 0.6649 - loss: 0.3713 - mae: 0.4905 - rmse: 0.6070 - smape: 0.8882 - val_ia: 0.3704 - val_loss: 1.0703 - val_mae: 0.8446 - val_rmse: 0.9668 - val_smape: 1.2554

Epoch 16/128

573/573 - 4s - 8ms/step - ia: 0.6701 - loss: 0.3635 - mae: 0.4845 - rmse: 0.6004 - smape: 0.8796 - val_ia: 0.3717 - val_loss: 1.0723 - val_mae: 0.8441 - val_rmse: 0.9663 - val_smape: 1.2595

Epoch 17/128

573/573 - 3s - 5ms/step - ia: 0.6748 - loss: 0.3567 - mae: 0.4789 - rmse: 0.5948 - smape: 0.8721 - val_ia: 0.3732 - val_loss: 1.0743 - val_mae: 0.8433 - val_rmse: 0.9658 - val_smape: 1.2622

Epoch 18/128

573/573 - 5s - 8ms/step - ia: 0.6789 - loss: 0.3504 - mae: 0.4738 - rmse: 0.5896 - smape: 0.8661 - val_ia: 0.3745 - val_loss: 1.0842 - val_mae: 0.8449 - val_rmse: 0.9683 - val_smape: 1.2628

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:20 866ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 66%|██████▌   | 33/50 [3:15:12<3:17:23, 696.65s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

2292/2292 - 18s - 8ms/step - ia: 0.6231 - loss: 0.4852 - mae: 0.5478 - rmse: 0.6754 - smape: 0.9310 - val_ia: 0.2252 - val_loss: 1.0676 - val_mae: 0.8225 - val_rmse: 0.8600 - val_smape: 1.1652

Epoch 2/32

2292/2292 - 9s - 4ms/step - ia: 0.6877 - loss: 0.3224 - mae: 0.4519 - rmse: 0.5588 - smape: 0.8275 - val_ia: 0.2268 - val_loss: 1.0501 - val_mae: 0.8033 - val_rmse: 0.8458 - val_smape: 1.1240

Epoch 3/32

2292/2292 - 14s - 6ms/step - ia: 0.7063 - loss: 0.2875 - mae: 0.4260 - rmse: 0.5279 - smape: 0.7958 - val_ia: 0.2322 - val_loss: 0.7379 - val_mae: 0.6869 - val_rmse: 0.7303 - val_smape: 1.0928

Epoch 4/32

2292/2292 - 10s - 4ms/step - ia: 0.7193 - loss: 0.2662 - mae: 0.4092 - rmse: 0.5076 - smape: 0.7723 - val_ia: 0.2440 - val_loss: 0.6152 - val_mae: 0.6269 - val_rmse: 0.6707 - val_smape: 1.0436

Epoch 5/32

2292/2292 - 9s - 4ms/step - ia: 0.7273 - loss: 0.2535 - mae: 0.3997 - rmse: 0.4951 - smape: 0.7650 - val_ia: 0.2511 - val_loss: 0.5707 - val_mae: 0.6035 - val_rmse: 0.6472 - val_smape: 1.0320

Epoch 6/32

2292/2292 - 12s - 5ms/step - ia: 0.7351 - loss: 0.2431 - mae: 0.3900 - rmse: 0.4849 - smape: 0.7500 - val_ia: 0.2621 - val_loss: 0.4514 - val_mae: 0.5493 - val_rmse: 0.5904 - val_smape: 1.0076

Epoch 7/32

2292/2292 - 13s - 6ms/step - ia: 0.7398 - loss: 0.2361 - mae: 0.3840 - rmse: 0.4774 - smape: 0.7451 - val_ia: 0.2596 - val_loss: 0.4645 - val_mae: 0.5570 - val_rmse: 0.5981 - val_smape: 1.0046

Epoch 8/32

2292/2292 - 20s - 9ms/step - ia: 0.7419 - loss: 0.2317 - mae: 0.3794 - rmse: 0.4726 - smape: 0.7374 - val_ia: 0.2726 - val_loss: 0.3743 - val_mae: 0.4997 - val_rmse: 0.5398 - val_smape: 0.9480

Epoch 9/32

2292/2292 - 13s - 6ms/step - ia: 0.7452 - loss: 0.2278 - mae: 0.3763 - rmse: 0.4688 - smape: 0.7361 - val_ia: 0.2716 - val_loss: 0.3723 - val_mae: 0.5014 - val_rmse: 0.5408 - val_smape: 0.9471

Epoch 10/32

2292/2292 - 14s - 6ms/step - ia: 0.7478 - loss: 0.2251 - mae: 0.3732 - rmse: 0.4660 - smape: 0.7278 - val_ia: 0.2922 - val_loss: 0.2979 - val_mae: 0.4507 - val_rmse: 0.4868 - val_smape: 0.8737

Epoch 11/32

2292/2292 - 12s - 5ms/step - ia: 0.7477 - loss: 0.2248 - mae: 0.3727 - rmse: 0.4661 - smape: 0.7287 - val_ia: 0.2818 - val_loss: 0.3306 - val_mae: 0.4742 - val_rmse: 0.5113 - val_smape: 0.9136

Epoch 12/32

2292/2292 - 10s - 4ms/step - ia: 0.7502 - loss: 0.2213 - mae: 0.3692 - rmse: 0.4620 - smape: 0.7235 - val_ia: 0.2853 - val_loss: 0.3310 - val_mae: 0.4733 - val_rmse: 0.5120 - val_smape: 0.9142

Epoch 13/32

2292/2292 - 13s - 6ms/step - ia: 0.7522 - loss: 0.2203 - mae: 0.3675 - rmse: 0.4609 - smape: 0.7179 - val_ia: 0.2759 - val_loss: 0.3728 - val_mae: 0.5026 - val_rmse: 0.5418 - val_smape: 0.9443

Epoch 14/32

2292/2292 - 12s - 5ms/step - ia: 0.7527 - loss: 0.2182 - mae: 0.3656 - rmse: 0.4585 - smape: 0.7192 - val_ia: 0.2897 - val_loss: 0.3182 - val_mae: 0.4639 - val_rmse: 0.5022 - val_smape: 0.8956

Epoch 15/32

2292/2292 - 12s - 5ms/step - ia: 0.7556 - loss: 0.2155 - mae: 0.3626 - rmse: 0.4553 - smape: 0.7150 - val_ia: 0.2910 - val_loss: 0.3211 - val_mae: 0.4690 - val_rmse: 0.5062 - val_smape: 0.8844

Epoch 16/32

2292/2292 - 13s - 5ms/step - ia: 0.7546 - loss: 0.2158 - mae: 0.3635 - rmse: 0.4554 - smape: 0.7145 - val_ia: 0.2870 - val_loss: 0.2958 - val_mae: 0.4537 - val_rmse: 0.4897 - val_smape: 0.8720

Epoch 17/32

2292/2292 - 21s - 9ms/step - ia: 0.7563 - loss: 0.2134 - mae: 0.3612 - rmse: 0.4534 - smape: 0.7115 - val_ia: 0.3025 - val_loss: 0.2857 - val_mae: 0.4371 - val_rmse: 0.4752 - val_smape: 0.8619

Epoch 18/32

2292/2292 - 18s - 8ms/step - ia: 0.7564 - loss: 0.2125 - mae: 0.3603 - rmse: 0.4521 - smape: 0.7112 - val_ia: 0.2890 - val_loss: 0.3146 - val_mae: 0.4644 - val_rmse: 0.5035 - val_smape: 0.8884

Epoch 19/32

2292/2292 - 12s - 5ms/step - ia: 0.7569 - loss: 0.2135 - mae: 0.3603 - rmse: 0.4530 - smape: 0.7125 - val_ia: 0.2907 - val_loss: 0.3302 - val_mae: 0.4737 - val_rmse: 0.5126 - val_smape: 0.8892

Epoch 20/32

2292/2292 - 10s - 4ms/step - ia: 0.7591 - loss: 0.2098 - mae: 0.3575 - rmse: 0.4494 - smape: 0.7079 - val_ia: 0.2857 - val_loss: 0.3288 - val_mae: 0.4731 - val_rmse: 0.5129 - val_smape: 0.8967

Epoch 21/32

2292/2292 - 12s - 5ms/step - ia: 0.7587 - loss: 0.2110 - mae: 0.3587 - rmse: 0.4505 - smape: 0.7080 - val_ia: 0.2966 - val_loss: 0.3118 - val_mae: 0.4604 - val_rmse: 0.4983 - val_smape: 0.8751

Epoch 22/32

2292/2292 - 14s - 6ms/step - ia: 0.7578 - loss: 0.2124 - mae: 0.3594 - rmse: 0.4521 - smape: 0.7105 - val_ia: 0.2891 - val_loss: 0.3196 - val_mae: 0.4608 - val_rmse: 0.4987 - val_smape: 0.8951

Epoch 23/32

2292/2292 - 10s - 4ms/step - ia: 0.7589 - loss: 0.2098 - mae: 0.3572 - rmse: 0.4497 - smape: 0.7070 - val_ia: 0.2916 - val_loss: 0.3374 - val_mae: 0.4742 - val_rmse: 0.5150 - val_smape: 0.8950

Epoch 24/32

2292/2292 - 11s - 5ms/step - ia: 0.7612 - loss: 0.2074 - mae: 0.3544 - rmse: 0.4467 - smape: 0.7029 - val_ia: 0.3031 - val_loss: 0.2766 - val_mae: 0.4306 - val_rmse: 0.4693 - val_smape: 0.8402

Epoch 25/32

2292/2292 - 12s - 5ms/step - ia: 0.7619 - loss: 0.2060 - mae: 0.3533 - rmse: 0.4450 - smape: 0.7007 - val_ia: 0.2854 - val_loss: 0.3098 - val_mae: 0.4634 - val_rmse: 0.5018 - val_smape: 0.8767

Epoch 26/32

2292/2292 - 12s - 5ms/step - ia: 0.7599 - loss: 0.2082 - mae: 0.3556 - rmse: 0.4474 - smape: 0.7035 - val_ia: 0.2999 - val_loss: 0.3035 - val_mae: 0.4524 - val_rmse: 0.4910 - val_smape: 0.8583

Epoch 27/32

2292/2292 - 20s - 9ms/step - ia: 0.7608 - loss: 0.2070 - mae: 0.3547 - rmse: 0.4464 - smape: 0.7030 - val_ia: 0.3244 - val_loss: 0.2261 - val_mae: 0.3888 - val_rmse: 0.4237 - val_smape: 0.7325

Epoch 28/32

2292/2292 - 11s - 5ms/step - ia: 0.7607 - loss: 0.2080 - mae: 0.3542 - rmse: 0.4470 - smape: 0.7006 - val_ia: 0.2969 - val_loss: 0.2967 - val_mae: 0.4475 - val_rmse: 0.4875 - val_smape: 0.8640

Epoch 29/32

2292/2292 - 20s - 9ms/step - ia: 0.7611 - loss: 0.2066 - mae: 0.3539 - rmse: 0.4455 - smape: 0.7018 - val_ia: 0.3095 - val_loss: 0.2619 - val_mae: 0.4217 - val_rmse: 0.4592 - val_smape: 0.7924

Epoch 30/32

2292/2292 - 12s - 5ms/step - ia: 0.7641 - loss: 0.2036 - mae: 0.3516 - rmse: 0.4424 - smape: 0.7017 - val_ia: 0.3037 - val_loss: 0.2740 - val_mae: 0.4314 - val_rmse: 0.4698 - val_smape: 0.8371

Epoch 31/32

2292/2292 - 13s - 6ms/step - ia: 0.7606 - loss: 0.2063 - mae: 0.3541 - rmse: 0.4453 - smape: 0.7022 - val_ia: 0.2978 - val_loss: 0.2876 - val_mae: 0.4426 - val_rmse: 0.4828 - val_smape: 0.8436

Epoch 32/32

2292/2292 - 12s - 5ms/step - ia: 0.7619 - loss: 0.2059 - mae: 0.3530 - rmse: 0.4450 - smape: 0.7005 - val_ia: 0.2983 - val_loss: 0.3017 - val_mae: 0.4544 - val_rmse: 0.4933 - val_smape: 0.8535

Restoring model weights from the end of the best epoch: 27.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:01 750ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 12s 76ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step

 68%|██████▊   | 34/50 [3:23:01<2:47:35, 628.50s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1146/1146 - 24s - 21ms/step - ia: 0.7074 - loss: 0.3189 - mae: 0.4319 - rmse: 0.5474 - smape: 0.8196 - val_ia: 0.3442 - val_loss: 0.8237 - val_mae: 0.6655 - val_rmse: 0.7546 - val_smape: 1.1593

Epoch 2/64

1146/1146 - 8s - 7ms/step - ia: 0.7986 - loss: 0.1634 - mae: 0.3080 - rmse: 0.3990 - smape: 0.6802 - val_ia: 0.4470 - val_loss: 0.4383 - val_mae: 0.4653 - val_rmse: 0.5426 - val_smape: 0.9161

Epoch 3/64

1146/1146 - 6s - 6ms/step - ia: 0.8234 - loss: 0.1299 - mae: 0.2725 - rmse: 0.3558 - smape: 0.6318 - val_ia: 0.4705 - val_loss: 0.2705 - val_mae: 0.3876 - val_rmse: 0.4510 - val_smape: 0.8221

Epoch 4/64

1146/1146 - 9s - 7ms/step - ia: 0.8405 - loss: 0.1091 - mae: 0.2481 - rmse: 0.3253 - smape: 0.5934 - val_ia: 0.4393 - val_loss: 0.3963 - val_mae: 0.4544 - val_rmse: 0.5324 - val_smape: 0.9144

Epoch 5/64

1146/1146 - 8s - 7ms/step - ia: 0.8500 - loss: 0.0982 - mae: 0.2341 - rmse: 0.3086 - smape: 0.5663 - val_ia: 0.4704 - val_loss: 0.3920 - val_mae: 0.4326 - val_rmse: 0.5080 - val_smape: 0.8496

Epoch 6/64

1146/1146 - 10s - 8ms/step - ia: 0.8565 - loss: 0.0906 - mae: 0.2245 - rmse: 0.2964 - smape: 0.5414 - val_ia: 0.4772 - val_loss: 0.4229 - val_mae: 0.4427 - val_rmse: 0.5191 - val_smape: 0.8382

Epoch 7/64

1146/1146 - 7s - 6ms/step - ia: 0.8615 - loss: 0.0847 - mae: 0.2169 - rmse: 0.2865 - smape: 0.5246 - val_ia: 0.4803 - val_loss: 0.3568 - val_mae: 0.4146 - val_rmse: 0.4934 - val_smape: 0.8556

Epoch 8/64

1146/1146 - 7s - 6ms/step - ia: 0.8668 - loss: 0.0793 - mae: 0.2092 - rmse: 0.2770 - smape: 0.5111 - val_ia: 0.4769 - val_loss: 0.4010 - val_mae: 0.4332 - val_rmse: 0.5103 - val_smape: 0.8417

Epoch 9/64

1146/1146 - 8s - 7ms/step - ia: 0.8697 - loss: 0.0758 - mae: 0.2049 - rmse: 0.2709 - smape: 0.5031 - val_ia: 0.4903 - val_loss: 0.2735 - val_mae: 0.3710 - val_rmse: 0.4463 - val_smape: 0.7705

Epoch 10/64

1146/1146 - 10s - 9ms/step - ia: 0.8717 - loss: 0.0733 - mae: 0.2016 - rmse: 0.2660 - smape: 0.4986 - val_ia: 0.4837 - val_loss: 0.3602 - val_mae: 0.4180 - val_rmse: 0.4870 - val_smape: 0.8503

Epoch 11/64

1146/1146 - 11s - 10ms/step - ia: 0.8751 - loss: 0.0699 - mae: 0.1967 - rmse: 0.2602 - smape: 0.4900 - val_ia: 0.4858 - val_loss: 0.3617 - val_mae: 0.4130 - val_rmse: 0.4881 - val_smape: 0.8324

Epoch 12/64

1146/1146 - 7s - 6ms/step - ia: 0.8774 - loss: 0.0678 - mae: 0.1932 - rmse: 0.2562 - smape: 0.4803 - val_ia: 0.4979 - val_loss: 0.3303 - val_mae: 0.3954 - val_rmse: 0.4657 - val_smape: 0.7880

Epoch 13/64

1146/1146 - 5s - 4ms/step - ia: 0.8792 - loss: 0.0661 - mae: 0.1906 - rmse: 0.2525 - smape: 0.4745 - val_ia: 0.4920 - val_loss: 0.3588 - val_mae: 0.4135 - val_rmse: 0.4842 - val_smape: 0.8002

Epoch 14/64

1146/1146 - 8s - 7ms/step - ia: 0.8808 - loss: 0.0645 - mae: 0.1882 - rmse: 0.2496 - smape: 0.4707 - val_ia: 0.4801 - val_loss: 0.3581 - val_mae: 0.4156 - val_rmse: 0.4929 - val_smape: 0.8178

Epoch 15/64

1146/1146 - 8s - 7ms/step - ia: 0.8814 - loss: 0.0635 - mae: 0.1868 - rmse: 0.2474 - smape: 0.4696 - val_ia: 0.4927 - val_loss: 0.3529 - val_mae: 0.4025 - val_rmse: 0.4825 - val_smape: 0.7866

Epoch 16/64

1146/1146 - 10s - 9ms/step - ia: 0.8834 - loss: 0.0614 - mae: 0.1838 - rmse: 0.2436 - smape: 0.4613 - val_ia: 0.4975 - val_loss: 0.3098 - val_mae: 0.3912 - val_rmse: 0.4590 - val_smape: 0.7853

Epoch 17/64

1146/1146 - 7s - 6ms/step - ia: 0.8845 - loss: 0.0606 - mae: 0.1825 - rmse: 0.2420 - smape: 0.4590 - val_ia: 0.4815 - val_loss: 0.4683 - val_mae: 0.4420 - val_rmse: 0.5271 - val_smape: 0.8397

Epoch 18/64

1146/1146 - 7s - 6ms/step - ia: 0.8855 - loss: 0.0598 - mae: 0.1808 - rmse: 0.2400 - smape: 0.4563 - val_ia: 0.4938 - val_loss: 0.3665 - val_mae: 0.4089 - val_rmse: 0.4854 - val_smape: 0.8099

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:37 600ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 51/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
158/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 70%|███████   | 35/50 [3:25:47<2:02:24, 489.63s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 26s - 11ms/step - ia: 0.3858 - loss: 0.9870 - mae: 0.8049 - rmse: 0.9727 - smape: 1.3145 - val_ia: 0.1799 - val_loss: 0.9997 - val_mae: 0.8378 - val_rmse: 0.8707 - val_smape: 1.3283

Epoch 2/128

2292/2292 - 13s - 6ms/step - ia: 0.5345 - loss: 0.6507 - mae: 0.6470 - rmse: 0.7947 - smape: 1.0766 - val_ia: 0.1732 - val_loss: 1.2087 - val_mae: 0.9318 - val_rmse: 0.9680 - val_smape: 1.3530

Epoch 3/128

2292/2292 - 21s - 9ms/step - ia: 0.5634 - loss: 0.5775 - mae: 0.6064 - rmse: 0.7491 - smape: 1.0229 - val_ia: 0.1733 - val_loss: 1.1805 - val_mae: 0.9177 - val_rmse: 0.9539 - val_smape: 1.3501

Epoch 4/128

2292/2292 - 13s - 6ms/step - ia: 0.5784 - loss: 0.5331 - mae: 0.5829 - rmse: 0.7189 - smape: 0.9951 - val_ia: 0.1698 - val_loss: 1.2907 - val_mae: 0.9609 - val_rmse: 0.9969 - val_smape: 1.3749

Epoch 5/128

2292/2292 - 20s - 9ms/step - ia: 0.5932 - loss: 0.4992 - mae: 0.5624 - rmse: 0.6957 - smape: 0.9666 - val_ia: 0.1729 - val_loss: 1.2440 - val_mae: 0.9348 - val_rmse: 0.9708 - val_smape: 1.3654

Epoch 6/128

2292/2292 - 20s - 9ms/step - ia: 0.5993 - loss: 0.4797 - mae: 0.5520 - rmse: 0.6821 - smape: 0.9593 - val_ia: 0.1741 - val_loss: 1.2303 - val_mae: 0.9239 - val_rmse: 0.9592 - val_smape: 1.3634

Epoch 7/128

2292/2292 - 12s - 5ms/step - ia: 0.6142 - loss: 0.4545 - mae: 0.5361 - rmse: 0.6641 - smape: 0.9372 - val_ia: 0.1746 - val_loss: 1.1918 - val_mae: 0.9035 - val_rmse: 0.9382 - val_smape: 1.3612

Epoch 8/128

2292/2292 - 17s - 7ms/step - ia: 0.6242 - loss: 0.4348 - mae: 0.5247 - rmse: 0.6495 - smape: 0.9239 - val_ia: 0.1765 - val_loss: 1.1316 - val_mae: 0.8734 - val_rmse: 0.9078 - val_smape: 1.3410

Epoch 9/128

2292/2292 - 13s - 5ms/step - ia: 0.6363 - loss: 0.4109 - mae: 0.5100 - rmse: 0.6314 - smape: 0.9031 - val_ia: 0.1780 - val_loss: 1.1068 - val_mae: 0.8598 - val_rmse: 0.8932 - val_smape: 1.3327

Epoch 10/128

2292/2292 - 21s - 9ms/step - ia: 0.6473 - loss: 0.3909 - mae: 0.4983 - rmse: 0.6157 - smape: 0.8853 - val_ia: 0.1804 - val_loss: 1.0829 - val_mae: 0.8475 - val_rmse: 0.8803 - val_smape: 1.3182

Epoch 11/128

2292/2292 - 13s - 5ms/step - ia: 0.6577 - loss: 0.3742 - mae: 0.4878 - rmse: 0.6022 - smape: 0.8699 - val_ia: 0.1830 - val_loss: 1.0449 - val_mae: 0.8305 - val_rmse: 0.8625 - val_smape: 1.3060

Epoch 12/128

2292/2292 - 12s - 5ms/step - ia: 0.6668 - loss: 0.3578 - mae: 0.4767 - rmse: 0.5894 - smape: 0.8540 - val_ia: 0.1867 - val_loss: 1.0038 - val_mae: 0.8098 - val_rmse: 0.8415 - val_smape: 1.2837

Epoch 13/128

2292/2292 - 13s - 6ms/step - ia: 0.6723 - loss: 0.3461 - mae: 0.4694 - rmse: 0.5791 - smape: 0.8442 - val_ia: 0.1903 - val_loss: 0.9725 - val_mae: 0.7912 - val_rmse: 0.8229 - val_smape: 1.2591

Epoch 14/128

2292/2292 - 12s - 5ms/step - ia: 0.6797 - loss: 0.3372 - mae: 0.4619 - rmse: 0.5716 - smape: 0.8310 - val_ia: 0.1947 - val_loss: 0.9753 - val_mae: 0.7876 - val_rmse: 0.8194 - val_smape: 1.2447

Epoch 15/128

2292/2292 - 16s - 7ms/step - ia: 0.6863 - loss: 0.3271 - mae: 0.4536 - rmse: 0.5628 - smape: 0.8223 - val_ia: 0.2003 - val_loss: 0.9210 - val_mae: 0.7607 - val_rmse: 0.7925 - val_smape: 1.2260

Epoch 16/128

2292/2292 - 15s - 6ms/step - ia: 0.6907 - loss: 0.3178 - mae: 0.4464 - rmse: 0.5549 - smape: 0.8141 - val_ia: 0.2050 - val_loss: 0.9187 - val_mae: 0.7563 - val_rmse: 0.7882 - val_smape: 1.2164

Epoch 17/128

2292/2292 - 28s - 12ms/step - ia: 0.6973 - loss: 0.3083 - mae: 0.4401 - rmse: 0.5462 - smape: 0.8066 - val_ia: 0.2087 - val_loss: 0.9249 - val_mae: 0.7542 - val_rmse: 0.7862 - val_smape: 1.2065

Epoch 18/128

2292/2292 - 13s - 6ms/step - ia: 0.7017 - loss: 0.3001 - mae: 0.4336 - rmse: 0.5386 - smape: 0.7997 - val_ia: 0.2125 - val_loss: 0.9195 - val_mae: 0.7505 - val_rmse: 0.7828 - val_smape: 1.2032

Epoch 19/128

2292/2292 - 14s - 6ms/step - ia: 0.7050 - loss: 0.2940 - mae: 0.4294 - rmse: 0.5332 - smape: 0.7965 - val_ia: 0.2166 - val_loss: 0.8910 - val_mae: 0.7347 - val_rmse: 0.7672 - val_smape: 1.1907

Epoch 20/128

2292/2292 - 14s - 6ms/step - ia: 0.7100 - loss: 0.2868 - mae: 0.4229 - rmse: 0.5263 - smape: 0.7900 - val_ia: 0.2192 - val_loss: 0.9211 - val_mae: 0.7441 - val_rmse: 0.7770 - val_smape: 1.1881

Epoch 21/128

2292/2292 - 19s - 8ms/step - ia: 0.7139 - loss: 0.2791 - mae: 0.4163 - rmse: 0.5194 - smape: 0.7831 - val_ia: 0.2231 - val_loss: 0.8769 - val_mae: 0.7233 - val_rmse: 0.7567 - val_smape: 1.1792

Epoch 22/128

2292/2292 - 13s - 6ms/step - ia: 0.7175 - loss: 0.2737 - mae: 0.4125 - rmse: 0.5141 - smape: 0.7794 - val_ia: 0.2258 - val_loss: 0.8667 - val_mae: 0.7174 - val_rmse: 0.7512 - val_smape: 1.1747

Epoch 23/128

2292/2292 - 19s - 8ms/step - ia: 0.7217 - loss: 0.2677 - mae: 0.4075 - rmse: 0.5082 - smape: 0.7750 - val_ia: 0.2290 - val_loss: 0.8306 - val_mae: 0.7007 - val_rmse: 0.7350 - val_smape: 1.1667

Epoch 24/128

2292/2292 - 15s - 7ms/step - ia: 0.7233 - loss: 0.2626 - mae: 0.4036 - rmse: 0.5034 - smape: 0.7718 - val_ia: 0.2322 - val_loss: 0.8294 - val_mae: 0.6961 - val_rmse: 0.7311 - val_smape: 1.1557

Epoch 25/128

2292/2292 - 14s - 6ms/step - ia: 0.7270 - loss: 0.2582 - mae: 0.3995 - rmse: 0.4988 - smape: 0.7684 - val_ia: 0.2332 - val_loss: 0.8270 - val_mae: 0.6964 - val_rmse: 0.7316 - val_smape: 1.1613

Epoch 26/128

2292/2292 - 13s - 6ms/step - ia: 0.7310 - loss: 0.2512 - mae: 0.3940 - rmse: 0.4922 - smape: 0.7626 - val_ia: 0.2381 - val_loss: 0.7741 - val_mae: 0.6723 - val_rmse: 0.7078 - val_smape: 1.1438

Epoch 27/128

2292/2292 - 12s - 5ms/step - ia: 0.7341 - loss: 0.2482 - mae: 0.3908 - rmse: 0.4892 - smape: 0.7593 - val_ia: 0.2423 - val_loss: 0.7453 - val_mae: 0.6572 - val_rmse: 0.6935 - val_smape: 1.1303

Epoch 28/128

2292/2292 - 14s - 6ms/step - ia: 0.7360 - loss: 0.2431 - mae: 0.3864 - rmse: 0.4841 - smape: 0.7542 - val_ia: 0.2424 - val_loss: 0.7501 - val_mae: 0.6593 - val_rmse: 0.6960 - val_smape: 1.1332

Epoch 29/128

2292/2292 - 11s - 5ms/step - ia: 0.7371 - loss: 0.2412 - mae: 0.3849 - rmse: 0.4821 - smape: 0.7536 - val_ia: 0.2457 - val_loss: 0.7249 - val_mae: 0.6474 - val_rmse: 0.6844 - val_smape: 1.1259

Epoch 30/128

2292/2292 - 22s - 10ms/step - ia: 0.7414 - loss: 0.2355 - mae: 0.3797 - rmse: 0.4762 - smape: 0.7507 - val_ia: 0.2476 - val_loss: 0.7193 - val_mae: 0.6443 - val_rmse: 0.6819 - val_smape: 1.1229

Epoch 31/128

2292/2292 - 21s - 9ms/step - ia: 0.7425 - loss: 0.2341 - mae: 0.3788 - rmse: 0.4750 - smape: 0.7480 - val_ia: 0.2500 - val_loss: 0.6912 - val_mae: 0.6305 - val_rmse: 0.6685 - val_smape: 1.1131

Epoch 32/128

2292/2292 - 12s - 5ms/step - ia: 0.7432 - loss: 0.2304 - mae: 0.3767 - rmse: 0.4712 - smape: 0.7489 - val_ia: 0.2515 - val_loss: 0.6823 - val_mae: 0.6264 - val_rmse: 0.6650 - val_smape: 1.1109

Epoch 33/128

2292/2292 - 13s - 6ms/step - ia: 0.7469 - loss: 0.2265 - mae: 0.3729 - rmse: 0.4673 - smape: 0.7461 - val_ia: 0.2544 - val_loss: 0.6534 - val_mae: 0.6124 - val_rmse: 0.6516 - val_smape: 1.0976

Epoch 34/128

2292/2292 - 11s - 5ms/step - ia: 0.7502 - loss: 0.2233 - mae: 0.3693 - rmse: 0.4638 - smape: 0.7398 - val_ia: 0.2567 - val_loss: 0.6474 - val_mae: 0.6083 - val_rmse: 0.6476 - val_smape: 1.0963

Epoch 35/128

2292/2292 - 23s - 10ms/step - ia: 0.7496 - loss: 0.2217 - mae: 0.3677 - rmse: 0.4619 - smape: 0.7388 - val_ia: 0.2591 - val_loss: 0.6155 - val_mae: 0.5936 - val_rmse: 0.6335 - val_smape: 1.0833

Epoch 36/128

2292/2292 - 13s - 6ms/step - ia: 0.7517 - loss: 0.2186 - mae: 0.3657 - rmse: 0.4593 - smape: 0.7345 - val_ia: 0.2609 - val_loss: 0.6017 - val_mae: 0.5863 - val_rmse: 0.6264 - val_smape: 1.0783

Epoch 37/128

2292/2292 - 11s - 5ms/step - ia: 0.7536 - loss: 0.2143 - mae: 0.3620 - rmse: 0.4539 - smape: 0.7341 - val_ia: 0.2648 - val_loss: 0.5718 - val_mae: 0.5713 - val_rmse: 0.6118 - val_smape: 1.0629

Epoch 38/128

2292/2292 - 13s - 6ms/step - ia: 0.7548 - loss: 0.2124 - mae: 0.3604 - rmse: 0.4524 - smape: 0.7341 - val_ia: 0.2650 - val_loss: 0.5612 - val_mae: 0.5672 - val_rmse: 0.6081 - val_smape: 1.0598

Epoch 39/128

2292/2292 - 22s - 10ms/step - ia: 0.7551 - loss: 0.2120 - mae: 0.3599 - rmse: 0.4519 - smape: 0.7325 - val_ia: 0.2664 - val_loss: 0.5576 - val_mae: 0.5644 - val_rmse: 0.6062 - val_smape: 1.0554

Epoch 40/128

2292/2292 - 16s - 7ms/step - ia: 0.7578 - loss: 0.2080 - mae: 0.3570 - rmse: 0.4474 - smape: 0.7271 - val_ia: 0.2660 - val_loss: 0.5618 - val_mae: 0.5665 - val_rmse: 0.6085 - val_smape: 1.0582

Epoch 41/128

2292/2292 - 18s - 8ms/step - ia: 0.7616 - loss: 0.2042 - mae: 0.3530 - rmse: 0.4433 - smape: 0.7232 - val_ia: 0.2674 - val_loss: 0.5469 - val_mae: 0.5594 - val_rmse: 0.6018 - val_smape: 1.0527

Epoch 42/128

2292/2292 - 13s - 6ms/step - ia: 0.7605 - loss: 0.2046 - mae: 0.3528 - rmse: 0.4436 - smape: 0.7250 - val_ia: 0.2715 - val_loss: 0.5038 - val_mae: 0.5384 - val_rmse: 0.5810 - val_smape: 1.0315

Epoch 43/128

2292/2292 - 13s - 6ms/step - ia: 0.7610 - loss: 0.2021 - mae: 0.3515 - rmse: 0.4412 - smape: 0.7245 - val_ia: 0.2727 - val_loss: 0.4904 - val_mae: 0.5320 - val_rmse: 0.5747 - val_smape: 1.0275

Epoch 44/128

2292/2292 - 14s - 6ms/step - ia: 0.7640 - loss: 0.1987 - mae: 0.3474 - rmse: 0.4370 - smape: 0.7198 - val_ia: 0.2742 - val_loss: 0.4696 - val_mae: 0.5218 - val_rmse: 0.5652 - val_smape: 1.0132

Epoch 45/128

2292/2292 - 12s - 5ms/step - ia: 0.7658 - loss: 0.1970 - mae: 0.3460 - rmse: 0.4353 - smape: 0.7172 - val_ia: 0.2717 - val_loss: 0.4867 - val_mae: 0.5316 - val_rmse: 0.5750 - val_smape: 1.0287

Epoch 46/128

2292/2292 - 13s - 6ms/step - ia: 0.7685 - loss: 0.1937 - mae: 0.3431 - rmse: 0.4317 - smape: 0.7158 - val_ia: 0.2761 - val_loss: 0.4637 - val_mae: 0.5177 - val_rmse: 0.5619 - val_smape: 1.0098

Epoch 47/128

2292/2292 - 20s - 9ms/step - ia: 0.7691 - loss: 0.1910 - mae: 0.3414 - rmse: 0.4285 - smape: 0.7115 - val_ia: 0.2763 - val_loss: 0.4536 - val_mae: 0.5132 - val_rmse: 0.5571 - val_smape: 1.0061

Epoch 48/128

2292/2292 - 13s - 6ms/step - ia: 0.7685 - loss: 0.1926 - mae: 0.3418 - rmse: 0.4305 - smape: 0.7134 - val_ia: 0.2801 - val_loss: 0.4368 - val_mae: 0.5037 - val_rmse: 0.5482 - val_smape: 0.9935

Epoch 49/128

2292/2292 - 14s - 6ms/step - ia: 0.7690 - loss: 0.1905 - mae: 0.3410 - rmse: 0.4280 - smape: 0.7116 - val_ia: 0.2814 - val_loss: 0.4190 - val_mae: 0.4941 - val_rmse: 0.5385 - val_smape: 0.9833

Epoch 50/128

2292/2292 - 12s - 5ms/step - ia: 0.7707 - loss: 0.1884 - mae: 0.3388 - rmse: 0.4256 - smape: 0.7116 - val_ia: 0.2840 - val_loss: 0.4020 - val_mae: 0.4838 - val_rmse: 0.5286 - val_smape: 0.9668

Epoch 51/128

2292/2292 - 11s - 5ms/step - ia: 0.7727 - loss: 0.1871 - mae: 0.3363 - rmse: 0.4236 - smape: 0.7055 - val_ia: 0.2852 - val_loss: 0.4072 - val_mae: 0.4856 - val_rmse: 0.5312 - val_smape: 0.9685

Epoch 52/128

2292/2292 - 13s - 6ms/step - ia: 0.7732 - loss: 0.1853 - mae: 0.3349 - rmse: 0.4219 - smape: 0.7049 - val_ia: 0.2824 - val_loss: 0.4098 - val_mae: 0.4894 - val_rmse: 0.5347 - val_smape: 0.9775

Epoch 53/128

2292/2292 - 12s - 5ms/step - ia: 0.7748 - loss: 0.1832 - mae: 0.3329 - rmse: 0.4194 - smape: 0.7015 - val_ia: 0.2880 - val_loss: 0.3802 - val_mae: 0.4709 - val_rmse: 0.5166 - val_smape: 0.9524

Epoch 54/128

2292/2292 - 20s - 9ms/step - ia: 0.7755 - loss: 0.1809 - mae: 0.3312 - rmse: 0.4167 - smape: 0.7020 - val_ia: 0.2874 - val_loss: 0.3796 - val_mae: 0.4712 - val_rmse: 0.5169 - val_smape: 0.9529

Epoch 55/128

2292/2292 - 20s - 9ms/step - ia: 0.7778 - loss: 0.1793 - mae: 0.3291 - rmse: 0.4150 - smape: 0.6980 - val_ia: 0.2883 - val_loss: 0.3731 - val_mae: 0.4674 - val_rmse: 0.5131 - val_smape: 0.9467

Epoch 56/128

2292/2292 - 10s - 4ms/step - ia: 0.7777 - loss: 0.1780 - mae: 0.3280 - rmse: 0.4130 - smape: 0.6972 - val_ia: 0.2901 - val_loss: 0.3599 - val_mae: 0.4595 - val_rmse: 0.5056 - val_smape: 0.9355

Epoch 57/128

2292/2292 - 10s - 4ms/step - ia: 0.7785 - loss: 0.1786 - mae: 0.3288 - rmse: 0.4139 - smape: 0.6990 - val_ia: 0.2882 - val_loss: 0.3649 - val_mae: 0.4639 - val_rmse: 0.5097 - val_smape: 0.9458

Epoch 58/128

2292/2292 - 8s - 4ms/step - ia: 0.7798 - loss: 0.1759 - mae: 0.3261 - rmse: 0.4109 - smape: 0.6957 - val_ia: 0.2919 - val_loss: 0.3518 - val_mae: 0.4544 - val_rmse: 0.5007 - val_smape: 0.9297

Epoch 59/128

2292/2292 - 8s - 3ms/step - ia: 0.7813 - loss: 0.1744 - mae: 0.3245 - rmse: 0.4095 - smape: 0.6941 - val_ia: 0.2942 - val_loss: 0.3409 - val_mae: 0.4472 - val_rmse: 0.4931 - val_smape: 0.9190

Epoch 60/128

2292/2292 - 10s - 4ms/step - ia: 0.7807 - loss: 0.1741 - mae: 0.3245 - rmse: 0.4088 - smape: 0.6938 - val_ia: 0.2922 - val_loss: 0.3489 - val_mae: 0.4523 - val_rmse: 0.4983 - val_smape: 0.9275

Epoch 61/128

2292/2292 - 11s - 5ms/step - ia: 0.7821 - loss: 0.1717 - mae: 0.3222 - rmse: 0.4055 - smape: 0.6919 - val_ia: 0.2922 - val_loss: 0.3520 - val_mae: 0.4539 - val_rmse: 0.5005 - val_smape: 0.9254

Epoch 62/128

2292/2292 - 12s - 5ms/step - ia: 0.7822 - loss: 0.1717 - mae: 0.3222 - rmse: 0.4058 - smape: 0.6918 - val_ia: 0.2925 - val_loss: 0.3440 - val_mae: 0.4493 - val_rmse: 0.4954 - val_smape: 0.9226

Epoch 63/128

2292/2292 - 20s - 9ms/step - ia: 0.7844 - loss: 0.1699 - mae: 0.3195 - rmse: 0.4033 - smape: 0.6884 - val_ia: 0.2938 - val_loss: 0.3339 - val_mae: 0.4435 - val_rmse: 0.4895 - val_smape: 0.9140

Epoch 64/128

2292/2292 - 12s - 5ms/step - ia: 0.7843 - loss: 0.1695 - mae: 0.3199 - rmse: 0.4033 - smape: 0.6871 - val_ia: 0.2984 - val_loss: 0.3267 - val_mae: 0.4360 - val_rmse: 0.4827 - val_smape: 0.9000

Epoch 65/128

2292/2292 - 13s - 6ms/step - ia: 0.7865 - loss: 0.1677 - mae: 0.3171 - rmse: 0.4012 - smape: 0.6859 - val_ia: 0.2975 - val_loss: 0.3269 - val_mae: 0.4361 - val_rmse: 0.4828 - val_smape: 0.8992

Epoch 66/128

2292/2292 - 13s - 6ms/step - ia: 0.7862 - loss: 0.1668 - mae: 0.3164 - rmse: 0.3998 - smape: 0.6846 - val_ia: 0.3011 - val_loss: 0.3139 - val_mae: 0.4266 - val_rmse: 0.4735 - val_smape: 0.8853

Epoch 67/128

2292/2292 - 21s - 9ms/step - ia: 0.7860 - loss: 0.1666 - mae: 0.3163 - rmse: 0.3996 - smape: 0.6856 - val_ia: 0.3016 - val_loss: 0.3135 - val_mae: 0.4261 - val_rmse: 0.4733 - val_smape: 0.8836

Epoch 68/128

2292/2292 - 14s - 6ms/step - ia: 0.7879 - loss: 0.1643 - mae: 0.3138 - rmse: 0.3968 - smape: 0.6821 - val_ia: 0.3011 - val_loss: 0.3134 - val_mae: 0.4258 - val_rmse: 0.4727 - val_smape: 0.8825

Epoch 69/128

2292/2292 - 15s - 6ms/step - ia: 0.7883 - loss: 0.1639 - mae: 0.3134 - rmse: 0.3963 - smape: 0.6811 - val_ia: 0.3036 - val_loss: 0.3029 - val_mae: 0.4196 - val_rmse: 0.4660 - val_smape: 0.8737

Epoch 70/128

2292/2292 - 14s - 6ms/step - ia: 0.7884 - loss: 0.1643 - mae: 0.3138 - rmse: 0.3966 - smape: 0.6802 - val_ia: 0.3043 - val_loss: 0.3007 - val_mae: 0.4174 - val_rmse: 0.4639 - val_smape: 0.8711

Epoch 71/128

2292/2292 - 21s - 9ms/step - ia: 0.7899 - loss: 0.1624 - mae: 0.3113 - rmse: 0.3947 - smape: 0.6788 - val_ia: 0.3058 - val_loss: 0.2967 - val_mae: 0.4143 - val_rmse: 0.4609 - val_smape: 0.8662

Epoch 72/128

2292/2292 - 14s - 6ms/step - ia: 0.7905 - loss: 0.1615 - mae: 0.3105 - rmse: 0.3932 - smape: 0.6765 - val_ia: 0.3053 - val_loss: 0.2959 - val_mae: 0.4133 - val_rmse: 0.4602 - val_smape: 0.8661

Epoch 73/128

2292/2292 - 20s - 9ms/step - ia: 0.7909 - loss: 0.1608 - mae: 0.3106 - rmse: 0.3924 - smape: 0.6777 - val_ia: 0.3075 - val_loss: 0.2919 - val_mae: 0.4093 - val_rmse: 0.4564 - val_smape: 0.8582

Epoch 74/128

2292/2292 - 14s - 6ms/step - ia: 0.7922 - loss: 0.1594 - mae: 0.3083 - rmse: 0.3908 - smape: 0.6745 - val_ia: 0.3094 - val_loss: 0.2949 - val_mae: 0.4097 - val_rmse: 0.4569 - val_smape: 0.8534

Epoch 75/128

2292/2292 - 15s - 7ms/step - ia: 0.7922 - loss: 0.1583 - mae: 0.3083 - rmse: 0.3895 - smape: 0.6748 - val_ia: 0.3045 - val_loss: 0.3038 - val_mae: 0.4173 - val_rmse: 0.4644 - val_smape: 0.8683

Epoch 76/128

2292/2292 - 16s - 7ms/step - ia: 0.7914 - loss: 0.1592 - mae: 0.3093 - rmse: 0.3909 - smape: 0.6761 - val_ia: 0.3098 - val_loss: 0.2922 - val_mae: 0.4069 - val_rmse: 0.4544 - val_smape: 0.8521

Epoch 77/128

2292/2292 - 14s - 6ms/step - ia: 0.7921 - loss: 0.1582 - mae: 0.3080 - rmse: 0.3896 - smape: 0.6752 - val_ia: 0.3068 - val_loss: 0.2989 - val_mae: 0.4128 - val_rmse: 0.4599 - val_smape: 0.8625

Epoch 78/128

2292/2292 - 19s - 8ms/step - ia: 0.7936 - loss: 0.1572 - mae: 0.3066 - rmse: 0.3883 - smape: 0.6722 - val_ia: 0.3055 - val_loss: 0.3004 - val_mae: 0.4140 - val_rmse: 0.4613 - val_smape: 0.8651

Epoch 79/128

2292/2292 - 13s - 6ms/step - ia: 0.7944 - loss: 0.1564 - mae: 0.3055 - rmse: 0.3870 - smape: 0.6739 - val_ia: 0.3099 - val_loss: 0.2930 - val_mae: 0.4071 - val_rmse: 0.4544 - val_smape: 0.8477

Epoch 80/128

2292/2292 - 15s - 7ms/step - ia: 0.7941 - loss: 0.1560 - mae: 0.3054 - rmse: 0.3864 - smape: 0.6684 - val_ia: 0.3089 - val_loss: 0.2901 - val_mae: 0.4065 - val_rmse: 0.4533 - val_smape: 0.8498

Epoch 81/128

2292/2292 - 12s - 5ms/step - ia: 0.7957 - loss: 0.1542 - mae: 0.3034 - rmse: 0.3840 - smape: 0.6681 - val_ia: 0.3100 - val_loss: 0.2849 - val_mae: 0.4030 - val_rmse: 0.4498 - val_smape: 0.8476

Epoch 82/128

2292/2292 - 11s - 5ms/step - ia: 0.7954 - loss: 0.1541 - mae: 0.3031 - rmse: 0.3838 - smape: 0.6693 - val_ia: 0.3099 - val_loss: 0.2855 - val_mae: 0.4033 - val_rmse: 0.4500 - val_smape: 0.8460

Epoch 83/128

2292/2292 - 14s - 6ms/step - ia: 0.7967 - loss: 0.1526 - mae: 0.3025 - rmse: 0.3823 - smape: 0.6682 - val_ia: 0.3153 - val_loss: 0.2768 - val_mae: 0.3951 - val_rmse: 0.4418 - val_smape: 0.8294

Epoch 84/128

2292/2292 - 13s - 6ms/step - ia: 0.7962 - loss: 0.1532 - mae: 0.3024 - rmse: 0.3831 - smape: 0.6669 - val_ia: 0.3112 - val_loss: 0.2840 - val_mae: 0.4020 - val_rmse: 0.4486 - val_smape: 0.8421

Epoch 85/128

2292/2292 - 14s - 6ms/step - ia: 0.7971 - loss: 0.1525 - mae: 0.3008 - rmse: 0.3818 - smape: 0.6654 - val_ia: 0.3167 - val_loss: 0.2747 - val_mae: 0.3924 - val_rmse: 0.4396 - val_smape: 0.8224

Epoch 86/128

2292/2292 - 9s - 4ms/step - ia: 0.7965 - loss: 0.1525 - mae: 0.3015 - rmse: 0.3816 - smape: 0.6666 - val_ia: 0.3180 - val_loss: 0.2718 - val_mae: 0.3901 - val_rmse: 0.4369 - val_smape: 0.8209

Epoch 87/128

2292/2292 - 10s - 4ms/step - ia: 0.7992 - loss: 0.1499 - mae: 0.2992 - rmse: 0.3790 - smape: 0.6640 - val_ia: 0.3142 - val_loss: 0.2783 - val_mae: 0.3964 - val_rmse: 0.4429 - val_smape: 0.8332

Epoch 88/128

2292/2292 - 9s - 4ms/step - ia: 0.7993 - loss: 0.1494 - mae: 0.2981 - rmse: 0.3783 - smape: 0.6621 - val_ia: 0.3110 - val_loss: 0.2907 - val_mae: 0.4053 - val_rmse: 0.4522 - val_smape: 0.8404

Epoch 89/128

2292/2292 - 6s - 3ms/step - ia: 0.7990 - loss: 0.1502 - mae: 0.2983 - rmse: 0.3789 - smape: 0.6615 - val_ia: 0.3115 - val_loss: 0.2858 - val_mae: 0.4017 - val_rmse: 0.4485 - val_smape: 0.8408

Epoch 90/128

2292/2292 - 9s - 4ms/step - ia: 0.7986 - loss: 0.1508 - mae: 0.2993 - rmse: 0.3799 - smape: 0.6621 - val_ia: 0.3156 - val_loss: 0.2814 - val_mae: 0.3965 - val_rmse: 0.4435 - val_smape: 0.8269

Epoch 91/128

2292/2292 - 8s - 4ms/step - ia: 0.7996 - loss: 0.1490 - mae: 0.2975 - rmse: 0.3776 - smape: 0.6598 - val_ia: 0.3122 - val_loss: 0.2902 - val_mae: 0.4036 - val_rmse: 0.4506 - val_smape: 0.8410

Epoch 92/128

2292/2292 - 8s - 3ms/step - ia: 0.7989 - loss: 0.1497 - mae: 0.2978 - rmse: 0.3785 - smape: 0.6607 - val_ia: 0.3166 - val_loss: 0.2774 - val_mae: 0.3937 - val_rmse: 0.4405 - val_smape: 0.8236

Epoch 93/128

2292/2292 - 8s - 4ms/step - ia: 0.8005 - loss: 0.1485 - mae: 0.2966 - rmse: 0.3767 - smape: 0.6582 - val_ia: 0.3140 - val_loss: 0.2835 - val_mae: 0.3991 - val_rmse: 0.4459 - val_smape: 0.8321

Epoch 94/128

2292/2292 - 16s - 7ms/step - ia: 0.8014 - loss: 0.1473 - mae: 0.2953 - rmse: 0.3751 - smape: 0.6586 - val_ia: 0.3162 - val_loss: 0.2772 - val_mae: 0.3935 - val_rmse: 0.4404 - val_smape: 0.8215

Epoch 95/128

2292/2292 - 12s - 5ms/step - ia: 0.8022 - loss: 0.1458 - mae: 0.2942 - rmse: 0.3731 - smape: 0.6560 - val_ia: 0.3155 - val_loss: 0.2803 - val_mae: 0.3955 - val_rmse: 0.4426 - val_smape: 0.8260

Epoch 96/128

2292/2292 - 14s - 6ms/step - ia: 0.8011 - loss: 0.1465 - mae: 0.2950 - rmse: 0.3743 - smape: 0.6566 - val_ia: 0.3154 - val_loss: 0.2833 - val_mae: 0.3976 - val_rmse: 0.4444 - val_smape: 0.8261

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

144/144 - 13s - 90ms/step - ia: 0.5694 - loss: 0.6692 - mae: 0.6232 - rmse: 0.7865 - smape: 1.0456 - val_ia: 0.4956 - val_loss: 0.9704 - val_mae: 0.7944 - val_rmse: 0.9421 - val_smape: 1.1800

Epoch 2/256

144/144 - 2s - 12ms/step - ia: 0.6413 - loss: 0.4162 - mae: 0.5142 - rmse: 0.6442 - smape: 0.9251 - val_ia: 0.5488 - val_loss: 0.7642 - val_mae: 0.7054 - val_rmse: 0.8325 - val_smape: 1.1173

Epoch 3/256

144/144 - 1s - 8ms/step - ia: 0.6550 - loss: 0.3955 - mae: 0.4988 - rmse: 0.6285 - smape: 0.8995 - val_ia: 0.5428 - val_loss: 0.8095 - val_mae: 0.7352 - val_rmse: 0.8641 - val_smape: 1.1269

Epoch 4/256

144/144 - 1s - 7ms/step - ia: 0.6620 - loss: 0.3840 - mae: 0.4906 - rmse: 0.6189 - smape: 0.8909 - val_ia: 0.5390 - val_loss: 0.9566 - val_mae: 0.7764 - val_rmse: 0.9520 - val_smape: 1.0929

Epoch 5/256

144/144 - 1s - 9ms/step - ia: 0.6680 - loss: 0.3761 - mae: 0.4843 - rmse: 0.6123 - smape: 0.8774 - val_ia: 0.5432 - val_loss: 0.9134 - val_mae: 0.7677 - val_rmse: 0.9295 - val_smape: 1.1070

Epoch 6/256

144/144 - 1s - 7ms/step - ia: 0.6678 - loss: 0.3759 - mae: 0.4836 - rmse: 0.6130 - smape: 0.8833 - val_ia: 0.5839 - val_loss: 0.6571 - val_mae: 0.6464 - val_rmse: 0.7935 - val_smape: 1.0390

Epoch 7/256

144/144 - 1s - 9ms/step - ia: 0.6687 - loss: 0.3748 - mae: 0.4823 - rmse: 0.6117 - smape: 0.8782 - val_ia: 0.5709 - val_loss: 0.7140 - val_mae: 0.6910 - val_rmse: 0.8217 - val_smape: 1.0847

Epoch 8/256

144/144 - 1s - 7ms/step - ia: 0.6688 - loss: 0.3749 - mae: 0.4820 - rmse: 0.6118 - smape: 0.8824 - val_ia: 0.5868 - val_loss: 0.6212 - val_mae: 0.6445 - val_rmse: 0.7651 - val_smape: 1.0582

Epoch 9/256

144/144 - 1s - 9ms/step - ia: 0.6729 - loss: 0.3684 - mae: 0.4771 - rmse: 0.6062 - smape: 0.8737 - val_ia: 0.5648 - val_loss: 0.7530 - val_mae: 0.7129 - val_rmse: 0.8420 - val_smape: 1.0972

Epoch 10/256

144/144 - 1s - 6ms/step - ia: 0.6738 - loss: 0.3681 - mae: 0.4766 - rmse: 0.6060 - smape: 0.8740 - val_ia: 0.5800 - val_loss: 0.7000 - val_mae: 0.6711 - val_rmse: 0.8123 - val_smape: 1.0593

Epoch 11/256

144/144 - 1s - 8ms/step - ia: 0.6721 - loss: 0.3711 - mae: 0.4793 - rmse: 0.6081 - smape: 0.8747 - val_ia: 0.5767 - val_loss: 0.7205 - val_mae: 0.6746 - val_rmse: 0.8324 - val_smape: 1.0479

Epoch 12/256

144/144 - 1s - 10ms/step - ia: 0.6718 - loss: 0.3724 - mae: 0.4789 - rmse: 0.6090 - smape: 0.8703 - val_ia: 0.5551 - val_loss: 0.7761 - val_mae: 0.7229 - val_rmse: 0.8551 - val_smape: 1.1138

Epoch 13/256

144/144 - 2s - 11ms/step - ia: 0.6724 - loss: 0.3707 - mae: 0.4787 - rmse: 0.6075 - smape: 0.8733 - val_ia: 0.5454 - val_loss: 0.8965 - val_mae: 0.7705 - val_rmse: 0.9182 - val_smape: 1.1149

Epoch 14/256

144/144 - 2s - 13ms/step - ia: 0.6736 - loss: 0.3681 - mae: 0.4763 - rmse: 0.6057 - smape: 0.8727 - val_ia: 0.5344 - val_loss: 0.9485 - val_mae: 0.7984 - val_rmse: 0.9476 - val_smape: 1.1326

Epoch 15/256

144/144 - 2s - 13ms/step - ia: 0.6732 - loss: 0.3682 - mae: 0.4767 - rmse: 0.6068 - smape: 0.8751 - val_ia: 0.5517 - val_loss: 0.8129 - val_mae: 0.7481 - val_rmse: 0.8713 - val_smape: 1.1306

Epoch 16/256

144/144 - 2s - 11ms/step - ia: 0.6726 - loss: 0.3696 - mae: 0.4775 - rmse: 0.6075 - smape: 0.8751 - val_ia: 0.5610 - val_loss: 0.7484 - val_mae: 0.7154 - val_rmse: 0.8399 - val_smape: 1.1088

Epoch 17/256

144/144 - 3s - 17ms/step - ia: 0.6737 - loss: 0.3683 - mae: 0.4767 - rmse: 0.6066 - smape: 0.8726 - val_ia: 0.5520 - val_loss: 0.8453 - val_mae: 0.7558 - val_rmse: 0.8954 - val_smape: 1.1089

Epoch 18/256

144/144 - 2s - 11ms/step - ia: 0.6715 - loss: 0.3701 - mae: 0.4781 - rmse: 0.6084 - smape: 0.8753 - val_ia: 0.5459 - val_loss: 0.7698 - val_mae: 0.7295 - val_rmse: 0.8461 - val_smape: 1.1436

Epoch 19/256

144/144 - 1s - 10ms/step - ia: 0.6763 - loss: 0.3628 - mae: 0.4736 - rmse: 0.6013 - smape: 0.8687 - val_ia: 0.5572 - val_loss: 0.8143 - val_mae: 0.7395 - val_rmse: 0.8750 - val_smape: 1.1075

Epoch 20/256

144/144 - 1s - 9ms/step - ia: 0.6751 - loss: 0.3653 - mae: 0.4746 - rmse: 0.6039 - smape: 0.8722 - val_ia: 0.5381 - val_loss: 0.8713 - val_mae: 0.7841 - val_rmse: 0.9041 - val_smape: 1.1483

Epoch 21/256

144/144 - 2s - 12ms/step - ia: 0.6743 - loss: 0.3682 - mae: 0.4762 - rmse: 0.6066 - smape: 0.8710 - val_ia: 0.5471 - val_loss: 0.8796 - val_mae: 0.7693 - val_rmse: 0.9082 - val_smape: 1.1220

Epoch 22/256

144/144 - 3s - 20ms/step - ia: 0.6733 - loss: 0.3701 - mae: 0.4775 - rmse: 0.6068 - smape: 0.8734 - val_ia: 0.5437 - val_loss: 0.8486 - val_mae: 0.7635 - val_rmse: 0.8968 - val_smape: 1.1337

Epoch 23/256

144/144 - 3s - 18ms/step - ia: 0.6745 - loss: 0.3661 - mae: 0.4756 - rmse: 0.6041 - smape: 0.8737 - val_ia: 0.5597 - val_loss: 0.7893 - val_mae: 0.7349 - val_rmse: 0.8667 - val_smape: 1.1028

Epoch 23: early stopping

Restoring model weights from the end of the best epoch: 8.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:25 530ms/step
  3/163 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 74%|███████▍  | 37/50 [3:56:46<2:17:35, 635.04s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

573/573 - 19s - 32ms/step - ia: 0.6622 - loss: 0.4140 - mae: 0.5086 - rmse: 0.6363 - smape: 0.9015 - val_ia: 0.4491 - val_loss: 0.9215 - val_mae: 0.7240 - val_rmse: 0.8500 - val_smape: 1.1765

Epoch 2/8

573/573 - 9s - 15ms/step - ia: 0.7285 - loss: 0.2791 - mae: 0.4159 - rmse: 0.5260 - smape: 0.7988 - val_ia: 0.4779 - val_loss: 0.7446 - val_mae: 0.6373 - val_rmse: 0.7675 - val_smape: 1.0852

Epoch 3/8

573/573 - 7s - 12ms/step - ia: 0.7525 - loss: 0.2411 - mae: 0.3827 - rmse: 0.4882 - smape: 0.7548 - val_ia: 0.4994 - val_loss: 0.6748 - val_mae: 0.6022 - val_rmse: 0.7246 - val_smape: 1.0481

Epoch 4/8

573/573 - 7s - 12ms/step - ia: 0.7657 - loss: 0.2186 - mae: 0.3633 - rmse: 0.4652 - smape: 0.7297 - val_ia: 0.5207 - val_loss: 0.6476 - val_mae: 0.5869 - val_rmse: 0.7032 - val_smape: 1.0230

Epoch 5/8

573/573 - 3s - 5ms/step - ia: 0.7770 - loss: 0.2012 - mae: 0.3470 - rmse: 0.4462 - smape: 0.7121 - val_ia: 0.5536 - val_loss: 0.5180 - val_mae: 0.5253 - val_rmse: 0.6321 - val_smape: 0.9623

Epoch 6/8

573/573 - 6s - 11ms/step - ia: 0.7856 - loss: 0.1867 - mae: 0.3341 - rmse: 0.4297 - smape: 0.6974 - val_ia: 0.5481 - val_loss: 0.5631 - val_mae: 0.5407 - val_rmse: 0.6478 - val_smape: 0.9835

Epoch 7/8

573/573 - 6s - 10ms/step - ia: 0.7914 - loss: 0.1775 - mae: 0.3258 - rmse: 0.4191 - smape: 0.6885 - val_ia: 0.5756 - val_loss: 0.4896 - val_mae: 0.4989 - val_rmse: 0.6044 - val_smape: 0.9250

Epoch 8/8

573/573 - 4s - 7ms/step - ia: 0.7987 - loss: 0.1666 - mae: 0.3151 - rmse: 0.4060 - smape: 0.6746 - val_ia: 0.5728 - val_loss: 0.5210 - val_mae: 0.5185 - val_rmse: 0.6189 - val_smape: 0.9481

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:14 832ms/step
  2/163 ━━━━━━━━━━━━━━━━━━━━ 15s 95ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 19/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 76%|███████▌  | 38/50 [3:57:53<1:32:54, 464.58s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 27s - 12ms/step - ia: 0.2961 - loss: 1.6854 - mae: 1.0506 - rmse: 1.2812 - smape: 1.4468 - val_ia: 0.1902 - val_loss: 0.8350 - val_mae: 0.7521 - val_rmse: 0.7916 - val_smape: 1.4615

Epoch 2/128

2292/2292 - 11s - 5ms/step - ia: 0.2992 - loss: 1.6509 - mae: 1.0385 - rmse: 1.2682 - smape: 1.4428 - val_ia: 0.1907 - val_loss: 0.8322 - val_mae: 0.7528 - val_rmse: 0.7919 - val_smape: 1.5110

Epoch 3/128

2292/2292 - 8s - 4ms/step - ia: 0.2976 - loss: 1.6295 - mae: 1.0337 - rmse: 1.2591 - smape: 1.4449 - val_ia: 0.1896 - val_loss: 0.8315 - val_mae: 0.7539 - val_rmse: 0.7927 - val_smape: 1.5595

Epoch 4/128

2292/2292 - 10s - 4ms/step - ia: 0.2902 - loss: 1.6460 - mae: 1.0406 - rmse: 1.2661 - smape: 1.4544 - val_ia: 0.1884 - val_loss: 0.8320 - val_mae: 0.7553 - val_rmse: 0.7939 - val_smape: 1.6068

Epoch 5/128

2292/2292 - 10s - 4ms/step - ia: 0.2963 - loss: 1.6057 - mae: 1.0280 - rmse: 1.2503 - smape: 1.4462 - val_ia: 0.1867 - val_loss: 0.8333 - val_mae: 0.7568 - val_rmse: 0.7951 - val_smape: 1.6516

Epoch 6/128

2292/2292 - 10s - 5ms/step - ia: 0.2939 - loss: 1.5920 - mae: 1.0243 - rmse: 1.2451 - smape: 1.4485 - val_ia: 0.1860 - val_loss: 0.8349 - val_mae: 0.7583 - val_rmse: 0.7963 - val_smape: 1.6949

Epoch 7/128

2292/2292 - 10s - 4ms/step - ia: 0.2996 - loss: 1.5662 - mae: 1.0135 - rmse: 1.2354 - smape: 1.4401 - val_ia: 0.1851 - val_loss: 0.8364 - val_mae: 0.7595 - val_rmse: 0.7974 - val_smape: 1.7339

Epoch 8/128

2292/2292 - 14s - 6ms/step - ia: 0.2956 - loss: 1.5724 - mae: 1.0182 - rmse: 1.2374 - smape: 1.4471 - val_ia: 0.1841 - val_loss: 0.8382 - val_mae: 0.7608 - val_rmse: 0.7985 - val_smape: 1.7750

Epoch 9/128

2292/2292 - 16s - 7ms/step - ia: 0.2964 - loss: 1.5455 - mae: 1.0098 - rmse: 1.2276 - smape: 1.4482 - val_ia: 0.1832 - val_loss: 0.8393 - val_mae: 0.7615 - val_rmse: 0.7992 - val_smape: 1.8072

Epoch 10/128

2292/2292 - 13s - 6ms/step - ia: 0.2923 - loss: 1.5567 - mae: 1.0138 - rmse: 1.2315 - smape: 1.4504 - val_ia: 0.1821 - val_loss: 0.8408 - val_mae: 0.7625 - val_rmse: 0.8000 - val_smape: 1.8312

Epoch 11/128

2292/2292 - 8s - 4ms/step - ia: 0.2940 - loss: 1.5394 - mae: 1.0082 - rmse: 1.2253 - smape: 1.4497 - val_ia: 0.1814 - val_loss: 0.8416 - val_mae: 0.7630 - val_rmse: 0.8005 - val_smape: 1.8411

Epoch 12/128

2292/2292 - 8s - 4ms/step - ia: 0.2946 - loss: 1.5327 - mae: 1.0045 - rmse: 1.2215 - smape: 1.4459 - val_ia: 0.1807 - val_loss: 0.8424 - val_mae: 0.7635 - val_rmse: 0.8009 - val_smape: 1.8483

Epoch 13/128

2292/2292 - 13s - 6ms/step - ia: 0.2932 - loss: 1.5233 - mae: 1.0047 - rmse: 1.2177 - smape: 1.4527 - val_ia: 0.1803 - val_loss: 0.8427 - val_mae: 0.7637 - val_rmse: 0.8011 - val_smape: 1.8505

Epoch 14/128

2292/2292 - 9s - 4ms/step - ia: 0.2908 - loss: 1.5156 - mae: 1.0040 - rmse: 1.2145 - smape: 1.4593 - val_ia: 0.1798 - val_loss: 0.8432 - val_mae: 0.7640 - val_rmse: 0.8013 - val_smape: 1.8505

Epoch 15/128

2292/2292 - 11s - 5ms/step - ia: 0.2949 - loss: 1.4867 - mae: 0.9932 - rmse: 1.2038 - smape: 1.4486 - val_ia: 0.1794 - val_loss: 0.8434 - val_mae: 0.7642 - val_rmse: 0.8015 - val_smape: 1.8482

Epoch 16/128

2292/2292 - 23s - 10ms/step - ia: 0.2958 - loss: 1.4843 - mae: 0.9907 - rmse: 1.2028 - smape: 1.4467 - val_ia: 0.1792 - val_loss: 0.8434 - val_mae: 0.7642 - val_rmse: 0.8015 - val_smape: 1.8450

Epoch 17/128

2292/2292 - 12s - 5ms/step - ia: 0.2934 - loss: 1.4760 - mae: 0.9908 - rmse: 1.1998 - smape: 1.4547 - val_ia: 0.1790 - val_loss: 0.8433 - val_mae: 0.7642 - val_rmse: 0.8014 - val_smape: 1.8412

Epoch 18/128

2292/2292 - 19s - 8ms/step - ia: 0.2948 - loss: 1.4656 - mae: 0.9870 - rmse: 1.1957 - smape: 1.4478 - val_ia: 0.1789 - val_loss: 0.8428 - val_mae: 0.7640 - val_rmse: 0.8012 - val_smape: 1.8371

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:24 520ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 78%|███████▊  | 39/50 [4:01:51<1:12:43, 396.71s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 24s - 21ms/step - ia: 0.3122 - loss: 2.5147 - mae: 1.2638 - rmse: 1.5725 - smape: 1.4506 - val_ia: 0.2093 - val_loss: 1.2737 - val_mae: 0.9204 - val_rmse: 1.0830 - val_smape: 1.2072

Epoch 2/128

1146/1146 - 9s - 8ms/step - ia: 0.3373 - loss: 1.7841 - mae: 1.0772 - rmse: 1.3270 - smape: 1.4129 - val_ia: 0.2168 - val_loss: 1.0149 - val_mae: 0.8316 - val_rmse: 0.9668 - val_smape: 1.2466

Epoch 3/128

1146/1146 - 6s - 5ms/step - ia: 0.3466 - loss: 1.4249 - mae: 0.9727 - rmse: 1.1859 - smape: 1.4001 - val_ia: 0.2228 - val_loss: 0.8371 - val_mae: 0.7620 - val_rmse: 0.8698 - val_smape: 1.2929

Epoch 4/128

1146/1146 - 5s - 5ms/step - ia: 0.3623 - loss: 1.1885 - mae: 0.8933 - rmse: 1.0836 - smape: 1.3827 - val_ia: 0.2298 - val_loss: 0.7097 - val_mae: 0.7056 - val_rmse: 0.7913 - val_smape: 1.3034

Epoch 5/128

1146/1146 - 6s - 5ms/step - ia: 0.3859 - loss: 1.0195 - mae: 0.8296 - rmse: 1.0038 - smape: 1.3570 - val_ia: 0.2427 - val_loss: 0.6361 - val_mae: 0.6686 - val_rmse: 0.7418 - val_smape: 1.2770

Epoch 6/128

1146/1146 - 6s - 5ms/step - ia: 0.4037 - loss: 0.9085 - mae: 0.7856 - rmse: 0.9477 - smape: 1.3352 - val_ia: 0.2615 - val_loss: 0.6095 - val_mae: 0.6500 - val_rmse: 0.7200 - val_smape: 1.2537

Epoch 7/128

1146/1146 - 5s - 5ms/step - ia: 0.4254 - loss: 0.8329 - mae: 0.7498 - rmse: 0.9077 - smape: 1.2998 - val_ia: 0.2833 - val_loss: 0.6076 - val_mae: 0.6396 - val_rmse: 0.7133 - val_smape: 1.2289

Epoch 8/128

1146/1146 - 4s - 3ms/step - ia: 0.4484 - loss: 0.7661 - mae: 0.7182 - rmse: 0.8705 - smape: 1.2647 - val_ia: 0.2988 - val_loss: 0.6326 - val_mae: 0.6431 - val_rmse: 0.7229 - val_smape: 1.2143

Epoch 9/128

1146/1146 - 5s - 4ms/step - ia: 0.4647 - loss: 0.7240 - mae: 0.6958 - rmse: 0.8461 - smape: 1.2294 - val_ia: 0.3042 - val_loss: 0.6686 - val_mae: 0.6564 - val_rmse: 0.7396 - val_smape: 1.2112

Epoch 10/128

1146/1146 - 5s - 4ms/step - ia: 0.4829 - loss: 0.6802 - mae: 0.6740 - rmse: 0.8200 - smape: 1.2025 - val_ia: 0.3037 - val_loss: 0.7041 - val_mae: 0.6724 - val_rmse: 0.7568 - val_smape: 1.2086

Epoch 11/128

1146/1146 - 5s - 4ms/step - ia: 0.4945 - loss: 0.6567 - mae: 0.6601 - rmse: 0.8053 - smape: 1.1798 - val_ia: 0.2998 - val_loss: 0.7430 - val_mae: 0.6920 - val_rmse: 0.7763 - val_smape: 1.2146

Epoch 12/128

1146/1146 - 5s - 4ms/step - ia: 0.5014 - loss: 0.6440 - mae: 0.6537 - rmse: 0.7976 - smape: 1.1681 - val_ia: 0.2957 - val_loss: 0.7792 - val_mae: 0.7112 - val_rmse: 0.7942 - val_smape: 1.2226

Epoch 13/128

1146/1146 - 5s - 4ms/step - ia: 0.5131 - loss: 0.6176 - mae: 0.6384 - rmse: 0.7811 - smape: 1.1431 - val_ia: 0.2919 - val_loss: 0.8089 - val_mae: 0.7266 - val_rmse: 0.8083 - val_smape: 1.2220

Epoch 14/128

1146/1146 - 3s - 3ms/step - ia: 0.5234 - loss: 0.6007 - mae: 0.6276 - rmse: 0.7703 - smape: 1.1266 - val_ia: 0.2889 - val_loss: 0.8316 - val_mae: 0.7383 - val_rmse: 0.8187 - val_smape: 1.2231

Epoch 15/128

1146/1146 - 5s - 5ms/step - ia: 0.5278 - loss: 0.5899 - mae: 0.6220 - rmse: 0.7633 - smape: 1.1175 - val_ia: 0.2861 - val_loss: 0.8588 - val_mae: 0.7523 - val_rmse: 0.8313 - val_smape: 1.2268

Epoch 16/128

1146/1146 - 3s - 2ms/step - ia: 0.5345 - loss: 0.5831 - mae: 0.6164 - rmse: 0.7590 - smape: 1.1016 - val_ia: 0.2845 - val_loss: 0.8724 - val_mae: 0.7591 - val_rmse: 0.8369 - val_smape: 1.2263

Epoch 17/128

1146/1146 - 4s - 3ms/step - ia: 0.5399 - loss: 0.5716 - mae: 0.6099 - rmse: 0.7513 - smape: 1.0955 - val_ia: 0.2824 - val_loss: 0.8941 - val_mae: 0.7686 - val_rmse: 0.8458 - val_smape: 1.2246

Epoch 18/128

1146/1146 - 5s - 5ms/step - ia: 0.5442 - loss: 0.5673 - mae: 0.6062 - rmse: 0.7478 - smape: 1.0879 - val_ia: 0.2807 - val_loss: 0.9089 - val_mae: 0.7783 - val_rmse: 0.8537 - val_smape: 1.2352

Epoch 19/128

1146/1146 - 6s - 5ms/step - ia: 0.5493 - loss: 0.5563 - mae: 0.5993 - rmse: 0.7409 - smape: 1.0744 - val_ia: 0.2796 - val_loss: 0.9223 - val_mae: 0.7846 - val_rmse: 0.8592 - val_smape: 1.2367

Epoch 20/128

1146/1146 - 5s - 4ms/step - ia: 0.5510 - loss: 0.5553 - mae: 0.5975 - rmse: 0.7401 - smape: 1.0709 - val_ia: 0.2788 - val_loss: 0.9311 - val_mae: 0.7879 - val_rmse: 0.8621 - val_smape: 1.2336

Epoch 21/128

1146/1146 - 4s - 4ms/step - ia: 0.5505 - loss: 0.5542 - mae: 0.5990 - rmse: 0.7392 - smape: 1.0741 - val_ia: 0.2786 - val_loss: 0.9349 - val_mae: 0.7899 - val_rmse: 0.8634 - val_smape: 1.2333

Epoch 22/128

1146/1146 - 4s - 3ms/step - ia: 0.5558 - loss: 0.5458 - mae: 0.5925 - rmse: 0.7338 - smape: 1.0625 - val_ia: 0.2778 - val_loss: 0.9467 - val_mae: 0.7941 - val_rmse: 0.8675 - val_smape: 1.2304

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 38s 236ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 80%|████████  | 40/50 [4:04:03<52:52, 317.30s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

144/144 - 6s - 45ms/step - ia: 0.5046 - loss: 0.8499 - mae: 0.7300 - rmse: 0.9066 - smape: 1.1520 - val_ia: 0.4082 - val_loss: 1.3838 - val_mae: 1.0096 - val_rmse: 1.1394 - val_smape: 1.3824

Epoch 2/64

144/144 - 1s - 5ms/step - ia: 0.5722 - loss: 0.6387 - mae: 0.6389 - rmse: 0.7989 - smape: 1.0414 - val_ia: 0.4046 - val_loss: 1.5074 - val_mae: 1.0478 - val_rmse: 1.1788 - val_smape: 1.3892

Epoch 3/64

144/144 - 1s - 8ms/step - ia: 0.5811 - loss: 0.6158 - mae: 0.6265 - rmse: 0.7840 - smape: 1.0282 - val_ia: 0.4069 - val_loss: 1.5016 - val_mae: 1.0432 - val_rmse: 1.1748 - val_smape: 1.3845

Epoch 4/64

144/144 - 1s - 5ms/step - ia: 0.5877 - loss: 0.5928 - mae: 0.6154 - rmse: 0.7694 - smape: 1.0168 - val_ia: 0.4155 - val_loss: 1.4110 - val_mae: 1.0044 - val_rmse: 1.1383 - val_smape: 1.3614

Epoch 5/64

144/144 - 1s - 6ms/step - ia: 0.5960 - loss: 0.5708 - mae: 0.6037 - rmse: 0.7548 - smape: 1.0023 - val_ia: 0.4148 - val_loss: 1.4186 - val_mae: 1.0094 - val_rmse: 1.1421 - val_smape: 1.3664

Epoch 6/64

144/144 - 1s - 9ms/step - ia: 0.6018 - loss: 0.5540 - mae: 0.5948 - rmse: 0.7441 - smape: 0.9938 - val_ia: 0.4201 - val_loss: 1.3681 - val_mae: 0.9874 - val_rmse: 1.1214 - val_smape: 1.3549

Epoch 7/64

144/144 - 1s - 6ms/step - ia: 0.6118 - loss: 0.5302 - mae: 0.5808 - rmse: 0.7269 - smape: 0.9785 - val_ia: 0.4205 - val_loss: 1.3495 - val_mae: 0.9840 - val_rmse: 1.1126 - val_smape: 1.3606

Epoch 8/64

144/144 - 1s - 9ms/step - ia: 0.6173 - loss: 0.5093 - mae: 0.5707 - rmse: 0.7129 - smape: 0.9695 - val_ia: 0.4288 - val_loss: 1.3067 - val_mae: 0.9595 - val_rmse: 1.0945 - val_smape: 1.3379

Epoch 9/64

144/144 - 2s - 11ms/step - ia: 0.6235 - loss: 0.4947 - mae: 0.5621 - rmse: 0.7024 - smape: 0.9609 - val_ia: 0.4257 - val_loss: 1.3379 - val_mae: 0.9736 - val_rmse: 1.1074 - val_smape: 1.3483

Epoch 10/64

144/144 - 1s - 5ms/step - ia: 0.6305 - loss: 0.4746 - mae: 0.5514 - rmse: 0.6877 - smape: 0.9495 - val_ia: 0.4317 - val_loss: 1.2858 - val_mae: 0.9499 - val_rmse: 1.0847 - val_smape: 1.3364

Epoch 11/64

144/144 - 1s - 5ms/step - ia: 0.6337 - loss: 0.4657 - mae: 0.5464 - rmse: 0.6822 - smape: 0.9425 - val_ia: 0.4381 - val_loss: 1.2521 - val_mae: 0.9312 - val_rmse: 1.0685 - val_smape: 1.3223

Epoch 12/64

144/144 - 1s - 7ms/step - ia: 0.6427 - loss: 0.4458 - mae: 0.5334 - rmse: 0.6670 - smape: 0.9277 - val_ia: 0.4421 - val_loss: 1.2111 - val_mae: 0.9159 - val_rmse: 1.0487 - val_smape: 1.3203

Epoch 13/64

144/144 - 1s - 8ms/step - ia: 0.6458 - loss: 0.4381 - mae: 0.5290 - rmse: 0.6614 - smape: 0.9249 - val_ia: 0.4387 - val_loss: 1.2496 - val_mae: 0.9308 - val_rmse: 1.0650 - val_smape: 1.3272

Epoch 14/64

144/144 - 1s - 6ms/step - ia: 0.6534 - loss: 0.4224 - mae: 0.5183 - rmse: 0.6485 - smape: 0.9135 - val_ia: 0.4448 - val_loss: 1.2100 - val_mae: 0.9078 - val_rmse: 1.0474 - val_smape: 1.3099

Epoch 15/64

144/144 - 1s - 4ms/step - ia: 0.6572 - loss: 0.4119 - mae: 0.5125 - rmse: 0.6409 - smape: 0.9056 - val_ia: 0.4487 - val_loss: 1.1958 - val_mae: 0.8971 - val_rmse: 1.0403 - val_smape: 1.3006

Epoch 16/64

144/144 - 2s - 15ms/step - ia: 0.6642 - loss: 0.3984 - mae: 0.5031 - rmse: 0.6306 - smape: 0.8963 - val_ia: 0.4532 - val_loss: 1.1482 - val_mae: 0.8785 - val_rmse: 1.0153 - val_smape: 1.2994

Epoch 17/64

144/144 - 2s - 13ms/step - ia: 0.6673 - loss: 0.3902 - mae: 0.4988 - rmse: 0.6247 - smape: 0.8915 - val_ia: 0.4532 - val_loss: 1.1669 - val_mae: 0.8814 - val_rmse: 1.0244 - val_smape: 1.2948

Epoch 18/64

144/144 - 2s - 16ms/step - ia: 0.6712 - loss: 0.3838 - mae: 0.4936 - rmse: 0.6188 - smape: 0.8853 - val_ia: 0.4608 - val_loss: 1.1236 - val_mae: 0.8560 - val_rmse: 1.0042 - val_smape: 1.2776

Epoch 19/64

144/144 - 1s - 6ms/step - ia: 0.6760 - loss: 0.3727 - mae: 0.4863 - rmse: 0.6098 - smape: 0.8774 - val_ia: 0.4601 - val_loss: 1.1425 - val_mae: 0.8665 - val_rmse: 1.0116 - val_smape: 1.2830

Epoch 20/64

144/144 - 1s - 5ms/step - ia: 0.6813 - loss: 0.3661 - mae: 0.4803 - rmse: 0.6042 - smape: 0.8705 - val_ia: 0.4643 - val_loss: 1.0924 - val_mae: 0.8421 - val_rmse: 0.9872 - val_smape: 1.2747

Epoch 21/64

144/144 - 1s - 8ms/step - ia: 0.6852 - loss: 0.3578 - mae: 0.4751 - rmse: 0.5972 - smape: 0.8650 - val_ia: 0.4672 - val_loss: 1.0734 - val_mae: 0.8340 - val_rmse: 0.9765 - val_smape: 1.2720

Epoch 22/64

144/144 - 1s - 4ms/step - ia: 0.6894 - loss: 0.3498 - mae: 0.4689 - rmse: 0.5907 - smape: 0.8587 - val_ia: 0.4686 - val_loss: 1.0761 - val_mae: 0.8312 - val_rmse: 0.9780 - val_smape: 1.2678

Epoch 23/64

144/144 - 1s - 4ms/step - ia: 0.6903 - loss: 0.3478 - mae: 0.4678 - rmse: 0.5893 - smape: 0.8555 - val_ia: 0.4729 - val_loss: 1.0570 - val_mae: 0.8196 - val_rmse: 0.9693 - val_smape: 1.2572

Epoch 24/64

144/144 - 1s - 4ms/step - ia: 0.6955 - loss: 0.3394 - mae: 0.4615 - rmse: 0.5819 - smape: 0.8496 - val_ia: 0.4787 - val_loss: 1.0055 - val_mae: 0.7956 - val_rmse: 0.9445 - val_smape: 1.2463

Epoch 25/64

144/144 - 1s - 5ms/step - ia: 0.6985 - loss: 0.3337 - mae: 0.4574 - rmse: 0.5769 - smape: 0.8435 - val_ia: 0.4797 - val_loss: 1.0085 - val_mae: 0.7932 - val_rmse: 0.9467 - val_smape: 1.2412

Epoch 26/64

144/144 - 1s - 5ms/step - ia: 0.7002 - loss: 0.3304 - mae: 0.4549 - rmse: 0.5742 - smape: 0.8426 - val_ia: 0.4805 - val_loss: 1.0071 - val_mae: 0.7891 - val_rmse: 0.9468 - val_smape: 1.2364

Epoch 27/64

144/144 - 1s - 6ms/step - ia: 0.7033 - loss: 0.3248 - mae: 0.4513 - rmse: 0.5684 - smape: 0.8383 - val_ia: 0.4869 - val_loss: 0.9609 - val_mae: 0.7693 - val_rmse: 0.9230 - val_smape: 1.2277

Epoch 28/64

144/144 - 1s - 5ms/step - ia: 0.7063 - loss: 0.3195 - mae: 0.4468 - rmse: 0.5645 - smape: 0.8338 - val_ia: 0.4893 - val_loss: 0.9508 - val_mae: 0.7630 - val_rmse: 0.9182 - val_smape: 1.2211

Epoch 29/64

144/144 - 1s - 4ms/step - ia: 0.7099 - loss: 0.3152 - mae: 0.4425 - rmse: 0.5609 - smape: 0.8269 - val_ia: 0.4900 - val_loss: 0.9531 - val_mae: 0.7616 - val_rmse: 0.9197 - val_smape: 1.2190

Epoch 30/64

144/144 - 0s - 3ms/step - ia: 0.7119 - loss: 0.3100 - mae: 0.4392 - rmse: 0.5560 - smape: 0.8229 - val_ia: 0.4951 - val_loss: 0.9232 - val_mae: 0.7440 - val_rmse: 0.9069 - val_smape: 1.2039

Epoch 31/64

144/144 - 1s - 6ms/step - ia: 0.7132 - loss: 0.3093 - mae: 0.4382 - rmse: 0.5553 - smape: 0.8239 - val_ia: 0.4889 - val_loss: 0.9602 - val_mae: 0.7616 - val_rmse: 0.9237 - val_smape: 1.2175

Epoch 32/64

144/144 - 1s - 4ms/step - ia: 0.7142 - loss: 0.3060 - mae: 0.4364 - rmse: 0.5525 - smape: 0.8214 - val_ia: 0.4951 - val_loss: 0.9211 - val_mae: 0.7428 - val_rmse: 0.9045 - val_smape: 1.2053

Epoch 33/64

144/144 - 1s - 4ms/step - ia: 0.7177 - loss: 0.3018 - mae: 0.4328 - rmse: 0.5484 - smape: 0.8142 - val_ia: 0.4977 - val_loss: 0.8968 - val_mae: 0.7300 - val_rmse: 0.8923 - val_smape: 1.1970

Epoch 34/64

144/144 - 1s - 4ms/step - ia: 0.7190 - loss: 0.2982 - mae: 0.4299 - rmse: 0.5456 - smape: 0.8114 - val_ia: 0.4997 - val_loss: 0.8994 - val_mae: 0.7279 - val_rmse: 0.8943 - val_smape: 1.1916

Epoch 35/64

144/144 - 1s - 5ms/step - ia: 0.7204 - loss: 0.2965 - mae: 0.4282 - rmse: 0.5439 - smape: 0.8127 - val_ia: 0.5017 - val_loss: 0.8766 - val_mae: 0.7221 - val_rmse: 0.8805 - val_smape: 1.1919

Epoch 36/64

144/144 - 1s - 4ms/step - ia: 0.7239 - loss: 0.2909 - mae: 0.4235 - rmse: 0.5390 - smape: 0.8037 - val_ia: 0.5014 - val_loss: 0.8810 - val_mae: 0.7226 - val_rmse: 0.8833 - val_smape: 1.1932

Epoch 37/64

144/144 - 1s - 4ms/step - ia: 0.7247 - loss: 0.2885 - mae: 0.4225 - rmse: 0.5359 - smape: 0.8035 - val_ia: 0.5065 - val_loss: 0.8642 - val_mae: 0.7101 - val_rmse: 0.8767 - val_smape: 1.1777

Epoch 38/64

144/144 - 1s - 4ms/step - ia: 0.7252 - loss: 0.2872 - mae: 0.4220 - rmse: 0.5350 - smape: 0.8041 - val_ia: 0.5063 - val_loss: 0.8738 - val_mae: 0.7154 - val_rmse: 0.8802 - val_smape: 1.1808

Epoch 39/64

144/144 - 1s - 4ms/step - ia: 0.7282 - loss: 0.2830 - mae: 0.4171 - rmse: 0.5314 - smape: 0.7958 - val_ia: 0.5049 - val_loss: 0.8814 - val_mae: 0.7167 - val_rmse: 0.8850 - val_smape: 1.1805

Epoch 40/64

144/144 - 1s - 4ms/step - ia: 0.7290 - loss: 0.2802 - mae: 0.4163 - rmse: 0.5288 - smape: 0.7982 - val_ia: 0.5102 - val_loss: 0.8478 - val_mae: 0.6984 - val_rmse: 0.8706 - val_smape: 1.1634

Epoch 41/64

144/144 - 1s - 4ms/step - ia: 0.7301 - loss: 0.2794 - mae: 0.4154 - rmse: 0.5281 - smape: 0.7959 - val_ia: 0.5107 - val_loss: 0.8406 - val_mae: 0.6977 - val_rmse: 0.8652 - val_smape: 1.1669

Epoch 42/64

144/144 - 1s - 4ms/step - ia: 0.7301 - loss: 0.2790 - mae: 0.4148 - rmse: 0.5278 - smape: 0.7955 - val_ia: 0.5131 - val_loss: 0.8350 - val_mae: 0.6970 - val_rmse: 0.8605 - val_smape: 1.1674

Epoch 43/64

144/144 - 1s - 5ms/step - ia: 0.7325 - loss: 0.2755 - mae: 0.4118 - rmse: 0.5252 - smape: 0.7909 - val_ia: 0.5154 - val_loss: 0.7994 - val_mae: 0.6820 - val_rmse: 0.8427 - val_smape: 1.1609

Epoch 44/64

144/144 - 1s - 5ms/step - ia: 0.7340 - loss: 0.2730 - mae: 0.4098 - rmse: 0.5217 - smape: 0.7900 - val_ia: 0.5134 - val_loss: 0.8253 - val_mae: 0.6913 - val_rmse: 0.8574 - val_smape: 1.1622

Epoch 45/64

144/144 - 1s - 5ms/step - ia: 0.7349 - loss: 0.2694 - mae: 0.4079 - rmse: 0.5183 - smape: 0.7861 - val_ia: 0.5174 - val_loss: 0.8175 - val_mae: 0.6865 - val_rmse: 0.8530 - val_smape: 1.1568

Epoch 46/64

144/144 - 1s - 6ms/step - ia: 0.7359 - loss: 0.2690 - mae: 0.4072 - rmse: 0.5185 - smape: 0.7848 - val_ia: 0.5166 - val_loss: 0.8236 - val_mae: 0.6900 - val_rmse: 0.8565 - val_smape: 1.1582

Epoch 47/64

144/144 - 1s - 7ms/step - ia: 0.7369 - loss: 0.2670 - mae: 0.4055 - rmse: 0.5159 - smape: 0.7838 - val_ia: 0.5213 - val_loss: 0.7714 - val_mae: 0.6653 - val_rmse: 0.8295 - val_smape: 1.1454

Epoch 48/64

144/144 - 1s - 4ms/step - ia: 0.7393 - loss: 0.2647 - mae: 0.4023 - rmse: 0.5136 - smape: 0.7780 - val_ia: 0.5183 - val_loss: 0.8121 - val_mae: 0.6845 - val_rmse: 0.8503 - val_smape: 1.1551

Epoch 49/64

144/144 - 1s - 5ms/step - ia: 0.7407 - loss: 0.2607 - mae: 0.4000 - rmse: 0.5100 - smape: 0.7778 - val_ia: 0.5217 - val_loss: 0.7934 - val_mae: 0.6757 - val_rmse: 0.8410 - val_smape: 1.1484

Epoch 50/64

144/144 - 1s - 4ms/step - ia: 0.7404 - loss: 0.2620 - mae: 0.4011 - rmse: 0.5113 - smape: 0.7784 - val_ia: 0.5234 - val_loss: 0.7884 - val_mae: 0.6726 - val_rmse: 0.8387 - val_smape: 1.1455

Epoch 51/64

144/144 - 1s - 4ms/step - ia: 0.7418 - loss: 0.2593 - mae: 0.3988 - rmse: 0.5084 - smape: 0.7721 - val_ia: 0.5213 - val_loss: 0.8140 - val_mae: 0.6834 - val_rmse: 0.8528 - val_smape: 1.1485

Epoch 52/64

144/144 - 0s - 3ms/step - ia: 0.7412 - loss: 0.2599 - mae: 0.4003 - rmse: 0.5093 - smape: 0.7766 - val_ia: 0.5261 - val_loss: 0.7565 - val_mae: 0.6577 - val_rmse: 0.8224 - val_smape: 1.1370

Epoch 53/64

144/144 - 0s - 3ms/step - ia: 0.7441 - loss: 0.2555 - mae: 0.3960 - rmse: 0.5047 - smape: 0.7705 - val_ia: 0.5225 - val_loss: 0.7865 - val_mae: 0.6718 - val_rmse: 0.8381 - val_smape: 1.1449

Epoch 54/64

144/144 - 1s - 4ms/step - ia: 0.7426 - loss: 0.2561 - mae: 0.3977 - rmse: 0.5052 - smape: 0.7745 - val_ia: 0.5276 - val_loss: 0.7517 - val_mae: 0.6551 - val_rmse: 0.8200 - val_smape: 1.1342

Epoch 55/64

144/144 - 1s - 4ms/step - ia: 0.7444 - loss: 0.2541 - mae: 0.3949 - rmse: 0.5041 - smape: 0.7687 - val_ia: 0.5248 - val_loss: 0.7927 - val_mae: 0.6725 - val_rmse: 0.8419 - val_smape: 1.1407

Epoch 56/64

144/144 - 0s - 3ms/step - ia: 0.7454 - loss: 0.2530 - mae: 0.3939 - rmse: 0.5022 - smape: 0.7685 - val_ia: 0.5295 - val_loss: 0.7468 - val_mae: 0.6541 - val_rmse: 0.8159 - val_smape: 1.1343

Epoch 57/64

144/144 - 0s - 3ms/step - ia: 0.7478 - loss: 0.2501 - mae: 0.3908 - rmse: 0.4994 - smape: 0.7628 - val_ia: 0.5287 - val_loss: 0.7593 - val_mae: 0.6580 - val_rmse: 0.8248 - val_smape: 1.1313

Epoch 58/64

144/144 - 0s - 3ms/step - ia: 0.7477 - loss: 0.2492 - mae: 0.3907 - rmse: 0.4982 - smape: 0.7638 - val_ia: 0.5315 - val_loss: 0.7374 - val_mae: 0.6479 - val_rmse: 0.8126 - val_smape: 1.1264

Epoch 59/64

144/144 - 0s - 3ms/step - ia: 0.7496 - loss: 0.2469 - mae: 0.3882 - rmse: 0.4962 - smape: 0.7598 - val_ia: 0.5332 - val_loss: 0.7314 - val_mae: 0.6436 - val_rmse: 0.8094 - val_smape: 1.1226

Epoch 60/64

144/144 - 1s - 4ms/step - ia: 0.7501 - loss: 0.2449 - mae: 0.3876 - rmse: 0.4942 - smape: 0.7594 - val_ia: 0.5311 - val_loss: 0.7363 - val_mae: 0.6467 - val_rmse: 0.8126 - val_smape: 1.1253

Epoch 61/64

144/144 - 1s - 5ms/step - ia: 0.7503 - loss: 0.2452 - mae: 0.3869 - rmse: 0.4945 - smape: 0.7590 - val_ia: 0.5349 - val_loss: 0.7122 - val_mae: 0.6385 - val_rmse: 0.7983 - val_smape: 1.1223

Epoch 62/64

144/144 - 1s - 4ms/step - ia: 0.7517 - loss: 0.2434 - mae: 0.3851 - rmse: 0.4925 - smape: 0.7567 - val_ia: 0.5319 - val_loss: 0.7358 - val_mae: 0.6458 - val_rmse: 0.8132 - val_smape: 1.1228

Epoch 63/64

144/144 - 1s - 4ms/step - ia: 0.7523 - loss: 0.2413 - mae: 0.3837 - rmse: 0.4907 - smape: 0.7560 - val_ia: 0.5349 - val_loss: 0.6845 - val_mae: 0.6239 - val_rmse: 0.7852 - val_smape: 1.1159

Epoch 64/64

144/144 - 1s - 4ms/step - ia: 0.7531 - loss: 0.2409 - mae: 0.3831 - rmse: 0.4903 - smape: 0.7561 - val_ia: 0.5359 - val_loss: 0.7030 - val_mae: 0.6330 - val_rmse: 0.7947 - val_smape: 1.1182

Restoring model weights from the end of the best epoch: 63.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 18s 114ms/step
 17/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
146/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 82%|████████▏ | 41/50 [4:05:02<35:57, 239.76s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

4584/4584 - 18s - 4ms/step - ia: 0.5456 - loss: 0.6038 - mae: 0.6133 - rmse: 0.7452 - smape: 1.0234 - val_ia: 0.1170 - val_loss: 1.3117 - val_mae: 0.9559 - val_rmse: 0.9768 - val_smape: 1.3444

Epoch 2/32

4584/4584 - 13s - 3ms/step - ia: 0.5719 - loss: 0.4965 - mae: 0.5615 - rmse: 0.6831 - smape: 0.9764 - val_ia: 0.1121 - val_loss: 1.3100 - val_mae: 0.9735 - val_rmse: 0.9941 - val_smape: 1.3592

Epoch 3/32

4584/4584 - 14s - 3ms/step - ia: 0.5758 - loss: 0.4903 - mae: 0.5574 - rmse: 0.6791 - smape: 0.9711 - val_ia: 0.1082 - val_loss: 1.5150 - val_mae: 1.0407 - val_rmse: 1.0645 - val_smape: 1.3480

Epoch 4/32

4584/4584 - 14s - 3ms/step - ia: 0.5771 - loss: 0.4892 - mae: 0.5555 - rmse: 0.6780 - smape: 0.9673 - val_ia: 0.1072 - val_loss: 1.6459 - val_mae: 1.0815 - val_rmse: 1.1053 - val_smape: 1.3575

Epoch 5/32

4584/4584 - 12s - 3ms/step - ia: 0.5776 - loss: 0.4882 - mae: 0.5559 - rmse: 0.6780 - smape: 0.9684 - val_ia: 0.1127 - val_loss: 1.3553 - val_mae: 0.9809 - val_rmse: 1.0042 - val_smape: 1.3319

Epoch 6/32

4584/4584 - 13s - 3ms/step - ia: 0.5764 - loss: 0.4872 - mae: 0.5548 - rmse: 0.6766 - smape: 0.9672 - val_ia: 0.1019 - val_loss: 1.6133 - val_mae: 1.0927 - val_rmse: 1.1135 - val_smape: 1.4113

Epoch 7/32

4584/4584 - 20s - 4ms/step - ia: 0.5788 - loss: 0.4865 - mae: 0.5544 - rmse: 0.6762 - smape: 0.9661 - val_ia: 0.1048 - val_loss: 1.5526 - val_mae: 1.0629 - val_rmse: 1.0868 - val_smape: 1.3660

Epoch 8/32

4584/4584 - 20s - 4ms/step - ia: 0.5786 - loss: 0.4842 - mae: 0.5530 - rmse: 0.6743 - smape: 0.9663 - val_ia: 0.1036 - val_loss: 1.6013 - val_mae: 1.0845 - val_rmse: 1.1065 - val_smape: 1.3946

Epoch 9/32

4584/4584 - 12s - 3ms/step - ia: 0.5801 - loss: 0.4847 - mae: 0.5527 - rmse: 0.6749 - smape: 0.9648 - val_ia: 0.1123 - val_loss: 1.2846 - val_mae: 0.9653 - val_rmse: 0.9851 - val_smape: 1.3678

Epoch 10/32

4584/4584 - 13s - 3ms/step - ia: 0.5785 - loss: 0.4840 - mae: 0.5522 - rmse: 0.6742 - smape: 0.9644 - val_ia: 0.1147 - val_loss: 1.3040 - val_mae: 0.9593 - val_rmse: 0.9828 - val_smape: 1.3128

Epoch 11/32

4584/4584 - 20s - 4ms/step - ia: 0.5785 - loss: 0.4836 - mae: 0.5524 - rmse: 0.6744 - smape: 0.9650 - val_ia: 0.1123 - val_loss: 1.3019 - val_mae: 0.9682 - val_rmse: 0.9898 - val_smape: 1.3550

Epoch 12/32

4584/4584 - 12s - 3ms/step - ia: 0.5795 - loss: 0.4844 - mae: 0.5525 - rmse: 0.6748 - smape: 0.9641 - val_ia: 0.1122 - val_loss: 1.3271 - val_mae: 0.9749 - val_rmse: 0.9973 - val_smape: 1.3464

Epoch 13/32

4584/4584 - 12s - 3ms/step - ia: 0.5780 - loss: 0.4857 - mae: 0.5536 - rmse: 0.6760 - smape: 0.9660 - val_ia: 0.1047 - val_loss: 1.4325 - val_mae: 1.0304 - val_rmse: 1.0527 - val_smape: 1.3852

Epoch 14/32

4584/4584 - 11s - 2ms/step - ia: 0.5804 - loss: 0.4825 - mae: 0.5512 - rmse: 0.6728 - smape: 0.9643 - val_ia: 0.1105 - val_loss: 1.6478 - val_mae: 1.0725 - val_rmse: 1.0990 - val_smape: 1.3161

Epoch 15/32

4584/4584 - 17s - 4ms/step - ia: 0.5791 - loss: 0.4825 - mae: 0.5518 - rmse: 0.6731 - smape: 0.9638 - val_ia: 0.1169 - val_loss: 1.2242 - val_mae: 0.9303 - val_rmse: 0.9532 - val_smape: 1.3138

Epoch 16/32

4584/4584 - 12s - 3ms/step - ia: 0.5791 - loss: 0.4831 - mae: 0.5523 - rmse: 0.6736 - smape: 0.9652 - val_ia: 0.1007 - val_loss: 1.6408 - val_mae: 1.0994 - val_rmse: 1.1249 - val_smape: 1.3797

Epoch 17/32

4584/4584 - 12s - 3ms/step - ia: 0.5803 - loss: 0.4829 - mae: 0.5515 - rmse: 0.6741 - smape: 0.9625 - val_ia: 0.1070 - val_loss: 1.6538 - val_mae: 1.0832 - val_rmse: 1.1091 - val_smape: 1.3420

Epoch 18/32

4584/4584 - 12s - 3ms/step - ia: 0.5803 - loss: 0.4831 - mae: 0.5519 - rmse: 0.6738 - smape: 0.9650 - val_ia: 0.1077 - val_loss: 1.4302 - val_mae: 1.0218 - val_rmse: 1.0442 - val_smape: 1.3679

Epoch 19/32

4584/4584 - 13s - 3ms/step - ia: 0.5808 - loss: 0.4828 - mae: 0.5519 - rmse: 0.6739 - smape: 0.9641 - val_ia: 0.1176 - val_loss: 1.3033 - val_mae: 0.9493 - val_rmse: 0.9741 - val_smape: 1.2824

Epoch 20/32

4584/4584 - 10s - 2ms/step - ia: 0.5813 - loss: 0.4816 - mae: 0.5510 - rmse: 0.6728 - smape: 0.9611 - val_ia: 0.1090 - val_loss: 1.5063 - val_mae: 1.0370 - val_rmse: 1.0598 - val_smape: 1.3534

Epoch 21/32

4584/4584 - 11s - 3ms/step - ia: 0.5794 - loss: 0.4836 - mae: 0.5525 - rmse: 0.6738 - smape: 0.9653 - val_ia: 0.1116 - val_loss: 1.4070 - val_mae: 1.0034 - val_rmse: 1.0267 - val_smape: 1.3408

Epoch 22/32

4584/4584 - 11s - 2ms/step - ia: 0.5800 - loss: 0.4824 - mae: 0.5517 - rmse: 0.6734 - smape: 0.9646 - val_ia: 0.1077 - val_loss: 1.3637 - val_mae: 1.0005 - val_rmse: 1.0226 - val_smape: 1.3715

Epoch 23/32

4584/4584 - 11s - 2ms/step - ia: 0.5788 - loss: 0.4828 - mae: 0.5517 - rmse: 0.6738 - smape: 0.9628 - val_ia: 0.1029 - val_loss: 1.5661 - val_mae: 1.0769 - val_rmse: 1.0998 - val_smape: 1.3880

Epoch 24/32

4584/4584 - 12s - 3ms/step - ia: 0.5808 - loss: 0.4828 - mae: 0.5519 - rmse: 0.6738 - smape: 0.9637 - val_ia: 0.1037 - val_loss: 1.7303 - val_mae: 1.1165 - val_rmse: 1.1415 - val_smape: 1.3707

Epoch 25/32

4584/4584 - 10s - 2ms/step - ia: 0.5799 - loss: 0.4824 - mae: 0.5505 - rmse: 0.6730 - smape: 0.9612 - val_ia: 0.1122 - val_loss: 1.2667 - val_mae: 0.9599 - val_rmse: 0.9815 - val_smape: 1.3588

Epoch 26/32

4584/4584 - 11s - 2ms/step - ia: 0.5799 - loss: 0.4816 - mae: 0.5515 - rmse: 0.6730 - smape: 0.9626 - val_ia: 0.1110 - val_loss: 1.4307 - val_mae: 1.0069 - val_rmse: 1.0310 - val_smape: 1.3296

Epoch 27/32

4584/4584 - 25s - 5ms/step - ia: 0.5805 - loss: 0.4810 - mae: 0.5512 - rmse: 0.6721 - smape: 0.9610 - val_ia: 0.1157 - val_loss: 1.2447 - val_mae: 0.9405 - val_rmse: 0.9624 - val_smape: 1.3312

Epoch 28/32

4584/4584 - 14s - 3ms/step - ia: 0.5801 - loss: 0.4812 - mae: 0.5506 - rmse: 0.6718 - smape: 0.9625 - val_ia: 0.1175 - val_loss: 1.3398 - val_mae: 0.9612 - val_rmse: 0.9855 - val_smape: 1.2892

Epoch 29/32

4584/4584 - 17s - 4ms/step - ia: 0.5813 - loss: 0.4826 - mae: 0.5512 - rmse: 0.6735 - smape: 0.9635 - val_ia: 0.1083 - val_loss: 1.5659 - val_mae: 1.0554 - val_rmse: 1.0804 - val_smape: 1.3432

Epoch 30/32

4584/4584 - 10s - 2ms/step - ia: 0.5804 - loss: 0.4828 - mae: 0.5523 - rmse: 0.6736 - smape: 0.9647 - val_ia: 0.1087 - val_loss: 1.4959 - val_mae: 1.0351 - val_rmse: 1.0585 - val_smape: 1.3562

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 37s 232ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 84%|████████▍ | 42/50 [4:11:58<39:00, 292.55s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

2292/2292 - 12s - 5ms/step - ia: 0.3227 - loss: 1.4304 - mae: 0.9695 - rmse: 1.1797 - smape: 1.4060 - val_ia: 0.1900 - val_loss: 0.7086 - val_mae: 0.7005 - val_rmse: 0.7385 - val_smape: 1.4420

Epoch 2/8

2292/2292 - 6s - 3ms/step - ia: 0.3445 - loss: 1.3213 - mae: 0.9297 - rmse: 1.1339 - smape: 1.3762 - val_ia: 0.1922 - val_loss: 0.7112 - val_mae: 0.7035 - val_rmse: 0.7402 - val_smape: 1.3899

Epoch 3/8

2292/2292 - 10s - 4ms/step - ia: 0.3563 - loss: 1.2548 - mae: 0.9092 - rmse: 1.1051 - smape: 1.3644 - val_ia: 0.1937 - val_loss: 0.7232 - val_mae: 0.7112 - val_rmse: 0.7470 - val_smape: 1.3600

Epoch 4/8

2292/2292 - 6s - 3ms/step - ia: 0.3715 - loss: 1.1923 - mae: 0.8846 - rmse: 1.0777 - smape: 1.3380 - val_ia: 0.1941 - val_loss: 0.7391 - val_mae: 0.7202 - val_rmse: 0.7554 - val_smape: 1.3391

Epoch 5/8

2292/2292 - 11s - 5ms/step - ia: 0.3791 - loss: 1.1537 - mae: 0.8720 - rmse: 1.0607 - smape: 1.3301 - val_ia: 0.1926 - val_loss: 0.7633 - val_mae: 0.7339 - val_rmse: 0.7685 - val_smape: 1.3316

Epoch 6/8

2292/2292 - 6s - 2ms/step - ia: 0.3920 - loss: 1.1059 - mae: 0.8513 - rmse: 1.0377 - smape: 1.3112 - val_ia: 0.1902 - val_loss: 0.7864 - val_mae: 0.7465 - val_rmse: 0.7807 - val_smape: 1.3248

Epoch 7/8

2292/2292 - 5s - 2ms/step - ia: 0.3986 - loss: 1.0774 - mae: 0.8409 - rmse: 1.0244 - smape: 1.2987 - val_ia: 0.1886 - val_loss: 0.8087 - val_mae: 0.7585 - val_rmse: 0.7924 - val_smape: 1.3220

Epoch 8/8

2292/2292 - 6s - 3ms/step - ia: 0.4111 - loss: 1.0387 - mae: 0.8248 - rmse: 1.0053 - smape: 1.2845 - val_ia: 0.1870 - val_loss: 0.8297 - val_mae: 0.7699 - val_rmse: 0.8036 - val_smape: 1.3212

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 104ms/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 86%|████████▌ | 43/50 [4:13:01<26:06, 223.77s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 4s - 14ms/step - ia: 0.3586 - loss: 0.8090 - mae: 0.7369 - rmse: 0.8934 - smape: 1.3469 - val_ia: 0.4199 - val_loss: 0.9290 - val_mae: 0.8045 - val_rmse: 0.9388 - val_smape: 1.3184

Epoch 2/128

287/287 - 1s - 4ms/step - ia: 0.5549 - loss: 0.5680 - mae: 0.6059 - rmse: 0.7523 - smape: 1.0594 - val_ia: 0.4157 - val_loss: 1.3075 - val_mae: 0.9704 - val_rmse: 1.1068 - val_smape: 1.3556

Epoch 3/128

287/287 - 1s - 5ms/step - ia: 0.5908 - loss: 0.5423 - mae: 0.5868 - rmse: 0.7352 - smape: 1.0007 - val_ia: 0.4113 - val_loss: 1.4248 - val_mae: 1.0149 - val_rmse: 1.1499 - val_smape: 1.3684

Epoch 4/128

287/287 - 1s - 3ms/step - ia: 0.5988 - loss: 0.5308 - mae: 0.5808 - rmse: 0.7272 - smape: 0.9876 - val_ia: 0.4097 - val_loss: 1.4554 - val_mae: 1.0264 - val_rmse: 1.1577 - val_smape: 1.3746

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.5997 - loss: 0.5264 - mae: 0.5800 - rmse: 0.7243 - smape: 0.9908 - val_ia: 0.4077 - val_loss: 1.5030 - val_mae: 1.0418 - val_rmse: 1.1745 - val_smape: 1.3777

Epoch 6/128

287/287 - 1s - 4ms/step - ia: 0.6045 - loss: 0.5184 - mae: 0.5749 - rmse: 0.7187 - smape: 0.9790 - val_ia: 0.4091 - val_loss: 1.5032 - val_mae: 1.0389 - val_rmse: 1.1737 - val_smape: 1.3735

Epoch 7/128

287/287 - 1s - 4ms/step - ia: 0.6065 - loss: 0.5150 - mae: 0.5726 - rmse: 0.7165 - smape: 0.9760 - val_ia: 0.4113 - val_loss: 1.4860 - val_mae: 1.0314 - val_rmse: 1.1661 - val_smape: 1.3686

Epoch 8/128

287/287 - 1s - 3ms/step - ia: 0.6135 - loss: 0.5000 - mae: 0.5636 - rmse: 0.7057 - smape: 0.9667 - val_ia: 0.4091 - val_loss: 1.5059 - val_mae: 1.0404 - val_rmse: 1.1742 - val_smape: 1.3745

Epoch 9/128

287/287 - 1s - 5ms/step - ia: 0.6160 - loss: 0.4929 - mae: 0.5604 - rmse: 0.7005 - smape: 0.9647 - val_ia: 0.4164 - val_loss: 1.4398 - val_mae: 1.0110 - val_rmse: 1.1476 - val_smape: 1.3557

Epoch 10/128

287/287 - 1s - 3ms/step - ia: 0.6196 - loss: 0.4841 - mae: 0.5553 - rmse: 0.6947 - smape: 0.9552 - val_ia: 0.4148 - val_loss: 1.4446 - val_mae: 1.0168 - val_rmse: 1.1487 - val_smape: 1.3642

Epoch 11/128

287/287 - 1s - 3ms/step - ia: 0.6233 - loss: 0.4783 - mae: 0.5508 - rmse: 0.6901 - smape: 0.9494 - val_ia: 0.4177 - val_loss: 1.4136 - val_mae: 1.0036 - val_rmse: 1.1361 - val_smape: 1.3576

Epoch 12/128

287/287 - 1s - 3ms/step - ia: 0.6279 - loss: 0.4658 - mae: 0.5450 - rmse: 0.6813 - smape: 0.9432 - val_ia: 0.4194 - val_loss: 1.4232 - val_mae: 1.0019 - val_rmse: 1.1412 - val_smape: 1.3495

Epoch 13/128

287/287 - 1s - 5ms/step - ia: 0.6305 - loss: 0.4600 - mae: 0.5423 - rmse: 0.6769 - smape: 0.9401 - val_ia: 0.4202 - val_loss: 1.3975 - val_mae: 0.9965 - val_rmse: 1.1298 - val_smape: 1.3547

Epoch 14/128

287/287 - 1s - 4ms/step - ia: 0.6330 - loss: 0.4554 - mae: 0.5398 - rmse: 0.6736 - smape: 0.9366 - val_ia: 0.4234 - val_loss: 1.3744 - val_mae: 0.9856 - val_rmse: 1.1201 - val_smape: 1.3477

Epoch 15/128

287/287 - 1s - 3ms/step - ia: 0.6385 - loss: 0.4451 - mae: 0.5324 - rmse: 0.6660 - smape: 0.9265 - val_ia: 0.4273 - val_loss: 1.3384 - val_mae: 0.9697 - val_rmse: 1.1047 - val_smape: 1.3402

Epoch 16/128

287/287 - 1s - 3ms/step - ia: 0.6431 - loss: 0.4353 - mae: 0.5271 - rmse: 0.6584 - smape: 0.9235 - val_ia: 0.4288 - val_loss: 1.3202 - val_mae: 0.9621 - val_rmse: 1.0965 - val_smape: 1.3384

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 18s 112ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 88%|████████▊ | 44/50 [4:13:23<16:19, 163.28s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1146/1146 - 7s - 6ms/step - ia: 0.4343 - loss: 0.9872 - mae: 0.7616 - rmse: 0.9527 - smape: 1.2663 - val_ia: 0.2488 - val_loss: 1.0967 - val_mae: 0.8762 - val_rmse: 0.9449 - val_smape: 1.3516

Epoch 2/128

1146/1146 - 3s - 3ms/step - ia: 0.4824 - loss: 0.6648 - mae: 0.6549 - rmse: 0.8097 - smape: 1.1864 - val_ia: 0.2445 - val_loss: 1.1210 - val_mae: 0.8908 - val_rmse: 0.9592 - val_smape: 1.3593

Epoch 3/128

1146/1146 - 3s - 3ms/step - ia: 0.5019 - loss: 0.6259 - mae: 0.6352 - rmse: 0.7853 - smape: 1.1501 - val_ia: 0.2400 - val_loss: 1.1944 - val_mae: 0.9196 - val_rmse: 0.9903 - val_smape: 1.3487

Epoch 4/128

1146/1146 - 3s - 3ms/step - ia: 0.5144 - loss: 0.6040 - mae: 0.6232 - rmse: 0.7720 - smape: 1.1242 - val_ia: 0.2441 - val_loss: 1.1396 - val_mae: 0.8978 - val_rmse: 0.9671 - val_smape: 1.3520

Epoch 5/128

1146/1146 - 3s - 3ms/step - ia: 0.5204 - loss: 0.5922 - mae: 0.6164 - rmse: 0.7640 - smape: 1.1118 - val_ia: 0.2393 - val_loss: 1.2391 - val_mae: 0.9282 - val_rmse: 1.0036 - val_smape: 1.3252

Epoch 6/128

1146/1146 - 5s - 4ms/step - ia: 0.5211 - loss: 0.5926 - mae: 0.6168 - rmse: 0.7645 - smape: 1.1079 - val_ia: 0.2376 - val_loss: 1.2205 - val_mae: 0.9352 - val_rmse: 1.0044 - val_smape: 1.3598

Epoch 7/128

1146/1146 - 6s - 5ms/step - ia: 0.5229 - loss: 0.5877 - mae: 0.6153 - rmse: 0.7614 - smape: 1.1039 - val_ia: 0.2486 - val_loss: 1.1129 - val_mae: 0.8847 - val_rmse: 0.9539 - val_smape: 1.3377

Epoch 8/128

1146/1146 - 3s - 2ms/step - ia: 0.5260 - loss: 0.5844 - mae: 0.6131 - rmse: 0.7591 - smape: 1.1030 - val_ia: 0.2415 - val_loss: 1.1895 - val_mae: 0.9180 - val_rmse: 0.9878 - val_smape: 1.3467

Epoch 9/128

1146/1146 - 5s - 4ms/step - ia: 0.5252 - loss: 0.5836 - mae: 0.6122 - rmse: 0.7587 - smape: 1.1008 - val_ia: 0.2317 - val_loss: 1.3445 - val_mae: 0.9861 - val_rmse: 1.0540 - val_smape: 1.3846

Epoch 10/128

1146/1146 - 3s - 3ms/step - ia: 0.5309 - loss: 0.5775 - mae: 0.6083 - rmse: 0.7547 - smape: 1.0936 - val_ia: 0.2379 - val_loss: 1.2455 - val_mae: 0.9429 - val_rmse: 1.0114 - val_smape: 1.3629

Epoch 11/128

1146/1146 - 3s - 3ms/step - ia: 0.5263 - loss: 0.5842 - mae: 0.6120 - rmse: 0.7588 - smape: 1.0997 - val_ia: 0.2426 - val_loss: 1.1583 - val_mae: 0.9087 - val_rmse: 0.9767 - val_smape: 1.3584

Epoch 12/128

1146/1146 - 3s - 3ms/step - ia: 0.5263 - loss: 0.5832 - mae: 0.6108 - rmse: 0.7585 - smape: 1.0979 - val_ia: 0.2436 - val_loss: 1.1693 - val_mae: 0.9118 - val_rmse: 0.9795 - val_smape: 1.3512

Epoch 13/128

1146/1146 - 3s - 3ms/step - ia: 0.5270 - loss: 0.5826 - mae: 0.6116 - rmse: 0.7576 - smape: 1.0995 - val_ia: 0.2428 - val_loss: 1.1468 - val_mae: 0.9093 - val_rmse: 0.9756 - val_smape: 1.3682

Epoch 14/128

1146/1146 - 3s - 3ms/step - ia: 0.5251 - loss: 0.5844 - mae: 0.6128 - rmse: 0.7593 - smape: 1.1022 - val_ia: 0.2362 - val_loss: 1.2493 - val_mae: 0.9441 - val_rmse: 1.0155 - val_smape: 1.3509

Epoch 15/128

1146/1146 - 3s - 3ms/step - ia: 0.5301 - loss: 0.5795 - mae: 0.6096 - rmse: 0.7556 - smape: 1.0959 - val_ia: 0.2459 - val_loss: 1.1242 - val_mae: 0.8943 - val_rmse: 0.9619 - val_smape: 1.3519

Epoch 16/128

1146/1146 - 3s - 3ms/step - ia: 0.5268 - loss: 0.5822 - mae: 0.6111 - rmse: 0.7575 - smape: 1.0995 - val_ia: 0.2388 - val_loss: 1.2054 - val_mae: 0.9276 - val_rmse: 0.9984 - val_smape: 1.3409

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 90%|█████████ | 45/50 [4:14:23<11:01, 132.22s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

2292/2292 - 8s - 4ms/step - ia: 0.6830 - loss: 0.3377 - mae: 0.4604 - rmse: 0.5687 - smape: 0.8324 - val_ia: 0.2158 - val_loss: 1.1167 - val_mae: 0.8486 - val_rmse: 0.8908 - val_smape: 1.1215

Epoch 2/256

2292/2292 - 10s - 4ms/step - ia: 0.7070 - loss: 0.2921 - mae: 0.4292 - rmse: 0.5312 - smape: 0.7935 - val_ia: 0.2569 - val_loss: 0.4992 - val_mae: 0.5758 - val_rmse: 0.6207 - val_smape: 1.0283

Epoch 3/256

2292/2292 - 11s - 5ms/step - ia: 0.7124 - loss: 0.2833 - mae: 0.4209 - rmse: 0.5228 - smape: 0.7810 - val_ia: 0.2888 - val_loss: 0.3163 - val_mae: 0.4674 - val_rmse: 0.5031 - val_smape: 0.9253

Epoch 4/256

2292/2292 - 6s - 3ms/step - ia: 0.7159 - loss: 0.2788 - mae: 0.4178 - rmse: 0.5188 - smape: 0.7777 - val_ia: 0.2763 - val_loss: 0.3593 - val_mae: 0.4980 - val_rmse: 0.5387 - val_smape: 0.9339

Epoch 5/256

2292/2292 - 4s - 2ms/step - ia: 0.7173 - loss: 0.2758 - mae: 0.4154 - rmse: 0.5154 - smape: 0.7744 - val_ia: 0.2848 - val_loss: 0.3616 - val_mae: 0.4766 - val_rmse: 0.5186 - val_smape: 0.8936

Epoch 6/256

2292/2292 - 6s - 3ms/step - ia: 0.7219 - loss: 0.2696 - mae: 0.4094 - rmse: 0.5102 - smape: 0.7667 - val_ia: 0.3084 - val_loss: 0.2637 - val_mae: 0.4204 - val_rmse: 0.4634 - val_smape: 0.7836

Epoch 7/256

2292/2292 - 7s - 3ms/step - ia: 0.7242 - loss: 0.2663 - mae: 0.4062 - rmse: 0.5068 - smape: 0.7590 - val_ia: 0.3151 - val_loss: 0.2593 - val_mae: 0.4167 - val_rmse: 0.4538 - val_smape: 0.7838

Epoch 8/256

2292/2292 - 7s - 3ms/step - ia: 0.7236 - loss: 0.2678 - mae: 0.4080 - rmse: 0.5086 - smape: 0.7583 - val_ia: 0.2843 - val_loss: 0.4578 - val_mae: 0.5403 - val_rmse: 0.5955 - val_smape: 0.9813

Epoch 9/256

2292/2292 - 7s - 3ms/step - ia: 0.7285 - loss: 0.2605 - mae: 0.4015 - rmse: 0.5012 - smape: 0.7528 - val_ia: 0.3034 - val_loss: 0.2691 - val_mae: 0.4245 - val_rmse: 0.4595 - val_smape: 0.8716

Epoch 10/256

2292/2292 - 6s - 3ms/step - ia: 0.7263 - loss: 0.2637 - mae: 0.4044 - rmse: 0.5042 - smape: 0.7541 - val_ia: 0.3471 - val_loss: 0.2321 - val_mae: 0.3783 - val_rmse: 0.4144 - val_smape: 0.7138

Epoch 11/256

2292/2292 - 6s - 3ms/step - ia: 0.7262 - loss: 0.2643 - mae: 0.4042 - rmse: 0.5040 - smape: 0.7550 - val_ia: 0.3082 - val_loss: 0.2751 - val_mae: 0.4229 - val_rmse: 0.4662 - val_smape: 0.7867

Epoch 12/256

2292/2292 - 10s - 4ms/step - ia: 0.7289 - loss: 0.2600 - mae: 0.4015 - rmse: 0.5007 - smape: 0.7508 - val_ia: 0.3498 - val_loss: 0.2147 - val_mae: 0.3656 - val_rmse: 0.4048 - val_smape: 0.7159

Epoch 13/256

2292/2292 - 10s - 5ms/step - ia: 0.7272 - loss: 0.2630 - mae: 0.4034 - rmse: 0.5033 - smape: 0.7546 - val_ia: 0.3132 - val_loss: 0.3178 - val_mae: 0.4540 - val_rmse: 0.4933 - val_smape: 0.7251

Epoch 14/256

2292/2292 - 5s - 2ms/step - ia: 0.7289 - loss: 0.2582 - mae: 0.4006 - rmse: 0.4994 - smape: 0.7500 - val_ia: 0.3162 - val_loss: 0.2358 - val_mae: 0.3936 - val_rmse: 0.4292 - val_smape: 0.7286

Epoch 15/256

2292/2292 - 11s - 5ms/step - ia: 0.7299 - loss: 0.2578 - mae: 0.3998 - rmse: 0.4981 - smape: 0.7471 - val_ia: 0.2999 - val_loss: 0.3365 - val_mae: 0.4656 - val_rmse: 0.5073 - val_smape: 0.7663

Epoch 16/256

2292/2292 - 5s - 2ms/step - ia: 0.7289 - loss: 0.2570 - mae: 0.3995 - rmse: 0.4981 - smape: 0.7487 - val_ia: 0.3220 - val_loss: 0.3363 - val_mae: 0.4482 - val_rmse: 0.4936 - val_smape: 0.8580

Epoch 17/256

2292/2292 - 10s - 4ms/step - ia: 0.7287 - loss: 0.2596 - mae: 0.4008 - rmse: 0.4997 - smape: 0.7509 - val_ia: 0.2838 - val_loss: 0.4117 - val_mae: 0.5209 - val_rmse: 0.5674 - val_smape: 0.8904

Epoch 18/256

2292/2292 - 10s - 5ms/step - ia: 0.7298 - loss: 0.2583 - mae: 0.3998 - rmse: 0.4988 - smape: 0.7495 - val_ia: 0.2645 - val_loss: 0.5327 - val_mae: 0.5944 - val_rmse: 0.6415 - val_smape: 0.9887

Epoch 19/256

2292/2292 - 12s - 5ms/step - ia: 0.7309 - loss: 0.2573 - mae: 0.3980 - rmse: 0.4979 - smape: 0.7468 - val_ia: 0.3333 - val_loss: 0.2334 - val_mae: 0.3799 - val_rmse: 0.4174 - val_smape: 0.6977

Epoch 20/256

2292/2292 - 6s - 2ms/step - ia: 0.7311 - loss: 0.2560 - mae: 0.3981 - rmse: 0.4966 - smape: 0.7470 - val_ia: 0.2787 - val_loss: 0.5033 - val_mae: 0.5793 - val_rmse: 0.6267 - val_smape: 0.9655

Epoch 21/256

2292/2292 - 10s - 4ms/step - ia: 0.7312 - loss: 0.2563 - mae: 0.3975 - rmse: 0.4967 - smape: 0.7449 - val_ia: 0.3276 - val_loss: 0.2509 - val_mae: 0.3968 - val_rmse: 0.4413 - val_smape: 0.7735

Epoch 22/256

2292/2292 - 4s - 2ms/step - ia: 0.7313 - loss: 0.2559 - mae: 0.3989 - rmse: 0.4969 - smape: 0.7493 - val_ia: 0.3267 - val_loss: 0.1975 - val_mae: 0.3613 - val_rmse: 0.3962 - val_smape: 0.7577

Epoch 23/256

2292/2292 - 5s - 2ms/step - ia: 0.7324 - loss: 0.2522 - mae: 0.3956 - rmse: 0.4934 - smape: 0.7433 - val_ia: 0.2797 - val_loss: 0.3076 - val_mae: 0.4692 - val_rmse: 0.5110 - val_smape: 0.8868

Epoch 24/256

2292/2292 - 6s - 3ms/step - ia: 0.7297 - loss: 0.2590 - mae: 0.3997 - rmse: 0.4994 - smape: 0.7485 - val_ia: 0.2881 - val_loss: 0.4881 - val_mae: 0.5315 - val_rmse: 0.5931 - val_smape: 0.9722

Epoch 25/256

2292/2292 - 6s - 2ms/step - ia: 0.7329 - loss: 0.2538 - mae: 0.3952 - rmse: 0.4943 - smape: 0.7431 - val_ia: 0.2875 - val_loss: 0.3953 - val_mae: 0.5064 - val_rmse: 0.5581 - val_smape: 0.9589

Epoch 26/256

2292/2292 - 5s - 2ms/step - ia: 0.7314 - loss: 0.2567 - mae: 0.3985 - rmse: 0.4975 - smape: 0.7470 - val_ia: 0.2337 - val_loss: 0.6328 - val_mae: 0.6723 - val_rmse: 0.7113 - val_smape: 1.1064

Epoch 27/256

2292/2292 - 5s - 2ms/step - ia: 0.7311 - loss: 0.2554 - mae: 0.3972 - rmse: 0.4960 - smape: 0.7441 - val_ia: 0.3696 - val_loss: 0.1979 - val_mae: 0.3412 - val_rmse: 0.3753 - val_smape: 0.6366

Epoch 28/256

2292/2292 - 6s - 2ms/step - ia: 0.7313 - loss: 0.2549 - mae: 0.3972 - rmse: 0.4959 - smape: 0.7452 - val_ia: 0.2908 - val_loss: 0.3012 - val_mae: 0.4468 - val_rmse: 0.4865 - val_smape: 0.8518

Epoch 29/256

2292/2292 - 6s - 2ms/step - ia: 0.7328 - loss: 0.2536 - mae: 0.3959 - rmse: 0.4944 - smape: 0.7407 - val_ia: 0.3106 - val_loss: 0.4114 - val_mae: 0.4887 - val_rmse: 0.5412 - val_smape: 0.9001

Epoch 30/256

2292/2292 - 10s - 4ms/step - ia: 0.7302 - loss: 0.2573 - mae: 0.3988 - rmse: 0.4979 - smape: 0.7473 - val_ia: 0.2758 - val_loss: 0.5797 - val_mae: 0.5901 - val_rmse: 0.6491 - val_smape: 0.9982

Epoch 31/256

2292/2292 - 10s - 4ms/step - ia: 0.7319 - loss: 0.2539 - mae: 0.3965 - rmse: 0.4945 - smape: 0.7434 - val_ia: 0.3010 - val_loss: 0.2651 - val_mae: 0.4194 - val_rmse: 0.4623 - val_smape: 0.7991

Epoch 32/256

2292/2292 - 4s - 2ms/step - ia: 0.7293 - loss: 0.2600 - mae: 0.3996 - rmse: 0.4998 - smape: 0.7472 - val_ia: 0.3016 - val_loss: 0.3275 - val_mae: 0.4652 - val_rmse: 0.5078 - val_smape: 0.8594

Epoch 33/256

2292/2292 - 5s - 2ms/step - ia: 0.7347 - loss: 0.2511 - mae: 0.3946 - rmse: 0.4913 - smape: 0.7395 - val_ia: 0.2899 - val_loss: 0.3569 - val_mae: 0.4913 - val_rmse: 0.5325 - val_smape: 0.9863

Epoch 34/256

2292/2292 - 6s - 3ms/step - ia: 0.7321 - loss: 0.2545 - mae: 0.3964 - rmse: 0.4950 - smape: 0.7425 - val_ia: 0.3252 - val_loss: 0.2246 - val_mae: 0.3829 - val_rmse: 0.4235 - val_smape: 0.7606

Epoch 35/256

2292/2292 - 10s - 4ms/step - ia: 0.7313 - loss: 0.2545 - mae: 0.3968 - rmse: 0.4953 - smape: 0.7451 - val_ia: 0.3398 - val_loss: 0.2284 - val_mae: 0.3774 - val_rmse: 0.4163 - val_smape: 0.6916

Epoch 36/256

2292/2292 - 5s - 2ms/step - ia: 0.7302 - loss: 0.2564 - mae: 0.3979 - rmse: 0.4964 - smape: 0.7485 - val_ia: 0.2815 - val_loss: 0.3252 - val_mae: 0.4645 - val_rmse: 0.5020 - val_smape: 0.8785

Epoch 37/256

2292/2292 - 6s - 3ms/step - ia: 0.7327 - loss: 0.2528 - mae: 0.3949 - rmse: 0.4939 - smape: 0.7407 - val_ia: 0.2898 - val_loss: 0.6042 - val_mae: 0.5938 - val_rmse: 0.6505 - val_smape: 0.9453

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 22.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
115/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/8

 92%|█████████▏| 46/50 [4:18:52<11:33, 173.28s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

144/144 - 4s - 30ms/step - ia: 0.2814 - loss: 0.8568 - mae: 0.7631 - rmse: 0.9170 - smape: 1.4411 - val_ia: 0.3902 - val_loss: 0.8466 - val_mae: 0.7658 - val_rmse: 0.8984 - val_smape: 1.3439

Epoch 2/8

144/144 - 1s - 5ms/step - ia: 0.5616 - loss: 0.5133 - mae: 0.5790 - rmse: 0.7158 - smape: 1.0270 - val_ia: 0.4051 - val_loss: 1.3600 - val_mae: 0.9952 - val_rmse: 1.1333 - val_smape: 1.3730

Epoch 3/8

144/144 - 1s - 4ms/step - ia: 0.6198 - loss: 0.4725 - mae: 0.5464 - rmse: 0.6861 - smape: 0.9433 - val_ia: 0.4151 - val_loss: 1.3377 - val_mae: 0.9776 - val_rmse: 1.1173 - val_smape: 1.3513

Epoch 4/8

144/144 - 1s - 4ms/step - ia: 0.6268 - loss: 0.4613 - mae: 0.5385 - rmse: 0.6781 - smape: 0.9310 - val_ia: 0.4116 - val_loss: 1.3989 - val_mae: 1.0010 - val_rmse: 1.1388 - val_smape: 1.3651

Epoch 5/8

144/144 - 1s - 4ms/step - ia: 0.6329 - loss: 0.4487 - mae: 0.5305 - rmse: 0.6692 - smape: 0.9218 - val_ia: 0.4166 - val_loss: 1.3739 - val_mae: 0.9873 - val_rmse: 1.1253 - val_smape: 1.3593

Epoch 6/8

144/144 - 1s - 4ms/step - ia: 0.6430 - loss: 0.4289 - mae: 0.5187 - rmse: 0.6541 - smape: 0.9056 - val_ia: 0.4180 - val_loss: 1.3807 - val_mae: 0.9847 - val_rmse: 1.1278 - val_smape: 1.3582

Epoch 7/8

144/144 - 1s - 5ms/step - ia: 0.6554 - loss: 0.4008 - mae: 0.5023 - rmse: 0.6330 - smape: 0.8855 - val_ia: 0.4178 - val_loss: 1.4188 - val_mae: 0.9935 - val_rmse: 1.1432 - val_smape: 1.3618

Epoch 8/8

144/144 - 1s - 6ms/step - ia: 0.6714 - loss: 0.3702 - mae: 0.4841 - rmse: 0.6076 - smape: 0.8629 - val_ia: 0.4361 - val_loss: 1.2638 - val_mae: 0.9197 - val_rmse: 1.0754 - val_smape: 1.3233

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 22s 139ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
117/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 94%|█████████▍| 47/50 [4:19:03<06:13, 124.51s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

573/573 - 17s - 30ms/step - ia: 0.5526 - loss: 0.6600 - mae: 0.6544 - rmse: 0.8082 - smape: 1.0728 - val_ia: 0.3497 - val_loss: 1.2860 - val_mae: 0.9781 - val_rmse: 1.0682 - val_smape: 1.3790

Epoch 2/16

573/573 - 2s - 3ms/step - ia: 0.6045 - loss: 0.5201 - mae: 0.5800 - rmse: 0.7183 - smape: 0.9824 - val_ia: 0.3620 - val_loss: 1.2688 - val_mae: 0.9489 - val_rmse: 1.0478 - val_smape: 1.3407

Epoch 3/16

573/573 - 1s - 2ms/step - ia: 0.6256 - loss: 0.4701 - mae: 0.5493 - rmse: 0.6832 - smape: 0.9482 - val_ia: 0.3667 - val_loss: 1.3070 - val_mae: 0.9508 - val_rmse: 1.0567 - val_smape: 1.3243

Epoch 4/16

573/573 - 2s - 3ms/step - ia: 0.6397 - loss: 0.4390 - mae: 0.5306 - rmse: 0.6601 - smape: 0.9247 - val_ia: 0.3773 - val_loss: 1.2161 - val_mae: 0.9086 - val_rmse: 1.0153 - val_smape: 1.3011

Epoch 5/16

573/573 - 1s - 2ms/step - ia: 0.6495 - loss: 0.4171 - mae: 0.5180 - rmse: 0.6433 - smape: 0.9115 - val_ia: 0.3847 - val_loss: 1.1599 - val_mae: 0.8829 - val_rmse: 0.9882 - val_smape: 1.2916

Epoch 6/16

573/573 - 2s - 3ms/step - ia: 0.6590 - loss: 0.3966 - mae: 0.5038 - rmse: 0.6275 - smape: 0.8961 - val_ia: 0.3963 - val_loss: 1.1190 - val_mae: 0.8571 - val_rmse: 0.9659 - val_smape: 1.2707

Epoch 7/16

573/573 - 2s - 3ms/step - ia: 0.6670 - loss: 0.3808 - mae: 0.4938 - rmse: 0.6148 - smape: 0.8859 - val_ia: 0.4027 - val_loss: 1.0900 - val_mae: 0.8455 - val_rmse: 0.9521 - val_smape: 1.2648

Epoch 8/16

573/573 - 2s - 4ms/step - ia: 0.6773 - loss: 0.3648 - mae: 0.4811 - rmse: 0.6017 - smape: 0.8705 - val_ia: 0.4091 - val_loss: 1.0487 - val_mae: 0.8210 - val_rmse: 0.9307 - val_smape: 1.2491

Epoch 9/16

573/573 - 2s - 3ms/step - ia: 0.6827 - loss: 0.3555 - mae: 0.4745 - rmse: 0.5938 - smape: 0.8621 - val_ia: 0.4140 - val_loss: 1.0270 - val_mae: 0.8086 - val_rmse: 0.9199 - val_smape: 1.2366

Epoch 10/16

573/573 - 2s - 3ms/step - ia: 0.6868 - loss: 0.3473 - mae: 0.4691 - rmse: 0.5868 - smape: 0.8563 - val_ia: 0.4159 - val_loss: 1.0229 - val_mae: 0.8104 - val_rmse: 0.9173 - val_smape: 1.2434

Epoch 11/16

573/573 - 2s - 3ms/step - ia: 0.6935 - loss: 0.3379 - mae: 0.4604 - rmse: 0.5788 - smape: 0.8460 - val_ia: 0.4241 - val_loss: 0.9855 - val_mae: 0.7849 - val_rmse: 0.8976 - val_smape: 1.2151

Epoch 12/16

573/573 - 3s - 5ms/step - ia: 0.6973 - loss: 0.3287 - mae: 0.4553 - rmse: 0.5707 - smape: 0.8408 - val_ia: 0.4261 - val_loss: 0.9823 - val_mae: 0.7854 - val_rmse: 0.8961 - val_smape: 1.2132

Epoch 13/16

573/573 - 2s - 3ms/step - ia: 0.7000 - loss: 0.3243 - mae: 0.4522 - rmse: 0.5672 - smape: 0.8389 - val_ia: 0.4308 - val_loss: 0.9574 - val_mae: 0.7696 - val_rmse: 0.8830 - val_smape: 1.1985

Epoch 14/16

573/573 - 2s - 3ms/step - ia: 0.7036 - loss: 0.3184 - mae: 0.4476 - rmse: 0.5619 - smape: 0.8301 - val_ia: 0.4332 - val_loss: 0.9589 - val_mae: 0.7668 - val_rmse: 0.8813 - val_smape: 1.1896

Epoch 15/16

573/573 - 1s - 3ms/step - ia: 0.7051 - loss: 0.3139 - mae: 0.4452 - rmse: 0.5577 - smape: 0.8296 - val_ia: 0.4356 - val_loss: 0.9286 - val_mae: 0.7598 - val_rmse: 0.8691 - val_smape: 1.1980

Epoch 16/16

573/573 - 2s - 3ms/step - ia: 0.7073 - loss: 0.3127 - mae: 0.4434 - rmse: 0.5569 - smape: 0.8268 - val_ia: 0.4366 - val_loss: 0.9303 - val_mae: 0.7582 - val_rmse: 0.8688 - val_smape: 1.1927

Restoring model weights from the end of the best epoch: 15.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 14s 87ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
130/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/128

 96%|█████████▌| 48/50 [4:19:46<03:20, 100.20s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4584/4584 - 17s - 4ms/step - ia: 0.5608 - loss: 0.5408 - mae: 0.5841 - rmse: 0.7100 - smape: 0.9960 - val_ia: 0.1048 - val_loss: 1.6775 - val_mae: 1.1147 - val_rmse: 1.1348 - val_smape: 1.4218

Epoch 2/128

4584/4584 - 22s - 5ms/step - ia: 0.5689 - loss: 0.5042 - mae: 0.5654 - rmse: 0.6886 - smape: 0.9806 - val_ia: 0.1057 - val_loss: 1.4517 - val_mae: 1.0414 - val_rmse: 1.0605 - val_smape: 1.4229

Epoch 3/128

4584/4584 - 11s - 2ms/step - ia: 0.5693 - loss: 0.5031 - mae: 0.5652 - rmse: 0.6881 - smape: 0.9791 - val_ia: 0.0988 - val_loss: 1.7742 - val_mae: 1.1425 - val_rmse: 1.1674 - val_smape: 1.3918

Epoch 4/128

4584/4584 - 22s - 5ms/step - ia: 0.5703 - loss: 0.5009 - mae: 0.5637 - rmse: 0.6861 - smape: 0.9793 - val_ia: 0.1129 - val_loss: 1.2725 - val_mae: 0.9608 - val_rmse: 0.9797 - val_smape: 1.3768

Epoch 5/128

4584/4584 - 12s - 3ms/step - ia: 0.5712 - loss: 0.4999 - mae: 0.5635 - rmse: 0.6851 - smape: 0.9804 - val_ia: 0.1089 - val_loss: 1.3458 - val_mae: 0.9954 - val_rmse: 1.0161 - val_smape: 1.3798

Epoch 6/128

4584/4584 - 22s - 5ms/step - ia: 0.5695 - loss: 0.4995 - mae: 0.5628 - rmse: 0.6852 - smape: 0.9766 - val_ia: 0.1207 - val_loss: 1.1901 - val_mae: 0.9068 - val_rmse: 0.9286 - val_smape: 1.2989

Epoch 7/128

4584/4584 - 20s - 4ms/step - ia: 0.5721 - loss: 0.5000 - mae: 0.5634 - rmse: 0.6859 - smape: 0.9792 - val_ia: 0.1018 - val_loss: 1.5824 - val_mae: 1.0854 - val_rmse: 1.1094 - val_smape: 1.3827

Epoch 8/128

4584/4584 - 14s - 3ms/step - ia: 0.5736 - loss: 0.4983 - mae: 0.5610 - rmse: 0.6840 - smape: 0.9745 - val_ia: 0.1086 - val_loss: 1.5158 - val_mae: 1.0449 - val_rmse: 1.0659 - val_smape: 1.3770

Epoch 9/128

4584/4584 - 14s - 3ms/step - ia: 0.5723 - loss: 0.4990 - mae: 0.5624 - rmse: 0.6858 - smape: 0.9772 - val_ia: 0.1149 - val_loss: 1.2075 - val_mae: 0.9310 - val_rmse: 0.9520 - val_smape: 1.3471

Epoch 10/128

4584/4584 - 22s - 5ms/step - ia: 0.5753 - loss: 0.4955 - mae: 0.5597 - rmse: 0.6822 - smape: 0.9750 - val_ia: 0.1039 - val_loss: 1.7136 - val_mae: 1.1071 - val_rmse: 1.1331 - val_smape: 1.3480

Epoch 11/128

4584/4584 - 11s - 2ms/step - ia: 0.5732 - loss: 0.4971 - mae: 0.5607 - rmse: 0.6834 - smape: 0.9756 - val_ia: 0.1138 - val_loss: 1.3942 - val_mae: 0.9895 - val_rmse: 1.0143 - val_smape: 1.3113

Epoch 12/128

4584/4584 - 8s - 2ms/step - ia: 0.5720 - loss: 0.4981 - mae: 0.5619 - rmse: 0.6844 - smape: 0.9770 - val_ia: 0.1112 - val_loss: 1.5085 - val_mae: 1.0320 - val_rmse: 1.0569 - val_smape: 1.3312

Epoch 13/128

4584/4584 - 13s - 3ms/step - ia: 0.5734 - loss: 0.4974 - mae: 0.5610 - rmse: 0.6839 - smape: 0.9747 - val_ia: 0.1143 - val_loss: 1.2854 - val_mae: 0.9553 - val_rmse: 0.9766 - val_smape: 1.3431

Epoch 14/128

4584/4584 - 13s - 3ms/step - ia: 0.5741 - loss: 0.4958 - mae: 0.5600 - rmse: 0.6830 - smape: 0.9739 - val_ia: 0.1131 - val_loss: 1.1922 - val_mae: 0.9385 - val_rmse: 0.9580 - val_smape: 1.3738

Epoch 15/128

4584/4584 - 14s - 3ms/step - ia: 0.5723 - loss: 0.4972 - mae: 0.5612 - rmse: 0.6838 - smape: 0.9755 - val_ia: 0.1113 - val_loss: 1.6090 - val_mae: 1.0498 - val_rmse: 1.0788 - val_smape: 1.2879

Epoch 16/128

4584/4584 - 14s - 3ms/step - ia: 0.5720 - loss: 0.4970 - mae: 0.5616 - rmse: 0.6843 - smape: 0.9787 - val_ia: 0.0949 - val_loss: 2.5169 - val_mae: 1.3371 - val_rmse: 1.3650 - val_smape: 1.3910

Epoch 17/128

4584/4584 - 17s - 4ms/step - ia: 0.5728 - loss: 0.4964 - mae: 0.5602 - rmse: 0.6826 - smape: 0.9746 - val_ia: 0.1176 - val_loss: 1.5457 - val_mae: 1.0037 - val_rmse: 1.0276 - val_smape: 1.2654

Epoch 18/128

4584/4584 - 13s - 3ms/step - ia: 0.5737 - loss: 0.4959 - mae: 0.5597 - rmse: 0.6829 - smape: 0.9736 - val_ia: 0.1111 - val_loss: 1.3536 - val_mae: 0.9856 - val_rmse: 1.0077 - val_smape: 1.3524

Epoch 19/128

4584/4584 - 21s - 5ms/step - ia: 0.5726 - loss: 0.4952 - mae: 0.5604 - rmse: 0.6822 - smape: 0.9738 - val_ia: 0.0992 - val_loss: 1.8269 - val_mae: 1.1542 - val_rmse: 1.1780 - val_smape: 1.3906

Epoch 20/128

4584/4584 - 12s - 3ms/step - ia: 0.5702 - loss: 0.4973 - mae: 0.5616 - rmse: 0.6841 - smape: 0.9761 - val_ia: 0.0964 - val_loss: 1.9908 - val_mae: 1.2111 - val_rmse: 1.2340 - val_smape: 1.4165

Epoch 21/128

4584/4584 - 12s - 3ms/step - ia: 0.5740 - loss: 0.4949 - mae: 0.5596 - rmse: 0.6818 - smape: 0.9737 - val_ia: 0.1008 - val_loss: 1.4867 - val_mae: 1.0550 - val_rmse: 1.0777 - val_smape: 1.4051

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 100ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 67/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/32

 98%|█████████▊| 49/50 [4:25:13<02:48, 168.03s/trial, best loss: 0.15528137861599256]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 4s - 15ms/step - ia: 0.5230 - loss: 0.7106 - mae: 0.6697 - rmse: 0.8338 - smape: 1.1157 - val_ia: 0.4128 - val_loss: 1.0961 - val_mae: 0.8598 - val_rmse: 1.0179 - val_smape: 1.3102

Epoch 2/32

287/287 - 2s - 7ms/step - ia: 0.5849 - loss: 0.5297 - mae: 0.5772 - rmse: 0.7264 - smape: 1.0015 - val_ia: 0.4256 - val_loss: 1.0065 - val_mae: 0.8092 - val_rmse: 0.9763 - val_smape: 1.2788

Epoch 3/32

287/287 - 1s - 3ms/step - ia: 0.5947 - loss: 0.5092 - mae: 0.5662 - rmse: 0.7122 - smape: 0.9872 - val_ia: 0.4187 - val_loss: 1.0391 - val_mae: 0.8231 - val_rmse: 0.9915 - val_smape: 1.2859

Epoch 4/32

287/287 - 1s - 3ms/step - ia: 0.5985 - loss: 0.5030 - mae: 0.5612 - rmse: 0.7078 - smape: 0.9795 - val_ia: 0.4210 - val_loss: 1.0650 - val_mae: 0.8299 - val_rmse: 1.0018 - val_smape: 1.2806

Epoch 5/32

287/287 - 1s - 3ms/step - ia: 0.6022 - loss: 0.4928 - mae: 0.5567 - rmse: 0.7007 - smape: 0.9801 - val_ia: 0.4226 - val_loss: 1.1092 - val_mae: 0.8467 - val_rmse: 1.0200 - val_smape: 1.2845

Epoch 6/32

287/287 - 1s - 3ms/step - ia: 0.6078 - loss: 0.4838 - mae: 0.5500 - rmse: 0.6942 - smape: 0.9734 - val_ia: 0.4226 - val_loss: 1.1447 - val_mae: 0.8580 - val_rmse: 1.0322 - val_smape: 1.2863

Epoch 7/32

287/287 - 1s - 3ms/step - ia: 0.6094 - loss: 0.4792 - mae: 0.5483 - rmse: 0.6908 - smape: 0.9760 - val_ia: 0.4288 - val_loss: 1.0930 - val_mae: 0.8330 - val_rmse: 1.0077 - val_smape: 1.2714

Epoch 8/32

287/287 - 1s - 5ms/step - ia: 0.6131 - loss: 0.4754 - mae: 0.5439 - rmse: 0.6877 - smape: 0.9714 - val_ia: 0.4315 - val_loss: 1.0808 - val_mae: 0.8306 - val_rmse: 0.9983 - val_smape: 1.2779

Epoch 9/32

287/287 - 1s - 4ms/step - ia: 0.6120 - loss: 0.4719 - mae: 0.5442 - rmse: 0.6856 - smape: 0.9786 - val_ia: 0.4321 - val_loss: 1.0861 - val_mae: 0.8304 - val_rmse: 1.0027 - val_smape: 1.2743

Epoch 10/32

287/287 - 1s - 3ms/step - ia: 0.6165 - loss: 0.4650 - mae: 0.5396 - rmse: 0.6808 - smape: 0.9713 - val_ia: 0.4348 - val_loss: 1.0809 - val_mae: 0.8258 - val_rmse: 0.9996 - val_smape: 1.2674

Epoch 11/32

287/287 - 1s - 3ms/step - ia: 0.6163 - loss: 0.4646 - mae: 0.5395 - rmse: 0.6801 - smape: 0.9741 - val_ia: 0.4392 - val_loss: 1.0917 - val_mae: 0.8299 - val_rmse: 1.0019 - val_smape: 1.2682

Epoch 12/32

287/287 - 1s - 5ms/step - ia: 0.6197 - loss: 0.4589 - mae: 0.5353 - rmse: 0.6762 - smape: 0.9702 - val_ia: 0.4444 - val_loss: 1.0277 - val_mae: 0.8029 - val_rmse: 0.9734 - val_smape: 1.2597

Epoch 13/32

287/287 - 1s - 3ms/step - ia: 0.6209 - loss: 0.4564 - mae: 0.5344 - rmse: 0.6744 - smape: 0.9692 - val_ia: 0.4420 - val_loss: 1.0481 - val_mae: 0.8138 - val_rmse: 0.9791 - val_smape: 1.2695

Epoch 14/32

287/287 - 1s - 3ms/step - ia: 0.6195 - loss: 0.4580 - mae: 0.5356 - rmse: 0.6753 - smape: 0.9658 - val_ia: 0.4492 - val_loss: 0.9688 - val_mae: 0.7799 - val_rmse: 0.9431 - val_smape: 1.2544

Epoch 15/32

287/287 - 1s - 3ms/step - ia: 0.6201 - loss: 0.4567 - mae: 0.5350 - rmse: 0.6742 - smape: 0.9629 - val_ia: 0.4582 - val_loss: 0.9644 - val_mae: 0.7746 - val_rmse: 0.9391 - val_smape: 1.2422

Epoch 16/32

287/287 - 1s - 3ms/step - ia: 0.6231 - loss: 0.4525 - mae: 0.5313 - rmse: 0.6713 - smape: 0.9578 - val_ia: 0.4539 - val_loss: 0.9924 - val_mae: 0.7892 - val_rmse: 0.9551 - val_smape: 1.2488

Epoch 17/32

287/287 - 1s - 3ms/step - ia: 0.6226 - loss: 0.4527 - mae: 0.5318 - rmse: 0.6711 - smape: 0.9620 - val_ia: 0.4538 - val_loss: 0.9723 - val_mae: 0.7839 - val_rmse: 0.9409 - val_smape: 1.2641

Epoch 18/32

287/287 - 1s - 5ms/step - ia: 0.6218 - loss: 0.4531 - mae: 0.5320 - rmse: 0.6714 - smape: 0.9639 - val_ia: 0.4564 - val_loss: 0.9818 - val_mae: 0.7839 - val_rmse: 0.9463 - val_smape: 1.2555

Epoch 19/32

287/287 - 1s - 3ms/step - ia: 0.6224 - loss: 0.4514 - mae: 0.5315 - rmse: 0.6707 - smape: 0.9645 - val_ia: 0.4541 - val_loss: 0.9659 - val_mae: 0.7787 - val_rmse: 0.9391 - val_smape: 1.2547

Epoch 20/32

287/287 - 1s - 3ms/step - ia: 0.6226 - loss: 0.4516 - mae: 0.5311 - rmse: 0.6708 - smape: 0.9616 - val_ia: 0.4663 - val_loss: 0.9153 - val_mae: 0.7541 - val_rmse: 0.9139 - val_smape: 1.2342

Epoch 21/32

287/287 - 1s - 3ms/step - ia: 0.6266 - loss: 0.4467 - mae: 0.5263 - rmse: 0.6668 - smape: 0.9532 - val_ia: 0.4629 - val_loss: 0.9407 - val_mae: 0.7641 - val_rmse: 0.9288 - val_smape: 1.2388

Epoch 22/32

287/287 - 1s - 3ms/step - ia: 0.6246 - loss: 0.4478 - mae: 0.5287 - rmse: 0.6678 - smape: 0.9625 - val_ia: 0.4616 - val_loss: 0.9422 - val_mae: 0.7659 - val_rmse: 0.9277 - val_smape: 1.2476

Epoch 23/32

287/287 - 1s - 3ms/step - ia: 0.6261 - loss: 0.4459 - mae: 0.5271 - rmse: 0.6666 - smape: 0.9584 - val_ia: 0.4698 - val_loss: 0.8947 - val_mae: 0.7484 - val_rmse: 0.9035 - val_smape: 1.2315

Epoch 24/32

287/287 - 1s - 3ms/step - ia: 0.6244 - loss: 0.4481 - mae: 0.5287 - rmse: 0.6681 - smape: 0.9560 - val_ia: 0.4642 - val_loss: 0.9577 - val_mae: 0.7742 - val_rmse: 0.9362 - val_smape: 1.2459

Epoch 25/32

287/287 - 1s - 5ms/step - ia: 0.6275 - loss: 0.4444 - mae: 0.5259 - rmse: 0.6652 - smape: 0.9534 - val_ia: 0.4707 - val_loss: 0.9241 - val_mae: 0.7577 - val_rmse: 0.9193 - val_smape: 1.2288

Epoch 26/32

287/287 - 2s - 6ms/step - ia: 0.6292 - loss: 0.4410 - mae: 0.5235 - rmse: 0.6627 - smape: 0.9538 - val_ia: 0.4662 - val_loss: 0.8895 - val_mae: 0.7464 - val_rmse: 0.9007 - val_smape: 1.2445

Epoch 27/32

287/287 - 1s - 5ms/step - ia: 0.6289 - loss: 0.4420 - mae: 0.5232 - rmse: 0.6634 - smape: 0.9529 - val_ia: 0.4682 - val_loss: 0.9372 - val_mae: 0.7671 - val_rmse: 0.9234 - val_smape: 1.2425

Epoch 28/32

287/287 - 1s - 3ms/step - ia: 0.6279 - loss: 0.4423 - mae: 0.5252 - rmse: 0.6635 - smape: 0.9534 - val_ia: 0.4759 - val_loss: 0.8950 - val_mae: 0.7445 - val_rmse: 0.9031 - val_smape: 1.2226

Epoch 29/32

287/287 - 1s - 3ms/step - ia: 0.6265 - loss: 0.4447 - mae: 0.5260 - rmse: 0.6653 - smape: 0.9535 - val_ia: 0.4778 - val_loss: 0.8889 - val_mae: 0.7459 - val_rmse: 0.8945 - val_smape: 1.2360

Epoch 30/32

287/287 - 1s - 5ms/step - ia: 0.6302 - loss: 0.4375 - mae: 0.5220 - rmse: 0.6600 - smape: 0.9494 - val_ia: 0.4717 - val_loss: 0.9367 - val_mae: 0.7664 - val_rmse: 0.9209 - val_smape: 1.2388

Epoch 31/32

287/287 - 1s - 3ms/step - ia: 0.6267 - loss: 0.4434 - mae: 0.5257 - rmse: 0.6646 - smape: 0.9570 - val_ia: 0.4740 - val_loss: 0.8890 - val_mae: 0.7436 - val_rmse: 0.8999 - val_smape: 1.2292

Epoch 32/32

287/287 - 1s - 5ms/step - ia: 0.6299 - loss: 0.4406 - mae: 0.5223 - rmse: 0.6625 - smape: 0.9528 - val_ia: 0.4730 - val_loss: 0.9292 - val_mae: 0.7590 - val_rmse: 0.9173 - val_smape: 1.2320

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 16s 99ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
143/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

100%|██████████| 50/50 [4:25:51<00:00, 319.04s/trial, best loss: 0.15528137861599256]
{'activation': 1, 'batch': 1, 'dropout': 0.30000000000000004, 'epochs': 4, 'layers': 1.0, 'learning_rate': 0.008417176284345648, 'units': 4}

In [23]:
print(best)

{'activation': 1, 'batch': 1, 'dropout': 0.30000000000000004, 'epochs': 4, 'layers': 1.0, 'learning_rate': 0.008417176284345648, 'units': 4}