Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\colab\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'epochs': hp.choice('epochs', [2 ** i for i in range(3, 9)]),  # Número de épocas de entrenamiento
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 24
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [16]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [17]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (43765, 72)

Se dividen nuevamente los conjuntos de datos

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 72)
Las dimensiones de testX son:  (8797, 72)
Las dimensiones de valX son:  (4333, 72)

In [19]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [20]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [21]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [22]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=params['epochs'],
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [23]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=50, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 25s - 26ms/step - ia: 0.2798 - loss: 3.7096 - mae: 1.2781 - rmse: 1.7388 - smape: 1.4483 - val_ia: 0.2520 - val_loss: 0.8778 - val_mae: 0.7035 - val_rmse: 0.7990 - val_smape: 1.4732

Epoch 2/128

958/958 - 8s - 8ms/step - ia: 0.2924 - loss: 1.2283 - mae: 0.8283 - rmse: 1.0863 - smape: 1.4558 - val_ia: 0.2471 - val_loss: 0.8564 - val_mae: 0.6960 - val_rmse: 0.7814 - val_smape: 1.5313

Epoch 3/128

958/958 - 7s - 8ms/step - ia: 0.2832 - loss: 1.0564 - mae: 0.7700 - rmse: 1.0076 - smape: 1.4796 - val_ia: 0.2466 - val_loss: 0.8457 - val_mae: 0.6860 - val_rmse: 0.7699 - val_smape: 1.5145

Epoch 4/128

958/958 - 8s - 8ms/step - ia: 0.2814 - loss: 0.9885 - mae: 0.7439 - rmse: 0.9753 - smape: 1.4904 - val_ia: 0.2481 - val_loss: 0.8200 - val_mae: 0.6796 - val_rmse: 0.7642 - val_smape: 1.4673

Epoch 5/128

958/958 - 4s - 4ms/step - ia: 0.2885 - loss: 0.9497 - mae: 0.7285 - rmse: 0.9556 - smape: 1.4810 - val_ia: 0.2493 - val_loss: 0.8126 - val_mae: 0.6727 - val_rmse: 0.7580 - val_smape: 1.4394

Epoch 6/128

958/958 - 3s - 3ms/step - ia: 0.2922 - loss: 0.9308 - mae: 0.7183 - rmse: 0.9432 - smape: 1.4781 - val_ia: 0.2512 - val_loss: 0.8052 - val_mae: 0.6694 - val_rmse: 0.7556 - val_smape: 1.4235

Epoch 7/128

958/958 - 7s - 7ms/step - ia: 0.2978 - loss: 0.9150 - mae: 0.7106 - rmse: 0.9363 - smape: 1.4705 - val_ia: 0.2527 - val_loss: 0.7975 - val_mae: 0.6663 - val_rmse: 0.7533 - val_smape: 1.4066

Epoch 8/128

958/958 - 5s - 6ms/step - ia: 0.3033 - loss: 0.9027 - mae: 0.7048 - rmse: 0.9295 - smape: 1.4630 - val_ia: 0.2550 - val_loss: 0.7806 - val_mae: 0.6583 - val_rmse: 0.7471 - val_smape: 1.3565

Epoch 9/128

958/958 - 6s - 6ms/step - ia: 0.3060 - loss: 0.8938 - mae: 0.7022 - rmse: 0.9256 - smape: 1.4599 - val_ia: 0.2551 - val_loss: 0.7801 - val_mae: 0.6557 - val_rmse: 0.7437 - val_smape: 1.3572

Epoch 10/128

958/958 - 4s - 5ms/step - ia: 0.3141 - loss: 0.8809 - mae: 0.6970 - rmse: 0.9195 - smape: 1.4417 - val_ia: 0.2561 - val_loss: 0.7769 - val_mae: 0.6537 - val_rmse: 0.7420 - val_smape: 1.3469

Epoch 11/128

958/958 - 7s - 7ms/step - ia: 0.3195 - loss: 0.8736 - mae: 0.6949 - rmse: 0.9153 - smape: 1.4349 - val_ia: 0.2544 - val_loss: 0.7841 - val_mae: 0.6590 - val_rmse: 0.7467 - val_smape: 1.3730

Epoch 12/128

958/958 - 8s - 9ms/step - ia: 0.3207 - loss: 0.8737 - mae: 0.6932 - rmse: 0.9159 - smape: 1.4299 - val_ia: 0.2525 - val_loss: 0.7901 - val_mae: 0.6626 - val_rmse: 0.7487 - val_smape: 1.4016

Epoch 13/128

958/958 - 3s - 3ms/step - ia: 0.3178 - loss: 0.8713 - mae: 0.6933 - rmse: 0.9147 - smape: 1.4350 - val_ia: 0.2569 - val_loss: 0.7743 - val_mae: 0.6549 - val_rmse: 0.7436 - val_smape: 1.3479

Epoch 14/128

958/958 - 3s - 3ms/step - ia: 0.3232 - loss: 0.8731 - mae: 0.6915 - rmse: 0.9134 - smape: 1.4270 - val_ia: 0.2543 - val_loss: 0.7883 - val_mae: 0.6633 - val_rmse: 0.7511 - val_smape: 1.3840

Epoch 15/128

958/958 - 4s - 4ms/step - ia: 0.3187 - loss: 0.8710 - mae: 0.6920 - rmse: 0.9136 - smape: 1.4308 - val_ia: 0.2550 - val_loss: 0.7814 - val_mae: 0.6574 - val_rmse: 0.7455 - val_smape: 1.3605

Epoch 16/128

958/958 - 8s - 8ms/step - ia: 0.3266 - loss: 0.8633 - mae: 0.6885 - rmse: 0.9094 - smape: 1.4146 - val_ia: 0.2567 - val_loss: 0.7715 - val_mae: 0.6524 - val_rmse: 0.7400 - val_smape: 1.3490

Epoch 17/128

958/958 - 6s - 7ms/step - ia: 0.3264 - loss: 0.8601 - mae: 0.6877 - rmse: 0.9093 - smape: 1.4208 - val_ia: 0.2591 - val_loss: 0.7667 - val_mae: 0.6492 - val_rmse: 0.7406 - val_smape: 1.3101

Epoch 18/128

958/958 - 5s - 6ms/step - ia: 0.3270 - loss: 0.8658 - mae: 0.6884 - rmse: 0.9114 - smape: 1.4166 - val_ia: 0.2550 - val_loss: 0.7762 - val_mae: 0.6534 - val_rmse: 0.7404 - val_smape: 1.3608

Epoch 19/128

958/958 - 5s - 5ms/step - ia: 0.3311 - loss: 0.8580 - mae: 0.6867 - rmse: 0.9074 - smape: 1.4079 - val_ia: 0.2551 - val_loss: 0.7729 - val_mae: 0.6541 - val_rmse: 0.7416 - val_smape: 1.3536

Epoch 20/128

958/958 - 6s - 7ms/step - ia: 0.3288 - loss: 0.8583 - mae: 0.6866 - rmse: 0.9075 - smape: 1.4124 - val_ia: 0.2583 - val_loss: 0.7670 - val_mae: 0.6477 - val_rmse: 0.7372 - val_smape: 1.3197

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.3277 - loss: 0.8618 - mae: 0.6877 - rmse: 0.9085 - smape: 1.4130 - val_ia: 0.2578 - val_loss: 0.7730 - val_mae: 0.6519 - val_rmse: 0.7407 - val_smape: 1.3393

Epoch 22/128

958/958 - 6s - 6ms/step - ia: 0.3339 - loss: 0.8577 - mae: 0.6850 - rmse: 0.9057 - smape: 1.4018 - val_ia: 0.2561 - val_loss: 0.7770 - val_mae: 0.6548 - val_rmse: 0.7430 - val_smape: 1.3537

Epoch 23/128

958/958 - 6s - 6ms/step - ia: 0.3358 - loss: 0.8523 - mae: 0.6835 - rmse: 0.9040 - smape: 1.3997 - val_ia: 0.2575 - val_loss: 0.7674 - val_mae: 0.6508 - val_rmse: 0.7401 - val_smape: 1.3292

Epoch 24/128

958/958 - 9s - 9ms/step - ia: 0.3304 - loss: 0.8565 - mae: 0.6852 - rmse: 0.9059 - smape: 1.4066 - val_ia: 0.2589 - val_loss: 0.7606 - val_mae: 0.6465 - val_rmse: 0.7362 - val_smape: 1.3136

Epoch 25/128

958/958 - 6s - 6ms/step - ia: 0.3376 - loss: 0.8498 - mae: 0.6830 - rmse: 0.9020 - smape: 1.3984 - val_ia: 0.2556 - val_loss: 0.7713 - val_mae: 0.6518 - val_rmse: 0.7401 - val_smape: 1.3419

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.3331 - loss: 0.8590 - mae: 0.6841 - rmse: 0.9070 - smape: 1.4022 - val_ia: 0.2538 - val_loss: 0.7844 - val_mae: 0.6589 - val_rmse: 0.7453 - val_smape: 1.3852

Epoch 27/128

958/958 - 5s - 5ms/step - ia: 0.3364 - loss: 0.8503 - mae: 0.6823 - rmse: 0.9028 - smape: 1.3981 - val_ia: 0.2585 - val_loss: 0.7620 - val_mae: 0.6464 - val_rmse: 0.7360 - val_smape: 1.3113

Epoch 28/128

958/958 - 7s - 7ms/step - ia: 0.3317 - loss: 0.8551 - mae: 0.6849 - rmse: 0.9061 - smape: 1.4060 - val_ia: 0.2569 - val_loss: 0.7758 - val_mae: 0.6552 - val_rmse: 0.7443 - val_smape: 1.3469

Epoch 29/128

958/958 - 6s - 6ms/step - ia: 0.3382 - loss: 0.8497 - mae: 0.6820 - rmse: 0.9031 - smape: 1.3953 - val_ia: 0.2579 - val_loss: 0.7659 - val_mae: 0.6486 - val_rmse: 0.7377 - val_smape: 1.3266

Epoch 30/128

958/958 - 3s - 3ms/step - ia: 0.3347 - loss: 0.8523 - mae: 0.6833 - rmse: 0.9058 - smape: 1.3960 - val_ia: 0.2567 - val_loss: 0.7728 - val_mae: 0.6515 - val_rmse: 0.7393 - val_smape: 1.3516

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.3362 - loss: 0.8538 - mae: 0.6825 - rmse: 0.9053 - smape: 1.3942 - val_ia: 0.2559 - val_loss: 0.7750 - val_mae: 0.6533 - val_rmse: 0.7407 - val_smape: 1.3579

Epoch 32/128

958/958 - 6s - 6ms/step - ia: 0.3330 - loss: 0.8543 - mae: 0.6826 - rmse: 0.9042 - smape: 1.3990 - val_ia: 0.2594 - val_loss: 0.7631 - val_mae: 0.6471 - val_rmse: 0.7375 - val_smape: 1.3088

Epoch 33/128

958/958 - 4s - 4ms/step - ia: 0.3340 - loss: 0.8527 - mae: 0.6832 - rmse: 0.9048 - smape: 1.4004 - val_ia: 0.2602 - val_loss: 0.7601 - val_mae: 0.6445 - val_rmse: 0.7356 - val_smape: 1.2956

Epoch 34/128

958/958 - 4s - 4ms/step - ia: 0.3421 - loss: 0.8471 - mae: 0.6804 - rmse: 0.9022 - smape: 1.3852 - val_ia: 0.2578 - val_loss: 0.7662 - val_mae: 0.6493 - val_rmse: 0.7381 - val_smape: 1.3340

Epoch 35/128

958/958 - 3s - 3ms/step - ia: 0.3330 - loss: 0.8559 - mae: 0.6847 - rmse: 0.9059 - smape: 1.3978 - val_ia: 0.2586 - val_loss: 0.7668 - val_mae: 0.6500 - val_rmse: 0.7396 - val_smape: 1.3236

Epoch 36/128

958/958 - 6s - 7ms/step - ia: 0.3355 - loss: 0.8516 - mae: 0.6822 - rmse: 0.9032 - smape: 1.3941 - val_ia: 0.2571 - val_loss: 0.7678 - val_mae: 0.6497 - val_rmse: 0.7384 - val_smape: 1.3299

Epoch 37/128

958/958 - 4s - 5ms/step - ia: 0.3368 - loss: 0.8492 - mae: 0.6816 - rmse: 0.9031 - smape: 1.3898 - val_ia: 0.2599 - val_loss: 0.7594 - val_mae: 0.6455 - val_rmse: 0.7364 - val_smape: 1.2989

Epoch 38/128

958/958 - 3s - 3ms/step - ia: 0.3405 - loss: 0.8479 - mae: 0.6814 - rmse: 0.9022 - smape: 1.3876 - val_ia: 0.2584 - val_loss: 0.7666 - val_mae: 0.6506 - val_rmse: 0.7399 - val_smape: 1.3312

Epoch 39/128

958/958 - 3s - 3ms/step - ia: 0.3356 - loss: 0.8512 - mae: 0.6823 - rmse: 0.9030 - smape: 1.3947 - val_ia: 0.2580 - val_loss: 0.7654 - val_mae: 0.6472 - val_rmse: 0.7356 - val_smape: 1.3256

Epoch 40/128

958/958 - 6s - 7ms/step - ia: 0.3378 - loss: 0.8510 - mae: 0.6821 - rmse: 0.9028 - smape: 1.3885 - val_ia: 0.2563 - val_loss: 0.7726 - val_mae: 0.6540 - val_rmse: 0.7414 - val_smape: 1.3579

Epoch 41/128

958/958 - 5s - 5ms/step - ia: 0.3404 - loss: 0.8439 - mae: 0.6816 - rmse: 0.9008 - smape: 1.3887 - val_ia: 0.2572 - val_loss: 0.7685 - val_mae: 0.6503 - val_rmse: 0.7385 - val_smape: 1.3382

Epoch 42/128

958/958 - 5s - 6ms/step - ia: 0.3367 - loss: 0.8517 - mae: 0.6825 - rmse: 0.9036 - smape: 1.3957 - val_ia: 0.2578 - val_loss: 0.7706 - val_mae: 0.6501 - val_rmse: 0.7385 - val_smape: 1.3417

Epoch 43/128

958/958 - 3s - 3ms/step - ia: 0.3333 - loss: 0.8537 - mae: 0.6818 - rmse: 0.9045 - smape: 1.3898 - val_ia: 0.2589 - val_loss: 0.7645 - val_mae: 0.6485 - val_rmse: 0.7380 - val_smape: 1.3289

Epoch 44/128

958/958 - 4s - 4ms/step - ia: 0.3425 - loss: 0.8448 - mae: 0.6814 - rmse: 0.9002 - smape: 1.3856 - val_ia: 0.2557 - val_loss: 0.7752 - val_mae: 0.6521 - val_rmse: 0.7391 - val_smape: 1.3592

Epoch 45/128

958/958 - 4s - 4ms/step - ia: 0.3373 - loss: 0.8492 - mae: 0.6808 - rmse: 0.9021 - smape: 1.3894 - val_ia: 0.2613 - val_loss: 0.7565 - val_mae: 0.6416 - val_rmse: 0.7332 - val_smape: 1.2788

Epoch 46/128

958/958 - 4s - 4ms/step - ia: 0.3390 - loss: 0.8503 - mae: 0.6807 - rmse: 0.9037 - smape: 1.3886 - val_ia: 0.2585 - val_loss: 0.7690 - val_mae: 0.6509 - val_rmse: 0.7408 - val_smape: 1.3305

Epoch 47/128

958/958 - 5s - 5ms/step - ia: 0.3349 - loss: 0.8537 - mae: 0.6832 - rmse: 0.9061 - smape: 1.3934 - val_ia: 0.2580 - val_loss: 0.7650 - val_mae: 0.6488 - val_rmse: 0.7371 - val_smape: 1.3343

Epoch 48/128

958/958 - 3s - 3ms/step - ia: 0.3376 - loss: 0.8528 - mae: 0.6829 - rmse: 0.9042 - smape: 1.3926 - val_ia: 0.2557 - val_loss: 0.7715 - val_mae: 0.6535 - val_rmse: 0.7412 - val_smape: 1.3525

Epoch 49/128

958/958 - 6s - 6ms/step - ia: 0.3358 - loss: 0.8533 - mae: 0.6822 - rmse: 0.9043 - smape: 1.3933 - val_ia: 0.2575 - val_loss: 0.7676 - val_mae: 0.6515 - val_rmse: 0.7401 - val_smape: 1.3425

Epoch 50/128

958/958 - 3s - 3ms/step - ia: 0.3420 - loss: 0.8464 - mae: 0.6788 - rmse: 0.9014 - smape: 1.3799 - val_ia: 0.2591 - val_loss: 0.7647 - val_mae: 0.6464 - val_rmse: 0.7361 - val_smape: 1.3168

Epoch 51/128

958/958 - 2s - 2ms/step - ia: 0.3398 - loss: 0.8488 - mae: 0.6800 - rmse: 0.9022 - smape: 1.3850 - val_ia: 0.2620 - val_loss: 0.7581 - val_mae: 0.6416 - val_rmse: 0.7338 - val_smape: 1.2758

Epoch 52/128

958/958 - 2s - 2ms/step - ia: 0.3410 - loss: 0.8456 - mae: 0.6807 - rmse: 0.8993 - smape: 1.3869 - val_ia: 0.2604 - val_loss: 0.7601 - val_mae: 0.6456 - val_rmse: 0.7362 - val_smape: 1.3072

Epoch 53/128

958/958 - 2s - 3ms/step - ia: 0.3387 - loss: 0.8490 - mae: 0.6819 - rmse: 0.9020 - smape: 1.3906 - val_ia: 0.2571 - val_loss: 0.7695 - val_mae: 0.6498 - val_rmse: 0.7373 - val_smape: 1.3444

Epoch 54/128

958/958 - 2s - 2ms/step - ia: 0.3406 - loss: 0.8460 - mae: 0.6793 - rmse: 0.9012 - smape: 1.3848 - val_ia: 0.2586 - val_loss: 0.7642 - val_mae: 0.6479 - val_rmse: 0.7368 - val_smape: 1.3266

Epoch 55/128

958/958 - 3s - 3ms/step - ia: 0.3393 - loss: 0.8493 - mae: 0.6811 - rmse: 0.9032 - smape: 1.3893 - val_ia: 0.2567 - val_loss: 0.7715 - val_mae: 0.6528 - val_rmse: 0.7409 - val_smape: 1.3499

Epoch 56/128

958/958 - 5s - 5ms/step - ia: 0.3395 - loss: 0.8482 - mae: 0.6815 - rmse: 0.9014 - smape: 1.3875 - val_ia: 0.2583 - val_loss: 0.7642 - val_mae: 0.6495 - val_rmse: 0.7381 - val_smape: 1.3320

Epoch 57/128

958/958 - 11s - 12ms/step - ia: 0.3317 - loss: 0.8531 - mae: 0.6837 - rmse: 0.9055 - smape: 1.3998 - val_ia: 0.2596 - val_loss: 0.7620 - val_mae: 0.6453 - val_rmse: 0.7347 - val_smape: 1.3136

Epoch 58/128

958/958 - 8s - 8ms/step - ia: 0.3385 - loss: 0.8516 - mae: 0.6817 - rmse: 0.9036 - smape: 1.3861 - val_ia: 0.2572 - val_loss: 0.7697 - val_mae: 0.6521 - val_rmse: 0.7403 - val_smape: 1.3452

Epoch 59/128

958/958 - 7s - 7ms/step - ia: 0.3358 - loss: 0.8520 - mae: 0.6822 - rmse: 0.9035 - smape: 1.3891 - val_ia: 0.2590 - val_loss: 0.7619 - val_mae: 0.6457 - val_rmse: 0.7347 - val_smape: 1.3169

Epoch 60/128

958/958 - 5s - 5ms/step - ia: 0.3408 - loss: 0.8500 - mae: 0.6801 - rmse: 0.9025 - smape: 1.3836 - val_ia: 0.2592 - val_loss: 0.7622 - val_mae: 0.6489 - val_rmse: 0.7386 - val_smape: 1.3254

Epoch 60: early stopping

Restoring model weights from the end of the best epoch: 45.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:05 483ms/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

  2%|▏         | 1/50 [05:36<4:34:57, 336.68s/trial, best loss: 0.7822532309140019]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

120/120 - 15s - 127ms/step - ia: 0.3598 - loss: 0.8335 - mae: 0.6736 - rmse: 0.9098 - smape: 1.3268 - val_ia: 0.3562 - val_loss: 0.7574 - val_mae: 0.6330 - val_rmse: 0.8023 - val_smape: 1.2286

Epoch 2/16

120/120 - 2s - 14ms/step - ia: 0.4181 - loss: 0.7758 - mae: 0.6427 - rmse: 0.8787 - smape: 1.2385 - val_ia: 0.3557 - val_loss: 0.7586 - val_mae: 0.6494 - val_rmse: 0.8125 - val_smape: 1.2876

Epoch 3/16

120/120 - 1s - 6ms/step - ia: 0.4345 - loss: 0.7541 - mae: 0.6311 - rmse: 0.8653 - smape: 1.2170 - val_ia: 0.3601 - val_loss: 0.7759 - val_mae: 0.6552 - val_rmse: 0.8229 - val_smape: 1.2848

Epoch 4/16

120/120 - 1s - 5ms/step - ia: 0.4473 - loss: 0.7383 - mae: 0.6231 - rmse: 0.8569 - smape: 1.1983 - val_ia: 0.3567 - val_loss: 0.7765 - val_mae: 0.6596 - val_rmse: 0.8238 - val_smape: 1.2966

Epoch 5/16

120/120 - 1s - 6ms/step - ia: 0.4546 - loss: 0.7241 - mae: 0.6184 - rmse: 0.8482 - smape: 1.1894 - val_ia: 0.3870 - val_loss: 0.7885 - val_mae: 0.6438 - val_rmse: 0.8232 - val_smape: 1.2157

Epoch 6/16

120/120 - 0s - 4ms/step - ia: 0.4642 - loss: 0.7102 - mae: 0.6123 - rmse: 0.8398 - smape: 1.1779 - val_ia: 0.3811 - val_loss: 0.7619 - val_mae: 0.6365 - val_rmse: 0.8077 - val_smape: 1.2397

Epoch 7/16

120/120 - 0s - 4ms/step - ia: 0.4722 - loss: 0.6966 - mae: 0.6051 - rmse: 0.8326 - smape: 1.1666 - val_ia: 0.3698 - val_loss: 0.7905 - val_mae: 0.6578 - val_rmse: 0.8281 - val_smape: 1.2687

Epoch 8/16

120/120 - 1s - 6ms/step - ia: 0.4810 - loss: 0.6807 - mae: 0.5989 - rmse: 0.8228 - smape: 1.1570 - val_ia: 0.3805 - val_loss: 0.7666 - val_mae: 0.6358 - val_rmse: 0.8086 - val_smape: 1.2201

Epoch 9/16

120/120 - 1s - 7ms/step - ia: 0.4879 - loss: 0.6666 - mae: 0.5930 - rmse: 0.8136 - smape: 1.1468 - val_ia: 0.3853 - val_loss: 0.8289 - val_mae: 0.6526 - val_rmse: 0.8383 - val_smape: 1.2142

Epoch 10/16

120/120 - 1s - 10ms/step - ia: 0.4969 - loss: 0.6529 - mae: 0.5862 - rmse: 0.8062 - smape: 1.1349 - val_ia: 0.3755 - val_loss: 0.8321 - val_mae: 0.6698 - val_rmse: 0.8505 - val_smape: 1.2648

Epoch 11/16

120/120 - 1s - 6ms/step - ia: 0.5014 - loss: 0.6426 - mae: 0.5830 - rmse: 0.7995 - smape: 1.1331 - val_ia: 0.3919 - val_loss: 0.8258 - val_mae: 0.6554 - val_rmse: 0.8388 - val_smape: 1.2159

Epoch 12/16

120/120 - 1s - 5ms/step - ia: 0.5136 - loss: 0.6220 - mae: 0.5734 - rmse: 0.7869 - smape: 1.1139 - val_ia: 0.3748 - val_loss: 0.8780 - val_mae: 0.6771 - val_rmse: 0.8652 - val_smape: 1.2648

Epoch 13/16

120/120 - 1s - 7ms/step - ia: 0.5198 - loss: 0.6100 - mae: 0.5685 - rmse: 0.7789 - smape: 1.1086 - val_ia: 0.3849 - val_loss: 0.8111 - val_mae: 0.6460 - val_rmse: 0.8252 - val_smape: 1.2116

Epoch 14/16

120/120 - 1s - 6ms/step - ia: 0.5280 - loss: 0.5968 - mae: 0.5620 - rmse: 0.7706 - smape: 1.0996 - val_ia: 0.3837 - val_loss: 0.8484 - val_mae: 0.6667 - val_rmse: 0.8493 - val_smape: 1.2458

Epoch 15/16

120/120 - 1s - 5ms/step - ia: 0.5348 - loss: 0.5818 - mae: 0.5559 - rmse: 0.7611 - smape: 1.0928 - val_ia: 0.3916 - val_loss: 0.8690 - val_mae: 0.6626 - val_rmse: 0.8540 - val_smape: 1.2005

Epoch 16/16

120/120 - 1s - 5ms/step - ia: 0.5397 - loss: 0.5730 - mae: 0.5525 - rmse: 0.7550 - smape: 1.0861 - val_ia: 0.3860 - val_loss: 0.8853 - val_mae: 0.6847 - val_rmse: 0.8752 - val_smape: 1.2566

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 20s 155ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  4%|▍         | 2/50 [06:05<2:04:34, 155.72s/trial, best loss: 0.7811234802454173]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 22s - 46ms/step - ia: 0.2215 - loss: 1.1032 - mae: 0.7997 - rmse: 1.0392 - smape: 1.5768 - val_ia: 0.2554 - val_loss: 0.9864 - val_mae: 0.7781 - val_rmse: 0.8928 - val_smape: 1.7086

Epoch 2/8

479/479 - 3s - 7ms/step - ia: 0.2210 - loss: 1.0925 - mae: 0.7936 - rmse: 1.0344 - smape: 1.5762 - val_ia: 0.2548 - val_loss: 0.9800 - val_mae: 0.7743 - val_rmse: 0.8886 - val_smape: 1.7124

Epoch 3/8

479/479 - 4s - 8ms/step - ia: 0.2160 - loss: 1.0999 - mae: 0.7967 - rmse: 1.0376 - smape: 1.5846 - val_ia: 0.2541 - val_loss: 0.9742 - val_mae: 0.7707 - val_rmse: 0.8848 - val_smape: 1.7164

Epoch 4/8

479/479 - 1s - 3ms/step - ia: 0.2196 - loss: 1.0800 - mae: 0.7887 - rmse: 1.0273 - smape: 1.5809 - val_ia: 0.2535 - val_loss: 0.9692 - val_mae: 0.7676 - val_rmse: 0.8815 - val_smape: 1.7200

Epoch 5/8

479/479 - 2s - 5ms/step - ia: 0.2186 - loss: 1.0786 - mae: 0.7871 - rmse: 1.0272 - smape: 1.5860 - val_ia: 0.2530 - val_loss: 0.9645 - val_mae: 0.7647 - val_rmse: 0.8784 - val_smape: 1.7236

Epoch 6/8

479/479 - 2s - 3ms/step - ia: 0.2136 - loss: 1.0784 - mae: 0.7868 - rmse: 1.0281 - smape: 1.5893 - val_ia: 0.2525 - val_loss: 0.9604 - val_mae: 0.7623 - val_rmse: 0.8758 - val_smape: 1.7267

Epoch 7/8

479/479 - 1s - 2ms/step - ia: 0.2118 - loss: 1.0746 - mae: 0.7849 - rmse: 1.0271 - smape: 1.5894 - val_ia: 0.2520 - val_loss: 0.9567 - val_mae: 0.7599 - val_rmse: 0.8733 - val_smape: 1.7294

Epoch 8/8

479/479 - 1s - 3ms/step - ia: 0.2130 - loss: 1.0648 - mae: 0.7810 - rmse: 1.0212 - smape: 1.5914 - val_ia: 0.2515 - val_loss: 0.9534 - val_mae: 0.7578 - val_rmse: 0.8711 - val_smape: 1.7320

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 220ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

  6%|▌         | 3/50 [06:43<1:19:54, 102.02s/trial, best loss: 0.7811234802454173]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

240/240 - 15s - 64ms/step - ia: 0.2921 - loss: 1.9079 - mae: 1.0725 - rmse: 1.3773 - smape: 1.4363 - val_ia: 0.2996 - val_loss: 1.1522 - val_mae: 0.8315 - val_rmse: 1.0009 - val_smape: 1.5033

Epoch 2/32

240/240 - 3s - 12ms/step - ia: 0.3040 - loss: 1.7798 - mae: 1.0323 - rmse: 1.3293 - smape: 1.4170 - val_ia: 0.3048 - val_loss: 1.0444 - val_mae: 0.7881 - val_rmse: 0.9521 - val_smape: 1.4690

Epoch 3/32

240/240 - 3s - 14ms/step - ia: 0.3146 - loss: 1.6681 - mae: 1.0010 - rmse: 1.2886 - smape: 1.4059 - val_ia: 0.3097 - val_loss: 0.9764 - val_mae: 0.7569 - val_rmse: 0.9182 - val_smape: 1.4224

Epoch 4/32

240/240 - 3s - 11ms/step - ia: 0.3200 - loss: 1.6288 - mae: 0.9873 - rmse: 1.2727 - smape: 1.3955 - val_ia: 0.3143 - val_loss: 0.9332 - val_mae: 0.7349 - val_rmse: 0.8951 - val_smape: 1.3811

Epoch 5/32

240/240 - 4s - 17ms/step - ia: 0.3298 - loss: 1.5609 - mae: 0.9644 - rmse: 1.2442 - smape: 1.3821 - val_ia: 0.3180 - val_loss: 0.9074 - val_mae: 0.7200 - val_rmse: 0.8800 - val_smape: 1.3523

Epoch 6/32

240/240 - 3s - 13ms/step - ia: 0.3378 - loss: 1.4926 - mae: 0.9449 - rmse: 1.2171 - smape: 1.3713 - val_ia: 0.3206 - val_loss: 0.8882 - val_mae: 0.7085 - val_rmse: 0.8682 - val_smape: 1.3270

Epoch 7/32

240/240 - 4s - 16ms/step - ia: 0.3399 - loss: 1.4683 - mae: 0.9355 - rmse: 1.2074 - smape: 1.3700 - val_ia: 0.3223 - val_loss: 0.8741 - val_mae: 0.6996 - val_rmse: 0.8592 - val_smape: 1.3087

Epoch 8/32

240/240 - 6s - 25ms/step - ia: 0.3468 - loss: 1.4302 - mae: 0.9180 - rmse: 1.1918 - smape: 1.3577 - val_ia: 0.3232 - val_loss: 0.8638 - val_mae: 0.6932 - val_rmse: 0.8523 - val_smape: 1.2993

Epoch 9/32

240/240 - 2s - 10ms/step - ia: 0.3423 - loss: 1.4151 - mae: 0.9194 - rmse: 1.1852 - smape: 1.3677 - val_ia: 0.3247 - val_loss: 0.8569 - val_mae: 0.6890 - val_rmse: 0.8480 - val_smape: 1.2913

Epoch 10/32

240/240 - 3s - 13ms/step - ia: 0.3478 - loss: 1.3949 - mae: 0.9096 - rmse: 1.1765 - smape: 1.3582 - val_ia: 0.3253 - val_loss: 0.8490 - val_mae: 0.6838 - val_rmse: 0.8427 - val_smape: 1.2816

Epoch 11/32

240/240 - 2s - 8ms/step - ia: 0.3505 - loss: 1.3691 - mae: 0.8965 - rmse: 1.1664 - smape: 1.3511 - val_ia: 0.3255 - val_loss: 0.8418 - val_mae: 0.6798 - val_rmse: 0.8381 - val_smape: 1.2754

Epoch 12/32

240/240 - 2s - 7ms/step - ia: 0.3465 - loss: 1.3638 - mae: 0.8946 - rmse: 1.1635 - smape: 1.3565 - val_ia: 0.3257 - val_loss: 0.8361 - val_mae: 0.6765 - val_rmse: 0.8343 - val_smape: 1.2704

Epoch 13/32

240/240 - 3s - 11ms/step - ia: 0.3503 - loss: 1.3382 - mae: 0.8855 - rmse: 1.1514 - smape: 1.3537 - val_ia: 0.3257 - val_loss: 0.8322 - val_mae: 0.6741 - val_rmse: 0.8317 - val_smape: 1.2653

Epoch 14/32

240/240 - 2s - 9ms/step - ia: 0.3536 - loss: 1.3189 - mae: 0.8793 - rmse: 1.1435 - smape: 1.3480 - val_ia: 0.3258 - val_loss: 0.8289 - val_mae: 0.6723 - val_rmse: 0.8296 - val_smape: 1.2628

Epoch 15/32

240/240 - 3s - 11ms/step - ia: 0.3499 - loss: 1.3118 - mae: 0.8785 - rmse: 1.1411 - smape: 1.3563 - val_ia: 0.3256 - val_loss: 0.8246 - val_mae: 0.6700 - val_rmse: 0.8268 - val_smape: 1.2604

Epoch 16/32

240/240 - 4s - 17ms/step - ia: 0.3553 - loss: 1.2814 - mae: 0.8666 - rmse: 1.1283 - smape: 1.3500 - val_ia: 0.3253 - val_loss: 0.8206 - val_mae: 0.6681 - val_rmse: 0.8242 - val_smape: 1.2596

Epoch 17/32

240/240 - 5s - 20ms/step - ia: 0.3525 - loss: 1.2781 - mae: 0.8657 - rmse: 1.1260 - smape: 1.3537 - val_ia: 0.3253 - val_loss: 0.8182 - val_mae: 0.6667 - val_rmse: 0.8226 - val_smape: 1.2571

Epoch 18/32

240/240 - 2s - 9ms/step - ia: 0.3515 - loss: 1.2712 - mae: 0.8624 - rmse: 1.1236 - smape: 1.3499 - val_ia: 0.3253 - val_loss: 0.8163 - val_mae: 0.6657 - val_rmse: 0.8215 - val_smape: 1.2554

Epoch 19/32

240/240 - 3s - 11ms/step - ia: 0.3539 - loss: 1.2543 - mae: 0.8539 - rmse: 1.1163 - smape: 1.3489 - val_ia: 0.3248 - val_loss: 0.8133 - val_mae: 0.6639 - val_rmse: 0.8194 - val_smape: 1.2522

Epoch 20/32

240/240 - 3s - 12ms/step - ia: 0.3530 - loss: 1.2490 - mae: 0.8541 - rmse: 1.1142 - smape: 1.3492 - val_ia: 0.3249 - val_loss: 0.8115 - val_mae: 0.6631 - val_rmse: 0.8183 - val_smape: 1.2508

Epoch 21/32

240/240 - 3s - 13ms/step - ia: 0.3561 - loss: 1.2347 - mae: 0.8469 - rmse: 1.1078 - smape: 1.3455 - val_ia: 0.3241 - val_loss: 0.8088 - val_mae: 0.6620 - val_rmse: 0.8167 - val_smape: 1.2513

Epoch 22/32

240/240 - 2s - 9ms/step - ia: 0.3556 - loss: 1.2243 - mae: 0.8446 - rmse: 1.1032 - smape: 1.3495 - val_ia: 0.3231 - val_loss: 0.8063 - val_mae: 0.6609 - val_rmse: 0.8150 - val_smape: 1.2500

Epoch 23/32

240/240 - 3s - 12ms/step - ia: 0.3493 - loss: 1.2219 - mae: 0.8455 - rmse: 1.1008 - smape: 1.3555 - val_ia: 0.3231 - val_loss: 0.8051 - val_mae: 0.6602 - val_rmse: 0.8142 - val_smape: 1.2503

Epoch 24/32

240/240 - 3s - 13ms/step - ia: 0.3524 - loss: 1.2252 - mae: 0.8438 - rmse: 1.1024 - smape: 1.3508 - val_ia: 0.3237 - val_loss: 0.8045 - val_mae: 0.6599 - val_rmse: 0.8140 - val_smape: 1.2494

Epoch 25/32

240/240 - 3s - 12ms/step - ia: 0.3592 - loss: 1.1864 - mae: 0.8307 - rmse: 1.0853 - smape: 1.3401 - val_ia: 0.3239 - val_loss: 0.8038 - val_mae: 0.6596 - val_rmse: 0.8137 - val_smape: 1.2497

Epoch 26/32

240/240 - 3s - 14ms/step - ia: 0.3576 - loss: 1.1932 - mae: 0.8315 - rmse: 1.0877 - smape: 1.3441 - val_ia: 0.3242 - val_loss: 0.8030 - val_mae: 0.6593 - val_rmse: 0.8134 - val_smape: 1.2491

Epoch 27/32

240/240 - 5s - 19ms/step - ia: 0.3568 - loss: 1.1848 - mae: 0.8273 - rmse: 1.0841 - smape: 1.3450 - val_ia: 0.3240 - val_loss: 0.8007 - val_mae: 0.6580 - val_rmse: 0.8118 - val_smape: 1.2458

Epoch 28/32

240/240 - 2s - 8ms/step - ia: 0.3557 - loss: 1.1926 - mae: 0.8301 - rmse: 1.0877 - smape: 1.3406 - val_ia: 0.3231 - val_loss: 0.8004 - val_mae: 0.6581 - val_rmse: 0.8115 - val_smape: 1.2495

Epoch 29/32

240/240 - 2s - 8ms/step - ia: 0.3563 - loss: 1.1761 - mae: 0.8233 - rmse: 1.0792 - smape: 1.3409 - val_ia: 0.3230 - val_loss: 0.7986 - val_mae: 0.6573 - val_rmse: 0.8105 - val_smape: 1.2481

Epoch 30/32

240/240 - 3s - 11ms/step - ia: 0.3562 - loss: 1.1743 - mae: 0.8223 - rmse: 1.0796 - smape: 1.3440 - val_ia: 0.3230 - val_loss: 0.7977 - val_mae: 0.6569 - val_rmse: 0.8100 - val_smape: 1.2479

Epoch 31/32

240/240 - 2s - 7ms/step - ia: 0.3555 - loss: 1.1655 - mae: 0.8199 - rmse: 1.0755 - smape: 1.3442 - val_ia: 0.3232 - val_loss: 0.7965 - val_mae: 0.6562 - val_rmse: 0.8092 - val_smape: 1.2466

Epoch 32/32

240/240 - 3s - 13ms/step - ia: 0.3576 - loss: 1.1695 - mae: 0.8192 - rmse: 1.0763 - smape: 1.3433 - val_ia: 0.3227 - val_loss: 0.7956 - val_mae: 0.6559 - val_rmse: 0.8086 - val_smape: 1.2478

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:32 683ms/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

  8%|▊         | 4/50 [08:37<1:21:35, 106.42s/trial, best loss: 0.7811234802454173]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

3830/3830 - 42s - 11ms/step - ia: 0.3687 - loss: 1.7237 - mae: 0.9142 - rmse: 1.2191 - smape: 1.1941 - val_ia: 0.2154 - val_loss: 1.3685 - val_mae: 0.7355 - val_rmse: 0.7785 - val_smape: 1.0044

Epoch 2/64

3830/3830 - 31s - 8ms/step - ia: 0.3613 - loss: 1.5290 - mae: 0.8517 - rmse: 1.1450 - smape: 1.2217 - val_ia: 0.2112 - val_loss: 1.2124 - val_mae: 0.6984 - val_rmse: 0.7403 - val_smape: 1.0391

Epoch 3/64

3830/3830 - 19s - 5ms/step - ia: 0.3488 - loss: 1.3761 - mae: 0.8076 - rmse: 1.0827 - smape: 1.2620 - val_ia: 0.2062 - val_loss: 1.1060 - val_mae: 0.6853 - val_rmse: 0.7259 - val_smape: 1.1166

Epoch 4/64

3830/3830 - 21s - 5ms/step - ia: 0.3267 - loss: 1.2772 - mae: 0.7869 - rmse: 1.0453 - smape: 1.3183 - val_ia: 0.2002 - val_loss: 1.0392 - val_mae: 0.6867 - val_rmse: 0.7259 - val_smape: 1.2307

Epoch 5/64

3830/3830 - 18s - 5ms/step - ia: 0.3142 - loss: 1.2076 - mae: 0.7782 - rmse: 1.0160 - smape: 1.3682 - val_ia: 0.1970 - val_loss: 1.0003 - val_mae: 0.6940 - val_rmse: 0.7325 - val_smape: 1.3625

Epoch 6/64

3830/3830 - 26s - 7ms/step - ia: 0.3043 - loss: 1.1812 - mae: 0.7780 - rmse: 1.0072 - smape: 1.4058 - val_ia: 0.1931 - val_loss: 0.9774 - val_mae: 0.7025 - val_rmse: 0.7405 - val_smape: 1.5031

Epoch 7/64

3830/3830 - 20s - 5ms/step - ia: 0.2987 - loss: 1.1508 - mae: 0.7775 - rmse: 0.9974 - smape: 1.4239 - val_ia: 0.1892 - val_loss: 0.9632 - val_mae: 0.7092 - val_rmse: 0.7467 - val_smape: 1.6233

Epoch 8/64

3830/3830 - 8s - 2ms/step - ia: 0.2915 - loss: 1.1378 - mae: 0.7824 - rmse: 0.9938 - smape: 1.4490 - val_ia: 0.1859 - val_loss: 0.9528 - val_mae: 0.7142 - val_rmse: 0.7512 - val_smape: 1.6979

Epoch 9/64

3830/3830 - 15s - 4ms/step - ia: 0.2903 - loss: 1.1254 - mae: 0.7804 - rmse: 0.9918 - smape: 1.4519 - val_ia: 0.1850 - val_loss: 0.9442 - val_mae: 0.7166 - val_rmse: 0.7534 - val_smape: 1.7246

Epoch 10/64

3830/3830 - 21s - 5ms/step - ia: 0.2908 - loss: 1.1107 - mae: 0.7789 - rmse: 0.9853 - smape: 1.4598 - val_ia: 0.1853 - val_loss: 0.9362 - val_mae: 0.7173 - val_rmse: 0.7540 - val_smape: 1.7267

Epoch 11/64

3830/3830 - 9s - 2ms/step - ia: 0.2892 - loss: 1.1007 - mae: 0.7785 - rmse: 0.9811 - smape: 1.4637 - val_ia: 0.1857 - val_loss: 0.9289 - val_mae: 0.7172 - val_rmse: 0.7538 - val_smape: 1.7195

Epoch 12/64

3830/3830 - 14s - 4ms/step - ia: 0.2890 - loss: 1.0973 - mae: 0.7814 - rmse: 0.9825 - smape: 1.4682 - val_ia: 0.1861 - val_loss: 0.9219 - val_mae: 0.7161 - val_rmse: 0.7527 - val_smape: 1.7071

Epoch 13/64

3830/3830 - 21s - 5ms/step - ia: 0.2894 - loss: 1.0939 - mae: 0.7784 - rmse: 0.9789 - smape: 1.4639 - val_ia: 0.1867 - val_loss: 0.9152 - val_mae: 0.7147 - val_rmse: 0.7514 - val_smape: 1.6922

Epoch 14/64

3830/3830 - 12s - 3ms/step - ia: 0.2884 - loss: 1.0846 - mae: 0.7766 - rmse: 0.9773 - smape: 1.4629 - val_ia: 0.1873 - val_loss: 0.9087 - val_mae: 0.7128 - val_rmse: 0.7495 - val_smape: 1.6762

Epoch 15/64

3830/3830 - 20s - 5ms/step - ia: 0.2946 - loss: 1.0727 - mae: 0.7713 - rmse: 0.9704 - smape: 1.4546 - val_ia: 0.1878 - val_loss: 0.9025 - val_mae: 0.7108 - val_rmse: 0.7475 - val_smape: 1.6601

Epoch 16/64

3830/3830 - 10s - 3ms/step - ia: 0.2957 - loss: 1.0679 - mae: 0.7718 - rmse: 0.9703 - smape: 1.4560 - val_ia: 0.1884 - val_loss: 0.8966 - val_mae: 0.7085 - val_rmse: 0.7453 - val_smape: 1.6432

Epoch 17/64

3830/3830 - 10s - 3ms/step - ia: 0.2972 - loss: 1.0576 - mae: 0.7673 - rmse: 0.9642 - smape: 1.4477 - val_ia: 0.1890 - val_loss: 0.8910 - val_mae: 0.7062 - val_rmse: 0.7431 - val_smape: 1.6262

Epoch 18/64

3830/3830 - 19s - 5ms/step - ia: 0.3019 - loss: 1.0537 - mae: 0.7648 - rmse: 0.9628 - smape: 1.4439 - val_ia: 0.1893 - val_loss: 0.8862 - val_mae: 0.7044 - val_rmse: 0.7414 - val_smape: 1.6111

Epoch 19/64

3830/3830 - 23s - 6ms/step - ia: 0.3026 - loss: 1.0476 - mae: 0.7636 - rmse: 0.9593 - smape: 1.4434 - val_ia: 0.1897 - val_loss: 0.8813 - val_mae: 0.7022 - val_rmse: 0.7392 - val_smape: 1.5956

Epoch 20/64

3830/3830 - 37s - 10ms/step - ia: 0.3030 - loss: 1.0415 - mae: 0.7619 - rmse: 0.9566 - smape: 1.4386 - val_ia: 0.1900 - val_loss: 0.8771 - val_mae: 0.7005 - val_rmse: 0.7377 - val_smape: 1.5822

Epoch 21/64

3830/3830 - 11s - 3ms/step - ia: 0.3059 - loss: 1.0363 - mae: 0.7581 - rmse: 0.9545 - smape: 1.4328 - val_ia: 0.1902 - val_loss: 0.8730 - val_mae: 0.6988 - val_rmse: 0.7360 - val_smape: 1.5687

Epoch 22/64

3830/3830 - 27s - 7ms/step - ia: 0.3057 - loss: 1.0352 - mae: 0.7612 - rmse: 0.9544 - smape: 1.4374 - val_ia: 0.1904 - val_loss: 0.8690 - val_mae: 0.6970 - val_rmse: 0.7343 - val_smape: 1.5557

Epoch 23/64

3830/3830 - 25s - 6ms/step - ia: 0.3078 - loss: 1.0313 - mae: 0.7581 - rmse: 0.9530 - smape: 1.4287 - val_ia: 0.1907 - val_loss: 0.8652 - val_mae: 0.6954 - val_rmse: 0.7328 - val_smape: 1.5433

Epoch 24/64

3830/3830 - 22s - 6ms/step - ia: 0.3101 - loss: 1.0239 - mae: 0.7563 - rmse: 0.9499 - smape: 1.4289 - val_ia: 0.1911 - val_loss: 0.8616 - val_mae: 0.6933 - val_rmse: 0.7308 - val_smape: 1.5303

Epoch 25/64

3830/3830 - 25s - 7ms/step - ia: 0.3124 - loss: 1.0152 - mae: 0.7507 - rmse: 0.9460 - smape: 1.4195 - val_ia: 0.1914 - val_loss: 0.8581 - val_mae: 0.6915 - val_rmse: 0.7291 - val_smape: 1.5181

Epoch 26/64

3830/3830 - 17s - 5ms/step - ia: 0.3120 - loss: 1.0075 - mae: 0.7513 - rmse: 0.9427 - smape: 1.4227 - val_ia: 0.1917 - val_loss: 0.8551 - val_mae: 0.6902 - val_rmse: 0.7279 - val_smape: 1.5080

Epoch 27/64

3830/3830 - 24s - 6ms/step - ia: 0.3130 - loss: 1.0065 - mae: 0.7495 - rmse: 0.9414 - smape: 1.4173 - val_ia: 0.1919 - val_loss: 0.8522 - val_mae: 0.6891 - val_rmse: 0.7268 - val_smape: 1.4986

Epoch 28/64

3830/3830 - 22s - 6ms/step - ia: 0.3168 - loss: 1.0048 - mae: 0.7469 - rmse: 0.9402 - smape: 1.4106 - val_ia: 0.1921 - val_loss: 0.8496 - val_mae: 0.6878 - val_rmse: 0.7256 - val_smape: 1.4897

Epoch 29/64

3830/3830 - 24s - 6ms/step - ia: 0.3160 - loss: 1.0020 - mae: 0.7479 - rmse: 0.9387 - smape: 1.4160 - val_ia: 0.1925 - val_loss: 0.8468 - val_mae: 0.6861 - val_rmse: 0.7240 - val_smape: 1.4793

Epoch 30/64

3830/3830 - 21s - 6ms/step - ia: 0.3179 - loss: 1.0043 - mae: 0.7468 - rmse: 0.9406 - smape: 1.4089 - val_ia: 0.1929 - val_loss: 0.8445 - val_mae: 0.6848 - val_rmse: 0.7227 - val_smape: 1.4707

Epoch 31/64

3830/3830 - 48s - 13ms/step - ia: 0.3195 - loss: 0.9921 - mae: 0.7439 - rmse: 0.9370 - smape: 1.4029 - val_ia: 0.1932 - val_loss: 0.8422 - val_mae: 0.6837 - val_rmse: 0.7217 - val_smape: 1.4631

Epoch 32/64

3830/3830 - 20s - 5ms/step - ia: 0.3201 - loss: 0.9963 - mae: 0.7457 - rmse: 0.9374 - smape: 1.4057 - val_ia: 0.1934 - val_loss: 0.8404 - val_mae: 0.6830 - val_rmse: 0.7211 - val_smape: 1.4571

Epoch 33/64

3830/3830 - 23s - 6ms/step - ia: 0.3215 - loss: 0.9913 - mae: 0.7431 - rmse: 0.9351 - smape: 1.4021 - val_ia: 0.1937 - val_loss: 0.8384 - val_mae: 0.6821 - val_rmse: 0.7202 - val_smape: 1.4504

Epoch 34/64

3830/3830 - 10s - 3ms/step - ia: 0.3241 - loss: 0.9915 - mae: 0.7416 - rmse: 0.9343 - smape: 1.3957 - val_ia: 0.1940 - val_loss: 0.8366 - val_mae: 0.6813 - val_rmse: 0.7195 - val_smape: 1.4443

Epoch 35/64

3830/3830 - 21s - 6ms/step - ia: 0.3242 - loss: 0.9821 - mae: 0.7403 - rmse: 0.9315 - smape: 1.3956 - val_ia: 0.1944 - val_loss: 0.8349 - val_mae: 0.6803 - val_rmse: 0.7186 - val_smape: 1.4381

Epoch 36/64

3830/3830 - 53s - 14ms/step - ia: 0.3280 - loss: 0.9783 - mae: 0.7369 - rmse: 0.9298 - smape: 1.3859 - val_ia: 0.1948 - val_loss: 0.8331 - val_mae: 0.6794 - val_rmse: 0.7177 - val_smape: 1.4320

Epoch 37/64

3830/3830 - 36s - 10ms/step - ia: 0.3248 - loss: 0.9803 - mae: 0.7385 - rmse: 0.9310 - smape: 1.3900 - val_ia: 0.1952 - val_loss: 0.8318 - val_mae: 0.6786 - val_rmse: 0.7170 - val_smape: 1.4271

Epoch 38/64

3830/3830 - 48s - 13ms/step - ia: 0.3245 - loss: 0.9832 - mae: 0.7387 - rmse: 0.9311 - smape: 1.3894 - val_ia: 0.1956 - val_loss: 0.8302 - val_mae: 0.6776 - val_rmse: 0.7161 - val_smape: 1.4213

Epoch 39/64

3830/3830 - 35s - 9ms/step - ia: 0.3292 - loss: 0.9765 - mae: 0.7368 - rmse: 0.9274 - smape: 1.3880 - val_ia: 0.1960 - val_loss: 0.8286 - val_mae: 0.6766 - val_rmse: 0.7151 - val_smape: 1.4155

Epoch 40/64

3830/3830 - 16s - 4ms/step - ia: 0.3304 - loss: 0.9735 - mae: 0.7341 - rmse: 0.9280 - smape: 1.3814 - val_ia: 0.1963 - val_loss: 0.8273 - val_mae: 0.6759 - val_rmse: 0.7145 - val_smape: 1.4111

Epoch 41/64

3830/3830 - 14s - 4ms/step - ia: 0.3328 - loss: 0.9717 - mae: 0.7332 - rmse: 0.9250 - smape: 1.3808 - val_ia: 0.1966 - val_loss: 0.8260 - val_mae: 0.6752 - val_rmse: 0.7138 - val_smape: 1.4067

Epoch 42/64

3830/3830 - 11s - 3ms/step - ia: 0.3321 - loss: 0.9686 - mae: 0.7337 - rmse: 0.9236 - smape: 1.3837 - val_ia: 0.1968 - val_loss: 0.8250 - val_mae: 0.6749 - val_rmse: 0.7135 - val_smape: 1.4037

Epoch 43/64

3830/3830 - 9s - 2ms/step - ia: 0.3319 - loss: 0.9645 - mae: 0.7330 - rmse: 0.9236 - smape: 1.3818 - val_ia: 0.1972 - val_loss: 0.8238 - val_mae: 0.6742 - val_rmse: 0.7129 - val_smape: 1.3995

Epoch 44/64

3830/3830 - 13s - 3ms/step - ia: 0.3355 - loss: 0.9650 - mae: 0.7317 - rmse: 0.9213 - smape: 1.3774 - val_ia: 0.1975 - val_loss: 0.8228 - val_mae: 0.6735 - val_rmse: 0.7123 - val_smape: 1.3958

Epoch 45/64

3830/3830 - 12s - 3ms/step - ia: 0.3365 - loss: 0.9619 - mae: 0.7305 - rmse: 0.9212 - smape: 1.3743 - val_ia: 0.1978 - val_loss: 0.8217 - val_mae: 0.6729 - val_rmse: 0.7117 - val_smape: 1.3923

Epoch 46/64

3830/3830 - 17s - 4ms/step - ia: 0.3385 - loss: 0.9618 - mae: 0.7290 - rmse: 0.9206 - smape: 1.3732 - val_ia: 0.1980 - val_loss: 0.8209 - val_mae: 0.6725 - val_rmse: 0.7113 - val_smape: 1.3893

Epoch 47/64

3830/3830 - 13s - 4ms/step - ia: 0.3364 - loss: 0.9627 - mae: 0.7304 - rmse: 0.9209 - smape: 1.3734 - val_ia: 0.1982 - val_loss: 0.8200 - val_mae: 0.6720 - val_rmse: 0.7109 - val_smape: 1.3865

Epoch 48/64

3830/3830 - 12s - 3ms/step - ia: 0.3353 - loss: 0.9634 - mae: 0.7315 - rmse: 0.9229 - smape: 1.3734 - val_ia: 0.1984 - val_loss: 0.8191 - val_mae: 0.6715 - val_rmse: 0.7103 - val_smape: 1.3834

Epoch 49/64

3830/3830 - 15s - 4ms/step - ia: 0.3394 - loss: 0.9529 - mae: 0.7273 - rmse: 0.9183 - smape: 1.3671 - val_ia: 0.1985 - val_loss: 0.8182 - val_mae: 0.6710 - val_rmse: 0.7099 - val_smape: 1.3807

Epoch 50/64

3830/3830 - 17s - 5ms/step - ia: 0.3371 - loss: 0.9550 - mae: 0.7269 - rmse: 0.9180 - smape: 1.3684 - val_ia: 0.1987 - val_loss: 0.8175 - val_mae: 0.6706 - val_rmse: 0.7095 - val_smape: 1.3779

Epoch 51/64

3830/3830 - 10s - 3ms/step - ia: 0.3379 - loss: 0.9511 - mae: 0.7274 - rmse: 0.9168 - smape: 1.3710 - val_ia: 0.1989 - val_loss: 0.8166 - val_mae: 0.6701 - val_rmse: 0.7090 - val_smape: 1.3750

Epoch 52/64

3830/3830 - 12s - 3ms/step - ia: 0.3393 - loss: 0.9516 - mae: 0.7258 - rmse: 0.9159 - smape: 1.3669 - val_ia: 0.1990 - val_loss: 0.8159 - val_mae: 0.6698 - val_rmse: 0.7088 - val_smape: 1.3728

Epoch 53/64

3830/3830 - 17s - 4ms/step - ia: 0.3395 - loss: 0.9476 - mae: 0.7263 - rmse: 0.9144 - smape: 1.3688 - val_ia: 0.1991 - val_loss: 0.8151 - val_mae: 0.6693 - val_rmse: 0.7082 - val_smape: 1.3699

Epoch 54/64

3830/3830 - 18s - 5ms/step - ia: 0.3379 - loss: 0.9498 - mae: 0.7264 - rmse: 0.9169 - smape: 1.3689 - val_ia: 0.1993 - val_loss: 0.8145 - val_mae: 0.6688 - val_rmse: 0.7079 - val_smape: 1.3678

Epoch 55/64

3830/3830 - 15s - 4ms/step - ia: 0.3404 - loss: 0.9443 - mae: 0.7226 - rmse: 0.9129 - smape: 1.3624 - val_ia: 0.1993 - val_loss: 0.8141 - val_mae: 0.6687 - val_rmse: 0.7077 - val_smape: 1.3663

Epoch 56/64

3830/3830 - 18s - 5ms/step - ia: 0.3423 - loss: 0.9400 - mae: 0.7217 - rmse: 0.9115 - smape: 1.3638 - val_ia: 0.1995 - val_loss: 0.8132 - val_mae: 0.6681 - val_rmse: 0.7072 - val_smape: 1.3634

Epoch 57/64

3830/3830 - 18s - 5ms/step - ia: 0.3439 - loss: 0.9406 - mae: 0.7201 - rmse: 0.9106 - smape: 1.3578 - val_ia: 0.1996 - val_loss: 0.8128 - val_mae: 0.6679 - val_rmse: 0.7070 - val_smape: 1.3620

Epoch 58/64

3830/3830 - 19s - 5ms/step - ia: 0.3419 - loss: 0.9396 - mae: 0.7202 - rmse: 0.9101 - smape: 1.3578 - val_ia: 0.1996 - val_loss: 0.8122 - val_mae: 0.6677 - val_rmse: 0.7068 - val_smape: 1.3605

Epoch 59/64

3830/3830 - 19s - 5ms/step - ia: 0.3430 - loss: 0.9403 - mae: 0.7211 - rmse: 0.9104 - smape: 1.3581 - val_ia: 0.1997 - val_loss: 0.8116 - val_mae: 0.6675 - val_rmse: 0.7066 - val_smape: 1.3588

Epoch 60/64

3830/3830 - 17s - 4ms/step - ia: 0.3449 - loss: 0.9331 - mae: 0.7192 - rmse: 0.9064 - smape: 1.3579 - val_ia: 0.1998 - val_loss: 0.8110 - val_mae: 0.6671 - val_rmse: 0.7063 - val_smape: 1.3569

Epoch 61/64

3830/3830 - 16s - 4ms/step - ia: 0.3444 - loss: 0.9349 - mae: 0.7185 - rmse: 0.9073 - smape: 1.3570 - val_ia: 0.1999 - val_loss: 0.8103 - val_mae: 0.6667 - val_rmse: 0.7059 - val_smape: 1.3547

Epoch 62/64

3830/3830 - 18s - 5ms/step - ia: 0.3446 - loss: 0.9408 - mae: 0.7204 - rmse: 0.9113 - smape: 1.3550 - val_ia: 0.1999 - val_loss: 0.8099 - val_mae: 0.6666 - val_rmse: 0.7057 - val_smape: 1.3535

Epoch 63/64

3830/3830 - 16s - 4ms/step - ia: 0.3486 - loss: 0.9324 - mae: 0.7159 - rmse: 0.9063 - smape: 1.3536 - val_ia: 0.1999 - val_loss: 0.8095 - val_mae: 0.6667 - val_rmse: 0.7059 - val_smape: 1.3531

Epoch 64/64

3830/3830 - 15s - 4ms/step - ia: 0.3424 - loss: 0.9347 - mae: 0.7189 - rmse: 0.9084 - smape: 1.3576 - val_ia: 0.2000 - val_loss: 0.8090 - val_mae: 0.6663 - val_rmse: 0.7055 - val_smape: 1.3512

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 49s 364ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
127/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 10%|█         | 5/50 [30:07<6:40:04, 533.44s/trial, best loss: 0.7811234802454173]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 10s - 11ms/step - ia: 0.2382 - loss: 6.5136 - mae: 1.9046 - rmse: 2.4999 - smape: 1.4879 - val_ia: 0.2054 - val_loss: 1.5958 - val_mae: 0.9687 - val_rmse: 1.1571 - val_smape: 1.4573

Epoch 2/128

958/958 - 5s - 5ms/step - ia: 0.2514 - loss: 5.1244 - mae: 1.7215 - rmse: 2.2311 - smape: 1.4743 - val_ia: 0.2187 - val_loss: 1.3199 - val_mae: 0.8767 - val_rmse: 1.0455 - val_smape: 1.4108

Epoch 3/128

958/958 - 4s - 4ms/step - ia: 0.2621 - loss: 4.5780 - mae: 1.6199 - rmse: 2.1083 - smape: 1.4598 - val_ia: 0.2247 - val_loss: 1.1988 - val_mae: 0.8345 - val_rmse: 0.9912 - val_smape: 1.3994

Epoch 4/128

958/958 - 4s - 4ms/step - ia: 0.2688 - loss: 4.1241 - mae: 1.5454 - rmse: 2.0032 - smape: 1.4513 - val_ia: 0.2303 - val_loss: 1.1059 - val_mae: 0.7997 - val_rmse: 0.9456 - val_smape: 1.3899

Epoch 5/128

958/958 - 4s - 4ms/step - ia: 0.2778 - loss: 3.7322 - mae: 1.4717 - rmse: 1.9069 - smape: 1.4399 - val_ia: 0.2352 - val_loss: 1.0334 - val_mae: 0.7705 - val_rmse: 0.9075 - val_smape: 1.3793

Epoch 6/128

958/958 - 6s - 6ms/step - ia: 0.2848 - loss: 3.4384 - mae: 1.4064 - rmse: 1.8267 - smape: 1.4297 - val_ia: 0.2396 - val_loss: 0.9744 - val_mae: 0.7455 - val_rmse: 0.8746 - val_smape: 1.3649

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.2942 - loss: 3.1572 - mae: 1.3436 - rmse: 1.7498 - smape: 1.4149 - val_ia: 0.2434 - val_loss: 0.9315 - val_mae: 0.7269 - val_rmse: 0.8494 - val_smape: 1.3568

Epoch 8/128

958/958 - 4s - 5ms/step - ia: 0.2978 - loss: 2.9256 - mae: 1.2992 - rmse: 1.6857 - smape: 1.4171 - val_ia: 0.2448 - val_loss: 0.9031 - val_mae: 0.7137 - val_rmse: 0.8315 - val_smape: 1.3445

Epoch 9/128

958/958 - 7s - 8ms/step - ia: 0.3041 - loss: 2.7337 - mae: 1.2516 - rmse: 1.6281 - smape: 1.4101 - val_ia: 0.2465 - val_loss: 0.8789 - val_mae: 0.7026 - val_rmse: 0.8152 - val_smape: 1.3476

Epoch 10/128

958/958 - 5s - 5ms/step - ia: 0.3069 - loss: 2.5677 - mae: 1.2125 - rmse: 1.5787 - smape: 1.4066 - val_ia: 0.2479 - val_loss: 0.8594 - val_mae: 0.6931 - val_rmse: 0.8019 - val_smape: 1.3389

Epoch 11/128

958/958 - 5s - 5ms/step - ia: 0.3107 - loss: 2.4037 - mae: 1.1769 - rmse: 1.5288 - smape: 1.4026 - val_ia: 0.2496 - val_loss: 0.8418 - val_mae: 0.6840 - val_rmse: 0.7900 - val_smape: 1.3267

Epoch 12/128

958/958 - 3s - 3ms/step - ia: 0.3208 - loss: 2.2489 - mae: 1.1310 - rmse: 1.4767 - smape: 1.3836 - val_ia: 0.2508 - val_loss: 0.8289 - val_mae: 0.6772 - val_rmse: 0.7809 - val_smape: 1.3174

Epoch 13/128

958/958 - 3s - 3ms/step - ia: 0.3233 - loss: 2.1511 - mae: 1.1090 - rmse: 1.4447 - smape: 1.3842 - val_ia: 0.2510 - val_loss: 0.8216 - val_mae: 0.6733 - val_rmse: 0.7748 - val_smape: 1.3193

Epoch 14/128

958/958 - 3s - 4ms/step - ia: 0.3266 - loss: 2.0682 - mae: 1.0859 - rmse: 1.4163 - smape: 1.3791 - val_ia: 0.2519 - val_loss: 0.8122 - val_mae: 0.6689 - val_rmse: 0.7688 - val_smape: 1.3156

Epoch 15/128

958/958 - 6s - 6ms/step - ia: 0.3300 - loss: 1.9410 - mae: 1.0556 - rmse: 1.3739 - smape: 1.3800 - val_ia: 0.2530 - val_loss: 0.8059 - val_mae: 0.6654 - val_rmse: 0.7637 - val_smape: 1.3159

Epoch 16/128

958/958 - 4s - 4ms/step - ia: 0.3357 - loss: 1.8617 - mae: 1.0293 - rmse: 1.3440 - smape: 1.3704 - val_ia: 0.2531 - val_loss: 0.8030 - val_mae: 0.6637 - val_rmse: 0.7611 - val_smape: 1.3174

Epoch 17/128

958/958 - 3s - 4ms/step - ia: 0.3355 - loss: 1.8097 - mae: 1.0179 - rmse: 1.3251 - smape: 1.3736 - val_ia: 0.2528 - val_loss: 0.8008 - val_mae: 0.6625 - val_rmse: 0.7590 - val_smape: 1.3172

Epoch 18/128

958/958 - 4s - 4ms/step - ia: 0.3362 - loss: 1.7610 - mae: 1.0032 - rmse: 1.3060 - smape: 1.3704 - val_ia: 0.2537 - val_loss: 0.7962 - val_mae: 0.6598 - val_rmse: 0.7553 - val_smape: 1.3138

Epoch 19/128

958/958 - 3s - 3ms/step - ia: 0.3396 - loss: 1.6897 - mae: 0.9809 - rmse: 1.2806 - smape: 1.3628 - val_ia: 0.2540 - val_loss: 0.7931 - val_mae: 0.6585 - val_rmse: 0.7534 - val_smape: 1.3132

Epoch 20/128

958/958 - 3s - 3ms/step - ia: 0.3365 - loss: 1.6713 - mae: 0.9780 - rmse: 1.2732 - smape: 1.3710 - val_ia: 0.2544 - val_loss: 0.7898 - val_mae: 0.6565 - val_rmse: 0.7513 - val_smape: 1.3068

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.3417 - loss: 1.6273 - mae: 0.9611 - rmse: 1.2564 - smape: 1.3657 - val_ia: 0.2544 - val_loss: 0.7871 - val_mae: 0.6555 - val_rmse: 0.7498 - val_smape: 1.3068

Epoch 22/128

958/958 - 3s - 3ms/step - ia: 0.3421 - loss: 1.5753 - mae: 0.9510 - rmse: 1.2343 - smape: 1.3650 - val_ia: 0.2541 - val_loss: 0.7868 - val_mae: 0.6556 - val_rmse: 0.7493 - val_smape: 1.3099

Epoch 23/128

958/958 - 3s - 3ms/step - ia: 0.3441 - loss: 1.5372 - mae: 0.9371 - rmse: 1.2214 - smape: 1.3619 - val_ia: 0.2543 - val_loss: 0.7854 - val_mae: 0.6551 - val_rmse: 0.7482 - val_smape: 1.3129

Epoch 24/128

958/958 - 5s - 5ms/step - ia: 0.3473 - loss: 1.4949 - mae: 0.9220 - rmse: 1.2027 - smape: 1.3586 - val_ia: 0.2548 - val_loss: 0.7829 - val_mae: 0.6537 - val_rmse: 0.7469 - val_smape: 1.3070

Epoch 25/128

958/958 - 5s - 6ms/step - ia: 0.3443 - loss: 1.4979 - mae: 0.9248 - rmse: 1.2063 - smape: 1.3612 - val_ia: 0.2548 - val_loss: 0.7820 - val_mae: 0.6529 - val_rmse: 0.7456 - val_smape: 1.3079

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.3488 - loss: 1.4328 - mae: 0.9047 - rmse: 1.1785 - smape: 1.3567 - val_ia: 0.2547 - val_loss: 0.7813 - val_mae: 0.6527 - val_rmse: 0.7451 - val_smape: 1.3094

Epoch 27/128

958/958 - 3s - 3ms/step - ia: 0.3468 - loss: 1.4155 - mae: 0.8998 - rmse: 1.1729 - smape: 1.3580 - val_ia: 0.2548 - val_loss: 0.7803 - val_mae: 0.6523 - val_rmse: 0.7444 - val_smape: 1.3088

Epoch 28/128

958/958 - 2s - 3ms/step - ia: 0.3515 - loss: 1.3895 - mae: 0.8889 - rmse: 1.1609 - smape: 1.3529 - val_ia: 0.2546 - val_loss: 0.7800 - val_mae: 0.6521 - val_rmse: 0.7440 - val_smape: 1.3101

Epoch 29/128

958/958 - 3s - 3ms/step - ia: 0.3504 - loss: 1.3804 - mae: 0.8853 - rmse: 1.1565 - smape: 1.3555 - val_ia: 0.2548 - val_loss: 0.7788 - val_mae: 0.6517 - val_rmse: 0.7435 - val_smape: 1.3097

Epoch 30/128

958/958 - 2s - 3ms/step - ia: 0.3534 - loss: 1.3403 - mae: 0.8732 - rmse: 1.1395 - smape: 1.3521 - val_ia: 0.2551 - val_loss: 0.7772 - val_mae: 0.6510 - val_rmse: 0.7426 - val_smape: 1.3061

Epoch 31/128

958/958 - 2s - 3ms/step - ia: 0.3481 - loss: 1.3504 - mae: 0.8746 - rmse: 1.1446 - smape: 1.3556 - val_ia: 0.2553 - val_loss: 0.7757 - val_mae: 0.6502 - val_rmse: 0.7417 - val_smape: 1.3040

Epoch 32/128

958/958 - 3s - 3ms/step - ia: 0.3545 - loss: 1.3019 - mae: 0.8623 - rmse: 1.1250 - smape: 1.3510 - val_ia: 0.2555 - val_loss: 0.7748 - val_mae: 0.6502 - val_rmse: 0.7414 - val_smape: 1.3081

Epoch 33/128

958/958 - 2s - 3ms/step - ia: 0.3492 - loss: 1.3004 - mae: 0.8617 - rmse: 1.1220 - smape: 1.3637 - val_ia: 0.2554 - val_loss: 0.7747 - val_mae: 0.6501 - val_rmse: 0.7412 - val_smape: 1.3074

Epoch 34/128

958/958 - 2s - 2ms/step - ia: 0.3502 - loss: 1.2976 - mae: 0.8559 - rmse: 1.1213 - smape: 1.3541 - val_ia: 0.2555 - val_loss: 0.7753 - val_mae: 0.6507 - val_rmse: 0.7416 - val_smape: 1.3127

Epoch 35/128

958/958 - 4s - 4ms/step - ia: 0.3530 - loss: 1.2717 - mae: 0.8485 - rmse: 1.1090 - smape: 1.3529 - val_ia: 0.2557 - val_loss: 0.7750 - val_mae: 0.6504 - val_rmse: 0.7413 - val_smape: 1.3107

Epoch 36/128

958/958 - 6s - 6ms/step - ia: 0.3545 - loss: 1.2573 - mae: 0.8443 - rmse: 1.1047 - smape: 1.3489 - val_ia: 0.2555 - val_loss: 0.7749 - val_mae: 0.6501 - val_rmse: 0.7409 - val_smape: 1.3079

Epoch 37/128

958/958 - 6s - 6ms/step - ia: 0.3550 - loss: 1.2334 - mae: 0.8372 - rmse: 1.0932 - smape: 1.3517 - val_ia: 0.2560 - val_loss: 0.7736 - val_mae: 0.6493 - val_rmse: 0.7402 - val_smape: 1.3043

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.3551 - loss: 1.2297 - mae: 0.8352 - rmse: 1.0917 - smape: 1.3520 - val_ia: 0.2559 - val_loss: 0.7734 - val_mae: 0.6494 - val_rmse: 0.7403 - val_smape: 1.3067

Epoch 39/128

958/958 - 5s - 5ms/step - ia: 0.3586 - loss: 1.2018 - mae: 0.8262 - rmse: 1.0792 - smape: 1.3436 - val_ia: 0.2559 - val_loss: 0.7732 - val_mae: 0.6497 - val_rmse: 0.7404 - val_smape: 1.3088

Epoch 40/128

958/958 - 5s - 5ms/step - ia: 0.3559 - loss: 1.2058 - mae: 0.8267 - rmse: 1.0809 - smape: 1.3487 - val_ia: 0.2561 - val_loss: 0.7724 - val_mae: 0.6491 - val_rmse: 0.7399 - val_smape: 1.3063

Epoch 41/128

958/958 - 6s - 7ms/step - ia: 0.3602 - loss: 1.1800 - mae: 0.8177 - rmse: 1.0678 - smape: 1.3470 - val_ia: 0.2560 - val_loss: 0.7723 - val_mae: 0.6492 - val_rmse: 0.7397 - val_smape: 1.3089

Epoch 42/128

958/958 - 5s - 5ms/step - ia: 0.3577 - loss: 1.1770 - mae: 0.8164 - rmse: 1.0676 - smape: 1.3476 - val_ia: 0.2558 - val_loss: 0.7721 - val_mae: 0.6490 - val_rmse: 0.7395 - val_smape: 1.3071

Epoch 43/128

958/958 - 5s - 6ms/step - ia: 0.3554 - loss: 1.1818 - mae: 0.8181 - rmse: 1.0704 - smape: 1.3465 - val_ia: 0.2561 - val_loss: 0.7719 - val_mae: 0.6490 - val_rmse: 0.7394 - val_smape: 1.3068

Epoch 44/128

958/958 - 4s - 4ms/step - ia: 0.3555 - loss: 1.1701 - mae: 0.8138 - rmse: 1.0654 - smape: 1.3478 - val_ia: 0.2561 - val_loss: 0.7716 - val_mae: 0.6489 - val_rmse: 0.7393 - val_smape: 1.3067

Epoch 45/128

958/958 - 5s - 6ms/step - ia: 0.3579 - loss: 1.1606 - mae: 0.8111 - rmse: 1.0603 - smape: 1.3476 - val_ia: 0.2561 - val_loss: 0.7714 - val_mae: 0.6491 - val_rmse: 0.7393 - val_smape: 1.3092

Epoch 46/128

958/958 - 4s - 4ms/step - ia: 0.3571 - loss: 1.1485 - mae: 0.8056 - rmse: 1.0539 - smape: 1.3489 - val_ia: 0.2562 - val_loss: 0.7709 - val_mae: 0.6489 - val_rmse: 0.7392 - val_smape: 1.3081

Epoch 47/128

958/958 - 6s - 6ms/step - ia: 0.3598 - loss: 1.1294 - mae: 0.7986 - rmse: 1.0458 - smape: 1.3433 - val_ia: 0.2558 - val_loss: 0.7718 - val_mae: 0.6493 - val_rmse: 0.7394 - val_smape: 1.3104

Epoch 48/128

958/958 - 4s - 4ms/step - ia: 0.3587 - loss: 1.1292 - mae: 0.7990 - rmse: 1.0451 - smape: 1.3436 - val_ia: 0.2560 - val_loss: 0.7714 - val_mae: 0.6491 - val_rmse: 0.7392 - val_smape: 1.3101

Epoch 49/128

958/958 - 6s - 6ms/step - ia: 0.3579 - loss: 1.1174 - mae: 0.7971 - rmse: 1.0400 - smape: 1.3455 - val_ia: 0.2559 - val_loss: 0.7717 - val_mae: 0.6493 - val_rmse: 0.7393 - val_smape: 1.3115

Epoch 50/128

958/958 - 6s - 6ms/step - ia: 0.3558 - loss: 1.1196 - mae: 0.7972 - rmse: 1.0411 - smape: 1.3505 - val_ia: 0.2560 - val_loss: 0.7712 - val_mae: 0.6492 - val_rmse: 0.7392 - val_smape: 1.3117

Epoch 51/128

958/958 - 5s - 5ms/step - ia: 0.3581 - loss: 1.1174 - mae: 0.7912 - rmse: 1.0401 - smape: 1.3420 - val_ia: 0.2564 - val_loss: 0.7708 - val_mae: 0.6487 - val_rmse: 0.7388 - val_smape: 1.3097

Epoch 52/128

958/958 - 5s - 5ms/step - ia: 0.3553 - loss: 1.1100 - mae: 0.7921 - rmse: 1.0368 - smape: 1.3471 - val_ia: 0.2565 - val_loss: 0.7698 - val_mae: 0.6483 - val_rmse: 0.7385 - val_smape: 1.3079

Epoch 53/128

958/958 - 5s - 5ms/step - ia: 0.3586 - loss: 1.1049 - mae: 0.7886 - rmse: 1.0339 - smape: 1.3438 - val_ia: 0.2564 - val_loss: 0.7700 - val_mae: 0.6485 - val_rmse: 0.7386 - val_smape: 1.3078

Epoch 54/128

958/958 - 5s - 6ms/step - ia: 0.3624 - loss: 1.0869 - mae: 0.7797 - rmse: 1.0241 - smape: 1.3373 - val_ia: 0.2565 - val_loss: 0.7697 - val_mae: 0.6485 - val_rmse: 0.7387 - val_smape: 1.3097

Epoch 55/128

958/958 - 5s - 6ms/step - ia: 0.3601 - loss: 1.0794 - mae: 0.7800 - rmse: 1.0205 - smape: 1.3450 - val_ia: 0.2565 - val_loss: 0.7698 - val_mae: 0.6483 - val_rmse: 0.7384 - val_smape: 1.3070

Epoch 56/128

958/958 - 5s - 6ms/step - ia: 0.3594 - loss: 1.0712 - mae: 0.7777 - rmse: 1.0185 - smape: 1.3439 - val_ia: 0.2565 - val_loss: 0.7692 - val_mae: 0.6479 - val_rmse: 0.7381 - val_smape: 1.3055

Epoch 57/128

958/958 - 6s - 6ms/step - ia: 0.3624 - loss: 1.0620 - mae: 0.7728 - rmse: 1.0136 - smape: 1.3408 - val_ia: 0.2568 - val_loss: 0.7686 - val_mae: 0.6474 - val_rmse: 0.7377 - val_smape: 1.3032

Epoch 58/128

958/958 - 4s - 4ms/step - ia: 0.3616 - loss: 1.0594 - mae: 0.7720 - rmse: 1.0113 - smape: 1.3395 - val_ia: 0.2565 - val_loss: 0.7694 - val_mae: 0.6482 - val_rmse: 0.7383 - val_smape: 1.3075

Epoch 59/128

958/958 - 5s - 5ms/step - ia: 0.3606 - loss: 1.0630 - mae: 0.7730 - rmse: 1.0129 - smape: 1.3411 - val_ia: 0.2566 - val_loss: 0.7688 - val_mae: 0.6479 - val_rmse: 0.7381 - val_smape: 1.3058

Epoch 60/128

958/958 - 5s - 6ms/step - ia: 0.3589 - loss: 1.0566 - mae: 0.7727 - rmse: 1.0124 - smape: 1.3443 - val_ia: 0.2563 - val_loss: 0.7693 - val_mae: 0.6482 - val_rmse: 0.7383 - val_smape: 1.3069

Epoch 61/128

958/958 - 5s - 6ms/step - ia: 0.3611 - loss: 1.0471 - mae: 0.7677 - rmse: 1.0078 - smape: 1.3400 - val_ia: 0.2567 - val_loss: 0.7681 - val_mae: 0.6477 - val_rmse: 0.7379 - val_smape: 1.3050

Epoch 62/128

958/958 - 5s - 6ms/step - ia: 0.3609 - loss: 1.0436 - mae: 0.7655 - rmse: 1.0048 - smape: 1.3401 - val_ia: 0.2567 - val_loss: 0.7678 - val_mae: 0.6475 - val_rmse: 0.7377 - val_smape: 1.3050

Epoch 63/128

958/958 - 4s - 4ms/step - ia: 0.3598 - loss: 1.0448 - mae: 0.7657 - rmse: 1.0042 - smape: 1.3423 - val_ia: 0.2566 - val_loss: 0.7682 - val_mae: 0.6477 - val_rmse: 0.7380 - val_smape: 1.3051

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.3607 - loss: 1.0356 - mae: 0.7618 - rmse: 0.9993 - smape: 1.3362 - val_ia: 0.2567 - val_loss: 0.7681 - val_mae: 0.6477 - val_rmse: 0.7380 - val_smape: 1.3041

Epoch 65/128

958/958 - 5s - 5ms/step - ia: 0.3624 - loss: 1.0252 - mae: 0.7593 - rmse: 0.9953 - smape: 1.3397 - val_ia: 0.2569 - val_loss: 0.7679 - val_mae: 0.6476 - val_rmse: 0.7379 - val_smape: 1.3035

Epoch 66/128

958/958 - 4s - 4ms/step - ia: 0.3620 - loss: 1.0288 - mae: 0.7605 - rmse: 0.9968 - smape: 1.3391 - val_ia: 0.2567 - val_loss: 0.7683 - val_mae: 0.6480 - val_rmse: 0.7382 - val_smape: 1.3063

Epoch 67/128

958/958 - 6s - 6ms/step - ia: 0.3620 - loss: 1.0246 - mae: 0.7595 - rmse: 0.9947 - smape: 1.3409 - val_ia: 0.2569 - val_loss: 0.7678 - val_mae: 0.6477 - val_rmse: 0.7377 - val_smape: 1.3062

Epoch 68/128

958/958 - 4s - 4ms/step - ia: 0.3636 - loss: 1.0193 - mae: 0.7557 - rmse: 0.9920 - smape: 1.3340 - val_ia: 0.2569 - val_loss: 0.7678 - val_mae: 0.6477 - val_rmse: 0.7377 - val_smape: 1.3074

Epoch 69/128

958/958 - 4s - 4ms/step - ia: 0.3640 - loss: 1.0087 - mae: 0.7518 - rmse: 0.9884 - smape: 1.3363 - val_ia: 0.2571 - val_loss: 0.7676 - val_mae: 0.6476 - val_rmse: 0.7378 - val_smape: 1.3067

Epoch 70/128

958/958 - 4s - 4ms/step - ia: 0.3607 - loss: 1.0084 - mae: 0.7530 - rmse: 0.9873 - smape: 1.3363 - val_ia: 0.2571 - val_loss: 0.7672 - val_mae: 0.6474 - val_rmse: 0.7376 - val_smape: 1.3045

Epoch 71/128

958/958 - 5s - 6ms/step - ia: 0.3607 - loss: 1.0107 - mae: 0.7535 - rmse: 0.9875 - smape: 1.3398 - val_ia: 0.2571 - val_loss: 0.7674 - val_mae: 0.6474 - val_rmse: 0.7377 - val_smape: 1.3045

Epoch 72/128

958/958 - 5s - 5ms/step - ia: 0.3659 - loss: 0.9973 - mae: 0.7464 - rmse: 0.9817 - smape: 1.3312 - val_ia: 0.2571 - val_loss: 0.7668 - val_mae: 0.6472 - val_rmse: 0.7375 - val_smape: 1.3028

Epoch 73/128

958/958 - 3s - 3ms/step - ia: 0.3643 - loss: 0.9983 - mae: 0.7472 - rmse: 0.9818 - smape: 1.3339 - val_ia: 0.2572 - val_loss: 0.7670 - val_mae: 0.6472 - val_rmse: 0.7375 - val_smape: 1.3029

Epoch 74/128

958/958 - 6s - 6ms/step - ia: 0.3639 - loss: 0.9952 - mae: 0.7458 - rmse: 0.9809 - smape: 1.3338 - val_ia: 0.2576 - val_loss: 0.7668 - val_mae: 0.6471 - val_rmse: 0.7374 - val_smape: 1.3032

Epoch 75/128

958/958 - 6s - 6ms/step - ia: 0.3659 - loss: 0.9870 - mae: 0.7431 - rmse: 0.9766 - smape: 1.3349 - val_ia: 0.2576 - val_loss: 0.7664 - val_mae: 0.6470 - val_rmse: 0.7374 - val_smape: 1.3026

Epoch 76/128

958/958 - 5s - 5ms/step - ia: 0.3649 - loss: 0.9916 - mae: 0.7435 - rmse: 0.9775 - smape: 1.3340 - val_ia: 0.2576 - val_loss: 0.7663 - val_mae: 0.6470 - val_rmse: 0.7372 - val_smape: 1.3033

Epoch 77/128

958/958 - 5s - 5ms/step - ia: 0.3632 - loss: 0.9909 - mae: 0.7437 - rmse: 0.9786 - smape: 1.3339 - val_ia: 0.2578 - val_loss: 0.7663 - val_mae: 0.6470 - val_rmse: 0.7373 - val_smape: 1.3033

Epoch 78/128

958/958 - 6s - 6ms/step - ia: 0.3635 - loss: 0.9819 - mae: 0.7411 - rmse: 0.9742 - smape: 1.3378 - val_ia: 0.2578 - val_loss: 0.7659 - val_mae: 0.6468 - val_rmse: 0.7372 - val_smape: 1.3024

Epoch 79/128

958/958 - 4s - 5ms/step - ia: 0.3645 - loss: 0.9780 - mae: 0.7390 - rmse: 0.9714 - smape: 1.3369 - val_ia: 0.2579 - val_loss: 0.7664 - val_mae: 0.6471 - val_rmse: 0.7376 - val_smape: 1.3032

Epoch 80/128

958/958 - 6s - 6ms/step - ia: 0.3630 - loss: 0.9765 - mae: 0.7388 - rmse: 0.9706 - smape: 1.3334 - val_ia: 0.2579 - val_loss: 0.7664 - val_mae: 0.6470 - val_rmse: 0.7375 - val_smape: 1.3021

Epoch 81/128

958/958 - 5s - 6ms/step - ia: 0.3646 - loss: 0.9693 - mae: 0.7379 - rmse: 0.9674 - smape: 1.3379 - val_ia: 0.2580 - val_loss: 0.7662 - val_mae: 0.6468 - val_rmse: 0.7373 - val_smape: 1.3014

Epoch 82/128

958/958 - 4s - 5ms/step - ia: 0.3637 - loss: 0.9720 - mae: 0.7368 - rmse: 0.9687 - smape: 1.3342 - val_ia: 0.2582 - val_loss: 0.7657 - val_mae: 0.6465 - val_rmse: 0.7371 - val_smape: 1.3000

Epoch 83/128

958/958 - 5s - 5ms/step - ia: 0.3655 - loss: 0.9725 - mae: 0.7355 - rmse: 0.9695 - smape: 1.3290 - val_ia: 0.2580 - val_loss: 0.7659 - val_mae: 0.6466 - val_rmse: 0.7371 - val_smape: 1.3007

Epoch 84/128

958/958 - 4s - 5ms/step - ia: 0.3655 - loss: 0.9690 - mae: 0.7351 - rmse: 0.9660 - smape: 1.3350 - val_ia: 0.2581 - val_loss: 0.7657 - val_mae: 0.6466 - val_rmse: 0.7371 - val_smape: 1.3008

Epoch 85/128

958/958 - 4s - 4ms/step - ia: 0.3668 - loss: 0.9613 - mae: 0.7302 - rmse: 0.9621 - smape: 1.3298 - val_ia: 0.2584 - val_loss: 0.7654 - val_mae: 0.6465 - val_rmse: 0.7371 - val_smape: 1.2991

Epoch 86/128

958/958 - 5s - 5ms/step - ia: 0.3680 - loss: 0.9631 - mae: 0.7317 - rmse: 0.9630 - smape: 1.3290 - val_ia: 0.2584 - val_loss: 0.7655 - val_mae: 0.6465 - val_rmse: 0.7371 - val_smape: 1.2996

Epoch 87/128

958/958 - 3s - 3ms/step - ia: 0.3653 - loss: 0.9571 - mae: 0.7306 - rmse: 0.9618 - smape: 1.3333 - val_ia: 0.2587 - val_loss: 0.7652 - val_mae: 0.6461 - val_rmse: 0.7369 - val_smape: 1.2973

Epoch 88/128

958/958 - 5s - 5ms/step - ia: 0.3670 - loss: 0.9553 - mae: 0.7282 - rmse: 0.9591 - smape: 1.3291 - val_ia: 0.2588 - val_loss: 0.7653 - val_mae: 0.6460 - val_rmse: 0.7369 - val_smape: 1.2962

Epoch 89/128

958/958 - 3s - 3ms/step - ia: 0.3647 - loss: 0.9576 - mae: 0.7310 - rmse: 0.9612 - smape: 1.3314 - val_ia: 0.2587 - val_loss: 0.7654 - val_mae: 0.6462 - val_rmse: 0.7370 - val_smape: 1.2973

Epoch 90/128

958/958 - 6s - 6ms/step - ia: 0.3676 - loss: 0.9512 - mae: 0.7271 - rmse: 0.9573 - smape: 1.3309 - val_ia: 0.2586 - val_loss: 0.7654 - val_mae: 0.6464 - val_rmse: 0.7372 - val_smape: 1.2986

Epoch 91/128

958/958 - 5s - 5ms/step - ia: 0.3663 - loss: 0.9521 - mae: 0.7267 - rmse: 0.9571 - smape: 1.3327 - val_ia: 0.2587 - val_loss: 0.7650 - val_mae: 0.6461 - val_rmse: 0.7370 - val_smape: 1.2982

Epoch 92/128

958/958 - 3s - 3ms/step - ia: 0.3693 - loss: 0.9424 - mae: 0.7221 - rmse: 0.9541 - smape: 1.3253 - val_ia: 0.2586 - val_loss: 0.7651 - val_mae: 0.6462 - val_rmse: 0.7371 - val_smape: 1.2982

Epoch 93/128

958/958 - 6s - 6ms/step - ia: 0.3683 - loss: 0.9433 - mae: 0.7244 - rmse: 0.9540 - smape: 1.3273 - val_ia: 0.2587 - val_loss: 0.7653 - val_mae: 0.6463 - val_rmse: 0.7372 - val_smape: 1.2986

Epoch 94/128

958/958 - 5s - 5ms/step - ia: 0.3698 - loss: 0.9374 - mae: 0.7230 - rmse: 0.9511 - smape: 1.3283 - val_ia: 0.2588 - val_loss: 0.7651 - val_mae: 0.6463 - val_rmse: 0.7370 - val_smape: 1.2992

Epoch 95/128

958/958 - 4s - 4ms/step - ia: 0.3679 - loss: 0.9382 - mae: 0.7202 - rmse: 0.9513 - smape: 1.3266 - val_ia: 0.2590 - val_loss: 0.7644 - val_mae: 0.6458 - val_rmse: 0.7366 - val_smape: 1.2964

Epoch 96/128

958/958 - 5s - 5ms/step - ia: 0.3662 - loss: 0.9376 - mae: 0.7221 - rmse: 0.9505 - smape: 1.3294 - val_ia: 0.2588 - val_loss: 0.7647 - val_mae: 0.6460 - val_rmse: 0.7368 - val_smape: 1.2964

Epoch 97/128

958/958 - 4s - 4ms/step - ia: 0.3691 - loss: 0.9313 - mae: 0.7199 - rmse: 0.9482 - smape: 1.3263 - val_ia: 0.2588 - val_loss: 0.7645 - val_mae: 0.6459 - val_rmse: 0.7367 - val_smape: 1.2966

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 6s - 46ms/step - ia: 0.3802 - loss: 1.0144 - mae: 0.7386 - rmse: 0.9886 - smape: 1.3021 - val_ia: 0.3518 - val_loss: 0.7483 - val_mae: 0.6375 - val_rmse: 0.7987 - val_smape: 1.2563

Epoch 2/128

120/120 - 2s - 16ms/step - ia: 0.3955 - loss: 0.8116 - mae: 0.6605 - rmse: 0.8988 - smape: 1.2759 - val_ia: 0.3535 - val_loss: 0.7411 - val_mae: 0.6360 - val_rmse: 0.7964 - val_smape: 1.2296

Epoch 3/128

120/120 - 1s - 7ms/step - ia: 0.3987 - loss: 0.8071 - mae: 0.6583 - rmse: 0.8958 - smape: 1.2726 - val_ia: 0.3703 - val_loss: 0.7433 - val_mae: 0.6318 - val_rmse: 0.7961 - val_smape: 1.2367

Epoch 4/128

120/120 - 1s - 6ms/step - ia: 0.3999 - loss: 0.8026 - mae: 0.6569 - rmse: 0.8937 - smape: 1.2683 - val_ia: 0.3807 - val_loss: 0.7477 - val_mae: 0.6315 - val_rmse: 0.7992 - val_smape: 1.2145

Epoch 5/128

120/120 - 1s - 8ms/step - ia: 0.4018 - loss: 0.8025 - mae: 0.6570 - rmse: 0.8929 - smape: 1.2695 - val_ia: 0.3292 - val_loss: 0.7455 - val_mae: 0.6463 - val_rmse: 0.7992 - val_smape: 1.3184

Epoch 6/128

120/120 - 1s - 7ms/step - ia: 0.4000 - loss: 0.8016 - mae: 0.6564 - rmse: 0.8932 - smape: 1.2715 - val_ia: 0.3628 - val_loss: 0.7506 - val_mae: 0.6418 - val_rmse: 0.8034 - val_smape: 1.2640

Epoch 7/128

120/120 - 1s - 8ms/step - ia: 0.4042 - loss: 0.7994 - mae: 0.6563 - rmse: 0.8910 - smape: 1.2695 - val_ia: 0.3428 - val_loss: 0.7294 - val_mae: 0.6310 - val_rmse: 0.7869 - val_smape: 1.2464

Epoch 8/128

120/120 - 1s - 6ms/step - ia: 0.4040 - loss: 0.7973 - mae: 0.6548 - rmse: 0.8910 - smape: 1.2675 - val_ia: 0.3729 - val_loss: 0.7636 - val_mae: 0.6465 - val_rmse: 0.8115 - val_smape: 1.2844

Epoch 9/128

120/120 - 1s - 6ms/step - ia: 0.4046 - loss: 0.7982 - mae: 0.6555 - rmse: 0.8911 - smape: 1.2639 - val_ia: 0.3654 - val_loss: 0.7487 - val_mae: 0.6419 - val_rmse: 0.8048 - val_smape: 1.2523

Epoch 10/128

120/120 - 1s - 10ms/step - ia: 0.4071 - loss: 0.7961 - mae: 0.6537 - rmse: 0.8907 - smape: 1.2591 - val_ia: 0.3794 - val_loss: 0.7390 - val_mae: 0.6291 - val_rmse: 0.7940 - val_smape: 1.2094

Epoch 11/128

120/120 - 1s - 5ms/step - ia: 0.4063 - loss: 0.7966 - mae: 0.6548 - rmse: 0.8901 - smape: 1.2631 - val_ia: 0.3561 - val_loss: 0.7546 - val_mae: 0.6488 - val_rmse: 0.8078 - val_smape: 1.2992

Epoch 12/128

120/120 - 1s - 5ms/step - ia: 0.4049 - loss: 0.7996 - mae: 0.6564 - rmse: 0.8914 - smape: 1.2643 - val_ia: 0.3706 - val_loss: 0.7384 - val_mae: 0.6390 - val_rmse: 0.8004 - val_smape: 1.2649

Epoch 13/128

120/120 - 0s - 4ms/step - ia: 0.4024 - loss: 0.8016 - mae: 0.6568 - rmse: 0.8936 - smape: 1.2720 - val_ia: 0.3618 - val_loss: 0.7550 - val_mae: 0.6451 - val_rmse: 0.8064 - val_smape: 1.2649

Epoch 14/128

120/120 - 1s - 6ms/step - ia: 0.4071 - loss: 0.7977 - mae: 0.6542 - rmse: 0.8911 - smape: 1.2626 - val_ia: 0.3707 - val_loss: 0.7471 - val_mae: 0.6450 - val_rmse: 0.8054 - val_smape: 1.2666

Epoch 15/128

120/120 - 0s - 4ms/step - ia: 0.4048 - loss: 0.8024 - mae: 0.6573 - rmse: 0.8934 - smape: 1.2660 - val_ia: 0.3689 - val_loss: 0.7304 - val_mae: 0.6328 - val_rmse: 0.7929 - val_smape: 1.2664

Epoch 16/128

120/120 - 1s - 5ms/step - ia: 0.4090 - loss: 0.7928 - mae: 0.6531 - rmse: 0.8880 - smape: 1.2603 - val_ia: 0.3686 - val_loss: 0.7391 - val_mae: 0.6212 - val_rmse: 0.7869 - val_smape: 1.2405

Epoch 17/128

120/120 - 1s - 6ms/step - ia: 0.4089 - loss: 0.7955 - mae: 0.6540 - rmse: 0.8893 - smape: 1.2601 - val_ia: 0.3270 - val_loss: 0.7569 - val_mae: 0.6603 - val_rmse: 0.8110 - val_smape: 1.3575

Epoch 18/128

120/120 - 0s - 4ms/step - ia: 0.4029 - loss: 0.7995 - mae: 0.6564 - rmse: 0.8919 - smape: 1.2733 - val_ia: 0.3381 - val_loss: 0.7502 - val_mae: 0.6375 - val_rmse: 0.7963 - val_smape: 1.3019

Epoch 19/128

120/120 - 1s - 5ms/step - ia: 0.4080 - loss: 0.7923 - mae: 0.6543 - rmse: 0.8871 - smape: 1.2647 - val_ia: 0.3773 - val_loss: 0.7329 - val_mae: 0.6314 - val_rmse: 0.7936 - val_smape: 1.2670

Epoch 20/128

120/120 - 0s - 3ms/step - ia: 0.4055 - loss: 0.7951 - mae: 0.6547 - rmse: 0.8896 - smape: 1.2694 - val_ia: 0.3529 - val_loss: 0.7524 - val_mae: 0.6478 - val_rmse: 0.8064 - val_smape: 1.2791

Epoch 21/128

120/120 - 0s - 3ms/step - ia: 0.4077 - loss: 0.7961 - mae: 0.6545 - rmse: 0.8890 - smape: 1.2621 - val_ia: 0.3506 - val_loss: 0.7393 - val_mae: 0.6446 - val_rmse: 0.8001 - val_smape: 1.3183

Epoch 22/128

120/120 - 1s - 6ms/step - ia: 0.4077 - loss: 0.7914 - mae: 0.6531 - rmse: 0.8867 - smape: 1.2668 - val_ia: 0.3835 - val_loss: 0.7509 - val_mae: 0.6380 - val_rmse: 0.8052 - val_smape: 1.2329

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 18s 140ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 14%|█▍        | 7/50 [40:27<4:33:04, 381.04s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

1915/1915 - 17s - 9ms/step - ia: 0.3798 - loss: 0.8633 - mae: 0.6862 - rmse: 0.8958 - smape: 1.2909 - val_ia: 0.2488 - val_loss: 0.7793 - val_mae: 0.6491 - val_rmse: 0.7204 - val_smape: 1.2397

Epoch 2/8

1915/1915 - 7s - 4ms/step - ia: 0.3978 - loss: 0.8197 - mae: 0.6634 - rmse: 0.8715 - smape: 1.2589 - val_ia: 0.2438 - val_loss: 0.7743 - val_mae: 0.6557 - val_rmse: 0.7240 - val_smape: 1.3200

Epoch 3/8

1915/1915 - 10s - 5ms/step - ia: 0.4054 - loss: 0.8069 - mae: 0.6574 - rmse: 0.8653 - smape: 1.2472 - val_ia: 0.2474 - val_loss: 0.8107 - val_mae: 0.6562 - val_rmse: 0.7331 - val_smape: 1.2105

Epoch 4/8

1915/1915 - 5s - 3ms/step - ia: 0.4071 - loss: 0.8028 - mae: 0.6559 - rmse: 0.8633 - smape: 1.2460 - val_ia: 0.2547 - val_loss: 0.8267 - val_mae: 0.6559 - val_rmse: 0.7374 - val_smape: 1.1736

Epoch 5/8

1915/1915 - 5s - 3ms/step - ia: 0.4163 - loss: 0.7902 - mae: 0.6500 - rmse: 0.8568 - smape: 1.2347 - val_ia: 0.2491 - val_loss: 0.8018 - val_mae: 0.6519 - val_rmse: 0.7274 - val_smape: 1.2117

Epoch 6/8

1915/1915 - 7s - 4ms/step - ia: 0.4198 - loss: 0.7836 - mae: 0.6463 - rmse: 0.8526 - smape: 1.2291 - val_ia: 0.2497 - val_loss: 0.8121 - val_mae: 0.6566 - val_rmse: 0.7365 - val_smape: 1.2041

Epoch 7/8

1915/1915 - 9s - 5ms/step - ia: 0.4228 - loss: 0.7793 - mae: 0.6458 - rmse: 0.8508 - smape: 1.2241 - val_ia: 0.2448 - val_loss: 0.8179 - val_mae: 0.6655 - val_rmse: 0.7435 - val_smape: 1.2228

Epoch 8/8

1915/1915 - 7s - 4ms/step - ia: 0.4256 - loss: 0.7721 - mae: 0.6428 - rmse: 0.8461 - smape: 1.2218 - val_ia: 0.2528 - val_loss: 0.7794 - val_mae: 0.6379 - val_rmse: 0.7160 - val_smape: 1.2264

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 43s 324ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 16%|█▌        | 8/50 [41:39<3:18:00, 282.86s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 21s - 179ms/step - ia: 0.3461 - loss: 1.5851 - mae: 0.9342 - rmse: 1.2311 - smape: 1.3592 - val_ia: 0.3403 - val_loss: 0.8389 - val_mae: 0.6760 - val_rmse: 0.8507 - val_smape: 1.2925

Epoch 2/128

120/120 - 7s - 55ms/step - ia: 0.3719 - loss: 0.9757 - mae: 0.7362 - rmse: 0.9847 - smape: 1.3187 - val_ia: 0.3391 - val_loss: 0.7849 - val_mae: 0.6545 - val_rmse: 0.8182 - val_smape: 1.2863

Epoch 3/128

120/120 - 1s - 5ms/step - ia: 0.3740 - loss: 0.9120 - mae: 0.7111 - rmse: 0.9526 - smape: 1.3154 - val_ia: 0.3401 - val_loss: 0.7779 - val_mae: 0.6541 - val_rmse: 0.8153 - val_smape: 1.3040

Epoch 4/128

120/120 - 1s - 6ms/step - ia: 0.3695 - loss: 0.8904 - mae: 0.6996 - rmse: 0.9414 - smape: 1.3210 - val_ia: 0.3430 - val_loss: 0.7639 - val_mae: 0.6441 - val_rmse: 0.8055 - val_smape: 1.2675

Epoch 5/128

120/120 - 1s - 5ms/step - ia: 0.3731 - loss: 0.8676 - mae: 0.6890 - rmse: 0.9287 - smape: 1.3153 - val_ia: 0.3422 - val_loss: 0.7646 - val_mae: 0.6420 - val_rmse: 0.8041 - val_smape: 1.2616

Epoch 6/128

120/120 - 1s - 6ms/step - ia: 0.3732 - loss: 0.8538 - mae: 0.6821 - rmse: 0.9218 - smape: 1.3121 - val_ia: 0.3376 - val_loss: 0.7671 - val_mae: 0.6456 - val_rmse: 0.8063 - val_smape: 1.2860

Epoch 7/128

120/120 - 1s - 4ms/step - ia: 0.3717 - loss: 0.8533 - mae: 0.6815 - rmse: 0.9214 - smape: 1.3147 - val_ia: 0.3419 - val_loss: 0.7646 - val_mae: 0.6427 - val_rmse: 0.8046 - val_smape: 1.2705

Epoch 8/128

120/120 - 1s - 4ms/step - ia: 0.3738 - loss: 0.8416 - mae: 0.6778 - rmse: 0.9155 - smape: 1.3135 - val_ia: 0.3442 - val_loss: 0.7699 - val_mae: 0.6476 - val_rmse: 0.8093 - val_smape: 1.2925

Epoch 9/128

120/120 - 1s - 7ms/step - ia: 0.3729 - loss: 0.8378 - mae: 0.6755 - rmse: 0.9126 - smape: 1.3101 - val_ia: 0.3483 - val_loss: 0.7566 - val_mae: 0.6384 - val_rmse: 0.8007 - val_smape: 1.2549

Epoch 10/128

120/120 - 0s - 4ms/step - ia: 0.3720 - loss: 0.8354 - mae: 0.6744 - rmse: 0.9113 - smape: 1.3131 - val_ia: 0.3384 - val_loss: 0.7636 - val_mae: 0.6431 - val_rmse: 0.8034 - val_smape: 1.2895

Epoch 11/128

120/120 - 0s - 4ms/step - ia: 0.3754 - loss: 0.8315 - mae: 0.6722 - rmse: 0.9093 - smape: 1.3092 - val_ia: 0.3472 - val_loss: 0.7552 - val_mae: 0.6372 - val_rmse: 0.7991 - val_smape: 1.2579

Epoch 12/128

120/120 - 1s - 5ms/step - ia: 0.3736 - loss: 0.8325 - mae: 0.6715 - rmse: 0.9091 - smape: 1.3095 - val_ia: 0.3446 - val_loss: 0.7599 - val_mae: 0.6415 - val_rmse: 0.8028 - val_smape: 1.2700

Epoch 13/128

120/120 - 1s - 5ms/step - ia: 0.3754 - loss: 0.8305 - mae: 0.6709 - rmse: 0.9090 - smape: 1.3052 - val_ia: 0.3426 - val_loss: 0.7586 - val_mae: 0.6436 - val_rmse: 0.8032 - val_smape: 1.2757

Epoch 14/128

120/120 - 1s - 6ms/step - ia: 0.3726 - loss: 0.8282 - mae: 0.6703 - rmse: 0.9077 - smape: 1.3108 - val_ia: 0.3443 - val_loss: 0.7615 - val_mae: 0.6436 - val_rmse: 0.8044 - val_smape: 1.2789

Epoch 15/128

120/120 - 1s - 5ms/step - ia: 0.3732 - loss: 0.8288 - mae: 0.6702 - rmse: 0.9089 - smape: 1.3093 - val_ia: 0.3443 - val_loss: 0.7582 - val_mae: 0.6422 - val_rmse: 0.8026 - val_smape: 1.2757

Epoch 16/128

120/120 - 1s - 6ms/step - ia: 0.3732 - loss: 0.8271 - mae: 0.6708 - rmse: 0.9072 - smape: 1.3114 - val_ia: 0.3396 - val_loss: 0.7630 - val_mae: 0.6446 - val_rmse: 0.8044 - val_smape: 1.2944

Epoch 17/128

120/120 - 1s - 5ms/step - ia: 0.3744 - loss: 0.8248 - mae: 0.6692 - rmse: 0.9055 - smape: 1.3082 - val_ia: 0.3406 - val_loss: 0.7557 - val_mae: 0.6413 - val_rmse: 0.8003 - val_smape: 1.2777

Epoch 18/128

120/120 - 1s - 6ms/step - ia: 0.3739 - loss: 0.8255 - mae: 0.6698 - rmse: 0.9063 - smape: 1.3091 - val_ia: 0.3476 - val_loss: 0.7525 - val_mae: 0.6370 - val_rmse: 0.7985 - val_smape: 1.2373

Epoch 19/128

120/120 - 1s - 6ms/step - ia: 0.3744 - loss: 0.8222 - mae: 0.6682 - rmse: 0.9046 - smape: 1.3097 - val_ia: 0.3396 - val_loss: 0.7525 - val_mae: 0.6398 - val_rmse: 0.7985 - val_smape: 1.2692

Epoch 20/128

120/120 - 1s - 6ms/step - ia: 0.3727 - loss: 0.8263 - mae: 0.6691 - rmse: 0.9064 - smape: 1.3106 - val_ia: 0.3473 - val_loss: 0.7629 - val_mae: 0.6448 - val_rmse: 0.8059 - val_smape: 1.2806

Epoch 21/128

120/120 - 0s - 4ms/step - ia: 0.3741 - loss: 0.8241 - mae: 0.6688 - rmse: 0.9055 - smape: 1.3084 - val_ia: 0.3397 - val_loss: 0.7601 - val_mae: 0.6426 - val_rmse: 0.8023 - val_smape: 1.2840

Epoch 22/128

120/120 - 1s - 7ms/step - ia: 0.3718 - loss: 0.8237 - mae: 0.6679 - rmse: 0.9050 - smape: 1.3120 - val_ia: 0.3408 - val_loss: 0.7588 - val_mae: 0.6425 - val_rmse: 0.8023 - val_smape: 1.2836

Epoch 23/128

120/120 - 0s - 4ms/step - ia: 0.3741 - loss: 0.8238 - mae: 0.6686 - rmse: 0.9047 - smape: 1.3091 - val_ia: 0.3392 - val_loss: 0.7625 - val_mae: 0.6424 - val_rmse: 0.8028 - val_smape: 1.2842

Epoch 24/128

120/120 - 0s - 4ms/step - ia: 0.3748 - loss: 0.8223 - mae: 0.6669 - rmse: 0.9041 - smape: 1.3052 - val_ia: 0.3431 - val_loss: 0.7545 - val_mae: 0.6410 - val_rmse: 0.8004 - val_smape: 1.2732

Epoch 25/128

120/120 - 0s - 3ms/step - ia: 0.3720 - loss: 0.8237 - mae: 0.6679 - rmse: 0.9056 - smape: 1.3114 - val_ia: 0.3530 - val_loss: 0.7544 - val_mae: 0.6371 - val_rmse: 0.7998 - val_smape: 1.2454

Epoch 26/128

120/120 - 1s - 5ms/step - ia: 0.3746 - loss: 0.8212 - mae: 0.6671 - rmse: 0.9038 - smape: 1.3061 - val_ia: 0.3480 - val_loss: 0.7572 - val_mae: 0.6398 - val_rmse: 0.8012 - val_smape: 1.2622

Epoch 27/128

120/120 - 1s - 9ms/step - ia: 0.3756 - loss: 0.8220 - mae: 0.6669 - rmse: 0.9040 - smape: 1.3050 - val_ia: 0.3362 - val_loss: 0.7601 - val_mae: 0.6455 - val_rmse: 0.8035 - val_smape: 1.2933

Epoch 28/128

120/120 - 1s - 11ms/step - ia: 0.3721 - loss: 0.8234 - mae: 0.6685 - rmse: 0.9050 - smape: 1.3120 - val_ia: 0.3459 - val_loss: 0.7593 - val_mae: 0.6417 - val_rmse: 0.8030 - val_smape: 1.2746

Epoch 29/128

120/120 - 1s - 6ms/step - ia: 0.3727 - loss: 0.8229 - mae: 0.6678 - rmse: 0.9040 - smape: 1.3120 - val_ia: 0.3502 - val_loss: 0.7636 - val_mae: 0.6429 - val_rmse: 0.8056 - val_smape: 1.2674

Epoch 30/128

120/120 - 1s - 7ms/step - ia: 0.3753 - loss: 0.8211 - mae: 0.6675 - rmse: 0.9039 - smape: 1.3081 - val_ia: 0.3371 - val_loss: 0.7610 - val_mae: 0.6451 - val_rmse: 0.8035 - val_smape: 1.3026

Epoch 31/128

120/120 - 1s - 4ms/step - ia: 0.3746 - loss: 0.8214 - mae: 0.6665 - rmse: 0.9042 - smape: 1.3076 - val_ia: 0.3385 - val_loss: 0.7646 - val_mae: 0.6470 - val_rmse: 0.8062 - val_smape: 1.3012

Epoch 32/128

120/120 - 1s - 5ms/step - ia: 0.3730 - loss: 0.8211 - mae: 0.6677 - rmse: 0.9037 - smape: 1.3115 - val_ia: 0.3436 - val_loss: 0.7502 - val_mae: 0.6365 - val_rmse: 0.7964 - val_smape: 1.2552

Epoch 33/128

120/120 - 1s - 5ms/step - ia: 0.3737 - loss: 0.8225 - mae: 0.6669 - rmse: 0.9040 - smape: 1.3070 - val_ia: 0.3436 - val_loss: 0.7638 - val_mae: 0.6443 - val_rmse: 0.8052 - val_smape: 1.2846

Epoch 34/128

120/120 - 1s - 5ms/step - ia: 0.3731 - loss: 0.8220 - mae: 0.6674 - rmse: 0.9035 - smape: 1.3096 - val_ia: 0.3378 - val_loss: 0.7565 - val_mae: 0.6413 - val_rmse: 0.8003 - val_smape: 1.2808

Epoch 35/128

120/120 - 1s - 5ms/step - ia: 0.3742 - loss: 0.8204 - mae: 0.6666 - rmse: 0.9028 - smape: 1.3083 - val_ia: 0.3342 - val_loss: 0.7620 - val_mae: 0.6460 - val_rmse: 0.8040 - val_smape: 1.3029

Epoch 36/128

120/120 - 1s - 6ms/step - ia: 0.3767 - loss: 0.8198 - mae: 0.6665 - rmse: 0.9025 - smape: 1.3044 - val_ia: 0.3392 - val_loss: 0.7591 - val_mae: 0.6437 - val_rmse: 0.8026 - val_smape: 1.2916

Epoch 37/128

120/120 - 1s - 6ms/step - ia: 0.3735 - loss: 0.8197 - mae: 0.6661 - rmse: 0.9031 - smape: 1.3084 - val_ia: 0.3431 - val_loss: 0.7601 - val_mae: 0.6438 - val_rmse: 0.8037 - val_smape: 1.2885

Epoch 38/128

120/120 - 1s - 6ms/step - ia: 0.3721 - loss: 0.8213 - mae: 0.6673 - rmse: 0.9035 - smape: 1.3119 - val_ia: 0.3454 - val_loss: 0.7576 - val_mae: 0.6392 - val_rmse: 0.8005 - val_smape: 1.2671

Epoch 39/128

120/120 - 0s - 3ms/step - ia: 0.3755 - loss: 0.8217 - mae: 0.6666 - rmse: 0.9040 - smape: 1.3046 - val_ia: 0.3360 - val_loss: 0.7578 - val_mae: 0.6434 - val_rmse: 0.8016 - val_smape: 1.2855

Epoch 40/128

120/120 - 0s - 3ms/step - ia: 0.3743 - loss: 0.8200 - mae: 0.6665 - rmse: 0.9038 - smape: 1.3082 - val_ia: 0.3465 - val_loss: 0.7549 - val_mae: 0.6410 - val_rmse: 0.8008 - val_smape: 1.2682

Epoch 41/128

120/120 - 1s - 6ms/step - ia: 0.3754 - loss: 0.8187 - mae: 0.6662 - rmse: 0.9020 - smape: 1.3085 - val_ia: 0.3470 - val_loss: 0.7554 - val_mae: 0.6381 - val_rmse: 0.7996 - val_smape: 1.2543

Epoch 42/128

120/120 - 1s - 7ms/step - ia: 0.3744 - loss: 0.8213 - mae: 0.6681 - rmse: 0.9037 - smape: 1.3089 - val_ia: 0.3369 - val_loss: 0.7609 - val_mae: 0.6450 - val_rmse: 0.8036 - val_smape: 1.2958

Epoch 43/128

120/120 - 0s - 4ms/step - ia: 0.3741 - loss: 0.8194 - mae: 0.6664 - rmse: 0.9028 - smape: 1.3078 - val_ia: 0.3448 - val_loss: 0.7533 - val_mae: 0.6374 - val_rmse: 0.7983 - val_smape: 1.2486

Epoch 44/128

120/120 - 1s - 5ms/step - ia: 0.3753 - loss: 0.8179 - mae: 0.6662 - rmse: 0.9018 - smape: 1.3079 - val_ia: 0.3419 - val_loss: 0.7521 - val_mae: 0.6381 - val_rmse: 0.7978 - val_smape: 1.2657

Epoch 45/128

120/120 - 0s - 3ms/step - ia: 0.3742 - loss: 0.8221 - mae: 0.6674 - rmse: 0.9044 - smape: 1.3068 - val_ia: 0.3316 - val_loss: 0.7560 - val_mae: 0.6428 - val_rmse: 0.7997 - val_smape: 1.2983

Epoch 46/128

120/120 - 1s - 6ms/step - ia: 0.3748 - loss: 0.8194 - mae: 0.6669 - rmse: 0.9029 - smape: 1.3071 - val_ia: 0.3351 - val_loss: 0.7618 - val_mae: 0.6457 - val_rmse: 0.8038 - val_smape: 1.3059

Epoch 47/128

120/120 - 1s - 5ms/step - ia: 0.3719 - loss: 0.8228 - mae: 0.6672 - rmse: 0.9046 - smape: 1.3098 - val_ia: 0.3422 - val_loss: 0.7579 - val_mae: 0.6413 - val_rmse: 0.8013 - val_smape: 1.2777

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 39s 290ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 18%|█▊        | 9/50 [42:39<2:25:39, 213.16s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

958/958 - 17s - 18ms/step - ia: 0.3386 - loss: 1.1288 - mae: 0.7916 - rmse: 1.0415 - smape: 1.3682 - val_ia: 0.2514 - val_loss: 0.7996 - val_mae: 0.6681 - val_rmse: 0.7600 - val_smape: 1.3808

Epoch 2/16

958/958 - 3s - 3ms/step - ia: 0.3584 - loss: 0.9277 - mae: 0.7149 - rmse: 0.9452 - smape: 1.3434 - val_ia: 0.2513 - val_loss: 0.7890 - val_mae: 0.6670 - val_rmse: 0.7571 - val_smape: 1.3845

Epoch 3/16

958/958 - 3s - 3ms/step - ia: 0.3649 - loss: 0.8798 - mae: 0.6943 - rmse: 0.9193 - smape: 1.3335 - val_ia: 0.2520 - val_loss: 0.7800 - val_mae: 0.6642 - val_rmse: 0.7527 - val_smape: 1.3881

Epoch 4/16

958/958 - 6s - 6ms/step - ia: 0.3751 - loss: 0.8464 - mae: 0.6803 - rmse: 0.9030 - smape: 1.3171 - val_ia: 0.2535 - val_loss: 0.7685 - val_mae: 0.6580 - val_rmse: 0.7459 - val_smape: 1.3748

Epoch 5/16

958/958 - 5s - 5ms/step - ia: 0.3790 - loss: 0.8354 - mae: 0.6736 - rmse: 0.8961 - smape: 1.3070 - val_ia: 0.2555 - val_loss: 0.7617 - val_mae: 0.6579 - val_rmse: 0.7470 - val_smape: 1.3617

Epoch 6/16

958/958 - 4s - 4ms/step - ia: 0.3831 - loss: 0.8286 - mae: 0.6701 - rmse: 0.8922 - smape: 1.2986 - val_ia: 0.2562 - val_loss: 0.7605 - val_mae: 0.6580 - val_rmse: 0.7466 - val_smape: 1.3686

Epoch 7/16

958/958 - 5s - 5ms/step - ia: 0.3864 - loss: 0.8218 - mae: 0.6659 - rmse: 0.8893 - smape: 1.2898 - val_ia: 0.2567 - val_loss: 0.7592 - val_mae: 0.6539 - val_rmse: 0.7418 - val_smape: 1.3638

Epoch 8/16

958/958 - 5s - 5ms/step - ia: 0.3901 - loss: 0.8137 - mae: 0.6631 - rmse: 0.8842 - smape: 1.2912 - val_ia: 0.2575 - val_loss: 0.7552 - val_mae: 0.6544 - val_rmse: 0.7422 - val_smape: 1.3678

Epoch 9/16

958/958 - 6s - 6ms/step - ia: 0.3928 - loss: 0.8061 - mae: 0.6588 - rmse: 0.8805 - smape: 1.2806 - val_ia: 0.2583 - val_loss: 0.7527 - val_mae: 0.6542 - val_rmse: 0.7432 - val_smape: 1.3558

Epoch 10/16

958/958 - 6s - 6ms/step - ia: 0.3974 - loss: 0.8062 - mae: 0.6582 - rmse: 0.8808 - smape: 1.2750 - val_ia: 0.2578 - val_loss: 0.7504 - val_mae: 0.6516 - val_rmse: 0.7400 - val_smape: 1.3502

Epoch 11/16

958/958 - 5s - 5ms/step - ia: 0.3967 - loss: 0.8007 - mae: 0.6557 - rmse: 0.8765 - smape: 1.2733 - val_ia: 0.2592 - val_loss: 0.7472 - val_mae: 0.6481 - val_rmse: 0.7378 - val_smape: 1.3324

Epoch 12/16

958/958 - 6s - 6ms/step - ia: 0.3999 - loss: 0.7961 - mae: 0.6542 - rmse: 0.8750 - smape: 1.2708 - val_ia: 0.2584 - val_loss: 0.7487 - val_mae: 0.6507 - val_rmse: 0.7389 - val_smape: 1.3536

Epoch 13/16

958/958 - 5s - 5ms/step - ia: 0.4012 - loss: 0.7945 - mae: 0.6533 - rmse: 0.8738 - smape: 1.2714 - val_ia: 0.2581 - val_loss: 0.7496 - val_mae: 0.6489 - val_rmse: 0.7378 - val_smape: 1.3377

Epoch 14/16

958/958 - 5s - 6ms/step - ia: 0.4030 - loss: 0.7931 - mae: 0.6529 - rmse: 0.8720 - smape: 1.2643 - val_ia: 0.2573 - val_loss: 0.7522 - val_mae: 0.6505 - val_rmse: 0.7393 - val_smape: 1.3469

Epoch 15/16

958/958 - 5s - 5ms/step - ia: 0.4079 - loss: 0.7876 - mae: 0.6492 - rmse: 0.8695 - smape: 1.2566 - val_ia: 0.2575 - val_loss: 0.7534 - val_mae: 0.6545 - val_rmse: 0.7428 - val_smape: 1.3637

Epoch 16/16

958/958 - 6s - 7ms/step - ia: 0.4056 - loss: 0.7848 - mae: 0.6498 - rmse: 0.8684 - smape: 1.2618 - val_ia: 0.2600 - val_loss: 0.7455 - val_mae: 0.6474 - val_rmse: 0.7375 - val_smape: 1.3289

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:37 723ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 20%|██        | 10/50 [44:14<1:57:45, 176.64s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 10s - 41ms/step - ia: 0.1567 - loss: 18.3784 - mae: 3.0274 - rmse: 4.2575 - smape: 1.5887 - val_ia: 0.1686 - val_loss: 7.8125 - val_mae: 2.2426 - val_rmse: 2.6708 - val_smape: 1.6196

Epoch 2/8

240/240 - 1s - 5ms/step - ia: 0.1548 - loss: 18.8929 - mae: 3.0611 - rmse: 4.3100 - smape: 1.5905 - val_ia: 0.1699 - val_loss: 7.6127 - val_mae: 2.2096 - val_rmse: 2.6365 - val_smape: 1.6165

Epoch 3/8

240/240 - 2s - 6ms/step - ia: 0.1577 - loss: 18.3930 - mae: 2.9942 - rmse: 4.2564 - smape: 1.5863 - val_ia: 0.1712 - val_loss: 7.4272 - val_mae: 2.1788 - val_rmse: 2.6043 - val_smape: 1.6131

Epoch 4/8

240/240 - 1s - 5ms/step - ia: 0.1569 - loss: 17.9364 - mae: 2.9877 - rmse: 4.2065 - smape: 1.5895 - val_ia: 0.1725 - val_loss: 7.2506 - val_mae: 2.1490 - val_rmse: 2.5732 - val_smape: 1.6104

Epoch 5/8

240/240 - 1s - 5ms/step - ia: 0.1589 - loss: 17.7698 - mae: 2.9559 - rmse: 4.1834 - smape: 1.5867 - val_ia: 0.1737 - val_loss: 7.0843 - val_mae: 2.1209 - val_rmse: 2.5436 - val_smape: 1.6078

Epoch 6/8

240/240 - 2s - 7ms/step - ia: 0.1599 - loss: 17.1429 - mae: 2.9259 - rmse: 4.1176 - smape: 1.5857 - val_ia: 0.1750 - val_loss: 6.9193 - val_mae: 2.0924 - val_rmse: 2.5137 - val_smape: 1.6047

Epoch 7/8

240/240 - 1s - 5ms/step - ia: 0.1614 - loss: 17.3351 - mae: 2.9072 - rmse: 4.1313 - smape: 1.5753 - val_ia: 0.1762 - val_loss: 6.7610 - val_mae: 2.0652 - val_rmse: 2.4848 - val_smape: 1.6013

Epoch 8/8

240/240 - 1s - 4ms/step - ia: 0.1630 - loss: 16.5136 - mae: 2.8697 - rmse: 4.0348 - smape: 1.5802 - val_ia: 0.1774 - val_loss: 6.6054 - val_mae: 2.0377 - val_rmse: 2.4558 - val_smape: 1.5982

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 27s 207ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 22%|██▏       | 11/50 [44:36<1:23:57, 129.17s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 7s - 7ms/step - ia: 0.3805 - loss: 0.9231 - mae: 0.7166 - rmse: 0.9437 - smape: 1.3023 - val_ia: 0.2641 - val_loss: 0.7560 - val_mae: 0.6372 - val_rmse: 0.7299 - val_smape: 1.2647

Epoch 2/128

958/958 - 3s - 3ms/step - ia: 0.3911 - loss: 0.8844 - mae: 0.6975 - rmse: 0.9230 - smape: 1.2877 - val_ia: 0.2604 - val_loss: 0.7562 - val_mae: 0.6410 - val_rmse: 0.7331 - val_smape: 1.2837

Epoch 3/128

958/958 - 3s - 3ms/step - ia: 0.3908 - loss: 0.8607 - mae: 0.6873 - rmse: 0.9107 - smape: 1.2842 - val_ia: 0.2653 - val_loss: 0.7476 - val_mae: 0.6397 - val_rmse: 0.7322 - val_smape: 1.2679

Epoch 4/128

958/958 - 2s - 2ms/step - ia: 0.3929 - loss: 0.8441 - mae: 0.6789 - rmse: 0.9011 - smape: 1.2817 - val_ia: 0.2655 - val_loss: 0.7499 - val_mae: 0.6314 - val_rmse: 0.7253 - val_smape: 1.2405

Epoch 5/128

958/958 - 2s - 2ms/step - ia: 0.3948 - loss: 0.8289 - mae: 0.6724 - rmse: 0.8934 - smape: 1.2770 - val_ia: 0.2627 - val_loss: 0.7640 - val_mae: 0.6561 - val_rmse: 0.7506 - val_smape: 1.3131

Epoch 6/128

958/958 - 2s - 2ms/step - ia: 0.3969 - loss: 0.8222 - mae: 0.6680 - rmse: 0.8887 - smape: 1.2730 - val_ia: 0.2659 - val_loss: 0.7505 - val_mae: 0.6387 - val_rmse: 0.7342 - val_smape: 1.2455

Epoch 7/128

958/958 - 3s - 3ms/step - ia: 0.3970 - loss: 0.8208 - mae: 0.6666 - rmse: 0.8873 - smape: 1.2740 - val_ia: 0.2627 - val_loss: 0.7615 - val_mae: 0.6503 - val_rmse: 0.7453 - val_smape: 1.2818

Epoch 8/128

958/958 - 3s - 3ms/step - ia: 0.3955 - loss: 0.8164 - mae: 0.6655 - rmse: 0.8854 - smape: 1.2730 - val_ia: 0.2635 - val_loss: 0.7643 - val_mae: 0.6501 - val_rmse: 0.7457 - val_smape: 1.2868

Epoch 9/128

958/958 - 2s - 2ms/step - ia: 0.3983 - loss: 0.8090 - mae: 0.6622 - rmse: 0.8817 - smape: 1.2687 - val_ia: 0.2661 - val_loss: 0.7536 - val_mae: 0.6383 - val_rmse: 0.7349 - val_smape: 1.2409

Epoch 10/128

958/958 - 3s - 3ms/step - ia: 0.4011 - loss: 0.8064 - mae: 0.6614 - rmse: 0.8806 - smape: 1.2669 - val_ia: 0.2647 - val_loss: 0.7557 - val_mae: 0.6441 - val_rmse: 0.7391 - val_smape: 1.2667

Epoch 11/128

958/958 - 2s - 3ms/step - ia: 0.4001 - loss: 0.8058 - mae: 0.6610 - rmse: 0.8804 - smape: 1.2657 - val_ia: 0.2649 - val_loss: 0.7596 - val_mae: 0.6447 - val_rmse: 0.7407 - val_smape: 1.2638

Epoch 12/128

958/958 - 3s - 3ms/step - ia: 0.4008 - loss: 0.8055 - mae: 0.6601 - rmse: 0.8794 - smape: 1.2628 - val_ia: 0.2651 - val_loss: 0.7540 - val_mae: 0.6365 - val_rmse: 0.7312 - val_smape: 1.2564

Epoch 13/128

958/958 - 3s - 3ms/step - ia: 0.4013 - loss: 0.8049 - mae: 0.6597 - rmse: 0.8795 - smape: 1.2649 - val_ia: 0.2638 - val_loss: 0.7627 - val_mae: 0.6475 - val_rmse: 0.7432 - val_smape: 1.2716

Epoch 14/128

958/958 - 2s - 2ms/step - ia: 0.4061 - loss: 0.7998 - mae: 0.6565 - rmse: 0.8755 - smape: 1.2561 - val_ia: 0.2637 - val_loss: 0.7683 - val_mae: 0.6543 - val_rmse: 0.7495 - val_smape: 1.2976

Epoch 15/128

958/958 - 2s - 2ms/step - ia: 0.4050 - loss: 0.8016 - mae: 0.6569 - rmse: 0.8771 - smape: 1.2591 - val_ia: 0.2651 - val_loss: 0.7596 - val_mae: 0.6442 - val_rmse: 0.7400 - val_smape: 1.2679

Epoch 16/128

958/958 - 3s - 3ms/step - ia: 0.4080 - loss: 0.7978 - mae: 0.6553 - rmse: 0.8746 - smape: 1.2516 - val_ia: 0.2661 - val_loss: 0.7547 - val_mae: 0.6408 - val_rmse: 0.7362 - val_smape: 1.2573

Epoch 17/128

958/958 - 2s - 2ms/step - ia: 0.4071 - loss: 0.7969 - mae: 0.6552 - rmse: 0.8759 - smape: 1.2540 - val_ia: 0.2678 - val_loss: 0.7550 - val_mae: 0.6392 - val_rmse: 0.7359 - val_smape: 1.2475

Epoch 18/128

958/958 - 3s - 3ms/step - ia: 0.4105 - loss: 0.7937 - mae: 0.6536 - rmse: 0.8726 - smape: 1.2500 - val_ia: 0.2635 - val_loss: 0.7808 - val_mae: 0.6698 - val_rmse: 0.7650 - val_smape: 1.3276

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 16s 125ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 24%|██▍       | 12/50 [45:26<1:06:32, 105.08s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 6s - 25ms/step - ia: 0.3339 - loss: 1.3336 - mae: 0.8491 - rmse: 1.1186 - smape: 1.3814 - val_ia: 0.3083 - val_loss: 0.7759 - val_mae: 0.6544 - val_rmse: 0.7955 - val_smape: 1.3129

Epoch 2/16

240/240 - 1s - 3ms/step - ia: 0.3612 - loss: 0.8980 - mae: 0.7043 - rmse: 0.9432 - smape: 1.3340 - val_ia: 0.3116 - val_loss: 0.7662 - val_mae: 0.6456 - val_rmse: 0.7874 - val_smape: 1.2881

Epoch 3/16

240/240 - 1s - 5ms/step - ia: 0.3657 - loss: 0.8675 - mae: 0.6899 - rmse: 0.9266 - smape: 1.3255 - val_ia: 0.3179 - val_loss: 0.7572 - val_mae: 0.6439 - val_rmse: 0.7848 - val_smape: 1.2732

Epoch 4/16

240/240 - 1s - 3ms/step - ia: 0.3679 - loss: 0.8500 - mae: 0.6819 - rmse: 0.9159 - smape: 1.3207 - val_ia: 0.3255 - val_loss: 0.7661 - val_mae: 0.6467 - val_rmse: 0.7919 - val_smape: 1.2762

Epoch 5/16

240/240 - 1s - 5ms/step - ia: 0.3675 - loss: 0.8460 - mae: 0.6792 - rmse: 0.9147 - smape: 1.3194 - val_ia: 0.3252 - val_loss: 0.7694 - val_mae: 0.6505 - val_rmse: 0.7952 - val_smape: 1.2937

Epoch 6/16

240/240 - 1s - 4ms/step - ia: 0.3705 - loss: 0.8414 - mae: 0.6774 - rmse: 0.9124 - smape: 1.3173 - val_ia: 0.3237 - val_loss: 0.7732 - val_mae: 0.6520 - val_rmse: 0.7966 - val_smape: 1.2997

Epoch 7/16

240/240 - 1s - 6ms/step - ia: 0.3733 - loss: 0.8352 - mae: 0.6740 - rmse: 0.9085 - smape: 1.3132 - val_ia: 0.3150 - val_loss: 0.7597 - val_mae: 0.6442 - val_rmse: 0.7845 - val_smape: 1.2963

Epoch 8/16

240/240 - 1s - 4ms/step - ia: 0.3726 - loss: 0.8319 - mae: 0.6735 - rmse: 0.9082 - smape: 1.3128 - val_ia: 0.3199 - val_loss: 0.7605 - val_mae: 0.6400 - val_rmse: 0.7836 - val_smape: 1.2751

Epoch 9/16

240/240 - 1s - 4ms/step - ia: 0.3764 - loss: 0.8292 - mae: 0.6713 - rmse: 0.9050 - smape: 1.3082 - val_ia: 0.3181 - val_loss: 0.7598 - val_mae: 0.6416 - val_rmse: 0.7840 - val_smape: 1.2801

Epoch 10/16

240/240 - 1s - 4ms/step - ia: 0.3744 - loss: 0.8270 - mae: 0.6708 - rmse: 0.9037 - smape: 1.3096 - val_ia: 0.3274 - val_loss: 0.7663 - val_mae: 0.6444 - val_rmse: 0.7904 - val_smape: 1.2685

Epoch 11/16

240/240 - 1s - 5ms/step - ia: 0.3775 - loss: 0.8272 - mae: 0.6702 - rmse: 0.9053 - smape: 1.3050 - val_ia: 0.3126 - val_loss: 0.7554 - val_mae: 0.6414 - val_rmse: 0.7812 - val_smape: 1.2870

Epoch 12/16

240/240 - 1s - 4ms/step - ia: 0.3758 - loss: 0.8249 - mae: 0.6685 - rmse: 0.9026 - smape: 1.3057 - val_ia: 0.3234 - val_loss: 0.7550 - val_mae: 0.6420 - val_rmse: 0.7850 - val_smape: 1.2653

Epoch 13/16

240/240 - 2s - 6ms/step - ia: 0.3748 - loss: 0.8271 - mae: 0.6699 - rmse: 0.9042 - smape: 1.3065 - val_ia: 0.3313 - val_loss: 0.7581 - val_mae: 0.6395 - val_rmse: 0.7857 - val_smape: 1.2472

Epoch 14/16

240/240 - 1s - 6ms/step - ia: 0.3748 - loss: 0.8247 - mae: 0.6693 - rmse: 0.9038 - smape: 1.3068 - val_ia: 0.3353 - val_loss: 0.7569 - val_mae: 0.6403 - val_rmse: 0.7871 - val_smape: 1.2462

Epoch 15/16

240/240 - 1s - 5ms/step - ia: 0.3773 - loss: 0.8231 - mae: 0.6682 - rmse: 0.9034 - smape: 1.3036 - val_ia: 0.3172 - val_loss: 0.7591 - val_mae: 0.6447 - val_rmse: 0.7854 - val_smape: 1.2988

Epoch 16/16

240/240 - 2s - 8ms/step - ia: 0.3729 - loss: 0.8249 - mae: 0.6692 - rmse: 0.9029 - smape: 1.3078 - val_ia: 0.3272 - val_loss: 0.7558 - val_mae: 0.6403 - val_rmse: 0.7849 - val_smape: 1.2543

Restoring model weights from the end of the best epoch: 12.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 40s 300ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 26%|██▌       | 13/50 [45:50<49:45, 80.70s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

240/240 - 5s - 22ms/step - ia: 0.3228 - loss: 2.2680 - mae: 1.1464 - rmse: 1.4923 - smape: 1.3942 - val_ia: 0.3193 - val_loss: 0.8678 - val_mae: 0.7006 - val_rmse: 0.8595 - val_smape: 1.3188

Epoch 2/8

240/240 - 1s - 3ms/step - ia: 0.3478 - loss: 1.6985 - mae: 0.9944 - rmse: 1.2989 - smape: 1.3605 - val_ia: 0.3232 - val_loss: 0.8241 - val_mae: 0.6781 - val_rmse: 0.8323 - val_smape: 1.3140

Epoch 3/8

240/240 - 1s - 3ms/step - ia: 0.3594 - loss: 1.4723 - mae: 0.9273 - rmse: 1.2086 - smape: 1.3474 - val_ia: 0.3174 - val_loss: 0.8005 - val_mae: 0.6655 - val_rmse: 0.8149 - val_smape: 1.3095

Epoch 4/8

240/240 - 1s - 3ms/step - ia: 0.3618 - loss: 1.3606 - mae: 0.8825 - rmse: 1.1622 - smape: 1.3403 - val_ia: 0.3209 - val_loss: 0.7823 - val_mae: 0.6539 - val_rmse: 0.8027 - val_smape: 1.2670

Epoch 5/8

240/240 - 2s - 9ms/step - ia: 0.3713 - loss: 1.2265 - mae: 0.8396 - rmse: 1.1035 - smape: 1.3332 - val_ia: 0.3221 - val_loss: 0.7785 - val_mae: 0.6519 - val_rmse: 0.8008 - val_smape: 1.2649

Epoch 6/8

240/240 - 1s - 4ms/step - ia: 0.3709 - loss: 1.1905 - mae: 0.8232 - rmse: 1.0867 - smape: 1.3315 - val_ia: 0.3201 - val_loss: 0.7757 - val_mae: 0.6505 - val_rmse: 0.7978 - val_smape: 1.2723

Epoch 7/8

240/240 - 1s - 6ms/step - ia: 0.3755 - loss: 1.1394 - mae: 0.7997 - rmse: 1.0632 - smape: 1.3200 - val_ia: 0.3178 - val_loss: 0.7668 - val_mae: 0.6466 - val_rmse: 0.7919 - val_smape: 1.2617

Epoch 8/8

240/240 - 1s - 5ms/step - ia: 0.3764 - loss: 1.0816 - mae: 0.7822 - rmse: 1.0354 - smape: 1.3224 - val_ia: 0.3206 - val_loss: 0.7751 - val_mae: 0.6503 - val_rmse: 0.7972 - val_smape: 1.2842

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 24s 180ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 28%|██▊       | 14/50 [46:05<36:24, 60.67s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 6s - 12ms/step - ia: 0.3764 - loss: 0.9026 - mae: 0.7031 - rmse: 0.9383 - smape: 1.3010 - val_ia: 0.2817 - val_loss: 0.7588 - val_mae: 0.6410 - val_rmse: 0.7632 - val_smape: 1.2516

Epoch 2/16

479/479 - 1s - 3ms/step - ia: 0.3859 - loss: 0.8317 - mae: 0.6711 - rmse: 0.9027 - smape: 1.2791 - val_ia: 0.2725 - val_loss: 0.7687 - val_mae: 0.6454 - val_rmse: 0.7656 - val_smape: 1.2708

Epoch 3/16

479/479 - 1s - 3ms/step - ia: 0.3904 - loss: 0.8279 - mae: 0.6688 - rmse: 0.8995 - smape: 1.2731 - val_ia: 0.2796 - val_loss: 0.7688 - val_mae: 0.6507 - val_rmse: 0.7725 - val_smape: 1.2913

Epoch 4/16

479/479 - 1s - 2ms/step - ia: 0.3956 - loss: 0.8236 - mae: 0.6670 - rmse: 0.8980 - smape: 1.2675 - val_ia: 0.2873 - val_loss: 0.7605 - val_mae: 0.6378 - val_rmse: 0.7643 - val_smape: 1.2231

Epoch 5/16

479/479 - 1s - 3ms/step - ia: 0.3961 - loss: 0.8231 - mae: 0.6666 - rmse: 0.8984 - smape: 1.2659 - val_ia: 0.2949 - val_loss: 0.7719 - val_mae: 0.6452 - val_rmse: 0.7772 - val_smape: 1.2018

Epoch 6/16

479/479 - 2s - 4ms/step - ia: 0.3966 - loss: 0.8222 - mae: 0.6667 - rmse: 0.8966 - smape: 1.2644 - val_ia: 0.2825 - val_loss: 0.7611 - val_mae: 0.6443 - val_rmse: 0.7696 - val_smape: 1.2302

Epoch 7/16

479/479 - 3s - 5ms/step - ia: 0.3986 - loss: 0.8218 - mae: 0.6657 - rmse: 0.8966 - smape: 1.2598 - val_ia: 0.2836 - val_loss: 0.7733 - val_mae: 0.6509 - val_rmse: 0.7769 - val_smape: 1.2654

Epoch 8/16

479/479 - 3s - 7ms/step - ia: 0.4000 - loss: 0.8182 - mae: 0.6639 - rmse: 0.8954 - smape: 1.2557 - val_ia: 0.2955 - val_loss: 0.7601 - val_mae: 0.6422 - val_rmse: 0.7714 - val_smape: 1.2314

Epoch 9/16

479/479 - 3s - 5ms/step - ia: 0.4029 - loss: 0.8158 - mae: 0.6634 - rmse: 0.8942 - smape: 1.2533 - val_ia: 0.2935 - val_loss: 0.7667 - val_mae: 0.6482 - val_rmse: 0.7752 - val_smape: 1.2648

Epoch 10/16

479/479 - 3s - 6ms/step - ia: 0.4037 - loss: 0.8145 - mae: 0.6623 - rmse: 0.8929 - smape: 1.2544 - val_ia: 0.2917 - val_loss: 0.7755 - val_mae: 0.6546 - val_rmse: 0.7829 - val_smape: 1.2607

Epoch 11/16

479/479 - 2s - 4ms/step - ia: 0.4034 - loss: 0.8167 - mae: 0.6632 - rmse: 0.8938 - smape: 1.2538 - val_ia: 0.2904 - val_loss: 0.7889 - val_mae: 0.6668 - val_rmse: 0.7936 - val_smape: 1.3045

Epoch 12/16

479/479 - 4s - 8ms/step - ia: 0.4056 - loss: 0.8137 - mae: 0.6626 - rmse: 0.8919 - smape: 1.2543 - val_ia: 0.2799 - val_loss: 0.7622 - val_mae: 0.6489 - val_rmse: 0.7710 - val_smape: 1.2840

Epoch 13/16

479/479 - 5s - 10ms/step - ia: 0.4055 - loss: 0.8144 - mae: 0.6623 - rmse: 0.8932 - smape: 1.2492 - val_ia: 0.2913 - val_loss: 0.7510 - val_mae: 0.6368 - val_rmse: 0.7632 - val_smape: 1.2296

Epoch 14/16

479/479 - 3s - 5ms/step - ia: 0.4065 - loss: 0.8143 - mae: 0.6611 - rmse: 0.8927 - smape: 1.2477 - val_ia: 0.2908 - val_loss: 0.7731 - val_mae: 0.6585 - val_rmse: 0.7851 - val_smape: 1.2819

Epoch 15/16

479/479 - 3s - 6ms/step - ia: 0.4070 - loss: 0.8089 - mae: 0.6615 - rmse: 0.8906 - smape: 1.2559 - val_ia: 0.2888 - val_loss: 0.7690 - val_mae: 0.6511 - val_rmse: 0.7764 - val_smape: 1.2817

Epoch 16/16

479/479 - 2s - 4ms/step - ia: 0.4101 - loss: 0.8077 - mae: 0.6597 - rmse: 0.8891 - smape: 1.2441 - val_ia: 0.2973 - val_loss: 0.7748 - val_mae: 0.6558 - val_rmse: 0.7877 - val_smape: 1.2520

Restoring model weights from the end of the best epoch: 13.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 31s 233ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 30%|███       | 15/50 [46:48<32:23, 55.53s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 24s - 6ms/step - ia: 0.3405 - loss: 0.8961 - mae: 0.7008 - rmse: 0.8868 - smape: 1.3980 - val_ia: 0.2094 - val_loss: 0.7708 - val_mae: 0.6417 - val_rmse: 0.6854 - val_smape: 1.2069

Epoch 2/256

3830/3830 - 19s - 5ms/step - ia: 0.3374 - loss: 0.8803 - mae: 0.6953 - rmse: 0.8780 - smape: 1.4152 - val_ia: 0.1927 - val_loss: 0.8513 - val_mae: 0.6940 - val_rmse: 0.7303 - val_smape: 1.5578

Epoch 3/256

3830/3830 - 21s - 5ms/step - ia: 0.3379 - loss: 0.8777 - mae: 0.6948 - rmse: 0.8771 - smape: 1.4112 - val_ia: 0.2054 - val_loss: 0.9004 - val_mae: 0.6889 - val_rmse: 0.7418 - val_smape: 1.1733

Epoch 4/256

3830/3830 - 24s - 6ms/step - ia: 0.3367 - loss: 0.8818 - mae: 0.6960 - rmse: 0.8794 - smape: 1.4158 - val_ia: 0.1966 - val_loss: 0.7977 - val_mae: 0.6720 - val_rmse: 0.7103 - val_smape: 1.4142

Epoch 5/256

3830/3830 - 27s - 7ms/step - ia: 0.3348 - loss: 0.8816 - mae: 0.6964 - rmse: 0.8776 - smape: 1.4217 - val_ia: 0.1870 - val_loss: 0.8962 - val_mae: 0.7212 - val_rmse: 0.7573 - val_smape: 1.7002

Epoch 6/256

3830/3830 - 13s - 3ms/step - ia: 0.3332 - loss: 0.8851 - mae: 0.6981 - rmse: 0.8806 - smape: 1.4242 - val_ia: 0.1913 - val_loss: 0.9053 - val_mae: 0.7011 - val_rmse: 0.7375 - val_smape: 1.6240

Epoch 7/256

3830/3830 - 12s - 3ms/step - ia: 0.3390 - loss: 0.8732 - mae: 0.6924 - rmse: 0.8757 - smape: 1.4033 - val_ia: 0.2001 - val_loss: 0.7756 - val_mae: 0.6663 - val_rmse: 0.7072 - val_smape: 1.3754

Epoch 8/256

3830/3830 - 14s - 4ms/step - ia: 0.3405 - loss: 0.8796 - mae: 0.6946 - rmse: 0.8773 - smape: 1.4152 - val_ia: 0.1958 - val_loss: 0.8112 - val_mae: 0.6723 - val_rmse: 0.7093 - val_smape: 1.4683

Epoch 9/256

3830/3830 - 14s - 4ms/step - ia: 0.3363 - loss: 0.8790 - mae: 0.6946 - rmse: 0.8776 - smape: 1.4181 - val_ia: 0.1986 - val_loss: 0.7780 - val_mae: 0.6581 - val_rmse: 0.6978 - val_smape: 1.3611

Epoch 10/256

3830/3830 - 13s - 4ms/step - ia: 0.3338 - loss: 0.8818 - mae: 0.6958 - rmse: 0.8782 - smape: 1.4224 - val_ia: 0.1890 - val_loss: 0.8767 - val_mae: 0.7040 - val_rmse: 0.7402 - val_smape: 1.6409

Epoch 11/256

3830/3830 - 14s - 4ms/step - ia: 0.3383 - loss: 0.8760 - mae: 0.6938 - rmse: 0.8756 - smape: 1.4114 - val_ia: 0.2070 - val_loss: 0.7669 - val_mae: 0.6365 - val_rmse: 0.6757 - val_smape: 1.2879

Epoch 12/256

3830/3830 - 22s - 6ms/step - ia: 0.3400 - loss: 0.8769 - mae: 0.6949 - rmse: 0.8760 - smape: 1.4141 - val_ia: 0.2069 - val_loss: 0.7629 - val_mae: 0.6378 - val_rmse: 0.6792 - val_smape: 1.2548

Epoch 13/256

3830/3830 - 14s - 4ms/step - ia: 0.3345 - loss: 0.8810 - mae: 0.6976 - rmse: 0.8791 - smape: 1.4183 - val_ia: 0.1966 - val_loss: 0.8146 - val_mae: 0.6748 - val_rmse: 0.7144 - val_smape: 1.4086

Epoch 14/256

3830/3830 - 22s - 6ms/step - ia: 0.3375 - loss: 0.8796 - mae: 0.6952 - rmse: 0.8772 - smape: 1.4145 - val_ia: 0.1898 - val_loss: 0.8486 - val_mae: 0.6913 - val_rmse: 0.7280 - val_smape: 1.5623

Epoch 15/256

3830/3830 - 19s - 5ms/step - ia: 0.3352 - loss: 0.8801 - mae: 0.6969 - rmse: 0.8791 - smape: 1.4191 - val_ia: 0.1973 - val_loss: 0.8199 - val_mae: 0.6752 - val_rmse: 0.7161 - val_smape: 1.3583

Epoch 16/256

3830/3830 - 14s - 4ms/step - ia: 0.3356 - loss: 0.8795 - mae: 0.6950 - rmse: 0.8786 - smape: 1.4169 - val_ia: 0.2030 - val_loss: 0.7924 - val_mae: 0.6627 - val_rmse: 0.7029 - val_smape: 1.3623

Epoch 17/256

3830/3830 - 14s - 4ms/step - ia: 0.3373 - loss: 0.8811 - mae: 0.6954 - rmse: 0.8805 - smape: 1.4109 - val_ia: 0.1990 - val_loss: 0.8003 - val_mae: 0.6544 - val_rmse: 0.6926 - val_smape: 1.3775

Epoch 18/256

3830/3830 - 14s - 4ms/step - ia: 0.3398 - loss: 0.8760 - mae: 0.6934 - rmse: 0.8761 - smape: 1.4135 - val_ia: 0.1953 - val_loss: 0.8047 - val_mae: 0.6828 - val_rmse: 0.7195 - val_smape: 1.4844

Epoch 19/256

3830/3830 - 15s - 4ms/step - ia: 0.3361 - loss: 0.8776 - mae: 0.6953 - rmse: 0.8775 - smape: 1.4196 - val_ia: 0.1951 - val_loss: 0.8533 - val_mae: 0.6791 - val_rmse: 0.7165 - val_smape: 1.4907

Epoch 20/256

3830/3830 - 20s - 5ms/step - ia: 0.3402 - loss: 0.8750 - mae: 0.6922 - rmse: 0.8751 - smape: 1.4116 - val_ia: 0.2099 - val_loss: 0.7742 - val_mae: 0.6448 - val_rmse: 0.6923 - val_smape: 1.1765

Epoch 21/256

3830/3830 - 15s - 4ms/step - ia: 0.3389 - loss: 0.8815 - mae: 0.6958 - rmse: 0.8786 - smape: 1.4117 - val_ia: 0.1989 - val_loss: 0.8412 - val_mae: 0.6841 - val_rmse: 0.7265 - val_smape: 1.3706

Epoch 22/256

3830/3830 - 14s - 4ms/step - ia: 0.3334 - loss: 0.8814 - mae: 0.6958 - rmse: 0.8786 - smape: 1.4167 - val_ia: 0.2062 - val_loss: 0.7647 - val_mae: 0.6439 - val_rmse: 0.6860 - val_smape: 1.2930

Epoch 23/256

3830/3830 - 20s - 5ms/step - ia: 0.3410 - loss: 0.8757 - mae: 0.6931 - rmse: 0.8768 - smape: 1.4097 - val_ia: 0.2009 - val_loss: 0.7774 - val_mae: 0.6563 - val_rmse: 0.6973 - val_smape: 1.3412

Epoch 24/256

3830/3830 - 23s - 6ms/step - ia: 0.3426 - loss: 0.8758 - mae: 0.6937 - rmse: 0.8769 - smape: 1.4021 - val_ia: 0.1977 - val_loss: 0.8266 - val_mae: 0.6670 - val_rmse: 0.7047 - val_smape: 1.4485

Epoch 25/256

3830/3830 - 15s - 4ms/step - ia: 0.3374 - loss: 0.8769 - mae: 0.6946 - rmse: 0.8766 - smape: 1.4147 - val_ia: 0.2020 - val_loss: 0.7753 - val_mae: 0.6533 - val_rmse: 0.6936 - val_smape: 1.3490

Epoch 26/256

3830/3830 - 12s - 3ms/step - ia: 0.3365 - loss: 0.8759 - mae: 0.6940 - rmse: 0.8768 - smape: 1.4167 - val_ia: 0.1886 - val_loss: 0.9242 - val_mae: 0.7203 - val_rmse: 0.7564 - val_smape: 1.6823

Epoch 27/256

3830/3830 - 15s - 4ms/step - ia: 0.3373 - loss: 0.8789 - mae: 0.6943 - rmse: 0.8763 - smape: 1.4073 - val_ia: 0.2142 - val_loss: 0.8070 - val_mae: 0.6424 - val_rmse: 0.6929 - val_smape: 1.1724

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:36 715ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 32%|███▏      | 16/50 [54:37<1:41:55, 179.88s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 28s - 7ms/step - ia: 0.3691 - loss: 0.8458 - mae: 0.6791 - rmse: 0.8618 - smape: 1.3034 - val_ia: 0.2087 - val_loss: 0.7380 - val_mae: 0.6219 - val_rmse: 0.6645 - val_smape: 1.1972

Epoch 2/256

3830/3830 - 14s - 4ms/step - ia: 0.3936 - loss: 0.7999 - mae: 0.6570 - rmse: 0.8383 - smape: 1.2813 - val_ia: 0.2011 - val_loss: 0.7648 - val_mae: 0.6515 - val_rmse: 0.6942 - val_smape: 1.2874

Epoch 3/256

3830/3830 - 12s - 3ms/step - ia: 0.4003 - loss: 0.7849 - mae: 0.6495 - rmse: 0.8303 - smape: 1.2736 - val_ia: 0.2031 - val_loss: 0.8565 - val_mae: 0.6695 - val_rmse: 0.7171 - val_smape: 1.2557

Epoch 4/256

3830/3830 - 16s - 4ms/step - ia: 0.4037 - loss: 0.7749 - mae: 0.6449 - rmse: 0.8243 - smape: 1.2647 - val_ia: 0.2074 - val_loss: 0.7844 - val_mae: 0.6395 - val_rmse: 0.6853 - val_smape: 1.2254

Epoch 5/256

3830/3830 - 15s - 4ms/step - ia: 0.4110 - loss: 0.7679 - mae: 0.6408 - rmse: 0.8204 - smape: 1.2548 - val_ia: 0.2022 - val_loss: 0.7731 - val_mae: 0.6484 - val_rmse: 0.6894 - val_smape: 1.3298

Epoch 6/256

3830/3830 - 21s - 5ms/step - ia: 0.4136 - loss: 0.7587 - mae: 0.6369 - rmse: 0.8151 - smape: 1.2500 - val_ia: 0.2039 - val_loss: 0.8272 - val_mae: 0.6514 - val_rmse: 0.6977 - val_smape: 1.2519

Epoch 7/256

3830/3830 - 13s - 3ms/step - ia: 0.4172 - loss: 0.7539 - mae: 0.6355 - rmse: 0.8122 - smape: 1.2412 - val_ia: 0.2048 - val_loss: 0.7510 - val_mae: 0.6410 - val_rmse: 0.6838 - val_smape: 1.2925

Epoch 8/256

3830/3830 - 24s - 6ms/step - ia: 0.4189 - loss: 0.7494 - mae: 0.6330 - rmse: 0.8108 - smape: 1.2453 - val_ia: 0.2013 - val_loss: 0.7454 - val_mae: 0.6356 - val_rmse: 0.6775 - val_smape: 1.3023

Epoch 9/256

3830/3830 - 16s - 4ms/step - ia: 0.4212 - loss: 0.7401 - mae: 0.6294 - rmse: 0.8059 - smape: 1.2401 - val_ia: 0.2142 - val_loss: 0.7913 - val_mae: 0.6284 - val_rmse: 0.6780 - val_smape: 1.2031

Epoch 10/256

3830/3830 - 16s - 4ms/step - ia: 0.4275 - loss: 0.7355 - mae: 0.6255 - rmse: 0.8017 - smape: 1.2292 - val_ia: 0.2046 - val_loss: 0.7537 - val_mae: 0.6375 - val_rmse: 0.6795 - val_smape: 1.3152

Epoch 11/256

3830/3830 - 15s - 4ms/step - ia: 0.4283 - loss: 0.7315 - mae: 0.6247 - rmse: 0.7997 - smape: 1.2299 - val_ia: 0.2044 - val_loss: 0.8044 - val_mae: 0.6531 - val_rmse: 0.6989 - val_smape: 1.2435

Epoch 12/256

3830/3830 - 16s - 4ms/step - ia: 0.4321 - loss: 0.7271 - mae: 0.6229 - rmse: 0.7969 - smape: 1.2230 - val_ia: 0.2020 - val_loss: 0.7636 - val_mae: 0.6451 - val_rmse: 0.6864 - val_smape: 1.3226

Epoch 13/256

3830/3830 - 18s - 5ms/step - ia: 0.4335 - loss: 0.7244 - mae: 0.6211 - rmse: 0.7970 - smape: 1.2211 - val_ia: 0.2015 - val_loss: 0.7687 - val_mae: 0.6514 - val_rmse: 0.6941 - val_smape: 1.3048

Epoch 14/256

3830/3830 - 23s - 6ms/step - ia: 0.4338 - loss: 0.7221 - mae: 0.6199 - rmse: 0.7934 - smape: 1.2158 - val_ia: 0.2021 - val_loss: 0.7882 - val_mae: 0.6577 - val_rmse: 0.7017 - val_smape: 1.3125

Epoch 15/256

3830/3830 - 15s - 4ms/step - ia: 0.4374 - loss: 0.7179 - mae: 0.6188 - rmse: 0.7931 - smape: 1.2165 - val_ia: 0.2056 - val_loss: 0.7901 - val_mae: 0.6365 - val_rmse: 0.6832 - val_smape: 1.2242

Epoch 16/256

3830/3830 - 18s - 5ms/step - ia: 0.4365 - loss: 0.7150 - mae: 0.6181 - rmse: 0.7926 - smape: 1.2116 - val_ia: 0.2026 - val_loss: 0.7627 - val_mae: 0.6458 - val_rmse: 0.6891 - val_smape: 1.2788

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:14 555ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 34%|███▍      | 17/50 [59:20<1:55:55, 210.76s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

240/240 - 7s - 27ms/step - ia: 0.2726 - loss: 2.3621 - mae: 1.1822 - rmse: 1.5318 - smape: 1.4507 - val_ia: 0.2954 - val_loss: 1.6753 - val_mae: 0.9947 - val_rmse: 1.1963 - val_smape: 1.5282

Epoch 2/16

240/240 - 2s - 10ms/step - ia: 0.2788 - loss: 2.3220 - mae: 1.1710 - rmse: 1.5183 - smape: 1.4454 - val_ia: 0.2973 - val_loss: 1.6185 - val_mae: 0.9749 - val_rmse: 1.1751 - val_smape: 1.5249

Epoch 3/16

240/240 - 1s - 5ms/step - ia: 0.2740 - loss: 2.2792 - mae: 1.1631 - rmse: 1.5034 - smape: 1.4517 - val_ia: 0.2991 - val_loss: 1.5640 - val_mae: 0.9556 - val_rmse: 1.1544 - val_smape: 1.5207

Epoch 4/16

240/240 - 2s - 7ms/step - ia: 0.2778 - loss: 2.2565 - mae: 1.1533 - rmse: 1.4966 - smape: 1.4463 - val_ia: 0.3007 - val_loss: 1.5167 - val_mae: 0.9389 - val_rmse: 1.1363 - val_smape: 1.5161

Epoch 5/16

240/240 - 1s - 5ms/step - ia: 0.2793 - loss: 2.1807 - mae: 1.1387 - rmse: 1.4715 - smape: 1.4428 - val_ia: 0.3022 - val_loss: 1.4724 - val_mae: 0.9231 - val_rmse: 1.1190 - val_smape: 1.5116

Epoch 6/16

240/240 - 1s - 5ms/step - ia: 0.2833 - loss: 2.1837 - mae: 1.1331 - rmse: 1.4723 - smape: 1.4366 - val_ia: 0.3034 - val_loss: 1.4323 - val_mae: 0.9089 - val_rmse: 1.1033 - val_smape: 1.5077

Epoch 7/16

240/240 - 2s - 6ms/step - ia: 0.2837 - loss: 2.1309 - mae: 1.1236 - rmse: 1.4538 - smape: 1.4394 - val_ia: 0.3044 - val_loss: 1.3956 - val_mae: 0.8958 - val_rmse: 1.0887 - val_smape: 1.5033

Epoch 8/16

240/240 - 1s - 6ms/step - ia: 0.2837 - loss: 2.1058 - mae: 1.1181 - rmse: 1.4474 - smape: 1.4412 - val_ia: 0.3054 - val_loss: 1.3600 - val_mae: 0.8829 - val_rmse: 1.0743 - val_smape: 1.4986

Epoch 9/16

240/240 - 1s - 6ms/step - ia: 0.2884 - loss: 2.0915 - mae: 1.1143 - rmse: 1.4416 - smape: 1.4349 - val_ia: 0.3062 - val_loss: 1.3278 - val_mae: 0.8713 - val_rmse: 1.0612 - val_smape: 1.4940

Epoch 10/16

240/240 - 1s - 4ms/step - ia: 0.2891 - loss: 2.0455 - mae: 1.1019 - rmse: 1.4256 - smape: 1.4305 - val_ia: 0.3070 - val_loss: 1.2983 - val_mae: 0.8608 - val_rmse: 1.0493 - val_smape: 1.4905

Epoch 11/16

240/240 - 1s - 5ms/step - ia: 0.2948 - loss: 1.9931 - mae: 1.0882 - rmse: 1.4068 - smape: 1.4256 - val_ia: 0.3078 - val_loss: 1.2698 - val_mae: 0.8504 - val_rmse: 1.0374 - val_smape: 1.4861

Epoch 12/16

240/240 - 1s - 4ms/step - ia: 0.2941 - loss: 1.9869 - mae: 1.0886 - rmse: 1.4057 - smape: 1.4285 - val_ia: 0.3085 - val_loss: 1.2431 - val_mae: 0.8406 - val_rmse: 1.0262 - val_smape: 1.4807

Epoch 13/16

240/240 - 1s - 3ms/step - ia: 0.2984 - loss: 1.9614 - mae: 1.0790 - rmse: 1.3948 - smape: 1.4214 - val_ia: 0.3090 - val_loss: 1.2188 - val_mae: 0.8318 - val_rmse: 1.0160 - val_smape: 1.4759

Epoch 14/16

240/240 - 1s - 5ms/step - ia: 0.2956 - loss: 1.9537 - mae: 1.0781 - rmse: 1.3932 - smape: 1.4250 - val_ia: 0.3096 - val_loss: 1.1946 - val_mae: 0.8228 - val_rmse: 1.0055 - val_smape: 1.4707

Epoch 15/16

240/240 - 1s - 3ms/step - ia: 0.2974 - loss: 1.9348 - mae: 1.0708 - rmse: 1.3865 - smape: 1.4231 - val_ia: 0.3101 - val_loss: 1.1747 - val_mae: 0.8156 - val_rmse: 0.9971 - val_smape: 1.4668

Epoch 16/16

240/240 - 1s - 3ms/step - ia: 0.3011 - loss: 1.8971 - mae: 1.0604 - rmse: 1.3732 - smape: 1.4175 - val_ia: 0.3106 - val_loss: 1.1557 - val_mae: 0.8085 - val_rmse: 0.9888 - val_smape: 1.4629

Restoring model weights from the end of the best epoch: 16.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 12s 95ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 51/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
108/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 36%|███▌      | 18/50 [59:46<1:22:55, 155.48s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

479/479 - 5s - 10ms/step - ia: 0.3868 - loss: 0.8804 - mae: 0.6949 - rmse: 0.9287 - smape: 1.2893 - val_ia: 0.2876 - val_loss: 0.7459 - val_mae: 0.6320 - val_rmse: 0.7557 - val_smape: 1.2185

Epoch 2/16

479/479 - 3s - 6ms/step - ia: 0.3916 - loss: 0.8249 - mae: 0.6706 - rmse: 0.8992 - smape: 1.2799 - val_ia: 0.2923 - val_loss: 0.7648 - val_mae: 0.6518 - val_rmse: 0.7790 - val_smape: 1.2639

Epoch 3/16

479/479 - 2s - 5ms/step - ia: 0.4000 - loss: 0.8141 - mae: 0.6645 - rmse: 0.8929 - smape: 1.2674 - val_ia: 0.2878 - val_loss: 0.7836 - val_mae: 0.6620 - val_rmse: 0.7916 - val_smape: 1.2724

Epoch 4/16

479/479 - 3s - 7ms/step - ia: 0.4057 - loss: 0.8088 - mae: 0.6608 - rmse: 0.8906 - smape: 1.2572 - val_ia: 0.2791 - val_loss: 0.7595 - val_mae: 0.6424 - val_rmse: 0.7681 - val_smape: 1.2669

Epoch 5/16

479/479 - 2s - 5ms/step - ia: 0.4107 - loss: 0.8030 - mae: 0.6576 - rmse: 0.8869 - smape: 1.2516 - val_ia: 0.2872 - val_loss: 0.7537 - val_mae: 0.6282 - val_rmse: 0.7551 - val_smape: 1.2185

Epoch 6/16

479/479 - 3s - 5ms/step - ia: 0.4167 - loss: 0.7953 - mae: 0.6532 - rmse: 0.8813 - smape: 1.2439 - val_ia: 0.2858 - val_loss: 0.7604 - val_mae: 0.6438 - val_rmse: 0.7689 - val_smape: 1.2738

Epoch 7/16

479/479 - 3s - 7ms/step - ia: 0.4186 - loss: 0.7923 - mae: 0.6525 - rmse: 0.8806 - smape: 1.2397 - val_ia: 0.2949 - val_loss: 0.7462 - val_mae: 0.6241 - val_rmse: 0.7553 - val_smape: 1.1752

Epoch 8/16

479/479 - 2s - 5ms/step - ia: 0.4244 - loss: 0.7878 - mae: 0.6500 - rmse: 0.8772 - smape: 1.2304 - val_ia: 0.2849 - val_loss: 0.7431 - val_mae: 0.6319 - val_rmse: 0.7566 - val_smape: 1.2377

Epoch 9/16

479/479 - 2s - 4ms/step - ia: 0.4271 - loss: 0.7810 - mae: 0.6457 - rmse: 0.8749 - smape: 1.2279 - val_ia: 0.2867 - val_loss: 0.7540 - val_mae: 0.6332 - val_rmse: 0.7614 - val_smape: 1.2331

Epoch 10/16

479/479 - 3s - 6ms/step - ia: 0.4261 - loss: 0.7793 - mae: 0.6472 - rmse: 0.8751 - smape: 1.2288 - val_ia: 0.2915 - val_loss: 0.7501 - val_mae: 0.6377 - val_rmse: 0.7656 - val_smape: 1.2320

Epoch 11/16

479/479 - 2s - 3ms/step - ia: 0.4319 - loss: 0.7746 - mae: 0.6440 - rmse: 0.8702 - smape: 1.2200 - val_ia: 0.2905 - val_loss: 0.7446 - val_mae: 0.6321 - val_rmse: 0.7590 - val_smape: 1.2283

Epoch 12/16

479/479 - 2s - 3ms/step - ia: 0.4340 - loss: 0.7722 - mae: 0.6422 - rmse: 0.8694 - smape: 1.2215 - val_ia: 0.2999 - val_loss: 0.7667 - val_mae: 0.6421 - val_rmse: 0.7772 - val_smape: 1.2112

Epoch 13/16

479/479 - 3s - 6ms/step - ia: 0.4339 - loss: 0.7718 - mae: 0.6425 - rmse: 0.8700 - smape: 1.2159 - val_ia: 0.2979 - val_loss: 0.7447 - val_mae: 0.6322 - val_rmse: 0.7617 - val_smape: 1.2354

Epoch 14/16

479/479 - 3s - 6ms/step - ia: 0.4374 - loss: 0.7658 - mae: 0.6401 - rmse: 0.8651 - smape: 1.2120 - val_ia: 0.3000 - val_loss: 0.7694 - val_mae: 0.6478 - val_rmse: 0.7811 - val_smape: 1.2585

Epoch 15/16

479/479 - 3s - 6ms/step - ia: 0.4382 - loss: 0.7649 - mae: 0.6397 - rmse: 0.8653 - smape: 1.2133 - val_ia: 0.2968 - val_loss: 0.7541 - val_mae: 0.6415 - val_rmse: 0.7718 - val_smape: 1.2412

Epoch 16/16

479/479 - 3s - 6ms/step - ia: 0.4385 - loss: 0.7631 - mae: 0.6387 - rmse: 0.8646 - smape: 1.2112 - val_ia: 0.2969 - val_loss: 0.7884 - val_mae: 0.6706 - val_rmse: 0.8009 - val_smape: 1.3054

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 23s 176ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 38%|███▊      | 19/50 [1:00:31<1:03:08, 122.20s/trial, best loss: 0.7610878178901423]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 37s - 10ms/step - ia: 0.3025 - loss: 0.9370 - mae: 0.7148 - rmse: 0.9018 - smape: 1.4341 - val_ia: 0.2037 - val_loss: 0.8153 - val_mae: 0.6567 - val_rmse: 0.6978 - val_smape: 1.2435

Epoch 2/32

3830/3830 - 16s - 4ms/step - ia: 0.3566 - loss: 0.8700 - mae: 0.6860 - rmse: 0.8713 - smape: 1.2839 - val_ia: 0.1994 - val_loss: 0.7957 - val_mae: 0.6613 - val_rmse: 0.7016 - val_smape: 1.2698

Epoch 3/32

3830/3830 - 20s - 5ms/step - ia: 0.3634 - loss: 0.8572 - mae: 0.6812 - rmse: 0.8657 - smape: 1.2740 - val_ia: 0.2026 - val_loss: 0.7843 - val_mae: 0.6487 - val_rmse: 0.6901 - val_smape: 1.2367

Epoch 4/32

3830/3830 - 21s - 5ms/step - ia: 0.3675 - loss: 0.8482 - mae: 0.6774 - rmse: 0.8609 - smape: 1.2706 - val_ia: 0.2028 - val_loss: 0.7805 - val_mae: 0.6479 - val_rmse: 0.6893 - val_smape: 1.2284

Epoch 5/32

3830/3830 - 14s - 4ms/step - ia: 0.3710 - loss: 0.8413 - mae: 0.6738 - rmse: 0.8585 - smape: 1.2604 - val_ia: 0.2034 - val_loss: 0.7723 - val_mae: 0.6430 - val_rmse: 0.6845 - val_smape: 1.2194

Epoch 6/32

3830/3830 - 22s - 6ms/step - ia: 0.3734 - loss: 0.8362 - mae: 0.6720 - rmse: 0.8559 - smape: 1.2574 - val_ia: 0.2047 - val_loss: 0.7661 - val_mae: 0.6440 - val_rmse: 0.6856 - val_smape: 1.2225

Epoch 7/32

3830/3830 - 19s - 5ms/step - ia: 0.3767 - loss: 0.8313 - mae: 0.6693 - rmse: 0.8546 - smape: 1.2523 - val_ia: 0.2035 - val_loss: 0.7676 - val_mae: 0.6410 - val_rmse: 0.6825 - val_smape: 1.2168

Epoch 8/32

3830/3830 - 14s - 4ms/step - ia: 0.3774 - loss: 0.8307 - mae: 0.6693 - rmse: 0.8513 - smape: 1.2572 - val_ia: 0.2044 - val_loss: 0.7604 - val_mae: 0.6445 - val_rmse: 0.6863 - val_smape: 1.2192

Epoch 9/32

3830/3830 - 19s - 5ms/step - ia: 0.3827 - loss: 0.8217 - mae: 0.6654 - rmse: 0.8480 - smape: 1.2515 - val_ia: 0.2048 - val_loss: 0.7562 - val_mae: 0.6423 - val_rmse: 0.6832 - val_smape: 1.2444

Epoch 10/32

3830/3830 - 14s - 4ms/step - ia: 0.3825 - loss: 0.8207 - mae: 0.6649 - rmse: 0.8467 - smape: 1.2567 - val_ia: 0.2036 - val_loss: 0.7590 - val_mae: 0.6459 - val_rmse: 0.6869 - val_smape: 1.2519

Epoch 11/32

3830/3830 - 17s - 4ms/step - ia: 0.3814 - loss: 0.8207 - mae: 0.6651 - rmse: 0.8465 - smape: 1.2581 - val_ia: 0.2035 - val_loss: 0.7651 - val_mae: 0.6504 - val_rmse: 0.6923 - val_smape: 1.2420

Epoch 12/32

3830/3830 - 21s - 5ms/step - ia: 0.3860 - loss: 0.8149 - mae: 0.6628 - rmse: 0.8458 - smape: 1.2552 - val_ia: 0.2038 - val_loss: 0.7573 - val_mae: 0.6417 - val_rmse: 0.6837 - val_smape: 1.2291

Epoch 13/32

3830/3830 - 16s - 4ms/step - ia: 0.3856 - loss: 0.8109 - mae: 0.6616 - rmse: 0.8426 - smape: 1.2564 - val_ia: 0.2036 - val_loss: 0.7551 - val_mae: 0.6436 - val_rmse: 0.6852 - val_smape: 1.2488

Epoch 14/32

3830/3830 - 20s - 5ms/step - ia: 0.3906 - loss: 0.8086 - mae: 0.6589 - rmse: 0.8406 - smape: 1.2525 - val_ia: 0.2046 - val_loss: 0.7543 - val_mae: 0.6417 - val_rmse: 0.6837 - val_smape: 1.2272

Epoch 15/32

3830/3830 - 20s - 5ms/step - ia: 0.3886 - loss: 0.8110 - mae: 0.6610 - rmse: 0.8419 - smape: 1.2601 - val_ia: 0.2041 - val_loss: 0.7564 - val_mae: 0.6440 - val_rmse: 0.6857 - val_smape: 1.2375

Epoch 16/32

3830/3830 - 14s - 4ms/step - ia: 0.3902 - loss: 0.8062 - mae: 0.6591 - rmse: 0.8399 - smape: 1.2584 - val_ia: 0.2046 - val_loss: 0.7596 - val_mae: 0.6424 - val_rmse: 0.6854 - val_smape: 1.2235

Epoch 17/32

3830/3830 - 16s - 4ms/step - ia: 0.3904 - loss: 0.8108 - mae: 0.6601 - rmse: 0.8422 - smape: 1.2617 - val_ia: 0.2045 - val_loss: 0.7628 - val_mae: 0.6473 - val_rmse: 0.6900 - val_smape: 1.2265

Epoch 18/32

3830/3830 - 21s - 6ms/step - ia: 0.3916 - loss: 0.8021 - mae: 0.6580 - rmse: 0.8366 - smape: 1.2558 - val_ia: 0.2060 - val_loss: 0.7444 - val_mae: 0.6340 - val_rmse: 0.6771 - val_smape: 1.2198

Epoch 19/32

3830/3830 - 18s - 5ms/step - ia: 0.3938 - loss: 0.8035 - mae: 0.6576 - rmse: 0.8390 - smape: 1.2575 - val_ia: 0.2049 - val_loss: 0.7511 - val_mae: 0.6396 - val_rmse: 0.6824 - val_smape: 1.2292

Epoch 20/32

3830/3830 - 17s - 4ms/step - ia: 0.3909 - loss: 0.8047 - mae: 0.6585 - rmse: 0.8387 - smape: 1.2582 - val_ia: 0.2041 - val_loss: 0.7527 - val_mae: 0.6430 - val_rmse: 0.6854 - val_smape: 1.2485

Epoch 21/32

3830/3830 - 17s - 4ms/step - ia: 0.3924 - loss: 0.8054 - mae: 0.6583 - rmse: 0.8382 - smape: 1.2558 - val_ia: 0.2045 - val_loss: 0.7450 - val_mae: 0.6354 - val_rmse: 0.6780 - val_smape: 1.2323

Epoch 22/32

3830/3830 - 14s - 4ms/step - ia: 0.3934 - loss: 0.7998 - mae: 0.6565 - rmse: 0.8363 - smape: 1.2552 - val_ia: 0.2033 - val_loss: 0.7470 - val_mae: 0.6368 - val_rmse: 0.6793 - val_smape: 1.2447

Epoch 23/32

3830/3830 - 12s - 3ms/step - ia: 0.3968 - loss: 0.7954 - mae: 0.6540 - rmse: 0.8327 - smape: 1.2519 - val_ia: 0.2036 - val_loss: 0.7587 - val_mae: 0.6444 - val_rmse: 0.6877 - val_smape: 1.2487

Epoch 24/32

3830/3830 - 20s - 5ms/step - ia: 0.3915 - loss: 0.8051 - mae: 0.6581 - rmse: 0.8397 - smape: 1.2566 - val_ia: 0.2032 - val_loss: 0.7535 - val_mae: 0.6437 - val_rmse: 0.6861 - val_smape: 1.2509

Epoch 25/32

3830/3830 - 13s - 3ms/step - ia: 0.3972 - loss: 0.7933 - mae: 0.6534 - rmse: 0.8321 - smape: 1.2470 - val_ia: 0.2048 - val_loss: 0.7531 - val_mae: 0.6381 - val_rmse: 0.6816 - val_smape: 1.2041

Epoch 26/32

3830/3830 - 17s - 4ms/step - ia: 0.3946 - loss: 0.8003 - mae: 0.6561 - rmse: 0.8371 - smape: 1.2491 - val_ia: 0.2041 - val_loss: 0.7672 - val_mae: 0.6440 - val_rmse: 0.6886 - val_smape: 1.2175

Epoch 27/32

3830/3830 - 18s - 5ms/step - ia: 0.3947 - loss: 0.7964 - mae: 0.6551 - rmse: 0.8342 - smape: 1.2494 - val_ia: 0.2048 - val_loss: 0.7510 - val_mae: 0.6368 - val_rmse: 0.6807 - val_smape: 1.2174

Epoch 28/32

3830/3830 - 13s - 3ms/step - ia: 0.3959 - loss: 0.7994 - mae: 0.6554 - rmse: 0.8359 - smape: 1.2475 - val_ia: 0.2044 - val_loss: 0.7545 - val_mae: 0.6430 - val_rmse: 0.6867 - val_smape: 1.2247

Epoch 29/32

3830/3830 - 15s - 4ms/step - ia: 0.3942 - loss: 0.7983 - mae: 0.6561 - rmse: 0.8359 - smape: 1.2527 - val_ia: 0.2031 - val_loss: 0.7498 - val_mae: 0.6405 - val_rmse: 0.6838 - val_smape: 1.2353

Epoch 30/32

3830/3830 - 11s - 3ms/step - ia: 0.3973 - loss: 0.7945 - mae: 0.6527 - rmse: 0.8329 - smape: 1.2453 - val_ia: 0.2055 - val_loss: 0.7425 - val_mae: 0.6330 - val_rmse: 0.6766 - val_smape: 1.2157

Epoch 31/32

3830/3830 - 14s - 4ms/step - ia: 0.3965 - loss: 0.7930 - mae: 0.6532 - rmse: 0.8323 - smape: 1.2500 - val_ia: 0.2033 - val_loss: 0.7559 - val_mae: 0.6417 - val_rmse: 0.6851 - val_smape: 1.2370

Epoch 32/32

3830/3830 - 15s - 4ms/step - ia: 0.4013 - loss: 0.7897 - mae: 0.6509 - rmse: 0.8309 - smape: 1.2445 - val_ia: 0.2031 - val_loss: 0.7466 - val_mae: 0.6403 - val_rmse: 0.6830 - val_smape: 1.2560

Restoring model weights from the end of the best epoch: 30.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:34 700ms/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

 40%|████      | 20/50 [1:09:47<2:06:16, 252.54s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 12s - 99ms/step - ia: 0.2163 - loss: 0.9218 - mae: 0.7224 - rmse: 0.9575 - smape: 1.5398 - val_ia: 0.2757 - val_loss: 0.8528 - val_mae: 0.6866 - val_rmse: 0.8475 - val_smape: 1.4353

Epoch 2/32

120/120 - 1s - 8ms/step - ia: 0.2860 - loss: 0.8770 - mae: 0.6989 - rmse: 0.9338 - smape: 1.4331 - val_ia: 0.2949 - val_loss: 0.8280 - val_mae: 0.6746 - val_rmse: 0.8367 - val_smape: 1.3709

Epoch 3/32

120/120 - 1s - 9ms/step - ia: 0.3207 - loss: 0.8568 - mae: 0.6893 - rmse: 0.9231 - smape: 1.3832 - val_ia: 0.3080 - val_loss: 0.8166 - val_mae: 0.6695 - val_rmse: 0.8325 - val_smape: 1.3431

Epoch 4/32

120/120 - 1s - 10ms/step - ia: 0.3394 - loss: 0.8451 - mae: 0.6834 - rmse: 0.9169 - smape: 1.3603 - val_ia: 0.3157 - val_loss: 0.8096 - val_mae: 0.6667 - val_rmse: 0.8301 - val_smape: 1.3310

Epoch 5/32

120/120 - 1s - 11ms/step - ia: 0.3514 - loss: 0.8369 - mae: 0.6788 - rmse: 0.9119 - smape: 1.3446 - val_ia: 0.3218 - val_loss: 0.8026 - val_mae: 0.6621 - val_rmse: 0.8262 - val_smape: 1.3170

Epoch 6/32

120/120 - 1s - 6ms/step - ia: 0.3589 - loss: 0.8301 - mae: 0.6741 - rmse: 0.9095 - smape: 1.3321 - val_ia: 0.3237 - val_loss: 0.8000 - val_mae: 0.6635 - val_rmse: 0.8266 - val_smape: 1.3229

Epoch 7/32

120/120 - 1s - 8ms/step - ia: 0.3649 - loss: 0.8245 - mae: 0.6717 - rmse: 0.9056 - smape: 1.3248 - val_ia: 0.3289 - val_loss: 0.7953 - val_mae: 0.6596 - val_rmse: 0.8238 - val_smape: 1.3126

Epoch 8/32

120/120 - 1s - 7ms/step - ia: 0.3705 - loss: 0.8197 - mae: 0.6678 - rmse: 0.9032 - smape: 1.3148 - val_ia: 0.3308 - val_loss: 0.7913 - val_mae: 0.6576 - val_rmse: 0.8218 - val_smape: 1.3071

Epoch 9/32

120/120 - 1s - 5ms/step - ia: 0.3770 - loss: 0.8152 - mae: 0.6656 - rmse: 0.9003 - smape: 1.3053 - val_ia: 0.3337 - val_loss: 0.7881 - val_mae: 0.6557 - val_rmse: 0.8202 - val_smape: 1.3013

Epoch 10/32

120/120 - 1s - 6ms/step - ia: 0.3804 - loss: 0.8112 - mae: 0.6631 - rmse: 0.8982 - smape: 1.3000 - val_ia: 0.3344 - val_loss: 0.7858 - val_mae: 0.6555 - val_rmse: 0.8196 - val_smape: 1.3016

Epoch 11/32

120/120 - 2s - 15ms/step - ia: 0.3830 - loss: 0.8075 - mae: 0.6608 - rmse: 0.8957 - smape: 1.2950 - val_ia: 0.3370 - val_loss: 0.7856 - val_mae: 0.6557 - val_rmse: 0.8203 - val_smape: 1.3000

Epoch 12/32

120/120 - 1s - 9ms/step - ia: 0.3865 - loss: 0.8043 - mae: 0.6591 - rmse: 0.8944 - smape: 1.2894 - val_ia: 0.3396 - val_loss: 0.7833 - val_mae: 0.6539 - val_rmse: 0.8190 - val_smape: 1.2943

Epoch 13/32

120/120 - 1s - 11ms/step - ia: 0.3923 - loss: 0.8012 - mae: 0.6575 - rmse: 0.8925 - smape: 1.2811 - val_ia: 0.3411 - val_loss: 0.7786 - val_mae: 0.6502 - val_rmse: 0.8155 - val_smape: 1.2867

Epoch 14/32

120/120 - 1s - 9ms/step - ia: 0.3925 - loss: 0.7985 - mae: 0.6553 - rmse: 0.8906 - smape: 1.2790 - val_ia: 0.3422 - val_loss: 0.7790 - val_mae: 0.6511 - val_rmse: 0.8165 - val_smape: 1.2864

Epoch 15/32

120/120 - 1s - 11ms/step - ia: 0.3967 - loss: 0.7960 - mae: 0.6546 - rmse: 0.8898 - smape: 1.2734 - val_ia: 0.3432 - val_loss: 0.7766 - val_mae: 0.6498 - val_rmse: 0.8152 - val_smape: 1.2848

Epoch 16/32

120/120 - 1s - 12ms/step - ia: 0.3975 - loss: 0.7937 - mae: 0.6530 - rmse: 0.8886 - smape: 1.2715 - val_ia: 0.3443 - val_loss: 0.7777 - val_mae: 0.6504 - val_rmse: 0.8163 - val_smape: 1.2841

Epoch 17/32

120/120 - 1s - 8ms/step - ia: 0.4004 - loss: 0.7915 - mae: 0.6521 - rmse: 0.8875 - smape: 1.2680 - val_ia: 0.3454 - val_loss: 0.7741 - val_mae: 0.6478 - val_rmse: 0.8137 - val_smape: 1.2772

Epoch 18/32

120/120 - 1s - 11ms/step - ia: 0.4022 - loss: 0.7895 - mae: 0.6501 - rmse: 0.8860 - smape: 1.2644 - val_ia: 0.3454 - val_loss: 0.7741 - val_mae: 0.6486 - val_rmse: 0.8142 - val_smape: 1.2784

Epoch 19/32

120/120 - 1s - 11ms/step - ia: 0.4029 - loss: 0.7875 - mae: 0.6499 - rmse: 0.8852 - smape: 1.2644 - val_ia: 0.3475 - val_loss: 0.7766 - val_mae: 0.6502 - val_rmse: 0.8165 - val_smape: 1.2802

Epoch 20/32

120/120 - 1s - 11ms/step - ia: 0.4068 - loss: 0.7856 - mae: 0.6482 - rmse: 0.8836 - smape: 1.2584 - val_ia: 0.3466 - val_loss: 0.7774 - val_mae: 0.6519 - val_rmse: 0.8177 - val_smape: 1.2850

Epoch 21/32

120/120 - 1s - 11ms/step - ia: 0.4067 - loss: 0.7839 - mae: 0.6481 - rmse: 0.8834 - smape: 1.2588 - val_ia: 0.3487 - val_loss: 0.7744 - val_mae: 0.6489 - val_rmse: 0.8152 - val_smape: 1.2755

Epoch 22/32

120/120 - 1s - 11ms/step - ia: 0.4093 - loss: 0.7822 - mae: 0.6469 - rmse: 0.8821 - smape: 1.2553 - val_ia: 0.3488 - val_loss: 0.7746 - val_mae: 0.6494 - val_rmse: 0.8157 - val_smape: 1.2777

Epoch 23/32

120/120 - 2s - 14ms/step - ia: 0.4113 - loss: 0.7804 - mae: 0.6459 - rmse: 0.8807 - smape: 1.2527 - val_ia: 0.3503 - val_loss: 0.7720 - val_mae: 0.6473 - val_rmse: 0.8138 - val_smape: 1.2708

Epoch 24/32

120/120 - 3s - 21ms/step - ia: 0.4118 - loss: 0.7788 - mae: 0.6449 - rmse: 0.8796 - smape: 1.2517 - val_ia: 0.3502 - val_loss: 0.7724 - val_mae: 0.6482 - val_rmse: 0.8145 - val_smape: 1.2728

Epoch 25/32

120/120 - 1s - 11ms/step - ia: 0.4135 - loss: 0.7775 - mae: 0.6445 - rmse: 0.8796 - smape: 1.2490 - val_ia: 0.3520 - val_loss: 0.7725 - val_mae: 0.6474 - val_rmse: 0.8143 - val_smape: 1.2677

Epoch 26/32

120/120 - 1s - 11ms/step - ia: 0.4141 - loss: 0.7758 - mae: 0.6430 - rmse: 0.8784 - smape: 1.2475 - val_ia: 0.3514 - val_loss: 0.7739 - val_mae: 0.6497 - val_rmse: 0.8162 - val_smape: 1.2760

Epoch 27/32

120/120 - 2s - 14ms/step - ia: 0.4171 - loss: 0.7744 - mae: 0.6423 - rmse: 0.8772 - smape: 1.2433 - val_ia: 0.3509 - val_loss: 0.7735 - val_mae: 0.6499 - val_rmse: 0.8160 - val_smape: 1.2765

Epoch 28/32

120/120 - 2s - 18ms/step - ia: 0.4162 - loss: 0.7729 - mae: 0.6425 - rmse: 0.8767 - smape: 1.2454 - val_ia: 0.3538 - val_loss: 0.7722 - val_mae: 0.6478 - val_rmse: 0.8149 - val_smape: 1.2681

Epoch 29/32

120/120 - 1s - 11ms/step - ia: 0.4197 - loss: 0.7716 - mae: 0.6411 - rmse: 0.8769 - smape: 1.2401 - val_ia: 0.3524 - val_loss: 0.7721 - val_mae: 0.6486 - val_rmse: 0.8152 - val_smape: 1.2725

Epoch 30/32

120/120 - 1s - 10ms/step - ia: 0.4192 - loss: 0.7703 - mae: 0.6407 - rmse: 0.8750 - smape: 1.2402 - val_ia: 0.3539 - val_loss: 0.7710 - val_mae: 0.6476 - val_rmse: 0.8145 - val_smape: 1.2692

Epoch 31/32

120/120 - 1s - 7ms/step - ia: 0.4209 - loss: 0.7691 - mae: 0.6402 - rmse: 0.8739 - smape: 1.2384 - val_ia: 0.3546 - val_loss: 0.7714 - val_mae: 0.6478 - val_rmse: 0.8148 - val_smape: 1.2673

Epoch 32/32

120/120 - 2s - 19ms/step - ia: 0.4222 - loss: 0.7679 - mae: 0.6393 - rmse: 0.8731 - smape: 1.2372 - val_ia: 0.3552 - val_loss: 0.7696 - val_mae: 0.6466 - val_rmse: 0.8137 - val_smape: 1.2650

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 34s 253ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 90/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 42%|████▏     | 21/50 [1:10:47<1:34:07, 194.74s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 32s - 8ms/step - ia: 0.3130 - loss: 0.9209 - mae: 0.7120 - rmse: 0.8967 - smape: 1.4875 - val_ia: 0.1901 - val_loss: 0.8416 - val_mae: 0.7119 - val_rmse: 0.7535 - val_smape: 1.6564

Epoch 2/32

3830/3830 - 13s - 3ms/step - ia: 0.2256 - loss: 1.0125 - mae: 0.7464 - rmse: 0.9319 - smape: 1.7832 - val_ia: 0.1877 - val_loss: 0.9651 - val_mae: 0.7288 - val_rmse: 0.7651 - val_smape: 1.8224

Epoch 3/32

3830/3830 - 21s - 5ms/step - ia: 0.2504 - loss: 0.9845 - mae: 0.7371 - rmse: 0.9220 - smape: 1.6196 - val_ia: 0.1819 - val_loss: 0.9594 - val_mae: 0.7409 - val_rmse: 0.7828 - val_smape: 1.4633

Epoch 4/32

3830/3830 - 13s - 3ms/step - ia: 0.2350 - loss: 1.0182 - mae: 0.7436 - rmse: 0.9310 - smape: 1.6976 - val_ia: 0.1808 - val_loss: 0.9776 - val_mae: 0.7559 - val_rmse: 0.7915 - val_smape: 1.8204

Epoch 5/32

3830/3830 - 21s - 6ms/step - ia: 0.2176 - loss: 1.0034 - mae: 0.7496 - rmse: 0.9329 - smape: 1.8469 - val_ia: 0.1840 - val_loss: 1.0260 - val_mae: 0.7497 - val_rmse: 0.7879 - val_smape: 1.9090

Epoch 6/32

3830/3830 - 18s - 5ms/step - ia: 0.2145 - loss: 1.0191 - mae: 0.7516 - rmse: 0.9351 - smape: 1.8435 - val_ia: 0.1863 - val_loss: 0.9678 - val_mae: 0.7350 - val_rmse: 0.7710 - val_smape: 1.9437

Epoch 7/32

3830/3830 - 17s - 5ms/step - ia: 0.2163 - loss: 1.0021 - mae: 0.7504 - rmse: 0.9329 - smape: 1.8480 - val_ia: 0.1802 - val_loss: 0.9807 - val_mae: 0.7601 - val_rmse: 0.7956 - val_smape: 1.8016

Epoch 8/32

3830/3830 - 17s - 4ms/step - ia: 0.2144 - loss: 1.0028 - mae: 0.7510 - rmse: 0.9336 - smape: 1.8497 - val_ia: 0.1855 - val_loss: 0.9688 - val_mae: 0.7381 - val_rmse: 0.7741 - val_smape: 1.9764

Epoch 9/32

3830/3830 - 20s - 5ms/step - ia: 0.2166 - loss: 1.0024 - mae: 0.7510 - rmse: 0.9333 - smape: 1.8563 - val_ia: 0.1855 - val_loss: 0.9689 - val_mae: 0.7382 - val_rmse: 0.7742 - val_smape: 1.9741

Epoch 10/32

3830/3830 - 21s - 6ms/step - ia: 0.2145 - loss: 1.0026 - mae: 0.7507 - rmse: 0.9316 - smape: 1.8492 - val_ia: 0.1864 - val_loss: 0.9676 - val_mae: 0.7342 - val_rmse: 0.7703 - val_smape: 1.9253

Epoch 11/32

3830/3830 - 30s - 8ms/step - ia: 0.2148 - loss: 1.0019 - mae: 0.7507 - rmse: 0.9322 - smape: 1.8413 - val_ia: 0.1880 - val_loss: 0.9663 - val_mae: 0.7279 - val_rmse: 0.7642 - val_smape: 1.8009

Epoch 12/32

3830/3830 - 25s - 7ms/step - ia: 0.2126 - loss: 1.0026 - mae: 0.7509 - rmse: 0.9343 - smape: 1.8541 - val_ia: 0.1844 - val_loss: 0.9704 - val_mae: 0.7421 - val_rmse: 0.7780 - val_smape: 1.9216

Epoch 13/32

3830/3830 - 17s - 4ms/step - ia: 0.2141 - loss: 1.0025 - mae: 0.7507 - rmse: 0.9353 - smape: 1.8671 - val_ia: 0.1794 - val_loss: 0.9865 - val_mae: 0.7680 - val_rmse: 0.8034 - val_smape: 1.7710

Epoch 14/32

3830/3830 - 20s - 5ms/step - ia: 0.2146 - loss: 1.0053 - mae: 0.7514 - rmse: 0.9355 - smape: 1.8769 - val_ia: 0.1893 - val_loss: 0.9659 - val_mae: 0.7234 - val_rmse: 0.7598 - val_smape: 1.7265

Epoch 15/32

3830/3830 - 14s - 4ms/step - ia: 0.2124 - loss: 1.0026 - mae: 0.7506 - rmse: 0.9330 - smape: 1.8678 - val_ia: 0.1820 - val_loss: 0.9752 - val_mae: 0.7515 - val_rmse: 0.7872 - val_smape: 1.8465

Epoch 16/32

3830/3830 - 14s - 4ms/step - ia: 0.2171 - loss: 1.0028 - mae: 0.7507 - rmse: 0.9334 - smape: 1.8596 - val_ia: 0.1841 - val_loss: 0.9710 - val_mae: 0.7435 - val_rmse: 0.7794 - val_smape: 1.9072

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 35s 261ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 44%|████▍     | 22/50 [1:16:03<1:47:52, 231.17s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1915/1915 - 22s - 12ms/step - ia: 0.2352 - loss: 1.0685 - mae: 0.7693 - rmse: 0.9928 - smape: 1.5685 - val_ia: 0.2229 - val_loss: 0.9418 - val_mae: 0.7191 - val_rmse: 0.7791 - val_smape: 1.7633

Epoch 2/64

1915/1915 - 7s - 3ms/step - ia: 0.2357 - loss: 0.9695 - mae: 0.7337 - rmse: 0.9462 - smape: 1.5727 - val_ia: 0.2295 - val_loss: 0.8643 - val_mae: 0.6880 - val_rmse: 0.7497 - val_smape: 1.4214

Epoch 3/64

1915/1915 - 11s - 6ms/step - ia: 0.2965 - loss: 0.9224 - mae: 0.7137 - rmse: 0.9233 - smape: 1.4278 - val_ia: 0.2344 - val_loss: 0.8395 - val_mae: 0.6784 - val_rmse: 0.7427 - val_smape: 1.3140

Epoch 4/64

1915/1915 - 20s - 11ms/step - ia: 0.3084 - loss: 0.9144 - mae: 0.7084 - rmse: 0.9190 - smape: 1.3905 - val_ia: 0.2384 - val_loss: 0.8333 - val_mae: 0.6669 - val_rmse: 0.7332 - val_smape: 1.2576

Epoch 5/64

1915/1915 - 6s - 3ms/step - ia: 0.3196 - loss: 0.9047 - mae: 0.7040 - rmse: 0.9132 - smape: 1.3651 - val_ia: 0.2386 - val_loss: 0.8290 - val_mae: 0.6680 - val_rmse: 0.7346 - val_smape: 1.2514

Epoch 6/64

1915/1915 - 7s - 4ms/step - ia: 0.3268 - loss: 0.8968 - mae: 0.7007 - rmse: 0.9102 - smape: 1.3467 - val_ia: 0.2387 - val_loss: 0.8213 - val_mae: 0.6670 - val_rmse: 0.7329 - val_smape: 1.2583

Epoch 7/64

1915/1915 - 8s - 4ms/step - ia: 0.3259 - loss: 0.8965 - mae: 0.6992 - rmse: 0.9102 - smape: 1.3451 - val_ia: 0.2399 - val_loss: 0.8230 - val_mae: 0.6654 - val_rmse: 0.7330 - val_smape: 1.2332

Epoch 8/64

1915/1915 - 8s - 4ms/step - ia: 0.3354 - loss: 0.8893 - mae: 0.6965 - rmse: 0.9076 - smape: 1.3302 - val_ia: 0.2395 - val_loss: 0.8139 - val_mae: 0.6644 - val_rmse: 0.7305 - val_smape: 1.2532

Epoch 9/64

1915/1915 - 10s - 5ms/step - ia: 0.3316 - loss: 0.8889 - mae: 0.6968 - rmse: 0.9071 - smape: 1.3361 - val_ia: 0.2399 - val_loss: 0.8086 - val_mae: 0.6643 - val_rmse: 0.7307 - val_smape: 1.2475

Epoch 10/64

1915/1915 - 9s - 5ms/step - ia: 0.3358 - loss: 0.8874 - mae: 0.6965 - rmse: 0.9063 - smape: 1.3325 - val_ia: 0.2394 - val_loss: 0.8174 - val_mae: 0.6639 - val_rmse: 0.7304 - val_smape: 1.2520

Epoch 11/64

1915/1915 - 9s - 4ms/step - ia: 0.3405 - loss: 0.8837 - mae: 0.6927 - rmse: 0.9042 - smape: 1.3221 - val_ia: 0.2402 - val_loss: 0.8171 - val_mae: 0.6661 - val_rmse: 0.7336 - val_smape: 1.2467

Epoch 12/64

1915/1915 - 6s - 3ms/step - ia: 0.3403 - loss: 0.8831 - mae: 0.6931 - rmse: 0.9037 - smape: 1.3262 - val_ia: 0.2391 - val_loss: 0.8085 - val_mae: 0.6680 - val_rmse: 0.7339 - val_smape: 1.2692

Epoch 13/64

1915/1915 - 14s - 7ms/step - ia: 0.3423 - loss: 0.8783 - mae: 0.6910 - rmse: 0.9008 - smape: 1.3201 - val_ia: 0.2416 - val_loss: 0.8066 - val_mae: 0.6591 - val_rmse: 0.7265 - val_smape: 1.2389

Epoch 14/64

1915/1915 - 12s - 6ms/step - ia: 0.3441 - loss: 0.8783 - mae: 0.6909 - rmse: 0.9009 - smape: 1.3192 - val_ia: 0.2437 - val_loss: 0.7920 - val_mae: 0.6526 - val_rmse: 0.7195 - val_smape: 1.2323

Epoch 15/64

1915/1915 - 7s - 4ms/step - ia: 0.3509 - loss: 0.8704 - mae: 0.6877 - rmse: 0.8970 - smape: 1.3109 - val_ia: 0.2434 - val_loss: 0.7935 - val_mae: 0.6508 - val_rmse: 0.7175 - val_smape: 1.2296

Epoch 16/64

1915/1915 - 7s - 4ms/step - ia: 0.3444 - loss: 0.8724 - mae: 0.6895 - rmse: 0.8985 - smape: 1.3235 - val_ia: 0.2421 - val_loss: 0.7908 - val_mae: 0.6572 - val_rmse: 0.7239 - val_smape: 1.2515

Epoch 17/64

1915/1915 - 13s - 7ms/step - ia: 0.3520 - loss: 0.8686 - mae: 0.6869 - rmse: 0.8967 - smape: 1.3123 - val_ia: 0.2436 - val_loss: 0.7845 - val_mae: 0.6512 - val_rmse: 0.7175 - val_smape: 1.2365

Epoch 18/64

1915/1915 - 18s - 9ms/step - ia: 0.3482 - loss: 0.8717 - mae: 0.6871 - rmse: 0.8966 - smape: 1.3156 - val_ia: 0.2429 - val_loss: 0.7894 - val_mae: 0.6526 - val_rmse: 0.7196 - val_smape: 1.2352

Epoch 19/64

1915/1915 - 8s - 4ms/step - ia: 0.3472 - loss: 0.8737 - mae: 0.6868 - rmse: 0.8989 - smape: 1.3172 - val_ia: 0.2422 - val_loss: 0.7878 - val_mae: 0.6549 - val_rmse: 0.7216 - val_smape: 1.2440

Epoch 20/64

1915/1915 - 6s - 3ms/step - ia: 0.3524 - loss: 0.8676 - mae: 0.6857 - rmse: 0.8962 - smape: 1.3123 - val_ia: 0.2444 - val_loss: 0.7764 - val_mae: 0.6476 - val_rmse: 0.7139 - val_smape: 1.2345

Epoch 21/64

1915/1915 - 5s - 2ms/step - ia: 0.3514 - loss: 0.8671 - mae: 0.6858 - rmse: 0.8955 - smape: 1.3136 - val_ia: 0.2429 - val_loss: 0.7817 - val_mae: 0.6528 - val_rmse: 0.7194 - val_smape: 1.2421

Epoch 22/64

1915/1915 - 6s - 3ms/step - ia: 0.3549 - loss: 0.8646 - mae: 0.6841 - rmse: 0.8941 - smape: 1.3108 - val_ia: 0.2421 - val_loss: 0.7833 - val_mae: 0.6531 - val_rmse: 0.7192 - val_smape: 1.2557

Epoch 23/64

1915/1915 - 11s - 6ms/step - ia: 0.3555 - loss: 0.8616 - mae: 0.6829 - rmse: 0.8923 - smape: 1.3125 - val_ia: 0.2414 - val_loss: 0.7816 - val_mae: 0.6534 - val_rmse: 0.7194 - val_smape: 1.2530

Epoch 24/64

1915/1915 - 9s - 5ms/step - ia: 0.3553 - loss: 0.8632 - mae: 0.6834 - rmse: 0.8934 - smape: 1.3137 - val_ia: 0.2424 - val_loss: 0.7790 - val_mae: 0.6496 - val_rmse: 0.7157 - val_smape: 1.2531

Epoch 25/64

1915/1915 - 11s - 6ms/step - ia: 0.3563 - loss: 0.8612 - mae: 0.6830 - rmse: 0.8924 - smape: 1.3154 - val_ia: 0.2446 - val_loss: 0.7700 - val_mae: 0.6450 - val_rmse: 0.7115 - val_smape: 1.2332

Epoch 26/64

1915/1915 - 10s - 5ms/step - ia: 0.3548 - loss: 0.8593 - mae: 0.6823 - rmse: 0.8916 - smape: 1.3173 - val_ia: 0.2437 - val_loss: 0.7740 - val_mae: 0.6500 - val_rmse: 0.7175 - val_smape: 1.2391

Epoch 27/64

1915/1915 - 6s - 3ms/step - ia: 0.3608 - loss: 0.8571 - mae: 0.6802 - rmse: 0.8893 - smape: 1.3105 - val_ia: 0.2446 - val_loss: 0.7717 - val_mae: 0.6476 - val_rmse: 0.7158 - val_smape: 1.2210

Epoch 28/64

1915/1915 - 5s - 3ms/step - ia: 0.3566 - loss: 0.8593 - mae: 0.6827 - rmse: 0.8910 - smape: 1.3233 - val_ia: 0.2436 - val_loss: 0.7708 - val_mae: 0.6476 - val_rmse: 0.7141 - val_smape: 1.2461

Epoch 29/64

1915/1915 - 11s - 6ms/step - ia: 0.3600 - loss: 0.8568 - mae: 0.6808 - rmse: 0.8903 - smape: 1.3136 - val_ia: 0.2425 - val_loss: 0.7739 - val_mae: 0.6514 - val_rmse: 0.7176 - val_smape: 1.2562

Epoch 30/64

1915/1915 - 6s - 3ms/step - ia: 0.3595 - loss: 0.8541 - mae: 0.6807 - rmse: 0.8893 - smape: 1.3150 - val_ia: 0.2448 - val_loss: 0.7672 - val_mae: 0.6469 - val_rmse: 0.7141 - val_smape: 1.2384

Epoch 31/64

1915/1915 - 9s - 5ms/step - ia: 0.3611 - loss: 0.8560 - mae: 0.6797 - rmse: 0.8891 - smape: 1.3079 - val_ia: 0.2413 - val_loss: 0.7745 - val_mae: 0.6529 - val_rmse: 0.7190 - val_smape: 1.2676

Epoch 32/64

1915/1915 - 10s - 5ms/step - ia: 0.3581 - loss: 0.8555 - mae: 0.6812 - rmse: 0.8889 - smape: 1.3144 - val_ia: 0.2422 - val_loss: 0.7741 - val_mae: 0.6511 - val_rmse: 0.7183 - val_smape: 1.2472

Epoch 33/64

1915/1915 - 11s - 6ms/step - ia: 0.3620 - loss: 0.8551 - mae: 0.6803 - rmse: 0.8889 - smape: 1.3108 - val_ia: 0.2449 - val_loss: 0.7684 - val_mae: 0.6474 - val_rmse: 0.7145 - val_smape: 1.2377

Epoch 34/64

1915/1915 - 10s - 5ms/step - ia: 0.3632 - loss: 0.8527 - mae: 0.6792 - rmse: 0.8886 - smape: 1.3073 - val_ia: 0.2424 - val_loss: 0.7744 - val_mae: 0.6492 - val_rmse: 0.7151 - val_smape: 1.2603

Epoch 35/64

1915/1915 - 6s - 3ms/step - ia: 0.3566 - loss: 0.8557 - mae: 0.6807 - rmse: 0.8899 - smape: 1.3204 - val_ia: 0.2414 - val_loss: 0.7738 - val_mae: 0.6533 - val_rmse: 0.7197 - val_smape: 1.2703

Epoch 36/64

1915/1915 - 15s - 8ms/step - ia: 0.3621 - loss: 0.8487 - mae: 0.6789 - rmse: 0.8858 - smape: 1.3160 - val_ia: 0.2434 - val_loss: 0.7666 - val_mae: 0.6480 - val_rmse: 0.7152 - val_smape: 1.2485

Epoch 37/64

1915/1915 - 8s - 4ms/step - ia: 0.3638 - loss: 0.8520 - mae: 0.6787 - rmse: 0.8884 - smape: 1.3093 - val_ia: 0.2431 - val_loss: 0.7693 - val_mae: 0.6471 - val_rmse: 0.7140 - val_smape: 1.2525

Epoch 38/64

1915/1915 - 10s - 5ms/step - ia: 0.3622 - loss: 0.8490 - mae: 0.6780 - rmse: 0.8868 - smape: 1.3115 - val_ia: 0.2425 - val_loss: 0.7697 - val_mae: 0.6498 - val_rmse: 0.7169 - val_smape: 1.2580

Epoch 39/64

1915/1915 - 11s - 6ms/step - ia: 0.3656 - loss: 0.8466 - mae: 0.6766 - rmse: 0.8856 - smape: 1.3062 - val_ia: 0.2431 - val_loss: 0.7651 - val_mae: 0.6468 - val_rmse: 0.7143 - val_smape: 1.2464

Epoch 40/64

1915/1915 - 10s - 5ms/step - ia: 0.3637 - loss: 0.8484 - mae: 0.6772 - rmse: 0.8849 - smape: 1.3125 - val_ia: 0.2450 - val_loss: 0.7651 - val_mae: 0.6470 - val_rmse: 0.7145 - val_smape: 1.2422

Epoch 41/64

1915/1915 - 7s - 4ms/step - ia: 0.3590 - loss: 0.8547 - mae: 0.6813 - rmse: 0.8904 - smape: 1.3201 - val_ia: 0.2433 - val_loss: 0.7678 - val_mae: 0.6471 - val_rmse: 0.7139 - val_smape: 1.2520

Epoch 42/64

1915/1915 - 10s - 5ms/step - ia: 0.3638 - loss: 0.8508 - mae: 0.6783 - rmse: 0.8876 - smape: 1.3081 - val_ia: 0.2429 - val_loss: 0.7700 - val_mae: 0.6475 - val_rmse: 0.7143 - val_smape: 1.2526

Epoch 43/64

1915/1915 - 14s - 7ms/step - ia: 0.3637 - loss: 0.8468 - mae: 0.6772 - rmse: 0.8859 - smape: 1.3140 - val_ia: 0.2430 - val_loss: 0.7656 - val_mae: 0.6453 - val_rmse: 0.7130 - val_smape: 1.2431

Epoch 44/64

1915/1915 - 19s - 10ms/step - ia: 0.3647 - loss: 0.8481 - mae: 0.6778 - rmse: 0.8859 - smape: 1.3107 - val_ia: 0.2453 - val_loss: 0.7639 - val_mae: 0.6486 - val_rmse: 0.7159 - val_smape: 1.2546

Epoch 45/64

1915/1915 - 9s - 5ms/step - ia: 0.3630 - loss: 0.8468 - mae: 0.6783 - rmse: 0.8863 - smape: 1.3158 - val_ia: 0.2426 - val_loss: 0.7657 - val_mae: 0.6472 - val_rmse: 0.7148 - val_smape: 1.2539

Epoch 46/64

1915/1915 - 7s - 4ms/step - ia: 0.3660 - loss: 0.8472 - mae: 0.6777 - rmse: 0.8853 - smape: 1.3113 - val_ia: 0.2447 - val_loss: 0.7620 - val_mae: 0.6431 - val_rmse: 0.7103 - val_smape: 1.2400

Epoch 47/64

1915/1915 - 6s - 3ms/step - ia: 0.3657 - loss: 0.8453 - mae: 0.6759 - rmse: 0.8843 - smape: 1.3127 - val_ia: 0.2427 - val_loss: 0.7636 - val_mae: 0.6461 - val_rmse: 0.7147 - val_smape: 1.2367

Epoch 48/64

1915/1915 - 6s - 3ms/step - ia: 0.3659 - loss: 0.8489 - mae: 0.6775 - rmse: 0.8853 - smape: 1.3101 - val_ia: 0.2442 - val_loss: 0.7612 - val_mae: 0.6424 - val_rmse: 0.7101 - val_smape: 1.2359

Epoch 49/64

1915/1915 - 11s - 6ms/step - ia: 0.3646 - loss: 0.8431 - mae: 0.6766 - rmse: 0.8829 - smape: 1.3136 - val_ia: 0.2455 - val_loss: 0.7571 - val_mae: 0.6442 - val_rmse: 0.7117 - val_smape: 1.2500

Epoch 50/64

1915/1915 - 13s - 7ms/step - ia: 0.3658 - loss: 0.8445 - mae: 0.6763 - rmse: 0.8851 - smape: 1.3140 - val_ia: 0.2451 - val_loss: 0.7620 - val_mae: 0.6466 - val_rmse: 0.7141 - val_smape: 1.2453

Epoch 51/64

1915/1915 - 7s - 4ms/step - ia: 0.3678 - loss: 0.8431 - mae: 0.6758 - rmse: 0.8830 - smape: 1.3078 - val_ia: 0.2434 - val_loss: 0.7605 - val_mae: 0.6431 - val_rmse: 0.7108 - val_smape: 1.2420

Epoch 52/64

1915/1915 - 6s - 3ms/step - ia: 0.3636 - loss: 0.8448 - mae: 0.6771 - rmse: 0.8845 - smape: 1.3153 - val_ia: 0.2445 - val_loss: 0.7605 - val_mae: 0.6439 - val_rmse: 0.7124 - val_smape: 1.2317

Epoch 53/64

1915/1915 - 5s - 3ms/step - ia: 0.3683 - loss: 0.8424 - mae: 0.6754 - rmse: 0.8825 - smape: 1.3077 - val_ia: 0.2453 - val_loss: 0.7578 - val_mae: 0.6435 - val_rmse: 0.7119 - val_smape: 1.2390

Epoch 54/64

1915/1915 - 10s - 5ms/step - ia: 0.3681 - loss: 0.8397 - mae: 0.6744 - rmse: 0.8825 - smape: 1.3090 - val_ia: 0.2446 - val_loss: 0.7565 - val_mae: 0.6424 - val_rmse: 0.7106 - val_smape: 1.2397

Epoch 55/64

1915/1915 - 8s - 4ms/step - ia: 0.3671 - loss: 0.8415 - mae: 0.6759 - rmse: 0.8823 - smape: 1.3133 - val_ia: 0.2449 - val_loss: 0.7532 - val_mae: 0.6391 - val_rmse: 0.7072 - val_smape: 1.2386

Epoch 56/64

1915/1915 - 8s - 4ms/step - ia: 0.3653 - loss: 0.8436 - mae: 0.6772 - rmse: 0.8840 - smape: 1.3135 - val_ia: 0.2412 - val_loss: 0.7614 - val_mae: 0.6463 - val_rmse: 0.7126 - val_smape: 1.2659

Epoch 57/64

1915/1915 - 9s - 5ms/step - ia: 0.3664 - loss: 0.8396 - mae: 0.6744 - rmse: 0.8826 - smape: 1.3090 - val_ia: 0.2443 - val_loss: 0.7545 - val_mae: 0.6401 - val_rmse: 0.7085 - val_smape: 1.2379

Epoch 58/64

1915/1915 - 8s - 4ms/step - ia: 0.3661 - loss: 0.8412 - mae: 0.6758 - rmse: 0.8823 - smape: 1.3155 - val_ia: 0.2452 - val_loss: 0.7568 - val_mae: 0.6426 - val_rmse: 0.7117 - val_smape: 1.2353

Epoch 59/64

1915/1915 - 8s - 4ms/step - ia: 0.3701 - loss: 0.8405 - mae: 0.6748 - rmse: 0.8820 - smape: 1.3079 - val_ia: 0.2448 - val_loss: 0.7543 - val_mae: 0.6422 - val_rmse: 0.7099 - val_smape: 1.2546

Epoch 60/64

1915/1915 - 9s - 5ms/step - ia: 0.3677 - loss: 0.8401 - mae: 0.6740 - rmse: 0.8821 - smape: 1.3130 - val_ia: 0.2429 - val_loss: 0.7580 - val_mae: 0.6477 - val_rmse: 0.7154 - val_smape: 1.2638

Epoch 61/64

1915/1915 - 11s - 6ms/step - ia: 0.3705 - loss: 0.8378 - mae: 0.6732 - rmse: 0.8796 - smape: 1.3084 - val_ia: 0.2418 - val_loss: 0.7605 - val_mae: 0.6494 - val_rmse: 0.7170 - val_smape: 1.2721

Epoch 62/64

1915/1915 - 6s - 3ms/step - ia: 0.3651 - loss: 0.8423 - mae: 0.6747 - rmse: 0.8824 - smape: 1.3129 - val_ia: 0.2428 - val_loss: 0.7604 - val_mae: 0.6450 - val_rmse: 0.7141 - val_smape: 1.2388

Epoch 63/64

1915/1915 - 6s - 3ms/step - ia: 0.3698 - loss: 0.8422 - mae: 0.6749 - rmse: 0.8838 - smape: 1.3065 - val_ia: 0.2447 - val_loss: 0.7586 - val_mae: 0.6467 - val_rmse: 0.7142 - val_smape: 1.2672

Epoch 64/64

1915/1915 - 5s - 3ms/step - ia: 0.3690 - loss: 0.8356 - mae: 0.6722 - rmse: 0.8792 - smape: 1.3076 - val_ia: 0.2432 - val_loss: 0.7561 - val_mae: 0.6445 - val_rmse: 0.7135 - val_smape: 1.2488

Restoring model weights from the end of the best epoch: 55.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 54s 401ms/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 46%|████▌     | 23/50 [1:26:06<2:34:08, 342.52s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 10s - 87ms/step - ia: 0.1969 - loss: 1.0498 - mae: 0.7810 - rmse: 1.0223 - smape: 1.5781 - val_ia: 0.2854 - val_loss: 0.9387 - val_mae: 0.7329 - val_rmse: 0.8948 - val_smape: 1.5583

Epoch 2/32

120/120 - 3s - 23ms/step - ia: 0.2206 - loss: 0.9764 - mae: 0.7357 - rmse: 0.9847 - smape: 1.5443 - val_ia: 0.3006 - val_loss: 0.8997 - val_mae: 0.7068 - val_rmse: 0.8718 - val_smape: 1.5201

Epoch 3/32

120/120 - 1s - 7ms/step - ia: 0.2476 - loss: 0.9448 - mae: 0.7174 - rmse: 0.9690 - smape: 1.5064 - val_ia: 0.3087 - val_loss: 0.8778 - val_mae: 0.6969 - val_rmse: 0.8618 - val_smape: 1.4989

Epoch 4/32

120/120 - 1s - 7ms/step - ia: 0.2667 - loss: 0.9241 - mae: 0.7093 - rmse: 0.9577 - smape: 1.4792 - val_ia: 0.3128 - val_loss: 0.8596 - val_mae: 0.6916 - val_rmse: 0.8551 - val_smape: 1.4800

Epoch 5/32

120/120 - 1s - 10ms/step - ia: 0.2827 - loss: 0.9064 - mae: 0.7045 - rmse: 0.9491 - smape: 1.4596 - val_ia: 0.3156 - val_loss: 0.8454 - val_mae: 0.6878 - val_rmse: 0.8500 - val_smape: 1.4627

Epoch 6/32

120/120 - 0s - 4ms/step - ia: 0.2961 - loss: 0.8911 - mae: 0.7004 - rmse: 0.9413 - smape: 1.4418 - val_ia: 0.3181 - val_loss: 0.8355 - val_mae: 0.6846 - val_rmse: 0.8466 - val_smape: 1.4450

Epoch 7/32

120/120 - 0s - 4ms/step - ia: 0.3095 - loss: 0.8790 - mae: 0.6971 - rmse: 0.9351 - smape: 1.4260 - val_ia: 0.3202 - val_loss: 0.8291 - val_mae: 0.6817 - val_rmse: 0.8439 - val_smape: 1.4296

Epoch 8/32

120/120 - 1s - 4ms/step - ia: 0.3190 - loss: 0.8699 - mae: 0.6936 - rmse: 0.9305 - smape: 1.4122 - val_ia: 0.3218 - val_loss: 0.8255 - val_mae: 0.6801 - val_rmse: 0.8427 - val_smape: 1.4180

Epoch 9/32

120/120 - 1s - 5ms/step - ia: 0.3268 - loss: 0.8628 - mae: 0.6907 - rmse: 0.9263 - smape: 1.4018 - val_ia: 0.3234 - val_loss: 0.8226 - val_mae: 0.6774 - val_rmse: 0.8409 - val_smape: 1.4056

Epoch 10/32

120/120 - 1s - 5ms/step - ia: 0.3327 - loss: 0.8568 - mae: 0.6876 - rmse: 0.9229 - smape: 1.3927 - val_ia: 0.3248 - val_loss: 0.8211 - val_mae: 0.6756 - val_rmse: 0.8399 - val_smape: 1.3959

Epoch 11/32

120/120 - 1s - 4ms/step - ia: 0.3377 - loss: 0.8520 - mae: 0.6856 - rmse: 0.9202 - smape: 1.3844 - val_ia: 0.3257 - val_loss: 0.8195 - val_mae: 0.6737 - val_rmse: 0.8388 - val_smape: 1.3861

Epoch 12/32

120/120 - 1s - 6ms/step - ia: 0.3424 - loss: 0.8477 - mae: 0.6830 - rmse: 0.9182 - smape: 1.3762 - val_ia: 0.3261 - val_loss: 0.8180 - val_mae: 0.6730 - val_rmse: 0.8382 - val_smape: 1.3795

Epoch 13/32

120/120 - 1s - 5ms/step - ia: 0.3455 - loss: 0.8443 - mae: 0.6815 - rmse: 0.9167 - smape: 1.3707 - val_ia: 0.3276 - val_loss: 0.8160 - val_mae: 0.6704 - val_rmse: 0.8366 - val_smape: 1.3691

Epoch 14/32

120/120 - 1s - 5ms/step - ia: 0.3498 - loss: 0.8412 - mae: 0.6794 - rmse: 0.9142 - smape: 1.3636 - val_ia: 0.3280 - val_loss: 0.8141 - val_mae: 0.6687 - val_rmse: 0.8353 - val_smape: 1.3620

Epoch 15/32

120/120 - 1s - 8ms/step - ia: 0.3524 - loss: 0.8383 - mae: 0.6775 - rmse: 0.9130 - smape: 1.3578 - val_ia: 0.3290 - val_loss: 0.8125 - val_mae: 0.6676 - val_rmse: 0.8345 - val_smape: 1.3554

Epoch 16/32

120/120 - 0s - 3ms/step - ia: 0.3543 - loss: 0.8356 - mae: 0.6763 - rmse: 0.9113 - smape: 1.3538 - val_ia: 0.3303 - val_loss: 0.8113 - val_mae: 0.6663 - val_rmse: 0.8339 - val_smape: 1.3498

Epoch 17/32

120/120 - 0s - 3ms/step - ia: 0.3565 - loss: 0.8332 - mae: 0.6748 - rmse: 0.9100 - smape: 1.3490 - val_ia: 0.3315 - val_loss: 0.8097 - val_mae: 0.6652 - val_rmse: 0.8331 - val_smape: 1.3447

Epoch 18/32

120/120 - 0s - 4ms/step - ia: 0.3613 - loss: 0.8308 - mae: 0.6732 - rmse: 0.9086 - smape: 1.3425 - val_ia: 0.3323 - val_loss: 0.8078 - val_mae: 0.6638 - val_rmse: 0.8320 - val_smape: 1.3393

Epoch 19/32

120/120 - 1s - 7ms/step - ia: 0.3623 - loss: 0.8286 - mae: 0.6723 - rmse: 0.9075 - smape: 1.3385 - val_ia: 0.3331 - val_loss: 0.8057 - val_mae: 0.6625 - val_rmse: 0.8308 - val_smape: 1.3340

Epoch 20/32

120/120 - 1s - 6ms/step - ia: 0.3640 - loss: 0.8266 - mae: 0.6708 - rmse: 0.9065 - smape: 1.3336 - val_ia: 0.3339 - val_loss: 0.8046 - val_mae: 0.6621 - val_rmse: 0.8306 - val_smape: 1.3302

Epoch 21/32

120/120 - 1s - 6ms/step - ia: 0.3669 - loss: 0.8247 - mae: 0.6699 - rmse: 0.9059 - smape: 1.3296 - val_ia: 0.3352 - val_loss: 0.8032 - val_mae: 0.6611 - val_rmse: 0.8298 - val_smape: 1.3263

Epoch 22/32

120/120 - 1s - 6ms/step - ia: 0.3697 - loss: 0.8229 - mae: 0.6693 - rmse: 0.9047 - smape: 1.3254 - val_ia: 0.3354 - val_loss: 0.8014 - val_mae: 0.6604 - val_rmse: 0.8290 - val_smape: 1.3231

Epoch 23/32

120/120 - 1s - 12ms/step - ia: 0.3713 - loss: 0.8212 - mae: 0.6676 - rmse: 0.9034 - smape: 1.3212 - val_ia: 0.3361 - val_loss: 0.8005 - val_mae: 0.6603 - val_rmse: 0.8289 - val_smape: 1.3217

Epoch 24/32

120/120 - 1s - 9ms/step - ia: 0.3736 - loss: 0.8195 - mae: 0.6678 - rmse: 0.9023 - smape: 1.3183 - val_ia: 0.3371 - val_loss: 0.7984 - val_mae: 0.6585 - val_rmse: 0.8274 - val_smape: 1.3154

Epoch 25/32

120/120 - 1s - 5ms/step - ia: 0.3757 - loss: 0.8179 - mae: 0.6663 - rmse: 0.9014 - smape: 1.3134 - val_ia: 0.3383 - val_loss: 0.7973 - val_mae: 0.6576 - val_rmse: 0.8269 - val_smape: 1.3111

Epoch 26/32

120/120 - 1s - 5ms/step - ia: 0.3765 - loss: 0.8164 - mae: 0.6652 - rmse: 0.9008 - smape: 1.3108 - val_ia: 0.3384 - val_loss: 0.7964 - val_mae: 0.6579 - val_rmse: 0.8268 - val_smape: 1.3111

Epoch 27/32

120/120 - 1s - 5ms/step - ia: 0.3790 - loss: 0.8149 - mae: 0.6650 - rmse: 0.8994 - smape: 1.3078 - val_ia: 0.3392 - val_loss: 0.7949 - val_mae: 0.6571 - val_rmse: 0.8260 - val_smape: 1.3074

Epoch 28/32

120/120 - 1s - 4ms/step - ia: 0.3797 - loss: 0.8134 - mae: 0.6634 - rmse: 0.8993 - smape: 1.3043 - val_ia: 0.3396 - val_loss: 0.7933 - val_mae: 0.6565 - val_rmse: 0.8253 - val_smape: 1.3050

Epoch 29/32

120/120 - 1s - 5ms/step - ia: 0.3812 - loss: 0.8120 - mae: 0.6634 - rmse: 0.8988 - smape: 1.3022 - val_ia: 0.3410 - val_loss: 0.7926 - val_mae: 0.6558 - val_rmse: 0.8250 - val_smape: 1.3016

Epoch 30/32

120/120 - 1s - 8ms/step - ia: 0.3841 - loss: 0.8107 - mae: 0.6622 - rmse: 0.8974 - smape: 1.2978 - val_ia: 0.3416 - val_loss: 0.7919 - val_mae: 0.6560 - val_rmse: 0.8250 - val_smape: 1.3007

Epoch 31/32

120/120 - 2s - 13ms/step - ia: 0.3849 - loss: 0.8093 - mae: 0.6617 - rmse: 0.8977 - smape: 1.2955 - val_ia: 0.3419 - val_loss: 0.7901 - val_mae: 0.6553 - val_rmse: 0.8241 - val_smape: 1.2985

Epoch 32/32

120/120 - 1s - 12ms/step - ia: 0.3862 - loss: 0.8080 - mae: 0.6610 - rmse: 0.8967 - smape: 1.2933 - val_ia: 0.3425 - val_loss: 0.7888 - val_mae: 0.6544 - val_rmse: 0.8232 - val_smape: 1.2947

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:34 700ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 48%|████▊     | 24/50 [1:26:46<1:49:11, 251.99s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 10s - 81ms/step - ia: 0.3694 - loss: 0.9495 - mae: 0.7359 - rmse: 0.9693 - smape: 1.3276 - val_ia: 0.3432 - val_loss: 0.7642 - val_mae: 0.6476 - val_rmse: 0.8086 - val_smape: 1.2772

Epoch 2/32

120/120 - 2s - 14ms/step - ia: 0.3961 - loss: 0.8473 - mae: 0.6800 - rmse: 0.9180 - smape: 1.2780 - val_ia: 0.3458 - val_loss: 0.7727 - val_mae: 0.6544 - val_rmse: 0.8162 - val_smape: 1.2788

Epoch 3/32

120/120 - 2s - 13ms/step - ia: 0.3911 - loss: 0.8355 - mae: 0.6727 - rmse: 0.9119 - smape: 1.2785 - val_ia: 0.3373 - val_loss: 0.7597 - val_mae: 0.6464 - val_rmse: 0.8044 - val_smape: 1.2658

Epoch 4/32

120/120 - 1s - 12ms/step - ia: 0.3942 - loss: 0.8217 - mae: 0.6667 - rmse: 0.9037 - smape: 1.2726 - val_ia: 0.3350 - val_loss: 0.7566 - val_mae: 0.6430 - val_rmse: 0.8012 - val_smape: 1.2626

Epoch 5/32

120/120 - 2s - 14ms/step - ia: 0.3917 - loss: 0.8235 - mae: 0.6670 - rmse: 0.9054 - smape: 1.2721 - val_ia: 0.3416 - val_loss: 0.7598 - val_mae: 0.6431 - val_rmse: 0.8036 - val_smape: 1.2538

Epoch 6/32

120/120 - 3s - 23ms/step - ia: 0.3952 - loss: 0.8170 - mae: 0.6638 - rmse: 0.9008 - smape: 1.2669 - val_ia: 0.3402 - val_loss: 0.7606 - val_mae: 0.6453 - val_rmse: 0.8047 - val_smape: 1.2685

Epoch 7/32

120/120 - 2s - 13ms/step - ia: 0.3986 - loss: 0.8131 - mae: 0.6602 - rmse: 0.8997 - smape: 1.2629 - val_ia: 0.3365 - val_loss: 0.7622 - val_mae: 0.6480 - val_rmse: 0.8065 - val_smape: 1.2720

Epoch 8/32

120/120 - 1s - 11ms/step - ia: 0.4024 - loss: 0.8102 - mae: 0.6598 - rmse: 0.8973 - smape: 1.2574 - val_ia: 0.3482 - val_loss: 0.7666 - val_mae: 0.6473 - val_rmse: 0.8103 - val_smape: 1.2686

Epoch 9/32

120/120 - 2s - 14ms/step - ia: 0.4007 - loss: 0.8084 - mae: 0.6594 - rmse: 0.8966 - smape: 1.2612 - val_ia: 0.3447 - val_loss: 0.7560 - val_mae: 0.6428 - val_rmse: 0.8031 - val_smape: 1.2484

Epoch 10/32

120/120 - 1s - 12ms/step - ia: 0.4041 - loss: 0.8077 - mae: 0.6572 - rmse: 0.8956 - smape: 1.2531 - val_ia: 0.3507 - val_loss: 0.7591 - val_mae: 0.6454 - val_rmse: 0.8071 - val_smape: 1.2528

Epoch 11/32

120/120 - 3s - 21ms/step - ia: 0.4038 - loss: 0.8050 - mae: 0.6575 - rmse: 0.8946 - smape: 1.2556 - val_ia: 0.3502 - val_loss: 0.7589 - val_mae: 0.6434 - val_rmse: 0.8061 - val_smape: 1.2434

Epoch 12/32

120/120 - 1s - 5ms/step - ia: 0.4086 - loss: 0.8015 - mae: 0.6550 - rmse: 0.8930 - smape: 1.2465 - val_ia: 0.3479 - val_loss: 0.7509 - val_mae: 0.6392 - val_rmse: 0.8005 - val_smape: 1.2507

Epoch 13/32

120/120 - 1s - 7ms/step - ia: 0.4110 - loss: 0.7971 - mae: 0.6531 - rmse: 0.8908 - smape: 1.2465 - val_ia: 0.3458 - val_loss: 0.7497 - val_mae: 0.6410 - val_rmse: 0.8010 - val_smape: 1.2579

Epoch 14/32

120/120 - 0s - 3ms/step - ia: 0.4113 - loss: 0.7976 - mae: 0.6530 - rmse: 0.8910 - smape: 1.2449 - val_ia: 0.3526 - val_loss: 0.7611 - val_mae: 0.6458 - val_rmse: 0.8096 - val_smape: 1.2575

Epoch 15/32

120/120 - 1s - 6ms/step - ia: 0.4132 - loss: 0.7932 - mae: 0.6505 - rmse: 0.8884 - smape: 1.2417 - val_ia: 0.3643 - val_loss: 0.7559 - val_mae: 0.6413 - val_rmse: 0.8072 - val_smape: 1.2318

Epoch 16/32

120/120 - 1s - 6ms/step - ia: 0.4138 - loss: 0.7931 - mae: 0.6513 - rmse: 0.8878 - smape: 1.2402 - val_ia: 0.3524 - val_loss: 0.7491 - val_mae: 0.6421 - val_rmse: 0.8032 - val_smape: 1.2558

Epoch 17/32

120/120 - 0s - 4ms/step - ia: 0.4143 - loss: 0.7905 - mae: 0.6508 - rmse: 0.8871 - smape: 1.2397 - val_ia: 0.3569 - val_loss: 0.7537 - val_mae: 0.6451 - val_rmse: 0.8079 - val_smape: 1.2592

Epoch 18/32

120/120 - 1s - 7ms/step - ia: 0.4154 - loss: 0.7905 - mae: 0.6502 - rmse: 0.8866 - smape: 1.2388 - val_ia: 0.3605 - val_loss: 0.7496 - val_mae: 0.6421 - val_rmse: 0.8051 - val_smape: 1.2585

Epoch 19/32

120/120 - 1s - 4ms/step - ia: 0.4128 - loss: 0.7891 - mae: 0.6502 - rmse: 0.8859 - smape: 1.2416 - val_ia: 0.3560 - val_loss: 0.7462 - val_mae: 0.6389 - val_rmse: 0.8008 - val_smape: 1.2539

Epoch 20/32

120/120 - 1s - 6ms/step - ia: 0.4153 - loss: 0.7891 - mae: 0.6487 - rmse: 0.8859 - smape: 1.2395 - val_ia: 0.3502 - val_loss: 0.7508 - val_mae: 0.6474 - val_rmse: 0.8068 - val_smape: 1.2679

Epoch 21/32

120/120 - 1s - 6ms/step - ia: 0.4177 - loss: 0.7884 - mae: 0.6492 - rmse: 0.8853 - smape: 1.2357 - val_ia: 0.3578 - val_loss: 0.7416 - val_mae: 0.6380 - val_rmse: 0.7998 - val_smape: 1.2542

Epoch 22/32

120/120 - 1s - 6ms/step - ia: 0.4179 - loss: 0.7850 - mae: 0.6470 - rmse: 0.8836 - smape: 1.2339 - val_ia: 0.3607 - val_loss: 0.7417 - val_mae: 0.6355 - val_rmse: 0.7993 - val_smape: 1.2355

Epoch 23/32

120/120 - 1s - 6ms/step - ia: 0.4183 - loss: 0.7849 - mae: 0.6477 - rmse: 0.8837 - smape: 1.2344 - val_ia: 0.3609 - val_loss: 0.7464 - val_mae: 0.6433 - val_rmse: 0.8052 - val_smape: 1.2625

Epoch 24/32

120/120 - 1s - 5ms/step - ia: 0.4203 - loss: 0.7832 - mae: 0.6465 - rmse: 0.8828 - smape: 1.2309 - val_ia: 0.3576 - val_loss: 0.7499 - val_mae: 0.6388 - val_rmse: 0.8025 - val_smape: 1.2575

Epoch 25/32

120/120 - 1s - 5ms/step - ia: 0.4170 - loss: 0.7823 - mae: 0.6473 - rmse: 0.8820 - smape: 1.2399 - val_ia: 0.3615 - val_loss: 0.7451 - val_mae: 0.6379 - val_rmse: 0.8017 - val_smape: 1.2487

Epoch 26/32

120/120 - 1s - 5ms/step - ia: 0.4211 - loss: 0.7818 - mae: 0.6458 - rmse: 0.8818 - smape: 1.2324 - val_ia: 0.3566 - val_loss: 0.7473 - val_mae: 0.6415 - val_rmse: 0.8035 - val_smape: 1.2779

Epoch 27/32

120/120 - 1s - 5ms/step - ia: 0.4195 - loss: 0.7809 - mae: 0.6465 - rmse: 0.8805 - smape: 1.2356 - val_ia: 0.3686 - val_loss: 0.7368 - val_mae: 0.6305 - val_rmse: 0.7959 - val_smape: 1.2270

Epoch 28/32

120/120 - 1s - 6ms/step - ia: 0.4221 - loss: 0.7808 - mae: 0.6456 - rmse: 0.8809 - smape: 1.2319 - val_ia: 0.3643 - val_loss: 0.7480 - val_mae: 0.6381 - val_rmse: 0.8032 - val_smape: 1.2582

Epoch 29/32

120/120 - 1s - 4ms/step - ia: 0.4186 - loss: 0.7800 - mae: 0.6458 - rmse: 0.8813 - smape: 1.2379 - val_ia: 0.3586 - val_loss: 0.7459 - val_mae: 0.6396 - val_rmse: 0.8032 - val_smape: 1.2557

Epoch 30/32

120/120 - 1s - 6ms/step - ia: 0.4199 - loss: 0.7791 - mae: 0.6468 - rmse: 0.8802 - smape: 1.2373 - val_ia: 0.3657 - val_loss: 0.7367 - val_mae: 0.6314 - val_rmse: 0.7958 - val_smape: 1.2465

Epoch 31/32

120/120 - 1s - 5ms/step - ia: 0.4212 - loss: 0.7784 - mae: 0.6441 - rmse: 0.8799 - smape: 1.2329 - val_ia: 0.3659 - val_loss: 0.7368 - val_mae: 0.6310 - val_rmse: 0.7963 - val_smape: 1.2337

Epoch 32/32

120/120 - 1s - 5ms/step - ia: 0.4213 - loss: 0.7779 - mae: 0.6443 - rmse: 0.8801 - smape: 1.2336 - val_ia: 0.3624 - val_loss: 0.7477 - val_mae: 0.6429 - val_rmse: 0.8061 - val_smape: 1.2632

Restoring model weights from the end of the best epoch: 30.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 216ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 50%|█████     | 25/50 [1:27:30<1:18:54, 189.38s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 22s - 6ms/step - ia: 0.3397 - loss: 0.9422 - mae: 0.7180 - rmse: 0.9069 - smape: 1.3517 - val_ia: 0.1975 - val_loss: 0.7878 - val_mae: 0.6670 - val_rmse: 0.7067 - val_smape: 1.3009

Epoch 2/128

3830/3830 - 22s - 6ms/step - ia: 0.3689 - loss: 0.8432 - mae: 0.6775 - rmse: 0.8593 - smape: 1.2906 - val_ia: 0.1994 - val_loss: 0.7677 - val_mae: 0.6556 - val_rmse: 0.6955 - val_smape: 1.3126

Epoch 3/128

3830/3830 - 37s - 10ms/step - ia: 0.3810 - loss: 0.8192 - mae: 0.6664 - rmse: 0.8479 - smape: 1.2862 - val_ia: 0.2028 - val_loss: 0.7442 - val_mae: 0.6347 - val_rmse: 0.6756 - val_smape: 1.2777

Epoch 4/128

3830/3830 - 13s - 3ms/step - ia: 0.3831 - loss: 0.8128 - mae: 0.6634 - rmse: 0.8441 - smape: 1.2911 - val_ia: 0.2032 - val_loss: 0.7611 - val_mae: 0.6402 - val_rmse: 0.6831 - val_smape: 1.2504

Epoch 5/128

3830/3830 - 12s - 3ms/step - ia: 0.3855 - loss: 0.8062 - mae: 0.6609 - rmse: 0.8421 - smape: 1.2862 - val_ia: 0.2048 - val_loss: 0.7607 - val_mae: 0.6372 - val_rmse: 0.6802 - val_smape: 1.2362

Epoch 6/128

3830/3830 - 18s - 5ms/step - ia: 0.3919 - loss: 0.7998 - mae: 0.6575 - rmse: 0.8373 - smape: 1.2835 - val_ia: 0.2017 - val_loss: 0.7619 - val_mae: 0.6481 - val_rmse: 0.6901 - val_smape: 1.3133

Epoch 7/128

3830/3830 - 18s - 5ms/step - ia: 0.3919 - loss: 0.7958 - mae: 0.6558 - rmse: 0.8356 - smape: 1.2766 - val_ia: 0.2044 - val_loss: 0.7516 - val_mae: 0.6380 - val_rmse: 0.6801 - val_smape: 1.2621

Epoch 8/128

3830/3830 - 26s - 7ms/step - ia: 0.3958 - loss: 0.7908 - mae: 0.6531 - rmse: 0.8329 - smape: 1.2711 - val_ia: 0.2044 - val_loss: 0.7532 - val_mae: 0.6374 - val_rmse: 0.6791 - val_smape: 1.2760

Epoch 9/128

3830/3830 - 14s - 4ms/step - ia: 0.3965 - loss: 0.7873 - mae: 0.6520 - rmse: 0.8307 - smape: 1.2708 - val_ia: 0.2071 - val_loss: 0.7613 - val_mae: 0.6333 - val_rmse: 0.6771 - val_smape: 1.2276

Epoch 10/128

3830/3830 - 19s - 5ms/step - ia: 0.3992 - loss: 0.7826 - mae: 0.6502 - rmse: 0.8290 - smape: 1.2612 - val_ia: 0.2066 - val_loss: 0.7642 - val_mae: 0.6373 - val_rmse: 0.6812 - val_smape: 1.2603

Epoch 11/128

3830/3830 - 17s - 4ms/step - ia: 0.4016 - loss: 0.7793 - mae: 0.6483 - rmse: 0.8272 - smape: 1.2599 - val_ia: 0.2069 - val_loss: 0.7609 - val_mae: 0.6390 - val_rmse: 0.6832 - val_smape: 1.2612

Epoch 12/128

3830/3830 - 25s - 7ms/step - ia: 0.4039 - loss: 0.7769 - mae: 0.6478 - rmse: 0.8259 - smape: 1.2608 - val_ia: 0.2063 - val_loss: 0.7590 - val_mae: 0.6373 - val_rmse: 0.6808 - val_smape: 1.2591

Epoch 13/128

3830/3830 - 40s - 10ms/step - ia: 0.4026 - loss: 0.7779 - mae: 0.6478 - rmse: 0.8271 - smape: 1.2581 - val_ia: 0.2054 - val_loss: 0.7545 - val_mae: 0.6380 - val_rmse: 0.6809 - val_smape: 1.2624

Epoch 14/128

3830/3830 - 17s - 5ms/step - ia: 0.4063 - loss: 0.7718 - mae: 0.6446 - rmse: 0.8222 - smape: 1.2561 - val_ia: 0.2034 - val_loss: 0.7629 - val_mae: 0.6488 - val_rmse: 0.6914 - val_smape: 1.3018

Epoch 15/128

3830/3830 - 19s - 5ms/step - ia: 0.4076 - loss: 0.7705 - mae: 0.6435 - rmse: 0.8216 - smape: 1.2511 - val_ia: 0.2044 - val_loss: 0.7595 - val_mae: 0.6431 - val_rmse: 0.6859 - val_smape: 1.2873

Epoch 16/128

3830/3830 - 20s - 5ms/step - ia: 0.4055 - loss: 0.7693 - mae: 0.6421 - rmse: 0.8218 - smape: 1.2552 - val_ia: 0.2054 - val_loss: 0.7562 - val_mae: 0.6381 - val_rmse: 0.6813 - val_smape: 1.2583

Epoch 17/128

3830/3830 - 18s - 5ms/step - ia: 0.4093 - loss: 0.7652 - mae: 0.6413 - rmse: 0.8182 - smape: 1.2468 - val_ia: 0.2072 - val_loss: 0.7542 - val_mae: 0.6305 - val_rmse: 0.6744 - val_smape: 1.2259

Epoch 18/128

3830/3830 - 17s - 5ms/step - ia: 0.4129 - loss: 0.7617 - mae: 0.6400 - rmse: 0.8184 - smape: 1.2396 - val_ia: 0.2049 - val_loss: 0.7565 - val_mae: 0.6395 - val_rmse: 0.6824 - val_smape: 1.2577

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:05 933ms/step
  3/136 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 52%|█████▏    | 26/50 [1:33:48<1:38:23, 245.96s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 8s - 70ms/step - ia: 0.2168 - loss: 1.6263 - mae: 0.9145 - rmse: 1.2672 - smape: 1.6203 - val_ia: 0.2377 - val_loss: 0.9472 - val_mae: 0.7237 - val_rmse: 0.8899 - val_smape: 1.6060

Epoch 2/32

120/120 - 1s - 8ms/step - ia: 0.2135 - loss: 1.3113 - mae: 0.8352 - rmse: 1.1419 - smape: 1.6045 - val_ia: 0.2385 - val_loss: 0.9419 - val_mae: 0.7187 - val_rmse: 0.8830 - val_smape: 1.6299

Epoch 3/32

120/120 - 1s - 11ms/step - ia: 0.2015 - loss: 1.1840 - mae: 0.8011 - rmse: 1.0849 - smape: 1.6175 - val_ia: 0.2423 - val_loss: 0.9454 - val_mae: 0.7204 - val_rmse: 0.8842 - val_smape: 1.6701

Epoch 4/32

120/120 - 1s - 9ms/step - ia: 0.1902 - loss: 1.1231 - mae: 0.7816 - rmse: 1.0569 - smape: 1.6369 - val_ia: 0.2440 - val_loss: 0.9462 - val_mae: 0.7216 - val_rmse: 0.8845 - val_smape: 1.7007

Epoch 5/32

120/120 - 1s - 10ms/step - ia: 0.1765 - loss: 1.0882 - mae: 0.7722 - rmse: 1.0411 - smape: 1.6659 - val_ia: 0.2457 - val_loss: 0.9480 - val_mae: 0.7233 - val_rmse: 0.8858 - val_smape: 1.7343

Epoch 6/32

120/120 - 1s - 12ms/step - ia: 0.1656 - loss: 1.0641 - mae: 0.7660 - rmse: 1.0288 - smape: 1.6927 - val_ia: 0.2468 - val_loss: 0.9497 - val_mae: 0.7249 - val_rmse: 0.8871 - val_smape: 1.7660

Epoch 7/32

120/120 - 1s - 10ms/step - ia: 0.1572 - loss: 1.0445 - mae: 0.7603 - rmse: 1.0188 - smape: 1.7143 - val_ia: 0.2478 - val_loss: 0.9524 - val_mae: 0.7265 - val_rmse: 0.8886 - val_smape: 1.7943

Epoch 8/32

120/120 - 1s - 7ms/step - ia: 0.1454 - loss: 1.0405 - mae: 0.7592 - rmse: 1.0160 - smape: 1.7382 - val_ia: 0.2488 - val_loss: 0.9540 - val_mae: 0.7281 - val_rmse: 0.8899 - val_smape: 1.8237

Epoch 9/32

120/120 - 1s - 11ms/step - ia: 0.1406 - loss: 1.0292 - mae: 0.7573 - rmse: 1.0106 - smape: 1.7532 - val_ia: 0.2495 - val_loss: 0.9540 - val_mae: 0.7287 - val_rmse: 0.8902 - val_smape: 1.8394

Epoch 10/32

120/120 - 1s - 9ms/step - ia: 0.1357 - loss: 1.0235 - mae: 0.7550 - rmse: 1.0092 - smape: 1.7634 - val_ia: 0.2498 - val_loss: 0.9544 - val_mae: 0.7296 - val_rmse: 0.8907 - val_smape: 1.8565

Epoch 11/32

120/120 - 1s - 11ms/step - ia: 0.1309 - loss: 1.0165 - mae: 0.7545 - rmse: 1.0046 - smape: 1.7786 - val_ia: 0.2503 - val_loss: 0.9546 - val_mae: 0.7301 - val_rmse: 0.8910 - val_smape: 1.8666

Epoch 12/32

120/120 - 1s - 12ms/step - ia: 0.1259 - loss: 1.0134 - mae: 0.7533 - rmse: 1.0037 - smape: 1.7849 - val_ia: 0.2506 - val_loss: 0.9552 - val_mae: 0.7303 - val_rmse: 0.8912 - val_smape: 1.8756

Epoch 13/32

120/120 - 1s - 8ms/step - ia: 0.1198 - loss: 1.0080 - mae: 0.7505 - rmse: 1.0015 - smape: 1.7901 - val_ia: 0.2507 - val_loss: 0.9548 - val_mae: 0.7307 - val_rmse: 0.8913 - val_smape: 1.8847

Epoch 14/32

120/120 - 1s - 5ms/step - ia: 0.1211 - loss: 1.0018 - mae: 0.7493 - rmse: 0.9983 - smape: 1.7949 - val_ia: 0.2513 - val_loss: 0.9535 - val_mae: 0.7303 - val_rmse: 0.8907 - val_smape: 1.8875

Epoch 15/32

120/120 - 1s - 11ms/step - ia: 0.1267 - loss: 0.9961 - mae: 0.7469 - rmse: 0.9947 - smape: 1.7981 - val_ia: 0.2512 - val_loss: 0.9501 - val_mae: 0.7299 - val_rmse: 0.8896 - val_smape: 1.8881

Epoch 16/32

120/120 - 1s - 9ms/step - ia: 0.1261 - loss: 0.9922 - mae: 0.7460 - rmse: 0.9934 - smape: 1.7993 - val_ia: 0.2514 - val_loss: 0.9468 - val_mae: 0.7290 - val_rmse: 0.8883 - val_smape: 1.8854

Epoch 17/32

120/120 - 1s - 9ms/step - ia: 0.1227 - loss: 0.9958 - mae: 0.7468 - rmse: 0.9949 - smape: 1.8050 - val_ia: 0.2518 - val_loss: 0.9455 - val_mae: 0.7285 - val_rmse: 0.8877 - val_smape: 1.8858

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 17s 127ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

Epoch 1/64

 54%|█████▍    | 27/50 [1:34:17<1:09:19, 180.84s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

1915/1915 - 18s - 9ms/step - ia: 0.3695 - loss: 0.8520 - mae: 0.6784 - rmse: 0.8892 - smape: 1.3381 - val_ia: 0.2451 - val_loss: 0.7612 - val_mae: 0.6506 - val_rmse: 0.7190 - val_smape: 1.3288

Epoch 2/64

1915/1915 - 8s - 4ms/step - ia: 0.3836 - loss: 0.8181 - mae: 0.6637 - rmse: 0.8693 - smape: 1.3299 - val_ia: 0.2423 - val_loss: 0.7741 - val_mae: 0.6568 - val_rmse: 0.7246 - val_smape: 1.3414

Epoch 3/64

1915/1915 - 7s - 4ms/step - ia: 0.3812 - loss: 0.8167 - mae: 0.6652 - rmse: 0.8704 - smape: 1.3277 - val_ia: 0.2495 - val_loss: 0.7560 - val_mae: 0.6339 - val_rmse: 0.7056 - val_smape: 1.2641

Epoch 4/64

1915/1915 - 12s - 6ms/step - ia: 0.3872 - loss: 0.8103 - mae: 0.6611 - rmse: 0.8671 - smape: 1.3263 - val_ia: 0.2309 - val_loss: 0.7980 - val_mae: 0.6874 - val_rmse: 0.7538 - val_smape: 1.4595

Epoch 5/64

1915/1915 - 10s - 5ms/step - ia: 0.3922 - loss: 0.8014 - mae: 0.6571 - rmse: 0.8616 - smape: 1.3165 - val_ia: 0.2494 - val_loss: 0.7668 - val_mae: 0.6383 - val_rmse: 0.7073 - val_smape: 1.2690

Epoch 6/64

1915/1915 - 10s - 5ms/step - ia: 0.3904 - loss: 0.7984 - mae: 0.6570 - rmse: 0.8598 - smape: 1.3268 - val_ia: 0.2460 - val_loss: 0.7743 - val_mae: 0.6367 - val_rmse: 0.7042 - val_smape: 1.2812

Epoch 7/64

1915/1915 - 17s - 9ms/step - ia: 0.3943 - loss: 0.7940 - mae: 0.6553 - rmse: 0.8575 - smape: 1.3215 - val_ia: 0.2594 - val_loss: 0.7885 - val_mae: 0.6313 - val_rmse: 0.7079 - val_smape: 1.1550

Epoch 8/64

1915/1915 - 22s - 12ms/step - ia: 0.3976 - loss: 0.7828 - mae: 0.6500 - rmse: 0.8518 - smape: 1.3146 - val_ia: 0.2370 - val_loss: 0.8878 - val_mae: 0.6801 - val_rmse: 0.7574 - val_smape: 1.3644

Epoch 9/64

1915/1915 - 11s - 6ms/step - ia: 0.3980 - loss: 0.7809 - mae: 0.6500 - rmse: 0.8503 - smape: 1.3198 - val_ia: 0.2409 - val_loss: 0.8710 - val_mae: 0.6785 - val_rmse: 0.7532 - val_smape: 1.3581

Epoch 10/64

1915/1915 - 18s - 9ms/step - ia: 0.4017 - loss: 0.7721 - mae: 0.6473 - rmse: 0.8461 - smape: 1.3270 - val_ia: 0.2471 - val_loss: 0.7788 - val_mae: 0.6421 - val_rmse: 0.7155 - val_smape: 1.3172

Epoch 11/64

1915/1915 - 8s - 4ms/step - ia: 0.4017 - loss: 0.7731 - mae: 0.6457 - rmse: 0.8455 - smape: 1.3314 - val_ia: 0.2246 - val_loss: 0.8650 - val_mae: 0.7298 - val_rmse: 0.7939 - val_smape: 1.5935

Epoch 12/64

1915/1915 - 6s - 3ms/step - ia: 0.4016 - loss: 0.7710 - mae: 0.6463 - rmse: 0.8454 - smape: 1.3274 - val_ia: 0.2486 - val_loss: 0.7890 - val_mae: 0.6473 - val_rmse: 0.7177 - val_smape: 1.3134

Epoch 13/64

1915/1915 - 6s - 3ms/step - ia: 0.4057 - loss: 0.7630 - mae: 0.6419 - rmse: 0.8409 - smape: 1.3161 - val_ia: 0.2585 - val_loss: 0.8339 - val_mae: 0.6455 - val_rmse: 0.7298 - val_smape: 1.2262

Epoch 14/64

1915/1915 - 7s - 4ms/step - ia: 0.4042 - loss: 0.7666 - mae: 0.6447 - rmse: 0.8437 - smape: 1.3350 - val_ia: 0.2574 - val_loss: 0.8054 - val_mae: 0.6363 - val_rmse: 0.7123 - val_smape: 1.2716

Epoch 15/64

1915/1915 - 9s - 5ms/step - ia: 0.4075 - loss: 0.7595 - mae: 0.6404 - rmse: 0.8391 - smape: 1.3145 - val_ia: 0.2368 - val_loss: 0.8299 - val_mae: 0.6744 - val_rmse: 0.7468 - val_smape: 1.3845

Epoch 16/64

1915/1915 - 7s - 4ms/step - ia: 0.4049 - loss: 0.7552 - mae: 0.6420 - rmse: 0.8372 - smape: 1.3301 - val_ia: 0.2442 - val_loss: 0.8511 - val_mae: 0.6773 - val_rmse: 0.7503 - val_smape: 1.3891

Epoch 17/64

1915/1915 - 8s - 4ms/step - ia: 0.4068 - loss: 0.7524 - mae: 0.6392 - rmse: 0.8351 - smape: 1.3350 - val_ia: 0.2303 - val_loss: 0.8615 - val_mae: 0.7129 - val_rmse: 0.7826 - val_smape: 1.5958

Epoch 18/64

1915/1915 - 9s - 5ms/step - ia: 0.4044 - loss: 0.7608 - mae: 0.6422 - rmse: 0.8412 - smape: 1.3326 - val_ia: 0.2528 - val_loss: 0.8181 - val_mae: 0.6505 - val_rmse: 0.7280 - val_smape: 1.2794

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 42s 318ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
119/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 56%|█████▌    | 28/50 [1:37:33<1:08:00, 185.47s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 54s - 14ms/step - ia: 0.2703 - loss: 1.1651 - mae: 0.8202 - rmse: 1.0189 - smape: 1.5038 - val_ia: 0.1860 - val_loss: 0.9634 - val_mae: 0.7354 - val_rmse: 0.7714 - val_smape: 1.9634

Epoch 2/128

3830/3830 - 13s - 3ms/step - ia: 0.2646 - loss: 1.1095 - mae: 0.7929 - rmse: 0.9890 - smape: 1.5180 - val_ia: 0.1871 - val_loss: 0.9572 - val_mae: 0.7302 - val_rmse: 0.7663 - val_smape: 1.8899

Epoch 3/128

3830/3830 - 22s - 6ms/step - ia: 0.2547 - loss: 1.0795 - mae: 0.7798 - rmse: 0.9722 - smape: 1.5476 - val_ia: 0.1869 - val_loss: 0.9519 - val_mae: 0.7304 - val_rmse: 0.7665 - val_smape: 1.8862

Epoch 4/128

3830/3830 - 15s - 4ms/step - ia: 0.2516 - loss: 1.0459 - mae: 0.7696 - rmse: 0.9574 - smape: 1.5700 - val_ia: 0.1876 - val_loss: 0.9439 - val_mae: 0.7265 - val_rmse: 0.7625 - val_smape: 1.8322

Epoch 5/128

3830/3830 - 20s - 5ms/step - ia: 0.2519 - loss: 1.0230 - mae: 0.7587 - rmse: 0.9458 - smape: 1.5732 - val_ia: 0.1885 - val_loss: 0.9336 - val_mae: 0.7201 - val_rmse: 0.7563 - val_smape: 1.7603

Epoch 6/128

3830/3830 - 12s - 3ms/step - ia: 0.2502 - loss: 1.0077 - mae: 0.7522 - rmse: 0.9379 - smape: 1.5774 - val_ia: 0.1887 - val_loss: 0.9229 - val_mae: 0.7183 - val_rmse: 0.7544 - val_smape: 1.7248

Epoch 7/128

3830/3830 - 17s - 4ms/step - ia: 0.2546 - loss: 0.9955 - mae: 0.7488 - rmse: 0.9318 - smape: 1.5808 - val_ia: 0.1899 - val_loss: 0.9095 - val_mae: 0.7109 - val_rmse: 0.7471 - val_smape: 1.6528

Epoch 8/128

3830/3830 - 24s - 6ms/step - ia: 0.2625 - loss: 0.9717 - mae: 0.7368 - rmse: 0.9207 - smape: 1.5515 - val_ia: 0.1908 - val_loss: 0.8957 - val_mae: 0.7062 - val_rmse: 0.7426 - val_smape: 1.5964

Epoch 9/128

3830/3830 - 16s - 4ms/step - ia: 0.2684 - loss: 0.9599 - mae: 0.7329 - rmse: 0.9152 - smape: 1.5320 - val_ia: 0.1912 - val_loss: 0.8807 - val_mae: 0.6997 - val_rmse: 0.7363 - val_smape: 1.5356

Epoch 10/128

3830/3830 - 21s - 5ms/step - ia: 0.2758 - loss: 0.9546 - mae: 0.7303 - rmse: 0.9125 - smape: 1.5124 - val_ia: 0.1926 - val_loss: 0.8670 - val_mae: 0.6918 - val_rmse: 0.7287 - val_smape: 1.4754

Epoch 11/128

3830/3830 - 19s - 5ms/step - ia: 0.2836 - loss: 0.9432 - mae: 0.7255 - rmse: 0.9081 - smape: 1.4859 - val_ia: 0.1928 - val_loss: 0.8561 - val_mae: 0.6882 - val_rmse: 0.7253 - val_smape: 1.4387

Epoch 12/128

3830/3830 - 19s - 5ms/step - ia: 0.2940 - loss: 0.9387 - mae: 0.7220 - rmse: 0.9056 - smape: 1.4637 - val_ia: 0.1943 - val_loss: 0.8478 - val_mae: 0.6819 - val_rmse: 0.7194 - val_smape: 1.3963

Epoch 13/128

3830/3830 - 21s - 5ms/step - ia: 0.3003 - loss: 0.9271 - mae: 0.7172 - rmse: 0.8991 - smape: 1.4388 - val_ia: 0.1954 - val_loss: 0.8393 - val_mae: 0.6795 - val_rmse: 0.7173 - val_smape: 1.3718

Epoch 14/128

3830/3830 - 13s - 3ms/step - ia: 0.3048 - loss: 0.9256 - mae: 0.7156 - rmse: 0.8995 - smape: 1.4262 - val_ia: 0.1959 - val_loss: 0.8339 - val_mae: 0.6781 - val_rmse: 0.7161 - val_smape: 1.3560

Epoch 15/128

3830/3830 - 19s - 5ms/step - ia: 0.3074 - loss: 0.9219 - mae: 0.7148 - rmse: 0.8985 - smape: 1.4184 - val_ia: 0.1968 - val_loss: 0.8286 - val_mae: 0.6746 - val_rmse: 0.7128 - val_smape: 1.3351

Epoch 16/128

3830/3830 - 16s - 4ms/step - ia: 0.3132 - loss: 0.9165 - mae: 0.7115 - rmse: 0.8939 - smape: 1.4024 - val_ia: 0.1967 - val_loss: 0.8235 - val_mae: 0.6744 - val_rmse: 0.7128 - val_smape: 1.3284

Epoch 17/128

3830/3830 - 14s - 4ms/step - ia: 0.3138 - loss: 0.9191 - mae: 0.7122 - rmse: 0.8959 - smape: 1.3968 - val_ia: 0.1974 - val_loss: 0.8218 - val_mae: 0.6718 - val_rmse: 0.7104 - val_smape: 1.3164

Epoch 18/128

3830/3830 - 17s - 4ms/step - ia: 0.3168 - loss: 0.9077 - mae: 0.7075 - rmse: 0.8915 - smape: 1.3866 - val_ia: 0.1979 - val_loss: 0.8172 - val_mae: 0.6702 - val_rmse: 0.7090 - val_smape: 1.3048

Epoch 19/128

3830/3830 - 19s - 5ms/step - ia: 0.3228 - loss: 0.8989 - mae: 0.7038 - rmse: 0.8867 - smape: 1.3767 - val_ia: 0.1985 - val_loss: 0.8124 - val_mae: 0.6678 - val_rmse: 0.7068 - val_smape: 1.2903

Epoch 20/128

3830/3830 - 18s - 5ms/step - ia: 0.3272 - loss: 0.8998 - mae: 0.7029 - rmse: 0.8866 - smape: 1.3655 - val_ia: 0.1992 - val_loss: 0.8099 - val_mae: 0.6661 - val_rmse: 0.7052 - val_smape: 1.2819

Epoch 21/128

3830/3830 - 20s - 5ms/step - ia: 0.3239 - loss: 0.9013 - mae: 0.7045 - rmse: 0.8868 - smape: 1.3675 - val_ia: 0.1986 - val_loss: 0.8087 - val_mae: 0.6672 - val_rmse: 0.7064 - val_smape: 1.2847

Epoch 22/128

3830/3830 - 8s - 2ms/step - ia: 0.3280 - loss: 0.8924 - mae: 0.7012 - rmse: 0.8849 - smape: 1.3570 - val_ia: 0.1990 - val_loss: 0.8057 - val_mae: 0.6661 - val_rmse: 0.7054 - val_smape: 1.2780

Epoch 23/128

3830/3830 - 20s - 5ms/step - ia: 0.3301 - loss: 0.8952 - mae: 0.7020 - rmse: 0.8848 - smape: 1.3573 - val_ia: 0.2003 - val_loss: 0.8039 - val_mae: 0.6624 - val_rmse: 0.7018 - val_smape: 1.2648

Epoch 24/128

3830/3830 - 14s - 4ms/step - ia: 0.3302 - loss: 0.8911 - mae: 0.6998 - rmse: 0.8828 - smape: 1.3496 - val_ia: 0.1994 - val_loss: 0.8030 - val_mae: 0.6645 - val_rmse: 0.7040 - val_smape: 1.2695

Epoch 25/128

3830/3830 - 18s - 5ms/step - ia: 0.3295 - loss: 0.8904 - mae: 0.7009 - rmse: 0.8825 - smape: 1.3517 - val_ia: 0.1994 - val_loss: 0.8015 - val_mae: 0.6643 - val_rmse: 0.7038 - val_smape: 1.2681

Epoch 26/128

3830/3830 - 13s - 3ms/step - ia: 0.3307 - loss: 0.8884 - mae: 0.6993 - rmse: 0.8814 - smape: 1.3476 - val_ia: 0.1997 - val_loss: 0.8000 - val_mae: 0.6629 - val_rmse: 0.7025 - val_smape: 1.2621

Epoch 27/128

3830/3830 - 10s - 3ms/step - ia: 0.3348 - loss: 0.8857 - mae: 0.6981 - rmse: 0.8812 - smape: 1.3418 - val_ia: 0.1997 - val_loss: 0.7994 - val_mae: 0.6628 - val_rmse: 0.7024 - val_smape: 1.2608

Epoch 28/128

3830/3830 - 12s - 3ms/step - ia: 0.3318 - loss: 0.8887 - mae: 0.6998 - rmse: 0.8805 - smape: 1.3426 - val_ia: 0.2002 - val_loss: 0.7974 - val_mae: 0.6611 - val_rmse: 0.7007 - val_smape: 1.2577

Epoch 29/128

3830/3830 - 12s - 3ms/step - ia: 0.3312 - loss: 0.8868 - mae: 0.6987 - rmse: 0.8810 - smape: 1.3419 - val_ia: 0.2001 - val_loss: 0.7955 - val_mae: 0.6610 - val_rmse: 0.7007 - val_smape: 1.2568

Epoch 30/128

3830/3830 - 16s - 4ms/step - ia: 0.3343 - loss: 0.8855 - mae: 0.6975 - rmse: 0.8812 - smape: 1.3381 - val_ia: 0.1997 - val_loss: 0.7961 - val_mae: 0.6617 - val_rmse: 0.7014 - val_smape: 1.2601

Epoch 31/128

3830/3830 - 17s - 4ms/step - ia: 0.3340 - loss: 0.8831 - mae: 0.6971 - rmse: 0.8796 - smape: 1.3371 - val_ia: 0.1999 - val_loss: 0.7950 - val_mae: 0.6612 - val_rmse: 0.7010 - val_smape: 1.2568

Epoch 32/128

3830/3830 - 19s - 5ms/step - ia: 0.3373 - loss: 0.8813 - mae: 0.6965 - rmse: 0.8772 - smape: 1.3334 - val_ia: 0.2012 - val_loss: 0.7938 - val_mae: 0.6579 - val_rmse: 0.6979 - val_smape: 1.2451

Epoch 33/128

3830/3830 - 15s - 4ms/step - ia: 0.3376 - loss: 0.8784 - mae: 0.6941 - rmse: 0.8763 - smape: 1.3264 - val_ia: 0.2010 - val_loss: 0.7912 - val_mae: 0.6582 - val_rmse: 0.6982 - val_smape: 1.2450

Epoch 34/128

3830/3830 - 14s - 4ms/step - ia: 0.3372 - loss: 0.8811 - mae: 0.6948 - rmse: 0.8770 - smape: 1.3244 - val_ia: 0.2010 - val_loss: 0.7911 - val_mae: 0.6579 - val_rmse: 0.6978 - val_smape: 1.2466

Epoch 35/128

3830/3830 - 13s - 3ms/step - ia: 0.3367 - loss: 0.8793 - mae: 0.6956 - rmse: 0.8777 - smape: 1.3317 - val_ia: 0.2004 - val_loss: 0.7912 - val_mae: 0.6590 - val_rmse: 0.6989 - val_smape: 1.2513

Epoch 36/128

3830/3830 - 13s - 3ms/step - ia: 0.3406 - loss: 0.8740 - mae: 0.6933 - rmse: 0.8747 - smape: 1.3261 - val_ia: 0.2005 - val_loss: 0.7902 - val_mae: 0.6590 - val_rmse: 0.6990 - val_smape: 1.2476

Epoch 37/128

3830/3830 - 14s - 4ms/step - ia: 0.3391 - loss: 0.8730 - mae: 0.6928 - rmse: 0.8750 - smape: 1.3242 - val_ia: 0.2006 - val_loss: 0.7900 - val_mae: 0.6583 - val_rmse: 0.6984 - val_smape: 1.2459

Epoch 38/128

3830/3830 - 13s - 3ms/step - ia: 0.3425 - loss: 0.8741 - mae: 0.6918 - rmse: 0.8749 - smape: 1.3172 - val_ia: 0.2011 - val_loss: 0.7880 - val_mae: 0.6570 - val_rmse: 0.6972 - val_smape: 1.2415

Epoch 39/128

3830/3830 - 21s - 5ms/step - ia: 0.3417 - loss: 0.8725 - mae: 0.6919 - rmse: 0.8741 - smape: 1.3206 - val_ia: 0.2010 - val_loss: 0.7873 - val_mae: 0.6572 - val_rmse: 0.6974 - val_smape: 1.2427

Epoch 40/128

3830/3830 - 20s - 5ms/step - ia: 0.3405 - loss: 0.8724 - mae: 0.6930 - rmse: 0.8734 - smape: 1.3242 - val_ia: 0.2008 - val_loss: 0.7871 - val_mae: 0.6576 - val_rmse: 0.6978 - val_smape: 1.2450

Epoch 41/128

3830/3830 - 25s - 7ms/step - ia: 0.3433 - loss: 0.8703 - mae: 0.6923 - rmse: 0.8747 - smape: 1.3205 - val_ia: 0.2013 - val_loss: 0.7851 - val_mae: 0.6560 - val_rmse: 0.6963 - val_smape: 1.2397

Epoch 42/128

3830/3830 - 16s - 4ms/step - ia: 0.3437 - loss: 0.8673 - mae: 0.6909 - rmse: 0.8719 - smape: 1.3163 - val_ia: 0.2013 - val_loss: 0.7856 - val_mae: 0.6558 - val_rmse: 0.6962 - val_smape: 1.2398

Epoch 43/128

3830/3830 - 15s - 4ms/step - ia: 0.3459 - loss: 0.8678 - mae: 0.6898 - rmse: 0.8697 - smape: 1.3129 - val_ia: 0.2015 - val_loss: 0.7836 - val_mae: 0.6552 - val_rmse: 0.6956 - val_smape: 1.2372

Epoch 44/128

3830/3830 - 12s - 3ms/step - ia: 0.3426 - loss: 0.8711 - mae: 0.6916 - rmse: 0.8741 - smape: 1.3181 - val_ia: 0.2009 - val_loss: 0.7834 - val_mae: 0.6567 - val_rmse: 0.6970 - val_smape: 1.2437

Epoch 45/128

3830/3830 - 16s - 4ms/step - ia: 0.3417 - loss: 0.8717 - mae: 0.6931 - rmse: 0.8740 - smape: 1.3199 - val_ia: 0.2013 - val_loss: 0.7824 - val_mae: 0.6552 - val_rmse: 0.6955 - val_smape: 1.2405

Epoch 46/128

3830/3830 - 14s - 4ms/step - ia: 0.3456 - loss: 0.8641 - mae: 0.6887 - rmse: 0.8709 - smape: 1.3116 - val_ia: 0.2011 - val_loss: 0.7830 - val_mae: 0.6557 - val_rmse: 0.6961 - val_smape: 1.2405

Epoch 47/128

3830/3830 - 9s - 2ms/step - ia: 0.3442 - loss: 0.8673 - mae: 0.6904 - rmse: 0.8717 - smape: 1.3143 - val_ia: 0.2012 - val_loss: 0.7826 - val_mae: 0.6553 - val_rmse: 0.6958 - val_smape: 1.2408

Epoch 48/128

3830/3830 - 15s - 4ms/step - ia: 0.3455 - loss: 0.8633 - mae: 0.6885 - rmse: 0.8697 - smape: 1.3127 - val_ia: 0.2016 - val_loss: 0.7813 - val_mae: 0.6544 - val_rmse: 0.6949 - val_smape: 1.2360

Epoch 49/128

3830/3830 - 19s - 5ms/step - ia: 0.3481 - loss: 0.8643 - mae: 0.6879 - rmse: 0.8693 - smape: 1.3075 - val_ia: 0.2017 - val_loss: 0.7812 - val_mae: 0.6540 - val_rmse: 0.6945 - val_smape: 1.2359

Epoch 50/128

3830/3830 - 11s - 3ms/step - ia: 0.3469 - loss: 0.8655 - mae: 0.6889 - rmse: 0.8721 - smape: 1.3102 - val_ia: 0.2013 - val_loss: 0.7822 - val_mae: 0.6544 - val_rmse: 0.6949 - val_smape: 1.2394

Epoch 51/128

3830/3830 - 16s - 4ms/step - ia: 0.3477 - loss: 0.8636 - mae: 0.6877 - rmse: 0.8684 - smape: 1.3086 - val_ia: 0.2015 - val_loss: 0.7811 - val_mae: 0.6538 - val_rmse: 0.6943 - val_smape: 1.2389

Epoch 52/128

3830/3830 - 13s - 3ms/step - ia: 0.3452 - loss: 0.8650 - mae: 0.6883 - rmse: 0.8722 - smape: 1.3116 - val_ia: 0.2011 - val_loss: 0.7814 - val_mae: 0.6547 - val_rmse: 0.6952 - val_smape: 1.2424

Epoch 53/128

3830/3830 - 23s - 6ms/step - ia: 0.3451 - loss: 0.8637 - mae: 0.6890 - rmse: 0.8697 - smape: 1.3133 - val_ia: 0.2009 - val_loss: 0.7807 - val_mae: 0.6554 - val_rmse: 0.6958 - val_smape: 1.2435

Epoch 54/128

3830/3830 - 19s - 5ms/step - ia: 0.3420 - loss: 0.8665 - mae: 0.6909 - rmse: 0.8721 - smape: 1.3163 - val_ia: 0.2011 - val_loss: 0.7809 - val_mae: 0.6544 - val_rmse: 0.6948 - val_smape: 1.2440

Epoch 55/128

3830/3830 - 11s - 3ms/step - ia: 0.3463 - loss: 0.8598 - mae: 0.6873 - rmse: 0.8682 - smape: 1.3109 - val_ia: 0.2007 - val_loss: 0.7807 - val_mae: 0.6551 - val_rmse: 0.6956 - val_smape: 1.2448

Epoch 56/128

3830/3830 - 25s - 6ms/step - ia: 0.3487 - loss: 0.8594 - mae: 0.6858 - rmse: 0.8666 - smape: 1.3081 - val_ia: 0.2011 - val_loss: 0.7791 - val_mae: 0.6545 - val_rmse: 0.6951 - val_smape: 1.2409

Epoch 57/128

3830/3830 - 14s - 4ms/step - ia: 0.3526 - loss: 0.8554 - mae: 0.6844 - rmse: 0.8652 - smape: 1.2989 - val_ia: 0.2014 - val_loss: 0.7786 - val_mae: 0.6535 - val_rmse: 0.6942 - val_smape: 1.2367

Epoch 58/128

3830/3830 - 13s - 3ms/step - ia: 0.3519 - loss: 0.8574 - mae: 0.6840 - rmse: 0.8672 - smape: 1.2987 - val_ia: 0.2013 - val_loss: 0.7785 - val_mae: 0.6533 - val_rmse: 0.6940 - val_smape: 1.2369

Epoch 59/128

3830/3830 - 23s - 6ms/step - ia: 0.3476 - loss: 0.8603 - mae: 0.6861 - rmse: 0.8675 - smape: 1.3064 - val_ia: 0.2020 - val_loss: 0.7768 - val_mae: 0.6519 - val_rmse: 0.6927 - val_smape: 1.2329

Epoch 60/128

3830/3830 - 16s - 4ms/step - ia: 0.3506 - loss: 0.8565 - mae: 0.6855 - rmse: 0.8668 - smape: 1.3086 - val_ia: 0.2018 - val_loss: 0.7776 - val_mae: 0.6520 - val_rmse: 0.6928 - val_smape: 1.2325

Epoch 61/128

3830/3830 - 14s - 4ms/step - ia: 0.3505 - loss: 0.8584 - mae: 0.6851 - rmse: 0.8674 - smape: 1.3038 - val_ia: 0.2017 - val_loss: 0.7776 - val_mae: 0.6520 - val_rmse: 0.6928 - val_smape: 1.2352

Epoch 62/128

3830/3830 - 16s - 4ms/step - ia: 0.3515 - loss: 0.8544 - mae: 0.6836 - rmse: 0.8649 - smape: 1.3004 - val_ia: 0.2018 - val_loss: 0.7766 - val_mae: 0.6517 - val_rmse: 0.6925 - val_smape: 1.2343

Epoch 63/128

3830/3830 - 21s - 5ms/step - ia: 0.3561 - loss: 0.8517 - mae: 0.6833 - rmse: 0.8639 - smape: 1.2976 - val_ia: 0.2021 - val_loss: 0.7761 - val_mae: 0.6509 - val_rmse: 0.6918 - val_smape: 1.2312

Epoch 64/128

3830/3830 - 18s - 5ms/step - ia: 0.3565 - loss: 0.8515 - mae: 0.6820 - rmse: 0.8617 - smape: 1.2958 - val_ia: 0.2018 - val_loss: 0.7762 - val_mae: 0.6516 - val_rmse: 0.6924 - val_smape: 1.2361

Epoch 65/128

3830/3830 - 19s - 5ms/step - ia: 0.3535 - loss: 0.8531 - mae: 0.6840 - rmse: 0.8658 - smape: 1.2998 - val_ia: 0.2017 - val_loss: 0.7759 - val_mae: 0.6518 - val_rmse: 0.6925 - val_smape: 1.2387

Epoch 66/128

3830/3830 - 11s - 3ms/step - ia: 0.3549 - loss: 0.8524 - mae: 0.6831 - rmse: 0.8650 - smape: 1.3002 - val_ia: 0.2023 - val_loss: 0.7752 - val_mae: 0.6503 - val_rmse: 0.6911 - val_smape: 1.2331

Epoch 67/128

3830/3830 - 14s - 4ms/step - ia: 0.3533 - loss: 0.8536 - mae: 0.6826 - rmse: 0.8663 - smape: 1.2984 - val_ia: 0.2021 - val_loss: 0.7752 - val_mae: 0.6508 - val_rmse: 0.6916 - val_smape: 1.2357

Epoch 68/128

3830/3830 - 15s - 4ms/step - ia: 0.3547 - loss: 0.8522 - mae: 0.6836 - rmse: 0.8632 - smape: 1.2994 - val_ia: 0.2022 - val_loss: 0.7744 - val_mae: 0.6509 - val_rmse: 0.6917 - val_smape: 1.2364

Epoch 69/128

3830/3830 - 16s - 4ms/step - ia: 0.3562 - loss: 0.8487 - mae: 0.6813 - rmse: 0.8616 - smape: 1.2980 - val_ia: 0.2022 - val_loss: 0.7745 - val_mae: 0.6509 - val_rmse: 0.6917 - val_smape: 1.2352

Epoch 70/128

3830/3830 - 20s - 5ms/step - ia: 0.3550 - loss: 0.8513 - mae: 0.6831 - rmse: 0.8646 - smape: 1.3027 - val_ia: 0.2020 - val_loss: 0.7748 - val_mae: 0.6510 - val_rmse: 0.6918 - val_smape: 1.2370

Epoch 71/128

3830/3830 - 21s - 5ms/step - ia: 0.3593 - loss: 0.8462 - mae: 0.6794 - rmse: 0.8613 - smape: 1.2920 - val_ia: 0.2023 - val_loss: 0.7735 - val_mae: 0.6497 - val_rmse: 0.6906 - val_smape: 1.2336

Epoch 72/128

3830/3830 - 10s - 3ms/step - ia: 0.3581 - loss: 0.8480 - mae: 0.6815 - rmse: 0.8631 - smape: 1.2960 - val_ia: 0.2017 - val_loss: 0.7739 - val_mae: 0.6509 - val_rmse: 0.6917 - val_smape: 1.2401

Epoch 73/128

3830/3830 - 16s - 4ms/step - ia: 0.3582 - loss: 0.8476 - mae: 0.6787 - rmse: 0.8608 - smape: 1.2968 - val_ia: 0.2017 - val_loss: 0.7737 - val_mae: 0.6510 - val_rmse: 0.6919 - val_smape: 1.2385

Epoch 74/128

3830/3830 - 11s - 3ms/step - ia: 0.3589 - loss: 0.8464 - mae: 0.6798 - rmse: 0.8613 - smape: 1.2953 - val_ia: 0.2017 - val_loss: 0.7733 - val_mae: 0.6511 - val_rmse: 0.6920 - val_smape: 1.2400

Epoch 75/128

3830/3830 - 12s - 3ms/step - ia: 0.3566 - loss: 0.8483 - mae: 0.6818 - rmse: 0.8619 - smape: 1.3042 - val_ia: 0.2022 - val_loss: 0.7723 - val_mae: 0.6497 - val_rmse: 0.6907 - val_smape: 1.2375

Epoch 76/128

3830/3830 - 22s - 6ms/step - ia: 0.3567 - loss: 0.8476 - mae: 0.6804 - rmse: 0.8609 - smape: 1.3008 - val_ia: 0.2025 - val_loss: 0.7719 - val_mae: 0.6487 - val_rmse: 0.6897 - val_smape: 1.2338

Epoch 77/128

3830/3830 - 16s - 4ms/step - ia: 0.3593 - loss: 0.8498 - mae: 0.6805 - rmse: 0.8635 - smape: 1.2955 - val_ia: 0.2018 - val_loss: 0.7725 - val_mae: 0.6503 - val_rmse: 0.6911 - val_smape: 1.2421

Epoch 78/128

3830/3830 - 16s - 4ms/step - ia: 0.3582 - loss: 0.8485 - mae: 0.6799 - rmse: 0.8621 - smape: 1.2972 - val_ia: 0.2019 - val_loss: 0.7728 - val_mae: 0.6500 - val_rmse: 0.6909 - val_smape: 1.2410

Epoch 79/128

3830/3830 - 15s - 4ms/step - ia: 0.3575 - loss: 0.8449 - mae: 0.6790 - rmse: 0.8599 - smape: 1.2970 - val_ia: 0.2018 - val_loss: 0.7727 - val_mae: 0.6499 - val_rmse: 0.6909 - val_smape: 1.2398

Epoch 80/128

3830/3830 - 13s - 3ms/step - ia: 0.3587 - loss: 0.8484 - mae: 0.6803 - rmse: 0.8617 - smape: 1.2967 - val_ia: 0.2023 - val_loss: 0.7716 - val_mae: 0.6490 - val_rmse: 0.6900 - val_smape: 1.2375

Epoch 81/128

3830/3830 - 27s - 7ms/step - ia: 0.3604 - loss: 0.8433 - mae: 0.6787 - rmse: 0.8591 - smape: 1.2950 - val_ia: 0.2024 - val_loss: 0.7713 - val_mae: 0.6489 - val_rmse: 0.6899 - val_smape: 1.2367

Epoch 82/128

3830/3830 - 27s - 7ms/step - ia: 0.3613 - loss: 0.8417 - mae: 0.6776 - rmse: 0.8597 - smape: 1.2936 - val_ia: 0.2022 - val_loss: 0.7718 - val_mae: 0.6488 - val_rmse: 0.6898 - val_smape: 1.2373

Epoch 83/128

3830/3830 - 21s - 5ms/step - ia: 0.3616 - loss: 0.8428 - mae: 0.6786 - rmse: 0.8596 - smape: 1.2952 - val_ia: 0.2021 - val_loss: 0.7715 - val_mae: 0.6487 - val_rmse: 0.6897 - val_smape: 1.2406

Epoch 84/128

3830/3830 - 17s - 5ms/step - ia: 0.3596 - loss: 0.8438 - mae: 0.6781 - rmse: 0.8592 - smape: 1.2975 - val_ia: 0.2023 - val_loss: 0.7707 - val_mae: 0.6489 - val_rmse: 0.6899 - val_smape: 1.2388

Epoch 85/128

3830/3830 - 20s - 5ms/step - ia: 0.3600 - loss: 0.8409 - mae: 0.6774 - rmse: 0.8587 - smape: 1.2947 - val_ia: 0.2021 - val_loss: 0.7704 - val_mae: 0.6491 - val_rmse: 0.6901 - val_smape: 1.2403

Epoch 86/128

3830/3830 - 18s - 5ms/step - ia: 0.3623 - loss: 0.8450 - mae: 0.6789 - rmse: 0.8610 - smape: 1.2968 - val_ia: 0.2023 - val_loss: 0.7702 - val_mae: 0.6480 - val_rmse: 0.6890 - val_smape: 1.2391

Epoch 87/128

3830/3830 - 21s - 6ms/step - ia: 0.3609 - loss: 0.8408 - mae: 0.6772 - rmse: 0.8570 - smape: 1.2955 - val_ia: 0.2022 - val_loss: 0.7700 - val_mae: 0.6478 - val_rmse: 0.6887 - val_smape: 1.2414

Epoch 88/128

3830/3830 - 21s - 5ms/step - ia: 0.3619 - loss: 0.8432 - mae: 0.6772 - rmse: 0.8592 - smape: 1.2953 - val_ia: 0.2018 - val_loss: 0.7706 - val_mae: 0.6490 - val_rmse: 0.6900 - val_smape: 1.2443

Epoch 89/128

3830/3830 - 20s - 5ms/step - ia: 0.3610 - loss: 0.8410 - mae: 0.6778 - rmse: 0.8583 - smape: 1.2961 - val_ia: 0.2026 - val_loss: 0.7693 - val_mae: 0.6477 - val_rmse: 0.6887 - val_smape: 1.2388

Epoch 90/128

3830/3830 - 21s - 5ms/step - ia: 0.3610 - loss: 0.8390 - mae: 0.6768 - rmse: 0.8569 - smape: 1.2953 - val_ia: 0.2031 - val_loss: 0.7683 - val_mae: 0.6473 - val_rmse: 0.6884 - val_smape: 1.2363

Epoch 91/128

3830/3830 - 19s - 5ms/step - ia: 0.3630 - loss: 0.8415 - mae: 0.6783 - rmse: 0.8593 - smape: 1.2984 - val_ia: 0.2023 - val_loss: 0.7691 - val_mae: 0.6480 - val_rmse: 0.6890 - val_smape: 1.2412

Epoch 92/128

3830/3830 - 20s - 5ms/step - ia: 0.3616 - loss: 0.8409 - mae: 0.6782 - rmse: 0.8584 - smape: 1.3013 - val_ia: 0.2018 - val_loss: 0.7697 - val_mae: 0.6483 - val_rmse: 0.6893 - val_smape: 1.2447

Epoch 93/128

3830/3830 - 20s - 5ms/step - ia: 0.3646 - loss: 0.8393 - mae: 0.6758 - rmse: 0.8582 - smape: 1.2953 - val_ia: 0.2020 - val_loss: 0.7687 - val_mae: 0.6481 - val_rmse: 0.6891 - val_smape: 1.2445

Epoch 94/128

3830/3830 - 18s - 5ms/step - ia: 0.3624 - loss: 0.8400 - mae: 0.6765 - rmse: 0.8566 - smape: 1.2973 - val_ia: 0.2020 - val_loss: 0.7685 - val_mae: 0.6480 - val_rmse: 0.6889 - val_smape: 1.2453

Epoch 95/128

3830/3830 - 23s - 6ms/step - ia: 0.3636 - loss: 0.8401 - mae: 0.6757 - rmse: 0.8579 - smape: 1.2949 - val_ia: 0.2025 - val_loss: 0.7678 - val_mae: 0.6472 - val_rmse: 0.6881 - val_smape: 1.2434

Epoch 96/128

3830/3830 - 22s - 6ms/step - ia: 0.3641 - loss: 0.8380 - mae: 0.6759 - rmse: 0.8565 - smape: 1.2976 - val_ia: 0.2026 - val_loss: 0.7675 - val_mae: 0.6470 - val_rmse: 0.6880 - val_smape: 1.2429

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

120/120 - 10s - 80ms/step - ia: 0.3120 - loss: 1.9066 - mae: 1.0659 - rmse: 1.3754 - smape: 1.4199 - val_ia: 0.3160 - val_loss: 0.9096 - val_mae: 0.7299 - val_rmse: 0.9026 - val_smape: 1.3694

Epoch 2/128

120/120 - 1s - 5ms/step - ia: 0.3459 - loss: 1.3989 - mae: 0.9000 - rmse: 1.1793 - smape: 1.3636 - val_ia: 0.3301 - val_loss: 0.8477 - val_mae: 0.6938 - val_rmse: 0.8620 - val_smape: 1.3358

Epoch 3/128

120/120 - 1s - 6ms/step - ia: 0.3604 - loss: 1.1898 - mae: 0.8254 - rmse: 1.0880 - smape: 1.3424 - val_ia: 0.3310 - val_loss: 0.8140 - val_mae: 0.6742 - val_rmse: 0.8389 - val_smape: 1.3200

Epoch 4/128

120/120 - 1s - 5ms/step - ia: 0.3691 - loss: 1.0852 - mae: 0.7851 - rmse: 1.0392 - smape: 1.3335 - val_ia: 0.3299 - val_loss: 0.7987 - val_mae: 0.6675 - val_rmse: 0.8297 - val_smape: 1.3241

Epoch 5/128

120/120 - 1s - 7ms/step - ia: 0.3747 - loss: 1.0188 - mae: 0.7536 - rmse: 1.0072 - smape: 1.3158 - val_ia: 0.3319 - val_loss: 0.7832 - val_mae: 0.6576 - val_rmse: 0.8194 - val_smape: 1.2996

Epoch 6/128

120/120 - 1s - 6ms/step - ia: 0.3728 - loss: 0.9852 - mae: 0.7400 - rmse: 0.9895 - smape: 1.3221 - val_ia: 0.3342 - val_loss: 0.7769 - val_mae: 0.6537 - val_rmse: 0.8154 - val_smape: 1.2927

Epoch 7/128

120/120 - 1s - 6ms/step - ia: 0.3785 - loss: 0.9444 - mae: 0.7228 - rmse: 0.9688 - smape: 1.3113 - val_ia: 0.3342 - val_loss: 0.7700 - val_mae: 0.6503 - val_rmse: 0.8109 - val_smape: 1.2865

Epoch 8/128

120/120 - 2s - 13ms/step - ia: 0.3784 - loss: 0.9280 - mae: 0.7144 - rmse: 0.9610 - smape: 1.3138 - val_ia: 0.3368 - val_loss: 0.7731 - val_mae: 0.6532 - val_rmse: 0.8140 - val_smape: 1.3107

Epoch 9/128

120/120 - 3s - 24ms/step - ia: 0.3782 - loss: 0.9065 - mae: 0.7052 - rmse: 0.9490 - smape: 1.3136 - val_ia: 0.3361 - val_loss: 0.7637 - val_mae: 0.6473 - val_rmse: 0.8074 - val_smape: 1.2856

Epoch 10/128

120/120 - 2s - 20ms/step - ia: 0.3813 - loss: 0.8921 - mae: 0.6992 - rmse: 0.9427 - smape: 1.3095 - val_ia: 0.3331 - val_loss: 0.7602 - val_mae: 0.6465 - val_rmse: 0.8050 - val_smape: 1.2923

Epoch 11/128

120/120 - 2s - 14ms/step - ia: 0.3773 - loss: 0.8810 - mae: 0.6944 - rmse: 0.9355 - smape: 1.3143 - val_ia: 0.3356 - val_loss: 0.7607 - val_mae: 0.6474 - val_rmse: 0.8062 - val_smape: 1.3032

Epoch 12/128

120/120 - 2s - 14ms/step - ia: 0.3779 - loss: 0.8694 - mae: 0.6890 - rmse: 0.9296 - smape: 1.3141 - val_ia: 0.3386 - val_loss: 0.7579 - val_mae: 0.6457 - val_rmse: 0.8046 - val_smape: 1.2907

Epoch 13/128

120/120 - 1s - 10ms/step - ia: 0.3787 - loss: 0.8649 - mae: 0.6879 - rmse: 0.9276 - smape: 1.3128 - val_ia: 0.3370 - val_loss: 0.7557 - val_mae: 0.6448 - val_rmse: 0.8030 - val_smape: 1.2956

Epoch 14/128

120/120 - 2s - 13ms/step - ia: 0.3790 - loss: 0.8579 - mae: 0.6830 - rmse: 0.9236 - smape: 1.3092 - val_ia: 0.3400 - val_loss: 0.7548 - val_mae: 0.6441 - val_rmse: 0.8028 - val_smape: 1.2948

Epoch 15/128

120/120 - 1s - 11ms/step - ia: 0.3794 - loss: 0.8535 - mae: 0.6798 - rmse: 0.9216 - smape: 1.3073 - val_ia: 0.3384 - val_loss: 0.7514 - val_mae: 0.6421 - val_rmse: 0.8003 - val_smape: 1.2886

Epoch 16/128

120/120 - 1s - 10ms/step - ia: 0.3769 - loss: 0.8481 - mae: 0.6783 - rmse: 0.9184 - smape: 1.3127 - val_ia: 0.3398 - val_loss: 0.7504 - val_mae: 0.6414 - val_rmse: 0.7999 - val_smape: 1.2845

Epoch 17/128

120/120 - 1s - 8ms/step - ia: 0.3778 - loss: 0.8462 - mae: 0.6771 - rmse: 0.9172 - smape: 1.3112 - val_ia: 0.3397 - val_loss: 0.7495 - val_mae: 0.6410 - val_rmse: 0.7992 - val_smape: 1.2852

Epoch 18/128

120/120 - 1s - 8ms/step - ia: 0.3794 - loss: 0.8394 - mae: 0.6747 - rmse: 0.9141 - smape: 1.3069 - val_ia: 0.3431 - val_loss: 0.7492 - val_mae: 0.6406 - val_rmse: 0.7996 - val_smape: 1.2853

Epoch 19/128

120/120 - 1s - 11ms/step - ia: 0.3788 - loss: 0.8395 - mae: 0.6734 - rmse: 0.9133 - smape: 1.3109 - val_ia: 0.3394 - val_loss: 0.7464 - val_mae: 0.6395 - val_rmse: 0.7974 - val_smape: 1.2790

Epoch 20/128

120/120 - 1s - 11ms/step - ia: 0.3787 - loss: 0.8332 - mae: 0.6720 - rmse: 0.9101 - smape: 1.3109 - val_ia: 0.3406 - val_loss: 0.7470 - val_mae: 0.6396 - val_rmse: 0.7977 - val_smape: 1.2800

Epoch 21/128

120/120 - 2s - 13ms/step - ia: 0.3776 - loss: 0.8341 - mae: 0.6733 - rmse: 0.9112 - smape: 1.3124 - val_ia: 0.3398 - val_loss: 0.7475 - val_mae: 0.6409 - val_rmse: 0.7985 - val_smape: 1.2925

Epoch 22/128

120/120 - 1s - 11ms/step - ia: 0.3756 - loss: 0.8341 - mae: 0.6723 - rmse: 0.9108 - smape: 1.3183 - val_ia: 0.3413 - val_loss: 0.7447 - val_mae: 0.6389 - val_rmse: 0.7968 - val_smape: 1.2862

Epoch 23/128

120/120 - 3s - 21ms/step - ia: 0.3768 - loss: 0.8296 - mae: 0.6711 - rmse: 0.9083 - smape: 1.3148 - val_ia: 0.3436 - val_loss: 0.7456 - val_mae: 0.6387 - val_rmse: 0.7973 - val_smape: 1.2789

Epoch 24/128

120/120 - 2s - 17ms/step - ia: 0.3792 - loss: 0.8295 - mae: 0.6690 - rmse: 0.9078 - smape: 1.3119 - val_ia: 0.3411 - val_loss: 0.7457 - val_mae: 0.6396 - val_rmse: 0.7974 - val_smape: 1.2848

Epoch 25/128

120/120 - 2s - 20ms/step - ia: 0.3811 - loss: 0.8254 - mae: 0.6673 - rmse: 0.9059 - smape: 1.3075 - val_ia: 0.3426 - val_loss: 0.7449 - val_mae: 0.6385 - val_rmse: 0.7968 - val_smape: 1.2839

Epoch 26/128

120/120 - 3s - 24ms/step - ia: 0.3773 - loss: 0.8224 - mae: 0.6680 - rmse: 0.9045 - smape: 1.3159 - val_ia: 0.3447 - val_loss: 0.7420 - val_mae: 0.6361 - val_rmse: 0.7949 - val_smape: 1.2705

Epoch 27/128

120/120 - 1s - 12ms/step - ia: 0.3812 - loss: 0.8233 - mae: 0.6664 - rmse: 0.9052 - smape: 1.3101 - val_ia: 0.3439 - val_loss: 0.7423 - val_mae: 0.6370 - val_rmse: 0.7954 - val_smape: 1.2748

Epoch 28/128

120/120 - 1s - 11ms/step - ia: 0.3792 - loss: 0.8219 - mae: 0.6656 - rmse: 0.9042 - smape: 1.3096 - val_ia: 0.3451 - val_loss: 0.7423 - val_mae: 0.6368 - val_rmse: 0.7953 - val_smape: 1.2788

Epoch 29/128

120/120 - 2s - 13ms/step - ia: 0.3811 - loss: 0.8208 - mae: 0.6660 - rmse: 0.9037 - smape: 1.3117 - val_ia: 0.3427 - val_loss: 0.7418 - val_mae: 0.6373 - val_rmse: 0.7950 - val_smape: 1.2838

Epoch 30/128

120/120 - 2s - 13ms/step - ia: 0.3788 - loss: 0.8199 - mae: 0.6660 - rmse: 0.9032 - smape: 1.3129 - val_ia: 0.3445 - val_loss: 0.7419 - val_mae: 0.6374 - val_rmse: 0.7954 - val_smape: 1.2763

Epoch 31/128

120/120 - 1s - 11ms/step - ia: 0.3780 - loss: 0.8214 - mae: 0.6667 - rmse: 0.9031 - smape: 1.3114 - val_ia: 0.3434 - val_loss: 0.7420 - val_mae: 0.6380 - val_rmse: 0.7958 - val_smape: 1.2815

Epoch 32/128

120/120 - 1s - 9ms/step - ia: 0.3816 - loss: 0.8166 - mae: 0.6639 - rmse: 0.9014 - smape: 1.3079 - val_ia: 0.3465 - val_loss: 0.7403 - val_mae: 0.6358 - val_rmse: 0.7946 - val_smape: 1.2757

Epoch 33/128

120/120 - 1s - 11ms/step - ia: 0.3838 - loss: 0.8118 - mae: 0.6635 - rmse: 0.8982 - smape: 1.3084 - val_ia: 0.3485 - val_loss: 0.7417 - val_mae: 0.6368 - val_rmse: 0.7959 - val_smape: 1.2782

Epoch 34/128

120/120 - 1s - 12ms/step - ia: 0.3840 - loss: 0.8128 - mae: 0.6618 - rmse: 0.8993 - smape: 1.3033 - val_ia: 0.3473 - val_loss: 0.7414 - val_mae: 0.6368 - val_rmse: 0.7954 - val_smape: 1.2793

Epoch 35/128

120/120 - 1s - 8ms/step - ia: 0.3819 - loss: 0.8153 - mae: 0.6633 - rmse: 0.9003 - smape: 1.3064 - val_ia: 0.3438 - val_loss: 0.7411 - val_mae: 0.6384 - val_rmse: 0.7958 - val_smape: 1.2827

Epoch 36/128

120/120 - 1s - 9ms/step - ia: 0.3841 - loss: 0.8117 - mae: 0.6626 - rmse: 0.8983 - smape: 1.3058 - val_ia: 0.3442 - val_loss: 0.7398 - val_mae: 0.6359 - val_rmse: 0.7940 - val_smape: 1.2776

Epoch 37/128

120/120 - 2s - 14ms/step - ia: 0.3823 - loss: 0.8132 - mae: 0.6623 - rmse: 0.8993 - smape: 1.3078 - val_ia: 0.3473 - val_loss: 0.7416 - val_mae: 0.6375 - val_rmse: 0.7960 - val_smape: 1.2805

Epoch 38/128

120/120 - 2s - 14ms/step - ia: 0.3850 - loss: 0.8072 - mae: 0.6613 - rmse: 0.8960 - smape: 1.3069 - val_ia: 0.3457 - val_loss: 0.7403 - val_mae: 0.6364 - val_rmse: 0.7947 - val_smape: 1.2741

Epoch 39/128

120/120 - 1s - 7ms/step - ia: 0.3827 - loss: 0.8119 - mae: 0.6629 - rmse: 0.8983 - smape: 1.3077 - val_ia: 0.3488 - val_loss: 0.7389 - val_mae: 0.6348 - val_rmse: 0.7937 - val_smape: 1.2722

Epoch 40/128

120/120 - 1s - 7ms/step - ia: 0.3825 - loss: 0.8122 - mae: 0.6610 - rmse: 0.8980 - smape: 1.3062 - val_ia: 0.3490 - val_loss: 0.7378 - val_mae: 0.6346 - val_rmse: 0.7934 - val_smape: 1.2665

Epoch 41/128

120/120 - 1s - 7ms/step - ia: 0.3879 - loss: 0.8048 - mae: 0.6598 - rmse: 0.8946 - smape: 1.3007 - val_ia: 0.3479 - val_loss: 0.7406 - val_mae: 0.6366 - val_rmse: 0.7952 - val_smape: 1.2768

Epoch 42/128

120/120 - 1s - 12ms/step - ia: 0.3842 - loss: 0.8103 - mae: 0.6606 - rmse: 0.8974 - smape: 1.3039 - val_ia: 0.3494 - val_loss: 0.7400 - val_mae: 0.6363 - val_rmse: 0.7950 - val_smape: 1.2775

Epoch 43/128

120/120 - 1s - 8ms/step - ia: 0.3840 - loss: 0.8104 - mae: 0.6608 - rmse: 0.8979 - smape: 1.3009 - val_ia: 0.3469 - val_loss: 0.7393 - val_mae: 0.6368 - val_rmse: 0.7947 - val_smape: 1.2737

Epoch 44/128

120/120 - 1s - 10ms/step - ia: 0.3843 - loss: 0.8095 - mae: 0.6609 - rmse: 0.8975 - smape: 1.3046 - val_ia: 0.3494 - val_loss: 0.7422 - val_mae: 0.6373 - val_rmse: 0.7962 - val_smape: 1.2768

Epoch 45/128

120/120 - 2s - 13ms/step - ia: 0.3831 - loss: 0.8106 - mae: 0.6620 - rmse: 0.8979 - smape: 1.3077 - val_ia: 0.3488 - val_loss: 0.7399 - val_mae: 0.6359 - val_rmse: 0.7947 - val_smape: 1.2756

Epoch 46/128

120/120 - 2s - 13ms/step - ia: 0.3837 - loss: 0.8088 - mae: 0.6604 - rmse: 0.8968 - smape: 1.3047 - val_ia: 0.3507 - val_loss: 0.7404 - val_mae: 0.6362 - val_rmse: 0.7955 - val_smape: 1.2759

Epoch 47/128

120/120 - 1s - 10ms/step - ia: 0.3869 - loss: 0.8069 - mae: 0.6594 - rmse: 0.8954 - smape: 1.3021 - val_ia: 0.3479 - val_loss: 0.7383 - val_mae: 0.6364 - val_rmse: 0.7946 - val_smape: 1.2742

Epoch 48/128

120/120 - 1s - 10ms/step - ia: 0.3862 - loss: 0.8064 - mae: 0.6592 - rmse: 0.8948 - smape: 1.3011 - val_ia: 0.3514 - val_loss: 0.7403 - val_mae: 0.6361 - val_rmse: 0.7956 - val_smape: 1.2676

Epoch 49/128

120/120 - 1s - 10ms/step - ia: 0.3862 - loss: 0.8079 - mae: 0.6608 - rmse: 0.8963 - smape: 1.3009 - val_ia: 0.3500 - val_loss: 0.7395 - val_mae: 0.6359 - val_rmse: 0.7952 - val_smape: 1.2708

Epoch 50/128

120/120 - 2s - 14ms/step - ia: 0.3895 - loss: 0.8023 - mae: 0.6574 - rmse: 0.8935 - smape: 1.2973 - val_ia: 0.3494 - val_loss: 0.7405 - val_mae: 0.6364 - val_rmse: 0.7955 - val_smape: 1.2719

Epoch 51/128

120/120 - 1s - 12ms/step - ia: 0.3869 - loss: 0.8084 - mae: 0.6602 - rmse: 0.8968 - smape: 1.2991 - val_ia: 0.3477 - val_loss: 0.7390 - val_mae: 0.6359 - val_rmse: 0.7943 - val_smape: 1.2762

Epoch 52/128

120/120 - 1s - 9ms/step - ia: 0.3909 - loss: 0.7992 - mae: 0.6567 - rmse: 0.8922 - smape: 1.2951 - val_ia: 0.3511 - val_loss: 0.7401 - val_mae: 0.6363 - val_rmse: 0.7955 - val_smape: 1.2764

Epoch 53/128

120/120 - 1s - 12ms/step - ia: 0.3887 - loss: 0.8034 - mae: 0.6588 - rmse: 0.8940 - smape: 1.2975 - val_ia: 0.3510 - val_loss: 0.7398 - val_mae: 0.6369 - val_rmse: 0.7959 - val_smape: 1.2785

Epoch 54/128

120/120 - 2s - 13ms/step - ia: 0.3884 - loss: 0.8007 - mae: 0.6583 - rmse: 0.8923 - smape: 1.2982 - val_ia: 0.3497 - val_loss: 0.7376 - val_mae: 0.6349 - val_rmse: 0.7937 - val_smape: 1.2692

Epoch 55/128

120/120 - 1s - 12ms/step - ia: 0.3862 - loss: 0.8074 - mae: 0.6597 - rmse: 0.8953 - smape: 1.3009 - val_ia: 0.3541 - val_loss: 0.7386 - val_mae: 0.6346 - val_rmse: 0.7944 - val_smape: 1.2680

Epoch 56/128

120/120 - 1s - 12ms/step - ia: 0.3874 - loss: 0.8010 - mae: 0.6590 - rmse: 0.8929 - smape: 1.3015 - val_ia: 0.3555 - val_loss: 0.7401 - val_mae: 0.6348 - val_rmse: 0.7954 - val_smape: 1.2656

Epoch 57/128

120/120 - 2s - 14ms/step - ia: 0.3914 - loss: 0.8003 - mae: 0.6572 - rmse: 0.8923 - smape: 1.2954 - val_ia: 0.3514 - val_loss: 0.7406 - val_mae: 0.6369 - val_rmse: 0.7959 - val_smape: 1.2802

Epoch 58/128

120/120 - 1s - 11ms/step - ia: 0.3867 - loss: 0.8033 - mae: 0.6586 - rmse: 0.8936 - smape: 1.3020 - val_ia: 0.3543 - val_loss: 0.7372 - val_mae: 0.6338 - val_rmse: 0.7936 - val_smape: 1.2676

Epoch 59/128

120/120 - 2s - 13ms/step - ia: 0.3895 - loss: 0.8040 - mae: 0.6577 - rmse: 0.8937 - smape: 1.2961 - val_ia: 0.3525 - val_loss: 0.7391 - val_mae: 0.6354 - val_rmse: 0.7947 - val_smape: 1.2727

Epoch 60/128

120/120 - 1s - 9ms/step - ia: 0.3896 - loss: 0.8031 - mae: 0.6578 - rmse: 0.8937 - smape: 1.2964 - val_ia: 0.3506 - val_loss: 0.7364 - val_mae: 0.6341 - val_rmse: 0.7929 - val_smape: 1.2705

Epoch 61/128

120/120 - 2s - 13ms/step - ia: 0.3845 - loss: 0.8093 - mae: 0.6595 - rmse: 0.8973 - smape: 1.2977 - val_ia: 0.3510 - val_loss: 0.7361 - val_mae: 0.6341 - val_rmse: 0.7929 - val_smape: 1.2657

Epoch 62/128

120/120 - 1s - 9ms/step - ia: 0.3916 - loss: 0.7979 - mae: 0.6559 - rmse: 0.8915 - smape: 1.2933 - val_ia: 0.3529 - val_loss: 0.7355 - val_mae: 0.6334 - val_rmse: 0.7926 - val_smape: 1.2645

Epoch 63/128

120/120 - 1s - 12ms/step - ia: 0.3895 - loss: 0.8017 - mae: 0.6576 - rmse: 0.8926 - smape: 1.2966 - val_ia: 0.3533 - val_loss: 0.7381 - val_mae: 0.6352 - val_rmse: 0.7944 - val_smape: 1.2708

Epoch 64/128

120/120 - 1s - 11ms/step - ia: 0.3896 - loss: 0.8018 - mae: 0.6573 - rmse: 0.8930 - smape: 1.2975 - val_ia: 0.3544 - val_loss: 0.7378 - val_mae: 0.6351 - val_rmse: 0.7946 - val_smape: 1.2704

Epoch 65/128

120/120 - 1s - 5ms/step - ia: 0.3906 - loss: 0.8015 - mae: 0.6570 - rmse: 0.8924 - smape: 1.2950 - val_ia: 0.3524 - val_loss: 0.7390 - val_mae: 0.6355 - val_rmse: 0.7946 - val_smape: 1.2722

Epoch 66/128

120/120 - 1s - 5ms/step - ia: 0.3885 - loss: 0.7994 - mae: 0.6574 - rmse: 0.8916 - smape: 1.2987 - val_ia: 0.3547 - val_loss: 0.7367 - val_mae: 0.6342 - val_rmse: 0.7937 - val_smape: 1.2649

Epoch 67/128

120/120 - 1s - 4ms/step - ia: 0.3905 - loss: 0.8009 - mae: 0.6571 - rmse: 0.8918 - smape: 1.2939 - val_ia: 0.3527 - val_loss: 0.7383 - val_mae: 0.6359 - val_rmse: 0.7946 - val_smape: 1.2764

Epoch 68/128

120/120 - 1s - 6ms/step - ia: 0.3911 - loss: 0.8019 - mae: 0.6562 - rmse: 0.8932 - smape: 1.2920 - val_ia: 0.3517 - val_loss: 0.7366 - val_mae: 0.6349 - val_rmse: 0.7935 - val_smape: 1.2682

Epoch 69/128

120/120 - 0s - 4ms/step - ia: 0.3889 - loss: 0.8016 - mae: 0.6579 - rmse: 0.8931 - smape: 1.2973 - val_ia: 0.3540 - val_loss: 0.7361 - val_mae: 0.6340 - val_rmse: 0.7933 - val_smape: 1.2632

Epoch 70/128

120/120 - 0s - 4ms/step - ia: 0.3936 - loss: 0.7980 - mae: 0.6556 - rmse: 0.8913 - smape: 1.2891 - val_ia: 0.3556 - val_loss: 0.7372 - val_mae: 0.6347 - val_rmse: 0.7944 - val_smape: 1.2660

Epoch 71/128

120/120 - 0s - 4ms/step - ia: 0.3918 - loss: 0.7984 - mae: 0.6559 - rmse: 0.8915 - smape: 1.2918 - val_ia: 0.3539 - val_loss: 0.7355 - val_mae: 0.6335 - val_rmse: 0.7928 - val_smape: 1.2600

Epoch 72/128

120/120 - 1s - 5ms/step - ia: 0.3924 - loss: 0.7974 - mae: 0.6553 - rmse: 0.8908 - smape: 1.2906 - val_ia: 0.3545 - val_loss: 0.7347 - val_mae: 0.6339 - val_rmse: 0.7928 - val_smape: 1.2618

Epoch 73/128

120/120 - 1s - 5ms/step - ia: 0.3929 - loss: 0.7991 - mae: 0.6573 - rmse: 0.8913 - smape: 1.2919 - val_ia: 0.3542 - val_loss: 0.7372 - val_mae: 0.6354 - val_rmse: 0.7943 - val_smape: 1.2680

Epoch 74/128

120/120 - 1s - 5ms/step - ia: 0.3924 - loss: 0.7996 - mae: 0.6567 - rmse: 0.8914 - smape: 1.2926 - val_ia: 0.3557 - val_loss: 0.7379 - val_mae: 0.6353 - val_rmse: 0.7951 - val_smape: 1.2665

Epoch 75/128

120/120 - 1s - 6ms/step - ia: 0.3913 - loss: 0.7978 - mae: 0.6582 - rmse: 0.8901 - smape: 1.2957 - val_ia: 0.3543 - val_loss: 0.7362 - val_mae: 0.6348 - val_rmse: 0.7938 - val_smape: 1.2660

Epoch 76/128

120/120 - 1s - 6ms/step - ia: 0.3921 - loss: 0.7983 - mae: 0.6550 - rmse: 0.8913 - smape: 1.2922 - val_ia: 0.3581 - val_loss: 0.7349 - val_mae: 0.6324 - val_rmse: 0.7927 - val_smape: 1.2584

Epoch 77/128

120/120 - 1s - 7ms/step - ia: 0.3915 - loss: 0.8017 - mae: 0.6574 - rmse: 0.8926 - smape: 1.2899 - val_ia: 0.3576 - val_loss: 0.7357 - val_mae: 0.6331 - val_rmse: 0.7930 - val_smape: 1.2606

Epoch 78/128

120/120 - 1s - 10ms/step - ia: 0.3911 - loss: 0.7972 - mae: 0.6554 - rmse: 0.8898 - smape: 1.2912 - val_ia: 0.3582 - val_loss: 0.7373 - val_mae: 0.6340 - val_rmse: 0.7942 - val_smape: 1.2610

Epoch 79/128

120/120 - 1s - 6ms/step - ia: 0.3948 - loss: 0.7968 - mae: 0.6551 - rmse: 0.8902 - smape: 1.2873 - val_ia: 0.3550 - val_loss: 0.7354 - val_mae: 0.6337 - val_rmse: 0.7930 - val_smape: 1.2616

Epoch 80/128

120/120 - 1s - 5ms/step - ia: 0.3942 - loss: 0.7956 - mae: 0.6552 - rmse: 0.8899 - smape: 1.2884 - val_ia: 0.3580 - val_loss: 0.7361 - val_mae: 0.6339 - val_rmse: 0.7939 - val_smape: 1.2584

Epoch 81/128

120/120 - 1s - 4ms/step - ia: 0.3923 - loss: 0.7963 - mae: 0.6559 - rmse: 0.8901 - smape: 1.2910 - val_ia: 0.3561 - val_loss: 0.7378 - val_mae: 0.6351 - val_rmse: 0.7946 - val_smape: 1.2639

Epoch 82/128

120/120 - 1s - 5ms/step - ia: 0.3923 - loss: 0.7982 - mae: 0.6573 - rmse: 0.8908 - smape: 1.2937 - val_ia: 0.3578 - val_loss: 0.7351 - val_mae: 0.6334 - val_rmse: 0.7933 - val_smape: 1.2616

Epoch 83/128

120/120 - 0s - 4ms/step - ia: 0.3934 - loss: 0.7949 - mae: 0.6553 - rmse: 0.8893 - smape: 1.2899 - val_ia: 0.3562 - val_loss: 0.7348 - val_mae: 0.6334 - val_rmse: 0.7930 - val_smape: 1.2615

Epoch 84/128

120/120 - 1s - 4ms/step - ia: 0.3924 - loss: 0.7964 - mae: 0.6564 - rmse: 0.8898 - smape: 1.2945 - val_ia: 0.3576 - val_loss: 0.7352 - val_mae: 0.6330 - val_rmse: 0.7933 - val_smape: 1.2611

Epoch 85/128

120/120 - 1s - 5ms/step - ia: 0.3950 - loss: 0.7944 - mae: 0.6547 - rmse: 0.8889 - smape: 1.2880 - val_ia: 0.3571 - val_loss: 0.7371 - val_mae: 0.6348 - val_rmse: 0.7946 - val_smape: 1.2641

Epoch 86/128

120/120 - 1s - 5ms/step - ia: 0.3941 - loss: 0.7963 - mae: 0.6548 - rmse: 0.8896 - smape: 1.2894 - val_ia: 0.3580 - val_loss: 0.7370 - val_mae: 0.6343 - val_rmse: 0.7944 - val_smape: 1.2626

Epoch 87/128

120/120 - 2s - 18ms/step - ia: 0.3927 - loss: 0.7973 - mae: 0.6556 - rmse: 0.8911 - smape: 1.2916 - val_ia: 0.3557 - val_loss: 0.7355 - val_mae: 0.6346 - val_rmse: 0.7937 - val_smape: 1.2642

Epoch 87: early stopping

Restoring model weights from the end of the best epoch: 72.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:00 447ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 69/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 60%|██████    | 30/50 [2:18:07<3:24:19, 612.98s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

3830/3830 - 27s - 7ms/step - ia: 0.3209 - loss: 0.8863 - mae: 0.6977 - rmse: 0.8788 - smape: 1.4132 - val_ia: 0.2009 - val_loss: 0.7817 - val_mae: 0.6530 - val_rmse: 0.6941 - val_smape: 1.2437

Epoch 2/256

3830/3830 - 19s - 5ms/step - ia: 0.3855 - loss: 0.8151 - mae: 0.6623 - rmse: 0.8449 - smape: 1.2370 - val_ia: 0.2037 - val_loss: 0.7585 - val_mae: 0.6352 - val_rmse: 0.6776 - val_smape: 1.2112

Epoch 3/256

3830/3830 - 13s - 3ms/step - ia: 0.3923 - loss: 0.8023 - mae: 0.6576 - rmse: 0.8392 - smape: 1.2404 - val_ia: 0.1997 - val_loss: 0.7646 - val_mae: 0.6529 - val_rmse: 0.6950 - val_smape: 1.2700

Epoch 4/256

3830/3830 - 18s - 5ms/step - ia: 0.3988 - loss: 0.7932 - mae: 0.6537 - rmse: 0.8345 - smape: 1.2369 - val_ia: 0.2029 - val_loss: 0.7621 - val_mae: 0.6475 - val_rmse: 0.6900 - val_smape: 1.2413

Epoch 5/256

3830/3830 - 18s - 5ms/step - ia: 0.4017 - loss: 0.7879 - mae: 0.6508 - rmse: 0.8320 - smape: 1.2377 - val_ia: 0.2032 - val_loss: 0.7492 - val_mae: 0.6372 - val_rmse: 0.6793 - val_smape: 1.2493

Epoch 6/256

3830/3830 - 19s - 5ms/step - ia: 0.4044 - loss: 0.7830 - mae: 0.6483 - rmse: 0.8284 - smape: 1.2342 - val_ia: 0.2033 - val_loss: 0.7658 - val_mae: 0.6514 - val_rmse: 0.6941 - val_smape: 1.2547

Epoch 7/256

3830/3830 - 17s - 4ms/step - ia: 0.4094 - loss: 0.7771 - mae: 0.6450 - rmse: 0.8261 - smape: 1.2287 - val_ia: 0.2056 - val_loss: 0.7664 - val_mae: 0.6471 - val_rmse: 0.6903 - val_smape: 1.2388

Epoch 8/256

3830/3830 - 20s - 5ms/step - ia: 0.4133 - loss: 0.7719 - mae: 0.6424 - rmse: 0.8221 - smape: 1.2229 - val_ia: 0.2028 - val_loss: 0.7608 - val_mae: 0.6494 - val_rmse: 0.6921 - val_smape: 1.2732

Epoch 9/256

3830/3830 - 19s - 5ms/step - ia: 0.4163 - loss: 0.7677 - mae: 0.6401 - rmse: 0.8194 - smape: 1.2207 - val_ia: 0.2049 - val_loss: 0.7753 - val_mae: 0.6542 - val_rmse: 0.6976 - val_smape: 1.2640

Epoch 10/256

3830/3830 - 22s - 6ms/step - ia: 0.4203 - loss: 0.7621 - mae: 0.6378 - rmse: 0.8167 - smape: 1.2198 - val_ia: 0.2050 - val_loss: 0.7708 - val_mae: 0.6527 - val_rmse: 0.6964 - val_smape: 1.2587

Epoch 11/256

3830/3830 - 18s - 5ms/step - ia: 0.4224 - loss: 0.7569 - mae: 0.6343 - rmse: 0.8154 - smape: 1.2104 - val_ia: 0.2048 - val_loss: 0.7851 - val_mae: 0.6600 - val_rmse: 0.7039 - val_smape: 1.2696

Epoch 12/256

3830/3830 - 18s - 5ms/step - ia: 0.4251 - loss: 0.7515 - mae: 0.6319 - rmse: 0.8114 - smape: 1.2054 - val_ia: 0.2078 - val_loss: 0.7689 - val_mae: 0.6454 - val_rmse: 0.6901 - val_smape: 1.2389

Epoch 13/256

3830/3830 - 22s - 6ms/step - ia: 0.4269 - loss: 0.7473 - mae: 0.6297 - rmse: 0.8098 - smape: 1.2033 - val_ia: 0.2074 - val_loss: 0.7691 - val_mae: 0.6443 - val_rmse: 0.6893 - val_smape: 1.2388

Epoch 14/256

3830/3830 - 37s - 10ms/step - ia: 0.4310 - loss: 0.7423 - mae: 0.6271 - rmse: 0.8065 - smape: 1.1976 - val_ia: 0.2064 - val_loss: 0.7911 - val_mae: 0.6561 - val_rmse: 0.7006 - val_smape: 1.2604

Epoch 15/256

3830/3830 - 14s - 4ms/step - ia: 0.4301 - loss: 0.7387 - mae: 0.6256 - rmse: 0.8035 - smape: 1.1976 - val_ia: 0.2095 - val_loss: 0.8066 - val_mae: 0.6503 - val_rmse: 0.6967 - val_smape: 1.2140

Epoch 16/256

3830/3830 - 13s - 3ms/step - ia: 0.4347 - loss: 0.7355 - mae: 0.6236 - rmse: 0.8017 - smape: 1.1928 - val_ia: 0.2107 - val_loss: 0.7804 - val_mae: 0.6386 - val_rmse: 0.6842 - val_smape: 1.2060

Epoch 17/256

3830/3830 - 13s - 3ms/step - ia: 0.4355 - loss: 0.7316 - mae: 0.6221 - rmse: 0.7997 - smape: 1.1899 - val_ia: 0.2147 - val_loss: 0.7908 - val_mae: 0.6365 - val_rmse: 0.6840 - val_smape: 1.1884

Epoch 18/256

3830/3830 - 20s - 5ms/step - ia: 0.4346 - loss: 0.7292 - mae: 0.6217 - rmse: 0.7995 - smape: 1.1902 - val_ia: 0.2103 - val_loss: 0.7967 - val_mae: 0.6435 - val_rmse: 0.6902 - val_smape: 1.2054

Epoch 19/256

3830/3830 - 16s - 4ms/step - ia: 0.4372 - loss: 0.7265 - mae: 0.6204 - rmse: 0.7969 - smape: 1.1878 - val_ia: 0.2090 - val_loss: 0.8209 - val_mae: 0.6581 - val_rmse: 0.7053 - val_smape: 1.2317

Epoch 20/256

3830/3830 - 22s - 6ms/step - ia: 0.4379 - loss: 0.7233 - mae: 0.6194 - rmse: 0.7955 - smape: 1.1879 - val_ia: 0.2041 - val_loss: 0.8292 - val_mae: 0.6776 - val_rmse: 0.7243 - val_smape: 1.2935

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:15 1s/step
  2/136 ━━━━━━━━━━━━━━━━━━━━ 20s 150ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 62%|██████▏   | 31/50 [2:24:37<2:52:56, 546.11s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 9s - 79ms/step - ia: 0.2417 - loss: 1.0116 - mae: 0.7582 - rmse: 1.0029 - smape: 1.5216 - val_ia: 0.2974 - val_loss: 0.8585 - val_mae: 0.6957 - val_rmse: 0.8548 - val_smape: 1.4965

Epoch 2/32

120/120 - 2s - 13ms/step - ia: 0.2994 - loss: 0.9247 - mae: 0.7199 - rmse: 0.9584 - smape: 1.4403 - val_ia: 0.3135 - val_loss: 0.8352 - val_mae: 0.6806 - val_rmse: 0.8429 - val_smape: 1.4308

Epoch 3/32

120/120 - 1s - 10ms/step - ia: 0.3164 - loss: 0.9007 - mae: 0.7070 - rmse: 0.9469 - smape: 1.4141 - val_ia: 0.3148 - val_loss: 0.8234 - val_mae: 0.6767 - val_rmse: 0.8380 - val_smape: 1.4152

Epoch 4/32

120/120 - 1s - 12ms/step - ia: 0.3297 - loss: 0.8800 - mae: 0.6964 - rmse: 0.9349 - smape: 1.3924 - val_ia: 0.3169 - val_loss: 0.8119 - val_mae: 0.6712 - val_rmse: 0.8320 - val_smape: 1.3993

Epoch 5/32

120/120 - 1s - 7ms/step - ia: 0.3343 - loss: 0.8681 - mae: 0.6912 - rmse: 0.9292 - smape: 1.3833 - val_ia: 0.3244 - val_loss: 0.8028 - val_mae: 0.6659 - val_rmse: 0.8280 - val_smape: 1.3739

Epoch 6/32

120/120 - 0s - 4ms/step - ia: 0.3453 - loss: 0.8560 - mae: 0.6869 - rmse: 0.9223 - smape: 1.3686 - val_ia: 0.3276 - val_loss: 0.7947 - val_mae: 0.6614 - val_rmse: 0.8233 - val_smape: 1.3607

Epoch 7/32

120/120 - 1s - 7ms/step - ia: 0.3505 - loss: 0.8500 - mae: 0.6811 - rmse: 0.9193 - smape: 1.3562 - val_ia: 0.3284 - val_loss: 0.7876 - val_mae: 0.6585 - val_rmse: 0.8199 - val_smape: 1.3527

Epoch 8/32

120/120 - 1s - 7ms/step - ia: 0.3566 - loss: 0.8387 - mae: 0.6774 - rmse: 0.9135 - smape: 1.3452 - val_ia: 0.3313 - val_loss: 0.7808 - val_mae: 0.6553 - val_rmse: 0.8167 - val_smape: 1.3456

Epoch 9/32

120/120 - 2s - 18ms/step - ia: 0.3617 - loss: 0.8331 - mae: 0.6734 - rmse: 0.9100 - smape: 1.3352 - val_ia: 0.3389 - val_loss: 0.7779 - val_mae: 0.6549 - val_rmse: 0.8172 - val_smape: 1.3351

Epoch 10/32

120/120 - 1s - 11ms/step - ia: 0.3706 - loss: 0.8276 - mae: 0.6703 - rmse: 0.9079 - smape: 1.3237 - val_ia: 0.3377 - val_loss: 0.7704 - val_mae: 0.6515 - val_rmse: 0.8126 - val_smape: 1.3320

Epoch 11/32

120/120 - 1s - 8ms/step - ia: 0.3733 - loss: 0.8249 - mae: 0.6683 - rmse: 0.9054 - smape: 1.3174 - val_ia: 0.3400 - val_loss: 0.7695 - val_mae: 0.6523 - val_rmse: 0.8134 - val_smape: 1.3310

Epoch 12/32

120/120 - 2s - 14ms/step - ia: 0.3788 - loss: 0.8187 - mae: 0.6658 - rmse: 0.9014 - smape: 1.3094 - val_ia: 0.3388 - val_loss: 0.7642 - val_mae: 0.6476 - val_rmse: 0.8086 - val_smape: 1.3238

Epoch 13/32

120/120 - 1s - 7ms/step - ia: 0.3756 - loss: 0.8207 - mae: 0.6675 - rmse: 0.9038 - smape: 1.3135 - val_ia: 0.3426 - val_loss: 0.7605 - val_mae: 0.6455 - val_rmse: 0.8070 - val_smape: 1.3143

Epoch 14/32

120/120 - 1s - 5ms/step - ia: 0.3811 - loss: 0.8128 - mae: 0.6629 - rmse: 0.8990 - smape: 1.3062 - val_ia: 0.3456 - val_loss: 0.7600 - val_mae: 0.6465 - val_rmse: 0.8080 - val_smape: 1.3113

Epoch 15/32

120/120 - 1s - 7ms/step - ia: 0.3884 - loss: 0.8084 - mae: 0.6609 - rmse: 0.8968 - smape: 1.2931 - val_ia: 0.3428 - val_loss: 0.7573 - val_mae: 0.6465 - val_rmse: 0.8068 - val_smape: 1.3162

Epoch 16/32

120/120 - 1s - 9ms/step - ia: 0.3861 - loss: 0.8105 - mae: 0.6595 - rmse: 0.8974 - smape: 1.2939 - val_ia: 0.3456 - val_loss: 0.7573 - val_mae: 0.6468 - val_rmse: 0.8074 - val_smape: 1.3123

Epoch 17/32

120/120 - 1s - 12ms/step - ia: 0.3895 - loss: 0.8072 - mae: 0.6594 - rmse: 0.8961 - smape: 1.2904 - val_ia: 0.3453 - val_loss: 0.7543 - val_mae: 0.6454 - val_rmse: 0.8055 - val_smape: 1.3112

Epoch 18/32

120/120 - 1s - 9ms/step - ia: 0.3906 - loss: 0.8074 - mae: 0.6591 - rmse: 0.8957 - smape: 1.2907 - val_ia: 0.3436 - val_loss: 0.7551 - val_mae: 0.6465 - val_rmse: 0.8062 - val_smape: 1.3217

Epoch 19/32

120/120 - 1s - 6ms/step - ia: 0.3874 - loss: 0.8051 - mae: 0.6591 - rmse: 0.8950 - smape: 1.2936 - val_ia: 0.3504 - val_loss: 0.7536 - val_mae: 0.6443 - val_rmse: 0.8055 - val_smape: 1.3060

Epoch 20/32

120/120 - 1s - 9ms/step - ia: 0.3977 - loss: 0.7983 - mae: 0.6556 - rmse: 0.8907 - smape: 1.2805 - val_ia: 0.3466 - val_loss: 0.7507 - val_mae: 0.6431 - val_rmse: 0.8031 - val_smape: 1.3079

Epoch 21/32

120/120 - 1s - 11ms/step - ia: 0.3946 - loss: 0.7984 - mae: 0.6555 - rmse: 0.8912 - smape: 1.2823 - val_ia: 0.3484 - val_loss: 0.7528 - val_mae: 0.6454 - val_rmse: 0.8056 - val_smape: 1.3051

Epoch 22/32

120/120 - 1s - 10ms/step - ia: 0.3966 - loss: 0.7965 - mae: 0.6546 - rmse: 0.8901 - smape: 1.2792 - val_ia: 0.3493 - val_loss: 0.7535 - val_mae: 0.6447 - val_rmse: 0.8056 - val_smape: 1.3026

Epoch 23/32

120/120 - 1s - 6ms/step - ia: 0.3988 - loss: 0.7989 - mae: 0.6555 - rmse: 0.8909 - smape: 1.2777 - val_ia: 0.3492 - val_loss: 0.7494 - val_mae: 0.6406 - val_rmse: 0.8015 - val_smape: 1.2941

Epoch 24/32

120/120 - 1s - 6ms/step - ia: 0.3971 - loss: 0.7940 - mae: 0.6543 - rmse: 0.8884 - smape: 1.2765 - val_ia: 0.3483 - val_loss: 0.7519 - val_mae: 0.6432 - val_rmse: 0.8037 - val_smape: 1.2989

Epoch 25/32

120/120 - 1s - 6ms/step - ia: 0.4028 - loss: 0.7892 - mae: 0.6518 - rmse: 0.8853 - smape: 1.2703 - val_ia: 0.3551 - val_loss: 0.7531 - val_mae: 0.6422 - val_rmse: 0.8048 - val_smape: 1.2885

Epoch 26/32

120/120 - 1s - 9ms/step - ia: 0.4034 - loss: 0.7907 - mae: 0.6520 - rmse: 0.8863 - smape: 1.2699 - val_ia: 0.3508 - val_loss: 0.7509 - val_mae: 0.6422 - val_rmse: 0.8034 - val_smape: 1.2969

Epoch 27/32

120/120 - 1s - 10ms/step - ia: 0.4021 - loss: 0.7881 - mae: 0.6514 - rmse: 0.8856 - smape: 1.2701 - val_ia: 0.3540 - val_loss: 0.7528 - val_mae: 0.6440 - val_rmse: 0.8057 - val_smape: 1.2955

Epoch 28/32

120/120 - 1s - 5ms/step - ia: 0.4048 - loss: 0.7888 - mae: 0.6509 - rmse: 0.8859 - smape: 1.2670 - val_ia: 0.3529 - val_loss: 0.7510 - val_mae: 0.6422 - val_rmse: 0.8034 - val_smape: 1.2957

Epoch 29/32

120/120 - 1s - 7ms/step - ia: 0.4064 - loss: 0.7843 - mae: 0.6499 - rmse: 0.8830 - smape: 1.2651 - val_ia: 0.3543 - val_loss: 0.7524 - val_mae: 0.6431 - val_rmse: 0.8047 - val_smape: 1.2941

Epoch 30/32

120/120 - 1s - 10ms/step - ia: 0.4082 - loss: 0.7836 - mae: 0.6491 - rmse: 0.8834 - smape: 1.2622 - val_ia: 0.3518 - val_loss: 0.7524 - val_mae: 0.6435 - val_rmse: 0.8045 - val_smape: 1.2932

Epoch 31/32

120/120 - 0s - 3ms/step - ia: 0.4062 - loss: 0.7840 - mae: 0.6492 - rmse: 0.8833 - smape: 1.2633 - val_ia: 0.3527 - val_loss: 0.7520 - val_mae: 0.6435 - val_rmse: 0.8043 - val_smape: 1.2921

Epoch 32/32

120/120 - 1s - 8ms/step - ia: 0.4101 - loss: 0.7820 - mae: 0.6481 - rmse: 0.8813 - smape: 1.2602 - val_ia: 0.3536 - val_loss: 0.7500 - val_mae: 0.6415 - val_rmse: 0.8028 - val_smape: 1.2903

Restoring model weights from the end of the best epoch: 23.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 37s 281ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 64%|██████▍   | 32/50 [2:25:22<1:58:43, 395.72s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 15s - 31ms/step - ia: 0.3896 - loss: 0.8334 - mae: 0.6715 - rmse: 0.9028 - smape: 1.2742 - val_ia: 0.2949 - val_loss: 0.7690 - val_mae: 0.6467 - val_rmse: 0.7774 - val_smape: 1.2340

Epoch 2/128

479/479 - 3s - 7ms/step - ia: 0.4126 - loss: 0.7933 - mae: 0.6526 - rmse: 0.8805 - smape: 1.2436 - val_ia: 0.2906 - val_loss: 0.7815 - val_mae: 0.6599 - val_rmse: 0.7887 - val_smape: 1.2980

Epoch 3/128

479/479 - 3s - 5ms/step - ia: 0.4215 - loss: 0.7789 - mae: 0.6448 - rmse: 0.8738 - smape: 1.2309 - val_ia: 0.2983 - val_loss: 0.7800 - val_mae: 0.6527 - val_rmse: 0.7870 - val_smape: 1.2647

Epoch 4/128

479/479 - 3s - 6ms/step - ia: 0.4310 - loss: 0.7660 - mae: 0.6383 - rmse: 0.8662 - smape: 1.2184 - val_ia: 0.2927 - val_loss: 0.7774 - val_mae: 0.6451 - val_rmse: 0.7785 - val_smape: 1.2343

Epoch 5/128

479/479 - 3s - 6ms/step - ia: 0.4370 - loss: 0.7563 - mae: 0.6331 - rmse: 0.8607 - smape: 1.2114 - val_ia: 0.2987 - val_loss: 0.7775 - val_mae: 0.6453 - val_rmse: 0.7819 - val_smape: 1.2351

Epoch 6/128

479/479 - 2s - 5ms/step - ia: 0.4427 - loss: 0.7484 - mae: 0.6298 - rmse: 0.8554 - smape: 1.2059 - val_ia: 0.2977 - val_loss: 0.8069 - val_mae: 0.6561 - val_rmse: 0.7968 - val_smape: 1.2387

Epoch 7/128

479/479 - 2s - 4ms/step - ia: 0.4475 - loss: 0.7380 - mae: 0.6254 - rmse: 0.8496 - smape: 1.1985 - val_ia: 0.2958 - val_loss: 0.7944 - val_mae: 0.6500 - val_rmse: 0.7891 - val_smape: 1.2227

Epoch 8/128

479/479 - 4s - 8ms/step - ia: 0.4509 - loss: 0.7317 - mae: 0.6223 - rmse: 0.8459 - smape: 1.1957 - val_ia: 0.2954 - val_loss: 0.7858 - val_mae: 0.6505 - val_rmse: 0.7884 - val_smape: 1.2287

Epoch 9/128

479/479 - 3s - 6ms/step - ia: 0.4541 - loss: 0.7285 - mae: 0.6204 - rmse: 0.8449 - smape: 1.1912 - val_ia: 0.2905 - val_loss: 0.8251 - val_mae: 0.6634 - val_rmse: 0.8028 - val_smape: 1.2464

Epoch 10/128

479/479 - 5s - 11ms/step - ia: 0.4586 - loss: 0.7195 - mae: 0.6176 - rmse: 0.8390 - smape: 1.1887 - val_ia: 0.3013 - val_loss: 0.7874 - val_mae: 0.6549 - val_rmse: 0.7925 - val_smape: 1.2630

Epoch 11/128

479/479 - 5s - 10ms/step - ia: 0.4627 - loss: 0.7129 - mae: 0.6141 - rmse: 0.8350 - smape: 1.1813 - val_ia: 0.2960 - val_loss: 0.8245 - val_mae: 0.6777 - val_rmse: 0.8157 - val_smape: 1.2951

Epoch 12/128

479/479 - 5s - 11ms/step - ia: 0.4634 - loss: 0.7067 - mae: 0.6125 - rmse: 0.8327 - smape: 1.1813 - val_ia: 0.3007 - val_loss: 0.8015 - val_mae: 0.6557 - val_rmse: 0.7969 - val_smape: 1.2529

Epoch 13/128

479/479 - 3s - 5ms/step - ia: 0.4689 - loss: 0.7022 - mae: 0.6104 - rmse: 0.8293 - smape: 1.1750 - val_ia: 0.2959 - val_loss: 0.8105 - val_mae: 0.6558 - val_rmse: 0.7958 - val_smape: 1.2351

Epoch 14/128

479/479 - 4s - 8ms/step - ia: 0.4712 - loss: 0.6938 - mae: 0.6074 - rmse: 0.8248 - smape: 1.1732 - val_ia: 0.2887 - val_loss: 0.8185 - val_mae: 0.6626 - val_rmse: 0.7984 - val_smape: 1.2652

Epoch 15/128

479/479 - 5s - 9ms/step - ia: 0.4744 - loss: 0.6914 - mae: 0.6054 - rmse: 0.8222 - smape: 1.1684 - val_ia: 0.2968 - val_loss: 0.8050 - val_mae: 0.6525 - val_rmse: 0.7942 - val_smape: 1.2289

Epoch 16/128

479/479 - 3s - 6ms/step - ia: 0.4756 - loss: 0.6861 - mae: 0.6039 - rmse: 0.8199 - smape: 1.1701 - val_ia: 0.2849 - val_loss: 0.8178 - val_mae: 0.6621 - val_rmse: 0.7962 - val_smape: 1.2804

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 40s 303ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 49/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 66%|██████▌   | 33/50 [2:26:32<1:24:24, 297.91s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

3830/3830 - 24s - 6ms/step - ia: 0.2929 - loss: 2.0156 - mae: 1.0517 - rmse: 1.3376 - smape: 1.3991 - val_ia: 0.1905 - val_loss: 0.9833 - val_mae: 0.7267 - val_rmse: 0.7764 - val_smape: 1.5193

Epoch 2/64

3830/3830 - 21s - 5ms/step - ia: 0.2939 - loss: 1.4171 - mae: 0.8916 - rmse: 1.1249 - smape: 1.4389 - val_ia: 0.1888 - val_loss: 0.9319 - val_mae: 0.7279 - val_rmse: 0.7715 - val_smape: 1.6190

Epoch 3/64

3830/3830 - 16s - 4ms/step - ia: 0.3000 - loss: 1.2086 - mae: 0.8272 - rmse: 1.0372 - smape: 1.4436 - val_ia: 0.1875 - val_loss: 0.9168 - val_mae: 0.7278 - val_rmse: 0.7688 - val_smape: 1.6509

Epoch 4/64

3830/3830 - 15s - 4ms/step - ia: 0.2960 - loss: 1.1102 - mae: 0.7940 - rmse: 0.9940 - smape: 1.4614 - val_ia: 0.1877 - val_loss: 0.9077 - val_mae: 0.7263 - val_rmse: 0.7662 - val_smape: 1.6651

Epoch 5/64

3830/3830 - 18s - 5ms/step - ia: 0.3019 - loss: 1.0584 - mae: 0.7726 - rmse: 0.9669 - smape: 1.4681 - val_ia: 0.1883 - val_loss: 0.8998 - val_mae: 0.7230 - val_rmse: 0.7623 - val_smape: 1.6625

Epoch 6/64

3830/3830 - 9s - 2ms/step - ia: 0.3036 - loss: 1.0138 - mae: 0.7535 - rmse: 0.9466 - smape: 1.4681 - val_ia: 0.1881 - val_loss: 0.8944 - val_mae: 0.7219 - val_rmse: 0.7608 - val_smape: 1.6667

Epoch 7/64

3830/3830 - 13s - 3ms/step - ia: 0.3033 - loss: 0.9986 - mae: 0.7497 - rmse: 0.9394 - smape: 1.4790 - val_ia: 0.1883 - val_loss: 0.8906 - val_mae: 0.7192 - val_rmse: 0.7578 - val_smape: 1.6625

Epoch 8/64

3830/3830 - 25s - 6ms/step - ia: 0.3029 - loss: 0.9805 - mae: 0.7400 - rmse: 0.9285 - smape: 1.4804 - val_ia: 0.1881 - val_loss: 0.8879 - val_mae: 0.7183 - val_rmse: 0.7566 - val_smape: 1.6647

Epoch 9/64

3830/3830 - 16s - 4ms/step - ia: 0.3015 - loss: 0.9653 - mae: 0.7354 - rmse: 0.9198 - smape: 1.4871 - val_ia: 0.1880 - val_loss: 0.8840 - val_mae: 0.7169 - val_rmse: 0.7550 - val_smape: 1.6620

Epoch 10/64

3830/3830 - 16s - 4ms/step - ia: 0.3068 - loss: 0.9503 - mae: 0.7281 - rmse: 0.9147 - smape: 1.4802 - val_ia: 0.1881 - val_loss: 0.8786 - val_mae: 0.7149 - val_rmse: 0.7530 - val_smape: 1.6548

Epoch 11/64

3830/3830 - 14s - 4ms/step - ia: 0.3125 - loss: 0.9380 - mae: 0.7219 - rmse: 0.9068 - smape: 1.4752 - val_ia: 0.1884 - val_loss: 0.8734 - val_mae: 0.7122 - val_rmse: 0.7503 - val_smape: 1.6443

Epoch 12/64

3830/3830 - 14s - 4ms/step - ia: 0.3180 - loss: 0.9351 - mae: 0.7188 - rmse: 0.9043 - smape: 1.4707 - val_ia: 0.1886 - val_loss: 0.8711 - val_mae: 0.7109 - val_rmse: 0.7488 - val_smape: 1.6403

Epoch 13/64

3830/3830 - 15s - 4ms/step - ia: 0.3131 - loss: 0.9276 - mae: 0.7172 - rmse: 0.9015 - smape: 1.4751 - val_ia: 0.1887 - val_loss: 0.8677 - val_mae: 0.7096 - val_rmse: 0.7475 - val_smape: 1.6354

Epoch 14/64

3830/3830 - 21s - 5ms/step - ia: 0.3180 - loss: 0.9227 - mae: 0.7135 - rmse: 0.8981 - smape: 1.4682 - val_ia: 0.1887 - val_loss: 0.8652 - val_mae: 0.7084 - val_rmse: 0.7463 - val_smape: 1.6314

Epoch 15/64

3830/3830 - 15s - 4ms/step - ia: 0.3188 - loss: 0.9142 - mae: 0.7114 - rmse: 0.8950 - smape: 1.4660 - val_ia: 0.1888 - val_loss: 0.8629 - val_mae: 0.7071 - val_rmse: 0.7449 - val_smape: 1.6245

Epoch 16/64

3830/3830 - 16s - 4ms/step - ia: 0.3239 - loss: 0.9017 - mae: 0.7067 - rmse: 0.8900 - smape: 1.4595 - val_ia: 0.1890 - val_loss: 0.8589 - val_mae: 0.7057 - val_rmse: 0.7435 - val_smape: 1.6191

Epoch 17/64

3830/3830 - 10s - 3ms/step - ia: 0.3257 - loss: 0.9044 - mae: 0.7046 - rmse: 0.8893 - smape: 1.4522 - val_ia: 0.1892 - val_loss: 0.8554 - val_mae: 0.7046 - val_rmse: 0.7423 - val_smape: 1.6126

Epoch 18/64

3830/3830 - 15s - 4ms/step - ia: 0.3260 - loss: 0.8953 - mae: 0.7042 - rmse: 0.8875 - smape: 1.4496 - val_ia: 0.1895 - val_loss: 0.8505 - val_mae: 0.7023 - val_rmse: 0.7400 - val_smape: 1.6010

Epoch 19/64

3830/3830 - 15s - 4ms/step - ia: 0.3278 - loss: 0.8970 - mae: 0.7032 - rmse: 0.8872 - smape: 1.4479 - val_ia: 0.1898 - val_loss: 0.8510 - val_mae: 0.7015 - val_rmse: 0.7391 - val_smape: 1.6000

Epoch 20/64

3830/3830 - 15s - 4ms/step - ia: 0.3260 - loss: 0.8953 - mae: 0.7021 - rmse: 0.8865 - smape: 1.4489 - val_ia: 0.1898 - val_loss: 0.8459 - val_mae: 0.7004 - val_rmse: 0.7380 - val_smape: 1.5925

Epoch 21/64

3830/3830 - 15s - 4ms/step - ia: 0.3315 - loss: 0.8874 - mae: 0.6992 - rmse: 0.8827 - smape: 1.4396 - val_ia: 0.1900 - val_loss: 0.8446 - val_mae: 0.6998 - val_rmse: 0.7373 - val_smape: 1.5893

Epoch 22/64

3830/3830 - 20s - 5ms/step - ia: 0.3288 - loss: 0.8875 - mae: 0.7003 - rmse: 0.8832 - smape: 1.4432 - val_ia: 0.1903 - val_loss: 0.8430 - val_mae: 0.6980 - val_rmse: 0.7353 - val_smape: 1.5825

Epoch 23/64

3830/3830 - 10s - 2ms/step - ia: 0.3328 - loss: 0.8853 - mae: 0.6980 - rmse: 0.8813 - smape: 1.4386 - val_ia: 0.1904 - val_loss: 0.8408 - val_mae: 0.6974 - val_rmse: 0.7347 - val_smape: 1.5787

Epoch 24/64

3830/3830 - 9s - 2ms/step - ia: 0.3347 - loss: 0.8779 - mae: 0.6956 - rmse: 0.8773 - smape: 1.4354 - val_ia: 0.1908 - val_loss: 0.8387 - val_mae: 0.6955 - val_rmse: 0.7328 - val_smape: 1.5713

Epoch 25/64

3830/3830 - 10s - 3ms/step - ia: 0.3369 - loss: 0.8796 - mae: 0.6949 - rmse: 0.8765 - smape: 1.4297 - val_ia: 0.1910 - val_loss: 0.8369 - val_mae: 0.6946 - val_rmse: 0.7319 - val_smape: 1.5675

Epoch 26/64

3830/3830 - 17s - 4ms/step - ia: 0.3375 - loss: 0.8748 - mae: 0.6929 - rmse: 0.8745 - smape: 1.4292 - val_ia: 0.1913 - val_loss: 0.8332 - val_mae: 0.6929 - val_rmse: 0.7301 - val_smape: 1.5576

Epoch 27/64

3830/3830 - 21s - 6ms/step - ia: 0.3402 - loss: 0.8776 - mae: 0.6923 - rmse: 0.8745 - smape: 1.4228 - val_ia: 0.1911 - val_loss: 0.8314 - val_mae: 0.6928 - val_rmse: 0.7300 - val_smape: 1.5581

Epoch 28/64

3830/3830 - 17s - 5ms/step - ia: 0.3373 - loss: 0.8703 - mae: 0.6914 - rmse: 0.8739 - smape: 1.4196 - val_ia: 0.1913 - val_loss: 0.8292 - val_mae: 0.6916 - val_rmse: 0.7287 - val_smape: 1.5499

Epoch 29/64

3830/3830 - 18s - 5ms/step - ia: 0.3422 - loss: 0.8708 - mae: 0.6905 - rmse: 0.8739 - smape: 1.4168 - val_ia: 0.1913 - val_loss: 0.8288 - val_mae: 0.6910 - val_rmse: 0.7280 - val_smape: 1.5477

Epoch 30/64

3830/3830 - 10s - 3ms/step - ia: 0.3432 - loss: 0.8647 - mae: 0.6896 - rmse: 0.8703 - smape: 1.4185 - val_ia: 0.1917 - val_loss: 0.8238 - val_mae: 0.6893 - val_rmse: 0.7265 - val_smape: 1.5393

Epoch 31/64

3830/3830 - 16s - 4ms/step - ia: 0.3451 - loss: 0.8657 - mae: 0.6877 - rmse: 0.8701 - smape: 1.4074 - val_ia: 0.1917 - val_loss: 0.8236 - val_mae: 0.6892 - val_rmse: 0.7263 - val_smape: 1.5390

Epoch 32/64

3830/3830 - 16s - 4ms/step - ia: 0.3474 - loss: 0.8614 - mae: 0.6861 - rmse: 0.8676 - smape: 1.4048 - val_ia: 0.1923 - val_loss: 0.8211 - val_mae: 0.6867 - val_rmse: 0.7238 - val_smape: 1.5276

Epoch 33/64

3830/3830 - 16s - 4ms/step - ia: 0.3447 - loss: 0.8672 - mae: 0.6890 - rmse: 0.8709 - smape: 1.4114 - val_ia: 0.1923 - val_loss: 0.8202 - val_mae: 0.6861 - val_rmse: 0.7232 - val_smape: 1.5262

Epoch 34/64

3830/3830 - 25s - 7ms/step - ia: 0.3496 - loss: 0.8571 - mae: 0.6842 - rmse: 0.8655 - smape: 1.3999 - val_ia: 0.1926 - val_loss: 0.8177 - val_mae: 0.6846 - val_rmse: 0.7217 - val_smape: 1.5198

Epoch 35/64

3830/3830 - 22s - 6ms/step - ia: 0.3453 - loss: 0.8541 - mae: 0.6849 - rmse: 0.8646 - smape: 1.4067 - val_ia: 0.1927 - val_loss: 0.8145 - val_mae: 0.6843 - val_rmse: 0.7214 - val_smape: 1.5154

Epoch 36/64

3830/3830 - 17s - 4ms/step - ia: 0.3475 - loss: 0.8608 - mae: 0.6880 - rmse: 0.8682 - smape: 1.4024 - val_ia: 0.1924 - val_loss: 0.8137 - val_mae: 0.6849 - val_rmse: 0.7219 - val_smape: 1.5188

Epoch 37/64

3830/3830 - 16s - 4ms/step - ia: 0.3507 - loss: 0.8576 - mae: 0.6833 - rmse: 0.8663 - smape: 1.3948 - val_ia: 0.1931 - val_loss: 0.8104 - val_mae: 0.6825 - val_rmse: 0.7196 - val_smape: 1.5069

Epoch 38/64

3830/3830 - 16s - 4ms/step - ia: 0.3508 - loss: 0.8607 - mae: 0.6844 - rmse: 0.8680 - smape: 1.3948 - val_ia: 0.1930 - val_loss: 0.8110 - val_mae: 0.6824 - val_rmse: 0.7194 - val_smape: 1.5086

Epoch 39/64

3830/3830 - 16s - 4ms/step - ia: 0.3481 - loss: 0.8547 - mae: 0.6843 - rmse: 0.8647 - smape: 1.3961 - val_ia: 0.1932 - val_loss: 0.8100 - val_mae: 0.6818 - val_rmse: 0.7188 - val_smape: 1.5048

Epoch 40/64

3830/3830 - 20s - 5ms/step - ia: 0.3519 - loss: 0.8526 - mae: 0.6830 - rmse: 0.8639 - smape: 1.3903 - val_ia: 0.1935 - val_loss: 0.8072 - val_mae: 0.6809 - val_rmse: 0.7180 - val_smape: 1.5007

Epoch 41/64

3830/3830 - 17s - 4ms/step - ia: 0.3517 - loss: 0.8547 - mae: 0.6831 - rmse: 0.8654 - smape: 1.3902 - val_ia: 0.1936 - val_loss: 0.8067 - val_mae: 0.6803 - val_rmse: 0.7173 - val_smape: 1.4990

Epoch 42/64

3830/3830 - 15s - 4ms/step - ia: 0.3495 - loss: 0.8583 - mae: 0.6843 - rmse: 0.8660 - smape: 1.3935 - val_ia: 0.1936 - val_loss: 0.8074 - val_mae: 0.6800 - val_rmse: 0.7170 - val_smape: 1.4990

Epoch 43/64

3830/3830 - 14s - 4ms/step - ia: 0.3532 - loss: 0.8476 - mae: 0.6798 - rmse: 0.8619 - smape: 1.3858 - val_ia: 0.1943 - val_loss: 0.8034 - val_mae: 0.6787 - val_rmse: 0.7158 - val_smape: 1.4899

Epoch 44/64

3830/3830 - 24s - 6ms/step - ia: 0.3542 - loss: 0.8501 - mae: 0.6820 - rmse: 0.8631 - smape: 1.3850 - val_ia: 0.1941 - val_loss: 0.8043 - val_mae: 0.6792 - val_rmse: 0.7162 - val_smape: 1.4933

Epoch 45/64

3830/3830 - 18s - 5ms/step - ia: 0.3538 - loss: 0.8561 - mae: 0.6818 - rmse: 0.8653 - smape: 1.3830 - val_ia: 0.1947 - val_loss: 0.8039 - val_mae: 0.6771 - val_rmse: 0.7142 - val_smape: 1.4857

Epoch 46/64

3830/3830 - 19s - 5ms/step - ia: 0.3553 - loss: 0.8495 - mae: 0.6805 - rmse: 0.8611 - smape: 1.3825 - val_ia: 0.1946 - val_loss: 0.8025 - val_mae: 0.6771 - val_rmse: 0.7141 - val_smape: 1.4840

Epoch 47/64

3830/3830 - 22s - 6ms/step - ia: 0.3546 - loss: 0.8429 - mae: 0.6784 - rmse: 0.8597 - smape: 1.3802 - val_ia: 0.1946 - val_loss: 0.8011 - val_mae: 0.6772 - val_rmse: 0.7142 - val_smape: 1.4824

Epoch 48/64

3830/3830 - 15s - 4ms/step - ia: 0.3547 - loss: 0.8515 - mae: 0.6812 - rmse: 0.8631 - smape: 1.3795 - val_ia: 0.1948 - val_loss: 0.8002 - val_mae: 0.6763 - val_rmse: 0.7133 - val_smape: 1.4793

Epoch 49/64

3830/3830 - 13s - 4ms/step - ia: 0.3553 - loss: 0.8469 - mae: 0.6796 - rmse: 0.8620 - smape: 1.3794 - val_ia: 0.1950 - val_loss: 0.7984 - val_mae: 0.6756 - val_rmse: 0.7127 - val_smape: 1.4763

Epoch 50/64

3830/3830 - 18s - 5ms/step - ia: 0.3574 - loss: 0.8470 - mae: 0.6797 - rmse: 0.8611 - smape: 1.3746 - val_ia: 0.1951 - val_loss: 0.7971 - val_mae: 0.6750 - val_rmse: 0.7121 - val_smape: 1.4734

Epoch 51/64

3830/3830 - 11s - 3ms/step - ia: 0.3570 - loss: 0.8492 - mae: 0.6800 - rmse: 0.8616 - smape: 1.3787 - val_ia: 0.1951 - val_loss: 0.7970 - val_mae: 0.6746 - val_rmse: 0.7116 - val_smape: 1.4716

Epoch 52/64

3830/3830 - 15s - 4ms/step - ia: 0.3572 - loss: 0.8425 - mae: 0.6779 - rmse: 0.8594 - smape: 1.3763 - val_ia: 0.1953 - val_loss: 0.7953 - val_mae: 0.6739 - val_rmse: 0.7110 - val_smape: 1.4669

Epoch 53/64

3830/3830 - 16s - 4ms/step - ia: 0.3583 - loss: 0.8437 - mae: 0.6787 - rmse: 0.8595 - smape: 1.3717 - val_ia: 0.1952 - val_loss: 0.7954 - val_mae: 0.6742 - val_rmse: 0.7113 - val_smape: 1.4688

Epoch 54/64

3830/3830 - 21s - 5ms/step - ia: 0.3586 - loss: 0.8431 - mae: 0.6787 - rmse: 0.8592 - smape: 1.3715 - val_ia: 0.1954 - val_loss: 0.7956 - val_mae: 0.6734 - val_rmse: 0.7105 - val_smape: 1.4663

Epoch 55/64

3830/3830 - 15s - 4ms/step - ia: 0.3589 - loss: 0.8465 - mae: 0.6766 - rmse: 0.8598 - smape: 1.3688 - val_ia: 0.1952 - val_loss: 0.7970 - val_mae: 0.6742 - val_rmse: 0.7112 - val_smape: 1.4699

Epoch 56/64

3830/3830 - 16s - 4ms/step - ia: 0.3583 - loss: 0.8458 - mae: 0.6782 - rmse: 0.8608 - smape: 1.3718 - val_ia: 0.1954 - val_loss: 0.7953 - val_mae: 0.6736 - val_rmse: 0.7106 - val_smape: 1.4669

Epoch 57/64

3830/3830 - 14s - 4ms/step - ia: 0.3568 - loss: 0.8446 - mae: 0.6785 - rmse: 0.8599 - smape: 1.3740 - val_ia: 0.1958 - val_loss: 0.7933 - val_mae: 0.6723 - val_rmse: 0.7094 - val_smape: 1.4606

Epoch 58/64

3830/3830 - 13s - 3ms/step - ia: 0.3581 - loss: 0.8440 - mae: 0.6777 - rmse: 0.8589 - smape: 1.3677 - val_ia: 0.1958 - val_loss: 0.7932 - val_mae: 0.6724 - val_rmse: 0.7095 - val_smape: 1.4611

Epoch 59/64

3830/3830 - 11s - 3ms/step - ia: 0.3615 - loss: 0.8406 - mae: 0.6760 - rmse: 0.8575 - smape: 1.3665 - val_ia: 0.1958 - val_loss: 0.7906 - val_mae: 0.6720 - val_rmse: 0.7090 - val_smape: 1.4587

Epoch 60/64

3830/3830 - 10s - 3ms/step - ia: 0.3585 - loss: 0.8458 - mae: 0.6780 - rmse: 0.8605 - smape: 1.3677 - val_ia: 0.1963 - val_loss: 0.7898 - val_mae: 0.6709 - val_rmse: 0.7080 - val_smape: 1.4529

Epoch 61/64

3830/3830 - 14s - 4ms/step - ia: 0.3627 - loss: 0.8339 - mae: 0.6732 - rmse: 0.8549 - smape: 1.3572 - val_ia: 0.1963 - val_loss: 0.7882 - val_mae: 0.6709 - val_rmse: 0.7081 - val_smape: 1.4522

Epoch 62/64

3830/3830 - 16s - 4ms/step - ia: 0.3633 - loss: 0.8366 - mae: 0.6753 - rmse: 0.8571 - smape: 1.3576 - val_ia: 0.1963 - val_loss: 0.7889 - val_mae: 0.6706 - val_rmse: 0.7077 - val_smape: 1.4511

Epoch 63/64

3830/3830 - 13s - 3ms/step - ia: 0.3617 - loss: 0.8359 - mae: 0.6746 - rmse: 0.8558 - smape: 1.3610 - val_ia: 0.1965 - val_loss: 0.7871 - val_mae: 0.6699 - val_rmse: 0.7071 - val_smape: 1.4458

Epoch 64/64

3830/3830 - 16s - 4ms/step - ia: 0.3625 - loss: 0.8366 - mae: 0.6747 - rmse: 0.8559 - smape: 1.3602 - val_ia: 0.1968 - val_loss: 0.7858 - val_mae: 0.6691 - val_rmse: 0.7063 - val_smape: 1.4425

Restoring model weights from the end of the best epoch: 64.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:51 823ms/step
  2/136 ━━━━━━━━━━━━━━━━━━━━ 9s 70ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 84/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 68%|██████▊   | 34/50 [2:43:40<2:17:55, 517.21s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

958/958 - 9s - 10ms/step - ia: 0.2156 - loss: 1.0276 - mae: 0.7192 - rmse: 0.9853 - smape: 1.4144 - val_ia: 0.2368 - val_loss: 0.9579 - val_mae: 0.7124 - val_rmse: 0.7984 - val_smape: 1.6075

Epoch 2/32

958/958 - 6s - 6ms/step - ia: 0.1595 - loss: 0.9842 - mae: 0.7333 - rmse: 0.9684 - smape: 1.7398 - val_ia: 0.2344 - val_loss: 0.9447 - val_mae: 0.7238 - val_rmse: 0.8081 - val_smape: 1.8129

Epoch 3/32

958/958 - 5s - 5ms/step - ia: 0.1557 - loss: 0.9688 - mae: 0.7345 - rmse: 0.9594 - smape: 1.7834 - val_ia: 0.2348 - val_loss: 0.9294 - val_mae: 0.7196 - val_rmse: 0.8036 - val_smape: 1.7576

Epoch 4/32

958/958 - 5s - 5ms/step - ia: 0.1719 - loss: 0.9534 - mae: 0.7282 - rmse: 0.9545 - smape: 1.7126 - val_ia: 0.2355 - val_loss: 0.9131 - val_mae: 0.7136 - val_rmse: 0.7974 - val_smape: 1.6881

Epoch 5/32

958/958 - 5s - 5ms/step - ia: 0.1832 - loss: 0.9379 - mae: 0.7214 - rmse: 0.9466 - smape: 1.6427 - val_ia: 0.2375 - val_loss: 0.8974 - val_mae: 0.7073 - val_rmse: 0.7914 - val_smape: 1.6215

Epoch 6/32

958/958 - 5s - 6ms/step - ia: 0.2043 - loss: 0.9228 - mae: 0.7149 - rmse: 0.9398 - smape: 1.5787 - val_ia: 0.2398 - val_loss: 0.8812 - val_mae: 0.6989 - val_rmse: 0.7834 - val_smape: 1.5507

Epoch 7/32

958/958 - 5s - 6ms/step - ia: 0.2260 - loss: 0.9088 - mae: 0.7085 - rmse: 0.9315 - smape: 1.5224 - val_ia: 0.2422 - val_loss: 0.8668 - val_mae: 0.6906 - val_rmse: 0.7759 - val_smape: 1.4880

Epoch 8/32

958/958 - 5s - 5ms/step - ia: 0.2472 - loss: 0.8964 - mae: 0.7013 - rmse: 0.9253 - smape: 1.4690 - val_ia: 0.2444 - val_loss: 0.8557 - val_mae: 0.6875 - val_rmse: 0.7735 - val_smape: 1.4512

Epoch 9/32

958/958 - 5s - 6ms/step - ia: 0.2668 - loss: 0.8858 - mae: 0.6972 - rmse: 0.9203 - smape: 1.4294 - val_ia: 0.2467 - val_loss: 0.8448 - val_mae: 0.6807 - val_rmse: 0.7675 - val_smape: 1.4055

Epoch 10/32

958/958 - 6s - 7ms/step - ia: 0.2853 - loss: 0.8768 - mae: 0.6920 - rmse: 0.9145 - smape: 1.3924 - val_ia: 0.2480 - val_loss: 0.8357 - val_mae: 0.6764 - val_rmse: 0.7641 - val_smape: 1.3735

Epoch 11/32

958/958 - 4s - 4ms/step - ia: 0.3014 - loss: 0.8694 - mae: 0.6878 - rmse: 0.9100 - smape: 1.3627 - val_ia: 0.2492 - val_loss: 0.8286 - val_mae: 0.6741 - val_rmse: 0.7625 - val_smape: 1.3511

Epoch 12/32

958/958 - 6s - 6ms/step - ia: 0.3153 - loss: 0.8632 - mae: 0.6853 - rmse: 0.9080 - smape: 1.3416 - val_ia: 0.2511 - val_loss: 0.8217 - val_mae: 0.6691 - val_rmse: 0.7584 - val_smape: 1.3242

Epoch 13/32

958/958 - 4s - 4ms/step - ia: 0.3255 - loss: 0.8580 - mae: 0.6822 - rmse: 0.9060 - smape: 1.3213 - val_ia: 0.2523 - val_loss: 0.8165 - val_mae: 0.6668 - val_rmse: 0.7568 - val_smape: 1.3078

Epoch 14/32

958/958 - 4s - 4ms/step - ia: 0.3369 - loss: 0.8536 - mae: 0.6797 - rmse: 0.9034 - smape: 1.3050 - val_ia: 0.2535 - val_loss: 0.8119 - val_mae: 0.6646 - val_rmse: 0.7553 - val_smape: 1.2943

Epoch 15/32

958/958 - 3s - 4ms/step - ia: 0.3447 - loss: 0.8499 - mae: 0.6780 - rmse: 0.9015 - smape: 1.2928 - val_ia: 0.2544 - val_loss: 0.8078 - val_mae: 0.6622 - val_rmse: 0.7534 - val_smape: 1.2819

Epoch 16/32

958/958 - 4s - 4ms/step - ia: 0.3513 - loss: 0.8467 - mae: 0.6759 - rmse: 0.9015 - smape: 1.2828 - val_ia: 0.2550 - val_loss: 0.8047 - val_mae: 0.6615 - val_rmse: 0.7531 - val_smape: 1.2755

Epoch 17/32

958/958 - 5s - 5ms/step - ia: 0.3567 - loss: 0.8439 - mae: 0.6748 - rmse: 0.8987 - smape: 1.2757 - val_ia: 0.2559 - val_loss: 0.8003 - val_mae: 0.6588 - val_rmse: 0.7508 - val_smape: 1.2649

Epoch 18/32

958/958 - 5s - 5ms/step - ia: 0.3611 - loss: 0.8413 - mae: 0.6736 - rmse: 0.8971 - smape: 1.2697 - val_ia: 0.2564 - val_loss: 0.7971 - val_mae: 0.6569 - val_rmse: 0.7492 - val_smape: 1.2578

Epoch 19/32

958/958 - 4s - 4ms/step - ia: 0.3660 - loss: 0.8390 - mae: 0.6719 - rmse: 0.8969 - smape: 1.2635 - val_ia: 0.2568 - val_loss: 0.7953 - val_mae: 0.6570 - val_rmse: 0.7496 - val_smape: 1.2573

Epoch 20/32

958/958 - 3s - 3ms/step - ia: 0.3693 - loss: 0.8370 - mae: 0.6713 - rmse: 0.8947 - smape: 1.2608 - val_ia: 0.2573 - val_loss: 0.7927 - val_mae: 0.6554 - val_rmse: 0.7482 - val_smape: 1.2523

Epoch 21/32

958/958 - 3s - 4ms/step - ia: 0.3718 - loss: 0.8351 - mae: 0.6706 - rmse: 0.8941 - smape: 1.2580 - val_ia: 0.2576 - val_loss: 0.7908 - val_mae: 0.6546 - val_rmse: 0.7476 - val_smape: 1.2498

Epoch 22/32

958/958 - 4s - 4ms/step - ia: 0.3732 - loss: 0.8333 - mae: 0.6693 - rmse: 0.8927 - smape: 1.2550 - val_ia: 0.2579 - val_loss: 0.7893 - val_mae: 0.6544 - val_rmse: 0.7476 - val_smape: 1.2487

Epoch 23/32

958/958 - 4s - 5ms/step - ia: 0.3745 - loss: 0.8316 - mae: 0.6689 - rmse: 0.8925 - smape: 1.2543 - val_ia: 0.2583 - val_loss: 0.7870 - val_mae: 0.6532 - val_rmse: 0.7465 - val_smape: 1.2455

Epoch 24/32

958/958 - 4s - 4ms/step - ia: 0.3767 - loss: 0.8300 - mae: 0.6680 - rmse: 0.8920 - smape: 1.2532 - val_ia: 0.2585 - val_loss: 0.7860 - val_mae: 0.6531 - val_rmse: 0.7466 - val_smape: 1.2456

Epoch 25/32

958/958 - 3s - 3ms/step - ia: 0.3782 - loss: 0.8285 - mae: 0.6677 - rmse: 0.8914 - smape: 1.2520 - val_ia: 0.2589 - val_loss: 0.7840 - val_mae: 0.6521 - val_rmse: 0.7457 - val_smape: 1.2430

Epoch 26/32

958/958 - 5s - 5ms/step - ia: 0.3794 - loss: 0.8270 - mae: 0.6668 - rmse: 0.8910 - smape: 1.2510 - val_ia: 0.2593 - val_loss: 0.7825 - val_mae: 0.6518 - val_rmse: 0.7456 - val_smape: 1.2425

Epoch 27/32

958/958 - 2s - 2ms/step - ia: 0.3797 - loss: 0.8256 - mae: 0.6667 - rmse: 0.8902 - smape: 1.2520 - val_ia: 0.2598 - val_loss: 0.7803 - val_mae: 0.6500 - val_rmse: 0.7439 - val_smape: 1.2381

Epoch 28/32

958/958 - 3s - 3ms/step - ia: 0.3814 - loss: 0.8242 - mae: 0.6662 - rmse: 0.8894 - smape: 1.2505 - val_ia: 0.2599 - val_loss: 0.7800 - val_mae: 0.6498 - val_rmse: 0.7438 - val_smape: 1.2385

Epoch 29/32

958/958 - 3s - 3ms/step - ia: 0.3832 - loss: 0.8229 - mae: 0.6653 - rmse: 0.8891 - smape: 1.2495 - val_ia: 0.2603 - val_loss: 0.7784 - val_mae: 0.6495 - val_rmse: 0.7436 - val_smape: 1.2385

Epoch 30/32

958/958 - 7s - 7ms/step - ia: 0.3842 - loss: 0.8216 - mae: 0.6649 - rmse: 0.8875 - smape: 1.2495 - val_ia: 0.2605 - val_loss: 0.7776 - val_mae: 0.6493 - val_rmse: 0.7436 - val_smape: 1.2389

Epoch 31/32

958/958 - 4s - 4ms/step - ia: 0.3836 - loss: 0.8204 - mae: 0.6647 - rmse: 0.8859 - smape: 1.2505 - val_ia: 0.2609 - val_loss: 0.7755 - val_mae: 0.6481 - val_rmse: 0.7424 - val_smape: 1.2361

Epoch 32/32

958/958 - 4s - 4ms/step - ia: 0.3831 - loss: 0.8192 - mae: 0.6638 - rmse: 0.8858 - smape: 1.2498 - val_ia: 0.2613 - val_loss: 0.7744 - val_mae: 0.6482 - val_rmse: 0.7426 - val_smape: 1.2367

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 46s 345ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 41/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 99/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 70%|███████   | 35/50 [2:46:10<1:41:41, 406.77s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 12s - 6ms/step - ia: 0.3188 - loss: 1.0156 - mae: 0.7547 - rmse: 0.9731 - smape: 1.4223 - val_ia: 0.2363 - val_loss: 0.8083 - val_mae: 0.6788 - val_rmse: 0.7432 - val_smape: 1.4450

Epoch 2/128

1915/1915 - 11s - 6ms/step - ia: 0.3407 - loss: 0.8797 - mae: 0.6986 - rmse: 0.9053 - smape: 1.3978 - val_ia: 0.2386 - val_loss: 0.7850 - val_mae: 0.6653 - val_rmse: 0.7295 - val_smape: 1.3927

Epoch 3/128

1915/1915 - 9s - 5ms/step - ia: 0.3607 - loss: 0.8474 - mae: 0.6816 - rmse: 0.8880 - smape: 1.3537 - val_ia: 0.2401 - val_loss: 0.7724 - val_mae: 0.6587 - val_rmse: 0.7226 - val_smape: 1.3680

Epoch 4/128

1915/1915 - 9s - 4ms/step - ia: 0.3703 - loss: 0.8311 - mae: 0.6723 - rmse: 0.8768 - smape: 1.3315 - val_ia: 0.2419 - val_loss: 0.7629 - val_mae: 0.6566 - val_rmse: 0.7207 - val_smape: 1.3564

Epoch 5/128

1915/1915 - 8s - 4ms/step - ia: 0.3795 - loss: 0.8206 - mae: 0.6664 - rmse: 0.8720 - smape: 1.3139 - val_ia: 0.2433 - val_loss: 0.7571 - val_mae: 0.6500 - val_rmse: 0.7142 - val_smape: 1.3391

Epoch 6/128

1915/1915 - 5s - 3ms/step - ia: 0.3792 - loss: 0.8187 - mae: 0.6649 - rmse: 0.8722 - smape: 1.3109 - val_ia: 0.2456 - val_loss: 0.7508 - val_mae: 0.6450 - val_rmse: 0.7104 - val_smape: 1.3179

Epoch 7/128

1915/1915 - 6s - 3ms/step - ia: 0.3864 - loss: 0.8087 - mae: 0.6605 - rmse: 0.8672 - smape: 1.2990 - val_ia: 0.2448 - val_loss: 0.7516 - val_mae: 0.6458 - val_rmse: 0.7112 - val_smape: 1.3189

Epoch 8/128

1915/1915 - 12s - 6ms/step - ia: 0.3904 - loss: 0.8036 - mae: 0.6584 - rmse: 0.8637 - smape: 1.2900 - val_ia: 0.2452 - val_loss: 0.7490 - val_mae: 0.6471 - val_rmse: 0.7123 - val_smape: 1.3236

Epoch 9/128

1915/1915 - 13s - 7ms/step - ia: 0.3888 - loss: 0.8037 - mae: 0.6588 - rmse: 0.8628 - smape: 1.2939 - val_ia: 0.2450 - val_loss: 0.7498 - val_mae: 0.6463 - val_rmse: 0.7114 - val_smape: 1.3247

Epoch 10/128

1915/1915 - 9s - 5ms/step - ia: 0.3927 - loss: 0.7922 - mae: 0.6542 - rmse: 0.8585 - smape: 1.2845 - val_ia: 0.2474 - val_loss: 0.7476 - val_mae: 0.6440 - val_rmse: 0.7118 - val_smape: 1.2916

Epoch 11/128

1915/1915 - 7s - 3ms/step - ia: 0.3960 - loss: 0.7940 - mae: 0.6545 - rmse: 0.8575 - smape: 1.2804 - val_ia: 0.2453 - val_loss: 0.7482 - val_mae: 0.6432 - val_rmse: 0.7098 - val_smape: 1.3103

Epoch 12/128

1915/1915 - 5s - 3ms/step - ia: 0.3959 - loss: 0.7940 - mae: 0.6545 - rmse: 0.8605 - smape: 1.2794 - val_ia: 0.2440 - val_loss: 0.7505 - val_mae: 0.6445 - val_rmse: 0.7093 - val_smape: 1.3192

Epoch 13/128

1915/1915 - 4s - 2ms/step - ia: 0.3973 - loss: 0.7919 - mae: 0.6525 - rmse: 0.8581 - smape: 1.2740 - val_ia: 0.2432 - val_loss: 0.7514 - val_mae: 0.6482 - val_rmse: 0.7139 - val_smape: 1.3256

Epoch 14/128

1915/1915 - 5s - 3ms/step - ia: 0.4001 - loss: 0.7912 - mae: 0.6512 - rmse: 0.8568 - smape: 1.2706 - val_ia: 0.2446 - val_loss: 0.7542 - val_mae: 0.6467 - val_rmse: 0.7146 - val_smape: 1.3085

Epoch 15/128

1915/1915 - 10s - 5ms/step - ia: 0.4016 - loss: 0.7876 - mae: 0.6513 - rmse: 0.8550 - smape: 1.2679 - val_ia: 0.2480 - val_loss: 0.7446 - val_mae: 0.6378 - val_rmse: 0.7049 - val_smape: 1.2855

Epoch 16/128

1915/1915 - 13s - 7ms/step - ia: 0.4014 - loss: 0.7872 - mae: 0.6489 - rmse: 0.8550 - smape: 1.2630 - val_ia: 0.2446 - val_loss: 0.7509 - val_mae: 0.6472 - val_rmse: 0.7131 - val_smape: 1.3285

Epoch 17/128

1915/1915 - 10s - 5ms/step - ia: 0.4041 - loss: 0.7823 - mae: 0.6471 - rmse: 0.8521 - smape: 1.2626 - val_ia: 0.2462 - val_loss: 0.7490 - val_mae: 0.6444 - val_rmse: 0.7125 - val_smape: 1.3031

Epoch 18/128

1915/1915 - 14s - 7ms/step - ia: 0.4061 - loss: 0.7819 - mae: 0.6474 - rmse: 0.8524 - smape: 1.2614 - val_ia: 0.2477 - val_loss: 0.7425 - val_mae: 0.6404 - val_rmse: 0.7084 - val_smape: 1.2919

Epoch 19/128

1915/1915 - 18s - 9ms/step - ia: 0.4050 - loss: 0.7814 - mae: 0.6472 - rmse: 0.8504 - smape: 1.2611 - val_ia: 0.2444 - val_loss: 0.7468 - val_mae: 0.6447 - val_rmse: 0.7116 - val_smape: 1.3150

Epoch 20/128

1915/1915 - 6s - 3ms/step - ia: 0.4064 - loss: 0.7801 - mae: 0.6477 - rmse: 0.8510 - smape: 1.2619 - val_ia: 0.2443 - val_loss: 0.7515 - val_mae: 0.6459 - val_rmse: 0.7137 - val_smape: 1.3094

Epoch 21/128

1915/1915 - 5s - 3ms/step - ia: 0.4065 - loss: 0.7780 - mae: 0.6467 - rmse: 0.8488 - smape: 1.2623 - val_ia: 0.2457 - val_loss: 0.7488 - val_mae: 0.6418 - val_rmse: 0.7097 - val_smape: 1.3012

Epoch 22/128

1915/1915 - 5s - 3ms/step - ia: 0.4053 - loss: 0.7773 - mae: 0.6462 - rmse: 0.8500 - smape: 1.2585 - val_ia: 0.2485 - val_loss: 0.7449 - val_mae: 0.6385 - val_rmse: 0.7073 - val_smape: 1.2836

Epoch 23/128

1915/1915 - 6s - 3ms/step - ia: 0.4095 - loss: 0.7748 - mae: 0.6452 - rmse: 0.8488 - smape: 1.2548 - val_ia: 0.2451 - val_loss: 0.7486 - val_mae: 0.6455 - val_rmse: 0.7120 - val_smape: 1.3208

Epoch 24/128

1915/1915 - 15s - 8ms/step - ia: 0.4083 - loss: 0.7711 - mae: 0.6443 - rmse: 0.8457 - smape: 1.2609 - val_ia: 0.2464 - val_loss: 0.7490 - val_mae: 0.6420 - val_rmse: 0.7105 - val_smape: 1.2984

Epoch 25/128

1915/1915 - 16s - 8ms/step - ia: 0.4092 - loss: 0.7703 - mae: 0.6430 - rmse: 0.8454 - smape: 1.2559 - val_ia: 0.2446 - val_loss: 0.7514 - val_mae: 0.6449 - val_rmse: 0.7139 - val_smape: 1.3149

Epoch 26/128

1915/1915 - 4s - 2ms/step - ia: 0.4097 - loss: 0.7732 - mae: 0.6446 - rmse: 0.8473 - smape: 1.2566 - val_ia: 0.2456 - val_loss: 0.7535 - val_mae: 0.6428 - val_rmse: 0.7124 - val_smape: 1.2988

Epoch 27/128

1915/1915 - 6s - 3ms/step - ia: 0.4103 - loss: 0.7728 - mae: 0.6428 - rmse: 0.8477 - smape: 1.2545 - val_ia: 0.2478 - val_loss: 0.7474 - val_mae: 0.6414 - val_rmse: 0.7108 - val_smape: 1.3012

Epoch 28/128

1915/1915 - 5s - 3ms/step - ia: 0.4100 - loss: 0.7721 - mae: 0.6434 - rmse: 0.8467 - smape: 1.2582 - val_ia: 0.2459 - val_loss: 0.7482 - val_mae: 0.6455 - val_rmse: 0.7128 - val_smape: 1.3218

Epoch 29/128

1915/1915 - 5s - 3ms/step - ia: 0.4126 - loss: 0.7656 - mae: 0.6415 - rmse: 0.8423 - smape: 1.2516 - val_ia: 0.2451 - val_loss: 0.7493 - val_mae: 0.6424 - val_rmse: 0.7105 - val_smape: 1.3099

Epoch 30/128

1915/1915 - 4s - 2ms/step - ia: 0.4121 - loss: 0.7679 - mae: 0.6418 - rmse: 0.8439 - smape: 1.2577 - val_ia: 0.2499 - val_loss: 0.7436 - val_mae: 0.6379 - val_rmse: 0.7065 - val_smape: 1.2904

Epoch 31/128

1915/1915 - 5s - 2ms/step - ia: 0.4129 - loss: 0.7661 - mae: 0.6407 - rmse: 0.8422 - smape: 1.2523 - val_ia: 0.2477 - val_loss: 0.7449 - val_mae: 0.6396 - val_rmse: 0.7087 - val_smape: 1.2980

Epoch 32/128

1915/1915 - 7s - 4ms/step - ia: 0.4124 - loss: 0.7654 - mae: 0.6416 - rmse: 0.8432 - smape: 1.2578 - val_ia: 0.2486 - val_loss: 0.7446 - val_mae: 0.6389 - val_rmse: 0.7076 - val_smape: 1.2940

Epoch 33/128

1915/1915 - 11s - 6ms/step - ia: 0.4131 - loss: 0.7633 - mae: 0.6403 - rmse: 0.8406 - smape: 1.2531 - val_ia: 0.2476 - val_loss: 0.7460 - val_mae: 0.6382 - val_rmse: 0.7067 - val_smape: 1.2941

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:08 505ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 72%|███████▏  | 36/50 [2:50:57<1:26:31, 370.85s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

120/120 - 9s - 73ms/step - ia: 0.3512 - loss: 1.1664 - mae: 0.7689 - rmse: 1.0741 - smape: 1.3021 - val_ia: 0.3226 - val_loss: 0.8992 - val_mae: 0.6692 - val_rmse: 0.8605 - val_smape: 1.2309

Epoch 2/256

120/120 - 1s - 6ms/step - ia: 0.3604 - loss: 0.9775 - mae: 0.7257 - rmse: 0.9860 - smape: 1.3170 - val_ia: 0.3277 - val_loss: 0.8224 - val_mae: 0.6581 - val_rmse: 0.8306 - val_smape: 1.2733

Epoch 3/256

120/120 - 1s - 6ms/step - ia: 0.3672 - loss: 0.9264 - mae: 0.7141 - rmse: 0.9606 - smape: 1.3169 - val_ia: 0.3300 - val_loss: 0.7986 - val_mae: 0.6589 - val_rmse: 0.8233 - val_smape: 1.2997

Epoch 4/256

120/120 - 1s - 7ms/step - ia: 0.3775 - loss: 0.9023 - mae: 0.7050 - rmse: 0.9471 - smape: 1.3049 - val_ia: 0.3310 - val_loss: 0.7874 - val_mae: 0.6572 - val_rmse: 0.8184 - val_smape: 1.3084

Epoch 5/256

120/120 - 1s - 6ms/step - ia: 0.3748 - loss: 0.8972 - mae: 0.7045 - rmse: 0.9452 - smape: 1.3099 - val_ia: 0.3358 - val_loss: 0.7757 - val_mae: 0.6503 - val_rmse: 0.8114 - val_smape: 1.2834

Epoch 6/256

120/120 - 1s - 5ms/step - ia: 0.3817 - loss: 0.8845 - mae: 0.6981 - rmse: 0.9381 - smape: 1.3015 - val_ia: 0.3381 - val_loss: 0.7719 - val_mae: 0.6490 - val_rmse: 0.8096 - val_smape: 1.2824

Epoch 7/256

120/120 - 1s - 10ms/step - ia: 0.3816 - loss: 0.8845 - mae: 0.6994 - rmse: 0.9387 - smape: 1.3008 - val_ia: 0.3356 - val_loss: 0.7681 - val_mae: 0.6479 - val_rmse: 0.8072 - val_smape: 1.2830

Epoch 8/256

120/120 - 1s - 8ms/step - ia: 0.3840 - loss: 0.8759 - mae: 0.6921 - rmse: 0.9333 - smape: 1.2937 - val_ia: 0.3384 - val_loss: 0.7671 - val_mae: 0.6478 - val_rmse: 0.8072 - val_smape: 1.2792

Epoch 9/256

120/120 - 2s - 14ms/step - ia: 0.3857 - loss: 0.8701 - mae: 0.6903 - rmse: 0.9301 - smape: 1.2948 - val_ia: 0.3412 - val_loss: 0.7633 - val_mae: 0.6451 - val_rmse: 0.8049 - val_smape: 1.2674

Epoch 10/256

120/120 - 1s - 6ms/step - ia: 0.3870 - loss: 0.8686 - mae: 0.6901 - rmse: 0.9298 - smape: 1.2909 - val_ia: 0.3412 - val_loss: 0.7638 - val_mae: 0.6458 - val_rmse: 0.8054 - val_smape: 1.2749

Epoch 11/256

120/120 - 1s - 6ms/step - ia: 0.3870 - loss: 0.8625 - mae: 0.6872 - rmse: 0.9268 - smape: 1.2897 - val_ia: 0.3448 - val_loss: 0.7667 - val_mae: 0.6484 - val_rmse: 0.8086 - val_smape: 1.2804

Epoch 12/256

120/120 - 1s - 6ms/step - ia: 0.3869 - loss: 0.8622 - mae: 0.6874 - rmse: 0.9258 - smape: 1.2912 - val_ia: 0.3433 - val_loss: 0.7624 - val_mae: 0.6453 - val_rmse: 0.8051 - val_smape: 1.2696

Epoch 13/256

120/120 - 1s - 9ms/step - ia: 0.3878 - loss: 0.8578 - mae: 0.6846 - rmse: 0.9232 - smape: 1.2914 - val_ia: 0.3419 - val_loss: 0.7596 - val_mae: 0.6449 - val_rmse: 0.8037 - val_smape: 1.2655

Epoch 14/256

120/120 - 1s - 5ms/step - ia: 0.3860 - loss: 0.8535 - mae: 0.6840 - rmse: 0.9218 - smape: 1.2916 - val_ia: 0.3462 - val_loss: 0.7633 - val_mae: 0.6457 - val_rmse: 0.8063 - val_smape: 1.2694

Epoch 15/256

120/120 - 1s - 7ms/step - ia: 0.3865 - loss: 0.8563 - mae: 0.6834 - rmse: 0.9229 - smape: 1.2897 - val_ia: 0.3412 - val_loss: 0.7589 - val_mae: 0.6436 - val_rmse: 0.8026 - val_smape: 1.2647

Epoch 16/256

120/120 - 2s - 14ms/step - ia: 0.3876 - loss: 0.8504 - mae: 0.6816 - rmse: 0.9196 - smape: 1.2900 - val_ia: 0.3420 - val_loss: 0.7607 - val_mae: 0.6454 - val_rmse: 0.8043 - val_smape: 1.2699

Epoch 17/256

120/120 - 1s - 10ms/step - ia: 0.3872 - loss: 0.8514 - mae: 0.6801 - rmse: 0.9204 - smape: 1.2857 - val_ia: 0.3422 - val_loss: 0.7580 - val_mae: 0.6428 - val_rmse: 0.8020 - val_smape: 1.2633

Epoch 18/256

120/120 - 1s - 9ms/step - ia: 0.3871 - loss: 0.8425 - mae: 0.6778 - rmse: 0.9149 - smape: 1.2890 - val_ia: 0.3433 - val_loss: 0.7593 - val_mae: 0.6438 - val_rmse: 0.8032 - val_smape: 1.2671

Epoch 19/256

120/120 - 2s - 13ms/step - ia: 0.3878 - loss: 0.8441 - mae: 0.6778 - rmse: 0.9163 - smape: 1.2861 - val_ia: 0.3435 - val_loss: 0.7616 - val_mae: 0.6459 - val_rmse: 0.8053 - val_smape: 1.2727

Epoch 20/256

120/120 - 1s - 11ms/step - ia: 0.3882 - loss: 0.8401 - mae: 0.6751 - rmse: 0.9142 - smape: 1.2831 - val_ia: 0.3433 - val_loss: 0.7593 - val_mae: 0.6444 - val_rmse: 0.8036 - val_smape: 1.2674

Epoch 21/256

120/120 - 1s - 5ms/step - ia: 0.3862 - loss: 0.8404 - mae: 0.6757 - rmse: 0.9147 - smape: 1.2857 - val_ia: 0.3449 - val_loss: 0.7610 - val_mae: 0.6446 - val_rmse: 0.8046 - val_smape: 1.2679

Epoch 22/256

120/120 - 1s - 6ms/step - ia: 0.3894 - loss: 0.8356 - mae: 0.6736 - rmse: 0.9117 - smape: 1.2811 - val_ia: 0.3435 - val_loss: 0.7583 - val_mae: 0.6432 - val_rmse: 0.8026 - val_smape: 1.2637

Epoch 23/256

120/120 - 1s - 7ms/step - ia: 0.3880 - loss: 0.8377 - mae: 0.6742 - rmse: 0.9124 - smape: 1.2843 - val_ia: 0.3442 - val_loss: 0.7618 - val_mae: 0.6453 - val_rmse: 0.8051 - val_smape: 1.2715

Epoch 24/256

120/120 - 1s - 8ms/step - ia: 0.3896 - loss: 0.8351 - mae: 0.6732 - rmse: 0.9113 - smape: 1.2818 - val_ia: 0.3417 - val_loss: 0.7617 - val_mae: 0.6458 - val_rmse: 0.8048 - val_smape: 1.2789

Epoch 25/256

120/120 - 1s - 12ms/step - ia: 0.3855 - loss: 0.8324 - mae: 0.6730 - rmse: 0.9094 - smape: 1.2892 - val_ia: 0.3439 - val_loss: 0.7596 - val_mae: 0.6437 - val_rmse: 0.8034 - val_smape: 1.2673

Epoch 26/256

120/120 - 1s - 10ms/step - ia: 0.3876 - loss: 0.8312 - mae: 0.6714 - rmse: 0.9088 - smape: 1.2818 - val_ia: 0.3458 - val_loss: 0.7630 - val_mae: 0.6466 - val_rmse: 0.8067 - val_smape: 1.2749

Epoch 27/256

120/120 - 1s - 5ms/step - ia: 0.3882 - loss: 0.8305 - mae: 0.6722 - rmse: 0.9085 - smape: 1.2840 - val_ia: 0.3455 - val_loss: 0.7610 - val_mae: 0.6437 - val_rmse: 0.8042 - val_smape: 1.2666

Epoch 28/256

120/120 - 1s - 6ms/step - ia: 0.3890 - loss: 0.8275 - mae: 0.6688 - rmse: 0.9071 - smape: 1.2781 - val_ia: 0.3463 - val_loss: 0.7600 - val_mae: 0.6441 - val_rmse: 0.8043 - val_smape: 1.2625

Epoch 29/256

120/120 - 1s - 8ms/step - ia: 0.3902 - loss: 0.8281 - mae: 0.6694 - rmse: 0.9077 - smape: 1.2785 - val_ia: 0.3452 - val_loss: 0.7610 - val_mae: 0.6451 - val_rmse: 0.8051 - val_smape: 1.2685

Epoch 30/256

120/120 - 1s - 6ms/step - ia: 0.3897 - loss: 0.8273 - mae: 0.6689 - rmse: 0.9069 - smape: 1.2782 - val_ia: 0.3444 - val_loss: 0.7583 - val_mae: 0.6437 - val_rmse: 0.8032 - val_smape: 1.2607

Epoch 31/256

120/120 - 1s - 7ms/step - ia: 0.3889 - loss: 0.8303 - mae: 0.6709 - rmse: 0.9083 - smape: 1.2787 - val_ia: 0.3428 - val_loss: 0.7576 - val_mae: 0.6430 - val_rmse: 0.8022 - val_smape: 1.2613

Epoch 32/256

120/120 - 1s - 8ms/step - ia: 0.3887 - loss: 0.8284 - mae: 0.6690 - rmse: 0.9072 - smape: 1.2769 - val_ia: 0.3433 - val_loss: 0.7582 - val_mae: 0.6440 - val_rmse: 0.8032 - val_smape: 1.2627

Epoch 33/256

120/120 - 1s - 6ms/step - ia: 0.3893 - loss: 0.8264 - mae: 0.6687 - rmse: 0.9060 - smape: 1.2774 - val_ia: 0.3430 - val_loss: 0.7561 - val_mae: 0.6414 - val_rmse: 0.8009 - val_smape: 1.2573

Epoch 34/256

120/120 - 1s - 6ms/step - ia: 0.3909 - loss: 0.8251 - mae: 0.6669 - rmse: 0.9048 - smape: 1.2731 - val_ia: 0.3444 - val_loss: 0.7614 - val_mae: 0.6452 - val_rmse: 0.8052 - val_smape: 1.2713

Epoch 35/256

120/120 - 1s - 6ms/step - ia: 0.3883 - loss: 0.8265 - mae: 0.6681 - rmse: 0.9070 - smape: 1.2785 - val_ia: 0.3459 - val_loss: 0.7607 - val_mae: 0.6447 - val_rmse: 0.8050 - val_smape: 1.2662

Epoch 36/256

120/120 - 1s - 7ms/step - ia: 0.3906 - loss: 0.8220 - mae: 0.6662 - rmse: 0.9039 - smape: 1.2732 - val_ia: 0.3467 - val_loss: 0.7606 - val_mae: 0.6439 - val_rmse: 0.8046 - val_smape: 1.2651

Epoch 37/256

120/120 - 1s - 6ms/step - ia: 0.3916 - loss: 0.8231 - mae: 0.6666 - rmse: 0.9048 - smape: 1.2751 - val_ia: 0.3435 - val_loss: 0.7616 - val_mae: 0.6464 - val_rmse: 0.8059 - val_smape: 1.2753

Epoch 38/256

120/120 - 1s - 12ms/step - ia: 0.3928 - loss: 0.8218 - mae: 0.6654 - rmse: 0.9031 - smape: 1.2727 - val_ia: 0.3408 - val_loss: 0.7562 - val_mae: 0.6422 - val_rmse: 0.8010 - val_smape: 1.2640

Epoch 39/256

120/120 - 1s - 8ms/step - ia: 0.3906 - loss: 0.8203 - mae: 0.6651 - rmse: 0.9033 - smape: 1.2737 - val_ia: 0.3440 - val_loss: 0.7578 - val_mae: 0.6434 - val_rmse: 0.8029 - val_smape: 1.2631

Epoch 40/256

120/120 - 1s - 5ms/step - ia: 0.3920 - loss: 0.8205 - mae: 0.6656 - rmse: 0.9028 - smape: 1.2715 - val_ia: 0.3440 - val_loss: 0.7569 - val_mae: 0.6434 - val_rmse: 0.8027 - val_smape: 1.2598

Epoch 41/256

120/120 - 1s - 8ms/step - ia: 0.3922 - loss: 0.8209 - mae: 0.6651 - rmse: 0.9032 - smape: 1.2738 - val_ia: 0.3473 - val_loss: 0.7588 - val_mae: 0.6432 - val_rmse: 0.8039 - val_smape: 1.2602

Epoch 42/256

120/120 - 1s - 8ms/step - ia: 0.3914 - loss: 0.8201 - mae: 0.6651 - rmse: 0.9037 - smape: 1.2718 - val_ia: 0.3458 - val_loss: 0.7574 - val_mae: 0.6437 - val_rmse: 0.8036 - val_smape: 1.2583

Epoch 43/256

120/120 - 1s - 7ms/step - ia: 0.3938 - loss: 0.8196 - mae: 0.6646 - rmse: 0.9028 - smape: 1.2687 - val_ia: 0.3469 - val_loss: 0.7588 - val_mae: 0.6438 - val_rmse: 0.8043 - val_smape: 1.2607

Epoch 44/256

120/120 - 2s - 15ms/step - ia: 0.3939 - loss: 0.8163 - mae: 0.6638 - rmse: 0.9011 - smape: 1.2697 - val_ia: 0.3465 - val_loss: 0.7605 - val_mae: 0.6450 - val_rmse: 0.8055 - val_smape: 1.2669

Epoch 45/256

120/120 - 1s - 9ms/step - ia: 0.3933 - loss: 0.8178 - mae: 0.6636 - rmse: 0.9020 - smape: 1.2699 - val_ia: 0.3461 - val_loss: 0.7570 - val_mae: 0.6434 - val_rmse: 0.8034 - val_smape: 1.2583

Epoch 46/256

120/120 - 1s - 12ms/step - ia: 0.3966 - loss: 0.8149 - mae: 0.6627 - rmse: 0.8999 - smape: 1.2664 - val_ia: 0.3468 - val_loss: 0.7556 - val_mae: 0.6416 - val_rmse: 0.8020 - val_smape: 1.2552

Epoch 47/256

120/120 - 1s - 10ms/step - ia: 0.3944 - loss: 0.8165 - mae: 0.6623 - rmse: 0.9015 - smape: 1.2684 - val_ia: 0.3438 - val_loss: 0.7564 - val_mae: 0.6443 - val_rmse: 0.8034 - val_smape: 1.2627

Epoch 48/256

120/120 - 1s - 6ms/step - ia: 0.3959 - loss: 0.8159 - mae: 0.6624 - rmse: 0.9006 - smape: 1.2653 - val_ia: 0.3449 - val_loss: 0.7540 - val_mae: 0.6420 - val_rmse: 0.8014 - val_smape: 1.2549

Epoch 49/256

120/120 - 1s - 5ms/step - ia: 0.3941 - loss: 0.8142 - mae: 0.6631 - rmse: 0.8999 - smape: 1.2697 - val_ia: 0.3480 - val_loss: 0.7545 - val_mae: 0.6414 - val_rmse: 0.8018 - val_smape: 1.2497

Epoch 50/256

120/120 - 1s - 5ms/step - ia: 0.3956 - loss: 0.8151 - mae: 0.6632 - rmse: 0.8998 - smape: 1.2667 - val_ia: 0.3468 - val_loss: 0.7556 - val_mae: 0.6428 - val_rmse: 0.8028 - val_smape: 1.2560

Epoch 51/256

120/120 - 1s - 6ms/step - ia: 0.3960 - loss: 0.8153 - mae: 0.6622 - rmse: 0.9008 - smape: 1.2653 - val_ia: 0.3482 - val_loss: 0.7550 - val_mae: 0.6416 - val_rmse: 0.8022 - val_smape: 1.2508

Epoch 52/256

120/120 - 1s - 11ms/step - ia: 0.3960 - loss: 0.8136 - mae: 0.6623 - rmse: 0.8996 - smape: 1.2647 - val_ia: 0.3490 - val_loss: 0.7559 - val_mae: 0.6423 - val_rmse: 0.8031 - val_smape: 1.2554

Epoch 53/256

120/120 - 1s - 9ms/step - ia: 0.3950 - loss: 0.8151 - mae: 0.6630 - rmse: 0.8997 - smape: 1.2698 - val_ia: 0.3484 - val_loss: 0.7558 - val_mae: 0.6422 - val_rmse: 0.8030 - val_smape: 1.2539

Epoch 54/256

120/120 - 1s - 12ms/step - ia: 0.3970 - loss: 0.8146 - mae: 0.6623 - rmse: 0.8997 - smape: 1.2637 - val_ia: 0.3465 - val_loss: 0.7529 - val_mae: 0.6407 - val_rmse: 0.8009 - val_smape: 1.2498

Epoch 55/256

120/120 - 1s - 9ms/step - ia: 0.3969 - loss: 0.8129 - mae: 0.6615 - rmse: 0.8987 - smape: 1.2654 - val_ia: 0.3478 - val_loss: 0.7541 - val_mae: 0.6415 - val_rmse: 0.8020 - val_smape: 1.2537

Epoch 56/256

120/120 - 1s - 11ms/step - ia: 0.3981 - loss: 0.8122 - mae: 0.6604 - rmse: 0.8986 - smape: 1.2619 - val_ia: 0.3487 - val_loss: 0.7569 - val_mae: 0.6445 - val_rmse: 0.8050 - val_smape: 1.2605

Epoch 57/256

120/120 - 1s - 10ms/step - ia: 0.3975 - loss: 0.8117 - mae: 0.6609 - rmse: 0.8988 - smape: 1.2632 - val_ia: 0.3457 - val_loss: 0.7539 - val_mae: 0.6425 - val_rmse: 0.8022 - val_smape: 1.2580

Epoch 58/256

120/120 - 1s - 6ms/step - ia: 0.3975 - loss: 0.8107 - mae: 0.6605 - rmse: 0.8976 - smape: 1.2654 - val_ia: 0.3484 - val_loss: 0.7529 - val_mae: 0.6402 - val_rmse: 0.8010 - val_smape: 1.2506

Epoch 59/256

120/120 - 1s - 8ms/step - ia: 0.3984 - loss: 0.8131 - mae: 0.6601 - rmse: 0.8992 - smape: 1.2600 - val_ia: 0.3488 - val_loss: 0.7547 - val_mae: 0.6421 - val_rmse: 0.8029 - val_smape: 1.2564

Epoch 60/256

120/120 - 1s - 7ms/step - ia: 0.3998 - loss: 0.8077 - mae: 0.6583 - rmse: 0.8959 - smape: 1.2594 - val_ia: 0.3470 - val_loss: 0.7516 - val_mae: 0.6408 - val_rmse: 0.8008 - val_smape: 1.2501

Epoch 61/256

120/120 - 2s - 13ms/step - ia: 0.3992 - loss: 0.8096 - mae: 0.6607 - rmse: 0.8976 - smape: 1.2629 - val_ia: 0.3475 - val_loss: 0.7512 - val_mae: 0.6406 - val_rmse: 0.8007 - val_smape: 1.2509

Epoch 62/256

120/120 - 1s - 7ms/step - ia: 0.3990 - loss: 0.8082 - mae: 0.6590 - rmse: 0.8965 - smape: 1.2625 - val_ia: 0.3482 - val_loss: 0.7523 - val_mae: 0.6419 - val_rmse: 0.8020 - val_smape: 1.2529

Epoch 63/256

120/120 - 1s - 11ms/step - ia: 0.3990 - loss: 0.8099 - mae: 0.6598 - rmse: 0.8968 - smape: 1.2615 - val_ia: 0.3475 - val_loss: 0.7495 - val_mae: 0.6397 - val_rmse: 0.7997 - val_smape: 1.2460

Epoch 64/256

120/120 - 1s - 5ms/step - ia: 0.4003 - loss: 0.8111 - mae: 0.6591 - rmse: 0.8982 - smape: 1.2573 - val_ia: 0.3485 - val_loss: 0.7508 - val_mae: 0.6404 - val_rmse: 0.8007 - val_smape: 1.2483

Epoch 65/256

120/120 - 1s - 8ms/step - ia: 0.4011 - loss: 0.8084 - mae: 0.6585 - rmse: 0.8963 - smape: 1.2573 - val_ia: 0.3494 - val_loss: 0.7518 - val_mae: 0.6412 - val_rmse: 0.8017 - val_smape: 1.2519

Epoch 66/256

120/120 - 1s - 5ms/step - ia: 0.4011 - loss: 0.8079 - mae: 0.6581 - rmse: 0.8964 - smape: 1.2583 - val_ia: 0.3479 - val_loss: 0.7505 - val_mae: 0.6408 - val_rmse: 0.8008 - val_smape: 1.2533

Epoch 67/256

120/120 - 1s - 6ms/step - ia: 0.4000 - loss: 0.8063 - mae: 0.6583 - rmse: 0.8956 - smape: 1.2592 - val_ia: 0.3522 - val_loss: 0.7510 - val_mae: 0.6396 - val_rmse: 0.8010 - val_smape: 1.2460

Epoch 68/256

120/120 - 1s - 8ms/step - ia: 0.4034 - loss: 0.8063 - mae: 0.6572 - rmse: 0.8955 - smape: 1.2545 - val_ia: 0.3495 - val_loss: 0.7478 - val_mae: 0.6387 - val_rmse: 0.7990 - val_smape: 1.2440

Epoch 69/256

120/120 - 1s - 5ms/step - ia: 0.4022 - loss: 0.8077 - mae: 0.6580 - rmse: 0.8963 - smape: 1.2566 - val_ia: 0.3492 - val_loss: 0.7501 - val_mae: 0.6410 - val_rmse: 0.8011 - val_smape: 1.2517

Epoch 70/256

120/120 - 1s - 6ms/step - ia: 0.3997 - loss: 0.8079 - mae: 0.6585 - rmse: 0.8960 - smape: 1.2598 - val_ia: 0.3515 - val_loss: 0.7514 - val_mae: 0.6414 - val_rmse: 0.8023 - val_smape: 1.2504

Epoch 71/256

120/120 - 1s - 7ms/step - ia: 0.4053 - loss: 0.8025 - mae: 0.6549 - rmse: 0.8936 - smape: 1.2507 - val_ia: 0.3503 - val_loss: 0.7491 - val_mae: 0.6397 - val_rmse: 0.8003 - val_smape: 1.2482

Epoch 72/256

120/120 - 1s - 6ms/step - ia: 0.4017 - loss: 0.8050 - mae: 0.6570 - rmse: 0.8944 - smape: 1.2570 - val_ia: 0.3524 - val_loss: 0.7499 - val_mae: 0.6403 - val_rmse: 0.8014 - val_smape: 1.2481

Epoch 73/256

120/120 - 1s - 12ms/step - ia: 0.4057 - loss: 0.8033 - mae: 0.6558 - rmse: 0.8937 - smape: 1.2514 - val_ia: 0.3511 - val_loss: 0.7494 - val_mae: 0.6401 - val_rmse: 0.8008 - val_smape: 1.2497

Epoch 74/256

120/120 - 1s - 9ms/step - ia: 0.4027 - loss: 0.8038 - mae: 0.6573 - rmse: 0.8942 - smape: 1.2572 - val_ia: 0.3532 - val_loss: 0.7485 - val_mae: 0.6389 - val_rmse: 0.8002 - val_smape: 1.2444

Epoch 75/256

120/120 - 1s - 10ms/step - ia: 0.4029 - loss: 0.8046 - mae: 0.6565 - rmse: 0.8944 - smape: 1.2544 - val_ia: 0.3508 - val_loss: 0.7477 - val_mae: 0.6397 - val_rmse: 0.8000 - val_smape: 1.2460

Epoch 76/256

120/120 - 1s - 6ms/step - ia: 0.4050 - loss: 0.8031 - mae: 0.6559 - rmse: 0.8935 - smape: 1.2541 - val_ia: 0.3514 - val_loss: 0.7478 - val_mae: 0.6398 - val_rmse: 0.8003 - val_smape: 1.2466

Epoch 77/256

120/120 - 1s - 5ms/step - ia: 0.4055 - loss: 0.8018 - mae: 0.6558 - rmse: 0.8925 - smape: 1.2520 - val_ia: 0.3542 - val_loss: 0.7488 - val_mae: 0.6396 - val_rmse: 0.8011 - val_smape: 1.2472

Epoch 78/256

120/120 - 1s - 6ms/step - ia: 0.4060 - loss: 0.8037 - mae: 0.6548 - rmse: 0.8942 - smape: 1.2484 - val_ia: 0.3512 - val_loss: 0.7473 - val_mae: 0.6401 - val_rmse: 0.8004 - val_smape: 1.2510

Epoch 79/256

120/120 - 1s - 6ms/step - ia: 0.4048 - loss: 0.8022 - mae: 0.6553 - rmse: 0.8923 - smape: 1.2537 - val_ia: 0.3506 - val_loss: 0.7471 - val_mae: 0.6401 - val_rmse: 0.8003 - val_smape: 1.2493

Epoch 80/256

120/120 - 1s - 6ms/step - ia: 0.4058 - loss: 0.8009 - mae: 0.6550 - rmse: 0.8929 - smape: 1.2529 - val_ia: 0.3509 - val_loss: 0.7456 - val_mae: 0.6388 - val_rmse: 0.7990 - val_smape: 1.2418

Epoch 81/256

120/120 - 1s - 9ms/step - ia: 0.4071 - loss: 0.8002 - mae: 0.6551 - rmse: 0.8919 - smape: 1.2501 - val_ia: 0.3532 - val_loss: 0.7471 - val_mae: 0.6392 - val_rmse: 0.8002 - val_smape: 1.2461

Epoch 82/256

120/120 - 1s - 10ms/step - ia: 0.4061 - loss: 0.8001 - mae: 0.6544 - rmse: 0.8927 - smape: 1.2504 - val_ia: 0.3528 - val_loss: 0.7467 - val_mae: 0.6392 - val_rmse: 0.8001 - val_smape: 1.2445

Epoch 83/256

120/120 - 1s - 5ms/step - ia: 0.4081 - loss: 0.8000 - mae: 0.6539 - rmse: 0.8908 - smape: 1.2471 - val_ia: 0.3524 - val_loss: 0.7451 - val_mae: 0.6381 - val_rmse: 0.7988 - val_smape: 1.2420

Epoch 84/256

120/120 - 1s - 7ms/step - ia: 0.4087 - loss: 0.7990 - mae: 0.6544 - rmse: 0.8908 - smape: 1.2492 - val_ia: 0.3530 - val_loss: 0.7463 - val_mae: 0.6394 - val_rmse: 0.8001 - val_smape: 1.2491

Epoch 85/256

120/120 - 1s - 6ms/step - ia: 0.4066 - loss: 0.8002 - mae: 0.6543 - rmse: 0.8914 - smape: 1.2488 - val_ia: 0.3512 - val_loss: 0.7454 - val_mae: 0.6394 - val_rmse: 0.7995 - val_smape: 1.2482

Epoch 86/256

120/120 - 1s - 7ms/step - ia: 0.4079 - loss: 0.7998 - mae: 0.6546 - rmse: 0.8909 - smape: 1.2503 - val_ia: 0.3535 - val_loss: 0.7454 - val_mae: 0.6385 - val_rmse: 0.7994 - val_smape: 1.2460

Epoch 87/256

120/120 - 2s - 14ms/step - ia: 0.4077 - loss: 0.7977 - mae: 0.6534 - rmse: 0.8903 - smape: 1.2493 - val_ia: 0.3530 - val_loss: 0.7440 - val_mae: 0.6379 - val_rmse: 0.7985 - val_smape: 1.2427

Epoch 88/256

120/120 - 1s - 10ms/step - ia: 0.4074 - loss: 0.7981 - mae: 0.6539 - rmse: 0.8902 - smape: 1.2508 - val_ia: 0.3532 - val_loss: 0.7467 - val_mae: 0.6398 - val_rmse: 0.8006 - val_smape: 1.2507

Epoch 89/256

120/120 - 1s - 4ms/step - ia: 0.4076 - loss: 0.7987 - mae: 0.6547 - rmse: 0.8919 - smape: 1.2522 - val_ia: 0.3535 - val_loss: 0.7454 - val_mae: 0.6387 - val_rmse: 0.7996 - val_smape: 1.2484

Epoch 90/256

120/120 - 1s - 5ms/step - ia: 0.4068 - loss: 0.7989 - mae: 0.6542 - rmse: 0.8910 - smape: 1.2516 - val_ia: 0.3542 - val_loss: 0.7466 - val_mae: 0.6399 - val_rmse: 0.8010 - val_smape: 1.2488

Epoch 91/256

120/120 - 1s - 6ms/step - ia: 0.4084 - loss: 0.7984 - mae: 0.6529 - rmse: 0.8913 - smape: 1.2462 - val_ia: 0.3521 - val_loss: 0.7448 - val_mae: 0.6393 - val_rmse: 0.7995 - val_smape: 1.2470

Epoch 92/256

120/120 - 1s - 7ms/step - ia: 0.4082 - loss: 0.7974 - mae: 0.6540 - rmse: 0.8908 - smape: 1.2499 - val_ia: 0.3532 - val_loss: 0.7455 - val_mae: 0.6392 - val_rmse: 0.7999 - val_smape: 1.2476

Epoch 93/256

120/120 - 1s - 7ms/step - ia: 0.4080 - loss: 0.7970 - mae: 0.6532 - rmse: 0.8903 - smape: 1.2493 - val_ia: 0.3533 - val_loss: 0.7441 - val_mae: 0.6387 - val_rmse: 0.7993 - val_smape: 1.2458

Epoch 94/256

120/120 - 1s - 7ms/step - ia: 0.4086 - loss: 0.7966 - mae: 0.6527 - rmse: 0.8894 - smape: 1.2498 - val_ia: 0.3530 - val_loss: 0.7435 - val_mae: 0.6384 - val_rmse: 0.7988 - val_smape: 1.2468

Epoch 95/256

120/120 - 1s - 12ms/step - ia: 0.4089 - loss: 0.7973 - mae: 0.6540 - rmse: 0.8906 - smape: 1.2486 - val_ia: 0.3539 - val_loss: 0.7437 - val_mae: 0.6381 - val_rmse: 0.7990 - val_smape: 1.2463

Epoch 96/256

120/120 - 1s - 7ms/step - ia: 0.4090 - loss: 0.7958 - mae: 0.6526 - rmse: 0.8899 - smape: 1.2488 - val_ia: 0.3555 - val_loss: 0.7434 - val_mae: 0.6377 - val_rmse: 0.7988 - val_smape: 1.2429

Epoch 97/256

120/120 - 1s - 8ms/step - ia: 0.4099 - loss: 0.7980 - mae: 0.6528 - rmse: 0.8901 - smape: 1.2460 - val_ia: 0.3526 - val_loss: 0.7417 - val_mae: 0.6373 - val_rmse: 0.7975 - val_smape: 1.2452

Epoch 98/256


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

3830/3830 - 15s - 4ms/step - ia: 0.3853 - loss: 0.8721 - mae: 0.6909 - rmse: 0.8772 - smape: 1.2797 - val_ia: 0.2037 - val_loss: 0.7957 - val_mae: 0.6601 - val_rmse: 0.7043 - val_smape: 1.2499

Epoch 2/8

3830/3830 - 29s - 7ms/step - ia: 0.4108 - loss: 0.8013 - mae: 0.6542 - rmse: 0.8383 - smape: 1.2328 - val_ia: 0.2075 - val_loss: 0.8422 - val_mae: 0.6685 - val_rmse: 0.7156 - val_smape: 1.1822

Epoch 3/8

3830/3830 - 19s - 5ms/step - ia: 0.4166 - loss: 0.7848 - mae: 0.6475 - rmse: 0.8305 - smape: 1.2251 - val_ia: 0.2039 - val_loss: 0.7749 - val_mae: 0.6509 - val_rmse: 0.6939 - val_smape: 1.2730

Epoch 4/8

3830/3830 - 14s - 4ms/step - ia: 0.4259 - loss: 0.7682 - mae: 0.6414 - rmse: 0.8194 - smape: 1.2171 - val_ia: 0.2025 - val_loss: 0.8045 - val_mae: 0.6611 - val_rmse: 0.7101 - val_smape: 1.2447

Epoch 5/8

3830/3830 - 15s - 4ms/step - ia: 0.4394 - loss: 0.7506 - mae: 0.6312 - rmse: 0.8107 - smape: 1.1918 - val_ia: 0.2040 - val_loss: 0.7994 - val_mae: 0.6600 - val_rmse: 0.7070 - val_smape: 1.2565

Epoch 6/8

3830/3830 - 23s - 6ms/step - ia: 0.4454 - loss: 0.7334 - mae: 0.6268 - rmse: 0.8030 - smape: 1.1874 - val_ia: 0.2123 - val_loss: 0.7640 - val_mae: 0.6321 - val_rmse: 0.6793 - val_smape: 1.2010

Epoch 7/8

3830/3830 - 15s - 4ms/step - ia: 0.4505 - loss: 0.7208 - mae: 0.6195 - rmse: 0.7968 - smape: 1.1773 - val_ia: 0.2072 - val_loss: 0.7779 - val_mae: 0.6414 - val_rmse: 0.6878 - val_smape: 1.2591

Epoch 8/8

3830/3830 - 21s - 5ms/step - ia: 0.4554 - loss: 0.7093 - mae: 0.6149 - rmse: 0.7899 - smape: 1.1670 - val_ia: 0.1972 - val_loss: 0.9879 - val_mae: 0.7211 - val_rmse: 0.7728 - val_smape: 1.2589

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 58s 430ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 76%|███████▌  | 38/50 [2:56:02<51:56, 259.73s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 12s - 25ms/step - ia: 0.2868 - loss: 1.2536 - mae: 0.7781 - rmse: 1.1058 - smape: 1.3957 - val_ia: 0.2522 - val_loss: 0.9812 - val_mae: 0.7072 - val_rmse: 0.8310 - val_smape: 1.5464

Epoch 2/128

479/479 - 3s - 6ms/step - ia: 0.2591 - loss: 1.1659 - mae: 0.7649 - rmse: 1.0669 - smape: 1.4570 - val_ia: 0.2493 - val_loss: 0.9605 - val_mae: 0.7166 - val_rmse: 0.8369 - val_smape: 1.6630

Epoch 3/128

479/479 - 3s - 7ms/step - ia: 0.2403 - loss: 1.1180 - mae: 0.7617 - rmse: 1.0440 - smape: 1.5044 - val_ia: 0.2472 - val_loss: 0.9500 - val_mae: 0.7252 - val_rmse: 0.8430 - val_smape: 1.7221

Epoch 4/128

479/479 - 4s - 9ms/step - ia: 0.2264 - loss: 1.0943 - mae: 0.7617 - rmse: 1.0336 - smape: 1.5305 - val_ia: 0.2455 - val_loss: 0.9433 - val_mae: 0.7317 - val_rmse: 0.8477 - val_smape: 1.7428

Epoch 5/128

479/479 - 2s - 4ms/step - ia: 0.2199 - loss: 1.0766 - mae: 0.7621 - rmse: 1.0242 - smape: 1.5540 - val_ia: 0.2444 - val_loss: 0.9386 - val_mae: 0.7364 - val_rmse: 0.8513 - val_smape: 1.7470

Epoch 6/128

479/479 - 2s - 3ms/step - ia: 0.2123 - loss: 1.0668 - mae: 0.7642 - rmse: 1.0215 - smape: 1.5691 - val_ia: 0.2435 - val_loss: 0.9346 - val_mae: 0.7392 - val_rmse: 0.8532 - val_smape: 1.7460

Epoch 7/128

479/479 - 3s - 6ms/step - ia: 0.2099 - loss: 1.0481 - mae: 0.7617 - rmse: 1.0116 - smape: 1.5802 - val_ia: 0.2429 - val_loss: 0.9312 - val_mae: 0.7402 - val_rmse: 0.8537 - val_smape: 1.7444

Epoch 8/128

479/479 - 4s - 8ms/step - ia: 0.2074 - loss: 1.0473 - mae: 0.7627 - rmse: 1.0109 - smape: 1.5883 - val_ia: 0.2423 - val_loss: 0.9275 - val_mae: 0.7405 - val_rmse: 0.8536 - val_smape: 1.7411

Epoch 9/128

479/479 - 3s - 7ms/step - ia: 0.2053 - loss: 1.0375 - mae: 0.7625 - rmse: 1.0060 - smape: 1.5954 - val_ia: 0.2418 - val_loss: 0.9233 - val_mae: 0.7399 - val_rmse: 0.8527 - val_smape: 1.7359

Epoch 10/128

479/479 - 2s - 4ms/step - ia: 0.2032 - loss: 1.0337 - mae: 0.7619 - rmse: 1.0046 - smape: 1.5975 - val_ia: 0.2414 - val_loss: 0.9193 - val_mae: 0.7388 - val_rmse: 0.8514 - val_smape: 1.7308

Epoch 11/128

479/479 - 3s - 6ms/step - ia: 0.2014 - loss: 1.0283 - mae: 0.7606 - rmse: 1.0028 - smape: 1.6022 - val_ia: 0.2410 - val_loss: 0.9159 - val_mae: 0.7379 - val_rmse: 0.8502 - val_smape: 1.7268

Epoch 12/128

479/479 - 3s - 6ms/step - ia: 0.2064 - loss: 1.0225 - mae: 0.7586 - rmse: 0.9985 - smape: 1.5992 - val_ia: 0.2405 - val_loss: 0.9121 - val_mae: 0.7364 - val_rmse: 0.8485 - val_smape: 1.7226

Epoch 13/128

479/479 - 3s - 6ms/step - ia: 0.2042 - loss: 1.0117 - mae: 0.7548 - rmse: 0.9953 - smape: 1.5968 - val_ia: 0.2402 - val_loss: 0.9085 - val_mae: 0.7348 - val_rmse: 0.8468 - val_smape: 1.7172

Epoch 14/128

479/479 - 2s - 5ms/step - ia: 0.2050 - loss: 1.0032 - mae: 0.7530 - rmse: 0.9894 - smape: 1.5985 - val_ia: 0.2400 - val_loss: 0.9043 - val_mae: 0.7330 - val_rmse: 0.8449 - val_smape: 1.7095

Epoch 15/128

479/479 - 3s - 6ms/step - ia: 0.2092 - loss: 0.9986 - mae: 0.7518 - rmse: 0.9873 - smape: 1.5946 - val_ia: 0.2396 - val_loss: 0.9003 - val_mae: 0.7310 - val_rmse: 0.8428 - val_smape: 1.7015

Epoch 16/128

479/479 - 3s - 7ms/step - ia: 0.2082 - loss: 0.9888 - mae: 0.7501 - rmse: 0.9845 - smape: 1.5958 - val_ia: 0.2394 - val_loss: 0.8963 - val_mae: 0.7291 - val_rmse: 0.8408 - val_smape: 1.6927

Epoch 17/128

479/479 - 4s - 7ms/step - ia: 0.2130 - loss: 0.9893 - mae: 0.7474 - rmse: 0.9839 - smape: 1.5845 - val_ia: 0.2393 - val_loss: 0.8925 - val_mae: 0.7270 - val_rmse: 0.8387 - val_smape: 1.6833

Epoch 18/128

479/479 - 5s - 10ms/step - ia: 0.2129 - loss: 0.9854 - mae: 0.7469 - rmse: 0.9819 - smape: 1.5841 - val_ia: 0.2392 - val_loss: 0.8882 - val_mae: 0.7248 - val_rmse: 0.8365 - val_smape: 1.6737

Epoch 19/128

479/479 - 3s - 5ms/step - ia: 0.2181 - loss: 0.9753 - mae: 0.7419 - rmse: 0.9772 - smape: 1.5746 - val_ia: 0.2392 - val_loss: 0.8835 - val_mae: 0.7225 - val_rmse: 0.8341 - val_smape: 1.6623

Epoch 20/128

479/479 - 4s - 8ms/step - ia: 0.2211 - loss: 0.9791 - mae: 0.7428 - rmse: 0.9785 - smape: 1.5729 - val_ia: 0.2392 - val_loss: 0.8794 - val_mae: 0.7205 - val_rmse: 0.8321 - val_smape: 1.6514

Epoch 21/128

479/479 - 5s - 11ms/step - ia: 0.2193 - loss: 0.9711 - mae: 0.7405 - rmse: 0.9745 - smape: 1.5734 - val_ia: 0.2392 - val_loss: 0.8749 - val_mae: 0.7184 - val_rmse: 0.8299 - val_smape: 1.6386

Epoch 22/128

479/479 - 3s - 7ms/step - ia: 0.2243 - loss: 0.9680 - mae: 0.7391 - rmse: 0.9724 - smape: 1.5656 - val_ia: 0.2394 - val_loss: 0.8705 - val_mae: 0.7162 - val_rmse: 0.8277 - val_smape: 1.6269

Epoch 23/128

479/479 - 2s - 3ms/step - ia: 0.2266 - loss: 0.9644 - mae: 0.7372 - rmse: 0.9727 - smape: 1.5575 - val_ia: 0.2396 - val_loss: 0.8653 - val_mae: 0.7133 - val_rmse: 0.8249 - val_smape: 1.6113

Epoch 24/128

479/479 - 2s - 4ms/step - ia: 0.2287 - loss: 0.9628 - mae: 0.7375 - rmse: 0.9719 - smape: 1.5588 - val_ia: 0.2400 - val_loss: 0.8610 - val_mae: 0.7113 - val_rmse: 0.8229 - val_smape: 1.5997

Epoch 25/128

479/479 - 4s - 9ms/step - ia: 0.2358 - loss: 0.9589 - mae: 0.7341 - rmse: 0.9696 - smape: 1.5447 - val_ia: 0.2404 - val_loss: 0.8570 - val_mae: 0.7093 - val_rmse: 0.8210 - val_smape: 1.5879

Epoch 26/128

479/479 - 4s - 7ms/step - ia: 0.2383 - loss: 0.9573 - mae: 0.7330 - rmse: 0.9677 - smape: 1.5394 - val_ia: 0.2407 - val_loss: 0.8529 - val_mae: 0.7067 - val_rmse: 0.8185 - val_smape: 1.5752

Epoch 27/128

479/479 - 5s - 10ms/step - ia: 0.2436 - loss: 0.9469 - mae: 0.7302 - rmse: 0.9618 - smape: 1.5341 - val_ia: 0.2411 - val_loss: 0.8489 - val_mae: 0.7045 - val_rmse: 0.8165 - val_smape: 1.5629

Epoch 28/128

479/479 - 5s - 11ms/step - ia: 0.2497 - loss: 0.9426 - mae: 0.7288 - rmse: 0.9607 - smape: 1.5278 - val_ia: 0.2415 - val_loss: 0.8455 - val_mae: 0.7021 - val_rmse: 0.8142 - val_smape: 1.5511

Epoch 29/128

479/479 - 5s - 10ms/step - ia: 0.2530 - loss: 0.9402 - mae: 0.7271 - rmse: 0.9572 - smape: 1.5206 - val_ia: 0.2419 - val_loss: 0.8416 - val_mae: 0.6997 - val_rmse: 0.8120 - val_smape: 1.5390

Epoch 30/128

479/479 - 2s - 3ms/step - ia: 0.2575 - loss: 0.9319 - mae: 0.7238 - rmse: 0.9540 - smape: 1.5127 - val_ia: 0.2425 - val_loss: 0.8380 - val_mae: 0.6977 - val_rmse: 0.8102 - val_smape: 1.5279

Epoch 31/128

479/479 - 1s - 3ms/step - ia: 0.2564 - loss: 0.9353 - mae: 0.7243 - rmse: 0.9566 - smape: 1.5087 - val_ia: 0.2430 - val_loss: 0.8346 - val_mae: 0.6957 - val_rmse: 0.8084 - val_smape: 1.5170

Epoch 32/128

479/479 - 2s - 4ms/step - ia: 0.2632 - loss: 0.9279 - mae: 0.7209 - rmse: 0.9529 - smape: 1.5006 - val_ia: 0.2436 - val_loss: 0.8314 - val_mae: 0.6941 - val_rmse: 0.8069 - val_smape: 1.5078

Epoch 33/128

479/479 - 4s - 8ms/step - ia: 0.2632 - loss: 0.9313 - mae: 0.7225 - rmse: 0.9549 - smape: 1.4992 - val_ia: 0.2442 - val_loss: 0.8282 - val_mae: 0.6924 - val_rmse: 0.8053 - val_smape: 1.4987

Epoch 34/128

479/479 - 3s - 7ms/step - ia: 0.2695 - loss: 0.9303 - mae: 0.7198 - rmse: 0.9536 - smape: 1.4909 - val_ia: 0.2448 - val_loss: 0.8258 - val_mae: 0.6909 - val_rmse: 0.8040 - val_smape: 1.4911

Epoch 35/128

479/479 - 5s - 10ms/step - ia: 0.2730 - loss: 0.9220 - mae: 0.7188 - rmse: 0.9492 - smape: 1.4906 - val_ia: 0.2454 - val_loss: 0.8233 - val_mae: 0.6893 - val_rmse: 0.8026 - val_smape: 1.4833

Epoch 36/128

479/479 - 3s - 6ms/step - ia: 0.2694 - loss: 0.9219 - mae: 0.7194 - rmse: 0.9507 - smape: 1.4880 - val_ia: 0.2460 - val_loss: 0.8209 - val_mae: 0.6877 - val_rmse: 0.8012 - val_smape: 1.4755

Epoch 37/128

479/479 - 2s - 5ms/step - ia: 0.2773 - loss: 0.9210 - mae: 0.7158 - rmse: 0.9493 - smape: 1.4747 - val_ia: 0.2466 - val_loss: 0.8192 - val_mae: 0.6863 - val_rmse: 0.8000 - val_smape: 1.4690

Epoch 38/128

479/479 - 3s - 6ms/step - ia: 0.2787 - loss: 0.9244 - mae: 0.7169 - rmse: 0.9509 - smape: 1.4749 - val_ia: 0.2470 - val_loss: 0.8173 - val_mae: 0.6850 - val_rmse: 0.7988 - val_smape: 1.4627

Epoch 39/128

479/479 - 6s - 12ms/step - ia: 0.2810 - loss: 0.9110 - mae: 0.7136 - rmse: 0.9438 - smape: 1.4738 - val_ia: 0.2475 - val_loss: 0.8151 - val_mae: 0.6837 - val_rmse: 0.7977 - val_smape: 1.4566

Epoch 40/128

479/479 - 2s - 4ms/step - ia: 0.2816 - loss: 0.9162 - mae: 0.7157 - rmse: 0.9464 - smape: 1.4742 - val_ia: 0.2480 - val_loss: 0.8128 - val_mae: 0.6819 - val_rmse: 0.7960 - val_smape: 1.4487

Epoch 41/128

479/479 - 2s - 3ms/step - ia: 0.2873 - loss: 0.9106 - mae: 0.7114 - rmse: 0.9444 - smape: 1.4586 - val_ia: 0.2485 - val_loss: 0.8111 - val_mae: 0.6805 - val_rmse: 0.7948 - val_smape: 1.4430

Epoch 42/128

479/479 - 4s - 8ms/step - ia: 0.2879 - loss: 0.9101 - mae: 0.7119 - rmse: 0.9433 - smape: 1.4645 - val_ia: 0.2490 - val_loss: 0.8092 - val_mae: 0.6797 - val_rmse: 0.7941 - val_smape: 1.4387

Epoch 43/128

479/479 - 5s - 10ms/step - ia: 0.2893 - loss: 0.9078 - mae: 0.7110 - rmse: 0.9416 - smape: 1.4635 - val_ia: 0.2495 - val_loss: 0.8078 - val_mae: 0.6787 - val_rmse: 0.7931 - val_smape: 1.4346

Epoch 44/128

479/479 - 1s - 3ms/step - ia: 0.2903 - loss: 0.9078 - mae: 0.7107 - rmse: 0.9430 - smape: 1.4571 - val_ia: 0.2498 - val_loss: 0.8063 - val_mae: 0.6777 - val_rmse: 0.7923 - val_smape: 1.4301

Epoch 45/128

479/479 - 2s - 4ms/step - ia: 0.2939 - loss: 0.9062 - mae: 0.7104 - rmse: 0.9417 - smape: 1.4538 - val_ia: 0.2503 - val_loss: 0.8050 - val_mae: 0.6768 - val_rmse: 0.7915 - val_smape: 1.4262

Epoch 46/128

479/479 - 3s - 6ms/step - ia: 0.2937 - loss: 0.9085 - mae: 0.7097 - rmse: 0.9434 - smape: 1.4494 - val_ia: 0.2507 - val_loss: 0.8041 - val_mae: 0.6758 - val_rmse: 0.7906 - val_smape: 1.4230

Epoch 47/128

479/479 - 3s - 7ms/step - ia: 0.2959 - loss: 0.9038 - mae: 0.7081 - rmse: 0.9419 - smape: 1.4476 - val_ia: 0.2510 - val_loss: 0.8031 - val_mae: 0.6751 - val_rmse: 0.7900 - val_smape: 1.4211

Epoch 48/128

479/479 - 3s - 7ms/step - ia: 0.2973 - loss: 0.9027 - mae: 0.7076 - rmse: 0.9394 - smape: 1.4455 - val_ia: 0.2513 - val_loss: 0.8019 - val_mae: 0.6741 - val_rmse: 0.7891 - val_smape: 1.4165

Epoch 49/128

479/479 - 4s - 8ms/step - ia: 0.2980 - loss: 0.9017 - mae: 0.7075 - rmse: 0.9397 - smape: 1.4427 - val_ia: 0.2518 - val_loss: 0.8005 - val_mae: 0.6734 - val_rmse: 0.7884 - val_smape: 1.4131

Epoch 50/128

479/479 - 1s - 3ms/step - ia: 0.3006 - loss: 0.8998 - mae: 0.7059 - rmse: 0.9381 - smape: 1.4420 - val_ia: 0.2521 - val_loss: 0.7993 - val_mae: 0.6727 - val_rmse: 0.7878 - val_smape: 1.4105

Epoch 51/128

479/479 - 4s - 8ms/step - ia: 0.3038 - loss: 0.8945 - mae: 0.7040 - rmse: 0.9366 - smape: 1.4364 - val_ia: 0.2525 - val_loss: 0.7980 - val_mae: 0.6718 - val_rmse: 0.7870 - val_smape: 1.4065

Epoch 52/128

479/479 - 5s - 10ms/step - ia: 0.3049 - loss: 0.8957 - mae: 0.7038 - rmse: 0.9351 - smape: 1.4340 - val_ia: 0.2528 - val_loss: 0.7970 - val_mae: 0.6713 - val_rmse: 0.7865 - val_smape: 1.4048

Epoch 53/128

479/479 - 2s - 3ms/step - ia: 0.3044 - loss: 0.8957 - mae: 0.7039 - rmse: 0.9361 - smape: 1.4356 - val_ia: 0.2532 - val_loss: 0.7961 - val_mae: 0.6704 - val_rmse: 0.7857 - val_smape: 1.4021

Epoch 54/128

479/479 - 2s - 3ms/step - ia: 0.3057 - loss: 0.8909 - mae: 0.7025 - rmse: 0.9338 - smape: 1.4337 - val_ia: 0.2535 - val_loss: 0.7951 - val_mae: 0.6699 - val_rmse: 0.7852 - val_smape: 1.3999

Epoch 55/128

479/479 - 2s - 5ms/step - ia: 0.3059 - loss: 0.8922 - mae: 0.7030 - rmse: 0.9343 - smape: 1.4336 - val_ia: 0.2539 - val_loss: 0.7941 - val_mae: 0.6691 - val_rmse: 0.7845 - val_smape: 1.3963

Epoch 56/128

479/479 - 4s - 9ms/step - ia: 0.3066 - loss: 0.8916 - mae: 0.7023 - rmse: 0.9336 - smape: 1.4329 - val_ia: 0.2542 - val_loss: 0.7937 - val_mae: 0.6686 - val_rmse: 0.7841 - val_smape: 1.3950

Epoch 57/128

479/479 - 2s - 3ms/step - ia: 0.3081 - loss: 0.8925 - mae: 0.7026 - rmse: 0.9344 - smape: 1.4310 - val_ia: 0.2547 - val_loss: 0.7927 - val_mae: 0.6680 - val_rmse: 0.7836 - val_smape: 1.3926

Epoch 58/128

479/479 - 1s - 3ms/step - ia: 0.3104 - loss: 0.8871 - mae: 0.7011 - rmse: 0.9315 - smape: 1.4292 - val_ia: 0.2549 - val_loss: 0.7921 - val_mae: 0.6677 - val_rmse: 0.7833 - val_smape: 1.3919

Epoch 59/128

479/479 - 1s - 3ms/step - ia: 0.3094 - loss: 0.8860 - mae: 0.7004 - rmse: 0.9323 - smape: 1.4295 - val_ia: 0.2553 - val_loss: 0.7913 - val_mae: 0.6672 - val_rmse: 0.7828 - val_smape: 1.3899

Epoch 60/128

479/479 - 2s - 4ms/step - ia: 0.3144 - loss: 0.8837 - mae: 0.6987 - rmse: 0.9303 - smape: 1.4224 - val_ia: 0.2556 - val_loss: 0.7906 - val_mae: 0.6671 - val_rmse: 0.7827 - val_smape: 1.3892

Epoch 61/128

479/479 - 3s - 6ms/step - ia: 0.3129 - loss: 0.8828 - mae: 0.6991 - rmse: 0.9297 - smape: 1.4227 - val_ia: 0.2561 - val_loss: 0.7892 - val_mae: 0.6662 - val_rmse: 0.7820 - val_smape: 1.3853

Epoch 62/128

479/479 - 2s - 5ms/step - ia: 0.3121 - loss: 0.8865 - mae: 0.7008 - rmse: 0.9311 - smape: 1.4256 - val_ia: 0.2562 - val_loss: 0.7885 - val_mae: 0.6659 - val_rmse: 0.7816 - val_smape: 1.3845

Epoch 63/128

479/479 - 2s - 5ms/step - ia: 0.3139 - loss: 0.8832 - mae: 0.6993 - rmse: 0.9303 - smape: 1.4206 - val_ia: 0.2565 - val_loss: 0.7879 - val_mae: 0.6654 - val_rmse: 0.7811 - val_smape: 1.3829

Epoch 64/128

479/479 - 3s - 5ms/step - ia: 0.3124 - loss: 0.8824 - mae: 0.6991 - rmse: 0.9291 - smape: 1.4246 - val_ia: 0.2569 - val_loss: 0.7871 - val_mae: 0.6652 - val_rmse: 0.7810 - val_smape: 1.3819

Epoch 65/128

479/479 - 2s - 4ms/step - ia: 0.3162 - loss: 0.8780 - mae: 0.6968 - rmse: 0.9271 - smape: 1.4165 - val_ia: 0.2572 - val_loss: 0.7865 - val_mae: 0.6646 - val_rmse: 0.7805 - val_smape: 1.3796

Epoch 66/128

479/479 - 3s - 7ms/step - ia: 0.3169 - loss: 0.8826 - mae: 0.6978 - rmse: 0.9293 - smape: 1.4145 - val_ia: 0.2574 - val_loss: 0.7863 - val_mae: 0.6643 - val_rmse: 0.7802 - val_smape: 1.3795

Epoch 67/128

479/479 - 3s - 6ms/step - ia: 0.3174 - loss: 0.8827 - mae: 0.6971 - rmse: 0.9283 - smape: 1.4170 - val_ia: 0.2576 - val_loss: 0.7857 - val_mae: 0.6639 - val_rmse: 0.7798 - val_smape: 1.3784

Epoch 68/128

479/479 - 3s - 7ms/step - ia: 0.3170 - loss: 0.8790 - mae: 0.6971 - rmse: 0.9274 - smape: 1.4179 - val_ia: 0.2579 - val_loss: 0.7854 - val_mae: 0.6637 - val_rmse: 0.7796 - val_smape: 1.3779

Epoch 69/128

479/479 - 6s - 12ms/step - ia: 0.3210 - loss: 0.8772 - mae: 0.6952 - rmse: 0.9259 - smape: 1.4119 - val_ia: 0.2581 - val_loss: 0.7851 - val_mae: 0.6634 - val_rmse: 0.7794 - val_smape: 1.3771

Epoch 70/128

479/479 - 4s - 7ms/step - ia: 0.3213 - loss: 0.8767 - mae: 0.6935 - rmse: 0.9260 - smape: 1.4100 - val_ia: 0.2583 - val_loss: 0.7848 - val_mae: 0.6630 - val_rmse: 0.7791 - val_smape: 1.3761

Epoch 71/128

479/479 - 4s - 9ms/step - ia: 0.3183 - loss: 0.8805 - mae: 0.6962 - rmse: 0.9287 - smape: 1.4103 - val_ia: 0.2585 - val_loss: 0.7844 - val_mae: 0.6629 - val_rmse: 0.7789 - val_smape: 1.3758

Epoch 72/128

479/479 - 2s - 4ms/step - ia: 0.3164 - loss: 0.8762 - mae: 0.6962 - rmse: 0.9262 - smape: 1.4142 - val_ia: 0.2588 - val_loss: 0.7837 - val_mae: 0.6625 - val_rmse: 0.7786 - val_smape: 1.3743

Epoch 73/128

479/479 - 2s - 3ms/step - ia: 0.3209 - loss: 0.8789 - mae: 0.6947 - rmse: 0.9279 - smape: 1.4091 - val_ia: 0.2589 - val_loss: 0.7834 - val_mae: 0.6623 - val_rmse: 0.7784 - val_smape: 1.3743

Epoch 74/128

479/479 - 2s - 4ms/step - ia: 0.3194 - loss: 0.8786 - mae: 0.6948 - rmse: 0.9280 - smape: 1.4109 - val_ia: 0.2591 - val_loss: 0.7829 - val_mae: 0.6617 - val_rmse: 0.7779 - val_smape: 1.3726

Epoch 75/128

479/479 - 3s - 7ms/step - ia: 0.3218 - loss: 0.8755 - mae: 0.6933 - rmse: 0.9260 - smape: 1.4080 - val_ia: 0.2592 - val_loss: 0.7824 - val_mae: 0.6616 - val_rmse: 0.7777 - val_smape: 1.3725

Epoch 76/128

479/479 - 4s - 8ms/step - ia: 0.3241 - loss: 0.8742 - mae: 0.6936 - rmse: 0.9240 - smape: 1.4059 - val_ia: 0.2594 - val_loss: 0.7822 - val_mae: 0.6614 - val_rmse: 0.7775 - val_smape: 1.3723

Epoch 77/128

479/479 - 1s - 3ms/step - ia: 0.3197 - loss: 0.8712 - mae: 0.6945 - rmse: 0.9230 - smape: 1.4110 - val_ia: 0.2595 - val_loss: 0.7814 - val_mae: 0.6611 - val_rmse: 0.7772 - val_smape: 1.3708

Epoch 78/128

479/479 - 3s - 5ms/step - ia: 0.3257 - loss: 0.8716 - mae: 0.6920 - rmse: 0.9235 - smape: 1.4031 - val_ia: 0.2598 - val_loss: 0.7808 - val_mae: 0.6608 - val_rmse: 0.7770 - val_smape: 1.3696

Epoch 79/128

479/479 - 3s - 7ms/step - ia: 0.3237 - loss: 0.8739 - mae: 0.6929 - rmse: 0.9251 - smape: 1.4050 - val_ia: 0.2599 - val_loss: 0.7805 - val_mae: 0.6606 - val_rmse: 0.7768 - val_smape: 1.3691

Epoch 80/128

479/479 - 4s - 8ms/step - ia: 0.3269 - loss: 0.8682 - mae: 0.6907 - rmse: 0.9218 - smape: 1.3986 - val_ia: 0.2602 - val_loss: 0.7798 - val_mae: 0.6603 - val_rmse: 0.7766 - val_smape: 1.3678

Epoch 81/128

479/479 - 4s - 9ms/step - ia: 0.3231 - loss: 0.8792 - mae: 0.6940 - rmse: 0.9278 - smape: 1.4054 - val_ia: 0.2601 - val_loss: 0.7801 - val_mae: 0.6604 - val_rmse: 0.7765 - val_smape: 1.3691

Epoch 82/128

479/479 - 4s - 8ms/step - ia: 0.3223 - loss: 0.8730 - mae: 0.6929 - rmse: 0.9259 - smape: 1.4055 - val_ia: 0.2602 - val_loss: 0.7797 - val_mae: 0.6603 - val_rmse: 0.7764 - val_smape: 1.3690

Epoch 83/128

479/479 - 1s - 3ms/step - ia: 0.3266 - loss: 0.8700 - mae: 0.6905 - rmse: 0.9231 - smape: 1.3989 - val_ia: 0.2605 - val_loss: 0.7791 - val_mae: 0.6599 - val_rmse: 0.7761 - val_smape: 1.3674

Epoch 84/128

479/479 - 2s - 3ms/step - ia: 0.3249 - loss: 0.8697 - mae: 0.6909 - rmse: 0.9234 - smape: 1.4001 - val_ia: 0.2606 - val_loss: 0.7790 - val_mae: 0.6599 - val_rmse: 0.7761 - val_smape: 1.3675

Epoch 85/128

479/479 - 5s - 10ms/step - ia: 0.3303 - loss: 0.8602 - mae: 0.6886 - rmse: 0.9177 - smape: 1.3961 - val_ia: 0.2609 - val_loss: 0.7782 - val_mae: 0.6595 - val_rmse: 0.7757 - val_smape: 1.3650

Epoch 86/128

479/479 - 3s - 7ms/step - ia: 0.3255 - loss: 0.8723 - mae: 0.6923 - rmse: 0.9239 - smape: 1.4016 - val_ia: 0.2610 - val_loss: 0.7783 - val_mae: 0.6595 - val_rmse: 0.7757 - val_smape: 1.3658

Epoch 87/128

479/479 - 3s - 6ms/step - ia: 0.3277 - loss: 0.8669 - mae: 0.6895 - rmse: 0.9211 - smape: 1.3951 - val_ia: 0.2612 - val_loss: 0.7775 - val_mae: 0.6592 - val_rmse: 0.7755 - val_smape: 1.3646

Epoch 88/128

479/479 - 3s - 7ms/step - ia: 0.3275 - loss: 0.8691 - mae: 0.6903 - rmse: 0.9217 - smape: 1.3964 - val_ia: 0.2613 - val_loss: 0.7773 - val_mae: 0.6590 - val_rmse: 0.7754 - val_smape: 1.3641

Epoch 89/128

479/479 - 6s - 13ms/step - ia: 0.3256 - loss: 0.8697 - mae: 0.6912 - rmse: 0.9228 - smape: 1.4010 - val_ia: 0.2615 - val_loss: 0.7773 - val_mae: 0.6589 - val_rmse: 0.7752 - val_smape: 1.3637

Epoch 90/128

479/479 - 6s - 12ms/step - ia: 0.3287 - loss: 0.8673 - mae: 0.6896 - rmse: 0.9211 - smape: 1.3958 - val_ia: 0.2616 - val_loss: 0.7768 - val_mae: 0.6585 - val_rmse: 0.7749 - val_smape: 1.3624

Epoch 91/128

479/479 - 6s - 13ms/step - ia: 0.3319 - loss: 0.8622 - mae: 0.6882 - rmse: 0.9178 - smape: 1.3931 - val_ia: 0.2617 - val_loss: 0.7767 - val_mae: 0.6582 - val_rmse: 0.7746 - val_smape: 1.3617

Epoch 92/128

479/479 - 8s - 16ms/step - ia: 0.3327 - loss: 0.8640 - mae: 0.6880 - rmse: 0.9194 - smape: 1.3909 - val_ia: 0.2619 - val_loss: 0.7764 - val_mae: 0.6578 - val_rmse: 0.7743 - val_smape: 1.3602

Epoch 93/128

479/479 - 2s - 5ms/step - ia: 0.3322 - loss: 0.8598 - mae: 0.6878 - rmse: 0.9174 - smape: 1.3904 - val_ia: 0.2621 - val_loss: 0.7758 - val_mae: 0.6577 - val_rmse: 0.7741 - val_smape: 1.3592

Epoch 94/128

479/479 - 5s - 11ms/step - ia: 0.3303 - loss: 0.8727 - mae: 0.6886 - rmse: 0.9240 - smape: 1.3913 - val_ia: 0.2620 - val_loss: 0.7760 - val_mae: 0.6578 - val_rmse: 0.7742 - val_smape: 1.3603

Epoch 95/128

479/479 - 5s - 11ms/step - ia: 0.3312 - loss: 0.8658 - mae: 0.6882 - rmse: 0.9201 - smape: 1.3917 - val_ia: 0.2622 - val_loss: 0.7757 - val_mae: 0.6574 - val_rmse: 0.7739 - val_smape: 1.3591

Epoch 96/128

479/479 - 5s - 11ms/step - ia: 0.3290 - loss: 0.8673 - mae: 0.6888 - rmse: 0.9208 - smape: 1.3967 - val_ia: 0.2622 - val_loss: 0.7753 - val_mae: 0.6574 - val_rmse: 0.7738 - val_smape: 1.3590

Epoch 97/128

479/479 - 4s - 8ms/step - ia: 0.3319 - loss: 0.8637 - mae: 0.6878 - rmse: 0.9191 - smape: 1.3893 - val_ia: 0.2624 - val_loss: 0.7749 - val_mae: 0.6572 - val_rmse: 0.7737 - val_smape: 1.3583

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

120/120 - 8s - 68ms/step - ia: 0.0822 - loss: 1.0044 - mae: 0.7449 - rmse: 0.9989 - smape: 1.7785 - val_ia: 0.2611 - val_loss: 0.9840 - val_mae: 0.7392 - val_rmse: 0.9055 - val_smape: 1.8006

Epoch 2/32

120/120 - 0s - 4ms/step - ia: 0.0899 - loss: 1.0003 - mae: 0.7438 - rmse: 0.9962 - smape: 1.7823 - val_ia: 0.2612 - val_loss: 0.9787 - val_mae: 0.7376 - val_rmse: 0.9031 - val_smape: 1.8055

Epoch 3/32

120/120 - 0s - 4ms/step - ia: 0.0890 - loss: 0.9964 - mae: 0.7422 - rmse: 0.9954 - smape: 1.7835 - val_ia: 0.2613 - val_loss: 0.9736 - val_mae: 0.7355 - val_rmse: 0.9006 - val_smape: 1.8072

Epoch 4/32

120/120 - 0s - 4ms/step - ia: 0.0872 - loss: 0.9925 - mae: 0.7410 - rmse: 0.9937 - smape: 1.7840 - val_ia: 0.2614 - val_loss: 0.9687 - val_mae: 0.7339 - val_rmse: 0.8984 - val_smape: 1.8086

Epoch 5/32

120/120 - 0s - 4ms/step - ia: 0.0913 - loss: 0.9888 - mae: 0.7397 - rmse: 0.9908 - smape: 1.7832 - val_ia: 0.2616 - val_loss: 0.9640 - val_mae: 0.7321 - val_rmse: 0.8962 - val_smape: 1.8071

Epoch 6/32

120/120 - 1s - 8ms/step - ia: 0.0904 - loss: 0.9851 - mae: 0.7385 - rmse: 0.9894 - smape: 1.7797 - val_ia: 0.2617 - val_loss: 0.9592 - val_mae: 0.7304 - val_rmse: 0.8940 - val_smape: 1.8034

Epoch 7/32

120/120 - 1s - 11ms/step - ia: 0.0971 - loss: 0.9814 - mae: 0.7373 - rmse: 0.9871 - smape: 1.7749 - val_ia: 0.2619 - val_loss: 0.9547 - val_mae: 0.7288 - val_rmse: 0.8919 - val_smape: 1.7971

Epoch 8/32

120/120 - 1s - 10ms/step - ia: 0.0968 - loss: 0.9778 - mae: 0.7359 - rmse: 0.9848 - smape: 1.7695 - val_ia: 0.2621 - val_loss: 0.9501 - val_mae: 0.7268 - val_rmse: 0.8896 - val_smape: 1.7898

Epoch 9/32

120/120 - 2s - 15ms/step - ia: 0.0993 - loss: 0.9742 - mae: 0.7345 - rmse: 0.9837 - smape: 1.7615 - val_ia: 0.2624 - val_loss: 0.9457 - val_mae: 0.7253 - val_rmse: 0.8876 - val_smape: 1.7818

Epoch 10/32

120/120 - 2s - 19ms/step - ia: 0.1047 - loss: 0.9706 - mae: 0.7333 - rmse: 0.9814 - smape: 1.7538 - val_ia: 0.2627 - val_loss: 0.9414 - val_mae: 0.7238 - val_rmse: 0.8857 - val_smape: 1.7731

Epoch 11/32

120/120 - 2s - 13ms/step - ia: 0.1132 - loss: 0.9671 - mae: 0.7320 - rmse: 0.9798 - smape: 1.7447 - val_ia: 0.2630 - val_loss: 0.9371 - val_mae: 0.7221 - val_rmse: 0.8837 - val_smape: 1.7631

Epoch 12/32

120/120 - 2s - 14ms/step - ia: 0.1106 - loss: 0.9635 - mae: 0.7309 - rmse: 0.9784 - smape: 1.7355 - val_ia: 0.2634 - val_loss: 0.9328 - val_mae: 0.7206 - val_rmse: 0.8817 - val_smape: 1.7525

Epoch 13/32

120/120 - 2s - 17ms/step - ia: 0.1178 - loss: 0.9600 - mae: 0.7294 - rmse: 0.9764 - smape: 1.7252 - val_ia: 0.2639 - val_loss: 0.9285 - val_mae: 0.7189 - val_rmse: 0.8797 - val_smape: 1.7410

Epoch 14/32

120/120 - 0s - 4ms/step - ia: 0.1202 - loss: 0.9565 - mae: 0.7282 - rmse: 0.9741 - smape: 1.7149 - val_ia: 0.2644 - val_loss: 0.9243 - val_mae: 0.7174 - val_rmse: 0.8778 - val_smape: 1.7295

Epoch 15/32

120/120 - 0s - 4ms/step - ia: 0.1238 - loss: 0.9530 - mae: 0.7269 - rmse: 0.9722 - smape: 1.7039 - val_ia: 0.2649 - val_loss: 0.9201 - val_mae: 0.7158 - val_rmse: 0.8759 - val_smape: 1.7172

Epoch 16/32

120/120 - 1s - 4ms/step - ia: 0.1321 - loss: 0.9496 - mae: 0.7256 - rmse: 0.9711 - smape: 1.6932 - val_ia: 0.2656 - val_loss: 0.9160 - val_mae: 0.7143 - val_rmse: 0.8740 - val_smape: 1.7050

Epoch 17/32

120/120 - 1s - 5ms/step - ia: 0.1347 - loss: 0.9461 - mae: 0.7241 - rmse: 0.9695 - smape: 1.6817 - val_ia: 0.2662 - val_loss: 0.9119 - val_mae: 0.7126 - val_rmse: 0.8720 - val_smape: 1.6922

Epoch 18/32

120/120 - 0s - 3ms/step - ia: 0.1391 - loss: 0.9427 - mae: 0.7228 - rmse: 0.9680 - smape: 1.6704 - val_ia: 0.2669 - val_loss: 0.9079 - val_mae: 0.7112 - val_rmse: 0.8703 - val_smape: 1.6806

Epoch 19/32

120/120 - 0s - 2ms/step - ia: 0.1479 - loss: 0.9393 - mae: 0.7217 - rmse: 0.9664 - smape: 1.6594 - val_ia: 0.2676 - val_loss: 0.9038 - val_mae: 0.7096 - val_rmse: 0.8684 - val_smape: 1.6682

Epoch 20/32

120/120 - 0s - 2ms/step - ia: 0.1514 - loss: 0.9359 - mae: 0.7202 - rmse: 0.9643 - smape: 1.6481 - val_ia: 0.2684 - val_loss: 0.8999 - val_mae: 0.7082 - val_rmse: 0.8667 - val_smape: 1.6563

Epoch 21/32

120/120 - 0s - 3ms/step - ia: 0.1593 - loss: 0.9326 - mae: 0.7190 - rmse: 0.9619 - smape: 1.6372 - val_ia: 0.2692 - val_loss: 0.8960 - val_mae: 0.7068 - val_rmse: 0.8650 - val_smape: 1.6445

Epoch 22/32

120/120 - 0s - 3ms/step - ia: 0.1647 - loss: 0.9293 - mae: 0.7179 - rmse: 0.9607 - smape: 1.6267 - val_ia: 0.2699 - val_loss: 0.8922 - val_mae: 0.7055 - val_rmse: 0.8633 - val_smape: 1.6331

Epoch 23/32

120/120 - 1s - 7ms/step - ia: 0.1690 - loss: 0.9261 - mae: 0.7165 - rmse: 0.9586 - smape: 1.6153 - val_ia: 0.2708 - val_loss: 0.8884 - val_mae: 0.7038 - val_rmse: 0.8615 - val_smape: 1.6206

Epoch 24/32

120/120 - 2s - 14ms/step - ia: 0.1748 - loss: 0.9229 - mae: 0.7151 - rmse: 0.9578 - smape: 1.6042 - val_ia: 0.2717 - val_loss: 0.8847 - val_mae: 0.7021 - val_rmse: 0.8597 - val_smape: 1.6082

Epoch 25/32

120/120 - 3s - 22ms/step - ia: 0.1801 - loss: 0.9197 - mae: 0.7137 - rmse: 0.9554 - smape: 1.5935 - val_ia: 0.2726 - val_loss: 0.8811 - val_mae: 0.7007 - val_rmse: 0.8581 - val_smape: 1.5967

Epoch 26/32

120/120 - 3s - 27ms/step - ia: 0.1872 - loss: 0.9167 - mae: 0.7125 - rmse: 0.9539 - smape: 1.5833 - val_ia: 0.2736 - val_loss: 0.8776 - val_mae: 0.6993 - val_rmse: 0.8565 - val_smape: 1.5854

Epoch 27/32

120/120 - 2s - 14ms/step - ia: 0.1913 - loss: 0.9137 - mae: 0.7113 - rmse: 0.9527 - smape: 1.5730 - val_ia: 0.2746 - val_loss: 0.8742 - val_mae: 0.6978 - val_rmse: 0.8550 - val_smape: 1.5741

Epoch 28/32

120/120 - 2s - 14ms/step - ia: 0.1955 - loss: 0.9108 - mae: 0.7101 - rmse: 0.9521 - smape: 1.5633 - val_ia: 0.2757 - val_loss: 0.8708 - val_mae: 0.6963 - val_rmse: 0.8534 - val_smape: 1.5629

Epoch 29/32

120/120 - 1s - 10ms/step - ia: 0.2038 - loss: 0.9079 - mae: 0.7087 - rmse: 0.9494 - smape: 1.5530 - val_ia: 0.2767 - val_loss: 0.8676 - val_mae: 0.6949 - val_rmse: 0.8519 - val_smape: 1.5524

Epoch 30/32

120/120 - 1s - 11ms/step - ia: 0.2087 - loss: 0.9052 - mae: 0.7077 - rmse: 0.9478 - smape: 1.5440 - val_ia: 0.2777 - val_loss: 0.8644 - val_mae: 0.6936 - val_rmse: 0.8505 - val_smape: 1.5424

Epoch 31/32

120/120 - 1s - 7ms/step - ia: 0.2140 - loss: 0.9025 - mae: 0.7066 - rmse: 0.9459 - smape: 1.5347 - val_ia: 0.2789 - val_loss: 0.8613 - val_mae: 0.6921 - val_rmse: 0.8490 - val_smape: 1.5317

Epoch 32/32

120/120 - 1s - 7ms/step - ia: 0.2194 - loss: 0.8999 - mae: 0.7052 - rmse: 0.9457 - smape: 1.5252 - val_ia: 0.2800 - val_loss: 0.8584 - val_mae: 0.6907 - val_rmse: 0.8477 - val_smape: 1.5220

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 36s 269ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 80%|████████  | 40/50 [3:04:04<38:45, 232.57s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 9s - 9ms/step - ia: 0.2933 - loss: 1.6692 - mae: 1.0047 - rmse: 1.2706 - smape: 1.4767 - val_ia: 0.2434 - val_loss: 0.9979 - val_mae: 0.7645 - val_rmse: 0.8905 - val_smape: 1.4125

Epoch 2/128

958/958 - 7s - 7ms/step - ia: 0.3364 - loss: 1.1900 - mae: 0.8318 - rmse: 1.0724 - smape: 1.4027 - val_ia: 0.2489 - val_loss: 0.8931 - val_mae: 0.7069 - val_rmse: 0.8215 - val_smape: 1.3391

Epoch 3/128

958/958 - 5s - 5ms/step - ia: 0.3454 - loss: 1.0544 - mae: 0.7744 - rmse: 1.0086 - smape: 1.3836 - val_ia: 0.2529 - val_loss: 0.8454 - val_mae: 0.6844 - val_rmse: 0.7909 - val_smape: 1.3356

Epoch 4/128

958/958 - 5s - 6ms/step - ia: 0.3469 - loss: 0.9880 - mae: 0.7419 - rmse: 0.9757 - smape: 1.3777 - val_ia: 0.2532 - val_loss: 0.8205 - val_mae: 0.6730 - val_rmse: 0.7749 - val_smape: 1.3372

Epoch 5/128

958/958 - 5s - 5ms/step - ia: 0.3457 - loss: 0.9418 - mae: 0.7230 - rmse: 0.9520 - smape: 1.3810 - val_ia: 0.2531 - val_loss: 0.8038 - val_mae: 0.6662 - val_rmse: 0.7652 - val_smape: 1.3407

Epoch 6/128

958/958 - 4s - 4ms/step - ia: 0.3459 - loss: 0.9180 - mae: 0.7106 - rmse: 0.9386 - smape: 1.3797 - val_ia: 0.2542 - val_loss: 0.7901 - val_mae: 0.6598 - val_rmse: 0.7568 - val_smape: 1.3345

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.3447 - loss: 0.8955 - mae: 0.7024 - rmse: 0.9286 - smape: 1.3809 - val_ia: 0.2543 - val_loss: 0.7822 - val_mae: 0.6569 - val_rmse: 0.7523 - val_smape: 1.3385

Epoch 8/128

958/958 - 6s - 6ms/step - ia: 0.3485 - loss: 0.8823 - mae: 0.6946 - rmse: 0.9207 - smape: 1.3739 - val_ia: 0.2548 - val_loss: 0.7784 - val_mae: 0.6550 - val_rmse: 0.7492 - val_smape: 1.3376

Epoch 9/128

958/958 - 6s - 6ms/step - ia: 0.3463 - loss: 0.8773 - mae: 0.6913 - rmse: 0.9194 - smape: 1.3750 - val_ia: 0.2545 - val_loss: 0.7752 - val_mae: 0.6540 - val_rmse: 0.7476 - val_smape: 1.3422

Epoch 10/128

958/958 - 4s - 4ms/step - ia: 0.3465 - loss: 0.8648 - mae: 0.6888 - rmse: 0.9119 - smape: 1.3794 - val_ia: 0.2563 - val_loss: 0.7687 - val_mae: 0.6510 - val_rmse: 0.7445 - val_smape: 1.3266

Epoch 11/128

958/958 - 4s - 4ms/step - ia: 0.3494 - loss: 0.8602 - mae: 0.6860 - rmse: 0.9096 - smape: 1.3756 - val_ia: 0.2571 - val_loss: 0.7651 - val_mae: 0.6498 - val_rmse: 0.7429 - val_smape: 1.3270

Epoch 12/128

958/958 - 5s - 5ms/step - ia: 0.3477 - loss: 0.8648 - mae: 0.6861 - rmse: 0.9118 - smape: 1.3778 - val_ia: 0.2572 - val_loss: 0.7642 - val_mae: 0.6497 - val_rmse: 0.7423 - val_smape: 1.3292

Epoch 13/128

958/958 - 7s - 7ms/step - ia: 0.3494 - loss: 0.8577 - mae: 0.6840 - rmse: 0.9071 - smape: 1.3794 - val_ia: 0.2569 - val_loss: 0.7634 - val_mae: 0.6483 - val_rmse: 0.7403 - val_smape: 1.3320

Epoch 14/128

958/958 - 10s - 11ms/step - ia: 0.3521 - loss: 0.8505 - mae: 0.6800 - rmse: 0.9034 - smape: 1.3735 - val_ia: 0.2573 - val_loss: 0.7626 - val_mae: 0.6479 - val_rmse: 0.7400 - val_smape: 1.3266

Epoch 15/128

958/958 - 9s - 9ms/step - ia: 0.3516 - loss: 0.8497 - mae: 0.6799 - rmse: 0.9026 - smape: 1.3761 - val_ia: 0.2580 - val_loss: 0.7588 - val_mae: 0.6465 - val_rmse: 0.7388 - val_smape: 1.3198

Epoch 16/128

958/958 - 6s - 6ms/step - ia: 0.3536 - loss: 0.8491 - mae: 0.6787 - rmse: 0.9024 - smape: 1.3715 - val_ia: 0.2581 - val_loss: 0.7584 - val_mae: 0.6463 - val_rmse: 0.7383 - val_smape: 1.3249

Epoch 17/128

958/958 - 12s - 12ms/step - ia: 0.3535 - loss: 0.8456 - mae: 0.6774 - rmse: 0.9016 - smape: 1.3734 - val_ia: 0.2582 - val_loss: 0.7575 - val_mae: 0.6463 - val_rmse: 0.7382 - val_smape: 1.3256

Epoch 18/128

958/958 - 5s - 5ms/step - ia: 0.3575 - loss: 0.8405 - mae: 0.6744 - rmse: 0.8984 - smape: 1.3705 - val_ia: 0.2593 - val_loss: 0.7550 - val_mae: 0.6456 - val_rmse: 0.7375 - val_smape: 1.3201

Epoch 19/128

958/958 - 8s - 9ms/step - ia: 0.3545 - loss: 0.8413 - mae: 0.6769 - rmse: 0.8990 - smape: 1.3749 - val_ia: 0.2590 - val_loss: 0.7540 - val_mae: 0.6443 - val_rmse: 0.7363 - val_smape: 1.3200

Epoch 20/128

958/958 - 7s - 7ms/step - ia: 0.3547 - loss: 0.8429 - mae: 0.6770 - rmse: 0.9000 - smape: 1.3751 - val_ia: 0.2593 - val_loss: 0.7546 - val_mae: 0.6455 - val_rmse: 0.7372 - val_smape: 1.3237

Epoch 21/128

958/958 - 11s - 12ms/step - ia: 0.3525 - loss: 0.8467 - mae: 0.6779 - rmse: 0.9014 - smape: 1.3760 - val_ia: 0.2590 - val_loss: 0.7554 - val_mae: 0.6437 - val_rmse: 0.7354 - val_smape: 1.3186

Epoch 22/128

958/958 - 9s - 10ms/step - ia: 0.3530 - loss: 0.8452 - mae: 0.6771 - rmse: 0.9010 - smape: 1.3767 - val_ia: 0.2593 - val_loss: 0.7548 - val_mae: 0.6448 - val_rmse: 0.7363 - val_smape: 1.3247

Epoch 23/128

958/958 - 11s - 11ms/step - ia: 0.3559 - loss: 0.8406 - mae: 0.6743 - rmse: 0.8982 - smape: 1.3722 - val_ia: 0.2603 - val_loss: 0.7514 - val_mae: 0.6437 - val_rmse: 0.7353 - val_smape: 1.3197

Epoch 24/128

958/958 - 11s - 12ms/step - ia: 0.3563 - loss: 0.8344 - mae: 0.6746 - rmse: 0.8953 - smape: 1.3770 - val_ia: 0.2606 - val_loss: 0.7512 - val_mae: 0.6440 - val_rmse: 0.7362 - val_smape: 1.3164

Epoch 25/128

958/958 - 8s - 8ms/step - ia: 0.3585 - loss: 0.8361 - mae: 0.6749 - rmse: 0.8959 - smape: 1.3781 - val_ia: 0.2591 - val_loss: 0.7542 - val_mae: 0.6438 - val_rmse: 0.7352 - val_smape: 1.3255

Epoch 26/128

958/958 - 6s - 6ms/step - ia: 0.3535 - loss: 0.8367 - mae: 0.6745 - rmse: 0.8963 - smape: 1.3793 - val_ia: 0.2606 - val_loss: 0.7505 - val_mae: 0.6418 - val_rmse: 0.7337 - val_smape: 1.3128

Epoch 27/128

958/958 - 7s - 7ms/step - ia: 0.3549 - loss: 0.8397 - mae: 0.6757 - rmse: 0.8978 - smape: 1.3804 - val_ia: 0.2607 - val_loss: 0.7515 - val_mae: 0.6432 - val_rmse: 0.7345 - val_smape: 1.3197

Epoch 28/128

958/958 - 3s - 3ms/step - ia: 0.3536 - loss: 0.8365 - mae: 0.6748 - rmse: 0.8955 - smape: 1.3835 - val_ia: 0.2601 - val_loss: 0.7523 - val_mae: 0.6444 - val_rmse: 0.7360 - val_smape: 1.3183

Epoch 29/128

958/958 - 4s - 4ms/step - ia: 0.3587 - loss: 0.8341 - mae: 0.6741 - rmse: 0.8953 - smape: 1.3760 - val_ia: 0.2606 - val_loss: 0.7509 - val_mae: 0.6432 - val_rmse: 0.7347 - val_smape: 1.3179

Epoch 30/128

958/958 - 5s - 5ms/step - ia: 0.3553 - loss: 0.8352 - mae: 0.6751 - rmse: 0.8965 - smape: 1.3808 - val_ia: 0.2604 - val_loss: 0.7517 - val_mae: 0.6432 - val_rmse: 0.7347 - val_smape: 1.3166

Epoch 31/128

958/958 - 6s - 6ms/step - ia: 0.3588 - loss: 0.8316 - mae: 0.6730 - rmse: 0.8936 - smape: 1.3771 - val_ia: 0.2612 - val_loss: 0.7497 - val_mae: 0.6429 - val_rmse: 0.7344 - val_smape: 1.3128

Epoch 32/128

958/958 - 5s - 6ms/step - ia: 0.3581 - loss: 0.8342 - mae: 0.6733 - rmse: 0.8944 - smape: 1.3754 - val_ia: 0.2614 - val_loss: 0.7490 - val_mae: 0.6420 - val_rmse: 0.7336 - val_smape: 1.3089

Epoch 33/128

958/958 - 10s - 11ms/step - ia: 0.3605 - loss: 0.8283 - mae: 0.6717 - rmse: 0.8922 - smape: 1.3724 - val_ia: 0.2608 - val_loss: 0.7512 - val_mae: 0.6439 - val_rmse: 0.7352 - val_smape: 1.3161

Epoch 34/128

958/958 - 2s - 2ms/step - ia: 0.3587 - loss: 0.8309 - mae: 0.6717 - rmse: 0.8948 - smape: 1.3738 - val_ia: 0.2612 - val_loss: 0.7493 - val_mae: 0.6429 - val_rmse: 0.7342 - val_smape: 1.3128

Epoch 35/128

958/958 - 2s - 2ms/step - ia: 0.3594 - loss: 0.8307 - mae: 0.6731 - rmse: 0.8931 - smape: 1.3740 - val_ia: 0.2615 - val_loss: 0.7481 - val_mae: 0.6416 - val_rmse: 0.7328 - val_smape: 1.3108

Epoch 36/128

958/958 - 4s - 4ms/step - ia: 0.3571 - loss: 0.8323 - mae: 0.6734 - rmse: 0.8928 - smape: 1.3788 - val_ia: 0.2610 - val_loss: 0.7483 - val_mae: 0.6413 - val_rmse: 0.7326 - val_smape: 1.3101

Epoch 37/128

958/958 - 5s - 6ms/step - ia: 0.3599 - loss: 0.8274 - mae: 0.6706 - rmse: 0.8915 - smape: 1.3744 - val_ia: 0.2608 - val_loss: 0.7495 - val_mae: 0.6424 - val_rmse: 0.7337 - val_smape: 1.3094

Epoch 38/128

958/958 - 6s - 6ms/step - ia: 0.3586 - loss: 0.8292 - mae: 0.6737 - rmse: 0.8924 - smape: 1.3766 - val_ia: 0.2612 - val_loss: 0.7499 - val_mae: 0.6428 - val_rmse: 0.7340 - val_smape: 1.3119

Epoch 39/128

958/958 - 7s - 7ms/step - ia: 0.3592 - loss: 0.8303 - mae: 0.6722 - rmse: 0.8928 - smape: 1.3749 - val_ia: 0.2612 - val_loss: 0.7492 - val_mae: 0.6430 - val_rmse: 0.7345 - val_smape: 1.3114

Epoch 40/128

958/958 - 11s - 11ms/step - ia: 0.3576 - loss: 0.8323 - mae: 0.6733 - rmse: 0.8945 - smape: 1.3802 - val_ia: 0.2612 - val_loss: 0.7486 - val_mae: 0.6420 - val_rmse: 0.7333 - val_smape: 1.3108

Epoch 41/128

958/958 - 4s - 4ms/step - ia: 0.3589 - loss: 0.8299 - mae: 0.6729 - rmse: 0.8924 - smape: 1.3810 - val_ia: 0.2603 - val_loss: 0.7495 - val_mae: 0.6427 - val_rmse: 0.7340 - val_smape: 1.3162

Epoch 42/128

958/958 - 7s - 7ms/step - ia: 0.3649 - loss: 0.8243 - mae: 0.6699 - rmse: 0.8903 - smape: 1.3730 - val_ia: 0.2613 - val_loss: 0.7481 - val_mae: 0.6415 - val_rmse: 0.7328 - val_smape: 1.3110

Epoch 43/128

958/958 - 11s - 12ms/step - ia: 0.3608 - loss: 0.8274 - mae: 0.6711 - rmse: 0.8902 - smape: 1.3775 - val_ia: 0.2612 - val_loss: 0.7488 - val_mae: 0.6426 - val_rmse: 0.7341 - val_smape: 1.3097

Epoch 44/128

958/958 - 5s - 5ms/step - ia: 0.3597 - loss: 0.8311 - mae: 0.6725 - rmse: 0.8940 - smape: 1.3766 - val_ia: 0.2607 - val_loss: 0.7489 - val_mae: 0.6412 - val_rmse: 0.7325 - val_smape: 1.3089

Epoch 45/128

958/958 - 7s - 8ms/step - ia: 0.3608 - loss: 0.8238 - mae: 0.6710 - rmse: 0.8883 - smape: 1.3775 - val_ia: 0.2610 - val_loss: 0.7491 - val_mae: 0.6419 - val_rmse: 0.7337 - val_smape: 1.3059

Epoch 46/128

958/958 - 7s - 7ms/step - ia: 0.3614 - loss: 0.8276 - mae: 0.6714 - rmse: 0.8917 - smape: 1.3745 - val_ia: 0.2615 - val_loss: 0.7478 - val_mae: 0.6406 - val_rmse: 0.7322 - val_smape: 1.3026

Epoch 47/128

958/958 - 10s - 11ms/step - ia: 0.3620 - loss: 0.8243 - mae: 0.6705 - rmse: 0.8897 - smape: 1.3740 - val_ia: 0.2615 - val_loss: 0.7473 - val_mae: 0.6406 - val_rmse: 0.7319 - val_smape: 1.3017

Epoch 48/128

958/958 - 9s - 10ms/step - ia: 0.3626 - loss: 0.8253 - mae: 0.6701 - rmse: 0.8907 - smape: 1.3710 - val_ia: 0.2609 - val_loss: 0.7487 - val_mae: 0.6426 - val_rmse: 0.7338 - val_smape: 1.3113

Epoch 49/128

958/958 - 10s - 10ms/step - ia: 0.3637 - loss: 0.8240 - mae: 0.6695 - rmse: 0.8904 - smape: 1.3716 - val_ia: 0.2611 - val_loss: 0.7482 - val_mae: 0.6420 - val_rmse: 0.7333 - val_smape: 1.3091

Epoch 50/128

958/958 - 7s - 8ms/step - ia: 0.3643 - loss: 0.8227 - mae: 0.6693 - rmse: 0.8886 - smape: 1.3686 - val_ia: 0.2614 - val_loss: 0.7472 - val_mae: 0.6411 - val_rmse: 0.7325 - val_smape: 1.3041

Epoch 51/128

958/958 - 9s - 9ms/step - ia: 0.3626 - loss: 0.8291 - mae: 0.6709 - rmse: 0.8925 - smape: 1.3745 - val_ia: 0.2617 - val_loss: 0.7468 - val_mae: 0.6405 - val_rmse: 0.7319 - val_smape: 1.3044

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.3648 - loss: 0.8232 - mae: 0.6698 - rmse: 0.8883 - smape: 1.3722 - val_ia: 0.2607 - val_loss: 0.7489 - val_mae: 0.6414 - val_rmse: 0.7326 - val_smape: 1.3084

Epoch 53/128

958/958 - 4s - 4ms/step - ia: 0.3631 - loss: 0.8252 - mae: 0.6703 - rmse: 0.8907 - smape: 1.3747 - val_ia: 0.2625 - val_loss: 0.7455 - val_mae: 0.6406 - val_rmse: 0.7323 - val_smape: 1.3009

Epoch 54/128

958/958 - 4s - 4ms/step - ia: 0.3602 - loss: 0.8275 - mae: 0.6726 - rmse: 0.8922 - smape: 1.3799 - val_ia: 0.2614 - val_loss: 0.7470 - val_mae: 0.6410 - val_rmse: 0.7323 - val_smape: 1.3091

Epoch 55/128

958/958 - 6s - 6ms/step - ia: 0.3613 - loss: 0.8256 - mae: 0.6714 - rmse: 0.8911 - smape: 1.3800 - val_ia: 0.2614 - val_loss: 0.7468 - val_mae: 0.6401 - val_rmse: 0.7314 - val_smape: 1.3091

Epoch 56/128

958/958 - 6s - 6ms/step - ia: 0.3645 - loss: 0.8238 - mae: 0.6694 - rmse: 0.8893 - smape: 1.3772 - val_ia: 0.2626 - val_loss: 0.7458 - val_mae: 0.6408 - val_rmse: 0.7322 - val_smape: 1.3035

Epoch 57/128

958/958 - 5s - 5ms/step - ia: 0.3641 - loss: 0.8223 - mae: 0.6699 - rmse: 0.8885 - smape: 1.3760 - val_ia: 0.2622 - val_loss: 0.7459 - val_mae: 0.6399 - val_rmse: 0.7315 - val_smape: 1.3004

Epoch 58/128

958/958 - 4s - 4ms/step - ia: 0.3620 - loss: 0.8273 - mae: 0.6710 - rmse: 0.8920 - smape: 1.3755 - val_ia: 0.2614 - val_loss: 0.7476 - val_mae: 0.6414 - val_rmse: 0.7328 - val_smape: 1.3060

Epoch 59/128

958/958 - 5s - 5ms/step - ia: 0.3625 - loss: 0.8272 - mae: 0.6704 - rmse: 0.8912 - smape: 1.3780 - val_ia: 0.2615 - val_loss: 0.7470 - val_mae: 0.6418 - val_rmse: 0.7330 - val_smape: 1.3115

Epoch 60/128

958/958 - 8s - 8ms/step - ia: 0.3628 - loss: 0.8271 - mae: 0.6709 - rmse: 0.8915 - smape: 1.3784 - val_ia: 0.2619 - val_loss: 0.7462 - val_mae: 0.6401 - val_rmse: 0.7311 - val_smape: 1.3103

Epoch 61/128

958/958 - 6s - 6ms/step - ia: 0.3606 - loss: 0.8247 - mae: 0.6695 - rmse: 0.8894 - smape: 1.3835 - val_ia: 0.2609 - val_loss: 0.7485 - val_mae: 0.6412 - val_rmse: 0.7326 - val_smape: 1.3094

Epoch 62/128

958/958 - 9s - 9ms/step - ia: 0.3658 - loss: 0.8223 - mae: 0.6688 - rmse: 0.8887 - smape: 1.3769 - val_ia: 0.2615 - val_loss: 0.7474 - val_mae: 0.6412 - val_rmse: 0.7325 - val_smape: 1.3053

Epoch 63/128

958/958 - 5s - 5ms/step - ia: 0.3641 - loss: 0.8253 - mae: 0.6708 - rmse: 0.8899 - smape: 1.3783 - val_ia: 0.2613 - val_loss: 0.7480 - val_mae: 0.6423 - val_rmse: 0.7334 - val_smape: 1.3140

Epoch 64/128

958/958 - 4s - 4ms/step - ia: 0.3630 - loss: 0.8225 - mae: 0.6702 - rmse: 0.8874 - smape: 1.3796 - val_ia: 0.2616 - val_loss: 0.7473 - val_mae: 0.6405 - val_rmse: 0.7318 - val_smape: 1.3055

Epoch 65/128

958/958 - 4s - 4ms/step - ia: 0.3638 - loss: 0.8241 - mae: 0.6701 - rmse: 0.8887 - smape: 1.3783 - val_ia: 0.2621 - val_loss: 0.7463 - val_mae: 0.6411 - val_rmse: 0.7323 - val_smape: 1.3085

Epoch 66/128

958/958 - 4s - 5ms/step - ia: 0.3613 - loss: 0.8242 - mae: 0.6704 - rmse: 0.8914 - smape: 1.3800 - val_ia: 0.2622 - val_loss: 0.7455 - val_mae: 0.6404 - val_rmse: 0.7319 - val_smape: 1.3055

Epoch 67/128

958/958 - 5s - 5ms/step - ia: 0.3669 - loss: 0.8174 - mae: 0.6676 - rmse: 0.8866 - smape: 1.3756 - val_ia: 0.2622 - val_loss: 0.7461 - val_mae: 0.6408 - val_rmse: 0.7327 - val_smape: 1.3016

Epoch 68/128

958/958 - 5s - 6ms/step - ia: 0.3659 - loss: 0.8232 - mae: 0.6683 - rmse: 0.8892 - smape: 1.3728 - val_ia: 0.2618 - val_loss: 0.7467 - val_mae: 0.6403 - val_rmse: 0.7317 - val_smape: 1.3041

Epoch 68: early stopping

Restoring model weights from the end of the best epoch: 53.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:05 484ms/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 75/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 82%|████████▏ | 41/50 [3:11:25<44:15, 295.02s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/64

1915/1915 - 61s - 32ms/step - ia: 0.3515 - loss: 1.0037 - mae: 0.7366 - rmse: 0.9559 - smape: 1.3537 - val_ia: 0.2409 - val_loss: 0.7923 - val_mae: 0.6704 - val_rmse: 0.7364 - val_smape: 1.3603

Epoch 2/64

1915/1915 - 13s - 7ms/step - ia: 0.3472 - loss: 0.9049 - mae: 0.7055 - rmse: 0.9177 - smape: 1.3672 - val_ia: 0.2377 - val_loss: 0.8137 - val_mae: 0.6769 - val_rmse: 0.7391 - val_smape: 1.4527

Epoch 3/64

1915/1915 - 14s - 7ms/step - ia: 0.3396 - loss: 0.9266 - mae: 0.7134 - rmse: 0.9276 - smape: 1.3790 - val_ia: 0.2348 - val_loss: 0.8108 - val_mae: 0.6707 - val_rmse: 0.7316 - val_smape: 1.4377

Epoch 4/64

1915/1915 - 13s - 7ms/step - ia: 0.3397 - loss: 0.9280 - mae: 0.7152 - rmse: 0.9279 - smape: 1.3813 - val_ia: 0.2402 - val_loss: 0.7896 - val_mae: 0.6665 - val_rmse: 0.7288 - val_smape: 1.4085

Epoch 5/64

1915/1915 - 20s - 11ms/step - ia: 0.3442 - loss: 0.9171 - mae: 0.7110 - rmse: 0.9228 - smape: 1.3726 - val_ia: 0.2428 - val_loss: 0.8074 - val_mae: 0.6755 - val_rmse: 0.7450 - val_smape: 1.3428

Epoch 6/64

1915/1915 - 21s - 11ms/step - ia: 0.3421 - loss: 0.9319 - mae: 0.7175 - rmse: 0.9303 - smape: 1.3793 - val_ia: 0.2278 - val_loss: 0.8763 - val_mae: 0.6981 - val_rmse: 0.7586 - val_smape: 1.5354

Epoch 7/64

1915/1915 - 10s - 5ms/step - ia: 0.3361 - loss: 0.9383 - mae: 0.7199 - rmse: 0.9348 - smape: 1.3854 - val_ia: 0.2357 - val_loss: 0.8038 - val_mae: 0.6652 - val_rmse: 0.7346 - val_smape: 1.3766

Epoch 8/64

1915/1915 - 7s - 4ms/step - ia: 0.3382 - loss: 0.9294 - mae: 0.7180 - rmse: 0.9292 - smape: 1.3899 - val_ia: 0.2425 - val_loss: 0.7782 - val_mae: 0.6511 - val_rmse: 0.7206 - val_smape: 1.2858

Epoch 9/64

1915/1915 - 8s - 4ms/step - ia: 0.3396 - loss: 0.9280 - mae: 0.7155 - rmse: 0.9292 - smape: 1.3842 - val_ia: 0.2477 - val_loss: 0.7823 - val_mae: 0.6630 - val_rmse: 0.7313 - val_smape: 1.3145

Epoch 10/64

1915/1915 - 7s - 4ms/step - ia: 0.3373 - loss: 0.9371 - mae: 0.7176 - rmse: 0.9340 - smape: 1.3860 - val_ia: 0.2130 - val_loss: 0.9867 - val_mae: 0.7475 - val_rmse: 0.8106 - val_smape: 1.6622

Epoch 11/64

1915/1915 - 10s - 5ms/step - ia: 0.3399 - loss: 0.9337 - mae: 0.7174 - rmse: 0.9326 - smape: 1.3831 - val_ia: 0.2389 - val_loss: 0.7865 - val_mae: 0.6525 - val_rmse: 0.7209 - val_smape: 1.3263

Epoch 12/64

1915/1915 - 7s - 4ms/step - ia: 0.3381 - loss: 0.9321 - mae: 0.7169 - rmse: 0.9306 - smape: 1.3839 - val_ia: 0.2582 - val_loss: 0.7814 - val_mae: 0.6533 - val_rmse: 0.7328 - val_smape: 1.2077

Epoch 13/64

1915/1915 - 12s - 6ms/step - ia: 0.3412 - loss: 0.9289 - mae: 0.7152 - rmse: 0.9290 - smape: 1.3793 - val_ia: 0.2497 - val_loss: 0.8266 - val_mae: 0.6576 - val_rmse: 0.7342 - val_smape: 1.1740

Epoch 14/64

1915/1915 - 12s - 6ms/step - ia: 0.3411 - loss: 0.9293 - mae: 0.7144 - rmse: 0.9298 - smape: 1.3774 - val_ia: 0.2474 - val_loss: 0.7926 - val_mae: 0.6600 - val_rmse: 0.7260 - val_smape: 1.3520

Epoch 15/64

1915/1915 - 13s - 7ms/step - ia: 0.3413 - loss: 0.9300 - mae: 0.7163 - rmse: 0.9298 - smape: 1.3824 - val_ia: 0.2259 - val_loss: 0.8943 - val_mae: 0.7072 - val_rmse: 0.7675 - val_smape: 1.5952

Epoch 16/64

1915/1915 - 12s - 6ms/step - ia: 0.3404 - loss: 0.9241 - mae: 0.7161 - rmse: 0.9269 - smape: 1.3821 - val_ia: 0.2474 - val_loss: 0.9003 - val_mae: 0.7075 - val_rmse: 0.7837 - val_smape: 1.2427

Epoch 17/64

1915/1915 - 12s - 6ms/step - ia: 0.3377 - loss: 0.9411 - mae: 0.7214 - rmse: 0.9343 - smape: 1.3859 - val_ia: 0.2196 - val_loss: 0.9107 - val_mae: 0.7352 - val_rmse: 0.7942 - val_smape: 1.6878

Epoch 18/64

1915/1915 - 12s - 7ms/step - ia: 0.3388 - loss: 0.9275 - mae: 0.7154 - rmse: 0.9276 - smape: 1.3809 - val_ia: 0.2568 - val_loss: 0.8043 - val_mae: 0.6564 - val_rmse: 0.7377 - val_smape: 1.1828

Epoch 19/64

1915/1915 - 7s - 4ms/step - ia: 0.3406 - loss: 0.9310 - mae: 0.7163 - rmse: 0.9299 - smape: 1.3834 - val_ia: 0.2582 - val_loss: 0.7715 - val_mae: 0.6398 - val_rmse: 0.7125 - val_smape: 1.2285

Epoch 20/64

1915/1915 - 10s - 5ms/step - ia: 0.3399 - loss: 0.9349 - mae: 0.7172 - rmse: 0.9305 - smape: 1.3849 - val_ia: 0.2495 - val_loss: 0.8251 - val_mae: 0.6666 - val_rmse: 0.7432 - val_smape: 1.2701

Epoch 21/64

1915/1915 - 12s - 6ms/step - ia: 0.3422 - loss: 0.9216 - mae: 0.7122 - rmse: 0.9244 - smape: 1.3793 - val_ia: 0.2576 - val_loss: 0.7766 - val_mae: 0.6506 - val_rmse: 0.7226 - val_smape: 1.2531

Epoch 22/64

1915/1915 - 14s - 7ms/step - ia: 0.3412 - loss: 0.9275 - mae: 0.7145 - rmse: 0.9272 - smape: 1.3860 - val_ia: 0.2269 - val_loss: 0.8439 - val_mae: 0.6951 - val_rmse: 0.7556 - val_smape: 1.5157

Epoch 23/64

1915/1915 - 9s - 4ms/step - ia: 0.3419 - loss: 0.9291 - mae: 0.7153 - rmse: 0.9276 - smape: 1.3814 - val_ia: 0.2542 - val_loss: 0.8043 - val_mae: 0.6528 - val_rmse: 0.7278 - val_smape: 1.2210

Epoch 24/64

1915/1915 - 9s - 5ms/step - ia: 0.3403 - loss: 0.9209 - mae: 0.7145 - rmse: 0.9262 - smape: 1.3833 - val_ia: 0.2423 - val_loss: 0.7905 - val_mae: 0.6666 - val_rmse: 0.7388 - val_smape: 1.3036

Epoch 25/64

1915/1915 - 11s - 6ms/step - ia: 0.3437 - loss: 0.9333 - mae: 0.7175 - rmse: 0.9312 - smape: 1.3740 - val_ia: 0.2440 - val_loss: 0.8675 - val_mae: 0.6902 - val_rmse: 0.7746 - val_smape: 1.2413

Epoch 26/64

1915/1915 - 11s - 6ms/step - ia: 0.3397 - loss: 0.9312 - mae: 0.7162 - rmse: 0.9302 - smape: 1.3802 - val_ia: 0.2474 - val_loss: 0.8027 - val_mae: 0.6573 - val_rmse: 0.7261 - val_smape: 1.2868

Epoch 27/64

1915/1915 - 21s - 11ms/step - ia: 0.3367 - loss: 0.9387 - mae: 0.7193 - rmse: 0.9325 - smape: 1.3890 - val_ia: 0.2292 - val_loss: 0.8818 - val_mae: 0.7136 - val_rmse: 0.7759 - val_smape: 1.4974

Epoch 28/64

1915/1915 - 12s - 6ms/step - ia: 0.3391 - loss: 0.9268 - mae: 0.7154 - rmse: 0.9290 - smape: 1.3831 - val_ia: 0.2483 - val_loss: 0.7627 - val_mae: 0.6432 - val_rmse: 0.7111 - val_smape: 1.2863

Epoch 29/64

1915/1915 - 10s - 5ms/step - ia: 0.3452 - loss: 0.9298 - mae: 0.7148 - rmse: 0.9297 - smape: 1.3728 - val_ia: 0.2231 - val_loss: 0.8759 - val_mae: 0.7208 - val_rmse: 0.7794 - val_smape: 1.6201

Epoch 30/64

1915/1915 - 12s - 6ms/step - ia: 0.3409 - loss: 0.9241 - mae: 0.7144 - rmse: 0.9277 - smape: 1.3789 - val_ia: 0.2447 - val_loss: 0.7808 - val_mae: 0.6516 - val_rmse: 0.7210 - val_smape: 1.3011

Epoch 31/64

1915/1915 - 11s - 6ms/step - ia: 0.3363 - loss: 0.9295 - mae: 0.7178 - rmse: 0.9299 - smape: 1.3855 - val_ia: 0.2238 - val_loss: 0.9104 - val_mae: 0.7152 - val_rmse: 0.7759 - val_smape: 1.5864

Epoch 32/64

1915/1915 - 12s - 6ms/step - ia: 0.3433 - loss: 0.9273 - mae: 0.7147 - rmse: 0.9276 - smape: 1.3747 - val_ia: 0.2499 - val_loss: 0.7747 - val_mae: 0.6468 - val_rmse: 0.7131 - val_smape: 1.3046

Epoch 33/64

1915/1915 - 11s - 6ms/step - ia: 0.3363 - loss: 0.9327 - mae: 0.7197 - rmse: 0.9324 - smape: 1.3893 - val_ia: 0.2336 - val_loss: 0.9369 - val_mae: 0.7293 - val_rmse: 0.8095 - val_smape: 1.3278

Epoch 34/64

1915/1915 - 11s - 6ms/step - ia: 0.3394 - loss: 0.9364 - mae: 0.7185 - rmse: 0.9322 - smape: 1.3831 - val_ia: 0.2296 - val_loss: 0.8597 - val_mae: 0.7020 - val_rmse: 0.7691 - val_smape: 1.4324

Epoch 35/64

1915/1915 - 21s - 11ms/step - ia: 0.3363 - loss: 0.9300 - mae: 0.7164 - rmse: 0.9297 - smape: 1.3876 - val_ia: 0.2580 - val_loss: 0.7802 - val_mae: 0.6484 - val_rmse: 0.7259 - val_smape: 1.2030

Epoch 36/64

1915/1915 - 13s - 7ms/step - ia: 0.3395 - loss: 0.9344 - mae: 0.7185 - rmse: 0.9332 - smape: 1.3861 - val_ia: 0.2251 - val_loss: 0.9490 - val_mae: 0.7235 - val_rmse: 0.7864 - val_smape: 1.6645

Epoch 37/64

1915/1915 - 12s - 6ms/step - ia: 0.3439 - loss: 0.9272 - mae: 0.7151 - rmse: 0.9279 - smape: 1.3763 - val_ia: 0.2165 - val_loss: 0.9457 - val_mae: 0.7478 - val_rmse: 0.8135 - val_smape: 1.5166

Epoch 38/64

1915/1915 - 12s - 6ms/step - ia: 0.3420 - loss: 0.9247 - mae: 0.7144 - rmse: 0.9266 - smape: 1.3815 - val_ia: 0.2274 - val_loss: 0.9147 - val_mae: 0.7108 - val_rmse: 0.7734 - val_smape: 1.5423

Epoch 39/64

1915/1915 - 11s - 6ms/step - ia: 0.3384 - loss: 0.9320 - mae: 0.7202 - rmse: 0.9326 - smape: 1.3840 - val_ia: 0.2500 - val_loss: 0.7817 - val_mae: 0.6512 - val_rmse: 0.7226 - val_smape: 1.2651

Epoch 40/64

1915/1915 - 10s - 5ms/step - ia: 0.3370 - loss: 0.9281 - mae: 0.7167 - rmse: 0.9290 - smape: 1.3897 - val_ia: 0.2427 - val_loss: 0.8236 - val_mae: 0.6789 - val_rmse: 0.7491 - val_smape: 1.3287

Epoch 41/64

1915/1915 - 12s - 6ms/step - ia: 0.3371 - loss: 0.9320 - mae: 0.7177 - rmse: 0.9311 - smape: 1.3888 - val_ia: 0.2259 - val_loss: 0.8604 - val_mae: 0.6956 - val_rmse: 0.7587 - val_smape: 1.4270

Epoch 42/64

1915/1915 - 22s - 11ms/step - ia: 0.3375 - loss: 0.9309 - mae: 0.7183 - rmse: 0.9305 - smape: 1.3845 - val_ia: 0.2436 - val_loss: 0.7803 - val_mae: 0.6613 - val_rmse: 0.7283 - val_smape: 1.3333

Epoch 43/64

1915/1915 - 21s - 11ms/step - ia: 0.3432 - loss: 0.9336 - mae: 0.7170 - rmse: 0.9306 - smape: 1.3769 - val_ia: 0.2457 - val_loss: 0.8033 - val_mae: 0.6660 - val_rmse: 0.7355 - val_smape: 1.3244

Epoch 43: early stopping

Restoring model weights from the end of the best epoch: 28.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:01 1s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step

 84%|████████▍ | 42/50 [3:21:14<51:04, 383.08s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

120/120 - 13s - 106ms/step - ia: 0.3594 - loss: 1.1792 - mae: 0.8237 - rmse: 1.0799 - smape: 1.3448 - val_ia: 0.3168 - val_loss: 0.7951 - val_mae: 0.6610 - val_rmse: 0.8231 - val_smape: 1.2968

Epoch 2/8

120/120 - 2s - 13ms/step - ia: 0.3661 - loss: 0.9227 - mae: 0.7147 - rmse: 0.9584 - smape: 1.3240 - val_ia: 0.3199 - val_loss: 0.7682 - val_mae: 0.6497 - val_rmse: 0.8062 - val_smape: 1.2845

Epoch 3/8

120/120 - 1s - 11ms/step - ia: 0.3677 - loss: 0.8725 - mae: 0.6908 - rmse: 0.9313 - smape: 1.3200 - val_ia: 0.3340 - val_loss: 0.7710 - val_mae: 0.6492 - val_rmse: 0.8089 - val_smape: 1.2794

Epoch 4/8

120/120 - 1s - 9ms/step - ia: 0.3700 - loss: 0.8567 - mae: 0.6828 - rmse: 0.9226 - smape: 1.3121 - val_ia: 0.3347 - val_loss: 0.7709 - val_mae: 0.6503 - val_rmse: 0.8097 - val_smape: 1.2833

Epoch 5/8

120/120 - 2s - 16ms/step - ia: 0.3680 - loss: 0.8532 - mae: 0.6802 - rmse: 0.9208 - smape: 1.3124 - val_ia: 0.3299 - val_loss: 0.7768 - val_mae: 0.6554 - val_rmse: 0.8133 - val_smape: 1.3110

Epoch 6/8

120/120 - 2s - 20ms/step - ia: 0.3667 - loss: 0.8481 - mae: 0.6783 - rmse: 0.9185 - smape: 1.3125 - val_ia: 0.3293 - val_loss: 0.7617 - val_mae: 0.6449 - val_rmse: 0.8021 - val_smape: 1.2689

Epoch 7/8

120/120 - 2s - 13ms/step - ia: 0.3704 - loss: 0.8428 - mae: 0.6758 - rmse: 0.9148 - smape: 1.3064 - val_ia: 0.3280 - val_loss: 0.7639 - val_mae: 0.6455 - val_rmse: 0.8031 - val_smape: 1.2694

Epoch 8/8

120/120 - 1s - 12ms/step - ia: 0.3690 - loss: 0.8401 - mae: 0.6739 - rmse: 0.9137 - smape: 1.3091 - val_ia: 0.3383 - val_loss: 0.7689 - val_mae: 0.6477 - val_rmse: 0.8079 - val_smape: 1.2753

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 54s 400ms/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 55/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 86%|████████▌ | 43/50 [3:21:42<32:16, 276.58s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 15s - 61ms/step - ia: 0.3125 - loss: 1.1839 - mae: 0.8301 - rmse: 1.0816 - smape: 1.4078 - val_ia: 0.2899 - val_loss: 0.8092 - val_mae: 0.6583 - val_rmse: 0.8017 - val_smape: 1.3345

Epoch 2/128

240/240 - 3s - 14ms/step - ia: 0.3350 - loss: 0.9522 - mae: 0.7283 - rmse: 0.9711 - smape: 1.3660 - val_ia: 0.2929 - val_loss: 0.7985 - val_mae: 0.6641 - val_rmse: 0.8039 - val_smape: 1.3536

Epoch 3/128

240/240 - 2s - 7ms/step - ia: 0.3383 - loss: 0.8981 - mae: 0.7042 - rmse: 0.9416 - smape: 1.3545 - val_ia: 0.2951 - val_loss: 0.7830 - val_mae: 0.6536 - val_rmse: 0.7939 - val_smape: 1.3061

Epoch 4/128

240/240 - 3s - 12ms/step - ia: 0.3463 - loss: 0.8716 - mae: 0.6917 - rmse: 0.9292 - smape: 1.3390 - val_ia: 0.3000 - val_loss: 0.7763 - val_mae: 0.6559 - val_rmse: 0.7955 - val_smape: 1.3077

Epoch 5/128

240/240 - 3s - 11ms/step - ia: 0.3535 - loss: 0.8577 - mae: 0.6855 - rmse: 0.9212 - smape: 1.3206 - val_ia: 0.3009 - val_loss: 0.7687 - val_mae: 0.6493 - val_rmse: 0.7896 - val_smape: 1.2858

Epoch 6/128

240/240 - 1s - 6ms/step - ia: 0.3582 - loss: 0.8477 - mae: 0.6816 - rmse: 0.9157 - smape: 1.3186 - val_ia: 0.3036 - val_loss: 0.7623 - val_mae: 0.6480 - val_rmse: 0.7885 - val_smape: 1.2683

Epoch 7/128

240/240 - 3s - 11ms/step - ia: 0.3643 - loss: 0.8406 - mae: 0.6781 - rmse: 0.9106 - smape: 1.3070 - val_ia: 0.3064 - val_loss: 0.7621 - val_mae: 0.6480 - val_rmse: 0.7891 - val_smape: 1.2752

Epoch 8/128

240/240 - 2s - 8ms/step - ia: 0.3685 - loss: 0.8369 - mae: 0.6760 - rmse: 0.9094 - smape: 1.3022 - val_ia: 0.3053 - val_loss: 0.7573 - val_mae: 0.6478 - val_rmse: 0.7874 - val_smape: 1.2791

Epoch 9/128

240/240 - 2s - 9ms/step - ia: 0.3695 - loss: 0.8323 - mae: 0.6738 - rmse: 0.9067 - smape: 1.3010 - val_ia: 0.3088 - val_loss: 0.7503 - val_mae: 0.6384 - val_rmse: 0.7802 - val_smape: 1.2428

Epoch 10/128

240/240 - 3s - 11ms/step - ia: 0.3728 - loss: 0.8292 - mae: 0.6715 - rmse: 0.9063 - smape: 1.2951 - val_ia: 0.3093 - val_loss: 0.7553 - val_mae: 0.6442 - val_rmse: 0.7848 - val_smape: 1.2819

Epoch 11/128

240/240 - 2s - 10ms/step - ia: 0.3717 - loss: 0.8282 - mae: 0.6722 - rmse: 0.9051 - smape: 1.3001 - val_ia: 0.3112 - val_loss: 0.7506 - val_mae: 0.6420 - val_rmse: 0.7832 - val_smape: 1.2658

Epoch 12/128

240/240 - 2s - 10ms/step - ia: 0.3789 - loss: 0.8175 - mae: 0.6673 - rmse: 0.8984 - smape: 1.2933 - val_ia: 0.3152 - val_loss: 0.7459 - val_mae: 0.6385 - val_rmse: 0.7809 - val_smape: 1.2510

Epoch 13/128

240/240 - 2s - 8ms/step - ia: 0.3793 - loss: 0.8208 - mae: 0.6676 - rmse: 0.9007 - smape: 1.2915 - val_ia: 0.3150 - val_loss: 0.7452 - val_mae: 0.6381 - val_rmse: 0.7799 - val_smape: 1.2666

Epoch 14/128

240/240 - 3s - 13ms/step - ia: 0.3788 - loss: 0.8166 - mae: 0.6675 - rmse: 0.8978 - smape: 1.2960 - val_ia: 0.3179 - val_loss: 0.7477 - val_mae: 0.6378 - val_rmse: 0.7813 - val_smape: 1.2591

Epoch 15/128

240/240 - 2s - 8ms/step - ia: 0.3802 - loss: 0.8158 - mae: 0.6660 - rmse: 0.8986 - smape: 1.2966 - val_ia: 0.3175 - val_loss: 0.7441 - val_mae: 0.6372 - val_rmse: 0.7801 - val_smape: 1.2619

Epoch 16/128

240/240 - 2s - 9ms/step - ia: 0.3812 - loss: 0.8135 - mae: 0.6648 - rmse: 0.8967 - smape: 1.2994 - val_ia: 0.3186 - val_loss: 0.7458 - val_mae: 0.6384 - val_rmse: 0.7819 - val_smape: 1.2626

Epoch 17/128

240/240 - 2s - 8ms/step - ia: 0.3820 - loss: 0.8096 - mae: 0.6632 - rmse: 0.8943 - smape: 1.2968 - val_ia: 0.3227 - val_loss: 0.7478 - val_mae: 0.6415 - val_rmse: 0.7854 - val_smape: 1.2727

Epoch 18/128

240/240 - 2s - 10ms/step - ia: 0.3847 - loss: 0.8113 - mae: 0.6635 - rmse: 0.8955 - smape: 1.2946 - val_ia: 0.3206 - val_loss: 0.7419 - val_mae: 0.6343 - val_rmse: 0.7784 - val_smape: 1.2586

Epoch 19/128

240/240 - 2s - 10ms/step - ia: 0.3839 - loss: 0.8073 - mae: 0.6631 - rmse: 0.8931 - smape: 1.3004 - val_ia: 0.3230 - val_loss: 0.7442 - val_mae: 0.6361 - val_rmse: 0.7805 - val_smape: 1.2697

Epoch 20/128

240/240 - 3s - 13ms/step - ia: 0.3905 - loss: 0.8021 - mae: 0.6597 - rmse: 0.8896 - smape: 1.2919 - val_ia: 0.3225 - val_loss: 0.7454 - val_mae: 0.6372 - val_rmse: 0.7814 - val_smape: 1.2802

Epoch 21/128

240/240 - 3s - 13ms/step - ia: 0.3889 - loss: 0.8036 - mae: 0.6601 - rmse: 0.8915 - smape: 1.2984 - val_ia: 0.3253 - val_loss: 0.7465 - val_mae: 0.6368 - val_rmse: 0.7819 - val_smape: 1.2814

Epoch 22/128

240/240 - 2s - 7ms/step - ia: 0.3879 - loss: 0.8019 - mae: 0.6602 - rmse: 0.8912 - smape: 1.3006 - val_ia: 0.3237 - val_loss: 0.7488 - val_mae: 0.6390 - val_rmse: 0.7838 - val_smape: 1.2907

Epoch 23/128

240/240 - 2s - 9ms/step - ia: 0.3872 - loss: 0.8052 - mae: 0.6601 - rmse: 0.8924 - smape: 1.2978 - val_ia: 0.3222 - val_loss: 0.7497 - val_mae: 0.6429 - val_rmse: 0.7866 - val_smape: 1.2993

Epoch 24/128

240/240 - 2s - 7ms/step - ia: 0.3911 - loss: 0.7989 - mae: 0.6580 - rmse: 0.8904 - smape: 1.2989 - val_ia: 0.3199 - val_loss: 0.7460 - val_mae: 0.6384 - val_rmse: 0.7821 - val_smape: 1.2931

Epoch 25/128

240/240 - 2s - 10ms/step - ia: 0.3914 - loss: 0.7972 - mae: 0.6575 - rmse: 0.8890 - smape: 1.2985 - val_ia: 0.3248 - val_loss: 0.7474 - val_mae: 0.6396 - val_rmse: 0.7844 - val_smape: 1.2933

Epoch 26/128

240/240 - 2s - 10ms/step - ia: 0.3911 - loss: 0.7987 - mae: 0.6581 - rmse: 0.8890 - smape: 1.2996 - val_ia: 0.3257 - val_loss: 0.7432 - val_mae: 0.6349 - val_rmse: 0.7800 - val_smape: 1.2849

Epoch 27/128

240/240 - 3s - 11ms/step - ia: 0.3907 - loss: 0.7971 - mae: 0.6565 - rmse: 0.8867 - smape: 1.3014 - val_ia: 0.3275 - val_loss: 0.7493 - val_mae: 0.6406 - val_rmse: 0.7862 - val_smape: 1.2960

Epoch 28/128

240/240 - 3s - 13ms/step - ia: 0.3949 - loss: 0.7929 - mae: 0.6555 - rmse: 0.8856 - smape: 1.2951 - val_ia: 0.3279 - val_loss: 0.7448 - val_mae: 0.6355 - val_rmse: 0.7817 - val_smape: 1.2846

Epoch 29/128

240/240 - 2s - 10ms/step - ia: 0.3920 - loss: 0.7968 - mae: 0.6561 - rmse: 0.8880 - smape: 1.3041 - val_ia: 0.3272 - val_loss: 0.7443 - val_mae: 0.6369 - val_rmse: 0.7824 - val_smape: 1.2960

Epoch 30/128

240/240 - 2s - 9ms/step - ia: 0.3940 - loss: 0.7935 - mae: 0.6562 - rmse: 0.8851 - smape: 1.3024 - val_ia: 0.3263 - val_loss: 0.7440 - val_mae: 0.6368 - val_rmse: 0.7819 - val_smape: 1.3010

Epoch 31/128

240/240 - 2s - 9ms/step - ia: 0.3933 - loss: 0.7907 - mae: 0.6546 - rmse: 0.8835 - smape: 1.3046 - val_ia: 0.3304 - val_loss: 0.7479 - val_mae: 0.6388 - val_rmse: 0.7858 - val_smape: 1.2958

Epoch 32/128

240/240 - 2s - 8ms/step - ia: 0.3931 - loss: 0.7958 - mae: 0.6562 - rmse: 0.8868 - smape: 1.3036 - val_ia: 0.3293 - val_loss: 0.7464 - val_mae: 0.6380 - val_rmse: 0.7841 - val_smape: 1.3005

Epoch 33/128

240/240 - 2s - 8ms/step - ia: 0.3918 - loss: 0.7934 - mae: 0.6554 - rmse: 0.8856 - smape: 1.3068 - val_ia: 0.3307 - val_loss: 0.7476 - val_mae: 0.6364 - val_rmse: 0.7840 - val_smape: 1.2891

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:52 836ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 17/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 67/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
103/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step

 88%|████████▊ | 44/50 [3:23:17<22:13, 222.29s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 41s - 11ms/step - ia: 0.3288 - loss: 1.4207 - mae: 0.9017 - rmse: 1.1256 - smape: 1.3783 - val_ia: 0.1947 - val_loss: 0.8105 - val_mae: 0.6676 - val_rmse: 0.7123 - val_smape: 1.3619

Epoch 2/32

3830/3830 - 23s - 6ms/step - ia: 0.3392 - loss: 1.0137 - mae: 0.7540 - rmse: 0.9490 - smape: 1.3760 - val_ia: 0.1982 - val_loss: 0.7917 - val_mae: 0.6591 - val_rmse: 0.6999 - val_smape: 1.3450

Epoch 3/32

3830/3830 - 22s - 6ms/step - ia: 0.3507 - loss: 0.9213 - mae: 0.7141 - rmse: 0.9016 - smape: 1.3579 - val_ia: 0.1993 - val_loss: 0.7859 - val_mae: 0.6566 - val_rmse: 0.6969 - val_smape: 1.3398

Epoch 4/32

3830/3830 - 23s - 6ms/step - ia: 0.3529 - loss: 0.8922 - mae: 0.7016 - rmse: 0.8879 - smape: 1.3557 - val_ia: 0.2006 - val_loss: 0.7763 - val_mae: 0.6516 - val_rmse: 0.6923 - val_smape: 1.3176

Epoch 5/32

3830/3830 - 23s - 6ms/step - ia: 0.3574 - loss: 0.8770 - mae: 0.6946 - rmse: 0.8806 - smape: 1.3480 - val_ia: 0.2012 - val_loss: 0.7712 - val_mae: 0.6476 - val_rmse: 0.6880 - val_smape: 1.3098

Epoch 6/32

3830/3830 - 20s - 5ms/step - ia: 0.3577 - loss: 0.8627 - mae: 0.6873 - rmse: 0.8717 - smape: 1.3428 - val_ia: 0.2010 - val_loss: 0.7701 - val_mae: 0.6482 - val_rmse: 0.6890 - val_smape: 1.3050

Epoch 7/32

3830/3830 - 22s - 6ms/step - ia: 0.3646 - loss: 0.8531 - mae: 0.6827 - rmse: 0.8660 - smape: 1.3324 - val_ia: 0.2003 - val_loss: 0.7707 - val_mae: 0.6501 - val_rmse: 0.6903 - val_smape: 1.3260

Epoch 8/32

3830/3830 - 22s - 6ms/step - ia: 0.3631 - loss: 0.8487 - mae: 0.6815 - rmse: 0.8639 - smape: 1.3393 - val_ia: 0.2027 - val_loss: 0.7603 - val_mae: 0.6441 - val_rmse: 0.6849 - val_smape: 1.2876

Epoch 9/32

3830/3830 - 21s - 6ms/step - ia: 0.3604 - loss: 0.8507 - mae: 0.6826 - rmse: 0.8655 - smape: 1.3418 - val_ia: 0.2017 - val_loss: 0.7640 - val_mae: 0.6453 - val_rmse: 0.6863 - val_smape: 1.2899

Epoch 10/32

3830/3830 - 20s - 5ms/step - ia: 0.3669 - loss: 0.8426 - mae: 0.6785 - rmse: 0.8608 - smape: 1.3325 - val_ia: 0.2011 - val_loss: 0.7632 - val_mae: 0.6461 - val_rmse: 0.6863 - val_smape: 1.3076

Epoch 11/32

3830/3830 - 22s - 6ms/step - ia: 0.3641 - loss: 0.8421 - mae: 0.6786 - rmse: 0.8613 - smape: 1.3341 - val_ia: 0.2034 - val_loss: 0.7563 - val_mae: 0.6415 - val_rmse: 0.6823 - val_smape: 1.2766

Epoch 12/32

3830/3830 - 37s - 10ms/step - ia: 0.3660 - loss: 0.8385 - mae: 0.6769 - rmse: 0.8583 - smape: 1.3296 - val_ia: 0.2018 - val_loss: 0.7601 - val_mae: 0.6441 - val_rmse: 0.6850 - val_smape: 1.2877

Epoch 13/32

3830/3830 - 24s - 6ms/step - ia: 0.3682 - loss: 0.8336 - mae: 0.6748 - rmse: 0.8568 - smape: 1.3237 - val_ia: 0.2021 - val_loss: 0.7587 - val_mae: 0.6431 - val_rmse: 0.6842 - val_smape: 1.2815

Epoch 14/32

3830/3830 - 21s - 5ms/step - ia: 0.3662 - loss: 0.8380 - mae: 0.6758 - rmse: 0.8576 - smape: 1.3310 - val_ia: 0.2014 - val_loss: 0.7621 - val_mae: 0.6451 - val_rmse: 0.6860 - val_smape: 1.2972

Epoch 15/32

3830/3830 - 18s - 5ms/step - ia: 0.3686 - loss: 0.8348 - mae: 0.6749 - rmse: 0.8555 - smape: 1.3280 - val_ia: 0.2012 - val_loss: 0.7635 - val_mae: 0.6457 - val_rmse: 0.6866 - val_smape: 1.2982

Epoch 16/32

3830/3830 - 20s - 5ms/step - ia: 0.3698 - loss: 0.8342 - mae: 0.6739 - rmse: 0.8558 - smape: 1.3253 - val_ia: 0.2013 - val_loss: 0.7614 - val_mae: 0.6443 - val_rmse: 0.6851 - val_smape: 1.2899

Epoch 17/32

3830/3830 - 21s - 6ms/step - ia: 0.3685 - loss: 0.8338 - mae: 0.6745 - rmse: 0.8552 - smape: 1.3289 - val_ia: 0.2016 - val_loss: 0.7627 - val_mae: 0.6446 - val_rmse: 0.6858 - val_smape: 1.2866

Epoch 18/32

3830/3830 - 21s - 5ms/step - ia: 0.3672 - loss: 0.8322 - mae: 0.6740 - rmse: 0.8543 - smape: 1.3270 - val_ia: 0.2018 - val_loss: 0.7603 - val_mae: 0.6438 - val_rmse: 0.6848 - val_smape: 1.2858

Epoch 19/32

3830/3830 - 28s - 7ms/step - ia: 0.3678 - loss: 0.8337 - mae: 0.6734 - rmse: 0.8550 - smape: 1.3288 - val_ia: 0.2019 - val_loss: 0.7582 - val_mae: 0.6422 - val_rmse: 0.6832 - val_smape: 1.2803

Epoch 20/32

3830/3830 - 29s - 8ms/step - ia: 0.3692 - loss: 0.8311 - mae: 0.6725 - rmse: 0.8542 - smape: 1.3208 - val_ia: 0.2018 - val_loss: 0.7662 - val_mae: 0.6462 - val_rmse: 0.6873 - val_smape: 1.2924

Epoch 21/32

3830/3830 - 34s - 9ms/step - ia: 0.3703 - loss: 0.8317 - mae: 0.6717 - rmse: 0.8526 - smape: 1.3203 - val_ia: 0.2024 - val_loss: 0.7556 - val_mae: 0.6427 - val_rmse: 0.6834 - val_smape: 1.2854

Epoch 22/32

3830/3830 - 42s - 11ms/step - ia: 0.3695 - loss: 0.8300 - mae: 0.6726 - rmse: 0.8551 - smape: 1.3229 - val_ia: 0.2014 - val_loss: 0.7637 - val_mae: 0.6452 - val_rmse: 0.6860 - val_smape: 1.2955

Epoch 23/32

3830/3830 - 25s - 7ms/step - ia: 0.3714 - loss: 0.8268 - mae: 0.6704 - rmse: 0.8517 - smape: 1.3167 - val_ia: 0.2020 - val_loss: 0.7578 - val_mae: 0.6428 - val_rmse: 0.6837 - val_smape: 1.2810

Epoch 24/32

3830/3830 - 12s - 3ms/step - ia: 0.3730 - loss: 0.8274 - mae: 0.6699 - rmse: 0.8522 - smape: 1.3158 - val_ia: 0.2013 - val_loss: 0.7621 - val_mae: 0.6455 - val_rmse: 0.6863 - val_smape: 1.2997

Epoch 25/32

3830/3830 - 19s - 5ms/step - ia: 0.3720 - loss: 0.8274 - mae: 0.6703 - rmse: 0.8517 - smape: 1.3171 - val_ia: 0.2025 - val_loss: 0.7561 - val_mae: 0.6420 - val_rmse: 0.6834 - val_smape: 1.2743

Epoch 26/32

3830/3830 - 21s - 5ms/step - ia: 0.3715 - loss: 0.8274 - mae: 0.6710 - rmse: 0.8519 - smape: 1.3212 - val_ia: 0.2018 - val_loss: 0.7651 - val_mae: 0.6455 - val_rmse: 0.6869 - val_smape: 1.2888

Epoch 27/32

3830/3830 - 17s - 5ms/step - ia: 0.3715 - loss: 0.8253 - mae: 0.6691 - rmse: 0.8514 - smape: 1.3166 - val_ia: 0.2050 - val_loss: 0.7543 - val_mae: 0.6385 - val_rmse: 0.6808 - val_smape: 1.2488

Epoch 28/32

3830/3830 - 19s - 5ms/step - ia: 0.3734 - loss: 0.8286 - mae: 0.6704 - rmse: 0.8538 - smape: 1.3144 - val_ia: 0.2022 - val_loss: 0.7582 - val_mae: 0.6416 - val_rmse: 0.6831 - val_smape: 1.2736

Epoch 29/32

3830/3830 - 20s - 5ms/step - ia: 0.3709 - loss: 0.8273 - mae: 0.6701 - rmse: 0.8528 - smape: 1.3167 - val_ia: 0.2025 - val_loss: 0.7563 - val_mae: 0.6408 - val_rmse: 0.6824 - val_smape: 1.2703

Epoch 30/32

3830/3830 - 23s - 6ms/step - ia: 0.3735 - loss: 0.8235 - mae: 0.6689 - rmse: 0.8498 - smape: 1.3138 - val_ia: 0.2017 - val_loss: 0.7593 - val_mae: 0.6433 - val_rmse: 0.6848 - val_smape: 1.2807

Epoch 31/32

3830/3830 - 17s - 5ms/step - ia: 0.3716 - loss: 0.8280 - mae: 0.6706 - rmse: 0.8520 - smape: 1.3152 - val_ia: 0.2020 - val_loss: 0.7563 - val_mae: 0.6425 - val_rmse: 0.6832 - val_smape: 1.2890

Epoch 32/32

3830/3830 - 18s - 5ms/step - ia: 0.3737 - loss: 0.8243 - mae: 0.6688 - rmse: 0.8493 - smape: 1.3160 - val_ia: 0.2023 - val_loss: 0.7569 - val_mae: 0.6416 - val_rmse: 0.6828 - val_smape: 1.2778

Restoring model weights from the end of the best epoch: 27.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 95/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
105/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 90%|█████████ | 45/50 [3:35:53<31:51, 382.38s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/256

958/958 - 14s - 15ms/step - ia: 0.2906 - loss: 2.1022 - mae: 1.0684 - rmse: 1.4028 - smape: 1.4430 - val_ia: 0.2446 - val_loss: 1.0795 - val_mae: 0.7840 - val_rmse: 0.9106 - val_smape: 1.4208

Epoch 2/256

958/958 - 6s - 6ms/step - ia: 0.3262 - loss: 1.1757 - mae: 0.8175 - rmse: 1.0667 - smape: 1.4156 - val_ia: 0.2546 - val_loss: 0.8962 - val_mae: 0.7156 - val_rmse: 0.8282 - val_smape: 1.3850

Epoch 3/256

958/958 - 5s - 6ms/step - ia: 0.3429 - loss: 1.0204 - mae: 0.7590 - rmse: 0.9929 - smape: 1.4008 - val_ia: 0.2570 - val_loss: 0.8414 - val_mae: 0.6932 - val_rmse: 0.7995 - val_smape: 1.3826

Epoch 4/256

958/958 - 9s - 10ms/step - ia: 0.3461 - loss: 0.9553 - mae: 0.7314 - rmse: 0.9601 - smape: 1.3962 - val_ia: 0.2591 - val_loss: 0.8148 - val_mae: 0.6784 - val_rmse: 0.7820 - val_smape: 1.3614

Epoch 5/256

958/958 - 5s - 5ms/step - ia: 0.3549 - loss: 0.9141 - mae: 0.7145 - rmse: 0.9381 - smape: 1.3843 - val_ia: 0.2601 - val_loss: 0.7965 - val_mae: 0.6702 - val_rmse: 0.7698 - val_smape: 1.3700

Epoch 6/256

958/958 - 7s - 7ms/step - ia: 0.3551 - loss: 0.8885 - mae: 0.7011 - rmse: 0.9245 - smape: 1.3787 - val_ia: 0.2608 - val_loss: 0.7855 - val_mae: 0.6646 - val_rmse: 0.7632 - val_smape: 1.3588

Epoch 7/256

958/958 - 8s - 9ms/step - ia: 0.3567 - loss: 0.8702 - mae: 0.6947 - rmse: 0.9163 - smape: 1.3729 - val_ia: 0.2618 - val_loss: 0.7744 - val_mae: 0.6574 - val_rmse: 0.7553 - val_smape: 1.3388

Epoch 8/256

958/958 - 7s - 7ms/step - ia: 0.3606 - loss: 0.8647 - mae: 0.6884 - rmse: 0.9110 - smape: 1.3611 - val_ia: 0.2619 - val_loss: 0.7723 - val_mae: 0.6554 - val_rmse: 0.7525 - val_smape: 1.3287

Epoch 9/256

958/958 - 5s - 5ms/step - ia: 0.3609 - loss: 0.8545 - mae: 0.6833 - rmse: 0.9074 - smape: 1.3572 - val_ia: 0.2614 - val_loss: 0.7670 - val_mae: 0.6522 - val_rmse: 0.7480 - val_smape: 1.3300

Epoch 10/256

958/958 - 6s - 7ms/step - ia: 0.3671 - loss: 0.8446 - mae: 0.6777 - rmse: 0.9003 - smape: 1.3416 - val_ia: 0.2620 - val_loss: 0.7621 - val_mae: 0.6497 - val_rmse: 0.7454 - val_smape: 1.3148

Epoch 11/256

958/958 - 10s - 10ms/step - ia: 0.3681 - loss: 0.8401 - mae: 0.6754 - rmse: 0.8976 - smape: 1.3382 - val_ia: 0.2622 - val_loss: 0.7572 - val_mae: 0.6469 - val_rmse: 0.7420 - val_smape: 1.3064

Epoch 12/256

958/958 - 5s - 6ms/step - ia: 0.3739 - loss: 0.8332 - mae: 0.6710 - rmse: 0.8952 - smape: 1.3302 - val_ia: 0.2608 - val_loss: 0.7598 - val_mae: 0.6468 - val_rmse: 0.7413 - val_smape: 1.3011

Epoch 13/256

958/958 - 5s - 6ms/step - ia: 0.3766 - loss: 0.8289 - mae: 0.6687 - rmse: 0.8922 - smape: 1.3217 - val_ia: 0.2607 - val_loss: 0.7596 - val_mae: 0.6479 - val_rmse: 0.7426 - val_smape: 1.3075

Epoch 14/256

958/958 - 10s - 10ms/step - ia: 0.3792 - loss: 0.8233 - mae: 0.6673 - rmse: 0.8896 - smape: 1.3172 - val_ia: 0.2608 - val_loss: 0.7530 - val_mae: 0.6444 - val_rmse: 0.7382 - val_smape: 1.2963

Epoch 15/256

958/958 - 6s - 6ms/step - ia: 0.3800 - loss: 0.8218 - mae: 0.6654 - rmse: 0.8898 - smape: 1.3148 - val_ia: 0.2602 - val_loss: 0.7536 - val_mae: 0.6444 - val_rmse: 0.7382 - val_smape: 1.2962

Epoch 16/256

958/958 - 11s - 12ms/step - ia: 0.3822 - loss: 0.8239 - mae: 0.6648 - rmse: 0.8890 - smape: 1.3090 - val_ia: 0.2603 - val_loss: 0.7518 - val_mae: 0.6434 - val_rmse: 0.7371 - val_smape: 1.2946

Epoch 17/256

958/958 - 10s - 10ms/step - ia: 0.3847 - loss: 0.8162 - mae: 0.6622 - rmse: 0.8854 - smape: 1.3076 - val_ia: 0.2602 - val_loss: 0.7529 - val_mae: 0.6433 - val_rmse: 0.7367 - val_smape: 1.2910

Epoch 18/256

958/958 - 7s - 7ms/step - ia: 0.3829 - loss: 0.8173 - mae: 0.6627 - rmse: 0.8865 - smape: 1.3079 - val_ia: 0.2614 - val_loss: 0.7488 - val_mae: 0.6418 - val_rmse: 0.7363 - val_smape: 1.2801

Epoch 19/256

958/958 - 6s - 6ms/step - ia: 0.3888 - loss: 0.8096 - mae: 0.6598 - rmse: 0.8818 - smape: 1.3052 - val_ia: 0.2613 - val_loss: 0.7467 - val_mae: 0.6385 - val_rmse: 0.7326 - val_smape: 1.2721

Epoch 20/256

958/958 - 6s - 6ms/step - ia: 0.3905 - loss: 0.8097 - mae: 0.6586 - rmse: 0.8816 - smape: 1.3002 - val_ia: 0.2606 - val_loss: 0.7482 - val_mae: 0.6406 - val_rmse: 0.7345 - val_smape: 1.2812

Epoch 21/256

958/958 - 5s - 5ms/step - ia: 0.3867 - loss: 0.8098 - mae: 0.6598 - rmse: 0.8822 - smape: 1.3079 - val_ia: 0.2611 - val_loss: 0.7486 - val_mae: 0.6406 - val_rmse: 0.7354 - val_smape: 1.2744

Epoch 22/256

958/958 - 5s - 5ms/step - ia: 0.3905 - loss: 0.8101 - mae: 0.6591 - rmse: 0.8823 - smape: 1.3061 - val_ia: 0.2598 - val_loss: 0.7520 - val_mae: 0.6425 - val_rmse: 0.7359 - val_smape: 1.2868

Epoch 23/256

958/958 - 6s - 7ms/step - ia: 0.3904 - loss: 0.8073 - mae: 0.6586 - rmse: 0.8810 - smape: 1.3021 - val_ia: 0.2611 - val_loss: 0.7467 - val_mae: 0.6413 - val_rmse: 0.7351 - val_smape: 1.2789

Epoch 24/256

958/958 - 6s - 7ms/step - ia: 0.3886 - loss: 0.8098 - mae: 0.6597 - rmse: 0.8812 - smape: 1.3043 - val_ia: 0.2613 - val_loss: 0.7497 - val_mae: 0.6414 - val_rmse: 0.7366 - val_smape: 1.2736

Epoch 25/256

958/958 - 9s - 9ms/step - ia: 0.3919 - loss: 0.8076 - mae: 0.6586 - rmse: 0.8807 - smape: 1.3028 - val_ia: 0.2616 - val_loss: 0.7459 - val_mae: 0.6384 - val_rmse: 0.7327 - val_smape: 1.2626

Epoch 26/256

958/958 - 8s - 8ms/step - ia: 0.3909 - loss: 0.8077 - mae: 0.6583 - rmse: 0.8793 - smape: 1.2992 - val_ia: 0.2602 - val_loss: 0.7497 - val_mae: 0.6419 - val_rmse: 0.7369 - val_smape: 1.2806

Epoch 27/256

958/958 - 6s - 6ms/step - ia: 0.3956 - loss: 0.8034 - mae: 0.6573 - rmse: 0.8786 - smape: 1.2932 - val_ia: 0.2610 - val_loss: 0.7458 - val_mae: 0.6399 - val_rmse: 0.7342 - val_smape: 1.2772

Epoch 28/256

958/958 - 5s - 5ms/step - ia: 0.3928 - loss: 0.8048 - mae: 0.6574 - rmse: 0.8799 - smape: 1.2953 - val_ia: 0.2608 - val_loss: 0.7453 - val_mae: 0.6397 - val_rmse: 0.7338 - val_smape: 1.2780

Epoch 29/256

958/958 - 6s - 6ms/step - ia: 0.3939 - loss: 0.8028 - mae: 0.6568 - rmse: 0.8784 - smape: 1.2945 - val_ia: 0.2603 - val_loss: 0.7468 - val_mae: 0.6400 - val_rmse: 0.7341 - val_smape: 1.2774

Epoch 30/256

958/958 - 10s - 11ms/step - ia: 0.3935 - loss: 0.8037 - mae: 0.6563 - rmse: 0.8788 - smape: 1.2958 - val_ia: 0.2604 - val_loss: 0.7468 - val_mae: 0.6385 - val_rmse: 0.7330 - val_smape: 1.2676

Epoch 31/256

958/958 - 11s - 11ms/step - ia: 0.3962 - loss: 0.8022 - mae: 0.6561 - rmse: 0.8773 - smape: 1.2901 - val_ia: 0.2613 - val_loss: 0.7458 - val_mae: 0.6398 - val_rmse: 0.7340 - val_smape: 1.2739

Epoch 32/256

958/958 - 5s - 6ms/step - ia: 0.3938 - loss: 0.8032 - mae: 0.6560 - rmse: 0.8776 - smape: 1.2935 - val_ia: 0.2618 - val_loss: 0.7457 - val_mae: 0.6400 - val_rmse: 0.7347 - val_smape: 1.2689

Epoch 33/256

958/958 - 11s - 11ms/step - ia: 0.3955 - loss: 0.8022 - mae: 0.6563 - rmse: 0.8768 - smape: 1.2896 - val_ia: 0.2609 - val_loss: 0.7467 - val_mae: 0.6395 - val_rmse: 0.7336 - val_smape: 1.2675

Epoch 34/256

958/958 - 6s - 6ms/step - ia: 0.3942 - loss: 0.8014 - mae: 0.6561 - rmse: 0.8781 - smape: 1.2906 - val_ia: 0.2626 - val_loss: 0.7432 - val_mae: 0.6360 - val_rmse: 0.7313 - val_smape: 1.2531

Epoch 35/256

958/958 - 4s - 4ms/step - ia: 0.3977 - loss: 0.8006 - mae: 0.6551 - rmse: 0.8772 - smape: 1.2868 - val_ia: 0.2615 - val_loss: 0.7469 - val_mae: 0.6409 - val_rmse: 0.7356 - val_smape: 1.2716

Epoch 36/256

958/958 - 6s - 6ms/step - ia: 0.3954 - loss: 0.8003 - mae: 0.6566 - rmse: 0.8767 - smape: 1.2891 - val_ia: 0.2618 - val_loss: 0.7421 - val_mae: 0.6370 - val_rmse: 0.7314 - val_smape: 1.2679

Epoch 37/256

958/958 - 6s - 7ms/step - ia: 0.3950 - loss: 0.7986 - mae: 0.6561 - rmse: 0.8759 - smape: 1.2926 - val_ia: 0.2618 - val_loss: 0.7446 - val_mae: 0.6384 - val_rmse: 0.7330 - val_smape: 1.2640

Epoch 38/256

958/958 - 9s - 9ms/step - ia: 0.3964 - loss: 0.7996 - mae: 0.6563 - rmse: 0.8765 - smape: 1.2901 - val_ia: 0.2615 - val_loss: 0.7455 - val_mae: 0.6383 - val_rmse: 0.7328 - val_smape: 1.2621

Epoch 39/256

958/958 - 4s - 4ms/step - ia: 0.4006 - loss: 0.7956 - mae: 0.6539 - rmse: 0.8747 - smape: 1.2827 - val_ia: 0.2617 - val_loss: 0.7436 - val_mae: 0.6384 - val_rmse: 0.7333 - val_smape: 1.2695

Epoch 40/256

958/958 - 7s - 7ms/step - ia: 0.3965 - loss: 0.8004 - mae: 0.6556 - rmse: 0.8756 - smape: 1.2878 - val_ia: 0.2627 - val_loss: 0.7428 - val_mae: 0.6378 - val_rmse: 0.7325 - val_smape: 1.2645

Epoch 41/256

958/958 - 5s - 5ms/step - ia: 0.3966 - loss: 0.7978 - mae: 0.6545 - rmse: 0.8757 - smape: 1.2877 - val_ia: 0.2622 - val_loss: 0.7441 - val_mae: 0.6382 - val_rmse: 0.7330 - val_smape: 1.2635

Epoch 42/256

958/958 - 4s - 4ms/step - ia: 0.3971 - loss: 0.7992 - mae: 0.6551 - rmse: 0.8762 - smape: 1.2873 - val_ia: 0.2621 - val_loss: 0.7439 - val_mae: 0.6372 - val_rmse: 0.7323 - val_smape: 1.2586

Epoch 43/256

958/958 - 4s - 5ms/step - ia: 0.3959 - loss: 0.7997 - mae: 0.6558 - rmse: 0.8772 - smape: 1.2873 - val_ia: 0.2611 - val_loss: 0.7448 - val_mae: 0.6380 - val_rmse: 0.7325 - val_smape: 1.2667

Epoch 44/256

958/958 - 5s - 6ms/step - ia: 0.3954 - loss: 0.7979 - mae: 0.6556 - rmse: 0.8755 - smape: 1.2889 - val_ia: 0.2623 - val_loss: 0.7446 - val_mae: 0.6391 - val_rmse: 0.7342 - val_smape: 1.2669

Epoch 45/256

958/958 - 4s - 4ms/step - ia: 0.3992 - loss: 0.7977 - mae: 0.6547 - rmse: 0.8751 - smape: 1.2849 - val_ia: 0.2632 - val_loss: 0.7404 - val_mae: 0.6362 - val_rmse: 0.7315 - val_smape: 1.2599

Epoch 46/256

958/958 - 3s - 3ms/step - ia: 0.4003 - loss: 0.7959 - mae: 0.6540 - rmse: 0.8738 - smape: 1.2838 - val_ia: 0.2609 - val_loss: 0.7466 - val_mae: 0.6405 - val_rmse: 0.7348 - val_smape: 1.2700

Epoch 47/256

958/958 - 6s - 6ms/step - ia: 0.3981 - loss: 0.7962 - mae: 0.6556 - rmse: 0.8745 - smape: 1.2858 - val_ia: 0.2619 - val_loss: 0.7435 - val_mae: 0.6379 - val_rmse: 0.7324 - val_smape: 1.2663

Epoch 48/256

958/958 - 3s - 3ms/step - ia: 0.3962 - loss: 0.7994 - mae: 0.6545 - rmse: 0.8761 - smape: 1.2879 - val_ia: 0.2623 - val_loss: 0.7425 - val_mae: 0.6379 - val_rmse: 0.7335 - val_smape: 1.2676

Epoch 49/256

958/958 - 3s - 3ms/step - ia: 0.3990 - loss: 0.7976 - mae: 0.6550 - rmse: 0.8747 - smape: 1.2835 - val_ia: 0.2624 - val_loss: 0.7410 - val_mae: 0.6363 - val_rmse: 0.7312 - val_smape: 1.2615

Epoch 50/256

958/958 - 3s - 3ms/step - ia: 0.3981 - loss: 0.7973 - mae: 0.6543 - rmse: 0.8751 - smape: 1.2869 - val_ia: 0.2622 - val_loss: 0.7411 - val_mae: 0.6358 - val_rmse: 0.7306 - val_smape: 1.2616

Epoch 51/256

958/958 - 6s - 7ms/step - ia: 0.3980 - loss: 0.7954 - mae: 0.6537 - rmse: 0.8749 - smape: 1.2862 - val_ia: 0.2608 - val_loss: 0.7452 - val_mae: 0.6398 - val_rmse: 0.7342 - val_smape: 1.2728

Epoch 52/256

958/958 - 6s - 6ms/step - ia: 0.3975 - loss: 0.7973 - mae: 0.6539 - rmse: 0.8767 - smape: 1.2853 - val_ia: 0.2630 - val_loss: 0.7422 - val_mae: 0.6373 - val_rmse: 0.7330 - val_smape: 1.2642

Epoch 53/256

958/958 - 12s - 12ms/step - ia: 0.4011 - loss: 0.7952 - mae: 0.6531 - rmse: 0.8737 - smape: 1.2828 - val_ia: 0.2611 - val_loss: 0.7449 - val_mae: 0.6393 - val_rmse: 0.7341 - val_smape: 1.2704

Epoch 54/256

958/958 - 9s - 9ms/step - ia: 0.3975 - loss: 0.7971 - mae: 0.6546 - rmse: 0.8747 - smape: 1.2864 - val_ia: 0.2610 - val_loss: 0.7446 - val_mae: 0.6391 - val_rmse: 0.7341 - val_smape: 1.2704

Epoch 55/256

958/958 - 4s - 5ms/step - ia: 0.3998 - loss: 0.7955 - mae: 0.6533 - rmse: 0.8740 - smape: 1.2818 - val_ia: 0.2637 - val_loss: 0.7395 - val_mae: 0.6373 - val_rmse: 0.7320 - val_smape: 1.2634

Epoch 56/256

958/958 - 7s - 7ms/step - ia: 0.3998 - loss: 0.7947 - mae: 0.6532 - rmse: 0.8739 - smape: 1.2819 - val_ia: 0.2636 - val_loss: 0.7405 - val_mae: 0.6380 - val_rmse: 0.7331 - val_smape: 1.2654

Epoch 57/256

958/958 - 6s - 6ms/step - ia: 0.3983 - loss: 0.7955 - mae: 0.6533 - rmse: 0.8744 - smape: 1.2814 - val_ia: 0.2610 - val_loss: 0.7446 - val_mae: 0.6387 - val_rmse: 0.7342 - val_smape: 1.2689

Epoch 58/256

958/958 - 9s - 9ms/step - ia: 0.4013 - loss: 0.7925 - mae: 0.6516 - rmse: 0.8735 - smape: 1.2809 - val_ia: 0.2626 - val_loss: 0.7437 - val_mae: 0.6395 - val_rmse: 0.7350 - val_smape: 1.2641

Epoch 59/256

958/958 - 8s - 8ms/step - ia: 0.4012 - loss: 0.7944 - mae: 0.6530 - rmse: 0.8746 - smape: 1.2746 - val_ia: 0.2616 - val_loss: 0.7415 - val_mae: 0.6364 - val_rmse: 0.7305 - val_smape: 1.2642

Epoch 60/256

958/958 - 10s - 10ms/step - ia: 0.4012 - loss: 0.7915 - mae: 0.6514 - rmse: 0.8715 - smape: 1.2788 - val_ia: 0.2616 - val_loss: 0.7459 - val_mae: 0.6402 - val_rmse: 0.7353 - val_smape: 1.2649

Epoch 61/256

958/958 - 10s - 11ms/step - ia: 0.4013 - loss: 0.7940 - mae: 0.6534 - rmse: 0.8742 - smape: 1.2769 - val_ia: 0.2622 - val_loss: 0.7428 - val_mae: 0.6373 - val_rmse: 0.7321 - val_smape: 1.2608

Epoch 62/256

958/958 - 3s - 3ms/step - ia: 0.4003 - loss: 0.7939 - mae: 0.6535 - rmse: 0.8735 - smape: 1.2797 - val_ia: 0.2626 - val_loss: 0.7414 - val_mae: 0.6381 - val_rmse: 0.7330 - val_smape: 1.2667

Epoch 63/256

958/958 - 2s - 2ms/step - ia: 0.3972 - loss: 0.7940 - mae: 0.6540 - rmse: 0.8741 - smape: 1.2857 - val_ia: 0.2645 - val_loss: 0.7396 - val_mae: 0.6355 - val_rmse: 0.7312 - val_smape: 1.2520

Epoch 64/256

958/958 - 2s - 2ms/step - ia: 0.4000 - loss: 0.7931 - mae: 0.6531 - rmse: 0.8735 - smape: 1.2811 - val_ia: 0.2620 - val_loss: 0.7436 - val_mae: 0.6381 - val_rmse: 0.7333 - val_smape: 1.2642

Epoch 65/256

958/958 - 3s - 3ms/step - ia: 0.4010 - loss: 0.7929 - mae: 0.6532 - rmse: 0.8726 - smape: 1.2824 - val_ia: 0.2618 - val_loss: 0.7437 - val_mae: 0.6376 - val_rmse: 0.7327 - val_smape: 1.2617

Epoch 66/256

958/958 - 6s - 6ms/step - ia: 0.4007 - loss: 0.7954 - mae: 0.6527 - rmse: 0.8742 - smape: 1.2808 - val_ia: 0.2633 - val_loss: 0.7413 - val_mae: 0.6357 - val_rmse: 0.7309 - val_smape: 1.2559

Epoch 67/256

958/958 - 11s - 11ms/step - ia: 0.3985 - loss: 0.7946 - mae: 0.6548 - rmse: 0.8733 - smape: 1.2844 - val_ia: 0.2620 - val_loss: 0.7426 - val_mae: 0.6375 - val_rmse: 0.7327 - val_smape: 1.2654

Epoch 68/256

958/958 - 5s - 5ms/step - ia: 0.3981 - loss: 0.7941 - mae: 0.6531 - rmse: 0.8743 - smape: 1.2810 - val_ia: 0.2632 - val_loss: 0.7410 - val_mae: 0.6343 - val_rmse: 0.7301 - val_smape: 1.2490

Epoch 69/256

958/958 - 5s - 5ms/step - ia: 0.4018 - loss: 0.7920 - mae: 0.6529 - rmse: 0.8720 - smape: 1.2818 - val_ia: 0.2625 - val_loss: 0.7410 - val_mae: 0.6361 - val_rmse: 0.7310 - val_smape: 1.2583

Epoch 70/256

958/958 - 5s - 6ms/step - ia: 0.3998 - loss: 0.7955 - mae: 0.6533 - rmse: 0.8740 - smape: 1.2792 - val_ia: 0.2612 - val_loss: 0.7442 - val_mae: 0.6376 - val_rmse: 0.7323 - val_smape: 1.2663

Epoch 70: early stopping

Restoring model weights from the end of the best epoch: 55.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 3:26 2s/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step

 92%|█████████▏| 46/50 [3:43:34<27:03, 405.93s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/8

479/479 - 16s - 33ms/step - ia: 0.3911 - loss: 0.8644 - mae: 0.6855 - rmse: 0.9196 - smape: 1.2745 - val_ia: 0.2923 - val_loss: 0.7859 - val_mae: 0.6561 - val_rmse: 0.7870 - val_smape: 1.2530

Epoch 2/8

479/479 - 3s - 6ms/step - ia: 0.4056 - loss: 0.8041 - mae: 0.6589 - rmse: 0.8869 - smape: 1.2540 - val_ia: 0.2920 - val_loss: 0.7830 - val_mae: 0.6582 - val_rmse: 0.7875 - val_smape: 1.2758

Epoch 3/8

479/479 - 6s - 13ms/step - ia: 0.4108 - loss: 0.7933 - mae: 0.6536 - rmse: 0.8815 - smape: 1.2483 - val_ia: 0.2898 - val_loss: 0.7860 - val_mae: 0.6533 - val_rmse: 0.7853 - val_smape: 1.2416

Epoch 4/8

479/479 - 5s - 11ms/step - ia: 0.4165 - loss: 0.7850 - mae: 0.6495 - rmse: 0.8765 - smape: 1.2417 - val_ia: 0.2953 - val_loss: 0.7931 - val_mae: 0.6616 - val_rmse: 0.7948 - val_smape: 1.2730

Epoch 5/8

479/479 - 4s - 8ms/step - ia: 0.4208 - loss: 0.7769 - mae: 0.6448 - rmse: 0.8722 - smape: 1.2368 - val_ia: 0.2911 - val_loss: 0.7852 - val_mae: 0.6524 - val_rmse: 0.7851 - val_smape: 1.2455

Epoch 6/8

479/479 - 5s - 10ms/step - ia: 0.4255 - loss: 0.7706 - mae: 0.6415 - rmse: 0.8685 - smape: 1.2297 - val_ia: 0.2939 - val_loss: 0.7849 - val_mae: 0.6590 - val_rmse: 0.7904 - val_smape: 1.2767

Epoch 7/8

479/479 - 4s - 9ms/step - ia: 0.4283 - loss: 0.7639 - mae: 0.6381 - rmse: 0.8644 - smape: 1.2245 - val_ia: 0.2935 - val_loss: 0.7897 - val_mae: 0.6529 - val_rmse: 0.7871 - val_smape: 1.2418

Epoch 8/8

479/479 - 5s - 9ms/step - ia: 0.4325 - loss: 0.7574 - mae: 0.6352 - rmse: 0.8614 - smape: 1.2179 - val_ia: 0.2975 - val_loss: 0.7789 - val_mae: 0.6509 - val_rmse: 0.7846 - val_smape: 1.2436

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:03 470ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
134/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 94%|█████████▍| 47/50 [3:44:26<14:59, 299.68s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/16

120/120 - 22s - 183ms/step - ia: 0.1888 - loss: 1.0335 - mae: 0.7627 - rmse: 1.0130 - smape: 1.5795 - val_ia: 0.2582 - val_loss: 0.9137 - val_mae: 0.7121 - val_rmse: 0.8711 - val_smape: 1.7054

Epoch 2/16

120/120 - 3s - 23ms/step - ia: 0.2857 - loss: 0.9336 - mae: 0.7195 - rmse: 0.9629 - smape: 1.4264 - val_ia: 0.3261 - val_loss: 0.8051 - val_mae: 0.6492 - val_rmse: 0.8179 - val_smape: 1.2577

Epoch 3/16

120/120 - 3s - 29ms/step - ia: 0.3613 - loss: 0.8880 - mae: 0.6985 - rmse: 0.9407 - smape: 1.3159 - val_ia: 0.3254 - val_loss: 0.7887 - val_mae: 0.6567 - val_rmse: 0.8176 - val_smape: 1.2850

Epoch 4/16

120/120 - 3s - 25ms/step - ia: 0.3739 - loss: 0.8664 - mae: 0.6874 - rmse: 0.9280 - smape: 1.2961 - val_ia: 0.3257 - val_loss: 0.7804 - val_mae: 0.6616 - val_rmse: 0.8182 - val_smape: 1.2878

Epoch 5/16

120/120 - 2s - 18ms/step - ia: 0.3816 - loss: 0.8535 - mae: 0.6828 - rmse: 0.9212 - smape: 1.2856 - val_ia: 0.3294 - val_loss: 0.7763 - val_mae: 0.6586 - val_rmse: 0.8161 - val_smape: 1.2933

Epoch 6/16

120/120 - 2s - 16ms/step - ia: 0.3821 - loss: 0.8472 - mae: 0.6794 - rmse: 0.9183 - smape: 1.2839 - val_ia: 0.3415 - val_loss: 0.7675 - val_mae: 0.6480 - val_rmse: 0.8096 - val_smape: 1.2567

Epoch 7/16

120/120 - 3s - 22ms/step - ia: 0.3875 - loss: 0.8395 - mae: 0.6754 - rmse: 0.9131 - smape: 1.2736 - val_ia: 0.3337 - val_loss: 0.7646 - val_mae: 0.6520 - val_rmse: 0.8099 - val_smape: 1.2717

Epoch 8/16

120/120 - 3s - 25ms/step - ia: 0.3873 - loss: 0.8355 - mae: 0.6748 - rmse: 0.9113 - smape: 1.2745 - val_ia: 0.3445 - val_loss: 0.7514 - val_mae: 0.6249 - val_rmse: 0.7922 - val_smape: 1.1826

Epoch 9/16

120/120 - 3s - 22ms/step - ia: 0.3886 - loss: 0.8315 - mae: 0.6724 - rmse: 0.9097 - smape: 1.2725 - val_ia: 0.3395 - val_loss: 0.7509 - val_mae: 0.6349 - val_rmse: 0.7968 - val_smape: 1.2290

Epoch 10/16

120/120 - 3s - 21ms/step - ia: 0.3885 - loss: 0.8263 - mae: 0.6699 - rmse: 0.9060 - smape: 1.2739 - val_ia: 0.3424 - val_loss: 0.7570 - val_mae: 0.6450 - val_rmse: 0.8055 - val_smape: 1.2503

Epoch 11/16

120/120 - 3s - 29ms/step - ia: 0.3936 - loss: 0.8242 - mae: 0.6690 - rmse: 0.9056 - smape: 1.2682 - val_ia: 0.3357 - val_loss: 0.7493 - val_mae: 0.6388 - val_rmse: 0.7984 - val_smape: 1.2495

Epoch 12/16

120/120 - 3s - 21ms/step - ia: 0.3889 - loss: 0.8208 - mae: 0.6691 - rmse: 0.9037 - smape: 1.2768 - val_ia: 0.3427 - val_loss: 0.7465 - val_mae: 0.6340 - val_rmse: 0.7960 - val_smape: 1.2300

Epoch 13/16

120/120 - 2s - 19ms/step - ia: 0.3959 - loss: 0.8178 - mae: 0.6655 - rmse: 0.9021 - smape: 1.2662 - val_ia: 0.3320 - val_loss: 0.7472 - val_mae: 0.6406 - val_rmse: 0.7984 - val_smape: 1.2655

Epoch 14/16

120/120 - 3s - 26ms/step - ia: 0.3894 - loss: 0.8164 - mae: 0.6666 - rmse: 0.9015 - smape: 1.2737 - val_ia: 0.3423 - val_loss: 0.7491 - val_mae: 0.6408 - val_rmse: 0.8010 - val_smape: 1.2539

Epoch 15/16

120/120 - 2s - 21ms/step - ia: 0.3964 - loss: 0.8122 - mae: 0.6631 - rmse: 0.8993 - smape: 1.2654 - val_ia: 0.3455 - val_loss: 0.7439 - val_mae: 0.6345 - val_rmse: 0.7963 - val_smape: 1.2319

Epoch 16/16

120/120 - 3s - 21ms/step - ia: 0.3959 - loss: 0.8086 - mae: 0.6627 - rmse: 0.8974 - smape: 1.2678 - val_ia: 0.3450 - val_loss: 0.7461 - val_mae: 0.6379 - val_rmse: 0.7990 - val_smape: 1.2441

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:18 1s/step
  5/136 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
133/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 96%|█████████▌| 48/50 [3:45:34<07:40, 230.29s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 14s - 59ms/step - ia: 0.1363 - loss: 35.3191 - mae: 3.9799 - rmse: 5.9065 - smape: 1.6064 - val_ia: 0.1952 - val_loss: 9.0454 - val_mae: 2.5674 - val_rmse: 2.8357 - val_smape: 1.6241

Epoch 2/128

240/240 - 4s - 16ms/step - ia: 0.1419 - loss: 31.1603 - mae: 3.7469 - rmse: 5.5425 - smape: 1.6016 - val_ia: 0.2061 - val_loss: 7.5267 - val_mae: 2.3297 - val_rmse: 2.5941 - val_smape: 1.6045

Epoch 3/128

240/240 - 3s - 13ms/step - ia: 0.1489 - loss: 27.3961 - mae: 3.5446 - rmse: 5.1947 - smape: 1.5897 - val_ia: 0.2167 - val_loss: 6.3000 - val_mae: 2.1184 - val_rmse: 2.3797 - val_smape: 1.5864

Epoch 4/128

240/240 - 3s - 12ms/step - ia: 0.1563 - loss: 24.3831 - mae: 3.3484 - rmse: 4.9060 - smape: 1.5820 - val_ia: 0.2265 - val_loss: 5.3288 - val_mae: 1.9360 - val_rmse: 2.1944 - val_smape: 1.5701

Epoch 5/128

240/240 - 3s - 12ms/step - ia: 0.1604 - loss: 22.5263 - mae: 3.2204 - rmse: 4.7059 - smape: 1.5766 - val_ia: 0.2364 - val_loss: 4.5201 - val_mae: 1.7697 - val_rmse: 2.0256 - val_smape: 1.5545

Epoch 6/128

240/240 - 3s - 13ms/step - ia: 0.1669 - loss: 20.0574 - mae: 3.0711 - rmse: 4.4506 - smape: 1.5665 - val_ia: 0.2457 - val_loss: 3.8886 - val_mae: 1.6288 - val_rmse: 1.8824 - val_smape: 1.5393

Epoch 7/128

240/240 - 3s - 11ms/step - ia: 0.1737 - loss: 17.6837 - mae: 2.8929 - rmse: 4.1742 - smape: 1.5601 - val_ia: 0.2540 - val_loss: 3.4030 - val_mae: 1.5118 - val_rmse: 1.7634 - val_smape: 1.5265

Epoch 8/128

240/240 - 2s - 8ms/step - ia: 0.1751 - loss: 16.4983 - mae: 2.8048 - rmse: 4.0353 - smape: 1.5620 - val_ia: 0.2625 - val_loss: 2.9880 - val_mae: 1.4039 - val_rmse: 1.6537 - val_smape: 1.5127

Epoch 9/128

240/240 - 2s - 10ms/step - ia: 0.1785 - loss: 15.3098 - mae: 2.7107 - rmse: 3.8801 - smape: 1.5607 - val_ia: 0.2703 - val_loss: 2.6532 - val_mae: 1.3107 - val_rmse: 1.5587 - val_smape: 1.4986

Epoch 10/128

240/240 - 2s - 8ms/step - ia: 0.1854 - loss: 14.5797 - mae: 2.6214 - rmse: 3.7839 - smape: 1.5496 - val_ia: 0.2775 - val_loss: 2.3752 - val_mae: 1.2288 - val_rmse: 1.4747 - val_smape: 1.4842

Epoch 11/128

240/240 - 3s - 14ms/step - ia: 0.1891 - loss: 12.9480 - mae: 2.5139 - rmse: 3.5811 - smape: 1.5456 - val_ia: 0.2834 - val_loss: 2.1535 - val_mae: 1.1602 - val_rmse: 1.4034 - val_smape: 1.4717

Epoch 12/128

240/240 - 3s - 11ms/step - ia: 0.1958 - loss: 12.1993 - mae: 2.4280 - rmse: 3.4677 - smape: 1.5356 - val_ia: 0.2888 - val_loss: 1.9585 - val_mae: 1.0974 - val_rmse: 1.3371 - val_smape: 1.4607

Epoch 13/128

240/240 - 5s - 22ms/step - ia: 0.1974 - loss: 11.3975 - mae: 2.3504 - rmse: 3.3534 - smape: 1.5340 - val_ia: 0.2929 - val_loss: 1.8071 - val_mae: 1.0466 - val_rmse: 1.2826 - val_smape: 1.4527

Epoch 14/128

240/240 - 2s - 10ms/step - ia: 0.2052 - loss: 10.5783 - mae: 2.2679 - rmse: 3.2270 - smape: 1.5256 - val_ia: 0.2959 - val_loss: 1.6887 - val_mae: 1.0063 - val_rmse: 1.2382 - val_smape: 1.4467

Epoch 15/128

240/240 - 3s - 10ms/step - ia: 0.2039 - loss: 10.1779 - mae: 2.2254 - rmse: 3.1620 - smape: 1.5308 - val_ia: 0.2982 - val_loss: 1.5858 - val_mae: 0.9707 - val_rmse: 1.1983 - val_smape: 1.4408

Epoch 16/128

240/240 - 2s - 7ms/step - ia: 0.2051 - loss: 9.6676 - mae: 2.1901 - rmse: 3.0869 - smape: 1.5273 - val_ia: 0.3001 - val_loss: 1.4984 - val_mae: 0.9401 - val_rmse: 1.1634 - val_smape: 1.4350

Epoch 17/128

240/240 - 3s - 11ms/step - ia: 0.2101 - loss: 8.9745 - mae: 2.1100 - rmse: 2.9740 - smape: 1.5214 - val_ia: 0.3017 - val_loss: 1.4259 - val_mae: 0.9140 - val_rmse: 1.1332 - val_smape: 1.4287

Epoch 18/128

240/240 - 3s - 13ms/step - ia: 0.2162 - loss: 8.6102 - mae: 2.0396 - rmse: 2.9101 - smape: 1.5135 - val_ia: 0.3028 - val_loss: 1.3611 - val_mae: 0.8903 - val_rmse: 1.1054 - val_smape: 1.4231

Epoch 19/128

240/240 - 3s - 11ms/step - ia: 0.2178 - loss: 8.3506 - mae: 2.0114 - rmse: 2.8673 - smape: 1.5113 - val_ia: 0.3034 - val_loss: 1.3067 - val_mae: 0.8702 - val_rmse: 1.0813 - val_smape: 1.4182

Epoch 20/128

240/240 - 2s - 8ms/step - ia: 0.2202 - loss: 7.5771 - mae: 1.9440 - rmse: 2.7360 - smape: 1.5119 - val_ia: 0.3039 - val_loss: 1.2607 - val_mae: 0.8527 - val_rmse: 1.0601 - val_smape: 1.4143

Epoch 21/128

240/240 - 3s - 11ms/step - ia: 0.2262 - loss: 7.3300 - mae: 1.9046 - rmse: 2.6905 - smape: 1.5009 - val_ia: 0.3041 - val_loss: 1.2191 - val_mae: 0.8374 - val_rmse: 1.0410 - val_smape: 1.4116

Epoch 22/128

240/240 - 3s - 12ms/step - ia: 0.2239 - loss: 7.2217 - mae: 1.8743 - rmse: 2.6638 - smape: 1.5044 - val_ia: 0.3046 - val_loss: 1.1859 - val_mae: 0.8247 - val_rmse: 1.0251 - val_smape: 1.4095

Epoch 23/128

240/240 - 1s - 6ms/step - ia: 0.2333 - loss: 6.6297 - mae: 1.8095 - rmse: 2.5542 - smape: 1.4958 - val_ia: 0.3047 - val_loss: 1.1570 - val_mae: 0.8137 - val_rmse: 1.0111 - val_smape: 1.4079

Epoch 24/128

240/240 - 1s - 6ms/step - ia: 0.2276 - loss: 6.5636 - mae: 1.7980 - rmse: 2.5397 - smape: 1.5069 - val_ia: 0.3049 - val_loss: 1.1314 - val_mae: 0.8038 - val_rmse: 0.9984 - val_smape: 1.4052

Epoch 25/128

240/240 - 1s - 5ms/step - ia: 0.2350 - loss: 6.0956 - mae: 1.7473 - rmse: 2.4489 - smape: 1.4938 - val_ia: 0.3050 - val_loss: 1.1082 - val_mae: 0.7949 - val_rmse: 0.9868 - val_smape: 1.4040

Epoch 26/128

240/240 - 2s - 7ms/step - ia: 0.2350 - loss: 5.9523 - mae: 1.7255 - rmse: 2.4210 - smape: 1.4966 - val_ia: 0.3049 - val_loss: 1.0856 - val_mae: 0.7862 - val_rmse: 0.9750 - val_smape: 1.4039

Epoch 27/128

240/240 - 3s - 11ms/step - ia: 0.2416 - loss: 5.6080 - mae: 1.6691 - rmse: 2.3471 - smape: 1.4878 - val_ia: 0.3046 - val_loss: 1.0678 - val_mae: 0.7793 - val_rmse: 0.9657 - val_smape: 1.4050

Epoch 28/128

240/240 - 3s - 12ms/step - ia: 0.2412 - loss: 5.6045 - mae: 1.6574 - rmse: 2.3471 - smape: 1.4885 - val_ia: 0.3042 - val_loss: 1.0530 - val_mae: 0.7734 - val_rmse: 0.9575 - val_smape: 1.4067

Epoch 29/128

240/240 - 3s - 11ms/step - ia: 0.2450 - loss: 5.1871 - mae: 1.6233 - rmse: 2.2621 - smape: 1.4871 - val_ia: 0.3038 - val_loss: 1.0395 - val_mae: 0.7682 - val_rmse: 0.9500 - val_smape: 1.4088

Epoch 30/128

240/240 - 2s - 9ms/step - ia: 0.2498 - loss: 4.9524 - mae: 1.5774 - rmse: 2.2106 - smape: 1.4808 - val_ia: 0.3032 - val_loss: 1.0255 - val_mae: 0.7624 - val_rmse: 0.9420 - val_smape: 1.4090

Epoch 31/128

240/240 - 3s - 14ms/step - ia: 0.2473 - loss: 4.8387 - mae: 1.5570 - rmse: 2.1823 - smape: 1.4862 - val_ia: 0.3027 - val_loss: 1.0167 - val_mae: 0.7587 - val_rmse: 0.9366 - val_smape: 1.4118

Epoch 32/128

240/240 - 2s - 9ms/step - ia: 0.2558 - loss: 4.5283 - mae: 1.5121 - rmse: 2.1161 - smape: 1.4730 - val_ia: 0.3024 - val_loss: 1.0078 - val_mae: 0.7550 - val_rmse: 0.9312 - val_smape: 1.4150

Epoch 33/128

240/240 - 2s - 7ms/step - ia: 0.2481 - loss: 4.5396 - mae: 1.5076 - rmse: 2.1131 - smape: 1.4860 - val_ia: 0.3016 - val_loss: 0.9960 - val_mae: 0.7502 - val_rmse: 0.9242 - val_smape: 1.4166

Epoch 34/128

240/240 - 2s - 9ms/step - ia: 0.2544 - loss: 4.4069 - mae: 1.4788 - rmse: 2.0843 - smape: 1.4741 - val_ia: 0.3006 - val_loss: 0.9864 - val_mae: 0.7464 - val_rmse: 0.9185 - val_smape: 1.4191

Epoch 35/128

240/240 - 3s - 14ms/step - ia: 0.2569 - loss: 4.1420 - mae: 1.4444 - rmse: 2.0184 - smape: 1.4764 - val_ia: 0.3000 - val_loss: 0.9785 - val_mae: 0.7430 - val_rmse: 0.9135 - val_smape: 1.4217

Epoch 36/128

240/240 - 2s - 8ms/step - ia: 0.2575 - loss: 3.9692 - mae: 1.4256 - rmse: 1.9793 - smape: 1.4769 - val_ia: 0.2989 - val_loss: 0.9717 - val_mae: 0.7404 - val_rmse: 0.9092 - val_smape: 1.4255

Epoch 37/128

240/240 - 1s - 6ms/step - ia: 0.2584 - loss: 3.9353 - mae: 1.4088 - rmse: 1.9684 - smape: 1.4755 - val_ia: 0.2978 - val_loss: 0.9637 - val_mae: 0.7373 - val_rmse: 0.9043 - val_smape: 1.4283

Epoch 38/128

240/240 - 2s - 9ms/step - ia: 0.2634 - loss: 3.7555 - mae: 1.3801 - rmse: 1.9273 - smape: 1.4659 - val_ia: 0.2969 - val_loss: 0.9560 - val_mae: 0.7343 - val_rmse: 0.8997 - val_smape: 1.4303

Epoch 39/128

240/240 - 3s - 11ms/step - ia: 0.2587 - loss: 3.7391 - mae: 1.3810 - rmse: 1.9222 - smape: 1.4773 - val_ia: 0.2958 - val_loss: 0.9488 - val_mae: 0.7312 - val_rmse: 0.8951 - val_smape: 1.4325

Epoch 40/128

240/240 - 3s - 14ms/step - ia: 0.2632 - loss: 3.5817 - mae: 1.3580 - rmse: 1.8803 - smape: 1.4760 - val_ia: 0.2947 - val_loss: 0.9447 - val_mae: 0.7294 - val_rmse: 0.8919 - val_smape: 1.4382

Epoch 41/128

240/240 - 2s - 9ms/step - ia: 0.2637 - loss: 3.5116 - mae: 1.3374 - rmse: 1.8606 - smape: 1.4728 - val_ia: 0.2935 - val_loss: 0.9386 - val_mae: 0.7267 - val_rmse: 0.8878 - val_smape: 1.4410

Epoch 42/128

240/240 - 3s - 12ms/step - ia: 0.2605 - loss: 3.3503 - mae: 1.3136 - rmse: 1.8182 - smape: 1.4761 - val_ia: 0.2926 - val_loss: 0.9354 - val_mae: 0.7255 - val_rmse: 0.8854 - val_smape: 1.4462

Epoch 43/128

240/240 - 2s - 7ms/step - ia: 0.2643 - loss: 3.3167 - mae: 1.3034 - rmse: 1.8082 - smape: 1.4691 - val_ia: 0.2914 - val_loss: 0.9305 - val_mae: 0.7237 - val_rmse: 0.8823 - val_smape: 1.4503

Epoch 44/128

240/240 - 3s - 11ms/step - ia: 0.2689 - loss: 3.2537 - mae: 1.2878 - rmse: 1.7891 - smape: 1.4671 - val_ia: 0.2902 - val_loss: 0.9256 - val_mae: 0.7216 - val_rmse: 0.8789 - val_smape: 1.4542

Epoch 45/128

240/240 - 1s - 5ms/step - ia: 0.2672 - loss: 3.1299 - mae: 1.2681 - rmse: 1.7571 - smape: 1.4707 - val_ia: 0.2891 - val_loss: 0.9230 - val_mae: 0.7205 - val_rmse: 0.8768 - val_smape: 1.4596

Epoch 46/128

240/240 - 2s - 8ms/step - ia: 0.2732 - loss: 3.0116 - mae: 1.2432 - rmse: 1.7230 - smape: 1.4614 - val_ia: 0.2880 - val_loss: 0.9210 - val_mae: 0.7195 - val_rmse: 0.8749 - val_smape: 1.4653

Epoch 47/128

240/240 - 1s - 5ms/step - ia: 0.2705 - loss: 2.8629 - mae: 1.2282 - rmse: 1.6837 - smape: 1.4684 - val_ia: 0.2870 - val_loss: 0.9191 - val_mae: 0.7187 - val_rmse: 0.8732 - val_smape: 1.4707

Epoch 48/128

240/240 - 2s - 6ms/step - ia: 0.2722 - loss: 2.8119 - mae: 1.2136 - rmse: 1.6641 - smape: 1.4669 - val_ia: 0.2860 - val_loss: 0.9166 - val_mae: 0.7176 - val_rmse: 0.8713 - val_smape: 1.4750

Epoch 49/128

240/240 - 1s - 4ms/step - ia: 0.2701 - loss: 2.7735 - mae: 1.2001 - rmse: 1.6550 - smape: 1.4709 - val_ia: 0.2852 - val_loss: 0.9145 - val_mae: 0.7169 - val_rmse: 0.8697 - val_smape: 1.4805

Epoch 50/128

240/240 - 1s - 5ms/step - ia: 0.2718 - loss: 2.7345 - mae: 1.1930 - rmse: 1.6415 - smape: 1.4697 - val_ia: 0.2843 - val_loss: 0.9127 - val_mae: 0.7160 - val_rmse: 0.8681 - val_smape: 1.4853

Epoch 51/128

240/240 - 1s - 5ms/step - ia: 0.2711 - loss: 2.6360 - mae: 1.1769 - rmse: 1.6136 - smape: 1.4701 - val_ia: 0.2832 - val_loss: 0.9117 - val_mae: 0.7155 - val_rmse: 0.8669 - val_smape: 1.4911

Epoch 52/128

240/240 - 1s - 6ms/step - ia: 0.2766 - loss: 2.5461 - mae: 1.1536 - rmse: 1.5833 - smape: 1.4658 - val_ia: 0.2821 - val_loss: 0.9108 - val_mae: 0.7151 - val_rmse: 0.8658 - val_smape: 1.4970

Epoch 53/128

240/240 - 1s - 5ms/step - ia: 0.2767 - loss: 2.5092 - mae: 1.1463 - rmse: 1.5731 - smape: 1.4621 - val_ia: 0.2812 - val_loss: 0.9093 - val_mae: 0.7146 - val_rmse: 0.8645 - val_smape: 1.5020

Epoch 54/128

240/240 - 2s - 7ms/step - ia: 0.2748 - loss: 2.4311 - mae: 1.1408 - rmse: 1.5517 - smape: 1.4691 - val_ia: 0.2801 - val_loss: 0.9074 - val_mae: 0.7136 - val_rmse: 0.8628 - val_smape: 1.5060

Epoch 55/128

240/240 - 1s - 6ms/step - ia: 0.2718 - loss: 2.4410 - mae: 1.1359 - rmse: 1.5550 - smape: 1.4704 - val_ia: 0.2790 - val_loss: 0.9066 - val_mae: 0.7133 - val_rmse: 0.8618 - val_smape: 1.5117

Epoch 56/128

240/240 - 1s - 4ms/step - ia: 0.2732 - loss: 2.3425 - mae: 1.1168 - rmse: 1.5220 - smape: 1.4694 - val_ia: 0.2780 - val_loss: 0.9062 - val_mae: 0.7131 - val_rmse: 0.8610 - val_smape: 1.5171

Epoch 57/128

240/240 - 1s - 4ms/step - ia: 0.2726 - loss: 2.2724 - mae: 1.1068 - rmse: 1.4989 - smape: 1.4732 - val_ia: 0.2772 - val_loss: 0.9063 - val_mae: 0.7133 - val_rmse: 0.8607 - val_smape: 1.5241

Epoch 58/128

240/240 - 1s - 6ms/step - ia: 0.2780 - loss: 2.2017 - mae: 1.0920 - rmse: 1.4770 - smape: 1.4677 - val_ia: 0.2762 - val_loss: 0.9056 - val_mae: 0.7131 - val_rmse: 0.8599 - val_smape: 1.5291

Epoch 59/128

240/240 - 2s - 7ms/step - ia: 0.2753 - loss: 2.2068 - mae: 1.0874 - rmse: 1.4772 - smape: 1.4666 - val_ia: 0.2755 - val_loss: 0.9056 - val_mae: 0.7131 - val_rmse: 0.8595 - val_smape: 1.5349

Epoch 60/128

240/240 - 2s - 6ms/step - ia: 0.2786 - loss: 2.1231 - mae: 1.0714 - rmse: 1.4495 - smape: 1.4669 - val_ia: 0.2747 - val_loss: 0.9056 - val_mae: 0.7131 - val_rmse: 0.8591 - val_smape: 1.5402

Epoch 61/128

240/240 - 2s - 9ms/step - ia: 0.2746 - loss: 2.1434 - mae: 1.0707 - rmse: 1.4527 - smape: 1.4709 - val_ia: 0.2740 - val_loss: 0.9054 - val_mae: 0.7130 - val_rmse: 0.8585 - val_smape: 1.5452

Epoch 62/128

240/240 - 2s - 7ms/step - ia: 0.2787 - loss: 2.0757 - mae: 1.0606 - rmse: 1.4331 - smape: 1.4655 - val_ia: 0.2732 - val_loss: 0.9049 - val_mae: 0.7128 - val_rmse: 0.8579 - val_smape: 1.5499

Epoch 63/128

240/240 - 1s - 5ms/step - ia: 0.2744 - loss: 2.0663 - mae: 1.0564 - rmse: 1.4309 - smape: 1.4735 - val_ia: 0.2723 - val_loss: 0.9046 - val_mae: 0.7126 - val_rmse: 0.8573 - val_smape: 1.5549

Epoch 64/128

240/240 - 1s - 3ms/step - ia: 0.2787 - loss: 1.9887 - mae: 1.0401 - rmse: 1.4040 - smape: 1.4678 - val_ia: 0.2716 - val_loss: 0.9049 - val_mae: 0.7127 - val_rmse: 0.8570 - val_smape: 1.5603

Epoch 65/128

240/240 - 1s - 3ms/step - ia: 0.2782 - loss: 1.9700 - mae: 1.0340 - rmse: 1.3967 - smape: 1.4682 - val_ia: 0.2707 - val_loss: 0.9048 - val_mae: 0.7127 - val_rmse: 0.8565 - val_smape: 1.5657

Epoch 66/128

240/240 - 1s - 3ms/step - ia: 0.2760 - loss: 1.9186 - mae: 1.0226 - rmse: 1.3800 - smape: 1.4727 - val_ia: 0.2700 - val_loss: 0.9052 - val_mae: 0.7126 - val_rmse: 0.8562 - val_smape: 1.5703

Epoch 67/128

240/240 - 1s - 3ms/step - ia: 0.2767 - loss: 1.9091 - mae: 1.0154 - rmse: 1.3750 - smape: 1.4724 - val_ia: 0.2695 - val_loss: 0.9046 - val_mae: 0.7123 - val_rmse: 0.8556 - val_smape: 1.5740

Epoch 68/128

240/240 - 1s - 5ms/step - ia: 0.2769 - loss: 1.8394 - mae: 1.0035 - rmse: 1.3520 - smape: 1.4707 - val_ia: 0.2689 - val_loss: 0.9047 - val_mae: 0.7123 - val_rmse: 0.8553 - val_smape: 1.5788

Epoch 69/128

240/240 - 0s - 2ms/step - ia: 0.2727 - loss: 1.8747 - mae: 1.0092 - rmse: 1.3606 - smape: 1.4816 - val_ia: 0.2685 - val_loss: 0.9056 - val_mae: 0.7127 - val_rmse: 0.8555 - val_smape: 1.5847

Epoch 70/128

240/240 - 1s - 5ms/step - ia: 0.2726 - loss: 1.8110 - mae: 0.9978 - rmse: 1.3391 - smape: 1.4796 - val_ia: 0.2679 - val_loss: 0.9057 - val_mae: 0.7126 - val_rmse: 0.8552 - val_smape: 1.5890

Epoch 71/128

240/240 - 1s - 6ms/step - ia: 0.2740 - loss: 1.7775 - mae: 0.9897 - rmse: 1.3254 - smape: 1.4798 - val_ia: 0.2673 - val_loss: 0.9056 - val_mae: 0.7126 - val_rmse: 0.8549 - val_smape: 1.5935

Epoch 72/128

240/240 - 1s - 5ms/step - ia: 0.2728 - loss: 1.7712 - mae: 0.9841 - rmse: 1.3237 - smape: 1.4807 - val_ia: 0.2669 - val_loss: 0.9058 - val_mae: 0.7128 - val_rmse: 0.8548 - val_smape: 1.5984

Epoch 73/128

240/240 - 2s - 7ms/step - ia: 0.2724 - loss: 1.7763 - mae: 0.9796 - rmse: 1.3231 - smape: 1.4772 - val_ia: 0.2663 - val_loss: 0.9068 - val_mae: 0.7133 - val_rmse: 0.8552 - val_smape: 1.6050

Epoch 74/128

240/240 - 1s - 5ms/step - ia: 0.2782 - loss: 1.7157 - mae: 0.9638 - rmse: 1.3014 - smape: 1.4740 - val_ia: 0.2656 - val_loss: 0.9069 - val_mae: 0.7133 - val_rmse: 0.8549 - val_smape: 1.6097

Epoch 75/128

240/240 - 2s - 7ms/step - ia: 0.2735 - loss: 1.6720 - mae: 0.9611 - rmse: 1.2862 - smape: 1.4803 - val_ia: 0.2653 - val_loss: 0.9074 - val_mae: 0.7136 - val_rmse: 0.8550 - val_smape: 1.6145

Epoch 76/128

240/240 - 1s - 3ms/step - ia: 0.2747 - loss: 1.6459 - mae: 0.9528 - rmse: 1.2762 - smape: 1.4773 - val_ia: 0.2649 - val_loss: 0.9083 - val_mae: 0.7141 - val_rmse: 0.8554 - val_smape: 1.6201

Epoch 77/128

240/240 - 1s - 3ms/step - ia: 0.2695 - loss: 1.6494 - mae: 0.9560 - rmse: 1.2771 - smape: 1.4857 - val_ia: 0.2646 - val_loss: 0.9087 - val_mae: 0.7141 - val_rmse: 0.8553 - val_smape: 1.6237

Epoch 78/128

240/240 - 2s - 7ms/step - ia: 0.2691 - loss: 1.6338 - mae: 0.9497 - rmse: 1.2726 - smape: 1.4886 - val_ia: 0.2642 - val_loss: 0.9088 - val_mae: 0.7141 - val_rmse: 0.8552 - val_smape: 1.6273

Epoch 79/128

240/240 - 1s - 3ms/step - ia: 0.2732 - loss: 1.5874 - mae: 0.9379 - rmse: 1.2543 - smape: 1.4795 - val_ia: 0.2638 - val_loss: 0.9092 - val_mae: 0.7143 - val_rmse: 0.8552 - val_smape: 1.6315

Epoch 80/128

240/240 - 1s - 6ms/step - ia: 0.2712 - loss: 1.5900 - mae: 0.9386 - rmse: 1.2556 - smape: 1.4857 - val_ia: 0.2636 - val_loss: 0.9101 - val_mae: 0.7146 - val_rmse: 0.8555 - val_smape: 1.6360

Epoch 81/128

240/240 - 2s - 7ms/step - ia: 0.2697 - loss: 1.5747 - mae: 0.9338 - rmse: 1.2480 - smape: 1.4916 - val_ia: 0.2633 - val_loss: 0.9102 - val_mae: 0.7147 - val_rmse: 0.8555 - val_smape: 1.6399

Epoch 82/128

240/240 - 1s - 4ms/step - ia: 0.2704 - loss: 1.5560 - mae: 0.9290 - rmse: 1.2405 - smape: 1.4857 - val_ia: 0.2629 - val_loss: 0.9110 - val_mae: 0.7151 - val_rmse: 0.8557 - val_smape: 1.6450

Epoch 82: early stopping

Restoring model weights from the end of the best epoch: 67.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 37s 277ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 76/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 98%|█████████▊| 49/50 [3:48:28<03:33, 213.43s/trial, best loss: 0.7586230026386068]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/32

3830/3830 - 35s - 9ms/step - ia: 0.3704 - loss: 0.8909 - mae: 0.6963 - rmse: 0.8827 - smape: 1.3258 - val_ia: 0.2053 - val_loss: 0.7552 - val_mae: 0.6416 - val_rmse: 0.6829 - val_smape: 1.2583

Epoch 2/32

3830/3830 - 20s - 5ms/step - ia: 0.3831 - loss: 0.8249 - mae: 0.6672 - rmse: 0.8502 - smape: 1.3052 - val_ia: 0.2032 - val_loss: 0.7515 - val_mae: 0.6442 - val_rmse: 0.6834 - val_smape: 1.2926

Epoch 3/32

3830/3830 - 22s - 6ms/step - ia: 0.3859 - loss: 0.8161 - mae: 0.6644 - rmse: 0.8486 - smape: 1.2956 - val_ia: 0.2039 - val_loss: 0.7511 - val_mae: 0.6403 - val_rmse: 0.6801 - val_smape: 1.2618

Epoch 4/32

3830/3830 - 40s - 10ms/step - ia: 0.3899 - loss: 0.8112 - mae: 0.6622 - rmse: 0.8431 - smape: 1.2929 - val_ia: 0.2056 - val_loss: 0.7353 - val_mae: 0.6304 - val_rmse: 0.6719 - val_smape: 1.2514

Epoch 5/32

3830/3830 - 15s - 4ms/step - ia: 0.3918 - loss: 0.8118 - mae: 0.6611 - rmse: 0.8418 - smape: 1.2890 - val_ia: 0.2070 - val_loss: 0.7332 - val_mae: 0.6237 - val_rmse: 0.6658 - val_smape: 1.2247

Epoch 6/32

3830/3830 - 21s - 6ms/step - ia: 0.3939 - loss: 0.8080 - mae: 0.6587 - rmse: 0.8432 - smape: 1.2833 - val_ia: 0.2037 - val_loss: 0.7682 - val_mae: 0.6483 - val_rmse: 0.6901 - val_smape: 1.2716

Epoch 7/32

3830/3830 - 16s - 4ms/step - ia: 0.3905 - loss: 0.8117 - mae: 0.6620 - rmse: 0.8438 - smape: 1.2880 - val_ia: 0.1996 - val_loss: 0.7488 - val_mae: 0.6433 - val_rmse: 0.6839 - val_smape: 1.3206

Epoch 8/32

3830/3830 - 17s - 4ms/step - ia: 0.3915 - loss: 0.8096 - mae: 0.6613 - rmse: 0.8437 - smape: 1.2883 - val_ia: 0.2077 - val_loss: 0.7366 - val_mae: 0.6260 - val_rmse: 0.6683 - val_smape: 1.2181

Epoch 9/32

3830/3830 - 16s - 4ms/step - ia: 0.3917 - loss: 0.8078 - mae: 0.6605 - rmse: 0.8428 - smape: 1.2873 - val_ia: 0.2062 - val_loss: 0.7380 - val_mae: 0.6328 - val_rmse: 0.6736 - val_smape: 1.2691

Epoch 10/32

3830/3830 - 19s - 5ms/step - ia: 0.3934 - loss: 0.8069 - mae: 0.6597 - rmse: 0.8419 - smape: 1.2883 - val_ia: 0.2005 - val_loss: 0.7720 - val_mae: 0.6519 - val_rmse: 0.6936 - val_smape: 1.2792

Epoch 11/32

3830/3830 - 15s - 4ms/step - ia: 0.3916 - loss: 0.8081 - mae: 0.6605 - rmse: 0.8418 - smape: 1.2875 - val_ia: 0.2054 - val_loss: 0.7391 - val_mae: 0.6349 - val_rmse: 0.6758 - val_smape: 1.2560

Epoch 12/32

3830/3830 - 16s - 4ms/step - ia: 0.3915 - loss: 0.8055 - mae: 0.6593 - rmse: 0.8399 - smape: 1.2864 - val_ia: 0.2085 - val_loss: 0.7396 - val_mae: 0.6281 - val_rmse: 0.6718 - val_smape: 1.2344

Epoch 13/32

3830/3830 - 14s - 4ms/step - ia: 0.3947 - loss: 0.8041 - mae: 0.6583 - rmse: 0.8393 - smape: 1.2841 - val_ia: 0.2003 - val_loss: 0.7495 - val_mae: 0.6476 - val_rmse: 0.6882 - val_smape: 1.3112

Epoch 14/32

3830/3830 - 16s - 4ms/step - ia: 0.3960 - loss: 0.8023 - mae: 0.6586 - rmse: 0.8389 - smape: 1.2801 - val_ia: 0.2030 - val_loss: 0.7423 - val_mae: 0.6341 - val_rmse: 0.6755 - val_smape: 1.2701

Epoch 15/32

3830/3830 - 16s - 4ms/step - ia: 0.3930 - loss: 0.8066 - mae: 0.6584 - rmse: 0.8409 - smape: 1.2865 - val_ia: 0.2068 - val_loss: 0.7362 - val_mae: 0.6265 - val_rmse: 0.6693 - val_smape: 1.2497

Epoch 16/32

3830/3830 - 18s - 5ms/step - ia: 0.3947 - loss: 0.8013 - mae: 0.6578 - rmse: 0.8394 - smape: 1.2845 - val_ia: 0.2033 - val_loss: 0.7387 - val_mae: 0.6309 - val_rmse: 0.6727 - val_smape: 1.2488

Epoch 17/32

3830/3830 - 21s - 6ms/step - ia: 0.3970 - loss: 0.8025 - mae: 0.6572 - rmse: 0.8376 - smape: 1.2785 - val_ia: 0.2067 - val_loss: 0.7476 - val_mae: 0.6320 - val_rmse: 0.6760 - val_smape: 1.2286

Epoch 18/32

3830/3830 - 17s - 4ms/step - ia: 0.3978 - loss: 0.7989 - mae: 0.6564 - rmse: 0.8378 - smape: 1.2781 - val_ia: 0.2061 - val_loss: 0.7360 - val_mae: 0.6291 - val_rmse: 0.6726 - val_smape: 1.2483

Epoch 19/32

3830/3830 - 18s - 5ms/step - ia: 0.3965 - loss: 0.7970 - mae: 0.6571 - rmse: 0.8357 - smape: 1.2827 - val_ia: 0.2097 - val_loss: 0.7295 - val_mae: 0.6218 - val_rmse: 0.6656 - val_smape: 1.2053

Epoch 20/32

3830/3830 - 14s - 4ms/step - ia: 0.3971 - loss: 0.7986 - mae: 0.6564 - rmse: 0.8362 - smape: 1.2796 - val_ia: 0.2062 - val_loss: 0.7426 - val_mae: 0.6281 - val_rmse: 0.6727 - val_smape: 1.2156

Epoch 21/32

3830/3830 - 20s - 5ms/step - ia: 0.3979 - loss: 0.7975 - mae: 0.6562 - rmse: 0.8361 - smape: 1.2834 - val_ia: 0.2068 - val_loss: 0.7400 - val_mae: 0.6252 - val_rmse: 0.6671 - val_smape: 1.2384

Epoch 22/32

3830/3830 - 18s - 5ms/step - ia: 0.3991 - loss: 0.7972 - mae: 0.6558 - rmse: 0.8360 - smape: 1.2815 - val_ia: 0.1991 - val_loss: 0.7540 - val_mae: 0.6586 - val_rmse: 0.6986 - val_smape: 1.3601

Epoch 23/32

3830/3830 - 24s - 6ms/step - ia: 0.3993 - loss: 0.7972 - mae: 0.6557 - rmse: 0.8354 - smape: 1.2769 - val_ia: 0.2091 - val_loss: 0.7332 - val_mae: 0.6196 - val_rmse: 0.6635 - val_smape: 1.2015

Epoch 24/32

3830/3830 - 27s - 7ms/step - ia: 0.3982 - loss: 0.7977 - mae: 0.6560 - rmse: 0.8368 - smape: 1.2820 - val_ia: 0.2046 - val_loss: 0.7324 - val_mae: 0.6287 - val_rmse: 0.6690 - val_smape: 1.2655

Epoch 25/32

3830/3830 - 18s - 5ms/step - ia: 0.3948 - loss: 0.7993 - mae: 0.6569 - rmse: 0.8381 - smape: 1.2786 - val_ia: 0.2020 - val_loss: 0.7462 - val_mae: 0.6430 - val_rmse: 0.6851 - val_smape: 1.3078

Epoch 26/32

3830/3830 - 17s - 4ms/step - ia: 0.3984 - loss: 0.7955 - mae: 0.6554 - rmse: 0.8354 - smape: 1.2820 - val_ia: 0.2042 - val_loss: 0.7315 - val_mae: 0.6345 - val_rmse: 0.6758 - val_smape: 1.2880

Epoch 27/32

3830/3830 - 21s - 5ms/step - ia: 0.3992 - loss: 0.7970 - mae: 0.6545 - rmse: 0.8364 - smape: 1.2763 - val_ia: 0.2051 - val_loss: 0.7376 - val_mae: 0.6358 - val_rmse: 0.6772 - val_smape: 1.2616

Epoch 28/32

3830/3830 - 22s - 6ms/step - ia: 0.4009 - loss: 0.7935 - mae: 0.6545 - rmse: 0.8345 - smape: 1.2755 - val_ia: 0.2034 - val_loss: 0.7427 - val_mae: 0.6408 - val_rmse: 0.6830 - val_smape: 1.2725

Epoch 29/32

3830/3830 - 23s - 6ms/step - ia: 0.3985 - loss: 0.7938 - mae: 0.6540 - rmse: 0.8325 - smape: 1.2821 - val_ia: 0.2032 - val_loss: 0.7373 - val_mae: 0.6383 - val_rmse: 0.6807 - val_smape: 1.2881

Epoch 30/32

3830/3830 - 19s - 5ms/step - ia: 0.3988 - loss: 0.7909 - mae: 0.6538 - rmse: 0.8335 - smape: 1.2787 - val_ia: 0.2041 - val_loss: 0.7484 - val_mae: 0.6413 - val_rmse: 0.6833 - val_smape: 1.2669

Epoch 31/32

3830/3830 - 20s - 5ms/step - ia: 0.3991 - loss: 0.7951 - mae: 0.6553 - rmse: 0.8359 - smape: 1.2812 - val_ia: 0.2045 - val_loss: 0.7400 - val_mae: 0.6347 - val_rmse: 0.6761 - val_smape: 1.2803

Epoch 32/32

3830/3830 - 19s - 5ms/step - ia: 0.3969 - loss: 0.7977 - mae: 0.6559 - rmse: 0.8365 - smape: 1.2754 - val_ia: 0.2034 - val_loss: 0.7413 - val_mae: 0.6326 - val_rmse: 0.6745 - val_smape: 1.2677

Restoring model weights from the end of the best epoch: 19.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:19 590ms/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
 20/136 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step
 21/136 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step
 24/136 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step
 58/136 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
 77/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
126/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

100%|██████████| 50/50 [3:59:09<00:00, 287.00s/trial, best loss: 0.7586230026386068]
{'activation': 1, 'batch': 0, 'dropout': 0.1, 'epochs': 2, 'layers': 4.0, 'learning_rate': 0.0007115052124615948, 'units': 0}

In [24]:
print(best)

{'activation': 1, 'batch': 0, 'dropout': 0.1, 'epochs': 2, 'layers': 4.0, 'learning_rate': 0.0007115052124615948, 'units': 0}