Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [4]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [5]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [6]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [7]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [8]:
datosNormalizados.shape

(52416, 5)

In [9]:
datosNormalizados.head(37)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823
2017-01-01 02:10:00 -2.308740 -1.464790 -1.131650 -0.649995 -1.371823
2017-01-01 02:20:00 -2.307607 -1.497449 -1.188510 -0.673256 -1.371823
2017-01-01 02:30:00 -2.320226 -1.523410 -1.251127 -0.684886 -1.371823
2017-01-01 02:40:00 -2.300328 -1.553557 -1.278478 -0.698305 -1.371823
2017-01-01 02:50:00 -2.237721 -1.581192 -1.348293 -0.725144 -1.371823
2017-01-01 03:00:00 -2.276223 -1.633112 -1.363408 -0.755561 -1.227305
2017-01-01 03:10:00 -2.290459 -1.648186 -1.395796 -0.768086 -1.227305
2017-01-01 03:20:00 -2.296930 -1.665772 -1.430344 -0.775243 -1.227305
2017-01-01 03:30:00 -2.298063 -1.665772 -1.436102 -0.793136 -1.227305
2017-01-01 03:40:00 -2.320388 -1.703456 -1.441860 -0.838762 -1.227305
2017-01-01 03:50:00 -2.335109 -1.727742 -1.487204 -0.840551 -1.227305
2017-01-01 04:00:00 -2.343522 -1.713505 -1.504477 -0.841445 -1.082788
2017-01-01 04:10:00 -2.319579 -1.719367 -1.462732 -0.862022 -1.082788
2017-01-01 04:20:00 -2.270723 -1.712668 -1.483605 -0.896018 -1.082788
2017-01-01 04:30:00 -2.239824 -1.715180 -1.479286 -0.907648 -1.082788
2017-01-01 04:40:00 -2.278326 -1.717693 -1.484325 -0.896018 -1.082788
2017-01-01 04:50:00 -2.274605 -1.742815 -1.492962 -0.894228 -1.082788
2017-01-01 05:00:00 -2.314240 -1.710993 -1.507356 -0.894228 -0.938270
2017-01-01 05:10:00 -2.349184 -1.700107 -1.498000 -0.915699 -0.938270
2017-01-01 05:20:00 -2.215234 -1.699269 -1.500159 -0.890650 -0.938270
2017-01-01 05:30:00 -2.358890 -1.675821 -1.441860 -0.877230 -0.938270
2017-01-01 05:40:00 -2.403540 -1.667447 -1.428904 -0.848602 -0.938270
2017-01-01 05:50:00 -2.431042 -1.593753 -1.355490 -0.798503 -0.938270
2017-01-01 06:00:00 -2.415511 -1.479863 -1.258325 -0.791346 -0.793753

Espacio de búsqueda

In [10]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [11]:
futuros = 24
pasados  = 12

In [12]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [13]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [14]:
print(datosY[0])

[-1.59375341]

Se dividen nuevamente los conjuntos de datos

In [15]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 12, 5)
Las dimensiones de testX son:  (10529, 12, 5)
Las dimensiones de valX son:  (5186, 12, 5)

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [17]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [18]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [19]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [20]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 19s - 65ms/step - ia: 0.2480 - loss: 1.2267 - mae: 0.9102 - rmse: 1.1050 - smape: 1.5068 - val_ia: 0.2173 - val_loss: 0.8542 - val_mae: 0.7688 - val_rmse: 0.9176 - val_smape: 1.9034

Epoch 2/128

287/287 - 9s - 30ms/step - ia: 0.2012 - loss: 1.0900 - mae: 0.8644 - rmse: 1.0427 - smape: 1.5664 - val_ia: 0.2112 - val_loss: 0.8683 - val_mae: 0.7758 - val_rmse: 0.9243 - val_smape: 1.8613

Epoch 3/128

287/287 - 5s - 18ms/step - ia: 0.1762 - loss: 1.0567 - mae: 0.8516 - rmse: 1.0266 - smape: 1.6053 - val_ia: 0.2115 - val_loss: 0.8685 - val_mae: 0.7759 - val_rmse: 0.9243 - val_smape: 1.8414

Epoch 4/128

287/287 - 5s - 18ms/step - ia: 0.1573 - loss: 1.0334 - mae: 0.8434 - rmse: 1.0151 - smape: 1.6402 - val_ia: 0.2129 - val_loss: 0.8641 - val_mae: 0.7738 - val_rmse: 0.9220 - val_smape: 1.8438

Epoch 5/128

287/287 - 5s - 16ms/step - ia: 0.1486 - loss: 1.0137 - mae: 0.8351 - rmse: 1.0057 - smape: 1.6557 - val_ia: 0.2160 - val_loss: 0.8587 - val_mae: 0.7711 - val_rmse: 0.9190 - val_smape: 1.8154

Epoch 6/128

287/287 - 6s - 20ms/step - ia: 0.1554 - loss: 0.9807 - mae: 0.8210 - rmse: 0.9891 - smape: 1.6417 - val_ia: 0.2299 - val_loss: 0.8309 - val_mae: 0.7574 - val_rmse: 0.9038 - val_smape: 1.7428

Epoch 7/128

287/287 - 6s - 21ms/step - ia: 0.2570 - loss: 0.8578 - mae: 0.7614 - rmse: 0.9240 - smape: 1.4706 - val_ia: 0.2938 - val_loss: 0.8367 - val_mae: 0.7595 - val_rmse: 0.9015 - val_smape: 1.4534

Epoch 8/128

287/287 - 9s - 30ms/step - ia: 0.4681 - loss: 0.6440 - mae: 0.6509 - rmse: 0.8008 - smape: 1.1438 - val_ia: 0.3739 - val_loss: 0.9480 - val_mae: 0.8166 - val_rmse: 0.9478 - val_smape: 1.3534

Epoch 9/128

287/287 - 5s - 17ms/step - ia: 0.5661 - loss: 0.5527 - mae: 0.5994 - rmse: 0.7421 - smape: 0.9981 - val_ia: 0.3963 - val_loss: 0.9606 - val_mae: 0.8255 - val_rmse: 0.9494 - val_smape: 1.3430

Epoch 10/128

287/287 - 5s - 18ms/step - ia: 0.5968 - loss: 0.5102 - mae: 0.5743 - rmse: 0.7128 - smape: 0.9548 - val_ia: 0.4101 - val_loss: 0.9484 - val_mae: 0.8196 - val_rmse: 0.9420 - val_smape: 1.3327

Epoch 11/128

287/287 - 5s - 17ms/step - ia: 0.6111 - loss: 0.4852 - mae: 0.5590 - rmse: 0.6951 - smape: 0.9356 - val_ia: 0.4248 - val_loss: 0.9387 - val_mae: 0.8113 - val_rmse: 0.9364 - val_smape: 1.3114

Epoch 12/128

287/287 - 5s - 18ms/step - ia: 0.6204 - loss: 0.4708 - mae: 0.5494 - rmse: 0.6849 - smape: 0.9249 - val_ia: 0.4414 - val_loss: 0.9004 - val_mae: 0.7946 - val_rmse: 0.9133 - val_smape: 1.2935

Epoch 13/128

287/287 - 5s - 19ms/step - ia: 0.6284 - loss: 0.4558 - mae: 0.5419 - rmse: 0.6737 - smape: 0.9108 - val_ia: 0.4626 - val_loss: 0.8368 - val_mae: 0.7610 - val_rmse: 0.8780 - val_smape: 1.2576

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.6391 - loss: 0.4386 - mae: 0.5292 - rmse: 0.6610 - smape: 0.8990 - val_ia: 0.4809 - val_loss: 0.7841 - val_mae: 0.7321 - val_rmse: 0.8488 - val_smape: 1.2232

Epoch 15/128

287/287 - 5s - 18ms/step - ia: 0.6383 - loss: 0.4337 - mae: 0.5288 - rmse: 0.6575 - smape: 0.9008 - val_ia: 0.4986 - val_loss: 0.7613 - val_mae: 0.7175 - val_rmse: 0.8352 - val_smape: 1.1886

Epoch 16/128

287/287 - 5s - 17ms/step - ia: 0.6417 - loss: 0.4302 - mae: 0.5256 - rmse: 0.6544 - smape: 0.8976 - val_ia: 0.5143 - val_loss: 0.7187 - val_mae: 0.6935 - val_rmse: 0.8112 - val_smape: 1.1567

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 0.6496 - loss: 0.4142 - mae: 0.5154 - rmse: 0.6424 - smape: 0.8875 - val_ia: 0.5278 - val_loss: 0.6865 - val_mae: 0.6757 - val_rmse: 0.7922 - val_smape: 1.1321

Epoch 18/128

287/287 - 6s - 20ms/step - ia: 0.6531 - loss: 0.4091 - mae: 0.5121 - rmse: 0.6382 - smape: 0.8833 - val_ia: 0.5443 - val_loss: 0.6402 - val_mae: 0.6477 - val_rmse: 0.7665 - val_smape: 1.0988

Epoch 19/128

287/287 - 11s - 37ms/step - ia: 0.6536 - loss: 0.4056 - mae: 0.5087 - rmse: 0.6359 - smape: 0.8856 - val_ia: 0.5556 - val_loss: 0.6225 - val_mae: 0.6380 - val_rmse: 0.7551 - val_smape: 1.0808

Epoch 20/128

287/287 - 6s - 19ms/step - ia: 0.6574 - loss: 0.3999 - mae: 0.5053 - rmse: 0.6311 - smape: 0.8814 - val_ia: 0.5630 - val_loss: 0.6043 - val_mae: 0.6269 - val_rmse: 0.7452 - val_smape: 1.0698

Epoch 21/128

287/287 - 10s - 36ms/step - ia: 0.6606 - loss: 0.3939 - mae: 0.5007 - rmse: 0.6265 - smape: 0.8776 - val_ia: 0.5734 - val_loss: 0.5722 - val_mae: 0.6097 - val_rmse: 0.7255 - val_smape: 1.0536

Epoch 22/128

287/287 - 6s - 21ms/step - ia: 0.6632 - loss: 0.3899 - mae: 0.4975 - rmse: 0.6233 - smape: 0.8725 - val_ia: 0.5792 - val_loss: 0.5587 - val_mae: 0.6016 - val_rmse: 0.7178 - val_smape: 1.0448

Epoch 23/128

287/287 - 5s - 18ms/step - ia: 0.6650 - loss: 0.3844 - mae: 0.4938 - rmse: 0.6188 - smape: 0.8734 - val_ia: 0.5800 - val_loss: 0.5729 - val_mae: 0.6094 - val_rmse: 0.7259 - val_smape: 1.0427

Epoch 24/128

287/287 - 5s - 19ms/step - ia: 0.6670 - loss: 0.3817 - mae: 0.4920 - rmse: 0.6166 - smape: 0.8706 - val_ia: 0.5904 - val_loss: 0.5476 - val_mae: 0.5951 - val_rmse: 0.7107 - val_smape: 1.0286

Epoch 25/128

287/287 - 11s - 37ms/step - ia: 0.6699 - loss: 0.3763 - mae: 0.4885 - rmse: 0.6122 - smape: 0.8692 - val_ia: 0.5968 - val_loss: 0.5228 - val_mae: 0.5819 - val_rmse: 0.6951 - val_smape: 1.0210

Epoch 26/128

287/287 - 6s - 20ms/step - ia: 0.6709 - loss: 0.3751 - mae: 0.4862 - rmse: 0.6112 - smape: 0.8696 - val_ia: 0.5941 - val_loss: 0.5363 - val_mae: 0.5891 - val_rmse: 0.7045 - val_smape: 1.0253

Epoch 27/128

287/287 - 11s - 37ms/step - ia: 0.6718 - loss: 0.3727 - mae: 0.4851 - rmse: 0.6093 - smape: 0.8689 - val_ia: 0.6000 - val_loss: 0.5216 - val_mae: 0.5816 - val_rmse: 0.6944 - val_smape: 1.0161

Epoch 28/128

287/287 - 10s - 35ms/step - ia: 0.6733 - loss: 0.3688 - mae: 0.4831 - rmse: 0.6061 - smape: 0.8648 - val_ia: 0.6032 - val_loss: 0.5100 - val_mae: 0.5749 - val_rmse: 0.6868 - val_smape: 1.0098

Epoch 29/128

287/287 - 5s - 18ms/step - ia: 0.6747 - loss: 0.3689 - mae: 0.4817 - rmse: 0.6061 - smape: 0.8641 - val_ia: 0.6081 - val_loss: 0.4936 - val_mae: 0.5660 - val_rmse: 0.6770 - val_smape: 1.0041

Epoch 30/128

287/287 - 7s - 23ms/step - ia: 0.6777 - loss: 0.3615 - mae: 0.4774 - rmse: 0.6000 - smape: 0.8610 - val_ia: 0.6102 - val_loss: 0.4868 - val_mae: 0.5619 - val_rmse: 0.6721 - val_smape: 1.0006

Epoch 31/128

287/287 - 9s - 31ms/step - ia: 0.6789 - loss: 0.3590 - mae: 0.4756 - rmse: 0.5980 - smape: 0.8582 - val_ia: 0.6119 - val_loss: 0.4837 - val_mae: 0.5601 - val_rmse: 0.6705 - val_smape: 0.9980

Epoch 32/128

287/287 - 5s - 18ms/step - ia: 0.6810 - loss: 0.3545 - mae: 0.4726 - rmse: 0.5944 - smape: 0.8582 - val_ia: 0.6157 - val_loss: 0.4673 - val_mae: 0.5515 - val_rmse: 0.6600 - val_smape: 0.9931

Epoch 33/128

287/287 - 5s - 17ms/step - ia: 0.6823 - loss: 0.3539 - mae: 0.4713 - rmse: 0.5935 - smape: 0.8560 - val_ia: 0.6144 - val_loss: 0.4693 - val_mae: 0.5519 - val_rmse: 0.6613 - val_smape: 0.9949

Epoch 34/128

287/287 - 5s - 18ms/step - ia: 0.6859 - loss: 0.3460 - mae: 0.4663 - rmse: 0.5871 - smape: 0.8527 - val_ia: 0.6216 - val_loss: 0.4566 - val_mae: 0.5458 - val_rmse: 0.6525 - val_smape: 0.9838

Epoch 35/128

287/287 - 5s - 18ms/step - ia: 0.6842 - loss: 0.3490 - mae: 0.4681 - rmse: 0.5893 - smape: 0.8591 - val_ia: 0.6213 - val_loss: 0.4511 - val_mae: 0.5415 - val_rmse: 0.6491 - val_smape: 0.9843

Epoch 36/128

287/287 - 5s - 18ms/step - ia: 0.6850 - loss: 0.3464 - mae: 0.4662 - rmse: 0.5876 - smape: 0.8578 - val_ia: 0.6278 - val_loss: 0.4299 - val_mae: 0.5304 - val_rmse: 0.6347 - val_smape: 0.9757

Epoch 37/128

287/287 - 5s - 17ms/step - ia: 0.6884 - loss: 0.3415 - mae: 0.4623 - rmse: 0.5831 - smape: 0.8525 - val_ia: 0.6318 - val_loss: 0.4167 - val_mae: 0.5229 - val_rmse: 0.6252 - val_smape: 0.9700

Epoch 38/128

287/287 - 5s - 18ms/step - ia: 0.6910 - loss: 0.3370 - mae: 0.4583 - rmse: 0.5792 - smape: 0.8523 - val_ia: 0.6326 - val_loss: 0.4142 - val_mae: 0.5207 - val_rmse: 0.6238 - val_smape: 0.9682

Epoch 39/128

287/287 - 5s - 17ms/step - ia: 0.6946 - loss: 0.3308 - mae: 0.4532 - rmse: 0.5739 - smape: 0.8444 - val_ia: 0.6336 - val_loss: 0.4109 - val_mae: 0.5193 - val_rmse: 0.6207 - val_smape: 0.9675

Epoch 40/128

287/287 - 5s - 18ms/step - ia: 0.6970 - loss: 0.3249 - mae: 0.4500 - rmse: 0.5689 - smape: 0.8464 - val_ia: 0.6335 - val_loss: 0.4019 - val_mae: 0.5128 - val_rmse: 0.6156 - val_smape: 0.9678

Epoch 41/128

287/287 - 5s - 16ms/step - ia: 0.6984 - loss: 0.3228 - mae: 0.4477 - rmse: 0.5668 - smape: 0.8459 - val_ia: 0.6390 - val_loss: 0.3848 - val_mae: 0.5011 - val_rmse: 0.6031 - val_smape: 0.9581

Epoch 42/128

287/287 - 5s - 18ms/step - ia: 0.7014 - loss: 0.3168 - mae: 0.4425 - rmse: 0.5617 - smape: 0.8426 - val_ia: 0.6396 - val_loss: 0.3870 - val_mae: 0.5038 - val_rmse: 0.6038 - val_smape: 0.9575

Epoch 43/128

287/287 - 5s - 18ms/step - ia: 0.7016 - loss: 0.3151 - mae: 0.4424 - rmse: 0.5601 - smape: 0.8468 - val_ia: 0.6417 - val_loss: 0.3828 - val_mae: 0.5019 - val_rmse: 0.5994 - val_smape: 0.9523

Epoch 44/128

287/287 - 5s - 18ms/step - ia: 0.7068 - loss: 0.3078 - mae: 0.4349 - rmse: 0.5536 - smape: 0.8392 - val_ia: 0.6440 - val_loss: 0.3755 - val_mae: 0.4975 - val_rmse: 0.5943 - val_smape: 0.9451

Epoch 45/128

287/287 - 5s - 18ms/step - ia: 0.7073 - loss: 0.3064 - mae: 0.4339 - rmse: 0.5522 - smape: 0.8376 - val_ia: 0.6465 - val_loss: 0.3698 - val_mae: 0.4943 - val_rmse: 0.5901 - val_smape: 0.9398

Epoch 46/128

287/287 - 5s - 18ms/step - ia: 0.7109 - loss: 0.2989 - mae: 0.4288 - rmse: 0.5455 - smape: 0.8310 - val_ia: 0.6502 - val_loss: 0.3642 - val_mae: 0.4917 - val_rmse: 0.5858 - val_smape: 0.9352

Epoch 47/128

287/287 - 5s - 17ms/step - ia: 0.7122 - loss: 0.2959 - mae: 0.4265 - rmse: 0.5430 - smape: 0.8336 - val_ia: 0.6539 - val_loss: 0.3539 - val_mae: 0.4873 - val_rmse: 0.5768 - val_smape: 0.9302

Epoch 48/128

287/287 - 5s - 17ms/step - ia: 0.7144 - loss: 0.2916 - mae: 0.4229 - rmse: 0.5389 - smape: 0.8320 - val_ia: 0.6606 - val_loss: 0.3419 - val_mae: 0.4803 - val_rmse: 0.5663 - val_smape: 0.9206

Epoch 49/128

287/287 - 5s - 17ms/step - ia: 0.7177 - loss: 0.2867 - mae: 0.4184 - rmse: 0.5342 - smape: 0.8238 - val_ia: 0.6666 - val_loss: 0.3282 - val_mae: 0.4715 - val_rmse: 0.5558 - val_smape: 0.9101

Epoch 50/128

287/287 - 5s - 17ms/step - ia: 0.7207 - loss: 0.2815 - mae: 0.4146 - rmse: 0.5290 - smape: 0.8213 - val_ia: 0.6672 - val_loss: 0.3282 - val_mae: 0.4726 - val_rmse: 0.5555 - val_smape: 0.9103

Epoch 51/128

287/287 - 5s - 18ms/step - ia: 0.7215 - loss: 0.2786 - mae: 0.4135 - rmse: 0.5264 - smape: 0.8218 - val_ia: 0.6718 - val_loss: 0.3118 - val_mae: 0.4620 - val_rmse: 0.5412 - val_smape: 0.9044

Epoch 52/128

287/287 - 5s - 18ms/step - ia: 0.7225 - loss: 0.2766 - mae: 0.4120 - rmse: 0.5248 - smape: 0.8215 - val_ia: 0.6775 - val_loss: 0.3046 - val_mae: 0.4583 - val_rmse: 0.5348 - val_smape: 0.8954

Epoch 53/128

287/287 - 5s - 16ms/step - ia: 0.7259 - loss: 0.2717 - mae: 0.4074 - rmse: 0.5200 - smape: 0.8143 - val_ia: 0.6816 - val_loss: 0.2932 - val_mae: 0.4504 - val_rmse: 0.5251 - val_smape: 0.8881

Epoch 54/128

287/287 - 5s - 16ms/step - ia: 0.7254 - loss: 0.2721 - mae: 0.4079 - rmse: 0.5204 - smape: 0.8155 - val_ia: 0.6823 - val_loss: 0.2925 - val_mae: 0.4510 - val_rmse: 0.5243 - val_smape: 0.8855

Epoch 55/128

287/287 - 5s - 17ms/step - ia: 0.7260 - loss: 0.2697 - mae: 0.4078 - rmse: 0.5182 - smape: 0.8167 - val_ia: 0.6866 - val_loss: 0.2805 - val_mae: 0.4425 - val_rmse: 0.5131 - val_smape: 0.8791

Epoch 56/128

287/287 - 5s - 17ms/step - ia: 0.7266 - loss: 0.2679 - mae: 0.4062 - rmse: 0.5165 - smape: 0.8153 - val_ia: 0.6869 - val_loss: 0.2849 - val_mae: 0.4458 - val_rmse: 0.5163 - val_smape: 0.8792

Epoch 57/128

287/287 - 5s - 17ms/step - ia: 0.7302 - loss: 0.2626 - mae: 0.4015 - rmse: 0.5112 - smape: 0.8080 - val_ia: 0.6959 - val_loss: 0.2641 - val_mae: 0.4309 - val_rmse: 0.4977 - val_smape: 0.8623

Epoch 58/128

287/287 - 5s - 18ms/step - ia: 0.7273 - loss: 0.2678 - mae: 0.4058 - rmse: 0.5164 - smape: 0.8136 - val_ia: 0.6943 - val_loss: 0.2658 - val_mae: 0.4318 - val_rmse: 0.4989 - val_smape: 0.8630

Epoch 59/128

287/287 - 5s - 18ms/step - ia: 0.7286 - loss: 0.2649 - mae: 0.4033 - rmse: 0.5134 - smape: 0.8114 - val_ia: 0.6975 - val_loss: 0.2610 - val_mae: 0.4284 - val_rmse: 0.4942 - val_smape: 0.8591

Epoch 60/128

287/287 - 5s - 18ms/step - ia: 0.7298 - loss: 0.2625 - mae: 0.4019 - rmse: 0.5112 - smape: 0.8108 - val_ia: 0.7037 - val_loss: 0.2432 - val_mae: 0.4143 - val_rmse: 0.4781 - val_smape: 0.8474

Epoch 61/128

287/287 - 5s - 17ms/step - ia: 0.7301 - loss: 0.2610 - mae: 0.4008 - rmse: 0.5097 - smape: 0.8110 - val_ia: 0.7021 - val_loss: 0.2468 - val_mae: 0.4172 - val_rmse: 0.4816 - val_smape: 0.8481

Epoch 62/128

287/287 - 5s - 18ms/step - ia: 0.7332 - loss: 0.2565 - mae: 0.3975 - rmse: 0.5054 - smape: 0.7992 - val_ia: 0.7046 - val_loss: 0.2471 - val_mae: 0.4178 - val_rmse: 0.4806 - val_smape: 0.8460

Epoch 63/128

287/287 - 5s - 17ms/step - ia: 0.7316 - loss: 0.2598 - mae: 0.3989 - rmse: 0.5086 - smape: 0.8053 - val_ia: 0.7046 - val_loss: 0.2518 - val_mae: 0.4215 - val_rmse: 0.4848 - val_smape: 0.8465

Epoch 64/128

287/287 - 5s - 17ms/step - ia: 0.7330 - loss: 0.2583 - mae: 0.3981 - rmse: 0.5073 - smape: 0.8047 - val_ia: 0.7015 - val_loss: 0.2502 - val_mae: 0.4194 - val_rmse: 0.4834 - val_smape: 0.8485

Epoch 65/128

287/287 - 5s - 18ms/step - ia: 0.7338 - loss: 0.2550 - mae: 0.3966 - rmse: 0.5038 - smape: 0.8009 - val_ia: 0.7117 - val_loss: 0.2355 - val_mae: 0.4076 - val_rmse: 0.4688 - val_smape: 0.8318

Epoch 66/128

287/287 - 5s - 17ms/step - ia: 0.7340 - loss: 0.2554 - mae: 0.3957 - rmse: 0.5041 - smape: 0.8006 - val_ia: 0.7078 - val_loss: 0.2413 - val_mae: 0.4128 - val_rmse: 0.4752 - val_smape: 0.8390

Epoch 67/128

287/287 - 5s - 17ms/step - ia: 0.7336 - loss: 0.2567 - mae: 0.3964 - rmse: 0.5056 - smape: 0.8004 - val_ia: 0.7102 - val_loss: 0.2372 - val_mae: 0.4093 - val_rmse: 0.4708 - val_smape: 0.8348

Epoch 68/128

287/287 - 5s - 18ms/step - ia: 0.7335 - loss: 0.2568 - mae: 0.3965 - rmse: 0.5055 - smape: 0.8046 - val_ia: 0.7120 - val_loss: 0.2384 - val_mae: 0.4104 - val_rmse: 0.4716 - val_smape: 0.8314

Epoch 69/128

287/287 - 11s - 37ms/step - ia: 0.7356 - loss: 0.2543 - mae: 0.3940 - rmse: 0.5030 - smape: 0.7980 - val_ia: 0.7153 - val_loss: 0.2292 - val_mae: 0.4024 - val_rmse: 0.4624 - val_smape: 0.8250

Epoch 70/128

287/287 - 5s - 18ms/step - ia: 0.7349 - loss: 0.2540 - mae: 0.3947 - rmse: 0.5029 - smape: 0.8010 - val_ia: 0.7115 - val_loss: 0.2400 - val_mae: 0.4114 - val_rmse: 0.4727 - val_smape: 0.8327

Epoch 71/128

287/287 - 5s - 18ms/step - ia: 0.7372 - loss: 0.2513 - mae: 0.3922 - rmse: 0.5002 - smape: 0.7958 - val_ia: 0.7179 - val_loss: 0.2271 - val_mae: 0.4000 - val_rmse: 0.4593 - val_smape: 0.8205

Epoch 72/128

287/287 - 10s - 36ms/step - ia: 0.7357 - loss: 0.2532 - mae: 0.3935 - rmse: 0.5020 - smape: 0.7993 - val_ia: 0.7142 - val_loss: 0.2358 - val_mae: 0.4076 - val_rmse: 0.4680 - val_smape: 0.8269

Epoch 73/128

287/287 - 10s - 35ms/step - ia: 0.7373 - loss: 0.2504 - mae: 0.3918 - rmse: 0.4994 - smape: 0.7949 - val_ia: 0.7167 - val_loss: 0.2309 - val_mae: 0.4032 - val_rmse: 0.4623 - val_smape: 0.8228

Epoch 74/128

287/287 - 5s - 18ms/step - ia: 0.7373 - loss: 0.2499 - mae: 0.3917 - rmse: 0.4989 - smape: 0.7960 - val_ia: 0.7172 - val_loss: 0.2304 - val_mae: 0.4029 - val_rmse: 0.4622 - val_smape: 0.8225

Epoch 75/128

287/287 - 5s - 17ms/step - ia: 0.7385 - loss: 0.2489 - mae: 0.3901 - rmse: 0.4976 - smape: 0.7915 - val_ia: 0.7164 - val_loss: 0.2319 - val_mae: 0.4040 - val_rmse: 0.4640 - val_smape: 0.8238

Epoch 76/128

287/287 - 6s - 19ms/step - ia: 0.7398 - loss: 0.2464 - mae: 0.3886 - rmse: 0.4951 - smape: 0.7931 - val_ia: 0.7197 - val_loss: 0.2267 - val_mae: 0.3997 - val_rmse: 0.4591 - val_smape: 0.8183

Epoch 77/128

287/287 - 5s - 19ms/step - ia: 0.7386 - loss: 0.2486 - mae: 0.3899 - rmse: 0.4976 - smape: 0.7926 - val_ia: 0.7163 - val_loss: 0.2327 - val_mae: 0.4047 - val_rmse: 0.4636 - val_smape: 0.8222

Epoch 78/128

287/287 - 5s - 17ms/step - ia: 0.7384 - loss: 0.2484 - mae: 0.3901 - rmse: 0.4971 - smape: 0.7925 - val_ia: 0.7177 - val_loss: 0.2314 - val_mae: 0.4031 - val_rmse: 0.4629 - val_smape: 0.8200

Epoch 79/128

287/287 - 5s - 18ms/step - ia: 0.7383 - loss: 0.2481 - mae: 0.3899 - rmse: 0.4969 - smape: 0.7926 - val_ia: 0.7148 - val_loss: 0.2378 - val_mae: 0.4083 - val_rmse: 0.4696 - val_smape: 0.8246

Epoch 80/128

287/287 - 5s - 17ms/step - ia: 0.7397 - loss: 0.2474 - mae: 0.3889 - rmse: 0.4963 - smape: 0.7883 - val_ia: 0.7173 - val_loss: 0.2312 - val_mae: 0.4028 - val_rmse: 0.4629 - val_smape: 0.8207

Epoch 81/128

287/287 - 5s - 17ms/step - ia: 0.7411 - loss: 0.2445 - mae: 0.3870 - rmse: 0.4931 - smape: 0.7883 - val_ia: 0.7202 - val_loss: 0.2287 - val_mae: 0.4006 - val_rmse: 0.4602 - val_smape: 0.8155

Epoch 82/128

287/287 - 5s - 18ms/step - ia: 0.7404 - loss: 0.2452 - mae: 0.3878 - rmse: 0.4940 - smape: 0.7907 - val_ia: 0.7172 - val_loss: 0.2332 - val_mae: 0.4037 - val_rmse: 0.4638 - val_smape: 0.8182

Epoch 83/128

287/287 - 5s - 19ms/step - ia: 0.7405 - loss: 0.2447 - mae: 0.3870 - rmse: 0.4933 - smape: 0.7883 - val_ia: 0.7144 - val_loss: 0.2405 - val_mae: 0.4099 - val_rmse: 0.4722 - val_smape: 0.8229

Epoch 84/128

287/287 - 10s - 36ms/step - ia: 0.7411 - loss: 0.2446 - mae: 0.3872 - rmse: 0.4935 - smape: 0.7867 - val_ia: 0.7205 - val_loss: 0.2304 - val_mae: 0.4014 - val_rmse: 0.4611 - val_smape: 0.8143

Epoch 85/128

287/287 - 5s - 19ms/step - ia: 0.7403 - loss: 0.2455 - mae: 0.3871 - rmse: 0.4944 - smape: 0.7877 - val_ia: 0.7228 - val_loss: 0.2228 - val_mae: 0.3957 - val_rmse: 0.4549 - val_smape: 0.8102

Epoch 86/128

287/287 - 5s - 19ms/step - ia: 0.7404 - loss: 0.2447 - mae: 0.3870 - rmse: 0.4934 - smape: 0.7861 - val_ia: 0.7251 - val_loss: 0.2199 - val_mae: 0.3923 - val_rmse: 0.4510 - val_smape: 0.8046

Epoch 87/128

287/287 - 5s - 18ms/step - ia: 0.7410 - loss: 0.2445 - mae: 0.3866 - rmse: 0.4933 - smape: 0.7854 - val_ia: 0.7253 - val_loss: 0.2187 - val_mae: 0.3917 - val_rmse: 0.4513 - val_smape: 0.8046

Epoch 88/128

287/287 - 5s - 18ms/step - ia: 0.7431 - loss: 0.2414 - mae: 0.3839 - rmse: 0.4901 - smape: 0.7834 - val_ia: 0.7191 - val_loss: 0.2356 - val_mae: 0.4051 - val_rmse: 0.4658 - val_smape: 0.8136

Epoch 89/128

287/287 - 5s - 17ms/step - ia: 0.7425 - loss: 0.2414 - mae: 0.3849 - rmse: 0.4902 - smape: 0.7866 - val_ia: 0.7224 - val_loss: 0.2251 - val_mae: 0.3971 - val_rmse: 0.4563 - val_smape: 0.8083

Epoch 90/128

287/287 - 5s - 18ms/step - ia: 0.7436 - loss: 0.2404 - mae: 0.3835 - rmse: 0.4889 - smape: 0.7823 - val_ia: 0.7187 - val_loss: 0.2333 - val_mae: 0.4035 - val_rmse: 0.4638 - val_smape: 0.8142

Epoch 91/128

287/287 - 6s - 19ms/step - ia: 0.7430 - loss: 0.2422 - mae: 0.3842 - rmse: 0.4907 - smape: 0.7827 - val_ia: 0.7180 - val_loss: 0.2330 - val_mae: 0.4030 - val_rmse: 0.4641 - val_smape: 0.8158

Epoch 92/128

287/287 - 10s - 33ms/step - ia: 0.7437 - loss: 0.2403 - mae: 0.3827 - rmse: 0.4892 - smape: 0.7811 - val_ia: 0.7246 - val_loss: 0.2255 - val_mae: 0.3968 - val_rmse: 0.4564 - val_smape: 0.8054

Epoch 93/128

287/287 - 5s - 18ms/step - ia: 0.7431 - loss: 0.2413 - mae: 0.3842 - rmse: 0.4900 - smape: 0.7848 - val_ia: 0.7173 - val_loss: 0.2380 - val_mae: 0.4067 - val_rmse: 0.4687 - val_smape: 0.8151

Epoch 94/128

287/287 - 5s - 17ms/step - ia: 0.7435 - loss: 0.2402 - mae: 0.3836 - rmse: 0.4891 - smape: 0.7836 - val_ia: 0.7203 - val_loss: 0.2308 - val_mae: 0.4015 - val_rmse: 0.4620 - val_smape: 0.8113

Epoch 95/128

287/287 - 5s - 17ms/step - ia: 0.7441 - loss: 0.2398 - mae: 0.3824 - rmse: 0.4884 - smape: 0.7827 - val_ia: 0.7207 - val_loss: 0.2317 - val_mae: 0.4025 - val_rmse: 0.4640 - val_smape: 0.8111

Epoch 96/128

287/287 - 5s - 19ms/step - ia: 0.7451 - loss: 0.2382 - mae: 0.3816 - rmse: 0.4867 - smape: 0.7765 - val_ia: 0.7181 - val_loss: 0.2389 - val_mae: 0.4078 - val_rmse: 0.4699 - val_smape: 0.8143

Epoch 97/128

287/287 - 5s - 18ms/step - ia: 0.7439 - loss: 0.2413 - mae: 0.3828 - rmse: 0.4902 - smape: 0.7786 - val_ia: 0.7227 - val_loss: 0.2313 - val_mae: 0.4011 - val_rmse: 0.4619 - val_smape: 0.8072

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 70s - 30ms/step - ia: 0.7611 - loss: 0.2180 - mae: 0.3511 - rmse: 0.4440 - smape: 0.7154 - val_ia: 0.3172 - val_loss: 0.2436 - val_mae: 0.3734 - val_rmse: 0.4146 - val_smape: 0.7522

Epoch 2/128

2292/2292 - 83s - 36ms/step - ia: 0.8450 - loss: 0.1006 - mae: 0.2339 - rmse: 0.3072 - smape: 0.5603 - val_ia: 0.3842 - val_loss: 0.1751 - val_mae: 0.3104 - val_rmse: 0.3465 - val_smape: 0.6731

Epoch 3/128

2292/2292 - 81s - 36ms/step - ia: 0.8605 - loss: 0.0834 - mae: 0.2120 - rmse: 0.2792 - smape: 0.5186 - val_ia: 0.3805 - val_loss: 0.1990 - val_mae: 0.3296 - val_rmse: 0.3637 - val_smape: 0.6914

Epoch 4/128

2292/2292 - 48s - 21ms/step - ia: 0.8721 - loss: 0.0706 - mae: 0.1947 - rmse: 0.2564 - smape: 0.4866 - val_ia: 0.3990 - val_loss: 0.1668 - val_mae: 0.2986 - val_rmse: 0.3319 - val_smape: 0.6558

Epoch 5/128

2292/2292 - 53s - 23ms/step - ia: 0.8771 - loss: 0.0662 - mae: 0.1878 - rmse: 0.2480 - smape: 0.4715 - val_ia: 0.3592 - val_loss: 0.2030 - val_mae: 0.3375 - val_rmse: 0.3813 - val_smape: 0.6950

Epoch 6/128

2292/2292 - 56s - 25ms/step - ia: 0.8831 - loss: 0.0604 - mae: 0.1792 - rmse: 0.2370 - smape: 0.4576 - val_ia: 0.3690 - val_loss: 0.2061 - val_mae: 0.3255 - val_rmse: 0.3654 - val_smape: 0.6878

Epoch 7/128

2292/2292 - 57s - 25ms/step - ia: 0.8880 - loss: 0.0555 - mae: 0.1713 - rmse: 0.2270 - smape: 0.4426 - val_ia: 0.3802 - val_loss: 0.1542 - val_mae: 0.3014 - val_rmse: 0.3338 - val_smape: 0.6609

Epoch 8/128

2292/2292 - 46s - 20ms/step - ia: 0.8899 - loss: 0.0542 - mae: 0.1684 - rmse: 0.2239 - smape: 0.4390 - val_ia: 0.3429 - val_loss: 0.2395 - val_mae: 0.3584 - val_rmse: 0.4060 - val_smape: 0.7428

Epoch 9/128

2292/2292 - 99s - 43ms/step - ia: 0.8944 - loss: 0.0505 - mae: 0.1619 - rmse: 0.2163 - smape: 0.4264 - val_ia: 0.3768 - val_loss: 0.1840 - val_mae: 0.3296 - val_rmse: 0.3582 - val_smape: 0.6872

Epoch 10/128

2292/2292 - 77s - 33ms/step - ia: 0.8976 - loss: 0.0474 - mae: 0.1568 - rmse: 0.2092 - smape: 0.4171 - val_ia: 0.3828 - val_loss: 0.2026 - val_mae: 0.3392 - val_rmse: 0.3698 - val_smape: 0.7007

Epoch 11/128

2292/2292 - 55s - 24ms/step - ia: 0.9007 - loss: 0.0450 - mae: 0.1520 - rmse: 0.2035 - smape: 0.4066 - val_ia: 0.3740 - val_loss: 0.2101 - val_mae: 0.3392 - val_rmse: 0.3754 - val_smape: 0.7095

Epoch 12/128

2292/2292 - 77s - 34ms/step - ia: 0.9032 - loss: 0.0433 - mae: 0.1489 - rmse: 0.2001 - smape: 0.4037 - val_ia: 0.3752 - val_loss: 0.1892 - val_mae: 0.3244 - val_rmse: 0.3635 - val_smape: 0.6701

Epoch 13/128

2292/2292 - 50s - 22ms/step - ia: 0.9066 - loss: 0.0401 - mae: 0.1432 - rmse: 0.1919 - smape: 0.3940 - val_ia: 0.3623 - val_loss: 0.1976 - val_mae: 0.3363 - val_rmse: 0.3758 - val_smape: 0.7138

Epoch 14/128

2292/2292 - 58s - 25ms/step - ia: 0.9096 - loss: 0.0383 - mae: 0.1389 - rmse: 0.1873 - smape: 0.3841 - val_ia: 0.3506 - val_loss: 0.2742 - val_mae: 0.3864 - val_rmse: 0.4290 - val_smape: 0.7761

Epoch 15/128

2292/2292 - 59s - 26ms/step - ia: 0.9104 - loss: 0.0380 - mae: 0.1381 - rmse: 0.1861 - smape: 0.3800 - val_ia: 0.3514 - val_loss: 0.2472 - val_mae: 0.3682 - val_rmse: 0.4097 - val_smape: 0.7385

Epoch 16/128

2292/2292 - 79s - 35ms/step - ia: 0.9151 - loss: 0.0342 - mae: 0.1310 - rmse: 0.1765 - smape: 0.3693 - val_ia: 0.3538 - val_loss: 0.2653 - val_mae: 0.3721 - val_rmse: 0.4192 - val_smape: 0.7414

Epoch 17/128

2292/2292 - 83s - 36ms/step - ia: 0.9168 - loss: 0.0327 - mae: 0.1281 - rmse: 0.1726 - smape: 0.3632 - val_ia: 0.3481 - val_loss: 0.2489 - val_mae: 0.3665 - val_rmse: 0.4095 - val_smape: 0.7520

Epoch 18/128

2292/2292 - 53s - 23ms/step - ia: 0.9190 - loss: 0.0315 - mae: 0.1256 - rmse: 0.1694 - smape: 0.3569 - val_ia: 0.3362 - val_loss: 0.3115 - val_mae: 0.4039 - val_rmse: 0.4561 - val_smape: 0.8176

Epoch 19/128

2292/2292 - 49s - 21ms/step - ia: 0.9214 - loss: 0.0291 - mae: 0.1208 - rmse: 0.1627 - smape: 0.3467 - val_ia: 0.3687 - val_loss: 0.2034 - val_mae: 0.3383 - val_rmse: 0.3809 - val_smape: 0.7124

Epoch 20/128

2292/2292 - 51s - 22ms/step - ia: 0.9235 - loss: 0.0280 - mae: 0.1180 - rmse: 0.1596 - smape: 0.3394 - val_ia: 0.3645 - val_loss: 0.2319 - val_mae: 0.3560 - val_rmse: 0.3950 - val_smape: 0.7350

Epoch 21/128

2292/2292 - 53s - 23ms/step - ia: 0.9253 - loss: 0.0265 - mae: 0.1153 - rmse: 0.1555 - smape: 0.3337 - val_ia: 0.3617 - val_loss: 0.2936 - val_mae: 0.3877 - val_rmse: 0.4347 - val_smape: 0.7501

Epoch 22/128

2292/2292 - 50s - 22ms/step - ia: 0.9271 - loss: 0.0251 - mae: 0.1123 - rmse: 0.1511 - smape: 0.3260 - val_ia: 0.3585 - val_loss: 0.2426 - val_mae: 0.3606 - val_rmse: 0.4061 - val_smape: 0.7444

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:37 1s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 50/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
105/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
133/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
144/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step

 17%|█▋        | 2/12 [33:25<2:58:33, 1071.33s/trial, best loss: 0.212949463855241]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 75s - 16ms/step - ia: 0.2138 - loss: 1.1156 - mae: 0.8703 - rmse: 1.0341 - smape: 1.6879 - val_ia: 0.1369 - val_loss: 0.9777 - val_mae: 0.8034 - val_rmse: 0.8208 - val_smape: 1.5623

Epoch 2/128

4584/4584 - 51s - 11ms/step - ia: 0.2117 - loss: 1.0670 - mae: 0.8540 - rmse: 1.0118 - smape: 1.7111 - val_ia: 0.1376 - val_loss: 0.9208 - val_mae: 0.7817 - val_rmse: 0.7989 - val_smape: 1.5659

Epoch 3/128

4584/4584 - 74s - 16ms/step - ia: 0.2160 - loss: 1.0319 - mae: 0.8422 - rmse: 0.9952 - smape: 1.7171 - val_ia: 0.1395 - val_loss: 0.8767 - val_mae: 0.7641 - val_rmse: 0.7813 - val_smape: 1.5371

Epoch 4/128

4584/4584 - 44s - 10ms/step - ia: 0.2229 - loss: 1.0025 - mae: 0.8327 - rmse: 0.9810 - smape: 1.7098 - val_ia: 0.1426 - val_loss: 0.8410 - val_mae: 0.7492 - val_rmse: 0.7664 - val_smape: 1.4917

Epoch 5/128

4584/4584 - 44s - 10ms/step - ia: 0.2281 - loss: 0.9783 - mae: 0.8229 - rmse: 0.9690 - smape: 1.6914 - val_ia: 0.1446 - val_loss: 0.8105 - val_mae: 0.7361 - val_rmse: 0.7533 - val_smape: 1.4577

Epoch 6/128

4584/4584 - 89s - 19ms/step - ia: 0.2353 - loss: 0.9601 - mae: 0.8161 - rmse: 0.9601 - smape: 1.6757 - val_ia: 0.1460 - val_loss: 0.7874 - val_mae: 0.7264 - val_rmse: 0.7436 - val_smape: 1.4413

Epoch 7/128

4584/4584 - 39s - 9ms/step - ia: 0.2398 - loss: 0.9444 - mae: 0.8099 - rmse: 0.9518 - smape: 1.6614 - val_ia: 0.1470 - val_loss: 0.7697 - val_mae: 0.7191 - val_rmse: 0.7363 - val_smape: 1.4298

Epoch 8/128

4584/4584 - 42s - 9ms/step - ia: 0.2444 - loss: 0.9318 - mae: 0.8049 - rmse: 0.9455 - smape: 1.6448 - val_ia: 0.1479 - val_loss: 0.7544 - val_mae: 0.7127 - val_rmse: 0.7300 - val_smape: 1.4194

Epoch 9/128

4584/4584 - 45s - 10ms/step - ia: 0.2477 - loss: 0.9202 - mae: 0.8004 - rmse: 0.9397 - smape: 1.6255 - val_ia: 0.1487 - val_loss: 0.7400 - val_mae: 0.7064 - val_rmse: 0.7238 - val_smape: 1.4059

Epoch 10/128

4584/4584 - 79s - 17ms/step - ia: 0.2558 - loss: 0.9071 - mae: 0.7957 - rmse: 0.9337 - smape: 1.6032 - val_ia: 0.1495 - val_loss: 0.7258 - val_mae: 0.7001 - val_rmse: 0.7176 - val_smape: 1.3923

Epoch 11/128

4584/4584 - 81s - 18ms/step - ia: 0.2648 - loss: 0.8929 - mae: 0.7899 - rmse: 0.9263 - smape: 1.5812 - val_ia: 0.1506 - val_loss: 0.7115 - val_mae: 0.6935 - val_rmse: 0.7111 - val_smape: 1.3774

Epoch 12/128

4584/4584 - 44s - 10ms/step - ia: 0.2691 - loss: 0.8799 - mae: 0.7852 - rmse: 0.9200 - smape: 1.5584 - val_ia: 0.1516 - val_loss: 0.6968 - val_mae: 0.6867 - val_rmse: 0.7043 - val_smape: 1.3615

Epoch 13/128

4584/4584 - 43s - 9ms/step - ia: 0.2786 - loss: 0.8656 - mae: 0.7788 - rmse: 0.9121 - smape: 1.5344 - val_ia: 0.1522 - val_loss: 0.6819 - val_mae: 0.6795 - val_rmse: 0.6973 - val_smape: 1.3431

Epoch 14/128

4584/4584 - 44s - 10ms/step - ia: 0.2884 - loss: 0.8490 - mae: 0.7719 - rmse: 0.9038 - smape: 1.5098 - val_ia: 0.1528 - val_loss: 0.6669 - val_mae: 0.6721 - val_rmse: 0.6900 - val_smape: 1.3237

Epoch 15/128

4584/4584 - 43s - 9ms/step - ia: 0.2964 - loss: 0.8363 - mae: 0.7667 - rmse: 0.8969 - smape: 1.4880 - val_ia: 0.1535 - val_loss: 0.6517 - val_mae: 0.6643 - val_rmse: 0.6823 - val_smape: 1.3037

Epoch 16/128

4584/4584 - 44s - 10ms/step - ia: 0.3080 - loss: 0.8207 - mae: 0.7590 - rmse: 0.8887 - smape: 1.4636 - val_ia: 0.1550 - val_loss: 0.6361 - val_mae: 0.6561 - val_rmse: 0.6742 - val_smape: 1.2830

Epoch 17/128

4584/4584 - 44s - 10ms/step - ia: 0.3159 - loss: 0.8071 - mae: 0.7527 - rmse: 0.8807 - smape: 1.4402 - val_ia: 0.1563 - val_loss: 0.6203 - val_mae: 0.6475 - val_rmse: 0.6656 - val_smape: 1.2597

Epoch 18/128

4584/4584 - 45s - 10ms/step - ia: 0.3261 - loss: 0.7891 - mae: 0.7448 - rmse: 0.8698 - smape: 1.4177 - val_ia: 0.1572 - val_loss: 0.6036 - val_mae: 0.6383 - val_rmse: 0.6565 - val_smape: 1.2357

Epoch 19/128

4584/4584 - 44s - 10ms/step - ia: 0.3379 - loss: 0.7724 - mae: 0.7367 - rmse: 0.8616 - smape: 1.3938 - val_ia: 0.1589 - val_loss: 0.5863 - val_mae: 0.6283 - val_rmse: 0.6467 - val_smape: 1.2096

Epoch 20/128

4584/4584 - 43s - 9ms/step - ia: 0.3503 - loss: 0.7537 - mae: 0.7277 - rmse: 0.8513 - smape: 1.3689 - val_ia: 0.1608 - val_loss: 0.5676 - val_mae: 0.6172 - val_rmse: 0.6356 - val_smape: 1.1817

Epoch 21/128

4584/4584 - 82s - 18ms/step - ia: 0.3602 - loss: 0.7380 - mae: 0.7200 - rmse: 0.8423 - smape: 1.3470 - val_ia: 0.1624 - val_loss: 0.5488 - val_mae: 0.6058 - val_rmse: 0.6243 - val_smape: 1.1544

Epoch 22/128

4584/4584 - 82s - 18ms/step - ia: 0.3752 - loss: 0.7170 - mae: 0.7094 - rmse: 0.8294 - smape: 1.3208 - val_ia: 0.1636 - val_loss: 0.5303 - val_mae: 0.5946 - val_rmse: 0.6132 - val_smape: 1.1281

Epoch 23/128

4584/4584 - 44s - 10ms/step - ia: 0.3859 - loss: 0.6989 - mae: 0.7004 - rmse: 0.8194 - smape: 1.2978 - val_ia: 0.1652 - val_loss: 0.5116 - val_mae: 0.5831 - val_rmse: 0.6018 - val_smape: 1.1031

Epoch 24/128

4584/4584 - 44s - 10ms/step - ia: 0.3986 - loss: 0.6798 - mae: 0.6900 - rmse: 0.8075 - smape: 1.2740 - val_ia: 0.1678 - val_loss: 0.4929 - val_mae: 0.5714 - val_rmse: 0.5903 - val_smape: 1.0783

Epoch 25/128

4584/4584 - 81s - 18ms/step - ia: 0.4130 - loss: 0.6603 - mae: 0.6799 - rmse: 0.7964 - smape: 1.2474 - val_ia: 0.1709 - val_loss: 0.4741 - val_mae: 0.5593 - val_rmse: 0.5784 - val_smape: 1.0529

Epoch 26/128

4584/4584 - 43s - 9ms/step - ia: 0.4247 - loss: 0.6395 - mae: 0.6686 - rmse: 0.7833 - smape: 1.2251 - val_ia: 0.1747 - val_loss: 0.4559 - val_mae: 0.5471 - val_rmse: 0.5664 - val_smape: 1.0264

Epoch 27/128

4584/4584 - 44s - 10ms/step - ia: 0.4386 - loss: 0.6228 - mae: 0.6592 - rmse: 0.7730 - smape: 1.2004 - val_ia: 0.1779 - val_loss: 0.4380 - val_mae: 0.5351 - val_rmse: 0.5546 - val_smape: 1.0017

Epoch 28/128

4584/4584 - 83s - 18ms/step - ia: 0.4537 - loss: 0.6008 - mae: 0.6477 - rmse: 0.7592 - smape: 1.1768 - val_ia: 0.1823 - val_loss: 0.4205 - val_mae: 0.5231 - val_rmse: 0.5430 - val_smape: 0.9781

Epoch 29/128

4584/4584 - 44s - 10ms/step - ia: 0.4661 - loss: 0.5830 - mae: 0.6381 - rmse: 0.7480 - smape: 1.1548 - val_ia: 0.1849 - val_loss: 0.4038 - val_mae: 0.5116 - val_rmse: 0.5318 - val_smape: 0.9555

Epoch 30/128

4584/4584 - 81s - 18ms/step - ia: 0.4795 - loss: 0.5626 - mae: 0.6251 - rmse: 0.7347 - smape: 1.1268 - val_ia: 0.1872 - val_loss: 0.3878 - val_mae: 0.5003 - val_rmse: 0.5208 - val_smape: 0.9342

Epoch 31/128

4584/4584 - 83s - 18ms/step - ia: 0.4933 - loss: 0.5460 - mae: 0.6154 - rmse: 0.7235 - smape: 1.1037 - val_ia: 0.1911 - val_loss: 0.3724 - val_mae: 0.4894 - val_rmse: 0.5103 - val_smape: 0.9142

Epoch 32/128

4584/4584 - 44s - 10ms/step - ia: 0.5066 - loss: 0.5285 - mae: 0.6050 - rmse: 0.7118 - smape: 1.0817 - val_ia: 0.1948 - val_loss: 0.3583 - val_mae: 0.4791 - val_rmse: 0.5004 - val_smape: 0.8952

Epoch 33/128

4584/4584 - 81s - 18ms/step - ia: 0.5169 - loss: 0.5144 - mae: 0.5961 - rmse: 0.7021 - smape: 1.0606 - val_ia: 0.1978 - val_loss: 0.3449 - val_mae: 0.4693 - val_rmse: 0.4909 - val_smape: 0.8775

Epoch 34/128

4584/4584 - 43s - 9ms/step - ia: 0.5277 - loss: 0.5009 - mae: 0.5882 - rmse: 0.6920 - smape: 1.0454 - val_ia: 0.2006 - val_loss: 0.3321 - val_mae: 0.4599 - val_rmse: 0.4818 - val_smape: 0.8614

Epoch 35/128

4584/4584 - 42s - 9ms/step - ia: 0.5380 - loss: 0.4852 - mae: 0.5789 - rmse: 0.6817 - smape: 1.0296 - val_ia: 0.2021 - val_loss: 0.3209 - val_mae: 0.4516 - val_rmse: 0.4737 - val_smape: 0.8468

Epoch 36/128

4584/4584 - 43s - 9ms/step - ia: 0.5488 - loss: 0.4762 - mae: 0.5722 - rmse: 0.6751 - smape: 1.0119 - val_ia: 0.2035 - val_loss: 0.3108 - val_mae: 0.4442 - val_rmse: 0.4663 - val_smape: 0.8339

Epoch 37/128

4584/4584 - 44s - 10ms/step - ia: 0.5584 - loss: 0.4654 - mae: 0.5642 - rmse: 0.6672 - smape: 0.9964 - val_ia: 0.2056 - val_loss: 0.3014 - val_mae: 0.4372 - val_rmse: 0.4594 - val_smape: 0.8222

Epoch 38/128

4584/4584 - 43s - 9ms/step - ia: 0.5692 - loss: 0.4515 - mae: 0.5548 - rmse: 0.6563 - smape: 0.9760 - val_ia: 0.2076 - val_loss: 0.2931 - val_mae: 0.4311 - val_rmse: 0.4533 - val_smape: 0.8121

Epoch 39/128

4584/4584 - 44s - 10ms/step - ia: 0.5756 - loss: 0.4434 - mae: 0.5507 - rmse: 0.6507 - smape: 0.9715 - val_ia: 0.2094 - val_loss: 0.2858 - val_mae: 0.4257 - val_rmse: 0.4479 - val_smape: 0.8032

Epoch 40/128

4584/4584 - 79s - 17ms/step - ia: 0.5831 - loss: 0.4358 - mae: 0.5442 - rmse: 0.6447 - smape: 0.9577 - val_ia: 0.2105 - val_loss: 0.2803 - val_mae: 0.4216 - val_rmse: 0.4438 - val_smape: 0.7951

Epoch 41/128

4584/4584 - 42s - 9ms/step - ia: 0.5884 - loss: 0.4310 - mae: 0.5402 - rmse: 0.6408 - smape: 0.9509 - val_ia: 0.2121 - val_loss: 0.2752 - val_mae: 0.4177 - val_rmse: 0.4399 - val_smape: 0.7888

Epoch 42/128

4584/4584 - 43s - 9ms/step - ia: 0.5929 - loss: 0.4269 - mae: 0.5378 - rmse: 0.6381 - smape: 0.9454 - val_ia: 0.2134 - val_loss: 0.2712 - val_mae: 0.4146 - val_rmse: 0.4368 - val_smape: 0.7834

Epoch 43/128

4584/4584 - 44s - 10ms/step - ia: 0.5974 - loss: 0.4236 - mae: 0.5348 - rmse: 0.6349 - smape: 0.9380 - val_ia: 0.2148 - val_loss: 0.2676 - val_mae: 0.4118 - val_rmse: 0.4338 - val_smape: 0.7781

Epoch 44/128

4584/4584 - 79s - 17ms/step - ia: 0.6013 - loss: 0.4180 - mae: 0.5308 - rmse: 0.6307 - smape: 0.9313 - val_ia: 0.2161 - val_loss: 0.2644 - val_mae: 0.4093 - val_rmse: 0.4312 - val_smape: 0.7729

Epoch 45/128

4584/4584 - 43s - 9ms/step - ia: 0.6048 - loss: 0.4126 - mae: 0.5275 - rmse: 0.6264 - smape: 0.9240 - val_ia: 0.2171 - val_loss: 0.2615 - val_mae: 0.4069 - val_rmse: 0.4287 - val_smape: 0.7680

Epoch 46/128

4584/4584 - 81s - 18ms/step - ia: 0.6091 - loss: 0.4101 - mae: 0.5246 - rmse: 0.6243 - smape: 0.9198 - val_ia: 0.2180 - val_loss: 0.2596 - val_mae: 0.4053 - val_rmse: 0.4270 - val_smape: 0.7642

Epoch 47/128

4584/4584 - 42s - 9ms/step - ia: 0.6103 - loss: 0.4047 - mae: 0.5211 - rmse: 0.6210 - smape: 0.9131 - val_ia: 0.2191 - val_loss: 0.2579 - val_mae: 0.4036 - val_rmse: 0.4252 - val_smape: 0.7608

Epoch 48/128

4584/4584 - 44s - 9ms/step - ia: 0.6137 - loss: 0.4034 - mae: 0.5199 - rmse: 0.6190 - smape: 0.9086 - val_ia: 0.2203 - val_loss: 0.2566 - val_mae: 0.4023 - val_rmse: 0.4238 - val_smape: 0.7577

Epoch 49/128

4584/4584 - 81s - 18ms/step - ia: 0.6167 - loss: 0.4007 - mae: 0.5173 - rmse: 0.6176 - smape: 0.9069 - val_ia: 0.2218 - val_loss: 0.2557 - val_mae: 0.4011 - val_rmse: 0.4225 - val_smape: 0.7560

Epoch 50/128

4584/4584 - 42s - 9ms/step - ia: 0.6183 - loss: 0.3965 - mae: 0.5148 - rmse: 0.6129 - smape: 0.9024 - val_ia: 0.2225 - val_loss: 0.2550 - val_mae: 0.4003 - val_rmse: 0.4216 - val_smape: 0.7540

Epoch 51/128

4584/4584 - 82s - 18ms/step - ia: 0.6203 - loss: 0.3958 - mae: 0.5136 - rmse: 0.6129 - smape: 0.9000 - val_ia: 0.2233 - val_loss: 0.2547 - val_mae: 0.3997 - val_rmse: 0.4210 - val_smape: 0.7534

Epoch 52/128

4584/4584 - 81s - 18ms/step - ia: 0.6243 - loss: 0.3888 - mae: 0.5083 - rmse: 0.6068 - smape: 0.8911 - val_ia: 0.2240 - val_loss: 0.2539 - val_mae: 0.3987 - val_rmse: 0.4199 - val_smape: 0.7520

Epoch 53/128

4584/4584 - 83s - 18ms/step - ia: 0.6259 - loss: 0.3887 - mae: 0.5084 - rmse: 0.6077 - smape: 0.8902 - val_ia: 0.2247 - val_loss: 0.2541 - val_mae: 0.3984 - val_rmse: 0.4196 - val_smape: 0.7519

Epoch 54/128

4584/4584 - 47s - 10ms/step - ia: 0.6278 - loss: 0.3841 - mae: 0.5054 - rmse: 0.6036 - smape: 0.8868 - val_ia: 0.2252 - val_loss: 0.2539 - val_mae: 0.3979 - val_rmse: 0.4190 - val_smape: 0.7513

Epoch 55/128

4584/4584 - 77s - 17ms/step - ia: 0.6291 - loss: 0.3816 - mae: 0.5035 - rmse: 0.6015 - smape: 0.8850 - val_ia: 0.2258 - val_loss: 0.2536 - val_mae: 0.3974 - val_rmse: 0.4184 - val_smape: 0.7510

Epoch 56/128

4584/4584 - 43s - 9ms/step - ia: 0.6287 - loss: 0.3832 - mae: 0.5039 - rmse: 0.6024 - smape: 0.8848 - val_ia: 0.2264 - val_loss: 0.2541 - val_mae: 0.3975 - val_rmse: 0.4184 - val_smape: 0.7519

Epoch 57/128

4584/4584 - 43s - 9ms/step - ia: 0.6328 - loss: 0.3760 - mae: 0.4994 - rmse: 0.5970 - smape: 0.8784 - val_ia: 0.2271 - val_loss: 0.2540 - val_mae: 0.3971 - val_rmse: 0.4180 - val_smape: 0.7519

Epoch 58/128

4584/4584 - 42s - 9ms/step - ia: 0.6338 - loss: 0.3752 - mae: 0.4990 - rmse: 0.5959 - smape: 0.8796 - val_ia: 0.2276 - val_loss: 0.2551 - val_mae: 0.3976 - val_rmse: 0.4184 - val_smape: 0.7532

Epoch 59/128

4584/4584 - 43s - 9ms/step - ia: 0.6349 - loss: 0.3729 - mae: 0.4978 - rmse: 0.5945 - smape: 0.8776 - val_ia: 0.2280 - val_loss: 0.2557 - val_mae: 0.3976 - val_rmse: 0.4184 - val_smape: 0.7545

Epoch 60/128

4584/4584 - 44s - 10ms/step - ia: 0.6375 - loss: 0.3685 - mae: 0.4932 - rmse: 0.5905 - smape: 0.8692 - val_ia: 0.2284 - val_loss: 0.2564 - val_mae: 0.3979 - val_rmse: 0.4186 - val_smape: 0.7562

Epoch 61/128

4584/4584 - 81s - 18ms/step - ia: 0.6383 - loss: 0.3678 - mae: 0.4920 - rmse: 0.5904 - smape: 0.8678 - val_ia: 0.2288 - val_loss: 0.2569 - val_mae: 0.3980 - val_rmse: 0.4187 - val_smape: 0.7579

Epoch 62/128

4584/4584 - 82s - 18ms/step - ia: 0.6396 - loss: 0.3632 - mae: 0.4894 - rmse: 0.5868 - smape: 0.8664 - val_ia: 0.2290 - val_loss: 0.2574 - val_mae: 0.3982 - val_rmse: 0.4188 - val_smape: 0.7598

Epoch 63/128

4584/4584 - 44s - 10ms/step - ia: 0.6410 - loss: 0.3642 - mae: 0.4900 - rmse: 0.5871 - smape: 0.8657 - val_ia: 0.2289 - val_loss: 0.2594 - val_mae: 0.3995 - val_rmse: 0.4200 - val_smape: 0.7642

Epoch 64/128

4584/4584 - 44s - 9ms/step - ia: 0.6426 - loss: 0.3609 - mae: 0.4869 - rmse: 0.5836 - smape: 0.8639 - val_ia: 0.2290 - val_loss: 0.2607 - val_mae: 0.4004 - val_rmse: 0.4208 - val_smape: 0.7671

Epoch 65/128

4584/4584 - 81s - 18ms/step - ia: 0.6442 - loss: 0.3598 - mae: 0.4865 - rmse: 0.5832 - smape: 0.8632 - val_ia: 0.2290 - val_loss: 0.2613 - val_mae: 0.4007 - val_rmse: 0.4211 - val_smape: 0.7695

Epoch 66/128

4584/4584 - 43s - 9ms/step - ia: 0.6464 - loss: 0.3574 - mae: 0.4837 - rmse: 0.5812 - smape: 0.8567 - val_ia: 0.2278 - val_loss: 0.2637 - val_mae: 0.4025 - val_rmse: 0.4227 - val_smape: 0.7747

Epoch 67/128

4584/4584 - 44s - 10ms/step - ia: 0.6484 - loss: 0.3524 - mae: 0.4804 - rmse: 0.5776 - smape: 0.8544 - val_ia: 0.2276 - val_loss: 0.2649 - val_mae: 0.4033 - val_rmse: 0.4235 - val_smape: 0.7784

Epoch 68/128

4584/4584 - 43s - 9ms/step - ia: 0.6508 - loss: 0.3521 - mae: 0.4793 - rmse: 0.5766 - smape: 0.8535 - val_ia: 0.2275 - val_loss: 0.2663 - val_mae: 0.4044 - val_rmse: 0.4245 - val_smape: 0.7822

Epoch 69/128

4584/4584 - 81s - 18ms/step - ia: 0.6530 - loss: 0.3485 - mae: 0.4769 - rmse: 0.5736 - smape: 0.8512 - val_ia: 0.2270 - val_loss: 0.2680 - val_mae: 0.4055 - val_rmse: 0.4255 - val_smape: 0.7862

Epoch 70/128

4584/4584 - 82s - 18ms/step - ia: 0.6532 - loss: 0.3452 - mae: 0.4745 - rmse: 0.5707 - smape: 0.8499 - val_ia: 0.2271 - val_loss: 0.2684 - val_mae: 0.4057 - val_rmse: 0.4257 - val_smape: 0.7883

Epoch 70: early stopping

Restoring model weights from the end of the best epoch: 55.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:35 962ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
124/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 25%|██▌       | 3/12 [1:39:50<6:00:15, 2401.78s/trial, best loss: 0.212949463855241]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 24s - 21ms/step - ia: 0.3323 - loss: 0.8202 - mae: 0.7526 - rmse: 0.8993 - smape: 1.4033 - val_ia: 0.2571 - val_loss: 0.9569 - val_mae: 0.8008 - val_rmse: 0.8696 - val_smape: 1.3493

Epoch 2/128

1146/1146 - 20s - 17ms/step - ia: 0.4983 - loss: 0.6189 - mae: 0.6449 - rmse: 0.7817 - smape: 1.1463 - val_ia: 0.2528 - val_loss: 1.4677 - val_mae: 1.0049 - val_rmse: 1.0791 - val_smape: 1.3814

Epoch 3/128

1146/1146 - 17s - 15ms/step - ia: 0.5506 - loss: 0.5668 - mae: 0.6095 - rmse: 0.7477 - smape: 1.0675 - val_ia: 0.2464 - val_loss: 1.6266 - val_mae: 1.0658 - val_rmse: 1.1400 - val_smape: 1.3966

Epoch 4/128

1146/1146 - 18s - 15ms/step - ia: 0.5751 - loss: 0.5283 - mae: 0.5867 - rmse: 0.7221 - smape: 1.0275 - val_ia: 0.2474 - val_loss: 1.5969 - val_mae: 1.0538 - val_rmse: 1.1269 - val_smape: 1.3812

Epoch 5/128

1146/1146 - 17s - 15ms/step - ia: 0.5968 - loss: 0.4969 - mae: 0.5647 - rmse: 0.6992 - smape: 0.9900 - val_ia: 0.2509 - val_loss: 1.5665 - val_mae: 1.0402 - val_rmse: 1.1136 - val_smape: 1.3560

Epoch 6/128

1146/1146 - 17s - 15ms/step - ia: 0.6139 - loss: 0.4693 - mae: 0.5468 - rmse: 0.6798 - smape: 0.9593 - val_ia: 0.2577 - val_loss: 1.4827 - val_mae: 1.0078 - val_rmse: 1.0813 - val_smape: 1.3185

Epoch 7/128

1146/1146 - 17s - 15ms/step - ia: 0.6298 - loss: 0.4437 - mae: 0.5314 - rmse: 0.6613 - smape: 0.9314 - val_ia: 0.2643 - val_loss: 1.3911 - val_mae: 0.9731 - val_rmse: 1.0460 - val_smape: 1.2854

Epoch 8/128

1146/1146 - 17s - 15ms/step - ia: 0.6386 - loss: 0.4270 - mae: 0.5221 - rmse: 0.6487 - smape: 0.9119 - val_ia: 0.2740 - val_loss: 1.2631 - val_mae: 0.9190 - val_rmse: 0.9928 - val_smape: 1.2410

Epoch 9/128

1146/1146 - 17s - 15ms/step - ia: 0.6496 - loss: 0.4097 - mae: 0.5106 - rmse: 0.6351 - smape: 0.8964 - val_ia: 0.2828 - val_loss: 1.1764 - val_mae: 0.8836 - val_rmse: 0.9563 - val_smape: 1.2190

Epoch 10/128

1146/1146 - 17s - 15ms/step - ia: 0.6573 - loss: 0.3976 - mae: 0.5017 - rmse: 0.6254 - smape: 0.8776 - val_ia: 0.2892 - val_loss: 1.0913 - val_mae: 0.8481 - val_rmse: 0.9210 - val_smape: 1.1983

Epoch 11/128

1146/1146 - 17s - 15ms/step - ia: 0.6627 - loss: 0.3859 - mae: 0.4961 - rmse: 0.6166 - smape: 0.8692 - val_ia: 0.2908 - val_loss: 1.0222 - val_mae: 0.8192 - val_rmse: 0.8919 - val_smape: 1.1848

Epoch 12/128

1146/1146 - 20s - 18ms/step - ia: 0.6683 - loss: 0.3766 - mae: 0.4896 - rmse: 0.6085 - smape: 0.8616 - val_ia: 0.2958 - val_loss: 0.9448 - val_mae: 0.7913 - val_rmse: 0.8605 - val_smape: 1.1765

Epoch 13/128

1146/1146 - 20s - 18ms/step - ia: 0.6740 - loss: 0.3667 - mae: 0.4836 - rmse: 0.6009 - smape: 0.8512 - val_ia: 0.2956 - val_loss: 0.9022 - val_mae: 0.7731 - val_rmse: 0.8423 - val_smape: 1.1676

Epoch 14/128

1146/1146 - 17s - 15ms/step - ia: 0.6762 - loss: 0.3610 - mae: 0.4808 - rmse: 0.5965 - smape: 0.8464 - val_ia: 0.2984 - val_loss: 0.8785 - val_mae: 0.7645 - val_rmse: 0.8325 - val_smape: 1.1617

Epoch 15/128

1146/1146 - 17s - 15ms/step - ia: 0.6808 - loss: 0.3542 - mae: 0.4751 - rmse: 0.5907 - smape: 0.8396 - val_ia: 0.2970 - val_loss: 0.8504 - val_mae: 0.7528 - val_rmse: 0.8209 - val_smape: 1.1569

Epoch 16/128

1146/1146 - 21s - 19ms/step - ia: 0.6844 - loss: 0.3463 - mae: 0.4704 - rmse: 0.5840 - smape: 0.8330 - val_ia: 0.2979 - val_loss: 0.8327 - val_mae: 0.7458 - val_rmse: 0.8131 - val_smape: 1.1538

Epoch 17/128

1146/1146 - 21s - 18ms/step - ia: 0.6887 - loss: 0.3402 - mae: 0.4664 - rmse: 0.5788 - smape: 0.8299 - val_ia: 0.2999 - val_loss: 0.7871 - val_mae: 0.7274 - val_rmse: 0.7937 - val_smape: 1.1479

Epoch 18/128

1146/1146 - 19s - 17ms/step - ia: 0.6897 - loss: 0.3366 - mae: 0.4642 - rmse: 0.5756 - smape: 0.8244 - val_ia: 0.2996 - val_loss: 0.7895 - val_mae: 0.7286 - val_rmse: 0.7950 - val_smape: 1.1468

Epoch 19/128

1146/1146 - 17s - 15ms/step - ia: 0.6932 - loss: 0.3321 - mae: 0.4608 - rmse: 0.5718 - smape: 0.8184 - val_ia: 0.3035 - val_loss: 0.7499 - val_mae: 0.7113 - val_rmse: 0.7770 - val_smape: 1.1427

Epoch 20/128

1146/1146 - 21s - 18ms/step - ia: 0.6926 - loss: 0.3313 - mae: 0.4605 - rmse: 0.5710 - smape: 0.8201 - val_ia: 0.3043 - val_loss: 0.7518 - val_mae: 0.7118 - val_rmse: 0.7775 - val_smape: 1.1400

Epoch 21/128

1146/1146 - 21s - 18ms/step - ia: 0.6957 - loss: 0.3269 - mae: 0.4569 - rmse: 0.5672 - smape: 0.8184 - val_ia: 0.3041 - val_loss: 0.7631 - val_mae: 0.7170 - val_rmse: 0.7825 - val_smape: 1.1422

Epoch 22/128

1146/1146 - 17s - 15ms/step - ia: 0.6988 - loss: 0.3218 - mae: 0.4530 - rmse: 0.5628 - smape: 0.8101 - val_ia: 0.3058 - val_loss: 0.7357 - val_mae: 0.7047 - val_rmse: 0.7703 - val_smape: 1.1390

Epoch 23/128

1146/1146 - 17s - 15ms/step - ia: 0.7003 - loss: 0.3189 - mae: 0.4497 - rmse: 0.5603 - smape: 0.8071 - val_ia: 0.3050 - val_loss: 0.7390 - val_mae: 0.7065 - val_rmse: 0.7722 - val_smape: 1.1386

Epoch 24/128

1146/1146 - 17s - 15ms/step - ia: 0.7014 - loss: 0.3170 - mae: 0.4489 - rmse: 0.5585 - smape: 0.8069 - val_ia: 0.3089 - val_loss: 0.7129 - val_mae: 0.6952 - val_rmse: 0.7596 - val_smape: 1.1337

Epoch 25/128

1146/1146 - 17s - 15ms/step - ia: 0.7016 - loss: 0.3162 - mae: 0.4484 - rmse: 0.5577 - smape: 0.8069 - val_ia: 0.3086 - val_loss: 0.7209 - val_mae: 0.6991 - val_rmse: 0.7631 - val_smape: 1.1337

Epoch 26/128

1146/1146 - 17s - 15ms/step - ia: 0.7050 - loss: 0.3125 - mae: 0.4449 - rmse: 0.5543 - smape: 0.8041 - val_ia: 0.3096 - val_loss: 0.7107 - val_mae: 0.6949 - val_rmse: 0.7588 - val_smape: 1.1356

Epoch 27/128

1146/1146 - 16s - 14ms/step - ia: 0.7048 - loss: 0.3107 - mae: 0.4447 - rmse: 0.5531 - smape: 0.8025 - val_ia: 0.3097 - val_loss: 0.7103 - val_mae: 0.6948 - val_rmse: 0.7585 - val_smape: 1.1338

Epoch 28/128

1146/1146 - 16s - 14ms/step - ia: 0.7059 - loss: 0.3084 - mae: 0.4425 - rmse: 0.5509 - smape: 0.7998 - val_ia: 0.3108 - val_loss: 0.7003 - val_mae: 0.6913 - val_rmse: 0.7546 - val_smape: 1.1355

Epoch 29/128

1146/1146 - 16s - 14ms/step - ia: 0.7085 - loss: 0.3051 - mae: 0.4395 - rmse: 0.5479 - smape: 0.7980 - val_ia: 0.3135 - val_loss: 0.6786 - val_mae: 0.6817 - val_rmse: 0.7439 - val_smape: 1.1288

Epoch 30/128

1146/1146 - 19s - 16ms/step - ia: 0.7078 - loss: 0.3066 - mae: 0.4402 - rmse: 0.5494 - smape: 0.7987 - val_ia: 0.3102 - val_loss: 0.7027 - val_mae: 0.6934 - val_rmse: 0.7563 - val_smape: 1.1342

Epoch 31/128

1146/1146 - 19s - 16ms/step - ia: 0.7099 - loss: 0.3018 - mae: 0.4375 - rmse: 0.5446 - smape: 0.7973 - val_ia: 0.3122 - val_loss: 0.6990 - val_mae: 0.6912 - val_rmse: 0.7534 - val_smape: 1.1316

Epoch 32/128

1146/1146 - 21s - 18ms/step - ia: 0.7114 - loss: 0.3021 - mae: 0.4361 - rmse: 0.5448 - smape: 0.7924 - val_ia: 0.3144 - val_loss: 0.6684 - val_mae: 0.6781 - val_rmse: 0.7401 - val_smape: 1.1294

Epoch 33/128

1146/1146 - 19s - 16ms/step - ia: 0.7139 - loss: 0.2971 - mae: 0.4324 - rmse: 0.5404 - smape: 0.7922 - val_ia: 0.3174 - val_loss: 0.6545 - val_mae: 0.6713 - val_rmse: 0.7322 - val_smape: 1.1221

Epoch 34/128

1146/1146 - 18s - 16ms/step - ia: 0.7128 - loss: 0.2976 - mae: 0.4334 - rmse: 0.5409 - smape: 0.7924 - val_ia: 0.3165 - val_loss: 0.6592 - val_mae: 0.6748 - val_rmse: 0.7355 - val_smape: 1.1232

Epoch 35/128

1146/1146 - 21s - 18ms/step - ia: 0.7139 - loss: 0.2946 - mae: 0.4316 - rmse: 0.5384 - smape: 0.7903 - val_ia: 0.3160 - val_loss: 0.6583 - val_mae: 0.6743 - val_rmse: 0.7355 - val_smape: 1.1210

Epoch 36/128

1146/1146 - 18s - 16ms/step - ia: 0.7164 - loss: 0.2938 - mae: 0.4290 - rmse: 0.5372 - smape: 0.7873 - val_ia: 0.3193 - val_loss: 0.6391 - val_mae: 0.6658 - val_rmse: 0.7259 - val_smape: 1.1186

Epoch 37/128

1146/1146 - 16s - 14ms/step - ia: 0.7180 - loss: 0.2903 - mae: 0.4262 - rmse: 0.5340 - smape: 0.7846 - val_ia: 0.3199 - val_loss: 0.6386 - val_mae: 0.6658 - val_rmse: 0.7260 - val_smape: 1.1212

Epoch 38/128

1146/1146 - 19s - 16ms/step - ia: 0.7181 - loss: 0.2906 - mae: 0.4260 - rmse: 0.5343 - smape: 0.7877 - val_ia: 0.3209 - val_loss: 0.6319 - val_mae: 0.6627 - val_rmse: 0.7225 - val_smape: 1.1158

Epoch 39/128

1146/1146 - 18s - 16ms/step - ia: 0.7197 - loss: 0.2883 - mae: 0.4244 - rmse: 0.5325 - smape: 0.7840 - val_ia: 0.3220 - val_loss: 0.6258 - val_mae: 0.6595 - val_rmse: 0.7192 - val_smape: 1.1129

Epoch 40/128

1146/1146 - 19s - 16ms/step - ia: 0.7209 - loss: 0.2857 - mae: 0.4226 - rmse: 0.5295 - smape: 0.7837 - val_ia: 0.3227 - val_loss: 0.6160 - val_mae: 0.6552 - val_rmse: 0.7145 - val_smape: 1.1059

Epoch 41/128

1146/1146 - 19s - 16ms/step - ia: 0.7220 - loss: 0.2845 - mae: 0.4217 - rmse: 0.5289 - smape: 0.7818 - val_ia: 0.3246 - val_loss: 0.6119 - val_mae: 0.6529 - val_rmse: 0.7118 - val_smape: 1.1032

Epoch 42/128

1146/1146 - 19s - 16ms/step - ia: 0.7219 - loss: 0.2835 - mae: 0.4208 - rmse: 0.5278 - smape: 0.7813 - val_ia: 0.3251 - val_loss: 0.5981 - val_mae: 0.6474 - val_rmse: 0.7065 - val_smape: 1.1044

Epoch 43/128

1146/1146 - 18s - 16ms/step - ia: 0.7243 - loss: 0.2796 - mae: 0.4174 - rmse: 0.5243 - smape: 0.7803 - val_ia: 0.3263 - val_loss: 0.5920 - val_mae: 0.6444 - val_rmse: 0.7033 - val_smape: 1.1024

Epoch 44/128

1146/1146 - 16s - 14ms/step - ia: 0.7243 - loss: 0.2802 - mae: 0.4177 - rmse: 0.5248 - smape: 0.7793 - val_ia: 0.3271 - val_loss: 0.5882 - val_mae: 0.6412 - val_rmse: 0.7000 - val_smape: 1.0925

Epoch 45/128

1146/1146 - 19s - 16ms/step - ia: 0.7259 - loss: 0.2772 - mae: 0.4154 - rmse: 0.5218 - smape: 0.7760 - val_ia: 0.3296 - val_loss: 0.5727 - val_mae: 0.6339 - val_rmse: 0.6921 - val_smape: 1.0871

Epoch 46/128

1146/1146 - 21s - 18ms/step - ia: 0.7275 - loss: 0.2765 - mae: 0.4137 - rmse: 0.5212 - smape: 0.7751 - val_ia: 0.3275 - val_loss: 0.5834 - val_mae: 0.6394 - val_rmse: 0.6989 - val_smape: 1.0955

Epoch 47/128

1146/1146 - 21s - 18ms/step - ia: 0.7280 - loss: 0.2743 - mae: 0.4130 - rmse: 0.5188 - smape: 0.7763 - val_ia: 0.3294 - val_loss: 0.5728 - val_mae: 0.6346 - val_rmse: 0.6936 - val_smape: 1.0928

Epoch 48/128

1146/1146 - 17s - 14ms/step - ia: 0.7295 - loss: 0.2732 - mae: 0.4111 - rmse: 0.5182 - smape: 0.7721 - val_ia: 0.3305 - val_loss: 0.5726 - val_mae: 0.6341 - val_rmse: 0.6933 - val_smape: 1.0935

Epoch 49/128

1146/1146 - 23s - 20ms/step - ia: 0.7306 - loss: 0.2707 - mae: 0.4096 - rmse: 0.5158 - smape: 0.7730 - val_ia: 0.3330 - val_loss: 0.5577 - val_mae: 0.6260 - val_rmse: 0.6845 - val_smape: 1.0828

Epoch 50/128

1146/1146 - 19s - 16ms/step - ia: 0.7311 - loss: 0.2712 - mae: 0.4090 - rmse: 0.5159 - smape: 0.7715 - val_ia: 0.3314 - val_loss: 0.5649 - val_mae: 0.6293 - val_rmse: 0.6886 - val_smape: 1.0809

Epoch 51/128

1146/1146 - 18s - 16ms/step - ia: 0.7323 - loss: 0.2674 - mae: 0.4065 - rmse: 0.5123 - smape: 0.7695 - val_ia: 0.3340 - val_loss: 0.5510 - val_mae: 0.6223 - val_rmse: 0.6812 - val_smape: 1.0769

Epoch 52/128

1146/1146 - 18s - 16ms/step - ia: 0.7329 - loss: 0.2675 - mae: 0.4064 - rmse: 0.5126 - smape: 0.7697 - val_ia: 0.3382 - val_loss: 0.5273 - val_mae: 0.6096 - val_rmse: 0.6682 - val_smape: 1.0697

Epoch 53/128

1146/1146 - 19s - 16ms/step - ia: 0.7328 - loss: 0.2665 - mae: 0.4051 - rmse: 0.5112 - smape: 0.7713 - val_ia: 0.3425 - val_loss: 0.5069 - val_mae: 0.5982 - val_rmse: 0.6560 - val_smape: 1.0583

Epoch 54/128

1146/1146 - 18s - 16ms/step - ia: 0.7339 - loss: 0.2656 - mae: 0.4043 - rmse: 0.5106 - smape: 0.7678 - val_ia: 0.3361 - val_loss: 0.5412 - val_mae: 0.6165 - val_rmse: 0.6762 - val_smape: 1.0740

Epoch 55/128

1146/1146 - 16s - 14ms/step - ia: 0.7357 - loss: 0.2622 - mae: 0.4016 - rmse: 0.5074 - smape: 0.7676 - val_ia: 0.3407 - val_loss: 0.5165 - val_mae: 0.6028 - val_rmse: 0.6618 - val_smape: 1.0646

Epoch 56/128

1146/1146 - 22s - 19ms/step - ia: 0.7358 - loss: 0.2610 - mae: 0.4003 - rmse: 0.5061 - smape: 0.7668 - val_ia: 0.3367 - val_loss: 0.5392 - val_mae: 0.6147 - val_rmse: 0.6742 - val_smape: 1.0666

Epoch 57/128

1146/1146 - 21s - 18ms/step - ia: 0.7376 - loss: 0.2601 - mae: 0.3994 - rmse: 0.5053 - smape: 0.7656 - val_ia: 0.3422 - val_loss: 0.5114 - val_mae: 0.5981 - val_rmse: 0.6580 - val_smape: 1.0556

Epoch 58/128

1146/1146 - 18s - 16ms/step - ia: 0.7389 - loss: 0.2580 - mae: 0.3972 - rmse: 0.5032 - smape: 0.7637 - val_ia: 0.3443 - val_loss: 0.5010 - val_mae: 0.5921 - val_rmse: 0.6520 - val_smape: 1.0504

Epoch 59/128

1146/1146 - 18s - 16ms/step - ia: 0.7398 - loss: 0.2563 - mae: 0.3952 - rmse: 0.5015 - smape: 0.7628 - val_ia: 0.3426 - val_loss: 0.5070 - val_mae: 0.5967 - val_rmse: 0.6562 - val_smape: 1.0578

Epoch 60/128

1146/1146 - 20s - 17ms/step - ia: 0.7423 - loss: 0.2535 - mae: 0.3927 - rmse: 0.4987 - smape: 0.7567 - val_ia: 0.3442 - val_loss: 0.4925 - val_mae: 0.5868 - val_rmse: 0.6482 - val_smape: 1.0532

Epoch 61/128

1146/1146 - 20s - 17ms/step - ia: 0.7412 - loss: 0.2542 - mae: 0.3939 - rmse: 0.4992 - smape: 0.7626 - val_ia: 0.3480 - val_loss: 0.4817 - val_mae: 0.5807 - val_rmse: 0.6406 - val_smape: 1.0451

Epoch 62/128

1146/1146 - 20s - 18ms/step - ia: 0.7427 - loss: 0.2529 - mae: 0.3923 - rmse: 0.4980 - smape: 0.7592 - val_ia: 0.3466 - val_loss: 0.4877 - val_mae: 0.5834 - val_rmse: 0.6444 - val_smape: 1.0479

Epoch 63/128

1146/1146 - 18s - 15ms/step - ia: 0.7428 - loss: 0.2511 - mae: 0.3907 - rmse: 0.4963 - smape: 0.7578 - val_ia: 0.3474 - val_loss: 0.4778 - val_mae: 0.5785 - val_rmse: 0.6397 - val_smape: 1.0500

Epoch 64/128

1146/1146 - 19s - 17ms/step - ia: 0.7441 - loss: 0.2498 - mae: 0.3892 - rmse: 0.4947 - smape: 0.7564 - val_ia: 0.3528 - val_loss: 0.4567 - val_mae: 0.5644 - val_rmse: 0.6257 - val_smape: 1.0336

Epoch 65/128

1146/1146 - 19s - 17ms/step - ia: 0.7454 - loss: 0.2491 - mae: 0.3879 - rmse: 0.4941 - smape: 0.7561 - val_ia: 0.3556 - val_loss: 0.4536 - val_mae: 0.5620 - val_rmse: 0.6222 - val_smape: 1.0264

Epoch 66/128

1146/1146 - 19s - 17ms/step - ia: 0.7481 - loss: 0.2456 - mae: 0.3848 - rmse: 0.4908 - smape: 0.7513 - val_ia: 0.3546 - val_loss: 0.4513 - val_mae: 0.5615 - val_rmse: 0.6222 - val_smape: 1.0328

Epoch 67/128

1146/1146 - 20s - 18ms/step - ia: 0.7471 - loss: 0.2461 - mae: 0.3854 - rmse: 0.4912 - smape: 0.7541 - val_ia: 0.3568 - val_loss: 0.4409 - val_mae: 0.5550 - val_rmse: 0.6165 - val_smape: 1.0347

Epoch 68/128

1146/1146 - 21s - 18ms/step - ia: 0.7488 - loss: 0.2437 - mae: 0.3830 - rmse: 0.4884 - smape: 0.7512 - val_ia: 0.3591 - val_loss: 0.4388 - val_mae: 0.5520 - val_rmse: 0.6131 - val_smape: 1.0216

Epoch 69/128

1146/1146 - 23s - 20ms/step - ia: 0.7505 - loss: 0.2407 - mae: 0.3807 - rmse: 0.4855 - smape: 0.7485 - val_ia: 0.3662 - val_loss: 0.4224 - val_mae: 0.5398 - val_rmse: 0.6009 - val_smape: 1.0060

Epoch 70/128

1146/1146 - 17s - 15ms/step - ia: 0.7514 - loss: 0.2391 - mae: 0.3794 - rmse: 0.4838 - smape: 0.7466 - val_ia: 0.3620 - val_loss: 0.4343 - val_mae: 0.5489 - val_rmse: 0.6092 - val_smape: 1.0196

Epoch 71/128

1146/1146 - 17s - 15ms/step - ia: 0.7515 - loss: 0.2387 - mae: 0.3789 - rmse: 0.4836 - smape: 0.7471 - val_ia: 0.3657 - val_loss: 0.4214 - val_mae: 0.5397 - val_rmse: 0.6011 - val_smape: 1.0135

Epoch 72/128

1146/1146 - 21s - 19ms/step - ia: 0.7529 - loss: 0.2364 - mae: 0.3774 - rmse: 0.4813 - smape: 0.7462 - val_ia: 0.3675 - val_loss: 0.4154 - val_mae: 0.5361 - val_rmse: 0.5973 - val_smape: 1.0136

Epoch 73/128

1146/1146 - 20s - 17ms/step - ia: 0.7533 - loss: 0.2357 - mae: 0.3763 - rmse: 0.4807 - smape: 0.7450 - val_ia: 0.3665 - val_loss: 0.4171 - val_mae: 0.5374 - val_rmse: 0.5989 - val_smape: 1.0174

Epoch 74/128

1146/1146 - 18s - 15ms/step - ia: 0.7549 - loss: 0.2324 - mae: 0.3735 - rmse: 0.4772 - smape: 0.7424 - val_ia: 0.3723 - val_loss: 0.3990 - val_mae: 0.5251 - val_rmse: 0.5851 - val_smape: 1.0012

Epoch 75/128

1146/1146 - 22s - 19ms/step - ia: 0.7548 - loss: 0.2330 - mae: 0.3741 - rmse: 0.4779 - smape: 0.7436 - val_ia: 0.3775 - val_loss: 0.3916 - val_mae: 0.5182 - val_rmse: 0.5785 - val_smape: 0.9893

Epoch 76/128

1146/1146 - 19s - 16ms/step - ia: 0.7569 - loss: 0.2301 - mae: 0.3715 - rmse: 0.4747 - smape: 0.7401 - val_ia: 0.3759 - val_loss: 0.3903 - val_mae: 0.5185 - val_rmse: 0.5787 - val_smape: 0.9981

Epoch 77/128

1146/1146 - 19s - 16ms/step - ia: 0.7576 - loss: 0.2277 - mae: 0.3697 - rmse: 0.4724 - smape: 0.7375 - val_ia: 0.3762 - val_loss: 0.3911 - val_mae: 0.5185 - val_rmse: 0.5783 - val_smape: 0.9952

Epoch 78/128

1146/1146 - 17s - 15ms/step - ia: 0.7592 - loss: 0.2260 - mae: 0.3679 - rmse: 0.4706 - smape: 0.7351 - val_ia: 0.3824 - val_loss: 0.3770 - val_mae: 0.5083 - val_rmse: 0.5680 - val_smape: 0.9882

Epoch 79/128

1146/1146 - 22s - 19ms/step - ia: 0.7593 - loss: 0.2252 - mae: 0.3675 - rmse: 0.4698 - smape: 0.7330 - val_ia: 0.3854 - val_loss: 0.3690 - val_mae: 0.5018 - val_rmse: 0.5615 - val_smape: 0.9825

Epoch 80/128

1146/1146 - 19s - 17ms/step - ia: 0.7607 - loss: 0.2241 - mae: 0.3657 - rmse: 0.4687 - smape: 0.7347 - val_ia: 0.3852 - val_loss: 0.3705 - val_mae: 0.5038 - val_rmse: 0.5626 - val_smape: 0.9862

Epoch 81/128

1146/1146 - 19s - 17ms/step - ia: 0.7615 - loss: 0.2215 - mae: 0.3639 - rmse: 0.4659 - smape: 0.7328 - val_ia: 0.3836 - val_loss: 0.3725 - val_mae: 0.5058 - val_rmse: 0.5650 - val_smape: 0.9948

Epoch 82/128

1146/1146 - 21s - 18ms/step - ia: 0.7623 - loss: 0.2198 - mae: 0.3625 - rmse: 0.4641 - smape: 0.7298 - val_ia: 0.3886 - val_loss: 0.3633 - val_mae: 0.4979 - val_rmse: 0.5562 - val_smape: 0.9828

Epoch 83/128

1146/1146 - 21s - 18ms/step - ia: 0.7641 - loss: 0.2177 - mae: 0.3600 - rmse: 0.4618 - smape: 0.7274 - val_ia: 0.3898 - val_loss: 0.3555 - val_mae: 0.4928 - val_rmse: 0.5512 - val_smape: 0.9859

Epoch 84/128

1146/1146 - 19s - 17ms/step - ia: 0.7649 - loss: 0.2158 - mae: 0.3587 - rmse: 0.4600 - smape: 0.7279 - val_ia: 0.3920 - val_loss: 0.3533 - val_mae: 0.4906 - val_rmse: 0.5490 - val_smape: 0.9790

Epoch 85/128

1146/1146 - 19s - 17ms/step - ia: 0.7651 - loss: 0.2156 - mae: 0.3584 - rmse: 0.4598 - smape: 0.7282 - val_ia: 0.3926 - val_loss: 0.3548 - val_mae: 0.4912 - val_rmse: 0.5490 - val_smape: 0.9760

Epoch 86/128

1146/1146 - 17s - 15ms/step - ia: 0.7648 - loss: 0.2151 - mae: 0.3584 - rmse: 0.4594 - smape: 0.7268 - val_ia: 0.3989 - val_loss: 0.3442 - val_mae: 0.4832 - val_rmse: 0.5394 - val_smape: 0.9697

Epoch 87/128

1146/1146 - 17s - 15ms/step - ia: 0.7674 - loss: 0.2117 - mae: 0.3551 - rmse: 0.4555 - smape: 0.7199 - val_ia: 0.3980 - val_loss: 0.3416 - val_mae: 0.4809 - val_rmse: 0.5380 - val_smape: 0.9747

Epoch 88/128

1146/1146 - 18s - 16ms/step - ia: 0.7679 - loss: 0.2103 - mae: 0.3538 - rmse: 0.4537 - smape: 0.7233 - val_ia: 0.4062 - val_loss: 0.3280 - val_mae: 0.4700 - val_rmse: 0.5260 - val_smape: 0.9624

Epoch 89/128

1146/1146 - 17s - 15ms/step - ia: 0.7692 - loss: 0.2085 - mae: 0.3520 - rmse: 0.4516 - smape: 0.7179 - val_ia: 0.4060 - val_loss: 0.3293 - val_mae: 0.4713 - val_rmse: 0.5268 - val_smape: 0.9670

Epoch 90/128

1146/1146 - 19s - 16ms/step - ia: 0.7708 - loss: 0.2062 - mae: 0.3500 - rmse: 0.4493 - smape: 0.7166 - val_ia: 0.4021 - val_loss: 0.3337 - val_mae: 0.4757 - val_rmse: 0.5314 - val_smape: 0.9794

Epoch 91/128

1146/1146 - 18s - 16ms/step - ia: 0.7710 - loss: 0.2049 - mae: 0.3495 - rmse: 0.4480 - smape: 0.7178 - val_ia: 0.4127 - val_loss: 0.3210 - val_mae: 0.4650 - val_rmse: 0.5193 - val_smape: 0.9604

Epoch 92/128

1146/1146 - 18s - 15ms/step - ia: 0.7720 - loss: 0.2036 - mae: 0.3480 - rmse: 0.4461 - smape: 0.7125 - val_ia: 0.4125 - val_loss: 0.3190 - val_mae: 0.4634 - val_rmse: 0.5178 - val_smape: 0.9593

Epoch 93/128

1146/1146 - 16s - 14ms/step - ia: 0.7729 - loss: 0.2013 - mae: 0.3465 - rmse: 0.4438 - smape: 0.7112 - val_ia: 0.4079 - val_loss: 0.3249 - val_mae: 0.4698 - val_rmse: 0.5245 - val_smape: 0.9735

Epoch 94/128

1146/1146 - 18s - 16ms/step - ia: 0.7734 - loss: 0.2004 - mae: 0.3458 - rmse: 0.4429 - smape: 0.7123 - val_ia: 0.4117 - val_loss: 0.3164 - val_mae: 0.4623 - val_rmse: 0.5170 - val_smape: 0.9726

Epoch 95/128

1146/1146 - 17s - 15ms/step - ia: 0.7743 - loss: 0.1984 - mae: 0.3439 - rmse: 0.4405 - smape: 0.7082 - val_ia: 0.4179 - val_loss: 0.3114 - val_mae: 0.4563 - val_rmse: 0.5105 - val_smape: 0.9654

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

573/573 - 13s - 22ms/step - ia: 0.2295 - loss: 1.1633 - mae: 0.8831 - rmse: 1.0755 - smape: 1.5157 - val_ia: 0.2999 - val_loss: 0.9741 - val_mae: 0.8099 - val_rmse: 0.9493 - val_smape: 1.4445

Epoch 2/128

573/573 - 5s - 9ms/step - ia: 0.2324 - loss: 1.1076 - mae: 0.8626 - rmse: 1.0500 - smape: 1.5130 - val_ia: 0.3015 - val_loss: 0.9342 - val_mae: 0.7945 - val_rmse: 0.9296 - val_smape: 1.4513

Epoch 3/128

573/573 - 5s - 9ms/step - ia: 0.2369 - loss: 1.0587 - mae: 0.8444 - rmse: 1.0261 - smape: 1.5095 - val_ia: 0.3030 - val_loss: 0.8988 - val_mae: 0.7805 - val_rmse: 0.9117 - val_smape: 1.4562

Epoch 4/128

573/573 - 5s - 9ms/step - ia: 0.2431 - loss: 1.0144 - mae: 0.8273 - rmse: 1.0047 - smape: 1.5018 - val_ia: 0.3046 - val_loss: 0.8677 - val_mae: 0.7680 - val_rmse: 0.8954 - val_smape: 1.4576

Epoch 5/128

573/573 - 10s - 18ms/step - ia: 0.2483 - loss: 0.9753 - mae: 0.8138 - rmse: 0.9851 - smape: 1.4954 - val_ia: 0.3070 - val_loss: 0.8404 - val_mae: 0.7567 - val_rmse: 0.8807 - val_smape: 1.4530

Epoch 6/128

573/573 - 5s - 9ms/step - ia: 0.2597 - loss: 0.9377 - mae: 0.8008 - rmse: 0.9659 - smape: 1.4850 - val_ia: 0.3096 - val_loss: 0.8165 - val_mae: 0.7468 - val_rmse: 0.8675 - val_smape: 1.4409

Epoch 7/128

573/573 - 10s - 18ms/step - ia: 0.2713 - loss: 0.9027 - mae: 0.7865 - rmse: 0.9477 - smape: 1.4672 - val_ia: 0.3125 - val_loss: 0.7959 - val_mae: 0.7380 - val_rmse: 0.8557 - val_smape: 1.4259

Epoch 8/128

573/573 - 5s - 9ms/step - ia: 0.2841 - loss: 0.8732 - mae: 0.7760 - rmse: 0.9321 - smape: 1.4493 - val_ia: 0.3154 - val_loss: 0.7785 - val_mae: 0.7304 - val_rmse: 0.8453 - val_smape: 1.4114

Epoch 9/128

573/573 - 5s - 9ms/step - ia: 0.2978 - loss: 0.8479 - mae: 0.7654 - rmse: 0.9185 - smape: 1.4292 - val_ia: 0.3183 - val_loss: 0.7641 - val_mae: 0.7241 - val_rmse: 0.8364 - val_smape: 1.3994

Epoch 10/128

573/573 - 10s - 17ms/step - ia: 0.3131 - loss: 0.8253 - mae: 0.7564 - rmse: 0.9063 - smape: 1.4097 - val_ia: 0.3212 - val_loss: 0.7525 - val_mae: 0.7188 - val_rmse: 0.8288 - val_smape: 1.3890

Epoch 11/128

573/573 - 5s - 9ms/step - ia: 0.3280 - loss: 0.8035 - mae: 0.7487 - rmse: 0.8942 - smape: 1.3921 - val_ia: 0.3241 - val_loss: 0.7437 - val_mae: 0.7146 - val_rmse: 0.8226 - val_smape: 1.3753

Epoch 12/128

573/573 - 10s - 18ms/step - ia: 0.3445 - loss: 0.7844 - mae: 0.7400 - rmse: 0.8836 - smape: 1.3705 - val_ia: 0.3271 - val_loss: 0.7376 - val_mae: 0.7114 - val_rmse: 0.8178 - val_smape: 1.3606

Epoch 13/128

573/573 - 5s - 9ms/step - ia: 0.3583 - loss: 0.7687 - mae: 0.7334 - rmse: 0.8748 - smape: 1.3518 - val_ia: 0.3304 - val_loss: 0.7341 - val_mae: 0.7090 - val_rmse: 0.8143 - val_smape: 1.3451

Epoch 14/128

573/573 - 10s - 18ms/step - ia: 0.3751 - loss: 0.7497 - mae: 0.7247 - rmse: 0.8637 - smape: 1.3296 - val_ia: 0.3339 - val_loss: 0.7328 - val_mae: 0.7075 - val_rmse: 0.8121 - val_smape: 1.3309

Epoch 15/128

573/573 - 5s - 9ms/step - ia: 0.3882 - loss: 0.7372 - mae: 0.7193 - rmse: 0.8565 - smape: 1.3131 - val_ia: 0.3374 - val_loss: 0.7339 - val_mae: 0.7069 - val_rmse: 0.8111 - val_smape: 1.3172

Epoch 16/128

573/573 - 5s - 8ms/step - ia: 0.4002 - loss: 0.7272 - mae: 0.7148 - rmse: 0.8508 - smape: 1.2972 - val_ia: 0.3410 - val_loss: 0.7365 - val_mae: 0.7068 - val_rmse: 0.8111 - val_smape: 1.3041

Epoch 17/128

573/573 - 6s - 10ms/step - ia: 0.4103 - loss: 0.7200 - mae: 0.7111 - rmse: 0.8464 - smape: 1.2842 - val_ia: 0.3446 - val_loss: 0.7408 - val_mae: 0.7075 - val_rmse: 0.8120 - val_smape: 1.2921

Epoch 18/128

573/573 - 5s - 9ms/step - ia: 0.4211 - loss: 0.7091 - mae: 0.7049 - rmse: 0.8398 - smape: 1.2682 - val_ia: 0.3482 - val_loss: 0.7464 - val_mae: 0.7086 - val_rmse: 0.8137 - val_smape: 1.2820

Epoch 19/128

573/573 - 5s - 8ms/step - ia: 0.4303 - loss: 0.7017 - mae: 0.7010 - rmse: 0.8355 - smape: 1.2571 - val_ia: 0.3518 - val_loss: 0.7527 - val_mae: 0.7102 - val_rmse: 0.8160 - val_smape: 1.2733

Epoch 20/128

573/573 - 5s - 9ms/step - ia: 0.4380 - loss: 0.6968 - mae: 0.6977 - rmse: 0.8329 - smape: 1.2438 - val_ia: 0.3553 - val_loss: 0.7600 - val_mae: 0.7123 - val_rmse: 0.8188 - val_smape: 1.2659

Epoch 21/128

573/573 - 5s - 8ms/step - ia: 0.4456 - loss: 0.6876 - mae: 0.6923 - rmse: 0.8271 - smape: 1.2332 - val_ia: 0.3586 - val_loss: 0.7680 - val_mae: 0.7149 - val_rmse: 0.8221 - val_smape: 1.2607

Epoch 22/128

573/573 - 5s - 8ms/step - ia: 0.4548 - loss: 0.6792 - mae: 0.6873 - rmse: 0.8222 - smape: 1.2216 - val_ia: 0.3617 - val_loss: 0.7764 - val_mae: 0.7177 - val_rmse: 0.8257 - val_smape: 1.2560

Epoch 23/128

573/573 - 5s - 8ms/step - ia: 0.4598 - loss: 0.6723 - mae: 0.6834 - rmse: 0.8179 - smape: 1.2162 - val_ia: 0.3646 - val_loss: 0.7853 - val_mae: 0.7207 - val_rmse: 0.8297 - val_smape: 1.2520

Epoch 24/128

573/573 - 6s - 10ms/step - ia: 0.4660 - loss: 0.6689 - mae: 0.6802 - rmse: 0.8157 - smape: 1.2046 - val_ia: 0.3674 - val_loss: 0.7946 - val_mae: 0.7239 - val_rmse: 0.8339 - val_smape: 1.2489

Epoch 25/128

573/573 - 5s - 9ms/step - ia: 0.4723 - loss: 0.6607 - mae: 0.6757 - rmse: 0.8105 - smape: 1.1973 - val_ia: 0.3700 - val_loss: 0.8038 - val_mae: 0.7273 - val_rmse: 0.8382 - val_smape: 1.2464

Epoch 26/128

573/573 - 5s - 8ms/step - ia: 0.4759 - loss: 0.6591 - mae: 0.6739 - rmse: 0.8097 - smape: 1.1896 - val_ia: 0.3725 - val_loss: 0.8128 - val_mae: 0.7306 - val_rmse: 0.8424 - val_smape: 1.2446

Epoch 27/128

573/573 - 5s - 8ms/step - ia: 0.4807 - loss: 0.6529 - mae: 0.6698 - rmse: 0.8059 - smape: 1.1846 - val_ia: 0.3748 - val_loss: 0.8222 - val_mae: 0.7342 - val_rmse: 0.8469 - val_smape: 1.2432

Epoch 28/128

573/573 - 5s - 9ms/step - ia: 0.4840 - loss: 0.6480 - mae: 0.6670 - rmse: 0.8025 - smape: 1.1786 - val_ia: 0.3769 - val_loss: 0.8315 - val_mae: 0.7377 - val_rmse: 0.8514 - val_smape: 1.2421

Epoch 29/128

573/573 - 5s - 9ms/step - ia: 0.4886 - loss: 0.6420 - mae: 0.6635 - rmse: 0.7989 - smape: 1.1702 - val_ia: 0.3788 - val_loss: 0.8407 - val_mae: 0.7413 - val_rmse: 0.8559 - val_smape: 1.2413

Epoch 29: early stopping

Restoring model weights from the end of the best epoch: 14.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:41 625ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
150/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

Epoch 1/128

 42%|████▏     | 5/12 [2:22:38<3:06:23, 1597.66s/trial, best loss: 0.212949463855241]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 17s - 60ms/step - ia: 0.2884 - loss: 1.4893 - mae: 0.9987 - rmse: 1.2183 - smape: 1.4490 - val_ia: 0.2648 - val_loss: 1.0711 - val_mae: 0.8611 - val_rmse: 1.0186 - val_smape: 1.4765

Epoch 2/128

287/287 - 10s - 33ms/step - ia: 0.2825 - loss: 1.3665 - mae: 0.9569 - rmse: 1.1669 - smape: 1.4590 - val_ia: 0.2316 - val_loss: 0.9530 - val_mae: 0.8117 - val_rmse: 0.9642 - val_smape: 1.5536

Epoch 3/128

287/287 - 5s - 18ms/step - ia: 0.2767 - loss: 1.3116 - mae: 0.9397 - rmse: 1.1437 - smape: 1.4688 - val_ia: 0.2158 - val_loss: 0.8933 - val_mae: 0.7867 - val_rmse: 0.9359 - val_smape: 1.6580

Epoch 4/128

287/287 - 4s - 13ms/step - ia: 0.2715 - loss: 1.2959 - mae: 0.9338 - rmse: 1.1364 - smape: 1.4744 - val_ia: 0.2147 - val_loss: 0.8639 - val_mae: 0.7739 - val_rmse: 0.9217 - val_smape: 1.7639

Epoch 5/128

287/287 - 5s - 17ms/step - ia: 0.2720 - loss: 1.2834 - mae: 0.9290 - rmse: 1.1309 - smape: 1.4762 - val_ia: 0.2154 - val_loss: 0.8510 - val_mae: 0.7680 - val_rmse: 0.9153 - val_smape: 1.8323

Epoch 6/128

287/287 - 5s - 19ms/step - ia: 0.2742 - loss: 1.2695 - mae: 0.9230 - rmse: 1.1253 - smape: 1.4745 - val_ia: 0.2167 - val_loss: 0.8444 - val_mae: 0.7649 - val_rmse: 0.9120 - val_smape: 1.8502

Epoch 7/128

287/287 - 5s - 18ms/step - ia: 0.2695 - loss: 1.2642 - mae: 0.9233 - rmse: 1.1225 - smape: 1.4811 - val_ia: 0.2179 - val_loss: 0.8407 - val_mae: 0.7631 - val_rmse: 0.9101 - val_smape: 1.8429

Epoch 8/128

287/287 - 5s - 18ms/step - ia: 0.2749 - loss: 1.2426 - mae: 0.9129 - rmse: 1.1129 - smape: 1.4696 - val_ia: 0.2188 - val_loss: 0.8381 - val_mae: 0.7619 - val_rmse: 0.9088 - val_smape: 1.8338

Epoch 9/128

287/287 - 5s - 18ms/step - ia: 0.2723 - loss: 1.2302 - mae: 0.9101 - rmse: 1.1075 - smape: 1.4746 - val_ia: 0.2198 - val_loss: 0.8357 - val_mae: 0.7607 - val_rmse: 0.9075 - val_smape: 1.8246

Epoch 10/128

287/287 - 4s - 15ms/step - ia: 0.2695 - loss: 1.2288 - mae: 0.9106 - rmse: 1.1068 - smape: 1.4797 - val_ia: 0.2210 - val_loss: 0.8330 - val_mae: 0.7595 - val_rmse: 0.9062 - val_smape: 1.8148

Epoch 11/128

287/287 - 4s - 15ms/step - ia: 0.2687 - loss: 1.2212 - mae: 0.9087 - rmse: 1.1037 - smape: 1.4790 - val_ia: 0.2214 - val_loss: 0.8327 - val_mae: 0.7594 - val_rmse: 0.9060 - val_smape: 1.8064

Epoch 12/128

287/287 - 5s - 18ms/step - ia: 0.2668 - loss: 1.2121 - mae: 0.9052 - rmse: 1.0996 - smape: 1.4809 - val_ia: 0.2226 - val_loss: 0.8298 - val_mae: 0.7580 - val_rmse: 0.9045 - val_smape: 1.7966

Epoch 13/128

287/287 - 5s - 17ms/step - ia: 0.2650 - loss: 1.2029 - mae: 0.9025 - rmse: 1.0952 - smape: 1.4854 - val_ia: 0.2235 - val_loss: 0.8281 - val_mae: 0.7572 - val_rmse: 0.9036 - val_smape: 1.7875

Epoch 14/128

287/287 - 4s - 14ms/step - ia: 0.2671 - loss: 1.1856 - mae: 0.8970 - rmse: 1.0873 - smape: 1.4836 - val_ia: 0.2242 - val_loss: 0.8270 - val_mae: 0.7567 - val_rmse: 0.9030 - val_smape: 1.7793

Epoch 15/128

287/287 - 5s - 18ms/step - ia: 0.2657 - loss: 1.1721 - mae: 0.8927 - rmse: 1.0810 - smape: 1.4853 - val_ia: 0.2249 - val_loss: 0.8256 - val_mae: 0.7561 - val_rmse: 0.9022 - val_smape: 1.7707

Epoch 16/128

287/287 - 4s - 14ms/step - ia: 0.2696 - loss: 1.1589 - mae: 0.8850 - rmse: 1.0751 - smape: 1.4789 - val_ia: 0.2256 - val_loss: 0.8246 - val_mae: 0.7556 - val_rmse: 0.9017 - val_smape: 1.7623

Epoch 17/128

287/287 - 5s - 16ms/step - ia: 0.2670 - loss: 1.1536 - mae: 0.8838 - rmse: 1.0727 - smape: 1.4806 - val_ia: 0.2269 - val_loss: 0.8218 - val_mae: 0.7543 - val_rmse: 0.9002 - val_smape: 1.7531

Epoch 18/128

287/287 - 6s - 20ms/step - ia: 0.2665 - loss: 1.1431 - mae: 0.8814 - rmse: 1.0677 - smape: 1.4837 - val_ia: 0.2279 - val_loss: 0.8199 - val_mae: 0.7534 - val_rmse: 0.8992 - val_smape: 1.7444

Epoch 19/128

287/287 - 5s - 18ms/step - ia: 0.2612 - loss: 1.1439 - mae: 0.8830 - rmse: 1.0681 - smape: 1.4917 - val_ia: 0.2286 - val_loss: 0.8189 - val_mae: 0.7529 - val_rmse: 0.8986 - val_smape: 1.7367

Epoch 20/128

287/287 - 4s - 15ms/step - ia: 0.2632 - loss: 1.1342 - mae: 0.8791 - rmse: 1.0636 - smape: 1.4866 - val_ia: 0.2292 - val_loss: 0.8183 - val_mae: 0.7527 - val_rmse: 0.8983 - val_smape: 1.7293

Epoch 21/128

287/287 - 4s - 15ms/step - ia: 0.2593 - loss: 1.1299 - mae: 0.8775 - rmse: 1.0617 - smape: 1.4919 - val_ia: 0.2302 - val_loss: 0.8166 - val_mae: 0.7519 - val_rmse: 0.8974 - val_smape: 1.7214

Epoch 22/128

287/287 - 6s - 20ms/step - ia: 0.2602 - loss: 1.1235 - mae: 0.8751 - rmse: 1.0586 - smape: 1.4921 - val_ia: 0.2308 - val_loss: 0.8161 - val_mae: 0.7517 - val_rmse: 0.8971 - val_smape: 1.7139

Epoch 23/128

287/287 - 5s - 18ms/step - ia: 0.2627 - loss: 1.1060 - mae: 0.8688 - rmse: 1.0504 - smape: 1.4892 - val_ia: 0.2320 - val_loss: 0.8138 - val_mae: 0.7506 - val_rmse: 0.8959 - val_smape: 1.7058

Epoch 24/128

287/287 - 5s - 18ms/step - ia: 0.2631 - loss: 1.1003 - mae: 0.8665 - rmse: 1.0473 - smape: 1.4875 - val_ia: 0.2328 - val_loss: 0.8126 - val_mae: 0.7500 - val_rmse: 0.8952 - val_smape: 1.6983

Epoch 25/128

287/287 - 5s - 19ms/step - ia: 0.2602 - loss: 1.0995 - mae: 0.8663 - rmse: 1.0471 - smape: 1.4918 - val_ia: 0.2335 - val_loss: 0.8122 - val_mae: 0.7499 - val_rmse: 0.8950 - val_smape: 1.6913

Epoch 26/128

287/287 - 11s - 38ms/step - ia: 0.2594 - loss: 1.0924 - mae: 0.8656 - rmse: 1.0439 - smape: 1.4948 - val_ia: 0.2344 - val_loss: 0.8107 - val_mae: 0.7492 - val_rmse: 0.8941 - val_smape: 1.6840

Epoch 27/128

287/287 - 10s - 35ms/step - ia: 0.2609 - loss: 1.0817 - mae: 0.8607 - rmse: 1.0387 - smape: 1.4904 - val_ia: 0.2353 - val_loss: 0.8097 - val_mae: 0.7487 - val_rmse: 0.8936 - val_smape: 1.6768

Epoch 28/128

287/287 - 5s - 18ms/step - ia: 0.2588 - loss: 1.0778 - mae: 0.8598 - rmse: 1.0368 - smape: 1.4961 - val_ia: 0.2365 - val_loss: 0.8074 - val_mae: 0.7476 - val_rmse: 0.8924 - val_smape: 1.6694

Epoch 29/128

287/287 - 5s - 16ms/step - ia: 0.2576 - loss: 1.0704 - mae: 0.8567 - rmse: 1.0336 - smape: 1.4950 - val_ia: 0.2373 - val_loss: 0.8066 - val_mae: 0.7473 - val_rmse: 0.8920 - val_smape: 1.6623

Epoch 30/128

287/287 - 6s - 20ms/step - ia: 0.2605 - loss: 1.0645 - mae: 0.8534 - rmse: 1.0304 - smape: 1.4893 - val_ia: 0.2382 - val_loss: 0.8063 - val_mae: 0.7471 - val_rmse: 0.8917 - val_smape: 1.6553

Epoch 31/128

287/287 - 10s - 33ms/step - ia: 0.2618 - loss: 1.0510 - mae: 0.8486 - rmse: 1.0241 - smape: 1.4886 - val_ia: 0.2392 - val_loss: 0.8051 - val_mae: 0.7466 - val_rmse: 0.8911 - val_smape: 1.6482

Epoch 32/128

287/287 - 5s - 19ms/step - ia: 0.2582 - loss: 1.0540 - mae: 0.8495 - rmse: 1.0255 - smape: 1.4921 - val_ia: 0.2403 - val_loss: 0.8038 - val_mae: 0.7459 - val_rmse: 0.8903 - val_smape: 1.6411

Epoch 33/128

287/287 - 5s - 18ms/step - ia: 0.2596 - loss: 1.0457 - mae: 0.8472 - rmse: 1.0214 - smape: 1.4905 - val_ia: 0.2413 - val_loss: 0.8026 - val_mae: 0.7454 - val_rmse: 0.8897 - val_smape: 1.6343

Epoch 34/128

287/287 - 5s - 19ms/step - ia: 0.2604 - loss: 1.0394 - mae: 0.8441 - rmse: 1.0180 - smape: 1.4926 - val_ia: 0.2424 - val_loss: 0.8015 - val_mae: 0.7448 - val_rmse: 0.8891 - val_smape: 1.6273

Epoch 35/128

287/287 - 5s - 19ms/step - ia: 0.2579 - loss: 1.0337 - mae: 0.8430 - rmse: 1.0151 - smape: 1.4953 - val_ia: 0.2436 - val_loss: 0.7998 - val_mae: 0.7440 - val_rmse: 0.8882 - val_smape: 1.6203

Epoch 36/128

287/287 - 5s - 18ms/step - ia: 0.2580 - loss: 1.0267 - mae: 0.8416 - rmse: 1.0118 - smape: 1.4982 - val_ia: 0.2446 - val_loss: 0.7992 - val_mae: 0.7437 - val_rmse: 0.8878 - val_smape: 1.6134

Epoch 37/128

287/287 - 10s - 35ms/step - ia: 0.2626 - loss: 1.0178 - mae: 0.8370 - rmse: 1.0076 - smape: 1.4901 - val_ia: 0.2457 - val_loss: 0.7988 - val_mae: 0.7435 - val_rmse: 0.8875 - val_smape: 1.6065

Epoch 38/128

287/287 - 5s - 18ms/step - ia: 0.2617 - loss: 1.0148 - mae: 0.8353 - rmse: 1.0057 - smape: 1.4907 - val_ia: 0.2471 - val_loss: 0.7957 - val_mae: 0.7420 - val_rmse: 0.8859 - val_smape: 1.5997

Epoch 39/128

287/287 - 4s - 14ms/step - ia: 0.2628 - loss: 1.0092 - mae: 0.8342 - rmse: 1.0035 - smape: 1.4891 - val_ia: 0.2482 - val_loss: 0.7955 - val_mae: 0.7419 - val_rmse: 0.8857 - val_smape: 1.5929

Epoch 40/128

287/287 - 6s - 20ms/step - ia: 0.2624 - loss: 1.0062 - mae: 0.8343 - rmse: 1.0017 - smape: 1.4930 - val_ia: 0.2494 - val_loss: 0.7945 - val_mae: 0.7414 - val_rmse: 0.8851 - val_smape: 1.5864

Epoch 41/128

287/287 - 5s - 18ms/step - ia: 0.2638 - loss: 0.9978 - mae: 0.8297 - rmse: 0.9977 - smape: 1.4865 - val_ia: 0.2506 - val_loss: 0.7937 - val_mae: 0.7410 - val_rmse: 0.8847 - val_smape: 1.5797

Epoch 42/128

287/287 - 5s - 17ms/step - ia: 0.2641 - loss: 0.9916 - mae: 0.8293 - rmse: 0.9944 - smape: 1.4883 - val_ia: 0.2520 - val_loss: 0.7921 - val_mae: 0.7401 - val_rmse: 0.8838 - val_smape: 1.5728

Epoch 43/128

287/287 - 5s - 17ms/step - ia: 0.2640 - loss: 0.9909 - mae: 0.8272 - rmse: 0.9939 - smape: 1.4863 - val_ia: 0.2534 - val_loss: 0.7902 - val_mae: 0.7392 - val_rmse: 0.8828 - val_smape: 1.5662

Epoch 44/128

287/287 - 5s - 16ms/step - ia: 0.2649 - loss: 0.9849 - mae: 0.8255 - rmse: 0.9913 - smape: 1.4867 - val_ia: 0.2547 - val_loss: 0.7896 - val_mae: 0.7389 - val_rmse: 0.8824 - val_smape: 1.5596

Epoch 45/128

287/287 - 5s - 17ms/step - ia: 0.2657 - loss: 0.9824 - mae: 0.8245 - rmse: 0.9901 - smape: 1.4847 - val_ia: 0.2562 - val_loss: 0.7881 - val_mae: 0.7381 - val_rmse: 0.8815 - val_smape: 1.5528

Epoch 46/128

287/287 - 5s - 17ms/step - ia: 0.2670 - loss: 0.9778 - mae: 0.8236 - rmse: 0.9875 - smape: 1.4852 - val_ia: 0.2577 - val_loss: 0.7877 - val_mae: 0.7378 - val_rmse: 0.8813 - val_smape: 1.5462

Epoch 47/128

287/287 - 6s - 20ms/step - ia: 0.2719 - loss: 0.9683 - mae: 0.8180 - rmse: 0.9829 - smape: 1.4756 - val_ia: 0.2592 - val_loss: 0.7876 - val_mae: 0.7377 - val_rmse: 0.8812 - val_smape: 1.5393

Epoch 48/128

287/287 - 11s - 37ms/step - ia: 0.2717 - loss: 0.9641 - mae: 0.8190 - rmse: 0.9806 - smape: 1.4807 - val_ia: 0.2608 - val_loss: 0.7867 - val_mae: 0.7372 - val_rmse: 0.8807 - val_smape: 1.5329

Epoch 49/128

287/287 - 11s - 37ms/step - ia: 0.2715 - loss: 0.9645 - mae: 0.8175 - rmse: 0.9809 - smape: 1.4790 - val_ia: 0.2623 - val_loss: 0.7850 - val_mae: 0.7364 - val_rmse: 0.8797 - val_smape: 1.5265

Epoch 50/128

287/287 - 7s - 24ms/step - ia: 0.2708 - loss: 0.9618 - mae: 0.8171 - rmse: 0.9795 - smape: 1.4808 - val_ia: 0.2639 - val_loss: 0.7835 - val_mae: 0.7356 - val_rmse: 0.8788 - val_smape: 1.5201

Epoch 51/128

287/287 - 6s - 22ms/step - ia: 0.2729 - loss: 0.9592 - mae: 0.8164 - rmse: 0.9783 - smape: 1.4763 - val_ia: 0.2655 - val_loss: 0.7805 - val_mae: 0.7341 - val_rmse: 0.8773 - val_smape: 1.5141

Epoch 52/128

287/287 - 10s - 36ms/step - ia: 0.2741 - loss: 0.9523 - mae: 0.8140 - rmse: 0.9749 - smape: 1.4761 - val_ia: 0.2672 - val_loss: 0.7804 - val_mae: 0.7340 - val_rmse: 0.8771 - val_smape: 1.5075

Epoch 53/128

287/287 - 11s - 37ms/step - ia: 0.2796 - loss: 0.9456 - mae: 0.8109 - rmse: 0.9712 - smape: 1.4695 - val_ia: 0.2689 - val_loss: 0.7792 - val_mae: 0.7333 - val_rmse: 0.8764 - val_smape: 1.5012

Epoch 54/128

287/287 - 4s - 15ms/step - ia: 0.2828 - loss: 0.9350 - mae: 0.8064 - rmse: 0.9656 - smape: 1.4632 - val_ia: 0.2707 - val_loss: 0.7778 - val_mae: 0.7326 - val_rmse: 0.8757 - val_smape: 1.4950

Epoch 55/128

287/287 - 5s - 18ms/step - ia: 0.2825 - loss: 0.9382 - mae: 0.8071 - rmse: 0.9678 - smape: 1.4620 - val_ia: 0.2727 - val_loss: 0.7789 - val_mae: 0.7330 - val_rmse: 0.8761 - val_smape: 1.4885

Epoch 56/128

287/287 - 11s - 40ms/step - ia: 0.2849 - loss: 0.9353 - mae: 0.8048 - rmse: 0.9659 - smape: 1.4580 - val_ia: 0.2745 - val_loss: 0.7776 - val_mae: 0.7323 - val_rmse: 0.8754 - val_smape: 1.4825

Epoch 57/128

287/287 - 6s - 22ms/step - ia: 0.2844 - loss: 0.9299 - mae: 0.8044 - rmse: 0.9631 - smape: 1.4592 - val_ia: 0.2763 - val_loss: 0.7754 - val_mae: 0.7312 - val_rmse: 0.8741 - val_smape: 1.4765

Epoch 58/128

287/287 - 10s - 36ms/step - ia: 0.2866 - loss: 0.9268 - mae: 0.8022 - rmse: 0.9614 - smape: 1.4556 - val_ia: 0.2781 - val_loss: 0.7741 - val_mae: 0.7305 - val_rmse: 0.8734 - val_smape: 1.4705

Epoch 59/128

287/287 - 4s - 14ms/step - ia: 0.2894 - loss: 0.9187 - mae: 0.7996 - rmse: 0.9572 - smape: 1.4545 - val_ia: 0.2801 - val_loss: 0.7736 - val_mae: 0.7302 - val_rmse: 0.8731 - val_smape: 1.4643

Epoch 60/128

287/287 - 6s - 21ms/step - ia: 0.2912 - loss: 0.9161 - mae: 0.7993 - rmse: 0.9562 - smape: 1.4545 - val_ia: 0.2819 - val_loss: 0.7711 - val_mae: 0.7289 - val_rmse: 0.8716 - val_smape: 1.4586

Epoch 61/128

287/287 - 6s - 22ms/step - ia: 0.2913 - loss: 0.9162 - mae: 0.7986 - rmse: 0.9558 - smape: 1.4515 - val_ia: 0.2840 - val_loss: 0.7703 - val_mae: 0.7284 - val_rmse: 0.8712 - val_smape: 1.4526

Epoch 62/128

287/287 - 10s - 36ms/step - ia: 0.2951 - loss: 0.9128 - mae: 0.7974 - rmse: 0.9539 - smape: 1.4477 - val_ia: 0.2861 - val_loss: 0.7702 - val_mae: 0.7283 - val_rmse: 0.8710 - val_smape: 1.4468

Epoch 63/128

287/287 - 10s - 36ms/step - ia: 0.2975 - loss: 0.9074 - mae: 0.7934 - rmse: 0.9511 - smape: 1.4424 - val_ia: 0.2881 - val_loss: 0.7688 - val_mae: 0.7276 - val_rmse: 0.8702 - val_smape: 1.4410

Epoch 64/128

287/287 - 10s - 35ms/step - ia: 0.2988 - loss: 0.9056 - mae: 0.7944 - rmse: 0.9504 - smape: 1.4432 - val_ia: 0.2902 - val_loss: 0.7679 - val_mae: 0.7271 - val_rmse: 0.8697 - val_smape: 1.4355

Epoch 65/128

287/287 - 6s - 22ms/step - ia: 0.3015 - loss: 0.9028 - mae: 0.7927 - rmse: 0.9491 - smape: 1.4392 - val_ia: 0.2923 - val_loss: 0.7670 - val_mae: 0.7266 - val_rmse: 0.8691 - val_smape: 1.4303

Epoch 66/128

287/287 - 10s - 36ms/step - ia: 0.3047 - loss: 0.8941 - mae: 0.7897 - rmse: 0.9443 - smape: 1.4335 - val_ia: 0.2949 - val_loss: 0.7686 - val_mae: 0.7272 - val_rmse: 0.8698 - val_smape: 1.4252

Epoch 67/128

287/287 - 6s - 22ms/step - ia: 0.3095 - loss: 0.8877 - mae: 0.7859 - rmse: 0.9410 - smape: 1.4256 - val_ia: 0.2970 - val_loss: 0.7670 - val_mae: 0.7263 - val_rmse: 0.8689 - val_smape: 1.4199

Epoch 68/128

287/287 - 4s - 14ms/step - ia: 0.3079 - loss: 0.8907 - mae: 0.7877 - rmse: 0.9428 - smape: 1.4284 - val_ia: 0.2990 - val_loss: 0.7646 - val_mae: 0.7251 - val_rmse: 0.8676 - val_smape: 1.4148

Epoch 69/128

287/287 - 6s - 20ms/step - ia: 0.3127 - loss: 0.8776 - mae: 0.7823 - rmse: 0.9358 - smape: 1.4217 - val_ia: 0.3014 - val_loss: 0.7634 - val_mae: 0.7245 - val_rmse: 0.8668 - val_smape: 1.4092

Epoch 70/128

287/287 - 11s - 38ms/step - ia: 0.3132 - loss: 0.8825 - mae: 0.7844 - rmse: 0.9382 - smape: 1.4214 - val_ia: 0.3038 - val_loss: 0.7630 - val_mae: 0.7242 - val_rmse: 0.8665 - val_smape: 1.4043

Epoch 71/128

287/287 - 6s - 22ms/step - ia: 0.3161 - loss: 0.8763 - mae: 0.7815 - rmse: 0.9352 - smape: 1.4158 - val_ia: 0.3061 - val_loss: 0.7625 - val_mae: 0.7239 - val_rmse: 0.8661 - val_smape: 1.3996

Epoch 72/128

287/287 - 5s - 16ms/step - ia: 0.3166 - loss: 0.8704 - mae: 0.7800 - rmse: 0.9319 - smape: 1.4162 - val_ia: 0.3082 - val_loss: 0.7596 - val_mae: 0.7224 - val_rmse: 0.8645 - val_smape: 1.3942

Epoch 73/128

287/287 - 6s - 21ms/step - ia: 0.3225 - loss: 0.8620 - mae: 0.7761 - rmse: 0.9272 - smape: 1.4084 - val_ia: 0.3106 - val_loss: 0.7578 - val_mae: 0.7215 - val_rmse: 0.8634 - val_smape: 1.3889

Epoch 74/128

287/287 - 11s - 39ms/step - ia: 0.3250 - loss: 0.8610 - mae: 0.7759 - rmse: 0.9265 - smape: 1.4088 - val_ia: 0.3131 - val_loss: 0.7577 - val_mae: 0.7213 - val_rmse: 0.8632 - val_smape: 1.3843

Epoch 75/128

287/287 - 10s - 36ms/step - ia: 0.3277 - loss: 0.8564 - mae: 0.7740 - rmse: 0.9246 - smape: 1.4027 - val_ia: 0.3157 - val_loss: 0.7591 - val_mae: 0.7219 - val_rmse: 0.8639 - val_smape: 1.3803

Epoch 76/128

287/287 - 6s - 22ms/step - ia: 0.3311 - loss: 0.8528 - mae: 0.7711 - rmse: 0.9223 - smape: 1.3961 - val_ia: 0.3183 - val_loss: 0.7604 - val_mae: 0.7224 - val_rmse: 0.8645 - val_smape: 1.3763

Epoch 77/128

287/287 - 4s - 14ms/step - ia: 0.3319 - loss: 0.8516 - mae: 0.7707 - rmse: 0.9218 - smape: 1.3950 - val_ia: 0.3204 - val_loss: 0.7572 - val_mae: 0.7208 - val_rmse: 0.8626 - val_smape: 1.3713

Epoch 78/128

287/287 - 6s - 20ms/step - ia: 0.3361 - loss: 0.8469 - mae: 0.7690 - rmse: 0.9191 - smape: 1.3903 - val_ia: 0.3228 - val_loss: 0.7561 - val_mae: 0.7203 - val_rmse: 0.8619 - val_smape: 1.3671

Epoch 79/128

287/287 - 6s - 21ms/step - ia: 0.3382 - loss: 0.8448 - mae: 0.7674 - rmse: 0.9179 - smape: 1.3881 - val_ia: 0.3252 - val_loss: 0.7557 - val_mae: 0.7200 - val_rmse: 0.8616 - val_smape: 1.3631

Epoch 80/128

287/287 - 6s - 22ms/step - ia: 0.3413 - loss: 0.8386 - mae: 0.7646 - rmse: 0.9145 - smape: 1.3839 - val_ia: 0.3277 - val_loss: 0.7551 - val_mae: 0.7197 - val_rmse: 0.8611 - val_smape: 1.3586

Epoch 81/128

287/287 - 10s - 34ms/step - ia: 0.3451 - loss: 0.8348 - mae: 0.7626 - rmse: 0.9124 - smape: 1.3785 - val_ia: 0.3303 - val_loss: 0.7551 - val_mae: 0.7196 - val_rmse: 0.8610 - val_smape: 1.3547

Epoch 82/128

287/287 - 11s - 38ms/step - ia: 0.3480 - loss: 0.8289 - mae: 0.7601 - rmse: 0.9093 - smape: 1.3729 - val_ia: 0.3327 - val_loss: 0.7542 - val_mae: 0.7191 - val_rmse: 0.8603 - val_smape: 1.3505

Epoch 83/128

287/287 - 6s - 21ms/step - ia: 0.3489 - loss: 0.8284 - mae: 0.7597 - rmse: 0.9090 - smape: 1.3728 - val_ia: 0.3353 - val_loss: 0.7547 - val_mae: 0.7193 - val_rmse: 0.8605 - val_smape: 1.3468

Epoch 84/128

287/287 - 4s - 14ms/step - ia: 0.3526 - loss: 0.8201 - mae: 0.7564 - rmse: 0.9047 - smape: 1.3681 - val_ia: 0.3379 - val_loss: 0.7552 - val_mae: 0.7194 - val_rmse: 0.8606 - val_smape: 1.3431

Epoch 85/128

287/287 - 6s - 21ms/step - ia: 0.3551 - loss: 0.8165 - mae: 0.7558 - rmse: 0.9024 - smape: 1.3648 - val_ia: 0.3404 - val_loss: 0.7536 - val_mae: 0.7186 - val_rmse: 0.8596 - val_smape: 1.3388

Epoch 86/128

287/287 - 6s - 22ms/step - ia: 0.3589 - loss: 0.8144 - mae: 0.7538 - rmse: 0.9016 - smape: 1.3604 - val_ia: 0.3430 - val_loss: 0.7543 - val_mae: 0.7189 - val_rmse: 0.8598 - val_smape: 1.3358

Epoch 87/128

287/287 - 5s - 19ms/step - ia: 0.3643 - loss: 0.8075 - mae: 0.7502 - rmse: 0.8974 - smape: 1.3514 - val_ia: 0.3454 - val_loss: 0.7520 - val_mae: 0.7178 - val_rmse: 0.8584 - val_smape: 1.3318

Epoch 88/128

287/287 - 4s - 14ms/step - ia: 0.3668 - loss: 0.8029 - mae: 0.7473 - rmse: 0.8951 - smape: 1.3471 - val_ia: 0.3481 - val_loss: 0.7530 - val_mae: 0.7182 - val_rmse: 0.8588 - val_smape: 1.3290

Epoch 89/128

287/287 - 6s - 22ms/step - ia: 0.3686 - loss: 0.8009 - mae: 0.7475 - rmse: 0.8937 - smape: 1.3459 - val_ia: 0.3507 - val_loss: 0.7540 - val_mae: 0.7186 - val_rmse: 0.8592 - val_smape: 1.3262

Epoch 90/128

287/287 - 7s - 23ms/step - ia: 0.3714 - loss: 0.7979 - mae: 0.7454 - rmse: 0.8921 - smape: 1.3405 - val_ia: 0.3531 - val_loss: 0.7512 - val_mae: 0.7172 - val_rmse: 0.8575 - val_smape: 1.3224

Epoch 91/128

287/287 - 10s - 33ms/step - ia: 0.3728 - loss: 0.7944 - mae: 0.7445 - rmse: 0.8903 - smape: 1.3414 - val_ia: 0.3558 - val_loss: 0.7522 - val_mae: 0.7176 - val_rmse: 0.8578 - val_smape: 1.3198

Epoch 92/128

287/287 - 11s - 38ms/step - ia: 0.3795 - loss: 0.7859 - mae: 0.7399 - rmse: 0.8852 - smape: 1.3324 - val_ia: 0.3584 - val_loss: 0.7507 - val_mae: 0.7169 - val_rmse: 0.8568 - val_smape: 1.3163

Epoch 93/128

287/287 - 6s - 23ms/step - ia: 0.3826 - loss: 0.7795 - mae: 0.7364 - rmse: 0.8816 - smape: 1.3287 - val_ia: 0.3611 - val_loss: 0.7508 - val_mae: 0.7169 - val_rmse: 0.8567 - val_smape: 1.3132

Epoch 94/128

287/287 - 10s - 34ms/step - ia: 0.3860 - loss: 0.7773 - mae: 0.7358 - rmse: 0.8804 - smape: 1.3252 - val_ia: 0.3637 - val_loss: 0.7497 - val_mae: 0.7163 - val_rmse: 0.8559 - val_smape: 1.3102

Epoch 95/128

287/287 - 6s - 22ms/step - ia: 0.3897 - loss: 0.7722 - mae: 0.7332 - rmse: 0.8774 - smape: 1.3205 - val_ia: 0.3664 - val_loss: 0.7543 - val_mae: 0.7184 - val_rmse: 0.8582 - val_smape: 1.3093

Epoch 96/128

287/287 - 9s - 32ms/step - ia: 0.3919 - loss: 0.7687 - mae: 0.7317 - rmse: 0.8756 - smape: 1.3150 - val_ia: 0.3690 - val_loss: 0.7563 - val_mae: 0.7193 - val_rmse: 0.8591 - val_smape: 1.3074

Epoch 97/128

287/287 - 6s - 22ms/step - ia: 0.3963 - loss: 0.7619 - mae: 0.7272 - rmse: 0.8719 - smape: 1.3072 - val_ia: 0.3718 - val_loss: 0.7579 - val_mae: 0.7199 - val_rmse: 0.8598 - val_smape: 1.3056

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 11s - 40ms/step - ia: 0.7711 - loss: 0.2188 - mae: 0.3509 - rmse: 0.4490 - smape: 0.7131 - val_ia: 0.7137 - val_loss: 0.3119 - val_mae: 0.4157 - val_rmse: 0.5348 - val_smape: 0.7981

Epoch 2/128

287/287 - 3s - 11ms/step - ia: 0.8362 - loss: 0.1168 - mae: 0.2594 - rmse: 0.3402 - smape: 0.5872 - val_ia: 0.7463 - val_loss: 0.2297 - val_mae: 0.3631 - val_rmse: 0.4410 - val_smape: 0.7254

Epoch 3/128

287/287 - 5s - 19ms/step - ia: 0.8505 - loss: 0.0994 - mae: 0.2380 - rmse: 0.3137 - smape: 0.5506 - val_ia: 0.7438 - val_loss: 0.2348 - val_mae: 0.3719 - val_rmse: 0.4438 - val_smape: 0.7362

Epoch 4/128

287/287 - 5s - 18ms/step - ia: 0.8571 - loss: 0.0915 - mae: 0.2286 - rmse: 0.3010 - smape: 0.5283 - val_ia: 0.7773 - val_loss: 0.1453 - val_mae: 0.3060 - val_rmse: 0.3575 - val_smape: 0.6774

Epoch 5/128

287/287 - 3s - 11ms/step - ia: 0.8635 - loss: 0.0841 - mae: 0.2186 - rmse: 0.2887 - smape: 0.5091 - val_ia: 0.7768 - val_loss: 0.1725 - val_mae: 0.3164 - val_rmse: 0.3910 - val_smape: 0.6732

Epoch 6/128

287/287 - 3s - 11ms/step - ia: 0.8648 - loss: 0.0828 - mae: 0.2167 - rmse: 0.2866 - smape: 0.5060 - val_ia: 0.7708 - val_loss: 0.1796 - val_mae: 0.3267 - val_rmse: 0.3949 - val_smape: 0.6930

Epoch 7/128

287/287 - 5s - 18ms/step - ia: 0.8690 - loss: 0.0777 - mae: 0.2106 - rmse: 0.2775 - smape: 0.4919 - val_ia: 0.7557 - val_loss: 0.1835 - val_mae: 0.3411 - val_rmse: 0.4075 - val_smape: 0.7115

Epoch 8/128

287/287 - 3s - 11ms/step - ia: 0.8715 - loss: 0.0750 - mae: 0.2067 - rmse: 0.2727 - smape: 0.4853 - val_ia: 0.7321 - val_loss: 0.2722 - val_mae: 0.3813 - val_rmse: 0.4970 - val_smape: 0.7422

Epoch 9/128

287/287 - 3s - 11ms/step - ia: 0.8741 - loss: 0.0721 - mae: 0.2026 - rmse: 0.2675 - smape: 0.4761 - val_ia: 0.7504 - val_loss: 0.2350 - val_mae: 0.3542 - val_rmse: 0.4411 - val_smape: 0.7186

Epoch 10/128

287/287 - 3s - 11ms/step - ia: 0.8762 - loss: 0.0698 - mae: 0.1994 - rmse: 0.2630 - smape: 0.4710 - val_ia: 0.7639 - val_loss: 0.1906 - val_mae: 0.3374 - val_rmse: 0.4048 - val_smape: 0.6966

Epoch 11/128

287/287 - 5s - 18ms/step - ia: 0.8747 - loss: 0.0713 - mae: 0.2016 - rmse: 0.2658 - smape: 0.4737 - val_ia: 0.7835 - val_loss: 0.1659 - val_mae: 0.3080 - val_rmse: 0.3820 - val_smape: 0.6599

Epoch 12/128

287/287 - 5s - 18ms/step - ia: 0.8783 - loss: 0.0676 - mae: 0.1960 - rmse: 0.2589 - smape: 0.4631 - val_ia: 0.7819 - val_loss: 0.1628 - val_mae: 0.3119 - val_rmse: 0.3616 - val_smape: 0.6796

Epoch 13/128

287/287 - 3s - 11ms/step - ia: 0.8768 - loss: 0.0697 - mae: 0.1985 - rmse: 0.2629 - smape: 0.4654 - val_ia: 0.7520 - val_loss: 0.2199 - val_mae: 0.3595 - val_rmse: 0.4353 - val_smape: 0.7122

Epoch 14/128

287/287 - 3s - 11ms/step - ia: 0.8809 - loss: 0.0648 - mae: 0.1922 - rmse: 0.2534 - smape: 0.4533 - val_ia: 0.7535 - val_loss: 0.2243 - val_mae: 0.3557 - val_rmse: 0.4413 - val_smape: 0.7249

Epoch 15/128

287/287 - 3s - 11ms/step - ia: 0.1010 - loss: 5829240029184.0000 - mae: 848854.5000 - rmse: 1532930.5000 - smape: 1.8024 - val_ia: 3.9928e-07 - val_loss: 11027801440256.0000 - val_mae: 2018302.7500 - val_rmse: 3172041.2500 - val_smape: 2.0000

Epoch 16/128

287/287 - 3s - 11ms/step - ia: 2.3380e-05 - loss: 1886251909120.0000 - mae: 414028.5625 - rmse: 712453.2500 - smape: 1.9995 - val_ia: 1.3822e-04 - val_loss: 72887760.0000 - val_mae: 5007.6592 - val_rmse: 8251.6562 - val_smape: 1.9971

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 7.7901e-04 - loss: 36109568.0000 - mae: 2457.4854 - rmse: 4453.9189 - smape: 1.9865 - val_ia: 0.0036 - val_loss: 111503.5391 - val_mae: 195.2915 - val_rmse: 322.5835 - val_smape: 1.9540

Epoch 18/128

287/287 - 3s - 11ms/step - ia: 0.0283 - loss: 40922.2969 - mae: 76.3053 - rmse: 140.9899 - smape: 1.8415 - val_ia: 0.1190 - val_loss: 71.8641 - val_mae: 5.0802 - val_rmse: 8.0945 - val_smape: 1.6512

Epoch 19/128

287/287 - 3s - 11ms/step - ia: 0.2329 - loss: 22.8786 - mae: 2.7571 - rmse: 3.9039 - smape: 1.5089 - val_ia: 0.2522 - val_loss: 5.1205 - val_mae: 2.0210 - val_rmse: 2.2388 - val_smape: 1.5780

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 55s 341ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 58%|█████▊    | 7/12 [2:35:50<1:14:55, 899.04s/trial, best loss: 0.212949463855241]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4584/4584 - 83s - 18ms/step - ia: 0.7665 - loss: 0.1870 - mae: 0.3252 - rmse: 0.4052 - smape: 0.6937 - val_ia: 0.2257 - val_loss: 0.2998 - val_mae: 0.4212 - val_rmse: 0.4395 - val_smape: 0.8311

Epoch 2/128

4584/4584 - 76s - 17ms/step - ia: 0.8245 - loss: 0.1087 - mae: 0.2475 - rmse: 0.3126 - smape: 0.5811 - val_ia: 0.2363 - val_loss: 0.2638 - val_mae: 0.4017 - val_rmse: 0.4189 - val_smape: 0.8311

Epoch 3/128

4584/4584 - 75s - 16ms/step - ia: 0.8414 - loss: 0.0908 - mae: 0.2257 - rmse: 0.2849 - smape: 0.5335 - val_ia: 0.2525 - val_loss: 0.2142 - val_mae: 0.3591 - val_rmse: 0.3750 - val_smape: 0.7671

Epoch 4/128

4584/4584 - 37s - 8ms/step - ia: 0.8508 - loss: 0.0808 - mae: 0.2125 - rmse: 0.2684 - smape: 0.5066 - val_ia: 0.2851 - val_loss: 0.1528 - val_mae: 0.2996 - val_rmse: 0.3150 - val_smape: 0.6717

Epoch 5/128

4584/4584 - 51s - 11ms/step - ia: 0.8556 - loss: 0.0753 - mae: 0.2053 - rmse: 0.2597 - smape: 0.4905 - val_ia: 0.2806 - val_loss: 0.1653 - val_mae: 0.3132 - val_rmse: 0.3278 - val_smape: 0.6854

Epoch 6/128

4584/4584 - 82s - 18ms/step - ia: 0.8608 - loss: 0.0710 - mae: 0.1989 - rmse: 0.2516 - smape: 0.4754 - val_ia: 0.2593 - val_loss: 0.1992 - val_mae: 0.3454 - val_rmse: 0.3627 - val_smape: 0.7183

Epoch 7/128

4584/4584 - 83s - 18ms/step - ia: 0.8633 - loss: 0.0683 - mae: 0.1951 - rmse: 0.2470 - smape: 0.4678 - val_ia: 0.2582 - val_loss: 0.2078 - val_mae: 0.3475 - val_rmse: 0.3657 - val_smape: 0.7494

Epoch 8/128

4584/4584 - 81s - 18ms/step - ia: 0.8673 - loss: 0.0653 - mae: 0.1900 - rmse: 0.2411 - smape: 0.4552 - val_ia: 0.2547 - val_loss: 0.2171 - val_mae: 0.3510 - val_rmse: 0.3702 - val_smape: 0.7751

Epoch 9/128

4584/4584 - 82s - 18ms/step - ia: 0.8680 - loss: 0.0644 - mae: 0.1890 - rmse: 0.2396 - smape: 0.4544 - val_ia: 0.2620 - val_loss: 0.2326 - val_mae: 0.3611 - val_rmse: 0.3819 - val_smape: 0.7583

Epoch 10/128

4584/4584 - 80s - 17ms/step - ia: 0.8711 - loss: 0.0613 - mae: 0.1847 - rmse: 0.2336 - smape: 0.4485 - val_ia: 0.2803 - val_loss: 0.1955 - val_mae: 0.3221 - val_rmse: 0.3453 - val_smape: 0.7202

Epoch 11/128

4584/4584 - 52s - 11ms/step - ia: 0.8734 - loss: 0.0589 - mae: 0.1817 - rmse: 0.2294 - smape: 0.4419 - val_ia: 0.2686 - val_loss: 0.2297 - val_mae: 0.3507 - val_rmse: 0.3722 - val_smape: 0.7665

Epoch 12/128

4584/4584 - 51s - 11ms/step - ia: 0.8748 - loss: 0.0577 - mae: 0.1791 - rmse: 0.2269 - smape: 0.4375 - val_ia: 0.2656 - val_loss: 0.2347 - val_mae: 0.3593 - val_rmse: 0.3792 - val_smape: 0.7713

Epoch 13/128

4584/4584 - 79s - 17ms/step - ia: 0.8768 - loss: 0.0560 - mae: 0.1768 - rmse: 0.2237 - smape: 0.4289 - val_ia: 0.2716 - val_loss: 0.1899 - val_mae: 0.3283 - val_rmse: 0.3497 - val_smape: 0.7033

Epoch 14/128

4584/4584 - 50s - 11ms/step - ia: 0.8767 - loss: 0.0564 - mae: 0.1765 - rmse: 0.2237 - smape: 0.4299 - val_ia: 0.2622 - val_loss: 0.2244 - val_mae: 0.3530 - val_rmse: 0.3734 - val_smape: 0.7492

Epoch 15/128

4584/4584 - 54s - 12ms/step - ia: 0.8797 - loss: 0.0533 - mae: 0.1728 - rmse: 0.2184 - smape: 0.4243 - val_ia: 0.2613 - val_loss: 0.1988 - val_mae: 0.3364 - val_rmse: 0.3581 - val_smape: 0.7305

Epoch 16/128

4584/4584 - 48s - 11ms/step - ia: 0.8790 - loss: 0.0533 - mae: 0.1726 - rmse: 0.2184 - smape: 0.4219 - val_ia: 0.2610 - val_loss: 0.2410 - val_mae: 0.3610 - val_rmse: 0.3844 - val_smape: 0.7671

Epoch 17/128

4584/4584 - 85s - 19ms/step - ia: 0.8808 - loss: 0.0522 - mae: 0.1712 - rmse: 0.2162 - smape: 0.4196 - val_ia: 0.2530 - val_loss: 0.2754 - val_mae: 0.3859 - val_rmse: 0.4102 - val_smape: 0.7817

Epoch 18/128

4584/4584 - 53s - 12ms/step - ia: 0.8802 - loss: 0.0525 - mae: 0.1709 - rmse: 0.2161 - smape: 0.4164 - val_ia: 0.2527 - val_loss: 0.2536 - val_mae: 0.3820 - val_rmse: 0.4032 - val_smape: 0.7971

Epoch 19/128

4584/4584 - 47s - 10ms/step - ia: 0.8831 - loss: 0.0507 - mae: 0.1680 - rmse: 0.2125 - smape: 0.4116 - val_ia: 0.2495 - val_loss: 0.2659 - val_mae: 0.3851 - val_rmse: 0.4069 - val_smape: 0.7764

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:35 1s/step
  4/163 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 74/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
145/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 67%|██████▋   | 8/12 [2:56:41<1:07:24, 1011.24s/trial, best loss: 0.212949463855241]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 8s - 29ms/step - ia: 0.4772 - loss: 0.8225 - mae: 0.7201 - rmse: 0.8910 - smape: 1.1964 - val_ia: 0.4367 - val_loss: 1.1907 - val_mae: 0.9154 - val_rmse: 1.0490 - val_smape: 1.3393

Epoch 2/128

287/287 - 4s - 13ms/step - ia: 0.6349 - loss: 0.4453 - mae: 0.5302 - rmse: 0.6650 - smape: 0.9467 - val_ia: 0.5164 - val_loss: 0.8425 - val_mae: 0.7489 - val_rmse: 0.8701 - val_smape: 1.1871

Epoch 3/128

287/287 - 2s - 6ms/step - ia: 0.6855 - loss: 0.3547 - mae: 0.4728 - rmse: 0.5943 - smape: 0.8591 - val_ia: 0.5442 - val_loss: 0.7036 - val_mae: 0.6780 - val_rmse: 0.7937 - val_smape: 1.1331

Epoch 4/128

287/287 - 2s - 6ms/step - ia: 0.7090 - loss: 0.3150 - mae: 0.4427 - rmse: 0.5601 - smape: 0.8176 - val_ia: 0.5653 - val_loss: 0.6121 - val_mae: 0.6318 - val_rmse: 0.7343 - val_smape: 1.0703

Epoch 5/128

287/287 - 2s - 6ms/step - ia: 0.7252 - loss: 0.2873 - mae: 0.4205 - rmse: 0.5350 - smape: 0.7869 - val_ia: 0.5879 - val_loss: 0.4912 - val_mae: 0.5723 - val_rmse: 0.6635 - val_smape: 1.0138

Epoch 6/128

287/287 - 2s - 6ms/step - ia: 0.7327 - loss: 0.2718 - mae: 0.4090 - rmse: 0.5200 - smape: 0.7777 - val_ia: 0.6050 - val_loss: 0.4590 - val_mae: 0.5571 - val_rmse: 0.6444 - val_smape: 0.9788

Epoch 7/128

287/287 - 2s - 6ms/step - ia: 0.7375 - loss: 0.2624 - mae: 0.4004 - rmse: 0.5112 - smape: 0.7755 - val_ia: 0.6149 - val_loss: 0.4005 - val_mae: 0.5232 - val_rmse: 0.6089 - val_smape: 0.9493

Epoch 8/128

287/287 - 3s - 9ms/step - ia: 0.7419 - loss: 0.2545 - mae: 0.3936 - rmse: 0.5035 - smape: 0.7701 - val_ia: 0.6536 - val_loss: 0.3390 - val_mae: 0.4790 - val_rmse: 0.5568 - val_smape: 0.8833

Epoch 9/128

287/287 - 3s - 9ms/step - ia: 0.7469 - loss: 0.2445 - mae: 0.3861 - rmse: 0.4932 - smape: 0.7639 - val_ia: 0.6522 - val_loss: 0.3399 - val_mae: 0.4795 - val_rmse: 0.5591 - val_smape: 0.8852

Epoch 10/128

287/287 - 2s - 6ms/step - ia: 0.7523 - loss: 0.2354 - mae: 0.3782 - rmse: 0.4838 - smape: 0.7526 - val_ia: 0.6609 - val_loss: 0.3170 - val_mae: 0.4601 - val_rmse: 0.5479 - val_smape: 0.8735

Epoch 11/128

287/287 - 2s - 6ms/step - ia: 0.7600 - loss: 0.2233 - mae: 0.3673 - rmse: 0.4711 - smape: 0.7387 - val_ia: 0.6716 - val_loss: 0.3135 - val_mae: 0.4525 - val_rmse: 0.5426 - val_smape: 0.8722

Epoch 12/128

287/287 - 2s - 6ms/step - ia: 0.7650 - loss: 0.2150 - mae: 0.3599 - rmse: 0.4625 - smape: 0.7320 - val_ia: 0.6903 - val_loss: 0.2658 - val_mae: 0.4196 - val_rmse: 0.4976 - val_smape: 0.8487

Epoch 13/128

287/287 - 2s - 6ms/step - ia: 0.7688 - loss: 0.2064 - mae: 0.3537 - rmse: 0.4531 - smape: 0.7275 - val_ia: 0.7140 - val_loss: 0.2316 - val_mae: 0.3904 - val_rmse: 0.4628 - val_smape: 0.8151

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.7734 - loss: 0.1978 - mae: 0.3468 - rmse: 0.4434 - smape: 0.7222 - val_ia: 0.7448 - val_loss: 0.1999 - val_mae: 0.3577 - val_rmse: 0.4316 - val_smape: 0.7651

Epoch 15/128

287/287 - 2s - 7ms/step - ia: 0.7755 - loss: 0.1955 - mae: 0.3438 - rmse: 0.4408 - smape: 0.7187 - val_ia: 0.7425 - val_loss: 0.1862 - val_mae: 0.3507 - val_rmse: 0.4119 - val_smape: 0.7737

Epoch 16/128

287/287 - 2s - 6ms/step - ia: 0.7802 - loss: 0.1875 - mae: 0.3371 - rmse: 0.4318 - smape: 0.7087 - val_ia: 0.7460 - val_loss: 0.1923 - val_mae: 0.3545 - val_rmse: 0.4195 - val_smape: 0.7782

Epoch 17/128

287/287 - 2s - 6ms/step - ia: 0.7843 - loss: 0.1829 - mae: 0.3315 - rmse: 0.4266 - smape: 0.7017 - val_ia: 0.7406 - val_loss: 0.1993 - val_mae: 0.3595 - val_rmse: 0.4233 - val_smape: 0.7899

Epoch 18/128

287/287 - 2s - 6ms/step - ia: 0.7876 - loss: 0.1776 - mae: 0.3262 - rmse: 0.4203 - smape: 0.6973 - val_ia: 0.7453 - val_loss: 0.1779 - val_mae: 0.3485 - val_rmse: 0.4019 - val_smape: 0.7799

Epoch 19/128

287/287 - 2s - 6ms/step - ia: 0.7878 - loss: 0.1771 - mae: 0.3256 - rmse: 0.4197 - smape: 0.6921 - val_ia: 0.7308 - val_loss: 0.2101 - val_mae: 0.3703 - val_rmse: 0.4419 - val_smape: 0.8025

Epoch 20/128

287/287 - 2s - 6ms/step - ia: 0.7919 - loss: 0.1723 - mae: 0.3201 - rmse: 0.4140 - smape: 0.6878 - val_ia: 0.7408 - val_loss: 0.1931 - val_mae: 0.3555 - val_rmse: 0.4174 - val_smape: 0.7913

Epoch 21/128

287/287 - 2s - 7ms/step - ia: 0.7933 - loss: 0.1699 - mae: 0.3178 - rmse: 0.4109 - smape: 0.6836 - val_ia: 0.7504 - val_loss: 0.1747 - val_mae: 0.3438 - val_rmse: 0.4014 - val_smape: 0.7718

Epoch 22/128

287/287 - 2s - 9ms/step - ia: 0.7934 - loss: 0.1695 - mae: 0.3180 - rmse: 0.4107 - smape: 0.6817 - val_ia: 0.7446 - val_loss: 0.1852 - val_mae: 0.3519 - val_rmse: 0.4132 - val_smape: 0.7777

Epoch 23/128

287/287 - 2s - 6ms/step - ia: 0.7968 - loss: 0.1654 - mae: 0.3127 - rmse: 0.4054 - smape: 0.6739 - val_ia: 0.7480 - val_loss: 0.1818 - val_mae: 0.3503 - val_rmse: 0.4099 - val_smape: 0.7755

Epoch 24/128

287/287 - 2s - 7ms/step - ia: 0.7974 - loss: 0.1640 - mae: 0.3117 - rmse: 0.4040 - smape: 0.6735 - val_ia: 0.7471 - val_loss: 0.1860 - val_mae: 0.3496 - val_rmse: 0.4103 - val_smape: 0.7770

Epoch 25/128

287/287 - 2s - 8ms/step - ia: 0.8004 - loss: 0.1605 - mae: 0.3075 - rmse: 0.3994 - smape: 0.6663 - val_ia: 0.7433 - val_loss: 0.1942 - val_mae: 0.3584 - val_rmse: 0.4212 - val_smape: 0.7835

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.8018 - loss: 0.1588 - mae: 0.3054 - rmse: 0.3974 - smape: 0.6624 - val_ia: 0.7573 - val_loss: 0.1694 - val_mae: 0.3391 - val_rmse: 0.3940 - val_smape: 0.7616

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.8042 - loss: 0.1551 - mae: 0.3020 - rmse: 0.3926 - smape: 0.6550 - val_ia: 0.7492 - val_loss: 0.1784 - val_mae: 0.3461 - val_rmse: 0.4081 - val_smape: 0.7679

Epoch 28/128

287/287 - 1s - 4ms/step - ia: 0.8031 - loss: 0.1564 - mae: 0.3037 - rmse: 0.3944 - smape: 0.6558 - val_ia: 0.7586 - val_loss: 0.1769 - val_mae: 0.3432 - val_rmse: 0.4009 - val_smape: 0.7626

Epoch 29/128

287/287 - 1s - 4ms/step - ia: 0.8069 - loss: 0.1520 - mae: 0.2982 - rmse: 0.3888 - smape: 0.6483 - val_ia: 0.7521 - val_loss: 0.1852 - val_mae: 0.3459 - val_rmse: 0.4113 - val_smape: 0.7676

Epoch 30/128

287/287 - 1s - 4ms/step - ia: 0.8063 - loss: 0.1527 - mae: 0.2992 - rmse: 0.3896 - smape: 0.6486 - val_ia: 0.7515 - val_loss: 0.1896 - val_mae: 0.3525 - val_rmse: 0.4219 - val_smape: 0.7611

Epoch 31/128

287/287 - 1s - 4ms/step - ia: 0.8075 - loss: 0.1518 - mae: 0.2976 - rmse: 0.3886 - smape: 0.6465 - val_ia: 0.7543 - val_loss: 0.1792 - val_mae: 0.3459 - val_rmse: 0.4098 - val_smape: 0.7669

Epoch 32/128

287/287 - 1s - 4ms/step - ia: 0.8066 - loss: 0.1527 - mae: 0.2991 - rmse: 0.3897 - smape: 0.6465 - val_ia: 0.7575 - val_loss: 0.1723 - val_mae: 0.3366 - val_rmse: 0.4013 - val_smape: 0.7584

Epoch 33/128

287/287 - 1s - 4ms/step - ia: 0.8086 - loss: 0.1498 - mae: 0.2958 - rmse: 0.3860 - smape: 0.6408 - val_ia: 0.7680 - val_loss: 0.1621 - val_mae: 0.3280 - val_rmse: 0.3852 - val_smape: 0.7433

Epoch 34/128

287/287 - 1s - 4ms/step - ia: 0.8093 - loss: 0.1490 - mae: 0.2953 - rmse: 0.3849 - smape: 0.6425 - val_ia: 0.7665 - val_loss: 0.1627 - val_mae: 0.3272 - val_rmse: 0.3892 - val_smape: 0.7399

Epoch 35/128

287/287 - 1s - 4ms/step - ia: 0.8092 - loss: 0.1492 - mae: 0.2952 - rmse: 0.3849 - smape: 0.6419 - val_ia: 0.7669 - val_loss: 0.1623 - val_mae: 0.3247 - val_rmse: 0.3862 - val_smape: 0.7418

Epoch 36/128

287/287 - 1s - 4ms/step - ia: 0.8087 - loss: 0.1500 - mae: 0.2965 - rmse: 0.3862 - smape: 0.6407 - val_ia: 0.7664 - val_loss: 0.1598 - val_mae: 0.3236 - val_rmse: 0.3855 - val_smape: 0.7384

Epoch 37/128

287/287 - 1s - 4ms/step - ia: 0.8090 - loss: 0.1494 - mae: 0.2957 - rmse: 0.3854 - smape: 0.6397 - val_ia: 0.7632 - val_loss: 0.1616 - val_mae: 0.3273 - val_rmse: 0.3885 - val_smape: 0.7447

Epoch 38/128

287/287 - 1s - 4ms/step - ia: 0.8088 - loss: 0.1487 - mae: 0.2960 - rmse: 0.3847 - smape: 0.6403 - val_ia: 0.7716 - val_loss: 0.1637 - val_mae: 0.3268 - val_rmse: 0.3917 - val_smape: 0.7296

Epoch 39/128

287/287 - 1s - 5ms/step - ia: 0.8104 - loss: 0.1473 - mae: 0.2940 - rmse: 0.3826 - smape: 0.6375 - val_ia: 0.7881 - val_loss: 0.1351 - val_mae: 0.3001 - val_rmse: 0.3549 - val_smape: 0.6994

Epoch 40/128

287/287 - 1s - 4ms/step - ia: 0.8097 - loss: 0.1484 - mae: 0.2945 - rmse: 0.3841 - smape: 0.6404 - val_ia: 0.7824 - val_loss: 0.1487 - val_mae: 0.3113 - val_rmse: 0.3721 - val_smape: 0.7104

Epoch 41/128

287/287 - 1s - 4ms/step - ia: 0.8107 - loss: 0.1474 - mae: 0.2934 - rmse: 0.3827 - smape: 0.6353 - val_ia: 0.7717 - val_loss: 0.1570 - val_mae: 0.3216 - val_rmse: 0.3834 - val_smape: 0.7226

Epoch 42/128

287/287 - 1s - 4ms/step - ia: 0.8102 - loss: 0.1485 - mae: 0.2940 - rmse: 0.3841 - smape: 0.6352 - val_ia: 0.7717 - val_loss: 0.1652 - val_mae: 0.3272 - val_rmse: 0.3947 - val_smape: 0.7230

Epoch 43/128

287/287 - 2s - 7ms/step - ia: 0.8121 - loss: 0.1453 - mae: 0.2912 - rmse: 0.3801 - smape: 0.6326 - val_ia: 0.7745 - val_loss: 0.1576 - val_mae: 0.3192 - val_rmse: 0.3856 - val_smape: 0.7218

Epoch 44/128

287/287 - 2s - 6ms/step - ia: 0.8110 - loss: 0.1467 - mae: 0.2928 - rmse: 0.3820 - smape: 0.6363 - val_ia: 0.7786 - val_loss: 0.1532 - val_mae: 0.3160 - val_rmse: 0.3771 - val_smape: 0.7128

Epoch 45/128

287/287 - 2s - 6ms/step - ia: 0.8112 - loss: 0.1462 - mae: 0.2928 - rmse: 0.3812 - smape: 0.6339 - val_ia: 0.7779 - val_loss: 0.1605 - val_mae: 0.3177 - val_rmse: 0.3869 - val_smape: 0.7090

Epoch 46/128

287/287 - 2s - 6ms/step - ia: 0.8123 - loss: 0.1452 - mae: 0.2912 - rmse: 0.3799 - smape: 0.6308 - val_ia: 0.7838 - val_loss: 0.1513 - val_mae: 0.3098 - val_rmse: 0.3738 - val_smape: 0.7036

Epoch 47/128

287/287 - 3s - 9ms/step - ia: 0.8121 - loss: 0.1455 - mae: 0.2913 - rmse: 0.3803 - smape: 0.6295 - val_ia: 0.7868 - val_loss: 0.1420 - val_mae: 0.3050 - val_rmse: 0.3630 - val_smape: 0.6941

Epoch 48/128

287/287 - 2s - 6ms/step - ia: 0.8125 - loss: 0.1440 - mae: 0.2909 - rmse: 0.3785 - smape: 0.6293 - val_ia: 0.7857 - val_loss: 0.1471 - val_mae: 0.3056 - val_rmse: 0.3669 - val_smape: 0.6969

Epoch 49/128

287/287 - 2s - 6ms/step - ia: 0.8127 - loss: 0.1439 - mae: 0.2904 - rmse: 0.3785 - smape: 0.6274 - val_ia: 0.7892 - val_loss: 0.1405 - val_mae: 0.2972 - val_rmse: 0.3570 - val_smape: 0.6801

Epoch 50/128

287/287 - 2s - 6ms/step - ia: 0.8131 - loss: 0.1437 - mae: 0.2900 - rmse: 0.3781 - smape: 0.6275 - val_ia: 0.7670 - val_loss: 0.1772 - val_mae: 0.3325 - val_rmse: 0.4072 - val_smape: 0.7216

Epoch 51/128

287/287 - 3s - 9ms/step - ia: 0.8122 - loss: 0.1443 - mae: 0.2916 - rmse: 0.3787 - smape: 0.6317 - val_ia: 0.7791 - val_loss: 0.1524 - val_mae: 0.3113 - val_rmse: 0.3746 - val_smape: 0.6993

Epoch 52/128

287/287 - 3s - 9ms/step - ia: 0.8129 - loss: 0.1439 - mae: 0.2903 - rmse: 0.3783 - smape: 0.6252 - val_ia: 0.7771 - val_loss: 0.1658 - val_mae: 0.3172 - val_rmse: 0.3909 - val_smape: 0.7037

Epoch 53/128

287/287 - 1s - 5ms/step - ia: 0.8134 - loss: 0.1434 - mae: 0.2898 - rmse: 0.3774 - smape: 0.6250 - val_ia: 0.7791 - val_loss: 0.1642 - val_mae: 0.3171 - val_rmse: 0.3912 - val_smape: 0.6992

Epoch 54/128

287/287 - 2s - 6ms/step - ia: 0.8141 - loss: 0.1425 - mae: 0.2889 - rmse: 0.3764 - smape: 0.6238 - val_ia: 0.7770 - val_loss: 0.1732 - val_mae: 0.3212 - val_rmse: 0.4035 - val_smape: 0.6963

Epoch 54: early stopping

Restoring model weights from the end of the best epoch: 39.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:10 433ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 85/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 75%|███████▌  | 9/12 [2:58:23<36:20, 726.96s/trial, best loss: 0.18750297233085142]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 43s - 19ms/step - ia: 0.3308 - loss: 0.9708 - mae: 0.8133 - rmse: 0.9696 - smape: 1.4055 - val_ia: 0.1860 - val_loss: 0.7861 - val_mae: 0.7326 - val_rmse: 0.7648 - val_smape: 1.2817

Epoch 2/128

2292/2292 - 38s - 17ms/step - ia: 0.5658 - loss: 0.5419 - mae: 0.5930 - rmse: 0.7247 - smape: 1.0217 - val_ia: 0.1778 - val_loss: 1.1886 - val_mae: 0.9174 - val_rmse: 0.9506 - val_smape: 1.3568

Epoch 3/128

2292/2292 - 41s - 18ms/step - ia: 0.6303 - loss: 0.4346 - mae: 0.5259 - rmse: 0.6491 - smape: 0.9014 - val_ia: 0.1791 - val_loss: 1.1072 - val_mae: 0.8801 - val_rmse: 0.9120 - val_smape: 1.3335

Epoch 4/128

2292/2292 - 41s - 18ms/step - ia: 0.6593 - loss: 0.3836 - mae: 0.4918 - rmse: 0.6096 - smape: 0.8442 - val_ia: 0.1822 - val_loss: 1.0582 - val_mae: 0.8602 - val_rmse: 0.8912 - val_smape: 1.3203

Epoch 5/128

2292/2292 - 29s - 12ms/step - ia: 0.6798 - loss: 0.3485 - mae: 0.4670 - rmse: 0.5807 - smape: 0.8054 - val_ia: 0.1941 - val_loss: 0.8433 - val_mae: 0.7490 - val_rmse: 0.7813 - val_smape: 1.2217

Epoch 6/128

2292/2292 - 25s - 11ms/step - ia: 0.6938 - loss: 0.3250 - mae: 0.4486 - rmse: 0.5603 - smape: 0.7848 - val_ia: 0.2001 - val_loss: 0.7723 - val_mae: 0.7086 - val_rmse: 0.7412 - val_smape: 1.1860

Epoch 7/128

2292/2292 - 47s - 21ms/step - ia: 0.7069 - loss: 0.3044 - mae: 0.4325 - rmse: 0.5420 - smape: 0.7678 - val_ia: 0.2135 - val_loss: 0.6803 - val_mae: 0.6515 - val_rmse: 0.6848 - val_smape: 1.1273

Epoch 8/128

2292/2292 - 30s - 13ms/step - ia: 0.7177 - loss: 0.2844 - mae: 0.4171 - rmse: 0.5243 - smape: 0.7570 - val_ia: 0.2269 - val_loss: 0.6448 - val_mae: 0.6257 - val_rmse: 0.6593 - val_smape: 1.0889

Epoch 9/128

2292/2292 - 30s - 13ms/step - ia: 0.7267 - loss: 0.2673 - mae: 0.4036 - rmse: 0.5076 - smape: 0.7495 - val_ia: 0.2361 - val_loss: 0.5728 - val_mae: 0.5902 - val_rmse: 0.6226 - val_smape: 1.0472

Epoch 10/128

2292/2292 - 30s - 13ms/step - ia: 0.7381 - loss: 0.2485 - mae: 0.3876 - rmse: 0.4888 - smape: 0.7447 - val_ia: 0.2429 - val_loss: 0.5892 - val_mae: 0.5938 - val_rmse: 0.6258 - val_smape: 1.0463

Epoch 11/128

2292/2292 - 41s - 18ms/step - ia: 0.7473 - loss: 0.2321 - mae: 0.3735 - rmse: 0.4721 - smape: 0.7369 - val_ia: 0.2623 - val_loss: 0.4589 - val_mae: 0.5266 - val_rmse: 0.5556 - val_smape: 0.9687

Epoch 12/128

2292/2292 - 29s - 13ms/step - ia: 0.7549 - loss: 0.2179 - mae: 0.3618 - rmse: 0.4576 - smape: 0.7279 - val_ia: 0.2662 - val_loss: 0.4605 - val_mae: 0.5258 - val_rmse: 0.5553 - val_smape: 0.9636

Epoch 13/128

2292/2292 - 42s - 18ms/step - ia: 0.7602 - loss: 0.2083 - mae: 0.3536 - rmse: 0.4478 - smape: 0.7212 - val_ia: 0.2753 - val_loss: 0.3942 - val_mae: 0.4889 - val_rmse: 0.5175 - val_smape: 0.9355

Epoch 14/128

2292/2292 - 30s - 13ms/step - ia: 0.7657 - loss: 0.1991 - mae: 0.3458 - rmse: 0.4374 - smape: 0.7166 - val_ia: 0.2857 - val_loss: 0.3395 - val_mae: 0.4569 - val_rmse: 0.4855 - val_smape: 0.9053

Epoch 15/128

2292/2292 - 31s - 13ms/step - ia: 0.7719 - loss: 0.1893 - mae: 0.3364 - rmse: 0.4265 - smape: 0.7047 - val_ia: 0.2900 - val_loss: 0.3545 - val_mae: 0.4589 - val_rmse: 0.4898 - val_smape: 0.8788

Epoch 16/128

2292/2292 - 31s - 13ms/step - ia: 0.7792 - loss: 0.1800 - mae: 0.3266 - rmse: 0.4150 - smape: 0.7000 - val_ia: 0.2891 - val_loss: 0.3833 - val_mae: 0.4679 - val_rmse: 0.5009 - val_smape: 0.8759

Epoch 17/128

2292/2292 - 30s - 13ms/step - ia: 0.7856 - loss: 0.1708 - mae: 0.3178 - rmse: 0.4044 - smape: 0.6890 - val_ia: 0.2885 - val_loss: 0.4096 - val_mae: 0.4735 - val_rmse: 0.5091 - val_smape: 0.8674

Epoch 18/128

2292/2292 - 39s - 17ms/step - ia: 0.7947 - loss: 0.1590 - mae: 0.3047 - rmse: 0.3898 - smape: 0.6749 - val_ia: 0.2958 - val_loss: 0.3717 - val_mae: 0.4520 - val_rmse: 0.4898 - val_smape: 0.8460

Epoch 19/128

2292/2292 - 25s - 11ms/step - ia: 0.8008 - loss: 0.1508 - mae: 0.2961 - rmse: 0.3790 - smape: 0.6670 - val_ia: 0.2907 - val_loss: 0.3890 - val_mae: 0.4607 - val_rmse: 0.5002 - val_smape: 0.8343

Epoch 20/128

2292/2292 - 31s - 13ms/step - ia: 0.8063 - loss: 0.1419 - mae: 0.2873 - rmse: 0.3676 - smape: 0.6598 - val_ia: 0.3044 - val_loss: 0.3001 - val_mae: 0.4173 - val_rmse: 0.4545 - val_smape: 0.8275

Epoch 21/128

2292/2292 - 23s - 10ms/step - ia: 0.8123 - loss: 0.1348 - mae: 0.2797 - rmse: 0.3585 - smape: 0.6488 - val_ia: 0.3162 - val_loss: 0.2512 - val_mae: 0.3910 - val_rmse: 0.4253 - val_smape: 0.7789

Epoch 22/128

2292/2292 - 29s - 13ms/step - ia: 0.8161 - loss: 0.1301 - mae: 0.2744 - rmse: 0.3515 - smape: 0.6427 - val_ia: 0.3225 - val_loss: 0.2141 - val_mae: 0.3681 - val_rmse: 0.4034 - val_smape: 0.7629

Epoch 23/128

2292/2292 - 41s - 18ms/step - ia: 0.8209 - loss: 0.1240 - mae: 0.2677 - rmse: 0.3434 - smape: 0.6322 - val_ia: 0.3271 - val_loss: 0.1976 - val_mae: 0.3554 - val_rmse: 0.3918 - val_smape: 0.7490

Epoch 24/128

2292/2292 - 28s - 12ms/step - ia: 0.8240 - loss: 0.1195 - mae: 0.2632 - rmse: 0.3370 - smape: 0.6276 - val_ia: 0.3376 - val_loss: 0.1810 - val_mae: 0.3420 - val_rmse: 0.3775 - val_smape: 0.7312

Epoch 25/128

2292/2292 - 43s - 19ms/step - ia: 0.8272 - loss: 0.1164 - mae: 0.2590 - rmse: 0.3323 - smape: 0.6179 - val_ia: 0.3360 - val_loss: 0.1964 - val_mae: 0.3508 - val_rmse: 0.3883 - val_smape: 0.7218

Epoch 26/128

2292/2292 - 41s - 18ms/step - ia: 0.8282 - loss: 0.1149 - mae: 0.2573 - rmse: 0.3301 - smape: 0.6164 - val_ia: 0.3238 - val_loss: 0.2269 - val_mae: 0.3714 - val_rmse: 0.4120 - val_smape: 0.7411

Epoch 27/128

2292/2292 - 30s - 13ms/step - ia: 0.8312 - loss: 0.1124 - mae: 0.2539 - rmse: 0.3265 - smape: 0.6090 - val_ia: 0.3563 - val_loss: 0.1551 - val_mae: 0.3187 - val_rmse: 0.3514 - val_smape: 0.7058

Epoch 28/128

2292/2292 - 40s - 18ms/step - ia: 0.8320 - loss: 0.1109 - mae: 0.2523 - rmse: 0.3241 - smape: 0.6072 - val_ia: 0.3424 - val_loss: 0.1664 - val_mae: 0.3286 - val_rmse: 0.3636 - val_smape: 0.7088

Epoch 29/128

2292/2292 - 23s - 10ms/step - ia: 0.8336 - loss: 0.1093 - mae: 0.2501 - rmse: 0.3215 - smape: 0.6016 - val_ia: 0.3530 - val_loss: 0.1737 - val_mae: 0.3324 - val_rmse: 0.3667 - val_smape: 0.7043

Epoch 30/128

2292/2292 - 48s - 21ms/step - ia: 0.8345 - loss: 0.1079 - mae: 0.2482 - rmse: 0.3199 - smape: 0.5987 - val_ia: 0.3520 - val_loss: 0.1757 - val_mae: 0.3325 - val_rmse: 0.3698 - val_smape: 0.7020

Epoch 31/128

2292/2292 - 30s - 13ms/step - ia: 0.8357 - loss: 0.1065 - mae: 0.2464 - rmse: 0.3175 - smape: 0.5939 - val_ia: 0.3639 - val_loss: 0.1636 - val_mae: 0.3205 - val_rmse: 0.3573 - val_smape: 0.6917

Epoch 32/128

2292/2292 - 30s - 13ms/step - ia: 0.8366 - loss: 0.1061 - mae: 0.2456 - rmse: 0.3168 - smape: 0.5902 - val_ia: 0.3478 - val_loss: 0.1778 - val_mae: 0.3331 - val_rmse: 0.3714 - val_smape: 0.7070

Epoch 33/128

2292/2292 - 30s - 13ms/step - ia: 0.8383 - loss: 0.1045 - mae: 0.2435 - rmse: 0.3145 - smape: 0.5864 - val_ia: 0.3503 - val_loss: 0.1885 - val_mae: 0.3421 - val_rmse: 0.3808 - val_smape: 0.7114

Epoch 34/128

2292/2292 - 23s - 10ms/step - ia: 0.8384 - loss: 0.1038 - mae: 0.2433 - rmse: 0.3139 - smape: 0.5840 - val_ia: 0.3539 - val_loss: 0.1720 - val_mae: 0.3287 - val_rmse: 0.3676 - val_smape: 0.6958

Epoch 35/128

2292/2292 - 48s - 21ms/step - ia: 0.8390 - loss: 0.1028 - mae: 0.2420 - rmse: 0.3120 - smape: 0.5831 - val_ia: 0.3411 - val_loss: 0.1905 - val_mae: 0.3453 - val_rmse: 0.3842 - val_smape: 0.7141

Epoch 36/128

2292/2292 - 31s - 13ms/step - ia: 0.8403 - loss: 0.1016 - mae: 0.2406 - rmse: 0.3100 - smape: 0.5787 - val_ia: 0.3578 - val_loss: 0.1570 - val_mae: 0.3161 - val_rmse: 0.3537 - val_smape: 0.6877

Epoch 37/128

2292/2292 - 41s - 18ms/step - ia: 0.8407 - loss: 0.1014 - mae: 0.2397 - rmse: 0.3097 - smape: 0.5764 - val_ia: 0.3601 - val_loss: 0.1762 - val_mae: 0.3317 - val_rmse: 0.3683 - val_smape: 0.6961

Epoch 38/128

2292/2292 - 40s - 18ms/step - ia: 0.8414 - loss: 0.1002 - mae: 0.2387 - rmse: 0.3078 - smape: 0.5756 - val_ia: 0.3640 - val_loss: 0.1517 - val_mae: 0.3107 - val_rmse: 0.3481 - val_smape: 0.6780

Epoch 39/128

2292/2292 - 24s - 10ms/step - ia: 0.8420 - loss: 0.0996 - mae: 0.2380 - rmse: 0.3068 - smape: 0.5744 - val_ia: 0.3540 - val_loss: 0.1744 - val_mae: 0.3321 - val_rmse: 0.3697 - val_smape: 0.6982

Epoch 40/128

2292/2292 - 30s - 13ms/step - ia: 0.8431 - loss: 0.0983 - mae: 0.2365 - rmse: 0.3047 - smape: 0.5696 - val_ia: 0.3564 - val_loss: 0.1686 - val_mae: 0.3267 - val_rmse: 0.3633 - val_smape: 0.6967

Epoch 41/128

2292/2292 - 30s - 13ms/step - ia: 0.8437 - loss: 0.0979 - mae: 0.2353 - rmse: 0.3044 - smape: 0.5700 - val_ia: 0.3542 - val_loss: 0.1773 - val_mae: 0.3340 - val_rmse: 0.3710 - val_smape: 0.6960

Epoch 42/128

2292/2292 - 41s - 18ms/step - ia: 0.8433 - loss: 0.0976 - mae: 0.2358 - rmse: 0.3038 - smape: 0.5664 - val_ia: 0.3653 - val_loss: 0.1563 - val_mae: 0.3157 - val_rmse: 0.3510 - val_smape: 0.6843

Epoch 43/128

2292/2292 - 30s - 13ms/step - ia: 0.8450 - loss: 0.0961 - mae: 0.2338 - rmse: 0.3012 - smape: 0.5644 - val_ia: 0.3659 - val_loss: 0.1473 - val_mae: 0.3077 - val_rmse: 0.3440 - val_smape: 0.6707

Epoch 44/128

2292/2292 - 39s - 17ms/step - ia: 0.8452 - loss: 0.0960 - mae: 0.2338 - rmse: 0.3012 - smape: 0.5638 - val_ia: 0.3615 - val_loss: 0.1556 - val_mae: 0.3152 - val_rmse: 0.3530 - val_smape: 0.6816

Epoch 45/128

2292/2292 - 26s - 11ms/step - ia: 0.8453 - loss: 0.0954 - mae: 0.2332 - rmse: 0.3007 - smape: 0.5609 - val_ia: 0.3530 - val_loss: 0.1784 - val_mae: 0.3340 - val_rmse: 0.3725 - val_smape: 0.7024

Epoch 46/128

2292/2292 - 27s - 12ms/step - ia: 0.8465 - loss: 0.0942 - mae: 0.2321 - rmse: 0.2988 - smape: 0.5590 - val_ia: 0.3671 - val_loss: 0.1524 - val_mae: 0.3100 - val_rmse: 0.3461 - val_smape: 0.6781

Epoch 47/128

2292/2292 - 27s - 12ms/step - ia: 0.8470 - loss: 0.0938 - mae: 0.2313 - rmse: 0.2982 - smape: 0.5543 - val_ia: 0.3608 - val_loss: 0.1603 - val_mae: 0.3182 - val_rmse: 0.3564 - val_smape: 0.6850

Epoch 48/128

2292/2292 - 40s - 18ms/step - ia: 0.8475 - loss: 0.0935 - mae: 0.2300 - rmse: 0.2972 - smape: 0.5529 - val_ia: 0.3557 - val_loss: 0.1732 - val_mae: 0.3322 - val_rmse: 0.3680 - val_smape: 0.6988

Epoch 49/128

2292/2292 - 27s - 12ms/step - ia: 0.8484 - loss: 0.0924 - mae: 0.2294 - rmse: 0.2958 - smape: 0.5512 - val_ia: 0.3545 - val_loss: 0.1788 - val_mae: 0.3367 - val_rmse: 0.3748 - val_smape: 0.6966

Epoch 50/128

2292/2292 - 28s - 12ms/step - ia: 0.8485 - loss: 0.0924 - mae: 0.2296 - rmse: 0.2960 - smape: 0.5518 - val_ia: 0.3653 - val_loss: 0.1496 - val_mae: 0.3093 - val_rmse: 0.3463 - val_smape: 0.6711

Epoch 51/128

2292/2292 - 23s - 10ms/step - ia: 0.8489 - loss: 0.0912 - mae: 0.2285 - rmse: 0.2940 - smape: 0.5507 - val_ia: 0.3732 - val_loss: 0.1500 - val_mae: 0.3116 - val_rmse: 0.3458 - val_smape: 0.6694

Epoch 52/128

2292/2292 - 44s - 19ms/step - ia: 0.8493 - loss: 0.0916 - mae: 0.2284 - rmse: 0.2948 - smape: 0.5491 - val_ia: 0.3431 - val_loss: 0.1947 - val_mae: 0.3469 - val_rmse: 0.3896 - val_smape: 0.7167

Epoch 53/128

2292/2292 - 27s - 12ms/step - ia: 0.8500 - loss: 0.0905 - mae: 0.2270 - rmse: 0.2929 - smape: 0.5447 - val_ia: 0.3372 - val_loss: 0.1971 - val_mae: 0.3515 - val_rmse: 0.3930 - val_smape: 0.7197

Epoch 54/128

2292/2292 - 23s - 10ms/step - ia: 0.8503 - loss: 0.0893 - mae: 0.2259 - rmse: 0.2908 - smape: 0.5401 - val_ia: 0.3481 - val_loss: 0.1801 - val_mae: 0.3397 - val_rmse: 0.3766 - val_smape: 0.7046

Epoch 55/128

2292/2292 - 27s - 12ms/step - ia: 0.8509 - loss: 0.0891 - mae: 0.2255 - rmse: 0.2904 - smape: 0.5423 - val_ia: 0.3676 - val_loss: 0.1477 - val_mae: 0.3069 - val_rmse: 0.3428 - val_smape: 0.6706

Epoch 56/128

2292/2292 - 27s - 12ms/step - ia: 0.8520 - loss: 0.0882 - mae: 0.2244 - rmse: 0.2890 - smape: 0.5364 - val_ia: 0.3512 - val_loss: 0.1706 - val_mae: 0.3273 - val_rmse: 0.3673 - val_smape: 0.6959

Epoch 57/128

2292/2292 - 27s - 12ms/step - ia: 0.8530 - loss: 0.0872 - mae: 0.2231 - rmse: 0.2872 - smape: 0.5367 - val_ia: 0.3424 - val_loss: 0.1865 - val_mae: 0.3438 - val_rmse: 0.3831 - val_smape: 0.7107

Epoch 58/128

2292/2292 - 27s - 12ms/step - ia: 0.8530 - loss: 0.0870 - mae: 0.2232 - rmse: 0.2871 - smape: 0.5357 - val_ia: 0.3522 - val_loss: 0.1908 - val_mae: 0.3470 - val_rmse: 0.3842 - val_smape: 0.7119

Epoch 58: early stopping

Restoring model weights from the end of the best epoch: 43.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:15 466ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 58/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 83%|████████▎ | 10/12 [3:30:03<36:18, 1089.09s/trial, best loss: 0.1562418293598551]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

4584/4584 - 42s - 9ms/step - ia: 0.2973 - loss: 1.0353 - mae: 0.8350 - rmse: 0.9944 - smape: 1.5374 - val_ia: 0.1392 - val_loss: 0.8240 - val_mae: 0.7543 - val_rmse: 0.7728 - val_smape: 1.7145

Epoch 2/128

4584/4584 - 31s - 7ms/step - ia: 0.2989 - loss: 1.0105 - mae: 0.8256 - rmse: 0.9823 - smape: 1.5397 - val_ia: 0.1395 - val_loss: 0.8205 - val_mae: 0.7528 - val_rmse: 0.7713 - val_smape: 1.7084

Epoch 3/128

4584/4584 - 27s - 6ms/step - ia: 0.3032 - loss: 0.9942 - mae: 0.8177 - rmse: 0.9740 - smape: 1.5358 - val_ia: 0.1399 - val_loss: 0.8172 - val_mae: 0.7514 - val_rmse: 0.7699 - val_smape: 1.7014

Epoch 4/128

4584/4584 - 29s - 6ms/step - ia: 0.3023 - loss: 0.9820 - mae: 0.8132 - rmse: 0.9682 - smape: 1.5386 - val_ia: 0.1403 - val_loss: 0.8137 - val_mae: 0.7498 - val_rmse: 0.7683 - val_smape: 1.6933

Epoch 5/128

4584/4584 - 27s - 6ms/step - ia: 0.3095 - loss: 0.9576 - mae: 0.8029 - rmse: 0.9561 - smape: 1.5300 - val_ia: 0.1405 - val_loss: 0.8105 - val_mae: 0.7483 - val_rmse: 0.7668 - val_smape: 1.6847

Epoch 6/128

4584/4584 - 44s - 10ms/step - ia: 0.3094 - loss: 0.9464 - mae: 0.7984 - rmse: 0.9504 - smape: 1.5351 - val_ia: 0.1407 - val_loss: 0.8068 - val_mae: 0.7465 - val_rmse: 0.7650 - val_smape: 1.6746

Epoch 7/128

4584/4584 - 31s - 7ms/step - ia: 0.3143 - loss: 0.9319 - mae: 0.7927 - rmse: 0.9434 - smape: 1.5271 - val_ia: 0.1411 - val_loss: 0.8027 - val_mae: 0.7445 - val_rmse: 0.7629 - val_smape: 1.6651

Epoch 8/128

4584/4584 - 40s - 9ms/step - ia: 0.3168 - loss: 0.9205 - mae: 0.7870 - rmse: 0.9378 - smape: 1.5226 - val_ia: 0.1416 - val_loss: 0.7988 - val_mae: 0.7425 - val_rmse: 0.7609 - val_smape: 1.6546

Epoch 9/128

4584/4584 - 31s - 7ms/step - ia: 0.3187 - loss: 0.9130 - mae: 0.7852 - rmse: 0.9342 - smape: 1.5182 - val_ia: 0.1420 - val_loss: 0.7948 - val_mae: 0.7405 - val_rmse: 0.7589 - val_smape: 1.6448

Epoch 10/128

4584/4584 - 31s - 7ms/step - ia: 0.3197 - loss: 0.9016 - mae: 0.7804 - rmse: 0.9282 - smape: 1.5160 - val_ia: 0.1425 - val_loss: 0.7903 - val_mae: 0.7381 - val_rmse: 0.7566 - val_smape: 1.6347

Epoch 11/128

4584/4584 - 31s - 7ms/step - ia: 0.3217 - loss: 0.8973 - mae: 0.7782 - rmse: 0.9255 - smape: 1.5167 - val_ia: 0.1431 - val_loss: 0.7854 - val_mae: 0.7356 - val_rmse: 0.7540 - val_smape: 1.6246

Epoch 12/128

4584/4584 - 41s - 9ms/step - ia: 0.3217 - loss: 0.8904 - mae: 0.7764 - rmse: 0.9229 - smape: 1.5180 - val_ia: 0.1436 - val_loss: 0.7808 - val_mae: 0.7332 - val_rmse: 0.7516 - val_smape: 1.6145

Epoch 13/128

4584/4584 - 31s - 7ms/step - ia: 0.3306 - loss: 0.8723 - mae: 0.7670 - rmse: 0.9132 - smape: 1.5034 - val_ia: 0.1441 - val_loss: 0.7759 - val_mae: 0.7306 - val_rmse: 0.7490 - val_smape: 1.6046

Epoch 14/128

4584/4584 - 31s - 7ms/step - ia: 0.3327 - loss: 0.8652 - mae: 0.7639 - rmse: 0.9094 - smape: 1.4995 - val_ia: 0.1447 - val_loss: 0.7708 - val_mae: 0.7280 - val_rmse: 0.7464 - val_smape: 1.5947

Epoch 15/128

4584/4584 - 41s - 9ms/step - ia: 0.3336 - loss: 0.8583 - mae: 0.7612 - rmse: 0.9059 - smape: 1.4941 - val_ia: 0.1452 - val_loss: 0.7658 - val_mae: 0.7254 - val_rmse: 0.7438 - val_smape: 1.5850

Epoch 16/128

4584/4584 - 39s - 8ms/step - ia: 0.3401 - loss: 0.8476 - mae: 0.7554 - rmse: 0.8991 - smape: 1.4833 - val_ia: 0.1453 - val_loss: 0.7612 - val_mae: 0.7231 - val_rmse: 0.7415 - val_smape: 1.5765

Epoch 17/128

4584/4584 - 31s - 7ms/step - ia: 0.3418 - loss: 0.8408 - mae: 0.7532 - rmse: 0.8964 - smape: 1.4841 - val_ia: 0.1457 - val_loss: 0.7565 - val_mae: 0.7207 - val_rmse: 0.7391 - val_smape: 1.5675

Epoch 18/128

4584/4584 - 30s - 6ms/step - ia: 0.3459 - loss: 0.8380 - mae: 0.7506 - rmse: 0.8940 - smape: 1.4752 - val_ia: 0.1462 - val_loss: 0.7520 - val_mae: 0.7184 - val_rmse: 0.7369 - val_smape: 1.5593

Epoch 19/128

4584/4584 - 27s - 6ms/step - ia: 0.3466 - loss: 0.8302 - mae: 0.7474 - rmse: 0.8909 - smape: 1.4713 - val_ia: 0.1465 - val_loss: 0.7472 - val_mae: 0.7161 - val_rmse: 0.7345 - val_smape: 1.5509

Epoch 20/128

4584/4584 - 31s - 7ms/step - ia: 0.3493 - loss: 0.8253 - mae: 0.7441 - rmse: 0.8882 - smape: 1.4632 - val_ia: 0.1466 - val_loss: 0.7428 - val_mae: 0.7140 - val_rmse: 0.7324 - val_smape: 1.5435

Epoch 21/128

4584/4584 - 41s - 9ms/step - ia: 0.3554 - loss: 0.8149 - mae: 0.7390 - rmse: 0.8817 - smape: 1.4536 - val_ia: 0.1466 - val_loss: 0.7388 - val_mae: 0.7121 - val_rmse: 0.7305 - val_smape: 1.5369

Epoch 22/128

4584/4584 - 31s - 7ms/step - ia: 0.3598 - loss: 0.8046 - mae: 0.7359 - rmse: 0.8771 - smape: 1.4477 - val_ia: 0.1466 - val_loss: 0.7346 - val_mae: 0.7102 - val_rmse: 0.7285 - val_smape: 1.5302

Epoch 23/128

4584/4584 - 31s - 7ms/step - ia: 0.3602 - loss: 0.8047 - mae: 0.7350 - rmse: 0.8767 - smape: 1.4455 - val_ia: 0.1469 - val_loss: 0.7300 - val_mae: 0.7081 - val_rmse: 0.7264 - val_smape: 1.5236

Epoch 24/128

4584/4584 - 31s - 7ms/step - ia: 0.3639 - loss: 0.8040 - mae: 0.7324 - rmse: 0.8764 - smape: 1.4366 - val_ia: 0.1470 - val_loss: 0.7264 - val_mae: 0.7064 - val_rmse: 0.7247 - val_smape: 1.5180

Epoch 25/128

4584/4584 - 41s - 9ms/step - ia: 0.3689 - loss: 0.7896 - mae: 0.7268 - rmse: 0.8673 - smape: 1.4316 - val_ia: 0.1468 - val_loss: 0.7224 - val_mae: 0.7048 - val_rmse: 0.7230 - val_smape: 1.5120

Epoch 26/128

4584/4584 - 39s - 8ms/step - ia: 0.3694 - loss: 0.7857 - mae: 0.7247 - rmse: 0.8662 - smape: 1.4270 - val_ia: 0.1464 - val_loss: 0.7192 - val_mae: 0.7035 - val_rmse: 0.7217 - val_smape: 1.5070

Epoch 27/128

4584/4584 - 45s - 10ms/step - ia: 0.3713 - loss: 0.7806 - mae: 0.7226 - rmse: 0.8631 - smape: 1.4192 - val_ia: 0.1462 - val_loss: 0.7151 - val_mae: 0.7017 - val_rmse: 0.7199 - val_smape: 1.5009

Epoch 28/128

4584/4584 - 26s - 6ms/step - ia: 0.3746 - loss: 0.7740 - mae: 0.7197 - rmse: 0.8595 - smape: 1.4159 - val_ia: 0.1461 - val_loss: 0.7111 - val_mae: 0.6999 - val_rmse: 0.7181 - val_smape: 1.4955

Epoch 29/128

4584/4584 - 30s - 7ms/step - ia: 0.3812 - loss: 0.7680 - mae: 0.7153 - rmse: 0.8558 - smape: 1.4033 - val_ia: 0.1460 - val_loss: 0.7077 - val_mae: 0.6985 - val_rmse: 0.7166 - val_smape: 1.4902

Epoch 30/128

4584/4584 - 31s - 7ms/step - ia: 0.3867 - loss: 0.7601 - mae: 0.7108 - rmse: 0.8509 - smape: 1.3947 - val_ia: 0.1460 - val_loss: 0.7044 - val_mae: 0.6972 - val_rmse: 0.7152 - val_smape: 1.4853

Epoch 31/128

4584/4584 - 31s - 7ms/step - ia: 0.3871 - loss: 0.7585 - mae: 0.7105 - rmse: 0.8508 - smape: 1.3934 - val_ia: 0.1461 - val_loss: 0.7016 - val_mae: 0.6961 - val_rmse: 0.7141 - val_smape: 1.4814

Epoch 32/128

4584/4584 - 40s - 9ms/step - ia: 0.3901 - loss: 0.7551 - mae: 0.7086 - rmse: 0.8485 - smape: 1.3830 - val_ia: 0.1463 - val_loss: 0.6989 - val_mae: 0.6949 - val_rmse: 0.7130 - val_smape: 1.4780

Epoch 33/128

4584/4584 - 30s - 7ms/step - ia: 0.3958 - loss: 0.7429 - mae: 0.7029 - rmse: 0.8420 - smape: 1.3744 - val_ia: 0.1462 - val_loss: 0.6960 - val_mae: 0.6939 - val_rmse: 0.7118 - val_smape: 1.4731

Epoch 34/128

4584/4584 - 27s - 6ms/step - ia: 0.3964 - loss: 0.7434 - mae: 0.7018 - rmse: 0.8421 - smape: 1.3716 - val_ia: 0.1462 - val_loss: 0.6931 - val_mae: 0.6927 - val_rmse: 0.7106 - val_smape: 1.4694

Epoch 35/128

4584/4584 - 30s - 7ms/step - ia: 0.3977 - loss: 0.7407 - mae: 0.7004 - rmse: 0.8399 - smape: 1.3679 - val_ia: 0.1460 - val_loss: 0.6909 - val_mae: 0.6918 - val_rmse: 0.7097 - val_smape: 1.4667

Epoch 36/128

4584/4584 - 31s - 7ms/step - ia: 0.4027 - loss: 0.7340 - mae: 0.6969 - rmse: 0.8367 - smape: 1.3575 - val_ia: 0.1460 - val_loss: 0.6881 - val_mae: 0.6906 - val_rmse: 0.7085 - val_smape: 1.4632

Epoch 37/128

4584/4584 - 30s - 7ms/step - ia: 0.4047 - loss: 0.7302 - mae: 0.6948 - rmse: 0.8343 - smape: 1.3536 - val_ia: 0.1459 - val_loss: 0.6860 - val_mae: 0.6899 - val_rmse: 0.7077 - val_smape: 1.4592

Epoch 38/128

4584/4584 - 27s - 6ms/step - ia: 0.4065 - loss: 0.7254 - mae: 0.6927 - rmse: 0.8315 - smape: 1.3478 - val_ia: 0.1459 - val_loss: 0.6838 - val_mae: 0.6891 - val_rmse: 0.7068 - val_smape: 1.4554

Epoch 39/128

4584/4584 - 29s - 6ms/step - ia: 0.4119 - loss: 0.7248 - mae: 0.6921 - rmse: 0.8305 - smape: 1.3397 - val_ia: 0.1457 - val_loss: 0.6820 - val_mae: 0.6884 - val_rmse: 0.7061 - val_smape: 1.4528

Epoch 40/128

4584/4584 - 28s - 6ms/step - ia: 0.4121 - loss: 0.7194 - mae: 0.6885 - rmse: 0.8280 - smape: 1.3339 - val_ia: 0.1455 - val_loss: 0.6799 - val_mae: 0.6876 - val_rmse: 0.7053 - val_smape: 1.4492

Epoch 41/128

4584/4584 - 43s - 9ms/step - ia: 0.4158 - loss: 0.7131 - mae: 0.6846 - rmse: 0.8238 - smape: 1.3277 - val_ia: 0.1452 - val_loss: 0.6780 - val_mae: 0.6869 - val_rmse: 0.7045 - val_smape: 1.4464

Epoch 42/128

4584/4584 - 31s - 7ms/step - ia: 0.4192 - loss: 0.7076 - mae: 0.6816 - rmse: 0.8204 - smape: 1.3176 - val_ia: 0.1447 - val_loss: 0.6766 - val_mae: 0.6866 - val_rmse: 0.7041 - val_smape: 1.4434

Epoch 43/128

4584/4584 - 31s - 7ms/step - ia: 0.4201 - loss: 0.7043 - mae: 0.6806 - rmse: 0.8184 - smape: 1.3150 - val_ia: 0.1443 - val_loss: 0.6751 - val_mae: 0.6861 - val_rmse: 0.7035 - val_smape: 1.4401

Epoch 44/128

4584/4584 - 31s - 7ms/step - ia: 0.4215 - loss: 0.7040 - mae: 0.6806 - rmse: 0.8182 - smape: 1.3130 - val_ia: 0.1440 - val_loss: 0.6737 - val_mae: 0.6856 - val_rmse: 0.7030 - val_smape: 1.4369

Epoch 45/128

4584/4584 - 37s - 8ms/step - ia: 0.4255 - loss: 0.6975 - mae: 0.6770 - rmse: 0.8157 - smape: 1.3013 - val_ia: 0.1436 - val_loss: 0.6727 - val_mae: 0.6855 - val_rmse: 0.7028 - val_smape: 1.4346

Epoch 46/128

4584/4584 - 31s - 7ms/step - ia: 0.4271 - loss: 0.6948 - mae: 0.6755 - rmse: 0.8136 - smape: 1.2985 - val_ia: 0.1436 - val_loss: 0.6708 - val_mae: 0.6846 - val_rmse: 0.7019 - val_smape: 1.4309

Epoch 47/128

4584/4584 - 41s - 9ms/step - ia: 0.4321 - loss: 0.6893 - mae: 0.6718 - rmse: 0.8101 - smape: 1.2901 - val_ia: 0.1435 - val_loss: 0.6700 - val_mae: 0.6845 - val_rmse: 0.7017 - val_smape: 1.4283

Epoch 48/128

4584/4584 - 31s - 7ms/step - ia: 0.4328 - loss: 0.6890 - mae: 0.6716 - rmse: 0.8091 - smape: 1.2872 - val_ia: 0.1434 - val_loss: 0.6687 - val_mae: 0.6841 - val_rmse: 0.7012 - val_smape: 1.4255

Epoch 49/128

4584/4584 - 31s - 7ms/step - ia: 0.4368 - loss: 0.6843 - mae: 0.6683 - rmse: 0.8072 - smape: 1.2782 - val_ia: 0.1433 - val_loss: 0.6674 - val_mae: 0.6837 - val_rmse: 0.7008 - val_smape: 1.4221

Epoch 50/128

4584/4584 - 40s - 9ms/step - ia: 0.4379 - loss: 0.6758 - mae: 0.6653 - rmse: 0.8015 - smape: 1.2744 - val_ia: 0.1434 - val_loss: 0.6652 - val_mae: 0.6827 - val_rmse: 0.6997 - val_smape: 1.4178

Epoch 51/128

4584/4584 - 31s - 7ms/step - ia: 0.4400 - loss: 0.6789 - mae: 0.6654 - rmse: 0.8031 - smape: 1.2699 - val_ia: 0.1433 - val_loss: 0.6641 - val_mae: 0.6823 - val_rmse: 0.6993 - val_smape: 1.4149

Epoch 52/128

4584/4584 - 27s - 6ms/step - ia: 0.4420 - loss: 0.6735 - mae: 0.6627 - rmse: 0.8001 - smape: 1.2641 - val_ia: 0.1433 - val_loss: 0.6625 - val_mae: 0.6817 - val_rmse: 0.6986 - val_smape: 1.4114

Epoch 53/128

4584/4584 - 31s - 7ms/step - ia: 0.4436 - loss: 0.6725 - mae: 0.6624 - rmse: 0.7982 - smape: 1.2617 - val_ia: 0.1433 - val_loss: 0.6613 - val_mae: 0.6812 - val_rmse: 0.6981 - val_smape: 1.4083

Epoch 54/128

4584/4584 - 30s - 7ms/step - ia: 0.4461 - loss: 0.6692 - mae: 0.6605 - rmse: 0.7971 - smape: 1.2551 - val_ia: 0.1433 - val_loss: 0.6600 - val_mae: 0.6807 - val_rmse: 0.6975 - val_smape: 1.4046

Epoch 55/128

4584/4584 - 41s - 9ms/step - ia: 0.4491 - loss: 0.6672 - mae: 0.6590 - rmse: 0.7955 - smape: 1.2465 - val_ia: 0.1433 - val_loss: 0.6595 - val_mae: 0.6807 - val_rmse: 0.6974 - val_smape: 1.4020

Epoch 56/128

4584/4584 - 31s - 7ms/step - ia: 0.4508 - loss: 0.6611 - mae: 0.6559 - rmse: 0.7918 - smape: 1.2423 - val_ia: 0.1434 - val_loss: 0.6583 - val_mae: 0.6801 - val_rmse: 0.6968 - val_smape: 1.3990

Epoch 57/128

4584/4584 - 40s - 9ms/step - ia: 0.4525 - loss: 0.6629 - mae: 0.6567 - rmse: 0.7932 - smape: 1.2404 - val_ia: 0.1435 - val_loss: 0.6575 - val_mae: 0.6799 - val_rmse: 0.6965 - val_smape: 1.3961

Epoch 58/128

4584/4584 - 29s - 6ms/step - ia: 0.4556 - loss: 0.6555 - mae: 0.6528 - rmse: 0.7887 - smape: 1.2335 - val_ia: 0.1436 - val_loss: 0.6571 - val_mae: 0.6799 - val_rmse: 0.6964 - val_smape: 1.3932

Epoch 59/128

4584/4584 - 27s - 6ms/step - ia: 0.4575 - loss: 0.6534 - mae: 0.6528 - rmse: 0.7877 - smape: 1.2296 - val_ia: 0.1438 - val_loss: 0.6558 - val_mae: 0.6793 - val_rmse: 0.6959 - val_smape: 1.3900

Epoch 60/128

4584/4584 - 31s - 7ms/step - ia: 0.4554 - loss: 0.6561 - mae: 0.6528 - rmse: 0.7890 - smape: 1.2262 - val_ia: 0.1440 - val_loss: 0.6561 - val_mae: 0.6797 - val_rmse: 0.6962 - val_smape: 1.3877

Epoch 61/128

4584/4584 - 30s - 7ms/step - ia: 0.4608 - loss: 0.6460 - mae: 0.6473 - rmse: 0.7831 - smape: 1.2192 - val_ia: 0.1442 - val_loss: 0.6555 - val_mae: 0.6795 - val_rmse: 0.6960 - val_smape: 1.3842

Epoch 62/128

4584/4584 - 29s - 6ms/step - ia: 0.4605 - loss: 0.6503 - mae: 0.6496 - rmse: 0.7859 - smape: 1.2180 - val_ia: 0.1443 - val_loss: 0.6551 - val_mae: 0.6795 - val_rmse: 0.6959 - val_smape: 1.3812

Epoch 63/128

4584/4584 - 27s - 6ms/step - ia: 0.4628 - loss: 0.6464 - mae: 0.6470 - rmse: 0.7825 - smape: 1.2148 - val_ia: 0.1444 - val_loss: 0.6548 - val_mae: 0.6794 - val_rmse: 0.6958 - val_smape: 1.3786

Epoch 64/128

4584/4584 - 27s - 6ms/step - ia: 0.4643 - loss: 0.6422 - mae: 0.6455 - rmse: 0.7803 - smape: 1.2088 - val_ia: 0.1445 - val_loss: 0.6537 - val_mae: 0.6789 - val_rmse: 0.6953 - val_smape: 1.3754

Epoch 65/128

4584/4584 - 32s - 7ms/step - ia: 0.4677 - loss: 0.6396 - mae: 0.6435 - rmse: 0.7787 - smape: 1.2015 - val_ia: 0.1444 - val_loss: 0.6541 - val_mae: 0.6794 - val_rmse: 0.6957 - val_smape: 1.3736

Epoch 66/128

4584/4584 - 30s - 7ms/step - ia: 0.4689 - loss: 0.6314 - mae: 0.6402 - rmse: 0.7743 - smape: 1.1996 - val_ia: 0.1445 - val_loss: 0.6529 - val_mae: 0.6788 - val_rmse: 0.6951 - val_smape: 1.3697

Epoch 67/128

4584/4584 - 42s - 9ms/step - ia: 0.4687 - loss: 0.6410 - mae: 0.6441 - rmse: 0.7796 - smape: 1.1985 - val_ia: 0.1445 - val_loss: 0.6532 - val_mae: 0.6792 - val_rmse: 0.6954 - val_smape: 1.3686

Epoch 68/128

4584/4584 - 30s - 7ms/step - ia: 0.4727 - loss: 0.6307 - mae: 0.6387 - rmse: 0.7740 - smape: 1.1905 - val_ia: 0.1446 - val_loss: 0.6518 - val_mae: 0.6785 - val_rmse: 0.6947 - val_smape: 1.3651

Epoch 69/128

4584/4584 - 31s - 7ms/step - ia: 0.4711 - loss: 0.6331 - mae: 0.6412 - rmse: 0.7754 - smape: 1.1930 - val_ia: 0.1446 - val_loss: 0.6505 - val_mae: 0.6778 - val_rmse: 0.6940 - val_smape: 1.3621

Epoch 70/128

4584/4584 - 30s - 7ms/step - ia: 0.4721 - loss: 0.6332 - mae: 0.6403 - rmse: 0.7751 - smape: 1.1879 - val_ia: 0.1444 - val_loss: 0.6502 - val_mae: 0.6778 - val_rmse: 0.6939 - val_smape: 1.3600

Epoch 71/128

4584/4584 - 30s - 7ms/step - ia: 0.4771 - loss: 0.6207 - mae: 0.6345 - rmse: 0.7677 - smape: 1.1791 - val_ia: 0.1443 - val_loss: 0.6493 - val_mae: 0.6774 - val_rmse: 0.6935 - val_smape: 1.3574

Epoch 72/128

4584/4584 - 41s - 9ms/step - ia: 0.4776 - loss: 0.6281 - mae: 0.6370 - rmse: 0.7713 - smape: 1.1787 - val_ia: 0.1442 - val_loss: 0.6492 - val_mae: 0.6775 - val_rmse: 0.6935 - val_smape: 1.3553

Epoch 73/128

4584/4584 - 31s - 7ms/step - ia: 0.4770 - loss: 0.6255 - mae: 0.6364 - rmse: 0.7701 - smape: 1.1776 - val_ia: 0.1442 - val_loss: 0.6487 - val_mae: 0.6773 - val_rmse: 0.6933 - val_smape: 1.3536

Epoch 74/128

4584/4584 - 31s - 7ms/step - ia: 0.4782 - loss: 0.6257 - mae: 0.6368 - rmse: 0.7704 - smape: 1.1765 - val_ia: 0.1442 - val_loss: 0.6488 - val_mae: 0.6774 - val_rmse: 0.6934 - val_smape: 1.3521

Epoch 75/128

4584/4584 - 28s - 6ms/step - ia: 0.4819 - loss: 0.6200 - mae: 0.6329 - rmse: 0.7661 - smape: 1.1729 - val_ia: 0.1444 - val_loss: 0.6475 - val_mae: 0.6768 - val_rmse: 0.6927 - val_smape: 1.3495

Epoch 76/128

4584/4584 - 29s - 6ms/step - ia: 0.4821 - loss: 0.6174 - mae: 0.6319 - rmse: 0.7656 - smape: 1.1705 - val_ia: 0.1444 - val_loss: 0.6468 - val_mae: 0.6764 - val_rmse: 0.6923 - val_smape: 1.3473

Epoch 77/128

4584/4584 - 30s - 7ms/step - ia: 0.4827 - loss: 0.6180 - mae: 0.6316 - rmse: 0.7651 - smape: 1.1644 - val_ia: 0.1444 - val_loss: 0.6464 - val_mae: 0.6763 - val_rmse: 0.6921 - val_smape: 1.3451

Epoch 78/128

4584/4584 - 31s - 7ms/step - ia: 0.4845 - loss: 0.6148 - mae: 0.6305 - rmse: 0.7629 - smape: 1.1623 - val_ia: 0.1442 - val_loss: 0.6471 - val_mae: 0.6768 - val_rmse: 0.6926 - val_smape: 1.3437

Epoch 79/128

4584/4584 - 31s - 7ms/step - ia: 0.4819 - loss: 0.6164 - mae: 0.6306 - rmse: 0.7645 - smape: 1.1638 - val_ia: 0.1442 - val_loss: 0.6465 - val_mae: 0.6765 - val_rmse: 0.6923 - val_smape: 1.3412

Epoch 80/128

4584/4584 - 30s - 7ms/step - ia: 0.4856 - loss: 0.6109 - mae: 0.6277 - rmse: 0.7613 - smape: 1.1546 - val_ia: 0.1440 - val_loss: 0.6467 - val_mae: 0.6767 - val_rmse: 0.6925 - val_smape: 1.3397

Epoch 81/128

4584/4584 - 31s - 7ms/step - ia: 0.4886 - loss: 0.6128 - mae: 0.6282 - rmse: 0.7614 - smape: 1.1538 - val_ia: 0.1439 - val_loss: 0.6471 - val_mae: 0.6770 - val_rmse: 0.6927 - val_smape: 1.3390

Epoch 82/128

4584/4584 - 31s - 7ms/step - ia: 0.4880 - loss: 0.6124 - mae: 0.6283 - rmse: 0.7613 - smape: 1.1553 - val_ia: 0.1438 - val_loss: 0.6473 - val_mae: 0.6771 - val_rmse: 0.6928 - val_smape: 1.3378

Epoch 83/128

4584/4584 - 31s - 7ms/step - ia: 0.4897 - loss: 0.6072 - mae: 0.6260 - rmse: 0.7577 - smape: 1.1488 - val_ia: 0.1435 - val_loss: 0.6474 - val_mae: 0.6772 - val_rmse: 0.6929 - val_smape: 1.3363

Epoch 84/128

4584/4584 - 31s - 7ms/step - ia: 0.4911 - loss: 0.6033 - mae: 0.6247 - rmse: 0.7564 - smape: 1.1460 - val_ia: 0.1434 - val_loss: 0.6472 - val_mae: 0.6771 - val_rmse: 0.6928 - val_smape: 1.3342

Epoch 85/128

4584/4584 - 31s - 7ms/step - ia: 0.4887 - loss: 0.6092 - mae: 0.6277 - rmse: 0.7598 - smape: 1.1470 - val_ia: 0.1431 - val_loss: 0.6483 - val_mae: 0.6778 - val_rmse: 0.6934 - val_smape: 1.3338

Epoch 86/128

4584/4584 - 41s - 9ms/step - ia: 0.4956 - loss: 0.5999 - mae: 0.6213 - rmse: 0.7538 - smape: 1.1390 - val_ia: 0.1432 - val_loss: 0.6472 - val_mae: 0.6772 - val_rmse: 0.6928 - val_smape: 1.3311

Epoch 87/128

4584/4584 - 31s - 7ms/step - ia: 0.4925 - loss: 0.6016 - mae: 0.6224 - rmse: 0.7551 - smape: 1.1371 - val_ia: 0.1432 - val_loss: 0.6465 - val_mae: 0.6768 - val_rmse: 0.6924 - val_smape: 1.3292

Epoch 88/128

4584/4584 - 30s - 7ms/step - ia: 0.4941 - loss: 0.5978 - mae: 0.6224 - rmse: 0.7527 - smape: 1.1389 - val_ia: 0.1429 - val_loss: 0.6474 - val_mae: 0.6773 - val_rmse: 0.6929 - val_smape: 1.3281

Epoch 89/128

4584/4584 - 43s - 9ms/step - ia: 0.4957 - loss: 0.5957 - mae: 0.6208 - rmse: 0.7513 - smape: 1.1345 - val_ia: 0.1429 - val_loss: 0.6468 - val_mae: 0.6770 - val_rmse: 0.6926 - val_smape: 1.3263

Epoch 90/128

4584/4584 - 31s - 7ms/step - ia: 0.4969 - loss: 0.5968 - mae: 0.6206 - rmse: 0.7512 - smape: 1.1330 - val_ia: 0.1427 - val_loss: 0.6472 - val_mae: 0.6773 - val_rmse: 0.6928 - val_smape: 1.3251

Epoch 91/128

4584/4584 - 30s - 7ms/step - ia: 0.4976 - loss: 0.5945 - mae: 0.6198 - rmse: 0.7504 - smape: 1.1306 - val_ia: 0.1427 - val_loss: 0.6464 - val_mae: 0.6768 - val_rmse: 0.6923 - val_smape: 1.3236

Epoch 92/128

4584/4584 - 40s - 9ms/step - ia: 0.5010 - loss: 0.5946 - mae: 0.6185 - rmse: 0.7509 - smape: 1.1263 - val_ia: 0.1428 - val_loss: 0.6458 - val_mae: 0.6764 - val_rmse: 0.6919 - val_smape: 1.3214

Epoch 93/128

4584/4584 - 38s - 8ms/step - ia: 0.5001 - loss: 0.5927 - mae: 0.6188 - rmse: 0.7494 - smape: 1.1270 - val_ia: 0.1426 - val_loss: 0.6466 - val_mae: 0.6768 - val_rmse: 0.6923 - val_smape: 1.3206

Epoch 94/128

4584/4584 - 43s - 9ms/step - ia: 0.5008 - loss: 0.5890 - mae: 0.6166 - rmse: 0.7473 - smape: 1.1215 - val_ia: 0.1425 - val_loss: 0.6463 - val_mae: 0.6767 - val_rmse: 0.6922 - val_smape: 1.3186

Epoch 95/128

4584/4584 - 30s - 6ms/step - ia: 0.5007 - loss: 0.5875 - mae: 0.6158 - rmse: 0.7463 - smape: 1.1199 - val_ia: 0.1428 - val_loss: 0.6447 - val_mae: 0.6756 - val_rmse: 0.6911 - val_smape: 1.3159

Epoch 96/128

4584/4584 - 36s - 8ms/step - ia: 0.5018 - loss: 0.5889 - mae: 0.6166 - rmse: 0.7468 - smape: 1.1213 - val_ia: 0.1427 - val_loss: 0.6451 - val_mae: 0.6758 - val_rmse: 0.6913 - val_smape: 1.3147

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 7s - 24ms/step - ia: 0.3576 - loss: 0.8578 - mae: 0.7633 - rmse: 0.9222 - smape: 1.3551 - val_ia: 0.4114 - val_loss: 0.8105 - val_mae: 0.7560 - val_rmse: 0.8837 - val_smape: 1.3043

Epoch 2/128

287/287 - 3s - 12ms/step - ia: 0.5644 - loss: 0.5616 - mae: 0.6024 - rmse: 0.7478 - smape: 1.0416 - val_ia: 0.4385 - val_loss: 1.1194 - val_mae: 0.8895 - val_rmse: 1.0273 - val_smape: 1.2996

Epoch 3/128

287/287 - 3s - 12ms/step - ia: 0.6200 - loss: 0.4867 - mae: 0.5549 - rmse: 0.6962 - smape: 0.9485 - val_ia: 0.4441 - val_loss: 1.2310 - val_mae: 0.9266 - val_rmse: 1.0710 - val_smape: 1.2884

Epoch 4/128

287/287 - 3s - 12ms/step - ia: 0.6524 - loss: 0.4306 - mae: 0.5202 - rmse: 0.6546 - smape: 0.8959 - val_ia: 0.4658 - val_loss: 1.1373 - val_mae: 0.8837 - val_rmse: 1.0209 - val_smape: 1.2490

Epoch 5/128

287/287 - 4s - 12ms/step - ia: 0.6767 - loss: 0.3844 - mae: 0.4914 - rmse: 0.6185 - smape: 0.8515 - val_ia: 0.4853 - val_loss: 1.0281 - val_mae: 0.8360 - val_rmse: 0.9626 - val_smape: 1.2250

Epoch 6/128

287/287 - 3s - 12ms/step - ia: 0.6940 - loss: 0.3541 - mae: 0.4701 - rmse: 0.5936 - smape: 0.8202 - val_ia: 0.5062 - val_loss: 0.9365 - val_mae: 0.7868 - val_rmse: 0.9163 - val_smape: 1.1836

Epoch 7/128

287/287 - 3s - 12ms/step - ia: 0.7059 - loss: 0.3308 - mae: 0.4535 - rmse: 0.5739 - smape: 0.7989 - val_ia: 0.5154 - val_loss: 0.9024 - val_mae: 0.7690 - val_rmse: 0.8965 - val_smape: 1.1685

Epoch 8/128

287/287 - 4s - 12ms/step - ia: 0.7178 - loss: 0.3103 - mae: 0.4380 - rmse: 0.5559 - smape: 0.7807 - val_ia: 0.5371 - val_loss: 0.8162 - val_mae: 0.7234 - val_rmse: 0.8494 - val_smape: 1.1271

Epoch 9/128

287/287 - 3s - 12ms/step - ia: 0.7258 - loss: 0.2949 - mae: 0.4271 - rmse: 0.5417 - smape: 0.7684 - val_ia: 0.5652 - val_loss: 0.6732 - val_mae: 0.6524 - val_rmse: 0.7684 - val_smape: 1.0729

Epoch 10/128

287/287 - 3s - 12ms/step - ia: 0.7343 - loss: 0.2789 - mae: 0.4144 - rmse: 0.5271 - smape: 0.7545 - val_ia: 0.5682 - val_loss: 0.6860 - val_mae: 0.6560 - val_rmse: 0.7734 - val_smape: 1.0698

Epoch 11/128

287/287 - 3s - 12ms/step - ia: 0.7397 - loss: 0.2686 - mae: 0.4064 - rmse: 0.5172 - smape: 0.7489 - val_ia: 0.5899 - val_loss: 0.6190 - val_mae: 0.6234 - val_rmse: 0.7294 - val_smape: 1.0262

Epoch 12/128

287/287 - 3s - 12ms/step - ia: 0.7457 - loss: 0.2584 - mae: 0.3976 - rmse: 0.5068 - smape: 0.7398 - val_ia: 0.6031 - val_loss: 0.5504 - val_mae: 0.5873 - val_rmse: 0.6941 - val_smape: 1.0131

Epoch 13/128

287/287 - 3s - 12ms/step - ia: 0.7501 - loss: 0.2493 - mae: 0.3905 - rmse: 0.4983 - smape: 0.7384 - val_ia: 0.5985 - val_loss: 0.5903 - val_mae: 0.6011 - val_rmse: 0.7087 - val_smape: 1.0153

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.7556 - loss: 0.2400 - mae: 0.3823 - rmse: 0.4889 - smape: 0.7318 - val_ia: 0.6040 - val_loss: 0.5941 - val_mae: 0.5997 - val_rmse: 0.7106 - val_smape: 1.0157

Epoch 15/128

287/287 - 4s - 12ms/step - ia: 0.7616 - loss: 0.2301 - mae: 0.3728 - rmse: 0.4785 - smape: 0.7265 - val_ia: 0.6197 - val_loss: 0.5581 - val_mae: 0.5832 - val_rmse: 0.6889 - val_smape: 0.9903

Epoch 16/128

287/287 - 3s - 12ms/step - ia: 0.7664 - loss: 0.2220 - mae: 0.3656 - rmse: 0.4701 - smape: 0.7217 - val_ia: 0.6283 - val_loss: 0.5408 - val_mae: 0.5658 - val_rmse: 0.6788 - val_smape: 0.9818

Epoch 17/128

287/287 - 5s - 18ms/step - ia: 0.7733 - loss: 0.2100 - mae: 0.3546 - rmse: 0.4571 - smape: 0.7147 - val_ia: 0.6503 - val_loss: 0.4918 - val_mae: 0.5435 - val_rmse: 0.6414 - val_smape: 0.9300

Epoch 18/128

287/287 - 3s - 12ms/step - ia: 0.7805 - loss: 0.1980 - mae: 0.3432 - rmse: 0.4437 - smape: 0.7068 - val_ia: 0.6582 - val_loss: 0.4928 - val_mae: 0.5314 - val_rmse: 0.6467 - val_smape: 0.9214

Epoch 19/128

287/287 - 3s - 12ms/step - ia: 0.7874 - loss: 0.1866 - mae: 0.3318 - rmse: 0.4305 - smape: 0.6947 - val_ia: 0.6746 - val_loss: 0.4507 - val_mae: 0.5075 - val_rmse: 0.6213 - val_smape: 0.8791

Epoch 20/128

287/287 - 3s - 12ms/step - ia: 0.7958 - loss: 0.1729 - mae: 0.3190 - rmse: 0.4146 - smape: 0.6819 - val_ia: 0.6865 - val_loss: 0.4348 - val_mae: 0.4930 - val_rmse: 0.6204 - val_smape: 0.8537

Epoch 21/128

287/287 - 3s - 12ms/step - ia: 0.8039 - loss: 0.1603 - mae: 0.3065 - rmse: 0.3993 - smape: 0.6701 - val_ia: 0.7174 - val_loss: 0.3076 - val_mae: 0.4255 - val_rmse: 0.5314 - val_smape: 0.8084

Epoch 22/128

287/287 - 4s - 12ms/step - ia: 0.8120 - loss: 0.1491 - mae: 0.2943 - rmse: 0.3851 - smape: 0.6564 - val_ia: 0.7247 - val_loss: 0.2875 - val_mae: 0.4109 - val_rmse: 0.5224 - val_smape: 0.8034

Epoch 23/128

287/287 - 4s - 16ms/step - ia: 0.8193 - loss: 0.1392 - mae: 0.2836 - rmse: 0.3720 - smape: 0.6421 - val_ia: 0.7398 - val_loss: 0.2464 - val_mae: 0.3946 - val_rmse: 0.4767 - val_smape: 0.7772

Epoch 24/128

287/287 - 4s - 15ms/step - ia: 0.8243 - loss: 0.1321 - mae: 0.2766 - rmse: 0.3622 - smape: 0.6326 - val_ia: 0.7360 - val_loss: 0.2509 - val_mae: 0.3941 - val_rmse: 0.4886 - val_smape: 0.7741

Epoch 25/128

287/287 - 3s - 12ms/step - ia: 0.8307 - loss: 0.1238 - mae: 0.2669 - rmse: 0.3507 - smape: 0.6186 - val_ia: 0.7479 - val_loss: 0.2249 - val_mae: 0.3781 - val_rmse: 0.4586 - val_smape: 0.7523

Epoch 26/128

287/287 - 3s - 12ms/step - ia: 0.8339 - loss: 0.1198 - mae: 0.2621 - rmse: 0.3449 - smape: 0.6118 - val_ia: 0.7610 - val_loss: 0.2005 - val_mae: 0.3579 - val_rmse: 0.4358 - val_smape: 0.7322

Epoch 27/128

287/287 - 5s - 18ms/step - ia: 0.8370 - loss: 0.1162 - mae: 0.2577 - rmse: 0.3396 - smape: 0.6038 - val_ia: 0.7498 - val_loss: 0.2346 - val_mae: 0.3811 - val_rmse: 0.4725 - val_smape: 0.7502

Epoch 28/128

287/287 - 4s - 12ms/step - ia: 0.8391 - loss: 0.1129 - mae: 0.2543 - rmse: 0.3350 - smape: 0.5984 - val_ia: 0.7712 - val_loss: 0.1884 - val_mae: 0.3446 - val_rmse: 0.4189 - val_smape: 0.7103

Epoch 29/128

287/287 - 4s - 12ms/step - ia: 0.8405 - loss: 0.1111 - mae: 0.2520 - rmse: 0.3322 - smape: 0.5936 - val_ia: 0.7780 - val_loss: 0.1729 - val_mae: 0.3324 - val_rmse: 0.4072 - val_smape: 0.7026

Epoch 30/128

287/287 - 4s - 13ms/step - ia: 0.8431 - loss: 0.1081 - mae: 0.2481 - rmse: 0.3277 - smape: 0.5896 - val_ia: 0.7734 - val_loss: 0.1939 - val_mae: 0.3485 - val_rmse: 0.4246 - val_smape: 0.7051

Epoch 31/128

287/287 - 4s - 13ms/step - ia: 0.8445 - loss: 0.1067 - mae: 0.2462 - rmse: 0.3251 - smape: 0.5867 - val_ia: 0.7714 - val_loss: 0.1773 - val_mae: 0.3367 - val_rmse: 0.4111 - val_smape: 0.7199

Epoch 32/128

287/287 - 4s - 12ms/step - ia: 0.8458 - loss: 0.1048 - mae: 0.2442 - rmse: 0.3227 - smape: 0.5838 - val_ia: 0.7667 - val_loss: 0.2131 - val_mae: 0.3645 - val_rmse: 0.4453 - val_smape: 0.7174

Epoch 33/128

287/287 - 3s - 12ms/step - ia: 0.8469 - loss: 0.1036 - mae: 0.2427 - rmse: 0.3207 - smape: 0.5801 - val_ia: 0.7726 - val_loss: 0.1849 - val_mae: 0.3420 - val_rmse: 0.4180 - val_smape: 0.7089

Epoch 34/128

287/287 - 4s - 12ms/step - ia: 0.8488 - loss: 0.1015 - mae: 0.2401 - rmse: 0.3174 - smape: 0.5726 - val_ia: 0.7787 - val_loss: 0.1797 - val_mae: 0.3365 - val_rmse: 0.4107 - val_smape: 0.6972

Epoch 35/128

287/287 - 3s - 12ms/step - ia: 0.8493 - loss: 0.1005 - mae: 0.2392 - rmse: 0.3159 - smape: 0.5740 - val_ia: 0.7712 - val_loss: 0.2010 - val_mae: 0.3546 - val_rmse: 0.4354 - val_smape: 0.7077

Epoch 36/128

287/287 - 3s - 12ms/step - ia: 0.8508 - loss: 0.0987 - mae: 0.2366 - rmse: 0.3132 - smape: 0.5711 - val_ia: 0.7782 - val_loss: 0.1736 - val_mae: 0.3324 - val_rmse: 0.4072 - val_smape: 0.6974

Epoch 37/128

287/287 - 3s - 12ms/step - ia: 0.8511 - loss: 0.0984 - mae: 0.2362 - rmse: 0.3125 - smape: 0.5676 - val_ia: 0.7800 - val_loss: 0.1797 - val_mae: 0.3363 - val_rmse: 0.4124 - val_smape: 0.6912

Epoch 38/128

287/287 - 3s - 12ms/step - ia: 0.8535 - loss: 0.0963 - mae: 0.2332 - rmse: 0.3091 - smape: 0.5640 - val_ia: 0.7925 - val_loss: 0.1487 - val_mae: 0.3086 - val_rmse: 0.3758 - val_smape: 0.6658

Epoch 39/128

287/287 - 4s - 12ms/step - ia: 0.8530 - loss: 0.0960 - mae: 0.2334 - rmse: 0.3086 - smape: 0.5646 - val_ia: 0.7779 - val_loss: 0.1864 - val_mae: 0.3444 - val_rmse: 0.4175 - val_smape: 0.6977

Epoch 40/128

287/287 - 4s - 12ms/step - ia: 0.8544 - loss: 0.0944 - mae: 0.2315 - rmse: 0.3061 - smape: 0.5614 - val_ia: 0.7876 - val_loss: 0.1623 - val_mae: 0.3209 - val_rmse: 0.3930 - val_smape: 0.6776

Epoch 41/128

287/287 - 3s - 12ms/step - ia: 0.8548 - loss: 0.0941 - mae: 0.2310 - rmse: 0.3054 - smape: 0.5608 - val_ia: 0.7767 - val_loss: 0.1801 - val_mae: 0.3382 - val_rmse: 0.4128 - val_smape: 0.6961

Epoch 42/128

287/287 - 3s - 12ms/step - ia: 0.8558 - loss: 0.0931 - mae: 0.2295 - rmse: 0.3041 - smape: 0.5581 - val_ia: 0.7846 - val_loss: 0.1726 - val_mae: 0.3284 - val_rmse: 0.4055 - val_smape: 0.6804

Epoch 43/128

287/287 - 3s - 12ms/step - ia: 0.8567 - loss: 0.0920 - mae: 0.2280 - rmse: 0.3023 - smape: 0.5535 - val_ia: 0.7830 - val_loss: 0.1674 - val_mae: 0.3273 - val_rmse: 0.3954 - val_smape: 0.6871

Epoch 44/128

287/287 - 4s - 12ms/step - ia: 0.8573 - loss: 0.0910 - mae: 0.2268 - rmse: 0.3007 - smape: 0.5516 - val_ia: 0.7749 - val_loss: 0.1901 - val_mae: 0.3422 - val_rmse: 0.4270 - val_smape: 0.6966

Epoch 45/128

287/287 - 5s - 18ms/step - ia: 0.8591 - loss: 0.0896 - mae: 0.2246 - rmse: 0.2981 - smape: 0.5475 - val_ia: 0.7879 - val_loss: 0.1573 - val_mae: 0.3162 - val_rmse: 0.3854 - val_smape: 0.6771

Epoch 46/128

287/287 - 5s - 18ms/step - ia: 0.8584 - loss: 0.0903 - mae: 0.2257 - rmse: 0.2992 - smape: 0.5494 - val_ia: 0.7940 - val_loss: 0.1507 - val_mae: 0.3103 - val_rmse: 0.3781 - val_smape: 0.6632

Epoch 47/128

287/287 - 3s - 12ms/step - ia: 0.8590 - loss: 0.0887 - mae: 0.2244 - rmse: 0.2968 - smape: 0.5471 - val_ia: 0.7785 - val_loss: 0.1774 - val_mae: 0.3361 - val_rmse: 0.4108 - val_smape: 0.6943

Epoch 48/128

287/287 - 3s - 12ms/step - ia: 0.8596 - loss: 0.0887 - mae: 0.2237 - rmse: 0.2966 - smape: 0.5442 - val_ia: 0.7829 - val_loss: 0.1710 - val_mae: 0.3279 - val_rmse: 0.4030 - val_smape: 0.6850

Epoch 49/128

287/287 - 3s - 12ms/step - ia: 0.8603 - loss: 0.0878 - mae: 0.2229 - rmse: 0.2949 - smape: 0.5450 - val_ia: 0.7732 - val_loss: 0.1843 - val_mae: 0.3429 - val_rmse: 0.4149 - val_smape: 0.7075

Epoch 50/128

287/287 - 4s - 12ms/step - ia: 0.8612 - loss: 0.0867 - mae: 0.2214 - rmse: 0.2934 - smape: 0.5420 - val_ia: 0.7946 - val_loss: 0.1470 - val_mae: 0.3070 - val_rmse: 0.3717 - val_smape: 0.6629

Epoch 51/128

287/287 - 3s - 12ms/step - ia: 0.8610 - loss: 0.0867 - mae: 0.2213 - rmse: 0.2932 - smape: 0.5398 - val_ia: 0.7820 - val_loss: 0.1707 - val_mae: 0.3255 - val_rmse: 0.4037 - val_smape: 0.6849

Epoch 52/128

287/287 - 3s - 12ms/step - ia: 0.8618 - loss: 0.0860 - mae: 0.2206 - rmse: 0.2922 - smape: 0.5397 - val_ia: 0.7765 - val_loss: 0.1786 - val_mae: 0.3391 - val_rmse: 0.4096 - val_smape: 0.7031

Epoch 53/128

287/287 - 3s - 12ms/step - ia: 0.8631 - loss: 0.0845 - mae: 0.2185 - rmse: 0.2895 - smape: 0.5370 - val_ia: 0.7891 - val_loss: 0.1562 - val_mae: 0.3175 - val_rmse: 0.3839 - val_smape: 0.6736

Epoch 54/128

287/287 - 3s - 12ms/step - ia: 0.8637 - loss: 0.0837 - mae: 0.2177 - rmse: 0.2880 - smape: 0.5318 - val_ia: 0.7802 - val_loss: 0.1680 - val_mae: 0.3222 - val_rmse: 0.3987 - val_smape: 0.6858

Epoch 55/128

287/287 - 4s - 13ms/step - ia: 0.8636 - loss: 0.0839 - mae: 0.2175 - rmse: 0.2886 - smape: 0.5343 - val_ia: 0.7684 - val_loss: 0.1913 - val_mae: 0.3500 - val_rmse: 0.4226 - val_smape: 0.7169

Epoch 56/128

287/287 - 4s - 13ms/step - ia: 0.8643 - loss: 0.0834 - mae: 0.2170 - rmse: 0.2876 - smape: 0.5312 - val_ia: 0.7660 - val_loss: 0.2012 - val_mae: 0.3533 - val_rmse: 0.4365 - val_smape: 0.7137

Epoch 57/128

287/287 - 4s - 14ms/step - ia: 0.8646 - loss: 0.0828 - mae: 0.2163 - rmse: 0.2865 - smape: 0.5298 - val_ia: 0.7878 - val_loss: 0.1550 - val_mae: 0.3134 - val_rmse: 0.3819 - val_smape: 0.6714

Epoch 58/128

287/287 - 4s - 13ms/step - ia: 0.8654 - loss: 0.0821 - mae: 0.2149 - rmse: 0.2854 - smape: 0.5301 - val_ia: 0.7819 - val_loss: 0.1680 - val_mae: 0.3263 - val_rmse: 0.3951 - val_smape: 0.6894

Epoch 59/128

287/287 - 4s - 14ms/step - ia: 0.8654 - loss: 0.0819 - mae: 0.2149 - rmse: 0.2849 - smape: 0.5290 - val_ia: 0.7910 - val_loss: 0.1453 - val_mae: 0.3071 - val_rmse: 0.3686 - val_smape: 0.6662

Epoch 60/128

287/287 - 4s - 14ms/step - ia: 0.8666 - loss: 0.0805 - mae: 0.2134 - rmse: 0.2827 - smape: 0.5250 - val_ia: 0.7896 - val_loss: 0.1502 - val_mae: 0.3074 - val_rmse: 0.3744 - val_smape: 0.6705

Epoch 61/128

287/287 - 4s - 13ms/step - ia: 0.8660 - loss: 0.0809 - mae: 0.2142 - rmse: 0.2835 - smape: 0.5278 - val_ia: 0.7874 - val_loss: 0.1541 - val_mae: 0.3126 - val_rmse: 0.3773 - val_smape: 0.6759

Epoch 62/128

287/287 - 5s - 18ms/step - ia: 0.8661 - loss: 0.0811 - mae: 0.2142 - rmse: 0.2836 - smape: 0.5251 - val_ia: 0.7877 - val_loss: 0.1528 - val_mae: 0.3099 - val_rmse: 0.3776 - val_smape: 0.6726

Epoch 63/128

287/287 - 4s - 13ms/step - ia: 0.8668 - loss: 0.0806 - mae: 0.2132 - rmse: 0.2826 - smape: 0.5256 - val_ia: 0.7922 - val_loss: 0.1411 - val_mae: 0.3009 - val_rmse: 0.3618 - val_smape: 0.6605

Epoch 64/128

287/287 - 4s - 13ms/step - ia: 0.8668 - loss: 0.0805 - mae: 0.2129 - rmse: 0.2827 - smape: 0.5220 - val_ia: 0.7852 - val_loss: 0.1540 - val_mae: 0.3109 - val_rmse: 0.3783 - val_smape: 0.6758

Epoch 65/128

287/287 - 5s - 18ms/step - ia: 0.8678 - loss: 0.0791 - mae: 0.2116 - rmse: 0.2801 - smape: 0.5221 - val_ia: 0.7759 - val_loss: 0.1774 - val_mae: 0.3301 - val_rmse: 0.4066 - val_smape: 0.6981

Epoch 66/128

287/287 - 4s - 12ms/step - ia: 0.8684 - loss: 0.0788 - mae: 0.2107 - rmse: 0.2793 - smape: 0.5190 - val_ia: 0.7668 - val_loss: 0.1879 - val_mae: 0.3444 - val_rmse: 0.4163 - val_smape: 0.7173

Epoch 67/128

287/287 - 4s - 13ms/step - ia: 0.8689 - loss: 0.0782 - mae: 0.2102 - rmse: 0.2785 - smape: 0.5163 - val_ia: 0.7814 - val_loss: 0.1641 - val_mae: 0.3213 - val_rmse: 0.3887 - val_smape: 0.6873

Epoch 68/128

287/287 - 4s - 13ms/step - ia: 0.8700 - loss: 0.0770 - mae: 0.2082 - rmse: 0.2762 - smape: 0.5157 - val_ia: 0.7836 - val_loss: 0.1558 - val_mae: 0.3127 - val_rmse: 0.3784 - val_smape: 0.6805

Epoch 69/128

287/287 - 4s - 13ms/step - ia: 0.8697 - loss: 0.0770 - mae: 0.2089 - rmse: 0.2765 - smape: 0.5132 - val_ia: 0.7762 - val_loss: 0.1765 - val_mae: 0.3297 - val_rmse: 0.4049 - val_smape: 0.6910

Epoch 70/128

287/287 - 5s - 18ms/step - ia: 0.8696 - loss: 0.0772 - mae: 0.2087 - rmse: 0.2767 - smape: 0.5133 - val_ia: 0.7732 - val_loss: 0.1773 - val_mae: 0.3304 - val_rmse: 0.4060 - val_smape: 0.6991

Epoch 71/128

287/287 - 5s - 18ms/step - ia: 0.8700 - loss: 0.0772 - mae: 0.2083 - rmse: 0.2764 - smape: 0.5126 - val_ia: 0.7743 - val_loss: 0.1801 - val_mae: 0.3308 - val_rmse: 0.4101 - val_smape: 0.6957

Epoch 72/128

287/287 - 5s - 18ms/step - ia: 0.8705 - loss: 0.0765 - mae: 0.2077 - rmse: 0.2753 - smape: 0.5124 - val_ia: 0.7848 - val_loss: 0.1551 - val_mae: 0.3141 - val_rmse: 0.3740 - val_smape: 0.6799

Epoch 73/128

287/287 - 4s - 13ms/step - ia: 0.8709 - loss: 0.0759 - mae: 0.2068 - rmse: 0.2744 - smape: 0.5113 - val_ia: 0.7700 - val_loss: 0.1813 - val_mae: 0.3435 - val_rmse: 0.4071 - val_smape: 0.7099

Epoch 74/128

287/287 - 4s - 13ms/step - ia: 0.8714 - loss: 0.0756 - mae: 0.2062 - rmse: 0.2736 - smape: 0.5077 - val_ia: 0.7882 - val_loss: 0.1479 - val_mae: 0.3035 - val_rmse: 0.3693 - val_smape: 0.6685

Epoch 75/128

287/287 - 4s - 13ms/step - ia: 0.8719 - loss: 0.0748 - mae: 0.2057 - rmse: 0.2724 - smape: 0.5082 - val_ia: 0.7748 - val_loss: 0.1736 - val_mae: 0.3316 - val_rmse: 0.3974 - val_smape: 0.7006

Epoch 76/128

287/287 - 4s - 13ms/step - ia: 0.8719 - loss: 0.0750 - mae: 0.2055 - rmse: 0.2728 - smape: 0.5080 - val_ia: 0.7829 - val_loss: 0.1534 - val_mae: 0.3077 - val_rmse: 0.3748 - val_smape: 0.6779

Epoch 77/128

287/287 - 4s - 13ms/step - ia: 0.8722 - loss: 0.0749 - mae: 0.2048 - rmse: 0.2724 - smape: 0.5065 - val_ia: 0.7687 - val_loss: 0.1869 - val_mae: 0.3408 - val_rmse: 0.4137 - val_smape: 0.7131

Epoch 78/128

287/287 - 4s - 13ms/step - ia: 0.8735 - loss: 0.0736 - mae: 0.2031 - rmse: 0.2702 - smape: 0.5041 - val_ia: 0.7854 - val_loss: 0.1508 - val_mae: 0.3088 - val_rmse: 0.3685 - val_smape: 0.6754

Epoch 78: early stopping

Restoring model weights from the end of the best epoch: 63.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 34s 211ms/step
 15/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 53/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 93/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
151/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

100%|██████████| 12/12 [4:42:59<00:00, 1414.96s/trial, best loss: 0.1562418293598551]

In [21]:
print(best)

{'activation': 1, 'batch': 1, 'dropout': 0.4, 'layers': 2.0, 'learning_rate': 8.360431152477965e-05, 'units': 4}