Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [5]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [6]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [8]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [9]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [10]:
datosNormalizados.shape

(43800, 6)

In [11]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [12]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [13]:
futuros = 24
pasados  = 12

In [14]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [15]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [16]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 12, 6)
Las dimensiones de testX son:  (8797, 12, 6)
Las dimensiones de valX son:  (4333, 12, 6)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(GRU(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(GRU(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 16s - 67ms/step - ia: 0.1933 - loss: 1.1486 - mae: 0.8573 - rmse: 1.0668 - smape: 1.6114 - val_ia: 0.2558 - val_loss: 0.9829 - val_mae: 0.7633 - val_rmse: 0.9006 - val_smape: 1.7882

Epoch 2/128

240/240 - 4s - 17ms/step - ia: 0.1688 - loss: 1.0454 - mae: 0.7746 - rmse: 1.0158 - smape: 1.6228 - val_ia: 0.2529 - val_loss: 0.9678 - val_mae: 0.7367 - val_rmse: 0.8786 - val_smape: 1.9922

Epoch 3/128

240/240 - 5s - 20ms/step - ia: 0.1583 - loss: 1.0316 - mae: 0.7619 - rmse: 1.0100 - smape: 1.6291 - val_ia: 0.2529 - val_loss: 0.9664 - val_mae: 0.7337 - val_rmse: 0.8763 - val_smape: 1.9217

Epoch 4/128

240/240 - 3s - 13ms/step - ia: 0.1448 - loss: 1.0218 - mae: 0.7577 - rmse: 1.0047 - smape: 1.6595 - val_ia: 0.2529 - val_loss: 0.9653 - val_mae: 0.7325 - val_rmse: 0.8751 - val_smape: 1.8984

Epoch 5/128

240/240 - 4s - 18ms/step - ia: 0.1349 - loss: 1.0149 - mae: 0.7553 - rmse: 1.0010 - smape: 1.6865 - val_ia: 0.2526 - val_loss: 0.9632 - val_mae: 0.7290 - val_rmse: 0.8723 - val_smape: 1.8360

Epoch 6/128

240/240 - 4s - 18ms/step - ia: 0.1250 - loss: 1.0103 - mae: 0.7522 - rmse: 0.9990 - smape: 1.7019 - val_ia: 0.2531 - val_loss: 0.9622 - val_mae: 0.7329 - val_rmse: 0.8749 - val_smape: 1.9249

Epoch 7/128

240/240 - 4s - 18ms/step - ia: 0.1202 - loss: 1.0051 - mae: 0.7523 - rmse: 0.9970 - smape: 1.7241 - val_ia: 0.2529 - val_loss: 0.9578 - val_mae: 0.7282 - val_rmse: 0.8707 - val_smape: 1.8516

Epoch 8/128

240/240 - 4s - 18ms/step - ia: 0.1191 - loss: 0.9989 - mae: 0.7479 - rmse: 0.9936 - smape: 1.7267 - val_ia: 0.2537 - val_loss: 0.9526 - val_mae: 0.7293 - val_rmse: 0.8705 - val_smape: 1.8713

Epoch 9/128

240/240 - 5s - 21ms/step - ia: 0.1200 - loss: 0.9920 - mae: 0.7486 - rmse: 0.9893 - smape: 1.7334 - val_ia: 0.2533 - val_loss: 0.9406 - val_mae: 0.7203 - val_rmse: 0.8620 - val_smape: 1.7651

Epoch 10/128

240/240 - 5s - 21ms/step - ia: 0.1352 - loss: 0.9804 - mae: 0.7411 - rmse: 0.9839 - smape: 1.6902 - val_ia: 0.2541 - val_loss: 0.9226 - val_mae: 0.7142 - val_rmse: 0.8546 - val_smape: 1.6864

Epoch 11/128

240/240 - 5s - 22ms/step - ia: 0.1629 - loss: 0.9602 - mae: 0.7339 - rmse: 0.9736 - smape: 1.6300 - val_ia: 0.2582 - val_loss: 0.8985 - val_mae: 0.7092 - val_rmse: 0.8477 - val_smape: 1.5882

Epoch 12/128

240/240 - 3s - 13ms/step - ia: 0.2035 - loss: 0.9417 - mae: 0.7262 - rmse: 0.9646 - smape: 1.5495 - val_ia: 0.2614 - val_loss: 0.8726 - val_mae: 0.6968 - val_rmse: 0.8358 - val_smape: 1.4706

Epoch 13/128

240/240 - 6s - 26ms/step - ia: 0.2471 - loss: 0.9202 - mae: 0.7156 - rmse: 0.9533 - smape: 1.4689 - val_ia: 0.2669 - val_loss: 0.8548 - val_mae: 0.6873 - val_rmse: 0.8280 - val_smape: 1.3883

Epoch 14/128

240/240 - 5s - 23ms/step - ia: 0.2752 - loss: 0.9127 - mae: 0.7114 - rmse: 0.9498 - smape: 1.4214 - val_ia: 0.2683 - val_loss: 0.8422 - val_mae: 0.6777 - val_rmse: 0.8196 - val_smape: 1.3372

Epoch 15/128

240/240 - 5s - 21ms/step - ia: 0.2884 - loss: 0.9094 - mae: 0.7073 - rmse: 0.9486 - smape: 1.3979 - val_ia: 0.2729 - val_loss: 0.8370 - val_mae: 0.6778 - val_rmse: 0.8199 - val_smape: 1.3228

Epoch 16/128

240/240 - 5s - 20ms/step - ia: 0.3011 - loss: 0.9032 - mae: 0.7037 - rmse: 0.9452 - smape: 1.3743 - val_ia: 0.2742 - val_loss: 0.8312 - val_mae: 0.6716 - val_rmse: 0.8149 - val_smape: 1.2970

Epoch 17/128

240/240 - 6s - 25ms/step - ia: 0.3090 - loss: 0.8998 - mae: 0.7018 - rmse: 0.9439 - smape: 1.3626 - val_ia: 0.2768 - val_loss: 0.8276 - val_mae: 0.6731 - val_rmse: 0.8159 - val_smape: 1.2961

Epoch 18/128

240/240 - 5s - 20ms/step - ia: 0.3137 - loss: 0.8957 - mae: 0.7006 - rmse: 0.9398 - smape: 1.3563 - val_ia: 0.2779 - val_loss: 0.8234 - val_mae: 0.6700 - val_rmse: 0.8130 - val_smape: 1.2860

Epoch 19/128

240/240 - 4s - 18ms/step - ia: 0.3185 - loss: 0.8896 - mae: 0.6981 - rmse: 0.9389 - smape: 1.3477 - val_ia: 0.2809 - val_loss: 0.8218 - val_mae: 0.6713 - val_rmse: 0.8143 - val_smape: 1.2860

Epoch 20/128

240/240 - 4s - 18ms/step - ia: 0.3218 - loss: 0.8893 - mae: 0.6983 - rmse: 0.9374 - smape: 1.3443 - val_ia: 0.2793 - val_loss: 0.8179 - val_mae: 0.6659 - val_rmse: 0.8094 - val_smape: 1.2705

Epoch 21/128

240/240 - 5s - 21ms/step - ia: 0.3232 - loss: 0.8890 - mae: 0.6976 - rmse: 0.9378 - smape: 1.3418 - val_ia: 0.2822 - val_loss: 0.8171 - val_mae: 0.6692 - val_rmse: 0.8121 - val_smape: 1.2793

Epoch 22/128

240/240 - 4s - 19ms/step - ia: 0.3243 - loss: 0.8859 - mae: 0.6968 - rmse: 0.9356 - smape: 1.3399 - val_ia: 0.2819 - val_loss: 0.8144 - val_mae: 0.6659 - val_rmse: 0.8092 - val_smape: 1.2687

Epoch 23/128

240/240 - 5s - 20ms/step - ia: 0.3301 - loss: 0.8835 - mae: 0.6941 - rmse: 0.9345 - smape: 1.3286 - val_ia: 0.2827 - val_loss: 0.8122 - val_mae: 0.6647 - val_rmse: 0.8081 - val_smape: 1.2629

Epoch 24/128

240/240 - 5s - 21ms/step - ia: 0.3297 - loss: 0.8821 - mae: 0.6951 - rmse: 0.9337 - smape: 1.3284 - val_ia: 0.2824 - val_loss: 0.8103 - val_mae: 0.6629 - val_rmse: 0.8063 - val_smape: 1.2564

Epoch 25/128

240/240 - 5s - 22ms/step - ia: 0.3325 - loss: 0.8831 - mae: 0.6943 - rmse: 0.9340 - smape: 1.3238 - val_ia: 0.2821 - val_loss: 0.8099 - val_mae: 0.6624 - val_rmse: 0.8056 - val_smape: 1.2592

Epoch 26/128

240/240 - 5s - 22ms/step - ia: 0.3316 - loss: 0.8790 - mae: 0.6936 - rmse: 0.9328 - smape: 1.3271 - val_ia: 0.2830 - val_loss: 0.8080 - val_mae: 0.6609 - val_rmse: 0.8044 - val_smape: 1.2530

Epoch 27/128

240/240 - 4s - 19ms/step - ia: 0.3346 - loss: 0.8780 - mae: 0.6928 - rmse: 0.9308 - smape: 1.3244 - val_ia: 0.2833 - val_loss: 0.8063 - val_mae: 0.6605 - val_rmse: 0.8038 - val_smape: 1.2515

Epoch 28/128

240/240 - 5s - 19ms/step - ia: 0.3341 - loss: 0.8790 - mae: 0.6928 - rmse: 0.9321 - smape: 1.3234 - val_ia: 0.2857 - val_loss: 0.8072 - val_mae: 0.6655 - val_rmse: 0.8080 - val_smape: 1.2684

Epoch 29/128

240/240 - 4s - 19ms/step - ia: 0.3356 - loss: 0.8747 - mae: 0.6917 - rmse: 0.9295 - smape: 1.3232 - val_ia: 0.2849 - val_loss: 0.8046 - val_mae: 0.6614 - val_rmse: 0.8045 - val_smape: 1.2534

Epoch 30/128

240/240 - 6s - 25ms/step - ia: 0.3364 - loss: 0.8784 - mae: 0.6919 - rmse: 0.9328 - smape: 1.3205 - val_ia: 0.2851 - val_loss: 0.8030 - val_mae: 0.6605 - val_rmse: 0.8034 - val_smape: 1.2526

Epoch 31/128

240/240 - 4s - 18ms/step - ia: 0.3391 - loss: 0.8741 - mae: 0.6900 - rmse: 0.9297 - smape: 1.3193 - val_ia: 0.2873 - val_loss: 0.8022 - val_mae: 0.6611 - val_rmse: 0.8041 - val_smape: 1.2538

Epoch 32/128

240/240 - 5s - 23ms/step - ia: 0.3398 - loss: 0.8720 - mae: 0.6909 - rmse: 0.9290 - smape: 1.3198 - val_ia: 0.2863 - val_loss: 0.8007 - val_mae: 0.6580 - val_rmse: 0.8014 - val_smape: 1.2460

Epoch 33/128

240/240 - 5s - 20ms/step - ia: 0.3396 - loss: 0.8752 - mae: 0.6913 - rmse: 0.9286 - smape: 1.3182 - val_ia: 0.2871 - val_loss: 0.8006 - val_mae: 0.6590 - val_rmse: 0.8019 - val_smape: 1.2532

Epoch 34/128

240/240 - 6s - 24ms/step - ia: 0.3373 - loss: 0.8741 - mae: 0.6902 - rmse: 0.9294 - smape: 1.3235 - val_ia: 0.2883 - val_loss: 0.8002 - val_mae: 0.6601 - val_rmse: 0.8030 - val_smape: 1.2534

Epoch 35/128

240/240 - 5s - 20ms/step - ia: 0.3397 - loss: 0.8692 - mae: 0.6901 - rmse: 0.9276 - smape: 1.3199 - val_ia: 0.2869 - val_loss: 0.7971 - val_mae: 0.6556 - val_rmse: 0.7990 - val_smape: 1.2391

Epoch 36/128

240/240 - 4s - 18ms/step - ia: 0.3419 - loss: 0.8711 - mae: 0.6897 - rmse: 0.9278 - smape: 1.3182 - val_ia: 0.2886 - val_loss: 0.7976 - val_mae: 0.6581 - val_rmse: 0.8010 - val_smape: 1.2505

Epoch 37/128

240/240 - 5s - 21ms/step - ia: 0.3447 - loss: 0.8693 - mae: 0.6886 - rmse: 0.9271 - smape: 1.3142 - val_ia: 0.2870 - val_loss: 0.7967 - val_mae: 0.6570 - val_rmse: 0.7998 - val_smape: 1.2463

Epoch 38/128

240/240 - 4s - 18ms/step - ia: 0.3417 - loss: 0.8652 - mae: 0.6889 - rmse: 0.9243 - smape: 1.3209 - val_ia: 0.2896 - val_loss: 0.7957 - val_mae: 0.6592 - val_rmse: 0.8018 - val_smape: 1.2503

Epoch 39/128

240/240 - 5s - 23ms/step - ia: 0.3451 - loss: 0.8655 - mae: 0.6872 - rmse: 0.9247 - smape: 1.3114 - val_ia: 0.2906 - val_loss: 0.7952 - val_mae: 0.6591 - val_rmse: 0.8019 - val_smape: 1.2505

Epoch 40/128

240/240 - 4s - 19ms/step - ia: 0.3479 - loss: 0.8615 - mae: 0.6865 - rmse: 0.9228 - smape: 1.3111 - val_ia: 0.2903 - val_loss: 0.7937 - val_mae: 0.6566 - val_rmse: 0.7996 - val_smape: 1.2451

Epoch 41/128

240/240 - 5s - 20ms/step - ia: 0.3422 - loss: 0.8671 - mae: 0.6889 - rmse: 0.9259 - smape: 1.3204 - val_ia: 0.2911 - val_loss: 0.7941 - val_mae: 0.6594 - val_rmse: 0.8019 - val_smape: 1.2558

Epoch 42/128

240/240 - 6s - 23ms/step - ia: 0.3479 - loss: 0.8583 - mae: 0.6865 - rmse: 0.9207 - smape: 1.3156 - val_ia: 0.2923 - val_loss: 0.7922 - val_mae: 0.6568 - val_rmse: 0.8001 - val_smape: 1.2428

Epoch 43/128

240/240 - 4s - 17ms/step - ia: 0.3482 - loss: 0.8612 - mae: 0.6861 - rmse: 0.9223 - smape: 1.3116 - val_ia: 0.2918 - val_loss: 0.7916 - val_mae: 0.6566 - val_rmse: 0.7995 - val_smape: 1.2480

Epoch 44/128

240/240 - 5s - 23ms/step - ia: 0.3430 - loss: 0.8659 - mae: 0.6881 - rmse: 0.9254 - smape: 1.3195 - val_ia: 0.2924 - val_loss: 0.7910 - val_mae: 0.6569 - val_rmse: 0.7998 - val_smape: 1.2489

Epoch 45/128

240/240 - 4s - 17ms/step - ia: 0.3506 - loss: 0.8586 - mae: 0.6842 - rmse: 0.9201 - smape: 1.3113 - val_ia: 0.2923 - val_loss: 0.7894 - val_mae: 0.6543 - val_rmse: 0.7976 - val_smape: 1.2425

Epoch 46/128

240/240 - 4s - 18ms/step - ia: 0.3492 - loss: 0.8619 - mae: 0.6853 - rmse: 0.9222 - smape: 1.3129 - val_ia: 0.2919 - val_loss: 0.7890 - val_mae: 0.6552 - val_rmse: 0.7980 - val_smape: 1.2471

Epoch 47/128

240/240 - 4s - 17ms/step - ia: 0.3485 - loss: 0.8590 - mae: 0.6854 - rmse: 0.9203 - smape: 1.3154 - val_ia: 0.2931 - val_loss: 0.7891 - val_mae: 0.6557 - val_rmse: 0.7987 - val_smape: 1.2490

Epoch 48/128

240/240 - 5s - 19ms/step - ia: 0.3493 - loss: 0.8564 - mae: 0.6847 - rmse: 0.9193 - smape: 1.3134 - val_ia: 0.2943 - val_loss: 0.7888 - val_mae: 0.6565 - val_rmse: 0.7995 - val_smape: 1.2521

Epoch 49/128

240/240 - 5s - 20ms/step - ia: 0.3492 - loss: 0.8629 - mae: 0.6850 - rmse: 0.9226 - smape: 1.3119 - val_ia: 0.2943 - val_loss: 0.7885 - val_mae: 0.6570 - val_rmse: 0.7996 - val_smape: 1.2585

Epoch 50/128

240/240 - 4s - 17ms/step - ia: 0.3496 - loss: 0.8578 - mae: 0.6840 - rmse: 0.9203 - smape: 1.3172 - val_ia: 0.2957 - val_loss: 0.7879 - val_mae: 0.6553 - val_rmse: 0.7988 - val_smape: 1.2504

Epoch 51/128

240/240 - 5s - 22ms/step - ia: 0.3488 - loss: 0.8612 - mae: 0.6857 - rmse: 0.9232 - smape: 1.3155 - val_ia: 0.2940 - val_loss: 0.7864 - val_mae: 0.6528 - val_rmse: 0.7962 - val_smape: 1.2495

Epoch 52/128

240/240 - 4s - 17ms/step - ia: 0.3489 - loss: 0.8598 - mae: 0.6857 - rmse: 0.9219 - smape: 1.3182 - val_ia: 0.2945 - val_loss: 0.7863 - val_mae: 0.6532 - val_rmse: 0.7967 - val_smape: 1.2500

Epoch 53/128

240/240 - 5s - 21ms/step - ia: 0.3497 - loss: 0.8609 - mae: 0.6845 - rmse: 0.9224 - smape: 1.3156 - val_ia: 0.2949 - val_loss: 0.7860 - val_mae: 0.6538 - val_rmse: 0.7971 - val_smape: 1.2545

Epoch 54/128

240/240 - 5s - 22ms/step - ia: 0.3527 - loss: 0.8512 - mae: 0.6815 - rmse: 0.9179 - smape: 1.3131 - val_ia: 0.2964 - val_loss: 0.7858 - val_mae: 0.6548 - val_rmse: 0.7983 - val_smape: 1.2556

Epoch 55/128

240/240 - 5s - 22ms/step - ia: 0.3492 - loss: 0.8607 - mae: 0.6845 - rmse: 0.9236 - smape: 1.3177 - val_ia: 0.2946 - val_loss: 0.7840 - val_mae: 0.6524 - val_rmse: 0.7956 - val_smape: 1.2547

Epoch 56/128

240/240 - 4s - 18ms/step - ia: 0.3501 - loss: 0.8541 - mae: 0.6825 - rmse: 0.9179 - smape: 1.3202 - val_ia: 0.2960 - val_loss: 0.7838 - val_mae: 0.6526 - val_rmse: 0.7963 - val_smape: 1.2534

Epoch 57/128

240/240 - 4s - 17ms/step - ia: 0.3511 - loss: 0.8535 - mae: 0.6837 - rmse: 0.9190 - smape: 1.3205 - val_ia: 0.2953 - val_loss: 0.7829 - val_mae: 0.6504 - val_rmse: 0.7945 - val_smape: 1.2451

Epoch 58/128

240/240 - 4s - 17ms/step - ia: 0.3524 - loss: 0.8553 - mae: 0.6819 - rmse: 0.9193 - smape: 1.3150 - val_ia: 0.2976 - val_loss: 0.7846 - val_mae: 0.6560 - val_rmse: 0.7991 - val_smape: 1.2659

Epoch 59/128

240/240 - 4s - 18ms/step - ia: 0.3550 - loss: 0.8510 - mae: 0.6822 - rmse: 0.9161 - smape: 1.3139 - val_ia: 0.2968 - val_loss: 0.7825 - val_mae: 0.6520 - val_rmse: 0.7960 - val_smape: 1.2527

Epoch 60/128

240/240 - 4s - 18ms/step - ia: 0.3529 - loss: 0.8519 - mae: 0.6806 - rmse: 0.9173 - smape: 1.3156 - val_ia: 0.2982 - val_loss: 0.7824 - val_mae: 0.6531 - val_rmse: 0.7971 - val_smape: 1.2566

Epoch 61/128

240/240 - 4s - 17ms/step - ia: 0.3581 - loss: 0.8478 - mae: 0.6804 - rmse: 0.9162 - smape: 1.3126 - val_ia: 0.2962 - val_loss: 0.7810 - val_mae: 0.6506 - val_rmse: 0.7946 - val_smape: 1.2554

Epoch 62/128

240/240 - 4s - 18ms/step - ia: 0.3538 - loss: 0.8512 - mae: 0.6821 - rmse: 0.9179 - smape: 1.3177 - val_ia: 0.2961 - val_loss: 0.7807 - val_mae: 0.6513 - val_rmse: 0.7950 - val_smape: 1.2594

Epoch 63/128

240/240 - 4s - 17ms/step - ia: 0.3519 - loss: 0.8538 - mae: 0.6819 - rmse: 0.9189 - smape: 1.3218 - val_ia: 0.2976 - val_loss: 0.7810 - val_mae: 0.6524 - val_rmse: 0.7964 - val_smape: 1.2602

Epoch 64/128

240/240 - 5s - 21ms/step - ia: 0.3562 - loss: 0.8475 - mae: 0.6797 - rmse: 0.9164 - smape: 1.3150 - val_ia: 0.2959 - val_loss: 0.7796 - val_mae: 0.6500 - val_rmse: 0.7941 - val_smape: 1.2557

Epoch 65/128

240/240 - 5s - 22ms/step - ia: 0.3554 - loss: 0.8456 - mae: 0.6799 - rmse: 0.9142 - smape: 1.3173 - val_ia: 0.2978 - val_loss: 0.7786 - val_mae: 0.6496 - val_rmse: 0.7942 - val_smape: 1.2516

Epoch 66/128

240/240 - 4s - 18ms/step - ia: 0.3581 - loss: 0.8466 - mae: 0.6787 - rmse: 0.9147 - smape: 1.3121 - val_ia: 0.2997 - val_loss: 0.7796 - val_mae: 0.6524 - val_rmse: 0.7967 - val_smape: 1.2603

Epoch 67/128

240/240 - 4s - 18ms/step - ia: 0.3550 - loss: 0.8476 - mae: 0.6797 - rmse: 0.9149 - smape: 1.3150 - val_ia: 0.3012 - val_loss: 0.7802 - val_mae: 0.6545 - val_rmse: 0.7986 - val_smape: 1.2665

Epoch 68/128

240/240 - 5s - 21ms/step - ia: 0.3573 - loss: 0.8469 - mae: 0.6786 - rmse: 0.9149 - smape: 1.3149 - val_ia: 0.3014 - val_loss: 0.7794 - val_mae: 0.6532 - val_rmse: 0.7974 - val_smape: 1.2658

Epoch 69/128

240/240 - 5s - 22ms/step - ia: 0.3595 - loss: 0.8473 - mae: 0.6790 - rmse: 0.9149 - smape: 1.3127 - val_ia: 0.2989 - val_loss: 0.7779 - val_mae: 0.6515 - val_rmse: 0.7954 - val_smape: 1.2674

Epoch 70/128

240/240 - 5s - 22ms/step - ia: 0.3568 - loss: 0.8450 - mae: 0.6788 - rmse: 0.9152 - smape: 1.3177 - val_ia: 0.3000 - val_loss: 0.7781 - val_mae: 0.6517 - val_rmse: 0.7959 - val_smape: 1.2647

Epoch 71/128

240/240 - 5s - 22ms/step - ia: 0.3554 - loss: 0.8482 - mae: 0.6796 - rmse: 0.9164 - smape: 1.3182 - val_ia: 0.3001 - val_loss: 0.7779 - val_mae: 0.6517 - val_rmse: 0.7959 - val_smape: 1.2693

Epoch 72/128

240/240 - 5s - 22ms/step - ia: 0.3599 - loss: 0.8423 - mae: 0.6771 - rmse: 0.9123 - smape: 1.3118 - val_ia: 0.3013 - val_loss: 0.7776 - val_mae: 0.6511 - val_rmse: 0.7959 - val_smape: 1.2633

Epoch 73/128

240/240 - 5s - 22ms/step - ia: 0.3584 - loss: 0.8493 - mae: 0.6795 - rmse: 0.9159 - smape: 1.3168 - val_ia: 0.2974 - val_loss: 0.7759 - val_mae: 0.6479 - val_rmse: 0.7921 - val_smape: 1.2656

Epoch 74/128

240/240 - 4s - 18ms/step - ia: 0.3594 - loss: 0.8391 - mae: 0.6758 - rmse: 0.9108 - smape: 1.3151 - val_ia: 0.3029 - val_loss: 0.7782 - val_mae: 0.6525 - val_rmse: 0.7973 - val_smape: 1.2662

Epoch 75/128

240/240 - 4s - 18ms/step - ia: 0.3614 - loss: 0.8459 - mae: 0.6774 - rmse: 0.9148 - smape: 1.3096 - val_ia: 0.3001 - val_loss: 0.7759 - val_mae: 0.6491 - val_rmse: 0.7937 - val_smape: 1.2654

Epoch 76/128

240/240 - 5s - 22ms/step - ia: 0.3595 - loss: 0.8409 - mae: 0.6764 - rmse: 0.9115 - smape: 1.3155 - val_ia: 0.3031 - val_loss: 0.7770 - val_mae: 0.6500 - val_rmse: 0.7953 - val_smape: 1.2625

Epoch 77/128

240/240 - 4s - 18ms/step - ia: 0.3608 - loss: 0.8455 - mae: 0.6768 - rmse: 0.9136 - smape: 1.3125 - val_ia: 0.3033 - val_loss: 0.7773 - val_mae: 0.6513 - val_rmse: 0.7964 - val_smape: 1.2686

Epoch 78/128

240/240 - 5s - 22ms/step - ia: 0.3616 - loss: 0.8440 - mae: 0.6771 - rmse: 0.9132 - smape: 1.3138 - val_ia: 0.3001 - val_loss: 0.7756 - val_mae: 0.6488 - val_rmse: 0.7934 - val_smape: 1.2682

Epoch 79/128

240/240 - 4s - 18ms/step - ia: 0.3615 - loss: 0.8395 - mae: 0.6767 - rmse: 0.9118 - smape: 1.3129 - val_ia: 0.3001 - val_loss: 0.7755 - val_mae: 0.6495 - val_rmse: 0.7939 - val_smape: 1.2709

Epoch 80/128

240/240 - 5s - 22ms/step - ia: 0.3599 - loss: 0.8419 - mae: 0.6768 - rmse: 0.9119 - smape: 1.3186 - val_ia: 0.3028 - val_loss: 0.7752 - val_mae: 0.6493 - val_rmse: 0.7944 - val_smape: 1.2657

Epoch 81/128

240/240 - 5s - 22ms/step - ia: 0.3598 - loss: 0.8452 - mae: 0.6770 - rmse: 0.9142 - smape: 1.3154 - val_ia: 0.3021 - val_loss: 0.7752 - val_mae: 0.6498 - val_rmse: 0.7946 - val_smape: 1.2706

Epoch 82/128

240/240 - 5s - 22ms/step - ia: 0.3619 - loss: 0.8424 - mae: 0.6756 - rmse: 0.9115 - smape: 1.3128 - val_ia: 0.3022 - val_loss: 0.7746 - val_mae: 0.6494 - val_rmse: 0.7942 - val_smape: 1.2719

Epoch 83/128

240/240 - 5s - 22ms/step - ia: 0.3621 - loss: 0.8392 - mae: 0.6758 - rmse: 0.9103 - smape: 1.3166 - val_ia: 0.3029 - val_loss: 0.7757 - val_mae: 0.6513 - val_rmse: 0.7961 - val_smape: 1.2733

Epoch 84/128

240/240 - 4s - 15ms/step - ia: 0.3601 - loss: 0.8459 - mae: 0.6777 - rmse: 0.9141 - smape: 1.3173 - val_ia: 0.3006 - val_loss: 0.7745 - val_mae: 0.6505 - val_rmse: 0.7945 - val_smape: 1.2832

Epoch 85/128

240/240 - 6s - 26ms/step - ia: 0.3600 - loss: 0.8388 - mae: 0.6758 - rmse: 0.9103 - smape: 1.3178 - val_ia: 0.3031 - val_loss: 0.7754 - val_mae: 0.6511 - val_rmse: 0.7960 - val_smape: 1.2756

Epoch 86/128

240/240 - 5s - 22ms/step - ia: 0.3612 - loss: 0.8404 - mae: 0.6759 - rmse: 0.9106 - smape: 1.3159 - val_ia: 0.3027 - val_loss: 0.7754 - val_mae: 0.6521 - val_rmse: 0.7966 - val_smape: 1.2813

Epoch 87/128

240/240 - 5s - 19ms/step - ia: 0.3587 - loss: 0.8421 - mae: 0.6762 - rmse: 0.9120 - smape: 1.3211 - val_ia: 0.3048 - val_loss: 0.7757 - val_mae: 0.6518 - val_rmse: 0.7971 - val_smape: 1.2746

Epoch 88/128

240/240 - 4s - 16ms/step - ia: 0.3614 - loss: 0.8396 - mae: 0.6766 - rmse: 0.9113 - smape: 1.3225 - val_ia: 0.3046 - val_loss: 0.7760 - val_mae: 0.6529 - val_rmse: 0.7978 - val_smape: 1.2808

Epoch 89/128

240/240 - 4s - 17ms/step - ia: 0.3629 - loss: 0.8410 - mae: 0.6769 - rmse: 0.9115 - smape: 1.3157 - val_ia: 0.3026 - val_loss: 0.7724 - val_mae: 0.6476 - val_rmse: 0.7927 - val_smape: 1.2718

Epoch 90/128

240/240 - 4s - 18ms/step - ia: 0.3621 - loss: 0.8401 - mae: 0.6761 - rmse: 0.9108 - smape: 1.3172 - val_ia: 0.3032 - val_loss: 0.7747 - val_mae: 0.6522 - val_rmse: 0.7964 - val_smape: 1.2913

Epoch 91/128

240/240 - 3s - 14ms/step - ia: 0.3610 - loss: 0.8406 - mae: 0.6757 - rmse: 0.9112 - smape: 1.3206 - val_ia: 0.3036 - val_loss: 0.7731 - val_mae: 0.6493 - val_rmse: 0.7942 - val_smape: 1.2759

Epoch 92/128

240/240 - 4s - 18ms/step - ia: 0.3591 - loss: 0.8393 - mae: 0.6756 - rmse: 0.9103 - smape: 1.3240 - val_ia: 0.3060 - val_loss: 0.7754 - val_mae: 0.6532 - val_rmse: 0.7980 - val_smape: 1.2855

Epoch 93/128

240/240 - 5s - 22ms/step - ia: 0.3635 - loss: 0.8399 - mae: 0.6758 - rmse: 0.9107 - smape: 1.3173 - val_ia: 0.3034 - val_loss: 0.7729 - val_mae: 0.6496 - val_rmse: 0.7945 - val_smape: 1.2819

Epoch 94/128

240/240 - 4s - 18ms/step - ia: 0.3587 - loss: 0.8404 - mae: 0.6764 - rmse: 0.9118 - smape: 1.3207 - val_ia: 0.3029 - val_loss: 0.7722 - val_mae: 0.6483 - val_rmse: 0.7935 - val_smape: 1.2749

Epoch 95/128

240/240 - 5s - 23ms/step - ia: 0.3630 - loss: 0.8382 - mae: 0.6746 - rmse: 0.9102 - smape: 1.3160 - val_ia: 0.3044 - val_loss: 0.7734 - val_mae: 0.6508 - val_rmse: 0.7956 - val_smape: 1.2840

Epoch 96/128

240/240 - 5s - 21ms/step - ia: 0.3599 - loss: 0.8418 - mae: 0.6762 - rmse: 0.9125 - smape: 1.3235 - val_ia: 0.3039 - val_loss: 0.7716 - val_mae: 0.6487 - val_rmse: 0.7935 - val_smape: 1.2826

Epoch 97/128

240/240 - 4s - 18ms/step - ia: 0.3635 - loss: 0.8384 - mae: 0.6738 - rmse: 0.9111 - smape: 1.3155 - val_ia: 0.3062 - val_loss: 0.7721 - val_mae: 0.6488 - val_rmse: 0.7942 - val_smape: 1.2779

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 66s - 34ms/step - ia: 0.3785 - loss: 0.8236 - mae: 0.6675 - rmse: 0.8741 - smape: 1.2993 - val_ia: 0.2593 - val_loss: 0.7889 - val_mae: 0.6318 - val_rmse: 0.7091 - val_smape: 1.1579

Epoch 2/128

1915/1915 - 44s - 23ms/step - ia: 0.4100 - loss: 0.7880 - mae: 0.6482 - rmse: 0.8533 - smape: 1.2458 - val_ia: 0.2576 - val_loss: 0.7738 - val_mae: 0.6294 - val_rmse: 0.7061 - val_smape: 1.1619

Epoch 3/128

1915/1915 - 49s - 26ms/step - ia: 0.4205 - loss: 0.7711 - mae: 0.6395 - rmse: 0.8451 - smape: 1.2303 - val_ia: 0.2490 - val_loss: 0.7476 - val_mae: 0.6456 - val_rmse: 0.7116 - val_smape: 1.2913

Epoch 4/128

1915/1915 - 48s - 25ms/step - ia: 0.4288 - loss: 0.7588 - mae: 0.6344 - rmse: 0.8381 - smape: 1.2193 - val_ia: 0.2492 - val_loss: 0.7944 - val_mae: 0.6503 - val_rmse: 0.7239 - val_smape: 1.2447

Epoch 5/128

1915/1915 - 51s - 27ms/step - ia: 0.4351 - loss: 0.7466 - mae: 0.6291 - rmse: 0.8325 - smape: 1.2106 - val_ia: 0.2512 - val_loss: 0.7650 - val_mae: 0.6467 - val_rmse: 0.7169 - val_smape: 1.2705

Epoch 6/128

1915/1915 - 80s - 42ms/step - ia: 0.4463 - loss: 0.7269 - mae: 0.6197 - rmse: 0.8215 - smape: 1.1949 - val_ia: 0.2572 - val_loss: 0.8295 - val_mae: 0.6427 - val_rmse: 0.7208 - val_smape: 1.1841

Epoch 7/128

1915/1915 - 49s - 26ms/step - ia: 0.4566 - loss: 0.7031 - mae: 0.6112 - rmse: 0.8078 - smape: 1.1780 - val_ia: 0.2487 - val_loss: 0.7997 - val_mae: 0.6469 - val_rmse: 0.7195 - val_smape: 1.2785

Epoch 8/128

1915/1915 - 51s - 27ms/step - ia: 0.4680 - loss: 0.6777 - mae: 0.6001 - rmse: 0.7940 - smape: 1.1642 - val_ia: 0.2571 - val_loss: 0.8231 - val_mae: 0.6422 - val_rmse: 0.7231 - val_smape: 1.2037

Epoch 9/128

1915/1915 - 72s - 38ms/step - ia: 0.4846 - loss: 0.6459 - mae: 0.5867 - rmse: 0.7748 - smape: 1.1466 - val_ia: 0.2532 - val_loss: 0.9110 - val_mae: 0.6673 - val_rmse: 0.7453 - val_smape: 1.2609

Epoch 10/128

1915/1915 - 46s - 24ms/step - ia: 0.5007 - loss: 0.6076 - mae: 0.5708 - rmse: 0.7533 - smape: 1.1262 - val_ia: 0.2536 - val_loss: 0.8465 - val_mae: 0.6522 - val_rmse: 0.7311 - val_smape: 1.2182

Epoch 11/128

1915/1915 - 48s - 25ms/step - ia: 0.5185 - loss: 0.5704 - mae: 0.5534 - rmse: 0.7303 - smape: 1.1009 - val_ia: 0.2486 - val_loss: 0.9680 - val_mae: 0.6761 - val_rmse: 0.7606 - val_smape: 1.2418

Epoch 12/128

1915/1915 - 53s - 27ms/step - ia: 0.5396 - loss: 0.5275 - mae: 0.5340 - rmse: 0.7012 - smape: 1.0746 - val_ia: 0.2533 - val_loss: 0.9434 - val_mae: 0.6738 - val_rmse: 0.7606 - val_smape: 1.2234

Epoch 13/128

1915/1915 - 78s - 41ms/step - ia: 0.5611 - loss: 0.4828 - mae: 0.5128 - rmse: 0.6726 - smape: 1.0439 - val_ia: 0.2532 - val_loss: 0.9734 - val_mae: 0.6911 - val_rmse: 0.7823 - val_smape: 1.2402

Epoch 14/128

1915/1915 - 45s - 23ms/step - ia: 0.5830 - loss: 0.4416 - mae: 0.4928 - rmse: 0.6441 - smape: 1.0161 - val_ia: 0.2489 - val_loss: 0.9632 - val_mae: 0.6838 - val_rmse: 0.7784 - val_smape: 1.2357

Epoch 15/128

1915/1915 - 87s - 45ms/step - ia: 0.6038 - loss: 0.4036 - mae: 0.4723 - rmse: 0.6162 - smape: 0.9834 - val_ia: 0.2394 - val_loss: 1.0662 - val_mae: 0.7140 - val_rmse: 0.8098 - val_smape: 1.2545

Epoch 16/128

1915/1915 - 50s - 26ms/step - ia: 0.6273 - loss: 0.3606 - mae: 0.4475 - rmse: 0.5832 - smape: 0.9435 - val_ia: 0.2439 - val_loss: 1.1182 - val_mae: 0.7239 - val_rmse: 0.8309 - val_smape: 1.2343

Epoch 17/128

1915/1915 - 52s - 27ms/step - ia: 0.6503 - loss: 0.3214 - mae: 0.4244 - rmse: 0.5504 - smape: 0.9075 - val_ia: 0.2403 - val_loss: 1.0787 - val_mae: 0.7194 - val_rmse: 0.8259 - val_smape: 1.2141

Epoch 18/128

1915/1915 - 82s - 43ms/step - ia: 0.6690 - loss: 0.2910 - mae: 0.4030 - rmse: 0.5236 - smape: 0.8732 - val_ia: 0.2413 - val_loss: 1.0402 - val_mae: 0.7134 - val_rmse: 0.8189 - val_smape: 1.2228

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:21 1s/step
  7/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 32/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 40/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 62/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 70/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
102/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
107/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 17%|█▋        | 2/12 [27:53<2:25:50, 875.00s/trial, best loss: 0.7654894358534513]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 59s - 15ms/step - ia: 0.2230 - loss: 1.0542 - mae: 0.8135 - rmse: 0.9756 - smape: 1.6853 - val_ia: 0.1733 - val_loss: 1.0474 - val_mae: 0.8175 - val_rmse: 0.8532 - val_smape: 1.7121

Epoch 2/128

3830/3830 - 52s - 14ms/step - ia: 0.2221 - loss: 1.0305 - mae: 0.7967 - rmse: 0.9605 - smape: 1.7132 - val_ia: 0.1762 - val_loss: 1.0162 - val_mae: 0.7959 - val_rmse: 0.8318 - val_smape: 1.7354

Epoch 3/128

3830/3830 - 75s - 20ms/step - ia: 0.2215 - loss: 1.0149 - mae: 0.7849 - rmse: 0.9499 - smape: 1.7423 - val_ia: 0.1788 - val_loss: 0.9943 - val_mae: 0.7804 - val_rmse: 0.8163 - val_smape: 1.7585

Epoch 4/128

3830/3830 - 47s - 12ms/step - ia: 0.2192 - loss: 1.0055 - mae: 0.7768 - rmse: 0.9452 - smape: 1.7610 - val_ia: 0.1801 - val_loss: 0.9781 - val_mae: 0.7687 - val_rmse: 0.8047 - val_smape: 1.7786

Epoch 5/128

3830/3830 - 48s - 13ms/step - ia: 0.2225 - loss: 0.9985 - mae: 0.7708 - rmse: 0.9400 - smape: 1.7779 - val_ia: 0.1816 - val_loss: 0.9659 - val_mae: 0.7599 - val_rmse: 0.7960 - val_smape: 1.7907

Epoch 6/128

3830/3830 - 45s - 12ms/step - ia: 0.2216 - loss: 0.9923 - mae: 0.7661 - rmse: 0.9363 - smape: 1.7902 - val_ia: 0.1829 - val_loss: 0.9563 - val_mae: 0.7531 - val_rmse: 0.7893 - val_smape: 1.7959

Epoch 7/128

3830/3830 - 42s - 11ms/step - ia: 0.2222 - loss: 0.9860 - mae: 0.7629 - rmse: 0.9328 - smape: 1.7958 - val_ia: 0.1841 - val_loss: 0.9481 - val_mae: 0.7478 - val_rmse: 0.7840 - val_smape: 1.7962

Epoch 8/128

3830/3830 - 44s - 12ms/step - ia: 0.2259 - loss: 0.9815 - mae: 0.7593 - rmse: 0.9306 - smape: 1.7898 - val_ia: 0.1853 - val_loss: 0.9408 - val_mae: 0.7434 - val_rmse: 0.7797 - val_smape: 1.7909

Epoch 9/128

3830/3830 - 43s - 11ms/step - ia: 0.2224 - loss: 0.9786 - mae: 0.7571 - rmse: 0.9283 - smape: 1.7878 - val_ia: 0.1862 - val_loss: 0.9341 - val_mae: 0.7396 - val_rmse: 0.7759 - val_smape: 1.7806

Epoch 10/128

3830/3830 - 36s - 9ms/step - ia: 0.2289 - loss: 0.9722 - mae: 0.7544 - rmse: 0.9246 - smape: 1.7763 - val_ia: 0.1869 - val_loss: 0.9276 - val_mae: 0.7364 - val_rmse: 0.7727 - val_smape: 1.7666

Epoch 11/128

3830/3830 - 42s - 11ms/step - ia: 0.2297 - loss: 0.9705 - mae: 0.7526 - rmse: 0.9256 - smape: 1.7648 - val_ia: 0.1875 - val_loss: 0.9217 - val_mae: 0.7335 - val_rmse: 0.7699 - val_smape: 1.7514

Epoch 12/128

3830/3830 - 38s - 10ms/step - ia: 0.2304 - loss: 0.9654 - mae: 0.7505 - rmse: 0.9214 - smape: 1.7528 - val_ia: 0.1881 - val_loss: 0.9157 - val_mae: 0.7308 - val_rmse: 0.7673 - val_smape: 1.7351

Epoch 13/128

3830/3830 - 40s - 11ms/step - ia: 0.2324 - loss: 0.9609 - mae: 0.7486 - rmse: 0.9211 - smape: 1.7407 - val_ia: 0.1885 - val_loss: 0.9100 - val_mae: 0.7284 - val_rmse: 0.7649 - val_smape: 1.7186

Epoch 14/128

3830/3830 - 31s - 8ms/step - ia: 0.2342 - loss: 0.9574 - mae: 0.7473 - rmse: 0.9173 - smape: 1.7302 - val_ia: 0.1888 - val_loss: 0.9046 - val_mae: 0.7262 - val_rmse: 0.7627 - val_smape: 1.7026

Epoch 15/128

3830/3830 - 35s - 9ms/step - ia: 0.2362 - loss: 0.9545 - mae: 0.7459 - rmse: 0.9173 - smape: 1.7191 - val_ia: 0.1889 - val_loss: 0.8995 - val_mae: 0.7242 - val_rmse: 0.7607 - val_smape: 1.6875

Epoch 16/128

3830/3830 - 44s - 11ms/step - ia: 0.2392 - loss: 0.9499 - mae: 0.7440 - rmse: 0.9164 - smape: 1.7041 - val_ia: 0.1889 - val_loss: 0.8946 - val_mae: 0.7224 - val_rmse: 0.7589 - val_smape: 1.6729

Epoch 17/128

3830/3830 - 76s - 20ms/step - ia: 0.2429 - loss: 0.9472 - mae: 0.7425 - rmse: 0.9143 - smape: 1.6897 - val_ia: 0.1889 - val_loss: 0.8898 - val_mae: 0.7204 - val_rmse: 0.7569 - val_smape: 1.6576

Epoch 18/128

3830/3830 - 38s - 10ms/step - ia: 0.2457 - loss: 0.9421 - mae: 0.7412 - rmse: 0.9118 - smape: 1.6801 - val_ia: 0.1889 - val_loss: 0.8852 - val_mae: 0.7186 - val_rmse: 0.7552 - val_smape: 1.6436

Epoch 19/128

3830/3830 - 31s - 8ms/step - ia: 0.2468 - loss: 0.9399 - mae: 0.7397 - rmse: 0.9113 - smape: 1.6687 - val_ia: 0.1889 - val_loss: 0.8809 - val_mae: 0.7171 - val_rmse: 0.7538 - val_smape: 1.6309

Epoch 20/128

3830/3830 - 35s - 9ms/step - ia: 0.2505 - loss: 0.9384 - mae: 0.7388 - rmse: 0.9101 - smape: 1.6544 - val_ia: 0.1889 - val_loss: 0.8768 - val_mae: 0.7154 - val_rmse: 0.7521 - val_smape: 1.6180

Epoch 21/128

3830/3830 - 37s - 10ms/step - ia: 0.2501 - loss: 0.9335 - mae: 0.7376 - rmse: 0.9101 - smape: 1.6459 - val_ia: 0.1889 - val_loss: 0.8728 - val_mae: 0.7137 - val_rmse: 0.7505 - val_smape: 1.6052

Epoch 22/128

3830/3830 - 32s - 8ms/step - ia: 0.2556 - loss: 0.9302 - mae: 0.7362 - rmse: 0.9067 - smape: 1.6371 - val_ia: 0.1889 - val_loss: 0.8691 - val_mae: 0.7124 - val_rmse: 0.7492 - val_smape: 1.5937

Epoch 23/128

3830/3830 - 45s - 12ms/step - ia: 0.2571 - loss: 0.9274 - mae: 0.7350 - rmse: 0.9057 - smape: 1.6262 - val_ia: 0.1890 - val_loss: 0.8656 - val_mae: 0.7110 - val_rmse: 0.7479 - val_smape: 1.5827

Epoch 24/128

3830/3830 - 37s - 10ms/step - ia: 0.2599 - loss: 0.9238 - mae: 0.7329 - rmse: 0.9037 - smape: 1.6113 - val_ia: 0.1890 - val_loss: 0.8620 - val_mae: 0.7094 - val_rmse: 0.7464 - val_smape: 1.5713

Epoch 25/128

3830/3830 - 41s - 11ms/step - ia: 0.2626 - loss: 0.9237 - mae: 0.7330 - rmse: 0.9040 - smape: 1.6061 - val_ia: 0.1891 - val_loss: 0.8587 - val_mae: 0.7079 - val_rmse: 0.7449 - val_smape: 1.5607

Epoch 26/128

3830/3830 - 37s - 10ms/step - ia: 0.2667 - loss: 0.9186 - mae: 0.7304 - rmse: 0.9012 - smape: 1.5925 - val_ia: 0.1892 - val_loss: 0.8556 - val_mae: 0.7065 - val_rmse: 0.7436 - val_smape: 1.5505

Epoch 27/128

3830/3830 - 41s - 11ms/step - ia: 0.2673 - loss: 0.9150 - mae: 0.7295 - rmse: 0.8996 - smape: 1.5852 - val_ia: 0.1892 - val_loss: 0.8526 - val_mae: 0.7053 - val_rmse: 0.7424 - val_smape: 1.5409

Epoch 28/128

3830/3830 - 37s - 10ms/step - ia: 0.2681 - loss: 0.9120 - mae: 0.7286 - rmse: 0.8986 - smape: 1.5799 - val_ia: 0.1894 - val_loss: 0.8496 - val_mae: 0.7040 - val_rmse: 0.7411 - val_smape: 1.5313

Epoch 29/128

3830/3830 - 37s - 10ms/step - ia: 0.2699 - loss: 0.9120 - mae: 0.7280 - rmse: 0.8990 - smape: 1.5685 - val_ia: 0.1894 - val_loss: 0.8468 - val_mae: 0.7027 - val_rmse: 0.7399 - val_smape: 1.5222

Epoch 30/128

3830/3830 - 38s - 10ms/step - ia: 0.2731 - loss: 0.9097 - mae: 0.7266 - rmse: 0.8971 - smape: 1.5609 - val_ia: 0.1895 - val_loss: 0.8442 - val_mae: 0.7015 - val_rmse: 0.7387 - val_smape: 1.5139

Epoch 31/128

3830/3830 - 37s - 10ms/step - ia: 0.2767 - loss: 0.9072 - mae: 0.7250 - rmse: 0.8952 - smape: 1.5504 - val_ia: 0.1896 - val_loss: 0.8416 - val_mae: 0.7002 - val_rmse: 0.7375 - val_smape: 1.5052

Epoch 32/128

3830/3830 - 37s - 10ms/step - ia: 0.2772 - loss: 0.9054 - mae: 0.7243 - rmse: 0.8955 - smape: 1.5421 - val_ia: 0.1896 - val_loss: 0.8392 - val_mae: 0.6990 - val_rmse: 0.7364 - val_smape: 1.4975

Epoch 33/128

3830/3830 - 40s - 10ms/step - ia: 0.2791 - loss: 0.9040 - mae: 0.7232 - rmse: 0.8947 - smape: 1.5344 - val_ia: 0.1896 - val_loss: 0.8368 - val_mae: 0.6978 - val_rmse: 0.7352 - val_smape: 1.4895

Epoch 34/128

3830/3830 - 30s - 8ms/step - ia: 0.2804 - loss: 0.9021 - mae: 0.7219 - rmse: 0.8934 - smape: 1.5249 - val_ia: 0.1897 - val_loss: 0.8344 - val_mae: 0.6966 - val_rmse: 0.7340 - val_smape: 1.4815

Epoch 35/128

3830/3830 - 36s - 9ms/step - ia: 0.2814 - loss: 0.8984 - mae: 0.7205 - rmse: 0.8907 - smape: 1.5192 - val_ia: 0.1898 - val_loss: 0.8322 - val_mae: 0.6954 - val_rmse: 0.7329 - val_smape: 1.4738

Epoch 36/128

3830/3830 - 32s - 8ms/step - ia: 0.2821 - loss: 0.8974 - mae: 0.7195 - rmse: 0.8915 - smape: 1.5122 - val_ia: 0.1899 - val_loss: 0.8302 - val_mae: 0.6945 - val_rmse: 0.7320 - val_smape: 1.4672

Epoch 37/128

3830/3830 - 33s - 9ms/step - ia: 0.2845 - loss: 0.8947 - mae: 0.7184 - rmse: 0.8907 - smape: 1.5043 - val_ia: 0.1900 - val_loss: 0.8281 - val_mae: 0.6934 - val_rmse: 0.7310 - val_smape: 1.4601

Epoch 38/128

3830/3830 - 36s - 10ms/step - ia: 0.2853 - loss: 0.8961 - mae: 0.7189 - rmse: 0.8912 - smape: 1.5007 - val_ia: 0.1900 - val_loss: 0.8262 - val_mae: 0.6921 - val_rmse: 0.7298 - val_smape: 1.4531

Epoch 39/128

3830/3830 - 37s - 10ms/step - ia: 0.2872 - loss: 0.8943 - mae: 0.7176 - rmse: 0.8886 - smape: 1.4951 - val_ia: 0.1901 - val_loss: 0.8244 - val_mae: 0.6911 - val_rmse: 0.7287 - val_smape: 1.4468

Epoch 40/128

3830/3830 - 37s - 10ms/step - ia: 0.2898 - loss: 0.8914 - mae: 0.7160 - rmse: 0.8878 - smape: 1.4874 - val_ia: 0.1902 - val_loss: 0.8224 - val_mae: 0.6900 - val_rmse: 0.7277 - val_smape: 1.4400

Epoch 41/128

3830/3830 - 31s - 8ms/step - ia: 0.2924 - loss: 0.8872 - mae: 0.7141 - rmse: 0.8865 - smape: 1.4788 - val_ia: 0.1904 - val_loss: 0.8206 - val_mae: 0.6889 - val_rmse: 0.7267 - val_smape: 1.4335

Epoch 42/128

3830/3830 - 34s - 9ms/step - ia: 0.2949 - loss: 0.8878 - mae: 0.7136 - rmse: 0.8861 - smape: 1.4734 - val_ia: 0.1907 - val_loss: 0.8190 - val_mae: 0.6880 - val_rmse: 0.7259 - val_smape: 1.4281

Epoch 43/128

3830/3830 - 37s - 10ms/step - ia: 0.2963 - loss: 0.8864 - mae: 0.7130 - rmse: 0.8861 - smape: 1.4670 - val_ia: 0.1909 - val_loss: 0.8176 - val_mae: 0.6871 - val_rmse: 0.7250 - val_smape: 1.4230

Epoch 44/128

3830/3830 - 42s - 11ms/step - ia: 0.2968 - loss: 0.8866 - mae: 0.7120 - rmse: 0.8856 - smape: 1.4615 - val_ia: 0.1911 - val_loss: 0.8161 - val_mae: 0.6862 - val_rmse: 0.7241 - val_smape: 1.4176

Epoch 45/128

3830/3830 - 38s - 10ms/step - ia: 0.2981 - loss: 0.8845 - mae: 0.7113 - rmse: 0.8839 - smape: 1.4574 - val_ia: 0.1913 - val_loss: 0.8147 - val_mae: 0.6853 - val_rmse: 0.7233 - val_smape: 1.4124

Epoch 46/128

3830/3830 - 30s - 8ms/step - ia: 0.2996 - loss: 0.8842 - mae: 0.7107 - rmse: 0.8852 - smape: 1.4519 - val_ia: 0.1915 - val_loss: 0.8133 - val_mae: 0.6843 - val_rmse: 0.7224 - val_smape: 1.4071

Epoch 47/128

3830/3830 - 37s - 10ms/step - ia: 0.3012 - loss: 0.8773 - mae: 0.7082 - rmse: 0.8807 - smape: 1.4480 - val_ia: 0.1918 - val_loss: 0.8119 - val_mae: 0.6836 - val_rmse: 0.7217 - val_smape: 1.4022

Epoch 48/128

3830/3830 - 37s - 10ms/step - ia: 0.3011 - loss: 0.8810 - mae: 0.7093 - rmse: 0.8826 - smape: 1.4425 - val_ia: 0.1920 - val_loss: 0.8107 - val_mae: 0.6828 - val_rmse: 0.7210 - val_smape: 1.3974

Epoch 49/128

3830/3830 - 32s - 8ms/step - ia: 0.3037 - loss: 0.8787 - mae: 0.7078 - rmse: 0.8823 - smape: 1.4351 - val_ia: 0.1923 - val_loss: 0.8095 - val_mae: 0.6820 - val_rmse: 0.7202 - val_smape: 1.3929

Epoch 50/128

3830/3830 - 32s - 8ms/step - ia: 0.3079 - loss: 0.8763 - mae: 0.7061 - rmse: 0.8806 - smape: 1.4294 - val_ia: 0.1926 - val_loss: 0.8081 - val_mae: 0.6810 - val_rmse: 0.7193 - val_smape: 1.3876

Epoch 51/128

3830/3830 - 35s - 9ms/step - ia: 0.3075 - loss: 0.8796 - mae: 0.7063 - rmse: 0.8814 - smape: 1.4267 - val_ia: 0.1929 - val_loss: 0.8071 - val_mae: 0.6802 - val_rmse: 0.7185 - val_smape: 1.3835

Epoch 52/128

3830/3830 - 31s - 8ms/step - ia: 0.3106 - loss: 0.8740 - mae: 0.7045 - rmse: 0.8799 - smape: 1.4206 - val_ia: 0.1931 - val_loss: 0.8061 - val_mae: 0.6796 - val_rmse: 0.7180 - val_smape: 1.3799

Epoch 53/128

3830/3830 - 36s - 9ms/step - ia: 0.3116 - loss: 0.8749 - mae: 0.7047 - rmse: 0.8788 - smape: 1.4161 - val_ia: 0.1935 - val_loss: 0.8049 - val_mae: 0.6789 - val_rmse: 0.7173 - val_smape: 1.3757

Epoch 54/128

3830/3830 - 37s - 10ms/step - ia: 0.3105 - loss: 0.8745 - mae: 0.7036 - rmse: 0.8795 - smape: 1.4150 - val_ia: 0.1938 - val_loss: 0.8039 - val_mae: 0.6782 - val_rmse: 0.7166 - val_smape: 1.3719

Epoch 55/128

3830/3830 - 33s - 9ms/step - ia: 0.3114 - loss: 0.8743 - mae: 0.7036 - rmse: 0.8792 - smape: 1.4102 - val_ia: 0.1941 - val_loss: 0.8028 - val_mae: 0.6773 - val_rmse: 0.7158 - val_smape: 1.3678

Epoch 56/128

3830/3830 - 31s - 8ms/step - ia: 0.3140 - loss: 0.8707 - mae: 0.7021 - rmse: 0.8783 - smape: 1.4063 - val_ia: 0.1944 - val_loss: 0.8019 - val_mae: 0.6766 - val_rmse: 0.7152 - val_smape: 1.3641

Epoch 57/128

3830/3830 - 37s - 10ms/step - ia: 0.3144 - loss: 0.8709 - mae: 0.7016 - rmse: 0.8770 - smape: 1.4033 - val_ia: 0.1947 - val_loss: 0.8010 - val_mae: 0.6759 - val_rmse: 0.7145 - val_smape: 1.3605

Epoch 58/128

3830/3830 - 37s - 10ms/step - ia: 0.3168 - loss: 0.8710 - mae: 0.7007 - rmse: 0.8769 - smape: 1.3990 - val_ia: 0.1950 - val_loss: 0.8002 - val_mae: 0.6753 - val_rmse: 0.7140 - val_smape: 1.3573

Epoch 59/128

3830/3830 - 37s - 10ms/step - ia: 0.3177 - loss: 0.8703 - mae: 0.7003 - rmse: 0.8764 - smape: 1.3943 - val_ia: 0.1952 - val_loss: 0.7994 - val_mae: 0.6747 - val_rmse: 0.7134 - val_smape: 1.3542

Epoch 60/128

3830/3830 - 41s - 11ms/step - ia: 0.3196 - loss: 0.8654 - mae: 0.6989 - rmse: 0.8759 - smape: 1.3933 - val_ia: 0.1955 - val_loss: 0.7987 - val_mae: 0.6743 - val_rmse: 0.7130 - val_smape: 1.3514

Epoch 61/128

3830/3830 - 37s - 10ms/step - ia: 0.3184 - loss: 0.8694 - mae: 0.6996 - rmse: 0.8754 - smape: 1.3899 - val_ia: 0.1957 - val_loss: 0.7979 - val_mae: 0.6736 - val_rmse: 0.7124 - val_smape: 1.3480

Epoch 62/128

3830/3830 - 36s - 10ms/step - ia: 0.3210 - loss: 0.8689 - mae: 0.6986 - rmse: 0.8742 - smape: 1.3850 - val_ia: 0.1959 - val_loss: 0.7973 - val_mae: 0.6730 - val_rmse: 0.7119 - val_smape: 1.3454

Epoch 63/128

3830/3830 - 37s - 10ms/step - ia: 0.3224 - loss: 0.8670 - mae: 0.6986 - rmse: 0.8750 - smape: 1.3846 - val_ia: 0.1962 - val_loss: 0.7965 - val_mae: 0.6723 - val_rmse: 0.7112 - val_smape: 1.3420

Epoch 64/128

3830/3830 - 36s - 9ms/step - ia: 0.3243 - loss: 0.8640 - mae: 0.6961 - rmse: 0.8727 - smape: 1.3787 - val_ia: 0.1964 - val_loss: 0.7959 - val_mae: 0.6720 - val_rmse: 0.7109 - val_smape: 1.3397

Epoch 65/128

3830/3830 - 30s - 8ms/step - ia: 0.3239 - loss: 0.8661 - mae: 0.6968 - rmse: 0.8736 - smape: 1.3789 - val_ia: 0.1966 - val_loss: 0.7950 - val_mae: 0.6713 - val_rmse: 0.7103 - val_smape: 1.3367

Epoch 66/128

3830/3830 - 35s - 9ms/step - ia: 0.3256 - loss: 0.8661 - mae: 0.6968 - rmse: 0.8747 - smape: 1.3746 - val_ia: 0.1968 - val_loss: 0.7945 - val_mae: 0.6709 - val_rmse: 0.7099 - val_smape: 1.3347

Epoch 67/128

3830/3830 - 43s - 11ms/step - ia: 0.3272 - loss: 0.8620 - mae: 0.6944 - rmse: 0.8716 - smape: 1.3702 - val_ia: 0.1971 - val_loss: 0.7937 - val_mae: 0.6702 - val_rmse: 0.7093 - val_smape: 1.3317

Epoch 68/128

3830/3830 - 41s - 11ms/step - ia: 0.3264 - loss: 0.8642 - mae: 0.6956 - rmse: 0.8727 - smape: 1.3692 - val_ia: 0.1973 - val_loss: 0.7931 - val_mae: 0.6697 - val_rmse: 0.7089 - val_smape: 1.3295

Epoch 69/128

3830/3830 - 37s - 10ms/step - ia: 0.3276 - loss: 0.8630 - mae: 0.6941 - rmse: 0.8743 - smape: 1.3657 - val_ia: 0.1975 - val_loss: 0.7925 - val_mae: 0.6692 - val_rmse: 0.7084 - val_smape: 1.3269

Epoch 70/128

3830/3830 - 33s - 9ms/step - ia: 0.3270 - loss: 0.8624 - mae: 0.6936 - rmse: 0.8714 - smape: 1.3644 - val_ia: 0.1977 - val_loss: 0.7921 - val_mae: 0.6689 - val_rmse: 0.7081 - val_smape: 1.3254

Epoch 71/128

3830/3830 - 31s - 8ms/step - ia: 0.3296 - loss: 0.8598 - mae: 0.6928 - rmse: 0.8721 - smape: 1.3607 - val_ia: 0.1979 - val_loss: 0.7915 - val_mae: 0.6685 - val_rmse: 0.7077 - val_smape: 1.3233

Epoch 72/128

3830/3830 - 46s - 12ms/step - ia: 0.3306 - loss: 0.8574 - mae: 0.6925 - rmse: 0.8708 - smape: 1.3587 - val_ia: 0.1980 - val_loss: 0.7911 - val_mae: 0.6681 - val_rmse: 0.7074 - val_smape: 1.3214

Epoch 73/128

3830/3830 - 36s - 9ms/step - ia: 0.3298 - loss: 0.8619 - mae: 0.6929 - rmse: 0.8716 - smape: 1.3564 - val_ia: 0.1982 - val_loss: 0.7906 - val_mae: 0.6675 - val_rmse: 0.7069 - val_smape: 1.3193

Epoch 74/128

3830/3830 - 30s - 8ms/step - ia: 0.3318 - loss: 0.8614 - mae: 0.6927 - rmse: 0.8709 - smape: 1.3557 - val_ia: 0.1984 - val_loss: 0.7902 - val_mae: 0.6672 - val_rmse: 0.7065 - val_smape: 1.3179

Epoch 75/128

3830/3830 - 34s - 9ms/step - ia: 0.3318 - loss: 0.8615 - mae: 0.6925 - rmse: 0.8710 - smape: 1.3556 - val_ia: 0.1985 - val_loss: 0.7898 - val_mae: 0.6668 - val_rmse: 0.7062 - val_smape: 1.3166

Epoch 76/128

3830/3830 - 36s - 9ms/step - ia: 0.3322 - loss: 0.8578 - mae: 0.6912 - rmse: 0.8690 - smape: 1.3535 - val_ia: 0.1986 - val_loss: 0.7892 - val_mae: 0.6663 - val_rmse: 0.7057 - val_smape: 1.3143

Epoch 77/128

3830/3830 - 41s - 11ms/step - ia: 0.3338 - loss: 0.8586 - mae: 0.6907 - rmse: 0.8699 - smape: 1.3499 - val_ia: 0.1987 - val_loss: 0.7888 - val_mae: 0.6660 - val_rmse: 0.7054 - val_smape: 1.3130

Epoch 78/128

3830/3830 - 34s - 9ms/step - ia: 0.3341 - loss: 0.8584 - mae: 0.6905 - rmse: 0.8691 - smape: 1.3484 - val_ia: 0.1988 - val_loss: 0.7883 - val_mae: 0.6656 - val_rmse: 0.7051 - val_smape: 1.3111

Epoch 79/128

3830/3830 - 31s - 8ms/step - ia: 0.3357 - loss: 0.8590 - mae: 0.6898 - rmse: 0.8696 - smape: 1.3452 - val_ia: 0.1989 - val_loss: 0.7879 - val_mae: 0.6652 - val_rmse: 0.7047 - val_smape: 1.3094

Epoch 80/128

3830/3830 - 36s - 9ms/step - ia: 0.3372 - loss: 0.8578 - mae: 0.6890 - rmse: 0.8679 - smape: 1.3409 - val_ia: 0.1989 - val_loss: 0.7876 - val_mae: 0.6650 - val_rmse: 0.7045 - val_smape: 1.3082

Epoch 81/128

3830/3830 - 37s - 10ms/step - ia: 0.3380 - loss: 0.8565 - mae: 0.6890 - rmse: 0.8682 - smape: 1.3425 - val_ia: 0.1989 - val_loss: 0.7874 - val_mae: 0.6648 - val_rmse: 0.7044 - val_smape: 1.3075

Epoch 82/128

3830/3830 - 34s - 9ms/step - ia: 0.3380 - loss: 0.8549 - mae: 0.6890 - rmse: 0.8673 - smape: 1.3428 - val_ia: 0.1990 - val_loss: 0.7870 - val_mae: 0.6645 - val_rmse: 0.7042 - val_smape: 1.3061

Epoch 83/128

3830/3830 - 33s - 9ms/step - ia: 0.3385 - loss: 0.8601 - mae: 0.6901 - rmse: 0.8695 - smape: 1.3421 - val_ia: 0.1991 - val_loss: 0.7866 - val_mae: 0.6641 - val_rmse: 0.7037 - val_smape: 1.3047

Epoch 84/128

3830/3830 - 34s - 9ms/step - ia: 0.3400 - loss: 0.8530 - mae: 0.6876 - rmse: 0.8669 - smape: 1.3368 - val_ia: 0.1991 - val_loss: 0.7862 - val_mae: 0.6637 - val_rmse: 0.7034 - val_smape: 1.3028

Epoch 85/128

3830/3830 - 30s - 8ms/step - ia: 0.3401 - loss: 0.8569 - mae: 0.6880 - rmse: 0.8670 - smape: 1.3370 - val_ia: 0.1992 - val_loss: 0.7858 - val_mae: 0.6634 - val_rmse: 0.7031 - val_smape: 1.3017

Epoch 86/128

3830/3830 - 36s - 9ms/step - ia: 0.3411 - loss: 0.8538 - mae: 0.6870 - rmse: 0.8669 - smape: 1.3340 - val_ia: 0.1992 - val_loss: 0.7855 - val_mae: 0.6631 - val_rmse: 0.7028 - val_smape: 1.3004

Epoch 87/128

3830/3830 - 36s - 9ms/step - ia: 0.3416 - loss: 0.8521 - mae: 0.6863 - rmse: 0.8671 - smape: 1.3317 - val_ia: 0.1993 - val_loss: 0.7852 - val_mae: 0.6628 - val_rmse: 0.7026 - val_smape: 1.2994

Epoch 88/128

3830/3830 - 34s - 9ms/step - ia: 0.3425 - loss: 0.8543 - mae: 0.6869 - rmse: 0.8665 - smape: 1.3337 - val_ia: 0.1993 - val_loss: 0.7851 - val_mae: 0.6627 - val_rmse: 0.7025 - val_smape: 1.2990

Epoch 89/128

3830/3830 - 38s - 10ms/step - ia: 0.3442 - loss: 0.8523 - mae: 0.6857 - rmse: 0.8665 - smape: 1.3299 - val_ia: 0.1993 - val_loss: 0.7849 - val_mae: 0.6625 - val_rmse: 0.7023 - val_smape: 1.2981

Epoch 90/128

3830/3830 - 37s - 10ms/step - ia: 0.3438 - loss: 0.8533 - mae: 0.6863 - rmse: 0.8665 - smape: 1.3289 - val_ia: 0.1994 - val_loss: 0.7845 - val_mae: 0.6621 - val_rmse: 0.7019 - val_smape: 1.2967

Epoch 91/128

3830/3830 - 36s - 9ms/step - ia: 0.3432 - loss: 0.8534 - mae: 0.6860 - rmse: 0.8668 - smape: 1.3293 - val_ia: 0.1994 - val_loss: 0.7842 - val_mae: 0.6619 - val_rmse: 0.7017 - val_smape: 1.2959

Epoch 92/128

3830/3830 - 36s - 9ms/step - ia: 0.3448 - loss: 0.8515 - mae: 0.6847 - rmse: 0.8664 - smape: 1.3224 - val_ia: 0.1995 - val_loss: 0.7839 - val_mae: 0.6616 - val_rmse: 0.7015 - val_smape: 1.2951

Epoch 93/128

3830/3830 - 36s - 10ms/step - ia: 0.3446 - loss: 0.8535 - mae: 0.6855 - rmse: 0.8663 - smape: 1.3269 - val_ia: 0.1995 - val_loss: 0.7838 - val_mae: 0.6615 - val_rmse: 0.7014 - val_smape: 1.2946

Epoch 94/128

3830/3830 - 37s - 10ms/step - ia: 0.3449 - loss: 0.8490 - mae: 0.6840 - rmse: 0.8650 - smape: 1.3244 - val_ia: 0.1995 - val_loss: 0.7835 - val_mae: 0.6613 - val_rmse: 0.7013 - val_smape: 1.2938

Epoch 95/128

3830/3830 - 41s - 11ms/step - ia: 0.3442 - loss: 0.8493 - mae: 0.6842 - rmse: 0.8644 - smape: 1.3236 - val_ia: 0.1996 - val_loss: 0.7832 - val_mae: 0.6610 - val_rmse: 0.7010 - val_smape: 1.2926

Epoch 96/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 30s - 31ms/step - ia: 0.2603 - loss: 0.9514 - mae: 0.7302 - rmse: 0.9557 - smape: 1.5002 - val_ia: 0.2480 - val_loss: 0.8221 - val_mae: 0.6750 - val_rmse: 0.7610 - val_smape: 1.4180

Epoch 2/128

958/958 - 19s - 20ms/step - ia: 0.3234 - loss: 0.8966 - mae: 0.7068 - rmse: 0.9287 - smape: 1.3919 - val_ia: 0.2545 - val_loss: 0.7998 - val_mae: 0.6615 - val_rmse: 0.7509 - val_smape: 1.3371

Epoch 3/128

958/958 - 16s - 16ms/step - ia: 0.3435 - loss: 0.8813 - mae: 0.6986 - rmse: 0.9201 - smape: 1.3612 - val_ia: 0.2558 - val_loss: 0.7928 - val_mae: 0.6576 - val_rmse: 0.7479 - val_smape: 1.3158

Epoch 4/128

958/958 - 15s - 15ms/step - ia: 0.3465 - loss: 0.8754 - mae: 0.6960 - rmse: 0.9173 - smape: 1.3565 - val_ia: 0.2550 - val_loss: 0.7925 - val_mae: 0.6572 - val_rmse: 0.7481 - val_smape: 1.3121

Epoch 5/128

958/958 - 16s - 17ms/step - ia: 0.3518 - loss: 0.8693 - mae: 0.6930 - rmse: 0.9145 - smape: 1.3465 - val_ia: 0.2552 - val_loss: 0.7881 - val_mae: 0.6555 - val_rmse: 0.7464 - val_smape: 1.3079

Epoch 6/128

958/958 - 16s - 16ms/step - ia: 0.3540 - loss: 0.8650 - mae: 0.6908 - rmse: 0.9106 - smape: 1.3428 - val_ia: 0.2553 - val_loss: 0.7852 - val_mae: 0.6545 - val_rmse: 0.7457 - val_smape: 1.3055

Epoch 7/128

958/958 - 17s - 18ms/step - ia: 0.3556 - loss: 0.8597 - mae: 0.6888 - rmse: 0.9100 - smape: 1.3386 - val_ia: 0.2547 - val_loss: 0.7842 - val_mae: 0.6545 - val_rmse: 0.7452 - val_smape: 1.3091

Epoch 8/128

958/958 - 14s - 15ms/step - ia: 0.3532 - loss: 0.8622 - mae: 0.6895 - rmse: 0.9109 - smape: 1.3426 - val_ia: 0.2546 - val_loss: 0.7832 - val_mae: 0.6539 - val_rmse: 0.7450 - val_smape: 1.3060

Epoch 9/128

958/958 - 16s - 16ms/step - ia: 0.3575 - loss: 0.8581 - mae: 0.6868 - rmse: 0.9086 - smape: 1.3369 - val_ia: 0.2545 - val_loss: 0.7818 - val_mae: 0.6533 - val_rmse: 0.7442 - val_smape: 1.3057

Epoch 10/128

958/958 - 16s - 16ms/step - ia: 0.3605 - loss: 0.8538 - mae: 0.6844 - rmse: 0.9064 - smape: 1.3326 - val_ia: 0.2542 - val_loss: 0.7804 - val_mae: 0.6532 - val_rmse: 0.7437 - val_smape: 1.3106

Epoch 11/128

958/958 - 21s - 22ms/step - ia: 0.3567 - loss: 0.8528 - mae: 0.6846 - rmse: 0.9044 - smape: 1.3385 - val_ia: 0.2556 - val_loss: 0.7770 - val_mae: 0.6508 - val_rmse: 0.7421 - val_smape: 1.2964

Epoch 12/128

958/958 - 15s - 16ms/step - ia: 0.3612 - loss: 0.8530 - mae: 0.6835 - rmse: 0.9048 - smape: 1.3311 - val_ia: 0.2549 - val_loss: 0.7771 - val_mae: 0.6513 - val_rmse: 0.7423 - val_smape: 1.3026

Epoch 13/128

958/958 - 16s - 16ms/step - ia: 0.3606 - loss: 0.8488 - mae: 0.6821 - rmse: 0.9039 - smape: 1.3312 - val_ia: 0.2553 - val_loss: 0.7755 - val_mae: 0.6511 - val_rmse: 0.7422 - val_smape: 1.3001

Epoch 14/128

958/958 - 16s - 16ms/step - ia: 0.3597 - loss: 0.8492 - mae: 0.6825 - rmse: 0.9026 - smape: 1.3342 - val_ia: 0.2548 - val_loss: 0.7756 - val_mae: 0.6508 - val_rmse: 0.7418 - val_smape: 1.3013

Epoch 15/128

958/958 - 16s - 16ms/step - ia: 0.3618 - loss: 0.8443 - mae: 0.6803 - rmse: 0.9003 - smape: 1.3291 - val_ia: 0.2553 - val_loss: 0.7744 - val_mae: 0.6498 - val_rmse: 0.7415 - val_smape: 1.2931

Epoch 16/128

958/958 - 16s - 16ms/step - ia: 0.3624 - loss: 0.8450 - mae: 0.6810 - rmse: 0.9017 - smape: 1.3290 - val_ia: 0.2554 - val_loss: 0.7732 - val_mae: 0.6497 - val_rmse: 0.7411 - val_smape: 1.2956

Epoch 17/128

958/958 - 16s - 16ms/step - ia: 0.3632 - loss: 0.8441 - mae: 0.6802 - rmse: 0.9014 - smape: 1.3276 - val_ia: 0.2549 - val_loss: 0.7732 - val_mae: 0.6494 - val_rmse: 0.7407 - val_smape: 1.2970

Epoch 18/128

958/958 - 16s - 16ms/step - ia: 0.3627 - loss: 0.8459 - mae: 0.6791 - rmse: 0.9018 - smape: 1.3234 - val_ia: 0.2550 - val_loss: 0.7722 - val_mae: 0.6490 - val_rmse: 0.7401 - val_smape: 1.2974

Epoch 19/128

958/958 - 21s - 21ms/step - ia: 0.3643 - loss: 0.8421 - mae: 0.6790 - rmse: 0.9005 - smape: 1.3275 - val_ia: 0.2544 - val_loss: 0.7727 - val_mae: 0.6498 - val_rmse: 0.7409 - val_smape: 1.3023

Epoch 20/128

958/958 - 15s - 15ms/step - ia: 0.3629 - loss: 0.8434 - mae: 0.6788 - rmse: 0.9008 - smape: 1.3273 - val_ia: 0.2549 - val_loss: 0.7711 - val_mae: 0.6488 - val_rmse: 0.7401 - val_smape: 1.2973

Epoch 21/128

958/958 - 16s - 17ms/step - ia: 0.3645 - loss: 0.8423 - mae: 0.6778 - rmse: 0.8996 - smape: 1.3237 - val_ia: 0.2552 - val_loss: 0.7699 - val_mae: 0.6484 - val_rmse: 0.7397 - val_smape: 1.2959

Epoch 22/128

958/958 - 15s - 15ms/step - ia: 0.3653 - loss: 0.8403 - mae: 0.6775 - rmse: 0.8982 - smape: 1.3243 - val_ia: 0.2551 - val_loss: 0.7698 - val_mae: 0.6480 - val_rmse: 0.7395 - val_smape: 1.2940

Epoch 23/128

958/958 - 16s - 17ms/step - ia: 0.3656 - loss: 0.8392 - mae: 0.6771 - rmse: 0.8981 - smape: 1.3221 - val_ia: 0.2558 - val_loss: 0.7681 - val_mae: 0.6475 - val_rmse: 0.7393 - val_smape: 1.2890

Epoch 24/128

958/958 - 18s - 19ms/step - ia: 0.3675 - loss: 0.8372 - mae: 0.6760 - rmse: 0.8965 - smape: 1.3170 - val_ia: 0.2547 - val_loss: 0.7699 - val_mae: 0.6493 - val_rmse: 0.7407 - val_smape: 1.2995

Epoch 25/128

958/958 - 16s - 16ms/step - ia: 0.3673 - loss: 0.8350 - mae: 0.6762 - rmse: 0.8963 - smape: 1.3229 - val_ia: 0.2552 - val_loss: 0.7676 - val_mae: 0.6475 - val_rmse: 0.7388 - val_smape: 1.2933

Epoch 26/128

958/958 - 16s - 16ms/step - ia: 0.3670 - loss: 0.8374 - mae: 0.6763 - rmse: 0.8965 - smape: 1.3203 - val_ia: 0.2553 - val_loss: 0.7664 - val_mae: 0.6471 - val_rmse: 0.7385 - val_smape: 1.2923

Epoch 27/128

958/958 - 16s - 17ms/step - ia: 0.3692 - loss: 0.8345 - mae: 0.6747 - rmse: 0.8954 - smape: 1.3168 - val_ia: 0.2553 - val_loss: 0.7659 - val_mae: 0.6467 - val_rmse: 0.7383 - val_smape: 1.2915

Epoch 28/128

958/958 - 16s - 16ms/step - ia: 0.3664 - loss: 0.8358 - mae: 0.6756 - rmse: 0.8974 - smape: 1.3194 - val_ia: 0.2557 - val_loss: 0.7654 - val_mae: 0.6466 - val_rmse: 0.7386 - val_smape: 1.2874

Epoch 29/128

958/958 - 15s - 16ms/step - ia: 0.3700 - loss: 0.8342 - mae: 0.6747 - rmse: 0.8957 - smape: 1.3152 - val_ia: 0.2557 - val_loss: 0.7651 - val_mae: 0.6465 - val_rmse: 0.7385 - val_smape: 1.2879

Epoch 30/128

958/958 - 15s - 16ms/step - ia: 0.3700 - loss: 0.8326 - mae: 0.6741 - rmse: 0.8944 - smape: 1.3163 - val_ia: 0.2559 - val_loss: 0.7643 - val_mae: 0.6458 - val_rmse: 0.7379 - val_smape: 1.2842

Epoch 31/128

958/958 - 16s - 16ms/step - ia: 0.3706 - loss: 0.8324 - mae: 0.6731 - rmse: 0.8942 - smape: 1.3143 - val_ia: 0.2561 - val_loss: 0.7635 - val_mae: 0.6457 - val_rmse: 0.7378 - val_smape: 1.2846

Epoch 32/128

958/958 - 18s - 19ms/step - ia: 0.3734 - loss: 0.8286 - mae: 0.6719 - rmse: 0.8926 - smape: 1.3095 - val_ia: 0.2560 - val_loss: 0.7622 - val_mae: 0.6454 - val_rmse: 0.7372 - val_smape: 1.2863

Epoch 33/128

958/958 - 22s - 23ms/step - ia: 0.3719 - loss: 0.8291 - mae: 0.6725 - rmse: 0.8919 - smape: 1.3133 - val_ia: 0.2560 - val_loss: 0.7625 - val_mae: 0.6451 - val_rmse: 0.7372 - val_smape: 1.2841

Epoch 34/128

958/958 - 22s - 23ms/step - ia: 0.3749 - loss: 0.8266 - mae: 0.6711 - rmse: 0.8913 - smape: 1.3102 - val_ia: 0.2564 - val_loss: 0.7606 - val_mae: 0.6441 - val_rmse: 0.7363 - val_smape: 1.2792

Epoch 35/128

958/958 - 21s - 22ms/step - ia: 0.3753 - loss: 0.8265 - mae: 0.6710 - rmse: 0.8916 - smape: 1.3071 - val_ia: 0.2567 - val_loss: 0.7591 - val_mae: 0.6438 - val_rmse: 0.7360 - val_smape: 1.2789

Epoch 36/128

958/958 - 19s - 20ms/step - ia: 0.3760 - loss: 0.8279 - mae: 0.6721 - rmse: 0.8912 - smape: 1.3101 - val_ia: 0.2560 - val_loss: 0.7587 - val_mae: 0.6444 - val_rmse: 0.7361 - val_smape: 1.2867

Epoch 37/128

958/958 - 23s - 24ms/step - ia: 0.3714 - loss: 0.8274 - mae: 0.6717 - rmse: 0.8912 - smape: 1.3102 - val_ia: 0.2562 - val_loss: 0.7584 - val_mae: 0.6441 - val_rmse: 0.7361 - val_smape: 1.2842

Epoch 38/128

958/958 - 17s - 17ms/step - ia: 0.3747 - loss: 0.8274 - mae: 0.6714 - rmse: 0.8916 - smape: 1.3113 - val_ia: 0.2561 - val_loss: 0.7590 - val_mae: 0.6446 - val_rmse: 0.7368 - val_smape: 1.2853

Epoch 39/128

958/958 - 17s - 18ms/step - ia: 0.3748 - loss: 0.8237 - mae: 0.6706 - rmse: 0.8904 - smape: 1.3095 - val_ia: 0.2567 - val_loss: 0.7566 - val_mae: 0.6435 - val_rmse: 0.7357 - val_smape: 1.2796

Epoch 40/128

958/958 - 20s - 21ms/step - ia: 0.3757 - loss: 0.8252 - mae: 0.6709 - rmse: 0.8915 - smape: 1.3074 - val_ia: 0.2562 - val_loss: 0.7573 - val_mae: 0.6435 - val_rmse: 0.7359 - val_smape: 1.2801

Epoch 41/128

958/958 - 15s - 16ms/step - ia: 0.3758 - loss: 0.8262 - mae: 0.6697 - rmse: 0.8914 - smape: 1.3069 - val_ia: 0.2565 - val_loss: 0.7566 - val_mae: 0.6430 - val_rmse: 0.7358 - val_smape: 1.2766

Epoch 42/128

958/958 - 19s - 20ms/step - ia: 0.3784 - loss: 0.8241 - mae: 0.6693 - rmse: 0.8897 - smape: 1.3022 - val_ia: 0.2564 - val_loss: 0.7574 - val_mae: 0.6433 - val_rmse: 0.7362 - val_smape: 1.2757

Epoch 43/128

958/958 - 21s - 22ms/step - ia: 0.3810 - loss: 0.8201 - mae: 0.6684 - rmse: 0.8881 - smape: 1.3001 - val_ia: 0.2564 - val_loss: 0.7559 - val_mae: 0.6430 - val_rmse: 0.7355 - val_smape: 1.2777

Epoch 44/128

958/958 - 20s - 21ms/step - ia: 0.3771 - loss: 0.8242 - mae: 0.6697 - rmse: 0.8905 - smape: 1.3056 - val_ia: 0.2568 - val_loss: 0.7548 - val_mae: 0.6425 - val_rmse: 0.7352 - val_smape: 1.2741

Epoch 45/128

958/958 - 21s - 22ms/step - ia: 0.3780 - loss: 0.8245 - mae: 0.6704 - rmse: 0.8906 - smape: 1.3060 - val_ia: 0.2565 - val_loss: 0.7544 - val_mae: 0.6427 - val_rmse: 0.7351 - val_smape: 1.2787

Epoch 46/128

958/958 - 16s - 16ms/step - ia: 0.3796 - loss: 0.8226 - mae: 0.6680 - rmse: 0.8881 - smape: 1.3000 - val_ia: 0.2566 - val_loss: 0.7549 - val_mae: 0.6430 - val_rmse: 0.7357 - val_smape: 1.2772

Epoch 47/128

958/958 - 21s - 22ms/step - ia: 0.3794 - loss: 0.8248 - mae: 0.6696 - rmse: 0.8910 - smape: 1.3041 - val_ia: 0.2564 - val_loss: 0.7552 - val_mae: 0.6430 - val_rmse: 0.7358 - val_smape: 1.2765

Epoch 48/128

958/958 - 19s - 20ms/step - ia: 0.3794 - loss: 0.8220 - mae: 0.6687 - rmse: 0.8890 - smape: 1.3026 - val_ia: 0.2566 - val_loss: 0.7540 - val_mae: 0.6421 - val_rmse: 0.7349 - val_smape: 1.2737

Epoch 49/128

958/958 - 21s - 22ms/step - ia: 0.3804 - loss: 0.8184 - mae: 0.6675 - rmse: 0.8878 - smape: 1.2998 - val_ia: 0.2569 - val_loss: 0.7519 - val_mae: 0.6407 - val_rmse: 0.7335 - val_smape: 1.2682

Epoch 50/128

958/958 - 21s - 22ms/step - ia: 0.3826 - loss: 0.8181 - mae: 0.6667 - rmse: 0.8855 - smape: 1.2987 - val_ia: 0.2568 - val_loss: 0.7524 - val_mae: 0.6420 - val_rmse: 0.7349 - val_smape: 1.2747

Epoch 51/128

958/958 - 20s - 20ms/step - ia: 0.3803 - loss: 0.8202 - mae: 0.6670 - rmse: 0.8876 - smape: 1.2995 - val_ia: 0.2569 - val_loss: 0.7537 - val_mae: 0.6420 - val_rmse: 0.7353 - val_smape: 1.2705

Epoch 52/128

958/958 - 16s - 17ms/step - ia: 0.3825 - loss: 0.8193 - mae: 0.6663 - rmse: 0.8867 - smape: 1.2963 - val_ia: 0.2572 - val_loss: 0.7526 - val_mae: 0.6416 - val_rmse: 0.7349 - val_smape: 1.2676

Epoch 53/128

958/958 - 16s - 17ms/step - ia: 0.3865 - loss: 0.8146 - mae: 0.6660 - rmse: 0.8842 - smape: 1.2938 - val_ia: 0.2568 - val_loss: 0.7527 - val_mae: 0.6425 - val_rmse: 0.7356 - val_smape: 1.2767

Epoch 54/128

958/958 - 16s - 17ms/step - ia: 0.3820 - loss: 0.8161 - mae: 0.6659 - rmse: 0.8856 - smape: 1.2985 - val_ia: 0.2571 - val_loss: 0.7528 - val_mae: 0.6415 - val_rmse: 0.7350 - val_smape: 1.2676

Epoch 55/128

958/958 - 20s - 20ms/step - ia: 0.3846 - loss: 0.8146 - mae: 0.6660 - rmse: 0.8848 - smape: 1.2970 - val_ia: 0.2572 - val_loss: 0.7504 - val_mae: 0.6410 - val_rmse: 0.7341 - val_smape: 1.2701

Epoch 56/128

958/958 - 17s - 17ms/step - ia: 0.3843 - loss: 0.8140 - mae: 0.6642 - rmse: 0.8844 - smape: 1.2946 - val_ia: 0.2576 - val_loss: 0.7504 - val_mae: 0.6402 - val_rmse: 0.7338 - val_smape: 1.2625

Epoch 57/128

958/958 - 20s - 21ms/step - ia: 0.3842 - loss: 0.8213 - mae: 0.6673 - rmse: 0.8879 - smape: 1.2948 - val_ia: 0.2571 - val_loss: 0.7512 - val_mae: 0.6411 - val_rmse: 0.7344 - val_smape: 1.2695

Epoch 58/128

958/958 - 15s - 16ms/step - ia: 0.3858 - loss: 0.8163 - mae: 0.6651 - rmse: 0.8850 - smape: 1.2927 - val_ia: 0.2574 - val_loss: 0.7497 - val_mae: 0.6406 - val_rmse: 0.7337 - val_smape: 1.2688

Epoch 59/128

958/958 - 21s - 22ms/step - ia: 0.3847 - loss: 0.8156 - mae: 0.6647 - rmse: 0.8846 - smape: 1.2934 - val_ia: 0.2575 - val_loss: 0.7510 - val_mae: 0.6410 - val_rmse: 0.7345 - val_smape: 1.2669

Epoch 60/128

958/958 - 20s - 21ms/step - ia: 0.3858 - loss: 0.8172 - mae: 0.6657 - rmse: 0.8860 - smape: 1.2910 - val_ia: 0.2576 - val_loss: 0.7506 - val_mae: 0.6414 - val_rmse: 0.7347 - val_smape: 1.2703

Epoch 61/128

958/958 - 22s - 23ms/step - ia: 0.3840 - loss: 0.8160 - mae: 0.6649 - rmse: 0.8857 - smape: 1.2943 - val_ia: 0.2576 - val_loss: 0.7517 - val_mae: 0.6409 - val_rmse: 0.7347 - val_smape: 1.2648

Epoch 62/128

958/958 - 16s - 17ms/step - ia: 0.3890 - loss: 0.8142 - mae: 0.6643 - rmse: 0.8848 - smape: 1.2908 - val_ia: 0.2574 - val_loss: 0.7510 - val_mae: 0.6413 - val_rmse: 0.7348 - val_smape: 1.2709

Epoch 63/128

958/958 - 16s - 17ms/step - ia: 0.3841 - loss: 0.8164 - mae: 0.6658 - rmse: 0.8867 - smape: 1.2938 - val_ia: 0.2573 - val_loss: 0.7513 - val_mae: 0.6415 - val_rmse: 0.7350 - val_smape: 1.2727

Epoch 64/128

958/958 - 21s - 21ms/step - ia: 0.3862 - loss: 0.8141 - mae: 0.6642 - rmse: 0.8839 - smape: 1.2924 - val_ia: 0.2579 - val_loss: 0.7495 - val_mae: 0.6404 - val_rmse: 0.7339 - val_smape: 1.2661

Epoch 65/128

958/958 - 21s - 22ms/step - ia: 0.3870 - loss: 0.8102 - mae: 0.6626 - rmse: 0.8825 - smape: 1.2903 - val_ia: 0.2579 - val_loss: 0.7518 - val_mae: 0.6418 - val_rmse: 0.7357 - val_smape: 1.2688

Epoch 66/128

958/958 - 21s - 21ms/step - ia: 0.3859 - loss: 0.8146 - mae: 0.6649 - rmse: 0.8857 - smape: 1.2942 - val_ia: 0.2582 - val_loss: 0.7528 - val_mae: 0.6417 - val_rmse: 0.7358 - val_smape: 1.2637

Epoch 67/128

958/958 - 16s - 17ms/step - ia: 0.3886 - loss: 0.8130 - mae: 0.6630 - rmse: 0.8841 - smape: 1.2875 - val_ia: 0.2577 - val_loss: 0.7501 - val_mae: 0.6415 - val_rmse: 0.7348 - val_smape: 1.2735

Epoch 68/128

958/958 - 15s - 15ms/step - ia: 0.3864 - loss: 0.8148 - mae: 0.6635 - rmse: 0.8831 - smape: 1.2903 - val_ia: 0.2583 - val_loss: 0.7511 - val_mae: 0.6407 - val_rmse: 0.7347 - val_smape: 1.2629

Epoch 69/128

958/958 - 22s - 22ms/step - ia: 0.3879 - loss: 0.8137 - mae: 0.6637 - rmse: 0.8849 - smape: 1.2898 - val_ia: 0.2583 - val_loss: 0.7484 - val_mae: 0.6398 - val_rmse: 0.7333 - val_smape: 1.2645

Epoch 70/128

958/958 - 20s - 21ms/step - ia: 0.3879 - loss: 0.8132 - mae: 0.6634 - rmse: 0.8838 - smape: 1.2889 - val_ia: 0.2587 - val_loss: 0.7492 - val_mae: 0.6403 - val_rmse: 0.7342 - val_smape: 1.2627

Epoch 71/128

958/958 - 16s - 16ms/step - ia: 0.3870 - loss: 0.8099 - mae: 0.6631 - rmse: 0.8822 - smape: 1.2912 - val_ia: 0.2583 - val_loss: 0.7521 - val_mae: 0.6412 - val_rmse: 0.7355 - val_smape: 1.2650

Epoch 72/128

958/958 - 20s - 21ms/step - ia: 0.3913 - loss: 0.8111 - mae: 0.6627 - rmse: 0.8829 - smape: 1.2845 - val_ia: 0.2581 - val_loss: 0.7500 - val_mae: 0.6404 - val_rmse: 0.7342 - val_smape: 1.2671

Epoch 73/128

958/958 - 16s - 16ms/step - ia: 0.3885 - loss: 0.8100 - mae: 0.6630 - rmse: 0.8821 - smape: 1.2905 - val_ia: 0.2584 - val_loss: 0.7502 - val_mae: 0.6407 - val_rmse: 0.7346 - val_smape: 1.2670

Epoch 74/128

958/958 - 19s - 19ms/step - ia: 0.3900 - loss: 0.8098 - mae: 0.6618 - rmse: 0.8824 - smape: 1.2872 - val_ia: 0.2588 - val_loss: 0.7502 - val_mae: 0.6398 - val_rmse: 0.7340 - val_smape: 1.2591

Epoch 75/128

958/958 - 15s - 16ms/step - ia: 0.3878 - loss: 0.8110 - mae: 0.6628 - rmse: 0.8817 - smape: 1.2892 - val_ia: 0.2587 - val_loss: 0.7516 - val_mae: 0.6411 - val_rmse: 0.7354 - val_smape: 1.2642

Epoch 76/128

958/958 - 16s - 16ms/step - ia: 0.3892 - loss: 0.8099 - mae: 0.6628 - rmse: 0.8835 - smape: 1.2891 - val_ia: 0.2590 - val_loss: 0.7505 - val_mae: 0.6404 - val_rmse: 0.7346 - val_smape: 1.2614

Epoch 77/128

958/958 - 21s - 22ms/step - ia: 0.3923 - loss: 0.8102 - mae: 0.6613 - rmse: 0.8829 - smape: 1.2817 - val_ia: 0.2585 - val_loss: 0.7516 - val_mae: 0.6422 - val_rmse: 0.7361 - val_smape: 1.2727

Epoch 78/128

958/958 - 14s - 15ms/step - ia: 0.3898 - loss: 0.8081 - mae: 0.6623 - rmse: 0.8818 - smape: 1.2867 - val_ia: 0.2588 - val_loss: 0.7484 - val_mae: 0.6407 - val_rmse: 0.7343 - val_smape: 1.2701

Epoch 79/128

958/958 - 16s - 16ms/step - ia: 0.3904 - loss: 0.8072 - mae: 0.6611 - rmse: 0.8797 - smape: 1.2898 - val_ia: 0.2591 - val_loss: 0.7498 - val_mae: 0.6405 - val_rmse: 0.7347 - val_smape: 1.2643

Epoch 80/128

958/958 - 21s - 22ms/step - ia: 0.3919 - loss: 0.8090 - mae: 0.6618 - rmse: 0.8820 - smape: 1.2841 - val_ia: 0.2591 - val_loss: 0.7480 - val_mae: 0.6400 - val_rmse: 0.7338 - val_smape: 1.2670

Epoch 81/128

958/958 - 16s - 16ms/step - ia: 0.3882 - loss: 0.8089 - mae: 0.6625 - rmse: 0.8816 - smape: 1.2904 - val_ia: 0.2591 - val_loss: 0.7509 - val_mae: 0.6402 - val_rmse: 0.7347 - val_smape: 1.2618

Epoch 82/128

958/958 - 16s - 16ms/step - ia: 0.3906 - loss: 0.8083 - mae: 0.6611 - rmse: 0.8814 - smape: 1.2842 - val_ia: 0.2591 - val_loss: 0.7512 - val_mae: 0.6410 - val_rmse: 0.7353 - val_smape: 1.2660

Epoch 83/128

958/958 - 16s - 17ms/step - ia: 0.3900 - loss: 0.8075 - mae: 0.6613 - rmse: 0.8812 - smape: 1.2883 - val_ia: 0.2591 - val_loss: 0.7512 - val_mae: 0.6411 - val_rmse: 0.7352 - val_smape: 1.2678

Epoch 84/128

958/958 - 16s - 16ms/step - ia: 0.3912 - loss: 0.8057 - mae: 0.6604 - rmse: 0.8801 - smape: 1.2856 - val_ia: 0.2599 - val_loss: 0.7500 - val_mae: 0.6398 - val_rmse: 0.7343 - val_smape: 1.2583

Epoch 85/128

958/958 - 14s - 15ms/step - ia: 0.3910 - loss: 0.8097 - mae: 0.6614 - rmse: 0.8820 - smape: 1.2840 - val_ia: 0.2595 - val_loss: 0.7526 - val_mae: 0.6411 - val_rmse: 0.7358 - val_smape: 1.2626

Epoch 86/128

958/958 - 22s - 23ms/step - ia: 0.3919 - loss: 0.8082 - mae: 0.6611 - rmse: 0.8805 - smape: 1.2852 - val_ia: 0.2597 - val_loss: 0.7508 - val_mae: 0.6402 - val_rmse: 0.7347 - val_smape: 1.2602

Epoch 87/128

958/958 - 16s - 16ms/step - ia: 0.3911 - loss: 0.8084 - mae: 0.6611 - rmse: 0.8814 - smape: 1.2840 - val_ia: 0.2596 - val_loss: 0.7520 - val_mae: 0.6404 - val_rmse: 0.7350 - val_smape: 1.2602

Epoch 88/128

958/958 - 15s - 16ms/step - ia: 0.3909 - loss: 0.8077 - mae: 0.6605 - rmse: 0.8815 - smape: 1.2866 - val_ia: 0.2601 - val_loss: 0.7515 - val_mae: 0.6402 - val_rmse: 0.7349 - val_smape: 1.2575

Epoch 89/128

958/958 - 21s - 22ms/step - ia: 0.3913 - loss: 0.8091 - mae: 0.6612 - rmse: 0.8815 - smape: 1.2824 - val_ia: 0.2596 - val_loss: 0.7507 - val_mae: 0.6408 - val_rmse: 0.7351 - val_smape: 1.2665

Epoch 90/128

958/958 - 14s - 15ms/step - ia: 0.3946 - loss: 0.8046 - mae: 0.6590 - rmse: 0.8793 - smape: 1.2810 - val_ia: 0.2600 - val_loss: 0.7496 - val_mae: 0.6409 - val_rmse: 0.7351 - val_smape: 1.2678

Epoch 91/128

958/958 - 14s - 15ms/step - ia: 0.3924 - loss: 0.8022 - mae: 0.6592 - rmse: 0.8767 - smape: 1.2862 - val_ia: 0.2604 - val_loss: 0.7518 - val_mae: 0.6397 - val_rmse: 0.7349 - val_smape: 1.2540

Epoch 92/128

958/958 - 16s - 16ms/step - ia: 0.3965 - loss: 0.8036 - mae: 0.6583 - rmse: 0.8782 - smape: 1.2767 - val_ia: 0.2600 - val_loss: 0.7497 - val_mae: 0.6402 - val_rmse: 0.7347 - val_smape: 1.2643

Epoch 93/128

958/958 - 16s - 16ms/step - ia: 0.3914 - loss: 0.8072 - mae: 0.6602 - rmse: 0.8814 - smape: 1.2835 - val_ia: 0.2600 - val_loss: 0.7507 - val_mae: 0.6401 - val_rmse: 0.7348 - val_smape: 1.2619

Epoch 94/128

958/958 - 16s - 16ms/step - ia: 0.3949 - loss: 0.8041 - mae: 0.6593 - rmse: 0.8792 - smape: 1.2805 - val_ia: 0.2603 - val_loss: 0.7500 - val_mae: 0.6397 - val_rmse: 0.7343 - val_smape: 1.2595

Epoch 95/128

958/958 - 15s - 16ms/step - ia: 0.3947 - loss: 0.8046 - mae: 0.6598 - rmse: 0.8796 - smape: 1.2814 - val_ia: 0.2599 - val_loss: 0.7486 - val_mae: 0.6399 - val_rmse: 0.7339 - val_smape: 1.2673

Epoch 95: early stopping

Restoring model weights from the end of the best epoch: 80.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:23 1s/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 23/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 44/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 10s - 21ms/step - ia: 0.2334 - loss: 1.3131 - mae: 0.8447 - rmse: 1.1335 - smape: 1.5239 - val_ia: 0.2650 - val_loss: 1.3550 - val_mae: 0.8822 - val_rmse: 1.0210 - val_smape: 1.5995

Epoch 2/128

479/479 - 5s - 10ms/step - ia: 0.2313 - loss: 1.2861 - mae: 0.8348 - rmse: 1.1206 - smape: 1.5272 - val_ia: 0.2644 - val_loss: 1.3203 - val_mae: 0.8691 - val_rmse: 1.0066 - val_smape: 1.6046

Epoch 3/128

479/479 - 5s - 10ms/step - ia: 0.2274 - loss: 1.2655 - mae: 0.8267 - rmse: 1.1127 - smape: 1.5340 - val_ia: 0.2637 - val_loss: 1.2879 - val_mae: 0.8569 - val_rmse: 0.9930 - val_smape: 1.6097

Epoch 4/128

479/479 - 5s - 11ms/step - ia: 0.2252 - loss: 1.2352 - mae: 0.8175 - rmse: 1.0982 - smape: 1.5415 - val_ia: 0.2631 - val_loss: 1.2582 - val_mae: 0.8454 - val_rmse: 0.9804 - val_smape: 1.6147

Epoch 5/128

479/479 - 5s - 10ms/step - ia: 0.2228 - loss: 1.2144 - mae: 0.8098 - rmse: 1.0879 - smape: 1.5456 - val_ia: 0.2623 - val_loss: 1.2302 - val_mae: 0.8347 - val_rmse: 0.9685 - val_smape: 1.6203

Epoch 6/128

479/479 - 5s - 10ms/step - ia: 0.2186 - loss: 1.1971 - mae: 0.8040 - rmse: 1.0811 - smape: 1.5514 - val_ia: 0.2617 - val_loss: 1.2038 - val_mae: 0.8244 - val_rmse: 0.9571 - val_smape: 1.6259

Epoch 7/128

479/479 - 5s - 10ms/step - ia: 0.2152 - loss: 1.1770 - mae: 0.7974 - rmse: 1.0722 - smape: 1.5584 - val_ia: 0.2609 - val_loss: 1.1789 - val_mae: 0.8148 - val_rmse: 0.9464 - val_smape: 1.6318

Epoch 8/128

479/479 - 5s - 9ms/step - ia: 0.2141 - loss: 1.1601 - mae: 0.7913 - rmse: 1.0638 - smape: 1.5618 - val_ia: 0.2600 - val_loss: 1.1555 - val_mae: 0.8058 - val_rmse: 0.9362 - val_smape: 1.6382

Epoch 9/128

479/479 - 5s - 10ms/step - ia: 0.2092 - loss: 1.1460 - mae: 0.7866 - rmse: 1.0577 - smape: 1.5707 - val_ia: 0.2591 - val_loss: 1.1332 - val_mae: 0.7971 - val_rmse: 0.9265 - val_smape: 1.6448

Epoch 10/128

479/479 - 5s - 10ms/step - ia: 0.2080 - loss: 1.1283 - mae: 0.7817 - rmse: 1.0480 - smape: 1.5776 - val_ia: 0.2583 - val_loss: 1.1122 - val_mae: 0.7890 - val_rmse: 0.9173 - val_smape: 1.6518

Epoch 11/128

479/479 - 5s - 11ms/step - ia: 0.2062 - loss: 1.1097 - mae: 0.7750 - rmse: 1.0406 - smape: 1.5760 - val_ia: 0.2578 - val_loss: 1.0924 - val_mae: 0.7812 - val_rmse: 0.9085 - val_smape: 1.6589

Epoch 12/128

479/479 - 5s - 11ms/step - ia: 0.2029 - loss: 1.0979 - mae: 0.7709 - rmse: 1.0352 - smape: 1.5829 - val_ia: 0.2573 - val_loss: 1.0734 - val_mae: 0.7739 - val_rmse: 0.9001 - val_smape: 1.6661

Epoch 13/128

479/479 - 5s - 10ms/step - ia: 0.1998 - loss: 1.0884 - mae: 0.7689 - rmse: 1.0307 - smape: 1.5899 - val_ia: 0.2567 - val_loss: 1.0555 - val_mae: 0.7669 - val_rmse: 0.8921 - val_smape: 1.6736

Epoch 14/128

479/479 - 5s - 10ms/step - ia: 0.1991 - loss: 1.0737 - mae: 0.7634 - rmse: 1.0229 - smape: 1.5906 - val_ia: 0.2561 - val_loss: 1.0387 - val_mae: 0.7603 - val_rmse: 0.8846 - val_smape: 1.6817

Epoch 15/128

479/479 - 4s - 9ms/step - ia: 0.2000 - loss: 1.0573 - mae: 0.7574 - rmse: 1.0153 - smape: 1.5895 - val_ia: 0.2554 - val_loss: 1.0230 - val_mae: 0.7542 - val_rmse: 0.8775 - val_smape: 1.6900

Epoch 16/128

479/479 - 5s - 11ms/step - ia: 0.1985 - loss: 1.0468 - mae: 0.7541 - rmse: 1.0108 - smape: 1.5907 - val_ia: 0.2547 - val_loss: 1.0079 - val_mae: 0.7483 - val_rmse: 0.8707 - val_smape: 1.6975

Epoch 17/128

479/479 - 5s - 11ms/step - ia: 0.1999 - loss: 1.0357 - mae: 0.7507 - rmse: 1.0042 - smape: 1.5907 - val_ia: 0.2540 - val_loss: 0.9938 - val_mae: 0.7427 - val_rmse: 0.8644 - val_smape: 1.7027

Epoch 18/128

479/479 - 5s - 10ms/step - ia: 0.1993 - loss: 1.0244 - mae: 0.7469 - rmse: 0.9991 - smape: 1.5924 - val_ia: 0.2532 - val_loss: 0.9803 - val_mae: 0.7373 - val_rmse: 0.8582 - val_smape: 1.7061

Epoch 19/128

479/479 - 4s - 9ms/step - ia: 0.1969 - loss: 1.0152 - mae: 0.7455 - rmse: 0.9952 - smape: 1.5994 - val_ia: 0.2523 - val_loss: 0.9676 - val_mae: 0.7322 - val_rmse: 0.8524 - val_smape: 1.7072

Epoch 20/128

479/479 - 5s - 11ms/step - ia: 0.1980 - loss: 1.0093 - mae: 0.7421 - rmse: 0.9925 - smape: 1.5959 - val_ia: 0.2513 - val_loss: 0.9557 - val_mae: 0.7275 - val_rmse: 0.8470 - val_smape: 1.7049

Epoch 21/128

479/479 - 5s - 10ms/step - ia: 0.2013 - loss: 0.9932 - mae: 0.7374 - rmse: 0.9849 - smape: 1.5911 - val_ia: 0.2503 - val_loss: 0.9445 - val_mae: 0.7230 - val_rmse: 0.8419 - val_smape: 1.6986

Epoch 22/128

479/479 - 5s - 10ms/step - ia: 0.2030 - loss: 0.9889 - mae: 0.7366 - rmse: 0.9820 - smape: 1.5914 - val_ia: 0.2494 - val_loss: 0.9339 - val_mae: 0.7187 - val_rmse: 0.8371 - val_smape: 1.6880

Epoch 23/128

479/479 - 5s - 10ms/step - ia: 0.2050 - loss: 0.9828 - mae: 0.7344 - rmse: 0.9787 - smape: 1.5858 - val_ia: 0.2487 - val_loss: 0.9240 - val_mae: 0.7147 - val_rmse: 0.8326 - val_smape: 1.6744

Epoch 24/128

479/479 - 5s - 11ms/step - ia: 0.2115 - loss: 0.9719 - mae: 0.7299 - rmse: 0.9733 - smape: 1.5762 - val_ia: 0.2481 - val_loss: 0.9147 - val_mae: 0.7109 - val_rmse: 0.8284 - val_smape: 1.6580

Epoch 25/128

479/479 - 5s - 10ms/step - ia: 0.2114 - loss: 0.9634 - mae: 0.7275 - rmse: 0.9700 - smape: 1.5727 - val_ia: 0.2476 - val_loss: 0.9059 - val_mae: 0.7073 - val_rmse: 0.8244 - val_smape: 1.6396

Epoch 26/128

479/479 - 5s - 10ms/step - ia: 0.2176 - loss: 0.9562 - mae: 0.7245 - rmse: 0.9667 - smape: 1.5614 - val_ia: 0.2473 - val_loss: 0.8977 - val_mae: 0.7039 - val_rmse: 0.8207 - val_smape: 1.6199

Epoch 27/128

479/479 - 5s - 10ms/step - ia: 0.2217 - loss: 0.9492 - mae: 0.7228 - rmse: 0.9624 - smape: 1.5573 - val_ia: 0.2471 - val_loss: 0.8899 - val_mae: 0.7006 - val_rmse: 0.8172 - val_smape: 1.5995

Epoch 28/128

479/479 - 5s - 10ms/step - ia: 0.2245 - loss: 0.9460 - mae: 0.7203 - rmse: 0.9609 - smape: 1.5477 - val_ia: 0.2473 - val_loss: 0.8829 - val_mae: 0.6977 - val_rmse: 0.8141 - val_smape: 1.5798

Epoch 29/128

479/479 - 5s - 10ms/step - ia: 0.2325 - loss: 0.9353 - mae: 0.7171 - rmse: 0.9550 - smape: 1.5370 - val_ia: 0.2476 - val_loss: 0.8761 - val_mae: 0.6948 - val_rmse: 0.8111 - val_smape: 1.5604

Epoch 30/128

479/479 - 4s - 9ms/step - ia: 0.2354 - loss: 0.9325 - mae: 0.7157 - rmse: 0.9532 - smape: 1.5290 - val_ia: 0.2480 - val_loss: 0.8698 - val_mae: 0.6921 - val_rmse: 0.8084 - val_smape: 1.5422

Epoch 31/128

479/479 - 5s - 10ms/step - ia: 0.2418 - loss: 0.9258 - mae: 0.7133 - rmse: 0.9499 - smape: 1.5194 - val_ia: 0.2485 - val_loss: 0.8638 - val_mae: 0.6894 - val_rmse: 0.8057 - val_smape: 1.5249

Epoch 32/128

479/479 - 5s - 11ms/step - ia: 0.2453 - loss: 0.9193 - mae: 0.7116 - rmse: 0.9478 - smape: 1.5116 - val_ia: 0.2491 - val_loss: 0.8582 - val_mae: 0.6869 - val_rmse: 0.8033 - val_smape: 1.5083

Epoch 33/128

479/479 - 5s - 10ms/step - ia: 0.2525 - loss: 0.9146 - mae: 0.7099 - rmse: 0.9446 - smape: 1.5027 - val_ia: 0.2496 - val_loss: 0.8529 - val_mae: 0.6845 - val_rmse: 0.8010 - val_smape: 1.4926

Epoch 34/128

479/479 - 5s - 10ms/step - ia: 0.2549 - loss: 0.9091 - mae: 0.7085 - rmse: 0.9431 - smape: 1.4969 - val_ia: 0.2503 - val_loss: 0.8480 - val_mae: 0.6822 - val_rmse: 0.7989 - val_smape: 1.4777

Epoch 35/128

479/479 - 5s - 10ms/step - ia: 0.2613 - loss: 0.9060 - mae: 0.7076 - rmse: 0.9403 - smape: 1.4864 - val_ia: 0.2510 - val_loss: 0.8437 - val_mae: 0.6802 - val_rmse: 0.7971 - val_smape: 1.4645

Epoch 36/128

479/479 - 5s - 10ms/step - ia: 0.2672 - loss: 0.9028 - mae: 0.7057 - rmse: 0.9385 - smape: 1.4780 - val_ia: 0.2517 - val_loss: 0.8394 - val_mae: 0.6782 - val_rmse: 0.7952 - val_smape: 1.4514

Epoch 37/128

479/479 - 4s - 9ms/step - ia: 0.2703 - loss: 0.8989 - mae: 0.7040 - rmse: 0.9374 - smape: 1.4697 - val_ia: 0.2524 - val_loss: 0.8355 - val_mae: 0.6763 - val_rmse: 0.7936 - val_smape: 1.4391

Epoch 38/128

479/479 - 5s - 10ms/step - ia: 0.2764 - loss: 0.8970 - mae: 0.7032 - rmse: 0.9365 - smape: 1.4610 - val_ia: 0.2533 - val_loss: 0.8319 - val_mae: 0.6745 - val_rmse: 0.7921 - val_smape: 1.4274

Epoch 39/128

479/479 - 5s - 10ms/step - ia: 0.2816 - loss: 0.8920 - mae: 0.7012 - rmse: 0.9333 - smape: 1.4523 - val_ia: 0.2542 - val_loss: 0.8287 - val_mae: 0.6729 - val_rmse: 0.7908 - val_smape: 1.4170

Epoch 40/128

479/479 - 4s - 9ms/step - ia: 0.2866 - loss: 0.8893 - mae: 0.7003 - rmse: 0.9326 - smape: 1.4439 - val_ia: 0.2551 - val_loss: 0.8256 - val_mae: 0.6714 - val_rmse: 0.7895 - val_smape: 1.4067

Epoch 41/128

479/479 - 4s - 9ms/step - ia: 0.2927 - loss: 0.8826 - mae: 0.6977 - rmse: 0.9294 - smape: 1.4359 - val_ia: 0.2560 - val_loss: 0.8227 - val_mae: 0.6698 - val_rmse: 0.7883 - val_smape: 1.3969

Epoch 42/128

479/479 - 5s - 10ms/step - ia: 0.2958 - loss: 0.8828 - mae: 0.6968 - rmse: 0.9293 - smape: 1.4261 - val_ia: 0.2569 - val_loss: 0.8201 - val_mae: 0.6685 - val_rmse: 0.7873 - val_smape: 1.3877

Epoch 43/128

479/479 - 5s - 10ms/step - ia: 0.3002 - loss: 0.8827 - mae: 0.6971 - rmse: 0.9296 - smape: 1.4183 - val_ia: 0.2579 - val_loss: 0.8177 - val_mae: 0.6673 - val_rmse: 0.7864 - val_smape: 1.3796

Epoch 44/128

479/479 - 5s - 10ms/step - ia: 0.3046 - loss: 0.8763 - mae: 0.6943 - rmse: 0.9254 - smape: 1.4088 - val_ia: 0.2588 - val_loss: 0.8156 - val_mae: 0.6662 - val_rmse: 0.7857 - val_smape: 1.3720

Epoch 45/128

479/479 - 5s - 10ms/step - ia: 0.3085 - loss: 0.8739 - mae: 0.6931 - rmse: 0.9249 - smape: 1.4087 - val_ia: 0.2597 - val_loss: 0.8135 - val_mae: 0.6652 - val_rmse: 0.7849 - val_smape: 1.3647

Epoch 46/128

479/479 - 4s - 9ms/step - ia: 0.3112 - loss: 0.8755 - mae: 0.6948 - rmse: 0.9239 - smape: 1.4038 - val_ia: 0.2605 - val_loss: 0.8118 - val_mae: 0.6642 - val_rmse: 0.7843 - val_smape: 1.3582

Epoch 47/128

479/479 - 4s - 7ms/step - ia: 0.3164 - loss: 0.8748 - mae: 0.6924 - rmse: 0.9257 - smape: 1.3949 - val_ia: 0.2612 - val_loss: 0.8101 - val_mae: 0.6634 - val_rmse: 0.7837 - val_smape: 1.3523

Epoch 48/128

479/479 - 4s - 8ms/step - ia: 0.3187 - loss: 0.8746 - mae: 0.6924 - rmse: 0.9249 - smape: 1.3896 - val_ia: 0.2620 - val_loss: 0.8086 - val_mae: 0.6626 - val_rmse: 0.7832 - val_smape: 1.3467

Epoch 49/128

479/479 - 6s - 12ms/step - ia: 0.3211 - loss: 0.8718 - mae: 0.6911 - rmse: 0.9240 - smape: 1.3856 - val_ia: 0.2626 - val_loss: 0.8072 - val_mae: 0.6618 - val_rmse: 0.7827 - val_smape: 1.3415

Epoch 50/128

479/479 - 4s - 9ms/step - ia: 0.3256 - loss: 0.8696 - mae: 0.6905 - rmse: 0.9217 - smape: 1.3799 - val_ia: 0.2633 - val_loss: 0.8058 - val_mae: 0.6611 - val_rmse: 0.7822 - val_smape: 1.3367

Epoch 51/128

479/479 - 4s - 9ms/step - ia: 0.3271 - loss: 0.8688 - mae: 0.6906 - rmse: 0.9214 - smape: 1.3782 - val_ia: 0.2640 - val_loss: 0.8047 - val_mae: 0.6605 - val_rmse: 0.7818 - val_smape: 1.3322

Epoch 52/128

479/479 - 4s - 9ms/step - ia: 0.3302 - loss: 0.8659 - mae: 0.6893 - rmse: 0.9216 - smape: 1.3730 - val_ia: 0.2646 - val_loss: 0.8036 - val_mae: 0.6600 - val_rmse: 0.7816 - val_smape: 1.3283

Epoch 53/128

479/479 - 3s - 7ms/step - ia: 0.3321 - loss: 0.8642 - mae: 0.6889 - rmse: 0.9193 - smape: 1.3701 - val_ia: 0.2652 - val_loss: 0.8026 - val_mae: 0.6595 - val_rmse: 0.7813 - val_smape: 1.3246

Epoch 54/128

479/479 - 3s - 7ms/step - ia: 0.3349 - loss: 0.8638 - mae: 0.6885 - rmse: 0.9196 - smape: 1.3648 - val_ia: 0.2658 - val_loss: 0.8016 - val_mae: 0.6589 - val_rmse: 0.7810 - val_smape: 1.3207

Epoch 55/128

479/479 - 4s - 9ms/step - ia: 0.3393 - loss: 0.8620 - mae: 0.6874 - rmse: 0.9181 - smape: 1.3588 - val_ia: 0.2663 - val_loss: 0.8005 - val_mae: 0.6584 - val_rmse: 0.7806 - val_smape: 1.3171

Epoch 56/128

479/479 - 4s - 9ms/step - ia: 0.3394 - loss: 0.8636 - mae: 0.6878 - rmse: 0.9191 - smape: 1.3591 - val_ia: 0.2668 - val_loss: 0.7998 - val_mae: 0.6580 - val_rmse: 0.7803 - val_smape: 1.3144

Epoch 57/128

479/479 - 3s - 7ms/step - ia: 0.3426 - loss: 0.8605 - mae: 0.6866 - rmse: 0.9170 - smape: 1.3564 - val_ia: 0.2672 - val_loss: 0.7990 - val_mae: 0.6575 - val_rmse: 0.7800 - val_smape: 1.3115

Epoch 58/128

479/479 - 6s - 12ms/step - ia: 0.3423 - loss: 0.8623 - mae: 0.6874 - rmse: 0.9181 - smape: 1.3526 - val_ia: 0.2676 - val_loss: 0.7982 - val_mae: 0.6571 - val_rmse: 0.7798 - val_smape: 1.3092

Epoch 59/128

479/479 - 4s - 9ms/step - ia: 0.3449 - loss: 0.8585 - mae: 0.6852 - rmse: 0.9174 - smape: 1.3489 - val_ia: 0.2680 - val_loss: 0.7974 - val_mae: 0.6567 - val_rmse: 0.7795 - val_smape: 1.3070

Epoch 60/128

479/479 - 4s - 9ms/step - ia: 0.3465 - loss: 0.8586 - mae: 0.6858 - rmse: 0.9172 - smape: 1.3479 - val_ia: 0.2684 - val_loss: 0.7968 - val_mae: 0.6564 - val_rmse: 0.7793 - val_smape: 1.3050

Epoch 61/128

479/479 - 4s - 9ms/step - ia: 0.3491 - loss: 0.8569 - mae: 0.6847 - rmse: 0.9150 - smape: 1.3432 - val_ia: 0.2687 - val_loss: 0.7961 - val_mae: 0.6561 - val_rmse: 0.7792 - val_smape: 1.3032

Epoch 62/128

479/479 - 3s - 7ms/step - ia: 0.3498 - loss: 0.8550 - mae: 0.6842 - rmse: 0.9150 - smape: 1.3426 - val_ia: 0.2690 - val_loss: 0.7954 - val_mae: 0.6558 - val_rmse: 0.7789 - val_smape: 1.3012

Epoch 63/128

479/479 - 4s - 8ms/step - ia: 0.3502 - loss: 0.8561 - mae: 0.6853 - rmse: 0.9159 - smape: 1.3428 - val_ia: 0.2693 - val_loss: 0.7947 - val_mae: 0.6554 - val_rmse: 0.7786 - val_smape: 1.2993

Epoch 64/128

479/479 - 6s - 12ms/step - ia: 0.3506 - loss: 0.8575 - mae: 0.6856 - rmse: 0.9158 - smape: 1.3420 - val_ia: 0.2696 - val_loss: 0.7941 - val_mae: 0.6552 - val_rmse: 0.7784 - val_smape: 1.2979

Epoch 65/128

479/479 - 4s - 8ms/step - ia: 0.3515 - loss: 0.8566 - mae: 0.6848 - rmse: 0.9157 - smape: 1.3389 - val_ia: 0.2698 - val_loss: 0.7935 - val_mae: 0.6548 - val_rmse: 0.7782 - val_smape: 1.2963

Epoch 66/128

479/479 - 3s - 7ms/step - ia: 0.3532 - loss: 0.8572 - mae: 0.6842 - rmse: 0.9159 - smape: 1.3347 - val_ia: 0.2701 - val_loss: 0.7930 - val_mae: 0.6546 - val_rmse: 0.7780 - val_smape: 1.2950

Epoch 67/128

479/479 - 4s - 9ms/step - ia: 0.3547 - loss: 0.8543 - mae: 0.6834 - rmse: 0.9144 - smape: 1.3354 - val_ia: 0.2703 - val_loss: 0.7924 - val_mae: 0.6544 - val_rmse: 0.7779 - val_smape: 1.2938

Epoch 68/128

479/479 - 4s - 9ms/step - ia: 0.3536 - loss: 0.8549 - mae: 0.6845 - rmse: 0.9155 - smape: 1.3363 - val_ia: 0.2706 - val_loss: 0.7918 - val_mae: 0.6541 - val_rmse: 0.7776 - val_smape: 1.2923

Epoch 69/128

479/479 - 4s - 8ms/step - ia: 0.3566 - loss: 0.8560 - mae: 0.6835 - rmse: 0.9152 - smape: 1.3299 - val_ia: 0.2707 - val_loss: 0.7915 - val_mae: 0.6540 - val_rmse: 0.7775 - val_smape: 1.2919

Epoch 70/128

479/479 - 3s - 7ms/step - ia: 0.3566 - loss: 0.8548 - mae: 0.6838 - rmse: 0.9138 - smape: 1.3329 - val_ia: 0.2709 - val_loss: 0.7910 - val_mae: 0.6537 - val_rmse: 0.7774 - val_smape: 1.2909

Epoch 71/128

479/479 - 4s - 9ms/step - ia: 0.3568 - loss: 0.8558 - mae: 0.6837 - rmse: 0.9154 - smape: 1.3328 - val_ia: 0.2711 - val_loss: 0.7904 - val_mae: 0.6535 - val_rmse: 0.7772 - val_smape: 1.2899

Epoch 72/128

479/479 - 4s - 9ms/step - ia: 0.3561 - loss: 0.8551 - mae: 0.6835 - rmse: 0.9149 - smape: 1.3310 - val_ia: 0.2713 - val_loss: 0.7900 - val_mae: 0.6533 - val_rmse: 0.7770 - val_smape: 1.2890

Epoch 73/128

479/479 - 5s - 11ms/step - ia: 0.3595 - loss: 0.8532 - mae: 0.6828 - rmse: 0.9132 - smape: 1.3289 - val_ia: 0.2715 - val_loss: 0.7895 - val_mae: 0.6531 - val_rmse: 0.7768 - val_smape: 1.2880

Epoch 74/128

479/479 - 5s - 11ms/step - ia: 0.3581 - loss: 0.8543 - mae: 0.6833 - rmse: 0.9150 - smape: 1.3282 - val_ia: 0.2716 - val_loss: 0.7890 - val_mae: 0.6529 - val_rmse: 0.7767 - val_smape: 1.2875

Epoch 75/128

479/479 - 4s - 9ms/step - ia: 0.3591 - loss: 0.8513 - mae: 0.6826 - rmse: 0.9132 - smape: 1.3270 - val_ia: 0.2718 - val_loss: 0.7887 - val_mae: 0.6528 - val_rmse: 0.7766 - val_smape: 1.2869

Epoch 76/128

479/479 - 4s - 9ms/step - ia: 0.3614 - loss: 0.8491 - mae: 0.6810 - rmse: 0.9120 - smape: 1.3256 - val_ia: 0.2719 - val_loss: 0.7882 - val_mae: 0.6526 - val_rmse: 0.7764 - val_smape: 1.2862

Epoch 77/128

479/479 - 5s - 11ms/step - ia: 0.3612 - loss: 0.8521 - mae: 0.6820 - rmse: 0.9138 - smape: 1.3242 - val_ia: 0.2720 - val_loss: 0.7878 - val_mae: 0.6524 - val_rmse: 0.7763 - val_smape: 1.2856

Epoch 78/128

479/479 - 4s - 9ms/step - ia: 0.3604 - loss: 0.8500 - mae: 0.6818 - rmse: 0.9126 - smape: 1.3252 - val_ia: 0.2721 - val_loss: 0.7872 - val_mae: 0.6522 - val_rmse: 0.7760 - val_smape: 1.2850

Epoch 79/128

479/479 - 5s - 11ms/step - ia: 0.3606 - loss: 0.8522 - mae: 0.6822 - rmse: 0.9144 - smape: 1.3248 - val_ia: 0.2722 - val_loss: 0.7868 - val_mae: 0.6521 - val_rmse: 0.7759 - val_smape: 1.2845

Epoch 80/128

479/479 - 5s - 11ms/step - ia: 0.3619 - loss: 0.8505 - mae: 0.6816 - rmse: 0.9128 - smape: 1.3234 - val_ia: 0.2724 - val_loss: 0.7865 - val_mae: 0.6519 - val_rmse: 0.7758 - val_smape: 1.2841

Epoch 81/128

479/479 - 5s - 11ms/step - ia: 0.3618 - loss: 0.8502 - mae: 0.6821 - rmse: 0.9119 - smape: 1.3261 - val_ia: 0.2725 - val_loss: 0.7862 - val_mae: 0.6518 - val_rmse: 0.7757 - val_smape: 1.2840

Epoch 82/128

479/479 - 4s - 9ms/step - ia: 0.3619 - loss: 0.8470 - mae: 0.6805 - rmse: 0.9115 - smape: 1.3241 - val_ia: 0.2726 - val_loss: 0.7858 - val_mae: 0.6517 - val_rmse: 0.7755 - val_smape: 1.2836

Epoch 83/128

479/479 - 4s - 9ms/step - ia: 0.3619 - loss: 0.8495 - mae: 0.6821 - rmse: 0.9120 - smape: 1.3245 - val_ia: 0.2727 - val_loss: 0.7854 - val_mae: 0.6516 - val_rmse: 0.7754 - val_smape: 1.2832

Epoch 84/128

479/479 - 5s - 11ms/step - ia: 0.3629 - loss: 0.8483 - mae: 0.6807 - rmse: 0.9113 - smape: 1.3205 - val_ia: 0.2727 - val_loss: 0.7850 - val_mae: 0.6514 - val_rmse: 0.7752 - val_smape: 1.2828

Epoch 85/128

479/479 - 5s - 11ms/step - ia: 0.3620 - loss: 0.8519 - mae: 0.6824 - rmse: 0.9134 - smape: 1.3250 - val_ia: 0.2728 - val_loss: 0.7848 - val_mae: 0.6514 - val_rmse: 0.7752 - val_smape: 1.2828

Epoch 86/128

479/479 - 5s - 11ms/step - ia: 0.3634 - loss: 0.8498 - mae: 0.6814 - rmse: 0.9117 - smape: 1.3222 - val_ia: 0.2730 - val_loss: 0.7844 - val_mae: 0.6512 - val_rmse: 0.7751 - val_smape: 1.2824

Epoch 87/128

479/479 - 5s - 10ms/step - ia: 0.3646 - loss: 0.8459 - mae: 0.6798 - rmse: 0.9097 - smape: 1.3203 - val_ia: 0.2730 - val_loss: 0.7839 - val_mae: 0.6510 - val_rmse: 0.7748 - val_smape: 1.2818

Epoch 88/128

479/479 - 3s - 7ms/step - ia: 0.3653 - loss: 0.8467 - mae: 0.6795 - rmse: 0.9106 - smape: 1.3180 - val_ia: 0.2731 - val_loss: 0.7837 - val_mae: 0.6510 - val_rmse: 0.7748 - val_smape: 1.2819

Epoch 89/128

479/479 - 6s - 12ms/step - ia: 0.3658 - loss: 0.8466 - mae: 0.6799 - rmse: 0.9106 - smape: 1.3177 - val_ia: 0.2732 - val_loss: 0.7833 - val_mae: 0.6508 - val_rmse: 0.7746 - val_smape: 1.2814

Epoch 90/128

479/479 - 4s - 7ms/step - ia: 0.3654 - loss: 0.8478 - mae: 0.6798 - rmse: 0.9105 - smape: 1.3179 - val_ia: 0.2732 - val_loss: 0.7829 - val_mae: 0.6506 - val_rmse: 0.7744 - val_smape: 1.2807

Epoch 91/128

479/479 - 6s - 13ms/step - ia: 0.3654 - loss: 0.8479 - mae: 0.6809 - rmse: 0.9110 - smape: 1.3181 - val_ia: 0.2733 - val_loss: 0.7827 - val_mae: 0.6506 - val_rmse: 0.7744 - val_smape: 1.2811

Epoch 92/128

479/479 - 4s - 8ms/step - ia: 0.3657 - loss: 0.8456 - mae: 0.6795 - rmse: 0.9096 - smape: 1.3177 - val_ia: 0.2734 - val_loss: 0.7824 - val_mae: 0.6505 - val_rmse: 0.7743 - val_smape: 1.2809

Epoch 93/128

479/479 - 5s - 10ms/step - ia: 0.3655 - loss: 0.8450 - mae: 0.6790 - rmse: 0.9093 - smape: 1.3184 - val_ia: 0.2735 - val_loss: 0.7821 - val_mae: 0.6504 - val_rmse: 0.7742 - val_smape: 1.2807

Epoch 94/128

479/479 - 6s - 12ms/step - ia: 0.3665 - loss: 0.8509 - mae: 0.6798 - rmse: 0.9118 - smape: 1.3161 - val_ia: 0.2735 - val_loss: 0.7817 - val_mae: 0.6503 - val_rmse: 0.7741 - val_smape: 1.2804

Epoch 95/128

479/479 - 10s - 21ms/step - ia: 0.3663 - loss: 0.8454 - mae: 0.6791 - rmse: 0.9098 - smape: 1.3175 - val_ia: 0.2735 - val_loss: 0.7813 - val_mae: 0.6501 - val_rmse: 0.7738 - val_smape: 1.2800

Epoch 96/128

479/479 - 6s - 12ms/step - ia: 0.3664 - loss: 0.8452 - mae: 0.6789 - rmse: 0.9095 - smape: 1.3159 - val_ia: 0.2736 - val_loss: 0.7811 - val_mae: 0.6500 - val_rmse: 0.7738 - val_smape: 1.2797

Epoch 97/128

479/479 - 5s - 11ms/step - ia: 0.3650 - loss: 0.8474 - mae: 0.6795 - rmse: 0.9118 - smape: 1.3192 - val_ia: 0.2737 - val_loss: 0.7808 - val_mae: 0.6499 - val_rmse: 0.7737 - val_smape: 1.2796

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 17s - 71ms/step - ia: 0.3173 - loss: 3.6597 - mae: 1.5626 - rmse: 1.9079 - smape: 1.3278 - val_ia: 0.2864 - val_loss: 2.9794 - val_mae: 1.4166 - val_rmse: 1.6067 - val_smape: 1.2805

Epoch 2/128

240/240 - 4s - 15ms/step - ia: 0.3323 - loss: 3.2529 - mae: 1.4346 - rmse: 1.7988 - smape: 1.2943 - val_ia: 0.3119 - val_loss: 2.5786 - val_mae: 1.2675 - val_rmse: 1.4754 - val_smape: 1.2272

Epoch 3/128

240/240 - 5s - 23ms/step - ia: 0.3471 - loss: 2.8411 - mae: 1.3028 - rmse: 1.6799 - smape: 1.2631 - val_ia: 0.3412 - val_loss: 2.2421 - val_mae: 1.1273 - val_rmse: 1.3556 - val_smape: 1.1692

Epoch 4/128

240/240 - 10s - 40ms/step - ia: 0.3580 - loss: 2.5314 - mae: 1.2007 - rmse: 1.5854 - smape: 1.2427 - val_ia: 0.3758 - val_loss: 1.9577 - val_mae: 0.9936 - val_rmse: 1.2459 - val_smape: 1.1049

Epoch 5/128

240/240 - 5s - 22ms/step - ia: 0.3655 - loss: 2.2726 - mae: 1.1095 - rmse: 1.5013 - smape: 1.2305 - val_ia: 0.4036 - val_loss: 1.7204 - val_mae: 0.8808 - val_rmse: 1.1474 - val_smape: 1.0486

Epoch 6/128

240/240 - 5s - 21ms/step - ia: 0.3696 - loss: 2.0125 - mae: 1.0269 - rmse: 1.4140 - smape: 1.2287 - val_ia: 0.4041 - val_loss: 1.5269 - val_mae: 0.8030 - val_rmse: 1.0624 - val_smape: 1.0189

Epoch 7/128

240/240 - 5s - 21ms/step - ia: 0.3665 - loss: 1.8351 - mae: 0.9671 - rmse: 1.3496 - smape: 1.2386 - val_ia: 0.3763 - val_loss: 1.3708 - val_mae: 0.7488 - val_rmse: 0.9919 - val_smape: 1.0097

Epoch 8/128

240/240 - 3s - 13ms/step - ia: 0.3586 - loss: 1.6890 - mae: 0.9213 - rmse: 1.2917 - smape: 1.2619 - val_ia: 0.3331 - val_loss: 1.2490 - val_mae: 0.7137 - val_rmse: 0.9376 - val_smape: 1.0208

Epoch 9/128

240/240 - 5s - 21ms/step - ia: 0.3529 - loss: 1.5615 - mae: 0.8840 - rmse: 1.2429 - smape: 1.2824 - val_ia: 0.3089 - val_loss: 1.1551 - val_mae: 0.6929 - val_rmse: 0.8984 - val_smape: 1.0515

Epoch 10/128

240/240 - 4s - 17ms/step - ia: 0.3400 - loss: 1.4681 - mae: 0.8598 - rmse: 1.2039 - smape: 1.3061 - val_ia: 0.2772 - val_loss: 1.0864 - val_mae: 0.6834 - val_rmse: 0.8731 - val_smape: 1.1005

Epoch 11/128

240/240 - 4s - 17ms/step - ia: 0.3278 - loss: 1.3960 - mae: 0.8470 - rmse: 1.1741 - smape: 1.3391 - val_ia: 0.2636 - val_loss: 1.0368 - val_mae: 0.6820 - val_rmse: 0.8586 - val_smape: 1.1690

Epoch 12/128

240/240 - 5s - 22ms/step - ia: 0.3186 - loss: 1.3524 - mae: 0.8371 - rmse: 1.1557 - smape: 1.3562 - val_ia: 0.2457 - val_loss: 1.0028 - val_mae: 0.6865 - val_rmse: 0.8523 - val_smape: 1.2568

Epoch 13/128

240/240 - 9s - 40ms/step - ia: 0.3071 - loss: 1.3183 - mae: 0.8311 - rmse: 1.1406 - smape: 1.3786 - val_ia: 0.2424 - val_loss: 0.9820 - val_mae: 0.6937 - val_rmse: 0.8519 - val_smape: 1.3541

Epoch 14/128

240/240 - 3s - 13ms/step - ia: 0.2949 - loss: 1.2950 - mae: 0.8331 - rmse: 1.1325 - smape: 1.4065 - val_ia: 0.2402 - val_loss: 0.9699 - val_mae: 0.7022 - val_rmse: 0.8548 - val_smape: 1.4608

Epoch 15/128

240/240 - 5s - 20ms/step - ia: 0.2898 - loss: 1.2690 - mae: 0.8303 - rmse: 1.1209 - smape: 1.4166 - val_ia: 0.2444 - val_loss: 0.9638 - val_mae: 0.7105 - val_rmse: 0.8592 - val_smape: 1.5685

Epoch 16/128

240/240 - 5s - 22ms/step - ia: 0.2835 - loss: 1.2611 - mae: 0.8305 - rmse: 1.1172 - smape: 1.4284 - val_ia: 0.2502 - val_loss: 0.9613 - val_mae: 0.7178 - val_rmse: 0.8638 - val_smape: 1.6731

Epoch 17/128

240/240 - 5s - 19ms/step - ia: 0.2796 - loss: 1.2578 - mae: 0.8341 - rmse: 1.1145 - smape: 1.4378 - val_ia: 0.2528 - val_loss: 0.9604 - val_mae: 0.7237 - val_rmse: 0.8678 - val_smape: 1.7675

Epoch 18/128

240/240 - 3s - 15ms/step - ia: 0.2753 - loss: 1.2511 - mae: 0.8344 - rmse: 1.1132 - smape: 1.4451 - val_ia: 0.2538 - val_loss: 0.9603 - val_mae: 0.7281 - val_rmse: 0.8709 - val_smape: 1.8527

Epoch 19/128

240/240 - 6s - 23ms/step - ia: 0.2720 - loss: 1.2478 - mae: 0.8361 - rmse: 1.1101 - smape: 1.4532 - val_ia: 0.2543 - val_loss: 0.9604 - val_mae: 0.7318 - val_rmse: 0.8736 - val_smape: 1.9187

Epoch 20/128

240/240 - 10s - 42ms/step - ia: 0.2744 - loss: 1.2290 - mae: 0.8320 - rmse: 1.1031 - smape: 1.4500 - val_ia: 0.2546 - val_loss: 0.9603 - val_mae: 0.7342 - val_rmse: 0.8753 - val_smape: 1.9310

Epoch 21/128

240/240 - 5s - 23ms/step - ia: 0.2696 - loss: 1.2281 - mae: 0.8338 - rmse: 1.1020 - smape: 1.4571 - val_ia: 0.2547 - val_loss: 0.9597 - val_mae: 0.7347 - val_rmse: 0.8756 - val_smape: 1.9258

Epoch 22/128

240/240 - 3s - 14ms/step - ia: 0.2696 - loss: 1.2185 - mae: 0.8321 - rmse: 1.0986 - smape: 1.4600 - val_ia: 0.2548 - val_loss: 0.9593 - val_mae: 0.7358 - val_rmse: 0.8763 - val_smape: 1.9150

Epoch 23/128

240/240 - 5s - 19ms/step - ia: 0.2640 - loss: 1.2221 - mae: 0.8335 - rmse: 1.1007 - smape: 1.4685 - val_ia: 0.2549 - val_loss: 0.9586 - val_mae: 0.7360 - val_rmse: 0.8764 - val_smape: 1.9087

Epoch 24/128

240/240 - 4s - 18ms/step - ia: 0.2669 - loss: 1.2157 - mae: 0.8290 - rmse: 1.0995 - smape: 1.4633 - val_ia: 0.2550 - val_loss: 0.9576 - val_mae: 0.7355 - val_rmse: 0.8758 - val_smape: 1.9083

Epoch 25/128

240/240 - 4s - 15ms/step - ia: 0.2627 - loss: 1.2164 - mae: 0.8297 - rmse: 1.0976 - smape: 1.4683 - val_ia: 0.2551 - val_loss: 0.9569 - val_mae: 0.7357 - val_rmse: 0.8758 - val_smape: 1.9025

Epoch 26/128

240/240 - 5s - 22ms/step - ia: 0.2654 - loss: 1.2011 - mae: 0.8229 - rmse: 1.0905 - smape: 1.4634 - val_ia: 0.2551 - val_loss: 0.9564 - val_mae: 0.7365 - val_rmse: 0.8763 - val_smape: 1.8929

Epoch 27/128

240/240 - 3s - 14ms/step - ia: 0.2673 - loss: 1.1916 - mae: 0.8211 - rmse: 1.0856 - smape: 1.4623 - val_ia: 0.2553 - val_loss: 0.9561 - val_mae: 0.7376 - val_rmse: 0.8771 - val_smape: 1.8808

Epoch 28/128

240/240 - 5s - 20ms/step - ia: 0.2606 - loss: 1.1943 - mae: 0.8235 - rmse: 1.0869 - smape: 1.4738 - val_ia: 0.2554 - val_loss: 0.9548 - val_mae: 0.7363 - val_rmse: 0.8759 - val_smape: 1.8862

Epoch 29/128

240/240 - 6s - 24ms/step - ia: 0.2633 - loss: 1.1769 - mae: 0.8159 - rmse: 1.0787 - smape: 1.4695 - val_ia: 0.2555 - val_loss: 0.9537 - val_mae: 0.7355 - val_rmse: 0.8751 - val_smape: 1.8876

Epoch 30/128

240/240 - 4s - 18ms/step - ia: 0.2615 - loss: 1.1696 - mae: 0.8148 - rmse: 1.0749 - smape: 1.4755 - val_ia: 0.2556 - val_loss: 0.9530 - val_mae: 0.7358 - val_rmse: 0.8752 - val_smape: 1.8821

Epoch 31/128

240/240 - 4s - 16ms/step - ia: 0.2560 - loss: 1.1774 - mae: 0.8167 - rmse: 1.0803 - smape: 1.4780 - val_ia: 0.2557 - val_loss: 0.9524 - val_mae: 0.7361 - val_rmse: 0.8754 - val_smape: 1.8763

Epoch 32/128

240/240 - 5s - 23ms/step - ia: 0.2568 - loss: 1.1636 - mae: 0.8129 - rmse: 1.0729 - smape: 1.4805 - val_ia: 0.2558 - val_loss: 0.9514 - val_mae: 0.7356 - val_rmse: 0.8748 - val_smape: 1.8762

Epoch 33/128

240/240 - 5s - 23ms/step - ia: 0.2544 - loss: 1.1624 - mae: 0.8099 - rmse: 1.0725 - smape: 1.4787 - val_ia: 0.2559 - val_loss: 0.9503 - val_mae: 0.7347 - val_rmse: 0.8740 - val_smape: 1.8772

Epoch 34/128

240/240 - 10s - 42ms/step - ia: 0.2576 - loss: 1.1523 - mae: 0.8062 - rmse: 1.0676 - smape: 1.4762 - val_ia: 0.2561 - val_loss: 0.9498 - val_mae: 0.7354 - val_rmse: 0.8744 - val_smape: 1.8706

Epoch 35/128

240/240 - 3s - 14ms/step - ia: 0.2559 - loss: 1.1458 - mae: 0.8052 - rmse: 1.0650 - smape: 1.4809 - val_ia: 0.2562 - val_loss: 0.9487 - val_mae: 0.7346 - val_rmse: 0.8736 - val_smape: 1.8715

Epoch 36/128

240/240 - 5s - 20ms/step - ia: 0.2593 - loss: 1.1337 - mae: 0.8006 - rmse: 1.0595 - smape: 1.4769 - val_ia: 0.2563 - val_loss: 0.9480 - val_mae: 0.7346 - val_rmse: 0.8735 - val_smape: 1.8683

Epoch 37/128

240/240 - 5s - 22ms/step - ia: 0.2542 - loss: 1.1386 - mae: 0.8018 - rmse: 1.0625 - smape: 1.4831 - val_ia: 0.2564 - val_loss: 0.9471 - val_mae: 0.7341 - val_rmse: 0.8730 - val_smape: 1.8670

Epoch 38/128

240/240 - 5s - 22ms/step - ia: 0.2535 - loss: 1.1311 - mae: 0.7994 - rmse: 1.0574 - smape: 1.4819 - val_ia: 0.2565 - val_loss: 0.9464 - val_mae: 0.7341 - val_rmse: 0.8729 - val_smape: 1.8644

Epoch 39/128

240/240 - 10s - 41ms/step - ia: 0.2504 - loss: 1.1354 - mae: 0.7998 - rmse: 1.0603 - smape: 1.4881 - val_ia: 0.2566 - val_loss: 0.9456 - val_mae: 0.7338 - val_rmse: 0.8725 - val_smape: 1.8622

Epoch 40/128

240/240 - 3s - 14ms/step - ia: 0.2500 - loss: 1.1284 - mae: 0.7957 - rmse: 1.0562 - smape: 1.4877 - val_ia: 0.2567 - val_loss: 0.9449 - val_mae: 0.7338 - val_rmse: 0.8724 - val_smape: 1.8594

Epoch 41/128

240/240 - 5s - 20ms/step - ia: 0.2480 - loss: 1.1201 - mae: 0.7970 - rmse: 1.0526 - smape: 1.4938 - val_ia: 0.2567 - val_loss: 0.9439 - val_mae: 0.7329 - val_rmse: 0.8716 - val_smape: 1.8596

Epoch 42/128

240/240 - 4s - 17ms/step - ia: 0.2469 - loss: 1.1160 - mae: 0.7932 - rmse: 1.0512 - smape: 1.4944 - val_ia: 0.2569 - val_loss: 0.9433 - val_mae: 0.7332 - val_rmse: 0.8717 - val_smape: 1.8560

Epoch 43/128

240/240 - 4s - 16ms/step - ia: 0.2463 - loss: 1.1095 - mae: 0.7916 - rmse: 1.0485 - smape: 1.4920 - val_ia: 0.2569 - val_loss: 0.9424 - val_mae: 0.7325 - val_rmse: 0.8710 - val_smape: 1.8551

Epoch 44/128

240/240 - 5s - 22ms/step - ia: 0.2461 - loss: 1.1129 - mae: 0.7900 - rmse: 1.0494 - smape: 1.4918 - val_ia: 0.2570 - val_loss: 0.9418 - val_mae: 0.7324 - val_rmse: 0.8709 - val_smape: 1.8527

Epoch 45/128

240/240 - 5s - 22ms/step - ia: 0.2446 - loss: 1.1063 - mae: 0.7891 - rmse: 1.0455 - smape: 1.4972 - val_ia: 0.2571 - val_loss: 0.9412 - val_mae: 0.7325 - val_rmse: 0.8709 - val_smape: 1.8496

Epoch 46/128

240/240 - 10s - 43ms/step - ia: 0.2457 - loss: 1.0951 - mae: 0.7856 - rmse: 1.0414 - smape: 1.4945 - val_ia: 0.2572 - val_loss: 0.9401 - val_mae: 0.7315 - val_rmse: 0.8699 - val_smape: 1.8498

Epoch 47/128

240/240 - 5s - 22ms/step - ia: 0.2416 - loss: 1.0950 - mae: 0.7861 - rmse: 1.0409 - smape: 1.4974 - val_ia: 0.2572 - val_loss: 0.9391 - val_mae: 0.7308 - val_rmse: 0.8692 - val_smape: 1.8487

Epoch 48/128

240/240 - 5s - 22ms/step - ia: 0.2414 - loss: 1.0902 - mae: 0.7835 - rmse: 1.0387 - smape: 1.4999 - val_ia: 0.2573 - val_loss: 0.9384 - val_mae: 0.7305 - val_rmse: 0.8689 - val_smape: 1.8466

Epoch 49/128

240/240 - 4s - 15ms/step - ia: 0.2438 - loss: 1.0834 - mae: 0.7782 - rmse: 1.0343 - smape: 1.4916 - val_ia: 0.2574 - val_loss: 0.9377 - val_mae: 0.7303 - val_rmse: 0.8687 - val_smape: 1.8445

Epoch 50/128

240/240 - 4s - 18ms/step - ia: 0.2364 - loss: 1.0853 - mae: 0.7828 - rmse: 1.0364 - smape: 1.5094 - val_ia: 0.2575 - val_loss: 0.9372 - val_mae: 0.7304 - val_rmse: 0.8687 - val_smape: 1.8419

Epoch 51/128

240/240 - 5s - 20ms/step - ia: 0.2392 - loss: 1.0805 - mae: 0.7797 - rmse: 1.0346 - smape: 1.5009 - val_ia: 0.2576 - val_loss: 0.9366 - val_mae: 0.7303 - val_rmse: 0.8685 - val_smape: 1.8397

Epoch 52/128

240/240 - 3s - 14ms/step - ia: 0.2360 - loss: 1.0744 - mae: 0.7784 - rmse: 1.0325 - smape: 1.5063 - val_ia: 0.2576 - val_loss: 0.9356 - val_mae: 0.7294 - val_rmse: 0.8677 - val_smape: 1.8383

Epoch 53/128

240/240 - 5s - 22ms/step - ia: 0.2387 - loss: 1.0720 - mae: 0.7757 - rmse: 1.0298 - smape: 1.5056 - val_ia: 0.2577 - val_loss: 0.9350 - val_mae: 0.7292 - val_rmse: 0.8674 - val_smape: 1.8362

Epoch 54/128

240/240 - 5s - 22ms/step - ia: 0.2334 - loss: 1.0763 - mae: 0.7776 - rmse: 1.0315 - smape: 1.5126 - val_ia: 0.2578 - val_loss: 0.9346 - val_mae: 0.7298 - val_rmse: 0.8678 - val_smape: 1.8335

Epoch 55/128

240/240 - 10s - 42ms/step - ia: 0.2371 - loss: 1.0637 - mae: 0.7719 - rmse: 1.0266 - smape: 1.5038 - val_ia: 0.2579 - val_loss: 0.9341 - val_mae: 0.7300 - val_rmse: 0.8678 - val_smape: 1.8309

Epoch 56/128

240/240 - 5s - 23ms/step - ia: 0.2331 - loss: 1.0652 - mae: 0.7732 - rmse: 1.0266 - smape: 1.5098 - val_ia: 0.2579 - val_loss: 0.9329 - val_mae: 0.7284 - val_rmse: 0.8665 - val_smape: 1.8297

Epoch 57/128

240/240 - 5s - 22ms/step - ia: 0.2333 - loss: 1.0547 - mae: 0.7707 - rmse: 1.0212 - smape: 1.5135 - val_ia: 0.2580 - val_loss: 0.9323 - val_mae: 0.7283 - val_rmse: 0.8663 - val_smape: 1.8276

Epoch 58/128

240/240 - 11s - 45ms/step - ia: 0.2307 - loss: 1.0598 - mae: 0.7729 - rmse: 1.0238 - smape: 1.5146 - val_ia: 0.2581 - val_loss: 0.9315 - val_mae: 0.7277 - val_rmse: 0.8657 - val_smape: 1.8256

Epoch 59/128

240/240 - 5s - 22ms/step - ia: 0.2322 - loss: 1.0512 - mae: 0.7691 - rmse: 1.0189 - smape: 1.5150 - val_ia: 0.2581 - val_loss: 0.9306 - val_mae: 0.7272 - val_rmse: 0.8652 - val_smape: 1.8234

Epoch 60/128

240/240 - 4s - 17ms/step - ia: 0.2304 - loss: 1.0538 - mae: 0.7687 - rmse: 1.0198 - smape: 1.5172 - val_ia: 0.2582 - val_loss: 0.9299 - val_mae: 0.7268 - val_rmse: 0.8648 - val_smape: 1.8211

Epoch 61/128

240/240 - 4s - 17ms/step - ia: 0.2271 - loss: 1.0541 - mae: 0.7706 - rmse: 1.0212 - smape: 1.5232 - val_ia: 0.2582 - val_loss: 0.9289 - val_mae: 0.7258 - val_rmse: 0.8639 - val_smape: 1.8181

Epoch 62/128

240/240 - 5s - 22ms/step - ia: 0.2323 - loss: 1.0420 - mae: 0.7635 - rmse: 1.0152 - smape: 1.5109 - val_ia: 0.2585 - val_loss: 0.9290 - val_mae: 0.7273 - val_rmse: 0.8651 - val_smape: 1.8170

Epoch 63/128

240/240 - 3s - 14ms/step - ia: 0.2310 - loss: 1.0401 - mae: 0.7630 - rmse: 1.0139 - smape: 1.5155 - val_ia: 0.2585 - val_loss: 0.9281 - val_mae: 0.7267 - val_rmse: 0.8644 - val_smape: 1.8148

Epoch 64/128

240/240 - 5s - 22ms/step - ia: 0.2262 - loss: 1.0446 - mae: 0.7659 - rmse: 1.0163 - smape: 1.5236 - val_ia: 0.2587 - val_loss: 0.9277 - val_mae: 0.7271 - val_rmse: 0.8646 - val_smape: 1.8127

Epoch 65/128

240/240 - 5s - 22ms/step - ia: 0.2249 - loss: 1.0454 - mae: 0.7662 - rmse: 1.0175 - smape: 1.5248 - val_ia: 0.2587 - val_loss: 0.9270 - val_mae: 0.7265 - val_rmse: 0.8641 - val_smape: 1.8106

Epoch 66/128

240/240 - 4s - 16ms/step - ia: 0.2247 - loss: 1.0403 - mae: 0.7645 - rmse: 1.0131 - smape: 1.5227 - val_ia: 0.2588 - val_loss: 0.9261 - val_mae: 0.7259 - val_rmse: 0.8635 - val_smape: 1.8080

Epoch 67/128

240/240 - 4s - 18ms/step - ia: 0.2267 - loss: 1.0325 - mae: 0.7611 - rmse: 1.0108 - smape: 1.5200 - val_ia: 0.2589 - val_loss: 0.9254 - val_mae: 0.7255 - val_rmse: 0.8631 - val_smape: 1.8054

Epoch 68/128

240/240 - 6s - 26ms/step - ia: 0.2235 - loss: 1.0359 - mae: 0.7623 - rmse: 1.0123 - smape: 1.5278 - val_ia: 0.2590 - val_loss: 0.9250 - val_mae: 0.7259 - val_rmse: 0.8634 - val_smape: 1.8040

Epoch 69/128

240/240 - 5s - 19ms/step - ia: 0.2262 - loss: 1.0294 - mae: 0.7589 - rmse: 1.0085 - smape: 1.5220 - val_ia: 0.2591 - val_loss: 0.9242 - val_mae: 0.7253 - val_rmse: 0.8628 - val_smape: 1.8012

Epoch 70/128

240/240 - 3s - 14ms/step - ia: 0.2234 - loss: 1.0290 - mae: 0.7605 - rmse: 1.0079 - smape: 1.5278 - val_ia: 0.2592 - val_loss: 0.9234 - val_mae: 0.7250 - val_rmse: 0.8624 - val_smape: 1.7987

Epoch 71/128

240/240 - 7s - 29ms/step - ia: 0.2220 - loss: 1.0298 - mae: 0.7609 - rmse: 1.0086 - smape: 1.5308 - val_ia: 0.2593 - val_loss: 0.9227 - val_mae: 0.7246 - val_rmse: 0.8620 - val_smape: 1.7964

Epoch 72/128

240/240 - 5s - 22ms/step - ia: 0.2218 - loss: 1.0258 - mae: 0.7587 - rmse: 1.0075 - smape: 1.5311 - val_ia: 0.2594 - val_loss: 0.9223 - val_mae: 0.7251 - val_rmse: 0.8623 - val_smape: 1.7950

Epoch 73/128

240/240 - 10s - 43ms/step - ia: 0.2245 - loss: 1.0203 - mae: 0.7557 - rmse: 1.0050 - smape: 1.5219 - val_ia: 0.2595 - val_loss: 0.9216 - val_mae: 0.7246 - val_rmse: 0.8619 - val_smape: 1.7922

Epoch 74/128

240/240 - 5s - 22ms/step - ia: 0.2227 - loss: 1.0189 - mae: 0.7569 - rmse: 1.0039 - smape: 1.5293 - val_ia: 0.2596 - val_loss: 0.9205 - val_mae: 0.7237 - val_rmse: 0.8610 - val_smape: 1.7891

Epoch 75/128

240/240 - 10s - 43ms/step - ia: 0.2219 - loss: 1.0198 - mae: 0.7563 - rmse: 1.0039 - smape: 1.5309 - val_ia: 0.2597 - val_loss: 0.9199 - val_mae: 0.7237 - val_rmse: 0.8609 - val_smape: 1.7870

Epoch 76/128

240/240 - 5s - 22ms/step - ia: 0.2198 - loss: 1.0119 - mae: 0.7538 - rmse: 1.0008 - smape: 1.5348 - val_ia: 0.2597 - val_loss: 0.9188 - val_mae: 0.7225 - val_rmse: 0.8599 - val_smape: 1.7829

Epoch 77/128

240/240 - 5s - 22ms/step - ia: 0.2204 - loss: 1.0141 - mae: 0.7547 - rmse: 1.0007 - smape: 1.5340 - val_ia: 0.2599 - val_loss: 0.9182 - val_mae: 0.7226 - val_rmse: 0.8599 - val_smape: 1.7810

Epoch 78/128

240/240 - 10s - 43ms/step - ia: 0.2223 - loss: 1.0083 - mae: 0.7525 - rmse: 0.9976 - smape: 1.5298 - val_ia: 0.2599 - val_loss: 0.9172 - val_mae: 0.7219 - val_rmse: 0.8591 - val_smape: 1.7775

Epoch 79/128

240/240 - 10s - 43ms/step - ia: 0.2196 - loss: 1.0101 - mae: 0.7537 - rmse: 0.9987 - smape: 1.5343 - val_ia: 0.2600 - val_loss: 0.9163 - val_mae: 0.7212 - val_rmse: 0.8585 - val_smape: 1.7738

Epoch 80/128

240/240 - 9s - 38ms/step - ia: 0.2190 - loss: 1.0105 - mae: 0.7526 - rmse: 1.0000 - smape: 1.5334 - val_ia: 0.2602 - val_loss: 0.9156 - val_mae: 0.7211 - val_rmse: 0.8584 - val_smape: 1.7717

Epoch 81/128

240/240 - 4s - 16ms/step - ia: 0.2232 - loss: 1.0074 - mae: 0.7501 - rmse: 0.9972 - smape: 1.5244 - val_ia: 0.2603 - val_loss: 0.9152 - val_mae: 0.7216 - val_rmse: 0.8586 - val_smape: 1.7707

Epoch 82/128

240/240 - 4s - 18ms/step - ia: 0.2180 - loss: 1.0097 - mae: 0.7523 - rmse: 0.9983 - smape: 1.5366 - val_ia: 0.2604 - val_loss: 0.9142 - val_mae: 0.7208 - val_rmse: 0.8579 - val_smape: 1.7669

Epoch 83/128

240/240 - 4s - 18ms/step - ia: 0.2224 - loss: 0.9999 - mae: 0.7487 - rmse: 0.9936 - smape: 1.5286 - val_ia: 0.2606 - val_loss: 0.9136 - val_mae: 0.7208 - val_rmse: 0.8578 - val_smape: 1.7650

Epoch 84/128

240/240 - 4s - 18ms/step - ia: 0.2191 - loss: 1.0065 - mae: 0.7507 - rmse: 0.9965 - smape: 1.5369 - val_ia: 0.2606 - val_loss: 0.9125 - val_mae: 0.7198 - val_rmse: 0.8569 - val_smape: 1.7602

Epoch 85/128

240/240 - 5s - 19ms/step - ia: 0.2185 - loss: 1.0010 - mae: 0.7495 - rmse: 0.9947 - smape: 1.5354 - val_ia: 0.2608 - val_loss: 0.9118 - val_mae: 0.7198 - val_rmse: 0.8567 - val_smape: 1.7580

Epoch 86/128

240/240 - 5s - 21ms/step - ia: 0.2193 - loss: 1.0009 - mae: 0.7484 - rmse: 0.9959 - smape: 1.5333 - val_ia: 0.2609 - val_loss: 0.9108 - val_mae: 0.7191 - val_rmse: 0.8561 - val_smape: 1.7543

Epoch 87/128

240/240 - 4s - 17ms/step - ia: 0.2213 - loss: 0.9978 - mae: 0.7465 - rmse: 0.9928 - smape: 1.5301 - val_ia: 0.2611 - val_loss: 0.9104 - val_mae: 0.7197 - val_rmse: 0.8565 - val_smape: 1.7540

Epoch 88/128

240/240 - 5s - 21ms/step - ia: 0.2209 - loss: 0.9956 - mae: 0.7467 - rmse: 0.9930 - smape: 1.5306 - val_ia: 0.2612 - val_loss: 0.9092 - val_mae: 0.7187 - val_rmse: 0.8556 - val_smape: 1.7491

Epoch 89/128

240/240 - 5s - 20ms/step - ia: 0.2213 - loss: 0.9926 - mae: 0.7434 - rmse: 0.9897 - smape: 1.5291 - val_ia: 0.2614 - val_loss: 0.9086 - val_mae: 0.7189 - val_rmse: 0.8557 - val_smape: 1.7474

Epoch 90/128

240/240 - 4s - 17ms/step - ia: 0.2208 - loss: 0.9931 - mae: 0.7456 - rmse: 0.9899 - smape: 1.5307 - val_ia: 0.2615 - val_loss: 0.9076 - val_mae: 0.7183 - val_rmse: 0.8551 - val_smape: 1.7438

Epoch 91/128

240/240 - 4s - 18ms/step - ia: 0.2165 - loss: 0.9993 - mae: 0.7489 - rmse: 0.9934 - smape: 1.5411 - val_ia: 0.2616 - val_loss: 0.9066 - val_mae: 0.7177 - val_rmse: 0.8544 - val_smape: 1.7401

Epoch 92/128

240/240 - 6s - 25ms/step - ia: 0.2208 - loss: 0.9888 - mae: 0.7444 - rmse: 0.9877 - smape: 1.5330 - val_ia: 0.2617 - val_loss: 0.9056 - val_mae: 0.7169 - val_rmse: 0.8537 - val_smape: 1.7357

Epoch 93/128

240/240 - 5s - 20ms/step - ia: 0.2202 - loss: 0.9882 - mae: 0.7447 - rmse: 0.9876 - smape: 1.5349 - val_ia: 0.2619 - val_loss: 0.9046 - val_mae: 0.7164 - val_rmse: 0.8532 - val_smape: 1.7321

Epoch 94/128

240/240 - 5s - 20ms/step - ia: 0.2183 - loss: 0.9904 - mae: 0.7453 - rmse: 0.9899 - smape: 1.5380 - val_ia: 0.2620 - val_loss: 0.9036 - val_mae: 0.7159 - val_rmse: 0.8526 - val_smape: 1.7286

Epoch 95/128

240/240 - 4s - 16ms/step - ia: 0.2192 - loss: 0.9854 - mae: 0.7442 - rmse: 0.9874 - smape: 1.5330 - val_ia: 0.2621 - val_loss: 0.9026 - val_mae: 0.7151 - val_rmse: 0.8519 - val_smape: 1.7245

Epoch 96/128

240/240 - 5s - 21ms/step - ia: 0.2190 - loss: 0.9894 - mae: 0.7435 - rmse: 0.9888 - smape: 1.5302 - val_ia: 0.2623 - val_loss: 0.9016 - val_mae: 0.7147 - val_rmse: 0.8515 - val_smape: 1.7212

Epoch 97/128

240/240 - 5s - 20ms/step - ia: 0.2206 - loss: 0.9870 - mae: 0.7426 - rmse: 0.9873 - smape: 1.5322 - val_ia: 0.2625 - val_loss: 0.9010 - val_mae: 0.7150 - val_rmse: 0.8517 - val_smape: 1.7199

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 8s - 32ms/step - ia: 0.3828 - loss: 0.8354 - mae: 0.6702 - rmse: 0.9082 - smape: 1.2905 - val_ia: 0.3113 - val_loss: 0.7426 - val_mae: 0.6342 - val_rmse: 0.7768 - val_smape: 1.2535

Epoch 2/128

240/240 - 4s - 18ms/step - ia: 0.4107 - loss: 0.7909 - mae: 0.6508 - rmse: 0.8841 - smape: 1.2482 - val_ia: 0.3596 - val_loss: 0.7815 - val_mae: 0.6508 - val_rmse: 0.8117 - val_smape: 1.2337

Epoch 3/128

240/240 - 3s - 11ms/step - ia: 0.4268 - loss: 0.7709 - mae: 0.6422 - rmse: 0.8725 - smape: 1.2318 - val_ia: 0.3342 - val_loss: 0.7796 - val_mae: 0.6596 - val_rmse: 0.8076 - val_smape: 1.3329

Epoch 4/128

240/240 - 3s - 11ms/step - ia: 0.4266 - loss: 0.7701 - mae: 0.6421 - rmse: 0.8718 - smape: 1.2329 - val_ia: 0.3720 - val_loss: 0.8097 - val_mae: 0.6557 - val_rmse: 0.8271 - val_smape: 1.2014

Epoch 5/128

240/240 - 2s - 9ms/step - ia: 0.4064 - loss: 399.1174 - mae: 1.8162 - rmse: 4.5455 - smape: 1.2517 - val_ia: 0.1003 - val_loss: 23231.2949 - val_mae: 47.1133 - val_rmse: 97.4757 - val_smape: 1.6374

Epoch 6/128

240/240 - 2s - 9ms/step - ia: 4.4588e-04 - loss: 30203500544.0000 - mae: 56166.9688 - rmse: 103472.4453 - smape: 1.9682 - val_ia: 6.7025e-06 - val_loss: 63823515648.0000 - val_mae: 147470.9062 - val_rmse: 235064.0000 - val_smape: 1.9996

Epoch 7/128

240/240 - 2s - 7ms/step - ia: 2.1112e-06 - loss: 1038484635648.0000 - mae: 501895.2188 - rmse: 876891.8125 - smape: 1.9999 - val_ia: 6.7941e-06 - val_loss: 34076729344.0000 - val_mae: 118371.0078 - val_rmse: 175938.0625 - val_smape: 1.9995

Epoch 8/128

240/240 - 3s - 11ms/step - ia: 1.5504e-05 - loss: 76922839040.0000 - mae: 115279.0156 - rmse: 203708.2656 - smape: 1.9994 - val_ia: 7.5954e-05 - val_loss: 333725088.0000 - val_mae: 10934.5938 - val_rmse: 16805.8887 - val_smape: 1.9985

Epoch 9/128

240/240 - 3s - 11ms/step - ia: 1.7668e-04 - loss: 136092352.0000 - mae: 5520.1006 - rmse: 10226.0869 - smape: 1.9948 - val_ia: 5.7177e-04 - val_loss: 12405360.0000 - val_mae: 1816.3146 - val_rmse: 3062.1453 - val_smape: 1.9922

Epoch 10/128

240/240 - 2s - 6ms/step - ia: 6.2061e-04 - loss: 8108097.0000 - mae: 1360.6473 - rmse: 2653.6560 - smape: 1.9855 - val_ia: 0.0020 - val_loss: 1638191.5000 - val_mae: 604.1480 - val_rmse: 1094.9152 - val_smape: 1.9772

Epoch 11/128

240/240 - 2s - 7ms/step - ia: 0.0018 - loss: 1206297.2500 - mae: 462.0451 - rmse: 989.8805 - smape: 1.9675 - val_ia: 0.0071 - val_loss: 207105.3750 - val_mae: 199.3458 - val_rmse: 382.9373 - val_smape: 1.9126

Epoch 12/128

240/240 - 2s - 7ms/step - ia: 0.0056 - loss: 118604.5703 - mae: 144.9645 - rmse: 323.6103 - smape: 1.9152 - val_ia: 0.0157 - val_loss: 32450.6523 - val_mae: 73.3137 - val_rmse: 149.0799 - val_smape: 1.8890

Epoch 13/128

240/240 - 2s - 7ms/step - ia: 0.0162 - loss: 16850.7168 - mae: 48.7765 - rmse: 116.0548 - smape: 1.8305 - val_ia: 0.0428 - val_loss: 3352.2175 - val_mae: 23.5927 - val_rmse: 47.6372 - val_smape: 1.7202

Epoch 14/128

240/240 - 3s - 11ms/step - ia: 0.0466 - loss: 1689.2312 - mae: 15.3902 - rmse: 36.4932 - smape: 1.7139 - val_ia: 0.1086 - val_loss: 270.1379 - val_mae: 7.4667 - val_rmse: 13.8098 - val_smape: 1.5707

Epoch 15/128

240/240 - 2s - 7ms/step - ia: 0.1232 - loss: 122.0104 - mae: 4.2984 - rmse: 9.6508 - smape: 1.5717 - val_ia: 0.1818 - val_loss: 13.3030 - val_mae: 1.8241 - val_rmse: 3.1680 - val_smape: 1.5838

Epoch 16/128

240/240 - 3s - 11ms/step - ia: 0.2059 - loss: 6.0718 - mae: 1.2917 - rmse: 2.2848 - smape: 1.5337 - val_ia: 0.2473 - val_loss: 1.4607 - val_mae: 0.8494 - val_rmse: 1.1316 - val_smape: 1.6657

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 24s 180ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 93/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
123/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Epoch 1/128

 58%|█████▊    | 7/12 [2:38:57<1:16:44, 920.95s/trial, best loss: 0.7654894358534513]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

3830/3830 - 53s - 14ms/step - ia: 0.3826 - loss: 0.8271 - mae: 0.6666 - rmse: 0.8515 - smape: 1.2820 - val_ia: 0.2044 - val_loss: 0.7629 - val_mae: 0.6428 - val_rmse: 0.6839 - val_smape: 1.2796

Epoch 2/128

3830/3830 - 79s - 21ms/step - ia: 0.4028 - loss: 0.7902 - mae: 0.6491 - rmse: 0.8333 - smape: 1.2412 - val_ia: 0.2074 - val_loss: 0.7513 - val_mae: 0.6388 - val_rmse: 0.6813 - val_smape: 1.2283

Epoch 3/128

3830/3830 - 33s - 9ms/step - ia: 0.4184 - loss: 0.7612 - mae: 0.6367 - rmse: 0.8140 - smape: 1.2238 - val_ia: 0.2091 - val_loss: 0.7730 - val_mae: 0.6318 - val_rmse: 0.6769 - val_smape: 1.1795

Epoch 4/128

3830/3830 - 40s - 10ms/step - ia: 0.4331 - loss: 0.7208 - mae: 0.6205 - rmse: 0.7939 - smape: 1.2026 - val_ia: 0.2051 - val_loss: 0.8954 - val_mae: 0.6807 - val_rmse: 0.7321 - val_smape: 1.2083

Epoch 5/128

3830/3830 - 36s - 9ms/step - ia: 0.4460 - loss: 0.6814 - mae: 0.6065 - rmse: 0.7735 - smape: 1.1815 - val_ia: 0.2049 - val_loss: 0.8040 - val_mae: 0.6418 - val_rmse: 0.6868 - val_smape: 1.2415

Epoch 6/128

3830/3830 - 37s - 10ms/step - ia: 0.4593 - loss: 0.6413 - mae: 0.5897 - rmse: 0.7514 - smape: 1.1608 - val_ia: 0.1986 - val_loss: 0.8081 - val_mae: 0.6592 - val_rmse: 0.7049 - val_smape: 1.3019

Epoch 7/128

3830/3830 - 38s - 10ms/step - ia: 0.4709 - loss: 0.6154 - mae: 0.5789 - rmse: 0.7367 - smape: 1.1457 - val_ia: 0.2029 - val_loss: 0.9013 - val_mae: 0.6628 - val_rmse: 0.7169 - val_smape: 1.2434

Epoch 8/128

3830/3830 - 35s - 9ms/step - ia: 0.4833 - loss: 0.5793 - mae: 0.5651 - rmse: 0.7163 - smape: 1.1280 - val_ia: 0.2008 - val_loss: 0.8611 - val_mae: 0.6638 - val_rmse: 0.7123 - val_smape: 1.2755

Epoch 9/128

3830/3830 - 40s - 11ms/step - ia: 0.4891 - loss: 0.5724 - mae: 0.5611 - rmse: 0.7115 - smape: 1.1241 - val_ia: 0.1994 - val_loss: 0.9012 - val_mae: 0.6759 - val_rmse: 0.7299 - val_smape: 1.2798

Epoch 10/128

3830/3830 - 31s - 8ms/step - ia: 0.5010 - loss: 0.5392 - mae: 0.5465 - rmse: 0.6905 - smape: 1.1059 - val_ia: 0.2000 - val_loss: 0.8917 - val_mae: 0.6750 - val_rmse: 0.7291 - val_smape: 1.3151

Epoch 11/128

3830/3830 - 42s - 11ms/step - ia: 0.5033 - loss: 0.5276 - mae: 0.5427 - rmse: 0.6834 - smape: 1.1056 - val_ia: 0.2020 - val_loss: 0.9842 - val_mae: 0.6891 - val_rmse: 0.7521 - val_smape: 1.2238

Epoch 12/128

3830/3830 - 31s - 8ms/step - ia: 0.5084 - loss: 0.5130 - mae: 0.5348 - rmse: 0.6748 - smape: 1.0903 - val_ia: 0.2011 - val_loss: 1.0117 - val_mae: 0.6878 - val_rmse: 0.7473 - val_smape: 1.2563

Epoch 13/128

3830/3830 - 52s - 13ms/step - ia: 0.5151 - loss: 0.5063 - mae: 0.5327 - rmse: 0.6710 - smape: 1.0925 - val_ia: 0.2032 - val_loss: 1.0260 - val_mae: 0.6864 - val_rmse: 0.7474 - val_smape: 1.2322

Epoch 14/128

3830/3830 - 43s - 11ms/step - ia: 0.5194 - loss: 0.4922 - mae: 0.5243 - rmse: 0.6603 - smape: 1.0754 - val_ia: 0.1960 - val_loss: 1.0061 - val_mae: 0.7088 - val_rmse: 0.7688 - val_smape: 1.2962

Epoch 15/128

3830/3830 - 42s - 11ms/step - ia: 0.5246 - loss: 0.4844 - mae: 0.5202 - rmse: 0.6570 - smape: 1.0652 - val_ia: 0.1964 - val_loss: 0.9482 - val_mae: 0.6938 - val_rmse: 0.7504 - val_smape: 1.2748

Epoch 16/128

3830/3830 - 35s - 9ms/step - ia: 0.5250 - loss: 0.4842 - mae: 0.5215 - rmse: 0.6569 - smape: 1.0710 - val_ia: 0.1978 - val_loss: 1.0690 - val_mae: 0.7122 - val_rmse: 0.7758 - val_smape: 1.2818

Epoch 17/128

3830/3830 - 37s - 10ms/step - ia: 0.5264 - loss: 0.4757 - mae: 0.5172 - rmse: 0.6500 - smape: 1.0671 - val_ia: 0.2003 - val_loss: 0.9815 - val_mae: 0.6906 - val_rmse: 0.7533 - val_smape: 1.2705

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 2.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step
  8/136 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
 15/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step

 67%|██████▋   | 8/12 [2:50:45<56:53, 853.41s/trial, best loss: 0.7654894358534513]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 7s - 29ms/step - ia: 0.2787 - loss: 1.0508 - mae: 0.7550 - rmse: 1.0121 - smape: 1.4570 - val_ia: 0.3025 - val_loss: 0.7840 - val_mae: 0.6550 - val_rmse: 0.7997 - val_smape: 1.3142

Epoch 2/128

240/240 - 2s - 8ms/step - ia: 0.3551 - loss: 0.8510 - mae: 0.6839 - rmse: 0.9186 - smape: 1.3480 - val_ia: 0.3116 - val_loss: 0.7716 - val_mae: 0.6552 - val_rmse: 0.7984 - val_smape: 1.3284

Epoch 3/128

240/240 - 1s - 6ms/step - ia: 0.3657 - loss: 0.8362 - mae: 0.6747 - rmse: 0.9090 - smape: 1.3269 - val_ia: 0.3109 - val_loss: 0.7545 - val_mae: 0.6443 - val_rmse: 0.7865 - val_smape: 1.2943

Epoch 4/128

240/240 - 3s - 11ms/step - ia: 0.3758 - loss: 0.8238 - mae: 0.6697 - rmse: 0.9020 - smape: 1.3134 - val_ia: 0.3187 - val_loss: 0.7513 - val_mae: 0.6415 - val_rmse: 0.7849 - val_smape: 1.2964

Epoch 5/128

240/240 - 1s - 6ms/step - ia: 0.3790 - loss: 0.8138 - mae: 0.6649 - rmse: 0.8983 - smape: 1.3092 - val_ia: 0.3290 - val_loss: 0.7534 - val_mae: 0.6451 - val_rmse: 0.7918 - val_smape: 1.2837

Epoch 6/128

240/240 - 1s - 6ms/step - ia: 0.3855 - loss: 0.8110 - mae: 0.6624 - rmse: 0.8956 - smape: 1.2984 - val_ia: 0.3252 - val_loss: 0.7496 - val_mae: 0.6433 - val_rmse: 0.7879 - val_smape: 1.2998

Epoch 7/128

240/240 - 1s - 6ms/step - ia: 0.3913 - loss: 0.8045 - mae: 0.6581 - rmse: 0.8920 - smape: 1.2894 - val_ia: 0.3273 - val_loss: 0.7522 - val_mae: 0.6435 - val_rmse: 0.7895 - val_smape: 1.2836

Epoch 8/128

240/240 - 1s - 5ms/step - ia: 0.3898 - loss: 0.8040 - mae: 0.6587 - rmse: 0.8914 - smape: 1.2925 - val_ia: 0.3324 - val_loss: 0.7634 - val_mae: 0.6429 - val_rmse: 0.7935 - val_smape: 1.2749

Epoch 9/128

240/240 - 1s - 5ms/step - ia: 0.3956 - loss: 0.7975 - mae: 0.6551 - rmse: 0.8883 - smape: 1.2823 - val_ia: 0.3290 - val_loss: 0.7601 - val_mae: 0.6481 - val_rmse: 0.7951 - val_smape: 1.2918

Epoch 10/128

240/240 - 1s - 5ms/step - ia: 0.3959 - loss: 0.7961 - mae: 0.6551 - rmse: 0.8871 - smape: 1.2855 - val_ia: 0.3342 - val_loss: 0.7571 - val_mae: 0.6449 - val_rmse: 0.7933 - val_smape: 1.2700

Epoch 11/128

240/240 - 1s - 6ms/step - ia: 0.4012 - loss: 0.7874 - mae: 0.6520 - rmse: 0.8820 - smape: 1.2774 - val_ia: 0.3342 - val_loss: 0.7701 - val_mae: 0.6483 - val_rmse: 0.7991 - val_smape: 1.2733

Epoch 12/128

240/240 - 1s - 6ms/step - ia: 0.4007 - loss: 0.7937 - mae: 0.6519 - rmse: 0.8856 - smape: 1.2728 - val_ia: 0.3282 - val_loss: 0.7560 - val_mae: 0.6433 - val_rmse: 0.7896 - val_smape: 1.2813

Epoch 13/128

240/240 - 1s - 6ms/step - ia: 0.4026 - loss: 0.7880 - mae: 0.6513 - rmse: 0.8820 - smape: 1.2741 - val_ia: 0.3261 - val_loss: 0.7614 - val_mae: 0.6475 - val_rmse: 0.7923 - val_smape: 1.3104

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.4019 - loss: 0.7910 - mae: 0.6507 - rmse: 0.8835 - smape: 1.2714 - val_ia: 0.3304 - val_loss: 0.7644 - val_mae: 0.6443 - val_rmse: 0.7931 - val_smape: 1.2610

Epoch 15/128

240/240 - 1s - 6ms/step - ia: 0.4058 - loss: 0.7834 - mae: 0.6480 - rmse: 0.8807 - smape: 1.2666 - val_ia: 0.3344 - val_loss: 0.7609 - val_mae: 0.6454 - val_rmse: 0.7937 - val_smape: 1.2786

Epoch 16/128

240/240 - 1s - 6ms/step - ia: 0.4066 - loss: 0.7797 - mae: 0.6483 - rmse: 0.8786 - smape: 1.2666 - val_ia: 0.3370 - val_loss: 0.7842 - val_mae: 0.6538 - val_rmse: 0.8073 - val_smape: 1.2729

Epoch 17/128

240/240 - 1s - 6ms/step - ia: 0.4080 - loss: 0.7818 - mae: 0.6479 - rmse: 0.8788 - smape: 1.2621 - val_ia: 0.3382 - val_loss: 0.7625 - val_mae: 0.6418 - val_rmse: 0.7931 - val_smape: 1.2527

Epoch 18/128

240/240 - 1s - 6ms/step - ia: 0.4091 - loss: 0.7798 - mae: 0.6471 - rmse: 0.8779 - smape: 1.2624 - val_ia: 0.3393 - val_loss: 0.7731 - val_mae: 0.6445 - val_rmse: 0.7972 - val_smape: 1.2472

Epoch 19/128

240/240 - 1s - 5ms/step - ia: 0.4094 - loss: 0.7774 - mae: 0.6469 - rmse: 0.8773 - smape: 1.2637 - val_ia: 0.3373 - val_loss: 0.7634 - val_mae: 0.6437 - val_rmse: 0.7947 - val_smape: 1.2599

Epoch 20/128

240/240 - 1s - 5ms/step - ia: 0.4090 - loss: 0.7781 - mae: 0.6464 - rmse: 0.8766 - smape: 1.2621 - val_ia: 0.3403 - val_loss: 0.7876 - val_mae: 0.6511 - val_rmse: 0.8059 - val_smape: 1.2521

Epoch 21/128

240/240 - 3s - 11ms/step - ia: 0.4121 - loss: 0.7735 - mae: 0.6452 - rmse: 0.8738 - smape: 1.2603 - val_ia: 0.3356 - val_loss: 0.7745 - val_mae: 0.6480 - val_rmse: 0.7992 - val_smape: 1.2818

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 6.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 47s 349ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
109/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 75%|███████▌  | 9/12 [2:51:23<29:55, 598.54s/trial, best loss: 0.7654894358534513]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 38s - 20ms/step - ia: 0.2838 - loss: 1.0916 - mae: 0.7850 - rmse: 1.0075 - smape: 1.4587 - val_ia: 0.2238 - val_loss: 0.8466 - val_mae: 0.6956 - val_rmse: 0.7546 - val_smape: 1.5568

Epoch 2/128

1915/1915 - 24s - 13ms/step - ia: 0.3345 - loss: 0.9029 - mae: 0.7081 - rmse: 0.9174 - smape: 1.3730 - val_ia: 0.2404 - val_loss: 0.7842 - val_mae: 0.6588 - val_rmse: 0.7236 - val_smape: 1.3382

Epoch 3/128

1915/1915 - 24s - 12ms/step - ia: 0.3620 - loss: 0.8604 - mae: 0.6870 - rmse: 0.8963 - smape: 1.3222 - val_ia: 0.2399 - val_loss: 0.7815 - val_mae: 0.6618 - val_rmse: 0.7271 - val_smape: 1.3362

Epoch 4/128

1915/1915 - 41s - 21ms/step - ia: 0.3637 - loss: 0.8529 - mae: 0.6837 - rmse: 0.8911 - smape: 1.3175 - val_ia: 0.2453 - val_loss: 0.7706 - val_mae: 0.6437 - val_rmse: 0.7102 - val_smape: 1.2689

Epoch 5/128

1915/1915 - 19s - 10ms/step - ia: 0.3708 - loss: 0.8388 - mae: 0.6764 - rmse: 0.8828 - smape: 1.3036 - val_ia: 0.2445 - val_loss: 0.7702 - val_mae: 0.6441 - val_rmse: 0.7101 - val_smape: 1.2771

Epoch 6/128

1915/1915 - 17s - 9ms/step - ia: 0.3720 - loss: 0.8347 - mae: 0.6743 - rmse: 0.8815 - smape: 1.3019 - val_ia: 0.2443 - val_loss: 0.7674 - val_mae: 0.6490 - val_rmse: 0.7170 - val_smape: 1.2753

Epoch 7/128

1915/1915 - 22s - 11ms/step - ia: 0.3768 - loss: 0.8293 - mae: 0.6720 - rmse: 0.8785 - smape: 1.2922 - val_ia: 0.2425 - val_loss: 0.7698 - val_mae: 0.6545 - val_rmse: 0.7218 - val_smape: 1.2965

Epoch 8/128

1915/1915 - 25s - 13ms/step - ia: 0.3753 - loss: 0.8302 - mae: 0.6721 - rmse: 0.8784 - smape: 1.2943 - val_ia: 0.2457 - val_loss: 0.7635 - val_mae: 0.6393 - val_rmse: 0.7069 - val_smape: 1.2508

Epoch 9/128

1915/1915 - 40s - 21ms/step - ia: 0.3792 - loss: 0.8239 - mae: 0.6689 - rmse: 0.8751 - smape: 1.2862 - val_ia: 0.2426 - val_loss: 0.7678 - val_mae: 0.6550 - val_rmse: 0.7224 - val_smape: 1.2971

Epoch 10/128

1915/1915 - 23s - 12ms/step - ia: 0.3817 - loss: 0.8223 - mae: 0.6681 - rmse: 0.8739 - smape: 1.2858 - val_ia: 0.2446 - val_loss: 0.7619 - val_mae: 0.6432 - val_rmse: 0.7108 - val_smape: 1.2651

Epoch 11/128

1915/1915 - 24s - 12ms/step - ia: 0.3823 - loss: 0.8203 - mae: 0.6672 - rmse: 0.8741 - smape: 1.2838 - val_ia: 0.2450 - val_loss: 0.7654 - val_mae: 0.6336 - val_rmse: 0.6999 - val_smape: 1.2400

Epoch 12/128

1915/1915 - 39s - 20ms/step - ia: 0.3795 - loss: 0.8182 - mae: 0.6667 - rmse: 0.8727 - smape: 1.2850 - val_ia: 0.2444 - val_loss: 0.7626 - val_mae: 0.6462 - val_rmse: 0.7145 - val_smape: 1.2706

Epoch 13/128

1915/1915 - 24s - 12ms/step - ia: 0.3844 - loss: 0.8187 - mae: 0.6654 - rmse: 0.8732 - smape: 1.2797 - val_ia: 0.2440 - val_loss: 0.7617 - val_mae: 0.6471 - val_rmse: 0.7146 - val_smape: 1.2809

Epoch 14/128

1915/1915 - 24s - 13ms/step - ia: 0.3863 - loss: 0.8157 - mae: 0.6644 - rmse: 0.8710 - smape: 1.2781 - val_ia: 0.2451 - val_loss: 0.7574 - val_mae: 0.6407 - val_rmse: 0.7078 - val_smape: 1.2690

Epoch 15/128

1915/1915 - 39s - 21ms/step - ia: 0.3860 - loss: 0.8173 - mae: 0.6645 - rmse: 0.8714 - smape: 1.2787 - val_ia: 0.2444 - val_loss: 0.7592 - val_mae: 0.6451 - val_rmse: 0.7120 - val_smape: 1.2815

Epoch 16/128

1915/1915 - 23s - 12ms/step - ia: 0.3848 - loss: 0.8152 - mae: 0.6642 - rmse: 0.8709 - smape: 1.2784 - val_ia: 0.2474 - val_loss: 0.7578 - val_mae: 0.6373 - val_rmse: 0.7070 - val_smape: 1.2304

Epoch 17/128

1915/1915 - 25s - 13ms/step - ia: 0.3886 - loss: 0.8132 - mae: 0.6629 - rmse: 0.8696 - smape: 1.2750 - val_ia: 0.2460 - val_loss: 0.7593 - val_mae: 0.6413 - val_rmse: 0.7104 - val_smape: 1.2505

Epoch 18/128

1915/1915 - 23s - 12ms/step - ia: 0.3883 - loss: 0.8142 - mae: 0.6622 - rmse: 0.8709 - smape: 1.2731 - val_ia: 0.2468 - val_loss: 0.7600 - val_mae: 0.6403 - val_rmse: 0.7105 - val_smape: 1.2360

Epoch 19/128

1915/1915 - 21s - 11ms/step - ia: 0.3900 - loss: 0.8097 - mae: 0.6615 - rmse: 0.8667 - smape: 1.2721 - val_ia: 0.2460 - val_loss: 0.7609 - val_mae: 0.6456 - val_rmse: 0.7151 - val_smape: 1.2550

Epoch 20/128

1915/1915 - 25s - 13ms/step - ia: 0.3916 - loss: 0.8083 - mae: 0.6612 - rmse: 0.8676 - smape: 1.2674 - val_ia: 0.2482 - val_loss: 0.7549 - val_mae: 0.6318 - val_rmse: 0.7013 - val_smape: 1.2231

Epoch 21/128

1915/1915 - 21s - 11ms/step - ia: 0.3914 - loss: 0.8093 - mae: 0.6607 - rmse: 0.8684 - smape: 1.2690 - val_ia: 0.2461 - val_loss: 0.7575 - val_mae: 0.6418 - val_rmse: 0.7104 - val_smape: 1.2621

Epoch 22/128

1915/1915 - 26s - 14ms/step - ia: 0.3906 - loss: 0.8073 - mae: 0.6600 - rmse: 0.8678 - smape: 1.2707 - val_ia: 0.2442 - val_loss: 0.7609 - val_mae: 0.6494 - val_rmse: 0.7171 - val_smape: 1.2912

Epoch 23/128

1915/1915 - 26s - 14ms/step - ia: 0.3922 - loss: 0.8079 - mae: 0.6608 - rmse: 0.8670 - smape: 1.2730 - val_ia: 0.2460 - val_loss: 0.7581 - val_mae: 0.6412 - val_rmse: 0.7106 - val_smape: 1.2532

Epoch 24/128

1915/1915 - 37s - 19ms/step - ia: 0.3926 - loss: 0.8077 - mae: 0.6597 - rmse: 0.8673 - smape: 1.2691 - val_ia: 0.2460 - val_loss: 0.7557 - val_mae: 0.6399 - val_rmse: 0.7078 - val_smape: 1.2624

Epoch 25/128

1915/1915 - 24s - 12ms/step - ia: 0.3924 - loss: 0.8058 - mae: 0.6596 - rmse: 0.8646 - smape: 1.2700 - val_ia: 0.2475 - val_loss: 0.7537 - val_mae: 0.6366 - val_rmse: 0.7052 - val_smape: 1.2481

Epoch 26/128

1915/1915 - 26s - 14ms/step - ia: 0.3925 - loss: 0.8049 - mae: 0.6587 - rmse: 0.8662 - smape: 1.2654 - val_ia: 0.2460 - val_loss: 0.7552 - val_mae: 0.6382 - val_rmse: 0.7060 - val_smape: 1.2637

Epoch 27/128

1915/1915 - 26s - 14ms/step - ia: 0.3937 - loss: 0.8056 - mae: 0.6583 - rmse: 0.8660 - smape: 1.2657 - val_ia: 0.2466 - val_loss: 0.7543 - val_mae: 0.6373 - val_rmse: 0.7055 - val_smape: 1.2561

Epoch 28/128

1915/1915 - 26s - 14ms/step - ia: 0.3941 - loss: 0.8043 - mae: 0.6578 - rmse: 0.8645 - smape: 1.2643 - val_ia: 0.2434 - val_loss: 0.7662 - val_mae: 0.6533 - val_rmse: 0.7218 - val_smape: 1.2892

Epoch 29/128

1915/1915 - 26s - 14ms/step - ia: 0.3962 - loss: 0.8028 - mae: 0.6586 - rmse: 0.8643 - smape: 1.2660 - val_ia: 0.2469 - val_loss: 0.7544 - val_mae: 0.6385 - val_rmse: 0.7075 - val_smape: 1.2559

Epoch 30/128

1915/1915 - 20s - 11ms/step - ia: 0.3961 - loss: 0.8013 - mae: 0.6564 - rmse: 0.8628 - smape: 1.2629 - val_ia: 0.2457 - val_loss: 0.7586 - val_mae: 0.6428 - val_rmse: 0.7121 - val_smape: 1.2639

Epoch 31/128

1915/1915 - 26s - 14ms/step - ia: 0.3963 - loss: 0.7995 - mae: 0.6571 - rmse: 0.8631 - smape: 1.2680 - val_ia: 0.2457 - val_loss: 0.7525 - val_mae: 0.6386 - val_rmse: 0.7060 - val_smape: 1.2734

Epoch 32/128

1915/1915 - 26s - 14ms/step - ia: 0.3993 - loss: 0.7987 - mae: 0.6557 - rmse: 0.8611 - smape: 1.2600 - val_ia: 0.2470 - val_loss: 0.7524 - val_mae: 0.6375 - val_rmse: 0.7058 - val_smape: 1.2599

Epoch 33/128

1915/1915 - 20s - 10ms/step - ia: 0.3976 - loss: 0.7992 - mae: 0.6558 - rmse: 0.8609 - smape: 1.2623 - val_ia: 0.2461 - val_loss: 0.7560 - val_mae: 0.6419 - val_rmse: 0.7106 - val_smape: 1.2658

Epoch 34/128

1915/1915 - 26s - 14ms/step - ia: 0.4002 - loss: 0.7983 - mae: 0.6552 - rmse: 0.8618 - smape: 1.2589 - val_ia: 0.2466 - val_loss: 0.7588 - val_mae: 0.6421 - val_rmse: 0.7124 - val_smape: 1.2508

Epoch 35/128

1915/1915 - 27s - 14ms/step - ia: 0.4026 - loss: 0.7961 - mae: 0.6541 - rmse: 0.8596 - smape: 1.2555 - val_ia: 0.2494 - val_loss: 0.7491 - val_mae: 0.6300 - val_rmse: 0.6986 - val_smape: 1.2360

Epoch 36/128

1915/1915 - 27s - 14ms/step - ia: 0.4005 - loss: 0.7963 - mae: 0.6537 - rmse: 0.8594 - smape: 1.2579 - val_ia: 0.2451 - val_loss: 0.7598 - val_mae: 0.6463 - val_rmse: 0.7157 - val_smape: 1.2702

Epoch 37/128

1915/1915 - 26s - 14ms/step - ia: 0.4015 - loss: 0.7937 - mae: 0.6535 - rmse: 0.8585 - smape: 1.2587 - val_ia: 0.2470 - val_loss: 0.7548 - val_mae: 0.6401 - val_rmse: 0.7098 - val_smape: 1.2560

Epoch 38/128

1915/1915 - 26s - 14ms/step - ia: 0.4022 - loss: 0.7928 - mae: 0.6535 - rmse: 0.8583 - smape: 1.2588 - val_ia: 0.2484 - val_loss: 0.7481 - val_mae: 0.6334 - val_rmse: 0.7021 - val_smape: 1.2576

Epoch 39/128

1915/1915 - 21s - 11ms/step - ia: 0.4022 - loss: 0.7919 - mae: 0.6525 - rmse: 0.8579 - smape: 1.2601 - val_ia: 0.2491 - val_loss: 0.7516 - val_mae: 0.6342 - val_rmse: 0.7044 - val_smape: 1.2387

Epoch 40/128

1915/1915 - 25s - 13ms/step - ia: 0.4030 - loss: 0.7901 - mae: 0.6515 - rmse: 0.8570 - smape: 1.2569 - val_ia: 0.2481 - val_loss: 0.7549 - val_mae: 0.6374 - val_rmse: 0.7076 - val_smape: 1.2434

Epoch 41/128

1915/1915 - 42s - 22ms/step - ia: 0.4056 - loss: 0.7889 - mae: 0.6517 - rmse: 0.8559 - smape: 1.2564 - val_ia: 0.2495 - val_loss: 0.7456 - val_mae: 0.6285 - val_rmse: 0.6964 - val_smape: 1.2505

Epoch 42/128

1915/1915 - 26s - 14ms/step - ia: 0.4030 - loss: 0.7896 - mae: 0.6511 - rmse: 0.8563 - smape: 1.2574 - val_ia: 0.2473 - val_loss: 0.7484 - val_mae: 0.6354 - val_rmse: 0.7041 - val_smape: 1.2631

Epoch 43/128

1915/1915 - 41s - 22ms/step - ia: 0.4047 - loss: 0.7892 - mae: 0.6515 - rmse: 0.8559 - smape: 1.2588 - val_ia: 0.2475 - val_loss: 0.7517 - val_mae: 0.6378 - val_rmse: 0.7076 - val_smape: 1.2520

Epoch 44/128

1915/1915 - 41s - 21ms/step - ia: 0.4056 - loss: 0.7854 - mae: 0.6494 - rmse: 0.8547 - smape: 1.2539 - val_ia: 0.2482 - val_loss: 0.7541 - val_mae: 0.6372 - val_rmse: 0.7078 - val_smape: 1.2384

Epoch 45/128

1915/1915 - 25s - 13ms/step - ia: 0.4050 - loss: 0.7875 - mae: 0.6500 - rmse: 0.8543 - smape: 1.2523 - val_ia: 0.2480 - val_loss: 0.7481 - val_mae: 0.6353 - val_rmse: 0.7047 - val_smape: 1.2554

Epoch 46/128

1915/1915 - 40s - 21ms/step - ia: 0.4062 - loss: 0.7867 - mae: 0.6494 - rmse: 0.8547 - smape: 1.2523 - val_ia: 0.2471 - val_loss: 0.7536 - val_mae: 0.6389 - val_rmse: 0.7089 - val_smape: 1.2585

Epoch 47/128

1915/1915 - 20s - 10ms/step - ia: 0.4090 - loss: 0.7825 - mae: 0.6480 - rmse: 0.8535 - smape: 1.2520 - val_ia: 0.2467 - val_loss: 0.7613 - val_mae: 0.6415 - val_rmse: 0.7121 - val_smape: 1.2456

Epoch 48/128

1915/1915 - 26s - 14ms/step - ia: 0.4098 - loss: 0.7806 - mae: 0.6470 - rmse: 0.8516 - smape: 1.2466 - val_ia: 0.2519 - val_loss: 0.7515 - val_mae: 0.6275 - val_rmse: 0.6985 - val_smape: 1.2158

Epoch 49/128

1915/1915 - 26s - 14ms/step - ia: 0.4093 - loss: 0.7796 - mae: 0.6463 - rmse: 0.8511 - smape: 1.2503 - val_ia: 0.2484 - val_loss: 0.7471 - val_mae: 0.6343 - val_rmse: 0.7041 - val_smape: 1.2501

Epoch 50/128

1915/1915 - 20s - 11ms/step - ia: 0.4110 - loss: 0.7785 - mae: 0.6464 - rmse: 0.8496 - smape: 1.2482 - val_ia: 0.2482 - val_loss: 0.7501 - val_mae: 0.6375 - val_rmse: 0.7072 - val_smape: 1.2540

Epoch 51/128

1915/1915 - 26s - 14ms/step - ia: 0.4117 - loss: 0.7774 - mae: 0.6454 - rmse: 0.8502 - smape: 1.2473 - val_ia: 0.2493 - val_loss: 0.7526 - val_mae: 0.6359 - val_rmse: 0.7061 - val_smape: 1.2379

Epoch 52/128

1915/1915 - 35s - 18ms/step - ia: 0.4130 - loss: 0.7767 - mae: 0.6452 - rmse: 0.8482 - smape: 1.2443 - val_ia: 0.2517 - val_loss: 0.7464 - val_mae: 0.6284 - val_rmse: 0.6990 - val_smape: 1.2290

Epoch 53/128

1915/1915 - 23s - 12ms/step - ia: 0.4139 - loss: 0.7741 - mae: 0.6441 - rmse: 0.8479 - smape: 1.2466 - val_ia: 0.2493 - val_loss: 0.7518 - val_mae: 0.6332 - val_rmse: 0.7035 - val_smape: 1.2422

Epoch 54/128

1915/1915 - 26s - 14ms/step - ia: 0.4127 - loss: 0.7741 - mae: 0.6442 - rmse: 0.8480 - smape: 1.2475 - val_ia: 0.2478 - val_loss: 0.7886 - val_mae: 0.6472 - val_rmse: 0.7203 - val_smape: 1.2212

Epoch 55/128

1915/1915 - 26s - 14ms/step - ia: 0.4155 - loss: 0.7710 - mae: 0.6420 - rmse: 0.8454 - smape: 1.2411 - val_ia: 0.2502 - val_loss: 0.7690 - val_mae: 0.6376 - val_rmse: 0.7100 - val_smape: 1.2215

Epoch 56/128

1915/1915 - 26s - 14ms/step - ia: 0.4159 - loss: 0.7697 - mae: 0.6417 - rmse: 0.8453 - smape: 1.2418 - val_ia: 0.2486 - val_loss: 0.7415 - val_mae: 0.6314 - val_rmse: 0.7000 - val_smape: 1.2680

Epoch 57/128

1915/1915 - 26s - 14ms/step - ia: 0.4164 - loss: 0.7709 - mae: 0.6417 - rmse: 0.8450 - smape: 1.2432 - val_ia: 0.2472 - val_loss: 0.7779 - val_mae: 0.6460 - val_rmse: 0.7180 - val_smape: 1.2416

Epoch 58/128

1915/1915 - 35s - 18ms/step - ia: 0.4189 - loss: 0.7673 - mae: 0.6406 - rmse: 0.8439 - smape: 1.2392 - val_ia: 0.2488 - val_loss: 0.7667 - val_mae: 0.6404 - val_rmse: 0.7114 - val_smape: 1.2418

Epoch 59/128

1915/1915 - 23s - 12ms/step - ia: 0.4173 - loss: 0.7682 - mae: 0.6402 - rmse: 0.8450 - smape: 1.2394 - val_ia: 0.2473 - val_loss: 0.7671 - val_mae: 0.6451 - val_rmse: 0.7159 - val_smape: 1.2479

Epoch 60/128

1915/1915 - 26s - 14ms/step - ia: 0.4189 - loss: 0.7671 - mae: 0.6399 - rmse: 0.8419 - smape: 1.2345 - val_ia: 0.2477 - val_loss: 0.7546 - val_mae: 0.6391 - val_rmse: 0.7081 - val_smape: 1.2730

Epoch 61/128

1915/1915 - 26s - 13ms/step - ia: 0.4169 - loss: 0.7663 - mae: 0.6400 - rmse: 0.8418 - smape: 1.2411 - val_ia: 0.2525 - val_loss: 0.7584 - val_mae: 0.6324 - val_rmse: 0.7042 - val_smape: 1.2222

Epoch 62/128

1915/1915 - 26s - 13ms/step - ia: 0.4207 - loss: 0.7642 - mae: 0.6387 - rmse: 0.8419 - smape: 1.2352 - val_ia: 0.2478 - val_loss: 0.7646 - val_mae: 0.6411 - val_rmse: 0.7119 - val_smape: 1.2529

Epoch 63/128

1915/1915 - 21s - 11ms/step - ia: 0.4192 - loss: 0.7625 - mae: 0.6380 - rmse: 0.8419 - smape: 1.2337 - val_ia: 0.2492 - val_loss: 0.7540 - val_mae: 0.6351 - val_rmse: 0.7056 - val_smape: 1.2536

Epoch 64/128

1915/1915 - 27s - 14ms/step - ia: 0.4200 - loss: 0.7645 - mae: 0.6393 - rmse: 0.8412 - smape: 1.2393 - val_ia: 0.2496 - val_loss: 0.7649 - val_mae: 0.6390 - val_rmse: 0.7101 - val_smape: 1.2415

Epoch 65/128

1915/1915 - 40s - 21ms/step - ia: 0.4209 - loss: 0.7633 - mae: 0.6382 - rmse: 0.8410 - smape: 1.2368 - val_ia: 0.2473 - val_loss: 0.7501 - val_mae: 0.6357 - val_rmse: 0.7041 - val_smape: 1.2779

Epoch 66/128

1915/1915 - 26s - 14ms/step - ia: 0.4198 - loss: 0.7633 - mae: 0.6380 - rmse: 0.8414 - smape: 1.2377 - val_ia: 0.2502 - val_loss: 0.7725 - val_mae: 0.6384 - val_rmse: 0.7111 - val_smape: 1.2243

Epoch 67/128

1915/1915 - 23s - 12ms/step - ia: 0.4222 - loss: 0.7607 - mae: 0.6376 - rmse: 0.8400 - smape: 1.2353 - val_ia: 0.2487 - val_loss: 0.7711 - val_mae: 0.6413 - val_rmse: 0.7129 - val_smape: 1.2401

Epoch 68/128

1915/1915 - 23s - 12ms/step - ia: 0.4224 - loss: 0.7590 - mae: 0.6365 - rmse: 0.8385 - smape: 1.2364 - val_ia: 0.2478 - val_loss: 0.7610 - val_mae: 0.6394 - val_rmse: 0.7097 - val_smape: 1.2597

Epoch 69/128

1915/1915 - 26s - 14ms/step - ia: 0.4239 - loss: 0.7596 - mae: 0.6357 - rmse: 0.8393 - smape: 1.2328 - val_ia: 0.2455 - val_loss: 0.7680 - val_mae: 0.6457 - val_rmse: 0.7158 - val_smape: 1.2688

Epoch 70/128

1915/1915 - 23s - 12ms/step - ia: 0.4242 - loss: 0.7572 - mae: 0.6360 - rmse: 0.8379 - smape: 1.2315 - val_ia: 0.2500 - val_loss: 0.7605 - val_mae: 0.6353 - val_rmse: 0.7073 - val_smape: 1.2388

Epoch 71/128

1915/1915 - 24s - 13ms/step - ia: 0.4249 - loss: 0.7586 - mae: 0.6351 - rmse: 0.8385 - smape: 1.2311 - val_ia: 0.2507 - val_loss: 0.7638 - val_mae: 0.6368 - val_rmse: 0.7088 - val_smape: 1.2318

Epoch 71: early stopping

Restoring model weights from the end of the best epoch: 56.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 2:41 1s/step
  4/136 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step
 13/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 22/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 39/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 57/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 80/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 87/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
106/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
122/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
131/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 83%|████████▎ | 10/12 [3:23:22<33:32, 1006.23s/trial, best loss: 0.7654894358534513]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 39s - 10ms/step - ia: 0.2461 - loss: 1.0636 - mae: 0.7918 - rmse: 0.9714 - smape: 1.6345 - val_ia: 0.1797 - val_loss: 1.0009 - val_mae: 0.7695 - val_rmse: 0.8065 - val_smape: 1.7668

Epoch 2/128

3830/3830 - 30s - 8ms/step - ia: 0.2497 - loss: 1.0568 - mae: 0.7872 - rmse: 0.9671 - smape: 1.6329 - val_ia: 0.1805 - val_loss: 0.9945 - val_mae: 0.7646 - val_rmse: 0.8015 - val_smape: 1.7692

Epoch 3/128

3830/3830 - 25s - 7ms/step - ia: 0.2474 - loss: 1.0432 - mae: 0.7816 - rmse: 0.9617 - smape: 1.6348 - val_ia: 0.1809 - val_loss: 0.9890 - val_mae: 0.7604 - val_rmse: 0.7973 - val_smape: 1.7709

Epoch 4/128

3830/3830 - 28s - 7ms/step - ia: 0.2463 - loss: 1.0413 - mae: 0.7799 - rmse: 0.9603 - smape: 1.6432 - val_ia: 0.1812 - val_loss: 0.9840 - val_mae: 0.7566 - val_rmse: 0.7935 - val_smape: 1.7722

Epoch 5/128

3830/3830 - 29s - 8ms/step - ia: 0.2464 - loss: 1.0353 - mae: 0.7739 - rmse: 0.9563 - smape: 1.6398 - val_ia: 0.1813 - val_loss: 0.9795 - val_mae: 0.7532 - val_rmse: 0.7900 - val_smape: 1.7724

Epoch 6/128

3830/3830 - 31s - 8ms/step - ia: 0.2490 - loss: 1.0271 - mae: 0.7707 - rmse: 0.9511 - smape: 1.6424 - val_ia: 0.1815 - val_loss: 0.9755 - val_mae: 0.7504 - val_rmse: 0.7871 - val_smape: 1.7725

Epoch 7/128

3830/3830 - 34s - 9ms/step - ia: 0.2460 - loss: 1.0281 - mae: 0.7698 - rmse: 0.9509 - smape: 1.6440 - val_ia: 0.1820 - val_loss: 0.9718 - val_mae: 0.7476 - val_rmse: 0.7843 - val_smape: 1.7724

Epoch 8/128

3830/3830 - 28s - 7ms/step - ia: 0.2475 - loss: 1.0198 - mae: 0.7647 - rmse: 0.9472 - smape: 1.6439 - val_ia: 0.1824 - val_loss: 0.9685 - val_mae: 0.7452 - val_rmse: 0.7819 - val_smape: 1.7723

Epoch 9/128

3830/3830 - 29s - 8ms/step - ia: 0.2453 - loss: 1.0208 - mae: 0.7650 - rmse: 0.9469 - smape: 1.6467 - val_ia: 0.1828 - val_loss: 0.9653 - val_mae: 0.7430 - val_rmse: 0.7797 - val_smape: 1.7720

Epoch 10/128

3830/3830 - 41s - 11ms/step - ia: 0.2451 - loss: 1.0158 - mae: 0.7629 - rmse: 0.9455 - smape: 1.6475 - val_ia: 0.1832 - val_loss: 0.9624 - val_mae: 0.7410 - val_rmse: 0.7776 - val_smape: 1.7714

Epoch 11/128

3830/3830 - 30s - 8ms/step - ia: 0.2490 - loss: 1.0056 - mae: 0.7575 - rmse: 0.9389 - smape: 1.6447 - val_ia: 0.1835 - val_loss: 0.9596 - val_mae: 0.7391 - val_rmse: 0.7757 - val_smape: 1.7705

Epoch 12/128

3830/3830 - 30s - 8ms/step - ia: 0.2477 - loss: 1.0063 - mae: 0.7578 - rmse: 0.9381 - smape: 1.6488 - val_ia: 0.1838 - val_loss: 0.9570 - val_mae: 0.7375 - val_rmse: 0.7741 - val_smape: 1.7698

Epoch 13/128

3830/3830 - 29s - 8ms/step - ia: 0.2499 - loss: 1.0046 - mae: 0.7548 - rmse: 0.9381 - smape: 1.6444 - val_ia: 0.1842 - val_loss: 0.9544 - val_mae: 0.7359 - val_rmse: 0.7726 - val_smape: 1.7688

Epoch 14/128

3830/3830 - 36s - 10ms/step - ia: 0.2494 - loss: 0.9997 - mae: 0.7547 - rmse: 0.9356 - smape: 1.6492 - val_ia: 0.1846 - val_loss: 0.9521 - val_mae: 0.7345 - val_rmse: 0.7711 - val_smape: 1.7676

Epoch 15/128

3830/3830 - 25s - 7ms/step - ia: 0.2505 - loss: 0.9969 - mae: 0.7524 - rmse: 0.9332 - smape: 1.6500 - val_ia: 0.1849 - val_loss: 0.9498 - val_mae: 0.7332 - val_rmse: 0.7698 - val_smape: 1.7665

Epoch 16/128

3830/3830 - 25s - 7ms/step - ia: 0.2508 - loss: 0.9942 - mae: 0.7495 - rmse: 0.9319 - smape: 1.6461 - val_ia: 0.1852 - val_loss: 0.9478 - val_mae: 0.7321 - val_rmse: 0.7688 - val_smape: 1.7655

Epoch 17/128

3830/3830 - 41s - 11ms/step - ia: 0.2480 - loss: 0.9960 - mae: 0.7515 - rmse: 0.9343 - smape: 1.6518 - val_ia: 0.1854 - val_loss: 0.9455 - val_mae: 0.7309 - val_rmse: 0.7676 - val_smape: 1.7648

Epoch 18/128

3830/3830 - 39s - 10ms/step - ia: 0.2514 - loss: 0.9898 - mae: 0.7479 - rmse: 0.9307 - smape: 1.6507 - val_ia: 0.1856 - val_loss: 0.9435 - val_mae: 0.7299 - val_rmse: 0.7665 - val_smape: 1.7638

Epoch 19/128

3830/3830 - 24s - 6ms/step - ia: 0.2502 - loss: 0.9878 - mae: 0.7471 - rmse: 0.9281 - smape: 1.6538 - val_ia: 0.1858 - val_loss: 0.9414 - val_mae: 0.7289 - val_rmse: 0.7655 - val_smape: 1.7628

Epoch 20/128

3830/3830 - 26s - 7ms/step - ia: 0.2499 - loss: 0.9864 - mae: 0.7472 - rmse: 0.9294 - smape: 1.6539 - val_ia: 0.1861 - val_loss: 0.9396 - val_mae: 0.7279 - val_rmse: 0.7646 - val_smape: 1.7618

Epoch 21/128

3830/3830 - 24s - 6ms/step - ia: 0.2524 - loss: 0.9853 - mae: 0.7462 - rmse: 0.9275 - smape: 1.6531 - val_ia: 0.1863 - val_loss: 0.9377 - val_mae: 0.7270 - val_rmse: 0.7637 - val_smape: 1.7607

Epoch 22/128

3830/3830 - 25s - 6ms/step - ia: 0.2527 - loss: 0.9821 - mae: 0.7443 - rmse: 0.9258 - smape: 1.6521 - val_ia: 0.1865 - val_loss: 0.9359 - val_mae: 0.7263 - val_rmse: 0.7629 - val_smape: 1.7595

Epoch 23/128

3830/3830 - 25s - 7ms/step - ia: 0.2518 - loss: 0.9773 - mae: 0.7435 - rmse: 0.9238 - smape: 1.6548 - val_ia: 0.1867 - val_loss: 0.9343 - val_mae: 0.7256 - val_rmse: 0.7622 - val_smape: 1.7579

Epoch 24/128

3830/3830 - 26s - 7ms/step - ia: 0.2538 - loss: 0.9794 - mae: 0.7437 - rmse: 0.9246 - smape: 1.6539 - val_ia: 0.1869 - val_loss: 0.9325 - val_mae: 0.7248 - val_rmse: 0.7614 - val_smape: 1.7563

Epoch 25/128

3830/3830 - 25s - 7ms/step - ia: 0.2568 - loss: 0.9777 - mae: 0.7408 - rmse: 0.9226 - smape: 1.6517 - val_ia: 0.1871 - val_loss: 0.9309 - val_mae: 0.7240 - val_rmse: 0.7607 - val_smape: 1.7547

Epoch 26/128

3830/3830 - 25s - 7ms/step - ia: 0.2557 - loss: 0.9799 - mae: 0.7416 - rmse: 0.9239 - smape: 1.6504 - val_ia: 0.1872 - val_loss: 0.9293 - val_mae: 0.7234 - val_rmse: 0.7600 - val_smape: 1.7531

Epoch 27/128

3830/3830 - 23s - 6ms/step - ia: 0.2540 - loss: 0.9786 - mae: 0.7411 - rmse: 0.9238 - smape: 1.6520 - val_ia: 0.1873 - val_loss: 0.9279 - val_mae: 0.7228 - val_rmse: 0.7594 - val_smape: 1.7519

Epoch 28/128

3830/3830 - 26s - 7ms/step - ia: 0.2527 - loss: 0.9741 - mae: 0.7406 - rmse: 0.9221 - smape: 1.6557 - val_ia: 0.1874 - val_loss: 0.9264 - val_mae: 0.7222 - val_rmse: 0.7588 - val_smape: 1.7508

Epoch 29/128

3830/3830 - 26s - 7ms/step - ia: 0.2548 - loss: 0.9754 - mae: 0.7400 - rmse: 0.9214 - smape: 1.6498 - val_ia: 0.1875 - val_loss: 0.9250 - val_mae: 0.7217 - val_rmse: 0.7583 - val_smape: 1.7500

Epoch 30/128

3830/3830 - 26s - 7ms/step - ia: 0.2549 - loss: 0.9741 - mae: 0.7401 - rmse: 0.9223 - smape: 1.6546 - val_ia: 0.1877 - val_loss: 0.9235 - val_mae: 0.7211 - val_rmse: 0.7577 - val_smape: 1.7484

Epoch 31/128

3830/3830 - 23s - 6ms/step - ia: 0.2562 - loss: 0.9710 - mae: 0.7388 - rmse: 0.9210 - smape: 1.6541 - val_ia: 0.1878 - val_loss: 0.9220 - val_mae: 0.7206 - val_rmse: 0.7571 - val_smape: 1.7463

Epoch 32/128

3830/3830 - 24s - 6ms/step - ia: 0.2538 - loss: 0.9676 - mae: 0.7388 - rmse: 0.9197 - smape: 1.6573 - val_ia: 0.1879 - val_loss: 0.9207 - val_mae: 0.7201 - val_rmse: 0.7567 - val_smape: 1.7443

Epoch 33/128

3830/3830 - 24s - 6ms/step - ia: 0.2564 - loss: 0.9668 - mae: 0.7373 - rmse: 0.9177 - smape: 1.6529 - val_ia: 0.1880 - val_loss: 0.9193 - val_mae: 0.7196 - val_rmse: 0.7561 - val_smape: 1.7423

Epoch 34/128

3830/3830 - 41s - 11ms/step - ia: 0.2567 - loss: 0.9679 - mae: 0.7375 - rmse: 0.9186 - smape: 1.6549 - val_ia: 0.1881 - val_loss: 0.9179 - val_mae: 0.7190 - val_rmse: 0.7556 - val_smape: 1.7397

Epoch 35/128

3830/3830 - 25s - 7ms/step - ia: 0.2562 - loss: 0.9657 - mae: 0.7378 - rmse: 0.9195 - smape: 1.6575 - val_ia: 0.1882 - val_loss: 0.9166 - val_mae: 0.7186 - val_rmse: 0.7551 - val_smape: 1.7379

Epoch 36/128

3830/3830 - 41s - 11ms/step - ia: 0.2573 - loss: 0.9661 - mae: 0.7361 - rmse: 0.9179 - smape: 1.6528 - val_ia: 0.1883 - val_loss: 0.9154 - val_mae: 0.7182 - val_rmse: 0.7547 - val_smape: 1.7360

Epoch 37/128

3830/3830 - 24s - 6ms/step - ia: 0.2563 - loss: 0.9644 - mae: 0.7355 - rmse: 0.9171 - smape: 1.6526 - val_ia: 0.1884 - val_loss: 0.9142 - val_mae: 0.7178 - val_rmse: 0.7543 - val_smape: 1.7340

Epoch 38/128

3830/3830 - 24s - 6ms/step - ia: 0.2601 - loss: 0.9648 - mae: 0.7353 - rmse: 0.9177 - smape: 1.6529 - val_ia: 0.1884 - val_loss: 0.9130 - val_mae: 0.7173 - val_rmse: 0.7538 - val_smape: 1.7320

Epoch 39/128

3830/3830 - 25s - 7ms/step - ia: 0.2584 - loss: 0.9594 - mae: 0.7348 - rmse: 0.9148 - smape: 1.6529 - val_ia: 0.1885 - val_loss: 0.9117 - val_mae: 0.7169 - val_rmse: 0.7534 - val_smape: 1.7297

Epoch 40/128

3830/3830 - 26s - 7ms/step - ia: 0.2611 - loss: 0.9569 - mae: 0.7329 - rmse: 0.9136 - smape: 1.6516 - val_ia: 0.1885 - val_loss: 0.9105 - val_mae: 0.7165 - val_rmse: 0.7530 - val_smape: 1.7274

Epoch 41/128

3830/3830 - 26s - 7ms/step - ia: 0.2606 - loss: 0.9570 - mae: 0.7334 - rmse: 0.9139 - smape: 1.6531 - val_ia: 0.1886 - val_loss: 0.9093 - val_mae: 0.7161 - val_rmse: 0.7526 - val_smape: 1.7251

Epoch 42/128

3830/3830 - 25s - 7ms/step - ia: 0.2669 - loss: 0.9540 - mae: 0.7315 - rmse: 0.9133 - smape: 1.6439 - val_ia: 0.1887 - val_loss: 0.9081 - val_mae: 0.7156 - val_rmse: 0.7521 - val_smape: 1.7230

Epoch 43/128

3830/3830 - 23s - 6ms/step - ia: 0.2603 - loss: 0.9586 - mae: 0.7339 - rmse: 0.9152 - smape: 1.6476 - val_ia: 0.1887 - val_loss: 0.9071 - val_mae: 0.7152 - val_rmse: 0.7517 - val_smape: 1.7209

Epoch 44/128

3830/3830 - 24s - 6ms/step - ia: 0.2615 - loss: 0.9566 - mae: 0.7328 - rmse: 0.9144 - smape: 1.6530 - val_ia: 0.1888 - val_loss: 0.9059 - val_mae: 0.7148 - val_rmse: 0.7513 - val_smape: 1.7189

Epoch 45/128

3830/3830 - 40s - 11ms/step - ia: 0.2640 - loss: 0.9564 - mae: 0.7320 - rmse: 0.9141 - smape: 1.6465 - val_ia: 0.1889 - val_loss: 0.9048 - val_mae: 0.7144 - val_rmse: 0.7509 - val_smape: 1.7169

Epoch 46/128

3830/3830 - 23s - 6ms/step - ia: 0.2638 - loss: 0.9491 - mae: 0.7306 - rmse: 0.9107 - smape: 1.6430 - val_ia: 0.1889 - val_loss: 0.9037 - val_mae: 0.7140 - val_rmse: 0.7505 - val_smape: 1.7146

Epoch 47/128

3830/3830 - 25s - 6ms/step - ia: 0.2650 - loss: 0.9490 - mae: 0.7302 - rmse: 0.9099 - smape: 1.6429 - val_ia: 0.1889 - val_loss: 0.9025 - val_mae: 0.7136 - val_rmse: 0.7501 - val_smape: 1.7123

Epoch 48/128

3830/3830 - 41s - 11ms/step - ia: 0.2651 - loss: 0.9481 - mae: 0.7286 - rmse: 0.9103 - smape: 1.6404 - val_ia: 0.1890 - val_loss: 0.9014 - val_mae: 0.7133 - val_rmse: 0.7497 - val_smape: 1.7101

Epoch 49/128

3830/3830 - 26s - 7ms/step - ia: 0.2642 - loss: 0.9497 - mae: 0.7302 - rmse: 0.9106 - smape: 1.6433 - val_ia: 0.1890 - val_loss: 0.9004 - val_mae: 0.7129 - val_rmse: 0.7493 - val_smape: 1.7080

Epoch 50/128

3830/3830 - 26s - 7ms/step - ia: 0.2665 - loss: 0.9560 - mae: 0.7313 - rmse: 0.9123 - smape: 1.6451 - val_ia: 0.1890 - val_loss: 0.8996 - val_mae: 0.7125 - val_rmse: 0.7490 - val_smape: 1.7064

Epoch 51/128

3830/3830 - 24s - 6ms/step - ia: 0.2657 - loss: 0.9492 - mae: 0.7290 - rmse: 0.9103 - smape: 1.6386 - val_ia: 0.1891 - val_loss: 0.8987 - val_mae: 0.7122 - val_rmse: 0.7487 - val_smape: 1.7044

Epoch 52/128

3830/3830 - 25s - 6ms/step - ia: 0.2667 - loss: 0.9495 - mae: 0.7295 - rmse: 0.9111 - smape: 1.6437 - val_ia: 0.1891 - val_loss: 0.8977 - val_mae: 0.7119 - val_rmse: 0.7483 - val_smape: 1.7023

Epoch 53/128

3830/3830 - 26s - 7ms/step - ia: 0.2667 - loss: 0.9512 - mae: 0.7290 - rmse: 0.9106 - smape: 1.6382 - val_ia: 0.1891 - val_loss: 0.8969 - val_mae: 0.7115 - val_rmse: 0.7479 - val_smape: 1.7000

Epoch 54/128

3830/3830 - 25s - 7ms/step - ia: 0.2671 - loss: 0.9460 - mae: 0.7280 - rmse: 0.9094 - smape: 1.6325 - val_ia: 0.1892 - val_loss: 0.8961 - val_mae: 0.7111 - val_rmse: 0.7476 - val_smape: 1.6977

Epoch 55/128

3830/3830 - 41s - 11ms/step - ia: 0.2708 - loss: 0.9443 - mae: 0.7270 - rmse: 0.9077 - smape: 1.6347 - val_ia: 0.1892 - val_loss: 0.8952 - val_mae: 0.7107 - val_rmse: 0.7472 - val_smape: 1.6954

Epoch 56/128

3830/3830 - 26s - 7ms/step - ia: 0.2682 - loss: 0.9466 - mae: 0.7291 - rmse: 0.9109 - smape: 1.6357 - val_ia: 0.1892 - val_loss: 0.8944 - val_mae: 0.7105 - val_rmse: 0.7469 - val_smape: 1.6941

Epoch 57/128

3830/3830 - 25s - 7ms/step - ia: 0.2663 - loss: 0.9486 - mae: 0.7294 - rmse: 0.9099 - smape: 1.6380 - val_ia: 0.1893 - val_loss: 0.8938 - val_mae: 0.7103 - val_rmse: 0.7467 - val_smape: 1.6924

Epoch 58/128

3830/3830 - 25s - 7ms/step - ia: 0.2676 - loss: 0.9496 - mae: 0.7287 - rmse: 0.9114 - smape: 1.6333 - val_ia: 0.1893 - val_loss: 0.8931 - val_mae: 0.7100 - val_rmse: 0.7465 - val_smape: 1.6910

Epoch 59/128

3830/3830 - 41s - 11ms/step - ia: 0.2683 - loss: 0.9460 - mae: 0.7278 - rmse: 0.9074 - smape: 1.6343 - val_ia: 0.1893 - val_loss: 0.8924 - val_mae: 0.7097 - val_rmse: 0.7462 - val_smape: 1.6891

Epoch 60/128

3830/3830 - 39s - 10ms/step - ia: 0.2679 - loss: 0.9483 - mae: 0.7275 - rmse: 0.9101 - smape: 1.6349 - val_ia: 0.1893 - val_loss: 0.8918 - val_mae: 0.7095 - val_rmse: 0.7459 - val_smape: 1.6875

Epoch 61/128

3830/3830 - 24s - 6ms/step - ia: 0.2703 - loss: 0.9405 - mae: 0.7263 - rmse: 0.9077 - smape: 1.6318 - val_ia: 0.1893 - val_loss: 0.8910 - val_mae: 0.7093 - val_rmse: 0.7457 - val_smape: 1.6859

Epoch 62/128

3830/3830 - 25s - 7ms/step - ia: 0.2736 - loss: 0.9396 - mae: 0.7255 - rmse: 0.9069 - smape: 1.6294 - val_ia: 0.1893 - val_loss: 0.8902 - val_mae: 0.7089 - val_rmse: 0.7454 - val_smape: 1.6837

Epoch 63/128

3830/3830 - 25s - 7ms/step - ia: 0.2718 - loss: 0.9410 - mae: 0.7262 - rmse: 0.9064 - smape: 1.6277 - val_ia: 0.1894 - val_loss: 0.8896 - val_mae: 0.7086 - val_rmse: 0.7450 - val_smape: 1.6817

Epoch 64/128

3830/3830 - 25s - 7ms/step - ia: 0.2720 - loss: 0.9409 - mae: 0.7252 - rmse: 0.9085 - smape: 1.6274 - val_ia: 0.1894 - val_loss: 0.8889 - val_mae: 0.7083 - val_rmse: 0.7447 - val_smape: 1.6798

Epoch 65/128

3830/3830 - 26s - 7ms/step - ia: 0.2723 - loss: 0.9415 - mae: 0.7268 - rmse: 0.9070 - smape: 1.6272 - val_ia: 0.1894 - val_loss: 0.8882 - val_mae: 0.7080 - val_rmse: 0.7444 - val_smape: 1.6778

Epoch 66/128

3830/3830 - 25s - 7ms/step - ia: 0.2714 - loss: 0.9396 - mae: 0.7254 - rmse: 0.9073 - smape: 1.6252 - val_ia: 0.1894 - val_loss: 0.8876 - val_mae: 0.7077 - val_rmse: 0.7441 - val_smape: 1.6759

Epoch 67/128

3830/3830 - 31s - 8ms/step - ia: 0.2725 - loss: 0.9393 - mae: 0.7250 - rmse: 0.9067 - smape: 1.6217 - val_ia: 0.1895 - val_loss: 0.8869 - val_mae: 0.7074 - val_rmse: 0.7438 - val_smape: 1.6742

Epoch 68/128

3830/3830 - 23s - 6ms/step - ia: 0.2711 - loss: 0.9376 - mae: 0.7248 - rmse: 0.9035 - smape: 1.6248 - val_ia: 0.1895 - val_loss: 0.8863 - val_mae: 0.7072 - val_rmse: 0.7436 - val_smape: 1.6723

Epoch 69/128

3830/3830 - 25s - 7ms/step - ia: 0.2744 - loss: 0.9364 - mae: 0.7244 - rmse: 0.9048 - smape: 1.6219 - val_ia: 0.1895 - val_loss: 0.8856 - val_mae: 0.7069 - val_rmse: 0.7433 - val_smape: 1.6702

Epoch 70/128

3830/3830 - 26s - 7ms/step - ia: 0.2763 - loss: 0.9365 - mae: 0.7228 - rmse: 0.9042 - smape: 1.6167 - val_ia: 0.1895 - val_loss: 0.8851 - val_mae: 0.7066 - val_rmse: 0.7430 - val_smape: 1.6684

Epoch 71/128

3830/3830 - 25s - 7ms/step - ia: 0.2732 - loss: 0.9333 - mae: 0.7236 - rmse: 0.9032 - smape: 1.6193 - val_ia: 0.1896 - val_loss: 0.8844 - val_mae: 0.7063 - val_rmse: 0.7427 - val_smape: 1.6662

Epoch 72/128

3830/3830 - 24s - 6ms/step - ia: 0.2746 - loss: 0.9365 - mae: 0.7244 - rmse: 0.9046 - smape: 1.6169 - val_ia: 0.1896 - val_loss: 0.8839 - val_mae: 0.7060 - val_rmse: 0.7424 - val_smape: 1.6646

Epoch 73/128

3830/3830 - 25s - 6ms/step - ia: 0.2755 - loss: 0.9326 - mae: 0.7225 - rmse: 0.9029 - smape: 1.6107 - val_ia: 0.1897 - val_loss: 0.8833 - val_mae: 0.7057 - val_rmse: 0.7421 - val_smape: 1.6624

Epoch 74/128

3830/3830 - 25s - 7ms/step - ia: 0.2760 - loss: 0.9349 - mae: 0.7225 - rmse: 0.9044 - smape: 1.6138 - val_ia: 0.1897 - val_loss: 0.8827 - val_mae: 0.7055 - val_rmse: 0.7419 - val_smape: 1.6609

Epoch 75/128

3830/3830 - 26s - 7ms/step - ia: 0.2751 - loss: 0.9344 - mae: 0.7225 - rmse: 0.9031 - smape: 1.6122 - val_ia: 0.1897 - val_loss: 0.8821 - val_mae: 0.7052 - val_rmse: 0.7416 - val_smape: 1.6585

Epoch 76/128

3830/3830 - 41s - 11ms/step - ia: 0.2810 - loss: 0.9294 - mae: 0.7204 - rmse: 0.9015 - smape: 1.6078 - val_ia: 0.1897 - val_loss: 0.8815 - val_mae: 0.7049 - val_rmse: 0.7413 - val_smape: 1.6566

Epoch 77/128

3830/3830 - 25s - 7ms/step - ia: 0.2792 - loss: 0.9339 - mae: 0.7218 - rmse: 0.9031 - smape: 1.6083 - val_ia: 0.1898 - val_loss: 0.8809 - val_mae: 0.7046 - val_rmse: 0.7410 - val_smape: 1.6546

Epoch 78/128

3830/3830 - 23s - 6ms/step - ia: 0.2802 - loss: 0.9340 - mae: 0.7217 - rmse: 0.9027 - smape: 1.6065 - val_ia: 0.1898 - val_loss: 0.8803 - val_mae: 0.7043 - val_rmse: 0.7407 - val_smape: 1.6524

Epoch 79/128

3830/3830 - 25s - 7ms/step - ia: 0.2801 - loss: 0.9288 - mae: 0.7216 - rmse: 0.9014 - smape: 1.6067 - val_ia: 0.1898 - val_loss: 0.8798 - val_mae: 0.7040 - val_rmse: 0.7404 - val_smape: 1.6504

Epoch 80/128

3830/3830 - 26s - 7ms/step - ia: 0.2813 - loss: 0.9253 - mae: 0.7205 - rmse: 0.9002 - smape: 1.6069 - val_ia: 0.1899 - val_loss: 0.8791 - val_mae: 0.7038 - val_rmse: 0.7402 - val_smape: 1.6484

Epoch 81/128

3830/3830 - 23s - 6ms/step - ia: 0.2775 - loss: 0.9339 - mae: 0.7229 - rmse: 0.9038 - smape: 1.6098 - val_ia: 0.1899 - val_loss: 0.8786 - val_mae: 0.7035 - val_rmse: 0.7399 - val_smape: 1.6465

Epoch 82/128

3830/3830 - 25s - 7ms/step - ia: 0.2780 - loss: 0.9289 - mae: 0.7203 - rmse: 0.9017 - smape: 1.6010 - val_ia: 0.1899 - val_loss: 0.8781 - val_mae: 0.7032 - val_rmse: 0.7396 - val_smape: 1.6445

Epoch 83/128

3830/3830 - 25s - 7ms/step - ia: 0.2799 - loss: 0.9332 - mae: 0.7220 - rmse: 0.9015 - smape: 1.6042 - val_ia: 0.1899 - val_loss: 0.8776 - val_mae: 0.7030 - val_rmse: 0.7394 - val_smape: 1.6427

Epoch 84/128

3830/3830 - 42s - 11ms/step - ia: 0.2807 - loss: 0.9299 - mae: 0.7211 - rmse: 0.9015 - smape: 1.5970 - val_ia: 0.1899 - val_loss: 0.8771 - val_mae: 0.7028 - val_rmse: 0.7392 - val_smape: 1.6414

Epoch 85/128

3830/3830 - 26s - 7ms/step - ia: 0.2809 - loss: 0.9278 - mae: 0.7201 - rmse: 0.9020 - smape: 1.6017 - val_ia: 0.1900 - val_loss: 0.8766 - val_mae: 0.7025 - val_rmse: 0.7390 - val_smape: 1.6395

Epoch 86/128

3830/3830 - 25s - 7ms/step - ia: 0.2838 - loss: 0.9262 - mae: 0.7190 - rmse: 0.8984 - smape: 1.5936 - val_ia: 0.1900 - val_loss: 0.8761 - val_mae: 0.7023 - val_rmse: 0.7387 - val_smape: 1.6376

Epoch 87/128

3830/3830 - 26s - 7ms/step - ia: 0.2831 - loss: 0.9255 - mae: 0.7205 - rmse: 0.9000 - smape: 1.5970 - val_ia: 0.1900 - val_loss: 0.8756 - val_mae: 0.7020 - val_rmse: 0.7384 - val_smape: 1.6356

Epoch 88/128

3830/3830 - 41s - 11ms/step - ia: 0.2817 - loss: 0.9296 - mae: 0.7200 - rmse: 0.9014 - smape: 1.5930 - val_ia: 0.1900 - val_loss: 0.8751 - val_mae: 0.7017 - val_rmse: 0.7382 - val_smape: 1.6337

Epoch 89/128

3830/3830 - 41s - 11ms/step - ia: 0.2852 - loss: 0.9198 - mae: 0.7180 - rmse: 0.8960 - smape: 1.5887 - val_ia: 0.1901 - val_loss: 0.8745 - val_mae: 0.7014 - val_rmse: 0.7379 - val_smape: 1.6314

Epoch 90/128

3830/3830 - 25s - 6ms/step - ia: 0.2833 - loss: 0.9275 - mae: 0.7199 - rmse: 0.9000 - smape: 1.5897 - val_ia: 0.1901 - val_loss: 0.8740 - val_mae: 0.7011 - val_rmse: 0.7376 - val_smape: 1.6294

Epoch 91/128

3830/3830 - 23s - 6ms/step - ia: 0.2861 - loss: 0.9269 - mae: 0.7184 - rmse: 0.9001 - smape: 1.5842 - val_ia: 0.1902 - val_loss: 0.8735 - val_mae: 0.7008 - val_rmse: 0.7373 - val_smape: 1.6274

Epoch 92/128

3830/3830 - 25s - 7ms/step - ia: 0.2856 - loss: 0.9249 - mae: 0.7193 - rmse: 0.8990 - smape: 1.5868 - val_ia: 0.1902 - val_loss: 0.8729 - val_mae: 0.7005 - val_rmse: 0.7370 - val_smape: 1.6253

Epoch 93/128

3830/3830 - 25s - 7ms/step - ia: 0.2869 - loss: 0.9249 - mae: 0.7177 - rmse: 0.8990 - smape: 1.5832 - val_ia: 0.1902 - val_loss: 0.8724 - val_mae: 0.7002 - val_rmse: 0.7367 - val_smape: 1.6234

Epoch 94/128

3830/3830 - 25s - 7ms/step - ia: 0.2846 - loss: 0.9246 - mae: 0.7177 - rmse: 0.8983 - smape: 1.5829 - val_ia: 0.1903 - val_loss: 0.8719 - val_mae: 0.6999 - val_rmse: 0.7364 - val_smape: 1.6212

Epoch 95/128

3830/3830 - 26s - 7ms/step - ia: 0.2871 - loss: 0.9233 - mae: 0.7164 - rmse: 0.8968 - smape: 1.5789 - val_ia: 0.1903 - val_loss: 0.8714 - val_mae: 0.6996 - val_rmse: 0.7361 - val_smape: 1.6190

Epoch 96/128

3830/3830 - 25s - 7ms/step - ia: 0.2892 - loss: 0.9186 - mae: 0.7159 - rmse: 0.8961 - smape: 1.5740 - val_ia: 0.1904 - val_loss: 0.8708 - val_mae: 0.6992 - val_rmse: 0.7357 - val_smape: 1.6168

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 9s - 36ms/step - ia: 0.2966 - loss: 0.9969 - mae: 0.7479 - rmse: 0.9913 - smape: 1.4226 - val_ia: 0.2988 - val_loss: 0.7960 - val_mae: 0.6692 - val_rmse: 0.8077 - val_smape: 1.4012

Epoch 2/128

240/240 - 4s - 16ms/step - ia: 0.3620 - loss: 0.8968 - mae: 0.7057 - rmse: 0.9413 - smape: 1.3279 - val_ia: 0.3157 - val_loss: 0.7703 - val_mae: 0.6431 - val_rmse: 0.7887 - val_smape: 1.2741

Epoch 3/128

240/240 - 4s - 16ms/step - ia: 0.3748 - loss: 0.8716 - mae: 0.6935 - rmse: 0.9285 - smape: 1.3057 - val_ia: 0.3167 - val_loss: 0.7700 - val_mae: 0.6446 - val_rmse: 0.7901 - val_smape: 1.2794

Epoch 4/128

240/240 - 4s - 16ms/step - ia: 0.3766 - loss: 0.8559 - mae: 0.6859 - rmse: 0.9205 - smape: 1.3048 - val_ia: 0.3211 - val_loss: 0.7622 - val_mae: 0.6338 - val_rmse: 0.7815 - val_smape: 1.2372

Epoch 5/128

240/240 - 4s - 16ms/step - ia: 0.3799 - loss: 0.8460 - mae: 0.6794 - rmse: 0.9150 - smape: 1.2948 - val_ia: 0.3235 - val_loss: 0.7610 - val_mae: 0.6342 - val_rmse: 0.7824 - val_smape: 1.2372

Epoch 6/128

240/240 - 3s - 14ms/step - ia: 0.3819 - loss: 0.8376 - mae: 0.6749 - rmse: 0.9106 - smape: 1.2911 - val_ia: 0.3211 - val_loss: 0.7599 - val_mae: 0.6426 - val_rmse: 0.7884 - val_smape: 1.2641

Epoch 7/128

240/240 - 6s - 23ms/step - ia: 0.3863 - loss: 0.8282 - mae: 0.6706 - rmse: 0.9052 - smape: 1.2850 - val_ia: 0.3203 - val_loss: 0.7652 - val_mae: 0.6511 - val_rmse: 0.7960 - val_smape: 1.2896

Epoch 8/128

240/240 - 4s - 16ms/step - ia: 0.3882 - loss: 0.8255 - mae: 0.6695 - rmse: 0.9039 - smape: 1.2831 - val_ia: 0.3217 - val_loss: 0.7535 - val_mae: 0.6351 - val_rmse: 0.7814 - val_smape: 1.2434

Epoch 9/128

240/240 - 4s - 16ms/step - ia: 0.3890 - loss: 0.8228 - mae: 0.6673 - rmse: 0.9011 - smape: 1.2803 - val_ia: 0.3204 - val_loss: 0.7605 - val_mae: 0.6480 - val_rmse: 0.7928 - val_smape: 1.2832

Epoch 10/128

240/240 - 4s - 17ms/step - ia: 0.3879 - loss: 0.8218 - mae: 0.6676 - rmse: 0.9015 - smape: 1.2809 - val_ia: 0.3243 - val_loss: 0.7514 - val_mae: 0.6356 - val_rmse: 0.7823 - val_smape: 1.2440

Epoch 11/128

240/240 - 4s - 16ms/step - ia: 0.3919 - loss: 0.8173 - mae: 0.6655 - rmse: 0.8982 - smape: 1.2776 - val_ia: 0.3220 - val_loss: 0.7525 - val_mae: 0.6380 - val_rmse: 0.7837 - val_smape: 1.2596

Epoch 12/128

240/240 - 4s - 16ms/step - ia: 0.3908 - loss: 0.8167 - mae: 0.6646 - rmse: 0.8980 - smape: 1.2754 - val_ia: 0.3232 - val_loss: 0.7490 - val_mae: 0.6326 - val_rmse: 0.7789 - val_smape: 1.2432

Epoch 13/128

240/240 - 4s - 16ms/step - ia: 0.3931 - loss: 0.8124 - mae: 0.6631 - rmse: 0.8960 - smape: 1.2745 - val_ia: 0.3219 - val_loss: 0.7482 - val_mae: 0.6352 - val_rmse: 0.7806 - val_smape: 1.2524

Epoch 14/128

240/240 - 5s - 21ms/step - ia: 0.3910 - loss: 0.8111 - mae: 0.6626 - rmse: 0.8955 - smape: 1.2773 - val_ia: 0.3287 - val_loss: 0.7480 - val_mae: 0.6345 - val_rmse: 0.7822 - val_smape: 1.2406

Epoch 15/128

240/240 - 4s - 18ms/step - ia: 0.3960 - loss: 0.8097 - mae: 0.6612 - rmse: 0.8946 - smape: 1.2719 - val_ia: 0.3213 - val_loss: 0.7569 - val_mae: 0.6516 - val_rmse: 0.7950 - val_smape: 1.2973

Epoch 16/128

240/240 - 4s - 15ms/step - ia: 0.3977 - loss: 0.8055 - mae: 0.6595 - rmse: 0.8929 - smape: 1.2661 - val_ia: 0.3271 - val_loss: 0.7445 - val_mae: 0.6283 - val_rmse: 0.7755 - val_smape: 1.2298

Epoch 17/128

240/240 - 4s - 16ms/step - ia: 0.3955 - loss: 0.8057 - mae: 0.6593 - rmse: 0.8925 - smape: 1.2732 - val_ia: 0.3325 - val_loss: 0.7431 - val_mae: 0.6288 - val_rmse: 0.7776 - val_smape: 1.2209

Epoch 18/128

240/240 - 4s - 16ms/step - ia: 0.4005 - loss: 0.8023 - mae: 0.6573 - rmse: 0.8907 - smape: 1.2651 - val_ia: 0.3258 - val_loss: 0.7493 - val_mae: 0.6428 - val_rmse: 0.7880 - val_smape: 1.2712

Epoch 19/128

240/240 - 4s - 16ms/step - ia: 0.4009 - loss: 0.8004 - mae: 0.6567 - rmse: 0.8900 - smape: 1.2636 - val_ia: 0.3262 - val_loss: 0.7571 - val_mae: 0.6516 - val_rmse: 0.7967 - val_smape: 1.2896

Epoch 20/128

240/240 - 5s - 21ms/step - ia: 0.4002 - loss: 0.8016 - mae: 0.6578 - rmse: 0.8907 - smape: 1.2668 - val_ia: 0.3291 - val_loss: 0.7455 - val_mae: 0.6381 - val_rmse: 0.7846 - val_smape: 1.2569

Epoch 21/128

240/240 - 4s - 16ms/step - ia: 0.4027 - loss: 0.7992 - mae: 0.6556 - rmse: 0.8891 - smape: 1.2621 - val_ia: 0.3250 - val_loss: 0.7465 - val_mae: 0.6423 - val_rmse: 0.7867 - val_smape: 1.2737

Epoch 22/128

240/240 - 4s - 16ms/step - ia: 0.4045 - loss: 0.7968 - mae: 0.6542 - rmse: 0.8872 - smape: 1.2589 - val_ia: 0.3283 - val_loss: 0.7430 - val_mae: 0.6371 - val_rmse: 0.7829 - val_smape: 1.2593

Epoch 23/128

240/240 - 5s - 21ms/step - ia: 0.4052 - loss: 0.7956 - mae: 0.6539 - rmse: 0.8878 - smape: 1.2560 - val_ia: 0.3257 - val_loss: 0.7416 - val_mae: 0.6374 - val_rmse: 0.7825 - val_smape: 1.2590

Epoch 24/128

240/240 - 4s - 15ms/step - ia: 0.4064 - loss: 0.7933 - mae: 0.6524 - rmse: 0.8855 - smape: 1.2585 - val_ia: 0.3295 - val_loss: 0.7542 - val_mae: 0.6492 - val_rmse: 0.7954 - val_smape: 1.2800

Epoch 25/128

240/240 - 4s - 16ms/step - ia: 0.4091 - loss: 0.7930 - mae: 0.6522 - rmse: 0.8860 - smape: 1.2524 - val_ia: 0.3302 - val_loss: 0.7470 - val_mae: 0.6432 - val_rmse: 0.7892 - val_smape: 1.2706

Epoch 26/128

240/240 - 4s - 16ms/step - ia: 0.4092 - loss: 0.7917 - mae: 0.6521 - rmse: 0.8846 - smape: 1.2528 - val_ia: 0.3364 - val_loss: 0.7373 - val_mae: 0.6271 - val_rmse: 0.7764 - val_smape: 1.2218

Epoch 27/128

240/240 - 5s - 22ms/step - ia: 0.4105 - loss: 0.7881 - mae: 0.6497 - rmse: 0.8829 - smape: 1.2495 - val_ia: 0.3424 - val_loss: 0.7410 - val_mae: 0.6248 - val_rmse: 0.7773 - val_smape: 1.2057

Epoch 28/128

240/240 - 4s - 16ms/step - ia: 0.4114 - loss: 0.7888 - mae: 0.6496 - rmse: 0.8832 - smape: 1.2496 - val_ia: 0.3376 - val_loss: 0.7398 - val_mae: 0.6297 - val_rmse: 0.7799 - val_smape: 1.2214

Epoch 29/128

240/240 - 4s - 16ms/step - ia: 0.4115 - loss: 0.7882 - mae: 0.6502 - rmse: 0.8837 - smape: 1.2489 - val_ia: 0.3403 - val_loss: 0.7488 - val_mae: 0.6346 - val_rmse: 0.7871 - val_smape: 1.2280

Epoch 30/128

240/240 - 4s - 16ms/step - ia: 0.4134 - loss: 0.7856 - mae: 0.6487 - rmse: 0.8815 - smape: 1.2471 - val_ia: 0.3360 - val_loss: 0.7394 - val_mae: 0.6309 - val_rmse: 0.7806 - val_smape: 1.2284

Epoch 31/128

240/240 - 4s - 16ms/step - ia: 0.4151 - loss: 0.7851 - mae: 0.6478 - rmse: 0.8799 - smape: 1.2440 - val_ia: 0.3313 - val_loss: 0.7442 - val_mae: 0.6385 - val_rmse: 0.7862 - val_smape: 1.2611

Epoch 32/128

240/240 - 4s - 16ms/step - ia: 0.4146 - loss: 0.7820 - mae: 0.6468 - rmse: 0.8810 - smape: 1.2441 - val_ia: 0.3356 - val_loss: 0.7491 - val_mae: 0.6404 - val_rmse: 0.7903 - val_smape: 1.2481

Epoch 33/128

240/240 - 4s - 16ms/step - ia: 0.4181 - loss: 0.7820 - mae: 0.6461 - rmse: 0.8800 - smape: 1.2406 - val_ia: 0.3338 - val_loss: 0.7378 - val_mae: 0.6279 - val_rmse: 0.7776 - val_smape: 1.2269

Epoch 34/128

240/240 - 4s - 15ms/step - ia: 0.4164 - loss: 0.7807 - mae: 0.6458 - rmse: 0.8791 - smape: 1.2393 - val_ia: 0.3352 - val_loss: 0.7465 - val_mae: 0.6358 - val_rmse: 0.7862 - val_smape: 1.2464

Epoch 35/128

240/240 - 3s - 13ms/step - ia: 0.4174 - loss: 0.7791 - mae: 0.6450 - rmse: 0.8767 - smape: 1.2396 - val_ia: 0.3386 - val_loss: 0.7409 - val_mae: 0.6306 - val_rmse: 0.7815 - val_smape: 1.2318

Epoch 36/128

240/240 - 4s - 16ms/step - ia: 0.4186 - loss: 0.7789 - mae: 0.6449 - rmse: 0.8777 - smape: 1.2377 - val_ia: 0.3385 - val_loss: 0.7463 - val_mae: 0.6375 - val_rmse: 0.7881 - val_smape: 1.2414

Epoch 37/128

240/240 - 5s - 21ms/step - ia: 0.4196 - loss: 0.7781 - mae: 0.6449 - rmse: 0.8774 - smape: 1.2368 - val_ia: 0.3387 - val_loss: 0.7396 - val_mae: 0.6299 - val_rmse: 0.7807 - val_smape: 1.2279

Epoch 38/128

240/240 - 5s - 22ms/step - ia: 0.4192 - loss: 0.7783 - mae: 0.6441 - rmse: 0.8769 - smape: 1.2370 - val_ia: 0.3446 - val_loss: 0.7425 - val_mae: 0.6276 - val_rmse: 0.7814 - val_smape: 1.2118

Epoch 39/128

240/240 - 5s - 21ms/step - ia: 0.4206 - loss: 0.7746 - mae: 0.6426 - rmse: 0.8758 - smape: 1.2348 - val_ia: 0.3417 - val_loss: 0.7416 - val_mae: 0.6295 - val_rmse: 0.7819 - val_smape: 1.2210

Epoch 40/128

240/240 - 4s - 16ms/step - ia: 0.4222 - loss: 0.7746 - mae: 0.6428 - rmse: 0.8758 - smape: 1.2332 - val_ia: 0.3392 - val_loss: 0.7426 - val_mae: 0.6296 - val_rmse: 0.7817 - val_smape: 1.2216

Epoch 41/128

240/240 - 5s - 21ms/step - ia: 0.4226 - loss: 0.7738 - mae: 0.6425 - rmse: 0.8747 - smape: 1.2328 - val_ia: 0.3368 - val_loss: 0.7432 - val_mae: 0.6381 - val_rmse: 0.7872 - val_smape: 1.2566

Epoch 41: early stopping

Restoring model weights from the end of the best epoch: 26.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 30s 228ms/step
 14/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 30/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 61/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
120/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

100%|██████████| 12/12 [4:25:05<00:00, 1325.48s/trial, best loss: 0.7654894358534513]

In [23]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}