Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [4]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(43800, 6)

In [10]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [15]:
print(datosX[0])

[[ 0.31768099 -1.2140229  -1.26852411  0.32968671 -0.38094383 -0.46404777]
 [ 0.52615226 -1.14430217 -1.26852411  0.32968671 -0.38094383 -0.44657536]
 [ 0.64684616 -0.86541928 -1.34931411  0.42612698 -0.38094383 -0.42910295]
 [ 0.88823396 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.39396181]
 [ 0.41643054 -0.58653639 -1.34931411  0.52256725 -0.38094383 -0.3764894 ]
 [ 0.09823754 -0.58653639 -1.4301041   0.52256725 -0.38094383 -0.35901698]
 [ 0.05434885 -0.58653639 -1.4301041   0.61900753 -0.38094383 -0.32387584]
 [ 0.26282012 -0.58653639 -1.34931411  0.7154478  -0.38094383 -0.2887347 ]
 [ 0.21893143 -0.65625711 -1.4301041   0.7154478  -0.38094383 -0.25359356]
 [ 0.3505975  -0.58653639 -1.34931411  0.81188808 -0.38094383 -0.21845241]
 [ 0.43837488 -0.58653639 -1.34931411  0.90832835 -0.38094383 -0.15700449]
 [ 0.57004095 -0.65625711 -1.34931411  0.90832835 -0.38094383 -0.09555657]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 12, 6)
Las dimensiones de testX son:  (8797, 12, 6)
Las dimensiones de valX son:  (4333, 12, 6)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 14s - 57ms/step - ia: 0.1860 - loss: 1.0906 - mae: 0.8155 - rmse: 1.0399 - smape: 1.6083 - val_ia: 0.2529 - val_loss: 0.9710 - val_mae: 0.7438 - val_rmse: 0.8843 - val_smape: 1.9040

Epoch 2/128

240/240 - 3s - 12ms/step - ia: 0.1706 - loss: 1.0407 - mae: 0.7674 - rmse: 1.0132 - smape: 1.6251 - val_ia: 0.2529 - val_loss: 0.9672 - val_mae: 0.7363 - val_rmse: 0.8782 - val_smape: 1.9842

Epoch 3/128

240/240 - 3s - 12ms/step - ia: 0.1570 - loss: 1.0271 - mae: 0.7604 - rmse: 1.0071 - smape: 1.6438 - val_ia: 0.2529 - val_loss: 0.9663 - val_mae: 0.7362 - val_rmse: 0.8780 - val_smape: 1.9829

Epoch 4/128

240/240 - 3s - 13ms/step - ia: 0.1416 - loss: 1.0194 - mae: 0.7571 - rmse: 1.0021 - smape: 1.6686 - val_ia: 0.2530 - val_loss: 0.9654 - val_mae: 0.7371 - val_rmse: 0.8785 - val_smape: 1.9735

Epoch 5/128

240/240 - 6s - 24ms/step - ia: 0.1324 - loss: 1.0116 - mae: 0.7550 - rmse: 1.0002 - smape: 1.6871 - val_ia: 0.2531 - val_loss: 0.9624 - val_mae: 0.7323 - val_rmse: 0.8745 - val_smape: 1.9114

Epoch 6/128

240/240 - 6s - 23ms/step - ia: 0.1267 - loss: 1.0088 - mae: 0.7527 - rmse: 0.9992 - smape: 1.7005 - val_ia: 0.2534 - val_loss: 0.9616 - val_mae: 0.7361 - val_rmse: 0.8771 - val_smape: 1.9565

Epoch 7/128

240/240 - 4s - 17ms/step - ia: 0.1205 - loss: 1.0050 - mae: 0.7517 - rmse: 0.9976 - smape: 1.7164 - val_ia: 0.2536 - val_loss: 0.9563 - val_mae: 0.7303 - val_rmse: 0.8719 - val_smape: 1.8902

Epoch 8/128

240/240 - 5s - 22ms/step - ia: 0.1237 - loss: 0.9972 - mae: 0.7486 - rmse: 0.9925 - smape: 1.7169 - val_ia: 0.2534 - val_loss: 0.9481 - val_mae: 0.7229 - val_rmse: 0.8652 - val_smape: 1.7974

Epoch 9/128

240/240 - 5s - 22ms/step - ia: 0.1268 - loss: 0.9919 - mae: 0.7448 - rmse: 0.9896 - smape: 1.7033 - val_ia: 0.2554 - val_loss: 0.9366 - val_mae: 0.7220 - val_rmse: 0.8625 - val_smape: 1.7838

Epoch 10/128

240/240 - 5s - 21ms/step - ia: 0.1452 - loss: 0.9755 - mae: 0.7388 - rmse: 0.9817 - smape: 1.6647 - val_ia: 0.2567 - val_loss: 0.9092 - val_mae: 0.7097 - val_rmse: 0.8491 - val_smape: 1.6504

Epoch 11/128

240/240 - 5s - 22ms/step - ia: 0.2027 - loss: 0.9446 - mae: 0.7248 - rmse: 0.9663 - smape: 1.5484 - val_ia: 0.2626 - val_loss: 0.8605 - val_mae: 0.6856 - val_rmse: 0.8251 - val_smape: 1.4406

Epoch 12/128

240/240 - 4s - 16ms/step - ia: 0.2735 - loss: 0.9193 - mae: 0.7099 - rmse: 0.9542 - smape: 1.4183 - val_ia: 0.2739 - val_loss: 0.8360 - val_mae: 0.6718 - val_rmse: 0.8140 - val_smape: 1.3358

Epoch 13/128

240/240 - 5s - 21ms/step - ia: 0.3034 - loss: 0.9059 - mae: 0.7021 - rmse: 0.9461 - smape: 1.3696 - val_ia: 0.2822 - val_loss: 0.8266 - val_mae: 0.6697 - val_rmse: 0.8127 - val_smape: 1.3117

Epoch 14/128

240/240 - 4s - 15ms/step - ia: 0.3134 - loss: 0.9019 - mae: 0.6990 - rmse: 0.9437 - smape: 1.3548 - val_ia: 0.2850 - val_loss: 0.8228 - val_mae: 0.6690 - val_rmse: 0.8123 - val_smape: 1.3023

Epoch 15/128

240/240 - 4s - 15ms/step - ia: 0.3190 - loss: 0.8966 - mae: 0.6980 - rmse: 0.9408 - smape: 1.3489 - val_ia: 0.2834 - val_loss: 0.8193 - val_mae: 0.6651 - val_rmse: 0.8084 - val_smape: 1.2908

Epoch 16/128

240/240 - 5s - 22ms/step - ia: 0.3229 - loss: 0.8925 - mae: 0.6954 - rmse: 0.9400 - smape: 1.3407 - val_ia: 0.2857 - val_loss: 0.8163 - val_mae: 0.6623 - val_rmse: 0.8064 - val_smape: 1.2791

Epoch 17/128

240/240 - 5s - 22ms/step - ia: 0.3267 - loss: 0.8929 - mae: 0.6951 - rmse: 0.9399 - smape: 1.3381 - val_ia: 0.2859 - val_loss: 0.8144 - val_mae: 0.6637 - val_rmse: 0.8067 - val_smape: 1.2873

Epoch 18/128

240/240 - 4s - 16ms/step - ia: 0.3242 - loss: 0.8892 - mae: 0.6951 - rmse: 0.9366 - smape: 1.3449 - val_ia: 0.2862 - val_loss: 0.8106 - val_mae: 0.6598 - val_rmse: 0.8034 - val_smape: 1.2709

Epoch 19/128

240/240 - 4s - 17ms/step - ia: 0.3277 - loss: 0.8854 - mae: 0.6931 - rmse: 0.9350 - smape: 1.3409 - val_ia: 0.2893 - val_loss: 0.8085 - val_mae: 0.6612 - val_rmse: 0.8049 - val_smape: 1.2691

Epoch 20/128

240/240 - 4s - 16ms/step - ia: 0.3318 - loss: 0.8866 - mae: 0.6941 - rmse: 0.9352 - smape: 1.3357 - val_ia: 0.2879 - val_loss: 0.8083 - val_mae: 0.6624 - val_rmse: 0.8050 - val_smape: 1.2796

Epoch 21/128

240/240 - 4s - 15ms/step - ia: 0.3316 - loss: 0.8810 - mae: 0.6919 - rmse: 0.9328 - smape: 1.3329 - val_ia: 0.2891 - val_loss: 0.8054 - val_mae: 0.6604 - val_rmse: 0.8033 - val_smape: 1.2708

Epoch 22/128

240/240 - 5s - 22ms/step - ia: 0.3329 - loss: 0.8815 - mae: 0.6926 - rmse: 0.9343 - smape: 1.3350 - val_ia: 0.2892 - val_loss: 0.8042 - val_mae: 0.6564 - val_rmse: 0.8001 - val_smape: 1.2592

Epoch 23/128

240/240 - 4s - 15ms/step - ia: 0.3340 - loss: 0.8788 - mae: 0.6903 - rmse: 0.9315 - smape: 1.3329 - val_ia: 0.2901 - val_loss: 0.8024 - val_mae: 0.6544 - val_rmse: 0.7986 - val_smape: 1.2514

Epoch 24/128

240/240 - 5s - 21ms/step - ia: 0.3386 - loss: 0.8754 - mae: 0.6890 - rmse: 0.9306 - smape: 1.3267 - val_ia: 0.2920 - val_loss: 0.8013 - val_mae: 0.6566 - val_rmse: 0.8003 - val_smape: 1.2597

Epoch 25/128

240/240 - 4s - 16ms/step - ia: 0.3355 - loss: 0.8800 - mae: 0.6906 - rmse: 0.9319 - smape: 1.3329 - val_ia: 0.2913 - val_loss: 0.8007 - val_mae: 0.6540 - val_rmse: 0.7980 - val_smape: 1.2526

Epoch 26/128

240/240 - 4s - 16ms/step - ia: 0.3373 - loss: 0.8761 - mae: 0.6896 - rmse: 0.9306 - smape: 1.3310 - val_ia: 0.2931 - val_loss: 0.8005 - val_mae: 0.6567 - val_rmse: 0.8003 - val_smape: 1.2640

Epoch 27/128

240/240 - 4s - 15ms/step - ia: 0.3387 - loss: 0.8730 - mae: 0.6872 - rmse: 0.9298 - smape: 1.3280 - val_ia: 0.2948 - val_loss: 0.7982 - val_mae: 0.6544 - val_rmse: 0.7987 - val_smape: 1.2512

Epoch 28/128

240/240 - 5s - 22ms/step - ia: 0.3428 - loss: 0.8722 - mae: 0.6868 - rmse: 0.9275 - smape: 1.3251 - val_ia: 0.2965 - val_loss: 0.7981 - val_mae: 0.6577 - val_rmse: 0.8014 - val_smape: 1.2620

Epoch 29/128

240/240 - 5s - 21ms/step - ia: 0.3390 - loss: 0.8760 - mae: 0.6888 - rmse: 0.9300 - smape: 1.3305 - val_ia: 0.2954 - val_loss: 0.7973 - val_mae: 0.6557 - val_rmse: 0.7995 - val_smape: 1.2586

Epoch 30/128

240/240 - 3s - 14ms/step - ia: 0.3404 - loss: 0.8730 - mae: 0.6885 - rmse: 0.9299 - smape: 1.3312 - val_ia: 0.2949 - val_loss: 0.7966 - val_mae: 0.6548 - val_rmse: 0.7985 - val_smape: 1.2572

Epoch 31/128

240/240 - 3s - 14ms/step - ia: 0.3406 - loss: 0.8711 - mae: 0.6876 - rmse: 0.9275 - smape: 1.3294 - val_ia: 0.2962 - val_loss: 0.7954 - val_mae: 0.6535 - val_rmse: 0.7977 - val_smape: 1.2531

Epoch 32/128

240/240 - 3s - 14ms/step - ia: 0.3417 - loss: 0.8692 - mae: 0.6869 - rmse: 0.9271 - smape: 1.3276 - val_ia: 0.2978 - val_loss: 0.7944 - val_mae: 0.6535 - val_rmse: 0.7980 - val_smape: 1.2489

Epoch 33/128

240/240 - 4s - 17ms/step - ia: 0.3473 - loss: 0.8653 - mae: 0.6863 - rmse: 0.9246 - smape: 1.3252 - val_ia: 0.2975 - val_loss: 0.7940 - val_mae: 0.6544 - val_rmse: 0.7984 - val_smape: 1.2547

Epoch 34/128

240/240 - 6s - 27ms/step - ia: 0.3401 - loss: 0.8693 - mae: 0.6878 - rmse: 0.9262 - smape: 1.3341 - val_ia: 0.2978 - val_loss: 0.7935 - val_mae: 0.6545 - val_rmse: 0.7986 - val_smape: 1.2554

Epoch 35/128

240/240 - 5s - 21ms/step - ia: 0.3447 - loss: 0.8672 - mae: 0.6870 - rmse: 0.9257 - smape: 1.3296 - val_ia: 0.2981 - val_loss: 0.7932 - val_mae: 0.6556 - val_rmse: 0.7993 - val_smape: 1.2614

Epoch 36/128

240/240 - 5s - 22ms/step - ia: 0.3427 - loss: 0.8682 - mae: 0.6868 - rmse: 0.9260 - smape: 1.3286 - val_ia: 0.2976 - val_loss: 0.7921 - val_mae: 0.6535 - val_rmse: 0.7975 - val_smape: 1.2536

Epoch 37/128

240/240 - 5s - 20ms/step - ia: 0.3425 - loss: 0.8667 - mae: 0.6876 - rmse: 0.9255 - smape: 1.3320 - val_ia: 0.2983 - val_loss: 0.7918 - val_mae: 0.6516 - val_rmse: 0.7963 - val_smape: 1.2462

Epoch 38/128

240/240 - 5s - 22ms/step - ia: 0.3450 - loss: 0.8662 - mae: 0.6856 - rmse: 0.9254 - smape: 1.3293 - val_ia: 0.2987 - val_loss: 0.7913 - val_mae: 0.6535 - val_rmse: 0.7975 - val_smape: 1.2574

Epoch 39/128

240/240 - 5s - 20ms/step - ia: 0.3449 - loss: 0.8658 - mae: 0.6862 - rmse: 0.9245 - smape: 1.3289 - val_ia: 0.2997 - val_loss: 0.7900 - val_mae: 0.6502 - val_rmse: 0.7953 - val_smape: 1.2433

Epoch 40/128

240/240 - 7s - 28ms/step - ia: 0.3482 - loss: 0.8619 - mae: 0.6844 - rmse: 0.9227 - smape: 1.3249 - val_ia: 0.3000 - val_loss: 0.7897 - val_mae: 0.6516 - val_rmse: 0.7963 - val_smape: 1.2494

Epoch 41/128

240/240 - 8s - 35ms/step - ia: 0.3459 - loss: 0.8638 - mae: 0.6843 - rmse: 0.9236 - smape: 1.3288 - val_ia: 0.3005 - val_loss: 0.7890 - val_mae: 0.6509 - val_rmse: 0.7958 - val_smape: 1.2475

Epoch 42/128

240/240 - 4s - 18ms/step - ia: 0.3461 - loss: 0.8624 - mae: 0.6849 - rmse: 0.9233 - smape: 1.3283 - val_ia: 0.2990 - val_loss: 0.7881 - val_mae: 0.6515 - val_rmse: 0.7959 - val_smape: 1.2495

Epoch 43/128

240/240 - 4s - 18ms/step - ia: 0.3482 - loss: 0.8584 - mae: 0.6837 - rmse: 0.9203 - smape: 1.3287 - val_ia: 0.2998 - val_loss: 0.7868 - val_mae: 0.6500 - val_rmse: 0.7949 - val_smape: 1.2435

Epoch 44/128

240/240 - 6s - 24ms/step - ia: 0.3504 - loss: 0.8571 - mae: 0.6827 - rmse: 0.9202 - smape: 1.3240 - val_ia: 0.3021 - val_loss: 0.7855 - val_mae: 0.6484 - val_rmse: 0.7942 - val_smape: 1.2329

Epoch 45/128

240/240 - 5s - 19ms/step - ia: 0.3504 - loss: 0.8584 - mae: 0.6832 - rmse: 0.9215 - smape: 1.3258 - val_ia: 0.3004 - val_loss: 0.7860 - val_mae: 0.6507 - val_rmse: 0.7955 - val_smape: 1.2481

Epoch 46/128

240/240 - 5s - 20ms/step - ia: 0.3528 - loss: 0.8533 - mae: 0.6820 - rmse: 0.9179 - smape: 1.3223 - val_ia: 0.3002 - val_loss: 0.7851 - val_mae: 0.6485 - val_rmse: 0.7937 - val_smape: 1.2411

Epoch 47/128

240/240 - 5s - 21ms/step - ia: 0.3464 - loss: 0.8587 - mae: 0.6841 - rmse: 0.9212 - smape: 1.3324 - val_ia: 0.3015 - val_loss: 0.7859 - val_mae: 0.6529 - val_rmse: 0.7973 - val_smape: 1.2572

Epoch 48/128

240/240 - 5s - 19ms/step - ia: 0.3502 - loss: 0.8571 - mae: 0.6834 - rmse: 0.9209 - smape: 1.3271 - val_ia: 0.3004 - val_loss: 0.7839 - val_mae: 0.6486 - val_rmse: 0.7937 - val_smape: 1.2446

Epoch 49/128

240/240 - 5s - 19ms/step - ia: 0.3488 - loss: 0.8560 - mae: 0.6831 - rmse: 0.9207 - smape: 1.3312 - val_ia: 0.3025 - val_loss: 0.7841 - val_mae: 0.6489 - val_rmse: 0.7945 - val_smape: 1.2431

Epoch 50/128

240/240 - 5s - 22ms/step - ia: 0.3515 - loss: 0.8546 - mae: 0.6811 - rmse: 0.9184 - smape: 1.3265 - val_ia: 0.3025 - val_loss: 0.7836 - val_mae: 0.6474 - val_rmse: 0.7933 - val_smape: 1.2399

Epoch 51/128

240/240 - 5s - 19ms/step - ia: 0.3530 - loss: 0.8539 - mae: 0.6798 - rmse: 0.9179 - smape: 1.3244 - val_ia: 0.3031 - val_loss: 0.7831 - val_mae: 0.6475 - val_rmse: 0.7935 - val_smape: 1.2421

Epoch 52/128

240/240 - 5s - 19ms/step - ia: 0.3553 - loss: 0.8484 - mae: 0.6794 - rmse: 0.9169 - smape: 1.3214 - val_ia: 0.3045 - val_loss: 0.7826 - val_mae: 0.6478 - val_rmse: 0.7942 - val_smape: 1.2380

Epoch 53/128

240/240 - 4s - 17ms/step - ia: 0.3567 - loss: 0.8481 - mae: 0.6786 - rmse: 0.9151 - smape: 1.3200 - val_ia: 0.3047 - val_loss: 0.7817 - val_mae: 0.6473 - val_rmse: 0.7938 - val_smape: 1.2372

Epoch 54/128

240/240 - 6s - 26ms/step - ia: 0.3561 - loss: 0.8508 - mae: 0.6801 - rmse: 0.9172 - smape: 1.3228 - val_ia: 0.3042 - val_loss: 0.7828 - val_mae: 0.6516 - val_rmse: 0.7969 - val_smape: 1.2560

Epoch 55/128

240/240 - 5s - 19ms/step - ia: 0.3554 - loss: 0.8503 - mae: 0.6791 - rmse: 0.9172 - smape: 1.3237 - val_ia: 0.3041 - val_loss: 0.7821 - val_mae: 0.6498 - val_rmse: 0.7955 - val_smape: 1.2517

Epoch 56/128

240/240 - 4s - 18ms/step - ia: 0.3525 - loss: 0.8497 - mae: 0.6809 - rmse: 0.9159 - smape: 1.3279 - val_ia: 0.3058 - val_loss: 0.7819 - val_mae: 0.6492 - val_rmse: 0.7957 - val_smape: 1.2430

Epoch 57/128

240/240 - 4s - 19ms/step - ia: 0.3593 - loss: 0.8474 - mae: 0.6783 - rmse: 0.9147 - smape: 1.3194 - val_ia: 0.3064 - val_loss: 0.7812 - val_mae: 0.6481 - val_rmse: 0.7948 - val_smape: 1.2430

Epoch 58/128

240/240 - 5s - 22ms/step - ia: 0.3533 - loss: 0.8527 - mae: 0.6804 - rmse: 0.9176 - smape: 1.3285 - val_ia: 0.3057 - val_loss: 0.7819 - val_mae: 0.6498 - val_rmse: 0.7959 - val_smape: 1.2530

Epoch 59/128

240/240 - 5s - 21ms/step - ia: 0.3551 - loss: 0.8493 - mae: 0.6802 - rmse: 0.9180 - smape: 1.3260 - val_ia: 0.3060 - val_loss: 0.7816 - val_mae: 0.6497 - val_rmse: 0.7959 - val_smape: 1.2524

Epoch 60/128

240/240 - 5s - 22ms/step - ia: 0.3545 - loss: 0.8482 - mae: 0.6790 - rmse: 0.9168 - smape: 1.3264 - val_ia: 0.3076 - val_loss: 0.7810 - val_mae: 0.6479 - val_rmse: 0.7950 - val_smape: 1.2428

Epoch 61/128

240/240 - 5s - 21ms/step - ia: 0.3606 - loss: 0.8481 - mae: 0.6785 - rmse: 0.9142 - smape: 1.3209 - val_ia: 0.3068 - val_loss: 0.7815 - val_mae: 0.6499 - val_rmse: 0.7964 - val_smape: 1.2531

Epoch 62/128

240/240 - 5s - 20ms/step - ia: 0.3547 - loss: 0.8468 - mae: 0.6789 - rmse: 0.9156 - smape: 1.3263 - val_ia: 0.3084 - val_loss: 0.7808 - val_mae: 0.6474 - val_rmse: 0.7950 - val_smape: 1.2393

Epoch 63/128

240/240 - 4s - 15ms/step - ia: 0.3543 - loss: 0.8506 - mae: 0.6798 - rmse: 0.9160 - smape: 1.3287 - val_ia: 0.3071 - val_loss: 0.7799 - val_mae: 0.6460 - val_rmse: 0.7934 - val_smape: 1.2387

Epoch 64/128

240/240 - 5s - 19ms/step - ia: 0.3591 - loss: 0.8417 - mae: 0.6764 - rmse: 0.9124 - smape: 1.3184 - val_ia: 0.3101 - val_loss: 0.7804 - val_mae: 0.6469 - val_rmse: 0.7952 - val_smape: 1.2348

Epoch 65/128

240/240 - 5s - 22ms/step - ia: 0.3626 - loss: 0.8427 - mae: 0.6769 - rmse: 0.9131 - smape: 1.3190 - val_ia: 0.3078 - val_loss: 0.7791 - val_mae: 0.6449 - val_rmse: 0.7928 - val_smape: 1.2353

Epoch 66/128

240/240 - 5s - 20ms/step - ia: 0.3586 - loss: 0.8463 - mae: 0.6776 - rmse: 0.9134 - smape: 1.3208 - val_ia: 0.3073 - val_loss: 0.7802 - val_mae: 0.6495 - val_rmse: 0.7962 - val_smape: 1.2558

Epoch 67/128

240/240 - 6s - 26ms/step - ia: 0.3574 - loss: 0.8437 - mae: 0.6777 - rmse: 0.9132 - smape: 1.3276 - val_ia: 0.3091 - val_loss: 0.7789 - val_mae: 0.6447 - val_rmse: 0.7930 - val_smape: 1.2367

Epoch 68/128

240/240 - 9s - 39ms/step - ia: 0.3573 - loss: 0.8460 - mae: 0.6784 - rmse: 0.9138 - smape: 1.3259 - val_ia: 0.3087 - val_loss: 0.7788 - val_mae: 0.6447 - val_rmse: 0.7929 - val_smape: 1.2369

Epoch 69/128

240/240 - 5s - 22ms/step - ia: 0.3587 - loss: 0.8445 - mae: 0.6759 - rmse: 0.9126 - smape: 1.3239 - val_ia: 0.3098 - val_loss: 0.7800 - val_mae: 0.6488 - val_rmse: 0.7964 - val_smape: 1.2511

Epoch 70/128

240/240 - 5s - 21ms/step - ia: 0.3612 - loss: 0.8409 - mae: 0.6755 - rmse: 0.9115 - smape: 1.3195 - val_ia: 0.3111 - val_loss: 0.7798 - val_mae: 0.6476 - val_rmse: 0.7960 - val_smape: 1.2445

Epoch 71/128

240/240 - 5s - 19ms/step - ia: 0.3581 - loss: 0.8428 - mae: 0.6768 - rmse: 0.9115 - smape: 1.3247 - val_ia: 0.3103 - val_loss: 0.7802 - val_mae: 0.6494 - val_rmse: 0.7972 - val_smape: 1.2516

Epoch 72/128

240/240 - 4s - 16ms/step - ia: 0.3646 - loss: 0.8410 - mae: 0.6745 - rmse: 0.9117 - smape: 1.3156 - val_ia: 0.3110 - val_loss: 0.7798 - val_mae: 0.6483 - val_rmse: 0.7965 - val_smape: 1.2487

Epoch 73/128

240/240 - 3s - 14ms/step - ia: 0.3615 - loss: 0.8407 - mae: 0.6755 - rmse: 0.9110 - smape: 1.3223 - val_ia: 0.3118 - val_loss: 0.7791 - val_mae: 0.6466 - val_rmse: 0.7955 - val_smape: 1.2405

Epoch 74/128

240/240 - 3s - 12ms/step - ia: 0.3625 - loss: 0.8424 - mae: 0.6744 - rmse: 0.9118 - smape: 1.3195 - val_ia: 0.3109 - val_loss: 0.7784 - val_mae: 0.6456 - val_rmse: 0.7942 - val_smape: 1.2437

Epoch 75/128

240/240 - 6s - 27ms/step - ia: 0.3619 - loss: 0.8395 - mae: 0.6747 - rmse: 0.9111 - smape: 1.3200 - val_ia: 0.3120 - val_loss: 0.7791 - val_mae: 0.6472 - val_rmse: 0.7960 - val_smape: 1.2448

Epoch 76/128

240/240 - 5s - 22ms/step - ia: 0.3606 - loss: 0.8422 - mae: 0.6766 - rmse: 0.9121 - smape: 1.3232 - val_ia: 0.3109 - val_loss: 0.7794 - val_mae: 0.6490 - val_rmse: 0.7970 - val_smape: 1.2550

Epoch 77/128

240/240 - 4s - 16ms/step - ia: 0.3596 - loss: 0.8436 - mae: 0.6764 - rmse: 0.9132 - smape: 1.3237 - val_ia: 0.3110 - val_loss: 0.7782 - val_mae: 0.6467 - val_rmse: 0.7948 - val_smape: 1.2520

Epoch 78/128

240/240 - 3s - 14ms/step - ia: 0.3599 - loss: 0.8437 - mae: 0.6752 - rmse: 0.9138 - smape: 1.3232 - val_ia: 0.3108 - val_loss: 0.7797 - val_mae: 0.6504 - val_rmse: 0.7977 - val_smape: 1.2655

Epoch 79/128

240/240 - 3s - 11ms/step - ia: 0.3611 - loss: 0.8400 - mae: 0.6745 - rmse: 0.9108 - smape: 1.3195 - val_ia: 0.3109 - val_loss: 0.7795 - val_mae: 0.6501 - val_rmse: 0.7977 - val_smape: 1.2628

Epoch 80/128

240/240 - 3s - 11ms/step - ia: 0.3596 - loss: 0.8424 - mae: 0.6764 - rmse: 0.9119 - smape: 1.3245 - val_ia: 0.3143 - val_loss: 0.7776 - val_mae: 0.6432 - val_rmse: 0.7933 - val_smape: 1.2329

Epoch 81/128

240/240 - 4s - 15ms/step - ia: 0.3607 - loss: 0.8392 - mae: 0.6749 - rmse: 0.9119 - smape: 1.3244 - val_ia: 0.3138 - val_loss: 0.7785 - val_mae: 0.6460 - val_rmse: 0.7956 - val_smape: 1.2421

Epoch 82/128

240/240 - 6s - 24ms/step - ia: 0.3616 - loss: 0.8409 - mae: 0.6755 - rmse: 0.9116 - smape: 1.3239 - val_ia: 0.3127 - val_loss: 0.7782 - val_mae: 0.6465 - val_rmse: 0.7955 - val_smape: 1.2480

Epoch 83/128

240/240 - 4s - 18ms/step - ia: 0.3638 - loss: 0.8391 - mae: 0.6735 - rmse: 0.9105 - smape: 1.3194 - val_ia: 0.3113 - val_loss: 0.7779 - val_mae: 0.6468 - val_rmse: 0.7952 - val_smape: 1.2537

Epoch 84/128

240/240 - 5s - 22ms/step - ia: 0.3594 - loss: 0.8392 - mae: 0.6748 - rmse: 0.9109 - smape: 1.3237 - val_ia: 0.3142 - val_loss: 0.7778 - val_mae: 0.6448 - val_rmse: 0.7948 - val_smape: 1.2389

Epoch 85/128

240/240 - 4s - 18ms/step - ia: 0.3614 - loss: 0.8412 - mae: 0.6750 - rmse: 0.9117 - smape: 1.3214 - val_ia: 0.3139 - val_loss: 0.7781 - val_mae: 0.6471 - val_rmse: 0.7963 - val_smape: 1.2496

Epoch 86/128

240/240 - 5s - 22ms/step - ia: 0.3657 - loss: 0.8367 - mae: 0.6734 - rmse: 0.9089 - smape: 1.3184 - val_ia: 0.3118 - val_loss: 0.7770 - val_mae: 0.6455 - val_rmse: 0.7942 - val_smape: 1.2519

Epoch 87/128

240/240 - 5s - 21ms/step - ia: 0.3598 - loss: 0.8412 - mae: 0.6758 - rmse: 0.9119 - smape: 1.3250 - val_ia: 0.3122 - val_loss: 0.7781 - val_mae: 0.6467 - val_rmse: 0.7954 - val_smape: 1.2556

Epoch 88/128

240/240 - 5s - 19ms/step - ia: 0.3635 - loss: 0.8382 - mae: 0.6740 - rmse: 0.9095 - smape: 1.3201 - val_ia: 0.3133 - val_loss: 0.7777 - val_mae: 0.6444 - val_rmse: 0.7941 - val_smape: 1.2436

Epoch 89/128

240/240 - 5s - 21ms/step - ia: 0.3627 - loss: 0.8377 - mae: 0.6727 - rmse: 0.9099 - smape: 1.3218 - val_ia: 0.3157 - val_loss: 0.7783 - val_mae: 0.6456 - val_rmse: 0.7959 - val_smape: 1.2441

Epoch 90/128

240/240 - 4s - 18ms/step - ia: 0.3660 - loss: 0.8371 - mae: 0.6722 - rmse: 0.9089 - smape: 1.3163 - val_ia: 0.3154 - val_loss: 0.7794 - val_mae: 0.6491 - val_rmse: 0.7984 - val_smape: 1.2574

Epoch 91/128

240/240 - 3s - 11ms/step - ia: 0.3660 - loss: 0.8354 - mae: 0.6720 - rmse: 0.9088 - smape: 1.3165 - val_ia: 0.3159 - val_loss: 0.7791 - val_mae: 0.6487 - val_rmse: 0.7981 - val_smape: 1.2567

Epoch 92/128

240/240 - 3s - 11ms/step - ia: 0.3670 - loss: 0.8342 - mae: 0.6714 - rmse: 0.9075 - smape: 1.3154 - val_ia: 0.3167 - val_loss: 0.7773 - val_mae: 0.6441 - val_rmse: 0.7946 - val_smape: 1.2428

Epoch 93/128

240/240 - 3s - 11ms/step - ia: 0.3664 - loss: 0.8342 - mae: 0.6720 - rmse: 0.9079 - smape: 1.3174 - val_ia: 0.3158 - val_loss: 0.7780 - val_mae: 0.6467 - val_rmse: 0.7964 - val_smape: 1.2522

Epoch 94/128

240/240 - 3s - 11ms/step - ia: 0.3649 - loss: 0.8360 - mae: 0.6730 - rmse: 0.9093 - smape: 1.3180 - val_ia: 0.3157 - val_loss: 0.7801 - val_mae: 0.6510 - val_rmse: 0.7999 - val_smape: 1.2658

Epoch 95/128

240/240 - 3s - 12ms/step - ia: 0.3706 - loss: 0.8318 - mae: 0.6697 - rmse: 0.9064 - smape: 1.3120 - val_ia: 0.3177 - val_loss: 0.7779 - val_mae: 0.6449 - val_rmse: 0.7957 - val_smape: 1.2432

Epoch 96/128

240/240 - 3s - 12ms/step - ia: 0.3662 - loss: 0.8361 - mae: 0.6719 - rmse: 0.9082 - smape: 1.3176 - val_ia: 0.3173 - val_loss: 0.7804 - val_mae: 0.6504 - val_rmse: 0.8000 - val_smape: 1.2621

Epoch 97/128

240/240 - 3s - 11ms/step - ia: 0.3634 - loss: 0.8382 - mae: 0.6745 - rmse: 0.9113 - smape: 1.3219 - val_ia: 0.3156 - val_loss: 0.7784 - val_mae: 0.6455 - val_rmse: 0.7959 - val_smape: 1.2443

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 65s - 34ms/step - ia: 0.3622 - loss: 0.8322 - mae: 0.6725 - rmse: 0.8784 - smape: 1.3291 - val_ia: 0.2508 - val_loss: 0.7513 - val_mae: 0.6369 - val_rmse: 0.7046 - val_smape: 1.2473

Epoch 2/128

1915/1915 - 80s - 42ms/step - ia: 0.4087 - loss: 0.7844 - mae: 0.6464 - rmse: 0.8515 - smape: 1.2439 - val_ia: 0.2495 - val_loss: 0.7510 - val_mae: 0.6396 - val_rmse: 0.7093 - val_smape: 1.2457

Epoch 3/128

1915/1915 - 81s - 42ms/step - ia: 0.4238 - loss: 0.7656 - mae: 0.6361 - rmse: 0.8429 - smape: 1.2190 - val_ia: 0.2541 - val_loss: 0.7390 - val_mae: 0.6235 - val_rmse: 0.6931 - val_smape: 1.2129

Epoch 4/128

1915/1915 - 83s - 43ms/step - ia: 0.4341 - loss: 0.7490 - mae: 0.6281 - rmse: 0.8322 - smape: 1.2018 - val_ia: 0.2470 - val_loss: 0.7559 - val_mae: 0.6442 - val_rmse: 0.7135 - val_smape: 1.2760

Epoch 5/128

1915/1915 - 49s - 25ms/step - ia: 0.4446 - loss: 0.7327 - mae: 0.6205 - rmse: 0.8235 - smape: 1.1845 - val_ia: 0.2520 - val_loss: 0.7521 - val_mae: 0.6330 - val_rmse: 0.7048 - val_smape: 1.2284

Epoch 6/128

1915/1915 - 79s - 41ms/step - ia: 0.4560 - loss: 0.7114 - mae: 0.6121 - rmse: 0.8131 - smape: 1.1728 - val_ia: 0.2494 - val_loss: 0.7912 - val_mae: 0.6505 - val_rmse: 0.7236 - val_smape: 1.2623

Epoch 7/128

1915/1915 - 38s - 20ms/step - ia: 0.4648 - loss: 0.6942 - mae: 0.6044 - rmse: 0.8031 - smape: 1.1587 - val_ia: 0.2523 - val_loss: 0.8684 - val_mae: 0.6594 - val_rmse: 0.7393 - val_smape: 1.2242

Epoch 8/128

1915/1915 - 54s - 28ms/step - ia: 0.4755 - loss: 0.6719 - mae: 0.5953 - rmse: 0.7882 - smape: 1.1522 - val_ia: 0.2522 - val_loss: 0.8301 - val_mae: 0.6462 - val_rmse: 0.7223 - val_smape: 1.2289

Epoch 9/128

1915/1915 - 48s - 25ms/step - ia: 0.4812 - loss: 0.6602 - mae: 0.5886 - rmse: 0.7823 - smape: 1.1448 - val_ia: 0.2477 - val_loss: 0.8738 - val_mae: 0.6671 - val_rmse: 0.7479 - val_smape: 1.2370

Epoch 10/128

1915/1915 - 82s - 43ms/step - ia: 0.4933 - loss: 0.6369 - mae: 0.5789 - rmse: 0.7679 - smape: 1.1301 - val_ia: 0.2400 - val_loss: 0.9103 - val_mae: 0.6885 - val_rmse: 0.7724 - val_smape: 1.3002

Epoch 11/128

1915/1915 - 81s - 42ms/step - ia: 0.5028 - loss: 0.6160 - mae: 0.5696 - rmse: 0.7569 - smape: 1.1191 - val_ia: 0.2368 - val_loss: 0.9600 - val_mae: 0.6923 - val_rmse: 0.7786 - val_smape: 1.2732

Epoch 12/128

1915/1915 - 36s - 19ms/step - ia: 0.5152 - loss: 0.5949 - mae: 0.5593 - rmse: 0.7416 - smape: 1.1039 - val_ia: 0.2390 - val_loss: 0.9356 - val_mae: 0.6910 - val_rmse: 0.7779 - val_smape: 1.2763

Epoch 13/128

1915/1915 - 35s - 19ms/step - ia: 0.5270 - loss: 0.5681 - mae: 0.5474 - rmse: 0.7263 - smape: 1.0843 - val_ia: 0.2417 - val_loss: 0.9996 - val_mae: 0.6998 - val_rmse: 0.7897 - val_smape: 1.2389

Epoch 14/128

1915/1915 - 30s - 16ms/step - ia: 0.5431 - loss: 0.5392 - mae: 0.5338 - rmse: 0.7086 - smape: 1.0591 - val_ia: 0.2337 - val_loss: 1.0169 - val_mae: 0.7348 - val_rmse: 0.8257 - val_smape: 1.3376

Epoch 15/128

1915/1915 - 38s - 20ms/step - ia: 0.5561 - loss: 0.5122 - mae: 0.5200 - rmse: 0.6889 - smape: 1.0413 - val_ia: 0.2417 - val_loss: 1.0082 - val_mae: 0.7037 - val_rmse: 0.7903 - val_smape: 1.2738

Epoch 16/128

1915/1915 - 38s - 20ms/step - ia: 0.5750 - loss: 0.4753 - mae: 0.5025 - rmse: 0.6642 - smape: 1.0165 - val_ia: 0.2333 - val_loss: 1.1057 - val_mae: 0.7276 - val_rmse: 0.8244 - val_smape: 1.2628

Epoch 17/128

1915/1915 - 33s - 17ms/step - ia: 0.5870 - loss: 0.4494 - mae: 0.4899 - rmse: 0.6471 - smape: 0.9949 - val_ia: 0.2334 - val_loss: 1.0854 - val_mae: 0.7223 - val_rmse: 0.8235 - val_smape: 1.2369

Epoch 18/128

1915/1915 - 47s - 24ms/step - ia: 0.6067 - loss: 0.4149 - mae: 0.4695 - rmse: 0.6203 - smape: 0.9627 - val_ia: 0.2303 - val_loss: 1.1192 - val_mae: 0.7477 - val_rmse: 0.8487 - val_smape: 1.2807

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:38 733ms/step
  6/136 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 12/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 26/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 33/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 48/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 54/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 60/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 79/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 91/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
114/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
118/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step

 17%|█▋        | 2/12 [24:24<2:09:56, 779.61s/trial, best loss: 0.7446180315174813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 41s - 11ms/step - ia: 0.2086 - loss: 1.0327 - mae: 0.7760 - rmse: 0.9541 - smape: 1.8571 - val_ia: 0.1810 - val_loss: 0.9890 - val_mae: 0.7571 - val_rmse: 0.7934 - val_smape: 1.8758

Epoch 2/128

3830/3830 - 28s - 7ms/step - ia: 0.2114 - loss: 1.0201 - mae: 0.7698 - rmse: 0.9465 - smape: 1.8722 - val_ia: 0.1817 - val_loss: 0.9819 - val_mae: 0.7524 - val_rmse: 0.7886 - val_smape: 1.8889

Epoch 3/128

3830/3830 - 41s - 11ms/step - ia: 0.2094 - loss: 1.0131 - mae: 0.7654 - rmse: 0.9414 - smape: 1.8818 - val_ia: 0.1825 - val_loss: 0.9770 - val_mae: 0.7489 - val_rmse: 0.7851 - val_smape: 1.8982

Epoch 4/128

3830/3830 - 28s - 7ms/step - ia: 0.2102 - loss: 1.0085 - mae: 0.7622 - rmse: 0.9398 - smape: 1.8896 - val_ia: 0.1831 - val_loss: 0.9733 - val_mae: 0.7462 - val_rmse: 0.7824 - val_smape: 1.9042

Epoch 5/128

3830/3830 - 28s - 7ms/step - ia: 0.2124 - loss: 1.0047 - mae: 0.7596 - rmse: 0.9370 - smape: 1.8911 - val_ia: 0.1836 - val_loss: 0.9705 - val_mae: 0.7442 - val_rmse: 0.7804 - val_smape: 1.9072

Epoch 6/128

3830/3830 - 29s - 8ms/step - ia: 0.2116 - loss: 1.0017 - mae: 0.7577 - rmse: 0.9362 - smape: 1.8932 - val_ia: 0.1840 - val_loss: 0.9680 - val_mae: 0.7425 - val_rmse: 0.7787 - val_smape: 1.9073

Epoch 7/128

3830/3830 - 29s - 8ms/step - ia: 0.2149 - loss: 0.9989 - mae: 0.7559 - rmse: 0.9343 - smape: 1.8906 - val_ia: 0.1843 - val_loss: 0.9657 - val_mae: 0.7410 - val_rmse: 0.7773 - val_smape: 1.9045

Epoch 8/128

3830/3830 - 29s - 8ms/step - ia: 0.2135 - loss: 0.9972 - mae: 0.7548 - rmse: 0.9326 - smape: 1.8886 - val_ia: 0.1846 - val_loss: 0.9635 - val_mae: 0.7398 - val_rmse: 0.7760 - val_smape: 1.8991

Epoch 9/128

3830/3830 - 28s - 7ms/step - ia: 0.2165 - loss: 0.9946 - mae: 0.7534 - rmse: 0.9323 - smape: 1.8822 - val_ia: 0.1848 - val_loss: 0.9613 - val_mae: 0.7386 - val_rmse: 0.7749 - val_smape: 1.8925

Epoch 10/128

3830/3830 - 43s - 11ms/step - ia: 0.2151 - loss: 0.9925 - mae: 0.7524 - rmse: 0.9321 - smape: 1.8767 - val_ia: 0.1850 - val_loss: 0.9591 - val_mae: 0.7376 - val_rmse: 0.7738 - val_smape: 1.8843

Epoch 11/128

3830/3830 - 28s - 7ms/step - ia: 0.2165 - loss: 0.9901 - mae: 0.7512 - rmse: 0.9294 - smape: 1.8697 - val_ia: 0.1851 - val_loss: 0.9569 - val_mae: 0.7367 - val_rmse: 0.7730 - val_smape: 1.8750

Epoch 12/128

3830/3830 - 30s - 8ms/step - ia: 0.2195 - loss: 0.9870 - mae: 0.7500 - rmse: 0.9284 - smape: 1.8600 - val_ia: 0.1853 - val_loss: 0.9546 - val_mae: 0.7359 - val_rmse: 0.7722 - val_smape: 1.8653

Epoch 13/128

3830/3830 - 29s - 8ms/step - ia: 0.2157 - loss: 0.9848 - mae: 0.7492 - rmse: 0.9264 - smape: 1.8508 - val_ia: 0.1854 - val_loss: 0.9523 - val_mae: 0.7351 - val_rmse: 0.7714 - val_smape: 1.8547

Epoch 14/128

3830/3830 - 31s - 8ms/step - ia: 0.2175 - loss: 0.9825 - mae: 0.7484 - rmse: 0.9272 - smape: 1.8400 - val_ia: 0.1855 - val_loss: 0.9499 - val_mae: 0.7343 - val_rmse: 0.7706 - val_smape: 1.8437

Epoch 15/128

3830/3830 - 36s - 9ms/step - ia: 0.2225 - loss: 0.9800 - mae: 0.7477 - rmse: 0.9246 - smape: 1.8308 - val_ia: 0.1858 - val_loss: 0.9474 - val_mae: 0.7335 - val_rmse: 0.7698 - val_smape: 1.8326

Epoch 16/128

3830/3830 - 28s - 7ms/step - ia: 0.2213 - loss: 0.9768 - mae: 0.7466 - rmse: 0.9235 - smape: 1.8193 - val_ia: 0.1860 - val_loss: 0.9448 - val_mae: 0.7328 - val_rmse: 0.7691 - val_smape: 1.8208

Epoch 17/128

3830/3830 - 41s - 11ms/step - ia: 0.2201 - loss: 0.9739 - mae: 0.7455 - rmse: 0.9228 - smape: 1.8069 - val_ia: 0.1862 - val_loss: 0.9420 - val_mae: 0.7320 - val_rmse: 0.7684 - val_smape: 1.8086

Epoch 18/128

3830/3830 - 28s - 7ms/step - ia: 0.2255 - loss: 0.9709 - mae: 0.7448 - rmse: 0.9213 - smape: 1.7961 - val_ia: 0.1864 - val_loss: 0.9391 - val_mae: 0.7311 - val_rmse: 0.7675 - val_smape: 1.7955

Epoch 19/128

3830/3830 - 28s - 7ms/step - ia: 0.2245 - loss: 0.9679 - mae: 0.7435 - rmse: 0.9203 - smape: 1.7822 - val_ia: 0.1865 - val_loss: 0.9359 - val_mae: 0.7302 - val_rmse: 0.7666 - val_smape: 1.7814

Epoch 20/128

3830/3830 - 41s - 11ms/step - ia: 0.2301 - loss: 0.9642 - mae: 0.7427 - rmse: 0.9168 - smape: 1.7702 - val_ia: 0.1866 - val_loss: 0.9324 - val_mae: 0.7292 - val_rmse: 0.7656 - val_smape: 1.7665

Epoch 21/128

3830/3830 - 28s - 7ms/step - ia: 0.2315 - loss: 0.9605 - mae: 0.7412 - rmse: 0.9158 - smape: 1.7555 - val_ia: 0.1867 - val_loss: 0.9287 - val_mae: 0.7282 - val_rmse: 0.7647 - val_smape: 1.7513

Epoch 22/128

3830/3830 - 28s - 7ms/step - ia: 0.2330 - loss: 0.9556 - mae: 0.7396 - rmse: 0.9135 - smape: 1.7405 - val_ia: 0.1869 - val_loss: 0.9246 - val_mae: 0.7270 - val_rmse: 0.7636 - val_smape: 1.7347

Epoch 23/128

3830/3830 - 28s - 7ms/step - ia: 0.2367 - loss: 0.9513 - mae: 0.7385 - rmse: 0.9112 - smape: 1.7263 - val_ia: 0.1870 - val_loss: 0.9202 - val_mae: 0.7256 - val_rmse: 0.7622 - val_smape: 1.7166

Epoch 24/128

3830/3830 - 42s - 11ms/step - ia: 0.2372 - loss: 0.9472 - mae: 0.7370 - rmse: 0.9106 - smape: 1.7107 - val_ia: 0.1871 - val_loss: 0.9156 - val_mae: 0.7242 - val_rmse: 0.7608 - val_smape: 1.6984

Epoch 25/128

3830/3830 - 28s - 7ms/step - ia: 0.2443 - loss: 0.9425 - mae: 0.7351 - rmse: 0.9075 - smape: 1.6934 - val_ia: 0.1872 - val_loss: 0.9109 - val_mae: 0.7226 - val_rmse: 0.7594 - val_smape: 1.6795

Epoch 26/128

3830/3830 - 42s - 11ms/step - ia: 0.2446 - loss: 0.9370 - mae: 0.7333 - rmse: 0.9070 - smape: 1.6756 - val_ia: 0.1874 - val_loss: 0.9060 - val_mae: 0.7208 - val_rmse: 0.7576 - val_smape: 1.6597

Epoch 27/128

3830/3830 - 41s - 11ms/step - ia: 0.2480 - loss: 0.9311 - mae: 0.7310 - rmse: 0.9049 - smape: 1.6580 - val_ia: 0.1878 - val_loss: 0.9009 - val_mae: 0.7190 - val_rmse: 0.7559 - val_smape: 1.6390

Epoch 28/128

3830/3830 - 28s - 7ms/step - ia: 0.2545 - loss: 0.9261 - mae: 0.7289 - rmse: 0.9014 - smape: 1.6408 - val_ia: 0.1881 - val_loss: 0.8960 - val_mae: 0.7170 - val_rmse: 0.7540 - val_smape: 1.6183

Epoch 29/128

3830/3830 - 28s - 7ms/step - ia: 0.2570 - loss: 0.9226 - mae: 0.7270 - rmse: 0.8988 - smape: 1.6220 - val_ia: 0.1883 - val_loss: 0.8914 - val_mae: 0.7150 - val_rmse: 0.7521 - val_smape: 1.5980

Epoch 30/128

3830/3830 - 45s - 12ms/step - ia: 0.2617 - loss: 0.9169 - mae: 0.7245 - rmse: 0.8976 - smape: 1.6028 - val_ia: 0.1886 - val_loss: 0.8872 - val_mae: 0.7130 - val_rmse: 0.7503 - val_smape: 1.5783

Epoch 31/128

3830/3830 - 40s - 11ms/step - ia: 0.2660 - loss: 0.9140 - mae: 0.7229 - rmse: 0.8957 - smape: 1.5866 - val_ia: 0.1890 - val_loss: 0.8834 - val_mae: 0.7108 - val_rmse: 0.7483 - val_smape: 1.5591

Epoch 32/128

3830/3830 - 32s - 8ms/step - ia: 0.2697 - loss: 0.9086 - mae: 0.7205 - rmse: 0.8931 - smape: 1.5710 - val_ia: 0.1893 - val_loss: 0.8801 - val_mae: 0.7088 - val_rmse: 0.7464 - val_smape: 1.5411

Epoch 33/128

3830/3830 - 32s - 8ms/step - ia: 0.2747 - loss: 0.9048 - mae: 0.7183 - rmse: 0.8912 - smape: 1.5568 - val_ia: 0.1898 - val_loss: 0.8773 - val_mae: 0.7067 - val_rmse: 0.7445 - val_smape: 1.5234

Epoch 34/128

3830/3830 - 32s - 8ms/step - ia: 0.2779 - loss: 0.9025 - mae: 0.7163 - rmse: 0.8893 - smape: 1.5403 - val_ia: 0.1903 - val_loss: 0.8749 - val_mae: 0.7047 - val_rmse: 0.7427 - val_smape: 1.5067

Epoch 35/128

3830/3830 - 41s - 11ms/step - ia: 0.2835 - loss: 0.8987 - mae: 0.7144 - rmse: 0.8877 - smape: 1.5284 - val_ia: 0.1907 - val_loss: 0.8730 - val_mae: 0.7029 - val_rmse: 0.7412 - val_smape: 1.4918

Epoch 36/128

3830/3830 - 30s - 8ms/step - ia: 0.2866 - loss: 0.8980 - mae: 0.7128 - rmse: 0.8883 - smape: 1.5168 - val_ia: 0.1911 - val_loss: 0.8714 - val_mae: 0.7013 - val_rmse: 0.7397 - val_smape: 1.4790

Epoch 37/128

3830/3830 - 33s - 9ms/step - ia: 0.2882 - loss: 0.8943 - mae: 0.7113 - rmse: 0.8861 - smape: 1.5045 - val_ia: 0.1916 - val_loss: 0.8701 - val_mae: 0.6997 - val_rmse: 0.7383 - val_smape: 1.4674

Epoch 38/128

3830/3830 - 32s - 8ms/step - ia: 0.2944 - loss: 0.8931 - mae: 0.7095 - rmse: 0.8858 - smape: 1.4933 - val_ia: 0.1919 - val_loss: 0.8689 - val_mae: 0.6985 - val_rmse: 0.7372 - val_smape: 1.4582

Epoch 39/128

3830/3830 - 32s - 8ms/step - ia: 0.2955 - loss: 0.8914 - mae: 0.7080 - rmse: 0.8851 - smape: 1.4838 - val_ia: 0.1922 - val_loss: 0.8677 - val_mae: 0.6971 - val_rmse: 0.7360 - val_smape: 1.4486

Epoch 40/128

3830/3830 - 41s - 11ms/step - ia: 0.3003 - loss: 0.8889 - mae: 0.7068 - rmse: 0.8826 - smape: 1.4758 - val_ia: 0.1924 - val_loss: 0.8666 - val_mae: 0.6960 - val_rmse: 0.7349 - val_smape: 1.4412

Epoch 41/128

3830/3830 - 34s - 9ms/step - ia: 0.3016 - loss: 0.8881 - mae: 0.7061 - rmse: 0.8838 - smape: 1.4695 - val_ia: 0.1925 - val_loss: 0.8655 - val_mae: 0.6950 - val_rmse: 0.7340 - val_smape: 1.4348

Epoch 42/128

3830/3830 - 39s - 10ms/step - ia: 0.3029 - loss: 0.8885 - mae: 0.7048 - rmse: 0.8823 - smape: 1.4642 - val_ia: 0.1926 - val_loss: 0.8644 - val_mae: 0.6941 - val_rmse: 0.7331 - val_smape: 1.4292

Epoch 43/128

3830/3830 - 35s - 9ms/step - ia: 0.3037 - loss: 0.8844 - mae: 0.7035 - rmse: 0.8815 - smape: 1.4582 - val_ia: 0.1927 - val_loss: 0.8634 - val_mae: 0.6933 - val_rmse: 0.7324 - val_smape: 1.4234

Epoch 44/128

3830/3830 - 35s - 9ms/step - ia: 0.3054 - loss: 0.8827 - mae: 0.7025 - rmse: 0.8812 - smape: 1.4520 - val_ia: 0.1927 - val_loss: 0.8626 - val_mae: 0.6926 - val_rmse: 0.7318 - val_smape: 1.4188

Epoch 45/128

3830/3830 - 32s - 8ms/step - ia: 0.3079 - loss: 0.8849 - mae: 0.7025 - rmse: 0.8807 - smape: 1.4473 - val_ia: 0.1927 - val_loss: 0.8615 - val_mae: 0.6919 - val_rmse: 0.7311 - val_smape: 1.4148

Epoch 46/128

3830/3830 - 32s - 8ms/step - ia: 0.3108 - loss: 0.8820 - mae: 0.7012 - rmse: 0.8799 - smape: 1.4439 - val_ia: 0.1927 - val_loss: 0.8605 - val_mae: 0.6912 - val_rmse: 0.7305 - val_smape: 1.4110

Epoch 47/128

3830/3830 - 30s - 8ms/step - ia: 0.3110 - loss: 0.8798 - mae: 0.7006 - rmse: 0.8801 - smape: 1.4399 - val_ia: 0.1928 - val_loss: 0.8598 - val_mae: 0.6906 - val_rmse: 0.7299 - val_smape: 1.4069

Epoch 48/128

3830/3830 - 32s - 8ms/step - ia: 0.3128 - loss: 0.8814 - mae: 0.7009 - rmse: 0.8802 - smape: 1.4372 - val_ia: 0.1929 - val_loss: 0.8587 - val_mae: 0.6901 - val_rmse: 0.7294 - val_smape: 1.4050

Epoch 49/128

3830/3830 - 33s - 9ms/step - ia: 0.3134 - loss: 0.8815 - mae: 0.7002 - rmse: 0.8794 - smape: 1.4331 - val_ia: 0.1931 - val_loss: 0.8575 - val_mae: 0.6895 - val_rmse: 0.7288 - val_smape: 1.4029

Epoch 50/128

3830/3830 - 31s - 8ms/step - ia: 0.3157 - loss: 0.8823 - mae: 0.7002 - rmse: 0.8809 - smape: 1.4329 - val_ia: 0.1932 - val_loss: 0.8566 - val_mae: 0.6892 - val_rmse: 0.7285 - val_smape: 1.4015

Epoch 51/128

3830/3830 - 32s - 8ms/step - ia: 0.3140 - loss: 0.8795 - mae: 0.6994 - rmse: 0.8791 - smape: 1.4306 - val_ia: 0.1934 - val_loss: 0.8558 - val_mae: 0.6888 - val_rmse: 0.7281 - val_smape: 1.3994

Epoch 52/128

3830/3830 - 31s - 8ms/step - ia: 0.3164 - loss: 0.8781 - mae: 0.6986 - rmse: 0.8783 - smape: 1.4292 - val_ia: 0.1935 - val_loss: 0.8550 - val_mae: 0.6883 - val_rmse: 0.7277 - val_smape: 1.3977

Epoch 53/128

3830/3830 - 41s - 11ms/step - ia: 0.3151 - loss: 0.8788 - mae: 0.6994 - rmse: 0.8789 - smape: 1.4278 - val_ia: 0.1935 - val_loss: 0.8541 - val_mae: 0.6880 - val_rmse: 0.7274 - val_smape: 1.3967

Epoch 54/128

3830/3830 - 33s - 9ms/step - ia: 0.3177 - loss: 0.8773 - mae: 0.6986 - rmse: 0.8759 - smape: 1.4256 - val_ia: 0.1936 - val_loss: 0.8533 - val_mae: 0.6876 - val_rmse: 0.7270 - val_smape: 1.3950

Epoch 55/128

3830/3830 - 31s - 8ms/step - ia: 0.3189 - loss: 0.8749 - mae: 0.6976 - rmse: 0.8757 - smape: 1.4228 - val_ia: 0.1936 - val_loss: 0.8526 - val_mae: 0.6874 - val_rmse: 0.7268 - val_smape: 1.3937

Epoch 56/128

3830/3830 - 30s - 8ms/step - ia: 0.3177 - loss: 0.8778 - mae: 0.6981 - rmse: 0.8781 - smape: 1.4223 - val_ia: 0.1937 - val_loss: 0.8517 - val_mae: 0.6869 - val_rmse: 0.7264 - val_smape: 1.3924

Epoch 57/128

3830/3830 - 34s - 9ms/step - ia: 0.3196 - loss: 0.8784 - mae: 0.6981 - rmse: 0.8769 - smape: 1.4220 - val_ia: 0.1937 - val_loss: 0.8509 - val_mae: 0.6867 - val_rmse: 0.7261 - val_smape: 1.3916

Epoch 58/128

3830/3830 - 32s - 8ms/step - ia: 0.3204 - loss: 0.8767 - mae: 0.6970 - rmse: 0.8758 - smape: 1.4187 - val_ia: 0.1937 - val_loss: 0.8500 - val_mae: 0.6862 - val_rmse: 0.7257 - val_smape: 1.3902

Epoch 59/128

3830/3830 - 31s - 8ms/step - ia: 0.3230 - loss: 0.8745 - mae: 0.6969 - rmse: 0.8765 - smape: 1.4177 - val_ia: 0.1937 - val_loss: 0.8493 - val_mae: 0.6860 - val_rmse: 0.7255 - val_smape: 1.3895

Epoch 60/128

3830/3830 - 36s - 9ms/step - ia: 0.3216 - loss: 0.8740 - mae: 0.6969 - rmse: 0.8752 - smape: 1.4186 - val_ia: 0.1937 - val_loss: 0.8488 - val_mae: 0.6858 - val_rmse: 0.7252 - val_smape: 1.3886

Epoch 61/128

3830/3830 - 36s - 9ms/step - ia: 0.3207 - loss: 0.8758 - mae: 0.6974 - rmse: 0.8757 - smape: 1.4176 - val_ia: 0.1937 - val_loss: 0.8479 - val_mae: 0.6855 - val_rmse: 0.7249 - val_smape: 1.3879

Epoch 62/128

3830/3830 - 33s - 9ms/step - ia: 0.3224 - loss: 0.8730 - mae: 0.6965 - rmse: 0.8749 - smape: 1.4150 - val_ia: 0.1937 - val_loss: 0.8473 - val_mae: 0.6852 - val_rmse: 0.7247 - val_smape: 1.3868

Epoch 63/128

3830/3830 - 32s - 8ms/step - ia: 0.3227 - loss: 0.8720 - mae: 0.6965 - rmse: 0.8757 - smape: 1.4137 - val_ia: 0.1938 - val_loss: 0.8467 - val_mae: 0.6848 - val_rmse: 0.7243 - val_smape: 1.3852

Epoch 64/128

3830/3830 - 31s - 8ms/step - ia: 0.3234 - loss: 0.8710 - mae: 0.6955 - rmse: 0.8742 - smape: 1.4133 - val_ia: 0.1939 - val_loss: 0.8461 - val_mae: 0.6844 - val_rmse: 0.7239 - val_smape: 1.3835

Epoch 65/128

3830/3830 - 33s - 9ms/step - ia: 0.3229 - loss: 0.8693 - mae: 0.6957 - rmse: 0.8733 - smape: 1.4151 - val_ia: 0.1939 - val_loss: 0.8457 - val_mae: 0.6842 - val_rmse: 0.7237 - val_smape: 1.3822

Epoch 66/128

3830/3830 - 34s - 9ms/step - ia: 0.3239 - loss: 0.8708 - mae: 0.6955 - rmse: 0.8724 - smape: 1.4119 - val_ia: 0.1939 - val_loss: 0.8451 - val_mae: 0.6839 - val_rmse: 0.7234 - val_smape: 1.3810

Epoch 67/128

3830/3830 - 32s - 8ms/step - ia: 0.3248 - loss: 0.8721 - mae: 0.6953 - rmse: 0.8745 - smape: 1.4098 - val_ia: 0.1940 - val_loss: 0.8443 - val_mae: 0.6835 - val_rmse: 0.7231 - val_smape: 1.3804

Epoch 68/128

3830/3830 - 41s - 11ms/step - ia: 0.3237 - loss: 0.8722 - mae: 0.6958 - rmse: 0.8754 - smape: 1.4096 - val_ia: 0.1941 - val_loss: 0.8434 - val_mae: 0.6831 - val_rmse: 0.7226 - val_smape: 1.3794

Epoch 69/128

3830/3830 - 33s - 9ms/step - ia: 0.3259 - loss: 0.8706 - mae: 0.6952 - rmse: 0.8741 - smape: 1.4095 - val_ia: 0.1941 - val_loss: 0.8428 - val_mae: 0.6827 - val_rmse: 0.7223 - val_smape: 1.3782

Epoch 70/128

3830/3830 - 38s - 10ms/step - ia: 0.3236 - loss: 0.8707 - mae: 0.6950 - rmse: 0.8747 - smape: 1.4078 - val_ia: 0.1941 - val_loss: 0.8423 - val_mae: 0.6825 - val_rmse: 0.7220 - val_smape: 1.3774

Epoch 71/128

3830/3830 - 34s - 9ms/step - ia: 0.3263 - loss: 0.8708 - mae: 0.6947 - rmse: 0.8746 - smape: 1.4079 - val_ia: 0.1941 - val_loss: 0.8417 - val_mae: 0.6823 - val_rmse: 0.7218 - val_smape: 1.3767

Epoch 72/128

3830/3830 - 31s - 8ms/step - ia: 0.3248 - loss: 0.8725 - mae: 0.6957 - rmse: 0.8750 - smape: 1.4082 - val_ia: 0.1942 - val_loss: 0.8411 - val_mae: 0.6820 - val_rmse: 0.7215 - val_smape: 1.3760

Epoch 73/128

3830/3830 - 32s - 8ms/step - ia: 0.3272 - loss: 0.8674 - mae: 0.6937 - rmse: 0.8732 - smape: 1.4048 - val_ia: 0.1942 - val_loss: 0.8407 - val_mae: 0.6818 - val_rmse: 0.7213 - val_smape: 1.3751

Epoch 74/128

3830/3830 - 32s - 8ms/step - ia: 0.3279 - loss: 0.8672 - mae: 0.6936 - rmse: 0.8714 - smape: 1.4048 - val_ia: 0.1943 - val_loss: 0.8404 - val_mae: 0.6815 - val_rmse: 0.7210 - val_smape: 1.3734

Epoch 75/128

3830/3830 - 33s - 9ms/step - ia: 0.3291 - loss: 0.8673 - mae: 0.6935 - rmse: 0.8720 - smape: 1.4034 - val_ia: 0.1942 - val_loss: 0.8398 - val_mae: 0.6814 - val_rmse: 0.7209 - val_smape: 1.3735

Epoch 76/128

3830/3830 - 32s - 8ms/step - ia: 0.3277 - loss: 0.8681 - mae: 0.6934 - rmse: 0.8731 - smape: 1.4009 - val_ia: 0.1943 - val_loss: 0.8392 - val_mae: 0.6810 - val_rmse: 0.7205 - val_smape: 1.3725

Epoch 77/128

3830/3830 - 32s - 8ms/step - ia: 0.3295 - loss: 0.8677 - mae: 0.6934 - rmse: 0.8725 - smape: 1.4031 - val_ia: 0.1944 - val_loss: 0.8385 - val_mae: 0.6806 - val_rmse: 0.7201 - val_smape: 1.3712

Epoch 78/128

3830/3830 - 44s - 11ms/step - ia: 0.3299 - loss: 0.8672 - mae: 0.6929 - rmse: 0.8712 - smape: 1.4007 - val_ia: 0.1944 - val_loss: 0.8378 - val_mae: 0.6803 - val_rmse: 0.7198 - val_smape: 1.3706

Epoch 79/128

3830/3830 - 38s - 10ms/step - ia: 0.3298 - loss: 0.8660 - mae: 0.6925 - rmse: 0.8725 - smape: 1.3973 - val_ia: 0.1944 - val_loss: 0.8373 - val_mae: 0.6800 - val_rmse: 0.7195 - val_smape: 1.3695

Epoch 80/128

3830/3830 - 37s - 10ms/step - ia: 0.3320 - loss: 0.8648 - mae: 0.6921 - rmse: 0.8722 - smape: 1.3976 - val_ia: 0.1945 - val_loss: 0.8369 - val_mae: 0.6798 - val_rmse: 0.7193 - val_smape: 1.3683

Epoch 81/128

3830/3830 - 39s - 10ms/step - ia: 0.3305 - loss: 0.8655 - mae: 0.6921 - rmse: 0.8722 - smape: 1.3953 - val_ia: 0.1945 - val_loss: 0.8365 - val_mae: 0.6796 - val_rmse: 0.7191 - val_smape: 1.3677

Epoch 82/128

3830/3830 - 40s - 10ms/step - ia: 0.3312 - loss: 0.8641 - mae: 0.6911 - rmse: 0.8711 - smape: 1.3950 - val_ia: 0.1945 - val_loss: 0.8359 - val_mae: 0.6794 - val_rmse: 0.7189 - val_smape: 1.3672

Epoch 83/128

3830/3830 - 40s - 10ms/step - ia: 0.3314 - loss: 0.8637 - mae: 0.6920 - rmse: 0.8707 - smape: 1.3953 - val_ia: 0.1945 - val_loss: 0.8355 - val_mae: 0.6792 - val_rmse: 0.7187 - val_smape: 1.3664

Epoch 84/128

3830/3830 - 40s - 11ms/step - ia: 0.3329 - loss: 0.8626 - mae: 0.6909 - rmse: 0.8699 - smape: 1.3916 - val_ia: 0.1946 - val_loss: 0.8350 - val_mae: 0.6789 - val_rmse: 0.7185 - val_smape: 1.3656

Epoch 85/128

3830/3830 - 41s - 11ms/step - ia: 0.3327 - loss: 0.8625 - mae: 0.6912 - rmse: 0.8704 - smape: 1.3925 - val_ia: 0.1946 - val_loss: 0.8345 - val_mae: 0.6786 - val_rmse: 0.7181 - val_smape: 1.3645

Epoch 86/128

3830/3830 - 41s - 11ms/step - ia: 0.3325 - loss: 0.8635 - mae: 0.6916 - rmse: 0.8704 - smape: 1.3931 - val_ia: 0.1947 - val_loss: 0.8339 - val_mae: 0.6782 - val_rmse: 0.7178 - val_smape: 1.3634

Epoch 87/128

3830/3830 - 39s - 10ms/step - ia: 0.3318 - loss: 0.8623 - mae: 0.6912 - rmse: 0.8695 - smape: 1.3940 - val_ia: 0.1948 - val_loss: 0.8334 - val_mae: 0.6781 - val_rmse: 0.7176 - val_smape: 1.3630

Epoch 88/128

3830/3830 - 36s - 9ms/step - ia: 0.3344 - loss: 0.8641 - mae: 0.6903 - rmse: 0.8708 - smape: 1.3887 - val_ia: 0.1949 - val_loss: 0.8328 - val_mae: 0.6777 - val_rmse: 0.7172 - val_smape: 1.3618

Epoch 89/128

3830/3830 - 36s - 9ms/step - ia: 0.3325 - loss: 0.8635 - mae: 0.6915 - rmse: 0.8701 - smape: 1.3928 - val_ia: 0.1948 - val_loss: 0.8323 - val_mae: 0.6777 - val_rmse: 0.7172 - val_smape: 1.3623

Epoch 90/128

3830/3830 - 32s - 8ms/step - ia: 0.3349 - loss: 0.8603 - mae: 0.6899 - rmse: 0.8679 - smape: 1.3878 - val_ia: 0.1949 - val_loss: 0.8318 - val_mae: 0.6774 - val_rmse: 0.7169 - val_smape: 1.3613

Epoch 91/128

3830/3830 - 31s - 8ms/step - ia: 0.3335 - loss: 0.8616 - mae: 0.6905 - rmse: 0.8690 - smape: 1.3888 - val_ia: 0.1949 - val_loss: 0.8314 - val_mae: 0.6772 - val_rmse: 0.7167 - val_smape: 1.3612

Epoch 92/128

3830/3830 - 25s - 7ms/step - ia: 0.3331 - loss: 0.8600 - mae: 0.6897 - rmse: 0.8688 - smape: 1.3864 - val_ia: 0.1949 - val_loss: 0.8311 - val_mae: 0.6771 - val_rmse: 0.7166 - val_smape: 1.3603

Epoch 93/128

3830/3830 - 51s - 13ms/step - ia: 0.3335 - loss: 0.8630 - mae: 0.6905 - rmse: 0.8706 - smape: 1.3874 - val_ia: 0.1949 - val_loss: 0.8306 - val_mae: 0.6770 - val_rmse: 0.7165 - val_smape: 1.3601

Epoch 94/128

3830/3830 - 33s - 9ms/step - ia: 0.3344 - loss: 0.8602 - mae: 0.6895 - rmse: 0.8688 - smape: 1.3868 - val_ia: 0.1950 - val_loss: 0.8302 - val_mae: 0.6767 - val_rmse: 0.7162 - val_smape: 1.3587

Epoch 95/128

3830/3830 - 32s - 8ms/step - ia: 0.3347 - loss: 0.8602 - mae: 0.6895 - rmse: 0.8674 - smape: 1.3853 - val_ia: 0.1951 - val_loss: 0.8298 - val_mae: 0.6764 - val_rmse: 0.7159 - val_smape: 1.3577

Epoch 96/128

3830/3830 - 31s - 8ms/step - ia: 0.3359 - loss: 0.8588 - mae: 0.6890 - rmse: 0.8678 - smape: 1.3838 - val_ia: 0.1950 - val_loss: 0.8295 - val_mae: 0.6764 - val_rmse: 0.7159 - val_smape: 1.3574

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 27s - 28ms/step - ia: 0.1708 - loss: 0.9719 - mae: 0.7406 - rmse: 0.9640 - smape: 1.7301 - val_ia: 0.2357 - val_loss: 0.8785 - val_mae: 0.7036 - val_rmse: 0.7865 - val_smape: 1.6006

Epoch 2/128

958/958 - 15s - 16ms/step - ia: 0.2444 - loss: 0.9058 - mae: 0.7144 - rmse: 0.9330 - smape: 1.5435 - val_ia: 0.2429 - val_loss: 0.8393 - val_mae: 0.6854 - val_rmse: 0.7712 - val_smape: 1.4497

Epoch 3/128

958/958 - 14s - 15ms/step - ia: 0.2910 - loss: 0.8851 - mae: 0.7034 - rmse: 0.9210 - smape: 1.4552 - val_ia: 0.2452 - val_loss: 0.8287 - val_mae: 0.6790 - val_rmse: 0.7667 - val_smape: 1.4041

Epoch 4/128

958/958 - 19s - 19ms/step - ia: 0.3067 - loss: 0.8770 - mae: 0.7001 - rmse: 0.9185 - smape: 1.4265 - val_ia: 0.2471 - val_loss: 0.8223 - val_mae: 0.6751 - val_rmse: 0.7639 - val_smape: 1.3769

Epoch 5/128

958/958 - 15s - 16ms/step - ia: 0.3170 - loss: 0.8707 - mae: 0.6959 - rmse: 0.9141 - smape: 1.4051 - val_ia: 0.2480 - val_loss: 0.8188 - val_mae: 0.6739 - val_rmse: 0.7629 - val_smape: 1.3705

Epoch 6/128

958/958 - 15s - 15ms/step - ia: 0.3228 - loss: 0.8682 - mae: 0.6937 - rmse: 0.9131 - smape: 1.3982 - val_ia: 0.2482 - val_loss: 0.8156 - val_mae: 0.6735 - val_rmse: 0.7624 - val_smape: 1.3706

Epoch 7/128

958/958 - 15s - 16ms/step - ia: 0.3222 - loss: 0.8686 - mae: 0.6940 - rmse: 0.9131 - smape: 1.3988 - val_ia: 0.2488 - val_loss: 0.8117 - val_mae: 0.6723 - val_rmse: 0.7611 - val_smape: 1.3674

Epoch 8/128

958/958 - 15s - 15ms/step - ia: 0.3273 - loss: 0.8649 - mae: 0.6920 - rmse: 0.9119 - smape: 1.3895 - val_ia: 0.2491 - val_loss: 0.8090 - val_mae: 0.6719 - val_rmse: 0.7607 - val_smape: 1.3655

Epoch 9/128

958/958 - 19s - 20ms/step - ia: 0.3280 - loss: 0.8626 - mae: 0.6917 - rmse: 0.9104 - smape: 1.3870 - val_ia: 0.2495 - val_loss: 0.8056 - val_mae: 0.6701 - val_rmse: 0.7591 - val_smape: 1.3579

Epoch 10/128

958/958 - 9s - 10ms/step - ia: 0.3321 - loss: 0.8593 - mae: 0.6894 - rmse: 0.9094 - smape: 1.3817 - val_ia: 0.2496 - val_loss: 0.8045 - val_mae: 0.6699 - val_rmse: 0.7592 - val_smape: 1.3546

Epoch 11/128

958/958 - 14s - 14ms/step - ia: 0.3335 - loss: 0.8581 - mae: 0.6890 - rmse: 0.9079 - smape: 1.3764 - val_ia: 0.2498 - val_loss: 0.8017 - val_mae: 0.6691 - val_rmse: 0.7583 - val_smape: 1.3530

Epoch 12/128

958/958 - 22s - 23ms/step - ia: 0.3357 - loss: 0.8556 - mae: 0.6876 - rmse: 0.9077 - smape: 1.3765 - val_ia: 0.2497 - val_loss: 0.8006 - val_mae: 0.6692 - val_rmse: 0.7584 - val_smape: 1.3548

Epoch 13/128

958/958 - 20s - 21ms/step - ia: 0.3395 - loss: 0.8510 - mae: 0.6856 - rmse: 0.9043 - smape: 1.3705 - val_ia: 0.2499 - val_loss: 0.7993 - val_mae: 0.6683 - val_rmse: 0.7577 - val_smape: 1.3499

Epoch 14/128

958/958 - 10s - 10ms/step - ia: 0.3404 - loss: 0.8512 - mae: 0.6854 - rmse: 0.9030 - smape: 1.3688 - val_ia: 0.2501 - val_loss: 0.7970 - val_mae: 0.6670 - val_rmse: 0.7565 - val_smape: 1.3467

Epoch 15/128

958/958 - 13s - 13ms/step - ia: 0.3438 - loss: 0.8513 - mae: 0.6850 - rmse: 0.9039 - smape: 1.3687 - val_ia: 0.2501 - val_loss: 0.7962 - val_mae: 0.6674 - val_rmse: 0.7569 - val_smape: 1.3496

Epoch 16/128

958/958 - 16s - 16ms/step - ia: 0.3423 - loss: 0.8491 - mae: 0.6837 - rmse: 0.9023 - smape: 1.3663 - val_ia: 0.2504 - val_loss: 0.7928 - val_mae: 0.6662 - val_rmse: 0.7557 - val_smape: 1.3461

Epoch 17/128

958/958 - 21s - 21ms/step - ia: 0.3440 - loss: 0.8453 - mae: 0.6828 - rmse: 0.9011 - smape: 1.3640 - val_ia: 0.2505 - val_loss: 0.7919 - val_mae: 0.6658 - val_rmse: 0.7556 - val_smape: 1.3437

Epoch 18/128

958/958 - 15s - 15ms/step - ia: 0.3468 - loss: 0.8457 - mae: 0.6827 - rmse: 0.9030 - smape: 1.3580 - val_ia: 0.2502 - val_loss: 0.7909 - val_mae: 0.6656 - val_rmse: 0.7552 - val_smape: 1.3470

Epoch 19/128

958/958 - 17s - 17ms/step - ia: 0.3458 - loss: 0.8438 - mae: 0.6815 - rmse: 0.9008 - smape: 1.3582 - val_ia: 0.2507 - val_loss: 0.7887 - val_mae: 0.6642 - val_rmse: 0.7542 - val_smape: 1.3387

Epoch 20/128

958/958 - 19s - 20ms/step - ia: 0.3464 - loss: 0.8440 - mae: 0.6815 - rmse: 0.9012 - smape: 1.3561 - val_ia: 0.2507 - val_loss: 0.7894 - val_mae: 0.6639 - val_rmse: 0.7542 - val_smape: 1.3361

Epoch 21/128

958/958 - 15s - 16ms/step - ia: 0.3508 - loss: 0.8410 - mae: 0.6801 - rmse: 0.8983 - smape: 1.3516 - val_ia: 0.2509 - val_loss: 0.7860 - val_mae: 0.6630 - val_rmse: 0.7530 - val_smape: 1.3374

Epoch 22/128

958/958 - 16s - 16ms/step - ia: 0.3510 - loss: 0.8393 - mae: 0.6791 - rmse: 0.8984 - smape: 1.3516 - val_ia: 0.2510 - val_loss: 0.7847 - val_mae: 0.6627 - val_rmse: 0.7527 - val_smape: 1.3378

Epoch 23/128

958/958 - 20s - 21ms/step - ia: 0.3519 - loss: 0.8383 - mae: 0.6789 - rmse: 0.8971 - smape: 1.3487 - val_ia: 0.2512 - val_loss: 0.7857 - val_mae: 0.6627 - val_rmse: 0.7533 - val_smape: 1.3344

Epoch 24/128

958/958 - 15s - 16ms/step - ia: 0.3544 - loss: 0.8358 - mae: 0.6781 - rmse: 0.8965 - smape: 1.3463 - val_ia: 0.2513 - val_loss: 0.7851 - val_mae: 0.6620 - val_rmse: 0.7527 - val_smape: 1.3310

Epoch 25/128

958/958 - 21s - 21ms/step - ia: 0.3564 - loss: 0.8371 - mae: 0.6767 - rmse: 0.8958 - smape: 1.3426 - val_ia: 0.2518 - val_loss: 0.7833 - val_mae: 0.6618 - val_rmse: 0.7525 - val_smape: 1.3316

Epoch 26/128

958/958 - 15s - 15ms/step - ia: 0.3575 - loss: 0.8347 - mae: 0.6775 - rmse: 0.8945 - smape: 1.3423 - val_ia: 0.2517 - val_loss: 0.7822 - val_mae: 0.6616 - val_rmse: 0.7523 - val_smape: 1.3325

Epoch 27/128

958/958 - 22s - 23ms/step - ia: 0.3586 - loss: 0.8355 - mae: 0.6761 - rmse: 0.8947 - smape: 1.3399 - val_ia: 0.2518 - val_loss: 0.7820 - val_mae: 0.6611 - val_rmse: 0.7518 - val_smape: 1.3308

Epoch 28/128

958/958 - 20s - 20ms/step - ia: 0.3583 - loss: 0.8347 - mae: 0.6761 - rmse: 0.8955 - smape: 1.3439 - val_ia: 0.2522 - val_loss: 0.7805 - val_mae: 0.6609 - val_rmse: 0.7516 - val_smape: 1.3305

Epoch 29/128

958/958 - 15s - 16ms/step - ia: 0.3587 - loss: 0.8325 - mae: 0.6753 - rmse: 0.8943 - smape: 1.3406 - val_ia: 0.2522 - val_loss: 0.7823 - val_mae: 0.6605 - val_rmse: 0.7517 - val_smape: 1.3254

Epoch 30/128

958/958 - 12s - 13ms/step - ia: 0.3612 - loss: 0.8307 - mae: 0.6740 - rmse: 0.8936 - smape: 1.3360 - val_ia: 0.2525 - val_loss: 0.7812 - val_mae: 0.6597 - val_rmse: 0.7510 - val_smape: 1.3227

Epoch 31/128

958/958 - 22s - 23ms/step - ia: 0.3619 - loss: 0.8284 - mae: 0.6737 - rmse: 0.8923 - smape: 1.3350 - val_ia: 0.2525 - val_loss: 0.7801 - val_mae: 0.6595 - val_rmse: 0.7506 - val_smape: 1.3257

Epoch 32/128

958/958 - 10s - 10ms/step - ia: 0.3635 - loss: 0.8284 - mae: 0.6739 - rmse: 0.8916 - smape: 1.3342 - val_ia: 0.2525 - val_loss: 0.7777 - val_mae: 0.6585 - val_rmse: 0.7495 - val_smape: 1.3260

Epoch 33/128

958/958 - 13s - 14ms/step - ia: 0.3614 - loss: 0.8275 - mae: 0.6724 - rmse: 0.8927 - smape: 1.3351 - val_ia: 0.2532 - val_loss: 0.7815 - val_mae: 0.6586 - val_rmse: 0.7506 - val_smape: 1.3157

Epoch 34/128

958/958 - 20s - 21ms/step - ia: 0.3661 - loss: 0.8285 - mae: 0.6731 - rmse: 0.8923 - smape: 1.3296 - val_ia: 0.2533 - val_loss: 0.7786 - val_mae: 0.6592 - val_rmse: 0.7506 - val_smape: 1.3233

Epoch 35/128

958/958 - 9s - 10ms/step - ia: 0.3649 - loss: 0.8265 - mae: 0.6724 - rmse: 0.8910 - smape: 1.3299 - val_ia: 0.2534 - val_loss: 0.7780 - val_mae: 0.6580 - val_rmse: 0.7497 - val_smape: 1.3178

Epoch 36/128

958/958 - 14s - 14ms/step - ia: 0.3674 - loss: 0.8261 - mae: 0.6722 - rmse: 0.8922 - smape: 1.3275 - val_ia: 0.2534 - val_loss: 0.7772 - val_mae: 0.6579 - val_rmse: 0.7493 - val_smape: 1.3206

Epoch 37/128

958/958 - 15s - 16ms/step - ia: 0.3662 - loss: 0.8268 - mae: 0.6714 - rmse: 0.8919 - smape: 1.3248 - val_ia: 0.2537 - val_loss: 0.7747 - val_mae: 0.6577 - val_rmse: 0.7488 - val_smape: 1.3233

Epoch 38/128

958/958 - 10s - 11ms/step - ia: 0.3667 - loss: 0.8232 - mae: 0.6704 - rmse: 0.8888 - smape: 1.3268 - val_ia: 0.2538 - val_loss: 0.7750 - val_mae: 0.6567 - val_rmse: 0.7483 - val_smape: 1.3176

Epoch 39/128

958/958 - 13s - 13ms/step - ia: 0.3680 - loss: 0.8246 - mae: 0.6709 - rmse: 0.8900 - smape: 1.3223 - val_ia: 0.2541 - val_loss: 0.7762 - val_mae: 0.6580 - val_rmse: 0.7495 - val_smape: 1.3209

Epoch 40/128

958/958 - 16s - 16ms/step - ia: 0.3701 - loss: 0.8214 - mae: 0.6701 - rmse: 0.8874 - smape: 1.3244 - val_ia: 0.2542 - val_loss: 0.7776 - val_mae: 0.6573 - val_rmse: 0.7493 - val_smape: 1.3141

Epoch 41/128

958/958 - 21s - 22ms/step - ia: 0.3695 - loss: 0.8218 - mae: 0.6698 - rmse: 0.8887 - smape: 1.3223 - val_ia: 0.2545 - val_loss: 0.7734 - val_mae: 0.6569 - val_rmse: 0.7485 - val_smape: 1.3197

Epoch 42/128

958/958 - 15s - 16ms/step - ia: 0.3700 - loss: 0.8233 - mae: 0.6696 - rmse: 0.8900 - smape: 1.3216 - val_ia: 0.2552 - val_loss: 0.7739 - val_mae: 0.6567 - val_rmse: 0.7485 - val_smape: 1.3141

Epoch 43/128

958/958 - 10s - 10ms/step - ia: 0.3723 - loss: 0.8189 - mae: 0.6690 - rmse: 0.8868 - smape: 1.3194 - val_ia: 0.2549 - val_loss: 0.7750 - val_mae: 0.6563 - val_rmse: 0.7485 - val_smape: 1.3123

Epoch 44/128

958/958 - 15s - 16ms/step - ia: 0.3733 - loss: 0.8197 - mae: 0.6694 - rmse: 0.8875 - smape: 1.3191 - val_ia: 0.2550 - val_loss: 0.7716 - val_mae: 0.6567 - val_rmse: 0.7481 - val_smape: 1.3245

Epoch 45/128

958/958 - 16s - 17ms/step - ia: 0.3725 - loss: 0.8189 - mae: 0.6679 - rmse: 0.8864 - smape: 1.3186 - val_ia: 0.2554 - val_loss: 0.7748 - val_mae: 0.6553 - val_rmse: 0.7477 - val_smape: 1.3076

Epoch 46/128

958/958 - 11s - 11ms/step - ia: 0.3741 - loss: 0.8198 - mae: 0.6676 - rmse: 0.8865 - smape: 1.3174 - val_ia: 0.2557 - val_loss: 0.7735 - val_mae: 0.6560 - val_rmse: 0.7482 - val_smape: 1.3123

Epoch 47/128

958/958 - 24s - 26ms/step - ia: 0.3733 - loss: 0.8191 - mae: 0.6692 - rmse: 0.8869 - smape: 1.3180 - val_ia: 0.2561 - val_loss: 0.7740 - val_mae: 0.6559 - val_rmse: 0.7482 - val_smape: 1.3115

Epoch 48/128

958/958 - 21s - 22ms/step - ia: 0.3746 - loss: 0.8202 - mae: 0.6678 - rmse: 0.8871 - smape: 1.3159 - val_ia: 0.2561 - val_loss: 0.7750 - val_mae: 0.6563 - val_rmse: 0.7489 - val_smape: 1.3106

Epoch 49/128

958/958 - 15s - 15ms/step - ia: 0.3748 - loss: 0.8177 - mae: 0.6682 - rmse: 0.8863 - smape: 1.3151 - val_ia: 0.2563 - val_loss: 0.7733 - val_mae: 0.6552 - val_rmse: 0.7476 - val_smape: 1.3075

Epoch 50/128

958/958 - 15s - 16ms/step - ia: 0.3763 - loss: 0.8172 - mae: 0.6669 - rmse: 0.8860 - smape: 1.3114 - val_ia: 0.2563 - val_loss: 0.7715 - val_mae: 0.6551 - val_rmse: 0.7471 - val_smape: 1.3141

Epoch 51/128

958/958 - 16s - 16ms/step - ia: 0.3779 - loss: 0.8145 - mae: 0.6648 - rmse: 0.8850 - smape: 1.3091 - val_ia: 0.2569 - val_loss: 0.7715 - val_mae: 0.6546 - val_rmse: 0.7471 - val_smape: 1.3067

Epoch 52/128

958/958 - 15s - 16ms/step - ia: 0.3765 - loss: 0.8170 - mae: 0.6662 - rmse: 0.8858 - smape: 1.3114 - val_ia: 0.2574 - val_loss: 0.7702 - val_mae: 0.6532 - val_rmse: 0.7459 - val_smape: 1.2995

Epoch 53/128

958/958 - 15s - 16ms/step - ia: 0.3787 - loss: 0.8158 - mae: 0.6662 - rmse: 0.8846 - smape: 1.3106 - val_ia: 0.2575 - val_loss: 0.7710 - val_mae: 0.6536 - val_rmse: 0.7463 - val_smape: 1.3004

Epoch 54/128

958/958 - 20s - 21ms/step - ia: 0.3770 - loss: 0.8125 - mae: 0.6649 - rmse: 0.8835 - smape: 1.3081 - val_ia: 0.2577 - val_loss: 0.7739 - val_mae: 0.6550 - val_rmse: 0.7481 - val_smape: 1.3023

Epoch 55/128

958/958 - 21s - 22ms/step - ia: 0.3763 - loss: 0.8181 - mae: 0.6673 - rmse: 0.8857 - smape: 1.3104 - val_ia: 0.2578 - val_loss: 0.7712 - val_mae: 0.6540 - val_rmse: 0.7467 - val_smape: 1.3034

Epoch 56/128

958/958 - 10s - 10ms/step - ia: 0.3771 - loss: 0.8140 - mae: 0.6652 - rmse: 0.8843 - smape: 1.3071 - val_ia: 0.2581 - val_loss: 0.7725 - val_mae: 0.6535 - val_rmse: 0.7467 - val_smape: 1.2952

Epoch 57/128

958/958 - 14s - 15ms/step - ia: 0.3779 - loss: 0.8155 - mae: 0.6659 - rmse: 0.8848 - smape: 1.3085 - val_ia: 0.2583 - val_loss: 0.7708 - val_mae: 0.6536 - val_rmse: 0.7465 - val_smape: 1.3007

Epoch 58/128

958/958 - 15s - 16ms/step - ia: 0.3795 - loss: 0.8147 - mae: 0.6647 - rmse: 0.8848 - smape: 1.3064 - val_ia: 0.2588 - val_loss: 0.7733 - val_mae: 0.6538 - val_rmse: 0.7474 - val_smape: 1.2945

Epoch 59/128

958/958 - 15s - 16ms/step - ia: 0.3796 - loss: 0.8155 - mae: 0.6659 - rmse: 0.8838 - smape: 1.3038 - val_ia: 0.2588 - val_loss: 0.7701 - val_mae: 0.6534 - val_rmse: 0.7464 - val_smape: 1.2993

Epoch 60/128

958/958 - 14s - 15ms/step - ia: 0.3809 - loss: 0.8141 - mae: 0.6644 - rmse: 0.8841 - smape: 1.3053 - val_ia: 0.2588 - val_loss: 0.7704 - val_mae: 0.6534 - val_rmse: 0.7465 - val_smape: 1.3000

Epoch 61/128

958/958 - 9s - 10ms/step - ia: 0.3826 - loss: 0.8120 - mae: 0.6645 - rmse: 0.8835 - smape: 1.3028 - val_ia: 0.2589 - val_loss: 0.7681 - val_mae: 0.6533 - val_rmse: 0.7459 - val_smape: 1.3044

Epoch 62/128

958/958 - 13s - 14ms/step - ia: 0.3817 - loss: 0.8119 - mae: 0.6636 - rmse: 0.8825 - smape: 1.3041 - val_ia: 0.2593 - val_loss: 0.7704 - val_mae: 0.6532 - val_rmse: 0.7463 - val_smape: 1.2991

Epoch 63/128

958/958 - 22s - 23ms/step - ia: 0.3825 - loss: 0.8113 - mae: 0.6631 - rmse: 0.8830 - smape: 1.3004 - val_ia: 0.2595 - val_loss: 0.7705 - val_mae: 0.6527 - val_rmse: 0.7459 - val_smape: 1.2964

Epoch 64/128

958/958 - 15s - 16ms/step - ia: 0.3824 - loss: 0.8131 - mae: 0.6641 - rmse: 0.8835 - smape: 1.3025 - val_ia: 0.2597 - val_loss: 0.7708 - val_mae: 0.6534 - val_rmse: 0.7467 - val_smape: 1.2979

Epoch 65/128

958/958 - 16s - 17ms/step - ia: 0.3820 - loss: 0.8101 - mae: 0.6633 - rmse: 0.8819 - smape: 1.3012 - val_ia: 0.2595 - val_loss: 0.7709 - val_mae: 0.6537 - val_rmse: 0.7470 - val_smape: 1.2991

Epoch 66/128

958/958 - 14s - 14ms/step - ia: 0.3821 - loss: 0.8108 - mae: 0.6629 - rmse: 0.8823 - smape: 1.2987 - val_ia: 0.2600 - val_loss: 0.7691 - val_mae: 0.6529 - val_rmse: 0.7460 - val_smape: 1.2985

Epoch 67/128

958/958 - 15s - 16ms/step - ia: 0.3847 - loss: 0.8087 - mae: 0.6624 - rmse: 0.8809 - smape: 1.2973 - val_ia: 0.2601 - val_loss: 0.7695 - val_mae: 0.6533 - val_rmse: 0.7466 - val_smape: 1.2993

Epoch 68/128

958/958 - 15s - 16ms/step - ia: 0.3837 - loss: 0.8099 - mae: 0.6631 - rmse: 0.8824 - smape: 1.3009 - val_ia: 0.2603 - val_loss: 0.7675 - val_mae: 0.6522 - val_rmse: 0.7454 - val_smape: 1.2962

Epoch 69/128

958/958 - 20s - 21ms/step - ia: 0.3868 - loss: 0.8070 - mae: 0.6613 - rmse: 0.8804 - smape: 1.2947 - val_ia: 0.2605 - val_loss: 0.7672 - val_mae: 0.6522 - val_rmse: 0.7453 - val_smape: 1.2977

Epoch 70/128

958/958 - 21s - 21ms/step - ia: 0.3855 - loss: 0.8073 - mae: 0.6619 - rmse: 0.8804 - smape: 1.2960 - val_ia: 0.2607 - val_loss: 0.7678 - val_mae: 0.6521 - val_rmse: 0.7453 - val_smape: 1.2963

Epoch 71/128

958/958 - 16s - 17ms/step - ia: 0.3849 - loss: 0.8111 - mae: 0.6620 - rmse: 0.8823 - smape: 1.2952 - val_ia: 0.2607 - val_loss: 0.7679 - val_mae: 0.6521 - val_rmse: 0.7453 - val_smape: 1.2965

Epoch 72/128

958/958 - 15s - 16ms/step - ia: 0.3856 - loss: 0.8080 - mae: 0.6617 - rmse: 0.8802 - smape: 1.2969 - val_ia: 0.2610 - val_loss: 0.7700 - val_mae: 0.6533 - val_rmse: 0.7469 - val_smape: 1.2970

Epoch 73/128

958/958 - 15s - 15ms/step - ia: 0.3875 - loss: 0.8075 - mae: 0.6616 - rmse: 0.8800 - smape: 1.2950 - val_ia: 0.2612 - val_loss: 0.7677 - val_mae: 0.6518 - val_rmse: 0.7451 - val_smape: 1.2941

Epoch 74/128

958/958 - 10s - 11ms/step - ia: 0.3858 - loss: 0.8099 - mae: 0.6619 - rmse: 0.8816 - smape: 1.2963 - val_ia: 0.2614 - val_loss: 0.7691 - val_mae: 0.6524 - val_rmse: 0.7459 - val_smape: 1.2952

Epoch 75/128

958/958 - 15s - 15ms/step - ia: 0.3844 - loss: 0.8122 - mae: 0.6632 - rmse: 0.8829 - smape: 1.2961 - val_ia: 0.2613 - val_loss: 0.7664 - val_mae: 0.6514 - val_rmse: 0.7447 - val_smape: 1.2946

Epoch 76/128

958/958 - 24s - 25ms/step - ia: 0.3856 - loss: 0.8066 - mae: 0.6604 - rmse: 0.8810 - smape: 1.2950 - val_ia: 0.2618 - val_loss: 0.7714 - val_mae: 0.6523 - val_rmse: 0.7464 - val_smape: 1.2878

Epoch 77/128

958/958 - 16s - 17ms/step - ia: 0.3868 - loss: 0.8077 - mae: 0.6621 - rmse: 0.8811 - smape: 1.2935 - val_ia: 0.2618 - val_loss: 0.7700 - val_mae: 0.6523 - val_rmse: 0.7462 - val_smape: 1.2913

Epoch 78/128

958/958 - 17s - 17ms/step - ia: 0.3879 - loss: 0.8078 - mae: 0.6613 - rmse: 0.8804 - smape: 1.2915 - val_ia: 0.2620 - val_loss: 0.7669 - val_mae: 0.6513 - val_rmse: 0.7448 - val_smape: 1.2917

Epoch 79/128

958/958 - 16s - 17ms/step - ia: 0.3855 - loss: 0.8094 - mae: 0.6620 - rmse: 0.8821 - smape: 1.2942 - val_ia: 0.2620 - val_loss: 0.7665 - val_mae: 0.6513 - val_rmse: 0.7447 - val_smape: 1.2920

Epoch 80/128

958/958 - 20s - 21ms/step - ia: 0.3883 - loss: 0.8061 - mae: 0.6616 - rmse: 0.8793 - smape: 1.2933 - val_ia: 0.2622 - val_loss: 0.7659 - val_mae: 0.6513 - val_rmse: 0.7447 - val_smape: 1.2940

Epoch 81/128

958/958 - 15s - 16ms/step - ia: 0.3868 - loss: 0.8045 - mae: 0.6602 - rmse: 0.8797 - smape: 1.2924 - val_ia: 0.2624 - val_loss: 0.7718 - val_mae: 0.6518 - val_rmse: 0.7461 - val_smape: 1.2847

Epoch 82/128

958/958 - 15s - 16ms/step - ia: 0.3881 - loss: 0.8062 - mae: 0.6605 - rmse: 0.8794 - smape: 1.2913 - val_ia: 0.2626 - val_loss: 0.7694 - val_mae: 0.6512 - val_rmse: 0.7454 - val_smape: 1.2854

Epoch 83/128

958/958 - 15s - 15ms/step - ia: 0.3884 - loss: 0.8070 - mae: 0.6608 - rmse: 0.8815 - smape: 1.2899 - val_ia: 0.2625 - val_loss: 0.7674 - val_mae: 0.6518 - val_rmse: 0.7454 - val_smape: 1.2940

Epoch 84/128

958/958 - 10s - 10ms/step - ia: 0.3888 - loss: 0.8067 - mae: 0.6602 - rmse: 0.8804 - smape: 1.2899 - val_ia: 0.2624 - val_loss: 0.7653 - val_mae: 0.6518 - val_rmse: 0.7450 - val_smape: 1.2974

Epoch 85/128

958/958 - 14s - 14ms/step - ia: 0.3876 - loss: 0.8041 - mae: 0.6601 - rmse: 0.8791 - smape: 1.2885 - val_ia: 0.2628 - val_loss: 0.7655 - val_mae: 0.6499 - val_rmse: 0.7438 - val_smape: 1.2854

Epoch 86/128

958/958 - 15s - 16ms/step - ia: 0.3905 - loss: 0.8043 - mae: 0.6595 - rmse: 0.8795 - smape: 1.2868 - val_ia: 0.2627 - val_loss: 0.7671 - val_mae: 0.6513 - val_rmse: 0.7451 - val_smape: 1.2901

Epoch 87/128

958/958 - 16s - 16ms/step - ia: 0.3906 - loss: 0.8054 - mae: 0.6605 - rmse: 0.8801 - smape: 1.2887 - val_ia: 0.2627 - val_loss: 0.7643 - val_mae: 0.6515 - val_rmse: 0.7447 - val_smape: 1.2984

Epoch 88/128

958/958 - 20s - 21ms/step - ia: 0.3897 - loss: 0.8036 - mae: 0.6594 - rmse: 0.8786 - smape: 1.2912 - val_ia: 0.2630 - val_loss: 0.7681 - val_mae: 0.6513 - val_rmse: 0.7455 - val_smape: 1.2875

Epoch 89/128

958/958 - 21s - 21ms/step - ia: 0.3914 - loss: 0.8021 - mae: 0.6588 - rmse: 0.8776 - smape: 1.2878 - val_ia: 0.2628 - val_loss: 0.7669 - val_mae: 0.6523 - val_rmse: 0.7460 - val_smape: 1.2966

Epoch 90/128

958/958 - 16s - 17ms/step - ia: 0.3889 - loss: 0.8042 - mae: 0.6595 - rmse: 0.8799 - smape: 1.2883 - val_ia: 0.2630 - val_loss: 0.7675 - val_mae: 0.6522 - val_rmse: 0.7460 - val_smape: 1.2951

Epoch 91/128

958/958 - 14s - 15ms/step - ia: 0.3891 - loss: 0.8016 - mae: 0.6586 - rmse: 0.8773 - smape: 1.2896 - val_ia: 0.2635 - val_loss: 0.7717 - val_mae: 0.6518 - val_rmse: 0.7464 - val_smape: 1.2853

Epoch 92/128

958/958 - 9s - 10ms/step - ia: 0.3912 - loss: 0.8027 - mae: 0.6591 - rmse: 0.8788 - smape: 1.2858 - val_ia: 0.2636 - val_loss: 0.7688 - val_mae: 0.6513 - val_rmse: 0.7455 - val_smape: 1.2880

Epoch 93/128

958/958 - 15s - 15ms/step - ia: 0.3916 - loss: 0.8029 - mae: 0.6590 - rmse: 0.8787 - smape: 1.2846 - val_ia: 0.2635 - val_loss: 0.7665 - val_mae: 0.6515 - val_rmse: 0.7453 - val_smape: 1.2919

Epoch 94/128

958/958 - 15s - 15ms/step - ia: 0.3911 - loss: 0.8004 - mae: 0.6573 - rmse: 0.8760 - smape: 1.2841 - val_ia: 0.2641 - val_loss: 0.7693 - val_mae: 0.6520 - val_rmse: 0.7464 - val_smape: 1.2874

Epoch 95/128

958/958 - 22s - 22ms/step - ia: 0.3910 - loss: 0.8019 - mae: 0.6589 - rmse: 0.8777 - smape: 1.2851 - val_ia: 0.2639 - val_loss: 0.7703 - val_mae: 0.6519 - val_rmse: 0.7464 - val_smape: 1.2877

Epoch 96/128

958/958 - 14s - 15ms/step - ia: 0.3910 - loss: 0.8022 - mae: 0.6589 - rmse: 0.8780 - smape: 1.2874 - val_ia: 0.2643 - val_loss: 0.7676 - val_mae: 0.6509 - val_rmse: 0.7452 - val_smape: 1.2852

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 9s - 19ms/step - ia: 0.1284 - loss: 1.0079 - mae: 0.7638 - rmse: 0.9936 - smape: 1.7352 - val_ia: 0.2345 - val_loss: 0.9472 - val_mae: 0.7357 - val_rmse: 0.8484 - val_smape: 1.7330

Epoch 2/128

479/479 - 4s - 7ms/step - ia: 0.1302 - loss: 1.0013 - mae: 0.7605 - rmse: 0.9905 - smape: 1.7377 - val_ia: 0.2343 - val_loss: 0.9416 - val_mae: 0.7337 - val_rmse: 0.8461 - val_smape: 1.7396

Epoch 3/128

479/479 - 4s - 7ms/step - ia: 0.1292 - loss: 0.9946 - mae: 0.7567 - rmse: 0.9872 - smape: 1.7346 - val_ia: 0.2340 - val_loss: 0.9362 - val_mae: 0.7317 - val_rmse: 0.8439 - val_smape: 1.7462

Epoch 4/128

479/479 - 3s - 7ms/step - ia: 0.1373 - loss: 0.9844 - mae: 0.7525 - rmse: 0.9806 - smape: 1.7280 - val_ia: 0.2338 - val_loss: 0.9309 - val_mae: 0.7298 - val_rmse: 0.8417 - val_smape: 1.7495

Epoch 5/128

479/479 - 3s - 7ms/step - ia: 0.1421 - loss: 0.9787 - mae: 0.7504 - rmse: 0.9786 - smape: 1.7269 - val_ia: 0.2336 - val_loss: 0.9258 - val_mae: 0.7279 - val_rmse: 0.8396 - val_smape: 1.7487

Epoch 6/128

479/479 - 3s - 7ms/step - ia: 0.1416 - loss: 0.9730 - mae: 0.7480 - rmse: 0.9752 - smape: 1.7245 - val_ia: 0.2335 - val_loss: 0.9208 - val_mae: 0.7260 - val_rmse: 0.8375 - val_smape: 1.7457

Epoch 7/128

479/479 - 4s - 8ms/step - ia: 0.1466 - loss: 0.9681 - mae: 0.7455 - rmse: 0.9731 - smape: 1.7180 - val_ia: 0.2335 - val_loss: 0.9159 - val_mae: 0.7241 - val_rmse: 0.8355 - val_smape: 1.7406

Epoch 8/128

479/479 - 3s - 7ms/step - ia: 0.1531 - loss: 0.9628 - mae: 0.7427 - rmse: 0.9696 - smape: 1.7091 - val_ia: 0.2336 - val_loss: 0.9112 - val_mae: 0.7223 - val_rmse: 0.8335 - val_smape: 1.7342

Epoch 9/128

479/479 - 3s - 7ms/step - ia: 0.1577 - loss: 0.9563 - mae: 0.7398 - rmse: 0.9667 - smape: 1.6985 - val_ia: 0.2337 - val_loss: 0.9065 - val_mae: 0.7205 - val_rmse: 0.8316 - val_smape: 1.7249

Epoch 10/128

479/479 - 4s - 7ms/step - ia: 0.1592 - loss: 0.9523 - mae: 0.7377 - rmse: 0.9661 - smape: 1.6915 - val_ia: 0.2338 - val_loss: 0.9019 - val_mae: 0.7186 - val_rmse: 0.8296 - val_smape: 1.7146

Epoch 11/128

479/479 - 3s - 7ms/step - ia: 0.1681 - loss: 0.9438 - mae: 0.7342 - rmse: 0.9599 - smape: 1.6775 - val_ia: 0.2341 - val_loss: 0.8972 - val_mae: 0.7167 - val_rmse: 0.8276 - val_smape: 1.7024

Epoch 12/128

479/479 - 3s - 7ms/step - ia: 0.1722 - loss: 0.9405 - mae: 0.7325 - rmse: 0.9590 - smape: 1.6649 - val_ia: 0.2343 - val_loss: 0.8928 - val_mae: 0.7149 - val_rmse: 0.8258 - val_smape: 1.6898

Epoch 13/128

479/479 - 4s - 7ms/step - ia: 0.1749 - loss: 0.9343 - mae: 0.7296 - rmse: 0.9564 - smape: 1.6534 - val_ia: 0.2346 - val_loss: 0.8884 - val_mae: 0.7131 - val_rmse: 0.8240 - val_smape: 1.6772

Epoch 14/128

479/479 - 3s - 7ms/step - ia: 0.1831 - loss: 0.9316 - mae: 0.7278 - rmse: 0.9542 - smape: 1.6424 - val_ia: 0.2348 - val_loss: 0.8842 - val_mae: 0.7113 - val_rmse: 0.8222 - val_smape: 1.6644

Epoch 15/128

479/479 - 3s - 7ms/step - ia: 0.1889 - loss: 0.9284 - mae: 0.7262 - rmse: 0.9524 - smape: 1.6308 - val_ia: 0.2351 - val_loss: 0.8801 - val_mae: 0.7094 - val_rmse: 0.8204 - val_smape: 1.6507

Epoch 16/128

479/479 - 3s - 7ms/step - ia: 0.1944 - loss: 0.9225 - mae: 0.7235 - rmse: 0.9495 - smape: 1.6185 - val_ia: 0.2354 - val_loss: 0.8760 - val_mae: 0.7076 - val_rmse: 0.8187 - val_smape: 1.6373

Epoch 17/128

479/479 - 4s - 7ms/step - ia: 0.2037 - loss: 0.9188 - mae: 0.7212 - rmse: 0.9474 - smape: 1.6046 - val_ia: 0.2358 - val_loss: 0.8721 - val_mae: 0.7058 - val_rmse: 0.8170 - val_smape: 1.6241

Epoch 18/128

479/479 - 4s - 7ms/step - ia: 0.2075 - loss: 0.9160 - mae: 0.7202 - rmse: 0.9470 - smape: 1.5956 - val_ia: 0.2361 - val_loss: 0.8683 - val_mae: 0.7040 - val_rmse: 0.8154 - val_smape: 1.6114

Epoch 19/128

479/479 - 4s - 7ms/step - ia: 0.2127 - loss: 0.9107 - mae: 0.7173 - rmse: 0.9435 - smape: 1.5820 - val_ia: 0.2365 - val_loss: 0.8647 - val_mae: 0.7023 - val_rmse: 0.8139 - val_smape: 1.5990

Epoch 20/128

479/479 - 4s - 7ms/step - ia: 0.2184 - loss: 0.9087 - mae: 0.7169 - rmse: 0.9424 - smape: 1.5724 - val_ia: 0.2369 - val_loss: 0.8612 - val_mae: 0.7006 - val_rmse: 0.8124 - val_smape: 1.5862

Epoch 21/128

479/479 - 3s - 7ms/step - ia: 0.2245 - loss: 0.9045 - mae: 0.7139 - rmse: 0.9403 - smape: 1.5592 - val_ia: 0.2374 - val_loss: 0.8578 - val_mae: 0.6990 - val_rmse: 0.8110 - val_smape: 1.5738

Epoch 22/128

479/479 - 3s - 7ms/step - ia: 0.2308 - loss: 0.9012 - mae: 0.7115 - rmse: 0.9394 - smape: 1.5444 - val_ia: 0.2378 - val_loss: 0.8546 - val_mae: 0.6973 - val_rmse: 0.8095 - val_smape: 1.5616

Epoch 23/128

479/479 - 3s - 7ms/step - ia: 0.2374 - loss: 0.8998 - mae: 0.7115 - rmse: 0.9371 - smape: 1.5394 - val_ia: 0.2382 - val_loss: 0.8515 - val_mae: 0.6958 - val_rmse: 0.8083 - val_smape: 1.5501

Epoch 24/128

479/479 - 4s - 7ms/step - ia: 0.2412 - loss: 0.8970 - mae: 0.7100 - rmse: 0.9371 - smape: 1.5258 - val_ia: 0.2386 - val_loss: 0.8485 - val_mae: 0.6943 - val_rmse: 0.8070 - val_smape: 1.5385

Epoch 25/128

479/479 - 5s - 11ms/step - ia: 0.2449 - loss: 0.8949 - mae: 0.7089 - rmse: 0.9355 - smape: 1.5189 - val_ia: 0.2389 - val_loss: 0.8457 - val_mae: 0.6929 - val_rmse: 0.8058 - val_smape: 1.5276

Epoch 26/128

479/479 - 5s - 11ms/step - ia: 0.2516 - loss: 0.8919 - mae: 0.7077 - rmse: 0.9339 - smape: 1.5111 - val_ia: 0.2393 - val_loss: 0.8430 - val_mae: 0.6914 - val_rmse: 0.8046 - val_smape: 1.5167

Epoch 27/128

479/479 - 3s - 7ms/step - ia: 0.2563 - loss: 0.8889 - mae: 0.7052 - rmse: 0.9323 - smape: 1.4992 - val_ia: 0.2397 - val_loss: 0.8405 - val_mae: 0.6901 - val_rmse: 0.8035 - val_smape: 1.5069

Epoch 28/128

479/479 - 5s - 11ms/step - ia: 0.2604 - loss: 0.8882 - mae: 0.7049 - rmse: 0.9327 - smape: 1.4915 - val_ia: 0.2401 - val_loss: 0.8381 - val_mae: 0.6888 - val_rmse: 0.8025 - val_smape: 1.4971

Epoch 29/128

479/479 - 3s - 7ms/step - ia: 0.2643 - loss: 0.8856 - mae: 0.7039 - rmse: 0.9309 - smape: 1.4844 - val_ia: 0.2406 - val_loss: 0.8359 - val_mae: 0.6875 - val_rmse: 0.8015 - val_smape: 1.4877

Epoch 30/128

479/479 - 3s - 7ms/step - ia: 0.2680 - loss: 0.8841 - mae: 0.7031 - rmse: 0.9302 - smape: 1.4795 - val_ia: 0.2411 - val_loss: 0.8337 - val_mae: 0.6863 - val_rmse: 0.8006 - val_smape: 1.4788

Epoch 31/128

479/479 - 3s - 7ms/step - ia: 0.2730 - loss: 0.8841 - mae: 0.7029 - rmse: 0.9301 - smape: 1.4720 - val_ia: 0.2416 - val_loss: 0.8317 - val_mae: 0.6851 - val_rmse: 0.7997 - val_smape: 1.4706

Epoch 32/128

479/479 - 4s - 7ms/step - ia: 0.2775 - loss: 0.8802 - mae: 0.7005 - rmse: 0.9275 - smape: 1.4621 - val_ia: 0.2420 - val_loss: 0.8298 - val_mae: 0.6840 - val_rmse: 0.7988 - val_smape: 1.4627

Epoch 33/128

479/479 - 4s - 7ms/step - ia: 0.2810 - loss: 0.8777 - mae: 0.6994 - rmse: 0.9274 - smape: 1.4568 - val_ia: 0.2425 - val_loss: 0.8278 - val_mae: 0.6829 - val_rmse: 0.7980 - val_smape: 1.4551

Epoch 34/128

479/479 - 3s - 7ms/step - ia: 0.2838 - loss: 0.8777 - mae: 0.6992 - rmse: 0.9265 - smape: 1.4521 - val_ia: 0.2429 - val_loss: 0.8261 - val_mae: 0.6820 - val_rmse: 0.7973 - val_smape: 1.4481

Epoch 35/128

479/479 - 3s - 7ms/step - ia: 0.2874 - loss: 0.8763 - mae: 0.6985 - rmse: 0.9264 - smape: 1.4455 - val_ia: 0.2434 - val_loss: 0.8245 - val_mae: 0.6810 - val_rmse: 0.7966 - val_smape: 1.4416

Epoch 36/128

479/479 - 4s - 7ms/step - ia: 0.2905 - loss: 0.8737 - mae: 0.6976 - rmse: 0.9249 - smape: 1.4426 - val_ia: 0.2438 - val_loss: 0.8230 - val_mae: 0.6801 - val_rmse: 0.7959 - val_smape: 1.4354

Epoch 37/128

479/479 - 3s - 7ms/step - ia: 0.2932 - loss: 0.8734 - mae: 0.6969 - rmse: 0.9245 - smape: 1.4342 - val_ia: 0.2442 - val_loss: 0.8216 - val_mae: 0.6793 - val_rmse: 0.7953 - val_smape: 1.4299

Epoch 38/128

479/479 - 4s - 7ms/step - ia: 0.2964 - loss: 0.8728 - mae: 0.6965 - rmse: 0.9243 - smape: 1.4303 - val_ia: 0.2446 - val_loss: 0.8202 - val_mae: 0.6785 - val_rmse: 0.7947 - val_smape: 1.4245

Epoch 39/128

479/479 - 5s - 11ms/step - ia: 0.2992 - loss: 0.8721 - mae: 0.6954 - rmse: 0.9241 - smape: 1.4258 - val_ia: 0.2451 - val_loss: 0.8190 - val_mae: 0.6777 - val_rmse: 0.7942 - val_smape: 1.4196

Epoch 40/128

479/479 - 4s - 7ms/step - ia: 0.3007 - loss: 0.8716 - mae: 0.6953 - rmse: 0.9235 - smape: 1.4221 - val_ia: 0.2455 - val_loss: 0.8178 - val_mae: 0.6771 - val_rmse: 0.7937 - val_smape: 1.4152

Epoch 41/128

479/479 - 3s - 7ms/step - ia: 0.3035 - loss: 0.8718 - mae: 0.6945 - rmse: 0.9249 - smape: 1.4165 - val_ia: 0.2459 - val_loss: 0.8166 - val_mae: 0.6763 - val_rmse: 0.7932 - val_smape: 1.4106

Epoch 42/128

479/479 - 5s - 11ms/step - ia: 0.3060 - loss: 0.8682 - mae: 0.6933 - rmse: 0.9221 - smape: 1.4126 - val_ia: 0.2462 - val_loss: 0.8155 - val_mae: 0.6757 - val_rmse: 0.7927 - val_smape: 1.4063

Epoch 43/128

479/479 - 4s - 8ms/step - ia: 0.3075 - loss: 0.8676 - mae: 0.6932 - rmse: 0.9210 - smape: 1.4109 - val_ia: 0.2466 - val_loss: 0.8145 - val_mae: 0.6750 - val_rmse: 0.7922 - val_smape: 1.4024

Epoch 44/128

479/479 - 5s - 10ms/step - ia: 0.3096 - loss: 0.8674 - mae: 0.6922 - rmse: 0.9212 - smape: 1.4056 - val_ia: 0.2470 - val_loss: 0.8135 - val_mae: 0.6744 - val_rmse: 0.7917 - val_smape: 1.3987

Epoch 45/128

479/479 - 4s - 8ms/step - ia: 0.3100 - loss: 0.8688 - mae: 0.6933 - rmse: 0.9223 - smape: 1.4068 - val_ia: 0.2474 - val_loss: 0.8125 - val_mae: 0.6738 - val_rmse: 0.7913 - val_smape: 1.3954

Epoch 46/128

479/479 - 4s - 8ms/step - ia: 0.3131 - loss: 0.8659 - mae: 0.6919 - rmse: 0.9208 - smape: 1.4030 - val_ia: 0.2477 - val_loss: 0.8116 - val_mae: 0.6733 - val_rmse: 0.7909 - val_smape: 1.3922

Epoch 47/128

479/479 - 4s - 8ms/step - ia: 0.3150 - loss: 0.8651 - mae: 0.6919 - rmse: 0.9205 - smape: 1.3988 - val_ia: 0.2481 - val_loss: 0.8107 - val_mae: 0.6728 - val_rmse: 0.7906 - val_smape: 1.3895

Epoch 48/128

479/479 - 4s - 7ms/step - ia: 0.3163 - loss: 0.8645 - mae: 0.6912 - rmse: 0.9199 - smape: 1.3977 - val_ia: 0.2485 - val_loss: 0.8099 - val_mae: 0.6722 - val_rmse: 0.7902 - val_smape: 1.3866

Epoch 49/128

479/479 - 4s - 8ms/step - ia: 0.3161 - loss: 0.8640 - mae: 0.6910 - rmse: 0.9199 - smape: 1.3954 - val_ia: 0.2488 - val_loss: 0.8091 - val_mae: 0.6718 - val_rmse: 0.7898 - val_smape: 1.3839

Epoch 50/128

479/479 - 4s - 8ms/step - ia: 0.3191 - loss: 0.8609 - mae: 0.6899 - rmse: 0.9190 - smape: 1.3922 - val_ia: 0.2492 - val_loss: 0.8084 - val_mae: 0.6714 - val_rmse: 0.7896 - val_smape: 1.3818

Epoch 51/128

479/479 - 5s - 11ms/step - ia: 0.3183 - loss: 0.8626 - mae: 0.6906 - rmse: 0.9191 - smape: 1.3940 - val_ia: 0.2495 - val_loss: 0.8077 - val_mae: 0.6711 - val_rmse: 0.7893 - val_smape: 1.3799

Epoch 52/128

479/479 - 4s - 8ms/step - ia: 0.3194 - loss: 0.8624 - mae: 0.6905 - rmse: 0.9192 - smape: 1.3920 - val_ia: 0.2499 - val_loss: 0.8070 - val_mae: 0.6707 - val_rmse: 0.7890 - val_smape: 1.3779

Epoch 53/128

479/479 - 4s - 8ms/step - ia: 0.3216 - loss: 0.8600 - mae: 0.6894 - rmse: 0.9175 - smape: 1.3871 - val_ia: 0.2502 - val_loss: 0.8064 - val_mae: 0.6703 - val_rmse: 0.7888 - val_smape: 1.3760

Epoch 54/128

479/479 - 5s - 10ms/step - ia: 0.3235 - loss: 0.8609 - mae: 0.6892 - rmse: 0.9177 - smape: 1.3855 - val_ia: 0.2505 - val_loss: 0.8057 - val_mae: 0.6699 - val_rmse: 0.7885 - val_smape: 1.3741

Epoch 55/128

479/479 - 3s - 7ms/step - ia: 0.3223 - loss: 0.8608 - mae: 0.6897 - rmse: 0.9184 - smape: 1.3843 - val_ia: 0.2508 - val_loss: 0.8051 - val_mae: 0.6696 - val_rmse: 0.7883 - val_smape: 1.3727

Epoch 56/128

479/479 - 4s - 8ms/step - ia: 0.3249 - loss: 0.8581 - mae: 0.6885 - rmse: 0.9170 - smape: 1.3837 - val_ia: 0.2511 - val_loss: 0.8045 - val_mae: 0.6693 - val_rmse: 0.7881 - val_smape: 1.3712

Epoch 57/128

479/479 - 4s - 8ms/step - ia: 0.3256 - loss: 0.8592 - mae: 0.6884 - rmse: 0.9172 - smape: 1.3809 - val_ia: 0.2514 - val_loss: 0.8039 - val_mae: 0.6690 - val_rmse: 0.7878 - val_smape: 1.3698

Epoch 58/128

479/479 - 4s - 7ms/step - ia: 0.3262 - loss: 0.8592 - mae: 0.6882 - rmse: 0.9168 - smape: 1.3797 - val_ia: 0.2517 - val_loss: 0.8033 - val_mae: 0.6687 - val_rmse: 0.7876 - val_smape: 1.3684

Epoch 59/128

479/479 - 5s - 11ms/step - ia: 0.3271 - loss: 0.8603 - mae: 0.6879 - rmse: 0.9184 - smape: 1.3778 - val_ia: 0.2520 - val_loss: 0.8027 - val_mae: 0.6684 - val_rmse: 0.7874 - val_smape: 1.3671

Epoch 60/128

479/479 - 4s - 8ms/step - ia: 0.3288 - loss: 0.8578 - mae: 0.6876 - rmse: 0.9168 - smape: 1.3787 - val_ia: 0.2523 - val_loss: 0.8021 - val_mae: 0.6681 - val_rmse: 0.7871 - val_smape: 1.3659

Epoch 61/128

479/479 - 5s - 10ms/step - ia: 0.3297 - loss: 0.8564 - mae: 0.6874 - rmse: 0.9151 - smape: 1.3752 - val_ia: 0.2525 - val_loss: 0.8016 - val_mae: 0.6679 - val_rmse: 0.7869 - val_smape: 1.3650

Epoch 62/128

479/479 - 5s - 10ms/step - ia: 0.3286 - loss: 0.8578 - mae: 0.6868 - rmse: 0.9177 - smape: 1.3731 - val_ia: 0.2528 - val_loss: 0.8012 - val_mae: 0.6677 - val_rmse: 0.7868 - val_smape: 1.3641

Epoch 63/128

479/479 - 3s - 6ms/step - ia: 0.3320 - loss: 0.8553 - mae: 0.6862 - rmse: 0.9150 - smape: 1.3741 - val_ia: 0.2531 - val_loss: 0.8007 - val_mae: 0.6674 - val_rmse: 0.7866 - val_smape: 1.3631

Epoch 64/128

479/479 - 5s - 11ms/step - ia: 0.3292 - loss: 0.8570 - mae: 0.6875 - rmse: 0.9161 - smape: 1.3751 - val_ia: 0.2533 - val_loss: 0.8001 - val_mae: 0.6671 - val_rmse: 0.7863 - val_smape: 1.3618

Epoch 65/128

479/479 - 3s - 6ms/step - ia: 0.3323 - loss: 0.8549 - mae: 0.6857 - rmse: 0.9145 - smape: 1.3713 - val_ia: 0.2536 - val_loss: 0.7997 - val_mae: 0.6670 - val_rmse: 0.7863 - val_smape: 1.3611

Epoch 66/128

479/479 - 3s - 7ms/step - ia: 0.3341 - loss: 0.8535 - mae: 0.6853 - rmse: 0.9133 - smape: 1.3692 - val_ia: 0.2539 - val_loss: 0.7993 - val_mae: 0.6667 - val_rmse: 0.7861 - val_smape: 1.3601

Epoch 67/128

479/479 - 5s - 11ms/step - ia: 0.3327 - loss: 0.8537 - mae: 0.6861 - rmse: 0.9152 - smape: 1.3713 - val_ia: 0.2541 - val_loss: 0.7988 - val_mae: 0.6665 - val_rmse: 0.7859 - val_smape: 1.3589

Epoch 68/128

479/479 - 4s - 8ms/step - ia: 0.3328 - loss: 0.8554 - mae: 0.6858 - rmse: 0.9157 - smape: 1.3708 - val_ia: 0.2544 - val_loss: 0.7984 - val_mae: 0.6663 - val_rmse: 0.7858 - val_smape: 1.3581

Epoch 69/128

479/479 - 4s - 7ms/step - ia: 0.3344 - loss: 0.8538 - mae: 0.6855 - rmse: 0.9145 - smape: 1.3677 - val_ia: 0.2546 - val_loss: 0.7979 - val_mae: 0.6661 - val_rmse: 0.7856 - val_smape: 1.3572

Epoch 70/128

479/479 - 4s - 7ms/step - ia: 0.3358 - loss: 0.8510 - mae: 0.6843 - rmse: 0.9125 - smape: 1.3657 - val_ia: 0.2548 - val_loss: 0.7975 - val_mae: 0.6660 - val_rmse: 0.7855 - val_smape: 1.3568

Epoch 71/128

479/479 - 5s - 10ms/step - ia: 0.3363 - loss: 0.8525 - mae: 0.6847 - rmse: 0.9136 - smape: 1.3654 - val_ia: 0.2551 - val_loss: 0.7971 - val_mae: 0.6658 - val_rmse: 0.7854 - val_smape: 1.3560

Epoch 72/128

479/479 - 5s - 11ms/step - ia: 0.3364 - loss: 0.8504 - mae: 0.6841 - rmse: 0.9122 - smape: 1.3654 - val_ia: 0.2553 - val_loss: 0.7967 - val_mae: 0.6656 - val_rmse: 0.7852 - val_smape: 1.3553

Epoch 73/128

479/479 - 5s - 11ms/step - ia: 0.3369 - loss: 0.8522 - mae: 0.6844 - rmse: 0.9140 - smape: 1.3644 - val_ia: 0.2555 - val_loss: 0.7963 - val_mae: 0.6654 - val_rmse: 0.7850 - val_smape: 1.3547

Epoch 74/128

479/479 - 5s - 11ms/step - ia: 0.3384 - loss: 0.8511 - mae: 0.6837 - rmse: 0.9120 - smape: 1.3630 - val_ia: 0.2557 - val_loss: 0.7960 - val_mae: 0.6653 - val_rmse: 0.7850 - val_smape: 1.3543

Epoch 75/128

479/479 - 5s - 11ms/step - ia: 0.3387 - loss: 0.8495 - mae: 0.6837 - rmse: 0.9123 - smape: 1.3608 - val_ia: 0.2559 - val_loss: 0.7956 - val_mae: 0.6652 - val_rmse: 0.7849 - val_smape: 1.3539

Epoch 76/128

479/479 - 4s - 7ms/step - ia: 0.3386 - loss: 0.8491 - mae: 0.6835 - rmse: 0.9114 - smape: 1.3606 - val_ia: 0.2561 - val_loss: 0.7952 - val_mae: 0.6650 - val_rmse: 0.7848 - val_smape: 1.3532

Epoch 77/128

479/479 - 3s - 6ms/step - ia: 0.3384 - loss: 0.8497 - mae: 0.6836 - rmse: 0.9121 - smape: 1.3602 - val_ia: 0.2563 - val_loss: 0.7949 - val_mae: 0.6648 - val_rmse: 0.7846 - val_smape: 1.3526

Epoch 78/128

479/479 - 3s - 6ms/step - ia: 0.3380 - loss: 0.8511 - mae: 0.6840 - rmse: 0.9124 - smape: 1.3602 - val_ia: 0.2565 - val_loss: 0.7946 - val_mae: 0.6648 - val_rmse: 0.7846 - val_smape: 1.3523

Epoch 79/128

479/479 - 3s - 6ms/step - ia: 0.3394 - loss: 0.8490 - mae: 0.6836 - rmse: 0.9117 - smape: 1.3607 - val_ia: 0.2567 - val_loss: 0.7942 - val_mae: 0.6646 - val_rmse: 0.7845 - val_smape: 1.3518

Epoch 80/128

479/479 - 3s - 6ms/step - ia: 0.3405 - loss: 0.8497 - mae: 0.6831 - rmse: 0.9115 - smape: 1.3585 - val_ia: 0.2568 - val_loss: 0.7938 - val_mae: 0.6644 - val_rmse: 0.7843 - val_smape: 1.3512

Epoch 81/128

479/479 - 5s - 10ms/step - ia: 0.3396 - loss: 0.8505 - mae: 0.6837 - rmse: 0.9126 - smape: 1.3598 - val_ia: 0.2570 - val_loss: 0.7935 - val_mae: 0.6643 - val_rmse: 0.7842 - val_smape: 1.3507

Epoch 82/128

479/479 - 3s - 7ms/step - ia: 0.3421 - loss: 0.8472 - mae: 0.6820 - rmse: 0.9110 - smape: 1.3558 - val_ia: 0.2571 - val_loss: 0.7932 - val_mae: 0.6642 - val_rmse: 0.7841 - val_smape: 1.3505

Epoch 83/128

479/479 - 4s - 8ms/step - ia: 0.3426 - loss: 0.8471 - mae: 0.6823 - rmse: 0.9111 - smape: 1.3553 - val_ia: 0.2573 - val_loss: 0.7929 - val_mae: 0.6641 - val_rmse: 0.7840 - val_smape: 1.3500

Epoch 84/128

479/479 - 4s - 8ms/step - ia: 0.3419 - loss: 0.8461 - mae: 0.6822 - rmse: 0.9107 - smape: 1.3575 - val_ia: 0.2575 - val_loss: 0.7926 - val_mae: 0.6640 - val_rmse: 0.7840 - val_smape: 1.3497

Epoch 85/128

479/479 - 4s - 8ms/step - ia: 0.3423 - loss: 0.8491 - mae: 0.6825 - rmse: 0.9110 - smape: 1.3565 - val_ia: 0.2576 - val_loss: 0.7923 - val_mae: 0.6639 - val_rmse: 0.7839 - val_smape: 1.3493

Epoch 86/128

479/479 - 5s - 11ms/step - ia: 0.3423 - loss: 0.8486 - mae: 0.6830 - rmse: 0.9122 - smape: 1.3548 - val_ia: 0.2578 - val_loss: 0.7920 - val_mae: 0.6639 - val_rmse: 0.7838 - val_smape: 1.3491

Epoch 87/128

479/479 - 4s - 8ms/step - ia: 0.3426 - loss: 0.8479 - mae: 0.6821 - rmse: 0.9110 - smape: 1.3547 - val_ia: 0.2579 - val_loss: 0.7917 - val_mae: 0.6637 - val_rmse: 0.7837 - val_smape: 1.3488

Epoch 88/128

479/479 - 5s - 10ms/step - ia: 0.3426 - loss: 0.8493 - mae: 0.6832 - rmse: 0.9120 - smape: 1.3579 - val_ia: 0.2580 - val_loss: 0.7914 - val_mae: 0.6636 - val_rmse: 0.7836 - val_smape: 1.3483

Epoch 89/128

479/479 - 5s - 11ms/step - ia: 0.3439 - loss: 0.8467 - mae: 0.6820 - rmse: 0.9109 - smape: 1.3542 - val_ia: 0.2582 - val_loss: 0.7912 - val_mae: 0.6635 - val_rmse: 0.7836 - val_smape: 1.3481

Epoch 90/128

479/479 - 4s - 8ms/step - ia: 0.3427 - loss: 0.8463 - mae: 0.6815 - rmse: 0.9109 - smape: 1.3528 - val_ia: 0.2583 - val_loss: 0.7908 - val_mae: 0.6634 - val_rmse: 0.7834 - val_smape: 1.3476

Epoch 91/128

479/479 - 5s - 10ms/step - ia: 0.3447 - loss: 0.8465 - mae: 0.6816 - rmse: 0.9106 - smape: 1.3523 - val_ia: 0.2584 - val_loss: 0.7905 - val_mae: 0.6633 - val_rmse: 0.7833 - val_smape: 1.3472

Epoch 92/128

479/479 - 5s - 11ms/step - ia: 0.3435 - loss: 0.8462 - mae: 0.6820 - rmse: 0.9099 - smape: 1.3554 - val_ia: 0.2585 - val_loss: 0.7901 - val_mae: 0.6631 - val_rmse: 0.7831 - val_smape: 1.3467

Epoch 93/128

479/479 - 5s - 11ms/step - ia: 0.3444 - loss: 0.8455 - mae: 0.6821 - rmse: 0.9093 - smape: 1.3556 - val_ia: 0.2587 - val_loss: 0.7898 - val_mae: 0.6630 - val_rmse: 0.7830 - val_smape: 1.3460

Epoch 94/128

479/479 - 4s - 9ms/step - ia: 0.3442 - loss: 0.8455 - mae: 0.6810 - rmse: 0.9101 - smape: 1.3516 - val_ia: 0.2588 - val_loss: 0.7894 - val_mae: 0.6628 - val_rmse: 0.7829 - val_smape: 1.3456

Epoch 95/128

479/479 - 6s - 13ms/step - ia: 0.3452 - loss: 0.8437 - mae: 0.6809 - rmse: 0.9090 - smape: 1.3517 - val_ia: 0.2590 - val_loss: 0.7892 - val_mae: 0.6628 - val_rmse: 0.7828 - val_smape: 1.3453

Epoch 96/128

479/479 - 4s - 8ms/step - ia: 0.3452 - loss: 0.8432 - mae: 0.6810 - rmse: 0.9087 - smape: 1.3529 - val_ia: 0.2591 - val_loss: 0.7890 - val_mae: 0.6627 - val_rmse: 0.7828 - val_smape: 1.3450

Epoch 97/128

479/479 - 4s - 8ms/step - ia: 0.3476 - loss: 0.8428 - mae: 0.6796 - rmse: 0.9088 - smape: 1.3469 - val_ia: 0.2592 - val_loss: 0.7887 - val_mae: 0.6626 - val_rmse: 0.7827 - val_smape: 1.3447

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 10s - 41ms/step - ia: 0.2384 - loss: 1.4299 - mae: 1.0034 - rmse: 1.1922 - smape: 1.5710 - val_ia: 0.2479 - val_loss: 1.2426 - val_mae: 0.9521 - val_rmse: 1.0759 - val_smape: 1.5966

Epoch 2/128

240/240 - 4s - 16ms/step - ia: 0.2278 - loss: 1.2937 - mae: 0.9337 - rmse: 1.1339 - smape: 1.5763 - val_ia: 0.2513 - val_loss: 1.1275 - val_mae: 0.8836 - val_rmse: 1.0105 - val_smape: 1.6200

Epoch 3/128

240/240 - 3s - 14ms/step - ia: 0.2185 - loss: 1.2109 - mae: 0.8829 - rmse: 1.0963 - smape: 1.5768 - val_ia: 0.2548 - val_loss: 1.0556 - val_mae: 0.8326 - val_rmse: 0.9629 - val_smape: 1.6549

Epoch 4/128

240/240 - 3s - 13ms/step - ia: 0.2128 - loss: 1.1691 - mae: 0.8526 - rmse: 1.0773 - smape: 1.5738 - val_ia: 0.2583 - val_loss: 1.0142 - val_mae: 0.7975 - val_rmse: 0.9308 - val_smape: 1.7011

Epoch 5/128

240/240 - 3s - 13ms/step - ia: 0.2180 - loss: 1.1366 - mae: 0.8278 - rmse: 1.0610 - smape: 1.5571 - val_ia: 0.2570 - val_loss: 0.9911 - val_mae: 0.7735 - val_rmse: 0.9095 - val_smape: 1.7559

Epoch 6/128

240/240 - 3s - 13ms/step - ia: 0.2197 - loss: 1.1296 - mae: 0.8168 - rmse: 1.0583 - smape: 1.5478 - val_ia: 0.2564 - val_loss: 0.9791 - val_mae: 0.7583 - val_rmse: 0.8964 - val_smape: 1.8120

Epoch 7/128

240/240 - 4s - 15ms/step - ia: 0.2256 - loss: 1.1192 - mae: 0.8049 - rmse: 1.0526 - smape: 1.5306 - val_ia: 0.2552 - val_loss: 0.9726 - val_mae: 0.7487 - val_rmse: 0.8883 - val_smape: 1.8650

Epoch 8/128

240/240 - 4s - 17ms/step - ia: 0.2257 - loss: 1.1123 - mae: 0.7998 - rmse: 1.0501 - smape: 1.5283 - val_ia: 0.2539 - val_loss: 0.9694 - val_mae: 0.7436 - val_rmse: 0.8840 - val_smape: 1.9042

Epoch 9/128

240/240 - 5s - 21ms/step - ia: 0.2268 - loss: 1.1144 - mae: 0.7979 - rmse: 1.0505 - smape: 1.5235 - val_ia: 0.2533 - val_loss: 0.9675 - val_mae: 0.7408 - val_rmse: 0.8817 - val_smape: 1.9267

Epoch 10/128

240/240 - 4s - 16ms/step - ia: 0.2276 - loss: 1.1079 - mae: 0.7943 - rmse: 1.0468 - smape: 1.5229 - val_ia: 0.2532 - val_loss: 0.9659 - val_mae: 0.7388 - val_rmse: 0.8799 - val_smape: 1.9385

Epoch 11/128

240/240 - 4s - 16ms/step - ia: 0.2253 - loss: 1.1157 - mae: 0.7956 - rmse: 1.0495 - smape: 1.5288 - val_ia: 0.2533 - val_loss: 0.9648 - val_mae: 0.7377 - val_rmse: 0.8789 - val_smape: 1.9415

Epoch 12/128

240/240 - 5s - 22ms/step - ia: 0.2240 - loss: 1.1064 - mae: 0.7937 - rmse: 1.0457 - smape: 1.5293 - val_ia: 0.2534 - val_loss: 0.9639 - val_mae: 0.7373 - val_rmse: 0.8785 - val_smape: 1.9403

Epoch 13/128

240/240 - 6s - 25ms/step - ia: 0.2220 - loss: 1.1061 - mae: 0.7921 - rmse: 1.0458 - smape: 1.5285 - val_ia: 0.2535 - val_loss: 0.9627 - val_mae: 0.7359 - val_rmse: 0.8773 - val_smape: 1.9424

Epoch 14/128

240/240 - 4s - 17ms/step - ia: 0.2255 - loss: 1.0967 - mae: 0.7876 - rmse: 1.0408 - smape: 1.5243 - val_ia: 0.2536 - val_loss: 0.9616 - val_mae: 0.7347 - val_rmse: 0.8762 - val_smape: 1.9402

Epoch 15/128

240/240 - 5s - 21ms/step - ia: 0.2219 - loss: 1.0914 - mae: 0.7870 - rmse: 1.0382 - smape: 1.5304 - val_ia: 0.2537 - val_loss: 0.9608 - val_mae: 0.7345 - val_rmse: 0.8759 - val_smape: 1.9379

Epoch 16/128

240/240 - 4s - 16ms/step - ia: 0.2235 - loss: 1.0920 - mae: 0.7835 - rmse: 1.0397 - smape: 1.5254 - val_ia: 0.2538 - val_loss: 0.9601 - val_mae: 0.7346 - val_rmse: 0.8758 - val_smape: 1.9358

Epoch 17/128

240/240 - 4s - 16ms/step - ia: 0.2223 - loss: 1.0856 - mae: 0.7821 - rmse: 1.0358 - smape: 1.5279 - val_ia: 0.2539 - val_loss: 0.9591 - val_mae: 0.7339 - val_rmse: 0.8752 - val_smape: 1.9321

Epoch 18/128

240/240 - 4s - 16ms/step - ia: 0.2187 - loss: 1.0885 - mae: 0.7837 - rmse: 1.0376 - smape: 1.5322 - val_ia: 0.2540 - val_loss: 0.9583 - val_mae: 0.7338 - val_rmse: 0.8749 - val_smape: 1.9294

Epoch 19/128

240/240 - 4s - 16ms/step - ia: 0.2138 - loss: 1.0856 - mae: 0.7849 - rmse: 1.0362 - smape: 1.5419 - val_ia: 0.2541 - val_loss: 0.9573 - val_mae: 0.7331 - val_rmse: 0.8743 - val_smape: 1.9252

Epoch 20/128

240/240 - 5s - 21ms/step - ia: 0.2183 - loss: 1.0799 - mae: 0.7804 - rmse: 1.0328 - smape: 1.5335 - val_ia: 0.2541 - val_loss: 0.9561 - val_mae: 0.7318 - val_rmse: 0.8731 - val_smape: 1.9152

Epoch 21/128

240/240 - 4s - 16ms/step - ia: 0.2162 - loss: 1.0751 - mae: 0.7797 - rmse: 1.0320 - smape: 1.5352 - val_ia: 0.2543 - val_loss: 0.9554 - val_mae: 0.7321 - val_rmse: 0.8732 - val_smape: 1.9162

Epoch 22/128

240/240 - 4s - 16ms/step - ia: 0.2149 - loss: 1.0673 - mae: 0.7773 - rmse: 1.0271 - smape: 1.5393 - val_ia: 0.2543 - val_loss: 0.9543 - val_mae: 0.7311 - val_rmse: 0.8723 - val_smape: 1.9075

Epoch 23/128

240/240 - 4s - 18ms/step - ia: 0.2182 - loss: 1.0598 - mae: 0.7709 - rmse: 1.0240 - smape: 1.5340 - val_ia: 0.2544 - val_loss: 0.9532 - val_mae: 0.7302 - val_rmse: 0.8715 - val_smape: 1.8988

Epoch 24/128

240/240 - 4s - 16ms/step - ia: 0.2127 - loss: 1.0683 - mae: 0.7768 - rmse: 1.0269 - smape: 1.5440 - val_ia: 0.2545 - val_loss: 0.9524 - val_mae: 0.7303 - val_rmse: 0.8714 - val_smape: 1.8991

Epoch 25/128

240/240 - 4s - 17ms/step - ia: 0.2132 - loss: 1.0671 - mae: 0.7747 - rmse: 1.0265 - smape: 1.5397 - val_ia: 0.2546 - val_loss: 0.9514 - val_mae: 0.7296 - val_rmse: 0.8707 - val_smape: 1.8926

Epoch 26/128

240/240 - 5s - 21ms/step - ia: 0.2114 - loss: 1.0670 - mae: 0.7751 - rmse: 1.0261 - smape: 1.5420 - val_ia: 0.2547 - val_loss: 0.9508 - val_mae: 0.7303 - val_rmse: 0.8711 - val_smape: 1.8967

Epoch 27/128

240/240 - 4s - 16ms/step - ia: 0.2098 - loss: 1.0598 - mae: 0.7725 - rmse: 1.0243 - smape: 1.5480 - val_ia: 0.2548 - val_loss: 0.9496 - val_mae: 0.7293 - val_rmse: 0.8702 - val_smape: 1.8877

Epoch 28/128

240/240 - 4s - 17ms/step - ia: 0.2081 - loss: 1.0567 - mae: 0.7741 - rmse: 1.0231 - smape: 1.5534 - val_ia: 0.2548 - val_loss: 0.9483 - val_mae: 0.7279 - val_rmse: 0.8689 - val_smape: 1.8742

Epoch 29/128

240/240 - 5s - 21ms/step - ia: 0.2089 - loss: 1.0484 - mae: 0.7705 - rmse: 1.0178 - smape: 1.5483 - val_ia: 0.2549 - val_loss: 0.9472 - val_mae: 0.7272 - val_rmse: 0.8683 - val_smape: 1.8679

Epoch 30/128

240/240 - 4s - 16ms/step - ia: 0.2085 - loss: 1.0524 - mae: 0.7690 - rmse: 1.0202 - smape: 1.5471 - val_ia: 0.2551 - val_loss: 0.9464 - val_mae: 0.7275 - val_rmse: 0.8683 - val_smape: 1.8703

Epoch 31/128

240/240 - 4s - 16ms/step - ia: 0.2102 - loss: 1.0499 - mae: 0.7682 - rmse: 1.0185 - smape: 1.5485 - val_ia: 0.2552 - val_loss: 0.9453 - val_mae: 0.7271 - val_rmse: 0.8678 - val_smape: 1.8657

Epoch 32/128

240/240 - 5s - 21ms/step - ia: 0.2052 - loss: 1.0500 - mae: 0.7698 - rmse: 1.0194 - smape: 1.5553 - val_ia: 0.2553 - val_loss: 0.9443 - val_mae: 0.7269 - val_rmse: 0.8675 - val_smape: 1.8633

Epoch 33/128

240/240 - 4s - 16ms/step - ia: 0.2060 - loss: 1.0456 - mae: 0.7679 - rmse: 1.0167 - smape: 1.5529 - val_ia: 0.2554 - val_loss: 0.9433 - val_mae: 0.7267 - val_rmse: 0.8672 - val_smape: 1.8607

Epoch 34/128

240/240 - 5s - 21ms/step - ia: 0.2087 - loss: 1.0401 - mae: 0.7643 - rmse: 1.0142 - smape: 1.5482 - val_ia: 0.2555 - val_loss: 0.9421 - val_mae: 0.7258 - val_rmse: 0.8663 - val_smape: 1.8525

Epoch 35/128

240/240 - 4s - 17ms/step - ia: 0.2081 - loss: 1.0347 - mae: 0.7636 - rmse: 1.0115 - smape: 1.5529 - val_ia: 0.2556 - val_loss: 0.9409 - val_mae: 0.7253 - val_rmse: 0.8657 - val_smape: 1.8471

Epoch 36/128

240/240 - 4s - 18ms/step - ia: 0.2060 - loss: 1.0402 - mae: 0.7659 - rmse: 1.0130 - smape: 1.5563 - val_ia: 0.2557 - val_loss: 0.9397 - val_mae: 0.7248 - val_rmse: 0.8652 - val_smape: 1.8422

Epoch 37/128

240/240 - 4s - 17ms/step - ia: 0.2058 - loss: 1.0307 - mae: 0.7628 - rmse: 1.0089 - smape: 1.5556 - val_ia: 0.2558 - val_loss: 0.9384 - val_mae: 0.7239 - val_rmse: 0.8643 - val_smape: 1.8339

Epoch 38/128

240/240 - 4s - 17ms/step - ia: 0.2044 - loss: 1.0342 - mae: 0.7630 - rmse: 1.0103 - smape: 1.5581 - val_ia: 0.2559 - val_loss: 0.9372 - val_mae: 0.7236 - val_rmse: 0.8638 - val_smape: 1.8301

Epoch 39/128

240/240 - 5s - 19ms/step - ia: 0.2045 - loss: 1.0281 - mae: 0.7605 - rmse: 1.0073 - smape: 1.5542 - val_ia: 0.2561 - val_loss: 0.9360 - val_mae: 0.7234 - val_rmse: 0.8635 - val_smape: 1.8280

Epoch 40/128

240/240 - 5s - 20ms/step - ia: 0.2052 - loss: 1.0271 - mae: 0.7599 - rmse: 1.0082 - smape: 1.5555 - val_ia: 0.2562 - val_loss: 0.9348 - val_mae: 0.7230 - val_rmse: 0.8630 - val_smape: 1.8233

Epoch 41/128

240/240 - 4s - 16ms/step - ia: 0.2031 - loss: 1.0286 - mae: 0.7597 - rmse: 1.0079 - smape: 1.5568 - val_ia: 0.2564 - val_loss: 0.9336 - val_mae: 0.7229 - val_rmse: 0.8627 - val_smape: 1.8217

Epoch 42/128

240/240 - 4s - 16ms/step - ia: 0.2042 - loss: 1.0226 - mae: 0.7578 - rmse: 1.0052 - smape: 1.5568 - val_ia: 0.2565 - val_loss: 0.9320 - val_mae: 0.7216 - val_rmse: 0.8616 - val_smape: 1.8111

Epoch 43/128

240/240 - 4s - 16ms/step - ia: 0.2043 - loss: 1.0238 - mae: 0.7586 - rmse: 1.0056 - smape: 1.5566 - val_ia: 0.2566 - val_loss: 0.9307 - val_mae: 0.7211 - val_rmse: 0.8609 - val_smape: 1.8058

Epoch 44/128

240/240 - 4s - 17ms/step - ia: 0.2066 - loss: 1.0148 - mae: 0.7564 - rmse: 1.0011 - smape: 1.5557 - val_ia: 0.2568 - val_loss: 0.9294 - val_mae: 0.7209 - val_rmse: 0.8606 - val_smape: 1.8037

Epoch 45/128

240/240 - 5s - 21ms/step - ia: 0.2035 - loss: 1.0193 - mae: 0.7579 - rmse: 1.0052 - smape: 1.5603 - val_ia: 0.2570 - val_loss: 0.9281 - val_mae: 0.7206 - val_rmse: 0.8601 - val_smape: 1.7997

Epoch 46/128

240/240 - 4s - 17ms/step - ia: 0.2040 - loss: 1.0194 - mae: 0.7565 - rmse: 1.0030 - smape: 1.5571 - val_ia: 0.2571 - val_loss: 0.9265 - val_mae: 0.7195 - val_rmse: 0.8590 - val_smape: 1.7904

Epoch 47/128

240/240 - 4s - 17ms/step - ia: 0.2026 - loss: 1.0157 - mae: 0.7553 - rmse: 1.0029 - smape: 1.5608 - val_ia: 0.2573 - val_loss: 0.9252 - val_mae: 0.7196 - val_rmse: 0.8589 - val_smape: 1.7904

Epoch 48/128

240/240 - 5s - 21ms/step - ia: 0.2044 - loss: 1.0120 - mae: 0.7552 - rmse: 1.0014 - smape: 1.5589 - val_ia: 0.2573 - val_loss: 0.9234 - val_mae: 0.7181 - val_rmse: 0.8575 - val_smape: 1.7781

Epoch 49/128

240/240 - 5s - 22ms/step - ia: 0.2060 - loss: 1.0028 - mae: 0.7515 - rmse: 0.9952 - smape: 1.5578 - val_ia: 0.2575 - val_loss: 0.9219 - val_mae: 0.7179 - val_rmse: 0.8571 - val_smape: 1.7753

Epoch 50/128

240/240 - 5s - 21ms/step - ia: 0.2043 - loss: 1.0048 - mae: 0.7535 - rmse: 0.9956 - smape: 1.5606 - val_ia: 0.2577 - val_loss: 0.9202 - val_mae: 0.7170 - val_rmse: 0.8562 - val_smape: 1.7678

Epoch 51/128

240/240 - 4s - 16ms/step - ia: 0.2065 - loss: 1.0052 - mae: 0.7520 - rmse: 0.9971 - smape: 1.5542 - val_ia: 0.2579 - val_loss: 0.9187 - val_mae: 0.7168 - val_rmse: 0.8558 - val_smape: 1.7653

Epoch 52/128

240/240 - 4s - 17ms/step - ia: 0.2045 - loss: 1.0043 - mae: 0.7516 - rmse: 0.9962 - smape: 1.5551 - val_ia: 0.2581 - val_loss: 0.9171 - val_mae: 0.7161 - val_rmse: 0.8550 - val_smape: 1.7592

Epoch 53/128

240/240 - 5s - 21ms/step - ia: 0.2074 - loss: 1.0033 - mae: 0.7501 - rmse: 0.9959 - smape: 1.5508 - val_ia: 0.2584 - val_loss: 0.9157 - val_mae: 0.7164 - val_rmse: 0.8549 - val_smape: 1.7590

Epoch 54/128

240/240 - 4s - 16ms/step - ia: 0.2058 - loss: 1.0007 - mae: 0.7506 - rmse: 0.9950 - smape: 1.5559 - val_ia: 0.2586 - val_loss: 0.9139 - val_mae: 0.7156 - val_rmse: 0.8540 - val_smape: 1.7523

Epoch 55/128

240/240 - 4s - 16ms/step - ia: 0.2087 - loss: 0.9962 - mae: 0.7484 - rmse: 0.9936 - smape: 1.5528 - val_ia: 0.2588 - val_loss: 0.9122 - val_mae: 0.7152 - val_rmse: 0.8535 - val_smape: 1.7479

Epoch 56/128

240/240 - 4s - 16ms/step - ia: 0.2080 - loss: 0.9944 - mae: 0.7480 - rmse: 0.9904 - smape: 1.5500 - val_ia: 0.2590 - val_loss: 0.9102 - val_mae: 0.7141 - val_rmse: 0.8524 - val_smape: 1.7396

Epoch 57/128

240/240 - 6s - 23ms/step - ia: 0.2082 - loss: 0.9946 - mae: 0.7486 - rmse: 0.9906 - smape: 1.5568 - val_ia: 0.2591 - val_loss: 0.9083 - val_mae: 0.7130 - val_rmse: 0.8512 - val_smape: 1.7306

Epoch 58/128

240/240 - 5s - 21ms/step - ia: 0.2087 - loss: 0.9887 - mae: 0.7464 - rmse: 0.9884 - smape: 1.5514 - val_ia: 0.2594 - val_loss: 0.9065 - val_mae: 0.7128 - val_rmse: 0.8508 - val_smape: 1.7279

Epoch 59/128

240/240 - 5s - 21ms/step - ia: 0.2112 - loss: 0.9897 - mae: 0.7455 - rmse: 0.9889 - smape: 1.5461 - val_ia: 0.2596 - val_loss: 0.9044 - val_mae: 0.7117 - val_rmse: 0.8497 - val_smape: 1.7191

Epoch 60/128

240/240 - 5s - 23ms/step - ia: 0.2145 - loss: 0.9775 - mae: 0.7423 - rmse: 0.9830 - smape: 1.5438 - val_ia: 0.2597 - val_loss: 0.9022 - val_mae: 0.7104 - val_rmse: 0.8483 - val_smape: 1.7089

Epoch 61/128

240/240 - 5s - 21ms/step - ia: 0.2125 - loss: 0.9835 - mae: 0.7439 - rmse: 0.9849 - smape: 1.5477 - val_ia: 0.2599 - val_loss: 0.9001 - val_mae: 0.7093 - val_rmse: 0.8472 - val_smape: 1.7003

Epoch 62/128

240/240 - 4s - 17ms/step - ia: 0.2158 - loss: 0.9802 - mae: 0.7423 - rmse: 0.9852 - smape: 1.5433 - val_ia: 0.2601 - val_loss: 0.8979 - val_mae: 0.7082 - val_rmse: 0.8460 - val_smape: 1.6917

Epoch 63/128

240/240 - 4s - 16ms/step - ia: 0.2149 - loss: 0.9799 - mae: 0.7430 - rmse: 0.9845 - smape: 1.5432 - val_ia: 0.2604 - val_loss: 0.8958 - val_mae: 0.7076 - val_rmse: 0.8452 - val_smape: 1.6863

Epoch 64/128

240/240 - 4s - 17ms/step - ia: 0.2186 - loss: 0.9753 - mae: 0.7396 - rmse: 0.9824 - smape: 1.5375 - val_ia: 0.2608 - val_loss: 0.8938 - val_mae: 0.7073 - val_rmse: 0.8447 - val_smape: 1.6832

Epoch 65/128

240/240 - 5s - 21ms/step - ia: 0.2177 - loss: 0.9757 - mae: 0.7411 - rmse: 0.9813 - smape: 1.5408 - val_ia: 0.2609 - val_loss: 0.8915 - val_mae: 0.7060 - val_rmse: 0.8434 - val_smape: 1.6732

Epoch 66/128

240/240 - 4s - 16ms/step - ia: 0.2203 - loss: 0.9717 - mae: 0.7392 - rmse: 0.9798 - smape: 1.5351 - val_ia: 0.2614 - val_loss: 0.8895 - val_mae: 0.7060 - val_rmse: 0.8431 - val_smape: 1.6716

Epoch 67/128

240/240 - 4s - 16ms/step - ia: 0.2193 - loss: 0.9731 - mae: 0.7409 - rmse: 0.9802 - smape: 1.5358 - val_ia: 0.2615 - val_loss: 0.8868 - val_mae: 0.7039 - val_rmse: 0.8411 - val_smape: 1.6571

Epoch 68/128

240/240 - 4s - 17ms/step - ia: 0.2218 - loss: 0.9703 - mae: 0.7386 - rmse: 0.9793 - smape: 1.5303 - val_ia: 0.2618 - val_loss: 0.8847 - val_mae: 0.7034 - val_rmse: 0.8404 - val_smape: 1.6524

Epoch 69/128

240/240 - 5s - 21ms/step - ia: 0.2246 - loss: 0.9664 - mae: 0.7360 - rmse: 0.9773 - smape: 1.5204 - val_ia: 0.2623 - val_loss: 0.8825 - val_mae: 0.7031 - val_rmse: 0.8399 - val_smape: 1.6489

Epoch 70/128

240/240 - 4s - 17ms/step - ia: 0.2264 - loss: 0.9643 - mae: 0.7363 - rmse: 0.9754 - smape: 1.5249 - val_ia: 0.2626 - val_loss: 0.8800 - val_mae: 0.7018 - val_rmse: 0.8385 - val_smape: 1.6394

Epoch 71/128

240/240 - 5s - 21ms/step - ia: 0.2272 - loss: 0.9621 - mae: 0.7367 - rmse: 0.9752 - smape: 1.5240 - val_ia: 0.2628 - val_loss: 0.8774 - val_mae: 0.7003 - val_rmse: 0.8371 - val_smape: 1.6290

Epoch 72/128

240/240 - 4s - 16ms/step - ia: 0.2271 - loss: 0.9660 - mae: 0.7359 - rmse: 0.9764 - smape: 1.5194 - val_ia: 0.2632 - val_loss: 0.8750 - val_mae: 0.6992 - val_rmse: 0.8359 - val_smape: 1.6209

Epoch 73/128

240/240 - 4s - 17ms/step - ia: 0.2315 - loss: 0.9574 - mae: 0.7331 - rmse: 0.9723 - smape: 1.5148 - val_ia: 0.2636 - val_loss: 0.8725 - val_mae: 0.6984 - val_rmse: 0.8349 - val_smape: 1.6139

Epoch 74/128

240/240 - 4s - 16ms/step - ia: 0.2346 - loss: 0.9542 - mae: 0.7318 - rmse: 0.9715 - smape: 1.5105 - val_ia: 0.2641 - val_loss: 0.8699 - val_mae: 0.6972 - val_rmse: 0.8337 - val_smape: 1.6056

Epoch 75/128

240/240 - 4s - 16ms/step - ia: 0.2382 - loss: 0.9505 - mae: 0.7310 - rmse: 0.9689 - smape: 1.5083 - val_ia: 0.2643 - val_loss: 0.8671 - val_mae: 0.6953 - val_rmse: 0.8319 - val_smape: 1.5930

Epoch 76/128

240/240 - 4s - 17ms/step - ia: 0.2385 - loss: 0.9520 - mae: 0.7313 - rmse: 0.9696 - smape: 1.5047 - val_ia: 0.2648 - val_loss: 0.8645 - val_mae: 0.6942 - val_rmse: 0.8307 - val_smape: 1.5849

Epoch 77/128

240/240 - 4s - 17ms/step - ia: 0.2402 - loss: 0.9499 - mae: 0.7302 - rmse: 0.9701 - smape: 1.5021 - val_ia: 0.2654 - val_loss: 0.8621 - val_mae: 0.6936 - val_rmse: 0.8299 - val_smape: 1.5793

Epoch 78/128

240/240 - 4s - 16ms/step - ia: 0.2440 - loss: 0.9441 - mae: 0.7277 - rmse: 0.9648 - smape: 1.4984 - val_ia: 0.2660 - val_loss: 0.8596 - val_mae: 0.6928 - val_rmse: 0.8290 - val_smape: 1.5731

Epoch 79/128

240/240 - 5s - 21ms/step - ia: 0.2471 - loss: 0.9391 - mae: 0.7266 - rmse: 0.9640 - smape: 1.4948 - val_ia: 0.2666 - val_loss: 0.8571 - val_mae: 0.6920 - val_rmse: 0.8281 - val_smape: 1.5671

Epoch 80/128

240/240 - 4s - 16ms/step - ia: 0.2471 - loss: 0.9457 - mae: 0.7280 - rmse: 0.9671 - smape: 1.4952 - val_ia: 0.2672 - val_loss: 0.8546 - val_mae: 0.6911 - val_rmse: 0.8271 - val_smape: 1.5601

Epoch 81/128

240/240 - 4s - 17ms/step - ia: 0.2512 - loss: 0.9379 - mae: 0.7263 - rmse: 0.9633 - smape: 1.4889 - val_ia: 0.2679 - val_loss: 0.8521 - val_mae: 0.6907 - val_rmse: 0.8265 - val_smape: 1.5555

Epoch 82/128

240/240 - 4s - 16ms/step - ia: 0.2506 - loss: 0.9405 - mae: 0.7267 - rmse: 0.9634 - smape: 1.4883 - val_ia: 0.2684 - val_loss: 0.8495 - val_mae: 0.6892 - val_rmse: 0.8251 - val_smape: 1.5457

Epoch 83/128

240/240 - 5s - 20ms/step - ia: 0.2550 - loss: 0.9378 - mae: 0.7252 - rmse: 0.9631 - smape: 1.4814 - val_ia: 0.2688 - val_loss: 0.8468 - val_mae: 0.6875 - val_rmse: 0.8235 - val_smape: 1.5347

Epoch 84/128

240/240 - 3s - 13ms/step - ia: 0.2595 - loss: 0.9309 - mae: 0.7233 - rmse: 0.9592 - smape: 1.4773 - val_ia: 0.2696 - val_loss: 0.8446 - val_mae: 0.6873 - val_rmse: 0.8231 - val_smape: 1.5318

Epoch 85/128

240/240 - 3s - 13ms/step - ia: 0.2618 - loss: 0.9277 - mae: 0.7209 - rmse: 0.9574 - smape: 1.4696 - val_ia: 0.2701 - val_loss: 0.8419 - val_mae: 0.6855 - val_rmse: 0.8215 - val_smape: 1.5205

Epoch 86/128

240/240 - 4s - 16ms/step - ia: 0.2623 - loss: 0.9318 - mae: 0.7232 - rmse: 0.9591 - smape: 1.4722 - val_ia: 0.2706 - val_loss: 0.8394 - val_mae: 0.6840 - val_rmse: 0.8201 - val_smape: 1.5108

Epoch 87/128

240/240 - 5s - 22ms/step - ia: 0.2664 - loss: 0.9251 - mae: 0.7203 - rmse: 0.9572 - smape: 1.4668 - val_ia: 0.2713 - val_loss: 0.8371 - val_mae: 0.6833 - val_rmse: 0.8194 - val_smape: 1.5054

Epoch 88/128

240/240 - 4s - 16ms/step - ia: 0.2678 - loss: 0.9240 - mae: 0.7204 - rmse: 0.9566 - smape: 1.4629 - val_ia: 0.2719 - val_loss: 0.8345 - val_mae: 0.6820 - val_rmse: 0.8181 - val_smape: 1.4965

Epoch 89/128

240/240 - 5s - 22ms/step - ia: 0.2725 - loss: 0.9174 - mae: 0.7180 - rmse: 0.9523 - smape: 1.4561 - val_ia: 0.2726 - val_loss: 0.8319 - val_mae: 0.6807 - val_rmse: 0.8169 - val_smape: 1.4881

Epoch 90/128

240/240 - 5s - 21ms/step - ia: 0.2747 - loss: 0.9215 - mae: 0.7185 - rmse: 0.9543 - smape: 1.4540 - val_ia: 0.2732 - val_loss: 0.8297 - val_mae: 0.6797 - val_rmse: 0.8159 - val_smape: 1.4812

Epoch 91/128

240/240 - 5s - 22ms/step - ia: 0.2777 - loss: 0.9192 - mae: 0.7163 - rmse: 0.9528 - smape: 1.4463 - val_ia: 0.2740 - val_loss: 0.8276 - val_mae: 0.6792 - val_rmse: 0.8154 - val_smape: 1.4766

Epoch 92/128

240/240 - 4s - 15ms/step - ia: 0.2797 - loss: 0.9174 - mae: 0.7172 - rmse: 0.9529 - smape: 1.4456 - val_ia: 0.2747 - val_loss: 0.8255 - val_mae: 0.6784 - val_rmse: 0.8146 - val_smape: 1.4704

Epoch 93/128

240/240 - 5s - 23ms/step - ia: 0.2821 - loss: 0.9120 - mae: 0.7161 - rmse: 0.9501 - smape: 1.4439 - val_ia: 0.2754 - val_loss: 0.8233 - val_mae: 0.6772 - val_rmse: 0.8136 - val_smape: 1.4629

Epoch 94/128

240/240 - 4s - 16ms/step - ia: 0.2856 - loss: 0.9127 - mae: 0.7146 - rmse: 0.9506 - smape: 1.4326 - val_ia: 0.2761 - val_loss: 0.8213 - val_mae: 0.6762 - val_rmse: 0.8126 - val_smape: 1.4560

Epoch 95/128

240/240 - 5s - 22ms/step - ia: 0.2882 - loss: 0.9101 - mae: 0.7148 - rmse: 0.9481 - smape: 1.4334 - val_ia: 0.2769 - val_loss: 0.8192 - val_mae: 0.6751 - val_rmse: 0.8117 - val_smape: 1.4491

Epoch 96/128

240/240 - 5s - 22ms/step - ia: 0.2922 - loss: 0.9060 - mae: 0.7112 - rmse: 0.9456 - smape: 1.4246 - val_ia: 0.2777 - val_loss: 0.8173 - val_mae: 0.6745 - val_rmse: 0.8111 - val_smape: 1.4439

Epoch 97/128

240/240 - 4s - 16ms/step - ia: 0.2942 - loss: 0.9041 - mae: 0.7120 - rmse: 0.9455 - smape: 1.4268 - val_ia: 0.2783 - val_loss: 0.8153 - val_mae: 0.6728 - val_rmse: 0.8097 - val_smape: 1.4345

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 6s - 24ms/step - ia: 0.3798 - loss: 0.8359 - mae: 0.6695 - rmse: 0.9070 - smape: 1.2914 - val_ia: 0.3429 - val_loss: 0.7505 - val_mae: 0.6437 - val_rmse: 0.7897 - val_smape: 1.2657

Epoch 2/128

240/240 - 2s - 8ms/step - ia: 0.4024 - loss: 0.8134 - mae: 0.6557 - rmse: 0.8950 - smape: 1.2538 - val_ia: 0.3009 - val_loss: 0.7726 - val_mae: 0.6647 - val_rmse: 0.8040 - val_smape: 1.3472

Epoch 3/128

240/240 - 3s - 11ms/step - ia: 0.4023 - loss: 0.8025 - mae: 0.6552 - rmse: 0.8909 - smape: 1.2576 - val_ia: 0.3347 - val_loss: 0.7487 - val_mae: 0.6346 - val_rmse: 0.7845 - val_smape: 1.2416

Epoch 4/128

240/240 - 3s - 11ms/step - ia: 0.4082 - loss: 0.7932 - mae: 0.6512 - rmse: 0.8868 - smape: 1.2522 - val_ia: 0.3256 - val_loss: 0.7568 - val_mae: 0.6340 - val_rmse: 0.7820 - val_smape: 1.2387

Epoch 5/128

240/240 - 2s - 8ms/step - ia: 0.4171 - loss: 0.7772 - mae: 0.6448 - rmse: 0.8766 - smape: 1.2406 - val_ia: 0.3629 - val_loss: 0.7879 - val_mae: 0.6293 - val_rmse: 0.7997 - val_smape: 1.1633

Epoch 6/128

240/240 - 2s - 9ms/step - ia: 0.4295 - loss: 0.7670 - mae: 0.6379 - rmse: 0.8701 - smape: 1.2199 - val_ia: 0.3299 - val_loss: 0.7989 - val_mae: 0.6706 - val_rmse: 0.8204 - val_smape: 1.3128

Epoch 7/128

240/240 - 2s - 8ms/step - ia: 0.4319 - loss: 0.7582 - mae: 0.6347 - rmse: 0.8651 - smape: 1.2184 - val_ia: 0.3422 - val_loss: 0.7322 - val_mae: 0.6239 - val_rmse: 0.7743 - val_smape: 1.2270

Epoch 8/128

240/240 - 2s - 8ms/step - ia: 0.4415 - loss: 0.7413 - mae: 0.6285 - rmse: 0.8551 - smape: 1.2109 - val_ia: 0.3542 - val_loss: 0.7833 - val_mae: 0.6391 - val_rmse: 0.8046 - val_smape: 1.2060

Epoch 9/128

240/240 - 3s - 11ms/step - ia: 0.4488 - loss: 0.7295 - mae: 0.6232 - rmse: 0.8488 - smape: 1.2020 - val_ia: 0.3610 - val_loss: 0.7834 - val_mae: 0.6441 - val_rmse: 0.8079 - val_smape: 1.2039

Epoch 10/128

240/240 - 3s - 11ms/step - ia: 0.2735 - loss: 2837562624.0000 - mae: 8080.6011 - rmse: 17316.3789 - smape: 1.4755 - val_ia: 8.7887e-06 - val_loss: 16322461696.0000 - val_mae: 72046.3672 - val_rmse: 123937.0469 - val_smape: 1.9998

Epoch 11/128

240/240 - 3s - 10ms/step - ia: 8.2379e-07 - loss: 48070960087040.0000 - mae: 2789699.5000 - rmse: 5466789.5000 - smape: 1.9999 - val_ia: 3.9520e-06 - val_loss: 78305591296.0000 - val_mae: 161453.7969 - val_rmse: 270168.9375 - val_smape: 1.9998

Epoch 12/128

240/240 - 3s - 11ms/step - ia: 8.4126e-05 - loss: 15142970368.0000 - mae: 38922.0742 - rmse: 72732.2812 - smape: 1.9968 - val_ia: 3.8854e-04 - val_loss: 11525943.0000 - val_mae: 1761.6075 - val_rmse: 3216.9863 - val_smape: 1.9895

Epoch 13/128

240/240 - 2s - 10ms/step - ia: 0.0088 - loss: 2746141.7500 - mae: 500.4616 - rmse: 1033.5431 - smape: 1.9177 - val_ia: 0.0615 - val_loss: 248.8344 - val_mae: 8.6813 - val_rmse: 15.1601 - val_smape: 1.7056

Epoch 14/128

240/240 - 2s - 8ms/step - ia: 0.1718 - loss: 107.5917 - mae: 3.3986 - rmse: 6.4885 - smape: 1.5927 - val_ia: 0.2527 - val_loss: 1.2155 - val_mae: 0.9260 - val_rmse: 1.0608 - val_smape: 1.6035

Epoch 15/128

240/240 - 3s - 11ms/step - ia: 0.2271 - loss: 1.2473 - mae: 0.9244 - rmse: 1.1140 - smape: 1.5639 - val_ia: 0.2540 - val_loss: 1.1933 - val_mae: 0.9155 - val_rmse: 1.0482 - val_smape: 1.5977

Epoch 16/128

240/240 - 2s - 6ms/step - ia: 0.2268 - loss: 1.2439 - mae: 0.9222 - rmse: 1.1119 - smape: 1.5631 - val_ia: 0.2522 - val_loss: 1.1937 - val_mae: 0.9170 - val_rmse: 1.0490 - val_smape: 1.5966

Epoch 17/128

240/240 - 2s - 7ms/step - ia: 0.2275 - loss: 1.2584 - mae: 0.9269 - rmse: 1.1187 - smape: 1.5633 - val_ia: 0.2535 - val_loss: 1.2040 - val_mae: 0.9188 - val_rmse: 1.0535 - val_smape: 1.6020

Epoch 18/128

240/240 - 2s - 7ms/step - ia: 0.2289 - loss: 1.2729 - mae: 0.9296 - rmse: 1.1238 - smape: 1.5606 - val_ia: 0.2503 - val_loss: 1.2292 - val_mae: 0.9331 - val_rmse: 1.0665 - val_smape: 1.6001

Epoch 19/128

240/240 - 2s - 7ms/step - ia: 0.2279 - loss: 1.2815 - mae: 0.9341 - rmse: 1.1289 - smape: 1.5639 - val_ia: 0.2552 - val_loss: 1.2443 - val_mae: 0.9319 - val_rmse: 1.0749 - val_smape: 1.5951

Epoch 20/128

240/240 - 2s - 6ms/step - ia: 0.2303 - loss: 1.3183 - mae: 0.9426 - rmse: 1.1443 - smape: 1.5614 - val_ia: 0.2533 - val_loss: 1.2431 - val_mae: 0.9356 - val_rmse: 1.0720 - val_smape: 1.6023

Epoch 21/128

240/240 - 2s - 6ms/step - ia: 0.2289 - loss: 1.6446 - mae: 1.0026 - rmse: 1.2681 - smape: 1.5629 - val_ia: 0.2448 - val_loss: 1.3801 - val_mae: 0.9846 - val_rmse: 1.1399 - val_smape: 1.6095

Epoch 22/128

240/240 - 2s - 7ms/step - ia: 0.2317 - loss: 1.9942 - mae: 1.0601 - rmse: 1.3875 - smape: 1.5575 - val_ia: 0.2494 - val_loss: 1.4747 - val_mae: 0.9823 - val_rmse: 1.1784 - val_smape: 1.5743

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 29s 216ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 36/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 43/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

Epoch 1/128

 58%|█████▊    | 7/12 [2:25:45<1:10:13, 842.79s/trial, best loss: 0.7446180315174813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

3830/3830 - 43s - 11ms/step - ia: 0.3801 - loss: 0.8207 - mae: 0.6645 - rmse: 0.8481 - smape: 1.2900 - val_ia: 0.2039 - val_loss: 0.7661 - val_mae: 0.6421 - val_rmse: 0.6830 - val_smape: 1.2500

Epoch 2/128

3830/3830 - 36s - 9ms/step - ia: 0.4095 - loss: 0.7776 - mae: 0.6426 - rmse: 0.8231 - smape: 1.2310 - val_ia: 0.2059 - val_loss: 0.7590 - val_mae: 0.6382 - val_rmse: 0.6820 - val_smape: 1.2574

Epoch 3/128

3830/3830 - 34s - 9ms/step - ia: 0.4225 - loss: 0.7549 - mae: 0.6318 - rmse: 0.8118 - smape: 1.2140 - val_ia: 0.2065 - val_loss: 0.7514 - val_mae: 0.6376 - val_rmse: 0.6826 - val_smape: 1.2500

Epoch 4/128

3830/3830 - 38s - 10ms/step - ia: 0.4333 - loss: 0.7315 - mae: 0.6224 - rmse: 0.7992 - smape: 1.1965 - val_ia: 0.2047 - val_loss: 0.7664 - val_mae: 0.6408 - val_rmse: 0.6862 - val_smape: 1.2377

Epoch 5/128

3830/3830 - 38s - 10ms/step - ia: 0.4435 - loss: 0.7085 - mae: 0.6128 - rmse: 0.7853 - smape: 1.1778 - val_ia: 0.2072 - val_loss: 0.7983 - val_mae: 0.6483 - val_rmse: 0.6972 - val_smape: 1.2115

Epoch 6/128

3830/3830 - 41s - 11ms/step - ia: 0.4537 - loss: 0.6858 - mae: 0.6026 - rmse: 0.7728 - smape: 1.1708 - val_ia: 0.2008 - val_loss: 0.8009 - val_mae: 0.6553 - val_rmse: 0.7013 - val_smape: 1.2563

Epoch 7/128

3830/3830 - 36s - 9ms/step - ia: 0.4636 - loss: 0.6590 - mae: 0.5910 - rmse: 0.7581 - smape: 1.1565 - val_ia: 0.1990 - val_loss: 0.8715 - val_mae: 0.6719 - val_rmse: 0.7215 - val_smape: 1.2913

Epoch 8/128

3830/3830 - 35s - 9ms/step - ia: 0.4742 - loss: 0.6302 - mae: 0.5788 - rmse: 0.7426 - smape: 1.1426 - val_ia: 0.1987 - val_loss: 0.9106 - val_mae: 0.6844 - val_rmse: 0.7358 - val_smape: 1.2634

Epoch 9/128

3830/3830 - 35s - 9ms/step - ia: 0.4852 - loss: 0.5994 - mae: 0.5662 - rmse: 0.7242 - smape: 1.1229 - val_ia: 0.2027 - val_loss: 0.9372 - val_mae: 0.6733 - val_rmse: 0.7285 - val_smape: 1.1986

Epoch 10/128

3830/3830 - 34s - 9ms/step - ia: 0.4940 - loss: 0.5840 - mae: 0.5593 - rmse: 0.7152 - smape: 1.1156 - val_ia: 0.1972 - val_loss: 0.9041 - val_mae: 0.6761 - val_rmse: 0.7287 - val_smape: 1.2509

Epoch 11/128

3830/3830 - 34s - 9ms/step - ia: 0.5025 - loss: 0.5618 - mae: 0.5492 - rmse: 0.7011 - smape: 1.0999 - val_ia: 0.2006 - val_loss: 0.9755 - val_mae: 0.6904 - val_rmse: 0.7443 - val_smape: 1.2941

Epoch 12/128

3830/3830 - 40s - 11ms/step - ia: 0.5136 - loss: 0.5435 - mae: 0.5388 - rmse: 0.6891 - smape: 1.0818 - val_ia: 0.2003 - val_loss: 0.8745 - val_mae: 0.6646 - val_rmse: 0.7168 - val_smape: 1.2645

Epoch 13/128

3830/3830 - 33s - 9ms/step - ia: 0.5218 - loss: 0.5180 - mae: 0.5297 - rmse: 0.6745 - smape: 1.0680 - val_ia: 0.2025 - val_loss: 0.9398 - val_mae: 0.6869 - val_rmse: 0.7431 - val_smape: 1.2418

Epoch 14/128

3830/3830 - 41s - 11ms/step - ia: 0.5330 - loss: 0.4982 - mae: 0.5195 - rmse: 0.6606 - smape: 1.0514 - val_ia: 0.1995 - val_loss: 0.9921 - val_mae: 0.6940 - val_rmse: 0.7515 - val_smape: 1.2458

Epoch 15/128

3830/3830 - 33s - 9ms/step - ia: 0.5419 - loss: 0.4808 - mae: 0.5094 - rmse: 0.6492 - smape: 1.0323 - val_ia: 0.1959 - val_loss: 1.0413 - val_mae: 0.7110 - val_rmse: 0.7717 - val_smape: 1.2481

Epoch 16/128

3830/3830 - 33s - 9ms/step - ia: 0.5482 - loss: 0.4666 - mae: 0.5020 - rmse: 0.6391 - smape: 1.0204 - val_ia: 0.1926 - val_loss: 1.0585 - val_mae: 0.7283 - val_rmse: 0.7925 - val_smape: 1.2829

Epoch 17/128

3830/3830 - 34s - 9ms/step - ia: 0.5540 - loss: 0.4534 - mae: 0.4968 - rmse: 0.6325 - smape: 1.0119 - val_ia: 0.1959 - val_loss: 1.0902 - val_mae: 0.7209 - val_rmse: 0.7829 - val_smape: 1.2551

Epoch 18/128

3830/3830 - 35s - 9ms/step - ia: 0.5622 - loss: 0.4392 - mae: 0.4881 - rmse: 0.6217 - smape: 0.9989 - val_ia: 0.2027 - val_loss: 0.9961 - val_mae: 0.6929 - val_rmse: 0.7519 - val_smape: 1.2233

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 3.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:57 867ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 78/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
117/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

Epoch 1/128

 67%|██████▋   | 8/12 [2:36:41<52:14, 783.53s/trial, best loss: 0.7446180315174813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

240/240 - 4s - 15ms/step - ia: 0.3403 - loss: 0.9228 - mae: 0.7158 - rmse: 0.9540 - smape: 1.3710 - val_ia: 0.3045 - val_loss: 0.7886 - val_mae: 0.6673 - val_rmse: 0.8074 - val_smape: 1.3811

Epoch 2/128

240/240 - 1s - 6ms/step - ia: 0.3544 - loss: 0.8459 - mae: 0.6799 - rmse: 0.9140 - smape: 1.3470 - val_ia: 0.3069 - val_loss: 0.7605 - val_mae: 0.6465 - val_rmse: 0.7878 - val_smape: 1.3022

Epoch 3/128

240/240 - 2s - 6ms/step - ia: 0.3670 - loss: 0.8288 - mae: 0.6706 - rmse: 0.9047 - smape: 1.3280 - val_ia: 0.3171 - val_loss: 0.7552 - val_mae: 0.6449 - val_rmse: 0.7883 - val_smape: 1.2984

Epoch 4/128

240/240 - 1s - 6ms/step - ia: 0.3753 - loss: 0.8219 - mae: 0.6669 - rmse: 0.9021 - smape: 1.3171 - val_ia: 0.3161 - val_loss: 0.7518 - val_mae: 0.6434 - val_rmse: 0.7862 - val_smape: 1.2936

Epoch 5/128

240/240 - 1s - 4ms/step - ia: 0.3799 - loss: 0.8149 - mae: 0.6631 - rmse: 0.8976 - smape: 1.3072 - val_ia: 0.3201 - val_loss: 0.7544 - val_mae: 0.6446 - val_rmse: 0.7882 - val_smape: 1.2998

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.3841 - loss: 0.8122 - mae: 0.6603 - rmse: 0.8962 - smape: 1.2980 - val_ia: 0.3261 - val_loss: 0.7558 - val_mae: 0.6445 - val_rmse: 0.7905 - val_smape: 1.2839

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.3895 - loss: 0.8083 - mae: 0.6588 - rmse: 0.8936 - smape: 1.2917 - val_ia: 0.3276 - val_loss: 0.7512 - val_mae: 0.6386 - val_rmse: 0.7863 - val_smape: 1.2593

Epoch 8/128

240/240 - 1s - 3ms/step - ia: 0.3892 - loss: 0.8066 - mae: 0.6585 - rmse: 0.8930 - smape: 1.2904 - val_ia: 0.3293 - val_loss: 0.7546 - val_mae: 0.6411 - val_rmse: 0.7883 - val_smape: 1.2784

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.3917 - loss: 0.8035 - mae: 0.6563 - rmse: 0.8899 - smape: 1.2872 - val_ia: 0.3326 - val_loss: 0.7479 - val_mae: 0.6386 - val_rmse: 0.7851 - val_smape: 1.2663

Epoch 10/128

240/240 - 1s - 3ms/step - ia: 0.3945 - loss: 0.7986 - mae: 0.6547 - rmse: 0.8888 - smape: 1.2844 - val_ia: 0.3304 - val_loss: 0.7517 - val_mae: 0.6405 - val_rmse: 0.7872 - val_smape: 1.2654

Epoch 11/128

240/240 - 1s - 5ms/step - ia: 0.3944 - loss: 0.7958 - mae: 0.6538 - rmse: 0.8867 - smape: 1.2837 - val_ia: 0.3367 - val_loss: 0.7580 - val_mae: 0.6432 - val_rmse: 0.7930 - val_smape: 1.2562

Epoch 12/128

240/240 - 1s - 6ms/step - ia: 0.3973 - loss: 0.7952 - mae: 0.6539 - rmse: 0.8865 - smape: 1.2823 - val_ia: 0.3371 - val_loss: 0.7517 - val_mae: 0.6387 - val_rmse: 0.7866 - val_smape: 1.2552

Epoch 13/128

240/240 - 1s - 6ms/step - ia: 0.3999 - loss: 0.7931 - mae: 0.6510 - rmse: 0.8861 - smape: 1.2751 - val_ia: 0.3339 - val_loss: 0.7540 - val_mae: 0.6427 - val_rmse: 0.7885 - val_smape: 1.2757

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.4005 - loss: 0.7882 - mae: 0.6507 - rmse: 0.8829 - smape: 1.2761 - val_ia: 0.3349 - val_loss: 0.7517 - val_mae: 0.6424 - val_rmse: 0.7884 - val_smape: 1.2634

Epoch 15/128

240/240 - 3s - 11ms/step - ia: 0.4014 - loss: 0.7881 - mae: 0.6499 - rmse: 0.8830 - smape: 1.2759 - val_ia: 0.3419 - val_loss: 0.7723 - val_mae: 0.6452 - val_rmse: 0.7977 - val_smape: 1.2539

Epoch 16/128

240/240 - 3s - 11ms/step - ia: 0.4022 - loss: 0.7883 - mae: 0.6493 - rmse: 0.8827 - smape: 1.2738 - val_ia: 0.3407 - val_loss: 0.7580 - val_mae: 0.6429 - val_rmse: 0.7920 - val_smape: 1.2500

Epoch 17/128

240/240 - 2s - 7ms/step - ia: 0.4063 - loss: 0.7806 - mae: 0.6472 - rmse: 0.8781 - smape: 1.2699 - val_ia: 0.3459 - val_loss: 0.7640 - val_mae: 0.6415 - val_rmse: 0.7933 - val_smape: 1.2345

Epoch 18/128

240/240 - 1s - 6ms/step - ia: 0.4088 - loss: 0.7789 - mae: 0.6463 - rmse: 0.8778 - smape: 1.2655 - val_ia: 0.3354 - val_loss: 0.7643 - val_mae: 0.6436 - val_rmse: 0.7917 - val_smape: 1.2528

Epoch 19/128

240/240 - 1s - 5ms/step - ia: 0.4071 - loss: 0.7791 - mae: 0.6457 - rmse: 0.8780 - smape: 1.2646 - val_ia: 0.3450 - val_loss: 0.7786 - val_mae: 0.6465 - val_rmse: 0.7997 - val_smape: 1.2405

Epoch 20/128

240/240 - 1s - 6ms/step - ia: 0.4069 - loss: 0.7787 - mae: 0.6467 - rmse: 0.8778 - smape: 1.2697 - val_ia: 0.3431 - val_loss: 0.7635 - val_mae: 0.6466 - val_rmse: 0.7953 - val_smape: 1.2473

Epoch 21/128

240/240 - 1s - 6ms/step - ia: 0.4104 - loss: 0.7763 - mae: 0.6445 - rmse: 0.8755 - smape: 1.2625 - val_ia: 0.3393 - val_loss: 0.7459 - val_mae: 0.6379 - val_rmse: 0.7834 - val_smape: 1.2505

Epoch 22/128

240/240 - 1s - 6ms/step - ia: 0.4105 - loss: 0.7748 - mae: 0.6452 - rmse: 0.8761 - smape: 1.2626 - val_ia: 0.3411 - val_loss: 0.7712 - val_mae: 0.6463 - val_rmse: 0.7966 - val_smape: 1.2501

Epoch 23/128

240/240 - 1s - 5ms/step - ia: 0.4104 - loss: 0.7764 - mae: 0.6452 - rmse: 0.8764 - smape: 1.2625 - val_ia: 0.3405 - val_loss: 0.7720 - val_mae: 0.6431 - val_rmse: 0.7940 - val_smape: 1.2452

Epoch 24/128

240/240 - 1s - 6ms/step - ia: 0.4100 - loss: 0.7743 - mae: 0.6452 - rmse: 0.8754 - smape: 1.2628 - val_ia: 0.3394 - val_loss: 0.7614 - val_mae: 0.6390 - val_rmse: 0.7876 - val_smape: 1.2443

Epoch 25/128

240/240 - 1s - 6ms/step - ia: 0.4119 - loss: 0.7692 - mae: 0.6424 - rmse: 0.8730 - smape: 1.2621 - val_ia: 0.3401 - val_loss: 0.7657 - val_mae: 0.6410 - val_rmse: 0.7902 - val_smape: 1.2438

Epoch 26/128

240/240 - 1s - 6ms/step - ia: 0.4128 - loss: 0.7703 - mae: 0.6431 - rmse: 0.8722 - smape: 1.2612 - val_ia: 0.3432 - val_loss: 0.7613 - val_mae: 0.6374 - val_rmse: 0.7875 - val_smape: 1.2368

Epoch 27/128

240/240 - 1s - 5ms/step - ia: 0.4128 - loss: 0.7700 - mae: 0.6425 - rmse: 0.8718 - smape: 1.2591 - val_ia: 0.3461 - val_loss: 0.7687 - val_mae: 0.6411 - val_rmse: 0.7922 - val_smape: 1.2324

Epoch 28/128

240/240 - 1s - 3ms/step - ia: 0.4153 - loss: 0.7661 - mae: 0.6414 - rmse: 0.8714 - smape: 1.2557 - val_ia: 0.3415 - val_loss: 0.7692 - val_mae: 0.6415 - val_rmse: 0.7917 - val_smape: 1.2396

Epoch 29/128

240/240 - 1s - 3ms/step - ia: 0.4161 - loss: 0.7653 - mae: 0.6406 - rmse: 0.8696 - smape: 1.2540 - val_ia: 0.3544 - val_loss: 0.8086 - val_mae: 0.6496 - val_rmse: 0.8110 - val_smape: 1.2273

Epoch 30/128

240/240 - 1s - 3ms/step - ia: 0.4150 - loss: 0.7675 - mae: 0.6419 - rmse: 0.8715 - smape: 1.2542 - val_ia: 0.3498 - val_loss: 0.7866 - val_mae: 0.6431 - val_rmse: 0.7988 - val_smape: 1.2288

Epoch 31/128

240/240 - 1s - 3ms/step - ia: 0.4182 - loss: 0.7615 - mae: 0.6388 - rmse: 0.8678 - smape: 1.2513 - val_ia: 0.3471 - val_loss: 0.7800 - val_mae: 0.6388 - val_rmse: 0.7948 - val_smape: 1.2296

Epoch 32/128

240/240 - 1s - 3ms/step - ia: 0.4183 - loss: 0.7605 - mae: 0.6399 - rmse: 0.8675 - smape: 1.2530 - val_ia: 0.3471 - val_loss: 0.7764 - val_mae: 0.6448 - val_rmse: 0.7978 - val_smape: 1.2349

Epoch 33/128

240/240 - 1s - 5ms/step - ia: 0.4200 - loss: 0.7605 - mae: 0.6392 - rmse: 0.8673 - smape: 1.2463 - val_ia: 0.3424 - val_loss: 0.7553 - val_mae: 0.6384 - val_rmse: 0.7859 - val_smape: 1.2493

Epoch 34/128

240/240 - 1s - 6ms/step - ia: 0.4185 - loss: 0.7630 - mae: 0.6387 - rmse: 0.8689 - smape: 1.2482 - val_ia: 0.3457 - val_loss: 0.7531 - val_mae: 0.6398 - val_rmse: 0.7884 - val_smape: 1.2458

Epoch 35/128

240/240 - 2s - 10ms/step - ia: 0.4183 - loss: 0.7619 - mae: 0.6398 - rmse: 0.8678 - smape: 1.2514 - val_ia: 0.3472 - val_loss: 0.7647 - val_mae: 0.6459 - val_rmse: 0.7954 - val_smape: 1.2621

Epoch 36/128

240/240 - 2s - 6ms/step - ia: 0.4207 - loss: 0.7600 - mae: 0.6384 - rmse: 0.8667 - smape: 1.2488 - val_ia: 0.3473 - val_loss: 0.7755 - val_mae: 0.6441 - val_rmse: 0.7957 - val_smape: 1.2407

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:09 518ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 35/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 47/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
112/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

 75%|███████▌  | 9/12 [2:37:34<27:44, 554.97s/trial, best loss: 0.7446180315174813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 35s - 18ms/step - ia: 0.2649 - loss: 1.0355 - mae: 0.7633 - rmse: 0.9802 - smape: 1.4987 - val_ia: 0.2289 - val_loss: 0.8168 - val_mae: 0.6784 - val_rmse: 0.7395 - val_smape: 1.4504

Epoch 2/128

1915/1915 - 26s - 14ms/step - ia: 0.3468 - loss: 0.8892 - mae: 0.7010 - rmse: 0.9097 - smape: 1.3451 - val_ia: 0.2349 - val_loss: 0.7960 - val_mae: 0.6743 - val_rmse: 0.7390 - val_smape: 1.3598

Epoch 3/128

1915/1915 - 24s - 13ms/step - ia: 0.3627 - loss: 0.8581 - mae: 0.6862 - rmse: 0.8941 - smape: 1.3195 - val_ia: 0.2439 - val_loss: 0.7766 - val_mae: 0.6493 - val_rmse: 0.7155 - val_smape: 1.2839

Epoch 4/128

1915/1915 - 25s - 13ms/step - ia: 0.3631 - loss: 0.8501 - mae: 0.6830 - rmse: 0.8894 - smape: 1.3170 - val_ia: 0.2436 - val_loss: 0.7747 - val_mae: 0.6515 - val_rmse: 0.7185 - val_smape: 1.2853

Epoch 5/128

1915/1915 - 24s - 12ms/step - ia: 0.3650 - loss: 0.8442 - mae: 0.6798 - rmse: 0.8863 - smape: 1.3086 - val_ia: 0.2420 - val_loss: 0.7769 - val_mae: 0.6586 - val_rmse: 0.7260 - val_smape: 1.2992

Epoch 6/128

1915/1915 - 42s - 22ms/step - ia: 0.3681 - loss: 0.8393 - mae: 0.6765 - rmse: 0.8845 - smape: 1.3063 - val_ia: 0.2440 - val_loss: 0.7695 - val_mae: 0.6510 - val_rmse: 0.7185 - val_smape: 1.2829

Epoch 7/128

1915/1915 - 39s - 21ms/step - ia: 0.3701 - loss: 0.8359 - mae: 0.6758 - rmse: 0.8835 - smape: 1.3038 - val_ia: 0.2430 - val_loss: 0.7700 - val_mae: 0.6535 - val_rmse: 0.7209 - val_smape: 1.2936

Epoch 8/128

1915/1915 - 23s - 12ms/step - ia: 0.3749 - loss: 0.8305 - mae: 0.6730 - rmse: 0.8796 - smape: 1.2998 - val_ia: 0.2458 - val_loss: 0.7653 - val_mae: 0.6360 - val_rmse: 0.7022 - val_smape: 1.2464

Epoch 9/128

1915/1915 - 25s - 13ms/step - ia: 0.3739 - loss: 0.8269 - mae: 0.6712 - rmse: 0.8775 - smape: 1.3021 - val_ia: 0.2445 - val_loss: 0.7626 - val_mae: 0.6459 - val_rmse: 0.7131 - val_smape: 1.2823

Epoch 10/128

1915/1915 - 28s - 15ms/step - ia: 0.3786 - loss: 0.8249 - mae: 0.6687 - rmse: 0.8756 - smape: 1.2959 - val_ia: 0.2464 - val_loss: 0.7602 - val_mae: 0.6406 - val_rmse: 0.7097 - val_smape: 1.2514

Epoch 11/128

1915/1915 - 34s - 18ms/step - ia: 0.3805 - loss: 0.8235 - mae: 0.6680 - rmse: 0.8758 - smape: 1.2887 - val_ia: 0.2456 - val_loss: 0.7588 - val_mae: 0.6445 - val_rmse: 0.7126 - val_smape: 1.2725

Epoch 12/128

1915/1915 - 16s - 8ms/step - ia: 0.3801 - loss: 0.8223 - mae: 0.6680 - rmse: 0.8740 - smape: 1.2922 - val_ia: 0.2463 - val_loss: 0.7587 - val_mae: 0.6387 - val_rmse: 0.7077 - val_smape: 1.2509

Epoch 13/128

1915/1915 - 16s - 8ms/step - ia: 0.3843 - loss: 0.8200 - mae: 0.6666 - rmse: 0.8732 - smape: 1.2870 - val_ia: 0.2454 - val_loss: 0.7568 - val_mae: 0.6401 - val_rmse: 0.7067 - val_smape: 1.2752

Epoch 14/128

1915/1915 - 16s - 8ms/step - ia: 0.3811 - loss: 0.8167 - mae: 0.6653 - rmse: 0.8714 - smape: 1.2876 - val_ia: 0.2461 - val_loss: 0.7648 - val_mae: 0.6459 - val_rmse: 0.7154 - val_smape: 1.2618

Epoch 15/128

1915/1915 - 16s - 8ms/step - ia: 0.3829 - loss: 0.8166 - mae: 0.6652 - rmse: 0.8719 - smape: 1.2835 - val_ia: 0.2478 - val_loss: 0.7573 - val_mae: 0.6342 - val_rmse: 0.7041 - val_smape: 1.2272

Epoch 16/128

1915/1915 - 16s - 8ms/step - ia: 0.3852 - loss: 0.8143 - mae: 0.6640 - rmse: 0.8699 - smape: 1.2837 - val_ia: 0.2452 - val_loss: 0.7629 - val_mae: 0.6468 - val_rmse: 0.7166 - val_smape: 1.2679

Epoch 17/128

1915/1915 - 17s - 9ms/step - ia: 0.3861 - loss: 0.8119 - mae: 0.6633 - rmse: 0.8692 - smape: 1.2821 - val_ia: 0.2469 - val_loss: 0.7579 - val_mae: 0.6391 - val_rmse: 0.7094 - val_smape: 1.2426

Epoch 18/128

1915/1915 - 17s - 9ms/step - ia: 0.3874 - loss: 0.8117 - mae: 0.6626 - rmse: 0.8692 - smape: 1.2793 - val_ia: 0.2461 - val_loss: 0.7564 - val_mae: 0.6435 - val_rmse: 0.7121 - val_smape: 1.2696

Epoch 19/128

1915/1915 - 16s - 9ms/step - ia: 0.3856 - loss: 0.8120 - mae: 0.6625 - rmse: 0.8697 - smape: 1.2807 - val_ia: 0.2459 - val_loss: 0.7584 - val_mae: 0.6440 - val_rmse: 0.7138 - val_smape: 1.2602

Epoch 20/128

1915/1915 - 20s - 11ms/step - ia: 0.3893 - loss: 0.8117 - mae: 0.6621 - rmse: 0.8686 - smape: 1.2755 - val_ia: 0.2470 - val_loss: 0.7516 - val_mae: 0.6377 - val_rmse: 0.7070 - val_smape: 1.2507

Epoch 21/128

1915/1915 - 21s - 11ms/step - ia: 0.3897 - loss: 0.8085 - mae: 0.6612 - rmse: 0.8662 - smape: 1.2766 - val_ia: 0.2455 - val_loss: 0.7546 - val_mae: 0.6426 - val_rmse: 0.7107 - val_smape: 1.2788

Epoch 22/128

1915/1915 - 16s - 8ms/step - ia: 0.3921 - loss: 0.8077 - mae: 0.6604 - rmse: 0.8662 - smape: 1.2750 - val_ia: 0.2464 - val_loss: 0.7536 - val_mae: 0.6413 - val_rmse: 0.7102 - val_smape: 1.2678

Epoch 23/128

1915/1915 - 16s - 9ms/step - ia: 0.3893 - loss: 0.8079 - mae: 0.6601 - rmse: 0.8668 - smape: 1.2756 - val_ia: 0.2472 - val_loss: 0.7552 - val_mae: 0.6415 - val_rmse: 0.7112 - val_smape: 1.2534

Epoch 24/128

1915/1915 - 16s - 9ms/step - ia: 0.3922 - loss: 0.8058 - mae: 0.6597 - rmse: 0.8663 - smape: 1.2714 - val_ia: 0.2479 - val_loss: 0.7548 - val_mae: 0.6366 - val_rmse: 0.7076 - val_smape: 1.2351

Epoch 25/128

1915/1915 - 17s - 9ms/step - ia: 0.3954 - loss: 0.8036 - mae: 0.6575 - rmse: 0.8638 - smape: 1.2653 - val_ia: 0.2466 - val_loss: 0.7545 - val_mae: 0.6397 - val_rmse: 0.7095 - val_smape: 1.2519

Epoch 26/128

1915/1915 - 17s - 9ms/step - ia: 0.3941 - loss: 0.8035 - mae: 0.6576 - rmse: 0.8641 - smape: 1.2694 - val_ia: 0.2493 - val_loss: 0.7507 - val_mae: 0.6296 - val_rmse: 0.6997 - val_smape: 1.2219

Epoch 27/128

1915/1915 - 17s - 9ms/step - ia: 0.3929 - loss: 0.8043 - mae: 0.6578 - rmse: 0.8643 - smape: 1.2681 - val_ia: 0.2461 - val_loss: 0.7560 - val_mae: 0.6434 - val_rmse: 0.7126 - val_smape: 1.2706

Epoch 28/128

1915/1915 - 20s - 11ms/step - ia: 0.3986 - loss: 0.7988 - mae: 0.6556 - rmse: 0.8604 - smape: 1.2624 - val_ia: 0.2492 - val_loss: 0.7504 - val_mae: 0.6300 - val_rmse: 0.6999 - val_smape: 1.2264

Epoch 29/128

1915/1915 - 20s - 11ms/step - ia: 0.3956 - loss: 0.8027 - mae: 0.6569 - rmse: 0.8627 - smape: 1.2673 - val_ia: 0.2482 - val_loss: 0.7467 - val_mae: 0.6311 - val_rmse: 0.6998 - val_smape: 1.2417

Epoch 30/128

1915/1915 - 17s - 9ms/step - ia: 0.3972 - loss: 0.7998 - mae: 0.6556 - rmse: 0.8619 - smape: 1.2625 - val_ia: 0.2497 - val_loss: 0.7510 - val_mae: 0.6310 - val_rmse: 0.7015 - val_smape: 1.2228

Epoch 31/128

1915/1915 - 16s - 9ms/step - ia: 0.3975 - loss: 0.7984 - mae: 0.6550 - rmse: 0.8612 - smape: 1.2611 - val_ia: 0.2451 - val_loss: 0.7589 - val_mae: 0.6474 - val_rmse: 0.7166 - val_smape: 1.2764

Epoch 32/128

1915/1915 - 17s - 9ms/step - ia: 0.4005 - loss: 0.7956 - mae: 0.6540 - rmse: 0.8591 - smape: 1.2595 - val_ia: 0.2497 - val_loss: 0.7461 - val_mae: 0.6292 - val_rmse: 0.6989 - val_smape: 1.2306

Epoch 33/128

1915/1915 - 17s - 9ms/step - ia: 0.3992 - loss: 0.7956 - mae: 0.6533 - rmse: 0.8606 - smape: 1.2613 - val_ia: 0.2456 - val_loss: 0.7509 - val_mae: 0.6402 - val_rmse: 0.7089 - val_smape: 1.2693

Epoch 34/128

1915/1915 - 16s - 9ms/step - ia: 0.4004 - loss: 0.7942 - mae: 0.6534 - rmse: 0.8589 - smape: 1.2588 - val_ia: 0.2477 - val_loss: 0.7539 - val_mae: 0.6393 - val_rmse: 0.7099 - val_smape: 1.2503

Epoch 35/128

1915/1915 - 17s - 9ms/step - ia: 0.4038 - loss: 0.7910 - mae: 0.6515 - rmse: 0.8568 - smape: 1.2580 - val_ia: 0.2497 - val_loss: 0.7565 - val_mae: 0.6341 - val_rmse: 0.7053 - val_smape: 1.2227

Epoch 36/128

1915/1915 - 17s - 9ms/step - ia: 0.4022 - loss: 0.7915 - mae: 0.6513 - rmse: 0.8577 - smape: 1.2549 - val_ia: 0.2463 - val_loss: 0.7582 - val_mae: 0.6411 - val_rmse: 0.7113 - val_smape: 1.2516

Epoch 37/128

1915/1915 - 17s - 9ms/step - ia: 0.4033 - loss: 0.7907 - mae: 0.6515 - rmse: 0.8566 - smape: 1.2579 - val_ia: 0.2474 - val_loss: 0.7548 - val_mae: 0.6382 - val_rmse: 0.7078 - val_smape: 1.2553

Epoch 38/128

1915/1915 - 17s - 9ms/step - ia: 0.4032 - loss: 0.7883 - mae: 0.6504 - rmse: 0.8567 - smape: 1.2564 - val_ia: 0.2475 - val_loss: 0.7561 - val_mae: 0.6372 - val_rmse: 0.7074 - val_smape: 1.2464

Epoch 39/128

1915/1915 - 21s - 11ms/step - ia: 0.4038 - loss: 0.7893 - mae: 0.6503 - rmse: 0.8556 - smape: 1.2573 - val_ia: 0.2460 - val_loss: 0.7612 - val_mae: 0.6426 - val_rmse: 0.7125 - val_smape: 1.2592

Epoch 40/128

1915/1915 - 18s - 9ms/step - ia: 0.4063 - loss: 0.7869 - mae: 0.6491 - rmse: 0.8547 - smape: 1.2539 - val_ia: 0.2494 - val_loss: 0.7497 - val_mae: 0.6331 - val_rmse: 0.7027 - val_smape: 1.2431

Epoch 41/128

1915/1915 - 18s - 9ms/step - ia: 0.4056 - loss: 0.7862 - mae: 0.6499 - rmse: 0.8542 - smape: 1.2577 - val_ia: 0.2477 - val_loss: 0.7695 - val_mae: 0.6431 - val_rmse: 0.7142 - val_smape: 1.2451

Epoch 42/128

1915/1915 - 18s - 10ms/step - ia: 0.4070 - loss: 0.7834 - mae: 0.6487 - rmse: 0.8533 - smape: 1.2538 - val_ia: 0.2495 - val_loss: 0.7616 - val_mae: 0.6369 - val_rmse: 0.7081 - val_smape: 1.2377

Epoch 43/128

1915/1915 - 18s - 10ms/step - ia: 0.4081 - loss: 0.7829 - mae: 0.6477 - rmse: 0.8524 - smape: 1.2549 - val_ia: 0.2483 - val_loss: 0.7569 - val_mae: 0.6385 - val_rmse: 0.7088 - val_smape: 1.2458

Epoch 44/128

1915/1915 - 18s - 9ms/step - ia: 0.4081 - loss: 0.7835 - mae: 0.6478 - rmse: 0.8527 - smape: 1.2511 - val_ia: 0.2482 - val_loss: 0.7577 - val_mae: 0.6394 - val_rmse: 0.7094 - val_smape: 1.2487

Epoch 45/128

1915/1915 - 20s - 11ms/step - ia: 0.4090 - loss: 0.7826 - mae: 0.6476 - rmse: 0.8523 - smape: 1.2546 - val_ia: 0.2491 - val_loss: 0.7630 - val_mae: 0.6385 - val_rmse: 0.7095 - val_smape: 1.2368

Epoch 46/128

1915/1915 - 20s - 11ms/step - ia: 0.4119 - loss: 0.7785 - mae: 0.6455 - rmse: 0.8498 - smape: 1.2492 - val_ia: 0.2497 - val_loss: 0.7487 - val_mae: 0.6316 - val_rmse: 0.7006 - val_smape: 1.2454

Epoch 47/128

1915/1915 - 18s - 9ms/step - ia: 0.4104 - loss: 0.7794 - mae: 0.6464 - rmse: 0.8510 - smape: 1.2508 - val_ia: 0.2499 - val_loss: 0.7472 - val_mae: 0.6319 - val_rmse: 0.7011 - val_smape: 1.2492

Epoch 47: early stopping

Restoring model weights from the end of the best epoch: 32.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:13 542ms/step
  9/136 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 19/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 42/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 53/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 63/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 73/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 83/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 94/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
135/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

Epoch 1/128

 83%|████████▎ | 10/12 [2:53:32<22:39, 679.58s/trial, best loss: 0.7446180315174813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

3830/3830 - 23s - 6ms/step - ia: 0.2329 - loss: 0.9875 - mae: 0.7433 - rmse: 0.9285 - smape: 1.6850 - val_ia: 0.1902 - val_loss: 0.9362 - val_mae: 0.7112 - val_rmse: 0.7474 - val_smape: 1.6286

Epoch 2/128

3830/3830 - 20s - 5ms/step - ia: 0.2324 - loss: 0.9847 - mae: 0.7421 - rmse: 0.9260 - smape: 1.6864 - val_ia: 0.1901 - val_loss: 0.9350 - val_mae: 0.7117 - val_rmse: 0.7478 - val_smape: 1.6361

Epoch 3/128

3830/3830 - 19s - 5ms/step - ia: 0.2349 - loss: 0.9794 - mae: 0.7404 - rmse: 0.9252 - smape: 1.6842 - val_ia: 0.1901 - val_loss: 0.9339 - val_mae: 0.7121 - val_rmse: 0.7482 - val_smape: 1.6426

Epoch 4/128

3830/3830 - 19s - 5ms/step - ia: 0.2358 - loss: 0.9776 - mae: 0.7400 - rmse: 0.9239 - smape: 1.6900 - val_ia: 0.1900 - val_loss: 0.9328 - val_mae: 0.7124 - val_rmse: 0.7485 - val_smape: 1.6490

Epoch 5/128

3830/3830 - 19s - 5ms/step - ia: 0.2331 - loss: 0.9752 - mae: 0.7403 - rmse: 0.9227 - smape: 1.6925 - val_ia: 0.1900 - val_loss: 0.9318 - val_mae: 0.7127 - val_rmse: 0.7488 - val_smape: 1.6549

Epoch 6/128

3830/3830 - 19s - 5ms/step - ia: 0.2358 - loss: 0.9730 - mae: 0.7393 - rmse: 0.9222 - smape: 1.6909 - val_ia: 0.1899 - val_loss: 0.9308 - val_mae: 0.7130 - val_rmse: 0.7491 - val_smape: 1.6597

Epoch 7/128

3830/3830 - 19s - 5ms/step - ia: 0.2365 - loss: 0.9697 - mae: 0.7384 - rmse: 0.9212 - smape: 1.6913 - val_ia: 0.1899 - val_loss: 0.9298 - val_mae: 0.7132 - val_rmse: 0.7492 - val_smape: 1.6638

Epoch 8/128

3830/3830 - 19s - 5ms/step - ia: 0.2388 - loss: 0.9695 - mae: 0.7382 - rmse: 0.9206 - smape: 1.6920 - val_ia: 0.1899 - val_loss: 0.9288 - val_mae: 0.7133 - val_rmse: 0.7493 - val_smape: 1.6675

Epoch 9/128

3830/3830 - 18s - 5ms/step - ia: 0.2368 - loss: 0.9668 - mae: 0.7370 - rmse: 0.9193 - smape: 1.6915 - val_ia: 0.1899 - val_loss: 0.9278 - val_mae: 0.7133 - val_rmse: 0.7493 - val_smape: 1.6701

Epoch 10/128

3830/3830 - 20s - 5ms/step - ia: 0.2405 - loss: 0.9622 - mae: 0.7353 - rmse: 0.9169 - smape: 1.6874 - val_ia: 0.1899 - val_loss: 0.9268 - val_mae: 0.7132 - val_rmse: 0.7493 - val_smape: 1.6722

Epoch 11/128

3830/3830 - 19s - 5ms/step - ia: 0.2406 - loss: 0.9649 - mae: 0.7368 - rmse: 0.9191 - smape: 1.6912 - val_ia: 0.1899 - val_loss: 0.9258 - val_mae: 0.7131 - val_rmse: 0.7492 - val_smape: 1.6739

Epoch 12/128

3830/3830 - 18s - 5ms/step - ia: 0.2416 - loss: 0.9585 - mae: 0.7346 - rmse: 0.9154 - smape: 1.6876 - val_ia: 0.1899 - val_loss: 0.9246 - val_mae: 0.7130 - val_rmse: 0.7490 - val_smape: 1.6747

Epoch 13/128

3830/3830 - 18s - 5ms/step - ia: 0.2449 - loss: 0.9570 - mae: 0.7332 - rmse: 0.9143 - smape: 1.6818 - val_ia: 0.1899 - val_loss: 0.9235 - val_mae: 0.7128 - val_rmse: 0.7489 - val_smape: 1.6754

Epoch 14/128

3830/3830 - 18s - 5ms/step - ia: 0.2438 - loss: 0.9590 - mae: 0.7344 - rmse: 0.9156 - smape: 1.6861 - val_ia: 0.1899 - val_loss: 0.9225 - val_mae: 0.7126 - val_rmse: 0.7487 - val_smape: 1.6763

Epoch 15/128

3830/3830 - 20s - 5ms/step - ia: 0.2441 - loss: 0.9569 - mae: 0.7331 - rmse: 0.9156 - smape: 1.6832 - val_ia: 0.1899 - val_loss: 0.9214 - val_mae: 0.7124 - val_rmse: 0.7484 - val_smape: 1.6766

Epoch 16/128

3830/3830 - 20s - 5ms/step - ia: 0.2482 - loss: 0.9511 - mae: 0.7313 - rmse: 0.9127 - smape: 1.6790 - val_ia: 0.1899 - val_loss: 0.9202 - val_mae: 0.7121 - val_rmse: 0.7482 - val_smape: 1.6765

Epoch 17/128

3830/3830 - 18s - 5ms/step - ia: 0.2489 - loss: 0.9513 - mae: 0.7305 - rmse: 0.9118 - smape: 1.6736 - val_ia: 0.1899 - val_loss: 0.9190 - val_mae: 0.7118 - val_rmse: 0.7478 - val_smape: 1.6758

Epoch 18/128

3830/3830 - 19s - 5ms/step - ia: 0.2474 - loss: 0.9508 - mae: 0.7316 - rmse: 0.9125 - smape: 1.6775 - val_ia: 0.1898 - val_loss: 0.9180 - val_mae: 0.7116 - val_rmse: 0.7476 - val_smape: 1.6763

Epoch 19/128

3830/3830 - 19s - 5ms/step - ia: 0.2506 - loss: 0.9482 - mae: 0.7300 - rmse: 0.9111 - smape: 1.6711 - val_ia: 0.1898 - val_loss: 0.9168 - val_mae: 0.7113 - val_rmse: 0.7473 - val_smape: 1.6757

Epoch 20/128

3830/3830 - 18s - 5ms/step - ia: 0.2514 - loss: 0.9522 - mae: 0.7312 - rmse: 0.9112 - smape: 1.6745 - val_ia: 0.1898 - val_loss: 0.9157 - val_mae: 0.7109 - val_rmse: 0.7470 - val_smape: 1.6750

Epoch 21/128

3830/3830 - 17s - 5ms/step - ia: 0.2516 - loss: 0.9482 - mae: 0.7295 - rmse: 0.9094 - smape: 1.6718 - val_ia: 0.1899 - val_loss: 0.9146 - val_mae: 0.7106 - val_rmse: 0.7467 - val_smape: 1.6742

Epoch 22/128

3830/3830 - 17s - 4ms/step - ia: 0.2528 - loss: 0.9474 - mae: 0.7292 - rmse: 0.9102 - smape: 1.6683 - val_ia: 0.1899 - val_loss: 0.9135 - val_mae: 0.7102 - val_rmse: 0.7463 - val_smape: 1.6735

Epoch 23/128

3830/3830 - 17s - 4ms/step - ia: 0.2565 - loss: 0.9430 - mae: 0.7277 - rmse: 0.9071 - smape: 1.6628 - val_ia: 0.1900 - val_loss: 0.9123 - val_mae: 0.7098 - val_rmse: 0.7459 - val_smape: 1.6717

Epoch 24/128

3830/3830 - 17s - 4ms/step - ia: 0.2546 - loss: 0.9465 - mae: 0.7289 - rmse: 0.9093 - smape: 1.6644 - val_ia: 0.1900 - val_loss: 0.9114 - val_mae: 0.7095 - val_rmse: 0.7456 - val_smape: 1.6709

Epoch 25/128

3830/3830 - 21s - 5ms/step - ia: 0.2582 - loss: 0.9428 - mae: 0.7259 - rmse: 0.9098 - smape: 1.6565 - val_ia: 0.1901 - val_loss: 0.9103 - val_mae: 0.7090 - val_rmse: 0.7451 - val_smape: 1.6688

Epoch 26/128

3830/3830 - 17s - 4ms/step - ia: 0.2591 - loss: 0.9420 - mae: 0.7270 - rmse: 0.9071 - smape: 1.6604 - val_ia: 0.1902 - val_loss: 0.9092 - val_mae: 0.7086 - val_rmse: 0.7448 - val_smape: 1.6679

Epoch 27/128

3830/3830 - 17s - 4ms/step - ia: 0.2587 - loss: 0.9407 - mae: 0.7259 - rmse: 0.9069 - smape: 1.6568 - val_ia: 0.1903 - val_loss: 0.9083 - val_mae: 0.7082 - val_rmse: 0.7444 - val_smape: 1.6665

Epoch 28/128

3830/3830 - 17s - 5ms/step - ia: 0.2607 - loss: 0.9411 - mae: 0.7260 - rmse: 0.9076 - smape: 1.6557 - val_ia: 0.1903 - val_loss: 0.9072 - val_mae: 0.7079 - val_rmse: 0.7440 - val_smape: 1.6653

Epoch 29/128

3830/3830 - 17s - 4ms/step - ia: 0.2621 - loss: 0.9385 - mae: 0.7248 - rmse: 0.9054 - smape: 1.6507 - val_ia: 0.1904 - val_loss: 0.9062 - val_mae: 0.7075 - val_rmse: 0.7437 - val_smape: 1.6639

Epoch 30/128

3830/3830 - 17s - 4ms/step - ia: 0.2671 - loss: 0.9398 - mae: 0.7242 - rmse: 0.9061 - smape: 1.6468 - val_ia: 0.1905 - val_loss: 0.9052 - val_mae: 0.7071 - val_rmse: 0.7432 - val_smape: 1.6620

Epoch 31/128

3830/3830 - 17s - 4ms/step - ia: 0.2656 - loss: 0.9426 - mae: 0.7244 - rmse: 0.9063 - smape: 1.6455 - val_ia: 0.1905 - val_loss: 0.9043 - val_mae: 0.7066 - val_rmse: 0.7428 - val_smape: 1.6606

Epoch 32/128

3830/3830 - 21s - 5ms/step - ia: 0.2654 - loss: 0.9354 - mae: 0.7233 - rmse: 0.9030 - smape: 1.6444 - val_ia: 0.1906 - val_loss: 0.9033 - val_mae: 0.7062 - val_rmse: 0.7424 - val_smape: 1.6588

Epoch 33/128

3830/3830 - 21s - 5ms/step - ia: 0.2671 - loss: 0.9358 - mae: 0.7227 - rmse: 0.9059 - smape: 1.6422 - val_ia: 0.1907 - val_loss: 0.9024 - val_mae: 0.7059 - val_rmse: 0.7421 - val_smape: 1.6577

Epoch 34/128

3830/3830 - 18s - 5ms/step - ia: 0.2704 - loss: 0.9313 - mae: 0.7209 - rmse: 0.9020 - smape: 1.6402 - val_ia: 0.1907 - val_loss: 0.9014 - val_mae: 0.7055 - val_rmse: 0.7417 - val_smape: 1.6561

Epoch 35/128

3830/3830 - 17s - 5ms/step - ia: 0.2698 - loss: 0.9254 - mae: 0.7196 - rmse: 0.8996 - smape: 1.6373 - val_ia: 0.1908 - val_loss: 0.9004 - val_mae: 0.7051 - val_rmse: 0.7413 - val_smape: 1.6547

Epoch 36/128

3830/3830 - 18s - 5ms/step - ia: 0.2675 - loss: 0.9327 - mae: 0.7217 - rmse: 0.9030 - smape: 1.6373 - val_ia: 0.1908 - val_loss: 0.8995 - val_mae: 0.7047 - val_rmse: 0.7409 - val_smape: 1.6531

Epoch 37/128

3830/3830 - 17s - 4ms/step - ia: 0.2723 - loss: 0.9285 - mae: 0.7199 - rmse: 0.9011 - smape: 1.6325 - val_ia: 0.1909 - val_loss: 0.8984 - val_mae: 0.7043 - val_rmse: 0.7405 - val_smape: 1.6510

Epoch 38/128

3830/3830 - 17s - 4ms/step - ia: 0.2693 - loss: 0.9294 - mae: 0.7212 - rmse: 0.9023 - smape: 1.6386 - val_ia: 0.1909 - val_loss: 0.8976 - val_mae: 0.7040 - val_rmse: 0.7403 - val_smape: 1.6499

Epoch 39/128

3830/3830 - 17s - 4ms/step - ia: 0.2713 - loss: 0.9303 - mae: 0.7208 - rmse: 0.9028 - smape: 1.6339 - val_ia: 0.1909 - val_loss: 0.8967 - val_mae: 0.7037 - val_rmse: 0.7400 - val_smape: 1.6487

Epoch 40/128

3830/3830 - 17s - 5ms/step - ia: 0.2714 - loss: 0.9299 - mae: 0.7210 - rmse: 0.9029 - smape: 1.6323 - val_ia: 0.1909 - val_loss: 0.8959 - val_mae: 0.7034 - val_rmse: 0.7397 - val_smape: 1.6476

Epoch 41/128

3830/3830 - 19s - 5ms/step - ia: 0.2727 - loss: 0.9298 - mae: 0.7198 - rmse: 0.9014 - smape: 1.6296 - val_ia: 0.1909 - val_loss: 0.8952 - val_mae: 0.7031 - val_rmse: 0.7394 - val_smape: 1.6463

Epoch 42/128

3830/3830 - 19s - 5ms/step - ia: 0.2753 - loss: 0.9289 - mae: 0.7204 - rmse: 0.9012 - smape: 1.6272 - val_ia: 0.1910 - val_loss: 0.8944 - val_mae: 0.7029 - val_rmse: 0.7392 - val_smape: 1.6453

Epoch 43/128

3830/3830 - 19s - 5ms/step - ia: 0.2760 - loss: 0.9262 - mae: 0.7183 - rmse: 0.9011 - smape: 1.6222 - val_ia: 0.1910 - val_loss: 0.8937 - val_mae: 0.7026 - val_rmse: 0.7389 - val_smape: 1.6438

Epoch 44/128

3830/3830 - 18s - 5ms/step - ia: 0.2764 - loss: 0.9231 - mae: 0.7174 - rmse: 0.8980 - smape: 1.6184 - val_ia: 0.1910 - val_loss: 0.8928 - val_mae: 0.7022 - val_rmse: 0.7386 - val_smape: 1.6420

Epoch 45/128

3830/3830 - 18s - 5ms/step - ia: 0.2745 - loss: 0.9265 - mae: 0.7192 - rmse: 0.9006 - smape: 1.6213 - val_ia: 0.1910 - val_loss: 0.8920 - val_mae: 0.7019 - val_rmse: 0.7382 - val_smape: 1.6405

Epoch 46/128

3830/3830 - 18s - 5ms/step - ia: 0.2796 - loss: 0.9230 - mae: 0.7181 - rmse: 0.8970 - smape: 1.6197 - val_ia: 0.1910 - val_loss: 0.8913 - val_mae: 0.7016 - val_rmse: 0.7380 - val_smape: 1.6390

Epoch 47/128

3830/3830 - 18s - 5ms/step - ia: 0.2798 - loss: 0.9260 - mae: 0.7178 - rmse: 0.8989 - smape: 1.6158 - val_ia: 0.1911 - val_loss: 0.8906 - val_mae: 0.7013 - val_rmse: 0.7377 - val_smape: 1.6374

Epoch 48/128

3830/3830 - 18s - 5ms/step - ia: 0.2772 - loss: 0.9213 - mae: 0.7172 - rmse: 0.8973 - smape: 1.6172 - val_ia: 0.1911 - val_loss: 0.8898 - val_mae: 0.7009 - val_rmse: 0.7373 - val_smape: 1.6353

Epoch 49/128

3830/3830 - 21s - 5ms/step - ia: 0.2787 - loss: 0.9252 - mae: 0.7178 - rmse: 0.8992 - smape: 1.6134 - val_ia: 0.1911 - val_loss: 0.8890 - val_mae: 0.7006 - val_rmse: 0.7370 - val_smape: 1.6335

Epoch 50/128

3830/3830 - 18s - 5ms/step - ia: 0.2785 - loss: 0.9224 - mae: 0.7177 - rmse: 0.8989 - smape: 1.6134 - val_ia: 0.1912 - val_loss: 0.8883 - val_mae: 0.7003 - val_rmse: 0.7367 - val_smape: 1.6320

Epoch 51/128

3830/3830 - 18s - 5ms/step - ia: 0.2815 - loss: 0.9193 - mae: 0.7152 - rmse: 0.8963 - smape: 1.6075 - val_ia: 0.1912 - val_loss: 0.8876 - val_mae: 0.7001 - val_rmse: 0.7365 - val_smape: 1.6302

Epoch 52/128

3830/3830 - 18s - 5ms/step - ia: 0.2818 - loss: 0.9175 - mae: 0.7148 - rmse: 0.8967 - smape: 1.6072 - val_ia: 0.1912 - val_loss: 0.8869 - val_mae: 0.6998 - val_rmse: 0.7362 - val_smape: 1.6285

Epoch 53/128

3830/3830 - 18s - 5ms/step - ia: 0.2812 - loss: 0.9235 - mae: 0.7165 - rmse: 0.8981 - smape: 1.6088 - val_ia: 0.1913 - val_loss: 0.8863 - val_mae: 0.6995 - val_rmse: 0.7359 - val_smape: 1.6270

Epoch 54/128

3830/3830 - 18s - 5ms/step - ia: 0.2828 - loss: 0.9225 - mae: 0.7172 - rmse: 0.8979 - smape: 1.6056 - val_ia: 0.1913 - val_loss: 0.8858 - val_mae: 0.6993 - val_rmse: 0.7357 - val_smape: 1.6259

Epoch 55/128

3830/3830 - 19s - 5ms/step - ia: 0.2821 - loss: 0.9220 - mae: 0.7165 - rmse: 0.8990 - smape: 1.6049 - val_ia: 0.1913 - val_loss: 0.8852 - val_mae: 0.6991 - val_rmse: 0.7355 - val_smape: 1.6245

Epoch 56/128

3830/3830 - 18s - 5ms/step - ia: 0.2829 - loss: 0.9232 - mae: 0.7157 - rmse: 0.8983 - smape: 1.6035 - val_ia: 0.1913 - val_loss: 0.8847 - val_mae: 0.6989 - val_rmse: 0.7353 - val_smape: 1.6233

Epoch 57/128

3830/3830 - 19s - 5ms/step - ia: 0.2839 - loss: 0.9218 - mae: 0.7159 - rmse: 0.8974 - smape: 1.6020 - val_ia: 0.1913 - val_loss: 0.8843 - val_mae: 0.6988 - val_rmse: 0.7352 - val_smape: 1.6226

Epoch 58/128

3830/3830 - 19s - 5ms/step - ia: 0.2848 - loss: 0.9180 - mae: 0.7144 - rmse: 0.8949 - smape: 1.5993 - val_ia: 0.1913 - val_loss: 0.8837 - val_mae: 0.6986 - val_rmse: 0.7350 - val_smape: 1.6213

Epoch 59/128

3830/3830 - 20s - 5ms/step - ia: 0.2834 - loss: 0.9147 - mae: 0.7140 - rmse: 0.8956 - smape: 1.5981 - val_ia: 0.1914 - val_loss: 0.8830 - val_mae: 0.6982 - val_rmse: 0.7347 - val_smape: 1.6193

Epoch 60/128

3830/3830 - 18s - 5ms/step - ia: 0.2860 - loss: 0.9198 - mae: 0.7147 - rmse: 0.8962 - smape: 1.5929 - val_ia: 0.1914 - val_loss: 0.8826 - val_mae: 0.6981 - val_rmse: 0.7345 - val_smape: 1.6183

Epoch 61/128

3830/3830 - 19s - 5ms/step - ia: 0.2854 - loss: 0.9139 - mae: 0.7136 - rmse: 0.8946 - smape: 1.5929 - val_ia: 0.1914 - val_loss: 0.8820 - val_mae: 0.6979 - val_rmse: 0.7343 - val_smape: 1.6169

Epoch 62/128

3830/3830 - 20s - 5ms/step - ia: 0.2871 - loss: 0.9112 - mae: 0.7128 - rmse: 0.8924 - smape: 1.5923 - val_ia: 0.1914 - val_loss: 0.8813 - val_mae: 0.6976 - val_rmse: 0.7340 - val_smape: 1.6151

Epoch 63/128

3830/3830 - 19s - 5ms/step - ia: 0.2860 - loss: 0.9183 - mae: 0.7142 - rmse: 0.8963 - smape: 1.5915 - val_ia: 0.1915 - val_loss: 0.8809 - val_mae: 0.6973 - val_rmse: 0.7338 - val_smape: 1.6138

Epoch 64/128

3830/3830 - 19s - 5ms/step - ia: 0.2898 - loss: 0.9174 - mae: 0.7143 - rmse: 0.8969 - smape: 1.5899 - val_ia: 0.1915 - val_loss: 0.8803 - val_mae: 0.6971 - val_rmse: 0.7336 - val_smape: 1.6123

Epoch 65/128

3830/3830 - 19s - 5ms/step - ia: 0.2871 - loss: 0.9166 - mae: 0.7147 - rmse: 0.8972 - smape: 1.5937 - val_ia: 0.1915 - val_loss: 0.8800 - val_mae: 0.6970 - val_rmse: 0.7335 - val_smape: 1.6118

Epoch 66/128

3830/3830 - 18s - 5ms/step - ia: 0.2870 - loss: 0.9160 - mae: 0.7140 - rmse: 0.8962 - smape: 1.5897 - val_ia: 0.1915 - val_loss: 0.8795 - val_mae: 0.6969 - val_rmse: 0.7333 - val_smape: 1.6107

Epoch 67/128

3830/3830 - 18s - 5ms/step - ia: 0.2910 - loss: 0.9126 - mae: 0.7122 - rmse: 0.8920 - smape: 1.5843 - val_ia: 0.1915 - val_loss: 0.8791 - val_mae: 0.6967 - val_rmse: 0.7332 - val_smape: 1.6099

Epoch 68/128

3830/3830 - 18s - 5ms/step - ia: 0.2886 - loss: 0.9152 - mae: 0.7123 - rmse: 0.8955 - smape: 1.5870 - val_ia: 0.1915 - val_loss: 0.8786 - val_mae: 0.6965 - val_rmse: 0.7330 - val_smape: 1.6085

Epoch 69/128

3830/3830 - 18s - 5ms/step - ia: 0.2895 - loss: 0.9114 - mae: 0.7134 - rmse: 0.8940 - smape: 1.5873 - val_ia: 0.1915 - val_loss: 0.8780 - val_mae: 0.6963 - val_rmse: 0.7328 - val_smape: 1.6069

Epoch 70/128

3830/3830 - 18s - 5ms/step - ia: 0.2875 - loss: 0.9143 - mae: 0.7137 - rmse: 0.8949 - smape: 1.5850 - val_ia: 0.1915 - val_loss: 0.8777 - val_mae: 0.6962 - val_rmse: 0.7327 - val_smape: 1.6064

Epoch 71/128

3830/3830 - 19s - 5ms/step - ia: 0.2917 - loss: 0.9187 - mae: 0.7136 - rmse: 0.8949 - smape: 1.5779 - val_ia: 0.1915 - val_loss: 0.8775 - val_mae: 0.6962 - val_rmse: 0.7326 - val_smape: 1.6060

Epoch 72/128

3830/3830 - 19s - 5ms/step - ia: 0.2909 - loss: 0.9143 - mae: 0.7128 - rmse: 0.8940 - smape: 1.5817 - val_ia: 0.1915 - val_loss: 0.8772 - val_mae: 0.6960 - val_rmse: 0.7325 - val_smape: 1.6051

Epoch 73/128

3830/3830 - 20s - 5ms/step - ia: 0.2925 - loss: 0.9113 - mae: 0.7122 - rmse: 0.8929 - smape: 1.5791 - val_ia: 0.1915 - val_loss: 0.8768 - val_mae: 0.6959 - val_rmse: 0.7324 - val_smape: 1.6039

Epoch 74/128

3830/3830 - 21s - 5ms/step - ia: 0.2913 - loss: 0.9186 - mae: 0.7148 - rmse: 0.8973 - smape: 1.5818 - val_ia: 0.1915 - val_loss: 0.8767 - val_mae: 0.6959 - val_rmse: 0.7324 - val_smape: 1.6041

Epoch 75/128

3830/3830 - 19s - 5ms/step - ia: 0.2951 - loss: 0.9099 - mae: 0.7121 - rmse: 0.8921 - smape: 1.5771 - val_ia: 0.1915 - val_loss: 0.8763 - val_mae: 0.6958 - val_rmse: 0.7323 - val_smape: 1.6034

Epoch 76/128

3830/3830 - 19s - 5ms/step - ia: 0.2926 - loss: 0.9152 - mae: 0.7134 - rmse: 0.8944 - smape: 1.5832 - val_ia: 0.1915 - val_loss: 0.8760 - val_mae: 0.6958 - val_rmse: 0.7323 - val_smape: 1.6029

Epoch 77/128

3830/3830 - 19s - 5ms/step - ia: 0.2941 - loss: 0.9169 - mae: 0.7125 - rmse: 0.8951 - smape: 1.5728 - val_ia: 0.1915 - val_loss: 0.8758 - val_mae: 0.6957 - val_rmse: 0.7322 - val_smape: 1.6024

Epoch 78/128

3830/3830 - 19s - 5ms/step - ia: 0.2906 - loss: 0.9142 - mae: 0.7135 - rmse: 0.8951 - smape: 1.5787 - val_ia: 0.1915 - val_loss: 0.8757 - val_mae: 0.6958 - val_rmse: 0.7323 - val_smape: 1.6025

Epoch 79/128

3830/3830 - 19s - 5ms/step - ia: 0.2954 - loss: 0.9080 - mae: 0.7110 - rmse: 0.8927 - smape: 1.5726 - val_ia: 0.1915 - val_loss: 0.8753 - val_mae: 0.6956 - val_rmse: 0.7321 - val_smape: 1.6015

Epoch 80/128

3830/3830 - 18s - 5ms/step - ia: 0.2922 - loss: 0.9167 - mae: 0.7135 - rmse: 0.8962 - smape: 1.5754 - val_ia: 0.1915 - val_loss: 0.8752 - val_mae: 0.6956 - val_rmse: 0.7321 - val_smape: 1.6012

Epoch 81/128

3830/3830 - 20s - 5ms/step - ia: 0.2931 - loss: 0.9126 - mae: 0.7124 - rmse: 0.8932 - smape: 1.5753 - val_ia: 0.1915 - val_loss: 0.8750 - val_mae: 0.6956 - val_rmse: 0.7321 - val_smape: 1.6008

Epoch 82/128

3830/3830 - 21s - 5ms/step - ia: 0.2923 - loss: 0.9109 - mae: 0.7108 - rmse: 0.8937 - smape: 1.5709 - val_ia: 0.1915 - val_loss: 0.8747 - val_mae: 0.6954 - val_rmse: 0.7320 - val_smape: 1.6001

Epoch 83/128

3830/3830 - 18s - 5ms/step - ia: 0.2958 - loss: 0.9116 - mae: 0.7112 - rmse: 0.8935 - smape: 1.5692 - val_ia: 0.1915 - val_loss: 0.8745 - val_mae: 0.6954 - val_rmse: 0.7319 - val_smape: 1.5995

Epoch 84/128

3830/3830 - 19s - 5ms/step - ia: 0.2961 - loss: 0.9073 - mae: 0.7102 - rmse: 0.8917 - smape: 1.5689 - val_ia: 0.1915 - val_loss: 0.8742 - val_mae: 0.6953 - val_rmse: 0.7319 - val_smape: 1.5991

Epoch 85/128

3830/3830 - 19s - 5ms/step - ia: 0.2943 - loss: 0.9146 - mae: 0.7130 - rmse: 0.8939 - smape: 1.5713 - val_ia: 0.1915 - val_loss: 0.8741 - val_mae: 0.6954 - val_rmse: 0.7319 - val_smape: 1.5991

Epoch 86/128

3830/3830 - 19s - 5ms/step - ia: 0.2933 - loss: 0.9114 - mae: 0.7120 - rmse: 0.8940 - smape: 1.5685 - val_ia: 0.1915 - val_loss: 0.8738 - val_mae: 0.6954 - val_rmse: 0.7319 - val_smape: 1.5990

Epoch 87/128

3830/3830 - 18s - 5ms/step - ia: 0.2961 - loss: 0.9103 - mae: 0.7099 - rmse: 0.8935 - smape: 1.5593 - val_ia: 0.1915 - val_loss: 0.8736 - val_mae: 0.6953 - val_rmse: 0.7319 - val_smape: 1.5987

Epoch 88/128

3830/3830 - 18s - 5ms/step - ia: 0.2978 - loss: 0.9093 - mae: 0.7100 - rmse: 0.8909 - smape: 1.5666 - val_ia: 0.1916 - val_loss: 0.8733 - val_mae: 0.6951 - val_rmse: 0.7317 - val_smape: 1.5974

Epoch 89/128

3830/3830 - 19s - 5ms/step - ia: 0.2988 - loss: 0.9090 - mae: 0.7105 - rmse: 0.8929 - smape: 1.5645 - val_ia: 0.1916 - val_loss: 0.8730 - val_mae: 0.6951 - val_rmse: 0.7316 - val_smape: 1.5967

Epoch 90/128

3830/3830 - 20s - 5ms/step - ia: 0.2962 - loss: 0.9118 - mae: 0.7113 - rmse: 0.8935 - smape: 1.5596 - val_ia: 0.1916 - val_loss: 0.8729 - val_mae: 0.6950 - val_rmse: 0.7315 - val_smape: 1.5962

Epoch 91/128

3830/3830 - 20s - 5ms/step - ia: 0.2971 - loss: 0.9111 - mae: 0.7111 - rmse: 0.8940 - smape: 1.5613 - val_ia: 0.1916 - val_loss: 0.8728 - val_mae: 0.6951 - val_rmse: 0.7316 - val_smape: 1.5965

Epoch 92/128

3830/3830 - 19s - 5ms/step - ia: 0.2965 - loss: 0.9053 - mae: 0.7091 - rmse: 0.8898 - smape: 1.5603 - val_ia: 0.1917 - val_loss: 0.8725 - val_mae: 0.6950 - val_rmse: 0.7315 - val_smape: 1.5956

Epoch 93/128

3830/3830 - 19s - 5ms/step - ia: 0.2968 - loss: 0.9124 - mae: 0.7103 - rmse: 0.8934 - smape: 1.5572 - val_ia: 0.1917 - val_loss: 0.8724 - val_mae: 0.6949 - val_rmse: 0.7314 - val_smape: 1.5953

Epoch 94/128

3830/3830 - 18s - 5ms/step - ia: 0.2972 - loss: 0.9098 - mae: 0.7105 - rmse: 0.8923 - smape: 1.5609 - val_ia: 0.1917 - val_loss: 0.8722 - val_mae: 0.6949 - val_rmse: 0.7314 - val_smape: 1.5950

Epoch 95/128

3830/3830 - 20s - 5ms/step - ia: 0.2968 - loss: 0.9085 - mae: 0.7103 - rmse: 0.8928 - smape: 1.5552 - val_ia: 0.1917 - val_loss: 0.8722 - val_mae: 0.6950 - val_rmse: 0.7315 - val_smape: 1.5950

Epoch 96/128

3830/3830 - 19s - 5ms/step - ia: 0.2958 - loss: 0.9149 - mae: 0.7123 - rmse: 0.8950 - smape: 1.5646 - val_ia: 0.1918 - val_loss: 0.8721 - val_mae: 0.6949 - val_rmse: 0.7314 - val_smape: 1.5949

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 15s - 61ms/step - ia: 0.2847 - loss: 0.9418 - mae: 0.7229 - rmse: 0.9651 - smape: 1.4360 - val_ia: 0.3098 - val_loss: 0.7822 - val_mae: 0.6404 - val_rmse: 0.7871 - val_smape: 1.2760

Epoch 2/128

240/240 - 4s - 15ms/step - ia: 0.3666 - loss: 0.8633 - mae: 0.6895 - rmse: 0.9232 - smape: 1.3197 - val_ia: 0.3118 - val_loss: 0.7770 - val_mae: 0.6569 - val_rmse: 0.8001 - val_smape: 1.3175

Epoch 3/128

240/240 - 4s - 17ms/step - ia: 0.3746 - loss: 0.8514 - mae: 0.6822 - rmse: 0.9171 - smape: 1.3036 - val_ia: 0.3150 - val_loss: 0.7723 - val_mae: 0.6504 - val_rmse: 0.7952 - val_smape: 1.2945

Epoch 4/128

240/240 - 4s - 15ms/step - ia: 0.3781 - loss: 0.8420 - mae: 0.6774 - rmse: 0.9132 - smape: 1.2985 - val_ia: 0.3162 - val_loss: 0.7679 - val_mae: 0.6454 - val_rmse: 0.7911 - val_smape: 1.2778

Epoch 5/128

240/240 - 3s - 14ms/step - ia: 0.3806 - loss: 0.8368 - mae: 0.6749 - rmse: 0.9092 - smape: 1.2931 - val_ia: 0.3180 - val_loss: 0.7633 - val_mae: 0.6353 - val_rmse: 0.7828 - val_smape: 1.2413

Epoch 6/128

240/240 - 3s - 15ms/step - ia: 0.3816 - loss: 0.8283 - mae: 0.6715 - rmse: 0.9055 - smape: 1.2905 - val_ia: 0.3171 - val_loss: 0.7605 - val_mae: 0.6349 - val_rmse: 0.7819 - val_smape: 1.2419

Epoch 7/128

240/240 - 5s - 21ms/step - ia: 0.3846 - loss: 0.8257 - mae: 0.6692 - rmse: 0.9039 - smape: 1.2856 - val_ia: 0.3122 - val_loss: 0.7634 - val_mae: 0.6457 - val_rmse: 0.7895 - val_smape: 1.2846

Epoch 8/128

240/240 - 3s - 15ms/step - ia: 0.3809 - loss: 0.8283 - mae: 0.6705 - rmse: 0.9048 - smape: 1.2931 - val_ia: 0.3179 - val_loss: 0.7621 - val_mae: 0.6367 - val_rmse: 0.7839 - val_smape: 1.2516

Epoch 9/128

240/240 - 4s - 15ms/step - ia: 0.3843 - loss: 0.8232 - mae: 0.6678 - rmse: 0.9028 - smape: 1.2853 - val_ia: 0.3131 - val_loss: 0.7568 - val_mae: 0.6363 - val_rmse: 0.7815 - val_smape: 1.2527

Epoch 10/128

240/240 - 4s - 15ms/step - ia: 0.3843 - loss: 0.8195 - mae: 0.6672 - rmse: 0.9009 - smape: 1.2882 - val_ia: 0.3175 - val_loss: 0.7559 - val_mae: 0.6388 - val_rmse: 0.7845 - val_smape: 1.2553

Epoch 11/128

240/240 - 3s - 14ms/step - ia: 0.3836 - loss: 0.8203 - mae: 0.6663 - rmse: 0.9013 - smape: 1.2853 - val_ia: 0.3224 - val_loss: 0.7573 - val_mae: 0.6379 - val_rmse: 0.7856 - val_smape: 1.2481

Epoch 12/128

240/240 - 4s - 15ms/step - ia: 0.3872 - loss: 0.8195 - mae: 0.6661 - rmse: 0.9003 - smape: 1.2839 - val_ia: 0.3145 - val_loss: 0.7628 - val_mae: 0.6526 - val_rmse: 0.7957 - val_smape: 1.3028

Epoch 13/128

240/240 - 4s - 15ms/step - ia: 0.3881 - loss: 0.8154 - mae: 0.6642 - rmse: 0.8982 - smape: 1.2814 - val_ia: 0.3191 - val_loss: 0.7515 - val_mae: 0.6333 - val_rmse: 0.7801 - val_smape: 1.2391

Epoch 14/128

240/240 - 4s - 15ms/step - ia: 0.3858 - loss: 0.8175 - mae: 0.6651 - rmse: 0.8993 - smape: 1.2856 - val_ia: 0.3220 - val_loss: 0.7519 - val_mae: 0.6356 - val_rmse: 0.7829 - val_smape: 1.2414

Epoch 15/128

240/240 - 3s - 14ms/step - ia: 0.3898 - loss: 0.8133 - mae: 0.6634 - rmse: 0.8972 - smape: 1.2771 - val_ia: 0.3200 - val_loss: 0.7521 - val_mae: 0.6377 - val_rmse: 0.7840 - val_smape: 1.2524

Epoch 16/128

240/240 - 4s - 15ms/step - ia: 0.3900 - loss: 0.8115 - mae: 0.6620 - rmse: 0.8956 - smape: 1.2784 - val_ia: 0.3181 - val_loss: 0.7533 - val_mae: 0.6428 - val_rmse: 0.7877 - val_smape: 1.2690

Epoch 17/128

240/240 - 3s - 14ms/step - ia: 0.3925 - loss: 0.8124 - mae: 0.6620 - rmse: 0.8964 - smape: 1.2759 - val_ia: 0.3172 - val_loss: 0.7492 - val_mae: 0.6324 - val_rmse: 0.7786 - val_smape: 1.2423

Epoch 18/128

240/240 - 4s - 15ms/step - ia: 0.3892 - loss: 0.8096 - mae: 0.6619 - rmse: 0.8951 - smape: 1.2804 - val_ia: 0.3214 - val_loss: 0.7526 - val_mae: 0.6407 - val_rmse: 0.7873 - val_smape: 1.2589

Epoch 19/128

240/240 - 5s - 22ms/step - ia: 0.3935 - loss: 0.8077 - mae: 0.6602 - rmse: 0.8943 - smape: 1.2732 - val_ia: 0.3203 - val_loss: 0.7482 - val_mae: 0.6353 - val_rmse: 0.7818 - val_smape: 1.2476

Epoch 20/128

240/240 - 4s - 15ms/step - ia: 0.3918 - loss: 0.8072 - mae: 0.6600 - rmse: 0.8942 - smape: 1.2754 - val_ia: 0.3337 - val_loss: 0.7504 - val_mae: 0.6269 - val_rmse: 0.7794 - val_smape: 1.2012

Epoch 21/128

240/240 - 5s - 21ms/step - ia: 0.3940 - loss: 0.8059 - mae: 0.6593 - rmse: 0.8916 - smape: 1.2720 - val_ia: 0.3247 - val_loss: 0.7524 - val_mae: 0.6399 - val_rmse: 0.7877 - val_smape: 1.2524

Epoch 22/128

240/240 - 4s - 15ms/step - ia: 0.3967 - loss: 0.8059 - mae: 0.6586 - rmse: 0.8927 - smape: 1.2703 - val_ia: 0.3259 - val_loss: 0.7489 - val_mae: 0.6348 - val_rmse: 0.7835 - val_smape: 1.2355

Epoch 23/128

240/240 - 4s - 15ms/step - ia: 0.3965 - loss: 0.8055 - mae: 0.6586 - rmse: 0.8929 - smape: 1.2681 - val_ia: 0.3258 - val_loss: 0.7483 - val_mae: 0.6309 - val_rmse: 0.7796 - val_smape: 1.2348

Epoch 24/128

240/240 - 4s - 15ms/step - ia: 0.3974 - loss: 0.8025 - mae: 0.6569 - rmse: 0.8905 - smape: 1.2677 - val_ia: 0.3252 - val_loss: 0.7447 - val_mae: 0.6309 - val_rmse: 0.7790 - val_smape: 1.2339

Epoch 25/128

240/240 - 4s - 15ms/step - ia: 0.3998 - loss: 0.8012 - mae: 0.6566 - rmse: 0.8900 - smape: 1.2658 - val_ia: 0.3253 - val_loss: 0.7491 - val_mae: 0.6371 - val_rmse: 0.7849 - val_smape: 1.2514

Epoch 26/128

240/240 - 5s - 21ms/step - ia: 0.4004 - loss: 0.7995 - mae: 0.6562 - rmse: 0.8893 - smape: 1.2650 - val_ia: 0.3223 - val_loss: 0.7415 - val_mae: 0.6305 - val_rmse: 0.7778 - val_smape: 1.2328

Epoch 27/128

240/240 - 4s - 15ms/step - ia: 0.3994 - loss: 0.8009 - mae: 0.6561 - rmse: 0.8894 - smape: 1.2648 - val_ia: 0.3215 - val_loss: 0.7421 - val_mae: 0.6307 - val_rmse: 0.7773 - val_smape: 1.2436

Epoch 28/128

240/240 - 4s - 15ms/step - ia: 0.4017 - loss: 0.7972 - mae: 0.6541 - rmse: 0.8887 - smape: 1.2630 - val_ia: 0.3249 - val_loss: 0.7487 - val_mae: 0.6390 - val_rmse: 0.7863 - val_smape: 1.2624

Epoch 29/128

240/240 - 4s - 15ms/step - ia: 0.4012 - loss: 0.7985 - mae: 0.6555 - rmse: 0.8884 - smape: 1.2650 - val_ia: 0.3248 - val_loss: 0.7477 - val_mae: 0.6381 - val_rmse: 0.7855 - val_smape: 1.2562

Epoch 30/128

240/240 - 4s - 15ms/step - ia: 0.4042 - loss: 0.7950 - mae: 0.6532 - rmse: 0.8873 - smape: 1.2599 - val_ia: 0.3220 - val_loss: 0.7558 - val_mae: 0.6497 - val_rmse: 0.7951 - val_smape: 1.2901

Epoch 31/128

240/240 - 3s - 14ms/step - ia: 0.4041 - loss: 0.7943 - mae: 0.6531 - rmse: 0.8867 - smape: 1.2592 - val_ia: 0.3245 - val_loss: 0.7495 - val_mae: 0.6403 - val_rmse: 0.7879 - val_smape: 1.2612

Epoch 32/128

240/240 - 3s - 15ms/step - ia: 0.4050 - loss: 0.7932 - mae: 0.6526 - rmse: 0.8854 - smape: 1.2607 - val_ia: 0.3253 - val_loss: 0.7542 - val_mae: 0.6435 - val_rmse: 0.7916 - val_smape: 1.2656

Epoch 33/128

240/240 - 4s - 15ms/step - ia: 0.4073 - loss: 0.7920 - mae: 0.6514 - rmse: 0.8851 - smape: 1.2564 - val_ia: 0.3264 - val_loss: 0.7417 - val_mae: 0.6321 - val_rmse: 0.7799 - val_smape: 1.2482

Epoch 34/128

240/240 - 4s - 15ms/step - ia: 0.4080 - loss: 0.7900 - mae: 0.6505 - rmse: 0.8842 - smape: 1.2570 - val_ia: 0.3294 - val_loss: 0.7427 - val_mae: 0.6297 - val_rmse: 0.7792 - val_smape: 1.2366

Epoch 35/128

240/240 - 3s - 15ms/step - ia: 0.4089 - loss: 0.7886 - mae: 0.6501 - rmse: 0.8826 - smape: 1.2541 - val_ia: 0.3300 - val_loss: 0.7424 - val_mae: 0.6304 - val_rmse: 0.7799 - val_smape: 1.2382

Epoch 36/128

240/240 - 5s - 22ms/step - ia: 0.4106 - loss: 0.7869 - mae: 0.6488 - rmse: 0.8820 - smape: 1.2503 - val_ia: 0.3281 - val_loss: 0.7477 - val_mae: 0.6385 - val_rmse: 0.7867 - val_smape: 1.2653

Epoch 37/128

240/240 - 3s - 14ms/step - ia: 0.4112 - loss: 0.7866 - mae: 0.6489 - rmse: 0.8821 - smape: 1.2513 - val_ia: 0.3231 - val_loss: 0.7387 - val_mae: 0.6323 - val_rmse: 0.7785 - val_smape: 1.2600

Epoch 38/128

240/240 - 4s - 15ms/step - ia: 0.4109 - loss: 0.7850 - mae: 0.6481 - rmse: 0.8807 - smape: 1.2509 - val_ia: 0.3313 - val_loss: 0.7443 - val_mae: 0.6326 - val_rmse: 0.7826 - val_smape: 1.2462

Epoch 39/128

240/240 - 4s - 15ms/step - ia: 0.4128 - loss: 0.7833 - mae: 0.6473 - rmse: 0.8815 - smape: 1.2497 - val_ia: 0.3298 - val_loss: 0.7383 - val_mae: 0.6283 - val_rmse: 0.7769 - val_smape: 1.2384

Epoch 40/128

240/240 - 3s - 15ms/step - ia: 0.4151 - loss: 0.7807 - mae: 0.6459 - rmse: 0.8785 - smape: 1.2473 - val_ia: 0.3335 - val_loss: 0.7496 - val_mae: 0.6380 - val_rmse: 0.7882 - val_smape: 1.2582

Epoch 41/128

240/240 - 4s - 15ms/step - ia: 0.4171 - loss: 0.7811 - mae: 0.6457 - rmse: 0.8788 - smape: 1.2446 - val_ia: 0.3351 - val_loss: 0.7436 - val_mae: 0.6293 - val_rmse: 0.7803 - val_smape: 1.2433

Epoch 42/128

240/240 - 4s - 15ms/step - ia: 0.4150 - loss: 0.7800 - mae: 0.6454 - rmse: 0.8777 - smape: 1.2465 - val_ia: 0.3395 - val_loss: 0.7454 - val_mae: 0.6285 - val_rmse: 0.7819 - val_smape: 1.2230

Epoch 43/128

240/240 - 4s - 15ms/step - ia: 0.4192 - loss: 0.7781 - mae: 0.6446 - rmse: 0.8777 - smape: 1.2431 - val_ia: 0.3350 - val_loss: 0.7483 - val_mae: 0.6309 - val_rmse: 0.7835 - val_smape: 1.2347

Epoch 44/128

240/240 - 4s - 15ms/step - ia: 0.4180 - loss: 0.7776 - mae: 0.6436 - rmse: 0.8768 - smape: 1.2433 - val_ia: 0.3346 - val_loss: 0.7498 - val_mae: 0.6373 - val_rmse: 0.7882 - val_smape: 1.2562

Epoch 45/128

240/240 - 4s - 15ms/step - ia: 0.4191 - loss: 0.7752 - mae: 0.6430 - rmse: 0.8769 - smape: 1.2414 - val_ia: 0.3445 - val_loss: 0.7554 - val_mae: 0.6351 - val_rmse: 0.7906 - val_smape: 1.2357

Epoch 46/128

240/240 - 4s - 15ms/step - ia: 0.4219 - loss: 0.7740 - mae: 0.6424 - rmse: 0.8752 - smape: 1.2362 - val_ia: 0.3337 - val_loss: 0.7592 - val_mae: 0.6418 - val_rmse: 0.7940 - val_smape: 1.2601

Epoch 47/128

240/240 - 4s - 15ms/step - ia: 0.4201 - loss: 0.7747 - mae: 0.6425 - rmse: 0.8756 - smape: 1.2395 - val_ia: 0.3448 - val_loss: 0.7625 - val_mae: 0.6373 - val_rmse: 0.7942 - val_smape: 1.2284

Epoch 48/128

240/240 - 4s - 15ms/step - ia: 0.4229 - loss: 0.7726 - mae: 0.6415 - rmse: 0.8747 - smape: 1.2364 - val_ia: 0.3347 - val_loss: 0.7417 - val_mae: 0.6292 - val_rmse: 0.7797 - val_smape: 1.2561

Epoch 49/128

240/240 - 3s - 15ms/step - ia: 0.4219 - loss: 0.7720 - mae: 0.6414 - rmse: 0.8742 - smape: 1.2369 - val_ia: 0.3440 - val_loss: 0.7557 - val_mae: 0.6341 - val_rmse: 0.7898 - val_smape: 1.2275

Epoch 50/128

240/240 - 3s - 15ms/step - ia: 0.4237 - loss: 0.7709 - mae: 0.6413 - rmse: 0.8726 - smape: 1.2371 - val_ia: 0.3447 - val_loss: 0.7454 - val_mae: 0.6234 - val_rmse: 0.7787 - val_smape: 1.2137

Epoch 51/128

240/240 - 3s - 14ms/step - ia: 0.4246 - loss: 0.7700 - mae: 0.6396 - rmse: 0.8722 - smape: 1.2328 - val_ia: 0.3426 - val_loss: 0.7483 - val_mae: 0.6286 - val_rmse: 0.7835 - val_smape: 1.2234

Epoch 52/128

240/240 - 3s - 14ms/step - ia: 0.4255 - loss: 0.7669 - mae: 0.6389 - rmse: 0.8689 - smape: 1.2321 - val_ia: 0.3445 - val_loss: 0.7636 - val_mae: 0.6417 - val_rmse: 0.7975 - val_smape: 1.2435

Epoch 53/128

240/240 - 4s - 15ms/step - ia: 0.4251 - loss: 0.7661 - mae: 0.6387 - rmse: 0.8718 - smape: 1.2333 - val_ia: 0.3448 - val_loss: 0.7636 - val_mae: 0.6407 - val_rmse: 0.7971 - val_smape: 1.2420

Epoch 54/128

240/240 - 4s - 15ms/step - ia: 0.4272 - loss: 0.7671 - mae: 0.6383 - rmse: 0.8713 - smape: 1.2284 - val_ia: 0.3422 - val_loss: 0.7610 - val_mae: 0.6414 - val_rmse: 0.7963 - val_smape: 1.2518

Epoch 54: early stopping

Restoring model weights from the end of the best epoch: 39.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 27s 201ms/step
 18/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 34/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
100/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
116/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
132/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

100%|██████████| 12/12 [3:37:12<00:00, 1086.06s/trial, best loss: 0.7446180315174813]

In [22]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}