Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(14)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340
2017-01-01 01:40:00 -2.220087 -1.248733 -0.988421 -0.523853 -1.516340
2017-01-01 01:50:00 -2.227367 -1.297304 -1.032325 -0.561427 -1.516340
2017-01-01 02:00:00 -2.294018 -1.371835 -1.040962 -0.604369 -1.371823
2017-01-01 02:10:00 -2.308740 -1.464790 -1.131650 -0.649995 -1.371823

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas LSTM
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades LSTM
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes LSTM, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [15]:
print(datosX[0])

[[-2.05135573  0.15144479 -0.85166941  0.03349964 -1.66085756]
 [-2.07481311 -0.43307937 -0.21109699  0.01650173 -1.66085756]
 [-2.0911524  -0.52770864 -0.28379117 -0.05506842 -1.66085756]
 [-2.12221321 -0.65164785 -0.41118591 -0.17405378 -1.66085756]
 [-2.15456823 -0.77474965 -0.50763164 -0.2447293  -1.66085756]
 [-2.16556893 -0.87272862 -0.59759968 -0.29303915 -1.66085756]
 [-2.19986525 -0.95898362 -0.68109001 -0.32166721 -1.51634012]
 [-2.22332263 -1.03518949 -0.74658674 -0.39681586 -1.51634012]
 [-2.19387957 -1.12730648 -0.83223632 -0.46391287 -1.51634012]
 [-2.22413151 -1.19597551 -0.88909611 -0.49969795 -1.51634012]
 [-2.22008713 -1.24873342 -0.98842083 -0.52385287 -1.51634012]
 [-2.22736701 -1.29730419 -1.03232523 -0.5614272  -1.51634012]]

Se dividen nuevamente los conjuntos de datos

In [16]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 12, 5)
Las dimensiones de testX son:  (10529, 12, 5)
Las dimensiones de valX son:  (5186, 12, 5)

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [18]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [19]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [20]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1], trainX.shape[2])))
    if (params['layers'] == 1):
      model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=False))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(LSTM(units=params['units'], activation=params['activation'], return_sequences=True))
          model.add(Dropout(params['dropout']))
      model.add(LSTM(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [21]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 22s - 77ms/step - ia: 0.2228 - loss: 1.1432 - mae: 0.8834 - rmse: 1.0675 - smape: 1.5343 - val_ia: 0.2102 - val_loss: 0.8748 - val_mae: 0.7789 - val_rmse: 0.9275 - val_smape: 1.8272

Epoch 2/128

287/287 - 6s - 20ms/step - ia: 0.1836 - loss: 1.0721 - mae: 0.8580 - rmse: 1.0341 - smape: 1.5959 - val_ia: 0.2126 - val_loss: 0.8646 - val_mae: 0.7741 - val_rmse: 0.9226 - val_smape: 1.9133

Epoch 3/128

287/287 - 10s - 36ms/step - ia: 0.1634 - loss: 1.0470 - mae: 0.8484 - rmse: 1.0221 - smape: 1.6285 - val_ia: 0.2137 - val_loss: 0.8614 - val_mae: 0.7725 - val_rmse: 0.9210 - val_smape: 1.9470

Epoch 4/128

287/287 - 5s - 17ms/step - ia: 0.1454 - loss: 1.0334 - mae: 0.8435 - rmse: 1.0156 - smape: 1.6574 - val_ia: 0.2142 - val_loss: 0.8599 - val_mae: 0.7719 - val_rmse: 0.9202 - val_smape: 1.9424

Epoch 5/128

287/287 - 5s - 17ms/step - ia: 0.1403 - loss: 1.0163 - mae: 0.8364 - rmse: 1.0071 - smape: 1.6709 - val_ia: 0.2156 - val_loss: 0.8554 - val_mae: 0.7698 - val_rmse: 0.9176 - val_smape: 1.8798

Epoch 6/128

287/287 - 4s - 15ms/step - ia: 0.1733 - loss: 0.9587 - mae: 0.8128 - rmse: 0.9779 - smape: 1.6176 - val_ia: 0.2555 - val_loss: 0.8705 - val_mae: 0.7718 - val_rmse: 0.9219 - val_smape: 1.5226

Epoch 7/128

287/287 - 4s - 15ms/step - ia: 0.3759 - loss: 0.7548 - mae: 0.7158 - rmse: 0.8669 - smape: 1.2971 - val_ia: 0.3358 - val_loss: 1.1232 - val_mae: 0.8817 - val_rmse: 1.0386 - val_smape: 1.3837

Epoch 8/128

287/287 - 5s - 18ms/step - ia: 0.5176 - loss: 0.6349 - mae: 0.6473 - rmse: 0.7957 - smape: 1.0862 - val_ia: 0.3540 - val_loss: 1.1891 - val_mae: 0.9121 - val_rmse: 1.0662 - val_smape: 1.3811

Epoch 9/128

287/287 - 5s - 18ms/step - ia: 0.5596 - loss: 0.5810 - mae: 0.6143 - rmse: 0.7610 - smape: 1.0280 - val_ia: 0.3679 - val_loss: 1.1669 - val_mae: 0.9024 - val_rmse: 1.0546 - val_smape: 1.3707

Epoch 10/128

287/287 - 4s - 15ms/step - ia: 0.5781 - loss: 0.5481 - mae: 0.5963 - rmse: 0.7388 - smape: 0.9993 - val_ia: 0.3790 - val_loss: 1.1486 - val_mae: 0.8936 - val_rmse: 1.0450 - val_smape: 1.3613

Epoch 11/128

287/287 - 5s - 18ms/step - ia: 0.5890 - loss: 0.5311 - mae: 0.5845 - rmse: 0.7277 - smape: 0.9814 - val_ia: 0.3921 - val_loss: 1.1506 - val_mae: 0.8922 - val_rmse: 1.0447 - val_smape: 1.3447

Epoch 12/128

287/287 - 4s - 16ms/step - ia: 0.6015 - loss: 0.5094 - mae: 0.5720 - rmse: 0.7125 - smape: 0.9604 - val_ia: 0.4038 - val_loss: 1.1193 - val_mae: 0.8755 - val_rmse: 1.0296 - val_smape: 1.3252

Epoch 13/128

287/287 - 5s - 19ms/step - ia: 0.6080 - loss: 0.4973 - mae: 0.5643 - rmse: 0.7039 - smape: 0.9517 - val_ia: 0.4111 - val_loss: 1.1052 - val_mae: 0.8677 - val_rmse: 1.0224 - val_smape: 1.3134

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.6138 - loss: 0.4857 - mae: 0.5577 - rmse: 0.6956 - smape: 0.9418 - val_ia: 0.4305 - val_loss: 1.0800 - val_mae: 0.8490 - val_rmse: 1.0104 - val_smape: 1.2721

Epoch 15/128

287/287 - 4s - 15ms/step - ia: 0.6190 - loss: 0.4741 - mae: 0.5514 - rmse: 0.6873 - smape: 0.9350 - val_ia: 0.4426 - val_loss: 1.0720 - val_mae: 0.8406 - val_rmse: 1.0063 - val_smape: 1.2480

Epoch 16/128

287/287 - 5s - 16ms/step - ia: 0.6275 - loss: 0.4625 - mae: 0.5424 - rmse: 0.6787 - smape: 0.9219 - val_ia: 0.4488 - val_loss: 1.0645 - val_mae: 0.8344 - val_rmse: 1.0029 - val_smape: 1.2348

Epoch 17/128

287/287 - 5s - 17ms/step - ia: 0.6311 - loss: 0.4538 - mae: 0.5380 - rmse: 0.6723 - smape: 0.9205 - val_ia: 0.4531 - val_loss: 1.0462 - val_mae: 0.8250 - val_rmse: 0.9941 - val_smape: 1.2266

Epoch 18/128

287/287 - 5s - 18ms/step - ia: 0.6314 - loss: 0.4524 - mae: 0.5372 - rmse: 0.6715 - smape: 0.9159 - val_ia: 0.4676 - val_loss: 1.0261 - val_mae: 0.8093 - val_rmse: 0.9849 - val_smape: 1.1961

Epoch 19/128

287/287 - 4s - 16ms/step - ia: 0.6371 - loss: 0.4442 - mae: 0.5306 - rmse: 0.6651 - smape: 0.9103 - val_ia: 0.4795 - val_loss: 0.9832 - val_mae: 0.7851 - val_rmse: 0.9651 - val_smape: 1.1709

Epoch 20/128

287/287 - 4s - 14ms/step - ia: 0.6391 - loss: 0.4382 - mae: 0.5272 - rmse: 0.6607 - smape: 0.9081 - val_ia: 0.4885 - val_loss: 0.9640 - val_mae: 0.7747 - val_rmse: 0.9556 - val_smape: 1.1574

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 4:38 2s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
154/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step

  8%|▊         | 1/12 [02:04<22:50, 124.57s/trial, best loss: 1.0126952786554486]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 71s - 31ms/step - ia: 0.7812 - loss: 0.1874 - mae: 0.3200 - rmse: 0.4075 - smape: 0.6825 - val_ia: 0.3404 - val_loss: 0.1990 - val_mae: 0.3515 - val_rmse: 0.3879 - val_smape: 0.7344

Epoch 2/128

2292/2292 - 51s - 22ms/step - ia: 0.8487 - loss: 0.0971 - mae: 0.2283 - rmse: 0.3012 - smape: 0.5535 - val_ia: 0.3901 - val_loss: 0.1986 - val_mae: 0.3252 - val_rmse: 0.3576 - val_smape: 0.6808

Epoch 3/128

2292/2292 - 48s - 21ms/step - ia: 0.8614 - loss: 0.0830 - mae: 0.2101 - rmse: 0.2779 - smape: 0.5236 - val_ia: 0.3435 - val_loss: 0.2175 - val_mae: 0.3567 - val_rmse: 0.3938 - val_smape: 0.7254

Epoch 4/128

2292/2292 - 52s - 23ms/step - ia: 0.8695 - loss: 0.0751 - mae: 0.1984 - rmse: 0.2642 - smape: 0.5002 - val_ia: 0.3606 - val_loss: 0.1826 - val_mae: 0.3350 - val_rmse: 0.3617 - val_smape: 0.7109

Epoch 5/128

2292/2292 - 76s - 33ms/step - ia: 0.8735 - loss: 0.0707 - mae: 0.1921 - rmse: 0.2560 - smape: 0.4879 - val_ia: 0.3740 - val_loss: 0.2283 - val_mae: 0.3658 - val_rmse: 0.3878 - val_smape: 0.7563

Epoch 6/128

2292/2292 - 91s - 40ms/step - ia: 0.8789 - loss: 0.0652 - mae: 0.1846 - rmse: 0.2461 - smape: 0.4769 - val_ia: 0.3596 - val_loss: 0.2017 - val_mae: 0.3453 - val_rmse: 0.3734 - val_smape: 0.7313

Epoch 7/128

2292/2292 - 37s - 16ms/step - ia: 0.8831 - loss: 0.0616 - mae: 0.1785 - rmse: 0.2383 - smape: 0.4638 - val_ia: 0.3321 - val_loss: 0.2257 - val_mae: 0.3645 - val_rmse: 0.3982 - val_smape: 0.7640

Epoch 8/128

2292/2292 - 58s - 25ms/step - ia: 0.8883 - loss: 0.0568 - mae: 0.1705 - rmse: 0.2287 - smape: 0.4496 - val_ia: 0.3505 - val_loss: 0.2380 - val_mae: 0.3669 - val_rmse: 0.3996 - val_smape: 0.7575

Epoch 9/128

2292/2292 - 48s - 21ms/step - ia: 0.8925 - loss: 0.0534 - mae: 0.1644 - rmse: 0.2213 - smape: 0.4344 - val_ia: 0.3587 - val_loss: 0.2443 - val_mae: 0.3719 - val_rmse: 0.4059 - val_smape: 0.7616

Epoch 10/128

2292/2292 - 45s - 20ms/step - ia: 0.8968 - loss: 0.0499 - mae: 0.1578 - rmse: 0.2135 - smape: 0.4213 - val_ia: 0.3544 - val_loss: 0.2434 - val_mae: 0.3677 - val_rmse: 0.4025 - val_smape: 0.7571

Epoch 11/128

2292/2292 - 53s - 23ms/step - ia: 0.8984 - loss: 0.0486 - mae: 0.1559 - rmse: 0.2106 - smape: 0.4187 - val_ia: 0.3686 - val_loss: 0.1873 - val_mae: 0.3293 - val_rmse: 0.3637 - val_smape: 0.7067

Epoch 12/128

2292/2292 - 58s - 25ms/step - ia: 0.9019 - loss: 0.0451 - mae: 0.1502 - rmse: 0.2030 - smape: 0.4079 - val_ia: 0.3491 - val_loss: 0.2199 - val_mae: 0.3528 - val_rmse: 0.3907 - val_smape: 0.7296

Epoch 13/128

2292/2292 - 36s - 16ms/step - ia: 0.9047 - loss: 0.0435 - mae: 0.1465 - rmse: 0.1988 - smape: 0.4006 - val_ia: 0.3391 - val_loss: 0.2152 - val_mae: 0.3508 - val_rmse: 0.3916 - val_smape: 0.7242

Epoch 14/128

2292/2292 - 65s - 28ms/step - ia: 0.9055 - loss: 0.0426 - mae: 0.1447 - rmse: 0.1975 - smape: 0.3941 - val_ia: 0.3348 - val_loss: 0.2535 - val_mae: 0.3721 - val_rmse: 0.4134 - val_smape: 0.7613

Epoch 15/128

2292/2292 - 83s - 36ms/step - ia: 0.9091 - loss: 0.0391 - mae: 0.1397 - rmse: 0.1888 - smape: 0.3867 - val_ia: 0.3678 - val_loss: 0.2122 - val_mae: 0.3310 - val_rmse: 0.3727 - val_smape: 0.6763

Epoch 16/128

2292/2292 - 49s - 22ms/step - ia: 0.9097 - loss: 0.0391 - mae: 0.1386 - rmse: 0.1883 - smape: 0.3843 - val_ia: 0.3673 - val_loss: 0.2865 - val_mae: 0.3756 - val_rmse: 0.4196 - val_smape: 0.7293

Epoch 17/128

2292/2292 - 48s - 21ms/step - ia: 0.9120 - loss: 0.0373 - mae: 0.1351 - rmse: 0.1833 - smape: 0.3783 - val_ia: 0.3554 - val_loss: 0.2455 - val_mae: 0.3547 - val_rmse: 0.3996 - val_smape: 0.7400

Epoch 18/128

2292/2292 - 43s - 19ms/step - ia: 0.9143 - loss: 0.0353 - mae: 0.1318 - rmse: 0.1790 - smape: 0.3679 - val_ia: 0.3531 - val_loss: 0.2145 - val_mae: 0.3470 - val_rmse: 0.3917 - val_smape: 0.7272

Epoch 19/128

2292/2292 - 55s - 24ms/step - ia: 0.9160 - loss: 0.0340 - mae: 0.1293 - rmse: 0.1757 - smape: 0.3628 - val_ia: 0.3588 - val_loss: 0.2407 - val_mae: 0.3551 - val_rmse: 0.4018 - val_smape: 0.7106

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:29 920ms/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
 12/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 18/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 29/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 35/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 41/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 48/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 66/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 72/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
 78/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
 98/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
125/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
136/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
156/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
161/163 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

 17%|█▋        | 2/12 [19:57<1:53:45, 682.51s/trial, best loss: 0.4360207921761623]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 65s - 14ms/step - ia: 0.2040 - loss: 0.9991 - mae: 0.8293 - rmse: 0.9806 - smape: 1.9730 - val_ia: 0.1379 - val_loss: 0.8601 - val_mae: 0.7715 - val_rmse: 0.7884 - val_smape: 1.9705

Epoch 2/128

4584/4584 - 81s - 18ms/step - ia: 0.2046 - loss: 0.9976 - mae: 0.8285 - rmse: 0.9791 - smape: 1.9673 - val_ia: 0.1380 - val_loss: 0.8588 - val_mae: 0.7710 - val_rmse: 0.7879 - val_smape: 1.9599

Epoch 3/128

4584/4584 - 45s - 10ms/step - ia: 0.2099 - loss: 0.9958 - mae: 0.8277 - rmse: 0.9784 - smape: 1.9570 - val_ia: 0.1381 - val_loss: 0.8571 - val_mae: 0.7704 - val_rmse: 0.7872 - val_smape: 1.9475

Epoch 4/128

4584/4584 - 78s - 17ms/step - ia: 0.2074 - loss: 0.9936 - mae: 0.8266 - rmse: 0.9769 - smape: 1.9463 - val_ia: 0.1383 - val_loss: 0.8549 - val_mae: 0.7695 - val_rmse: 0.7863 - val_smape: 1.9318

Epoch 5/128

4584/4584 - 33s - 7ms/step - ia: 0.2082 - loss: 0.9903 - mae: 0.8252 - rmse: 0.9758 - smape: 1.9304 - val_ia: 0.1386 - val_loss: 0.8518 - val_mae: 0.7681 - val_rmse: 0.7850 - val_smape: 1.9125

Epoch 6/128

4584/4584 - 34s - 7ms/step - ia: 0.2079 - loss: 0.9855 - mae: 0.8231 - rmse: 0.9743 - smape: 1.9106 - val_ia: 0.1390 - val_loss: 0.8472 - val_mae: 0.7661 - val_rmse: 0.7829 - val_smape: 1.8869

Epoch 7/128

4584/4584 - 35s - 8ms/step - ia: 0.2126 - loss: 0.9789 - mae: 0.8202 - rmse: 0.9698 - smape: 1.8861 - val_ia: 0.1396 - val_loss: 0.8404 - val_mae: 0.7630 - val_rmse: 0.7799 - val_smape: 1.8541

Epoch 8/128

4584/4584 - 41s - 9ms/step - ia: 0.2157 - loss: 0.9692 - mae: 0.8161 - rmse: 0.9649 - smape: 1.8562 - val_ia: 0.1406 - val_loss: 0.8313 - val_mae: 0.7588 - val_rmse: 0.7757 - val_smape: 1.8118

Epoch 9/128

4584/4584 - 34s - 7ms/step - ia: 0.2192 - loss: 0.9552 - mae: 0.8100 - rmse: 0.9583 - smape: 1.8151 - val_ia: 0.1421 - val_loss: 0.8193 - val_mae: 0.7532 - val_rmse: 0.7701 - val_smape: 1.7603

Epoch 10/128

4584/4584 - 35s - 8ms/step - ia: 0.2285 - loss: 0.9360 - mae: 0.8018 - rmse: 0.9486 - smape: 1.7683 - val_ia: 0.1437 - val_loss: 0.8020 - val_mae: 0.7448 - val_rmse: 0.7617 - val_smape: 1.6975

Epoch 11/128

4584/4584 - 40s - 9ms/step - ia: 0.2437 - loss: 0.9085 - mae: 0.7897 - rmse: 0.9340 - smape: 1.7072 - val_ia: 0.1471 - val_loss: 0.7771 - val_mae: 0.7320 - val_rmse: 0.7490 - val_smape: 1.6182

Epoch 12/128

4584/4584 - 35s - 8ms/step - ia: 0.2667 - loss: 0.8696 - mae: 0.7716 - rmse: 0.9127 - smape: 1.6312 - val_ia: 0.1520 - val_loss: 0.7439 - val_mae: 0.7136 - val_rmse: 0.7310 - val_smape: 1.5222

Epoch 13/128

4584/4584 - 40s - 9ms/step - ia: 0.3044 - loss: 0.8201 - mae: 0.7460 - rmse: 0.8859 - smape: 1.5442 - val_ia: 0.1564 - val_loss: 0.7081 - val_mae: 0.6907 - val_rmse: 0.7087 - val_smape: 1.4177

Epoch 14/128

4584/4584 - 36s - 8ms/step - ia: 0.3495 - loss: 0.7698 - mae: 0.7166 - rmse: 0.8572 - smape: 1.4549 - val_ia: 0.1612 - val_loss: 0.6908 - val_mae: 0.6757 - val_rmse: 0.6943 - val_smape: 1.3358

Epoch 15/128

4584/4584 - 35s - 8ms/step - ia: 0.3799 - loss: 0.7312 - mae: 0.6958 - rmse: 0.8351 - smape: 1.3827 - val_ia: 0.1582 - val_loss: 0.7028 - val_mae: 0.6790 - val_rmse: 0.6972 - val_smape: 1.2888

Epoch 16/128

4584/4584 - 46s - 10ms/step - ia: 0.4069 - loss: 0.6954 - mae: 0.6776 - rmse: 0.8144 - smape: 1.3191 - val_ia: 0.1554 - val_loss: 0.7338 - val_mae: 0.6928 - val_rmse: 0.7106 - val_smape: 1.2610

Epoch 17/128

4584/4584 - 39s - 8ms/step - ia: 0.4326 - loss: 0.6632 - mae: 0.6613 - rmse: 0.7955 - smape: 1.2672 - val_ia: 0.1565 - val_loss: 0.7696 - val_mae: 0.7089 - val_rmse: 0.7271 - val_smape: 1.2453

Epoch 18/128

4584/4584 - 34s - 8ms/step - ia: 0.4480 - loss: 0.6464 - mae: 0.6515 - rmse: 0.7847 - smape: 1.2358 - val_ia: 0.1579 - val_loss: 0.7899 - val_mae: 0.7182 - val_rmse: 0.7367 - val_smape: 1.2389

Epoch 19/128

4584/4584 - 34s - 7ms/step - ia: 0.4597 - loss: 0.6344 - mae: 0.6439 - rmse: 0.7767 - smape: 1.2189 - val_ia: 0.1584 - val_loss: 0.8030 - val_mae: 0.7245 - val_rmse: 0.7432 - val_smape: 1.2359

Epoch 20/128

4584/4584 - 34s - 7ms/step - ia: 0.4642 - loss: 0.6253 - mae: 0.6395 - rmse: 0.7721 - smape: 1.2075 - val_ia: 0.1578 - val_loss: 0.8149 - val_mae: 0.7304 - val_rmse: 0.7493 - val_smape: 1.2340

Epoch 21/128

4584/4584 - 43s - 9ms/step - ia: 0.4731 - loss: 0.6141 - mae: 0.6326 - rmse: 0.7636 - smape: 1.1931 - val_ia: 0.1567 - val_loss: 0.8285 - val_mae: 0.7372 - val_rmse: 0.7562 - val_smape: 1.2332

Epoch 22/128

4584/4584 - 40s - 9ms/step - ia: 0.4792 - loss: 0.6054 - mae: 0.6277 - rmse: 0.7582 - smape: 1.1807 - val_ia: 0.1572 - val_loss: 0.8418 - val_mae: 0.7440 - val_rmse: 0.7631 - val_smape: 1.2336

Epoch 23/128

4584/4584 - 34s - 7ms/step - ia: 0.4853 - loss: 0.5956 - mae: 0.6223 - rmse: 0.7522 - smape: 1.1702 - val_ia: 0.1574 - val_loss: 0.8573 - val_mae: 0.7516 - val_rmse: 0.7709 - val_smape: 1.2343

Epoch 24/128

4584/4584 - 35s - 8ms/step - ia: 0.4918 - loss: 0.5867 - mae: 0.6179 - rmse: 0.7467 - smape: 1.1614 - val_ia: 0.1573 - val_loss: 0.8672 - val_mae: 0.7563 - val_rmse: 0.7757 - val_smape: 1.2337

Epoch 25/128

4584/4584 - 34s - 7ms/step - ia: 0.4972 - loss: 0.5791 - mae: 0.6137 - rmse: 0.7419 - smape: 1.1529 - val_ia: 0.1562 - val_loss: 0.8843 - val_mae: 0.7642 - val_rmse: 0.7836 - val_smape: 1.2350

Epoch 26/128

4584/4584 - 34s - 7ms/step - ia: 0.5011 - loss: 0.5724 - mae: 0.6102 - rmse: 0.7371 - smape: 1.1432 - val_ia: 0.1556 - val_loss: 0.9035 - val_mae: 0.7727 - val_rmse: 0.7921 - val_smape: 1.2365

Epoch 27/128

4584/4584 - 43s - 9ms/step - ia: 0.5077 - loss: 0.5617 - mae: 0.6050 - rmse: 0.7309 - smape: 1.1311 - val_ia: 0.1546 - val_loss: 0.9222 - val_mae: 0.7805 - val_rmse: 0.7999 - val_smape: 1.2377

Epoch 28/128

4584/4584 - 34s - 7ms/step - ia: 0.5144 - loss: 0.5526 - mae: 0.5997 - rmse: 0.7247 - smape: 1.1175 - val_ia: 0.1537 - val_loss: 0.9469 - val_mae: 0.7906 - val_rmse: 0.8100 - val_smape: 1.2396

Epoch 29/128

4584/4584 - 34s - 7ms/step - ia: 0.5190 - loss: 0.5447 - mae: 0.5958 - rmse: 0.7195 - smape: 1.1053 - val_ia: 0.1530 - val_loss: 0.9713 - val_mae: 0.8000 - val_rmse: 0.8196 - val_smape: 1.2410

Epoch 29: early stopping

Restoring model weights from the end of the best epoch: 14.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:09 800ms/step
 14/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 73/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

 25%|██▌       | 3/12 [39:43<2:16:50, 912.32s/trial, best loss: 0.4360207921761623]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 19s - 17ms/step - ia: 0.2761 - loss: 0.8261 - mae: 0.7622 - rmse: 0.9032 - smape: 1.5085 - val_ia: 0.2552 - val_loss: 0.8102 - val_mae: 0.7357 - val_rmse: 0.8023 - val_smape: 1.3357

Epoch 2/128

1146/1146 - 13s - 11ms/step - ia: 0.5205 - loss: 0.5639 - mae: 0.6138 - rmse: 0.7462 - smape: 1.1100 - val_ia: 0.2575 - val_loss: 1.3047 - val_mae: 0.9507 - val_rmse: 1.0214 - val_smape: 1.3731

Epoch 3/128

1146/1146 - 14s - 12ms/step - ia: 0.5939 - loss: 0.4847 - mae: 0.5586 - rmse: 0.6913 - smape: 0.9880 - val_ia: 0.2497 - val_loss: 1.4126 - val_mae: 1.0008 - val_rmse: 1.0685 - val_smape: 1.3855

Epoch 4/128

1146/1146 - 13s - 12ms/step - ia: 0.6125 - loss: 0.4555 - mae: 0.5424 - rmse: 0.6703 - smape: 0.9513 - val_ia: 0.2503 - val_loss: 1.4276 - val_mae: 1.0086 - val_rmse: 1.0758 - val_smape: 1.3748

Epoch 5/128

1146/1146 - 12s - 11ms/step - ia: 0.6263 - loss: 0.4324 - mae: 0.5285 - rmse: 0.6530 - smape: 0.9275 - val_ia: 0.2587 - val_loss: 1.3437 - val_mae: 0.9698 - val_rmse: 1.0399 - val_smape: 1.3274

Epoch 6/128

1146/1146 - 23s - 20ms/step - ia: 0.6397 - loss: 0.4115 - mae: 0.5154 - rmse: 0.6371 - smape: 0.9058 - val_ia: 0.2654 - val_loss: 1.2535 - val_mae: 0.9324 - val_rmse: 1.0029 - val_smape: 1.2945

Epoch 7/128

1146/1146 - 14s - 12ms/step - ia: 0.6492 - loss: 0.3942 - mae: 0.5046 - rmse: 0.6235 - smape: 0.8889 - val_ia: 0.2722 - val_loss: 1.2014 - val_mae: 0.9053 - val_rmse: 0.9788 - val_smape: 1.2613

Epoch 8/128

1146/1146 - 14s - 12ms/step - ia: 0.6592 - loss: 0.3774 - mae: 0.4941 - rmse: 0.6100 - smape: 0.8719 - val_ia: 0.2829 - val_loss: 1.0857 - val_mae: 0.8527 - val_rmse: 0.9280 - val_smape: 1.2265

Epoch 9/128

1146/1146 - 14s - 12ms/step - ia: 0.6685 - loss: 0.3612 - mae: 0.4831 - rmse: 0.5965 - smape: 0.8538 - val_ia: 0.2886 - val_loss: 1.0008 - val_mae: 0.8149 - val_rmse: 0.8899 - val_smape: 1.2064

Epoch 10/128

1146/1146 - 21s - 18ms/step - ia: 0.6773 - loss: 0.3484 - mae: 0.4749 - rmse: 0.5860 - smape: 0.8408 - val_ia: 0.2953 - val_loss: 0.9026 - val_mae: 0.7757 - val_rmse: 0.8469 - val_smape: 1.1933

Epoch 11/128

1146/1146 - 14s - 12ms/step - ia: 0.6809 - loss: 0.3401 - mae: 0.4697 - rmse: 0.5792 - smape: 0.8352 - val_ia: 0.2965 - val_loss: 0.8753 - val_mae: 0.7627 - val_rmse: 0.8338 - val_smape: 1.1823

Epoch 12/128

1146/1146 - 14s - 12ms/step - ia: 0.6882 - loss: 0.3306 - mae: 0.4622 - rmse: 0.5709 - smape: 0.8242 - val_ia: 0.3007 - val_loss: 0.8069 - val_mae: 0.7349 - val_rmse: 0.8025 - val_smape: 1.1707

Epoch 13/128

1146/1146 - 13s - 11ms/step - ia: 0.6924 - loss: 0.3239 - mae: 0.4576 - rmse: 0.5653 - smape: 0.8174 - val_ia: 0.3018 - val_loss: 0.7786 - val_mae: 0.7233 - val_rmse: 0.7891 - val_smape: 1.1597

Epoch 14/128

1146/1146 - 13s - 11ms/step - ia: 0.6962 - loss: 0.3171 - mae: 0.4521 - rmse: 0.5587 - smape: 0.8113 - val_ia: 0.3038 - val_loss: 0.7485 - val_mae: 0.7109 - val_rmse: 0.7752 - val_smape: 1.1485

Epoch 15/128

1146/1146 - 14s - 12ms/step - ia: 0.6995 - loss: 0.3139 - mae: 0.4492 - rmse: 0.5561 - smape: 0.8074 - val_ia: 0.3068 - val_loss: 0.7188 - val_mae: 0.6988 - val_rmse: 0.7603 - val_smape: 1.1394

Epoch 16/128

1146/1146 - 14s - 12ms/step - ia: 0.7033 - loss: 0.3083 - mae: 0.4442 - rmse: 0.5511 - smape: 0.8025 - val_ia: 0.3072 - val_loss: 0.7116 - val_mae: 0.6956 - val_rmse: 0.7567 - val_smape: 1.1334

Epoch 17/128

1146/1146 - 21s - 18ms/step - ia: 0.7075 - loss: 0.3016 - mae: 0.4395 - rmse: 0.5451 - smape: 0.7985 - val_ia: 0.3112 - val_loss: 0.6762 - val_mae: 0.6796 - val_rmse: 0.7397 - val_smape: 1.1171

Epoch 18/128

1146/1146 - 21s - 18ms/step - ia: 0.7099 - loss: 0.2979 - mae: 0.4368 - rmse: 0.5416 - smape: 0.7964 - val_ia: 0.3144 - val_loss: 0.6517 - val_mae: 0.6685 - val_rmse: 0.7272 - val_smape: 1.1037

Epoch 19/128

1146/1146 - 14s - 12ms/step - ia: 0.7128 - loss: 0.2927 - mae: 0.4328 - rmse: 0.5365 - smape: 0.7925 - val_ia: 0.3229 - val_loss: 0.5927 - val_mae: 0.6405 - val_rmse: 0.6977 - val_smape: 1.0795

Epoch 20/128

1146/1146 - 14s - 12ms/step - ia: 0.7159 - loss: 0.2887 - mae: 0.4283 - rmse: 0.5331 - smape: 0.7891 - val_ia: 0.3256 - val_loss: 0.5828 - val_mae: 0.6351 - val_rmse: 0.6917 - val_smape: 1.0688

Epoch 21/128

1146/1146 - 21s - 18ms/step - ia: 0.7202 - loss: 0.2827 - mae: 0.4228 - rmse: 0.5276 - smape: 0.7846 - val_ia: 0.3310 - val_loss: 0.5566 - val_mae: 0.6206 - val_rmse: 0.6774 - val_smape: 1.0542

Epoch 22/128

1146/1146 - 14s - 12ms/step - ia: 0.7225 - loss: 0.2798 - mae: 0.4202 - rmse: 0.5246 - smape: 0.7819 - val_ia: 0.3379 - val_loss: 0.5252 - val_mae: 0.6032 - val_rmse: 0.6597 - val_smape: 1.0316

Epoch 23/128

1146/1146 - 14s - 12ms/step - ia: 0.7257 - loss: 0.2742 - mae: 0.4159 - rmse: 0.5198 - smape: 0.7799 - val_ia: 0.3453 - val_loss: 0.4919 - val_mae: 0.5844 - val_rmse: 0.6416 - val_smape: 1.0203

Epoch 24/128

1146/1146 - 12s - 10ms/step - ia: 0.7273 - loss: 0.2716 - mae: 0.4136 - rmse: 0.5168 - smape: 0.7791 - val_ia: 0.3543 - val_loss: 0.4590 - val_mae: 0.5640 - val_rmse: 0.6211 - val_smape: 1.0015

Epoch 25/128

1146/1146 - 14s - 12ms/step - ia: 0.7306 - loss: 0.2672 - mae: 0.4088 - rmse: 0.5127 - smape: 0.7742 - val_ia: 0.3643 - val_loss: 0.4256 - val_mae: 0.5438 - val_rmse: 0.5996 - val_smape: 0.9841

Epoch 26/128

1146/1146 - 14s - 12ms/step - ia: 0.7328 - loss: 0.2634 - mae: 0.4056 - rmse: 0.5088 - smape: 0.7720 - val_ia: 0.3735 - val_loss: 0.3987 - val_mae: 0.5257 - val_rmse: 0.5809 - val_smape: 0.9643

Epoch 27/128

1146/1146 - 14s - 12ms/step - ia: 0.7363 - loss: 0.2580 - mae: 0.4006 - rmse: 0.5032 - smape: 0.7659 - val_ia: 0.3734 - val_loss: 0.3952 - val_mae: 0.5237 - val_rmse: 0.5800 - val_smape: 0.9704

Epoch 28/128

1146/1146 - 21s - 18ms/step - ia: 0.7386 - loss: 0.2539 - mae: 0.3973 - rmse: 0.4999 - smape: 0.7670 - val_ia: 0.3767 - val_loss: 0.3860 - val_mae: 0.5178 - val_rmse: 0.5736 - val_smape: 0.9676

Epoch 29/128

1146/1146 - 12s - 10ms/step - ia: 0.7413 - loss: 0.2485 - mae: 0.3928 - rmse: 0.4944 - smape: 0.7629 - val_ia: 0.3887 - val_loss: 0.3552 - val_mae: 0.4961 - val_rmse: 0.5519 - val_smape: 0.9495

Epoch 30/128

1146/1146 - 14s - 12ms/step - ia: 0.7435 - loss: 0.2451 - mae: 0.3891 - rmse: 0.4910 - smape: 0.7615 - val_ia: 0.3992 - val_loss: 0.3328 - val_mae: 0.4792 - val_rmse: 0.5344 - val_smape: 0.9347

Epoch 31/128

1146/1146 - 14s - 13ms/step - ia: 0.7453 - loss: 0.2432 - mae: 0.3870 - rmse: 0.4887 - smape: 0.7597 - val_ia: 0.4062 - val_loss: 0.3181 - val_mae: 0.4681 - val_rmse: 0.5227 - val_smape: 0.9274

Epoch 32/128

1146/1146 - 14s - 12ms/step - ia: 0.7474 - loss: 0.2397 - mae: 0.3841 - rmse: 0.4851 - smape: 0.7556 - val_ia: 0.4180 - val_loss: 0.2976 - val_mae: 0.4513 - val_rmse: 0.5052 - val_smape: 0.9121

Epoch 33/128

1146/1146 - 14s - 12ms/step - ia: 0.7501 - loss: 0.2347 - mae: 0.3794 - rmse: 0.4799 - smape: 0.7518 - val_ia: 0.4178 - val_loss: 0.2962 - val_mae: 0.4505 - val_rmse: 0.5049 - val_smape: 0.9132

Epoch 34/128

1146/1146 - 13s - 12ms/step - ia: 0.7513 - loss: 0.2328 - mae: 0.3780 - rmse: 0.4783 - smape: 0.7507 - val_ia: 0.4293 - val_loss: 0.2764 - val_mae: 0.4340 - val_rmse: 0.4864 - val_smape: 0.8962

Epoch 35/128

1146/1146 - 14s - 12ms/step - ia: 0.7546 - loss: 0.2278 - mae: 0.3734 - rmse: 0.4728 - smape: 0.7482 - val_ia: 0.4399 - val_loss: 0.2632 - val_mae: 0.4210 - val_rmse: 0.4724 - val_smape: 0.8798

Epoch 36/128

1146/1146 - 14s - 12ms/step - ia: 0.7566 - loss: 0.2236 - mae: 0.3701 - rmse: 0.4685 - smape: 0.7437 - val_ia: 0.4429 - val_loss: 0.2599 - val_mae: 0.4177 - val_rmse: 0.4681 - val_smape: 0.8822

Epoch 37/128

1146/1146 - 13s - 12ms/step - ia: 0.7593 - loss: 0.2189 - mae: 0.3656 - rmse: 0.4633 - smape: 0.7401 - val_ia: 0.4457 - val_loss: 0.2546 - val_mae: 0.4140 - val_rmse: 0.4637 - val_smape: 0.8800

Epoch 38/128

1146/1146 - 14s - 12ms/step - ia: 0.7604 - loss: 0.2168 - mae: 0.3634 - rmse: 0.4611 - smape: 0.7363 - val_ia: 0.4594 - val_loss: 0.2404 - val_mae: 0.3978 - val_rmse: 0.4470 - val_smape: 0.8623

Epoch 39/128

1146/1146 - 14s - 12ms/step - ia: 0.7632 - loss: 0.2138 - mae: 0.3602 - rmse: 0.4578 - smape: 0.7344 - val_ia: 0.4652 - val_loss: 0.2383 - val_mae: 0.3936 - val_rmse: 0.4424 - val_smape: 0.8551

Epoch 40/128

1146/1146 - 14s - 12ms/step - ia: 0.7659 - loss: 0.2105 - mae: 0.3565 - rmse: 0.4540 - smape: 0.7247 - val_ia: 0.4571 - val_loss: 0.2416 - val_mae: 0.4009 - val_rmse: 0.4495 - val_smape: 0.8733

Epoch 41/128

1146/1146 - 14s - 12ms/step - ia: 0.7658 - loss: 0.2087 - mae: 0.3556 - rmse: 0.4523 - smape: 0.7266 - val_ia: 0.4713 - val_loss: 0.2298 - val_mae: 0.3855 - val_rmse: 0.4335 - val_smape: 0.8507

Epoch 42/128

1146/1146 - 21s - 19ms/step - ia: 0.7672 - loss: 0.2061 - mae: 0.3537 - rmse: 0.4496 - smape: 0.7271 - val_ia: 0.4758 - val_loss: 0.2242 - val_mae: 0.3792 - val_rmse: 0.4268 - val_smape: 0.8383

Epoch 43/128

1146/1146 - 21s - 18ms/step - ia: 0.7717 - loss: 0.2014 - mae: 0.3479 - rmse: 0.4446 - smape: 0.7169 - val_ia: 0.4738 - val_loss: 0.2225 - val_mae: 0.3797 - val_rmse: 0.4269 - val_smape: 0.8470

Epoch 44/128

1146/1146 - 14s - 12ms/step - ia: 0.7721 - loss: 0.1993 - mae: 0.3465 - rmse: 0.4419 - smape: 0.7167 - val_ia: 0.4755 - val_loss: 0.2200 - val_mae: 0.3773 - val_rmse: 0.4238 - val_smape: 0.8433

Epoch 45/128

1146/1146 - 21s - 19ms/step - ia: 0.7734 - loss: 0.1975 - mae: 0.3454 - rmse: 0.4401 - smape: 0.7165 - val_ia: 0.4810 - val_loss: 0.2132 - val_mae: 0.3718 - val_rmse: 0.4179 - val_smape: 0.8381

Epoch 46/128

1146/1146 - 14s - 12ms/step - ia: 0.7753 - loss: 0.1939 - mae: 0.3422 - rmse: 0.4358 - smape: 0.7120 - val_ia: 0.4824 - val_loss: 0.2117 - val_mae: 0.3701 - val_rmse: 0.4156 - val_smape: 0.8322

Epoch 47/128

1146/1146 - 14s - 12ms/step - ia: 0.7766 - loss: 0.1925 - mae: 0.3404 - rmse: 0.4344 - smape: 0.7104 - val_ia: 0.4797 - val_loss: 0.2093 - val_mae: 0.3700 - val_rmse: 0.4149 - val_smape: 0.8419

Epoch 48/128

1146/1146 - 14s - 12ms/step - ia: 0.7791 - loss: 0.1894 - mae: 0.3369 - rmse: 0.4308 - smape: 0.7069 - val_ia: 0.4865 - val_loss: 0.2012 - val_mae: 0.3622 - val_rmse: 0.4062 - val_smape: 0.8250

Epoch 49/128

1146/1146 - 21s - 18ms/step - ia: 0.7789 - loss: 0.1892 - mae: 0.3377 - rmse: 0.4305 - smape: 0.7091 - val_ia: 0.4853 - val_loss: 0.2049 - val_mae: 0.3645 - val_rmse: 0.4084 - val_smape: 0.8277

Epoch 50/128

1146/1146 - 21s - 18ms/step - ia: 0.7813 - loss: 0.1854 - mae: 0.3337 - rmse: 0.4261 - smape: 0.7013 - val_ia: 0.4857 - val_loss: 0.1989 - val_mae: 0.3625 - val_rmse: 0.4049 - val_smape: 0.8241

Epoch 51/128

1146/1146 - 14s - 12ms/step - ia: 0.7818 - loss: 0.1844 - mae: 0.3331 - rmse: 0.4253 - smape: 0.7032 - val_ia: 0.4884 - val_loss: 0.1929 - val_mae: 0.3582 - val_rmse: 0.3997 - val_smape: 0.8170

Epoch 52/128

1146/1146 - 19s - 16ms/step - ia: 0.7850 - loss: 0.1802 - mae: 0.3291 - rmse: 0.4201 - smape: 0.6959 - val_ia: 0.4920 - val_loss: 0.1892 - val_mae: 0.3529 - val_rmse: 0.3945 - val_smape: 0.8096

Epoch 53/128

1146/1146 - 14s - 12ms/step - ia: 0.7854 - loss: 0.1789 - mae: 0.3278 - rmse: 0.4186 - smape: 0.6986 - val_ia: 0.4917 - val_loss: 0.1860 - val_mae: 0.3531 - val_rmse: 0.3933 - val_smape: 0.8092

Epoch 54/128

1146/1146 - 14s - 12ms/step - ia: 0.7857 - loss: 0.1783 - mae: 0.3275 - rmse: 0.4177 - smape: 0.6944 - val_ia: 0.4935 - val_loss: 0.1826 - val_mae: 0.3497 - val_rmse: 0.3896 - val_smape: 0.8044

Epoch 55/128

1146/1146 - 21s - 19ms/step - ia: 0.7878 - loss: 0.1747 - mae: 0.3240 - rmse: 0.4135 - smape: 0.6884 - val_ia: 0.4928 - val_loss: 0.1822 - val_mae: 0.3492 - val_rmse: 0.3892 - val_smape: 0.8050

Epoch 56/128

1146/1146 - 14s - 12ms/step - ia: 0.7885 - loss: 0.1733 - mae: 0.3227 - rmse: 0.4121 - smape: 0.6912 - val_ia: 0.4987 - val_loss: 0.1753 - val_mae: 0.3432 - val_rmse: 0.3825 - val_smape: 0.7946

Epoch 57/128

1146/1146 - 14s - 12ms/step - ia: 0.7908 - loss: 0.1716 - mae: 0.3207 - rmse: 0.4097 - smape: 0.6879 - val_ia: 0.4960 - val_loss: 0.1766 - val_mae: 0.3453 - val_rmse: 0.3843 - val_smape: 0.7917

Epoch 58/128

1146/1146 - 21s - 18ms/step - ia: 0.7904 - loss: 0.1708 - mae: 0.3206 - rmse: 0.4087 - smape: 0.6877 - val_ia: 0.4943 - val_loss: 0.1743 - val_mae: 0.3455 - val_rmse: 0.3845 - val_smape: 0.7982

Epoch 59/128

1146/1146 - 21s - 18ms/step - ia: 0.7915 - loss: 0.1698 - mae: 0.3187 - rmse: 0.4075 - smape: 0.6847 - val_ia: 0.4952 - val_loss: 0.1742 - val_mae: 0.3436 - val_rmse: 0.3830 - val_smape: 0.7965

Epoch 60/128

1146/1146 - 20s - 18ms/step - ia: 0.7926 - loss: 0.1677 - mae: 0.3171 - rmse: 0.4054 - smape: 0.6852 - val_ia: 0.4938 - val_loss: 0.1745 - val_mae: 0.3455 - val_rmse: 0.3849 - val_smape: 0.7996

Epoch 61/128

1146/1146 - 16s - 14ms/step - ia: 0.7946 - loss: 0.1656 - mae: 0.3145 - rmse: 0.4026 - smape: 0.6816 - val_ia: 0.4956 - val_loss: 0.1724 - val_mae: 0.3433 - val_rmse: 0.3823 - val_smape: 0.7903

Epoch 62/128

1146/1146 - 15s - 13ms/step - ia: 0.7956 - loss: 0.1639 - mae: 0.3126 - rmse: 0.4005 - smape: 0.6810 - val_ia: 0.5008 - val_loss: 0.1688 - val_mae: 0.3384 - val_rmse: 0.3766 - val_smape: 0.7705

Epoch 63/128

1146/1146 - 20s - 18ms/step - ia: 0.7957 - loss: 0.1635 - mae: 0.3124 - rmse: 0.4001 - smape: 0.6778 - val_ia: 0.4964 - val_loss: 0.1706 - val_mae: 0.3418 - val_rmse: 0.3813 - val_smape: 0.7852

Epoch 64/128

1146/1146 - 14s - 12ms/step - ia: 0.7969 - loss: 0.1622 - mae: 0.3113 - rmse: 0.3983 - smape: 0.6777 - val_ia: 0.5018 - val_loss: 0.1660 - val_mae: 0.3356 - val_rmse: 0.3739 - val_smape: 0.7656

Epoch 65/128

1146/1146 - 14s - 12ms/step - ia: 0.7980 - loss: 0.1597 - mae: 0.3090 - rmse: 0.3951 - smape: 0.6759 - val_ia: 0.5082 - val_loss: 0.1595 - val_mae: 0.3292 - val_rmse: 0.3665 - val_smape: 0.7496

Epoch 66/128

1146/1146 - 23s - 20ms/step - ia: 0.7985 - loss: 0.1597 - mae: 0.3086 - rmse: 0.3954 - smape: 0.6738 - val_ia: 0.5029 - val_loss: 0.1636 - val_mae: 0.3337 - val_rmse: 0.3724 - val_smape: 0.7596

Epoch 67/128

1146/1146 - 21s - 18ms/step - ia: 0.8008 - loss: 0.1563 - mae: 0.3053 - rmse: 0.3909 - smape: 0.6710 - val_ia: 0.5003 - val_loss: 0.1656 - val_mae: 0.3367 - val_rmse: 0.3749 - val_smape: 0.7620

Epoch 68/128

1146/1146 - 19s - 16ms/step - ia: 0.8018 - loss: 0.1549 - mae: 0.3033 - rmse: 0.3894 - smape: 0.6675 - val_ia: 0.5060 - val_loss: 0.1617 - val_mae: 0.3310 - val_rmse: 0.3690 - val_smape: 0.7484

Epoch 69/128

1146/1146 - 19s - 17ms/step - ia: 0.8024 - loss: 0.1547 - mae: 0.3037 - rmse: 0.3891 - smape: 0.6689 - val_ia: 0.5054 - val_loss: 0.1631 - val_mae: 0.3316 - val_rmse: 0.3708 - val_smape: 0.7485

Epoch 70/128

1146/1146 - 16s - 14ms/step - ia: 0.8032 - loss: 0.1536 - mae: 0.3020 - rmse: 0.3876 - smape: 0.6669 - val_ia: 0.5056 - val_loss: 0.1623 - val_mae: 0.3311 - val_rmse: 0.3707 - val_smape: 0.7455

Epoch 71/128

1146/1146 - 14s - 12ms/step - ia: 0.8052 - loss: 0.1509 - mae: 0.2991 - rmse: 0.3840 - smape: 0.6632 - val_ia: 0.5061 - val_loss: 0.1625 - val_mae: 0.3310 - val_rmse: 0.3704 - val_smape: 0.7435

Epoch 72/128

1146/1146 - 14s - 12ms/step - ia: 0.8051 - loss: 0.1504 - mae: 0.2985 - rmse: 0.3837 - smape: 0.6603 - val_ia: 0.5087 - val_loss: 0.1615 - val_mae: 0.3288 - val_rmse: 0.3675 - val_smape: 0.7345

Epoch 73/128

1146/1146 - 21s - 19ms/step - ia: 0.8061 - loss: 0.1488 - mae: 0.2970 - rmse: 0.3813 - smape: 0.6606 - val_ia: 0.5074 - val_loss: 0.1610 - val_mae: 0.3291 - val_rmse: 0.3675 - val_smape: 0.7310

Epoch 74/128

1146/1146 - 20s - 18ms/step - ia: 0.8063 - loss: 0.1478 - mae: 0.2965 - rmse: 0.3802 - smape: 0.6573 - val_ia: 0.5081 - val_loss: 0.1629 - val_mae: 0.3300 - val_rmse: 0.3695 - val_smape: 0.7316

Epoch 75/128

1146/1146 - 14s - 12ms/step - ia: 0.8077 - loss: 0.1471 - mae: 0.2949 - rmse: 0.3791 - smape: 0.6587 - val_ia: 0.5145 - val_loss: 0.1566 - val_mae: 0.3239 - val_rmse: 0.3611 - val_smape: 0.7148

Epoch 76/128

1146/1146 - 14s - 12ms/step - ia: 0.8087 - loss: 0.1469 - mae: 0.2944 - rmse: 0.3788 - smape: 0.6549 - val_ia: 0.5110 - val_loss: 0.1590 - val_mae: 0.3261 - val_rmse: 0.3640 - val_smape: 0.7229

Epoch 77/128

1146/1146 - 14s - 12ms/step - ia: 0.8092 - loss: 0.1452 - mae: 0.2927 - rmse: 0.3770 - smape: 0.6544 - val_ia: 0.5048 - val_loss: 0.1649 - val_mae: 0.3335 - val_rmse: 0.3726 - val_smape: 0.7353

Epoch 78/128

1146/1146 - 17s - 15ms/step - ia: 0.8109 - loss: 0.1430 - mae: 0.2905 - rmse: 0.3738 - smape: 0.6530 - val_ia: 0.5106 - val_loss: 0.1600 - val_mae: 0.3275 - val_rmse: 0.3657 - val_smape: 0.7232

Epoch 79/128

1146/1146 - 14s - 12ms/step - ia: 0.8106 - loss: 0.1429 - mae: 0.2904 - rmse: 0.3732 - smape: 0.6510 - val_ia: 0.5072 - val_loss: 0.1656 - val_mae: 0.3336 - val_rmse: 0.3724 - val_smape: 0.7309

Epoch 80/128

1146/1146 - 14s - 13ms/step - ia: 0.8113 - loss: 0.1420 - mae: 0.2896 - rmse: 0.3726 - smape: 0.6509 - val_ia: 0.5128 - val_loss: 0.1581 - val_mae: 0.3255 - val_rmse: 0.3627 - val_smape: 0.7169

Epoch 81/128

1146/1146 - 14s - 13ms/step - ia: 0.8124 - loss: 0.1408 - mae: 0.2880 - rmse: 0.3709 - smape: 0.6493 - val_ia: 0.5114 - val_loss: 0.1628 - val_mae: 0.3297 - val_rmse: 0.3679 - val_smape: 0.7207

Epoch 82/128

1146/1146 - 12s - 10ms/step - ia: 0.8145 - loss: 0.1388 - mae: 0.2846 - rmse: 0.3680 - smape: 0.6420 - val_ia: 0.5098 - val_loss: 0.1657 - val_mae: 0.3323 - val_rmse: 0.3705 - val_smape: 0.7228

Epoch 83/128

1146/1146 - 14s - 12ms/step - ia: 0.8141 - loss: 0.1389 - mae: 0.2851 - rmse: 0.3682 - smape: 0.6440 - val_ia: 0.5135 - val_loss: 0.1624 - val_mae: 0.3290 - val_rmse: 0.3669 - val_smape: 0.7170

Epoch 84/128

1146/1146 - 14s - 13ms/step - ia: 0.8151 - loss: 0.1372 - mae: 0.2835 - rmse: 0.3660 - smape: 0.6418 - val_ia: 0.5152 - val_loss: 0.1600 - val_mae: 0.3262 - val_rmse: 0.3639 - val_smape: 0.7158

Epoch 85/128

1146/1146 - 14s - 12ms/step - ia: 0.8164 - loss: 0.1358 - mae: 0.2820 - rmse: 0.3638 - smape: 0.6402 - val_ia: 0.5155 - val_loss: 0.1613 - val_mae: 0.3276 - val_rmse: 0.3651 - val_smape: 0.7165

Epoch 86/128

1146/1146 - 15s - 13ms/step - ia: 0.8163 - loss: 0.1370 - mae: 0.2831 - rmse: 0.3655 - smape: 0.6420 - val_ia: 0.5107 - val_loss: 0.1649 - val_mae: 0.3322 - val_rmse: 0.3710 - val_smape: 0.7256

Epoch 87/128

1146/1146 - 15s - 13ms/step - ia: 0.8179 - loss: 0.1335 - mae: 0.2798 - rmse: 0.3608 - smape: 0.6370 - val_ia: 0.5132 - val_loss: 0.1629 - val_mae: 0.3295 - val_rmse: 0.3672 - val_smape: 0.7189

Epoch 88/128

1146/1146 - 15s - 13ms/step - ia: 0.8177 - loss: 0.1343 - mae: 0.2800 - rmse: 0.3619 - smape: 0.6395 - val_ia: 0.5140 - val_loss: 0.1622 - val_mae: 0.3291 - val_rmse: 0.3669 - val_smape: 0.7190

Epoch 89/128

1146/1146 - 20s - 17ms/step - ia: 0.8184 - loss: 0.1341 - mae: 0.2794 - rmse: 0.3616 - smape: 0.6380 - val_ia: 0.5186 - val_loss: 0.1581 - val_mae: 0.3246 - val_rmse: 0.3610 - val_smape: 0.7079

Epoch 90/128

1146/1146 - 16s - 14ms/step - ia: 0.8199 - loss: 0.1315 - mae: 0.2772 - rmse: 0.3584 - smape: 0.6313 - val_ia: 0.5150 - val_loss: 0.1608 - val_mae: 0.3279 - val_rmse: 0.3658 - val_smape: 0.7193

Epoch 90: early stopping

Restoring model weights from the end of the best epoch: 75.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 3:03 1s/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 33/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 45/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
138/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
159/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step

 33%|███▎      | 4/12 [1:03:38<2:29:09, 1118.72s/trial, best loss: 0.1851744141239589]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

573/573 - 12s - 21ms/step - ia: 0.1446 - loss: 1.0746 - mae: 0.8531 - rmse: 1.0339 - smape: 1.6593 - val_ia: 0.2909 - val_loss: 0.8898 - val_mae: 0.7771 - val_rmse: 0.9136 - val_smape: 1.6169

Epoch 2/128

573/573 - 9s - 17ms/step - ia: 0.1474 - loss: 1.0441 - mae: 0.8415 - rmse: 1.0191 - smape: 1.6643 - val_ia: 0.2949 - val_loss: 0.8656 - val_mae: 0.7667 - val_rmse: 0.9011 - val_smape: 1.6187

Epoch 3/128

573/573 - 5s - 8ms/step - ia: 0.1504 - loss: 1.0171 - mae: 0.8319 - rmse: 1.0061 - smape: 1.6687 - val_ia: 0.2987 - val_loss: 0.8428 - val_mae: 0.7567 - val_rmse: 0.8890 - val_smape: 1.6155

Epoch 4/128

573/573 - 5s - 8ms/step - ia: 0.1570 - loss: 0.9898 - mae: 0.8219 - rmse: 0.9923 - smape: 1.6634 - val_ia: 0.3022 - val_loss: 0.8210 - val_mae: 0.7469 - val_rmse: 0.8774 - val_smape: 1.6074

Epoch 5/128

573/573 - 5s - 9ms/step - ia: 0.1645 - loss: 0.9649 - mae: 0.8132 - rmse: 0.9798 - smape: 1.6549 - val_ia: 0.3058 - val_loss: 0.8003 - val_mae: 0.7374 - val_rmse: 0.8661 - val_smape: 1.5927

Epoch 6/128

573/573 - 5s - 9ms/step - ia: 0.1762 - loss: 0.9408 - mae: 0.8042 - rmse: 0.9677 - smape: 1.6390 - val_ia: 0.3094 - val_loss: 0.7803 - val_mae: 0.7280 - val_rmse: 0.8551 - val_smape: 1.5710

Epoch 7/128

573/573 - 5s - 9ms/step - ia: 0.1897 - loss: 0.9188 - mae: 0.7962 - rmse: 0.9565 - smape: 1.6183 - val_ia: 0.3128 - val_loss: 0.7613 - val_mae: 0.7189 - val_rmse: 0.8444 - val_smape: 1.5428

Epoch 8/128

573/573 - 5s - 8ms/step - ia: 0.2034 - loss: 0.8962 - mae: 0.7869 - rmse: 0.9445 - smape: 1.5922 - val_ia: 0.3164 - val_loss: 0.7433 - val_mae: 0.7101 - val_rmse: 0.8341 - val_smape: 1.5128

Epoch 9/128

573/573 - 5s - 8ms/step - ia: 0.2211 - loss: 0.8734 - mae: 0.7781 - rmse: 0.9324 - smape: 1.5657 - val_ia: 0.3202 - val_loss: 0.7262 - val_mae: 0.7015 - val_rmse: 0.8242 - val_smape: 1.4808

Epoch 10/128

573/573 - 5s - 9ms/step - ia: 0.2368 - loss: 0.8549 - mae: 0.7711 - rmse: 0.9224 - smape: 1.5397 - val_ia: 0.3242 - val_loss: 0.7102 - val_mae: 0.6934 - val_rmse: 0.8147 - val_smape: 1.4507

Epoch 11/128

573/573 - 5s - 9ms/step - ia: 0.2539 - loss: 0.8341 - mae: 0.7621 - rmse: 0.9113 - smape: 1.5065 - val_ia: 0.3281 - val_loss: 0.6950 - val_mae: 0.6855 - val_rmse: 0.8056 - val_smape: 1.4217

Epoch 12/128

573/573 - 4s - 8ms/step - ia: 0.2702 - loss: 0.8176 - mae: 0.7556 - rmse: 0.9020 - smape: 1.4818 - val_ia: 0.3320 - val_loss: 0.6807 - val_mae: 0.6779 - val_rmse: 0.7969 - val_smape: 1.3937

Epoch 13/128

573/573 - 4s - 8ms/step - ia: 0.2857 - loss: 0.8009 - mae: 0.7482 - rmse: 0.8928 - smape: 1.4568 - val_ia: 0.3356 - val_loss: 0.6675 - val_mae: 0.6708 - val_rmse: 0.7886 - val_smape: 1.3678

Epoch 14/128

573/573 - 4s - 8ms/step - ia: 0.3027 - loss: 0.7835 - mae: 0.7411 - rmse: 0.8831 - smape: 1.4319 - val_ia: 0.3393 - val_loss: 0.6549 - val_mae: 0.6640 - val_rmse: 0.7807 - val_smape: 1.3444

Epoch 15/128

573/573 - 4s - 8ms/step - ia: 0.3191 - loss: 0.7651 - mae: 0.7323 - rmse: 0.8729 - smape: 1.4059 - val_ia: 0.3433 - val_loss: 0.6431 - val_mae: 0.6576 - val_rmse: 0.7731 - val_smape: 1.3218

Epoch 16/128

573/573 - 4s - 8ms/step - ia: 0.3341 - loss: 0.7496 - mae: 0.7258 - rmse: 0.8639 - smape: 1.3883 - val_ia: 0.3476 - val_loss: 0.6322 - val_mae: 0.6516 - val_rmse: 0.7660 - val_smape: 1.3015

Epoch 17/128

573/573 - 5s - 9ms/step - ia: 0.3466 - loss: 0.7373 - mae: 0.7196 - rmse: 0.8567 - smape: 1.3681 - val_ia: 0.3520 - val_loss: 0.6220 - val_mae: 0.6461 - val_rmse: 0.7592 - val_smape: 1.2826

Epoch 18/128

573/573 - 4s - 8ms/step - ia: 0.3620 - loss: 0.7199 - mae: 0.7111 - rmse: 0.8465 - smape: 1.3451 - val_ia: 0.3565 - val_loss: 0.6127 - val_mae: 0.6409 - val_rmse: 0.7529 - val_smape: 1.2646

Epoch 19/128

573/573 - 5s - 9ms/step - ia: 0.3761 - loss: 0.7049 - mae: 0.7036 - rmse: 0.8375 - smape: 1.3246 - val_ia: 0.3611 - val_loss: 0.6039 - val_mae: 0.6361 - val_rmse: 0.7469 - val_smape: 1.2468

Epoch 20/128

573/573 - 5s - 8ms/step - ia: 0.3889 - loss: 0.6909 - mae: 0.6966 - rmse: 0.8292 - smape: 1.3053 - val_ia: 0.3657 - val_loss: 0.5960 - val_mae: 0.6317 - val_rmse: 0.7414 - val_smape: 1.2306

Epoch 21/128

573/573 - 6s - 10ms/step - ia: 0.4037 - loss: 0.6750 - mae: 0.6882 - rmse: 0.8196 - smape: 1.2872 - val_ia: 0.3703 - val_loss: 0.5888 - val_mae: 0.6277 - val_rmse: 0.7362 - val_smape: 1.2157

Epoch 22/128

573/573 - 10s - 18ms/step - ia: 0.4152 - loss: 0.6630 - mae: 0.6810 - rmse: 0.8125 - smape: 1.2674 - val_ia: 0.3751 - val_loss: 0.5824 - val_mae: 0.6240 - val_rmse: 0.7316 - val_smape: 1.2020

Epoch 23/128

573/573 - 5s - 9ms/step - ia: 0.4271 - loss: 0.6499 - mae: 0.6739 - rmse: 0.8043 - smape: 1.2514 - val_ia: 0.3799 - val_loss: 0.5766 - val_mae: 0.6207 - val_rmse: 0.7274 - val_smape: 1.1900

Epoch 24/128

573/573 - 5s - 8ms/step - ia: 0.4385 - loss: 0.6366 - mae: 0.6674 - rmse: 0.7959 - smape: 1.2376 - val_ia: 0.3845 - val_loss: 0.5717 - val_mae: 0.6178 - val_rmse: 0.7238 - val_smape: 1.1787

Epoch 25/128

573/573 - 5s - 9ms/step - ia: 0.4504 - loss: 0.6251 - mae: 0.6599 - rmse: 0.7886 - smape: 1.2194 - val_ia: 0.3889 - val_loss: 0.5676 - val_mae: 0.6156 - val_rmse: 0.7207 - val_smape: 1.1687

Epoch 26/128

573/573 - 4s - 7ms/step - ia: 0.4624 - loss: 0.6114 - mae: 0.6527 - rmse: 0.7798 - smape: 1.2022 - val_ia: 0.3932 - val_loss: 0.5644 - val_mae: 0.6139 - val_rmse: 0.7182 - val_smape: 1.1591

Epoch 27/128

573/573 - 4s - 8ms/step - ia: 0.4731 - loss: 0.6016 - mae: 0.6465 - rmse: 0.7738 - smape: 1.1872 - val_ia: 0.3973 - val_loss: 0.5621 - val_mae: 0.6127 - val_rmse: 0.7163 - val_smape: 1.1508

Epoch 28/128

573/573 - 4s - 8ms/step - ia: 0.4850 - loss: 0.5867 - mae: 0.6374 - rmse: 0.7638 - smape: 1.1701 - val_ia: 0.4012 - val_loss: 0.5605 - val_mae: 0.6120 - val_rmse: 0.7149 - val_smape: 1.1437

Epoch 29/128

573/573 - 5s - 9ms/step - ia: 0.4951 - loss: 0.5778 - mae: 0.6323 - rmse: 0.7582 - smape: 1.1558 - val_ia: 0.4048 - val_loss: 0.5598 - val_mae: 0.6118 - val_rmse: 0.7141 - val_smape: 1.1384

Epoch 30/128

573/573 - 4s - 8ms/step - ia: 0.5062 - loss: 0.5650 - mae: 0.6236 - rmse: 0.7496 - smape: 1.1379 - val_ia: 0.4083 - val_loss: 0.5598 - val_mae: 0.6122 - val_rmse: 0.7139 - val_smape: 1.1338

Epoch 31/128

573/573 - 5s - 8ms/step - ia: 0.5154 - loss: 0.5551 - mae: 0.6179 - rmse: 0.7431 - smape: 1.1236 - val_ia: 0.4116 - val_loss: 0.5599 - val_mae: 0.6126 - val_rmse: 0.7138 - val_smape: 1.1295

Epoch 32/128

573/573 - 4s - 8ms/step - ia: 0.5230 - loss: 0.5497 - mae: 0.6134 - rmse: 0.7393 - smape: 1.1132 - val_ia: 0.4144 - val_loss: 0.5617 - val_mae: 0.6141 - val_rmse: 0.7147 - val_smape: 1.1274

Epoch 33/128

573/573 - 5s - 9ms/step - ia: 0.5331 - loss: 0.5383 - mae: 0.6062 - rmse: 0.7318 - smape: 1.0953 - val_ia: 0.4170 - val_loss: 0.5633 - val_mae: 0.6154 - val_rmse: 0.7157 - val_smape: 1.1260

Epoch 34/128

573/573 - 4s - 8ms/step - ia: 0.5411 - loss: 0.5307 - mae: 0.6013 - rmse: 0.7263 - smape: 1.0864 - val_ia: 0.4194 - val_loss: 0.5654 - val_mae: 0.6169 - val_rmse: 0.7169 - val_smape: 1.1244

Epoch 35/128

573/573 - 4s - 8ms/step - ia: 0.5499 - loss: 0.5215 - mae: 0.5948 - rmse: 0.7201 - smape: 1.0712 - val_ia: 0.4216 - val_loss: 0.5674 - val_mae: 0.6185 - val_rmse: 0.7182 - val_smape: 1.1235

Epoch 36/128

573/573 - 4s - 8ms/step - ia: 0.5564 - loss: 0.5151 - mae: 0.5903 - rmse: 0.7158 - smape: 1.0607 - val_ia: 0.4235 - val_loss: 0.5703 - val_mae: 0.6204 - val_rmse: 0.7200 - val_smape: 1.1230

Epoch 37/128

573/573 - 4s - 8ms/step - ia: 0.5627 - loss: 0.5091 - mae: 0.5864 - rmse: 0.7114 - smape: 1.0513 - val_ia: 0.4253 - val_loss: 0.5727 - val_mae: 0.6221 - val_rmse: 0.7215 - val_smape: 1.1225

Epoch 38/128

573/573 - 4s - 8ms/step - ia: 0.5692 - loss: 0.5024 - mae: 0.5814 - rmse: 0.7068 - smape: 1.0382 - val_ia: 0.4270 - val_loss: 0.5749 - val_mae: 0.6237 - val_rmse: 0.7230 - val_smape: 1.1224

Epoch 39/128

573/573 - 5s - 9ms/step - ia: 0.5774 - loss: 0.4942 - mae: 0.5754 - rmse: 0.7008 - smape: 1.0294 - val_ia: 0.4283 - val_loss: 0.5782 - val_mae: 0.6258 - val_rmse: 0.7251 - val_smape: 1.1229

Epoch 40/128

573/573 - 4s - 7ms/step - ia: 0.5828 - loss: 0.4893 - mae: 0.5716 - rmse: 0.6971 - smape: 1.0192 - val_ia: 0.4294 - val_loss: 0.5811 - val_mae: 0.6278 - val_rmse: 0.7270 - val_smape: 1.1240

Epoch 41/128

573/573 - 5s - 8ms/step - ia: 0.5881 - loss: 0.4824 - mae: 0.5667 - rmse: 0.6926 - smape: 1.0102 - val_ia: 0.4303 - val_loss: 0.5840 - val_mae: 0.6299 - val_rmse: 0.7289 - val_smape: 1.1250

Epoch 42/128

573/573 - 4s - 7ms/step - ia: 0.5917 - loss: 0.4783 - mae: 0.5639 - rmse: 0.6895 - smape: 1.0026 - val_ia: 0.4311 - val_loss: 0.5867 - val_mae: 0.6318 - val_rmse: 0.7306 - val_smape: 1.1266

Epoch 43/128

573/573 - 4s - 8ms/step - ia: 0.5975 - loss: 0.4737 - mae: 0.5604 - rmse: 0.6859 - smape: 0.9935 - val_ia: 0.4318 - val_loss: 0.5889 - val_mae: 0.6336 - val_rmse: 0.7321 - val_smape: 1.1282

Epoch 44/128

573/573 - 5s - 9ms/step - ia: 0.6036 - loss: 0.4650 - mae: 0.5545 - rmse: 0.6797 - smape: 0.9833 - val_ia: 0.4322 - val_loss: 0.5917 - val_mae: 0.6356 - val_rmse: 0.7339 - val_smape: 1.1305

Epoch 44: early stopping

Restoring model weights from the end of the best epoch: 29.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:12 448ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 34/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 70/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 89/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 42%|████▏     | 5/12 [1:07:24<1:32:58, 796.91s/trial, best loss: 0.1851744141239589]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 13s - 45ms/step - ia: 0.3029 - loss: 1.5216 - mae: 1.0168 - rmse: 1.2314 - smape: 1.4135 - val_ia: 0.3017 - val_loss: 1.3075 - val_mae: 0.9565 - val_rmse: 1.1207 - val_smape: 1.4413

Epoch 2/128

287/287 - 5s - 17ms/step - ia: 0.2769 - loss: 1.3332 - mae: 0.9516 - rmse: 1.1529 - smape: 1.4527 - val_ia: 0.2670 - val_loss: 1.1163 - val_mae: 0.8786 - val_rmse: 1.0385 - val_smape: 1.4686

Epoch 3/128

287/287 - 4s - 16ms/step - ia: 0.2501 - loss: 1.2335 - mae: 0.9170 - rmse: 1.1090 - smape: 1.4955 - val_ia: 0.2377 - val_loss: 0.9990 - val_mae: 0.8307 - val_rmse: 0.9856 - val_smape: 1.5291

Epoch 4/128

287/287 - 5s - 19ms/step - ia: 0.2369 - loss: 1.1671 - mae: 0.8933 - rmse: 1.0787 - smape: 1.5122 - val_ia: 0.2164 - val_loss: 0.9307 - val_mae: 0.8028 - val_rmse: 0.9539 - val_smape: 1.6150

Epoch 5/128

287/287 - 5s - 17ms/step - ia: 0.2258 - loss: 1.1480 - mae: 0.8847 - rmse: 1.0701 - smape: 1.5316 - val_ia: 0.2128 - val_loss: 0.8928 - val_mae: 0.7869 - val_rmse: 0.9359 - val_smape: 1.7119

Epoch 6/128

287/287 - 5s - 18ms/step - ia: 0.2256 - loss: 1.1313 - mae: 0.8792 - rmse: 1.0622 - smape: 1.5331 - val_ia: 0.2119 - val_loss: 0.8745 - val_mae: 0.7788 - val_rmse: 0.9271 - val_smape: 1.7885

Epoch 7/128

287/287 - 5s - 19ms/step - ia: 0.2232 - loss: 1.1234 - mae: 0.8768 - rmse: 1.0584 - smape: 1.5394 - val_ia: 0.2126 - val_loss: 0.8632 - val_mae: 0.7736 - val_rmse: 0.9216 - val_smape: 1.8585

Epoch 8/128

287/287 - 5s - 18ms/step - ia: 0.2219 - loss: 1.1147 - mae: 0.8732 - rmse: 1.0543 - smape: 1.5366 - val_ia: 0.2140 - val_loss: 0.8578 - val_mae: 0.7711 - val_rmse: 0.9190 - val_smape: 1.8958

Epoch 9/128

287/287 - 5s - 17ms/step - ia: 0.2215 - loss: 1.1156 - mae: 0.8730 - rmse: 1.0545 - smape: 1.5389 - val_ia: 0.2153 - val_loss: 0.8538 - val_mae: 0.7693 - val_rmse: 0.9170 - val_smape: 1.9046

Epoch 10/128

287/287 - 5s - 16ms/step - ia: 0.2216 - loss: 1.1039 - mae: 0.8700 - rmse: 1.0489 - smape: 1.5433 - val_ia: 0.2160 - val_loss: 0.8517 - val_mae: 0.7683 - val_rmse: 0.9159 - val_smape: 1.8956

Epoch 11/128

287/287 - 5s - 16ms/step - ia: 0.2203 - loss: 1.0987 - mae: 0.8677 - rmse: 1.0472 - smape: 1.5432 - val_ia: 0.2166 - val_loss: 0.8501 - val_mae: 0.7675 - val_rmse: 0.9151 - val_smape: 1.8855

Epoch 12/128

287/287 - 5s - 17ms/step - ia: 0.2168 - loss: 1.1056 - mae: 0.8709 - rmse: 1.0503 - smape: 1.5509 - val_ia: 0.2172 - val_loss: 0.8485 - val_mae: 0.7668 - val_rmse: 0.9143 - val_smape: 1.8752

Epoch 13/128

287/287 - 5s - 16ms/step - ia: 0.2165 - loss: 1.0935 - mae: 0.8669 - rmse: 1.0443 - smape: 1.5511 - val_ia: 0.2177 - val_loss: 0.8474 - val_mae: 0.7663 - val_rmse: 0.9136 - val_smape: 1.8652

Epoch 14/128

287/287 - 5s - 18ms/step - ia: 0.2191 - loss: 1.0880 - mae: 0.8629 - rmse: 1.0421 - smape: 1.5450 - val_ia: 0.2181 - val_loss: 0.8467 - val_mae: 0.7660 - val_rmse: 0.9132 - val_smape: 1.8552

Epoch 15/128

287/287 - 5s - 16ms/step - ia: 0.2170 - loss: 1.0828 - mae: 0.8616 - rmse: 1.0392 - smape: 1.5467 - val_ia: 0.2195 - val_loss: 0.8435 - val_mae: 0.7645 - val_rmse: 0.9116 - val_smape: 1.8457

Epoch 16/128

287/287 - 5s - 19ms/step - ia: 0.2180 - loss: 1.0702 - mae: 0.8581 - rmse: 1.0334 - smape: 1.5509 - val_ia: 0.2205 - val_loss: 0.8413 - val_mae: 0.7635 - val_rmse: 0.9105 - val_smape: 1.8354

Epoch 17/128

287/287 - 9s - 33ms/step - ia: 0.2177 - loss: 1.0719 - mae: 0.8566 - rmse: 1.0340 - smape: 1.5468 - val_ia: 0.2212 - val_loss: 0.8401 - val_mae: 0.7629 - val_rmse: 0.9098 - val_smape: 1.8259

Epoch 18/128

287/287 - 5s - 17ms/step - ia: 0.2176 - loss: 1.0644 - mae: 0.8543 - rmse: 1.0303 - smape: 1.5464 - val_ia: 0.2223 - val_loss: 0.8378 - val_mae: 0.7618 - val_rmse: 0.9086 - val_smape: 1.8157

Epoch 19/128

287/287 - 5s - 17ms/step - ia: 0.2155 - loss: 1.0619 - mae: 0.8542 - rmse: 1.0293 - smape: 1.5520 - val_ia: 0.2224 - val_loss: 0.8378 - val_mae: 0.7619 - val_rmse: 0.9086 - val_smape: 1.8068

Epoch 20/128

287/287 - 5s - 18ms/step - ia: 0.2152 - loss: 1.0558 - mae: 0.8523 - rmse: 1.0264 - smape: 1.5524 - val_ia: 0.2233 - val_loss: 0.8362 - val_mae: 0.7612 - val_rmse: 0.9078 - val_smape: 1.7970

Epoch 21/128

287/287 - 5s - 18ms/step - ia: 0.2164 - loss: 1.0471 - mae: 0.8485 - rmse: 1.0216 - smape: 1.5509 - val_ia: 0.2246 - val_loss: 0.8335 - val_mae: 0.7599 - val_rmse: 0.9064 - val_smape: 1.7868

Epoch 22/128

287/287 - 5s - 17ms/step - ia: 0.2133 - loss: 1.0531 - mae: 0.8516 - rmse: 1.0249 - smape: 1.5549 - val_ia: 0.2253 - val_loss: 0.8326 - val_mae: 0.7595 - val_rmse: 0.9058 - val_smape: 1.7774

Epoch 23/128

287/287 - 5s - 17ms/step - ia: 0.2146 - loss: 1.0401 - mae: 0.8476 - rmse: 1.0188 - smape: 1.5557 - val_ia: 0.2260 - val_loss: 0.8317 - val_mae: 0.7590 - val_rmse: 0.9053 - val_smape: 1.7679

Epoch 24/128

287/287 - 5s - 17ms/step - ia: 0.2143 - loss: 1.0369 - mae: 0.8457 - rmse: 1.0169 - smape: 1.5551 - val_ia: 0.2272 - val_loss: 0.8293 - val_mae: 0.7579 - val_rmse: 0.9041 - val_smape: 1.7580

Epoch 25/128

287/287 - 5s - 17ms/step - ia: 0.2175 - loss: 1.0276 - mae: 0.8421 - rmse: 1.0127 - smape: 1.5498 - val_ia: 0.2282 - val_loss: 0.8279 - val_mae: 0.7572 - val_rmse: 0.9033 - val_smape: 1.7484

Epoch 26/128

287/287 - 5s - 18ms/step - ia: 0.2183 - loss: 1.0263 - mae: 0.8409 - rmse: 1.0119 - smape: 1.5483 - val_ia: 0.2293 - val_loss: 0.8260 - val_mae: 0.7563 - val_rmse: 0.9023 - val_smape: 1.7386

Epoch 27/128

287/287 - 5s - 19ms/step - ia: 0.2156 - loss: 1.0234 - mae: 0.8403 - rmse: 1.0103 - smape: 1.5540 - val_ia: 0.2301 - val_loss: 0.8253 - val_mae: 0.7560 - val_rmse: 0.9019 - val_smape: 1.7289

Epoch 28/128

287/287 - 5s - 18ms/step - ia: 0.2169 - loss: 1.0199 - mae: 0.8394 - rmse: 1.0087 - smape: 1.5499 - val_ia: 0.2313 - val_loss: 0.8236 - val_mae: 0.7552 - val_rmse: 0.9010 - val_smape: 1.7193

Epoch 29/128

287/287 - 5s - 16ms/step - ia: 0.2150 - loss: 1.0158 - mae: 0.8378 - rmse: 1.0070 - smape: 1.5554 - val_ia: 0.2323 - val_loss: 0.8223 - val_mae: 0.7546 - val_rmse: 0.9003 - val_smape: 1.7096

Epoch 30/128

287/287 - 5s - 17ms/step - ia: 0.2176 - loss: 1.0090 - mae: 0.8353 - rmse: 1.0036 - smape: 1.5516 - val_ia: 0.2331 - val_loss: 0.8219 - val_mae: 0.7545 - val_rmse: 0.9000 - val_smape: 1.6997

Epoch 31/128

287/287 - 5s - 18ms/step - ia: 0.2191 - loss: 1.0084 - mae: 0.8345 - rmse: 1.0029 - smape: 1.5460 - val_ia: 0.2343 - val_loss: 0.8201 - val_mae: 0.7536 - val_rmse: 0.8991 - val_smape: 1.6897

Epoch 32/128

287/287 - 5s - 17ms/step - ia: 0.2212 - loss: 0.9990 - mae: 0.8315 - rmse: 0.9982 - smape: 1.5465 - val_ia: 0.2355 - val_loss: 0.8189 - val_mae: 0.7530 - val_rmse: 0.8984 - val_smape: 1.6796

Epoch 33/128

287/287 - 5s - 16ms/step - ia: 0.2219 - loss: 0.9961 - mae: 0.8306 - rmse: 0.9967 - smape: 1.5459 - val_ia: 0.2369 - val_loss: 0.8166 - val_mae: 0.7519 - val_rmse: 0.8972 - val_smape: 1.6697

Epoch 34/128

287/287 - 5s - 16ms/step - ia: 0.2219 - loss: 0.9965 - mae: 0.8316 - rmse: 0.9970 - smape: 1.5484 - val_ia: 0.2384 - val_loss: 0.8145 - val_mae: 0.7509 - val_rmse: 0.8961 - val_smape: 1.6598

Epoch 35/128

287/287 - 5s - 17ms/step - ia: 0.2250 - loss: 0.9912 - mae: 0.8281 - rmse: 0.9944 - smape: 1.5422 - val_ia: 0.2396 - val_loss: 0.8138 - val_mae: 0.7505 - val_rmse: 0.8956 - val_smape: 1.6499

Epoch 36/128

287/287 - 5s - 17ms/step - ia: 0.2274 - loss: 0.9852 - mae: 0.8268 - rmse: 0.9916 - smape: 1.5398 - val_ia: 0.2413 - val_loss: 0.8109 - val_mae: 0.7491 - val_rmse: 0.8941 - val_smape: 1.6401

Epoch 37/128

287/287 - 5s - 16ms/step - ia: 0.2251 - loss: 0.9836 - mae: 0.8270 - rmse: 0.9906 - smape: 1.5437 - val_ia: 0.2427 - val_loss: 0.8101 - val_mae: 0.7487 - val_rmse: 0.8936 - val_smape: 1.6299

Epoch 38/128

287/287 - 5s - 18ms/step - ia: 0.2266 - loss: 0.9775 - mae: 0.8243 - rmse: 0.9872 - smape: 1.5406 - val_ia: 0.2441 - val_loss: 0.8093 - val_mae: 0.7483 - val_rmse: 0.8932 - val_smape: 1.6199

Epoch 39/128

287/287 - 5s - 18ms/step - ia: 0.2318 - loss: 0.9722 - mae: 0.8219 - rmse: 0.9849 - smape: 1.5311 - val_ia: 0.2459 - val_loss: 0.8066 - val_mae: 0.7469 - val_rmse: 0.8917 - val_smape: 1.6098

Epoch 40/128

287/287 - 5s - 17ms/step - ia: 0.2334 - loss: 0.9690 - mae: 0.8208 - rmse: 0.9834 - smape: 1.5341 - val_ia: 0.2475 - val_loss: 0.8054 - val_mae: 0.7463 - val_rmse: 0.8910 - val_smape: 1.5998

Epoch 41/128

287/287 - 5s - 16ms/step - ia: 0.2346 - loss: 0.9668 - mae: 0.8211 - rmse: 0.9821 - smape: 1.5301 - val_ia: 0.2492 - val_loss: 0.8044 - val_mae: 0.7457 - val_rmse: 0.8904 - val_smape: 1.5900

Epoch 42/128

287/287 - 4s - 15ms/step - ia: 0.2372 - loss: 0.9613 - mae: 0.8186 - rmse: 0.9793 - smape: 1.5265 - val_ia: 0.2509 - val_loss: 0.8029 - val_mae: 0.7449 - val_rmse: 0.8896 - val_smape: 1.5800

Epoch 43/128

287/287 - 5s - 16ms/step - ia: 0.2387 - loss: 0.9610 - mae: 0.8174 - rmse: 0.9792 - smape: 1.5244 - val_ia: 0.2527 - val_loss: 0.8026 - val_mae: 0.7447 - val_rmse: 0.8894 - val_smape: 1.5699

Epoch 44/128

287/287 - 5s - 16ms/step - ia: 0.2428 - loss: 0.9520 - mae: 0.8144 - rmse: 0.9743 - smape: 1.5166 - val_ia: 0.2548 - val_loss: 0.7993 - val_mae: 0.7430 - val_rmse: 0.8876 - val_smape: 1.5600

Epoch 45/128

287/287 - 5s - 16ms/step - ia: 0.2455 - loss: 0.9500 - mae: 0.8129 - rmse: 0.9733 - smape: 1.5150 - val_ia: 0.2568 - val_loss: 0.7988 - val_mae: 0.7426 - val_rmse: 0.8873 - val_smape: 1.5496

Epoch 46/128

287/287 - 5s - 16ms/step - ia: 0.2458 - loss: 0.9465 - mae: 0.8134 - rmse: 0.9716 - smape: 1.5171 - val_ia: 0.2590 - val_loss: 0.7973 - val_mae: 0.7418 - val_rmse: 0.8865 - val_smape: 1.5396

Epoch 47/128

287/287 - 5s - 16ms/step - ia: 0.2526 - loss: 0.9401 - mae: 0.8095 - rmse: 0.9686 - smape: 1.5053 - val_ia: 0.2612 - val_loss: 0.7958 - val_mae: 0.7409 - val_rmse: 0.8856 - val_smape: 1.5296

Epoch 48/128

287/287 - 5s - 17ms/step - ia: 0.2549 - loss: 0.9346 - mae: 0.8075 - rmse: 0.9656 - smape: 1.5019 - val_ia: 0.2635 - val_loss: 0.7951 - val_mae: 0.7404 - val_rmse: 0.8851 - val_smape: 1.5197

Epoch 49/128

287/287 - 5s - 18ms/step - ia: 0.2569 - loss: 0.9360 - mae: 0.8085 - rmse: 0.9662 - smape: 1.4992 - val_ia: 0.2659 - val_loss: 0.7938 - val_mae: 0.7396 - val_rmse: 0.8844 - val_smape: 1.5101

Epoch 50/128

287/287 - 5s - 17ms/step - ia: 0.2590 - loss: 0.9325 - mae: 0.8077 - rmse: 0.9646 - smape: 1.4963 - val_ia: 0.2683 - val_loss: 0.7928 - val_mae: 0.7389 - val_rmse: 0.8838 - val_smape: 1.5007

Epoch 51/128

287/287 - 4s - 15ms/step - ia: 0.2614 - loss: 0.9294 - mae: 0.8062 - rmse: 0.9628 - smape: 1.4939 - val_ia: 0.2708 - val_loss: 0.7914 - val_mae: 0.7380 - val_rmse: 0.8830 - val_smape: 1.4912

Epoch 52/128

287/287 - 5s - 16ms/step - ia: 0.2675 - loss: 0.9222 - mae: 0.8029 - rmse: 0.9595 - smape: 1.4848 - val_ia: 0.2733 - val_loss: 0.7893 - val_mae: 0.7369 - val_rmse: 0.8819 - val_smape: 1.4822

Epoch 53/128

287/287 - 5s - 16ms/step - ia: 0.2683 - loss: 0.9224 - mae: 0.8042 - rmse: 0.9592 - smape: 1.4873 - val_ia: 0.2759 - val_loss: 0.7898 - val_mae: 0.7369 - val_rmse: 0.8820 - val_smape: 1.4731

Epoch 54/128

287/287 - 5s - 16ms/step - ia: 0.2704 - loss: 0.9203 - mae: 0.8025 - rmse: 0.9581 - smape: 1.4822 - val_ia: 0.2785 - val_loss: 0.7901 - val_mae: 0.7367 - val_rmse: 0.8821 - val_smape: 1.4644

Epoch 55/128

287/287 - 5s - 17ms/step - ia: 0.2742 - loss: 0.9160 - mae: 0.8020 - rmse: 0.9559 - smape: 1.4786 - val_ia: 0.2812 - val_loss: 0.7886 - val_mae: 0.7358 - val_rmse: 0.8812 - val_smape: 1.4557

Epoch 56/128

287/287 - 5s - 17ms/step - ia: 0.2792 - loss: 0.9106 - mae: 0.7988 - rmse: 0.9530 - smape: 1.4717 - val_ia: 0.2838 - val_loss: 0.7881 - val_mae: 0.7353 - val_rmse: 0.8809 - val_smape: 1.4477

Epoch 57/128

287/287 - 5s - 16ms/step - ia: 0.2820 - loss: 0.9063 - mae: 0.7967 - rmse: 0.9509 - smape: 1.4650 - val_ia: 0.2864 - val_loss: 0.7865 - val_mae: 0.7343 - val_rmse: 0.8799 - val_smape: 1.4396

Epoch 58/128

287/287 - 5s - 18ms/step - ia: 0.2839 - loss: 0.9063 - mae: 0.7970 - rmse: 0.9508 - smape: 1.4655 - val_ia: 0.2891 - val_loss: 0.7859 - val_mae: 0.7338 - val_rmse: 0.8796 - val_smape: 1.4318

Epoch 59/128

287/287 - 4s - 15ms/step - ia: 0.2897 - loss: 0.8980 - mae: 0.7928 - rmse: 0.9466 - smape: 1.4517 - val_ia: 0.2918 - val_loss: 0.7850 - val_mae: 0.7331 - val_rmse: 0.8790 - val_smape: 1.4241

Epoch 60/128

287/287 - 4s - 16ms/step - ia: 0.2916 - loss: 0.8939 - mae: 0.7916 - rmse: 0.9447 - smape: 1.4504 - val_ia: 0.2947 - val_loss: 0.7850 - val_mae: 0.7328 - val_rmse: 0.8789 - val_smape: 1.4163

Epoch 61/128

287/287 - 5s - 16ms/step - ia: 0.2967 - loss: 0.8887 - mae: 0.7895 - rmse: 0.9416 - smape: 1.4449 - val_ia: 0.2977 - val_loss: 0.7849 - val_mae: 0.7324 - val_rmse: 0.8788 - val_smape: 1.4088

Epoch 62/128

287/287 - 5s - 17ms/step - ia: 0.3031 - loss: 0.8815 - mae: 0.7856 - rmse: 0.9377 - smape: 1.4382 - val_ia: 0.3006 - val_loss: 0.7844 - val_mae: 0.7319 - val_rmse: 0.8784 - val_smape: 1.4014

Epoch 63/128

287/287 - 5s - 18ms/step - ia: 0.3019 - loss: 0.8835 - mae: 0.7876 - rmse: 0.9390 - smape: 1.4387 - val_ia: 0.3037 - val_loss: 0.7863 - val_mae: 0.7324 - val_rmse: 0.8793 - val_smape: 1.3945

Epoch 64/128

287/287 - 5s - 16ms/step - ia: 0.3085 - loss: 0.8762 - mae: 0.7837 - rmse: 0.9350 - smape: 1.4277 - val_ia: 0.3064 - val_loss: 0.7843 - val_mae: 0.7312 - val_rmse: 0.8781 - val_smape: 1.3878

Epoch 65/128

287/287 - 5s - 18ms/step - ia: 0.3127 - loss: 0.8689 - mae: 0.7804 - rmse: 0.9312 - smape: 1.4260 - val_ia: 0.3097 - val_loss: 0.7867 - val_mae: 0.7319 - val_rmse: 0.8793 - val_smape: 1.3810

Epoch 66/128

287/287 - 5s - 16ms/step - ia: 0.3134 - loss: 0.8714 - mae: 0.7817 - rmse: 0.9323 - smape: 1.4219 - val_ia: 0.3125 - val_loss: 0.7854 - val_mae: 0.7310 - val_rmse: 0.8785 - val_smape: 1.3745

Epoch 67/128

287/287 - 5s - 18ms/step - ia: 0.3184 - loss: 0.8658 - mae: 0.7796 - rmse: 0.9290 - smape: 1.4172 - val_ia: 0.3154 - val_loss: 0.7861 - val_mae: 0.7309 - val_rmse: 0.8787 - val_smape: 1.3688

Epoch 68/128

287/287 - 5s - 16ms/step - ia: 0.3215 - loss: 0.8635 - mae: 0.7774 - rmse: 0.9279 - smape: 1.4096 - val_ia: 0.3182 - val_loss: 0.7868 - val_mae: 0.7309 - val_rmse: 0.8790 - val_smape: 1.3631

Epoch 69/128

287/287 - 5s - 17ms/step - ia: 0.3254 - loss: 0.8562 - mae: 0.7754 - rmse: 0.9244 - smape: 1.4057 - val_ia: 0.3208 - val_loss: 0.7844 - val_mae: 0.7295 - val_rmse: 0.8776 - val_smape: 1.3569

Epoch 70/128

287/287 - 5s - 19ms/step - ia: 0.3285 - loss: 0.8528 - mae: 0.7742 - rmse: 0.9224 - smape: 1.4020 - val_ia: 0.3237 - val_loss: 0.7846 - val_mae: 0.7293 - val_rmse: 0.8776 - val_smape: 1.3513

Epoch 71/128

287/287 - 5s - 18ms/step - ia: 0.3328 - loss: 0.8478 - mae: 0.7713 - rmse: 0.9194 - smape: 1.3981 - val_ia: 0.3266 - val_loss: 0.7850 - val_mae: 0.7291 - val_rmse: 0.8777 - val_smape: 1.3461

Epoch 72/128

287/287 - 5s - 16ms/step - ia: 0.3369 - loss: 0.8446 - mae: 0.7699 - rmse: 0.9179 - smape: 1.3917 - val_ia: 0.3293 - val_loss: 0.7861 - val_mae: 0.7292 - val_rmse: 0.8781 - val_smape: 1.3416

Epoch 73/128

287/287 - 5s - 18ms/step - ia: 0.3391 - loss: 0.8445 - mae: 0.7691 - rmse: 0.9179 - smape: 1.3852 - val_ia: 0.3320 - val_loss: 0.7872 - val_mae: 0.7294 - val_rmse: 0.8785 - val_smape: 1.3373

Epoch 74/128

287/287 - 5s - 17ms/step - ia: 0.3420 - loss: 0.8383 - mae: 0.7670 - rmse: 0.9145 - smape: 1.3851 - val_ia: 0.3349 - val_loss: 0.7917 - val_mae: 0.7310 - val_rmse: 0.8807 - val_smape: 1.3342

Epoch 75/128

287/287 - 5s - 16ms/step - ia: 0.3475 - loss: 0.8311 - mae: 0.7634 - rmse: 0.9106 - smape: 1.3762 - val_ia: 0.3375 - val_loss: 0.7898 - val_mae: 0.7299 - val_rmse: 0.8796 - val_smape: 1.3292

Epoch 76/128

287/287 - 5s - 17ms/step - ia: 0.3510 - loss: 0.8288 - mae: 0.7614 - rmse: 0.9094 - smape: 1.3728 - val_ia: 0.3404 - val_loss: 0.7897 - val_mae: 0.7295 - val_rmse: 0.8794 - val_smape: 1.3244

Epoch 77/128

287/287 - 6s - 20ms/step - ia: 0.3563 - loss: 0.8211 - mae: 0.7575 - rmse: 0.9051 - smape: 1.3637 - val_ia: 0.3432 - val_loss: 0.7885 - val_mae: 0.7286 - val_rmse: 0.8786 - val_smape: 1.3198

Epoch 78/128

287/287 - 5s - 17ms/step - ia: 0.3575 - loss: 0.8191 - mae: 0.7577 - rmse: 0.9039 - smape: 1.3643 - val_ia: 0.3464 - val_loss: 0.7929 - val_mae: 0.7302 - val_rmse: 0.8808 - val_smape: 1.3175

Epoch 79/128

287/287 - 5s - 18ms/step - ia: 0.3643 - loss: 0.8083 - mae: 0.7519 - rmse: 0.8977 - smape: 1.3521 - val_ia: 0.3495 - val_loss: 0.7942 - val_mae: 0.7304 - val_rmse: 0.8812 - val_smape: 1.3133

Epoch 79: early stopping

Restoring model weights from the end of the best epoch: 64.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:13 451ms/step
 11/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 25/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 82/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 97/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
111/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
155/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

Epoch 1/128

 50%|█████     | 6/12 [1:14:05<1:06:13, 662.27s/trial, best loss: 0.1851744141239589]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 10s - 37ms/step - ia: 0.7633 - loss: 0.2262 - mae: 0.3599 - rmse: 0.4604 - smape: 0.7258 - val_ia: 0.7764 - val_loss: 0.1596 - val_mae: 0.3205 - val_rmse: 0.3895 - val_smape: 0.7220

Epoch 2/128

287/287 - 6s - 19ms/step - ia: 0.8347 - loss: 0.1202 - mae: 0.2606 - rmse: 0.3451 - smape: 0.5932 - val_ia: 0.7945 - val_loss: 0.1336 - val_mae: 0.2881 - val_rmse: 0.3491 - val_smape: 0.6477

Epoch 3/128

287/287 - 3s - 9ms/step - ia: 0.8471 - loss: 0.1043 - mae: 0.2421 - rmse: 0.3216 - smape: 0.5646 - val_ia: 0.8068 - val_loss: 0.1261 - val_mae: 0.2798 - val_rmse: 0.3423 - val_smape: 0.6427

Epoch 4/128

287/287 - 3s - 9ms/step - ia: 0.8511 - loss: 0.0995 - mae: 0.2367 - rmse: 0.3138 - smape: 0.5495 - val_ia: 0.7842 - val_loss: 0.1569 - val_mae: 0.3093 - val_rmse: 0.3650 - val_smape: 0.6768

Epoch 5/128

287/287 - 3s - 9ms/step - ia: 0.8574 - loss: 0.0918 - mae: 0.2272 - rmse: 0.3018 - smape: 0.5294 - val_ia: 0.8112 - val_loss: 0.1155 - val_mae: 0.2669 - val_rmse: 0.3223 - val_smape: 0.6378

Epoch 6/128

287/287 - 3s - 9ms/step - ia: 0.8600 - loss: 0.0883 - mae: 0.2234 - rmse: 0.2959 - smape: 0.5195 - val_ia: 0.7948 - val_loss: 0.1479 - val_mae: 0.2944 - val_rmse: 0.3511 - val_smape: 0.6502

Epoch 7/128

287/287 - 3s - 9ms/step - ia: 0.8665 - loss: 0.0812 - mae: 0.2136 - rmse: 0.2835 - smape: 0.5007 - val_ia: 0.7985 - val_loss: 0.1410 - val_mae: 0.2839 - val_rmse: 0.3474 - val_smape: 0.6503

Epoch 8/128

287/287 - 3s - 9ms/step - ia: 0.8708 - loss: 0.0765 - mae: 0.2074 - rmse: 0.2753 - smape: 0.4890 - val_ia: 0.7881 - val_loss: 0.1534 - val_mae: 0.3016 - val_rmse: 0.3700 - val_smape: 0.6777

Epoch 9/128

287/287 - 3s - 10ms/step - ia: 0.8721 - loss: 0.0750 - mae: 0.2054 - rmse: 0.2727 - smape: 0.4863 - val_ia: 0.8029 - val_loss: 0.1290 - val_mae: 0.2744 - val_rmse: 0.3371 - val_smape: 0.6423

Epoch 10/128

287/287 - 3s - 9ms/step - ia: 0.8734 - loss: 0.0737 - mae: 0.2036 - rmse: 0.2701 - smape: 0.4819 - val_ia: 0.8024 - val_loss: 0.1410 - val_mae: 0.2861 - val_rmse: 0.3475 - val_smape: 0.6519

Epoch 11/128

287/287 - 2s - 9ms/step - ia: 0.8754 - loss: 0.0712 - mae: 0.2001 - rmse: 0.2655 - smape: 0.4738 - val_ia: 0.7932 - val_loss: 0.1443 - val_mae: 0.2861 - val_rmse: 0.3550 - val_smape: 0.6600

Epoch 12/128

287/287 - 3s - 9ms/step - ia: 0.8774 - loss: 0.0692 - mae: 0.1974 - rmse: 0.2618 - smape: 0.4707 - val_ia: 0.7802 - val_loss: 0.1680 - val_mae: 0.3101 - val_rmse: 0.3789 - val_smape: 0.6825

Epoch 13/128

287/287 - 3s - 9ms/step - ia: 0.8793 - loss: 0.0672 - mae: 0.1941 - rmse: 0.2575 - smape: 0.4605 - val_ia: 0.7840 - val_loss: 0.1639 - val_mae: 0.3044 - val_rmse: 0.3726 - val_smape: 0.6710

Epoch 14/128

287/287 - 3s - 9ms/step - ia: 0.8810 - loss: 0.0654 - mae: 0.1916 - rmse: 0.2546 - smape: 0.4582 - val_ia: 0.7726 - val_loss: 0.1778 - val_mae: 0.3221 - val_rmse: 0.3927 - val_smape: 0.6984

Epoch 15/128

287/287 - 2s - 8ms/step - ia: 0.8710 - loss: 0.0795 - mae: 0.2066 - rmse: 0.2768 - smape: 0.4838 - val_ia: 0.7386 - val_loss: 0.2522 - val_mae: 0.3712 - val_rmse: 0.4663 - val_smape: 0.7684

Epoch 16/128

287/287 - 3s - 9ms/step - ia: 0.8716 - loss: 0.0757 - mae: 0.2059 - rmse: 0.2736 - smape: 0.4829 - val_ia: 0.7612 - val_loss: 0.1779 - val_mae: 0.3245 - val_rmse: 0.3916 - val_smape: 0.7300

Epoch 17/128

287/287 - 3s - 9ms/step - ia: 0.4530 - loss: 391848427520.0000 - mae: 130559.2344 - rmse: 296759.2812 - smape: 1.1779 - val_ia: 9.0269e-07 - val_loss: 1366294528000.0000 - val_mae: 699888.6250 - val_rmse: 1138349.6250 - val_smape: 1.9998

Epoch 18/128

287/287 - 3s - 9ms/step - ia: 1.1809e-05 - loss: 674891300864.0000 - mae: 303343.1250 - rmse: 590002.6250 - smape: 1.9987 - val_ia: 1.4899e-04 - val_loss: 85120064.0000 - val_mae: 4932.0605 - val_rmse: 8755.4668 - val_smape: 1.9903

Epoch 19/128

287/287 - 2s - 9ms/step - ia: 5.0318e-04 - loss: 44953896.0000 - mae: 2615.4700 - rmse: 5292.5176 - smape: 1.9690 - val_ia: 0.0013 - val_loss: 1687333.6250 - val_mae: 513.9719 - val_rmse: 1210.8909 - val_smape: 1.9271

Epoch 20/128

287/287 - 2s - 9ms/step - ia: 0.0019 - loss: 1542649.3750 - mae: 477.3865 - rmse: 1092.9309 - smape: 1.9191 - val_ia: 0.0051 - val_loss: 114722.1094 - val_mae: 131.3170 - val_rmse: 315.9122 - val_smape: 1.8760

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 41s 255ms/step
  8/163 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
 26/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
153/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 58%|█████▊    | 7/12 [1:15:09<38:53, 466.64s/trial, best loss: 0.18220391301703978]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 52s - 11ms/step - ia: 0.7885 - loss: 0.1569 - mae: 0.2955 - rmse: 0.3703 - smape: 0.6546 - val_ia: 0.2606 - val_loss: 0.2898 - val_mae: 0.4031 - val_rmse: 0.4197 - val_smape: 0.7475

Epoch 2/128

4584/4584 - 87s - 19ms/step - ia: 0.8328 - loss: 0.1018 - mae: 0.2374 - rmse: 0.3016 - smape: 0.5511 - val_ia: 0.2700 - val_loss: 0.2255 - val_mae: 0.3629 - val_rmse: 0.3831 - val_smape: 0.7234

Epoch 3/128

4584/4584 - 45s - 10ms/step - ia: 0.8461 - loss: 0.0863 - mae: 0.2179 - rmse: 0.2773 - smape: 0.5131 - val_ia: 0.2787 - val_loss: 0.2217 - val_mae: 0.3556 - val_rmse: 0.3699 - val_smape: 0.7365

Epoch 4/128

4584/4584 - 82s - 18ms/step - ia: 0.8550 - loss: 0.0779 - mae: 0.2068 - rmse: 0.2632 - smape: 0.4916 - val_ia: 0.2350 - val_loss: 0.3184 - val_mae: 0.4209 - val_rmse: 0.4439 - val_smape: 0.8424

Epoch 5/128

4584/4584 - 44s - 10ms/step - ia: 0.8595 - loss: 0.0721 - mae: 0.1995 - rmse: 0.2535 - smape: 0.4775 - val_ia: 0.2685 - val_loss: 0.1821 - val_mae: 0.3296 - val_rmse: 0.3451 - val_smape: 0.7109

Epoch 6/128

4584/4584 - 50s - 11ms/step - ia: 0.8660 - loss: 0.0669 - mae: 0.1908 - rmse: 0.2437 - smape: 0.4588 - val_ia: 0.2546 - val_loss: 0.2549 - val_mae: 0.3789 - val_rmse: 0.3978 - val_smape: 0.7666

Epoch 7/128

4584/4584 - 44s - 10ms/step - ia: 0.8683 - loss: 0.0640 - mae: 0.1872 - rmse: 0.2383 - smape: 0.4525 - val_ia: 0.2504 - val_loss: 0.2591 - val_mae: 0.3803 - val_rmse: 0.4003 - val_smape: 0.8063

Epoch 8/128

4584/4584 - 43s - 9ms/step - ia: 0.8717 - loss: 0.0614 - mae: 0.1835 - rmse: 0.2332 - smape: 0.4452 - val_ia: 0.2708 - val_loss: 0.2301 - val_mae: 0.3550 - val_rmse: 0.3749 - val_smape: 0.7519

Epoch 9/128

4584/4584 - 82s - 18ms/step - ia: 0.8760 - loss: 0.0586 - mae: 0.1786 - rmse: 0.2275 - smape: 0.4363 - val_ia: 0.2837 - val_loss: 0.2279 - val_mae: 0.3431 - val_rmse: 0.3636 - val_smape: 0.7380

Epoch 10/128

4584/4584 - 44s - 10ms/step - ia: 0.8778 - loss: 0.0559 - mae: 0.1747 - rmse: 0.2226 - smape: 0.4274 - val_ia: 0.2716 - val_loss: 0.2439 - val_mae: 0.3636 - val_rmse: 0.3833 - val_smape: 0.7530

Epoch 11/128

4584/4584 - 42s - 9ms/step - ia: 0.8783 - loss: 0.0559 - mae: 0.1739 - rmse: 0.2218 - smape: 0.4296 - val_ia: 0.2930 - val_loss: 0.2040 - val_mae: 0.3275 - val_rmse: 0.3477 - val_smape: 0.6962

Epoch 12/128

4584/4584 - 44s - 10ms/step - ia: 0.8810 - loss: 0.0531 - mae: 0.1703 - rmse: 0.2167 - smape: 0.4227 - val_ia: 0.2860 - val_loss: 0.2151 - val_mae: 0.3336 - val_rmse: 0.3540 - val_smape: 0.7207

Epoch 13/128

4584/4584 - 43s - 9ms/step - ia: 0.8829 - loss: 0.0522 - mae: 0.1680 - rmse: 0.2144 - smape: 0.4150 - val_ia: 0.2614 - val_loss: 0.2907 - val_mae: 0.3931 - val_rmse: 0.4151 - val_smape: 0.7720

Epoch 14/128

4584/4584 - 47s - 10ms/step - ia: 0.8840 - loss: 0.0513 - mae: 0.1663 - rmse: 0.2123 - smape: 0.4117 - val_ia: 0.2810 - val_loss: 0.2134 - val_mae: 0.3322 - val_rmse: 0.3548 - val_smape: 0.7070

Epoch 15/128

4584/4584 - 43s - 9ms/step - ia: 0.8867 - loss: 0.0487 - mae: 0.1636 - rmse: 0.2080 - smape: 0.4059 - val_ia: 0.2964 - val_loss: 0.1962 - val_mae: 0.3183 - val_rmse: 0.3392 - val_smape: 0.6826

Epoch 16/128

4584/4584 - 43s - 9ms/step - ia: 0.8883 - loss: 0.0473 - mae: 0.1611 - rmse: 0.2049 - smape: 0.4037 - val_ia: 0.2703 - val_loss: 0.2217 - val_mae: 0.3519 - val_rmse: 0.3739 - val_smape: 0.7175

Epoch 17/128

4584/4584 - 77s - 17ms/step - ia: 0.8883 - loss: 0.0473 - mae: 0.1604 - rmse: 0.2043 - smape: 0.4024 - val_ia: 0.2627 - val_loss: 0.2390 - val_mae: 0.3555 - val_rmse: 0.3826 - val_smape: 0.7229

Epoch 18/128

4584/4584 - 42s - 9ms/step - ia: 0.8900 - loss: 0.0458 - mae: 0.1580 - rmse: 0.2011 - smape: 0.3973 - val_ia: 0.2771 - val_loss: 0.1852 - val_mae: 0.3215 - val_rmse: 0.3449 - val_smape: 0.6760

Epoch 19/128

4584/4584 - 42s - 9ms/step - ia: 0.8893 - loss: 0.0467 - mae: 0.1590 - rmse: 0.2026 - smape: 0.3975 - val_ia: 0.2857 - val_loss: 0.1873 - val_mae: 0.3169 - val_rmse: 0.3399 - val_smape: 0.6537

Epoch 20/128

4584/4584 - 42s - 9ms/step - ia: 0.8908 - loss: 0.0449 - mae: 0.1567 - rmse: 0.1994 - smape: 0.3946 - val_ia: 0.2638 - val_loss: 0.2320 - val_mae: 0.3528 - val_rmse: 0.3773 - val_smape: 0.7524

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 5.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:50 1s/step
 10/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 90/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
103/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
128/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
162/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step

 67%|██████▋   | 8/12 [1:32:30<43:18, 649.52s/trial, best loss: 0.18220391301703978]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 5s - 19ms/step - ia: 0.4914 - loss: 0.6954 - mae: 0.6581 - rmse: 0.8122 - smape: 1.1813 - val_ia: 0.5357 - val_loss: 0.7840 - val_mae: 0.7323 - val_rmse: 0.8386 - val_smape: 1.1597

Epoch 2/128

287/287 - 1s - 5ms/step - ia: 0.6869 - loss: 0.3482 - mae: 0.4676 - rmse: 0.5885 - smape: 0.8666 - val_ia: 0.5942 - val_loss: 0.4365 - val_mae: 0.5577 - val_rmse: 0.6365 - val_smape: 1.0302

Epoch 3/128

287/287 - 1s - 5ms/step - ia: 0.7171 - loss: 0.2971 - mae: 0.4266 - rmse: 0.5437 - smape: 0.8237 - val_ia: 0.6437 - val_loss: 0.3385 - val_mae: 0.4832 - val_rmse: 0.5551 - val_smape: 0.9211

Epoch 4/128

287/287 - 3s - 9ms/step - ia: 0.7307 - loss: 0.2729 - mae: 0.4070 - rmse: 0.5208 - smape: 0.8025 - val_ia: 0.6453 - val_loss: 0.3445 - val_mae: 0.4820 - val_rmse: 0.5583 - val_smape: 0.9196

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.7413 - loss: 0.2543 - mae: 0.3914 - rmse: 0.5029 - smape: 0.7848 - val_ia: 0.6683 - val_loss: 0.2954 - val_mae: 0.4378 - val_rmse: 0.5154 - val_smape: 0.8703

Epoch 6/128

287/287 - 1s - 5ms/step - ia: 0.7484 - loss: 0.2402 - mae: 0.3812 - rmse: 0.4887 - smape: 0.7693 - val_ia: 0.6834 - val_loss: 0.2810 - val_mae: 0.4239 - val_rmse: 0.5036 - val_smape: 0.8537

Epoch 7/128

287/287 - 2s - 8ms/step - ia: 0.7548 - loss: 0.2288 - mae: 0.3712 - rmse: 0.4769 - smape: 0.7531 - val_ia: 0.6845 - val_loss: 0.2677 - val_mae: 0.4170 - val_rmse: 0.4999 - val_smape: 0.8538

Epoch 8/128

287/287 - 1s - 5ms/step - ia: 0.7612 - loss: 0.2195 - mae: 0.3629 - rmse: 0.4671 - smape: 0.7394 - val_ia: 0.6877 - val_loss: 0.2721 - val_mae: 0.4152 - val_rmse: 0.4994 - val_smape: 0.8449

Epoch 9/128

287/287 - 1s - 5ms/step - ia: 0.7675 - loss: 0.2096 - mae: 0.3538 - rmse: 0.4567 - smape: 0.7260 - val_ia: 0.7043 - val_loss: 0.2463 - val_mae: 0.4021 - val_rmse: 0.4775 - val_smape: 0.8234

Epoch 10/128

287/287 - 1s - 4ms/step - ia: 0.7731 - loss: 0.2011 - mae: 0.3466 - rmse: 0.4470 - smape: 0.7111 - val_ia: 0.7197 - val_loss: 0.2280 - val_mae: 0.3805 - val_rmse: 0.4593 - val_smape: 0.8178

Epoch 11/128

287/287 - 1s - 4ms/step - ia: 0.7814 - loss: 0.1892 - mae: 0.3347 - rmse: 0.4336 - smape: 0.6977 - val_ia: 0.7254 - val_loss: 0.2279 - val_mae: 0.3770 - val_rmse: 0.4599 - val_smape: 0.8125

Epoch 12/128

287/287 - 1s - 4ms/step - ia: 0.7891 - loss: 0.1794 - mae: 0.3238 - rmse: 0.4223 - smape: 0.6828 - val_ia: 0.7463 - val_loss: 0.1870 - val_mae: 0.3386 - val_rmse: 0.4162 - val_smape: 0.7616

Epoch 13/128

287/287 - 3s - 9ms/step - ia: 0.7939 - loss: 0.1731 - mae: 0.3175 - rmse: 0.4150 - smape: 0.6741 - val_ia: 0.7579 - val_loss: 0.1789 - val_mae: 0.3361 - val_rmse: 0.4087 - val_smape: 0.7577

Epoch 14/128

287/287 - 1s - 4ms/step - ia: 0.7963 - loss: 0.1696 - mae: 0.3133 - rmse: 0.4106 - smape: 0.6691 - val_ia: 0.7732 - val_loss: 0.1601 - val_mae: 0.3198 - val_rmse: 0.3863 - val_smape: 0.7161

Epoch 15/128

287/287 - 1s - 4ms/step - ia: 0.7971 - loss: 0.1691 - mae: 0.3128 - rmse: 0.4098 - smape: 0.6671 - val_ia: 0.7661 - val_loss: 0.1700 - val_mae: 0.3227 - val_rmse: 0.4009 - val_smape: 0.7289

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.7998 - loss: 0.1645 - mae: 0.3082 - rmse: 0.4039 - smape: 0.6618 - val_ia: 0.7715 - val_loss: 0.1610 - val_mae: 0.3134 - val_rmse: 0.3930 - val_smape: 0.7067

Epoch 17/128

287/287 - 1s - 4ms/step - ia: 0.8019 - loss: 0.1621 - mae: 0.3053 - rmse: 0.4012 - smape: 0.6551 - val_ia: 0.7850 - val_loss: 0.1481 - val_mae: 0.2930 - val_rmse: 0.3713 - val_smape: 0.6664

Epoch 18/128

287/287 - 1s - 5ms/step - ia: 0.8017 - loss: 0.1627 - mae: 0.3056 - rmse: 0.4023 - smape: 0.6537 - val_ia: 0.7968 - val_loss: 0.1310 - val_mae: 0.2796 - val_rmse: 0.3505 - val_smape: 0.6492

Epoch 19/128

287/287 - 1s - 4ms/step - ia: 0.8032 - loss: 0.1599 - mae: 0.3031 - rmse: 0.3987 - smape: 0.6513 - val_ia: 0.7936 - val_loss: 0.1391 - val_mae: 0.2869 - val_rmse: 0.3624 - val_smape: 0.6481

Epoch 20/128

287/287 - 1s - 5ms/step - ia: 0.8041 - loss: 0.1586 - mae: 0.3018 - rmse: 0.3973 - smape: 0.6482 - val_ia: 0.7816 - val_loss: 0.1617 - val_mae: 0.3023 - val_rmse: 0.3902 - val_smape: 0.6683

Epoch 21/128

287/287 - 1s - 5ms/step - ia: 0.8059 - loss: 0.1565 - mae: 0.2997 - rmse: 0.3944 - smape: 0.6423 - val_ia: 0.7835 - val_loss: 0.1448 - val_mae: 0.2921 - val_rmse: 0.3716 - val_smape: 0.6699

Epoch 22/128

287/287 - 3s - 9ms/step - ia: 0.8070 - loss: 0.1546 - mae: 0.2978 - rmse: 0.3922 - smape: 0.6425 - val_ia: 0.7888 - val_loss: 0.1491 - val_mae: 0.3001 - val_rmse: 0.3709 - val_smape: 0.6739

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.8066 - loss: 0.1560 - mae: 0.2985 - rmse: 0.3934 - smape: 0.6417 - val_ia: 0.7941 - val_loss: 0.1500 - val_mae: 0.2895 - val_rmse: 0.3676 - val_smape: 0.6532

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.8067 - loss: 0.1540 - mae: 0.2981 - rmse: 0.3911 - smape: 0.6455 - val_ia: 0.7854 - val_loss: 0.1632 - val_mae: 0.2981 - val_rmse: 0.3865 - val_smape: 0.6595

Epoch 25/128

287/287 - 1s - 4ms/step - ia: 0.8082 - loss: 0.1527 - mae: 0.2960 - rmse: 0.3895 - smape: 0.6409 - val_ia: 0.7818 - val_loss: 0.1631 - val_mae: 0.3004 - val_rmse: 0.3857 - val_smape: 0.6680

Epoch 26/128

287/287 - 3s - 9ms/step - ia: 0.8085 - loss: 0.1526 - mae: 0.2955 - rmse: 0.3893 - smape: 0.6387 - val_ia: 0.7834 - val_loss: 0.1679 - val_mae: 0.3118 - val_rmse: 0.3905 - val_smape: 0.6816

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.8094 - loss: 0.1513 - mae: 0.2944 - rmse: 0.3878 - smape: 0.6369 - val_ia: 0.7889 - val_loss: 0.1586 - val_mae: 0.2963 - val_rmse: 0.3774 - val_smape: 0.6637

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.8080 - loss: 0.1526 - mae: 0.2961 - rmse: 0.3895 - smape: 0.6403 - val_ia: 0.7842 - val_loss: 0.1697 - val_mae: 0.3070 - val_rmse: 0.3917 - val_smape: 0.6778

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.8077 - loss: 0.1531 - mae: 0.2964 - rmse: 0.3902 - smape: 0.6396 - val_ia: 0.7882 - val_loss: 0.1577 - val_mae: 0.2969 - val_rmse: 0.3797 - val_smape: 0.6615

Epoch 30/128

287/287 - 1s - 4ms/step - ia: 0.8093 - loss: 0.1501 - mae: 0.2943 - rmse: 0.3863 - smape: 0.6389 - val_ia: 0.7787 - val_loss: 0.1755 - val_mae: 0.3111 - val_rmse: 0.4011 - val_smape: 0.6758

Epoch 31/128

287/287 - 1s - 5ms/step - ia: 0.8099 - loss: 0.1499 - mae: 0.2934 - rmse: 0.3859 - smape: 0.6392 - val_ia: 0.7867 - val_loss: 0.1673 - val_mae: 0.3084 - val_rmse: 0.3868 - val_smape: 0.6727

Epoch 32/128

287/287 - 1s - 5ms/step - ia: 0.8106 - loss: 0.1498 - mae: 0.2925 - rmse: 0.3856 - smape: 0.6337 - val_ia: 0.7889 - val_loss: 0.1588 - val_mae: 0.3010 - val_rmse: 0.3795 - val_smape: 0.6615

Epoch 33/128

287/287 - 1s - 4ms/step - ia: 0.8112 - loss: 0.1495 - mae: 0.2919 - rmse: 0.3854 - smape: 0.6337 - val_ia: 0.7832 - val_loss: 0.1700 - val_mae: 0.3088 - val_rmse: 0.3976 - val_smape: 0.6771

Epoch 33: early stopping

Restoring model weights from the end of the best epoch: 18.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 34s 215ms/step
 21/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 57/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 64/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
135/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 75%|███████▌  | 9/12 [1:33:26<23:11, 463.76s/trial, best loss: 0.18220391301703978]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 32s - 14ms/step - ia: 0.3401 - loss: 0.8885 - mae: 0.7794 - rmse: 0.9288 - smape: 1.3926 - val_ia: 0.1809 - val_loss: 1.2966 - val_mae: 0.9441 - val_rmse: 0.9757 - val_smape: 1.3513

Epoch 2/128

2292/2292 - 41s - 18ms/step - ia: 0.5591 - loss: 0.5574 - mae: 0.6022 - rmse: 0.7358 - smape: 1.0308 - val_ia: 0.1780 - val_loss: 1.2883 - val_mae: 0.9408 - val_rmse: 0.9728 - val_smape: 1.3629

Epoch 3/128

2292/2292 - 26s - 11ms/step - ia: 0.6129 - loss: 0.4627 - mae: 0.5433 - rmse: 0.6697 - smape: 0.9347 - val_ia: 0.1760 - val_loss: 1.3403 - val_mae: 0.9682 - val_rmse: 1.0001 - val_smape: 1.3798

Epoch 4/128

2292/2292 - 40s - 18ms/step - ia: 0.6485 - loss: 0.4011 - mae: 0.5055 - rmse: 0.6236 - smape: 0.8732 - val_ia: 0.1840 - val_loss: 1.1678 - val_mae: 0.8947 - val_rmse: 0.9264 - val_smape: 1.3134

Epoch 5/128

2292/2292 - 26s - 11ms/step - ia: 0.6699 - loss: 0.3659 - mae: 0.4815 - rmse: 0.5956 - smape: 0.8322 - val_ia: 0.1920 - val_loss: 0.9426 - val_mae: 0.7946 - val_rmse: 0.8255 - val_smape: 1.2489

Epoch 6/128

2292/2292 - 40s - 17ms/step - ia: 0.6829 - loss: 0.3423 - mae: 0.4657 - rmse: 0.5755 - smape: 0.8109 - val_ia: 0.2062 - val_loss: 0.8666 - val_mae: 0.7518 - val_rmse: 0.7842 - val_smape: 1.1915

Epoch 7/128

2292/2292 - 42s - 18ms/step - ia: 0.6934 - loss: 0.3224 - mae: 0.4505 - rmse: 0.5586 - smape: 0.7945 - val_ia: 0.2093 - val_loss: 0.7772 - val_mae: 0.7114 - val_rmse: 0.7432 - val_smape: 1.1722

Epoch 8/128

2292/2292 - 25s - 11ms/step - ia: 0.7044 - loss: 0.3049 - mae: 0.4367 - rmse: 0.5431 - smape: 0.7805 - val_ia: 0.2231 - val_loss: 0.6363 - val_mae: 0.6388 - val_rmse: 0.6709 - val_smape: 1.0971

Epoch 9/128

2292/2292 - 28s - 12ms/step - ia: 0.7122 - loss: 0.2897 - mae: 0.4255 - rmse: 0.5296 - smape: 0.7716 - val_ia: 0.2220 - val_loss: 0.6175 - val_mae: 0.6281 - val_rmse: 0.6596 - val_smape: 1.1022

Epoch 10/128

2292/2292 - 41s - 18ms/step - ia: 0.7212 - loss: 0.2735 - mae: 0.4116 - rmse: 0.5138 - smape: 0.7605 - val_ia: 0.2341 - val_loss: 0.5266 - val_mae: 0.5817 - val_rmse: 0.6116 - val_smape: 1.0476

Epoch 11/128

2292/2292 - 28s - 12ms/step - ia: 0.7300 - loss: 0.2589 - mae: 0.3992 - rmse: 0.4993 - smape: 0.7558 - val_ia: 0.2422 - val_loss: 0.4845 - val_mae: 0.5634 - val_rmse: 0.5915 - val_smape: 1.0311

Epoch 12/128

2292/2292 - 27s - 12ms/step - ia: 0.7413 - loss: 0.2430 - mae: 0.3844 - rmse: 0.4831 - smape: 0.7452 - val_ia: 0.2422 - val_loss: 0.5212 - val_mae: 0.5864 - val_rmse: 0.6158 - val_smape: 1.0650

Epoch 13/128

2292/2292 - 41s - 18ms/step - ia: 0.7498 - loss: 0.2275 - mae: 0.3706 - rmse: 0.4679 - smape: 0.7376 - val_ia: 0.2610 - val_loss: 0.3954 - val_mae: 0.5083 - val_rmse: 0.5361 - val_smape: 0.9635

Epoch 14/128

2292/2292 - 27s - 12ms/step - ia: 0.7579 - loss: 0.2134 - mae: 0.3581 - rmse: 0.4522 - smape: 0.7287 - val_ia: 0.2577 - val_loss: 0.4532 - val_mae: 0.5373 - val_rmse: 0.5689 - val_smape: 0.9776

Epoch 15/128

2292/2292 - 42s - 18ms/step - ia: 0.7662 - loss: 0.2006 - mae: 0.3461 - rmse: 0.4388 - smape: 0.7228 - val_ia: 0.2729 - val_loss: 0.3623 - val_mae: 0.4815 - val_rmse: 0.5120 - val_smape: 0.9175

Epoch 16/128

2292/2292 - 28s - 12ms/step - ia: 0.7745 - loss: 0.1866 - mae: 0.3324 - rmse: 0.4223 - smape: 0.7098 - val_ia: 0.2764 - val_loss: 0.3501 - val_mae: 0.4706 - val_rmse: 0.5015 - val_smape: 0.9139

Epoch 17/128

2292/2292 - 26s - 11ms/step - ia: 0.7808 - loss: 0.1779 - mae: 0.3236 - rmse: 0.4122 - smape: 0.7011 - val_ia: 0.2793 - val_loss: 0.3376 - val_mae: 0.4586 - val_rmse: 0.4916 - val_smape: 0.8726

Epoch 18/128

2292/2292 - 28s - 12ms/step - ia: 0.7852 - loss: 0.1724 - mae: 0.3170 - rmse: 0.4056 - smape: 0.6911 - val_ia: 0.2799 - val_loss: 0.3550 - val_mae: 0.4706 - val_rmse: 0.5020 - val_smape: 0.8929

Epoch 19/128

2292/2292 - 28s - 12ms/step - ia: 0.7896 - loss: 0.1667 - mae: 0.3114 - rmse: 0.3987 - smape: 0.6825 - val_ia: 0.2903 - val_loss: 0.2920 - val_mae: 0.4306 - val_rmse: 0.4624 - val_smape: 0.8511

Epoch 20/128

2292/2292 - 27s - 12ms/step - ia: 0.7920 - loss: 0.1623 - mae: 0.3062 - rmse: 0.3929 - smape: 0.6758 - val_ia: 0.2892 - val_loss: 0.3025 - val_mae: 0.4371 - val_rmse: 0.4700 - val_smape: 0.8458

Epoch 21/128

2292/2292 - 28s - 12ms/step - ia: 0.7945 - loss: 0.1593 - mae: 0.3035 - rmse: 0.3897 - smape: 0.6702 - val_ia: 0.3010 - val_loss: 0.2493 - val_mae: 0.4028 - val_rmse: 0.4346 - val_smape: 0.8176

Epoch 22/128

2292/2292 - 26s - 11ms/step - ia: 0.7956 - loss: 0.1567 - mae: 0.3005 - rmse: 0.3865 - smape: 0.6652 - val_ia: 0.2936 - val_loss: 0.2736 - val_mae: 0.4187 - val_rmse: 0.4525 - val_smape: 0.8309

Epoch 23/128

2292/2292 - 25s - 11ms/step - ia: 0.7977 - loss: 0.1539 - mae: 0.2978 - rmse: 0.3828 - smape: 0.6603 - val_ia: 0.3007 - val_loss: 0.2302 - val_mae: 0.3909 - val_rmse: 0.4240 - val_smape: 0.8061

Epoch 24/128

2292/2292 - 41s - 18ms/step - ia: 0.8002 - loss: 0.1512 - mae: 0.2952 - rmse: 0.3799 - smape: 0.6565 - val_ia: 0.3059 - val_loss: 0.2139 - val_mae: 0.3784 - val_rmse: 0.4102 - val_smape: 0.7921

Epoch 25/128

2292/2292 - 41s - 18ms/step - ia: 0.8023 - loss: 0.1483 - mae: 0.2920 - rmse: 0.3755 - smape: 0.6509 - val_ia: 0.2830 - val_loss: 0.2906 - val_mae: 0.4299 - val_rmse: 0.4672 - val_smape: 0.8434

Epoch 26/128

2292/2292 - 44s - 19ms/step - ia: 0.8035 - loss: 0.1470 - mae: 0.2912 - rmse: 0.3741 - smape: 0.6488 - val_ia: 0.3164 - val_loss: 0.1977 - val_mae: 0.3646 - val_rmse: 0.3950 - val_smape: 0.7706

Epoch 27/128

2292/2292 - 40s - 17ms/step - ia: 0.8050 - loss: 0.1443 - mae: 0.2878 - rmse: 0.3702 - smape: 0.6440 - val_ia: 0.3002 - val_loss: 0.2267 - val_mae: 0.3853 - val_rmse: 0.4207 - val_smape: 0.7988

Epoch 28/128

2292/2292 - 26s - 11ms/step - ia: 0.8071 - loss: 0.1419 - mae: 0.2859 - rmse: 0.3674 - smape: 0.6424 - val_ia: 0.3127 - val_loss: 0.2074 - val_mae: 0.3703 - val_rmse: 0.4026 - val_smape: 0.7801

Epoch 29/128

2292/2292 - 41s - 18ms/step - ia: 0.8084 - loss: 0.1392 - mae: 0.2832 - rmse: 0.3638 - smape: 0.6392 - val_ia: 0.2984 - val_loss: 0.2621 - val_mae: 0.4038 - val_rmse: 0.4423 - val_smape: 0.8043

Epoch 30/128

2292/2292 - 40s - 17ms/step - ia: 0.8100 - loss: 0.1379 - mae: 0.2816 - rmse: 0.3621 - smape: 0.6378 - val_ia: 0.3011 - val_loss: 0.2360 - val_mae: 0.3886 - val_rmse: 0.4254 - val_smape: 0.7906

Epoch 31/128

2292/2292 - 27s - 12ms/step - ia: 0.8117 - loss: 0.1353 - mae: 0.2792 - rmse: 0.3588 - smape: 0.6358 - val_ia: 0.3353 - val_loss: 0.1750 - val_mae: 0.3416 - val_rmse: 0.3719 - val_smape: 0.7366

Epoch 32/128

2292/2292 - 29s - 12ms/step - ia: 0.8143 - loss: 0.1325 - mae: 0.2766 - rmse: 0.3550 - smape: 0.6323 - val_ia: 0.3065 - val_loss: 0.2179 - val_mae: 0.3754 - val_rmse: 0.4112 - val_smape: 0.7815

Epoch 33/128

2292/2292 - 29s - 13ms/step - ia: 0.8167 - loss: 0.1294 - mae: 0.2730 - rmse: 0.3503 - smape: 0.6313 - val_ia: 0.3299 - val_loss: 0.1721 - val_mae: 0.3384 - val_rmse: 0.3718 - val_smape: 0.7370

Epoch 34/128

2292/2292 - 26s - 11ms/step - ia: 0.8193 - loss: 0.1265 - mae: 0.2698 - rmse: 0.3465 - smape: 0.6283 - val_ia: 0.3124 - val_loss: 0.2008 - val_mae: 0.3617 - val_rmse: 0.3975 - val_smape: 0.7758

Epoch 35/128

2292/2292 - 28s - 12ms/step - ia: 0.8205 - loss: 0.1250 - mae: 0.2677 - rmse: 0.3444 - smape: 0.6290 - val_ia: 0.2949 - val_loss: 0.2453 - val_mae: 0.3904 - val_rmse: 0.4303 - val_smape: 0.7938

Epoch 36/128

2292/2292 - 41s - 18ms/step - ia: 0.8232 - loss: 0.1212 - mae: 0.2639 - rmse: 0.3387 - smape: 0.6254 - val_ia: 0.3336 - val_loss: 0.1875 - val_mae: 0.3465 - val_rmse: 0.3820 - val_smape: 0.7404

Epoch 37/128

2292/2292 - 28s - 12ms/step - ia: 0.8244 - loss: 0.1201 - mae: 0.2625 - rmse: 0.3373 - smape: 0.6220 - val_ia: 0.3237 - val_loss: 0.1844 - val_mae: 0.3462 - val_rmse: 0.3823 - val_smape: 0.7655

Epoch 38/128

2292/2292 - 39s - 17ms/step - ia: 0.8270 - loss: 0.1176 - mae: 0.2590 - rmse: 0.3337 - smape: 0.6231 - val_ia: 0.3486 - val_loss: 0.1690 - val_mae: 0.3311 - val_rmse: 0.3632 - val_smape: 0.7292

Epoch 39/128

2292/2292 - 31s - 13ms/step - ia: 0.8274 - loss: 0.1167 - mae: 0.2582 - rmse: 0.3318 - smape: 0.6213 - val_ia: 0.3386 - val_loss: 0.1750 - val_mae: 0.3365 - val_rmse: 0.3702 - val_smape: 0.7522

Epoch 40/128

2292/2292 - 39s - 17ms/step - ia: 0.8279 - loss: 0.1159 - mae: 0.2576 - rmse: 0.3308 - smape: 0.6200 - val_ia: 0.3222 - val_loss: 0.2267 - val_mae: 0.3690 - val_rmse: 0.4084 - val_smape: 0.7593

Epoch 41/128

2292/2292 - 28s - 12ms/step - ia: 0.8304 - loss: 0.1137 - mae: 0.2545 - rmse: 0.3277 - smape: 0.6161 - val_ia: 0.3605 - val_loss: 0.1526 - val_mae: 0.3145 - val_rmse: 0.3450 - val_smape: 0.7003

Epoch 42/128

2292/2292 - 42s - 18ms/step - ia: 0.8300 - loss: 0.1138 - mae: 0.2545 - rmse: 0.3282 - smape: 0.6138 - val_ia: 0.3553 - val_loss: 0.1555 - val_mae: 0.3190 - val_rmse: 0.3498 - val_smape: 0.7197

Epoch 43/128

2292/2292 - 29s - 12ms/step - ia: 0.8315 - loss: 0.1121 - mae: 0.2529 - rmse: 0.3254 - smape: 0.6109 - val_ia: 0.3332 - val_loss: 0.1875 - val_mae: 0.3460 - val_rmse: 0.3794 - val_smape: 0.7500

Epoch 44/128

2292/2292 - 45s - 20ms/step - ia: 0.8323 - loss: 0.1111 - mae: 0.2515 - rmse: 0.3242 - smape: 0.6120 - val_ia: 0.3261 - val_loss: 0.2306 - val_mae: 0.3704 - val_rmse: 0.4126 - val_smape: 0.7492

Epoch 45/128

2292/2292 - 30s - 13ms/step - ia: 0.8331 - loss: 0.1105 - mae: 0.2506 - rmse: 0.3231 - smape: 0.6082 - val_ia: 0.3348 - val_loss: 0.1898 - val_mae: 0.3458 - val_rmse: 0.3812 - val_smape: 0.7449

Epoch 46/128

2292/2292 - 28s - 12ms/step - ia: 0.8347 - loss: 0.1091 - mae: 0.2484 - rmse: 0.3206 - smape: 0.6036 - val_ia: 0.3408 - val_loss: 0.1788 - val_mae: 0.3368 - val_rmse: 0.3719 - val_smape: 0.7339

Epoch 47/128

2292/2292 - 29s - 13ms/step - ia: 0.8349 - loss: 0.1089 - mae: 0.2478 - rmse: 0.3207 - smape: 0.6027 - val_ia: 0.3362 - val_loss: 0.1996 - val_mae: 0.3492 - val_rmse: 0.3854 - val_smape: 0.7435

Epoch 48/128

2292/2292 - 29s - 12ms/step - ia: 0.8351 - loss: 0.1084 - mae: 0.2476 - rmse: 0.3199 - smape: 0.6035 - val_ia: 0.3339 - val_loss: 0.1999 - val_mae: 0.3516 - val_rmse: 0.3874 - val_smape: 0.7447

Epoch 49/128

2292/2292 - 41s - 18ms/step - ia: 0.8349 - loss: 0.1083 - mae: 0.2476 - rmse: 0.3196 - smape: 0.6017 - val_ia: 0.3470 - val_loss: 0.1893 - val_mae: 0.3426 - val_rmse: 0.3755 - val_smape: 0.7257

Epoch 50/128

2292/2292 - 27s - 12ms/step - ia: 0.8370 - loss: 0.1066 - mae: 0.2445 - rmse: 0.3173 - smape: 0.5963 - val_ia: 0.3575 - val_loss: 0.1534 - val_mae: 0.3152 - val_rmse: 0.3470 - val_smape: 0.7078

Epoch 51/128

2292/2292 - 27s - 12ms/step - ia: 0.8358 - loss: 0.1067 - mae: 0.2457 - rmse: 0.3174 - smape: 0.5971 - val_ia: 0.3586 - val_loss: 0.1544 - val_mae: 0.3137 - val_rmse: 0.3461 - val_smape: 0.7056

Epoch 52/128

2292/2292 - 29s - 13ms/step - ia: 0.8378 - loss: 0.1057 - mae: 0.2439 - rmse: 0.3156 - smape: 0.5931 - val_ia: 0.3483 - val_loss: 0.1865 - val_mae: 0.3370 - val_rmse: 0.3724 - val_smape: 0.7309

Epoch 53/128

2292/2292 - 40s - 17ms/step - ia: 0.8373 - loss: 0.1054 - mae: 0.2442 - rmse: 0.3152 - smape: 0.5934 - val_ia: 0.3482 - val_loss: 0.1762 - val_mae: 0.3336 - val_rmse: 0.3681 - val_smape: 0.7201

Epoch 54/128

2292/2292 - 25s - 11ms/step - ia: 0.8377 - loss: 0.1047 - mae: 0.2432 - rmse: 0.3142 - smape: 0.5919 - val_ia: 0.3501 - val_loss: 0.1724 - val_mae: 0.3278 - val_rmse: 0.3633 - val_smape: 0.7129

Epoch 55/128

2292/2292 - 44s - 19ms/step - ia: 0.8384 - loss: 0.1043 - mae: 0.2423 - rmse: 0.3137 - smape: 0.5897 - val_ia: 0.3593 - val_loss: 0.1709 - val_mae: 0.3298 - val_rmse: 0.3593 - val_smape: 0.7129

Epoch 56/128

2292/2292 - 29s - 13ms/step - ia: 0.8393 - loss: 0.1039 - mae: 0.2411 - rmse: 0.3133 - smape: 0.5864 - val_ia: 0.3496 - val_loss: 0.1727 - val_mae: 0.3284 - val_rmse: 0.3660 - val_smape: 0.7092

Epoch 56: early stopping

Restoring model weights from the end of the best epoch: 41.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:47 1s/step
  6/163 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 28/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 44/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 52/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 60/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 68/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 76/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 84/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
114/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
122/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
141/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step

 83%|████████▎ | 10/12 [2:04:03<29:35, 887.98s/trial, best loss: 0.15488481435603096]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 36s - 8ms/step - ia: 0.2444 - loss: 1.5229 - mae: 0.9487 - rmse: 1.1765 - smape: 1.6040 - val_ia: 0.1475 - val_loss: 0.8240 - val_mae: 0.7306 - val_rmse: 0.7470 - val_smape: 1.5078

Epoch 2/128

4584/4584 - 28s - 6ms/step - ia: 0.2439 - loss: 1.4007 - mae: 0.9249 - rmse: 1.1376 - smape: 1.6173 - val_ia: 0.1465 - val_loss: 0.8164 - val_mae: 0.7298 - val_rmse: 0.7460 - val_smape: 1.5342

Epoch 3/128

4584/4584 - 29s - 6ms/step - ia: 0.2400 - loss: 1.3205 - mae: 0.9070 - rmse: 1.1091 - smape: 1.6279 - val_ia: 0.1460 - val_loss: 0.8112 - val_mae: 0.7301 - val_rmse: 0.7461 - val_smape: 1.5613

Epoch 4/128

4584/4584 - 26s - 6ms/step - ia: 0.2406 - loss: 1.2587 - mae: 0.8939 - rmse: 1.0866 - smape: 1.6385 - val_ia: 0.1456 - val_loss: 0.8079 - val_mae: 0.7314 - val_rmse: 0.7473 - val_smape: 1.5895

Epoch 5/128

4584/4584 - 29s - 6ms/step - ia: 0.2399 - loss: 1.1982 - mae: 0.8781 - rmse: 1.0622 - smape: 1.6454 - val_ia: 0.1452 - val_loss: 0.8060 - val_mae: 0.7331 - val_rmse: 0.7491 - val_smape: 1.6171

Epoch 6/128

4584/4584 - 37s - 8ms/step - ia: 0.2392 - loss: 1.1514 - mae: 0.8659 - rmse: 1.0435 - smape: 1.6551 - val_ia: 0.1443 - val_loss: 0.8052 - val_mae: 0.7350 - val_rmse: 0.7510 - val_smape: 1.6432

Epoch 7/128

4584/4584 - 27s - 6ms/step - ia: 0.2376 - loss: 1.1190 - mae: 0.8566 - rmse: 1.0303 - smape: 1.6605 - val_ia: 0.1433 - val_loss: 0.8047 - val_mae: 0.7367 - val_rmse: 0.7528 - val_smape: 1.6674

Epoch 8/128

4584/4584 - 27s - 6ms/step - ia: 0.2372 - loss: 1.0871 - mae: 0.8473 - rmse: 1.0164 - smape: 1.6663 - val_ia: 0.1428 - val_loss: 0.8045 - val_mae: 0.7383 - val_rmse: 0.7544 - val_smape: 1.6900

Epoch 9/128

4584/4584 - 25s - 5ms/step - ia: 0.2364 - loss: 1.0654 - mae: 0.8405 - rmse: 1.0068 - smape: 1.6707 - val_ia: 0.1424 - val_loss: 0.8044 - val_mae: 0.7397 - val_rmse: 0.7558 - val_smape: 1.7099

Epoch 10/128

4584/4584 - 26s - 6ms/step - ia: 0.2365 - loss: 1.0420 - mae: 0.8328 - rmse: 0.9965 - smape: 1.6692 - val_ia: 0.1421 - val_loss: 0.8042 - val_mae: 0.7407 - val_rmse: 0.7569 - val_smape: 1.7267

Epoch 11/128

4584/4584 - 26s - 6ms/step - ia: 0.2384 - loss: 1.0265 - mae: 0.8274 - rmse: 0.9895 - smape: 1.6712 - val_ia: 0.1416 - val_loss: 0.8035 - val_mae: 0.7414 - val_rmse: 0.7576 - val_smape: 1.7414

Epoch 12/128

4584/4584 - 28s - 6ms/step - ia: 0.2411 - loss: 1.0084 - mae: 0.8212 - rmse: 0.9804 - smape: 1.6710 - val_ia: 0.1415 - val_loss: 0.8025 - val_mae: 0.7416 - val_rmse: 0.7578 - val_smape: 1.7521

Epoch 13/128

4584/4584 - 26s - 6ms/step - ia: 0.2425 - loss: 0.9916 - mae: 0.8148 - rmse: 0.9733 - smape: 1.6650 - val_ia: 0.1414 - val_loss: 0.8010 - val_mae: 0.7415 - val_rmse: 0.7578 - val_smape: 1.7598

Epoch 14/128

4584/4584 - 27s - 6ms/step - ia: 0.2468 - loss: 0.9793 - mae: 0.8102 - rmse: 0.9665 - smape: 1.6622 - val_ia: 0.1415 - val_loss: 0.7989 - val_mae: 0.7410 - val_rmse: 0.7573 - val_smape: 1.7637

Epoch 15/128

4584/4584 - 40s - 9ms/step - ia: 0.2518 - loss: 0.9636 - mae: 0.8037 - rmse: 0.9588 - smape: 1.6502 - val_ia: 0.1417 - val_loss: 0.7963 - val_mae: 0.7401 - val_rmse: 0.7565 - val_smape: 1.7653

Epoch 16/128

4584/4584 - 26s - 6ms/step - ia: 0.2552 - loss: 0.9512 - mae: 0.7987 - rmse: 0.9535 - smape: 1.6430 - val_ia: 0.1418 - val_loss: 0.7936 - val_mae: 0.7392 - val_rmse: 0.7556 - val_smape: 1.7662

Epoch 17/128

4584/4584 - 42s - 9ms/step - ia: 0.2591 - loss: 0.9411 - mae: 0.7949 - rmse: 0.9478 - smape: 1.6378 - val_ia: 0.1419 - val_loss: 0.7905 - val_mae: 0.7380 - val_rmse: 0.7544 - val_smape: 1.7632

Epoch 18/128

4584/4584 - 29s - 6ms/step - ia: 0.2656 - loss: 0.9315 - mae: 0.7905 - rmse: 0.9427 - smape: 1.6310 - val_ia: 0.1420 - val_loss: 0.7876 - val_mae: 0.7369 - val_rmse: 0.7534 - val_smape: 1.7594

Epoch 19/128

4584/4584 - 29s - 6ms/step - ia: 0.2685 - loss: 0.9192 - mae: 0.7858 - rmse: 0.9372 - smape: 1.6222 - val_ia: 0.1421 - val_loss: 0.7845 - val_mae: 0.7357 - val_rmse: 0.7521 - val_smape: 1.7545

Epoch 20/128

4584/4584 - 25s - 5ms/step - ia: 0.2739 - loss: 0.9106 - mae: 0.7813 - rmse: 0.9318 - smape: 1.6125 - val_ia: 0.1421 - val_loss: 0.7813 - val_mae: 0.7343 - val_rmse: 0.7508 - val_smape: 1.7486

Epoch 21/128

4584/4584 - 26s - 6ms/step - ia: 0.2778 - loss: 0.9042 - mae: 0.7787 - rmse: 0.9292 - smape: 1.6098 - val_ia: 0.1422 - val_loss: 0.7780 - val_mae: 0.7329 - val_rmse: 0.7494 - val_smape: 1.7414

Epoch 22/128

4584/4584 - 26s - 6ms/step - ia: 0.2830 - loss: 0.8967 - mae: 0.7754 - rmse: 0.9249 - smape: 1.5992 - val_ia: 0.1423 - val_loss: 0.7749 - val_mae: 0.7315 - val_rmse: 0.7480 - val_smape: 1.7350

Epoch 23/128

4584/4584 - 26s - 6ms/step - ia: 0.2864 - loss: 0.8863 - mae: 0.7709 - rmse: 0.9195 - smape: 1.5906 - val_ia: 0.1425 - val_loss: 0.7714 - val_mae: 0.7300 - val_rmse: 0.7464 - val_smape: 1.7275

Epoch 24/128

4584/4584 - 28s - 6ms/step - ia: 0.2908 - loss: 0.8788 - mae: 0.7670 - rmse: 0.9153 - smape: 1.5783 - val_ia: 0.1427 - val_loss: 0.7674 - val_mae: 0.7281 - val_rmse: 0.7445 - val_smape: 1.7182

Epoch 25/128

4584/4584 - 47s - 10ms/step - ia: 0.2958 - loss: 0.8686 - mae: 0.7623 - rmse: 0.9097 - smape: 1.5692 - val_ia: 0.1430 - val_loss: 0.7630 - val_mae: 0.7260 - val_rmse: 0.7425 - val_smape: 1.7081

Epoch 26/128

4584/4584 - 34s - 7ms/step - ia: 0.3045 - loss: 0.8594 - mae: 0.7574 - rmse: 0.9053 - smape: 1.5583 - val_ia: 0.1432 - val_loss: 0.7585 - val_mae: 0.7239 - val_rmse: 0.7403 - val_smape: 1.6978

Epoch 27/128

4584/4584 - 33s - 7ms/step - ia: 0.3073 - loss: 0.8598 - mae: 0.7557 - rmse: 0.9039 - smape: 1.5498 - val_ia: 0.1435 - val_loss: 0.7547 - val_mae: 0.7221 - val_rmse: 0.7385 - val_smape: 1.6894

Epoch 28/128

4584/4584 - 34s - 7ms/step - ia: 0.3135 - loss: 0.8463 - mae: 0.7504 - rmse: 0.8977 - smape: 1.5374 - val_ia: 0.1439 - val_loss: 0.7506 - val_mae: 0.7201 - val_rmse: 0.7365 - val_smape: 1.6805

Epoch 29/128

4584/4584 - 35s - 8ms/step - ia: 0.3205 - loss: 0.8358 - mae: 0.7446 - rmse: 0.8917 - smape: 1.5241 - val_ia: 0.1443 - val_loss: 0.7456 - val_mae: 0.7177 - val_rmse: 0.7340 - val_smape: 1.6700

Epoch 30/128

4584/4584 - 32s - 7ms/step - ia: 0.3261 - loss: 0.8319 - mae: 0.7405 - rmse: 0.8880 - smape: 1.5109 - val_ia: 0.1446 - val_loss: 0.7413 - val_mae: 0.7157 - val_rmse: 0.7319 - val_smape: 1.6617

Epoch 31/128

4584/4584 - 31s - 7ms/step - ia: 0.3337 - loss: 0.8193 - mae: 0.7354 - rmse: 0.8820 - smape: 1.4996 - val_ia: 0.1450 - val_loss: 0.7366 - val_mae: 0.7134 - val_rmse: 0.7296 - val_smape: 1.6524

Epoch 32/128

4584/4584 - 33s - 7ms/step - ia: 0.3398 - loss: 0.8129 - mae: 0.7311 - rmse: 0.8786 - smape: 1.4864 - val_ia: 0.1453 - val_loss: 0.7325 - val_mae: 0.7114 - val_rmse: 0.7276 - val_smape: 1.6445

Epoch 33/128

4584/4584 - 34s - 7ms/step - ia: 0.3457 - loss: 0.8021 - mae: 0.7259 - rmse: 0.8730 - smape: 1.4772 - val_ia: 0.1456 - val_loss: 0.7280 - val_mae: 0.7093 - val_rmse: 0.7254 - val_smape: 1.6357

Epoch 34/128

4584/4584 - 33s - 7ms/step - ia: 0.3529 - loss: 0.8001 - mae: 0.7219 - rmse: 0.8708 - smape: 1.4622 - val_ia: 0.1459 - val_loss: 0.7244 - val_mae: 0.7075 - val_rmse: 0.7236 - val_smape: 1.6286

Epoch 35/128

4584/4584 - 39s - 9ms/step - ia: 0.3578 - loss: 0.7861 - mae: 0.7161 - rmse: 0.8636 - smape: 1.4500 - val_ia: 0.1461 - val_loss: 0.7208 - val_mae: 0.7058 - val_rmse: 0.7219 - val_smape: 1.6207

Epoch 36/128

4584/4584 - 33s - 7ms/step - ia: 0.3644 - loss: 0.7844 - mae: 0.7142 - rmse: 0.8626 - smape: 1.4401 - val_ia: 0.1462 - val_loss: 0.7194 - val_mae: 0.7053 - val_rmse: 0.7213 - val_smape: 1.6170

Epoch 37/128

4584/4584 - 42s - 9ms/step - ia: 0.3683 - loss: 0.7759 - mae: 0.7100 - rmse: 0.8574 - smape: 1.4324 - val_ia: 0.1466 - val_loss: 0.7169 - val_mae: 0.7041 - val_rmse: 0.7202 - val_smape: 1.6112

Epoch 38/128

4584/4584 - 32s - 7ms/step - ia: 0.3720 - loss: 0.7696 - mae: 0.7057 - rmse: 0.8532 - smape: 1.4215 - val_ia: 0.1468 - val_loss: 0.7152 - val_mae: 0.7034 - val_rmse: 0.7195 - val_smape: 1.6061

Epoch 39/128

4584/4584 - 32s - 7ms/step - ia: 0.3730 - loss: 0.7710 - mae: 0.7053 - rmse: 0.8537 - smape: 1.4170 - val_ia: 0.1470 - val_loss: 0.7143 - val_mae: 0.7031 - val_rmse: 0.7192 - val_smape: 1.6021

Epoch 40/128

4584/4584 - 30s - 7ms/step - ia: 0.3776 - loss: 0.7598 - mae: 0.7020 - rmse: 0.8486 - smape: 1.4081 - val_ia: 0.1473 - val_loss: 0.7134 - val_mae: 0.7028 - val_rmse: 0.7188 - val_smape: 1.5976

Epoch 41/128

4584/4584 - 30s - 7ms/step - ia: 0.3838 - loss: 0.7500 - mae: 0.6961 - rmse: 0.8423 - smape: 1.3961 - val_ia: 0.1477 - val_loss: 0.7125 - val_mae: 0.7024 - val_rmse: 0.7185 - val_smape: 1.5929

Epoch 42/128

4584/4584 - 37s - 8ms/step - ia: 0.3836 - loss: 0.7517 - mae: 0.6967 - rmse: 0.8432 - smape: 1.3923 - val_ia: 0.1480 - val_loss: 0.7124 - val_mae: 0.7026 - val_rmse: 0.7186 - val_smape: 1.5889

Epoch 43/128

4584/4584 - 25s - 6ms/step - ia: 0.3877 - loss: 0.7459 - mae: 0.6928 - rmse: 0.8395 - smape: 1.3830 - val_ia: 0.1482 - val_loss: 0.7120 - val_mae: 0.7025 - val_rmse: 0.7185 - val_smape: 1.5837

Epoch 44/128

4584/4584 - 43s - 9ms/step - ia: 0.3896 - loss: 0.7391 - mae: 0.6910 - rmse: 0.8363 - smape: 1.3757 - val_ia: 0.1484 - val_loss: 0.7113 - val_mae: 0.7023 - val_rmse: 0.7183 - val_smape: 1.5778

Epoch 45/128

4584/4584 - 42s - 9ms/step - ia: 0.3931 - loss: 0.7335 - mae: 0.6879 - rmse: 0.8339 - smape: 1.3663 - val_ia: 0.1485 - val_loss: 0.7115 - val_mae: 0.7025 - val_rmse: 0.7185 - val_smape: 1.5729

Epoch 46/128

4584/4584 - 27s - 6ms/step - ia: 0.3941 - loss: 0.7337 - mae: 0.6890 - rmse: 0.8334 - smape: 1.3670 - val_ia: 0.1485 - val_loss: 0.7117 - val_mae: 0.7028 - val_rmse: 0.7188 - val_smape: 1.5680

Epoch 47/128

4584/4584 - 27s - 6ms/step - ia: 0.3991 - loss: 0.7246 - mae: 0.6832 - rmse: 0.8282 - smape: 1.3508 - val_ia: 0.1487 - val_loss: 0.7117 - val_mae: 0.7029 - val_rmse: 0.7189 - val_smape: 1.5627

Epoch 48/128

4584/4584 - 25s - 6ms/step - ia: 0.3987 - loss: 0.7212 - mae: 0.6825 - rmse: 0.8260 - smape: 1.3489 - val_ia: 0.1489 - val_loss: 0.7113 - val_mae: 0.7028 - val_rmse: 0.7188 - val_smape: 1.5571

Epoch 49/128

4584/4584 - 27s - 6ms/step - ia: 0.4025 - loss: 0.7178 - mae: 0.6797 - rmse: 0.8236 - smape: 1.3383 - val_ia: 0.1490 - val_loss: 0.7113 - val_mae: 0.7030 - val_rmse: 0.7190 - val_smape: 1.5520

Epoch 50/128

4584/4584 - 27s - 6ms/step - ia: 0.4054 - loss: 0.7149 - mae: 0.6783 - rmse: 0.8228 - smape: 1.3332 - val_ia: 0.1489 - val_loss: 0.7121 - val_mae: 0.7035 - val_rmse: 0.7195 - val_smape: 1.5478

Epoch 51/128

4584/4584 - 28s - 6ms/step - ia: 0.4093 - loss: 0.7106 - mae: 0.6753 - rmse: 0.8186 - smape: 1.3264 - val_ia: 0.1487 - val_loss: 0.7124 - val_mae: 0.7037 - val_rmse: 0.7197 - val_smape: 1.5430

Epoch 52/128

4584/4584 - 27s - 6ms/step - ia: 0.4089 - loss: 0.7084 - mae: 0.6746 - rmse: 0.8181 - smape: 1.3207 - val_ia: 0.1489 - val_loss: 0.7123 - val_mae: 0.7038 - val_rmse: 0.7197 - val_smape: 1.5377

Epoch 53/128

4584/4584 - 27s - 6ms/step - ia: 0.4128 - loss: 0.6994 - mae: 0.6706 - rmse: 0.8122 - smape: 1.3098 - val_ia: 0.1489 - val_loss: 0.7125 - val_mae: 0.7040 - val_rmse: 0.7200 - val_smape: 1.5323

Epoch 54/128

4584/4584 - 26s - 6ms/step - ia: 0.4142 - loss: 0.6993 - mae: 0.6695 - rmse: 0.8134 - smape: 1.3058 - val_ia: 0.1487 - val_loss: 0.7129 - val_mae: 0.7043 - val_rmse: 0.7203 - val_smape: 1.5271

Epoch 55/128

4584/4584 - 27s - 6ms/step - ia: 0.4180 - loss: 0.6893 - mae: 0.6652 - rmse: 0.8071 - smape: 1.2956 - val_ia: 0.1484 - val_loss: 0.7125 - val_mae: 0.7042 - val_rmse: 0.7202 - val_smape: 1.5220

Epoch 56/128

4584/4584 - 27s - 6ms/step - ia: 0.4181 - loss: 0.6894 - mae: 0.6649 - rmse: 0.8068 - smape: 1.2903 - val_ia: 0.1482 - val_loss: 0.7125 - val_mae: 0.7043 - val_rmse: 0.7202 - val_smape: 1.5170

Epoch 57/128

4584/4584 - 40s - 9ms/step - ia: 0.4199 - loss: 0.6877 - mae: 0.6632 - rmse: 0.8049 - smape: 1.2852 - val_ia: 0.1481 - val_loss: 0.7128 - val_mae: 0.7045 - val_rmse: 0.7204 - val_smape: 1.5124

Epoch 58/128

4584/4584 - 24s - 5ms/step - ia: 0.4211 - loss: 0.6833 - mae: 0.6625 - rmse: 0.8032 - smape: 1.2809 - val_ia: 0.1482 - val_loss: 0.7131 - val_mae: 0.7047 - val_rmse: 0.7206 - val_smape: 1.5076

Epoch 59/128

4584/4584 - 26s - 6ms/step - ia: 0.4272 - loss: 0.6779 - mae: 0.6591 - rmse: 0.7993 - smape: 1.2721 - val_ia: 0.1484 - val_loss: 0.7139 - val_mae: 0.7052 - val_rmse: 0.7211 - val_smape: 1.5030

Epoch 60/128

4584/4584 - 27s - 6ms/step - ia: 0.4294 - loss: 0.6733 - mae: 0.6568 - rmse: 0.7975 - smape: 1.2642 - val_ia: 0.1486 - val_loss: 0.7149 - val_mae: 0.7058 - val_rmse: 0.7217 - val_smape: 1.4984

Epoch 61/128

4584/4584 - 42s - 9ms/step - ia: 0.4285 - loss: 0.6781 - mae: 0.6589 - rmse: 0.7991 - smape: 1.2627 - val_ia: 0.1490 - val_loss: 0.7152 - val_mae: 0.7059 - val_rmse: 0.7218 - val_smape: 1.4933

Epoch 62/128

4584/4584 - 26s - 6ms/step - ia: 0.4329 - loss: 0.6660 - mae: 0.6536 - rmse: 0.7928 - smape: 1.2511 - val_ia: 0.1492 - val_loss: 0.7155 - val_mae: 0.7061 - val_rmse: 0.7219 - val_smape: 1.4878

Epoch 63/128

4584/4584 - 26s - 6ms/step - ia: 0.4339 - loss: 0.6633 - mae: 0.6527 - rmse: 0.7913 - smape: 1.2509 - val_ia: 0.1492 - val_loss: 0.7154 - val_mae: 0.7061 - val_rmse: 0.7219 - val_smape: 1.4826

Epoch 63: early stopping

Restoring model weights from the end of the best epoch: 48.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 2:20 866ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 31/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
127/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
142/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

 92%|█████████▏| 11/12 [2:36:21<20:09, 1209.32s/trial, best loss: 0.15488481435603096]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 10s - 34ms/step - ia: 0.3594 - loss: 0.8128 - mae: 0.7490 - rmse: 0.8982 - smape: 1.3576 - val_ia: 0.4173 - val_loss: 1.0892 - val_mae: 0.8492 - val_rmse: 1.0206 - val_smape: 1.3101

Epoch 2/128

287/287 - 10s - 34ms/step - ia: 0.5502 - loss: 0.5871 - mae: 0.6191 - rmse: 0.7647 - smape: 1.0801 - val_ia: 0.4122 - val_loss: 1.4557 - val_mae: 0.9989 - val_rmse: 1.1724 - val_smape: 1.3531

Epoch 3/128

287/287 - 10s - 36ms/step - ia: 0.6107 - loss: 0.4892 - mae: 0.5600 - rmse: 0.6978 - smape: 0.9779 - val_ia: 0.4247 - val_loss: 1.4142 - val_mae: 0.9831 - val_rmse: 1.1502 - val_smape: 1.3236

Epoch 4/128

287/287 - 4s - 15ms/step - ia: 0.6518 - loss: 0.4219 - mae: 0.5179 - rmse: 0.6483 - smape: 0.9035 - val_ia: 0.4567 - val_loss: 1.1778 - val_mae: 0.8955 - val_rmse: 1.0411 - val_smape: 1.2647

Epoch 5/128

287/287 - 5s - 18ms/step - ia: 0.6803 - loss: 0.3744 - mae: 0.4862 - rmse: 0.6105 - smape: 0.8501 - val_ia: 0.4887 - val_loss: 1.0197 - val_mae: 0.8245 - val_rmse: 0.9639 - val_smape: 1.2101

Epoch 6/128

287/287 - 5s - 19ms/step - ia: 0.6943 - loss: 0.3493 - mae: 0.4701 - rmse: 0.5898 - smape: 0.8252 - val_ia: 0.5185 - val_loss: 0.8458 - val_mae: 0.7431 - val_rmse: 0.8772 - val_smape: 1.1651

Epoch 7/128

287/287 - 5s - 19ms/step - ia: 0.7049 - loss: 0.3300 - mae: 0.4565 - rmse: 0.5733 - smape: 0.8064 - val_ia: 0.5265 - val_loss: 0.8066 - val_mae: 0.7246 - val_rmse: 0.8561 - val_smape: 1.1545

Epoch 8/128

287/287 - 10s - 33ms/step - ia: 0.7146 - loss: 0.3119 - mae: 0.4431 - rmse: 0.5569 - smape: 0.7901 - val_ia: 0.5365 - val_loss: 0.7733 - val_mae: 0.7084 - val_rmse: 0.8372 - val_smape: 1.1394

Epoch 9/128

287/287 - 5s - 16ms/step - ia: 0.7204 - loss: 0.3028 - mae: 0.4356 - rmse: 0.5493 - smape: 0.7778 - val_ia: 0.5665 - val_loss: 0.6382 - val_mae: 0.6473 - val_rmse: 0.7602 - val_smape: 1.0828

Epoch 10/128

287/287 - 4s - 15ms/step - ia: 0.7270 - loss: 0.2912 - mae: 0.4266 - rmse: 0.5384 - smape: 0.7693 - val_ia: 0.5603 - val_loss: 0.6564 - val_mae: 0.6548 - val_rmse: 0.7674 - val_smape: 1.0970

Epoch 11/128

287/287 - 4s - 14ms/step - ia: 0.7315 - loss: 0.2836 - mae: 0.4200 - rmse: 0.5315 - smape: 0.7629 - val_ia: 0.5689 - val_loss: 0.6407 - val_mae: 0.6469 - val_rmse: 0.7578 - val_smape: 1.0813

Epoch 12/128

287/287 - 6s - 21ms/step - ia: 0.7358 - loss: 0.2766 - mae: 0.4137 - rmse: 0.5247 - smape: 0.7546 - val_ia: 0.5888 - val_loss: 0.5630 - val_mae: 0.6077 - val_rmse: 0.7110 - val_smape: 1.0383

Epoch 13/128

287/287 - 11s - 38ms/step - ia: 0.7402 - loss: 0.2686 - mae: 0.4068 - rmse: 0.5169 - smape: 0.7506 - val_ia: 0.6035 - val_loss: 0.5174 - val_mae: 0.5837 - val_rmse: 0.6843 - val_smape: 1.0080

Epoch 14/128

287/287 - 8s - 29ms/step - ia: 0.7458 - loss: 0.2595 - mae: 0.3990 - rmse: 0.5082 - smape: 0.7451 - val_ia: 0.6004 - val_loss: 0.5500 - val_mae: 0.6000 - val_rmse: 0.6996 - val_smape: 1.0128

Epoch 15/128

287/287 - 6s - 23ms/step - ia: 0.7505 - loss: 0.2513 - mae: 0.3917 - rmse: 0.5002 - smape: 0.7407 - val_ia: 0.6240 - val_loss: 0.4863 - val_mae: 0.5640 - val_rmse: 0.6605 - val_smape: 0.9653

Epoch 16/128

287/287 - 7s - 24ms/step - ia: 0.7576 - loss: 0.2395 - mae: 0.3804 - rmse: 0.4880 - smape: 0.7320 - val_ia: 0.6339 - val_loss: 0.4745 - val_mae: 0.5546 - val_rmse: 0.6555 - val_smape: 0.9477

Epoch 17/128

287/287 - 7s - 23ms/step - ia: 0.7670 - loss: 0.2244 - mae: 0.3662 - rmse: 0.4722 - smape: 0.7211 - val_ia: 0.6596 - val_loss: 0.4076 - val_mae: 0.5177 - val_rmse: 0.6056 - val_smape: 0.9100

Epoch 18/128

287/287 - 6s - 21ms/step - ia: 0.7766 - loss: 0.2097 - mae: 0.3509 - rmse: 0.4567 - smape: 0.7119 - val_ia: 0.6787 - val_loss: 0.3486 - val_mae: 0.4837 - val_rmse: 0.5672 - val_smape: 0.8835

Epoch 19/128

287/287 - 11s - 38ms/step - ia: 0.7856 - loss: 0.1947 - mae: 0.3362 - rmse: 0.4400 - smape: 0.7038 - val_ia: 0.6794 - val_loss: 0.3642 - val_mae: 0.4894 - val_rmse: 0.5776 - val_smape: 0.8810

Epoch 20/128

287/287 - 7s - 24ms/step - ia: 0.7946 - loss: 0.1806 - mae: 0.3223 - rmse: 0.4236 - smape: 0.6903 - val_ia: 0.7013 - val_loss: 0.3003 - val_mae: 0.4490 - val_rmse: 0.5291 - val_smape: 0.8542

Epoch 21/128

287/287 - 6s - 22ms/step - ia: 0.8020 - loss: 0.1693 - mae: 0.3106 - rmse: 0.4100 - smape: 0.6762 - val_ia: 0.7215 - val_loss: 0.2319 - val_mae: 0.4013 - val_rmse: 0.4703 - val_smape: 0.8409

Epoch 22/128

287/287 - 11s - 38ms/step - ia: 0.8078 - loss: 0.1599 - mae: 0.3013 - rmse: 0.3982 - smape: 0.6692 - val_ia: 0.7166 - val_loss: 0.2800 - val_mae: 0.4248 - val_rmse: 0.4983 - val_smape: 0.8154

Epoch 23/128

287/287 - 7s - 23ms/step - ia: 0.8124 - loss: 0.1528 - mae: 0.2937 - rmse: 0.3893 - smape: 0.6570 - val_ia: 0.7380 - val_loss: 0.2161 - val_mae: 0.3829 - val_rmse: 0.4505 - val_smape: 0.8088

Epoch 24/128

287/287 - 6s - 22ms/step - ia: 0.8195 - loss: 0.1424 - mae: 0.2832 - rmse: 0.3759 - smape: 0.6444 - val_ia: 0.7208 - val_loss: 0.2661 - val_mae: 0.4130 - val_rmse: 0.4968 - val_smape: 0.8105

Epoch 25/128

287/287 - 6s - 22ms/step - ia: 0.8231 - loss: 0.1370 - mae: 0.2777 - rmse: 0.3686 - smape: 0.6375 - val_ia: 0.7318 - val_loss: 0.2434 - val_mae: 0.3960 - val_rmse: 0.4726 - val_smape: 0.7865

Epoch 26/128

287/287 - 11s - 37ms/step - ia: 0.8271 - loss: 0.1308 - mae: 0.2720 - rmse: 0.3604 - smape: 0.6275 - val_ia: 0.7509 - val_loss: 0.1971 - val_mae: 0.3586 - val_rmse: 0.4285 - val_smape: 0.7768

Epoch 27/128

287/287 - 7s - 23ms/step - ia: 0.8315 - loss: 0.1261 - mae: 0.2656 - rmse: 0.3536 - smape: 0.6177 - val_ia: 0.7453 - val_loss: 0.2089 - val_mae: 0.3666 - val_rmse: 0.4414 - val_smape: 0.7739

Epoch 28/128

287/287 - 7s - 25ms/step - ia: 0.8323 - loss: 0.1238 - mae: 0.2638 - rmse: 0.3503 - smape: 0.6171 - val_ia: 0.7472 - val_loss: 0.1901 - val_mae: 0.3590 - val_rmse: 0.4284 - val_smape: 0.8084

Epoch 29/128

287/287 - 4s - 13ms/step - ia: 0.8360 - loss: 0.1201 - mae: 0.2591 - rmse: 0.3451 - smape: 0.6075 - val_ia: 0.7604 - val_loss: 0.1815 - val_mae: 0.3434 - val_rmse: 0.4123 - val_smape: 0.7499

Epoch 30/128

287/287 - 4s - 12ms/step - ia: 0.8370 - loss: 0.1187 - mae: 0.2573 - rmse: 0.3429 - smape: 0.6056 - val_ia: 0.7644 - val_loss: 0.1688 - val_mae: 0.3342 - val_rmse: 0.4018 - val_smape: 0.7493

Epoch 31/128

287/287 - 4s - 12ms/step - ia: 0.8390 - loss: 0.1157 - mae: 0.2543 - rmse: 0.3388 - smape: 0.5998 - val_ia: 0.7491 - val_loss: 0.2172 - val_mae: 0.3697 - val_rmse: 0.4533 - val_smape: 0.7578

Epoch 32/128

287/287 - 6s - 19ms/step - ia: 0.8396 - loss: 0.1154 - mae: 0.2531 - rmse: 0.3384 - smape: 0.5982 - val_ia: 0.7673 - val_loss: 0.1788 - val_mae: 0.3387 - val_rmse: 0.4104 - val_smape: 0.7303

Epoch 33/128

287/287 - 7s - 24ms/step - ia: 0.8414 - loss: 0.1139 - mae: 0.2511 - rmse: 0.3361 - smape: 0.5936 - val_ia: 0.7706 - val_loss: 0.1700 - val_mae: 0.3319 - val_rmse: 0.4006 - val_smape: 0.7263

Epoch 34/128

287/287 - 10s - 35ms/step - ia: 0.8427 - loss: 0.1123 - mae: 0.2492 - rmse: 0.3337 - smape: 0.5898 - val_ia: 0.7593 - val_loss: 0.2002 - val_mae: 0.3559 - val_rmse: 0.4334 - val_smape: 0.7429

Epoch 35/128

287/287 - 5s - 16ms/step - ia: 0.8430 - loss: 0.1111 - mae: 0.2482 - rmse: 0.3320 - smape: 0.5919 - val_ia: 0.7693 - val_loss: 0.1669 - val_mae: 0.3294 - val_rmse: 0.3998 - val_smape: 0.7259

Epoch 36/128

287/287 - 4s - 13ms/step - ia: 0.8445 - loss: 0.1094 - mae: 0.2463 - rmse: 0.3293 - smape: 0.5848 - val_ia: 0.7708 - val_loss: 0.1593 - val_mae: 0.3237 - val_rmse: 0.3926 - val_smape: 0.7299

Epoch 37/128

287/287 - 4s - 13ms/step - ia: 0.8446 - loss: 0.1094 - mae: 0.2460 - rmse: 0.3294 - smape: 0.5838 - val_ia: 0.7816 - val_loss: 0.1475 - val_mae: 0.3107 - val_rmse: 0.3754 - val_smape: 0.7000

Epoch 38/128

287/287 - 4s - 13ms/step - ia: 0.8449 - loss: 0.1089 - mae: 0.2456 - rmse: 0.3285 - smape: 0.5861 - val_ia: 0.7669 - val_loss: 0.1793 - val_mae: 0.3359 - val_rmse: 0.4151 - val_smape: 0.7214

Epoch 39/128

287/287 - 4s - 13ms/step - ia: 0.8454 - loss: 0.1083 - mae: 0.2446 - rmse: 0.3275 - smape: 0.5839 - val_ia: 0.7765 - val_loss: 0.1575 - val_mae: 0.3205 - val_rmse: 0.3890 - val_smape: 0.7115

Epoch 40/128

287/287 - 6s - 21ms/step - ia: 0.8458 - loss: 0.1078 - mae: 0.2444 - rmse: 0.3267 - smape: 0.5852 - val_ia: 0.7897 - val_loss: 0.1413 - val_mae: 0.3029 - val_rmse: 0.3689 - val_smape: 0.6857

Epoch 41/128

287/287 - 11s - 38ms/step - ia: 0.8465 - loss: 0.1069 - mae: 0.2435 - rmse: 0.3253 - smape: 0.5816 - val_ia: 0.7626 - val_loss: 0.1969 - val_mae: 0.3541 - val_rmse: 0.4330 - val_smape: 0.7344

Epoch 42/128

287/287 - 10s - 33ms/step - ia: 0.8463 - loss: 0.1070 - mae: 0.2436 - rmse: 0.3255 - smape: 0.5851 - val_ia: 0.7650 - val_loss: 0.1804 - val_mae: 0.3416 - val_rmse: 0.4126 - val_smape: 0.7314

Epoch 43/128

287/287 - 7s - 23ms/step - ia: 0.8476 - loss: 0.1060 - mae: 0.2417 - rmse: 0.3242 - smape: 0.5800 - val_ia: 0.7739 - val_loss: 0.1702 - val_mae: 0.3309 - val_rmse: 0.4020 - val_smape: 0.7157

Epoch 44/128

287/287 - 10s - 35ms/step - ia: 0.8473 - loss: 0.1057 - mae: 0.2420 - rmse: 0.3236 - smape: 0.5796 - val_ia: 0.7732 - val_loss: 0.1651 - val_mae: 0.3267 - val_rmse: 0.3963 - val_smape: 0.7146

Epoch 45/128

287/287 - 10s - 36ms/step - ia: 0.8477 - loss: 0.1060 - mae: 0.2416 - rmse: 0.3240 - smape: 0.5821 - val_ia: 0.7595 - val_loss: 0.1993 - val_mae: 0.3566 - val_rmse: 0.4350 - val_smape: 0.7421

Epoch 46/128

287/287 - 7s - 23ms/step - ia: 0.8483 - loss: 0.1051 - mae: 0.2406 - rmse: 0.3228 - smape: 0.5778 - val_ia: 0.7456 - val_loss: 0.2196 - val_mae: 0.3802 - val_rmse: 0.4548 - val_smape: 0.7704

Epoch 47/128

287/287 - 10s - 34ms/step - ia: 0.8483 - loss: 0.1046 - mae: 0.2407 - rmse: 0.3219 - smape: 0.5784 - val_ia: 0.7659 - val_loss: 0.1851 - val_mae: 0.3450 - val_rmse: 0.4175 - val_smape: 0.7318

Epoch 48/128

287/287 - 6s - 22ms/step - ia: 0.8480 - loss: 0.1050 - mae: 0.2412 - rmse: 0.3228 - smape: 0.5789 - val_ia: 0.7633 - val_loss: 0.1917 - val_mae: 0.3477 - val_rmse: 0.4267 - val_smape: 0.7309

Epoch 49/128

287/287 - 7s - 23ms/step - ia: 0.8490 - loss: 0.1039 - mae: 0.2395 - rmse: 0.3211 - smape: 0.5778 - val_ia: 0.7634 - val_loss: 0.1876 - val_mae: 0.3490 - val_rmse: 0.4199 - val_smape: 0.7352

Epoch 50/128

287/287 - 7s - 23ms/step - ia: 0.8494 - loss: 0.1035 - mae: 0.2386 - rmse: 0.3202 - smape: 0.5753 - val_ia: 0.7752 - val_loss: 0.1648 - val_mae: 0.3240 - val_rmse: 0.3988 - val_smape: 0.7103

Epoch 51/128

287/287 - 8s - 27ms/step - ia: 0.8502 - loss: 0.1022 - mae: 0.2376 - rmse: 0.3182 - smape: 0.5727 - val_ia: 0.7868 - val_loss: 0.1472 - val_mae: 0.3068 - val_rmse: 0.3763 - val_smape: 0.6880

Epoch 52/128

287/287 - 8s - 27ms/step - ia: 0.8487 - loss: 0.1042 - mae: 0.2399 - rmse: 0.3211 - smape: 0.5781 - val_ia: 0.7789 - val_loss: 0.1607 - val_mae: 0.3216 - val_rmse: 0.3884 - val_smape: 0.7086

Epoch 53/128

287/287 - 4s - 15ms/step - ia: 0.8500 - loss: 0.1029 - mae: 0.2379 - rmse: 0.3195 - smape: 0.5744 - val_ia: 0.7425 - val_loss: 0.2291 - val_mae: 0.3888 - val_rmse: 0.4631 - val_smape: 0.7805

Epoch 54/128

287/287 - 5s - 18ms/step - ia: 0.8506 - loss: 0.1019 - mae: 0.2372 - rmse: 0.3178 - smape: 0.5735 - val_ia: 0.7760 - val_loss: 0.1674 - val_mae: 0.3282 - val_rmse: 0.3983 - val_smape: 0.7106

Epoch 55/128

287/287 - 7s - 24ms/step - ia: 0.8505 - loss: 0.1017 - mae: 0.2371 - rmse: 0.3175 - smape: 0.5737 - val_ia: 0.7839 - val_loss: 0.1524 - val_mae: 0.3121 - val_rmse: 0.3806 - val_smape: 0.6941

Epoch 55: early stopping

Restoring model weights from the end of the best epoch: 40.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:04 400ms/step
  9/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 38/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 49/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 79/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 99/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
116/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
137/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
160/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step

100%|██████████| 12/12 [2:42:40<00:00, 813.41s/trial, best loss: 0.12070520930322165]

In [22]:
print(best)

{'activation': 1, 'batch': 4, 'dropout': 0.2, 'layers': 1.0, 'learning_rate': 0.0002707756079796208, 'units': 4}