Prueba

In [1]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (0.2.7)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.14.1)
Requirement already satisfied: six in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\wamt1\appdata\local\programs\python\python312\lib\site-packages (from hyperopt) (0.10.9.7)
Requirement already satisfied: colorama in c:\users\wamt1\appdata\roaming\python\python312\site-packages (from tqdm->hyperopt) (0.4.6)

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [3]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNconsumptionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [4]:
datos.head()

                      temp        zone1        zone2        zone3  hour
date
2017-01-01 00:00:00  6.559  34055.69620  16128.87538  20240.96386     0
2017-01-01 00:10:00  6.414  29814.68354  19375.07599  20131.08434     0
2017-01-01 00:20:00  6.313  29128.10127  19006.68693  19668.43373     0
2017-01-01 00:30:00  6.121  28228.86076  18361.09422  18899.27711     0
2017-01-01 00:40:00  5.921  27335.69620  17872.34043  18442.40964     0

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (36691, 5)
Las dimensiones de test son:  (10535, 5)
Las dimensiones de val son:  (5190, 5)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(52416, 5)

In [10]:
datosNormalizados.head(10)

                         temp     zone1     zone2     zone3      hour
date
2017-01-01 00:00:00 -2.051356  0.151445 -0.851669  0.033500 -1.660858
2017-01-01 00:10:00 -2.074813 -0.433079 -0.211097  0.016502 -1.660858
2017-01-01 00:20:00 -2.091152 -0.527709 -0.283791 -0.055068 -1.660858
2017-01-01 00:30:00 -2.122213 -0.651648 -0.411186 -0.174054 -1.660858
2017-01-01 00:40:00 -2.154568 -0.774750 -0.507632 -0.244729 -1.660858
2017-01-01 00:50:00 -2.165569 -0.872729 -0.597600 -0.293039 -1.660858
2017-01-01 01:00:00 -2.199865 -0.958984 -0.681090 -0.321667 -1.516340
2017-01-01 01:10:00 -2.223323 -1.035189 -0.746587 -0.396816 -1.516340
2017-01-01 01:20:00 -2.193880 -1.127306 -0.832236 -0.463913 -1.516340
2017-01-01 01:30:00 -2.224132 -1.195976 -0.889096 -0.499698 -1.516340

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 1])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (52381, 12, 5)
Dimensiones de Y: (52381, 1)

In [15]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [16]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (52381, 60)

Se dividen nuevamente los conjuntos de datos

In [ ]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (36666, 60)
Las dimensiones de testX son:  (10529, 60)
Las dimensiones de valX son:  (5186, 60)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (36666, 1)
Las dimensiones de testY son:  (10529, 1)
Las dimensiones de valY son:  (5186, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 6s - 21ms/step - ia: 0.2695 - loss: 1.3131 - mae: 0.9393 - rmse: 1.1445 - smape: 1.4759 - val_ia: 0.2146 - val_loss: 0.8557 - val_mae: 0.7699 - val_rmse: 0.9181 - val_smape: 1.9436

Epoch 2/128

287/287 - 1s - 3ms/step - ia: 0.2498 - loss: 1.1812 - mae: 0.8950 - rmse: 1.0853 - smape: 1.5046 - val_ia: 0.2163 - val_loss: 0.8508 - val_mae: 0.7675 - val_rmse: 0.9153 - val_smape: 1.8973

Epoch 3/128

287/287 - 1s - 3ms/step - ia: 0.2338 - loss: 1.1057 - mae: 0.8684 - rmse: 1.0502 - smape: 1.5246 - val_ia: 0.2189 - val_loss: 0.8464 - val_mae: 0.7655 - val_rmse: 0.9127 - val_smape: 1.8175

Epoch 4/128

287/287 - 1s - 4ms/step - ia: 0.2342 - loss: 1.0335 - mae: 0.8389 - rmse: 1.0150 - smape: 1.5189 - val_ia: 0.2276 - val_loss: 0.8396 - val_mae: 0.7621 - val_rmse: 0.9084 - val_smape: 1.7080

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.2601 - loss: 0.9572 - mae: 0.8058 - rmse: 0.9769 - smape: 1.4747 - val_ia: 0.2427 - val_loss: 0.8438 - val_mae: 0.7633 - val_rmse: 0.9092 - val_smape: 1.5748

Epoch 6/128

287/287 - 1s - 2ms/step - ia: 0.3139 - loss: 0.8781 - mae: 0.7685 - rmse: 0.9354 - smape: 1.3929 - val_ia: 0.2782 - val_loss: 0.8667 - val_mae: 0.7721 - val_rmse: 0.9186 - val_smape: 1.4584

Epoch 7/128

287/287 - 1s - 2ms/step - ia: 0.3738 - loss: 0.8123 - mae: 0.7361 - rmse: 0.8999 - smape: 1.3014 - val_ia: 0.3035 - val_loss: 0.8971 - val_mae: 0.7848 - val_rmse: 0.9321 - val_smape: 1.4053

Epoch 8/128

287/287 - 1s - 5ms/step - ia: 0.4263 - loss: 0.7616 - mae: 0.7095 - rmse: 0.8710 - smape: 1.2243 - val_ia: 0.3294 - val_loss: 0.9411 - val_mae: 0.8027 - val_rmse: 0.9520 - val_smape: 1.3638

Epoch 9/128

287/287 - 1s - 3ms/step - ia: 0.4554 - loss: 0.7329 - mae: 0.6954 - rmse: 0.8548 - smape: 1.1822 - val_ia: 0.3439 - val_loss: 0.9772 - val_mae: 0.8178 - val_rmse: 0.9686 - val_smape: 1.3488

Epoch 10/128

287/287 - 2s - 5ms/step - ia: 0.4747 - loss: 0.7061 - mae: 0.6835 - rmse: 0.8387 - smape: 1.1519 - val_ia: 0.3541 - val_loss: 1.0000 - val_mae: 0.8269 - val_rmse: 0.9789 - val_smape: 1.3385

Epoch 11/128

287/287 - 1s - 4ms/step - ia: 0.4878 - loss: 0.6910 - mae: 0.6735 - rmse: 0.8298 - smape: 1.1293 - val_ia: 0.3591 - val_loss: 1.0130 - val_mae: 0.8315 - val_rmse: 0.9850 - val_smape: 1.3326

Epoch 12/128

287/287 - 1s - 3ms/step - ia: 0.4971 - loss: 0.6764 - mae: 0.6675 - rmse: 0.8210 - smape: 1.1132 - val_ia: 0.3635 - val_loss: 1.0213 - val_mae: 0.8342 - val_rmse: 0.9886 - val_smape: 1.3277

Epoch 13/128

287/287 - 1s - 4ms/step - ia: 0.5033 - loss: 0.6662 - mae: 0.6607 - rmse: 0.8148 - smape: 1.1017 - val_ia: 0.3653 - val_loss: 1.0252 - val_mae: 0.8347 - val_rmse: 0.9905 - val_smape: 1.3257

Epoch 14/128

287/287 - 2s - 6ms/step - ia: 0.5137 - loss: 0.6516 - mae: 0.6529 - rmse: 0.8058 - smape: 1.0840 - val_ia: 0.3651 - val_loss: 1.0332 - val_mae: 0.8376 - val_rmse: 0.9945 - val_smape: 1.3276

Epoch 15/128

287/287 - 1s - 4ms/step - ia: 0.5201 - loss: 0.6384 - mae: 0.6464 - rmse: 0.7975 - smape: 1.0725 - val_ia: 0.3697 - val_loss: 1.0406 - val_mae: 0.8403 - val_rmse: 0.9979 - val_smape: 1.3216

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.5248 - loss: 0.6305 - mae: 0.6422 - rmse: 0.7929 - smape: 1.0645 - val_ia: 0.3733 - val_loss: 1.0502 - val_mae: 0.8441 - val_rmse: 1.0024 - val_smape: 1.3175

Epoch 17/128

287/287 - 1s - 3ms/step - ia: 0.5303 - loss: 0.6252 - mae: 0.6386 - rmse: 0.7891 - smape: 1.0546 - val_ia: 0.3719 - val_loss: 1.0494 - val_mae: 0.8431 - val_rmse: 1.0023 - val_smape: 1.3207

Epoch 18/128

287/287 - 1s - 2ms/step - ia: 0.5340 - loss: 0.6167 - mae: 0.6346 - rmse: 0.7841 - smape: 1.0493 - val_ia: 0.3737 - val_loss: 1.0557 - val_mae: 0.8454 - val_rmse: 1.0053 - val_smape: 1.3195

Epoch 19/128

287/287 - 1s - 3ms/step - ia: 0.5412 - loss: 0.6046 - mae: 0.6277 - rmse: 0.7761 - smape: 1.0371 - val_ia: 0.3786 - val_loss: 1.0607 - val_mae: 0.8477 - val_rmse: 1.0074 - val_smape: 1.3135

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 4.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 43s 271ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 92/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
148/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

  8%|▊         | 1/12 [00:28<05:10, 28.22s/trial, best loss: 0.986918051920107]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 12s - 5ms/step - ia: 0.5964 - loss: 0.4923 - mae: 0.5571 - rmse: 0.6907 - smape: 0.9663 - val_ia: 0.1556 - val_loss: 1.7512 - val_mae: 1.1261 - val_rmse: 1.1706 - val_smape: 1.3821

Epoch 2/128

2292/2292 - 7s - 3ms/step - ia: 0.6021 - loss: 0.4786 - mae: 0.5487 - rmse: 0.6816 - smape: 0.9563 - val_ia: 0.1626 - val_loss: 1.5625 - val_mae: 1.0358 - val_rmse: 1.0791 - val_smape: 1.3407

Epoch 3/128

2292/2292 - 7s - 3ms/step - ia: 0.6018 - loss: 0.4758 - mae: 0.5474 - rmse: 0.6793 - smape: 0.9541 - val_ia: 0.1743 - val_loss: 1.3304 - val_mae: 0.9519 - val_rmse: 0.9945 - val_smape: 1.2854

Epoch 4/128

2292/2292 - 10s - 4ms/step - ia: 0.6039 - loss: 0.4736 - mae: 0.5458 - rmse: 0.6774 - smape: 0.9538 - val_ia: 0.1495 - val_loss: 1.5825 - val_mae: 1.0871 - val_rmse: 1.1290 - val_smape: 1.4028

Epoch 5/128

2292/2292 - 11s - 5ms/step - ia: 0.6041 - loss: 0.4714 - mae: 0.5443 - rmse: 0.6756 - smape: 0.9505 - val_ia: 0.1517 - val_loss: 1.6153 - val_mae: 1.0950 - val_rmse: 1.1361 - val_smape: 1.4065

Epoch 6/128

2292/2292 - 11s - 5ms/step - ia: 0.6045 - loss: 0.4704 - mae: 0.5437 - rmse: 0.6748 - smape: 0.9510 - val_ia: 0.1652 - val_loss: 1.3854 - val_mae: 1.0007 - val_rmse: 1.0404 - val_smape: 1.3629

Epoch 7/128

2292/2292 - 11s - 5ms/step - ia: 0.6054 - loss: 0.4700 - mae: 0.5434 - rmse: 0.6753 - smape: 0.9494 - val_ia: 0.1577 - val_loss: 1.7283 - val_mae: 1.1099 - val_rmse: 1.1556 - val_smape: 1.3602

Epoch 8/128

2292/2292 - 8s - 3ms/step - ia: 0.6074 - loss: 0.4678 - mae: 0.5418 - rmse: 0.6733 - smape: 0.9477 - val_ia: 0.1653 - val_loss: 1.3852 - val_mae: 0.9981 - val_rmse: 1.0406 - val_smape: 1.3422

Epoch 9/128

2292/2292 - 7s - 3ms/step - ia: 0.6073 - loss: 0.4677 - mae: 0.5416 - rmse: 0.6736 - smape: 0.9481 - val_ia: 0.1626 - val_loss: 1.4727 - val_mae: 1.0363 - val_rmse: 1.0775 - val_smape: 1.3669

Epoch 10/128

2292/2292 - 7s - 3ms/step - ia: 0.6069 - loss: 0.4673 - mae: 0.5418 - rmse: 0.6730 - smape: 0.9475 - val_ia: 0.1623 - val_loss: 1.5670 - val_mae: 1.0562 - val_rmse: 1.0991 - val_smape: 1.3511

Epoch 11/128

2292/2292 - 8s - 3ms/step - ia: 0.6074 - loss: 0.4671 - mae: 0.5413 - rmse: 0.6725 - smape: 0.9481 - val_ia: 0.1569 - val_loss: 1.5723 - val_mae: 1.0725 - val_rmse: 1.1145 - val_smape: 1.3818

Epoch 12/128

2292/2292 - 9s - 4ms/step - ia: 0.6072 - loss: 0.4667 - mae: 0.5410 - rmse: 0.6720 - smape: 0.9477 - val_ia: 0.1707 - val_loss: 1.2570 - val_mae: 0.9450 - val_rmse: 0.9836 - val_smape: 1.3311

Epoch 13/128

2292/2292 - 11s - 5ms/step - ia: 0.6060 - loss: 0.4663 - mae: 0.5412 - rmse: 0.6722 - smape: 0.9479 - val_ia: 0.1620 - val_loss: 1.3265 - val_mae: 0.9868 - val_rmse: 1.0257 - val_smape: 1.3710

Epoch 14/128

2292/2292 - 11s - 5ms/step - ia: 0.6086 - loss: 0.4656 - mae: 0.5403 - rmse: 0.6715 - smape: 0.9460 - val_ia: 0.1570 - val_loss: 1.4490 - val_mae: 1.0409 - val_rmse: 1.0804 - val_smape: 1.3953

Epoch 15/128

2292/2292 - 10s - 5ms/step - ia: 0.6076 - loss: 0.4653 - mae: 0.5404 - rmse: 0.6716 - smape: 0.9463 - val_ia: 0.1575 - val_loss: 1.4914 - val_mae: 1.0440 - val_rmse: 1.0850 - val_smape: 1.3793

Epoch 16/128

2292/2292 - 8s - 3ms/step - ia: 0.6083 - loss: 0.4652 - mae: 0.5404 - rmse: 0.6718 - smape: 0.9475 - val_ia: 0.1600 - val_loss: 1.4428 - val_mae: 1.0289 - val_rmse: 1.0702 - val_smape: 1.3718

Epoch 17/128

2292/2292 - 11s - 5ms/step - ia: 0.6071 - loss: 0.4652 - mae: 0.5407 - rmse: 0.6716 - smape: 0.9469 - val_ia: 0.1663 - val_loss: 1.3587 - val_mae: 0.9863 - val_rmse: 1.0255 - val_smape: 1.3523

Epoch 18/128

2292/2292 - 7s - 3ms/step - ia: 0.6070 - loss: 0.4654 - mae: 0.5405 - rmse: 0.6716 - smape: 0.9460 - val_ia: 0.1587 - val_loss: 1.4609 - val_mae: 1.0360 - val_rmse: 1.0768 - val_smape: 1.3757

Epoch 19/128

2292/2292 - 11s - 5ms/step - ia: 0.6078 - loss: 0.4648 - mae: 0.5400 - rmse: 0.6712 - smape: 0.9450 - val_ia: 0.1645 - val_loss: 1.3487 - val_mae: 0.9911 - val_rmse: 1.0328 - val_smape: 1.3533

Epoch 20/128

2292/2292 - 6s - 3ms/step - ia: 0.6082 - loss: 0.4643 - mae: 0.5397 - rmse: 0.6711 - smape: 0.9439 - val_ia: 0.1592 - val_loss: 1.5397 - val_mae: 1.0513 - val_rmse: 1.0958 - val_smape: 1.3542

Epoch 21/128

2292/2292 - 11s - 5ms/step - ia: 0.6086 - loss: 0.4647 - mae: 0.5401 - rmse: 0.6714 - smape: 0.9448 - val_ia: 0.1614 - val_loss: 1.4443 - val_mae: 1.0207 - val_rmse: 1.0594 - val_smape: 1.3708

Epoch 22/128

2292/2292 - 7s - 3ms/step - ia: 0.6089 - loss: 0.4642 - mae: 0.5396 - rmse: 0.6711 - smape: 0.9453 - val_ia: 0.1596 - val_loss: 1.5438 - val_mae: 1.0595 - val_rmse: 1.1046 - val_smape: 1.3599

Epoch 23/128

2292/2292 - 10s - 4ms/step - ia: 0.6092 - loss: 0.4647 - mae: 0.5399 - rmse: 0.6709 - smape: 0.9444 - val_ia: 0.1656 - val_loss: 1.4157 - val_mae: 1.0041 - val_rmse: 1.0461 - val_smape: 1.3394

Epoch 24/128

2292/2292 - 7s - 3ms/step - ia: 0.6082 - loss: 0.4641 - mae: 0.5398 - rmse: 0.6707 - smape: 0.9458 - val_ia: 0.1661 - val_loss: 1.3735 - val_mae: 0.9850 - val_rmse: 1.0260 - val_smape: 1.3336

Epoch 25/128

2292/2292 - 7s - 3ms/step - ia: 0.6083 - loss: 0.4646 - mae: 0.5398 - rmse: 0.6713 - smape: 0.9446 - val_ia: 0.1639 - val_loss: 1.4059 - val_mae: 1.0069 - val_rmse: 1.0471 - val_smape: 1.3577

Epoch 26/128

2292/2292 - 7s - 3ms/step - ia: 0.6089 - loss: 0.4634 - mae: 0.5393 - rmse: 0.6703 - smape: 0.9456 - val_ia: 0.1506 - val_loss: 1.8040 - val_mae: 1.1446 - val_rmse: 1.1907 - val_smape: 1.3858

Epoch 27/128

2292/2292 - 6s - 3ms/step - ia: 0.6088 - loss: 0.4637 - mae: 0.5391 - rmse: 0.6701 - smape: 0.9440 - val_ia: 0.1652 - val_loss: 1.3997 - val_mae: 0.9983 - val_rmse: 1.0403 - val_smape: 1.3378

Epoch 27: early stopping

Restoring model weights from the end of the best epoch: 12.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 40s 250ms/step
 13/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 46/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 94/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
139/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 17%|█▋        | 2/12 [04:25<25:09, 150.92s/trial, best loss: 0.986918051920107]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 19s - 4ms/step - ia: 0.3268 - loss: 0.9809 - mae: 0.8048 - rmse: 0.9658 - smape: 1.4296 - val_ia: 0.1401 - val_loss: 0.8732 - val_mae: 0.7750 - val_rmse: 0.7981 - val_smape: 1.5457

Epoch 2/128

4584/4584 - 18s - 4ms/step - ia: 0.3378 - loss: 0.9290 - mae: 0.7843 - rmse: 0.9410 - smape: 1.4200 - val_ia: 0.1419 - val_loss: 0.8282 - val_mae: 0.7541 - val_rmse: 0.7772 - val_smape: 1.5102

Epoch 3/128

4584/4584 - 12s - 3ms/step - ia: 0.3458 - loss: 0.8901 - mae: 0.7698 - rmse: 0.9216 - smape: 1.4142 - val_ia: 0.1445 - val_loss: 0.7909 - val_mae: 0.7365 - val_rmse: 0.7596 - val_smape: 1.4828

Epoch 4/128

4584/4584 - 19s - 4ms/step - ia: 0.3561 - loss: 0.8647 - mae: 0.7581 - rmse: 0.9077 - smape: 1.4052 - val_ia: 0.1464 - val_loss: 0.7602 - val_mae: 0.7217 - val_rmse: 0.7447 - val_smape: 1.4617

Epoch 5/128

4584/4584 - 12s - 3ms/step - ia: 0.3656 - loss: 0.8381 - mae: 0.7467 - rmse: 0.8934 - smape: 1.3977 - val_ia: 0.1482 - val_loss: 0.7342 - val_mae: 0.7090 - val_rmse: 0.7319 - val_smape: 1.4431

Epoch 6/128

4584/4584 - 11s - 2ms/step - ia: 0.3698 - loss: 0.8270 - mae: 0.7405 - rmse: 0.8869 - smape: 1.3986 - val_ia: 0.1503 - val_loss: 0.7115 - val_mae: 0.6977 - val_rmse: 0.7204 - val_smape: 1.4279

Epoch 7/128

4584/4584 - 12s - 3ms/step - ia: 0.3806 - loss: 0.8029 - mae: 0.7290 - rmse: 0.8743 - smape: 1.3851 - val_ia: 0.1524 - val_loss: 0.6923 - val_mae: 0.6879 - val_rmse: 0.7105 - val_smape: 1.4137

Epoch 8/128

4584/4584 - 20s - 4ms/step - ia: 0.3885 - loss: 0.7856 - mae: 0.7196 - rmse: 0.8650 - smape: 1.3740 - val_ia: 0.1542 - val_loss: 0.6765 - val_mae: 0.6799 - val_rmse: 0.7025 - val_smape: 1.4001

Epoch 9/128

4584/4584 - 11s - 2ms/step - ia: 0.3958 - loss: 0.7732 - mae: 0.7135 - rmse: 0.8577 - smape: 1.3689 - val_ia: 0.1555 - val_loss: 0.6624 - val_mae: 0.6728 - val_rmse: 0.6952 - val_smape: 1.3874

Epoch 10/128

4584/4584 - 11s - 2ms/step - ia: 0.4058 - loss: 0.7584 - mae: 0.7053 - rmse: 0.8496 - smape: 1.3559 - val_ia: 0.1563 - val_loss: 0.6486 - val_mae: 0.6657 - val_rmse: 0.6880 - val_smape: 1.3719

Epoch 11/128

4584/4584 - 11s - 2ms/step - ia: 0.4129 - loss: 0.7440 - mae: 0.6974 - rmse: 0.8409 - smape: 1.3478 - val_ia: 0.1569 - val_loss: 0.6382 - val_mae: 0.6604 - val_rmse: 0.6826 - val_smape: 1.3587

Epoch 12/128

4584/4584 - 21s - 5ms/step - ia: 0.4194 - loss: 0.7322 - mae: 0.6920 - rmse: 0.8336 - smape: 1.3367 - val_ia: 0.1573 - val_loss: 0.6286 - val_mae: 0.6555 - val_rmse: 0.6775 - val_smape: 1.3445

Epoch 13/128

4584/4584 - 11s - 2ms/step - ia: 0.4242 - loss: 0.7276 - mae: 0.6882 - rmse: 0.8310 - smape: 1.3311 - val_ia: 0.1574 - val_loss: 0.6214 - val_mae: 0.6518 - val_rmse: 0.6737 - val_smape: 1.3335

Epoch 14/128

4584/4584 - 21s - 5ms/step - ia: 0.4368 - loss: 0.7039 - mae: 0.6747 - rmse: 0.8180 - smape: 1.3074 - val_ia: 0.1573 - val_loss: 0.6148 - val_mae: 0.6483 - val_rmse: 0.6700 - val_smape: 1.3208

Epoch 15/128

4584/4584 - 20s - 4ms/step - ia: 0.4416 - loss: 0.6975 - mae: 0.6709 - rmse: 0.8132 - smape: 1.3001 - val_ia: 0.1573 - val_loss: 0.6088 - val_mae: 0.6450 - val_rmse: 0.6667 - val_smape: 1.3085

Epoch 16/128

4584/4584 - 12s - 3ms/step - ia: 0.4436 - loss: 0.7000 - mae: 0.6714 - rmse: 0.8146 - smape: 1.2963 - val_ia: 0.1575 - val_loss: 0.6028 - val_mae: 0.6418 - val_rmse: 0.6633 - val_smape: 1.2962

Epoch 17/128

4584/4584 - 11s - 2ms/step - ia: 0.4497 - loss: 0.6855 - mae: 0.6645 - rmse: 0.8068 - smape: 1.2851 - val_ia: 0.1579 - val_loss: 0.5975 - val_mae: 0.6390 - val_rmse: 0.6604 - val_smape: 1.2840

Epoch 18/128

4584/4584 - 12s - 3ms/step - ia: 0.4588 - loss: 0.6763 - mae: 0.6575 - rmse: 0.8000 - smape: 1.2678 - val_ia: 0.1578 - val_loss: 0.5928 - val_mae: 0.6366 - val_rmse: 0.6578 - val_smape: 1.2717

Epoch 19/128

4584/4584 - 14s - 3ms/step - ia: 0.4682 - loss: 0.6598 - mae: 0.6505 - rmse: 0.7910 - smape: 1.2486 - val_ia: 0.1576 - val_loss: 0.5897 - val_mae: 0.6352 - val_rmse: 0.6563 - val_smape: 1.2601

Epoch 20/128

4584/4584 - 17s - 4ms/step - ia: 0.4801 - loss: 0.6413 - mae: 0.6401 - rmse: 0.7789 - smape: 1.2225 - val_ia: 0.1575 - val_loss: 0.5872 - val_mae: 0.6344 - val_rmse: 0.6554 - val_smape: 1.2473

Epoch 21/128

4584/4584 - 11s - 2ms/step - ia: 0.4936 - loss: 0.6141 - mae: 0.6264 - rmse: 0.7615 - smape: 1.1921 - val_ia: 0.1567 - val_loss: 0.5882 - val_mae: 0.6353 - val_rmse: 0.6561 - val_smape: 1.2372

Epoch 22/128

4584/4584 - 21s - 5ms/step - ia: 0.5036 - loss: 0.6067 - mae: 0.6175 - rmse: 0.7554 - smape: 1.1626 - val_ia: 0.1556 - val_loss: 0.5925 - val_mae: 0.6375 - val_rmse: 0.6582 - val_smape: 1.2312

Epoch 23/128

4584/4584 - 11s - 2ms/step - ia: 0.5135 - loss: 0.5912 - mae: 0.6085 - rmse: 0.7465 - smape: 1.1411 - val_ia: 0.1547 - val_loss: 0.5996 - val_mae: 0.6406 - val_rmse: 0.6613 - val_smape: 1.2281

Epoch 24/128

4584/4584 - 26s - 6ms/step - ia: 0.5192 - loss: 0.5868 - mae: 0.6038 - rmse: 0.7416 - smape: 1.1254 - val_ia: 0.1537 - val_loss: 0.6074 - val_mae: 0.6439 - val_rmse: 0.6646 - val_smape: 1.2275

Epoch 25/128

4584/4584 - 16s - 3ms/step - ia: 0.5265 - loss: 0.5771 - mae: 0.5979 - rmse: 0.7350 - smape: 1.1107 - val_ia: 0.1529 - val_loss: 0.6166 - val_mae: 0.6480 - val_rmse: 0.6687 - val_smape: 1.2278

Epoch 26/128

4584/4584 - 20s - 4ms/step - ia: 0.5309 - loss: 0.5708 - mae: 0.5934 - rmse: 0.7318 - smape: 1.1006 - val_ia: 0.1529 - val_loss: 0.6245 - val_mae: 0.6513 - val_rmse: 0.6721 - val_smape: 1.2271

Epoch 27/128

4584/4584 - 21s - 5ms/step - ia: 0.5339 - loss: 0.5629 - mae: 0.5896 - rmse: 0.7262 - smape: 1.0904 - val_ia: 0.1529 - val_loss: 0.6333 - val_mae: 0.6551 - val_rmse: 0.6759 - val_smape: 1.2262

Epoch 28/128

4584/4584 - 16s - 3ms/step - ia: 0.5384 - loss: 0.5589 - mae: 0.5868 - rmse: 0.7234 - smape: 1.0798 - val_ia: 0.1523 - val_loss: 0.6416 - val_mae: 0.6588 - val_rmse: 0.6796 - val_smape: 1.2271

Epoch 29/128

4584/4584 - 9s - 2ms/step - ia: 0.5386 - loss: 0.5575 - mae: 0.5846 - rmse: 0.7219 - smape: 1.0739 - val_ia: 0.1526 - val_loss: 0.6483 - val_mae: 0.6616 - val_rmse: 0.6825 - val_smape: 1.2253

Epoch 30/128

4584/4584 - 9s - 2ms/step - ia: 0.5399 - loss: 0.5512 - mae: 0.5829 - rmse: 0.7185 - smape: 1.0701 - val_ia: 0.1528 - val_loss: 0.6567 - val_mae: 0.6653 - val_rmse: 0.6862 - val_smape: 1.2246

Epoch 31/128

4584/4584 - 9s - 2ms/step - ia: 0.5467 - loss: 0.5421 - mae: 0.5783 - rmse: 0.7122 - smape: 1.0588 - val_ia: 0.1531 - val_loss: 0.6649 - val_mae: 0.6689 - val_rmse: 0.6899 - val_smape: 1.2245

Epoch 32/128

4584/4584 - 12s - 3ms/step - ia: 0.5478 - loss: 0.5414 - mae: 0.5767 - rmse: 0.7123 - smape: 1.0520 - val_ia: 0.1529 - val_loss: 0.6751 - val_mae: 0.6736 - val_rmse: 0.6947 - val_smape: 1.2265

Epoch 33/128

4584/4584 - 16s - 4ms/step - ia: 0.5499 - loss: 0.5350 - mae: 0.5734 - rmse: 0.7077 - smape: 1.0503 - val_ia: 0.1527 - val_loss: 0.6831 - val_mae: 0.6771 - val_rmse: 0.6982 - val_smape: 1.2265

Epoch 34/128

4584/4584 - 16s - 4ms/step - ia: 0.5492 - loss: 0.5381 - mae: 0.5767 - rmse: 0.7109 - smape: 1.0531 - val_ia: 0.1525 - val_loss: 0.6914 - val_mae: 0.6809 - val_rmse: 0.7020 - val_smape: 1.2276

Epoch 35/128

4584/4584 - 11s - 2ms/step - ia: 0.5553 - loss: 0.5298 - mae: 0.5690 - rmse: 0.7039 - smape: 1.0386 - val_ia: 0.1524 - val_loss: 0.6998 - val_mae: 0.6847 - val_rmse: 0.7059 - val_smape: 1.2286

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 22s 141ms/step
 30/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 63/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 87/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
120/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
152/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 25%|██▌       | 3/12 [13:07<48:03, 320.41s/trial, best loss: 0.6606366506449813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1146/1146 - 7s - 6ms/step - ia: 0.2388 - loss: 8.0473 - mae: 2.1273 - rmse: 2.7918 - smape: 1.4896 - val_ia: 0.2291 - val_loss: 0.8887 - val_mae: 0.7766 - val_rmse: 0.8600 - val_smape: 1.3423

Epoch 2/128

1146/1146 - 3s - 2ms/step - ia: 0.2814 - loss: 5.3924 - mae: 1.7590 - rmse: 2.2884 - smape: 1.4361 - val_ia: 0.2435 - val_loss: 0.9392 - val_mae: 0.8038 - val_rmse: 0.8823 - val_smape: 1.3263

Epoch 3/128

1146/1146 - 5s - 4ms/step - ia: 0.3194 - loss: 3.7964 - mae: 1.4944 - rmse: 1.9224 - smape: 1.3881 - val_ia: 0.2486 - val_loss: 0.9789 - val_mae: 0.8235 - val_rmse: 0.8982 - val_smape: 1.3281

Epoch 4/128

1146/1146 - 5s - 4ms/step - ia: 0.3492 - loss: 2.8655 - mae: 1.3086 - rmse: 1.6722 - smape: 1.3561 - val_ia: 0.2501 - val_loss: 1.0105 - val_mae: 0.8411 - val_rmse: 0.9130 - val_smape: 1.3349

Epoch 5/128

1146/1146 - 3s - 2ms/step - ia: 0.3746 - loss: 2.2933 - mae: 1.1776 - rmse: 1.4985 - smape: 1.3244 - val_ia: 0.2495 - val_loss: 1.0413 - val_mae: 0.8561 - val_rmse: 0.9272 - val_smape: 1.3407

Epoch 6/128

1146/1146 - 3s - 2ms/step - ia: 0.3981 - loss: 1.8729 - mae: 1.0708 - rmse: 1.3546 - smape: 1.2964 - val_ia: 0.2497 - val_loss: 1.0495 - val_mae: 0.8608 - val_rmse: 0.9308 - val_smape: 1.3445

Epoch 7/128

1146/1146 - 5s - 4ms/step - ia: 0.4139 - loss: 1.5852 - mae: 0.9931 - rmse: 1.2472 - smape: 1.2812 - val_ia: 0.2488 - val_loss: 1.0631 - val_mae: 0.8685 - val_rmse: 0.9380 - val_smape: 1.3497

Epoch 8/128

1146/1146 - 4s - 3ms/step - ia: 0.4315 - loss: 1.3822 - mae: 0.9267 - rmse: 1.1649 - smape: 1.2541 - val_ia: 0.2470 - val_loss: 1.0946 - val_mae: 0.8819 - val_rmse: 0.9517 - val_smape: 1.3537

Epoch 9/128

1146/1146 - 7s - 6ms/step - ia: 0.4444 - loss: 1.2365 - mae: 0.8774 - rmse: 1.1021 - smape: 1.2371 - val_ia: 0.2463 - val_loss: 1.1136 - val_mae: 0.8890 - val_rmse: 0.9590 - val_smape: 1.3556

Epoch 10/128

1146/1146 - 5s - 4ms/step - ia: 0.4583 - loss: 1.1155 - mae: 0.8363 - rmse: 1.0469 - smape: 1.2183 - val_ia: 0.2440 - val_loss: 1.1451 - val_mae: 0.9035 - val_rmse: 0.9733 - val_smape: 1.3630

Epoch 11/128

1146/1146 - 5s - 4ms/step - ia: 0.4636 - loss: 1.0414 - mae: 0.8069 - rmse: 1.0124 - smape: 1.2070 - val_ia: 0.2423 - val_loss: 1.1696 - val_mae: 0.9136 - val_rmse: 0.9836 - val_smape: 1.3662

Epoch 12/128

1146/1146 - 6s - 5ms/step - ia: 0.4729 - loss: 0.9760 - mae: 0.7821 - rmse: 0.9794 - smape: 1.1943 - val_ia: 0.2412 - val_loss: 1.1976 - val_mae: 0.9235 - val_rmse: 0.9937 - val_smape: 1.3667

Epoch 13/128

1146/1146 - 6s - 5ms/step - ia: 0.4834 - loss: 0.9090 - mae: 0.7545 - rmse: 0.9448 - smape: 1.1772 - val_ia: 0.2400 - val_loss: 1.2259 - val_mae: 0.9348 - val_rmse: 1.0048 - val_smape: 1.3703

Epoch 14/128

1146/1146 - 5s - 4ms/step - ia: 0.4918 - loss: 0.8645 - mae: 0.7382 - rmse: 0.9222 - smape: 1.1653 - val_ia: 0.2386 - val_loss: 1.2426 - val_mae: 0.9420 - val_rmse: 1.0120 - val_smape: 1.3730

Epoch 15/128

1146/1146 - 5s - 4ms/step - ia: 0.4935 - loss: 0.8367 - mae: 0.7266 - rmse: 0.9068 - smape: 1.1632 - val_ia: 0.2377 - val_loss: 1.2609 - val_mae: 0.9485 - val_rmse: 1.0189 - val_smape: 1.3721

Epoch 16/128

1146/1146 - 4s - 4ms/step - ia: 0.4971 - loss: 0.8150 - mae: 0.7177 - rmse: 0.8955 - smape: 1.1553 - val_ia: 0.2374 - val_loss: 1.2609 - val_mae: 0.9497 - val_rmse: 1.0194 - val_smape: 1.3739

Epoch 16: early stopping

Restoring model weights from the end of the best epoch: 1.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 22s 138ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 83/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
123/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 33%|███▎      | 4/12 [14:25<29:58, 224.78s/trial, best loss: 0.6606366506449813]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

573/573 - 12s - 20ms/step - ia: 0.1549 - loss: 2.1509 - mae: 1.2406 - rmse: 1.4631 - smape: 1.6577 - val_ia: 0.1705 - val_loss: 1.9047 - val_mae: 1.1735 - val_rmse: 1.3219 - val_smape: 1.5155

Epoch 2/128

573/573 - 4s - 7ms/step - ia: 0.1637 - loss: 2.0294 - mae: 1.2040 - rmse: 1.4214 - smape: 1.6482 - val_ia: 0.1727 - val_loss: 1.7690 - val_mae: 1.1365 - val_rmse: 1.2783 - val_smape: 1.5210

Epoch 3/128

573/573 - 2s - 3ms/step - ia: 0.1726 - loss: 1.9427 - mae: 1.1768 - rmse: 1.3908 - smape: 1.6362 - val_ia: 0.1754 - val_loss: 1.6436 - val_mae: 1.1003 - val_rmse: 1.2362 - val_smape: 1.5259

Epoch 4/128

573/573 - 2s - 3ms/step - ia: 0.1840 - loss: 1.8401 - mae: 1.1436 - rmse: 1.3532 - smape: 1.6206 - val_ia: 0.1788 - val_loss: 1.5282 - val_mae: 1.0649 - val_rmse: 1.1957 - val_smape: 1.5306

Epoch 5/128

573/573 - 2s - 4ms/step - ia: 0.1964 - loss: 1.7477 - mae: 1.1126 - rmse: 1.3189 - smape: 1.6036 - val_ia: 0.1829 - val_loss: 1.4217 - val_mae: 1.0300 - val_rmse: 1.1565 - val_smape: 1.5348

Epoch 6/128

573/573 - 3s - 5ms/step - ia: 0.2034 - loss: 1.6699 - mae: 1.0871 - rmse: 1.2892 - smape: 1.5927 - val_ia: 0.1881 - val_loss: 1.3238 - val_mae: 0.9958 - val_rmse: 1.1188 - val_smape: 1.5388

Epoch 7/128

573/573 - 3s - 5ms/step - ia: 0.2121 - loss: 1.5985 - mae: 1.0633 - rmse: 1.2614 - smape: 1.5835 - val_ia: 0.1944 - val_loss: 1.2346 - val_mae: 0.9622 - val_rmse: 1.0826 - val_smape: 1.5426

Epoch 8/128

573/573 - 3s - 5ms/step - ia: 0.2247 - loss: 1.5331 - mae: 1.0389 - rmse: 1.2351 - smape: 1.5653 - val_ia: 0.2017 - val_loss: 1.1534 - val_mae: 0.9295 - val_rmse: 1.0479 - val_smape: 1.5452

Epoch 9/128

573/573 - 3s - 5ms/step - ia: 0.2402 - loss: 1.4601 - mae: 1.0129 - rmse: 1.2055 - smape: 1.5435 - val_ia: 0.2104 - val_loss: 1.0800 - val_mae: 0.8979 - val_rmse: 1.0149 - val_smape: 1.5468

Epoch 10/128

573/573 - 2s - 4ms/step - ia: 0.2556 - loss: 1.3937 - mae: 0.9860 - rmse: 1.1777 - smape: 1.5199 - val_ia: 0.2202 - val_loss: 1.0148 - val_mae: 0.8679 - val_rmse: 0.9841 - val_smape: 1.5439

Epoch 11/128

573/573 - 2s - 4ms/step - ia: 0.2672 - loss: 1.3258 - mae: 0.9619 - rmse: 1.1483 - smape: 1.5060 - val_ia: 0.2310 - val_loss: 0.9581 - val_mae: 0.8400 - val_rmse: 0.9557 - val_smape: 1.5285

Epoch 12/128

573/573 - 4s - 6ms/step - ia: 0.2774 - loss: 1.2934 - mae: 0.9476 - rmse: 1.1341 - smape: 1.4879 - val_ia: 0.2433 - val_loss: 0.9081 - val_mae: 0.8138 - val_rmse: 0.9292 - val_smape: 1.5051

Epoch 13/128

573/573 - 5s - 8ms/step - ia: 0.2931 - loss: 1.2419 - mae: 0.9274 - rmse: 1.1113 - smape: 1.4695 - val_ia: 0.2566 - val_loss: 0.8656 - val_mae: 0.7904 - val_rmse: 0.9054 - val_smape: 1.4830

Epoch 14/128

573/573 - 3s - 5ms/step - ia: 0.3097 - loss: 1.1863 - mae: 0.9038 - rmse: 1.0864 - smape: 1.4412 - val_ia: 0.2695 - val_loss: 0.8301 - val_mae: 0.7702 - val_rmse: 0.8841 - val_smape: 1.4609

Epoch 15/128

573/573 - 2s - 3ms/step - ia: 0.3202 - loss: 1.1568 - mae: 0.8920 - rmse: 1.0729 - smape: 1.4253 - val_ia: 0.2816 - val_loss: 0.8017 - val_mae: 0.7536 - val_rmse: 0.8660 - val_smape: 1.4419

Epoch 16/128

573/573 - 1s - 2ms/step - ia: 0.3396 - loss: 1.0980 - mae: 0.8683 - rmse: 1.0451 - smape: 1.3993 - val_ia: 0.2931 - val_loss: 0.7794 - val_mae: 0.7397 - val_rmse: 0.8508 - val_smape: 1.4215

Epoch 17/128

573/573 - 3s - 5ms/step - ia: 0.3550 - loss: 1.0587 - mae: 0.8503 - rmse: 1.0262 - smape: 1.3747 - val_ia: 0.3044 - val_loss: 0.7632 - val_mae: 0.7287 - val_rmse: 0.8387 - val_smape: 1.3984

Epoch 18/128

573/573 - 1s - 2ms/step - ia: 0.3667 - loss: 1.0310 - mae: 0.8380 - rmse: 1.0126 - smape: 1.3556 - val_ia: 0.3161 - val_loss: 0.7524 - val_mae: 0.7200 - val_rmse: 0.8296 - val_smape: 1.3728

Epoch 19/128

573/573 - 1s - 2ms/step - ia: 0.3851 - loss: 0.9903 - mae: 0.8189 - rmse: 0.9924 - smape: 1.3322 - val_ia: 0.3271 - val_loss: 0.7470 - val_mae: 0.7139 - val_rmse: 0.8237 - val_smape: 1.3468

Epoch 20/128

573/573 - 1s - 2ms/step - ia: 0.3921 - loss: 0.9715 - mae: 0.8115 - rmse: 0.9828 - smape: 1.3200 - val_ia: 0.3384 - val_loss: 0.7458 - val_mae: 0.7099 - val_rmse: 0.8206 - val_smape: 1.3233

Epoch 21/128

573/573 - 1s - 2ms/step - ia: 0.4095 - loss: 0.9346 - mae: 0.7951 - rmse: 0.9636 - smape: 1.2960 - val_ia: 0.3492 - val_loss: 0.7489 - val_mae: 0.7080 - val_rmse: 0.8202 - val_smape: 1.3015

Epoch 22/128

573/573 - 1s - 2ms/step - ia: 0.4181 - loss: 0.9187 - mae: 0.7868 - rmse: 0.9557 - smape: 1.2831 - val_ia: 0.3588 - val_loss: 0.7554 - val_mae: 0.7081 - val_rmse: 0.8222 - val_smape: 1.2850

Epoch 23/128

573/573 - 2s - 3ms/step - ia: 0.4311 - loss: 0.8941 - mae: 0.7749 - rmse: 0.9429 - smape: 1.2635 - val_ia: 0.3671 - val_loss: 0.7655 - val_mae: 0.7106 - val_rmse: 0.8266 - val_smape: 1.2714

Epoch 24/128

573/573 - 1s - 2ms/step - ia: 0.4416 - loss: 0.8710 - mae: 0.7643 - rmse: 0.9305 - smape: 1.2474 - val_ia: 0.3739 - val_loss: 0.7776 - val_mae: 0.7149 - val_rmse: 0.8325 - val_smape: 1.2615

Epoch 25/128

573/573 - 1s - 2ms/step - ia: 0.4532 - loss: 0.8477 - mae: 0.7531 - rmse: 0.9181 - smape: 1.2312 - val_ia: 0.3794 - val_loss: 0.7918 - val_mae: 0.7210 - val_rmse: 0.8398 - val_smape: 1.2565

Epoch 26/128

573/573 - 1s - 3ms/step - ia: 0.4645 - loss: 0.8291 - mae: 0.7425 - rmse: 0.9078 - smape: 1.2120 - val_ia: 0.3835 - val_loss: 0.8081 - val_mae: 0.7284 - val_rmse: 0.8485 - val_smape: 1.2540

Epoch 27/128

573/573 - 2s - 4ms/step - ia: 0.4733 - loss: 0.8144 - mae: 0.7362 - rmse: 0.8997 - smape: 1.1980 - val_ia: 0.3863 - val_loss: 0.8249 - val_mae: 0.7367 - val_rmse: 0.8576 - val_smape: 1.2551

Epoch 28/128

573/573 - 1s - 2ms/step - ia: 0.4810 - loss: 0.7999 - mae: 0.7283 - rmse: 0.8912 - smape: 1.1864 - val_ia: 0.3882 - val_loss: 0.8427 - val_mae: 0.7458 - val_rmse: 0.8674 - val_smape: 1.2584

Epoch 29/128

573/573 - 1s - 2ms/step - ia: 0.4886 - loss: 0.7885 - mae: 0.7228 - rmse: 0.8854 - smape: 1.1757 - val_ia: 0.3891 - val_loss: 0.8607 - val_mae: 0.7554 - val_rmse: 0.8774 - val_smape: 1.2626

Epoch 30/128

573/573 - 2s - 4ms/step - ia: 0.4937 - loss: 0.7751 - mae: 0.7177 - rmse: 0.8776 - smape: 1.1695 - val_ia: 0.3894 - val_loss: 0.8792 - val_mae: 0.7651 - val_rmse: 0.8875 - val_smape: 1.2670

Epoch 31/128

573/573 - 2s - 3ms/step - ia: 0.5044 - loss: 0.7541 - mae: 0.7060 - rmse: 0.8655 - smape: 1.1518 - val_ia: 0.3890 - val_loss: 0.8968 - val_mae: 0.7749 - val_rmse: 0.8971 - val_smape: 1.2721

Epoch 32/128

573/573 - 1s - 2ms/step - ia: 0.5060 - loss: 0.7540 - mae: 0.7055 - rmse: 0.8655 - smape: 1.1474 - val_ia: 0.3885 - val_loss: 0.9146 - val_mae: 0.7844 - val_rmse: 0.9068 - val_smape: 1.2767

Epoch 33/128

573/573 - 1s - 2ms/step - ia: 0.5166 - loss: 0.7348 - mae: 0.6957 - rmse: 0.8542 - smape: 1.1333 - val_ia: 0.3875 - val_loss: 0.9314 - val_mae: 0.7935 - val_rmse: 0.9158 - val_smape: 1.2815

Epoch 34/128

573/573 - 3s - 4ms/step - ia: 0.5187 - loss: 0.7322 - mae: 0.6949 - rmse: 0.8527 - smape: 1.1300 - val_ia: 0.3863 - val_loss: 0.9484 - val_mae: 0.8028 - val_rmse: 0.9248 - val_smape: 1.2865

Epoch 35/128

573/573 - 4s - 6ms/step - ia: 0.5218 - loss: 0.7237 - mae: 0.6908 - rmse: 0.8480 - smape: 1.1258 - val_ia: 0.3850 - val_loss: 0.9643 - val_mae: 0.8114 - val_rmse: 0.9332 - val_smape: 1.2917

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 20.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 58s 362ms/step
 23/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 37/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 54/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 62/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 91/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
101/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
109/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
110/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
126/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 42%|████▏     | 5/12 [15:52<20:27, 175.30s/trial, best loss: 0.6302634588467535]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 13s - 44ms/step - ia: 0.2665 - loss: 1.3388 - mae: 0.9506 - rmse: 1.1553 - smape: 1.4760 - val_ia: 0.2473 - val_loss: 1.0070 - val_mae: 0.8325 - val_rmse: 0.9882 - val_smape: 1.5188

Epoch 2/128

287/287 - 4s - 13ms/step - ia: 0.2654 - loss: 1.2859 - mae: 0.9305 - rmse: 1.1321 - smape: 1.4790 - val_ia: 0.2342 - val_loss: 0.9510 - val_mae: 0.8092 - val_rmse: 0.9623 - val_smape: 1.5629

Epoch 3/128

287/287 - 2s - 9ms/step - ia: 0.2641 - loss: 1.2587 - mae: 0.9216 - rmse: 1.1200 - smape: 1.4830 - val_ia: 0.2281 - val_loss: 0.9135 - val_mae: 0.7932 - val_rmse: 0.9445 - val_smape: 1.6039

Epoch 4/128

287/287 - 1s - 5ms/step - ia: 0.2644 - loss: 1.2380 - mae: 0.9133 - rmse: 1.1111 - smape: 1.4813 - val_ia: 0.2261 - val_loss: 0.8894 - val_mae: 0.7829 - val_rmse: 0.9328 - val_smape: 1.6359

Epoch 5/128

287/287 - 1s - 5ms/step - ia: 0.2678 - loss: 1.2190 - mae: 0.9055 - rmse: 1.1022 - smape: 1.4779 - val_ia: 0.2270 - val_loss: 0.8739 - val_mae: 0.7763 - val_rmse: 0.9251 - val_smape: 1.6555

Epoch 6/128

287/287 - 3s - 10ms/step - ia: 0.2717 - loss: 1.2010 - mae: 0.8990 - rmse: 1.0942 - smape: 1.4724 - val_ia: 0.2284 - val_loss: 0.8605 - val_mae: 0.7704 - val_rmse: 0.9184 - val_smape: 1.6753

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.2742 - loss: 1.1830 - mae: 0.8929 - rmse: 1.0864 - smape: 1.4710 - val_ia: 0.2307 - val_loss: 0.8499 - val_mae: 0.7657 - val_rmse: 0.9130 - val_smape: 1.6877

Epoch 8/128

287/287 - 2s - 5ms/step - ia: 0.2735 - loss: 1.1790 - mae: 0.8933 - rmse: 1.0841 - smape: 1.4722 - val_ia: 0.2339 - val_loss: 0.8431 - val_mae: 0.7626 - val_rmse: 0.9094 - val_smape: 1.6837

Epoch 9/128

287/287 - 1s - 5ms/step - ia: 0.2798 - loss: 1.1593 - mae: 0.8858 - rmse: 1.0750 - smape: 1.4639 - val_ia: 0.2375 - val_loss: 0.8363 - val_mae: 0.7595 - val_rmse: 0.9058 - val_smape: 1.6747

Epoch 10/128

287/287 - 3s - 9ms/step - ia: 0.2812 - loss: 1.1464 - mae: 0.8817 - rmse: 1.0688 - smape: 1.4625 - val_ia: 0.2414 - val_loss: 0.8305 - val_mae: 0.7568 - val_rmse: 0.9027 - val_smape: 1.6595

Epoch 11/128

287/287 - 1s - 5ms/step - ia: 0.2838 - loss: 1.1314 - mae: 0.8750 - rmse: 1.0619 - smape: 1.4590 - val_ia: 0.2454 - val_loss: 0.8262 - val_mae: 0.7547 - val_rmse: 0.9003 - val_smape: 1.6404

Epoch 12/128

287/287 - 2s - 8ms/step - ia: 0.2894 - loss: 1.1169 - mae: 0.8695 - rmse: 1.0556 - smape: 1.4522 - val_ia: 0.2497 - val_loss: 0.8231 - val_mae: 0.7531 - val_rmse: 0.8985 - val_smape: 1.6204

Epoch 13/128

287/287 - 1s - 4ms/step - ia: 0.2911 - loss: 1.1128 - mae: 0.8687 - rmse: 1.0534 - smape: 1.4494 - val_ia: 0.2539 - val_loss: 0.8178 - val_mae: 0.7505 - val_rmse: 0.8957 - val_smape: 1.6024

Epoch 14/128

287/287 - 2s - 6ms/step - ia: 0.2990 - loss: 1.0853 - mae: 0.8571 - rmse: 1.0403 - smape: 1.4375 - val_ia: 0.2587 - val_loss: 0.8154 - val_mae: 0.7492 - val_rmse: 0.8942 - val_smape: 1.5836

Epoch 15/128

287/287 - 2s - 6ms/step - ia: 0.2972 - loss: 1.0901 - mae: 0.8598 - rmse: 1.0427 - smape: 1.4423 - val_ia: 0.2633 - val_loss: 0.8108 - val_mae: 0.7469 - val_rmse: 0.8916 - val_smape: 1.5671

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.2999 - loss: 1.0782 - mae: 0.8563 - rmse: 1.0366 - smape: 1.4425 - val_ia: 0.2683 - val_loss: 0.8090 - val_mae: 0.7459 - val_rmse: 0.8905 - val_smape: 1.5516

Epoch 17/128

287/287 - 1s - 4ms/step - ia: 0.3076 - loss: 1.0576 - mae: 0.8457 - rmse: 1.0271 - smape: 1.4270 - val_ia: 0.2734 - val_loss: 0.8077 - val_mae: 0.7451 - val_rmse: 0.8896 - val_smape: 1.5371

Epoch 18/128

287/287 - 2s - 5ms/step - ia: 0.3144 - loss: 1.0401 - mae: 0.8397 - rmse: 1.0186 - smape: 1.4225 - val_ia: 0.2782 - val_loss: 0.8056 - val_mae: 0.7439 - val_rmse: 0.8882 - val_smape: 1.5236

Epoch 19/128

287/287 - 1s - 5ms/step - ia: 0.3118 - loss: 1.0407 - mae: 0.8426 - rmse: 1.0185 - smape: 1.4243 - val_ia: 0.2832 - val_loss: 0.8036 - val_mae: 0.7428 - val_rmse: 0.8870 - val_smape: 1.5104

Epoch 20/128

287/287 - 1s - 5ms/step - ia: 0.3171 - loss: 1.0320 - mae: 0.8362 - rmse: 1.0144 - smape: 1.4170 - val_ia: 0.2879 - val_loss: 0.8016 - val_mae: 0.7418 - val_rmse: 0.8857 - val_smape: 1.4985

Epoch 21/128

287/287 - 1s - 5ms/step - ia: 0.3234 - loss: 1.0111 - mae: 0.8282 - rmse: 1.0043 - smape: 1.4088 - val_ia: 0.2926 - val_loss: 0.8000 - val_mae: 0.7410 - val_rmse: 0.8846 - val_smape: 1.4877

Epoch 22/128

287/287 - 1s - 5ms/step - ia: 0.3279 - loss: 1.0065 - mae: 0.8254 - rmse: 1.0017 - smape: 1.3991 - val_ia: 0.2976 - val_loss: 0.8004 - val_mae: 0.7411 - val_rmse: 0.8846 - val_smape: 1.4773

Epoch 23/128

287/287 - 1s - 5ms/step - ia: 0.3281 - loss: 0.9989 - mae: 0.8244 - rmse: 0.9983 - smape: 1.4007 - val_ia: 0.3021 - val_loss: 0.7985 - val_mae: 0.7401 - val_rmse: 0.8833 - val_smape: 1.4670

Epoch 24/128

287/287 - 2s - 6ms/step - ia: 0.3338 - loss: 0.9858 - mae: 0.8169 - rmse: 0.9916 - smape: 1.3905 - val_ia: 0.3067 - val_loss: 0.7979 - val_mae: 0.7397 - val_rmse: 0.8827 - val_smape: 1.4572

Epoch 25/128

287/287 - 1s - 5ms/step - ia: 0.3376 - loss: 0.9745 - mae: 0.8120 - rmse: 0.9859 - smape: 1.3872 - val_ia: 0.3112 - val_loss: 0.7967 - val_mae: 0.7392 - val_rmse: 0.8819 - val_smape: 1.4477

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.3448 - loss: 0.9633 - mae: 0.8082 - rmse: 0.9798 - smape: 1.3762 - val_ia: 0.3158 - val_loss: 0.7979 - val_mae: 0.7397 - val_rmse: 0.8822 - val_smape: 1.4391

Epoch 27/128

287/287 - 1s - 5ms/step - ia: 0.3445 - loss: 0.9605 - mae: 0.8064 - rmse: 0.9791 - smape: 1.3762 - val_ia: 0.3200 - val_loss: 0.7968 - val_mae: 0.7392 - val_rmse: 0.8814 - val_smape: 1.4311

Epoch 28/128

287/287 - 1s - 5ms/step - ia: 0.3517 - loss: 0.9433 - mae: 0.7991 - rmse: 0.9699 - smape: 1.3679 - val_ia: 0.3245 - val_loss: 0.7982 - val_mae: 0.7398 - val_rmse: 0.8818 - val_smape: 1.4234

Epoch 29/128

287/287 - 3s - 11ms/step - ia: 0.3571 - loss: 0.9308 - mae: 0.7950 - rmse: 0.9637 - smape: 1.3608 - val_ia: 0.3290 - val_loss: 0.7999 - val_mae: 0.7406 - val_rmse: 0.8824 - val_smape: 1.4164

Epoch 30/128

287/287 - 2s - 5ms/step - ia: 0.3607 - loss: 0.9241 - mae: 0.7909 - rmse: 0.9598 - smape: 1.3553 - val_ia: 0.3333 - val_loss: 0.8012 - val_mae: 0.7412 - val_rmse: 0.8828 - val_smape: 1.4095

Epoch 31/128

287/287 - 1s - 5ms/step - ia: 0.3646 - loss: 0.9155 - mae: 0.7876 - rmse: 0.9553 - smape: 1.3502 - val_ia: 0.3375 - val_loss: 0.8019 - val_mae: 0.7415 - val_rmse: 0.8829 - val_smape: 1.4024

Epoch 32/128

287/287 - 2s - 5ms/step - ia: 0.3672 - loss: 0.9070 - mae: 0.7839 - rmse: 0.9513 - smape: 1.3446 - val_ia: 0.3419 - val_loss: 0.8059 - val_mae: 0.7434 - val_rmse: 0.8847 - val_smape: 1.3961

Epoch 33/128

287/287 - 1s - 5ms/step - ia: 0.3750 - loss: 0.8940 - mae: 0.7794 - rmse: 0.9438 - smape: 1.3379 - val_ia: 0.3459 - val_loss: 0.8075 - val_mae: 0.7442 - val_rmse: 0.8853 - val_smape: 1.3899

Epoch 34/128

287/287 - 1s - 5ms/step - ia: 0.3815 - loss: 0.8803 - mae: 0.7704 - rmse: 0.9373 - smape: 1.3248 - val_ia: 0.3499 - val_loss: 0.8101 - val_mae: 0.7454 - val_rmse: 0.8864 - val_smape: 1.3839

Epoch 35/128

287/287 - 3s - 9ms/step - ia: 0.3870 - loss: 0.8679 - mae: 0.7665 - rmse: 0.9301 - smape: 1.3182 - val_ia: 0.3539 - val_loss: 0.8129 - val_mae: 0.7467 - val_rmse: 0.8875 - val_smape: 1.3782

Epoch 36/128

287/287 - 2s - 5ms/step - ia: 0.3886 - loss: 0.8694 - mae: 0.7663 - rmse: 0.9307 - smape: 1.3162 - val_ia: 0.3579 - val_loss: 0.8167 - val_mae: 0.7486 - val_rmse: 0.8892 - val_smape: 1.3732

Epoch 37/128

287/287 - 3s - 9ms/step - ia: 0.3959 - loss: 0.8599 - mae: 0.7604 - rmse: 0.9259 - smape: 1.3039 - val_ia: 0.3616 - val_loss: 0.8202 - val_mae: 0.7503 - val_rmse: 0.8908 - val_smape: 1.3685

Epoch 38/128

287/287 - 3s - 9ms/step - ia: 0.4037 - loss: 0.8431 - mae: 0.7517 - rmse: 0.9167 - smape: 1.2916 - val_ia: 0.3653 - val_loss: 0.8246 - val_mae: 0.7526 - val_rmse: 0.8928 - val_smape: 1.3642

Epoch 39/128

287/287 - 3s - 10ms/step - ia: 0.4098 - loss: 0.8282 - mae: 0.7462 - rmse: 0.9086 - smape: 1.2835 - val_ia: 0.3688 - val_loss: 0.8296 - val_mae: 0.7552 - val_rmse: 0.8951 - val_smape: 1.3607

Epoch 40/128

287/287 - 2s - 8ms/step - ia: 0.4107 - loss: 0.8287 - mae: 0.7469 - rmse: 0.9092 - smape: 1.2840 - val_ia: 0.3721 - val_loss: 0.8335 - val_mae: 0.7572 - val_rmse: 0.8969 - val_smape: 1.3572

Epoch 40: early stopping

Restoring model weights from the end of the best epoch: 25.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 15s 96ms/step
 27/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 56/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 77/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
102/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
131/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Epoch 1/128

 50%|█████     | 6/12 [17:18<14:28, 144.73s/trial, best loss: 0.6302634588467535]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

287/287 - 7s - 25ms/step - ia: 0.5761 - loss: 0.7323 - mae: 0.6376 - rmse: 0.8012 - smape: 1.0209 - val_ia: 0.3999 - val_loss: 1.5819 - val_mae: 1.0681 - val_rmse: 1.1936 - val_smape: 1.3982

Epoch 2/128

287/287 - 2s - 5ms/step - ia: 0.6054 - loss: 0.4946 - mae: 0.5598 - rmse: 0.7018 - smape: 0.9718 - val_ia: 0.4035 - val_loss: 1.5124 - val_mae: 1.0528 - val_rmse: 1.1700 - val_smape: 1.3968

Epoch 3/128

287/287 - 2s - 5ms/step - ia: 0.6100 - loss: 0.4846 - mae: 0.5534 - rmse: 0.6947 - smape: 0.9658 - val_ia: 0.4056 - val_loss: 1.5270 - val_mae: 1.0532 - val_rmse: 1.1857 - val_smape: 1.3752

Epoch 4/128

287/287 - 1s - 4ms/step - ia: 0.6091 - loss: 0.4842 - mae: 0.5538 - rmse: 0.6946 - smape: 0.9656 - val_ia: 0.4106 - val_loss: 1.3398 - val_mae: 0.9903 - val_rmse: 1.1015 - val_smape: 1.3811

Epoch 5/128

287/287 - 2s - 7ms/step - ia: 0.6090 - loss: 0.4858 - mae: 0.5539 - rmse: 0.6956 - smape: 0.9649 - val_ia: 0.3971 - val_loss: 1.4155 - val_mae: 1.0283 - val_rmse: 1.1370 - val_smape: 1.4133

Epoch 6/128

287/287 - 1s - 5ms/step - ia: 0.6093 - loss: 0.4851 - mae: 0.5538 - rmse: 0.6952 - smape: 0.9654 - val_ia: 0.4398 - val_loss: 1.5229 - val_mae: 0.9801 - val_rmse: 1.1872 - val_smape: 1.2267

Epoch 7/128

287/287 - 1s - 5ms/step - ia: 0.6074 - loss: 0.4886 - mae: 0.5560 - rmse: 0.6976 - smape: 0.9656 - val_ia: 0.4115 - val_loss: 1.2141 - val_mae: 0.9410 - val_rmse: 1.0533 - val_smape: 1.3780

Epoch 8/128

287/287 - 1s - 5ms/step - ia: 0.6089 - loss: 0.4859 - mae: 0.5539 - rmse: 0.6958 - smape: 0.9652 - val_ia: 0.4190 - val_loss: 1.3643 - val_mae: 0.9882 - val_rmse: 1.1131 - val_smape: 1.3472

Epoch 9/128

287/287 - 1s - 4ms/step - ia: 0.6089 - loss: 0.4870 - mae: 0.5543 - rmse: 0.6965 - smape: 0.9658 - val_ia: 0.4178 - val_loss: 1.2697 - val_mae: 0.9596 - val_rmse: 1.0747 - val_smape: 1.3574

Epoch 10/128

287/287 - 2s - 6ms/step - ia: 0.6082 - loss: 0.4883 - mae: 0.5556 - rmse: 0.6974 - smape: 0.9690 - val_ia: 0.4158 - val_loss: 1.3632 - val_mae: 1.0006 - val_rmse: 1.1167 - val_smape: 1.3620

Epoch 11/128

287/287 - 1s - 5ms/step - ia: 0.6065 - loss: 0.4914 - mae: 0.5576 - rmse: 0.6996 - smape: 0.9696 - val_ia: 0.4310 - val_loss: 1.2204 - val_mae: 0.9243 - val_rmse: 1.0547 - val_smape: 1.3134

Epoch 12/128

287/287 - 2s - 6ms/step - ia: 0.6062 - loss: 0.4918 - mae: 0.5579 - rmse: 0.6999 - smape: 0.9681 - val_ia: 0.4048 - val_loss: 1.3557 - val_mae: 1.0054 - val_rmse: 1.1156 - val_smape: 1.3931

Epoch 13/128

287/287 - 2s - 5ms/step - ia: 0.6072 - loss: 0.4905 - mae: 0.5559 - rmse: 0.6990 - smape: 0.9675 - val_ia: 0.4079 - val_loss: 1.5201 - val_mae: 1.0637 - val_rmse: 1.1759 - val_smape: 1.3878

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.6074 - loss: 0.4907 - mae: 0.5568 - rmse: 0.6989 - smape: 0.9659 - val_ia: 0.4225 - val_loss: 1.5803 - val_mae: 1.0526 - val_rmse: 1.1970 - val_smape: 1.3260

Epoch 15/128

287/287 - 2s - 6ms/step - ia: 0.6090 - loss: 0.4885 - mae: 0.5547 - rmse: 0.6974 - smape: 0.9661 - val_ia: 0.4117 - val_loss: 1.5165 - val_mae: 1.0473 - val_rmse: 1.1759 - val_smape: 1.3634

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.6036 - loss: 0.4955 - mae: 0.5600 - rmse: 0.7025 - smape: 0.9712 - val_ia: 0.4380 - val_loss: 1.2813 - val_mae: 0.9453 - val_rmse: 1.0847 - val_smape: 1.2891

Epoch 17/128

287/287 - 1s - 5ms/step - ia: 0.6092 - loss: 0.4872 - mae: 0.5552 - rmse: 0.6966 - smape: 0.9651 - val_ia: 0.4305 - val_loss: 1.2467 - val_mae: 0.9322 - val_rmse: 1.0678 - val_smape: 1.3037

Epoch 18/128

287/287 - 2s - 6ms/step - ia: 0.6083 - loss: 0.4896 - mae: 0.5556 - rmse: 0.6983 - smape: 0.9660 - val_ia: 0.4066 - val_loss: 1.3253 - val_mae: 0.9978 - val_rmse: 1.1007 - val_smape: 1.3943

Epoch 19/128

287/287 - 3s - 9ms/step - ia: 0.6055 - loss: 0.4942 - mae: 0.5586 - rmse: 0.7015 - smape: 0.9704 - val_ia: 0.3994 - val_loss: 1.6995 - val_mae: 1.1078 - val_rmse: 1.2512 - val_smape: 1.3866

Epoch 20/128

287/287 - 2s - 5ms/step - ia: 0.6072 - loss: 0.4913 - mae: 0.5572 - rmse: 0.6994 - smape: 0.9698 - val_ia: 0.4240 - val_loss: 1.2169 - val_mae: 0.9226 - val_rmse: 1.0594 - val_smape: 1.3089

Epoch 21/128

287/287 - 1s - 4ms/step - ia: 0.6061 - loss: 0.4932 - mae: 0.5585 - rmse: 0.7008 - smape: 0.9700 - val_ia: 0.4239 - val_loss: 1.2496 - val_mae: 0.9443 - val_rmse: 1.0763 - val_smape: 1.3278

Epoch 22/128

287/287 - 1s - 5ms/step - ia: 0.6044 - loss: 0.4960 - mae: 0.5599 - rmse: 0.7030 - smape: 0.9729 - val_ia: 0.4083 - val_loss: 1.9786 - val_mae: 1.1692 - val_rmse: 1.3529 - val_smape: 1.3257

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 7.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 41s 254ms/step
 20/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 40/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 55/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 80/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 95/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
112/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
121/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
132/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 58%|█████▊    | 7/12 [17:59<09:14, 110.96s/trial, best loss: 0.6302634588467535]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 30s - 6ms/step - ia: 0.6697 - loss: 0.3492 - mae: 0.4558 - rmse: 0.5638 - smape: 0.8296 - val_ia: 0.1785 - val_loss: 0.7211 - val_mae: 0.6139 - val_rmse: 0.6459 - val_smape: 1.0564

Epoch 2/128

4584/4584 - 18s - 4ms/step - ia: 0.7511 - loss: 0.2102 - mae: 0.3508 - rmse: 0.4381 - smape: 0.7250 - val_ia: 0.2142 - val_loss: 0.3161 - val_mae: 0.4382 - val_rmse: 0.4616 - val_smape: 0.9171

Epoch 3/128

4584/4584 - 16s - 4ms/step - ia: 0.7693 - loss: 0.1811 - mae: 0.3235 - rmse: 0.4062 - smape: 0.6969 - val_ia: 0.2075 - val_loss: 0.3564 - val_mae: 0.4586 - val_rmse: 0.4813 - val_smape: 0.9703

Epoch 4/128

4584/4584 - 22s - 5ms/step - ia: 0.7763 - loss: 0.1688 - mae: 0.3135 - rmse: 0.3922 - smape: 0.6818 - val_ia: 0.2120 - val_loss: 0.2678 - val_mae: 0.4117 - val_rmse: 0.4354 - val_smape: 0.8609

Epoch 5/128

4584/4584 - 16s - 3ms/step - ia: 0.7839 - loss: 0.1601 - mae: 0.3045 - rmse: 0.3820 - smape: 0.6698 - val_ia: 0.2270 - val_loss: 0.2603 - val_mae: 0.4015 - val_rmse: 0.4242 - val_smape: 0.8343

Epoch 6/128

4584/4584 - 19s - 4ms/step - ia: 0.7850 - loss: 0.1578 - mae: 0.3025 - rmse: 0.3786 - smape: 0.6676 - val_ia: 0.2183 - val_loss: 0.2961 - val_mae: 0.4192 - val_rmse: 0.4486 - val_smape: 0.8817

Epoch 7/128

4584/4584 - 11s - 2ms/step - ia: 0.7869 - loss: 0.1550 - mae: 0.2998 - rmse: 0.3760 - smape: 0.6632 - val_ia: 0.2305 - val_loss: 0.2354 - val_mae: 0.3854 - val_rmse: 0.4068 - val_smape: 0.7987

Epoch 8/128

4584/4584 - 17s - 4ms/step - ia: 0.7901 - loss: 0.1506 - mae: 0.2953 - rmse: 0.3699 - smape: 0.6508 - val_ia: 0.2189 - val_loss: 0.2283 - val_mae: 0.3846 - val_rmse: 0.4110 - val_smape: 0.8608

Epoch 9/128

4584/4584 - 19s - 4ms/step - ia: 0.7903 - loss: 0.1508 - mae: 0.2949 - rmse: 0.3703 - smape: 0.6513 - val_ia: 0.2266 - val_loss: 0.2283 - val_mae: 0.3816 - val_rmse: 0.4036 - val_smape: 0.8388

Epoch 10/128

4584/4584 - 16s - 3ms/step - ia: 0.7929 - loss: 0.1474 - mae: 0.2925 - rmse: 0.3660 - smape: 0.6467 - val_ia: 0.2233 - val_loss: 0.2175 - val_mae: 0.3774 - val_rmse: 0.4021 - val_smape: 0.8647

Epoch 11/128

4584/4584 - 16s - 4ms/step - ia: 0.7928 - loss: 0.1467 - mae: 0.2920 - rmse: 0.3652 - smape: 0.6515 - val_ia: 0.2399 - val_loss: 0.2061 - val_mae: 0.3595 - val_rmse: 0.3838 - val_smape: 0.7814

Epoch 12/128

4584/4584 - 22s - 5ms/step - ia: 0.7953 - loss: 0.1451 - mae: 0.2894 - rmse: 0.3633 - smape: 0.6387 - val_ia: 0.2277 - val_loss: 0.2192 - val_mae: 0.3776 - val_rmse: 0.4029 - val_smape: 0.8105

Epoch 13/128

4584/4584 - 26s - 6ms/step - ia: 0.7945 - loss: 0.1447 - mae: 0.2897 - rmse: 0.3620 - smape: 0.6426 - val_ia: 0.2134 - val_loss: 0.2757 - val_mae: 0.4071 - val_rmse: 0.4346 - val_smape: 0.8819

Epoch 14/128

4584/4584 - 17s - 4ms/step - ia: 0.7951 - loss: 0.1438 - mae: 0.2892 - rmse: 0.3619 - smape: 0.6471 - val_ia: 0.2348 - val_loss: 0.1986 - val_mae: 0.3585 - val_rmse: 0.3816 - val_smape: 0.7931

Epoch 15/128

4584/4584 - 17s - 4ms/step - ia: 0.7945 - loss: 0.1429 - mae: 0.2882 - rmse: 0.3606 - smape: 0.6432 - val_ia: 0.2500 - val_loss: 0.2132 - val_mae: 0.3593 - val_rmse: 0.3833 - val_smape: 0.7440

Epoch 16/128

4584/4584 - 17s - 4ms/step - ia: 0.7987 - loss: 0.1400 - mae: 0.2856 - rmse: 0.3573 - smape: 0.6354 - val_ia: 0.2392 - val_loss: 0.2021 - val_mae: 0.3602 - val_rmse: 0.3826 - val_smape: 0.7356

Epoch 17/128

4584/4584 - 15s - 3ms/step - ia: 0.7966 - loss: 0.1423 - mae: 0.2880 - rmse: 0.3600 - smape: 0.6427 - val_ia: 0.2252 - val_loss: 0.2165 - val_mae: 0.3749 - val_rmse: 0.4007 - val_smape: 0.8449

Epoch 18/128

4584/4584 - 9s - 2ms/step - ia: 0.7964 - loss: 0.1416 - mae: 0.2865 - rmse: 0.3587 - smape: 0.6393 - val_ia: 0.2358 - val_loss: 0.2146 - val_mae: 0.3703 - val_rmse: 0.3942 - val_smape: 0.7380

Epoch 19/128

4584/4584 - 9s - 2ms/step - ia: 0.7980 - loss: 0.1411 - mae: 0.2859 - rmse: 0.3586 - smape: 0.6372 - val_ia: 0.2518 - val_loss: 0.2159 - val_mae: 0.3613 - val_rmse: 0.3849 - val_smape: 0.7443

Epoch 20/128

4584/4584 - 9s - 2ms/step - ia: 0.7971 - loss: 0.1409 - mae: 0.2862 - rmse: 0.3583 - smape: 0.6402 - val_ia: 0.2292 - val_loss: 0.2208 - val_mae: 0.3780 - val_rmse: 0.4031 - val_smape: 0.7668

Epoch 21/128

4584/4584 - 13s - 3ms/step - ia: 0.7970 - loss: 0.1396 - mae: 0.2851 - rmse: 0.3569 - smape: 0.6395 - val_ia: 0.2441 - val_loss: 0.1601 - val_mae: 0.3266 - val_rmse: 0.3488 - val_smape: 0.7514

Epoch 22/128

4584/4584 - 24s - 5ms/step - ia: 0.7991 - loss: 0.1380 - mae: 0.2834 - rmse: 0.3544 - smape: 0.6338 - val_ia: 0.2466 - val_loss: 0.1707 - val_mae: 0.3364 - val_rmse: 0.3601 - val_smape: 0.7759

Epoch 23/128

4584/4584 - 15s - 3ms/step - ia: 0.8013 - loss: 0.1365 - mae: 0.2825 - rmse: 0.3527 - smape: 0.6343 - val_ia: 0.2401 - val_loss: 0.1969 - val_mae: 0.3546 - val_rmse: 0.3780 - val_smape: 0.7829

Epoch 24/128

4584/4584 - 16s - 4ms/step - ia: 0.8008 - loss: 0.1371 - mae: 0.2825 - rmse: 0.3530 - smape: 0.6346 - val_ia: 0.2289 - val_loss: 0.2002 - val_mae: 0.3578 - val_rmse: 0.3828 - val_smape: 0.7485

Epoch 25/128

4584/4584 - 16s - 3ms/step - ia: 0.7996 - loss: 0.1369 - mae: 0.2824 - rmse: 0.3528 - smape: 0.6315 - val_ia: 0.2274 - val_loss: 0.2203 - val_mae: 0.3737 - val_rmse: 0.3992 - val_smape: 0.7693

Epoch 26/128

4584/4584 - 15s - 3ms/step - ia: 0.7990 - loss: 0.1389 - mae: 0.2842 - rmse: 0.3557 - smape: 0.6338 - val_ia: 0.2527 - val_loss: 0.1645 - val_mae: 0.3230 - val_rmse: 0.3482 - val_smape: 0.7026

Epoch 27/128

4584/4584 - 10s - 2ms/step - ia: 0.8017 - loss: 0.1366 - mae: 0.2813 - rmse: 0.3521 - smape: 0.6277 - val_ia: 0.2437 - val_loss: 0.2075 - val_mae: 0.3525 - val_rmse: 0.3805 - val_smape: 0.7594

Epoch 28/128

4584/4584 - 10s - 2ms/step - ia: 0.8005 - loss: 0.1375 - mae: 0.2827 - rmse: 0.3534 - smape: 0.6301 - val_ia: 0.2444 - val_loss: 0.1807 - val_mae: 0.3387 - val_rmse: 0.3642 - val_smape: 0.7797

Epoch 29/128

4584/4584 - 9s - 2ms/step - ia: 0.8022 - loss: 0.1344 - mae: 0.2796 - rmse: 0.3499 - smape: 0.6268 - val_ia: 0.2210 - val_loss: 0.2399 - val_mae: 0.3904 - val_rmse: 0.4149 - val_smape: 0.7294

Epoch 30/128

4584/4584 - 15s - 3ms/step - ia: 0.8030 - loss: 0.1355 - mae: 0.2798 - rmse: 0.3511 - smape: 0.6272 - val_ia: 0.2387 - val_loss: 0.2027 - val_mae: 0.3549 - val_rmse: 0.3791 - val_smape: 0.7685

Epoch 31/128

4584/4584 - 22s - 5ms/step - ia: 0.8000 - loss: 0.1366 - mae: 0.2817 - rmse: 0.3524 - smape: 0.6343 - val_ia: 0.2289 - val_loss: 0.2169 - val_mae: 0.3665 - val_rmse: 0.3931 - val_smape: 0.8136

Epoch 32/128

4584/4584 - 12s - 3ms/step - ia: 0.8031 - loss: 0.1337 - mae: 0.2786 - rmse: 0.3490 - smape: 0.6249 - val_ia: 0.2412 - val_loss: 0.1851 - val_mae: 0.3449 - val_rmse: 0.3696 - val_smape: 0.7185

Epoch 33/128

4584/4584 - 9s - 2ms/step - ia: 0.8010 - loss: 0.1365 - mae: 0.2816 - rmse: 0.3525 - smape: 0.6273 - val_ia: 0.2376 - val_loss: 0.1949 - val_mae: 0.3563 - val_rmse: 0.3788 - val_smape: 0.7406

Epoch 34/128

4584/4584 - 9s - 2ms/step - ia: 0.8024 - loss: 0.1353 - mae: 0.2802 - rmse: 0.3507 - smape: 0.6278 - val_ia: 0.2291 - val_loss: 0.2042 - val_mae: 0.3663 - val_rmse: 0.3886 - val_smape: 0.7780

Epoch 35/128

4584/4584 - 10s - 2ms/step - ia: 0.8022 - loss: 0.1348 - mae: 0.2804 - rmse: 0.3507 - smape: 0.6286 - val_ia: 0.2422 - val_loss: 0.1744 - val_mae: 0.3367 - val_rmse: 0.3630 - val_smape: 0.7189

Epoch 36/128

4584/4584 - 11s - 2ms/step - ia: 0.8026 - loss: 0.1339 - mae: 0.2797 - rmse: 0.3492 - smape: 0.6274 - val_ia: 0.2417 - val_loss: 0.1838 - val_mae: 0.3467 - val_rmse: 0.3703 - val_smape: 0.7822

Epoch 36: early stopping

Restoring model weights from the end of the best epoch: 21.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 1:23 519ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 24/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 43/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 65/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 69/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 86/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
108/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
118/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
129/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
149/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

 67%|██████▋   | 8/12 [27:21<16:57, 254.35s/trial, best loss: 0.2304277413911462]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 8s - 26ms/step - ia: 0.5281 - loss: 0.9020 - mae: 0.7263 - rmse: 0.9178 - smape: 1.1043 - val_ia: 0.4086 - val_loss: 1.4626 - val_mae: 1.0203 - val_rmse: 1.1562 - val_smape: 1.3704

Epoch 2/128

287/287 - 1s - 5ms/step - ia: 0.5747 - loss: 0.5653 - mae: 0.5993 - rmse: 0.7501 - smape: 1.0258 - val_ia: 0.4112 - val_loss: 1.4041 - val_mae: 0.9992 - val_rmse: 1.1311 - val_smape: 1.3657

Epoch 3/128

287/287 - 1s - 3ms/step - ia: 0.5856 - loss: 0.5300 - mae: 0.5812 - rmse: 0.7269 - smape: 1.0047 - val_ia: 0.4093 - val_loss: 1.4352 - val_mae: 1.0127 - val_rmse: 1.1441 - val_smape: 1.3713

Epoch 4/128

287/287 - 1s - 3ms/step - ia: 0.5899 - loss: 0.5143 - mae: 0.5727 - rmse: 0.7157 - smape: 0.9968 - val_ia: 0.4140 - val_loss: 1.3533 - val_mae: 0.9842 - val_rmse: 1.1104 - val_smape: 1.3619

Epoch 5/128

287/287 - 1s - 3ms/step - ia: 0.5924 - loss: 0.5074 - mae: 0.5693 - rmse: 0.7111 - smape: 0.9934 - val_ia: 0.4122 - val_loss: 1.4691 - val_mae: 1.0197 - val_rmse: 1.1600 - val_smape: 1.3560

Epoch 6/128

287/287 - 1s - 5ms/step - ia: 0.5945 - loss: 0.5040 - mae: 0.5667 - rmse: 0.7084 - smape: 0.9906 - val_ia: 0.4089 - val_loss: 1.3720 - val_mae: 1.0005 - val_rmse: 1.1141 - val_smape: 1.3813

Epoch 7/128

287/287 - 1s - 3ms/step - ia: 0.5960 - loss: 0.5018 - mae: 0.5652 - rmse: 0.7071 - smape: 0.9885 - val_ia: 0.4079 - val_loss: 1.4323 - val_mae: 1.0205 - val_rmse: 1.1409 - val_smape: 1.3792

Epoch 8/128

287/287 - 1s - 4ms/step - ia: 0.5974 - loss: 0.4992 - mae: 0.5633 - rmse: 0.7053 - smape: 0.9852 - val_ia: 0.4210 - val_loss: 1.3694 - val_mae: 0.9850 - val_rmse: 1.1195 - val_smape: 1.3381

Epoch 9/128

287/287 - 2s - 6ms/step - ia: 0.5967 - loss: 0.5007 - mae: 0.5633 - rmse: 0.7062 - smape: 0.9864 - val_ia: 0.4184 - val_loss: 1.3845 - val_mae: 0.9913 - val_rmse: 1.1230 - val_smape: 1.3461

Epoch 10/128

287/287 - 3s - 10ms/step - ia: 0.5996 - loss: 0.4973 - mae: 0.5608 - rmse: 0.7038 - smape: 0.9799 - val_ia: 0.4201 - val_loss: 1.3926 - val_mae: 0.9877 - val_rmse: 1.1254 - val_smape: 1.3362

Epoch 11/128

287/287 - 3s - 10ms/step - ia: 0.5979 - loss: 0.4976 - mae: 0.5617 - rmse: 0.7042 - smape: 0.9832 - val_ia: 0.4214 - val_loss: 1.2861 - val_mae: 0.9549 - val_rmse: 1.0853 - val_smape: 1.3367

Epoch 12/128

287/287 - 2s - 7ms/step - ia: 0.5988 - loss: 0.4963 - mae: 0.5606 - rmse: 0.7030 - smape: 0.9814 - val_ia: 0.4255 - val_loss: 1.3284 - val_mae: 0.9638 - val_rmse: 1.1030 - val_smape: 1.3191

Epoch 13/128

287/287 - 2s - 9ms/step - ia: 0.5998 - loss: 0.4950 - mae: 0.5599 - rmse: 0.7025 - smape: 0.9814 - val_ia: 0.4237 - val_loss: 1.3362 - val_mae: 0.9695 - val_rmse: 1.1059 - val_smape: 1.3264

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.5983 - loss: 0.4964 - mae: 0.5609 - rmse: 0.7031 - smape: 0.9820 - val_ia: 0.4225 - val_loss: 1.3609 - val_mae: 0.9823 - val_rmse: 1.1155 - val_smape: 1.3330

Epoch 15/128

287/287 - 2s - 9ms/step - ia: 0.5995 - loss: 0.4951 - mae: 0.5597 - rmse: 0.7023 - smape: 0.9812 - val_ia: 0.4085 - val_loss: 1.4481 - val_mae: 1.0256 - val_rmse: 1.1482 - val_smape: 1.3741

Epoch 16/128

287/287 - 1s - 5ms/step - ia: 0.5999 - loss: 0.4945 - mae: 0.5591 - rmse: 0.7020 - smape: 0.9794 - val_ia: 0.4099 - val_loss: 1.4470 - val_mae: 1.0214 - val_rmse: 1.1492 - val_smape: 1.3662

Epoch 17/128

287/287 - 1s - 4ms/step - ia: 0.6002 - loss: 0.4939 - mae: 0.5588 - rmse: 0.7014 - smape: 0.9781 - val_ia: 0.4151 - val_loss: 1.4336 - val_mae: 1.0106 - val_rmse: 1.1446 - val_smape: 1.3527

Epoch 18/128

287/287 - 1s - 3ms/step - ia: 0.5993 - loss: 0.4949 - mae: 0.5601 - rmse: 0.7022 - smape: 0.9810 - val_ia: 0.4081 - val_loss: 1.3779 - val_mae: 1.0066 - val_rmse: 1.1205 - val_smape: 1.3818

Epoch 19/128

287/287 - 1s - 3ms/step - ia: 0.5988 - loss: 0.4943 - mae: 0.5603 - rmse: 0.7018 - smape: 0.9816 - val_ia: 0.4154 - val_loss: 1.3979 - val_mae: 0.9984 - val_rmse: 1.1283 - val_smape: 1.3515

Epoch 20/128

287/287 - 1s - 4ms/step - ia: 0.6003 - loss: 0.4927 - mae: 0.5586 - rmse: 0.7005 - smape: 0.9795 - val_ia: 0.4133 - val_loss: 1.4252 - val_mae: 1.0155 - val_rmse: 1.1414 - val_smape: 1.3615

Epoch 21/128

287/287 - 2s - 6ms/step - ia: 0.5999 - loss: 0.4943 - mae: 0.5604 - rmse: 0.7017 - smape: 0.9799 - val_ia: 0.4214 - val_loss: 1.3913 - val_mae: 0.9922 - val_rmse: 1.1274 - val_smape: 1.3342

Epoch 22/128

287/287 - 2s - 6ms/step - ia: 0.5996 - loss: 0.4947 - mae: 0.5599 - rmse: 0.7021 - smape: 0.9815 - val_ia: 0.4212 - val_loss: 1.3045 - val_mae: 0.9662 - val_rmse: 1.0934 - val_smape: 1.3409

Epoch 23/128

287/287 - 1s - 4ms/step - ia: 0.6002 - loss: 0.4939 - mae: 0.5589 - rmse: 0.7016 - smape: 0.9797 - val_ia: 0.4154 - val_loss: 1.3936 - val_mae: 0.9989 - val_rmse: 1.1269 - val_smape: 1.3550

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.5983 - loss: 0.4958 - mae: 0.5611 - rmse: 0.7027 - smape: 0.9838 - val_ia: 0.4070 - val_loss: 1.4559 - val_mae: 1.0318 - val_rmse: 1.1496 - val_smape: 1.3824

Epoch 25/128

287/287 - 1s - 4ms/step - ia: 0.6001 - loss: 0.4933 - mae: 0.5584 - rmse: 0.7011 - smape: 0.9786 - val_ia: 0.4093 - val_loss: 1.4306 - val_mae: 1.0223 - val_rmse: 1.1401 - val_smape: 1.3770

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.6014 - loss: 0.4918 - mae: 0.5576 - rmse: 0.6999 - smape: 0.9775 - val_ia: 0.4076 - val_loss: 1.4290 - val_mae: 1.0257 - val_rmse: 1.1376 - val_smape: 1.3850

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 34s 210ms/step
  7/163 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
 22/163 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 61/163 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 88/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
106/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
134/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

 75%|███████▌  | 9/12 [28:10<09:30, 190.20s/trial, best loss: 0.2304277413911462]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

2292/2292 - 28s - 12ms/step - ia: 0.4542 - loss: 0.8855 - mae: 0.7554 - rmse: 0.9217 - smape: 1.2100 - val_ia: 0.1763 - val_loss: 1.2293 - val_mae: 0.9361 - val_rmse: 0.9731 - val_smape: 1.3459

Epoch 2/128

2292/2292 - 8s - 3ms/step - ia: 0.5558 - loss: 0.5910 - mae: 0.6153 - rmse: 0.7572 - smape: 1.0383 - val_ia: 0.1737 - val_loss: 1.2797 - val_mae: 0.9523 - val_rmse: 0.9901 - val_smape: 1.3576

Epoch 3/128

2292/2292 - 9s - 4ms/step - ia: 0.5869 - loss: 0.5149 - mae: 0.5707 - rmse: 0.7066 - smape: 0.9837 - val_ia: 0.1733 - val_loss: 1.2643 - val_mae: 0.9393 - val_rmse: 0.9758 - val_smape: 1.3619

Epoch 4/128

2292/2292 - 9s - 4ms/step - ia: 0.6052 - loss: 0.4758 - mae: 0.5471 - rmse: 0.6790 - smape: 0.9539 - val_ia: 0.1755 - val_loss: 1.1636 - val_mae: 0.8879 - val_rmse: 0.9233 - val_smape: 1.3517

Epoch 5/128

2292/2292 - 11s - 5ms/step - ia: 0.6191 - loss: 0.4477 - mae: 0.5294 - rmse: 0.6585 - smape: 0.9323 - val_ia: 0.1763 - val_loss: 1.2310 - val_mae: 0.9136 - val_rmse: 0.9477 - val_smape: 1.3698

Epoch 6/128

2292/2292 - 9s - 4ms/step - ia: 0.6289 - loss: 0.4275 - mae: 0.5167 - rmse: 0.6434 - smape: 0.9189 - val_ia: 0.1780 - val_loss: 1.2139 - val_mae: 0.9008 - val_rmse: 0.9345 - val_smape: 1.3678

Epoch 7/128

2292/2292 - 10s - 4ms/step - ia: 0.6392 - loss: 0.4095 - mae: 0.5049 - rmse: 0.6294 - smape: 0.9013 - val_ia: 0.1820 - val_loss: 1.1631 - val_mae: 0.8749 - val_rmse: 0.9084 - val_smape: 1.3540

Epoch 8/128

2292/2292 - 12s - 5ms/step - ia: 0.6486 - loss: 0.3932 - mae: 0.4940 - rmse: 0.6164 - smape: 0.8874 - val_ia: 0.1853 - val_loss: 1.1512 - val_mae: 0.8671 - val_rmse: 0.9000 - val_smape: 1.3551

Epoch 9/128

2292/2292 - 12s - 5ms/step - ia: 0.6593 - loss: 0.3735 - mae: 0.4808 - rmse: 0.6011 - smape: 0.8712 - val_ia: 0.1889 - val_loss: 1.1627 - val_mae: 0.8659 - val_rmse: 0.8990 - val_smape: 1.3486

Epoch 10/128

2292/2292 - 17s - 8ms/step - ia: 0.6683 - loss: 0.3558 - mae: 0.4699 - rmse: 0.5863 - smape: 0.8590 - val_ia: 0.1961 - val_loss: 1.1526 - val_mae: 0.8588 - val_rmse: 0.8918 - val_smape: 1.3465

Epoch 11/128

2292/2292 - 8s - 4ms/step - ia: 0.6754 - loss: 0.3430 - mae: 0.4610 - rmse: 0.5756 - smape: 0.8508 - val_ia: 0.2020 - val_loss: 1.1854 - val_mae: 0.8648 - val_rmse: 0.8981 - val_smape: 1.3436

Epoch 12/128

2292/2292 - 11s - 5ms/step - ia: 0.6838 - loss: 0.3278 - mae: 0.4509 - rmse: 0.5632 - smape: 0.8391 - val_ia: 0.2106 - val_loss: 1.1436 - val_mae: 0.8410 - val_rmse: 0.8754 - val_smape: 1.3315

Epoch 13/128

2292/2292 - 9s - 4ms/step - ia: 0.6906 - loss: 0.3157 - mae: 0.4421 - rmse: 0.5524 - smape: 0.8313 - val_ia: 0.2172 - val_loss: 1.1281 - val_mae: 0.8265 - val_rmse: 0.8619 - val_smape: 1.3172

Epoch 14/128

2292/2292 - 11s - 5ms/step - ia: 0.6993 - loss: 0.3034 - mae: 0.4323 - rmse: 0.5410 - smape: 0.8224 - val_ia: 0.2241 - val_loss: 1.0647 - val_mae: 0.7963 - val_rmse: 0.8326 - val_smape: 1.3003

Epoch 15/128

2292/2292 - 9s - 4ms/step - ia: 0.7047 - loss: 0.2924 - mae: 0.4240 - rmse: 0.5312 - smape: 0.8143 - val_ia: 0.2256 - val_loss: 1.1153 - val_mae: 0.8072 - val_rmse: 0.8446 - val_smape: 1.2929

Epoch 16/128

2292/2292 - 8s - 4ms/step - ia: 0.7114 - loss: 0.2829 - mae: 0.4166 - rmse: 0.5219 - smape: 0.8053 - val_ia: 0.2279 - val_loss: 1.0943 - val_mae: 0.7940 - val_rmse: 0.8323 - val_smape: 1.2849

Epoch 17/128

2292/2292 - 8s - 4ms/step - ia: 0.7156 - loss: 0.2746 - mae: 0.4099 - rmse: 0.5146 - smape: 0.8018 - val_ia: 0.2293 - val_loss: 1.0865 - val_mae: 0.7868 - val_rmse: 0.8258 - val_smape: 1.2782

Epoch 18/128

2292/2292 - 12s - 5ms/step - ia: 0.7239 - loss: 0.2643 - mae: 0.4012 - rmse: 0.5047 - smape: 0.7920 - val_ia: 0.2303 - val_loss: 1.0263 - val_mae: 0.7632 - val_rmse: 0.8021 - val_smape: 1.2710

Epoch 19/128

2292/2292 - 11s - 5ms/step - ia: 0.7271 - loss: 0.2583 - mae: 0.3969 - rmse: 0.4991 - smape: 0.7884 - val_ia: 0.2310 - val_loss: 1.0109 - val_mae: 0.7576 - val_rmse: 0.7970 - val_smape: 1.2690

Epoch 20/128

2292/2292 - 6s - 3ms/step - ia: 0.7307 - loss: 0.2511 - mae: 0.3910 - rmse: 0.4915 - smape: 0.7829 - val_ia: 0.2329 - val_loss: 0.9663 - val_mae: 0.7398 - val_rmse: 0.7793 - val_smape: 1.2590

Epoch 21/128

2292/2292 - 5s - 2ms/step - ia: 0.7332 - loss: 0.2459 - mae: 0.3867 - rmse: 0.4863 - smape: 0.7758 - val_ia: 0.2334 - val_loss: 0.9458 - val_mae: 0.7330 - val_rmse: 0.7729 - val_smape: 1.2567

Epoch 22/128

2292/2292 - 5s - 2ms/step - ia: 0.7373 - loss: 0.2401 - mae: 0.3823 - rmse: 0.4807 - smape: 0.7732 - val_ia: 0.2340 - val_loss: 0.9326 - val_mae: 0.7259 - val_rmse: 0.7666 - val_smape: 1.2527

Epoch 23/128

2292/2292 - 5s - 2ms/step - ia: 0.7402 - loss: 0.2346 - mae: 0.3786 - rmse: 0.4752 - smape: 0.7707 - val_ia: 0.2354 - val_loss: 0.8896 - val_mae: 0.7105 - val_rmse: 0.7513 - val_smape: 1.2503

Epoch 24/128

2292/2292 - 5s - 2ms/step - ia: 0.7425 - loss: 0.2328 - mae: 0.3754 - rmse: 0.4733 - smape: 0.7652 - val_ia: 0.2371 - val_loss: 0.8582 - val_mae: 0.6971 - val_rmse: 0.7382 - val_smape: 1.2400

Epoch 25/128

2292/2292 - 5s - 2ms/step - ia: 0.7455 - loss: 0.2271 - mae: 0.3706 - rmse: 0.4673 - smape: 0.7600 - val_ia: 0.2395 - val_loss: 0.7968 - val_mae: 0.6742 - val_rmse: 0.7152 - val_smape: 1.2347

Epoch 26/128

2292/2292 - 5s - 2ms/step - ia: 0.7488 - loss: 0.2233 - mae: 0.3669 - rmse: 0.4632 - smape: 0.7552 - val_ia: 0.2389 - val_loss: 0.8042 - val_mae: 0.6767 - val_rmse: 0.7185 - val_smape: 1.2315

Epoch 27/128

2292/2292 - 6s - 3ms/step - ia: 0.7495 - loss: 0.2195 - mae: 0.3650 - rmse: 0.4597 - smape: 0.7524 - val_ia: 0.2401 - val_loss: 0.7599 - val_mae: 0.6609 - val_rmse: 0.7030 - val_smape: 1.2236

Epoch 28/128

2292/2292 - 9s - 4ms/step - ia: 0.7529 - loss: 0.2155 - mae: 0.3616 - rmse: 0.4552 - smape: 0.7483 - val_ia: 0.2410 - val_loss: 0.7582 - val_mae: 0.6566 - val_rmse: 0.6995 - val_smape: 1.2121

Epoch 29/128

2292/2292 - 9s - 4ms/step - ia: 0.7558 - loss: 0.2116 - mae: 0.3573 - rmse: 0.4507 - smape: 0.7437 - val_ia: 0.2412 - val_loss: 0.7229 - val_mae: 0.6461 - val_rmse: 0.6893 - val_smape: 1.2149

Epoch 30/128

2292/2292 - 9s - 4ms/step - ia: 0.7578 - loss: 0.2085 - mae: 0.3542 - rmse: 0.4475 - smape: 0.7388 - val_ia: 0.2446 - val_loss: 0.6844 - val_mae: 0.6267 - val_rmse: 0.6706 - val_smape: 1.1879

Epoch 31/128

2292/2292 - 10s - 5ms/step - ia: 0.7600 - loss: 0.2054 - mae: 0.3519 - rmse: 0.4442 - smape: 0.7369 - val_ia: 0.2461 - val_loss: 0.6754 - val_mae: 0.6218 - val_rmse: 0.6660 - val_smape: 1.1856

Epoch 32/128

2292/2292 - 7s - 3ms/step - ia: 0.7612 - loss: 0.2039 - mae: 0.3502 - rmse: 0.4425 - smape: 0.7338 - val_ia: 0.2474 - val_loss: 0.6541 - val_mae: 0.6129 - val_rmse: 0.6576 - val_smape: 1.1766

Epoch 33/128

2292/2292 - 10s - 4ms/step - ia: 0.7621 - loss: 0.2022 - mae: 0.3489 - rmse: 0.4409 - smape: 0.7332 - val_ia: 0.2486 - val_loss: 0.6409 - val_mae: 0.6068 - val_rmse: 0.6520 - val_smape: 1.1600

Epoch 34/128

2292/2292 - 10s - 4ms/step - ia: 0.7642 - loss: 0.1986 - mae: 0.3454 - rmse: 0.4367 - smape: 0.7301 - val_ia: 0.2483 - val_loss: 0.6347 - val_mae: 0.6044 - val_rmse: 0.6500 - val_smape: 1.1669

Epoch 35/128

2292/2292 - 9s - 4ms/step - ia: 0.7653 - loss: 0.1968 - mae: 0.3443 - rmse: 0.4350 - smape: 0.7279 - val_ia: 0.2494 - val_loss: 0.6230 - val_mae: 0.5991 - val_rmse: 0.6456 - val_smape: 1.1531

Epoch 36/128

2292/2292 - 10s - 4ms/step - ia: 0.7681 - loss: 0.1939 - mae: 0.3408 - rmse: 0.4314 - smape: 0.7238 - val_ia: 0.2536 - val_loss: 0.5908 - val_mae: 0.5823 - val_rmse: 0.6288 - val_smape: 1.1317

Epoch 37/128

2292/2292 - 9s - 4ms/step - ia: 0.7689 - loss: 0.1910 - mae: 0.3392 - rmse: 0.4277 - smape: 0.7250 - val_ia: 0.2578 - val_loss: 0.5638 - val_mae: 0.5674 - val_rmse: 0.6146 - val_smape: 1.1078

Epoch 38/128

2292/2292 - 12s - 5ms/step - ia: 0.7708 - loss: 0.1888 - mae: 0.3365 - rmse: 0.4256 - smape: 0.7213 - val_ia: 0.2576 - val_loss: 0.5599 - val_mae: 0.5642 - val_rmse: 0.6121 - val_smape: 1.1091

Epoch 39/128

2292/2292 - 9s - 4ms/step - ia: 0.7712 - loss: 0.1891 - mae: 0.3365 - rmse: 0.4255 - smape: 0.7208 - val_ia: 0.2607 - val_loss: 0.5446 - val_mae: 0.5560 - val_rmse: 0.6047 - val_smape: 1.0890

Epoch 40/128

2292/2292 - 9s - 4ms/step - ia: 0.7735 - loss: 0.1852 - mae: 0.3336 - rmse: 0.4218 - smape: 0.7170 - val_ia: 0.2629 - val_loss: 0.5296 - val_mae: 0.5486 - val_rmse: 0.5970 - val_smape: 1.0815

Epoch 41/128

2292/2292 - 9s - 4ms/step - ia: 0.7740 - loss: 0.1841 - mae: 0.3324 - rmse: 0.4203 - smape: 0.7178 - val_ia: 0.2698 - val_loss: 0.5034 - val_mae: 0.5313 - val_rmse: 0.5808 - val_smape: 1.0495

Epoch 42/128

2292/2292 - 8s - 3ms/step - ia: 0.7758 - loss: 0.1821 - mae: 0.3303 - rmse: 0.4177 - smape: 0.7135 - val_ia: 0.2655 - val_loss: 0.5119 - val_mae: 0.5388 - val_rmse: 0.5882 - val_smape: 1.0652

Epoch 43/128

2292/2292 - 12s - 5ms/step - ia: 0.7789 - loss: 0.1787 - mae: 0.3264 - rmse: 0.4140 - smape: 0.7113 - val_ia: 0.2671 - val_loss: 0.5120 - val_mae: 0.5373 - val_rmse: 0.5864 - val_smape: 1.0566

Epoch 44/128

2292/2292 - 9s - 4ms/step - ia: 0.7770 - loss: 0.1794 - mae: 0.3278 - rmse: 0.4145 - smape: 0.7090 - val_ia: 0.2682 - val_loss: 0.5039 - val_mae: 0.5328 - val_rmse: 0.5831 - val_smape: 1.0472

Epoch 45/128

2292/2292 - 10s - 4ms/step - ia: 0.7780 - loss: 0.1783 - mae: 0.3268 - rmse: 0.4136 - smape: 0.7080 - val_ia: 0.2721 - val_loss: 0.4905 - val_mae: 0.5227 - val_rmse: 0.5744 - val_smape: 1.0315

Epoch 46/128

2292/2292 - 9s - 4ms/step - ia: 0.7807 - loss: 0.1766 - mae: 0.3243 - rmse: 0.4112 - smape: 0.7051 - val_ia: 0.2750 - val_loss: 0.4728 - val_mae: 0.5126 - val_rmse: 0.5645 - val_smape: 1.0187

Epoch 47/128

2292/2292 - 11s - 5ms/step - ia: 0.7819 - loss: 0.1725 - mae: 0.3207 - rmse: 0.4066 - smape: 0.7024 - val_ia: 0.2739 - val_loss: 0.4804 - val_mae: 0.5172 - val_rmse: 0.5689 - val_smape: 1.0247

Epoch 48/128

2292/2292 - 10s - 4ms/step - ia: 0.7812 - loss: 0.1747 - mae: 0.3227 - rmse: 0.4094 - smape: 0.7048 - val_ia: 0.2722 - val_loss: 0.4845 - val_mae: 0.5209 - val_rmse: 0.5726 - val_smape: 1.0273

Epoch 49/128

2292/2292 - 9s - 4ms/step - ia: 0.7828 - loss: 0.1721 - mae: 0.3203 - rmse: 0.4061 - smape: 0.7038 - val_ia: 0.2785 - val_loss: 0.4596 - val_mae: 0.5054 - val_rmse: 0.5575 - val_smape: 1.0025

Epoch 50/128

2292/2292 - 9s - 4ms/step - ia: 0.7847 - loss: 0.1704 - mae: 0.3186 - rmse: 0.4041 - smape: 0.7006 - val_ia: 0.2793 - val_loss: 0.4570 - val_mae: 0.5040 - val_rmse: 0.5554 - val_smape: 0.9987

Epoch 51/128

2292/2292 - 8s - 4ms/step - ia: 0.7838 - loss: 0.1705 - mae: 0.3185 - rmse: 0.4041 - smape: 0.7015 - val_ia: 0.2790 - val_loss: 0.4565 - val_mae: 0.5024 - val_rmse: 0.5542 - val_smape: 1.0052

Epoch 52/128

2292/2292 - 11s - 5ms/step - ia: 0.7859 - loss: 0.1680 - mae: 0.3163 - rmse: 0.4012 - smape: 0.6977 - val_ia: 0.2822 - val_loss: 0.4460 - val_mae: 0.4960 - val_rmse: 0.5481 - val_smape: 0.9869

Epoch 53/128

2292/2292 - 10s - 5ms/step - ia: 0.7860 - loss: 0.1667 - mae: 0.3157 - rmse: 0.3998 - smape: 0.6987 - val_ia: 0.2860 - val_loss: 0.4361 - val_mae: 0.4891 - val_rmse: 0.5413 - val_smape: 0.9796

Epoch 54/128

2292/2292 - 9s - 4ms/step - ia: 0.7868 - loss: 0.1665 - mae: 0.3144 - rmse: 0.3995 - smape: 0.6976 - val_ia: 0.2866 - val_loss: 0.4372 - val_mae: 0.4885 - val_rmse: 0.5409 - val_smape: 0.9780

Epoch 55/128

2292/2292 - 11s - 5ms/step - ia: 0.7865 - loss: 0.1660 - mae: 0.3141 - rmse: 0.3984 - smape: 0.6968 - val_ia: 0.2874 - val_loss: 0.4353 - val_mae: 0.4875 - val_rmse: 0.5398 - val_smape: 0.9694

Epoch 56/128

2292/2292 - 8s - 3ms/step - ia: 0.7873 - loss: 0.1647 - mae: 0.3134 - rmse: 0.3971 - smape: 0.6943 - val_ia: 0.2892 - val_loss: 0.4289 - val_mae: 0.4837 - val_rmse: 0.5361 - val_smape: 0.9634

Epoch 57/128

2292/2292 - 9s - 4ms/step - ia: 0.7893 - loss: 0.1630 - mae: 0.3111 - rmse: 0.3953 - smape: 0.6920 - val_ia: 0.2908 - val_loss: 0.4242 - val_mae: 0.4802 - val_rmse: 0.5326 - val_smape: 0.9555

Epoch 58/128

2292/2292 - 11s - 5ms/step - ia: 0.7903 - loss: 0.1623 - mae: 0.3107 - rmse: 0.3942 - smape: 0.6918 - val_ia: 0.2875 - val_loss: 0.4260 - val_mae: 0.4847 - val_rmse: 0.5375 - val_smape: 0.9585

Epoch 59/128

2292/2292 - 10s - 4ms/step - ia: 0.7895 - loss: 0.1619 - mae: 0.3100 - rmse: 0.3935 - smape: 0.6920 - val_ia: 0.2893 - val_loss: 0.4184 - val_mae: 0.4795 - val_rmse: 0.5306 - val_smape: 0.9605

Epoch 60/128

2292/2292 - 9s - 4ms/step - ia: 0.7919 - loss: 0.1589 - mae: 0.3074 - rmse: 0.3901 - smape: 0.6876 - val_ia: 0.2966 - val_loss: 0.3966 - val_mae: 0.4647 - val_rmse: 0.5166 - val_smape: 0.9336

Epoch 61/128

2292/2292 - 7s - 3ms/step - ia: 0.7912 - loss: 0.1589 - mae: 0.3084 - rmse: 0.3901 - smape: 0.6906 - val_ia: 0.2952 - val_loss: 0.4105 - val_mae: 0.4720 - val_rmse: 0.5237 - val_smape: 0.9386

Epoch 62/128

2292/2292 - 10s - 4ms/step - ia: 0.7916 - loss: 0.1587 - mae: 0.3072 - rmse: 0.3899 - smape: 0.6873 - val_ia: 0.2924 - val_loss: 0.4094 - val_mae: 0.4734 - val_rmse: 0.5243 - val_smape: 0.9471

Epoch 63/128

2292/2292 - 9s - 4ms/step - ia: 0.7924 - loss: 0.1587 - mae: 0.3069 - rmse: 0.3896 - smape: 0.6893 - val_ia: 0.3009 - val_loss: 0.3926 - val_mae: 0.4592 - val_rmse: 0.5116 - val_smape: 0.9234

Epoch 64/128

2292/2292 - 10s - 4ms/step - ia: 0.7934 - loss: 0.1575 - mae: 0.3058 - rmse: 0.3880 - smape: 0.6848 - val_ia: 0.2991 - val_loss: 0.3969 - val_mae: 0.4622 - val_rmse: 0.5144 - val_smape: 0.9269

Epoch 65/128

2292/2292 - 8s - 4ms/step - ia: 0.7937 - loss: 0.1560 - mae: 0.3046 - rmse: 0.3864 - smape: 0.6851 - val_ia: 0.3002 - val_loss: 0.3965 - val_mae: 0.4616 - val_rmse: 0.5145 - val_smape: 0.9224

Epoch 66/128

2292/2292 - 7s - 3ms/step - ia: 0.7939 - loss: 0.1555 - mae: 0.3035 - rmse: 0.3852 - smape: 0.6838 - val_ia: 0.2961 - val_loss: 0.4122 - val_mae: 0.4720 - val_rmse: 0.5235 - val_smape: 0.9368

Epoch 67/128

2292/2292 - 12s - 5ms/step - ia: 0.7960 - loss: 0.1539 - mae: 0.3023 - rmse: 0.3839 - smape: 0.6795 - val_ia: 0.2999 - val_loss: 0.4014 - val_mae: 0.4632 - val_rmse: 0.5161 - val_smape: 0.9244

Epoch 68/128

2292/2292 - 9s - 4ms/step - ia: 0.7960 - loss: 0.1540 - mae: 0.3017 - rmse: 0.3832 - smape: 0.6815 - val_ia: 0.2980 - val_loss: 0.3974 - val_mae: 0.4636 - val_rmse: 0.5157 - val_smape: 0.9321

Epoch 69/128

2292/2292 - 9s - 4ms/step - ia: 0.7952 - loss: 0.1537 - mae: 0.3028 - rmse: 0.3841 - smape: 0.6826 - val_ia: 0.3010 - val_loss: 0.3940 - val_mae: 0.4602 - val_rmse: 0.5117 - val_smape: 0.9221

Epoch 70/128

2292/2292 - 8s - 4ms/step - ia: 0.7978 - loss: 0.1515 - mae: 0.2999 - rmse: 0.3810 - smape: 0.6780 - val_ia: 0.2988 - val_loss: 0.3987 - val_mae: 0.4632 - val_rmse: 0.5154 - val_smape: 0.9298

Epoch 71/128

2292/2292 - 7s - 3ms/step - ia: 0.7970 - loss: 0.1517 - mae: 0.3002 - rmse: 0.3807 - smape: 0.6777 - val_ia: 0.3022 - val_loss: 0.3951 - val_mae: 0.4602 - val_rmse: 0.5129 - val_smape: 0.9157

Epoch 72/128

2292/2292 - 6s - 3ms/step - ia: 0.7989 - loss: 0.1504 - mae: 0.2984 - rmse: 0.3795 - smape: 0.6743 - val_ia: 0.3041 - val_loss: 0.3908 - val_mae: 0.4571 - val_rmse: 0.5088 - val_smape: 0.9130

Epoch 73/128

2292/2292 - 6s - 3ms/step - ia: 0.7994 - loss: 0.1491 - mae: 0.2969 - rmse: 0.3774 - smape: 0.6726 - val_ia: 0.3100 - val_loss: 0.3687 - val_mae: 0.4431 - val_rmse: 0.4953 - val_smape: 0.8946

Epoch 74/128

2292/2292 - 6s - 3ms/step - ia: 0.7992 - loss: 0.1496 - mae: 0.2980 - rmse: 0.3788 - smape: 0.6742 - val_ia: 0.3076 - val_loss: 0.3791 - val_mae: 0.4502 - val_rmse: 0.5019 - val_smape: 0.9040

Epoch 75/128

2292/2292 - 5s - 2ms/step - ia: 0.7985 - loss: 0.1502 - mae: 0.2991 - rmse: 0.3795 - smape: 0.6740 - val_ia: 0.3117 - val_loss: 0.3709 - val_mae: 0.4431 - val_rmse: 0.4947 - val_smape: 0.8933

Epoch 76/128

2292/2292 - 5s - 2ms/step - ia: 0.8001 - loss: 0.1475 - mae: 0.2959 - rmse: 0.3757 - smape: 0.6709 - val_ia: 0.3064 - val_loss: 0.3911 - val_mae: 0.4571 - val_rmse: 0.5082 - val_smape: 0.9122

Epoch 77/128

2292/2292 - 14s - 6ms/step - ia: 0.8009 - loss: 0.1463 - mae: 0.2955 - rmse: 0.3743 - smape: 0.6690 - val_ia: 0.3093 - val_loss: 0.3825 - val_mae: 0.4494 - val_rmse: 0.5011 - val_smape: 0.9018

Epoch 78/128

2292/2292 - 10s - 5ms/step - ia: 0.8011 - loss: 0.1466 - mae: 0.2948 - rmse: 0.3745 - smape: 0.6727 - val_ia: 0.3067 - val_loss: 0.3852 - val_mae: 0.4528 - val_rmse: 0.5042 - val_smape: 0.9118

Epoch 79/128

2292/2292 - 10s - 4ms/step - ia: 0.7997 - loss: 0.1483 - mae: 0.2968 - rmse: 0.3764 - smape: 0.6739 - val_ia: 0.3135 - val_loss: 0.3661 - val_mae: 0.4398 - val_rmse: 0.4911 - val_smape: 0.8936

Epoch 80/128

2292/2292 - 11s - 5ms/step - ia: 0.8013 - loss: 0.1468 - mae: 0.2947 - rmse: 0.3743 - smape: 0.6689 - val_ia: 0.3110 - val_loss: 0.3760 - val_mae: 0.4464 - val_rmse: 0.4980 - val_smape: 0.8988

Epoch 81/128

2292/2292 - 8s - 4ms/step - ia: 0.8023 - loss: 0.1452 - mae: 0.2932 - rmse: 0.3731 - smape: 0.6659 - val_ia: 0.3121 - val_loss: 0.3791 - val_mae: 0.4462 - val_rmse: 0.4982 - val_smape: 0.8961

Epoch 82/128

2292/2292 - 12s - 5ms/step - ia: 0.8030 - loss: 0.1442 - mae: 0.2927 - rmse: 0.3714 - smape: 0.6682 - val_ia: 0.3098 - val_loss: 0.3796 - val_mae: 0.4490 - val_rmse: 0.4998 - val_smape: 0.9038

Epoch 83/128

2292/2292 - 11s - 5ms/step - ia: 0.8036 - loss: 0.1437 - mae: 0.2920 - rmse: 0.3702 - smape: 0.6654 - val_ia: 0.3082 - val_loss: 0.3798 - val_mae: 0.4504 - val_rmse: 0.5009 - val_smape: 0.9102

Epoch 84/128

2292/2292 - 9s - 4ms/step - ia: 0.8046 - loss: 0.1425 - mae: 0.2909 - rmse: 0.3689 - smape: 0.6671 - val_ia: 0.3115 - val_loss: 0.3752 - val_mae: 0.4457 - val_rmse: 0.4971 - val_smape: 0.8982

Epoch 85/128

2292/2292 - 9s - 4ms/step - ia: 0.8038 - loss: 0.1435 - mae: 0.2914 - rmse: 0.3702 - smape: 0.6638 - val_ia: 0.3130 - val_loss: 0.3691 - val_mae: 0.4409 - val_rmse: 0.4928 - val_smape: 0.8912

Epoch 86/128

2292/2292 - 9s - 4ms/step - ia: 0.8052 - loss: 0.1412 - mae: 0.2899 - rmse: 0.3674 - smape: 0.6638 - val_ia: 0.3126 - val_loss: 0.3690 - val_mae: 0.4416 - val_rmse: 0.4929 - val_smape: 0.8898

Epoch 87/128

2292/2292 - 10s - 4ms/step - ia: 0.8047 - loss: 0.1415 - mae: 0.2899 - rmse: 0.3680 - smape: 0.6618 - val_ia: 0.3133 - val_loss: 0.3657 - val_mae: 0.4404 - val_rmse: 0.4914 - val_smape: 0.8911

Epoch 88/128

2292/2292 - 9s - 4ms/step - ia: 0.8059 - loss: 0.1399 - mae: 0.2889 - rmse: 0.3660 - smape: 0.6643 - val_ia: 0.3150 - val_loss: 0.3632 - val_mae: 0.4380 - val_rmse: 0.4892 - val_smape: 0.8864

Epoch 89/128

2292/2292 - 9s - 4ms/step - ia: 0.8069 - loss: 0.1385 - mae: 0.2866 - rmse: 0.3635 - smape: 0.6615 - val_ia: 0.3148 - val_loss: 0.3661 - val_mae: 0.4390 - val_rmse: 0.4909 - val_smape: 0.8888

Epoch 90/128

2292/2292 - 9s - 4ms/step - ia: 0.8065 - loss: 0.1392 - mae: 0.2875 - rmse: 0.3650 - smape: 0.6593 - val_ia: 0.3138 - val_loss: 0.3723 - val_mae: 0.4435 - val_rmse: 0.4941 - val_smape: 0.8960

Epoch 91/128

2292/2292 - 8s - 3ms/step - ia: 0.8066 - loss: 0.1394 - mae: 0.2877 - rmse: 0.3655 - smape: 0.6602 - val_ia: 0.3127 - val_loss: 0.3732 - val_mae: 0.4447 - val_rmse: 0.4954 - val_smape: 0.9007

Epoch 92/128

2292/2292 - 8s - 4ms/step - ia: 0.8060 - loss: 0.1393 - mae: 0.2879 - rmse: 0.3652 - smape: 0.6611 - val_ia: 0.3143 - val_loss: 0.3755 - val_mae: 0.4453 - val_rmse: 0.4953 - val_smape: 0.8985

Epoch 93/128

2292/2292 - 5s - 2ms/step - ia: 0.8069 - loss: 0.1379 - mae: 0.2865 - rmse: 0.3633 - smape: 0.6583 - val_ia: 0.3182 - val_loss: 0.3562 - val_mae: 0.4338 - val_rmse: 0.4841 - val_smape: 0.8833

Epoch 94/128

2292/2292 - 5s - 2ms/step - ia: 0.8071 - loss: 0.1389 - mae: 0.2871 - rmse: 0.3645 - smape: 0.6602 - val_ia: 0.3161 - val_loss: 0.3626 - val_mae: 0.4381 - val_rmse: 0.4883 - val_smape: 0.8960

Epoch 95/128

2292/2292 - 5s - 2ms/step - ia: 0.8086 - loss: 0.1378 - mae: 0.2860 - rmse: 0.3632 - smape: 0.6584 - val_ia: 0.3209 - val_loss: 0.3503 - val_mae: 0.4299 - val_rmse: 0.4802 - val_smape: 0.8765

Epoch 96/128

2292/2292 - 10s - 4ms/step - ia: 0.8095 - loss: 0.1363 - mae: 0.2838 - rmse: 0.3610 - smape: 0.6547 - val_ia: 0.3171 - val_loss: 0.3572 - val_mae: 0.4358 - val_rmse: 0.4858 - val_smape: 0.8895

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

4584/4584 - 21s - 5ms/step - ia: 0.2430 - loss: 2.4719 - mae: 1.2101 - rmse: 1.4994 - smape: 1.6221 - val_ia: 0.1148 - val_loss: 2.0896 - val_mae: 1.2062 - val_rmse: 1.2217 - val_smape: 1.4669

Epoch 2/128

4584/4584 - 14s - 3ms/step - ia: 0.2511 - loss: 2.1199 - mae: 1.1362 - rmse: 1.3955 - smape: 1.6106 - val_ia: 0.1200 - val_loss: 1.8349 - val_mae: 1.1266 - val_rmse: 1.1426 - val_smape: 1.4572

Epoch 3/128

4584/4584 - 26s - 6ms/step - ia: 0.2549 - loss: 1.8949 - mae: 1.0820 - rmse: 1.3219 - smape: 1.6103 - val_ia: 0.1270 - val_loss: 1.6406 - val_mae: 1.0592 - val_rmse: 1.0758 - val_smape: 1.4462

Epoch 4/128

4584/4584 - 13s - 3ms/step - ia: 0.2625 - loss: 1.7119 - mae: 1.0338 - rmse: 1.2593 - smape: 1.6003 - val_ia: 0.1325 - val_loss: 1.4962 - val_mae: 1.0054 - val_rmse: 1.0224 - val_smape: 1.4366

Epoch 5/128

4584/4584 - 13s - 3ms/step - ia: 0.2658 - loss: 1.5993 - mae: 0.9999 - rmse: 1.2180 - smape: 1.5956 - val_ia: 0.1366 - val_loss: 1.3840 - val_mae: 0.9620 - val_rmse: 0.9795 - val_smape: 1.4285

Epoch 6/128

4584/4584 - 14s - 3ms/step - ia: 0.2704 - loss: 1.4986 - mae: 0.9715 - rmse: 1.1810 - smape: 1.5875 - val_ia: 0.1403 - val_loss: 1.2932 - val_mae: 0.9262 - val_rmse: 0.9439 - val_smape: 1.4243

Epoch 7/128

4584/4584 - 11s - 2ms/step - ia: 0.2693 - loss: 1.4204 - mae: 0.9492 - rmse: 1.1501 - smape: 1.5895 - val_ia: 0.1427 - val_loss: 1.2229 - val_mae: 0.8980 - val_rmse: 0.9161 - val_smape: 1.4211

Epoch 8/128

4584/4584 - 15s - 3ms/step - ia: 0.2734 - loss: 1.3627 - mae: 0.9307 - rmse: 1.1273 - smape: 1.5856 - val_ia: 0.1458 - val_loss: 1.1669 - val_mae: 0.8753 - val_rmse: 0.8936 - val_smape: 1.4175

Epoch 9/128

4584/4584 - 13s - 3ms/step - ia: 0.2748 - loss: 1.3017 - mae: 0.9127 - rmse: 1.1035 - smape: 1.5840 - val_ia: 0.1463 - val_loss: 1.1212 - val_mae: 0.8569 - val_rmse: 0.8754 - val_smape: 1.4150

Epoch 10/128

4584/4584 - 17s - 4ms/step - ia: 0.2728 - loss: 1.2624 - mae: 0.9031 - rmse: 1.0886 - smape: 1.5875 - val_ia: 0.1467 - val_loss: 1.0825 - val_mae: 0.8414 - val_rmse: 0.8601 - val_smape: 1.4136

Epoch 11/128

4584/4584 - 18s - 4ms/step - ia: 0.2768 - loss: 1.2302 - mae: 0.8899 - rmse: 1.0734 - smape: 1.5827 - val_ia: 0.1462 - val_loss: 1.0522 - val_mae: 0.8296 - val_rmse: 0.8482 - val_smape: 1.4137

Epoch 12/128

4584/4584 - 11s - 2ms/step - ia: 0.2738 - loss: 1.1960 - mae: 0.8815 - rmse: 1.0602 - smape: 1.5867 - val_ia: 0.1462 - val_loss: 1.0270 - val_mae: 0.8197 - val_rmse: 0.8383 - val_smape: 1.4145

Epoch 13/128

4584/4584 - 23s - 5ms/step - ia: 0.2793 - loss: 1.1636 - mae: 0.8703 - rmse: 1.0472 - smape: 1.5776 - val_ia: 0.1461 - val_loss: 1.0042 - val_mae: 0.8108 - val_rmse: 0.8294 - val_smape: 1.4160

Epoch 14/128

4584/4584 - 19s - 4ms/step - ia: 0.2763 - loss: 1.1421 - mae: 0.8648 - rmse: 1.0385 - smape: 1.5834 - val_ia: 0.1459 - val_loss: 0.9843 - val_mae: 0.8030 - val_rmse: 0.8215 - val_smape: 1.4169

Epoch 15/128

4584/4584 - 12s - 3ms/step - ia: 0.2773 - loss: 1.1224 - mae: 0.8594 - rmse: 1.0298 - smape: 1.5855 - val_ia: 0.1462 - val_loss: 0.9679 - val_mae: 0.7966 - val_rmse: 0.8151 - val_smape: 1.4180

Epoch 16/128

4584/4584 - 13s - 3ms/step - ia: 0.2761 - loss: 1.1080 - mae: 0.8548 - rmse: 1.0246 - smape: 1.5893 - val_ia: 0.1466 - val_loss: 0.9544 - val_mae: 0.7915 - val_rmse: 0.8098 - val_smape: 1.4189

Epoch 17/128

4584/4584 - 13s - 3ms/step - ia: 0.2778 - loss: 1.0813 - mae: 0.8474 - rmse: 1.0127 - smape: 1.5823 - val_ia: 0.1467 - val_loss: 0.9414 - val_mae: 0.7864 - val_rmse: 0.8047 - val_smape: 1.4193

Epoch 18/128

4584/4584 - 13s - 3ms/step - ia: 0.2785 - loss: 1.0649 - mae: 0.8430 - rmse: 1.0059 - smape: 1.5826 - val_ia: 0.1466 - val_loss: 0.9300 - val_mae: 0.7819 - val_rmse: 0.8002 - val_smape: 1.4191

Epoch 19/128

4584/4584 - 13s - 3ms/step - ia: 0.2776 - loss: 1.0538 - mae: 0.8401 - rmse: 1.0015 - smape: 1.5855 - val_ia: 0.1464 - val_loss: 0.9207 - val_mae: 0.7784 - val_rmse: 0.7966 - val_smape: 1.4189

Epoch 20/128

4584/4584 - 13s - 3ms/step - ia: 0.2789 - loss: 1.0372 - mae: 0.8349 - rmse: 0.9939 - smape: 1.5805 - val_ia: 0.1465 - val_loss: 0.9114 - val_mae: 0.7748 - val_rmse: 0.7929 - val_smape: 1.4179

Epoch 21/128

4584/4584 - 13s - 3ms/step - ia: 0.2780 - loss: 1.0309 - mae: 0.8319 - rmse: 0.9903 - smape: 1.5806 - val_ia: 0.1466 - val_loss: 0.9029 - val_mae: 0.7715 - val_rmse: 0.7896 - val_smape: 1.4172

Epoch 22/128

4584/4584 - 12s - 3ms/step - ia: 0.2795 - loss: 1.0170 - mae: 0.8273 - rmse: 0.9849 - smape: 1.5785 - val_ia: 0.1465 - val_loss: 0.8960 - val_mae: 0.7690 - val_rmse: 0.7870 - val_smape: 1.4165

Epoch 23/128

4584/4584 - 12s - 3ms/step - ia: 0.2807 - loss: 1.0095 - mae: 0.8258 - rmse: 0.9817 - smape: 1.5734 - val_ia: 0.1465 - val_loss: 0.8898 - val_mae: 0.7667 - val_rmse: 0.7847 - val_smape: 1.4158

Epoch 24/128

4584/4584 - 21s - 5ms/step - ia: 0.2830 - loss: 0.9972 - mae: 0.8197 - rmse: 0.9757 - smape: 1.5695 - val_ia: 0.1463 - val_loss: 0.8851 - val_mae: 0.7651 - val_rmse: 0.7831 - val_smape: 1.4149

Epoch 25/128

4584/4584 - 12s - 3ms/step - ia: 0.2828 - loss: 0.9916 - mae: 0.8188 - rmse: 0.9732 - smape: 1.5708 - val_ia: 0.1460 - val_loss: 0.8806 - val_mae: 0.7636 - val_rmse: 0.7815 - val_smape: 1.4147

Epoch 26/128

4584/4584 - 20s - 4ms/step - ia: 0.2836 - loss: 0.9868 - mae: 0.8161 - rmse: 0.9712 - smape: 1.5665 - val_ia: 0.1458 - val_loss: 0.8765 - val_mae: 0.7622 - val_rmse: 0.7801 - val_smape: 1.4149

Epoch 27/128

4584/4584 - 12s - 3ms/step - ia: 0.2883 - loss: 0.9734 - mae: 0.8113 - rmse: 0.9639 - smape: 1.5630 - val_ia: 0.1454 - val_loss: 0.8734 - val_mae: 0.7613 - val_rmse: 0.7792 - val_smape: 1.4147

Epoch 28/128

4584/4584 - 12s - 3ms/step - ia: 0.2843 - loss: 0.9757 - mae: 0.8132 - rmse: 0.9657 - smape: 1.5670 - val_ia: 0.1452 - val_loss: 0.8713 - val_mae: 0.7608 - val_rmse: 0.7786 - val_smape: 1.4147

Epoch 29/128

4584/4584 - 11s - 2ms/step - ia: 0.2836 - loss: 0.9667 - mae: 0.8092 - rmse: 0.9608 - smape: 1.5647 - val_ia: 0.1451 - val_loss: 0.8694 - val_mae: 0.7603 - val_rmse: 0.7780 - val_smape: 1.4145

Epoch 30/128

4584/4584 - 21s - 5ms/step - ia: 0.2865 - loss: 0.9609 - mae: 0.8083 - rmse: 0.9586 - smape: 1.5662 - val_ia: 0.1449 - val_loss: 0.8668 - val_mae: 0.7595 - val_rmse: 0.7772 - val_smape: 1.4139

Epoch 31/128

4584/4584 - 12s - 3ms/step - ia: 0.2859 - loss: 0.9592 - mae: 0.8078 - rmse: 0.9577 - smape: 1.5642 - val_ia: 0.1447 - val_loss: 0.8649 - val_mae: 0.7590 - val_rmse: 0.7767 - val_smape: 1.4132

Epoch 32/128

4584/4584 - 12s - 3ms/step - ia: 0.2888 - loss: 0.9491 - mae: 0.8035 - rmse: 0.9527 - smape: 1.5577 - val_ia: 0.1445 - val_loss: 0.8644 - val_mae: 0.7590 - val_rmse: 0.7767 - val_smape: 1.4128

Epoch 33/128

4584/4584 - 11s - 2ms/step - ia: 0.2867 - loss: 0.9453 - mae: 0.8038 - rmse: 0.9519 - smape: 1.5609 - val_ia: 0.1444 - val_loss: 0.8629 - val_mae: 0.7587 - val_rmse: 0.7764 - val_smape: 1.4123

Epoch 34/128

4584/4584 - 12s - 3ms/step - ia: 0.2903 - loss: 0.9408 - mae: 0.8004 - rmse: 0.9486 - smape: 1.5532 - val_ia: 0.1443 - val_loss: 0.8622 - val_mae: 0.7586 - val_rmse: 0.7763 - val_smape: 1.4121

Epoch 35/128

4584/4584 - 12s - 3ms/step - ia: 0.2911 - loss: 0.9451 - mae: 0.8023 - rmse: 0.9503 - smape: 1.5544 - val_ia: 0.1443 - val_loss: 0.8616 - val_mae: 0.7585 - val_rmse: 0.7762 - val_smape: 1.4123

Epoch 36/128

4584/4584 - 20s - 4ms/step - ia: 0.2907 - loss: 0.9382 - mae: 0.7980 - rmse: 0.9465 - smape: 1.5506 - val_ia: 0.1441 - val_loss: 0.8611 - val_mae: 0.7586 - val_rmse: 0.7763 - val_smape: 1.4125

Epoch 37/128

4584/4584 - 11s - 2ms/step - ia: 0.2906 - loss: 0.9317 - mae: 0.7969 - rmse: 0.9446 - smape: 1.5484 - val_ia: 0.1439 - val_loss: 0.8616 - val_mae: 0.7591 - val_rmse: 0.7768 - val_smape: 1.4122

Epoch 38/128

4584/4584 - 21s - 4ms/step - ia: 0.2938 - loss: 0.9261 - mae: 0.7947 - rmse: 0.9416 - smape: 1.5517 - val_ia: 0.1437 - val_loss: 0.8621 - val_mae: 0.7596 - val_rmse: 0.7772 - val_smape: 1.4114

Epoch 39/128

4584/4584 - 10s - 2ms/step - ia: 0.2932 - loss: 0.9248 - mae: 0.7933 - rmse: 0.9409 - smape: 1.5421 - val_ia: 0.1436 - val_loss: 0.8625 - val_mae: 0.7599 - val_rmse: 0.7776 - val_smape: 1.4115

Epoch 40/128

4584/4584 - 13s - 3ms/step - ia: 0.2959 - loss: 0.9210 - mae: 0.7907 - rmse: 0.9382 - smape: 1.5411 - val_ia: 0.1437 - val_loss: 0.8615 - val_mae: 0.7596 - val_rmse: 0.7773 - val_smape: 1.4110

Epoch 41/128

4584/4584 - 13s - 3ms/step - ia: 0.2973 - loss: 0.9180 - mae: 0.7903 - rmse: 0.9365 - smape: 1.5411 - val_ia: 0.1435 - val_loss: 0.8613 - val_mae: 0.7597 - val_rmse: 0.7774 - val_smape: 1.4102

Epoch 42/128

4584/4584 - 12s - 3ms/step - ia: 0.2964 - loss: 0.9160 - mae: 0.7897 - rmse: 0.9362 - smape: 1.5396 - val_ia: 0.1434 - val_loss: 0.8610 - val_mae: 0.7597 - val_rmse: 0.7774 - val_smape: 1.4094

Epoch 43/128

4584/4584 - 10s - 2ms/step - ia: 0.2956 - loss: 0.9170 - mae: 0.7908 - rmse: 0.9374 - smape: 1.5405 - val_ia: 0.1434 - val_loss: 0.8603 - val_mae: 0.7595 - val_rmse: 0.7772 - val_smape: 1.4089

Epoch 44/128

4584/4584 - 12s - 3ms/step - ia: 0.2978 - loss: 0.9098 - mae: 0.7880 - rmse: 0.9327 - smape: 1.5334 - val_ia: 0.1433 - val_loss: 0.8603 - val_mae: 0.7595 - val_rmse: 0.7772 - val_smape: 1.4087

Epoch 45/128

4584/4584 - 12s - 3ms/step - ia: 0.2986 - loss: 0.9081 - mae: 0.7871 - rmse: 0.9324 - smape: 1.5347 - val_ia: 0.1434 - val_loss: 0.8591 - val_mae: 0.7590 - val_rmse: 0.7768 - val_smape: 1.4078

Epoch 46/128

4584/4584 - 13s - 3ms/step - ia: 0.2997 - loss: 0.9089 - mae: 0.7870 - rmse: 0.9331 - smape: 1.5350 - val_ia: 0.1435 - val_loss: 0.8583 - val_mae: 0.7587 - val_rmse: 0.7764 - val_smape: 1.4075

Epoch 47/128

4584/4584 - 12s - 3ms/step - ia: 0.3032 - loss: 0.9042 - mae: 0.7837 - rmse: 0.9302 - smape: 1.5272 - val_ia: 0.1435 - val_loss: 0.8585 - val_mae: 0.7588 - val_rmse: 0.7766 - val_smape: 1.4070

Epoch 48/128

4584/4584 - 13s - 3ms/step - ia: 0.2980 - loss: 0.9024 - mae: 0.7840 - rmse: 0.9303 - smape: 1.5283 - val_ia: 0.1435 - val_loss: 0.8587 - val_mae: 0.7588 - val_rmse: 0.7766 - val_smape: 1.4063

Epoch 49/128

4584/4584 - 20s - 4ms/step - ia: 0.3023 - loss: 0.8978 - mae: 0.7816 - rmse: 0.9269 - smape: 1.5263 - val_ia: 0.1436 - val_loss: 0.8581 - val_mae: 0.7586 - val_rmse: 0.7764 - val_smape: 1.4055

Epoch 50/128

4584/4584 - 12s - 3ms/step - ia: 0.3030 - loss: 0.9007 - mae: 0.7834 - rmse: 0.9283 - smape: 1.5272 - val_ia: 0.1438 - val_loss: 0.8561 - val_mae: 0.7577 - val_rmse: 0.7755 - val_smape: 1.4050

Epoch 51/128

4584/4584 - 21s - 5ms/step - ia: 0.3060 - loss: 0.8935 - mae: 0.7807 - rmse: 0.9247 - smape: 1.5258 - val_ia: 0.1439 - val_loss: 0.8550 - val_mae: 0.7572 - val_rmse: 0.7750 - val_smape: 1.4045

Epoch 52/128

4584/4584 - 12s - 3ms/step - ia: 0.3031 - loss: 0.8959 - mae: 0.7814 - rmse: 0.9254 - smape: 1.5232 - val_ia: 0.1441 - val_loss: 0.8545 - val_mae: 0.7569 - val_rmse: 0.7746 - val_smape: 1.4041

Epoch 53/128

4584/4584 - 9s - 2ms/step - ia: 0.3012 - loss: 0.8937 - mae: 0.7810 - rmse: 0.9250 - smape: 1.5233 - val_ia: 0.1441 - val_loss: 0.8540 - val_mae: 0.7567 - val_rmse: 0.7745 - val_smape: 1.4035

Epoch 54/128

4584/4584 - 11s - 2ms/step - ia: 0.3058 - loss: 0.8898 - mae: 0.7789 - rmse: 0.9235 - smape: 1.5219 - val_ia: 0.1440 - val_loss: 0.8552 - val_mae: 0.7572 - val_rmse: 0.7750 - val_smape: 1.4025

Epoch 55/128

4584/4584 - 12s - 3ms/step - ia: 0.3041 - loss: 0.8899 - mae: 0.7787 - rmse: 0.9228 - smape: 1.5167 - val_ia: 0.1441 - val_loss: 0.8548 - val_mae: 0.7570 - val_rmse: 0.7748 - val_smape: 1.4020

Epoch 56/128

4584/4584 - 12s - 3ms/step - ia: 0.3042 - loss: 0.8917 - mae: 0.7795 - rmse: 0.9242 - smape: 1.5187 - val_ia: 0.1442 - val_loss: 0.8530 - val_mae: 0.7561 - val_rmse: 0.7739 - val_smape: 1.4007

Epoch 57/128

4584/4584 - 11s - 2ms/step - ia: 0.3058 - loss: 0.8875 - mae: 0.7774 - rmse: 0.9213 - smape: 1.5160 - val_ia: 0.1444 - val_loss: 0.8514 - val_mae: 0.7555 - val_rmse: 0.7732 - val_smape: 1.4005

Epoch 58/128

4584/4584 - 21s - 5ms/step - ia: 0.3095 - loss: 0.8797 - mae: 0.7749 - rmse: 0.9182 - smape: 1.5114 - val_ia: 0.1444 - val_loss: 0.8524 - val_mae: 0.7558 - val_rmse: 0.7735 - val_smape: 1.3993

Epoch 59/128

4584/4584 - 13s - 3ms/step - ia: 0.3085 - loss: 0.8852 - mae: 0.7761 - rmse: 0.9200 - smape: 1.5098 - val_ia: 0.1446 - val_loss: 0.8511 - val_mae: 0.7552 - val_rmse: 0.7729 - val_smape: 1.3994

Epoch 60/128

4584/4584 - 11s - 2ms/step - ia: 0.3071 - loss: 0.8812 - mae: 0.7746 - rmse: 0.9193 - smape: 1.5096 - val_ia: 0.1446 - val_loss: 0.8510 - val_mae: 0.7551 - val_rmse: 0.7728 - val_smape: 1.3987

Epoch 61/128

4584/4584 - 12s - 3ms/step - ia: 0.3093 - loss: 0.8759 - mae: 0.7717 - rmse: 0.9156 - smape: 1.5038 - val_ia: 0.1445 - val_loss: 0.8523 - val_mae: 0.7556 - val_rmse: 0.7733 - val_smape: 1.3967

Epoch 62/128

4584/4584 - 21s - 5ms/step - ia: 0.3116 - loss: 0.8784 - mae: 0.7725 - rmse: 0.9174 - smape: 1.5019 - val_ia: 0.1446 - val_loss: 0.8525 - val_mae: 0.7556 - val_rmse: 0.7733 - val_smape: 1.3961

Epoch 63/128

4584/4584 - 23s - 5ms/step - ia: 0.3095 - loss: 0.8802 - mae: 0.7741 - rmse: 0.9179 - smape: 1.5061 - val_ia: 0.1449 - val_loss: 0.8507 - val_mae: 0.7547 - val_rmse: 0.7724 - val_smape: 1.3953

Epoch 64/128

4584/4584 - 13s - 3ms/step - ia: 0.3103 - loss: 0.8803 - mae: 0.7741 - rmse: 0.9184 - smape: 1.5026 - val_ia: 0.1450 - val_loss: 0.8500 - val_mae: 0.7544 - val_rmse: 0.7720 - val_smape: 1.3952

Epoch 65/128

4584/4584 - 21s - 5ms/step - ia: 0.3116 - loss: 0.8729 - mae: 0.7715 - rmse: 0.9139 - smape: 1.4986 - val_ia: 0.1451 - val_loss: 0.8497 - val_mae: 0.7542 - val_rmse: 0.7719 - val_smape: 1.3948

Epoch 66/128

4584/4584 - 14s - 3ms/step - ia: 0.3115 - loss: 0.8773 - mae: 0.7720 - rmse: 0.9162 - smape: 1.4990 - val_ia: 0.1453 - val_loss: 0.8488 - val_mae: 0.7538 - val_rmse: 0.7714 - val_smape: 1.3949

Epoch 67/128

4584/4584 - 13s - 3ms/step - ia: 0.3123 - loss: 0.8741 - mae: 0.7713 - rmse: 0.9146 - smape: 1.4967 - val_ia: 0.1454 - val_loss: 0.8480 - val_mae: 0.7534 - val_rmse: 0.7710 - val_smape: 1.3950

Epoch 68/128

4584/4584 - 20s - 4ms/step - ia: 0.3128 - loss: 0.8740 - mae: 0.7704 - rmse: 0.9149 - smape: 1.4960 - val_ia: 0.1455 - val_loss: 0.8474 - val_mae: 0.7531 - val_rmse: 0.7708 - val_smape: 1.3943

Epoch 69/128

4584/4584 - 11s - 2ms/step - ia: 0.3151 - loss: 0.8703 - mae: 0.7683 - rmse: 0.9131 - smape: 1.4919 - val_ia: 0.1456 - val_loss: 0.8470 - val_mae: 0.7529 - val_rmse: 0.7705 - val_smape: 1.3933

Epoch 70/128

4584/4584 - 13s - 3ms/step - ia: 0.3172 - loss: 0.8647 - mae: 0.7668 - rmse: 0.9101 - smape: 1.4849 - val_ia: 0.1457 - val_loss: 0.8471 - val_mae: 0.7528 - val_rmse: 0.7705 - val_smape: 1.3921

Epoch 71/128

4584/4584 - 13s - 3ms/step - ia: 0.3157 - loss: 0.8690 - mae: 0.7683 - rmse: 0.9118 - smape: 1.4890 - val_ia: 0.1458 - val_loss: 0.8468 - val_mae: 0.7527 - val_rmse: 0.7703 - val_smape: 1.3919

Epoch 72/128

4584/4584 - 12s - 3ms/step - ia: 0.3191 - loss: 0.8647 - mae: 0.7665 - rmse: 0.9099 - smape: 1.4852 - val_ia: 0.1458 - val_loss: 0.8479 - val_mae: 0.7531 - val_rmse: 0.7707 - val_smape: 1.3916

Epoch 73/128

4584/4584 - 12s - 3ms/step - ia: 0.3182 - loss: 0.8680 - mae: 0.7678 - rmse: 0.9120 - smape: 1.4845 - val_ia: 0.1458 - val_loss: 0.8488 - val_mae: 0.7534 - val_rmse: 0.7711 - val_smape: 1.3915

Epoch 74/128

4584/4584 - 11s - 2ms/step - ia: 0.3186 - loss: 0.8654 - mae: 0.7667 - rmse: 0.9098 - smape: 1.4839 - val_ia: 0.1460 - val_loss: 0.8487 - val_mae: 0.7532 - val_rmse: 0.7709 - val_smape: 1.3904

Epoch 75/128

4584/4584 - 13s - 3ms/step - ia: 0.3199 - loss: 0.8643 - mae: 0.7654 - rmse: 0.9098 - smape: 1.4770 - val_ia: 0.1461 - val_loss: 0.8484 - val_mae: 0.7531 - val_rmse: 0.7707 - val_smape: 1.3904

Epoch 76/128

4584/4584 - 12s - 3ms/step - ia: 0.3172 - loss: 0.8648 - mae: 0.7672 - rmse: 0.9098 - smape: 1.4844 - val_ia: 0.1461 - val_loss: 0.8484 - val_mae: 0.7531 - val_rmse: 0.7707 - val_smape: 1.3902

Epoch 77/128

4584/4584 - 13s - 3ms/step - ia: 0.3179 - loss: 0.8638 - mae: 0.7661 - rmse: 0.9094 - smape: 1.4779 - val_ia: 0.1463 - val_loss: 0.8481 - val_mae: 0.7528 - val_rmse: 0.7704 - val_smape: 1.3889

Epoch 78/128

4584/4584 - 12s - 3ms/step - ia: 0.3192 - loss: 0.8554 - mae: 0.7621 - rmse: 0.9046 - smape: 1.4757 - val_ia: 0.1463 - val_loss: 0.8484 - val_mae: 0.7528 - val_rmse: 0.7705 - val_smape: 1.3878

Epoch 79/128

4584/4584 - 21s - 5ms/step - ia: 0.3213 - loss: 0.8555 - mae: 0.7620 - rmse: 0.9046 - smape: 1.4700 - val_ia: 0.1463 - val_loss: 0.8482 - val_mae: 0.7528 - val_rmse: 0.7704 - val_smape: 1.3881

Epoch 80/128

4584/4584 - 17s - 4ms/step - ia: 0.3217 - loss: 0.8566 - mae: 0.7628 - rmse: 0.9052 - smape: 1.4707 - val_ia: 0.1465 - val_loss: 0.8484 - val_mae: 0.7527 - val_rmse: 0.7704 - val_smape: 1.3873

Epoch 81/128

4584/4584 - 14s - 3ms/step - ia: 0.3212 - loss: 0.8577 - mae: 0.7626 - rmse: 0.9060 - smape: 1.4695 - val_ia: 0.1466 - val_loss: 0.8490 - val_mae: 0.7530 - val_rmse: 0.7706 - val_smape: 1.3880

Epoch 82/128

4584/4584 - 13s - 3ms/step - ia: 0.3251 - loss: 0.8533 - mae: 0.7606 - rmse: 0.9031 - smape: 1.4657 - val_ia: 0.1467 - val_loss: 0.8489 - val_mae: 0.7529 - val_rmse: 0.7706 - val_smape: 1.3878

Epoch 83/128

4584/4584 - 14s - 3ms/step - ia: 0.3254 - loss: 0.8518 - mae: 0.7599 - rmse: 0.9029 - smape: 1.4626 - val_ia: 0.1466 - val_loss: 0.8500 - val_mae: 0.7533 - val_rmse: 0.7709 - val_smape: 1.3869

Epoch 84/128

4584/4584 - 15s - 3ms/step - ia: 0.3246 - loss: 0.8549 - mae: 0.7607 - rmse: 0.9042 - smape: 1.4626 - val_ia: 0.1469 - val_loss: 0.8494 - val_mae: 0.7529 - val_rmse: 0.7705 - val_smape: 1.3861

Epoch 85/128

4584/4584 - 12s - 3ms/step - ia: 0.3273 - loss: 0.8529 - mae: 0.7611 - rmse: 0.9032 - smape: 1.4653 - val_ia: 0.1471 - val_loss: 0.8487 - val_mae: 0.7525 - val_rmse: 0.7702 - val_smape: 1.3861

Epoch 86/128

4584/4584 - 12s - 3ms/step - ia: 0.3269 - loss: 0.8507 - mae: 0.7590 - rmse: 0.9022 - smape: 1.4611 - val_ia: 0.1472 - val_loss: 0.8489 - val_mae: 0.7525 - val_rmse: 0.7702 - val_smape: 1.3861

Epoch 86: early stopping

Restoring model weights from the end of the best epoch: 71.

  1/163 ━━━━━━━━━━━━━━━━━━━━ 44s 275ms/step
 16/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 42/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 59/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 81/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 96/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
119/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
140/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
157/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
163/163 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 92%|█████████▏| 11/12 [1:08:08<11:58, 718.16s/trial, best loss: 0.2304277413911462]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

287/287 - 7s - 25ms/step - ia: 0.5369 - loss: 0.6602 - mae: 0.6523 - rmse: 0.8087 - smape: 1.0922 - val_ia: 0.4091 - val_loss: 1.4695 - val_mae: 1.0284 - val_rmse: 1.1653 - val_smape: 1.3730

Epoch 2/128

287/287 - 1s - 4ms/step - ia: 0.5904 - loss: 0.5703 - mae: 0.6018 - rmse: 0.7539 - smape: 1.0068 - val_ia: 0.4135 - val_loss: 1.4611 - val_mae: 1.0190 - val_rmse: 1.1575 - val_smape: 1.3623

Epoch 3/128

287/287 - 1s - 4ms/step - ia: 0.6011 - loss: 0.5365 - mae: 0.5851 - rmse: 0.7310 - smape: 0.9917 - val_ia: 0.4109 - val_loss: 1.4665 - val_mae: 1.0257 - val_rmse: 1.1583 - val_smape: 1.3731

Epoch 4/128

287/287 - 1s - 4ms/step - ia: 0.6105 - loss: 0.5062 - mae: 0.5689 - rmse: 0.7100 - smape: 0.9746 - val_ia: 0.4146 - val_loss: 1.4141 - val_mae: 1.0085 - val_rmse: 1.1384 - val_smape: 1.3689

Epoch 5/128

287/287 - 2s - 6ms/step - ia: 0.6210 - loss: 0.4804 - mae: 0.5546 - rmse: 0.6919 - smape: 0.9548 - val_ia: 0.4289 - val_loss: 1.2800 - val_mae: 0.9469 - val_rmse: 1.0801 - val_smape: 1.3342

Epoch 6/128

287/287 - 1s - 4ms/step - ia: 0.6295 - loss: 0.4603 - mae: 0.5429 - rmse: 0.6771 - smape: 0.9414 - val_ia: 0.4270 - val_loss: 1.3287 - val_mae: 0.9652 - val_rmse: 1.1006 - val_smape: 1.3423

Epoch 7/128

287/287 - 1s - 3ms/step - ia: 0.6373 - loss: 0.4435 - mae: 0.5316 - rmse: 0.6648 - smape: 0.9279 - val_ia: 0.4324 - val_loss: 1.2916 - val_mae: 0.9430 - val_rmse: 1.0846 - val_smape: 1.3274

Epoch 8/128

287/287 - 2s - 6ms/step - ia: 0.6447 - loss: 0.4274 - mae: 0.5222 - rmse: 0.6526 - smape: 0.9183 - val_ia: 0.4396 - val_loss: 1.2343 - val_mae: 0.9193 - val_rmse: 1.0581 - val_smape: 1.3169

Epoch 9/128

287/287 - 2s - 5ms/step - ia: 0.6534 - loss: 0.4092 - mae: 0.5113 - rmse: 0.6383 - smape: 0.9062 - val_ia: 0.4463 - val_loss: 1.1796 - val_mae: 0.8932 - val_rmse: 1.0328 - val_smape: 1.3042

Epoch 10/128

287/287 - 1s - 4ms/step - ia: 0.6610 - loss: 0.3974 - mae: 0.5014 - rmse: 0.6292 - smape: 0.8936 - val_ia: 0.4458 - val_loss: 1.2255 - val_mae: 0.9066 - val_rmse: 1.0527 - val_smape: 1.3021

Epoch 11/128

287/287 - 2s - 6ms/step - ia: 0.6697 - loss: 0.3806 - mae: 0.4904 - rmse: 0.6157 - smape: 0.8819 - val_ia: 0.4562 - val_loss: 1.1413 - val_mae: 0.8661 - val_rmse: 1.0138 - val_smape: 1.2819

Epoch 12/128

287/287 - 1s - 4ms/step - ia: 0.6753 - loss: 0.3698 - mae: 0.4834 - rmse: 0.6070 - smape: 0.8736 - val_ia: 0.4654 - val_loss: 1.0886 - val_mae: 0.8393 - val_rmse: 0.9888 - val_smape: 1.2650

Epoch 13/128

287/287 - 1s - 5ms/step - ia: 0.6821 - loss: 0.3587 - mae: 0.4750 - rmse: 0.5980 - smape: 0.8666 - val_ia: 0.4647 - val_loss: 1.1061 - val_mae: 0.8418 - val_rmse: 0.9962 - val_smape: 1.2637

Epoch 14/128

287/287 - 1s - 5ms/step - ia: 0.6896 - loss: 0.3462 - mae: 0.4664 - rmse: 0.5871 - smape: 0.8573 - val_ia: 0.4726 - val_loss: 1.0299 - val_mae: 0.8105 - val_rmse: 0.9584 - val_smape: 1.2539

Epoch 15/128

287/287 - 2s - 6ms/step - ia: 0.6931 - loss: 0.3407 - mae: 0.4621 - rmse: 0.5825 - smape: 0.8511 - val_ia: 0.4756 - val_loss: 1.0174 - val_mae: 0.8021 - val_rmse: 0.9519 - val_smape: 1.2480

Epoch 16/128

287/287 - 1s - 3ms/step - ia: 0.6976 - loss: 0.3316 - mae: 0.4554 - rmse: 0.5746 - smape: 0.8437 - val_ia: 0.4825 - val_loss: 1.0045 - val_mae: 0.7889 - val_rmse: 0.9466 - val_smape: 1.2287

Epoch 17/128

287/287 - 1s - 4ms/step - ia: 0.7029 - loss: 0.3245 - mae: 0.4494 - rmse: 0.5686 - smape: 0.8351 - val_ia: 0.4936 - val_loss: 0.9177 - val_mae: 0.7493 - val_rmse: 0.9039 - val_smape: 1.2078

Epoch 18/128

287/287 - 1s - 4ms/step - ia: 0.7060 - loss: 0.3182 - mae: 0.4457 - rmse: 0.5628 - smape: 0.8311 - val_ia: 0.4937 - val_loss: 0.9289 - val_mae: 0.7522 - val_rmse: 0.9095 - val_smape: 1.2054

Epoch 19/128

287/287 - 1s - 5ms/step - ia: 0.7086 - loss: 0.3141 - mae: 0.4422 - rmse: 0.5592 - smape: 0.8273 - val_ia: 0.4964 - val_loss: 0.9112 - val_mae: 0.7428 - val_rmse: 0.9012 - val_smape: 1.1995

Epoch 20/128

287/287 - 1s - 4ms/step - ia: 0.7135 - loss: 0.3056 - mae: 0.4355 - rmse: 0.5516 - smape: 0.8176 - val_ia: 0.4993 - val_loss: 0.9099 - val_mae: 0.7387 - val_rmse: 0.8999 - val_smape: 1.1905

Epoch 21/128

287/287 - 2s - 6ms/step - ia: 0.7144 - loss: 0.3053 - mae: 0.4355 - rmse: 0.5514 - smape: 0.8202 - val_ia: 0.5010 - val_loss: 0.9001 - val_mae: 0.7322 - val_rmse: 0.8957 - val_smape: 1.1850

Epoch 22/128

287/287 - 1s - 4ms/step - ia: 0.7157 - loss: 0.3003 - mae: 0.4332 - rmse: 0.5467 - smape: 0.8141 - val_ia: 0.5046 - val_loss: 0.8972 - val_mae: 0.7311 - val_rmse: 0.8929 - val_smape: 1.1826

Epoch 23/128

287/287 - 1s - 3ms/step - ia: 0.7189 - loss: 0.2965 - mae: 0.4294 - rmse: 0.5432 - smape: 0.8101 - val_ia: 0.5077 - val_loss: 0.8945 - val_mae: 0.7275 - val_rmse: 0.8927 - val_smape: 1.1746

Epoch 24/128

287/287 - 1s - 5ms/step - ia: 0.7220 - loss: 0.2907 - mae: 0.4253 - rmse: 0.5378 - smape: 0.8073 - val_ia: 0.5064 - val_loss: 0.9056 - val_mae: 0.7303 - val_rmse: 0.8994 - val_smape: 1.1718

Epoch 25/128

287/287 - 1s - 4ms/step - ia: 0.7238 - loss: 0.2894 - mae: 0.4233 - rmse: 0.5367 - smape: 0.8034 - val_ia: 0.5114 - val_loss: 0.8446 - val_mae: 0.7035 - val_rmse: 0.8693 - val_smape: 1.1598

Epoch 26/128

287/287 - 2s - 5ms/step - ia: 0.7247 - loss: 0.2864 - mae: 0.4212 - rmse: 0.5338 - smape: 0.8034 - val_ia: 0.5104 - val_loss: 0.8839 - val_mae: 0.7227 - val_rmse: 0.8874 - val_smape: 1.1702

Epoch 27/128

287/287 - 1s - 4ms/step - ia: 0.7273 - loss: 0.2819 - mae: 0.4181 - rmse: 0.5299 - smape: 0.7972 - val_ia: 0.5163 - val_loss: 0.8356 - val_mae: 0.7023 - val_rmse: 0.8626 - val_smape: 1.1600

Epoch 28/128

287/287 - 1s - 3ms/step - ia: 0.7274 - loss: 0.2822 - mae: 0.4181 - rmse: 0.5301 - smape: 0.7974 - val_ia: 0.5163 - val_loss: 0.8288 - val_mae: 0.6973 - val_rmse: 0.8609 - val_smape: 1.1557

Epoch 29/128

287/287 - 1s - 5ms/step - ia: 0.7307 - loss: 0.2764 - mae: 0.4131 - rmse: 0.5248 - smape: 0.7904 - val_ia: 0.5164 - val_loss: 0.8526 - val_mae: 0.7092 - val_rmse: 0.8717 - val_smape: 1.1605

Epoch 30/128

287/287 - 2s - 6ms/step - ia: 0.7325 - loss: 0.2737 - mae: 0.4112 - rmse: 0.5220 - smape: 0.7879 - val_ia: 0.5159 - val_loss: 0.8476 - val_mae: 0.7035 - val_rmse: 0.8703 - val_smape: 1.1550

Epoch 31/128

287/287 - 1s - 5ms/step - ia: 0.7332 - loss: 0.2710 - mae: 0.4098 - rmse: 0.5197 - smape: 0.7880 - val_ia: 0.5161 - val_loss: 0.8549 - val_mae: 0.7068 - val_rmse: 0.8740 - val_smape: 1.1564

Epoch 32/128

287/287 - 2s - 6ms/step - ia: 0.7338 - loss: 0.2705 - mae: 0.4091 - rmse: 0.5189 - smape: 0.7839 - val_ia: 0.5191 - val_loss: 0.8177 - val_mae: 0.6898 - val_rmse: 0.8558 - val_smape: 1.1484

Epoch 33/128

287/287 - 2s - 8ms/step - ia: 0.7350 - loss: 0.2696 - mae: 0.4077 - rmse: 0.5182 - smape: 0.7821 - val_ia: 0.5228 - val_loss: 0.8102 - val_mae: 0.6817 - val_rmse: 0.8544 - val_smape: 1.1335

Epoch 34/128

287/287 - 1s - 5ms/step - ia: 0.7376 - loss: 0.2642 - mae: 0.4037 - rmse: 0.5129 - smape: 0.7791 - val_ia: 0.5224 - val_loss: 0.8131 - val_mae: 0.6847 - val_rmse: 0.8546 - val_smape: 1.1383

Epoch 35/128

287/287 - 1s - 5ms/step - ia: 0.7394 - loss: 0.2612 - mae: 0.4015 - rmse: 0.5102 - smape: 0.7748 - val_ia: 0.5289 - val_loss: 0.7584 - val_mae: 0.6596 - val_rmse: 0.8264 - val_smape: 1.1238

Epoch 36/128

287/287 - 1s - 5ms/step - ia: 0.7386 - loss: 0.2621 - mae: 0.4025 - rmse: 0.5107 - smape: 0.7773 - val_ia: 0.5278 - val_loss: 0.7718 - val_mae: 0.6664 - val_rmse: 0.8342 - val_smape: 1.1277

Epoch 37/128

287/287 - 2s - 6ms/step - ia: 0.7418 - loss: 0.2576 - mae: 0.3983 - rmse: 0.5063 - smape: 0.7731 - val_ia: 0.5275 - val_loss: 0.7674 - val_mae: 0.6659 - val_rmse: 0.8309 - val_smape: 1.1324

Epoch 38/128

287/287 - 2s - 9ms/step - ia: 0.7444 - loss: 0.2528 - mae: 0.3945 - rmse: 0.5016 - smape: 0.7680 - val_ia: 0.5292 - val_loss: 0.7692 - val_mae: 0.6648 - val_rmse: 0.8329 - val_smape: 1.1256

Epoch 39/128

287/287 - 1s - 5ms/step - ia: 0.7450 - loss: 0.2522 - mae: 0.3936 - rmse: 0.5009 - smape: 0.7658 - val_ia: 0.5300 - val_loss: 0.7792 - val_mae: 0.6719 - val_rmse: 0.8372 - val_smape: 1.1325

Epoch 40/128

287/287 - 2s - 6ms/step - ia: 0.7454 - loss: 0.2514 - mae: 0.3935 - rmse: 0.5004 - smape: 0.7654 - val_ia: 0.5332 - val_loss: 0.7559 - val_mae: 0.6603 - val_rmse: 0.8245 - val_smape: 1.1253

Epoch 41/128

287/287 - 3s - 9ms/step - ia: 0.7483 - loss: 0.2471 - mae: 0.3894 - rmse: 0.4959 - smape: 0.7622 - val_ia: 0.5363 - val_loss: 0.7193 - val_mae: 0.6433 - val_rmse: 0.8053 - val_smape: 1.1165

Epoch 42/128

287/287 - 1s - 5ms/step - ia: 0.7463 - loss: 0.2492 - mae: 0.3921 - rmse: 0.4982 - smape: 0.7644 - val_ia: 0.5354 - val_loss: 0.7264 - val_mae: 0.6492 - val_rmse: 0.8085 - val_smape: 1.1249

Epoch 43/128

287/287 - 1s - 4ms/step - ia: 0.7499 - loss: 0.2444 - mae: 0.3866 - rmse: 0.4931 - smape: 0.7578 - val_ia: 0.5385 - val_loss: 0.6968 - val_mae: 0.6332 - val_rmse: 0.7949 - val_smape: 1.1116

Epoch 44/128

287/287 - 2s - 6ms/step - ia: 0.7515 - loss: 0.2417 - mae: 0.3847 - rmse: 0.4906 - smape: 0.7540 - val_ia: 0.5380 - val_loss: 0.7017 - val_mae: 0.6356 - val_rmse: 0.7972 - val_smape: 1.1141

Epoch 45/128

287/287 - 3s - 10ms/step - ia: 0.7519 - loss: 0.2406 - mae: 0.3843 - rmse: 0.4892 - smape: 0.7549 - val_ia: 0.5416 - val_loss: 0.6687 - val_mae: 0.6191 - val_rmse: 0.7800 - val_smape: 1.1048

Epoch 46/128

287/287 - 3s - 9ms/step - ia: 0.7524 - loss: 0.2390 - mae: 0.3831 - rmse: 0.4876 - smape: 0.7537 - val_ia: 0.5401 - val_loss: 0.6961 - val_mae: 0.6334 - val_rmse: 0.7939 - val_smape: 1.1131

Epoch 47/128

287/287 - 1s - 4ms/step - ia: 0.7535 - loss: 0.2383 - mae: 0.3821 - rmse: 0.4872 - smape: 0.7525 - val_ia: 0.5423 - val_loss: 0.6779 - val_mae: 0.6278 - val_rmse: 0.7831 - val_smape: 1.1130

Epoch 48/128

287/287 - 2s - 6ms/step - ia: 0.7548 - loss: 0.2349 - mae: 0.3799 - rmse: 0.4835 - smape: 0.7492 - val_ia: 0.5467 - val_loss: 0.6590 - val_mae: 0.6140 - val_rmse: 0.7755 - val_smape: 1.0974

Epoch 49/128

287/287 - 1s - 4ms/step - ia: 0.7558 - loss: 0.2343 - mae: 0.3784 - rmse: 0.4826 - smape: 0.7486 - val_ia: 0.5464 - val_loss: 0.6519 - val_mae: 0.6115 - val_rmse: 0.7714 - val_smape: 1.0977

Epoch 50/128

287/287 - 1s - 5ms/step - ia: 0.7573 - loss: 0.2315 - mae: 0.3764 - rmse: 0.4800 - smape: 0.7448 - val_ia: 0.5455 - val_loss: 0.6534 - val_mae: 0.6152 - val_rmse: 0.7695 - val_smape: 1.1078

Epoch 51/128

287/287 - 1s - 4ms/step - ia: 0.7567 - loss: 0.2316 - mae: 0.3772 - rmse: 0.4803 - smape: 0.7477 - val_ia: 0.5485 - val_loss: 0.6286 - val_mae: 0.6042 - val_rmse: 0.7548 - val_smape: 1.1036

Epoch 52/128

287/287 - 1s - 3ms/step - ia: 0.7596 - loss: 0.2282 - mae: 0.3733 - rmse: 0.4766 - smape: 0.7419 - val_ia: 0.5521 - val_loss: 0.5979 - val_mae: 0.5874 - val_rmse: 0.7392 - val_smape: 1.0924

Epoch 53/128

287/287 - 1s - 5ms/step - ia: 0.7600 - loss: 0.2270 - mae: 0.3727 - rmse: 0.4752 - smape: 0.7396 - val_ia: 0.5501 - val_loss: 0.6260 - val_mae: 0.6027 - val_rmse: 0.7545 - val_smape: 1.1012

Epoch 54/128

287/287 - 1s - 4ms/step - ia: 0.7591 - loss: 0.2278 - mae: 0.3736 - rmse: 0.4760 - smape: 0.7426 - val_ia: 0.5520 - val_loss: 0.6253 - val_mae: 0.6052 - val_rmse: 0.7514 - val_smape: 1.1063

Epoch 55/128

287/287 - 1s - 4ms/step - ia: 0.7611 - loss: 0.2258 - mae: 0.3712 - rmse: 0.4739 - smape: 0.7387 - val_ia: 0.5528 - val_loss: 0.6215 - val_mae: 0.6008 - val_rmse: 0.7505 - val_smape: 1.1005

Epoch 56/128

287/287 - 1s - 4ms/step - ia: 0.7612 - loss: 0.2252 - mae: 0.3707 - rmse: 0.4735 - smape: 0.7377 - val_ia: 0.5546 - val_loss: 0.6090 - val_mae: 0.5941 - val_rmse: 0.7447 - val_smape: 1.0950

Epoch 57/128

287/287 - 1s - 5ms/step - ia: 0.7617 - loss: 0.2242 - mae: 0.3702 - rmse: 0.4724 - smape: 0.7378 - val_ia: 0.5587 - val_loss: 0.5714 - val_mae: 0.5769 - val_rmse: 0.7228 - val_smape: 1.0889

Epoch 58/128

287/287 - 1s - 5ms/step - ia: 0.7635 - loss: 0.2216 - mae: 0.3682 - rmse: 0.4698 - smape: 0.7345 - val_ia: 0.5601 - val_loss: 0.5693 - val_mae: 0.5755 - val_rmse: 0.7212 - val_smape: 1.0858

Epoch 59/128

287/287 - 2s - 5ms/step - ia: 0.7647 - loss: 0.2202 - mae: 0.3662 - rmse: 0.4678 - smape: 0.7318 - val_ia: 0.5599 - val_loss: 0.5687 - val_mae: 0.5744 - val_rmse: 0.7211 - val_smape: 1.0876

Epoch 60/128

287/287 - 2s - 5ms/step - ia: 0.7651 - loss: 0.2180 - mae: 0.3655 - rmse: 0.4659 - smape: 0.7340 - val_ia: 0.5612 - val_loss: 0.5686 - val_mae: 0.5761 - val_rmse: 0.7197 - val_smape: 1.0880

Epoch 61/128

287/287 - 2s - 8ms/step - ia: 0.7658 - loss: 0.2169 - mae: 0.3646 - rmse: 0.4646 - smape: 0.7319 - val_ia: 0.5621 - val_loss: 0.5684 - val_mae: 0.5757 - val_rmse: 0.7201 - val_smape: 1.0871

Epoch 62/128

287/287 - 1s - 4ms/step - ia: 0.7653 - loss: 0.2183 - mae: 0.3655 - rmse: 0.4661 - smape: 0.7339 - val_ia: 0.5646 - val_loss: 0.5634 - val_mae: 0.5739 - val_rmse: 0.7163 - val_smape: 1.0856

Epoch 63/128

287/287 - 1s - 5ms/step - ia: 0.7673 - loss: 0.2150 - mae: 0.3621 - rmse: 0.4627 - smape: 0.7281 - val_ia: 0.5703 - val_loss: 0.5367 - val_mae: 0.5582 - val_rmse: 0.7010 - val_smape: 1.0726

Epoch 64/128

287/287 - 1s - 5ms/step - ia: 0.7678 - loss: 0.2148 - mae: 0.3616 - rmse: 0.4623 - smape: 0.7267 - val_ia: 0.5708 - val_loss: 0.5343 - val_mae: 0.5586 - val_rmse: 0.6986 - val_smape: 1.0752

Epoch 65/128

287/287 - 1s - 4ms/step - ia: 0.7684 - loss: 0.2133 - mae: 0.3606 - rmse: 0.4607 - smape: 0.7266 - val_ia: 0.5724 - val_loss: 0.5280 - val_mae: 0.5561 - val_rmse: 0.6939 - val_smape: 1.0740

Epoch 66/128

287/287 - 1s - 4ms/step - ia: 0.7690 - loss: 0.2122 - mae: 0.3601 - rmse: 0.4592 - smape: 0.7249 - val_ia: 0.5736 - val_loss: 0.5221 - val_mae: 0.5512 - val_rmse: 0.6923 - val_smape: 1.0708

Epoch 67/128

287/287 - 1s - 4ms/step - ia: 0.7705 - loss: 0.2107 - mae: 0.3583 - rmse: 0.4578 - smape: 0.7243 - val_ia: 0.5757 - val_loss: 0.5081 - val_mae: 0.5464 - val_rmse: 0.6809 - val_smape: 1.0713

Epoch 68/128

287/287 - 2s - 5ms/step - ia: 0.7699 - loss: 0.2114 - mae: 0.3589 - rmse: 0.4587 - smape: 0.7223 - val_ia: 0.5732 - val_loss: 0.5090 - val_mae: 0.5458 - val_rmse: 0.6842 - val_smape: 1.0703

Epoch 69/128

287/287 - 2s - 5ms/step - ia: 0.7705 - loss: 0.2092 - mae: 0.3577 - rmse: 0.4562 - smape: 0.7238 - val_ia: 0.5780 - val_loss: 0.5018 - val_mae: 0.5423 - val_rmse: 0.6780 - val_smape: 1.0655

Epoch 70/128

287/287 - 2s - 8ms/step - ia: 0.7711 - loss: 0.2086 - mae: 0.3570 - rmse: 0.4555 - smape: 0.7238 - val_ia: 0.5802 - val_loss: 0.5009 - val_mae: 0.5416 - val_rmse: 0.6775 - val_smape: 1.0626

Epoch 71/128

287/287 - 2s - 5ms/step - ia: 0.7722 - loss: 0.2066 - mae: 0.3553 - rmse: 0.4532 - smape: 0.7224 - val_ia: 0.5819 - val_loss: 0.4982 - val_mae: 0.5423 - val_rmse: 0.6733 - val_smape: 1.0634

Epoch 72/128

287/287 - 1s - 5ms/step - ia: 0.7735 - loss: 0.2045 - mae: 0.3535 - rmse: 0.4511 - smape: 0.7204 - val_ia: 0.5838 - val_loss: 0.4755 - val_mae: 0.5302 - val_rmse: 0.6589 - val_smape: 1.0574

Epoch 73/128

287/287 - 1s - 5ms/step - ia: 0.7745 - loss: 0.2032 - mae: 0.3520 - rmse: 0.4496 - smape: 0.7145 - val_ia: 0.5849 - val_loss: 0.4949 - val_mae: 0.5390 - val_rmse: 0.6727 - val_smape: 1.0588

Epoch 74/128

287/287 - 2s - 9ms/step - ia: 0.7745 - loss: 0.2036 - mae: 0.3524 - rmse: 0.4499 - smape: 0.7169 - val_ia: 0.5868 - val_loss: 0.4710 - val_mae: 0.5274 - val_rmse: 0.6566 - val_smape: 1.0544

Epoch 75/128

287/287 - 1s - 5ms/step - ia: 0.7757 - loss: 0.2023 - mae: 0.3508 - rmse: 0.4485 - smape: 0.7158 - val_ia: 0.5868 - val_loss: 0.4625 - val_mae: 0.5235 - val_rmse: 0.6502 - val_smape: 1.0548

Epoch 76/128

287/287 - 1s - 5ms/step - ia: 0.7755 - loss: 0.2012 - mae: 0.3506 - rmse: 0.4474 - smape: 0.7168 - val_ia: 0.5889 - val_loss: 0.4673 - val_mae: 0.5260 - val_rmse: 0.6523 - val_smape: 1.0507

Epoch 77/128

287/287 - 1s - 5ms/step - ia: 0.7770 - loss: 0.2000 - mae: 0.3488 - rmse: 0.4460 - smape: 0.7109 - val_ia: 0.5900 - val_loss: 0.4401 - val_mae: 0.5120 - val_rmse: 0.6368 - val_smape: 1.0436

Epoch 78/128

287/287 - 1s - 4ms/step - ia: 0.7767 - loss: 0.2006 - mae: 0.3493 - rmse: 0.4467 - smape: 0.7154 - val_ia: 0.5901 - val_loss: 0.4625 - val_mae: 0.5244 - val_rmse: 0.6484 - val_smape: 1.0497

Epoch 79/128

287/287 - 1s - 4ms/step - ia: 0.7752 - loss: 0.2011 - mae: 0.3508 - rmse: 0.4474 - smape: 0.7166 - val_ia: 0.5908 - val_loss: 0.4594 - val_mae: 0.5223 - val_rmse: 0.6480 - val_smape: 1.0483

Epoch 80/128

287/287 - 1s - 4ms/step - ia: 0.7777 - loss: 0.1987 - mae: 0.3475 - rmse: 0.4446 - smape: 0.7099 - val_ia: 0.5939 - val_loss: 0.4212 - val_mae: 0.5020 - val_rmse: 0.6227 - val_smape: 1.0350

Epoch 81/128

287/287 - 1s - 3ms/step - ia: 0.7784 - loss: 0.1979 - mae: 0.3467 - rmse: 0.4435 - smape: 0.7092 - val_ia: 0.5966 - val_loss: 0.4162 - val_mae: 0.4997 - val_rmse: 0.6188 - val_smape: 1.0303

Epoch 82/128

287/287 - 1s - 4ms/step - ia: 0.7781 - loss: 0.1975 - mae: 0.3469 - rmse: 0.4433 - smape: 0.7098 - val_ia: 0.5977 - val_loss: 0.4478 - val_mae: 0.5159 - val_rmse: 0.6384 - val_smape: 1.0382

Epoch 83/128

287/287 - 1s - 3ms/step - ia: 0.7790 - loss: 0.1968 - mae: 0.3454 - rmse: 0.4425 - smape: 0.7076 - val_ia: 0.5970 - val_loss: 0.4346 - val_mae: 0.5089 - val_rmse: 0.6311 - val_smape: 1.0370

Epoch 84/128

287/287 - 1s - 5ms/step - ia: 0.7787 - loss: 0.1962 - mae: 0.3457 - rmse: 0.4420 - smape: 0.7111 - val_ia: 0.6031 - val_loss: 0.3952 - val_mae: 0.4886 - val_rmse: 0.6037 - val_smape: 1.0179

Epoch 85/128

287/287 - 1s - 5ms/step - ia: 0.7805 - loss: 0.1938 - mae: 0.3431 - rmse: 0.4390 - smape: 0.7062 - val_ia: 0.6035 - val_loss: 0.4043 - val_mae: 0.4929 - val_rmse: 0.6092 - val_smape: 1.0206

Epoch 86/128

287/287 - 1s - 4ms/step - ia: 0.7818 - loss: 0.1915 - mae: 0.3416 - rmse: 0.4366 - smape: 0.7047 - val_ia: 0.6033 - val_loss: 0.4148 - val_mae: 0.4984 - val_rmse: 0.6157 - val_smape: 1.0234

Epoch 87/128

287/287 - 1s - 5ms/step - ia: 0.7800 - loss: 0.1940 - mae: 0.3441 - rmse: 0.4396 - smape: 0.7071 - val_ia: 0.6077 - val_loss: 0.3995 - val_mae: 0.4894 - val_rmse: 0.6055 - val_smape: 1.0148

Epoch 88/128

287/287 - 1s - 3ms/step - ia: 0.7808 - loss: 0.1929 - mae: 0.3430 - rmse: 0.4380 - smape: 0.7047 - val_ia: 0.6016 - val_loss: 0.4088 - val_mae: 0.4953 - val_rmse: 0.6141 - val_smape: 1.0220

Epoch 89/128

287/287 - 1s - 5ms/step - ia: 0.7815 - loss: 0.1925 - mae: 0.3419 - rmse: 0.4375 - smape: 0.7016 - val_ia: 0.6045 - val_loss: 0.4251 - val_mae: 0.5042 - val_rmse: 0.6227 - val_smape: 1.0262

Epoch 90/128

287/287 - 1s - 4ms/step - ia: 0.7828 - loss: 0.1907 - mae: 0.3400 - rmse: 0.4356 - smape: 0.6996 - val_ia: 0.6067 - val_loss: 0.4007 - val_mae: 0.4918 - val_rmse: 0.6058 - val_smape: 1.0173

Epoch 91/128

287/287 - 1s - 5ms/step - ia: 0.7827 - loss: 0.1904 - mae: 0.3402 - rmse: 0.4352 - smape: 0.7017 - val_ia: 0.6114 - val_loss: 0.3802 - val_mae: 0.4797 - val_rmse: 0.5937 - val_smape: 1.0026

Epoch 92/128

287/287 - 1s - 5ms/step - ia: 0.7823 - loss: 0.1907 - mae: 0.3410 - rmse: 0.4358 - smape: 0.7023 - val_ia: 0.6089 - val_loss: 0.4053 - val_mae: 0.4944 - val_rmse: 0.6089 - val_smape: 1.0155

Epoch 93/128

287/287 - 1s - 5ms/step - ia: 0.7850 - loss: 0.1867 - mae: 0.3367 - rmse: 0.4309 - smape: 0.6978 - val_ia: 0.6135 - val_loss: 0.3817 - val_mae: 0.4810 - val_rmse: 0.5911 - val_smape: 1.0013

Epoch 94/128

287/287 - 1s - 5ms/step - ia: 0.7835 - loss: 0.1885 - mae: 0.3388 - rmse: 0.4332 - smape: 0.7002 - val_ia: 0.6159 - val_loss: 0.3718 - val_mae: 0.4754 - val_rmse: 0.5845 - val_smape: 0.9952

Epoch 95/128

287/287 - 1s - 4ms/step - ia: 0.7843 - loss: 0.1875 - mae: 0.3377 - rmse: 0.4317 - smape: 0.6984 - val_ia: 0.6156 - val_loss: 0.3731 - val_mae: 0.4764 - val_rmse: 0.5842 - val_smape: 0.9963

Epoch 96/128

287/287 - 1s - 5ms/step - ia: 0.7846 - loss: 0.1862 - mae: 0.3373 - rmse: 0.4305 - smape: 0.7004 - val_ia: 0.6194 - val_loss: 0.3687 - val_mae: 0.4726 - val_rmse: 0.5823 - val_smape: 0.9903

Epoch 97/128

287/287 - 1s - 5ms/step - ia: 0.7859 - loss: 0.1862 - mae: 0.3359 - rmse: 0.4304 - smape: 0.6955 - val_ia: 0.6169 - val_loss: 0.3804 - val_mae: 0.4789 - val_rmse: 0.5893 - val_smape: 0.9982

Epoch 98/128


In [23]:
print(best)

{'activation': 0, 'batch': 0, 'dropout': 0.2, 'layers': 3.0, 'learning_rate': 0.002091021650264381, 'units': 2}