Prueba

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from hyperopt import hp, fmin, tpe, Trials, STATUS_OK
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU, InputLayer, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import os
np.random.seed(42)

LEER DATASET

In [2]:
import pandas as pd

datos = pd.read_csv("C:\\Users\\wamt1\\OneDrive\\Escritorio\\computadorNuevo\\SNpollutionFinal.csv")

datos['date'] = pd.to_datetime(datos['date'])

# Se establece la columna date como index
datos.set_index('date', inplace=True)

In [3]:
datos.head()

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-01 00:00:00      129.0  -21 -11.0  1021.0        2     1.79
2010-01-01 01:00:00      129.0  -21 -12.0  1020.0        2     4.92
2010-01-01 02:00:00      129.0  -21 -11.0  1019.0        2     6.71
2010-01-01 03:00:00      129.0  -21 -14.0  1019.0        2     9.84
2010-01-01 04:00:00      129.0  -20 -12.0  1018.0        2    12.97

Se eliminan las primeras 24 filas debido a que estas contenían valores NAN en la columna pollution, y habían sido rellenadas con interpolación lineal.

In [4]:
datos = datos.drop(datos.index[:24])

datos

                     pollution  dew  temp   press  wnd_dir  wnd_spd
date
2010-01-02 00:00:00      129.0  -16  -4.0  1020.0        1     1.79
2010-01-02 01:00:00      148.0  -15  -4.0  1020.0        1     2.68
2010-01-02 02:00:00      159.0  -11  -5.0  1021.0        1     3.57
2010-01-02 03:00:00      181.0   -7  -5.0  1022.0        1     5.36
2010-01-02 04:00:00      138.0   -7  -5.0  1022.0        1     6.25
...                        ...  ...   ...     ...      ...      ...
2014-12-31 19:00:00        8.0  -23  -2.0  1034.0        2   231.97
2014-12-31 20:00:00       10.0  -22  -3.0  1034.0        2   237.78
2014-12-31 21:00:00       10.0  -22  -3.0  1034.0        2   242.70
2014-12-31 22:00:00        8.0  -22  -4.0  1034.0        2   246.72
2014-12-31 23:00:00       12.0  -21  -3.0  1034.0        2   249.85

[43800 rows x 6 columns]

In [5]:
#Se verifica que el index está en formato de dato "datetime64"
print("El index del dataframe input es un tipo de dato: ", datos.index.dtype)

El index del dataframe input es un tipo de dato:  datetime64[ns]

Se divide el dataset

In [6]:
# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(datos, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
test, val = train_test_split(test, test_size=0.33, shuffle=False)

print("Las dimensiones de train son: ", train.shape)
print("Las dimensiones de test son: ", test.shape)
print("Las dimensiones de val son: ", val.shape)

Las dimensiones de train son:  (30660, 6)
Las dimensiones de test son:  (8803, 6)
Las dimensiones de val son:  (4337, 6)

Se normalizan los datos

In [7]:
from sklearn.preprocessing import StandardScaler


# Normalizar solo con los datos de entrenamiento
scaler = StandardScaler()
train = scaler.fit_transform(train)

# Aplicar la transformación a test y val usando los parámetros de train
test = scaler.transform(test)
val = scaler.transform(val)

train = pd.DataFrame(train, columns=datos.columns)
test = pd.DataFrame(test, columns=datos.columns)
val = pd.DataFrame(val, columns=datos.columns)

Se unen los datos nuevamente, ahora normalizados, en un único conjunto.

In [8]:
datosNormalizados = pd.concat([train, test, val])

datosNormalizados.index = datos.index

In [9]:
datosNormalizados.shape

(43800, 6)

In [10]:
datosNormalizados.head(10)

,pollution,dew,temp,press,wnd_dir,wnd_spd
date,,,,,,
2010-01-02 00:00:00,0.317681,-1.214023,-1.268524,0.329687,-0.380944,-0.464048
2010-01-02 01:00:00,0.526152,-1.144302,-1.268524,0.329687,-0.380944,-0.446575
2010-01-02 02:00:00,0.646846,-0.865419,-1.349314,0.426127,-0.380944,-0.429103
2010-01-02 03:00:00,0.888234,-0.586536,-1.349314,0.522567,-0.380944,-0.393962
2010-01-02 04:00:00,0.416431,-0.586536,-1.349314,0.522567,-0.380944,-0.376489
2010-01-02 05:00:00,0.098238,-0.586536,-1.430104,0.522567,-0.380944,-0.359017
2010-01-02 06:00:00,0.054349,-0.586536,-1.430104,0.619008,-0.380944,-0.323876
2010-01-02 07:00:00,0.262820,-0.586536,-1.349314,0.715448,-0.380944,-0.288735
2010-01-02 08:00:00,0.218931,-0.656257,-1.430104,0.715448,-0.380944,-0.253594
2010-01-02 09:00:00,0.350598,-0.586536,-1.349314,0.811888,-0.380944,-0.218452

Espacio de búsqueda

In [11]:
space = {
    'layers': hp.quniform('layers', 1, 4, 1), # Cantidad de capas GRU
    'units': hp.choice('units', [2 ** i for i in range(3, 8)]),  # Número de unidades GRU
    'activation': hp.choice('activation', ['tanh', 'sigmoid', 'relu', 'linear']),
    'dropout': hp.quniform('dropout', 0, 0.5, 0.1),  # Dropout para regularización
    'learning_rate': hp.loguniform('learning_rate', np.log(0.000001), np.log(0.01)),  # Tasa de aprendizaje
    'batch': hp.choice('batch',[2 ** i for i in range(3, 9)])
}

Se establece el formato de datos de entrada para redes GRU, es decir [observaciones, retardos, caracteristicas]

In [12]:
futuros = 24
pasados  = 12

In [13]:
datosX = []
datosY = []
for i in range(pasados, len(datosNormalizados) - futuros + 1):
  datosX.append(datosNormalizados.iloc[i-pasados:i, 0:datosNormalizados.shape[1]])
  datosY.append(datosNormalizados.iloc[i+futuros-1:i+futuros, 0])

In [14]:
# Convertir las listas en arrays numpy
datosX = np.array(datosX)
datosY = np.array(datosY)

# Ver las dimensiones (shape) de los arrays
print("Dimensiones de X:", datosX.shape)  # (n_muestras, pasos_de_tiempo, n_características)
print("Dimensiones de Y:", datosY.shape)  # (n_muestras, n_características)

Dimensiones de X: (43765, 12, 6)
Dimensiones de Y: (43765, 1)

In [15]:
inputs = datosX.shape[1] * datosX.shape[2]
datosX = datosX.reshape(datosX.shape[0], inputs)

In [16]:
print("Dimensiones de X después de rehape:", datosX.shape)

Dimensiones de X después de rehape: (43765, 72)

Se dividen nuevamente los conjuntos de datos

In [17]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainX, testX = train_test_split(datosX, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testX, valX = train_test_split(testX, test_size=0.33, shuffle=False)

print("Las dimensiones de trainX son: ", trainX.shape)
print("Las dimensiones de testX son: ", testX.shape)
print("Las dimensiones de valX son: ", valX.shape)

Las dimensiones de trainX son:  (30635, 72)
Las dimensiones de testX son:  (8797, 72)
Las dimensiones de valX son:  (4333, 72)

In [18]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
trainY, testY = train_test_split(datosY, test_size=0.3, shuffle=False)

# Luego, dividir el conjunto de prueba en conjuntos de prueba y validación
testY, valY = train_test_split(testY, test_size=0.33, shuffle=False)

print("Las dimensiones de trainY son: ", trainY.shape)
print("Las dimensiones de testY son: ", testY.shape)
print("Las dimensiones de valY son: ", valY.shape)

Las dimensiones de trainY son:  (30635, 1)
Las dimensiones de testY son:  (8797, 1)
Las dimensiones de valY son:  (4333, 1)

Se crean métricas para medir desempeño

In [19]:
import tensorflow.keras.backend as K

def smape(y_true, y_pred):
    """
    Define la función SMAPE (Error Porcentual Absoluto Medio Simétrico).
    """
    summ = K.abs(y_true) + K.abs(y_pred)
    smape_val = K.abs(y_pred - y_true) / summ * 2.0
    return K.mean(smape_val, axis=-1)

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

def ia(y_true, y_pred):
    numerator = K.sum(K.abs(y_true - y_pred))
    denominator = K.sum(K.abs(y_true - K.mean(y_true)) + K.abs(y_pred - K.mean(y_true)))
    return 1 - (numerator / denominator)

In [20]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

def graficarPrediccion(modelo, x, y, inicio, final):
  predicciones = modelo.predict(x)
  predicciones = predicciones.flatten()
  df = pd.DataFrame({'Originales': y, 'Predichos': predicciones})
  plt.plot(df.index, df['Originales'][inicio:final], label='Originales')
  plt.plot(df.index, df['Predichos'][inicio:final], label='Predichos')
  return df, mse(y, predicciones),  mae(y, predicciones), rmse(y, predicciones), smape(y,predicciones), ia(y, predicciones)

Versión Final

In [21]:
def objective(params):

    model = Sequential()
    model.add(InputLayer(input_shape=(trainX.shape[1],)))
    if (params['layers'] == 1):
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    else:
      for _ in range(int(params['layers']) - 1):
          model.add(Dense(units=params['units'], activation=params['activation']))
          model.add(Dropout(params['dropout']))
      model.add(Dense(units=params['units'], activation=params['activation']))
      model.add(Dropout(params['dropout']))

    model.add(Dense(1))


    opt = Adam(learning_rate=params['learning_rate'])
    model.compile(optimizer=opt, loss='mse', metrics=["mae", smape, rmse, ia])

    early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1, restore_best_weights= True)

    model.fit(trainX, trainY, epochs=128,
                        validation_data=(testX, testY),
                        verbose = 2, batch_size=params['batch'], callbacks=[early_stopping])


    predictions = model.predict(valX)


    loss = mean_squared_error(valY, predictions)

    return {'loss': loss, 'status': STATUS_OK}

In [22]:
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=12, trials=trials, rstate=np.random.default_rng(42))

print(best)

  0%|          | 0/12 [00:00<?, ?trial/s, best loss=?]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 7s - 30ms/step - ia: 0.2652 - loss: 1.1480 - mae: 0.7886 - rmse: 1.0648 - smape: 1.4519 - val_ia: 0.2527 - val_loss: 0.9630 - val_mae: 0.7286 - val_rmse: 0.8720 - val_smape: 1.8310

Epoch 2/128

240/240 - 2s - 7ms/step - ia: 0.2256 - loss: 1.0978 - mae: 0.7840 - rmse: 1.0416 - smape: 1.5193 - val_ia: 0.2533 - val_loss: 0.9613 - val_mae: 0.7323 - val_rmse: 0.8743 - val_smape: 1.9187

Epoch 3/128

240/240 - 1s - 4ms/step - ia: 0.2040 - loss: 1.0675 - mae: 0.7753 - rmse: 1.0279 - smape: 1.5541 - val_ia: 0.2537 - val_loss: 0.9592 - val_mae: 0.7321 - val_rmse: 0.8738 - val_smape: 1.9151

Epoch 4/128

240/240 - 1s - 3ms/step - ia: 0.1898 - loss: 1.0444 - mae: 0.7681 - rmse: 1.0153 - smape: 1.5832 - val_ia: 0.2541 - val_loss: 0.9563 - val_mae: 0.7300 - val_rmse: 0.8718 - val_smape: 1.8867

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.1734 - loss: 1.0350 - mae: 0.7638 - rmse: 1.0118 - smape: 1.6054 - val_ia: 0.2547 - val_loss: 0.9534 - val_mae: 0.7299 - val_rmse: 0.8712 - val_smape: 1.8752

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.1677 - loss: 1.0179 - mae: 0.7568 - rmse: 1.0021 - smape: 1.6217 - val_ia: 0.2557 - val_loss: 0.9502 - val_mae: 0.7314 - val_rmse: 0.8718 - val_smape: 1.8643

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.1621 - loss: 1.0071 - mae: 0.7530 - rmse: 0.9972 - smape: 1.6302 - val_ia: 0.2567 - val_loss: 0.9435 - val_mae: 0.7274 - val_rmse: 0.8677 - val_smape: 1.8203

Epoch 8/128

240/240 - 1s - 4ms/step - ia: 0.1578 - loss: 1.0014 - mae: 0.7514 - rmse: 0.9941 - smape: 1.6384 - val_ia: 0.2582 - val_loss: 0.9366 - val_mae: 0.7249 - val_rmse: 0.8648 - val_smape: 1.7804

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.1626 - loss: 0.9938 - mae: 0.7478 - rmse: 0.9908 - smape: 1.6312 - val_ia: 0.2597 - val_loss: 0.9270 - val_mae: 0.7208 - val_rmse: 0.8602 - val_smape: 1.7301

Epoch 10/128

240/240 - 1s - 5ms/step - ia: 0.1693 - loss: 0.9836 - mae: 0.7431 - rmse: 0.9853 - smape: 1.6144 - val_ia: 0.2608 - val_loss: 0.9152 - val_mae: 0.7118 - val_rmse: 0.8518 - val_smape: 1.6534

Epoch 11/128

240/240 - 1s - 6ms/step - ia: 0.1826 - loss: 0.9737 - mae: 0.7376 - rmse: 0.9809 - smape: 1.5900 - val_ia: 0.2640 - val_loss: 0.9030 - val_mae: 0.7085 - val_rmse: 0.8477 - val_smape: 1.6032

Epoch 12/128

240/240 - 1s - 3ms/step - ia: 0.1957 - loss: 0.9672 - mae: 0.7352 - rmse: 0.9774 - smape: 1.5681 - val_ia: 0.2666 - val_loss: 0.8896 - val_mae: 0.7012 - val_rmse: 0.8405 - val_smape: 1.5420

Epoch 13/128

240/240 - 1s - 6ms/step - ia: 0.2141 - loss: 0.9568 - mae: 0.7308 - rmse: 0.9724 - smape: 1.5410 - val_ia: 0.2690 - val_loss: 0.8754 - val_mae: 0.6934 - val_rmse: 0.8328 - val_smape: 1.4807

Epoch 14/128

240/240 - 1s - 3ms/step - ia: 0.2310 - loss: 0.9478 - mae: 0.7252 - rmse: 0.9677 - smape: 1.5076 - val_ia: 0.2715 - val_loss: 0.8647 - val_mae: 0.6873 - val_rmse: 0.8273 - val_smape: 1.4312

Epoch 15/128

240/240 - 1s - 3ms/step - ia: 0.2458 - loss: 0.9417 - mae: 0.7213 - rmse: 0.9643 - smape: 1.4790 - val_ia: 0.2745 - val_loss: 0.8588 - val_mae: 0.6859 - val_rmse: 0.8262 - val_smape: 1.4053

Epoch 16/128

240/240 - 1s - 3ms/step - ia: 0.2553 - loss: 0.9383 - mae: 0.7208 - rmse: 0.9638 - smape: 1.4672 - val_ia: 0.2763 - val_loss: 0.8515 - val_mae: 0.6832 - val_rmse: 0.8234 - val_smape: 1.3806

Epoch 17/128

240/240 - 1s - 3ms/step - ia: 0.2621 - loss: 0.9348 - mae: 0.7190 - rmse: 0.9613 - smape: 1.4542 - val_ia: 0.2785 - val_loss: 0.8493 - val_mae: 0.6818 - val_rmse: 0.8229 - val_smape: 1.3615

Epoch 18/128

240/240 - 1s - 2ms/step - ia: 0.2674 - loss: 0.9352 - mae: 0.7190 - rmse: 0.9604 - smape: 1.4445 - val_ia: 0.2788 - val_loss: 0.8447 - val_mae: 0.6804 - val_rmse: 0.8209 - val_smape: 1.3531

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.2747 - loss: 0.9282 - mae: 0.7146 - rmse: 0.9565 - smape: 1.4306 - val_ia: 0.2794 - val_loss: 0.8398 - val_mae: 0.6767 - val_rmse: 0.8175 - val_smape: 1.3318

Epoch 20/128

240/240 - 1s - 5ms/step - ia: 0.2777 - loss: 0.9223 - mae: 0.7144 - rmse: 0.9544 - smape: 1.4252 - val_ia: 0.2817 - val_loss: 0.8377 - val_mae: 0.6759 - val_rmse: 0.8173 - val_smape: 1.3186

Epoch 21/128

240/240 - 2s - 7ms/step - ia: 0.2825 - loss: 0.9227 - mae: 0.7123 - rmse: 0.9550 - smape: 1.4129 - val_ia: 0.2814 - val_loss: 0.8327 - val_mae: 0.6733 - val_rmse: 0.8143 - val_smape: 1.3077

Epoch 22/128

240/240 - 2s - 8ms/step - ia: 0.2870 - loss: 0.9207 - mae: 0.7118 - rmse: 0.9537 - smape: 1.4063 - val_ia: 0.2830 - val_loss: 0.8336 - val_mae: 0.6725 - val_rmse: 0.8143 - val_smape: 1.3005

Epoch 23/128

240/240 - 1s - 4ms/step - ia: 0.2884 - loss: 0.9184 - mae: 0.7108 - rmse: 0.9524 - smape: 1.4023 - val_ia: 0.2839 - val_loss: 0.8327 - val_mae: 0.6743 - val_rmse: 0.8158 - val_smape: 1.3017

Epoch 24/128

240/240 - 1s - 3ms/step - ia: 0.2917 - loss: 0.9137 - mae: 0.7097 - rmse: 0.9507 - smape: 1.3988 - val_ia: 0.2853 - val_loss: 0.8300 - val_mae: 0.6729 - val_rmse: 0.8148 - val_smape: 1.2900

Epoch 25/128

240/240 - 1s - 3ms/step - ia: 0.2934 - loss: 0.9148 - mae: 0.7088 - rmse: 0.9497 - smape: 1.3908 - val_ia: 0.2852 - val_loss: 0.8282 - val_mae: 0.6726 - val_rmse: 0.8141 - val_smape: 1.2878

Epoch 26/128

240/240 - 1s - 6ms/step - ia: 0.2999 - loss: 0.9090 - mae: 0.7060 - rmse: 0.9474 - smape: 1.3809 - val_ia: 0.2861 - val_loss: 0.8245 - val_mae: 0.6680 - val_rmse: 0.8104 - val_smape: 1.2680

Epoch 27/128

240/240 - 1s - 3ms/step - ia: 0.3000 - loss: 0.9111 - mae: 0.7066 - rmse: 0.9500 - smape: 1.3786 - val_ia: 0.2862 - val_loss: 0.8247 - val_mae: 0.6702 - val_rmse: 0.8121 - val_smape: 1.2732

Epoch 28/128

240/240 - 1s - 3ms/step - ia: 0.3036 - loss: 0.9063 - mae: 0.7059 - rmse: 0.9448 - smape: 1.3743 - val_ia: 0.2873 - val_loss: 0.8250 - val_mae: 0.6702 - val_rmse: 0.8125 - val_smape: 1.2703

Epoch 29/128

240/240 - 1s - 2ms/step - ia: 0.3029 - loss: 0.9069 - mae: 0.7056 - rmse: 0.9469 - smape: 1.3733 - val_ia: 0.2873 - val_loss: 0.8211 - val_mae: 0.6663 - val_rmse: 0.8087 - val_smape: 1.2566

Epoch 30/128

240/240 - 1s - 3ms/step - ia: 0.3038 - loss: 0.9076 - mae: 0.7053 - rmse: 0.9462 - smape: 1.3701 - val_ia: 0.2877 - val_loss: 0.8207 - val_mae: 0.6679 - val_rmse: 0.8098 - val_smape: 1.2617

Epoch 31/128

240/240 - 1s - 2ms/step - ia: 0.3098 - loss: 0.9006 - mae: 0.7029 - rmse: 0.9426 - smape: 1.3608 - val_ia: 0.2880 - val_loss: 0.8196 - val_mae: 0.6666 - val_rmse: 0.8088 - val_smape: 1.2559

Epoch 32/128

240/240 - 1s - 3ms/step - ia: 0.3116 - loss: 0.9022 - mae: 0.7034 - rmse: 0.9438 - smape: 1.3582 - val_ia: 0.2877 - val_loss: 0.8192 - val_mae: 0.6668 - val_rmse: 0.8087 - val_smape: 1.2580

Epoch 33/128

240/240 - 1s - 3ms/step - ia: 0.3062 - loss: 0.9051 - mae: 0.7053 - rmse: 0.9447 - smape: 1.3660 - val_ia: 0.2872 - val_loss: 0.8173 - val_mae: 0.6653 - val_rmse: 0.8069 - val_smape: 1.2564

Epoch 34/128

240/240 - 1s - 2ms/step - ia: 0.3084 - loss: 0.9058 - mae: 0.7038 - rmse: 0.9462 - smape: 1.3609 - val_ia: 0.2876 - val_loss: 0.8177 - val_mae: 0.6670 - val_rmse: 0.8084 - val_smape: 1.2604

Epoch 35/128

240/240 - 1s - 2ms/step - ia: 0.3097 - loss: 0.9018 - mae: 0.7031 - rmse: 0.9457 - smape: 1.3604 - val_ia: 0.2884 - val_loss: 0.8150 - val_mae: 0.6644 - val_rmse: 0.8061 - val_smape: 1.2508

Epoch 36/128

240/240 - 1s - 2ms/step - ia: 0.3147 - loss: 0.8997 - mae: 0.7017 - rmse: 0.9422 - smape: 1.3531 - val_ia: 0.2902 - val_loss: 0.8170 - val_mae: 0.6670 - val_rmse: 0.8090 - val_smape: 1.2568

Epoch 37/128

240/240 - 1s - 3ms/step - ia: 0.3121 - loss: 0.8998 - mae: 0.7031 - rmse: 0.9422 - smape: 1.3571 - val_ia: 0.2898 - val_loss: 0.8151 - val_mae: 0.6653 - val_rmse: 0.8072 - val_smape: 1.2515

Epoch 38/128

240/240 - 1s - 3ms/step - ia: 0.3157 - loss: 0.8949 - mae: 0.7012 - rmse: 0.9399 - smape: 1.3530 - val_ia: 0.2910 - val_loss: 0.8144 - val_mae: 0.6650 - val_rmse: 0.8072 - val_smape: 1.2490

Epoch 39/128

240/240 - 1s - 3ms/step - ia: 0.3202 - loss: 0.8938 - mae: 0.6998 - rmse: 0.9398 - smape: 1.3444 - val_ia: 0.2912 - val_loss: 0.8119 - val_mae: 0.6641 - val_rmse: 0.8061 - val_smape: 1.2459

Epoch 40/128

240/240 - 1s - 2ms/step - ia: 0.3180 - loss: 0.8967 - mae: 0.7019 - rmse: 0.9408 - smape: 1.3473 - val_ia: 0.2906 - val_loss: 0.8127 - val_mae: 0.6646 - val_rmse: 0.8063 - val_smape: 1.2503

Epoch 41/128

240/240 - 1s - 3ms/step - ia: 0.3187 - loss: 0.8940 - mae: 0.7006 - rmse: 0.9409 - smape: 1.3458 - val_ia: 0.2901 - val_loss: 0.8112 - val_mae: 0.6625 - val_rmse: 0.8043 - val_smape: 1.2464

Epoch 42/128

240/240 - 1s - 3ms/step - ia: 0.3206 - loss: 0.8924 - mae: 0.6990 - rmse: 0.9385 - smape: 1.3402 - val_ia: 0.2915 - val_loss: 0.8116 - val_mae: 0.6626 - val_rmse: 0.8049 - val_smape: 1.2432

Epoch 43/128

240/240 - 1s - 3ms/step - ia: 0.3200 - loss: 0.8931 - mae: 0.6988 - rmse: 0.9387 - smape: 1.3409 - val_ia: 0.2919 - val_loss: 0.8110 - val_mae: 0.6634 - val_rmse: 0.8055 - val_smape: 1.2454

Epoch 44/128

240/240 - 1s - 2ms/step - ia: 0.3232 - loss: 0.8917 - mae: 0.6978 - rmse: 0.9389 - smape: 1.3354 - val_ia: 0.2920 - val_loss: 0.8098 - val_mae: 0.6628 - val_rmse: 0.8049 - val_smape: 1.2439

Epoch 45/128

240/240 - 1s - 3ms/step - ia: 0.3225 - loss: 0.8914 - mae: 0.6992 - rmse: 0.9381 - smape: 1.3403 - val_ia: 0.2925 - val_loss: 0.8100 - val_mae: 0.6608 - val_rmse: 0.8035 - val_smape: 1.2392

Epoch 46/128

240/240 - 1s - 3ms/step - ia: 0.3263 - loss: 0.8872 - mae: 0.6961 - rmse: 0.9354 - smape: 1.3343 - val_ia: 0.2927 - val_loss: 0.8094 - val_mae: 0.6630 - val_rmse: 0.8052 - val_smape: 1.2455

Epoch 47/128

240/240 - 1s - 3ms/step - ia: 0.3227 - loss: 0.8925 - mae: 0.6997 - rmse: 0.9388 - smape: 1.3411 - val_ia: 0.2929 - val_loss: 0.8089 - val_mae: 0.6622 - val_rmse: 0.8043 - val_smape: 1.2452

Epoch 48/128

240/240 - 1s - 3ms/step - ia: 0.3249 - loss: 0.8892 - mae: 0.6972 - rmse: 0.9377 - smape: 1.3346 - val_ia: 0.2931 - val_loss: 0.8058 - val_mae: 0.6607 - val_rmse: 0.8026 - val_smape: 1.2399

Epoch 49/128

240/240 - 1s - 2ms/step - ia: 0.3265 - loss: 0.8898 - mae: 0.6973 - rmse: 0.9377 - smape: 1.3329 - val_ia: 0.2933 - val_loss: 0.8049 - val_mae: 0.6611 - val_rmse: 0.8028 - val_smape: 1.2425

Epoch 50/128

240/240 - 1s - 4ms/step - ia: 0.3269 - loss: 0.8883 - mae: 0.6974 - rmse: 0.9364 - smape: 1.3329 - val_ia: 0.2939 - val_loss: 0.8065 - val_mae: 0.6614 - val_rmse: 0.8036 - val_smape: 1.2404

Epoch 51/128

240/240 - 1s - 3ms/step - ia: 0.3280 - loss: 0.8837 - mae: 0.6958 - rmse: 0.9339 - smape: 1.3307 - val_ia: 0.2943 - val_loss: 0.8053 - val_mae: 0.6615 - val_rmse: 0.8035 - val_smape: 1.2411

Epoch 52/128

240/240 - 1s - 6ms/step - ia: 0.3252 - loss: 0.8884 - mae: 0.6985 - rmse: 0.9356 - smape: 1.3389 - val_ia: 0.2946 - val_loss: 0.8027 - val_mae: 0.6587 - val_rmse: 0.8008 - val_smape: 1.2366

Epoch 53/128

240/240 - 1s - 3ms/step - ia: 0.3275 - loss: 0.8885 - mae: 0.6958 - rmse: 0.9371 - smape: 1.3317 - val_ia: 0.2948 - val_loss: 0.8035 - val_mae: 0.6613 - val_rmse: 0.8028 - val_smape: 1.2472

Epoch 54/128

240/240 - 1s - 3ms/step - ia: 0.3277 - loss: 0.8872 - mae: 0.6968 - rmse: 0.9370 - smape: 1.3308 - val_ia: 0.2951 - val_loss: 0.8025 - val_mae: 0.6590 - val_rmse: 0.8009 - val_smape: 1.2415

Epoch 55/128

240/240 - 1s - 3ms/step - ia: 0.3286 - loss: 0.8857 - mae: 0.6962 - rmse: 0.9361 - smape: 1.3342 - val_ia: 0.2947 - val_loss: 0.8015 - val_mae: 0.6579 - val_rmse: 0.7997 - val_smape: 1.2402

Epoch 56/128

240/240 - 1s - 3ms/step - ia: 0.3282 - loss: 0.8869 - mae: 0.6940 - rmse: 0.9354 - smape: 1.3302 - val_ia: 0.2949 - val_loss: 0.8006 - val_mae: 0.6599 - val_rmse: 0.8008 - val_smape: 1.2496

Epoch 57/128

240/240 - 1s - 6ms/step - ia: 0.3293 - loss: 0.8838 - mae: 0.6958 - rmse: 0.9348 - smape: 1.3311 - val_ia: 0.2957 - val_loss: 0.7995 - val_mae: 0.6580 - val_rmse: 0.7994 - val_smape: 1.2431

Epoch 58/128

240/240 - 1s - 3ms/step - ia: 0.3313 - loss: 0.8793 - mae: 0.6941 - rmse: 0.9320 - smape: 1.3302 - val_ia: 0.2964 - val_loss: 0.7970 - val_mae: 0.6570 - val_rmse: 0.7983 - val_smape: 1.2408

Epoch 59/128

240/240 - 1s - 3ms/step - ia: 0.3305 - loss: 0.8834 - mae: 0.6955 - rmse: 0.9353 - smape: 1.3330 - val_ia: 0.2966 - val_loss: 0.7962 - val_mae: 0.6566 - val_rmse: 0.7976 - val_smape: 1.2447

Epoch 60/128

240/240 - 1s - 4ms/step - ia: 0.3294 - loss: 0.8853 - mae: 0.6948 - rmse: 0.9353 - smape: 1.3306 - val_ia: 0.2958 - val_loss: 0.7972 - val_mae: 0.6587 - val_rmse: 0.7992 - val_smape: 1.2525

Epoch 61/128

240/240 - 1s - 3ms/step - ia: 0.3291 - loss: 0.8842 - mae: 0.6947 - rmse: 0.9347 - smape: 1.3313 - val_ia: 0.2955 - val_loss: 0.7946 - val_mae: 0.6563 - val_rmse: 0.7968 - val_smape: 1.2469

Epoch 62/128

240/240 - 1s - 2ms/step - ia: 0.3279 - loss: 0.8848 - mae: 0.6946 - rmse: 0.9342 - smape: 1.3363 - val_ia: 0.2965 - val_loss: 0.7956 - val_mae: 0.6580 - val_rmse: 0.7985 - val_smape: 1.2496

Epoch 63/128

240/240 - 1s - 3ms/step - ia: 0.3331 - loss: 0.8803 - mae: 0.6938 - rmse: 0.9327 - smape: 1.3298 - val_ia: 0.2964 - val_loss: 0.7933 - val_mae: 0.6553 - val_rmse: 0.7962 - val_smape: 1.2406

Epoch 64/128

240/240 - 1s - 5ms/step - ia: 0.3329 - loss: 0.8800 - mae: 0.6931 - rmse: 0.9321 - smape: 1.3288 - val_ia: 0.2967 - val_loss: 0.7933 - val_mae: 0.6554 - val_rmse: 0.7963 - val_smape: 1.2421

Epoch 65/128

240/240 - 1s - 4ms/step - ia: 0.3375 - loss: 0.8799 - mae: 0.6924 - rmse: 0.9322 - smape: 1.3254 - val_ia: 0.2978 - val_loss: 0.7939 - val_mae: 0.6561 - val_rmse: 0.7970 - val_smape: 1.2469

Epoch 66/128

240/240 - 1s - 3ms/step - ia: 0.3332 - loss: 0.8808 - mae: 0.6939 - rmse: 0.9321 - smape: 1.3278 - val_ia: 0.2963 - val_loss: 0.7919 - val_mae: 0.6556 - val_rmse: 0.7960 - val_smape: 1.2443

Epoch 67/128

240/240 - 1s - 3ms/step - ia: 0.3315 - loss: 0.8814 - mae: 0.6940 - rmse: 0.9331 - smape: 1.3329 - val_ia: 0.2973 - val_loss: 0.7915 - val_mae: 0.6548 - val_rmse: 0.7955 - val_smape: 1.2431

Epoch 68/128

240/240 - 1s - 3ms/step - ia: 0.3324 - loss: 0.8795 - mae: 0.6947 - rmse: 0.9323 - smape: 1.3331 - val_ia: 0.2971 - val_loss: 0.7902 - val_mae: 0.6536 - val_rmse: 0.7942 - val_smape: 1.2414

Epoch 69/128

240/240 - 1s - 3ms/step - ia: 0.3347 - loss: 0.8759 - mae: 0.6917 - rmse: 0.9307 - smape: 1.3274 - val_ia: 0.2982 - val_loss: 0.7892 - val_mae: 0.6541 - val_rmse: 0.7947 - val_smape: 1.2421

Epoch 70/128

240/240 - 1s - 5ms/step - ia: 0.3368 - loss: 0.8773 - mae: 0.6919 - rmse: 0.9314 - smape: 1.3244 - val_ia: 0.2982 - val_loss: 0.7887 - val_mae: 0.6535 - val_rmse: 0.7938 - val_smape: 1.2475

Epoch 71/128

240/240 - 2s - 7ms/step - ia: 0.3306 - loss: 0.8800 - mae: 0.6927 - rmse: 0.9323 - smape: 1.3383 - val_ia: 0.2985 - val_loss: 0.7873 - val_mae: 0.6533 - val_rmse: 0.7936 - val_smape: 1.2465

Epoch 72/128

240/240 - 1s - 4ms/step - ia: 0.3350 - loss: 0.8759 - mae: 0.6921 - rmse: 0.9306 - smape: 1.3331 - val_ia: 0.2985 - val_loss: 0.7874 - val_mae: 0.6543 - val_rmse: 0.7942 - val_smape: 1.2521

Epoch 73/128

240/240 - 1s - 5ms/step - ia: 0.3334 - loss: 0.8784 - mae: 0.6926 - rmse: 0.9316 - smape: 1.3347 - val_ia: 0.2987 - val_loss: 0.7870 - val_mae: 0.6543 - val_rmse: 0.7940 - val_smape: 1.2563

Epoch 74/128

240/240 - 1s - 3ms/step - ia: 0.3318 - loss: 0.8782 - mae: 0.6933 - rmse: 0.9310 - smape: 1.3387 - val_ia: 0.2993 - val_loss: 0.7853 - val_mae: 0.6531 - val_rmse: 0.7931 - val_smape: 1.2485

Epoch 75/128

240/240 - 1s - 3ms/step - ia: 0.3389 - loss: 0.8714 - mae: 0.6903 - rmse: 0.9291 - smape: 1.3266 - val_ia: 0.3001 - val_loss: 0.7848 - val_mae: 0.6529 - val_rmse: 0.7930 - val_smape: 1.2498

Epoch 76/128

240/240 - 1s - 2ms/step - ia: 0.3373 - loss: 0.8743 - mae: 0.6912 - rmse: 0.9289 - smape: 1.3295 - val_ia: 0.2994 - val_loss: 0.7837 - val_mae: 0.6524 - val_rmse: 0.7922 - val_smape: 1.2510

Epoch 77/128

240/240 - 1s - 4ms/step - ia: 0.3364 - loss: 0.8719 - mae: 0.6902 - rmse: 0.9283 - smape: 1.3354 - val_ia: 0.3001 - val_loss: 0.7834 - val_mae: 0.6530 - val_rmse: 0.7927 - val_smape: 1.2530

Epoch 78/128

240/240 - 1s - 5ms/step - ia: 0.3354 - loss: 0.8755 - mae: 0.6920 - rmse: 0.9301 - smape: 1.3367 - val_ia: 0.2994 - val_loss: 0.7827 - val_mae: 0.6525 - val_rmse: 0.7921 - val_smape: 1.2519

Epoch 79/128

240/240 - 0s - 2ms/step - ia: 0.3370 - loss: 0.8761 - mae: 0.6903 - rmse: 0.9304 - smape: 1.3326 - val_ia: 0.2983 - val_loss: 0.7826 - val_mae: 0.6531 - val_rmse: 0.7922 - val_smape: 1.2555

Epoch 80/128

240/240 - 1s - 2ms/step - ia: 0.3370 - loss: 0.8706 - mae: 0.6899 - rmse: 0.9286 - smape: 1.3334 - val_ia: 0.3001 - val_loss: 0.7827 - val_mae: 0.6534 - val_rmse: 0.7927 - val_smape: 1.2593

Epoch 81/128

240/240 - 1s - 3ms/step - ia: 0.3405 - loss: 0.8714 - mae: 0.6898 - rmse: 0.9273 - smape: 1.3312 - val_ia: 0.2995 - val_loss: 0.7817 - val_mae: 0.6518 - val_rmse: 0.7911 - val_smape: 1.2568

Epoch 82/128

240/240 - 1s - 2ms/step - ia: 0.3355 - loss: 0.8721 - mae: 0.6901 - rmse: 0.9284 - smape: 1.3363 - val_ia: 0.2994 - val_loss: 0.7800 - val_mae: 0.6516 - val_rmse: 0.7908 - val_smape: 1.2556

Epoch 83/128

240/240 - 1s - 3ms/step - ia: 0.3382 - loss: 0.8720 - mae: 0.6902 - rmse: 0.9278 - smape: 1.3364 - val_ia: 0.3013 - val_loss: 0.7794 - val_mae: 0.6502 - val_rmse: 0.7900 - val_smape: 1.2522

Epoch 84/128

240/240 - 2s - 7ms/step - ia: 0.3397 - loss: 0.8680 - mae: 0.6890 - rmse: 0.9255 - smape: 1.3327 - val_ia: 0.3013 - val_loss: 0.7787 - val_mae: 0.6501 - val_rmse: 0.7899 - val_smape: 1.2498

Epoch 85/128

240/240 - 1s - 4ms/step - ia: 0.3390 - loss: 0.8731 - mae: 0.6909 - rmse: 0.9287 - smape: 1.3349 - val_ia: 0.3002 - val_loss: 0.7792 - val_mae: 0.6501 - val_rmse: 0.7895 - val_smape: 1.2554

Epoch 86/128

240/240 - 1s - 2ms/step - ia: 0.3403 - loss: 0.8666 - mae: 0.6894 - rmse: 0.9264 - smape: 1.3323 - val_ia: 0.3003 - val_loss: 0.7783 - val_mae: 0.6492 - val_rmse: 0.7890 - val_smape: 1.2510

Epoch 87/128

240/240 - 1s - 2ms/step - ia: 0.3406 - loss: 0.8695 - mae: 0.6884 - rmse: 0.9268 - smape: 1.3311 - val_ia: 0.3009 - val_loss: 0.7781 - val_mae: 0.6492 - val_rmse: 0.7891 - val_smape: 1.2508

Epoch 88/128

240/240 - 1s - 3ms/step - ia: 0.3447 - loss: 0.8646 - mae: 0.6870 - rmse: 0.9253 - smape: 1.3269 - val_ia: 0.3014 - val_loss: 0.7770 - val_mae: 0.6493 - val_rmse: 0.7891 - val_smape: 1.2509

Epoch 89/128

240/240 - 1s - 4ms/step - ia: 0.3438 - loss: 0.8663 - mae: 0.6865 - rmse: 0.9261 - smape: 1.3295 - val_ia: 0.3024 - val_loss: 0.7777 - val_mae: 0.6497 - val_rmse: 0.7897 - val_smape: 1.2539

Epoch 90/128

240/240 - 1s - 5ms/step - ia: 0.3396 - loss: 0.8705 - mae: 0.6902 - rmse: 0.9274 - smape: 1.3364 - val_ia: 0.3011 - val_loss: 0.7787 - val_mae: 0.6514 - val_rmse: 0.7907 - val_smape: 1.2616

Epoch 91/128

240/240 - 1s - 4ms/step - ia: 0.3393 - loss: 0.8670 - mae: 0.6890 - rmse: 0.9274 - smape: 1.3385 - val_ia: 0.3016 - val_loss: 0.7774 - val_mae: 0.6497 - val_rmse: 0.7895 - val_smape: 1.2576

Epoch 92/128

240/240 - 1s - 5ms/step - ia: 0.3386 - loss: 0.8672 - mae: 0.6886 - rmse: 0.9268 - smape: 1.3383 - val_ia: 0.3012 - val_loss: 0.7770 - val_mae: 0.6502 - val_rmse: 0.7897 - val_smape: 1.2575

Epoch 93/128

240/240 - 2s - 6ms/step - ia: 0.3404 - loss: 0.8694 - mae: 0.6888 - rmse: 0.9266 - smape: 1.3347 - val_ia: 0.3004 - val_loss: 0.7768 - val_mae: 0.6495 - val_rmse: 0.7891 - val_smape: 1.2553

Epoch 94/128

240/240 - 1s - 6ms/step - ia: 0.3445 - loss: 0.8607 - mae: 0.6857 - rmse: 0.9216 - smape: 1.3298 - val_ia: 0.3022 - val_loss: 0.7760 - val_mae: 0.6503 - val_rmse: 0.7902 - val_smape: 1.2505

Epoch 95/128

240/240 - 1s - 5ms/step - ia: 0.3450 - loss: 0.8662 - mae: 0.6883 - rmse: 0.9249 - smape: 1.3298 - val_ia: 0.3020 - val_loss: 0.7773 - val_mae: 0.6509 - val_rmse: 0.7905 - val_smape: 1.2598

Epoch 96/128

240/240 - 1s - 5ms/step - ia: 0.3412 - loss: 0.8640 - mae: 0.6884 - rmse: 0.9248 - smape: 1.3357 - val_ia: 0.3021 - val_loss: 0.7764 - val_mae: 0.6500 - val_rmse: 0.7897 - val_smape: 1.2581

Epoch 97/128

240/240 - 1s - 2ms/step - ia: 0.3397 - loss: 0.8711 - mae: 0.6901 - rmse: 0.9273 - smape: 1.3394 - val_ia: 0.3015 - val_loss: 0.7770 - val_mae: 0.6505 - val_rmse: 0.7899 - val_smape: 1.2624

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 14s - 7ms/step - ia: 0.3788 - loss: 0.8591 - mae: 0.6829 - rmse: 0.8937 - smape: 1.3029 - val_ia: 0.2594 - val_loss: 0.7753 - val_mae: 0.6466 - val_rmse: 0.7226 - val_smape: 1.2219

Epoch 2/128

1915/1915 - 6s - 3ms/step - ia: 0.3793 - loss: 0.8326 - mae: 0.6714 - rmse: 0.8804 - smape: 1.2979 - val_ia: 0.2475 - val_loss: 0.7687 - val_mae: 0.6501 - val_rmse: 0.7160 - val_smape: 1.3289

Epoch 3/128

1915/1915 - 6s - 3ms/step - ia: 0.3825 - loss: 0.8284 - mae: 0.6690 - rmse: 0.8765 - smape: 1.2946 - val_ia: 0.2580 - val_loss: 0.7553 - val_mae: 0.6358 - val_rmse: 0.7102 - val_smape: 1.2111

Epoch 4/128

1915/1915 - 7s - 4ms/step - ia: 0.3799 - loss: 0.8248 - mae: 0.6687 - rmse: 0.8762 - smape: 1.2941 - val_ia: 0.2515 - val_loss: 0.7671 - val_mae: 0.6402 - val_rmse: 0.7115 - val_smape: 1.2478

Epoch 5/128

1915/1915 - 7s - 3ms/step - ia: 0.3809 - loss: 0.8220 - mae: 0.6676 - rmse: 0.8742 - smape: 1.2947 - val_ia: 0.2440 - val_loss: 0.7818 - val_mae: 0.6540 - val_rmse: 0.7209 - val_smape: 1.3341

Epoch 6/128

1915/1915 - 10s - 5ms/step - ia: 0.3824 - loss: 0.8224 - mae: 0.6673 - rmse: 0.8744 - smape: 1.2926 - val_ia: 0.2453 - val_loss: 0.7701 - val_mae: 0.6496 - val_rmse: 0.7171 - val_smape: 1.3068

Epoch 7/128

1915/1915 - 6s - 3ms/step - ia: 0.3831 - loss: 0.8202 - mae: 0.6662 - rmse: 0.8737 - smape: 1.2931 - val_ia: 0.2566 - val_loss: 0.7516 - val_mae: 0.6354 - val_rmse: 0.7041 - val_smape: 1.2505

Epoch 8/128

1915/1915 - 6s - 3ms/step - ia: 0.3857 - loss: 0.8186 - mae: 0.6651 - rmse: 0.8711 - smape: 1.2889 - val_ia: 0.2551 - val_loss: 0.7630 - val_mae: 0.6443 - val_rmse: 0.7158 - val_smape: 1.2483

Epoch 9/128

1915/1915 - 10s - 5ms/step - ia: 0.3837 - loss: 0.8178 - mae: 0.6649 - rmse: 0.8716 - smape: 1.2904 - val_ia: 0.2574 - val_loss: 0.7589 - val_mae: 0.6381 - val_rmse: 0.7105 - val_smape: 1.2286

Epoch 10/128

1915/1915 - 10s - 5ms/step - ia: 0.3838 - loss: 0.8179 - mae: 0.6652 - rmse: 0.8721 - smape: 1.2904 - val_ia: 0.2601 - val_loss: 0.7689 - val_mae: 0.6370 - val_rmse: 0.7103 - val_smape: 1.2108

Epoch 11/128

1915/1915 - 6s - 3ms/step - ia: 0.3850 - loss: 0.8171 - mae: 0.6638 - rmse: 0.8699 - smape: 1.2891 - val_ia: 0.2518 - val_loss: 0.7548 - val_mae: 0.6406 - val_rmse: 0.7077 - val_smape: 1.2774

Epoch 12/128

1915/1915 - 5s - 3ms/step - ia: 0.3847 - loss: 0.8156 - mae: 0.6641 - rmse: 0.8703 - smape: 1.2920 - val_ia: 0.2553 - val_loss: 0.7559 - val_mae: 0.6373 - val_rmse: 0.7071 - val_smape: 1.2458

Epoch 13/128

1915/1915 - 6s - 3ms/step - ia: 0.3852 - loss: 0.8158 - mae: 0.6640 - rmse: 0.8708 - smape: 1.2884 - val_ia: 0.2498 - val_loss: 0.7623 - val_mae: 0.6397 - val_rmse: 0.7074 - val_smape: 1.2646

Epoch 14/128

1915/1915 - 7s - 3ms/step - ia: 0.3835 - loss: 0.8150 - mae: 0.6639 - rmse: 0.8701 - smape: 1.2880 - val_ia: 0.2474 - val_loss: 0.7672 - val_mae: 0.6441 - val_rmse: 0.7121 - val_smape: 1.2887

Epoch 15/128

1915/1915 - 6s - 3ms/step - ia: 0.3848 - loss: 0.8143 - mae: 0.6628 - rmse: 0.8694 - smape: 1.2862 - val_ia: 0.2589 - val_loss: 0.7719 - val_mae: 0.6409 - val_rmse: 0.7168 - val_smape: 1.2000

Epoch 16/128

1915/1915 - 6s - 3ms/step - ia: 0.3864 - loss: 0.8144 - mae: 0.6632 - rmse: 0.8693 - smape: 1.2877 - val_ia: 0.2463 - val_loss: 0.7716 - val_mae: 0.6500 - val_rmse: 0.7169 - val_smape: 1.3019

Epoch 17/128

1915/1915 - 9s - 5ms/step - ia: 0.3846 - loss: 0.8135 - mae: 0.6629 - rmse: 0.8677 - smape: 1.2842 - val_ia: 0.2504 - val_loss: 0.7545 - val_mae: 0.6411 - val_rmse: 0.7097 - val_smape: 1.2769

Epoch 18/128

1915/1915 - 6s - 3ms/step - ia: 0.3857 - loss: 0.8143 - mae: 0.6623 - rmse: 0.8704 - smape: 1.2855 - val_ia: 0.2565 - val_loss: 0.7541 - val_mae: 0.6399 - val_rmse: 0.7103 - val_smape: 1.2431

Epoch 19/128

1915/1915 - 9s - 5ms/step - ia: 0.3872 - loss: 0.8130 - mae: 0.6624 - rmse: 0.8682 - smape: 1.2836 - val_ia: 0.2570 - val_loss: 0.7489 - val_mae: 0.6333 - val_rmse: 0.7036 - val_smape: 1.2339

Epoch 20/128

1915/1915 - 6s - 3ms/step - ia: 0.3861 - loss: 0.8132 - mae: 0.6620 - rmse: 0.8684 - smape: 1.2843 - val_ia: 0.2590 - val_loss: 0.7656 - val_mae: 0.6402 - val_rmse: 0.7145 - val_smape: 1.2132

Epoch 21/128

1915/1915 - 10s - 5ms/step - ia: 0.3875 - loss: 0.8133 - mae: 0.6630 - rmse: 0.8683 - smape: 1.2869 - val_ia: 0.2574 - val_loss: 0.7520 - val_mae: 0.6356 - val_rmse: 0.7067 - val_smape: 1.2257

Epoch 22/128

1915/1915 - 6s - 3ms/step - ia: 0.3856 - loss: 0.8115 - mae: 0.6622 - rmse: 0.8687 - smape: 1.2851 - val_ia: 0.2490 - val_loss: 0.7609 - val_mae: 0.6410 - val_rmse: 0.7079 - val_smape: 1.2805

Epoch 23/128

1915/1915 - 10s - 5ms/step - ia: 0.3869 - loss: 0.8122 - mae: 0.6621 - rmse: 0.8683 - smape: 1.2850 - val_ia: 0.2488 - val_loss: 0.7592 - val_mae: 0.6384 - val_rmse: 0.7046 - val_smape: 1.2841

Epoch 24/128

1915/1915 - 6s - 3ms/step - ia: 0.3872 - loss: 0.8122 - mae: 0.6616 - rmse: 0.8683 - smape: 1.2816 - val_ia: 0.2530 - val_loss: 0.7668 - val_mae: 0.6409 - val_rmse: 0.7123 - val_smape: 1.2463

Epoch 25/128

1915/1915 - 6s - 3ms/step - ia: 0.3861 - loss: 0.8126 - mae: 0.6627 - rmse: 0.8677 - smape: 1.2854 - val_ia: 0.2534 - val_loss: 0.7582 - val_mae: 0.6371 - val_rmse: 0.7075 - val_smape: 1.2451

Epoch 26/128

1915/1915 - 10s - 5ms/step - ia: 0.3861 - loss: 0.8121 - mae: 0.6622 - rmse: 0.8687 - smape: 1.2861 - val_ia: 0.2517 - val_loss: 0.7582 - val_mae: 0.6399 - val_rmse: 0.7088 - val_smape: 1.2684

Epoch 27/128

1915/1915 - 5s - 3ms/step - ia: 0.3881 - loss: 0.8111 - mae: 0.6619 - rmse: 0.8685 - smape: 1.2839 - val_ia: 0.2539 - val_loss: 0.7562 - val_mae: 0.6368 - val_rmse: 0.7072 - val_smape: 1.2465

Epoch 28/128

1915/1915 - 6s - 3ms/step - ia: 0.3869 - loss: 0.8114 - mae: 0.6612 - rmse: 0.8687 - smape: 1.2815 - val_ia: 0.2547 - val_loss: 0.7572 - val_mae: 0.6373 - val_rmse: 0.7072 - val_smape: 1.2417

Epoch 29/128

1915/1915 - 6s - 3ms/step - ia: 0.3879 - loss: 0.8114 - mae: 0.6621 - rmse: 0.8678 - smape: 1.2834 - val_ia: 0.2471 - val_loss: 0.7619 - val_mae: 0.6441 - val_rmse: 0.7096 - val_smape: 1.3061

Epoch 30/128

1915/1915 - 5s - 3ms/step - ia: 0.3863 - loss: 0.8115 - mae: 0.6613 - rmse: 0.8671 - smape: 1.2818 - val_ia: 0.2465 - val_loss: 0.7680 - val_mae: 0.6487 - val_rmse: 0.7160 - val_smape: 1.2985

Epoch 31/128

1915/1915 - 11s - 5ms/step - ia: 0.3868 - loss: 0.8117 - mae: 0.6620 - rmse: 0.8688 - smape: 1.2841 - val_ia: 0.2545 - val_loss: 0.7541 - val_mae: 0.6380 - val_rmse: 0.7072 - val_smape: 1.2476

Epoch 32/128

1915/1915 - 11s - 6ms/step - ia: 0.3868 - loss: 0.8121 - mae: 0.6623 - rmse: 0.8689 - smape: 1.2837 - val_ia: 0.2460 - val_loss: 0.7637 - val_mae: 0.6467 - val_rmse: 0.7113 - val_smape: 1.3215

Epoch 33/128

1915/1915 - 5s - 3ms/step - ia: 0.3861 - loss: 0.8110 - mae: 0.6615 - rmse: 0.8680 - smape: 1.2832 - val_ia: 0.2474 - val_loss: 0.7651 - val_mae: 0.6435 - val_rmse: 0.7111 - val_smape: 1.2851

Epoch 34/128

1915/1915 - 5s - 2ms/step - ia: 0.3862 - loss: 0.8114 - mae: 0.6620 - rmse: 0.8699 - smape: 1.2846 - val_ia: 0.2556 - val_loss: 0.7541 - val_mae: 0.6352 - val_rmse: 0.7053 - val_smape: 1.2386

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 19.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 14s 110ms/step
 27/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 56/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 85/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
115/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 17%|█▋        | 2/12 [06:23<33:45, 202.53s/trial, best loss: 0.7718968131959658]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 12s - 3ms/step - ia: 0.2522 - loss: 1.0951 - mae: 0.7991 - rmse: 0.9899 - smape: 1.6459 - val_ia: 0.1777 - val_loss: 1.0168 - val_mae: 0.7717 - val_rmse: 0.8221 - val_smape: 1.6530

Epoch 2/128

3830/3830 - 10s - 3ms/step - ia: 0.2554 - loss: 1.0632 - mae: 0.7839 - rmse: 0.9727 - smape: 1.6421 - val_ia: 0.1781 - val_loss: 1.0052 - val_mae: 0.7650 - val_rmse: 0.8141 - val_smape: 1.6556

Epoch 3/128

3830/3830 - 10s - 3ms/step - ia: 0.2577 - loss: 1.0442 - mae: 0.7743 - rmse: 0.9623 - smape: 1.6399 - val_ia: 0.1788 - val_loss: 0.9947 - val_mae: 0.7589 - val_rmse: 0.8071 - val_smape: 1.6555

Epoch 4/128

3830/3830 - 10s - 3ms/step - ia: 0.2582 - loss: 1.0341 - mae: 0.7694 - rmse: 0.9570 - smape: 1.6399 - val_ia: 0.1794 - val_loss: 0.9855 - val_mae: 0.7537 - val_rmse: 0.8010 - val_smape: 1.6538

Epoch 5/128

3830/3830 - 9s - 2ms/step - ia: 0.2600 - loss: 1.0206 - mae: 0.7636 - rmse: 0.9503 - smape: 1.6392 - val_ia: 0.1802 - val_loss: 0.9769 - val_mae: 0.7491 - val_rmse: 0.7959 - val_smape: 1.6517

Epoch 6/128

3830/3830 - 8s - 2ms/step - ia: 0.2610 - loss: 1.0131 - mae: 0.7586 - rmse: 0.9459 - smape: 1.6326 - val_ia: 0.1810 - val_loss: 0.9694 - val_mae: 0.7451 - val_rmse: 0.7913 - val_smape: 1.6504

Epoch 7/128

3830/3830 - 10s - 2ms/step - ia: 0.2633 - loss: 1.0113 - mae: 0.7566 - rmse: 0.9437 - smape: 1.6336 - val_ia: 0.1817 - val_loss: 0.9624 - val_mae: 0.7413 - val_rmse: 0.7871 - val_smape: 1.6477

Epoch 8/128

3830/3830 - 9s - 2ms/step - ia: 0.2649 - loss: 0.9950 - mae: 0.7502 - rmse: 0.9366 - smape: 1.6324 - val_ia: 0.1824 - val_loss: 0.9559 - val_mae: 0.7379 - val_rmse: 0.7833 - val_smape: 1.6452

Epoch 9/128

3830/3830 - 11s - 3ms/step - ia: 0.2655 - loss: 0.9899 - mae: 0.7471 - rmse: 0.9333 - smape: 1.6295 - val_ia: 0.1832 - val_loss: 0.9491 - val_mae: 0.7345 - val_rmse: 0.7797 - val_smape: 1.6430

Epoch 10/128

3830/3830 - 10s - 3ms/step - ia: 0.2660 - loss: 0.9941 - mae: 0.7472 - rmse: 0.9348 - smape: 1.6297 - val_ia: 0.1839 - val_loss: 0.9434 - val_mae: 0.7316 - val_rmse: 0.7765 - val_smape: 1.6411

Epoch 11/128

3830/3830 - 9s - 2ms/step - ia: 0.2660 - loss: 0.9858 - mae: 0.7456 - rmse: 0.9308 - smape: 1.6311 - val_ia: 0.1844 - val_loss: 0.9385 - val_mae: 0.7291 - val_rmse: 0.7737 - val_smape: 1.6397

Epoch 12/128

3830/3830 - 9s - 2ms/step - ia: 0.2691 - loss: 0.9813 - mae: 0.7416 - rmse: 0.9289 - smape: 1.6258 - val_ia: 0.1850 - val_loss: 0.9336 - val_mae: 0.7267 - val_rmse: 0.7711 - val_smape: 1.6377

Epoch 13/128

3830/3830 - 10s - 3ms/step - ia: 0.2694 - loss: 0.9781 - mae: 0.7410 - rmse: 0.9271 - smape: 1.6277 - val_ia: 0.1854 - val_loss: 0.9289 - val_mae: 0.7244 - val_rmse: 0.7687 - val_smape: 1.6350

Epoch 14/128

3830/3830 - 10s - 3ms/step - ia: 0.2700 - loss: 0.9758 - mae: 0.7395 - rmse: 0.9253 - smape: 1.6286 - val_ia: 0.1857 - val_loss: 0.9247 - val_mae: 0.7223 - val_rmse: 0.7664 - val_smape: 1.6325

Epoch 15/128

3830/3830 - 9s - 2ms/step - ia: 0.2732 - loss: 0.9704 - mae: 0.7376 - rmse: 0.9233 - smape: 1.6249 - val_ia: 0.1862 - val_loss: 0.9203 - val_mae: 0.7203 - val_rmse: 0.7643 - val_smape: 1.6288

Epoch 16/128

3830/3830 - 10s - 3ms/step - ia: 0.2714 - loss: 0.9676 - mae: 0.7368 - rmse: 0.9211 - smape: 1.6257 - val_ia: 0.1866 - val_loss: 0.9164 - val_mae: 0.7184 - val_rmse: 0.7623 - val_smape: 1.6251

Epoch 17/128

3830/3830 - 10s - 3ms/step - ia: 0.2739 - loss: 0.9656 - mae: 0.7366 - rmse: 0.9205 - smape: 1.6252 - val_ia: 0.1869 - val_loss: 0.9128 - val_mae: 0.7168 - val_rmse: 0.7606 - val_smape: 1.6213

Epoch 18/128

3830/3830 - 9s - 2ms/step - ia: 0.2758 - loss: 0.9621 - mae: 0.7349 - rmse: 0.9203 - smape: 1.6243 - val_ia: 0.1873 - val_loss: 0.9092 - val_mae: 0.7152 - val_rmse: 0.7590 - val_smape: 1.6185

Epoch 19/128

3830/3830 - 11s - 3ms/step - ia: 0.2772 - loss: 0.9589 - mae: 0.7326 - rmse: 0.9170 - smape: 1.6200 - val_ia: 0.1875 - val_loss: 0.9061 - val_mae: 0.7138 - val_rmse: 0.7575 - val_smape: 1.6157

Epoch 20/128

3830/3830 - 10s - 3ms/step - ia: 0.2802 - loss: 0.9563 - mae: 0.7307 - rmse: 0.9176 - smape: 1.6153 - val_ia: 0.1879 - val_loss: 0.9029 - val_mae: 0.7124 - val_rmse: 0.7560 - val_smape: 1.6132

Epoch 21/128

3830/3830 - 10s - 3ms/step - ia: 0.2795 - loss: 0.9536 - mae: 0.7309 - rmse: 0.9143 - smape: 1.6194 - val_ia: 0.1881 - val_loss: 0.9001 - val_mae: 0.7111 - val_rmse: 0.7546 - val_smape: 1.6103

Epoch 22/128

3830/3830 - 10s - 3ms/step - ia: 0.2772 - loss: 0.9533 - mae: 0.7300 - rmse: 0.9148 - smape: 1.6181 - val_ia: 0.1883 - val_loss: 0.8974 - val_mae: 0.7100 - val_rmse: 0.7534 - val_smape: 1.6079

Epoch 23/128

3830/3830 - 12s - 3ms/step - ia: 0.2819 - loss: 0.9515 - mae: 0.7284 - rmse: 0.9125 - smape: 1.6136 - val_ia: 0.1886 - val_loss: 0.8945 - val_mae: 0.7088 - val_rmse: 0.7522 - val_smape: 1.6047

Epoch 24/128

3830/3830 - 19s - 5ms/step - ia: 0.2829 - loss: 0.9488 - mae: 0.7287 - rmse: 0.9127 - smape: 1.6134 - val_ia: 0.1887 - val_loss: 0.8922 - val_mae: 0.7078 - val_rmse: 0.7511 - val_smape: 1.6023

Epoch 25/128

3830/3830 - 8s - 2ms/step - ia: 0.2850 - loss: 0.9433 - mae: 0.7262 - rmse: 0.9107 - smape: 1.6096 - val_ia: 0.1889 - val_loss: 0.8896 - val_mae: 0.7066 - val_rmse: 0.7499 - val_smape: 1.5987

Epoch 26/128

3830/3830 - 8s - 2ms/step - ia: 0.2828 - loss: 0.9459 - mae: 0.7266 - rmse: 0.9120 - smape: 1.6071 - val_ia: 0.1890 - val_loss: 0.8874 - val_mae: 0.7058 - val_rmse: 0.7491 - val_smape: 1.5964

Epoch 27/128

3830/3830 - 12s - 3ms/step - ia: 0.2842 - loss: 0.9452 - mae: 0.7275 - rmse: 0.9121 - smape: 1.6084 - val_ia: 0.1892 - val_loss: 0.8852 - val_mae: 0.7049 - val_rmse: 0.7481 - val_smape: 1.5941

Epoch 28/128

3830/3830 - 8s - 2ms/step - ia: 0.2855 - loss: 0.9377 - mae: 0.7244 - rmse: 0.9081 - smape: 1.6045 - val_ia: 0.1894 - val_loss: 0.8828 - val_mae: 0.7041 - val_rmse: 0.7472 - val_smape: 1.5910

Epoch 29/128

3830/3830 - 8s - 2ms/step - ia: 0.2836 - loss: 0.9418 - mae: 0.7262 - rmse: 0.9100 - smape: 1.6067 - val_ia: 0.1895 - val_loss: 0.8809 - val_mae: 0.7033 - val_rmse: 0.7464 - val_smape: 1.5887

Epoch 30/128

3830/3830 - 13s - 4ms/step - ia: 0.2870 - loss: 0.9401 - mae: 0.7243 - rmse: 0.9067 - smape: 1.6022 - val_ia: 0.1897 - val_loss: 0.8789 - val_mae: 0.7026 - val_rmse: 0.7456 - val_smape: 1.5873

Epoch 31/128

3830/3830 - 21s - 5ms/step - ia: 0.2890 - loss: 0.9357 - mae: 0.7225 - rmse: 0.9061 - smape: 1.5990 - val_ia: 0.1899 - val_loss: 0.8768 - val_mae: 0.7016 - val_rmse: 0.7446 - val_smape: 1.5840

Epoch 32/128

3830/3830 - 20s - 5ms/step - ia: 0.2901 - loss: 0.9329 - mae: 0.7210 - rmse: 0.9052 - smape: 1.5940 - val_ia: 0.1901 - val_loss: 0.8747 - val_mae: 0.7009 - val_rmse: 0.7439 - val_smape: 1.5808

Epoch 33/128

3830/3830 - 13s - 3ms/step - ia: 0.2895 - loss: 0.9334 - mae: 0.7224 - rmse: 0.9063 - smape: 1.5974 - val_ia: 0.1902 - val_loss: 0.8730 - val_mae: 0.7002 - val_rmse: 0.7432 - val_smape: 1.5782

Epoch 34/128

3830/3830 - 18s - 5ms/step - ia: 0.2906 - loss: 0.9341 - mae: 0.7222 - rmse: 0.9055 - smape: 1.5933 - val_ia: 0.1904 - val_loss: 0.8714 - val_mae: 0.6996 - val_rmse: 0.7426 - val_smape: 1.5761

Epoch 35/128

3830/3830 - 7s - 2ms/step - ia: 0.2940 - loss: 0.9266 - mae: 0.7190 - rmse: 0.9044 - smape: 1.5897 - val_ia: 0.1906 - val_loss: 0.8696 - val_mae: 0.6989 - val_rmse: 0.7419 - val_smape: 1.5731

Epoch 36/128

3830/3830 - 7s - 2ms/step - ia: 0.2930 - loss: 0.9242 - mae: 0.7192 - rmse: 0.9019 - smape: 1.5897 - val_ia: 0.1908 - val_loss: 0.8679 - val_mae: 0.6982 - val_rmse: 0.7412 - val_smape: 1.5700

Epoch 37/128

3830/3830 - 8s - 2ms/step - ia: 0.2950 - loss: 0.9234 - mae: 0.7185 - rmse: 0.9009 - smape: 1.5867 - val_ia: 0.1910 - val_loss: 0.8662 - val_mae: 0.6974 - val_rmse: 0.7404 - val_smape: 1.5669

Epoch 38/128

3830/3830 - 7s - 2ms/step - ia: 0.2979 - loss: 0.9246 - mae: 0.7174 - rmse: 0.9001 - smape: 1.5841 - val_ia: 0.1911 - val_loss: 0.8648 - val_mae: 0.6969 - val_rmse: 0.7398 - val_smape: 1.5645

Epoch 39/128

3830/3830 - 8s - 2ms/step - ia: 0.2979 - loss: 0.9225 - mae: 0.7170 - rmse: 0.8990 - smape: 1.5790 - val_ia: 0.1912 - val_loss: 0.8633 - val_mae: 0.6963 - val_rmse: 0.7392 - val_smape: 1.5623

Epoch 40/128

3830/3830 - 17s - 4ms/step - ia: 0.2979 - loss: 0.9251 - mae: 0.7189 - rmse: 0.9023 - smape: 1.5822 - val_ia: 0.1913 - val_loss: 0.8621 - val_mae: 0.6958 - val_rmse: 0.7387 - val_smape: 1.5606

Epoch 41/128

3830/3830 - 21s - 5ms/step - ia: 0.2985 - loss: 0.9244 - mae: 0.7171 - rmse: 0.9006 - smape: 1.5809 - val_ia: 0.1914 - val_loss: 0.8608 - val_mae: 0.6953 - val_rmse: 0.7382 - val_smape: 1.5584

Epoch 42/128

3830/3830 - 15s - 4ms/step - ia: 0.2992 - loss: 0.9210 - mae: 0.7156 - rmse: 0.8996 - smape: 1.5748 - val_ia: 0.1916 - val_loss: 0.8594 - val_mae: 0.6948 - val_rmse: 0.7376 - val_smape: 1.5561

Epoch 43/128

3830/3830 - 9s - 2ms/step - ia: 0.3000 - loss: 0.9213 - mae: 0.7160 - rmse: 0.8999 - smape: 1.5740 - val_ia: 0.1917 - val_loss: 0.8579 - val_mae: 0.6942 - val_rmse: 0.7371 - val_smape: 1.5540

Epoch 44/128

3830/3830 - 8s - 2ms/step - ia: 0.2996 - loss: 0.9203 - mae: 0.7154 - rmse: 0.9001 - smape: 1.5708 - val_ia: 0.1918 - val_loss: 0.8567 - val_mae: 0.6937 - val_rmse: 0.7366 - val_smape: 1.5517

Epoch 45/128

3830/3830 - 10s - 3ms/step - ia: 0.2981 - loss: 0.9189 - mae: 0.7154 - rmse: 0.9001 - smape: 1.5716 - val_ia: 0.1919 - val_loss: 0.8555 - val_mae: 0.6931 - val_rmse: 0.7360 - val_smape: 1.5487

Epoch 46/128

3830/3830 - 16s - 4ms/step - ia: 0.3019 - loss: 0.9193 - mae: 0.7151 - rmse: 0.8983 - smape: 1.5692 - val_ia: 0.1921 - val_loss: 0.8542 - val_mae: 0.6926 - val_rmse: 0.7354 - val_smape: 1.5463

Epoch 47/128

3830/3830 - 21s - 6ms/step - ia: 0.3005 - loss: 0.9185 - mae: 0.7154 - rmse: 0.8998 - smape: 1.5672 - val_ia: 0.1922 - val_loss: 0.8533 - val_mae: 0.6923 - val_rmse: 0.7351 - val_smape: 1.5449

Epoch 48/128

3830/3830 - 13s - 3ms/step - ia: 0.3043 - loss: 0.9125 - mae: 0.7119 - rmse: 0.8939 - smape: 1.5625 - val_ia: 0.1923 - val_loss: 0.8520 - val_mae: 0.6918 - val_rmse: 0.7346 - val_smape: 1.5422

Epoch 49/128

3830/3830 - 14s - 4ms/step - ia: 0.3011 - loss: 0.9205 - mae: 0.7165 - rmse: 0.9002 - smape: 1.5689 - val_ia: 0.1924 - val_loss: 0.8508 - val_mae: 0.6914 - val_rmse: 0.7342 - val_smape: 1.5406

Epoch 50/128

3830/3830 - 21s - 6ms/step - ia: 0.3020 - loss: 0.9177 - mae: 0.7148 - rmse: 0.8971 - smape: 1.5646 - val_ia: 0.1926 - val_loss: 0.8496 - val_mae: 0.6908 - val_rmse: 0.7336 - val_smape: 1.5380

Epoch 51/128

3830/3830 - 15s - 4ms/step - ia: 0.3043 - loss: 0.9187 - mae: 0.7139 - rmse: 0.8974 - smape: 1.5613 - val_ia: 0.1927 - val_loss: 0.8487 - val_mae: 0.6904 - val_rmse: 0.7332 - val_smape: 1.5360

Epoch 52/128

3830/3830 - 8s - 2ms/step - ia: 0.3019 - loss: 0.9169 - mae: 0.7146 - rmse: 0.8980 - smape: 1.5617 - val_ia: 0.1928 - val_loss: 0.8479 - val_mae: 0.6901 - val_rmse: 0.7329 - val_smape: 1.5348

Epoch 53/128

3830/3830 - 8s - 2ms/step - ia: 0.3051 - loss: 0.9137 - mae: 0.7133 - rmse: 0.8967 - smape: 1.5599 - val_ia: 0.1929 - val_loss: 0.8469 - val_mae: 0.6896 - val_rmse: 0.7324 - val_smape: 1.5324

Epoch 54/128

3830/3830 - 8s - 2ms/step - ia: 0.3050 - loss: 0.9128 - mae: 0.7128 - rmse: 0.8956 - smape: 1.5588 - val_ia: 0.1931 - val_loss: 0.8456 - val_mae: 0.6891 - val_rmse: 0.7318 - val_smape: 1.5296

Epoch 55/128

3830/3830 - 11s - 3ms/step - ia: 0.3101 - loss: 0.9081 - mae: 0.7105 - rmse: 0.8944 - smape: 1.5522 - val_ia: 0.1932 - val_loss: 0.8448 - val_mae: 0.6886 - val_rmse: 0.7314 - val_smape: 1.5276

Epoch 56/128

3830/3830 - 13s - 3ms/step - ia: 0.3074 - loss: 0.9156 - mae: 0.7127 - rmse: 0.8963 - smape: 1.5560 - val_ia: 0.1932 - val_loss: 0.8439 - val_mae: 0.6883 - val_rmse: 0.7311 - val_smape: 1.5261

Epoch 57/128

3830/3830 - 15s - 4ms/step - ia: 0.3064 - loss: 0.9127 - mae: 0.7120 - rmse: 0.8952 - smape: 1.5515 - val_ia: 0.1933 - val_loss: 0.8432 - val_mae: 0.6880 - val_rmse: 0.7308 - val_smape: 1.5249

Epoch 58/128

3830/3830 - 14s - 4ms/step - ia: 0.3075 - loss: 0.9090 - mae: 0.7105 - rmse: 0.8920 - smape: 1.5507 - val_ia: 0.1934 - val_loss: 0.8421 - val_mae: 0.6877 - val_rmse: 0.7304 - val_smape: 1.5228

Epoch 59/128

3830/3830 - 25s - 6ms/step - ia: 0.3084 - loss: 0.9073 - mae: 0.7096 - rmse: 0.8929 - smape: 1.5471 - val_ia: 0.1935 - val_loss: 0.8413 - val_mae: 0.6872 - val_rmse: 0.7299 - val_smape: 1.5206

Epoch 60/128

3830/3830 - 16s - 4ms/step - ia: 0.3099 - loss: 0.9092 - mae: 0.7098 - rmse: 0.8914 - smape: 1.5455 - val_ia: 0.1936 - val_loss: 0.8404 - val_mae: 0.6868 - val_rmse: 0.7295 - val_smape: 1.5187

Epoch 61/128

3830/3830 - 20s - 5ms/step - ia: 0.3095 - loss: 0.9087 - mae: 0.7105 - rmse: 0.8943 - smape: 1.5455 - val_ia: 0.1937 - val_loss: 0.8394 - val_mae: 0.6864 - val_rmse: 0.7292 - val_smape: 1.5167

Epoch 62/128

3830/3830 - 21s - 6ms/step - ia: 0.3107 - loss: 0.9036 - mae: 0.7085 - rmse: 0.8901 - smape: 1.5412 - val_ia: 0.1938 - val_loss: 0.8384 - val_mae: 0.6860 - val_rmse: 0.7288 - val_smape: 1.5146

Epoch 63/128

3830/3830 - 13s - 3ms/step - ia: 0.3111 - loss: 0.9068 - mae: 0.7093 - rmse: 0.8928 - smape: 1.5407 - val_ia: 0.1939 - val_loss: 0.8378 - val_mae: 0.6857 - val_rmse: 0.7284 - val_smape: 1.5133

Epoch 64/128

3830/3830 - 15s - 4ms/step - ia: 0.3087 - loss: 0.9080 - mae: 0.7109 - rmse: 0.8937 - smape: 1.5446 - val_ia: 0.1940 - val_loss: 0.8370 - val_mae: 0.6854 - val_rmse: 0.7281 - val_smape: 1.5118

Epoch 65/128

3830/3830 - 15s - 4ms/step - ia: 0.3111 - loss: 0.9035 - mae: 0.7084 - rmse: 0.8911 - smape: 1.5396 - val_ia: 0.1942 - val_loss: 0.8362 - val_mae: 0.6851 - val_rmse: 0.7278 - val_smape: 1.5097

Epoch 66/128

3830/3830 - 13s - 4ms/step - ia: 0.3133 - loss: 0.9037 - mae: 0.7084 - rmse: 0.8916 - smape: 1.5365 - val_ia: 0.1943 - val_loss: 0.8352 - val_mae: 0.6848 - val_rmse: 0.7275 - val_smape: 1.5080

Epoch 67/128

3830/3830 - 22s - 6ms/step - ia: 0.3136 - loss: 0.9038 - mae: 0.7088 - rmse: 0.8914 - smape: 1.5382 - val_ia: 0.1943 - val_loss: 0.8347 - val_mae: 0.6845 - val_rmse: 0.7272 - val_smape: 1.5072

Epoch 68/128

3830/3830 - 14s - 4ms/step - ia: 0.3119 - loss: 0.8992 - mae: 0.7071 - rmse: 0.8908 - smape: 1.5334 - val_ia: 0.1945 - val_loss: 0.8336 - val_mae: 0.6840 - val_rmse: 0.7268 - val_smape: 1.5044

Epoch 69/128

3830/3830 - 16s - 4ms/step - ia: 0.3128 - loss: 0.9026 - mae: 0.7084 - rmse: 0.8909 - smape: 1.5356 - val_ia: 0.1946 - val_loss: 0.8329 - val_mae: 0.6837 - val_rmse: 0.7265 - val_smape: 1.5027

Epoch 70/128

3830/3830 - 10s - 3ms/step - ia: 0.3164 - loss: 0.9001 - mae: 0.7069 - rmse: 0.8897 - smape: 1.5273 - val_ia: 0.1946 - val_loss: 0.8322 - val_mae: 0.6834 - val_rmse: 0.7261 - val_smape: 1.5016

Epoch 71/128

3830/3830 - 10s - 2ms/step - ia: 0.3140 - loss: 0.9003 - mae: 0.7068 - rmse: 0.8902 - smape: 1.5314 - val_ia: 0.1947 - val_loss: 0.8317 - val_mae: 0.6833 - val_rmse: 0.7260 - val_smape: 1.5012

Epoch 72/128

3830/3830 - 10s - 2ms/step - ia: 0.3156 - loss: 0.8980 - mae: 0.7059 - rmse: 0.8886 - smape: 1.5276 - val_ia: 0.1948 - val_loss: 0.8309 - val_mae: 0.6830 - val_rmse: 0.7257 - val_smape: 1.4991

Epoch 73/128

3830/3830 - 15s - 4ms/step - ia: 0.3179 - loss: 0.8991 - mae: 0.7064 - rmse: 0.8905 - smape: 1.5275 - val_ia: 0.1949 - val_loss: 0.8302 - val_mae: 0.6827 - val_rmse: 0.7253 - val_smape: 1.4974

Epoch 74/128

3830/3830 - 16s - 4ms/step - ia: 0.3179 - loss: 0.8937 - mae: 0.7043 - rmse: 0.8859 - smape: 1.5208 - val_ia: 0.1950 - val_loss: 0.8294 - val_mae: 0.6824 - val_rmse: 0.7251 - val_smape: 1.4957

Epoch 75/128

3830/3830 - 15s - 4ms/step - ia: 0.3185 - loss: 0.8938 - mae: 0.7033 - rmse: 0.8862 - smape: 1.5190 - val_ia: 0.1950 - val_loss: 0.8285 - val_mae: 0.6821 - val_rmse: 0.7248 - val_smape: 1.4937

Epoch 76/128

3830/3830 - 10s - 3ms/step - ia: 0.3183 - loss: 0.8904 - mae: 0.7036 - rmse: 0.8858 - smape: 1.5191 - val_ia: 0.1951 - val_loss: 0.8277 - val_mae: 0.6818 - val_rmse: 0.7245 - val_smape: 1.4917

Epoch 77/128

3830/3830 - 10s - 3ms/step - ia: 0.3171 - loss: 0.8968 - mae: 0.7046 - rmse: 0.8872 - smape: 1.5202 - val_ia: 0.1952 - val_loss: 0.8272 - val_mae: 0.6816 - val_rmse: 0.7243 - val_smape: 1.4903

Epoch 78/128

3830/3830 - 8s - 2ms/step - ia: 0.3196 - loss: 0.9010 - mae: 0.7056 - rmse: 0.8884 - smape: 1.5193 - val_ia: 0.1952 - val_loss: 0.8267 - val_mae: 0.6813 - val_rmse: 0.7240 - val_smape: 1.4893

Epoch 79/128

3830/3830 - 8s - 2ms/step - ia: 0.3174 - loss: 0.8939 - mae: 0.7050 - rmse: 0.8869 - smape: 1.5210 - val_ia: 0.1953 - val_loss: 0.8262 - val_mae: 0.6811 - val_rmse: 0.7238 - val_smape: 1.4878

Epoch 80/128

3830/3830 - 12s - 3ms/step - ia: 0.3206 - loss: 0.8897 - mae: 0.7024 - rmse: 0.8849 - smape: 1.5134 - val_ia: 0.1954 - val_loss: 0.8257 - val_mae: 0.6809 - val_rmse: 0.7236 - val_smape: 1.4867

Epoch 81/128

3830/3830 - 14s - 4ms/step - ia: 0.3187 - loss: 0.8893 - mae: 0.7034 - rmse: 0.8839 - smape: 1.5152 - val_ia: 0.1955 - val_loss: 0.8250 - val_mae: 0.6806 - val_rmse: 0.7233 - val_smape: 1.4845

Epoch 82/128

3830/3830 - 16s - 4ms/step - ia: 0.3194 - loss: 0.8932 - mae: 0.7047 - rmse: 0.8849 - smape: 1.5157 - val_ia: 0.1956 - val_loss: 0.8245 - val_mae: 0.6803 - val_rmse: 0.7230 - val_smape: 1.4829

Epoch 83/128

3830/3830 - 14s - 4ms/step - ia: 0.3227 - loss: 0.8876 - mae: 0.7021 - rmse: 0.8819 - smape: 1.5103 - val_ia: 0.1956 - val_loss: 0.8237 - val_mae: 0.6799 - val_rmse: 0.7226 - val_smape: 1.4806

Epoch 84/128

3830/3830 - 15s - 4ms/step - ia: 0.3205 - loss: 0.8946 - mae: 0.7043 - rmse: 0.8868 - smape: 1.5113 - val_ia: 0.1957 - val_loss: 0.8233 - val_mae: 0.6798 - val_rmse: 0.7225 - val_smape: 1.4799

Epoch 85/128

3830/3830 - 14s - 4ms/step - ia: 0.3222 - loss: 0.8901 - mae: 0.7019 - rmse: 0.8838 - smape: 1.5047 - val_ia: 0.1957 - val_loss: 0.8229 - val_mae: 0.6796 - val_rmse: 0.7223 - val_smape: 1.4789

Epoch 86/128

3830/3830 - 11s - 3ms/step - ia: 0.3228 - loss: 0.8905 - mae: 0.7031 - rmse: 0.8855 - smape: 1.5100 - val_ia: 0.1957 - val_loss: 0.8224 - val_mae: 0.6794 - val_rmse: 0.7220 - val_smape: 1.4770

Epoch 87/128

3830/3830 - 8s - 2ms/step - ia: 0.3216 - loss: 0.8926 - mae: 0.7028 - rmse: 0.8858 - smape: 1.5030 - val_ia: 0.1958 - val_loss: 0.8219 - val_mae: 0.6792 - val_rmse: 0.7218 - val_smape: 1.4760

Epoch 88/128

3830/3830 - 7s - 2ms/step - ia: 0.3204 - loss: 0.8887 - mae: 0.7028 - rmse: 0.8831 - smape: 1.5075 - val_ia: 0.1958 - val_loss: 0.8216 - val_mae: 0.6790 - val_rmse: 0.7216 - val_smape: 1.4748

Epoch 89/128

3830/3830 - 7s - 2ms/step - ia: 0.3210 - loss: 0.8914 - mae: 0.7026 - rmse: 0.8858 - smape: 1.5061 - val_ia: 0.1958 - val_loss: 0.8209 - val_mae: 0.6788 - val_rmse: 0.7214 - val_smape: 1.4729

Epoch 90/128

3830/3830 - 8s - 2ms/step - ia: 0.3230 - loss: 0.8916 - mae: 0.7023 - rmse: 0.8850 - smape: 1.5015 - val_ia: 0.1959 - val_loss: 0.8205 - val_mae: 0.6786 - val_rmse: 0.7212 - val_smape: 1.4719

Epoch 91/128

3830/3830 - 10s - 3ms/step - ia: 0.3233 - loss: 0.8888 - mae: 0.7024 - rmse: 0.8844 - smape: 1.5021 - val_ia: 0.1959 - val_loss: 0.8200 - val_mae: 0.6785 - val_rmse: 0.7211 - val_smape: 1.4708

Epoch 92/128

3830/3830 - 25s - 6ms/step - ia: 0.3246 - loss: 0.8858 - mae: 0.7006 - rmse: 0.8825 - smape: 1.4978 - val_ia: 0.1959 - val_loss: 0.8195 - val_mae: 0.6783 - val_rmse: 0.7209 - val_smape: 1.4693

Epoch 93/128

3830/3830 - 19s - 5ms/step - ia: 0.3254 - loss: 0.8868 - mae: 0.7004 - rmse: 0.8825 - smape: 1.4971 - val_ia: 0.1959 - val_loss: 0.8191 - val_mae: 0.6781 - val_rmse: 0.7207 - val_smape: 1.4681

Epoch 94/128

3830/3830 - 14s - 4ms/step - ia: 0.3250 - loss: 0.8893 - mae: 0.7011 - rmse: 0.8852 - smape: 1.4975 - val_ia: 0.1960 - val_loss: 0.8187 - val_mae: 0.6779 - val_rmse: 0.7205 - val_smape: 1.4670

Epoch 95/128

3830/3830 - 20s - 5ms/step - ia: 0.3271 - loss: 0.8839 - mae: 0.6994 - rmse: 0.8821 - smape: 1.4936 - val_ia: 0.1960 - val_loss: 0.8182 - val_mae: 0.6777 - val_rmse: 0.7203 - val_smape: 1.4650

Epoch 96/128

3830/3830 - 15s - 4ms/step - ia: 0.3267 - loss: 0.8877 - mae: 0.7006 - rmse: 0.8838 - smape: 1.4917 - val_ia: 0.1961 - val_loss: 0.8179 - val_mae: 0.6775 - val_rmse: 0.7201 - val_smape: 1.4635

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

958/958 - 6s - 6ms/step - ia: 0.2225 - loss: 8.5672 - mae: 2.2043 - rmse: 2.8796 - smape: 1.5076 - val_ia: 0.2327 - val_loss: 1.1895 - val_mae: 0.8211 - val_rmse: 0.9809 - val_smape: 1.3531

Epoch 2/128

958/958 - 7s - 7ms/step - ia: 0.2405 - loss: 6.5694 - mae: 1.9466 - rmse: 2.5264 - smape: 1.4851 - val_ia: 0.2410 - val_loss: 1.0283 - val_mae: 0.7598 - val_rmse: 0.8987 - val_smape: 1.3430

Epoch 3/128

958/958 - 5s - 5ms/step - ia: 0.2554 - loss: 5.3207 - mae: 1.7528 - rmse: 2.2750 - smape: 1.4693 - val_ia: 0.2472 - val_loss: 0.9298 - val_mae: 0.7192 - val_rmse: 0.8438 - val_smape: 1.3232

Epoch 4/128

958/958 - 4s - 4ms/step - ia: 0.2716 - loss: 4.4335 - mae: 1.5928 - rmse: 2.0756 - smape: 1.4454 - val_ia: 0.2504 - val_loss: 0.8789 - val_mae: 0.6974 - val_rmse: 0.8112 - val_smape: 1.3287

Epoch 5/128

958/958 - 6s - 6ms/step - ia: 0.2800 - loss: 3.8747 - mae: 1.4874 - rmse: 1.9385 - smape: 1.4370 - val_ia: 0.2526 - val_loss: 0.8455 - val_mae: 0.6825 - val_rmse: 0.7888 - val_smape: 1.3287

Epoch 6/128

958/958 - 4s - 4ms/step - ia: 0.2910 - loss: 3.3639 - mae: 1.3899 - rmse: 1.8060 - smape: 1.4243 - val_ia: 0.2527 - val_loss: 0.8342 - val_mae: 0.6775 - val_rmse: 0.7789 - val_smape: 1.3460

Epoch 7/128

958/958 - 5s - 5ms/step - ia: 0.2991 - loss: 3.0092 - mae: 1.3044 - rmse: 1.7076 - smape: 1.4157 - val_ia: 0.2542 - val_loss: 0.8184 - val_mae: 0.6695 - val_rmse: 0.7682 - val_smape: 1.3350

Epoch 8/128

958/958 - 4s - 4ms/step - ia: 0.3081 - loss: 2.7014 - mae: 1.2379 - rmse: 1.6175 - smape: 1.3994 - val_ia: 0.2549 - val_loss: 0.8068 - val_mae: 0.6635 - val_rmse: 0.7600 - val_smape: 1.3261

Epoch 9/128

958/958 - 4s - 4ms/step - ia: 0.3132 - loss: 2.4264 - mae: 1.1759 - rmse: 1.5333 - smape: 1.3949 - val_ia: 0.2552 - val_loss: 0.8021 - val_mae: 0.6612 - val_rmse: 0.7560 - val_smape: 1.3270

Epoch 10/128

958/958 - 5s - 5ms/step - ia: 0.3196 - loss: 2.2780 - mae: 1.1376 - rmse: 1.4871 - smape: 1.3883 - val_ia: 0.2544 - val_loss: 0.8003 - val_mae: 0.6608 - val_rmse: 0.7535 - val_smape: 1.3368

Epoch 11/128

958/958 - 4s - 4ms/step - ia: 0.3219 - loss: 2.1131 - mae: 1.0960 - rmse: 1.4298 - smape: 1.3910 - val_ia: 0.2543 - val_loss: 0.7984 - val_mae: 0.6602 - val_rmse: 0.7518 - val_smape: 1.3425

Epoch 12/128

958/958 - 6s - 7ms/step - ia: 0.3221 - loss: 1.9938 - mae: 1.0705 - rmse: 1.3929 - smape: 1.3870 - val_ia: 0.2537 - val_loss: 0.7956 - val_mae: 0.6588 - val_rmse: 0.7496 - val_smape: 1.3410

Epoch 13/128

958/958 - 5s - 5ms/step - ia: 0.3276 - loss: 1.8620 - mae: 1.0317 - rmse: 1.3431 - smape: 1.3829 - val_ia: 0.2535 - val_loss: 0.7944 - val_mae: 0.6584 - val_rmse: 0.7486 - val_smape: 1.3411

Epoch 14/128

958/958 - 6s - 6ms/step - ia: 0.3287 - loss: 1.8102 - mae: 1.0148 - rmse: 1.3258 - smape: 1.3809 - val_ia: 0.2530 - val_loss: 0.7938 - val_mae: 0.6583 - val_rmse: 0.7480 - val_smape: 1.3430

Epoch 15/128

958/958 - 4s - 4ms/step - ia: 0.3313 - loss: 1.7168 - mae: 0.9888 - rmse: 1.2902 - smape: 1.3797 - val_ia: 0.2523 - val_loss: 0.7952 - val_mae: 0.6600 - val_rmse: 0.7489 - val_smape: 1.3529

Epoch 16/128

958/958 - 5s - 6ms/step - ia: 0.3303 - loss: 1.6317 - mae: 0.9661 - rmse: 1.2575 - smape: 1.3840 - val_ia: 0.2524 - val_loss: 0.7938 - val_mae: 0.6589 - val_rmse: 0.7477 - val_smape: 1.3478

Epoch 17/128

958/958 - 4s - 4ms/step - ia: 0.3350 - loss: 1.5749 - mae: 0.9456 - rmse: 1.2353 - smape: 1.3767 - val_ia: 0.2520 - val_loss: 0.7944 - val_mae: 0.6593 - val_rmse: 0.7480 - val_smape: 1.3514

Epoch 18/128

958/958 - 4s - 4ms/step - ia: 0.3396 - loss: 1.5195 - mae: 0.9275 - rmse: 1.2136 - smape: 1.3690 - val_ia: 0.2524 - val_loss: 0.7949 - val_mae: 0.6598 - val_rmse: 0.7483 - val_smape: 1.3561

Epoch 19/128

958/958 - 4s - 4ms/step - ia: 0.3401 - loss: 1.4671 - mae: 0.9142 - rmse: 1.1922 - smape: 1.3712 - val_ia: 0.2524 - val_loss: 0.7939 - val_mae: 0.6592 - val_rmse: 0.7478 - val_smape: 1.3531

Epoch 20/128

958/958 - 5s - 5ms/step - ia: 0.3395 - loss: 1.4319 - mae: 0.9038 - rmse: 1.1788 - smape: 1.3662 - val_ia: 0.2523 - val_loss: 0.7933 - val_mae: 0.6593 - val_rmse: 0.7476 - val_smape: 1.3550

Epoch 21/128

958/958 - 5s - 5ms/step - ia: 0.3361 - loss: 1.4164 - mae: 0.8963 - rmse: 1.1702 - smape: 1.3742 - val_ia: 0.2526 - val_loss: 0.7917 - val_mae: 0.6584 - val_rmse: 0.7469 - val_smape: 1.3511

Epoch 22/128

958/958 - 3s - 4ms/step - ia: 0.3429 - loss: 1.3612 - mae: 0.8800 - rmse: 1.1492 - smape: 1.3665 - val_ia: 0.2521 - val_loss: 0.7937 - val_mae: 0.6599 - val_rmse: 0.7481 - val_smape: 1.3596

Epoch 23/128

958/958 - 4s - 4ms/step - ia: 0.3437 - loss: 1.3458 - mae: 0.8713 - rmse: 1.1410 - smape: 1.3643 - val_ia: 0.2520 - val_loss: 0.7933 - val_mae: 0.6599 - val_rmse: 0.7479 - val_smape: 1.3612

Epoch 24/128

958/958 - 4s - 4ms/step - ia: 0.3409 - loss: 1.3247 - mae: 0.8639 - rmse: 1.1345 - smape: 1.3659 - val_ia: 0.2523 - val_loss: 0.7933 - val_mae: 0.6603 - val_rmse: 0.7483 - val_smape: 1.3628

Epoch 25/128

958/958 - 4s - 4ms/step - ia: 0.3397 - loss: 1.3016 - mae: 0.8558 - rmse: 1.1223 - smape: 1.3699 - val_ia: 0.2527 - val_loss: 0.7917 - val_mae: 0.6596 - val_rmse: 0.7476 - val_smape: 1.3600

Epoch 26/128

958/958 - 5s - 5ms/step - ia: 0.3394 - loss: 1.2739 - mae: 0.8509 - rmse: 1.1110 - smape: 1.3728 - val_ia: 0.2528 - val_loss: 0.7921 - val_mae: 0.6601 - val_rmse: 0.7479 - val_smape: 1.3642

Epoch 27/128

958/958 - 4s - 4ms/step - ia: 0.3377 - loss: 1.2544 - mae: 0.8449 - rmse: 1.1017 - smape: 1.3761 - val_ia: 0.2528 - val_loss: 0.7924 - val_mae: 0.6601 - val_rmse: 0.7478 - val_smape: 1.3639

Epoch 28/128

958/958 - 5s - 6ms/step - ia: 0.3406 - loss: 1.2229 - mae: 0.8351 - rmse: 1.0892 - smape: 1.3689 - val_ia: 0.2529 - val_loss: 0.7917 - val_mae: 0.6594 - val_rmse: 0.7473 - val_smape: 1.3611

Epoch 29/128

958/958 - 5s - 6ms/step - ia: 0.3412 - loss: 1.2290 - mae: 0.8309 - rmse: 1.0907 - smape: 1.3674 - val_ia: 0.2530 - val_loss: 0.7912 - val_mae: 0.6591 - val_rmse: 0.7470 - val_smape: 1.3603

Epoch 30/128

958/958 - 5s - 5ms/step - ia: 0.3415 - loss: 1.1981 - mae: 0.8228 - rmse: 1.0763 - smape: 1.3663 - val_ia: 0.2533 - val_loss: 0.7890 - val_mae: 0.6580 - val_rmse: 0.7460 - val_smape: 1.3552

Epoch 31/128

958/958 - 3s - 3ms/step - ia: 0.3470 - loss: 1.1754 - mae: 0.8131 - rmse: 1.0668 - smape: 1.3594 - val_ia: 0.2532 - val_loss: 0.7885 - val_mae: 0.6578 - val_rmse: 0.7458 - val_smape: 1.3561

Epoch 32/128

958/958 - 6s - 6ms/step - ia: 0.3455 - loss: 1.1597 - mae: 0.8101 - rmse: 1.0589 - smape: 1.3671 - val_ia: 0.2538 - val_loss: 0.7867 - val_mae: 0.6568 - val_rmse: 0.7450 - val_smape: 1.3506

Epoch 33/128

958/958 - 4s - 4ms/step - ia: 0.3453 - loss: 1.1450 - mae: 0.8066 - rmse: 1.0518 - smape: 1.3665 - val_ia: 0.2539 - val_loss: 0.7854 - val_mae: 0.6560 - val_rmse: 0.7442 - val_smape: 1.3481

Epoch 34/128

958/958 - 4s - 4ms/step - ia: 0.3467 - loss: 1.1396 - mae: 0.8018 - rmse: 1.0497 - smape: 1.3592 - val_ia: 0.2537 - val_loss: 0.7856 - val_mae: 0.6564 - val_rmse: 0.7445 - val_smape: 1.3512

Epoch 35/128

958/958 - 4s - 4ms/step - ia: 0.3421 - loss: 1.1293 - mae: 0.8008 - rmse: 1.0450 - smape: 1.3719 - val_ia: 0.2542 - val_loss: 0.7846 - val_mae: 0.6558 - val_rmse: 0.7440 - val_smape: 1.3485

Epoch 36/128

958/958 - 5s - 5ms/step - ia: 0.3446 - loss: 1.1156 - mae: 0.7944 - rmse: 1.0372 - smape: 1.3652 - val_ia: 0.2542 - val_loss: 0.7838 - val_mae: 0.6556 - val_rmse: 0.7438 - val_smape: 1.3477

Epoch 37/128

958/958 - 6s - 6ms/step - ia: 0.3455 - loss: 1.1064 - mae: 0.7914 - rmse: 1.0351 - smape: 1.3704 - val_ia: 0.2545 - val_loss: 0.7834 - val_mae: 0.6553 - val_rmse: 0.7436 - val_smape: 1.3472

Epoch 38/128

958/958 - 4s - 4ms/step - ia: 0.3479 - loss: 1.0964 - mae: 0.7846 - rmse: 1.0299 - smape: 1.3624 - val_ia: 0.2547 - val_loss: 0.7826 - val_mae: 0.6550 - val_rmse: 0.7435 - val_smape: 1.3451

Epoch 39/128

958/958 - 4s - 4ms/step - ia: 0.3477 - loss: 1.0861 - mae: 0.7809 - rmse: 1.0239 - smape: 1.3619 - val_ia: 0.2551 - val_loss: 0.7813 - val_mae: 0.6544 - val_rmse: 0.7430 - val_smape: 1.3422

Epoch 40/128

958/958 - 4s - 4ms/step - ia: 0.3534 - loss: 1.0640 - mae: 0.7732 - rmse: 1.0142 - smape: 1.3571 - val_ia: 0.2551 - val_loss: 0.7806 - val_mae: 0.6543 - val_rmse: 0.7430 - val_smape: 1.3416

Epoch 41/128

958/958 - 4s - 4ms/step - ia: 0.3519 - loss: 1.0586 - mae: 0.7716 - rmse: 1.0119 - smape: 1.3572 - val_ia: 0.2551 - val_loss: 0.7805 - val_mae: 0.6544 - val_rmse: 0.7430 - val_smape: 1.3438

Epoch 42/128

958/958 - 4s - 4ms/step - ia: 0.3492 - loss: 1.0590 - mae: 0.7717 - rmse: 1.0121 - smape: 1.3602 - val_ia: 0.2553 - val_loss: 0.7793 - val_mae: 0.6534 - val_rmse: 0.7423 - val_smape: 1.3391

Epoch 43/128

958/958 - 4s - 4ms/step - ia: 0.3508 - loss: 1.0522 - mae: 0.7669 - rmse: 1.0079 - smape: 1.3560 - val_ia: 0.2555 - val_loss: 0.7784 - val_mae: 0.6530 - val_rmse: 0.7418 - val_smape: 1.3381

Epoch 44/128

958/958 - 4s - 4ms/step - ia: 0.3500 - loss: 1.0405 - mae: 0.7638 - rmse: 1.0009 - smape: 1.3598 - val_ia: 0.2557 - val_loss: 0.7775 - val_mae: 0.6526 - val_rmse: 0.7414 - val_smape: 1.3351

Epoch 45/128

958/958 - 5s - 5ms/step - ia: 0.3502 - loss: 1.0440 - mae: 0.7647 - rmse: 1.0054 - smape: 1.3590 - val_ia: 0.2557 - val_loss: 0.7775 - val_mae: 0.6526 - val_rmse: 0.7413 - val_smape: 1.3366

Epoch 46/128

958/958 - 5s - 5ms/step - ia: 0.3483 - loss: 1.0279 - mae: 0.7600 - rmse: 0.9955 - smape: 1.3590 - val_ia: 0.2561 - val_loss: 0.7761 - val_mae: 0.6519 - val_rmse: 0.7409 - val_smape: 1.3321

Epoch 47/128

958/958 - 4s - 4ms/step - ia: 0.3465 - loss: 1.0355 - mae: 0.7626 - rmse: 0.9998 - smape: 1.3658 - val_ia: 0.2561 - val_loss: 0.7759 - val_mae: 0.6519 - val_rmse: 0.7408 - val_smape: 1.3329

Epoch 48/128

958/958 - 4s - 4ms/step - ia: 0.3524 - loss: 1.0148 - mae: 0.7530 - rmse: 0.9900 - smape: 1.3535 - val_ia: 0.2561 - val_loss: 0.7755 - val_mae: 0.6520 - val_rmse: 0.7409 - val_smape: 1.3335

Epoch 49/128

958/958 - 4s - 5ms/step - ia: 0.3520 - loss: 1.0103 - mae: 0.7520 - rmse: 0.9872 - smape: 1.3540 - val_ia: 0.2563 - val_loss: 0.7748 - val_mae: 0.6516 - val_rmse: 0.7405 - val_smape: 1.3327

Epoch 50/128

958/958 - 5s - 5ms/step - ia: 0.3513 - loss: 0.9945 - mae: 0.7490 - rmse: 0.9800 - smape: 1.3592 - val_ia: 0.2566 - val_loss: 0.7741 - val_mae: 0.6511 - val_rmse: 0.7401 - val_smape: 1.3305

Epoch 51/128

958/958 - 4s - 4ms/step - ia: 0.3467 - loss: 1.0134 - mae: 0.7518 - rmse: 0.9905 - smape: 1.3573 - val_ia: 0.2568 - val_loss: 0.7733 - val_mae: 0.6504 - val_rmse: 0.7395 - val_smape: 1.3267

Epoch 52/128

958/958 - 4s - 4ms/step - ia: 0.3548 - loss: 0.9958 - mae: 0.7446 - rmse: 0.9801 - smape: 1.3521 - val_ia: 0.2571 - val_loss: 0.7722 - val_mae: 0.6499 - val_rmse: 0.7392 - val_smape: 1.3243

Epoch 53/128

958/958 - 4s - 4ms/step - ia: 0.3520 - loss: 0.9916 - mae: 0.7450 - rmse: 0.9789 - smape: 1.3558 - val_ia: 0.2568 - val_loss: 0.7725 - val_mae: 0.6501 - val_rmse: 0.7392 - val_smape: 1.3251

Epoch 54/128

958/958 - 4s - 4ms/step - ia: 0.3553 - loss: 0.9874 - mae: 0.7402 - rmse: 0.9748 - smape: 1.3523 - val_ia: 0.2571 - val_loss: 0.7718 - val_mae: 0.6497 - val_rmse: 0.7389 - val_smape: 1.3237

Epoch 55/128

958/958 - 5s - 5ms/step - ia: 0.3523 - loss: 0.9813 - mae: 0.7391 - rmse: 0.9731 - smape: 1.3555 - val_ia: 0.2569 - val_loss: 0.7716 - val_mae: 0.6496 - val_rmse: 0.7388 - val_smape: 1.3239

Epoch 56/128

958/958 - 5s - 6ms/step - ia: 0.3562 - loss: 0.9688 - mae: 0.7334 - rmse: 0.9668 - smape: 1.3486 - val_ia: 0.2572 - val_loss: 0.7706 - val_mae: 0.6490 - val_rmse: 0.7382 - val_smape: 1.3220

Epoch 57/128

958/958 - 4s - 4ms/step - ia: 0.3557 - loss: 0.9677 - mae: 0.7346 - rmse: 0.9660 - smape: 1.3549 - val_ia: 0.2574 - val_loss: 0.7699 - val_mae: 0.6485 - val_rmse: 0.7379 - val_smape: 1.3195

Epoch 58/128

958/958 - 5s - 5ms/step - ia: 0.3567 - loss: 0.9604 - mae: 0.7317 - rmse: 0.9622 - smape: 1.3497 - val_ia: 0.2573 - val_loss: 0.7705 - val_mae: 0.6490 - val_rmse: 0.7383 - val_smape: 1.3212

Epoch 59/128

958/958 - 4s - 4ms/step - ia: 0.3524 - loss: 0.9698 - mae: 0.7350 - rmse: 0.9670 - smape: 1.3545 - val_ia: 0.2575 - val_loss: 0.7696 - val_mae: 0.6485 - val_rmse: 0.7380 - val_smape: 1.3193

Epoch 60/128

958/958 - 4s - 4ms/step - ia: 0.3550 - loss: 0.9534 - mae: 0.7282 - rmse: 0.9591 - smape: 1.3493 - val_ia: 0.2578 - val_loss: 0.7690 - val_mae: 0.6482 - val_rmse: 0.7379 - val_smape: 1.3171

Epoch 61/128

958/958 - 4s - 4ms/step - ia: 0.3560 - loss: 0.9599 - mae: 0.7304 - rmse: 0.9616 - smape: 1.3482 - val_ia: 0.2576 - val_loss: 0.7691 - val_mae: 0.6484 - val_rmse: 0.7379 - val_smape: 1.3192

Epoch 62/128

958/958 - 4s - 4ms/step - ia: 0.3546 - loss: 0.9499 - mae: 0.7262 - rmse: 0.9561 - smape: 1.3502 - val_ia: 0.2575 - val_loss: 0.7691 - val_mae: 0.6485 - val_rmse: 0.7381 - val_smape: 1.3191

Epoch 63/128

958/958 - 4s - 4ms/step - ia: 0.3569 - loss: 0.9437 - mae: 0.7231 - rmse: 0.9554 - smape: 1.3476 - val_ia: 0.2574 - val_loss: 0.7696 - val_mae: 0.6488 - val_rmse: 0.7385 - val_smape: 1.3191

Epoch 64/128

958/958 - 6s - 6ms/step - ia: 0.3547 - loss: 0.9458 - mae: 0.7253 - rmse: 0.9550 - smape: 1.3487 - val_ia: 0.2579 - val_loss: 0.7688 - val_mae: 0.6484 - val_rmse: 0.7381 - val_smape: 1.3178

Epoch 65/128

958/958 - 4s - 4ms/step - ia: 0.3548 - loss: 0.9412 - mae: 0.7232 - rmse: 0.9527 - smape: 1.3528 - val_ia: 0.2576 - val_loss: 0.7696 - val_mae: 0.6488 - val_rmse: 0.7385 - val_smape: 1.3196

Epoch 66/128

958/958 - 4s - 4ms/step - ia: 0.3538 - loss: 0.9417 - mae: 0.7230 - rmse: 0.9530 - smape: 1.3525 - val_ia: 0.2579 - val_loss: 0.7687 - val_mae: 0.6483 - val_rmse: 0.7381 - val_smape: 1.3178

Epoch 67/128

958/958 - 5s - 5ms/step - ia: 0.3591 - loss: 0.9331 - mae: 0.7196 - rmse: 0.9490 - smape: 1.3431 - val_ia: 0.2581 - val_loss: 0.7679 - val_mae: 0.6479 - val_rmse: 0.7377 - val_smape: 1.3152

Epoch 68/128

958/958 - 3s - 4ms/step - ia: 0.3589 - loss: 0.9250 - mae: 0.7156 - rmse: 0.9437 - smape: 1.3444 - val_ia: 0.2582 - val_loss: 0.7674 - val_mae: 0.6477 - val_rmse: 0.7376 - val_smape: 1.3137

Epoch 69/128

958/958 - 6s - 6ms/step - ia: 0.3555 - loss: 0.9323 - mae: 0.7200 - rmse: 0.9477 - smape: 1.3508 - val_ia: 0.2582 - val_loss: 0.7673 - val_mae: 0.6477 - val_rmse: 0.7375 - val_smape: 1.3140

Epoch 70/128

958/958 - 5s - 5ms/step - ia: 0.3572 - loss: 0.9278 - mae: 0.7172 - rmse: 0.9457 - smape: 1.3462 - val_ia: 0.2580 - val_loss: 0.7679 - val_mae: 0.6482 - val_rmse: 0.7379 - val_smape: 1.3162

Epoch 71/128

958/958 - 5s - 5ms/step - ia: 0.3555 - loss: 0.9283 - mae: 0.7192 - rmse: 0.9454 - smape: 1.3509 - val_ia: 0.2581 - val_loss: 0.7681 - val_mae: 0.6481 - val_rmse: 0.7380 - val_smape: 1.3160

Epoch 72/128

958/958 - 4s - 4ms/step - ia: 0.3578 - loss: 0.9219 - mae: 0.7136 - rmse: 0.9415 - smape: 1.3459 - val_ia: 0.2584 - val_loss: 0.7677 - val_mae: 0.6478 - val_rmse: 0.7377 - val_smape: 1.3145

Epoch 73/128

958/958 - 6s - 7ms/step - ia: 0.3579 - loss: 0.9257 - mae: 0.7144 - rmse: 0.9447 - smape: 1.3447 - val_ia: 0.2584 - val_loss: 0.7673 - val_mae: 0.6477 - val_rmse: 0.7375 - val_smape: 1.3146

Epoch 74/128

958/958 - 4s - 4ms/step - ia: 0.3603 - loss: 0.9111 - mae: 0.7104 - rmse: 0.9358 - smape: 1.3445 - val_ia: 0.2583 - val_loss: 0.7674 - val_mae: 0.6477 - val_rmse: 0.7375 - val_smape: 1.3145

Epoch 75/128

958/958 - 5s - 6ms/step - ia: 0.3592 - loss: 0.9151 - mae: 0.7100 - rmse: 0.9386 - smape: 1.3435 - val_ia: 0.2586 - val_loss: 0.7668 - val_mae: 0.6476 - val_rmse: 0.7374 - val_smape: 1.3142

Epoch 76/128

958/958 - 5s - 6ms/step - ia: 0.3574 - loss: 0.9111 - mae: 0.7109 - rmse: 0.9374 - smape: 1.3494 - val_ia: 0.2588 - val_loss: 0.7662 - val_mae: 0.6471 - val_rmse: 0.7371 - val_smape: 1.3114

Epoch 77/128

958/958 - 5s - 5ms/step - ia: 0.3599 - loss: 0.9053 - mae: 0.7084 - rmse: 0.9347 - smape: 1.3418 - val_ia: 0.2591 - val_loss: 0.7659 - val_mae: 0.6468 - val_rmse: 0.7369 - val_smape: 1.3098

Epoch 78/128

958/958 - 6s - 6ms/step - ia: 0.3584 - loss: 0.9045 - mae: 0.7080 - rmse: 0.9346 - smape: 1.3468 - val_ia: 0.2591 - val_loss: 0.7654 - val_mae: 0.6465 - val_rmse: 0.7367 - val_smape: 1.3078

Epoch 79/128

958/958 - 5s - 5ms/step - ia: 0.3619 - loss: 0.9040 - mae: 0.7065 - rmse: 0.9321 - smape: 1.3384 - val_ia: 0.2589 - val_loss: 0.7657 - val_mae: 0.6467 - val_rmse: 0.7369 - val_smape: 1.3083

Epoch 80/128

958/958 - 5s - 5ms/step - ia: 0.3605 - loss: 0.9014 - mae: 0.7067 - rmse: 0.9314 - smape: 1.3424 - val_ia: 0.2590 - val_loss: 0.7656 - val_mae: 0.6465 - val_rmse: 0.7369 - val_smape: 1.3071

Epoch 81/128

958/958 - 5s - 6ms/step - ia: 0.3616 - loss: 0.9028 - mae: 0.7057 - rmse: 0.9334 - smape: 1.3406 - val_ia: 0.2591 - val_loss: 0.7653 - val_mae: 0.6463 - val_rmse: 0.7366 - val_smape: 1.3067

Epoch 82/128

958/958 - 3s - 4ms/step - ia: 0.3557 - loss: 0.9116 - mae: 0.7098 - rmse: 0.9382 - smape: 1.3494 - val_ia: 0.2589 - val_loss: 0.7657 - val_mae: 0.6468 - val_rmse: 0.7370 - val_smape: 1.3104

Epoch 83/128

958/958 - 4s - 4ms/step - ia: 0.3612 - loss: 0.8979 - mae: 0.7030 - rmse: 0.9282 - smape: 1.3384 - val_ia: 0.2591 - val_loss: 0.7650 - val_mae: 0.6464 - val_rmse: 0.7368 - val_smape: 1.3074

Epoch 84/128

958/958 - 5s - 5ms/step - ia: 0.3578 - loss: 0.8982 - mae: 0.7049 - rmse: 0.9298 - smape: 1.3443 - val_ia: 0.2593 - val_loss: 0.7644 - val_mae: 0.6461 - val_rmse: 0.7364 - val_smape: 1.3060

Epoch 85/128

958/958 - 4s - 4ms/step - ia: 0.3620 - loss: 0.8960 - mae: 0.7024 - rmse: 0.9282 - smape: 1.3365 - val_ia: 0.2592 - val_loss: 0.7644 - val_mae: 0.6462 - val_rmse: 0.7365 - val_smape: 1.3062

Epoch 86/128

958/958 - 4s - 4ms/step - ia: 0.3592 - loss: 0.8984 - mae: 0.7049 - rmse: 0.9305 - smape: 1.3440 - val_ia: 0.2590 - val_loss: 0.7652 - val_mae: 0.6467 - val_rmse: 0.7370 - val_smape: 1.3093

Epoch 87/128

958/958 - 5s - 6ms/step - ia: 0.3560 - loss: 0.8971 - mae: 0.7039 - rmse: 0.9298 - smape: 1.3470 - val_ia: 0.2588 - val_loss: 0.7658 - val_mae: 0.6470 - val_rmse: 0.7373 - val_smape: 1.3103

Epoch 88/128

958/958 - 5s - 5ms/step - ia: 0.3601 - loss: 0.8952 - mae: 0.7022 - rmse: 0.9274 - smape: 1.3411 - val_ia: 0.2593 - val_loss: 0.7646 - val_mae: 0.6464 - val_rmse: 0.7368 - val_smape: 1.3076

Epoch 89/128

958/958 - 5s - 6ms/step - ia: 0.3586 - loss: 0.8870 - mae: 0.7007 - rmse: 0.9239 - smape: 1.3432 - val_ia: 0.2594 - val_loss: 0.7641 - val_mae: 0.6459 - val_rmse: 0.7365 - val_smape: 1.3045

Epoch 90/128

958/958 - 4s - 4ms/step - ia: 0.3630 - loss: 0.8818 - mae: 0.6987 - rmse: 0.9215 - smape: 1.3401 - val_ia: 0.2595 - val_loss: 0.7636 - val_mae: 0.6455 - val_rmse: 0.7361 - val_smape: 1.3025

Epoch 91/128

958/958 - 2s - 3ms/step - ia: 0.3615 - loss: 0.8867 - mae: 0.6995 - rmse: 0.9228 - smape: 1.3391 - val_ia: 0.2592 - val_loss: 0.7646 - val_mae: 0.6461 - val_rmse: 0.7365 - val_smape: 1.3057

Epoch 92/128

958/958 - 2s - 2ms/step - ia: 0.3623 - loss: 0.8817 - mae: 0.6979 - rmse: 0.9220 - smape: 1.3341 - val_ia: 0.2594 - val_loss: 0.7635 - val_mae: 0.6456 - val_rmse: 0.7361 - val_smape: 1.3035

Epoch 93/128

958/958 - 3s - 3ms/step - ia: 0.3588 - loss: 0.8910 - mae: 0.7006 - rmse: 0.9252 - smape: 1.3404 - val_ia: 0.2594 - val_loss: 0.7641 - val_mae: 0.6458 - val_rmse: 0.7364 - val_smape: 1.3036

Epoch 94/128

958/958 - 3s - 3ms/step - ia: 0.3637 - loss: 0.8805 - mae: 0.6966 - rmse: 0.9215 - smape: 1.3363 - val_ia: 0.2596 - val_loss: 0.7633 - val_mae: 0.6454 - val_rmse: 0.7359 - val_smape: 1.3024

Epoch 95/128

958/958 - 2s - 3ms/step - ia: 0.3629 - loss: 0.8818 - mae: 0.6969 - rmse: 0.9200 - smape: 1.3380 - val_ia: 0.2596 - val_loss: 0.7635 - val_mae: 0.6456 - val_rmse: 0.7359 - val_smape: 1.3046

Epoch 96/128

958/958 - 3s - 3ms/step - ia: 0.3621 - loss: 0.8805 - mae: 0.6970 - rmse: 0.9193 - smape: 1.3392 - val_ia: 0.2595 - val_loss: 0.7638 - val_mae: 0.6457 - val_rmse: 0.7362 - val_smape: 1.3049

Epoch 97/128

958/958 - 3s - 3ms/step - ia: 0.3599 - loss: 0.8816 - mae: 0.6966 - rmse: 0.9205 - smape: 1.3405 - val_ia: 0.2596 - val_loss: 0.7636 - val_mae: 0.6457 - val_rmse: 0.7361 - val_smape: 1.3044

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

479/479 - 11s - 24ms/step - ia: 0.3830 - loss: 1.3123 - mae: 0.8864 - rmse: 1.1383 - smape: 1.3065 - val_ia: 0.2699 - val_loss: 1.1602 - val_mae: 0.8384 - val_rmse: 0.9916 - val_smape: 1.3589

Epoch 2/128

479/479 - 4s - 8ms/step - ia: 0.3841 - loss: 1.2718 - mae: 0.8682 - rmse: 1.1203 - smape: 1.3033 - val_ia: 0.2716 - val_loss: 1.1088 - val_mae: 0.8133 - val_rmse: 0.9651 - val_smape: 1.3497

Epoch 3/128

479/479 - 2s - 5ms/step - ia: 0.3849 - loss: 1.2321 - mae: 0.8523 - rmse: 1.1027 - smape: 1.3047 - val_ia: 0.2728 - val_loss: 1.0661 - val_mae: 0.7922 - val_rmse: 0.9425 - val_smape: 1.3415

Epoch 4/128

479/479 - 3s - 6ms/step - ia: 0.3815 - loss: 1.2129 - mae: 0.8415 - rmse: 1.0947 - smape: 1.3077 - val_ia: 0.2738 - val_loss: 1.0307 - val_mae: 0.7745 - val_rmse: 0.9233 - val_smape: 1.3342

Epoch 5/128

479/479 - 3s - 6ms/step - ia: 0.3838 - loss: 1.1856 - mae: 0.8301 - rmse: 1.0815 - smape: 1.3032 - val_ia: 0.2748 - val_loss: 1.0026 - val_mae: 0.7602 - val_rmse: 0.9078 - val_smape: 1.3278

Epoch 6/128

479/479 - 2s - 5ms/step - ia: 0.3815 - loss: 1.1679 - mae: 0.8261 - rmse: 1.0736 - smape: 1.3081 - val_ia: 0.2752 - val_loss: 0.9789 - val_mae: 0.7481 - val_rmse: 0.8943 - val_smape: 1.3225

Epoch 7/128

479/479 - 2s - 5ms/step - ia: 0.3794 - loss: 1.1516 - mae: 0.8177 - rmse: 1.0659 - smape: 1.3116 - val_ia: 0.2753 - val_loss: 0.9595 - val_mae: 0.7383 - val_rmse: 0.8833 - val_smape: 1.3195

Epoch 8/128

479/479 - 2s - 5ms/step - ia: 0.3796 - loss: 1.1404 - mae: 0.8134 - rmse: 1.0603 - smape: 1.3127 - val_ia: 0.2752 - val_loss: 0.9434 - val_mae: 0.7303 - val_rmse: 0.8739 - val_smape: 1.3165

Epoch 9/128

479/479 - 2s - 5ms/step - ia: 0.3810 - loss: 1.1177 - mae: 0.8046 - rmse: 1.0491 - smape: 1.3135 - val_ia: 0.2751 - val_loss: 0.9302 - val_mae: 0.7237 - val_rmse: 0.8662 - val_smape: 1.3139

Epoch 10/128

479/479 - 1s - 2ms/step - ia: 0.3800 - loss: 1.1073 - mae: 0.7992 - rmse: 1.0445 - smape: 1.3100 - val_ia: 0.2752 - val_loss: 0.9195 - val_mae: 0.7184 - val_rmse: 0.8599 - val_smape: 1.3123

Epoch 11/128

479/479 - 1s - 2ms/step - ia: 0.3732 - loss: 1.1154 - mae: 0.8032 - rmse: 1.0485 - smape: 1.3241 - val_ia: 0.2751 - val_loss: 0.9103 - val_mae: 0.7138 - val_rmse: 0.8544 - val_smape: 1.3120

Epoch 12/128

479/479 - 1s - 2ms/step - ia: 0.3751 - loss: 1.1010 - mae: 0.7975 - rmse: 1.0424 - smape: 1.3186 - val_ia: 0.2750 - val_loss: 0.9026 - val_mae: 0.7102 - val_rmse: 0.8498 - val_smape: 1.3119

Epoch 13/128

479/479 - 1s - 2ms/step - ia: 0.3729 - loss: 1.0884 - mae: 0.7915 - rmse: 1.0354 - smape: 1.3200 - val_ia: 0.2750 - val_loss: 0.8961 - val_mae: 0.7070 - val_rmse: 0.8459 - val_smape: 1.3119

Epoch 14/128

479/479 - 1s - 2ms/step - ia: 0.3719 - loss: 1.0872 - mae: 0.7911 - rmse: 1.0339 - smape: 1.3222 - val_ia: 0.2750 - val_loss: 0.8902 - val_mae: 0.7042 - val_rmse: 0.8424 - val_smape: 1.3118

Epoch 15/128

479/479 - 1s - 3ms/step - ia: 0.3693 - loss: 1.0811 - mae: 0.7887 - rmse: 1.0312 - smape: 1.3280 - val_ia: 0.2751 - val_loss: 0.8854 - val_mae: 0.7018 - val_rmse: 0.8394 - val_smape: 1.3123

Epoch 16/128

479/479 - 1s - 2ms/step - ia: 0.3690 - loss: 1.0782 - mae: 0.7886 - rmse: 1.0307 - smape: 1.3264 - val_ia: 0.2752 - val_loss: 0.8804 - val_mae: 0.6994 - val_rmse: 0.8364 - val_smape: 1.3120

Epoch 17/128

479/479 - 1s - 2ms/step - ia: 0.3688 - loss: 1.0721 - mae: 0.7861 - rmse: 1.0279 - smape: 1.3279 - val_ia: 0.2753 - val_loss: 0.8760 - val_mae: 0.6972 - val_rmse: 0.8337 - val_smape: 1.3121

Epoch 18/128

479/479 - 2s - 3ms/step - ia: 0.3701 - loss: 1.0593 - mae: 0.7786 - rmse: 1.0215 - smape: 1.3219 - val_ia: 0.2753 - val_loss: 0.8719 - val_mae: 0.6952 - val_rmse: 0.8312 - val_smape: 1.3122

Epoch 19/128

479/479 - 1s - 2ms/step - ia: 0.3689 - loss: 1.0619 - mae: 0.7817 - rmse: 1.0227 - smape: 1.3289 - val_ia: 0.2754 - val_loss: 0.8685 - val_mae: 0.6935 - val_rmse: 0.8291 - val_smape: 1.3132

Epoch 20/128

479/479 - 1s - 3ms/step - ia: 0.3654 - loss: 1.0577 - mae: 0.7799 - rmse: 1.0199 - smape: 1.3360 - val_ia: 0.2755 - val_loss: 0.8654 - val_mae: 0.6920 - val_rmse: 0.8272 - val_smape: 1.3139

Epoch 21/128

479/479 - 1s - 3ms/step - ia: 0.3619 - loss: 1.0626 - mae: 0.7814 - rmse: 1.0216 - smape: 1.3388 - val_ia: 0.2757 - val_loss: 0.8624 - val_mae: 0.6906 - val_rmse: 0.8254 - val_smape: 1.3141

Epoch 22/128

479/479 - 1s - 2ms/step - ia: 0.3669 - loss: 1.0490 - mae: 0.7753 - rmse: 1.0155 - smape: 1.3277 - val_ia: 0.2758 - val_loss: 0.8597 - val_mae: 0.6893 - val_rmse: 0.8237 - val_smape: 1.3148

Epoch 23/128

479/479 - 1s - 3ms/step - ia: 0.3640 - loss: 1.0521 - mae: 0.7752 - rmse: 1.0170 - smape: 1.3331 - val_ia: 0.2759 - val_loss: 0.8570 - val_mae: 0.6879 - val_rmse: 0.8221 - val_smape: 1.3150

Epoch 24/128

479/479 - 1s - 3ms/step - ia: 0.3641 - loss: 1.0489 - mae: 0.7742 - rmse: 1.0154 - smape: 1.3331 - val_ia: 0.2760 - val_loss: 0.8550 - val_mae: 0.6870 - val_rmse: 0.8208 - val_smape: 1.3159

Epoch 25/128

479/479 - 1s - 2ms/step - ia: 0.3635 - loss: 1.0434 - mae: 0.7747 - rmse: 1.0131 - smape: 1.3348 - val_ia: 0.2761 - val_loss: 0.8525 - val_mae: 0.6858 - val_rmse: 0.8193 - val_smape: 1.3161

Epoch 26/128

479/479 - 1s - 3ms/step - ia: 0.3660 - loss: 1.0433 - mae: 0.7708 - rmse: 1.0131 - smape: 1.3291 - val_ia: 0.2762 - val_loss: 0.8502 - val_mae: 0.6847 - val_rmse: 0.8179 - val_smape: 1.3159

Epoch 27/128

479/479 - 1s - 2ms/step - ia: 0.3621 - loss: 1.0406 - mae: 0.7713 - rmse: 1.0112 - smape: 1.3341 - val_ia: 0.2764 - val_loss: 0.8481 - val_mae: 0.6836 - val_rmse: 0.8166 - val_smape: 1.3159

Epoch 28/128

479/479 - 1s - 2ms/step - ia: 0.3626 - loss: 1.0339 - mae: 0.7700 - rmse: 1.0082 - smape: 1.3395 - val_ia: 0.2766 - val_loss: 0.8462 - val_mae: 0.6827 - val_rmse: 0.8155 - val_smape: 1.3159

Epoch 29/128

479/479 - 1s - 2ms/step - ia: 0.3631 - loss: 1.0382 - mae: 0.7679 - rmse: 1.0100 - smape: 1.3331 - val_ia: 0.2767 - val_loss: 0.8442 - val_mae: 0.6818 - val_rmse: 0.8143 - val_smape: 1.3157

Epoch 30/128

479/479 - 1s - 2ms/step - ia: 0.3647 - loss: 1.0316 - mae: 0.7649 - rmse: 1.0078 - smape: 1.3288 - val_ia: 0.2769 - val_loss: 0.8425 - val_mae: 0.6809 - val_rmse: 0.8132 - val_smape: 1.3160

Epoch 31/128

479/479 - 1s - 2ms/step - ia: 0.3605 - loss: 1.0234 - mae: 0.7652 - rmse: 1.0037 - smape: 1.3357 - val_ia: 0.2770 - val_loss: 0.8409 - val_mae: 0.6801 - val_rmse: 0.8122 - val_smape: 1.3159

Epoch 32/128

479/479 - 1s - 2ms/step - ia: 0.3628 - loss: 1.0265 - mae: 0.7648 - rmse: 1.0037 - smape: 1.3368 - val_ia: 0.2771 - val_loss: 0.8392 - val_mae: 0.6794 - val_rmse: 0.8112 - val_smape: 1.3159

Epoch 33/128

479/479 - 1s - 3ms/step - ia: 0.3615 - loss: 1.0247 - mae: 0.7630 - rmse: 1.0045 - smape: 1.3356 - val_ia: 0.2773 - val_loss: 0.8377 - val_mae: 0.6786 - val_rmse: 0.8103 - val_smape: 1.3157

Epoch 34/128

479/479 - 1s - 2ms/step - ia: 0.3618 - loss: 1.0185 - mae: 0.7614 - rmse: 1.0004 - smape: 1.3368 - val_ia: 0.2775 - val_loss: 0.8362 - val_mae: 0.6778 - val_rmse: 0.8094 - val_smape: 1.3149

Epoch 35/128

479/479 - 1s - 2ms/step - ia: 0.3606 - loss: 1.0216 - mae: 0.7607 - rmse: 1.0018 - smape: 1.3352 - val_ia: 0.2777 - val_loss: 0.8347 - val_mae: 0.6771 - val_rmse: 0.8085 - val_smape: 1.3138

Epoch 36/128

479/479 - 1s - 3ms/step - ia: 0.3620 - loss: 1.0170 - mae: 0.7601 - rmse: 0.9993 - smape: 1.3346 - val_ia: 0.2779 - val_loss: 0.8331 - val_mae: 0.6763 - val_rmse: 0.8076 - val_smape: 1.3132

Epoch 37/128

479/479 - 1s - 2ms/step - ia: 0.3640 - loss: 1.0127 - mae: 0.7583 - rmse: 0.9973 - smape: 1.3334 - val_ia: 0.2781 - val_loss: 0.8320 - val_mae: 0.6758 - val_rmse: 0.8069 - val_smape: 1.3129

Epoch 38/128

479/479 - 1s - 2ms/step - ia: 0.3628 - loss: 1.0134 - mae: 0.7575 - rmse: 0.9977 - smape: 1.3322 - val_ia: 0.2783 - val_loss: 0.8307 - val_mae: 0.6751 - val_rmse: 0.8062 - val_smape: 1.3119

Epoch 39/128

479/479 - 1s - 3ms/step - ia: 0.3654 - loss: 1.0079 - mae: 0.7549 - rmse: 0.9941 - smape: 1.3314 - val_ia: 0.2784 - val_loss: 0.8291 - val_mae: 0.6743 - val_rmse: 0.8053 - val_smape: 1.3110

Epoch 40/128

479/479 - 2s - 3ms/step - ia: 0.3677 - loss: 1.0022 - mae: 0.7528 - rmse: 0.9922 - smape: 1.3267 - val_ia: 0.2786 - val_loss: 0.8281 - val_mae: 0.6738 - val_rmse: 0.8047 - val_smape: 1.3105

Epoch 41/128

479/479 - 3s - 5ms/step - ia: 0.3601 - loss: 1.0125 - mae: 0.7572 - rmse: 0.9973 - smape: 1.3362 - val_ia: 0.2788 - val_loss: 0.8267 - val_mae: 0.6731 - val_rmse: 0.8038 - val_smape: 1.3093

Epoch 42/128

479/479 - 2s - 5ms/step - ia: 0.3623 - loss: 1.0056 - mae: 0.7555 - rmse: 0.9944 - smape: 1.3345 - val_ia: 0.2789 - val_loss: 0.8258 - val_mae: 0.6727 - val_rmse: 0.8033 - val_smape: 1.3089

Epoch 43/128

479/479 - 3s - 7ms/step - ia: 0.3656 - loss: 0.9977 - mae: 0.7503 - rmse: 0.9894 - smape: 1.3282 - val_ia: 0.2791 - val_loss: 0.8248 - val_mae: 0.6722 - val_rmse: 0.8027 - val_smape: 1.3088

Epoch 44/128

479/479 - 2s - 5ms/step - ia: 0.3650 - loss: 0.9989 - mae: 0.7496 - rmse: 0.9898 - smape: 1.3258 - val_ia: 0.2792 - val_loss: 0.8239 - val_mae: 0.6718 - val_rmse: 0.8021 - val_smape: 1.3088

Epoch 45/128

479/479 - 3s - 7ms/step - ia: 0.3643 - loss: 0.9995 - mae: 0.7522 - rmse: 0.9914 - smape: 1.3302 - val_ia: 0.2794 - val_loss: 0.8227 - val_mae: 0.6712 - val_rmse: 0.8015 - val_smape: 1.3081

Epoch 46/128

479/479 - 5s - 10ms/step - ia: 0.3630 - loss: 0.9979 - mae: 0.7511 - rmse: 0.9904 - smape: 1.3285 - val_ia: 0.2796 - val_loss: 0.8215 - val_mae: 0.6706 - val_rmse: 0.8008 - val_smape: 1.3074

Epoch 47/128

479/479 - 2s - 5ms/step - ia: 0.3654 - loss: 0.9913 - mae: 0.7481 - rmse: 0.9864 - smape: 1.3270 - val_ia: 0.2797 - val_loss: 0.8208 - val_mae: 0.6703 - val_rmse: 0.8004 - val_smape: 1.3075

Epoch 48/128

479/479 - 2s - 4ms/step - ia: 0.3632 - loss: 0.9883 - mae: 0.7486 - rmse: 0.9852 - smape: 1.3328 - val_ia: 0.2799 - val_loss: 0.8197 - val_mae: 0.6697 - val_rmse: 0.7997 - val_smape: 1.3065

Epoch 49/128

479/479 - 3s - 5ms/step - ia: 0.3632 - loss: 0.9958 - mae: 0.7492 - rmse: 0.9896 - smape: 1.3319 - val_ia: 0.2800 - val_loss: 0.8188 - val_mae: 0.6693 - val_rmse: 0.7992 - val_smape: 1.3058

Epoch 50/128

479/479 - 2s - 5ms/step - ia: 0.3641 - loss: 0.9923 - mae: 0.7485 - rmse: 0.9881 - smape: 1.3298 - val_ia: 0.2801 - val_loss: 0.8175 - val_mae: 0.6686 - val_rmse: 0.7984 - val_smape: 1.3049

Epoch 51/128

479/479 - 2s - 4ms/step - ia: 0.3673 - loss: 0.9832 - mae: 0.7444 - rmse: 0.9825 - smape: 1.3283 - val_ia: 0.2802 - val_loss: 0.8165 - val_mae: 0.6682 - val_rmse: 0.7979 - val_smape: 1.3044

Epoch 52/128

479/479 - 2s - 5ms/step - ia: 0.3659 - loss: 0.9848 - mae: 0.7447 - rmse: 0.9840 - smape: 1.3294 - val_ia: 0.2803 - val_loss: 0.8155 - val_mae: 0.6677 - val_rmse: 0.7973 - val_smape: 1.3037

Epoch 53/128

479/479 - 3s - 6ms/step - ia: 0.3610 - loss: 0.9895 - mae: 0.7485 - rmse: 0.9864 - smape: 1.3342 - val_ia: 0.2804 - val_loss: 0.8147 - val_mae: 0.6673 - val_rmse: 0.7969 - val_smape: 1.3032

Epoch 54/128

479/479 - 3s - 6ms/step - ia: 0.3659 - loss: 0.9763 - mae: 0.7415 - rmse: 0.9797 - smape: 1.3247 - val_ia: 0.2805 - val_loss: 0.8139 - val_mae: 0.6669 - val_rmse: 0.7964 - val_smape: 1.3026

Epoch 55/128

479/479 - 2s - 5ms/step - ia: 0.3679 - loss: 0.9800 - mae: 0.7413 - rmse: 0.9810 - smape: 1.3246 - val_ia: 0.2806 - val_loss: 0.8132 - val_mae: 0.6666 - val_rmse: 0.7960 - val_smape: 1.3024

Epoch 56/128

479/479 - 2s - 4ms/step - ia: 0.3661 - loss: 0.9785 - mae: 0.7418 - rmse: 0.9808 - smape: 1.3235 - val_ia: 0.2807 - val_loss: 0.8126 - val_mae: 0.6663 - val_rmse: 0.7956 - val_smape: 1.3023

Epoch 57/128

479/479 - 2s - 3ms/step - ia: 0.3652 - loss: 0.9745 - mae: 0.7424 - rmse: 0.9782 - smape: 1.3298 - val_ia: 0.2808 - val_loss: 0.8120 - val_mae: 0.6661 - val_rmse: 0.7953 - val_smape: 1.3019

Epoch 58/128

479/479 - 3s - 6ms/step - ia: 0.3652 - loss: 0.9754 - mae: 0.7405 - rmse: 0.9786 - smape: 1.3280 - val_ia: 0.2808 - val_loss: 0.8114 - val_mae: 0.6659 - val_rmse: 0.7950 - val_smape: 1.3016

Epoch 59/128

479/479 - 3s - 7ms/step - ia: 0.3672 - loss: 0.9804 - mae: 0.7415 - rmse: 0.9819 - smape: 1.3258 - val_ia: 0.2809 - val_loss: 0.8108 - val_mae: 0.6656 - val_rmse: 0.7946 - val_smape: 1.3014

Epoch 60/128

479/479 - 2s - 5ms/step - ia: 0.3652 - loss: 0.9723 - mae: 0.7406 - rmse: 0.9771 - smape: 1.3305 - val_ia: 0.2810 - val_loss: 0.8102 - val_mae: 0.6653 - val_rmse: 0.7943 - val_smape: 1.3010

Epoch 61/128

479/479 - 3s - 6ms/step - ia: 0.3694 - loss: 0.9687 - mae: 0.7346 - rmse: 0.9760 - smape: 1.3188 - val_ia: 0.2812 - val_loss: 0.8094 - val_mae: 0.6649 - val_rmse: 0.7939 - val_smape: 1.3003

Epoch 62/128

479/479 - 2s - 5ms/step - ia: 0.3692 - loss: 0.9661 - mae: 0.7368 - rmse: 0.9738 - smape: 1.3215 - val_ia: 0.2812 - val_loss: 0.8088 - val_mae: 0.6646 - val_rmse: 0.7935 - val_smape: 1.3000

Epoch 63/128

479/479 - 2s - 4ms/step - ia: 0.3688 - loss: 0.9639 - mae: 0.7366 - rmse: 0.9728 - smape: 1.3235 - val_ia: 0.2813 - val_loss: 0.8083 - val_mae: 0.6644 - val_rmse: 0.7932 - val_smape: 1.2997

Epoch 64/128

479/479 - 3s - 7ms/step - ia: 0.3712 - loss: 0.9666 - mae: 0.7360 - rmse: 0.9746 - smape: 1.3183 - val_ia: 0.2814 - val_loss: 0.8077 - val_mae: 0.6641 - val_rmse: 0.7929 - val_smape: 1.2996

Epoch 65/128

479/479 - 2s - 5ms/step - ia: 0.3677 - loss: 0.9712 - mae: 0.7360 - rmse: 0.9766 - smape: 1.3217 - val_ia: 0.2815 - val_loss: 0.8073 - val_mae: 0.6639 - val_rmse: 0.7927 - val_smape: 1.2991

Epoch 66/128

479/479 - 3s - 5ms/step - ia: 0.3676 - loss: 0.9696 - mae: 0.7361 - rmse: 0.9754 - smape: 1.3225 - val_ia: 0.2815 - val_loss: 0.8064 - val_mae: 0.6635 - val_rmse: 0.7922 - val_smape: 1.2984

Epoch 67/128

479/479 - 2s - 4ms/step - ia: 0.3676 - loss: 0.9665 - mae: 0.7345 - rmse: 0.9740 - smape: 1.3228 - val_ia: 0.2817 - val_loss: 0.8055 - val_mae: 0.6630 - val_rmse: 0.7917 - val_smape: 1.2968

Epoch 68/128

479/479 - 3s - 6ms/step - ia: 0.3671 - loss: 0.9581 - mae: 0.7341 - rmse: 0.9693 - smape: 1.3263 - val_ia: 0.2819 - val_loss: 0.8050 - val_mae: 0.6628 - val_rmse: 0.7914 - val_smape: 1.2961

Epoch 69/128

479/479 - 3s - 6ms/step - ia: 0.3694 - loss: 0.9655 - mae: 0.7343 - rmse: 0.9729 - smape: 1.3233 - val_ia: 0.2819 - val_loss: 0.8046 - val_mae: 0.6626 - val_rmse: 0.7912 - val_smape: 1.2959

Epoch 70/128

479/479 - 2s - 5ms/step - ia: 0.3679 - loss: 0.9607 - mae: 0.7338 - rmse: 0.9704 - smape: 1.3228 - val_ia: 0.2820 - val_loss: 0.8042 - val_mae: 0.6624 - val_rmse: 0.7910 - val_smape: 1.2952

Epoch 71/128

479/479 - 2s - 3ms/step - ia: 0.3713 - loss: 0.9569 - mae: 0.7305 - rmse: 0.9689 - smape: 1.3162 - val_ia: 0.2821 - val_loss: 0.8035 - val_mae: 0.6621 - val_rmse: 0.7906 - val_smape: 1.2945

Epoch 72/128

479/479 - 3s - 5ms/step - ia: 0.3706 - loss: 0.9562 - mae: 0.7317 - rmse: 0.9697 - smape: 1.3199 - val_ia: 0.2822 - val_loss: 0.8032 - val_mae: 0.6620 - val_rmse: 0.7904 - val_smape: 1.2946

Epoch 73/128

479/479 - 2s - 5ms/step - ia: 0.3720 - loss: 0.9504 - mae: 0.7288 - rmse: 0.9662 - smape: 1.3173 - val_ia: 0.2822 - val_loss: 0.8026 - val_mae: 0.6617 - val_rmse: 0.7901 - val_smape: 1.2942

Epoch 74/128

479/479 - 3s - 6ms/step - ia: 0.3708 - loss: 0.9503 - mae: 0.7287 - rmse: 0.9657 - smape: 1.3193 - val_ia: 0.2824 - val_loss: 0.8022 - val_mae: 0.6614 - val_rmse: 0.7898 - val_smape: 1.2935

Epoch 75/128

479/479 - 2s - 4ms/step - ia: 0.3688 - loss: 0.9513 - mae: 0.7301 - rmse: 0.9665 - smape: 1.3213 - val_ia: 0.2825 - val_loss: 0.8018 - val_mae: 0.6612 - val_rmse: 0.7896 - val_smape: 1.2930

Epoch 76/128

479/479 - 2s - 5ms/step - ia: 0.3668 - loss: 0.9516 - mae: 0.7304 - rmse: 0.9665 - smape: 1.3238 - val_ia: 0.2826 - val_loss: 0.8014 - val_mae: 0.6611 - val_rmse: 0.7894 - val_smape: 1.2923

Epoch 77/128

479/479 - 2s - 5ms/step - ia: 0.3728 - loss: 0.9527 - mae: 0.7274 - rmse: 0.9675 - smape: 1.3127 - val_ia: 0.2826 - val_loss: 0.8011 - val_mae: 0.6609 - val_rmse: 0.7892 - val_smape: 1.2921

Epoch 78/128

479/479 - 1s - 3ms/step - ia: 0.3714 - loss: 0.9488 - mae: 0.7269 - rmse: 0.9646 - smape: 1.3155 - val_ia: 0.2827 - val_loss: 0.8005 - val_mae: 0.6606 - val_rmse: 0.7889 - val_smape: 1.2915

Epoch 79/128

479/479 - 1s - 3ms/step - ia: 0.3700 - loss: 0.9510 - mae: 0.7295 - rmse: 0.9656 - smape: 1.3216 - val_ia: 0.2828 - val_loss: 0.7999 - val_mae: 0.6604 - val_rmse: 0.7886 - val_smape: 1.2908

Epoch 80/128

479/479 - 2s - 5ms/step - ia: 0.3689 - loss: 0.9548 - mae: 0.7296 - rmse: 0.9681 - smape: 1.3208 - val_ia: 0.2829 - val_loss: 0.7995 - val_mae: 0.6602 - val_rmse: 0.7884 - val_smape: 1.2906

Epoch 81/128

479/479 - 1s - 3ms/step - ia: 0.3716 - loss: 0.9437 - mae: 0.7264 - rmse: 0.9626 - smape: 1.3207 - val_ia: 0.2830 - val_loss: 0.7994 - val_mae: 0.6602 - val_rmse: 0.7884 - val_smape: 1.2905

Epoch 82/128

479/479 - 1s - 3ms/step - ia: 0.3699 - loss: 0.9464 - mae: 0.7268 - rmse: 0.9631 - smape: 1.3213 - val_ia: 0.2830 - val_loss: 0.7989 - val_mae: 0.6599 - val_rmse: 0.7881 - val_smape: 1.2901

Epoch 83/128

479/479 - 1s - 3ms/step - ia: 0.3707 - loss: 0.9485 - mae: 0.7259 - rmse: 0.9658 - smape: 1.3179 - val_ia: 0.2831 - val_loss: 0.7985 - val_mae: 0.6598 - val_rmse: 0.7879 - val_smape: 1.2897

Epoch 84/128

479/479 - 2s - 5ms/step - ia: 0.3720 - loss: 0.9425 - mae: 0.7252 - rmse: 0.9625 - smape: 1.3147 - val_ia: 0.2831 - val_loss: 0.7979 - val_mae: 0.6595 - val_rmse: 0.7875 - val_smape: 1.2891

Epoch 85/128

479/479 - 1s - 3ms/step - ia: 0.3706 - loss: 0.9440 - mae: 0.7253 - rmse: 0.9627 - smape: 1.3195 - val_ia: 0.2832 - val_loss: 0.7976 - val_mae: 0.6593 - val_rmse: 0.7874 - val_smape: 1.2890

Epoch 86/128

479/479 - 1s - 3ms/step - ia: 0.3727 - loss: 0.9411 - mae: 0.7237 - rmse: 0.9610 - smape: 1.3179 - val_ia: 0.2833 - val_loss: 0.7973 - val_mae: 0.6592 - val_rmse: 0.7872 - val_smape: 1.2887

Epoch 87/128

479/479 - 1s - 2ms/step - ia: 0.3695 - loss: 0.9443 - mae: 0.7256 - rmse: 0.9623 - smape: 1.3234 - val_ia: 0.2834 - val_loss: 0.7969 - val_mae: 0.6591 - val_rmse: 0.7870 - val_smape: 1.2884

Epoch 88/128

479/479 - 2s - 4ms/step - ia: 0.3721 - loss: 0.9370 - mae: 0.7227 - rmse: 0.9590 - smape: 1.3137 - val_ia: 0.2834 - val_loss: 0.7967 - val_mae: 0.6590 - val_rmse: 0.7870 - val_smape: 1.2885

Epoch 89/128

479/479 - 1s - 3ms/step - ia: 0.3707 - loss: 0.9386 - mae: 0.7232 - rmse: 0.9584 - smape: 1.3189 - val_ia: 0.2835 - val_loss: 0.7963 - val_mae: 0.6588 - val_rmse: 0.7868 - val_smape: 1.2881

Epoch 90/128

479/479 - 1s - 3ms/step - ia: 0.3728 - loss: 0.9370 - mae: 0.7214 - rmse: 0.9579 - smape: 1.3153 - val_ia: 0.2835 - val_loss: 0.7959 - val_mae: 0.6586 - val_rmse: 0.7865 - val_smape: 1.2877

Epoch 91/128

479/479 - 2s - 5ms/step - ia: 0.3715 - loss: 0.9376 - mae: 0.7232 - rmse: 0.9584 - smape: 1.3174 - val_ia: 0.2835 - val_loss: 0.7955 - val_mae: 0.6584 - val_rmse: 0.7862 - val_smape: 1.2874

Epoch 92/128

479/479 - 2s - 3ms/step - ia: 0.3724 - loss: 0.9363 - mae: 0.7210 - rmse: 0.9594 - smape: 1.3127 - val_ia: 0.2835 - val_loss: 0.7952 - val_mae: 0.6583 - val_rmse: 0.7861 - val_smape: 1.2874

Epoch 93/128

479/479 - 3s - 7ms/step - ia: 0.3712 - loss: 0.9359 - mae: 0.7216 - rmse: 0.9589 - smape: 1.3168 - val_ia: 0.2836 - val_loss: 0.7952 - val_mae: 0.6583 - val_rmse: 0.7861 - val_smape: 1.2875

Epoch 94/128

479/479 - 2s - 4ms/step - ia: 0.3743 - loss: 0.9277 - mae: 0.7194 - rmse: 0.9541 - smape: 1.3150 - val_ia: 0.2836 - val_loss: 0.7950 - val_mae: 0.6582 - val_rmse: 0.7860 - val_smape: 1.2871

Epoch 95/128

479/479 - 2s - 3ms/step - ia: 0.3719 - loss: 0.9350 - mae: 0.7209 - rmse: 0.9574 - smape: 1.3167 - val_ia: 0.2837 - val_loss: 0.7946 - val_mae: 0.6580 - val_rmse: 0.7858 - val_smape: 1.2866

Epoch 96/128

479/479 - 1s - 3ms/step - ia: 0.3702 - loss: 0.9379 - mae: 0.7224 - rmse: 0.9594 - smape: 1.3202 - val_ia: 0.2837 - val_loss: 0.7943 - val_mae: 0.6579 - val_rmse: 0.7856 - val_smape: 1.2863

Epoch 97/128

479/479 - 2s - 4ms/step - ia: 0.3723 - loss: 0.9370 - mae: 0.7209 - rmse: 0.9587 - smape: 1.3137 - val_ia: 0.2838 - val_loss: 0.7941 - val_mae: 0.6578 - val_rmse: 0.7855 - val_smape: 1.2863

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 10s - 43ms/step - ia: 0.3519 - loss: 2.1760 - mae: 1.0875 - rmse: 1.4696 - smape: 1.2658 - val_ia: 0.4065 - val_loss: 1.5826 - val_mae: 0.8290 - val_rmse: 1.0911 - val_smape: 1.0307

Epoch 2/128

240/240 - 1s - 6ms/step - ia: 0.3536 - loss: 1.9875 - mae: 1.0293 - rmse: 1.4048 - smape: 1.2695 - val_ia: 0.3958 - val_loss: 1.4266 - val_mae: 0.7708 - val_rmse: 1.0213 - val_smape: 1.0141

Epoch 3/128

240/240 - 2s - 6ms/step - ia: 0.3502 - loss: 1.8553 - mae: 0.9868 - rmse: 1.3562 - smape: 1.2811 - val_ia: 0.3686 - val_loss: 1.2991 - val_mae: 0.7292 - val_rmse: 0.9636 - val_smape: 1.0132

Epoch 4/128

240/240 - 2s - 7ms/step - ia: 0.3467 - loss: 1.7299 - mae: 0.9513 - rmse: 1.3091 - smape: 1.2958 - val_ia: 0.3361 - val_loss: 1.1976 - val_mae: 0.7010 - val_rmse: 0.9185 - val_smape: 1.0272

Epoch 5/128

240/240 - 2s - 9ms/step - ia: 0.3433 - loss: 1.6181 - mae: 0.9181 - rmse: 1.2648 - smape: 1.3067 - val_ia: 0.3108 - val_loss: 1.1177 - val_mae: 0.6838 - val_rmse: 0.8851 - val_smape: 1.0562

Epoch 6/128

240/240 - 1s - 5ms/step - ia: 0.3386 - loss: 1.5409 - mae: 0.8987 - rmse: 1.2364 - smape: 1.3221 - val_ia: 0.2852 - val_loss: 1.0557 - val_mae: 0.6746 - val_rmse: 0.8619 - val_smape: 1.0995

Epoch 7/128

240/240 - 1s - 6ms/step - ia: 0.3313 - loss: 1.4777 - mae: 0.8832 - rmse: 1.2086 - smape: 1.3380 - val_ia: 0.2712 - val_loss: 1.0092 - val_mae: 0.6715 - val_rmse: 0.8471 - val_smape: 1.1560

Epoch 8/128

240/240 - 1s - 5ms/step - ia: 0.3243 - loss: 1.4254 - mae: 0.8739 - rmse: 1.1888 - smape: 1.3574 - val_ia: 0.2595 - val_loss: 0.9754 - val_mae: 0.6728 - val_rmse: 0.8389 - val_smape: 1.2244

Epoch 9/128

240/240 - 1s - 6ms/step - ia: 0.3186 - loss: 1.3991 - mae: 0.8674 - rmse: 1.1760 - smape: 1.3692 - val_ia: 0.2536 - val_loss: 0.9508 - val_mae: 0.6766 - val_rmse: 0.8352 - val_smape: 1.3027

Epoch 10/128

240/240 - 1s - 5ms/step - ia: 0.3150 - loss: 1.3565 - mae: 0.8607 - rmse: 1.1585 - smape: 1.3799 - val_ia: 0.2520 - val_loss: 0.9335 - val_mae: 0.6819 - val_rmse: 0.8347 - val_smape: 1.3901

Epoch 11/128

240/240 - 1s - 4ms/step - ia: 0.3111 - loss: 1.3476 - mae: 0.8604 - rmse: 1.1548 - smape: 1.3891 - val_ia: 0.2542 - val_loss: 0.9218 - val_mae: 0.6875 - val_rmse: 0.8360 - val_smape: 1.4783

Epoch 12/128

240/240 - 1s - 5ms/step - ia: 0.3090 - loss: 1.3278 - mae: 0.8578 - rmse: 1.1458 - smape: 1.3954 - val_ia: 0.2576 - val_loss: 0.9136 - val_mae: 0.6928 - val_rmse: 0.8380 - val_smape: 1.5541

Epoch 13/128

240/240 - 1s - 4ms/step - ia: 0.3015 - loss: 1.3278 - mae: 0.8623 - rmse: 1.1469 - smape: 1.4072 - val_ia: 0.2600 - val_loss: 0.9077 - val_mae: 0.6974 - val_rmse: 0.8400 - val_smape: 1.6100

Epoch 14/128

240/240 - 1s - 5ms/step - ia: 0.3045 - loss: 1.2997 - mae: 0.8583 - rmse: 1.1342 - smape: 1.4090 - val_ia: 0.2616 - val_loss: 0.9033 - val_mae: 0.7010 - val_rmse: 0.8418 - val_smape: 1.6396

Epoch 15/128

240/240 - 2s - 7ms/step - ia: 0.3074 - loss: 1.2791 - mae: 0.8510 - rmse: 1.1258 - smape: 1.4035 - val_ia: 0.2629 - val_loss: 0.8997 - val_mae: 0.7038 - val_rmse: 0.8433 - val_smape: 1.6546

Epoch 16/128

240/240 - 1s - 4ms/step - ia: 0.3044 - loss: 1.2768 - mae: 0.8517 - rmse: 1.1257 - smape: 1.4071 - val_ia: 0.2637 - val_loss: 0.8959 - val_mae: 0.7052 - val_rmse: 0.8436 - val_smape: 1.6573

Epoch 17/128

240/240 - 1s - 4ms/step - ia: 0.3059 - loss: 1.2723 - mae: 0.8522 - rmse: 1.1232 - smape: 1.4088 - val_ia: 0.2645 - val_loss: 0.8926 - val_mae: 0.7065 - val_rmse: 0.8441 - val_smape: 1.6576

Epoch 18/128

240/240 - 1s - 6ms/step - ia: 0.3024 - loss: 1.2728 - mae: 0.8539 - rmse: 1.1224 - smape: 1.4143 - val_ia: 0.2652 - val_loss: 0.8895 - val_mae: 0.7074 - val_rmse: 0.8443 - val_smape: 1.6551

Epoch 19/128

240/240 - 2s - 7ms/step - ia: 0.3043 - loss: 1.2649 - mae: 0.8513 - rmse: 1.1201 - smape: 1.4120 - val_ia: 0.2658 - val_loss: 0.8861 - val_mae: 0.7067 - val_rmse: 0.8434 - val_smape: 1.6467

Epoch 20/128

240/240 - 1s - 4ms/step - ia: 0.3062 - loss: 1.2515 - mae: 0.8455 - rmse: 1.1140 - smape: 1.4149 - val_ia: 0.2664 - val_loss: 0.8826 - val_mae: 0.7064 - val_rmse: 0.8427 - val_smape: 1.6383

Epoch 21/128

240/240 - 1s - 6ms/step - ia: 0.3089 - loss: 1.2407 - mae: 0.8443 - rmse: 1.1102 - smape: 1.4101 - val_ia: 0.2671 - val_loss: 0.8792 - val_mae: 0.7053 - val_rmse: 0.8414 - val_smape: 1.6281

Epoch 22/128

240/240 - 1s - 4ms/step - ia: 0.3067 - loss: 1.2315 - mae: 0.8424 - rmse: 1.1051 - smape: 1.4116 - val_ia: 0.2677 - val_loss: 0.8756 - val_mae: 0.7038 - val_rmse: 0.8399 - val_smape: 1.6168

Epoch 23/128

240/240 - 1s - 5ms/step - ia: 0.3105 - loss: 1.2246 - mae: 0.8392 - rmse: 1.1025 - smape: 1.4048 - val_ia: 0.2684 - val_loss: 0.8728 - val_mae: 0.7032 - val_rmse: 0.8391 - val_smape: 1.6084

Epoch 24/128

240/240 - 1s - 5ms/step - ia: 0.3116 - loss: 1.2186 - mae: 0.8348 - rmse: 1.0983 - smape: 1.4035 - val_ia: 0.2691 - val_loss: 0.8696 - val_mae: 0.7021 - val_rmse: 0.8379 - val_smape: 1.5986

Epoch 25/128

240/240 - 1s - 5ms/step - ia: 0.3124 - loss: 1.2184 - mae: 0.8361 - rmse: 1.0983 - smape: 1.4034 - val_ia: 0.2698 - val_loss: 0.8667 - val_mae: 0.7014 - val_rmse: 0.8370 - val_smape: 1.5900

Epoch 26/128

240/240 - 1s - 4ms/step - ia: 0.3156 - loss: 1.2056 - mae: 0.8306 - rmse: 1.0929 - smape: 1.3961 - val_ia: 0.2704 - val_loss: 0.8637 - val_mae: 0.7001 - val_rmse: 0.8357 - val_smape: 1.5803

Epoch 27/128

240/240 - 2s - 6ms/step - ia: 0.3145 - loss: 1.1941 - mae: 0.8294 - rmse: 1.0878 - smape: 1.4012 - val_ia: 0.2711 - val_loss: 0.8607 - val_mae: 0.6985 - val_rmse: 0.8342 - val_smape: 1.5701

Epoch 28/128

240/240 - 1s - 6ms/step - ia: 0.3111 - loss: 1.1934 - mae: 0.8299 - rmse: 1.0874 - smape: 1.4084 - val_ia: 0.2717 - val_loss: 0.8580 - val_mae: 0.6971 - val_rmse: 0.8329 - val_smape: 1.5607

Epoch 29/128

240/240 - 1s - 5ms/step - ia: 0.3141 - loss: 1.1965 - mae: 0.8293 - rmse: 1.0886 - smape: 1.4053 - val_ia: 0.2724 - val_loss: 0.8555 - val_mae: 0.6959 - val_rmse: 0.8318 - val_smape: 1.5523

Epoch 30/128

240/240 - 2s - 8ms/step - ia: 0.3170 - loss: 1.1805 - mae: 0.8225 - rmse: 1.0807 - smape: 1.3961 - val_ia: 0.2730 - val_loss: 0.8528 - val_mae: 0.6947 - val_rmse: 0.8306 - val_smape: 1.5436

Epoch 31/128

240/240 - 3s - 11ms/step - ia: 0.3141 - loss: 1.1851 - mae: 0.8258 - rmse: 1.0846 - smape: 1.4017 - val_ia: 0.2737 - val_loss: 0.8506 - val_mae: 0.6937 - val_rmse: 0.8297 - val_smape: 1.5362

Epoch 32/128

240/240 - 1s - 4ms/step - ia: 0.3196 - loss: 1.1726 - mae: 0.8174 - rmse: 1.0767 - smape: 1.3894 - val_ia: 0.2745 - val_loss: 0.8486 - val_mae: 0.6926 - val_rmse: 0.8287 - val_smape: 1.5286

Epoch 33/128

240/240 - 1s - 6ms/step - ia: 0.3191 - loss: 1.1541 - mae: 0.8142 - rmse: 1.0706 - smape: 1.3911 - val_ia: 0.2751 - val_loss: 0.8467 - val_mae: 0.6921 - val_rmse: 0.8282 - val_smape: 1.5226

Epoch 34/128

240/240 - 1s - 6ms/step - ia: 0.3179 - loss: 1.1661 - mae: 0.8184 - rmse: 1.0751 - smape: 1.3979 - val_ia: 0.2758 - val_loss: 0.8448 - val_mae: 0.6915 - val_rmse: 0.8276 - val_smape: 1.5168

Epoch 35/128

240/240 - 1s - 6ms/step - ia: 0.3217 - loss: 1.1455 - mae: 0.8113 - rmse: 1.0652 - smape: 1.3918 - val_ia: 0.2764 - val_loss: 0.8427 - val_mae: 0.6901 - val_rmse: 0.8265 - val_smape: 1.5090

Epoch 36/128

240/240 - 1s - 4ms/step - ia: 0.3219 - loss: 1.1488 - mae: 0.8097 - rmse: 1.0685 - smape: 1.3888 - val_ia: 0.2770 - val_loss: 0.8409 - val_mae: 0.6892 - val_rmse: 0.8256 - val_smape: 1.5025

Epoch 37/128

240/240 - 1s - 4ms/step - ia: 0.3179 - loss: 1.1529 - mae: 0.8141 - rmse: 1.0685 - smape: 1.3963 - val_ia: 0.2775 - val_loss: 0.8390 - val_mae: 0.6880 - val_rmse: 0.8246 - val_smape: 1.4955

Epoch 38/128

240/240 - 1s - 6ms/step - ia: 0.3221 - loss: 1.1360 - mae: 0.8085 - rmse: 1.0619 - smape: 1.3937 - val_ia: 0.2781 - val_loss: 0.8373 - val_mae: 0.6872 - val_rmse: 0.8239 - val_smape: 1.4897

Epoch 39/128

240/240 - 2s - 8ms/step - ia: 0.3220 - loss: 1.1363 - mae: 0.8069 - rmse: 1.0612 - smape: 1.3918 - val_ia: 0.2786 - val_loss: 0.8357 - val_mae: 0.6865 - val_rmse: 0.8232 - val_smape: 1.4844

Epoch 40/128

240/240 - 1s - 4ms/step - ia: 0.3260 - loss: 1.1301 - mae: 0.8010 - rmse: 1.0577 - smape: 1.3798 - val_ia: 0.2792 - val_loss: 0.8340 - val_mae: 0.6853 - val_rmse: 0.8222 - val_smape: 1.4776

Epoch 41/128

240/240 - 1s - 4ms/step - ia: 0.3195 - loss: 1.1335 - mae: 0.8073 - rmse: 1.0595 - smape: 1.3963 - val_ia: 0.2798 - val_loss: 0.8324 - val_mae: 0.6843 - val_rmse: 0.8213 - val_smape: 1.4715

Epoch 42/128

240/240 - 1s - 5ms/step - ia: 0.3276 - loss: 1.1170 - mae: 0.7988 - rmse: 1.0522 - smape: 1.3819 - val_ia: 0.2803 - val_loss: 0.8307 - val_mae: 0.6831 - val_rmse: 0.8204 - val_smape: 1.4649

Epoch 43/128

240/240 - 1s - 4ms/step - ia: 0.3289 - loss: 1.1116 - mae: 0.7957 - rmse: 1.0493 - smape: 1.3784 - val_ia: 0.2808 - val_loss: 0.8294 - val_mae: 0.6824 - val_rmse: 0.8198 - val_smape: 1.4599

Epoch 44/128

240/240 - 1s - 5ms/step - ia: 0.3238 - loss: 1.1152 - mae: 0.7989 - rmse: 1.0514 - smape: 1.3888 - val_ia: 0.2813 - val_loss: 0.8281 - val_mae: 0.6815 - val_rmse: 0.8190 - val_smape: 1.4545

Epoch 45/128

240/240 - 2s - 7ms/step - ia: 0.3278 - loss: 1.1091 - mae: 0.7945 - rmse: 1.0483 - smape: 1.3792 - val_ia: 0.2817 - val_loss: 0.8266 - val_mae: 0.6802 - val_rmse: 0.8179 - val_smape: 1.4479

Epoch 46/128

240/240 - 1s - 5ms/step - ia: 0.3301 - loss: 1.1010 - mae: 0.7918 - rmse: 1.0451 - smape: 1.3775 - val_ia: 0.2822 - val_loss: 0.8255 - val_mae: 0.6799 - val_rmse: 0.8176 - val_smape: 1.4446

Epoch 47/128

240/240 - 1s - 4ms/step - ia: 0.3276 - loss: 1.1014 - mae: 0.7910 - rmse: 1.0447 - smape: 1.3815 - val_ia: 0.2829 - val_loss: 0.8249 - val_mae: 0.6800 - val_rmse: 0.8178 - val_smape: 1.4429

Epoch 48/128

240/240 - 1s - 5ms/step - ia: 0.3269 - loss: 1.0952 - mae: 0.7919 - rmse: 1.0432 - smape: 1.3846 - val_ia: 0.2834 - val_loss: 0.8241 - val_mae: 0.6798 - val_rmse: 0.8176 - val_smape: 1.4403

Epoch 49/128

240/240 - 1s - 5ms/step - ia: 0.3328 - loss: 1.0857 - mae: 0.7858 - rmse: 1.0370 - smape: 1.3735 - val_ia: 0.2840 - val_loss: 0.8235 - val_mae: 0.6800 - val_rmse: 0.8178 - val_smape: 1.4391

Epoch 50/128

240/240 - 1s - 3ms/step - ia: 0.3311 - loss: 1.0859 - mae: 0.7860 - rmse: 1.0379 - smape: 1.3749 - val_ia: 0.2844 - val_loss: 0.8227 - val_mae: 0.6797 - val_rmse: 0.8176 - val_smape: 1.4364

Epoch 51/128

240/240 - 1s - 3ms/step - ia: 0.3337 - loss: 1.0761 - mae: 0.7825 - rmse: 1.0330 - smape: 1.3728 - val_ia: 0.2847 - val_loss: 0.8212 - val_mae: 0.6782 - val_rmse: 0.8163 - val_smape: 1.4297

Epoch 52/128

240/240 - 1s - 3ms/step - ia: 0.3285 - loss: 1.0839 - mae: 0.7858 - rmse: 1.0362 - smape: 1.3831 - val_ia: 0.2852 - val_loss: 0.8206 - val_mae: 0.6784 - val_rmse: 0.8165 - val_smape: 1.4287

Epoch 53/128

240/240 - 1s - 4ms/step - ia: 0.3319 - loss: 1.0773 - mae: 0.7839 - rmse: 1.0331 - smape: 1.3754 - val_ia: 0.2855 - val_loss: 0.8196 - val_mae: 0.6777 - val_rmse: 0.8159 - val_smape: 1.4248

Epoch 54/128

240/240 - 2s - 7ms/step - ia: 0.3316 - loss: 1.0720 - mae: 0.7814 - rmse: 1.0302 - smape: 1.3749 - val_ia: 0.2859 - val_loss: 0.8188 - val_mae: 0.6770 - val_rmse: 0.8153 - val_smape: 1.4210

Epoch 55/128

240/240 - 2s - 6ms/step - ia: 0.3370 - loss: 1.0559 - mae: 0.7746 - rmse: 1.0226 - smape: 1.3679 - val_ia: 0.2862 - val_loss: 0.8180 - val_mae: 0.6765 - val_rmse: 0.8150 - val_smape: 1.4183

Epoch 56/128

240/240 - 1s - 5ms/step - ia: 0.3311 - loss: 1.0617 - mae: 0.7799 - rmse: 1.0255 - smape: 1.3791 - val_ia: 0.2867 - val_loss: 0.8173 - val_mae: 0.6757 - val_rmse: 0.8144 - val_smape: 1.4144

Epoch 57/128

240/240 - 1s - 6ms/step - ia: 0.3358 - loss: 1.0649 - mae: 0.7758 - rmse: 1.0268 - smape: 1.3691 - val_ia: 0.2870 - val_loss: 0.8168 - val_mae: 0.6757 - val_rmse: 0.8144 - val_smape: 1.4131

Epoch 58/128

240/240 - 2s - 7ms/step - ia: 0.3348 - loss: 1.0508 - mae: 0.7724 - rmse: 1.0201 - smape: 1.3726 - val_ia: 0.2874 - val_loss: 0.8160 - val_mae: 0.6750 - val_rmse: 0.8139 - val_smape: 1.4096

Epoch 59/128

240/240 - 1s - 6ms/step - ia: 0.3339 - loss: 1.0501 - mae: 0.7726 - rmse: 1.0199 - smape: 1.3698 - val_ia: 0.2878 - val_loss: 0.8154 - val_mae: 0.6748 - val_rmse: 0.8137 - val_smape: 1.4075

Epoch 60/128

240/240 - 2s - 7ms/step - ia: 0.3366 - loss: 1.0387 - mae: 0.7693 - rmse: 1.0149 - smape: 1.3711 - val_ia: 0.2880 - val_loss: 0.8143 - val_mae: 0.6739 - val_rmse: 0.8129 - val_smape: 1.4033

Epoch 61/128

240/240 - 3s - 12ms/step - ia: 0.3362 - loss: 1.0472 - mae: 0.7712 - rmse: 1.0189 - smape: 1.3706 - val_ia: 0.2884 - val_loss: 0.8137 - val_mae: 0.6731 - val_rmse: 0.8123 - val_smape: 1.3998

Epoch 62/128

240/240 - 2s - 7ms/step - ia: 0.3363 - loss: 1.0462 - mae: 0.7694 - rmse: 1.0177 - smape: 1.3673 - val_ia: 0.2887 - val_loss: 0.8131 - val_mae: 0.6727 - val_rmse: 0.8120 - val_smape: 1.3975

Epoch 63/128

240/240 - 2s - 7ms/step - ia: 0.3381 - loss: 1.0339 - mae: 0.7656 - rmse: 1.0124 - smape: 1.3665 - val_ia: 0.2890 - val_loss: 0.8129 - val_mae: 0.6730 - val_rmse: 0.8123 - val_smape: 1.3975

Epoch 64/128

240/240 - 3s - 11ms/step - ia: 0.3376 - loss: 1.0343 - mae: 0.7664 - rmse: 1.0117 - smape: 1.3672 - val_ia: 0.2893 - val_loss: 0.8122 - val_mae: 0.6725 - val_rmse: 0.8118 - val_smape: 1.3949

Epoch 65/128

240/240 - 2s - 7ms/step - ia: 0.3386 - loss: 1.0334 - mae: 0.7651 - rmse: 1.0109 - smape: 1.3662 - val_ia: 0.2895 - val_loss: 0.8117 - val_mae: 0.6724 - val_rmse: 0.8118 - val_smape: 1.3940

Epoch 66/128

240/240 - 1s - 4ms/step - ia: 0.3384 - loss: 1.0307 - mae: 0.7635 - rmse: 1.0092 - smape: 1.3655 - val_ia: 0.2899 - val_loss: 0.8111 - val_mae: 0.6717 - val_rmse: 0.8112 - val_smape: 1.3907

Epoch 67/128

240/240 - 1s - 4ms/step - ia: 0.3361 - loss: 1.0329 - mae: 0.7649 - rmse: 1.0122 - smape: 1.3710 - val_ia: 0.2902 - val_loss: 0.8108 - val_mae: 0.6718 - val_rmse: 0.8113 - val_smape: 1.3903

Epoch 68/128

240/240 - 1s - 5ms/step - ia: 0.3383 - loss: 1.0276 - mae: 0.7615 - rmse: 1.0109 - smape: 1.3636 - val_ia: 0.2903 - val_loss: 0.8100 - val_mae: 0.6710 - val_rmse: 0.8107 - val_smape: 1.3870

Epoch 69/128

240/240 - 1s - 4ms/step - ia: 0.3411 - loss: 1.0178 - mae: 0.7586 - rmse: 1.0050 - smape: 1.3629 - val_ia: 0.2905 - val_loss: 0.8094 - val_mae: 0.6705 - val_rmse: 0.8102 - val_smape: 1.3846

Epoch 70/128

240/240 - 1s - 4ms/step - ia: 0.3419 - loss: 1.0097 - mae: 0.7564 - rmse: 1.0000 - smape: 1.3618 - val_ia: 0.2908 - val_loss: 0.8090 - val_mae: 0.6700 - val_rmse: 0.8098 - val_smape: 1.3824

Epoch 71/128

240/240 - 1s - 4ms/step - ia: 0.3399 - loss: 1.0221 - mae: 0.7598 - rmse: 1.0048 - smape: 1.3622 - val_ia: 0.2909 - val_loss: 0.8086 - val_mae: 0.6697 - val_rmse: 0.8096 - val_smape: 1.3811

Epoch 72/128

240/240 - 1s - 4ms/step - ia: 0.3434 - loss: 1.0080 - mae: 0.7551 - rmse: 0.9991 - smape: 1.3596 - val_ia: 0.2911 - val_loss: 0.8085 - val_mae: 0.6705 - val_rmse: 0.8102 - val_smape: 1.3829

Epoch 73/128

240/240 - 1s - 6ms/step - ia: 0.3391 - loss: 1.0117 - mae: 0.7550 - rmse: 1.0004 - smape: 1.3629 - val_ia: 0.2914 - val_loss: 0.8081 - val_mae: 0.6701 - val_rmse: 0.8099 - val_smape: 1.3809

Epoch 74/128

240/240 - 1s - 4ms/step - ia: 0.3420 - loss: 1.0028 - mae: 0.7531 - rmse: 0.9961 - smape: 1.3607 - val_ia: 0.2916 - val_loss: 0.8077 - val_mae: 0.6699 - val_rmse: 0.8097 - val_smape: 1.3795

Epoch 75/128

240/240 - 1s - 4ms/step - ia: 0.3399 - loss: 1.0046 - mae: 0.7552 - rmse: 0.9967 - smape: 1.3648 - val_ia: 0.2919 - val_loss: 0.8074 - val_mae: 0.6697 - val_rmse: 0.8096 - val_smape: 1.3785

Epoch 76/128

240/240 - 2s - 6ms/step - ia: 0.3402 - loss: 1.0064 - mae: 0.7533 - rmse: 0.9982 - smape: 1.3622 - val_ia: 0.2921 - val_loss: 0.8071 - val_mae: 0.6695 - val_rmse: 0.8095 - val_smape: 1.3774

Epoch 77/128

240/240 - 1s - 5ms/step - ia: 0.3426 - loss: 0.9965 - mae: 0.7505 - rmse: 0.9928 - smape: 1.3600 - val_ia: 0.2923 - val_loss: 0.8068 - val_mae: 0.6695 - val_rmse: 0.8095 - val_smape: 1.3768

Epoch 78/128

240/240 - 1s - 6ms/step - ia: 0.3435 - loss: 1.0003 - mae: 0.7505 - rmse: 0.9960 - smape: 1.3573 - val_ia: 0.2924 - val_loss: 0.8064 - val_mae: 0.6691 - val_rmse: 0.8091 - val_smape: 1.3750

Epoch 79/128

240/240 - 1s - 6ms/step - ia: 0.3356 - loss: 1.0075 - mae: 0.7562 - rmse: 0.9989 - smape: 1.3705 - val_ia: 0.2927 - val_loss: 0.8062 - val_mae: 0.6690 - val_rmse: 0.8091 - val_smape: 1.3744

Epoch 80/128

240/240 - 1s - 5ms/step - ia: 0.3405 - loss: 0.9966 - mae: 0.7488 - rmse: 0.9944 - smape: 1.3595 - val_ia: 0.2928 - val_loss: 0.8059 - val_mae: 0.6690 - val_rmse: 0.8090 - val_smape: 1.3737

Epoch 81/128

240/240 - 2s - 8ms/step - ia: 0.3380 - loss: 1.0011 - mae: 0.7526 - rmse: 0.9956 - smape: 1.3677 - val_ia: 0.2930 - val_loss: 0.8055 - val_mae: 0.6687 - val_rmse: 0.8088 - val_smape: 1.3724

Epoch 82/128

240/240 - 1s - 5ms/step - ia: 0.3387 - loss: 0.9972 - mae: 0.7505 - rmse: 0.9931 - smape: 1.3653 - val_ia: 0.2932 - val_loss: 0.8052 - val_mae: 0.6682 - val_rmse: 0.8084 - val_smape: 1.3707

Epoch 83/128

240/240 - 1s - 5ms/step - ia: 0.3415 - loss: 0.9880 - mae: 0.7459 - rmse: 0.9906 - smape: 1.3593 - val_ia: 0.2933 - val_loss: 0.8045 - val_mae: 0.6675 - val_rmse: 0.8078 - val_smape: 1.3680

Epoch 84/128

240/240 - 1s - 4ms/step - ia: 0.3440 - loss: 0.9812 - mae: 0.7425 - rmse: 0.9856 - smape: 1.3588 - val_ia: 0.2935 - val_loss: 0.8046 - val_mae: 0.6680 - val_rmse: 0.8083 - val_smape: 1.3691

Epoch 85/128

240/240 - 1s - 4ms/step - ia: 0.3418 - loss: 0.9848 - mae: 0.7450 - rmse: 0.9871 - smape: 1.3583 - val_ia: 0.2937 - val_loss: 0.8044 - val_mae: 0.6679 - val_rmse: 0.8081 - val_smape: 1.3682

Epoch 86/128

240/240 - 1s - 4ms/step - ia: 0.3370 - loss: 0.9922 - mae: 0.7481 - rmse: 0.9915 - smape: 1.3668 - val_ia: 0.2939 - val_loss: 0.8040 - val_mae: 0.6672 - val_rmse: 0.8077 - val_smape: 1.3660

Epoch 87/128

240/240 - 1s - 5ms/step - ia: 0.3437 - loss: 0.9804 - mae: 0.7424 - rmse: 0.9847 - smape: 1.3544 - val_ia: 0.2941 - val_loss: 0.8040 - val_mae: 0.6676 - val_rmse: 0.8080 - val_smape: 1.3668

Epoch 88/128

240/240 - 1s - 5ms/step - ia: 0.3387 - loss: 0.9841 - mae: 0.7451 - rmse: 0.9861 - smape: 1.3664 - val_ia: 0.2943 - val_loss: 0.8038 - val_mae: 0.6675 - val_rmse: 0.8079 - val_smape: 1.3660

Epoch 89/128

240/240 - 1s - 5ms/step - ia: 0.3414 - loss: 0.9816 - mae: 0.7433 - rmse: 0.9855 - smape: 1.3592 - val_ia: 0.2944 - val_loss: 0.8034 - val_mae: 0.6671 - val_rmse: 0.8076 - val_smape: 1.3646

Epoch 90/128

240/240 - 1s - 4ms/step - ia: 0.3419 - loss: 0.9765 - mae: 0.7405 - rmse: 0.9827 - smape: 1.3596 - val_ia: 0.2946 - val_loss: 0.8029 - val_mae: 0.6665 - val_rmse: 0.8070 - val_smape: 1.3623

Epoch 91/128

240/240 - 1s - 6ms/step - ia: 0.3429 - loss: 0.9709 - mae: 0.7385 - rmse: 0.9806 - smape: 1.3568 - val_ia: 0.2947 - val_loss: 0.8027 - val_mae: 0.6666 - val_rmse: 0.8071 - val_smape: 1.3622

Epoch 92/128

240/240 - 1s - 5ms/step - ia: 0.3440 - loss: 0.9746 - mae: 0.7371 - rmse: 0.9815 - smape: 1.3532 - val_ia: 0.2949 - val_loss: 0.8025 - val_mae: 0.6666 - val_rmse: 0.8071 - val_smape: 1.3618

Epoch 93/128

240/240 - 1s - 6ms/step - ia: 0.3432 - loss: 0.9757 - mae: 0.7390 - rmse: 0.9826 - smape: 1.3551 - val_ia: 0.2950 - val_loss: 0.8023 - val_mae: 0.6664 - val_rmse: 0.8069 - val_smape: 1.3610

Epoch 94/128

240/240 - 1s - 4ms/step - ia: 0.3408 - loss: 0.9752 - mae: 0.7398 - rmse: 0.9831 - smape: 1.3585 - val_ia: 0.2951 - val_loss: 0.8019 - val_mae: 0.6660 - val_rmse: 0.8066 - val_smape: 1.3596

Epoch 95/128

240/240 - 1s - 5ms/step - ia: 0.3440 - loss: 0.9729 - mae: 0.7384 - rmse: 0.9832 - smape: 1.3558 - val_ia: 0.2952 - val_loss: 0.8019 - val_mae: 0.6661 - val_rmse: 0.8067 - val_smape: 1.3598

Epoch 96/128

240/240 - 2s - 6ms/step - ia: 0.3405 - loss: 0.9718 - mae: 0.7380 - rmse: 0.9820 - smape: 1.3580 - val_ia: 0.2954 - val_loss: 0.8017 - val_mae: 0.6660 - val_rmse: 0.8066 - val_smape: 1.3593

Epoch 97/128

240/240 - 2s - 9ms/step - ia: 0.3424 - loss: 0.9593 - mae: 0.7349 - rmse: 0.9754 - smape: 1.3575 - val_ia: 0.2956 - val_loss: 0.8017 - val_mae: 0.6663 - val_rmse: 0.8069 - val_smape: 1.3596

Epoch 98/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 7s - 31ms/step - ia: 0.3703 - loss: 1.0563 - mae: 0.7429 - rmse: 0.9940 - smape: 1.3201 - val_ia: 0.3149 - val_loss: 0.7753 - val_mae: 0.6509 - val_rmse: 0.7926 - val_smape: 1.3241

Epoch 2/128

240/240 - 1s - 4ms/step - ia: 0.3694 - loss: 0.8350 - mae: 0.6748 - rmse: 0.9088 - smape: 1.3143 - val_ia: 0.3502 - val_loss: 0.7812 - val_mae: 0.6496 - val_rmse: 0.8063 - val_smape: 1.1888

Epoch 3/128

240/240 - 1s - 3ms/step - ia: 0.3760 - loss: 0.8363 - mae: 0.6740 - rmse: 0.9093 - smape: 1.3080 - val_ia: 0.3138 - val_loss: 0.7823 - val_mae: 0.6568 - val_rmse: 0.8011 - val_smape: 1.3116

Epoch 4/128

240/240 - 1s - 3ms/step - ia: 0.3742 - loss: 0.8374 - mae: 0.6758 - rmse: 0.9103 - smape: 1.3096 - val_ia: 0.3257 - val_loss: 0.7839 - val_mae: 0.6558 - val_rmse: 0.7996 - val_smape: 1.3305

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.3736 - loss: 0.8356 - mae: 0.6755 - rmse: 0.9090 - smape: 1.3087 - val_ia: 0.3163 - val_loss: 0.7750 - val_mae: 0.6575 - val_rmse: 0.7985 - val_smape: 1.3272

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.3723 - loss: 0.8433 - mae: 0.6763 - rmse: 0.9125 - smape: 1.3086 - val_ia: 0.3200 - val_loss: 0.7871 - val_mae: 0.6587 - val_rmse: 0.8037 - val_smape: 1.3283

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.3686 - loss: 0.8437 - mae: 0.6771 - rmse: 0.9131 - smape: 1.3160 - val_ia: 0.3546 - val_loss: 0.7949 - val_mae: 0.6498 - val_rmse: 0.8103 - val_smape: 1.2227

Epoch 8/128

240/240 - 1s - 5ms/step - ia: 0.3691 - loss: 0.8478 - mae: 0.6780 - rmse: 0.9153 - smape: 1.3162 - val_ia: 0.3274 - val_loss: 0.7918 - val_mae: 0.6595 - val_rmse: 0.8095 - val_smape: 1.2990

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.3720 - loss: 0.8406 - mae: 0.6771 - rmse: 0.9116 - smape: 1.3128 - val_ia: 0.3138 - val_loss: 0.7886 - val_mae: 0.6656 - val_rmse: 0.8063 - val_smape: 1.3643

Epoch 10/128

240/240 - 1s - 3ms/step - ia: 0.3747 - loss: 0.8440 - mae: 0.6778 - rmse: 0.9135 - smape: 1.3124 - val_ia: 0.3391 - val_loss: 0.7676 - val_mae: 0.6481 - val_rmse: 0.7973 - val_smape: 1.2554

Epoch 11/128

240/240 - 1s - 3ms/step - ia: 0.3720 - loss: 0.8477 - mae: 0.6789 - rmse: 0.9148 - smape: 1.3146 - val_ia: 0.3198 - val_loss: 0.7675 - val_mae: 0.6482 - val_rmse: 0.7910 - val_smape: 1.2982

Epoch 12/128

240/240 - 1s - 3ms/step - ia: 0.3694 - loss: 0.8504 - mae: 0.6804 - rmse: 0.9174 - smape: 1.3184 - val_ia: 0.2932 - val_loss: 0.8703 - val_mae: 0.7062 - val_rmse: 0.8466 - val_smape: 1.5337

Epoch 13/128

240/240 - 1s - 6ms/step - ia: 0.3708 - loss: 0.8457 - mae: 0.6795 - rmse: 0.9143 - smape: 1.3198 - val_ia: 0.3471 - val_loss: 0.7634 - val_mae: 0.6414 - val_rmse: 0.7919 - val_smape: 1.2268

Epoch 14/128

240/240 - 1s - 4ms/step - ia: 0.3695 - loss: 0.8509 - mae: 0.6808 - rmse: 0.9166 - smape: 1.3162 - val_ia: 0.3157 - val_loss: 0.7508 - val_mae: 0.6397 - val_rmse: 0.7793 - val_smape: 1.2530

Epoch 15/128

240/240 - 1s - 3ms/step - ia: 0.3682 - loss: 0.8533 - mae: 0.6806 - rmse: 0.9180 - smape: 1.3172 - val_ia: 0.3353 - val_loss: 0.7553 - val_mae: 0.6340 - val_rmse: 0.7836 - val_smape: 1.1925

Epoch 16/128

240/240 - 1s - 4ms/step - ia: 0.3708 - loss: 0.8550 - mae: 0.6820 - rmse: 0.9200 - smape: 1.3139 - val_ia: 0.3146 - val_loss: 0.7650 - val_mae: 0.6438 - val_rmse: 0.7862 - val_smape: 1.2444

Epoch 17/128

240/240 - 1s - 6ms/step - ia: 0.3711 - loss: 0.8501 - mae: 0.6804 - rmse: 0.9154 - smape: 1.3156 - val_ia: 0.3331 - val_loss: 0.8257 - val_mae: 0.6750 - val_rmse: 0.8298 - val_smape: 1.3051

Epoch 18/128

240/240 - 1s - 4ms/step - ia: 0.3644 - loss: 0.8595 - mae: 0.6862 - rmse: 0.9218 - smape: 1.3256 - val_ia: 0.2921 - val_loss: 0.8595 - val_mae: 0.6965 - val_rmse: 0.8360 - val_smape: 1.5224

Epoch 19/128

240/240 - 2s - 6ms/step - ia: 0.3700 - loss: 0.8535 - mae: 0.6811 - rmse: 0.9181 - smape: 1.3185 - val_ia: 0.3282 - val_loss: 0.7591 - val_mae: 0.6403 - val_rmse: 0.7863 - val_smape: 1.2506

Epoch 20/128

240/240 - 1s - 5ms/step - ia: 0.3713 - loss: 0.8516 - mae: 0.6825 - rmse: 0.9186 - smape: 1.3178 - val_ia: 0.3374 - val_loss: 0.7982 - val_mae: 0.6523 - val_rmse: 0.8094 - val_smape: 1.2436

Epoch 21/128

240/240 - 1s - 5ms/step - ia: 0.3672 - loss: 0.8579 - mae: 0.6833 - rmse: 0.9212 - smape: 1.3214 - val_ia: 0.2899 - val_loss: 0.8484 - val_mae: 0.6876 - val_rmse: 0.8272 - val_smape: 1.5024

Epoch 22/128

240/240 - 1s - 5ms/step - ia: 0.3663 - loss: 0.8566 - mae: 0.6840 - rmse: 0.9190 - smape: 1.3272 - val_ia: 0.3069 - val_loss: 0.7547 - val_mae: 0.6423 - val_rmse: 0.7799 - val_smape: 1.2991

Epoch 23/128

240/240 - 1s - 6ms/step - ia: 0.3729 - loss: 0.8516 - mae: 0.6808 - rmse: 0.9178 - smape: 1.3140 - val_ia: 0.3359 - val_loss: 0.7880 - val_mae: 0.6665 - val_rmse: 0.8121 - val_smape: 1.3213

Epoch 24/128

240/240 - 2s - 10ms/step - ia: 0.3712 - loss: 0.8539 - mae: 0.6827 - rmse: 0.9190 - smape: 1.3167 - val_ia: 0.3633 - val_loss: 0.8139 - val_mae: 0.6541 - val_rmse: 0.8208 - val_smape: 1.1867

Epoch 25/128

240/240 - 1s - 5ms/step - ia: 0.3638 - loss: 0.8622 - mae: 0.6856 - rmse: 0.9220 - smape: 1.3269 - val_ia: 0.3046 - val_loss: 0.8287 - val_mae: 0.6930 - val_rmse: 0.8339 - val_smape: 1.4438

Epoch 26/128

240/240 - 1s - 4ms/step - ia: 0.3637 - loss: 0.8583 - mae: 0.6857 - rmse: 0.9209 - smape: 1.3296 - val_ia: 0.3267 - val_loss: 0.8117 - val_mae: 0.6641 - val_rmse: 0.8158 - val_smape: 1.2973

Epoch 27/128

240/240 - 1s - 3ms/step - ia: 0.3687 - loss: 0.8538 - mae: 0.6827 - rmse: 0.9183 - smape: 1.3214 - val_ia: 0.3098 - val_loss: 0.7916 - val_mae: 0.6687 - val_rmse: 0.8104 - val_smape: 1.3602

Epoch 28/128

240/240 - 1s - 4ms/step - ia: 0.3706 - loss: 0.8507 - mae: 0.6816 - rmse: 0.9171 - smape: 1.3189 - val_ia: 0.3042 - val_loss: 0.7678 - val_mae: 0.6603 - val_rmse: 0.7940 - val_smape: 1.3196

Epoch 29/128

240/240 - 1s - 6ms/step - ia: 0.3695 - loss: 0.8534 - mae: 0.6825 - rmse: 0.9192 - smape: 1.3176 - val_ia: 0.2896 - val_loss: 0.7914 - val_mae: 0.6598 - val_rmse: 0.7971 - val_smape: 1.3848

Epoch 29: early stopping

Restoring model weights from the end of the best epoch: 14.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 24s 178ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 46/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 65/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 82/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
104/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
125/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
130/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 58%|█████▊    | 7/12 [50:50<25:31, 306.30s/trial, best loss: 0.7718968131959658]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 22s - 6ms/step - ia: 0.3750 - loss: 0.8611 - mae: 0.6838 - rmse: 0.8687 - smape: 1.2868 - val_ia: 0.1999 - val_loss: 0.7871 - val_mae: 0.6594 - val_rmse: 0.7010 - val_smape: 1.2912

Epoch 2/128

3830/3830 - 13s - 3ms/step - ia: 0.3907 - loss: 0.8274 - mae: 0.6660 - rmse: 0.8508 - smape: 1.2600 - val_ia: 0.2108 - val_loss: 0.8128 - val_mae: 0.6531 - val_rmse: 0.7013 - val_smape: 1.1520

Epoch 3/128

3830/3830 - 11s - 3ms/step - ia: 0.3998 - loss: 0.8139 - mae: 0.6604 - rmse: 0.8442 - smape: 1.2490 - val_ia: 0.2099 - val_loss: 0.7978 - val_mae: 0.6383 - val_rmse: 0.6861 - val_smape: 1.1485

Epoch 4/128

3830/3830 - 19s - 5ms/step - ia: 0.4014 - loss: 0.8024 - mae: 0.6568 - rmse: 0.8381 - smape: 1.2482 - val_ia: 0.2049 - val_loss: 0.7786 - val_mae: 0.6535 - val_rmse: 0.6966 - val_smape: 1.3227

Epoch 5/128

3830/3830 - 11s - 3ms/step - ia: 0.4095 - loss: 0.7938 - mae: 0.6501 - rmse: 0.8338 - smape: 1.2302 - val_ia: 0.2023 - val_loss: 0.8063 - val_mae: 0.6675 - val_rmse: 0.7130 - val_smape: 1.2490

Epoch 6/128

3830/3830 - 19s - 5ms/step - ia: 0.4095 - loss: 0.7906 - mae: 0.6495 - rmse: 0.8332 - smape: 1.2312 - val_ia: 0.2013 - val_loss: 0.7861 - val_mae: 0.6668 - val_rmse: 0.7091 - val_smape: 1.3193

Epoch 7/128

3830/3830 - 11s - 3ms/step - ia: 0.4171 - loss: 0.7840 - mae: 0.6454 - rmse: 0.8275 - smape: 1.2216 - val_ia: 0.2099 - val_loss: 0.7814 - val_mae: 0.6301 - val_rmse: 0.6767 - val_smape: 1.1852

Epoch 8/128

3830/3830 - 11s - 3ms/step - ia: 0.4121 - loss: 0.7853 - mae: 0.6485 - rmse: 0.8292 - smape: 1.2348 - val_ia: 0.2069 - val_loss: 0.7552 - val_mae: 0.6317 - val_rmse: 0.6775 - val_smape: 1.2287

Epoch 9/128

3830/3830 - 11s - 3ms/step - ia: 0.4157 - loss: 0.7784 - mae: 0.6452 - rmse: 0.8262 - smape: 1.2246 - val_ia: 0.2096 - val_loss: 0.7776 - val_mae: 0.6325 - val_rmse: 0.6797 - val_smape: 1.2066

Epoch 10/128

3830/3830 - 12s - 3ms/step - ia: 0.4206 - loss: 0.7726 - mae: 0.6410 - rmse: 0.8215 - smape: 1.2174 - val_ia: 0.2014 - val_loss: 0.7974 - val_mae: 0.6669 - val_rmse: 0.7143 - val_smape: 1.2837

Epoch 11/128

3830/3830 - 21s - 5ms/step - ia: 0.4185 - loss: 0.7713 - mae: 0.6424 - rmse: 0.8225 - smape: 1.2129 - val_ia: 0.2025 - val_loss: 0.7564 - val_mae: 0.6416 - val_rmse: 0.6864 - val_smape: 1.2749

Epoch 12/128

3830/3830 - 12s - 3ms/step - ia: 0.4206 - loss: 0.7719 - mae: 0.6423 - rmse: 0.8223 - smape: 1.2172 - val_ia: 0.1999 - val_loss: 0.7795 - val_mae: 0.6550 - val_rmse: 0.6985 - val_smape: 1.2855

Epoch 13/128

3830/3830 - 12s - 3ms/step - ia: 0.4202 - loss: 0.7726 - mae: 0.6427 - rmse: 0.8221 - smape: 1.2201 - val_ia: 0.1986 - val_loss: 0.7903 - val_mae: 0.6598 - val_rmse: 0.7049 - val_smape: 1.2729

Epoch 14/128

3830/3830 - 11s - 3ms/step - ia: 0.4247 - loss: 0.7659 - mae: 0.6389 - rmse: 0.8180 - smape: 1.2136 - val_ia: 0.2016 - val_loss: 0.7826 - val_mae: 0.6457 - val_rmse: 0.6907 - val_smape: 1.3015

Epoch 15/128

3830/3830 - 11s - 3ms/step - ia: 0.4220 - loss: 0.7689 - mae: 0.6402 - rmse: 0.8207 - smape: 1.2091 - val_ia: 0.2046 - val_loss: 0.8130 - val_mae: 0.6569 - val_rmse: 0.7071 - val_smape: 1.2392

Epoch 16/128

3830/3830 - 10s - 3ms/step - ia: 0.4228 - loss: 0.7627 - mae: 0.6386 - rmse: 0.8169 - smape: 1.2112 - val_ia: 0.1980 - val_loss: 0.8289 - val_mae: 0.6736 - val_rmse: 0.7230 - val_smape: 1.2745

Epoch 17/128

3830/3830 - 10s - 3ms/step - ia: 0.4224 - loss: 0.7637 - mae: 0.6403 - rmse: 0.8196 - smape: 1.2174 - val_ia: 0.2052 - val_loss: 0.7808 - val_mae: 0.6382 - val_rmse: 0.6878 - val_smape: 1.2257

Epoch 18/128

3830/3830 - 12s - 3ms/step - ia: 0.4254 - loss: 0.7601 - mae: 0.6388 - rmse: 0.8167 - smape: 1.2128 - val_ia: 0.2043 - val_loss: 0.7859 - val_mae: 0.6444 - val_rmse: 0.6937 - val_smape: 1.2209

Epoch 19/128

3830/3830 - 10s - 3ms/step - ia: 0.4213 - loss: 0.7641 - mae: 0.6398 - rmse: 0.8192 - smape: 1.2122 - val_ia: 0.2016 - val_loss: 0.8002 - val_mae: 0.6529 - val_rmse: 0.7027 - val_smape: 1.2290

Epoch 20/128

3830/3830 - 9s - 2ms/step - ia: 0.4199 - loss: 0.7646 - mae: 0.6404 - rmse: 0.8190 - smape: 1.2183 - val_ia: 0.2051 - val_loss: 0.7814 - val_mae: 0.6460 - val_rmse: 0.6941 - val_smape: 1.2791

Epoch 21/128

3830/3830 - 10s - 3ms/step - ia: 0.4247 - loss: 0.7598 - mae: 0.6383 - rmse: 0.8171 - smape: 1.2134 - val_ia: 0.2066 - val_loss: 0.7629 - val_mae: 0.6317 - val_rmse: 0.6801 - val_smape: 1.2044

Epoch 22/128

3830/3830 - 11s - 3ms/step - ia: 0.4245 - loss: 0.7583 - mae: 0.6376 - rmse: 0.8155 - smape: 1.2120 - val_ia: 0.2035 - val_loss: 0.7977 - val_mae: 0.6458 - val_rmse: 0.6953 - val_smape: 1.2179

Epoch 23/128

3830/3830 - 10s - 3ms/step - ia: 0.4279 - loss: 0.7526 - mae: 0.6349 - rmse: 0.8124 - smape: 1.2057 - val_ia: 0.1995 - val_loss: 0.8013 - val_mae: 0.6605 - val_rmse: 0.7081 - val_smape: 1.2608

Epoch 23: early stopping

Restoring model weights from the end of the best epoch: 8.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 1:04 481ms/step
 16/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 38/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 64/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 86/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
110/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 67%|██████▋   | 8/12 [55:41<20:05, 301.29s/trial, best loss: 0.7718968131959658]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 13s - 54ms/step - ia: 0.3541 - loss: 1.3298 - mae: 0.8590 - rmse: 1.1319 - smape: 1.3503 - val_ia: 0.3240 - val_loss: 0.8227 - val_mae: 0.6709 - val_rmse: 0.8258 - val_smape: 1.2880

Epoch 2/128

240/240 - 1s - 3ms/step - ia: 0.3719 - loss: 0.9347 - mae: 0.7204 - rmse: 0.9620 - smape: 1.3199 - val_ia: 0.3249 - val_loss: 0.7842 - val_mae: 0.6559 - val_rmse: 0.8031 - val_smape: 1.2910

Epoch 3/128

240/240 - 1s - 3ms/step - ia: 0.3699 - loss: 0.8834 - mae: 0.6976 - rmse: 0.9346 - smape: 1.3233 - val_ia: 0.3214 - val_loss: 0.7830 - val_mae: 0.6535 - val_rmse: 0.7998 - val_smape: 1.2943

Epoch 4/128

240/240 - 1s - 3ms/step - ia: 0.3705 - loss: 0.8584 - mae: 0.6859 - rmse: 0.9215 - smape: 1.3171 - val_ia: 0.3250 - val_loss: 0.7645 - val_mae: 0.6451 - val_rmse: 0.7899 - val_smape: 1.2610

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.3722 - loss: 0.8459 - mae: 0.6800 - rmse: 0.9147 - smape: 1.3166 - val_ia: 0.3205 - val_loss: 0.7746 - val_mae: 0.6496 - val_rmse: 0.7944 - val_smape: 1.2942

Epoch 6/128

240/240 - 1s - 3ms/step - ia: 0.3684 - loss: 0.8403 - mae: 0.6770 - rmse: 0.9114 - smape: 1.3208 - val_ia: 0.3269 - val_loss: 0.7648 - val_mae: 0.6427 - val_rmse: 0.7888 - val_smape: 1.2606

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.3705 - loss: 0.8344 - mae: 0.6737 - rmse: 0.9085 - smape: 1.3172 - val_ia: 0.3234 - val_loss: 0.7586 - val_mae: 0.6403 - val_rmse: 0.7841 - val_smape: 1.2635

Epoch 8/128

240/240 - 1s - 2ms/step - ia: 0.3710 - loss: 0.8322 - mae: 0.6720 - rmse: 0.9070 - smape: 1.3141 - val_ia: 0.3261 - val_loss: 0.7634 - val_mae: 0.6446 - val_rmse: 0.7891 - val_smape: 1.2762

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.3734 - loss: 0.8272 - mae: 0.6702 - rmse: 0.9035 - smape: 1.3096 - val_ia: 0.3144 - val_loss: 0.7660 - val_mae: 0.6455 - val_rmse: 0.7883 - val_smape: 1.2818

Epoch 10/128

240/240 - 1s - 3ms/step - ia: 0.3691 - loss: 0.8277 - mae: 0.6718 - rmse: 0.9049 - smape: 1.3195 - val_ia: 0.3286 - val_loss: 0.7670 - val_mae: 0.6429 - val_rmse: 0.7898 - val_smape: 1.2611

Epoch 11/128

240/240 - 1s - 2ms/step - ia: 0.3708 - loss: 0.8266 - mae: 0.6703 - rmse: 0.9048 - smape: 1.3152 - val_ia: 0.3225 - val_loss: 0.7545 - val_mae: 0.6402 - val_rmse: 0.7825 - val_smape: 1.2659

Epoch 12/128

240/240 - 1s - 3ms/step - ia: 0.3721 - loss: 0.8259 - mae: 0.6699 - rmse: 0.9036 - smape: 1.3140 - val_ia: 0.3226 - val_loss: 0.7706 - val_mae: 0.6491 - val_rmse: 0.7927 - val_smape: 1.3046

Epoch 13/128

240/240 - 1s - 3ms/step - ia: 0.3734 - loss: 0.8235 - mae: 0.6686 - rmse: 0.9028 - smape: 1.3112 - val_ia: 0.3240 - val_loss: 0.7562 - val_mae: 0.6395 - val_rmse: 0.7833 - val_smape: 1.2547

Epoch 14/128

240/240 - 1s - 6ms/step - ia: 0.3754 - loss: 0.8226 - mae: 0.6680 - rmse: 0.9014 - smape: 1.3080 - val_ia: 0.3186 - val_loss: 0.7636 - val_mae: 0.6452 - val_rmse: 0.7880 - val_smape: 1.2875

Epoch 15/128

240/240 - 1s - 4ms/step - ia: 0.3724 - loss: 0.8225 - mae: 0.6691 - rmse: 0.9019 - smape: 1.3126 - val_ia: 0.3150 - val_loss: 0.7649 - val_mae: 0.6470 - val_rmse: 0.7880 - val_smape: 1.3068

Epoch 16/128

240/240 - 1s - 3ms/step - ia: 0.3705 - loss: 0.8247 - mae: 0.6685 - rmse: 0.9028 - smape: 1.3146 - val_ia: 0.3230 - val_loss: 0.7576 - val_mae: 0.6414 - val_rmse: 0.7849 - val_smape: 1.2588

Epoch 17/128

240/240 - 1s - 4ms/step - ia: 0.3713 - loss: 0.8230 - mae: 0.6682 - rmse: 0.9006 - smape: 1.3144 - val_ia: 0.3191 - val_loss: 0.7585 - val_mae: 0.6435 - val_rmse: 0.7852 - val_smape: 1.2852

Epoch 18/128

240/240 - 1s - 5ms/step - ia: 0.3714 - loss: 0.8243 - mae: 0.6686 - rmse: 0.9023 - smape: 1.3122 - val_ia: 0.3211 - val_loss: 0.7584 - val_mae: 0.6425 - val_rmse: 0.7846 - val_smape: 1.2844

Epoch 19/128

240/240 - 1s - 4ms/step - ia: 0.3721 - loss: 0.8230 - mae: 0.6679 - rmse: 0.9017 - smape: 1.3095 - val_ia: 0.3248 - val_loss: 0.7584 - val_mae: 0.6427 - val_rmse: 0.7852 - val_smape: 1.2858

Epoch 20/128

240/240 - 1s - 3ms/step - ia: 0.3743 - loss: 0.8224 - mae: 0.6677 - rmse: 0.9015 - smape: 1.3086 - val_ia: 0.3221 - val_loss: 0.7620 - val_mae: 0.6452 - val_rmse: 0.7878 - val_smape: 1.2962

Epoch 21/128

240/240 - 1s - 3ms/step - ia: 0.3744 - loss: 0.8220 - mae: 0.6672 - rmse: 0.9010 - smape: 1.3069 - val_ia: 0.3104 - val_loss: 0.7628 - val_mae: 0.6465 - val_rmse: 0.7854 - val_smape: 1.3170

Epoch 22/128

240/240 - 1s - 4ms/step - ia: 0.3738 - loss: 0.8209 - mae: 0.6668 - rmse: 0.9009 - smape: 1.3087 - val_ia: 0.3228 - val_loss: 0.7603 - val_mae: 0.6441 - val_rmse: 0.7877 - val_smape: 1.2807

Epoch 23/128

240/240 - 1s - 3ms/step - ia: 0.3727 - loss: 0.8195 - mae: 0.6670 - rmse: 0.9009 - smape: 1.3112 - val_ia: 0.3309 - val_loss: 0.7571 - val_mae: 0.6384 - val_rmse: 0.7844 - val_smape: 1.2507

Epoch 24/128

240/240 - 1s - 4ms/step - ia: 0.3750 - loss: 0.8224 - mae: 0.6675 - rmse: 0.9013 - smape: 1.3058 - val_ia: 0.3217 - val_loss: 0.7570 - val_mae: 0.6401 - val_rmse: 0.7833 - val_smape: 1.2696

Epoch 25/128

240/240 - 1s - 4ms/step - ia: 0.3727 - loss: 0.8221 - mae: 0.6677 - rmse: 0.9014 - smape: 1.3095 - val_ia: 0.3175 - val_loss: 0.7655 - val_mae: 0.6460 - val_rmse: 0.7883 - val_smape: 1.3000

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.3719 - loss: 0.8251 - mae: 0.6684 - rmse: 0.9024 - smape: 1.3119 - val_ia: 0.3186 - val_loss: 0.7571 - val_mae: 0.6419 - val_rmse: 0.7836 - val_smape: 1.2816

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 11s 83ms/step
 10/136 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
 37/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 66/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
101/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 75%|███████▌  | 9/12 [56:15<10:53, 217.89s/trial, best loss: 0.7718968131959658]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

1915/1915 - 13s - 7ms/step - ia: 0.3338 - loss: 1.1604 - mae: 0.8170 - rmse: 1.0440 - smape: 1.3763 - val_ia: 0.2378 - val_loss: 0.7976 - val_mae: 0.6624 - val_rmse: 0.7257 - val_smape: 1.3492

Epoch 2/128

1915/1915 - 9s - 5ms/step - ia: 0.3546 - loss: 0.9526 - mae: 0.7302 - rmse: 0.9449 - smape: 1.3427 - val_ia: 0.2408 - val_loss: 0.7833 - val_mae: 0.6585 - val_rmse: 0.7234 - val_smape: 1.3211

Epoch 3/128

1915/1915 - 10s - 5ms/step - ia: 0.3620 - loss: 0.8900 - mae: 0.7019 - rmse: 0.9123 - smape: 1.3284 - val_ia: 0.2441 - val_loss: 0.7703 - val_mae: 0.6490 - val_rmse: 0.7138 - val_smape: 1.3015

Epoch 4/128

1915/1915 - 11s - 6ms/step - ia: 0.3676 - loss: 0.8619 - mae: 0.6878 - rmse: 0.8958 - smape: 1.3162 - val_ia: 0.2442 - val_loss: 0.7657 - val_mae: 0.6494 - val_rmse: 0.7139 - val_smape: 1.3101

Epoch 5/128

1915/1915 - 10s - 5ms/step - ia: 0.3697 - loss: 0.8440 - mae: 0.6798 - rmse: 0.8869 - smape: 1.3146 - val_ia: 0.2431 - val_loss: 0.7634 - val_mae: 0.6531 - val_rmse: 0.7190 - val_smape: 1.3134

Epoch 6/128

1915/1915 - 5s - 3ms/step - ia: 0.3744 - loss: 0.8327 - mae: 0.6744 - rmse: 0.8807 - smape: 1.3061 - val_ia: 0.2479 - val_loss: 0.7529 - val_mae: 0.6422 - val_rmse: 0.7091 - val_smape: 1.2752

Epoch 7/128

1915/1915 - 5s - 2ms/step - ia: 0.3784 - loss: 0.8276 - mae: 0.6708 - rmse: 0.8783 - smape: 1.2987 - val_ia: 0.2441 - val_loss: 0.7567 - val_mae: 0.6527 - val_rmse: 0.7185 - val_smape: 1.3168

Epoch 8/128

1915/1915 - 5s - 3ms/step - ia: 0.3793 - loss: 0.8248 - mae: 0.6701 - rmse: 0.8751 - smape: 1.2992 - val_ia: 0.2484 - val_loss: 0.7473 - val_mae: 0.6398 - val_rmse: 0.7060 - val_smape: 1.2795

Epoch 9/128

1915/1915 - 6s - 3ms/step - ia: 0.3821 - loss: 0.8190 - mae: 0.6678 - rmse: 0.8739 - smape: 1.2988 - val_ia: 0.2484 - val_loss: 0.7468 - val_mae: 0.6404 - val_rmse: 0.7064 - val_smape: 1.2858

Epoch 10/128

1915/1915 - 10s - 5ms/step - ia: 0.3852 - loss: 0.8134 - mae: 0.6654 - rmse: 0.8717 - smape: 1.2930 - val_ia: 0.2500 - val_loss: 0.7448 - val_mae: 0.6363 - val_rmse: 0.7032 - val_smape: 1.2697

Epoch 11/128

1915/1915 - 10s - 5ms/step - ia: 0.3862 - loss: 0.8125 - mae: 0.6641 - rmse: 0.8696 - smape: 1.2900 - val_ia: 0.2491 - val_loss: 0.7447 - val_mae: 0.6397 - val_rmse: 0.7063 - val_smape: 1.2853

Epoch 12/128

1915/1915 - 5s - 2ms/step - ia: 0.3856 - loss: 0.8090 - mae: 0.6629 - rmse: 0.8674 - smape: 1.2935 - val_ia: 0.2508 - val_loss: 0.7459 - val_mae: 0.6381 - val_rmse: 0.7065 - val_smape: 1.2682

Epoch 13/128

1915/1915 - 6s - 3ms/step - ia: 0.3917 - loss: 0.8074 - mae: 0.6612 - rmse: 0.8661 - smape: 1.2868 - val_ia: 0.2495 - val_loss: 0.7442 - val_mae: 0.6399 - val_rmse: 0.7069 - val_smape: 1.2867

Epoch 14/128

1915/1915 - 10s - 5ms/step - ia: 0.3907 - loss: 0.8044 - mae: 0.6598 - rmse: 0.8645 - smape: 1.2885 - val_ia: 0.2505 - val_loss: 0.7448 - val_mae: 0.6385 - val_rmse: 0.7065 - val_smape: 1.2736

Epoch 15/128

1915/1915 - 5s - 3ms/step - ia: 0.3933 - loss: 0.8035 - mae: 0.6596 - rmse: 0.8659 - smape: 1.2846 - val_ia: 0.2519 - val_loss: 0.7391 - val_mae: 0.6330 - val_rmse: 0.7003 - val_smape: 1.2686

Epoch 16/128

1915/1915 - 5s - 3ms/step - ia: 0.3937 - loss: 0.8005 - mae: 0.6585 - rmse: 0.8628 - smape: 1.2867 - val_ia: 0.2492 - val_loss: 0.7450 - val_mae: 0.6393 - val_rmse: 0.7066 - val_smape: 1.2894

Epoch 17/128

1915/1915 - 6s - 3ms/step - ia: 0.3969 - loss: 0.7977 - mae: 0.6567 - rmse: 0.8619 - smape: 1.2810 - val_ia: 0.2481 - val_loss: 0.7451 - val_mae: 0.6410 - val_rmse: 0.7072 - val_smape: 1.3056

Epoch 18/128

1915/1915 - 10s - 5ms/step - ia: 0.3934 - loss: 0.7973 - mae: 0.6572 - rmse: 0.8603 - smape: 1.2884 - val_ia: 0.2501 - val_loss: 0.7459 - val_mae: 0.6384 - val_rmse: 0.7066 - val_smape: 1.2784

Epoch 19/128

1915/1915 - 6s - 3ms/step - ia: 0.3967 - loss: 0.7975 - mae: 0.6568 - rmse: 0.8604 - smape: 1.2841 - val_ia: 0.2510 - val_loss: 0.7448 - val_mae: 0.6373 - val_rmse: 0.7058 - val_smape: 1.2745

Epoch 20/128

1915/1915 - 10s - 5ms/step - ia: 0.3984 - loss: 0.7951 - mae: 0.6560 - rmse: 0.8589 - smape: 1.2822 - val_ia: 0.2504 - val_loss: 0.7453 - val_mae: 0.6386 - val_rmse: 0.7068 - val_smape: 1.2825

Epoch 21/128

1915/1915 - 10s - 5ms/step - ia: 0.3974 - loss: 0.7940 - mae: 0.6548 - rmse: 0.8605 - smape: 1.2848 - val_ia: 0.2495 - val_loss: 0.7471 - val_mae: 0.6389 - val_rmse: 0.7070 - val_smape: 1.2863

Epoch 22/128

1915/1915 - 12s - 6ms/step - ia: 0.4004 - loss: 0.7935 - mae: 0.6547 - rmse: 0.8586 - smape: 1.2793 - val_ia: 0.2510 - val_loss: 0.7425 - val_mae: 0.6346 - val_rmse: 0.7023 - val_smape: 1.2793

Epoch 23/128

1915/1915 - 10s - 5ms/step - ia: 0.3984 - loss: 0.7950 - mae: 0.6546 - rmse: 0.8600 - smape: 1.2825 - val_ia: 0.2516 - val_loss: 0.7453 - val_mae: 0.6353 - val_rmse: 0.7046 - val_smape: 1.2688

Epoch 24/128

1915/1915 - 10s - 5ms/step - ia: 0.4009 - loss: 0.7912 - mae: 0.6541 - rmse: 0.8586 - smape: 1.2810 - val_ia: 0.2506 - val_loss: 0.7460 - val_mae: 0.6381 - val_rmse: 0.7068 - val_smape: 1.2809

Epoch 25/128

1915/1915 - 6s - 3ms/step - ia: 0.4020 - loss: 0.7896 - mae: 0.6527 - rmse: 0.8564 - smape: 1.2752 - val_ia: 0.2505 - val_loss: 0.7429 - val_mae: 0.6354 - val_rmse: 0.7035 - val_smape: 1.2855

Epoch 26/128

1915/1915 - 11s - 6ms/step - ia: 0.3984 - loss: 0.7913 - mae: 0.6538 - rmse: 0.8575 - smape: 1.2817 - val_ia: 0.2525 - val_loss: 0.7460 - val_mae: 0.6332 - val_rmse: 0.7031 - val_smape: 1.2641

Epoch 27/128

1915/1915 - 6s - 3ms/step - ia: 0.4039 - loss: 0.7863 - mae: 0.6516 - rmse: 0.8544 - smape: 1.2786 - val_ia: 0.2494 - val_loss: 0.7450 - val_mae: 0.6377 - val_rmse: 0.7056 - val_smape: 1.2949

Epoch 28/128

1915/1915 - 6s - 3ms/step - ia: 0.4030 - loss: 0.7852 - mae: 0.6505 - rmse: 0.8548 - smape: 1.2770 - val_ia: 0.2507 - val_loss: 0.7469 - val_mae: 0.6365 - val_rmse: 0.7057 - val_smape: 1.2786

Epoch 29/128

1915/1915 - 9s - 5ms/step - ia: 0.4019 - loss: 0.7881 - mae: 0.6522 - rmse: 0.8563 - smape: 1.2799 - val_ia: 0.2500 - val_loss: 0.7446 - val_mae: 0.6362 - val_rmse: 0.7046 - val_smape: 1.2885

Epoch 30/128

1915/1915 - 6s - 3ms/step - ia: 0.4035 - loss: 0.7858 - mae: 0.6508 - rmse: 0.8540 - smape: 1.2778 - val_ia: 0.2513 - val_loss: 0.7456 - val_mae: 0.6342 - val_rmse: 0.7037 - val_smape: 1.2738

Epoch 30: early stopping

Restoring model weights from the end of the best epoch: 15.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 33s 251ms/step
 11/136 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
 28/136 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
 50/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 71/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
124/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

 83%|████████▎ | 10/12 [1:00:19<07:31, 225.91s/trial, best loss: 0.7718968131959658]

c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

3830/3830 - 16s - 4ms/step - ia: 0.2458 - loss: 1.9123 - mae: 1.0295 - rmse: 1.2964 - smape: 1.6086 - val_ia: 0.1666 - val_loss: 1.2150 - val_mae: 0.8835 - val_rmse: 0.9259 - val_smape: 1.7227

Epoch 2/128

3830/3830 - 8s - 2ms/step - ia: 0.2500 - loss: 1.8187 - mae: 1.0073 - rmse: 1.2663 - smape: 1.6074 - val_ia: 0.1680 - val_loss: 1.1826 - val_mae: 0.8670 - val_rmse: 0.9091 - val_smape: 1.7288

Epoch 3/128

3830/3830 - 10s - 3ms/step - ia: 0.2487 - loss: 1.6930 - mae: 0.9819 - rmse: 1.2293 - smape: 1.6083 - val_ia: 0.1693 - val_loss: 1.1546 - val_mae: 0.8526 - val_rmse: 0.8944 - val_smape: 1.7350

Epoch 4/128

3830/3830 - 11s - 3ms/step - ia: 0.2478 - loss: 1.6485 - mae: 0.9668 - rmse: 1.2093 - smape: 1.6066 - val_ia: 0.1706 - val_loss: 1.1300 - val_mae: 0.8397 - val_rmse: 0.8812 - val_smape: 1.7398

Epoch 5/128

3830/3830 - 10s - 3ms/step - ia: 0.2498 - loss: 1.5964 - mae: 0.9483 - rmse: 1.1900 - smape: 1.6037 - val_ia: 0.1721 - val_loss: 1.1094 - val_mae: 0.8286 - val_rmse: 0.8698 - val_smape: 1.7442

Epoch 6/128

3830/3830 - 7s - 2ms/step - ia: 0.2525 - loss: 1.5248 - mae: 0.9326 - rmse: 1.1661 - smape: 1.6021 - val_ia: 0.1733 - val_loss: 1.0913 - val_mae: 0.8185 - val_rmse: 0.8595 - val_smape: 1.7481

Epoch 7/128

3830/3830 - 10s - 3ms/step - ia: 0.2521 - loss: 1.5052 - mae: 0.9197 - rmse: 1.1533 - smape: 1.6031 - val_ia: 0.1745 - val_loss: 1.0758 - val_mae: 0.8099 - val_rmse: 0.8507 - val_smape: 1.7509

Epoch 8/128

3830/3830 - 10s - 3ms/step - ia: 0.2495 - loss: 1.4846 - mae: 0.9148 - rmse: 1.1455 - smape: 1.6100 - val_ia: 0.1757 - val_loss: 1.0624 - val_mae: 0.8022 - val_rmse: 0.8429 - val_smape: 1.7528

Epoch 9/128

3830/3830 - 10s - 3ms/step - ia: 0.2541 - loss: 1.4324 - mae: 0.8964 - rmse: 1.1227 - smape: 1.5969 - val_ia: 0.1768 - val_loss: 1.0507 - val_mae: 0.7952 - val_rmse: 0.8358 - val_smape: 1.7541

Epoch 10/128

3830/3830 - 9s - 2ms/step - ia: 0.2511 - loss: 1.4141 - mae: 0.8921 - rmse: 1.1173 - smape: 1.6044 - val_ia: 0.1778 - val_loss: 1.0404 - val_mae: 0.7890 - val_rmse: 0.8296 - val_smape: 1.7535

Epoch 11/128

3830/3830 - 10s - 3ms/step - ia: 0.2541 - loss: 1.3693 - mae: 0.8805 - rmse: 1.1011 - smape: 1.6051 - val_ia: 0.1786 - val_loss: 1.0312 - val_mae: 0.7834 - val_rmse: 0.8238 - val_smape: 1.7524

Epoch 12/128

3830/3830 - 22s - 6ms/step - ia: 0.2550 - loss: 1.3509 - mae: 0.8717 - rmse: 1.0913 - smape: 1.5958 - val_ia: 0.1793 - val_loss: 1.0230 - val_mae: 0.7783 - val_rmse: 0.8187 - val_smape: 1.7510

Epoch 13/128

3830/3830 - 9s - 2ms/step - ia: 0.2545 - loss: 1.3278 - mae: 0.8643 - rmse: 1.0819 - smape: 1.6015 - val_ia: 0.1799 - val_loss: 1.0156 - val_mae: 0.7737 - val_rmse: 0.8139 - val_smape: 1.7505

Epoch 14/128

3830/3830 - 13s - 4ms/step - ia: 0.2543 - loss: 1.3077 - mae: 0.8596 - rmse: 1.0754 - smape: 1.5989 - val_ia: 0.1805 - val_loss: 1.0090 - val_mae: 0.7696 - val_rmse: 0.8097 - val_smape: 1.7501

Epoch 15/128

3830/3830 - 19s - 5ms/step - ia: 0.2560 - loss: 1.2895 - mae: 0.8545 - rmse: 1.0675 - smape: 1.6007 - val_ia: 0.1810 - val_loss: 1.0029 - val_mae: 0.7656 - val_rmse: 0.8057 - val_smape: 1.7494

Epoch 16/128

3830/3830 - 11s - 3ms/step - ia: 0.2564 - loss: 1.2844 - mae: 0.8496 - rmse: 1.0642 - smape: 1.6003 - val_ia: 0.1816 - val_loss: 0.9975 - val_mae: 0.7621 - val_rmse: 0.8021 - val_smape: 1.7483

Epoch 17/128

3830/3830 - 11s - 3ms/step - ia: 0.2531 - loss: 1.2711 - mae: 0.8462 - rmse: 1.0589 - smape: 1.5989 - val_ia: 0.1822 - val_loss: 0.9926 - val_mae: 0.7588 - val_rmse: 0.7988 - val_smape: 1.7468

Epoch 18/128

3830/3830 - 13s - 3ms/step - ia: 0.2556 - loss: 1.2378 - mae: 0.8368 - rmse: 1.0469 - smape: 1.5982 - val_ia: 0.1828 - val_loss: 0.9884 - val_mae: 0.7560 - val_rmse: 0.7959 - val_smape: 1.7455

Epoch 19/128

3830/3830 - 11s - 3ms/step - ia: 0.2579 - loss: 1.2440 - mae: 0.8357 - rmse: 1.0470 - smape: 1.5943 - val_ia: 0.1833 - val_loss: 0.9844 - val_mae: 0.7533 - val_rmse: 0.7932 - val_smape: 1.7437

Epoch 20/128

3830/3830 - 22s - 6ms/step - ia: 0.2535 - loss: 1.2272 - mae: 0.8331 - rmse: 1.0414 - smape: 1.6029 - val_ia: 0.1837 - val_loss: 0.9806 - val_mae: 0.7508 - val_rmse: 0.7906 - val_smape: 1.7427

Epoch 21/128

3830/3830 - 12s - 3ms/step - ia: 0.2556 - loss: 1.2189 - mae: 0.8271 - rmse: 1.0361 - smape: 1.5975 - val_ia: 0.1842 - val_loss: 0.9769 - val_mae: 0.7484 - val_rmse: 0.7881 - val_smape: 1.7414

Epoch 22/128

3830/3830 - 11s - 3ms/step - ia: 0.2522 - loss: 1.2068 - mae: 0.8264 - rmse: 1.0316 - smape: 1.6029 - val_ia: 0.1845 - val_loss: 0.9744 - val_mae: 0.7465 - val_rmse: 0.7862 - val_smape: 1.7407

Epoch 23/128

3830/3830 - 9s - 2ms/step - ia: 0.2556 - loss: 1.1953 - mae: 0.8200 - rmse: 1.0261 - smape: 1.6025 - val_ia: 0.1849 - val_loss: 0.9711 - val_mae: 0.7444 - val_rmse: 0.7840 - val_smape: 1.7389

Epoch 24/128

3830/3830 - 11s - 3ms/step - ia: 0.2534 - loss: 1.1959 - mae: 0.8184 - rmse: 1.0255 - smape: 1.6024 - val_ia: 0.1852 - val_loss: 0.9687 - val_mae: 0.7428 - val_rmse: 0.7824 - val_smape: 1.7381

Epoch 25/128

3830/3830 - 21s - 5ms/step - ia: 0.2550 - loss: 1.1712 - mae: 0.8123 - rmse: 1.0159 - smape: 1.5998 - val_ia: 0.1855 - val_loss: 0.9662 - val_mae: 0.7412 - val_rmse: 0.7807 - val_smape: 1.7365

Epoch 26/128

3830/3830 - 11s - 3ms/step - ia: 0.2559 - loss: 1.1708 - mae: 0.8099 - rmse: 1.0147 - smape: 1.5991 - val_ia: 0.1859 - val_loss: 0.9639 - val_mae: 0.7396 - val_rmse: 0.7790 - val_smape: 1.7348

Epoch 27/128

3830/3830 - 11s - 3ms/step - ia: 0.2527 - loss: 1.1683 - mae: 0.8102 - rmse: 1.0129 - smape: 1.6087 - val_ia: 0.1862 - val_loss: 0.9615 - val_mae: 0.7381 - val_rmse: 0.7774 - val_smape: 1.7334

Epoch 28/128

3830/3830 - 20s - 5ms/step - ia: 0.2568 - loss: 1.1552 - mae: 0.8046 - rmse: 1.0066 - smape: 1.6049 - val_ia: 0.1864 - val_loss: 0.9599 - val_mae: 0.7370 - val_rmse: 0.7763 - val_smape: 1.7327

Epoch 29/128

3830/3830 - 21s - 6ms/step - ia: 0.2566 - loss: 1.1412 - mae: 0.8000 - rmse: 1.0019 - smape: 1.6048 - val_ia: 0.1866 - val_loss: 0.9582 - val_mae: 0.7358 - val_rmse: 0.7750 - val_smape: 1.7321

Epoch 30/128

3830/3830 - 20s - 5ms/step - ia: 0.2527 - loss: 1.1339 - mae: 0.8000 - rmse: 0.9991 - smape: 1.6088 - val_ia: 0.1869 - val_loss: 0.9563 - val_mae: 0.7346 - val_rmse: 0.7738 - val_smape: 1.7309

Epoch 31/128

3830/3830 - 10s - 3ms/step - ia: 0.2550 - loss: 1.1326 - mae: 0.7988 - rmse: 0.9987 - smape: 1.6061 - val_ia: 0.1871 - val_loss: 0.9543 - val_mae: 0.7335 - val_rmse: 0.7726 - val_smape: 1.7300

Epoch 32/128

3830/3830 - 10s - 3ms/step - ia: 0.2546 - loss: 1.1324 - mae: 0.7974 - rmse: 0.9955 - smape: 1.6112 - val_ia: 0.1872 - val_loss: 0.9528 - val_mae: 0.7325 - val_rmse: 0.7716 - val_smape: 1.7290

Epoch 33/128

3830/3830 - 9s - 2ms/step - ia: 0.2572 - loss: 1.1237 - mae: 0.7921 - rmse: 0.9936 - smape: 1.6033 - val_ia: 0.1874 - val_loss: 0.9513 - val_mae: 0.7316 - val_rmse: 0.7706 - val_smape: 1.7280

Epoch 34/128

3830/3830 - 11s - 3ms/step - ia: 0.2522 - loss: 1.1286 - mae: 0.7942 - rmse: 0.9951 - smape: 1.6114 - val_ia: 0.1876 - val_loss: 0.9498 - val_mae: 0.7307 - val_rmse: 0.7696 - val_smape: 1.7271

Epoch 35/128

3830/3830 - 12s - 3ms/step - ia: 0.2546 - loss: 1.1070 - mae: 0.7896 - rmse: 0.9856 - smape: 1.6138 - val_ia: 0.1877 - val_loss: 0.9484 - val_mae: 0.7300 - val_rmse: 0.7688 - val_smape: 1.7263

Epoch 36/128

3830/3830 - 11s - 3ms/step - ia: 0.2534 - loss: 1.1101 - mae: 0.7884 - rmse: 0.9878 - smape: 1.6128 - val_ia: 0.1878 - val_loss: 0.9471 - val_mae: 0.7292 - val_rmse: 0.7680 - val_smape: 1.7255

Epoch 37/128

3830/3830 - 12s - 3ms/step - ia: 0.2532 - loss: 1.1040 - mae: 0.7871 - rmse: 0.9837 - smape: 1.6168 - val_ia: 0.1879 - val_loss: 0.9458 - val_mae: 0.7285 - val_rmse: 0.7673 - val_smape: 1.7246

Epoch 38/128

3830/3830 - 12s - 3ms/step - ia: 0.2533 - loss: 1.0997 - mae: 0.7842 - rmse: 0.9805 - smape: 1.6162 - val_ia: 0.1880 - val_loss: 0.9449 - val_mae: 0.7281 - val_rmse: 0.7667 - val_smape: 1.7247

Epoch 39/128

3830/3830 - 12s - 3ms/step - ia: 0.2518 - loss: 1.0910 - mae: 0.7821 - rmse: 0.9802 - smape: 1.6139 - val_ia: 0.1881 - val_loss: 0.9435 - val_mae: 0.7275 - val_rmse: 0.7661 - val_smape: 1.7240

Epoch 40/128

3830/3830 - 13s - 3ms/step - ia: 0.2539 - loss: 1.0843 - mae: 0.7803 - rmse: 0.9741 - smape: 1.6193 - val_ia: 0.1882 - val_loss: 0.9424 - val_mae: 0.7270 - val_rmse: 0.7655 - val_smape: 1.7231

Epoch 41/128

3830/3830 - 19s - 5ms/step - ia: 0.2537 - loss: 1.0847 - mae: 0.7803 - rmse: 0.9760 - smape: 1.6207 - val_ia: 0.1883 - val_loss: 0.9414 - val_mae: 0.7266 - val_rmse: 0.7651 - val_smape: 1.7230

Epoch 42/128

3830/3830 - 20s - 5ms/step - ia: 0.2551 - loss: 1.0730 - mae: 0.7753 - rmse: 0.9692 - smape: 1.6179 - val_ia: 0.1883 - val_loss: 0.9406 - val_mae: 0.7262 - val_rmse: 0.7647 - val_smape: 1.7231

Epoch 43/128

3830/3830 - 12s - 3ms/step - ia: 0.2502 - loss: 1.0891 - mae: 0.7793 - rmse: 0.9746 - smape: 1.6237 - val_ia: 0.1884 - val_loss: 0.9400 - val_mae: 0.7259 - val_rmse: 0.7643 - val_smape: 1.7235

Epoch 44/128

3830/3830 - 11s - 3ms/step - ia: 0.2524 - loss: 1.0754 - mae: 0.7767 - rmse: 0.9700 - smape: 1.6247 - val_ia: 0.1884 - val_loss: 0.9392 - val_mae: 0.7256 - val_rmse: 0.7640 - val_smape: 1.7239

Epoch 45/128

3830/3830 - 21s - 6ms/step - ia: 0.2524 - loss: 1.0694 - mae: 0.7741 - rmse: 0.9673 - smape: 1.6250 - val_ia: 0.1884 - val_loss: 0.9384 - val_mae: 0.7254 - val_rmse: 0.7637 - val_smape: 1.7241

Epoch 46/128

3830/3830 - 12s - 3ms/step - ia: 0.2495 - loss: 1.0717 - mae: 0.7757 - rmse: 0.9690 - smape: 1.6291 - val_ia: 0.1884 - val_loss: 0.9375 - val_mae: 0.7250 - val_rmse: 0.7633 - val_smape: 1.7236

Epoch 47/128

3830/3830 - 12s - 3ms/step - ia: 0.2521 - loss: 1.0644 - mae: 0.7723 - rmse: 0.9648 - smape: 1.6296 - val_ia: 0.1885 - val_loss: 0.9366 - val_mae: 0.7247 - val_rmse: 0.7629 - val_smape: 1.7227

Epoch 48/128

3830/3830 - 22s - 6ms/step - ia: 0.2505 - loss: 1.0680 - mae: 0.7737 - rmse: 0.9674 - smape: 1.6296 - val_ia: 0.1886 - val_loss: 0.9356 - val_mae: 0.7243 - val_rmse: 0.7624 - val_smape: 1.7217

Epoch 49/128

3830/3830 - 12s - 3ms/step - ia: 0.2490 - loss: 1.0765 - mae: 0.7744 - rmse: 0.9691 - smape: 1.6341 - val_ia: 0.1886 - val_loss: 0.9351 - val_mae: 0.7241 - val_rmse: 0.7622 - val_smape: 1.7222

Epoch 50/128

3830/3830 - 12s - 3ms/step - ia: 0.2489 - loss: 1.0639 - mae: 0.7727 - rmse: 0.9642 - smape: 1.6349 - val_ia: 0.1886 - val_loss: 0.9343 - val_mae: 0.7238 - val_rmse: 0.7619 - val_smape: 1.7221

Epoch 51/128

3830/3830 - 10s - 3ms/step - ia: 0.2501 - loss: 1.0496 - mae: 0.7665 - rmse: 0.9582 - smape: 1.6308 - val_ia: 0.1887 - val_loss: 0.9333 - val_mae: 0.7236 - val_rmse: 0.7616 - val_smape: 1.7216

Epoch 52/128

3830/3830 - 11s - 3ms/step - ia: 0.2488 - loss: 1.0626 - mae: 0.7707 - rmse: 0.9642 - smape: 1.6386 - val_ia: 0.1887 - val_loss: 0.9326 - val_mae: 0.7234 - val_rmse: 0.7614 - val_smape: 1.7211

Epoch 53/128

3830/3830 - 12s - 3ms/step - ia: 0.2495 - loss: 1.0529 - mae: 0.7673 - rmse: 0.9594 - smape: 1.6363 - val_ia: 0.1887 - val_loss: 0.9322 - val_mae: 0.7232 - val_rmse: 0.7612 - val_smape: 1.7218

Epoch 54/128

3830/3830 - 11s - 3ms/step - ia: 0.2501 - loss: 1.0507 - mae: 0.7660 - rmse: 0.9582 - smape: 1.6402 - val_ia: 0.1887 - val_loss: 0.9315 - val_mae: 0.7230 - val_rmse: 0.7609 - val_smape: 1.7216

Epoch 55/128

3830/3830 - 20s - 5ms/step - ia: 0.2515 - loss: 1.0422 - mae: 0.7644 - rmse: 0.9549 - smape: 1.6357 - val_ia: 0.1888 - val_loss: 0.9306 - val_mae: 0.7227 - val_rmse: 0.7606 - val_smape: 1.7211

Epoch 56/128

3830/3830 - 11s - 3ms/step - ia: 0.2468 - loss: 1.0498 - mae: 0.7686 - rmse: 0.9587 - smape: 1.6456 - val_ia: 0.1888 - val_loss: 0.9301 - val_mae: 0.7226 - val_rmse: 0.7605 - val_smape: 1.7213

Epoch 57/128

3830/3830 - 8s - 2ms/step - ia: 0.2488 - loss: 1.0419 - mae: 0.7640 - rmse: 0.9543 - smape: 1.6404 - val_ia: 0.1888 - val_loss: 0.9291 - val_mae: 0.7225 - val_rmse: 0.7602 - val_smape: 1.7211

Epoch 58/128

3830/3830 - 9s - 2ms/step - ia: 0.2491 - loss: 1.0454 - mae: 0.7644 - rmse: 0.9545 - smape: 1.6417 - val_ia: 0.1888 - val_loss: 0.9285 - val_mae: 0.7224 - val_rmse: 0.7601 - val_smape: 1.7215

Epoch 59/128

3830/3830 - 8s - 2ms/step - ia: 0.2509 - loss: 1.0431 - mae: 0.7641 - rmse: 0.9542 - smape: 1.6443 - val_ia: 0.1888 - val_loss: 0.9278 - val_mae: 0.7223 - val_rmse: 0.7600 - val_smape: 1.7219

Epoch 60/128

3830/3830 - 8s - 2ms/step - ia: 0.2475 - loss: 1.0420 - mae: 0.7655 - rmse: 0.9534 - smape: 1.6522 - val_ia: 0.1888 - val_loss: 0.9271 - val_mae: 0.7222 - val_rmse: 0.7599 - val_smape: 1.7222

Epoch 61/128

3830/3830 - 10s - 3ms/step - ia: 0.2475 - loss: 1.0433 - mae: 0.7634 - rmse: 0.9551 - smape: 1.6476 - val_ia: 0.1888 - val_loss: 0.9265 - val_mae: 0.7220 - val_rmse: 0.7597 - val_smape: 1.7223

Epoch 62/128

3830/3830 - 11s - 3ms/step - ia: 0.2458 - loss: 1.0439 - mae: 0.7655 - rmse: 0.9551 - smape: 1.6509 - val_ia: 0.1888 - val_loss: 0.9259 - val_mae: 0.7219 - val_rmse: 0.7595 - val_smape: 1.7224

Epoch 63/128

3830/3830 - 8s - 2ms/step - ia: 0.2504 - loss: 1.0311 - mae: 0.7603 - rmse: 0.9480 - smape: 1.6459 - val_ia: 0.1888 - val_loss: 0.9253 - val_mae: 0.7217 - val_rmse: 0.7593 - val_smape: 1.7225

Epoch 64/128

3830/3830 - 8s - 2ms/step - ia: 0.2512 - loss: 1.0312 - mae: 0.7595 - rmse: 0.9486 - smape: 1.6468 - val_ia: 0.1888 - val_loss: 0.9246 - val_mae: 0.7216 - val_rmse: 0.7592 - val_smape: 1.7227

Epoch 65/128

3830/3830 - 8s - 2ms/step - ia: 0.2465 - loss: 1.0304 - mae: 0.7607 - rmse: 0.9479 - smape: 1.6508 - val_ia: 0.1888 - val_loss: 0.9239 - val_mae: 0.7215 - val_rmse: 0.7590 - val_smape: 1.7227

Epoch 66/128

3830/3830 - 7s - 2ms/step - ia: 0.2467 - loss: 1.0326 - mae: 0.7603 - rmse: 0.9475 - smape: 1.6512 - val_ia: 0.1888 - val_loss: 0.9232 - val_mae: 0.7213 - val_rmse: 0.7588 - val_smape: 1.7225

Epoch 67/128

3830/3830 - 8s - 2ms/step - ia: 0.2450 - loss: 1.0259 - mae: 0.7591 - rmse: 0.9471 - smape: 1.6516 - val_ia: 0.1888 - val_loss: 0.9224 - val_mae: 0.7212 - val_rmse: 0.7586 - val_smape: 1.7223

Epoch 68/128

3830/3830 - 7s - 2ms/step - ia: 0.2469 - loss: 1.0260 - mae: 0.7584 - rmse: 0.9464 - smape: 1.6537 - val_ia: 0.1888 - val_loss: 0.9218 - val_mae: 0.7211 - val_rmse: 0.7585 - val_smape: 1.7220

Epoch 69/128

3830/3830 - 8s - 2ms/step - ia: 0.2437 - loss: 1.0356 - mae: 0.7609 - rmse: 0.9513 - smape: 1.6550 - val_ia: 0.1888 - val_loss: 0.9215 - val_mae: 0.7210 - val_rmse: 0.7584 - val_smape: 1.7224

Epoch 70/128

3830/3830 - 9s - 2ms/step - ia: 0.2492 - loss: 1.0199 - mae: 0.7559 - rmse: 0.9427 - smape: 1.6516 - val_ia: 0.1888 - val_loss: 0.9207 - val_mae: 0.7209 - val_rmse: 0.7582 - val_smape: 1.7225

Epoch 71/128

3830/3830 - 8s - 2ms/step - ia: 0.2454 - loss: 1.0212 - mae: 0.7587 - rmse: 0.9461 - smape: 1.6612 - val_ia: 0.1888 - val_loss: 0.9198 - val_mae: 0.7208 - val_rmse: 0.7580 - val_smape: 1.7222

Epoch 72/128

3830/3830 - 9s - 2ms/step - ia: 0.2465 - loss: 1.0249 - mae: 0.7586 - rmse: 0.9466 - smape: 1.6579 - val_ia: 0.1888 - val_loss: 0.9191 - val_mae: 0.7206 - val_rmse: 0.7579 - val_smape: 1.7220

Epoch 73/128

3830/3830 - 10s - 3ms/step - ia: 0.2464 - loss: 1.0260 - mae: 0.7579 - rmse: 0.9453 - smape: 1.6568 - val_ia: 0.1888 - val_loss: 0.9188 - val_mae: 0.7205 - val_rmse: 0.7578 - val_smape: 1.7222

Epoch 74/128

3830/3830 - 8s - 2ms/step - ia: 0.2436 - loss: 1.0233 - mae: 0.7593 - rmse: 0.9467 - smape: 1.6632 - val_ia: 0.1888 - val_loss: 0.9182 - val_mae: 0.7204 - val_rmse: 0.7576 - val_smape: 1.7223

Epoch 75/128

3830/3830 - 8s - 2ms/step - ia: 0.2475 - loss: 1.0196 - mae: 0.7567 - rmse: 0.9433 - smape: 1.6603 - val_ia: 0.1888 - val_loss: 0.9173 - val_mae: 0.7203 - val_rmse: 0.7575 - val_smape: 1.7218

Epoch 76/128

3830/3830 - 8s - 2ms/step - ia: 0.2472 - loss: 1.0138 - mae: 0.7549 - rmse: 0.9418 - smape: 1.6577 - val_ia: 0.1888 - val_loss: 0.9168 - val_mae: 0.7202 - val_rmse: 0.7574 - val_smape: 1.7222

Epoch 77/128

3830/3830 - 8s - 2ms/step - ia: 0.2414 - loss: 1.0232 - mae: 0.7574 - rmse: 0.9454 - smape: 1.6651 - val_ia: 0.1888 - val_loss: 0.9162 - val_mae: 0.7202 - val_rmse: 0.7573 - val_smape: 1.7223

Epoch 78/128

3830/3830 - 11s - 3ms/step - ia: 0.2442 - loss: 1.0177 - mae: 0.7558 - rmse: 0.9434 - smape: 1.6602 - val_ia: 0.1888 - val_loss: 0.9156 - val_mae: 0.7201 - val_rmse: 0.7572 - val_smape: 1.7222

Epoch 79/128

3830/3830 - 8s - 2ms/step - ia: 0.2460 - loss: 1.0108 - mae: 0.7549 - rmse: 0.9415 - smape: 1.6616 - val_ia: 0.1888 - val_loss: 0.9148 - val_mae: 0.7199 - val_rmse: 0.7570 - val_smape: 1.7216

Epoch 80/128

3830/3830 - 7s - 2ms/step - ia: 0.2471 - loss: 1.0144 - mae: 0.7555 - rmse: 0.9413 - smape: 1.6612 - val_ia: 0.1888 - val_loss: 0.9143 - val_mae: 0.7198 - val_rmse: 0.7569 - val_smape: 1.7217

Epoch 81/128

3830/3830 - 9s - 2ms/step - ia: 0.2457 - loss: 1.0114 - mae: 0.7545 - rmse: 0.9411 - smape: 1.6603 - val_ia: 0.1888 - val_loss: 0.9136 - val_mae: 0.7198 - val_rmse: 0.7568 - val_smape: 1.7216

Epoch 82/128

3830/3830 - 10s - 3ms/step - ia: 0.2450 - loss: 1.0087 - mae: 0.7541 - rmse: 0.9397 - smape: 1.6655 - val_ia: 0.1887 - val_loss: 0.9129 - val_mae: 0.7197 - val_rmse: 0.7566 - val_smape: 1.7212

Epoch 83/128

3830/3830 - 9s - 2ms/step - ia: 0.2451 - loss: 1.0106 - mae: 0.7554 - rmse: 0.9417 - smape: 1.6693 - val_ia: 0.1887 - val_loss: 0.9121 - val_mae: 0.7196 - val_rmse: 0.7565 - val_smape: 1.7210

Epoch 84/128

3830/3830 - 9s - 2ms/step - ia: 0.2451 - loss: 1.0094 - mae: 0.7533 - rmse: 0.9379 - smape: 1.6649 - val_ia: 0.1887 - val_loss: 0.9117 - val_mae: 0.7195 - val_rmse: 0.7564 - val_smape: 1.7211

Epoch 85/128

3830/3830 - 8s - 2ms/step - ia: 0.2464 - loss: 1.0063 - mae: 0.7526 - rmse: 0.9375 - smape: 1.6645 - val_ia: 0.1887 - val_loss: 0.9110 - val_mae: 0.7194 - val_rmse: 0.7563 - val_smape: 1.7212

Epoch 86/128

3830/3830 - 8s - 2ms/step - ia: 0.2443 - loss: 1.0081 - mae: 0.7530 - rmse: 0.9386 - smape: 1.6637 - val_ia: 0.1887 - val_loss: 0.9106 - val_mae: 0.7194 - val_rmse: 0.7563 - val_smape: 1.7215

Epoch 87/128

3830/3830 - 9s - 2ms/step - ia: 0.2487 - loss: 1.0013 - mae: 0.7518 - rmse: 0.9359 - smape: 1.6642 - val_ia: 0.1887 - val_loss: 0.9098 - val_mae: 0.7192 - val_rmse: 0.7561 - val_smape: 1.7208

Epoch 88/128

3830/3830 - 7s - 2ms/step - ia: 0.2437 - loss: 1.0074 - mae: 0.7553 - rmse: 0.9373 - smape: 1.6739 - val_ia: 0.1887 - val_loss: 0.9092 - val_mae: 0.7191 - val_rmse: 0.7560 - val_smape: 1.7205

Epoch 89/128

3830/3830 - 7s - 2ms/step - ia: 0.2481 - loss: 1.0040 - mae: 0.7518 - rmse: 0.9377 - smape: 1.6692 - val_ia: 0.1887 - val_loss: 0.9086 - val_mae: 0.7190 - val_rmse: 0.7558 - val_smape: 1.7201

Epoch 90/128

3830/3830 - 7s - 2ms/step - ia: 0.2463 - loss: 1.0032 - mae: 0.7521 - rmse: 0.9389 - smape: 1.6660 - val_ia: 0.1887 - val_loss: 0.9078 - val_mae: 0.7189 - val_rmse: 0.7557 - val_smape: 1.7194

Epoch 91/128

3830/3830 - 7s - 2ms/step - ia: 0.2454 - loss: 0.9987 - mae: 0.7508 - rmse: 0.9348 - smape: 1.6640 - val_ia: 0.1887 - val_loss: 0.9070 - val_mae: 0.7187 - val_rmse: 0.7555 - val_smape: 1.7188

Epoch 92/128

3830/3830 - 7s - 2ms/step - ia: 0.2471 - loss: 1.0086 - mae: 0.7528 - rmse: 0.9393 - smape: 1.6695 - val_ia: 0.1887 - val_loss: 0.9067 - val_mae: 0.7186 - val_rmse: 0.7554 - val_smape: 1.7188

Epoch 93/128

3830/3830 - 7s - 2ms/step - ia: 0.2470 - loss: 1.0005 - mae: 0.7507 - rmse: 0.9352 - smape: 1.6648 - val_ia: 0.1887 - val_loss: 0.9061 - val_mae: 0.7185 - val_rmse: 0.7553 - val_smape: 1.7184

Epoch 94/128

3830/3830 - 7s - 2ms/step - ia: 0.2475 - loss: 0.9944 - mae: 0.7494 - rmse: 0.9335 - smape: 1.6654 - val_ia: 0.1886 - val_loss: 0.9054 - val_mae: 0.7184 - val_rmse: 0.7551 - val_smape: 1.7181

Epoch 95/128

3830/3830 - 7s - 2ms/step - ia: 0.2487 - loss: 1.0005 - mae: 0.7505 - rmse: 0.9350 - smape: 1.6680 - val_ia: 0.1886 - val_loss: 0.9048 - val_mae: 0.7182 - val_rmse: 0.7550 - val_smape: 1.7172

Epoch 96/128

3830/3830 - 10s - 3ms/step - ia: 0.2453 - loss: 0.9899 - mae: 0.7491 - rmse: 0.9323 - smape: 1.6686 - val_ia: 0.1886 - val_loss: 0.9040 - val_mae: 0.7181 - val_rmse: 0.7548 - val_smape: 1.7170

Epoch 97/128


c:\Users\wamt1\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

Epoch 1/128

240/240 - 3s - 14ms/step - ia: 0.3726 - loss: 0.9955 - mae: 0.7475 - rmse: 0.9923 - smape: 1.3176 - val_ia: 0.3279 - val_loss: 0.7737 - val_mae: 0.6497 - val_rmse: 0.7975 - val_smape: 1.2757

Epoch 2/128

240/240 - 1s - 3ms/step - ia: 0.3878 - loss: 0.9439 - mae: 0.7263 - rmse: 0.9670 - smape: 1.2997 - val_ia: 0.3292 - val_loss: 0.7576 - val_mae: 0.6409 - val_rmse: 0.7871 - val_smape: 1.2604

Epoch 3/128

240/240 - 1s - 2ms/step - ia: 0.3941 - loss: 0.9062 - mae: 0.7101 - rmse: 0.9472 - smape: 1.2882 - val_ia: 0.3295 - val_loss: 0.7593 - val_mae: 0.6441 - val_rmse: 0.7888 - val_smape: 1.2845

Epoch 4/128

240/240 - 1s - 2ms/step - ia: 0.3916 - loss: 0.8974 - mae: 0.7064 - rmse: 0.9420 - smape: 1.2908 - val_ia: 0.3312 - val_loss: 0.7549 - val_mae: 0.6444 - val_rmse: 0.7891 - val_smape: 1.2687

Epoch 5/128

240/240 - 1s - 3ms/step - ia: 0.3949 - loss: 0.8813 - mae: 0.6972 - rmse: 0.9329 - smape: 1.2865 - val_ia: 0.3261 - val_loss: 0.7548 - val_mae: 0.6420 - val_rmse: 0.7862 - val_smape: 1.2752

Epoch 6/128

240/240 - 1s - 2ms/step - ia: 0.3946 - loss: 0.8711 - mae: 0.6907 - rmse: 0.9279 - smape: 1.2828 - val_ia: 0.3244 - val_loss: 0.7547 - val_mae: 0.6457 - val_rmse: 0.7885 - val_smape: 1.2811

Epoch 7/128

240/240 - 1s - 3ms/step - ia: 0.3934 - loss: 0.8593 - mae: 0.6873 - rmse: 0.9223 - smape: 1.2860 - val_ia: 0.3256 - val_loss: 0.7635 - val_mae: 0.6488 - val_rmse: 0.7938 - val_smape: 1.2918

Epoch 8/128

240/240 - 1s - 3ms/step - ia: 0.3955 - loss: 0.8500 - mae: 0.6818 - rmse: 0.9178 - smape: 1.2788 - val_ia: 0.3274 - val_loss: 0.7493 - val_mae: 0.6356 - val_rmse: 0.7809 - val_smape: 1.2529

Epoch 9/128

240/240 - 1s - 3ms/step - ia: 0.3948 - loss: 0.8438 - mae: 0.6783 - rmse: 0.9147 - smape: 1.2803 - val_ia: 0.3291 - val_loss: 0.7505 - val_mae: 0.6355 - val_rmse: 0.7811 - val_smape: 1.2569

Epoch 10/128

240/240 - 1s - 2ms/step - ia: 0.3958 - loss: 0.8363 - mae: 0.6752 - rmse: 0.9101 - smape: 1.2784 - val_ia: 0.3286 - val_loss: 0.7529 - val_mae: 0.6424 - val_rmse: 0.7870 - val_smape: 1.2685

Epoch 11/128

240/240 - 1s - 3ms/step - ia: 0.3947 - loss: 0.8352 - mae: 0.6749 - rmse: 0.9092 - smape: 1.2784 - val_ia: 0.3267 - val_loss: 0.7469 - val_mae: 0.6346 - val_rmse: 0.7793 - val_smape: 1.2526

Epoch 12/128

240/240 - 1s - 2ms/step - ia: 0.3930 - loss: 0.8296 - mae: 0.6720 - rmse: 0.9060 - smape: 1.2797 - val_ia: 0.3347 - val_loss: 0.7596 - val_mae: 0.6410 - val_rmse: 0.7892 - val_smape: 1.2680

Epoch 13/128

240/240 - 1s - 3ms/step - ia: 0.3946 - loss: 0.8273 - mae: 0.6705 - rmse: 0.9054 - smape: 1.2769 - val_ia: 0.3255 - val_loss: 0.7637 - val_mae: 0.6537 - val_rmse: 0.7977 - val_smape: 1.2962

Epoch 14/128

240/240 - 1s - 3ms/step - ia: 0.3951 - loss: 0.8207 - mae: 0.6685 - rmse: 0.9009 - smape: 1.2778 - val_ia: 0.3318 - val_loss: 0.7498 - val_mae: 0.6337 - val_rmse: 0.7810 - val_smape: 1.2445

Epoch 15/128

240/240 - 1s - 3ms/step - ia: 0.3967 - loss: 0.8189 - mae: 0.6669 - rmse: 0.8989 - smape: 1.2756 - val_ia: 0.3285 - val_loss: 0.7589 - val_mae: 0.6479 - val_rmse: 0.7933 - val_smape: 1.2829

Epoch 16/128

240/240 - 1s - 3ms/step - ia: 0.3978 - loss: 0.8168 - mae: 0.6656 - rmse: 0.8996 - smape: 1.2715 - val_ia: 0.3279 - val_loss: 0.7540 - val_mae: 0.6440 - val_rmse: 0.7888 - val_smape: 1.2727

Epoch 17/128

240/240 - 1s - 3ms/step - ia: 0.3973 - loss: 0.8134 - mae: 0.6642 - rmse: 0.8969 - smape: 1.2715 - val_ia: 0.3284 - val_loss: 0.7539 - val_mae: 0.6438 - val_rmse: 0.7889 - val_smape: 1.2692

Epoch 18/128

240/240 - 1s - 3ms/step - ia: 0.3973 - loss: 0.8142 - mae: 0.6650 - rmse: 0.8970 - smape: 1.2728 - val_ia: 0.3298 - val_loss: 0.7641 - val_mae: 0.6505 - val_rmse: 0.7973 - val_smape: 1.2886

Epoch 19/128

240/240 - 1s - 2ms/step - ia: 0.3992 - loss: 0.8126 - mae: 0.6633 - rmse: 0.8955 - smape: 1.2684 - val_ia: 0.3292 - val_loss: 0.7568 - val_mae: 0.6402 - val_rmse: 0.7866 - val_smape: 1.2756

Epoch 20/128

240/240 - 1s - 2ms/step - ia: 0.3972 - loss: 0.8083 - mae: 0.6623 - rmse: 0.8939 - smape: 1.2709 - val_ia: 0.3321 - val_loss: 0.7574 - val_mae: 0.6422 - val_rmse: 0.7902 - val_smape: 1.2621

Epoch 21/128

240/240 - 1s - 3ms/step - ia: 0.4002 - loss: 0.8095 - mae: 0.6619 - rmse: 0.8945 - smape: 1.2665 - val_ia: 0.3312 - val_loss: 0.7508 - val_mae: 0.6369 - val_rmse: 0.7839 - val_smape: 1.2537

Epoch 22/128

240/240 - 1s - 5ms/step - ia: 0.4008 - loss: 0.8056 - mae: 0.6596 - rmse: 0.8925 - smape: 1.2671 - val_ia: 0.3321 - val_loss: 0.7622 - val_mae: 0.6476 - val_rmse: 0.7956 - val_smape: 1.2774

Epoch 23/128

240/240 - 1s - 3ms/step - ia: 0.4014 - loss: 0.8069 - mae: 0.6604 - rmse: 0.8925 - smape: 1.2669 - val_ia: 0.3316 - val_loss: 0.7529 - val_mae: 0.6349 - val_rmse: 0.7828 - val_smape: 1.2520

Epoch 24/128

240/240 - 1s - 3ms/step - ia: 0.3993 - loss: 0.8061 - mae: 0.6606 - rmse: 0.8929 - smape: 1.2697 - val_ia: 0.3311 - val_loss: 0.7555 - val_mae: 0.6434 - val_rmse: 0.7903 - val_smape: 1.2672

Epoch 25/128

240/240 - 1s - 2ms/step - ia: 0.4018 - loss: 0.8032 - mae: 0.6591 - rmse: 0.8906 - smape: 1.2648 - val_ia: 0.3332 - val_loss: 0.7507 - val_mae: 0.6353 - val_rmse: 0.7833 - val_smape: 1.2494

Epoch 26/128

240/240 - 1s - 3ms/step - ia: 0.4028 - loss: 0.8029 - mae: 0.6584 - rmse: 0.8915 - smape: 1.2613 - val_ia: 0.3312 - val_loss: 0.7537 - val_mae: 0.6402 - val_rmse: 0.7875 - val_smape: 1.2626

Epoch 26: early stopping

Restoring model weights from the end of the best epoch: 11.

  1/136 ━━━━━━━━━━━━━━━━━━━━ 7s 57ms/step
 31/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
 74/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
113/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

100%|██████████| 12/12 [1:22:37<00:00, 413.11s/trial, best loss: 0.7718968131959658]
{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}

In [23]:
print(best)

{'activation': 3, 'batch': 1, 'dropout': 0.0, 'layers': 4.0, 'learning_rate': 0.00027101707182655693, 'units': 4}